### ISSUE TITLE
The System.Text.Json source generator doesn't populate `JsonPropertyInfo.AttributeProvider` metadata.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#100095]
The `JsonPropertyInfo.AttributeProvider` property isn't being populated by the source generator, making it impossible to resolve additional attributes from `JsonPropertyInfo` instances. This can create issues when mapping contract metadata to richer representations such as JSON schema (e.g. resolving `DescriptionAttribute`).

cc @captainsafia @stephentoub

**Comment by gregsdennis** [comment]
@eiriktsarpalis I'm interested how this could affect a JSON Schema representation.  Where does this come from?

**Comment by eiriktsarpalis** [comment]
@gregsdennis We want to be able to extract a JSON schema from the contract as specified in `JsonTypeInfo` instances. I'm working on a prototype for that [here](https://github.com/eiriktsarpalis/stj-schema-mapper) but at the moment we still need to fall back to reflection to extract some of the necessary information.

**Comment by gregsdennis** [comment]
Happy to talk about this more offline if you have the time.

**Comment by eiriktsarpalis** [comment]
Reopening, since apparently https://github.com/dotnet/runtime/pull/100173 doesn't fully address the issue for the case of trimmed/Native AOT applications. The fact that it's using delayed `MemberInfo` resolution means that we're not providing any hints to the linker that these attributes shouldn't be trimmed.

One potential solution (already trialed in typeshape-csharp) is adding a delayed factory for `ICustomAttributeProvider` declared in the `JsonPropertyInfoValues<T>` class used by the source generator:

```C#
namespace System.Text.Json.Serialization.Metadata;

public partial class JsonPropertyInfoValues<T>
{
    public Func<ICustomAttributeProvider>? CustomAttributeProviderFactory { get; init; }
}
```

which would be populated by the source generator as follows:

```C#
new JsonPropertyInfoValues<string>
{
    PropertyName = "Name",
    CustomAttributeProviderFactory = static () => typeof(Person).GetProperty("Name"),
};

public record Person(string Name);
```

This should provide the linker with sufficient hints so that metadata for the particular properties will not be trimmed.

**Comment by eiriktsarpalis** [comment]
Superceded by #102078.
