### ISSUE TITLE
/usr/share/dotnet/sdk/8.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### ISSUE THREAD

**Issue by janusqa** [dotnet/runtime#100026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to build Blazor Web App project due to error

/usr/share/dotnet/sdk/8.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### Expected Behavior

Project should build, or produce a suitable error message.

### .NET Version

8.0.202

### Anything else?

```
.NET SDK:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.a7f084b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.202/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  8.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

**Comment by maraf** [comment]
@janusqa Can you please build the app (or an plain app from blazor template if the error occurs there as well) with `-bl` (`dotnet build -bl`) and share a produced binlog?

**Comment by janusqa** [comment]
@maraf 
1. ```Does the error occur also on a plain app from blazor template?``` No it does not.
2. ```Can you please build with -bl (dotnet build -bl) and share a produced binlog?``` I'm unable to upload msbuild.binlog. Not a supported upload type here.

**Comment by maraf** [comment]
> I'm unable to upload msbuild.binlog. Not a supported upload type here.

You can zip it, please

**Comment by janusqa** [comment]
@maraf, I'm brain dead today, I could have zipped it and attached, which I just did.
I don't have a membership at developercommunity.

**Comment by scrocquesel-ml150** [comment]
@janusqa  8.0.203 is now listed on the repo

**Comment by maraf** [comment]
> @maraf, I'm brain dead today, I could have zipped it and attached, which I just did. I don't have a membership at developercommunity.

No rush. You can zip it and attach it here
