### ISSUE TITLE
System.Text.Json: `JsonUnmappedMemberHandling.Disallow` throws when using `JsonPolymorphicAttribute`

### ISSUE THREAD

**Issue by jhm-ciberman** [dotnet/runtime#100057]
### Description

The [JsonSerializerOptions.UnmappedMemberHandling](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.unmappedmemberhandling?view=net-8.0) is incompatible with [JsonPolymorphicAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpolymorphicattribute?view=net-8.0) or [JsonDerivedTypeAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonderivedtypeattribute?view=net-8.0). 

If we try to deserialize a polymorphic class that uses a type discriminator (e.g. `"$type": "myClass"`) and we activate the [JsonSerializerOptions.UnmappedMemberHandling](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.unmappedmemberhandling?view=net-8.0) to [JsonUnmappedMemberHandling.Disallow](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonunmappedmemberhandling?view=net-8.0), then the following exception is thrown:

```
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll: 'The JSON property '$type' could not be mapped to any .NET member contained in type 'MyPolymorphicClass'.
```

### Reproduction Steps

```csharp
[JsonPolymorphic]
[JsonDerivedType(typeof(MyCat), typeDiscriminator: "cat")]
[JsonDerivedType(typeof(MyDog), typeDiscriminator: "dog")]
public class MyAnimal
{
    public string Name { get; set; }

    public int Age { get; set; }
}

public class MyCat : MyAnimal
{
    public int Lives { get; set; }
}

public class MyDog : MyAnimal
{
    public string Breed { get; set; }
}
```

```json
{
    "$type": "cat",
    "Name": "Fluffy",
    "Age": 3,
    "Lives": 9
}
```

```csharp
var options = new JsonSerializerOptions
{
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
};

var stream = File.OpenRead("animal.json");

MyAnimal cat = JsonSerializer.Deserialize<MyAnimal>(stream, options)
```

This will throw the following exception:

```
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll: 'The JSON property '$type' could not be mapped to any .NET member contained in type 'MyAnimal'.'
```

### Expected behavior

The type discriminator (e.g: `$type`) should not throw an exception when `JsonUnmappedMemberHandling.Disallow` is set.

### Actual behavior

The type discriminator (e.g: `$type`) throws an exception when `JsonUnmappedMemberHandling.Disallow` is set.

### Regression?

I don't think so. 

### Known Workarounds

I don't know any workaround other than disabling the `JsonUnmappedMemberHandling`. But in my context, I would really appreciate to have built-in validation of extra members since the JSON input is controlled by the user. 

### Configuration

```
$ dotnet --version
8.0.103
```

**Comment by eiriktsarpalis** [comment]
I can't reproduce using your code but I'm guessing you did something like this?
```C#
var options = new JsonSerializerOptions
{
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
};

string json = """
    {
        "$type": "cat",
        "Name": "Fluffy",
        "Lives": 9
    }
    """;

JsonSerializer.Deserialize<MyAnimal>(json, options); // Success
JsonSerializer.Deserialize<MyCat>(json, options); // JsonException

[JsonPolymorphic]
[JsonDerivedType(typeof(MyCat), typeDiscriminator: "cat")]
public class MyAnimal
{
    public string Name { get; set; }
}

public class MyCat : MyAnimal
{
    public int Lives { get; set; }
}
```
If that's the case, this is expected behavior. The polymorphic configuration of `MyAnimal` isn't inherited by `MyCat` and therefore using `MyCat` instead of `MyAnimal` as the declared type changes the serialization semantics to not require discriminator metadata.

**Comment by jhm-ciberman** [comment]
You are right! I didn't realize that detail. 
That sounds like a logic expected behavior. I tried in my project and it works perfect. Thank you! 

I'm closing this and leaving it in case someone else has the same problem.
