### ISSUE TITLE
Optimization System.Text.Json source generation

### ISSUE THREAD

**Issue by LioRei** [dotnet/runtime#100068]
Hello,

I'm working on improving System.Text.Json performance but I came across a weird piece of code. Is this normal or can I simplify it (by removing the double interpolation)? Or maybe the double interpolation is useful for something ?

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L1323

**Comment by pinkfloydx33** [comment]
Where do you see "double" interpolation?

That's an [interpolated raw string](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#interpolated-raw-string-literals)

**Comment by LioRei** [comment]
Oh, my bad, I doesn't know about raw string 😅
So no need to touch anything
