### ISSUE TITLE
[Question] Is it possible that .NET 7 framework-dependent application requires specific (the latest) .NET runtime version?

### ISSUE THREAD

**Issue by oblomingo** [dotnet/runtime#100006]
Some of the users that use our app confronted an issue when an application can't start because of missing .NET framework.
CI pipeline builds the application using the framework-dependent model. The application installer has a prerequisite feature and installs all required .NET components (dotnet-runtime-7.0.14-win-x86 and aspnetcore-runtime-7.0.14-win-x86) before application installation.
Recently we have got a log of the installer:
```
App: C:\Program Files (x86)\CompanyName\App.exe
		Architecture: x86
		Framework: 'Microsoft.NETCore.App', version '7.0.17' (x86)
		.NET location: C:\Program Files (x86)\dotnet\
		
		The following frameworks were found:
		7.0.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
		7.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App] (edited) 
```
It seems that the user system already has Microsoft.NETCore.App 7.0.14 and 7.0.16 framework versions, but still need 7.0.17 version.
The dotnet project doesn't have an explicit 7.0.17 framework version:
```
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>...</UserSecretsId>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Configurations>Debug;Release;QA</Configurations>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <RuntimeIdentifier>win10-x86</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <SelfContained>False</SelfContained>
  </PropertyGroup>
...
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <FrameworkReference Include="Microsoft.NETCore.App" />
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>
...
``` 
I'm wondering why a .NET framework-dependent app may require a specific (the latest) .NET runtime version? If possible, how to prevent this behavior and configure an app to use predefined 7.0.14 version?

**Comment by oblomingo** [comment]
I've checked runtimeConfig.json and it doesn't have the 7.0.14 version, only 7.0.0:
```
{
  "runtimeOptions": {
    "tfm": "net7.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "7.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "7.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "7.0.0"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

**Comment by filipnavara** [comment]
There's a semi-documented .csproj property that allows you to specify the minimum version for framework dependent projects (or specific version for self-contained ones):
```xml
<PropertyGroup>
  <RuntimeFrameworkVersion>7.0.14</RuntimeFrameworkVersion>
</PropertyGroup>
```

**Comment by vitek-karas** [comment]
One possible case is that ASP.NET or WindowsDesktop on that machine is 7.0.17 and that would have a reference to `NETCore.App` 7.0.17. Technically the installers should make sure this doesn't happen, but I guess it's possible.

**Comment by elinor-fung** [comment]
> One possible case is that ASP.NET or WindowsDesktop on that machine is 7.0.17 and that would have a reference to `NETCore.App` 7.0.17. Technically the installers should make sure this doesn't happen, but I guess it's possible.

This sounds like a likely culprit. The ASP.NET runtime bundle currently doesn't include the core runtime (`NETCore.App`): https://github.com/dotnet/aspnetcore/issues/49562

@oblomingo would it be possible to get one of your users hitting this to run `dotnet --info` to show what is installed?

**Comment by oblomingo** [comment]
@vitek-karas @elinor-fung It seems I've found the root cause and it is related to unexpected Microsoft.AspNetCore.App installation process.
For example, there is a .NET 7 framework-dependent app which depends on 3 runtimes:  
Microsoft.AspNetCore.App
Microsoft.WindowsDesktop.App
Microsoft.NETCore.App
Application runtime config file:
```json
{
  "runtimeOptions": {
    "tfm": "net7.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "7.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "7.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "7.0.0"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```
A system should have all three runtimes installed and (as I've found by trials and errors) all runtime versions should be the same (like, 7.0.14). If Microsoft.AspNetCore.App runtime has a different version like 7.0.17, the application doesn't work and shows "You must install or update .NET to run this application..." error message.

Steps to reproduce the problem:
1). the app is already installed with all required runtimes (7.0.14).
dotnet --info
```
.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```
2). Install Microsoft.AspNetCore.App 7.0.17 (aspnetcore-runtime-7.0.17-win-x86). In this case, the installer removes the previous version 7.0.14 and installs 7.0.17.  

Result:
The app doesn't work and shows error message:
```
You must install or update .NET to run this application.

App: C:\Program Files (x86)\Company\App.exe
Architecture: x86
Framework: 'Microsoft.NETCore.App', version '7.0.17' (x86)
.NET location: C:\Program Files (x86)\dotnet\

The following frameworks were found:
  7.0.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.17&arch=x86&rid=win10-x86
```
dotnet --info
```
  Microsoft.AspNetCore.App 7.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I believe it a big problem for apps that depend on runtimes, because random installation made by a user or even Windows update can break an application. Any ideas on how I could prevent this case from the solution or installer perspective?

**Comment by agocke** [comment]
Closing as dup of https://github.com/dotnet/aspnetcore/issues/49562
