### ISSUE TITLE
`ilverify` not installed as `dotnet-ilverify`

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#100069]
### Description

The `ilverify` tool installs (through `dotnet tool install --global`) itself as `%USERPROFILE%/.dotnet/tools/ilverify.exe`. As such, `dotnet-ilverify` and `dotnet ilverify` do not work. It should be installed as `dotnet-ilverify.exe`.

### Reproduction Steps

Follow the [instructions](https://github.com/dotnet/runtime/tree/e12e2fa6cbdd1f4b0c8ad1b1e2d960a480c21703/src/coreclr/tools/ILVerify):

```shell
> dotnet tool install --global ilverify
Tool 'dotnet-ilverify' was reinstalled with the stable version (version '8.0.0').
> dotnet ilverify
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ilverify does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

### Expected behavior

ILVerify runs.

### Actual behavior

I need to manually execute `ilverify.exe` by specifying its full path.

**Comment by vcsjones** [comment]
> I need to manually execute ilverify.exe by specifying its full path.

When you install .NET `%USERPROFILE%/.dotnet/tools` is usually added to the path. After installing it, it says "You can invoke the tool using the following command: ilverify". Why do you need to specify the full path?

When I install the global tool I can type "ilverify" and it runs.

**Comment by colejohnson66** [comment]
True, I didn't think about that. However, the documentation says to run `dotnet ilverify` which will look for `dotnet-ilverify.exe` only.
