### ISSUE TITLE
[API Proposal]: System.Net.Http.PipeReaderContent

### ISSUE THREAD

**Issue by markrendle** [dotnet/runtime#100019]
### Background and motivation

ASP.NET Core docs recommend using the `BodyReader` property of `HttpRequest`, which is a `PipeReader`, for improved performance.

If an `HttpClient` could replace the current `Stream`-based `HttpContent` types with `PipeReader`-based internals, and a `PipeReaderContent` which exposes the reader methods directly, could that improve performance at the client end similar to the server end?

### API Proposal

```csharp
namespace System.Net.Http;

public class PipeReaderContent : HttpContent
{
    public PipeReader Reader { get; }

    // All HttpContent methods implemented over PipeReader?
}
```

### API Usage

```csharp
var r = await httpClient.GetAsync("https://example.com/bigfile", HttpCompletionOption.ResponseHeadersRead);

if (r.Content is PipeReaderContent pipeReaderContent)
{
  await ProcessPipe(pipeReaderContent.Reader);
}
else
{
  // do usual stuff
}
```

### Alternative Designs

Could potentially be exposed via an abstract `ReadAsPipeReader/Async` method on `HttpContent`?

**Comment by MihaZupan** [comment]
If you use a `StreamContent`, we will serialize the content by calling `CopyToAsync` on that stream.
If the stream you provided is `PipeReader.AsStream()`, you'll already be calling into the `PipeReader.CopyToAsync(Stream)` implementation, so I don't think we would be able to do something much better with a dedicated content type.

**Comment by markrendle** [comment]
@MihaZupan @stephentoub Thanks for explaining. I'll go ahead and close this.
