### ISSUE TITLE
Socket.Bind does not work with any UDP port on Mac OSX or Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by jchristn** [dotnet/runtime#100043]
### Description

I've tried using a variety of UDP port numbers (>1024 and <65536) with and without `sudo` on Mac OSX (Apple M2, OSX 13.4) or Ubuntu 22.04.2 LTS, using the `Socket` class directly or the `SimpleUdp` package (see https://github.com/jchristn/simpleudp).  It works flawlessly on multiple versions of Windows.

It doesn't seem to matter what port I choose, there is always an exception (`Unhandled exception. System.Net.Sockets.SocketException (48): Address already in use`) thrown.  

`lsof -i | grep UDP` shows there are a small handful of UDP ports in use, but I'm not choosing any of those ports.

### Reproduction Steps

On Mac:
1) `git clone https://github.com/jchristn/simpleudp`
2) `cd simpleudp/src`
3) `dotnet build`
4) `cd node/bin/debug/net8.0`
5) `dotnet node.dll 127.0.0.1 10000` (or `sudo dotnet node.dll 127.0.0.1 10000`)

```
Unhandled exception. System.Net.Sockets.SocketException (48): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at SimpleUdp.UdpEndpoint.Start() in /Users/joelchristner/Code/simpleudp/src/SimpleUdp/UdpEndpoint.cs:line 182
   at Node.Program.Main(String[] args) in /Users/joelchristner/Code/simpleudp/src/Node/Program.cs:line 42
zsh: abort      dotnet node.dll 127.0.0.1 10000
```

### Expected behavior

The `UdpClient` should be operational (this exact scenario works great on Windows), e.g. on Windows I can spawn two instances (each with a different port) and successfully send datagrams from one to the other.  On Mac OSX and Linux, the aforementioned exception is thrown.

### Actual behavior

Exception of type `System.Net.Sockets.SocketException` is being thrown.

### Configuration

.NET 8.0, Mac OSX 13.4 on an M2 chip
Ubuntu 22.04.2 LTS (in WSL on Windows 11)

**Comment by jchristn** [comment]
I narrowed down the issue with this sample code.
```
namespace Test 
{
	using System;
	using System.Net;
	using System.Net.Sockets;

	static class Program 
	{
		static void Main(string[] args)
		{
			int port = Convert.ToInt32(args[0]);

			UdpClient udp = new UdpClient(); 
			// UdpClient udp = new UdpClient(port);
			
			Socket socket = new Socket(
				AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);

			socket.SetSocketOption(
				SocketOptionLevel.IP, SocketOptionName.ReuseAddress, true);

			socket.Bind(new IPEndPoint(IPAddress.Loopback, port));
			// socket.Bind throws a SocketException if the UdpClient is instantiated with
			// the port number on Linux or Mac OSX.  However, it works on Windows.
			//
			// It works on all platforms when UdpClient is not instantiated with a port, i.e.
			// the parameterless constructor.  However, in this case, the endpoint in receipt
			// of a datagram doesn't see the correct port number (random port assigned).

			Console.WriteLine("ENTER to exit");
			Console.ReadLine();
		}
	}
}
```

The issue is tied to whether or not the `port` is supplied in the `UdpClient` constructor.

With `port` specified in the constructor:
- It works on Windows with no problem
- `socket.Bind` throws a `SocketException` on Mac OSX and Ubuntu 22.04.2
- When sending a datagram (see the `SimpleUdp` library linked above), the endpoint *receiving* the datagram will see the port number of the sender as specified in the `port`-centric constructor

With no `port` specified in the constructor, e.g. the parameterless constructor:
- It works on Windows, Mac OSX, and Ubuntu 22.04.2
- `socket.Bind` does not throw the `SocketException`
- However, the endpoint *receiving* a datagram sees a random port number

Out of curiosity, why is it I can listen on a port and send using that as the source port on Windows, but cannot on Linux and Mac OSX?

**Comment by jchristn** [comment]
Example on Windows, no `port` specified in `UdpClient` constructor.
![image](https://github.com/dotnet/runtime/assets/1421081/7c38e947-cdcc-4017-9f9a-967767888d10)

Example on Windows, `port` specified in `UdpClient` constructor.
![image](https://github.com/dotnet/runtime/assets/1421081/299e29f8-729d-4806-8622-4ed20656362e)

The second is the desired behavior.  I can both send and receive on that port number.  

Any idea why the difference between amongst Windows, Linux, and Mac?

**Comment by jchristn** [comment]
Ok, it seems the `UdpClient(port)` constructor implicitly performs a `socket.Bind` under the hood.  Windows doesn't mind it, whereas Mac OSX and Linux throw the `SocketException`.

**Comment by jchristn** [comment]
Closing this one because I anticipate that the documentation (somewhere) indicates that 1) passing a port into the constructor of `UdpClient` will bind it, 2) Windows will tolerate an additional `Socket.Bind` against that same port whereas Linux and Mac OSX will not.

**Comment by MichalPetryka** [comment]
> Windows will tolerate an additional `Socket.Bind` against that same port whereas Linux and Mac OSX will not.

This behaviour depends on bind flags AFAIR:
```
       SO_REUSEADDR
              Indicates that the rules used in validating addresses
              supplied in a bind(2) call should allow reuse of local
              addresses.  For AF_INET sockets this means that a socket
              may bind, except when there is an active listening socket
              bound to the address.  When the listening socket is bound
              to INADDR_ANY with a specific port then it is not possible
              to bind to this port for any local address.  Argument is
              an integer boolean flag.

       SO_REUSEPORT (since Linux 3.9)
              Permits multiple AF_INET or AF_INET6 sockets to be bound
              to an identical socket address.  This option must be set
              on each socket (including the first socket) prior to
              calling bind(2) on the socket.  To prevent port hijacking,
              all of the processes binding to the same address must have
              the same effective UID.  This option can be employed with
              both TCP and UDP sockets.

              For TCP sockets, this option allows accept(2) load
              distribution in a multi-threaded server to be improved by
              using a distinct listener socket for each thread.  This
              provides improved load distribution as compared to
              traditional techniques such using a single accept(2)ing
              thread that distributes connections, or having multiple
              threads that compete to accept(2) from the same socket.

              For UDP sockets, the use of this option can provide better
              distribution of incoming datagrams to multiple processes
              (or threads) as compared to the traditional technique of
              having multiple processes compete to receive datagrams on
              the same socket.
```

**Comment by jchristn** [comment]
Thanks @MichalPetryka is there a way you would amend the code above to leverage such flags?  Ideally if we could have both send and receive from the same port number, cross-platform, that would be ideal

**Comment by MichalPetryka** [comment]
> is there a way you would amend the code above to leverage such flags?

I assume asking for it to be exposed in `SetSocketOption` would be the best idea, for now you could try PInvoking into the OS API that sets the flags.
