### ISSUE TITLE
How to release dll load by mono?

### ISSUE THREAD

**Issue by newNcy** [dotnet/runtime#100136]
Like embidding mono in c++ , the host process will keep load and run various assembly,  so how to release them after execution

**Comment by agocke** [comment]
This should work just like it does in CoreCLR, namely via AssemblyLoadContext unloading. See https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.unload?view=net-8.0

**Comment by huoyaoyuan** [comment]
Mono does not support unloadable ALC yet. You can figure out whether Mono can be unloaded totally.

**Comment by newNcy** [comment]
> Mono does not support unloadable ALC yet. You can figure out whether Mono can be unloaded totally.

I guess no，create a alc， load assembly, repeat 1w times，memory usage keep increase.
if ALC unloadiability supported on coreCLR, can i embed it in c++ library?

**Comment by huoyaoyuan** [comment]
Hosting coreclr is documented at https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting. Note that coreclr is not available on iOS, if you want to use.

Note that in ALC model instead of AppDomain model, there's no forceful unload support. Long-live references to objects/code of types defined in assembly will cause memory leak.

**Comment by newNcy** [comment]
> Hosting coreclr is documented at https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting. Note that coreclr is not available on iOS, if you want to use.
> 
> Note that in ALC model instead of AppDomain model, there's no forceful unload support. Long-live references to objects/code of types defined in assembly will cause memory leak.

what kind of refs are Long-Live references?  just want to know how to avoid it 
```C#
127     public static void run_game(string path)
128     {           
129         var alc = new AssemblyLoadContext("_", true);
130         Console.WriteLine($"dll to load {path}");
131         var asm = alc.LoadFromAssemblyPath(path);
132         Console.WriteLine($"dll to load {asm}");
133             
134         var programType = asm.GetType("Program");
135         if (programType == null)
136         {           
137             Console.WriteLine("Program type not found in the assembly");
138             return;
139         }       
140                 
141         var nqueenMethod = programType.GetMethod("Nqueen", BindingFlags.Public | BindingFlags.Static);
142         if (nqueenMethod == null)
143         {               
144             Console.WriteLine("Nqueen method not found in the Program type");
145             return;
146         }   
147             
148         nqueenMethod.Invoke(null, null);
149         alc.Unload();
150         alc = null;
151     }

```
```C#
30     static public List<object> objs = new List<object>();
131 
132     public static void Nqueen()
133     {
134         Console.WriteLine("dll2");
135         for (int i = 0; i < 1000; i++) {
136             objs.Add($"hello world {i}");
137         }
138         //GC.Collect();
139     }
```

**Comment by huoyaoyuan** [comment]
> what kind of refs are Long-Live references? just want to know how to avoid it

Just references to types/objects that lives beyond you use, for example something retains in a static cache dictionary, or some event registered with objects created from the assembly.
