### ISSUE TITLE
System.Net.Quic.QuicException : Connection aborted by peer

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#100121]
```
System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose(payloadSize: 65537, closeServer: True, useDispose: False) [FAIL]
      System.Net.Quic.QuicException : Connection aborted by peer (987).
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(177,0): at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(237,0): at System.Net.Quic.ResettableValueTaskSource.TrySetException(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(613,0): at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(636,0): at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(665,0): at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent)
```
---

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=613212
Build error leg or test failing: System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose
Pull request: https://github.com/dotnet/runtime/pull/100021

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.QuicException : Connection aborted by peer",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=613212
**Error message validated:** `[System.Net.Quic.QuicException : Connection aborted by peer`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/22/2024 6:06:57 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[613400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613400)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613400&view=ms.vss-test-web.build-test-results-tab&runId=14983436&resultId=207042)|dotnet/runtime#100117|
|[613336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613336)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613336&view=ms.vss-test-web.build-test-results-tab&runId=14982250&resultId=206476)|dotnet/runtime#100123|
|[613341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613341)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613341&view=ms.vss-test-web.build-test-results-tab&runId=14982472&resultId=218823)|dotnet/runtime#100001|
|[613219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613219)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613219&view=ms.vss-test-web.build-test-results-tab&runId=14978498&resultId=206613)|dotnet/runtime#100117|
|[613212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613212)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613212&view=ms.vss-test-web.build-test-results-tab&runId=14978328&resultId=206613)|dotnet/runtime#100021|
|[613161](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613161)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613161&view=ms.vss-test-web.build-test-results-tab&runId=14977288&resultId=208355)|dotnet/runtime#100115|
|[613135](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613135)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613135&view=ms.vss-test-web.build-test-results-tab&runId=14974922&resultId=206613)|dotnet/runtime#100116|
|[613118](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613118)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613118&view=ms.vss-test-web.build-test-results-tab&runId=14974712&resultId=206476)|dotnet/runtime#97792|
|[613101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613101)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613101&view=ms.vss-test-web.build-test-results-tab&runId=14974664&resultId=206262)|dotnet/runtime#99130|
|[613068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613068)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613068&view=ms.vss-test-web.build-test-results-tab&runId=14973914&resultId=206613)|dotnet/runtime#100110|
|[613027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613027)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613027&view=ms.vss-test-web.build-test-results-tab&runId=14973154&resultId=217316)|dotnet/runtime#100038|
|[612995](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612995)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612995&view=ms.vss-test-web.build-test-results-tab&runId=14972174&resultId=206613)|dotnet/runtime#97529|
|[612853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612853)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612853&view=ms.vss-test-web.build-test-results-tab&runId=14970006&resultId=198263)|dotnet/runtime#99467|
|[612822](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612822)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612822&view=ms.vss-test-web.build-test-results-tab&runId=14967372&resultId=206276)|dotnet/runtime#100050|
|[612743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612743)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612743&view=ms.vss-test-web.build-test-results-tab&runId=14965594&resultId=206476)|dotnet/runtime#99183|
|[612613](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612613)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612613&view=ms.vss-test-web.build-test-results-tab&runId=14960984&resultId=217209)|dotnet/runtime#98492|
|[612677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612677)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612677&view=ms.vss-test-web.build-test-results-tab&runId=14962632&resultId=206262)|dotnet/runtime#100107|
|[612627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612627)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612627&view=ms.vss-test-web.build-test-results-tab&runId=14960816&resultId=206613)|dotnet/runtime#100021|
|[612687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612687)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612687&view=ms.vss-test-web.build-test-results-tab&runId=14960582&resultId=198699)|dotnet/runtime#99833|
|[612582](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612582)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612582&view=ms.vss-test-web.build-test-results-tab&runId=14959532&resultId=206347)|dotnet/runtime#99970|
|[612455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612455)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612455&view=ms.vss-test-web.build-test-results-tab&runId=14953380&resultId=215110)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|21|21|21|

**Comment by liveans** [comment]
Looks like this is coming from this #100093 PR.
I will take a look.
cc @ManickaP
