### ISSUE TITLE
WASM test failing with OOM

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#100111]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=612582
Build error leg or test failing: WasmTestOnBrowser-System.Buffers.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/99970

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "MONO_WASM: Out of memory",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=612582
**Error message validated:** `[MONO_WASM: Out of memory`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/22/2024 12:51:34 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment]
related https://github.com/dotnet/runtime/issues/98578

**Comment by lewing** [comment]
also https://github.com/dotnet/runtime/issues/59678

**Comment by lewing** [comment]
and https://github.com/dotnet/runtime/issues/101016

**Comment by pavelsavara** [comment]
Possibly related https://github.com/dotnet/runtime/pull/102323

**Comment by pavelsavara** [comment]
no hits anymore
