### ISSUE TITLE
System.Net.Quic.QuicException : Connection aborted by peer (987)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#100150]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=613336
Build error leg or test failing: System.Net.Quic.Tests.QuicStreamTests.ReadsClosedFinishes_ConnectionClose
Pull request: https://github.com/dotnet/runtime/pull/100123

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.QuicException : Connection aborted by peer (987)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=613336
**Error message validated:** `[System.Net.Quic.QuicException : Connection aborted by peer (987)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/22/2024 5:02:51 PM UTC

**Comment by ManickaP** [comment]
Fixed by #100128
