### ISSUE TITLE
Convert.ChangeType(infinity, float/double) throws an error on Linux in .NET 6/7/8

### ISSUE THREAD

**Issue by Bartleby2718** [dotnet/runtime#100197]
### Description

[`System.Convert.ChangeType(...)`](https://learn.microsoft.com/en-us/dotnet/api/system.convert.changetype?view=net-8.0) cannot convert positive or negative infinity to `float` or `double` in .NET 6/7/8.

### Reproduction Steps

- GitHub repo: https://github.com/Bartleby2718/convert-changetype-infinity
- AppVeyor run: https://ci.appveyor.com/project/Bartleby2718/convert-changetype-infinity

### Expected behavior

On all supported OSes and on all versions of .NET:
- `(float)Convert.ChangeType("∞", typeof(float))` should equal [`Single.PositiveInfinity`](https://learn.microsoft.com/en-us/dotnet/api/system.single.positiveinfinity)
- `(float)Convert.ChangeType("-∞", typeof(float))` should equal [`Single.NegativeInfinity`](https://learn.microsoft.com/en-us/dotnet/api/system.single.negativeinfinity)
- `(double)Convert.ChangeType("∞", typeof(double))` should equal [`Double.PositiveInfinity`](https://learn.microsoft.com/en-us/dotnet/api/system.double.positiveinfinity)
- `(double)Convert.ChangeType("-∞", typeof(double))` should equal [`Double.NegativeInfinity`](https://learn.microsoft.com/en-us/dotnet/api/system.double.negativeinfinity)

### Actual behavior

They all throw on Linux.

### Regression?

This has never worked in the past few major versions of .NET (Core). Didn't test EOL'd version of .NET (Core).

### Known Workarounds

Special-case `"∞"` and `"-∞"`

### Configuration

- .NET version: 6, 7, 8
- OS version: Ubuntu 22.04

**Comment by huoyaoyuan** [comment]
`Convert.ChangeType` calls `float.Parse` and `double.Parse`. They only match `PositiveInfinitySymbol` and `NegativeInfinitySymbol` of current culture, which differ from OS and versions. You can print `CultureInfo.CurrentCulture.NumberFormat.PositiveInfinitySymbol` to verify. It prints `Infinity` for me on Linux.

**Comment by Bartleby2718** [comment]
@huoyaoyuan That was it! Good to know how this works under the hood.

Closing.
