### ISSUE TITLE
Question: does compiler keep names of static classes and static functions compiled with NativeAOT

### ISSUE THREAD

**Issue by LLT21** [dotnet/runtime#100166]
> Maybe a more important question: all internal/private classes, methods, properties -> are these included in the reflection data or only the public ones ? Any hint on how this might improve obfuscation ?

The compiler by default keeps names of types. Names of methods are included if stack trace data is generated (the suggested `<StackTraceSupport>false</StackTraceSupport>` disables that). Other than that, the compiler only generates reflection metadata for things that were visible targets of reflection. Only a very small portion of the program will be generated like that.

_Originally posted by @MichalStrehovsky in https://github.com/dotnet/runtime/issues/96339#issuecomment-1870926307_
 

Referring to this: does it makes sense to separate the code that one wants to protect from an IP standpoint in another project that is natively compiled with reflection disabled ? Or can the same result be more easily achieved by keeping the IP protected code in static classes and static methods ? As far as I understand these are not really "types", so the question is whether these names/signatures are still visible in a normal nativeaot compiled program ?

**Comment by jkotas** [comment]
> whether these names/signatures are still visible in a normal nativeaot compiled program ?

If you are disable StackTraceSupport, the native aot binary won't contain names and signatures of methods unless they are reflection visible.
