### ISSUE TITLE
Assertion failed 'lastBlockILEndOffset < beginOffs'

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#100125]
Native AOT outerloop tests are failing on all architectures.

Example: https://dev.azure.com/dnceng-public/public/_build/results?buildId=613229&view=logs&jobId=0cd015bc-ac80-5dfb-09b8-6d9db63883bc&j=0cd015bc-ac80-5dfb-09b8-6d9db63883bc&t=3393f03a-e6e5-5ccb-ae92-d1ce7b161b0e

```
    ILC: D:\git\runtime2\src\coreclr\jit\scopeinfo.cpp:1572
    ILC: Assertion failed 'lastBlockILEndOffset < beginOffs' in 'ABIStress.Program:DoStubCall(int,ubyte,ubyte,int,int):
  ubyte' during 'Generate code' (IL size 2013; hash 0x4766f2b1; MinOpts)

D:\git\runtime2\artifacts\bin\coreclr\windows.x64.Checked\build\Microsoft.NETCore.Native.targets(310,5): error MSB3073:
 The command ""D:\git\runtime2\artifacts\bin\coreclr\windows.x64.Checked\ilc-published\\ilc" @"D:\git\runtime2\artifact
s\tests\coreclr/obj/windows.x64.Checked/Managed/JIT\Stress\ABI\tailcalls_d\native\tailcalls_d.ilc.rsp"" exited with cod
e -2147483645. [D:\git\runtime2\src\tests\JIT\Stress\ABI\tailcalls_d.csproj] [D:\git\runtime2\src\tests\build.proj]
```

JitDump: 
[jitdump.zip](https://github.com/dotnet/runtime/files/14718946/jitdump.zip)

**Comment by MichalStrehovsky** [comment]
I'm blocking tests on this issue in #100117 since this is a test build break.

**Comment by filipnavara** [comment]
Related to the fix for https://github.com/dotnet/runtime/issues/99543, perhaps?

**Comment by MichalStrehovsky** [comment]
> Related to the fix for #99543, perhaps?

I can't tell but the assert sounds like that. I guess it doesn't hurt to cc @TIHan @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Yes, seems likely... @TIHan can you take a look?

**Comment by TIHan** [comment]
My change is likely the cause. I'll quickly have a change to fix this.
