### ISSUE TITLE
[Question] How to set proxy just for AAD endpoint?

### ISSUE THREAD

**Issue by yunbozhang-msft** [dotnet/runtime#100268]
Hi team,

Our network does not allow direct access to Azure AAD, it needs to go through a proxy. 

In .net 6, we refer to the following two documents to successfully configure the use of a proxy when only accessing AAD, and other requests do not go through the proxy:

https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-api-call-api-app-configuration?tabs=aspnetcore
https://stackoverflow.com/questions/54680904/is-there-a-way-to-configure-jwtbeareroptions-on-netcore-webapi-application

SDK we used in .net6
Microsoft.AspNetCore.Authentication.JwtBearer 6.0.14
Microsoft.Identity.Web 2.5.0

------------------

But after upgrading to .net 8, this method doesn't seem to work. Do you know the correct way to configure it on .net 8? I've searched about this, but there doesn't seem to be official documentation on this issue.

Do we have offical doc or sample to introduce how to do this in .net 8?

Thanks

**Comment by yunbozhang-msft** [comment]
After setting the HttpClient proxy via configuring Microsoft.Identity.Web.AadIssuerValidatorOptions, it could work as expected in .NET 8.0. But I cannot find any clue about why .NET 6.0 could work without this setting.

**Comment by ManickaP** [comment]
Can you share a simple `HttpClient` repro? What's the error you're seeing? Have you tried with .NET 7?
