### ISSUE TITLE
[apple][HybridGlobalization] Enable more System.Globalization.Tests for Apple Hybrid-Globalization

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#100240]
There are a lot of tests in `System.Globalization.Tests` that are only enabled for Hybrid-Globalization on Browser. For example: https://github.com/dotnet/runtime/blob/71a7d8844cf509717f7e76baafb1bfbf1217ceec/src/libraries/System.Runtime/tests/System.Globalization.Tests/DateTimeFormatInfo/DateTimeFormatInfoLongDatePattern.cs#L219-L224

Some of these tests could be used to verify correct functionality of Apple Hybrid-Globalization.

---

cc: @mkhamoyan

**Comment by mkhamoyan** [comment]
I wonder why are these test cases [runtime/src/libraries/System.Runtime/tests/System.Globalization.Tests/DateTimeFormatInfo/DateTimeFormatInfoLongDatePattern.cs](https://github.com/dotnet/runtime/blob/71a7d8844cf509717f7e76baafb1bfbf1217ceec/src/libraries/System.Runtime/tests/System.Globalization.Tests/DateTimeFormatInfo/DateTimeFormatInfoLongDatePattern.cs#L219-L224) enabled for only `hybrid` mode on `browser`, maybe they are specific to browser hybrid mode flow @ilonatommy ? 
If they are general let's enable for all platforms for both using ICU or hybrid mode.

**Comment by ilonatommy** [comment]
> If they are general let's enable for all platforms for both using ICU or hybrid mode.

They are not specific to hybrid but testing ICU on this is not necessary, in ICU if we loaded the data and it's available for one specific locale, then we can assume all the remaining locales are correct.
In hybrid it's not the case, when for one locale JS can have a correct value, for another one it might return nonsense, especially for patterns where we perform regexing and string operations + JS reply might differ between versions, a good example is this PR: https://github.com/dotnet/runtime/pull/90881 where `culture-info.ts` required changes and it was caught by these tests. Running them on ICU is in my opinion a waste of testing machine time.

**Comment by mkhamoyan** [comment]
> They are not specific to hybrid but testing ICU on this is not necessary, in ICU if we loaded the data and it's available for one specific locale, then we can assume all the remaining locales are correct. In hybrid it's not the case, when for one locale JS can have a correct value, for another one it might return nonsense, especially for `DatePatterns` where we perform regexing and string operations + JS reply might differ between versions of hosts. A good example is this PR: #90881 where `culture-info.ts` required changes for `ja-JP` only and it was caught by these tests. Running them on ICU is in my opinion a waste of testing machine time.
> 
> Edit: For apple I would ask myself a question: is it possible that only few locales are broken while `en-US` (or some other EFIGS locale) that we most frequently test by default returns correct value? If it is, then enabling them on apple makes sense. Otherwise, one locale per API for apple.

For Apple there should not be broken locales (Apple also uses ICU libs). IMHO running same suite of tests that we were validating ICU should be enough for Apple hybrid mode.

**Comment by ilonatommy** [comment]
@tarekgh, we are trying to understand what was the motivation for skipping some types of tests for globalization methods when developing the libs, e.g. `LongDatePattern` that was not tested even when we are performing normalization on our side in the libs. We are trying to figure out what is the motivation for testing only specific locales, e.g. `en-US`, `fr-FR` (https://github.com/dotnet/runtime/blob/71a7d8844cf509717f7e76baafb1bfbf1217ceec/src/libraries/System.Runtime/tests/System.Globalization.Tests/DateTimeFormatInfo/DateTimeFormatInfoFirstDayOfWeek.cs#L11
but skipping the rest and how did we choose which ones are worth testing?

**Comment by tarekgh** [comment]
@ilonatommy we are trying to make the tests stable. The globalization data is changing almost every release of ICU/Windows. If we test all cultures that will make the test unstable. So, we choose subset of the cultures that are stable enough to test against.

**Comment by matouskozak** [comment]
Completed in https://github.com/dotnet/runtime/pull/102464
