### ISSUE TITLE
Possible DEREF_AFTER_NULL.EX at  src/coreclr/vm/eepolicy.cpp

### ISSUE THREAD

**Issue by aslepykh** [dotnet/runtime#100210]
After having been compared to a `NULL` value at line 612, pointer `pExceptionInfo` is dereferenced at line 724.

https://github.com/dotnet/runtime/blob/9f4b1f5d664afdfc80e1508ab7ed099dff210fbd/src/coreclr/vm/eepolicy.cpp#L612

https://github.com/dotnet/runtime/blob/9f4b1f5d664afdfc80e1508ab7ed099dff210fbd/src/coreclr/vm/eepolicy.cpp#L724

There is a missing check for null before executing `param.pExceptionRecord = pExceptionInfo->ExceptionRecord` on line 724.

The check is present at lines 680-684 and 612, but is missing before line 724.

It is possible that the `if()` condition at lines 612 and 680 will not be satisfied.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author A. Slepykh.

**Comment by janvorli** [comment]
The method EEPolicy::HandleFatalStackOverflow is never called with NULL pExceptionInfo and it is never supposed to be called with one. There are two call sites and both pass it a reference to a local or a member of other data structure. I don't know why we have the defensive checks for NULL at some of the places. The other part mentioned has an assert to check it, which should be the way in both parts. Anyways, there is no bug here.
