### ISSUE TITLE
Question on Retrieving and Copying Method Instructions by Start Address in C#

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#100202]
I'm currently working on a project that involves low-level manipulation of method instructions in C#. Given the nature of my work, I specifically need to determine the end of a method given its start address in memory, and then copy all its instructions into a byte array. This task is crucial for a feature I am developing, which involves analyzing and potentially modifying method instructions at runtime. My project targets .NET Native, meaning that all code is compiled ahead-of-time (AOT) into native code.

Given this scenario, my questions for you are:

1. Considering the AOT compilation model of .NET Native, is there a recommended approach or any available tooling within the .NET ecosystem that would allow me to accurately determine the end of a method's instructions in memory based on its start address?
2. Are there any best practices or considerations I should be aware of when attempting to copy method instructions into a byte array, especially in the context of .NET Native?
3. Given my requirement to analyze and potentially modify method instructions at runtime, are there any specific challenges or limitations I might face with .NET Native, and how might I overcome them?

Any insights, recommendations, or guidance you can provide would be immensely helpful for navigating these challenges and ensuring the reliability and effectiveness of this feature in our project. Thank you for your time and assistance.

My code at the moment:

`public byte[] GetFullMethodInstructions(IntPtr methodPtr)
    {
        int size = 0;

        for (byte* instructions = (byte*)methodPtr; *instructions != 0xCC; instructions++)
        {
            size++;
        }

        byte[] bytes = new byte[size];

        fixed (byte* ptr = bytes)
        {
            for (int i = 0; i < size; i++)
            {
                ptr[i] = *(byte*)(methodPtr + i);
            }
        }

        return bytes;
    }`

**Comment by jkotas** [comment]
NativeAOT binaries are no different from C/C++ or other native binaries at this level. The answer to your question would equally apply to native binaries compiled from other languages.

A few different options that you have: 
- Write a disassembler that understands the instruction stream. Your code fragment suggests that you are considering going in this direction, but it has to be much more sophisticated.
- Use unwind information to find the ranges for the method code (libunwind library can help you with that)
- Use symbol information (.PDB on Windows, .DWARF on other platforms) to find the ranges for the method code

**Comment by jkotas** [comment]
> potentially modify method instructions at runtime

In general, modifying method instructions at runtime does not work for .NET. The GC tracking information that is separate data structure has to exactly match with the method instructions. If you modify the method instructions, it is very likely that the GC tracking information will be out of sync with your modifications, and you will see intermittent crashes.
