### ISSUE TITLE
DEREF_AFTER_NULL.EX in src/coreclr/vm/readytoruninfo.cpp

### ISSUE THREAD

**Issue by aslepykh** [dotnet/runtime#100208]
After having been assigned to a `NULL` value at line 95-96, pointers `pszName` and `pszNameSpace` arw dereferenced at line 162 by calling function `strcmp()`:

https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/src/coreclr/vm/readytoruninfo.cpp#L162

If the `if()` condition at line 106 is not met, then `pszName` and `pszNameSpace` will not be overridden and will remain `NULL`:

https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/src/coreclr/vm/readytoruninfo.cpp#L106

Once in the `else()` branch at line 138, another `if()` condition must be executed: 
if the `GetVersionResilientTypeHashCode()` function returns `false`, then it will `return FALSE`, which will prevent the null dereference situation, but if the function returns true, then program execution will continue.

https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/src/coreclr/vm/readytoruninfo.cpp#L138-L139

The `strcmp()` function will get `NULL`, where `pszName` and `pszNameSpace` will be dereferenced.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author A. Slepykh.

**Comment by jkotas** [comment]
> pointers pszName and pszNameSpace arw dereferenced at line 162 by calling function strcmp()

This line is only executed when `if (pName->GetTypeToken() == mdtBaseType || pName->GetTypeModule() == NULL)` condition is true. The method assigns non-NULL values to these pointers earlier under the same condition.

Notice that `pName->GetTypeToken() == mdtBaseType || pName->GetTypeModule() == NULL` condition shows up multiple times in the method.

**Comment by jkotas** [comment]
This is false positive as far as I can tell.

**Comment by aslepykh** [comment]
Yeah, on a second glance, I agree with false positive result. Thanks!
