### ISSUE TITLE
mono_jit_compile_method_jit_only failed

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#100237]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100156-merge-d2acb1ffe2ec4fbca7/normal-System.Text.RegularExpressions.Tests/1/console.0ddd7a8b.log?helixlogtype=result)
```
[14:09:15] info: Discovered:  System.Text.RegularExpressions.Tests.dll (found 257 of 358 test cases)
[14:09:15] info: Starting:    System.Text.RegularExpressions.Tests.dll
[14:09:15] info: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2662, condition `<disabled>' not met
[14:09:15] info: 
[14:09:15] info: Process v8-12.3.219.sh exited with 1
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=616683&view=logs&jobId=6c05861b-5acf-5a94-8135-27551ca7dfc6
Build error leg or test failing: System.Text.RegularExpressions

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "interp\\.c:2662.*condition.*not met",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=616683
**Error message validated:** `[interp\.c:2662.*condition.*not met`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/25/2024 2:44:01 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[616683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616683)|dotnet/runtime|[normal-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616683&view=ms.vss-test-web.build-test-results-tab&runId=15081748&resultId=107806)|dotnet/runtime#100156|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by pavelsavara** [comment]
cc @kg @BrzVlad

**Comment by kg** [comment]
![image](https://github.com/dotnet/runtime/assets/198130/2ff36314-df7a-4a97-86b5-80a060787e02)
Seems to be trying to JIT code. Jiterp could probably do this.

**Comment by kg** [comment]
Looking through the interp code, there are a couple obscure cases where the interpreter might try to perform a JIT call in interp mode, or a JIT call targeting non-AOT'd code in AOT mode, but they seem like they would all imply memory corruption. Vlad can probably make more sense of this.
