### ISSUE TITLE
GetUnicode_Invalid/GetAscii_Invalid test failures on Fedora 40

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#100287]
Some System.Globalization.Extensions.Tests tests are failing on Fedora 40.
Fedora 40 has libicu 74.2-1.

- `GetUnicode_Invalid`: 158 out of 5421 failed
- `GetAscii_Invalid`: 158 out of 5448 failed

See [testResults.xml.txt](https://github.com/dotnet/runtime/files/14758812/testResults.xml.txt)

cc @tarekgh @omajid

**Comment by tmds** [comment]
@tarekgh do you know what the root cause is for the test failures?

Here is one of the cases that fails:

```
Error: Expected IdnMapping.GetAscii("\u226E\uD835\uDFD5\uFF0E\u8B16Ss\u226F") to throw an ArgumentException. Line Number: 5448 [/var/home/tmds/repos/runtime/src/libraries/System.Runtime/tests/System.Globalization.Extensions.Tests/System.Globalization.Extensions.Tests.csproj]
/var/home/tmds/repos/runtime/src/libraries/System.Runtime/tests/System.Globalization.Extensions.Tests/IdnMapping/IdnMappingIdnaConformanceTests.cs(88): error VSTEST1: [5251]: Item:  Unicode_13_0_IdnaTest { ASCIIResult = ConformanceIdnaTestResult { ResultType = ToAscii, StatusValue = "[B2, B3, B6, V6]", Success = False, Value = "xn----ufo9661d.xn--r5gy929fhm4f" }, LineNumber = 6126, Source = "xn----ufo9661d.xn--r5gy929fhm4f", Type = Nontransitional, UnicodeResult = ConformanceIdnaUnicodeTestResult { ResultType = ToUnicode, StatusValue = "[B2, B3, B6, V6]", Success = False, ValidDomainName = True, Value = "ꡣ-≠.𞤹𐅢ↄ" } }
```

**Comment by tarekgh** [comment]
This test depends on the Unicode IDN data which changes with every new version.  Look at https://github.com/dotnet/runtime/tree/main/src/libraries/System.Runtime/tests/System.Globalization.Extensions.Tests/IdnMapping/Data/Unicode_11_0 as example. To fix this, we'll need to pick a new data and tweak it a little to make it pass.

**Comment by omajid** [comment]
Looks like libicu 74 uses Unicode 15.1: https://icu.unicode.org/download/74. I can look into adding this.

Do we also need to explicitly add [libicu 72/Unicode 15](https://icu.unicode.org/download/72) support? Or [libicu 70/Unicode 14](https://icu.unicode.org/download/70) support?

**Comment by tarekgh** [comment]
@omajid we can add both versions to ensure using different ICU versions will work. 

Please note, after porting the test data files, usually we comment some lines which are incompatible with our APIs. The best way to do that is just bring the data as it is, run the test, look at the failed entries and then we comment it. Thanks a lot for willing to help with that.

**Comment by omajid** [comment]
I just checked things and the tests don't fail on Fedora 39, which has icu 73. Maybe there's no interesting changes in Unicode 14 or 15 that are relevant for our test suite?

**Comment by tmds** [comment]
Thanks @omajid!
