### ISSUE TITLE
Possible DEREF_AFTER_NULL.EX at src/coreclr/vm/eepolicy.cpp

### ISSUE THREAD

**Issue by burkeartem** [dotnet/runtime#100212]
Version - 6.0.21 and higher.

After having been compared to a NULL value at eepolicy.cpp:426, pointer `pExceptionInfo->ExceptionRecord` is dereferenced at eepolicy.cpp:471.

1) NULL check
https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/src/coreclr/vm/eepolicy.cpp#L426

2) Dereference (`pExceptionInfo->ExceptionRecord` may be NULL here)
https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/src/coreclr/vm/eepolicy.cpp#L471

Probably, line 471 lacks a NULL check like: 
`(pExceptionInfo && pExceptionInfo->ExceptionRecord) ? (SIZE_T)pExceptionInfo->ExceptionRecord->ExceptionAddress : (SIZE_T)address`
instead of
`pExceptionInfo ? (SIZE_T)pExceptionInfo->ExceptionRecord->ExceptionAddress : (SIZE_T)address`.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author A. Burke.

**Comment by janvorli** [comment]
The  EEPolicy::LogFatalError is never called and never supposed to be called with NULL pExceptionInfo. We even have an assert at the beginning, the null checks at some of the places are actually useless.
