### ISSUE TITLE
Non-blittable struct with explicit layout has wrong managed size 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#100220]
Context https://github.com/dotnet/runtime/pull/100206#issuecomment-2016856746

## Repro

```csharp
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

Console.WriteLine(Unsafe.SizeOf<MyStruct>());

[StructLayout(LayoutKind.Explicit, Size = 9)]
struct MyStruct
{
    [FieldOffset(0)]
    public byte[] a;
    [FieldOffset(8)]
    public byte b;
}
```

## Expected result (on x64)

16

## Actual result

9

**Comment by MichalStrehovsky** [comment]
The layout logic is shared with crossgen2; this also reproes with ReadyToRun.

The type layout has been owned/worked on by the crossgen2 team since it needs to be bug-for-bug compatible with CoreCLR VM type system for ReadyToRun to work. Moving to crossgen2 area path.
