### ISSUE TITLE
[API Proposal]: Default SearchValues character classes

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#100244]
### Background and motivation

Many search values are: 'use all ASCII' except `,` and `;` etc.
For example: https://github.com/dotnet/aspnetcore/blob/83237c9afaa49a9cb90ceb4da56dddb744baeed0/src/Http/Shared/CookieHeaderParserShared.cs#L238

OR many examples in https://github.com/dotnet/aspnetcore/pull/45300/files

It would be better to have an API for the common cases, so I don't make a typo or leave out a character by accident.

Please note that the proposal below is very rudimentary, but it should give the idea. In case it gains interest, I would be happy to extend with further details.

cc. @MihaZupan 

### API Proposal

```csharp
namespace System.Buffers;

public class CharacterClass
{
    public static CharacterClass Ascii = "...";
    public static CharacterClass AsciiNumber = "...";
    public static CharacterClass AsciiDigits = "...";
    // etc.

    public CharacterClass Add(string characters);
    public CharacterClass Add(CharacterClass characters);
    public CharacterClass Remove(string characters);
    public CharacterClass Remove(CharacterClass characters);

    public string ToString();
    public ReadOnlySpan<char> AsSpan();
}
```

### API Usage

```csharp
private static readonly SearchValues<char> CookieValueChar = SearchValues.Create(CharacterClasses.Ascii.Remove(",\\;\"").AsSpan());

private static readonly SearchValues<char> CookieValueChar = SearchValues.Create(CharacterClasses.Ascii.Remove(CharacterClasses.AsciiDigits).AsSpan());
```

### Alternative Designs

Someone could create a `CharacterClassBuilder` or maybe `SearchValuesBuilder` etc. but I would try to keep things simple in the initial design.

**Comment by MihaZupan** [comment]
For reference, something similar exists in `System.Text.Encodings.Web`: [`TextEncoderSettings`](https://learn.microsoft.com/dotnet/api/system.text.encodings.web.textencodersettings)

**Comment by ladeak** [comment]
Do you have a preference on what way to move the proposal forward - given this could be a larger API surface? - If you think such an api is useful or general enough to be included in .NET?

**Comment by stephentoub** [comment]
Personally I'm not super excited about this. I understand the goal, but it's a fair amount of surface area for something that's better to just precompute and embed as a string.

**Comment by ladeak** [comment]
I have the same concern on the surface area.

**Comment by stephentoub** [comment]
What is the problem that needs solving at the regex level?

**Comment by ladeak** [comment]
What I meant to say that to my understanding the regex source generators already solves this problem by having these utility classes generated:

```csharp
span.IndexOfAnyExcept(Utilities.s_asciiExceptWordChars)
```

Hence I was wondering when you said precoumpute you meant alternative design with a source generator:

```csharp
[CharacterClasses(Include = CharacterClasses.Ascii, Exclude = ",;\\")]
private static partial SearchValues<char> CookieValueChar();
```

Or something totally independent.

**Comment by stephentoub** [comment]
> Hence I was wondering when you said precompute you meant alternative design with a source generator:

I meant just write out the string one's self.

**Comment by ladeak** [comment]
Sounds good to me, I see the majority liked that approach. I will close this issue for now.

**Comment by MihaZupan** [comment]
I could see some value in making it easier to use `UnicodeCategory`s, but I haven't seen that come up that much (outside of Regex which already has logic to deal with that).
