### ISSUE TITLE
Linux/arm64: Higher CPU utilization without ThreadPool_UnfairSemaphoreSpinLimit=0

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#100348]
On linux/arm64, we have noticed that the app [here](https://gist.github.com/kunalspathak/7c86f42505d51541191cacde8fbe7184) has higher CPU utilization and tweaking the flag `DOTNET_ThreadPool_UnfairSemaphoreSpinLimit` has significant impact on the numbers. Below table summarizes the CPU utilization on AMD/ARM depending on the value of the flag.

| DOTNET_ThreadPool_UnfairSemaphoreSpinLimit | AMD | Arm64 |
|-----|----|-----|
| default | 2%~14% | 46%
| 0 | 2.7%~3.3% | 3% stable
| 70 | - | 17% stable
| 280 | - | 55%

default:

![image](https://github.com/dotnet/runtime/assets/12488060/2add371e-7acb-4149-a528-f80c6aca4e20)

`DOTNET_ThreadPool_UnfairSemaphoreSpinLimit =0`:

![image](https://github.com/dotnet/runtime/assets/12488060/6237022f-726b-472c-9305-645d24fd1c72)

I see that different defaults are used for arm64 as seen in below code. When I tried to use the default used for AMD, the CPU consumption was still higher, but better than the existing default value (as seen in table above for `70`). To my understanding, the value of `DOTNET_ThreadPool_UnfairSemaphoreSpinLimit` should be `280` if not set, but I am not sure why CPU utilization is higher with this value than without it.

https://github.com/dotnet/runtime/blob/3f7ffddedad2a43c919b5144dbea3d4307d10623/src/coreclr/inc/clrconfigvalues.h#L527-L532

https://github.com/dotnet/runtime/blob/3f7ffddedad2a43c919b5144dbea3d4307d10623/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs#L19-L27

Based on the results shown in https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807 and recent conversation in https://github.com/dotnet/runtime/pull/92611#issuecomment-1864766668,  I tried switching to `isb` in https://github.com/kunalspathak/runtime/commit/e640d6f69ffc857cb9fc78de9d822bf0dfe6db09, but that doesn't give any better results.

![image](https://github.com/dotnet/runtime/assets/12488060/8cef7711-af72-4a05-9a5a-b1f6fe695458)

We should re-evaluate if we should advocate our customers to use `ThreadPool_UnfairSemaphoreSpinLimit=0` or should we re-think on our heuristics of spin wait, given that we also calculate the `yield` latency. If `ThreadPool_UnfairSemaphoreSpinLimit=0` is something we want to suggest, then we should have clear documentation on MSDN or .NET forum on why it is needed, which platforms it is needed and implication on app if this flag is not used.

**Comment by kunalspathak** [comment]
@mangod9 @kouvel 

cc: @jkotas @JulieLeeMSFT

**Comment by kunalspathak** [comment]
> I tried switching to isb in https://github.com/kunalspathak/runtime/commit/e640d6f69ffc857cb9fc78de9d822bf0dfe6db09, but that doesn't give any better results.

I just realized that my changes are just for runtime and not necessarily for the code we produce.

**Comment by EgorBo** [comment]
> but I am not sure why CPU utilization is higher with this value than without it.

I presume because spin-wating is generally worse than OS-wait when it comes to CPU usage where the tasks (e.g. ThreadPool, locks, etc) are typically non-short + spinwait is definitely worse on arm where we don't have `pause` in terms of CPU energy efficiency. I presume the current heuristics were based on some TE-like kind of workloads where spin wait is always better.

> > I tried switching to isb in [kunalspathak@e640d6f](https://github.com/kunalspathak/runtime/commit/e640d6f69ffc857cb9fc78de9d822bf0dfe6db09), but that doesn't give any better results.
> 
> I just realized that my changes are just for runtime and not necessarily for the code we produce. Let me fix that and recheck.

I don't think we emit any yield/wait in codegen currently.

Unfortantely `ThreadPool_UnfairSemaphoreSpinLimit` doesn't improve CPU usage in the OrchardCMS so if it works for you, then I presume we're actually chasing different issues.

**Comment by kunalspathak** [comment]
> I just realized that my changes are just for runtime and not necessarily for the code we produce. Let me fix that and recheck.

Never mind, we call into `ThreadNative_YieldThread` which calls into OS `sched_yield`.

> Unfortantely ThreadPool_UnfairSemaphoreSpinLimit doesn't improve CPU usage in the OrchardCMS so if it works for you, then I presume we're actually chasing different issues.

Yes, this issue was definitely not for OrchardCMS but for a different workload that is in PR description.

> It is also worth noticing that ThreadPool_UnfairSemaphoreSpinLimit only changes this behavior for ThreadPool

The CPU consumption is changing based on this flag, so yes, I was interested from ThreadPool perspective, although I switched the implementation to use `isb` for both ThreadPool/GC .

**Comment by jkotas** [comment]
> I presume the current heuristics were based on some TE-like kind of workloads where spin wait is always better.

+1. Our spinning heuristics are tuned towards max RPS. If you run with underutilized machine and want to minimize CPU utilization, it almost always better to just wait immediately as your test shows.

Perhaps we need an auto-tunning mechanism where we monitor profitability of spinning vs. waiting, and adjust it up or down based on the workload characteristics to limit the CPU use due to spinning to say less than 5%.

> GC has it's own heuristic for how long to spin vs OS-wait on gc-lock/join.

Server GC tries to run with full utilization on all cores, so the spinning is likely going to be more profitable there. It is different from the underutilized threadpool spinning while looking for work.

**Comment by EgorBo** [comment]
> Server GC tries to run with full utilization on all cores, so the spinning is likely going to be more profitable there. It is different from the underutilized threadpool spinning while looking for work.

Ah makes sense, just a bit odd that we use the same heuristic on x64 and arm64. I know we try to abstract that via NormalizedYield duration that should take care about current `YieldProcessor` instruction duration, but it doesn't take into account that `pause` on x64 leads to lower CPU usage and e.g. allows the other virtual core (on the current physical core) to do some useful work, while on arm, I believe, we're invoking `nop` in a tight loop currently.

**Comment by kunalspathak** [comment]
>  I believe, we're invoking nop (which yield technically is on most hw) in a tight loop currently.

that is my impression too and if that is the case, my understanding is it shouldn't matter the value of `DOTNET_ThreadPool_UnfairSemaphoreSpinLimit` because we should adjust the spin count automatically, but that doesn't seem to be happening?

**Comment by EgorBo** [comment]
> > I believe, we're invoking nop (which yield technically is on most hw) in a tight loop currently.
> 
> that is my impression too and if that is the case, my understanding is it shouldn't matter the value of `DOTNET_ThreadPool_UnfairSemaphoreSpinLimit` because we should adjust the spin count automatically, but that doesn't seem to be happening?

I believe these are separate. We have:
1) How long to iterate a single `Yield` instruction to get, say, a normalized 70ns pause. @tannergooding recently raised some concerns about the way we do that - https://github.com/dotnet/runtime/issues/100242
2) How long to iterate the normalized Yield ^ before we fallback to OS wait - I bilieve this one is purely based on heuristics/measurements of whoever defined those.
