### ISSUE TITLE
[API Proposal]: WriteOnlySpan<T>

### ISSUE THREAD

**Issue by JustNrik** [dotnet/runtime#100302]
### Background and motivation

The main use-case for this struct would be to guarantee that it will never be read when passed to a method. You may wonder how is this useful? Basically, when recycling buffers (like when you use MemoryPool<T>.Shared), you normally have to clean them before passing them to somewhere as they will be filled with garbage data, this is not necessary all the times, really depends on what the method does with the span, but this struct would make it clear that you don't have to clear the buffer, you can just pass it and you'll know the method is not gonna read the garbage it has, but just straight up write on it.

### API Proposal

```csharp
namespace System;

public readonly ref struct WriteOnlySpan<T> 
{
    // All stuff Span<T> has but without read-access
}
```

### API Usage

```csharp
var memoryOwner = MemoryPool<double>.Shared.Rent(1024);
var memory = memoryOwner.Memory.Slice(0, 1024);
// memory.Span.Clear(); no needed to clear it since the garbage it has won't be read.
DoSomethingWithBuffer(memory.Span); // implicit convertion
```

### Risks

Probably resolution issues against ReadOnlySpan since both are implicit conversions from Span, although it wouldn't make much sense that 2 methods take one, readonly and the other writeonly span 🤔

**Comment by tannergooding** [comment]
It's worth noting what's being asked for here is not strictly `WriteOnlySpan`, but rather something more akin to how `out` works.

That is:
`Span<T>`: Works like `ref`, can read or write
`ReadOnlySpan<T>`: Works like `in` (or `ref readonly`), can read
`...`: Works like `out`, must write (initialize) before reading

I'm not really sure that this makes a lot of sense, particularly since its up to the callee to decide how the data is used and that if they need well-defined state, they can simply `span.Clear()` or similar instead. The general language integration and tracking that would be required to do this optimally, and ensure that all data is correctly initialized would be quite expensive and likely not worth it given the relatively trivial workarounds one can do.

**Comment by paulbartrum** [comment]
There's another potential use case here, which is exposing a span to a Direct3D/Vulkan GPU upload buffer.

According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-map):
> Applications should avoid CPU reads from pointers to resources on UPLOAD heaps, even accidently. CPU reads will work, but are prohibitively slow on many common GPU architectures.

Unlike the original use-case, in this case reading doesn't make sense even for data that the client has written/initialized.

**Comment by tannergooding** [comment]
Avoiding reads is not the same as not being able to read, there are still many valid use-cases for reading from an upload buffer (even if `DEFAULT` or `READBACK` is preferred). This can be particularly true for UMA type setups, although there can be other considerations.

You also might not want to use span here for other reasons, as `device memory` can sometimes work differently from regular memory (in terms of coherency, how unaligned reads/writes operate, etc) and so it might not meet the expectations placed on `ref T`, such that using `T*` is necessary instead.

Not to mention that if you're working directly with D3D/Vulkan, you're already in an extremely lowlevel and advanced scenario, where you're expected to know what you're doing. A higher level library might abstract things, but it would likely also be responsible for ensuring that things like `UPLOAD` heaps aren't directly exposed to the regular developer.

**Comment by tannergooding** [comment]
All in all, an `init-first` buffer (that operates similarly to `out`) is itself niche. A truly `write-only` buffer is an even more niche scenario.

Both of these are things are rare and unique enough that are likely better handled in the domain specific locations by analyzers and custom types defined by those third party libraries.

They don't really meet the criteria, in my opinion, for inclusion in the BCL.

**Comment by paulbartrum** [comment]
While I agree that these examples are niche, I personally think it would be quite useful to distinguish algorithms in the BCL that mutate a buffer vs those that overwrite a buffer without regard to the existing contents of that buffer. Right now any method that takes a Span<T> could be of either sort. Of course, that's only if the extra implicit conversions are free (or nearly so); I wouldn't want this to regress performance.

**Comment by tannergooding** [comment]
We have several years worth of APIs that already take span for that purpose and which couldn’t be changed due to the need to maintain back-compat.

The documentation (both IntelliSense and online) currently covers whether a given array/span is an input, output, or both.

**Comment by paulbartrum** [comment]
> We have several years worth of APIs that already take span for that purpose and which couldn’t be changed due to the need to maintain back-compat.

Oh I thought existing Span<T> methods could be changed to take WriteOnlySpan<T> due to an implicit conversion Span<T> -> WriteOnlySpan<T>. Thinking about it I guess that would be source-compatible but not binary-compatible, right? In that case this proposal seems much less valuable.

**Comment by tannergooding** [comment]
Right, it would be potentially source-compatible (for C# at least, not for all other languages) and binary incompatible.

There will potentially be new language features that would allow a general transition, but the cost doesn't justify the benefit and doesn't address many of the other conceptual issues that exist for other APIs that take things like arrays, collections, or other types that fit into the same general bucket.

This is, for the most part, a documentation concern and one that has a lot of per use-case nuance in how exactly a method deals with a given output buffer.
