### ISSUE TITLE
Reading from `Console.OpenStandardInput` hangs forever when stdin is closed

### ISSUE THREAD

**Issue by Smaug123** [dotnet/runtime#100323]
### Description

`System.Console.OpenStandardInput` on Unix systems (at least linux-x64, darwin-aarch64) somehow manages to open standard input even when standard input is closed. I am completely baffled, but am pretty certain this behaviour is wrong, because https://github.com/dotnet/runtime/issues/100321 (which is a failure mode I would actually predict in advance given the prompt "there is a bug in Console.OpenStandardInput when stdin is closed") demonstrates that this behaviour is unique to the .NET runtime.

### Reproduction Steps

Program.fs:
```fsharp
namespace ConsoleApp

open System

module Program =
    [<EntryPoint>]
    let main _argv =
        let stdin = Console.OpenStandardInput ()
        let buf = [| 0uy |]
        printfn "About to read."
        let read = stdin.Read (buf)
        if read > 0 then
            printfn "Read a byte!"
        elif read = 0 then
            printfn "Failed to read!"
        else
            printfn $"howwwww %i{read}"

        0
```

ConsoleApp.fsproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

### Expected behavior

Program runs and prints "Failed to read!", because the read call immediately returns 0.

### Actual behavior

```
> ./bin/Release/net8.0/osx-arm64/publish/ConsoleApp <&-
About to read.
```
(and then hangs forever)

### Configuration

```
> dotnet --info 
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: arm64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.201 [/nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Other information

Examining /proc/{pid}/fd, it seems that stdin (fd 0) is in fact open at the time when Console.OpenStandardInput copies the 0 file descriptor. (And it would have to be, otherwise the call to `dup` would fail.) I can't account for how it can possibly be open.

The value of `Console.IsInputRedirected` appears to be (presumably-correctly) `true` when stdin is closed in this way.

**Comment by MichalStrehovsky** [comment]
> manages to open standard input even when standard input is closed

It opens whatever thing got file descriptor 0. The OS assigns the first available one and you just made it available by closing it. This is opening something random and we don't even know what that is.
