### ISSUE TITLE
JsonSerializer.Deserialize/Serialize  using JsonTypeInfo fails on Type emitted using TypeBuilder.CreateType

### ISSUE THREAD

**Issue by vllama** [dotnet/runtime#100305]
### Description

An exception is thrown even though the emmited type has a parameterless constructor.  

> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized 
constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. 

Adding a default constructor using TypeBuilder.DefineDefaultConstructor(MethodAttributes)  seems to have no effect.

looking through the source at TryGetDeserializationConstructor  it should work correctly.

### Reproduction Steps

```[TestMethod]
public void MinimalFailCase() {

	AssemblyName asemblyName = new AssemblyName("Test.TestAssembly");
	AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(asemblyName, AssemblyBuilderAccess.Run);
	ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule("MainModule");

	TypeBuilder typeBuilder = moduleBuilder.DefineType("Test.TestAssembly.TestClass"
			, TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.AutoLayout | 
			  TypeAttributes.AutoClass |TypeAttributes.AnsiClass |TypeAttributes.BeforeFieldInit 					
			, parent: null);
        //ConstructorBuilder constructorBuilder = typeBuilder.DefineDefaultConstructor(MethodAttributes.Public);
	var theType = typeBuilder.CreateType();


	var cTor = theType.GetConstructor(Type.EmptyTypes);
	Debug.Assert(cTor != null, "empty constructor");

	ConstructorInfo[] cTors = theType.GetConstructors(BindingFlags.Public | BindingFlags.Instance);
	Debug.Assert(cTors != null && cTors.Length == 1  && cTors[0] != null, "empty constructor");

	object theTypeInstance = Activator.CreateInstance(theType);

	var tJsonTypeInfo = JsonTypeInfo.CreateJsonTypeInfo(theType, JsonSerializerOptions.Default);
	
	var theTypeSerialized = JsonSerializer.Serialize(theTypeInstance);
	
	// the two below fail 
	var theTypeSerializedFails = JsonSerializer.Serialize(theTypeInstance, tJsonTypeInfo);
	var commonObjectFails = JsonSerializer.Deserialize(theTypeSerialized, tJsonTypeInfo);
}
```

### Expected behavior

I would expect it to serialize and de-serialze the object.

### Actual behavior

Message: 
>Test method MARSworx.Middleware.Tests.CommonDataRuntimeTest.MinimalFailCase threw exception: 
System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Test.TestAssembly.TestClass'. Path: $ | LineNumber: 0 | BytePositionInLine: 1. ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Test.TestAssembly.TestClass'.

 Stack Trace: 
>ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
JsonSerializer.Deserialize(String json, JsonTypeInfo jsonTypeInfo)
CommonDataRuntimeTest.MinimalFailCase() line 130

### Configuration

.net 8
Windows 11 pro 64

**Comment by elgonzo** [comment]
TypeBuilder is a red herring with respect to the reported exception. Replace all the TypeBuilderStuff with an ordinary class declaration:
```C#
public class Foo
{
    public Foo() { }
}

var theType = typeof(Foo);
...
```
and you should still observe the exact same behavior.

If i am not mistaken, the reason of the observed behavior is `JsonTypeInfo.CreateJsonTypeInfo` returning a "_blank_" JsonTypeInfo. That's how the [documentation calls it](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.metadata.jsontypeinfo?view=net-8.0), with no explanation how such a "blank" JsonTypeInfo is usable/unusable in which situations.

To get a usable JsonTypeInfo for your type, i'd suggest you do something similar like this:
```C#
var tJsonTypeInfo = new DefaultJsonTypeInfoResolver().GetTypeInfo(theType, JsonSerializerOptions.Default);
```

**Comment by eiriktsarpalis** [comment]
What @elgonzo said. You should be using `JsonSerializerOptions.GetTypeInfo` if you're looking to get a contract derived from your options. The `JsonTypeInfo.CreateJsonTypeInfo` method is for creating unpopulated instances intended for [contract customization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts) scenaria.

**Comment by vllama** [comment]
> I am not sure why you are using a JsonTypeInfo in this situation instead of just passing the Type object to the De/Serialize method, but to get a usable JsonTypeInfo for your type i'd suggest you do something similar like this:

I was using it because while reading the documentation, it will be required when we use the library being written in an AOT context (Blazor), and it is recommended so that the code would not be optimized away from AOT, but I did not get that far.  Maybe I misunderstood how the source based serialization will work.

**Comment by elgonzo** [comment]
> Maybe I misunderstood how the source based serialization will work.

STJ source generation requires you to set up a [JsonSerializerContext](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0). But with respect to the code in your report, this is moot as STJ code generation isn't really applicable in your case.

The STJ source generator collects relevant metadata about the types involved in serialization and generates (C#) source code (hence the phrase "_source_ generation") with bespoke serialization-related code for these types that avoids reflection and which will thusly not only be more performant than reflection-based serialization but also play nicely with trimming and especially with AOT.

The STJ source generator runs at compile time, the generated source being then compiled by the C# compiler as part of your project, like any other source code file would. For this to work, the STJ source generator has to be able to inspect the relevant types at compile time. However, in your case there is no type for your TestClass to be found at compile time, so there is nothing the STJ source generator would be able to process here.
