### ISSUE TITLE
`OpenStandardInput` in PublishAot throws if stdin is closed

### ISSUE THREAD

**Issue by Smaug123** [dotnet/runtime#100321]
### Description

`System.Console.OpenStandardInput` is documented as throwing no exceptions, but in fact in a `PublishAot` context on Linux it will throw at stream construction time if stdin is closed. I haven't checked behaviour on any platform except darwin-aarch64. Note that I believe the non-PublishAot runtime *also* does the wrong thing when stdin is closed, but a different wrong thing (I'll be raising a separate bug report); I wouldn't try and match the behaviour of the .NET runtime here.

### Reproduction Steps

Program.fs:

```fsharp
 namespace ConsoleApp

 open System

 module Program =
     [<EntryPoint>]
     let main _argv =
         let stdin = Console.OpenStandardInput ()
         let buf = [| 0uy |]
         printfn "About to read."
         let read = stdin.Read (buf)
         if read > 0 then
             printfn "Read a byte!"
         elif read = 0 then
             printfn "Failed to read!"
         else
             printfn $"howwwww %i{read}"

         0
```
ConsoleApp.fsproj:
```xml
 <Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
     <OutputType>Exe</OutputType>
     <TargetFramework>net8.0</TargetFramework>
     <SelfContained>true</SelfContained>
     <PublishAot>true</PublishAot>
   </PropertyGroup>

   <ItemGroup>
     <Compile Include="Program.fs" />
   </ItemGroup>

 </Project>
```

### Expected behavior

Program runs and prints "Failed to read!"

### Actual behavior

```
> ./bin/Release/net8.0/osx-arm64/publish/ConsoleApp <&-
Unhandled Exception: System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Bad file descriptor
   --- End of inner exception stack trace ---
   at Interop.CheckIo[TSafeHandle](TSafeHandle, String, Boolean) + 0x78
   at System.ConsolePal.OpenStandardInput() + 0x4c
   at ConsoleApp.Program.main(String[] _argv) + 0x14
   at ConsoleApp!<BaseAddress>+0x1e45a8
```

### Configuration

```
> dotnet --info 
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: arm64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.201 [/nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/nix/store/9zqlmf2ja3rf72cmkba08x82cyf9hk9l-dotnet-sdk-8.0.201/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by MichalStrehovsky** [comment]
The difference between this and #100323 is just that a random thing gets file descriptor 0 in one case, and nothing has that descriptor in the other case.

You're putting the underlying environment into an undefined state. We don't define behaviors on the .NET side if the underlying environment is in an undefined state. The only reason why an exception is thrown is because the environment no longer conforms to the POSIX specification:

From https://pubs.opengroup.org/onlinepubs/9699919799/functions/execve.html:

> **If file descriptor 0, 1, or 2 would otherwise be closed** after a successful call to one of the exec family of functions, **implementations may open an unspecified file for the file descriptor** in the new process image. If a standard utility or a **conforming application is executed with file descriptor 0 not open for reading** or with file descriptor 1 or 2 not open for writing, the environment in which the utility or application is executed **shall be deemed non-conforming**, and consequently the utility or application might not behave as described in this standard.

**Comment by Smaug123** [comment]
Thanks, the spec is indeed clear and unambiguous! I wonder why nobody mentioned it during the several hours I spent searching for the answer.
