### ISSUE TITLE
Browser SignalRClientTests failing in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#100307]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=618222
Build error leg or test failing: Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/100222

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=618222
**Error message validated:** `[at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/26/2024 8:14:00 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[626284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626284)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626284&view=ms.vss-test-web.build-test-results-tab&runId=15360076&resultId=100165)|dotnet/runtime#100490|
|[625160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625160)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625160&view=ms.vss-test-web.build-test-results-tab&runId=15321878&resultId=100165)||
|[624831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624831)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624831&view=ms.vss-test-web.build-test-results-tab&runId=15309636&resultId=100165)|dotnet/runtime#100402|
|[624617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624617)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624617&view=ms.vss-test-web.build-test-results-tab&runId=15300812&resultId=100165)|dotnet/runtime#100283|
|[623842](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623842)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623842&view=ms.vss-test-web.build-test-results-tab&runId=15282764&resultId=100165)|dotnet/runtime#100402|
|[623810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623810)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623810&view=ms.vss-test-web.build-test-results-tab&runId=15280660&resultId=100165)|dotnet/runtime#100401|
|[622955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622955)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.IcuTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622955&view=ms.vss-test-web.build-test-results-tab&runId=15258400&resultId=100168)|dotnet/runtime#96169|
|[622813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622813)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MT.Blazor.SimpleMultiThreadedTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622813&view=ms.vss-test-web.build-test-results-tab&runId=15255614&resultId=100164)|dotnet/runtime#100266|
|[622808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622808)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622808&view=ms.vss-test-web.build-test-results-tab&runId=15255518&resultId=100165)||
|[622670](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622670)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622670&view=ms.vss-test-web.build-test-results-tab&runId=15251796&resultId=100165)|dotnet/runtime#100377|
|[622534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622534)|dotnet/runtime|[Workloads-Wasm.Build.Tests.MT.Blazor.SimpleMultiThreadedTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622534&view=ms.vss-test-web.build-test-results-tab&runId=15248980&resultId=100164)|dotnet/runtime#100410|
|[622469](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622469)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.DefaultTemplate_WithoutWorkload](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622469&view=ms.vss-test-web.build-test-results-tab&runId=15247444&resultId=100007)|dotnet/runtime#100141|
|[622346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622346)|dotnet/runtime|[Wasm.Build.Tests.Blazor.IcuTests.FullIcuFromRuntimePackWithInvariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622346&view=ms.vss-test-web.build-test-results-tab&runId=15243448&resultId=100117)|dotnet/runtime#100266|
|[622303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622303)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.AppSettingsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622303&view=ms.vss-test-web.build-test-results-tab&runId=15241656&resultId=100149)|dotnet/runtime#100073|
|[622138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622138)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622138&view=ms.vss-test-web.build-test-results-tab&runId=15234448&resultId=100165)|dotnet/runtime#99685|
|[622178](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622178)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.DownloadResourceProgressTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622178&view=ms.vss-test-web.build-test-results-tab&runId=15235254&resultId=100149)|dotnet/runtime#99673|
|[621984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621984)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.DebugLevelTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621984&view=ms.vss-test-web.build-test-results-tab&runId=15229530&resultId=100166)|dotnet/runtime#100141|
|[621934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621934)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621934&view=ms.vss-test-web.build-test-results-tab&runId=15228036&resultId=100165)|dotnet/runtime#99833|
|[621932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621932)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621932&view=ms.vss-test-web.build-test-results-tab&runId=15227966&resultId=100165)||
|[621337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621337)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621337&view=ms.vss-test-web.build-test-results-tab&runId=15208340&resultId=100165)|dotnet/runtime#100288|
|[620921](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620921)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620921&view=ms.vss-test-web.build-test-results-tab&runId=15204670&resultId=100167)|dotnet/runtime#99439|
|[621147](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621147)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621147&view=ms.vss-test-web.build-test-results-tab&runId=15203142&resultId=100167)|dotnet/runtime#100251|
|[621102](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621102)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621102&view=ms.vss-test-web.build-test-results-tab&runId=15202284&resultId=100165)|dotnet/runtime#100106|
|[621089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621089)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.Test_WasmStripILAfterAOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621089&view=ms.vss-test-web.build-test-results-tab&runId=15201402&resultId=100116)|dotnet/runtime#100141|
|[621015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621015)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621015&view=ms.vss-test-web.build-test-results-tab&runId=15200670&resultId=100165)|dotnet/runtime#100294|
|[620807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620807)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620807&view=ms.vss-test-web.build-test-results-tab&runId=15192862&resultId=100167)|dotnet/runtime#99901|
|[620702](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620702)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.AppsettingsTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620702&view=ms.vss-test-web.build-test-results-tab&runId=15187356&resultId=100168)|dotnet/runtime#100280|
|[620527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620527)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.DownloadResourceProgressTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620527&view=ms.vss-test-web.build-test-results-tab&runId=15180802&resultId=100168)|dotnet/runtime#100074|
|[620480](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620480)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620480&view=ms.vss-test-web.build-test-results-tab&runId=15180052&resultId=100165)|dotnet/runtime#100271|
|[620433](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620433)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620433&view=ms.vss-test-web.build-test-results-tab&runId=15178444&resultId=100165)||
|[620405](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620405)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620405&view=ms.vss-test-web.build-test-results-tab&runId=15177284&resultId=100165)|dotnet/runtime#100251|
|[620329](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620329)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620329&view=ms.vss-test-web.build-test-results-tab&runId=15174824&resultId=100165)|dotnet/runtime#100106|
|[619862](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619862)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619862&view=ms.vss-test-web.build-test-results-tab&runId=15163946&resultId=100165)|dotnet/runtime#99922|
|[619810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619810)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619810&view=ms.vss-test-web.build-test-results-tab&runId=15163056&resultId=100165)|dotnet/runtime#100266|
|[619304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619304)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MT.Blazor.SimpleMultiThreadedTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619304&view=ms.vss-test-web.build-test-results-tab&runId=15149560&resultId=100166)|dotnet/runtime#100294|
|[619029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619029)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MT.Blazor.SimpleMultiThreadedTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619029&view=ms.vss-test-web.build-test-results-tab&runId=15142056&resultId=100166)|dotnet/runtime#98559|
|[618890](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618890)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MT.Blazor.SimpleMultiThreadedTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618890&view=ms.vss-test-web.build-test-results-tab&runId=15138268&resultId=100168)|dotnet/runtime#99833|
|[618669](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618669)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618669&view=ms.vss-test-web.build-test-results-tab&runId=15132054&resultId=100167)|dotnet/runtime#99596|
|[618638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618638)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618638&view=ms.vss-test-web.build-test-results-tab&runId=15131100&resultId=100165)|dotnet/runtime#100272|
|[618222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618222)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618222&view=ms.vss-test-web.build-test-results-tab&runId=15129528&resultId=100165)|dotnet/runtime#100222|
|[618579](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618579)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618579&view=ms.vss-test-web.build-test-results-tab&runId=15129542&resultId=100135)|dotnet/runtime#100141|
|[618181](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618181)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.MT.Blazor.SimpleMultiThreadedTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618181&view=ms.vss-test-web.build-test-results-tab&runId=15121184&resultId=100168)|dotnet/runtime#98559|
|[617697](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617697)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617697&view=ms.vss-test-web.build-test-results-tab&runId=15109920&resultId=100165)|dotnet/runtime#98559|
|[617624](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617624)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617624&view=ms.vss-test-web.build-test-results-tab&runId=15107546&resultId=100165)|dotnet/runtime#99596|
|[617458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617458)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617458&view=ms.vss-test-web.build-test-results-tab&runId=15102508&resultId=100165)||
|[617166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617166)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617166&view=ms.vss-test-web.build-test-results-tab&runId=15096560&resultId=100165)|dotnet/runtime#100233|
|[607398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607398)|dotnet/runtime|[Workloads-Wasm.Build.Tests.TestAppScenarios.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607398&view=ms.vss-test-web.build-test-results-tab&runId=14808830&resultId=100166)|dotnet/runtime#99927|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|41|47|

**Comment by ilonatommy** [comment]
It's the same problem as https://github.com/dotnet/runtime/issues/99961, being fixed in https://github.com/dotnet/runtime/pull/100074
