### ISSUE TITLE
Trimmer fails with IL1012 when building a MAUI app

### ISSUE THREAD

**Issue by darutter0508** [dotnet/runtime#100357]
### Description

I have a .NET 8.0 MAUI app that I am trying to create the archive for publishing and am getting the following error:
ILLink : error IL1012: IL Trimmer has encountered an unexpected error.

There is no real explanation of what is happening. I do get some messages at the end of the process, but the message is different each time I try the archive. The latest one is:
Dereference of a possibly null reference.

This should not cause a failure, just a warning. Other messages have included notes about supplying values for properties within a constructor.

I am using Visual Studio for Mac and setting the active configuration to "Release" and targeting an android tablet attached to the mac.

### Reproduction Steps

I have a .NET 8.0 MAUI app that is built on abp.io commercial that works fine in debug mode and can be compiled in release mode. When I attempt to archive the app is when it generates the error.

### Expected behavior

I expect the archive to be generated and ready to deploy to Google.

### Actual behavior

Archive fails with ILLink error as described above.

### Regression?

unknown

### Known Workarounds

none known

### Configuration

.NET 8.0 MAUI
targeting Android
operating on MacOS Sonoma 14.4.1

**Comment by darutter0508** [comment]
Here is some additional information. There is another error reported when attempting to optimize the package.
error NETSDK1144: Optimizing assemblies for size failed. The message also indicate optimization can be disabled by setting PublishTrimmed to false, but when I did that I get an error stating that the RunAOTCompilation is only supported when trimming is enabled.

**Comment by vitek-karas** [comment]
The trimmer should print out details about the failure, but maybe it's not part of the normal output of the build. The best way to look into this would be to grab an MSBuild binlog. If you publish from the command line, just append `/bl` and it should produce `msbuild.binlog` file. Then you can open that with https://msbuildlog.com/ and look for the error and there should be more details there. It might also work to turn on more verbose build logging.

The IL1012 error should basically always print out a stack trace of the crash.
