### ISSUE TITLE
NET 8 Application crashes without a StackTrace Code: 0xc0000409

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#100335]
### Description

I've started the proccess inside of Visual Studio, but it does not halt, and also noch crashdump is created.

I get this message in the Event log:

Name der fehlerhaften Anwendung: MCC.Common.Services.TestServiceConsoleHost.exe, Version: 6.0.0.0, Zeitstempel: 0x65410000
Name des fehlerhaften Moduls: AGLink40_x64.dll, Version: 6.0.2.0, Zeitstempel: 0x65c1069d
Ausnahmecode: 0xc0000409
Fehleroffset: 0x00000000002faa2c
ID des fehlerhaften Prozesses: 0x0xA3F8
Startzeit der fehlerhaften Anwendung: 0x0x1DA80382DB066B1
Pfad der fehlerhaften Anwendung: D:\repos\mlog\mcc\MCC.V1.0\bin\mcc\MCC.Common.Services.TestServiceConsoleHost.exe
Pfad des fehlerhaften Moduls: D:\repos\mlog\mcc\MCC.V1.0\bin\mcc\lib\AGLink40_x64.dll
Berichtskennung: 1f3b14ce-a19c-447c-849c-7b7156b61ae8
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

and following Information Message:

Fehlerbucket 1653442673736137309, Typ 5
Ereignisname: BEX64
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: MCC.Common.Services.TestServiceConsoleHost.exe
P2: 6.0.0.0
P3: 65410000
P4: AGLink40_x64.dll
P5: 6.0.2.0
P6: 65c1069d
P7: 00000000002faa2c
P8: c0000409
P9: 0000000000000007
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a73a5aff-6b1f-459b-991a-05f52ec3efce.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2b4f3c6c-5952-4d2d-a8b1-f2c32e2b31c5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6c09a14d-a171-489e-a64a-f0aeee985306.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ab5a722a-cd03-46e4-90b2-7668c17e16af.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cde69654-4d6e-4f3e-b585-8fe20cfa5a26.tmp.xml

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MCC.Common.Servi_4c6cd85ade50284f3343c74c6affd3429b6964cb_0e5b276b_0ee5a47c-b681-4641-81e9-2afa32f78c07

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 1f3b14ce-a19c-447c-849c-7b7156b61ae8
Berichtstatus: 268435456
Bucket mit Hash: 28eaf969ad902b9df6f23559f883ba5d
CAB-Datei-Guid: 0

### Reproduction Steps

i can reproduce but only on our internal installations (but on different computers)

### Expected behavior

stacktrace, or eaven not to crash

### Actual behavior

crash without stacktrace

**Comment by jogibear9988** [comment]
I'm wrong, I've a CrashDump, but isn't a stacktrace in the eventlog possible?

similar issue here: https://github.com/dotnet/runtime/issues/76875

**Comment by jkotas** [comment]
0xc0000409 is stack buffer overrun. Windows will typically terminate the process immediately when stack buffer overrun is encountered, without giving anybody (including .NET runtime) any chance to intercept it.

**Comment by mangod9** [comment]
Hi @jogibear9988 , are you able to share a repro or a dump to investigate further? Is this a regression since upgrading to 8?

**Comment by jogibear9988** [comment]
No, I'll close for now. Will reopen if it reoccures or I could reproduce
