### ISSUE TITLE
Byte[] initializer error Expression or initializer expected

### ISSUE THREAD

**Issue by fzh233** [dotnet/runtime#100325]
### Description

I found that assigning [1, 2, 3] to a byte[] type can run normally, but VS will report an error: Expression or initializer expected
![image](https://github.com/dotnet/runtime/assets/43662175/64948d19-fa60-48f8-9329-76593b08a844)
![image](https://github.com/dotnet/runtime/assets/43662175/bdacaace-29ee-4091-b59e-75f849826902)

### Reproduction Steps

Below is my code example
```
var a = new A()
{
    TestBytes = [1, 2, 3]
};

Console.WriteLine();

public class A
{
    public byte[] TestBytes { get; set; }
}
```

### Expected behavior

VS should not report an error

### Actual behavior

VS error: Expression or initializer expected

### Configuration

Which version of .NET is the code running on?
My running environment is .net 8
![image](https://github.com/dotnet/runtime/assets/43662175/16557b9f-66fc-4f19-97b8-7be7f38def68)

What OS and version, and what distro if applicable?
Windows 10 22H2

What is the architecture (x64, x86, ARM, ARM64)?
x64

**Comment by huoyaoyuan** [comment]
It looks like you are on an old VS version that does not support C# 12 syntax. You code snippet works fine for me in VS 17.9.4.

**Comment by fzh233** [comment]
> It looks like you are on an old VS version that does not support C# 12 syntax. You code snippet works fine for me in VS 17.9.4.

Thank you for your response, huoyaoyuan. I apologize for not mentioning earlier that my Visual Studio version is 17.9.5. Unfortunately, my code snippet still isn't working properly.

![image](https://github.com/dotnet/runtime/assets/43662175/c3588a81-ca14-4239-a8b4-d9a6e7e81de6)
![image](https://github.com/dotnet/runtime/assets/43662175/069c2b58-eee6-4f69-86b6-83e178dd4760)

**Comment by pinkfloydx33** [comment]
Are these actual error messages in the errors list / when you compile? Or are they IDE only? Given that you're able to run the project I'm guessing IDE only. 

If so, do you happen to have Resharper installed? It will behave similarly unless you A. update it to a compatible version and B. make sure the C# version is set properly (or at least not override on a solution/project basis)

**Comment by CyrusNajmabadi** [comment]
'Expression or initializer expected' is not a VS or roslyn error message.  My guess is that this is resharper.

**Comment by fzh233** [comment]
> Are these actual error messages in the errors list / when you compile? Or are they IDE only? Given that you're able to run the project I'm guessing IDE only.
> 
> If so, do you happen to have Resharper installed? It will behave similarly unless you A. update it to a compatible version and B. make sure the C# version is set properly (or at least not overridden at the solution/project levels via a DotSettings file)



> 'Expression or initializer expected' is not a VS or roslyn error message. My guess is that this is resharper.

Yes, pinkfloydx33 and CyrusNajmabadi, after I disabled Resharper, the IDE no longer shows any errors. Thank you both!
