### ISSUE TITLE
[wasi] Cannot find host wasmtime

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#100394]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100251-merge-c074c630e8804e1ab3/Workloads-Wasi.Build.Tests.ILStripTests/1/console.2a5e5935.log?helixlogtype=result)
```
    Wasi.Build.Tests.ILStripTests.WasmStripILAfterAOT_TestDefaultAndOverride(stripILAfterAOT: "", expectILStripping: True, singleFileBundle: False) [FAIL]
       Expected 0 exit code but got 255: /root/helix/work/workitem/e/dotnet-latest/dotnet run --no-silent --no-build -c Release
      Standard Output:
      [Release_3ubcj3n5_xxb] WasmAppHost --runtime-config /root/helix/work/workitem/e/wbt artifacts/Release_3ubcj3n5_xxb/bin/Release/net9.0/wasi-wasm/AppBundle/Release_3ubcj3n5_xxb.runtimeconfig.json --no-silent
      [Release_3ubcj3n5_xxb] Error: Cannot find host wasmtime: Tried to look for wasmtime in PATH: /root/helix/work/workitem/e/dotnet-latest, /root/helix/work/correlation/dotnet-latest, /root/helix/work/correlation/xharness-cli, /root/helix/work/correlation/dotnet-cli, /root/helix/work/correlation/wasi-sdk, /root/helix/work/correlation/wasmtime, /home/helixbot/.jsvu/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin .

```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=621924

## Error Message

```json
{
  "ErrorMessage": "Cannot find host wasmtime",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=621924
**Error message validated:** `[Cannot find host wasmtime`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/28/2024 9:09:15 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[645396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645396)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645396&view=ms.vss-test-web.build-test-results-tab&runId=15927810&resultId=100008)|dotnet/runtime#100141|
|[645013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645013)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645013&view=ms.vss-test-web.build-test-results-tab&runId=15914690&resultId=100008)|dotnet/runtime#100272|
|[644758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644758)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644758&view=ms.vss-test-web.build-test-results-tab&runId=15905890&resultId=100008)|dotnet/runtime#101095|
|[640285](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640285)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640285&view=ms.vss-test-web.build-test-results-tab&runId=15782160&resultId=100006)|dotnet/runtime#100157|
|[640282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640282)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640282&view=ms.vss-test-web.build-test-results-tab&runId=15782026&resultId=100008)|dotnet/runtime#100938|
|[639606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639606)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639606&view=ms.vss-test-web.build-test-results-tab&runId=15762740&resultId=100008)|dotnet/runtime#100661|
|[639437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639437)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639437&view=ms.vss-test-web.build-test-results-tab&runId=15759176&resultId=100008)|dotnet/runtime#100520|
|[638169](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638169)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638169&view=ms.vss-test-web.build-test-results-tab&runId=15721626&resultId=100008)|dotnet/runtime#100407|
|[637618](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637618)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637618&view=ms.vss-test-web.build-test-results-tab&runId=15705418&resultId=100008)|dotnet/runtime#100407|
|[637478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637478)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637478&view=ms.vss-test-web.build-test-results-tab&runId=15701180&resultId=100008)|dotnet/runtime#100858|
|[637169](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637169)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637169&view=ms.vss-test-web.build-test-results-tab&runId=15691626&resultId=100008)|dotnet/runtime#100847|
|[637144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637144)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637144&view=ms.vss-test-web.build-test-results-tab&runId=15691304&resultId=100008)|dotnet/runtime#100846|
|[635807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635807)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635807&view=ms.vss-test-web.build-test-results-tab&runId=15649446&resultId=100008)|dotnet/runtime#100801|
|[635488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635488)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635488&view=ms.vss-test-web.build-test-results-tab&runId=15638880&resultId=100008)|dotnet/runtime#100386|
|[634844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634844)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634844&view=ms.vss-test-web.build-test-results-tab&runId=15616744&resultId=100008)|dotnet/runtime#100610|
|[634832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634832)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634832&view=ms.vss-test-web.build-test-results-tab&runId=15616548&resultId=100008)|dotnet/runtime#91042|
|[634711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634711)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634711&view=ms.vss-test-web.build-test-results-tab&runId=15612764&resultId=100008)|dotnet/runtime#100767|
|[633684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633684)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633684&view=ms.vss-test-web.build-test-results-tab&runId=15578184&resultId=100008)||
|[631271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631271)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631271&view=ms.vss-test-web.build-test-results-tab&runId=15510474&resultId=100008)|dotnet/runtime#100618|
|[630000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630000)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630000&view=ms.vss-test-web.build-test-results-tab&runId=15475436&resultId=100008)|dotnet/runtime#100407|
|[629576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629576)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629576&view=ms.vss-test-web.build-test-results-tab&runId=15458190&resultId=100008)|dotnet/runtime#100610|
|[629024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629024)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629024&view=ms.vss-test-web.build-test-results-tab&runId=15441036&resultId=100008)|dotnet/runtime#98492|
|[628517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628517)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628517&view=ms.vss-test-web.build-test-results-tab&runId=15427018&resultId=100008)|dotnet/runtime#98492|
|[627438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=627438)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=627438&view=ms.vss-test-web.build-test-results-tab&runId=15396900&resultId=100008)|dotnet/runtime#96169|
|[626872](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626872)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626872&view=ms.vss-test-web.build-test-results-tab&runId=15378280&resultId=100008)|dotnet/runtime#100517|
|[624831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624831)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624831&view=ms.vss-test-web.build-test-results-tab&runId=15308104&resultId=100008)|dotnet/runtime#100402|
|[623845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623845)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623845&view=ms.vss-test-web.build-test-results-tab&runId=15280784&resultId=100008)|dotnet/runtime#100283|
|[623635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623635)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623635&view=ms.vss-test-web.build-test-results-tab&runId=15274964&resultId=100008)|dotnet/runtime#100141|
|[622955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622955)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622955&view=ms.vss-test-web.build-test-results-tab&runId=15257528&resultId=100008)|dotnet/runtime#96169|
|[621924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621924)|dotnet/runtime|[Wasi.Build.Tests.WasiTemplateTests.ConsoleBuildThenRunThenPublish](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621924&view=ms.vss-test-web.build-test-results-tab&runId=15226910&resultId=100007)|dotnet/runtime#100251|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|30|

**Comment by pavelsavara** [comment]
cc @akoeplinger

**Comment by akoeplinger** [comment]
It looks like wasmtime is missing from the correlation payload which suggests to me something goes wrong here: https://github.com/dotnet/runtime/blob/83b0d939bedadf7d782b0b26307c2d8c1d5b76f4/src/libraries/sendtohelix-wasi.targets#L19-L24

**Comment by maraf** [comment]
I'm not seeing it anymore

**Comment by maraf** [comment]
It looks like some AzDO machines have "broken" wasmtime installation. The collection payload for wasmtime is empty zip on them, while on the "others" is contains wasmtime

**Comment by lewing** [comment]
@dotnet/dnceng this is an intermittent failure on linux that appears to be container related, nothing is changing on our side

**Comment by maraf** [comment]
Missing wasmtime
![image](https://github.com/dotnet/runtime/assets/10020471/7e59decd-9a41-41a7-bf4e-d16d58cde34a)

Worming wasmtime
![image](https://github.com/dotnet/runtime/assets/10020471/cd963ecf-cd38-4262-b273-9bc7871d4be4)

**Comment by maraf** [comment]
The content of wasmtime on working case
![image](https://github.com/dotnet/runtime/assets/10020471/d9a79fc1-2abb-4f48-b1af-0ee8ba69f03d)

**Comment by pavelsavara** [comment]
> The content of wasmtime on working case (it's not a symlink or something)

Do we have the same for non-working image ?

**Comment by maraf** [comment]
Not yet. I'm starting to think about merging this info in main

**Comment by maraf** [comment]
Info from build
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645013&view=artifacts&pathAsName=false&type=publishedArtifacts)
[SendToHelix.binlog](https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzY0NTAxMy9hcnRpZmFjdE5hbWUvTG9nc19CdWlsZF9BdHRlbXB0MV93YXNpX3dhc21fbGludXhfUmVsZWFzZV9XYXNtQnVpbGRUZXN0cw2/content?format=file&subPath=%2FRelease%2FSendToHelix.binlog)

Source folder
```
Exec
    Assembly = Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    Parameters
        Command = ls -lsa /usr/local/wasmtime
    CommandLineArguments = ls -lsa /usr/local/wasmtime
    total 19764
        4 drwxr-xr-x 2 root root                       4096 Mar 26 19:59 .
        4 drwxr-xr-x 1 root root                       4096 Mar 26 19:59 ..
       12 -rw-r--r-- 1 1001 azure_pipelines_docker    12243 Jan 20  2023 LICENSE
        8 -rw-r--r-- 1 1001 azure_pipelines_docker     6610 Jan 20  2023 README.md
    19732 -rwxr-xr-x 1 1001 azure_pipelines_docker 20204640 Jan 20  2023 wasmtime
        4 -rw-r--r-- 1 root root                          6 Mar 26 19:59 wasmtime-version.txt
```
Correlation folder
```
Exec
    Assembly = Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    Parameters
        Command = ls -lsa /__w/1/s/artifacts/obj/helix-staging/wasmtime
    CommandLineArguments = ls -lsa /__w/1/s/artifacts/obj/helix-staging/wasmtime
    total 19764
        4 drwxr-xr-x 2 cloudtest_azpcontainer cloudtest_azpcontainer     4096 Apr 16 08:26 .
        4 drwxr-xr-x 4 cloudtest_azpcontainer cloudtest_azpcontainer     4096 Apr 16 08:26 ..
       12 -rw-r--r-- 1 cloudtest_azpcontainer cloudtest_azpcontainer    12243 Jan 20  2023 LICENSE
        8 -rw-r--r-- 1 cloudtest_azpcontainer cloudtest_azpcontainer     6610 Jan 20  2023 README.md
    19732 -rwxr-xr-x 1 cloudtest_azpcontainer cloudtest_azpcontainer 20204640 Jan 20  2023 wasmtime
        4 -rw-r--r-- 1 cloudtest_azpcontainer cloudtest_azpcontainer        6 Mar 26 19:59 wasmtime-version.txt
```

![image](https://github.com/dotnet/runtime/assets/10020471/8db8f3ab-bcdb-4f9b-8ab8-cf0292f4a8e4)

Correlation payload **is empty** https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-688688a5-2889-4ac0-a64f-0493e42e4d7ef03a1c00e8144989a/df58291e-6f6f-455a-befb-d41e018b2fab.zip?helixlogtype=result

**Comment by lewing** [comment]
Is this still matching the correct failures?

**Comment by maraf** [comment]
@pavelsavara You saw this on lib tests, right? But all of the matches are from WBT 🤔

**Comment by maraf** [comment]
Also, we won't see it after https://github.com/dotnet/runtime/pull/101392

**Comment by pavelsavara** [comment]
> @pavelsavara You saw this on lib tests, right? But all of the matches are from WBT 🤔

I just saw `ls -lsa` twice because `BuildHelixItems` -> `PrepareHelixCorrelationPayload_Wasi` is called twice. In `Build` and in `Test` which are separate MSBuild runs. I don't know why.

> Also, we won't see it after #101392

I'm not sure about that, why you think so ?
It will get downloaded every time on 
- as before on windows
- now as well on linux

**Comment by maraf** [comment]
> I'm not sure about that, why you think so ?

My bad, sorry

**Comment by pavelsavara** [comment]
well maybe it will fix because you saw it on linux, which was using pre-installed. Not it will be fresh every time.

**Comment by maraf** [comment]
Theory
- `sendtohelixhelp.proj` runs in parallel for two scenarios (workloads, noworkloads)
  - First runs `StageDependenciesForHelix`, because `@(__HelixDependenciesToStageThatDontExist->Count()) > 0`
    - 1) It creates folders for payloads
    - 2) It copies (a lot of) files
    - 5) Copying files is finished
    - 6) Executes `SendToHelixJob`, but zips are already uploaded, reusing them
  - Second doesn't run `StageDependenciesForHelix`, because `@(__HelixDependenciesToStageThatDontExist->Count()) == 0`
    - 3) Folders for payloads already exist
    - 4) Pass them to `SendToHelixJob`, which zips folders and upload them

According to this theory, WASI SDK payloads shouldn't be always complete

**Comment by pavelsavara** [comment]
workloads, noworkloads are not scenarios

**Comment by lewing** [comment]
reopening for a few days to let the fix make it into prs
