### ISSUE TITLE
Time-outs in `System.Net.Http.Functional.Tests` on Windows/arm64 CoreCLR

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#100328]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=618649
Build error leg or test failing: System.Net.Http.Functional.Tests

Failing `windows-arm64 Release Libraries_Release_CoreCLR` job on `runtime-extra-platforms`.

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: SyncSpan, useSsl: True) [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

[Error log](https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-100227-merge-43e5d41f5c0c41a284/System.Net.Http.Functional.Tests/3/console.42a4f7d0.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-100227-merge-43e5d41f5c0c41a284/System.Net.Http.Functional.Tests/3/console.42a4f7d0.log?helixlogtype=result))
```
 System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: SyncSpan, useSsl: True) [FAIL]
      System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
      ---- System.TimeoutException : The operation was canceled.
      -------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
      ------------ System.IO.IOException : The read operation failed, see inner exception.
      ---------------- System.ObjectDisposedException : Cannot access a disposed object.
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=618649
**Error message validated:** `[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: SyncSpan, useSsl: True) [FAIL]`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 3/27/2024 5:51:27 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[697183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697183)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_RequestContentLengthMismatchTest_Http3.ContentLength_DoesNotMatchRequestContentLength_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697183&view=ms.vss-test-web.build-test-results-tab&runId=17338526&resultId=212521)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by matouskozak** [comment]
> removing blocking-clean-ci as it has not failed in 30 days
> 
> 24-Hour Hit Count	7-Day Hit Count	1-Month Count
> 0	0	0

Per our offline discussion, the no-hits are caused by Build Analysis not running on the `runtime-extra-platforms` pipeline (cc: @AlitzelMendez). The failures are still present on main rolling builds (e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=621391&view=logs&jobId=542c931e-8293-51c7-dbad-a0a58a58ddc4&j=542c931e-8293-51c7-dbad-a0a58a58ddc4&t=9c7b0705-aa05-5c85-78fa-e85c2a87ac24).

**Comment by liveans** [comment]
No failure or re-runs `Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream` within 30 days in main, reported issue in the table is from `release/8.0-staging`.
