### ISSUE TITLE
System.Linq.Enumeration.Chunk - CS0121: The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by pjirsa** [dotnet/runtime#100370]
https://github.com/dotnet/runtime/blob/3f7ffddedad2a43c919b5144dbea3d4307d10623/src/libraries/System.Linq/src/System/Linq/Chunk.cs#L36

I'm creating a brand-new blank console app with `dotnet new console`. When I try to use the `Chunk` extension method on a simple array or list, it results in the following error:

```
Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Chunk<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)' and 'System.Linq.Enumerable.Chunk<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)'
```

**Comment by stephentoub** [comment]
Can you share a repro, both csproj and cs files?

**Comment by pjirsa** [comment]
@stephentoub thanks for the quick reply. I discovered that there was "sample" code polluting the namespace with an alternate implementation of the same extension method name.
