### ISSUE TITLE
[API Proposal]: Change Microsoft.Extensions.Hosting.Environments fields to consts

### ISSUE THREAD

**Issue by gdoron** [dotnet/runtime#100396]
### Background and motivation

Is there a reason the names of the envs are static readonly and not consts?

https://github.com/dotnet/runtime/blob/71e989d1b5641024655800cbae43f62895544692/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/Environments.cs#L15-L25

Because they are not consts, we cannot use them in attributes, such as:

```csharp
    [Theory]
    [InlineData("Production")]
    [InlineData("Staging")]
    [InlineData("Development")]
    public async Task Sso_InvalidUrl_Throws(string envName) {
```

### API Proposal

Changing them to consts.

### API Usage

same.

**Comment by huoyaoyuan** [comment]
Unfortunately, changing between `const` and `static readonly` is a breaking change. `string.Empty` has been `static readonly` for decades.

From https://stackoverflow.com/questions/27097198/cil-how-do-i-use-a-public-static-literal-field

> I.8.6.1.2 Location signatures
>
> The **literal constraint** promises that the value of the location is actually a fixed value of a built-in type. The value is specified as part of the constraint. Compilers are required to replace all references to the location with its value, and the VES therefore need not allocate space for the location. This constraint, while logically applicable to any location, shall only be placed on static fields of compound types. **Fields that are so marked are not permitted to be referenced from CIL** (they shall be in-lined to their constant value at compile time), but are available using reflection and tools that directly deal with the metadata.

**Comment by colejohnson66** [comment]
In shorter words: `const` values don't "exist" at runtime, except through reflection. You can't load them like you can fields.

**Comment by teo-tsirpanis** [comment]
Closing as non-actionable. In your case you can write `[InlineData(nameof(Environment.Production))]`.
