### ISSUE TITLE
Make CoreCLR compatible with W^X

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#10036]
https://en.wikipedia.org/wiki/W%5EX

**Comment by tannergooding** [comment]
It looks like this will be required to support the new Apple Silicon (Arm on macOS): https://github.com/mono/mono/pull/20014

**Comment by lambdageek** [comment]
> It looks like this will be required to support the new Apple Silicon (Arm on macOS): [mono/mono#20014](https://github.com/mono/mono/pull/20014)

The relevant Apple guidance is https://developer.apple.com/documentation/apple_silicon/porting_just-in-time_compilers_to_apple_silicon

> New memory pages start out as readable and executable (R-X) by default. Calling `pthread_jit_write_protect_np` with the value false removes the executable permission for the current thread and adds the writable permission (RW-). The change applies only to the current thread; other threads that write to the JIT memory region must similarly call the function before writing any data. When write protections are disabled, the thread may write instructions to the JIT memory page, but it may not execute those instructions.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/50391
