### ISSUE TITLE
Simple double multiplication returns wrong result

### ISSUE THREAD

**Issue by dirivero** [dotnet/runtime#100367]
### Description

Multiplying 0.7 by 330 results in 230.99999999999997
Using a float instead of a double returns 231 correctly.

### Reproduction Steps

In a console project write this:

Console.WriteLine(.7d * 330); // WRONG
Console.WriteLine(.7f * 330); // CORRECT

### Expected behavior

Both should return 231.

### Actual behavior

Double operation returns 230.99999999999997

### Regression?

Worked fine in NET 4.7.2. 
Doesn't work in .NET Core 3.1, .NET 5, .NET 6, .NET 7 and , .NET 8.

**Comment by tannergooding** [comment]
There are other resources on the internet that go more in depth into how binary-based floating-point numbers if you'd like to learn more.

Some examples include:
* https://www.exploringbinary.com/
* https://en.wikipedia.org/wiki/IEEE_754
* https://en.wikipedia.org/wiki/Single-precision_floating-point_format
* https://en.wikipedia.org/wiki/Double-precision_floating-point_format
* https://www.cs.cornell.edu/~tomf/notes/cps104/floating.html
* https://0.30000000000000004.com/
* etc

**Comment by dirivero** [comment]
Thanks for the explanation @tannergooding, good to know that it always behaved like this.
