### ISSUE TITLE
IL2026 and IL3050 code fixers generate invalid code

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#100474]
### Description

The `RequiresDynamicCodeCodeFixProvider` and `RequiresUnreferencedCodeCodeFixProvider` code fixers for IL2026 and IL3050 generate a code fix that does not compile (I'm also not convinced they should be trying to fix my code at all, but if that's the case that's a separate issue).

Running `dotnet format analyzers` on code with a method where these diagnostics are emitted will add the following attributes to the method:

```csharp
[RequiresDynamicCode()]
[RequiresUnreferencedCode()]
```

This code does not compile because neither attribute has a parameterless constructor.

Both fixers call into the following method:

https://github.com/dotnet/runtime/blob/1949bd2e017a0dc1e48b7cfed263051a6ed147a5/src/tools/illink/src/ILLink.CodeFix/RequiresHelpers.cs#L13-L20

It looks like the `hasPublicAccessibility` check is incorrect (maybe the API surface changed at some point), and instead the method should use the other branch to emit the following code instead:

```csharp
[RequiresDynamicCode("Calls SYMBOL_NAME_HERE")]
[RequiresUnreferencedCode("Calls SYMBOL_NAME_HERE")]
```

I can replicate this with both the `8.0.203` and `9.0.100-preview.2.24157.14` SDKs.

### Reproduction Steps

1. Clone https://github.com/martincostello/alexa-london-travel/commit/323d0b44fbbd631d537d495f5d7c3efcac22761d
2. Run `dotnet format analyzers --verbosity diagnostic`

### Expected behavior

Attributes are added which compile (or are not added at all, as my code works without the attributes being present).

### Actual behavior

Attributes are added that do not compile.

### Regression?

Unknown.

### Known Workarounds

Disable the IL2026 and IL3050 diagnostics in `.editorconfig`.

### Configuration

.NET SDK 8.0.203 and 9.0.100-preview.2.24157.14 on both Windows and Ubuntu.

**Comment by agocke** [comment]
There's no message that would be acceptable to automatically add to a user's public API. This is currently by-design, to force the user to specify an accurate message.
