### ISSUE TITLE
Failed test: baseservices/exceptions/unhandled/unhandledTester/unhandledTester

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#100495]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=625874
Build error leg or test failing: baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd
Pull request: https://github.com/dotnet/runtime/pull/100375

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Failed test: baseservices/exceptions/unhandled/unhandledTester/unhandledTester",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=625874
**Error message validated:** `[Failed test: baseservices/exceptions/unhandled/unhandledTester/unhandledTester`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/1/2024 7:18:14 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[750859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750859)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750859&view=ms.vss-test-web.build-test-results-tab&runId=19014554&resultId=111410)|dotnet/runtime#105278|
|[750809](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750809)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750809&view=ms.vss-test-web.build-test-results-tab&runId=19013570&resultId=111410)||
|[750537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750537)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750537&view=ms.vss-test-web.build-test-results-tab&runId=19005880&resultId=111410)|dotnet/runtime#105206|
|[748928](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748928)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748928&view=ms.vss-test-web.build-test-results-tab&runId=18945620&resultId=111410)|dotnet/runtime#105185|
|[748909](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748909)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748909&view=ms.vss-test-web.build-test-results-tab&runId=18944990&resultId=111410)|dotnet/runtime#105184|
|[746435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746435)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746435&view=ms.vss-test-web.build-test-results-tab&runId=18870062&resultId=111409)|dotnet/runtime#104731|
|[733445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733445)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733445&view=ms.vss-test-web.build-test-results-tab&runId=18466062&resultId=111407)|dotnet/runtime#104458|
|[725502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725502)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725502&view=ms.vss-test-web.build-test-results-tab&runId=18221458&resultId=111407)||
|[723841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=723841)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=723841&view=ms.vss-test-web.build-test-results-tab&runId=18166778&resultId=111407)|dotnet/runtime#104104|
|[721862](https://dev.azure.com/dnceng-public/public/_build/results?buildId=721862)|dotnet/runtime|[baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=721862&view=ms.vss-test-web.build-test-results-tab&runId=18112108&resultId=111406)|dotnet/runtime#104003|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|10|

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
There is something wrong with the test infra. It seems that it executes the testing apps that fail with unhandled exception as separate tests even though they have `<CLRTestKind>BuildOnly</CLRTestKind>` in their .csproj files. As you can see below, the unhandled.sh was executed and then the two sub-projects that are not supposed to be run separately were run too.
```
06:04:08.457 Passed test: baseservices/exceptions/unhandled/unhandled/unhandled.cmd
06:04:08.461 Running test: baseservices/exceptions/unhandled/unhandledmissingdependency/unhandledmissingdependency.cmd
Test executable '/private/tmp/helix/working/A7D20967/w/B6100991/e/baseservices/exceptions/baseservices-exceptions/../unhandled/unhandledmissingdependency/unhandledmissingdependency.sh' not found, skipping.
06:04:08.465 Passed test: baseservices/exceptions/unhandled/unhandledmissingdependency/unhandledmissingdependency.cmd
06:04:08.472 Running test: baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd
```

@jkoritzinsky do you have any idea what could be wrong with it?

**Comment by janvorli** [comment]
Hmm, maybe that's just a quirk and the helpers were actually not executed separately.

**Comment by janvorli** [comment]
Anyways, given the logs I have added to the test recently, I can see that the main test never completes waiting for the child test helper process.

**Comment by janvorli** [comment]
All the failures are on macOS x64, a recent PR has disabled this test on this platform.
