### ISSUE TITLE
Does NativeAOT have its own API, with which it gets the names of methods and their addresses for Stacktrace?

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#100486]
Which method in the NativeAOT project is responsible for obtaining the names of methods and their addresses when Stacktrace support and reflection are enabled?

Perhaps I'm asking the question incorrectly, but I don't know how to ask it differently. For example, Unity has a similar technology called IL2CPP. And it has its own api, through which you can get the names of assemblies, classes, fields, and their addresses.

**Comment by jkotas** [comment]
> Does NativeAOT have its own API, with which it gets the names of methods and their addresses for Stacktrace?

There are NativeAOT-specific managed APIs. All variants of .NET runtime dotnet/runtime expose the same set of managed APIs.

What is the problem that you are trying to solve?

**Comment by dadavadd** [comment]
> > Does NativeAOT have its own API, with which it gets the names of methods and their addresses for Stacktrace?
> 
> There are NativeAOT-specific managed APIs. All variants of .NET runtime dotnet/runtime expose the same set of managed APIs.
> 
> What is the problem that you are trying to solve?

I want to get a list of function names and their addresses from the outside via injection into my DLL process by calling that function with certain arguments.

**Comment by dadavadd** [comment]
> > Does NativeAOT have its own API, with which it gets the names of methods and their addresses for Stacktrace?
> 
> There are NativeAOT-specific managed APIs. All variants of .NET runtime dotnet/runtime expose the same set of managed APIs.
> 
> What is the problem that you are trying to solve?

For example, using these function calls, I could get the names and addresses of everything possible from a project compiled using IL2CPP. Is it possible to get at least 10% of this type of information from NativeAOT? And does NativeAOT have similar functions. Again: I may be asking the question incorrectly because I'm translating my question through Google Translate.
![image](https://github.com/dotnet/runtime/assets/111659964/4a9ebb4e-ce51-4b56-a2eb-3297838bd9af)

**Comment by jkotas** [comment]
.NET runtimes variants in this repo do not have public unmanaged APIs like that.

> Is it possible to get at least 10% of this type of information from NativeAOT?

Yes, it is possible using managed reflection APIs. If you need to get this information from external unmanaged code, you can create `UnmanagedCallersOnly` wrappers for the managed reflection APIs.

**Comment by MichalPetryka** [comment]
> .NET runtimes variants in this repo do not have public unmanaged APIs like that.

From what I've seen, Unity has added a lot of such unmanaged APIs in their fork of .NET, will those get accepted for upstreaming or will Unity need to find some other solution for their needs?

**Comment by jkotas** [comment]
Our default strategy is to expose managed APIs and encourage people to wrap them in a shape that fits their requirements if they need to call the API from unmanaged code. Function pointers in C#, `UnmanagedCallersOnly`, or #67090 are contributing to this strategy. Unity general approach is aligned with this strategy.

To bootstrap the CoreCLR port, Unity built a partial emulator of Mono embedding APIs that they have been eliminating and cleaning up - compare https://github.com/Unity-Technologies/runtime/commit/9e2c0f36529ab724fb2dc22bb30f609ea1c61062#diff-b5156dab0921e8ed3be144cbea6abc9fbc4fc618b9c11bf5be381f14ec21f3e0R33-R117 with https://github.com/Unity-Technologies/runtime/blob/unity-main/src/coreclr/dlls/mscoree/mscorwks_ntdef.src#L33-L77. We have engoing discussions with them on the best way to address each case. The North Star is to eliminate the delta between their fork and upstream, but it does not mean to upstream what they have there currently.

**Comment by agocke** [comment]
Closing this question as answered -- we can continue to deal with individual API requests as individual issues.
