### ISSUE TITLE
Test failure: ValueFactory attempted to access the Value property of this instance.

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100476]
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20240331.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625354&view=ms.vss-test-web.build-test-results-tab&runId=15328934&resultId=109747&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.ARM64.Open
    - JIT/Methodical/eh/basics/throwinclassconstructor_d/throwinclassconstructor_d.dll
```

**Error message:**
```
 ValueFactory attempted to access the Value property of this instance.
```

**Stack trace:**
```
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Program.<<Main>$>g__TestExecutor273|0_274(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20240406.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633144&view=ms.vss-test-web.build-test-results-tab&runId=15566352&resultId=106017&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.ARM64.Open
    - JIT/Methodical/eh/basics/throwinclassconstructor_d/throwinclassconstructor_d.dll
```

**Error message:**
```
 ValueFactory attempted to access the Value property of this instance.
```

**Stack trace:**
```
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Program.<<Main>$>g__TestExecutor273|0_274(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by kunalspathak** [comment]
@janvorli - This test passes with `DOTNET_LegacyExceptionHandling=1`. Assigning to you.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20240414.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=642857&view=ms.vss-test-web.build-test-results-tab&runId=15857854&resultId=113972&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.ARM64.Open
    - JIT/Methodical/eh/basics/throwinclassconstructor_d/throwinclassconstructor_d.dll
```

**Error message:**
```
 ValueFactory attempted to access the Value property of this instance.
```

**Stack trace:**
```
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Program.<<Main>$>g__TestExecutor273|0_274(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by janvorli** [comment]
@kunalspathak I am unable to repro it on my Apple M1. I've set COMPlus_TieredCompilation=0 COMPlus_JitStress=2 COMPlus_JitStressRegs=0x80 and ran the `./artifacts/tests/coreclr/osx.arm64.Checked/JIT/Methodical/Methodical_d1/Methodical_d1.sh`
Were you able to repro the issue locally?

**Comment by janvorli** [comment]
Interestingly, without COMPlus_JitStress=2, it doesn't call the 
`CORINFO_HELP_GETSHARED_GCTHREADSTATIC_BASE_DYNAMICCLASS` that is getting the address that we later end up reading "1" from and then attempt to read at an offset from this value, which obviously results in the null reference (in my local run)

**Comment by kunalspathak** [comment]
> Interestingly, without COMPlus_JitStress=2, it doesn't call the `CORINFO_HELP_GETSHARED_GCTHREADSTATIC_BASE_DYNAMICCLASS` that is getting the address that we later end up reading "1" from and then attempt to read at an offset from this value, which obviously results in the null reference (in my local run) It seems that (if I correlated the JIT dumps correctly), without COMPlus_JitStress=2, it ends up calling `` System.Threading.ThreadLocal``1[System.__Canon]:get_Value():System.__Canon:this `` instead.

and what happens when you set `DOTNET_LegacyExceptionHandling=1`?

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20240421.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651209&view=ms.vss-test-web.build-test-results-tab&runId=16101088&resultId=112576&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.ARM64.Open
    - JIT/Methodical/eh/basics/throwinclassconstructor_d/throwinclassconstructor_d.dll
```

**Error message:**
```
 ValueFactory attempted to access the Value property of this instance.
```

**Stack trace:**
```
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Program.<<Main>$>g__TestExecutor273|0_274(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by janvorli** [comment]
> and what happens when you set `DOTNET_LegacyExceptionHandling=1`

Exactly the same as without it.

**Comment by JulieLeeMSFT** [comment]
It is still failing in [runtime-coreclr jitstress2-jitstressregs](https://dev.azure.com/dnceng-public/public/_build?definitionId=111&_a=summary). 
@janvorli, so what would be the next step?

**Comment by JulieLeeMSFT** [comment]
link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=660114&view=ms.vss-test-web.build-test-results-tab&runId=16358166&resultId=107955&paneView=debug

**Comment by kunalspathak** [comment]
I pulled in the latest artifacts from https://dev.azure.com/dnceng-public/public/_build/results?buildId=664183&view=ms.vss-test-web.build-test-results-tab&runId=16472434&resultId=105819&paneView=debug and was able to repro it on my Mac M2:

<img width="870" alt="image" src="https://github.com/dotnet/runtime/assets/12488060/0a957063-ee24-40b8-9e79-67a627af4e9c">

**Comment by janvorli** [comment]
I can repro it with runfo using the build from your recent link.
