### ISSUE TITLE
[API Proposal]:Count method

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#100467]
### Background and motivation

I suggest adding a cast to the array in the Count method.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Count.cs

### API Proposal

```csharp

int Count<T>(IEnumerable<T> array)
{
    if(array is T[] res){
        return res.Length;
    }
    throw new Exception();
}
```

### API Usage

```csharp

Console.WriteLine(Count(new int[]{1}));
```

**Comment by huoyaoyuan** [comment]
This does not require new API. It's just internal optimization of LINQ.

Since array already implementents `ICollection<TSource>`, the overhead is just one virtual call, not the allocation and multiple virtual calls per element when using `GetEnumerator`. There should be a strong number showing the difference.

**Comment by huoyaoyuan** [comment]
Did a simple benchmark:

| Method        | Mean     | Error     | StdDev    |
|-------------- |---------:|----------:|----------:|
| ArrayMyCount1 | 3.960 ns | 0.0045 ns | 0.0037 ns |
| ArrayMyCount2 | 1.202 ns | 0.0080 ns | 0.0071 ns |
| ListMyCount1  | 1.403 ns | 0.0071 ns | 0.0067 ns |
| ListMyCount2  | 2.676 ns | 0.0161 ns | 0.0150 ns |

It can improve performance for array, but harms performance of non-array types because of the additional check.

```csharp
        private int[] array = [1, 2, 3];
        private List<int> list = [1, 2, 3];

        [Benchmark]
        public int ArrayMyCount1() => MyCount1(array);

        [Benchmark]
        public int ArrayMyCount2() => MyCount2(array);
        
        [Benchmark]
        public int ListMyCount1() => MyCount1(list);

        [Benchmark]
        public int ListMyCount2() => MyCount2(list);


        public static int MyCount1<TSource>(IEnumerable<TSource> source)
        {
            if (source is null)
            {
                ArgumentNullException.ThrowIfNull(source);
            }

            if (source is ICollection<TSource> collectionoft)
            {
                return collectionoft.Count;
            }

            if (source is ICollection collection)
            {
                return collection.Count;
            }

            int count = 0;
            using (IEnumerator<TSource> e = source.GetEnumerator())
            {
                checked
                {
                    while (e.MoveNext())
                    {
                        count++;
                    }
                }
            }

            return count;
        }

        public static int MyCount2<TSource>(IEnumerable<TSource> source)
        {
            if (source is null)
            {
                ArgumentNullException.ThrowIfNull(source);
            }

            if (source is TSource[] array)
            {
                return array.Length;
            }

            if (source is ICollection<TSource> collectionoft)
            {
                return collectionoft.Count;
            }

            if (source is ICollection collection)
            {
                return collection.Count;
            }

            int count = 0;
            using (IEnumerator<TSource> e = source.GetEnumerator())
            {
                checked
                {
                    while (e.MoveNext())
                    {
                        count++;
                    }
                }
            }

            return count;
        }
```

**Comment by Mr0N** [comment]
> This does not require new API. It's just internal optimization of LINQ.
> 
> Since array already implementents `ICollection<TSource>`, the overhead is just one virtual call, not the allocation and multiple virtual calls per element when using `GetEnumerator`. There should be a strong number showing the difference.

The array does not have the Count property, how can it be implemented in ICollection?

**Comment by Mr0N** [comment]
> Did a simple benchmark:
> 
> Method	Mean	Error	StdDev
> ArrayMyCount1	3.960 ns	0.0045 ns	0.0037 ns
> ArrayMyCount2	1.202 ns	0.0080 ns	0.0071 ns
> ListMyCount1	1.403 ns	0.0071 ns	0.0067 ns
> ListMyCount2	2.676 ns	0.0161 ns	0.0150 ns
> It can improve performance for array, but harms performance of non-array types because of the additional check.
> 
> ```cs
>         private int[] array = [1, 2, 3];
>         private List<int> list = [1, 2, 3];
> 
>         [Benchmark]
>         public int ArrayMyCount1() => MyCount1(array);
> 
>         [Benchmark]
>         public int ArrayMyCount2() => MyCount2(array);
>         
>         [Benchmark]
>         public int ListMyCount1() => MyCount1(list);
> 
>         [Benchmark]
>         public int ListMyCount2() => MyCount2(list);
> 
> 
>         public static int MyCount1<TSource>(IEnumerable<TSource> source)
>         {
>             if (source is null)
>             {
>                 ArgumentNullException.ThrowIfNull(source);
>             }
> 
>             if (source is ICollection<TSource> collectionoft)
>             {
>                 return collectionoft.Count;
>             }
> 
>             if (source is ICollection collection)
>             {
>                 return collection.Count;
>             }
> 
>             int count = 0;
>             using (IEnumerator<TSource> e = source.GetEnumerator())
>             {
>                 checked
>                 {
>                     while (e.MoveNext())
>                     {
>                         count++;
>                     }
>                 }
>             }
> 
>             return count;
>         }
> 
>         public static int MyCount2<TSource>(IEnumerable<TSource> source)
>         {
>             if (source is null)
>             {
>                 ArgumentNullException.ThrowIfNull(source);
>             }
> 
>             if (source is TSource[] array)
>             {
>                 return array.Length;
>             }
> 
>             if (source is ICollection<TSource> collectionoft)
>             {
>                 return collectionoft.Count;
>             }
> 
>             if (source is ICollection collection)
>             {
>                 return collection.Count;
>             }
> 
>             int count = 0;
>             using (IEnumerator<TSource> e = source.GetEnumerator())
>             {
>                 checked
>                 {
>                     while (e.MoveNext())
>                     {
>                         count++;
>                     }
>                 }
>             }
> 
>             return count;
>         }
> ```

Three elements for iteration, create an array with 10 million elements, see the difference.

**Comment by Mr0N** [comment]
![image](https://github.com/dotnet/runtime/assets/61237140/52ccad94-624b-44f1-9bac-2575e1d0c1bc)

**Comment by Mr0N** [comment]
![image](https://github.com/dotnet/runtime/assets/61237140/343ed009-ada5-4572-a763-645521dea05b)
Okay, it seems to be casting. But another question, how does it cast if the Count method is not in the array?

**Comment by Mr0N** [comment]
![image](https://github.com/dotnet/runtime/assets/61237140/fa08e30d-0ea2-4b9b-9db2-506483fc9ab8)
Cool, but somehow besides Count, nothing else is implemented.

**Comment by Mr0N** [comment]
![image](https://github.com/dotnet/runtime/assets/61237140/b065f348-d41d-40ee-a803-a5ef2d41ddae)
The array implements IList, which is very strange.

**Comment by huoyaoyuan** [comment]
The interface implementation of array is quite magical. It's down specially via SzArrayHelper.

But generally, **implementing an interface doesn't means a corresponding public member exists.** Interface implementation is done by explicit association, not name.

In C# you can say:

```csharp
void IMyInterface.MyMethod()
{
// private and not callable without casting to the interface
}
```

In VB:
```vb
Private Sub SuperFancyName() _
    Implements IMyInterface.MyMethod

End Sub
```

Implicit interface implementation is just C# compiler does for you.
