### ISSUE TITLE
performance: In a case, dotnet 8.0 is slower than java 22.

### ISSUE THREAD

**Issue by athinboy** [dotnet/runtime#100479]
First, sorry for my bad english!

### Description

When I  read a post that created in 2022  [https://www.zhihu.com/question/570161757](url)  and try to verify it ,I find that dotnet8.0 is very vlower than jdk22.

|                          | 10_000_000| 20_000_000 |     30_000_000    |
|--------------------------|-----------|------------|-------------------|
| jdk22                    |   2.97    |   17.09    |  OutOfMemoryError |  
| c# netcore8.0  server GC |   4.02    |   7.45     |         23.34     |
| c# netcore8.0            |   7.06    |    13.81   |        31.46      |

- without each toString()

|                          | 10_000_000| 20_000_000 |     30_000_000    |
|--------------------------|-----------|------------|-------------------|
| jdk22                    |   1.48    | 2.80       |     4.14          |  
| c# netcore8.0  server GC |   2.35    |   5.90     |         17.74     |
| c# netcore8.0            |   6.56    |    12.93   |        30.67      |

test screen shot:
[https://raw.githubusercontent.com/athinboy/file_repository/main/20240401/6.png](url)
[https://raw.githubusercontent.com/athinboy/file_repository/main/20240401/7.png](url)

code link:
https://[raw.githubusercontent.com/athinboy/file_repository/main/20240401/java/Main.java](https://raw.githubusercontent.com/athinboy/file_repository/main/20240401/java/Main.java)

[https://github.com/athinboy/file_repository/tree/main/20240401/c%23](url)

 c# code:
```
        static void Main(string[] args)
        {
            DateTime startTime, endTime;
            int count = int.Parse(args == null || args.Length == 0 ? "10000000" : args[0]);
            Console.WriteLine(count);
            startTime = DateTime.Now;

            //Span<StringBuilder> list = new Span<StringBuilder>();
            LinkedList<StringBuilder> list = new LinkedList<StringBuilder>();

            for (int i = 0; i < count; i++)
            {
                StringBuilder sb = new StringBuilder();
                sb.Append($"hellow world.{i}");
                //list.Fill(sb);
                list.AddLast(sb);
            }
            //foreach (StringBuilder sb in list)
            //{
            //    sb.ToString();
            //}
            endTime = DateTime.Now;
            Console.WriteLine((endTime - startTime).TotalMilliseconds);



            return;
        }
```

java code:
```
    public static void main(String[] args) {

        long startTime, endTime;
        Integer count = Integer.valueOf(args == null || args.length == 0 ? "10000000" : args[0]);
        System.out.println(count);
        startTime = System.currentTimeMillis();
        List<StringBuffer> list = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            StringBuffer str = new StringBuffer();
            //StringBuilder str=new StringBuilder();
            str.append("hellow world." + i);
            list.add(str);
        }
//        for (StringBuffer stringBuffer : list) {
//            stringBuffer.toString();
//        }
        endTime = System.currentTimeMillis();
        System.out.println(endTime - startTime);


    }
```

**Comment by huoyaoyuan** [comment]
You measuring code is very imprecise. Issues including:

1. `DateTime.Now` has considerable overhead. `Stopwatch` should be used instead.
Generally it should be avoided to measure time by yourself. If you are measuring performance for one platform, you should use benchmarking framework like [BenchmarkDotNet](https://benchmarkdotnet.org/). If you are comparing performance of different platforms, you should better measure the time from a same external system, for example using `Measure-Command` from PowerShell.
2. You are comparing a linear list (`ArrayList`) with linked list (`LinkedList`). They are very different data structures and use different algorithms.
3. There are difference between steady-state performance and cold-start performance. You are only measuring code start.

As the answers in https://www.zhihu.com/question/570161757 point out, your code isn't measuring anything meaningful at all.

**Comment by athinboy** [comment]
@huoyaoyuan  
Thanks for you reply. From you name ,I think you can speak Chinese.  But I hope all people  can understand this whole  issue , sorry for my bad English .
1. I change DateTime.Now to Stopwatch ,it make nothing change . It is impossible that several seconds between   Stopwatch   and DateTime.Now . 
2. I also  change LinkedList to List, similarly it make nothing change . 
3. I will try BenchmarkDotNet later .
4. As a developer ,I write the code ,run the code, the code is slower than java ,so ,should I question my measur first ? there is not millisecond class difference. It is several times gaps.
6. I do not want to  accuse the dotnet runtime team .I just want runtime team to  observer this phenomenon .
By the way , this is my answer in zhihu:[Java性能为什么比c#高很多？ - 手机党的回答 - 知乎
https://www.zhihu.com/question/570161757/answer/3447640202](url)

**Comment by huoyaoyuan** [comment]
> As a developer ,I write the code ,run the code, the code is slower than java ,so ,should I question my measur first ? there is not millisecond class difference.

1. Your code is measuring a mixture of different components, including string, list and GC. It's not a good micro benchmark that focus on one component.
2. Your code does not solve a whole problem, so it's not a good real-world benchmark.
3. Your code is not as optimal as it can. For example, in .NET we use interpolated strings directly without `StringBuilder` when not necessary.

I'm not familiar with what `StringBuffer` in Java does. The detailed capability and performance may be different with `StringBuilder` in .NET, but this doesn't mean you have to replicate its usage in .NET code for solving a whole problem. In many situations you can just create a string directly, or avoid the temporary string by passing spans around.

**Comment by athinboy** [comment]
> 1. Your code is measuring a mixture of different components, including string, list and GC. It's not a good micro benchmark that focus on one component.

OK，I will make myself more professionnal to find which  components is  slower than jdk22, GC /String/List/MemoryAlloc/MSIL. 

> 2. Your code does not solve a whole problem, so it's not a good real-world benchmark.

OK,I will rename the method in test code  to make them  more "real-world" like.

> 3. Your code is not as optimal as it can. For example, in .NET we use interpolated strings directly without `StringBuilder` when not necessary.

Please attention that :Java code in my test is  " not as optimal as it can"  too .

**Comment by huoyaoyuan** [comment]
The factors impacting this can be complex. One thing to notice that **the default capacity of StringBuilder in .NET is 16**. Your code is about to create strings with length of **14~21**. Setting a different capacity in StringBuilder constructor may result in very different result.

The different numbers under GC modes suggest it to be more related to GC. Altering `GCSettings.LatencyMode` may also change the results.

**Comment by huoyaoyuan** [comment]
Tested your code on my machine.

Result with `new StringBuilder()` (default capacity): 1979.7768ms
Result with `new StringBuilder(24)`: 1143.959ms

**Comment by huoyaoyuan** [comment]
Also posted my answer to https://www.zhihu.com/question/570161757/answer/3451262476 .
