### ISSUE TITLE
Disabling JavaScript disables .NET Timers in WebAssembly

### ISSUE THREAD

**Issue by SavoInfostream** [dotnet/runtime#100463]
Hello,
Just a random question I need help with.
Why is it that when I disable JS on the page, the `PeriodicTimers` and `Timers` in my WebAssembly app stop emitting events?
I am pretty sure my code works is not causing this.

**Comment by SingleAccretion** [comment]
Timers are implemented using the JavaScript event loop (specifically [`setTimeout`](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout)), so that's why they don't work if you disable JS.

**Comment by SavoInfostream** [comment]
@SingleAccretion How about `Task.Delay`? I want to be able to detect when the user disables JS so I wanted to have periodic checks if JS listeners are active, so I need some kind of scheduler.

**Comment by SingleAccretion** [comment]
> How about Task.Delay?

It is also implemented via the event loop.

In general, running any .NET runtime code with JS disabled is not supported, since async is not the only thing that depends on it.

**Comment by SavoInfostream** [comment]
@SingleAccretion Thank you again. I'll just record times of a JS alive signal, that emits from its own loop, so WebAssembly can then check its the time records to see if JS was blocked.
