### ISSUE TITLE
How to implement c++ VARINET Type in C#

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#100480]
How to implement c++ VARINET Type in C#?

There is a variant type in cpp called VARIENT, which acts like the Union structure in c and can hold any type of value, such as byte,str,int,long, and so on. In the built-in COM type, we can use object to represent this type and use some special classes to transform it, such as the UnKnownWrapper class, etc., but when switching to Com source generation, the object parameter does not support COM source generation marshalling. How to deal with this?
在 cpp 中有一种名为 VARIENT 的变体类型，它的作用类似于c语言中的Union结构体，里面可以存放任何类型的值，比如byte,str,int,long等等。在内置的COM类型中，我们可以使用 object 来表示这种类型，并使用一些特殊的类进行转换，比如 UnKnownWrapper 类等等，但是当切换成 Com 源生成时，object 类型的参数不支持 COM 源生成封送，这样子该如何处理呢？

VARIENT type parameters are used in IDoDownload.SetProperty
IDoDownload.SetProperty 中使用到了 VARIENT 类型的参数
https://learn.microsoft.com/zh-CN/windows/win32/api/deliveryoptimization/nf-deliveryoptimization-idodownload-setproperty

![b7b4deb6125cd62c86d3266be7ae290f](https://github.com/dotnet/runtime/assets/49179966/297db976-1db8-4a45-aa9f-eec4a93ed664)

COM interface definition
COM 接口定义

    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("FBBD7FC0-C147-4727-A38D-827EF071EE77")]
    [GeneratedComInterface()]
    public partial interface IDODownload
    {
        void Start(IntPtr ranges); // ranges is a marshaled DO_DOWNLOAD_RANGES_INFO

        void Pause();

        void Abort();

        void Finalize2(); // Note: Finalize() collides with Object.Finalize()

        void GetStatus(out DO_DOWNLOAD_STATUS status);

        void GetProperty(DODownloadProperty propId, out object propVal);

        void SetProperty(DODownloadProperty propId, ref object propVal);
    }

**Comment by huoyaoyuan** [comment]
It's `System.Runtime.InteropServices.Marshalling.ComVariant`.

**Comment by huoyaoyuan** [comment]
The proposed usage is in original issue #89543:

```csharp
[LibraryImport("Foo")]
public static partial Bar([MarshalUsing(typeof(ComVariantMarshaller))] object x);
```

**Comment by Gaoyifei1011** [comment]
> The proposed usage is in original issue #89543:
> 
> ```cs
> [LibraryImport("Foo")]
> public static partial Bar([MarshalUsing(typeof(ComVariantMarshaller))] object x);
> ```

![image](https://github.com/dotnet/runtime/assets/49179966/dadcca33-6ece-4054-8d93-f511feac7122)
However,it requires me to disable runtime marshalling

**Comment by huoyaoyuan** [comment]
The error SYSLIB1051 indicates the type isn't supported for source generation. Since `ComVariant` is new in 9.0, maybe its integration is not completed yet.

@AaronRobinsonMSFT for help on this.

**Comment by AaronRobinsonMSFT** [comment]
Thanks @huoyaoyuan 

@Gaoyifei1011 What version of .NET are you using? As @huoyaoyuan mentioned we are providing `VARIANT` marshalling support in .NET 9. I know that @jkoritzinsky was thinking about moving it back to .NET 8, but I'm not sure what the final decision was. As far as you being able to do this, it is going to require a fair bit of effort and that is why we are providing it. If I recall, the use of `object` is explicitly blocked in early versions since we weren't providing `VARIANT` marshalling support and "getting it right" isn't something we wanted to help debug.

@jkoritzinsky might have a stopgap mitigation for you, but I would recommend waiting until .NET 9 to use the provided mechanism.

**Comment by Gaoyifei1011** [comment]
> Thanks @huoyaoyuan
> 
> @Gaoyifei1011 What version of .NET are you using? As @huoyaoyuan mentioned we are providing `VARIANT` marshalling support in .NET 9. I know that @jkoritzinsky was thinking about moving it back to .NET 8, but I'm not sure what the final decision was. As far as you being able to do this, it is going to require a fair bit of effort and that is why we are providing it. If I recall, the use of `object` is explicitly blocked in early versions since we weren't providing `VARIANT` marshalling support and "getting it right" isn't something we wanted to help debug.
> 
> @jkoritzinsky might have a stopgap mitigation for you, but I would recommend waiting until .NET 9 to use the provided mechanism.

i use .net9 preview2

**Comment by Gaoyifei1011** [comment]
> Thanks @huoyaoyuan
> 
> @Gaoyifei1011 What version of .NET are you using? As @huoyaoyuan mentioned we are providing `VARIANT` marshalling support in .NET 9. I know that @jkoritzinsky was thinking about moving it back to .NET 8, but I'm not sure what the final decision was. As far as you being able to do this, it is going to require a fair bit of effort and that is why we are providing it. If I recall, the use of `object` is explicitly blocked in early versions since we weren't providing `VARIANT` marshalling support and "getting it right" isn't something we wanted to help debug.
> 
> @jkoritzinsky might have a stopgap mitigation for you, but I would recommend waiting until .NET 9 to use the provided mechanism.

i use .net9 preview2

**Comment by AaronRobinsonMSFT** [comment]
> i use .net9 preview2

Then I would use the mechanism mentioned in https://github.com/dotnet/runtime/issues/100480#issuecomment-2029512436.
