### ISSUE TITLE
.Net 4.8 HashAlgorithm.Initialize() is not called after as ICryptoTransform (i.e. in CryptoStream) thus providing incosistent experience (different hashes)

### ISSUE THREAD

**Issue by VadymLevkovskyi** [dotnet/runtime#100438]
### Description

In .Net 4.8 implementation of `SHA256` (at least this one) `.ComputeHash()` returns different result when same hash object was previously used as `ICryptoTransform` in `CryptoStream`.

### Reproduction Steps

Please run the attached code as .Net 4.8 console project. 
Check the comments and logs, they should be self-explanatory enough ;-)

```
using System;
using System.IO;
using System.Security.Cryptography;

namespace ComputeHashIssue
{
    class Program
    {
        static void Main()
        {
            var data = new byte[1] { 42 };

            using (var sha = SHA256.Create())
            {
                // first calculation
                var initialHash = "";
                using (var dataStream = new MemoryStream(data))
                    initialHash = BitConverter.ToString(sha.ComputeHash(dataStream));
                Console.WriteLine($"Initial hash:               {initialHash}");

                // break inner state of hash object using it inside CryptoStream as ICryptoTransform
                using (var dataStream = new MemoryStream(data))
                using (var tempStream = new MemoryStream())
                using (var cryptoStream = new CryptoStream(dataStream, sha, CryptoStreamMode.Read))
                    cryptoStream.CopyTo(tempStream); 

                // calculation after no Initialize()
                var cryptoStreamHash = "";
                using (var dataStream = new MemoryStream(data))
                    cryptoStreamHash = BitConverter.ToString(sha.ComputeHash(dataStream));
                Console.WriteLine($"After usage in CryptoStream: {cryptoStreamHash}");

                // next calculation
                var otherHash = "";
                using (var dataStream = new MemoryStream(data))
                    otherHash = BitConverter.ToString(sha.ComputeHash(dataStream));
                Console.WriteLine($"Other hash:                  {otherHash}");

                if (initialHash != otherHash)
                    Console.WriteLine($"Initial and other hash are different, should never occured");

                if (initialHash != cryptoStreamHash)
                    Console.WriteLine($"Initial and `after CryptoStream` hash are different, occurs always");
            }
        }
    }
}
```

### Expected behavior

All 3 hash values from suggested code should be the same.
In other words, usage of `HashAlgorithm` as `ICryptoTransform` shouldn't left hash object in 'spoiled' state.

### Actual behavior

Hash value calculated immediately after usage of hash object in `CryptoStream` differs from other hash values.

### Regression?

Has't investigated. Definitely fixed in .Net 8.

### Known Workarounds

Use `hash.Initialize()` after usage of `CryptoStream`

### Configuration

.Net 4.8

### Other information

Please pay attention to [.Net 4.8 HashAlgorithm.TransformFinalBlock](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/security/cryptography/hashalgorithm.cs#L156) implementation. I presume it has to have call to `Initialize()` closer to the end of the method body.

Compare to [.Net 8 HashAlgorithm.TransformFinalBlock](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HashAlgorithm.cs#L211) that has implicit call to `Initialize()` via `CaptureHashCodeAndReinitialize()`.

**Comment by bartonjs** [comment]
At a quick glance, none of the hash algorithm types in .NET Framework reset on TransformFinalBlock, which means it looks like it was actually a bug when I made .NET Core do that years and years ago.  (Or, maybe, an ease of use feature enhancement?)

.NET Framework 4.x is no longer under active development, and changing a behavior like this would exceed the breaking change tolerance of that product.

Instead of the ICryptoTransform role of HashAlgorithm, I recommend using `IncrementalHash`.  That type was created to better separate the poor interaction of the ICryptoTransform methods and ComputeHash methods.
