### ISSUE TITLE
[API Proposal]: ExecuteOnlySpan<T>

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#100485]
### Background and motivation

We already have `Span<T>` and `ReadOnlySpan<T>`. Issue #100302 suggested adding `WriteOnlySpan<T>`. Naturally, the only missing type after that to complete the memory protection triad is `ExecuteOnlySpan<T>`. After all, it may be useful addition to support scenarios like ARMeilleure emulator in Ryujinx which currently relies on custom memory mapping.

### API Proposal

```csharp
namespace Unsafe.AprilFools;

public readonly ref struct ExecuteOnlySpan<T> 
{
        // API surface from Span<T> that is applicable
        [System.CLSCompliantAttribute(false)]
        public unsafe ExecuteOnlySpan(void* pointer, int length);
        public ExecuteOnlySpan(ref readonly T reference);
        public ExecuteOnlySpan(T[]? array);
        public ExecuteOnlySpan(T[]? array, int start, int length);
        public static System.ExecuteOnlySpan<T> Empty { get; }
        public bool IsEmpty { get; }
        public int Length { get; }
        public static System.ExecuteOnlySpan<T> CastUp<TDerived>(System.ExecuteOnlySpan<TDerived> items) where TDerived : class?, T;
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public ref readonly T GetPinnableReference();
        public static bool operator ==(System.ExecuteOnlySpan<T> left, System.ExecuteOnlySpan<T> right);
        public static implicit operator System.ExecuteOnlySpan<T> (System.ArraySegment<T> segment);
        public static implicit operator System.ExecuteOnlySpan<T> (T[]? array);
        public static bool operator !=(System.ExecuteOnlySpan<T> left, System.ExecuteOnlySpan<T> right);
        public System.ExecuteOnlySpan<T> Slice(int start);
        public System.ExecuteOnlySpan<T> Slice(int start, int length);

        // Execute and return the value of natural int from register according to the current platform ABI
        public nint Execute();
}
```

### API Usage

```csharp
byte[] code = [0xf3, 0x0f, 0x1e, 0xfa];
ExecuteOnlySpan<byte> executableCode = new(code);
int result = executableCode.Execute();
```

### Alternative Designs

Expose `Unsafe.Calli` and let people handle the argument and buffers themselves.

### Risks

This is a fairly advanced API. I initially wrote a very conservative API surface for it but we may eventually want to add more APIs to facilitate the remapping and for a better support of the W^X execution model.

**Comment by stephentoub** [comment]
My least favorite day of the year.

**Comment by lambdageek** [comment]
I'm not sure about `Execute`.  I think it would be better to have an unsafe cast to some user-specified function pointer type.

```
   delegate*<TResult> GetUnsafeFPtr<TResult>();
   delegate*<T1, TResult> GetUnsafeFPtr<T1, TResult>();
   delegate*<T1, T2, TResult> GetUnsafeFPtr<T1, T2, TResult>();
   ...

   delegate *unmanaged<TResult> GetUnsafeUnmanagedFPtr<TResult>();
   delegate *unmanaged<T1,TResult> GetUnsafeUnmanagedFPtr<T1, TResult>();
   delegate *unmanaged<T1,T2,TResult> GetUnsafeUnmanagedFPtr<T1, T2, TResult>();
   ...
```

probably we will want the full pantheon of Win-x86 calling conventions there.  So 7 or 8 overloads of `GetUnsafeUnmanagedStdcallFPtr`, and `GetUnsafeUnmanagedFastcallFPtr`, and so on.  And of course we can mix and match calling conventions.  For maximum PERFORMANCE we will want `GetUnsafeUnmanagedSuppressGCTransitionFastcallFPtr` overloads.  And so on...

**Comment by filipnavara** [comment]
> I think it would be better to have an unsafe cast to some user-specified function pointer type.

Love that suggestion, but can we somehow make it more generic? I'm thinking `T GetUnsafeFPtr<T>() where T : delegate`. If we are lacking some C# feature to make that happen we probably should open some proposal for Roslyn as well.

**Comment by filipnavara** [comment]
> My least favorite day of the year.

I also hate Mondays.

**Comment by tannergooding** [comment]
I went back and forth on whether or not to write up a "proper" response here, but given it's "Monday", let's just leave this as "closed, no planned" for many of the same reasons given in the `WriteOnlySpan<T>` proposal ;)

A user wanting to do this should likely abstract it themselves by internally having a writeable `Span<T>` and externally exposing a `ReadOnlySpan<T>`. They would ensure that the execute bit is off when the span is writeable and on when mutations are complete. They would also need to ensure they call the relevant CPU instruction cache flushing API for the operating system in question.
