### ISSUE TITLE
Question: how to pass string pointer without Marshal to NativeAOT dylib ?

### ISSUE THREAD

**Issue by LLT21** [dotnet/runtime#100481]
Given the following 2 functions in a C# NativeAOT dylib (on Mac M1): 

```
    [UnmanagedCallersOnly(EntryPoint = "PrintString1")]
    public static void PrintString1(IntPtr pointer)
    {
        string stringToPrint1 = Marshal.PtrToStringAnsi(pointer) ?? string.Empty; 
        Console.WriteLine($"Marshal: {stringToPrint1}");
    }

    [UnmanagedCallersOnly(EntryPoint = "PrintString2")]
    public static void PrintString2(IntPtr pointer)
    {
        GCHandle gCHandle = GCHandle.FromIntPtr(pointer); 
        string stringToPrint2 = gCHandle.Target as string; 
        Console.WriteLine($"Target: {stringToPrint2}");
    }

```
When calling both functions in a console app as follows: 

```
    [DllImport("lib2.dylib", CallingConvention = CallingConvention.Cdecl)]
    public static extern void PrintString1(string pointer);

    [DllImport("lib2.dylib", CallingConvention = CallingConvention.Cdecl)]
    public static extern void PrintString2(IntPtr pointer);

    static void Main(string[] args)
    {
        string stringToPrint = "Hello";
        GCHandle gCHandle = GCHandle.Alloc(stringToPrint);
        nint intPtr = GCHandle.ToIntPtr(gCHandle); 
        PrintString1(stringToPrint);
        PrintString2(intPtr);
        gCHandle.Free(); 
    }

```

The PrintString1 writes "Hello" correctly, PrintString2 returns nothing: 

```
Marshal: Hello
Target: 

```

Probably I am missing something in my code, would rather prefer the PrintString2 function as it is clearer. Can you indicate what I am missing ?

**Comment by SingleAccretion** [comment]
When you receive the GCHandle in `PrintString2`, it contains an object from a separate runtime (in fact, the GC handle itself is "foreign"). Managed objects cannot be passed between two separate .NET runtimes - they can only communicate using C-level interfaces.

**Comment by LLT21** [comment]
This was my idea as well. But how can the first function work then ?

**Comment by SingleAccretion** [comment]
`PrintString1` passes the string via a copy to and them from unmanaged memory. So it doesn't have this problem.

**Comment by huoyaoyuan** [comment]
Note that there's a third way: exposing a `char*` instead of `string`. The `char*` points to managed memory in caller, the callee can use it as a read only source, or create a copy in its own managed memory:
```csharp
    [UnmanagedCallersOnly(EntryPoint = "PrintString3")]
    public static void PrintString3(char* pointer)
    {
        string stringToPrint3 = new string(pointer);
        Console.WriteLine($"Pointer: {stringToPrint3}");
    }
```

```csharp
    [DllImport("lib2.dylib", CallingConvention = CallingConvention.Cdecl)]
    public static extern void PrintString3(string pointer);
```

**Comment by LLT21** [comment]
Nice solution. Added unsafe and CharSet.Unicode to make it work, but seems to do the job:

```
    [UnmanagedCallersOnly(EntryPoint = "PrintString3")]
    public static unsafe void PrintString3(char* pointer)
    {
        string stringToPrint3 = new string(pointer);
        Console.WriteLine($"Pointer: {stringToPrint3}");
    }

```

Caller: 

```
    [DllImport("lib2.dylib", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Unicode)]
    public static extern void PrintString3(string pointer);

    static void Main(string[] args)
    {
        string stringToPrint = "Hello";
        PrintString1(stringToPrint);
        PrintString3(stringToPrint);
    }

```

**Comment by LLT21** [comment]
Any guidance how I can also return a string in this 3rd way ?

**Comment by huoyaoyuan** [comment]
Returning is more complex than input, because the lifetime of return buffer must be properly defined.
In this case, you have to act like C: the caller need to allocate a buffer using `char[]` or `stackalloc char`, and pass it to callee together with buffer length.

**Comment by LLT21** [comment]
Tried this one:

1) Caller side: 

```
    [DllImport("lib2.dylib", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Unicode)]
    public static extern unsafe char* ReverseString(string pointer);

    static unsafe void Main(string[] args)
    {
        string stringToPrint = "Hello";
        PrintString1(stringToPrint);
        PrintString3(stringToPrint);

        var charPointer = ReverseString(stringToPrint);
        string stringReversed = new string(charPointer);
        Console.WriteLine($"Reversed: {stringReversed}");
    }
}

```
2) Callee side: 

```
    [UnmanagedCallersOnly(EntryPoint = "ReverseString")]
    public static unsafe char* ReverseString(char* pointer)
    {
        string stringToPrint = new string(pointer);
        Console.WriteLine($"Pointer: {stringToPrint}");

        char[] charArray = stringToPrint.ToCharArray();
        Array.Reverse(charArray);
        string stringReversed = new string(charArray);

        fixed(char* s = stringReversed)
        {
            Console.WriteLine($"return {stringReversed}");
            return s; 
        }
    }

```

Just wondering whether I should still free something in this case ?

**Comment by huoyaoyuan** [comment]
> Called the GC explicitly in the callee, but just keeps working.

GC hole isn't guaranteed to invalidate things.

Pointers to managed memory is only valid when the managed object is pinned. When passing string from caller to callee, the P/Invoke method frame pins the string for you.

**Comment by LLT21** [comment]
But do I understand it correctly that the same does not happen for the returned object/string from callee to caller (not as a parameter but as a returned value) ? Code seems to work in my tests, just try to find out why.

**Comment by huoyaoyuan** [comment]
The `fixed` statement is out of scope after return. Never pass the fixed pointer to anywhere out of the `fixed` statement.

> Code seems to work in my tests

Quoting the description of GC hole in [botr](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/clr-code-guide.md#212-your-first-gc-hole): *This code compiles fine, and if you run simple pre-checkin tests, it will probably "work." But this code will crash eventually.*

The pointer will keep "working" until the memory is recycled by GC and cleared. But After the method returns, there's no way to prevent this from eventually happening.

**Comment by agocke** [comment]
Closing as answered. Interop in all these cases requires acting like C. Some part of each application must be responsible for allocating and freeing memory in each part of the boundary.
