### ISSUE TITLE
Warning origins for warnings originating from event accessors are very confusing

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#100499]
Currently `MarkEvent` will directly call `MarkMethod(add_event)` and `MarkMethod(remove_Event)` with the origin set to the event itself. So for example:

```C#
// IL2026 - about the add_event
public event EventHandler TestEvent {
    [RequiresUnreferencedCode()]
    add {}
}
```

The warning is reported on the event itself and not on the callsite actually accessing the event. It's also reported repeatedly (if there are multiple callsites).

This gets potentially even worse because `ProcessEvent(add_event)` will call `MarkEvent(event)` and so that will potentially trigger the warning multiple times on its own.

RUC on type makes this even worse since both accessors are automatically RUC and this loops on itself (I think I saw the warning triplicated and on the wrong place).

**Comment by tommcdon** [comment]
@sbomer This issue was incorrectly assigned to area-tracing, could you help us find the right area path for this issue?
