### ISSUE TITLE
System.AppContext.BaseDirectory returns path to directory content instead of path to directory

### ISSUE THREAD

**Issue by Lavshyak** [dotnet/runtime#100448]
### Description

System.AppContext.BaseDirectory is named "BaseDirectory", but not "BaseDirectoryContentPath". However, it returns the path to the contents of the directory, and not to the directory itself.

In most operating systems, "/dir" and "/dir/" represent different things.
"/dir" typically refers to a directory named "dir" located at the root of the file system.
On the other hand, "/dir/" typically refers to the contents within the directory "dir" located at the root of the file system.

So, this property should return a path without last '/' character.

### Reproduction Steps

System.AppContext.BaseDirectory

### Expected behavior

var b = (System.AppContext.BaseDirectory.Last() is '/' or '\\');
// b == false

### Actual behavior

var b = (System.AppContext.BaseDirectory.Last() is '/' or '\\');
// b == true

### Configuration

.net 8, in docker container based on mcr.microsoft.com/dotnet/aspnet:8.0 and mcr.microsoft.com/dotnet/sdk:8.0.

**Comment by jkotas** [comment]
AppContext.BaseDirectory (and AppDomain.BaseDirectory) used to return a path without the trailing slash in the early versions of .NET Core. The slash was later added back to improve compatibility with the .NET Framework: https://github.com/dotnet/runtime/issues/7866 . There is a lot of code out there that depends on the trailing slash in paths returned by these properties. Your proposal is a breaking change that would be hard to justify.
