### ISSUE TITLE
The type initializer sometimes doesn't execute for an empty struct

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#100466]
### Description

The type initializer sometimes doesn't execute for an empty struct, and the behavior is not consistent across different platforms + configurations. 

### Reproduction Steps

Repro:

```cs
var foo = new Foo<Bar>();
Console.WriteLine(foo.ToString());
Console.WriteLine(Bar.X);

struct Foo<T> where T : IBar
{
    static Foo()
    {
        T.Set();
    }
}

struct Bar : IBar
{
    public static int X;
    public static void Set()
    {
        X = 42;
    }
}

interface IBar
{
    abstract static void Set();
}
```

Note that the line `foo.ToString()` does an invocation to the virtual method. So according to ECMA:

```
If not marked BeforeFieldInit then that type’s initializer method is executed at
...
- first invocation of any instance or virtual method of that type if it is a value type
```

BTW the abstract static method and generic here is not necessary for the repro, the below code also reproduces this issue:

```cs
var foo = new Foo();
Console.WriteLine(foo.ToString());
Console.WriteLine(Bar.X);

struct Foo
{
    static Foo()
    {
        Bar.Set();
    }
}

struct Bar
{
    public static int X;
    public static void Set()
    {
        X = 42;
    }
}
```

### Expected behavior

Always prints
```
Foo`1[Bar]
42
```

### Actual behavior

The output from `Bar.X`:

| Platform | Configuration | TieredCompilation | Output |
| -- | -- | -- | -- |
| win-x64 | Debug | N/A | `0` |
| win-x64 | Release | true | `0` |
| win-x64 | Release | false | `0` |
| linux-x64 | Debug | N/A | `42` |
| linux-x64 | Release | true | `42` |
| linux-x64 | Release | false | `0` |
| linux-arm64 | Debug | N/A | `42` |
| linux-arm64 | Release | true | `42` |
| linux-arm64 | Release | false | `0` |
| osx-arm64 | Debug | N/A | `42` |
| osx-arm64 | Release | true | `42` |
| osx-arm64 | Release | false | `0` |

**Comment by am11** [comment]
Seems like this is only reproducible with PublishAot.

**Comment by huoyaoyuan** [comment]
> first invocation of any instance or virtual method of that type if it is a value type

Is it applicable to boxed `ToString`? The method is provided by base type `ValueType`.

**Comment by hez2010** [comment]
> Seems like this is only reproducible with PublishAot.

It does reproduce without PublishAot.

**Comment by am11** [comment]
> It does reproduce without PublishAot.

I tested with .NET 8 and .NET 9 daily build, can't reproduce without PublishAot=true.

**Comment by hez2010** [comment]
Tested on .NET 8:

```
> dotnet --version
8.0.202
> dotnet run -c Release
Foo`1[Bar]
0
```

**Comment by am11** [comment]
Which platform is it? This is linux-x64 with 8.0.202 and 9.0.100-preview.4.24180.1 https://github.com/am11/CrossRepoCITesting/actions/runs/8498315034/job/23277887637

```sh
$ dotnet run
Foo`1[Bar]
42

$ dotnet publish -p:PublishAot=true -c Release -o out
$ out/gh-100466
Foo`1[Bar]
0
```
Same results on linux-arm64 and osx-arm64.

**Comment by hez2010** [comment]
> Which platform is it? This is linux-x64 with 8.0.202 and 9.0.100-preview.4.24180.1 [am11/CrossRepoCITesting/actions/runs/8498315034/job/23277887637](https://github.com/am11/CrossRepoCITesting/actions/runs/8498315034/job/23277887637)
> 
> ```shell
> $ dotnet run
> Foo`1[Bar]
> 42
> 
> $ dotnet publish -p:PublishAot=true -c Release -o out
> $ out/gh-100466
> Foo`1[Bar]
> 0
> ```
> 
> Same results on linux-arm64 and osx-arm64.

I'm on Windows 11 x64.

**Comment by am11** [comment]
Yes, on win-x64 it returns 0 with JIT as well.

**Comment by hez2010** [comment]
> Yes, on win-x64 it returns 0 with JIT as well.

I updated the issue to reflect output from different configurations and platforms.

**Comment by jkotas** [comment]
This case is covered by `Thus for value types, the .cctor is only guaranteed to be called for instances of the value type that are not “all-zero”.` from the ECMA-335 spec.

For determinism, we always trigger the type initializers as late as possible. Thus, the expected behavior in this case is `0`.
