### ISSUE TITLE
Empty array allocated on the Frozen Heap for a Collectible type?

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#100437]
Hello folks,

Apologies, it's not a fully reproducible bug as we haven't tried yet to reproduce it with a simpler sample, but we have a suspicion.

We are investigating an error where we have the GC marking of frozen objects `gc_heap::mark_ro_segments()`that is crashing. 

One place that we are curious about is in `TryAllocateFrozenSzArray`:

https://github.com/dotnet/runtime/blob/7486be885b298aef622833bec509732e6b3f1667/src/coreclr/vm/gchelpers.cpp#L516-L520

Where it seems that we could allow to allocate an empty array for collectible MethodTable in the Frozen heap. Shouldn't it be something like this instead?

```cpp
    if (pArrayMT->Collectible() || (pArrayMT->ContainsPointers() && cElements > 0))
    {
        // For arrays with GC pointers we can only work with empty arrays
        return NULL;
    }
```

Before we investigate this further, any thoughts?

cc: @EgorBo

**Comment by jkotas** [comment]
> Before we investigate this further, any thoughts?

Yes, this looks like a bug. Could you please submit a PR with the fix?

**Comment by xoofx** [comment]
> Yes, this looks like a bug. Could you please submit a PR with the fix?

Sure!

**Comment by jkotas** [comment]
There is `CORJIT_FLAG_FROZEN_ALLOC_ALLOWED` that handles most cases, but it does not cover shared generics. The shared generic code may have `CORJIT_FLAG_FROZEN_ALLOC_ALLOWED` set, but the actual instantiation can be collectible. I think you should be able to reproduce the crash using a pattern like this.
