### ISSUE TITLE
Dotnet native compiled js file referencing wrong function in blazor web assembly file

### ISSUE THREAD

**Issue by Victorolu** [dotnet/runtime#100591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My team have been reliant on the blazor-error-ui banner for when we have errors we need to check and after upgrading our project from dotnet 7 to dotnet 8 and updating our packages, we have noticed the banner doesn't show up as often as we want it to.

Delving deeper and running the project, I noticed that within the compiled dotnet native file, **dotnet.native.8.0.3.9nm7bajy7e.js**, there were references to functions within the compiled blazor web assembly, **blazor.webassembly.js**. The references is 
```
var out = **Module["print"]** || console.log.bind(console);
var err = **Module["printErr"]** || console.warn.bind(console);
```
However, checking the blazor wasm file, I couldn't find those functions. Checking through the same on the dotnet 7 version of our project, I found those functions which the names **print** and **printErr**.

After some cross checking, I found out that the names of those functions on dotnet 8 had change to **out** and **err**.

**FYI**
These are the package references we have for WebAssembly in our project on dotnet 8:
```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.3" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.3" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.3" PrivateAssets="all" /
```

### Expected Behavior

The error and out functions should point to the correct functions

### Steps To Reproduce

Run any Blazor Client project on dotnet 8 with the aim of generating an unhandled error. It shouldn't show up if the error banner is enabled.

### .NET Version

dotnet 8

**Comment by javiercn** [comment]
@maraf @pavelsavara do you know what's going on here?

Seems that these functions aren't available in the net8.0 version of the dotnet.js file? Feel free to send it back if that's not the case. I don't recall us changing anything in this area.

**Comment by pavelsavara** [comment]
@javiercn I don't mind leaving it here for now, but this is Blazor's error notification bar we are talking about. 
Runtime's `Module.err` is just way how they touch internals 😉 

Should there be public API for the same ? Perhaps on `globalThis.Blazor` object ? Do we still consider multiple independent instances of wasm runtime in same page ?

**Comment by Victorolu** [comment]
Hi @pavelsavara thanks for your response. The files you referenced are correct, however, it looks different in the complied js file on my browser.

These are the function names on blazor.webassembly.js which are `out `and `err`
![image](https://github.com/dotnet/runtime/assets/42678223/b400bc71-e402-437b-9fc4-465714cac0bd)

But what is being referenced is different, `print `and `printErr`
![image](https://github.com/dotnet/runtime/assets/42678223/ae05bdbd-1e57-44ef-93f0-c22e8e3b6140)

This causes the code to only perform a console log because it can't find `print `and `printErr`

**Comment by BrownishMonster** [comment]
Hi all,

@Victorolu and I were comparing our release before and after the dotnet 8 upgrade, and the JS files in the framework were different.

dotnet 7:
![image](https://github.com/dotnet/runtime/assets/56352230/f2013cdc-1b48-4256-a269-76bc8f583754)

dotnet 8:
![image](https://github.com/dotnet/runtime/assets/56352230/d80b4fcb-cbd9-463f-a230-86391e7f163b)

A new dotnet 8 blazor project would contain `blazor.web.js` whereas our project contains `blazor.webassembly.js`. This is because we have not migrated to a Blazor Web App.

**Comment by pavelsavara** [comment]
Oh, this is interesting. You are saying that we don't configure the right thing anymore!

I think this is the change which we missed
https://github.com/emscripten-core/emscripten/pull/17955/

**Comment by BrownishMonster** [comment]
@pavelsavara 

Thank you for your quick response and assistance. Do we know when this fix might be released?

**Comment by pavelsavara** [comment]
@BrownishMonster @Victorolu 
The fix landed for Net9 yesterday and it would be in nightly release probably tomorrow or day after.

Could you please upgrade your solution to Net9 and test it with (redirect changes daily)
https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.zip

It would increase our confidence that we are patching the Net8 with the right fix.

**Comment by Victorolu** [comment]
@pavelsavara 
I have just tried to run a test project on dotnet 9 and it is giving build errors as shown:
![image](https://github.com/dotnet/runtime/assets/42678223/9c8cc3d5-b19a-4080-9b16-ab58b3628b7c)

**Comment by maraf** [comment]
@Victorolu Please, try to run the app from command line with `dotnet run` (in project directory). Getting nightly SDK into VS is more complicated

**Comment by maraf** [comment]
@Victorolu I'm sorry, I always forgot to mention it. Add to your csproj
```xml
<PropertyGroup>
 
 
 
 <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json</RestoreAdditionalProjectSources>
</PropertyGroup>
```

**Comment by Victorolu** [comment]
@maraf thanks for that. I was able to get the project to run after encountering some other issues like the missing project runtime config file that was not generated so I had to create mine and specify the framework to be used. Don't know if that is something that needs to be fixed as well.

But yeah, was able to run the project and got the error message. This, however, has led to another problem.
Looks like Blazor has crashed and is related to mono being disabled

![image](https://github.com/dotnet/runtime/assets/42678223/d754963b-f031-4ed0-a8a6-43beb2e59aed)


This was not the behaviour on dotnet 7 as the application was still running as normal after the error occurred

**Comment by maraf** [comment]
This looks weird. Blazor should be handling mono runtime start and shutdown correctly.
How you start blazor? Are you using just the standard `<script src="blazor.web.js"></script>` or do you customize things?
One things that comes to my mind is about browser cache, can you please try open the app in an incognito mode, other browser, or use different server port?

**Comment by Victorolu** [comment]
@maraf The file being called to start off blazor is referenced as `<script src="_framework/blazor.webassembly.js"></script>`
as there was no part of the documentation for upgrading from dotnet 7 to 8 that required it being changed.

@pavelsavara Why wasn't this the case with dotnet 7 then?

**Comment by pavelsavara** [comment]
> @pavelsavara Why wasn't this the case with dotnet 7 then?

We evolve :)
Why would it be good idea to let the corrupted program to keep running ?

**Comment by Victorolu** [comment]
@pavelsavara 
Well, that makes sense but not all errors corrupt programs though. In our case, we would still want to see the errors but we don't want the program to become unresponsive if that makes sense.

Question, does that mean all unhandled errors are classed as critical errors?

**Comment by maraf** [comment]
Yeah, when the runtime aborts, it means that something really bad happened. 
Does the app crash in incognito mode (no cache involved)?

**Comment by Victorolu** [comment]
Hi @maraf, yes the app crashes in incognito as well

**Comment by pavelsavara** [comment]
> @pavelsavara Well, that makes sense but not all errors corrupt programs though. 

Some assert happened in your native code (or in Mono code) and called `abort()`. 
There is no class of "harmless" asserts or aborts.
If you want to recover from such problem, I suggest that you reload the whole page.

**Comment by pavelsavara** [comment]
Fixed by https://github.com/dotnet/runtime/pull/100818 for next Net8 servicing release
