### ISSUE TITLE
[ARM32] Non-Windows UPDATE_GC_SHADOW is unimplemented

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#10058]
In src\vm\arm\asmhelpers.asm:
```
.macro UPDATE_GC_SHADOW name, ptrReg, valReg
    // Todo: implement, debugging helper
.endm
```

**Comment by mangod9** [comment]
what is the impact of this? Does this imply diagnostics is impacted on arm32?

**Comment by BruceForstall** [comment]
Looks like that comment is gone and UPDATE_GC_SHADOW has been implemented, so closing
