### ISSUE TITLE
Is it possible to implement a self-referential static abstract interface method in Reflection.Emit?

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#100537]
### Description

We've all seen self-referential interfaces.  `IComparable<T>`, where `T` is the type implementing `IComparable<T>` is a well-known example.  And since the rise of `static abstract` interface methods, using one as a factory appears to be the only way to instantiate a type with a non-parameterless constructor in a generic context, like so:

```
interface IConstructable<T>
{
   static abstract T Create(int value); //implementation simply calls the constructor
}
```

Unfortunately, this technique does not appear to be usable from `Reflection.Emit`.  To implement a normal interface method, it's sufficient to mark it `Public` and `Virtual` and match the signature, but on a `static abstract` method, you can't mark the method both `Static` and `Virtual` (an exception is raised if you try,) and if you mark it simply `Public` and `Static`, an exception is raised when you call `myTypeBuilder.CreateType()`:

> **System.TypeLoadException**: 'Virtual static method 'Create' is not implemented on type 'MyType' from assembly 'MyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.'

It appears that a call to [`DefineMethodOverride`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder.definemethodoverride?view=net-8.0) is needed to wire things up, but this also fails for a different reason: instantiating a generic type with a `TypeBuilder` as a type parameter yields a `TypeBuilderInstantiation`, which is useless in this scenario because [so many of its methods, including `GetMethod`, throw `NotSupportedException`](https://github.com/dotnet/runtime/blob/f37a5c18bd18440c3e81e59c28b05163874bc1ea/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilderInstantiation.cs#L171).

### Reproduction Steps

```
using System.Reflection;
using System.Reflection.Emit;

namespace Repro
{
	public interface IConstructable<T>
	{
		static abstract T Create(int value);
	}

	internal class Program
	{
		static void Main()
		{
			AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new("MyAssembly"), AssemblyBuilderAccess.RunAndCollect);
			ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule("MyAssembly");			
			var typeBuilder = moduleBuilder.DefineType("MyType");
			var intfType = typeof(IConstructable<>).MakeGenericType(typeBuilder);
			typeBuilder.AddInterfaceImplementation(intfType);
			var ctor = typeBuilder.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, [typeof(int)]);
			var il = ctor.GetILGenerator();
			il.Emit(OpCodes.Ret);

			var impl = typeBuilder.DefineMethod("Create", MethodAttributes.Public | MethodAttributes.Static, typeBuilder, [typeof(int)]);
			il = impl.GetILGenerator();
			il.Emit(OpCodes.Ldarg_0);
			il.Emit(OpCodes.Call, ctor);
			il.Emit(OpCodes.Ret);

			// error occurs here.  If you comment it out the next two lines, different error on CreateType
			var intfMethod = intfType.GetMethod("Create")!;
			typeBuilder.DefineMethodOverride(impl, intfMethod);
			var result = typeBuilder.CreateType();

			Console.WriteLine(result.FullName);
		}
	}
}
```

### Expected behavior

The code above should print the name of the type.

### Actual behavior

The code throws an exception, as described above.

### Known Workarounds

I can use reflection to get a handle to the constructor and `Invoke` it, but I'd prefer not to have to do that if possible.  This is coming from a solution being set up for performance-critical inner-loop code, where reflection would noticeably bog things down.

### Other information

To avoid any XY Problem issues, *the thing that I am trying to do* is instantiate a type, from generic code, that has a constructor with more than 0 parameters, that is defined at runtime using `Reflection.Emit`.  If there is a better way to accomplish that than what I am trying to do here, I'd be happy to hear about it.

**Comment by masonwheeler** [comment]
This whole `TypeBuilderInstantiation` thing keeps getting messier.  If I have something typed as `IEnumerable<MyType>`, I can't emit a call to `GetEnumerator<T>()` because of the same problem noted above.

I *can't be* the first person this has happened to.  Surely there's some way to do this that I'm just missing?

**Comment by buyaa-n** [comment]
> // error occurs here.  If you comment it out the next two lines, different error on CreateType
> 			var intfMethod = intfType.GetMethod("Create")!;

You cannot get a constructed generic method that uses `TypeBuilder` as type parameter, should use the static methods on TypeBuilder:
`var intfMethod = TypeBuilder.GetMethod(intfType, typeof(IConstructable<>).GetMethod("Create")!);`

After this change the code works for runtime `AssemblyBuilder`.

But this scenario fails with new `PersistedAssemblyBuilder` implementation, I'll keep issue open for fixing that failure, thanks for reporting the issue

**Comment by masonwheeler** [comment]
Yeah, I eventually found `TypeBuilder.GetMethod` and related methods with some research.  Any particular reason why the methods on `TypeBuilderInstantiation` can't be implemented as calls to the corresponding `TypeBuilder` methods?

**Comment by buyaa-n** [comment]
Well, I wasn't there when this design decision made, could not give exact/correct answer. In my opinion, even the `TypeBuidler` doesn't implement all overrides, it must be quite complex and/or repeating the runtime type implementation if it was possible to override all, you know there is many methos doesn't work until `TypeBuidler` is baked, and after its baked you cannot modify the `TypeBuidler`. So we need these temporary incomplete `Type` implementations until finishing building the type, but we don't need to have all overrides implemented for each. `TypeBuilderInstantiation` is just a wrapper around `TypeBuilder` and `MethodBuilder` that represents constructed generic type, maybe we could somehow implement `GetMethod` on it, but what about other methods, that is not only method that might needs an implementation, if we implement all then I would imagine it would like reimplementing the runtime type.

**Comment by masonwheeler** [comment]
`TypeBuilder` [defines the static methods](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilder.cs#L327) `GetMethod`, `GetConstructor`, and `GetField`.  The corresponding `TypeBuilderInstantiation` methods could be implemented as pass-through calls to these three, and the plural versions of these three would be trivial to implement.  The remaining Gets (for properties, interfaces, events, and nested types) aren't implemented yet, but being able to use these would be a good start.

> you know there is many methos doesn't work until TypeBuidler is baked, and after its baked you cannot modify the TypeBuidler.

Sure, but if I'm working with `TypeBuilder` and trying to call the Gets on constructed types in the first place, I don't need "methods that work"; I need valid metadata tokens to pass to `ILGenerator.Emit`.  And given that `TypeBuilder.GetMethod` throws if what you give it is not a type constructed off a `TypeBuilder`, and sometimes knowing which types are like that and which are not is not a trivial task, it would be really nice to just be able to use `GetMethod` calls in all cases.

**Comment by buyaa-n** [comment]
> TypeBuilder [defines the static methods](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilder.cs#L327) GetMethod, GetConstructor, and GetField. The corresponding TypeBuilderInstantiation methods could be implemented as pass-through calls to these three

That might doable, but that would need find the method/ctor/field with given from the internal type definition, I don't see much value having this method implemented, maybe will be less confusing for the user, in that case I am OK with adding implementation. Tag @jkotas @steveharter for more opinions.

> Sure, but if I'm working with TypeBuilder and trying to call the Gets on constructed types in the first place, I don't need "methods that work"; I need valid metadata tokens to pass to ILGenerator.Emit

I don't think you could use metadata tokens for both cases, `MetadataToken` property is not implemented in `MethodOnTypeBuilderInstantiation`, `ConstructorOnTypeBuilderInstantiation`, `FieldOnTypeBuilderInstantiation`

**Comment by buyaa-n** [comment]
> (It would be really nice to get access to properties BTW; with no TypeBuilder.GetProperty available, I don't see how to get access to IEnumerator<T>.Current where T is a TypeBuilder.)

I think you could use the getter/setter methods with `TypeBuilder.GetMethod()`
