### ISSUE TITLE
Request for analyser ICU usage and/or TZ data

### ISSUE THREAD

**Issue by svrooij** [dotnet/runtime#100531]
When trying to use the Chiseled docker images, we experienced issues with ICU not being available. Would it be possible to have an analyzer that would catch all usages of ICU and TZdata? That way we would be able to catch these issues way earlier.

**Comment by svrooij** [comment]
I was deploying my app that used `Microsoft.Data.Sql` only to get a message at runtime that it would not run because I used the `Chiseled` docker image. If there was a possibility to tell the project "hey I will be building this as chiseled image" (or maybe by checking the [ContainerBaseImage](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#containerbaseimage))

And then tell me at build time:

1. Error, your code depends upon ICU to be available.
2. Warning, you might be using code here that depends upon ICU and or tzdata, if you're doing anything with timezone info and or string casing

**Comment by tarekgh** [comment]
Currently, if ICU is not installed and [globalization invariant mode](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#invariant-mode) is not enabled, your app will encounter a runtime error when launched. You can detect this issue by checking if globalization invariant mode is enabled. I'm unsure if introducing an analyzer for this is worthwhile. Note that most developer scenarios involve building on one machine and then deploying and running on other machines or in the cloud. Therefore, having an analyzer during compilation time might not be helpful.
