### ISSUE TITLE
[wasm] Don't require ICU libs for invariant globalization

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#100583]
In `InvariantGlobalization=true` we still need to link ICU native libs and they don't get linked out. We could have a special build of corelib and (pick it in SDK during app build) that would not need ICU libs. It should reduc wasm size

**Comment by maraf** [comment]
cc @ilonatommy

**Comment by maraf** [comment]
Well, it shouldn't be a problem that we link the ICU libs, because they should get linked out when IL trimmer trims dll imports pointing to them. It seeems that there are some paths to ICU from managed that are missing the feature flag guard

**Comment by maraf** [comment]
Please, investigate the possible trimming issue in .NET 9 timeframe

**Comment by ilonatommy** [comment]
Reproduction:
1) build sample with
```
    <InvariantGlobalization>false</InvariantGlobalization>
    <WasmNativeStrip>false</WasmNativeStrip>
```
2) take `dotnet.native.wasm` and transform it to .wat (binaryen/wasm2wat)
3) look for e.g. `ucal_getKeywordValuesForLocale` (comes from `System.Globalization.Native` - lib needed for ICU globalization only)

**Comment by maraf** [comment]
All the ICU symbols are really linked out
