### ISSUE TITLE
AlpineARM32 Only, running dotnet new command will be Stuck with long time high CPU consumption after installing net9.0.100-preview.3.24175.24 

### ISSUE THREAD

**Issue by ChenhuiYuan01** [dotnet/runtime#100536]
**Reproduction Steps**
1. On Linux AlpineARM32 in docker , install 9.0.100-preview.3.24175.24  from https://dev.azure.com/dnceng/internal/_build/results?buildId=2414737&view=artifacts&pathAsName=false&type=publishedArtifacts 
2. In CLI, run dotnet new console

**Excepted:**
The project will be created successfully

**Actual Behavior**
Project is blocked   ---》Stuck with long time high CPU consumption
Running dotnet new console ------🡪 Stuck with long time high CPU consumption.
![pending](https://github.com/dotnet/sdk/assets/92560562/7130c957-6735-4cb6-93f0-306cb73c7528)
![cpu](https://github.com/dotnet/sdk/assets/92560562/70fd791e-ed0a-48d0-bc65-96fc4a0ea8fb)

**Dotnet --info**
.NET SDK:
 Version:           9.0.100-preview.3.24175.24
 Commit:            09d6f381e6
 Workload version:  9.0.100-manifests.77bb7ba9
 MSBuild version:   17.10.0-preview-24175-03+89b42a486

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.20
 OS Platform: Linux
 RID:         linux-musl-arm
 Base Path:   /root/mytest/sdk/9.0.100-preview.3.24175.24/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.3.24172.9
  Architecture: arm
  Commit:       9e6ba1f68c

.NET SDKs installed:
  9.0.100-preview.3.24175.24 [/root/mytest/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.3.24172.13 [/root/mytest/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24172.9 [/root/mytest/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

**Comment by jeffschwMSFT** [comment]
@mangod9 can you take a look?  not sure where this high cpu may be coming from.  also including @elinor-fung

**Comment by mangod9** [comment]
@ChenhuiYuan01, assuming this is a consistent repro are you able to capture a dump with dotnet-dump when the high cpu is occurring? Thanks

**Comment by NicoleWang001** [comment]
> > You're saying it hangs when running `dotnet --help`? That line also has a `dotnet new console` on it so I assumed it was that. Please do if you can.
> 
> @marcpopMSFT yes it hangs when running `dotnet --help`. Interestingly it hangs _after_ printing the help command's text.
> 
> I cannot get a dump without some further help with this - `dotnet tool install --global dotnet-dump` hangs, obviously, and the [dotnet dump tool](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump#install) does not provide a linux-musl-arm binary. Arm64 does not hang.

@mangod9  We could not get a dump either as the dotnet-dump hangs.  
Also tried below, but still could not get a dump
1.  On Alpine Arm32 container, install .NET 8.0->install tool dotnet-dump ->install SDK .NET 9.0.100-preview.3.24175.24 and run dotnet--help ->dotnet-dump hangs as well
2. On Alpine Arm32 container, install SDK .NET 9.0.100-preview.3.24175.24 and run dotnet--help. On host, install SDK .NET 9.0.100-preview.3.24175.24-> install tool dotnet-dump -> dotnet-dump failed with
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.Sockets.SocketException (111): Connection refused

**Comment by lauxjpn** [comment]
@NicoleWang001 I would suggest to generate a core dump without any .NET tool help (using OS bundled native tools). Then run `dotnet-dump` on a similar environment (that is not that failing docker container, e.g. a real arm32v7 environment) to analyze that previously collected core dump.

**Comment by lauxjpn** [comment]
I am experiencing hangs for all `dotnet` commands when targeting `arm32v7` once the SDK is installed (not if only the runtime is installed though), for .NET 6, 7, 8 and 9:

```yml
FROM mcr.microsoft.com/dotnet/nightly/sdk:9.0.100-preview.3-alpine3.19-arm32v7
WORKDIR /srv
RUN dotnet help
```

```yml
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine3.18-arm32v7
WORKDIR /srv
RUN dotnet help
```

```yml
FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18-arm32v7
WORKDIR /srv
RUN dotnet help
```

```yml
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.18-arm32v7
WORKDIR /srv
RUN dotnet help
```

```bash
docker build -f 'arm32v7-test.Dockerfile' --platform 'linux/arm32v7' --pull -t 'arm32v7-test:latest' ./empty/
```

Tested with a docker a host that is Windows 10 (with WSL2 integration to Ubuntu) or an Ubuntu 22.04/23.10 VM (VirtualBox, with a Windows 10 host). So these are environments that use _qemu_ to emulate `arm32v7`.

BTW, downloading and running the SDK in a custom build (buildroot) qemu busybox image targeting `arm32v7` (so without docker) works fine. I have not yet compared my custom buildroot options against those of https://github.com/docker-library/busybox.

**Comment by lbussell** [comment]
@lauxjpn the behavior for the 6.0, 7.0, and 8.0 Docker images is unexpected. Can you please post an issue for that in https://github.com/dotnet/dotnet-docker?

**Comment by janvorli** [comment]
I have done some inital investigations. I have found the issue is related to the new exception handling that was enabled in preview 3 by default. There is some exception that occurs on a secondary thread during the shutdown of the process and the function that the new exception handling uses to iterate over stack frames keeps returning the same frame over and over. This is actually an explicit frame (`InlinedCallFrame`) which has its internal "next" pointer pointing to itself. I don't have any idea how that could happen at the moment, but that causes the infinite loop there.
Until the issue is fully understood and fixed, it can be mitigated by enabling the legacy exception handling by setting the env variable DOTNET_LegacyExceptionHandling=1.
