### ISSUE TITLE
I am COM and I must Release() (in ComWrappers)

### ISSUE THREAD

**Issue by rmsimpson** [dotnet/runtime#100645]
There doesn't appear to be any decent way to deterministically release a COM pointer (especially in a non-Windows platform) specifically using ComWrappers.

The `ComObject` class implements a destructor, but doesn't implement `IDisposable`.  `ComObject`'s `FinalRelease`() method only works if the `UniqueInstance` boolean is set, and that doesn't seem to get set ever.  As a matter of fact, `ComInterfaceMarshaller::ConvertToManaged()` never passes in anything except `Unwrap` for the `CreateObjectFlags` parameter.

It's also awkward to cast a managed interface pointer to `ComObject`.  You have to box it first.  Currently the only way I've been able to get this to work is using a helper that dynamically invokes `ComObject`'s destructor, like this:

```
private readonly static MethodInfo? ComFinalize = typeof(ComObject).GetMethod("Finalize", BindingFlags.NonPublic | BindingFlags.Instance);

internal static void Release(object? managedInterface)
{
	if (ComFinalize != null && managedInterface is ComObject com)
	{
		ComFinalize.Invoke(com, null);
		GC.SuppressFinalize(com);
	}
}
```

It seems like there's got to be a better way.

Can we have maybe an attribute to identify a returned object as being unique?  It'd be helpful if there was a `[UniqueInterface]` attribute I could decorate the output parameter with so I could call `FinalRelease()` later on.

For example, in my case I'm using 7z.so in Linux/OSX:

```
[LibraryImport("7z")]
public static partial int CreateObject(in Guid classID, in Guid interfaceID, 
	[MarshalAs(UnmanagedType.Interface)] out object? createdObject);
```
There are also many interfaces and so on that return back pointers, for example:
```
[GeneratedComInterface]
[Guid("23170F69-40C1-278A-0000-000600400000")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal partial interface IInArchiveGetStream
{
	[PreserveSig]
	int GetStream(uint index, out ISequentialInStream? stream);
}
```
Of course, I'm also not entirely certain what the `UniqueInstance` boolean is really for, I'm just guessing behavior based on the source code which really doesn't mention it much.

**Comment by DaZombieKiller** [comment]
> It's also awkward to cast a managed interface pointer to `ComObject`. You have to box it first.

Could you elaborate on this? Boxing implies you have a value type, which does not sound right to me.

> It seems like there's got to be a better way.

Indeed. I believe `UniqueComInterfaceMarshaller<T>` already exists for your use case, so you can simply change your P/Invoke declaration to:
```cs
[LibraryImport("7z")]
public static partial int CreateObject(
    in Guid classID,
    in Guid interfaceID,
    [MarshalUsing(typeof(UniqueComInterfaceMarshaller<object>))] out object? createdObject);
```
And then `FinalRelease` should work as you expect.

**Comment by rmsimpson** [comment]
Sorry, what I meant by boxing is that this code doesn't work:

```
void MyFunc(ISequentialInStream managedObject)
{
	ComObject? comObject = managedObject as ComObject; // <-- this doesn't work, won't compile, etc.
	ComObject? comObject = (object)managedObject as ComObject; // <-- this works and will compile.
}

```
UniqueComInterfaceMarshaller looks like will work for me, but it means decorating every output value with it.  I'm not even sure under what circumstances UniqueInstance should be false??

**Comment by AaronRobinsonMSFT** [comment]
> UniqueComInterfaceMarshaller looks like will work for me, 

Using `UniqueComInterfaceMarshaller` is the correct way to handle this.

> but it means decorating every output value with it. 

Yes, that is by design.

> I'm not even sure under what circumstances UniqueInstance should be false??

There are some notes [here](https://learn.microsoft.com/dotnet/standard/native-interop/tutorial-comwrappers#step-4--handle-native-object-wrapper-lifetime-details) about this.

The new `ComWrappers` API was designed around being explicit. Either the consumer wants the GC to handle lifetime or they want to participate - it is a binary choice. The vast majority of COM interop consumers can let the GC handle the COM instance lifetimes - the default. There is an opt-out but it should be use narrowly as the entire purpose of the GC is to handle lifetime management.

Is there a novel scenario where manual management of the COM instance lifetime is needed? The two well-known cases are:

1) Allocation tracking tooling - only used in non-production scenarios.
2) COM objects that hold onto resources like files. The most common example is [DIA](https://learn.microsoft.com/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk).

**Comment by rmsimpson** [comment]
> Is there a novel scenario where manual management of the COM instance lifetime is needed? The two well-known cases are:
> 
>     1. Allocation tracking tooling - only used in non-production scenarios.
> 
>     2. COM objects that hold onto resources like files. The most common example is [DIA](https://learn.microsoft.com/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk).

In my case, a combination of 2 and:
3.  You're utilizing a COM component that doesn't support multi-threaded destruction.  In this case, the 7z's COM implementation was using non-atomic `++` and `--` operators and comparisons in its `AddRef`/`Release` [implementation](https://github.com/ip7z/7zip/blob/5b39dc76f1bc82f941d5c800ab9f34407a06b53a/CPP/Common/MyCom.h#L243).  Multi-threaded GC was causing shared references to have their ref counts stomped on.

**Comment by AaronRobinsonMSFT** [comment]
> You're utilizing a COM component that doesn't support multi-threaded destruction

Then this should be created on an STA thread or only used from a single thread. On non-Windows there is unfortunately no way to enforce this, but using it from a single thread is the solution here. If this is not designated an STA COM class on Windows, it is a bug, From the .NET perspective the recommended solution with `ComWrappers` is to use the `UniqueComInterfaceMarshaller`. An alternative is to create a .NET wrapper that manually manages the lifetime either by wrapping the object or manually dispatching through an `IntPtr`.
