### ISSUE TITLE
Linq's Count method makes unnecessary enumeration

### ISSUE THREAD

**Issue by leandromoh** [dotnet/runtime#100677]
Basically Linq's `Count` method does not check the cheap way using `TryGetNonEnumeratedCount`. So sometimes it makes unnecessary enumeration when `TryGetNonEnumeratedCount` does not. For example when was applied a `Select` before count.

[sharplab example](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwLACgACAmAjBzABgAJNcA6AGQEsoBHAbgwwDcBDMYgD2IF5ioAUwDuxWsADaAXQDexXDGLZFAZgC+TdM3TtOAT1x9u5AMqCANoIDGwABQ9eAPmJyyATlsAiAGYB7X54AlAykAOzcxIjyIWrEwawcxABehvwG5ADCvtB28VpYuB4pedq6xHrYRlymFtZ2Ds6uhV4ARhxBIZjhPFG4MXGaZUmVadjkACpgegDigsAAcr5QAKJQEAC2gmBswIJwWTm22cDEZVbZUMCBxAD8xOc5xCDEALTR2u62w8FAA=)

IMHO the implementation shoud try the cheap count using `TryGetNonEnumeratedCount` before enumerate the source.

**Comment by stephentoub** [comment]
> For example when was applied a Select before count.

This is a deliberate choice. We tried at one point not having the Select's selectors run, and it broke folks that were using Count() as a way to forcefully enumerate and rely on the side-effects of Select's selectors running. We had to revert.

**Comment by leandromoh** [comment]
Thanks for clarify @stephentoub
