### ISSUE TITLE
Cannot install wasi-experimental: Not found in NuGet feeds

### ISSUE THREAD

**Issue by dylanh724** [dotnet/runtime#100666]
### Description

> **dotnet workload install wasi-experimental**

> Advertising manifest not updated. Manifest package for microsoft.net.sdk.android doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.ios doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.maccatalyst doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.macos doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.maui doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.tvos doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.mono.toolchain.current doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.emscripten.current doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.emscripten.net6 doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.emscripten.net7 doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.mono.toolchain.net6 doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.mono.toolchain.net7 doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.aspire doesn't exist.
Downloading Microsoft.NET.Runtime.WebAssembly.Wasi.Sdk.Msi.x64 (8.0.3)
**Workload installation failed. Rolling back installed packs...
Workload installation failed: One or more errors occurred. (Version 8.0.3 of package microsoft.net.runtime.webassembly.wasi.sdk.msi.x64 is not found in NuGet feeds C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)**

### Reproduction Steps

1. Install the latest .net 8 (`8.0.203`): `winget install Microsoft.DotNet.SDK.8`
2. Enable wasi: `dotnet workload install wasi-experimental`
3. Error

This is a mostly-fresh install of Windows.

### Expected behavior

Should have installed

### Actual behavior

> **Workload installation failed. Rolling back installed packs...
Workload installation failed: One or more errors occurred. (Version 8.0.3 of package microsoft.net.runtime.webassembly.wasi.sdk.msi.x64 is not found in NuGet feeds C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)**

### Regression?

Probably - it worked before. In this new reformat of Windows, getting the latest version of .net 8, it's failing.

### Known Workarounds

Perhaps downgrade? Not sure

### Configuration

* .NET v8.0.23
* Win11

**Comment by maraf** [comment]
Can you install anything from nuget.org? From the log it seems you don't have `nuget.org` configured as source and it looks only for "offline" packages. What does your nuget config look like `"C:\Users\USER\AppData\Roaming\NuGet\NuGet.Config"`?

**Comment by dylanh724** [comment]
> Can you install anything from nuget.org? From the log it seems you don't have `nuget.org` configured as source and it looks only for "offline" packages. What does your nuget config look like `"C:\Users\USER\AppData\Roaming\NuGet\NuGet.Config"`?

It's empty lol. I deleted it and it seemed to regenerate when trying again, resolving this issue. What could possibly cause it to be empty? This is a fresh Windows install that recently installed vs2022 community and dotnet.

**Comment by maraf** [comment]
Sorry, I have no idea. I'm going to close this issue. Feel free to reopen it if it happens again

**Comment by dylanh724** [comment]
> Sorry, I have no idea. I'm going to close this issue. Feel free to reopen it if it happens again

I just reprod it again on another fresh install of a new device. All I can think of that I did differently is installed Visual Studio and related via Choco, that *should* be the same.

**Comment by maraf** [comment]
If I understand correctly, it does repro for installing .NET both with winget and choco. It doesn't repro when installing .NET via VS installer, right?
