### ISSUE TITLE
Valgrind:  JIT noway_assert codeGen->genAddrRelocTypeHint((size_t)addr) != IMAGE_REL_BASED_REL32

### ISSUE THREAD

**Issue by leculver** [dotnet/runtime#100600]
I'm working to see if we can make valgrind memcheck useful for .Net applications (or at least the .Net Runtime itself).  Cleaning this up so we can at least get basic C# applications running through valgrind is the first step, but I'm running into a JIT noway_assert in a very basic, hello-world application.

The assert is here:  https://github.com/dotnet/runtime/blob/7c030e8ef0d14c4cf6c473cff8d761f8040f0e88/src/coreclr/jit/emitxarch.cpp#L16564

Commenting this out results in a successful run, as does running retail.  Can you please take a look and see if we can clean this up?  While I'm unblocked from current work by commenting it out, I'd like to get at least "hello world" working successfully in valgrind so we can use this tool on a wider scale.

## Repro Steps

The repro steps are simple, but do require a little extra work, as the valgrind installed with Ubuntu 22 does not work well with .Net.

First, install valgrind.  You can follow instructions from valgrind.org, but here's a quick start:

``` bash
wget https://sourceware.org/pub/valgrind/valgrind-3.22.0.tar.bz2
tar xjvf valgrind-3.22.0.tar.bz2
cd valgrind-3.22.0
./configure && make
sudo make install
```

Build a basic hello world app:

``` bash
mkdir hello
cd hello
dotnet new console
dotnet build -c Release
```

Sync dotnet/runtime main branch and build.  After that the following will reproduce the problem.  Note that valgrind currently requires us to set a GC hardlimit.  My repo is in `~/git/runtime`, replace that with your path below:

``` bash
export CORE_LIBRARIES=~/git/runtime/artifacts/bin/runtime/net9.0-linux-Debug-x64
export CORE_ROOT=~/git/runtime/artifacts/bin/coreclr/linux.x64.Debug
export DOTNET_GCHeapHardLimit=c800000

/usr/local/bin/valgrind $CORE_ROOT/corerun ~/projects/hello/bin/Release/net8.0/hello.dll
```

If you need to debug the target process, keep in mind that Valgrind runs the app virtually, you can't just connect a debugger to it.  To debug the target process, you have to use `gdb`.  Launch the program with these flags:  `/usr/local/bin/valgrind --vgdb-error=0 --vgdb=yes  $CORE_ROOT/corerun ~/projects/hello/bin/Release/net8.0/hello.dll`.  Then follow the instructions onscreen.  It will tell you to launch:  `gdb $CORE_ROOT/corerun` and when prompted run `target remote | /usr/local/libexec/valgrind/../../bin/vgdb --pid=[pid]`.

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
I wonder if multiple `CEEJitInfo::getRelocTypeHint` calls are not consistent (i.e., the VM changes its mind), maybe due to how valgrind messes with memory, e.g., see `ExecutableAllocator::IsPreferredExecutableRange()`

Maybe running with `DOTNET_JitEnableOptionalRelocs=0` will get around the problem?

**Comment by EgorBo** [comment]
> I wonder if multiple CEEJitInfo::getRelocTypeHint calls are not consistent 

Yes, `getRelocTypeHint` is not precise (and we currently can't get a precise value without rewriting code manager on VM side). If it happens to return false positive - we typically throw away current JIT compilation, disable relocs completely for everyone and start JIT again

**Comment by leculver** [comment]
> Maybe running with `DOTNET_JitEnableOptionalRelocs=0` will get around the problem?
This worked!  No assert when I enabled that, and we are able to get through "hello world" in a debug version of the runtime.

Is this a real problem worth fixing?  If not, I'll close this issue.

It sounds like we can't easily fix this (without rewriting code manager), and it's only affecting this scenario.  I can just document setting `DOTNET_JitEnableOptionalRelocs=0` like we have to with setting the GC heap hard limit.

**Comment by EgorBo** [comment]
Personally,  I don't know - it's not precise, but it's not expected to be non-consistent for the same input

**Comment by BruceForstall** [comment]
> Is this a real problem worth fixing?

I would expect not. Of course, setting this config variable means we will never execute some code paths, but perhaps that's ok, to still achieve the main goal of using valgrind across the vast majority of the product.

**Comment by leculver** [comment]
> > Is this a real problem worth fixing?
> I would expect not. Of course, setting this config variable means we will never execute some code paths, but perhaps that's ok, to still achieve the main goal of using valgrind across the vast majority of the product.

Sounds good, I will close this then since there is an easy flag to avoid the assert.  Thanks for taking a look!
