### ISSUE TITLE
Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT") does not return the environment variable's value entered in the CLI

### ISSUE THREAD

**Issue by Arash-Sabet** [dotnet/runtime#100674]
### Description

We have a dotnet 8.0 console application that is supposed to read an `appsettings.{Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")}.json` file based on the value entered for the `DOTNET_ENVIRONMENT` environment variable. Unfortunately `Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")` always returns null.

### Reproduction Steps

Issue the following command:

```
 dotnet run -c Release -e DOTNET_ENVIRONMENT=Docker
```

### Expected behavior

`Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")`  should return the value `Docker` per the reproduction step to be able to utilize `appsettings.Docker.json` file.

### Actual behavior

`Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")`  returns null or empty.

### Configuration

.NET SDK:
 Version:           8.0.203
 Commit:            5e1ceea679
 Workload version:  8.0.200-manifests.8cf8de6d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.203\

**Comment by tommysor** [comment]
I don't think `-e` is a valid switch for `dotnet run`.
I also don't know of any way to pass an environment variable as a switch.
Possibly mixup with `docker run` that does have a switch `-e, --env list                         Set environment variables`

For `dotnet run` I believe you need to set the environment variable first.

Given a console application:
```csharp
var myValue = Environment.GetEnvironmentVariable("MyVar");
Console.WriteLine($"MyVar: '{myValue}'");
```
Can be invoked with windows cmd:
```
set "MyVar=SomeValue" & dotnet run
MyVar: 'SomeValue'
```

**Comment by Arash-Sabet** [comment]
Thanks @tommysor 
It worked well on Windows 11's command prompt but not on PowerShell. Is there something to consider in PS?
