### ISSUE TITLE
Suggestion: Make X509Certificate2Collection (and X509CertificateCollection) thread-safe

### ISSUE THREAD

**Issue by johncrim** [dotnet/runtime#100613]
This is not an API change, other than the fact that the lack of thread safety in `X509Certificate2Collection` could result in subtle bugs.

Many other .NET and ASP.NET APIs use a `X509Certificate2Collection` (or `X509CertificateCollection`) to setup server or client validation. Examples:
* [Setting up certificate authentication using a custom trust store](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-8.0#customtruststore)
* [Choosing a certificate for client authentication](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.clientcertificates?view=net-8.0#system-net-security-sslclientauthenticationoptions-clientcertificates)
* [Setting up a `ChainPolicy` for server certificate validation](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.customtruststore?view=net-8.0)

The `X509Certificate2Collection` is mutable but not thread-safe, and the object is shared across threads. Certificates are updated and expire, and long-running apps should fetch new certificates and remove old certificates as needed. It should be fine to update the certificates in any of these collections without potential concurrency bugs.

**Comment by bartonjs** [comment]
> and the object is shared across threads

Where is an example of it being mutated across threads?

**Comment by johncrim** [comment]
I don't have any examples of it being mutated simultaneously on multiple threads - it certainly can be, but I don't see that in the .NET Framework. The way it is normally used it can be mutated on one thread while being read from multiple threads. I would expect that if someone needs to update it from multiple threads concurrently they could handle their own synchronization.

The guidance for the base class [`CollectionBase`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.collectionbase?view=net-8.0#thread-safety) is:

> This implementation does not provide a synchronized (thread safe) wrapper for a [CollectionBase](https://learn.microsoft.com/en-us/dotnet/api/system.collections.collectionbase?view=net-8.0), but derived classes can create their own synchronized versions of the [CollectionBase](https://learn.microsoft.com/en-us/dotnet/api/system.collections.collectionbase?view=net-8.0) using the [SyncRoot](https://learn.microsoft.com/en-us/dotnet/api/system.collections.icollection.syncroot?view=net-8.0#system-collections-icollection-syncroot) property.

However the CertificateCollection classes don't use the `SyncRoot` or provide other synchronization.

It's mutable clearly - I can add or remove certificates, eg when I detect that they're updated in our Azure KeyVault. And it's shared across threads and can easily be read simultaneously - for example to setup client certificate authentication one sets  [SslClientAuthenticationOptions.ClientCertificates](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.clientcertificates?view=net-8.0#system-net-security-sslclientauthenticationoptions-clientcertificates), which is then read by the http handler on any thread when calls are made with the `HttpClient`.

I want to be clear that I don't have a call stack showing a thread-safety bug for this collection. But I do have a use case where I need to keep the collection of certificates current, and most of the ASP.NET infrastructure/middleware uses a single `X509Certificate(2)Collection` that is set on initialization, read concurrently on multiple threads and not synchronized; and in some cases (eg [ASP.NET Certificate Authentication](//learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-8.0#customtruststore) the only way to update the pool of certificates is to mutate the CertificateCollection.

I realize it would probably help if I wrote a multi-threaded test to prove that there can be incorrect collection behavior; but the bottom line is that `CollectionBase` is not threadsafe.

**Comment by vcsjones** [comment]
> But I do have a use case where I need to keep the collection of certificates current

I am not sure making the `X509Certificate2Collection` thread safe would make your use case thread safe.

Consider something like this.

```C#
/* 1: */ X509Certificate2Collection someCollection;
/* 2: */ someCollection.Remove(oldCertificate);
/* 3: */ someCollection.Add(newCertificate);
```

If another thread is using `someCollection` and it attempts to say "get me the current certificate" between lines 2 and 3, you still have a thread safety problem because there is no certificate in the collection since it happened between remove the old and add the new.

The collection itself cannot really enforce atomic updates of its contents, you would need to take a lock when everyone attempts to interact with the collection.

**Comment by Clockwork-Muse** [comment]
>However the CertificateCollection classes don't use the `SyncRoot` or provide other synchronization.

Nor do the generic collections, because at the point you'd want it you likely need/want some broader external "atomic" access mechanism that encompasses more than just the raw collection (as @vcsjones is saying).

Thread safety is a far smaller section of "application safety" here....

**Comment by johncrim** [comment]
@vcsjones - thanks for the reply. The issue you raise is also a potential problem, though it could be handled by delaying the remove. 

I submitted this issue out of concern for standard thread safety problems, eg collection pointers not atomically updated or collection state not atomically updated.

I'm fine if you want to expand this to "X509Certificate(2)Collections used in the frameworks need to be immutable or not shared across threads; and there needs to be a separate pattern for coordinating updates". That would be much safer.

In my code I use `Interlocked.Exchange()` to avoid mutating a certificate collection in use; however due to the amount of framework code that relies on a single `X509Certificate(2)Collection` that is created on startup there's no way to push updates or use an `Interlocked.Exchange()` to swap out the connection, without mutating that single `X509Certificate(2)Collection`.

**Comment by Clockwork-Muse** [comment]
> I'm fine if you want to expand this to "X509Certificate(2)Collections used in the frameworks need to be immutable or not shared across threads; and there needs to be a separate pattern for coordinating updates". That would be much safer.

Unless marked otherwise, it's better to assume that _no_ class is threadsafe.  That's the default state of the world, since it's much harder (and more expensive, performance wise) to make things threadsafe.

>In my code I use `Interlocked.Exchange()` to avoid mutating a certificate collection in use; however due to the amount of framework code that relies on a single `X509Certificate(2)Collection` that is created on startup there's no way to push updates or use an `Interlocked.Exchange()` to swap out the connection, without mutating that single `X509Certificate(2)Collection`.

The implication of your statement here is that you have what is effectively shared mutable global state, and wanting it to be picked up itself.
If so, don't do that.
Instead, you want some sort of update mechanism to push the value to those places that need it, as a snapshot of the value.  Consider how [`IOptionsMonitor<T>`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.ioptionsmonitor-1?view=dotnet-plat-ext-8.0) is meant to be used - although there are a number of related or similar patterns to use.

**Comment by jeffhandley** [comment]
I'm going to close this since there isn't a compelling enough reason to make this investment. Thanks for submitting the suggestion nonetheless, @johncrim.
