### ISSUE TITLE
[browser][MT] HttpClient does not work inside Thread().Start()

### ISSUE THREAD

**Issue by glutio** [dotnet/runtime#100636]
### Description

HttpClient does not work inside `new Thread().Start()`. Thread execution stops and no exception is thrown. But it works inside `Task.Run()`. If this is by design, what are the limitations of Threads vs Tasks in the MT runtime? Thanks!

### Reproduction Steps

Program.cs
```
new Thread(async (o) =>
{
    Console.WriteLine("Start Thread");
    try
    {
        var result = await new HttpClient().GetAsync("https://raw.githubusercontent.com/dotnet/runtime/main/README.md");
        Console.WriteLine(result.StatusCode);
    }
    catch (Exception e)
    {
        Console.WriteLine(e.ToString());
    }
    Console.WriteLine("End Thread");
}).Start();
```

### Expected behavior

Start Thread
OK
End Thread

### Actual behavior

Start Thread

### Regression?

no

### Known Workarounds

Works inside Task.Run()
```
await Task.Run(async () =>
{
    Console.WriteLine("Start Task");
    var result = await new HttpClient().GetAsync("https://raw.githubusercontent.com/dotnet/runtime/main/README.md");
    Console.WriteLine(result.StatusCode);
    Console.WriteLine("End Task");
});
```

### Configuration

.net9-preview

**Comment by pavelsavara** [comment]
I think this would not work even on desktop. 
The reason is that `new Task` first parameter expects [synchronous delegate](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.-ctor?view=net-8.0#system-threading-thread-ctor(system-threading-threadstart)) and ignores any promises returned.

The way how to test this is something like

```
async Task LogicAsync()
{
    Console.WriteLine("Start Thread");
    try
    {
        var result = await new HttpClient().GetAsync("https://raw.githubusercontent.com/dotnet/runtime/main/README.md");
        Console.WriteLine(result.StatusCode);
    }
    catch (Exception e)
    {
        Console.WriteLine(e.ToString());
    }
    Console.WriteLine("End Thread");
}

var thread = new Thread(() =>
    LogicAsync().Wait(); // blocking here until Task resolved
});
thread.Start();
```

**Comment by glutio** [comment]
Thanks, tried the suggested non async thread proc - same result, it does not work in browser. However both sync and async thread proc work on desktop (linqpad)

**Comment by pavelsavara** [comment]
OK, I took it more seriously now and actually tested it. 
Note that the continuation is not running on your thread but on thread pool.

```cs
using System;
using System.Net.Http;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices.JavaScript;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;

public class X
{
    public static int Main(){

        new Thread(async (o) =>
        {
            Console.WriteLine("Start Thread" + Environment.CurrentManagedThreadId);
            try
            {
                var result = await new HttpClient().GetAsync("https://raw.githubusercontent.com/dotnet/runtime/main/README.md");
                Console.WriteLine(result.StatusCode);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            Console.WriteLine("End Thread"+ Environment.CurrentManagedThreadId);
        }).Start();

        return 0;
    }
}
```

**Comment by glutio** [comment]
Ok, thank you, I had `dotnet.run()` instead of `runMain()` in my javascript. Your example generated `MONO_WASM: Assert failed: .NET runtime already exited with 0 Program terminated with exit(0). You can use runtime.runMain() which doesn't exit the runtime.`, so I changed it to `runMain()` and I confirm there's **no issue** the way I originally reported it. However if I use `dotnet.run()` and block the main thread with thread.Join() it still doesn't work, not sure if that's a bug...

```
import { dotnet } from './_framework/dotnet.js'
await dotnet.run();
```
```
var thread = new Thread(async (o) =>
{
    Console.WriteLine("Start Thread" + Environment.CurrentManagedThreadId);
    var result = await new HttpClient().GetAsync("https://raw.githubusercontent.com/dotnet/runtime/main/README.md");
    Console.WriteLine(result.StatusCode);
    Console.WriteLine("End Thread" + Environment.CurrentManagedThreadId);
});
thread.Start();
thread.Join();
return 0;
```

Thank you
