### ISSUE TITLE
.Net MAUI File.ReadAllText fails with Exception.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#100603]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-MAUI-FileReadAllText-fails-with-Ex/10582979)._

---
When built under .Net 7 the ReadAllText worked on both Windows and Android devices under Visual Studio. However with .Net 8 the Android version fails with an exception System.IO.DirectoryNotFoundException
  Message=Could not find a part of the path '/data/user/0/<xxxx>/files/Documents/<my file>'.

```cs
var x = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
  string fileName = Path.Combine(x, saveGameFileName);

string jsonString = File.ReadAllText(fileName);
```

Note: The app works under Windows.

---
#### Feedback Bot on 2/12/2024, 07:02 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
The two slashes between `0` and `files` in `/data/user/0//files/Documents/` seems suspect.

**Comment by adamsitnik** [comment]
> The two slashes between `0` and `files` in `/data/user/0//files/Documents/` seems suspect.

@CyrusNajmabadi is right, this is a matter of fixing the path.
