### ISSUE TITLE
System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle tests failing

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#100647]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=629829
Build error leg or test failing: System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle
Pull request: https://github.com/dotnet/runtime/pull/100110

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=629829
**Error message validated:** `[at System.Diagnostics.Tests.ProcessStartInfoTests.TestWindowStyle`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/4/2024 6:39:44 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci has it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
