### ISSUE TITLE
Custom Build Task Execution Order with NativeAOT Compilation

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#100646]
Hello!

I am currently working on a .NET project that involves obfuscation of the assembly as a post-build step before the NativeAOT compilation begins. The goal is to ensure the assembly is obfuscated right after the build process but before the NativeAOT compilation starts. This is crucial for the security aspect of our project.

Here's an excerpt of the MSBuild configuration we're using to achieve this:
![image](https://github.com/dotnet/runtime/assets/111659964/92c96b8e-028b-43ab-8453-6b976bb528a5)

However, we encountered a challenge with the timing of the NativeAOT compilation process. It seems that the NativeAOT compilation starts immediately after the build, not leaving a clear hook for a custom task to run obfuscation before NativeAOT compilation takes over. This situation results in the following error when attempting to modify the DLL for obfuscation:

**Unhandled Exception: System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open.**

**Request:**
Could you provide guidance or recommend a practice for integrating custom build tasks specifically with NativeAOT compilation? Specifically, we're looking for a way to ensure our CustomObfuscation task runs after the regular build process but strictly before the NativeAOT compilation begins.

This functionality is critical for ensuring the security of our application by obfuscating sensitive code before it's compiled into native code by NativeAOT. Any advice or enhancements to facilitate this process would be greatly appreciated.

Thank you for your support and looking forward to your recommendations.

**Comment by hez2010** [comment]
Maybe you can try setting the BeforeTargets to ComputeIlcCompileInputs.

**Comment by MichalStrehovsky** [comment]
Obfuscated inputs are unsupported. We don't have a documented target that can be used for this. ComputeIlcCompileInputs will likely work for .NET 8, we don't make support guarantees around these targets though.
