### ISSUE TITLE
Path.ChangeExtension with an empty string behaves differently on Linux and Windows platforms

### ISSUE THREAD

**Issue by jasonleenaylor** [dotnet/runtime#100687]
### Description

We have a cross platform application running on Windows and Linux and we noticed a difference between the
ChangeExtension implementation on the two platforms. On Windows calling ChangeExtension with an empty string results in the extension being removed. e.g. "file.extension" becomes "file" but on Linux we get "file."

On windows it must be running the framework version of this code but on Linux we get the core runtime implementation.

### Reproduction Steps

Run Path.ChangeExtension("file.extension", "") on Windows and Linux

### Expected behavior

The extension is removed leaving a bare file name with no trailing '.'

### Actual behavior

The extension is removed leaving a trailing '.'

### Regression?

This works as described in .NET Framework

### Known Workarounds

Users can use Path.RemoveExtension instead when removing, but if you are adding an optional extension the only workaround is to add a test for empty before using the method

### Other information

https://github.com/dotnet/runtime/blob/068ba8eba9787bb180878561d443abcf6133be9f/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L75

**Comment by jasonleenaylor** [comment]
@vcsjones or anyone I am happy to make a PR for this, but I would like to add a unit test. Can you help me locate other unit tests for System.IO?

**Comment by tommysor** [comment]
@jasonleenaylor Tests:
https://github.com/dotnet/runtime/blob/d79a753f0b4f78bf809b173018f18c6c98e6953d/src/libraries/System.Runtime/tests/System.Runtime.Extensions.Tests/System/IO/PathTests.cs#L13-L34

**Comment by MihaZupan** [comment]
```c#
Console.WriteLine(Path.ChangeExtension("file.extension", null));
Console.WriteLine(Path.ChangeExtension("file.extension", ""));
```
prints
```
file
file.
```

On .NET Framework, .NET 8 on Windows and .NET 8 on Linux.

**Comment by jasonleenaylor** [comment]
@MihaZupan Hmm, we saw this issue when running in .NET 6 on Windows, and .NET 6 on Linux.

It added the period on Linux, but not on Windows.
