### ISSUE TITLE
Stress issues on x86 in JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.dll

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#100695]
Saw two failures in one PR:

https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-8544b1d971e1457d9b/JIT.performance.0.1/1/console.303a6362.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-8544b1d971e1457d9b/JIT.performance.0.1/1/console.303a6362.log?helixlogtype=result)

```
08:52:39.270 Running test: JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.dll

Assert failure(PID 4656 [0x00001230], Thread: 5720 [0x1658]): SanityCheck()

CORECLR! MethodTable::Validate + 0x31 (0x7236f60c)
CORECLR! Object::ValidateInner + 0x133 (0x72379cc3)
CORECLR! Object::Validate + 0x98 (0x72379b58)
CORECLR! WKS::GCHeap::Promote + 0x8F (0x726c769f)
CORECLR! PromoteCarefully + 0x85 (0x723b7805)
CORECLR! GCFrame::GcScanRoots + 0x37 (0x722d579c)
CORECLR! ScanStackRoots + 0x1C4 (0x72490c42)
CORECLR! GCToEEInterface::GcScanRoots + 0xEF (0x7248edc3)
CORECLR! WKS::gc_heap::mark_phase + 0x20D (0x726dc1bb)
CORECLR! WKS::gc_heap::gc1 + 0x144 (0x726d5d70)
    File: D:\a\_work\1\s\src\coreclr\vm\methodtable.cpp:9528
    Image: C:\h\w\A04108CC\p\corerun.exe
```

and

https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-cf3303f0ac4941f19e/JIT.performance.0.1/1/console.d9957d6e.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-cf3303f0ac4941f19e/JIT.performance.0.1/1/console.d9957d6e.log?helixlogtype=result)

```
08:58:59.969 Running test: JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.dll

Assert failure(PID 7428 [0x00001d04], Thread: 8620 [0x21ac]): RawGetMethodTable()

CORECLR! WKS::CObjectHeader::SetMarked + 0x1C (0x71c07efb)
CORECLR! WKS::gc_heap::mark_object_simple + 0x1B9 (0x71c1be09)
CORECLR! WKS::GCHeap::Promote + 0xBC (0x71c076cc)
CORECLR! PromoteObject + 0xF3 (0x71bd6f73)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x71bd5a14)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x71bd54d9)
CORECLR! SegmentScanByTypeChain + 0x67 (0x71bd5a90)
CORECLR! TableScanHandles + 0x8D (0x71bd5c6d)
CORECLR! HndScanHandlesForGC + 0x139 (0x71bd3afe)
CORECLR! Ref_TraceNormalRoots + 0xFC (0x71bd8058)
    File: D:\a\_work\1\s\src\coreclr\gc\gc.cpp:4742
    Image: C:\h\w\AC190948\p\corerun.exe
```

Different stacks, but possibly caused by the same issue, since it is in the same test.

This is in a no-op PR to see if tests are passing.

Note that we had a green `runtime-coreclr gcstress-extra` a day before in https://dev.azure.com/dnceng-public/public/_build/results?buildId=629411&view=results , so this may be caused by something recent.

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib

**Comment by amanasifkhalid** [comment]
ping @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
i don't see this one coming in latest run:

![image](https://github.com/dotnet/runtime/assets/12488060/a503aeba-9932-43ab-9c72-94560fae154b)
