### ISSUE TITLE
Stress failure on x86 in JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.dll

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#100694]
https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-62043b0712444dcfad/IL_Conformance.0.1/1/console.efa7b77e.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-62043b0712444dcfad/IL_Conformance.0.1/1/console.efa7b77e.log?helixlogtype=result)

```
08:48:26.967 Running test: JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.dll

Assert failure(PID 2636 [0x00000a4c], Thread: 5260 [0x148c]): Consistency check failed: Crst Level violation: Can't take level 9 lock CrstCodeVersioning because you already holding level 3 lock CrstDynamicMT
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x7229ac1d)
CORECLR! CrstBase::IsSafeToTake + 0x2C3 (0x71df7acf)
CORECLR! CrstBase::Enter + 0x134 (0x71df758e)
CORECLR! CrstBase::AcquireLock + 0xD (0x71d4beb1)
CORECLR! CodeVersionManager::LockHolder::LockHolder + 0x25 (0x71d8e525)
CORECLR! EECodeInfo::GetNativeCodeVersion + 0xBF (0x71e70a80)
CORECLR! EECodeInfo::GetSavedMethodCode + 0x89 (0x71e70eb9)
CORECLR! EECodeManager::EnumGcRefs + 0xAF (0x71e165ef)
CORECLR! GcStackCrawlCallBack + 0x156 (0x72001886)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x71f299d5)
    File: D:\a\_work\1\s\src\coreclr\vm\crst.cpp:765
    Image: C:\h\w\A54D099E\p\corerun.exe
```

This is in a no-op PR to see if tests are passing.

Note that we had a green `runtime-coreclr gcstress0x3-gcstress0xc` a day before in https://dev.azure.com/dnceng-public/public/_build/results?buildId=629410&view=results , so this may be caused by something recent.

**Comment by jakobbotsch** [comment]
Is this a codegen issue? The assert doesn't look like a normal GCStress symptom to me. #82037 was a similar assert which was a VM issue.

**Comment by JulieLeeMSFT** [comment]
CC @VSadov, it seems not CodeGen issue because we don't handle lock. Could you please take a look?

**Comment by JulieLeeMSFT** [comment]
Pining again if you had a chance to look into it, @VSadov.

**Comment by VSadov** [comment]
Sorry, I kind of forgot where we ended on this. 

```
Assert failure(PID 2636 [0x00000a4c], Thread: 5260 [0x148c]): Consistency check failed: Crst Level violation: Can't take level 9 lock CrstCodeVersioning because you already holding level 3 lock CrstDynamicMT
FAILED: false
```

@kouvel - could this be related to tiering? 

Although, I think we disable tiering in GC stress runs.

**Comment by kouvel** [comment]
It could just be that the lock leveling between CrstDynamicMT and CrstCodeVersioning needs adjusting. I haven't seen interactions between these locks before, so maybe there wouldn't be any conflict in changing the leveling.
