### ISSUE TITLE
HttpClient Adding Custom External Protocol

### ISSUE THREAD

**Issue by KFKMan** [dotnet/runtime#100668]
Hi, i want to add my External Low Level Protocol to the Httpclient.
Example; hash check for IO, Aes encryption, custom identifiers....

it's like a decorator pattern. i'm can do that with fake proxy but i'm think it's a bad way for doing that

**Comment by stephentoub** [comment]
The general way to do that is to implement an HttpMessageHandler.

**Comment by stephentoub** [comment]
HttpMessageHandler is itself a decorator. You insert it into the pipeline, it's handed the message, and it then fully handles how that message is processed. That could be changing or completely replacing the message (eg creating a new one with encrypted content) and passing it along to what's next in the pipeline, that could be wrapping the response stream with its own (eg one that decrypts a response), etc. This is, for example, how automatic decompression is implemented: a handler is inserted that inspects response headers and wraps the response stream with one that decompresses.

**Comment by KFKMan** [comment]
My protocol is working after and before the Http Stuffs (socket connection).

**Comment by KFKMan** [comment]
Looks like thats what i want. Thanks for your help.

**Comment by stephentoub** [comment]
> Looks like thats what i want. Thanks for your help.

Great.
