### ISSUE TITLE
System.Speech.Recognition such useless thing

### ISSUE THREAD

**Issue by Mrgaton** [dotnet/runtime#100783]
### Description

I'm trying to use it to make a log of a podcast and it just writes ridiculous things. Can someone update it or something

### Reproduction Steps

Just use the class

### Expected behavior

At least write razonable text

### Actual behavior

 Recognized text: A ver cómo saber si así está observando cover girl consiste
Recognized text: Bares y si éstos no logran violar los desarrolladores y lo absurdo vista dos programa del consiste el cuadro bonos en paraguas los gobi o que entró hábil colusso es
Recognized text: semifinal con los constaba combatir con supuestos ha jugado en el primer y más audaz culturas
Recognized text: como breath you creo que sea yo lo vi espacio para el club acuática fuga de lo que opinas iglesia dos ser por cumplir de basura, uno,

**Comment by Mrgaton** [comment]
![image](https://github.com/dotnet/runtime/assets/68958481/c2be296c-3951-442b-a3a6-bcb25765cdc0)

**Comment by teo-tsirpanis** [comment]
Because `System.Speech` wraps Windows APIs, problems about its accuracy are not actionable in this repository. You should report a problem in the Windows Feedback Hub instead.

**Comment by Mrgaton** [comment]
Ok I Will

**Comment by danmoseley** [comment]
I believe it wraps their legacy API and may not be the newest tech. I think we'd be interested to know here if you find there's another client API that's better.

**Comment by Mrgaton** [comment]
Yes there it is and it's called open ai whisper 😮‍💨
