### ISSUE TITLE
Unable to Attach Visual Studio Debugger to Console App in SDK-style .NET Framework Project

### ISSUE THREAD

**Issue by dzhukovsky** [dotnet/runtime#100764]
### Description

I am experiencing an issue where the Visual Studio debugger does not attach to my console application built with an SDK-style project for the .NET Framework. This issue is compounded by the fact that no output is displayed in the console when the application is started in debug mode, despite the application running as expected (e.g., displaying "Hello, World!") when not in debug mode. This behavior occurs regardless of whether I start the application in debug mode directly from Visual Studio or attempt to attach the debugger to an already running process. As a result, breakpoints are ignored, and debugging the code becomes impossible, with the added complication of missing console output in debug mode.

### Reproduction Steps

1. Open an SDK-style project for the .NET Framework in Visual Studio.
2. Set breakpoints in the code of the console application.
3. Launch the application in debug mode from Visual Studio (or try to attach the debugger to an already running application).
4. Observe that the debugger does not trigger breakpoints, fails to attach to the application process, and no output is displayed in the console.
5. Run the application without debugging (Ctrl+F5) and note that the expected "Hello, World!" output is displayed in the console.

### Expected behavior

The Visual Studio debugger should successfully attach to the console application's process, breakpoints should be hit, and console output should be visible when running the application in debug mode, just as it is when running the application without debugging.

### Actual behavior

The Visual Studio debugger fails to attach to the application process, breakpoints are ignored, and no console output is displayed when the application is run in debug mode. Conversely, running the application without debugging displays the expected console output.

### Configuration

Operating System: Windows 11 24H2 (26085.1)
Visual Studio Version: 17.10.0 Preview 2.0
.NET Framework Version: net48

### Other information

.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
```

Program.cs
```cs
using System;

namespace ConsoleApp3
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
        }
    }
}
```

**Comment by jkotas** [comment]
Could you please report this issue via https://developercommunity.visualstudio.com/? This repo is not the right place to report Visual Studio and .NET Framework specific issues.

**Comment by dzhukovsky** [comment]
> Could you please report this issue via https://developercommunity.visualstudio.com/? This repo is not the right place to report Visual Studio and .NET Framework specific issues.

Thanks, I have created a ticket here:
https://developercommunity.visualstudio.com/t/Unable-to-Attach-Visual-Studio-Debugger/10638069
