### ISSUE TITLE
[libraries-jitstress] Various regex tests time out under jitstress

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#100754]
Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=631397&view=results
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-6cb54af51eea4845b7/System.Text.RegularExpressions.Tests/1/console.e637dad7.log?helixlogtype=result

```
DOTNET_EnableCrashReport=1
DOTNET_TieredCompilation=0
DOTNET_JitStress=1
DOTNET_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
DOTNET_DbgEnableMiniDump=1
...
[Long Running Test] 'System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_AnchoredPattern', Elapsed: 00:28:11
[Long Running Test] 'System.Text.RegularExpressions.Tests.RegexEnumerateMatchesTests.EnumerateMatches_CheckIndex', Elapsed: 00:28:07
[Long Running Test] 'System.Text.RegularExpressions.Tests.RegexUnicodeCharTests.WideLatin', Elapsed: 00:28:07
[Long Running Test] 'System.Text.RegularExpressions.Tests.RegexMultipleMatchTests.Matches_MultipleCapturingGroups', Elapsed: 00:28:06
[Long Running Test] 'System.Text.RegularExpressions.Tests.RegexCountTests.EnumerateMatches_ReturnsExpectedCount', Elapsed: 00:28:05
Killed
['System.Text.RegularExpressions.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by jakobbotsch** [comment]
These tests also sometimes time out even without any stress variables, with regular checked/debug builds of the runtime. Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=637524&view=ms.vss-test-web.build-test-results-tab&runId=15704680&resultId=206394&paneView=debug
Example console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-100428-merge-89d25380d6384201b3/System.Text.RegularExpressions.Tests/1/console.cc7944e2.log?helixlogtype=result

**Comment by steveharter** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
@jakobbotsch, is this still happening? Is there a way to tie this issue with such issues happening such that CI automatically updates it with cases? Do we have a dump that shows what the tests are doing when the timeouts occur? The builds linked above are no longer available.

**Comment by stephentoub** [comment]
@jakobbotsch, is this still happening?

**Comment by jakobbotsch** [comment]
Sorry for missing your earlier ping. I haven't seen this in a while... Let's close it.

**Comment by stephentoub** [comment]
ok, thanks
