### ISSUE TITLE
Guidance on Compiling C++ Static Libraries with NativeAOT and Method Invocation

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#100735]
Hello NativeAOT Team,

I am currently working on a project where I'm leveraging NativeAOT for ahead-of-time compilation of a .NET application. This project requires integration with several static libraries written in C++. I am seeking guidance on how to properly compile these C++ static libraries alongside my NativeAOT project and how to call methods defined within these libraries from my .NET code.

Could you provide any details on the environment setup required to ensure that the C++ libraries are correctly recognized and compiled as part of the NativeAOT build process?

Thank you in advance for your assistance and advice on this matter.

**Comment by jkotas** [comment]
Check https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#direct-pinvoke-calls and https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking

**Comment by MichalStrehovsky** [comment]
Closing as answered.
