### ISSUE TITLE
iOS AllSubsets_Mono queues can take a very long time

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#100752]
These queues can take 3+ hours to run, and then just end up timing out. An example here is one taking 6hrs and then timing out: https://dev.azure.com/dnceng-public/public/_build/results?buildId=633540&view=logs&jobId=7f49df26-8126-5de3-bf2f-6ac6bde01830&j=7f49df26-8126-5de3-bf2f-6ac6bde01830&t=c62b6a8c-bf71-5057-7f45-9c355fe0b802

A quick glance says that this might be waiting in the iOS queue for a runner. If the iOS queue is overloaded we should consider throttling down the amount of PR testing we're doing.

**Comment by steveisok** [comment]
ios/tvos has been whittled down to a few smoke tests on PRs. The only other course of action would be to remove the smoke tests entirely from PR runs.

@vitek-karas - is there any action you would like to take?

**Comment by vitek-karas** [comment]
I'll discuss this with @matouskozak once he's back - I think we should first pull some data around this (why are the queues overloaded).

**Comment by agocke** [comment]
I also used the Helix dashboard, but this was months ago. I agree, this seems resolved now. No idea what changed, but the queue times look good now. I'll close it out.
