### ISSUE TITLE
HttpClient requests only support Tls1.3 Website request failure

### ISSUE THREAD

**Issue by Dylan-Jinx** [dotnet/runtime#100799]
### Description

The HttpClient request only supports Tls1.3 website request failure, indicating that the SSL link fails to be established and that the bad protocol version is displayed internally in windows. Display platform not supported in apple environment

### Reproduction Steps

Create an httpClient. Select any website that supports only tls1.3 to make a get request

### Expected behavior

请求返回成功

### Actual behavior

发生异常, 建立ssl链接失败

### Configuration

dotnet version: .net 8
OS: MacOs 14.4.1(ARM) or windows 11(x64)

**Comment by huoyaoyuan** [comment]
What if you set `HttpClientHandler.SslProtocols` to `Tls13`?

**Comment by Dylan-Jinx** [comment]
@huoyaoyuan  I set this attribute, but it still throw the same exception

my test code:
``` C#

var url = "https://www.23digital.com.au/";

var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
httpClientHandler.SslProtocols = System.Security.Authentication.SslProtocols.Tls11
    | System.Security.Authentication.SslProtocols.Tls12
    | System.Security.Authentication.SslProtocols.Tls13;


var client = new HttpClient(httpClientHandler);
var response = client.GetAsync(url).Result;

Console.ReadKey();
```

**Comment by Dylan-Jinx** [comment]
@huoyaoyuan  I set this attribute, but it still throw the same exception.
```C#
var url = "only support tls 1.3 website url";

var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
httpClientHandler.SslProtocols = System.Security.Authentication.SslProtocols.Tls11
    | System.Security.Authentication.SslProtocols.Tls12
    | System.Security.Authentication.SslProtocols.Tls13;


var client = new HttpClient(httpClientHandler);
var response = client.GetAsync(url).Result;

Console.ReadKey();
```

**Comment by huoyaoyuan** [comment]
How about `Tls13` **only**, instead of `Tls11|Tls12|Tls13`? This can help to decide whether its issue around protocol decision, or TLS1.3 handling.

**Comment by Dylan-Jinx** [comment]
@huoyaoyuan I found that it works under windows11, and I think it has something to do with the operating system.

**Comment by huoyaoyuan** [comment]
TLS1.3 support on macOS is tracked at #1979.
