### ISSUE TITLE
WinDbg doesn't break on first chance managed exceptions with the new EH enabled

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#100701]
WinDbg is unable to break on first chance managed exceptions with the new EH enabled since it hooks to the structured exception handling mechanism which is not in use anymore. We should work with the WinDbg developers on a way to make it work again.

**Comment by jkotas** [comment]
Can we do a dummy RaiseException + catch when the unmanaged debugger is attached?

**Comment by janvorli** [comment]
I think I've tried that and there was some problem with it, but I'll try again to make sure.

**Comment by janvorli** [comment]
Interestingly, it works just fine, I must have been doing something wrong in the past. I'll create a PR with such fix.
