### ISSUE TITLE
Question: Testing with ActivitySource depenedency

### ISSUE THREAD

**Issue by tituszban** [dotnet/runtime#100813]
We have an aspnetcore API, that uses [`ActivitySource`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/ActivitySource.cs) for tracing in a class, where `ActivitySource` is injected via a wrapper class with DI.

We also have tests for said class. What is the recommended approach with `ActivitySource` in tests?

Our thinking on this:

* We usually use Moq for dependencies, however as `ActivitySource` has no interface, this is not an option.
* We have considered injecting an actual instance of `ActivitySource` with no listeners.
* We have considered building our own `IActivitySource` adapter, that re-implements all of `ActivitySource` 

What is the recommended way of testing with an `ActivitySource` dependency? Are there plans for an official `IActivitySource` interface to be used for mocking?

**Comment by teo-tsirpanis** [comment]
> `ActivitySource` is injected via a wrapper class with DI

My understanding is that this is not the recommended way to use `ActivitySource`. You should just store it in a `static readonly` field and use `ActivityListener` if you want to test that certain activities are started.

**Comment by tituszban** [comment]
DI has very little bearing on the actual question. It's just one way of sharing an instance across services.

The question was if to mock `ActivitySource` or use an instance, and what you seem to be saying is to not mock and use an instance (however it may be shared).

Is that the recommended approach? Is that why it doesn't have an interface?

**Comment by tarekgh** [comment]
@tituszban are you expecting to have multiple containers running on the same process same time? You can still register the ActivitySource object to the DI container and use it inside the container. I am asking the question because in your scenario I expect one instance of the ActivitySource will be created and used. right?

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by tituszban** [comment]
> @tituszban are you expecting to have multiple containers running on the same process same time? You can still register the ActivitySource object to the DI container and use it inside the container. I am asking the question because in your scenario I expect one instance of the ActivitySource will be created and used. right?

I can't stress it enough how irrelevant DI is for this question. Yes, in our case we have a singleton class that holds the `ActivitySource` instance. Essentially having the same effect as a static member. Standard DI use, single container creating all instances, consumed by controllers. Nothing too unique or esoteric.

We just want to understand what is the best practice for `ActivitySource` and testing.

**Comment by tarekgh** [comment]
> We just want to understand what is the best practice for ActivitySource and testing.

https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#activitysource.

In short, what @teo-tsirpanis mentioned is correct. You tests can use ActivityListener to listen any activity creations and perform whatever tests you want to validate. Let's know if you still have any question.
