### ISSUE TITLE
[API Proposal]: New AssemblyName-like type for TypeName parsing

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#100867]
## Background and Motivation

While working on the implementation of `TypeName` API (https://github.com/dotnet/runtime/issues/97566), it [turned out](https://github.com/dotnet/runtime/pull/100094#discussion_r1550648715) that it's impossible to set `AssemblyName.CultureName` without allocating a `CultrueInfo` instance (using public NS2.0 compatibile APIs).

https://github.com/dotnet/runtime/blob/07648642d345087d344bc8b7b9b3ea7c8793bbea/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L83

The type name parser needs to support parsing from untrusted input and such non-predefined culture name may be used as a vector of attack, so the existing `AssemblyName` is not suitable for our needs.

Since `AssemblyName` suffers from some other design issues (mutability, a LOT of obsolete properties), I would like to introduce a new, immutable, lightweight version of `AssemblyName` type.

## Proposed API

It's a concept and I need the help of API review board to choose the right name. Some of my ideas: `ReadOnlyAssemblyName`, `AssemblyId`, `LibraryName`.

```csharp
namespace System.Reflection.Metadata;

public sealed class AssemblyNameInfo : IEquatable<AssemblyNameInfo>
{
    public AssemblyNameInfo(string name, Version? version = null, string? cultureName = null, AssemblyNameFlags flags = AssemblyNameFlags.None,
   Collections.Immutable.ImmutableArray<byte> publicKeyOrToken = default);
    public string Name { get; }
    public string FullName { get; }
    public Version? Version { get; }
    public string? CultureName { get; }
    public AssemblyNameFlags Flags { get; }
    public ImmutableArray<byte> PublicKeyOrToken { get; }
    
    public AssemblyName ToAssemblyName();
    
    public static AssemblyNameInfo Parse(ReadOnlySpan<char> assemblyName);
    public static bool TryParse(ReadOnlySpan<char> assemblyName, [NotNullWhenAttribute(true)] out AssemblyNameInfo? result);
}
```

The approved `TypeName` API needs following changes:

```diff
public sealed partial class TypeName : IEquatable<TypeName>
{
-    public string AssemblySimpleName { get; }
-    public System.Reflection.AssemblyName? GetAssemblyName();
+    public AssemblyNameInfo? AssemblyName { get; }
}
```

## Usage Examples

Building high-level, opinionated parser on top of the low-level API:

```csharp
AssemblyName GetAssemblyName(string unsafeInput)
{
    if (!AssemblyNameInfo.TryParse(unsafeInput, out AssemblyNameInfo info))
    {
        throw new ArgumentException("Invalid name!");
    }

    if (info.Name.AsSpan().IndexOfAny(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) >= 0)
    {
        throw new InvalidOperationException("AssemblyName must not contain path characters.");
    }

    // the following line throws CultureNotFoundException for non-predefined cultures
    _ = CultureInfo.GetCultureInfo(info.CultureName, predefinedOnly: true);

    return info.ToAssemblyName();
}
```

## Alternative Designs

The proposed design has one property `PublickKeyOrToken` that can express the public key or its token. It's a design choice inherited from `AssemblyName` that uses `AssemblyNameFlags.PublicKey` flag to express what given byte array is.

We could have two dedicated properties and ctor arguments to express that: `PublicKey` and `PublicKeyToken`.

## Risks

Providing low quality design may require introducing another `AssemblyName`-like type in the future.

**Comment by teo-tsirpanis** [comment]
How about naming it `AssemblyNameInfo`? Similar to `TimeZone` and `TimeZoneInfo`.

**Comment by jkotas** [comment]
>  AssemblyName ToAssemblyName();

Should this have a FromAssemblyName method too?

**Comment by MichalStrehovsky** [comment]
If you're looking for code that could use this, I'd want to switch the managed type system to this AssemblyName:

https://github.com/dotnet/runtime/blob/674ba3fade49e5d617bc3ad3a555558572532593/src/coreclr/tools/Common/TypeSystem/Common/IAssemblyDesc.cs#L11-L18

We're using AssemblyName right now and it's probably the only reason why we cannot turn on culture invariant mode on tools that use the managed type system. AssemblyName is unusable when culture invariant mode is enabled due to the cultureinfo.

**Comment by adamsitnik** [comment]
I've tried to implement the API today and found out following things:

1. If the `ctor` accepts a byte array, then the user may mutate that and in order to create an immutable array, we need to perform a copy. But, if the `ctor` accepts an immutable array, the users can use `ImmutableCollectionsMarshal.AsImmutableArray(array)`, pass the result to the ctor and avoid the extra copy.
2. When `AssemblyName.FullName` is called and a public key is present, a validation is being performed and it may throw `SecurityException`. I believe it's better to validate it in the ctor and throw `ArgumentException` 
https://github.com/dotnet/runtime/blob/7b534da455fa12c7a19b518ddab059dd70af1fa7/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L260-L269
https://github.com/dotnet/runtime/blob/7b534da455fa12c7a19b518ddab059dd70af1fa7/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyNameHelpers.StrongName.cs#L19-L20
3. When `AssemblyName.FullName` is called and a public key **token** is present, a validation of the length is being performed and it may throw `ArgumentException`.  I believe it's better to validate it in the ctor.
https://github.com/dotnet/runtime/blob/7b534da455fa12c7a19b518ddab059dd70af1fa7/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L269
https://github.com/dotnet/runtime/blob/7b534da455fa12c7a19b518ddab059dd70af1fa7/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyNameFormatter.cs#L62-L63
4. When `AssemblyName.GetPublicKeyToken` is called, it may compute the token if public key is present. Since we want to make it immutable this work needs to be performed at ctor. https://github.com/dotnet/runtime/blob/7b534da455fa12c7a19b518ddab059dd70af1fa7/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L215

Please let me know if you believe that my observations are wrong.

**Comment by jkotas** [comment]
This type should not be doing any validation of the PublicKey or PublicKeyToken; or try to compute PublicKeyToken from PublicKey. It should treat the PublicKeyToken/PublicKey as an opaque blob. (BTW: We have been going in this direction for the assembly loader in modern .NET. Strong names and strong name mismatches are ignored by the assembly loader, and the publickey/publickeytoken are just treated as opaque blobs that are passed around for backward compatibility.)

We may want to have just a single property `PublicKeyOrToken` and use `AssemblyNameFlags.PublicKey` to determine whether it is key or token.

The existing behavior of AssemblyName.FullName that converts PublicKey to PublicKeyToken is questionable. It is perfectly fine to have full assembly name with public key. I do not think we want copy this behavior in this type. The full name should match what you have constructed the AssemblyNameInfo with, without any conversions.

**Comment by MichalStrehovsky** [comment]
How would be go about implementing `IEquatable<AssemblyNameInfo>` in the presence of PublicKey/PublicKeyToken? If we have two `AssemblyNameInfo`s for the same assembly, but one using PublicKey and the other using PublicKeyToken, would they not be equal? Or would we ignore public key in equality checks? (And if we ignore it, do we have any concerns when S.R.Metadata is used on desktop, since it still ships as netstandard?)

**Comment by jkotas** [comment]
I would expect that `IEquatable<AssemblyNameInfo>` would look for exact match of all components (the name can be compared as case insensitive).

`IEquatable<AssemblyNameInfo>` would be usable for ref/def binding. As you have pointed out, the .NET universe has number of different implementations of ref/def bindings.

**Comment by bartonjs** [comment]
* An AssemblyNameInfo(AssemblyName) ctor was proposed, but decided it was not needed.
* We talked about adding other properties from AssemblyName that are representable in the textual form, but decided they can be added later.
* We removed the IEquatable-ness from the type and from TypeName.  When we figure out what the semantics should be we can add it back.

```c#
namespace System.Reflection.Metadata;

public sealed class AssemblyNameInfo
{
    public AssemblyNameInfo(string name, Version? version = null, string? cultureName = null, AssemblyNameFlags flags = AssemblyNameFlags.None,
   Collections.Immutable.ImmutableArray<byte> publicKeyOrToken = default);
    public string Name { get; }
    public string FullName { get; }
    public Version? Version { get; }
    public string? CultureName { get; }
    public AssemblyNameFlags Flags { get; }
    public ImmutableArray<byte> PublicKeyOrToken { get; }
    
    public AssemblyName ToAssemblyName();

    public static AssemblyNameInfo Parse(ReadOnlySpan<char> assemblyName);
    public static bool TryParse(ReadOnlySpan<char> assemblyName, [NotNullWhenAttribute(true)] out AssemblyNameInfo? result);
}
```

```diff
-public sealed partial class TypeName : IEquatable<TypeName>
+public sealed partial class TypeName
{
-    public string AssemblySimpleName { get; }
-    public System.Reflection.AssemblyName? GetAssemblyName();
+    public AssemblyNameInfo? AssemblyName { get; }
}
```

**Comment by Neme12** [comment]
I really think `TypeName` should be `TypeNameInfo` to match `AssemblyNameInfo` for consistency if that's what `AssemblyNameInfo` will be called.

**Comment by Neme12** [comment]
Looking at `AssemblyNameInfo`, it seems it's only a bag of properties with a constructor with parameters that match each of the property. Should this be a `record` with `init` properties then? That has the benefit that users will be able to use `with` to get another instance with one property changed.

**Comment by Neme12** [comment]
I really think the types should implement `IParsable<TSelf>` since they already have Parse methods. Why not? They already have the functionality, so it's not any maintenance burden to just add the interface. My view is that a class should always implement standard interfaces corresponding to the methods it already provides, so that it can be used by someone when they're working with the interface. Otherwise it can't be since interfaces aren't duck typed in C#.
