### ISSUE TITLE
Incosistent Indentation of List Patterns in Switch Expressions

### ISSUE THREAD

**Issue by koenigst** [dotnet/runtime#100806]
### Description

I expect all case patterns in a switch expression to have the same indentation. For list patterns I get an IDE0055 warning if I indent them the same amount as other patterns (e.g. default pattern).

### Reproduction Steps

Project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
```

`.editorconfig` in project root:
```.editorconfig
root = true

[*.cs]
dotnet_diagnostic.IDE0055.severity = warning
```

Class:
```csharp
namespace Baz
{
    public static class Foo
    {
        public static int Bar(string[] args)
        {
            return args switch
            {
                [{ } s, ..] => s.Length,
                _ => -1,
            };
        }
    }
}
```

### Expected behavior

No warning because the indentation for all cases is the same.

### Actual behavior

```
.\Foo.cs(9,13,9,17): warning IDE0055: Fix formatting (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055)
```

### Configuration

* .NET SDK: 8.0.202
* OS: Windows 11 Enterprise, 22H2, 22621.3296

**Comment by CyrusNajmabadi** [comment]
I believe this is a roslyn issue (and also fixed). But I cannot seem to move the bug there currently (sometimes GitHub just does not let me move...)

**Comment by koenigst** [comment]
@CyrusNajmabadi Thanks for the hint. I think this is the issue you hinted at: dotnet/roslyn#72196
