### ISSUE TITLE
String.IndexOf has incorrectly behavier in Thai(Thaiand) region

### ISSUE THREAD

**Issue by hmisaki** [dotnet/runtime#100803]
### Description

for the C# code:
```
const string str= "Hello";
str.IndexOf(" ")
```
he str.IndexOf(" ") returns the wrong result "0" when I switch the region to Thai(Thailand). Some other special char for example: "@" has the same issue.

### Reproduction Steps

Create a new .net 8 project and write down the next codes:
```
const string str = "Hello";
Console.WriteLine($"{str.IndexOf(" ")}");
Console.WriteLine($"{str.IndexOf(" ", StringComparison.CurrentCulture)}");
Console.WriteLine($"{str.IndexOf(" ", StringComparison.InvariantCultureIgnoreCase)}");
Console.WriteLine($"{str.IndexOf(" ", StringComparison.Ordinal)}");
```
run the codes in English(US) region, then switch to Thai(Thailand), run again

### Expected behavior

We want to get four "-1".
-1
-1
-1
-1

### Actual behavior

The result is :
0
0
-1
-1

### Regression?

Yes, it works well in .net framework4.7.

### Known Workarounds

Use `str.IndexOf(" ", StringComparison.InvariantCultureIgnoreCase)`.

**Comment by huoyaoyuan** [comment]
Related to #87939 and #100381

**Comment by hamarb123** [comment]
string IndexOf is culture-dependent, you should specify a `StringComparison`.
You might want `StringComparison.Ordinal` / `StringComparison.OrdinalIgnoreCase` btw, since the invariant ones still do a culture-based comparison as opposed to a binary one.

**Comment by panxn** [comment]
One more sample:
```
var s = "a:b";
var t = ":";
Console.WriteLine(s.Length);            // it prints 3
Console.WriteLine(s.LastIndexOf(t));    // it also prints 3
```

I have read [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) and [Behavior changes when comparing strings on .NET 5+](https://learn.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus#ordinal-vs-linguistic-search-and-comparison). I realized `StringComparison.Ordinal` should be used here. But it's really strange that `String.LastIndexOf` returns `String.Length`, I think possible value for `String.LastIndexOf` should be `[0, String.Length-1] or -1`

**Comment by tarekgh** [comment]
@hmisaki please have a look at https://github.com/dotnet/runtime/issues/87939 and https://github.com/dotnet/runtime/issues/100381 for more info. Thanks @huoyaoyuan for linking these issues. 

> But it's really strange that String.LastIndexOf returns String.Length, I thought possible value for String.LastIndexOf should be [0, String.Length-1] or -1

I agree it can be confusing when seeing it for the first time :-) but this is the behavior that existed since day one and will be a breaking change if we change that. There are other arguments too if we return to other values (like `Length -1`) which still will not make sense too in some scenarios. 

I am closing the issue but feel free to send any questions if you still have any.
