### ISSUE TITLE
Is there any other way to generate native dlls without publishing?

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#100865]
### Description

Is there any other way to generate native dlls without publishing?
有没有其他方法在不发布的情况下生成native dll?

In ExplorerExtension. Sample warehouse in the Sample, we can by native IExplorerCommand interface, and add UnmanagedCallersOnlyAttribute, enable the AOT is released, can generate a native DLL, This dll enables custom Windows 11 right-click menus by changing the application manifest and packaging it as MSIX. However, publishing is required to generate a native dll. How do I generate a native dll without publishing and copy it to the wapproj appx directory?
在ExplorerExtension.Sample仓库示例中，我们可以通过原生实现IExplorerCommand接口，并添加UnmanagedCallersOnlyAttribute，启用AOT发布后，可以生成一个原生的dll，这个dll通过更改应用程序清单，并将其打包为 MSIX，可以实现自定义 Windows 11 的右键菜单。然而，生成原生的dll需要进行发布，请问如何在不发布的情况下生成原生的dll，并拷贝到wapproj的appx目录下？

Repository link:https://github.com/cnbluefire/ExplorerExtensions.Sample

### Reproduction Steps

See description

### Expected behavior

Generate a native dll without releasing the msix installation package

### Actual behavior

Managed DLLS are generated without the msix installation package being released, and managed dll cannot be called normally

### Regression?

No.It works in .NET 8+,because .NET 8+ supports com source generate.

### Known Workarounds

None

### Configuration

.NET 8+
Windows 11 22621.0
X64

### Other information

No other information

**Comment by agocke** [comment]
The only supported way to run AOT is through `publish`. It sounds like you may need to write custom MSBuild targets to call publish for you in a different place in your build.

There's no customization available in the AOT compiler for custom builds, only in MSBuild.
