### ISSUE TITLE
Mono Wasm V8 System.Text.Encodings.Web.Tests failure

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#100830]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=635026
Build error leg or test failing: normal-System.Text.Encodings.Web.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/100618

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[MONO] /__w/1/s/src/mono/mono/mini/interp/interp.c:3737 <disabled>",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=635026
**Error message validated:** `[[MONO] /__w/1/s/src/mono/mono/mini/interp/interp.c:3737 <disabled>`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/9/2024 5:52:52 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[637249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637249)|dotnet/runtime|[WasmTestOnBrowser-Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637249&view=ms.vss-test-web.build-test-results-tab&runId=15693710&resultId=183170)|dotnet/runtime#100849|
|[636875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636875)|dotnet/runtime|[WasmTestOnBrowser-Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636875&view=ms.vss-test-web.build-test-results-tab&runId=15683534&resultId=173887)|dotnet/runtime#99829|
|[636835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636835)|dotnet/runtime|[normal-System.Text.Encodings.Web.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636835&view=ms.vss-test-web.build-test-results-tab&runId=15683236&resultId=172881)||
|[636681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636681)|dotnet/runtime|[WasmTestOnBrowser-Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636681&view=ms.vss-test-web.build-test-results-tab&runId=15678324&resultId=181587)|dotnet/runtime#100048|
|[636351](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636351)|dotnet/runtime|[normal-System.Text.Encodings.Web.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636351&view=ms.vss-test-web.build-test-results-tab&runId=15669002&resultId=172878)|dotnet/runtime#100784|
|[636336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636336)|dotnet/runtime|[WasmTestOnBrowser-Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636336&view=ms.vss-test-web.build-test-results-tab&runId=15667446&resultId=181892)|dotnet/runtime#100610|
|[636188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636188)|dotnet/runtime|[WasmTestOnBrowser-Microsoft.Extensions.Http.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636188&view=ms.vss-test-web.build-test-results-tab&runId=15663424&resultId=183335)|dotnet/runtime#100812|
|[635124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635124)|dotnet/runtime|[normal-System.Text.Encodings.Web.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635124&view=ms.vss-test-web.build-test-results-tab&runId=15627652&resultId=172876)|dotnet/runtime#100782|
|[635016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635016)|dotnet/runtime|[WasmTestOnBrowser-System.Text.Encodings.Web.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635016&view=ms.vss-test-web.build-test-results-tab&runId=15622948&resultId=188148)|dotnet/runtime#98812|
|[635026](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635026)|dotnet/runtime|[normal-System.Text.Encodings.Web.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635026&view=ms.vss-test-web.build-test-results-tab&runId=15623056&resultId=182657)|dotnet/runtime#100618|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|10|

**Comment by pavelsavara** [comment]
Some of these are NOT multi-threading, they are V8. Perhaps it's related to https://github.com/dotnet/runtime/issues/100831

cc @BrzVlad

**Comment by BrzVlad** [comment]
Seems to have been fixed by https://github.com/dotnet/runtime/pull/100907
