### ISSUE TITLE
System.Text Exception cannot be caught in NativeAOT when Reflection is disabled, but is solved with a Console.WriteLine()

### ISSUE THREAD

**Issue by klimatr26** [dotnet/runtime#100888]
### Description

I was trying to integrate SharpCompress into my NativeAOT project with Reflection disabled. I had been able to do this in smaller projects that used similar functions, and I was also able to add ZstdSharp without any issue (to other projects where I had also disabled Reflection).

However, on my latest project, I wanted to do the same with a dedicated class, with a method called asynchronously. The program worked in as normal NativeAOT, but it started crashing when I disabled Reflection (which I was able to do in other projects using SharpCompress). This is mentioned in adamhathcock/sharpcompress#826.

I tried to reproduce the issue in the **Reproduction Steps** code. If you compile that code and pass it a file as argument, it will throw the following Exception, which is not caught in any of the try-catch blocks:

```
Unhandled Exception: MT140696613154920: TypeInitialization_Type_NoTypeAvailable
 ---> MT140696613152000: Reflection_Disabled
   at Internal.Reflection.RuntimeTypeInfo.get_Assembly() + 0x6f
   at System.Text.BaseCodePageEncoding.GetEncodingDataStream(String) + 0x1d
   at System.Text.BaseCodePageEncoding..cctor() + 0x5d
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
   Exception_EndOfInnerExceptionStack
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb0
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0xd
   at System.Text.BaseCodePageEncoding.GetCodePageByteSize(Int32) + 0x11f
   at System.Text.CodePagesEncodingProvider.GetEncoding(Int32) + 0xb1
   at System.Text.CodePagesEncodingProvider.GetEncoding(Int32) + 0x56
   at System.Text.EncodingProvider.GetEncodingFromProvider(Int32) + 0x3d
   at System.Text.Encoding.GetEncoding(Int32) + 0x11
   at System.Text.EncodingHelper.GetSupportedConsoleEncoding(Int32) + 0xf
   at System.Console.get_OutputEncoding() + 0x6c
   at System.ConsolePal.OpenStandardOutput() + 0x9
   at System.Console.<get_Out>g__EnsureInitialized|26_0() + 0x37
   at System.Console.WriteLine(String) + 0xd
   at AsyncList.Program.Main(String[]) + 0x109
   at AsyncList!<BaseAddress>+0x15dab0
```

What is really weird is that if I uncomment the line `//Console.WriteLine("Try to create Reader");`, it prints "Try to create Reader" and then works normally (correctly lists the contents of the file), even with Reflection disabled.

I thought this was an issue with SharpCompress, but that project is already NativeAOT-friendly. Also, the fact that uncommenting that line and printing something before everything else solves the issue, makes me believe the issue is somewhere else.

### Reproduction Steps

You can use this code:

```
using SharpCompress.Archives.Zip;

namespace AsyncList
{
    internal class Program
    {
        //static async Task Main(string[] args)
        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Provide a file to list its contents.");
            }
            else
            {
                try
                {
                    //Console.WriteLine("Try to create Reader");
                    var reader = new Reader(args[0]);
                    //string result = await reader.Read();
                    //string result = await Task.Run(() => reader.Read());
                    //Console.WriteLine("Try to read contents");
                    string result = reader.Read();
                    if (result.Length != 0)
                    {
                        Console.WriteLine(result);
                        Environment.Exit(1);
                    }
                    //var files = await Task.Run(() => reader.List());
                    //Console.WriteLine("Try to create list of contents");
                    string[] files = reader.List();
                    //Console.WriteLine("Try to list contents to console");
                    foreach (var file in files)
                    {
                        Console.WriteLine(file);
                    }
                }
                catch (Exception ex) //Still throws an Unhandled Exception
                {
                    Console.WriteLine(ex.ToString());
                }
            }
        }
    }

    internal class Reader(string filePath)
    {
        public string FilePath { get; } = filePath;

        //public string Read(CancellationToken? cancellationToken = null, IProgress<string>? fileNameProgress = null, IProgress<int>? progress = null)
        public string Read()
        {
            string result = string.Empty;
            try
            {
                using var archive = ZipArchive.Open(FilePath);
            }
            catch (Exception e)
            {
                result = e.Message;
            }
            return result;
        }

        public string[] List()
        {
            string[] result = Array.Empty<string>();
            try
            {
                using (var archive = ZipArchive.Open(FilePath))
                {
                    int noOfEntries = archive.Entries.Count;
                    result = new string[noOfEntries];
                    var i = 0;
                    foreach (var entry in archive.Entries)
                    {
                        result[i] = entry.Key;
                        i++;
                    }
                }
            }
            catch { }
            return result;
        }
    }
}
```

With this csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcDisableReflection>true</IlcDisableReflection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.36.0" />
  </ItemGroup>

</Project>
```

If you remove the `//` from `//Console.WriteLine("Try to create Reader");`, the problem will go away.
I tested this as Async first, but the problem persisted when I removed everything that worked asynchronously.

### Expected behavior

The program should list the contents of a ZIP file. If an Exception is thrown while doing this, it should be caught.

### Actual behavior

The program can't list the contents of a ZIP file, unless a `Console.WriteLine()` is added. An Unhandled Exception is thrown and cannot be caught.

### Known Workarounds

Add a `Console.WriteLine();`.

### Configuration

.NET 8.0.4 and older versions too
Windows 10 (x64)

**Comment by MichalStrehovsky** [comment]
`IlcReflectionDisabled` is unsupported. `BaseCodePageEncoding.GetEncodingDataStream` will not work in reflection disabled mode because it uses reflection:

https://github.com/dotnet/runtime/blob/d88c7ba88627b4b68ad523ba27cb354809eb7e67/src/libraries/System.Text.Encoding.CodePages/src/System/Text/BaseCodePageEncoding.cs#L232-L235

> What is really weird is that if I uncomment the line //Console.WriteLine("Try to create Reader");, it prints "Try to create Reader" and then works normally (correctly lists the contents of the file), even with Reflection disabled.

My guess is that something in SharpCompress switches the console encoding to a different encoding and when Console tries to initialize, it hits code paths that don't work with reflection disabled.

But since this is unuspported, I'm going to close this.

**Comment by klimatr26** [comment]
Thank you.
