### ISSUE TITLE
Using WinTrustVerify without certificates installed

### ISSUE THREAD

**Issue by tapika** [dotnet/runtime#100864]
We want our application to validate custom code signing certificates from an internal PKI.
 
We're attempting to use `WinTrustVerify` API for this. However, it seems that `WinVerifyTrust` relies on having the root certificate in the system store. Our IT has advised us against installing our custom root certificate to end-users machine. We've also failed to find a way to configure trust anchors used by `WinVerifyTrust` from inside the application. Without the knowledge of the root certificate, for a valid signature `WinTrustVerify` returns an error code `CERT_E_CHAINING` ("A certificate chain could not be built to a trusted root authority"). Given an invalid signature, it returns `CRYPT_E_FILE_ERROR` or `TRUST_E_BAD_DIGEST`, so we're able to use these error codes to get the information about signature validity.
 
For signer certificate validity, we're currently extracting and iterating through the certificates inside `SignerInfo` using `wincrypt.h` API. Since the root certificate is not part of the signature, we're able to verify that our intermediate certificate is present in that chain.
 
We're wondering, is it reasonable to rely on `CERT_E_CHAINING` error code and `SignerInfo` parsing? Essentially, we're making the intermediate certificate into a trust anchor.

**Comment by Clockwork-Muse** [comment]
> We want our application to validate custom code signing certificates from an internal PKI.
>
> Our IT has advised us against installing our custom root certificate to end-users machine.

Define "end user".  One of the following should be true:
 - The end user is people outside of your organization.  You should be using a public root (not internal), and just let Windows perform its built-in validation.
 - The end user is people inside your organization, on machines joined to your domain.  You can use a public root (which you may need anyways if you also distribute applications outside your organization), but it's completely acceptable and expected to push an internal root to these machines.

**Comment by bartonjs** [comment]
WinVerifyTrust isn't part of the .NET platform, so we can't really give opinions on it.

At a "general advice" level, I agree with @Clockwork-Muse.  If you're doing codesign and sharing the signed things outside of your organization, you should be using a publicly trusted CA.  If you're doing a thing sort of like codesign but is different, then you probably shouldn't be bothering with WinVerifyTrust.  With the lower-level chain building APIs you can specify a custom root trust list, and impose your own policy.
