### ISSUE TITLE
[API Proposal]: Add Utf8JsonReader.ValueTextEquals(ReadOnlySpan<byte> utf8Text, bool propertyNameCaseInsensitive) Overload

### ISSUE THREAD

**Issue by MatthewBroatch** [dotnet/runtime#100856]
### Background and motivation

When writing a custom `JsonConverter` you get passed `JsonSerializerOptions` and this may have `PropertyNameCaseInsensitive` set to true. But there is no simple way to check property names case insensitively in `Utf8JsonReader`

### API Proposal

```csharp
namespace System.Text.Json
{
    public ref struct Utf8JsonReader
    {
        public bool ValueTextEquals(ReadOnlySpan<byte> utf8Text, bool propertyNameCaseInsensitive);
    }
}
```

### API Usage

```csharp
public class UserConverter : JsonConverter<User>
{
  public override User Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
  {
    if (reader.TokenType != JsonTokenType.StartObject)
      throw new JsonException();

    User user = new User();
    while (reader.TokenType != JsonTokenType.EndObject)
    {
      reader.Read();
      if (reader.TokenType == JsonTokenType.PropertyName)
      {
        if (reader.ValueTextEquals(PropertyNameValue, propertyNameCaseInsensitive: true))
        {
          reader.Read();
          user.Value = reader.GetString();
        }
        ...
      }
    }
    return user;
  }
}
```

### Alternative Designs

Perhaps a more generic approach would be to allow non default equality comparers
```
public bool ValueTextEquals(ReadOnlySpan<byte> utf8Text, IEqualityComparer<byte>);
```

**Comment by eiriktsarpalis** [comment]
Case-insensitive property binding is a feature implemented on the serialization layer and not `Utf8JsonReader`. I think it would be inappropriate to push this down to reader APIs. The way `PropertyNameCaseInsensitive` is currently implemented is converting the property name to a string and comparing it with other values using `StringComparer.OrdinalIgnoreCase`.In the future, it should be possible to achieve span-based lookups without converting to a string using the APIs as approved in https://github.com/dotnet/runtime/issues/27229
