### ISSUE TITLE
CA1820 is not being triggered when the "is" operator is used for the comparison

### ISSUE THREAD

**Issue by rampaa** [dotnet/runtime#100834]
A comparison like `fooStr == ""` triggers `CA1820` but `fooStr is ""` does not trigger it, but it probably should.

**Comment by poizan42** [comment]
CA1820 is probably going to be completely removed anyways as it no longer serves a purpose, see https://github.com/dotnet/runtime/pull/63734 and the issue about removing the diagnostic at https://github.com/dotnet/runtime/issues/99219
