### ISSUE TITLE
Iterating over a ROS<byte> generates a bunch of NOPs in Release

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/runtime#100875]
### Description

I had some real code that was iterating through a ReadOnlySpan<byte>, I noticed in SharpLab that the asm output contains a bunch of `nop` for no reason I can see.

```csharp
static int Write(ReadOnlySpan<byte> span)
{
    var finalValue = 0;
    for (var position = 0; position + 1 <= span.Length; position += 1)
    {
        var pair = span[position..(position + 1)];
        finalValue += 1;
    }
    return finalValue;
}
```

<details>

<summary>Output</summary>

```asm
Program.<<Main>$>g__Write|0_0(System.ReadOnlySpan`1<Byte>)
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: push edi
    L0004: push esi
    L0005: mov eax, [ebp+0xc]
    L0008: xor edx, edx
    L000a: xor ecx, ecx
    L000c: cmp eax, 1
    L000f: jl short L0037
    L0011: nop
    L0012: nop
    L0013: nop
    L0014: nop
    L0015: nop
    L0016: nop
    L0017: nop
    L0018: nop
    L0019: nop
    L001a: nop
    L001b: nop
    L001c: nop
    L001d: nop
    L001e: nop
    L001f: nop
    L0020: lea esi, [ecx+1]
    L0023: cmp ecx, eax
    L0025: ja short L003f
    L0027: mov edi, eax
    L0029: sub edi, ecx
    L002b: je short L003f
    L002d: inc edx
    L002e: mov ecx, esi
    L0030: lea esi, [ecx+1]
    L0033: cmp esi, eax
    L0035: jle short L0020
    L0037: mov eax, edx
    L0039: pop esi
    L003a: pop edi
    L003b: pop ebp
    L003c: ret 8
    L003f: call dword ptr [0xbce5a40]
    L0045: int3
```

</details>

Either
* Changing the for loop to use `<` rather than `<=`
* Changing the code when indexing into the span to be `span[position..position]` (this changes the behaviour of the code, but it does demonstrate the issue).
* Indexing into the span directly, rather than using the range to slice

Removes the nops.

For my real use case, I need to both slice the span using that range, and increment the position, although its not the end of the world as its not a performance critical piece of code.

SharpLab with the reproduction:
https://sharplab.io/#v2:C4LghgzgtgPgAgJgAwFgBQiCM710wTgAoB1AJwEtgBTQgbUwBoACBZgZgF0BKLgbhzS5MANibkAdsCZlKNAEpUwAEwDy4gDYBPAMoAHMOIA8AI03UAfEwj7xXdAG90TZ0wBuYUkwBmEsOoBqfgCuVEwAvExI/Ggu3gD2noTunrpxEJTkceLhkbxMqenAmdkA1EyYTIYR1gYAdAAyVOIA5sAAFnkFGVlMJRGYdjEujkOxzsn5YOSe1Ta0XUVZtbWEC8W95Vwc0WMuPuJ+geohvf07LgC+Ti5wAOzevgHBVNFXghgiYpLSFNQIhAplGotHoDCYzFRLDVbA5ruMPA8Dk9jqEIlE4fFEhM1j00Z00t1SuVKrM6o0Wu18YV1n1NhiRrt4SkpjMrHMceJlhzthjYvtDs9TuVzs43rE7oiBSjXgI8KIJFIZNQ2ADFKoNDobOCLGyDIMGS4JvzkSc8RivAkmEkERyclF8gTFtlDLrOeTWh0HdSerSBvTeYabSyctD5o7istVuGfZseaMxsajidfSKmGKbvdE88Ze85V9Fb8qAAWVVAjWgoymHXQ/UYo2PJOo3Lmy3WlLR7J4r2EjYVKquhpND1Unu+waxA27bHB0niMPeomYOOMyUm0IpjHp5wSrPS9BvIA=

**Comment by En3Tho** [comment]
Please note that to get x64 codegen you have to explicitly pick x65 platform on sharplab. It still defaults to x86 for some reason and on x64 (and most people are actually interested in x64) codegen is different. There are few nops but I suspect they might be there for alignment reasons

**Comment by JakeYallop** [comment]
Selecting x64 removes the nops completely.

I had no idea SharpLab defaulted to x86, TIL. 

Thanks for the pointer!
