### ISSUE TITLE
JsonStringEnumConverter always returns a default value

### ISSUE THREAD

**Issue by Karatakos** [dotnet/runtime#100852]
### Description

When deserialising JSON containing a string that needs to be converted to an enum via JsonStringEnumConverter, the converter always deserialises with the first value of the enum.

### Reproduction Steps

```
    [Test]
    public void JsonEnumStringConverterTest() {
        const string json = 
        """
        { 
            "foo": 0,
            "bar": "secondvalue"
        }
        """;

        var opts = new JsonSerializerOptions();

        opts.Converters.Add(new JsonStringEnumConverter());

        var value = JsonSerializer.Deserialize<SomeType>(json, opts);

        value.Bar.Should().Be(Enum.Parse<SomeTypeEnum>("secondvalue", ignoreCase: true));
    }

    public record SomeType(int Foo, SomeTypeEnum Bar);

    public enum SomeTypeEnum {
        FirstValue,
        SecondValue
    }
```

### Expected behavior

`Bar` should be `SecondValue`

### Actual behavior

`Bar` is `FirstValue`

### Configuration

8.0.201
MacOS 14.2.1 (23C71)

**Comment by gregsdennis** [comment]
Related: #74385

**Comment by gregsdennis** [comment]
Why does your assertion use `Enum.Parse()` instead of just `SomeEnumType.SecondValue` directly?

I don't expect it should change the outcome, but it's probably better to eliminate the chance that it does.

**Comment by Karatakos** [comment]
> Why does your assertion use `Enum.Parse()` instead of just `SomeEnumType.SecondValue` directly?
> 
> I don't expect it should change the outcome, but it's probably better to eliminate the chance that it does.

Thanks for the quick response. It's only there to show the string can be correctly parsed. Changing it to `SomeTypeEnum.SecondValue` will produce the same outcome.

**Comment by elgonzo** [comment]
Your problem is not with JsonStringEnumConverter, nor with enums. Set the "foo" parameter to any integer value to anything other than zero, and you might notices that deserializing "foo" also doesn't seem to work.

The reason is that by default, STJ treats property names in a **case-sensitive** manner. To enable case-insensitive property handling, set `JsonSerializerOptions.PropertyNameCaseInsensitive` to true, and Bob should be your uncle...
