### ISSUE TITLE
mono/mini/interp/interp.c crash in System.Text.Encodings.Web.Tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#100850]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=637078
Build error leg or test failing: WasmTestOnBrowser-System.Text.Encodings.Web.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/100844

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Text.Encodings.Web.Tests", "src/mono/mono/mini/interp/interp.c", "mono_interp_exec_method"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=637078
**Error message validated:** `[System.Text.Encodings.Web.Tests src/mono/mono/mini/interp/interp.c mono_interp_exec_method`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/10/2024 5:03:12 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by vitek-karas** [comment]
@BrzVlad - could you please take a look?

**Comment by pavelsavara** [comment]
Possibly related [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100520-merge-d5edc2172337452a9b/normal-System.Text.Encodings.Web.Tests/1/console.e00d6b8a.log?helixlogtype=result) on WASM V8/ST
