### ISSUE TITLE
 Issue with Options having an array property that is added twice

### ISSUE THREAD

**Issue by benoit-maurice** [dotnet/runtime#100948]
### Description

When registering an option n times, if this option has an array property, it will be populated n time by concatenation. For instance,
the following settings 

```json
{
  "Config": {
    "List": ["1", "2", "3"]
  }
}
```

will lead to an option with List `["1","2","3","1","2","3"]` if the bound option is added twice.

### Reproduction Steps

https://github.com/benoit-maurice/Bug-OptionsTable

### Expected behavior

This behaviour does not seem to be intuitive and I couldn't find any documentation explaining this.
I would have expected List property to be overwritten instead of being concatenated. 

Following the above example, I would have expected the List property only to contain  `["1","2","3"]` 

### Actual behavior

Given an aspnet core 8.0 api
And the following option class : 

```csharp 
public class ConfigOptions
{
    public const string SectionName = "Config";
    
    public string[] List { get; init; }
}
```

and the folowing appsettings.json : 

```json
{
  // ... some irrelevant config
  "Config": {
    "List": ["1", "2", "3"]
  }
  // ... some irrelevant config
}
```

and I register the option twice : 

```csharp
builder.Services.AddOptions<ConfigOptions>().Bind(builder.Configuration.GetSection(ConfigOptions.SectionName));
builder.Services.AddOptions<ConfigOptions>().Bind(builder.Configuration.GetSection(ConfigOptions.SectionName));
```

When I inject `IOptions<ConfigOptions>` in a service

Then the List property will contain "1","2","3" twice, that is : `["1","2","3","1","2","3"]` 

    Note: If I register the option a third time then the options List will contains "1","2","3" three times

### Known Workarounds

For now, keeping only one AddOptions does the job, but we add an issue in our api because the two AddOptions were not side by side and it took us a moment before understanding that it was related to the two registrations. 

### Configuration

dotnet version : 8.0.104
OS : windows 11 & linux on Azure
Architecture : x64

**Comment by luca-cond** [comment]
Hi, I can confirm that this is also happening with the generic host in a .net 8 console application:

```json
{
  "MySection": {
    "MyList": [ "1", "2", "3" ]
  }
}
```

```csharp
await Host.CreateDefaultBuilder(args)
    .ConfigureServices((builder, services) =>
    {
        services.Configure<MyOptions>(builder.Configuration.GetSection("MySection"));
        services.Configure<MyOptions>(builder.Configuration.GetSection("MySection"));

        services.AddHostedService<SampleHostedService>();
    })
    .Build()
    .RunAsync();

public class MyOptions
{
    public HashSet<string>? MyList { get; set; }
}

internal class SampleHostedService : IHostedService
{
    private readonly IOptionsMonitor<MyOptions> optAccessor;

    public SampleHostedService(IOptionsMonitor<MyOptions> optAccessor)
    {
        this.optAccessor = optAccessor;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        foreach (var val in this.optAccessor.CurrentValue.MyList)
        {
            Console.WriteLine(val);
        }

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

Output:

![image](https://github.com/dotnet/runtime/assets/82594930/6d1bc485-60d3-4051-9ddd-32ffc9c8c1ce)


Using .net 6 for the exact same application is not causing any duplication.

Was there a change in the binding behavior somewhere in .net 7 or 8?

Thanks.

**Comment by luca-cond** [comment]
Hi,
> Adding the elements for each source is the most intuitive behavior for collection properties.

Maybe I'm missing something here, but isn't it the config source always the same here? In my sample console app that array is defined once in `appsettings.json`.

Also, from my point of view at least, the most important thing here is that the behavior has changed from .net 6. It's not necessarily a problem if it's been communicated/documented, but I couldn't find anything so far.

I was just looking (very very quickly) at this code here:
https://github.com/dotnet/runtime/blob/3b8b000a0e115700b18265d8ec8c6307056dc94d/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L322

and I was wondering whether that's the part that has been updated related to this observed behavior.

**Comment by julealgon** [comment]
> Hi,
> 
> > Adding the elements for each source is the most intuitive behavior for collection properties.
> 
> Maybe I'm missing something here, but isn't it the config source always the same here? In my sample console app that array is defined once in `appsettings.json`.

Sorry, I meant to say "sources" as in "actions against the `IOptions` pipeline". Each time you add a `Configure` call, you are adding a func to a initialization pipeline for that `IOptions<T>`, so it makes sense to me that if you "Bind twice", you are adding the same step one after the other as if they were 2 sequential `.Configure` calls.

> Also, from my point of view at least, the most important thing here is that the behavior has changed from .net 6. It's not necessarily a problem if it's been communicated/documented, but I couldn't find anything so far.
> 
> I was just looking (very very quickly) at this code here:
> 
> https://github.com/dotnet/runtime/blob/3b8b000a0e115700b18265d8ec8c6307056dc94d/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L322
> 
> and I was wondering whether that's the part that has been updated related to this observed behavior.

Fair. Agreed it is strange for this to have changed without proper documentation. Hopefully it is mentioned somewhere and someone here will clarify.

**Comment by luca-cond** [comment]
Found this one which probably applies also to other types like `List`, etc.:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/7.0/config-bind-dictionary

**Comment by benoit-maurice** [comment]
Hello all, 
Thanks for the help.

**Comment by benoit-maurice** [comment]
I know this issue is closed, but I hope you get a chance to see this message.

I understand that the behavior is intentional, and I'm not questioning that decision.

However, there are a few aspects of this feature that I'm struggling to grasp. I might have missed something with the Options. I comprehend the technical workings of the `IOptions` pipeline.

My perspective is that an Option serves as a projection of an underlying configuration, similar to how a View is a projection of one or more Tables in a database. What I don't understand is why projecting the configuration multiple times would result in data duplication.

I'm trying to identify a use case where this behavior is relevant, but I haven't found one. Is this a technical limitation of the `IOptions` pipeline, or am I missing something?

P.S. :
> Also consider using the BindConfiguration method instead which automatically handles the IConfiguration for you:

Thanks for this cool tip, I've always wondered if this method existed.

**Comment by julealgon** [comment]
> However, there are a few aspects of this feature that I'm struggling to grasp. I might have missed something with the Options. I comprehend the technical workings of the `IOptions` pipeline.
> 
> My perspective is that an Option serves as a projection of an underlying configuration, similar to how a View is a projection of one or more Tables in a database. What I don't understand is why projecting the configuration multiple times would result in data duplication.
> 
> I'm trying to identify a use case where this behavior is relevant, but I haven't found one. Is this a technical limitation of the `IOptions` pipeline, or am I missing something?

I suspect that the `Bind` calls just add an extra mutation step in the standard options pipeline, just as when you call `Configure` and pass a mutation lambda. It is likely that binding to the same section multiple times is just allowed by default and there are no specific checks or blocks to prevent you from binding to the same section again.

I could also see a situation where you might want to bind the same options to _multiple_ sections one after the other to accumulate the results. I've never needed to do that, but I could see it being useful depending on one's settings.

You could even do something like have a section with defaults, and another section with specific overrides, and then bind first to the default section and then to the override one. It's not a _common_ case by any stretch of the imagination but it would "make some sense" to do it. Particularly when named options are involved (imagine a case with a "default" section, and a section for each of the named variants that is bound after the defaults).

I believe attempting to actively "protect" the caller from binding to the same section would be _possible_, but convoluted, error prone, and unnecessarily limiting.

> P.S. :
> 
> > Also consider using the BindConfiguration method instead which automatically handles the IConfiguration for you:
> 
> Thanks for this cool tip, I've always wondered if this method existed.

Sure. It's a bit of an obscure one because it lives in a separate package, but I always try to use it as it makes the code just that bit simpler.

**Comment by benoit-maurice** [comment]
Okay, I was clearly missing those scenarios. They might be far-fetched but I can totally understand that, from the framework's perspective, it is important to take them into account.

With that in mind, I get why this is relevant.  

Thank you very much for taking the time to answer me.
