### ISSUE TITLE
NativeAOT. Starting Winforms using the DllMain entry point

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#100930]
I'm trying to compile and run a regular form using DllMain. But after injection into any process, the form does not appear, although there are no errors either. With a similar approach using an exe compiled with NativeAOT, the form appears successfully.

![image](https://github.com/dotnet/runtime/assets/111659964/c4c45903-f830-4ad0-9ed3-45eb867016d0)

**Comment by jkotas** [comment]
It is not possible to implement DllMain in managed code like your code fragment shows.

You have asked about this before: https://github.com/dotnet/runtime/issues/96345#issuecomment-1871262288

**Comment by dadavadd** [comment]
> It is not possible to implement DllMain in managed code like your code fragment shows.
> 
> You have asked about this before: [#96345 (comment)](https://github.com/dotnet/runtime/issues/96345#issuecomment-1871262288)

Sorry

**Comment by dadavadd** [comment]
> It is not possible to implement DllMain in managed code like your code fragment shows.
> 
> You have asked about this before: [#96345 (comment)](https://github.com/dotnet/runtime/issues/96345#issuecomment-1871262288)

Will it ever be possible to use DllMain in a dll using NativeA without crashing?

**Comment by dadavadd** [comment]
> It is not possible to implement DllMain in managed code like your code fragment shows.
> 
> You have asked about this before: [#96345 (comment)](https://github.com/dotnet/runtime/issues/96345#issuecomment-1871262288)

And one more question. Can I work around this error using these steps?:

First, I will get a pointer to the Main method and simply call it using delegate* unmanaged in my exe project. So will it work?

![image](https://github.com/dotnet/runtime/assets/111659964/a6d54edb-2468-4d07-8952-8c2f52d17260)

**Comment by dadavadd** [comment]
![image](https://github.com/dotnet/runtime/assets/111659964/b9ecbbc6-c91c-457a-a9c3-29d692b1476a)
It worked!😊😊

**Comment by jkotas** [comment]
> Will it ever be possible to use DllMain in a dll using NativeA without crashing?

Very unlikely. The same restriction exists e.g. for signal handlers; or for `fork` API. It is not possible to write reliable signal handlers or a reliable managed code that calls `fork` directly. You have to use C/C++ to implement this type of code. We do not plan to fix these restrictions. It would require to a completely re-architecting thread suspension for GC and replacing with a slower more expensive scheme.

**Comment by jkotas** [comment]
> I will get a pointer to the Main method and simply call it using delegate* unmanaged in my exe project. So will it work?

Yes, this is fine.
