### ISSUE TITLE
Inconsistent namespace declarations in XElement.

### ISSUE THREAD

**Issue by nathan130200** [dotnet/runtime#100940]
### Description

When we declare the default namespace on the element ("xmlns") should it automatically add the attribute?

See the example below, between creating the element with the XNamespace directly and then defining the XMLNS attribute:

```cs
using System.Xml.Linq;

// ------------------ Parsing an XML tree ------------------
var el = XElement.Parse(@"<foo xmlns='bar' />");
el.GetDefaultNamespace().Inspect("GetDefaultNamespace");

// ------------------ Creating an XML tree ------------------
el = new XElement("{bar}foo");
el.GetDefaultNamespace().Inspect("GetDefaultNamespace");
el.Name.Namespace.Inspect("el.Name.Namespace");

el.Add(new XAttribute("xmlns", "other"));

el.GetDefaultNamespace().Inspect("GetDefaultNamespace");
el.Name.Namespace.Inspect("el.Name.Namespace");

el.ToString().Inspect("XML");
```

The results are:

> [!TIP]
> The `Inspect` extension method only does `WriteLine` with the expression and the provided value.

```cs
// ------------------ Parsing an XML tree ------------------

// attribute declared, parsed
GetDefaultNamespace: bar

// ------------------ Creating an XML tree ------------------

// this is empty, because XName does not add an xmlns attribute and this is wrong?
// even that XName has an namespace.
GetDefaultNamespace: 

el.Name.Namespace: bar

GetDefaultNamespace: other

el.Name.Namespace: bar

```

We can already see the inconsistency above. When declaring the element as an XNamespace appended with the XName it becomes different from the namespace declared with the `xmlns` attribute.

Now we try to convert the XElement into its string form and look at the result:

```cs
System.Xml.XmlException: The prefix '' cannot be redefined from 'bar' to 'other' within the same start element tag.
   at System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(String prefix, String ns)
   at System.Xml.XmlWellFormedWriter.WriteEndAttribute()
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at Program.<Main>$(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

### Reproduction Steps

1. Create an XElement with an XNamespace together.
1. Declare an `xmlns` attribute with a different value.
1. Try converting to string (invokes `ToString`) of the element.
1. The exception is thrown due to the namespace inconsistency.

### Expected behavior

When declaring the `xmlns` attribute it should replace the namespace of the element and its descendants. Since what defines that the element has a namespace is an `xmlns` attribute and not the `XName`.

### Actual behavior

Throw `System.Xml.XmlException` saying that the namespace cannot be redefined, since it was not even declared.

### Other information

[SharpLab sample](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6ADQFsAbMgGQEsoBHAbjzwDcBDMIgKY0iAXiIUAojQFUBUYGQAKfAM4CAFKlQAiADwAzAPaGiAD1pQVIgOQAjPtaIB6AHzaAlB1xCyAcQHAACIC+jwQNMAAcjyyKgAOPADGGu5kAJKWcQKJwOraANqKAIIASgDKEgC6RP5BIWER0bEJyR5ePgAqhmXAYMwA5uqpGfHZudrF5RKB4gCy9G2c3sJiUAIA7uJSMnLjAN72YAC+RoaLy34BwaHhUTEC8Ukp6ZljefkAwiUSRR1VNVd6rcmg8WgJzj4QWQQY9ki9Rjl3l8fn9qpD7tD7rDwZ4lj4inA4Oo1psKEVgL1GLYIMANNpzDRLNoYERtIZgAALARgDy43B4Hy1a4NO7NJ5DeFZREFZG/f5CoGNLFgiF0KEwsGSt4y75ytFqjEap7nAV0Lo9PpQQbDV7S2V/GYUeZtIA==)

**Comment by nathan130200** [comment]
Hello?

**Comment by tannergooding** [comment]
Please note that it's the weekend and in many places throughout the US, it is currently spring break so many people may be out enjoying themselves or spending time with friends/family.

The relevant area owners have been tagged and will get to your question in due time.

**Comment by nathan130200** [comment]
No problem, I'll rollback my library to resolve this by reimplementing the XML nodes classes.
