### ISSUE TITLE
AddIniFile Not found!

### ISSUE THREAD

**Issue by omidud** [dotnet/runtime#100992]
### Description

I install via Nuget Microsoft.Extensions.Configuration 
and the method of builder.AddInifile says is not found

### Reproduction Steps

using Microsoft.Extensions.Configuration;

namespace SomeNameSpace
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var builder = new ConfigurationBuilder();
            var configRoot = builder
                .AddIniFile("myfile.ini", true, false)
                .Build();

            // Error: AddIniFile Not found!

            /*
                      

            Severity	Code	Description	Project	File	Line	Suppression State
            Error	CS1061	'ConfigurationBuilder' does not contain a definition for 'AddIniFile' 
            and no accessible extension method 'AddIniFile' 
            accepting a first argument of type 'ConfigurationBuilder' 
            could be found (are you missing a using directive or an assembly reference?)	           

            */

        }
    }
}

### Expected behavior

Well to read the ini file

### Actual behavior

 Severity	Code	Description	Project	File	Line	Suppression State
 Error	CS1061	'ConfigurationBuilder' does not contain a definition for 'AddIniFile' 
 and no accessible extension method 'AddIniFile' 
 accepting a first argument of type 'ConfigurationBuilder' 
 could be found (are you missing a using directive or an assembly reference?)	

### Regression?

dont know

### Configuration

App.Config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2"/>
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

### Other information

project is using .Net Framework 4.7.2 i try with 4.8 and same error

**Comment by Suchiman** [comment]
Did you also install https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Ini ?

**Comment by omidud** [comment]
Thanks Suchiman!, is workinging now
Have a great day

**Comment by omidud** [comment]
no more issue found
