### ISSUE TITLE
CompileToAssembly_SimpleUseInDebug test failure on windows amd64

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#100964]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=640726
Build error leg or test failing: System.Text.RegularExpressions.Tests.RegexMatchTests.Match_TestThatTimeoutHappens
Pull request: https://github.com/dotnet/runtime/pull/100669

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Condition(s) not met: \"IsDebugAndRemoteExecutorSupported\"",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=640726
**Error message validated:** `[Condition(s) not met: "IsDebugAndRemoteExecutorSupported"`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/12/2024 2:14:31 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by buyaa-n** [comment]
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

Closing since it did not happen since April and the old links are not accessible anymore
