### ISSUE TITLE
System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess fails

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#100983]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=640383
Build error leg or test failing: System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess
Pull request: https://github.com/dotnet/runtime/pull/100900

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was -2146232797 but it should have been 42",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=640383
**Error message validated:** `[Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was -2146232797 but it should have been 42`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/12/2024 6:10:40 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[641392](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641392)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641392&view=ms.vss-test-web.build-test-results-tab&runId=15818850&resultId=178801)|dotnet/runtime#100380|
|[641373](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641373)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641373&view=ms.vss-test-web.build-test-results-tab&runId=15818238&resultId=189729)|dotnet/runtime#100898|
|[641268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641268)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641268&view=ms.vss-test-web.build-test-results-tab&runId=15816180&resultId=177295)|dotnet/runtime#100716|
|[641252](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641252)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641252&view=ms.vss-test-web.build-test-results-tab&runId=15815412&resultId=179432)|dotnet/runtime#100946|
|[640857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640857)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640857&view=ms.vss-test-web.build-test-results-tab&runId=15801534&resultId=179326)|dotnet/runtime#100954|
|[640730](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640730)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640730&view=ms.vss-test-web.build-test-results-tab&runId=15796646&resultId=180457)|dotnet/runtime#100729|
|[640383](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640383)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640383&view=ms.vss-test-web.build-test-results-tab&runId=15786090&resultId=177787)|dotnet/runtime#100900|
|[640081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640081)|dotnet/runtime|[System.Security.Cryptography.Tests.FactorySha1Tests.HashAlgorithm_TransformBlockAndDispose_ConcurrentUseDoesNotCrashProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640081&view=ms.vss-test-web.build-test-results-tab&runId=15776962&resultId=191406)|dotnet/runtime#100697|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|8|8|

**Comment by vcsjones** [comment]
Mistakingly re-opened. This has been resolved.
