### ISSUE TITLE
[wasm] 'emcmake' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#100973]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=638368
Build error leg or test failing: Build Browser wasm release Browser_wasm_Windows / Build product
Pull request: https://github.com/dotnet/runtime/pull/100889

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "'emcmake' is not recognized as an internal or external command,",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=638368
**Error message validated:** `['emcmake' is not recognized as an internal or external command,`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/12/2024 5:20:48 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[644281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644281)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/644281/logs/83)|dotnet/runtime#101033|
|[641136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641136)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641136/logs/210)|dotnet/runtime#99859|
|[641369](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641369)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641369/logs/72)|dotnet/runtime#100988|
|[641353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641353)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641353/logs/102)|dotnet/runtime#100984|
|[641148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641148)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641148/logs/112)|dotnet/runtime#99697|
|[641144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641144)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641144/logs/103)|dotnet/runtime#99700|
|[641140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641140)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641140/logs/103)|dotnet/runtime#99786|
|[641106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641106)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641106/logs/77)|dotnet/runtime#99694|
|[641092](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641092)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/641092/logs/77)|dotnet/runtime#99698|
|[640464](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640464)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/640464/logs/77)|dotnet/runtime#100137|
|[640457](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640457)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/640457/logs/77)|dotnet/runtime#99698|
|[639812](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639812)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/639812/logs/77)|dotnet/runtime#99700|
|[638368](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638368)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/638368/logs/105)|dotnet/runtime#100889|
|[630659](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630659)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/630659/logs/205)|dotnet/runtime#100648|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|14|

**Comment by directhex** [comment]
Why did https://dev.azure.com/dnceng-public/public/_build/results?buildId=630659 not flag this? 🤔
