### ISSUE TITLE
Custom JsonSerializer with System.Text cannot handle non-finite floating point literals.

### ISSUE THREAD

**Issue by Jabbl** [dotnet/runtime#100952]
## Summary
When creating a custom serializer for System.Text, there's no standard way of handling float values like `NaN`, `Infinity` and `-Infinity`.\
The methods `Utf8JsonWriter.WriteNumber()` and `Utf8JsonWriter.WriteNumberValue()` have no overloads that allow `JsonNumberHandling` and always throw when provided a non-finite floating point value.

This in and of itself would not be a problem if, for example, the `Utf8JsonWriter`-method `WriteFloatingPointConstant` was public.\
However, this method and similar ones that handle non-finite values are all internal.

Another, less desirable option, would be doing something like this:
```cs
if (double.IsFinite(value))
{
    writer.WriteNumberValue(value);
}
else if (double.IsInfinity(value))
{
    writer.WriteStringValue(JsonConstants.PositiveInfinityValue);
}
else if (double.IsNegativeInfinity(value))
{
    writer.WriteStringValue(JsonConstants.NegativeInfinityValue);
}
else
{
    writer.WriteStringValue(JsonConstants.NaNValue);
}
```
The problem here is that `JsonConstants` also has an `internal` accessor, thus making this impossible.\
This means that the above code has to be re-written to use hardcoded string-values `"Infinity"`, `"-Infinity"` and `"NaN"`, respectively.

Unless these constants are copied from the .NET source code, this could also introduce incompatibilities with the native `JsonConverter` if, for example, the `-Infinity` was written on a keyboard where `-` gets written as an actual minus sign (`\u2212`) instead of a dash (`\u002D`).

## Minimal reproduction
```cs
public class Program()
{
    public static int Main(string[] args)
    {
        JsonSerializerOptions options = new() { NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals };

        TestClass? instance = new() { Value = Double.NaN };
        string json = JsonSerializer.Serialize(instance, options); // Throws, even though the options would seem to allow literals.

        json =
            """
            {
                "V": "NaN"
            }
            """;
        instance = JsonSerializer.Deserialize<TestClass>(json, options); // Also throws.
    }
}


[JsonConverter(typeof(TestClassConverter))]
class TestClass
{
    public double Value { get; set; }
}

class TestClassConverter : JsonConverter<TestClass>
{
    public override TestClass? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException();
        }

        TestClass instance = new();
        int startDepth = reader.CurrentDepth;
        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject && reader.CurrentDepth == startDepth)
            {
                break;
            }
            if (reader.TokenType == JsonTokenType.PropertyName)
            {
                if (reader.ValueTextEquals("V"))
                {
                    // instance.Value = reader.GetDoubleFloatingPointConstant() <- This method is inaccessible.
                    instance.Value = reader.GetDouble(); // <- This method doesn't accept 'JsonNumberHandling'.
                }
            }
        }
        return instance;
    }

    public override void Write(Utf8JsonWriter writer, TestClass value, JsonSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        writer.WriteStartObject();
        //writer.WritePropertyName("V"u8);
        //writer.WriteFloatingPointConstant(value.Value);  <- This method is inaccessible.
        writer.WriteNumber("V"u8, value.Value); // <- This method doesn't accept 'JsonNumberHandling'.
        writer.WriteEndObject();
    }
}
```

## Expected behaviour
`Utf8JsonWriter.WriteFloatingPointConstant()` and `Utf8JsonReader.GetDoubleFloatingPointConstant()` or similar helper-methods are public and can be accessed by custom Json converters.

## Environment details
.NET SDK version: 8.0

**Comment by elgonzo** [comment]
Instead of manually duplicating the de/serialization function for floating-point values, you could just use the de/serializer for this, e.g. replace

    instance.Value = reader.GetDouble()

with

    instance.Value = JsonSerializer.Deserialize<double>(ref reader, options)

and

    writer.WriteNumber("V"u8, value.Value)

with

    writer.WritePropertyName("V"u8); writer.WriteRawValue(JsonSerializer.Serialize(value.Value, options))
    

(The json format itself has no concept and no representations for NaN and infinity, so it kinda fits that Utf8JsonReader/Utf8JsonWriter don't deal with this. On the other hand, i would agree that it makes dealing with floating point values in such circumstances quite a bit akward...)

**Comment by eiriktsarpalis** [comment]
`JsonNumberHandling` is a concept sitting on the serialization layer and is not applicable to `Utf8JsonReader`. I dont' believe it would be appropriate to move that logic to the reader layer. Recommended workaround would be to delegate to the built-in converter for `double` per @elgonzo's suggestion.
