### ISSUE TITLE
Regression in R2R compilation time

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#100995]
Linux and Windows, PlaintextPlatform benchmark in this example, Single file, Trimmed and Self-contained

![image](https://github.com/dotnet/runtime/assets/1165805/6b9c7807-6ee1-44fb-a853-ceb6d5ffc65e)

Binlogs before/after show 

![image](https://github.com/dotnet/runtime/assets/1165805/5f0d1b7c-3522-4848-9ef3-934d6c6449b2)

[msbuild.binlog.zip](https://github.com/dotnet/runtime/files/14964046/msbuild.binlog.zip)

**Comment by EgorBo** [comment]
@sebastienros is there a commit range? (I don't see an ability to view it on the e.g. Single File tab)

**Comment by EgorBo** [comment]
Likely, https://github.com/dotnet/runtime/compare/ffb257818db8...e6c1a49be165

**Comment by sebastienros** [comment]
That's what I have yes, we could probably go shorter by trying builds from within the range if you don't find anything

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario plaintext --profile intel-lin-app --profile intel-load-load --application.buildArguments "/p:PublishReadyToRun=true /p:PublishSingleFile=true" --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.4.24205.2 --application.runtimeVersion 9.0.0-preview.4.24204.3 --application.sdkVersion 9.0.100-preview.4.24208.11
```

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario plaintext --profile intel-lin-app --profile intel-load-load --application.buildArguments "/p:PublishReadyToRun=true /p:PublishSingleFile=true" --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.4.24208.6 --application.runtimeVersion 9.0.0-preview.4.24209.8 --application.sdkVersion 9.0.100-preview.4.24211.4
```

**Comment by EgorBo** [comment]
TP regressed on NativeAOT too:


![image](https://github.com/dotnet/runtime/assets/523221/16161097-fcd7-4655-985d-dd3f317665c9)

**Comment by sebastienros** [comment]
Haven't had time to file this one, are you saying it's related? I wouldn't think so

**Comment by EgorBo** [comment]
> Haven't had time to file this one, are you saying it's related? I wouldn't think so

Dates match

**Comment by EgorBo** [comment]
The thing is - when something goes wrong for AOT'd code - JIT can just re-jit it, while NAOT cannot, so it explains why TP only got hurt for NAOT.

**Comment by sebastienros** [comment]
Here are the commands for the AOT one:

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario todosapipublishaot --profile intel-win-app --profile intel-lin-load --profile amd-lin2-db --application.packageReferences Microsoft.DotNet.ILCompiler=9.0.0-preview.4.24204.3 --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.4.24205.2 --application.runtimeVersion 9.0.0-preview.4.24204.3 --application.sdkVersion 9.0.100-preview.4.24208.11
```

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario todosapipublishaot --profile intel-win-app --profile intel-lin-load --profile amd-lin2-db --application.packageReferences Microsoft.DotNet.ILCompiler=9.0.0-preview.4.24209.5 --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.4.24208.6 --application.runtimeVersion 9.0.0-preview.4.24209.5 --application.sdkVersion 9.0.100-preview.4.24209.32
```

**Comment by EgorBo** [comment]
The main suspect is https://github.com/dotnet/runtime/pull/99982

**Comment by sebastienros** [comment]
Minimal changeset identified for the nativeaot benchmark:

https://github.com/dotnet/runtime/compare/a8c2a5e5bbc2...404b286b2309

**Comment by EgorBo** [comment]
Oh, so https://github.com/dotnet/runtime/pull/100728/ then?

**Comment by sebastienros** [comment]
nativeaot may be special, not sure if moving the runtime version without the corresponding sdk might change the outcome. But at least I set the framework reference and `Microsoft.DotNet.ILCompiler` to the same runtime. On `9.0.0-preview.4.24208.9+a8c2a5e5bbc2` we get 398K RPS and on `9.0.0-preview.4.24208.10+404b286b2309` only 178K RPS.

**Comment by stephentoub** [comment]
> Oh, so #100728 then?

Really??

**Comment by MichalPetryka** [comment]
> > Oh, so #100728 then?
> 
> Really??

@SingleAccretion suspects [this](https://github.com/dotnet/runtime/pull/100728/files#diff-a8b4511c639eea6bb771ebc0eed7e7c945145e5960628c5be6ef1bb66c5e4447R38) to be the reason since `CastCache` is a mutable struct.

**Comment by stephentoub** [comment]
Ugh. I looked for each such type I wasn't sure about, and I swear I saw it was a class, but I probably incorrectly mistook https://github.com/dotnet/runtime/blob/7b18be52fe191c7961be28621025710d2d6e3b05/src/coreclr/vm/castcache.h#L48 for it

**Comment by stephentoub** [comment]
> Feels like there should be a builtin analyzer warning on readonly fields and in parameters with non-readonly structs for this.

https://github.com/dotnet/runtime/issues/33773

https://github.com/dotnet/roslyn-analyzers/issues/2811

https://github.com/dotnet/roslyn-analyzers/pull/2831

https://github.com/dotnet/runtime/issues/50389

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/runtime/pull/100996

**Comment by EgorBo** [comment]
@sebastienros can you take a look if it's solved

**Comment by sebastienros** [comment]
I confirm the NAOT one is fixed, I had to set `--application.packageReferences Microsoft.DotNet.ILCompiler=9.0.0-preview.4.24215.2` as I assume it hasn't been ingested by the installer yet. But the build times are still slow. We should check again when we know this is in installer builds.
