### ISSUE TITLE
Process Start with RedirectOutput can lead to thread starvation

### ISSUE THREAD

**Issue by yuehuang010** [dotnet/runtime#101067]
### Description

Hello, 

My program is managing many child process via System.Diagnostics.Process API.  When starting the process with RedirectStandardInput/Error and their respective events, it leads to my program being less responsive due to other events being unable to fire.  I suspect it is due to thread starvation.

After troubleshooting, my workaround is to avoid the RedirectStandardInput/Error and implement my own private message pipe in both programs, but this workaround might not be suitable for everyone.  I wish this would would be addressed as it could extend to many other scenarios.  

### Configuration

Testing on Windows 11, x64, .net 4.7.2 and 8.  
Issue may not be limited to this configuration.
Due to threading scaling with machine core/thread, the number of child process necessary to repro may differ.

### Regression?

Not a regression

### Data

Attached repro source code. [Program.zip](https://github.com/dotnet/runtime/files/14981839/Program.zip)

Build and Run the app.
Once the app is running for about a second or two, press any key to start the cancelation event.  It will print how long it took to cancel.  Update the line `bool setReceiveEvents = true;` to `false`.  Rerun. See how long it takes to cancels.

When `true`, it takes:
```
Cancel took 16166.6151ms.
```
Compared to `false`
```
Cancel took 277.0083ms.
```

### Analysis

Take this analysis with a grain of salt.

Diagnostic Process is using AsyncStreamReader to read the pipe in a new task.  The new task is not created with TaskCreationOptions.LongRunning or similar flags.  I also have had mixed result with ThreadPool.QueueUserWorkItem() as it doesn't respect TaskCreationOptions.LongRunning.

**Comment by fbrosseau** [comment]
https://github.com/dotnet/runtime/issues/81896

**Comment by yuehuang010** [comment]
Awesome, I will follow the first issue.
