### ISSUE TITLE
[NativeAOT] Failed to create generic virtual method implementation

### ISSUE THREAD

**Issue by andreakarasho** [dotnet/runtime#101043]
### Description

Building the project with `dotnet publish -c Release -f net8.0 -r win-x64 -p:PublishAot=true -p:TargetFrameworks=net8.0`
and running the binary result causes the following error:

```bash
Process terminated. Failed to create generic virtual method implementation

Declaring type: ?
Method name: TinyEcs.ISystem.RunIf
Instantiation:
  Argument 00000000: ?<?>
  Argument 00000001: ?<?>
  Argument 00000002: ?<?>
  Argument 00000003: ?<?>
```

### Reproduction Steps

```bash
git clone https://github.com/andreakarasho/TinyEcs.git
cd TinyEcs/samples/MyBattleground
dotnet publish -c Release -f net8.0 -r win-x64 -p:PublishAot=true -p:TargetFrameworks=net8.0
```
Go to `bin/Release/net8.0/win-x64/publish` and execute `MyBattleground.exe`
It breaks here https://github.com/andreakarasho/TinyEcs/blob/e37759fac68dc5a98bb54ad0e68a31a0d8a5f6c9/samples/MyBattleground/Program.cs#L150

### Expected behavior

The app continue running

### Actual behavior

The app stops with `Process terminated. Failed to create generic virtual method implementation`

### Configuration

dotnet version: `9.0.100-preview.3.24204.13`
Windows 11 x64

### Other information

I also tested with latest net9.0 preview 3 with the following command:
`dotnet publish -c Release -f net9.0 -r win-x64 -p:PublishAot=true -p:TargetFrameworks=net9.0`
and got the same result.

`TinyEcs.ISystem.RunIf` Interface methods and implementation are generated by a source generator in /tools/

**Comment by MichalStrehovsky** [comment]
This is caused by the unsupported IlcDisableReflection switch in the project file. Drop the switch and the problem will be gone.

**Comment by andreakarasho** [comment]
> This is caused by the unsupported IlcDisableReflection switch in the project file. Drop the switch and the problem will be gone.

Hey, thank you for the reply!
I wonder how the reflection is involved if I'm not using it at all

**Comment by jkotas** [comment]
Generic virtual methods are de-facto reflection.
