### ISSUE TITLE
Using Visual Studio for Managed Code

### ISSUE THREAD

**Issue by jianghupt** [dotnet/runtime#101035]
### Description

I traced the debug runtime. md file debugging CoreCLR

According to the following document link:
https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-runtime.md#using-visual-studio-for-managed-code

But when the breakpoint reaches the PreStubWorker function of coreclr.dll, the parameter pMD of PreStubWorker cannot display the content in ifdef _DEBUG. How can I make it display?

Fields in ifdef _DEBUG of MethodDesc:

```
#ifdef_DEBUG
       LPCUTF8 m_pszDebugMethodName;
       LPCUTF8 m_pszDebugClassName;
       LPCUTF8 m_pszDebugMethodSignature;
       PTR_MethodTable m_pDebugMethodTable;
       PTR_GCOverageInfo m_GcCover;
#endif_DEBUG
```

For example, how should I check the value of pMD->m_pszDebugMethodName when the breakpoint reaches PreStubWorker?

### Reproduction Steps

I am debugging coreclr.dll and want to view the value of the field m_pszDebugMethodName in MethodDesc.

### Expected behavior

How to see the value of m_pszDebugMethodName

### Actual behavior

Cannot see the value defined in MethodDesc ifdef_DEBUG

**Comment by jkotas** [comment]
Fields under ifdef _DEBUG are only present in "Debug" builds of the runtime.

To see these fields, you have to create a local Debug build of the runtime by running `build.cmd -s clr -c Debug` or similar command. Check https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-runtime.md#debugging-coreclr-on-windows

**Comment by jianghupt** [comment]
> Fields under ifdef _DEBUG are only present in "Debug" builds of the runtime.
> 
> To see these fields, you have to create a local Debug build of the runtime by running `build.cmd -s clr -c Debug` or similar command. Check https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-runtime.md#debugging-coreclr-on-windows

If I don't build it, is there no other way to view it?

**Comment by jkotas** [comment]
Correct.

The "Debug" builds of the runtime with these additional fields do not ship anywhere. In theory, you can download them from dotnet/runtime CI system, but it is easier to just build your own.

**Comment by jianghupt** [comment]
> Correct.
> 
> The "Debug" builds of the runtime with these additional fields do not ship anywhere. In theory, you can download them from dotnet/runtime CI system, but it is easier to just build your own.

Thank you, got it

**Comment by jianghupt** [comment]
> Correct.
> 
> The "Debug" builds of the runtime with these additional fields do not ship anywhere. In theory, you can download them from dotnet/runtime CI system, but it is easier to just build your own.

Then this kind of Visual Studio debugging is meaningless.What is its significance?
can it Add a debug mode coreclr.dll to facilitate visual  studio debugging

**Comment by jkotas** [comment]
This kind of debugging is meant to be used by the developers in dotnet/runtime repo.

**Comment by jianghupt** [comment]
Are there any debugging symbols in debug mode that can be provided? Building coreclr is too troublesome compared to this.

**Comment by jkotas** [comment]
Do you mean symbols for the shipping binaries? Yes, the symbols for the shipping binaries are on the symbol server. Given that you were able to set a breakpoint at PreStubWorker, Visual Studio downloaded these symbols for you.

**Comment by jianghupt** [comment]
Debug symbols in debug mode, not release mode

**Comment by jkotas** [comment]
As I have said, it is best to build your own debug binaries with matching debug symbols. They are not readily available for download.

**Comment by jianghupt** [comment]
> As I have said, it is best to build your own debug binaries with matching debug symbols. They are not readily available for download.

Didn’t I say that the sysmbol provided by debug-debug can check the fields in if _debug, but the sysmbol of release-debug cannot check the fields in if _debug, otherwise what is the meaning of this vs debugging?
Does this mean that this is currently not possible?

**Comment by danmoseley** [comment]
@jianghupt Can you say now about what you're trying to achieve? Very few developers debug the runtime itself and even fewer the debug flavor.
