### ISSUE TITLE
Deserialization error for default datetime with offset other than 0

### ISSUE THREAD

**Issue by shridharrathi** [dotnet/runtime#101066]
Hi team, 

I came across the following issue.

When json datetime property has "0001-01-01T00:00:00+00:00" deserialization works properly.

When json datetime property has "0001-01-01T00:00:00+13:00" deserialization throws the following error. 

> Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset

Can this be fixed?

Following is the code
```
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
public class Program
{
	public static void Main()
	{
		string json = @"{		  
		  ""createdDate"": ""0001-01-01T00:00:00+13:00""
		}";
		
		Account account = System.Text.Json.JsonSerializer.Deserialize<Account>(json, new JsonSerializerOptions
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        });
		Console.WriteLine(account.CreatedDate);
	}
}

public class Account
{	
	public DateTimeOffset CreatedDate { get; set; }
}
```

**Comment by Clockwork-Muse** [comment]
> Sorry my bad, we are converting it to DateTime and DateTime.Parse works for it.

 - `DateTimeOffset` is the proper type
 - A value that logs the _timestamp_ when an account was created (`CreatedAt`) should be stored/serialized with a **zero** offset, in UTC.
 - A `CreatedDate` should likely always be populated, so a "non-present" value (such as a min value) may be unnecessary.  If you do need a "not set" value, consider using an optional/nullable value (eg, `DateTimeOffset?`)
 - Values created this way are given `DateTimeKind.Local`.  Assumedly your current offset is +13.  If you're deploying this to a server, which should be set to UTC, it will fail there, _in addition to_ possibly causing other subtle bugs.  If you deploy it to any other zone with an offset of less than +13 (which is almost all of them), it will also fail.

Changing the property to `DateTime` doesn't properly solve some fundamental problems with your apparent data usage and assumptions.

**Comment by shridharrathi** [comment]
@Clockwork-Muse, 

`Account` class is just for creating the sample. 

We are having trouble when our web app (using System.Text.Json deserialization) receives data from the API server(using Newtonsoft deserialization). It is API server which sets default date to `0001-01-01T00:00:00+13:00`

Both the servers are on-premise servers and we are using `DateTimeKind.Local`.

Having `DateTimeOffset?` does not solve the problem either.

Newtonsoft package can handle this scenario and hence I was wondering it can be handled in the System.Text.Json package as well

**Comment by Clockwork-Muse** [comment]
>  It is the API server that sets the default date to `0001-01-01T00:00:00+13:00`

Then you should change your API server, if practical.

> Both the servers are on-premise servers and we are using `DateTimeKind.Local`.

Don't do that.  And it's best practice to run your servers in UTC.
For one thing, you've just made it harder to run in cloud infrastructure, which may not always provide a way to set the server timezone.  If you expand to more timezones (or plan to expose the API to those who are, like Australia), you're going to run into the exact same problem you're experiencing here.

Making your API responses dependant on host timezone is only going to cause you (and your callers) problems, and you should change your code to avoid that.
For one thing, it's now not possible to just check against `DateTimeOffset.MinValue` to see if I got that "not set" value... I have to somehow know the proper offset.  Which, if you're in a timezone with DST, is going to change.

> Having `DateTimeOffset?` does not solve the problem either.

Of course just setting the field to that type alone wouldn't solve it.  The intent was that you make it that type, and then your API server _does not include the field_ in the response.  Because a min value like that usually means "I'm not setting a value".

**Comment by shridharrathi** [comment]
Thanks, to tackle this issue, we are handling this in API. I raised this because Newtownsoft.Json package can handle it and thought it might be possible to handle the same in System.Text package. 

If it is not going to be fixed, I can close this issue. 

PS: We can't set our servers on UTC due to other complicated reasons.

**Comment by Clockwork-Muse** [comment]
Won't be "fixed", this is by-design.

> We can't set our servers on UTC due to other complicated reasons.

While it's best practice to always set servers to UTC as a fallback safety measures, there are intermediate steps you can take:
 - Run the program/processes separately under UTC (via setting `TZ` or similar, or other applications).
 - Modern server applications should generally be run containerized, and normally will inherit a container default of UTC.  Run the application from inside a docker container.
 - Modify just this application to be zone and culture agnostic - never use `DateTimeKind.Local` or `DateTime.Now`/`DateTimeOffset.Now`, etc.  When a function needs a specific zone or culture for user-facing reasons, pass it in based on retrieving the relevant business entity records (eg, the user zone from profile information for online forums).

**Comment by shridharrathi** [comment]
Thanks, that is helpful.
