### ISSUE TITLE
WinForms Self Executable: The application to execute does not exist

### ISSUE THREAD

**Issue by mingazhev** [dotnet/runtime#1010]
**Situation:**
We build a small winforms app targeting netcoreapp3.1 as a single executable.
Somehow (we couldn't figure how and why), after about a week since last successful start application accidentally fails to start.
There is an error in windows event logs:

> Description: A .NET Core application failed.
> Application: {APP_NAME}.exe
> Path: {PATH_TO_EXE}.exe
> Message: The application to execute does not exist: 'C:\Users\{USER_NAME}\AppData\Local\Temp\.net\{APP_NAME}\upxeetor.sw2\{APP_NAME}.dll'.

After some experiments we found out that app starts successfull if the whole folder deleted but fails to start if only application DLL is deleted, and that is what is happened (on different PC-s, in different countries).

So **steps to reproduce** are:
1. Build single executable .NET Core 3.1 WinForm app
2. Start and gracefully exit application
3. Remove application DLL from C:\Users\{USER_NAME}\AppData\Local\Temp\.net\{APP_NAME}\ 
4. Try to start again

On the first glance, checking that files are not removed and consistent is not runtime' responsibility.

But on the other hand - application (as it is a single exe) checks that folder exists, creates if not, exctracts it's files there. I think that it would be wonderfull if it could at least check that all files are present and restore them if needed. Especially if it stores files in such unreliable location as "TEMP" folder.

**Comment by elinor-fung** [comment]
Looks like another instance of running into dotnet/core-setup#8314. The current workaround (described in that issue) is setting `DOTNET_BUNDLE_EXTRACT_BASE_DIR`.

cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
Yes, this is a dup of  dotnet/core-setup#8314. 

We're considering a service fix to re-extract the contents of the bundle on failure within the host.

In the meantime, by setting DOTNET_BUNDLE_EXTRACT_BASE_DIR, you can extract to a non-temporary location where the OS doesn't cleanup the files, thus circumventing the failure.
