### ISSUE TITLE
System.Net.Http.Functional.Tests.HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws fails

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#101015]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=642123
Build error leg or test failing: Build / Libraries Test Run release coreclr windows x64 Debug / Send to Helix
Pull request: https://github.com/dotnet/runtime.git/pull/101007

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "ClientHandler_MaxResponseHeadersLength_(?:Test|Http3)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=642123
**Error message validated:** `[ClientHandler_MaxResponseHeadersLength_(?:Test|Http3)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/16/2024 11:17:09 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[695292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695292)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/695292/logs/909)|dotnet/runtime#102699|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[688895](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688895)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688895&view=ms.vss-test-web.build-test-results-tab&runId=17113138&resultId=219023)|dotnet/runtime#102699|
|[687577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577&view=ms.vss-test-web.build-test-results-tab&runId=17073526&resultId=220449)|dotnet/runtime#100951|
|[682021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682021)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http2.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682021&view=ms.vss-test-web.build-test-results-tab&runId=16931180&resultId=213392)||
|[681987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http11_Cancellation_Test.GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987&view=ms.vss-test-web.build-test-results-tab&runId=16928002&resultId=213537)||
|[681186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186&view=ms.vss-test-web.build-test-results-tab&runId=16905374&resultId=216284)|dotnet/runtime#100951|
|[679966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679966)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http2.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679966&view=ms.vss-test-web.build-test-results-tab&runId=16862634&resultId=213752)||
|[679420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420&view=ms.vss-test-web.build-test-results-tab&runId=16846488&resultId=212322)||
|[678355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http1_Async.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355&view=ms.vss-test-web.build-test-results-tab&runId=16816166&resultId=209929)||
|[675315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675315)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675315&view=ms.vss-test-web.build-test-results-tab&runId=16743704&resultId=219556)|dotnet/runtime#102181|
|[667272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667272)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667272&view=ms.vss-test-web.build-test-results-tab&runId=16551250&resultId=217017)|dotnet/runtime#101939|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|11|

**Comment by liveans** [comment]
This is only failing for HTTP/3.

This test has been disabled with #94507 until now, and re-enabled on #100911, looks like it has the same root cause as #94507.

/cc: @ManickaP
