### ISSUE TITLE
[API Proposal]: Support fingers-crossed mode for logging.

### ISSUE THREAD

**Issue by voroninp** [dotnet/runtime#101054]
### Background and motivation

When things go wrong, it's better to know as much as possible, when everything works fine, silence is rewarding.
Logging should support this behavior.

The main idea is to introduce a section within which all log messages are cached until a message with certain level ( + category?) is logged. If this does not happen, all messages are discarded.

[PHP Symfony's Monolog has this mode](https://symfony.com/doc/current/logging.html#handlers-that-modify-log-entries)

### API Proposal

Add method to `ILoggerFactory` (breaking change unless default implementation is provided):
```
public interface ILoggerFactory
{
    public IDisposable StartGrouping(LogLevel logAtLevel)
    {
        throw new NotSupportedException();
    }
}
```
- This is the API intended for the middleware in the first place.
- Groups can be nested
- If the inner group produces no messages (Nothing is logged with `logAtLevel` level) then outer group does not receive the messages.
- Intersection of the groups should be prohibited:
  ```CSharp
  var group1 = _loggerFactory.StartGrouping(LogLevel.Error);
  var group2 = _loggerFactory.StartGrouping(LogLever.Critical);
  group1.Dispose(); // Should throw an exception here.
  group2.Dispose();
  ```
  

### API Usage

```CSharp
using var loggingGroup = _loggerFactory.StartGrouping(logAtLevel: LogLevel.Error);
_logger.LogInformation("Hello world!");
_logger.LogCritical("Apocalypse now!");
```
Both messages are logged.

```CSharp
using var loggingGroup = _loggerFactory.StartGrouping(logAtLevel: LogLevel.Error);
_logger.LogInformation("Hello world!");
_logger.LogWarning("Boeing opened another door!");
```
Neither of the messages get logged, because section did not contain logging with `Error` level.

### Risks

Keeping all log messages for the group, especially if it spans the entire request, negatively affects the performance. On the other hand, `Activity` api already has similar behavior.

Another config section is required for letting or prohibiting loggers of certain categories to join the group.
For example, I may be interested only in grouping log messages coming from my code.

If logging occurs inside grouping section and logger is allowed to join the group, `ILogger.IsEnabled(...)` should return `true` for the checks (especially relevant for source generated code):
```
if (_logger.IsEnabled(level))
{
    _logger.Log(...);
}
```

**Comment by voroninp** [comment]
> Log returns, the caller may recycle or otherwise invalidate the state object that it passed there.

Yes, you are right. This is indeed a predicament ='(. I'd prefer analyzer to emit a warning, if I pass complex objects as arguments to `Log` method. In most cases values are primitive types: ints, strings, dates.

**Comment by ChrML** [comment]
We did-ish something like this with a custom provider. But we only keep a ring-buffer of readily formatted messages. That are conditionally logged if more important things happen later.

**Comment by voroninp** [comment]
@ChrML , there's a Seq sink https://github.com/alexeyshockov/Serilog.Sinks.FingersCrossed for this, but it won't work for logging with source generator, because the generated code explicitly checks log level.

**Comment by tarekgh** [comment]
Looks this can be addressed by https://github.com/dotnet/extensions/issues/5123. 

CC @evgenyfedorov2 @geeknoid @noahfalk

**Comment by geeknoid** [comment]
Yes, we're aiming to add support for both sampling and buffering. Buffering keeps data in memory until/if a trigger happens, at which point the data is sent down the wire. 

Large active services can log a lot of state, and most of it is for naught. Yet, even though nobody looks at the data 99% of the time, generating, processing, and storing all this data costs a pretty penny. If we can avoid generating logs when everything is good, we think this can lead to quite substantial COGs improvements for the service.

**Comment by tarekgh** [comment]
I am closing this issue here. @voroninp feel free to respond on https://github.com/dotnet/extensions/issues/5123 if your scenario still missing features there. Thanks for your report.
