### ISSUE TITLE
MemoryStream is not [Serializable]

### ISSUE THREAD

**Issue by dasetser** [dotnet/runtime#10106]
MemoryStream is not marked with the SerializableAttribute and fails to be deserialized. Without this attribute we're unable to create a WCF client to communicate with existing services that return MemoryStreams.

This was reported in  dotnet/wcf#2307.

**Comment by danmosemsft** [comment]
What is the remaining action here - is it "I think the best we can do is to have a list of types that used to be binary serialiable, but are not serializable anymore" ?

**Comment by mconnew** [comment]
This isn't an issue with binary serialization. People with WCF services which return a MemoryStream are broken. This broke serialization with DataContractSerializer.

**Comment by GrabYourPitchforks** [comment]
@mconnew I tried serializing an empty `MemoryStream` using .NET Framework's DCS and got the following xml:

```xml
<MemoryStream xmlns="http://schemas.datacontract.org/2004/07/System.IO" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <__identity i:nil="true" xmlns="http://schemas.datacontract.org/2004/07/System"/>
  <_buffer/>
  <_capacity>0</_capacity>
  <_expandable>true</_expandable>
  <_exposable>true</_exposable>
  <_isOpen>true</_isOpen>
  <_length>0</_length>
  <_origin>0</_origin>
  <_position>0</_position>
  <_writable>true</_writable>
</MemoryStream>
```

Is this the expected output? That looks like something we don't want to send across the wire.

**Comment by mconnew** [comment]
@GrabYourPitchforks, while it's true that this isn't ideal to send across the wire, it does actually work to serialize and deserialize correctly. When the serializable attribute was placed on the class, it should have been designed better but it wasn't. I suspect that's the result of whoever did that only thinking about a single serialization case (BinaryFormatter). It's a mistake which gets repeated over and over even as recently as the 4.7.x release timeframe (CultureAwareComparer was broken for non-BinaryFormatter cases recently).  
But we're here now with customers using MemoryStream in their WCF service contracts unaware that it wasn't designed to be serialized to XML as it just works. On .NET Framework, it will roundtrip via XML successfully. But not on .NET Core. We broke customers web services and the answer was "they shouldn't be using that class" despite .NET putting the Serializable attribute on it explicitly telling customers it's fine to use.  
Can you tell I'm a little frustrated with the willingness to break existing customers serialization? The worst part is it fails silently. When deserializing on .NET Core, you just get an empty MemoryStream and are unaware that you dropped data.

**Comment by GrabYourPitchforks** [comment]
This scenario involves deserialization into private instance fields, which is one of the things we were trying to move away from across our serializers. (It's one of the main reasons we obsoleted `BinaryFormatter`.)

Can the scenario be accomplished through the use of a custom `IDataContractSurrogate` or similar?

**Comment by mconnew** [comment]
It can be done by a custom IDataContractSurrogate, and in fact that's the workaround we've recommended in the original issue on WCF. The problem though is it might go completely undetected for a while as it doesn't throw any errors. It just silently deserializes an empty MemoryStream. So the steps which would be needed are:  
1. Hopefully notice deserialization isn't working right before going into production and losing data
2. Go searching online and hopefully maybe find the issue in the WCF repo
3. Copy the code and add to your application to work around the breaking change

Expecting 1 and 2 to happen without causing frustration and ill will is optimistic. I believe breaking serialization of existing types which are data containers such as MemoryStream is wrong. It's akin to breaking serialization of `List<T>` or `Dictionary<K,V>`.

**Comment by Treit** [comment]
My team just had to perform a painful and technically difficult rollback after finally replacing one of our flagship web services (several million lines of code) with a new .NET Core version, only to discover this regression.

In our case we were seeing an exception because the serializer was trying to access the Timeout property, which on MemoryStream throws an InvalidOperationgException 'Timeouts are not supported on this stream.' Unfortunately this exception was happening in a code-path where we are writing cache data to disk and do not want to fail the call if the cache write fails, so we simply log the exception. Thus, none of our tests failed but in the real world this leads to increased database load and unacceptable latency regressions.

I agree with @mconnew that willfully breaking serialization of MemoryStream is a major mistake and a costly one. Please fix this.

**Comment by jkotas** [comment]
As I have said in https://github.com/dotnet/runtime/issues/10106#issuecomment-381235814, I believe this should be fixed by better diagnostic in the serializer. The serializer should throw exception instead of dropping the data silently on the floor.

**Comment by Treit** [comment]
> As I have said in [#10106 (comment)](https://github.com/dotnet/runtime/issues/10106#issuecomment-381235814), I believe this should be fixed by better diagnostic in the serializer. The serializer should throw exception instead of dropping the data silently on the floor.

@jkotas it didn't drop data silently in my case. It threw an exception:

`System.InvalidOperationException: Timeouts are not supported on this stream.
   at System.IO.Stream.get_ReadTimeout()
   at WriteMemoryStreamToXml(XmlWriterDelegator , Object , XmlObjectSerializerWriteContext , ClassDataContract )
   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
<snip>`

If it had silently dropped the data that would have been even worse, but it's still a major and unexpected breaking change for those of us porting large projects from. NET Framework to .NET Core.

**Comment by GrabYourPitchforks** [comment]
Applied t-shirt costing size small. Even if we make the change directly in the serializer rather than slap `[Serializable]` on this type, I'd expect it to be a targeted change without broad impact to the ecosystem.
