### ISSUE TITLE
ilasm do not handle the "/mdv" command line option

### ISSUE THREAD

**Issue by Migel1** [dotnet/runtime#101052]
### Description

ilasm always sets metadata version to "v4.0.30319" regardless of the value specified in the "/mdv" command line option.

### Reproduction Steps

Create test.il file with the following contents:
```
.assembly test
{
  .hash algorithm 0x00008004
  .ver 0:0:0:0
}
``` 
Assemble it with ilasm.exe:
`ilasm.exe -mdv=v2.0.50727 -dll test.il`
Now disassemble the resulting dll:
`ildasm.exe -out=test_new.il test.dll`

### Expected behavior

test_new.il is expected to contain the comment
`// Metadata version: v2.0.50727`

### Actual behavior

Actually test_new.il contains the comment
`// Metadata version: v4.0.30319`

### Regression?

The behaviour is observed in all tested releases of CoreCLR ilasm up to 9.0.0-preview.3.24172.9.

But ilasm.exe binary from .NET Framework 4.8 (and presumably other Framework versions) works correctly and successfully sets the metadata version in the test.dll assembly according to the value specified in the command line.

### Known Workarounds

none

### Configuration

Windows 10 x64 21H2.
CoreCLR ILAsm x64 8.0.0 and 9.0.0-preview.3.24172.9 (binaries from nuget.org).
Probably the problem is the same for all CoreCLR platforms.

### Other information

By inspecting the ilasm sources it seems that ilasm parses the "/mdv" option, but forgets to pass the parsed value to the CLR metadata writer, so the writer always use the default version string, which is "v4.0.30319".

**Comment by jkotas** [comment]
Regression introduced by #48497
