### ISSUE TITLE
[API Proposal]: MethodInfo.Invoke overload with span<object?> instead of object?[]

### ISSUE THREAD

**Issue by snakex64** [dotnet/runtime#101032]
### Background and motivation

It could provide significant performance advantages in specific situations to be able to use span instead of classical arrays when invoking method through reflection. 
One of the benefits in heavy generic reflection situation would be to allow re-using arrays from shared pools and create a span on it of the required size.

The current API already use Span in some places behind the scene, I haven't found any issue preventing a new overload

### API Proposal

```csharp
namespace System.Reflection;

public abstract class MethodBase : MethodInfo
{
    // existing methods
    public object? Invoke(object? obj, object?[]? parameters);
    public abstract object? Invoke(object? obj, BindingFlags invokeAttr, Binder? binder, object?[]? parameters, CultureInfo? culture);

   // New proposed methods
    public object? Invoke(object? obj, Span<object?>? parameters);
    public abstract object? Invoke(object? obj, BindingFlags invokeAttr, Binder? binder, Span<object?>? parameters, CultureInfo? culture);
}
```

### API Usage

```csharp
// Fancy the value
MethodInfo methodInfo = myType.GetMethod(...);

Span<object?> inputs = ...;
object? returnValue = methodInfo.Invoke(null, inputs);
```

### Alternative Designs

```csharp
namespace System.Reflection;

public abstract class MethodBase : MethodInfo
{
    // existing methods
    public object? Invoke(object? obj, object?[]? parameters);
    public abstract object? Invoke(object? obj, BindingFlags invokeAttr, Binder? binder, object?[]? parameters, CultureInfo? culture);

   // New proposed methods
    public object? Invoke(object? obj, Span<object?> parameters);
    public abstract object? Invoke(object? obj, BindingFlags invokeAttr, Binder? binder, Span<object?> parameters, CultureInfo? culture);
}
```

### Risks

Due to the performance impact of having a nullable span versus a simple Span<object?> and the fact that it is possible and very easy to create an empty span without any memory allocation it might be better to not make it nullable, as shown in the "Alternative Designs".

**Comment by teo-tsirpanis** [comment]
You can use the [`System.Reflection.MethodInvoker`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.methodinvoker?view=net-8.0) class which provides an overload of `Invoke` that takes a span. Make sure to reuse method invoker instances for maximum performance.
