### ISSUE TITLE
[browser] Wasm linux/windows HighResource LibrariestTests AOT are failing on build

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#101104]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416
Build error leg or test failing: Build product
Failing jobs on `runtime-extra-platforms`:
- `browser-wasm windows Release LibraryTests_HighResource_AOT`
- `browser-wasm linux Release LibraryTests_HighResource_AOT`

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "Assertion at .*mini-llvm\\.c:6194, condition `lhs' not met",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416
**Error message validated:** `[Assertion at .*mini-llvm\.c:6194, condition `lhs' not met`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/16/2024 6:29:40 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[651298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651298)|dotnet/runtime|[WasmTestOnChrome-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651298&view=ms.vss-test-web.build-test-results-tab&runId=16102506&resultId=169823)||
|[649141](https://dev.azure.com/dnceng-public/public/_build/results?buildId=649141)|dotnet/runtime|[WasmTestOnChrome-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=649141&view=ms.vss-test-web.build-test-results-tab&runId=16045806&resultId=169793)||
|[644416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416)|dotnet/runtime|[normal-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416&view=ms.vss-test-web.build-test-results-tab&runId=15898504&resultId=164499)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|3|

**Comment by pavelsavara** [comment]
There are many more on this [build](https://github.com/dotnet/runtime/pull/100697/checks?check_run_id=23972191760)

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-a1c74cb459404ce6b4/WasmTestOnV8-System.Reflection.MetadataLoadContext.Tests/1/console.841277a9.log?helixlogtype=result)
```
/root/helix/work/correlation/build/wasm-shared/WasmApp.Common.targets(682,5): error : Precompiling failed for /root/helix/work/workitem/e/wasm_build/obj/wasm/for-build/aot-in/System.Private.CoreLib.dll with exit code 1. [/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
/root/helix/work/correlation/build/wasm-shared/WasmApp.Common.targets(682,5): error : * Assertion at /__w/1/s/src/mono/mono/mini/mini-llvm.c:6194, condition `lhs' not met [/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
/root/helix/work/correlation/build/wasm-shared/WasmApp.Common.targets(682,5): error : Aborted (core dumped) [/root/helix/work/workitem/e/publish/ProxyProjectForAOTOnHelix.proj]
```

To replicate, just run `/azp run runtime-wasm`, probably on any branch

**Comment by pavelsavara** [comment]
`System.Reflection.MetadataLoadContext.Tests` could be good candidate to add to the AOT smoke test, so that we would see it break on `runtime` pipeline

**Comment by radekdoulik** [comment]
In browser targeted build I see it assert on:
```
converting llvm method System.Runtime.Intrinsics.Vector64`1<uint16> System.Runtime.Intrinsics.Arm.AdvSimd:Abs (System.Runtime.Intrinsics.Vector64`1<int16>)
* Assertion at /Users/rodo/git/runtime/src/mono/mono/mini/mini-llvm.c:6194, condition `lhs' not met
```

There are 2 problems we need to solve. 

1) The aot compiler is now failing to compile this method:

```
// System.Runtime.Intrinsics.Arm.AdvSimd
public static Vector64<ushort> Abs(Vector64<short> P_0)
{
	throw new PlatformNotSupportedException();
}
```

2) The `System.Runtime.Intrinsics.Arm.AdvSimd` should be linked away and it is not.

@vitek-karas what is the best way to find out why it was preserved during trimming? Still the illink analyzer or do we have some other way to find out?

**Comment by vitek-karas** [comment]
Set `_TrimmerDumpDependencies=True` and `_TrimmerDependenciesFileFormat=dgml` and then use https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot/DependencyGraphViewer to inspect the file. Search for the symbol which was included (and shouldn't be) and then you can walk back to what kept it.

**Comment by radekdoulik** [comment]
Nice, I should try the viewer when I will be on a windows machine. Meanwhile I used the linker analyzer, interestingly it still worked.

```
> illinkanalyzer -t AdvSimd artifacts/obj/System.Text.Json.Tests/Debug//net9.0/browser-wasm/linked/linker-dependencies.xml
Loading dependency tree from: artifacts/obj/System.Text.Json.Tests/Debug//net9.0/browser-wasm/linked/linker-dependencies.xml

--- Type dependencies: 'AdvSimd' ---------------------------------------

--- TypeDef:System.Runtime.Intrinsics.Arm.AdvSimd dependencies ---------
Dependency #1
        TypeDef:System.Runtime.Intrinsics.Arm.AdvSimd
        | Other:/Users/rodo/git/runtime/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/ILLink.Descriptors.xml
...
```

It looks like we are not trimming a lot of stuff after https://github.com/dotnet/runtime/pull/100669 was merged.

The AdvSimd is not trimmed away primarily because of these descriptors https://github.com/dotnet/runtime/pull/100669/files#diff-de4bf248fdfcb99fde3d06fd924756ab0073f5deaf5bb5218288fdc52ce16864R308-R310

@kotlarmilos  It is only affecting tests, I wonder though if we should make the use of these linker descriptors conditional and use them only for ios? I guess it also made browser AOT tests slower on CI and possibly other tests too.
