### ISSUE TITLE
Timeout in System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#101193]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=646861
Build error leg or test failing: System.Text.Json.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/101140

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "Takes very long to run on interpreter.", "System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers", "['System.Text.Json.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=646861
**Error message validated:** `[Takes very long to run on interpreter. System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers ['System.Text.Json.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/17/2024 5:06:43 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
See the discussion in #59678 for context

**Comment by lewing** [comment]
wasm variation 
```
[15:20:31] info: [PASS] System.Text.Json.Tests.Utf8JsonWriterTests.WriteDateTimesValue
[15:20:31] info: [STRT] System.Text.Json.Tests.Utf8JsonWriterTests.WriteDateTimesValue(options: System.Text.Json.JsonWriterOptions, keyString: "message")
[15:20:32] fail: Tests timed out. Killing driver service pid 79
[15:20:32] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by BrzVlad** [comment]
I did a few runs locally and I'm not seeing anything suspicious. It just looks like a heavy suite that takes a long time to run. Also I'm seeing that all these failures are on debug builds. While for jit/aot, debug build doesn't have a big impact, the interpreter execution engine is written in C and it can easily get 3x slower in debug build.

I'm not sure if it easy to do, but I think this test suite should be disabled on interpreter debug builds

**Comment by BrzVlad** [comment]
Disabled suite in debug runtime builds in /github.com/dotnet/runtime/pull/101483

**Comment by lewing** [comment]
reopening since a few builds weren't against the tip of main and hit this, feel free to close again next week

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by eiriktsarpalis** [comment]
Fixed by https://github.com/dotnet/runtime/pull/101556
