### ISSUE TITLE
Backport of #95390 (SignedXml.CheckSignature failing for valid Enveloped signature) seems to have failed

### ISSUE THREAD

**Issue by henning-krause** [dotnet/runtime#101163]
The bugfix for #95390 should have been back-ported to 8.0, according to @bartonjs . But with the latest release in .net 8 I still see the issue.

The preview build for .net 9 is working, though. 

[Nuget](https://www.nuget.org/packages/System.Security.Cryptography.Xml/9.0.0-preview.3.24172.9#versions-body-tab) only has the version 8.0.0 for the System.Security.Cryptography.Xml. 

Does this fix come with the next update? Or did something go wrong with the back-port?

**Comment by vcsjones** [comment]
It looks like this fix barely missed the servicing release for April based on the v8.0.4 tag https://github.com/dotnet/runtime/tree/v8.0.4/src/libraries/System.Security.Cryptography.Xml.

It is in the [release/8.0 branch](https://github.com/dotnet/runtime/tree/release/8.0/src/libraries/System.Security.Cryptography.Xml), so I would expect the fix (and a new 8.0.1 package for S.S.C.Xml) to be in the May servicing release.

**Comment by vcsjones** [comment]
Version 8.0.1 of [System.Security.Cryptography.Xml](https://www.nuget.org/packages/System.Security.Cryptography.Xml/8.0.1) was published today. @henning-krause can you check if this version of the package contains the expected fix?

**Comment by henning-krause** [comment]
@vcsjones The update fixes the issue. Many thanks :-).
