### ISSUE TITLE
Test failure: PlatformNotSupportedException: Blocking wait is not supported on the JS interop threads

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#101100]
```
[01:44:02] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ContentInDifferentThread
[01:44:02] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ContentInDifferentThread(executor1: JSWebWorker, executor2: JSWebWorker)
[01:44:03] warn: [0x05ae0378-jsww 01:44:03.163] [MONO] Process terminated.
[01:44:03] warn: [0x05ae0378-jsww 01:44:03.166] [MONO] CompleteTask: Unexpected synchronous failure (ManagedThreadId 44): System.PlatformNotSupportedException: Blocking wait is not supported on the JS interop threads.
                    at System.Threading.Thread.AssureBlockingPossible()
                    at System.Threading.ManualResetEventSlim.Wait(Int32 , CancellationToken )
                    at System.Threading.ManualResetEventSlim.Wait()
                    at System.Runtime.InteropServices.JavaScript.JavaScriptExports.CompleteTask(JSMarshalerArgument* arguments_buffer)
[01:44:03] info: [0x000ebcbc--UI- 01:44:03.169] MONO_WASM: Dumping web worker info as seen by UI thread, it could be stale:
```
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=644335
Build error leg or test failing: WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/101039

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "PlatformNotSupportedException: Blocking wait is not supported on the JS interop threads.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=644335
**Error message validated:** `[PlatformNotSupportedException: Blocking wait is not supported on the JS interop threads.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/16/2024 1:24:32 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[645086](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645086)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645086&view=ms.vss-test-web.build-test-results-tab&runId=15917038&resultId=100604)|dotnet/runtime#100954|
|[645056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645056)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645056&view=ms.vss-test-web.build-test-results-tab&runId=15916138&resultId=100604)|dotnet/runtime#100949|
|[645041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645041)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645041&view=ms.vss-test-web.build-test-results-tab&runId=15915880&resultId=100604)|dotnet/runtime#100951|
|[645023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645023)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645023&view=ms.vss-test-web.build-test-results-tab&runId=15915492&resultId=100604)|dotnet/runtime#100824|
|[645013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645013)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=645013&view=ms.vss-test-web.build-test-results-tab&runId=15914830&resultId=100604)|dotnet/runtime#100272|
|[644974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644974)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644974&view=ms.vss-test-web.build-test-results-tab&runId=15913924&resultId=185359)|dotnet/runtime#101106|
|[644946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644946)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644946&view=ms.vss-test-web.build-test-results-tab&runId=15912978&resultId=185903)|dotnet/runtime#101103|
|[644970](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644970)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644970&view=ms.vss-test-web.build-test-results-tab&runId=15913508&resultId=100604)|dotnet/runtime#100951|
|[644951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644951)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644951&view=ms.vss-test-web.build-test-results-tab&runId=15912846&resultId=100604)|dotnet/runtime#94970|
|[644913](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644913)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644913&view=ms.vss-test-web.build-test-results-tab&runId=15911664&resultId=100604)|dotnet/runtime#101101|
|[644335](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644335)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644335&view=ms.vss-test-web.build-test-results-tab&runId=15911382&resultId=100604)|dotnet/runtime#101039|
|[644900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644900)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644900&view=ms.vss-test-web.build-test-results-tab&runId=15909872&resultId=100604)|dotnet/runtime#100946|
|[644673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644673)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644673&view=ms.vss-test-web.build-test-results-tab&runId=15908964&resultId=100604)|dotnet/runtime#101082|
|[644773](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644773)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644773&view=ms.vss-test-web.build-test-results-tab&runId=15906776&resultId=100604)|dotnet/runtime#98838|
|[644550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644550)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644550&view=ms.vss-test-web.build-test-results-tab&runId=15901058&resultId=178990)|dotnet/runtime#101017|
|[644622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644622)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644622&view=ms.vss-test-web.build-test-results-tab&runId=15901784&resultId=100604)|dotnet/runtime#99555|
|[644616](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644616)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644616&view=ms.vss-test-web.build-test-results-tab&runId=15901738&resultId=100604)|dotnet/runtime#101087|
|[644611](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644611)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644611&view=ms.vss-test-web.build-test-results-tab&runId=15901530&resultId=100604)|dotnet/runtime#99875|
|[644593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644593)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644593&view=ms.vss-test-web.build-test-results-tab&runId=15900756&resultId=100604)|dotnet/runtime#101076|
|[644500](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644500)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644500&view=ms.vss-test-web.build-test-results-tab&runId=15899762&resultId=100604)|dotnet/runtime#101083|
|[644410](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644410)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644410&view=ms.vss-test-web.build-test-results-tab&runId=15898368&resultId=100604)|dotnet/runtime#100823|
|[644343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644343)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644343&view=ms.vss-test-web.build-test-results-tab&runId=15896646&resultId=100604)|dotnet/runtime#100898|
|[644263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644263)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644263&view=ms.vss-test-web.build-test-results-tab&runId=15894892&resultId=186785)|dotnet/runtime#100664|
|[644152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644152)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644152&view=ms.vss-test-web.build-test-results-tab&runId=15892138&resultId=186305)|dotnet/runtime#100587|
|[644210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644210)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644210&view=ms.vss-test-web.build-test-results-tab&runId=15893440&resultId=100604)|dotnet/runtime#100951|
|[644104](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644104)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644104&view=ms.vss-test-web.build-test-results-tab&runId=15890548&resultId=178980)|dotnet/runtime#101017|
|[643881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643881)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643881&view=ms.vss-test-web.build-test-results-tab&runId=15890716&resultId=186742)|dotnet/runtime#101056|
|[644125](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644125)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644125&view=ms.vss-test-web.build-test-results-tab&runId=15889764&resultId=100604)|dotnet/runtime#99875|
|[644038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644038)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644038&view=ms.vss-test-web.build-test-results-tab&runId=15888240&resultId=179013)|dotnet/runtime#100094|
|[644056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644056)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644056&view=ms.vss-test-web.build-test-results-tab&runId=15888292&resultId=100604)|dotnet/runtime#101038|
|[644058](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644058)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644058&view=ms.vss-test-web.build-test-results-tab&runId=15888278&resultId=100604)|dotnet/runtime#100706|
|[643951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643951)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643951&view=ms.vss-test-web.build-test-results-tab&runId=15886098&resultId=186742)|dotnet/runtime#100765|
|[643885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643885)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643885&view=ms.vss-test-web.build-test-results-tab&runId=15883368&resultId=100167)|dotnet/runtime#100898|
|[643867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643867)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643867&view=ms.vss-test-web.build-test-results-tab&runId=15883472&resultId=186785)|dotnet/runtime#100266|
|[643892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643892)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643892&view=ms.vss-test-web.build-test-results-tab&runId=15883710&resultId=100604)|dotnet/runtime#100949|
|[643833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643833)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643833&view=ms.vss-test-web.build-test-results-tab&runId=15881900&resultId=100604)|dotnet/runtime#100947|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|36|36|

**Comment by pavelsavara** [comment]
re-opening for few dayus of observation
