### ISSUE TITLE
How to use CoSetProxyBlanket in P/Invoke source generator?

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#101157]
How to use CoSetProxyBlanket in P/Invoke source generator?

使用PInvoke和COM源生成改写的代码
Generate the rewritten code using PInvoke and COM sources

        [LibraryImport(Ole32, EntryPoint = "CoCreateInstance", SetLastError = true)]
        public static partial int CoCreateInstance(ref Guid rclsid, IntPtr pUnkOuter, CLSCTX dwClsContext, ref Guid riid, [MarshalUsing(typeof(UniqueComInterfaceMarshaller<object>))]
        out object ppv);

        [LibraryImport("api-ms-win-core-com-l1-1-1.dll")]
        public static partial int CoSetProxyBlanket(
            IntPtr punk,
            uint dwAuthnSvc,
            uint dwAuthzSvc,
            IntPtr pServerPrincName,
            uint dwAuthLevel,
            uint dwImpLevel,
            IntPtr /* RPC_AUTH_IDENTITY_HANDLE */ pAuthInfo,
            uint dwCapabilities);

        public static object GetComObject(Guid clsid, Guid riid)
        {
            int hResult = CoCreateInstance(ref clsid, IntPtr.Zero, CLSCTX.CLSCTX_LOCAL_SERVER, ref riid, out object instance);
            if (hResult != 0)
            {
                throw new COMException("CoCreateInstance failed with the specified error", hResult);
            }
            return instance;
        }

        public static void AllowImpersonation(object proxyObject, ImpersonationLevel impLevel)
        {
            StrategyBasedComWrappers strategyBasedComWrappers = new StrategyBasedComWrappers();
            IntPtr pInterface = strategyBasedComWrappers.GetOrCreateComInterfaceForObject(proxyObject, CreateComInterfaceFlags.None);

            try
            {
                int hResult = CoSetProxyBlanket(pInterface, AuthN_Default, AuthZ_Default, COLE_DefaultPrincipal, AuthLevel_Default,
                    (uint)impLevel, IntPtr.Zero, Auth_StaticCloaking);
                if (hResult != 0)
                {
                    throw new COMException("CoSetProxyBlanket failed", hResult);
                }
            }
            finally
            {
                Marshal.Release(pInterface);
            }
        }

    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
    [GuidAttribute("400E2D4A-1431-4C1A-A748-39CA472CFDB1")]
    [GeneratedComInterface]
    public partial interface IDOManager
    {
        [PreserveSig]
        int CreateDownload([MarshalAs(UnmanagedType.Interface)] out IDODownload download);

        void EnumDownloads(IntPtr enumCategory, [MarshalAs(UnmanagedType.Interface)] out IEnumUnknown ppEnum);
    }

当我调用 CoCreateInstance 创建了 IDOManager COM 接口的实例后，然后调用 AllowImpersonation 方法中的 CoSetProxyBlanket 函数，会出现 COM 异常，错误代码-2147467262
When I create an instance of the IDOManager COM interface by calling CoCreateInstance, and then call the CoSetProxyBlanket function on the AllowImpersonation method, a COM exception occurs. Error code -2147467262

![image](https://github.com/dotnet/runtime/assets/49179966/cc45b25a-ba96-4816-a1e5-a6d015e3136a)

源代码
Source code

        [DllImport("api-ms-win-core-com-l1-1-1.dll")]
        public static extern Int32 CoCreateInstance(
            ref Guid clsid,
            [MarshalAs(UnmanagedType.IUnknown)] object inner,
            uint context,
            ref Guid uuid,
            [MarshalAs(UnmanagedType.IUnknown)] out object rReturnedComObject);

        [DllImport("api-ms-win-core-com-l1-1-1.dll")]
        public static extern Int32 CoSetProxyBlanket(
            [In] IntPtr punk,
            [In] uint dwAuthnSvc,
            [In] uint dwAuthzSvc,
            [In] IntPtr pServerPrincName,
            [In] uint dwAuthLevel,
            [In] uint dwImpLevel,
            [In] IntPtr /* RPC_AUTH_IDENTITY_HANDLE */ pAuthInfo,
            [In] uint dwCapabilities);

        public static object GetComObject(Guid clsid, Guid riid)
        {
            int hResult = CoCreateInstance(ref clsid, null, ClassContext_LocalServer, ref riid, out var instance);
            if (hResult != 0)
            {
                throw new COMException("CoCreateInstance failed with the specified error", hResult);
            }
            return instance;
        }

       public static void AllowImpersonation<TInterface>(object proxyObject, ImpersonationLevel impLevel)
        {
            IntPtr pInterface = Marshal.GetComInterfaceForObject<object, TInterface>(proxyObject);
            try
            {
                int hResult = CoSetProxyBlanket(pInterface, AuthN_Default, AuthZ_Default, COLE_DefaultPrincipal, AuthLevel_Default,
                    (uint)impLevel, IntPtr.Zero, Auth_StaticCloaking);
                if (hResult != 0)
                {
                    throw new COMException("CoSetProxyBlanket failed", hResult);
                }
            }
            finally
            {
                Marshal.Release(pInterface);
            }
        }

    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
    [GuidAttribute("400E2D4A-1431-4C1A-A748-39CA472CFDB1")]
    [ComImportAttribute()]
    public interface IDOManager
    {
        void CreateDownload([MarshalAs(UnmanagedType.Interface)] out IDODownload download);

        void EnumDownloads(IntPtr enumCategory, [MarshalAs(UnmanagedType.Interface)] out IEnumUnknown ppEnum);
    }

仓库链接（Repository Link）：https://github.com/shishirb-MSFT/DODownloaderDotNet

有其他可能的方法，将这个仓库中支持的平台改为 .NET 8+，并支持源生成以兼容AOT吗？
Are there other possible ways to change the platform supported in this repository to.NET 8+ and support source generation to be AOT-compatible?

**Comment by AaronRobinsonMSFT** [comment]
@Gaoyifei1011 The [`CoSetProxyBlanket()`](https://learn.microsoft.com/windows/win32/api/combaseapi/nf-combaseapi-cosetproxyblanket) API is specifically designed to operate on a COM proxy. A plain CCW is not a COM proxy so the API will fail. The API's name implies this and the documentation clearly states the mechanism that is being leveraged here:

> This is a helper function for [IClientSecurity::SetBlanket](https://learn.microsoft.com/en-us/windows/desktop/api/objidl/nf-objidl-iclientsecurity-setblanket).

The `IClientSecurity` interface is part of COM's proxy infrastructure and is implemented by COM when a proxy is created. There are a myriad of ways to create proxies but without details on what is being attempted here it is difficult to provide guidance. Please elaborate on the scenario so we can provide guidance.

**Comment by Gaoyifei1011** [comment]
> @Gaoyifei1011 The [`CoSetProxyBlanket()`](https://learn.microsoft.com/windows/win32/api/combaseapi/nf-combaseapi-cosetproxyblanket) API is specifically designed to operate on a COM proxy. A plain CCW is not a COM proxy so the API will fail. The API's name implies this and the documentation clearly states the mechanism that is being leveraged here:
> 
> > This is a helper function for [IClientSecurity::SetBlanket](https://learn.microsoft.com/en-us/windows/desktop/api/objidl/nf-objidl-iclientsecurity-setblanket).
> 
> The `IClientSecurity` interface is part of COM's proxy infrastructure and is implemented by COM when a proxy is created. There are a myriad of ways to create proxies but without details on what is being attempted here it is difficult to provide guidance. Please elaborate on the scenario so we can provide guidance.

c# simple samples
https://github.com/dahall/Vanara/blob/7de0f5301480fc4126c5bebe0a2dd25d2c2f0886/UnitTests/PInvoke/DOSvc/DOSvcTests.cs#L63

c# full samples
https://github.com/shishirb-MSFT/DODownloaderDotNet

c++ full samples
https://github.com/mmeierm/DO-Downloader/blob/4fc5564453e36dd1abde9d55c8f188a0f59d0e4a/DO-Downloader/DO-Downloader/do-client/download_impl.cpp#L228

The Microsoft official documentation for the detailed delivery optimization example does not provide any further explanation, and I do not know why the CoSetProxyBlanket function is called when setting up the delivery optimization. The c# example worked under CCW, and when I did some fine-tuning and tried to use RCW, an exception was raised.

**Comment by AaronRobinsonMSFT** [comment]
> and I do not know why the CoSetProxyBlanket function is called when setting up the delivery optimization.

That needs to be determined.

> and when I did some fine-tuning and tried to use COM wrappers to support native aot, an exception was raised.

Right, because the generated CCW is not a proxy, but the actual COM object. This API only works on proxies and therefore is not going to work on a non-proxy COM object.

**Comment by Gaoyifei1011** [comment]
> > and I do not know why the CoSetProxyBlanket function is called when setting up the delivery optimization.
> 
> That needs to be determined.
> 
> > and when I did some fine-tuning and tried to use COM wrappers to support native aot, an exception was raised.
> 
> Right, because the generated CCW is not a proxy, but the actual COM object. This API only works on proxies and therefore is not going to work on a non-proxy COM object.

![Screenshot_2024-04-21-11-40-24-610_mark via](https://github.com/dotnet/runtime/assets/49179966/da90857f-c941-42d0-9050-5f0042df626e)
![Screenshot_2024-04-21-11-40-47-628_mark via](https://github.com/dotnet/runtime/assets/49179966/a33958e5-fd01-46e4-934b-815aeeae10d9)
![Screenshot_2024-04-21-11-40-51-171_mark via](https://github.com/dotnet/runtime/assets/49179966/46e699a5-6805-4755-934f-87c83af57f69)
I tried to ask the Big Language Model, and here are some of the answers that the big language model provides

Here are some searched answers
DCOM是依赖于RPC服务的，是一种分布式远程过程（进程）调用，调用代码在远程主机上执行，使用远程主机的系统资源，因此要有远程主机所属的访问权限，一般来说访问用户应是远程主机本地用户或主机所属的域用户，所以

　　第一步是在远程主机或其域上注册（获得）一个有足够权限的用户，

　　第二步是使用此用户令牌激活远程COM服务器，方法是使用CoInitializeSecurity & CoCreateInstanceEx函数(见文后例子)，成功激活后就得到相关请求接口的代理，此时代理并没有对远程服务器访问的权限，

　　第三步是为接口代理设置访问权限，方法是使用CoSetProxyBlanket函数，此后就可以使用代理指针进行方法调用了。见文后例子

　　以上是客户端要做的处理，至于服务器端，只要使用CoInitializeSecurity函数设置一下访问许可权限就可以了（有时客户端也要进行这一处理，比如使用了连接点），对于即存的服务器程序使用dcomcfg工具在注册表里设置也可以。

**Comment by AaronRobinsonMSFT** [comment]
@Gaoyifei1011 I know why one would call `CoSetProxyBlanket`, what I am asking is why do you need to do that for your scenario. Calling this API on a CCW created by `ComWrappers` will never work since the `ComWrappers` API doesn't create proxies.

**Comment by Gaoyifei1011** [comment]
> @Gaoyifei1011 I know why one would call `CoSetProxyBlanket`, what I am asking is why do you need to do that for your scenario. Calling this API on a CCW created by `ComWrappers` will never work since the `ComWrappers` API doesn't create proxies.

Uh, all right. Thank you for your reminding. I thought I could switch from built-in com to comwrappers and continue to call this function normally, so if that doesn't work out, are there other solutions? (I'm sorry, I don't know much about the internal workings of comwrappers and it will take me a lot of time to learn.)
额，好吧。感谢您的提醒。我以为从built-in com切换到comwrappers后可以继续正常调用这个函数，那如果这条道路行不通的话，有其他的解决方案 吗？(很抱歉，我对comwrappers内部的运行机制了解的并不是很深，我可能需要使用大量的时间去学习)

**Comment by AaronRobinsonMSFT** [comment]
I don't think focusing on `ComWrappers` or the built-in system are needed here. The goal should be to understand why the existing code needs `CoSetProxyBlanket()`.

**Comment by AaronRobinsonMSFT** [comment]
Oh, I see now.

> CLSCTX.CLSCTX_LOCAL_SERVER

This is involving an out-of-proc COM server. That means the COM instance is already a proxy, however that also means we need to know all the appropriate RPC interfaces if we wanted to call them. That isn't what you want though. The solution here is to get the underlying COM instance and pass that to `CoSetProxyBlanket()`.

Use [`ComWrappers.TryGetComInstance()`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers.trygetcominstance) to get the underlying `IntPtr` from the `object` instance. The issue here is an attempt is being made to create a CCW for a wrapped RCW. You want the original RCW and pass that down to `CoSetProxyBlanket()`.

**Comment by Gaoyifei1011** [comment]
> Oh, I see now.
> 
> > CLSCTX.CLSCTX_LOCAL_SERVER
> 
> This is involving an out-of-proc COM server. That means the COM instance is already a proxy, however that also means we need to know all the appropriate RPC interfaces if we wanted to call them. That isn't what you want though. The solution here is to get the underlying COM instance and pass that to .`CoSetProxyBlanket()`
> 
> Use [`ComWrappers.TryGetComInstance()`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers.trygetcominstance) to get the underlying from the instance. The issue here is an attempt is being made to create a CCW for a wrapped RCW. You want the original RCW and pass that down to .`IntPtr``object``CoSetProxyBlanket()`

Well, thank you very much. That does solve my problem for the time being
