### ISSUE TITLE
TimeZoneInfo for Antarctica/Casey has incorrect data

### ISSUE THREAD

**Issue by SJShip** [dotnet/runtime#101111]
### Description

TimeZoneInfo for Antarctica/Casey has incorrect data. It contains the wrong UTC offset UTC+11 instead of UTC+8
Please, check the actual information here: https://www.timeanddate.com/worldclock/antarctica/casey

### Reproduction Steps

`TimeZoneInfo antarcticaTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Antarctica/Casey");`
Console.WriteLine(antarcticaTimeZone.BaseUtcOffset); // {11:00:00}

### Expected behavior

It should have the offset UTC+8

### Actual behavior

It has the offset UTC+11

**Comment by Clockwork-Muse** [comment]
The runtime does not maintain or distribute any timezones data, it comes from the host OS.  

On non-Windows systems, this comes from the CLDR data set.  
The most likely situation is that your system has not yet received an update containing the data, as they usually lag behind.  Please verify that your host has actually received such an update first.
