### ISSUE TITLE
How to change the position of Hamburger menu icon - .Net 8 Maui

### ISSUE THREAD

**Issue by VaibhavMethuku01** [dotnet/runtime#101112]
### Description

I recently upgraded my MAUI project from .Net7 to .Net8 and i"m facing some issues with the hamburger icon placement which is distorted after the upgradation

We have tried adding a renderer which is responsible to set the content off on the Nav bar. Here is the code snippet

`WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
{
    if (view.Handler != null)
        ((MauiWinUIWindow)view.Handler.PlatformView)!.ExtendsContentIntoTitleBar = false;
});`

### Reproduction Steps

Create a .Net 8 Maui project and observe the hamburger menu postion.

### Expected behavior

Position of hamburger menu icon should be below the bar 

![image](https://github.com/dotnet/runtime/assets/155944444/45f66605-26dc-4652-bc83-dab1c8aa2c1e)

### Actual behavior

But in Net8 it's not working and this is how it looks, the Hamburger menu is on the Nav bar

![image](https://github.com/dotnet/runtime/assets/155944444/dc609173-d8a1-4ec1-a05d-83575528a271)

**Comment by MichalStrehovsky** [comment]
Hi, please open this in the https://github.com/dotnet/maui repo, this is not the right repo.
