### ISSUE TITLE
We're attempting to retrieve a list of secrets from the AWS Parameter Store using .NET Core 8. To make external API calls, we included a certificate in the Lambda's environment variables with the **key** SSL_CERT_DIR and the **value** /opt/certs. However, after adding this variable, we encountered a certificate error while retrieving data from the parameter store. It worked fine without the SSL_CERT_DIR environment variable. How can we resolve this issue?

### ISSUE THREAD

**Issue by Boxter187** [dotnet/runtime#101280]
We're attempting to retrieve a list of secrets from the AWS Parameter Store using .NET Core 8. To make external API calls, we included a certificate in the Lambda's environment variables with the **key** SSL_CERT_DIR and the **value** /opt/certs. However, after adding this variable, we encountered a certificate error while retrieving data from the parameter store. It worked fine without the SSL_CERT_DIR environment variable. How can we resolve this issue?

.NET 8 uses Amazon Linux 2023 which has OpenSSL 3 versus .NET 6 used Amazon Linux 2 and OpenSSL 1

_Originally posted by @sajanmje in https://github.com/dotnet/runtime/discussions/101274_

**Comment by vcsjones** [comment]
This issue appears to have been opened by mistake. The conversation should be continued in the original discussion.
