### ISSUE TITLE
GetTypes on a collectibe assembly fails under special circumstances

### ISSUE THREAD

**Issue by osen1** [dotnet/runtime#101230]
### Description

- Two assemblies are loaded into a collectible AssemblyLoadContext, one of these (let's call it A) is referencing the other one (let's call it B)
- The version number of the reference is higher than the version number of the actual assembly
- One class in assembly A has a field with an enum defined in B

Loading the assemblies seems to work, but calling assembly.GetTypes afterwards fails with a NotSupportedException "A non-collectible assembly may not reference a collectible assembly".

### Reproduction Steps

Create two assemblies A.DLL and B.DLL , both with "Release" and "Any CPU" with following C# code. 

A.DLL:

```csharp
namespace A
{
  public class ClassA
  {
    private B.ClassB xxx;

    private B.BG bg;

    public static void Main(string[] args)
    {
      new A.ClassA();
    }

    public ClassA()
    {
      xxx = new B.ClassB();
    }
  }
}
```

B.DLL:

```csharp
namespace B
{
  public class ClassB
  {
    public string Name => "B";
  }
}

namespace B
{
  public enum BG
  {
    A,
    B,
    C
  }
}
```

When A.DLL is compiled, Assembly Version and File Version of B.DLL are 57.0.0.0
B.DLL is compiled later again with Assembly Version and File Version set to 56.0.0.0
Now the version numbers of the reference and the actual assembly don't match.

Next, try to load those DLL in the following way:

```csharp
class Program
{
  private static AssemblyLoadContext alc;
  private const string tempPath = @"C:\Temp";

  static void Main(string[] args)
  {
    alc = new AssemblyLoadContext("Temp", true);
    AssemblyLoadContext.Default.Resolving += CurrentAssemblyLoadContextWrapper_Resolving;
    try
    {
      Assembly assemblyA = alc.LoadFromAssemblyPath(Path.Combine(tempPath, "A.DLL"));
      Assembly assemblyB = alc.LoadFromAssemblyPath(Path.Combine(tempPath, "B.DLL"));
      Type[] typesA = assemblyA.GetTypes();    // <--- error
      Type[] typesB = assemblyB.GetTypes();
    }
    finally
    {
      AssemblyLoadContext.Default.Resolving -= CurrentAssemblyLoadContextWrapper_Resolving;
    }
  }

  private static Assembly CurrentAssemblyLoadContextWrapper_Resolving(AssemblyLoadContext arg1, AssemblyName arg2)
  {
    Assembly ret = null;
    string assemblyPath = Path.Combine(tempPath, arg2.Name + ".dll");
    if (File.Exists(assemblyPath))
    {
      ret = alc.LoadFromAssemblyPath(assemblyPath);
    }
    return ret;
  }
}
```

### Expected behavior

Obviously, I except no error "A non-collectible assembly may not reference a collectible assembly".
I don't see where such a reference can possibly exist in this example.
(Maybe that error message could also give some more details to improve clarity?)

### Actual behavior

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'B, Version=57.0.0.0, Culture=neutral, PublicKeyToken=null'. Operation is not supported. (0x80131515)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Test.Program.Main(String[] args)
System.IO.FileLoadException: Could not load file or assembly 'B, Version=57.0.0.0, Culture=neutral, PublicKeyToken=null'. Operation is not supported. (0x80131515)
File name: 'B, Version=57.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.NotSupportedException: A non-collectible assembly may not reference a collectible assembly.
```

### Configuration

Problem occurs in .Net 7 and .Net 8 , I did not try earlier versions.
I am using Windows 11, but I am not sure if it is relevant.

**Comment by huoyaoyuan** [comment]
If I'm correct, the operation should also fail when not using ALC. Assembly A is referencing B version 57.0.0.0, but only B version 56.0.0.0 is loaded.

The error message is incorrect when using ALC.

**Comment by osen1** [comment]
The operation would succeed even if the ALC was non-collectible.
I want to load both assemblies, and later unload them, regardless of their version numbers, therefore my attempt using the Resolving event.

**Comment by vitek-karas** [comment]
My guess without debugging this would be that the resolving handler loads something else beside A and B. Debug this and see if the handler is called for something else and if it actually resolves it.

Otherwise @huoyaoyuan  is correct in that this should basically never work. The runtime should fail the resolution if the reference is higher version than the resolved assembly version.

**Comment by osen1** [comment]
Yes, the Resolving handler finds the correct B.DLL, it returns the same assembly object according to "Make Object-ID"

While I agree that the standard behaviour should probably not allow loading wrong reference versions, there should be a way to overrule it. Besides, why does it fail only in such a very specific case then, with an enum field present and so on?

**Comment by vitek-karas** [comment]
> Besides, why does it fail only in such a very specific case then, with an enum field present and so on?

The CoreCLR type loader is very "lazy" - so calling just `GetTypes` will try to avoid loading too much stuff, but that depends on the shape of the types and so on. The exact behavior when it should fail is undefined.

**Comment by osen1** [comment]
>  The exact behavior when it should fail is undefined.

@vitek-karas , You mean, it should fail, and it should be impossible by design to load and work with assemblies that have an older version number than expected by a reference?

If so, it is surprising that it works in most cases. Particularly if the AssemblyLoadContext isn't collectible. I am confident that I have reduced the code example to the minimum, and that's why it looks to me that some unintended behaviour (if not bug) is going on here.

**Comment by vitek-karas** [comment]
> The exact behavior when it should fail is undefined.

The meaning of this was in the context of your question of why it fails if there's an enum field present. If the type graph has problems in it (for example a missing assembly) then it's not defined when it will fail. The runtime is free to not fail as long as it can make things work - which is mostly what it's doing by being very lazy about things.

**Comment by agocke** [comment]
Unfortunately being more aggressive about erroring is likely a breaking change for another group of users. I don't foresee us intentionally favoring certain behavior here.
