### ISSUE TITLE
[wasi] Enable debugger support using wasi preview/2 apis

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#101253]
https://github.com/bytecodealliance/wasmtime/issues/3936 makes it impossible to enable filesystem access and the debugger in wasmtime using preview 1 apis.  We should start preview 2 work with enabling the debugger.

**Comment by lewing** [comment]
cc @pavelsavara @thaystg

**Comment by pavelsavara** [comment]
This is fixed by https://github.com/dotnet/runtime/pull/109584
