### ISSUE TITLE
ComVariantMarshaller type bug

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#101275]
### Description

![image](https://github.com/dotnet/runtime/assets/49179966/009ec2bb-113d-4a0e-8536-926ac0ac2ca5)
The ComVariantMarshaller is for type object, shouldn't it be a ComVariant struct?

### Reproduction Steps

See description

### Expected behavior

    [CustomMarshaller(typeof(ComVariant), MarshalMode.Default, typeof(ComVariantMarshaller))]
    [CustomMarshaller(typeof(ComVariant), MarshalMode.UnmanagedToManagedRef, typeof(RefPropagate))]
    public static partial class ComVariantMarshaller

### Actual behavior

    [CustomMarshaller(typeof(object), MarshalMode.Default, typeof(ComVariantMarshaller))]
    [CustomMarshaller(typeof(object), MarshalMode.UnmanagedToManagedRef, typeof(RefPropagate))]
    public static partial class ComVariantMarshaller

### Regression?

None

### Known Workarounds

None

### Configuration

None

### Other information

None

**Comment by jkoritzinsky** [comment]
The `ComVariantMarshaller` marshals `object`s to `ComVariant` instances. `ComVariant`s can be passed to unmanaged code directly, they're blittable.

**Comment by Gaoyifei1011** [comment]
> The `ComVariantMarshaller` marshals `object`s to `ComVariant` instances. `ComVariant`s can be passed to unmanaged code directly, they're blittable.

Ok, I see. Thank you for your answer
