### ISSUE TITLE
LNK2001 Error When Linking Static Library with NativeAOT Project

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#101209]
Hello,

I'm encountering an LNK2001 error when trying to link a static library to my NativeAOT project. The error arises specifically when I do not use extern "C" __declspec(dllexport); however, using this directive makes the method names visible, which is not desirable for my use case.

![image](https://github.com/dotnet/runtime/assets/111659964/ea461990-460b-4678-b9df-f6e79a0721e1)

Could you please provide guidance on how to properly link a static library in NativeAOT while keeping the method names hidden, or suggest any workaround for this issue?

My csproj file:

![image](https://github.com/dotnet/runtime/assets/111659964/9fe35e38-9c7e-448e-86a3-feda48e83341)

Imports:

![image](https://github.com/dotnet/runtime/assets/111659964/1de75e49-878f-42df-ae33-a1f29ea8f13b)

Thank you for your assistance.

**Comment by jkotas** [comment]
Try exporting your entrypoints as `extern "C"` - add the following to near the top of your .cpp file:
```
extern "C" void Hook_Initialize();
extern "C" void CreateHook(void*, void*, void**);
```

**Comment by dadavadd** [comment]
> extern "C" void Hook_Initialize();
> extern "C" void CreateHook(void*, void*, void**);

Thank!
