### ISSUE TITLE
Expression.New() validator throws exception on implicit conversion of structs to interfaces

### ISSUE THREAD

**Issue by haavapet** [dotnet/runtime#101296]
### Description

When invoking Expression.New(), implicit conversion of structs to interfaces gets thrown as an error by a validator, even though roslyn supports this implicit conversion.

### Reproduction Steps

``` C#
using System.Reflection;
using System.Linq.Expressions;
using System.Linq;

// Implicit conversion works with roslyn for structs
StructImplementingInterface a = new();
StructInjectingInterface b = new(a);

ConstructorInfo ci = typeof(StructInjectingInterface).GetConstructors().Single();

// Expressions works for structs when explicitly converted
Expression.New(ci, Expression.Convert(Expression.Constant(a), typeof(MyInterface)));

// xpression works for classes with implicit conversion
Expression.New(ci, Expression.Constant(new ClassImplementingInterface()));

 // This throws argument exception, even though it can be implicitly converted
Expression.New(ci, Expression.Constant(a));

public interface MyInterface {}

struct StructImplementingInterface : MyInterface {
      public StructImplementingInterface() {}
}

class ClassImplementingInterface : MyInterface {
      public ClassImplementingInterface() {}
}

struct StructInjectingInterface {
      public StructInjectingInterface(MyInterface a) {}
}
```

### Expected behavior

Expression.New() should not throw an error here as this conversion can be done implicitly

### Actual behavior

Expression.New() throws and error in a validator

### Known Workarounds

Wrap the struct in a Expression.Convert(struct, interfaceType)

**Comment by colejohnson66** [comment]
Expressions are a representation of how the code will actually function. Implicit casts are still logic that has to be performed, hence why you need to use `Convert`. Specifically, this code:

```cs
MyInterface i = new StructImplementingInterface();
```

is actually treated by the compiler like this:

```cs
MyInterface i = (MyInterface)new StructImplementingInterface();
```

You just don’t have to write it like that.
