### ISSUE TITLE
[Jit] Recognize FMA pattern and Emit Fused Multiply Add (when available)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#10137]
e.g.

```csharp
float r =  a * b + c;
      r =  a * b - c;
      r =  c + a * b;
      r = -c + a * b;
Vector3 vR3 = v0 * v1 + v2;
// etc
Vector4 vR4 = v3 * v4 + v5;
// etc
```

Its a bit of a mine field on x86 https://en.wikipedia.org/wiki/FMA_instruction_set

> The incompatibility between Intel's FMA3 and AMD's FMA4 is due to both companies changing plans without coordinating coding details with each other. AMD changed their plans from FMA3 to FMA4 while Intel changed their plans from FMA4 to FMA3 almost at the same time. The history can be summarized as follows:
>
> * August 2007: AMD announces the SSE5 instruction set, which includes 3-operand FMA instructions. A new coding scheme (DREX) is introduced for allowing instructions to have three operands.[11]
> * April 2008: Intel announces their AVX and FMA instruction sets, including 4-operand FMA instructions. The coding of these instructions uses the new VEX coding scheme,[12] which is more flexible than AMD's DREX scheme.
> * December 2008: Intel changes the specification for their FMA instructions from 4-operand to 3-operand instructions. The VEX coding scheme is still used.[13]
> * May 2009: AMD changes the specification of their FMA instructions from the 3-operand DREX form to the 4-operand VEX form, compatible with the April 2008 Intel specification rather than the December 2008 Intel specification.[14]
> * October 2011: AMD Bulldozer processor supports FMA4.[15]
> * January 2012: AMD announces FMA3 support in future processors codenamed Trinity and Vishera; they are based on the Piledriver architecture.[16]
> * May 2012: AMD Piledriver processor supports both FMA3 and FMA4.[15]
> * June 2013: Intel Haswell processor supports FMA3.[17]
> * February 2017 The first generation of AMD Ryzen processors officially supports FMA3, but not FMA4 according to the CPUID instruction.[18] There has been confusion regarding whether FMA4 was implemented or not on this processor due to errata in the initial patch to the GNU Binutils package that has since been rectified.[19][20] While the FMA4 instructions seem to work according to some tests, they can also give wrong results.[7] Additionally, the initial Ryzen CPUs could be crashed by a particular sequence of FMA3 instructions. It has since been resolved by an updated CPU microcode.[21]

category:cq
theme:basic-cq
skill-level:expert
cost:medium

**Comment by tannergooding** [comment]
Closing this. We have explicit `FusedMultiplyAdd` APIs and will likely cover any future "pick the better of MultiplyAdd or FusedMultiplyAdd" via an explicit `MultiplyAddEstimate` API.
