### ISSUE TITLE
[API Proposal]: Expand GetValueOrDefault in CollectionExtensions to allow IDictionary, not just IReadOnlyDictionary

### ISSUE THREAD

**Issue by KyleMit** [dotnet/runtime#101311]
### Background and motivation

This is a pretty useful utility method, and there doesn't seem to be any reason why it couldn't apply to all dictionary types more broadly, rather than only on read only dicts.

### API Proposal

Update the following code

https://github.com/dotnet/runtime/blob/d28c577b78e0ed67a6c9cec989a3f155563c5753/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/CollectionExtensions.cs#L11-L22

```diff
- public static TValue? GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key) =>
+ public static TValue? GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key) =>
      dictionary.GetValueOrDefault(key, default!);
  
- public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, TValue defaultValue)
+ public static TValue GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key, TValue defaultValue)
  {
      if (dictionary is null)
      {
          ThrowHelper.ThrowArgumentNullException(ExceptionArgument.dictionary);
      }
  
      return dictionary.TryGetValue(key, out TValue? value) ? value : defaultValue;
  }

```

### API Usage

```csharp
IDictionary<string, string> things = new Dictionary<string, string>()
{
   { "apple", "A fruit" },
   { "car", "A vehicle" },
   { "book", "A written work" }
};

Console.WriteLine(things.GetValueOrDefault("apple"));

Console.WriteLine(things.GetValueOrDefault("unknown"));
```

> **Note** the above example works if you use `var` to initialize `things` because [`Dictionary`][1] natively implements `IReadOnlyDictionary`.  But there are many instances where a dictionary is passed via the interface, not the instance.

[1]: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-8.0

### Alternative Designs

Continue using standard API

```cs
myDict.TryGetValue("myKey", out var myValue) ? myValue: null;
```

Or individual projects bring their own extension method

### Risks

None that I'm aware of

### [Demo in dotnet fiddle](https://dotnetfiddle.net/3prRWz)

Happy to submit a PR if this makes sense

**Comment by colejohnson66** [comment]
Nit: backwards compatibility prevents changing method signatures. This proposal, if approved, would require a whole new method with the desired signature.

**Comment by stephentoub** [comment]
As of https://github.com/dotnet/runtime/pull/95830, every IDictionary will be an IReadOnlyDictionary. At that point, nothing additional is needed here. 

Also, as noted the existing signature can't be changed, and an overload for IDictionary can't be added because (until the aforementioned PR), it would be ambiguous for collections that implement both.

**Comment by KyleMit** [comment]
Good points - thanks for the replies!
