### ISSUE TITLE
Decompressing GZipStream produces invalid data

### ISSUE THREAD

**Issue by TETYYS** [dotnet/runtime#101351]
### Description

`GZipStream` with a specific file produces output that contains additional bytes

Comparison. `Source` is decompressed by .NET, `Target` is proper file

| Compare Type | Source Offset | Source Count (dec) | Source Count (hex) | Target Offset | Target Count (dec) | Target Count (hex) |
| - | - | - | - | - | - | - |
| Matched | 00000000 | 32947 | 80B3 | 00000000 | 32947 | 80B3 |
| Inserted | 000080B3 | 2 | 02 | 000080B3 | 0 | 00 |
| Matched | 000080B5 | 567809 | 0008AA01 | 000080B3 | 567809 | 0008AA01 |
| Inserted | 00092AB6 | 1 | 01 | 00092AB4 | 0 | 00 |
| Matched | 00092AB7 | 4969804 | 004BD54C | 00092AB4 | 4969804 | 004BD54C |
| Inserted | 00550003 | 2 | 02 | 00550000 | 0 | 00 |

### Reproduction Steps

```
using System.IO.Compression;

using (FileStream outputFileStream = File.Open("charmap_dotnet.bin", FileMode.CreateNew)) {
    using (FileStream originalFileStream = File.Open("charmap.bin.gz", FileMode.Open)) {
        using (GZipStream decompressionStream = new GZipStream(originalFileStream, CompressionMode.Decompress)) {
            while (true) {
                var bX = new byte[sizeof(float)];
                if (decompressionStream.Read(bX, 0, sizeof(float)) == 0) {
                    break;
                }
                var b = (byte)decompressionStream.ReadByte();

                outputFileStream.Write(bX, 0, sizeof(float));
                outputFileStream.WriteByte(b);
            }
        }
    }
    outputFileStream.Flush();
    outputFileStream.Close();
}
```
[charmap.bin.gz](https://github.com/dotnet/runtime/files/15052321/charmap.bin.gz)

### Expected behavior

```
$ dotnet run
$ sha256sum charmap_dotnet.bin
0b4f082af29232f8fa9f71fabb518fa4a83ef24d5e5da5b6d1f895f7e396d645 *charmap_dotnet.bin
$ gunzip charmap.bin.gz -k
$ sha256sum charmap.bin
0b4f082af29232f8fa9f71fabb518fa4a83ef24d5e5da5b6d1f895f7e396d645 *charmap.bin
```

### Actual behavior

```
$ dotnet run
$ sha256sum charmap_dotnet.bin
102c7154339da61eb555383dc9f4b2bd5e440db1f4d45baea4c9ea77082612d6 *charmap_dotnet.bin
$ gunzip charmap.bin.gz -k
$ sha256sum charmap.bin
0b4f082af29232f8fa9f71fabb518fa4a83ef24d5e5da5b6d1f895f7e396d645 *charmap.bin
```

### Regression?

netcoreapp3.1: 0b4f082af29232f8fa9f71fabb518fa4a83ef24d5e5da5b6d1f895f7e396d645 *charmap_dotnet.bin
net5.0: 0b4f082af29232f8fa9f71fabb518fa4a83ef24d5e5da5b6d1f895f7e396d645 *charmap_dotnet.bin
net6.0: 102c7154339da61eb555383dc9f4b2bd5e440db1f4d45baea4c9ea77082612d6 *charmap_dotnet.bin
net7.0: 102c7154339da61eb555383dc9f4b2bd5e440db1f4d45baea4c9ea77082612d6 *charmap_dotnet.bin
net8.0: 102c7154339da61eb555383dc9f4b2bd5e440db1f4d45baea4c9ea77082612d6 *charmap_dotnet.bin

### Configuration

- Which version of .NET is the code running on?
```
Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- What OS and version, and what distro if applicable?
dotnet run on Windows 22H2 19045.4170, gunzip on mingw64
- What is the architecture (x64, x86, ARM, ARM64)?
x64

**Comment by Tornhoof** [comment]
You're ignoring the actual length of the First Read call, there is no guarantee it will fully populate the byte array.

**Comment by TETYYS** [comment]
Is it expected that while file is perfectly aligned for 4 and 1 byte reads, synchronous read from file system could return less bytes? Why did it change between .NET versions?

**Comment by Tornhoof** [comment]
It was just an implementation Detail that it worked, the Stream API never changed, people just used it wrong. They used it wrong that often, that there is now ``ReadAtLeast`` 
https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readatleast?view=net-8.0#system-io-stream-readatleast(system-span((system-byte))-system-int32-system-boolean)

**Comment by TETYYS** [comment]
It would be interesting to know why it behaves that way and why is it on these exact same bytes every time

**Comment by huoyaoyuan** [comment]
See #64577 #71517 #62954 and so on.

> It would be interesting to know why it behaves that way and why is it on these exact same bytes every time

It is the result of deflater. A blocked with a length can be decompressed into a different length. It's the decompressed end of the first block of default read size.

**Comment by TETYYS** [comment]
Thanks, I believe the conclusion would be https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams
