### ISSUE TITLE
ParameterInfo.DefaultValue with invalid universal chars has inconsistent behavior across runtimes

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#101332]
From https://github.com/dotnet/runtime/pull/100939#discussion_r1573084111:
```c#
class Test
{
    static void Main()
    {
        Console.WriteLine((int)(((string)typeof(Test).GetMethod("M").GetParameters()[0].DefaultValue)[0]));
        M();
    }

    public static void M(string mangledKey = "\uD800\u1111") { Console.WriteLine((int)(mangledKey[0])); }
}
```
output is different across runtimes:
AOT: 65533 and 55296
JIT: 55296 and 55296

Regression: No, it repros with .NET 8 and 9.

**Comment by jkotas** [comment]
This is duplicate / related to https://github.com/dotnet/runtimelab/issues/803 . I have just transferred this issue from runtimelab. We have some tests disabled against it.

**Comment by am11** [comment]
Close as duplicate of #101333.
