### ISSUE TITLE
NativeAOT metadata encodings

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#101333]
NativeAOT metadata internally uses UTF-8 encoding to encode strings (things like names of types, or string literals, for reflection purposes).

The System.Runtime tests have a bunch of test cases with InlineDataAttribute that contains string literals with values that cannot be represented in UTF-8 (basically, invalid codepoints, such as "high surrogate" without a low surrogate).

When NativeAOT compiler generates metadata for these, we replace these with replacement characters. Unit test failures ensue.

Wondering whether we should roll our own UTF-8 encoder and decoder that simply passes the invalid codepoints through instead of crippling them. They can be represented - the encoders/decoders are just being told by the spec not to do that.

Alternatively we could also just ditch UTF-8 and store the UTF-16 code units as compressed integers. Or use compressed integers for the entire Unicode code point.

**Comment by agocke** [comment]
I'm not worried about this -- it's about error recovery for invalid strings.
