### ISSUE TITLE
[RyuJit] Allow TYP_BYREF folding.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#10132]
Right now `ValueNumStore::VNForFunc` has such code:
https://github.com/dotnet/coreclr/blob/b800f37c504d30c25bda3bdf148966fa91d17381/src/jit/valuenum.cpp#L1100-L1105

but there are no reasons why we can't support it, it looks like we should just change this part:
https://github.com/dotnet/coreclr/blob/b800f37c504d30c25bda3bdf148966fa91d17381/src/jit/valuenum.cpp#L1812

From discussion in dotnet/coreclr#17506 .

category:cq
theme:value-numbering
skill-level:intermediate
cost:small
impact:small

**Comment by EgorBo** [comment]
Closed via https://github.com/dotnet/runtime/pull/85888
