### ISSUE TITLE
CultureInfo gives incorrect information

### ISSUE THREAD

**Issue by MdeBruin93** [dotnet/runtime#101383]
### Description

The `CultureInfo` class gives wrong information.

I'm not sure how many Cultures are affected by this, but this doesn't seem right.

![Schermafbeelding 2024-04-22 160334](https://github.com/dotnet/runtime/assets/16732519/04dadcd7-c203-4659-9181-c093bead6d0a)

### Reproduction Steps

Create a console app using .NET 8 template.
Insert code:
`var cult = CultureInfo.GetCultureInfo("BEL");

var tmp = cult.DisplayName;
Console.WriteLine(cult.ThreeLetterISOLanguageName);
Console.WriteLine(tmp);

var cult2 = CultureInfo.GetCultureInfo("BLR");
Console.WriteLine(cult2.ThreeLetterISOLanguageName);
Console.WriteLine(cult2.DisplayName);`

### Expected behavior

When instantiating the `CultureInfo` class with the 3 letter ISO code "BEL" I expect to get the display name "Belgum". And with "BLR" I expect to get "Belarus".

### Actual behavior

When instantiating the `CultureInfo` class with the 3 letter ISO code "BEL" I'm getting the display name "Belarus" which is incorrect.

### Regression?

I reckon it worked before, but I haven't touched these classes in quite some time so can't tell you when it started.

**Comment by danmoseley** [comment]
Is it possible to check the result on some older .NET versions, like 7 and 6..

**Comment by MdeBruin93** [comment]
I've just tested it with those versions. .NET 7 also give me the same bug, .NET 6 does show the correct values for these Cultures.
I have not tested other Cultures.

**Comment by tarekgh** [comment]
To note, there is `RegionInfo` class which can be used to instantiate with the two letters ISO code of any region. Like doing ` var r = new RegionInfo("BE");` which will create `Belgium` region object. or you can enumerate cultures to see which one match the 3-letter ISO code as 

```C#
            foreach (CultureInfo c in CultureInfo.GetCultures(CultureTypes.SpecificCultures))
            {
                var ri = new RegionInfo(ci.Name);
                if (ri.ThreeLetterISORegionName.Equals("BEL", StringComparison.OrdinalIgnoreCase))
                {
                    Console.WriteLine($"{ri.Name} ... {ri.DisplayName} ... {ri.EnglishName} ... {ri.NativeName} ... {ri.ThreeLetterISORegionName} ... {ri.ThreeLetterWindowsRegionName} ... {ri.TwoLetterISORegionName}");
                    break;
                }
            }
```
