### ISSUE TITLE
Named pipes on MacOS can't connect in .NET 8

### ISSUE THREAD

**Issue by Jasper2213** [dotnet/runtime#101366]
### Description

I'm trying to use named pipes in .NET MAUI, but when testing on MacOS, the client can't connect to the server, it just hangs on connect.

When running the project with .NET 7, the client connects to the server on both Windows and MacOS.

### Reproduction Steps

1. Clone the [reproduction repo](https://github.com/Jasper2213/named-pipes)
2. Open the net-8 solution
3. Run the Server and Client at the same time

### Expected behavior

Client connects to Server and Server can send a message to Client

### Actual behavior

Client can't connect to Server, instead hangs at `_pipeClient.ConnectAsync()`

### Regression?

Worked on .NET 7, doesn't work on .NET 8.

**Comment by wfurt** [comment]
This  actually is `Socket` problem IMHO. It boils down to waking pending I/O on UnixDomainSocket. 
I wrote `System.Net.Sockets.Tests.UnixDomainSocketTest.UdsReceiveGetsCanceledByDispose` test (similar to we have for UDP & TCP) and it works as expected on Linux but hangs on maOC. 

tagging @tmds in case he wants to take a look. I did quick test with 6,.0 and it hangs as well as far as I can tell. So the claim it worked in 7.0 is surprising to me.

**Comment by wfurt** [comment]
I commented on wrong issue. It can still be `Socket` problem as the Named Pipes use unix domain socket under the cover.

**Comment by wfurt** [comment]
Your code is different between 7 and 8 versions @Jasper2213. At least in the provided example the 7.0 project use `ConnectAsync` and the `InitPipeClient` is marked as `async` so it will never block and hang on thread pool. 

In 8.0 you use synchronous connect and that will block everything until connected until connected. In my quick test I did not have server running yet but the application hangs in weird state while 7.0 looks responsive .... even if the socket is not actually connected., 

When I make the 7.0 and 8.0 version same I see same behavior e.g. I do not see regression.

**Comment by Jasper2213** [comment]
I updated the code in the .NET 8 project to match that of the .NET 7 project (can't believe I missed that).
This indeed doesn't fix the problem.

**Comment by vitek-karas** [comment]
Closing as answered.
