### ISSUE TITLE
cdac src/coreclr/runtime.proj(96,5): error MSB3073

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#101471]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=653289
Build error leg or test failing: Build / osx-arm64 release Runtime_Debug / Build product
Pull request: https://github.com/dotnet/runtime/pull/101329

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "src/coreclr/runtime.proj(96,5): error MSB3073",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=653289
**Error message validated:** `[src/coreclr/runtime.proj(96,5): error MSB3073`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/24/2024 2:41:26 AM UTC

**Comment by lewing** [comment]
cc @lambdageek

**Comment by jkotas** [comment]
The actual error is "Specific version of clang not found". It is a regression introduced by https://github.com/dotnet/arcade/pull/14696#issuecomment-2072281350 .

It seems to be impacting number of repos.
