### ISSUE TITLE
[Perf] Span/IndexerBench/KnownSizeArray(length:1024) regression of ~277% on x86

### ISSUE THREAD

**Issue by valenis** [dotnet/runtime#10145]
**[Perf] Span/IndexerBench/KnownSizeArray(length:1024) regression of ~277% on x86**

Regression can be seen in Benchview - CoreCLR/Master branch from [commit](https://github.com/dotnet/coreclr/compare/94ab205d5545699a49cc54d72e9d3d07a454f10a...dotnet:4456cc99ba0fbe3c02be3a9f54c34282caeb7218). Orange dotted line is the Release v2.0 baseline. This is affecting x86 only.

![image](https://user-images.githubusercontent.com/19602715/38752900-8f1c9aac-3f11-11e8-90ca-8393cdf46a74.png)

**Comment by CarolEidt** [comment]
The inner loop code now looks like this:
```
G_M36199_IG04:
       movzx    ecx, byte  ptr [edi+ebx]
       xor      edx, ecx
       movzx    edx, dl
       inc      ebx
       cmp      ebx, eax
       jl       SHORT G_M36199_IG04
```
So, although no real changes have been made to loop backedge splitting, it seems that the issue no longer exists.
