### ISSUE TITLE
MIssing runtime deps for 8.0.4

### ISSUE THREAD

**Issue by KnHell** [dotnet/runtime#101413]
Hi,

When trying to manually install aspnetcore 8.0.4 on a centos linux box, the runtime deps package is missing:
--> Finished Dependency Resolution
Error: Package: dotnet-runtime-8.0-8.0.4-1.x86_64 (packages-microsoft-com-prod)
           Requires: dotnet-runtime-deps-8.0 >= 8.0.4
           Installed: dotnet-runtime-deps-8.0-8.0.3-1.x86_64 (installed)
               dotnet-runtime-deps-8.0 = 8.0.3-1
           Available: dotnet-runtime-deps-8.0-8.0.0-1.x86_64 (packages-microsoft-com-prod)
               dotnet-runtime-deps-8.0 = 8.0.0-1
           Available: dotnet-runtime-deps-8.0-8.0.1-1.x86_64 (packages-microsoft-com-prod)
               dotnet-runtime-deps-8.0 = 8.0.1-1
           Available: dotnet-runtime-deps-8.0-8.0.2-1.x86_64 (packages-microsoft-com-prod)
               dotnet-runtime-deps-8.0 = 8.0.2-1

This package is also not present in https://packages.microsoft.com/centos/8/prod/Packages/d/ where all the packages for the different dotnet versions are located. Note that the 8.0.3 deps package is present

**Comment by NikolaMilosavljevic** [comment]
@leecow it appears that `dotnet-runtime-deps-8.0-8.0.4-1.x86_64.rpm` package is not available in https://packages.microsoft.com/centos/8/prod/Packages/d/

**Comment by leecow** [comment]
Sorry for the inconvenience. Fixed up and CentOS 8 test good for 8.0.4.
