### ISSUE TITLE
[API Proposal]: Determine Reference Type Nullability during runtime

### ISSUE THREAD

**Issue by hexxone** [dotnet/runtime#101438]
### Background and motivation

Im currently building an ASP .NET6 Core API with EF-Core. I have enabled "Nullabe" types for the entire solution.

For the purpose of this issue, we have a "Plant" DTO class which may look like this:

```csharp
public class Plant { 
    [Key]
    public int Id {get; set;} // auto-increment

    [Required]
    [StringLength(64)]
    public string MainGuid {get; set;} // always set

    [StringLength(64)]
    public string? OptionalGuid {get; set;} // same as Nullable<string>

    public int? Yield {get;set;} // same as Nullable<int>
}
```

Now, at runtime, I need to find out which of the properties are _actually_ nullable, including those of type string.

The problem is that `Nullabe.GetUnderlyingType(...)` only works for value properties like "Yield", as explained here: 
- <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types>

Finding out whether a reference type is marked as Nullable<T> seems to be done only at (pre)compile time, with no information given on how to get this information at runtime: 
- <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types>

Further hours of digging then led me here:
- <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis>

It seems that the compiler will create a [NullableAttribute] for the properties. But this only happens during compile-time, and we cannot normally reference this Attribute because it is only availabe to the Compiler itself.

So if I didnt miss anything, there is currently no easy way to distinguish a "string" from a "string?" Property after compilation using standard Reflection, which is undesirable.

### API Proposal

The only way I found to accomplish what I need was Referencing the [Namotion.Reflection](https://github.com/RicoSuter/Namotion.Reflection) Nuget Package:  <https://www.nuget.org/packages/Namotion.Reflection/>

and then modifying the "IsNullable" function from the example like so:

```csharp

public static bool IsNullable(this PropertyInfo property)
{
    return Nullable.GetUnderlyingType(property.PropertyType) != null 
        || property.ToContextualProperty().Nullability == Nullability.Nullable;
}
```

Instead of having to include a Third-Party library for gaining this funtionality, it would be highly preferred to have it built-in to the Reflection Std-Lib for Properties, Fields, etc.

For example: 

```csharp
class Nullable {

    public bool IsNullableReference(PropertyInfo prop) { /** ... */ }

    public bool IsNullableReference(FieldInfo field) { /** ... */ }
}
```

Then we could simplify the function like so:

```csharp

public static bool IsNullable(this PropertyInfo property)
{
    return Nullable.GetUnderlyingType(property.PropertyType) != null 
        || Nullable.IsNullableReference(property);
}
```

### API Usage

```csharp

public class Plant {
    [Key]
    public int Id {get; set;}

    [Required]
    [StringLength(64)]
    public string MainGuid {get; set;} // always set

    [StringLength(64)]
    public string? OptionalGuid {get; set;} // the same as Nullable<string>

    public int? Yield {get;set;} // the same as Nullable<int>
}

var plantType = typeof(Plant);
var plantProps = plantType.GetProperties();

// Getting the Nullability
foreach (var p in plantProps)
    Console.WriteLine(p.Name + " = " + p.IsNullable());

// Before the Change
// Id = false
// MainGuid = false
// OptionalGuid = false
// Yield = true

// After the change 
// Id = false
// MainGuid = false
// OptionalGuid = true  <--- should be desirable
// Yield = true
```

### Alternative Designs

Using a third-party library works for now, but getting to this workaround cost me a lot of time in reading docs and trial & error.

### Risks

I know, using Reflection is generally slow and considered bad practice, but in some places unavoidable.

The User should take great care to implement a "cache" layer on top of this functionality, and the documentation should hint at these facts accordingly. Otherwise, performance regressions are to be expected.

**Comment by teo-tsirpanis** [comment]
You can use the [`NullabilityInfoContext`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.nullabilityinfocontext?view=net-8.0) type to get reference type nullability information at runtime.

**Comment by hexxone** [comment]
> You can use the [`NullabilityInfoContext`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.nullabilityinfocontext?view=net-8.0) type to get reference type nullability information at runtime.

Thanks for the quick reply! This is actually exactly what I am looking for.

Its just sad that there aren't any other Links, references or information about this given on the docs I mentioned above.
Could have really saved some time there.

Any chance that we can update these Docs to include the information?

**Comment by colejohnson66** [comment]
Documentation issues go in dotnet/dotnet-api-docs
