### ISSUE TITLE
[API Proposal]: Enumerable.SequenceEqual

### ISSUE THREAD

**Issue by AshbyGeek** [dotnet/runtime#101448]
### Background and motivation

Implementing instances of IEqualityComparer so that you can use linq to compare lists is a frustrating experience. It would not be hard to add a lambda based SequenceEqual comparison as a compliment to the currently available overloads and could provide much greater flexibility. 

### API Proposal

```csharp
namespace System.Linq;

public static partial class Enumerable
{
    internal static bool SequenceEqual<T1,T2>(this IEnumerable<T1> first, IEnumerable<T2> second, Func<T1, T2, bool> comparer)
    {
        if (first is null)
        {
            throw new ArgumentNullException(nameof(first));
        }
        if (second is null)
        {
            throw new ArgumentNullException(nameof(second));
        }
    
        if (first is ICollection<T1> firstCol && second is ICollection<T2> secondCol)
        {
            if (firstCol.Count != secondCol.Count)
            {
                return false;
            }
    
            if (firstCol is IList<T1> firstList && secondCol is IList<T2> secondList)
            {
                int count = firstCol.Count;
                for (int i = 0; i < count; i++)
                {
                    if (!comparer(firstList[i], secondList[i]))
                    {
                        return false;
                    }
                }
    
                return true;
            }
        }
    
        using IEnumerator<T1> e1 = first.GetEnumerator();
        using IEnumerator<T2> e2 = second.GetEnumerator();
        while (e1.MoveNext())
        {
            if (!(e2.MoveNext() && comparer(e1.Current, e2.Current)))
            {
                return false;
            }
        }
    
        return !e2.MoveNext();
    }
}
```

### API Usage

```csharp

public record StuffWithId(string Id, int stuff);
public record DifferentStuffWithId(string Id, float otherStuff);

var list1 = new List<StuffWithId>(new StuffWithId("1A", 1));
var list2 = new List<DifferentStuffWithId>(new DifferentStuffWithId("1A", 0.1));

bool areEqual = list1.SequenceEqual(list2, (x,y) => x.Id == y.Id);
```

### Alternative Designs

First alternative: Make a generic implementation of IEqualityComparer that accepts lambda functions
    - is easier to use than current implementation
    - preserves the performance gains from the Span.SequenceEqual shortcut path
    - is less flexible because it expects both lists to contain the same type
    - is less convenient because it is more verbose

 Something like:
```csharp
public class RelayEqualityComparer<T> : IEqualityComparer<T>
{
    private Func<T?, T?, bool> _Comparer;
    private Func<T, int> _HashFunction;

    public RelayEqualityComparer(Func<T, T, bool> comparer, Func<T, int> hashFunction)
    {
        _Comparer = comparer;
        _HashFunction = hashFunction;
    }

    public bool Equals(T? x, T? y) 
    {
        if (x is null && y is null) return true;
        else if (x is not null || y is not null) return false;
        return _Comparer.Invoke(x, y);
    }

    public int GetHashCode([DisallowNull] T obj) => _HashFunction.Invoke(obj);
}
```
 
Second alternative: expose an overload that allows a lambda based comparison but then converts it to an IEquatable implementation. Something like this:
```csharp
SequenceEqual<T>(this IEnumerable<T> list1, IEnumerable<T> list2, Func<T, T, bool> comparer)
{
    var relay = new RelayEqualityComparer(comparer, null);
    list1.SequenceEqual(list2, relay);
}
```
 - doesn't require duplicating segments of the SequenceEqual code
 - gives a similar user experience to the first proposal
 - not as flexible as the first proposal, as both lists will have to have the same type argument

### Risks

The first proposal risks unexpected performance differences between it and existing SequenceEquals implementations due to the dropped AsSpan shortcut path. However, SequenceEquals(ReadOnlySpan<T> ...) falls back to a simple loop comparison when an IEqualityComparer is specified bypassing its greatest performance shortcuts. That means an equivalently performing overload could be made using a delegate instead of the IEqualityComparer.

**Comment by reflectronic** [comment]
There is a method [`EqualityComparer.Create`](https://learn.microsoft.com/dotnet/api/system.collections.generic.equalitycomparer-1.create), new in .NET 8, which takes lambda expressions (one for `Equals`, and optionally one for `GetHashCode`). So, I think the 'alternative' designs are already covered.

So, this proposal is only for the case where `T1` != `T2`.

**Comment by colejohnson66** [comment]
If `T1`!=`T2` a `Select` can be utilized to extract what you actually want to compare. Won’t solve all cases, but for the example of comparing integer IDs, it would.

**Comment by eiriktsarpalis** [comment]
> If so, then this proposal aught to be broadened to include all methods that use an equality comparer. Should I do so?

That's going to be *a lot* of methods, and wouldn't be restricted to System.Linq. We opted for shipping [EqualityComparer.Create](https://learn.microsoft.com/dotnet/api/system.collections.generic.equalitycomparer-1.create) as a low-cost accelerator that doesn't involve duplicating almost every API that uses customized equality comparison.

**Comment by AshbyGeek** [comment]
If I opened a pull request with implementations based on EqualityComparer.Create for all the appropriate LINQ methods (I feel like its more important in LINQ than elsewhere) with unit tests would it be considered? I understand that there are concerns beyond just the initial code.

Methods I would add an override for:
System.Linq
-----------
- Enumerable.AggregateBy
- Enumerable.Contians
- Enumerable.Distinct
- Enumerable.DistinctBy
- Enumerable.Except
- Enumerable.ExceptBy
- Enumerable.GroupBy
- Enumerable.GroupJoin
- Enumerable.Intersect
- Enumerable.IntersectBy
- Enumerable.Join
- Enumerable.SequenceEqual
- Enumerable.Union
- Enumerable.UnionBy
- ParallelEnumerable.Contains
- ParallelEnumerable.Distinct 
- ParallelEnumerable.DistinctBy
- ParallelEnumerable.Except
- ParallelEnumerable.GroupBy
- ParallelEnumerable.GroupJoin
- ParallelEnumerable.Intersect
- ParallelEnumerable.Join
- ParallelEnumerable.SequenceEqual
- ParallelEnumerable.Union
- Queryable.Contains
- Queryable.Distinct
- Queryable.DistinctBy
- Queryable.Except
- Queryable.ExceptBy
- Queryable.GroupBy
- Queryable.GroupJoin
- Queryable.Intersect
- Queryable.IntersectBy
- Queryable.Join
- Queryable.SequenceEqual
- Queryable.Union
- Queryable.UnionBy

System.Private.CoreLib -> src/System/MemoryExtensions.cs
-------------------------
- SequenceEqual
- CommonPrefixLength

**Comment by eiriktsarpalis** [comment]
It's simply that it's duplicating too many APIs to address a problem which has a workaround. For better or for worse, IEqualityComparer<T> is the de facto standard for customizing equality comparison. cc @terrajobst @bartonjs

**Comment by AshbyGeek** [comment]
ok, understood.
