### ISSUE TITLE
[mono] Mono doesn't respect explicit size for structures when marked with LayoutKind.Sequential

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#101432]
Mono doesn't respect explicit struct size when combined with sequential layout, i.e., when using `[StructLayout(LayoutKind.Sequential, Size = X)]`, the structure doesn't have the desired size `X`.

Repro code:
```
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential, Size = 12)]
struct F3_S0_S0
{
    public nint F0;
    public uint F1;

    public F3_S0_S0(nint f0, uint f1)
    {
        F0 = f0;
        F1 = f1;
    }
}

private static void Main(string[] args)
{
    Console.WriteLine(Marshal.SizeOf(typeof(F3_S0_S0)));
}
```

Mono output:
```
16
```

CoreCLR output:
```
12
```

**Comment by lambdageek** [comment]
This goes back a long time to 6fcc7591fa9e6657e44766abb21bfa5ae1e0d103
> ```
>   * class.h, class.h: take minimum alignment into consideration so
>    that the fields of a class remain aligned also when in an array.
> ```

Here:

https://github.com/dotnet/runtime/blob/2e75aac8dbbae5420a93f6fbe9568812dbeb3472/src/mono/mono/metadata/class-init.c#L2391-L2396

**Comment by jakobbotsch** [comment]
It's more evidence that something like #100896 is necessary, even without gneerics. These kind of struct layouts are necessary to model Swift structures in C#. cc @jkoritzinsky 

@matouskozak if you are blocked on the Swift work I can give you some instructions on generating the Swift unit tests with `ExplicitLayout`.

**Comment by lambdageek** [comment]
What happens in swift if you allocate an array of frozen structs that have a size that is not a multiple of the minimum alignment of any members? Do the array elements end up packing tightly and misaligning the members?

**Comment by jakobbotsch** [comment]
Swift has the notion of "stride" for this:

https://github.com/apple/swift/blob/4b440a1d80a0900b6121b6e4a15fff2a96263bc5/docs/ABI/TypeLayout.rst#fragile-struct-and-tuple-layout

> The final size and alignment are the size and alignment of the aggregate. The stride of the type is the final size rounded up to alignment.

I believe the stride is used for array allocations, but for struct layout Swift allows fields to pack into the "tail padding" of previous structures, like as follows:
```csharp
[StructLayout(LayoutKind.Sequential, Size = 12)]
struct F3_S0_S0
{
    public nint F0;
    public uint F1;

    public F3_S0_S0(nint f0, uint f1)
    {
        F0 = f0;
        F1 = f1;
    }
}

[StructLayout(LayoutKind.Sequential, Pack = 16)]
public struct S
{
  public F3_S0_S0 S;
  public int X; // at offset 12
}
```

**Comment by lambdageek** [comment]
> I believe the stride is used for array allocations, but for struct layout Swift allows fields to pack into the "tail padding" of previous structures, like as follows:

that makes sense, thanks

**Comment by lambdageek** [comment]
Fixed in https://github.com/dotnet/runtime/pull/101529
