### ISSUE TITLE
Arm64/Sve Test: Inputs for LoadVector API test

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#101475]
From the discussion at https://github.com/dotnet/runtime/pull/101291#discussion_r1574046599, we should make sure that we use some decent mask values in `LoadVector` and `StoreVector` APIs to exercise and test the functionality of these APIs.
- A mask containing mix of 0s and 1s
- A mask containing all 0s
- A mask containing all 1s
- Non-faulting should never throw exception even if invalid address such as `0x0` is passed to `LoadVector`.
- Faulting APIs throws exception when invalid address such as `0x0` is passed to `LoadVector`.
- In faulting APIs, inactive elements do not throw exception when invalid address is given to it.

**Comment by kunalspathak** [comment]
@a74nh @SwapnilGaikwad PTAL for .NET 9

**Comment by a74nh** [comment]
priority:2 for RC1 snap : Missing testing. However it's at the lower end compared to the other testing issues. There's always a chance of the existing testing using all 1s or all 0s etc. If there is a functionality issue we'd have _probably_ spotted it by now. However, there is still a chance we might not have.

**Comment by mikabl-arm** [comment]
I'll work on this.

**Comment by a74nh** [comment]
Assigning to my on behalf of @mikabl-arm
