### ISSUE TITLE
System.Text.Json.Tests.Utf8JsonWriterTests.WritingTooDeep failure

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#101470]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=652336
Build error leg or test failing: System.Text.Json.Tests.Utf8JsonWriterTests.WritingTooDeep
Pull request: https://github.com/dotnet/runtime/pull/101379

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.", "t System.Text.Json.Utf8JsonWriter.Grow(Int32 requiredSize)"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=652336
**Error message validated:** `[System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown. t System.Text.Json.Utf8JsonWriter.Grow(Int32 requiredSize)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/24/2024 2:35:37 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[653219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653219)|dotnet/runtime|[System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawMaxUtf16InputLength](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653219&view=ms.vss-test-web.build-test-results-tab&runId=16157124&resultId=104359)||
|[652336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652336)|dotnet/runtime|[System.Text.Json.Tests.Utf8JsonWriterTests.WritingTooDeep](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652336&view=ms.vss-test-web.build-test-results-tab&runId=16134266&resultId=203356)|dotnet/runtime#101379|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|2|

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/101379/checks?check_run_id=24173515403

**Comment by lewing** [comment]
@jeffhandley these tests are OOMing across multiple runtimes

**Comment by eiriktsarpalis** [comment]
This was presumably regressed by https://github.com/dotnet/runtime/pull/100890 which added more test cases to the writer options.

**Comment by carlossanlop** [comment]
I wonder if this failure is affecting more tests than the ones narrowed down by the ErrorMessage in this issue's json description. 

Specifically, I'm referring to:

- Timeouts: https://github.com/dotnet/runtime/issues/101522
- Dead lettering: https://dev.azure.com/dnceng-public/public/public%20Team/_build/results?buildId=654910&view=logs&j=0eae1e18-ea37-5071-1d48-9384b3d4e672&t=7c50f1ca-0ae5-5055-6835-fe157eafc276&l=59
