### ISSUE TITLE
PhysicalFileProviderTests.TokensFiredOnFileDeleted fails

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#101401]
```
C:\h\w\B6E8093C\w\B57C09CF\e>"C:\h\w\B6E8093C\p\dotnet.exe" exec --runtimeconfig Microsoft.Extensions.FileProviders.Physical.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.FileProviders.Physical.Tests.deps.json xunit.console.dll Microsoft.Extensions.FileProviders.Physical.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Microsoft.Extensions.FileProviders.Physical.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.FileProviders.Physical.Tests (found 82 of 92 test cases)
  Starting:    Microsoft.Extensions.FileProviders.Physical.Tests (parallel test collections = on [2 threads], stop on fail = off)
    Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokensFiredOnFileDeleted [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.cs(500,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokensFiredOnFileDeleted()
        --- End of stack trace from previous location ---
  Finished:    Microsoft.Extensions.FileProviders.Physical.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Extensions.FileProviders.Physical.Tests  Total: 193, Errors: 0, Failed: 1, Skipped: 0, Time: 106.048s
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=651616
Build error leg or test failing: Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokensFiredOnFileDeleted
Pull request: https://github.com/dotnet/runtime/pull/101373

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokensFiredOnFileDeleted [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=651616
**Error message validated:** `[Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokensFiredOnFileDeleted [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/22/2024 9:23:46 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by Jozkee** [comment]
If this comes up again, we could try increasing the [timeout](https://github.com/dotnet/runtime/blob/015b7edebbe7eadb267fede52905d5e246d1ebb9/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.cs#L498).
