### ISSUE TITLE
[QUIC] Add minimal testing to MsQuic CI

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#101589]
Add minimal tests on all the same platforms that runtime CI uses.
This is needed to verify that the produced library is loadable and to prevent regressions like Alpine Arm32 https://github.com/dotnet/runtime/issues/91757

By minimal test I mean a .NET application that would at least check `QuicConnection.IsSupported`, and it might also have a minimal send-receive test. This obviously can be expanded if we ever feel the need to.

We don't need a rolling build, I assume this might be only needed if we update MsQuic - so the testing leg only needs a manual trigger, if it is easier to do so.

**Comment by CarnaViire** [comment]
Another type of regression, added functionality broke Linux distros beside Ubuntu: https://github.com/dotnet/runtime/issues/101625 (https://github.com/microsoft/msquic/pull/3849, https://github.com/microsoft/msquic/pull/4264)

**Comment by liveans** [comment]
Initial implementation is here: [liveans/play-with-docker-github-actions](https://github.com/liveans/play-with-docker-github-actions)
Next step: Integrate it into `msquic` PR pipeline

**Comment by liveans** [comment]
I think we can close this now, since we have some basic test on msquic pipeline.
