### ISSUE TITLE
System.Text.Json.Tests timeout in Linux-Debug-x64-Mono_Interpreter_Debug-Ubuntu.2204.Amd64.Open

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#101508]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=654452
Build error leg or test failing: System.Text.Json.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/100743

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "EXECUTION TIMED OUT",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=654452
**Error message validated:** `[EXECUTION TIMED OUT`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/24/2024 6:03:13 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[654914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654914)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654914&view=ms.vss-test-web.build-test-results-tab&runId=16206422&resultId=100001)|dotnet/runtime#101499|
|[654927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654927)|dotnet/runtime|[WasmTestOnChrome-System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654927&view=ms.vss-test-web.build-test-results-tab&runId=16206730&resultId=179108)|dotnet/runtime#101392|
|[654382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654382)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654382&view=ms.vss-test-web.build-test-results-tab&runId=16206588&resultId=203617)|dotnet/runtime#101192|
|[654452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654452)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654452&view=ms.vss-test-web.build-test-results-tab&runId=16205236&resultId=203617)|dotnet/runtime#100743|
|[654860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654860)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654860&view=ms.vss-test-web.build-test-results-tab&runId=16205122&resultId=203655)|dotnet/runtime#100094|
|[653807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653807)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653807&view=ms.vss-test-web.build-test-results-tab&runId=16205082&resultId=203617)|dotnet/runtime#101442|
|[654571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654571)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654571&view=ms.vss-test-web.build-test-results-tab&runId=16204620&resultId=203617)|dotnet/runtime#101291|
|[654787](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654787)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654787&view=ms.vss-test-web.build-test-results-tab&runId=16202662&resultId=203617)|dotnet/runtime#100949|
|[654744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654744)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654744&view=ms.vss-test-web.build-test-results-tab&runId=16201972&resultId=203617)|dotnet/runtime#101330|
|[653322](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653322)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653322&view=ms.vss-test-web.build-test-results-tab&runId=16201738&resultId=203618)|dotnet/runtime#101188|
|[654715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654715)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654715&view=ms.vss-test-web.build-test-results-tab&runId=16201682&resultId=203617)|dotnet/runtime#101492|
|[654688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654688)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654688&view=ms.vss-test-web.build-test-results-tab&runId=16201216&resultId=203617)|dotnet/runtime#100918|
|[654316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654316)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654316&view=ms.vss-test-web.build-test-results-tab&runId=16201052&resultId=203617)|dotnet/runtime#101469|
|[654653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654653)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654653&view=ms.vss-test-web.build-test-results-tab&runId=16199836&resultId=114688)|dotnet/runtime#100697|
|[654627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654627)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654627&view=ms.vss-test-web.build-test-results-tab&runId=16198852&resultId=104516)||
|[654664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654664)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654664&view=ms.vss-test-web.build-test-results-tab&runId=16200034&resultId=203617)|dotnet/runtime#101449|
|[654610](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654610)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654610&view=ms.vss-test-web.build-test-results-tab&runId=16198780&resultId=104516)||
|[654606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654606)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654606&view=ms.vss-test-web.build-test-results-tab&runId=16198760&resultId=104516)||
|[654628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654628)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654628&view=ms.vss-test-web.build-test-results-tab&runId=16198738&resultId=104516)||
|[654649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654649)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654649&view=ms.vss-test-web.build-test-results-tab&runId=16199620&resultId=100604)|dotnet/runtime#101250|
|[654644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654644)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654644&view=ms.vss-test-web.build-test-results-tab&runId=16199550&resultId=203617)|dotnet/runtime#101447|
|[654588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654588)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654588&view=ms.vss-test-web.build-test-results-tab&runId=16198068&resultId=203617)|dotnet/runtime#101480|
|[654556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654556)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654556&view=ms.vss-test-web.build-test-results-tab&runId=16197306&resultId=203617)|dotnet/runtime#101478|
|[654532](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654532)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654532&view=ms.vss-test-web.build-test-results-tab&runId=16196836&resultId=203617)|dotnet/runtime#100775|
|[654504](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654504)|dotnet/runtime|[WasmTestOnChrome-System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654504&view=ms.vss-test-web.build-test-results-tab&runId=16196394&resultId=186920)||
|[654434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654434)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654434&view=ms.vss-test-web.build-test-results-tab&runId=16194422&resultId=203617)|dotnet/runtime#101474|
|[652161](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652161)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652161&view=ms.vss-test-web.build-test-results-tab&runId=16193110&resultId=203608)|dotnet/runtime#101294|
|[654360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654360)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654360&view=ms.vss-test-web.build-test-results-tab&runId=16192758&resultId=203617)|dotnet/runtime#101461|
|[654330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654330)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654330&view=ms.vss-test-web.build-test-results-tab&runId=16192168&resultId=203617)|dotnet/runtime#101101|
|[654212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654212)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654212&view=ms.vss-test-web.build-test-results-tab&runId=16192034&resultId=203617)|dotnet/runtime#101460|
|[654303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654303)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654303&view=ms.vss-test-web.build-test-results-tab&runId=16190810&resultId=203617)|dotnet/runtime#101468|
|[654293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654293)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654293&view=ms.vss-test-web.build-test-results-tab&runId=16190340&resultId=203617)|dotnet/runtime#101451|
|[653784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653784)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653784&view=ms.vss-test-web.build-test-results-tab&runId=16190220&resultId=203655)|dotnet/runtime#100094|
|[654135](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654135)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654135&view=ms.vss-test-web.build-test-results-tab&runId=16185734&resultId=203618)|dotnet/runtime#101457|
|[653837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653837)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653837&view=ms.vss-test-web.build-test-results-tab&runId=16185254&resultId=203617)|dotnet/runtime#101445|
|[653747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653747)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653747&view=ms.vss-test-web.build-test-results-tab&runId=16182784&resultId=203617)|dotnet/runtime#95830|
|[653721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653721)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653721&view=ms.vss-test-web.build-test-results-tab&runId=16182760&resultId=203617)|dotnet/runtime#100993|
|[654018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654018)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654018&view=ms.vss-test-web.build-test-results-tab&runId=16181230&resultId=203617)|dotnet/runtime#101451|
|[653949](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653949)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653949&view=ms.vss-test-web.build-test-results-tab&runId=16179318&resultId=203617)|dotnet/runtime#101416|
|[653946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653946)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653946&view=ms.vss-test-web.build-test-results-tab&runId=16179244&resultId=203617)|dotnet/runtime#101450|
|[653937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653937)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653937&view=ms.vss-test-web.build-test-results-tab&runId=16179018&resultId=203617)|dotnet/runtime#101439|
|[653929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653929)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653929&view=ms.vss-test-web.build-test-results-tab&runId=16178832&resultId=203617)|dotnet/runtime#101418|
|[653932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653932)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653932&view=ms.vss-test-web.build-test-results-tab&runId=16178846&resultId=203617)|dotnet/runtime#101449|
|[653924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653924)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653924&view=ms.vss-test-web.build-test-results-tab&runId=16178332&resultId=203591)||
|[653918](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653918)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653918&view=ms.vss-test-web.build-test-results-tab&runId=16178298&resultId=203617)|dotnet/runtime#101447|
|[653833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653833)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653833&view=ms.vss-test-web.build-test-results-tab&runId=16176242&resultId=203621)|dotnet/runtime#99490|
|[653823](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653823)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653823&view=ms.vss-test-web.build-test-results-tab&runId=16175448&resultId=203617)|dotnet/runtime#101443|
|[653816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653816)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653816&view=ms.vss-test-web.build-test-results-tab&runId=16175130&resultId=203617)|dotnet/runtime#100266|
|[652022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652022)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652022&view=ms.vss-test-web.build-test-results-tab&runId=16174478&resultId=203609)|dotnet/runtime#101381|
|[653677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653677)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653677&view=ms.vss-test-web.build-test-results-tab&runId=16171706&resultId=203617)|dotnet/runtime#100697|
|[653657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653657)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653657&view=ms.vss-test-web.build-test-results-tab&runId=16170848&resultId=203617)|dotnet/runtime#101428|
|[653607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653607)|dotnet/runtime|[WasmTestOnChrome-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653607&view=ms.vss-test-web.build-test-results-tab&runId=16170106&resultId=177468)|dotnet/runtime#101397|
|[653643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653643)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653643&view=ms.vss-test-web.build-test-results-tab&runId=16170250&resultId=203618)|dotnet/runtime#100951|
|[653622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653622)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653622&view=ms.vss-test-web.build-test-results-tab&runId=16169890&resultId=203618)|dotnet/runtime#100489|
|[653617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653617)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653617&view=ms.vss-test-web.build-test-results-tab&runId=16169768&resultId=203618)|dotnet/runtime#100580|
|[653616](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653616)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653616&view=ms.vss-test-web.build-test-results-tab&runId=16169750&resultId=203618)|dotnet/runtime#101429|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|49|56|56|

**Comment by fanyang-mono** [comment]
This is seen on CI lane `android-arm Release AllSubsets_Mono` as well. See log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-101442-merge-550867abf6fb4b0da0/System.Text.Json.Tests/1/console.fb61a682.log?helixlogtype=result

**Comment by lewing** [comment]
The pattern is too broad here and until https://github.com/dotnet/dnceng/issues/2628 rolled out (just happened) the existing issues would not always match the failure.  I'm closing this to avoid calling every timeout in any lane a knownbuilderror
