### ISSUE TITLE
Unable to cancel NamedPipeClientStream reads on MacOS

### ISSUE THREAD

**Issue by codecat** [dotnet/runtime#101539]
### Description

I am unable to cancel reads on `NamedPipeClientStream` on MacOS, as it seems to deadlock when closing the reader.

### Reproduction Steps

The following code reproduces the problem on MacOS, but works fine on both Windows and Linux:

```cs
using System.IO.Pipes;

new Thread(() => {
	using var host = new NamedPipeServerStream(
		"cstest_pipes",
		PipeDirection.InOut,
		NamedPipeServerStream.MaxAllowedServerInstances,
		PipeTransmissionMode.Byte,
		PipeOptions.Asynchronous
	);

	Console.WriteLine("Host: Waiting for connection..");
	host.WaitForConnection();

	Console.WriteLine("Host: Connected :)");

	while (true) {
		Thread.Sleep(1000);
	}
}).Start();

using var client = new NamedPipeClientStream(".", "cstest_pipes", PipeDirection.InOut, PipeOptions.Asynchronous);

Console.WriteLine("Client: Connecting..");
client.Connect(TimeSpan.FromSeconds(1));

Console.WriteLine($"Client: Connected: {client.IsConnected}");

var cts = new CancellationTokenSource();
var ct = cts.Token;

using var reader = new BinaryReader(client);
using var readerReg = ct.Register(reader.Close);

new Task(async () => {
	Console.WriteLine("Client: Cancelling in 500ms..");
	await Task.Delay(TimeSpan.FromMilliseconds(500));

	Console.WriteLine("Client: Cancelling..");
	cts.Cancel();

	Console.WriteLine("Client: Cancelled :)");
}).Start();

while (!ct.IsCancellationRequested) {
	Console.WriteLine("Client: Reading byte..");
	try {
		var b = reader.ReadByte();
		Console.WriteLine($"Client: Byte received: 0x{b:02x}");
	} catch (Exception) {
		Console.WriteLine("Client: Exception caught while reading byte");
		break;
	}
}

Console.WriteLine("Client: Disconnected :)");
```

### Expected behavior

On stream close, I expect any existing reads to be cancelled and throw an exception. In other words, I expect the output of the above program to be something like this:

```
Client: Connecting..
Host: Waiting for connection..
Client: Connected: True
Client: Reading byte..
Host: Connected :)
Client: Cancelling in 500ms..
Client: Cancelling..
Client: Exception caught while reading byte
Client: Cancelled :)
Client: Disconnected :)
```

### Actual behavior

In this case, a deadlock occurs between the stream closing and the stream being read from. In the example code above, the output of the program locks up here:

```
Host: Waiting for connection..
Client: Connected: True
Client: Reading byte..
Host: Connected :)
Client: Cancelling in 500ms..
Client: Cancelling..
```

### Configuration

Tested with SDK `9.0.100-preview.3.24204.13` (it happens on `8.0.203` as well)
MacOS Sonoma 14.4.1, arm64

**Comment by codecat** [comment]
I was able to work around this by writing a stream class that reads from the pipe stream using ReadAsync and waits for the result, as I can pass a `CancellationToken` to it.

**Comment by wfurt** [comment]
I put up PR with  fix but that is unlikely to meet servicing bar for 8.0 @codecat. 
another workaround would be something like 
```c#
using var readerReg = ct.Register(() =>
{
    var s = new Socket(new SafeSocketHandle(client.SafePipeHandle.DangerousGetHandle (), ownsHandle: false));
    s.Shutdown(SocketShutdown.Both);
    reader.Close();
});
```

**Comment by codecat** [comment]
Interesting, thanks for the tip! As another workaround, we've switched to using the cancelled cancellable ReadAsync which in some ways feels better, but in others not so much (have to create an intermediate class to ReadAsync everything which might become pretty slow).
