### ISSUE TITLE
Cannot inject HTTPClient into an IHostedService using HTTPClientFactory

### ISSUE THREAD

**Issue by glennc** [dotnet/runtime#101561]
### Description

I expected to be able to use HttpClientFactory and HostedServices together in the code sample, I expect there is a reason that this doesn't work that makes sense but I have no idea what it is.

### Reproduction Steps

```csharp
var builder = Host.CreateApplicationBuilder(args);

builder.AddServiceDefaults();

//Expectation: The HTTPClient I inject into the Worker class has its base address configured.
builder.Services.AddHttpClient<Worker>(c=>c.BaseAddress = new Uri("https://someuri"));
builder.Services.AddHostedService<Worker>();

var host = builder.Build();
host.Run();

public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;
    private readonly HttpClient _client;

    public Worker(ILogger<Worker> logger, HttpClient client)
    {
        _logger = logger;
// the HTTPClient here is not created with the configuration I expected, no base address.
        _client = client;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            if (_logger.IsEnabled(LogLevel.Information))
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            }
            await Task.Delay(1000, stoppingToken);
        }
    }
}
```

### Expected behavior

HTTPClient is configured as expected.

### Actual behavior

Default HTTPClient is injected.

### Regression?

I doubt it.

### Known Workarounds

Just inject the factory, the workaround isn't hard.

### Configuration

.NET 8

**Comment by glennc** [comment]
Yeah, that makes sense as a workaround as well and I think if I had any form of processing to do on the HTTP requests I would do that rather than inject it directly anyway.

I assumed the registrations as IHostedService had something to do with why this didn't work but still thought the code intuitive enough to create an issue to see if it was possible to make happen.

**Comment by LeaFrock** [comment]
You use the `AddHttpClient` incorrectly. Even if you inject a standalone `WorkerHttp`, you're still required to know something as `Worker` is a singleton service.

I suggest you reading this [doc](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory#avoid-typed-clients-in-singleton-services) which is a very good guidance.

**Comment by CarnaViire** [comment]
> The host looks for IHostedService services and gets an instance of Worker, but when the DI container constructs this instance, it does not care about the Worker service. And so the Worker instance gets just the default HttpClient.

Yeah. Also, the only reason it even gets the HttpClient injected is because a (default) HttpClient is registered as a transient service with a factory that does
https://github.com/dotnet/runtime/blob/f4b06109929b96ea570c38ef912f2a851985aa86/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L68

**Comment by CarnaViire** [comment]
If you'd REALLY want to inject HttpClient into the HostedService, while understanding the limitations (as @LeaFrock mentioned, HttpClient will essentially be a singleton, so you'd need to "manually" make sure the DNS changes are respected via `PooledConnectionLifetime`), you can also pick one of the two workarounds:

1. Register a singleton HttpClient without any use of HttpClientFactory -- if you don't need any specific setup

<details>

```c#
builder.Services.AddSingleton(() =>
{
    // make sure DNS changes are picked up
    var handler = new SocketsHttpHandler() { PooledConnectionLifetime = TimeSpan.FromMinutes(2) };
    return new HttpClient(handler) { BaseAddress = new Uri("https://someuri") };
});

//...

public class Worker : BackgroundService
{
    public Worker(ILogger<Worker> logger, HttpClient client)
    {
        _client = client;
//...
```

</details>

2. Use Keyed services registration of a Named client instead of a Typed client

<details>

```c#
// register named client in HttpClientFactory
builder.Services.AddHttpClient(nameof(Worker), c => c.BaseAddress = new Uri("https://someuri"))
    // make sure DNS changes are picked up
    .UseSocketsHttpHandler((h, _) => h.PooledConnectionLifetime = TimeSpan.FromMinutes(2))
    .SetHandlerLifetime(Timeout.InfiniteTimeSpan);

// register that client as a Keyed service
builder.Services.AddKeyedSingleton(nameof(Worker), (sp, _) => sp.GetRequiredService<IHttpClientFactory>().CreateClient(nameof(Worker)));

//...

public class Worker : BackgroundService
{
    public Worker(ILogger<Worker> logger, [FromKeyedServices(nameof(Worker))] HttpClient client)
    {
        _client = client;
//...
```

</details>

**Comment by CarnaViire** [comment]
Closing as answered above.
Let me know if you need any additional help/explanations.
