### ISSUE TITLE
WCF service with DataContract and EnumValues not returning enum values in result

### ISSUE THREAD

**Issue by nealculiner** [dotnet/runtime#101594]
### Description

I'm in the process of migrating a Xamarin.iOS app to net8.0-ios. I'm finding that some WCF service methods are broken which seem to be related to the wrong serializer being used from what I can tell. I'm using Visual Studio 2022 17.9.6 which is the latest as of this writing. It's a basic WCF service call to a service I host which returns a DataContract with an array of a class which contains an Enum. The enum is decorated with DataContract and each Enum value is decorated with EnumValue and there is an assignment for the 0 value. No matter what I try the enum value is always 0 in the returned array containing a list of this enum object. There are no DataSets in the return value as I've read there is an issue in net8-ios with using the Xml serializer instead of the DataContract serializer. Does anyone have any tips to resolve this as it seems WCF is broken in net8.0-ios.

### Steps to Reproduce

Basic WCF service with a class marked with DataContract and enum values marked with EnumValue. I return a List of a class that contains this enum as one of the properties. The enum always comes across as 0.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17

**Comment by agocke** [comment]
Without custom steps, XML Serializer isn't trim safe. If this is supposed to work in xamarin-ios then there is a bug in the custom steps. Otherwise, XMLSerializer is marked RUC so this is not expected to work through trimming.

**Comment by agocke** [comment]
Looks like I can't move issues cross-org, so I'm going to close this and link from a new issue.
