### ISSUE TITLE
iOS test failing with Keychain 'signing-certs.keychain-db' was not found (disabled device)

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#101502]
```log
['iOS.Device.ExportManagedSymbols.Test' END OF WORK ITEM LOG: Command exited with 22]
```

## Build Information

Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=654860
Build error leg or test failing: iOS.Device.Aot.Test.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/100094

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Keychain 'signing-certs.keychain-db' was not found",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=654860
**Error message validated:** `[Keychain 'signing-certs.keychain-db' was not found`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/25/2024 7:37:31 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by steveisok** [comment]
@vitek-karas I think this might be an infra build problem as I think the app isn't being properly signed. If that's the case, it may be a machine issue.

**Comment by akoeplinger** [comment]
Yes if you check the console log you'll see
> Keychain 'signing-certs.keychain-db' was not found

I fixed the error message pattern in the build analysis.

This is an infra issue. @dotnet/dnceng

**Comment by adamsitnik** [comment]
> I fixed the error message pattern in the build analysis.

**Comment by AlitzelMendez** [comment]
> Yes if you check the console log you'll see
> 
> > Keychain 'signing-certs.keychain-db' was not found
> 
> I fixed the error message pattern in the build analysis.
> 
> This is an infra issue. @dotnet/dnceng

I have taken the impacted machines offline while I work on fixing the underlying problem

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by vitek-karas** [comment]
@matouskozak could you please check if this is still happening? Otherwise close it please.

**Comment by matouskozak** [comment]
No longer happening, issue was closed https://github.com/dotnet/dnceng/issues/2667
