### ISSUE TITLE
JsonSerializer throws error if the property is a Func<> or delegate

### ISSUE THREAD

**Issue by SanjayVyas** [dotnet/runtime#1015]
JsonSearilizer throws exception if it comes across a delegate method

```using System;
using System.Text.Json;
class Rule
{
    public Func<object, object, bool> Method { get; set; }
    static bool function(object i, object o) { return true};
    public static void Main()
    {
        var rule = new Rule();
        rule.Method = function;
        Console.WriteLine(JsonSerializer.Serialize(rule.Method));
    }
}
```

The error message is misleading (object cycle or max depth)
Unhandled exception. System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)

**Comment by ahsonkhan** [comment]
@SanjayVyas - what do you expect the behavior to be in this case?

**Comment by SanjayVyas** [comment]
First of all, The exception message is completely misleading. I wasted hours checking and re-checking my object graph
Second, Not throw an exception.. maybe quietly write out "null". I had to implement JsonConverter just to get rid of the exception.

**Comment by GSPP** [comment]
I guess the delegate is treated like any other object. It is recursively descended into. The error message is indeed very misleading here. But the serialization and error handling is very logical in the sense that it's the same for any other "unserializable"/cyclic type.

The message could be improved by adding a special case for delegate types. I guess there are many such unserializable types that could be special-cased like that to obtain a better message. This does not seem like a scalable approach.

Ignoring unserializable data seems like the wrong approach. Logic bugs should not be silenced.

**Comment by SanjayVyas** [comment]
Yes, makes sense that logic bugs should not be silenced. However, the error could be 'Unserializable object: Func<int, int, bool>"

**Comment by GSPP** [comment]
Maybe the feature request should be: If a cycle is detected the error message should say what it was. At least give some hints such as some types of objects involved.

**Comment by ahsonkhan** [comment]
> At least give some hints such as some types of objects involved.

The type where the cycle was detected might be different from the actual property type. Would having the type info still be useful and helpful as part of the exception message?

For example, here is what `Newtonsoft.Json` throws:
`Unhandled exception. Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Module' with type 'System.Reflection.RuntimeModule'. Path 'Method.Module.Assembly.EntryPoint'.`
