### ISSUE TITLE
High Memory Consumption When Validating Remote Certificates With Client SslStreams

### ISSUE THREAD

**Issue by autoracer42** [dotnet/runtime#101552]
### Description

When authenticating an SSL Stream as client using the Online Certificate revocation check option in a Linux container we see significant unmanaged memory usage / growth often leading to OOM pod restarts.

This can most clearly be seen by monitoring the RES memory of the dotnet process via the TOP command whilst making TLS sessions and changing the CertificateRevocationCheckMode against the SslClientAuthenticationOptions passed to the AuthenticateAsClientAsync method.

### Reproduction Steps

This issue is most prevalent when using a certificate issued by a public CA (in the case of the testing digicert) and only occurs when the server does not support OCSP stapling. 

Attached are two test applications, one a TLS server and one a TLS client. The server expects two command line arguments, the PFX file for a server certificate and the password for that PFX, it subsequently listens on all hosts on port 54784
The TLS client application then expects three arguments, the host to connect to, the port to connect to and whether to perform revocation checks on server certificates.  The client subsequently makes 100 TLS sessions to the server and outputs memory details, hitting enter will make it send another batch of 100 requests.

When the client is run on Linux with the revocation argument set to false, the reported memory for the application remains around 65MB and this is consistent if numerous sets of requests are made. When setting the check revocation argument to true at the end of the first set of requests the memory usage is around 400MB and often continues to increase through subsequent sets of requests.

[CertificateRevocationMemoryUsageTestApps.zip](https://github.com/dotnet/runtime/files/15111754/CertificateRevocationMemoryUsageTestApps.zip)

### Expected behavior

Memory remains relatively stable and is cleared when TLS connections are terminated

### Actual behavior

Memory is higher and increases

### Regression?

Behaviour appears very similar if the test application is converted to .NET 6.0 using the runtime/6.0 container

### Known Workarounds

Disable Certificate revocation checks when authenticating SslStream objects

### Configuration

.NET 8.0 (tested with both 8.0.4 and the 8.0.5 preview)
runtime/8.0 and runtime/8.0-jammy containers
The certificate used appears quite important, as the issue does not occur with a self-signed certificate

**Comment by rzikm** [comment]
Triage: we should investiate in 9.0

**Comment by rzikm** [comment]
I was unable to reproduce this issue with various combinations of OCSP/CRL revocation checking on the server (I found #101684, but that was not as severe as you describe and reproduced regardless of parameters).

- Can you provide a generated certificate (or OpenSSL instructions how to generate one) which reproduces the issue?
- Alternatively, if there's public server against which I can run the repro, can you share the url (you can use my work email radekzikmund (at) microsoft.com)
- lastly, if neither is applicable, can you share the list of extensions on the certificate? You can anonymize them, but I need something which I can use to generate similar certificate to repro the issue.

Or, if you are willing to try investigating yourself, then the tool which is generally useful for these issues is `heaptrack`

    heaptrack -o <path to output file> <app name> <args....>

run the repro and then process the output file to create a report

    heaptrack_print -l1 -a0 -T0 -p0 -f <path to output file>.zst

And upload the report file here.

**Comment by bartonjs** [comment]
> The other thing which may be potentially interesting is that I tried downloading the CRLs manually and each is around 8.8MB.

Assuming there's nothing exotic going on in that CRL, that's probably the problem.  When I last looked into a high memory issue with CRLs, it basically boiled down to

* Every time there's a serial number in the CRL OpenSSL calls malloc to track it.
  * They're smallish.  16 bytes.  so `malloc(16)`.
* glibc doesn't want to track small allocations, so every allocation gets rounded up to the next 1024
* That means, practically speaking, a 1000 byte overhead per serial number in the CRL
* `openssl crl -in some_random.crl -text -noout | grep Serial | wc -l` on a few CRLs, tacking 3 zeros on the end of that, and comparing to the original file size gives a "finger in the wind" estimate of the memory usage of loading a CRL to be about 20x its original size.
* https://github.com/dotnet/runtime/issues/7144#issuecomment-270544252 says that for APNS's 100MB CRL the RSS peaked at about 900MB, so maybe it's only 9x, but it's still surprisingly large overhead.

So an 8.8MB CRL would expand to 176MB while it's in use (using my 20x guesstimate).  With a 512MB process quota you can't even have that loaded in parallel 3 times before kerploding.

The "round up to 1024" thing is from memory.  I didn't just write a test for it it, and don't know if glibc has self-tuning (or environment variable-controlled tuning) to adjust it.

**Comment by rzikm** [comment]
Given the information from bartonjs's comment, I don't think there is anything we can reasonably do from .NET side about this.

I think you can confirm bartonjs's hypthesis using something like this

```cs
        [StructLayout(LayoutKind.Sequential)]
        struct mallinfo2_st
        {
            public ulong arena;
            public ulong ordblks;
            public ulong smblks;
            public ulong hblks;
            public ulong hblkhd;
            public ulong usmblks;
            public ulong fsmblks;
            public ulong uordblks;
            public ulong fordblks;
            public ulong keepcost;
        }

        [DllImport("libc")]
        private static extern mallinfo2_st mallinfo2();

        private static void DumpMallInfo(in mallinfo2_st info)
        {
            Console.WriteLine($"Non-mmapped space allocated (bytes):        {info.arena,11:N0}");
            Console.WriteLine($"Number of free chunks:                      {info.ordblks,11:N0}");
            Console.WriteLine($"Number of free fastbin blocks:              {info.smblks,11:N0}");
            Console.WriteLine($"Number of mmapped regions:                  {info.hblks,11:N0}");
            Console.WriteLine($"Space allocated in mmapped regions (bytes): {info.hblkhd,11:N0}");
            Console.WriteLine($"usmblks:                                    {info.usmblks,11:N0}");
            Console.WriteLine($"Space in freed fastbin blocks (bytes):      {info.fsmblks,11:N0}");
            Console.WriteLine($"Total allocated space (bytes):              {info.uordblks,11:N0}");
            Console.WriteLine($"Total free space (bytes):                   {info.fordblks,11:N0}");
            Console.WriteLine($"Top-most, releasable space (bytes):         {info.keepcost,11:N0}");
            Console.WriteLine();
        }
```

You should see large memory being reported in `fastbin blocks`.

You can then try forcing the consolidation and release of those fastbin blocks using [mallopt](https://man7.org/linux/man-pages/man3/mallopt.3.html) or [malloc_trim](https://man7.org/linux/man-pages/man3/malloc_trim.3.html) (similarly as `mallinfo2` is being called in the snippet above). Be sure to guard the calls to these functions so that they happen only on Linux.

**Comment by rzikm** [comment]
.NET should support client-side OCSP queries, but from source code it seems that it will always prioritize CRL. @bartonjs will know for sure.

**Comment by bartonjs** [comment]
>  is there anything I can set on the stream so it performs a client-side OCSP check when an OCSP responder is defined in the certificate before falling back to the CRL as a last resort?

No.  For Android, macOS, and Windows, the CRL or OCSP decision is always made by the OS.  For Linux, the decision is made by .NET, but it's CRL-first (assuming no stapled OCSP).

**Comment by rzikm** [comment]
Since we can't add any API surface to control the CRL/OCSP priority, I don't think there is more at this moment we can do regarding this issue. Closing for now.
