### ISSUE TITLE
CborReader should support reading from streams

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#101516]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CborReader-should-support-reading-from-s/10619686)._

---
The CborReader currently only supports reading from a contiguous array of bytes in memory. This is very limiting as it will require a lot of memory for large documents.

---
#### Mila Zhou [MSFT] on 3/20/2024, 02:15 AM: 

(private comment, text removed)
#### Knut Wannheden on 3/20/2024, 05:32 AM: 

(private comment, text removed)
#### Feedback Bot on 3/20/2024, 10:15 PM: 

(private comment, text removed)

**Comment by reflectronic** [comment]
https://github.com/dotnet/runtime/issues/99993

**Comment by teo-tsirpanis** [comment]
Duplicate of #99993.
