### ISSUE TITLE
[API Proposal]: DateOnly support in IsoWeek

### ISSUE THREAD

**Issue by leonluc-dev** [dotnet/runtime#101597]
### Background and motivation

At the moment the IsoWeek class only supports DateTime structs. 

Since the IsoWeek class is primarily (if not exclusively) based around dates rather than times, it would make sense to have it support the recently added DateOnly struct.

### API Proposal

Adding DateOnly variants of the public methods on the IsoWeek class.

```csharp
namespace System.Globalization
{
    public static class ISOWeek
    {
        //Added methods
        public static int GetWeekOfYear(DateOnly date);
        public static int GetYear(DateOnly date);
        public static DateOnly ToDateOnly(int year, int week, DayOfWeek dayOfWeek);
    }
}
```

### API Usage

```csharp
var week = IsoWeek.GetWeekOfYear(new DateOnly(2024, 4, 26));
```

**Comment by tarekgh** [comment]
@leonluc-dev this proposal is approved. Are you interested in providing the implementation? If so, we may do that after two weeks or so after we fork `main` branch.

**Comment by leonluc-dev** [comment]
@tarekgh Thanks! I can provide the implementation if neccesary. 

In our own code we already implement the proposed methods simply by falling back on the original DateTime methods after conversion.
For example:

```
public static int GetWeekOfYear(DateOnly date)
{
    var dt = date.ToDateTime(TimeOnly.MinValue, DateTimeKind.Unspecified);
    GetWeekOfYear(dt);
}
```

If that is okay, I can open a PR with these implementations whenever ready.

Implementing this the other way around (e.g. making the DateOnly methods the base implementation and rewriting the existing DateTime methods to be the overload/conversion), is possible too but is a slightly larger change.

**Comment by tarekgh** [comment]
Yes, this can be implemented this way but may be we can optimize it a little by using [GetEquivalentDateTime](https://source.dot.net/System.Private.CoreLib/R/883acf5f04e6d569.html)(). 

```C#
public static int GetWeekOfYear(DateOnly date) => GetWeekOfYear(date.GetEquivalentDateTime());
```

Of course, we'll need to make [GetEquivalentDateTime](https://source.dot.net/System.Private.CoreLib/R/883acf5f04e6d569.html)() `internal` instead of `private`. 

As I mentioned we need to open the PR later, after two weeks or we can open it now as a draft and then we can merge it later. Please let me know what works best for you.

**Comment by leonluc-dev** [comment]
> Yes, this can be implemented this way but may be we can optimize it a little by using [GetEquivalentDateTime](https://source.dot.net/System.Private.CoreLib/R/883acf5f04e6d569.html)().
> 
> ```cs
> public static int GetWeekOfYear(DateOnly date) => GetWeekOfYear(date.GetEquivalentDateTime());
> ```
> 
> Of course, we'll need to make [GetEquivalentDateTime](https://source.dot.net/System.Private.CoreLib/R/883acf5f04e6d569.html)() `internal` instead of `private`.
> 
> As I mentioned we need to open the PR later, after two weeks or we can open it now as a draft and then we can merge it later. Please let me know what works best for you.

Sounds good. `GetEquivalentDateTime()` seems like a better option if it's okay to make it internal.

I'll wait two weeks until the PR can be opened. Once a branch is ready to fork/PR. will it be notified on this issue?

**Comment by leonluc-dev** [comment]
I have opened a draft PR for this proposal here: https://github.com/dotnet/runtime/pull/108479
