### ISSUE TITLE
[API Proposal]: BinaryReader.ReadExactly

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#101614]
### Background and motivation

When reading custom binary formats one very often needs a specific number of bytes. The existing `Read()` method doesn't read a specific number of bytes, it reads as many bytes are currently available. Calling code has to handle this.

We had the same issue on `Stream` and [solved this by exposing `Stream.ReadExactly` and `Stream.ReadAtLeast`](https://github.com/dotnet/runtime/issues/16598#issuecomment-1118973589).

### API Proposal

```csharp
namespace System.IO;

public partial class BinaryReader
{
    public virtual void ReadExactly(Span<byte> buffer);
}
```

### API Usage

```csharp
BinaryReader binaryReader = GetReader();

Span<byte> guidBytes = (Span<byte>)stackalloc byte[16];
reader.ReadExactly(guidBytes);

Guid guid = new Guid(guidBytes);
```

**Comment by PaulusParssinen** [comment]
This would be equivalent to calling ``ReadExactly(Span<byte>)`` on the ``BinaryReader.BaseStream`` property, right?

**Comment by terrajobst** [comment]
Logically yes, but practically the challenge is that the reader has its own buffer. By passing that would be problematic.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.IO;

public partial class BinaryReader
{
    public virtual ReadExactly(Span<byte> buffer);
}
```

**Comment by paulbartrum** [comment]
> ```cs
> public partial class BinaryReader
> {
>     public virtual ReadExactly(Span<byte> buffer);
> }
> ```

The method return type is missing (I'm assuming it should be `void`?)

**Comment by terrajobst** [comment]
LOL. Look, I only work here. Fixed.

**Comment by adamsitnik** [comment]
> Logically yes, but practically the challenge is that the reader has its own buffer.

It used to have it's own buffer, after https://github.com/dotnet/runtime/pull/80331 it does not.

I've marked this issue as "help wanted" and "good first issue" to attract some new contributors (any .NET Team member who whishes to contribute please wait for a PR from community and review it, it's the best way you can help).

The person who wishes to work on this issue should let others know here, so there are no multiple contributors working on the same problem.

Here are some tips that you may find useful:

- [here](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md) you can find our workflow instructions, the first step is to install everything required to build the product
- to build the clr, libs and tests you need to build following subsets:
```cmd
.\build.cmd -c Release -subset clr+libs+libs.tests
```
- the `BinaryReader` type is included in corelib, not in `System.IO.dll`: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs
- its tests are in `System.IO.Tests`: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System.IO.Tests/BinaryReader/BinaryReaderTests.cs
- the test projects can access only the public classes and methods that were added to the ref assembly: https://github.com/dotnet/runtime/blob/019d7580a27db97f1fbdcf0d26f7ae3fa54fc2d1/src/libraries/System.Runtime/ref/System.Runtime.cs#L9900
- To rebuild only the corelib (where `BinaryReader` is) and run the tests you can run following command:
```cmd
.\build.cmd -c Release -subset clr.corelib+clr.nativecorelib+libs.PreTest && .\dotnet.cmd build -c Release .\src\libraries\System.Runtime\System.Runtime.sln && .\dotnet.cmd build -c Release .\src\libraries\System.Runtime\tests\System.IO.Tests\System.IO.Tests.csproj /t:Test
```

Good luck!

**Comment by Log234** [comment]
I would like to attempt providing an implementation for this proposal, if I may have the chance.
