### ISSUE TITLE
DirectoryNotFoundException - Throws Misleading Exception When Path to File is Provided Instead of Directory

### ISSUE THREAD

**Issue by BayanBadir** [dotnet/runtime#101632]
### Describe the bug
In .NET Core, when calling [DirectoryInfo.EnumerateFileSystemInfos](https://learn.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.enumeratefilesysteminfos?view=net-8.0) Method 
if the folder path does not exist but a file with the same path does, an error message is generated stating, "Could not find a part of the path 'My/Path'." This error message is misleading because a file with that path does exist. The error message should be clearer, perhaps something like, "The folder was not found.".

### To Reproduce

1- Create a file without an extension.
2- Ensure that there is no directory with the same path as the file.
3- Invoke the `DirectoryInfo.EnumerateFileSystemInfos` method using the path of the file created in step 1.
4.- A `DirectoryNotFoundException` will be thrown. Observe the error message provided.

**Comment by Jozkee** [comment]
I'm unaware of why that wording was chosen historically, however, changing it will have as a consequence that multiple forum posts (e.g. StackOverflow) will no longer serve as a reference for investigating this error. I don't think it would be wise to change it.
