### ISSUE TITLE
[wasm] WebAssembly crashes if building with non-Release/Debug build config

### ISSUE THREAD

**Issue by RPGillespie6** [dotnet/runtime#101629]
### Description

Not actually sure if this is specifically a dotnet issue or a Skia issue, hoping to get some triage help.

Essentially the problem is that you cannot use custom build configurations if using SkiaSharp + WASM or it will mysteriously crash at runtime on SKPaint dispose (after a using block). But it usually doesn't crash right away, it takes around 79 dispose calls in the repro code before the crash:

![image](https://github.com/dotnet/runtime/assets/9853156/ac3fadde-8eef-4e04-9d5a-1f0dafd81e86)

### Reproduction Steps

Repro repo: https://github.com/RPGillespie6/dotnet_skia_wasm_crash

Build with Release build configuration and observe that the code runs to completion. Build with Release_WASM build configuration and observe that the code crashes on SKPaint dispose after 79 iterations. Confirmed this repo reproduces the problem on 2 different PCs (one with Intel i9, one with AMD Ryzen 7).

We use custom build configurations to set different #if flags, so it's kind of annoying to work around. This is why I'm opening an issue with dotnet -- as far as I can tell, my custom config should have identical settings as `Release` since I used:

![image](https://github.com/dotnet/runtime/assets/9853156/df2d5a5e-da94-49b2-949d-6da6d4741378)

But that doesn't seem to be the case. If I use my custom config, I get mysterious runtime crashes.

### Expected behavior

`Release` and `Release_WASM` build configs to produce identical runtime results

### Actual behavior

`Release_WASM` results in mysterious crash on after 79 Skia object disposals

### Known Workarounds

Stick to only using `Release` or `Debug` build configurations

### Configuration

Everything is in here: https://github.com/RPGillespie6/dotnet_skia_wasm_crash/blob/master/WasmOnly.csproj

**Comment by maraf** [comment]
@RPGillespie6 Thank you for the report. It seems it is already fixed in .NET 9 previews, but the fix wasn't backported to .NET 8. Can you please try suggested workaround from https://github.com/dotnet/runtime/issues/94939#issuecomment-1839929771 ?

**Comment by RPGillespie6** [comment]
Thanks, the suggested workaround from the linked comment appears to workaround the issue! We can close this issue. Is there an issue I can follow to track the progress of the backport to .NET 8?

**Comment by maraf** [comment]
Let's leave this one open at the moment. I'll update it based on backport plan

**Comment by maraf** [comment]
I'm sorry for late reply.

> Since AOT is so much faster than JIT, I'm back to just using `Release` and `Debug` build configurations again which seem to work. Deviating from these 2 build configurations seems like a minefield at the moment.

Various parts of .NET SDK provide various defaults based Debug/Release configuration. In WebAssembly the property `EmccLinkOptimizationFlag` has a default value of `-O2` for Release builds. Adding might fix the AOT problem.

**Comment by maraf** [comment]
I'm going to close this issue in favor of https://github.com/dotnet/runtime/issues/104540
