### ISSUE TITLE
How to Apply XML Configuration for Removing Specific Attribute Instances in .NET Linker ( NativeAOT )

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#101680]
Hello,

I am working on a .NET project and would like to optimize my assembly by removing specific attribute instances using the .NET linker. I have defined the following XML configuration but need guidance on properly integrating it with the linker in a .NET project:
![image](https://github.com/dotnet/runtime/assets/111659964/d0babe5e-80cc-4329-8e6e-550713aa1072)

How should this XML be integrated into the .NET project configuration to instruct the linker to remove these attribute instances?

**Comment by JakeYallop** [comment]
I've used something like this before:

```xml
  <ItemGroup Condition="'$(PublishTrimmed)' == 'True'">
    <RdXmlFile Include="rd.xml" />
  </ItemGroup>
  ```

**Comment by JakeYallop** [comment]
However, its also worth highlighting - NativeAOT uses a different format to the linker: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/rd-xml-format.md,

So I'm not sure if the XML file you have currently will actually work with NativeAOT.

**Comment by dadavadd** [comment]
> I've used something like this before:
> 
> ```
>   <ItemGroup Condition="'$(PublishTrimmed)' == 'True'">
>     <RdXmlFile Include="rd.xml" />
>   </ItemGroup>
> ```
![image](https://github.com/dotnet/runtime/assets/111659964/8b0e6c07-ebc1-49a9-9317-0c4cbbd94816)

**Comment by dadavadd** [comment]
> However, its also worth highlighting - NativeAOT uses a different format to the linker: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/rd-xml-format.md,
> 
> So I'm not sure if the XML file you have currently will actually work with NativeAOT.

I inserted <?xml version="1.0" encoding="utf-8" ?> before the start of the file and compilation completed successfully.

But this did not reduce the weight of the program.😁

**Comment by JakeYallop** [comment]
I'll admit, I've not really messed with trimming recently - that snippet was just copied from an old piece of code I had lying around.

WinForms does not officially support Native AOT anyway: https://github.com/dotnet/winforms/issues/4649

**Comment by MichalStrehovsky** [comment]
The native AOT compiler doesn't have any switches (documented or not) to inject this file into compilation and there are no plans to add one. This file format is only for use within the dotnet/runtime repo.

FWIW there is work in progress to make WinForms trimmable.
