### ISSUE TITLE
AssemblyBuilder still lacks SetEntryPoint

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#101667]
### Description

In the recent work on `Reflection.Emit` saving in .NET 9 preview, the `SetEntryPoint` API was removed entirely, with the developer left to implement it manually using `PersistableAssemblyBuilder` and various `System.Reflection.Metadata` APIs.  This works well enough if you're trying to save to a file, but one important use case is still failing hard: generating executable assemblies in-memory.  This has real-world applications for a REPL, or for a compiler test suite.

### Reproduction Steps

1. Try to generate an executable assembly in-memory with `System.Reflection.Emit`
2. You can't do it because there's no `SetEntryPoint` API available.

### Expected behavior

It should be possible to generate an executable assembly in-memory, as it was in .NET Framework.

### Actual behavior

It is not possible to generate an executable assembly in-memory.

### Regression?

This worked in .NET Framework.

### Known Workarounds

It's possible to use `PersistableAssemblyBuilder` and save the whole thing to a `MemoryStream`, and then call `Assembly.Load` on the bytes in the stream, but this feels like a gross hack.

### Configuration

.NET Core 9, Preview 3, Windows 10, x64

**Comment by jkotas** [comment]
> It's possible to use PersistableAssemblyBuilder and save the whole thing to a MemoryStream, and then call Assembly.Load on the bytes in the stream, but this feels like a gross hack.

I expect that this it is what we are going to do under the covers eventually.

The fundamental feature currently missing in PersistableAssemblyBuilder compared to in-memory RefEmit is ability to append new types to already executing assembly. If you do not need to append new types to already executing assembly, you may want to switch to PersistableAssemblyBuilder + Assembly.Load to get the features that are unavailable with in-memory RefEmit.

**Comment by masonwheeler** [comment]
@buyaa-n This was not meant to be about `PersistableAssemblyBuilder`, but rather `AssemblyBuilder`, because building and executing an executable assembly in-memory, without ever saving it, has always been a valid use case.

**Comment by buyaa-n** [comment]
Based on @jkotas comment:

> I expect that this it is what we are going to do under the covers eventually.

I assumed we wouldn't fix in runnable `AssemblyBuilder` either, feel free to reopen if that was not the case
