### ISSUE TITLE
Prevent runtime loading of my assembly into another application in C#

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#101678]
Hello,

I am currently developing a .NET application and am facing a security concern. I need to ensure that my assembly cannot be loaded by another application at runtime using methods like Assembly.Load, Assembly.LoadFrom, or Assembly.LoadFile. This is crucial for maintaining the integrity and security of my application.

Could anyone provide guidance or a method to effectively prevent or control the runtime loading of my specific assembly into other applications?

Additionally, if there are any recommended practices or patterns that could enhance the security around this issue, please share them.

Thank you for your assistance!

**Comment by huoyaoyuan** [comment]
> This is crucial for maintaining the integrity and security of my application.

**This is a false sense of security.** Nothing prevents other application to open your assembly as a file, analyze its content and create a new one. Any mechanism built into CLR can be bypassed by creating a custom build of CLR.

If you want any sort of protection of your application, at very least you should get help from operating system to prevent your files to be ever touched, for example through some app store protection.

**Comment by dadavadd** [comment]
> **This is a false sense of security.** Nothing prevents other application to open your assembly as a file, analyze its content and create a new one. Any mechanism built into CLR can be bypassed by creating a custom build of CLR.
> 
> If you want any sort of protection of your application, at very least you should get help from operating system to prevent your files to be ever touched, for example through some app store protection.

Are you saying that I can't prevent my assembly from being loaded into another assembly via Assembly.LoadFile?

**Comment by huoyaoyuan** [comment]
> Are you saying that I can't prevent my assembly from being loaded into another assembly via Assembly.LoadFile?

You don't control "your assembly" at all once it's accessible as a file.

**Comment by hez2010** [comment]
While you may implement some logic in the `ModuleInitializer` to detect whether the assembly is loaded in your desired environment, so that one cannot easily load your assembly without any efforts, but still, it's a false sense of security as anyone has the file access to your assembly can do anything to it including bypassing any logic you have implement.

**Comment by Clockwork-Muse** [comment]
> If you want any sort of protection of your application, at very least you should get help from operating system to prevent your files to be ever touched, for example through some app store protection.

Even this doesn't prevent everything.

The only way to prevent analysis of your _assembly_ is to never distribute it to "untrusted" parties (end users), hosting it in your own infra and providing some sort of remote API/RPC.  This can't prevent reverse engineering your API, though.
