### ISSUE TITLE
JsonSerializer allows nulls in arrays of non-nullable T

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#101659]
### Description

It appears that `System.Text.Json` treats the following objects in the same way:
```cs
record Nullable(string?[] Names);
record NonNullable(string[] Names);
```

### Reproduction Steps

```cs
using System.Text.Json;

var json = """
{
    "Names": ["Alice", "Bob", null, "Charlie"]
}
""";

var shouldSucceed = JsonSerializer.Deserialize<Nullable>(json);
var shouldFail = JsonSerializer.Deserialize<NonNullable>(json);

throw new Exception("Unreachable!");

record Nullable(string?[] Names);
record NonNullable(string[] Names);
```

### Expected behavior

Serializer throws an exception

### Actual behavior

The "unreachable" exception is thrown

### Regression?

No

### Known Workarounds

Using custom converter

### Configuration

.NET 8.0.3

**Comment by huoyaoyuan** [comment]
I believe this is covered under #100144.

**Comment by neon-sunset** [comment]
Ah, my bad, I tried searching for issues and could not find an appropriate one. Thanks.

**Comment by eiriktsarpalis** [comment]
Note that non-nullable element types are out of scope for https://github.com/dotnet/runtime/issues/100144, due to restrictions in their run-time representation.

**Comment by neon-sunset** [comment]
> Note that non-nullable element types are out of scope for #100144, due to restrictions in their run-time representation.

I see. Could there be a possibility of that changing in the future? (perhaps for source-generated serialization only?)

**Comment by eiriktsarpalis** [comment]
> > Note that non-nullable element types are out of scope for #100144, due to restrictions in their run-time representation.
> 
> I see. Could there be a possibility of that changing in the future? (perhaps for source-generated serialization only?)

Unlikely. The serialization infrastructure is shared between reflection and source gen and both key they contracts on `Type`, which cannot distinguish between `List<string>` and `List<string?>`.
