### ISSUE TITLE
[API Proposal]: HttpClient.GetStringAsync

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#101601]
### Background and motivation

I suggest adding to HttpClient an overload for ignoring HTTP errors. This overload is needed when the server returns an error, but there is still data it sends in the request body. Sometimes the HTTP status code isn't crucial, and what matters more is the response body.

`

### API Proposal

```csharp
public System.Threading.Tasks.Task<string> GetStringAsync (string? requestUr,bool ignoreHttpErrors);
```

### API Usage

```csharp
     using var client = new HttpClient();
     client.GetStringAsync("", true);
```

**Comment by Mr0N** [comment]
> I belive this can be easily written as an extension method, there is no need to implement this inside .NET runtime repository.

Well, you should use the GetAsync method for the extension method. And use the GetStringAsync method instead of GetAsync.

**Comment by Mr0N** [comment]
Well, plus GetStringAsync also adds additional headers like in an HTTP request.

**Comment by rzikm** [comment]
> Well, you should use ...

What I meant to say is that we are unlikely to add additional helper methods to HttpClient for functionality which can already be achieved using current public API. Especially for this rather niche scenario (this is the first request for such an API I know of).

Given that, it'll be faster and more flexible if you implement the extension method in your project and tailor the behavior to your specific needs.

This looks like something that might work for you

```cs
static class HttpClientExtensions
{
    public static async System.Threading.Tasks.Task<string> GetStringAsync(this HttpClient client, string? requestUri, bool ignoreHttpErrors)
    {
        ArgumentNullException.ThrowIfNull(client);
        var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, requestUri));
        if (!ignoreHttpErrors)
        {
            response.EnsureSuccessStatusCode();
        }

        return await response.Content.ReadAsStringAsync();
    }
}
```

**Comment by Mr0N** [comment]
> ```cs
>             response.EnsureSuccessStatusCode();
> ```

So basically, you can implement the entire runtime using that method where errors cannot be ignored, you know. I have a method I use, then the server sends a 404 code, and I have to separately implement another method to read what the server sent

**Comment by Mr0N** [comment]
> > Well, you should use ...
> 
> What I meant to say is that we are unlikely to add additional helper methods to HttpClient for functionality which can already be achieved using current public API. Especially for this rather niche scenario (this is the first request for such an API I know of).
> 
> Given that, it'll be faster and more flexible if you implement the extension method in your project and tailor the behavior to your specific needs.
> 
> This looks like something that might work for you
> 
> ```cs
> static class HttpClientExtensions
> {
>     public static async System.Threading.Tasks.Task<string> GetStringAsync(this HttpClient client, string? requestUri, bool ignoreHttpErrors)
>     {
>         ArgumentNullException.ThrowIfNull(client);
>         var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, requestUri));
>         if (!ignoreHttpErrors)
>         {
>             response.EnsureSuccessStatusCode();
>         }
> 
>         return await response.Content.ReadAsStringAsync();
>     }
> }
> ```
So basically, you can implement the entire runtime using that method where errors cannot be ignored, you know. I have a method I use, then the server sends a 404 code, and I have to separately implement another method to read what the server sent

**Comment by Mr0N** [comment]
> > Well, you should use ...
> 
> What I meant to say is that we are unlikely to add additional helper methods to HttpClient for functionality which can already be achieved using current public API. Especially for this rather niche scenario (this is the first request for such an API I know of).
> 
> Given that, it'll be faster and more flexible if you implement the extension method in your project and tailor the behavior to your specific needs.
> 
> This looks like something that might work for you
> 
> ```cs
> static class HttpClientExtensions
> {
>     public static async System.Threading.Tasks.Task<string> GetStringAsync(this HttpClient client, string? requestUri, bool ignoreHttpErrors)
>     {
>         ArgumentNullException.ThrowIfNull(client);
>         var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, requestUri));
>         if (!ignoreHttpErrors)
>         {
>             response.EnsureSuccessStatusCode();
>         }
> 
>         return await response.Content.ReadAsStringAsync();
>     }
> }
> ```

Well, you can implement GetAsync on the socket. I have a method I use, then the server sends a 404 code, and I have to separately implement another method to read what the server sent. It's quite inconvenient.

**Comment by MihaZupan** [comment]
> Well, plus GetStringAsync also adds additional headers like in an HTTP request.

It does not.

Wanting to read the response body even if the status code indicates an error makes sense.
But in such cases, I'd imagine that you want to know the response body ***in addition to*** the status code. Otherwise, why bother returning anything other than 200 from the API in the first place?

The existing alternative makes you write 2 lines instead of 1:
```diff
-string text = await client.GetStringAsync("/foo", someExtraArgument);
+using var response = await client.GetAsync("/foo");
+string text = await response.Content.ReadAsStringAsync();
```

This also gives you access to the response object that you can now query for things like `response.IsSuccessStatusCode`.

Given that, I don't see us adding extra overloads for this.

**Comment by Mr0N** [comment]
> > Well, plus GetStringAsync also adds additional headers like in an HTTP request.
> 
> It does not.
> 
> Wanting to read the response body even if the status code indicates an error makes sense. But in such cases, I'd imagine that you want to know the response body _**in addition to**_ the status code. Otherwise, why bother returning anything other than 200 from the API in the first place?
> 
> The existing alternative makes you write 2 lines instead of 1:
> 
> ```diff
> -string text = await client.GetStringAsync("/foo", someExtraArgument);
> +using var response = await client.GetAsync("/foo");
> +string text = await response.Content.ReadAsStringAsync();
> ```
> 
> This also gives you access to the response object that you can now query for things like `response.IsSuccessStatusCode`.
> 
> Given that, I don't see us adding extra overloads for this.

The point of the GetStringAsync method then? It seems like a non-working method that throws errors on status codes, for example, 404. This code indicates that the requested resource is not found. If, for instance, I have a heavily loaded application, these errors will significantly impair its functionality.

**Comment by Mr0N** [comment]
> > The point of the GetStringAsync method then?
> 
> It's a simple helper for simple scenarios. If you want to handle errors differently, you have the option to do so (the 1 extra line).

Why not allow the possibility to customize the execution of this method, not just ignoring errors but also providing some time-related settings?

**Comment by MihaZupan** [comment]
All methods here accept a `CancellationToken`, so you can customize timeouts by creating your own `CancellationTokenSource` if that's what you mean.

**Comment by Mr0N** [comment]
Well, I meant that more settings could be added over time for this method, well, okay, maybe you'll add them sometime.

**Comment by CyrusNajmabadi** [comment]
@Mr0N the point is that you can do all that customization in your own extension method.
