### ISSUE TITLE
ARM64-SVE: No obvious way to mask an Across function

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#101770]
ConditionalSelect is used to mask an API, for example:
```
a = Sve.ConditionalSelect(mask, Sve.Add(a,b), a);
```
Is equivalent to:
```
ADD zA, zMask/M, zA, zB
```

This does not work when using the across methods.
```
a = Sve.ConditionalSelect(mask, Sve.AddAcross(a), a);
```
Is saying to add together all the elements in `a` and place in field 0, zeroing all other elements. Then use `mask` to select which elements to pick from the result. That is valid C#, but is a weird thing to do.

the more likely use case is to take all the elements in `a` that are marked as active in `mask` and add them together, putting them in field 0, zeroing all other elements. There is no obvious way to do this?

**Comment by a74nh** [comment]
Having said that, it now occurs to me that for AddAcross you could do:
```
a = Sve.AddAcross(Sve.ConditionalSelect(mask, a, zero));
```

But that doesn't work for _all_ Across methods. For example, `MinAcross()`.

**Comment by a74nh** [comment]
@kunalspathak @tannergooding - this came up as part of implementing https://github.com/dotnet/runtime/pull/101674

**Comment by kunalspathak** [comment]
We discussed it in https://github.com/dotnet/runtime/pull/101674#discussion_r1583392032

**Comment by a74nh** [comment]
I think in these cases extra API methods would make sense.

This probably needs splitting into two issues then:

1. An API issue with the new methods in it
2. For the cases where the user does write code in the `*Across(ConditionalSelect)` style, something in lowering to detect and optimise.

**Comment by a74nh** [comment]
Opened:

- ARM64-SVE: Detect mask usage for Across functions : https://github.com/dotnet/runtime/issues/101973
- [API Proposal]: ARM64-SVE: Masked versions of Across methods https://github.com/dotnet/runtime/issues/101974


Closing this issue in favour of those
