### ISSUE TITLE
[x64/Ubuntu] Failure in JitStress=2 JitStressRegs=4 job

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#10177]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_jitstress2_jitstressregs4_tst/438/consoleText

FAILED   - baseservices/threading/waithandle/waitany/waitanyex5a/waitanyex5a.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_jitstress2_jitstressregs4_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun waitanyex5a.exe
               Abandoning only one Mutex in array with other WaitHandles, signaling other mutexes
               Waiting...
               WaitAny did not throw AbandonedMutexExcpetion
               Test Failed
               Expected: 100
               Actual: 255
               END EXECUTION - FAILED

**Comment by kouvel** [comment]
The test doesn't exist anymore, closing
