### ISSUE TITLE
[8.0] [Installer] Failure in command: rpm2cpio netstandard-targeting-pack-2.1.0-x64.rpm | cpio -idmv

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#101788]
## Build Information

Introduced by this PR: https://github.com/dotnet/runtime/pull/101518

The failing lines are these ones:
https://github.com/dotnet/runtime/blob/47f25fbcd4a1e7b29d8ec7f672bdade9a34d7cfd/src/installer/pkg/sfx/installers/netstandard2.1.proj#L32-L33

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=662640
Build error leg or test failing: `Installer Build and Test coreclr windows_x86 Debug` and `Installer Build and Test coreclr windows_x64 Release`

## Error Message

```json
{
  "ErrorMessage" : ".rpm | cpio -idmv\" exited with code",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- Found in this unrelated PR: https://github.com/dotnet/runtime/pull/101783

- [`Installer Build and Test coreclr windows_x86 Debug`](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662640&view=logs&j=23d5758c-f7b0-5d73-87db-6590bab86b75&t=4904e489-dd2d-5d58-b254-34c0b4b0e9ce&l=556): 
```
src\installer\pkg\sfx\installers\netstandard2.1.proj(32,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) 
The command "rpm2cpio D:\a\_work\1\s\artifacts\obj\netstandard2.1\download\netstandard-targeting-pack-2.1.0-x64.rpm | cpio -idmv" exited with code 255.
```
- [`Installer Build and Test coreclr windows_x64 Release`](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662640&view=logs&j=0b1f6f56-7668-5e77-ec2c-0f0b179fcaa0&t=4612a820-22ca-5e7a-fd4c-58fb71097a0f): 
```
src/installer/pkg/sfx/installers/netstandard2.1.proj(32,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) 
The command "rpm2cpio /__w/1/s/artifacts/obj/netstandard2.1/download/netstandard-targeting-pack-2.1.0-x64.rpm | cpio -idmv" exited with code 127.
```

@NikolaMilosavljevic @ViktorHofer @ericstj

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=662640
**Error message validated:** `[.rpm | cpio -idmv" exited with code`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/2/2024 4:01:59 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[663780](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663780)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663780/logs/126)|dotnet/runtime#101823|
|[663779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663779)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663779/logs/2381)|dotnet/runtime#101823|
|[2443719](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443719)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443719/logs/2994)||
|[663665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663665)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663665/logs/126)|dotnet/runtime#101703|
|[663664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663664)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663664/logs/2323)|dotnet/runtime#101703|
|[663623](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663623)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663623/logs/126)|dotnet/runtime#101817|
|[663647](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663647)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663647/logs/2312)||
|[2443613](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443613)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443613/logs/2995)||
|[663622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663622)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663622/logs/2593)|dotnet/runtime#101817|
|[2443591](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443591)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443591/logs/3028)||
|[2443576](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443576)|dotnet-runtime|Package Runtime Deps, Runtime, Framework Packs Deb installers - deb|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443576/logs/1915)||
|[663549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663549)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663549/logs/82)|dotnet/runtime#101703|
|[2443436](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443436)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443436/logs/2988)||
|[2443417](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443417)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443417/logs/3022)||
|[663454](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663454)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/663454/logs/2067)||
|[2443025](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443025)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443025/logs/3001)||
|[2443019](https://dev.azure.com/dnceng/internal/_build/results?buildId=2443019)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2443019/logs/2992)||
|[662867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662867)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/662867/logs/2253)||
|[2442924](https://dev.azure.com/dnceng/internal/_build/results?buildId=2442924)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2442924/logs/2981)||
|[2442911](https://dev.azure.com/dnceng/internal/_build/results?buildId=2442911)|dotnet-runtime|Build|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2442911/logs/2979)||
|[662746](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662746)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/662746/logs/2238)||
|[662640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662640)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/662640/logs/2423)|dotnet/runtime#101783|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|22|

**Comment by ericstj** [comment]
Looks like this is *failing* the build and should be addressed immediately @NikolaMilosavljevic 
Seems the build machine is missing the tool:
```
  'rpm2cpio' is not recognized as an internal or external command,
  operable program or batch file.
```

**Comment by carlossanlop** [comment]
What's interesting is that the CI legs did not fail in the PR, but they failed in the rolling builds.

Glad we merged it earlier and caught the issue on time, and not post code-complete.

**Comment by ericstj** [comment]
It could be due to a difference in the images used for PR validation vs rolling build?  Or an image change that happened after PR validation.  I'm not sure what's reponsible for making that `rpm2cpio` tool available.

**Comment by NikolaMilosavljevic** [comment]
I have a fix for this issue - it will be included in the new PR for NetStandard work.

I've kicked off validation that is unfortunately failing with some unrelated errors: https://dev.azure.com/dnceng/internal/_build/results?buildId=2446943&view=results @carlossanlop do you know if the errors are known and/or intermittent? I can always kick-off another build.

**Comment by NikolaMilosavljevic** [comment]
Closing - the change was reverted with https://github.com/dotnet/runtime/pull/101812

New PR for NETStandard 2.1 work is out: https://github.com/dotnet/runtime/pull/102081
