### ISSUE TITLE
Huge output of 0's on >256 character to Convert.ToHexString()

### ISSUE THREAD

**Issue by Hashbrown777** [dotnet/runtime#101757]
### Description

I'm hoping this works (you guys can repro) and isn't something wrong with PowerShell's calling of .NET.
I'm running Powershell 7.4 (with whatever .NET API that installs with).

### Reproduction Steps

[Convert]::ToHexString("`u{200F}"[0])

### Expected behavior

Probably `"Error: "Value was either too large or too small for an unsigned byte.""` or `200F`

### Actual behavior

![image](https://github.com/dotnet/runtime/assets/6907206/7ff938e7-ae31-48d1-9d54-ecbc1cbb89cd)

### Configuration

x64 Fedora Linux, I cannot ascertain the .NET version, google tells me to look up the non-existent registry value (please let me know if there's a way to ask the library itself at runtime, even if there might be a way to see via the installed files)

### Other information

![image](https://github.com/dotnet/runtime/assets/6907206/1e4d6bc0-2a38-4edd-8cea-b38036632f68)

**Comment by colejohnson66** [comment]
`Convert.ToHexString` is documented as only allowing `byte`-like types. Specifically, `byte[]`, `byte[]` with offset+length, and `ReadOnlySpan<byte>`. Trying to execute `Convert.ToHexString('\u0100')` or `Convert.ToHexString('\u200F')` fails to compile:

![image](https://github.com/dotnet/runtime/assets/11381599/ae28c33a-3c22-4025-b06b-b9b79e05fc01)

But if ran from Powershell, it does indeed output a string of `n` zeros (where `n` is the character's value times two). I wonder if it's creating a byte array of length `c*2` and passing it into the method?

**Comment by huoyaoyuan** [comment]
You can use `[Environment]::Version` to display underlying runtime version in PowerShell.

> This sounds like a PowerShell bug, not a .NET one.

It may be an un-intuitive behavior of implicit dynamic casting.

**Comment by colejohnson66** [comment]
I tested on .NET 8.0.4 through PowerShell 7.4.2. If ran on the old non-Core PowerShell 5.1, it uses .NET Framework 4.0, so `Convert.ToHexString` doesn't exist (it was added in 5)

**Comment by am11** [comment]
The issue is with the `char[]` cast.
``[Convert]::ToHexString([char]"`u{200F}")`` should be:
``[Convert]::ToHexString([System.Text.Encoding]::Unicode.GetBytes("`u{200F}"))``

**Comment by Hashbrown777** [comment]
Anyway to port issues across or do I close and open a new one over at PowerShell?

**Comment by Hashbrown777** [comment]
> The issue is with the `char[]` cast. 

Yeah I know how to do it properly once I saw the error, it's just that the error I saw wasn't an exception/message, it was some bad behaviour, so I thought I'd report it.

**Comment by Hashbrown777** [comment]
[explained as happening prior to .NET receiving the arguments](https://github.com/PowerShell/PowerShell/issues/21563#issuecomment-2088686194)
