### ISSUE TITLE
Cannot add System.Json to an Android .NET 8 project

### ISSUE THREAD

**Issue by FANMixco** [dotnet/runtime#101758]
### Description

I'm trying to add the `System.JSON` to an Android with .NET 8 project that I'm migrating from Xamarin, and only this library is not being recognized:

<img width="1127" alt="image" src="https://github.com/microsoft/dotnet/assets/1666156/9e4cd9d5-8d55-4efe-8615-aede07b929b9">

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>22</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>tk.supernovaic.themayanroute</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Json" Version="4.7.1" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.23" />
    <PackageReference Include="Xamarin.AndroidX.Preference" Version="1.2.1.4" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.10.0.3" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils" Version="1.0.0.23" />
    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.8.0" />
  </ItemGroup>
```

### Reproduction Steps

- Create a .NET for Android project.
- Add the `System.Json` lib from the NuGet.
- Try to use it.

<img width="1127" alt="image" src="https://github.com/microsoft/dotnet/assets/1666156/9e4cd9d5-8d55-4efe-8615-aede07b929b9">

### Expected behavior

To be able to use the `System.Json` lib properly. I cannot do any code serealization like this one:

```csharp
return JsonSerializer.Deserialize<CurrencyExchange>((await Task.Run(() => System.Json. JsonValue.Load(stream))).ToString());
```

### Actual behavior

The `System.Json` is not recognized for Android .NET 8 projects in Visual Studio 2022.

### Regression?

Yes, it's a regression. It used to work in Xamarin.Android.

### Known Workarounds

I don't know any way to make it work. Maybe to use Xamarin.Android?

### Configuration

- .NET 8
- Visual Studio 2022:

![image](https://github.com/dotnet/runtime/assets/1666156/47985981-807e-494c-b72f-fe04c9bea370)

**Comment by huoyaoyuan** [comment]
The package adds nothing to Xamarin.Android project because it was built-in in Xamarin. `net8.0-android` inherits the behavior from Xamarin.Android. Currently there's no way to override NuGet's resolution.

The package is highly legacy and you don't need to use it any more. There's now built-in `System.Text.Json` in the SDK. You can see the documentation at https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/overview .

`System.Text.Json` also provides a good integration with `HttpClient`. You can use a shorthand method `httpClient.GetFromJsonAsync<Type>(url)`.

**Comment by gregsdennis** [comment]
What is `System.Json`?  The library you're probably looking for is `System.Text.Json`.

**Comment by gregsdennis** [comment]
Found the lib, which points to https://github.com/dotnet/corefx.  The readme there:

> Going forward, the .NET team is using https://github.com/dotnet/runtime to develop the code and issues formerly in this repository.
>
> Please see the following for more context:
>
> https://github.com/dotnet/announcements/issues/119

It doesn't look like that has been worked on in years.

**Comment by vitek-karas** [comment]
@FANMixco could you please try the suggestions from @huoyaoyuan in https://github.com/dotnet/runtime/issues/101758#issuecomment-2088352125?

**Comment by FANMixco** [comment]
I'll check it tomorrow and let you know my results.

**Comment by FANMixco** [comment]
I was able to fix it with a code like this one:

```csharp
 var jsonDocument = await JsonDocument.ParseAsync(stream);
 var jsonString = jsonDocument.RootElement.ToString();
 var responseJson = JsonSerializer.Deserialize<MyObject>(jsonString);
````
