### ISSUE TITLE
Test failure: Unknown chain building error in System.Net.Security.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#101835]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=664116
Build error leg or test failing: `Libraries Test Run release coreclr windows x64 Release`

## Error Message

```json
{
  "ErrorMessage" : [
    "ConnectWithRevocation_WithCallback",
    "CryptographicException : An unknown chain building error occurred."
],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/101832
- Queue: `Libraries Test Run release coreclr windows x64 Release`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=664116&view=logs&j=cb76e204-ba8f-557d-eba6-9896b4f24865&t=6d961345-b39a-56d5-e488-12bf17e2dc49&l=104
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-staging-aeb81f9dbcbc4224a4/System.Net.Security.Tests/3/console.d9c7487a.log?helixlogtype=result
- Output:
```
    System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback(checkRevocation: True) [FAIL]
      System.Security.Cryptography.CryptographicException : An unknown chain building error occurred.
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Chain.cs(192,0): at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Chain.cs(91,0): at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.cs(63,0): at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspFetch)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(265,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        --- End of stack trace from previous location ---
    System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback(checkRevocation: False) [FAIL]
      System.Security.Cryptography.CryptographicException : An unknown chain building error occurred.
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Chain.cs(192,0): at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Chain.cs(91,0): at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.Windows.cs(29,0): at System.Net.Security.SslStreamCertificateContext..ctor(X509Certificate2 target, ReadOnlyCollection`1 intermediates, SslCertificateTrust trust)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.cs(121,0): at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspFetch)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(265,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(313,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates, String testName)
        --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=664116
**Error message validated:** `[ConnectWithRevocation_WithCallback CryptographicException : An unknown chain building error occurred.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/3/2024 4:02:56 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[718949](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718949)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718949&view=ms.vss-test-web.build-test-results-tab&runId=18019044&resultId=220763)|dotnet/runtime#103922|
|[718293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718293)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718293&view=ms.vss-test-web.build-test-results-tab&runId=18001758&resultId=218173)|dotnet/runtime#103766|
|[713739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713739)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713739&view=ms.vss-test-web.build-test-results-tab&runId=17853990&resultId=185166)|dotnet/runtime#103646|
|[712969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712969)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712969&view=ms.vss-test-web.build-test-results-tab&runId=17831444&resultId=206460)|dotnet/runtime#103704|
|[712671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712671)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712671&view=ms.vss-test-web.build-test-results-tab&runId=17821232&resultId=217028)|dotnet/runtime#103695|
|[711611](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711611)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711611&view=ms.vss-test-web.build-test-results-tab&runId=17788918&resultId=217918)|dotnet/runtime#103564|
|[711234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711234)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711234&view=ms.vss-test-web.build-test-results-tab&runId=17778846&resultId=219125)|dotnet/runtime#103590|
|[710815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710815)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710815&view=ms.vss-test-web.build-test-results-tab&runId=17774374&resultId=207530)|dotnet/runtime#103590|
|[709562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709562)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709562&view=ms.vss-test-web.build-test-results-tab&runId=17719246&resultId=213369)|dotnet/runtime#103458|
|[707574](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707574)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707574&view=ms.vss-test-web.build-test-results-tab&runId=17717838&resultId=174467)|dotnet/runtime#103226|
|[706066](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706066)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706066&view=ms.vss-test-web.build-test-results-tab&runId=17613744&resultId=210479)|dotnet/runtime#103324|
|[705837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705837)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705837&view=ms.vss-test-web.build-test-results-tab&runId=17606884&resultId=215012)|dotnet/runtime#103372|
|[705719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705719)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705719&view=ms.vss-test-web.build-test-results-tab&runId=17604172&resultId=208298)|dotnet/runtime#103322|
|[703480](https://dev.azure.com/dnceng-public/public/_build/results?buildId=703480)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=703480&view=ms.vss-test-web.build-test-results-tab&runId=17525978&resultId=201640)|dotnet/runtime#103226|
|[701187](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701187)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701187&view=ms.vss-test-web.build-test-results-tab&runId=17450858&resultId=205057)|dotnet/runtime#103058|
|[699344](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699344)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699344&view=ms.vss-test-web.build-test-results-tab&runId=17429932&resultId=188087)|dotnet/runtime#102379|
|[700427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700427)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700427&view=ms.vss-test-web.build-test-results-tab&runId=17429422&resultId=203268)|dotnet/runtime#103152|
|[700188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700188)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700188&view=ms.vss-test-web.build-test-results-tab&runId=17424170&resultId=205088)|dotnet/runtime#103052|
|[699781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699781)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699781&view=ms.vss-test-web.build-test-results-tab&runId=17415896&resultId=184020)|dotnet/runtime#102656|
|[698604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698604)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698604&view=ms.vss-test-web.build-test-results-tab&runId=17382454&resultId=205111)|dotnet/runtime#103058|
|[694770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=694770)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=694770&view=ms.vss-test-web.build-test-results-tab&runId=17259184&resultId=204955)||
|[691690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=691690)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=691690&view=ms.vss-test-web.build-test-results-tab&runId=17180656&resultId=203401)|dotnet/runtime#102793|
|[689901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689901)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689901&view=ms.vss-test-web.build-test-results-tab&runId=17138794&resultId=204590)|dotnet/runtime#102628|
|[689748](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689748)|dotnet/runtime|[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689748&view=ms.vss-test-web.build-test-results-tab&runId=17135562&resultId=204754)|dotnet/runtime#102769|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|4|24|

**Comment by rzikm** [comment]
Weird, this should've been fixed with https://github.com/dotnet/runtime/pull/99950

**Comment by rzikm** [comment]
I am unable to reproduce this locally :/ Putting this on hold for now to see if it happens more often.

**Comment by rzikm** [comment]
Seems to happen also in main, but in outerloop/extra platforms only

**Comment by rzikm** [comment]
No new failures since merge, this looks promising.
