### ISSUE TITLE
'ConvertOrWidenPrimitivesEnumsAndPointersIfPossible' in NativeAOT is unnecessarily rooting 'BigInteger' (and a bunch more stuff) due to 'Convert.*' calls

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#101821]
While working on reducing the size for WinRT component using NativeAOT, we found some numeric stuff being kept:

![image](https://github.com/dotnet/runtime/assets/10199417/a4e418f1-44aa-4282-9334-2da407ecad05)

Quoting @MichalStrehovsky on Discord:

> "Looks like the Convert.ToSingle call in ConvertOrWidenPrimitivesEnumsAndPointersIfPossible is an overkill, we don't need code to parse floats since conversion from string to single would have been disallowed"

> This is the entire set that needs to be supported: https://github.com/dotnet/runtime/blob/fcc2408188269837221ff73f169de161aa47acac/src/coreclr/nativeaot/System.Private.CoreLib/src/System/InvokeUtils.cs#L225-L242. Calling into convert just calls IConvertible methods so instead of the subset, one gets conversions from everything that was allocated in the app and supports IConvertible (that's why you get `string -> double` conversions). I don't know if there's a better mechanism in the BCL. One could just inline conversions for the whole matrix since there is an upper bound but that may not pass Jan's code review. If you can find a more narrow codepath in the BCL that handles the subset, that would be a good fix"

Opening this issue for tracking. @jkotas do you happen to know whether there's already some helper we can reuse here, or do you have any suggestions on how we could remove that dependency on `Convert.*` calls? Would hardcoding all possible combinations be acceptable, or something else? 🙂

**Comment by jkotas** [comment]
We have number of copies of the wideling algorithm both in managed.

https://github.com/dotnet/runtime/blob/af889b9efd454c4ed513edbc59e92e22c78e3608/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Array.NativeAot.cs#L506
https://github.com/dotnet/runtime/blob/af889b9efd454c4ed513edbc59e92e22c78e3608/src/coreclr/nativeaot/System.Private.CoreLib/src/System/InvokeUtils.cs#L102eAot.cs#L506
https://github.com/dotnet/runtime/blob/af889b9efd454c4ed513edbc59e92e22c78e3608/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs#L234
https://github.com/dotnet/runtime/blob/af889b9efd454c4ed513edbc59e92e22c78e3608/src/libraries/System.Private.CoreLib/src/System/Reflection/InvokeUtils.cs#L14 

And several more in native code.

Avoiding IConvertible,in in the native AOT implementations sounds good to me if it is only ever used for primitives. Bonus points for making the different implementations more uniform. Physically sharing the code may be too hard - I am not sure.
