### ISSUE TITLE
[API Proposal]: Add new Environment properties to detect argv[0]

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#101872]
### Background and motivation

This is a proposal related to the issue:

- #101837 

Today, `Environment.GetCommandLineArgs()[0]` doesn't return always the real `argv[0]` that was passed when launching a command (via a shell or executable), which lead to the impossibility to create certain kind of command line apps (e.g [Busybox](https://busybox.net/) with all the symlinks from `ls`, `ps`...etc. to `busybox`).

Also it is impossible to recreate the real command line arguments because of implicit arguments put in `Environment.GetCommandLineArgs()[0]` in case for example we call `dotnet foo.dll`, `foo.dll` would end up in `Environment.GetCommandLineArgs()[0]` but if we wanted to recreate the same command line (e.g to relaunch the same process), we would not know that `Environment.GetCommandLineArgs()[0]` has to be taken into account.

So I propose that we introduce 2 new properties to be able to have a full understanding of the command line:

- `string? Environment.ProcessInvocationName` would always return the real `argv[0]` that was passed to the executable.
- `bool Environment.IsFirstCommandLineArgImplicit` would indicate if `Environment.GetCommandLineArgs()[0]` was actually generated implicitly and was not really part of the original command line argument (e.g it would return false in the case of `dotnet foo.dll 1 2 3`, but it would return `true` in the case of `foo.exe 1 2 3`)

The following table should clarify how this would be used to detect the different configuration:

| Command line | ? | `Environment.ProcessInvocationName` | `Environment.GetCommandLineArgs()`
|------------------|--------------|---------------|---------------
| `./dotnet.exe foo.dll 1 2 3`| `false` |  `./dotnet.exe`  | `foo.dll`, `1`, `2`, `3` |
| `./foo.exe 1 2 3`| `true` | `./foo.exe`  | `foo.dll`, `1`, `2`, `3`
| `./special_foo.exe 1 2 3` with `special_foo.exe` symlinked to `foo.exe`| `true` | `./special_foo.exe` | `foo.dll`, `1`, `2`, `3`
| `./special_foo.exe 1 2 3` with `special_foo.exe` symlinked to `foo.exe` (NativeAOT) | `true`| `./special_foo.exe` | `./special_foo.exe`, `1`, `2`, `3`

with ? = `Environment.IsFirstCommandLineArgImplicit`

### API Proposal

```csharp
namespace System;

public static partial class Environment
{
    /// <summary> Gets the real argv[0]</summary> 
    public string? Environment.ProcessInvocationName { get; }

    /// <summary> Gets a boolean indicating whether `Environment.GetCommandLineArgs()[0]`
    ///  is an implicit argument generated by the runtime.</summary> 
    public bool Environment.IsFirstCommandLineArgImplicit { get; }
}
```

### API Usage

```csharp
var argv0 = Environment.ProcessInvocationName;
if (argv0 is not null)
    Console.WriteLine(argv0);
```

### Alternative Designs

The proposal above has the merit to not introduce breaking changes but only new APIs.

Otherwise, the naming proposal could be different:

- For `Environment.ProcessInvocationName`: `Environment.ProcessInvocationArgument` or `Environment.CommandLineArgv0`
- For `Environment.IsFirstCommandLineArgImplicit`: `Environment.IsImplicitCommandLineArgv0` or `Environment.IsCommandLineArgv0Implicit`

### Risks

No risks

**Comment by nietras** [comment]
Third column in table appears mislabeled, should it be ProcessInvocationName?

**Comment by xoofx** [comment]
> Third column in table appears mislabeled, should it be ProcessInvocationName?

Oops, good catch, wrong copy/paste, fixed 👍

**Comment by xoofx** [comment]
This request is put on hold, as there is maybe a possible agreement to fix `GetCommandLineArgs()[0]` without creating a new API as proposed in the original issue #101837

**Comment by jkotas** [comment]
Closed in favor of https://github.com/dotnet/runtime/issues/101837
