### ISSUE TITLE
[8.0][osx] Test failure: ILLink.Tasks.Tests.TaskArgumentTests.TestRootDescriptorFiles

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#101833]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=664117
Build error leg or test failing: `osx-x64 release ILLink_Runtime_Testing` -> `ILLink.Tasks.Tests.TaskArgumentTests.TestRootDescriptorFiles(rootDescriptorFiles: ["combined_output.xml"])`

## Error Message

```json
{
  "ErrorMessage" : "##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: /Users/runner/work/1/s/artifacts/TestResults/Release/ILLink.Tasks.Tests_net8.0_x64.html [net8.0|x64]",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/101832
- Queue: `osx-x64 release ILLink_Runtime_Testing`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=664117&view=logs&j=a91d5b76-3942-50cd-febd-c34c63751c3f&t=712aa978-ed17-5b68-83cb-e734b77c2bad
- Artifacts: Expand OSX and open the file `ILLink.Tasks.Tests_net8.0_x64.log` https://dev.azure.com/dnceng-public/public/_build/results?buildId=664117&view=artifacts&pathAsName=false&type=publishedArtifacts
- Output:
```
xUnit.net Console Runner v2.4.2+f110e5bee5 (64-bit .NET 8.0.4)
[37m  Discovering: ILLink.Tasks.Tests
[m[37m  Discovered:  ILLink.Tasks.Tests
[m[37m  Starting:    ILLink.Tasks.Tests
[m[31;1m    ILLink.Tasks.Tests.TaskArgumentTests.TestRootDescriptorFiles(rootDescriptorFiles: ["combined_output.xml"]) [FAIL]
[m[37m      Assert.Equal() Failure
[m[37m                 ↓ (pos 0)
[m[37m      Expected: ["combined_output.xml"]
[m[37m      Actual:   []
[m[37m                 ↑ (pos 0)
[m[30;1m      Stack Trace:
[m[37m        /_/src/tools/illink/test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs(202,0): at ILLink.Tasks.Tests.TaskArgumentTests.TestRootDescriptorFiles(String[] rootDescriptorFiles)
[m[37m           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[m[37m           at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[m[37m  Finished:    ILLink.Tasks.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   ILLink.Tasks.Tests  Total: 105, Errors: 0, Failed: 1, Skipped: 0, Time: 1.769s
[m[m=== COMMAND LINE ===
"/Users/runner/.dotnet/dotnet" exec --depsfile "/Users/runner/work/1/s/artifacts/bin/ILLink.Tasks.Tests/Release/net8.0/ILLink.Tasks.Tests.deps.json" --runtimeconfig "/Users/runner/work/1/s/artifacts/bin/ILLink.Tasks.Tests/Release/net8.0/ILLink.Tasks.Tests.runtimeconfig.json"  "/Users/runner/work/1/s/.packages/xunit.runner.console/2.4.2/tools/netcoreapp2.0/xunit.console.dll" "/Users/runner/work/1/s/artifacts/bin/ILLink.Tasks.Tests/Release/net8.0/ILLink.Tasks.Tests.dll" -noautoreporters -xml "/Users/runner/work/1/s/artifacts/TestResults/Release/ILLink.Tasks.Tests_net8.0_x64.xml" -html "/Users/runner/work/1/s/artifacts/TestResults/Release/ILLink.Tasks.Tests_net8.0_x64.html"  > "/Users/runner/work/1/s/artifacts/log/Release/ILLink.Tasks.Tests_net8.0_x64.log" 2>&1

```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=664117
**Error message validated:** `[##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: /Users/runner/work/1/s/artifacts/TestResults/Release/ILLink.Tasks.Tests_net8.0_x64.html [net8.0|x64]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/3/2024 1:53:48 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[713017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713017)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/713017/logs/43)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by agocke** [comment]
Very weird, but hasn't reappeared. Closing.
