### ISSUE TITLE
`ObjectFactory<T>` delegate should be covariant

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#101829]
Current workaround is to use the non-generic ObjectFactory and cast but that shouldn't be necessary.

```cs
ObjectFactory<A> a = ...;
ObjectFactory<B> b = ...;
ObjectFactory<Base> f = c ? a : b;
return f(...);
```

### API Proposal
```diff
namespace Microsoft.Extensions.DependencyInjection;
- public delegate T ObjectFactory<T>(IServiceProvider serviceProvider, object?[]? arguments);
+ public delegate T ObjectFactory<out T>(IServiceProvider serviceProvider, object?[]? arguments);
```

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/blob/ee93104aa0e7ac77ca7e4c6db9873356a9e3e622/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ObjectFactoryT.cs#L15

**Comment by alrz** [comment]
Would it be possible to use `params ReadOnlySpan<object>` for the arguments here? 
(I suppose this would be considered as a part of new `params span` set of APIs though.)

**Comment by stephentoub** [comment]
> Would it be possible to use `params ReadOnlySpan<object>` for the arguments here? (I suppose this would be considered as a part of new `params span` set of APIs though.)

That would need to be an entirely different delegate and an entirely different set of APIs that take that delegate... just changing the delegate itself would be a binary breaking change.  Feel free to open a separate issue with such a proposal.

**Comment by alrz** [comment]
Opened https://github.com/dotnet/runtime/issues/101889

**Comment by steveharter** [comment]
@terrajobst is this on the backlog for API review?

**Comment by terrajobst** [comment]
Yeah, it's number 16 though. https://apireview.net/?q=objectfactory

**Comment by bartonjs** [comment]
Looks good as proposed

```diff
namespace Microsoft.Extensions.DependencyInjection;
- public delegate T ObjectFactory<T>(IServiceProvider serviceProvider, object?[]? arguments);
+ public delegate T ObjectFactory<out T>(IServiceProvider serviceProvider, object?[]? arguments);
```
