### ISSUE TITLE
[8.0][ios][arm64][mono] Build error: SecKeychainUnlock signing-certs.keychain-db: user name or passphrase incorrect

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#101830]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=663779
Build error leg or test failing: net8.0-ios-Release-arm64-Mono_Release

## Error Message

```json
{
  "ErrorMessage" : [
      "security: SecKeychainUnlock signing-certs.keychain-db: The user name or passphrase you entered is not correct.",
      "ERROR: WORKLOAD TIMED OUT - Killing user command.."
  ],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/101823
- Queue: `ios-arm64 Release AllSubsets_Mono`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=663779&view=logs&j=7f49df26-8126-5de3-bf2f-6ac6bde01830&t=c62b6a8c-bf71-5057-7f45-9c355fe0b802&l=57
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-101823-merge-37861f4604b94dd188/System.Runtime.Tests/1/console.da6c67dd.log?helixlogtype=result
- Output:
```
  [196/196] aot-instances.dll -> aot-instances.dll.s, aot-instances.dll-llvm.o, aot-instances.aotdata
  Running: cmake -S. -BSystem.Runtime.Tests -GXcode -DTARGETS_APPLE_MOBILE=1 -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
  Using working directory: /tmp/helix/working/99F2085F/w/B1F40915/e/apple_build/AppBundle/
  Exit code: 0
  Running: xcodebuild ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -arch arm64 -sdk iphoneos -configuration Release
  Using working directory: /tmp/helix/working/99F2085F/w/B1F40915/e/apple_build/AppBundle/System.Runtime.Tests
  Exit code: 0
  
  APP size: 1712.7 Mb.
  
  Xcode: /tmp/helix/working/99F2085F/w/B1F40915/e/apple_build/AppBundle/System.Runtime.Tests/System.Runtime.Tests.xcodeproj
  App: /tmp/helix/working/99F2085F/w/B1F40915/e/apple_build/AppBundle/System.Runtime.Tests/Release-iphoneos/System.Runtime.Tests.app
  App moved to: /private/tmp/helix/working/99F2085F/w/B1F40915/e/System.Runtime.Tests.app/
Signing /tmp/helix/working/99F2085F/w/B1F40915/e/System.Runtime.Tests.app
    "/Users/helix-runner/Library/Keychains/signing-certs.keychain-db"
security: SecKeychainUnlock signing-certs.keychain-db: The user name or passphrase you entered is not correct.
ERROR: WORKLOAD TIMED OUT - Killing user command..
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=663779
**Error message validated:** `[security: SecKeychainUnlock signing-certs.keychain-db: The user name or passphrase you entered is not correct. ERROR: WORKLOAD TIMED OUT - Killing user command..`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/3/2024 1:08:34 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by vitek-karas** [comment]
@matouskozak could you please check if this is an infra issue? It somehow reminds me of something, but I can't quite remember what...

**Comment by matouskozak** [comment]
> @matouskozak could you please check if this is an infra issue? It somehow reminds me of something, but I can't quite remember what...

It looks like an infra issue. I checked the first few hits and it keeps happening on DNCENGMAC050  machine. Could it be related to https://github.com/dotnet/dnceng/issues/2667 @AlitzelMendez ?

**Comment by AlitzelMendez** [comment]
yes, it seems to be related to this :) I will put the machine offline and do more debugging on the machine

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by matouskozak** [comment]
The machine is back running without issues. Closing.
