### ISSUE TITLE
[x64/Windows] waitone2 test failures

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#10181]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_jitstress1/491/consoleText

BEGIN EXECUTION
         "D:\j\workspace\x64_checked_w---02832afb\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" waitone2.exe 
        Beginning test case MutexWaitOne2 at 4/16/2018 7:33:49 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        [Positive]
        Beginning scenario: PosTest1: Wait Infinite
        Beginning scenario: PosTest2: Wait some finite time
        Beginning scenario: PosTest3: Wait some finite time will quit for timeout
        ERROR!!!-004: WaitOne returns true when wait time out
        Beginning scenario: PosTest4: Wait some finite time will quit for timeout when another thread is in nondefault managed context
        Beginning scenario: PosTest5: Wait some finite time will quit for timeout when another thread is in nondefault managed context
        Beginning scenario: PosTest6: Wait infinite time when another thread is in nondefault managed context
        Beginning scenario: PosTest7: Wait infinite time when another thread is in nondefault managed context
        [Negative]
        Beginning scenario: NegTest1: AbandonedMutexException should be thrown if a thread exited without releasing a mutex
        Beginning scenario: NegTest2: ObjectDisposedException should be thrown if current instance has already been disposed
        Beginning scenario: NegTest3: Check ArgumentOutOfRangeException will be thrown if millisecondsTimeout is a negative number other than -1
        
        Ending test case at 4/16/2018 7:34:22 PM
        FAIL
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_checked_w---02832afb\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_checked_w---02832afb\bin\tests\Windows_NT.x64.Checked\baseservices\threading\mutex\misc\waitone2\waitone2.cmd
  
        Expected: True
        Actual:   False

**Comment by kouvel** [comment]
The test doesn't exist anymore, closing
