### ISSUE TITLE
Custom JsonConverter CanConvert returns true but Read is never called.

### ISSUE THREAD

**Issue by DavidVollmers** [dotnet/runtime#101881]
Hi,

I am trying to deserialize a `string` into a `DictionaryInfo` class with support for relative paths. The idea was to write a custom `DirectoryInfoJsonConverter` with a constructor to pass the current working directory to prepend if the string is not a rooted path: 
https://github.com/DavidVollmers/doki/blob/features/class-lib-output/src/Doki.CommandLine/Json/DirectoryInfoJsonConverter.cs

To use this converter I simply add it to the `Converters` collection of the `JsonSerializerOptions` instance used to deserialized the `JsonElement`:
https://github.com/DavidVollmers/doki/blob/features/class-lib-output/src/Doki.CommandLine/Json/JsonOutputOptionsProvider.cs

Unfortunately this always results in having the `DirectoryInfo` to be `null`. While debugging I noticed that the `CanConvert` method of my custom JsonConverter is called and returns true as intended, but the `Read` method is never called.

Do you guys have any idea what I am doing wrong here?

**Comment by elgonzo** [comment]
No idea, but it looks like your problem is buried somewhere else in the code. It doesn't seem to be the converter, and it doesn't seem to be the deserialization code in the `JsonOutputOptionsProvider.GetOptions` method itself either. This can be demonstrated by building a code example with the converter and the relevant code from JsonOutputOptionsProvider.GetOptions and see how they behave: https://dotnetfiddle.net/Er3WTE. As can be seen from the dotnetfiddle, the converter Read method is called, and the DirectoryInfo is being correctly deserialized.

**Comment by DavidVollmers** [comment]
@elgonzo yes that was also my first assumption but as I said I debugged through it step by step. The `JsonElement` looks like this:

```json
{
  "outputPath": "docs/api"
}
```

The custom JsonConverter `CanConvert` method is called and used as "effective converter" (I decompiled the System.Text.Json lib to be able to step through it while debugging) but at some point it seems to be discarded or something else. The `Read` method is never called and the property is set to `null`.

I will investigate further and try to pin the problem down, but please let me know if you have any suggestions...

**Comment by DavidVollmers** [comment]
I could reproduce the issue by adding the `IOutputOptions` interface to the fiddle:
https://dotnetfiddle.net/9t55QO

But I am still not sure what the exact issue is.

**Comment by elgonzo** [comment]
Yes, it's the JsonPropertyName attribute on the interface and not on the type(s) being deserialized. The deserializer is being blind to the serialization-related attribute on the interface members when deserializing a derived type, unless you use polymorphic (de)serialization.

**Comment by DavidVollmers** [comment]
But `JsonPropertyAttribute` should be inherited right? At least the `Inherited` property of its `AttributeUsageAttribute` is set to `true`. This looks like a bug to me, escpecially since the converter is first used (`CanConvert` is called and returns `true`) but then at some point it is discarded.

Even if intended this behavior is the opposite of intuitive...

**Comment by elgonzo** [comment]
> But JsonPropertyAttribute should be inherited right? 

`AttributeUsageAttribute.Inherited` applies only to members inherited from base classes, not implementations of interface members. In other words, if you were to turn the interface into an abstract base class/record and override the OutputDirectory property, then the attribute would be inherited: https://dotnetfiddle.net/9t55QO

**Comment by DavidVollmers** [comment]
I see, that makes sense, thank you very much!

I see this as solved then :)
