### ISSUE TITLE
Moving to dotnet 8 causes a memory leak

### ISSUE THREAD

**Issue by vtortola** [dotnet/runtime#101907]
### Description

We have an application that reads messages from Azure Service Bus and process them. The processing pipeline is based on Microsoft TPL Dataflow library and it works well in dotnet 6 and 7.  The application processes around 2-3K messages per second.

Unfortunately when moving to dotnet 8 we have been experimenting some memory problems. In this issue, I am focusing in what it seems a memory leak of some type regarding Tasks.

We have another ongoing issue regarding to [dotnet 8 and the Large Object Heap](https://github.com/dotnet/runtime/issues/101906).

We created a new build of the application only changing the target framework and ran them side by side. We can see how the Gen 2 continuously increases its size, until our container orchestrator has to kill it.

Violet : dotnet 7
Orange: dotnet 8

Working set:
<img width="548" alt="image" src="https://github.com/dotnet/runtime/assets/704420/ca517e48-0255-49a0-8ea8-573e5cdf8cde">
The memory starts very hight because this other issue: https://github.com/dotnet/runtime/issues/101906

Gen 0:
<img width="547" alt="image" src="https://github.com/dotnet/runtime/assets/704420/34bbfa7d-9f9f-4d4f-9d70-63e081193f23">

Gen 1:
<img width="548" alt="image" src="https://github.com/dotnet/runtime/assets/704420/c062087e-86a5-4ebb-9517-6c29f83f1505">

Gen 2:
<img width="549" alt="image" src="https://github.com/dotnet/runtime/assets/704420/155cab48-f4e5-4087-b053-fc0c06a4f787">
Those sudden drops in Gen2 size is because I was running `dotnet-gcdump`.

### Configuration

Docker image: `mcr.microsoft.com/dotnet/aspnet:8.0.3`

Server: `Standard_F16s_v2 `

```
Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66
  RID:          linux-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Regression?

Yes. We ran the two versions side by side ensuring the only difference was the dotnet version used and it was easily reproducible.

### Data

Using `dotnet-dump` I can see some type of objects piling up in the Gen 2 area, specifically `Task` and `TaskCancellationSource`:

Dotnet 8:
```
> dumpgen gen2
...
00007f8e657c7d70    42496     38398670 System.Byte[]
00007f8e651ed7c8   789341     40795094 System.String
00007f8e7183e0e0  1396481     67031088 System.Threading.Tasks.Dataflow.DataflowBlock+OutputAvailableAsyncTarget<System.ValueTuple<Code.Azure.AzureServiceBusMessage, System.Int32>>
00007f8e715076e8  1396481     67031088 System.Threading.Tasks.Dataflow.Internal.Disposables+Disposable<System.Object, System.Threading.Tasks.Dataflow.Internal.TargetRegistry<System.ValueTuple<Code.Azure.AzureServiceBusMessage, System.Int32>>, System.Threading.Tasks.Dataflow.ITargetBlock<System.ValueTuple<Code.Azure.AzureServiceBusMessage, System.Int32>>>
00007f8e69633240  1497165    107795880 System.Threading.Tasks.Task<System.Boolean>
00007f8e67c68058  1498470    119877600 System.Threading.CancellationTokenSource+CallbackNode
0000561da6889480   217095    246302344 Free
Total 8113994 objects
```

```
> dumpgen gen2 
...
00007f8e7157e750   258725     12418800 System.Threading.Tasks.Dataflow.DataflowBlock+OutputAvailableAsyncTarget`1[[System.ValueTuple`2[[Azure.Messaging.ServiceBus.ServiceBusMessage, Azure.Messaging.ServiceBus],[System.Byte[], System.Private.CoreLib]][], System.Private.CoreLib]]
00007f8e71591a70   258725     12418800 System.Threading.Tasks.Dataflow.Internal.Disposables+Disposable`3[[System.Object, System.Private.CoreLib],[System.Threading.Tasks.Dataflow.Internal.TargetRegistry`1[[System.ValueTuple`2[[Azure.Messaging.ServiceBus.ServiceBusMessage, Azure.Messaging.ServiceBus],[System.Byte[], System.Private.CoreLib]][], System.Private.CoreLib]], System.Threading.Tasks.Dataflow],[System.Threading.Tasks.Dataflow.ITargetBlock`1[[System.ValueTuple`2[[Azure.Messaging.ServiceBus.ServiceBusMessage, Azure.Messaging.ServiceBus],[System.Byte[], System.Private.CoreLib]][], System.Private.CoreLib]], System.Threading.Tasks.Dataflow]]
00007f8e651ed7c8   364292     17498698 System.String
00007f8e657c7d70    37691     23525956 System.Byte[]
0000561da6889480    72123    118880104 Free
00007f8e7183e0e0  3539076    169875648 System.Threading.Tasks.Dataflow.DataflowBlock+OutputAvailableAsyncTarget<System.ValueTuple<Code.Azure.AzureServiceBusMessage, System.Int32>>
00007f8e715076e8  3539076    169875648 System.Threading.Tasks.Dataflow.Internal.Disposables+Disposable<System.Object, System.Threading.Tasks.Dataflow.Internal.TargetRegistry<System.ValueTuple<Code.Azure.AzureServiceBusMessage, System.Int32>>, System.Threading.Tasks.Dataflow.ITargetBlock<System.ValueTuple<Code.Azure.AzureServiceBusMessage, System.Int32>>>
00007f8e69633240  3797810    273442320 System.Threading.Tasks.Task<System.Boolean>
00007f8e67c68058  3799377    303950160 System.Threading.CancellationTokenSource+CallbackNode
Total 16453841 objects
```

In the other hand, if we look to the server in dotnet 7 that has been running even for longer time, the picture is other.
Dotnet 7:
```
> dumpgen gen2 
...
00007ff6152bb9d8     9574       872936 System.Int32[]
00007ff615875780    27286       950440 System.RuntimeType[]
00007ff616da2b58     6518       990736 System.Reflection.Emit.DynamicILGenerator
00007ff62033ddb0    14695      1074408 some.app.type[]
00007ff6145d9300    50663      1215912 System.Object
00007ff6153b66f8      626      1289738 System.Char[]
00007ff61523a510    11604      1333864 System.Object[]
00007ff61538e140    28260      1518760 System.String[]
00007ff616d51f90    19898      1591840 System.Signature
00007ff621d94850      389      1602680 NodaTime.TimeZones.CachingZoneIntervalMap+HashArrayCache+HashCacheNode[]
00007ff621d4b900    18539      1779744 NodaTime.TimeZones.ZoneInterval
00007ff616d51be0    20112      1930752 System.Reflection.RuntimeParameterInfo
00007ff615238398    54286      2171440 System.RuntimeType
00007ff615902a38    24271      2524184 System.Reflection.RuntimeMethodInfo
00007ff61b768ed0    55358      3985776 some.app.type
00007ff61a8aa718    39591      8234928 StatsdClient.Statistic.Stats
00007ff61578c2f0    43696     20702535 System.Byte[]
00007ff615361038   425074     21975404 System.String
0000560ce58c1b10     3469     49284528 Free
Total 1405068 objects
```

Allow me remark again that the same code runs without problems in dotnet 7 with same degree of activity, and the only change we have applied is changing the target framework.

I uploaded the GC dumps to a Windows machine to see if it sheds some light regarding who is hoarding those `Task` and `CancellationTokenSource`, and I see the method `System.Threading.Tasks.Dataflow.DataflowBlock.OutputAvailableAsync` playing some role in this issue.

In Dotnet 8 the method looks like this:
```csharp
    public static Task<bool> OutputAvailableAsync<TOutput>(
      this ISourceBlock<TOutput> source,
      CancellationToken cancellationToken)
    {
      if (source == null)
        throw new ArgumentNullException(nameof (source));
      if (cancellationToken.IsCancellationRequested)
        return Common.CreateTaskFromCancellation<bool>(cancellationToken);
      DataflowBlock.OutputAvailableAsyncTarget<TOutput> availableAsyncTarget = new DataflowBlock.OutputAvailableAsyncTarget<TOutput>();
      try
      {
        availableAsyncTarget._unlinker = source.LinkTo((ITargetBlock<TOutput>) availableAsyncTarget, DataflowLinkOptions.UnlinkAfterOneAndPropagateCompletion);
        if (availableAsyncTarget.Task.IsCompleted)
          return availableAsyncTarget.Task;
        if (cancellationToken.CanBeCanceled)
        {
          // ISSUE: reference to a compiler-generated field
          // ISSUE: reference to a compiler-generated field
          availableAsyncTarget._ctr = cancellationToken.Register(DataflowBlock.\u003COutputAvailableAsync\u003EO__23_0<TOutput>.\u003C0\u003E__CancelAndUnlink ?? (DataflowBlock.\u003COutputAvailableAsync\u003EO__23_0<TOutput>.\u003C0\u003E__CancelAndUnlink = new Action<object, CancellationToken>(DataflowBlock.OutputAvailableAsyncTarget<TOutput>.CancelAndUnlink)), (object) availableAsyncTarget);
        }
        return availableAsyncTarget.Task;
      }
      catch (Exception ex)
      {
        availableAsyncTarget.TrySetException(ex);
        availableAsyncTarget.AttemptThreadSafeUnlink();
        return availableAsyncTarget.Task;
      }
    }
```
And one of the fundamental differences between 7 and 8 is this line `return availableAsyncTarget.Task;`.
In dotnet 7 it does:
```csharp
return availableAsyncTarget.Task.ContinueWith<bool>(DataflowBlock.OutputAvailableAsyncTarget<TOutput>.s_handleCompletion, (object) availableAsyncTarget, CancellationToken.None, Common.GetContinuationOptions() | TaskContinuationOptions.NotOnCanceled, TaskScheduler.Default);
```
which invokes:
```csharp
internal static readonly Func<Task<bool>, object, bool> s_handleCompletion = (Func<Task<bool>, object, bool>) ((antecedent, state) =>
{
  (state as DataflowBlock.OutputAvailableAsyncTarget<T>)._ctr.Dispose();
  return antecedent.GetAwaiter().GetResult();
});
```
That `_crt` field is of type `CancellationTokenRegistrationSource`.

I ignore if this is really not necessary in dotnet 8 anymore 🤷

**Comment by mangod9** [comment]
Moving to Tasks area, we are tracking the GC issue as part of the linked issue.

**Comment by vtortola** [comment]
It seems that `OutputAvailableAsync` is indeed playing an important role. I can reproduce the issue with a small program:
```
using System.Buffers;
using System.Threading.Tasks.Dataflow;

var buffer = new BufferBlock<byte[]>(new DataflowBlockOptions { BoundedCapacity = 1000});
var cancellationSource = new CancellationTokenSource();

for (var i = 0; i < 50; i++)
{
    _ = Task.Run(async () =>
    {
        while (!cancellationSource.IsCancellationRequested)
        {
            var available = await buffer.OutputAvailableAsync(cancellationSource.Token);
            if(!available)
            {
                await Task.Delay(10);
                continue;
            }

            if (buffer.TryReceive(out var array)) 
                ArrayPool<byte>.Shared.Return(array);
        }
    });   
}

_ = Task.Run(async () =>
{
    while (!cancellationSource.IsCancellationRequested)
    {
        var array = ArrayPool<byte>.Shared.Rent(8192);
        await buffer.SendAsync(array, cancellationSource.Token);
    }
});

Console.ReadKey();
cancellationSource.Cancel();
Console.WriteLine("END");
```

<img width="1044" alt="image" src="https://github.com/dotnet/runtime/assets/704420/366d5448-fab5-4f2b-891c-867e5bbdf4f8">

<img width="1496" alt="image" src="https://github.com/dotnet/runtime/assets/704420/0f938cd4-6da2-4b66-a312-b148d6683d99">

```console
$ dotnet --info
.NET SDK:
 Version:           8.0.104
 Commit:            034f91fcc0
 Workload version:  8.0.100-manifests.cd97f1c9
```

Let me know if there is any other test you want me to run.

**Comment by stephentoub** [comment]
> This seems pretty clearly a mistaken change that was made during #80978 (Propagate cancellation tokens to TrySetCanceled in Dataflow), involving exactly the lines you pointed out at the bottom of the original post.
> 
> @stephentoub That was your change, and I don't see any rationale for removing disposing of the CTR when the task finishes. This means that for a long-lived CTS (like one that only gets disposed for process shutdown), these CTRs can just build up over time, keeping both themselves and the task alive until the CTS is cancelled or disposed. I have the feeling you intended to change to registering a continuation for disposing the CTR inside the `if(cancellationToken.CanBeCanceled)`, but it looks like that line was missed. Here is a link to the relevant part of the PR diff: https://github.com/dotnet/runtime/pull/80978/files#diff-4b0ea916f15ebd40a956b51e1d61fb1d499abd825bcab365f99cd578d0251d7fL1471

This is https://github.com/dotnet/runtime/issues/99564.

**Comment by vtortola** [comment]
That is right, it is the same issue. We can close this one. Many thanks.
