### ISSUE TITLE
DbgEnableMiniDump does not work with PublishSingleFile

### ISSUE THREAD

**Issue by Androvald** [dotnet/runtime#101957]
### Description

The functionality to automatically create dumps from crashing processes in the .NET runtime does not work when the creating single files binaries.

### Reproduction Steps

1. Create a C# console project
2. Add the code `throw new Exception("Test");`
3. Add a publish profile, set the runtime identifier to "linux-x64" or "win-x64", the deployment mode to "self-contained" and the check "Produce Single File"
4. Publish
5. Run the produced executable with DOTNET_DbgEnableMiniDump=1 or COMPlus_DbgEnableMiniDump=1 and DOTNET_DbgMiniDumpName or COMPlus_DbgMiniDumpName to produce the minidump in a known location.

### Expected behavior

The program should throw the exception and create a mini-dump in the location specified.

### Actual behavior

Windows: No mini-dump is generated, no output is generated.
Linux: No mini-dump is generated, the following error is displayed:
`
[createdump] Gathering state for process 2665 ExceptionHandli
[createdump] Crashing thread 0a69 signal 6 (0006)
[createdump] InitializeDAC: dlopen(/mnt/j/Projects/ExceptionHandlingTest/ExceptionHandlingTest/bin/Release/net8.0/publish/linux-x64/libmscordaccore.so) FAILED /mnt/j/Projects/ExceptionHandlingTest/ExceptionHandlingTest/bin/Release/net8.0/publish/linux-x64/libmscordaccore.so: cannot open shared object file: No such file or directory
[createdump] Target process is alive
[createdump] Failure took 47ms
Aborted
`

### Known Workarounds

Linux: Copy libmscordaccore.so from the output folder to the published folder, adding a second file to your single file output.

### Configuration

.NET 8, running on either x64 Windows or x64 Linux (Ubuntu / WSL2).
On .NET 7 it instead complains about the "createdump" program not existing on Linux.

**Comment by mikem8361** [comment]
Are you creating/publishing the C# test project in VS?  What version of VS and what version of .NET 8.0?

**Comment by mikem8361** [comment]
Can you attach the csproj file you used?

**Comment by Androvald** [comment]
Here is my project:
[ExceptionHandlingTest.zip](https://github.com/dotnet/runtime/files/15396837/ExceptionHandlingTest.zip)

**Comment by Androvald** [comment]
I'm using Visual Studio 2022, latest for my development, with .NET 8.0.103 on Ubuntu WSL2

**Comment by mikem8361** [comment]
I see what is going on, we only support full dumps for self-contained/single-file apps.  You need to also `export DOTNET_DbgMiniDumpType=4` which is full.  Like you said in the workarounds, copying libmscordaccore.so next to your app will allow you to create heap dumps (DOTNET_DbgMiniDumpType=2).

**Comment by Androvald** [comment]
Thanks for the answers, Mike. May I suggest adding these limitations to the documentation?

**Comment by mikem8361** [comment]
Better error message and the docs are updated.
