### ISSUE TITLE
[browser][MT] MONO_WASM: index out of bounds

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#101930]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=683975&view=logs&jobId=63c2d0c8-fec2-5788-81c8-f3ac95e8841f
Build error leg or test failing: WasmTestOnFirefox-MT-System.Threading.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/101843

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": ["MONO_WASM","index out of bounds"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 5/22/2024 12:40:42 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[762078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762078)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Xml.Linq.Streaming.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762078&view=ms.vss-test-web.build-test-results-tab&runId=19363644&resultId=191144)|dotnet/runtime#105709|
|[760113](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760113)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.CSharp.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760113&view=ms.vss-test-web.build-test-results-tab&runId=19338586&resultId=190418)|dotnet/runtime#105561|
|[760835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760835)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Extensions.Configuration.Ini.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760835&view=ms.vss-test-web.build-test-results-tab&runId=19323840&resultId=191139)||
|[760209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760209)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.Security.Enterprise.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760209&view=ms.vss-test-web.build-test-results-tab&runId=19303186&resultId=191126)|dotnet/runtime#105691|
|[758805](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758805)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Extensions.FileProviders.Physical.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758805&view=ms.vss-test-web.build-test-results-tab&runId=19260188&resultId=191122)|dotnet/runtime#104608|
|[757926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757926)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Extensions.Logging.Testing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757926&view=ms.vss-test-web.build-test-results-tab&runId=19230106&resultId=191154)|dotnet/runtime#104536|
|[754642](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754642)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Bcl.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754642&view=ms.vss-test-web.build-test-results-tab&runId=19163948&resultId=191132)|dotnet/runtime#105380|
|[753448](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753448)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753448&view=ms.vss-test-web.build-test-results-tab&runId=19132046&resultId=191019)|dotnet/runtime#105027|
|[753435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753435)|dotnet/runtime|[WasmTestOnFirefox-MT-System.IO.FileSystem.DriveInfo.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753435&view=ms.vss-test-web.build-test-results-tab&runId=19095352&resultId=191046)|dotnet/runtime#105298|
|[752424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752424)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Win32.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752424&view=ms.vss-test-web.build-test-results-tab&runId=19062326&resultId=191172)|dotnet/runtime#105340|
|[752180](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752180)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Extensions.Configuration.CommandLine.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752180&view=ms.vss-test-web.build-test-results-tab&runId=19056394&resultId=191155)|dotnet/runtime#105285|
|[750587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750587)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750587&view=ms.vss-test-web.build-test-results-tab&runId=19004800&resultId=100568)|dotnet/runtime#102144|
|[747416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747416)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747416&view=ms.vss-test-web.build-test-results-tab&runId=18896642&resultId=191078)|dotnet/runtime#104558|
|[745063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745063)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.XmlSerializer.Generator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745063&view=ms.vss-test-web.build-test-results-tab&runId=18827912&resultId=190637)|dotnet/runtime#103755|
|[744256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744256)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744256&view=ms.vss-test-web.build-test-results-tab&runId=18804948&resultId=191031)|dotnet/runtime#104558|
|[741916](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741916)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Console.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741916&view=ms.vss-test-web.build-test-results-tab&runId=18733076&resultId=190951)|dotnet/runtime#104558|
|[741278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741278)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Win32.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741278&view=ms.vss-test-web.build-test-results-tab&runId=18714622&resultId=191035)|dotnet/runtime#104536|
|[738889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738889)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Reflection.TypeExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738889&view=ms.vss-test-web.build-test-results-tab&runId=18640564&resultId=190966)|dotnet/runtime#104672|
|[737280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737280)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Xml.Linq.Properties.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737280&view=ms.vss-test-web.build-test-results-tab&runId=18591412&resultId=190955)|dotnet/runtime#104730|
|[733707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733707)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Extensions.FileSystemGlobbing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733707&view=ms.vss-test-web.build-test-results-tab&runId=18471724&resultId=189997)|dotnet/runtime#103837|
|[732111](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732111)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Text.Encoding.CodePages.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732111&view=ms.vss-test-web.build-test-results-tab&runId=18431598&resultId=189376)|dotnet/runtime#104103|
|[732173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732173)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Composition.TypedParts.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732173&view=ms.vss-test-web.build-test-results-tab&runId=18425928&resultId=189762)|dotnet/runtime#104445|
|[731168](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731168)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Reflection.Context.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731168&view=ms.vss-test-web.build-test-results-tab&runId=18393560&resultId=189709)||
|[729374](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729374)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Xml.Linq.Axes.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729374&view=ms.vss-test-web.build-test-results-tab&runId=18339558&resultId=189754)|dotnet/runtime#104361|
|[728826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=728826)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Buffers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=728826&view=ms.vss-test-web.build-test-results-tab&runId=18330532&resultId=189696)|dotnet/runtime#104309|
|[727882](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727882)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.ServerSentEvents.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727882&view=ms.vss-test-web.build-test-results-tab&runId=18316342&resultId=189743)|dotnet/runtime#104206|
|[727781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727781)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Reflection.Emit.Lightweight.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727781&view=ms.vss-test-web.build-test-results-tab&runId=18281838&resultId=190028)|dotnet/runtime#103837|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|7|27|

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-102549-merge-dda7d3c0119b446ea6/WasmTestOnFirefox-MT-System.Formats.Asn1.Tests/1/console.923b07fa.log?helixlogtype=result)
```
[10:47:14] info: 001 | 0x01650328-dpty: isRunning:false isAttached: true isEventLoop:false reuseCount:  1 -
[10:47:14] fail: [0x01650328-dpty 10:47:13.987] MONO_WASM: index out of bounds
                 @mono_wasm_load_runtime (http://127.0.0.1:44465/_framework/dotnet.native.wasm:wasm-function[1355]:0x79545
                 @http://127.0.0.1:44465/_framework/dotnet.native.wasm:wasm-function[196]:0x14a0b)
                 createDotnetRuntime</</Module._mono_wasm_load_runtime@http://127.0.0.1:44465/_framework/dotnet.native.js:8:141271
                 ccall@http://127.0.0.1:44465/_framework/dotnet.native.js:8:127294
                 cwrap/<@http://127.0.0.1:44465/_framework/dotnet.native.js:8:127674
                 Nl</</</<@http://127.0.0.1:44465/_framework/dotnet.runtime.js:3:204157
                 Nl</</<@http://127.0.0.1:44465/_framework/dotnet.runtime.js:3:204285
[10:47:14] info: WASM EXIT 1
```

**Comment by pavelsavara** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/104271
