### ISSUE TITLE
ILLink: Preserve implementation for default static interface methods

### ISSUE THREAD

**Issue by vyacheslav-volkov** [dotnet/runtime#102008]
### Description

The llinker doesn't preserve default static methods but it works for non-static methods, I think the behavior should be the same in both cases.

### Reproduction Steps

```
public interface ITestBase
{
    static virtual string InvokeStatic() => throw new NotSupportedException();

    string Invoke() => throw new NotSupportedException();
}

public interface ITest : ITestBase
{
    static string ITestBase.InvokeStatic() => "Test";

    string ITestBase.Invoke() => "Test";
}

public class TestImpl : ITest
{
}

public static class TrimEx
{
    public static string Test<T>() where T : ITestBase => T.InvokeStatic();
}


void Main()
{
    ITest testImpl = new TestImpl();
    testImpl.Invoke();//returns "Test"
        
    TrimEx.Test<TestImpl>(); //throws NotSupportedException instead of "Test" value
}

```

### Expected behavior

The `InvokeStatic` method should return the `Test` string instead of `NotSupportedException` as it works for the non-static `Invoke` method. 

### Actual behavior

The `InvokeStatic` method throws `NotSupportedException` because the implementation from the `ITest` interfaces was removed by the linker.

### Configuration

net7.0, net8.0 with PublishTrimmed=true

**Comment by huoyaoyuan** [comment]
Looks related to #98536

**Comment by jtschuster** [comment]
Thank you for the detailed repro! This was fixed in https://github.com/dotnet/runtime/pull/96821 and https://github.com/dotnet/runtime/pull/97487 which are in the latest .NET 9 previews.
