### ISSUE TITLE
[API Proposal]: Add new string to ToList

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#102099]
### Background and motivation

https://github.com/dotnet/runtime/blob/9eac175d6a59a94b85ae2122b05c487a33eda788/src/coreclr/tools/Common/Internal/LowLevelLinq/LowLevelEnumerable.ToList.cs#L10

I suggest adding a check for an array in the ToList method, and if it's an array, the new List should be created using the List constructor.

### API Proposal

Now
```
     public static List<T> ToList<T>(this IEnumerable<T> source)
        {
            List<T> result;

            var collection = source as ICollection<T>;
            if (collection != null)
                result = new List<T>(collection.Count);
            else
                result = new List<T>();

            foreach (var element in source)
                result.Add(element);

            return result;
        }
```
after
```csharp
public static List<T> ToList<T>(this IEnumerable<T> source)
{
    if (source is T[])
        return new List<T>(source);
    List<T> result;

    var collection = source as ICollection<T>;
    if (collection != null)
        result = new List<T>(collection.Count);
    else
        result = new List<T>();

    foreach (var element in source)
        result.Add(element);

    return result;
}
```

### API Usage

```csharp
```

**Comment by stephentoub** [comment]
> I suggest adding a check for an array in the ToList method, and if it's an array, the new List should be created using the List constructor.

That is not the implementation of Enumerable.ToList. Enumerable.ToList is here:
https://github.com/dotnet/runtime/blob/56d7e5d80ed6dd5e80ca8225ab689a60cae3cfc7/src/libraries/System.Linq/src/System/Linq/ToCollection.cs#L60-L75
and for an array will already just delegate to the `List<T>` ctor.
