### ISSUE TITLE
System.Numerics.Tests.op_rightshiftTest.LargeNegativeBigIntegerShiftTest

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#102087]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=671466
Build error leg or test failing: System.Numerics.Tests.op_rightshiftTest.LargeNegativeBigIntegerShiftTest
Pull request: https://github.com/dotnet/runtime/pull/101977

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.Numerics.Tests.op_rightshiftTest.LargeNegativeBigIntegerShiftTest() in /_/src/libraries/System.Runtime.Numerics/tests/BigInteger/op_rightshift.cs:line 33",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=671466
**Error message validated:** `[at System.Numerics.Tests.op_rightshiftTest.LargeNegativeBigIntegerShiftTest() in /_/src/libraries/System.Runtime.Numerics/tests/BigInteger/op_rightshift.cs:line 33`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/10/2024 5:08:42 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by tannergooding** [comment]
This was resolved in https://github.com/dotnet/runtime/pull/102874
