### ISSUE TITLE
AssemblyNameInfo.FullName does not include public key

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#102051]
## Repro

```csharp
using System.Reflection;
using System.Reflection.Metadata;

var mscorlib = "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKey=00000000000000000400000000000000";

Console.WriteLine(new AssemblyName(mscorlib).FullName);
Console.WriteLine(AssemblyNameInfo.Parse(mscorlib).FullName);
```

## Actual result

```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
mscorlib, Version=4.0.0.0, Culture=neutral
```

## Expected result

PublicKey (or PublicKeyToken) is included in `AssemblyNameInfo.FullName`

**Comment by jkotas** [comment]
@adamsitnik I have run into this while working on https://github.com/dotnet/runtime/pull/102036. I see that you have mentioned this behavior in the documentation, but it is not the behavior that I would expect.

Somewhat related to this issue is a problem with conversions of PublicKey to PublicKeyToken. In #102036, I ended up calling into AssemblyName for this conversion in number of places, but it does not look pretty. Would it make sense to have a public API for it?

**Comment by adamsitnik** [comment]
> PublicKey (or PublicKeyToken) is included in `AssemblyNameInfo.FullName`

IIRC we did not want the `AssemblyNameInfo` to perform any conversions and validations of the PublicKey[Token]. 

Would including `PublicKey` in `AssemblyNameInfo.FullName` be enough for your scenario?

Have used it [here](https://github.com/dotnet/runtime/blob/5376eca94c2f31a5987459225af35c8811ea8ad3/src/coreclr/tools/Common/TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs#L127-L130) just to let it be a key in the dictionary (and part of the info was missing) or did you also want to treat two `AssemblyNameInfo` instances, one with `PublicKey` and another with `PublicKeyToken` that map to the same `PublicKeyToken` as equal?

**Comment by adamsitnik** [comment]
> Yes, I would address the behavior that I did not expect.

Great, then we agree on the solution.

When it comes to the fix I am currently busy with... backporting Full Framework with Security updates and finishing the PayloadReader API. I think I should be able to get back to this in +- 2 weeks.

**Comment by buyaa-n** [comment]
@adamsitnik is this still planned for 9.0?

**Comment by adamsitnik** [comment]
> @adamsitnik is this still planned for 9.0?

Yes, thank you for the reminder! I've sent #105649 to address it.
