### ISSUE TITLE
Application Not Looking in Working Directory for .NET

### ISSUE THREAD

**Issue by yannip1234** [dotnet/runtime#102028]
### Description

On macOS x64, I have the .NET Runtime installed into a custom directory where my application is also installed. When I try to run my application, it gives a .NET not found error. I set the environment variable DOTNET_ROOT to the directory and the application launches correctly. But, due to a limitation, I cannot set DOTNET_ROOT. It seems like the application is not looking in the working directory for the dotnet executable in addition to the environment variable and the PATH. On Linux, the configuration above works correctly. 

### Reproduction Steps

1. On macOS 13.6.5 x64, Run the application on a system where .NET is not installed in the default directory.
2. Note that the application fails to launch and prompts to install .NET.
3. Move application to the directory where dotnet is installed and attempt to run the application again.

### Expected behavior

the application should detect .NET when in the same working directory as the dotnet binary and run. 

### Actual behavior

It does not launch and gives a “You must install .NET to run this application and  a .NET location not found error. 

### Configuration

.net 6,7,8

**Comment by agocke** [comment]
What do you mean exactly by "I have the .NET Runtime installed into a custom directory where my application is also installed"? Can you fully describe the exact layout of your application and the steps you took to set this up?

**Comment by yannip1234** [comment]
I downloaded the .NET Runtime binaries from https://dotnet.microsoft.com/en-us/download/dotnet/6.0. I extracted the files into a folder "A" where I also have an application "GatewayOSX". When I try to run my application, I get this error:

```
You must install .NET to run this application.

App: <path_to_A>/GatewayOSX
Architecture: x64
App host version: 6.0.15
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx.13-x64&apphost_version=6.0.15
```

When I run the dotnet executable itself I get the following which is expected.
```
sh-3.2# <path_to_A>/dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
sh-3.2# /opt/IRIS/dotnet60/dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.29
  Architecture: x64
  Commit:       189fbbd88d

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.29 [/opt/IRIS/dotnet60/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by yannip1234** [comment]
Never mind, I fixed it! I looked through the code and saw that hostfxr needs to be in the root path. The script that I used to install dotnet created a broken symlink to libhostfxr.dylib as libhostfxr.so in the root path. I created a correct symlink with the dylib extension and my program launched.

<img width="1090" alt="image" src="https://github.com/dotnet/runtime/assets/2459177/c89d22dc-35eb-4815-ba9a-55cd730c8b51">

**Comment by agocke** [comment]
FYI the way you are deploying the app is functionally equivalent to a "self-contained" deployment. If you do that, this will be a supported scenario. What you're doing right now is not supported.

**Comment by yannip1234** [comment]
Thank you. Normally, our users will have dotnet installed in the proper paths.

**Comment by agocke** [comment]
If you decide to use self-contained deployment, instructions are at https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained
