### ISSUE TITLE
The JSON property name for 'IMyPoco3.Bar' collides with another property

### ISSUE THREAD

**Issue by MJB222398** [dotnet/runtime#102043]
### Description

This issue is a regression. I was updating from .NET 6 to .NET 8 and am now encountering this exception. Seems related to #93903 but is not quite the same - that one has been fixed.

### Reproduction Steps

```
using System.Text.Json;
using System.Text.Json.Serialization;

public static class JsonBug
{
    public static void Reproduce()
    {
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
        };

        string json = JsonSerializer.Serialize(new MyPoco1(), typeof(IMyPoco3), options);
        Console.WriteLine(json);
    }
}

public class MyPoco1 : MyPoco2, IMyPoco3
{
    [JsonPropertyName("gubbins")]
    public int Gubbins { get; set; }

    int IMyPoco3.Foo => 14;
}

public class MyPoco2
{
    [JsonIgnore]
    public int Bar { get; set; }
}

public interface IMyPoco3 : IMyPoco4
{
    [JsonPropertyName("bar")]
    int Foo { get; }
}

public interface IMyPoco4
{
    int Bar { get; }
}
```

### Expected behavior

The JsonIgnoreAttribute on MyPoco2.Bar should mean that this property is not considered as being a duplicate property.

### Actual behavior

System.InvalidOperationException: 'The JSON property name for 'IMyPoco3.Bar' collides with another property.'

### Regression?

Yes it worked in .NET 6

### Known Workarounds

A workaround could be to change the property name or the JsonPropertyName but this is a public API and if I did this it would be a breaking change so I will not.

**Comment by eiriktsarpalis** [comment]
This is due to .NET 8 adding support for [interface hierarchies](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/). The serialization contract for the type `IMyPoco4` now includes the properties from `IMyPoco3` which creates the conflict:
```C#
var options = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true,
};

JsonSerializer.Deserialize<IMyPoco3>("{}",options);

public interface IMyPoco3 : IMyPoco4
{
    [JsonPropertyName("bar")]
    int Foo { get; }
}

public interface IMyPoco4
{
    int Bar { get; }
}
```
One workaround would be to add to a `[JsonIgnore]` annotation on the property of `IMyPoco4`.
