### ISSUE TITLE
System.Text.Json of T Recursive call and nested objects

### ISSUE THREAD

**Issue by vintzl** [dotnet/runtime#1020]
Can we have a new method to override in System.Text.Json of JsonConverter<T>, especially the `Writer` method? (A rewrite would be better, but it will be a breaking change…)

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L53

Indeed, it would be better to have `Type value` instead of `T value` as the later is very limiting…
`Type value` is "a must have" for recursive call, when there are nested objects…

Or maybe there is something I have missed?

**Comment by ahsonkhan** [comment]
Can you share a code sample of how you would use such an API to showcase why it is necessary?

Also, since this is an api suggestion, please take a look at this guideline for what to include in the proposal (specifically, motivation, requirement, and usage code sample):
https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

Here's a good example:
https://github.com/dotnet/corefx/issues/271

**Comment by vintzl** [comment]
# Reason
Changing the definition of
- `System.Text.Json.Serialization.JsonConverter<T>.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options);`

to something like
- `System.Text.Json.Serialization.JsonConverter<T>.Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options);`

is  "a must have" for recursive call, when there are nested objects…

## Newtonsoft.Json case
The `JsonConverter` abstract class, from `Newtonsoft.Json`, has the following signature:
- `public abstract void WriteJson(JsonWriter writer, object value, JsonSerializer serializer);`

Of course it allows recursive calls…

## System.Text.Json case
The `JsonConverter` abstract class, from `System.Text.Json`, has the following signature:
- `public abstract void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options);`

Unfortunately it does not allow recursive calls…

### The issue

Following this extract taken from [this sample](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Text.Json/tests/Serialization/CustomConverterTests.Polymorphic.cs):

With such objects:

    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Address Home { get; set; }
    }

    public class Address
    {
        public string Street { get; set; }
    }


I can not call recursively the `System.Text.Json` `Write` method…

Here an example inspired of one of my project. The code is not tested, but I hope it will be clear enough…

If I try to migrate this kind of code from `Newtonsoft.Json` to `System.Text.Json`, I got this obvious issue:

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            var getters = viewModel.GetType().GetProperties(
                            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).ToList();
            var type = Regex.Replace(viewModel.GetType().FullName, @"((.+\.)(\w+)$)", "$3");

            if (depth == 0)
            {
                writer.WriteStartObject();
            }

            writer.WritePropertyName(type);
            writer.WriteStartObject();

            foreach (var getter in getters)
            {
                var value = viewModel.GetType().GetProperty(getter.Name, BindingFlags.NonPublic
                        | BindingFlags.Public | BindingFlags.Instance).GetValue(viewModel);
                var prop = getter.Name.First().ToString().ToUpper() + getter.Name.Substring(1);
                if (!getter.GetType().FullName.Contains("System"))
                {
                    depth += 1;
                    var obj = viewModel.GetType().GetProperty(prop);
                    writer.WritePropertyName(prop);
                    Write(writer, obj, options); // HERE THE ISSUE
                    depth -= 1;
                }
                else
                {
                    writer.WriteString(getter.Name, value?.ToString());
                }
            }

            writer.WriteEndObject();
            if (depth == 0)
            {
                writer.WriteEndObject();
            }
        }

And this is worsten with Collections of objects, etc…

# Proposed API
Change the current `JsonConverter<T>.Write` method to something like this (like Newtonsoft.Json):
- `System.Text.Json.Serialization.JsonConverter<T>.Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options);`

Sorry, as always I'm in a hurry…

**Comment by vintzl** [comment]
I have forget… The Same will apply with `Read` method…

**Comment by steveharter** [comment]
You can re-enter the serializer from a converter by calling the non-generic methods. For example:
```
    JsonSerializer.Serialize(ref writer, myObject, myObject.GetType(), options);
```

Closing this. Please re-open if necessary.
