### ISSUE TITLE
[API Proposal]: `ValueTask.ConfigureAwait(ConfigureAwaitOptions)`

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#102019]
### Background and motivation

`Task.ConfigureAwait(ConfigureAwaitOptions)` is useful in some niche cases. For example, we have a situation where two threads can await on a task, but we only want exceptions to bubble up from one of them, not both. Specifically, one thread is waiting for the other to complete so it can take its turn, but the other one actually executing the task should rethrow any exceptions. 

So, for the thread that should ignore exceptions, we use `await theTask.ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing)`, and the other one uses the normal `await theTask`. As an added benefit, this disables capturing of the context, which is useful for library developers.

That API does not exist for `ValueTask`; Only the original `ConfigureAwait(bool)` one does.

### API Proposal

```csharp
namespace System.Threading.Tasks;

public readonly struct ValueTask
{
    public ConfiguredValueTaskAwaitable ConfigureAwait(ConfigureAwaitOptions options);
}

public readonly struct ValueTask<TResult>
{
    public ConfiguredValueTaskAwaitable<TResult> ConfigureAwait(ConfigureAwaitOptions options);
}
```

### API Usage

```csharp
ValueTask theTask;
// ...
await theTask.ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
```

### Alternative Designs

For our specific use case, two options are currently available: (a) swallow the exception, or (b) wrap it in a task and `ConfigureAwait` _that_ task.

```csharp
ValueTask theTask;
// ...
try
{
    await theTask;
}
catch
{
    // intentionally ignored here due to XYZ
}
```

```csharp
ValueTask theTask;
// ...
await theTask.AsTask().ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
```

Alternatively, we could use a `TaskCompletionSource` that thread A (the one that should suppress exceptions) would `await`, and thread B (the one that should rethrow it) would mark as completed.

**Comment by stephentoub** [comment]
> That API does not exist for ValueTask

It was discussed and decided against as part of https://github.com/dotnet/runtime/issues/22144#issuecomment-1561983918.

**Comment by colejohnson66** [comment]
Unless I'm missing something, I don't see any discussion _against_ `ValueTask` having this API, just that having it on `Task<TResult>` doesn't make much sense. The API review comment even says, "We may consider the ValueTask family in later releases."

**Comment by colejohnson66** [comment]
Ah. I forgot that `ValueTask`s can't be used after awaiting.
