### ISSUE TITLE
Unifying Integer types

### ISSUE THREAD

**Issue by eSPiYa** [dotnet/runtime#102049]
### Is your feature request related to a problem? Please describe.
I'm sorry, english isn't my primary language, so please forgive me for any grammar mistakes.

Anyway, for some(if not most) .NET devs, we don't really care which kind of integer type we use, we just usually use int by default which is int32. I know that the reason why we do different types of integer is for optimization. But is it not possible for the runtime to automatically adjust it on the fly?

Having multiple types of integer can make different libraries hard to bridge. Yes, we can cast int64 to int32, as long as the number don't exceed it. But what if the result did exceed it? This will limit the usage of other classes or libraries. 

Example: A while ago, I'm trying to use `ItemsProviderResult` and the second parameter is an int for the total count of items. While the count function in my database(PostgreSQL) is a BigInt which an int64. As of now, after performing some querying, the count is just measly 16k out of 40k of records. And it continuously grows around 20k records each day. It won't be a problem any time soon, but it can be in the future. There's a higher chances to show up in a different scenario.

### Describe the solution you'd like
What I can think about is to have a size-varying integer and make it the base and default for all of the integers. This will ensure backward compatibility. The size will just become an initial allocation and not the limit, as you assign larger numbers, it will automatically adjust. I don't know how feasible is this, but I believe there's a good chance that this become possible with a probability of small performance loss.

If you assign a long/int64 variable to an int32 variable, it will automatically readjust depends on the actual content of the other variable.

For example the following code
```cs
long myInt64 = 7777777777777777777; // will allocate as int64 with value
int32 myInt32 = 100; // will allocate as int32
short myInt16 = 50; // will allocate as int16 with value of 50
myInt16 = myInt32; // will retain as int16 because the value of myInt32 didn't exceed int16's max value
myInt16 = myInt64; // will re-allocate as int64 because it is the largest integer that can accommodate the value that myInt64 holds
```

Down-sizing can be added too with the right logic.

For those that are very particular about the size, specially for performance, we can add some kind of option that makes it stick to that size. Like using exclamation point on the variable type like this `int64! postCount = 1000;`, `Strict<int16> productsCount = 23;`, or something. I don't know if this was used already, I just recently learned that exclamation point can be used to mark to make a variable null-forgiving. Question-mark after the variable type marks the type to be nullable.

**Comment by huoyaoyuan** [comment]
> But is it not possible for the runtime to automatically adjust it on the fly?

Numbers are value types. Their storage is typically embedded into other locations, like stack, array, or field of object. A number is not to be "adjusted". A location of expected length is provided to store the number.

> I don't know how feasible is this, but I believe there's a good chance that this become possible with a probability of small performance loss.

It breaks performance totally. Numbers are primitive and used everywhere. They are passed in fixed length. To support variable length, `BigInteger` like solution is required. It's not compatible to any existing code, and results in worse performance too.

---

It is a pain that some numbers in .NET ecosystem are limited to 32 bit, including the length of array/span. But the performance is too sensitive here. Simply inserting a shim that converts between int32 and int64 will make performance unacceptable.

**Comment by eSPiYa** [comment]
@KalleOlaviNiemitalo 

> C# already has the dynamic type, which can do arithmetic without having to choose the runtime type at compile time.

My case is about integer compatibility between classes/libraries that I don't have a control on what kind of int they use or produce. So dynamic won't really help. What I'm proposing is to unify them and make the CLR adjust the size on the fly. And I don't think the performance would be that bad, because it will only re-adjust once it exceeded the upper limit of the value and it will stay like that. Also, I think it won't get worse than an int64 running on 32-bit system.

> It would also break compatibility with existing code that uses these fixed-size types in file formats, network protocols, or Platform Invoke.

I considered this, that's why I mentioned that the underlying implementation of all int is based on a size-varying int, this probably can be achieved within the CLR too. When you declared it as long, int, or short, it will allocate the size of the declared type, unless you assigned a value that is larger than the declared size.

@huoyaoyuan 

> It breaks performance totally. Numbers are primitive and used everywhere. They are passed in fixed length. To support variable length, BigInteger like solution is required. It's not compatible to any existing code, and results in worse performance too.

Will there be a huge performance issue? It will only happen when you assign it with a value that is higher than its current capacity, and it will not happen that often. Like, it will happen twice at most in a single variable, but most of the time it won't for old codes. Also, casting an int32 to int64 have no noticeable performance issue, right? The probable underlying implementation in the CLR would be to create a new higher capacity integer, then deallocate the previous one.

Regarding backward compatibility, I made an answer to Kale, just a bit above within this comment. And if you pass the value and the value is higher that the declared capacity, then it will automatically use the next higher type that can handle the said value. This behavior will cascade to variables in the constructors too. So in the end, the chances of readjustments will be limited.

The goal for this proposal is to make existing classes/libraries that we don't have much control to become more compatible. Casting an int64 to int32 feels like more a band-aid fix, and once it won't work, the class/library where you need to use it won't work anymore. It will be lucky if the 3rd-party library is an open source one, but it will take time before you would be able to implement it. However, if it is a closed-source, time can tell when they'll support a higher capacity integer.

**Comment by danmoseley** [comment]
> The probable underlying implementation in the CLR would be to create a new higher capacity integer, then deallocate the previous one.

As @huoyaoyuan mentioned above, integers are value types which means they generally exist "in place" and cannot themselves be de allocated nor widened. It would require something quite different like `dynamic` that adds considerable overhead in memory and CPU.

Let's return to what you are trying to achieve. Can you give a concrete example of an API (notionally from a library) and how you are seeking to consume it?

**Comment by eSPiYa** [comment]
> As @huoyaoyuan mentioned above, integers are value types which means they generally exist "in place" and cannot themselves be de allocated nor widened. It would require something quite different like dynamic that adds considerable overhead in memory and CPU.

I get that part, my proposal is recreate that variable with higher capacity when the new assigned value became higher, and the previous location will get recycled.

> Let's return to what you are trying to achieve. Can you give a concrete example of an API (notionally from a library) and how you are seeking to consume it?

My recent encounter with this issue is regarding virtualization in Blazor and the query result with PostgreSQL. The virtualization uses the class `ItemsProviderResult` and its parameter for total count of items is int32, while the count function in PostgreSQL is a BigInt/int64. On the UI designer side, it is probably a bad design to display 2B records in there. But on the technical side, even if it works most of the time, casting int64 down to int32 looks really not good for me.

**Comment by danmoseley** [comment]
> my proposal is recreate that variable with higher capacity when the new assigned value became higher, and the previous location will get recycled.

Recycled how? An integer, as a "value type" generally has no identity to the GC, it is part of a larger type. Consider also that there is code that assumes the size of that type, which would somehow have to be recompiled, also all code that assumes the size of the integer itself. I do not believe what you are describing can be reasonably achieved at this level. 

A cast is the correct way to deal with this. It forces you to make a decision about the behavior you want.

**Comment by danmoseley** [comment]
In your case, for example, you have decided that it doesn't make sense to have over 2 billion entries in your UI. So an int is fine, and your can do a "checked cast" so that the code throws when there are more than int.MaxValue.

**Comment by tannergooding** [comment]
> Will there be a huge performance issue? It will only happen when you assign it with a value that is higher than its current capacity, and it will not happen that often.

In order to handle that in the first place every single arithmetic operation would need to become `checked` and therefore something which was previously just:
```asm
add dst, op1, op2
...
```

Now has to become something like:
```asm
add dst, op1, op2
jo handle_overflow
...

handle_overflow:
    ; extend operands up
    ; fixup various structs, locals, and other locations
    ; continue computation
```

So even in the case that no overflow happens, you're now inserting a branch after every single arithmetic operation, which completely breaks the ability for the CPU to pipeline instructions, to do proper branch prediction, etc. There are things the JIT could do to mitigate this, but not without themselves incurring cost and making code run slower.

So yes, there is significant cost even in the case overflow never happens.

**Comment by tannergooding** [comment]
Going to close this as inactionable.

As indicated by other responses above, doing this would be massively breaking to the ecosystem and is not feasible, particularly not in a way that allows for perf, type safety, and other considerations to be maintained.

Types should be authored with the consideration of what bounds are feasible for them to hit. If you truly need more than can be represented in 32-bits, then use 64-bits. If you need more than can be represented in 64-bits, consider 128-bits or BigInteger. This requires up front consideration of what is realistic to be hit and also factors in the consideration of when it would be appropriate for things to be split instead (having more than 2.14 billion items is not necessarily the same as having that many items in a single table or database, often you want to split them for more efficient access, for example).

**Comment by tannergooding** [comment]
> If the CPU predicts these forward branches not to be taken when it first sees them, and the predictions are correct, then does it save that branch history and thereby have to evict the history of some other branches that would have been more useful to keep?

Yes, that is a possibility.

Branch predictors can only do so much, they can only track so many branches, and the branches themselves (whether taken or not) can break pipelining or other optimizations (the ability to dispatch non-dependent instructions in parallel so that the effective throughput of the pipelined instructions is greater than that if they were executed sequentially).
