### ISSUE TITLE
[API Proposal]:  Introduce alternative name of constructors -> ctor

### ISSUE THREAD

**Issue by AcidJunkie303** [dotnet/runtime#102070]
### Background and motivation

The syntax of constructors is not very distinguishable from other methods. The only difference is that it doesn't have a return type and the method name is equal to the class name.

It would be much more readable if the constructor could be called just `ctor`. Also and especially, when the class name is quite long.

### API Proposal

How it is done currently:

```csharp
namespace MyApp;

public class MyVeryLongClassName
{
    private readonly ILogger<MyVeryLongClassName> _logger;

    public MyVeryLongClassName(ILogger<MyVeryLongClassName> logger)
    {
        _logger = logger;
    }
}
```

With the new `ctor` keyword:

```csharp
namespace MyApp;

public class MyVeryLongClassName
{
    private readonly ILogger<MyVeryLongClassName> _logger;

    public ctor(ILogger<MyVeryLongClassName> logger)
    {
        _logger = logger;
    }
}
```

### API Usage

From a consumer side, nothing would change:

```csharp
var whatever = new MyVeryLongClassName(logger)
```

**Comment by KeterSCP** [comment]
You can use new `primary constructor` syntax for this

**Comment by huoyaoyuan** [comment]
See https://github.com/dotnet/csharplang/discussions/1928
Closing since it's not an API request, and not actionable for runtime.
