### ISSUE TITLE
GB1030 dotnet info

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#102174]
1. copy a group of GB18030 characters(level 3 long sample data)
𫚭﹫𪛒𫍲𫟼𬘭𮯠⾢)

2. Use the supported string to create folder.  龯蝌灋齅ㄥ䶱

3. unzip dotnet-sdk-9.0.100-preview.4.24218.26-win-x64.zip to above folder
4. access to the folder and run `dotnet --info`

Expected Result:

the contents can be displayed well.

Actual Result:

GB18030 characters displays incorrectly.
![image](https://github.com/dotnet/runtime/assets/515774/56404937-413a-4058-aa31-fac9c89514d1)

**Comment by jtschuster** [comment]
@elinor-fung Thank you so much for the info, I would have been pretty lost trying to fix this issue without it.
