### ISSUE TITLE
HttpClient(AndroidMessageHandler) with NTLM v2 auth and Self Signed Certificate returns 401 Unauthorized 

### ISSUE THREAD

**Issue by AzizBelAbed** [dotnet/runtime#102107]
### Description

I'm using an on-premise exchange server with NTLM v2 authentication. 
When attempting to authenticate using HttpClient and AndroidMessageHandler, I encounter a 401 Unauthorized error, specifically due to a **self-signed certificate**. Interestingly, when using a **public certificate**, authentication proceeds without any issues.

Here parts of the code:

```csharp
       var _httpClientHandler = new CustomAndroidMessageHandler();
       var _credentials = new CredentialCache
        {
            { new Uri(serverEndpoint), "NTLM", new NetworkCredential(emailEntry.Text, passwordEntry.Text)}
        };
        _httpClientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
        
        _httpClientHandler.Credentials = _credentials;
        HttpClient httpclient = new HttpClient(_httpClientHandler);
```

```csharp
    public class CustomAndroidMessageHandler : AndroidMessageHandler
    {
        protected override async Task WriteRequestContentToOutput(
            HttpRequestMessage request,
            HttpURLConnection httpConnection,
            CancellationToken cancellationToken)
        {
            var stream = await request.Content.ReadAsStreamAsync().ConfigureAwait(false);
            await stream.CopyToAsync(httpConnection.OutputStream!, 4096, cancellationToken).ConfigureAwait(false);

            if (stream.CanSeek)
            {
                stream.Seek(0, SeekOrigin.Begin);
            }
        }
    }
```
    
I added 

```xml
<AndroidUseNegotiateAuthentication>true</AndroidUseNegotiateAuthentication>
```

in csproj
    
    

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by AzizBelAbed** [comment]
@simonrozsival 
Thanks for the update.
I tried using **SocketsHttpHandler** and **_httpClientHandler.SslOptions.RemoteCertificateValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };**
but I get an exception:
Message: 
The SSL connection could not be established, see inner exception
Inner Exception: 
System.10.10Exception:
Received an unexpected EOF or 0 bytes from the transport stream.
at System. Net.Security.Ss|Stream.<R
eceiveBlobAsync>d_1471 [[System.
Net.Security.AsyncReadWriteAdapter,
System. Net. Security, Version=7.0.0.0,
Culture=neutral, PublicKeyToken=b03f5
f7f11d50a3a]].MoveNext()
at
System.Net.Security.Ss|Stream.<ForceA
uthenticationAsync>d_146'1 [[System
Net.Security.AsyncReadWriteAdapter,
System.Net. Security, Version=7.0.0.0,
Culture=neutral, PublicKeyToken=b03f5
f7f11d50a3a]].MoveNext()
at System.Net.Http.ConnectHel
per.EstablishSs|ConnectionAsync
(SsIClientAuthenticationOptions sslOptions, HttpRequestMessage
request, Boolean async, Stream stream, CancellationToken cancellation Token)

**Comment by simonrozsival** [comment]
@AzizBelAbed I wonder if this is related to https://github.com/dotnet/runtime/issues/102483. Would it be possible to try your app with the latest preview version of .NET 9? It should contain improvements to the NTLM implementation that aren't yet backported into a .NET 8 servicing release.

**Comment by vitek-karas** [comment]
Moving to Future for now - if we can get actionable info here, please move back to 9/10 as appropriate.
