### ISSUE TITLE
error CS9176: There is no target type for the collection expression

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/runtime#102130]
### Description

Consider this code:

```
var names = [
    "John",
    "David"
];
```

We get this error for it:

> error CS9176: There is no target type for the collection expression

The target type is clear. It's an array of strings.

### Reproduction Steps

1- Create a simple console app
2- Add this code to it:
```
var names = [
    "John",
    "David"
];
```
3- Compile

### Expected behavior

No error should be thrown. The program should compile. The variable is an array of strings. This is the universal behavior in almost any language, including JavaScript and Python.

### Actual behavior

It does not compile. We need to change the `var` into `string[]` to make it compile which is unnecessary.

**Comment by huoyaoyuan** [comment]
This is a C# language question and should go to https://github.com/dotnet/csharplang/discussions. The natural type of collection expression is still being designed at https://github.com/dotnet/csharplang/blob/main/proposals/collection-expressions-next.md#natural-type and https://github.com/dotnet/csharplang/issues/7913.

> This is the universal behavior in almost any language, including JavaScript and Python.

It is not. JavaScript and Python do not have different collection types that provide different performance characteristics. There's only one weakly typed "array list".
Collection expression is more like `std::initializer_list` in C++, that can be accepted by different collection types.

Closing as not a runtime issue.
