### ISSUE TITLE
[browser][MT] mono_download_assets - RangeError: Start offset -1 is outside the bounds of the buffer

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#102196]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100141-merge-2bc80070eae34fc693/WasmTestOnChrome-MT-System.Runtime.ReflectionInvokeInterpreted.Tests/1/console.16b81351.log?helixlogtype=result)
```
[11:40:15] fail: [out of order message from the browser]: http://127.0.0.1:33721/_framework/dotnet.runtime.js 2:76111 Uncaught RangeError: Start offset -1 is outside the bounds of the buffer
[11:40:15] fail: Error in mono_download_assets: RangeError: Start offset -1 is outside the bounds of the buffer
[11:40:15] fail: [--000fb3fc-emsc 11:40:15.219] MONO_WASM: Start offset -1 is outside the bounds of the buffer
                 RangeError: Start offset -1 is outside the bounds of the buffer
                     at new Uint8Array (<anonymous>)
                     at http://127.0.0.1:33721/_framework/dotnet.runtime.js:3:76112
                     at Object.sa [as instantiate_asset] (http://127.0.0.1:33721/_framework/dotnet.runtime.js:3:76160)
                     at n (http://127.0.0.1:33721/_framework/dotnet.js:3:8629)
                     at async Promise.all (index 73)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=674731
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": ["mono_download_assets", "RangeError"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=674731
**Error message validated:** `[mono_download_assets RangeError`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/15/2024 10:05:35 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[678702](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678702)|dotnet/runtime|[WasmTestOnChrome-MT-System.Security.SecureString.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678702&view=ms.vss-test-web.build-test-results-tab&runId=16876628&resultId=188641)|dotnet/runtime#102363|
|[679376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679376)|dotnet/runtime|[WasmTestOnChrome-MT-Microsoft.Bcl.AsyncInterfaces.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679376&view=ms.vss-test-web.build-test-results-tab&runId=16855528&resultId=188776)|dotnet/runtime#102375|
|[679712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679712)|dotnet/runtime|[WasmTestOnChrome-MT-System.Linq.Parallel.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679712&view=ms.vss-test-web.build-test-results-tab&runId=16854480&resultId=188178)||
|[679157](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679157)|dotnet/runtime|[WasmTestOnChrome-MT-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679157&view=ms.vss-test-web.build-test-results-tab&runId=16839064&resultId=184039)|dotnet/runtime#102188|
|[678956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678956)|dotnet/runtime|[WasmTestOnChrome-MT-System.Reflection.InvokeEmit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678956&view=ms.vss-test-web.build-test-results-tab&runId=16836984&resultId=188499)|dotnet/runtime#102185|
|[679183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679183)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679183&view=ms.vss-test-web.build-test-results-tab&runId=16838684&resultId=100549)|dotnet/runtime#99818|
|[678900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678900)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Xml.XmlSerializer.ReflectionOnly.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678900&view=ms.vss-test-web.build-test-results-tab&runId=16836050&resultId=188515)|dotnet/runtime#102143|
|[678959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678959)|dotnet/runtime|[WasmTestOnChrome-MT-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678959&view=ms.vss-test-web.build-test-results-tab&runId=16831428&resultId=168134)|dotnet/runtime#102375|
|[678869](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678869)|dotnet/runtime|[WasmTestOnChrome-MT-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678869&view=ms.vss-test-web.build-test-results-tab&runId=16829756&resultId=188246)||
|[678827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678827)|dotnet/runtime|[WasmTestOnChrome-MT-System.Reflection.Metadata.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678827&view=ms.vss-test-web.build-test-results-tab&runId=16828838&resultId=180761)|dotnet/runtime#100675|
|[678753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678753)|dotnet/runtime|[WasmTestOnChrome-MT-System.Reflection.InvokeInterpreted.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678753&view=ms.vss-test-web.build-test-results-tab&runId=16827060&resultId=187367)|dotnet/runtime#102365|
|[677948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677948)|dotnet/runtime|[WasmTestOnChrome-MT-Microsoft.Extensions.HostFactoryResolver.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677948&view=ms.vss-test-web.build-test-results-tab&runId=16805206&resultId=188738)|dotnet/runtime#101938|
|[677879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677879)|dotnet/runtime|[WasmTestOnChrome-MT-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677879&view=ms.vss-test-web.build-test-results-tab&runId=16804194&resultId=180487)|dotnet/runtime#100675|
|[677621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677621)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Private.Uri.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677621&view=ms.vss-test-web.build-test-results-tab&runId=16802992&resultId=188341)|dotnet/runtime#102255|
|[677596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677596)|dotnet/runtime|[WasmTestOnChrome-MT-System.Diagnostics.StackTrace.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677596&view=ms.vss-test-web.build-test-results-tab&runId=16796808&resultId=185802)|dotnet/runtime#101975|
|[677577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677577)|dotnet/runtime|[WasmTestOnChrome-MT-System.Threading.ThreadPool.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677577&view=ms.vss-test-web.build-test-results-tab&runId=16796602&resultId=188715)|dotnet/runtime#101543|
|[677422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677422)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Xml.Linq.Axes.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677422&view=ms.vss-test-web.build-test-results-tab&runId=16793628&resultId=188694)||
|[677460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677460)|dotnet/runtime|[WasmTestOnChrome-MT-System.Xml.XmlSerializer.ReflectionOnly.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677460&view=ms.vss-test-web.build-test-results-tab&runId=16792436&resultId=188433)|dotnet/runtime#102212|
|[676620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676620)|dotnet/runtime|[WasmTestOnChrome-MT-System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676620&view=ms.vss-test-web.build-test-results-tab&runId=16790474&resultId=182993)|dotnet/runtime#102143|
|[677282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677282)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677282&view=ms.vss-test-web.build-test-results-tab&runId=16788182&resultId=188585)|dotnet/runtime#102292|
|[676525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676525)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.Mail.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676525&view=ms.vss-test-web.build-test-results-tab&runId=16778738&resultId=188603)|dotnet/runtime#102265|
|[676609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676609)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.ReflectionInvokeEmit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676609&view=ms.vss-test-web.build-test-results-tab&runId=16773906&resultId=188627)|dotnet/runtime#102185|
|[676344](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676344)|dotnet/runtime|[WasmTestOnChrome-MT-System.IO.UnmanagedMemoryStream.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676344&view=ms.vss-test-web.build-test-results-tab&runId=16772184&resultId=188716)|dotnet/runtime#101543|
|[676289](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676289)|dotnet/runtime|[WasmTestOnChrome-MT-System.ValueTuple.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676289&view=ms.vss-test-web.build-test-results-tab&runId=16767568&resultId=188648)|dotnet/runtime#102188|
|[676279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676279)|dotnet/runtime|[WasmTestOnChrome-MT-System.Drawing.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676279&view=ms.vss-test-web.build-test-results-tab&runId=16767300&resultId=188608)|dotnet/runtime#102212|
|[676251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676251)|dotnet/runtime|[WasmTestOnChrome-MT-Microsoft.Extensions.Configuration.CommandLine.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676251&view=ms.vss-test-web.build-test-results-tab&runId=16766820&resultId=188728)|dotnet/runtime#102254|
|[676242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676242)|dotnet/runtime|[WasmTestOnChrome-MT-System.Xml.Linq.Properties.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676242&view=ms.vss-test-web.build-test-results-tab&runId=16766680&resultId=180250)|dotnet/runtime#100675|
|[676228](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676228)|dotnet/runtime|[WasmTestOnChrome-MT-Microsoft.Extensions.Configuration.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676228&view=ms.vss-test-web.build-test-results-tab&runId=16765972&resultId=188706)|dotnet/runtime#101975|
|[676151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676151)|dotnet/runtime|[WasmTestOnFirefox-MT-Invariant.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676151&view=ms.vss-test-web.build-test-results-tab&runId=16762352&resultId=187804)|dotnet/runtime#101252|
|[676144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676144)|dotnet/runtime|[WasmTestOnFirefox-MT-Invariant.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676144&view=ms.vss-test-web.build-test-results-tab&runId=16762176&resultId=188656)|dotnet/runtime#102184|
|[674731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674731)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Caching.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674731&view=ms.vss-test-web.build-test-results-tab&runId=16758726&resultId=188678)|dotnet/runtime#100141|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|31|31|

**Comment by pavelsavara** [comment]
cc @kg

**Comment by kg** [comment]
I think this would indicate that malloc/sbrk/mmap failed during startup. Seems like a threading bug (emscripten libc bug?)

**Comment by pavelsavara** [comment]
This one is the same thing from firefox
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100141-merge-8e57a8150ae5444280/WasmTestOnFirefox-MT-System.Runtime.InteropServices.Tests/1/console.93b76773.log?helixlogtype=result)
```
JavaScript error: http://127.0.0.1:41545/_framework/dotnet.runtime.js, line 3: RangeError: invalid or out-of-range index
JavaScript error: http://127.0.0.1:41545/_framework/dotnet.runtime.js, line 3: RangeError: invalid or out-of-range index
JavaScript error: http://127.0.0.1:41545/_framework/dotnet.runtime.js, line 3: RangeError: invalid or out-of-range index
JavaScript error: http://127.0.0.1:41545/_framework/dotnet.runtime.js, line 3: RangeError: invalid or out-of-range index
JavaScript error: http://127.0.0.1:41545/_framework/dotnet.runtime.js, line 3: RangeError: invalid or out-of-range index
[08:07:17] fail: Error in mono_download_assets: RangeError: invalid or out-of-range index
[08:07:17] fail: [--000fb3fc-emsc 08:07:17.444] MONO_WASM: invalid or out-of-range index
                 sa/a<@http://127.0.0.1:41545/_framework/dotnet.runtime.js:3:76112
                 sa@http://127.0.0.1:41545/_framework/dotnet.runtime.js:3:76160
                 n@http://127.0.0.1:41545/_framework/dotnet.js:3:8629
[08:07:17] info: WASM EXIT 1
```

**Comment by kg** [comment]
The structure of emscripten's implementation of sbrk and v8's implementation of memory.grow both imply that it shouldn't be possible to get -1 unless we run out of memory.

However, looking closer at v8's underlying implementation, if you're using an SAB and multiple threads are racing to grow the heap, it looks like if mprotect() were to fail for any reason, the grow would immediately fail and return -1 even if you're not out of memory (there's no retry/loop in the implementation, regardless of what error code mprotect returns). I only consider this remotely plausible since (AFAIK) this failure is only happening on ubuntu and only affects MT lanes, since this logic is specifically different in V8 for SABs.

Still feels highly unlikely, though...

**Comment by kg** [comment]
It looks like it's possible for mprotect to return EINTR despite what the docs say, so that could be happening here.

**Comment by pavelsavara** [comment]
I think we could  lock around our allocations or retry
We could replace emscripten's `emscripten_resize_heap` in JS

**Comment by kg** [comment]
> I think we could lock around our allocations or retry We could replace emscripten's `emscripten_resize_heap` in JS

I looked into doing this before, but it seems very risky. It could cause problems in emscripten dlmalloc/mimalloc/emmalloc if we were to manage the heap size ourselves.

**Comment by kg** [comment]
24 hour hit count is 0, closing
