### ISSUE TITLE
[iOS/HybridGlobalization] No space between time and AM/PM designator

### ISSUE THREAD

**Issue by tipa** [dotnet/runtime#102250]
### Description

When using hybrid globalization on iOS and using the short time specifier, there is no space in front of the "AM" or "PM".

### Reproduction Steps

```
var date = DateTime.Today + TimeSpan.FromHours(15) + TimeSpan.FromMinutes(15);
var culture = new CultureInfo("en-US");
System.Diagnostics.Debug.WriteLine(date.ToString("t", culture));
```

### Expected behavior

`3:15 PM`

### Actual behavior

`3:15PM`

### Configuration

macos                      14.2.8053/8.0.100      SDK 8.0.200        
ios                        17.2.8053/8.0.100      SDK 8.0.200        

iOS 17.2

### Other information

The same problem happens when using the long time format specified ("T").
The space is present as expected when not using hybrid globalization

**Comment by ilonatommy** [comment]
@mkhamoyan, in https://github.com/dotnet/runtime/blob/43b7b5315b0b4160c1175ba89216a4fa9c1bb973/src/native/libs/System.Globalization.Native/pal_locale.m#L698 we are using methods that according to the documentation:
https://developer.apple.com/documentation/foundation/nsdateformatterstyle/nsdateformattershortstyle
https://developer.apple.com/documentation/foundation/nsdateformatterstyle/nsdateformattermediumstyle
should return formats with the space. Is it possible that we format it on the fly? Or might it be a behavioral change between iOS's ICU version?

**Comment by mkhamoyan** [comment]
We see bahavioural change as there was a fix in ICU flow ( see https://github.com/dotnet/runtime/pull/83589) and now https://github.com/dotnet/runtime/blob/0c64e66b497740e4477ad27bb532e564afb4c186/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L338 and https://github.com/dotnet/runtime/blob/0c64e66b497740e4477ad27bb532e564afb4c186/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L338 have different implementations. 
I will open a PR to use same function for both flows.

**Comment by mkhamoyan** [comment]
I am not able to reproduce this issue in the latest version of .NET 8 (works as expected on .Net 9 also). 
@tipa Could you please specify whether you created the project using `dotnet new maui` or `dotnet new ios`?

**Comment by tipa** [comment]
I can still reproduce this with .NET 8. I am using `dotnet new ios`.
It only happens when using `<HybridGlobalization>true</HybridGlobalization>`

**Comment by mkhamoyan** [comment]
Thanks! I can reproduce with `dotnet new ios`

**Comment by mkhamoyan** [comment]
In .NET 9 `HybridGlobalization` is the default and only mode.
I was previously unable to reproduce the issue because I was targeting an iOS device running version` 16.7.8`, which uses an older ICU version.

It appears that recent ICU versions have introduced a change where `regular spaces are replaced with non-breaking spaces (NBSP / \u00A0) or narrow non-breaking spaces (NNBSP / \u202F`). For more details, see the related [ICU change](https://unicode-org.atlassian.net/browse/CLDR-14032).

I will open a PR to handle these cases properly.
