### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007054F

### ISSUE THREAD

**Issue by mikugirls** [dotnet/runtime#102210]
Can't run in ubuntu 23.10 arm64 . 
Failed to create CoreCLR, HRESULT: 0x8007054F
[log.txt](https://github.com/dotnet/sdk/files/15286430/log.txt)

**Comment by mangod9** [comment]
hello @mikugirls, can you please provide more details on what scenario is failing for you?

**Comment by mikugirls** [comment]
Updated to 8.0.401, now available
