### ISSUE TITLE
Error MSB6006: "csc.exe" exited with code -2146232797.

### ISSUE THREAD

**Issue by Jakar510** [dotnet/runtime#102205]
### Description

I get the `Error MSB6006: "csc.exe" exited with code -2146232797` in Windows 11 23H2 (AMD desktop and Intel Laptop), MacOS (M3 max) for Visual Studio, Jetbrains Rider and Dotnet CLI when trying to build `Jakar.Extensions` project directly in `Release Mode`.

I also tried Visual Studio v17.10.0 Preview 7 with no changes. 

When trying to build with CLI: [CLI log.txt](https://github.com/dotnet/runtime/files/15311719/CLI.log.txt)

When Trying to rebuild (via right click in VS): [Output-Build.txt](https://github.com/dotnet/runtime/files/15311730/Output-Build.txt)

### Reproduction Steps

Clone this [repo](https://github.com/Jakar510/Jakar.Extensions/tree/Development)
Make sure it's in `Release Mode`
Try to build/rebuild `Jakar.Extensions` project directly...boom
Set startup project to `Jakar.Extensions.Experiments` 
Run with/without debug in Release and it builds successfully.

### Expected behavior

build/rebuild successfuly

### Actual behavior

I get the `error MSB6006: "csc.exe" exited with code -2146232797.`

### Regression?

Not sure

### Known Workarounds

None

### Configuration

<details>
  <summary>Envrionment</summary>
  
Microsoft Visual Studio Community 2022
Version 17.9.6
VisualStudio.17.Release/17.9.6+34728.123
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA697
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.9.199.22661
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2012   17.9.199.22661
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.9.199.22661
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.9.199.22661
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.24002.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Dotfuscator Community Edition   6.5.3+7f0b0a9d18
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extension Manager 2022   1.3.4
Import/export extensions as well as associate extensions with individual solutions

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

GitHub Copilot   1.181.0.1 (v1.181.0.1@b03e96737)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.181.0

Linux Core Dump Debugging   1.0.9.34714
Enables debugging of Linux core dumps.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.9.0 (b3bca6f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50908.1 Commit Hash:c294679b821c4b8f7f9c6db3827b7655db80fc28
Adds support for developing and debugging Node.js apps in Visual Studio

NpgsqlVSPackage Extension   1.0
NpgsqlVSPackage Visual Studio Extension Detailed Info

NuGet Package Manager   6.9.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.6.34328.02
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.24002.3
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.24002.3
Profiling support for Python projects.

Python with Pylance   17.0.24002.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.9.2.2412004+684740676513b3b208d5bd5b7f8786dab8d287b7
Provides languages services for ASP.NET Core Razor.

ResX Resource Manager   ResXManager
Manage localization of all ResX-based resources in one place. Shows all resources of a solution and lets you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   17.9.56.1
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.34511.75
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   15.0.34714.143
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.34714
Visual C++ for Linux Development

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Unity   17.9.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.9.0.140 (d17-9@7ca5d58)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.9.3.0 (remotes/origin/d17-9@f174974f91)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.9.0 (38e87ba)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.23 (9defd91b3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

### Other information

- [Visual Studio v17.9.6 bug report](https://developercommunity.visualstudio.com/t/error-MSB6006:-cscexe-exited-with-cod/10645277?ref=native&refTime=1713895327956&refUserId=06c2f756-29ea-4e0e-9d08-e297bf77a59d)
- [dotnet-framework-docker/issues/315](https://github.com/microsoft/dotnet-framework-docker/issues/315)
- [Visual Studio Report](https://developercommunity.visualstudio.com/t/error-msb6006-cscexe-exited-with-code-2146232797/94629)

**Comment by D7K7** [comment]
Windows 10, upon build...

![image](https://github.com/dotnet/runtime/assets/47164434/f868da11-bdb2-4af3-a613-93dad38ce2f6)

**Comment by mangod9** [comment]
Hey @Jakar510, can you clarify that you are seeing the failure on both windows and Mac? Looks like you are hitting it intermittently (as in most of the times the build succeeds?). Thx

**Comment by Jakar510** [comment]
@mangod9 

As stated in the description, the error occurs on all platforms. If I run, with or without debugging, the Jakar.Extensions.Experiments project in VS (not right click/build) it works as expected. But if I right click/build or rebuild it fails.

**Comment by Jakar510** [comment]
@mangod9 

I tried rolling back to `Visual Studio v17.8.7` and it worked.  `Visual Studio v17.9.0` and later does not.

**Comment by Jakar510** [comment]
Issue doesn't occur in `Visual Studio v17.10.1`

**Comment by mangod9** [comment]
Closing since this doesnt repro on latest versions.
