### ISSUE TITLE
Blazor Hybird Release Buid error-target andriod

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#102276]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Hybird-Release-Buid-error-target-/10653375)._

---
[severity:I'm unable to use this version]
I have blazor hybird application target andriod. it runs well in debug mode. But when set release mode and build. the following error occurs:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4184	The expression "[System.String]::Copy(null)" cannot be evaluated. Value cannot be null. Parameter name: str	MauiBIWebApp	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.85\targets\Microsoft.Android.Sdk.ILLink.targets	34
```
Thanks	

---
#### Feedback Bot on 5/6/2024, 10:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by qunshen** [comment]
I have upgraded mysolution to the lastest service pack.  the errors occurs:
.........
24>MauiBIWebApp -> D:\MyData\CorePortal\MauiBIWebApp\bin\Release\net8.0-android\MauiBIWebApp.dll
24>MauiBIWebApp -> D:\MyData\CorePortal\MauiBIWebApp\bin\Release\net8.0-maccatalyst\maccatalyst-arm64\MauiBIWebApp.dll
24>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.85\targets\Microsoft.Android.Sdk.ILLink.targets(34,11): error MSB4184: The expression "[System.String]::Copy(null)" cannot be evaluated. Value cannot be null. Parameter name: str
24>Done building project "MauiBIWebApp.csproj" -- FAILED.
24>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.85\targets\Microsoft.Android.Sdk.ILLink.targets(34,11): error MSB4184: The expression "[System.String]::Copy(null)" cannot be evaluated. Value cannot be null. Parameter name: str
24>Done building project "MauiBIWebApp.csproj" -- FAILED.
24>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.85\targets\Microsoft.Android.Sdk.ILLink.targets(34,11): error MSB4184: The expression "[System.String]::Copy(null)" cannot be evaluated. Value cannot be null. Parameter name: str
24>Done building project "MauiBIWebApp.csproj" -- FAILED.
24>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.85\targets\Microsoft.Android.Sdk.ILLink.targets(34,11): error MSB4184: The expression "[System.String]::Copy(null)" cannot be evaluated. Value cannot be null. Parameter name: str
24>Done building project "MauiBIWebApp.csproj" -- FAILED.
24>Done building project "BIWebRazorLibCore.csproj".
24>Done building project "MauiBIWebApp.csproj".
========== Build: 27 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 16:02 and took 03:28.198 minutes ==========

**Comment by mattleibow** [comment]
@jonathanpeppers I see this is the Android ILLink target that is failing. Thoughts?

**Comment by jonathanpeppers** [comment]
I don't understand how `%(FileName)` could be blank:

* https://github.com/xamarin/xamarin-android/blob/fa1b8017f7f8519bc55aa689ea016e4f03c994ee/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets#L34

@qunshen can you share a `.binlog` file of this error? https://aka.ms/binlog

**Comment by vitek-karas** [comment]
@qunshen we can't make any progress without more information on this. If this is still a problem, please feel free to reopen the issue and provide some more detailed info as specified above.
