### ISSUE TITLE
net7.0-ios16.1 depends on non-existent Microsoft.AspNetCore.App.Ref 7.0.20

### ISSUE THREAD

**Issue by bnickel** [dotnet/runtime#102214]
### Description

I have a library with `<TargetFramework>net7.0-ios</TargetFramework>`.  Running `dotnet build` fails with `error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 7.0.20)`

### Reproduction Steps

Create the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0-ios</TargetFramework>
	</PropertyGroup>
</Project>
```

Run `dotnet build`

### Expected behavior

The build succeeds.

### Actual behavior

The build fails with the following message:

```text
dotnet build -c Release HeapInc.Xamarin.iOS
  Determining projects to restore...
.../HeapInc.Xamarin.iOS.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 7.0.20)
.../HeapInc.Xamarin.iOS.csproj : error NU1102:   - Found 112 version(s) in nuget.org [ Nearest version: 8.0.0-preview.1.23110.8 ]
.../HeapInc.Xamarin.iOS.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
.../HeapInc.Xamarin.iOS.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 7.0.20)
.../HeapInc.Xamarin.iOS.csproj : error NU1102:   - Found 113 version(s) in nuget.org [ Nearest version: 8.0.0-preview.1.23112.2 ]
.../HeapInc.Xamarin.iOS.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
  Failed to restore .../HeapInc.Xamarin.iOS.csproj (in 326 ms).

Build FAILED.
```

The .nuget.dgspec.json contains the following:

```json
        "frameworks": {
          "net7.0-ios16.1": {
            "targetAlias": "net7.0-ios",
            "projectReferences": {}
          }
        },
```

And:

```json
      "frameworks": {
        "net7.0-ios16.1": {
          "targetAlias": "net7.0-ios",
          "dependencies": {
            "Microsoft.NET.ILLink.Analyzers": {
              "suppressParent": "All",
              "target": "Package",
              "version": "[7.0.100-1.23401.1, )",
              "autoReferenced": true
            },
            "Microsoft.NET.ILLink.Tasks": {
              "suppressParent": "All",
              "target": "Package",
              "version": "[7.0.100-1.23401.1, )",
              "autoReferenced": true
            }
          },
          "imports": [
            "net461",
            "net462",
            "net47",
            "net471",
            "net472",
            "net48",
            "net481"
          ],
          "assetTargetFallback": true,
          "warn": true,
          "downloadDependencies": [
            {
              "name": "Microsoft.AspNetCore.App.Ref",
              "version": "[7.0.20, 7.0.20]"
            },
            {
              "name": "Microsoft.NETCore.App.Ref",
              "version": "[7.0.20, 7.0.20]"
            }
          ],
          "frameworkReferences": {
            "Microsoft.iOS": {
              "privateAssets": "all"
            },
            "Microsoft.NETCore.App": {
              "privateAssets": "all"
            }
          },
          "runtimeIdentifierGraphPath": "/usr/local/share/dotnet/sdk/8.0.301/RuntimeIdentifierGraph.json"
        }
      }
```

### Configuration

dotnet 8.0.301
macOS 14.4.1
Arm64

**Comment by MagicAndre1981** [comment]
.net 7.0 is [out of support now](https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/), so change 7.0 to 8.0

> .NET 7 will reach [end of support on May 14, 2024](https://github.com/dotnet/core/blob/main/release-notes/7.0/README.md). After that, Microsoft will no longer provide servicing updates, including security fixes or technical support, for .NET 7. You’ll need to update to [.NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/) before this date into stay supported.

**Comment by filipnavara** [comment]
> .net 7.0 is [out of support now](https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/), so change 7.0 to 8.0

This seems to be breakage in the last .NET 7.0 update. It should be fixed regardless of the support status.

**Comment by NikolaMilosavljevic** [comment]
[Triage] @bnickel it look like you're running a pre-release version of the .NET SDK, is that correct?

**Comment by MichaelSimons** [comment]
> [Triage] @bnickel it look like you're running a pre-release version of the .NET SDK, is that correct?

If that is true, you need a nuget.config that is configured to with the prerelease feeds to acquire the 7.0 runtime from.

**Comment by MagicAndre1981** [comment]
[7.0.20](https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/7.0.20) and SDK 8.0.301 are now officially released to fix a security issue. So this should now work.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing as this should not repro anymore. Please reopen if that's not the case.

**Comment by bnickel** [comment]
Sorry for the late replay, but I wanted to confirm that this is working for me now. Thanks!
