### ISSUE TITLE
[Console]::Beep() does not activate "Bell Notifications"

### ISSUE THREAD

**Issue by GarThor** [dotnet/runtime#102211]
### Description

This bug was origionally posted at https://github.com/microsoft/terminal/issues/17263, however the developers on that project directed me to this one due to this code not pushing the notification: https://github.com/dotnet/runtime/blob/039d2ecb46687e89337d6d629c295687cfe226be/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L656-L673

Windows Terminal version
1.19.11213.0

Windows build number
10.0.19045.0

Other Software
Powershell v5 and v7

I do have oh-my-posh installed, but I don't think that affects this behavior

Flashing/notifications do appear to be configurable when using the Write-Host -NoNewLine "a"` command however.

### Reproduction Steps

Steps to reproduce
o Enable "Bell notificaiton styles" in "Advanced" for your powershell profile.
o Enter the command [Console]::Beep() into the console. Observe, while the terminal does emit an audible beep, it does not alert the user in any other way (via flashing the window or the taskbar as configured).

### Expected behavior

Expected Behavior
[Console]::Beep() should respect the user's configuration for bell notifications.

### Actual behavior

Actual Behavior
[Console]::Beep() does not respect the user's configuration for bell notifications.

### Known Workarounds

I can still use write-host "`a", which will produce the desired results.

**Comment by DHowett** [comment]
FWIW dotnet folks - `Console.Beep` uses the system `Beep` API on Windows, which always emits a sound. Printing `U+0007 BEL` is the most correct way, even on Windows (all the way down to Windows 7, if not prior), to emit a system bell.

**Comment by adamsitnik** [comment]
@DHowett thank you for your input! Do you know if switching from the `Beep` sys-call to writing `BEL` can have any other side effects?

**Comment by alexrp** [comment]
Well, for one thing, it'll make the API actually work as expected over SSH and the like.

**Comment by adamsitnik** [comment]
I've marked the issue as `help wanted`. The person who is willing to work on the fix should  do the following:

1. Let others know that they are going to work on it.
2. Check the current behavior of `Console.Beep` with redirected output (to a file for example)
3. Install everything required to build dotnet/runtime as described in https://github.com/dotnet/runtime/blob/039d2ecb46687e89337d6d629c295687cfe226be/docs/workflow/requirements/windows-requirements.md
4. Fork the repo, create a new branch and build dotnet/runtime
```cmd
.\build.cmd -c Release -subset clr+libs+libs.tests
```
5. Apply [suggested fix](https://github.com/dotnet/runtime/issues/102211#issuecomment-2110973504) to the overload that takes no parameters and rebuild only the System.Console.sln solution
```cmd
.\dotnet.cmd build .\src\libraries\System.Console\System.Console.sln -c Release
```
6. Use [corerun](https://github.com/dotnet/runtime/blob/7d8d6acb59b23ba0b0b6e5d7213e797b6b514d66/docs/workflow/testing/using-corerun-and-coreroot.md) to run a stand-alone console app to test the change
```cmd
.\artifacts\bin\testhost\net9.0-windows-Release-x64\shared\Microsoft.NETCore.App\9.0.0\corerun.exe $pathToDll
```
7. Ensure that nothing gets printed when the output is redirected

**Comment by karakasa** [comment]
I'm afriad <kbd>BEL</kbd> doesn't support frenquency & duration. So I assume we are relying on two different mechanics for `Beep()` & `Beep(int, int)` on Windows?

**Comment by karakasa** [comment]
> I've marked the issue as `help wanted`. The person who is willing to work on the fix should do the following:
> 
> 1. Let others know that they are going to work on it.
> 2. Check the current behavior of `Console.Beep` with redirected output (to a file for example)
> 3. Install everything required to build dotnet/runtime as described in https://github.com/dotnet/runtime/blob/039d2ecb46687e89337d6d629c295687cfe226be/docs/workflow/requirements/windows-requirements.md
> 4. Fork the repo, create a new branch and build dotnet/runtime
> 
> ```batchfile
> .\build.cmd -c Release -subset clr+libs+libs.tests
> ```
> 
> 5. Apply [suggested fix](https://github.com/dotnet/runtime/issues/102211#issuecomment-2110973504) to the overload that takes no parameters and rebuild only the System.Console.sln solution
> 
> ```batchfile
> .\dotnet.cmd build .\src\libraries\System.Console\System.Console.sln -c Release
> ```
> 
> 6. Use [corerun](https://github.com/dotnet/runtime/blob/7d8d6acb59b23ba0b0b6e5d7213e797b6b514d66/docs/workflow/testing/using-corerun-and-coreroot.md) to run a stand-alone console app to test the change
> 
> ```batchfile
> .\artifacts\bin\testhost\net9.0-windows-Release-x64\shared\Microsoft.NETCore.App\9.0.0\corerun.exe $pathToDll
> ```
> 
> 7. Ensure that nothing gets printed when the output is redirected

I would say this is a behavioral breaking change and involves some doc changes. Do you think it is necessary to fix the issue?

https://github.com/karakasa/runtime/blob/53d94f4a6c6ca1c61c968e5640e9aef0561967cd/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L678-L702
