### ISSUE TITLE
Different behavior of FromKeyedServices attribute in Minimal APIs handler vs class library

### ISSUE THREAD

**Issue by marcominerva** [dotnet/runtime#102204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If we use the `FromKeyedServices` attribute in a class library and the keyed registration is missing, it falls back to the default dependency injection behavior and gets the last registered implementation (even with no key). However, If we use `FromKeyedServices` directly in a Minimal API endpoint handler and the key does not exist, it throws an exception.

### Expected Behavior

The `FromKeyedServices` attribute should behave in the same way in every context.

### Steps To Reproduce

Minimal repro here: https://github.com/marcominerva/KeyedServicesIssue

### Exceptions (if any)

When using `FromKeyedServices` directly in a Minimal API endpoint handler:

System.InvalidOperationException: No service for type 'KeyedServicesIssue.Library.IDependency' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetRequiredKeyedService(Type serviceType, Object serviceKey, ServiceProviderEngineScope serviceProviderEngineScope)
   at lambda_method2(Closure, Object, HttpContext)

When using  `FromKeyedServices` in a class library, no exception at all is thrown, even if the key does not exist.

### .NET Version

8.0.204

**Comment by steveharter** [comment]
This should be fixed for v9.

**Comment by captainsafia** [comment]
@steveharter Thanks! Do you happen to know what preview the fix shipped in for verification?

**Comment by steveharter** [comment]
I think the correct behavior is to throw for the case where a keyed parameter is unresolved - i.e. don't inject an unkeyed service. I put up a PR for that.

**Comment by steveharter** [comment]
> @steveharter Thanks! Do you happen to know what preview the fix shipped in for verification?

@captainsafia the fix has not been shipped yet. v9.0 will be released later this year. Whether we want to backport this to 8.0 is an open topic.

**Comment by steveharter** [comment]
This will ship in v9 Preview 1. Once validated, we will backport to v8.

**Comment by steveharter** [comment]
> This will ship in v9 RC1. Once validated, we will backport to v8.

After further discussion, we may or may not backport this to v8. We typically don't backport breaking changes.
