### ISSUE TITLE
jitstress-isas-x86 fails with Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()'

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#102284]
```
Assert failure(PID 11512 [0x00002cf8], Thread: 13068 [0x330c]): Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()' in 'Program:<<Main>$>g__TestExecutor16|0_17(System.IO.StreamWriter,System.IO.StreamWriter,byref)' during 'Morph - Inlining' (IL size 269; hash 0xeb8a9ecb; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp:25578
    Image: C:\h\w\AD8E0944\p\corerun.exe

App Exit Code: -1073740286
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
```
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-7f150beb444c45d6a0/Regression_2/1/console.5feb3052.log?helixlogtype=result

## Build Information
Build: 
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "IsBaselineSimdIsaSupportedDebugOnly",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 5/15/2024 9:05:13 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by EgorBo** [comment]
cc @tannergooding - could it be related to one of your recent PRs?

**Comment by tannergooding** [comment]
Looks like yes. I'd guess it's due to checking for `SSE` while `ToScalar` checks for SSE and SSE2
