### ISSUE TITLE
ImmutableArray<T>.Builder.RemoveRange Not Robust

### ISSUE THREAD

**Issue by Matthew-Chidlow** [dotnet/runtime#102243]
### Description

- The `RemoveRange` method on an `ImmutableArray<T>.Builder` does not check for a negative length input, and so allows putting the internal state into an invalid one.

### Reproduction Steps

```cs
var test = ImmutableArray.CreateBuilder<int>(1);
test.Add(1);

// Should probably throw exception
test.RemoveRange(3, -2);

// Doesn't throw exception
Console.WriteLine(test[0]);
// Does throw exception
Console.WriteLine(test[^1]);
```

### Expected behavior

It should probably throw an exception when using a negative length, like `List<T>.RemoveRange` does.

### Actual behavior

Internal state gets messed up with Count > Capacity, and so all kinds of weird things can happen.

**Comment by eiriktsarpalis** [comment]
Thanks. Would you be interested in filing a PR?
