### ISSUE TITLE
ObjectStackAllocation: Assert failure "Precode->GetType() == PRECODE_FIXUP"

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#102294]
Fails in  `runtime-coreclr superpmi-collect` e.g. https://helixri107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-a16ed389b1f6488796/JIT.opt/1/console.ba6b67b2.log?sv=2021-08-06&se=2024-08-13T16%3A09%3A09Z&sr=c&sp=rl&sig=3pU%2BnrV55WRFAw5hf1nOSr6u3Rh6sOmh9cbS11%2FXgeQ%3D

```
17:17:47.270 Running test: JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.cmd

Assert failure(PID 4028 [0x00000fbc], Thread: 5620 [0x15f4]): pPrecode->GetType() == PRECODE_FIXUP

CORECLR! CEEJitInfo::getHelperFtn + 0x1FA (0x00007ffe`f947441a)
SUPERPMI-SHIM-COLLECTOR! <no symbol> + 0x0 (0x00007fff`22344e79)
CLRJIT! CodeGen::genGenerateCode + 0x14F (0x00007ffe`fc78fb4f)
CLRJIT! Compiler::compCompile + 0x217A (0x00007ffe`fc7a7f7a)
CLRJIT! Compiler::compCompileHelper + 0xAA0 (0x00007ffe`fc7aa260)
CLRJIT! Compiler::compCompile + 0xAA7 (0x00007ffe`fc7a8f97)
CLRJIT! `jitNativeCode'::`8'::__Body::Run + 0xEC (0x00007ffe`fc7a4c5c)
CLRJIT! jitNativeCode + 0x15D (0x00007ffe`fc7afeed)
CLRJIT! CILJit::compileMethod + 0x168 (0x00007ffe`fc7b7578)
SUPERPMI-SHIM-COLLECTOR! <no symbol> + 0x0 (0x00007fff`22341cc6)
    File: D:\a\_work\1\s\src\coreclr\vm\jitinterface.cpp:10739
    Image: C:\h\w\ADE10957\p\corerun.exe

```

## Build Information
Build: 
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "pPrecode->GetType() == PRECODE_FIXUP",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 5/15/2024 11:14:47 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by EgorBo** [comment]
hm.. looks like the assert fails for `DYNAMIC_CORINFO_HELP_BULK_WRITEBARRIER`

**Comment by EgorBo** [comment]
Looks like it's fixed in https://github.com/dotnet/runtime/pull/102209

**Comment by EgorBo** [comment]
Actually, I am not sure I understand this assert, so currently getHelperFtn fails on `CORINFO_HELP_BULK_WRITEBARRIER` [here](https://github.com/dotnet/runtime/blob/60edf5bb3e025d14ff0b64fbbb07df93f9037c95/src/coreclr/vm/jitinterface.cpp#L10739).

because its precode type is `PRECODE_STUB` instead of `PRECODE_FIXUP`

@jkotas does this ring a bell? the only thing that is unusual for `CORINFO_HELP_BULK_WRITEBARRIER` is that JIT creates a call for it in a late phase, so, perhaps, it misses some JIT-EE calls to prepare/compile it?

**Comment by jkotas** [comment]
It does not repro for me on latest main. What is the commit that the failure reproed on?

**Comment by EgorBo** [comment]
> It does not repro for me on latest main. What is the commit that the failure reproed on?

just checked on the latest main - still repros for me, I forgot to mention that I had `DOTNET_ReadyToRun=0` too

**Comment by EgorBo** [comment]
Seems like the culprit is `DOTNET_ProfAPI_RejitOnAttach=0`
