### ISSUE TITLE
ConcurrentQueue's TryDequeue is not thread-safe

### ISSUE THREAD

**Issue by zhenlei520** [dotnet/runtime#102256]
### Describe the bug

The TryDequeue method is not thread-safe, and the data obtained through multiple threads in parallel is duplicated.

> .net framework 461 and .net8 have this problem

### To Reproduce

```
ConcurrentQueue<int> list = new ConcurrentQueue<int>();
for (var i = 0; i < 100000; i++)
{
    list.Enqueue(i);
}

var list2 = new List<int>();
Parallel.For(0, list.Count, new ParallelOptions()
{
    MaxDegreeOfParallelism = 10
}, _ =>
{
    if (list.TryDequeue(out var log))
    {
        list2.Add(log);
    }
});

var oldCount = list2.Count();
var count = list2.Distinct().Count();
Assert.AreEqual(oldCount, count);
```

**Comment by EgorBo** [comment]
+ to the List.Add concern. the code has assumes that List.Add is thread-safe which is not, so I don't see any .NET issues here

**Comment by zhenlei520** [comment]
> The following variant still calls ConcurrentQueue<T>.TryDequeue on multiple threads in parallel, but it avoids using the thread-unsafe List<T>.Add method on the same instance in parallel. Instead, it creates a separate List<T> for each parallel partition and then concatenates these lists thread-safely when finished. The result is `oldCount = 100000, count = 100000`, as expected.
> 
> ```cs
> using System;
> using System.Collections.Concurrent;
> using System.Collections.Generic;
> using System.Linq;
> using System.Threading.Tasks;
> 
> class Program
> {
>     static void Main()
>     {
>         ConcurrentQueue<int> list = new ConcurrentQueue<int>();
>         for (var i = 0; i < 100000; i++)
>         {
>             list.Enqueue(i);
>         }
> 
>         var list2 = new List<int>();
>         Parallel.For(
>             fromInclusive: 0,
>             toExclusive: list.Count,
>             parallelOptions: new ParallelOptions()
>             {
>                 MaxDegreeOfParallelism = 10
>             },
>             localInit: () => new List<int>(),
>             body: (int index, ParallelLoopState state, List<int> local) =>
>             {
>                 if (list.TryDequeue(out var log))
>                 {
>                     local.Add(log);
>                 }
>                 return local;
>             },
>             localFinally: (List<int> local) =>
>             {
>                 lock (list2)
>                 {
>                     list2.AddRange(local);
>                 }
>             });
> 
>         var oldCount = list2.Count();
>         var count = list2.Distinct().Count();
>         Console.WriteLine($"oldCount = {oldCount}, count = {count}");
>     }
> }
> ```

I made a mistake here. List is not thread-safe. Thank you very much.
