### ISSUE TITLE
Feature Request: Add a dotnet root path property to the runtimeconfig.json file.

### ISSUE THREAD

**Issue by BillArmstrong** [dotnet/runtime#102329]
We have developed an application that has multiple DotNet console applications that reside in multiple folders. We want our application to be deployed with minimal system changes or prerequisites. As such we publish each of our projects with the "--self-contained true" option. As a result, our deployment package is larger than we would like.

To minimize the size of our deployment package, I've changed the publish option to "--self-contained false" on each application and included the dotnet runtime binaries in a "runtime" folder at the root of our installation package. I need all of the applications to load the runtime from that location.

I know that I can set the DOTNET_ROOT environment variable to accomplish this, but I don't want to make any global system changes. It would be great if we could add the dotnet root folder as a relative path in the runtimeconfig.json file of each application.

The approach that I'm currently taking is to create my own host executable in C++ that will load the hostfxr.dll file in our runtime folder and make the hostfxr_main_startupinfo call needed to execute our application. Being able to specify the root path in the config file would have saved me from having to do this.

**Comment by vitek-karas** [comment]
This has been discussed several times, and there's some good ideas for a solution, just nothing implemented yet.
Very similar proposal: https://github.com/dotnet/runtime/issues/64430
Broader design discussion: https://github.com/dotnet/runtime/issues/71282

**Comment by agocke** [comment]
Closing as duplicate.
