### ISSUE TITLE
Inner exception is not set when AssemblyLoadContext.Resolving handler throws an exception

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#1023]
1. Add a handler that throws an exception to `AssemblyLoadContext.Resolving` for the default ALC
2. Load an assembly (such that the handler would be called)
3. A `FileLoadException` is thrown, but its inner exception is not set to the one thrown by the handler

This is only the case for the default ALC. For a handler for the event on a custom ALC, the inner exception does get set to the one thrown by the handler.

**Comment by LakshanF** [comment]
Can repro this using a modified sample from https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading. Specifically changing from alc.LoadFromAssemblyPath() to alc.LoadFromAssemblyName() to ensure that the overriden alc.Load() gets called which will return null

Default ALC Resolving event throws: FileNotFoundException with inner exception set to null
Custom ALC Resolving event throws: FileLoadException with the inner exception set to the exception thrown by the handler

**Comment by LakshanF** [comment]
The default Resolving handler gets called by coreclr!CLRPrivBinderCoreCLR::BindAssemblyByName in [clrprivbindercoreclr.cpp](https://github.com/dotnet/runtime/blob/116aae9255c217c6cddc54190c2435fc44e3f426/src/coreclr/src/binder/clrprivbindercoreclr.cpp#L99) that swallows managed exceptions via EX_CATCH_HRESULT(hr). 

Given that the exception logic is there despite the [guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/exceptions.md#ex_catch_hresult) for this situation in runtime exceptions, there are [other ](https://github.com/dotnet/runtime/blob/116aae9255c217c6cddc54190c2435fc44e3f426/src/coreclr/src/vm/coreassemblyspec.cpp#L146 ) callers to this method, and possible non-managed callers using this method, I'm not very comfortable removing the exception handling code here to fix this issue.

For completeness, below are the relevant native frames for the default and non-default handlers when they throw. Note the additional 3 frames in the default case (between the default frame 0b and 0f). In the default case, the first call to AssemblyBinder::BindUsingHostAssemblyResolver gets called with CLRPrivBinderCoreCLR pTPABinder set to non-null and the subsequent call to the same method from the problem method, CLRPrivBinderCoreCLR::BindAssemblyByName, is with pTPABinder set to null.

- Default (with the issue)
    07 00000047`e0b99f50 00007ff8`b1eb869c     coreclr!CallDescrWorkerInternal+0x83 [F:\workspace\_work\1\s\src\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 100] 
    08 00000047`e0b99f90 00007ff8`b1e423ef     coreclr!MethodDescCallSite::CallTargetWorker+0x268 [F:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.cpp @ 552] 
    09 (Inline Function) --------`--------     coreclr!MethodDescCallSite::Call_RetOBJECTREF+0x23 [F:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.h @ 461] 
    0a 00000047`e0b9a0d0 00007ff8`b1e41e6c     coreclr!RuntimeInvokeHostAssemblyResolver+0x56b [F:\workspace\_work\1\s\src\coreclr\src\vm\appdomain.cpp @ 5451]
    0b 00000047`e0b9a6e0 00007ff8`b1e463c8     coreclr!BINDER_SPACE::AssemblyBinder::BindUsingHostAssemblyResolver+0x28 [F:\workspace\_work\1\s\src\coreclr\src\binder\assemblybinder.cpp @ 1405] 

    0c 00000047`e0b9a730 00007ff8`b1e42187     coreclr!CLRPrivBinderCoreCLR::BindAssemblyByName+0x388 [F:\workspace\_work\1\s\src\coreclr\src\binder\clrprivbindercoreclr.cpp @ 99] 
    0d 00000047`e0b9a8e0 00007ff8`b1e41e6c     coreclr!RuntimeInvokeHostAssemblyResolver+0x303 [F:\workspace\_work\1\s\src\coreclr\src\vm\appdomain.cpp @ 5394] 
    0e 00000047`e0b9aef0 00007ff8`b1e41da0     coreclr!BINDER_SPACE::AssemblyBinder::BindUsingHostAssemblyResolver+0x28 [F:\workspace\_work\1\s\src\coreclr\src\binder\assemblybinder.cpp @ 1405] 

    0f 00000047`e0b9af40 00007ff8`b1e43589     coreclr!CLRPrivBinderAssemblyLoadContext::BindAssemblyByName+0x170 [F:\workspace\_work\1\s\src\coreclr\src\binder\clrprivbinderassemblyloadcontext.cpp @ 87] 
    10 00000047`e0b9aff0 00007ff8`b1e43c3b     coreclr!AssemblySpec::Bind+0x189 [F:\workspace\_work\1\s\src\coreclr\src\vm\coreassemblyspec.cpp @ 146] 
    11 00000047`e0b9b940 00007ff8`b1f16381     coreclr!AppDomain::BindAssemblySpec+0x16b [F:\workspace\_work\1\s\src\coreclr\src\vm\appdomain.cpp @ 4001] 
    12 00000047`e0b9c090 00007ff8`b1f1593c     coreclr!AssemblySpec::LoadDomainAssembly+0xf1 [F:\workspace\_work\1\s\src\coreclr\src\vm\assemblyspec.cpp @ 789] 
    13 (Inline Function) --------`--------     coreclr!AssemblySpec::LoadAssembly+0x15 [F:\workspace\_work\1\s\src\coreclr\src\vm\assemblyspec.cpp @ 645] 
    14 00000047`e0b9c1c0 00007ff8`ab47d426     coreclr!AssemblyNative::InternalLoad+0x30c [F:\workspace\_work\1\s\src\coreclr\src\vm\assemblynative.cpp @ 121] 

- Non-Default
    07 0000004b`cbbfaa90 00007ff8`b1eb869c     coreclr!CallDescrWorkerInternal+0x83 [F:\workspace\_work\1\s\src\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 100] 
    08 0000004b`cbbfaad0 00007ff8`b1e423ef     coreclr!MethodDescCallSite::CallTargetWorker+0x268 [F:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.cpp @ 552] 
    09 (Inline Function) --------`--------     coreclr!MethodDescCallSite::Call_RetOBJECTREF+0x23 [F:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.h @ 461] 
    0a 0000004b`cbbfac10 00007ff8`b1e41e6c     coreclr!RuntimeInvokeHostAssemblyResolver+0x56b [F:\workspace\_work\1\s\src\coreclr\src\vm\appdomain.cpp @ 5451] 
    0b 0000004b`cbbfb220 00007ff8`b1e41da0     coreclr!BINDER_SPACE::AssemblyBinder::BindUsingHostAssemblyResolver+0x28 [F:\workspace\_work\1\s\src\coreclr\src\binder\assemblybinder.cpp @ 1405] 

    0c 0000004b`cbbfb270 00007ff8`b1e43589     coreclr!CLRPrivBinderAssemblyLoadContext::BindAssemblyByName+0x170 [F:\workspace\_work\1\s\src\coreclr\src\binder\clrprivbinderassemblyloadcontext.cpp @ 87] 
    0d 0000004b`cbbfb320 00007ff8`b1e43c3b     coreclr!AssemblySpec::Bind+0x189 [F:\workspace\_work\1\s\src\coreclr\src\vm\coreassemblyspec.cpp @ 146] 
    0e 0000004b`cbbfbc70 00007ff8`b1f16381     coreclr!AppDomain::BindAssemblySpec+0x16b [F:\workspace\_work\1\s\src\coreclr\src\vm\appdomain.cpp @ 4001] 
    0f 0000004b`cbbfc3c0 00007ff8`b1f1593c     coreclr!AssemblySpec::LoadDomainAssembly+0xf1 [F:\workspace\_work\1\s\src\coreclr\src\vm\assemblyspec.cpp @ 789] 
    10 (Inline Function) --------`--------     coreclr!AssemblySpec::LoadAssembly+0x15 [F:\workspace\_work\1\s\src\coreclr\src\vm\assemblyspec.cpp @ 645] 
    11 0000004b`cbbfc4f0 00007ff8`ab47d426     coreclr!AssemblyNative::InternalLoad+0x30c [F:\workspace\_work\1\s\src\coreclr\src\vm\assemblynative.cpp @ 121]

**Comment by LakshanF** [comment]
For completion and acknowledgement, below is an analysis from @elinor-fung that made it easier for me to remove the exception handling;

------

The only calls that I see are from:

- [AssemblySpec::Bind](https://github.com/dotnet/runtime/blob/50f82db26eaa743074fea538063abb4fec0adb02/src/coreclr/src/vm/coreassemblyspec.cpp#L146)
1. Called by [AppDomain::BindAssemblySpec](https://github.com/dotnet/runtime/blob/50f82db26eaa743074fea538063abb4fec0adb02/src/coreclr/src/vm/appdomain.cpp#L4000)
2. AppDomain::BindAssemblySpec already handles catching thrown exceptions and throwing a FileLoadException with the inner exception set to the caught exception
- [RuntimeInvokeHostAssemblyResolver](https://github.com/dotnet/runtime/blob/50f82db26eaa743074fea538063abb4fec0adb02/src/coreclr/src/vm/appdomain.cpp#L5394) 
1. It is called as the fallback to using the Default ALC when trying to load an assembly in a non-default ALC
2. This function is already expected to throw and is only called by AssemblyBinder::BindUsingHostAssemblyResolver, so removing the exception swallowing in CLRPrivBinderCoreCLR::BindAssemblyByName should not be problematic.
- [Assembly::BindAssemblyByName](https://github.com/dotnet/runtime/blob/3cf8d43713c6ee188486459d988db0af0d7596c6/src/coreclr/src/binder/assembly.cpp#L187)
1. I don’t think this is actually directly called by anything

Any managed APIs should end up going through those same paths above.
