### ISSUE TITLE
No way to create the "IAttributeSet" required by Android ExoPlayer constructor in .NET/C#

### ISSUE THREAD

**Issue by jonmdev** [dotnet/runtime#102300]
## Description

ExoPlayer is the Android video player recommended by Google and used by the MAUI Community Toolkit for video playback.

It has the following constructor in .NET:

`public unsafe StyledPlayerView (global::Android.Content.Context? context, global::Android.Util.IAttributeSet? attrs) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)`

ExoPlayer can be constructed with a SurfaceView, TextureView, or none type of `surface_type`. This `surface_type` determines rendering behavior of the video player. It can only be declared on construction of the ExoPlayer.

In order to specify this, we are intended by Google to create or load some XML stating the `surface_type`, convert it to an `IAttributeSet` and then pass it to this constructor.

However, this does not work in .NET/C# and there is therefore currently no way to build a TextureView type ExoPlayer. SurfaceView is the default but TextureView is needed in many situations, and there is no way in .NET to get it.

## Prior Discussion

See: 
- https://github.com/androidx/media/issues/1375
- https://github.com/androidx/media/issues/1360
- https://github.com/CommunityToolkit/Maui/issues/1730
- https://github.com/CommunityToolkit/Maui/issues/1773
- https://stackoverflow.com/questions/78446498/how-to-create-textureview-programmatically-with-exoplayer-in-net-maui
- https://stackoverflow.com/questions/78457606/how-to-create-iattributeset-from-xml-string-using-xmlreader-in-net-android

Despite two Android discussions, two MAUI discussions, and two StackOverflow discussions, no one anywhere can propose a working method for this to be done. Thus it seems this is a C#/.NET bug that must be fixed so we can use this properly.

By contrast a supposedly working Kotlin method is proposed [here](https://stackoverflow.com/a/75302312/10305478), but the functions referenced don't have matching C# equivalents so this is a dead end.

## My Best Attempt

My best attempt to do this is is with adding the following code to a default .NET Android Application:

```
protected override void OnCreate(Bundle? savedInstanceState) {
    base.OnCreate(savedInstanceState);

    string xmlString =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
        "<Com.Google.Android.Exoplayer2.UI.StyledPlayerView " +
        //"<com.google.android.exoplayer2.ui.PlayerView " +
        "android:id=\"@+id/player_view\" " +
        "app:surface_type=\"texture_view\" " +
        "android:layout_width=\"match_parent\" " +
        "android:layout_height=\"match_parent\"/>";

    XmlReader xmlReader = XmlReader.Create(new StringReader(xmlString));
    xmlReader.Read(); // https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlreader.read?view=net-8.0
    
    Android.Util.IAttributeSet attributes = Android.Util.Xml.AsAttributeSet(xmlReader);
    
    //BUILD EXOPLAYER
    Com.Google.Android.Exoplayer2.UI.StyledPlayerView styledPlayerView = new(this, attributes);
    System.Diagnostics.Debug.WriteLine("SURFACE TYPE " + styledPlayerView.VideoSurfaceView.GetType());
```
## Error 

However, this returns the error: 

`**Java.Lang.ClassCastException:** 'android.util.XmlPullAttributes cannot be cast to android.content.res.XmlBlock$Parser'`

The only reference I can find to this error suggests it is an insurmountable dead end: https://stackoverflow.com/questions/33331935/xmlpullattributes-cannot-be-cast-to-xmlblockparser#45918669

So what is the solution? Can .NET be fixed so that we can use this constructor and build ExoPlayer with a TextureView rather than SurfaceView?

## Bug Project

See reproduction bug Project here: https://github.com/jonmdev/AndroidIAttributeSetBug

## Reproduction Steps

Play bug project above. Or, to remake it, in Visual Studio 2022:

1) File > New > Android Application
2) Add the ExoPlayer NuGet `Xam.Plugins.Android.ExoPlayer`
3) Then in MainActivity.cs, copy/paste the code from above or also here: https://github.com/jonmdev/AndroidIAttributeSetBug/blob/main/AndroidIAttributeSetBug/MainActivity.cs

### Expected behavior

Should be able to make a TextureView ExoPlayer.

### Actual behavior

Dead end error - cannot do so.

### Regression?

I can find no reference anywhere on the Internet that suggests this ever worked or anyone has ever successfully made it work.

### Known Workarounds

None known seemingly by anyone anywhere.

### Other information

Any help toward a solution is greatly appreciated.

**Comment by huoyaoyuan** [comment]
Android API for .NET lives in https://github.com/xamarin/xamarin-android. Discussions should go there.

Searching for the corresponding API of [kotlin](https://stackoverflow.com/questions/68629114/use-textureview-programmatically-with-exoplayer/75302312#75302312), I can find an API at https://learn.microsoft.com/en-us/dotnet/api/android.content.res.resources.getxml .

**Comment by jonmdev** [comment]
Thank you actually @huoyaoyuan !

Your reply made me realize the Kotlin solution I posted was not programmatically creating the XML but just loading from resources. It seems Android offers no way to allow one to programmatically do this. One must save the XML to resources and then load it.

Absolutely absurd in my opinion, but this does work.

## .NET SOLUTION

1) Create XML file named "test.xml" in Resources\layout
2) Copy paste into it:

```
<?xml version="1.0" encoding="utf-8" ?> 
<com.google.android.exoplayer2.ui.StyledPlayerView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/test"
    app:surface_type="texture_view"
    android:layout_width= "match_parent"
    android:layout_height= "match_parent" />
```

3) Run code in MainActivity.cs:

```
XmlReader xmlResource = this.Resources.GetXml(Resource.Layout.test);
xmlResource.Read();

Android.Util.IAttributeSet attributes = Android.Util.Xml.AsAttributeSet(xmlResource);

//BUILD EXOPLAYER
Com.Google.Android.Exoplayer2.UI.StyledPlayerView styledPlayerView = new(this, attributes); 
```

This does work.
