### ISSUE TITLE
CancelPendingFlushDuringBackpressureThrows test fails on arm32 

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#102378]
```
  Starting:    System.Text.Json.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows [FAIL]
      Assert.Equal() Failure: Values differ
      Expected: 11
      Actual:   13
      Stack Trace:
           at System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows()
        --- End of stack trace from previous location ---
```
Example: https://dev.azure.com/dnceng-public/public/_build/results?buildId=678396&view=ms.vss-test-web.build-test-results-tab

## Build Information
Build: 
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "CancelPendingFlushDuringBackpressureThrows [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=678396
**Error message validated:** `[CancelPendingFlushDuringBackpressureThrows [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/17/2024 2:38:23 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[681018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681018)|dotnet/runtime|[System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681018&view=ms.vss-test-web.build-test-results-tab&runId=16898442&resultId=206013)|dotnet/runtime#102188|
|[678396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678396)|dotnet/runtime|[System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678396&view=ms.vss-test-web.build-test-results-tab&runId=16816696&resultId=207890)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|2|2|

**Comment by EgorBo** [comment]
Looks like this test was introduced recently in https://github.com/dotnet/runtime/pull/101461

cc @BrennanConroy 
if that helps, in this outerloop pipeline JIT is quite slow so if a test relies on some timings it might fail

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20240518.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680155&view=ms.vss-test-web.build-test-results-tab&runId=16866990&resultId=202352&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-jitstress2_jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 11
Actual:   13
```

**Stack trace:**
```
   at System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows()
--- End of stack trace from previous location ---
```
