### ISSUE TITLE
How can I use IReadOnlySet in netstandard2.0?

### ISSUE THREAD

**Issue by marco-carvalho** [dotnet/runtime#102389]
#### Description
I am working on a project that targets `netstandard2.0` and I need access to the `IReadOnlySet` interface from the `System.Collections.Generic` namespace. Unfortunately, `IReadOnlySet` is not available in `netstandard2.0`, and upgrading the target framework is not feasible for my project at this time.

#### Use Case
The main use case is to leverage the `IReadOnlySet` interface to improve type safety and performance in collections that should be immutable. Currently, there is no straightforward way to use this interface in `netstandard2.0`, which limits the ability to write code.

#### Proposal
Would it be possible to provide a  `System.Collections.Generic` NuGet package with support for `IReadOnlySet` for `netstandard2.0`? This would greatly benefit developers who need to maintain compatibility with `netstandard2.0` while still taking advantage of newer collection interfaces.

**Comment by teo-tsirpanis** [comment]
You can define it in your own code and provide wrapper classes on top of the foundational set types that implement it, but there is unfortunately no way to change .NET Standard 2.0's foundational set types to implement `IReadOnlySet<T>`.

**Comment by marco-carvalho** [comment]
There is a planning of creating some type of `System.Collections.Generic` NuGet package (like [System.Collection.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/)), for users that need to access those classes/interfaces?

**Comment by huoyaoyuan** [comment]
NuGet package can't modify existing type with additional members or interface implementations. It can only "replace" a type with new one with higher assembly version. Replacing assemblies are quite tricky and complicated. `netstandard` itself is already a trick existence.

`HashSet<T>` does not live in `mscorlib` for .NET Framework so the possibility is not eliminated, but it's very unlikely to happen. Other types like `List<T>` are more fundamental and can't be modified by OOB package.
