### ISSUE TITLE
Missing centos-stream9 runtime assets

### ISSUE THREAD

**Issue by MiYanni** [dotnet/runtime#102344]
## Summary

In transitioning the dotnet/installer repo into dotnet/sdk, the build uses some Linux containers. One of them is `centos-stream9`. However, the build does not succeed to download some runtime assets specific to this container.

Here are some example URLs it was looking for:
```
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/9.0.0-preview.4.24251.2/dotnet-runtime-deps-9.0.0-preview.4.24251.2-centos.9-x64.rpm
 
https://dotnetbuilds.blob.core.windows.net/public/Runtime/9.0.0-preview.4.24251.2/dotnet-runtime-deps-9.0.0-preview.4.24251.2-centos.9-x64.rpm
 
https://dotnetbuilds.blob.core.windows.net/internal/Runtime/9.0.0-preview.4.24251.2/dotnet-runtime-deps-9.0.0-preview.4.24251.2-centos.9-x64.rpm
```

However, if you change the ending from `.9-x64.rpm` to `.8-x64.rpm`, the links are valid and able to download the assets. This leads me to believe the assets are not being published for `centos-stream9` but are still being published for `centos-stream8`.

### Reproduction Steps

Try downloading the asset from any of these links:
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/9.0.0-preview.4.24251.2/dotnet-runtime-deps-9.0.0-preview.4.24251.2-centos.9-x64.rpm
- https://dotnetbuilds.blob.core.windows.net/public/Runtime/9.0.0-preview.4.24251.2/dotnet-runtime-deps-9.0.0-preview.4.24251.2-centos.9-x64.rpm
- https://dotnetbuilds.blob.core.windows.net/internal/Runtime/9.0.0-preview.4.24251.2/dotnet-runtime-deps-9.0.0-preview.4.24251.2-centos.9-x64.rpm

### Expected behavior

The assets are able to be downloaded.

### Actual behavior

They will fail to download/don't exist.

### Known Workarounds

I've told the build to use `centos-stream8` for the time being since those assets exist.

### Configuration

This was specific to building the dotnet/sdk repo in AzDO on the `centos-stream9` Linux container.

**Comment by NikolaMilosavljevic** [comment]
CI legs for CentOS-Stream9 are missing in runtime repo.

**Comment by akoeplinger** [comment]
We presumably need to update https://github.com/dotnet/runtime/blob/main/src/installer/pkg/sfx/installers/dotnet-runtime-deps/dotnet-runtime-deps-centos.8.proj

@jkoritzinsky I see you updated these last year in https://github.com/dotnet/runtime/pull/84805, do you know who owns these packages

**Comment by akoeplinger** [comment]
Also ties in with https://github.com/dotnet/runtime/pull/103379

**Comment by jkoritzinsky** [comment]
@NikolaMilosavljevic and I generally do the work for them. Officially, @NikolaMilosavljevic's team owns them.

I can update the packages again (just CentOS Stream this time because RHEL/Oracle Linux 8 are still supported in .NET 9)

**Comment by MiYanni** [comment]
@jkoritzinsky Can you let me know when the runtime change flows into the SDK? I can make a PR for the SDK after that to update the container there.
