### ISSUE TITLE
SupportedLinuxPlatforms_IsSupportedIsTrue failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#102479]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=682138
Build error leg or test failing: System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue
Pull request: https://github.com/dotnet/runtime/pull/102472

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "SupportedLinuxPlatforms_IsSupportedIsTrue",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=682138
**Error message validated:** `[SupportedLinuxPlatforms_IsSupportedIsTrue`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/21/2024 5:22:09 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[682950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682950)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682950&view=ms.vss-test-web.build-test-results-tab&runId=16952030&resultId=135332)|dotnet/runtime#101295|
|[682938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682938)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682938&view=ms.vss-test-web.build-test-results-tab&runId=16951600&resultId=141649)|dotnet/runtime#102248|
|[682905](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682905)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682905&view=ms.vss-test-web.build-test-results-tab&runId=16951108&resultId=142541)|dotnet/runtime#102469|
|[682941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682941)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682941&view=ms.vss-test-web.build-test-results-tab&runId=16950986&resultId=174342)|dotnet/runtime#102507|
|[682899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682899)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682899&view=ms.vss-test-web.build-test-results-tab&runId=16951026&resultId=139929)|dotnet/runtime#102297|
|[682932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682932)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682932&view=ms.vss-test-web.build-test-results-tab&runId=16950840&resultId=171881)|dotnet/runtime#102505|
|[682933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682933)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682933&view=ms.vss-test-web.build-test-results-tab&runId=16950768&resultId=157805)|dotnet/runtime#102506|
|[682872](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682872)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682872&view=ms.vss-test-web.build-test-results-tab&runId=16949894&resultId=146003)|dotnet/runtime#102262|
|[682742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682742)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682742&view=ms.vss-test-web.build-test-results-tab&runId=16947926&resultId=143940)|dotnet/runtime#102493|
|[682817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682817)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682817&view=ms.vss-test-web.build-test-results-tab&runId=16947702&resultId=162780)|dotnet/runtime#102496|
|[682754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682754)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682754&view=ms.vss-test-web.build-test-results-tab&runId=16947264&resultId=168474)|dotnet/runtime#102494|
|[682680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682680)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682680&view=ms.vss-test-web.build-test-results-tab&runId=16946532&resultId=135914)|dotnet/runtime#102490|
|[682671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682671)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682671&view=ms.vss-test-web.build-test-results-tab&runId=16946302&resultId=140005)|dotnet/runtime#101801|
|[682649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682649)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682649&view=ms.vss-test-web.build-test-results-tab&runId=16944446&resultId=136417)|dotnet/runtime#102489|
|[682643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682643)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682643&view=ms.vss-test-web.build-test-results-tab&runId=16944364&resultId=138712)|dotnet/runtime#102488|
|[682617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682617)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682617&view=ms.vss-test-web.build-test-results-tab&runId=16943284&resultId=136063)|dotnet/runtime#102487|
|[682593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682593)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682593&view=ms.vss-test-web.build-test-results-tab&runId=16941242&resultId=139135)|dotnet/runtime#99871|
|[682089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682089)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682089&view=ms.vss-test-web.build-test-results-tab&runId=16939422&resultId=144186)|dotnet/runtime#99818|
|[682524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682524)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682524&view=ms.vss-test-web.build-test-results-tab&runId=16938458&resultId=127419)|dotnet/runtime#102392|
|[682457](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682457)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682457&view=ms.vss-test-web.build-test-results-tab&runId=16936902&resultId=134443)|dotnet/runtime#102470|
|[682414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682414)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682414&view=ms.vss-test-web.build-test-results-tab&runId=16935528&resultId=139579)||
|[682341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682341)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682341&view=ms.vss-test-web.build-test-results-tab&runId=16933558&resultId=127784)|dotnet/runtime#102424|
|[682321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682321)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682321&view=ms.vss-test-web.build-test-results-tab&runId=16932986&resultId=133271)|dotnet/runtime#102469|
|[681938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681938)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681938&view=ms.vss-test-web.build-test-results-tab&runId=16931680&resultId=142740)|dotnet/runtime#102468|
|[682269](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682269)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682269&view=ms.vss-test-web.build-test-results-tab&runId=16931576&resultId=145874)|dotnet/runtime#102424|
|[682229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682229)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682229&view=ms.vss-test-web.build-test-results-tab&runId=16930956&resultId=132706)|dotnet/runtime#102476|
|[681910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681910)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681910&view=ms.vss-test-web.build-test-results-tab&runId=16929412&resultId=135814)|dotnet/runtime#102180|
|[682154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682154)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682154&view=ms.vss-test-web.build-test-results-tab&runId=16929384&resultId=133054)|dotnet/runtime#102364|
|[682148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682148)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682148&view=ms.vss-test-web.build-test-results-tab&runId=16929090&resultId=135875)|dotnet/runtime#102473|
|[682141](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682141)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682141&view=ms.vss-test-web.build-test-results-tab&runId=16929016&resultId=137602)|dotnet/runtime#102403|
|[682138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682138)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682138&view=ms.vss-test-web.build-test-results-tab&runId=16929006&resultId=135627)|dotnet/runtime#102472|
|[681983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681983)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681983&view=ms.vss-test-web.build-test-results-tab&runId=16926548&resultId=163642)||
|[681941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681941)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681941&view=ms.vss-test-web.build-test-results-tab&runId=16925942&resultId=153203)||
|[682066](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682066)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682066&view=ms.vss-test-web.build-test-results-tab&runId=16926552&resultId=121273)|dotnet/runtime#102415|
|[681930](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681930)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681930&view=ms.vss-test-web.build-test-results-tab&runId=16925894&resultId=176408)|dotnet/runtime#102408|
|[682017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682017)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682017&view=ms.vss-test-web.build-test-results-tab&runId=16925872&resultId=123573)|dotnet/runtime#102470|
|[682005](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682005)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682005&view=ms.vss-test-web.build-test-results-tab&runId=16925692&resultId=149306)|dotnet/runtime#102469|
|[681878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681878)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681878&view=ms.vss-test-web.build-test-results-tab&runId=16925298&resultId=135184)|dotnet/runtime#102271|
|[681927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681927)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681927&view=ms.vss-test-web.build-test-results-tab&runId=16925188&resultId=163214)|dotnet/runtime#102407|
|[681949](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681949)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681949&view=ms.vss-test-web.build-test-results-tab&runId=16923674&resultId=153580)|dotnet/runtime#102461|
|[681846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681846)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681846&view=ms.vss-test-web.build-test-results-tab&runId=16919700&resultId=158854)|dotnet/runtime#102397|
|[681854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681854)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681854&view=ms.vss-test-web.build-test-results-tab&runId=16920462&resultId=134803)||
|[681841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681841)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681841&view=ms.vss-test-web.build-test-results-tab&runId=16920020&resultId=128030)|dotnet/runtime#102364|
|[681748](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681748)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681748&view=ms.vss-test-web.build-test-results-tab&runId=16916934&resultId=164707)||
|[681723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681723)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681723&view=ms.vss-test-web.build-test-results-tab&runId=16916554&resultId=159263)||
|[681713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681713)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681713&view=ms.vss-test-web.build-test-results-tab&runId=16916944&resultId=133667)|dotnet/runtime#102295|
|[681672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681672)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681672&view=ms.vss-test-web.build-test-results-tab&runId=16916192&resultId=135055)|dotnet/runtime#102461|
|[681666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681666)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681666&view=ms.vss-test-web.build-test-results-tab&runId=16915904&resultId=129212)|dotnet/runtime#101295|
|[681558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681558)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681558&view=ms.vss-test-web.build-test-results-tab&runId=16914414&resultId=129759)|dotnet/runtime#102458|
|[681563](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681563)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681563&view=ms.vss-test-web.build-test-results-tab&runId=16914402&resultId=116627)|dotnet/runtime#85694|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|50|50|

**Comment by wfurt** [comment]
Alpine 3.17. Possibly outcome of https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1020 @ManickaP ?

**Comment by ManickaP** [comment]
It's https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1064 @jkoritzinsky are you gonna look into it or should I revert for now?

I just tested it with my change (works, `QuicConnection.IsSupported` ==> true) and with current main (doesn't work, `QuicConnection.IsSupported` ==> false).

**Comment by jkoritzinsky** [comment]
You can revert it for now to unblock builds and I'll take a look later.

**Comment by ManickaP** [comment]
Reverted in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1068, we just need to wait for it to flow.

**Comment by ManickaP** [comment]
Closing, haven't failed in 2 days, fix is in.
