### ISSUE TITLE
HttpClient doesn't support proxy server in HTTPS protocol in Linux

### ISSUE THREAD

**Issue by ms-hujia** [dotnet/runtime#102441]
From the document of `HttpClient`, I saw below description:

> The proxy server may be a hostname or IP address, optionally followed by a colon and port number, or it may be an http URL, optionally including a username and password for proxy authentication. The URL must be start with http, not https, and cannot include any text after the hostname, IP, or port.

I'm wondering if this is a platform specific limitation due to underlying stack, or it's due to some historical consideration which's gone away now. As using proxy server secured by HTTPS is common in customer's corpnet, could you help to evaluate if it's possible to support proxy server in HTTPS protocol by Linux? It's really frustrating as other clients/scripts written by Golang, Python, Ruby and curl could well support this scenario.

**Comment by MihaZupan** [comment]
Looks like our docs are outdated here. HTTPS proxy support was added in .NET 8.0: #87638

The scheme may also be `socks4`, `socks4a` or `socks5`.

**Comment by ms-hujia** [comment]
Thanks for the information, Miha!

I've verified the different behavior of dotnet 7 and dotnet 8:

For dotnet 7, the HTTP request will succeed but it doesn't go through the proxy server in HTTPS protocol.

For dotnet 8, the HTTP request will succeed, and it goes through the proxy server and secured by TLS.

Hope above behaviors could be updated in the public document.

**Comment by deeprobin** [comment]
@MihaZupan I would take that feature, if you want to assign it to me :smile:

**Comment by MihaZupan** [comment]
Thanks @deeprobin, note that this is a docs-only issue.

**Comment by deeprobin** [comment]
@MihaZupan Could you tag someone to review my PR?
