### ISSUE TITLE
NTLM does not always work properly on all platforms with MAUI with SocketsHttpHandler

### ISSUE THREAD

**Issue by JeroenBer** [dotnet/runtime#102483]
### Description

We recently ported our app from Xamarin to MAUI and run into some NTLM network issues on Android and iOS, on UWP it works fine.
This is a major problems for some of our clients.

### Steps to Reproduce

I wrote a small MAUI testprogram. It is located here:
https://github.com/JeroenBer/MauiTestNltm

If you run this on UWP NTLM test 1, 2 and 3 will all succeed.

If you run this on Android or iOS only NTLM test 1 will succeed and NTLM test 2 and 3 will fail.

On Xamarin using the old System.Net.Http.MonoWebRequestHandler this used to work fine for all 3 cases. So this seems to be a bug.

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Did you find any workaround?

No

**Comment by filipnavara** [comment]
I assume this could have been fixed in .NET 9 for Android by https://github.com/dotnet/runtime/pull/95898. On iOS we also unconditionally switched to use managed NTLM in .NET 9 so it would be affected by the same fix. While the root cause may be different on .NET 8 / iOS (which relies on GSSAPI system library) the behavior would be aligned now.

I have long intended to push for backporting #95898 to .NET 8, so additional data to support it would be nice. This needs confirmation that the "Extended Authentication" option is really the root cause.

**Comment by rzikm** [comment]
Is it possible to test this with .NET 9 preview? If it is the same issue as filipnavara references, then we may be able to make case for servicing and backporting the fix.

**Comment by JeroenBer** [comment]
As a response to your questions, this is not MAUI specific but is more at the dotnet ios/android runtime level. The errors it gives are just 401 Unauthorized. 

I will try to test .NET 9 this week to see if Extended Authentication is causing the issue.

**Comment by filipnavara** [comment]
Backport in progress: https://github.com/dotnet/runtime/pull/102565

**Comment by MohamedBayoumi25** [comment]
I Face Problem  NTLM does not  work properly on all Android with MAUI

**Comment by filipnavara** [comment]
> I Face Problem NTLM does not work properly on all Android with MAUI

Please file a new issue with detailed description. All fixes for known problems were backported and released in .NET 8.0.7 service release.

**Comment by MohamedBayoumi25** [comment]
> > I Face Problem NTLM does not work properly on all Android with MAUI
> 
> Please file a new issue with detailed description. All fixes for known problems were backported and released in .NET 8.0.7 service release.
 Face Problem NTLM does not work properly on all Android with MAUI

when i get data from sharepoint in .net maui will success in windows but android un auth

**Comment by rzikm** [comment]
Issue was fixed in 9.0 and backported to 8.0. If you encounter similar problems, please open a new issue with detailed description (and ideally attached repro).
