### ISSUE TITLE
Fix internal tool restore in official build and re-enable

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1024]
I saw this error with the CoreCLR and Libraries "Restore internal tools" steps while trying to develop official builds:

```
Build FAILED. 
 
 "/Users/runner/runners/2.160.1/work/1/s/eng/common/internal/Tools.csproj" (Restore target) (1) -> 
 (Restore target) -> 
 /Users/runner/runners/2.160.1/work/1/s/.dotnet/sdk/5.0.100-alpha1-015772/NuGet.targets(123,5): error : Value cannot be null. (Parameter 'folderName') [/Users/runner/runners/2.160.1/work/1/s/eng/common/internal/Tools.csproj] 
```

https://github.com/dotnet/runtime/pull/1016 removes internal tooling to unblock the official build, but this needs to be fixed and re-enabled.

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/coreclr/templates/build-job.yml#L83-L87

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/coreclr/templates/build-job.yml#L111-L130

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/libraries/build-job.yml#L68-L80

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/Versions.props#L18-L19

**Comment by safern** [comment]
Self assigned as I set-up this in corefx and have some experience with internal restore. Will give it a shot.
