### ISSUE TITLE
long.TryParse raises RuntimeBinderException (ambiguous call)

### ISSUE THREAD

**Issue by davegines** [dotnet/runtime#102414]
### Description

long.TryParse will raise a runtime exception when the first argument is of type dynamic.

### Reproduction Steps
```csharp
dynamic? a = null;
var parsed = long.TryParse(a, out long result);
```
### Expected behavior

I would expect that the TryParse method would return true or false. I would not expect it to raise an exception.

### Actual behavior

When executed an exception is raised with the following message: Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The call is ambiguous between the following methods or properties: 'long.TryParse(string, out long)' and 'long.TryParse(System.ReadOnlySpan<byte>, out long)'

### Regression?

This is a new issue/bug in .net 8. It was not a problem in .net 7.

### Known Workarounds

There are two workarounds that I can think of.
1. Explicitly cast the input
```csharp
dynamic? a = null;
var parsed = long.TryParse(a as string, out long result);
```
2. Wrap the long.TryParse in a try/catch block
```csharp
bool parsed = false;
long result = default;
try
{
  dynamic? a = null;
  parsed = long.TryParse(a, out result);
}
catch (RuntimeBinderException) { }
```

### Configuration

.NET version: .net 8
OS: Mac OS Sonoma 14.4.1
architecture: x86
This is not configuration specific as it also is a problem when run on our CircleCI linux servers

**Comment by CyrusNajmabadi** [comment]
> I would expect that the TryParse method would return true or false. I would not expect it to raise an exception.

TryParse is not the thing throwing the exception. The code doesn't even make it to the TryParse point because the call is ambiguous. Instead, the "runtime binder" which handles figuring out what a dynamic call means is telling you that it can't figure it out. There are two applicable overloads and so the code is ambiguous.  

This is always possible when adding an overload to a type and having someone recompile when they passed untyped arguments.

**Comment by davegines** [comment]
My concern was that the behavior changed when we upgraded to .net 8 and we only caught this with the help of unit tests, since there was no compilation error.

I appreciate the clarification @CyrusNajmabadi. We'll plan on handling all these changes in our own code base. Thanks again.

**Comment by CyrusNajmabadi** [comment]
> since there was no compilation error.

Correct.  That's expected with dynamic.  It *is* the feature that says "do not figure this out statically at compile-time.  Instead, blow up at runtime if there's an issue".  If you don't control exactly the calling code and the code it is dynamically dispatching to, you should *always* assume it will blow up.
