### ISSUE TITLE
Requires an SMB library that supports SMB3.1.1 and runs on Windows and Linux.

### ISSUE THREAD

**Issue by n2029-ndensan** [dotnet/runtime#102477]
Hi,

I tried looking for an SMB library that supports .NET Core, but I couldn't find one that supported SMB3.1.1. SMB recognizes that Microsoft determines the specifications. Therefore, we would like Microsoft to provide a .NET Core SMB library that fully supports SMB specifications. At the very least, as the title says, I would like to provide an SMB library that supports SMB3.1.1 and runs on Windows and Linux.

Best,
Motonari

**Comment by startewho** [comment]
https://github.com/TalAloni/SMBLibrary

the lib readme say it support SMB3.0

**Comment by n2029-ndensan** [comment]
Am I correct in my understanding that SMBLibrary supports all features of SMB3?
Is it correct to understand that the following issue supports SMB3.1.1?
https://github.com/TalAloni/SMBLibrary/issues/66

**Comment by n2029-ndensan** [comment]
When I asked SMBLibrary's contact information, they answered that they support SMB3.1.1.
