### ISSUE TITLE
Question - is it fine to bootstrap coreclr in DllMain?

### ISSUE THREAD

**Issue by podprad** [dotnet/runtime#102596]
I'm developing a legacy x32 unmanaged application that is extended by .NET Framework components.
It worked fine for ages and now it's time to upgrade from .NET Framework to .NET 8.

I wrote a C++ bootstrapper code in which I load coreclr.dll manually (by LoadLibrary("coreclr.dll")) and afterwards I call coreclr_initialize and coreclr_create_delegate.

Everything seems fine, coreclr initializes successfully and I'm able to run my .NET code.

The problem is that I'm doing the bootstrapping in DllMain() on DLL_PROCESS_ATTACH. I'm not sure if it's the right place. MSDN says that heavy operations should be avoided in DllMain. From other hand, everything seems to work fine.

Do you have any suggestions/pros/cons about bootstrapping .NET8 in DllMain?

**Comment by jkotas** [comment]
Bootstrapping CoreCLR in DllMain is not safe.

https://learn.microsoft.com/windows/win32/dlls/dllmain describes rules for what is safe to do in DllMain. There are significant limits on what can be done safely in DllMain. Bootstrapping CoreCLR violates number of these rules. If you bootstrap CoreCLR in DllMain, you will see intermittent dead locks or crashes when the .dll is loaded into a process with other things going on.
