### ISSUE TITLE
.NET 8.0.5 SDK Release Schedule

### ISSUE THREAD

**Issue by jdyer-draeger** [dotnet/runtime#102522]
When will the SDK download be updated to 8.0.5?  The SDK has been sitting 8.0.3 for 2 months.  There's bugs that have been address in 0.4 and 0.5 that I need for development.

Or is it possible to install the 8.0.5 runtime "over top" of the SDK to update it in place?

Thanks,
John

**Comment by Symbai** [comment]
You can install the nightly builds: https://github.com/dotnet/core/blob/main/daily-builds.md

**Comment by ericstj** [comment]
8.0.5 is available here https://dotnet.microsoft.com/en-us/download/dotnet/8.0.  Which download is it you're asking about?

**Comment by jdyer-draeger** [comment]
@ericstj It's the SDK that I'm interested in.  Clicking through on your link, the SDK is still at 8.0.3 while the rest of the "stuff" is 8.0.5

**Comment by Balkoth** [comment]
You are mixing SDK version which btw is `8.0.300` with .NET version.

So 8.0.300 is the latest SDK for .NET 8.0.5:
<img width="248" alt="image" src="https://github.com/dotnet/runtime/assets/80055480/6f99b29a-382c-4d51-b6f0-ed0ce6f34707">

**Comment by jdyer-draeger** [comment]
@Balkoth The issue I have is there is a fix I need that is in 8.0.4
So I need an SDK that's at least 8.0.4 or better still 8.0.5

I don't understand why the SDK versions are behind the regular releases.

**Comment by Balkoth** [comment]
Because they are not!

**Comment by colejohnson66** [comment]
The SDK version number's "patch level" has _no relation_ to the runtime version number's "patch level". They are different things, and you cannot compare them the way you are doing. Specifically, SDKs 8.0.105, 8.0.205, _and_ 8.0.300 are the SDKs for runtime 8.0.5.

**Comment by huoyaoyuan** [comment]
You can see more information about versioning at https://learn.microsoft.com/dotnet/core/versions/ .

BTW there will likely never be a 8.0.500 SDK. SDK currently is tied with Visual Studio which ships 4 feature updates a year. So the last SDK feature band will be 8.0.4xx. This has been true from .NET Core 3.1.

**Comment by danmoseley** [comment]
Closing as answered

**Comment by jdyer-draeger** [comment]
@huoyaoyuan Thanks for the link!
Looks like version 8 is still getting ramped up : )

*The .NET SDK, however, doesn't follow semantic versioning. The .NET SDK releases faster and its version numbers must communicate both the aligned runtime and the SDK's own minor and patch releases.*
