### ISSUE TITLE
CodeGen difference when manually extracting element to a local

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#102518]
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYm5JE1IMAKqoxDJeXDQDeNBg6a7mB4ihNnyACjYxsAEwB5LkkAT1kxbC4AHjAAC2woAD4GXABKBgBeJPtHPNwWWQxEjFwAdV4MOO8AcmwatI1qPNyHHT1Xd1NcDFIfPyCQ8MiY+MSU9Kyc5rzHAqKS8sq4vrqGppaZhwBtAFkYKoh/AElxSS99w5OzwLE+CC4CgEEAcxfYXFxeBRhjkN4uACXmkALqtJwdBjACAQSQMBZQUoVKrkaLGJJeKq8XAMXwBYJhCJRNETEZoEwMBTYSQcGAZADucRkMApIAYxwAogBHDjYYrAaQkgD84LsW1mvAAZgwvLgRiwADIwLgvKoMFJ0NLgvJi2Z6pgAdlSI22dBBQpY3N5klwXipNLpDCFQplEGAACsYGAMEK0vbaQxsQwuBxJJINvqAL7axzEI2S6m4GARhzR8XgvYHOJHU5ic6XbPXPO3e6PFivd6qL4/P6SAFA0Hg9ouKEwuEIpHLUgkzFxIN4waEkYk41RcnGSnU2kMpmwVnsq187ACmDC0UxhxSmVyqKK5WquLqhiajcMXX6vITjAwcRZUdcU0glMXw0Ma/iC2Lm12qeO52uj0vR9P1f0DHEQzDZ88jTC84wYBMbWTcE00jIA===)

```c#
public static void Test1(ReadOnlySpan<char> s) => s.StartsWith1('a');

public static void Test2(ReadOnlySpan<char> s) => s.StartsWith2('a');

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool StartsWith1<T>(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>?
{
    if (span.Length > 0)
    {
        return span[0]?.Equals(value) ?? (object?)value is null;
    }
    return false;
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool StartsWith2<T>(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>?
{
    if (span.Length > 0)
    {
        T temp = span[0];
        return temp?.Equals(value) ?? (object?)value is null;
    }
    return false;
}
```

```asm
TestClass.Test1(System.ReadOnlySpan`1<Char>)
    L0000: push rax
    L0001: mov rax, [rcx]
    L0004: mov ecx, [rcx+8]
    L0007: xor edx, edx
    L0009: mov [rsp+4], edx
    L000d: test ecx, ecx
    L000f: jle short L0019
    L0011: movzx eax, word ptr [rax]
    L0014: mov [rsp+4], ax
    L0019: add rsp, 8
    L001d: ret

TestClass.Test2(System.ReadOnlySpan`1<Char>)
    L0000: mov rax, [rcx]
    L0003: mov ecx, [rcx+8]
    L0006: test ecx, ecx
    L0008: jle short L000d
    L000a: cmp [rax], ax
    L000d: ret
```

Wasn't sure what to search for to look if there's an existing issue for this.

**Comment by jakobbotsch** [comment]
This is the same underlying problem as #87072 and #102273, where the IL takes the address of a local and leaves it live on the IL stack across control flow.
It's on my todo list to fix this for .NET 9.
