### ISSUE TITLE
Console.ReadKey() not picking up ConsoleModifiers when reading ConsoleKey.Backspace

### ISSUE THREAD

**Issue by MatsFischer** [dotnet/runtime#102511]
### Description

When using Console.ReadKey() the Modifiers property is not set correctly. When I press CTRL+u for example the key is recognized as U and the Modifier as Control. When I press CTRL+Backspace the key is recognized as Backspace but the Modifier is set to none.

### Reproduction Steps

I'm using .Net 8.0 on Windows 10 Pro (version 22H2) with IntelliJ Rider 2024.1.1.
I'm using the terminal built in with Rider.

The smallest Code Snippet showing this issue is the following:
```
ConsoleKeyInfo key = Console.ReadKey(true);
Console.Write(key.Modifiers + "+" + key.Key);
```

### Expected behavior

When I press CTRL+u the output in the console should be `Control+U`.
When I press CTRL+backspace the output in the console should be `Control+Backspace`.

### Actual behavior

When I press CTRL+u the output in the console is `Control+U`.
When I press CTRL+backspace the output in the console should be `None+Backspace`.

### Configuration

- .Net 8.0
- Windows 10 Pro (22H2)
- x64
- I'm not sure if it's specific but a similar issue has been raised in the past which I didn't want to resurrect (https://github.com/dotnet/runtime/issues/84668)

**Comment by mawosoft** [comment]
I'm not familiar with the Raider terminal, but it definitely is a terminal issue. The code snippet works just fine in a regular Windows Console.

With terminal implementations, the front end first translates native key events into a virtual terminal sequence. The backend then takes the VT sequence and synthesizes a key event. This only works for a subset of native key combos.
