### ISSUE TITLE
Enumerable.Except always creates a new hashset from the second argument

### ISSUE THREAD

**Issue by Meir017** [dotnet/runtime#102540]
### Description

consider the following code:
```cs
ISet<int> first = Enumerable.Range(0, 1000).ToHashSet();
ISet<int> second = Enumerable.Range(500, 1000).ToHashSet();
IEnumerable<int> except = first.Except(second);
```

### Regression?

No

### Analysis

Enumerable.Except -https://github.com/dotnet/runtime/blob/b8f554d1b834d71fe9028026a45761f857d8ad17/src/libraries/System.Linq/src/System/Linq/Except.cs#L81

I think this could be 
```cs
var set = comparer is null && second as ISet<TSource> ?? new HashSet<TSource>(second, comparer);
```

### Benchmark

// * Summary *

BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3593/23H2/2023Update/SunValley3)
11th Gen Intel Core i9-11950H 2.60GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.205
  [Host]     : .NET 8.0.5 (8.0.524.21615), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  DefaultJob : .NET 8.0.5 (8.0.524.21615), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

| Method                            | count   | Mean            | Error           | StdDev          | Median          | Allocated  |
|---------------------------------- |-------- |----------------:|----------------:|----------------:|----------------:|-----------:|
| EnumerableExceptCurrent           | 100     |      1,974.4 ns |        38.28 ns |        76.44 ns |      1,968.5 ns |     5848 B |
| EnumerableExceptNew               | 100     |        912.3 ns |        15.42 ns |        21.62 ns |        909.9 ns |      136 B |
| EnumerableExceptFrozenSet         | 100     |      2,020.4 ns |        18.18 ns |        16.12 ns |      2,018.9 ns |     2552 B |
| EnumerableExceptComparerCurrent   | 100     |      1,904.4 ns |        35.83 ns |        33.52 ns |      1,909.4 ns |     5848 B |
| EnumerableExceptComparerNew       | 100     |      1,249.8 ns |        24.26 ns |        34.01 ns |      1,244.6 ns |     1968 B |
| EnumerableExceptComparerFrozenSet | 100     |      2,048.2 ns |        40.10 ns |        52.14 ns |      2,050.6 ns |     2552 B |
| EnumerableExceptCurrent           | 10000   |    310,992.7 ns |     6,116.86 ns |    12,074.08 ns |    310,377.8 ns |   498365 B |
| EnumerableExceptNew               | 10000   |     91,039.8 ns |     1,709.02 ns |     1,828.64 ns |     90,624.4 ns |      136 B |
| EnumerableExceptFrozenSet         | 10000   |    200,844.4 ns |     2,676.33 ns |     2,372.50 ns |    200,567.7 ns |   208459 B |
| EnumerableExceptComparerCurrent   | 10000   |    309,712.4 ns |     6,169.56 ns |    12,602.78 ns |    307,080.1 ns |   498365 B |
| EnumerableExceptComparerNew       | 10000   |    164,056.8 ns |     3,128.44 ns |     6,800.98 ns |    162,050.4 ns |   161917 B |
| EnumerableExceptComparerFrozenSet | 10000   |    205,375.1 ns |     3,599.68 ns |     7,513.88 ns |    202,264.0 ns |   208459 B |
| EnumerableExceptCurrent           | 1000000 | 22,800,448.8 ns |   450,107.07 ns |   823,046.22 ns | 22,760,014.1 ns | 57180006 B |
| EnumerableExceptNew               | 1000000 |  9,630,900.5 ns |   190,697.57 ns |   434,314.87 ns |  9,607,377.3 ns |      142 B |
| EnumerableExceptFrozenSet         | 1000000 | 17,499,834.9 ns |   329,246.69 ns |   559,085.86 ns | 17,513,618.2 ns | 20073835 B |
| EnumerableExceptComparerCurrent   | 1000000 | 26,266,017.4 ns | 1,340,779.90 ns | 3,868,456.56 ns | 25,623,710.9 ns | 57179996 B |
| EnumerableExceptComparerNew       | 1000000 | 21,362,333.1 ns | 1,241,065.65 ns | 3,397,397.18 ns | 20,828,737.5 ns | 18603356 B |
| EnumerableExceptComparerFrozenSet | 1000000 | 25,438,711.8 ns |   963,092.55 ns | 2,824,583.73 ns | 24,772,477.8 ns | 20073850 B |

Benchmark code:

<details>

```cs
using System;
using System.Collections.Frozen;
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace MyBenchmarks;

[MemoryDiagnoser(false)]
public class EnumerableExcept
{
    [Params(100, 10000, 1000000)]
    public int count;

    private ISet<int> first;
    private ISet<int> second;

    [GlobalSetup]
    public void GlobalSetup()
    {
        first = Enumerable.Range(0, count).ToHashSet();
        second = Enumerable.Range(count / 2, count).ToHashSet();
    }

    [Benchmark]
    public int EnumerableExceptCurrent() => first.Except(second).Count();

    [Benchmark]
    public int EnumerableExceptNew() => MyEnumerable.Except(first, second).Count();

    [Benchmark]
    public int EnumerableExceptFrozenSet() => MyFrozenEnumerable.Except(first, second).Count();

    [Benchmark]
    public int EnumerableExceptComparerCurrent() => first.Except(second, EqualityComparer<int>.Default).Count();

    [Benchmark]
    public int EnumerableExceptComparerNew() => MyEnumerable.Except(first, second, EqualityComparer<int>.Default).Count();

    [Benchmark]
    public int EnumerableExceptComparerFrozenSet() => MyFrozenEnumerable.Except(first, second, EqualityComparer<int>.Default).Count();
}

public static class MyEnumerable
{

    public static IEnumerable<TSource> Except<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second)
    {
        ArgumentNullException.ThrowIfNull(first);
        ArgumentNullException.ThrowIfNull(second);

        return ExceptIterator(first, second, null);
    }

    public static IEnumerable<TSource> Except<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second, IEqualityComparer<TSource>? comparer)
    {
        ArgumentNullException.ThrowIfNull(first);
        ArgumentNullException.ThrowIfNull(second);

        return ExceptIterator(first, second, comparer);
    }

    private static IEnumerable<TSource> ExceptIterator<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second, IEqualityComparer<TSource>? comparer)
    {
        var secondSet = comparer is null ? second as ISet<TSource> ?? new HashSet<TSource>(second, comparer) : new HashSet<TSource>(second, comparer);
        foreach (var item in first)
        {
            if (!secondSet.Contains(item))
            {
                yield return item;
            }
        }
    }
}

public static class MyFrozenEnumerable
{

    public static IEnumerable<TSource> Except<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second)
    {
        ArgumentNullException.ThrowIfNull(first);
        ArgumentNullException.ThrowIfNull(second);

        return ExceptIterator(first, second, null);
    }

    public static IEnumerable<TSource> Except<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second, IEqualityComparer<TSource>? comparer)
    {
        ArgumentNullException.ThrowIfNull(first);
        ArgumentNullException.ThrowIfNull(second);

        return ExceptIterator(first, second, comparer);
    }

    private static IEnumerable<TSource> ExceptIterator<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second, IEqualityComparer<TSource>? comparer)
    {
        var secondSet = second.ToFrozenSet(comparer);
        foreach (var item in first)
        {
            if (!secondSet.Contains(item))
            {
                yield return item;
            }
        }
    }

    public static ISet<T> ToHashSet<T>(this IEnumerable<T> source)
    {
        return new HashSet<T>(source);
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        var summary = BenchmarkRunner.Run<EnumerableExcept>();
    }
}
```

</details>

**Comment by Meir017** [comment]
@huoyaoyuan one of the overloads doesn't require a compare (and passes null to the iterator method)

**Comment by En3Tho** [comment]
You can just reuse second anyway because it can be modified externally. You have to make a safe copy for a general api like this.

If allocations are a problem for you or your constraints are strictly defined then you should roll out your own helper

**Comment by Meir017** [comment]
@huoyaoyuan if we cannot re-use the ISet. 
I wonder if we can use FrozenSet, both allocation and performance are better with the FrozenSet

**Comment by eiriktsarpalis** [comment]
Even if `FrozenSet` provides better lookup performance, it is substantially more expensive to construct compared to `HashSet`. It is therefore not suitable for ephemeral uses like the implementation of `Except`.

I don't think there's any improvement we could make here that wouldn't break the invariants of `Except`. I would suggest not using Linq methods if you're trying to write a performance sensitive routine.
