### ISSUE TITLE
Add a good Binary Serializer

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/runtime#102535]
The BinaryFormatter is now marked as obsolete.  Though there are many Serializer like MessagePack and Protobuf. Each have its overhead and limitation when performing serialization. I would suggest the .NET team to look into MessagePack Serialization kind of implementation with support for polymorphic serialization and compression OOB. In case where there is possibility of UnSafe serialization that might happen, they can be shown as compiler warnings which developer can correct.

**Comment by huoyaoyuan** [comment]
> Though there are many Serializer like MessagePack and Protobuf. Each have its overhead and limitation when performing serialization.

They are just "good" serializers. The limitations are something you must pay for.

> support for polymorphic serialization

This is where danger comes.

> compression OOB

This is another layer that can be done separately. It will definitely harm performance for real cases. If you data can reach the size to benefit from compression, you should probably use database-like solutions.

The overhead of MessagePack and Protobuf-like serializers are close to minimal for making a "correct" serializer. Dumping memory blocks is fundamentally incorrect for persisted storage.

**Comment by Clockwork-Muse** [comment]
`BinaryFormatter` wasn't necessarily a more-performant serializer, and there's nothing inherently more performant about how it worked compared to third-party packages.  The fundamental unsafety was unrelated to performance (and entirely due to how it worked generally).

**Comment by neon-sunset** [comment]
Not everything has to live in CoreLib or extension packages of .NET itself. Binary serialization is a perfect example of specialized solution that is best served by standalone libraries. Besides MessagePack, there are multiple performant binary serde packages for .NET like MemoryPack.

**Comment by VenkateshSrini** [comment]
> > Though there are many Serializer like MessagePack and Protobuf. Each have its overhead and limitation when performing serialization.
> 
> They are just "good" serializers. The limitations are something you must pay for.
> 
> > support for polymorphic serialization
> 
> This is where danger comes.
> 
> > compression OOB
> 
> This is another layer that can be done separately. It will definitely harm performance for real cases. If you data can reach the size to benefit from compression, you should probably use database-like solutions.
> 
> The overhead of MessagePack and Protobuf-like serializers are close to minimal for making a "correct" serializer. Dumping memory blocks is fundamentally incorrect for persisted storage.

So can we build and provide the developers that will have less overheads and features like Polymorphic serialization and handle at least 95% of scenario and also provide a way to extend the functionality in case of some custom serialization is required

**Comment by VenkateshSrini** [comment]
> Not everything has to live in CoreLib or extension packages of .NET itself. Binary serialization is a perfect example of specialized solution that is best served by standalone libraries. Besides MessagePack, there are multiple performant binary serde packages for .NET like MemoryPack.

Is there some kind of library that we can act as a adapter for some best serialization libraries like Memory Pack, Message Pack, protobuf and other serializers? Something like EF, where we can define what we want to do in Library agnostic way, then choose a plug in library for popular serializer like Message Pack, Memory Pack, Protobuf etc. We would prefer not to add any attribute or implement any interface to existing classes. It should consume the class as it is. Is this at least good thought? Idea is to switch between libraries seamlessly

**Comment by VenkateshSrini** [comment]
> Not everything has to live in CoreLib or extension packages of .NET itself. Binary serialization is a perfect example of specialized solution that is best served by standalone libraries. Besides MessagePack, there are multiple performant binary serde packages for .NET like MemoryPack.

Is there some kind of library that we can act as a adapter for some best serialization libraries like Memory Pack, Message Pack, protobuf and other serializers? Something like EF, where we can define what we want to do in Library agnostic way, then choose a plug in library for popular serializer like Message Pack, Memory Pack, Protobuf etc: We would prefer not add any attribute or implement any interface to existing classes

**Comment by VenkateshSrini** [comment]
But then if we have a standard way of defining things and then have the underlying l

> > Is there some kind of library that we can act as a adapter for some best serialization libraries like Memory Pack, Message Pack, protobuf and other serializers? Something like EF, where we can define what we want to do in Library agnostic way
> 
> The was a very old `DataContractSerializer` that tries to adapt Xml and Json. It's considered a failure because the difference of Xml and Json are too significant. EF is mostly for relational databases, which have many similarity. I'm not an expert about the binary formats, but generally I'm pessimistic about this.

Help define what needs to be done in a common way and then have underlying library handle this is one way. It could be line what we are doing with IMessageFormatters. I'm not saying this is easy. Also, The community that supports this libraries should also come together to have such contracts

**Comment by GrabYourPitchforks** [comment]
IMO this issue is not actionable as written and should be closed. Other commenters have already given context as to why MemoryPack-like libraries are not appropriate for general purpose serialization, why attempts to add general purpose serialization interfaces have failed, and what other libraries exist in the ecosystem to fulfill this scenario. All aspects of OP's original question and follow-ups appear to have been resolved.

**Comment by koszeggy** [comment]
@VenkateshSrini: though [this one](https://github.com/koszeggy/KGySoft.CoreLibraries?tab=readme-ov-file#binary-serialization) is also just a 3rd party library ([NuGet](https://www.nuget.org/packages/KGySoft.CoreLibraries)), you can have a look at it, especially if you need `IFormatter` compatibility (disclaimer: I'm the author). Please note though that in safe mode (which is enabled by default) this compatibility is quite limited: no custom binders or serialization surrogates are allowed, and every custom type (basically every type that that is stored by assembly qualified name in the stream to support polymorphism) must be specified as expected types in the deserialization methods. See more details at the security notes at the **Remarks** section of the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm) class.

**Comment by VenkateshSrini** [comment]
> @VenkateshSrini: though [this one](https://github.com/koszeggy/KGySoft.CoreLibraries?tab=readme-ov-file#binary-serialization) is also just a 3rd party library ([NuGet](https://www.nuget.org/packages/KGySoft.CoreLibraries)), you can have a look at it, especially if you need `IFormatter` compatibility (disclaimer: I'm the author). Please note though that in safe mode (which is enabled by default) this compatibility is quite limited: no custom binders or serialization surrogates are allowed, and every custom type (basically every type that that is stored by assembly qualified name in the stream to support polymorphism) must be specified as expected types in the deserialization methods. See more details at the security notes at the **Remarks** section of the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm) class.

I'm asking exactly these capabilities. Can .NET team take this and implement
