### ISSUE TITLE
[API Proposal]: Adding DisposeAsync to HttpResponseMessage and HttpContent

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#102571]
### Background and motivation

The motivation for proposing the addition of `DisposeAsync` to `HttpResponseMessage` and `HttpContent` stems from the need to address performance issues related to the disposal of HTTP connections, particularly in the context of HTTP/3. The current implementation of synchronous disposal via `Dispose` can lead to [sync-over-async](https://github.com/dotnet/runtime/blob/994a410b4478eef496bd230f6d95f576d4aff6d7/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.Stream.cs#L222) scenarios deep within the `QuicStream`, which is not ideal.

The problem is exemplified by the issue reported on GitHub (#77139), where the shutdown of HTTP/3 connections or streams was observed to be slow, significantly affecting performance metrics such as requests per second (RPS). This issue highlights the impact of the current disposal pattern on performance, especially in high-throughput scenarios.

By introducing `DisposeAsync`, we aim to provide a more efficient way to dispose of these objects, particularly when dealing with asynchronous streams. This change would allow for asynchronous cleanup operations, which are more aligned with the nature of asynchronous programming and can help avoid the aforementioned performance pitfalls.

The addition of `DisposeAsync` would enable a more performant and reliable disposal mechanism, ensuring that resources are freed in a timely and non-blocking manner.

In conclusion, the proposal to add `DisposeAsync` is driven by a clear need to improve the performance and reliability of HTTP connection disposal, as evidenced by real-world issues and internal analysis. This change would bring the disposal pattern in line with modern asynchronous programming practices, benefiting developers and end-users alike with more efficient resource management and better application performance.

/cc @ManickaP 

### API Proposal

```diff
namespace System.Net.Http;

-public class HttpResponseMessage : IDisposable
+public class HttpResponseMessage : IDisposable, IAsyncDisposable
{
    public void Dispose();
+   public ValueTask DisposeAsync();
+   protected virtual ValueTask DisposeAsyncCore();
}

-public abstract class HttpContent: IDisposable
+public abstract class HttpContent: IDisposable, IAsyncDisposable
{
    public void Dispose();
+   public ValueTask DisposeAsync();
+   protected virtual ValueTask DisposeAsyncCore();
}
```
 

### API Usage

```csharp
HttpClient client = new(...);
await using HttpResponseMessage message = await client.GetAsync(...);
await using Stream responseStream = await message.Content.ReadAsStreamAsync();
```

or 

```csharp
HttpClient client = new(...);
HttpResponseMessage message = await client.GetAsync(...);
// Do something
_ = message.DisposeAsync();
```

### Alternative Designs

TODO

### Risks

TODO

**Comment by stephentoub** [comment]
What is it that a response QuicStream needs to do as part of disposal that is asynchronous?

**Comment by stephentoub** [comment]
> > What is it that a response QuicStream needs to do as part of disposal that is asynchronous?
> 
> `QuicStream.DisposeAsync()` waits for [`SHUTDOWN_COMPLETE` event](https://github.com/dotnet/runtime/blob/b83186a969946f61c71ad0da034936fac9947752/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs#L730)

The resources it's referring to, that's the freeing of the handle? Can the freeing of that handle be done fire-and-forget from the perspective of the stream such that neither Dispose / DisposeAsync needs to wait for the ack? Connection cleanup could be responsible for ensuring any stream handles that are still being cleaned up are freed prior to the connection handle being cleaned up.

**Comment by wfurt** [comment]
Since `HttpWebRequest`  I'm wondering if we should block HTTP/3 here.  It feels like with the current layering it would be _really_ hard to use the stream multiplexing effectively.

**Comment by ManickaP** [comment]
@stephentoub It's not just about freeing the handle. Writing data to the stream is just copying them to MsQuic internal buffer (same as with sockets). The problem is that MsQuic is user space, so after app closure, everything that hasn't been flushed to the network is lost (e.g. https://github.com/microsoft/msquic/issues/3842). On top of that, many applications do not dispose `HttpClient` (neither the gRPC benchmarks used the linked issue, neither would the proposal of `HttpClient.Shared`, ...). So no connection disposal to wait for the pending stream disposal. In extremis, this could lead to lost data.

**Comment by liveans** [comment]
As we have a good solution to the perf problem now, we decided to close this.
