### ISSUE TITLE
Assert failure(PID 1640 [0x00000668], Thread: 19388 [0x4bbc]): x > base

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#102585]
This fails occassionally on the [plug](https://github.com/dotnet/runtime/blob/main/src/tests/GC/Features/HeapExpansion/plug.cs) test case with DATAS turned on.

```
Assert failure(PID 1640 [0x00000668], Thread: 19388 [0x4bbc]): x > base

CORECLR! SVR::gc_heap::calculate_new_heap_count + 0xB70 (0x00007ffe`27d00590)
CORECLR! SVR::gc_heap::update_end_gc_time_per_heap + 0x298 (0x00007ffe`27d364d8)
CORECLR! SVR::gc_heap::gc1 + 0x155C (0x00007ffe`27d12aac)
CORECLR! SVR::gc_heap::garbage_collect + 0x99E (0x00007ffe`27d114fe)
CORECLR! SVR::gc_heap::gc_thread_function + 0x580 (0x00007ffe`27d13170)
CORECLR! SVR::gc_heap::gc_thread_stub + 0x7E (0x00007ffe`27d1358e)
CORECLR! <lambda_c106ffbf81d302a6ee5c9510e81a6997>::<lambda_invoker_cdecl> + 0x74 (0x00007ffe`279dd0a4)
KERNEL32! BaseThreadInitThunk + 0x1D (0x00007ffe`b52d257d)
NTDLL! RtlUserThreadStart + 0x28 (0x00007ffe`b664aa48)
    File: C:\dev\runtime\src\coreclr\gc\gc.cpp:25235
    Image: C:\dev\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe
```

Configuration: DevBox, Windows, x64, chk, datas

**Comment by mangod9** [comment]
Is this a recent failure or has this been seen before?

**Comment by cshung** [comment]
> Is this a recent failure or has this been seen before?

I just noticed it.

**Comment by mangod9** [comment]
Ok, could be related to recent change from @Maoni0

**Comment by cshung** [comment]
> Ok, could be related to recent change from @Maoni0

Probably not, it was ran on a commit before her changes.

It looks like the problem has to do with this math.

`log_with_base ((smoothed_median_throughput_cost_percent - target_tcp), log_base)`

The implementation of `log_with_base` asserts that `x` must be greater than `base`.

It looks like `x` is derived from measurement, so it could be really close to `target_tcp` to the point that it is less than `log_base`, and so it will fail.

**Comment by mangod9** [comment]
Ok then guessing it might not be relevant again. We can leave it open but if we don't hit it again in the next week or so can get it closed.

**Comment by Maoni0** [comment]
somehow I never got notified.. this code is no longer in use so we can ignore this. thanks!
