### ISSUE TITLE
Ios Maui sample app uses Chinese Simplified when Chinese Traditional is set in phone preferences

### ISSUE THREAD

**Issue by Czapek83** [dotnet/runtime#102560]
### Description

Created new maui project. Created Strings.resx, Strings.zh.resx, Strings.zh-Hans.resx, and Strings.zh-Hant.resx files with below values of SampleText:
![image](https://github.com/dotnet/maui/assets/11677674/398a7ba0-b16f-4d52-bb9a-97008af50144)

On MainPage.xaml added label that will display proper text according to current language:
![image](https://github.com/dotnet/maui/assets/11677674/46413552-15c7-454e-a3dd-3fb11c4355bc)

And now, when setting Iphone Region to "China mainland" and language to "Chinese Traditional", the SampleText is taken from Chinese, Simplified, but should be taken from Chinese, Traditional:
![image](https://github.com/dotnet/maui/assets/11677674/5e86213e-8714-4c4a-8cd7-efba74c2b7d7)

### Steps to Reproduce

1. Create new maui project.
2. Create localized strings in Resources (Strings.zh-Hans.resx for Chinese Simplified and Strings.zh-Hant for Chinese Traditional) with different strings in it.
3. Use localized string in one of your screens
4. Change your Iphone region to "China mainland" and language to "Chinese Traditional".
5. Run your application and you can see that Chinese Simplified string is used.

### Link to public reproduction project repository

https://github.com/Czapek83/Chinese_LanguageIssue

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.7.7, IOS 17.4.1

### Did you find any workaround?

Unfortunatelly, not at all.

**Comment by tarekgh** [comment]
CC @steveisok

**Comment by matouskozak** [comment]
Can confirm that the issue is reproducible with .NET 8. Works as expected with .NET 9.

**Comment by lewing** [comment]
Is the issue how we construct the icu locale in net8.0 or the fact that we've potentially removed the required information from the icu bundle we produce for size reasons?

**Comment by matouskozak** [comment]
> Is the issue how we construct the icu locale in net8.0 or the fact that we've potentially removed the required information from the icu bundle we produce for size reasons?

I'm unsure, I have thought that we have full ICU when hybrid globalization is not enabled on .NET 8 (do you know @mkhamoyan ?).

I did some digging and the correct language can be set using `[[NSLocale preferredLanguages] objectAtIndex:0]` (returns expected `zh-Hant-CN`).

**Comment by mkhamoyan** [comment]
@matouskozak We have whitelisted locales for ICU in net8.0 https://github.com/dotnet/icu/blob/dotnet/main/icu-filters/icudt_mobile.json#L8-L194 and I don't see here `zh-Hant_CN`.
For hybrid mode we do get default locale using `preferedLanguages` as you mentioned https://github.com/dotnet/runtime/blob/994a410b4478eef496bd230f6d95f576d4aff6d7/src/native/libs/System.Globalization.Native/pal_locale.m#L795

**Comment by sowacx** [comment]
Hey, this:
> For hybrid mode we do get default locale using `preferedLanguages` as you mentioned

Is applied only if there are more than 1 preferedLanguages selected. For single one it can be still evaluated as
` localeName = [NSString stringWithFormat:@"%@-%@", currentLocale.languageCode, currentLocale.countryCode];
`
