### ISSUE TITLE
`LibraryImport` do not copy `this`

### ISSUE THREAD

**Issue by MrScautHD** [dotnet/runtime#102690]
### Description

Hello, i tried to make extensions methods for my project and as i tried doing `this` it gave me a compile error.
![grafik](https://github.com/dotnet/runtime/assets/65916181/657e227c-5469-493a-b9e6-6afca6907412)

There is no `this` in the generated code:
![grafik](https://github.com/dotnet/runtime/assets/65916181/30968632-7a95-48f2-9ba3-ea4e4a34923c)

It told me:
![grafik](https://github.com/dotnet/runtime/assets/65916181/118d1c24-7ea2-4740-a0bb-57d878720166)
`0>LibraryImports.g.cs(1075,72): Error CS0755 : Both partial method declarations must be extension methods, or neither can be an extension method.`

### Reproduction Steps

Here is a small example:

```cs
public static partial class Camera3DExtensions {

    /// <summary>
    /// Update camera position for selected mode.
    /// </summary>
    /// <param name="camera">The camera to update.</param>
    /// <param name="mode">The camera mode.</param>
    [LibraryImport(Raylib.Name, EntryPoint = "UpdateCamera")]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void Update(this ref Camera3D camera, CameraMode mode);
}
```

### Expected behavior

No compile error.

### Actual behavior

![grafik](https://github.com/dotnet/runtime/assets/65916181/118d1c24-7ea2-4740-a0bb-57d878720166)

**Comment by AaronRobinsonMSFT** [comment]
@MrScautHD Thanks for asking about this. Does a workaround of creating a `private static` method for the `LibraryImport` and then calling that in the extension method work? I realize the expectation here is to propogate the `this`, but can you confirm if that workaround unblocks you please.

@jkoritzinsky and @jtschuster I assume all we need to do here is propogate the `this` keyword. I can't think of any real issue with providing this support but I avoid extension methods. Any concerns?

**Comment by MrScautHD** [comment]
> @MrScautHD Thanks for asking about this. Does a workaround of creating a `private static` method for the `LibraryImport` and then calling that in the extension method work? I realize the expectation here is to propogate the `this`, but can you confirm if that workaround unblocks you please.
> 
> @jkoritzinsky and @jtschuster I assume all we need to do here is propogate the `this` keyword. I can't think of any real issue with providing this support but I avoid extension methods. Any concerns?

Yes, I can confirm that the problem is resolved by implementing a new method that calls the LibraryImport function.
![grafik](https://github.com/dotnet/runtime/assets/65916181/62670731-0b8e-4d77-9992-e73351e38caf)

**Comment by jtschuster** [comment]
> I assume all we need to do here is propogate the this keyword. I can't think of any real issue with providing this support but I avoid extension methods. Any concerns?

I can't think of any concerns off the top of my head. It looks like Roslyn has no issues making `DllImport`s extension methods, so I imagine `LibraryImport` should support it too.

**Comment by AaronRobinsonMSFT** [comment]
>  It looks like Roslyn has no issues making DllImports extension methods, so I imagine LibraryImport should support it too.

@jtschuster Okay. I'll mark this for .NET 9. Interested in taking it on? If not, I assume one of us can handle this before we ship, seem like a simple change.

**Comment by jtschuster** [comment]
Yeah, I can take this one
