### ISSUE TITLE
Enable test signing during PR validation jobs

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1026]
In Core-Setup, PR validation ran test signing. This ensured new changes don't break the signing infrastructure in a fundamental way. It was removed in https://github.com/dotnet/runtime/pull/1016 to unblock official builds.

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/installer/jobs/base-job.yml#L57-L62

**Comment by ViktorHofer** [comment]
Why does signing depend on the UCRT redist files?

**Comment by dagood** [comment]
Someone who knows why CoreCLR needs to sign it would need to answer that. The config in question:

https://github.com/dotnet/runtime/blob/516956a01fee9aa732b199012a6ea0bcc2bd789f/eng/Signing.props#L53-L56

**Comment by dagood** [comment]
I'm not sure what the behavior of that DLL is in general--if it's only packed up in Release builds (so the condition just needs to work right?), if we could enable it in Debug builds, if there's some root issue that could be sorted out....  It's possible it's not hard, I didn't look into it other than filing this tracking issue since it wasn't the priority. Best first step IMO is seeing what happens.

/cc @NikolaMilosavljevic

**Comment by ViktorHofer** [comment]
Thanks, assigning to myself to look further.

**Comment by ViktorHofer** [comment]
cc @janvorli @trylek, why do we only produce that files in Releas? Tomas mentioned it might already be obsolete?

**Comment by trylek** [comment]
I found a commit that seems related:

https://github.com/dotnet/coreclr/commit/557c8f0078b01a220077f02bc703c4a16c3e4e41

@mmitche - is there any harm in executing the CopyUcrtFiles target even in debug mode so that we can test signing in PR runs?

**Comment by trylek** [comment]
@ViktorHofer / @dagood - does there exist any private branch or PR enabling signing in debug builds so that I could give it a try in combination with the fix for CopyUcrtFiles?

**Comment by mmitche** [comment]
@mmitche - is there any harm in executing the CopyUcrtFiles target even in debug mode so that we can test signing in PR runs?

No idea.

**Comment by dagood** [comment]
> does there exist any private branch

Not that I'm aware of. To get started, just changing the lines called out above will kick it off:

```yml
- name: SignType
  value: test
```
