### ISSUE TITLE
Make System.DirectoryServices.DirectorySearcher cross-plattform (Linux/macOS support)

### ISSUE THREAD

**Issue by rklec** [dotnet/runtime#102601]
### Description

In https://github.com/dotnet/runtime/issues/14734 support for Windows has been added, in https://github.com/dotnet/runtime/issues/23944#issuecomment-625485513  / https://github.com/dotnet/runtime/pull/35380 Linux support for `System.DirectoryServices.Protocols` has been added.

https://github.com/dotnet/runtime/issues/84831 and https://github.com/dotnet/runtime/issues/37100 tracks related progress for making `System.DirectoryServices.AccountManagement` cross-plattform.

_However_, I'd really only like to use `DirectorySearcher` to simplify search the AD/LDAP for users. 

### Reproduction Steps

[There are other simple wrappers around `System.DirectoryServices.Protocols`](https://codereview.stackexchange.com/questions/158821/ldap-search-helper-for-system-directoryservices-protocols) that already work and are the only cross-platform alternative. Or [`LinqToLdap`](https://github.com/madhatter22/LinqToLdap), which unfortunately does not seem to be maintained anymore, ([but is recommend by OWASP](https://cheatsheetseries.owasp.org/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.html#safe-net-example))

### Expected behavior

Support that wrapper around LDAP just for searching on Linux/macOS, too.

### Actual behavior

When importing it, I get [error `CA1416`](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416).

[The doc also confirms](https://learn.microsoft.com/en-US/dotnet/api/system.directoryservices.directorysearcher?view=net-8.0#applies-to) this it "applies to" Windows Desktop (only), compared with [`System.DirectoryServices.Protocols.DirectoryRequest.SearchRequest`](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.searchrequest?view=net-8.0#applies-to), which applies to all .NET versions.

### Known Workarounds

Use wrapper linked above.

### Other information

https://github.com/dotnet/runtime/issues/25121 is also about this issue.

**Comment by steveharter** [comment]
> [`System.DirectoryServices.Protocols.DirectoryRequest.SearchRequest`](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.searchrequest?view=net-8.0#applies-to), which applies to all .NET versions.

Yes that assembly is cross-platform.

Can you use that cross-plaform `SearchRequest` class from there instead of the Windows-only `DirectorySearcher` for your LDAP scenarios? What functionality is missing?

**Comment by rklec** [comment]
Well... there is a reason `DirectorySearcher` as a wrapper exists for `SearchRequest`, is not it? 

E.g. I then found [LinqToLdap](https://github.com/madhatter22/LinqToLdap), which [also wraps around SearchRequest](https://github.com/search?q=repo%3Amadhatter22%2FLinqToLdap%20SearchRequest&type=code), but e.g. amends it with features like:
* paginated queries (AFAIK [`DirectorySearcher` supports paging](https://github.com/madhatter22/LinqToLdap/wiki/Paging) this is kinda sad.) without needing to (re-)implement all that cookie stuff/handling

Also, it supports more features than `DirectorySearcher`, like:
* [preventing LDAP injection through proper filter escape](https://cheatsheetseries.owasp.org/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.html#safe-net-example) 
* mapping results directly to models

**Comment by steveharter** [comment]
Pinging consultants @BRDPM @grubioe @jay98014. What is the feasibility of making this cross-plat?

**Comment by buyaa-n** [comment]
Also ping @joperezr for input

**Comment by joperezr** [comment]
It's been a while since I looked at it so this is very outdated, but IIRC the assembly (as I didn't just look at this type specifically) had a lot of windows-specific concepts which would make it hard/impossible or maybe just misleading to have it be cross platform. For instance, some of the APIs were leaking COM objects. We picked `System.DirectoryServices.Protocols` as the one to make cross platform as that one, on the other hand, had basically no windows-specific concepts and instead is essentially just a managed layer on top of the ldap protocol itself. For the request here, I agree with Steve and I would expect the existing API should be sufficient for most if not all use cases, as after all it is just a layer lower in the stack. In the framework we have a lot of cases where you can achieve the same thing via multiple ways, and in terms of ActiveDirectory management that's the same, were one is lower in the stack and more down to the protocol, whereas DirectorySearcher is just a higher level abstraction that makes it more user friendly

**Comment by khellang** [comment]
> Well... there is a reason DirectorySearcher as a wrapper exists for SearchRequest, is not it?

`DirectorySearcher` is not a wrapper for `SearchRequest`. `System.DirectoryServices.Protocols` is an entirely different thing that operates on the protocol level and share very little code with `System.DirectoryServices` and `System.DirectoryServices.AccountManagement` (which are both based on COM and ADSI). Here's an old image floating around the internets showing the layering:

![image](https://github.com/dotnet/runtime/assets/582487/a4cd2882-178d-4530-bbdb-6a1a19eb8f21)

Of course, it might (or might not) be possible to re-implement `DirectorySearcher` on top of `SearchRequest`, but it's probably Very Hard™ and would probably break a lot of Windows-isms.

**Comment by steveharter** [comment]
Closing; not planned \ feasible.

**Comment by rklec** [comment]
Then what about adding support for paging [and possibly other features I currently miss](https://github.com/dotnet/runtime/issues/102601#issuecomment-2144812624) or so in `SearchRequest` or a new API using this? Or should I open a new issue for that?

**Comment by khellang** [comment]
> Then what about adding support for paging [and possibly other features I currently miss](https://github.com/dotnet/runtime/issues/102601#issuecomment-2144812624) (which are not platform-dependent) or so in `SearchRequest` or a new API using this?

Sounds like a nice opportunity for an open-source project 😄

**Comment by rklec** [comment]
> an open-source project 😄

...like .NET runtime 😉
