### ISSUE TITLE
System.Collections.Generic.List<T> constructor overload for initializing with pre-determined "size"

### ISSUE THREAD

**Issue by YashojaLakmith** [dotnet/runtime#102662]
### Background and motivation

The `List<T>` has a constructor overload for providing a pre-determined capacity. But it only internally allocates that capacity for the backing array while the `List<T>.Count` property and `_size` field remains 0. There is no way to directly initialize a `List<T>` with a given "**size**".

E.g:
```csharp
var integers = new List<int>(5);
integers[4] = 10;   // Invalid
```

### API Proposal

```csharp
namespace System.Collections.Generic;

public class List<T> : IList<T>, IList, IReadOnlyList<T>
{
    ....
    public List(int capacity, bool initializeElements = false)    // If initialize is true, elements within the allocated range will be initialized to default and accessible.
    {
        ...
    }
}
```

### API Usage

```csharp
// Initialize our list with initialize parameter set to true
var integers = new List<int>(5, true);

// Elements within the allocated size are available to access.
// Prints 0 as list items have been initialized to the default of the int
Console.WriteLine(integers[4]);

// Initialize the list with initialize parameter set to false (or false as its default value if unspecified)
integers = new List<int>(5);

// Accessing elements within the allocated capacity is invalid .
Console.WriteLine(integers[4]);    
```

### Risks

Should be none. Since the `initializeElements` parameter will be defaulted to `false` if unspecified, existing usages of `List<T>(int capacity)` constructor will not be affected.

**Comment by JakeYallop** [comment]
[`CollectionsMarshal.SetCount`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal.setcount?view=net-8.0) can be used to achieve this.

**Comment by huoyaoyuan** [comment]
The array-like is not friendly with nullability.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  Thanks!

**Comment by YashojaLakmith** [comment]
@JakeYallop though it is simple and straightforward to just do it during the initialization.

**Comment by YashojaLakmith** [comment]
@huoyaoyuan the developer is supposed to know that first x elements in the list are `null` after he called `new List<T>(x, true)` and `T` is a non-nullable type.

**Comment by tannergooding** [comment]
As others have indicated, this is already trivially possible using the `CollectionsMarshal.SetCount` API.

It is a very advanced scenario that is really oriented around very specific perf oriented cases and comes with several nuances that need to be considered, so using the hidden away/unsafe API seems like the right choice and it does not seem correct to expose this as a general purpose constructor directly on the type.
