### ISSUE TITLE
[API Proposal]: Add byte[] support in System.Text.Json

### ISSUE THREAD

**Issue by MicahKimel** [dotnet/runtime#102626]
### Background and motivation

If I understand correctly .net8 is stopping support for the following `services.AddMvc().AddNewtonsoftJson()` and moving to `System.Text.Json` for better security and control. I currently use NewtonsoftJson on many apis for mobile devices where I pass large objects as byte[] objects within the json object. This is not supported by `System.Text.Json`. Adding support for `byte[]` would improve efficiency, speed, and simplify code when working with large data such as images and documents.

### API Proposal

```csharp
// Update to add byte[] support
namespace System.Text.Json;

```

### API Usage

```csharp

public class ByteData
{
     public byte[] data { get; set; }
}

// Ability to use class with a byte[] object in json post
[HttpPost("PostByteData")]
public async Task<object> PostByteData(ByteData byteDoc)
{
     // Do something with byte[] data
}
```

### Alternative Designs

Maybe another type could be created like `System.Text.JsonByte` that has support for `byte[]`

### Risks

If developers use byte[] within a json object and do further derealization using a 3rd party tools it could potentially lead to derealization security vulnerabilities.

**Comment by gregsdennis** [comment]
How do you propose `byte[]` be encoded into JSON?

**Comment by eiriktsarpalis** [comment]
`byte[]` is already supported today and serializes to Base64 encoded strings. Are you proposing that we change this to serialize as an array of integers?

**Comment by MicahKimel** [comment]
@eiriktsarpalis Thanks, yeah I noticed it worked as a Base64 string. I was hopping to also get integer array support for byte[] since it's faster and more efficient with larger data. I can just use an integer array and then convert it into a byte array once received by my endpoint.

**Comment by gregsdennis** [comment]
> it's faster and more efficient

I'm not sure of this.  You save the encode/decide time, but JSON-encoded integer array will be significantly larger than a base 64 string, which will require more storage and will take longer to transmit.

**Comment by MicahKimel** [comment]
@gregsdennis I thought sending base64 string over http is around [30%](https://stackoverflow.com/questions/41315553/why-use-base64) larger than sending the raw integer array since it's more complex string using ASCII encoding than just using the raw bytes. I've never used sharplab, and likely I don't have this quite right, but here's an attempt to show how serialize doesn't work with byte[] int object within another object. [testCase](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AFQFMAPYMgKQGcB7KAbj0JMwBZPcAGQCWTYAB5gVMQD4icAIbAFIsUQC8RKFQDuRVRKmy8AbzxEtuokeBETRYXA1FMMIgCMAnkefa9XqQBtAF07Fzd0NwBmIgBfOJhzSz0bMMdnSI9vaV8rAKoQsN43AFY3ADY4uLxYgVJiACtWKABlYDBhKABzZ2Y2FqoOhQAbYQAvQbIBodGJgApFZQMASjrMAE45pv72zq7VvC50a2lgM1wLC1QYzttHAUuSGPzC/KYBWMPcIA)

**Comment by MicahKimel** [comment]
@MihaZupan Ok, I'll migrate from raw bytes to base64 strings I guess

**Comment by MicahKimel** [comment]
Thanks @kasperk81 that’s perfect!

**Comment by MihaZupan** [comment]
I was curious just how bad that'd be perf-wise ...

| Method              | BytesLength | Mean         | Error     | StdDev    | Allocated |
|-------------------- |------------ |-------------:|----------:|----------:|----------:|
| SerializeBase64     | 1048576     |     86.53 us |  0.423 us |  0.395 us |         - |
| DeserializeBase64   | 1048576     |    376.65 us |  1.203 us |  1.067 us | 1048642 B |
| SerializeIntArray   | 1048576     | 12,257.76 us | 37.181 us | 34.779 us |         - |
| DeserializeIntArray | 1048576     | 27,556.91 us | 84.104 us | 65.663 us | 3146328 B |

**Comment by MicahKimel** [comment]
@MihaZupan Wow I had no idea SerializeBase64 was so much faster than decimal, I've had this all very wrong. Thank you very much for correcting me on this!!

**Comment by colejohnson66** [comment]
Base64 is extremely fast because it can be accomplished in parallel through SIMD. Roughly, it treats 3-tuples of bytes as a 24-bit integer, does some bit shift swizzling, then spits out four bytes. As such, the output size can be computed from the input size - given `x` bytes, you get `ceiling(4x/3)` bytes in the output, *and* you know where each input byte will go.

Writing integers, on the other hand, is much harder because they can vary in length from one to three digits/bytes. Even if done in parallel, the logic to pack the results would, most likely, be very sequential. In addition, the output size can’t be know from just the input. Given `x` input bytes, the output size will be anywhere from `3x-1` to `5x-1` bytes.
