### ISSUE TITLE
ILLink: Trimmer and NativeAOT do not consider DoesNotReturnAttribute for diagnostics

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#102677]
```C#
// Trimmer/NativeAot don't optimize branches away based on DoesNotReturnIfAttribute
[ExpectedWarning ("IL2026", nameof (RequiresUnreferencedCode), Tool.Trimmer | Tool.NativeAot, "")]
static void GuardedAssert ()
{
	Debug.Assert (TestFeatures.IsUnreferencedCodeSupported);
	RequiresUnreferencedCode ();
}
```

This code should not warn because the parameter of `Debug.Assert` is marked `DoesNotReturnIf(false)`, and `TestFeatures.IsUnreferencedCodeSupported` is stubbed to `false`.

**Comment by MichalStrehovsky** [comment]
Is the intention to make the analyzer ignore that attribute as well?

(I don't think we'd want illink/aot to understand this attribute. The attribute doesn't mean anything in IL and as long as it means nothing in places like RyuJIT, it should also mean nothing in illink/aot.)

**Comment by jtschuster** [comment]
We probably shouldn't consider it for branch trimming, but I do think it makes sense for diagnostics. The docs for [DoesNotReturnIfAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnifattribute.parametervalue?view=net-8.0) say `Code after the method is considered unreachable by diagnostics if the argument to the associated parameter matches this value`, so I think the ideal behavior would be to treat the code after it the same as having warning suppressions.

I'll reword the title to scope it to diagnostics, not branch trimming.

cc @dotnet/illink any thoughts?
