### ISSUE TITLE
Include WinForms trimming feature switch information

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#102619]
The feature switches related to [WinForms trimming](https://github.com/dotnet/winforms/issues/10813) that are not yet defined in runtime trimming should be updated on a relevant WinForms target file or at [Microsoft.NET.ILLink.targets](https://github.com/dotnet/runtime/blob/7fdc74eb68a75c98c8797fc9c58878c05e128316/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets#L30) and [documented](https://github.com/dotnet/runtime/blob/7fdc74eb68a75c98c8797fc9c58878c05e128316/docs/workflow/trimming/feature-switches.md).

**Comment by MichalStrehovsky** [comment]
These would ideally be in WinForms-specific .targets. The feature switches we keep in the ILLink targets are specific to dotnet/runtime repo. We don't e.g. define feature switches for ASP.NET in this file. (Might want to move the issue to WinForms.)
