### ISSUE TITLE
any limitations on EventCounters on Linux?

### ISSUE THREAD

**Issue by kykwo** [dotnet/runtime#102629]
Hello, we use EventCounters to monitor dotnet performance counters on Linux, but I noticed that it does not collect counters for all dotnet processes that are currently running. Is there any limitation of EventCounters on Linux that I'm missing?

**Comment by hoyosjs** [comment]
`DiagnosticCounter` derived objects are meant to collect data within a process and publish said data to the in-proc `EventSource`. Then there's some mechanism that needs to deal with the collection of data of said source. In-proc you can do `EventListener`. Out of proc there's tools like dotnet-counters, dotnet-trace, dotnet-monitor, perfview, and VS. Perfview supports multiprocess monitoring but is windows only. The first three work on Linux as well, but they are single-process targeting at any point of time. 

My guess is using metrics + OpenTelemetry makes this kind of scenario possible since it would be multiple pipelines going to one connector - but I don't know how this works in practice. @noahfalk @tarekgh , do you know if there's such a scenario documented anywhere?

**Comment by noahfalk** [comment]
> it does not collect counters for all dotnet processes that are currently running

Can you help clarify this? Did you mean:
- you tried to connect some monitoring tool such as dotnet-counters to a process but it didn't connect
- you successfully connected a tool such as dotnet-counters to the process but it didn't show the set of counters you expected
- you successfully connected a tool and observed some value for the counter, but it wasn't the value you expected it to be
- something else?

Also let us know what tools you are using to collect the counter values (Visual Studio, dotnet-counters, dotnet-monitor, OpenTelemetry library, a custom written tool, something else?). Thanks!

**Comment by kykwo** [comment]
we use `EventPipeProvider` to collect a list of specified dotnet counters for .NET processes that get returned by `DiagnosticsClient.GetPublishedProcesses()` running on the machine, but we're finding that it's not getting the counters for all .NET processes. I guess the better question is whether there's something in `DiagnosticsClient.GetPublishedProcesses()` that is causing some processes not to get returned?

**Comment by hoyosjs** [comment]
`GetPublishedProcesses` will return the process ID's of the process calling the API has access to. By default, this is the ones started by the same user as the calling process's. If you want to see all, you'd need elevation. There's also ways processes using .NET can move their communication mechanism such that not even elevation will help - e.g. processes started with a private tmp won't be seen here, like those started by `systemd` with `PrivateTmp` enabled.

**Comment by kykwo** [comment]
Ohh I see, thank you for the explanation. Is there another API or method to programmatically get the .NET processes running on the node without needing elevation?

**Comment by noahfalk** [comment]
> Is there another API or method to programmatically get the .NET processes running on the node without needing elevation?

Nothing that is guaranteed to have the complete list or necessarily be easy. The processes that don't show up in the GetPublishedProcess() enumeration are either:
1. elevated processes you don't have access to. For these it would be a security problem if a non-elevated API let you access them or inspect them enough to determine if they are .NET processes.
2. processes running versions of .NET too old to support diagnostic port. For these you could enumerate them as part of a general OS process enumeration but you'd have to figure out what attribute will indicate they are .NET processes. For example you could enumerate their modules and look for one named libcoreclr on Linux.
3. processes that support diagnostic port, but configuration has disabled it. You could use /proc/<pid>/environ or the 'ps' command to enumerate environment variables. DOTNET_EnableDiagnostics=0 turns off diagnostic port.
4. processes that support diagnostic port, but configuration has moved the domain socket to a different temp directory. You could use the same approach as (3) to view the environment variables and then search in that app's TMPDIR for the domain socket.

For case (1) you can see the process but not know if its .NET. For (2) and (3) you can identify it as .NET but still can't connect to it. For (4) with some work you could identify it as .NET and connect to it.

**Comment by kykwo** [comment]
Thank you for the detailed answer. I wanted to double check one thing - 
If a process doesn't appear in `GetPublishedProcess()`, does that mean using `EventPipeProvider` to retrieve its dotnet counters won't work either due to access level etc.? Or does that not apply?

**Comment by noahfalk** [comment]
> If a process doesn't appear in GetPublishedProcess(), does that mean using EventPipeProvider to retrieve its dotnet counters won't work either due to access level etc.? Or does that not apply?

For cases 1, 2, and 3 above the counters aren't tracked or you won't have access to them. In case 4 its technically possible to read the counters, but you might need to fork and modify the DiagnosticsClient library source code to do it.

**Comment by kykwo** [comment]
Hello, this is a tangent but I was wondering if you knew a fix / reason for this. While testing I found that processes that get started in Linux by dotnet command (e.g. `dotnet MyApp.dll`) get reported with process name "dotnet" rather than something more specific. Is there a way to go around this?

**Comment by noahfalk** [comment]
There is a GetProcessInfo IPC command which includes the name of managed entrypoint assembly which might be helpful. I just checked and it looks like the API in DiagnosticsClient for whatever reason never got marked public, but its there if you want to call it via reflection: https://github.com/dotnet/diagnostics/blob/main/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs#L438

Its also documented in our protocol specification: https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#processinfo2
