### ISSUE TITLE
Use of  AssemblyNameInfo is wrong in TraceRuntimeDescToTypeSystemDesc

### ISSUE THREAD

**Issue by jialongcheng** [dotnet/runtime#102630]
### Description

[This commit](https://github.com/dotnet/runtime/pull/102036/files#diff-03d035a68af213d89f26e0f8287876c340026c734ba1d7e0553f523486c69f03) switched to use AssemblyNameInfo for TraceRuntimeDescToTypeSystemDesc.cs, however, the ModuleDescInfo  class takes AssemblyName like "System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e", which is not a simple name.

[This line](https://github.com/dotnet/runtime/pull/102036/files#diff-03d035a68af213d89f26e0f8287876c340026c734ba1d7e0553f523486c69f03R294) can't resolve modules like the above.

### Reproduction Steps

Run dotnet-pgo for a simple trace.

### Expected behavior

Loaded modules should be found with `_context.ResolveAssembly` from this line: https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs#L277

### Actual behavior

Null was returned from https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs#L277

**Comment by jkotas** [comment]
Thank you for reporting this. https://github.com/dotnet/runtime/pull/102634 should have the fix.
