### ISSUE TITLE
Activator.CreateInstance<T> does not bring compile error or throw exception for required property

### ISSUE THREAD

**Issue by Kumima** [dotnet/runtime#102734]
### Related: 
[dotnet-api-docs-issue-9172](https://github.com/dotnet/dotnet-api-docs/issues/9172)

### Detail:
Consider following code:
```csharp
//Read related issue first.
TodoItem todoItem = Activator.CreateInstance<TodoItem>();
Console.WriteLine(todoItem);
// This behaves like there is no "required" keyword.
// Id is initialized as 0 and Description is initialized as null.
public sealed record TodoItem
{
    public required int Id;
    public required string Description;
}
```

This behavior makes `required` keyword meaningless for the situation. It also breaks the nullable analysis, since `Description` should not be null under analysis.
> The [CreateInstance<T>()](https://learn.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=net-7.0#system-activator-createinstance-1) generic method is used by compilers to implement the instantiation of types specified by type parameters. For example, in the following generic method, the implementation of new T() (gcnew T() in C++) uses the [CreateInstance<T>()](https://learn.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=net-7.0#system-activator-createinstance-1) generic method.

As what I understand, the `required` keyword is indeed a compile stuff.

### Where I met problem
I met this problem when using `Microsoft.Extensions.Options`. The `OptionsFactory` uses `Activator.CreateInstance` to create a new instance of `TOptions`.  https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs#L93
Although I designed `TOption` with `required` property, if the configuration provider does not provide property value, the property will be initialized as null, and the nullable analysis can't generate warning for this. So, I met `NullReferenceException`.

Although I figured out that this is caused by `Activator.CreateInstance` as mentioned above, shouldn't `Activator.CreateInstance` bring compile error or throw exception? If this, does it mean `required` keyword will bring huge break changes?

I did not investigate the `Activator.CreateInstance<T>` internal implementation too much, just feel weird for this behavior and start this discussion.

**Comment by jkotas** [comment]
Reflection APIs do not enforce all rules enforced by C# language. This is one of them. It is up to the caller of the reflection API to not misuse them.

Another example is enforcement of visibility rules. Reflection allows you to call private methods that C# does not allow you to call.

**Comment by paulbartrum** [comment]
@Kumima Let's say `Activator.CreateInstance` did throw an exception. How would you ever construct an instance of that type using reflection? At least with the current behavior it is possible to detect the required fields and handle them.

**Comment by stephentoub** [comment]
Closing per https://github.com/dotnet/runtime/issues/102734#issuecomment-2134106772
