### ISSUE TITLE
`System.Text.Json` can't handle collection expressions in source gen mode

### ISSUE THREAD

**Issue by elringus** [dotnet/runtime#102746]
It seems there is no way to use collection expressions with the `Text.Json` serializer in [source generation mode](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation).

For example:
```cs
IReadOnlyList<string> list = ["foo", "bar"];
```
— would create an instance of `<>z__ReadOnlyArray`, but there doesn't seem to be a way to make the serializer aware of that type via `[JsonSerializable]` attribute.

This basically makes collection expression useless in AOT scenarios when JSON serialization is required.

Is this a known limitation or maybe there is a workaround/plan for one?

**Comment by huoyaoyuan** [comment]
System.Text.Json works with *contract* (variable) type, not *implementation* (object) type.

If you have a variable with type of `IReadOnlyList<string>`, you should make the serializer aware of `typeof(IReadOnlyList<string>)`:

```csharp
    [JsonSerializable(typeof(IReadOnlyList<string>))]
    partial class C : JsonSerializerContext
    {
    }

IReadOnlyList<string> list = ["foo", "bar"];
Console.WriteLine(JsonSerializer.Serialize(list, C.Default.IReadOnlyListString));
```

Variable type will not be used, unless the variable type is `object` when passed to `JsonSerializer`.

**Comment by elringus** [comment]
I've tried that, but it throws:

```
Failed to serialize '<>z__ReadOnlyArray`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' object: missing type info.
```

**Comment by huoyaoyuan** [comment]
I'm successfully running the code in .NET 8, and copied it.

Can you share more code or configuration?

**Comment by elringus** [comment]
I'm building with:

```
<PublishTrimmed>true</PublishTrimmed>
<TrimMode>full</TrimMode>
<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
<DynamicCodeSupport>false</DynamicCodeSupport>
```

— maybe that affects somethings?

I'll try to make a minimal repro.

**Comment by elringus** [comment]
My bad, I've actually had following under the hood:

```cs
public string Serialize (object poco)
{
    var type = poco.GetType();
    if (!Options.TryGetTypeInfo(type, out var info))
        throw new SerializeError($"Failed to serialize '{type.FullName}' object: missing type info.");
    return System.Text.Json.JsonSerializer.Serialize(poco, info);
}
```

Thanks for the help!
