### ISSUE TITLE
XmlSerializer.Deserialize fails when element contains XML content

### ISSUE THREAD

**Issue by mattfrear** [dotnet/runtime#102737]
### Description

I'm getting an exception when I call XmlSerializer.Deserialize - 'Element' is an invalid XmlNodeType.

It seems unlikely that there is a bug in such battle-tested code as the XmlSerializer, however, I have tried a couple of online XML validators and they don't complain.

I am trying to deserialize
```xml
<Response>
	<RT.VAL.ID>123</RT.VAL.ID>
	<Error>Parcel id invalid format [<RT.VAL.PARCEL.NO/>] should be 4N/N.</Error>
</Response>
```

### Reproduction Steps

```csharp
using System.Xml.Serialization;

namespace Tests;

public class XmlHelperTests
{
    [XmlRoot("Response")]
    public class UpdateValuationResponse
    {
        [XmlElement("RT.VAL.ID")]
        public string? ValidationId { get; set; }

        [XmlElement("Error")]
        public string? Error { get; set; }
    }

    [Fact]
    public void CanXmlDeserializeErrorResponse()
    {
        // Arrange
        var xml = "<Response><RT.VAL.ID>123</RT.VAL.ID><Error>Parcel id invalid format [<RT.VAL.PARCEL.NO/>] should be 4N/N.</Error></Response>";

        // Act
        var serializer = new XmlSerializer(typeof(UpdateValuationResponse));

        using var reader = new StringReader(xml);
        var result = serializer.Deserialize(reader) as UpdateValuationResponse; // throws InvalidOperationException

        // Assert
        Assert.StartsWith("Parcel id invalid format", result!.Error);
    }
}
```

Throws an InvalidOperationException - There is an error in XML document (1, 104).

### Expected behavior

The object should be deserialized and the Error should contain "Parcel id invalid format [<RT.VAL.PARCEL.NO/>] should be 4N/N."

### Actual behavior

System.InvalidOperationException: There is an error in XML document (1, 104).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Tests.XmlHelperTests.CanXmlDeserializeErrorResponse() in C:\code\tcc\Tcc.Ozone.Client\Tcc.Ozone.Client.Tests\Tests.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.FinishReadElementContentAsXxx()
   at System.Xml.XmlReader.ReadElementContentAsString()

### Configuration

.NET 8

**Comment by MichalStrehovsky** [comment]
> however, I have tried a couple of online XML validators and they don't complain.

Try modifying your XML like this and run the validator again:

```xml
<Response>
	<RT.VAL.ID>123</RT.VAL.ID>
	<Error>Parcel id invalid format [<RT.VAL.PARCEL.NO/] should be 4N/N.</Error>
</Response>
```

(I've deleted the `>` inside the Error "string".)

To get `<` and `>` treated like text in XML, one needs to escape it as `&lt;`/`&gt;` or `CDATA`, otherwise it's an XML tag and not textual data.

**Comment by filipnavara** [comment]
As Michal pointed out, the serializer is correct. The XML is valid but not according to the schema described by the C# class. The schema says that `<Error>` is a `string` while it's a mixed content here.

Ideally, the serializer should produce something like this:
```xml
<Response>
	<RT.VAL.ID>123</RT.VAL.ID>
	<Error>Parcel id invalid format [&lt;RT.VAL.PARCEL.NO/&gt;] should be 4N/N.</Error>
</Response>
```

The alternative is to read the content with `XmlReader` and use `XmlReader.ReadInnerXml()` to read the error string. If you want to keep using the serializer you can use this trick:
```csharp
[XmlRoot("Response")]
public class UpdateValuationResponse
{
    [XmlElement("RT.VAL.ID")]
    public string? ValidationId { get; set; }

    [XmlElement("Error")]
    public RawString? Error { get; set; }
}
    
public class RawString : IXmlSerializable
{
    public string Value { get; set; }
    public XmlSchema GetSchema() => null;
    public void ReadXml(System.Xml.XmlReader reader) => this.Value = reader.ReadInnerXml();
    public void WriteXml(System.Xml.XmlWriter writer) => writer.WriteRaw(this.Value);
}    
```

**Comment by mattfrear** [comment]
Thanks @MichalStrehovsky and @filipnavara . I will ask the creator of the XML to wrap it in CDATA.
