### ISSUE TITLE
In official build, use signing and SDL validation team properties based on Runtime team

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1027]
Right now, the TeamName for signing and some values for SDL validation came from Core-Setup, since it was the last in the set of builds and controls signing. These should be set to something related to the runtime team, not core-setup anymore, and SDL automation should be enabled.

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/runtime-official.yml#L25-L27

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/official/stages/publish.yml#L37-L38

**Comment by ViktorHofer** [comment]
SDL validation doesn't run anymore as part of our build. Closing.
