### ISSUE TITLE
Environment.FailFast in .NET 8 Container Yields Segmentation Fault (Exit Code 139)

### ISSUE THREAD

**Issue by assaftir** [dotnet/runtime#102785]
### Description

When running a .NET 8 application in a Linux container, invoking `Environment.FailFast` leads to unexpected behavior, resulting in a segmentation fault (signal SIGSEGV, exit code 139). However, when running the container with the `--pid=host` option, the application exits with the expected exit code 134 (signal SIGABRT).

### Reproduction Steps

1) Follow the example from the [official .NET documentation](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=linux&pivots=dotnet-8-0) to set up a .NET 8 container.
2) Modify `Program.cs` to call `Environment.FailFast`.
3) Build and run the container.
4) Observe that the container exits with exit code 139 (indicating a segmentation fault).
5) Run the container with the `--pid=host` option.
6) Observe that the container exits with exit code 134 (indicating an abort signal).

### Expected behavior

The application should consistently exit with code 134 (signal SIGABRT) when `Environment.FailFast` is invoked, regardless of the PID namespace configuration.

### Actual behavior

The application exit with code 139 (signal SIGSEGV) when `Environment.FailFast` is invoked.

### Other information

Upon examining the code for `Environment.FailFast`, I noticed the call to `Interop.Sys.Abort`. Based on this, the expected behavior for `Environment.FailFast` should be to terminate the process with SIGABRT (exit code 134).

Additionally, I am wondering about the implications of calling `abort` when the process is the init process (PID 1) in a Linux container. If `abort` is called on the init process, it could lead to unexpected behavior or the container hanging due to its special signal handling. I would like to understand better what the expected behavior should be in this scenario.

**Comment by janvorli** [comment]
I believe the reason for this is described here: https://ddanilov.me/how-signals-are-handled-in-a-docker-container.

**Comment by janvorli** [comment]
While we do install a SIGABORT handler, we just let it call the previously registered one, thinking it would be the default handler. Since there is none when the process PID is 1, we end up hitting what the article has described.

**Comment by assaftir** [comment]
We have migrated our containers to use the `dumb-init` process, which acts as the init system.
This change resolves the issue, as the .NET process is no longer running as PID 1. With `dumb-init` handling the init responsibilities, `Environment.FailFast` now behaves as expected, terminating the process with the appropriate signal without causing a segmentation fault.

**Comment by mangod9** [comment]
Hi @assaftir, assume this issue is ok to close?
