### ISSUE TITLE
Issue with LDAP connection on RHEL\Rocky

### ISSUE THREAD

**Issue by alexvadk** [dotnet/runtime#102757]
### Description

Hi!

While using the LDAP connection from RHEL\Rocky, we got an exception about the absence of the libldap-2.5.so.0.
As I understand the problem, the issue is:
- The OpenLDAP 2.6 contains the library with a new name libldap.so.2

### Reproduction Steps

You can find an example of the code to reproduce the problem in the attachment.
[LibldapIssue.zip](https://github.com/dotnet/runtime/files/15470204/LibldapIssue.zip)

### Expected behavior

We can use the new (non-legacy) version libldap-2.6.so to execute LDAP connection from RHEL\Rockynonlegacy

### Actual behavior

We have a following exception:

Unhandled exception. System.TypeInitializationException: The type initializer for 'Ldap' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'libldap-2.5.so.0' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.5/libldap-2.5.so.0: cannot open shared object file: No such file or directory
/home/odmin/LdapIssue/libldap-2.5.so.0: cannot open shared object file: No such file or directory
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.5/liblibldap-2.5.so.0: cannot open shared object file: No such file or directory
/home/odmin/LdapIssue/liblibldap-2.5.so.0: cannot open shared object file: No such file or directory
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.5/libldap-2.5.so.0.so: cannot open shared object file: No such file or directory
/home/odmin/LdapIssue/libldap-2.5.so.0.so: cannot open shared object file: No such file or directory
/usr/lib64/dotnet/shared/Microsoft.NETCore.App/8.0.5/liblibldap-2.5.so.0.so: cannot open shared object file: No such file or directory
/home/odmin/LdapIssue/liblibldap-2.5.so.0.so: cannot open shared object file: No such file or directory
 
   at Interop.Ldap.<ldap_get_option_int>g____PInvoke|7_0(IntPtr __ldapHandle_native, LdapOption __option_native, Int32* __outValue_native)
   at Interop.Ldap.ldap_get_option_int(IntPtr ldapHandle, LdapOption option, Int32& outValue)
   at Interop.Ldap..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ldap.ldap_initialize(IntPtr& ld, String uri)
   at System.DirectoryServices.Protocols.ConnectionHandle..ctor()
   at System.DirectoryServices.Protocols.LdapConnection.InternalInitConnectionHandle()
   at System.DirectoryServices.Protocols.LdapConnection.Init()
   at System.DirectoryServices.Protocols.LdapConnection..ctor(LdapDirectoryIdentifier identifier, NetworkCredential credential, AuthType authType)
   at System.DirectoryServices.Protocols.LdapConnection..ctor(LdapDirectoryIdentifier identifier)
   at LdapIssue.Program.Main(String[] args) in D:\Projects\atretyakov\LibldapIssue\LibldapIssue\Program.cs:line 11

### Known Workarounds

1) There is a workaround to install "openldap-compat.x86_64" (dnf -y install openldap-compat.x86_64), but it's part of the legacy repository and could be dropped at any moment.

2) Another way is ln -s /usr/lib64/libldap.so.2 /usr/lib64/libldap-2.5.so.0

### Configuration

.NET 8.0.5
Rocky 9.4\RHEL
Architecture x64
Yep, it's specific for the platform (on Ubuntu, it works fine)

**Comment by buyaa-n** [comment]
> We can use the new (non-legacy) version libldap-2.6.so to execute LDAP connection from RHEL\Rockynonlegacy

By my understanding the `libldap-2.5.so.0` is not legacy, it is the [current LTS Release](https://www.openldap.org/software/download/) version, we actually [changed the version](https://github.com/dotnet/runtime/pull/88851) in last release from `libldap-2.4.so.2` into `libldap-2.5.so.0`.  With that change we try to load `libldap-2.5.so.0` first, then try load `libldap-2.6.so.0` or `libldap-2.4.so.2`

What version of [System.DirectoryServices.Protocols](https://www.nuget.org/packages/System.DirectoryServices.Protocols/#versions-body-tab) you are using? If the updated version is not working for you for now you can keep using the workaround you mentioned in Known Workarounds section or can try [this workaround](https://github.com/dotnet/runtime/issues/69456#issuecomment-1592867432)
