### ISSUE TITLE
Add parameter to Except to allow non-uniqueness

### ISSUE THREAD

**Issue by bstordrup** [dotnet/runtime#102707]
I ran into the issue described in https://github.com/dotnet/runtime/issues/44516 when trying to get the version number part of a NuGet package name.

Providing the file name "My.Awesome.Package.19.0.0.1.nupkg", I used a regular exception to find the name parts and then find the version part using Except. But it returned the array {19, 0, 1}.

It can be solved by adding a parameter to the Except function (or an overload) that allows it to handle having duplicate parts in the result set as this could be a correct result in some situations.

**Comment by eiriktsarpalis** [comment]
I don't think we could consider a boolean parameter that changes the semantics of `Except` to something different. I would recommend writing a custom extension method instead.
