### ISSUE TITLE
ILC: Assertion failed '(unsigned)reg < ArrLen(regMasks)' in '...' during 'Generate code' (IL size 6; hash 0x04901a61; FullOpts)

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#102715]
Native AOT ARM32 Linux outerloop runs are on the floor due to hitting asserts in RyuJIT: https://dev.azure.com/dnceng-public/public/_build/results?buildId=687421&view=results

This regression was introduced in #102592 (the outerloop run at the commit right before the PR was clean).

**Comment by kunalspathak** [comment]
Will take a look

**Comment by kunalspathak** [comment]
It's odd that superpmi replay didn't catch these failures. We do have a collection for nativeaot, but probably collection pipeline also has some failures because of which we don't have the collection out there to test.
