### ISSUE TITLE
PersistedAssemblyBuilder writes incorrect type names to generated assembly for nested types

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#102777]
### Description

The repro case as-written, not using `PersistedAssemblyBuilder`, works correctly. But if you uncomment the alternative version that does use `PersistedAssemblyBuilder`, and comment out the normal `AssemblyBuilder` version, attempting to run it will throw `TypeLoadException`.

### Reproduction Steps

```
using System.Reflection.Emit;
using System.Reflection;

namespace NestedTypeName
{
	internal class NestedTypeEmit
	{
		static void Main()
		{
			var asm = Build();
			var foo = Activator.CreateInstance(asm.GetType("Foo")!)!;
			foo.GetType().GetMethod("Test")!.Invoke(null, null);
		}

		private static Assembly Build()
		{
			//var assemblyBuilder = new PersistedAssemblyBuilder(new("MyAssembly"), typeof(object).Assembly);
			var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new("MyAssembly"), AssemblyBuilderAccess.RunAndCollect);

			ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule("MyAssembly");
			var typeBuilder = moduleBuilder.DefineType("Foo", TypeAttributes.Public, typeof(object));
			typeBuilder.DefineDefaultConstructor(MethodAttributes.Public);

			var writeMethod = typeBuilder.DefineMethod("Test", MethodAttributes.Public | MethodAttributes.Static);
			var il = writeMethod.GetILGenerator();
			il.DeclareLocal(typeof(HashSet<int>.Enumerator));
			il.Emit(OpCodes.Newobj, typeof(HashSet<int>).GetConstructors().First(c => c.GetParameters().Length == 0));
			il.Emit(OpCodes.Callvirt, typeof(HashSet<int>).GetMethod("GetEnumerator")!);
			il.Emit(OpCodes.Stloc_0);
			il.Emit(OpCodes.Ret);

			typeBuilder.CreateType();

			/*
			var filename = Path.GetFullPath(".\\MyAssembly.dll");
			assemblyBuilder.Save(filename);
			return Assembly.LoadFile(filename);
			*/
			return assemblyBuilder;
		}

	}
}
```

### Expected behavior

Both implementations should run successfully and terminate silently.

### Actual behavior

The `PersistedAssemblyBuilder` version of the code throws the following error:

> System.TypeLoadException: 'Could not load type 'System.Collections.Generic.Enumerator' from assembly 'System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'

Somewhere along the line, it appears that `PeristedAssemblyBuilder` has lost track of the name of the enclosing class.

### Regression?

This worked correctly when saving assemblies from Reflection.Emit in .NET Framework.

### Configuration

.NET 9, Preview 4
Windows 10, x64

**Comment by masonwheeler** [comment]
@buyaa-n Got another one for you!

**Comment by masonwheeler** [comment]
@buyaa-n Thanks for all your hard work on these cases!

How does the daily build process work?  On an earlier issue, I got linked to https://github.com/dotnet/sdk/blob/main/documentation/package-table.md, but that doesn't appear to be updated every day with new builds, as the last update to the page was 9 days ago.

**Comment by buyaa-n** [comment]
> @buyaa-n Thanks for all your hard work on these cases!

Thank you for reporting the bug. 

> How does the daily build process work? On an earlier issue, I got linked to https://github.com/dotnet/sdk/blob/main/documentation/package-table.md, but that doesn't appear to be updated every day with new builds, as the last update to the page was 9 days ago.

It would build daily if the changes from many repos flow into SDK and builds successfully, sometimes some changes causes build failure and it could delay until the issues resolved.

Currently the [SDK version](https://aka.ms/dotnet/9.0.1xx/daily/productCommit-win-x64.txt) shows the runtime head on https://github.com/dotnet/runtime/commit/9fca0c3dbd3874ed0245b1bdb10547d0ba769d66, so it should have the other bug fix merged on Thursday.
