### ISSUE TITLE
[WASM][MT] fail: System.TypeLoadException: Could not resolve type with token

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#102762]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=684463
Build error leg or test failing: WasmTestOnChrome-MT-System.ComponentModel.Composition.Registration.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/102563

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "fail: System.TypeLoadException: Could not resolve type with token",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=684463
**Error message validated:** `[fail: System.TypeLoadException: Could not resolve type with token`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/28/2024 2:29:37 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ilonatommy** [comment]
No hits for a month. Feel free to reopen
