### ISSUE TITLE
System.Management.Tests fails with "CONTRACT VIOLATION by LoaderAllocator::SetHandleValue"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#102719]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=688333
Build error leg or test failing: System.Management.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/102074
Console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-102074-merge-ed0aa3fb9d2f423082/System.Management.Tests/1/console.40b94cf1.log?helixlogtype=result

```
C:\h\w\BBF60A2D\w\B9A90A05\e>"C:\h\w\BBF60A2D\p\dotnet.exe" exec --runtimeconfig System.Management.Tests.runtimeconfig.json --depsfile System.Management.Tests.deps.json xunit.console.dll System.Management.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Management.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Management.Tests (found 18 of 28 test cases)
  Starting:    System.Management.Tests (parallel test collections = on [4 threads], stop on fail = off)
    System.Management.Tests.ManagementObjectTests.PlatformNotSupportedException_On_Nano [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"

Assert failure(PID 920 [0x00000398], Thread: 6064 [0x17b0]): CONTRACT VIOLATION by LoaderAllocator::SetHandleValue at "D:\a\_work\1\s\src\coreclr\vm\loaderallocator.cpp":970

MODE_COOPERATIVE encountered while thread is in preemptive state.

                        CONTRACT in LoaderAllocator::SetHandleValue at "D:\a\_work\1\s\src\coreclr\vm\loaderallocator.cpp":970
                        CONTRACT in LoaderAllocator::FreeHandle at "D:\a\_work\1\s\src\coreclr\vm\loaderallocator.cpp":880
                        CONTRACT in EEMarshalingData::GetCustomMarshalerHelper at "D:\a\_work\1\s\src\coreclr\vm\mlinfo.cpp":909
VIOLATED-->  CONTRACT in SetupCustomMarshalerHelper at "D:\a\_work\1\s\src\coreclr\vm\mlinfo.cpp":398
                        CONTRACT in StubHelpers_CreateCustomMarshalerHelper at "D:\a\_work\1\s\src\coreclr\vm\mlinfo.cpp":4084
                        CONTRACT in DispatchCallSimple at "D:\a\_work\1\s\src\coreclr\vm\callhelpers.cpp":178
                        CONTRACT in ThreadNative::KickOffThread_Worker at "D:\a\_work\1\s\src\coreclr\vm\comsynchronizable.cpp":148
                        CONTRACT in ManagedThreadBase_DispatchInner at "D:\a\_work\1\s\src\coreclr\vm\threads.cpp":7168
                        CONTRACT in ManagedThreadBase_FullTransition at "D:\a\_work\1\s\src\coreclr\vm\threads.cpp":7416
                        CONTRACT in ThreadNative::KickOffThread at "D:\a\_work\1\s\src\coreclr\vm\comsynchronizable.cpp":196



CORECLR! CONTRACT_ASSERT + 0x2E4 (0x710d1909)
CORECLR! EEContract::DoChecks + 0x159 (0x7135d07a)
CORECLR! LoaderAllocator::SetHandleValue + 0x168 (0x7122c9b1)
CORECLR! LoaderAllocator::FreeHandle + 0x150 (0x712244d8)
CORECLR! CustomMarshalerInfo::~CustomMarshalerInfo + 0x43 (0x7133bc90)
CORECLR! EEMarshalingData::GetCustomMarshalerHelper + 0x57C (0x71417745)
CORECLR! SetupCustomMarshalerHelper + 0x28D (0x7141e661)
CORECLR! StubHelpers_CreateCustomMarshalerHelper + 0x252 (0x7141ecb2)
<no module>! <no symbol> + 0x0 (0x0da52ebe)
<no module>! <no symbol> + 0x0 (0x0da52b8b)
    File: D:\a\_work\1\s\src\coreclr\vm\loaderallocator.cpp:970
    Image: C:\h\w\BBF60A2D\p\dotnet.exe

```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "CONTRACT VIOLATION by LoaderAllocator::SetHandleValue",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=688333
**Error message validated:** `[CONTRACT VIOLATION by LoaderAllocator::SetHandleValue`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/27/2024 11:46:44 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[688622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688622)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688622&view=ms.vss-test-web.build-test-results-tab&runId=17108300&resultId=211771)|dotnet/runtime#102580|
|[688547](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688547)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688547&view=ms.vss-test-web.build-test-results-tab&runId=17106842&resultId=211771)|dotnet/runtime#102705|
|[688354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688354)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688354&view=ms.vss-test-web.build-test-results-tab&runId=17097054&resultId=211771)|dotnet/runtime#102713|
|[688333](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688333)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688333&view=ms.vss-test-web.build-test-results-tab&runId=17095942&resultId=211777)|dotnet/runtime#102074|
|[688323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688323)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688323&view=ms.vss-test-web.build-test-results-tab&runId=17095908&resultId=211771)|dotnet/runtime#102711|
|[687961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687961)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687961&view=ms.vss-test-web.build-test-results-tab&runId=17095732&resultId=211771)|dotnet/runtime#102688|
|[688285](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688285)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688285&view=ms.vss-test-web.build-test-results-tab&runId=17093488&resultId=211771)||
|[688243](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688243)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688243&view=ms.vss-test-web.build-test-results-tab&runId=17091412&resultId=211771)|dotnet/runtime#102645|
|[688076](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688076)|dotnet/runtime|[System.Management.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688076&view=ms.vss-test-web.build-test-results-tab&runId=17087222&resultId=211771)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|9|9|9|

**Comment by jakobbotsch** [comment]
This fails outside win-x86 as well, e.g. https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-e607368ae19646e987/System.Management.Tests/1/console.915818c5.log?helixlogtype=result is a failure on win-x64.

**Comment by EgorBo** [comment]
Looks like it started to fail after https://github.com/dotnet/runtime/pull/102605 ?

**Comment by jkotas** [comment]
This was introduced by https://github.com/dotnet/runtime/pull/99998/ . It changed the contract on LoaderAllocator::SetHandleValue method that's failing here.
