### ISSUE TITLE
Problem when including the `corprof.h` file to use the Profiling API

### ISSUE THREAD

**Issue by yegor-pelykh** [dotnet/runtime#102701]
### Description

I want to use Profiling API in my C++ DLL project.

When I add below include to the project and then run a build, a lot of build errors appear:
```cpp
#include "corprof.h"
```

Errors (not all, but the rest are similar):
![2](https://github.com/dotnet/runtime/assets/21262076/5ad81b6d-0f35-4fa8-af71-1e8a2f0473e2)

### Reproduction Steps

1) Include `corprof.h`
2) Build project

### Expected behavior

No errors

### Actual behavior

Many errors

### Other information

Additional information:
I already added `corguids.lib` as linked library.
So this is not the cause for sure.

**Comment by yegor-pelykh** [comment]
The simplest example to reproduce.

[Example.zip](https://github.com/dotnet/runtime/files/15457001/Example.zip)

Steps to create:
1) An empty DLL project was created in Visual Studio 2022
2) Added `#include "coprof.h"` in `pch.h`

**Comment by mdh1418** [comment]
Hi @yegor-pelykh, it looks like from `corprof.h`, [those types are excluded from a preprocessor directive](https://github.com/dotnet/runtime/blob/1fc1dd84f3ac84e22975c981098c0cc527f9c7b5/src/coreclr/pal/prebuilt/inc/corprof.h#L296-L331). Could you try adding `#include "cor.h"` before `#include "corprof.h"` in `pch.h`?

**Comment by yegor-pelykh** [comment]
> Could you try adding `#include "cor.h"` before `#include "corprof.h"` in `pch.h`?

Yes, it works!
Thanks for the tip.

So it was intended that these two headers should be included together?
Or is this a bug?

**Comment by mdh1418** [comment]
I'm not sure what the original thought was for having the `corprof.h` generator (corprof.idl) not import `cor.h`, but it seems like its been the general trend for profilers to include both of the headers (e.g. https://github.com/microsoft/clr-samples/blob/master/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.h#L7). Not sure if it'd somehow break any existing scenarios if we did import `cor.h` by default.

But in any case, adding the `#include "cor.h"` header (or even just a barebones type definitions for the missing types) should suffice. Thanks for reporting the issue, I'll close it as we currently aren't planning to change the behavior.

**Comment by yegor-pelykh** [comment]
Okay, thanks for the help!
