### ISSUE TITLE
`ServiceCollection` class ambiguous  reference in v.8.0.1 w/ Microsoft.Extensions.DependencyInjection v8.0.0

### ISSUE THREAD

**Issue by astrohart** [dotnet/runtime#102703]
### Description

I am trying to write a project that uses `ServiceCollection` and I have v8.0.1 of `Microsoft.Extensions.DependencyInjection.Abstractions` and v8.0.0 of `Microsoft.Extensions.DependencyInjection` [NuGet package](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/9.0.0-preview.4.24266.19).  v8.0.0 is the max 8-version of `Microsoft.Extensions.DependencyInjection`.

The problem is, they do not play nice but seem to depend on each other.  With both packages at the versions specified installed, my VS2022 IDE says "ServiceCollection: Ambiguous reference" but then when I remove one or the other package, other code breaks.

### Reproduction Steps

Install both of the NuGet packages listed above into a solution and then new up a `ServiceCollection` instance.  VS 2022 / Roslyn will complain that `ServiceCollection` is defined in both.  Then, attempt to call the `BuildServiceProvider` extension method.  Now, remove the `Microsoft.Extensions.DependencyInjection.Abstractions` NuGet package from the project.  The `BuildServiceProvider` method call breaks (undeclared identifier).

### Expected behavior

No errors.

### Actual behavior

Described above.

### Regression?

I am not clear.

**Comment by colejohnson66** [comment]
You shouldn't need to reference `Microsoft.Extensions.DependencyInjection.Abstractions`. The base `Microsoft.Extensions.DependencyInjection` references it already.

**Comment by steveharter** [comment]
Closing as not an issue. Please comment here if that is not the case.
