### ISSUE TITLE
Add Persian language for DayOfWeek of PersianCalendar class

### ISSUE THREAD

**Issue by Farzadhr** [dotnet/runtime#102779]
Hi
You can add Persian language for DayOfWeek of PersianCalendar class by this switch

`
            switch(StringDayOfWeek){
                case "Saturday":
                    return "شنبه";
                case "Sunday":
                    return "یک‌شنبه";
                case "Monday":
                    return "دو‌شنبه";
                case "Tuesday":
                    return "سه‌شنبه";
                case "Wednesday":
                    return "چهار‌شنبه";
                case "Thursday":
                    return "پنج‌شنبه";
                case "Friday":
                    return "جمعه";
                default:
                    return null;
            }
`

please add this switch, we need this

**Comment by colejohnson66** [comment]
Due to transfer, this is now a duplicate of #102556

**Comment by tarekgh** [comment]
Yes this is a duplicate of https://github.com/dotnet/runtime/issues/102556.
