### ISSUE TITLE
Need coredistools for arm32/arm64

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#10281]
The coredistools package needs arm32/arm64 builds to enable superpmi assembly diffs on these platforms. Currently, only Windows/Linux x86/x64 binaries are in the package.

(Note that it it not needed for these platforms for GC stress, which is the other major user of the coredistools package.)

fyi, coredistools is currently built in the https://github.com/dotnet/llilc repo.

category:eng-sys
theme:super-pmi
skill-level:intermediate
cost:small

**Comment by echesakovMSFT** [comment]
Will be closed by https://github.com/dotnet/jitutils/pull/293

**Comment by echesakovMSFT** [comment]
The updated coredistools were published to a NuGet feed from dotnet/jitituls (https://github.com/dotnet/jitutils/pull/298) and dotnet/runtime infrastructure was updated to use the package in https://github.com/dotnet/runtime/pull/44490. That version now supports both Arm32 and Arm64 as host platforms (i.e. can be loaded in processes on those platforms) and as targets platforms (i.e. the disassembler can decode Thumb2 and AArch64 instructions). 

There are issues with running superpmi replay using coredistools on these platforms, but they have nothing to do with coredistools per se (e.g. https://github.com/dotnet/runtime/issues/42641), so I believe the issue can be closed.
