### ISSUE TITLE
String.Split does not work well with slashes

### ISSUE THREAD

**Issue by drweb86** [dotnet/runtime#102841]
### Description

Splitting returns invalid data with slashes.

### Reproduction Steps

```
var parts = "\\1/2///\\\\"
    .Split('/', '\\', System.StringSplitOptions.RemoveEmptyEntries);
```

### Expected behavior

```
parts.Length == 2
parts[0] == "1"
parts[1] == "2"
```

### Actual behavior

```
parts.Length == 3
parts[0] == "\\1"
parts[1] == "2"
parts[2] == "\\\\"
```

### Configuration

.Net 8 x64 on Windows x64

### Other information

If you will fix it ping me please because I need it in my project.

**Comment by joegoldman2** [comment]
Currently you are using the overload that takes a char and a int (corresponding to the maximum number of elements expected in the returned array). The second argument `'\\'` is implicitly convert to a int which corresponds to the value 92.

You should use the overload that takes a char[]  to get your expected result like: `"\\1/2///\\\\".Split(new char[] { '/', '\\' }, System.StringSplitOptions.RemoveEmptyEntries);`

**Comment by joegoldman2** [comment]
Currently you are using the overload that takes a char and a int (corresponding to the maximum number of elements expected in the returned array). The second argument `'\\'` is implicitly convert to a int which corresponds to the value 92.

You should use the overload that takes a char[]  to get your expected result like: `"\\1/2///\\\\".Split(new char[] { '/', '\\' }, StringSplitOptions.RemoveEmptyEntries);`

**Comment by drweb86** [comment]
Hi @joegoldman2 . Thank's for your so fast response. Yes, that was it! Incredible!
