### ISSUE TITLE
Confused about NuGet package versions

### ISSUE THREAD

**Issue by astrohart** [dotnet/runtime#102889]
Hello:

I am confused. 

I noticed that the [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/9.0.0-preview.4.24266.19) is listed as having the most-recent stable version at  `8.0.0` but the [Microsoft.Extensions.DependencyInjection.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/8.0.1) is listed as being at `8.0.1`f or the most-recent stable version.

Do these package(s) and their version(s) play well together?  Because I am getting a breaking change when I use these versions that breaks my code.  Specifically, it seems as if the `BuildServiceProvider` method goes away.

**Comment by julealgon** [comment]
Looking like this might be related or a duplicate:
- https://github.com/dotnet/runtime/issues/102703

**Comment by huoyaoyuan** [comment]
> Because I am getting a breaking change when I use these versions that breaks my code. Specifically, it seems as if the `BuildServiceProvider` method goes away.

This type of breaking change can never happen during a patch version.

Installing both Extensions.DI and Extensions.DI.Abstractions in a same console application plays well. It's the expected behavior.

Can you share more about how you are installing and using these packages in your project?
