### ISSUE TITLE
Unify remaining diverged threading types in corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#10284]
We have reached the point that 60% of CoreCLR corelib code is shareable. We believe we can reasonably take this further, perhaps to 80% however much of the remaining reconciliation will take domain knowledge because the merges are not trivial.  

From a diff of `corert\src\system.private.corelib\src` and `coreclr\src\mscorlib\src` these are files related to threading/tasks whose implementations need to be unified. In some cases this will take care. In some happy cases the CoreRT code may just be a frozen old copy of the CoreCLR code from years ago in which case possibly resolution may be just "take coreclr". Once implementations have been reconciled, the shared copy should move under "shared" and the other copies deleted.

- [ ]     .\internal\runtime\augments\*thread.cs
- [ ]     .\system\runtime\compilerservices\taskawaiter.cs
- [ ]     .\system\threading\*  and	.\system\threading\tasks\* (about 85 files)
- [ ]  	.\internal\threading\tasks\asynccausalitysupport.cs
- [ ]  	.\internal\threading\tasks\tracing\tasktrace.cs
- [ ]  	.\internal\threading\tracing\spinlocktrace.cs

https://github.com/dotnet/coreclr/issues/9474

**Comment by stephentoub** [comment]
Closing as addressed.  @danmosemsft, please re-open if there's more to be done here.
