### ISSUE TITLE
Several LINQ classes implement IList<T> but raise on any mutating method

### ISSUE THREAD

**Issue by sglienke** [dotnet/runtime#102825]
### Description

I just noticed that with [this change](https://github.com/dotnet/runtime/pull/88249) several iterator classes that represent a non-mutable collection implement `IList<T>` for some internal optimization but raise exceptions on any of their mutating methods. To my understanding for this there exists `IReadOnlyList<T>` which if I am not missing something has all non-mutating methods except `Contains` and `IndexOf` (which I would argue the first also should be added to `IReadOnlyCollection<T>` and the second to `IReadOnlyList<T>`). Any code that for performance reasons checks if the collection is index-based read should instead ask for `IReadOnlyList<T>` and not `IList<T>` (for example `Enumerable.SequenceEqual` where I originally noticed that it went the path for `IList<T>` although I passed in the result of `Enumerable.Range` and was not expecting this `IEnumerable<T>` to be able to be treated as `IList<T>`.

My understanding is that partially implementing an interface and raising exceptions on some of it's method is to be avoided.

### Reproduction Steps

The following code will raise an exception:

```
var list = Enumerable.Range(1, TEST_COUNT) as IList<int>;
list?.Add(1);

```

### Expected behavior

Cast returning `null` and thus no attempt to call `Add` and no exception.

### Actual behavior

The code allows the cast to `IList<int>` and raises a `NotSupportedException`.

**Comment by stephentoub** [comment]
> My understanding is that partially implementing an interface and raising exceptions on some of it's method is to be avoided.

`IList<T>` has an `IsReadOnly` property (that comes from the inherited `ICollection<T>`). All of the cited types return true from `IsReadOnly`. Note that public types like `ReadOnlyCollection<T>` and `ReadOnlyDictionary<TKey, TValue>` also implement `IList<T>` and also return true from `IsReadOnly`.

This is all by design.

**Comment by sglienke** [comment]
Thanks for the quick response - I forgot about the `IsReadOnly`. I don't necessarily agree on that design but it is what it is and has been for quite a while.
But can you elaborate on the reason for newly implementing `IList<T>` where `IReadOnlyList<T>` would suffice? Is that because of the numerous places that check for `IList<T>` instead of `IReadOnlyList<T>` or classes that implement the former but not the latter?

**Comment by stephentoub** [comment]
> Is that because of the numerous places that check for IList<T> instead of IReadOnlyList<T>

Yes.
