### ISSUE TITLE
Version number on NuGet

### ISSUE THREAD

**Issue by Geertkok1** [dotnet/runtime#102871]
Good Morning,

We use the System.Text.Encodings.Web library from NuGet in one of our C# projects.

The version number that is available in NuGet and that also get reported if we manualy add System.Text.Encodings.Web.dll in a C# project is 8.0.0.0.

But if we manually check the version of the dll file in Windows we see version 8.0.23.53103.

Because the version is still reported as 8.0.0.0 our SBOM and Dependency scanning tool see it as an vurnerable version eventhough the dll is already on a version where the issue is fixed.

Could the necessary changes be made so that the version is detected correctly?

If this is the wrong place to create this issue please do no hesitate to tell me where the correct please is to open this issue so that I can open an issue there.

With Kind regards,
Geert

**Comment by colejohnson66** [comment]
This is a bug in your dependency vulnerability toolchain. The "file version" (`8.0.23.53103`) and the "product version" (`8.0.0+...`) are two different things, and should not be conflated.

**Comment by huoyaoyuan** [comment]
> So if we add it via NuGet the following version is visable

> It finds the following vulnerabilities:

Why are those vulnerabilities associated with System.Text.Encodings.Web at all? S.T.Encodings.Web depends on none of them.

The correct way to scan for NuGet dependency is inspecting `project.assets.json` produced by `dotnet restore`, which contains the restore result about which precise package versions are used.

**Comment by huoyaoyuan** [comment]
Also note that for compatibility, the assembly version (`System.Text.Encodings.Web, Version=8.0.0.0, Culture=neutral` in this case) is **NOT** changed when servicing for fixes. It should not be used for determining vulnerability.

**Comment by Geertkok1** [comment]
> Also note that for compatibility, the assembly version (`System.Text.Encodings.Web, Version=8.0.0.0, Culture=neutral` in this case) is **NOT** changed when servicing for fixes. It should not be used for determining vulnerability.

Good afternoon,

Thank you for the explanation. I will tell the team that it is an not relevant.

I will also send the feedback that you mentioned to the makers of depscan so that they can improve on scanning dependancies.

With Kind Regards,

Geert

**Comment by vitek-karas** [comment]
/fyi @agocke 

> The correct way to scan for NuGet dependency is inspecting project.assets.json

That's almost correct for self-contained apps. But not for framework dependent apps where one has to consider the frameworks installed on the target machine as well.

**Comment by julealgon** [comment]
Is there even a reason to rely on an external vulnerability checker today with the new NuGet vulnerability warnings feature? Shouldn't Microsoft just recommend _that_?
