### ISSUE TITLE
HttpClient.PostAsJsonAsync Extensions missing Content-Type Header

### ISSUE THREAD

**Issue by Zekiah-A** [dotnet/runtime#102855]
### Description
I've been using the HttpClient.PostAsJsonAsync extensions and noticed that this method does not set the Content-Type header at all. This omission has caused issues for me and, I suspect, many others, as many APIs will reject requests with a valid JSON body if the Content-Type header is not correctly set.

It is reasonable to expect that a method named PostAsJsonAsync would set the appropriate Content-Type header, as the absence of this header renders the method unusable for many intended use cases where the header is enforced. Therefore, I believe this to be an oversight in the method's design.

### Reference
Here is the link to the relevant source code: 
https://github.com/dotnet/runtime/blob/db4739da4e4565cb01f73cecbc974a05b5cb6b09/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Post.cs#L50

### Possible solution
Adding a content type header of `application/json`, possibly alongside other common headers for such a request could help this  extension method be usable for most common use cases. Additionally, providing clear documentation about which headers will and will not be included when using this method could help eliminate many pitfalls and reduce confusion.

**Comment by MihaZupan** [comment]
It does set the header
https://github.com/dotnet/runtime/blob/db4739da4e4565cb01f73cecbc974a05b5cb6b09/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs#L32

How did you determine that it's missing?

**Comment by Zekiah-A** [comment]
I was comparing a request with PostAsJsonAsync and  one with PostAsync, yet was getting different behaviour

```cs
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

const string apiUrl = "https://vector.profanity.dev";
var jsonOptions = new JsonSerializerOptions()
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase
};

using var httpClient = new HttpClient();
var result = await httpClient.PostAsJsonAsync(apiUrl,
    new { Message = "text upload" },
    jsonOptions);
Console.WriteLine(!result.IsSuccessStatusCode ? $"Error: {result.StatusCode}" : $"Success: {result.StatusCode}");


var content = JsonContent.Create(new { Message = "text upload" }, options: jsonOptions);
content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
var result2 = await httpClient.PostAsync(apiUrl, content);
Console.WriteLine(!result2.IsSuccessStatusCode ? $"Error: {result2.StatusCode}" : $"Success: {result2.StatusCode}");
```
![image](https://github.com/dotnet/runtime/assets/73035340/c2cb952b-9231-47d4-b7e1-a17d0f976c02)

If so, then something else I was not aware of is causing it to act like this and this can be closed

**Comment by MihaZupan** [comment]
There is a slight difference. `JsonContent` uses `application/json; charset=utf-8` by default, not `application/json`.
Your sample will fail if you change it to `new MediaTypeHeaderValue("application/json", "utf-8")`.

I'd file an issue with `vector.profanity.dev` because I don't see a reason why they'd want to block this
