### ISSUE TITLE
When does the.NET SDK release support 26100?

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#102861]
### Description

When does the.NET SDK release support 26100?
.NET SDK 版本什么时候支持 26100？

### Reproduction Steps

Modify the TargetFramework of the Csproj project to 26100, and the NETSDK1140 error is generated
10.0.26100.0 is not a valid TargetPlatformVersion for Windows. Valid versions include:
10.0.22621.0
10.0.22000.0
10.0.20348.0
10.0.19041.0
10.0.18362.0
10.0.17763.0
10.0.22000.0
10.0.20348.0
10.0.19041.0
10.0.18362.0
10.0.17763.0
8.0
7.0

修改 Csproj 项目的 TargetFramework 到 26100，编译时报错 NETSDK1140
10.0.26100.0 不是 Windows 的有效的 TargetPlatformVersion。有效版本包括:
10.0.22621.0
10.0.22000.0
10.0.20348.0
10.0.19041.0
10.0.18362.0
10.0.17763.0
10.0.22000.0
10.0.20348.0
10.0.19041.0
10.0.18362.0
10.0.17763.0
8.0
7.0

### Expected behavior

Supports TargetFramework windows sdk versions up to 26100
支持 TargetFramework windows sdk 版本到 26100

### Actual behavior

不支持 TargetFramework windows sdk 版本到 26100
TargetFramework windows sdk version up to 26100 is not supported

### Regression?

The TargetFramework windows sdk version is changed to 22621
TargetFramework windows sdk 版本修改成 22621

### Known Workarounds

None

### Configuration

.NET 9.0.0-preview4
Windows 10.0.22621.0
X64
None
None

### Other information

Screenshots
![image](https://github.com/dotnet/runtime/assets/49179966/a5333afd-512a-4d4c-a1d5-d3aaeee291de)

**Comment by huoyaoyuan** [comment]
This question belongs to the dotnet/sdk repo.

The Windows SDK package for 26100 has just been released on [NuGet](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref/10.0.26100.1). However, dotnet/sdk repo hasn't adapted it yet: 
https://github.com/dotnet/sdk/blob/99036714da5b8c10ecac8de7b081567ef6330697/src/Installer/redist-installer/targets/GenerateBundledVersions.targets#L1179-L1191

You can try something like `<WindowsSdkSupportedTargetPlatformVersion Include="10.0.26100.0" WindowsSdkPackageVersion="10.0.26100.1" MinimumNETVersion="6.0" />` in your project file. I'm not sure about its validity.

**Comment by huoyaoyuan** [comment]
And also kindly reminder: these small questions are better for being GitHub discussions. For issues, you are not forced to fill the bug template.

**Comment by Gaoyifei1011** [comment]
> This question belongs to the dotnet/sdk repo.
> 
> The Windows SDK package for 26100 has just been released on [NuGet](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref/10.0.26100.1). However, dotnet/sdk repo hasn't adapted it yet: https://github.com/dotnet/sdk/blob/99036714da5b8c10ecac8de7b081567ef6330697/src/Installer/redist-installer/targets/GenerateBundledVersions.targets#L1179-L1191
> 
> You can add this to your project file for manual support:
> 
> ```
>   <ItemGroup>
>     <WindowsSdkSupportedTargetPlatformVersion Include="10.0.26100.0" WindowsSdkPackageVersion="10.0.26100.1" MinimumNETVersion="6.0" />
>     <SdkSupportedTargetPlatformVersion Include="10.0.26100.0" />
>   </ItemGroup>
> ```

Thank you very much for your answer. This temporary solution really solved my problem.

**Comment by Gaoyifei1011** [comment]
> And also kindly reminder: these small questions are better for being GitHub discussions. For issues, you are not forced to fill the bug template.

Thank you for your advice. I'll take note next time and raise this issue with the hope that.NET will support Windows SDK 26100 as soon as possible
