### ISSUE TITLE
.NET 8 application crashes on startup with error code 0x80008093

### ISSUE THREAD

**Issue by BartoszCichecki** [dotnet/runtime#102898]
### Description

I am working on a small open-source [project](https://github.com/BartoszCichecki/LenovoLegionToolkit) and one of the users reports that application crashes on startup. Everything points to an issue with his .NET installation, but we can't figure out what is wrong.

In the Event Viewer user found following entry:

```
Faulting module name: hostpolicy.dll, version: 8.0.624.26715, time stamp: 0x66479d24
Exception code: 0xc0000005
Fault offset: 0x000000000000be57
Faulting process id: 0x0x4EFC
Faulting application start time: 0x0x1DAB2CC3958E1B7
Faulting application path: C:\Users\chris\AppData\Local\Programs\LenovoLegionToolkit\Lenovo Legion Toolkit.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.6\hostpolicy.dll
Report Id: 6ab63ce5-b05d-4d29-82d0-3859df8ded8f
Faulting package full name: 
Faulting package-relative application ID: 
```

We tried reinstalling .NET Runtime 8.0.6 and .NET Desktop Runtime 8.0.6 (which is required by my app) without success.

Installing previous versions of the app does not help.

Original issue reference: https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/1313

### Reproduction Steps

I cannot provide repro steps, since I cannot reproduce the issue. User claims, that application was working one day and suddenly stopped working next day.

### Expected behavior

Application starts correctly.

### Actual behavior

Application crashes with code `0x80008093`.

### Configuration

.NET 8.0.6 is installed on users system and they run Windows 11 Pro 23H2 22631.3593.

Application requires .NET 8 or higher.

### Other information

User tried compiling the source code and running his app using Visual Studio and the following error occurs:

`The program '[31968] Lenovo Legion Toolkit.exe' has exited with code 2147516563 (0x80008093).`

**Comment by BartoszCichecki** [comment]
FYI @cpowell

**Comment by cpowell** [comment]
I have restored application functionality here as follows:

1. Removed .NET SDK 8.0.6 by running Visual Studio Installer and un-checking the category ".NET desktop development".
2. Ensured no other 8.0.6 runtimes were on machine, rebooted.
3. Downloaded 8.0.5 runtimes from https://dotnet.microsoft.com/ and installed them.

App now runs correctly. It seems something in the 8.0.6 update is to blame.

**Comment by BartoszCichecki** [comment]
I am not sure what more information to provide. runtimeconfig.json was correct (same for everyone). The problem only went away after reinstalling/repairing 8.0.6 desktop runtime.

**Comment by BartoszCichecki** [comment]
I will keep this in mind for next time it happens. For now I will close the issue.
