### ISSUE TITLE
Tensor tests failing under jitstress with "Assertion failed 'gtEntryPoint == nullptr'"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#102839]
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=690710&view=results
Example console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-102808-merge-60e78a5ac13e438982/System.Numerics.Tensors.Net8.Tests/1/console.c406e047.log?helixlogtype=result

```
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Numerics.Tensors.Net8.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Tensors.Net8.Tests (found 2305 of 4126 test cases)
  Starting:    System.Numerics.Tensors.Net8.Tests (parallel test collections = on [2 threads], stop on fail = off)

Assert failure(PID 27 [0x0000001b], Thread: 41 [0x0029]): Assertion failed 'gtEntryPoint == nullptr' in 'System.Numerics.Tensors.TensorPrimitives:IndexOfFinalAggregate[uint,System.Numerics.Tensors.TensorPrimitives+IndexOfMinOperator`1[uint]](System.Runtime.Intrinsics.Vector128`1[uint],System.Runtime.Intrinsics.Vector128`1[uint]):int' during 'Importation' (IL size 948; hash 0xc4956a4a; Tier0)

    File: /__w/1/s/src/coreclr/jit/gentree.cpp:19642
    Image: /root/helix/work/correlation/dotnet
```

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib, @tannergooding can you please take a look?

**Comment by tannergooding** [comment]
Should have a fix up shortly. This is the issue I was just discussing in Discord and is actually a long standing issue that exists with `GT_INTRINSIC`, it's just being exposed because `HWIntrinsics` are a bit more prevalent and going down this path as well
