### ISSUE TITLE
RuntimeHelpers.IsReferenceOrContainsReferences should be `where T : allows ref struct`

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#102847]
We've agreed to annotate IsReferenceOrContainsReferences with its T being allows ref struct, but at least on some platforms it currently gives the wrong answer for ref struct Ts that contain refs (false instead of true).

**Comment by stephentoub** [comment]
cc: @AaronRobinsonMSFT

**Comment by EgorBo** [comment]
And `RuntimeHelpers.IsBitwiseEquatable` won't be marked as `allow ref`, right?

**Comment by jkotas** [comment]
> And RuntimeHelpers.IsBitwiseEquatable won't be marked as allow ref, right?

IsBitwiseEquatable is internal method. We can mark is a allow ref if we have a good use for it.
