### ISSUE TITLE
System.Text.Json: custom "Ignore" conditions on properties

### ISSUE THREAD

**Issue by dluc** [dotnet/runtime#102945]
When serializing an object with String properties, I'd like the serialized output to exclude properties having a default value. Currently it's only possible to skip fields that are `null` or `default`.

For instance

```csharp
class SomeClass
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string Description { get; set; } = string.Empty;
}
```

This is serialized to `{ "Description": "" }` rather than `{}`, because `string` `default` is `null`, not the default value provided in code. Note: the default value could be anything, not just empty strings. 

Using a custom writer, turning empty strings to null, doesn't seem to work either:

```csharp
class SomeClass
{
    [JsonConverter(typeof(EmptyStringToNullConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string Description { get; set; } = string.Empty;
}
```

in this case, the JSON writer emits the property name **before** running the custom converter *for the value*, so it's too late to skip the property. One would have to roll back the bytes already emitted, using some complex unicode-aware logic.

--

Is it possible to override the serializer at the property level, having control over the entire property, to say, for example, "**skip this property if the value is 'some value'**"?

If not, could you consider extending `JsonIgnoreCondition`, to ignore the user-provided default value, or better to provide a custom method responsible for this decision, whether to include/exclude a property?

**Comment by elgonzo** [comment]
In my opinion, i don't think a new value for `JsonIgnoreCondition` is a good idea, because your proposal doesn't round-trip: serializing an object with an empty string property, then deserializing the resulting json back to an object will not result in an object with an empty string property again. Therefore, i wager this is better left to custom (application-specific) converters or type resolvers.

In your particular case where serializing empty string properties should be conditional on `WhenWritingDefault`, a custom type resolver can realize this behavior, like this:
```C#
public class EmptyStringIsAlsoDefaultValueTypeResolver : DefaultJsonTypeInfoResolver
{
    public override JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options)
    {
        var typeInfo = base.GetTypeInfo(type, options);
        if (typeInfo.Kind == JsonTypeInfoKind.Object)
        {
            for (int i = 0; i < typeInfo.Properties.Count; i++)
            {
                var prop = typeInfo.Properties[i];
                if (prop.PropertyType == typeof(string))
                {
                    if (prop.ShouldSerialize is not null)
                    {
                        var jsonIgnoreAttr =
                            (prop.AttributeProvider?.GetCustomAttributes(typeof(JsonIgnoreAttribute), false) is not object[] attribs || attribs.Length == 0)
                                ? null
                                : (JsonIgnoreAttribute)attribs[0];

                        //
                        // Only test for empty string when the ignore condition is JsonIgnoreCondition.WhenWritingDefault.
                        //
                        // If the property/field has a [JsonIgnore] attribute, check against the attribute's ignore condition.
                        // Otherwise, check against the ignore condition specified by options.DefaultIgnoreCondition.
                        //
                        if (
                            (jsonIgnoreAttr is null && options.DefaultIgnoreCondition == JsonIgnoreCondition.WhenWritingDefault)
                            || jsonIgnoreAttr?.Condition == JsonIgnoreCondition.WhenWritingDefault
                        ) {
                            //
                            // Test for null and empty string
                            // (this is only applied when the ignore condition for the property is JsonIgnoreCondition.WhenWritingDefault)
                            //
                            prop.ShouldSerialize = (object parentObject, object? propertyValue) => propertyValue is string s && !string.IsNullOrEmpty(s);
                        }
                    }

                }
            }
        }

        return typeInfo;
    }
}
```
This type resolver is aware of ignore conditions set either by a `[JsonIgnore]` attribute or as specified by the given JsonSerializerOptions.

Please also take this example code only as an illustrative example, as i haven't thoroughly tested it. A brief demo showing the type resolver in action: https://dotnetfiddle.net/2d2j9G

**Comment by eiriktsarpalis** [comment]
You can use the `JsonPropertyInfo.ShouldSerialize` delegate to provide any customization you like to individual properties. We don't plan on extending `JsonIgnoreCondition` beyond what has been approved in https://github.com/dotnet/runtime/issues/66490
