### ISSUE TITLE
HttpClient on Android sends wrong content-type header with ByteArrayContent

### ISSUE THREAD

**Issue by rockfordlhotka** [dotnet/runtime#102923]
### Description

In _theory_, the `content-type` header should be automatically set based on the type used to set the `Content` property of an http request. As a result, the `content-type` for a `ByteArrayContent` object should match up to some binary content type value.

```c#
      var client = new HttpClient();
      var content = new ByteArrayContent(serialized);
      var httpResponse = await client.PostAsync(
        "<server url>",
        content);
```

In _practice_ this is what happens:

| Platform | Behavior |
| -- | -- |
| Windows | `content-type` is not set at all |
| Android | `content-type` is set to `application/x-www-form-urlencoded` |

The Windows behavior, while incorrect, at least _works_. 

The Android behavior doesn't work at all, because the aspnetcore server doesn't properly take the binary payload and make it available in `Request.Body` like it should.

The result is that we can't post binary data from a MAUI app on Android to aspnetcore. Accounts of this exist on [stackoverflow](https://stackoverflow.com/questions/77717463/net-maui-httpclient-file-upload-unexpected-end-of-stream) and in [CSLA](https://github.com/MarimerLLC/csla/issues/3791).

### Steps to Reproduce

1. Create an Android MAUI app and a Console app with code like this:

```c#
      var content = new ByteArrayContent(serialized);
      var httpResponse = await client.PostAsync(
        "<server url>",
        content);
```

2. Create an ASP.NET Core web site with a controller like this:

```c#
    [HttpPost]
    public virtual async Task PostAsync([FromQuery] string operation)
    {
        byte[] data;
        using (var requestBodyBuffer = new MemoryStream())
        {
          await Request.Body.CopyToAsync(requestBodyBuffer).ConfigureAwait(false);
          Request.Body.Position = 0;
          data = requestBodyBuffer.ToArray();
        }
    }
```

3. Run the web server
4. Run the console app and it works - `data` has data
5. Run the Android app and it fails - `data` is empty
6. Use something like ngrok to see what's going over the wire - the _exact same binary payload_ goes over the wire in both cases; the http `content-type` value is set wrong from Android and not at all from Windows

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

The workaround is to base64 encode the binary data and send it to the server using a `StringContent` object instead of the broken `ByteArrayContent` type.

Obviously the server endpoint has to accept and decode the string from Android and the binary payload from all other platforms.

**Comment by vitek-karas** [comment]
@simonrozsival is this a docs issue? If so, please move it to the docs repo.

**Comment by simonrozsival** [comment]
@rockfordlhotka @vitek-karas closing in favor of https://github.com/dotnet/docs/issues/41683
