### ISSUE TITLE
[WASM] browser-wasm tests fail with "Cannot box IsByRefLike type"

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#102988]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=695082
Build error leg or test failing: Build browser-wasm linux Release LibraryTests_Threading

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "System.InvalidProgramException.*Cannot box IsByRefLike type",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=695082
**Error message validated:** `[System.InvalidProgramException.*Cannot box IsByRefLike type`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/3/2024 6:16:35 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[695911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695911)|dotnet/runtime|[WasmTestOnFirefox-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695911&view=ms.vss-test-web.build-test-results-tab&runId=17421760&resultId=135060)|dotnet/runtime#101443|
|[696308](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696308)|dotnet/runtime|[WasmTestOnFirefox-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696308&view=ms.vss-test-web.build-test-results-tab&runId=17370026&resultId=135060)|dotnet/runtime#102845|
|[696281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696281)|dotnet/runtime|[WasmTestOnFirefox-ST-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696281&view=ms.vss-test-web.build-test-results-tab&runId=17357280&resultId=135064)|dotnet/runtime#103009|
|[696193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696193)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696193&view=ms.vss-test-web.build-test-results-tab&runId=17343154&resultId=135066)|dotnet/runtime#103005|
|[695634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695634)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695634&view=ms.vss-test-web.build-test-results-tab&runId=17339708&resultId=135070)|dotnet/runtime#102986|
|[696246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696246)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696246&view=ms.vss-test-web.build-test-results-tab&runId=17334174&resultId=135066)|dotnet/runtime#103008|
|[696316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696316)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696316&view=ms.vss-test-web.build-test-results-tab&runId=17309018&resultId=135066)|dotnet/runtime#102475|
|[696268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696268)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Primitives.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696268&view=ms.vss-test-web.build-test-results-tab&runId=17307890&resultId=135066)|dotnet/runtime#102928|
|[696224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696224)|dotnet/runtime|[WasmTestOnChrome-ST-System.Globalization.Calendars.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696224&view=ms.vss-test-web.build-test-results-tab&runId=17306078&resultId=135037)||
|[696179](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696179)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696179&view=ms.vss-test-web.build-test-results-tab&runId=17304850&resultId=135062)|dotnet/runtime#102295|
|[695848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695848)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695848&view=ms.vss-test-web.build-test-results-tab&runId=17304304&resultId=135062)|dotnet/runtime#102977|
|[696139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696139)|dotnet/runtime|[WasmTestOnChrome-MT-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696139&view=ms.vss-test-web.build-test-results-tab&runId=17303684&resultId=100133)|dotnet/runtime#101801|
|[695932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695932)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695932&view=ms.vss-test-web.build-test-results-tab&runId=17301578&resultId=135061)|dotnet/runtime#101547|
|[696078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696078)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696078&view=ms.vss-test-web.build-test-results-tab&runId=17302428&resultId=135064)|dotnet/runtime#102379|
|[696062](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696062)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696062&view=ms.vss-test-web.build-test-results-tab&runId=17301994&resultId=135062)|dotnet/runtime#102967|
|[695418](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695418)|dotnet/runtime|[WasmTestOnChrome-ST-System.Formats.Tar.Manual.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695418&view=ms.vss-test-web.build-test-results-tab&runId=17301598&resultId=135036)|dotnet/runtime#102516|
|[696041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696041)|dotnet/runtime|[WasmTestOnChrome-ST-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696041&view=ms.vss-test-web.build-test-results-tab&runId=17301492&resultId=135032)|dotnet/runtime#102679|
|[695995](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695995)|dotnet/runtime|[WasmTestOnFirefox-ST-System.Runtime.CompilerServices.Unsafe.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695995&view=ms.vss-test-web.build-test-results-tab&runId=17299548&resultId=182353)|dotnet/runtime#102998|
|[696017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696017)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=696017&view=ms.vss-test-web.build-test-results-tab&runId=17299974&resultId=135061)|dotnet/runtime#102992|
|[695970](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695970)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695970&view=ms.vss-test-web.build-test-results-tab&runId=17298562&resultId=135062)|dotnet/runtime#102996|
|[695914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695914)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695914&view=ms.vss-test-web.build-test-results-tab&runId=17297200&resultId=135062)|dotnet/runtime#102994|
|[695900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695900)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695900&view=ms.vss-test-web.build-test-results-tab&runId=17296832&resultId=135062)|dotnet/runtime#102993|
|[695886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695886)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695886&view=ms.vss-test-web.build-test-results-tab&runId=17296532&resultId=135060)|dotnet/runtime#102992|
|[695893](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695893)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695893&view=ms.vss-test-web.build-test-results-tab&runId=17296720&resultId=135062)|dotnet/runtime#102967|
|[695882](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695882)|dotnet/runtime|[WasmTestOnFirefox-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695882&view=ms.vss-test-web.build-test-results-tab&runId=17296506&resultId=135060)|dotnet/runtime#102989|
|[695859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695859)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695859&view=ms.vss-test-web.build-test-results-tab&runId=17295938&resultId=135062)|dotnet/runtime#102991|
|[695799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695799)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695799&view=ms.vss-test-web.build-test-results-tab&runId=17294364&resultId=135062)|dotnet/runtime#102699|
|[695795](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695795)|dotnet/runtime|[WasmTestOnChrome-ST-System.Diagnostics.TextWriterTraceListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695795&view=ms.vss-test-web.build-test-results-tab&runId=17294218&resultId=135028)|dotnet/runtime#102806|
|[695686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695686)|dotnet/runtime|[WasmTestOnChrome-ST-System.Globalization.Hybrid.WASM.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695686&view=ms.vss-test-web.build-test-results-tab&runId=17291880&resultId=135040)|dotnet/runtime#102987|
|[695616](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695616)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695616&view=ms.vss-test-web.build-test-results-tab&runId=17288248&resultId=135064)|dotnet/runtime#102597|
|[695594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695594)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695594&view=ms.vss-test-web.build-test-results-tab&runId=17286790&resultId=135062)|dotnet/runtime#102699|
|[695082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695082)|dotnet/runtime|[WasmTestOnChrome-ST-System.Net.Http.Json.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695082&view=ms.vss-test-web.build-test-results-tab&runId=17269976&resultId=135062)|dotnet/runtime#102963|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|31|32|

**Comment by jkotas** [comment]
```
[07:12:13] fail: System.InvalidProgramException: Cannot box IsByRefLike type 'System.Span`1'
[07:12:13] fail:    at System.Version.TryFormatCore[Char](Span`1 destination, Int32 fieldCount, Int32& charsWritten)
[07:12:13] fail:    at System.Version.System.ISpanFormattable.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
[07:12:13] fail:    at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
```

Introduced by #102795

cc @AaronRobinsonMSFT @stephentoub Looks like Mono is missing byref-like generics support for some patterns.

**Comment by lambdageek** [comment]
@stephentoub please revert for now.  I'm a bit surprised there's a difference.  I think the long term fix for mono is probably quick (most likely `BitCast` needs to be an intrinsic) but on the order of a week, not a few hours.

**Comment by lambdageek** [comment]
It looks like the problem is this code in Unsafe.Bitcast:

```csharp
            if (sizeof(TFrom) != sizeof(TTo) || default(TFrom) is null || default(TTo) is null)
            {
                ThrowHelper.ThrowNotSupportedException();
            }
            return ReadUnaligned<TTo>(ref As<TFrom, byte>(ref source));
```

the test `default(TFrom) is null` generates:

```
	IL_000f:  ldloca.s 1
	IL_0011:  initobj !!0
	IL_0017:  ldloc.1 
	IL_0018:  box !!0
	IL_001d:  brfalse.s IL_0035
```

and I think Mono interpreter doesn't correctly elide the boxing for the `box+brfalse` pattern.
(Also `Unsafe.Bitcast` should probably just be an interpreter intrinsic)

**Comment by lambdageek** [comment]
I have a fix, but for some reason I'm having trouble making a standalone repro.  The only way I get it to fail for sure is using our "xunit on chrome" scenario when this line executes:

https://github.com/dotnet/dotnet/blob/98884e3738c664d0950ed42dd9381a27ae630f43/src/source-build-externals/src/xunit/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs#L21

Doing the same thing in a standalone sample doesn't cause a crash.  As far as I can tell it's not due to IL differences.  It might be different inlining choices in the interpreter, but I don't see how that would alter what the interpreter sees.  very strange.
