### ISSUE TITLE
.NET connectivity issue, outbound connection timeout

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/runtime#103017]
### Description

This is the wierdest issue. Since a few weeks, I started getting outbound connection timeout on my development machine (running Garuda Linux), although once deployed it works perfectly fine on the Debian server.

To diagnose this problem, I created a simple console app with this code
```
var website = "https://perdu.com";
Console.WriteLine($"Querying {website}...");
using var client = new HttpClient();
client.Timeout = TimeSpan.FromSeconds(5);
var value = await client.GetStringAsync(website);
Console.WriteLine(value);
```

(anything wrong with the code?)

Console app times out in Garuda Linux. Booted from USB into a clean Live Boot environment, console app times out. Booted from Live Boot environments of Manjaro, Fedora and Ubuntu, I reproduce the timeout in all those environment. Booted into a Windows on USB, it times out also!

In Fedora, I tried downgrading .NET to v6, and it times out. Other people don't seem to be having the issue. The issue doesn't occur when running in a VM.

My laptop is Predator PH315-53.

We've discarded the OS. We've discarded the framework version. I tried querying direct IP address so we discarded DNS issue. I'm absolutely clueless where the issue could be at this point. Internet connection is a standard home fiber optic WiFi modem with Telmex in Mexico. No proxy or anything special.

### Reproduction Steps

1. Create a console app with the code above
2. Run the app

### Expected behavior

It should display the response from the server, equivalent of 'curl'

### Actual behavior

Timeout after 5 seconds.

### Regression?

It has been working for years, up until a few weeks ago.

### Known Workarounds

I deploy into Production and it works... cross my fingers since I can't test locally. This also affects .NET desktop applications that I had published. Haven't seen any other system problem other than .NET

### Configuration

I tried .NET 6 and .NET 8, problem persists.
I tried Garuda, Manjaro, Fedora, Ubuntu and Windows 10.
Architecture: x64
It looks hardware or environment dependent or something.

### Other information

Absolutely clueless. I've exhausted all my options.

Here's the output of `curl` and `dig` on my computer
```
> curl perdu.com
<html><head><title>Vous Etes Perdu ?</title></head><body><h1>Perdu sur l'Internet ?</h1><h2>Pas de panique, on va vous aider</h2><strong><pre>    * <----- vous &ecirc;tes ici</pre></strong></body></html>

> dig perdu.com
; <<>> DiG 9.18.26 <<>> perdu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6144
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;perdu.com.                     IN      A

;; ANSWER SECTION:
perdu.com.              263     IN      A       104.21.5.178
perdu.com.              263     IN      A       172.67.133.176

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Jun 03 21:17:38 EST 2024
;; MSG SIZE  rcvd: 70
```

Ran [wtrace](https://github.com/lowleveldesign/dotnet-wtrace) on the console app and got this. Not seeing anything useful here.

```
11:14:08.2429 ConsoleApp1 (47722.47739) Network/SocketInfo info [/#47722/1/59/] (null) (CreateSocket) SafeSocketHandle:17653682(0x3E)
11:14:08.2432 ConsoleApp1 (47722.47739) Network/SocketInfo info [/#47722/1/59/] Socket#35320229 (SetSocketOption) optionLevel:IPv6 optionName:IPv6Only optionValue:0
11:14:08.2434 ConsoleApp1 (47722.47739) Network/SocketInfo info [/#47722/1/59/] Socket#35320229 (SetSocketOption) SetSockOpt returns errorCode:Success
11:14:08.2434 ConsoleApp1 (47722.47739) Network/SocketInfo info [/#47722/1/59/] Socket#35320229 (SetSocketOption) optionLevel:Tcp optionName:NoDelay optionValue:1
11:14:08.2434 ConsoleApp1 (47722.47739) Network/SocketInfo info [/#47722/1/59/] Socket#35320229 (SetSocketOption) SetSockOpt returns errorCode:Success
11:14:08.2437 ConsoleApp1 (47722.47739) Network/SocketConnectedAsyncDns info [/#47722/1/59/] Socket#35320229
11:14:08.2438 ConsoleApp1 (47722.47739) Loader/AssemblyLoadStart info [/#47722/1/59/18/] name: 'System.Net.NameResolution, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a',requested by: 'System.Net.Sockets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
11:14:08.2439 ConsoleApp1 (47722.47739) Loader/KnownPathProbed info [/#47722/1/59/18/] '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.5/System.Net.NameResolution.dll' source: Microsoft.Diagnostics.Tracing.EventPipeEventSource, runtime: #0
11:14:08.2439 ConsoleApp1 (47722.47739) Loader/ResolutionAttempted error [/#47722/1/59/18/] message: 'Could not locate assembly', stage: FindInLoadContext
11:14:08.2439 ConsoleApp1 (47722.47739) Loader/ResolutionAttempted info [/#47722/1/59/18/] '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.5/System.Net.NameResolution.dll' stage: ApplicationAssemblies
11:14:08.2439 ConsoleApp1 (47722.47739) Loader/AssemblyLoadFinished info [/#47722/1/59/18/] name: 'System.Net.NameResolution, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', requested by: 'System.Net.Sockets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', duration: 0.088ms
11:14:08.2440 ConsoleApp1 (47722.47739) Loader/DomainModuleLoad info [/#47722/1/59/] '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.5/System.Net.NameResolution.dll' module type: managed
11:14:08.3017 ConsoleApp1 (47722.47741) Loader/AssemblyLoadStart info [/#47722/1/59/19/] name: 'System.Runtime.Intrinsics, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51',requested by: 'System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
```

One more thing. I recently had an hardware issue, internal webcam cable was loose, so the webcam didn't work, and the computer jammed on boot and needed 10 minutes to get to the OS and then worked fine. Now both the boot and the webcam work.

Could there be a very specific hardware issue or condition that could cause an issue only with .NET? Such a rare condition that it never would have been diagnosed or fixed ever before? Can't think of anything else.

**Comment by ManickaP** [comment]
Could you  try disable IPv6 usage in .NET: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_system_net_disableipv6

Otherwise, please do a packet capture (WireShark) and record the faulty situation.

**Comment by mysteryx93** [comment]
Works. Still need packet capture?

```
DOTNET_SYSTEM_NET_DISABLEIPV6=1 ./ConsoleApp1 
Querying http://www.perdu.com...
<html><head><title>Vous Etes Perdu ?</title></head><body><h1>Perdu sur l'Internet ?</h1><h2>Pas de panique, on va vous aider</h2><strong><pre>    * <----- vous &ecirc;tes ici</pre></strong></body></html>
```

**Comment by ManickaP** [comment]
I don't remember exactly the explanation (@antonfirsov might know), but sometimes IPv6 looks like it's supported (at least what we check for in the OS), but doesn't actually work. 
So there's nothing we can do about it. If you need to support these environments permanently, you can put `AppContext` switch directly in your code to disable the IPv6.

I hope this answers your question and we can close this issue.

**Comment by mysteryx93** [comment]
So what would have changed in the past few weeks, my ISP would have changed something that broke IPv6 support?

There's been a lot of outages in the area lately btw; both electric and also ISP outages.

**Comment by mysteryx93** [comment]
I reported the issue to the ISP.

It's not everyday you get to blame technical issues on solar activity!

Still, why are only .NET affected by this? I saw just one app that had connectivity problems, but otherwise, the system runs fine. Perhaps the situation could be handled better.

But if it wasn't for .NET failing so spectacularly, it would have been impossible to identify this ISP-level problem with IPv6, and that's not the kind of issues that should remain unreported.

**Comment by wfurt** [comment]
That goes to defaults @mysteryx93. I think `curl` prefers IPv4, .NET made choice while back to default to IPv6 where the underlying OS claims support for it.

**Comment by mysteryx93** [comment]
`curl -6 perdu.com`

Indeed fails miserably... hangs forever

**Comment by mysteryx93** [comment]
btw thanks for the amazing and prompt response. I literally spent weeks on that one.

**Comment by mysteryx93** [comment]
The problem has been resolved at the ISP

    curl -6 perdu.com
    curl -6 https://www.google.com

Works.

This, however, freezes there without giving an output but works fine in the browser.

```
curl -v -4 https://store.hanumaninstitute.com/api/app-version?app=1&os=linux-x64

* Host store.hanumaninstitute.com:443 was resolved.
* IPv6: (none)
* IPv4: 155.138.219.158
*   Trying 155.138.219.158:443...
* Connected to store.hanumaninstitute.com (155.138.219.158) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=store.hanumaninstitute.com
*  start date: May  3 15:27:56 2024 GMT
*  expire date: Aug  1 15:27:55 2024 GMT
*  subjectAltName: host "store.hanumaninstitute.com" matched cert's "store.hanumaninstitute.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET /api/app-version?app=1 HTTP/1.1
> Host: store.hanumaninstitute.com
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Wed, 26 Jun 2024 16:17:06 GMT
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host store.hanumaninstitute.com left intact
```

And this stays stuck there.
```
curl -v -6 https://store.hanumaninstitute.com/acurl -v -6 https://store.hanumaninstitute.com/api/app-version?app=1&os=linux-x64pi/app-version?app=1&os=linux-x64

* Host store.hanumaninstitute.com:443 was resolved.
* IPv6: 2001:19f0:5401:34d:5400:4ff:fee3:fe9
* IPv4: (none)
*   Trying [2001:19f0:5401:34d:5400:4ff:fee3:fe9]:443...
* connect to 2001:19f0:5401:34d:5400:4ff:fee3:fe9 port 443 from 2806:10be:d:6854:9fb7:f71:7aaa:cf71 port 43154 failed: Connection timed out
* Failed to connect to store.hanumaninstitute.com port 443 after 135326 ms: Couldn't connect to server
* Closing connection
```

Note that IPv6 isn't actually available in Mexico except for commercial lines, but they fixed the network to let the OS know what works or not.

Got any idea why it would fail ONLY for the .NET service URL?

**Comment by mysteryx93** [comment]
Here's the packet capture, for both the ipv4 and ipv6 requests

[Request-Capture.zip](https://github.com/user-attachments/files/15994437/Request-Capture.zip)
