### ISSUE TITLE
NET SDK does not support targeting .NET 9.0. 

### ISSUE THREAD

**Issue by PaskalSunari** [dotnet/runtime#103083]
### Targeting the .net 8
I have created the project with the below commands and changed the configuration of program.cs..But its throwing the build error

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	NETSDK1045	The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download	MyFirstDotNet9WebApp	C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	166

**Comment by colejohnson66** [comment]
You are using the .NET 8 SDK. You cannot target .NET 9 without the .NET 9 SDK.

**Comment by MagicAndre1981** [comment]
Install 9.0 SDK first:

https://dotnet.microsoft.com/en-us/download/dotnet/9.0
