### ISSUE TITLE
Unoptimal hash code combine in TypeHashingAlgorithms.ComputeMethodHashCode

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#103070]
There's a TODO in the code:

https://github.com/dotnet/runtime/blob/b438888c5504c8dafe3746393ab76f3e5e1eff6d/src/coreclr/tools/Common/TypeSystem/Common/TypeHashingAlgorithms.cs#L229-L234

Notably, this comes up as a sore spot in my profiles:

![image](https://github.com/dotnet/runtime/assets/1764393/3f503d76-5716-475f-9284-a9dbb18cb611)

Changing to `HashCode.Combine` yields about >20% less hash collisions in this method alone:

<img width="907" alt="image" src="https://github.com/dotnet/runtime/assets/1764393/d0a8792d-82cc-4d3c-aaf0-87760e7acb99">

This compilation speed improvement is quite noticable.

Unfortunately, there seems to be some dependency on the hash combining algorithm somewhere in the code because this produces an executable that fails to run at runtime:

```
Process terminated. Failed to create generic virtual method implementation

Declaring type: Microsoft.Extensions.Options.OptionsBuilder`1<Microsoft.Extensions.Options.StartupValidatorOptions>
Method name: Configure
Instantiation:
  Argument 00000000: Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.DependencyInjection.MetricsServiceExtensions+NoOpOptions>

   at System.RuntimeExceptionHelpers.FailFast(String, Exception, String, RhFailFastReason, IntPtr, IntPtr) + 0x2b0
   at Internal.Runtime.TypeLoader.TypeLoaderEnvironment.ResolveGenericVirtualMethodTarget(RuntimeTypeHandle, RuntimeMethodHandle) + 0x210
   at System.Runtime.TypeLoaderExports.<>c.<GVMLookupForSlotSlow>b__8_0(IntPtr context, IntPtr signature, Object contextObject, IntPtr& auxResult) + 0x31
   at System.Runtime.TypeLoaderExports.CacheMiss(IntPtr, IntPtr, RuntimeObjectFactory, Object) + 0x28
   at System.Runtime.TypeLoaderExports.GVMLookupForSlotSlow(Object, RuntimeMethodHandle) + 0x4e
   at System.Runtime.TypeLoaderExports.GVMLookupForSlot(Object, RuntimeMethodHandle) + 0x9a
   at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.ValidateOnStart[TOptions](OptionsBuilder`1) + 0x6e
   at Microsoft.Extensions.DependencyInjection.MetricsServiceExtensions.AddMetrics(IServiceCollection) + 0x47
   at Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient(IServiceCollection) + 0x26
   at MailClient.Program.SetUpDependencyInjection() + 0x2a9
   at MailClient.Program.Main(String[] args) + 0xd2
```

**Comment by huoyaoyuan** [comment]
At which level are you replacing with `HashCode.Combine`? I can't imagine anything faster than XOR if you only replace the `ComputeMethodHashCode` method.

**Comment by filipnavara** [comment]
> I can't imagine anything faster than XOR if you only replace the `ComputeMethodHashCode` method.

The problem is not the speed of the hashing itself. That's done only once per each method. The problem are the collisions that are caused by matching hashes and the simple XOR is extremely bad at that.

The profile above is with `TypeHashingAlgorithms.ComputeMethodHashCode` replaced to use `HashCode.Combine`. There are places in unmanaged CLR/R2R code that depend on the stable hash algorithm at the moment. I expected these places not to exist on NativeAOT since the relevant part of the code links to System.Private.TypeLoader.dll which uses the shared `TypeHashingAlgorithms` implementation, but apparently there is still some dependency.

**Comment by filipnavara** [comment]
> `HashCode.Combine` is randomized. It does not produce a stable hashcode.

Huh, that explains why it didn't work. I guess I should file a documentation issue since the current [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.hashcode.combine?view=net-8.0) doesn't mention this.

**Comment by vcsjones** [comment]
> . I guess I should file a documentation issue since the current [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.hashcode.combine?view=net-8.0) doesn't mention this.

It is, but in the class remarks. https://learn.microsoft.com/en-us/dotnet/api/system.hashcode?view=net-8.0#remarks

**Comment by filipnavara** [comment]
@vcsjones Thanks! I just searched for "HashCode.Combine" directly.

I went a bit more down the rabbit hole analyzing this and I am not necessarily sure that changing the hash function is a good enough fix.

In this particular instance we are running into a huge instance of `LockFreeReaderHashtable` that is particularly big and also quite full. It uses an 2^n sized hashtable with open addressing and double hashing in case of collision. The table is resized when a predetermined fill threshhold is reached. Notably, this is different from regular `Dictionary<K, V>` that uses prime-sized hash table, open addressing, linear probing, and detects high collision rates and resizes.

I don't have the numbers off-hand, but in the pessimistic case where the hashtable is nearly full, and you search for an element that is NOT in the hashtable (yet), you can end up searching linearly up to 60% (resize threshhold) of the table before finding out that the element is not there.

`NodeFactory` overwhelmingly uses the `LockFreeReaderHashtable` in a `GetOrAdd`/`GetOrCreateValue` fashion which lazily creates the values if they are not found. That ends up hitting the pessimistic lookup case rather often and badly no matter the quality of the hash code functions.

Overall, this data structure with these parameters doesn't scale up well. We can likely tweak some parameters of the 
Hashtable algorithm to get significant improvements but maybe a different approach is in order. Ideas that come to mind:

- Keep track of the maximum collision steps when adding an item. When looking up an item, stop the open addressing lookup after the said number of steps.
- Add a bloom filter if the hashtable gets too big to quickly answer that a given item is not in the set.

Both of these algorithms may be difficult to implement with the required concurrency requirements. That said, my benchmarks show the bottlenecks overwhelmingly happening in parts of the execution which are single-threaded. I am not necessarily good on algorithms, so any additional input is welcome.

**Comment by jkotas** [comment]
> you can end up searching linearly up to 60% (resize threshhold)

This can only happen when the hashcodes are poorly distributed or when you are really unlucky.

I think fixing the hashcodes should take care of this problem.

**Comment by filipnavara** [comment]
> This can only happen when the hashcodes are poorly distributed or when you are really unlucky.

They are definitely poorly distributed. There's no question about that. It may not be the only issue though and I don't have enough data to confirm/refute that yet.

I started tracking the collision numbers on Add (on a fairly large app build):
- `RuntimeDeterminedTypeKeyHashtable` gets over 2000 collisions but they do go down during expansion which suggests that they are not identical hash codes.
- `MethodEntrypointHashtable` get over 14000 collisions and they only go up.

For scale, the regular `Dictionary` uses a 100 as collision threshold for rehashing.

**Comment by filipnavara** [comment]
I may have found one of the root causes. WinForms generates a large number of `[System.Windows.Forms]SourceGenerated.EnumValidator Validate` methods. They differ with the parameters signature but that's never taken into account in the `MethodDesc` hash, so they all cause a collision.

**Comment by jkotas** [comment]
> For scale, the regular Dictionary uses a 100 as collision threshold for rehashing.

Nit: This threshold is used to switch to more expensive randomized string hash code and only for string keys. It is done for security reasons (protection against DoS attacks).

**Comment by filipnavara** [comment]
Few other notable collisions (same hash, but also same type and name):
```
    104 [System.Windows.Forms]SourceGenerated.EnumValidator Validate = 165151430
    107 [S.P.CoreLib]System.Runtime.CompilerServices.Unsafe Add = -821482047
    119 [S.P.CoreLib]Internal.Metadata.NativeFormat.MdBinaryReader Read = -456562824
    132 [S.P.CoreLib]System.Runtime.CompilerServices.Unsafe As = 1267830177
    174 [S.P.CoreLib]System.Runtime.CompilerServices.Unsafe AsRef = -693195293
    196 [S.P.CoreLib]Internal.Runtime.MethodTable Of = -396193247
    232 [S.P.CoreLib]System.Runtime.CompilerServices.Unsafe As = -740372691
    392 [S.P.CompilerGenerated]Internal.CompilerGenerated.<Module> CalliMarshallingMethodThunk = 1205279480
  21913 [S.P.CompilerGenerated]Internal.CompilerGenerated.<Module> DynamicInvoke = 292316103
```

First column is the number of such `MethodDesc`s created.

**Comment by jkotas** [comment]
For `MethodEntrypointHashtable` and similar hashtables that use MethodDesc as the key, the problem can be worked around by switching to object hashcode. Change these two lines https://github.com/dotnet/runtime/blob/fb1fe7f3481fc88fa477268c18d60d824b83c314/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs#L922-L923 to use RuntimeHelpers.GetHashCode. It is not the proper fix, but it would be better than nothing.

**Comment by filipnavara** [comment]
Is there runtime dependency on stability of the `DynamicInvokeMethodThunk` hash code?

This nearly removes the bottleneck:
```diff
--- a/src/coreclr/tools/Common/TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.cs
+++ b/src/coreclr/tools/Common/TypeSystem/IL/Stubs/DynamicInvokeMethodThunk.cs
@@ -112,6 +112,11 @@ public override MethodSignature Signature
             }
         }

+        protected override int ComputeHashCode()
+        {
+            return base.ComputeHashCode() ^ _targetSignature.GetHashCode();
+        }
+
         public override string Name => "DynamicInvoke";

         public override string DiagnosticName => "DynamicInvoke";
```

<img width="911" alt="image" src="https://github.com/dotnet/runtime/assets/1764393/c06e5060-ced5-416e-8798-d6595e8c375b">



I tried using `RuntimeHelpers.GetHashCode` but it seemingly didn't have the expected impact (measured by wall clock). I'll run it through profiler later on.
