### ISSUE TITLE
[wasi] Extract minimal build infrastructure to WasmSDK

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#103038]
This would allow "demo" mode the same as we have for browser.

**Comment by pavelsavara** [comment]
I think we don't want "demo" to exist ? Besides DLLImport needs LLVM

**Comment by maraf** [comment]
> I think we don't want "demo" to exist ?

Can you ellaborate, please? Since we have a browser demo mode and if we agree that there is a way to run something before installing quite large tooling. Is wasi different case?

**Comment by pavelsavara** [comment]
It creates much larger test and configuration space to support. And we know that the performance without re-link is not great. Let's not make the same mistake again.
