### ISSUE TITLE
Corrupting exceptions are not turned into fail fasts 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#103018]
## Repro:

It should not be possible to catch corrupting exceptions like AccessViolationExceptions.

```csharp
using System;

class Test
{
    static unsafe void Main()
    {
        try {
            *(int*)0x1235678 = 0x12345;
        }
        catch (Exception e) {
            Console.WriteLine("Here");
        }
    }
}
```

## Actual behavior

`Here`

## Expected behavior

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Test.Main()
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
cc @janvorli @VSadov

**Comment by jkotas** [comment]
This blocks post-mortem debugging of CI crashes caused by access violations (e.g. see #102919).

**Comment by janvorli** [comment]
I've found the culprit, missing handling of access violation as a failfast in the GetClasslibException. I'll fix it.
