### ISSUE TITLE
error MSB3971: The reference assemblies for ".NETFramework,Version=v8.0" were not found

### ISSUE THREAD

**Issue by abdi2000** [dotnet/runtime#103059]
I am getting below error----

/root/.dotnet/sdk/3.1.426/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v8.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.

So I am trying to upgrade my project to .Net 8.0 and I have checked that the required SDK is installed on my machine by the command dotnet --list-sdks.

I also can build solution locally after upgrading my project to .Net 8.0. Now when I am doing Octopus Deploy, the deployment is failing with the above error.

My Visual Studio version is 17.10.0

**Comment by huoyaoyuan** [comment]
Note that the correct moniker for .NET 8 is `.NETCoreApp,Version=v8.0`. The issue may belong to Octopus Deploy that is using .NET Framework tooling.

**Comment by vcsjones** [comment]
> /root/.dotnet/sdk/3.1.426/

It sounds like a very old SDK is being used. Do you have a global.json forcing the use of .NET Core 3.1 SDK?

**Comment by abdi2000** [comment]
Thanks for all your comments. Basically, there were other dependent scripts in Octopus Deploy which needed some modification after upgrading the framework version in VS. Doing those changes fixed the issue. Thanks.
