### ISSUE TITLE
[SIMD] Blazor Web App will not load webassembly component on virtualized machines with Chromium browser

### ISSUE THREAD

**Issue by mtbayley** [dotnet/runtime#103072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't think of how this is possible, but I get this message on startup of my published AOT compiled Blazor Web App. Some machines have no problem loading the site, but some machines show this error consistently.

Any help on where to look would be appreciated

### Exceptions (if any)

```
blazor.web.js:1  Error: AggregateException_ctor_DefaultMessage (EndOfStringNotFound Path: $['__internal__AntiforgeryRequestToken'] | LineNumber: 0 | BytePositionInLine: 2340.)
    at Jn (dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:31614)
    at Tl (dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:182415)
    at 0fd5c22a:0x27ba236
    at 0fd5c22a:0x27bbcf8
    at 0fd5c22a:0x27c169c
    at 0fd5c22a:0x2f2f5a4
    at 0fd5c22a:0x31d0e0e
    at 0fd5c22a:0x31ede66
    at 0fd5c22a:0x31cd780
    at 0fd5c22a:0x31c0b7d
callEntryPoint @ blazor.web.js:1
await in callEntryPoint (async)
ti @ blazor.web.js:1
await in ti (async)
ei @ blazor.web.js:1
startWebAssemblyIfNotStarted @ blazor.web.js:1
resolveRendererIdForDescriptor @ blazor.web.js:1
determinePendingOperation @ blazor.web.js:1
refreshRootComponents @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
setTimeout (async)
rootComponentsMayRequireRefresh @ blazor.web.js:1
onDocumentUpdated @ blazor.web.js:1
Ki @ blazor.web.js:1
Ji @ blazor.web.js:1
(anonymous) @ (index):770
```

### .NET Version

8.0.6

**Comment by javiercn** [comment]
@lewing FYI

**Comment by mtbayley** [comment]
Another update:
The machines that it fails on are all **virtualized**. All physical machines I have tested so far have no issues

**Comment by mtbayley** [comment]
Setting `WasmEnableSIMD` to false works around the issue. I can't understand why. SIMD should be supported by all major browsers

**Comment by maraf** [comment]
Looks similar as https://github.com/dotnet/runtime/issues/96004

**Comment by pavelsavara** [comment]
This is likely that the VM + browser can't use SIMD. The workaround is to disabler the SIMD. 

See https://github.com/dotnet/runtime/blob/main/src/mono/wasm/features.md on how to do it
