### ISSUE TITLE
NoWorkload-NoWebcil-ST-Wasm.Build.Tests.WorkItemExecution

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#103084]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=697153
Build error leg or test failing: Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadRequiredForBuild
Pull request: https://github.com/dotnet/runtime/pull/103010

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "The \"RestoreTask\" task returned false but did not log an error",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

/cc @lewing 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=697153
**Error message validated:** `[The "RestoreTask" task returned false but did not log an error`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 6/6/2024 7:54:55 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[698584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698584)|dotnet/runtime|[Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadNotRequiredForInvariantGlobalization](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698584&view=ms.vss-test-web.build-test-results-tab&runId=17382074&resultId=100005)|dotnet/runtime#103088|
|[697153](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697153)|dotnet/runtime|[Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadRequiredForBuild](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697153&view=ms.vss-test-web.build-test-results-tab&runId=17350356&resultId=100006)|dotnet/runtime#103010|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|2|2|

**Comment by maraf** [comment]
Missing `wasm-tools` workload is expected by some tests.
The actual error in both cases is `error MSB4181: The "RestoreTask" task returned false but did not log an error. `

**Comment by maraf** [comment]
Not sure why the known issue validation has failed

**Comment by ilonatommy** [comment]
Remains closed in favor of https://github.com/dotnet/runtime/issues/103114 that got successfully validated.
