### ISSUE TITLE
Environment variable DOTNET_DbgEnableMiniDump=1 doens't work when unhandled exception occurs in worker thread

### ISSUE THREAD

**Issue by KurokiYukari** [dotnet/runtime#103000]
### Description

I run a .NET application with environment variable DOTNET_DbgEnableMiniDump=1. If an unhandled exception 
occurs in main thread, the dump file is generated correctly. But if an unhandled exception occurs in worker thread, no dump file is generated.

### Reproduction Steps

using powershell on windows:
1. `dotnet new console`
2. Change Program.cs to
``` cs
var thread = new Thread(() =>
{
    throw new Exception();
});
thread.Start();
thread.Join();
```
3. run `$env:DOTNET_DbgEnableMiniDump=1`
4. run `dotnet run`

### Expected behavior

Dump is generated and placed in `%LocalAppData%/Temp` dir.

### Actual behavior

No dump is generated. 
Console output:
```
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at Program.<>c.<<Main>$>b__0_0() in C:\dumptest\Program.cs:line 3
```

### Configuration

1. Which version of .NET is the code running on? - 8.0.300
2. What OS and version, and what distro if applicable? - windows11  23H2 
3. What is the architecture (x64, x86, ARM, ARM64)? - x64
4. Do you know whether it is specific to that configuration? -no. I have tried .NET 6, but also no dump file is generated.

**Comment by hoyosjs** [comment]
threadpool threads don't exhibit this behavior: 

```csharp
await Task.Run(async () =>
{
    await Task.Yield();
    throw new Exception();
});
```

**Comment by KurokiYukari** [comment]
@hoyosjs I tried threadpool. it also doesn't work:
``` cs
ThreadPool.QueueUserWorkItem(state =>
{
    throw new Exception();
});
```
Task works because unhandled exceptions that are thrown by user code that is running inside a task are propagated back to the calling thread(main thread)

**Comment by mikem8361** [comment]
It works in .NET 9.  I did get it to repro on .NET 8.  I'm not sure what change went into 9.0 that fixes this yet.
```
Hello, World!

Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at Program.<>c.<<Main>$>b__0_0() in C:\sd\builds\background\Program.cs:line 7
[createdump] Writing minidump with heap for process 14676 to file c:\sd\builds\background\createdump.9.0.0.dmp
[createdump] Dump successfully written in 922ms
```

**Comment by mikem8361** [comment]
It looks like this was fixed as part of the new exception handling support. Not sure what part or where, but on .NET 9 if I disable the new exception handling with `set DOTNET_LegacyExceptionHandling=1` dumps are not generated anymore.

@janvorli any thoughts?

**Comment by janvorli** [comment]
I think that we need to call CreateCrashDumpIfEnabled here if we want to make it work with legacy EH:
https://github.com/dotnet/runtime/blob/b2b0db0c470eba512d358dcf3d359488083e82a8/src/coreclr/vm/excep.cpp#L4873

I've tried it and it worked.

**Comment by mikem8361** [comment]
Thanks Jan.  We need to decide if this fix should go into .NET 9 for the legacy EH and if it should go into .NET 8 servicing? 

@tommcdon?

**Comment by tommcdon** [comment]
For correctness I think we should try to fix the legacy exception scenario for .NET 9, and consider this
for .NET 8 servicing if we have a customer request.
