### ISSUE TITLE
WasmTestOnChrome-* test failures

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#103057]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=696281
Build error leg or test failing: WasmTestOnChrome-MT-System.Net.Http.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/103009

## Error Message

MONO_WASM: The type initializer for 'Xunit.Sdk.XunitTestFrameworkDiscoverer' threw an exception

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "MONO_WASM: The type initializer for 'Xunit.Sdk.XunitTestFrameworkDiscoverer' threw an exception",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=696281
**Error message validated:** `[MONO_WASM: The type initializer for 'Xunit.Sdk.XunitTestFrameworkDiscoverer' threw an exception`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/5/2024 12:39:35 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by tarekgh** [comment]
This might be duplicate of https://github.com/dotnet/runtime/issues/102988 but my PR https://github.com/dotnet/runtime/pull/103009 was still failing with same tests even when https://github.com/dotnet/runtime/issues/102988 is logged and linked to my PR.

**Comment by ViktorHofer** [comment]
@tarekgh I'm closing this issue as there are no direct hits in the last months. For anyone reading this, feel free to re-open if the issue still occurs.
