### ISSUE TITLE
Improving support in .NET for W3C Baggage standard

### ISSUE THREAD

**Issue by kalyanaj** [dotnet/runtime#103172]
The W3C Baggage spec (https://www.w3.org/TR/baggage/) reached Candidate Recommendation state as of 30 May 2024. Depending on the feedback from implementers, we are targeting to get to final recommendation state by end of 2024 / early 2025.

This is a tracking issue to support this in .NET (e.g., the new baggage header as currently only the older CorrelationContext http header is supported in .NET).

**Comment by tarekgh** [comment]
Thanks @kalyanaj for logging the issue. we have https://github.com/dotnet/runtime/issues/45496 tracking the same issue.
