### ISSUE TITLE
[API Proposal]: Disposable Enumerable

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#103123]
### Background and motivation

I suggest adding to Linq the ability to create Enumerables that can be read once. In some cases, if you read an Enumerable more than once, it can lead to incorrect behavior.

[example](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AdQFMAjAbj0JPIGEB7AGw6oGNgBLNlADODfMVIAWMU1JkAMvygBHGZgCcACgBE2gJRi8eAG4BDMETBVhRALxEAolAgBbKmFM1uZAEqmoAOZUmpgwmAR6ZACCwj5UpnAA8lAcAJ5Oru6e3Mk8wQZGuABmbFamPAAWmmYW/MBULkRKltZ6AN4AvoV4RCQAzE1Q9WBF5VREAJJxCclpuVQAPAAqAHxEIMx9y2ttRF24vagDpABsJOhES9bAPURtt72Hx5hnU/FJKanz20Qx0x9pDJuDxeKjfVaaYAVfg2UhbVZEKhQPQPR73A6PTGHADsRCgVAA7kR/rN0s5gdkwVA8ttNEiChjMfteszzsT3qSgVlQeCVpo4T96etJiTPrzbuisUQaGxOEQAPqVXgAawcAA9eBB6mIpUdJlyPMBSj8AOJUYAG0xGsCaFGMtGoqX8IpETSKioq9Wa+p2ezASBUPREKFgNhE/FE9V5AAOAiEOiW0JsSMyIO4LQSQjSRCEeX0Oqlj3dno1PC14z9AYLhZIuKRZDNFvJWWtturj32jv1zcNpU2DfNltbdqlkprztdxZ4qtL5d9wYDQZDYbxhMcapjcagCaTiJ7lIzcCzqRz1Ko+a7mKnM+9FYXECo7d1dagA6bqatpTbXdZHSAA)

### API Proposal

```csharp
 public interface IReadOnlyOnce<T> : IEnumerable<T> { }
  public static class Test
  {
      public static IReadOnlyOnce<T> AsReadOnlyEnumerableOnce<T>(this IEnumerable<T> en)
      {
          return new ReadOnlyEnumerableOnce<T>(en);
      }
  }
  class ReadOnlyEnumerableOnce<T>(IEnumerable<T> en) : IReadOnlyOnce<T>
  {
      bool _checkExecute;
      public IEnumerator<T> GetEnumerator()
      {
          if (_checkExecute == true) throw new Exception("This enumerable readonly once");
          _checkExecute = true;
          return en.GetEnumerator();
      }

      IEnumerator IEnumerable.GetEnumerator()
      {
         if (_checkExecute == true) throw new Exception("This enumerable readonly once");
          _checkExecute = true;
          return en.GetEnumerator();
      }
  }
```

### API Usage

```csharp
var res = Enumerable.Range(1,10).AsReadOnlyEnumerableOnce();

foreach(var item in res){}
foreach(var item in res){}

```

### Alternative Designs

-

### Risks

-

**Comment by eiriktsarpalis** [comment]
How could an interface such as the one you're proposing guarantee such an invariant? This can only stem from implementations. What's more the Enumerable/Enumerator pattern is explicitly designed in a way that canonically permits multiple enumerations of the same source, so exposing such a method would contravene this design philosophy.

**Comment by Mr0N** [comment]
> How could an interface such as the one you're proposing guarantee such an invariant? T

Just like IEnumerable, approximately

**Comment by eiriktsarpalis** [comment]
Why introduce a new interface then?

**Comment by Mr0N** [comment]
> Why introduce a new interface then?

To indicate that this enumeration is one-time, can do it like this

if(obj is IReadOnlyOnce<string>){}

**Comment by eiriktsarpalis** [comment]
I don't understand. What would happen in the `else` branch in that case? Would you be enumerating twice?

**Comment by Mr0N** [comment]
> `se` branch in that case? Would you be enumerating twice?

Well, you can split it into different thread, like an IEnumerable or something similar. Essentially, it's like a Stream where some Streams don't support moving the Position, and they have different names, so you can understand that this Stream doesn't allow moving the Position.

**Comment by eiriktsarpalis** [comment]
It's not something we would consider for inclusion in Linq. You can try writing your own extension method if necessary.

**Comment by CyrusNajmabadi** [comment]
It sounds like what you have is an Enumerator to begin with. Not an IEnumerable.  If you expose your type through the appropriate API, you won't have an issue here since enumerators are already effectively defined as read-once (unless they support Reset)

**Comment by Mr0N** [comment]
> It sounds like what you have is an Enumerator to begin with. Not an IEnumerable. If you expose your type through the appropriate API, you won't have an issue here since enumerators are already effectively defined as read-once (unless they support Reset)
Yes, only GetEnumerator creates new instances, and when the information is, for example, from something static, it turns out to be a problem because the information is different.

```

new Example().Execute();
new Example().Execute();
Console.ReadKey();


class Example
{
    static int _count = 0;
    static IEnumerable<string> _en = GetRange();
    static IEnumerable<string> GetRange()
    {
        yield return (_count++).ToString();
    }
    public void Execute()
    {
        foreach (var item in _en)
        {
            Console.WriteLine(item);
        }
        Console.WriteLine(new string('-', 20));
        foreach (var item in _en)
        {
            Console.WriteLine(item);
        }
    }
}


```

**Comment by CyrusNajmabadi** [comment]
I don't see how your new interface will have any effect here.  First, the compiler will not add it to yield iterators.  Second, how would it change your consumption code at all?

**Comment by Mr0N** [comment]
> I don't see how your new interface will have any effect here. First, the compiler will not add it to yield iterators. Second, how would it change your consumption code at all?

I don't like the idea that there will be some Enumerable that will throw errors and I won't know about it. So, the interface is a way to denote such an Enumerable, rather than for someone to implement it.

**Comment by CyrusNajmabadi** [comment]
> I don't like the idea that there will be some Enumerable that will throw errors 

No example you've given throws errors.

> and I won't know about it. So, the interface is a way to denote such an Enumerable

But your example can't implement a new interface.  When you `yield` in the language, you always get an IEnumerable or IEnumerator. 

> rather than for someone to implement it.

Again, what could you possibly do with this?  You haven't given a single example of how you consume this interface or what sort of different code you would execute if passed one of these.

**Comment by Mr0N** [comment]
> > I don't like the idea that there will be some Enumerable that will throw errors
> 
> No example you've given throws errors.
> 
> > and I won't know about it. So, the interface is a way to denote such an Enumerable
> 
> But your example can't implement a new interface. When you `yield` in the language, you always get an IEnumerable or IEnumerator.
> 
> > rather than for someone to implement it.
> 
> Again, what could you possibly do with this? You haven't given a single example of how you consume this interface or what sort of different code you would execute if passed one of these.

Well, okay, I just suggested an idea, maybe it really is a bad one.
