### ISSUE TITLE
HttpClient.Timeout seems to be canceling before expected

### ISSUE THREAD

**Issue by kaiohenrique** [dotnet/runtime#103134]
Hi
We have an application in AspNet Core 8 and in production we noticed a weird behavior in HttpClient which seems to be cancelling before the expected time. 

```
{"component": "x", "version": "1.4.22", "timestamp": "2024-06-05 03:00:00.636", "level": "WARN", "message": "Timeout or TaskCancelled The request was canceled due to the configured HttpClient.Timeout of 15 seconds elapsing.", "scope": "", "function_name": "general-logs", "request_id": "7c148c31e873cf77f80657b1a0fd7221"}

{"component": "x", "version": "1.4.22", "timestamp": "2024-06-05 03:00:00.640", "level": "INFO", "message": "{\"method\":\"POST\",\"url\":\"x\",\"query_string\":\"\",\"status_code\":500,\"response_length\":0,\"response_time\":1078, "scope": "", "function_name": "operation-complete", "request_id": "7c148c31e873cf77f80657b1a0fd7221"}

```

As you can see in the logs above, the HttpCLient.Timeout is configured to fire after 15 seconds, but the request response_time is taking 1078ms.
Any ideas?

**Comment by wfurt** [comment]
can you share repro? (preferably small console app) And are you applying the Timeout to just the message header or are you trying to fetch the whole body?

**Comment by kaiohenrique** [comment]
Hi, @wfurt . I am trying to reproduce the issue on staging environment but no success so far. 
We set a CancellationToken in SendAsync and we set HttpClient.Timeout too. HttpCompletionOption is set to ResponseHeadersRead.

**Comment by kaiohenrique** [comment]
Sorry, @wfurt . The application is actually in .Net6. I have read that there was a bug in ConnectionPool which has been fixed in .Net7. I have done the upgrade and now I see another suspicious behaviors
   
Capturing network packages, I have noticed that in some ocasions, when Socket.ConnectAsync fails due to CancellationToken firing, no network package is captured

722ms Exception: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Program.<<Main>$>g__MakeConnection|0_0() in C:\Users\kaio.chiarato\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 37
  
![image](https://github.com/dotnet/runtime/assets/6674612/721ed0eb-e20c-4fff-a34d-a8551f011507)


Also, is Socket ConnectAsync slower than Socket Connect?

Running a test opening 500 connections, seems ConnectAsync is slower...
async: false, 774ms
async: true, 2256ms

**Comment by wfurt** [comment]
note that 7.0 is out of support. If anything you should upgrade to 8.0. There were some weird issues around connection pool - other team members may remember better. 

As far as the sync vs async. The sync method would conceptually be faster as all the work is done by the kernel. However it does not really scale as it blocks calling thread. Now, in general I would not expect much difference in practice. If you do, you can try to isolate minimal repro.

**Comment by MihaZupan** [comment]
Do you have a `ConnectTimeout` set on `SocketsHttpHandler`?
Are you limiting `MaxConnectionsPerServer`?
Is this happening for all requests or a small subset?
Do you see the same behavior on .NET 8.0?

Could you log the time delta between calling `HttpClient.SendAsync` and the timeout firing, instead of the time since the destination received the request? It's possible for example that the request was sent at 14.9 seconds and timed out before getting a response.

**Comment by MihaZupan** [comment]
There was a bug before .NET 7.0 where a `ConnectTimeout` exception would be reported with the same timeout message as `HttpClient.Timeout` - #67505. You should still be able to see the real exception under inner exceptions on .NET 6.

**Comment by kaiohenrique** [comment]
Hi, @MihaZupan @wfurt -

I was reading these issues: https://github.com/dotnet/runtime/issues/48566 and https://github.com/dotnet/runtime/issues/81023
A few quetions:
- In .Net8 DNS Resolution is asynchronous in linux? 
- In .Net 8 are there any mechanism to not perform multiple calls to getaddrinfo for the same host in linux?

**Comment by MihaZupan** [comment]
> In .Net8 DNS Resolution is asynchronous in linux?

No, it's doing blocking calls on the thread pool under the hood.

> In .Net 8 are there any mechanism to not perform concurrent calls to getaddrinfo for the same host in linux?

Yes, resolutions to the same host on Linux will get serialized such that there's only one blocking call to the OS per host at a time.
This is why #81023 is a concern -- if that one call gets stuck, it can cause many calls to `Dns.*` to fail.

If you suspect you might be hitting the same issue, you could log the connect failures like so:
```c#
var handler = new SocketsHttpHandler
{
    ConnectCallback = async (context, ct) =>
    {
        var socket = new Socket(SocketType.Stream, ProtocolType.Tcp) { NoDelay = true };
        try
        {
            await socket.ConnectAsync(context.DnsEndPoint, ct);
            return new NetworkStream(socket, ownsSocket: true);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex); // Log this (including the stack trace!)

            socket.Dispose();
            throw;
        }
    }
};
```

The stack trace should be useful here to hint at whether the connection attempt actually got stuck at the DNS or Socket connect layer.

**Comment by kaiohenrique** [comment]
Hi, @MihaZupan @wfurt 
In this point https://github.com/dotnet/runtime/blob/041375910885f3a30ccf0bb8b751566dae7043f4/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs#L116
I think we need to validate if the Socket is already Connected before calling CancelConnectAsync. If the application in under heavy load and the runtime delays to unregister the cancellation token callback, I think is possible that we will dispose an already connected and healthy Socket. What do you think?

**Comment by kaiohenrique** [comment]
I have noticed that CancelConnectAsync is based in the property `_operating` which is set to Free (in SocketAsyncEventArgs.Complete method) after the Socket.SetToConnected. So, if any delays happens between Socket.SetToConnected and SocketAsyncEventArgs.Complete, the socket will be disposed but the Socket.Connected could be pottentially `true`.
