### ISSUE TITLE
Ensure that Microsoft.Extensions.Http.DefaultHttpClientFactory is supporting distributed tracing

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#103192]
Upon ananalysis of my application i have observed that "Microsoft.Extensions.Http.DefaultHttpClientFactory" is not having trace/transactions ids.

As such i would like that all methods generating logs are wrapped in activities to enabled distributed tracing and at the same time all log events have a trace/transaction id.

At the same time it should be checked if any other methods are not covered

**Comment by davidfowl** [comment]
HttpClient itself supports distributed tracing, its unclear from the description why it needs to be at this level. Can you elaborate what problem you are trying to solve?

**Comment by thompson-tomo** [comment]
@davidfowl / @CarnaViire when i look at my logs which are being written in ECS format i can see that the following messages are lacking and tracing information

```
{"@timestamp":"2024-06-13T08:53:07.4288541+10:00","log.level":"Debug","message":"Starting HttpMessageHandler cleanup cycle with 1 items","log":{"logger":"Microsoft.Extensions.Http.DefaultHttpClientFactory"},"labels":{"EventName":"CleanupCycleStart"},"event":{"code":"100","created":"2024-06-13T08:53:07.4288541+10:00","severity":7,"timezone":"AUS Eastern Standard Time"},"service":{"name":"WebManager","node.name":"","version":"2.3.1-beta-241610955\u002B81e61e0e20f6b035dc1bb7e4e91442759b37c0b3"},"metadata":{"InitialCount":1,"EventId":100},"MessageTemplate":"Starting HttpMessageHandler cleanup cycle with {InitialCount} items"}
{"@timestamp":"2024-06-13T08:53:07.4288541+10:00","log.level":"Debug","message":"Ending HttpMessageHandler cleanup cycle after 0.1111ms - processed: 0 items - remaining: 1 items","log":{"logger":"Microsoft.Extensions.Http.DefaultHttpClientFactory"},"labels":{"EventName":"CleanupCycleEnd"},"event":{"code":"101","created":"2024-06-13T08:53:07.4288541+10:00","severity":7,"timezone":"AUS Eastern Standard Time"},"service":{"name":"WebManager","node.name":"","version":"2.3.1-beta-241610955\u002B81e61e0e20f6b035dc1bb7e4e91442759b37c0b3"},"metadata":{"ElapsedMilliseconds":0.1111,"DisposedCount":0,"RemainingItems":1,"EventId":101},"MessageTemplate":"Ending HttpMessageHandler cleanup cycle after {ElapsedMilliseconds}ms - processed: {DisposedCount} items - remaining: {RemainingItems} items"}
``` 

Shouldn't these 2 log records belong to the same activity so that we can see when it starts and when it stops using the trace/span id's et? As such would suggest re-openning to ensure the mentioned aspect is being handled as a transaction.

**Comment by CarnaViire** [comment]
Cleanup cycles (and the events "CleanupCycleStart", "CleanupCycleEnd") are not related to any requests. It's a scheduled operation within `DefaultHttpClientFactory` (internal implementation of `IHttpClientFactory` interface), but anyway I'd consider both the cleanup process and its - debug-level - logs as an implementation detail. Is there any scenario where you'd actually need to collect them at all?

**Comment by thompson-tomo** [comment]
Agree that those logs provide limited use/value. Would it perhaps make sense to replace them with an event belonging to a transaction that way u can still get the same data but it becomes opt-in?
