### ISSUE TITLE
ILVerify.Program.Resolve throws NullReferenceException if missing DLL (regression)

### ISSUE THREAD

**Issue by carlos-quintero** [dotnet/runtime#103154]
### Description

When you run ilverify 8.0.0 to verify a DLL that has dependencies, if some dependency dll is missing ilverify throws:

Error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILVerify.Program.Resolve(String simpleName)
   at ILVerify.Program.ILVerify.IResolver.ResolveAssembly(AssemblyName assemblyName)
   at ILVerify.Verifier.SetSystemModuleName(AssemblyName name)
   at ILVerify.Program.Run()
   at ILVerify.ILVerifyRootCommand.<.ctor>b__40_0(ParseResult result)

instead of a more helpful exception (such as FileNotFound with the name of the missing file).

### Reproduction Steps

- Using Visual Studio 2022 create a solution with two .NET 8.0 Class Library projects (ClassLibrary1 and ClassLibrary2), with ClassLibrary2 referencing ClassLibrary1.

- In the referenced library (ClassLibrary1), create a static class with a static method.
- In the referencing library (ClassLibrary2), create a class with a method that calls the method in the other library
Build the solution
- Open a command prompt and change to the output folder of ClassLibrary2 (ClassLibrary2\bin\Debug\net6.0)
Run the following command:

`ilverify ClassLibrary2.dll -r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\*.dll"
`

(notice that we have omitted -r ".*.dll" so that ClassLibrary1.dll will not be found)

### Expected behavior

Something like:

"ClassLibrary1.dll not found"

like what you get with ILVerify version 7.0.0:

`[IL]: Error [FileLoadErrorGeneric]: [<path>\ClassLibrary2.dll : ClassLibrary2.Class2::f2()] Failed to load assembly 'ClassLibrary1'
`
### Actual behavior

System.NullReferenceException: Object reference not set to an instance of an object.
   at ILVerify.Program.Resolve(String simpleName)
   at ILVerify.Program.ILVerify.IResolver.ResolveAssembly(AssemblyName assemblyName)
   at ILVerify.Verifier.SetSystemModuleName(AssemblyName name)
   at ILVerify.Program.Run()
   at ILVerify.ILVerifyRootCommand.<.ctor>b__40_0(ParseResult result)

### Regression?

I already reported this issue in #62711 and it was fixed in version 7.0.0. It happens again in version 8.0.0

### Known Workarounds

Of course you must add -r with the required dlls, but if you miss some dll the current behavior with NullReferenceException makes it frustrating to know which dll is missing

### Configuration

.NET 8.0.5
Windows 10
AnyCPU

**Comment by jkotas** [comment]
Thank you for reporting. This was fixed for .NET 9 by #95939.
