### ISSUE TITLE
[API Proposal]: Implement IEnumerable, IReadOnlyCollection and IReadOnlyList for {RO}Span and {RO}Memory

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#103164]
### Background and motivation

With the addition of allowing implementing interfaces for ref struct, it now makes sense to implement `IEnumerable` for `{RO}Span` and `{RO}Memory` to allow developers to iterate on it.
Otherwise, developers have no way to interact with `{RO}Span/Memory` through generic types.

While I want to propose implementing `IList<T>` for `Span` and `Memory` as well, but it seems too bloated (as most methods will just throw a `NotSupportedException`), so alternatively we may introduce an interface `IReadOnlyMutableList<T>` to enable write access to a read-only list so that one can mutate values in a `Span` or `Memory` (out-of-scope from this proposal):

```cs
interface IReadOnlyMutableList<T> : IReadOnlyList<T>
{
    T this[int index] { get; set; }
}
```

### API Proposal

```diff
namespace System;

public ref struct Span<T> : IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>
{
+    public T this[int index] { get; }
+    public int Count { get; }
+    public IEnumerator<T> GetEnumerator();
+    IEnumerator IEnumerable.GetEnumerator();
}

public ref struct ReadOnlySpan<T> : IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>
{
+    public T this[int index] { get; }
+    public int Count { get; }
+    public IEnumerator<T> GetEnumerator();
+    IEnumerator IEnumerable.GetEnumerator();
}

public readonly struct Memory<T> : IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>
{
+    public T this[int index] { get; }
+    public int Count { get; }
+    public IEnumerator<T> GetEnumerator();
+    IEnumerator IEnumerable.GetEnumerator();
}

public readonly struct ReadOnlyMemory<T> : IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>
{
+    public T this[int index] { get; }
+    public int Count { get; }
+    public IEnumerator<T> GetEnumerator();
+    IEnumerator IEnumerable.GetEnumerator();
}
```

### API Usage

```csharp
M<Span<int>, int>([1, 2, 3, 4, 5]);

void M<T, U>(T span) where T : IEnumerable<U>, IReadOnlyCollection<U>, IReadOnlyList<U>, allows ref struct
{
    Console.WriteLine($"Count: {span.Count}");
    foreach (U u in span)
    {
        Console.WriteLine(u);
    }
    for (var i = 0; i < span.Count; i++)
    {
        Console.WriteLine(span[i]);
    }
}
```

**Comment by tannergooding** [comment]
> While I want to propose implementing IList<T> for Span and Memory as well, but it seems too bloated (as most methods will just throw a NotSupportedException), so alternatively we may introduce an interface IReadOnlyMutableList<T> to enable write access to a read-only list so that one can mutate values in a Span or Memory (out-of-scope from this proposal):

This would be counter to the use of the `IList<T>` and similar interfaces elsewhere (such as on `T[]`) where they do get implemented and many APIs intentionally throw. That is in part why there is an `IsReadOnly` property on them.

------------

In general this proposal needs more weigh in across the team including @stephentoub.

Most, if not all, of these APIs would also have to be explicitly implementation both to match how they exist for other similar types and to avoid conflicting with the existing members that already exist.

**Comment by eiriktsarpalis** [comment]
Implementing interfaces for the case of Memory has always been a possibility, however the designers chose to implement this as an explicit wrapper (via the `MemoryMarshal.ToEnumerable` method) so that enumeration can only happen intentionally rather than accidentally.

The same concerns apply to Span. At the same time, I find it unlikely that users would write generic code like this just to be able to reconcile Span with regular collections.

**Comment by eiriktsarpalis** [comment]
> Most, if not all, of these APIs would also have to be explicitly implementation both to match how they exist for other similar types and to avoid conflicting with the existing members that already exist.

It wouldn't be possible to use struct enumerators with explicit implementations though, right?

**Comment by stephentoub** [comment]
This is not possible for span. Even if it provides a strongly-typed GetEnumerator that returns a ref struct, it can't implement the GetEnumerator interface method, which is strongly-typed to return the interface.

**Comment by stephentoub** [comment]
And for Memory, we've discussed this multiple times in the past. While implementing IEnumerable can be argued either way, there's been a dislike for implementing IList, which would cause every indexing operation to need to retrieve the underlying span, adding measurable overhead compared to just getting the span once and indexing into it.

**Comment by hez2010** [comment]
> This is not possible for span. Even though it provides a strongly-typed GetEnumerator that returns a ref struct, it can't implement the GetEnumerator interface method, which is strongly-typed to return the interface.

The one returning `IEnumerable` can simply throw a `NotSupportedException`.

**Comment by tannergooding** [comment]
> The one returning IEnumerable can simply throw a NotSupportedException.

What that ends up being is that all `IEnumerable<T>` APIs throw and so the interface allows for nothing. We already have a ref struct `Enumerator GetEnumerator()` API exposed that allows it to work with the duck typing the language provides.

It sounds like the general thought here is that this doesn't actually give much real benefit (if any at all) and so it's not desirable to do.

**Comment by hez2010** [comment]
> What that ends up being is that all `IEnumerable<T>` APIs throw and so the interface allows for nothing. 

Yeah I was aware about this right after I posted the comment so I edited the comment.

> We already have a ref struct `Enumerator GetEnumerator()` API exposed that allows it to work with the duck typing the language provides.

This doesn't work for generic case, the issue here is that you cannot interact with `{RO}Span/Memory` through generic types.

**Comment by hez2010** [comment]
How about introducing an interface `IAlternateEnumerable<T, TEnumerator>`?

```cs
interface IAlternateEnumerable<T, TEnumerator> where TEnumerator : IEnumerator<T>, allows ref struct
{
    public TEnumerator GetEnumerator();
}
```

**Comment by hez2010** [comment]
> Instead, it'd be the typeof case where you try and extract a span and defer down to the specialized implementation (much as we do internally for LINQ)

The problem is, after applying `where T : allows ref struct`, you cannot do anything on that `T` regardless of whether `T` is a `Span` or not:

```cs
void Foo<T>(T v) where T : allows ref struct
{
    Console.WriteLine(v); // you cannot even print it due to `allows ref struct`
}
```

So, we need at least some interfaces so that we can do something on `v` here but adding interface constraints to `T` will soon reject all `Span` and `Memory`.

**Comment by tannergooding** [comment]
Going to close this as not actionable given the above discussion and input.
