### ISSUE TITLE
SslStream not working with ephemeral keys

### ISSUE THREAD

**Issue by troyha** [dotnet/runtime#103101]
### Description

#23749 was closed prematurely. This is still not working. I am retrieving a certificate from Azure Key Vault and reciving this error. 

[MS troubleshooting link](https://learn.microsoft.com/en-us/dotnet/core/extensions/sslstream-troubleshooting) clearly says:
"On Windows, you may encounter the (0x8009030E): No credentials are available in the security package error message when attempting to use certificates with ephemeral keys. This behavior is due to a bug in the underlying OS API (Schannel). More relevant info and workarounds can be found on the associated [GitHub issue](https://github.com/dotnet/runtime/issues/23749)."

#45680 was closed as dup of #23749 even though the author of the new one said the other was closed prematurely.

### Reproduction Steps

Using .Net C# 6.0 create new MongoClient using X.509 certificate Auth, stored in Azure Key Vault by using CertificateClient DownloadCertificate function to get certificate. 
Add certificate to MongoClient SSLSettings ClientCertficates.
Connect to MongoDB database collection -> this throws the exception "No credentials are available in the security package"

### Expected behavior

The certificate works when connecting to MongoDB using mongosh commands and other IDEs so the certificate is fine. The expected behaviour is that a valid certificate downloaded from the Azure Key Vault will work without storing locally since that is the purpose of using the Certificate store int he Key Vault.

### Actual behavior

The certificate downloads correctly into memory (can view public and private key with correct CN when debugging) but when trying to use it for Auth in the MongoClient SslSettings ClientCertificates we get the error:

---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x8009030E): No credentials are available in the security package

### Known Workarounds

Workarounds listed in #23749 

### Configuration

Windows OS (any based on previous ticket) .Net 6.0 we are using.

### Other information

#45680 was closed as dup of #23749 even though the author of the new one said the other was closed prematurely.

**Comment by bartonjs** [comment]
Just to set expectations, this is a Windows OS limitation, not a .NET limitation.  The best we can reasonably do is to notice that a certificate with an ephemeral private key has been passed down to SslStream and throw a more specific exception.

**Comment by wfurt** [comment]
As @bartonjs mentioned this is not .NET limitation so I'm inclined to just close it. The only "fix" would be start using OpenSSL (or something similar) on Windows and that has MANY problems .... so it is unlikely to happen. 
If you feel documentation can be improved about platform limitation go ahead and open PR in doc repo @troyha. I think that is best we can do at the moment.

**Comment by rzikm** [comment]
also, in .NET 8 we throw more helpful exception if we detect certs with ephemeral keys on Windows. (https://github.com/dotnet/runtime/pull/83436).

We also mention this in the SslStream troubleshooting guide https://learn.microsoft.com/en-us/dotnet/core/extensions/sslstream-troubleshooting#handshake-failed-with-ephemeral-keys. Unless there is another place where such documentation might be more visible, I don't see this issue as actionable.

**Comment by troyha** [comment]
Thanks for the replies. The troubleshooting guide was not explicit that the issue would not be resolved and the resolution was just to use the workarounds. Re-reading it now with the context makes more sense. 
Having a better error message also makes it much better since it was the frustration of figuring out why it was occurring in the first place that prompted me to raise the issue.
You could potentially add something more explicit in the troubleshooting e.g. "This issue will not be resolved within .Net so use the wrokarounds provided in the Github issue. Also, in .NET 8 we throw more helpful exception if we detect certs with ephemeral keys on Windows "
Happy to close this off.
