### ISSUE TITLE
System.IO.Pipelines issue: Ureleased memory after reader.Complete

### ISSUE THREAD

**Issue by augong0301** [dotnet/runtime#103149]
### Description

I'm testing on System.IO.Pipelines to figure out how fast could it be beyond ArrayPool when I had a large dataset to write/read.
But during my test,  I found that the memory cost can't be released after I consumed some of the data. I've learned that the Pipe() itself controls the memory usage, and so I try to print the total memory after several iterations. 
The GC told me that The memory usage has been released, but i found it wired that my Windows task manager never shows declaration in memory. 

So, what I want to know is :
1. Is there anything wrong with my implementation of PipeWriter and PipeReader?
2. When does the Pipe Start to release the memory it comsumed?
3. Does the pipe simply release the memory by Moving the memory to Unmanaged Memory since I can't find the byte[] by memory snapshot in Visual Studio?
4. What is the best practice when there is a big set of data like 10GB when i want to asynchronously write/read?

My codes are listed below:

```
using System.Buffers;
using System.Diagnostics;
using System.IO.Pipelines;

namespace Test
{
	class DoSomething
	{
		public async void Do()
		{
			try
			{
				await Console.Out.WriteLineAsync("Test start ————————————————————————————");
				await Console.Out.WriteLineAsync($"total memory for pipe is {GC.GetTotalMemory(true) / 1024 / 1024} MB ");

				var rand = new Random();
				long size = 1000;
				long gen = 10000000;
				long t = size * gen;
				await Console.Out.WriteLineAsync($"Sample size of {size} bytes, capacity of {gen}, theoretical memory is {size * gen / 1000000} MB");
				var buffer = new byte[size];
				rand.NextBytes(buffer);

				var pipe = new Pipe();

				var sw = new Stopwatch();
				sw.Start();
				Task wtask = WriteDataAsync(buffer, pipe, gen);
				Task rtask = ReadDataAndReleaseAsync(pipe, gen);


				Task.WaitAll(wtask, rtask);

				sw.Stop();
				await Console.Out.WriteLineAsync($"total memory for pipe is {GC.GetTotalMemory(true) / 1024 / 1024} MB ");
				pipe = null;
				GC.Collect(2);
				GC.WaitForPendingFinalizers();
				Console.WriteLine("pipe takes " + sw.ElapsedMilliseconds + "ms");
				Console.ReadKey();
				await Console.Out.WriteLineAsync($"total memory for pipe is {GC.GetTotalMemory(true) / 1024 / 1024} MB ");
			}
			catch (Exception ex)
			{
				await Console.Out.WriteLineAsync(ex.Message);
				throw;
			}


		}

		private async Task ReadDataAndReleaseAsync(Pipe pipe, long gen)
		{
			var reader = pipe.Reader;
			while (true)
			{
				ReadResult result = await reader.ReadAsync();
				ReadOnlySequence<byte> buffer = result.Buffer;

				SequencePosition consumed = buffer.Start;
				SequencePosition examined = buffer.Start;

				int timer = 0;
				while (TryReadLine(ref buffer, out ReadOnlySequence<byte> line, out SequencePosition lineEnd))
				{
					// Process data
					//ProcessBuffer(line);

					consumed = lineEnd;
					examined = lineEnd;

					// AdvanceTo() => update buffer
					reader.AdvanceTo(consumed, examined);
					result = await reader.ReadAsync();
					//buffer = result.Buffer;
					timer++;
					if (timer % 100000 == 0)
					{
						Console.Out.WriteLine($"after read {GC.GetTotalMemory(true) / 1024 / 1024} MB ");
					}
				}

				// 如果没有更多数据可供处理，更新 examined 位置
				if (buffer.Length > 0)
				{
					reader.AdvanceTo(consumed, buffer.End);
				}

				// 如果没有更多数据，则退出循环
				if (result.IsCompleted || result.IsCanceled)
				{
					break;
				}
			}

			await reader.CompleteAsync();
		}
		private async Task WriteDataAsync(byte[] buffer, Pipe pipe, long gen)
		{
			try
			{
				for (int j = 0; j < gen; j++)
				{
					WriteData(buffer, j, pipe.Writer);
				}
			}
			finally
			{
				await Console.Out.WriteLineAsync($"before write by {GC.GetTotalMemory(false) / 1024 / 1024} MB ");
				//pipe.Writer.Complete();
				await pipe.Writer.CompleteAsync();

				await Console.Out.WriteLineAsync($"after write by {GC.GetTotalMemory(false) / 1024 / 1024} MB ");
			}
		}

		public void WriteData(byte[] data, int index, PipeWriter writer)
		{
			var memory = writer.GetMemory(data.Length + 8);
			var span = memory.Span;

			BitConverter.GetBytes(data.Length + 4 + 4).CopyTo(span);
			span = span.Slice(4);

			data.CopyTo(span);
			span = span.Slice(data.Length);

			BitConverter.GetBytes(index).CopyTo(span);

			writer.Advance(data.Length + 4);
			writer.FlushAsync();
		}

		bool TryReadLine(ref ReadOnlySequence<byte> buffer, out ReadOnlySequence<byte> data, out SequencePosition lineEnd)
		{
			lineEnd = default;
			data = default;

			if (buffer.Length < 4)
			{
				return false;
			}
			// read length
			var length = 10008;
			//var ss = buffer.Slice(0, 4).ToArray();
			if (buffer.Length < length)
			{
				return false;
			}

			// Read the data and index
			var message = buffer.Slice(4, length - 4);
			data = message.Slice(0, message.Length - 4);

			// Look for a EOL in the buffer.
			lineEnd = buffer.GetPosition(length);
			buffer = buffer.Slice(length);
			return true;
		}
	}

}


```

### Reproduction Steps

I hope someone can resolve issue 4 as soon as possible

### Expected behavior

![test (2)](https://github.com/dotnet/runtime/assets/69343120/06896657-6086-4ac6-b003-0366adb37ca9)

### Actual behavior

the console output goes like this, there is no decrease in **Memory Usage** in  Diagnostic Tools 

![image](https://github.com/dotnet/runtime/assets/69343120/03e00769-a401-4980-8273-db646a2abc81)

And the Windows Task Manager never shows a declaration in memory 

![image](https://github.com/dotnet/runtime/assets/69343120/d543e5d3-fa89-437e-a917-65e8fe2e26f4)

**Comment by huoyaoyuan** [comment]
> 1. Is there anything wrong with my implementation of PipeWriter and PipeReader?

In the writing side, you are not awaiting `FlushAsync`. A pipe shouldn't hold unnecessary data in its buffer. It there's enough data for consumption, `FlushAsync` will block on awaiting and prevents overwriting. That's the total point of pipeline.

You reader also looks wrong. A sample of reading from https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/ :

```csharp
async Task ReadPipeAsync(PipeReader reader)
{
    while (true)
    {
        ReadResult result = await reader.ReadAsync();

        ReadOnlySequence<byte> buffer = result.Buffer;
        SequencePosition? position = null;

        do 
        {
            // Look for a EOL in the buffer
            position = buffer.PositionOf((byte)'\n');

            if (position != null)
            {
                // Process the line
                ProcessLine(buffer.Slice(0, position.Value));
                
                // Skip the line + the \n character (basically position)
                buffer = buffer.Slice(buffer.GetPosition(1, position.Value));
            }
        }
        while (position != null);

        // Tell the PipeReader how much of the buffer we have consumed
        reader.AdvanceTo(buffer.Start, buffer.End);

        // Stop reading if there's no more data coming
        if (result.IsCompleted)
        {
            break;
        }
    }

    // Mark the PipeReader as complete
    reader.Complete();
}
```

Basically, you should call `ReadAsync` when you **fail** to process a new block/line from buffer, and `AdvancedTo` when you **successfully** process one.
Your code seems causing a deadlock if properly awaiting `FlushAsync`.


> 2\. When does the Pipe Start to release the memory it comsumed?

Basically, when you call `AdvancedTo`, the buffer before the location is available for reusing.

> 3\. Does the pipe simply release the memory by Moving the memory to Unmanaged Memory since I can't find the byte[] by memory snapshot in Visual Studio?

`Pipe` itself doesn't use any unmanaged memory directly. It just rents from and returns to the default array pool.
It's actually a question to GC about the memory usage in this situation. @dotnet/gc can you help on this?

> 4\. What is the best practice when there is a big set of data like 10GB when i want to asynchronously write/read?

Use pipelines correctly. You usage is incorrect.
Basically, writer should only start to write when the reader has consumed reasonably amount of the buffer. That what pipeline does for you.

**Comment by davidfowl** [comment]
Also the docs https://learn.microsoft.com/en-us/dotnet/standard/io/pipelines

**Comment by cshung** [comment]
I can help with the memory consumption aspect, but I am unfamiliar with the libraries. I will need some help here.

First of all, @huoyaoyuan mentioned there are some suboptimal usage of the library, do we care about the memory aspect of the suboptimal program at all? 

Suppose we don't care about the suboptimal usage case, do we know if memory usage is a problem in a program with optimal library usage case? If so, can I have a simple repro with a main method so that I can run?

**Comment by huoyaoyuan** [comment]
A simple repro:

```csharp
using System;
using System.Buffers;
using System.IO.Pipelines;

var pipe = new Pipe();
var kilobyte = new byte[1024];

for (int i = 0; i < 5 * 1024 * 1024; i++)
{
    pipe.Writer.Write(kilobyte);
}

Console.ReadLine();

pipe = null;
GC.Collect(2);
GC.WaitForPendingFinalizers();

Console.ReadLine();

```

The large byte arrays used by the pipe are identified as "dead object" in VS memory snapshot.

So the question is: why are they identified as dead at the first ReadLine, as the pipe should be still holding references to them? Why are they not collected at the second ReadLine?

If there's some managed memory leak in pipeline, we may make it more robust against such suboptimal usage.

**Comment by augong0301** [comment]
> > 1. Is there anything wrong with my implementation of PipeWriter and PipeReader?
> 
> In the writing side, you are not awaiting `FlushAsync`. A pipe shouldn't hold unnecessary data in its buffer. It there's enough data for consumption, `FlushAsync` will block on awaiting and prevents overwriting. That's the total point of pipeline.
> 
> You reader also looks wrong. A sample of reading from https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/ :
> 
> ```cs
> async Task ReadPipeAsync(PipeReader reader)
> {
>     while (true)
>     {
>         ReadResult result = await reader.ReadAsync();
> 
>         ReadOnlySequence<byte> buffer = result.Buffer;
>         SequencePosition? position = null;
> 
>         do 
>         {
>             // Look for a EOL in the buffer
>             position = buffer.PositionOf((byte)'\n');
> 
>             if (position != null)
>             {
>                 // Process the line
>                 ProcessLine(buffer.Slice(0, position.Value));
>                 
>                 // Skip the line + the \n character (basically position)
>                 buffer = buffer.Slice(buffer.GetPosition(1, position.Value));
>             }
>         }
>         while (position != null);
> 
>         // Tell the PipeReader how much of the buffer we have consumed
>         reader.AdvanceTo(buffer.Start, buffer.End);
> 
>         // Stop reading if there's no more data coming
>         if (result.IsCompleted)
>         {
>             break;
>         }
>     }
> 
>     // Mark the PipeReader as complete
>     reader.Complete();
> }
> ```
> 
> Basically, you should call `ReadAsync` when you **fail** to process a new block/line from buffer, and `AdvancedTo` when you **successfully** process one. Your code seems causing a deadlock if properly awaiting `FlushAsync`.
> 
> > 2. When does the Pipe Start to release the memory it comsumed?
> 
> Basically, when you call `AdvancedTo`, the buffer before the location is available for reusing.
> 
> > 3. Does the pipe simply release the memory by Moving the memory to Unmanaged Memory since I can't find the byte[] by memory snapshot in Visual Studio?
> 
> `Pipe` itself doesn't use any unmanaged memory directly. It just rents from and returns to the default array pool. It's actually a question to GC about the memory usage in this situation. @dotnet/gc can you help on this?
> 
> > 4. What is the best practice when there is a big set of data like 10GB when i want to asynchronously write/read?
> 
> Use pipelines correctly. You usage is incorrect. Basically, writer should only start to write when the reader has consumed reasonably amount of the buffer. That what pipeline does for you.
> 
> I suggest to read https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/ in depth to help you understand how to use pipelines properly.

Thank u for pointing out the issue in my code. I looked into the blog and realized my faults in using Pipeline.

The pipe's principal is to store at least memory and waiting for user to consume as fast as we can.  Is this correct?

Additionally, I wonder what's the largest memory size pipe can hold or, i should define that according to my business?

**Comment by huoyaoyuan** [comment]
> The pipe's principal is to store at least memory and waiting for user to consume as fast as we can. Is this correct?

Yes. The pipe will resume the writer by unblocking `FlushAsync` when the data available is less than `ResumeWriterThreshold`.

> Additionally, I wonder what's the largest memory size pipe can hold or, i should define that according to my business?

If you write properly, it will pause you when reaching `PauseWriterThreshold`. These values are configurable via `PipeOptions`. The default values are 32KB and 64KB. You don't need to bother with these unless you are dealing with large data blocks.

 There's no hard limit as long as it can rent more memory from the pool.

**Comment by augong0301** [comment]
> A simple repro:
> 
> ```cs
> using System;
> using System.Buffers;
> using System.IO.Pipelines;
> 
> var pipe = new Pipe();
> var kilobyte = new byte[1024];
> 
> for (int i = 0; i < 5 * 1024 * 1024; i++)
> {
>     pipe.Writer.Write(kilobyte);
> }
> 
> Console.ReadLine();
> 
> pipe = null;
> GC.Collect(2);
> GC.WaitForPendingFinalizers();
> 
> Console.ReadLine();
> ```
> 
> The large byte arrays used by the pipe are identified as "dead object" in VS memory snapshot.
> 
> So the question is: why are they identified as dead at the first ReadLine, as the pipe should be still holding references to them? Why are they not collected at the second ReadLine?
> 
> If there's some managed memory leak in pipeline, we may make it more robust against such suboptimal usage.

I tried to continue this work and found something.

This might not be a good practice, but i think i followed the syntax of pipe.

```
using System.Buffers;
using System.IO.Pipelines;

var pipe = new Pipe();
var kilobyte = new byte[1024];

for (int i = 0; i <  1024 * 1024; i++)
{
    pipe.Writer.Write(kilobyte);
}
pipe.Writer.Complete();
Console.ReadLine();

pipe.Reader.TryRead(out var result);
pipe.Reader.AdvanceTo(result.Buffer.End);
pipe.Reader.Complete();
pipe.Reset();
pipe = null;

GC.Collect(2);
GC.WaitForPendingFinalizers();

Console.ReadLine();

```

As you said, before the GC works, I found the byte arrays in "dead objects". 

![image](https://github.com/dotnet/runtime/assets/69343120/bd171b8a-2475-4e52-a2fa-10ca3545669c)

 After I finished the write/read works and AdvanceTo the buffer's end, a small amount the memory was released by GC.

![image](https://github.com/dotnet/runtime/assets/69343120/6e94b94e-b43a-4e4d-84af-b40582eeb586)

I don't know whether this is a memory leak issue or just something else.

**Comment by cshung** [comment]
Am I missing something? When I tried to compile it, I am getting this error.

`error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)`

**Comment by julealgon** [comment]
> Am I missing something? When I tried to compile it, I am getting this error.
> 
> `error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)`

Add the NuGet package for the Pipelines. It is not native on the framework;
- https://www.nuget.org/packages/System.IO.Pipelines/8.0.0

**Comment by cshung** [comment]
Thanks, I am able to run the repro now.

It looks like the `byte[]` are held by `ArrayPool`, therefore the GC is not expected to collect them.

**Comment by augong0301** [comment]
> Thanks, I am able to run the repro now.
> 
> It looks like the `byte[]` are held by `ArrayPool`, therefore the GC is not expected to collect them.

So the memory is not Returned by the ArrayPool, and this issue comes? 

Anyway, i have learned the best way to Practice pipe. 

Give all my thanks to @huoyaoyuan @davidfowl @julealgon @cshung  

BTW, i don't know if this issue should be closed.

**Comment by stephentoub** [comment]
> So the memory is not Returned by the ArrayPool, and this issue comes?

The purpose of the ArrayPool is to hold on to arrays for them to be given out again to someone who later asks for them. Over time if there's memory pressure it will drop them.
