### ISSUE TITLE
NET8.0，Socket，Why can I send so much data continuously

### ISSUE THREAD

**Issue by snltty** [dotnet/runtime#103107]
NET8.0，Socket，Why can I send so much data continuously

![1](https://github.com/dotnet/runtime/assets/10977033/6303c56e-6e70-4f08-9fac-1b251507cf55)

**Comment by stephentoub** [comment]
The actual number of bytes ReceiveAsync reads is returned to you, but the code shown is ignoring it. ReceiveAsync does not guarantee it'll fill the entire buffer you supply.

**Comment by snltty** [comment]
> The actual number of bytes ReceiveAsync reads is returned to you, but the code shown is ignoring it. ReceiveAsync does not guarantee it'll fill the entire buffer you supply.

Even if it is full, it can only receive a maximum of 1KB at a time. Why can the sender continuously send 2568KB

**Comment by huoyaoyuan** [comment]
> Even if it is full, it can only receive a maximum of 1KB at a second. Why can the sender continuously send 2568KB

Windows OS provides TCP buffer. Unreceived data will be kept in the buffer.

```csharp
        using var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
        listener.Bind(new IPEndPoint(IPAddress.Loopback, 12345));
        listener.Listen();

        using var sender = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
        sender.Connect(new IPEndPoint(IPAddress.Loopback, 12345));

        for (int i = 0; i < 1024 * 1024; i++)
        {
            sender.Send(new byte[1024]);
            Console.WriteLine($"{i + 1}KB sent.");
        }
```

Even if there's no reader at all, it can still successfully send 2238KB on my machine.

**Comment by snltty** [comment]
> > Even if it is full, it can only receive a maximum of 1KB at a second. Why can the sender continuously send 2568KB
> 
> Windows OS provides TCP buffer. Unreceived data will be kept in the buffer.
> 
> ```cs
>         using var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
>         listener.Bind(new IPEndPoint(IPAddress.Loopback, 12345));
>         listener.Listen();
> 
>         using var sender = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
>         sender.Connect(new IPEndPoint(IPAddress.Loopback, 12345));
> 
>         for (int i = 0; i < 1024 * 1024; i++)
>         {
>             sender.Send(new byte[1024]);
>             Console.WriteLine($"{i + 1}KB sent.");
>         }
> ```
> 
> Even if there's no reader at all, it can still successfully send 2238KB on my machine.

My Debian system is also like this

**Comment by huoyaoyuan** [comment]
> 最直接的问题是，我用来转发RDP桌面，带宽信息错误

我没有找到RDP如何推断带宽的资料。这种情况手动选择目标带宽可能更好。

> A<-->server<-->B，我使用当我通信的数据量较大的时候，即使A端关闭了，服务器仍然在接收A的数据，然后发送给B

另一个单独的UDP通道？
这种情况，转发服务器只能在一方连接中断之后尽快切断双方连接，别的方面我也不清楚。

**Comment by snltty** [comment]
> > 最直接的问题是，我用来转发RDP桌面，带宽信息错误
> 
> 我没有找到RDP如何推断带宽的资料。这种情况手动选择目标带宽可能更好。
> 
> > A<-->server<-->B，我使用当我通信的数据量较大的时候，即使A端关闭了，服务器仍然在接收A的数据，然后发送给B
> 
> 另一个单独的UDP通道？ 这种情况，转发服务器只能在一方连接中断之后尽快切断双方连接，别的方面我也不清楚。

主要是，在A端程序关闭后，服务器并不能知道连接中断了，仍然能从A端的连接中接收数据，然后发送给B

**Comment by snltty** [comment]
![2](https://github.com/dotnet/runtime/assets/10977033/6e58e52e-79b0-4bf4-9c67-86b7169bc7a0)

**Comment by huoyaoyuan** [comment]
我对TCP没有更多深入了解。建议等network team解答问题。

I have no further knowledge about the detail about TCP. Waiting for network team member to answer this.

**Comment by Clockwork-Muse** [comment]
Side note:
There's now a [`MemoryPool`](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.memorypool-1?view=net-8.0) that would be generally preferrable to using `ArrayPool`.

**Comment by wfurt** [comment]
Can you post full repro somewhere @snltty? Images are just pain to dial with. And non-english comments are also difficult to deal with. The received counting is weird. As @stephentoub mentioned the `ReceiveAsync` returns specific bytes but you are making assumption instead. And it won't receive more than the provided buffer. e.g. you sending 8K chunks but reading only 1K at the time. Once the buffer is full TCP will shrink windows size and it takes more work to re-open it. If you want perf you should always try to read more data (or have buffer for) to avoid hitting limits and causing extra calls and roundtrips.  

And lastly it is not quite clear to me what the expectation is.

**Comment by huoyaoyuan** [comment]
In English: the remaining question is about TCP connectivity. There is a proxy server between RDP server and client. When the client disconnects, the server can still read the remaining data and send response back. What's the best way to shutdown the connection in this situation?

**Comment by wfurt** [comment]
There is no general rule IMHO. In traditional TCP way, The client would call `Socket.Shutdown(SocketShutdown.Send)`. With that, peer (proxy or server if connected directly) would get EOF and handle that accordingly. Either one can still send data and shutdown/close when done. At this point client can read until EOF and shutdown/close when it arrives. 

That would be traditional gracefull TCP close, however there is no time limit for TCP half-closed state. This can be tricky if peer misbehaves, there is network outage or some firewall along the way kicks in because connections was idle too long. 
So the client should probably have some mechanism to put limit of reading the response from the server. 

Alternatively if the client does not want to wait or care about the response you can do abortive close. That would send `RST` to the peer and the TCP session would be closed immediately.
