### ISSUE TITLE
Suggestion: run linters and formatters on PRs

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#10320]
GitHub has a new section in PR that shows checks:

![image](https://user-images.githubusercontent.com/33230602/39961331-6950b8fc-563c-11e8-98af-f44fb5adecfb.png)

In CoreCLR and CoreFX, in lieu of `Windows_NT x64 Formatting` CI job, this [Checks feature](https://help.github.com/articles/about-status-checks/#checks) can run:

* C# code formatter (https://github.com/dotnet/codeformatter)
* Clang-format for c/cpp/h files

and highlight when output of `diff changedFileX.cs $(codeformatter codeFileX.cs)` is non-empty.

**Comment by stephentoub** [comment]
The original poster of this issue deleted their account and is now a "ghost", so I'm going to close this issue.  Thanks.
