### ISSUE TITLE
Change in 1.27.12-preview breaks Moq/AutoMock with loose behavior

### ISSUE THREAD

**Issue by spankr** [dotnet/runtime#103281]
### Description

Our team came across this issue when upgrading from 1.25.3. We narrowed it down to the change in 1.27.12-preview, specifically the [feature for supporting parameters as query string](https://github.com/bUnit-dev/bUnit/commit/8f99afa6269b16439b33c400ef07d64d3f3a9b38).

The change to src/bunit.web/TestContext.cs is asking the `IServiceProvider` for an implementation of `IComponentActivator` and then implementing `WebTestRenderer` with it, if it finds one.

The issue for us is that we use AutoMock as [the fallback provider](https://bunit.dev/docs/providing-input/inject-services-into-components.html). We use loose behavior for mocking (for anyone unfamiliar with mocking behaviors, "loose" essentially means that if a mock is not pre-defined, a default one will be generated/provided for your test.). This means that when line 92 in TestContext.cs asks for an `IComponentActivator`, AutoMock provides a mocked implementation (and not null).

Our tests then die horribly with this complaint:

```
System.InvalidOperationException
The component activator returned a null value for a component of type
OurNameSpace.UnitTests.OurTestClass.CanCreateComponent+TestComponent.
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
```

### Reproduction Steps

We have a simple test scenario

```c#
@inherits OurTestBase

@code {
    [Fact]
    public void CanRenderTestComponent()
    {
        RenderComponent<TestComponent>();
    } 
    
    /// <summary>
    /// Just a component for testing
    /// </summary>
    class TestComponent : ComponentBase { }
}
```

and our test base class

```c#
    public class OurTestBase : TestContext
    {
        public OurTestBase()
        {
            JSInterop.Mode = JSRuntimeMode.Loose;
            Services.Add(ServiceDescriptor.Singleton(JSInterop));
            // Setup the automocker to use BUnit's mocked IJSRuntime
            _mock.Use(JSInterop.JSRuntime);

            // Attach Automocker here
            Services.AddFallbackServiceProvider(new AutoMockerServiceProvider(_mock));
        }

        protected readonly AutoMocker _mock = new AutoMocker(MockBehavior.Loose);

        private class AutoMockerServiceProvider : IServiceProvider
        {
            public AutoMockerServiceProvider(AutoMocker mock)
            {
                _mock = mock;
            }

            public object? GetService(Type serviceType)
            {
                return _mock.Get(serviceType);
            }

            private readonly AutoMocker _mock;
        }
    }
```

It's a hack but this modification to our code bypasses the problem for us:

```c#
            public object? GetService(Type serviceType)
            {
                // 2024.06.10 - Bunit gets angry if you provide a mock of IComponentActivator
                if (serviceType == typeof(IComponentActivator))
                    return null;

                return _mock.Get(serviceType);
            }
```

### Expected behavior

That our tests run without a low-level error in `Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent`.

### Actual behavior

Test failure with

```
System.InvalidOperationException
The component activator returned a null value for a component of type OurNameSpace.UnitTests.OurTestClass.CanCreateComponent+TestComponent.
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
...
```

### Known Workarounds

When setting up the FallbackServiceProvider, add a check for the type of `IComponentActivator` and return null.

### Other information

[Commit 8f99afa](https://github.com/bUnit-dev/bUnit/commit/8f99afa6269b16439b33c400ef07d64d3f3a9b38)

src/bunit.web/TestContext.cs, lines 92-95:

```c#
var componentActivator = Services.GetService<IComponentActivator>();
return componentActivator is null
	? new WebTestRenderer(renderedComponentActivator, Services, logger)
	: new WebTestRenderer(renderedComponentActivator, Services, logger, componentActivator);
```

**Comment by julealgon** [comment]
That check for `null` and the branch in the code seems like terrible design to me. Instead, bUnit should just register a default component activator using the null-object pattern and pass that.

This completely removes the `null` check while avoiding the issue here by having an actual registration for `IComponentActivator`.

Why is this issue not in the bUnit-dev repo though?

**Comment by spankr** [comment]
> That check for `null` and the branch in the code seems like terrible design to me. Instead, bUnit should just register a default component activator using the null-object pattern and pass that.
> 
> This completely removes the `null` check while avoiding the issue here by having an actual registration for `IComponentActivator`.
> 
> Why is this issue not in the bUnit-dev repo though?

Sunuva... you're right. My bad.

**Comment by spankr** [comment]
This is completely in the wrong spot. Thank @julealgon for pointing that out!

**Comment by julealgon** [comment]
@spankr , use the "close as unplanned" option for this to avoid misleading folks that something was implemented in the runtime repo.

**Comment by spankr** [comment]
Closing as unplanned

**Comment by spankr** [comment]
x

**Comment by spankr** [comment]
x
