### ISSUE TITLE
Configuration: IList properties initialized with Array.Empty not deserialized

### ISSUE THREAD

**Issue by Foorcee** [dotnet/runtime#103282]
### Describe the bug
When using .NET configuration, properties of type `IList` are not deserialized correctly if they are initialized with `Array.Empty<T>()`. However, if the same properties are initialized with `new List<T>()`, deserialization works as expected. Additionally, string arrays initialized with `Array.Empty<T>()` also deserialize correctly.

#### Configuration
```json
{
  "Strings": ["abc"],
  "StringList": ["abc"],
  "StringArray": ["abc"]
}
```

#### Example
```csharp
var config = new ConfigurationBuilder()
    .AddJsonFile("config.json").Build();
var obj = config.Get<TestConfig>();

public class TestConfig
{
    // IList: Initialize with Array.Empty<T>()
    public IList<string> Strings { get; set; } = Array.Empty<string>();

    // IList: Initialize with new List<T>()
    public IList<string> StringList { get; set; } = new List<string>();

    // Array: Initialize with Array.Empty<T>()
    public string[] StringArray { get; set; } = Array.Empty<string>();

    public override string ToString()
    {
        return
            $"{nameof(Strings)}: {string.Join(",", Strings)}," +
            $" {nameof(StringList)}: {string.Join(",", StringList)}," +
            $" {nameof(StringArray)}: {string.Join(",", StringArray)}";
    }
}
```
#### Result
```plaintext
Strings: , StringList: abc, StringArray: abc
```

#### Observed Behavior
- `Strings` (initialized with `Array.Empty<T>()`) is not deserialized and remains empty.
- `StringList` (initialized with `new List<T>()`) is deserialized correctly.
- `StringArray` (initialized with `Array.Empty<T>()`) is deserialized correctly.

### Further technical details
Microsoft.Extensions.Configuration: 8.0.0
Microsoft.Extensions.Configuration.Binder: 8.0.1
Microsoft.Extensions.Configuration.Json: 8.0.0

`dotnet --info`
```
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.4e5ea2d8
 MSBuild version:   17.10.4+10fbfbf2e

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

Installierte .NET-Workloads:
 [aspire]
   Installationsquelle: VS 17.10.34928.147
   Manifestversion:    8.0.0/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Installationstyp:              Msi


Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.417 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by julealgon** [comment]
`Array.Empty<T>` produces an immutable empty array. It cannot be added to. I imagine that if you remove the `set;` on the `StringArray` property, you should see the same behavior in the deserialized payload: empty

What seems to be happening here is that the configuration system is constructing and assigning a new array for you for the `StringArray` property, but attempting to add to the `IList` property.

I think the more correct thing to do here is to just drop the setters and use `new List` though, so that the properties are immutable but the underlying collections are not and can be added to.

Initializing to `Array.Empty<T>` is always a mistake for writable collections IMHO.

**Comment by tarekgh** [comment]
@julealgon is correct in his analysis. 

> I think the more correct thing to do here is to just drop the setters and use new List though, so that the properties are immutable but the underlying collections are not and can be added to.

I don't think this is correct either. Imagine if someone initialized the property with non-empty array instead? You cannot drop that and create a new List<T> for it. The right fix here not using arrays to initialize the List properties.

**Comment by julealgon** [comment]
@tarekgh 
> > I think the more correct thing to do here is to just drop the setters and use new List though, so that the properties are immutable but the underlying collections are not and can be added to.
> 
> I don't think this is correct either. Imagine if someone initialized the property with non-empty array instead? You cannot drop that and create a new List for it. The right fix here not using arrays to initialize the List properties.

That's not how it works I'm pretty sure. Even if you have a setter, and you use an array with a set of values pre-initialized in the model itself, it will _still_ only add other sources to it and never "clear" the original array.

Take this example here:

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
{
    ["Section:Collection:[0]"] = "1",
    ["Section:Collection:[1]"] = "2",
    ["Section:Collection:[2]"] = "3",
});

builder.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
{
    ["Section:Collection:[0]"] = "90",
    ["Section:Collection:[1]"] = "100",
});

builder.Services.AddOptions<OptionsModel>().BindConfiguration("Section");

var app = builder.Build();

var options = app.Services.GetRequiredService<IOptions<OptionsModel>>().Value;

public class OptionsModel
{
    public int[] Collection { get; set; } = [4, 5, 6, 7];
}
```

If you observe the final results on the `Collection` property it will have:
```csharp
[4, 5, 6, 7, 90, 100, 3]
```

So I still think the best practice of not having setters on these collection properties should hold in general.

**Comment by tarekgh** [comment]
I am talking about when having the property type is IList<T>.  Change `OptionsModel` to the following and you'll see what I mean:

```C#
    public class OptionsModel
    {
        public IList<int> Collection { get; set; } = new int[] { 4, 5, 6, 7 };
    }

```

**Comment by julealgon** [comment]
> I am talking about when having the property type is IList. Change `OptionsModel` to the following and you'll see what I mean:
> 
> ```cs
>     public class OptionsModel
>     {
>         public IList<int> Collection { get; set; } = new int[] { 4, 5, 6, 7 };
>     }
> ```

I'm sorry but I'm still not following you. If I make the change to initialize with a fixed array like that, all I get is an exception if I attempt to call `.Clear`, or if I remove those manual `Configure` calls, the values from configuration are just not honored at all (since the array is immutable) and I get the expected `[4, 5, 6, 7]` as the final output. The system does _not_ try to create new arrays and assign them in this situation, even with a setter in place.

Do let me know if I'm still missing something here.

**Comment by tarekgh** [comment]
Sorry it looks I am the one confused you with my comment https://github.com/dotnet/runtime/issues/103282#issuecomment-2163425312. in another word, I misunderstood your comment `I think the more correct thing to do here is to just drop the setters and use new List though, so that the properties are immutable but the underlying collections are not and can be added to.`. I think now we are both in same page and I agree with what you have said in https://github.com/dotnet/runtime/issues/103282#issuecomment-2160924687.
