### ISSUE TITLE
Type.GetType(string) can't find type if assembly loaded using AssemblyLoadContext

### ISSUE THREAD

**Issue by Kkamikadzee** [dotnet/runtime#103222]
### Description

It is impossible to get a type by its name using the `Type.GetType(string)` method, if the type is contained in an assembly that was loaded using the `AssemblyLoadContext`.

### Reproduction Steps

**_Plugin:_**
**Plugin.csproj**
```targets
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutDir>$(SolutionDir)/GetTypeAndAlcProblem/bin/$(Configuration)/</OutDir>
    </PropertyGroup>
</Project>
```
**Stuff.cs**
```csharp
namespace Plugin;

public record Stuff(int Value);
```

**_App:_**
**GetTypeAndAlcProblem.csproj**
```targets
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
</Project>
```
**Program.cs**
```csharp
using System.Reflection;
using System.Runtime.Loader;

AssemblyLoadContext context = new("_");
Assembly plugin = context.LoadFromAssemblyPath(
    Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!, "Plugin.dll"));
Type fromPlugin = plugin.GetType("Plugin.Stuff")!;
Type? linqFind = AppDomain.CurrentDomain.GetAssemblies()
    .Single(a => a.GetName().Name == "Plugin")
    .GetType("Plugin.Stuff");
Type? usingAssemblyQualifiedName = Type.GetType(fromPlugin.AssemblyQualifiedName!);
Type? usingNameAndAssembly = Type.GetType("Plugin.Stuff, Plugin");

Console.WriteLine($"Type from assembly returned ALC: {fromPlugin.AssemblyQualifiedName ?? "null"}");
Console.WriteLine($"Type from assembly iterating: {linqFind?.AssemblyQualifiedName ?? "null"}");
Console.WriteLine($"Type from GetType using `AssemblyQualifiedName`: {usingAssemblyQualifiedName?.AssemblyQualifiedName ?? "null"}");
Console.WriteLine($"Type from GetType using type name and assembly name: {usingNameAndAssembly?.AssemblyQualifiedName ?? "null"}");
```

### Expected behavior

The Type.GetType(string) method should return a type similar to what would be returned if the assembly was loaded using "Assembly.LoadFrom".

Program.cs
```csharp
using System.Reflection;

Assembly plugin = Assembly.LoadFrom(
    Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!, "Plugin.dll"));
Type fromPlugin = plugin.GetType("Plugin.Stuff")!;
Type? linqFind = AppDomain.CurrentDomain.GetAssemblies()
    .Single(a => a.GetName().Name == "Plugin")
    .GetType("Plugin.Stuff");
Type? usingAssemblyQualifiedName = Type.GetType(fromPlugin.AssemblyQualifiedName!);
Type? usingNameAndAssembly = Type.GetType("Plugin.Stuff, Plugin");

Console.WriteLine($"Type from assembly returned ALC: {fromPlugin.AssemblyQualifiedName ?? "null"}");
Console.WriteLine($"Type from assembly iterating: {linqFind?.AssemblyQualifiedName ?? "null"}");
Console.WriteLine($"Type from GetType using `AssemblyQualifiedName`: {usingAssemblyQualifiedName?.AssemblyQualifiedName ?? "null"}");
Console.WriteLine($"Type from GetType using type name and assembly name: {usingNameAndAssembly?.AssemblyQualifiedName ?? "null"}");
```

Output:
```
Type from assembly returned ALC: Plugin.Stuff, Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Type from assembly iterating: Plugin.Stuff, Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Type from GetType using `AssemblyQualifiedName`: Plugin.Stuff, Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Type from GetType using type name and assembly name: Plugin.Stuff, Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

### Actual behavior

Output when using ALC:
```
Type from assembly returned ALC: Plugin.Stuff, Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Type from assembly iterating: Plugin.Stuff, Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Type from GetType using `AssemblyQualifiedName`: null
Type from GetType using type name and assembly name: null
```

### Regression?

In .NET 6 and .NET 8, the behavior is equivalent.

### Known Workarounds

Iterating all loaded assemblies in domain.
```csharp
Type? type = AppDomain.CurrentDomain.GetAssemblies()
    .SingleOrDefault(a => a.GetName().Name == "Plugin")
    .GetType("Plugin.Stuff");
```
or
```csharp
Type? type = Type.GetType("Plugin.Stuff, Plugin",
    assemblyName => AppDomain.CurrentDomain.GetAssemblies()
        .SingleOrDefault(assembly => assembly.GetName().Name == assemblyName.Name),
    (assembly, typeName, throwOnError) => assembly?.GetType(typeName, throwOnError));
```

### Configuration

.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.301/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  3.1.426 [/usr/share/dotnet/sdk]
  6.0.420 [/usr/share/dotnet/sdk]
  8.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.28 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by huoyaoyuan** [comment]
This should be expected.

See the documentation at https://learn.microsoft.com/dotnet/fundamentals/runtime-libraries/system-type-gettype#usage-notes :

> If `typeName` is not an assembly-qualified name, assembly resolution is skipped. Unqualified type names can be resolved in the context of mscorlib.dll/System.Private.CoreLib.dll or the currently executing assembly, or you can optionally provide an assembly in the `typeResolver` parameter.

Since the host application is typically in default ALC, this method won't search for other ALCs.

**Comment by Kkamikadzee** [comment]
> Since the host application is typically in default ALC, this method won't search for other ALCs.

The only solution is iterate through the loaded assemblies? Or is there some trick with "Assembly Load Context.All"?

**Comment by jkotas** [comment]
You can provide a callback to `Type.GetType` to load the types from your AssemblyLoadContext:

`Type.GetType("Plugin.Stuff, Plugin", (an) => context.LoadFromAssemblyName(an), null)`

**Comment by Kkamikadzee** [comment]
> You can provide a callback to `Type.GetType` to load the types from your AssemblyLoadContext:
> 
> `Type.GetType("Plugin.Stuff, Plugin", (an) => context.LoadFromAssemblyName(an), null)`

Unfortunately, the class that is attempting to access the type information is located in the default context and is not aware of the existence of any plugins.

**Comment by jkotas** [comment]
You can consider [AssemblyLoadContext.ContextualReflectionScope](https://learn.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.contextualreflectionscope) to override the current context used by reflection APIs like `Type.GetType`. This will only work if you are able to insert it around the calls that are attempting to access the type information.

If this does not work, the hack with iterating all assemblies is equivalent to not using assembly load context at all. You are giving up the isolation that assembly load contexts provide by iterating all assemblies in the process. You may consider loading everything in the default context instead.

**Comment by Kkamikadzee** [comment]
Thank you very much for your assistance.
