### ISSUE TITLE
GC commits twice the limit when using large pages

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#103203]
### Description

While playing with large pages, I noticed an odd behavior. The GC commits twice the amount of memory set in `GCHeapHardLimit`, despite enforcing the limit as expected.

So for instance, if I set the heap limit to `DOTNET_GCHeapHardLimit=20000000` (512 MB)  and `DOTNET_GCLargePages=1`, the "private bytes" of the process are 1GB, and yet the application will throw OOM after allocating ~512MB in total (it doesn't matter if it's SOH/LOH/POH).

If I manually set the limits for each heap with `DOTNET_GCHeapHardLimitSOH`/`DOTNET_GCHeapHardLimitLOH`/`DOTNET_GCHeapHardLimitPOH` then the GC behaves as expected and commits the total of the three limits.

Note that I don't actually use large pages in a real application, I was just fooling around, so it's really low priority.

### Reproduction Steps

Build an application that tries to fill the memory:

```
internal class Program
{
    private static object[] _sohBag = new object[100_000];
    private static object[] _lohBag = new object[100_000];
    private static object[] _pohBag = new object[100_000];

    static long FillLoh()
    {
        var counter = 0;

        try
        {
            while (true)
            {
                _lohBag[counter++] = new byte[1024 * 1024];
            }
        }
        catch (OutOfMemoryException)
        {
        }

        return counter;
    }

    static long FillPoh()
    {
        var counter = 0;

        try
        {
            while (true)
            {
                _pohBag[counter++] = GC.AllocateArray<byte>(80_000, pinned: true);
            }
        }
        catch (OutOfMemoryException)
        {
        }

        return (counter * 80_000) / (1024 * 1024);
    }

    static long FillSoh()
    {
        var counter = 0;

        try
        {
            while (true)
            {
                _sohBag[counter++] = new byte[50_000];
            }
        }
        catch (OutOfMemoryException)
        {
        }

        return (counter * 50_000) / (1024 * 1024);
    }

    static void Main(string[] args)
    {
        while (true)
        {
            var process = Process.GetCurrentProcess();

            Console.WriteLine($"Working set: {process.WorkingSet64 / (1024.0 * 1024)}, Private bytes: {process.PrivateMemorySize64 / (1024.0 * 1024)}");
            
            Console.WriteLine($"Allocated {FillPoh()} MB in POH");
            Console.WriteLine($"Allocated {FillLoh()} MB in LOH");
            Console.WriteLine($"Allocated {FillSoh()} MB in SOH");

            return;
        }
    }
}
```

Then run it with `DOTNET_GCLargePages=1` and `DOTNET_GCHeapHardLimit=20000000`

### Expected behavior

The GC commits 512 MB of memory and starts throwing OOM after 512 MB are used across the heaps.

### Actual behavior

The GC commits 1024 MB of memory and starts throwing OOM after 512 MB are used across the heaps.

```
Working set: 16.3359375, Private bytes: 1029.31640625
Allocated 447 MB in POH
Allocated 30 MB in LOH
Allocated 15  MB in SOH
```

**Comment by mangod9** [comment]
This appears to be by design, @cshung?

**Comment by cshung** [comment]
> This appears to be by design, @cshung?

Yes, this is by design.

In the old days, in order to allow 512MB to be used under segments, we have no choice but to preallocate 512MB for SOH and then 512MB for LOH. We know the application is not going to use them all, but we have no idea where the allocation will land.

With the introduction of POH, that will becomes 3 times, to the point we believe this is not a sustainable solution, so we allow the user to specify the limits per object heap, that way we can preallocate the exact amount as user requested without having to double/triple the allocation.

Region lifted the constraint by allowing regions to be freely moved between different generations/object heaps. Still, we kept the old design, just to have no surprises.
