### ISSUE TITLE
SG unit tests are incredibly slow when run in Debug because they run on top of a Debug CoreCLR

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#103227]
Reproduction:
1) Build the repo to a reasonable state (`./build clr+libs`, perhaps some more components depending on what tests are being run).
2) Try to `dotnet test -c Debug` an SG unit test project. The one I was working on is `JSImportGenerator.Unit.Tests.csproj`, but this issue should apply to all of them equally.
3) Fix/workaround the build breaks if any.
4) Wait and see.

Step `4` will take a very very long time because the tests will run on top of Debug CoreCLR. This is not suport important for `dotnet test` experience specifically (you can `-c Release` to fix it), but it is important for debugging ("Debug Tests" functionality in VS).

I had to work around this issue like so:
```diff
--- a/src/libraries/System.Runtime.InteropServices.JavaScript/tests/JSImportGenerator.UnitTest/JSImportGenerator.Unit.Tests.csproj
+++ b/src/libraries/System.Runtime.InteropServices.JavaScript/tests/JSImportGenerator.UnitTest/JSImportGenerator.Unit.Tests.csproj
@@ -3,7 +3,9 @@
     <TargetFramework>$(NetCoreAppCurrent)</TargetFramework>
     <Nullable>enable</Nullable>
     <TestRunRequiresLiveRefPack>true</TestRunRequiresLiveRefPack>
-    <IgnoreForCI Condition="'$(TargetsMobile)' == 'true' or '$(TargetsLinuxBionic)' == 'true' or '$(TargetArchitecture)' == 'ARMv6'">true</IgnoreForCI>
+    <IgnoreForCI Condition="'$(TargetsMobile)' == 'true' or '$(TargetsLinuxBionic)' == 'true' or '$(TargetArchitecture)' == 'ARMv6'">true</IgnoreForCI>
+
+    <RunSettingsDotNetHostPath>C:\Users\Accretion\source\dotnet\runtimelab\artifacts\bin\testhost\net9.0-windows-Release-x64\dotnet.exe</RunSettingsDotNetHostPath>
   </PropertyGroup>
   <ItemGroup>
     <Compile Include="$(CommonTestPath)SourceGenerators\LiveReferencePack.cs" Link="Common\SourceGenerators\LiveReferencePack.cs" />
```
The instinctive workaround of `/p:RuntimeConfiguration=Release` did not work.

Perhaps it would make sense to run SG unit tests on top of a `Release` runtime and error out if it has not been built. Perhaps there is, or could be, some better workaround.

**Comment by SingleAccretion** [comment]
`RuntimeConfiguration` does not work here due to how these things are defined.

https://github.com/dotnet/runtime/blob/e6c2e536b85e3d8412c3b669a81b7baaf329fcb3/eng/testing/runsettings.targets#L30

https://github.com/dotnet/runtime/blob/e6c2e536b85e3d8412c3b669a81b7baaf329fcb3/src/libraries/Directory.Build.targets#L15-L20

It is partially what this issue is about.

**Comment by ViktorHofer** [comment]
`NetCoreAppCurrentBuildSettings` and other properties refer to the `testhost` folder which contains the host, shared framework and the runtime bits. It's correct that when running a Debug build/test, that the Debug testhost folder is used. By invoking the `libs.pretest` subset as documented above, you should get the Release runtime but with the debug libraries. Doesn't that work?

**Comment by SingleAccretion** [comment]
I see what you are saying. I did not realize that the contents of the folder are meant to be overwriteable (i. e. are not a pure function of the input configurations). Thank you.
