### ISSUE TITLE
x64 test failure: DeserializeStoredObjects strings differ.

### ISSUE THREAD

**Issue by michaelgsharp** [dotnet/runtime#103367]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=704412
Build error leg or test failing: System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects
Pull request: https://github.com/dotnet/runtime/pull/103244

## Error Message
System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects(value: sdfsdf, serializedData: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue])
Exception Message
Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "myns1"
Actual:   ""
Stack Trace
   at BinaryFormatTests.FormatterTests.EqualityExtensions.IsEqual(DataTable this, DataTable other, Boolean isSamePlatform) in /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/EqualityExtensions.cs:line 253
   at InvokeStub_EqualityExtensions.IsEqual(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Expected: \"myns1\"",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=704412
**Error message validated:** `[Expected: "myns1"`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/12/2024 6:53:15 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[709580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709580)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709580&view=ms.vss-test-web.build-test-results-tab&runId=17719798&resultId=126950)|dotnet/runtime#100334|
|[709426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709426)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709426&view=ms.vss-test-web.build-test-results-tab&runId=17715378&resultId=157610)|dotnet/runtime#99555|
|[709287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709287)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709287&view=ms.vss-test-web.build-test-results-tab&runId=17710398&resultId=160895)||
|[709244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709244)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709244&view=ms.vss-test-web.build-test-results-tab&runId=17709274&resultId=163940)|dotnet/runtime#103379|
|[708815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708815)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708815&view=ms.vss-test-web.build-test-results-tab&runId=17695332&resultId=131655)|dotnet/runtime#103508|
|[708353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708353)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708353&view=ms.vss-test-web.build-test-results-tab&runId=17684060&resultId=148990)|dotnet/runtime#103381|
|[708285](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708285)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708285&view=ms.vss-test-web.build-test-results-tab&runId=17682210&resultId=144385)|dotnet/runtime#103324|
|[708329](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708329)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708329&view=ms.vss-test-web.build-test-results-tab&runId=17683030&resultId=153389)|dotnet/runtime#103444|
|[708106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708106)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708106&view=ms.vss-test-web.build-test-results-tab&runId=17675762&resultId=150011)|dotnet/runtime#103241|
|[708015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708015)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708015&view=ms.vss-test-web.build-test-results-tab&runId=17674362&resultId=172688)|dotnet/runtime#103370|
|[707989](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707989)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707989&view=ms.vss-test-web.build-test-results-tab&runId=17673236&resultId=129458)|dotnet/runtime#103441|
|[707860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707860)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707860&view=ms.vss-test-web.build-test-results-tab&runId=17667428&resultId=115316)|dotnet/runtime#103473|
|[707826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707826)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707826&view=ms.vss-test-web.build-test-results-tab&runId=17666350&resultId=141010)|dotnet/runtime#103412|
|[707560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707560)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707560&view=ms.vss-test-web.build-test-results-tab&runId=17657828&resultId=174454)|dotnet/runtime#103454|
|[706227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706227)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706227&view=ms.vss-test-web.build-test-results-tab&runId=17618246&resultId=134957)|dotnet/runtime#103394|
|[706230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706230)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706230&view=ms.vss-test-web.build-test-results-tab&runId=17618028&resultId=152913)|dotnet/runtime#103363|
|[706214](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706214)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706214&view=ms.vss-test-web.build-test-results-tab&runId=17618006&resultId=156197)|dotnet/runtime#103382|
|[706149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706149)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706149&view=ms.vss-test-web.build-test-results-tab&runId=17616198&resultId=146169)|dotnet/runtime#103143|
|[705166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705166)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705166&view=ms.vss-test-web.build-test-results-tab&runId=17587388&resultId=165098)|dotnet/runtime#103159|
|[704412](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704412)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704412&view=ms.vss-test-web.build-test-results-tab&runId=17562032&resultId=172878)|dotnet/runtime#103244|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|20|20|

**Comment by vcsjones** [comment]
Test introduced by #102379, cc @adamsitnik
