### ISSUE TITLE
Visual Studio 2022 and .Net 8.0

### ISSUE THREAD

**Issue by pko67** [dotnet/runtime#103335]
### Description

Why does my Visual Studio Professional not show the target platform .Net 8.0?

Environment: Visual Studio Professional 2022 Version 17.10.2

### Reproduction Steps

Try to set the .Net Framework as target platform in the options dialog of an C# dll.

### Expected behavior

Expect, that the Visual Studio shows the Framework 8.0 as an option in target platform for an existing C# dll project.

### Actual behavior

.Net 8.0 is not showing

### Configuration

dotnet --info
.NET SDK:
 Version:           8.0.301
OS runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]
  8.0.301 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  ... old versions starting with 2.1.30
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Environment variables:
  Not set
global.json file:
  Not found

**Comment by huoyaoyuan** [comment]
The question belongs to https://github.com/dotnet/project-system.

Can you show which dialog you are using? Are you trying to change the target platform from .NET Framework to .NET 8?

.NET Framework and .NET Core/.NET 5+ are different series of platforms. The Visual Studio UI currently doesn't support to switch between them. You have to edit the project file yourself.

**Comment by pko67** [comment]
answered in that post
https://stackoverflow.com/questions/78611838/visual-studio-2022-and-net-8-0
