### ISSUE TITLE
Fully unhandled exceptions break debugger with empty stack

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#103385]
### Description

This is very similar to #101729, but in that issue, I wasn't clear if we were discussing user-unhandled exceptions (debugger stopping at the catch handler found) or fully unhandled exceptions. User-unhandled was addressed by the fix for #101729, but fully unhandled is still a problem.

### Reproduction Steps

Follow the same repro steps from #101729, but disable "Just My Code" before starting debugging

### Expected behavior

Debugger should break while there are still frames on the call stack

### Actual behavior

All frames are unwound when the debugger breaks

### Regression?

Regression from .NET 8

### Known Workarounds

Set the environment variable `DOTNET_LegacyExceptionHandling` to `1`

### Configuration

.NET 9 Preview 5 on Windows x64. I didn't try any other configuration.

**Comment by gregg-miskelly** [comment]
CC @janvorli

**Comment by janvorli** [comment]
I have a fix, I will create a PR later today.
