### ISSUE TITLE
cannot run winform app in dotnet 9 preview 6

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#103329]
### Description

when i use dotnet run, it required install dotnet
![image](https://github.com/dotnet/runtime/assets/126905141/4067a24c-52ec-4a02-ba52-244c0021437f)

### Reproduction Steps

dotnet run

### Expected behavior

run sucessfully

### Actual behavior

required install dotnet version

**Comment by NCLnclNCL** [comment]
> Did you run the installer or just extract it? The `Microsoft.NETCore.Sdk` folder needs to be in `C:\Program Files\dotnet`, but it looks like it's in your downloads.

I run with path to dotnet.exe, dotnet 9 preview 5 runs normally

**Comment by huoyaoyuan** [comment]
> I run with path to dotnet.exe, dotnet 9 preview 5 runs normally

When managing multiple installations with dotnet, it's particularly important to use the correct `dotnet.exe`. Running `dotnet --info` also gives you information.
