### ISSUE TITLE
[API Proposal]: Employ `allows ref struct` in comparer interfaces

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#103323]
EDITED on 6/17/2024 by @stephentoub to add more interfaces

### Background and motivation

Similar to https://github.com/dotnet/runtime/issues/102671.
Similar to https://github.com/dotnet/runtime/issues/103270.
I discovered this gap as I attempted to pre-emptively implement .NET 9 `allows ref struct` on some of my own APIs behind a `#if` to see which APIs missing it would cause me problems.
We have done the same thing for `IEnumerable<T>` and `IEnumerator<T>` already.

### API Proposal

```diff
namespace System.Collections.Generic;

public interface IComparable<T>
+   where T : allows ref struct
{
    ...
}

public interface IComparer<in T>
+   where T : allows ref struct
{
    ...
}

public interface IEquatable<T>
+   where T : allows ref struct
{
    ...
}

public interface IEqualityComparer<in T>
+    where T : allows ref struct
{
    ...
}

public interface IAlternateEqualityComparer<in TAlternate, T>
    where TAlternate : allows ref struct
+   where T : allows ref struct
{
    ...
}
```

### API Usage

```csharp
struct SpanSequenceComparer<T> : IEqualityComparer<ReadOnlySpan<T>>, IEqualityComparer<Span<T>>
{
    public readonly bool Equals(ReadOnlySpan<T> x, ReadOnlySpan<T> y)
    {
        if (x.Length != y.Length) return false;
        for (int i = 0; i < x.Length; i++)
        {
            if (!EqualityComparer<T>.Default.Equals(x[i], y[i])) return false;
        }
        return true;
    }

    public readonly bool Equals(Span<T> x, Span<T> y) => Equals((ReadOnlySpan<T>)x, (ReadOnlySpan<T>)y);

    public readonly int GetHashCode(ReadOnlySpan<T> obj)
    {
        HashCode hc = new();
        hc.Add(obj.Length);
        for (int i = 0; i < obj.Length; i++) hc.Add(EqualityComparer<T>.Default.GetHashCode(obj[i]));
        return hc.ToHashCode();
    }

    public readonly int GetHashCode(Span<T> obj) => GetHashCode((ReadOnlySpan<T>)obj);
}
```

### Alternative Designs

Also implement on readonly collection types:
```diff
public interface IReadOnlyCollection<out T>
+    where T : allows ref struct
{
    ...
}

public interface IReadOnlyList<out T>
+    where T : allows ref struct
{
    ...
}

public interface IReadOnlySet<T>
+    where T : allows ref struct
{
    ...
}
```

### Risks

These are interfaces, so none really.

**Comment by eiriktsarpalis** [comment]
Having written `ISpanEqualityComparer<T>` interfaces before, I can see the value in doing this to the comparison types. I would probably add it to some of the helper methods as well, such as `EqualityComparer<T>.Create`, `Comparison<T>` and `Comparer<T>.Create`.

Not sure if there's huge value in propagating this to all collection interfaces though, we did this with `IEnumerable<T>` and the use cases are limited, to say the least. Wouldn't hurt adding them either.

@stephentoub thoughts?

**Comment by eiriktsarpalis** [comment]
@hamarb123 would it be possible to update the API proposal to reflect feedback?

**Comment by hamarb123** [comment]
> I'm skeptical of other interfaces like `ICollection<T>`, where you need to implement methods like `Add(T)`. In fact looking at the interface, I don't think that's even possible, since it uses `T[]` in its APIs and that can't be done with a ref struct.

My understanding is that implementing `ICollection<T>` and `IList<T>`, even when mutating is not possible, and even when resizing makes no sense, is very common. For example, [ImmutableArray\<T\>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1?view=net-8.0) implements all the collection interfaces (other than the set ones obviously).

> We can't do `Comparer<T>.Create`, at least not without changing other code in its implementation, because that generic parameter is on the type level and the `T` is already used in unsupported ways.

I don't really see what the issue is here - are you talking about the non-generic API overloads? Boxing is pretty easy to work around by using `RuntimeHelpers.Box` (I've already implemented my own helper API for boxing with `allows ref struct`).

**Comment by stephentoub** [comment]
> My understanding is that implementing ICollection<T> and IList<T>

It is simply not possible to mark the `T` in these interfaces as `allows ref struct`. `ICollection<T>.CopyTo` accepts a `T[]`.

> I don't really see what the issue is here

I wrote "at least not without changing other code in its implementation". If you try to mark the `T` in `Comparer<T>` as `allows ref struct`, it will not compile without doing surgery on the code.

**Comment by hamarb123** [comment]
Ok, I have updated it - I missed the `CopyTo` method when looking at them 😄

**Comment by eiriktsarpalis** [comment]
Even if technically feasible, I still question the value of allowing ref structs in the other collection interfaces, ref types seem fundamentally irreconcilable with these abstractions. IEnumerable is different in that respect since it can be used to implement streaming.

Which reminds me -- we should add `IAsyncEnumerable<T>`/`IAsyncEnumerator<T>` to that list.

**Comment by stephentoub** [comment]
> Which reminds me -- we should add IAsyncEnumerable<T>/IAsyncEnumerator<T> to that list.

Those are already annotated.

**Comment by eiriktsarpalis** [comment]
Oh, ok. I thought they had missed the first round.

**Comment by hamarb123** [comment]
> Even if technically feasible, I still question the value of allowing ref structs in the other collection interfaces, ref types seem fundamentally irreconcilable with these abstractions.

I don't think it's fundamentally irreconcilable at all - I think it makes perfect sense to have a `readonly` list where you're able to lookup a span at any index for example.

**Comment by eiriktsarpalis** [comment]
> I think it makes perfect sense to have a readonly list where you're able to lookup a span at any index for example.

I saw the example that you shared earlier, but I struggle to see how this could be considered a valid collection implementation or where it could be used meaningfully. Perhaps sharing the full implementation + a consuming application might illuminate things a bit more.

**Comment by stephentoub** [comment]
I don't think we should do this for any of the readonly collection ones, either. From my perspective, it's a mistake of history that IReadOnlyCollection doesn't include members like CopyTo, and I'd like to reserve the ability to add those later as DIMs, plus possibly methods like ToArray. Making T here allows ref struct ptevents us from ever doing so. I don't believe the reward outweighs the risk.

**Comment by hamarb123** [comment]
> I don't think we should do this for any of the readonly collection ones, either. From my perspective, it's a mistake of history that IReadOnlyCollection doesn't include members like CopyTo, and I'd like to reserve the ability to add those later as DIMs, plus possibly methods like ToArray. Making T here allows ref struct ptevents us from ever doing so. I don't believe the reward outweighs the risk.

Yeah, okay, I will remove them.

> I saw the example that you shared earlier, but I struggle to see how this could be considered a valid collection implementation or where it could be used meaningfully. Perhaps sharing the full implementation + a consuming application might illuminate things a bit more.

Sorry, I didn't get a chance to reply to this :)
