### ISSUE TITLE
FileSystemWatcher on sub-directory prevents parent directory from being renamed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#103383]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FileSystemWatcher-on-sub-directory-preve/10665049)._

---
Using a slight variation of this MS Learn example https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-8.0#examples

1. Create a parent directory and a sub-directory.
1. Put a `FileSystemWatcher` on the sub-directory (as per above example, although they may not all be needed)
1. Try to rename the parent directory (e.g. from File Explorer).

Expected behavior

1. Folder is renamed successfully
1. Perhaps FileSystemWatcher raises an appropriate changed event for the sub-directory. The full path is changed so I assume it should count as a change.

Actual behavior

1. Get this error ![image.png](https://aka.ms/dc/image?name=B80807a0baed448c1aa317cce7df0b814638520400409483400_20240523-154719-image.png&tid=80807a0baed448c1aa317cce7df0b814638520400409483400)

Interestingly, the parent directory is incorrectly locked against renaming, but deleting the parent folder succeeds. 

Source:

```
var parentDirectoryInfo = Directory.CreateTempSubdirectory(@"__watchertest");
var subDirectoryInfo = Directory.CreateDirectory(Path.Combine(parentDirectoryInfo.FullName, "foo"));

Console.WriteLine($"Parent directory: {parentDirectoryInfo.FullName}");

var subDirectoryWatcher = new FileSystemWatcher(subDirectoryInfo.FullName);
subDirectoryWatcher.NotifyFilter = NotifyFilters.Attributes
								| NotifyFilters.CreationTime
								| NotifyFilters.DirectoryName
								| NotifyFilters.FileName
								| NotifyFilters.LastAccess
								| NotifyFilters.LastWrite
								| NotifyFilters.Security
								| NotifyFilters.Size;

subDirectoryWatcher.Changed += OnChanged;
subDirectoryWatcher.Created += OnCreated;
subDirectoryWatcher.Deleted += OnDeleted;
subDirectoryWatcher.Renamed += OnRenamed;
subDirectoryWatcher.Error += OnError;

subDirectoryWatcher.IncludeSubdirectories = true;
subDirectoryWatcher.EnableRaisingEvents = true;

Console.WriteLine("Press enter to exit.");
Console.ReadLine();

static void OnChanged(object sender, FileSystemEventArgs e)
{
	if (e.ChangeType != WatcherChangeTypes.Changed)
	{
		return;
	}
	Console.WriteLine($"Changed: {e.FullPath}");
}

static void OnCreated(object sender, FileSystemEventArgs e)
{
	string value = $"Created: {e.FullPath}";
	Console.WriteLine(value);
}

static void OnDeleted(object sender, FileSystemEventArgs e) =>
   Console.WriteLine($"Deleted: {e.FullPath}");

static void OnRenamed(object sender, RenamedEventArgs e)
{
	Console.WriteLine($"Renamed:");
	Console.WriteLine($"    Old: {e.OldFullPath}");
	Console.WriteLine($"    New: {e.FullPath}");
}

static void OnError(object sender, ErrorEventArgs e) =>
   PrintException(e.GetException());

static void PrintException(Exception? ex)
{
	if (ex != null)
	{
		Console.WriteLine($"Message: {ex. Message}");
		Console.WriteLine("Stacktrace:");
		Console.WriteLine(ex. StackTrace);
		Console.WriteLine();
		PrintException(ex. InnerException);
	}
}
```

As another scenario I added another `FileSystemWatcher` to the parent directory and if I delete the parent directory from File Explorer, then undo the deletion to restore the parent directory there's some inconsistencies. The parent directory stops getting FSW notifications. But the sub-directory FSW continues to get events. Yet, it is now possible to rename the parent directory. 

---
#### Feedback Bot on 5/23/2024, 09:13 AM: 

(private comment, text removed)
#### anfirszo [MSFT] on 6/2/2024, 10:15 PM: 

(private comment, text removed)
#### Cameron Miller on 6/13/2024, 01:19 AM: 

(private comment, text removed)
#### Feedback Bot on 6/12/2024, 10:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Jozkee** [comment]
This is just how Windows works, it blocks directories with open handles. FSW acquires a handle for the watched directory [here](https://github.com/dotnet/runtime/blob/e498286ae283754721a282c338b698d7998a3687/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L32-L37). 

This is non-actionable for us as there's nothing we can do on our side, this is also not exclusive to FileSystemWatcher, as I already mentioned.
