### ISSUE TITLE
ConfigurationRoot GetValue behavior changed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#103353]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ConfigurationRoot-GetValue-behavior-chan/10673265)._

---
[severity:It's more difficult to complete my work] [regression]
The behavior of  ConfigurationRoot.GetValue(type,string,object) seems to have changed regarding NULL values:

`(public static object? GetValue( this IConfiguration configuration, [DynamicallyAccessedMembers( DynamicallyAccessedMemberTypes.All )] Type type, string key, object? defaultValue ))`

When the JSON configuration contains a NULL value ("Dashboard": null,), an empty string is returned instead of NULL.

This is annoying; I expect the configuration system to retrieve values exactly as specified.

As far as I remember, this behavior was different and correct, before I updated VisualStudio to the latest release.

The NuGet manager shows version 8.0.0 for the configuration packages, with the exception of Binder, which has 8.0.1.

Microsoft Visual Studio Professional 2022 (64-bit) - Current - Version 17.10.1

---
#### Feedback Bot on 6/2/2024, 06:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tarekgh** [comment]
Please provide some code samples to reproduce the issue. Thanks!
