### ISSUE TITLE
Unable to debug crash dump created on machine using Ubuntu 22.04 feed runtime.

### ISSUE THREAD

**Issue by jwilliamsonveeam** [dotnet/runtime#103377]
### Description

After reading that the Microsoft Feed will not support dotnet on Ubuntu 24.04.
[](https://github.com/dotnet/core/discussions/9258)
I need to find a away to debug crash dumps using dotnet from the Ubuntu feed. 

### Reproduction Steps

I create and ran a test app on using :
```
ubuntu 22.04
Microsoft.AspNetCore.App 8.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
```
`dotnet new console -n microsoft.botsay -f net8.0`

Change Program.cs to have a Console.Readline so the program hangs

In another session create a crash dump
`/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.5/createdump 720 /720dump`

Export the dump to windows and open 720Dump in Visual Studio.
Select "Debug with Managed Only" from the action panel.

### Expected behavior

Debugger starts.

### Actual behavior

![image](https://github.com/dotnet/runtime/assets/163468527/82f2d7be-e4ef-4c76-bd54-ce62eda161f6)

### From VS Output:
The minidump has no heap. Managed minidump debugging will have limited data inspection.
'720dump' (Linux): Loaded '/opt/veeamvboproxy/Veeam.Archiver.Proxy'. Module was built without symbols.
'720dump' (Linux): Loaded '/usr/lib/x86_64-linux-gnu/liblttng-ust-tracepoint.so.1.0.0'. Module was built without symbols.
'720dump' (Linux): Loaded '/usr/lib/x86_64-linux-gnu/libssl.so.3'. Module was built without symbols.
Error: Failed to download .NET debugging library 'mscordbi.dll' with build id 'elf-buildid-coreclr-e914926c9bacad6dac6f7281f8837b846df8c3c9'.
The program '720dump' has exited with code 0 (0x0).

I then though the correct version of mscordbi is probably in the ubuntu feed so I added this url to the symbol file locations:
![image](https://github.com/dotnet/runtime/assets/163468527/33cac72d-c6a9-4319-8c1b-d007007abe5f)
This resulted in the error about mscordbi.dll going away but I now have a new error:
![image](https://github.com/dotnet/runtime/assets/163468527/13993333-5c31-4c76-96dc-adbcc2446d71)

### OS
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### dotnet
Package: dotnet-runtime-8.0
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 67761
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: dotnet8 (8.0.105-8.0.5-0ubuntu1~22.04.1)
Version: 8.0.5-0ubuntu1~22.04.1
Depends: dotnet-hostfxr-8.0, libicu70, libc6 (>= 2.34), libgcc-s1 (>= 3.0), liblttng-ust1 (>= 2.13.0), libssl3 (>= 3.0.0~~alpha1), libstdc++6 (>= 12), zlib1g (>= 1:1.1.4)
Breaks: dotnet-runtime-6.0 (<< 6.0.111~)

Package: dotnet-sdk-8.0
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 302588
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: dotnet8 (8.0.105-8.0.5-0ubuntu1~22.04.1)
Version: 8.0.105-0ubuntu1~22.04.1
Depends: aspnetcore-runtime-8.0, aspnetcore-targeting-pack-8.0, dotnet-apphost-pack-8.0, dotnet-runtime-8.0, dotnet-targeting-pack-8.0, dotnet-templates-8.0, netstandard-targeting-pack-2.1-8.0, ca-certificates, libc6 (>= 2.34), libgcc-s1 (>= 3.0), libstdc++6 (>= 5.2)
Breaks: dotnet-sdk-6.0 (<< 6.0.111~)

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by hoyosjs** [comment]
CC: @richlander, if there's no support for such builds going forward - cross OS diagnostic stories won't have a way to work right now. Can only think of a few options, but we aren't guaranteed for them to work cleanly.

**Comment by jwilliamsonveeam** [comment]
@hoyosjs Thanks for the info. Will there be plans to support cross OS diagnostics in the future and if so do you know when?

**Comment by tommcdon** [comment]
Hi @jwilliamsonveeam we have no immediate plans to support cross OS dump diagnostics for source-built runtimes.  We have an epic tracking work that should provide this functionality in the future (please see "Future" section of the following issue): https://github.com/dotnet/runtime/issues/99298.  Please note that we do expect cross-OS dump diagnostics to work for Microsoft-built .NET runtime installs.  cc @richlander

**Comment by jwilliamsonveeam** [comment]
@tommcdon using the source built dotnet is it possible to debug the dump on a different machine with the same OS using the cli?

**Comment by tommcdon** [comment]
@jwilliamsonveeam Yes - as long as we can load the matching libcoreclr.so, libmscordaccore.so, libmscordbi.so that matches the dump, I would expect `dotnet-dump` or lldb+sos to be able to debug the dump.
