### ISSUE TITLE
Blazor WASM, cannot run or debug after enabling WasmEnableThreads.

### ISSUE THREAD

**Issue by BradChase2011** [dotnet/runtime#103499]
### Description

Not sure exactly where to put this so forgive me if this is the wrong place.  I have an application moved over to blazor webassembly and now I need to turn on multi threading.  It runs just fine using a test and debug points hit on the client wasm.  Without changing any code and putting in the WasmEnableThreads flag in the project, all of a sudden I get an error when trying to run in the output:

still waiting on run dependencies:
dependency: mono_pre_init
dependency: mono_wasm_pre_init_essential_async
(end of list)

It just keeps cycling that over and over and the browser shows nothing as well as none of the breakpoints get it any longer.
Is there any way I get find more information on this or is there another setting I need to enable or change?  I'm new to the web side of things.  We also have tried both ServeMultithreadingHeaders and adding the headers manually, same issue with the only change that breaks it is setting WasmEnableThreads.

Ultimately we cannot run without multi threading so we would really appreciate any input to move forward on this.  

### Reproduction Steps

Start a blazor webassembly project and put a break point in the client Program main.  Add WasmEnableThreads to the project and try running again.

### Expected behavior

Expected behavior would have the multi threading work atleast as well as the single thread.

### Actual behavior

Browser shows blank and this error keeps repeating in console:

still waiting on run dependencies:
dependency: mono_pre_init
dependency: mono_wasm_pre_init_essential_async
(end of list)

### Regression?

Tried with the latest 8 libraries and up, broken on all.

### Known Workarounds

none.

### Configuration

.NET SDK 9.0.100-preview.5, , Microsoft.AspNetCore.Components.WebAssembly 9.0.0-preview.5.24306.11, Microsoft.AspNetCore.Components.WebAssembly.Server 9.0.0-preview.5.24306.11.
Browser wasm.
Chrome and Edge.

**Comment by maraf** [comment]
Multi-threading is not working with blazor yet, see https://github.com/dotnet/aspnetcore/issues/54365. An important progress has been made on .NET runtime side, but the blazor framework is not ready yet.

I'm going to close this issue now. Probably the best place to follow further progress is the linked aspnetcore issue.
