### ISSUE TITLE
[API Proposal]: [QUIC] Make CompleteWritesAsync

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#103434]
### Background and motivation

System.Net.Quic is still in Preview, before we un-preview it, we'd like to change this method to an async one. 
https://learn.microsoft.com/en-us/dotnet/api/system.net.quic.quicstream.completewrites?view=net-8.0

### API Proposal

```csharp
namespace System.Net.Quic;

// Existing class.
public class QuicStream : Stream
{
-    void CompleteWrites();
+    ValueTask CompleteWritesAsync();
}
```

### API Usage

```csharp
await using var quicStream = await connection.OpenStreamAsync(...);
// Use the stream...
await quicStream.CompleteWritesAsync();
```

### Alternative Designs

Keeping it not-async and use existing `Task WritesClosed` property.

**Comment by MihaZupan** [comment]
Alternative 2: Delete the method? 😆

**Comment by ManickaP** [comment]
Closing as we decided to keep the API as-is.
