### ISSUE TITLE
Task Status

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#103428]
### Description

In the tasks, for some reason, the status shows that they have already been completed, but they are still running. Because of this, Task.WaitAll does not stop them, as it thinks they have already finished. This is a strange behavior.
![image](https://github.com/dotnet/runtime/assets/61237140/01657100-77f0-4a38-8721-47cf6fd2b502)

### Reproduction Steps

```
using System;
using System.Collections.Concurrent;

var response = Enumerable.Range(0, 1000);

var res = response.Chunk(100);


var ls = new List<Task>();
CancellationTokenSource factory = new();
ConcurrentBag<string> info = new ConcurrentBag<string>();
foreach (var element in res)
{

    var task = new Task(async () =>
    {
        await Task.Delay(1000000, factory.Token)
                        .ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);
        foreach (var item in element)
        {
            info.Add(item.ToString());

            Console.Write(item + "|");
        }
    }, TaskCreationOptions.LongRunning);
    ls.Add(task);
    task.Start();
}
await Task.Delay(3000);
factory.Cancel();
Task.WaitAll(ls.ToArray());
Console.WriteLine($"Counts Distinct Items:{info.Distinct().Count()} Count {info.Count}");
Console.ReadKey();
```

### Expected behavior

-

### Actual behavior

-

**Comment by stephentoub** [comment]
The problem is in the repro code. If you have code like this:
```C#
var task = new Task(async () =>
{
    A();
    await Task.Delay(1000);
    B();
});
task.Start();
```
that compiles down to using the Task constructor that takes an Action, with the async lambda becoming an `async void`. That Action will return the moment it awaits something that's not yet complete. So in my above example, that Task will complete the moment it hits that await.

**Comment by Mr0N** [comment]
> The problem is in the repro code. If you have code like this:
> 
> ```cs
> var task = new Task(async () =>
> {
>     A();
>     await Task.Delay(1000);
>     B();
> });
> task.Start();
> ```
> 
> that compiles down to using the Task constructor that takes an Action, with the async lambda becoming an `async void`. That Action will return the moment it awaits something that's not yet complete. So in my above example, that Task will complete the moment it hits that await.

I basically understood why it is executed this way. It would be good to add a constructor public Task(Func<Task> action){} to the Task class so that it would be possible to wait for the task to complete.

**Comment by Mr0N** [comment]
> t(ConfigureAwaitOptions.SuppressThrowin

![image](https://github.com/dotnet/runtime/assets/61237140/afa8ece7-8e5e-4c70-9ee0-e3c48e3b6849)
The method Task.Run does not have these parameters.

**Comment by stephentoub** [comment]
> The method Task.Run does not have these parameters.

If you need those options, you can use `Task.Factory.StartNew` and call .Unwrap on the result.

**Comment by Mr0N** [comment]
Well, plus everything is quite deceptive. For example, the Task.Run method accepts asynchronous lambdas. A user who uses the Task constructor also ideally thinks that it accepts asynchronous lambdas.

**Comment by Mr0N** [comment]
The Task class is essentially part of async/await.

**Comment by stephentoub** [comment]
> A user who uses the Task constructor also ideally thinks that it accepts asynchronous lambdas.

I understand the concern. This is the danger of `async void` lambdas.
