### ISSUE TITLE
LdapConnection.SessionOptions.AutoReconnect throws LdapException on Linux

### ISSUE THREAD

**Issue by slavabielkin** [dotnet/runtime#103431]
### Description

I am using `System.DirectoryServices.Protocols` to setup a connection to an LDAP server in .Net 8 console application. The code works as expected in Windows. In Linux, when getting or setting any value to `LdapConnection.SessionOptions.AutoReconnect`, `System.DirectoryServices.Protocols.LdapException: 'The LDAP server is unavailable.'` occurs.

Connection is functional, if `AutoReconnect` usage is commented out.

### Reproduction Steps

Run this code on Linux
```
var id = new LdapDirectoryIdentifier(ldapServer, port);
var connection = new LdapConnection(id);
connection.SessionOptions.ProtocolVersion = 3;
connection.AuthType = AuthType.Basic;
connection.SessionOptions.ReferralChasing = ReferralChasingOptions.None;
connection.SessionOptions.SecureSocketLayer = ssl;
connection.Credential = new NetworkCredential(username, securePassword);
connection.SessionOptions.AutoReconnect = anyBoolValue; //LdapException exception occurs here
```

### Expected behavior

- Setting or getting `LdapConnection.SessionOptions.AutoReconnect` value should not throw exception on Linux;
- LdapConnection functions according to the value of the property.

### Actual behavior

- Setting or getting `LdapConnection.SessionOptions.AutoReconnect` value throws `System.DirectoryServices.Protocols.LdapException: 'The LDAP server is unavailable.'` on Linux.

### Configuration

.Net 8
Linux Ubuntu,
x64
Bug is consistent on Linux, and does not occur on Windows.

**Comment by ericstj** [comment]
Comment here indicates it's not supported on linux: https://github.com/dotnet/runtime/blob/4a7ac0e1f2dd20ec4424b4fccb0aba0624407a5f/src/libraries/Common/src/Interop/Interop.Ldap.cs#L149

I wonder if we should do better about surfacing these in supported platform attributes @buyaa-n @joperezr

**Comment by buyaa-n** [comment]
> I wonder if we should do better about surfacing these in supported platform attributes @buyaa-n @joperezr 

This case is mentioned in https://github.com/dotnet/runtime/issues/84825, where we will handle platform attributes and throw PNSE when needed, closing as duplicate
