### ISSUE TITLE
SslStream Custom Algorithm Support

### ISSUE THREAD

**Issue by KFKMan** [dotnet/runtime#103466]
Can you add Custom Algorithm (Key Exchange, Cipher Algorithm, Hash Algorithm) support for SslStream

**Comment by rzikm** [comment]
Implementation of these parts of TLS protocol is delegated to platform cryptographic libraries (Schannel/BCrypt on Windows, OpenSSL on Linux, ....), It is not possible to add custom algorightms from .NET.

Is there a specific scenario you are trying to achieve?

**Comment by wfurt** [comment]
on the note above, it should just work if you for example provide updated OpenSSL library. In general I think you are out of luck for macOS and Windows.
