### ISSUE TITLE
[release/6.0-staging] Ensure the single-job-per-target-based official build produces all the correct assets

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#103485]
As part of the 1ES pipeline backporting work, we accidentally dropped the steps to build the Linux deb/rpm packages and the cross-OS DAC packages. We need to make sure we bring these back before the next code-complete or back out the changes that built on the one that dropped these components (#102862).

**Comment by amanasifkhalid** [comment]
Per @hoyosjs's advice, I tested merging from `release/6.0-staging` into `release/6.0` after #103935 went in, and ran an official build: The merge was clean, and the [official build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2484961&view=results) looks good. Are we ready to close this?

**Comment by jkoritzinsky** [comment]
Yep we're good to close this.
