### ISSUE TITLE
IConfiguration does not work as one would expect in .NET 8

### ISSUE THREAD

**Issue by hjrb** [dotnet/runtime#103418]
### Description

Assume a simple appsettings.json
```javascript
"Deputies": {
      "Users": [ "a", "b", "c"]
   }
``` 
Now let's try to load that using the extension method
```c#
        /// <summary>
        /// Extracts the value with the specified key and converts it to type T.
        /// </summary>
        /// <typeparam name="T">The type to convert the value to.</typeparam>
        /// <param name="configuration">The configuration.</param>
        /// <param name="key">The key of the configuration section's value to convert.</param>
        /// <returns>The converted value.</returns>
        [RequiresUnreferencedCode(TrimmingWarningMessage)]
        public static T? GetValue<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T>(this IConfiguration configuration, string key)
``` 
from Microsoft.Extensions.Configuration

This should work:
```c#
			var x=builder.Configuration.GetValue<Dictionary<string, string[]>>("Deputies");

``` 
The value of the JSON object "Deputies" is a dictionary with keys of type string and values of type string[]
But it does not! The value of x is null!

Using the System.Text.Json JsonSerializer it DOES works!
```c#
var json = 
"""
{"Users": [ "a", "b", "c"]}
""";
var x=JsonSerializer.Deserialize<Dictionary<string, string[]>>(json);  
``` 

That is inconsistent behaviour.

### Reproduction Steps

see above

### Expected behavior

The configuration provider should understand that configuration values can be JSON and correctly deserialize it to the desired type

### Actual behavior

it does not work - the return value is null. Instead of throwing an exception that explains what is going on the implementation simply consumes the error and return null - THAT IS AN ANTI PATTERN!
It the configuration value does not exists return null is acceptable.
But if the configuration DOES exist, but does not match the expected type this is an ERROR. 
If you want avoid throwing exceptions you should implment a TryGetValue<T>(string key) method.

### Known Workarounds

Fiddle around with GetSection()....

### Configuration

.NET 8 latest
Windows
x64
It is not specific to the configuration

### Other information

PLEASE: don't try to be so smart. It is very simple.
Add and extension method string  GetRequiredValueAsJson((this IConfiguration configuration, string key) with the following behavior

1. if the key is missing throw an exception - do not return null!
2. if the key exists simply read the value and it AS IS. Dont try to be smart and figure out if it is JSON - the caller will do!

Add and extension method string?  GetOptionalValueAsJson((this IConfiguration configuration, string key) with the following behavior

1. if the key is return null
2. if the key exists simply read the value and it AS IS. Don't try to be smart and figure out if it is JSON - the caller will do!

**Comment by tarekgh** [comment]
@chrisoverzero Thanks for helping with the behavior explanation.

**Comment by hjrb** [comment]
1. Then GetValue should be deprecated. The name is confusing. The correct name is GetScalarValue()
2. Also GetSection(string key) has a wrong parameter name. Instead of key is should be path and there should be a comment for that weired syntax.
@tarekgh : please reopen the issue! The explanation is not a resolution. Please propose this as an answer and let me and the community decide if we will accpet it. You are not the owner of this thing!

**Comment by hjrb** [comment]
What is breaking about setting a method to deprecated and/or adding a better documentation. I will not sit here waste hours of my precious time to figure out how why this does not work, make suggestions how to fix your stuff and all you do is ignore it and I wrote is waste and you simply close it!! I feel offended and outright ignored. If you are not willing to collaborate in a decent way I will escalate that topic to my MS customer satisfaction representative. I represent one of the biggest MS Enterprise customers and my bloodpressure is rising quickly!

**Comment by hjrb** [comment]
What is breaking about setting a method to deprecating and adding better documentation. I will not sit here waste hours of my precious time to figure out how why this does not work and all you do is ignore all I write and simple close it!! I feel offended and outright ignored. If you are not willing to collaborate in a decent way I will escalate that to my MS customer satisfaction representative. I represent one of the biggest MS Enterprise customers. My blood pressure is quickly rising!

**Comment by tarekgh** [comment]
> What is breaking about setting a method to deprecated and/or adding a better documentation.

We are not deprecating any APIs that users are actively using; we continue to support them. I initially thought you were proposing renaming the API/parameter and apologize for the misunderstanding. This is why I mentioned it would be a breaking change, as we cannot rename APIs or parameters. I have opened a documentation issue [here](https://github.com/dotnet/dotnet-api-docs/issues/10020) to track improvements and clarify the API behavior. Feel free to comment there if you have any more specific docs suggestions. If there are any other concerns, please let me know, and I'll be happy to assist.

**Comment by hjrb** [comment]
If you search for [Obsolete you will find > 5000 results in the .NET repository. MS does deprecate actively used APIs all the time. If the name of a method is confusing it will lead to avoidable errors. The thing that puzzles me most: GetValue<T> has a type parameter being a generic method. But you claim it only reads scalar values.
>> The word "value" doesn't mean what you think it does, here. In Microsoft.Extensions.Configuration (which supports configuration from many varied sources – not only JSON), the Value property of the configuration section named by "Deputies" is null. This is because "value" means simple scalar values.

1. If this is true - then why have an arbitrary type parameter that suggest I can get any type of value?
2. GetValue<string> is ambiguous. The value is this example is indeed a string, which happens to have a JSON format. Why not simply return that string in that case
For me this is plain broken. Leaving it like this will cause avoidable errors in many programs today and in the future.

**Comment by julealgon** [comment]
> The thing that puzzles me most: GetValue has a type parameter being a generic method. But you claim it only reads scalar values.

`GetValue` supports the TypeConverter mechanism so it can read many types such as `Uri`, `TimeSpan`, `DateTime`, etc.

**Comment by tarekgh** [comment]
Here are some more details how things work:

Configurations work in abstract way over different configuration providers including JSON one. When calling `GetValue`, it reads the configuration value as a string and then converts this string to the actual generic type. If the json configuration file has the form 

```json
"Deputies": {
      "Users": [ "a", "b", "c"]
   }
```

and you are calling `GetValue` to read `Deputies`, it will find the value is defined as `{ ... }` which cannot read it as a simple string and at that time it will set the value of `Deputies` as null. If the json configuration has form 

```json
"Deputies": SomeValue
```

`GetValue` will read SomeValue as a string and then try to convert it to the generic type used with `GetValue`. The conversion is usually done using the type-converter. If the type-converter does not support the specific generic type, the API will return `null` too. Configurations support custom type converter too if want to provide one to allow conversion for types not recognized by the default runtime type-converter. 

To bind to a dictionary to support your scenario, you may consider using code like the following:

define the json configuration as:

```json
  "Deputies": {
    "Key1": [ 1, 2, 3 ],
    "Key2": [ 4, 5, 6 ],
    "Key3": [ 7, 8, 9 ]
  }
```

then write code like:

```C#
    var configDictionary = config.GetSection("Deputies").Get<Dictionary<string, int[]>>();
```

**Comment by hjrb** [comment]
>> Configurations work in abstract way over different configuration providers including JSON one. When calling GetValue, it reads the configuration value as a string
Stop right there. Give us that string (maybe in a new function). We are old enough to take care about using that string by ourselves - no kidding. Then we don't need to GUESS what the guy implementing the feature thought would be a great idea - but failed to document properly and named in in a confusing way. Keep It Simple Stupid (KISS).

**Comment by richlander** [comment]
This conversation is no longer healthy. Please focus your constructive energies on the docs issue.

https://github.com/dotnet/dotnet-api-docs/issues/10020
