### ISSUE TITLE
[Mono] Build fails with libcdacreader.so missing from manifest

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/runtime#103486]
### Description

When attempting to build Mono for linux-x64 using the build command `build.sh -ci -arch x64 -os linux -cross -s mono+clr.iltools+clr.hosts+libs+host+packs -c Release`, the build fails with this error:
```
/__w/1/s/.packages/microsoft.dotnet.sharedframework.sdk/9.0.0-beta.24311.10/targets/sharedfx.targets(296,5): error : The following files are missing entries in the templated manifest: [/__w/1/s/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/__w/1/s/.packages/microsoft.dotnet.sharedframework.sdk/9.0.0-beta.24311.10/targets/sharedfx.targets(296,5): error : libcdacreader.so. Add these file names with extensions to the 'PlatformManifestFileEntry' item group for the runtime pack and corresponding ref pack to include them in the platform manifest. [/__w/1/s/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
```

Example pipeline with the failure: https://dev.azure.com/dnceng/internal/_build/results?buildId=2472669&view=results
This seems like a similar error as was hit here: https://github.com/dotnet/runtime/issues/67829.

### Reproduction Steps

Clone the runtime repo and build with `build.sh -ci -arch x64 -os linux -cross -s mono+clr.iltools+clr.hosts+libs+host+packs -c Release` using the build.sh.

### Expected behavior

Build succeeds

### Actual behavior

Build fails with:
```
/__w/1/s/.packages/microsoft.dotnet.sharedframework.sdk/9.0.0-beta.24311.10/targets/sharedfx.targets(296,5): error : The following files are missing entries in the templated manifest: [/__w/1/s/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/__w/1/s/.packages/microsoft.dotnet.sharedframework.sdk/9.0.0-beta.24311.10/targets/sharedfx.targets(296,5): error : libcdacreader.so. Add these file names with extensions to the 'PlatformManifestFileEntry' item group for the runtime pack and corresponding ref pack to include them in the platform manifest. [/__w/1/s/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
```

### Regression?

This broke sometime Wednesday the 12th, with the diff between our last working and first broken build being: https://github.com/dotnet/runtime/compare/bb2a99b1e58311543ae26512e39ae626ba864faa...eb8f54d92b015c8b416f6e506fd4c3335740302c

### Known Workarounds

None

### Configuration

Build is completed with the latest runtime targeting linux-x64

**Comment by am11** [comment]
#103488 should fix it.

**Comment by lambdageek** [comment]
I don't think we want to add cdacreader to the manifest - we don't want to ship it yet since it's not signed like the other diagnostic libraries (and we don't check its signature even if it were signed) https://github.com/dotnet/runtime/pull/100946#discussion_r1566320500

**Comment by am11** [comment]
Entries are now there for exclusion, not inclusion.
