### ISSUE TITLE
Incorrect general long time pattern for some cultures on Android

### ISSUE THREAD

**Issue by PopSlime** [dotnet/runtime#103592]
### Description

On Android, some cultures have an incorrect general long time pattern, causing `DateTime.ToString(IFormatProvider)` to produce badly formatted strings.

### Reproduction Steps

Consider the following code:

```cs
new DateTime(2000, 1, 1, 20, 0, 0).ToString(new CultureInfo("zh-TW"));
```

### Expected behavior

A correctly formatted string (like `2000/1/1 下午8:00:00`) is returned.

### Actual behavior

A badly formatted string `2000/1/1 8:00:00` is returned, in which a 12-hour clock is used without an AM/PM designator.

### Configuration

- .NET version: 8.0
- Target operating system: Android
- Architecture: x64, arm64
- Android version: 13 (tested both on an emulator and a physical device)

**Comment by PopSlime** [comment]
I did some further investigations, this issue seems to be device-dependent. Just in case, this issue was reproduced with the `system-images;android-33;google_apis;x86_64` system image.

**Comment by tarekgh** [comment]
CC @vitek-karas @mkhamoyan @ilonatommy

**Comment by vitek-karas** [comment]
CC @matouskozak

**Comment by PopSlime** [comment]
This issue seems to relate to this `ConvertIcuTimeFormatString` method.

https://github.com/dotnet/runtime/blob/b93061adc14eaaf5e83e366f9fba507ad917308c/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L354

The current implementation does not cover the full Unicode [Date Format Patterns](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns). In the case of `zh-TW` (which expands to `zh-Hant-TW` and inherits `zh-Hant`,) the pattern symbol `B` is used [1], which is not covered in the aforementioned method.

Please consider support or partially support as many pattern symbols as possible just in case.

[1] https://github.com/unicode-org/cldr/blob/3147eda09f19de58463cc80d64248071531500a0/common/main/zh_Hant.xml#L4963

**Comment by PopSlime** [comment]
Related PR: https://github.com/unicode-org/cldr/pull/1297

**Comment by PopSlime** [comment]
Affected CLDR version: 40 and above (https://cldr.unicode.org/index/downloads/cldr-40#h.mc372kkefa0z)

Affected Android version: 13 and above (https://developer.android.com/guide/topics/resources/internationalization#versioning-nougat)

**Comment by tarekgh** [comment]
@PopSlime thanks for the update. We should support the `B` conversion. Are you interested in submitting a PR for that? 

CC @mkhamoyan

**Comment by PopSlime** [comment]
Hi, @tarekgh. I've submitted a PR for this issue but I'm not sure how to test it. Would you mind checking it out?
