### ISSUE TITLE
StaticIndexRangePartition uses volatiles suggesting multiple threading, but uses volatileVar++

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#103596]
https://github.com/dotnet/runtime/blob/cf854b305f2ce88d02cc61f401f79f79cc98167f/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/PartitionerStatic.cs#L1450

Is this correct? It's a volatile and increment operation isn't thread safe like this.

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/blob/cf854b305f2ce88d02cc61f401f79f79cc98167f/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/PartitionerStatic.cs#L1398-L1400

Presumably, it's not expected to be incrementated from different threads. My guess that "volatile" is used here to guarantee the expected order of writes/reads to these fields for external readers.

**Comment by omajid** [comment]
Thanks!
