### ISSUE TITLE
[jitstress] JIT\Regression\JitBlue\Runtime_90423 fails with "Assertion failed '(op2 == idx) || (op2->gtEffectiveVal() == idx)' during 'Find oper order'"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#103577]
jitstress is red due to this assertion failure: https://dev.azure.com/dnceng-public/public/_build?definitionId=109&_a=summary
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-103559-merge-65fba342677a469aac/Regression_2/1/console.ff49ede3.log?helixlogtype=result

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
Bisected to #99183, so probably something that was just exposed by that change...

**Comment by amanasifkhalid** [comment]
@EgorBo I'm seeing this assert hit again in #103904, though I don't think it was exposed by block compaction since it's hitting in MinOpts.

**Comment by JulieLeeMSFT** [comment]
cc @EgorBo, it is failing in [runtime-coreclr gcstress-extra](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720410&view=ms.vss-test-web.build-test-results-tab&runId=18065104&resultId=170568&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab)
- coreclr linux x64 Checked gcstress0xc_jitminopts_heapverify1 @ Ubuntu.2204.Amd64.Open
-- Regression_2.0.1 Work Item

**Comment by EgorBo** [comment]
Will take a look this week

**Comment by jakobbotsch** [comment]
This is still blocking jitstress... any luck @EgorBo?
