### ISSUE TITLE
[API Proposal]: Add Comparison overload to PriorityQueue constructor

### ISSUE THREAD

**Issue by Hixon10** [dotnet/runtime#103518]
### Background and motivation

Such overload will allow to use lambda for creating a PriorityQueue. At present, it is not possible, and people must use something like that:

```csharp
var queue = new PriorityQueue<int, int>(Comparer<int>.Create((x, y) => y - x));
```

But I would like to use it like this:

```csharp
var queue = new PriorityQueue<int, int>((x, y) => y.CompareTo(x));
```

### API Proposal

```csharp
namespace System.Collections.Generic;

public PriorityQueue(Comparison<TPriority> comparison)
{
           // ...
}
```

### API Usage

```csharp
var queue = new PriorityQueue<int, int>((x, y) => y.CompareTo(x));
```

### Alternative Designs

It could be possible to add `OrderByDescending` to some existing `PriorityQueue` APIs, so people will not want to use both `Comparison`, and `Comparer`.

### Risks

I don't see any risks. It is just additional code, which will be needed to maintain. So we tradeoff API UX over maintenance. I don't know, what is the most important thing here, but other classes in C# have both `Comparison`, and `Comparer`.

**Comment by eiriktsarpalis** [comment]
It's not the type of overload that we expose for collection types whether it's `IComparer<T>` or `IEqualityComparer<T>` (it would simply be too many overloads). The recommended approach is to wrap the delegates using either `Comparer<T>.Create` or `EqualityComparer<T>.Create`, as you showed in the original example.
