### ISSUE TITLE
[API Proposal]: Console.Write* convenience overloads for span

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#103500]
### Background and motivation

Console.Write and Console.WriteLine have a bunch of overloads for writing out various data types, but none for `ReadOnlySpan<char>`. We should add some purely for convenience. You can achieve the same by `.ToString()`'ing them or by using `Console.Out.Write*` instead, but it's just a little bit of unnecessary friction.

(I thought we already had an issue for this, but can't find it now.)

### API Proposal

```diff
namespace System;

public static class Console
{
+   public static void Write(ReadOnlySpan<char> value);
+   public static void WriteLine(ReadOnlySpan<char> value);
}
```

### API Usage

```C#
ReadOnlySpan<char> value = ...;
Console.WriteLine(value);
```

### Alternative Designs

n/a

### Risks

n/a

**Comment by neon-sunset** [comment]
Does it make sense to also create overloads which accept `DefaultInterpolatedStringHandler` given that `ReadOnlySpan<char> Text` property on it is `internal`?

**Comment by stephentoub** [comment]
Why? There's already a string overload, so interpolation already works. You're concerned about performance with Console.WriteLine?

**Comment by neon-sunset** [comment]
Haha no, not of WriteLine itself, but given there's an option to make it allocation-free, I thought it could be useful to raise it.

**Comment by stephentoub** [comment]
Please feel free to open a separate issue.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System;

public static class Console
{
    public static void Write(ReadOnlySpan<char> value);
    public static void WriteLine(ReadOnlySpan<char> value);
}
```
