### ISSUE TITLE
AdvSimd: Invalid "The constant does not fit within the value bounds of '0' to '15'" warning

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#103556]
Compile the following code:
```cs
Vector128<ulong> v = Vector128.Create(ulong.MaxValue);
_ = AdvSimd.ShiftLeftLogical(v, 32);
```
Expected:
```
no warning
```
Actual:
```
Warning CA1857: The constant does not fit within the value bounds of '0' to '15'
```

Seems like other overloads are affected as well.

cc @tannergooding 

SHL arm reference: https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions/SHL--Shift-Left--immediate--

**Comment by tannergooding** [comment]
Hmmm, the `ConstantExpected` for `ShiftLeftLogical*` seem wrong in general. They are effectively inverted and twice as large of a constant as they should be.
