### ISSUE TITLE
Running "sudo -s" via System.Diagnostics.Process on Linux results in its standard input "hijacking" the program

### ISSUE THREAD

**Issue by kanpov** [dotnet/runtime#103571]
### Description

When trying to execute `sudo -s` on Linux via the `Process` class while piping out stdin, stdout and stderr and without shell execute, the input of that process (`[sudo] password for root: `, which asks for the root password) somehow ends up **inside the C# program**!

This means that trying to `await process.StandardInput.WriteLineAsync("some password value");` doesn't actually send it to `sudo`'s stdin, and instead does nothing. The user of the program, meanwhile, can input the password into the program and that password will somehow be sent into `sudo`.

Plus, `sudo`'s stdout also somehow ends up in the program with the "Sorry, try again." messages becoming visible with neither an `await process.StandardOutput.ReadLineAsync();` nor a `process.BeginOutputReadLine();`.

This is extremely weird behavior.

### Reproduction Steps

1. Create a new C# CLI project.
2. Insert the following code into `Program.cs`:
```cs
using System.Diagnostics;

var process = new Process
{
    StartInfo = new ProcessStartInfo("/bin/sudo", "-s")
    {
        RedirectStandardInput = true,
        RedirectStandardOutput = true,
        RedirectStandardError = true,
        UseShellExecute = false,
        CreateNoWindow = true
    }
};

process.Start();

await process.StandardInput.WriteLineAsync("root_password");

await process.WaitForExitAsync();
```
3. `dotnet run` the project
4. See the password asker with `root_password` not being piped into `sudo`'s stdin, while the stdout is redirected straight into the C# program

### Expected behavior

The expected behavior is to **not** have any such unexpected redirection directly into the C# program happen, and instead be able to interact with its stdout and stdin "normally".

### Actual behavior

Somehow:
process's stdout => C# program's stdout
C# program's stdin => process's stdin
trying to insert anything into the `StandardInput` `StreamWriter` affects nothing

### Known Workarounds

It **might** be possible to use raw Linux glibc calls to start a process instead, but I'd expect a high level and somewhat convenient API such as `Process` to function correctly.

### Configuration

`dotnet --info` output:

```
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.011fccd5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     opensuse-tumbleweed
 OS Version:  20240606
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.301/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Other information

The motivation behind even trying to run `sudo -s` via C# code is to manually elevate a process to root without having to `sudo dotnet run`, which partly breaks MSBuild.

Even taking this into account, the fact this sort of thing can happen is extremely strange and severely detracts from the viability of the `Process` API for Linux applications or libraries (such as mine I encountered this in, FirecrackerSharp).

**Important note:** on some Linux devices, I've seen this happen with either:
- only `sudo -s`
- only `su`
- both `sudo -s` and `su`

Why this is the case I have no clue.

**Comment by kanpov** [comment]
My Linux desktop is running openSUSE Tumbleweed, I'll try to reproduce this on a Debian VM soon.

**Comment by poizan42** [comment]
sudo reads the password from the terminal and not from stdin by default - you would need to create a pty to intercept that.

Or you could just use the -S (capital S) option

> -S' The -S (stdin) option causes sudo to read the password from the standard input instead of the terminal device. The password must be followed by a newline character.
