### ISSUE TITLE
Produce Single File: app crashing

### ISSUE THREAD

**Issue by davidbuchweitz** [dotnet/runtime#103552]
I have a Blazor Server app that runs on kestrel in a Windows service.

Initially everything works perfectly but then after some time I start getting exceptions about certain .NET framework files not being able to load and the app crashes (Blazor red error bar in browser).

I see that by default when using the "Produce Single File" option when publishing, the files are extracted to **c:\\Windows\\Temp\\.net\\\<hash\>**.

I was under the impression the Temp folder was only cleaned on Windows startup but the internets says files in Temp can be removed in many different cases, such as using Disk Cleanup, running certain updates, on a timer when disk space is low etc.

Either which way, this seems like a terrible oversight for the Temp dir to be used as the extraction point by default.

I've since learned you can set the env var **DOTNET_BUNDLE_EXTRACT_BASE_DIR** but this is not practical as it would affect all apps published this way. Setting it for this file alone is also not an option as it would require a script to set the env var first.

As a workaround I'm setting **HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Wamp.NET\\Environment** to **DOTNET_BUNDLE_EXTRACT_BASE_DIR=C:\\Wamp.NET\\.wdn\\tmp** but this is messy.

**Comment by agocke** [comment]
This `TEMP` behavior is unfortunate, but by-design. However, the default configuration of .NET single-file is to not extract any files to disk. Have you considered turning off bundling?

**Comment by davidbuchweitz** [comment]
I haven't changed any defaults - where does this get set? It would be amazing if it could run from memory.

**Comment by agocke** [comment]
It should simply be default in .NET 6+. The only bundling done is manual, e.g. by setting `IncludeNativeLibrariesForSelfExtract`. See https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#native-libraries for that setting.

**Comment by davidbuchweitz** [comment]
Thanks Andy, but this takes the benefits away from a single file deployment where the app and framework are bundled together in a single file. Made deployment and updates really simple. Back to the drawing board...

**Comment by agocke** [comment]
Sorry, I don't understand. The whole framework is linked into that exe -- the only native assets that will appear outside the bundle are things outside the core framework. Do you have native assets aside from the ones in the core framework? Or are you using a UI framework that includes native assets?
