### ISSUE TITLE
coreclr.lib

### ISSUE THREAD

**Issue by SusLes** [dotnet/runtime#10359]
Copying from Dotnet: https://github.com/Microsoft/dotnet/issues/753

daoqiang commented 9 hours ago • edited  
I want to add coreclr to my project. I must introduce it in a static way. What should I do?
There can be no dynamic reference，thank you

**Comment by vitek-karas** [comment]
I know it's been a while, but maybe in .NET 5 this is now solved. If you're looking for an entire app, you can use the new single-file - which links together all of the runtime and bundles all the managed code. The build system now supports building coreclr as libs as well - not in a publicly usable state (published as packaged or so), but maybe it's enough if you want a special one-off project.
