### ISSUE TITLE
The mask of `shiftAmount` in `IShiftOperators<byte, int, byte>` should be 7 instead of 31

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#103506]
### Description

https://github.com/dotnet/runtime/blob/0f0981f7234bcb8dc796f90fd76bd3d7a2bf2393/src/libraries/System.Private.CoreLib/src/System/Byte.cs#L1117-L1124

### Reproduction Steps

```csharp
using System;
using System.Numerics;

BinaryIntegerWrapper<byte> a = new(2);
Console.WriteLine((a << 11).Value);

public struct BinaryIntegerWrapper<T> : IShiftOperators<BinaryIntegerWrapper<T>, int, BinaryIntegerWrapper<T>>
            where T : IBinaryInteger<T>
{
    public T Value;

    public BinaryIntegerWrapper(T value) => Value = value;

    public static implicit operator BinaryIntegerWrapper<T>(T value) => new BinaryIntegerWrapper<T>(value);

    public static BinaryIntegerWrapper<T> operator <<(BinaryIntegerWrapper<T> value, int shiftAmount) => value.Value << shiftAmount;
    public static BinaryIntegerWrapper<T> operator >>(BinaryIntegerWrapper<T> value, int shiftAmount) => value.Value >> shiftAmount;
    public static BinaryIntegerWrapper<T> operator >>>(BinaryIntegerWrapper<T> value, int shiftAmount) => value.Value >>> shiftAmount;
}
```

### Expected behavior

16

### Actual behavior

0

### Other information

Per [this comment](https://github.com/dotnet/runtime/pull/103900#issuecomment-2186722435) from @tannergooding:

> This is also notably an issue with `sbyte`, `short`, and `ushort`. It is also, unfortunately, a breaking change and will need a bar check.
> 
> The intent had indeed been to correctly mask, which is being done in other operations but was missed for these ones.

**Comment by jeffhandley** [comment]
I've added this to the 10.0.0 milestone as it would be beneficial to apply the breaking change fix early in an LTS release.
