### ISSUE TITLE
Excess MOVAPS on some non-VEX encoded SSE HW intrinsics having the same 1st and 2nd operand

### ISSUE THREAD

**Issue by voinokin** [dotnet/runtime#10356]
Codegen for some HW intrinsics on pre-AVX CPU provides result which is obviously too verbose.
Here is sample code:

                Vector128<ulong> vU64 = Sse2.ConvertScalarToVector128UInt64(1UL);
                vU64 = Sse2.UnpackHigh(vU64, vU64);
                Console.WriteLine(vU64);

Here is asm code generated on my i5-750 (Nehalem uarch):

> 000007FE650F5D20  mov         rsi,rcx  
> 000007FE650F5D23  mov         ecx,1  
> 000007FE650F5D28  movq        xmm6,rcx  
>                 vU64 = Sse2.UnpackHigh(vU64, vU64);
> 000007FE650F5D2D  movaps      xmm0,xmm6        ; <==========
> 000007FE650F5D30  punpckhqdq  xmm0,xmm6     ; <==========
> 000007FE650F5D34  movaps      xmm6,xmm0  
>                 Console.WriteLine(vU64);
> 000007FE650F5D37  mov         rcx,7FE650E6750h  
> 000007FE650F5D41  call        000007FEC4BB1940  
> 000007FE650F5D46  mov         rcx,rax  
> 000007FE650F5D49  movups      xmmword ptr [rcx+8],xmm6  
> 000007FE650F5D4D  call        000007FE650F2558

`vU64` is not used anywhere after the last line, and to my opinion the instructions marked can be replaced with just one `punpckhqdq  xmm6,xmm6`. The same excess `MOVAPS`s also happen to other HW intrinsics, so `UnpackHigh()` is just an example.

VEX-encoded version is OK, no extra `VMOVAPS` generated - tested with i7-4790K (Haswell uarch w/ AVX & AVX2).

UPD: I'm using .NET Core 2.1 RC1

category:cq
theme:register-allocator
skill-level:intermediate
cost:small

**Comment by CarolEidt** [comment]
This should be analyzed to determine if it's still happening.

**Comment by kunalspathak** [comment]
Verified on e830f1006de and it generates expected code.

```asm
G_M62409_IG01:              ;; offset=0000H
       4883EC38             sub      rsp, 56
       C5F877               vzeroupper
       C5F829742420         vmovaps  qword ptr [rsp+20H], xmm6
                                                ;; bbWeight=1    PerfScore 4.25
G_M62409_IG02:              ;; offset=000DH
       B901000000           mov      ecx, 1
       C4E1F96EF1           vmovd    xmm6, rcx
       48B9B8A89B61F87F0000 mov      rcx, 0x7FF8619BA8B8
       E88AE6A65F           call     CORINFO_HELP_NEWSFAST
       C5C96DC6             vpunpckhqdq xmm0, xmm6, xmm6
       C5F9114008           vmovupd  xmmword ptr [rax+8], xmm0
       488BC8               mov      rcx, rax
       E809FDFFFF           call     System.Console:WriteLine(System.Object)
       90                   nop
                                                ;; bbWeight=1    PerfScore 9.00
G_M62409_IG03:              ;; offset=0038H
       C5F828742420         vmovaps  xmm6, qword ptr [rsp+20H]
       4883C438             add      rsp, 56
       C3                   ret
                                                ;; bbWeight=1    PerfScore 5.25
```
