### ISSUE TITLE
Should we Dispose DefaultAssemblyResolver in SpaceAnalyzer

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#103581]
https://github.com/dotnet/runtime/blob/7e977dcbe5efaeec2c75ed0c3e200c85b2e55522/src/tools/illink/src/analyzer/LinkerAnalyzerCore/SpaceAnalyzer.cs#L122

It's an IDisposable, and maintains a cache of all assemblies, though we also maintain a cache of AssemblyDefinition in SpaceAnalyzer.

**Comment by agocke** [comment]
This is a non-shipping tool. If it's presenting a problem you can submit a PR, but I'm not going to change anything unless there's an identified issue.
