### ISSUE TITLE
static Resize method in the System. Array.cs creates a new array instance even if the new size is 0.

### ISSUE THREAD

**Issue by cheblin** [dotnet/runtime#103535]
In the original implementation of the the [Resize method](https://github.com/dotnet/runtime/blob/eb455ec34c6709e487c19e52c29ec712a6fa4d7f/src/libraries/System.Private.CoreLib/src/System/Array.cs#L43), when the new size is zero, a new array is created
```cs
 public static void Resize<T>([NotNull] ref T[]? array, int newSize)
        {
            if (newSize < 0)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.newSize, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);

            T[]? larray = array; // local copy
            if (larray == null)
            {
                array = new T[newSize];
                return;
            }

            if (larray.Length != newSize)
            {
                // Due to array variance, it's possible that the incoming array is
                // actually of type U[], where U:T; or that an int[] <-> uint[] or
                // similar cast has occurred. In any case, since it's always legal
                // to reinterpret U as T in this scenario (but not necessarily the
                // other way around), we can use SpanHelpers.Memmove here.

                T[] newArray = new T[newSize];
                Buffer.Memmove(
                    ref MemoryMarshal.GetArrayDataReference(newArray),
                    ref MemoryMarshal.GetArrayDataReference(larray),
                    (uint)Math.Min(newSize, larray.Length));
                array = newArray;
            }

            Debug.Assert(array != null);
        }
```
Suggested Improvement
I propose an additional check to handle the case where newSize is 0 more efficiently by using Array.Empty<T>(), which avoids unnecessary allocations. Here is my suggested improvement :

```cs
        public static void Resize<T>([NotNull] ref T[]? array, int newSize)
        {
            if (newSize < 0)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.newSize, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);

            T[]? larray = array; // local copy
            if (larray == null)
            {
                array = new T[newSize];
                return;
            }

            if (newSize == 0) array = Array.Empty<T>(); // <<<<<<<<<<<<<<<<<<<
            else if (larray.Length != newSize)
            {
                // Due to array variance, it's possible that the incoming array is
                // actually of type U[], where U:T; or that an int[] <-> uint[] or
                // similar cast has occurred. In any case, since it's always legal
                // to reinterpret U as T in this scenario (but not necessarily the
                // other way around), we can use SpanHelpers.Memmove here.

                T[] newArray = new T[newSize];
                Buffer.Memmove(
                    ref MemoryMarshal.GetArrayDataReference(newArray),
                    ref MemoryMarshal.GetArrayDataReference(larray),
                    (uint)Math.Min(newSize, larray.Length));
                array = newArray;
            }

            Debug.Assert(array != null);
        }
```
By introducing the check for newSize == 0, this improvement makes the Array.Resize method more efficient in handling zero-sized arrays. This avoids unnecessary heap allocations by reusing the singleton empty array provided by Array.Empty<T>(). This change is particularly beneficial in scenarios where resizing to zero is frequent, leading to potential performance improvements and reduced memory usage.

**Comment by stephentoub** [comment]
I'm not against this, but the most common use of resize I see is when growing an array, and 0 will never show up in that case. Can you share more details about the scenarios you have where this would be impactful?

**Comment by cheblin** [comment]
> scenarios

The scenarios are exactly the same as those for which Array.Empty<T>() exists.

**Comment by stephentoub** [comment]
> For example, a Fit method that sets Capacity to be the same as Count in a List when the List is empty.

For reference, `List<T>` doesn't use Resize:
https://github.com/dotnet/runtime/blob/193b82684971378be9fa0754a97bfabf82e5fd28/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L121

**Comment by jkotas** [comment]
Referencing `Array.Empty<T>()` in `Array.Resize<T>` will take extra memory for every instantiation of `Array.Resize` even when the `Array.Empty<T>` path is not ever taken. The question is whether the saving from `Array.Empty<T>()` special case offsets this extra cost on average.
