### ISSUE TITLE
System.Numerics.Tensors.Tests.TensorSpanTests test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#103525]
```
  Discovering: System.Numerics.Tensors.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Tensors.Tests (found 2422 of 4294 test cases)
  Starting:    System.Numerics.Tensors.Tests (parallel test collections = on [6 threads], stop on fail = off)
    System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>(tensorPrimitivesOperation: TensorPrimitivesSpanInSpanOut`1 { Method = Void SoftMax(System.ReadOnlySpan`1[System.Single], System.Span`1[System.Single]), Target = null }, tensorOperation: TensorSpanInSpanOut`1 { Method = System.Numerics.Tensors.TensorSpan`1[System.Single] SoftMaxInPlace[Single](System.Numerics.Tensors.TensorSpan`1[System.Single]), Target = null }) [FAIL]
      Assert.All() Failure: 1 out of 11 items in the collection did not pass.
      [10]: Item:  [4, 4, 4, 4, 4]
            Error: Assert.Equal() Failure: Values differ
                   Expected: 1.15352677E-23
                   Actual:   1.15352685E-23
      Stack Trace:
        /_/src/libraries/System.Numerics.Tensors/tests/TensorSpanTests.cs(143,0): at System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut[T](TensorPrimitivesSpanInSpanOut`1 tensorPrimitivesOperation, TensorSpanInSpanOut`1 tensorOperation)
           at InvokeStub_TensorSpanTests.TensorExtensionsSpanInSpanOut(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Numerics.Tensors.Tests
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=709057
Build error leg or test failing: System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>
Pull request: https://github.com/dotnet/runtime/pull/103519

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Numerics.Tensors", "items in the collection did not pass", "Failure: Values differ" ],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=709057
**Error message validated:** `[System.Numerics.Tensors items in the collection did not pass Failure: Values differ`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/15/2024 7:11:03 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[773673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773673)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773673&view=ms.vss-test-web.build-test-results-tab&runId=19781592&resultId=192901)|dotnet/runtime#106294|
|[773418](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773418)|dotnet/runtime|[System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.Dot_AllLengths](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773418&view=ms.vss-test-web.build-test-results-tab&runId=19777594&resultId=114807)|dotnet/runtime#106166|
|[773213](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773213)|dotnet/runtime|[System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.SumOfMagnitudes_AllLengths](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773213&view=ms.vss-test-web.build-test-results-tab&runId=19767678&resultId=114723)|dotnet/runtime#106166|
|[773114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773114)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773114&view=ms.vss-test-web.build-test-results-tab&runId=19766784&resultId=200340)|dotnet/runtime#106285|
|[773036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773036)|dotnet/runtime|[System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.SumOfMagnitudes_AllLengths](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773036&view=ms.vss-test-web.build-test-results-tab&runId=19763594&resultId=114723)|dotnet/runtime#106166|
|[772593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772593)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772593&view=ms.vss-test-web.build-test-results-tab&runId=19750104&resultId=170061)|dotnet/runtime#106257|
|[772519](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772519)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInTOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772519&view=ms.vss-test-web.build-test-results-tab&runId=19746244&resultId=181972)|dotnet/runtime#106252|
|[771366](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771366)|dotnet/runtime|[System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.SoftMax_AllLengths](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771366&view=ms.vss-test-web.build-test-results-tab&runId=19715296&resultId=210257)|dotnet/runtime#106166|
|[771264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771264)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771264&view=ms.vss-test-web.build-test-results-tab&runId=19704594&resultId=172341)|dotnet/runtime#106156|
|[770680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770680)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770680&view=ms.vss-test-web.build-test-results-tab&runId=19686816&resultId=187299)|dotnet/runtime#106179|
|[770472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770472)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInTOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770472&view=ms.vss-test-web.build-test-results-tab&runId=19680452&resultId=184088)|dotnet/runtime#106169|
|[770358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770358)|dotnet/runtime|[System.Numerics.Tensors.Tests.DoubleGenericTensorPrimitives.Distance_AllLengths](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770358&view=ms.vss-test-web.build-test-results-tab&runId=19677532&resultId=173791)|dotnet/runtime#106166|
|[770020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770020)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770020&view=ms.vss-test-web.build-test-results-tab&runId=19667778&resultId=177915)|dotnet/runtime#106151|
|[770010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770010)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770010&view=ms.vss-test-web.build-test-results-tab&runId=19667056&resultId=179632)|dotnet/runtime#106100|
|[769813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769813)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769813&view=ms.vss-test-web.build-test-results-tab&runId=19660464&resultId=172783)|dotnet/runtime#106111|
|[769293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769293)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769293&view=ms.vss-test-web.build-test-results-tab&runId=19638522&resultId=179605)|dotnet/runtime#106107|
|[768415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768415)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768415&view=ms.vss-test-web.build-test-results-tab&runId=19630790&resultId=177195)|dotnet/runtime#106014|
|[768462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768462)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768462&view=ms.vss-test-web.build-test-results-tab&runId=19611982&resultId=184307)|dotnet/runtime#105866|
|[768382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768382)|dotnet/runtime|[System.Numerics.Tensors.Tests.NFloatGenericTensorPrimitives.SpanScalarSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768382&view=ms.vss-test-web.build-test-results-tab&runId=19606436&resultId=105858)||
|[768349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768349)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768349&view=ms.vss-test-web.build-test-results-tab&runId=19606148&resultId=174347)|dotnet/runtime#99596|
|[767914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767914)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767914&view=ms.vss-test-web.build-test-results-tab&runId=19590284&resultId=196458)|dotnet/runtime#106050|
|[766803](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766803)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInTOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766803&view=ms.vss-test-web.build-test-results-tab&runId=19543332&resultId=176530)|dotnet/runtime#104964|
|[765968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765968)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765968&view=ms.vss-test-web.build-test-results-tab&runId=19521406&resultId=181223)|dotnet/runtime#105868|
|[764532](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764532)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764532&view=ms.vss-test-web.build-test-results-tab&runId=19447072&resultId=165622)|dotnet/runtime#105894|
|[764230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764230)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764230&view=ms.vss-test-web.build-test-results-tab&runId=19436934&resultId=176617)|dotnet/runtime#105879|
|[763503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763503)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763503&view=ms.vss-test-web.build-test-results-tab&runId=19411540&resultId=171393)|dotnet/runtime#105847|
|[763422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763422)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInTOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763422&view=ms.vss-test-web.build-test-results-tab&runId=19409260&resultId=178342)|dotnet/runtime#105761|
|[763040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763040)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763040&view=ms.vss-test-web.build-test-results-tab&runId=19397688&resultId=188382)|dotnet/runtime#105816|
|[762985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762985)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762985&view=ms.vss-test-web.build-test-results-tab&runId=19396830&resultId=190822)|dotnet/runtime#105812|
|[762880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762880)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762880&view=ms.vss-test-web.build-test-results-tab&runId=19393654&resultId=189509)|dotnet/runtime#105647|
|[762573](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762573)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762573&view=ms.vss-test-web.build-test-results-tab&runId=19381880&resultId=184932)|dotnet/runtime#105789|
|[761337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761337)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761337&view=ms.vss-test-web.build-test-results-tab&runId=19340162&resultId=175936)|dotnet/runtime#103752|
|[761191](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761191)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761191&view=ms.vss-test-web.build-test-results-tab&runId=19332800&resultId=180454)|dotnet/runtime#105671|
|[760039](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760039)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760039&view=ms.vss-test-web.build-test-results-tab&runId=19297422&resultId=173185)|dotnet/runtime#105427|
|[759277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759277)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759277&view=ms.vss-test-web.build-test-results-tab&runId=19282778&resultId=191916)|dotnet/runtime#105581|
|[758407](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758407)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758407&view=ms.vss-test-web.build-test-results-tab&runId=19245422&resultId=170697)|dotnet/runtime#104849|
|[757147](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757147)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757147&view=ms.vss-test-web.build-test-results-tab&runId=19202030&resultId=179961)|dotnet/runtime#105541|
|[756714](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756714)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756714&view=ms.vss-test-web.build-test-results-tab&runId=19191144&resultId=168802)|dotnet/runtime#105308|
|[756409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756409)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756409&view=ms.vss-test-web.build-test-results-tab&runId=19177902&resultId=198554)|dotnet/runtime#105544|
|[756082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756082)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756082&view=ms.vss-test-web.build-test-results-tab&runId=19169928&resultId=176996)|dotnet/runtime#105531|
|[755785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755785)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755785&view=ms.vss-test-web.build-test-results-tab&runId=19162440&resultId=212453)|dotnet/runtime#105517|
|[754695](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754695)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754695&view=ms.vss-test-web.build-test-results-tab&runId=19131056&resultId=186822)|dotnet/runtime#105207|
|[754100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754100)|dotnet/runtime|[System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.Log_AllValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754100&view=ms.vss-test-web.build-test-results-tab&runId=19121380&resultId=167321)|dotnet/runtime#104964|
|[754191](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754191)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754191&view=ms.vss-test-web.build-test-results-tab&runId=19116046&resultId=177977)|dotnet/runtime#85344|
|[753057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753057)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753057&view=ms.vss-test-web.build-test-results-tab&runId=19080550&resultId=178882)|dotnet/runtime#105308|
|[752619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752619)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752619&view=ms.vss-test-web.build-test-results-tab&runId=19069582&resultId=191221)|dotnet/runtime#104957|
|[751070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751070)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751070&view=ms.vss-test-web.build-test-results-tab&runId=19064050&resultId=173546)|dotnet/runtime#105268|
|[751836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751836)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInTOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751836&view=ms.vss-test-web.build-test-results-tab&runId=19049136&resultId=211112)|dotnet/runtime#104957|
|[751024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751024)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751024&view=ms.vss-test-web.build-test-results-tab&runId=19017790&resultId=166629)|dotnet/runtime#104957|
|[749527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749527)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749527&view=ms.vss-test-web.build-test-results-tab&runId=18967028&resultId=174667)|dotnet/runtime#105205|
|[749028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749028)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749028&view=ms.vss-test-web.build-test-results-tab&runId=18949080&resultId=169254)|dotnet/runtime#105181|
|[748782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748782)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748782&view=ms.vss-test-web.build-test-results-tab&runId=18940776&resultId=184727)|dotnet/runtime#104959|
|[746673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746673)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746673&view=ms.vss-test-web.build-test-results-tab&runId=18877440&resultId=203617)|dotnet/runtime#104848|
|[746420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746420)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746420&view=ms.vss-test-web.build-test-results-tab&runId=18869096&resultId=176320)|dotnet/runtime#105084|
|[744934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744934)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744934&view=ms.vss-test-web.build-test-results-tab&runId=18825790&resultId=178842)|dotnet/runtime#105003|
|[744859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744859)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744859&view=ms.vss-test-web.build-test-results-tab&runId=18822898&resultId=175870)|dotnet/runtime#104961|
|[744435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744435)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsTwoSpanInFloatOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=744435&view=ms.vss-test-web.build-test-results-tab&runId=18812188&resultId=178694)|dotnet/runtime#105016|
|[743917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743917)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743917&view=ms.vss-test-web.build-test-results-tab&runId=18795768&resultId=171782)|dotnet/runtime#104393|
|[743452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743452)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743452&view=ms.vss-test-web.build-test-results-tab&runId=18785864&resultId=191408)|dotnet/runtime#104848|
|[743262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743262)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743262&view=ms.vss-test-web.build-test-results-tab&runId=18778186&resultId=181953)|dotnet/runtime#104552|
|[743196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743196)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationDestinationFunctions_InPlace](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743196&view=ms.vss-test-web.build-test-results-tab&runId=18774096&resultId=188125)|dotnet/runtime#104848|
|[742229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742229)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742229&view=ms.vss-test-web.build-test-results-tab&runId=18743868&resultId=201571)|dotnet/runtime#104848|
|[741281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741281)|dotnet/runtime|[System.Numerics.Tensors.Tests.DoubleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741281&view=ms.vss-test-web.build-test-results-tab&runId=18715912&resultId=195270)|dotnet/runtime#104848|
|[741278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741278)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741278&view=ms.vss-test-web.build-test-results-tab&runId=18715316&resultId=190584)|dotnet/runtime#104536|
|[740696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740696)|dotnet/runtime|[System.Numerics.Tensors.Tests.DoubleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740696&view=ms.vss-test-web.build-test-results-tab&runId=18693194&resultId=192132)|dotnet/runtime#104848|
|[740646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740646)|dotnet/runtime|[System.Numerics.Tensors.Tests.DoubleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740646&view=ms.vss-test-web.build-test-results-tab&runId=18691914&resultId=204548)|dotnet/runtime#104848|
|[740442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740442)|dotnet/runtime|[System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740442&view=ms.vss-test-web.build-test-results-tab&runId=18687860&resultId=199853)|dotnet/runtime#104857|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|21|67|

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240619.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=712478&view=ms.vss-test-web.build-test-results-tab&runId=17814304&resultId=186952&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress1_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
net9.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.151808769
            Actual:   0.25312683
[4]: Item:  5
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.253379166
            Actual:   0.138663024
[5]: Item:  6
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.344092488
            Actual:   -0.0114496415
[6]: Item:  7
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.410494238
            Actual:   -0.248638168
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20240623.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717422&view=ms.vss-test-web.build-test-results-tab&runId=17968882&resultId=196602&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-jitosr_stress_random-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut<Single>
```

**Error message:**
```
Assert.All() Failure: 1 out of 12 items in the collection did not pass.
[11]: Item:  [1, 2, 3, 4, 5, ···]
Error: Assert.Equal() Failure: Values differ
Expected: 0.000104251681
Actual:   0.000104251689
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorTests.TensorExtensionsSpanInSpanOut[T](PerformCalculationSpanInSpanOut`1 tensorPrimitivesOperation, Func`2 tensorOperation) in /_/src/libraries/System.Numerics.Tensors/tests/TensorTests.cs:line 96
   at InvokeStub_TensorTests.TensorExtensionsSpanInSpanOut(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
