### ISSUE TITLE
[RyuJit/STRESS_BB_PROFILE] flowgraph.cpp  noway_assert(blockPred->bbTraversalStamp == curTraversalStamp) fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#10354]
1. `fgReplacePred` does not keep the sorted order (#13295);
2. if 1), then `fgAddRefPred` does not find the existing occurrence if the order is not sorted;
3. if 2) then `fgReplacePred` has several occurrences of the same block and when the block dies `fgReplacePred` updates only the first link;
4. if 3) The link to the dead block exposed `noway_assert` in `flowgraph`.

Repro: dotnet/coreclr#18057 

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
Should be fixed by #46351.
