### ISSUE TITLE
BinaryFormatterTests.ValidateAgainstBlobs test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#103530]
```
 BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs(obj: Datatable, blobs: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue]) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Data.Common/src/System/Data/DataTable.cs(294,0): at System.Data.DataTable.SerializeDataTable(SerializationInfo info, Boolean isSingleTable, SerializationFormat remotingFormat)
        /_/src/libraries/System.Data.Common/src/System/Data/DataTable.cs(232,0): at System.Data.DataTable.GetObjectData(SerializationInfo info, StreamingContext context)
        /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/BinaryFormatterTests.cs(183,0): at BinaryFormatTests.FormatterTests.BinaryFormatterTests.CheckObjectTypeIntegrity(ISerializable serializable)
        /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/BinaryFormatterTests.cs(46,0): at BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAndRoundtrip(Object obj, TypeSerializableValue[] blobs, Boolean isEqualityComparer)
        /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/BinaryFormatterTests.cs(23,0): at BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, TypeSerializableValue[] blobs)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=708999
Build error leg or test failing: System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_AllocatingSpan.RsaCryptRoundtrip_OaepSHA3_256
Pull request: https://github.com/dotnet/runtime/pull/103413

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs(obj: Datatable, blobs: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue]) [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=708999
**Error message validated:** `[BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs(obj: Datatable, blobs: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue]) [FAIL]`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 6/16/2024 5:06:31 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
cc @adamsitnik

**Comment by adamsitnik** [comment]
It most likely got fixed with https://github.com/dotnet/runtime/pull/103476. I am going to close it for now and re-open if there are any new hits.
