### ISSUE TITLE
Possible mach port leak on MacOS when running multiple tasks over a long time

### ISSUE THREAD

**Issue by trannamtrung1st** [dotnet/runtime#103507]
### Description

I have a C# program to simulate a consumer worker that pulls out messages from a queue and spawns multiple threads using `Task.Factory.StartNew` with `LongRunning` option to handle these messages.
The consumer worker will call some method with `Task.Delay` to simulate async I/O operations.

At first, I had some issues with memory leak due to `TaskCancellationSource, CancellationToken, CancellationRegistration` etc,... After resolving them, the CPU and memory usage already remain stable for the whole time. However, I noticed the mach ports in the ActivityMonitor keep going up then the app crashes after reaching ~300,000 ports (always). 

I've tried to do the trace and dispose all the things I could but cannot make it run longer without crashing.

### Configuration

+ .NET SDK version: 6.0.417
+ OS: MacOS
+ Chip:	Apple M2
+ Architecture: ARM64
+ Total Number of Cores:	8 (4 performance and 4 efficiency)
+ Memory:	24 GB

### Data
+ Here is the result of `dotnet-counters` tool, the numbers are stable over the whole running time.
```
Name                                                               Current Value
[System.Runtime]                                                                
    % Time in GC since last GC (%)                                         0    
    Allocation Rate (B / 1 sec)                                       4.4978e+08
    CPU Usage (%)                                                         36    
    Exception Count (Count / 1 sec)                                    3,153    
    GC Committed Bytes (MB)                                              374    
    GC Fragmentation (%)                                                  69.912
    GC Heap Size (MB)                                                     94    
    Gen 0 GC Count (Count / 1 sec)                                         6    
    Gen 0 Size (B)                                                47,790,176    
    Gen 1 GC Count (Count / 1 sec)                                         3    
    Gen 1 Size (B)                                                64,160,896    
    Gen 2 GC Count (Count / 1 sec)                                         2    
    Gen 2 Size (B)                                                78,935,184    
    IL Bytes Jitted (B)                                              566,081    
    LOH Size (B)                                                     635,296    
    Monitor Lock Contention Count (Count / 1 sec)                        273    
    Number of Active Timers                                            1,026    
    Number of Assemblies Loaded                                          117    
    Number of Methods Jitted                                           7,158    
    POH (Pinned Object Heap) Size (B)                                117,896    
    ThreadPool Completed Work Item Count (Count / 1 sec)               2,364    
    ThreadPool Queue Length                                                0    
    ThreadPool Thread Count                                              356    
    Time spent in JIT (ms / 1 sec)                                         0    
    Working Set (MB)                                                     546    
```

+ Only the `# Ports` number in Activity Monitor keeps growing

<img width="896" alt="image" src="https://github.com/dotnet/runtime/assets/40495531/9611434b-652a-4718-a41b-320a36ab33dd">

<img width="908" alt="image" src="https://github.com/dotnet/runtime/assets/40495531/bae1b642-c67d-4a13-8a6f-202296308b67">

+ Sometimes I received this message `Receive: 50: mach_msg() (ipc/rcv) unknown error code (1000600b)`

**Comment by trannamtrung1st** [comment]
For more details (maybe a bit unnecessary since the project is quite complicated), this is the project I'm working on that facing the issue. 
It's just in-memory stuffs so anyone can clone and run it locally.
Thanks.
https://github.com/trannamtrung1st/workflow-engines-learning/tree/jint-custom/Samples/WELearning.Samples.DeviceService

**Comment by huoyaoyuan** [comment]
6.0 is close to EOL now. Can you confirm if the issue also reproduces on 8.0?

**Comment by trannamtrung1st** [comment]
Wow, I can confirm this is fixed in .NET 8.0. Thanks so much!
