### ISSUE TITLE
[MONO] * Assertion: should not be reached at `/__w/1/s/src/mono/mono/mini/interp/interp.c:3850`

### ISSUE THREAD

**Issue by RubenPX** [dotnet/runtime#103698]
### Description

I tryed publish a blazor app into a IIS server, but it fails, perhaps if i publish using debug it works

### Reproduction Steps

Build any blazor wasm app with Radzen. In debug mode it works

I tried with AOT and without AOT, but fails

### Expected behavior

Work without problem

### Actual behavior

Throws a MONO error

> Brave / Chrome Error

```
MONO interpreter: NIY encountered in method AddRadzenComponents
Error: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/interp.c:3850

    at ht (dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:12765)
    at Tl (dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:176184)
    at dotnet.native.wasm:0x1e8e7d
    at dotnet.native.wasm:0x3a9dc
    at dotnet.native.wasm:0x375a9
    at dotnet.native.wasm:0x376ca
    at dotnet.native.wasm:0x37733
    at dotnet.native.wasm:0x7c72
    at dotnet.native.wasm:0x16096
    at dotnet.native.wasm:0xc56b5
```

> Firefox error

```
MONO interpreter: NIY encountered in method AddRadzenComponents
ht@https://xxx/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:12765
Tl<@https://xxx/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:176184
@:wasm-function[8021]:0x1e8e7d
@:wasm-function[753]:0x3a9dc
@:wasm-function[674]:0x375a9
@:wasm-function[678]:0x376ca
@:wasm-function[681]:0x37733
@:wasm-function[102]:0x7c72
@:wasm-function[136]:0x16096
@:wasm-function[2885]:0xc56b5
@:wasm-function[2214]:0x9c497
@:wasm-function[2213]:0x9c427
@:wasm-function[1668]:0x7a9f3
@:wasm-function[214]:0x18a35
@:wasm-function[109]:0x14e89
@:wasm-function[102]:0x82ac
@:wasm-function[136]:0x16096
@:wasm-function[2885]:0xc56b5
@:wasm-function[2214]:0x9c497
@:wasm-function[2220]:0x9cd8a
@:wasm-function[2244]:0x9f3ed
@:wasm-function[8012]:0x1e578c
createDotnetRuntime/Module._mono_wasm_invoke_method_bound@https://xxx/_framework/dotnet.native.8.0.6.5orhm1yjav.js:8:115821
kr@https://xxx/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:35365
Nl/e.onRuntimeInitialized/l.javaScriptExports.call_entry_point@https://xxx/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:208578
Oc@https://xxx/_framework/dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:136949
callEntryPoint@https://xxx/_framework/blazor.webassembly.js:1:45490
mn@https://xxx/_framework/blazor.webassembly.js:1:57708
async*fn@https://xxx/_framework/blazor.webassembly.js:1:54176
An@https://xxx/_framework/blazor.webassembly.js:1:60103
@https://xxx/_framework/blazor.webassembly.js:1:60231
@https://xxx/_framework/blazor.webassembly.js:1:60298
```

### Regression?

* Not tested *

### Configuration

.NET Version: 8.0
OS: Windows 23H2 22631.3737
Arch: x64

I'm using blazor with (Chrome or Brave or Firefox)

**Comment by vitek-karas** [comment]
@BrzVlad could you please take a look?

**Comment by kg** [comment]
The method in question looks really simple, so that suggests memory corruption to me or the interp ip ending up misaligned/incorrect
https://github.com/radzenhq/radzen-blazor/blob/f259fa85a57e4df91a8294af3a781209e829c71d/Radzen.Blazor/Common.cs#L288
Could be jiterp.

**Comment by RubenPX** [comment]
I deleted `obj` folder and it worked for me

**Comment by steveisok** [comment]
Can this be closed then?

**Comment by Kyle-Jang-Rogers** [comment]
> I deleted `obj` folder and it worked for me

I have the same issue. Do you mean cleanup obj folder before publish or build? I tried it but still the same issue.
Thanks in advance!

**Comment by RubenPX** [comment]
> > I deleted `obj` folder and it worked for me
> 
> I have the same issue. Do you mean cleanup obj folder before publish or build? I tried it but still the same issue.
> Thanks in advance! 

I deleted obj folder after build

**Comment by wisamidris7** [comment]
I did it and it didn't work still the same issue
I deleted and published the project 3x times

**Comment by vitek-karas** [comment]
@wisamidris7 could you please create a new issue? Given that you observe slightly different behavior it's better to create a new issue to be as specific as possible.
