### ISSUE TITLE
Issue with COM Interop in VB6 After Migrating from .NET 4.8 to .NET 8

### ISSUE THREAD

**Issue by masterprogrammer513** [dotnet/runtime#103656]
I am facing a problem with COM interop in VB6 after migrating from .NET 4.8 to .NET 8. This setup used to work perfectly in .NET 4.8 but is now failing in .NET 8.

Here's the setup:

I have a BaseClass in ASM1 defined as BaseClass : IBaseClass. There is another assembly, ASM2, which has a method like Method(BaseClass baseClass). Both classes are properly implemented with ComVisible attributes and have the necessary GUIDs, etc.

Here is the problematic VB6 code:

vb6 Copy code

```
Dim baseCls As ASM1_BaseClass
Set baseCls = New ASM1_BaseClass

Dim cls2 As ASM2_Class2
Set cls2 = New ASM2_Class2
```

```
cls2.Load(baseCls) ' This line throws InvalidCastException: "Cannot cast BaseClass to BaseClass"
The line cls2.Load(baseCls) throws an InvalidCastException with the message "Cannot cast BaseClass to BaseClass".
```

Has anyone encountered a similar issue when migrating from .NET 4.8 to .NET 8? How can I resolve this casting problem?

This is a sample project

https://github.com/masterprogrammer513/Com-Net8-Problem

![image](https://github.com/dotnet/runtime/assets/23259226/cd31a5a8-2297-4ed1-9a2f-64174e17ef06)

net48 assembly load 
![image](https://github.com/dotnet/runtime/assets/23259226/adb8e9fd-8019-46de-83df-e6a8b7ce8328)

Net8 assembly load 
![image](https://github.com/dotnet/runtime/assets/23259226/9587623d-f206-4a31-8f09-a5005ba9bddd)

.net8 loads a PrentCom multiple times in different contexts which makes a casting problem

**Comment by masterprogrammer513** [comment]
@jkoritzinsky Could I have your idea please?

**Comment by masterprogrammer513** [comment]
Any news?

**Comment by AaronRobinsonMSFT** [comment]
@masterprogrammer513 COM components are now always isolated. This behavior can be altered as described [here](https://learn.microsoft.com/dotnet/core/native-interop/expose-components-to-com#loading-in-the-default-assemblyloadcontext). Ideally this would handled in a more precise manner by directly managing [`AssemblyLoadContext`](https://learn.microsoft.com/dotnet/fundamentals/runtime-libraries/system-runtime-loader-assemblyloadcontext)s.
