### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [dotnet/runtime#103691]
Hi team,

Is there a plan to include the `PrivacyInfo.xcprivacy` manifest as required by Apple? 
ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files. Thanks

Dotnet already included the manifest for iOS, iPadOS, and tvOS platforms, but macOS is excluded now.

Regards,
Hao

**Comment by huoyaoyuan** [comment]
https://github.com/xamarin/xamarin-macios/issues/20059

**Comment by ivanpovazan** [comment]
Hello @baihao, 
- Is your question/concern related to types of data collected or accessing required reasons APIs? 
- Additionally, are you experiencing some issues with your macOS applications?

**Comment by agocke** [comment]
Closing as dup of https://github.com/xamarin/xamarin-macios/issues/20059

**Comment by baihao** [comment]
Hello @ivanpovazan,

>     * Is your question/concern related to types of data collected or accessing required reasons APIs?
Yes, we just want to know the data collection of this library, for macOS, the required reasons APIs are not needed.

>     * Additionally, are you experiencing some issues with your macOS applications?
Actually No, our product just want to follow Apple's guidelines to provide the privacy manifest, but we do not know these info for third party libraries

Thanks a lot for your answer.

**Comment by baihao** [comment]
Hi @agocke
> Closing as dup of [xamarin/xamarin-macios#20059](https://github.com/xamarin/xamarin-macios/issues/20059)
It seems it is for `xamarin/xamarin-macios`, would this can also be applied to dotnet runtime? This privacy manifest is for which version or higher? Thank you.

**Comment by huoyaoyuan** [comment]
> It seems it is for `xamarin/xamarin-macios`, would this can also be applied to dotnet runtime?

The title of the repo is now **.NET for iOS, Mac Catalyst, macOS, tvOS**. It's a part of .NET SDK if I'm correct.

**Comment by ivanpovazan** [comment]
> Yes, we just want to know the data collection of this library, for macOS, the required reasons APIs are not needed.

As far as I know, at this stage we did not investigate how data collection is affected. If you have any concerns could you please post the question in https://github.com/xamarin/xamarin-macios/issues/20059 ?

> Actually No, our product just want to follow Apple's guidelines to provide the privacy manifest, but we do not know these info for third party libraries

[This blog post ](https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/) includes guidance and information on what are the developer responsibilities when using our frameworks with a detailed list of affected required reason APIs.

> It seems it is for xamarin/xamarin-macios, would this can also be applied to dotnet runtime? This privacy manifest is for which version or higher? Thank you.

It is implicitly applied to dotnet runtime if your app is using our frameworks for Apple platforms. The privacy manifest is imposed by Apple and is needed for all applications published to the App store no matter the version of frameworks or third party libraries/SDKs your application is using.
