### ISSUE TITLE
RuntimeMethodHandle.FromIntPtr and RuntimeFieldHandle.FromIntPtr Allocates GC Memory

### ISSUE THREAD

**Issue by joncham** [dotnet/runtime#103601]
### Description

The [recently introduced](https://github.com/dotnet/runtime/issues/67090) APIs [RuntimeMethodHandle.FromIntPtr](https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs#L800) and [RuntimeFieldHandle.FromIntPtr](https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs#L1148) are useful for producing a pointer sized value representing a method/field. However, a GC allocation occurs when retrieving the respective runtime handles via the new `FromIntPtr` methods. This seems to be to ensure the handle target remains alive in the presence of unloadable assemblies.

The IntPtr representation is very useful for interop scenarios with native code, but the GC allocation upon retrieval means the API cannot be used in allocation sensitive code. I can approach these scenarios with a different solution, but wondered if there was any possibility and interest to avoid the stub allocations in the `FromIntPtr` methods.

### Configuration

.NET 7/8

### Regression?

No, these are new APIs.

**Comment by jkotas** [comment]
I would be fine to cache these allocations.

**Comment by stephentoub** [comment]
> It should be fine to cache these allocations.

@jkotas, is this a comment about the consumer of the API or about the API's implementation itself? I'm assuming the former and this issue should be closed?

**Comment by jkotas** [comment]
@joncham Does caching the results of `FromIntPtr` on the consumer side work for you? 

Caching the results on the consumer side is more flexible. It gives you control about cache size and cache invalidation policies, the data cached - you may actually want to cache the full resolved MethodInfo and not just the handle, etc. I think it would make sense to start with that, see how it works in practice, and then evaluate whether it makes sense to move the cache into the BCL or whether it is better for it to stay on the consumer side.

**Comment by joncham** [comment]
> @joncham Does caching the results of `FromIntPtr` on the consumer side work for you?

Yes, I can cache it myself on the client side. I wanted to use the existing `IntPtr` <-> `RuntimeMethodHandle` <-> `MethodInfo` mechanism if it made sense, but am fine maintaining my own.
