### ISSUE TITLE
Ability to obsolete `IEnumerable.GetEnumerator` used through Linq

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#103664]
Assume a class that reads rows from the network
```csharp
class MyDbReader : IEnumerable<object>, IAsyncEnumerable<object>
{
    [Obsolete]
    public IEnumerator<object> GetEnumerator()
    {
        yield return new object();
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    
    public async IAsyncEnumerator<object> GetAsyncEnumerator(CancellationToken cancellationToken = new())
    {
        yield return new object();
    }
}
```
the maintainer recently implemented IAsyncEnumerable after realizing that reading synchronously from the network using the `IEnumerable` was causing a thread pool starvation. They also added the Obsolete attribute on the `GetEnumerator` hoping this would guide the users to use `GetAsyncEnumerator`. Though, if used through a foreach or Linq, no warnings are emitted:
```csharp
MyDbReader r = new();
_ = r.GetEnumerator(); // Method 'MyDbReader.GetEnumerator()' is obsolete
_ = r.Select(x => x); // No warnings.
foreach (var x in r) // No warnings
{
}
```

When `GetEnumerator` is marked as obsolete, would it possible to generate warnings on foreach and Linq?

**Comment by JakeYallop** [comment]
Would this be something fixed by https://github.com/dotnet/roslyn/issues/73920 and https://github.com/dotnet/runtime/issues/103430, at least for the `foreach` case?

**Comment by eiriktsarpalis** [comment]
I'm seeing warnings in the foreach case:

![image](https://github.com/dotnet/runtime/assets/2813363/198a6ca2-6a40-41d0-aee6-76bc39b2c1ce)

I don't think it would be possible to warn for the case of the `Select` since the compiler can't possibly reason about the enumerator being used (it isn't in your case).

**Comment by verdie-g** [comment]
> I'm seeing warnings in the foreach case:

ha, indeed I see the warning in the build output but not in Rider. I'll redirect that issue to JetBrains.

> I don't think it would be possible to warn for the case of the Select since the compiler can't possibly reason about the enumerator being used

In the expression `x.Select`, in the case where `x` is not an IEnumerable (e.g. a `MyDbReader`), I think an analyzer could check if the `GetEnumerator` is obsolete, right?

**Comment by eiriktsarpalis** [comment]
> I think an analyzer could check if the GetEnumerator is obsolete, right?

It could, but like I said technically calling `Select` doesn't create an enumerator. In my view it doesn't seem like a particularly common pattern for us to invest in adding an analyzer.

**Comment by verdie-g** [comment]
> technically calling Select doesn't call GetEnumerator

Hmm true.

> In my view it doesn't seem like a particularly common pattern for us to invest in adding an analyzer.

With the introduction of `IAsyncEnumerable` in .NET Core 3, I feel like this could a great feature to migrate from one to the other. I've seen a bunch of libraries that mistakenly do sync-over-async because of their `IEnumerable` implementation ([example in CassandraCsharpDriver](https://datastax-oss.atlassian.net/browse/CSHARP-994)).
