### ISSUE TITLE
Is the implementation(s) of double-checked locking in XmlElement correct?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#103602]
https://github.com/dotnet/runtime/blob/ac996f3f48ea8c3364c347c24962a75fd80eafae/src/libraries/System.Private.Xml/src/System/Xml/Dom/XmlElement.cs#L18

https://github.com/dotnet/runtime/blob/ac996f3f48ea8c3364c347c24962a75fd80eafae/src/libraries/System.Private.Xml/src/System/Xml/Dom/XmlElement.cs#L237-L252

This implementation matches example 2 in the CodeQL [Double-checked lock is not thread-safe](https://codeql.github.com/codeql-query-help/csharp/cs-unsafe-double-checked-lock/) with a find/replace:

```csharp
XmlAttributeCollection _attributes;    // BAD: Not thread-safe

public XmlAttributeCollection Attributes
{
    get
    {
        if (_attributes == null)
        {
            lock (mutex)
            {
                if (_attributes == null)
                    _attributes = LoadNameFromDatabase();
            }
        }
        return _attributes;
    }
}
```

Is this implementation correct?

**Comment by stephentoub** [comment]
Yes, it's correct, in particular due to the now-documented [memory model](https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md), which states:

> Reads cannot be introduced.

and

> Object assignment to a location potentially accessible by other threads is a release with respect to accesses to the instance’s fields/elements and metadata.

**Comment by omajid** [comment]
Thank you!
