### ISSUE TITLE
MetaDataGetDispenser export missing for PublishSingleFile=true, and --self-contained

### ISSUE THREAD

**Issue by georgschausberger** [dotnet/runtime#103687]
### Description

If a .NET application is published with PublishSingleFile=true and --self-contained there are no exports to MetaDataGetDispenser any more. This method is needed for many ClrProfilers.

### Reproduction Steps

PublishSingleFile=true and --self-contained,
use objdump -TC myExecutable.exe to show the exported symbols.

### Expected behavior

symbold should be available

### Actual behavior

symbol is not available

### Known Workarounds

none

### Configuration

.NET 6 and newer

**Comment by jkotas** [comment]
This was fixed long time ago https://github.com/dotnet/runtime/pull/47451. This fix was included in .NET 6. I do see the symbol exported as expected from a single-file binary:

```
jkotas@jkotas-notebook:~/test/bin/Release/net8.0/linux-x64/publish$ objdump -TC ./test | grep MetaDataGetDispenser
0000000000925940 g    DF .text  00000000000000e8  V1.0        MetaDataGetDispenser
```

> use objdump -TC myExecutable.exe to show the exported symbols.

objdump is Unix-based tool and it may not work well for Windows binaries (depends on the variant of the tool that you use). Do you see this problem for Windows self-contained binary or Linux self-contained binary? Could you please include platform details and share more detailed steps to reproduce problem?

**Comment by georgschausberger** [comment]
Hi @jkotas ,
sorry for the confusion.

I've to apologize, it looks like the dispenser is correctly exported. The issue was on how to query for the exported method though.

Thanks for looking into this!

Best,
Georg
