### ISSUE TITLE
[ios-8.0/9.0] Cannot compile project with AOT enabled (Assertion at mini-llvm.c, condition `cinfo->ret.nslots == 1' not met)

### ISSUE THREAD

**Issue by vyacheslav-volkov** [dotnet/runtime#103628]
### Description

I'm developing a large project and at the very beginning the code compiled without problems, but after a while I checked again and got this error, I don’t have time to look for which specific type breaks the assembly, is it possible to display a more specific error message and how can I debug it?

I tried the latest net9.0-preview 5 but the result is the same.

### Reproduction Steps

I can't provide the source code as this is a commercial product.

### Expected behavior

No compilation errors

### Actual behavior

Mono Ahead of Time compiler - compiling assembly ..../obj/Release/net9.0-ios/ios-arm64/linked/MugenMvvm.dll
AOTID 0D0A964D-FAF6-A1E4-FADC-1F08E0767345
* Assertion at /Users/runner/work/1/s/src/mono/mono/mini/mini-llvm.c:1605, condition `cinfo->ret.nslots == 1' not met

**Comment by vyacheslav-volkov** [comment]
Hi @ivanpovazan, I think I've found the issue, I had ref type with no fields and marked with `[StructLayout(LayoutKind.Auto)]` once I removed the attribute the error went away.
```
    [StructLayout(LayoutKind.Auto)]
    public ref struct Builder<T>
    {
    }
 ```

**Comment by ivanpovazan** [comment]
Is this then still blocking you?

In any case we would appreciate if you could provide a smaller repro, so we could look into generating better error messages.

**Comment by vyacheslav-volkov** [comment]
@ivanpovazan thanks for the help, no blockers atm, I just removed `[StructLayout(LayoutKind.Auto)]` as it is redundant for this struct, I'll try to create a small repo to reproduce the issue.

**Comment by vyacheslav-volkov** [comment]
@ivanpovazan I've reproduced this with a simple example:
```
using System.Runtime.InteropServices;

namespace iOSApp1;

public static class Builder
{
    public static Builder<T> Get<T>() => new();
}

[StructLayout(LayoutKind.Auto)]
public ref struct Builder<T>
{
    public object Build() => "";
}

[Register("AppDelegate")]
public class AppDelegate : UIApplicationDelegate
{
    public override UIWindow? Window { get; set; }

    public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {
        Builder.Get<string>().Build();
        return true;
    }
}
```

**Comment by vitek-karas** [comment]
@jkurdek could you please try to repo and look what's going on?

**Comment by jkurdek** [comment]
```c#

[StructLayout(LayoutKind.Sequential)]
public struct Builder1
{
    public string Build() => "Hello";
}

namespace HelloWorld
{
    internal class Program
    {
        public static Builder1 Get() => new Builder1();
        private static void Main(string[] args)
        {

        }
    }
}

**Comment by jkurdek** [comment]
Minimal repro:

```c#
[StructLayout(LayoutKind.Auto)] // Also occurs when with [StructLayout(LayoutKind.Sequential)] 
public struct Builder1
{
    public string Build() => "Hello";
}

namespace HelloWorld
{
    internal class Program
    {
        public static Builder1 Get() => new Builder1();
        private static void Main(string[] args)
        {

        }
    }
}
```

---

### Initial investigation:
The issue seems to be caused by placing `StructLayoutAttribute` on a struct with no fields. The size of such struct is then computed to be 0. Then during handling of `Get()` method , 0 registers are allocated for the return value. Which then leads to failing assertion.

Will follow up with more detailed analyis
