### ISSUE TITLE
 Proposal: use ValueTask<TItem> in CacheExtensions.GetOrCreateAsync

### ISSUE THREAD

**Issue by gumbarros** [dotnet/runtime#103666]
Duplicated of #67069 

Why is this issue closed? It's marked as completed with no explanation and the method still returns a `Task`.

**Comment by stephentoub** [comment]
For the reason cited here:
https://github.com/dotnet/runtime/issues/67069#issuecomment-1076938339
The existing method's return type can't be changed (it's a binary breaking change) and overloading by return type is not supported. A different name / set of arguments would have been needed to be supplied. The creator of the issue then closed it.

**Comment by julealgon** [comment]
@gumbarros this has been implemented as part of the new `HybridCache` coming in .NET 9:
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.hybrid.hybridcache.getorcreateasync?view=netframework-4.8.1&viewFallbackFrom=aspnetcore-9.0

You might want to just switch to that.
