### ISSUE TITLE
AllSubsets_Mono_Minijit_RuntimeTests minijit fails to build with "Could not copy the file hostfxr.dll.pdb because it was not found"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#103642]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=711283
Build error leg or test failing: Build / windows-x64 Release AllSubsets_Mono_Minijit_RuntimeTests minijit / Build product
Pull request: https://github.com/dotnet/runtime/pull/103570

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Could not copy the file.*hostfxr",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=711283
**Error message validated:** `[Could not copy the file.*hostfxr`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/18/2024 1:56:53 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[711283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711283)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/711283/logs/1318)|dotnet/runtime#103570|
|[711360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711360)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/711360/logs/537)|dotnet/runtime#102670|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|2|2|

**Comment by lambdageek** [comment]
Shoudl be fixed by https://github.com/dotnet/runtime/pull/103641
