### ISSUE TITLE
lots of unresolved symbols in static lib?

### ISSUE THREAD

**Issue by ljzj2** [dotnet/runtime#103747]
### Description

I created library in .net 8.0 and compile it to static lib(native aot):
dotnet publish -r win-x64 -c release /p:NativeLib=Static
and want to use it in c++ program 
but there is so errors.

### Reproduction Steps

1. create .net 8.0 library
2. write function 
[UnmanagedCallersOnly(EntryPoint = "get")]
public static IntPtr Get(IntPtr url,){

.......
return Intptr.Zero;
}
3. create c++ program and use it
#pragma comment(lib,"mylib.lib")
extern "C" get (const char* url);

int main(){
auto val=get("this is my href");
}

### Expected behavior

will run perfectly

### Actual behavior

lots of errors unresolved symbols
RhYield	
 RhWaitForPendingFinalizers	
 RhUnregisterForGCReporting
 RhSuppressFinalize
....
NCryptSetProperty
 NCryptOpenKey
 NCryptDeleteKey
......
 g_cpuFeatures
....
GlobalizationNative_ToUnicode
 GlobalizationNative_LastIndexOf
GlobalizationNative_InitICUFunctions

....

as many as over 130 error

**Comment by MichalStrehovsky** [comment]
Additional static libraries are needed to successfully link. Refer to https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary#building-static-libraries, specifically "You can find a list of additional framework libraries by publishing the project as shared library (/p:NativeLib=Shared) with detailed verbosity (-v d), and looking at the output generated by the LinkNative target.".

We do not recommend building static libraries, the developer experience is rough.

**Comment by ljzj2** [comment]
I just do as the command
can you tell me how to link the libraries? using static.

**Comment by ljzj2** [comment]
If I do not set `<IlcGenerateWin32Resources>false</IlcGenerateWin32Resources>` 
I can not use this lib in c++ program.
If I use this there will be errors

**Comment by ljzj2** [comment]
Ok as you say I will not do that.
