### ISSUE TITLE
System.Reflection.Emit value type mismatch trying to create a value type

### ISSUE THREAD

**Issue by Zorbn** [dotnet/runtime#103796]
### Description

I'm trying to create a value type using the .NET 9 System.Reflection.Emit API. I wasn't able to find an example, so I tried to just define a type with a parent type of System.ValueType. Unfortunately, I get the following error when I run an assembly that uses the type. My guess is that there is a different, intended way to define a value type.

`Unhandled Exception: System.TypeLoadException: Could not load type 'myValueType' from assembly 'MyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.`

### Reproduction Steps

Define and create a type extending System.ValueType, then use it by declaring a local.

```csharp
var context = new MetadataLoadContext(resolver);
var valueType = content.CoreAssembly!.GetType("System.ValueType")!;
var myValueType = moduleBuilder.DefineType("myValueType", 0, valueType);
// ...
myValueType.CreateType();
// ...
ilGenerator.DeclareLocal(myValueType);
```

### Expected behavior

Either extending from System.ValueType works, or there is some other way to define a value type using System.Reflection.Emit.

### Actual behavior

`Unhandled Exception: System.TypeLoadException: Could not load type 'myValueType' from assembly 'MyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.`

### Configuration

Using .NET 9.0.100-preview.5.24307.3 and also using the reference assemblies from that version of .NET for my MetaDataLoadContext resolver.

**Comment by jkotas** [comment]
The problem is likely caused by wrong IsValueType value here: https://github.com/dotnet/runtime/blob/f06bc4dd3f281d8b96a0c873daeb6911ef39c55d/src/libraries/System.Reflection.Emit/src/System/Reflection/Emit/SignatureHelper.cs#L293 .

cc @buyaa-n

**Comment by Zorbn** [comment]
Here's a full example. It only happens when using the MetadataLoadContext's CoreAssembly. When I remove that part it works fine.

```csharp
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Loader;

var resolver =
    new PathAssemblyResolver(Directory.GetFiles("C:\\Program Files\\dotnet\\sdk\\9.0.100-preview.5.24307.3\\ref",
        "*.dll"));
using var context = new MetadataLoadContext(resolver);
var coreAssembly = context.CoreAssembly!;

var valueTypeType = coreAssembly.GetType("System.ValueType")!;

var ab = new PersistedAssemblyBuilder(new AssemblyName("MyAssembly"), coreAssembly);
var mob = ab.DefineDynamicModule("MyModule");

var valueTb = mob.DefineType("MyValueType", 0, valueTypeType);
valueTb.CreateType();

var tb = mob.DefineType("MyType", TypeAttributes.Public | TypeAttributes.Class);
var meb = tb.DefineMethod("MyMethod", MethodAttributes.Public | MethodAttributes.Static);
var il = meb.GetILGenerator();
il.BeginScope();
il.DeclareLocal(valueTb);
il.EndScope();
il.Emit(OpCodes.Ret);

tb.CreateType();

using var stream = new MemoryStream();
ab.Save(stream);
stream.Seek(0, SeekOrigin.Begin);
var assembly = AssemblyLoadContext.Default.LoadFromStream(stream);
var method = assembly.GetType("MyType")!.GetMethod("MyMethod");
method!.Invoke(null, null);
```

**Comment by Zorbn** [comment]
My local hack/fix for this was to add `protected override bool IsValueTypeImpl() => _typeParent?.FullName == "System.ValueType" || _typeParent?.IsValueType == true;` to TypeBuilderImpl. Probably not ideal but it's enough to allow me to move forward for now.
