### ISSUE TITLE
Incorrect if evaluation results in `if (true != true)` being true

### ISSUE THREAD

**Issue by brandonagr** [dotnet/runtime#103786]
### Description

We ran across a scenario where an if statement seems to do the wrong thing, `if (true != true)` should be false, but when running the program below it evaluates that if statement to true. 

This is a small repro from a larger code base, the fact that a Guid value is being written into what should only contain a bool true or false was a different bug in our code, but the fact that the debugger and every output shows it correctly reporting the value after the `bool?` conversion is true but the if statement is doing something different makes it look like something is wrong in the runtime

### Reproduction Steps

https://dotnetfiddle.net/HqPIDD

```c#
using System;
using System.Runtime.InteropServices;
					
public class Program
{
	public static void Main()
	{
		var accessor = new TestProperty() {IsConfirmation = true};
		var wrappedValue = new Value(true);
		
		bool? metaValue = (bool?)wrappedValue;
		bool result = true;
		
		Console.WriteLine(accessor.IsConfirmation);
		Console.WriteLine(metaValue.Value);
		
		if (accessor.IsConfirmation != metaValue.Value)
		{
			Console.WriteLine($"Shouldn't get here {accessor.IsConfirmation} != {metaValue.Value}");
			result = false;
		}

		if (!result)
		{
			Console.WriteLine("What happened?")	;
		}
		else
		{
			Console.WriteLine("Worked as expected");
		}			
	}
	
	struct Value
	{
		public Value(bool initial)
		{
			_data.BooleanField = initial;
			
			// If you comment out this line it will work as expected
			_data.GuidField = new Guid("7cb8a2c8-4bb7-4374-94b2-c9232d20ec46");
		}
		
		UnionOfStuff _data;
		
		public static explicit operator bool?(Value valueToCast)
		{
			return valueToCast._data.BooleanField;
		}
	}
	
	[StructLayout(LayoutKind.Explicit)]
	struct UnionOfStuff
	{
		[FieldOffset(0)]
		public bool BooleanField;
		[FieldOffset(0)]
		public Guid GuidField;
	}
	
	class TestProperty
    {
        public bool IsConfirmation;
    }
}
```

### Expected behavior

```
True
True
Worked as expected
```

### Actual behavior

```
True
True
Shouldn't get here True != True
What happened?
```

### Regression?

Previous frameworks and dotnet core versions seem to do the same thing

### Configuration

net8

**Comment by MihaZupan** [comment]
Using `bool` values backed by something other than 0/1 is asking for trouble.
See https://github.com/dotnet/roslyn/blob/main/docs/compilers/Boolean%20Representation.md

**Comment by ScarletKuro** [comment]
I'm not an expert in runtime specifics, but it's clear that this:

```csharp
[StructLayout(LayoutKind.Explicit)]
struct UnionOfStuff
{
    [FieldOffset(0)]
    public bool BooleanField;
    [FieldOffset(0)]
    public Guid GuidField;
}
```

will share the same memory location, leading to unexpected behavior. When you compare with `!=`, it compares the binary representations, which are not equal, but the internal `m_value` is the same. If you used `Equals` instead, it wouldn't hit that if clause. However, this is just my theory.

**Comment by colejohnson66** [comment]
As has been said: booleans in C# are compared by their bitwise value. They're similar to C's `#define` style boolean: any non-zero value evaluates as `true`, but an equality comparison compares the equivalent-integer-sized representation. This is an optimization performed by the runtime because normal code will never create booleans that _aren't_ 0 or 1.

In other words, given two booleans, `x` and `y`:
* `if (x)` is the same as `if (Unsafe.As<bool,int>(ref x) != 0)`
* `x==y` is actually `Unsafe.As<bool,int>(ref x)==Unsafe.As<bool,int>(ref y)`

By aliasing a boolean against something that _isn't_ a boolean, you're entering dangerous territory where, even if `if(x)` and `if(y)` evaluate as `true` and execute, `if(x==y)` _could_ evaluate as `false` and not execute.

**Comment by Spacefish** [comment]
```csharp
	[StructLayout(LayoutKind.Explicit)]
	struct UnionOfStuff
	{
		[FieldOffset(0)]
		public bool BooleanField;
		[FieldOffset(0)]
		public Guid GuidField;
	}
```
This will make the Guid and the boolean share the same memory. If any of the first bit´s of the Guid is set, the BooleanField will evaluate be true!

```csharp
var u = new UnionOfStuff();
u.BooleanField = false;
u.GuidField = Guid.NewGuid();

Console.WriteLine($"BooleanField: {u.BooleanField} Guid: {u.GuidField}");

u.BooleanField = true;

Console.WriteLine($"BooleanField: {u.BooleanField} Guid: {u.GuidField}");
```
This could will output something like:

```
BooleanField: True Guid: 6beab008-6a23-4c92-9bf6-4008e29b2190
BooleanField: True Guid: 6beab001-6a23-4c92-9bf6-4008e29b2190
```
