### ISSUE TITLE
Avoid NRE by throwing JsonException when deserializing "null" into non-nullable types

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#1037]
Currently, the following throws a `NullReferenceException`. It should instead throw `JsonException`.
```C#
public struct Foo
{
}

// throws NRE rather than InvalidOperationException
Foo mystruct = JsonSerializer.Deserialize<Foo>("null");
```

The behavior should be similar to the following (i.e. throw `JsonException` with relevant info in the message):
```C#
// System.Text.Json.JsonException : The JSON value could not be converted to System.Int32. 
// Path: $ | LineNumber: 0 | BytePositionInLine: 4.
//      ---- System.InvalidOperationException : Cannot get the value of a token type 
// 'Null' as a number.
int myint = JsonSerializer.Deserialize<int>("null");
```

Currently:
https://github.com/dotnet/runtime/blob/2755362aed8412f47a3ca6cc419a9a85f55b0314/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Span.cs#L22-L25

A naive fix like this could work, however, the exception wouldn't contain any useful information as part of the message:
```C#
public static TValue Deserialize<TValue>(ReadOnlySpan<byte> utf8Json, JsonSerializerOptions? options = null)
{
    object? result = ParseCore(utf8Json, typeof(TValue), options);

    if (result != null || default(TValue)! == null || Nullable.GetUnderlyingType(typeof(TValue)) != null)
    {
        return (TValue)result!;
    }

    throw new JsonException();
}
```

A more appropriate fix would be to check within the null handling logic and see whether the type can be set to null. If it can't, throw a `JsonException` there.
https://github.com/dotnet/runtime/blob/2755362aed8412f47a3ca6cc419a9a85f55b0314/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandleNull.cs#L24-L29

That way, the exception can be appended with the relevant info:
https://github.com/dotnet/runtime/blob/2755362aed8412f47a3ca6cc419a9a85f55b0314/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.cs#L134-L138

The difficulty there is that for root objects, `jsonPropertyInfo is null` and hence you can't rely on `jsonPropertyInfo.CanBeNull` to tell you that the type doesn't support `null`. This is where the investigation needs to occur along with the fix.

This needs to be fixed for all the generic `Deserialize` overloads along with adding relevant tests for all the overloads.

See additional info here:
https://github.com/dotnet/runtime/pull/528#discussion_r358594639

cc @steveharter, @layomia

**Comment by layomia** [comment]
This work should also include collections like `ImmutableArray<T>`: https://github.com/dotnet/corefx/issues/42399.
