### ISSUE TITLE
Date Time to string conversion Non-Breaking Space Being added when running in an Azure App Service Linux hosting .NET 8

### ISSUE THREAD

**Issue by ezrasocial2310** [dotnet/runtime#103750]
### Description

We have encountered an issue with non-breaking spaces being added during DateTime to string conversion. While this works fine on Windows, it causes problems on Linux. We having a large Web API application, changing this in numerous places would require significant effort and testing time. We are seeking expert advice to resolve this issue globally and quickly.

If you have any suggestions or solutions, please share them.

### Reproduction Steps

string dt = Convert.ToString(DateTime.Now));

### Expected behavior

without special character IN front  AM

### Actual behavior

'06/20/2024 12:00:00 AM' => the is some special character infornt of AM
![Untitled](https://github.com/dotnet/runtime/assets/142308030/46bbb7ea-aa35-46ce-a815-9895040ecbc8)

**Comment by tarekgh** [comment]
@ezrasocial2310 this is intentional change done by Unicode standard to disallow date string wrap in the middle by using non-break narrow space. I am closing the issue but feel free to respond with more details about how this broke you. Are you manually parsing the string?

**Comment by Clockwork-Muse** [comment]
As a side note:
```csharp
string dt = Convert.ToString(DateTime.Now));
```
If this is an API that's meant to be doing interchange, _this code is wrong_, in one (or possibly two) ways.
 1) You should be formatting with a round-trip format (`"O"`) in the invariant culture, or an explicit format string mimicking the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601) (if you need a subset of fields).
 1) _Usually_ server applications should always explicitly call `DateTime(Offset).UtcNow`, not the "local" now, and it would be even better from a testability standpoint to use [`TimeProvider`](https://learn.microsoft.com/en-us/dotnet/api/system.timeprovider?view=net-8.0).  For the rare times that some entity-specific local time (usually calendaring/future date work), ensure that you're retrieving the relevant timezone from the entity config record and explicitly converting it (or creating a custom `TimeProvider` instance with the relevant zone set), don't call the local `Now` directly.  Additionally, it will be easier and safer to drop the use of `DateTime` for such scenarios and instead only use `DateTimeOffset` (or switching wholesale to NodaTime).

**Comment by ezrasocial2310** [comment]
Is there any way to handle the entire system generically? For example, can we use middleware to set CultureInfo or adjust system threads or any other way ? Please provide guidance.

**Comment by ezrasocial2310** [comment]
> @ezrasocial2310 this is intentional change done by Unicode standard to disallow date string wrap in the middle by using non-break narrow space. I am closing the issue but feel free to respond with more details about how this broke you. Are you manually parsing the string?

Yes, in our application, many places convert.ToString() are used without specifying the CultureInfo or any specific format. any workout to resolve this problem in Linux server
