### ISSUE TITLE
Incorrect time patterns for some cultures on browser in `HybridGlobalization`

### ISSUE THREAD

**Issue by PopSlime** [dotnet/runtime#103745]
### Description

On browser when `HybridGlobalization` is on, some cultures (specifically, `fr-CA`) have incorrect time patterns, causing `DateTime.ToString(IFormatProvider)` to produce badly formatted strings.

### Reproduction Steps

Consider the following code:

```cs
new DateTime(2000, 1, 1, 20, 0, 0).ToString("T", new CultureInfo("fr-CA"));
```

### Expected behavior

A correctly formatted string (like `20 h 00 min 00 s` with the long time pattern `HH 'h' mm 'min' ss 's'`) is returned.

### Actual behavior

A badly formatted string `20 8 00 0in 00 0` is returned, with the long time pattern being `HH h mm min ss s`.

### Configuration

- .NET version: 8.0
- Target platform: Browser
- Web browser: Chrome, Firefox
- `HybridGlobalization`

### Other information

The incorrect patterns in the browser environment is caused by the following code, which does not handle literal texts and copies them into the pattern as is.

https://github.com/dotnet/runtime/blob/8ab80b9af668601ebc102760b4c4e60d23ba8d8f/src/mono/browser/runtime/hybrid-globalization/culture-info.ts#L77

This issue was found during the process of fixing #103592 and the PR #103681.

**Comment by tarekgh** [comment]
CC @ilonatommy
