### ISSUE TITLE
`InlineArrayAttribute` should allow for vectorization

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#103712]
Default implementations of `Equals()` and `GetHashCode()` now throw. It is expected for them to be implemented by users. How this was done though, does result in a lost opportunity. See comment below.

> This is an unfortunate consequence of throwing.

> We'd otherwise be able to treat `InlineArray` of primitive types as bitwise equatable and allow them to participate in some of the vectorization speedups.

> It would be nice if there was a better way to allow users to override the default while still opting their types into bitwise equality support.

_Originally posted by @tannergooding in https://github.com/dotnet/runtime/pull/103612#discussion_r1646376093_

**Comment by MichalPetryka** [comment]
Duplicate of #75642?

**Comment by AaronRobinsonMSFT** [comment]
> Duplicate of #75642?

Agreed.
