### ISSUE TITLE
[API Proposal]: Extend HostApplicationBuilderSettings with ServiceProviderOptions

### ISSUE THREAD

**Issue by Bonuspunkt** [dotnet/runtime#103730]
### Background and motivation

it is currently not possible to configure the service provider when creating a host.

came across a wpf application where the EF DataContext was created from the root provider

### API Proposal

```csharp
namespace Microsoft.Extensions.Hosting
{
    public sealed class HostApplicationBuilderSettings
    {
        //...
        public ServiceProviderOptions? ServiceProviderOptions { get; set; };
    }
}
```

### API Usage

```csharp
var options = new Microsoft.Extensions.DependencyInjection.ServiceProviderOptions 
{
    ValidateScopes = true 
};
var settings = new Microsoft.Extensions.Hosting.HostApplicationBuilderSettings
{
    ServiceProviderOption = options
};
var host = Microsoft.Extensions.Hosting.Host.CreateEmptyApplicationBuilder(settings);
```

**Comment by steveharter** [comment]
@Bonuspunkt the API proposal does not contain the actual new API, which I assume is adding a `ServiceProviderOptions` property to `HostApplicationBuilderSettings`?

Normally that would done with something like:
```csharp
ServiceProviderOptions options = ...
HostApplicationBuilder builder = ...
builder.ConfigureContainer(new DefaultServiceProviderFactory(options));
```

Please update the API portion with the actual new API along with examples.

**Comment by Bonuspunkt** [comment]
> the API proposal does not contain the actual new API, which I assume is adding a ServiceProviderOptions property to HostApplicationBuilderSettings
yes

oh, i see. that solves it, ty
