### ISSUE TITLE
'System.PlatformNotSupportedException: The system's ping utility could not be found.' thrown unless running as root on EndeavourOS.

### ISSUE THREAD

**Issue by Ninjastorm380** [dotnet/runtime#103736]
### Description

Ping.Send() is either failing to find the ping binary or cannot access the ping binary as a non-root user on EndeavourOS.

### Reproduction Steps

This vb.net code snippet triggers a System.PlatformNotSupportedException while executing as a non-root user reliably on EndeavourOS, and will not fail if the user is root.
```vb
Public Function PingAddress(Address As Net.IpAddress) As Boolean
    If (New Ping).Send(Address).Status = IPStatus.Success Then
        Return True
    End If
    Return False
End Function
```

### Expected behavior

Calls to Ping.Send() should function while running as a non-root user.

### Actual behavior

Ping.Send() throws a System.PlatformNotSupportedException with message 'The system's ping utility could not be found.' while running as a non-root user.

### Regression?

Unknown

### Known Workarounds

Run as root (this is a bad idea).

### Configuration

.Net Version: running on 8.0.6, with the library causing this error targeting netstandard2.0
OS: EndeavourOS Rolling (Archlinux Derivative) 
Arch: linux-x64
Configuration Specific: Not Tested, but presumed that this may also affect Archlinux users as well.

### Other information

it should be noted that archlinux package `iputils` no longer provides separate ping6 and ping4 binaries in favor of a unified ping binary. `src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs` appears to use the old names still.

**Comment by wfurt** [comment]
Do you have `ping` package installed (or equivalent) @Ninjastorm380? On Linux "normal" user does not have access to RAW socket e.g. trying to execute the ping utility is only one way for .NET.

**Comment by Ninjastorm380** [comment]
@wfurt ping is installed and operational.

**Comment by Ninjastorm380** [comment]
also, to quote myself here:

> `src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs` appears to use the old names still.

looks like you are trying to find ping4 and ping6, when those have been merged into just ping on EndeavourOS. I suspect the same is also true for archlinux, and that the old names are just symlinks for compatibility if they are found.

**Comment by wfurt** [comment]
I could see it being problem with IPv6. But there is still plain old `ping` on my Ubuntu. Perhaps @ManickaP can give it a shot on Arch.

**Comment by Ninjastorm380** [comment]
some additional info I dug up @wfurt: AUR package `iputils-ping6-symlink` provides symlinks to ping as ping4 and ping6, but it's description implies that it is intended for compatibility purposes. Changes are probably needed to avoid relying on compat packages.

**Comment by Ninjastorm380** [comment]
mind if I take this on? I know what would be needed (search for ping on linux first, then ping4/ping6)
