### ISSUE TITLE
AndroidStripILAfterAOT causing "InvalidProgramException: Invalid IL code in Xunit.Assert:True(bool)"

### ISSUE THREAD

**Issue by tranb3r** [dotnet/runtime#103782]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022 17.8.5

### Description

When setting `AndroidStripILAfterAOT=true` in a test app, some tests are failing the first time we run them, but then they'll pass if we run them again. 
The error is 100% reproducible when starting the app again.
Here is the error: `InvalidProgramException: Invalid IL code in Xunit.Assert:True(bool): method body is empty`.
No issue in Debug. No issue when removing `AndroidStripILAfterAOT=true`.
This is similar to dotnet/android#8562, but no BroadcastReceiver is involved here.

### Steps to Reproduce

1. Open [repro](https://git.histb.com/tranb3r/Issues/tree/main/MauiAppXunitInvalidILCode) in visual studio.
2. Run app in Release on android emulator.
3. Run all tests: one of the test fails.
4. Run all tests again: both tests succeed.

### Did you find any workaround?

Remove `AndroidStripILAfterAOT=true`.

**Comment by tipa** [comment]
@fanyang-mono will this fix also resolve https://github.com/dotnet/android/issues/8562?

**Comment by fanyang-mono** [comment]
The fix to this issue is on track to be shipped as part of .NET9 Preview7. Additionally, I've opened an PR to backport this fix to .NET8.

**Comment by tranb3r** [comment]
I've just tested net9-pre7. The fix works on my repro project. Thx.
