### ISSUE TITLE
nativeaot/SmokeTests/Exceptions failing with `Assertion failed: (n_heaps <= heap_number) || !gc_t_join.joined()`

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#103839]
```
Assertion failed: (n_heaps <= heap_number) || !gc_t_join.joined(), file D:\a\_work\1\s\src\coreclr\gc\gc.cpp, line 6988

Return code:      1
Raw output file:      C:\h\w\B51009A0\w\B29A098A\uploads\Reports\nativeaot.SmokeTests\Exceptions\Exceptions\Exceptions.output.txt
Raw output:
BEGIN EXECUTION
call C:\h\w\B51009A0\p\nativeaottest.cmd C:\h\w\B51009A0\w\B29A098A\e\nativeaot\SmokeTests\Exceptions\Exceptions\ Exceptions.dll 
Exception caught!
Null reference exception in write barrier caught!
Null reference exception caught!
Test Stacktrace with exception on stack:
   at BringUpTest.FilterWithStackTrace(Exception) + 0x28
   at BringUpTest.Main() + 0x31c
   at System.Runtime.EH.FindFirstPassHandler(Object, UInt32, StackFrameIterator&, UInt32&, Byte*&) + 0x188
   at System.Runtime.EH.DispatchEx(StackFrameIterator&, EH.ExInfo&) + 0x161
   at System.Runtime.EH.RhThrowEx(Object, EH.ExInfo&) + 0x4b
   at BringUpTest.Main() + 0xaf

Exception caught via filter!
Expected: 100
Actual: 3
END EXECUTION - FAILED
```
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=715849
Build error leg or test failing: nativeaot\\SmokeTests\\Exceptions\\Exceptions\\Exceptions.cmd
Pull request: https://github.com/dotnet/runtime/pull/103821

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Assertion failed: (n_heaps <= heap_number) || !gc_t_join.joined()",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[782793](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782793)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782793&view=ms.vss-test-web.build-test-results-tab&runId=20084754&resultId=100455)|dotnet/runtime#106713|
|[780945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=780945)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=780945&view=ms.vss-test-web.build-test-results-tab&runId=20026662&resultId=100455)|dotnet/runtime#106662|
|[779397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779397)|dotnet/runtime|[readytorun/GenericCycleDetection/Depth1Test/Depth1Test.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779397&view=ms.vss-test-web.build-test-results-tab&runId=19974514&resultId=107607)|dotnet/runtime#80154|
|[777119](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777119)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777119&view=ms.vss-test-web.build-test-results-tab&runId=19898356&resultId=100455)|dotnet/runtime#106474|
|[777004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777004)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777004&view=ms.vss-test-web.build-test-results-tab&runId=19894220&resultId=100455)|dotnet/runtime#106419|
|[776719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776719)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776719&view=ms.vss-test-web.build-test-results-tab&runId=19882940&resultId=100455)|dotnet/runtime#105946|
|[775455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775455)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775455&view=ms.vss-test-web.build-test-results-tab&runId=19839246&resultId=100455)|dotnet/runtime#106309|
|[770671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770671)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770671&view=ms.vss-test-web.build-test-results-tab&runId=19686388&resultId=100455)||
|[769702](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769702)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769702&view=ms.vss-test-web.build-test-results-tab&runId=19656152&resultId=100455)|dotnet/runtime#106130|
|[768094](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768094)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768094&view=ms.vss-test-web.build-test-results-tab&runId=19596962&resultId=100455)|dotnet/runtime#106010|
|[761651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761651)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761651&view=ms.vss-test-web.build-test-results-tab&runId=19350594&resultId=100453)|dotnet/runtime#105757|
|[757283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757283)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757283&view=ms.vss-test-web.build-test-results-tab&runId=19207850&resultId=100453)|dotnet/runtime#105578|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|4|12|

**Comment by jkotas** [comment]
Looks like a DATAs race condition. @dotnet/gc Could you please take a look?

Note that nativeaot\SmokeTests\Exceptions test is [explicitly opted into server GC](https://github.com/dotnet/runtime/blob/main/src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.csproj#L6) to get some coverage for server GC during default CI run.

**Comment by mrsharm** [comment]
Are there any dumps available? I can't seem to find them. Tried to repro locally to no avail. Seems like it's a low probability assertion failure (2 / month).

**Comment by MichalStrehovsky** [comment]
> Are there any dumps available? I can't seem to find them. Tried to repro locally to no avail. Seems like it's a low probability assertion failure (2 / month).

Yeah, it doesn't look like infra captured a dump for this.

There are 4 hits per month but we don't have any dedicated server GC testing. This is the one and only test we run with server GC enabled. We rely on CoreCLR testing to catch GC bugs right now (even this test is not really testing Server GC - it just tests that setting the csproj property to enable server GC actually enables the server GC).

**Comment by mangod9** [comment]
@mrsharm @MichalStrehovsky are any dumps available for this, or is there a local repro?

**Comment by mrsharm** [comment]
I couldn't locally repro this and nor could I get to any dumps. My one guess (by a long shot) is that this might be related to the other DATAS race condition we found via Reliability Framework where there is a race in the GetHeap while change_heap_count is invoked but without a dump it's difficult to validate.

**Comment by mangod9** [comment]
The reliability framework issue was fixed correct? Looks like this issue reproed today.

**Comment by mrsharm** [comment]
> The reliability framework issue was fixed correct? Looks like this issue reproed today.

It wasn't - I think we were still working on a solution. CC: @Maoni0.

**Comment by mangod9** [comment]
ah ok. We can tag it as such then, and see if the repro stops after that is fixed.

**Comment by Maoni0** [comment]
I made a fix at https://github.com/dotnet/runtime/pull/106752.

**Comment by mrsharm** [comment]
![image](https://github.com/user-attachments/assets/2283e055-183a-4a96-a75f-8832f8065aa0)

@cshung, we should wait some time before confirming this issue has truly fixed - I am observing that the bot is still picking up the same failures.

**Comment by cshung** [comment]
@mrsharm, wouldn't the bot reopen it if it finds new failures? I was hoping to confirm the fix by doing that.
