### ISSUE TITLE
Consider emitting unicode escape sequences for character ranges in the regex source generator

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/runtime#103840]
Given the following code, containing a regex with 2 non-ascii ranges (the actual ranges are not important, as long as they are not ASCII):

```csharp
[GeneratedRegex("[\u00C0-\u00FF\u0104-\u02D9]")]
private static partial Regex GetRegex();
```

The regex source generator outputs this:

![image](https://github.com/dotnet/runtime/assets/30874283/305c6af5-f5c8-4338-a98b-e25acade08b6)

This is actually `'\0'` and `'\u007F'`, but its impossible to tell from looking at the code, I had to open the file up in a hex editor to view what these characters actually were.

**Comment by danmoseley** [comment]
For the second one could you open a second issue?

**Comment by JakeYallop** [comment]
Raised #103842

**Comment by stephentoub** [comment]
Thanks. I have fixes for both.

**Comment by danmoseley** [comment]
@JakeYallop thanks again and please do open issues for any other regex generator oddities or perf opportunities.
