### ISSUE TITLE
Report a better error message when assembly version conflict is encountered

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#10387]
The simplest possible .NET Core 1.0 console application throws a `FileLoadException` with very little detail, when I try to load the netstandard1.0 build of System.Collections.Immutable.dll:

> Could not load file or assembly 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

If I update to .NET Core 2.0, it works, but it loads the assembly from a different path than the one I give it. And besides, in the original project, updating to .NET Core 2.0 creates other assembly load problems, so I'd prefer to learn why this doesn't work on .NET Core 1.0 and fix that issue.

Simplest repro project is linked below, but the C# code is simply this:

```csharp
AssemblyLoadContext.Default.LoadFromAssemblyPath(@"C:\Users\andarno\.nuget\packages\system.collections.immutable\1.4.0\lib\netstandard1.0\System.Collections.Immutable.dll");
```

[ConsoleApp20.zip](https://github.com/dotnet/coreclr/files/2042920/ConsoleApp20.zip)

**Comment by vitek-karas** [comment]
We didn't improve exception messages (yet), but we now have detailed tracing (similar to fusion logs in a way): https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/collect-details

Those should provide enough information to diagnose issues like this.
