### ISSUE TITLE
Performance: Potentially uneeded nullcheck for using?

### ISSUE THREAD

**Issue by Spacefish** [dotnet/runtime#103808]
If i have the following method:

```csharp
using var bla = new MyDisposable();
```

the following IL is generated by the compiler in Release mode with Optimizations on:
![image](https://github.com/dotnet/runtime/assets/375633/777cac65-a0b9-45d4-9727-843ad5d1db53)

Why the `brfalse.s` on offset 4?
As far as i understand `newobj` will either push a reference to the new object to the stack or throw an exception, but will never push a nullpointer onto the evaluation stack.

As bla is read-only (as its marked with using) (CS1656) and the reference is only present in the local scope, we should always be able to assume that´s it non-null, as it can´t be re-assigned. So the `brfalse.s` nullcheck shouldn´t be necessary.

Am i missing something here?

**Comment by colejohnson66** [comment]
You're correct that the null check is useless, but you have to remember that the compiler, even in Release mode, tends to not make optimizations about things like nullability; That's left to the JIT/runtime.

When JITed, the runtime detected that the null check is useless and removed it. It even went further  and inlined the entire `Dispose` method! If you look closely at the assembly, you can see the call to `Console.WriteLine(42)` on lines `L0014` and `L0019`.

https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQ64GYAEicDC6A3ujuXrnACw4CyAFAJRkWloWd4AMOAbmABOOAEYAbMDgC8OAHYBTAO70AngBEAlhAAOAewhhx85gG5W5AL7orGNNjwJVmnfsNj5OEDgCSzvQaMSc0o8Wj99YxYONmDOOCQATgZqBCYzaMtrIA==

```cs
using System;

public class C
{
    public void M()
    {
        using var bla = new MyDisposable();
    }
}

public class MyDisposable : IDisposable
{
    public void Dispose()
    {
        Console.WriteLine(42);
    }
}
```

```asm
; Core CLR 8.0.524.21615 on x86

C..ctor()
    L0000: ret

C.M()
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: sub esp, 0x14
    L0006: xor eax, eax
    L0008: mov [ebp-0x14], eax
    L000b: mov [ebp-0x10], eax
    L000e: mov [ebp-0xc], eax
    L0011: mov [ebp-8], eax
    L0014: mov ecx, 0x2a
    L0019: call dword ptr [0x12ad7198]
    L001f: mov esp, ebp
    L0021: pop ebp
    L0022: ret

MyDisposable..ctor()
    L0000: ret

MyDisposable.Dispose()
    L0000: mov ecx, 0x2a
    L0005: call dword ptr [0x12ad7198]
    L000b: ret
```

**Comment by EgorBo** [comment]
Closing as answered, thanks @colejohnson66 One note is that your jitted asm is x86, x64 is:
```asm
; Method C:M():this (FullOpts)
G_M22067_IG01:  ;; offset=0x0000
       sub      rsp, 40
						;; size=4 bbWeight=1 PerfScore 0.25

G_M22067_IG02:  ;; offset=0x0004
       mov      ecx, 42
       call     [System.Console:WriteLine(int)]
       nop      
						;; size=12 bbWeight=1 PerfScore 3.50

G_M22067_IG03:  ;; offset=0x0010
       add      rsp, 40
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25
; Total bytes of code: 21


```

If you think Roslyn could produce a more compact IL, feel free to file an issue in https://github.com/dotnet/roslyn
