### ISSUE TITLE
[API Proposal]: bool HashSet.Add(T, out T actualValue)

### ISSUE THREAD

**Issue by andrewjsaid** [dotnet/runtime#103885]
### Background and motivation

This API Proposal is an overload on the `HashSet<T>.Add` method. It is a combination of the existing `Add` and `TryGetValue`. 

Currently you would have to do the following to get the same functionality:
```csharp
IEnumerable<InboundRouteEntry> entries = ...
var seen = new HashSet<InboundRouteEntry>(new CustomComparer());
foreach (var entry in entries)
{
  if (seen.TryGetValue(entry, out var actualValue)
  {
    throw new Exception($"Ambiguous: {entry} and {actualValue}");
  }
  seen.Add(entry)
}
```
(inspired by https://github.com/dotnet/aspnetcore/pull/56415/files)

Besides being more ergonomic, the API will improve performance as it will reduce from two lookups (`Get` and `Add`) into 1.

Also for consideration is whether to add another overload for `HashSet<T>.AlternateLookup<TAlternate>.Add`.

### API Proposal

```diff
namespace System.Collections.Generic;

public class HashSet<T>
{
+ public bool Add(T item, out T actualValue)
}
```

### API Usage

```csharp
IEnumerable<InboundRouteEntry> entries = ...
var seen = new HashSet<InboundRouteEntry>(new CustomComparer());
foreach (var entry in entries)
{
  if (!seen.Add(entry, out var actualValue)
  {
    throw new Exception($"Ambiguous: {entry} and {actualValue}");
  }
}
```

**Comment by huoyaoyuan** [comment]
See also #21603

**Comment by andrewjsaid** [comment]
Hah, I made this proposal because `TryGetValue` exists - which is exactly what is being discussed in some of the comments in https://github.com/dotnet/runtime/issues/21603. That `TryGetValue` really does go against the idea of how @eiriktsarpalis describes this data structure in https://github.com/dotnet/runtime/issues/21603#issuecomment-2061168557.

FWIW if we see `HashSet` as a set, and `IEqualityComparer` as an equivalence relation then there's no theoretical reason to assume that partitioning the set should have exactly 1 element per partition.

Seeing as that discussion was so recent, I understand if this ticket is just closed.

**Comment by eiriktsarpalis** [comment]
> FWIW if we see `HashSet` as a set, and `IEqualityComparer` as an equivalence relation then there's no theoretical reason to assume that partitioning the set should have exactly 1 element per partition.

That is technically correct, however `HashSet<T>` as designed is better suited at answering the simple question of whether a particular equivalence class is represented within the set. If your domain requires further introspection then

1. This definition of equivalence is likely not appropriate for this type in the general case and
2. using a dictionary with a separate key type would be a preferable solution.
