### ISSUE TITLE
HttpClient spans don't show up as exemplars

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#103893]
### Description

I'm adding a [new exemplar feature](https://github.com/dotnet/aspire/pull/4629) to the Aspire dashboard. Basically, when a metric is recorded, in-progress spans are included as example data.

However, I never see the HttpClient span as an exemplar. Someone should investigate why and fix this.

I don't know exactly how this feature technically works. However, my _theory_ is the HttpClient span is ended before `http.client.request.duration` recorded, so the HttpClient activity isn't available for opentelemetry-sdk to associate with the metric. The order may need to be flipped: record `http.client.request.duration` and then stop the activity. I think it is a matter of making the metrics handler a child of the diagnostics handler [here](https://github.com/dotnet/runtime/blob/8b6acb2d9d2cd7ea24d309f9c51d9fbbfc4790dd/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L41-L45).

### Reproduction Steps

Capture OTEL data with metrics + exemplars enabled + make HTTP requests with HttpClient.

See https://github.com/dotnet/aspire/pull/4629 for an example.

### Expected behavior

HttpClient spans show update as exemplars.

### Actual behavior

HttpClient spans are never exemplars.

### Regression?

No

### Configuration

.NET 8

**Comment by JamesNK** [comment]
cc @reyang @noahfalk @tarekgh @samsp-msft

**Comment by JamesNK** [comment]
**Update:** I do see HttpClient spans show up as exemplars for some metrics: `dns.lookup.duration`, and `http.client.request.time_in_queue`.

For example, the points here are correctly HttpClient spans:
![image](https://github.com/dotnet/runtime/assets/303201/727e4c00-377c-45a2-9bb9-e04a832d2c02)

But HttpClient spans **don't** show up in `http.client.request.duration` (IMO, the most important one for them to be visible in). Only ASP.NET Core and gRPC spans are exemplars are visible.

**Comment by samsp-msft** [comment]
+ @CodeBlanch @cijothomas

**Comment by cijothomas** [comment]
> It seems like it is important to always end a duration metric before its associated activity so exemplars work. Is that correct

Yes. OTel's instrumentation library is reporting metric while Activity is still active, though that has [some hacky behavior](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerMetricsDiagnosticListener.cs#L89-L92) as it relies on activity duration, which is not normally available unless activity itself ends!

**Comment by CodeBlanch** [comment]
@JamesNK 

If you are doing...

```csharp
builder.SetExemplarFilter(ExemplarFilterType.TraceBased)
```

Then yes there will need to be an active trace (`Activity`) alive when the measurement is recorded to get an exemplar spit out.

There are other filters (and an envvar for histograms) you can use which will generate exemplars for all measurements but if there is no `Activity` they won't be linked to the trace you'll just get raw measurement + any tags that were filtered out.

**Comment by cijothomas** [comment]
I think the case here is - the HttpClient activity is ended, but the Asp.Net Core one is still active, so Exempalr will still link to the right traceid

**Comment by antonfirsov** [comment]
> The order may need to be flipped: record http.client.request.duration and then stop the activity. I think it is a matter of making the metrics handler a child of the diagnostics handler

@JamesNK would it make sense if I would send you a private build of `System.Net.Http` with this change so you can test if it helps before I move on opening a PR? If yes what version/branch should I base the change on?

**Comment by JamesNK** [comment]
Ok. Update to date main branch is fine.

**Comment by JamesNK** [comment]
To write a unit test for this I think you would assert in the `http.client.request.duration` value that the HTTP activity is present.

**Comment by antonfirsov** [comment]
@JamesNK built from the current main: [System.Net.Http-SwappedTelemetry.zip](https://github.com/user-attachments/files/16092411/System.Net.Http-SwappedTelemetry.zip), PTAL if it does the job!

Note that the [naive change](https://github.com/dotnet/runtime/compare/main...antonfirsov:enable-exemplars-01) breaks the ability of registering metrics enrichment callbacks on `System.Net.Http.HttpRequestOut.Stop` DaignosticSource events, unless we are willing to commit to a refactor that merges the two handlers so we can reorder things in complicated ways. I would prefer taking the breaking change instead, since I doubt there are many users doing enrichment together with DiagnosticListener. In fact, metrics enrichment seems to be a vastly unused feature. Thoughts?

It may also break other stuff, didn't have a chance yet to investigate the impact fully.

**Comment by JamesNK** [comment]
I don't think we should worry about it.

**Comment by JamesNK** [comment]
I couldn't test this with Aspire for reasons, so I wrote a test app that exports to console.

9.0 current (note: no exemplar):
![image](https://github.com/dotnet/runtime/assets/303201/119873b4-c248-47b7-aaed-e29185b5105c)

9.0 with custom System.Net.Http (note: has exemplar):
![image](https://github.com/dotnet/runtime/assets/303201/ad6d48e2-8e96-4622-8f16-082f81744c6c)
