### ISSUE TITLE
Could not load type 'System.Runtime.InteropServices.WindowsRuntime.IActivationFactory'

### ISSUE THREAD

**Issue by rub3r0id** [dotnet/runtime#103870]
### Description

I can build [project](https://github.com/rub3r0id/Test) for net8.0-windows10.0.19041.0

```c
namespace Test;
internal class Test
{
    public static void Main(string[] args)
    {
        var factory = System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.GetActivationFactory(typeof(Windows.Graphics.Capture.GraphicsCaptureItem));
    }
}
````

only in case of adding 

```xml
<PackageReference Include="System.Runtime.InteropServices.WindowsRuntime" Version="4.3.0" />
```

but at the runtime I get an exception

`
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.WindowsRuntime.IActivationFactory' from assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
`

### Reproduction Steps

1. Run dotnet build into Test.csproj folder
2. Run Test.exe

### Expected behavior

No exception

### Actual behavior

Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.WindowsRuntime.IActivationFactory' from assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### Known Workarounds

No workaround found

### Configuration

net8.0-windows10.0.19041.0
x64

### Other information

See code at the [test repository](https://github.com/rub3r0id/Test)
It can work at framework net472, for example
It has been found in the attempt to build a project based on [ScreenCapture](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/CaptureHelper.cs)

**Comment by AaronRobinsonMSFT** [comment]
The WinRT ecosystem is not longer built-in for .NET 5+. The [IActivationFactory](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.windowsruntime.iactivationfactory) interface being used marks support ending in .NET Core 3.1. Since .NET 5, the appropriate tooling can be found using the [CsWinRT](https://github.com/microsoft/CsWinRT) tool-chain.

**Comment by rub3r0id** [comment]
Thank you to point me to the right direction.
In my case it was replaced by 

`var interop = GraphicsCaptureItem.As<IGraphicsCaptureItemInterop>();`

[It has been described here](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#COM-Interop)
