### ISSUE TITLE
InvalidOperationException for nullable int in ConfigurationBinder source generator generated code

### ISSUE THREAD

**Issue by harrison314** [dotnet/runtime#103859]
### Description

The ConfigurationBinder source generator in the AOT template generates code that doesn’t consider the use of nullable value types like `int`, `long`, etc. As a result, binding fails with an `InvalidOperationException` because it tries to parse an empty string as an `int` in generated code.

`Microsoft.Extensions.Configuration.Binder.SourceGeneration` version `8.0.10.26715`

### Reproduction Steps

Configuration class:

```cs
public class LimitSetup
{
    public int? MaxCount { get; set; }
}
```

Binding in Program.cs (ASP web api AOT template):
```cs
builder.Services
    .AddOptions<LimitSetup>()
    .BindConfiguration("LimitSetup");
```

In _appsettings.json_:
```json
"LimitSetup": {
  "MaxCount": null
}
```

csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

</Project>
```

### Expected behavior

In options `LimitSetup.MaxCount` property is `null` value.

### Actual behavior

I get an exception when binding:

```
System.InvalidOperationException: 'Failed to convert configuration value at 'LimitSetup:MaxCount' to type 'System.Int32'.'
```

ConfigurationBinder source generator generate this code:

```cs
if (configuration["MaxCount"] is string value1)
{
    instance.MaxCount = ParseInt(value1, () => configuration.GetSection("MaxCount").Path);
}
```

Value `value1` is empty string if `MaxCount` is `null` in appsettings.json.

### Configuration

.NET 8 - ASP.NET Core Web API (Native AOT) template

**Comment by tarekgh** [comment]
The reflection binder successfully handles this case https://github.com/dotnet/runtime/blob/98e75704a85bfe4a71dd5932c8a2e5f860a09d05/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L879. We need to ensure the source generator handle that too.

**Comment by ericstj** [comment]
I see, so the runtime binder has special handling for nullable to deal with the empty string and treat it as null, but that's missing from the source generator.
