### ISSUE TITLE
[System.Threading.RateLimiting] Request Leaky Bucket rate limiter

### ISSUE THREAD

**Issue by Balder1840** [dotnet/runtime#103800]
When exploring System.Threading.RateLimiting, I can see `FixedWindowRateLimiter`, `SlidingWindowRateLimiter` and `TokenBucketRateLimiter`.
Any plan to introduce the rate limiter for leaky bucket as well?
Thanks.

**Comment by BrennanConroy** [comment]
Leaky Bucket is effectively the same as Token Bucket
https://wikipedia.org/wiki/Leaky_bucket#Comparison_with_the_token_bucket_algorithm

**Comment by Balder1840** [comment]
Thanks for the explanation
