### ISSUE TITLE
Is it safe to do this volatile++ operation in WebSocketBuffer?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#103907]
https://github.com/dotnet/runtime/blob/8d6e07d3683a0b5551e0c7c74d557ebf9904e2a8/src/libraries/System.Net.HttpListener/src/System/Net/Windows/WebSockets/WebSocketBuffer.cs#L346

It looks like this class tries to stick to atomic operations, but this operation seems like it could store the wrong values in the presence of multiple threads.

**Comment by CarnaViire** [comment]
Closing as answered above
