### ISSUE TITLE
[API Proposal]: Acquire those managed objects that cannot be recycled through the GC.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#103944]
### Background and motivation

Since the dotnet team introduced the ALC(AssemblyLoadContext) technical solution, I have been paying attention to this technology and using it in practical projects, but it often leads to the inability to uninstall ALC, and the memory occupation has been increasing. It is not that I did not handle the references well, but some frameworks or class libraries have retained my metadata references, resulting in the inability to uninstall ALC. I cannot ask about the reference details of each class library and framework one by one. I hope the dotnet official can provide a solution for me to achieve the complete uninstallation of ALC.
> If there is anything offensive, please let me know to correct it. 

### API Proposal

```csharp
namespace System.Collections.Generic;

public static class GC 
{
   public IEnumerable<UnRecycledObject> GetUnRecycledObjects(AssemblyLoadContext alc);
}

public class UnRecycledObject
{
      //The value of the object that cannot be recycled.
      public object Value;
      //The type of the object that cannot be recycled.
      public type Type;
      //object holder
      public IEnumerable<ObjectHolder> ReferenceHeldByObjects;
}

public  class ObjectHolder : UnRecycledObject{
      //The object value that holds the reference of the recycled object.
      public object Value;
      //The object type that holds the reference of the recycled object.
      public type Type;
       //The member name of the object that cannot be recycled in this reference.
      public string HoldingName;
}
```

> 

### API Usage

```csharp
//Main Program
public static class A{
    public static object Obj;
}
```

```csharp
//PluginB
public class B{}
```

```csharp
//Example
AssemblyLoadContext  alcB = new("ALC-B");

WeakReference weakReference = new WeakReference();
weakReference.Target = alcB ;

var assmblyB = alcB .Load("B.dll");
var typeB = assemblyB.GetType("B");
object b =  Activtor.CreateInstance(typeB);
A.Obj = b;

//Maybe waittig for a long time;
Task.Run(()=>{

  var uroObjs = GC.GetUnRecycledObjects(alcB);

  var firstURObj = uroObjs .First();
  firstURObj .Value == b;  //True
  firstURObj.Type.Name == "B";  //True

  var uroHolder = firstURObj.ReferenceHeldByObjects.First();
  uroHolder.Value == null;  //True
  uroHolder.Type.Name == "A";  //True
  uroHolder.HoldingName == "Obj"; //True

  //how to unload alcB 
  var field = uroHolder.Type.GetFiled/GetProperty(uroHolder.HoldingName);
  field.SetValue(null);
  uroObjs  = null;
  uroHolder = null;
});


GC.Collect();
weakReference.Target == null;//True
```

### Risks

1. This should be a acceptable : function with a long execution time.
2. There may exist circular references.
3. Generic and array objects may be difficult to handle.
4. More complex UnRecycledObject and ObjectHolder structures are required to record more information.

**Comment by huoyaoyuan** [comment]
This does not look actionable.

The first question is the representation of "ObjectHolder'. Using reflection is very heavy here. It can't cover every case either. In addition of field of heap object, a reference can also be an element of array, a field of struct that's on the stack, a local variable of another thread that's currently in register, or a leaked ObjectHandle held by CLR. *It can also be a executing method in an assembly of the ALC. What can happen if the method is the caller of current method?*

Doing a full heap scan is also very cost-ful. GC itself reduces pauses and overhead by optimistically scan required regions only. Populating a data structure about the information will increase the cost dramatically.

> ```cs
>   var field = uroHolder.Type.GetFiled/GetProperty(uroHolder.HoldingName);
>   field.SetValue(null);
> ```

It's certainly not acceptable to "free" the object reference in this way. It will change any invariant internally kept by a library and will results in more transitive inconsistency. It can also break thread safety.

> I cannot ask about the reference details of each class library and framework one by one.

This is something you must do.

As said above, there's no way to forcefully remove all references to an ALC. It's more suitable to be a feature of memory diagnostic tool.

**Comment by huoyaoyuan** [comment]
> Since the dotnet team introduced the ALC(AssemblyLoadContext) technical solution, I have been paying attention to this technology and using it in practical projects, but it often leads to the inability to uninstall ALC, and the memory occupation has been increasing.

I understand you desire and multiple requests to unload ALCs easily, but unfortunately there's no actionable solution. Forcefully modifying the heap will definitely results in crash of your process. Once you know how to avoid the crash, you are essentially knowing how to clean the references gracefully.

**Comment by huoyaoyuan** [comment]
> At the very beginning, this proposal could accept any "heavy", at least making the release of ALC become a possibility.

It's too heavy to be realistic and may result in OOM or infinite dead lock.
How can the scanning stop? What if other threads manipulating the heap concurrently? What about unmanaged structures like `RuntimeTypeHandle`?
The total over head can easily increase over restarting your process and reload all the data.

> Yes. It would be best to have an Action[], and the official actively promotes and publicizes it, allowing all class library developers to implement the uninstallation solution of their own class libraries here, which requires self-discipline and is difficult to achieve.

It's not as simple as such. A library need to deal carefully with **types from other assembly**.

For example, static types like `Newtonsoft.Json.JsonConvert` may cache `FieldInfo` and `PropertyInfo` about serialized type in static field. You can't really guarantee that nulling the cache won't cause crash in subsequent uses of the type.

**Comment by NMSAzulX** [comment]
> The basic tutorial is at https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak

Thank you very much!
