### ISSUE TITLE
[metadata] Move MonoClass:inlinearray_value out of MonoClass

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#103913]
inline arrays are quite infrequent.  We have the `is_inlinearray` bit on MonoClass for fast checks, but `inlinearray_value` doesn't really need to be on every single MonoClass.  We should move it to `MonoClass:infrequent_data`, or at least to `MonoClassDef` (since generic instances can't change a custom attribute value).

**Comment by DevPio** [comment]
You can assign this issue to me?

**Comment by syfFerdinand** [comment]
Hello everyone,
I'm interested in this issue and would like to work on it. Is anyone already on the case, or can I start investigating and propose a solution?

Thank you!

**Comment by syfFerdinand** [comment]
Hello everyone,

I just saw that @DevPio  expressed interest in working on this issue 5 hours ago. If needed, I'm also available and motivated to contribute. We can even collaborate if necessary.

Thank you very much!

**Comment by lambdageek** [comment]
@DevPio @syfFerdinand we generalliy don't assign issues to community contributors, but if you want to work on it, please open a PR when you have something.   If you'd like to discuss the issue, the .NET Discord server https://aka.ms/dotnet-discord has a #monovm channel for Mono-related chat
