### ISSUE TITLE
Expose Json in SqlDbType

### ISSUE THREAD

**Issue by saurabh500** [dotnet/runtime#103925]
### Background and motivation

The `System.Data.SqlDbType` enum represents the datatypes supported by SQL Server and is used with SqlParameter to specify the column type to be used in SQL server operations while execution `SqlCommand`.

With the JSON datatype being supported in SQL Server [link](https://learn.microsoft.com/en-us/sql/t-sql/data-types/json-data-type?view=azuresqldb-current) There is a need to support the JSON type in Microsoft.Data.SqlClient ADO.Net provider for SQL Server.

The API suggestion is aimed at adding an enum called `Json` with value `35` in `SqlDbType`. 
Once this enum is available Microsoft.Data.SqlClient (the SQL Server driver) can then leverage the enum value to allow JSON operations using Microsoft.Data.SqlClient APIs.

```C#

namespace System.Data
{
    // Specifies the SQL Server data type.
    public enum SqlDbType
    {
        Json = 35,
    }
}
```

The version of Microsoft.Data.SqlClient targeting .Net 9, will be able to use the enum `SqlDbType.Json` to provide JSON support.

### API Proposal

```C#

namespace System.Data
{
    // Specifies the SQL Server data type.
    public enum SqlDbType
    {
        Json = 35,
    }
}
```

### API Usage

```csharp
using Microsoft.Data.SqlClient;


SqlParameter param = new SqlParameter();

param.SqlDbType = System.Data.SqlDbType.Json;

```

There are parameters / properties in the constructors and APIs, which will be enhanced to support `SqlDbType.Json` 

`SqlParameter`
`SqlParameterCollection`
`SqlMetaData`

**Comment by saurabh500** [comment]
cc @roji  @uc-msft @David-Engel  @apoorvdeshmukh  @deepaksa1  @cheenamalhotra

**Comment by roji** [comment]
Thanks. Just noting that SqlDbType isn't actually referenced anywhere inside the runtime libraries, and @saurabh500 confirmed that previous versions of SqlClient are confirmed to throw on unknown SqlDbType values, so if a user attempts to use the new SqlDbType.Json with an older SqlClient, we should be safe there.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#

namespace System.Data
{
    // Specifies the SQL Server data type.
    public enum SqlDbType
    {
        Json = 35,
    }
}
```
