### ISSUE TITLE
AOT compiler should error out gracefully instead of crashing

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#103901]
### Description

AOT compiler crashes with invalid input.

The underlying cause for the failure is that the project file is adding references (using Reference items) to assemblies that reference assemblies that are not referenced. If the project used a ProjectReference or PackageReference, there would be a build warning or error complaining about something at some point when computing which assemblies to reference, but when using Reference items directly, the csproj author is responsible for getting it right.

The csproj author didn't get it right, and the set of assemblies to AOT compile isn't a coherent set of assemblies.

The bug is that the AOT compiler shouldn't crash when it encounters such invalid output, it should fail gracefully.

### Reproduction Steps

Test project: [aot-compiler-crash-deaab45.zip](https://github.com/user-attachments/files/15957860/aot-compiler-crash-deaab45.zip)

Build the project to reproduce:

```console
 dotnet build /p:RuntimeIdentifier=ios-arm64 -c Debug
```

### Expected behavior

An error message explaining what went wrong.

### Actual behavior

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 139.
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139.
```

### Regression?

Probably not.

### Known Workarounds

Don't make mistakes?

### Configuration

```
$ dotnet --info
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.3a2c5bc5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
 [maui-maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.21/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.21/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8473-ci.main/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8473-ci.main/WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8473-ci.main/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maccatalyst/17.2.8473-ci.main/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-preview.4.24266.19
  Architecture: arm64
  Commit:       d0d6fed6c0

.NET SDKs installed:
  7.0.311 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.104 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.3.24153.2 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24260.3 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24267.66 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.3.24151.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24260.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24129.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24260.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/rolf/test/dotnet/aot-compiler-crash/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by steveisok** [comment]
@rolfbjarne if you turn off dedup, does the same message occur?

**Comment by rolfbjarne** [comment]
> @rolfbjarne if you turn off dedup, does the same message occur?

There's only one crash instead of two:

> error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139.

In any case that's not the point: the point is that the AOT compiler shouldn't crash.

FWIW here's a crash report: https://gist.github.com/rolfbjarne/b51e918ebcc5fd71f72fb2f3de4a4cc0

**Comment by steveisok** [comment]
> In any case that's not the point: the point is that the AOT compiler shouldn't crash.

Agreed. I expected it to behave the same way and wanted to confirm.

**Comment by lambdageek** [comment]
I don't get a crash with the 8.0.6 runtime/SDK.

**Comment by lambdageek** [comment]
@rolfbjarne if you can repro, can you upload the binlog and the trimmed assemblies

**Comment by rolfbjarne** [comment]
Here's the entire project directory, with the bin/obj directories + an msbuild.binlog: https://www.dropbox.com/scl/fi/b9ignl8qsjk29llfdooqd/aot-compiler-crash-dotnet-runtime-issue-103901.zip?rlkey=awc1t3q8gxuxxikdk3lj40ny7&dl=0

**Comment by lambdageek** [comment]
Thanks @rolfbjarne , I realized the issue is I was doing a Release build.  but the issue repros when I do a device Debug build.  

It looks like one of the problems is the dedup assembly `aot-instances.dll` wants `Microsoft.Maui.dll` but it's not in the `linked` directory.  It looks like the linked `Microsoft.Maui.Controls.HotReload.Forms.dll` assembly has some references to it, but the linker didn't keep it.  Not sure how that happens.

**Comment by rolfbjarne** [comment]
> It looks like one of the problems is the dedup assembly `aot-instances.dll` wants `Microsoft.Maui.dll` but it's not in the `linked` directory. It looks like the linked `Microsoft.Maui.Controls.HotReload.Forms.dll` assembly has some references to it, but the linker didn't keep it. Not sure how that happens.

The underlying cause for the failure is that the project file is adding references (using `Reference` items) to assemblies that reference assemblies that are not referenced. If the project used a ProjectReference or PackageReference, there would be a build warning or error complaining about something at some point when computing which assemblies to reference, but when using `Reference` items directly, the csproj author is responsible for getting it right.

The csproj author didn't get it right, and the set of assemblies to AOT compile isn't a coherent set of assemblies.

The bug is that the AOT compiler shouldn't crash when it encounters such invalid output, it should fail gracefully.

**Comment by lambdageek** [comment]
> The underlying cause for the failure is [...] The bug is that the AOT compiler shouldn't crash when it encounters such invalid output, it should fail gracefully.

Thanks!
