### ISSUE TITLE
.NET 9 Preview 5 WebAssembly debugging broken

### ISSUE THREAD

**Issue by los93sol** [dotnet/runtime#103976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I spun up a Blazor Web App in Visual Studio 2022 Preview  using .NET 9 Preview 5, Authentication type: Individual Accounts, Configure HTTPS checked, Interactive render mode: Auto, Interactiviery location: Per page/component.

In this configuration breakpoints in counter.razor are not hit when running as webassembly.  The same configuration in 8.0.6 results in my breakpoints being hit.  Am I missing something?

### Expected Behavior

Breakpoints should hit as expected

### Steps To Reproduce

Set a breakpoint in IncrementCount on Counter.razor.  The first time it hits, now navigate to home and back and it will be running in WebAssembly and the break point will not hit anymore.

### .NET Version

.NET 9 Preview 5

**Comment by thaystg** [comment]
Which version of VS are you using?

**Comment by los93sol** [comment]
> Which version of VS are you using?

17.11.0 Preview 2.1

**Comment by thaystg** [comment]
This will be fixed in 17.11.0 Preview 3.0.
