### ISSUE TITLE
[Question] tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror Unix/CoreCLR skip

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#104095]
Test `tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror` was added to Unix/CoreCLR skips by https://github.com/dotnet/runtime/pull/81094 during discussion in https://github.com/dotnet/runtime/issues/80666. As says https://github.com/dotnet/runtime/issues/80666#issuecomment-1570970014 the issue was fixed by https://github.com/dotnet/runtime/pull/86180. Should eventsourceerror test still be in issues.targets?
https://github.com/dotnet/runtime/blob/2fc4bba579696e8e173f1b586c3abebeeed68f6d/src/tests/issues.targets#L90-L97

cc @jkotas @EgorBo @davmason @tommcdon

**Comment by t-mustafin** [comment]
cc @dotnet/samsung

**Comment by EgorBo** [comment]
Probably not, do you want to file a PR to enable it? 🙂

**Comment by jkotas** [comment]
Fixed by #104099
