### ISSUE TITLE
[Duplicate] Microsoft.Extensions.Configuration.Configuration Binder.BindArray() binding adding to the initialized Collections, not replacing

### ISSUE THREAD

**Issue by Kkamikadzee** [dotnet/runtime#104085]
### Description

It is not possible to set default values for configurations containing a collection.

This issue is duplicate to the #46988. I apologize for create it, but the original issue has been closed and  has not workarounds. I am still trying to figure out what plans are for addressing this issue.
[dotnet/runtime/v8.0.6/BinderOptions.cs](https://github.com/dotnet/runtime/blob/v8.0.6/src/libraries/Microsoft.Extensions.Configuration.Binder/src/BinderOptions.cs)

### Reproduction Steps

```csharp
using Microsoft.Extensions.Configuration;

ConfigurationBuilder builder = new();
builder.AddInMemoryCollection([KeyValuePair.Create("Values:0", "10")!,KeyValuePair.Create("Values:1", "11")!,]);
IConfiguration configuration = builder.Build();

FooOptions options = configuration.Get<FooOptions>()!;
Console.WriteLine(options);

internal sealed class FooOptions
{
    public IReadOnlyList<int> Values { get; set; } = [0, 1,];

    public override string ToString()
    {
        return $"Values: {string.Join(", ", Values)}";
    }
}
```

### Expected behavior

Program output: `Values: 10, 11`

### Actual behavior

Program output: `Values: 0, 1, 10, 11`

### Known Workarounds

```csharp
using System.Collections.Immutable;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

ConfigurationBuilder builder = new();
builder.AddInMemoryCollection([KeyValuePair.Create("Values:0", "10")!,KeyValuePair.Create("Values:1", "11")!,]);
IConfiguration configuration = builder.Build();

ServiceCollection serviceCollection = new();
serviceCollection.AddOptions<FooOptions>().Bind(configuration, binderOptions => binderOptions.BindNonPublicProperties = true);
IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();

FooOptions options = serviceProvider.GetRequiredService<IOptions<FooOptions>>().Value;
Console.WriteLine(options);

internal sealed class FooOptions
{
    private static readonly IImmutableList<int> DefaultValues = [0, 1];

    [ConfigurationKeyName("Values")]
    private IReadOnlyList<int>? HideValues { get; set; } = [];

    public IReadOnlyList<int> Values => HideValues?.Count > 0 ? HideValues : DefaultValues;
    public IReadOnlyList<int> SetValues(IReadOnlyList<int> value) => HideValues = value;

    public override string ToString()
    {
        return $"Values: {string.Join(", ", Values)}";
    }
}
```

You can use a private property with a value from the configuration, and the value is provided through a public property that does not have a setter, because otherwise the binder will assign a value. There is no way to ignore the property, as there is no attribute available for this purpose (issue #58384 ).

Unfortunately, you cannot use the `configuration.Get<FooOptions>(binderOptions => binderOptions.BindNonPublicProperties = true)` method to retrieve an object, as it will return null instead of an object with default values.

### Configuration

.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.302/

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       63d80966a9

.NET SDKs installed:
  8.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Packages:
Microsoft.Extensions.Configuration: 8.0.0
Microsoft.Extensions.Configuration.Binder: 8.0.1

**Comment by julealgon** [comment]
Using a `ReadOnlyCollection` with an options class seems.... very unintuitive to me. Options are supposed to allow mutation by multiple configuration steps (binding, configure calls, `IConfigureOptions` implementations, etc). I just don't understand why one would design an options class that is actively _not_ mutable like that.

I'd suggest using a normal collection without a setter instead:
```csharp
internal sealed class FooOptions
{
    public ICollection<int> Values { get; } = [0, 1];
}
```

And if you want to ignore/overwrite the defaults at any point in configuration, just make that explicit:
```csharp
services.Configure<FooOptions>(o => o.Values.Clear());

// .. perform extra bindings/configure calls here
```

**Comment by tarekgh** [comment]
@julealgon solution will work. If you are really need to keep the property using read-only list, you may consider implmenting your options as follow:

```C#
    internal sealed class FooOptions
    {
        private IReadOnlyList<int> _values = new List<int> { 0, 1 };

        public IReadOnlyList<int> Values
        {
            get => _values;
            set
            {
                if (value is null)
                    throw new ArgumentNullException(nameof(value));

                _values = StartsWith(value, _values) ? new ReadOnlyCollection<int>(value.Skip(_values.Count).ToList()) : value;
            }
        }

        private static bool StartsWith(IReadOnlyList<int> source, IReadOnlyList<int> prefix)
        {
            if (source.Count < prefix.Count)
            {
                return false;
            }

            for (int i = 0; i < prefix.Count; i++)
            {
                if (source[i] != prefix[i])
                    return false;
            }

            return true;
        }

        public override string ToString()
        {
            return $"Values: {string.Join(", ", Values)}";
        }
    }
```

**Comment by tarekgh** [comment]
@Kkamikadzee I am closing the issue, feel free to respond back if you still have any questions we can help with. Thanks!

**Comment by Kkamikadzee** [comment]
@julealgon
> Using a `IReadOnlyList` with an options class seems.... very unintuitive to me. Options are supposed to allow mutation by multiple configuration steps (binding, configure calls, `IConfigureOptions` implementations, etc). I just don't understand why one would design an options class that is actively _not_ mutable like that.

The use of IReadOnlyList has been given as an example. Even if you replace IReadOnlyList with ICollection in my example, the basic idea will remain the same. The default values will not be overwritten by the values from the configuration.

I'm sorry, I don't understand how using `services.Configure(o => o.Values.Clear())` would help me with the default configuration values. It would always overwrite the field contents, so I'm not sure why I would need to specify them during initialization.

But as an alternative, you could use another workaround.

```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

ConfigurationBuilder builder = new();
builder.AddInMemoryCollection([KeyValuePair.Create("Values:0", "10")!,KeyValuePair.Create("Values:1", "11")!,]);
IConfiguration configuration = builder.Build();

ServiceCollection serviceCollection = new();
serviceCollection.AddOptions<FooOptions>().Bind(configuration)
    .Configure(fooOptions => fooOptions.Values = fooOptions.Values is null ? [0, 1,] : fooOptions.Values);
IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();

FooOptions options = serviceProvider.GetRequiredService<IOptions<FooOptions>>().Value;
Console.WriteLine(options);

internal sealed class FooOptions
{
    public ICollection<int> Values { get; set; } = null!;

    public override string ToString()
    {
        return $"Values: {string.Join(", ", Values)}";
    }
}
```

However, if the default values are moved from initialization to the code that adds the configuration to the DI, it may lead to confusion and potential problems in the future. The default values will be mixed in with the rest of the code, making it difficult to maintain and support the project.
And empty initialization and null checking, if you use nullable reference types, will cause warnings in IDE. Of course, these warnings can be suppressed. However, the problem of smearing values by default still gives me concern.
