### ISSUE TITLE
[API Proposal]: System.Text.Json.Serialization.JsonPropertyNameAttribute should be applicable to primary constructor arguments of record classes.

### ISSUE THREAD

**Issue by Kile-Asmussen** [dotnet/runtime#104019]
### Background and motivation

Problem: System.Text.Json.Serialization.JsonPropertyNameAttribute cannot be applied to a primary constructor agument of a record class. Instead to apply the `JsonPropertyNameAttribute` the record must be expanded to not use an explicit constructor which is over 3x as many lines of code.

Motivation: Newtonsoft.JSON supports this functionality with their analogous attribute `JsonPropertyAttribute`.

### API Proposal

```csharp
namespace System.Text.Json.Serialization
{
    /// <summary>
    /// Specifies the property name that is present in the JSON when serializing and deserializing.
    /// This overrides any naming policy specified by <see cref="JsonNamingPolicy"/>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    public sealed class JsonPropertyNameAttribute : JsonAttribute
    {
        /// <summary>
        /// Initializes a new instance of <see cref="JsonPropertyNameAttribute"/> with the specified property name.
        /// </summary>
        /// <param name="name">The name of the property.</param>
        public JsonPropertyNameAttribute(string name)
        {
            Name = name;
        }

        /// <summary>
        /// The name of the property.
        /// </summary>
        public string Name { get; }
    }
}
```

### API Usage

```csharp
public record MyRecord([JsonPropertyName("alternateName")] string NamedProperty);
```

instead of 

```csharp
public record MyRecord {
  [JsonPropertyName("alternateName")] public string NamedProperty { get; }
  public MyRecord(string NamedProperty) => this.NamedProperty = NamedProperty;
  public Deconstruct(out string NamedProperty) => NamedProperty = this.NamedProperty;
}
```

### Alternative Designs

Leave as is, let people deal with not being able to use primary constructors.

### Risks

Will recquire some changes to the Json (de)serialization code to also look for properties of constructor arguments, which might have negative performance impacts.

**Comment by imb591** [comment]
You can apply an attribute to a property of a record using [attribute target syntax](https://github.com/dotnet/csharplang/blob/4ed4090c05fe5f0d66c5766bc24749f4b16eda42/proposals/csharp-9.0/records.md#properties):
```c#
public record MyRecord([property: JsonPropertyName("alternateName")] string NamedProperty);
```

**Comment by Kile-Asmussen** [comment]
Solved.
