### ISSUE TITLE
runtime-coreclr outerloop pipeline cannot be started

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#104059]
I've tried to start it numerous times today. I have then found that it has been down for other folks too. There is some misconfiguration of the pipelines, see the errors here:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=721075&view=results

It says:
* The 'stages' parameter is not a valid StageList.
* /eng/pipelines/common/xplat-setup.yml: Could not find /eng/pipelines/coreclr/templates/format-job.yml in repository self hosted on https://github.com/ using commit b043c3685b4f6c978ce1208a32f08e55ec834988. GitHub reported the error, "Not Found"

**Comment by janvorli** [comment]
cc @jkoritzinsky - it seems your recent PR #103846 has broken it

**Comment by jakobbotsch** [comment]
It should have been fixed by #103979

**Comment by janvorli** [comment]
Thanks @jakobbotsch, it works again now.
