### ISSUE TITLE
runtime-coreclr gcstress0x3-gcstress0xc has been failing for the past month

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#104062]
I can see that the last successful run was on April 30. There were no runs in May and the first failed run was on June 1. The failures are timeouts.

I've debugged it locally. The failures are due to `GC.WaitForPendingFinalizers` call and a finalizer that generates another right-away finalizable object. So the `GC.WaitForPendingFinalizers` never returns and the test hangs.

**Comment by AndyAyersMS** [comment]
Possibly related: #104057 -- though as best I can tell it just started timing out recently

**Comment by janvorli** [comment]
Fixed by #10373
