### ISSUE TITLE
Fail to link assemblies

### ISSUE THREAD

**Issue by perco754** [dotnet/runtime#1040]
Hello, today I tried to add System.Text.Json through Nuget to my Xamarin Forms .net standard 2.0 x-platform app. My iOS project fails to link to my shared assemblies. VS 2019, latest version, Xam Forms latest version. 
Any ideas appreciated!

**Comment by layomia** [comment]
We need to test and make System.Text.Json work on Xamarin iOS/Android. See related: https://github.com/dotnet/runtime/issues/31326.

**Comment by ahsonkhan** [comment]
cc @marek-safar, @MichalStrehovsky - if you have any thoughts or insights on this.

**Comment by marek-safar** [comment]
The problem has been well described in https://github.com/dotnet/runtime/issues/31326#issuecomment-548456030. The assembly is not linker friendly.
