### ISSUE TITLE
_statusCode of System.Diagnostics.Activity was set to be ActivityStatusCode.Ok explicitly, but somehow got modified to be ActivityStatusCode.Error

### ISSUE THREAD

**Issue by lukezgu** [dotnet/runtime#104068]
### Description

we have a method that has the following lines:

```
using var activity = _activitySource?.StartActivity("ActionName"); 
await Processing().ConfigureAwait(false); 
activity?.SetStatus(ActivityStatusCode.Ok);
```

here we explicitly set the status of this activity to be Ok, and this is the only place that we ever set the status of this activity object, and for the line 

`await Processing().ConfigureAwait(false);`

we have try-catch in this method, so we are not expecting it to throw any exception.

But, from logs we see that sometimes the Status of this object could be ActivityStatusCode.Error. 

Is there some way that the activity might listen to some events so that its status could be modified in some way? I checked the source code of System.Diagnostics.Activity but didn't see any such logic. 

### Reproduction Steps

I don't have steps to reproduce the issue, just wondering if it's designed like this and if there is any way that we can disable this feature, i.e. make the Status of Activity only accepted values that are explicitly passed in. 

### Expected behavior

When we set the value of Status, the value will not be changed.

### Actual behavior

The value of Status was set to be ActivityStatusCode.Ok, but it changed to be ActivityStatusCode.Error

**Comment by tarekgh** [comment]
This is most likely someone else called `activity?.SetStatus(ActivityStatusCode.Error, ...);` after your call to `activity?.SetStatus(ActivityStatusCode.Ok);`. Try to see if there is any `StatusDescription` that may give you a clue. Note, the Activity object can travel through async operations and execute code you may not own which set the status. 

We cannot tell exactly who setting the status without a repro code. I am closing the issue but feel free to respond back if you still have any other questions.
