### ISSUE TITLE
System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions?) throws an undocument ArgumentException

### ISSUE THREAD

**Issue by ravudet** [dotnet/runtime#104168]
### Description

The `System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions?)` overload is documented to only throw `NotSupportedException`, however it throws an `ArgumentException` if the serialized object has a string property that is too long.

### Reproduction Steps

```
private sealed class Foo
{
    public string? Bar { get; set; }
}

[TestMethod]
public void Test()
{
    var foo = new Foo() { Bar = new string(' ', 0x3FFFFFDF) };
    var serialized = JsonSerializer.Serialize(foo);
}
```

### Expected behavior

I believe there are several possible expected behaviors:
1. Simply document the `ArgumentException` that is throw here
2. Given the amount of "work" that the `Serialize` method does prior to this exception, I think it's a bit disingenuous to consider this an `ArgumentException`. I think that an `InvalidOperationException` is likely more appropriate. 
3. Ultimately, I don't think that the JSON standard has a maximum length on string properties. Given that .NET *does* have a maximum string length, and this overload returns a string, there *will* be some limit hit at some point, but the limit in the `Serialize` method is significantly smaller than the .NET limit. As a result, I believe that this is an artificial limit. Ideally, I would say that the best behavior would be:
    1. `Serialize` method should only throw if the resulting `string` exceeds the .NET string length thing
    2. `Serialize` should simply preserve the existing string `OutOfMemoryException`
    3. This `OutOfMemoryException` should be documented as a possible exception thrown by the `Serialize` method

### Actual behavior

An `ArgumentException` is thrown:

> The JSON value of length 1073741791 is too large and not supported.
> 
> Stack Trace: 
> ThrowHelper.ThrowArgumentException_ValueTooLarge(Int32 tokenLength)
> Utf8JsonWriter.WriteStringValue(ReadOnlySpan`1 value)
> JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
> JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
> ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
> JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
> JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
> JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
> JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
> JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)

**Comment by eiriktsarpalis** [comment]
It is not feasible for the `JsonSerializer` methods to document every possible exception that they might throw. This is because the methods are generic and plug into arbitrary converters which might be user defined. In this case, the error you are experiencing is due to https://github.com/dotnet/runtime/issues/67337#issuecomment-2196630108
