### ISSUE TITLE
System.Text.Json generated serialization code should follow performance best practices

### ISSUE THREAD

**Issue by nschuessler** [dotnet/runtime#104169]
### Description

We have written a Roslyn analyzer to check for best practices when concatenating strings. In particular `string.Format` should be replaced with `string.Concat` when there are 4 or fewer arguments.

The analyzer is causing a build break on generated code from `System.Text.Json` We are following up how to suppress the warning for generated code in another issue because nothing seems to work apart from disabling the analyzer (rule) from the entire project.

However, it would be nice if the generated code for improving performance used `string.Concat`.

Granted, it is an error code path (exception message string) and probably doesn't affect performance in the strict sense. However, it's like having someone smoking a cigarette tell you that it's not healthy to smoke.  People will observe the example you are setting, not what you are saying.

It is very difficult for an analyzer to exclude error code paths for all possible combinations of code that could be written.  i.e.:

```csharp
bool IsErrorCodePath(MethodInvocationExpressionSyntax stringFormatInvocation)
{
     // How on earth can I scan all combinations here to avoid the problem.
     return false;
}
```

A small change in the code generation would be appreciated.

Here is the generated code:
```csharp
      private static global::System.Text.Json.Serialization.JsonConverter ExpandConverter(global::System.Type type, global::System.Text.Json.Serialization.JsonConverter converter, global::System.Text.Json.JsonSerializerOptions options, bool validateCanConvert = true)
      {
          if (validateCanConvert && !converter.CanConvert(type))
          {
              throw new global::System.InvalidOperationException(string.Format("The converter '{0}' is not compatible with the type '{1}'.", converter.GetType(), type));
          }
      
          if (converter is global::System.Text.Json.Serialization.JsonConverterFactory factory)
          {
              converter = factory.CreateConverter(type, options);
              if (converter is null || converter is global::System.Text.Json.Serialization.JsonConverterFactory)
              {
                  throw new global::System.InvalidOperationException(string.Format("The converter '{0}' cannot return null or a JsonConverterFactory instance.", factory.GetType()));
              }
          }
      
          return converter;
      }
```

### Configuration

N/A

### Regression?

N/A

### Data

N/A

### Analysis

N/A

**Comment by huoyaoyuan** [comment]
But generally, analyzers should not run on generated code. As you describe, pattern violations in generated code are not easy to fix, and there can be conflict and disagreement from different analyzers.

**Comment by eiriktsarpalis** [comment]
> In particular string.Format should be replaced with string.Concat when there are 4 or fewer arguments.

It's not something we would be able to do in this case, primarily because it would interfere with how we resource error messages in the repo. As you're pointing, this is throwing exceptions in a method that isn't in the hot path.

To your wider point though, we're contemplating possible solutions in how source generators interact with warnings and analyzers. This is tracked by https://github.com/dotnet/runtime/issues/101738
