### ISSUE TITLE
Add bucket size hints to histograms

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#104137]
Histogram bucket annotations were added with https://github.com/dotnet/runtime/issues/63650. But they need to used with histograms that are published.

All `dotnet/runtime` histograms use seconds so they should have an annotation to provide good bucket boundaries.

`CreateHistogram<double>()` usages: https://github.com/search?q=repo%3Adotnet%2Fruntime%20CreateHistogram&type=code. Looks like they're currently all networking related.

dotnet/aspnetcore doing the same thing: https://github.com/dotnet/aspnetcore/pull/56500

This is easy to do and should be done in .NET 9. It allows opentelemetry-dotnet to remove [a hack to infer the bucket sizes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/978b461771c742ddc11e3c590fe52715af253450/src/OpenTelemetry/Metrics/Metric.cs#L21-L33). They can replace that code with code that looks at the attached bucket sizes.

**Comment by JamesNK** [comment]
cc @noahfalk @tarekgh

**Comment by karelz** [comment]
Triage: This will help remove hack in OTel. If it is really simple, we should do it. Discussed with @JamesNK.
FYI: @antonfirsov cc @CarnaViire
