### ISSUE TITLE
Thread.abort obselete and blocking inner calls, no way to abort the blocking call

### ISSUE THREAD

**Issue by progsen** [dotnet/runtime#104147]
### Description

When working with the Thread class:
I make a thread which handles Tcp connections and the thread process has a blocking call (acceptsocket)
that funciton does NOT support cancelation tokens 

then i cannot stop the thread anymore, unless i kill the program

example:
https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.acceptsocket?view=net-8.0

### Reproduction Steps

 static void Main(string[] args)
 {
     Console.WriteLine("Hello, World!");
     CancellationTokenSource source = new CancellationTokenSource();

     Thread start = new Thread(() =>
     {
         Console.WriteLine(DateTime.Now);
         TcpListener tcpListener = new TcpListener(8435);
         tcpListener.Start();
         tcpListener.AcceptSocket();//does not accept a cancellation token

         Console.WriteLine(DateTime.Now);

     });

     start.Start();
     source.Cancel();// won't do anything because unsupported by TcpListener.AcceptSocket
     //start.Abort();// does not work
 Console.ReadLine();

### Expected behavior

thread.abort work as in previous iterations
OR 
all blocking calls support cancellationtokens

### Actual behavior

inner thread cannot be stopped anymore without killing the program

**Comment by progsen** [comment]
trying to solve it with task:

Task t=Task.Run(() => {

    Console.WriteLine(DateTime.Now);
    TcpListener tcpListener = new TcpListener(8435);
    tcpListener.Start();
    tcpListener.AcceptSocket();//does not accept a cancellation token

    Console.WriteLine(DateTime.Now);
},source.Token);
Console.ReadLine();
Console.WriteLine("cancelling"+DateTime.Now);
source.Cancel();//doens't cancel the task
while (t.Status != TaskStatus.Canceled)
{
    //task stays in run mode!
    Console.WriteLine(t.Status + " " + source.Token.IsCancellationRequested);
}
Console.WriteLine(t.Status);
Console.ReadLine();

same issue

**Comment by DL444** [comment]
Why not `AcceptSocketAsync`? It's non-blocking, supports cooperative cancellation, and can be more scalable than its synchronous counterpart.

**Comment by progsen** [comment]
That sounds like an option.
Might still be worth looking into if all blocking calls have an async variant or no

**Comment by DL444** [comment]
Maybe irrelevant to this specific case, but do note that calling `Thead.Abort()` to arbitrarily kill threads is usually not a good idea, since it might leave the application in an inconsistent state (half-done data structure updates, half-written files, etc.). That's why we have cooperative cancellation (`CancellationToken`) so participating code can stop and cancel out gracefully.

**Comment by jkotas** [comment]
> Might still be worth looking into if, all blocking calls that are commonly used in threads, have an async variant or no, or to add cancellation token support to the non async versions

We add these overloads as we add them. You will find number of issues like https://github.com/dotnet/runtime/issues/921 . If you run into a commonly used API that we have missed, feel free to open a new issue on it.
