### ISSUE TITLE
Add NET 8.0 target to Microsoft.Bcl.Memory package

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#104185]
### Description

.NET 9.0 introduced `Base64Url`, and we are providing a polyfill for this type in `Microsoft.Bcl.Memory` to enable its use in earlier versions of .NET. The `Base64Url` implementation in .NET 9.0 leverages vectorization for improved performance. However, the polyfill implementation does not use vectorization, as it is not available in older framework versions. Although vectorization is possible in .NET 8.0, `Microsoft.Bcl.Memory` does not currently target .NET 8.0 specifically. When using `Microsoft.Bcl.Memory` on .NET 8.0, the polyfill implementation without vectorization is used. This issue tracks the addition of a .NET 8.0 target to `Microsoft.Bcl.Memory`, which will enable vectorization as well.

A quick test indicates that the current implementation, which uses vectorization, relies on the internal members of the public `Ascii` class: `VectorContainsNonAsciiChar`, `ExtractAsciiVector`, `StoreVectorAndZip`, `Load4xVector128AndUnzip`, and `ShuffleUnsafe`. These members need to be refactored to enable their use when targeting .NET 8.0.

### Reproduction Steps

Run any test app on .NET 8.0 with referencing `Microsoft.Bcl.Memory`.

### Expected behavior

Vectorization should be used

### Actual behavior

No Vectorization is used

### Regression?

No

### Known Workarounds

Target .NET 9.0 instead.

### Configuration

.NET 8.0

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by julealgon** [comment]
> .NET 9.0 introduced `Base64Url`

@tarekgh would you mind providing a link or some minimal information about this new type? Tried searching for it on the docs page but it doesn't seem to be there yet. I see one type with that name but its in an Azure namespace:
- [Microsoft.Azure.Commands.Attestation.Models.Base64Url](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.attestation.models.base64url?view=az-ps-latest)

**Comment by tarekgh** [comment]
@julealgon This is a brand new type, and the documentation has not yet been ported to the public portal. You can refer to the in-code documentation available at [Base64Url documentation in the code](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Base64Url). The triple-slash comments there will be the ones eventually ported to the public documentation.

CC @buyaa-n

**Comment by ericstj** [comment]
So there's a bit of a cost/benefit analysis to consider here.  The current netstandard implementation works on `net8.0` but could be benefit if it used vectorization.  Sounds like using vectorization will require some refactoring of the code and potentially maintaining a separate copy - so that's a cost here. @buyaa-n can you review this request and discuss with stakeholders and decide if it's work the cost to improve the implementation on `net8.0`?
