### ISSUE TITLE
Does anyone know what was accomplished in comment https://github.com/dotnet/core/issues/7556#issuecomment-1786377918

### ISSUE THREAD

**Issue by Sin-Shadow-Fox** [dotnet/runtime#104186]
Does anyone know what they're talking about or what these C++ runtimes are?

https://github.com/dotnet/core/issues/7556#issuecomment-1786377918

**Comment by danmoseley** [comment]
@agocke

**Comment by Sin-Shadow-Fox** [comment]
> @Sin-Shadow-Fox, there's some explanation at [Microsoft Visual C++ Redistributable latest supported downloads](https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist). The page says "Many applications built using Microsoft C and C++ tools require these libraries"; the .NET Runtime is built for Windows using those tools.

While I get what your saying, I don't understand how that explains the comment I linked to. It sounds like someone managed to get .net 8 to run on windows 7 and I'd really like to figure out how.

**Comment by Sin-Shadow-Fox** [comment]
> The comment says
> 
> > I can use .NET 7 event maybe .NET 8 on windows 7
> 
> and the screen shot shows only .NET 7 on Windows 7, so I'm not sure they managed to run .NET 8 on Windows 7.

Neither am I but I can't exactly ask either of them how things went as dotnet locked that whole thread and limited conversation to collaborators and I don't have the permission to re-open it.

**Comment by jkotas** [comment]
.NET 8 is **unsupported** on Windows 7.

.NET 8 is not actively blocked from running on Windows 7. Some .NET 8 apps will run on Windows 7, some .NET 8 apps are not going to run. YMMV.

**Comment by Sin-Shadow-Fox** [comment]
> .NET 8 is **unsupported** on Windows 7.
> 
> .NET 8 is not actively blocked from running on Windows 7. Some .NET 8 apps will run on Windows 7, some .NET 8 apps are not going to run. YMMV.

Well I'm not asking if .NET 8 is supported on windows 7.
I'm asking for help understanding what the people in the comment i linked to are talking about because it sounds like they got .NET 8 working on windows 7.

**Comment by Sin-Shadow-Fox** [comment]
P.S. request to un-close my issue as my question wasn't answered yet.

**Comment by jkotas** [comment]
> I'm asking for help understanding what the people in the comment i linked to are talking about because it sounds like they got .NET 8 working on windows 7.

Yes, they got it working for their app by installing the vc_redist. The comment is very clear about that.

I tried to explain why it may not be sufficient for the app that you are trying to run.

> P.S. request to un-close my issue as my question wasn't answered yet.

I am going to convert this to a discussion.
