### ISSUE TITLE
System.FieldAccessException: Cannot set initonly static field

### ISSUE THREAD

**Issue by LunarWhisper** [dotnet/runtime#104242]
### Description

The original issue:
https://github.com/dotnet/runtime/issues/11571
https://github.com/dotnet/standard/issues/1598

We faced the same issue when migrating from .NET Framework to .NET8.

Sorry, but this is a **regression bug**. I kindly ask you to provide the ability to disable optimizations and return the previous behavior to the ability to override static initonly fields.

You can provide any alternative, even a config for the built-in detours, but we need such an opportunity while .NET and third-party libraries use static initonly fields and properties.

Use cases:

1. Overriding the default behavior of .NET and 3rd-party types built around the use of static APIs such as ThreaPool. For example, we use this to impose an end-to-end limit on how many Parallel.ForEachs can run at the same time. At any time, you can carry out a refactoring that will make the readonly field we need and this technique will stop working.

2. Mock dependencies in tests. For example, we use a third-party library that provides an interface for interacting with DNS via a singleton. In tests, we need to replace the value of a static field.

### Reproduction Steps

```csharp
using System.Reflection;

typeof(Singleton)
    .GetField("<Value>k__BackingField", BindingFlags.Static | BindingFlags.NonPublic)
    .SetValue(obj: null, value: 2); // System.FieldAccessException: Cannot set initonly static field '<Value>k__BackingField' after type 'Singleton' is initialized.
    
public static class Singleton
{
    public static int Value { get; } = 1;
}
```

### Expected behavior

The value is set correctly without errors.

### Actual behavior

System.FieldAccessException: Cannot set initonly static field '<Value>k__BackingField' after type 'Singleton' is initialized.

### Regression?

Yes. It worked fine in the .NET Framework

### Known Workarounds

There are no known workarounds because, based on the discussion in the linked issues, changing static fields after type initialization can lead to broken behavior due to optimizations already applied.

### Configuration

.NET8

### Other information

We kindly ask you to take the community's requests as seriously as possible. This "optimization" broke many packages and solutions. It comes out at the moment when the enterprise migrates from the old .NET Framework to the new .NET.

I am not asking you to roll back these changes (although I do ask you to analyze whether they are really needed).

But please provide a CONVENIENT option to disable them at the solution / build configuration level.

**Comment by colejohnson66** [comment]
IIRC, modifying the backing field of init-only properties has *never* been defined behavior. Reflection always has the possibility to break things, and what you are doing was unsupported. So it broke when you upgraded.

**Comment by huoyaoyuan** [comment]
> 1. Overriding the default behavior of .NET and 3rd-party types built around the use of static APIs such as ThreaPool. For example, we use this to impose an end-to-end limit on how many Parallel.ForEachs can run at the same time.

This is unsupported case. Many internal code are implying the immutability of static readonly fields and behave depend on them.
The supported mechanism to tweak behavior of BCL apis is using AppContext switches.

> 1. At any time, you can carry out a refactoring that will make the readonly field we need and this technique will stop working.

Private fields can be refactored away in any versions. There's strictly no guarantee that reflection on them can work across versions.



> But please provide a CONVENIENT option to disable them at the solution / build configuration level.

It's hard to be convenient. The behavior has been employed by different components, including the JIT.

**Comment by hez2010** [comment]
At this time you can use `UnsafeAccessor` instead, while it requires non-static classes though:

```cs
using System.Reflection;

UnsafeAccessors.GetValueRef(new Singleton()) = 2;
Console.WriteLine(Singleton.Value);

class Singleton
{
    public static int Value { get; } = 1;
}

class UnsafeAccessors
{
    [UnsafeAccessor(UnsafeAccessorKind.StaticField, Name = "<Value>k__BackingField")]
    internal static extern ref int GetValueRef(Singleton t);
}
```

But worth to note no one guarantees this behavior won't change in the future.

Support for static classes is probably coming in .NET 10: https://github.com/dotnet/runtime/issues/90081

**Comment by tannergooding** [comment]
As was mentioned there are ways to still mutate the underlying field, such as via `UnsafeAccessor`, but such mutations are fundamentally unsafe and can lead to UB. If you need to mutate a field, don't mark it as `readonly` and provide an appropriate way to perform the mutation instead.

> Mock dependencies in tests. For example, we use a third-party library that provides an interface for interacting with DNS via a singleton. In tests, we need to replace the value of a static field.

We have such similar things in our own code, we simply drop the `const` or `readonly` for `DEBUG` allowing it to be mutated for that scenario: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigIntegerCalculator.SquMul.cs

The tests can then use a special helper that knows whether or not modifying the variable is supported: https://github.com/dotnet/runtime/blob/60d67b8630bfc9fc6882b0f88ea0801a15bb470c/src/libraries/System.Runtime.Numerics/tests/BigInteger/multiply.cs#L40 and https://github.com/dotnet/runtime/blob/60d67b8630bfc9fc6882b0f88ea0801a15bb470c/src/libraries/System.Runtime.Numerics/tests/BigInteger/BigIntTools.cs#L36

Alternatively you can utilize features such as `AppContext` switches, environment variables, or other mechanisms to ensure the initial value ends up correct.

> Overriding the default behavior of .NET and 3rd-party types built around the use of static APIs such as ThreaPool. For example, we use this to impose an end-to-end limit on how many Parallel.ForEachs can run at the same time. At any time, you can carry out a refactoring that will make the readonly field we need and this technique will stop working.

The same general considerations exist here, it is fairly trivial to have an AppContext switch, environment variable, or other input to seed a `static readonly` field allowing either user or per process customization. In some cases .NET provides its own context switches that allow you to customize the behavior (such as controlling GC configuration, limits in ASP.NET, etc).

**Comment by hez2010** [comment]
> As was mentioned there are ways to still mutate the underlying field, such as via `UnsafeAccessor`, but such mutations are fundamentally unsafe and can lead to UB.

Mutating initonly static fields using `UnsafeAccessor` is broken with optimization, so I have deleted the comment suggesting `UnsafeAccessor` :)

**Comment by tannergooding** [comment]
Right, that's why I made sure to call out that it's unsafe and can lead to UB.

`readonly` is considered an invariant and there are platforms, fields, and other scenarios that may require such data to go into readonly memory (such as for RVA statics or method local constants that go into otherwise "executable" memory). Further, because it is an invariant there are various systems and other components that take a dependency on this and assume the value will never be mutated once it's been initialized.

This isn't just an optimization, but rather a fundamental expectation of the system and that impacts many areas from security, to robustness, and also performance. If you have something that is fundamentally not readonly, then you shouldn't mark it as such.

**Comment by huoyaoyuan** [comment]
> If you have something that is fundamentally not readonly, then you shouldn't mark it as such.

The main ask was about components they don't own, including third party code and BCL types.

There is no really reliable way to modify static readonly fields, but some simple cases may just run well.

Using `UnsafeAccessor` can be an alternative way, but do remember the fundamental unreliability here.

**Comment by jkotas** [comment]
As others commented, this behavior is by design. The immutability of `readonly` fields is assumed by multiple parts of the system.

> Overriding the default behavior of .NET and 3rd-party types

If you need to modify behavior of .NET and 3rd-party components in ways that these components to do support natively, it is best to create your own build of those components with the required modifications, assuming that their license allows it.

**Comment by jkotas** [comment]
> Yes. It worked fine in the .NET Framework

It did not work reliably in .NET Framework. .NET Framework ignored the new value of readonly variable some of the time.
