### ISSUE TITLE
Potential improvements for System.Numerics.Complex

### ISSUE THREAD

**Issue by lilinus** [dotnet/runtime#104233]
I have found a number of potential places for improvements in `System.Numerics.Complex`:
1. Use `Math.SinCos` when available in various places.
2. Use `double.Hypot` when available in `Complex.Hypot`
3. `sinh` and `cosh` are calculated simultaneously as:
```
double p = Math.Exp(x);
double q = 1 / p;
double sinh = (p - q) * 0.5;
double cosh = (p + q) * 0.5;
```
This is inaccurate for `sinh` due to catastrophic cancellation of `p-q` when `x` is close to zero.
Could perhaps be solved by using `Math.Sinh` and `Math.Cosh` within a threshold?

**Comment by tannergooding** [comment]
Please feel free to submit a PR for each of these.

For 3, we should just always call `Math.Sinh` and `Math.Cosh` to avoid potential inaccuracies and ensure IEEE 754 compliant results.
