### ISSUE TITLE
runtime-community: linux-ppc64le mono failure in BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs - outdated stored blob

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#104338]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728642&view=logs&j=afa9e9c9-0835-5e87-9576-859a0f7dc04f&t=06e5c6f9-c6d6-516b-3325-4576fe8baba2
Build error leg or test failing: linux-ppc64le Release AllSubsets_Mono

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs", "The stored blob with index 0 for type"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

- Found in PR (unrelated to failure): https://github.com/dotnet/runtime/pull/102403 
- Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-102403-merge-38681b80eb6e4038b1/System.Resources.Extensions.BinaryFormat.Tests/1/console.a12d2df7.log?helixlogtype=result
- Output:
```
BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs(obj: Tuple (1, "2", 3, 4, 5.5999999999999996, 0, 9), blobs: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue]) [FAIL]
      The stored blob with index 0 for type System.Tuple`7[[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.UInt32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int64, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Double, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Single, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Decimal, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] is outdated and needs to be updated.
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=728642
**Error message validated:** `[BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs The stored blob with index 0 for type`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/3/2024 1:39:39 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[732644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732644)|dotnet/runtime|[BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732644&view=ms.vss-test-web.build-test-results-tab&runId=18442084&resultId=147080)|dotnet/runtime#103837|
|[729358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729358)|dotnet/runtime|[BinaryFormatTests.FormatterTests.BinaryFormatterTests.ValidateAgainstBlobs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729358&view=ms.vss-test-web.build-test-results-tab&runId=18339394&resultId=139492)|dotnet/runtime#104365|
|[728642](https://dev.azure.com/dnceng-public/public/_build/results?buildId=728642)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.DeserializeStoredObjects](https://dev.azure.com/dnceng-public/public/_build/results?buildId=728642&view=ms.vss-test-web.build-test-results-tab&runId=18310726&resultId=164104)|dotnet/runtime#102403|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|3|

**Comment by buyaa-n** [comment]
Same failure on https://github.com/dotnet/runtime/pull/104332/checks?check_run_id=26976612809

**Comment by carlossanlop** [comment]
> Haven't seen this recently, closing.

Do we have rolling builds for runtime-community @akoeplinger ? Because if not, then these failures only get hit in PRs when the azp run is executed. In other words: very rarely.

**Comment by akoeplinger** [comment]
yes we have rolling builds
