### ISSUE TITLE
docker build --rm -f test.dockerfile . -t img-test : native aot compilation fails on Mac M1 in version 9, ok in version 8

### ISSUE THREAD

**Issue by LLT21** [dotnet/runtime#104325]
### Description

While packaging the project in https://github.com/LLT21/dotnet9.git with the command `docker build --rm -f test.dockerfile . -t img-test`, the following error occurs with .NET 9 preview: 

![image](https://github.com/dotnet/runtime/assets/43903768/ab5b068f-fe37-42ff-a22d-17ab7fcb75d8)

### Reproduction Steps

1. Clone the project in https://github.com/LLT21/dotnet9.git on a Mac M1 (ARM)
2. Build the docker file with: `docker build --rm -f test.dockerfile . -t img-test`

### Expected behavior

With dotnet version 8 this compiles well in aot; would like this also to work in dotnet 9

### Actual behavior

In dotnet 9 there is this error: `12.32   /usr/bin/ld.bfd:obj/Release/net9.0/linux-arm64/native/test.exports:3: syntax error in VERSION script`

**Comment by LLT21** [comment]
Apparently this is due the this line in the .csproj file: 
`    <DebuggerSupport>false</DebuggerSupport>`
Was probably supported in .NET 8, not anymore in .NET 9 ?

**Comment by jkotas** [comment]
Thank you for the report! https://github.com/dotnet/runtime/pull/104339 has the fix.
