### ISSUE TITLE
Regular expression doesn't match properly with numeric backreference to a named capture group

### ISSUE THREAD

**Issue by gregli-msft** [dotnet/runtime#104398]
### Description

See the repo steps.  Adding another empty capture group in case 5 somehow changes the behavior, where it doesn't for the other cases.  Case 5 is unique in that it includes a numeric back reference to a named capture group.

### Reproduction Steps

```
namespace ConsoleApp15
{
    using System;
    using System.Text.RegularExpressions;

    public class Program
    {
        public static void Main()
        {
            /* 1 */ Console.WriteLine(Regex.Match("hello", @"(l)\1").Value);
            /* 2 */ Console.WriteLine(Regex.Match("hello", @"(l)()\1").Value);
            /* 3 */ Console.WriteLine(Regex.Match("hello", @"(?<named>l)\1").Value);
            /* 4 */ Console.WriteLine(Regex.Match("hello", @"(?<named>l)\k<named>").Value);
            /* 5 */ Console.WriteLine(Regex.Match("hello", @"(?<named>l)\k<1>").Value);
            /* 6 */ Console.WriteLine(Regex.Match("hello", @"(?<named>l)()\1").Value);
            /* 7 */ Console.WriteLine(Regex.Match("hello", @"(?<named>l)()\k<named>").Value);
            /* 8 */ Console.WriteLine(Regex.Match("hello", @"(?<named>l)()\k<1>").Value);
        }
    }
}
```

### Expected behavior

Notice the double "ll" for all 6 cases.
```
ll
ll
ll
ll
ll
ll
ll
ll
```

### Actual behavior

Notice the single "l" for the 6th and 8th case, with \1 and \k<1> with the added capture group
```
ll
ll
ll
ll
ll
l
ll
l
```

### Known Workarounds

Use one of the other 5 forms.  However, I'm exposing this functionality to users who are writing regular expressions that I don't control, I'd have to wall off the use of \number for named captures completely to avoid the bug.

### Configuration

x64, .NET 8, but have tried it on a few other flavors of .NET too with the same results.

**Comment by stephentoub** [comment]
From https://learn.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions#named-matched-subexpressions:
"Named matched subexpressions are numbered consecutively from left to right after matched subexpressions."

For example if you change the `\1` to a `\2` in your fifth example, then it outputs "ll" instead of "l".

**Comment by gregli-msft** [comment]
Thanks @stephentoub, very helpful.  I missed this difference in regular expression flavors, comparing in particular to JavaScript.
