### ISSUE TITLE
AccessViolationException when using System.Numerics.Vector3 on net481

### ISSUE THREAD

**Issue by bensmooth** [dotnet/runtime#104341]
### Description

An AccessViolationException is thrown when this code is executed.

### Reproduction Steps

```
using System;
using System.Numerics;

namespace Sanity
{
    internal class Sanity
    {
        static void Main()
        {
            TestSanity(new Vector3(10));
        }

        private static void TestSanity(Vector3 v)
        {
            v.X = v.Y;
            Console.WriteLine(new Vector4(v, 0));
        }
    }
}
```

With this project file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>
```

`dotnet run` or run in Visual Studio.
Happens in Release and Debug.

### Expected behavior

Something like `<10, 10, 10, 0>` is printed.

### Actual behavior

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory.
This is often an indication that other memory is corrupt.
   at Sanity.Sanity.TestSanity(Vector3 v) in Sanity.cs:line 15
   at Sanity.Sanity.Main() in Sanity.cs:line 9
```

### Regression?

This only happens in net48 and net481.

Changing it to net6.0 produces the expected behavior.

### Known Workarounds

Don't use net48/net481.  Use later versions.

### Configuration

Windows 10 x64 22H2 - 19045.4412
`dotnet --version` yields 8.0.100

### Other information

Similar issue here on OSX, reported for net7.0: https://github.com/dotnet/runtime/issues/79118
But that issue was described as not deterministic.  This issue happens every time.

**Comment by jeffschwMSFT** [comment]
Please use Visual Studio Developer community (https://developercommunity.visualstudio.com/index.html) for reporting .NET Framework issues.  Link the issue here and I can help route it to the right team.

**Comment by jeffschwMSFT** [comment]
thank you.  you may have already seen this post, but it has details about changes to .NET Framework

https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/

please include any additional details about impact, etc. to the developer community issue
