### ISSUE TITLE
Ensure no component embed the Index/Range source code and reference Microsoft.Bcl.Memory package instead

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#104308]
### Description

We have [poly filled the Index and Range types](https://github.com/dotnet/runtime/pull/104170) to make them work on ns2.0 and netfx. This issue is tracking to ensure all components we build in .NET shouldn't carry its own version of these types and instead should be referencing `Microsoft.Bcl.Memory` package. 

Searching the sources, looks only [ComInterfaceGenerator.csproj](https://github.com/dotnet/runtime/blob/7b1c0f3f4dc8a6e97ad3bbdf353bf3f74e4faede/src/libraries/System.Runtime.InteropServices/gen/ComInterfaceGenerator/ComInterfaceGenerator.csproj#L29) is using the Index source file. To remove this dependency, we will need to have this project depend on `Microsoft.Bcl.Memory` and ensure `Microsoft.Bcl.Memory` library is included in `microsoft.netcore.app.ref` pack too under the `analyzers\dotnet\cs` folder. Unfortunately, the current infrastructure does not allow to bin pace such dependency. 

Here are the things need to be done:
- Remove compiling the Index source code in https://github.com/dotnet/runtime/blob/7b1c0f3f4dc8a6e97ad3bbdf353bf3f74e4faede/src/libraries/System.Runtime.InteropServices/gen/ComInterfaceGenerator/ComInterfaceGenerator.csproj#L29
- Let ComInterfaceGenerator.csproj reference the project of `Microsoft.Bcl.Memory`.
- Delete the lines https://github.com/dotnet/runtime/blob/7b9f1c345b13b49eefd47d4b60c61c6de3aee1b9/src/libraries/Directory.Build.targets#L205-L209
- Ensure when building `Microsoft.Bcl.Memory` is bin placed inside the `microsoft.netcore.app.ref` package under `analyzers\dotnet\cs` folder and next to the ComInterfaceGenerator lib.
- Edit [Index](https://github.com/dotnet/runtime/blob/7b9f1c345b13b49eefd47d4b60c61c6de3aee1b9/src/libraries/System.Private.CoreLib/src/System/Index.cs#L18) and [Range](https://github.com/dotnet/runtime/blob/7b9f1c345b13b49eefd47d4b60c61c6de3aee1b9/src/libraries/System.Private.CoreLib/src/System/Range.cs#L23) to remove the `#if` there and only keep `public` specifier.
- edit `Microsoft.Bcl.Memory.csproj` from library `src` folder to remove the line `<DefineConstants>MICROSOFT_BCL_MEMORY;$(DefineConstants)</DefineConstants>`
- Build the whole tree and validate tests of the com interface and `Microsoft.Bcl.Memory` pass and the package `microsoft.netcore.app.ref` include `Microsoft.Bcl.Memory` library.

### Reproduction Steps

Com interface source gen is including the Index.cs in the project. 

### Expected behavior

No component in .NET is embedding the Index/Range sources. 

### Actual behavior

Com interface source gen carries a copy of the Index type code.

### Regression?

No

**Comment by tarekgh** [comment]
CC @ViktorHofer @ericstj  @jkoritzinsky @stephentoub

**Comment by ericstj** [comment]
I don't think we should be taking dependencies in our source generators.  Analyzers don't have a great system for distributing dependencies - no way to specify those to the compiler, nor control loading - also no way to use the framework version when it exists.  In cases of our analyzers it's better to share source.
