### ISSUE TITLE
Test time out for Loader tests on osx arm64 in  gcstress0x3

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#104323]
Pipeline: [runtime-coreclr gcstress0x3-gcstress0xc](https://dev.azure.com/dnceng-public/public/_build?definitionId=112&_a=summary): [20240630.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725436)

coreclr osx arm64 Checked gcstress0x3 @ OSX.1200.ARM64.Open
Loader.0.3 [Log](https://[helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e87e64454bd48c581/Loader.0.3/1/console.229eead2.log?helixlogtype=result](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e87e64454bd48c581/Loader.0.3/1/console.229eead2.log?helixlogtype=result))
Loader.2.3 [Log](https://[helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e87e64454bd48c581/Loader.2.3/1/console.d7ac6ba7.log?helixlogtype=result](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e87e64454bd48c581/Loader.2.3/1/console.d7ac6ba7.log?helixlogtype=result))

**Comment by EgorBo** [comment]
The test is just too slow under gcstress

**Comment by EgorBo** [comment]
Closing as recent runs are fine
