### ISSUE TITLE
[API Proposal]: Support iterating as span over Dictionary and HashSet

### ISSUE THREAD

**Issue by Meir017** [dotnet/runtime#104347]
### Background and motivation

Using span for iterating over dictionaries and sets will improve the performance

### API Proposal

```csharp
namespace System.Collections.Generic;

public class Dictionary<TKey, TValue>
{
    public void ForEach(Action<TKey, TValue> action)
    {
        Span<Entry> entries = _entries;
        foreach (Entry entry in entries)
        {
            action(entry.Key, entry.Value);
        }
    }
}

public class HashSet<T>
{
    public void ForEach(Action<T> action)
    {
        Span<T> entries = _entries;
        foreach (T entry in entries)
        {
            action(entry);
        }
    }
}
```

### API Usage

```csharp
// Fancy the value
var dictionary = new Dictionary<string, string>();
dictionary.ForEach((key, value) => {});

// Getting the values out
foreach (var v in c)
    Console.WriteLine(v);
```

### Alternative Designs

Have the compiler have special handling for foreach statements on Dictionary & HashSet and iterate by getting a span to the underlying entries array

### Risks

making changes to the current enumerator could break the behavior of the version check
```cs
if (_version != _hashSet._version)
{
    ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion();
}
```

**Comment by huoyaoyuan** [comment]
This isn't actionable. A span means a purely linear, compact backing storage on raw elements, which isn't true for hash-based collection.

**Comment by eiriktsarpalis** [comment]
Furthermore we're no longer adding `Foreach` methods to collection types. In practice a struct enumerator is much faster compared to making one delegate invocation per element.

**Comment by Meir017** [comment]
@eiriktsarpalis in this case - does the struct enumerator have similar performance to creating a span from the private entries and iterating over the span's iterator?

**Comment by eiriktsarpalis** [comment]
My expectation is that the cost of copying all entries to a new buffer plus the overheads of iterating using a callback would substantially outweigh any benefits of span iteration as such.

**Comment by huoyaoyuan** [comment]
Delegate invocation is usually *very* heavy comparing to struct enumerators.

**Comment by Meir017** [comment]
makes sense. 

one more suggestion, what if the `Dictionary.Entry` struct becomes public and the `key` & `value` fields become stay public and the `hashCode` & `index` become internal.

then a new `AsSpan` API can be exposed for Dictionary in the `CollectionsMarshal` class.

something like this:

```cs
namespace System.Runtime.InteropServices;

public static class CollectionsMarshal
{
    public static Span<Dictionary<TKey, TValue>.Entry> AsSpan<TKey, TValue>(Dictionary<TKey, TValue> dictionary);
    public static Span<HashSet<T>.Entry> AsSpan<T>(HashSet<T> hashSet);
}
```

**Comment by eiriktsarpalis** [comment]
This wouldn't be possible because the entries of a dictionary or hashset aren't necessarily stored in a contiguous span in that entries arrays. There could be gaps in between.

**Comment by huoyaoyuan** [comment]
List can benefit from `AsSpan` because its underlying storage is linear and compact, which fits in a span.

Using span can only benefit when *there's already a span*.

**Comment by Meir017** [comment]
@eiriktsarpalis meaning that the entries array can have more items than the dictionary/hashet due to some of the items being empty?

**Comment by stephentoub** [comment]
> [@eiriktsarpalis](https://github.com/eiriktsarpalis) meaning that the entries array can have more items than the dictionary/hashet due to some of the items being empty?

When an entry is removed from the dictionary, other entries in the array aren't shifted down to fill the gap: that gap will be filled on subsequent adds, and in the meantime the entry is just left there with garbage.
