### ISSUE TITLE
Make `System.Text.Json.Serialization.JsonConverter::.ctor` reflection-free

### ISSUE THREAD

**Issue by slxdy** [dotnet/runtime#104367]
Currently, it's pretty difficult to use the Json serializer with NativeAOT (reflection-free), because the `JsonConverter` constructor gets the assembly in which its object's type is defined.

My proposal is to turn `JsonConverter::IsInternalConverter` into a virtual property with a single getter that returns `false` by default, so all internal derivatives can override it and return `true` instead.

**Comment by eiriktsarpalis** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/78029
