### ISSUE TITLE
Exception when trying to GCHandle.Alloc(new ValueTuple<ulong, ulong>[1], GCHandleType.Pinned)

### ISSUE THREAD

**Issue by voinokin** [dotnet/runtime#10436]
I'm getting exception when I try to pin array of `ValueTuple`s using this statement with .NET Core 2.1 release:

> GCHandle.Alloc(new ValueTuple<ulong, ulong>[1], GCHandleType.Pinned)

The exception tells:
> System.ArgumentException
>   HResult=0x80070057
>   Message=Object contains non-primitive or non-blittable data.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
>    at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type) in E:\A\_work\31\s\src\mscorlib\src\System\Runtime\InteropServices\GcHandle.cs:line 94

**Comment by AaronRobinsonMSFT** [comment]
@voinokin Thanks for the suggestion. We have decided the error message mentions the blittable requirement here and searching for that term results in the description found [here](https://docs.microsoft.com/dotnet/framework/interop/default-marshaling-behavior#default-marshaling-for-value-types). Please let us know if there is any additional concern.
