### ISSUE TITLE
[API Proposal]: Obsolete AVX-512 sign-extended widening to unsigned

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/runtime#104320]
### Background and motivation

It looks like the AVX-512 integer widening instructions were inadvertently given unsigned method definitions since these do not match any C intrinsics, and the equivalents in SSE41 and AVX2 were not defined.  The methods for sign-extended widening to unsigned result are particularly confusing from a usage perspective.

### API Proposal

```csharp
public abstract class Avx512F : Avx2
{
    [Obsolete("Use ConvertToVector512Int32")]
    public static Vector512<uint> ConvertToVector512UInt32(Vector128<sbyte> value);
    [Obsolete("Use ConvertToVector512Int32")]
    public static Vector512<uint> ConvertToVector512UInt32(Vector128<byte> value);
    [Obsolete("Use ConvertToVector512Int32")]
    public static Vector512<uint> ConvertToVector512UInt32(Vector256<short> value);
    [Obsolete("Use ConvertToVector512Int32")]
    public static Vector512<uint> ConvertToVector512UInt32(Vector256<ushort> value);

    [Obsolete("Use ConvertToVector512Int64")]
    public static Vector512<ulong> ConvertToVector512UInt64(Vector128<sbyte> value);
    [Obsolete("Use ConvertToVector512Int64")]
    public static Vector512<ulong> ConvertToVector512UInt64(Vector128<byte> value);
    [Obsolete("Use ConvertToVector512Int64")]
    public static Vector512<ulong> ConvertToVector512UInt64(Vector128<short> value);
    [Obsolete("Use ConvertToVector512Int64")]
    public static Vector512<ulong> ConvertToVector512UInt64(Vector128<ushort> value);
    [Obsolete("Use ConvertToVector512Int64")]
    public static Vector512<ulong> ConvertToVector512UInt64(Vector256<int> value);
    [Obsolete("Use ConvertToVector512Int64")]
    public static Vector512<ulong> ConvertToVector512UInt64(Vector256<uint> value);
}

public abstract class Avx512BW : Avx512F
{
    [Obsolete("Use ConvertToVector512Int16")]
    public static Vector512<ushort> ConvertToVector512UInt16(Vector256<sbyte> value);
    [Obsolete("Use ConvertToVector512Int16")]
    public static Vector512<ushort> ConvertToVector512UInt16(Vector256<byte> value);
}
```

### API Usage

Don't use these.

### Alternative Designs

The zero-extending (unsigned->unsigned) methods are actually fine, though inconsistent with the other ISA APIs, so they could stay.  It's really just the signed extension to unsigned that are weird.

**Comment by tannergooding** [comment]
These are intentional and match the same behavior you'd get for `(uint)someSbyte`. Whether it is sign or zero-extending is based on the source type, not the destination type.

**Comment by saucecontrol** [comment]
That's not the same, though.  `(uint)someSbyte` zero-extends.  `ConvertToVector512UInt32(Vector128<sbyte> value)` emits `vpmovsxbd`, which sign extends, which is weird because it doesn't exist anywhere else as a signed->unsigned conversion.

**Comment by tannergooding** [comment]
> (uint)someSbyte zero-extends

It does not. `sbyte s = -1; uint x = (uint)s;` produces the value `uint.MaxValue`, not the value `0xFF`.

**Comment by saucecontrol** [comment]
Wait, `(uint)someSbyte` sign extends, so ok I guess that makes sense.  It's strange that the conversion is defined in the Avx512 surface area but not the others, then.  I'll just ignore them :)

**Comment by tannergooding** [comment]
>  It's strange that the conversion is defined in the Avx512 surface area but not the others, then

Yes, ideally we would expose these for parity.

I believe there's also some MultiplyLow overloads that are missing from the lower level APIs (for `n-bit * n-bit = n-bit` signed and unsigned multiplication always produces the same result). In general we've tried to expose such APIs where possible (to avoid the need for users to manually swap operands or `.AsType()` when it is bitwise equivalent), but there's places we've missed them.
