### ISSUE TITLE
x64 JIT crash 'Compiler::implResolveToken' for typeof(ValueType) containing array of self

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/runtime#10431]
The following program crashes the **x64** JIT.

    using System;

    public struct StructTree
    {
        public Double P;
        public StructTree[] rg;
    };

    class Program
    {
        static void Main() => T = typeof(StructTree);      // <-- EETypeLoadException

        static Type T; // (not important that 'T' be a non-local variable; only done here to
                       // prevent the above assignment from being fully optimized-out)
    }

The exception:

>Exception thrown at 0x00007FFDFD13F218 in ConsoleApp23.exe: Microsoft C++ exception: EETypeLoadException at memory location 0x0000003F1433A450.

Stack trace:

	RaiseException()
	_CxxThrowException()
	Compiler::impResolveToken() Line 277          <--- EETypeLoadException
	Compiler::impImportBlockCode() Line 14293
	Compiler::impImportBlock() Line 16079
	Compiler::impImport() Line 17163
	[Inline Frame] Compiler::fgImport() Line 6800
	Compiler::compCompile() Line 4386
	Compiler::compCompileHelper() Line 6025
	Compiler::compCompile() Line 5359
	jitNativeCode() Line 6666
	CILJit::compileMethod() Line 315
	_CorExeMain()
	_CorExeMain_Exported()
	BaseThreadInitThunk()
	RtlUserThreadStart()

Here's a link to the throwing source code form the [coreclr repo](https://github.com/dotnet/coreclr):

https://github.com/dotnet/coreclr/blob/86c438de4043359942f3e0f46c55fdaa98dc5b2f/src/jit/importer.cpp#L262-L277

As best as I can tell, that would be here:

![asm](https://user-images.githubusercontent.com/5589855/40815819-f5e8d6c6-64fd-11e8-9901-98adcc270f9b.png)

The **IL** code for the problematic **C#** JIT target method (`Program.Main`) is essentially the same for *Debug* and *Release* builds, and both exhibit the crash.

	L_0000: ldtoken StructTree
	L_0005: call class [mscorlib]Type [mscorlib]Type::GetTypeFromHandle(valuetype [mscorlib]RuntimeTypeHandle)
	L_000a: stsfld class [mscorlib]Type Program::T
	L_000f: ret 

To Reproduce
----

To reproduce this crash, create a new **C#** project for .NET 4.7.2 in the latest VS2017. Enter the code shown at the top. Alternatively, [here's a zip](https://github.com/dotnet/coreclr/files/2060673/jit-crash-resolve-token-recursive.zip) of the whole project.

Next, on the *Project Properties* pane, enable **Native Code Debugging**:

![app-properties](https://user-images.githubusercontent.com/5589855/40815912-a3573802-64fe-11e8-9d48-b0b8c86e142d.png)

On the *Exception Settings* pane, enable exceptions as shown here:

![ex-settings](https://user-images.githubusercontent.com/5589855/40815934-cd6d1526-64fe-11e8-8929-2b773df0df56.png)

Here are the debugger settings I used. In the case of **Suppress JIT optimization on module load**, it does not have any effect on the issue (the crash occurs in both modes).

![dbg-opts](https://user-images.githubusercontent.com/5589855/40816102-d3693878-64ff-11e8-82e0-16dfaa56e038.png)

**Comment by jkotas** [comment]
This was fixed some time ago. The internal exception is no longer thrown and caught in this case.
