### ISSUE TITLE
JIT: Spurious 0-sized diffs in smoke_tests.nativeaot.windows.arm64

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#104441]
We're seeing some spurious 0-sized diffs in smoke_tests.nativeaot.windows.arm64. Seems likely to be related to #104282, can you take a look @kunalspathak?

**Comment by jakobbotsch** [comment]
@kunalspathak #104516 does not seem to have fixed this issue -- I still see 0 sized diffs on superpmi-diffs in smoke_tests.nativeaot.windows.arm64.checked.

**Comment by kunalspathak** [comment]
> @kunalspathak #104516 does not seem to have fixed this issue -- I still see 0 sized diffs on superpmi-diffs in smoke_tests.nativeaot.windows.arm64.checked.

Yes, the fix in #104516 was mainly for handling the "unhandled reloc type" errors and not this specific one. I was not able to setup libcoredistools to debug what the problem is. Will send separate fix for this one.
