### ISSUE TITLE
Interpretation of ByRefLikeAttribute in .NET Core 2.1 is a breaking change and a standard violation

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/runtime#10446]
As a matter of facts, it is possible in .NET Core 2.0 to use a ref struct as an argument of a generic parameter if you're generating MSIL, but this same MSIL code no longer runs in .NET Core 2.1. We used this compilation pattern in PostSharp and did all the testing in .NET Core 2.0, just to see it's breaking in .NET Core 2.1.

I understand why you guys have taken this approach as this is a pragmatic way, but I think it is my role as a third-party tool developer to respectfully complain.

Giving a runtime meaning to a custom attribute (ByRefLikeAttribute) is non-standard-compliant (ECMA-335), so the least I would expect is that you document an extension or violation of the standard. An orthodox approach would have been to define a new TypeAttribute and to cope with the problem that the compiler will need a specific version of the runtime. 

The concrete impact for this change and as far as PostSharp is concerned is minimal because support for C# 7.2 in PostSharp wasn't made RTW yet.

However, as a policy, breaking standards and relying on "tricks" (like ObsoleteAttribute) to minimize their impact is unhealthy and warrants this complain.

It seems there's a need for a well-thought solution to this problem. Like .NET Standard is the API-level answer to this issue, should it be some CLR Standard? Maybe the compiler could emit a list of non-standard-compliant extensions, marked as MUST UNDERSTAND or OPTIONAL, that all members of the MSIL pipeline (therefore including the compiler, PostSharp and the CLR) would respect.

```
[assembly: AssemblyRequiresClr( 2012 /* baseline CIL spec */, "!RefStruct" /* required extension */ )]
```

**Comment by mangod9** [comment]
Hi @gfraiteur, assume this issue could be closed now, or is there anything actionable to keep it active? Thx.

**Comment by gfraiteur** [comment]
No problem to close.
