### ISSUE TITLE
System.Numerics.Complex Parse (string s, IFormatProvider? provider) don't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#104421]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemNumericsComplex-Parse-string-s/10676770)._

---
Copy the code into a new console application, and run.

```c#
using System.Numerics;

string text = "<47; 0>";
Complex value = Complex.Parse(text, null);  //  Throws OverflowException
```

---
#### Feedback Bot on 6/6/2024, 03:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tannergooding** [comment]
Resolved with #104388
