### ISSUE TITLE
Apple mobile JIT_Directed runtime tests failures: System.DllNotFoundException: EmptyStructsLib

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#104430]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=727276
Build error leg or test failing: `JIT_Directed`
Affected CI: `tvos_arm64_release_allsubsets_mono_runtimetests`, `ios_arm64_release_allsubsets_mono_runtimetests` (`runtime-extra-platforms`)
Range of commits: https://github.com/dotnet/runtime/compare/bb63e362...c07a81f9 (long due to broken Apple mobile CI)

Stack trace example:
```
[06:09:18.5655820] 2024-07-02 03:09:18.628 JIT_Directed[69619:100114480] System.DllNotFoundException: EmptyStructsLib
[06:09:18.5656160]    at Program.TestIntEmptySysV()
[06:09:18.5656240]    at __GeneratedMainWrapper.Main()
[06:09:18.5663210] Xamarin.Hosting: Process '69619' exited with exit code 101 or crashing signal .
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.DllNotFoundException: EmptyStructsLib",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=727276
**Error message validated:** `[System.DllNotFoundException: EmptyStructsLib`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/4/2024 11:48:18 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by matouskozak** [comment]
The range of commits is quite long so it's difficult to identify the root cause. @fanyang-mono do you know if https://github.com/dotnet/runtime/pull/103975 could have caused that the DLL is not loaded properly in these scenarios?

**Comment by jakobbotsch** [comment]
Note that the test is new with #103799, so it may have never worked.

**Comment by matouskozak** [comment]
> Note that the test is new with #103799, so it may have never worked.

You're right, missed that one. Thanks! I think we need to disable the tests because we don't support building native libraries on Apple mobile https://github.com/dotnet/runtime/issues/92129.
