### ISSUE TITLE
Customize bundle extract base directory within the app

### ISSUE THREAD

**Issue by rara64** [dotnet/runtime#104422]
I'm using `IncludeNativeLibrariesForSelfExtract` option in my single file self-contained app and by default these libraries will be extracted to `AppData\Local\Temp\.net`. I want to change this location to be in the same directory where the app executable is located. I understand there is an environment variable `DOTNET_BUNDLE_EXTRACT_BASE_DIR`, but this would require my app to have an external runner.

Is there a way to define this inside `runtimeconfig.template.json` or in a similar place so that the published app will auto-extract native libraries to the specified folder on every machine?

If something like this doesn't currently exist, I'd like to request this as a new feature.

**Comment by agocke** [comment]
> If something like this doesn't currently exist, I'd like to request this as a new feature.

Nothing like this exists right now. Extraction is already considered a secondary feature. I don't think it's likely that we will offer any more customization options in the future, so I'm going to close this as not planned.
