### ISSUE TITLE
Enumerating ImmutableSortedSet<> is slower than index-based for loop

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/runtime#1044]
To my great surprise it seems faster to iterate an `ImmutableSortedSet<object>` using a `for` loop (with lookup by index) rather than a `foreach` loop.

I discovered this while working on the CPS tree which makes heavy use of this collection type within Visual Studio.

I'd like to fix this if there's interest.

|  Method |    Runtime | Count |           Mean |         Error |        StdDev |
|-------- |----------- |------ |---------------:|--------------:|--------------:|
| Foreach |   .NET 4.8 |     1 |     376.414 ns |     7.4909 ns |    12.9214 ns |
| ForLoop |   .NET 4.8 |     1 |       4.992 ns |     0.0901 ns |     0.0753 ns |
| Foreach | CoreRt 3.1 |     1 |     360.885 ns |     2.8646 ns |     2.6796 ns |
| ForLoop | CoreRt 3.1 |     1 |       4.905 ns |     0.0653 ns |     0.0578 ns |
| Foreach |   .NET 4.8 |    10 |   1,322.343 ns |    16.3168 ns |    12.7391 ns |
| ForLoop |   .NET 4.8 |    10 |      77.545 ns |     1.5846 ns |     1.5562 ns |
| Foreach | CoreRt 3.1 |    10 |   1,079.793 ns |    15.3006 ns |    12.7767 ns |
| ForLoop | CoreRt 3.1 |    10 |      78.040 ns |     0.6698 ns |     0.6266 ns |
| Foreach |   .NET 4.8 |    50 |   5,375.774 ns |    47.3741 ns |    44.3138 ns |
| ForLoop |   .NET 4.8 |    50 |     553.756 ns |     4.5654 ns |     4.0471 ns |
| Foreach | CoreRt 3.1 |    50 |   4,260.279 ns |    91.8036 ns |    85.8732 ns |
| ForLoop | CoreRt 3.1 |    50 |     497.019 ns |     7.6752 ns |     7.1794 ns |
| Foreach |   .NET 4.8 |   100 |  10,312.971 ns |   202.4086 ns |   189.3331 ns |
| ForLoop |   .NET 4.8 |   100 |   1,206.282 ns |    14.0805 ns |    12.4820 ns |
| Foreach | CoreRt 3.1 |   100 |   8,181.352 ns |   103.6609 ns |    91.8927 ns |
| ForLoop | CoreRt 3.1 |   100 |   1,132.844 ns |    22.3796 ns |    21.9798 ns |
| Foreach |   .NET 4.8 |   500 |  51,068.065 ns |   735.3326 ns |   687.8306 ns |
| ForLoop |   .NET 4.8 |   500 |  22,065.454 ns |   354.1798 ns |   331.3000 ns |
| Foreach | CoreRt 3.1 |   500 |  39,410.555 ns |   903.0918 ns |   927.4088 ns |
| ForLoop | CoreRt 3.1 |   500 |  19,802.825 ns |   351.4609 ns |   328.7567 ns |
| Foreach |   .NET 4.8 |  1,000 | 103,140.166 ns | 2,051.8266 ns | 3,254.4144 ns |
| ForLoop |   .NET 4.8 |  1,000 |  49,174.719 ns |   974.7339 ns | 1,083.4141 ns |
| Foreach | CoreRt 3.1 |  1,000 |  78,940.633 ns | 1,278.5821 ns | 1,195.9865 ns |
| ForLoop | CoreRt 3.1 |  1,000 |  49,001.032 ns |   607.5614 ns |   568.3133 ns |
| Foreach |   .NET 4.8 |   100,000 |    11,109.16 us |    154.436 us |    128.961 us |
| ForLoop |   .NET 4.8 |   100000 |     6,856.00 us |    131.878 us |    171.478 us |
| Foreach | CoreRt 3.1 |   100,000 |     9,279.47 us |    181.671 us |    161.047 us |
| ForLoop | CoreRt 3.1 |   100,000 |     7,494.75 us |    148.876 us |    252.803 us |
| Foreach |   .NET 4.8 | 10,000,000 | 1,178,668.95 us |  7,865.580 us |  6,972.632 us |
| ForLoop |   .NET 4.8 | 10,000,000 |   968,972.85 us |  8,683.476 us |  8,122.529 us |
| Foreach | CoreRt 3.1 | 10,000,000 |   933,400.05 us | 15,967.356 us | 14,154.645 us |
| ForLoop | CoreRt 3.1 | 10,000,000 |   924,590.38 us | 17,706.653 us | 17,390.301 us |

---

Here is my benchmark methodology for review.

```text
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Xeon Silver 4110 CPU 2.10GHz, 2 CPU, 32 logical and 16 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4075.0), X64 RyuJIT
  Job-JVQUKH : .NET Framework 4.8 (4.8.4075.0), X64 RyuJIT
  Job-FFQQFZ : .NET CoreRT 1.0.28418.02 @BuiltBy: dlab14-DDVSOWINAGE101 @Branch: master @Commit: 871de747f73119bf7e8a86c8e8c2bf606b7cc673, X64 AOT
```

```c#
[SimpleJob(RuntimeMoniker.Net48)]
[SimpleJob(RuntimeMoniker.CoreRt31)]
public class ImmutableSortedSetIterationBenchmarks
{
    private ImmutableSortedSet<string> set;

    [Params(1, 10, 50, 100, 500, 1000)]
    public int Count;

    [GlobalSetup]
    public void Setup()
    {
        set = ImmutableSortedSet.CreateRange(
            StringComparer.Ordinal,
            Enumerable.Range(0, Count).Select(i => i.ToString()));
    }

    [Benchmark]
    public int Foreach()
    {
        var sum = 0;
        
        foreach (var item in set)
        {
            sum += item.Length;
        }

        return sum;
    }

    [Benchmark]
    public int ForLoop()
    {
        var sum = 0;

        for (var i = 0; i < set.Count; i++)
        {
            sum += set[i].Length;
        }

        return sum;
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;netcoreapp3.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.12.0" />
  </ItemGroup>
</Project>
```

**Comment by danmosemsft** [comment]
If you can offer a PR that improves it without impacting other scenarios or complicating the code to an unacceptable extent, I'm sure we'd be interested. Thanks.

**Comment by layomia** [comment]
Triage: on inspection, it looks like the MoveNext method in the enumerator is a constant time operation, so your results are surprising. We would need to profile the operation to check for any bottlenecks.
