### ISSUE TITLE
HostFxr - calling load_assembly_and_get_function_pointer return -2146234280

### ISSUE THREAD

**Issue by ArthurVasseur** [dotnet/runtime#104436]
I am trying to get a function pointer Hello from a C# dll, but I am encountering the following error:
```
0x80131058 : Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context.
```
The associated code can be found  [here](https://github.com/ConcertoEngine/ConcertoDotNet/blob/5e1fb8f1f7efd0601d3ea26ec6e5a94475ab0b64/Include/Concerto/DotNet/Assembly.hpp#L119)

The problem does not seem to come from the code itself but rather from how the library is being built. When I use the DLL provided from the  `.NET Hosting Sample`, it works correctly.

You can find the build file [here](https://github.com/ConcertoEngine/ConcertoDotNet/tree/main/Assets)
I am building the DLL using the following command: `dotnet build`

PS: For instructions on building the project, please refer to the repository [repo](https://github.com/ConcertoEngine/ConcertoDotNet), After following the setup instructions, run`xmake project -k vsxmake` to create a Visual Studio project.

**Comment by jkotas** [comment]
The build produces multiple flavors of the assembly .dll file:
- The flavor meant for execution. It is in directory like `bin\Debug\net8.0\*.dll`.
- The flavor called "reference assembly" that is only meant to be used during the build and cannot be executed. It is in `ref` or `refint` subdirectory, like `obj\Debug\net8.0\ref\*.dll`

"Reference assemblies should not be loaded for execution." error means that you are trying to reference assembly. Make sure that you are trying to execute the flavor meant for execution, and not the one from `ref` or `refint` subdirectory.

**Comment by ArthurVasseur** [comment]
Oh, I see it's working now, thank a lot !

On Windows, the code returned by  `load_assembly_and_get_function_pointer` can be decoded with the following C++ code:
```cpp
auto hres = HRESULT_FROM_WIN32(rc);
auto facility = HRESULT_FACILITY(hres);
auto severity = HRESULT_SEVERITY(hres);
auto code = HRESULT_CODE(hres);
```
How can this be done on POSIX systems?

**Comment by jkotas** [comment]
The HRESULT error codes should be treated as opaque constants. 

You should not ever need to decode them like that. (In case you really want to that for some reason, you can copy the definitions of these macros from this repo - they are under MIT license. https://github.com/search?q=repo%3Adotnet%2Fruntime%20HRESULT_SEVERITY&type=code
