### ISSUE TITLE
[BUG] typeof statements for types nested within generic types are incosistent

### ISSUE THREAD

**Issue by InsanityCode** [dotnet/runtime#104510]
### Description

`typeof` expressions treat type arguments of generic containing types differently depending on whether they are expressed explicitly or provided via an equivalent `using` alias.

### Reproduction Steps

1. Open Visual Studio or Visual Studio Code (with the C# Dev Kit installed)
2. Create project using the C# console project template
3. Paste below code into the generated `Program.cs` file
4. Comment out lines that won't compile or throw exceptions as desired
5. Run

``` C#
using Alias = Test.A<int>;

namespace Test
{
    class A<T>
    {
        public class B<U> { }
        public class C { }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // expected behavior: yields A<int>.B<double>
            // observed behavior: CS7003 Unexpected use of an unbound generic name
            typeof(A<int>.B<>).MakeGenericType(typeof(double));

            // expected behavior: yields A<int>.B<double> (should be the same as above, Alias is only an alias for A<int>)
            // observed behavior: throws System.ArgumentException: The number of generic arguments provided doesn't equal the arity of the generic type definition.
            typeof(Alias.B<>).MakeGenericType(typeof(double));

            // expected behavior: throws System.ArgumentException: The number of generic arguments provided doesn't equal the arity of the generic type definition.
            //                    Alias already specifies int as type argument for A<>.
            //                    Resupplying int in MakeGenericType is redundant and potentially incosistent with Alias (see below)
            // observed behavior: creates A<int>.B<double>
            typeof(Alias.B<>).MakeGenericType(typeof(int), typeof(double));

            // expected behavior: throws System.ArgumentException: The number of generic arguments provided doesn't equal the arity of the generic type definition.
            //                    Alias already specifies int as type argument for A<>.
            //                    Specifying string conflicts with int specified in Alias.
            // observed behavior: overrides int concretization (provided from Alias) with string
            typeof(Alias.B<>).MakeGenericType(typeof(string), typeof(double));

            // works as (may be?) expected
            typeof(A<>.B<>).MakeGenericType(typeof(int), typeof(double));
            typeof(A<>.C).MakeGenericType(typeof(int));

            // as expected:       crashes with InvalidOperationException: 'Test.A`1+C[System.Int32] is not a GenericTypeDefinition.
            typeof(A<int>.C).MakeGenericType();
            typeof(Alias.C).MakeGenericType();
            typeof(Alias.C).MakeGenericType(typeof(int));
        }
    }
}
```

### Expected behavior

See comments in provided code.

### Actual behavior

See comments in provided code.

### Regression?

No.
Tested with C# 2.0 up to C# 12.0 and multiple .NET Framework versions, all show the same behavior.

### Known Workarounds

As shown in the provided code.

### Configuration

Tested with
- Windows - Visual Studio 2015 - .NET Framework 4.5.2 - Architecture irrelvant
- Windows - .NET SDK 8.0.300 - Any target framework - Architecture irrelvant

### Other information

This might actually belong to the [C# language repository](https://github.com/dotnet/csharplang/), but that does not provide an option to create a bug report.  
[CS7003](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs7003) states that this error may be generated for variable declarations or object instantiation, but makes no mention of `typeof` statements, so having this error occur there seems like a bug.

Co-Authored-By: @FramePerfection

**Comment by huoyaoyuan** [comment]
> This might actually belong to the [C# language repository](https://github.com/dotnet/csharplang/), but that does not provide an option to create a bug report.

csharplang holds the language design and specification. Issues for compiler implementation should be reported to https://github.com/dotnet/roslyn . Sometimes there may ends up be unclear statement in language specification.

All `MakeGenericType` behaviors should be correct. Note that CLR doesn't allow *partially* instantiated generic type (`A<int>.B<>`). Thus, `Alias.B<>` will be translated to *uninstantiated* generic type (`A<>.B<>`). You can verify this at [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQCCANgJYCGAzqQLwUA81AdgC4B8A3IULY2AFR6EA3oVIzSGAMxyspAEKsAqj1ITSAX2myFS0gGFtewvoJDlImPS6SDMkQE8ADjFIBZABQBKZi0uDxgIADNfKjp6ADo1Hn8BAl0gA==).

Given the behavior is present since the first introduction of generic in C# 2, it should be properly documented.

**Comment by huoyaoyuan** [comment]
Interestingly, I can't find any words explicitly mentioning this in current C# standard: 
https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/namespaces.md#1452-using-alias-directives
https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/types.md
https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/expressions.md#12817-the-typeof-operator

Anyway, the question should be a discussion in csharplang repo.
