### ISSUE TITLE
Classic EventSources don't work in Release builds using .NET Native (UWP)

### ISSUE THREAD

**Issue by vancem** [dotnet/runtime#10457]
Michael Taron  reported this on 6/5/2018 via E-mail to @vancem and @brianrob 

To repro, using VS create the 'Blank UWP app' and add the following EventSource
```
[EventSource(Name = "Microsoft-StickyNotes")]
public class NoteEventSource : EventSource
{
      public static readonly NoteEventSource Log = new NoteEventSource();
      private NoteEventSource()
      {
      }
      public void AppConstructed() { WriteEvent(1); }
      public void AppSuspended() { WriteEvent(2); }
      public void BootStart() { WriteEvent(3); }
      public void BootStop() { WriteEvent(4); }
}
```
Then add NoteEventSource.Log.AppConstructed() or the other methods to the OnLaunched method.
Use 

PerfView /Providers=*Microsoft-StickyNotes collect

to collect a trace.  You will find that the manifest information is not generated IF YOU USE THE RELEASE BUILD (works OK on debug build).  
```
Event Name | Time MSec | Process Name | Rest
Provider(b8642b6a-9359-532e-c9dc-fccbe92b98b0)/EventID(1) | 2,945.520 | TestUWPApp (34364) | ThreadID="42,024" ProcessorNumber="6"
Provider(b8642b6a-9359-532e-c9dc-fccbe92b98b0)/EventID(3) | 2,945.757 | TestUWPApp (34364) | ThreadID="42,024" ProcessorNumber="6"
Provider(b8642b6a-9359-532e-c9dc-fccbe92b98b0)/EventID(4) | 2,949.862 | TestUWPApp (34364) | ThreadID="42,024" ProcessorNumber="4"   DURATION_MSEC="4.105"
```

Note that I tried using 
```
        public NoteEventSource() : base(EventSourceSettings.EtwSelfDescribingEventFormat) { }
```
To make the EventSource use self-describing events, but that causes a Exception to be thrown (**this seems like an independent but that is also worth fixing**).  

This bug is meant to track this issue (Note it is a .NET Native issue, not a .NET Core issue
@brianrob

**Comment by jkotas** [comment]
Non-actionable in dotnet/runtime

**Comment by brianrob** [comment]
cc: @noahfalk, @sywhang, @josalem
