### ISSUE TITLE
Question on how to properly set OdbcType for OdbcParameter

### ISSUE THREAD

**Issue by Frey-Wang** [dotnet/runtime#104537]
When inserting data using OdbcCommand and command text "insert into table1 (column1) values (?)", we usually set the OdbcType for OdbcParameter. But for cases like decimal type in .NET, we found that the default mapping OdbcType for it is `OdbcType.Numeric` according to https://github.com/dotnet/runtime/blob/4e278fe17f69ea31fbdcbab74ac47ec6fa84914b/src/libraries/System.Data.Odbc/src/System/Data/Odbc/Odbc32.cs#L886-L933

So the question here is that shall we follow the same mapping logic when we want to set the type OdbcParameter? Wondering why this is an internal mapping and why it's mapping from decimal to numeric?

**Comment by roji** [comment]
In many/most databases, numeric and decimal are equivalent types - effectively synonyms of each other; however, it's true that in the SQL standard, they're slightly different, and in your specific database that difference may be meaningful (e.g. [see this blog post](https://learnsql.com/blog/numeric-decimal-data-types-sql/)).

So at the end of the day, it's up to you to choose which OdbcType value to use, based on whether your database cares about the difference (usually not), and if so, based on which type you're actually looking for.

**Comment by Frey-Wang** [comment]
Hi @roji , thanks for the reply! Do you mean there will be cases that only accept decimal, and cases that only accept numeric? In that case, how should we properly handle the type we set for the OdbcParameter? Are there any ways that we can use to test type supports as using the native ODBC method?

**Comment by roji** [comment]
> Do you mean there will be cases that only accept decimal, and cases that only accept numeric?

I don't know enough about the ODBC mappings of databases to know exactly which will accept what value; that's a question that's unrelated to .NET and would need to be checked on a database-by-database basis.

> Are there any ways that we can use to test type supports as using the native ODBC method?

What kind of ways are you looking for? Why not just do actual tests against the databases you plan to support?

**Comment by Frey-Wang** [comment]
Hi @roji , I'm actually working on a generic support for ODBC drivers with .NET, so I can't assume the type from database, but only to leverage exiting methods from System.Data.Odbc.

**Comment by roji** [comment]
@Frey-Wang then it sounds like you need to expose the Numeric vs. Decimal choice to whoever is using you, as these are considered two distinct types in ODBC.

**Comment by Frey-Wang** [comment]
Got it, thanks for the suggestion!

**Comment by Frey-Wang** [comment]
Hi @roji , for cases when the table exists, is it a common pattern to use the ProviderType (from GetSchemaTable) in OdbcParameter (when we write the data into table)?

**Comment by roji** [comment]
@Frey-Wang sure, that could be a good approach.
