### ISSUE TITLE
wrong type when creating a generic whith nullable properties and using it with an enum

### ISSUE THREAD

**Issue by toasteur** [dotnet/runtime#104526]
### Description

i cannot assign a null value to a generic nullable property in a record (or class) i made, using an enum (or any value type) as the generic, but my property is a nullable of the generic

### Reproduction Steps

in a new console program, write this code

```c#
var changes = new PropertyChange<Statuses>
{
    NewValue = null,
    OldValue = null
};

public record PropertyChange<T>
{
    public T? OldValue { get; init; }
    public T? NewValue { get; init; }
}

internal enum Statuses
{
    On,
    Off,
}
```

### Expected behavior

i expect to be able to set null values in my properties

### Actual behavior

i cannot set null values in my properties

### Regression?

same thing for net 7

### Configuration

- NET 8 up to date
- either using vscode ou vstudio 2022 preview
- using windows 10

**Comment by CyrusNajmabadi** [comment]
You can only assign `default` here. If you want to assign `null` then you'll need to put the `where T : class` constraint on your type.

**Comment by huoyaoyuan** [comment]
In C#, nullable reference types and nullable value types (including enum) are different things. Unconstrained generic type means nullable reference type. See more at https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types, https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types and https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#default-constraint.

**Comment by toasteur** [comment]
thanks, i guess i'll have to do what i want in another way.
