### ISSUE TITLE
[browser][MT] PhysicalFileProviderTests test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#104523]
```
[15:00:30] info: [FAIL] Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter
[15:00:30] info: Assert.False() Failure
[15:00:30] info: Expected: False
[15:00:30] info: Actual:   True
[15:00:30] info:    at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter()
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=732111
Build error leg or test failing: WasmTestOnChrome-MT-Microsoft.Extensions.FileProviders.Physical.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/104103

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["SCENARIO=Wasm", "at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=732111
**Error message validated:** `[SCENARIO=Wasm at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/7/2024 4:06:45 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment]
no hits, closing
