### ISSUE TITLE
System.Net.Http.Json has transitive dependency on vulnerable System.Text.Json

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#104669]
The `System.Net.Http.Json` NuGet package has transitive dependency on vulnerable `System.Text.Json` NuGet package. This started giving us build errors due to yesterday's CVE. Notably, it includes the NuGet dependency even on frameworks where System.Text.Json ships inbox (eg. net8.0)

**Comment by eiriktsarpalis** [comment]
That package should have been bumped as well. Does adding an explicit reference to the patched STJ package address the issue?

**Comment by filipnavara** [comment]
>Does adding an explicit reference to the patched STJ package address the issue?

Yes, using that as workaround.

**Comment by ericstj** [comment]
It's by design that we don't update our packages just because a dependency updates.  If we happen to ship System.Net.Http.Json from the 8.0 branch it will be updated.  cc @GrabYourPitchforks @blowdart

**Comment by filipnavara** [comment]
The issue is not about updating System.Net.Http.Json as transitive dependency. The issue is that it unnecessarily links to System.Text.Json on platforms where it's already inbox.

**Comment by filipnavara** [comment]
Hmm... maybe I was mislead to believe that System.Text.Json is inbox though... I just rechecked my local dotnet installation :-/

**Comment by eiriktsarpalis** [comment]
> The issue is that it unnecessarily links to System.Text.Json NuGet on platforms where it's already inbox.

That's orthogonal to the fact that the referenced STJ version is vulnerable though, right? Both STJ proper and SNHJ are shipped in the shared framework.

**Comment by filipnavara** [comment]
> Both STJ proper and SNHJ are shipped in the shared framework.

Are they? I was under the impression that SNHJ is not. If that's the case I can just drop the reference from our builds and be done with it.
