### ISSUE TITLE
[MIPS64] Calling Native Functions from Managed Code

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#1046]
Hi,

Testcase1: [PInvokeTest](https://github.com/xiangzhai/PInvokeTest) to cover all MIPS N64 ABI testcase.

Tetstcase2: [baseservices/threading/interlocked/compareexchange/compareexchange1_cti/compareexchange1_cti.exe](https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/src/baseservices/threading/interlocked/compareexchange/compareexchange1_cti.cs#L133)
MIPS64 return `0`, but X86 and ARM64 return `100`.

This is because MIPS64 special ABI:

![abi](https://user-images.githubusercontent.com/851100/71150993-7793c380-21f8-11ea-9847-3a684e7b5415.png)

But the integer value 23 will be in `W0` register for ARM64.

Reduced testcase:

* libt

```
$ cat t.c
double foo(int a, double b, int c) {
  return (double)a + b + (double)c;
}

$ gcc -c t.c -o t.o
$ gcc -shared -Wl,-z,noexecstack -o libt.so t.o
```

Then `$ sudo cp libt.so` to `/usr/lib` or `/usr/lib64`.

* PInvokeTest

```
$ cat Program.cs 
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace PInvokeTest
{
    class Program
    {
        [DllImport("libt")]
        static extern double foo(int a, double b, int c);

        static void Main(string[] args)
        {
            double a = foo(0, 3.1415926, 0);
            Console.WriteLine("DEBUG: PInvokeTest: " + a.ToString("N7"));
        }
    }
}
```

The output for X64 and ARM64:

```
DEBUG: PInvokeTest: 3.1415926
```

But MIPS64:

```
DEBUG: PInvokeTest: NaN
```

Because MIPS64 use `foo(A0, F13, A2)`:

```
...
foo:                                                                            
        .frame  $fp,32,$31              # vars= 16, regs= 1/0, args= 0, gp= 0   
        .mask   0x40000000,-8                                                   
        .fmask  0x00000000,0                                                    
        .set    noreorder                                                       
        .set    nomacro                                                         
        daddiu  $sp,$sp,-32                                                     
        sd      $fp,24($sp)                                                     
        move    $fp,$sp                                                         
=>      move    $3,$4                   # A0 ($4)                                      
=>      sdc1    $f13,8($fp)             # F13  (FIRST_FP_ARGREG is F12)                                     
=>      move    $2,$6                   # A2 ($6)
...
```

But ARM64 use `foo(W0, D0, W1)`:

```
foo:                                                                            
        sub     sp, sp, #16                                                     
=>      str     w0, [sp, 12]                                                    
=>      str     d0, [sp]                                                        
=>      str     w1, [sp, 8]                                                     
        ldr     w0, [sp, 12]                                                    
        scvtf   d1, w0                                                          
        ldr     d0, [sp]                                                        
        fadd    d1, d1, d0                                                      
        ldr     w0, [sp, 8]                                                     
        scvtf   d0, w0                                                          
        fadd    d0, d1, d0                                                      
        add     sp, sp, 16                                                      
        ret
```

How to fit MIPS64 special ABI by modifing `src/jit/lsramips64.cpp` or `src/vm/jitinterface.cpp` or others?

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
\cc @BruceForstall

**Comment by BruceForstall** [comment]
It's a little hard to see what needs to be done, since we can't see the MIPS64 implementation.

However, in general, much of the ABI processing happens in `fgMorphArgs` and related functions, although it is also spread throughout the JIT in various ways.

cc @CarolEidt

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

Thanks for your teaching!

We created a table for clear description:

| C  | ARM64   | MIPS N64  |  MIPS N64 wrong |
|---|---|---|---|
| fun(int, int, int)  | W0, W1, W2  | A0, A1, A2  | -  |
| fun(float, float, float)  |S0, S1, S2   | F12, F13, F14  | -   |
| fun(int, float, int)  | W0, S0, W1  | A0, F13, A2  | **A0, F12, A1**  |

```
  #define FIRST_FP_ARGREG          REG_F12                                      
  #define LAST_FP_ARGREG           REG_F19
```

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

Thanks for your teaching!

Fxied :)

```
diff --git a/src/jit/morph.cpp b/src/jit/morph.cpp
index 95d49aa..39fea2f 100644
--- a/src/jit/morph.cpp
+++ b/src/jit/morph.cpp
@@ -3638,8 +3638,8 @@ void Compiler::fgInitArgInfo(GenTreeCall* call)
             else
             {
                 // fill in or update the argInfo table
-                nextRegNum = passUsingFloatRegs ? genMapFloatRegArgNumToRegNum(nextFltArgRegNum)
-                                                : genMapIntRegArgNumToRegNum(intArgRegNum);
+                nextRegNum = passUsingFloatRegs ? genMapFloatRegArgNumToRegNum(nextFltArgRegNum MIPS64_ONLY(+ intArgRegNum))
+                                                : genMapIntRegArgNumToRegNum(intArgRegNum MIPS64_ONLY(+ nextFltArgRegNum));
             }
 
 #ifdef _TARGET_AMD64_
diff --git a/src/jit/register_arg_convention.cpp b/src/jit/register_arg_convention.cpp
index 93c3b0b..aa161e7 100644
--- a/src/jit/register_arg_convention.cpp
+++ b/src/jit/register_arg_convention.cpp
@@ -43,6 +43,9 @@ unsigned InitVarDscInfo::allocRegArg(var_types type, unsigned numRegs /* = 1 */)
         // For System V the reg type counters should be independent.
         nextReg(TYP_INT, numRegs);
         nextReg(TYP_FLOAT, numRegs);
+#elif defined(_TARGET_MIPS64_)
+        nextReg(TYP_INT, numRegs);
+        nextReg(TYP_FLOAT, numRegs);
 #else
         // We didn't back-fill a register (on ARM), so skip the number of registers that we allocated.
         nextReg(type, numRegs);
```

Cheers,
Leslie Zhai

**Comment by xiangzhai** [comment]
GC issue relative: https://github.com/dotnet/runtime/issues/7069

> WriteBarrierManager is only for AMD64, and MIPS64 followed the ARM64 way in the very beginning of CoreCLR MIPS64 porting.

> But MIPS64 recently begin to follow the UNIX AMD64 ABI, for example, "copy" the SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR to MIPS64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR for passing and returning struct in the registers. The side effect of the changing is GC could not work correctly, because AMD64 treat gcPtrs differently from ARM64.

\cc @theaoqi @QiaoVanke

**Comment by BruceForstall** [comment]
@xiangzhai Is this a MIPS-specific issue? My understanding is that you track MIPS issues in your own system, and MIPS issues here are only created when you have a specific question for the .NET team (which we could conceivably answer without access to your MIPS source code). Is there a question here?

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

We will open source at https://github.com/gsvm ASAP.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
:mips-redesign
