### ISSUE TITLE
Add `JsonElement.GetPropertyCount()`

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#104692]
## API Proposal

Even though `JsonElement` exposes API for getting the length of a given array, there is no equivalent functionality for objects:

```diff
namespace System.Text.Json;

public partial struct JsonElement
{
     public int GetArrayLength();
+    public int GetPropertyCount();
}
```

## API Usage

```C#
JsonElement element = JsonSerializer.Deserialize<JsonElement>("""{ "foo" : 1, "bar" : 2 }""");
Console.WriteLine(element.GetPropertyCount()); // 2
```

/cc @bartonjs

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Text.Json;

public partial struct JsonElement
{
    public int GetPropertyCount();
}
```

**Comment by eiriktsarpalis** [comment]
The implementation already exists as an internal method, marking up-for-grabs as this is an easy task for anybody looking to contribute.
