### ISSUE TITLE
Metrics "framework" for JIT

### ISSUE THREAD

**Issue by mikedn** [dotnet/runtime#10462]
While hacking the JIT quite often I end up with a simple question - "how many time does X happen?":
* How many JCC instructions are generated?
* How many side effects trees are extracted?
* How many range checks are encountered/removed?

So I end up adding variables, `printf`s and what not. And it's always a quick improvisation, done to be used once and then thrown away.

I think it would be useful to have some basic metrics framework in the JIT that would let people to simply add a line like:
```C++
metrics.Increment("ExtractedSideEffect");
```
pretty much anywhere in the JIT code and have such counters dumped to the console like mem stats are. Or included in disassembly comments so that they show up in diffs and maybe be used by jit-analyze.

Counters should be collected per method and if possible per phase as well. And of course, some basic aggregations should be included as well.

The API should be as easy to use as possible - the above example shows the use of a string as a counter identifier (so I guess the implementation would be using these strings as a hashtable key). This would avoid the need to add a new enum member - such an enum typically resides in a header that when changed triggers the compilation of all JIT files.  Of course, an enum based overload could also provided, that would be useful for counters that are useful long term.

@dotnet/jit-contrib Thoughts?

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:medium
impact:medium

**Comment by jakobbotsch** [comment]
This was fixed by #98653
