### ISSUE TITLE
Can an application structure based on WPF and the Prism framework using IoC be compiled using AOT?

### ISSUE THREAD

**Issue by JusterZhu** [dotnet/runtime#104660]
Currently, I am using .NET 8, WPF, Prism, and designing with an IoC structure. I hope to compile an application using AOT for commercial use. Can it perfectly support AOT? If not, what modifications do I need to make to achieve this? Or is it currently not possible?

**Comment by driver1998** [comment]
WPF would be impossible for now because of its C++/CLI usage, will need to migrate all that to pure C++ or pure C# first.

See https://github.com/dotnet/wpf/discussions/6663 and https://github.com/dotnet/wpf/issues/5305.

**Comment by huoyaoyuan** [comment]
See the tracking issues https://github.com/dotnet/wpf/issues/3811 https://github.com/dotnet/winforms/issues/4649 . The supporting work is not completed yet.

**Comment by JusterZhu** [comment]
Thank you very much for everyone's responses.
