### ISSUE TITLE
Test failure: SslStream_RandomSizeWrites_OK

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#104650]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=735208
Build error leg or test failing: System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "SslStream_RandomSizeWrites_OK",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=735208
**Error message validated:** `[SslStream_RandomSizeWrites_OK`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/10/2024 12:33:51 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[735448](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735448)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735448&view=ms.vss-test-web.build-test-results-tab&runId=18530348&resultId=173059)|dotnet/runtime#104651|
|[735455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735455)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735455&view=ms.vss-test-web.build-test-results-tab&runId=18530054&resultId=219745)|dotnet/runtime#102758|
|[735413](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735413)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735413&view=ms.vss-test-web.build-test-results-tab&runId=18528924&resultId=192118)|dotnet/runtime#104532|
|[735388](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735388)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735388&view=ms.vss-test-web.build-test-results-tab&runId=18528904&resultId=210705)|dotnet/runtime#104629|
|[735360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735360)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735360&view=ms.vss-test-web.build-test-results-tab&runId=18525436&resultId=210455)|dotnet/runtime#104611|
|[735284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735284)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735284&view=ms.vss-test-web.build-test-results-tab&runId=18523964&resultId=207633)|dotnet/runtime#104629|
|[735272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735272)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735272&view=ms.vss-test-web.build-test-results-tab&runId=18523464&resultId=210609)|dotnet/runtime#104649|
|[735208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735208)|dotnet/runtime|[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735208&view=ms.vss-test-web.build-test-results-tab&runId=18520210&resultId=219356)|dotnet/runtime#104251|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|8|8|8|

**Comment by liveans** [comment]
Duplicate of #104605
