### ISSUE TITLE
[browser] tests and fixes for heap larger than 2GB

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#104618]
## WBT
 - set `<EmccMaximumHeapSize>4294901760</EmccMaximumHeapSize>`
 - allocate large arrays in order to deplete memory below 2GB
 - after that
     - test marshaling array of string via `JSImport`
     - call some method many times to trigger interp tier-up and jiterp

## Potential fixes needed
 - convert all results of `Module._malloc` from `int` to `uint`
     - in jiterp
     - in JS interop

See also https://github.com/dotnet/runtime/discussions/99114

**Comment by lewing** [comment]
@kg can you take a look at the jiterp side of things?

**Comment by pavelsavara** [comment]
probably also negative results from `sbrk`

**Comment by pavelsavara** [comment]
closed by https://github.com/dotnet/runtime/pull/109079

**Comment by ilonatommy** [comment]
@pavelsavara should I remove the comment
https://github.com/dotnet/runtime/blob/c2a10452cad4f532c09091b283fa67e91fd10bd4/src/mono/wasm/Wasm.Build.Tests/MemoryTests.cs#L23?
