### ISSUE TITLE
System.Diagnostics - API surface confusion for TagList / ActivityTagsCollection

### ISSUE THREAD

**Issue by abbottdev** [dotnet/runtime#104607]
I love the emphasis that's being put into the work in System.Diagnostics first off, so thank you maintainers!

My difficulty I'm having is, I don't understand why we have/need two distinct classes for a collection of Tags, moreover, why for one API (System.Diagnostics.Activity) vs another (System.Diagnostics.Metric/Counter) the implementation is either: `TagList` or it's `ActivityTagsCollection`.

I feel there should be some clearer either documentation, or implicit operators, or overloads to allow you to use one or both these implementations - but definitely not using distinctly different ones dependent on the API.

My reasoning is simple, if I'm emitting Metrics and ActivityEvents within the same scope, and I want to re-use my `Tags` for the metric and the activity, I can't. 

This could be a lack of understanding of another overload, but I feel as though we need either some overloads that take a tag list, or some implicit operators to reduce this duplicate code. (Note, this is just an example of one tag).

Thanks in advance!

```csharp
using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;
					
public class Program
{
	private static readonly Meter s_meter = new Meter("my-app");
	private static readonly ActivitySource s_source = new ActivitySource("my-source");
	private static readonly Counter<int> s_fruitCounter = s_meter.CreateCounter<int>("my-counter");
	
	public static void Main()
	{
		s_source.CreateActivity("FruitPicker", ActivityKind.Internal);
		
		Console.WriteLine("Hello World");
	}
	
	public static void PickFruit(string fruit, int qty)
	{
		var tags = new TagList
		{
			{ "fruit", "apple" },
		};
		
		s_fruitCounter.Add(1, tags);
		// I can't do this:
		//Activity.Current?.AddEvent(new ActivityEvent("fruit.picked", DateTime.UtcNow, tags));
		
		//Instead I must:
		Activity.Current.AddEvent(
			new ActivityEvent("fruit.picked", DateTime.UtcNow, 
							  new ActivityTagsCollection
							  {
								{ "fruit", "apple" },
							  }));

		Console.WriteLine("Fruit picked!");
	}
}
```

Relevant issue: #68056

**Comment by tommcdon** [comment]
@noahfalk

**Comment by abbottdev** [comment]
Thanks for the tips @tarekgh - I've raised the issue for the ActivityEvent API for now - but I do think there's some merit in looking further afield to using it consistently across all Diagnostics implementations.

I'll raise a doc issue if the associated API change doesn't land! ❤️
