### ISSUE TITLE
[browser] Trigger relink on `EmccMaximumHeapSize` change

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#104790]
Expectations:
- `EmccMaxHeapSize` is set -> relink
- If there's no workload -> fail

Use WBT added in https://github.com/dotnet/runtime/pull/104662.

**Comment by maraf** [comment]
Should we think more broadly? We have plenty properties and items that modify native build and that don't trigger it.

**Comment by ilonatommy** [comment]
> Shouldn't we think more broadly? We have plenty of properties and items that modify native build and that don't trigger it.

Should we go through whole https://github.com/dotnet/runtime/blob/8602bb3b4003dbf5187385f58b29bd87e9468670/src/mono/wasm/build/WasmApp.Common.targets#L6 list and see which ones should rebuild and add them to props json? Or did you have different approach in mind?

**Comment by maraf** [comment]
Probably I guess. It's of a thing to think about. Also, items are involved as well.

- Do we want to always set WasmNativeBuild on behalf of the user? 
- Do we want to do it only for high frequently used props & items?
- Do we want to do it for random props & items? 🙃
- If we don't do it for everything, we should document the behavior.
