### ISSUE TITLE
javascript calling a method with return Task type in .net 9.0 preview6, the returned promise is always in pending state

### ISSUE THREAD

**Issue by dczuo** [dotnet/runtime#104772]
### Description

return Task<T> is fine.

### Reproduction Steps

# c#
```
[JSExport]
internal static Task ReturnTask()
{
    return Task.CompletedTask;
}
```

# javascript
```
let p = (await getAssemblyExports(assemblyName)).namespaceName.className.ReturnTask();
console.log(p);
```

### Expected behavior

PromiseState is resolved

### Actual behavior

PromiseState is pending

### Regression?

Yes, .net8.0 is fine.

### Configuration

.NET SDK：9.0.100-preview.6.24328.19
Microsoft.NETCore.App: 9.0.0-preview.6.24327.7

**Comment by pavelsavara** [comment]
thanks for reporting it @dczuo
