### ISSUE TITLE
[android] Connection issues in Sockets and Functional networking tests

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#104709]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679
Build error leg or test failing: `System.Net.Sockets.Tests`, `System.Net.Ping.Functional.Tests`, `System.Net.NameResolution.Pal.Tests`
Affected CI: `android_[arm/arm64] Release AllSubset_Mono` (`runtime-extra-platforms`)
Range of commits: https://github.com/dotnet/runtime/compare/5795e8c0...a2b7214a

Stack trace example from `System.Net.Sockets.Tests`:
```
07-10 02:54:56.978 12860 18040 I DOTNET  : 1) 	[FAIL] System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint   Test name: System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint
07-10 02:54:56.978 12860 18040 I DOTNET  :    Assembly:  [System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-10 02:54:56.978 12860 18040 I DOTNET  :    Exception messages: System.Net.Sockets.SocketException : Network is unreachable   Exception stack traces:    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass11_0.<SendToAsync>b__0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs:line 92
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.Tasks.Task.<>c.<.cctor>b__292_0(Object obj)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Net.Sockets.Tests.SendTo`1.<Datagram_UDP_ShouldImplicitlyBindLocalEndpoint>d__7[[System.Net.Sockets.Tests.SocketHelperArraySync, System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendTo.cs:line 90
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    Execution time: 0.031889
07-10 02:54:56.978 12860 18040 I DOTNET  : 2) 	[FAIL] System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_AccessDenied_Throws_DoesNotBind   Test name: System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_AccessDenied_Throws_DoesNotBind
07-10 02:54:56.978 12860 18040 I DOTNET  :    Assembly:  [System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-10 02:54:56.978 12860 18040 I DOTNET  :    Exception messages: Assert.Equal() Failure: Values differ
07-10 02:54:56.978 12860 18040 I DOTNET  : Expected: AccessDenied
07-10 02:54:56.978 12860 18040 I DOTNET  : Actual:   NetworkUnreachable   Exception stack traces:    at System.Net.Sockets.Tests.SendTo`1.<Datagram_UDP_AccessDenied_Throws_DoesNotBind>d__8[[System.Net.Sockets.Tests.SocketHelperArraySync, System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendTo.cs:line 105
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    Execution time: 0.0532853
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "'System.Net.Sockets.Tests' END OF WORK ITEM LOG: Command exited with 1",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679
**Error message validated:** `['System.Net.Sockets.Tests' END OF WORK ITEM LOG: Command exited with 1`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/12/2024 8:22:53 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[745393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745393)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745393&view=ms.vss-test-web.build-test-results-tab&runId=18835576&resultId=177014)||
|[743450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743450)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743450&view=ms.vss-test-web.build-test-results-tab&runId=18782772&resultId=178070)||
|[743391](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743391)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743391&view=ms.vss-test-web.build-test-results-tab&runId=18781032&resultId=178070)||
|[743077](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743077)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743077&view=ms.vss-test-web.build-test-results-tab&runId=18767900&resultId=170181)||
|[742744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742744)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742744&view=ms.vss-test-web.build-test-results-tab&runId=18759928&resultId=167992)||
|[742370](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742370)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742370&view=ms.vss-test-web.build-test-results-tab&runId=18746046&resultId=178084)||
|[742110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742110)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742110&view=ms.vss-test-web.build-test-results-tab&runId=18737736&resultId=183429)||
|[741767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741767)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741767&view=ms.vss-test-web.build-test-results-tab&runId=18738008&resultId=178066)||
|[740838](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740838)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740838&view=ms.vss-test-web.build-test-results-tab&runId=18699226&resultId=177055)|dotnet/runtime#104541|
|[740555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740555)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740555&view=ms.vss-test-web.build-test-results-tab&runId=18689072&resultId=116571)|dotnet/runtime#104870|
|[740287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740287)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740287&view=ms.vss-test-web.build-test-results-tab&runId=18679232&resultId=192305)||
|[739967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967&view=ms.vss-test-web.build-test-results-tab&runId=18675492&resultId=178063)||
|[739577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577&view=ms.vss-test-web.build-test-results-tab&runId=18667498&resultId=178063)||
|[739539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539&view=ms.vss-test-web.build-test-results-tab&runId=18666866&resultId=178065)||
|[739937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739937)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739937&view=ms.vss-test-web.build-test-results-tab&runId=18666774&resultId=183422)||
|[738878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738878)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738878&view=ms.vss-test-web.build-test-results-tab&runId=18642120&resultId=203002)|dotnet/runtime#100356|
|[737515](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737515)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737515&view=ms.vss-test-web.build-test-results-tab&runId=18622936&resultId=171246)||
|[735679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679&view=ms.vss-test-web.build-test-results-tab&runId=18539116&resultId=192260)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|18|

**Comment by matouskozak** [comment]
Could the failures be caused by https://github.com/dotnet/runtime/pull/104251 @antonfirsov ?

**Comment by wfurt** [comment]
unlikely @matouskozak .
```c#
       [Fact]
        public async Task Datagram_UDP_ShouldImplicitlyBindLocalEndpoint()
        {
            using var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            byte[] buffer = new byte[32];

            Task sendTask = SendToAsync(socket, new ArraySegment<byte>(buffer), GetGetDummyTestEndpoint());
```

That tests sends data to random site that _should_ follow default route and succeed. So this looks more like environmental problem to me. (or test design) If this is persistent we should investigate of the test systems have full internet access.

**Comment by matouskozak** [comment]
> unlikely @matouskozak .
> 
> ```cs
>        [Fact]
>         public async Task Datagram_UDP_ShouldImplicitlyBindLocalEndpoint()
>         {
>             using var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
>             byte[] buffer = new byte[32];
> 
>             Task sendTask = SendToAsync(socket, new ArraySegment<byte>(buffer), GetGetDummyTestEndpoint());
> ```
> 
> That tests sends data to random site that _should_ follow default route and succeed. So this looks more like environmental problem to me. (or test design) If this is persistent we should investigate of the test systems have full internet access.

Thank you @wfurt for the investigation. I opened an infrastructure issue for it https://github.com/dotnet/dnceng/issues/3405.

**Comment by matouskozak** [comment]
The internet connection to the devices was restored. Closing.
