### ISSUE TITLE
System.Security.Principal.Windows 4.7.0 package too large

### ISSUE THREAD

**Issue by sebastijanstoja** [dotnet/runtime#104785]
Hi folks,

I am writing this email because we found contact as owner of package System.Security.Principal.Windows 4.7.0. The problem is that your package is too large, over 1GB. By the [standard](https://learn.microsoft.com/en-us/azure/devops/artifacts/reference/limits?view=azure-devops)should be around 500MB, and this is causing effect on our repos while onboarding to Dialtone*.
Is there any way to break into multiple or compress to be smallest size (around 500MB)?

If you are not package owner, please provide to appropriate person.

*A Dialtone build is a build run on an on-prem build system which is used if the Azure-based build system is down due to a large-scale Azure failure.
	
Regards,
Sebastijan from Azure Core

**Comment by julealgon** [comment]
Where are these sizes coming from? 

System.Security.Principal.Windows 4.7.0 is 499.11 KB according to NuGet.org itself:
- https://www.nuget.org/packages/System.Security.Principal.Windows/4.7.0
![image](https://github.com/user-attachments/assets/51b18074-1863-492e-a7c8-6d5bae444905)

When contents are extracted, it takes around 2.5MB:
![image](https://github.com/user-attachments/assets/7e0ecdd9-4d70-4e8e-ae58-1b9493d87e04)

**Comment by teo-tsirpanis** [comment]
Also @sebastijanstoja it's likely that you don't need this package if you are not targeting sufficiently new frameworks. I would suggest you to try removing it, rebuild your projects and see if the build fails.

**Comment by sebastijanstoja** [comment]
I need to get some permission to download from the location. I will come back ASAP I got the info.
