### ISSUE TITLE
Irregular tag name of version v9.0.0-preview.6.24327.7

### ISSUE THREAD

**Issue by liesauer** [dotnet/runtime#104784]
### Description

it makes the automated script fails

![image](https://github.com/user-attachments/assets/105c6cbe-dc85-4285-9355-9a1c79a09b30)

### Reproduction Steps

n/a

### Expected behavior

`v9.0.0-preview.6.24327.7`

### Actual behavior

`9.0.0-preview.6.24327.7`

**Comment by carlossanlop** [comment]
@rbhanda

**Comment by carlossanlop** [comment]
Fixed: https://github.com/dotnet/runtime/tree/v9.0.0-preview.6.24327.7

Thanks for reporting!
