### ISSUE TITLE
Indirect dependency on vulnerable System.Text.Json 8.0.0 through Microsoft.Extensions.Configuration.Json

### ISSUE THREAD

**Issue by xC0dex** [dotnet/runtime#104705]
## Description

I have `<NuGetAuditMode>all</NuGetAuditMode>` enabled in my Blazor authentication project. I encountered a high severity vulnerability warning for `System.Text.Json` version 8.0.0 ([Announcement](https://github.com/dotnet/announcements/issues/315)). This package is indirectly installed through `Microsoft.Extensions.Configuration.Json` version 8.0.0 which is installed by using `Microsoft.AspNetCore.Components.WebAssembly` version 8.0.7.
I'm not sure if that's the way it should be.

**Comment by gregsdennis** [comment]
8.0.4 is available. Do you get the warning if you explicitly install that package?

**Comment by xC0dex** [comment]
> 8.0.4 is available. Do you get the warning if you explicitly install that package?

I forgot to mention this. The warning is no longer there when I install 8.0.4 directly.

**Comment by xC0dex** [comment]
Ups, I just saw that https://github.com/dotnet/runtime/issues/104619 would be the right place for mentioning this, sorry!

**Comment by eiriktsarpalis** [comment]
Duplicate of #104669. We don't typically update packages because of a vulnerable dependency. The recommendation is to explicitly reference the patched STJ version.

**Comment by julealgon** [comment]
> The recommendation is to explicitly reference the patched STJ version.

@eiriktsarpalis shouldn't NuGet give lower priority to vulnerable packages when auto-resolving a transitive dependency though?

Why would it explicitly pick a vulnerable version if there is a newer patch version that is not vulnerable that fits the version range criteria for the parent?

If the user doesn't explicitly install the transitive package (which the _vast_ majority of people won't, especially if it's various levels of transitivity deep) then NuGet should just have a safer default.

**Comment by eiriktsarpalis** [comment]
> shouldn't NuGet give lower priority to vulnerable packages when auto-resolving a transitive dependency though?

I don't think this should be done automatically, primarily because NuGet wouldn't be able to determine if the next version contains breaking changes. It should be up to the user to either suppress the warning or explicitly bump the transitive dependency.

**Comment by Clockwork-Muse** [comment]
> if there is a newer patch version that is not vulnerable that fits the version range criteria for the parent?

This should be viable, though, if NuGet had some way to tell the package was vulnerable (or the repository didn't return the vulnerable versions for range searches)?  If we excluded the affected versions from the list the normal resolution should take over?

**Comment by eiriktsarpalis** [comment]
I think this would be an issue to bring up with the NuGet team. My main concern is that versioning semantics are not consistent for all maintainers. NuGet should not implicitly assume that a patch version increment is compatible.

> I'd rather not go back and have to maintain transitive dependencies again explicitly.

That's understandable but to be fair central package management does alleviate that burden to an extent.
