### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#104770]
## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Failed in:** [runtime-coreclr crossgen2 20240710.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736959&view=ms.vss-test-web.build-test-results-tab&runId=18579748&resultId=129406&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64
    - System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 0
Actual:   298
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1276
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=736959
**Error message validated:** `[[FAIL] System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/15/2024 10:03:05 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[741969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741969)|dotnet/runtime|[System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741969&view=ms.vss-test-web.build-test-results-tab&runId=18742344&resultId=110678)|dotnet/runtime#104904|
|[736959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736959)|dotnet/runtime|[System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736959&view=ms.vss-test-web.build-test-results-tab&runId=18579748&resultId=129406)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|2|

**Comment by danmoseley** [comment]
``` 

ERROR_TOO_MANY_POSTS
298 (0x12A)
Too many posts were made to a semaphore.
``` 
...?

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740357&view=ms.vss-test-web.build-test-results-tab&runId=18683066&resultId=129529&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64
    - System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 0
Actual:   298
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1276
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240714.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740735&view=ms.vss-test-web.build-test-results-tab&runId=18696316&resultId=129469&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64
    - System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 0
Actual:   298
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1276
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
@JulieLeeMSFT, this doesnt look like an R2R related issue. Any reason its assigned to me? Anyways @steveisok now owns R2R.

**Comment by MichalStrehovsky** [comment]
> @JulieLeeMSFT, this doesnt look like an R2R related issue. Any reason its assigned to me? Anyways @steveisok now owns R2R.

This is not R2R, we're also seeing it in native AOT legs. I'm closing the native AOT flavor of this bug as a dup of this one.

**Comment by MichalStrehovsky** [comment]
The common theme between the R2R and native AOT failures seems to be Windows Nano Server.

**Comment by JulieLeeMSFT** [comment]
@MichalStrehovsky, thanks for triaging.
Removed assignment to @mangod9.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240715.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742477&view=ms.vss-test-web.build-test-results-tab&runId=18753792&resultId=129555&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64
    - System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(useShellExecute: False)
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 0
Actual:   298
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_BadExe(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1276
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```
