### ISSUE TITLE
Suspicious AppBaseCompilationAssemblyResolver behaviour

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/runtime#1047]
On coverlet there are some scenario where we need to manually search asm to pass to Cecil during instrumentation.
During some user issue analisys we found a strange behaviour for `AppBaseCompilationAssemblyResolver` that lead to a resolution issue.

This is the point https://github.com/tonerdo/coverlet/pull/655#issuecomment-565356297

https://github.com/dotnet/runtime/blob/639122ab5be891bc6d782641e7c9afc2b5d0297c/src/installer/managed/Microsoft.Extensions.DependencyModel/Resolution/AppBaseCompilationAssemblyResolver.cs#L91-L114

Is it correct that in case of empty `Assemblies` resolver return `true` but actually without add any path to assemblies list?

cc: @jhartmann123

**Comment by MarcoRossignoli** [comment]
Any news on this?

**Comment by eerhardt** [comment]
My understanding of the logic is that the method returns `true` if it resolved all the Assemblies in the `CompilationLibrary`. In this case there were no `.Assemblies`, so they all were resolved. The other resolvers that we provide behave that way. Here are the other 2:

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/managed/Microsoft.Extensions.DependencyModel/Resolution/PackageCompilationAssemblyResolver.cs#L109-L125

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/managed/Microsoft.Extensions.DependencyModel/Resolution/ReferenceAssemblyPathResolver.cs#L47-L56

If you want/need to handle this situation separately, I would advise injecting your own resolver to the beginning of the list when invoking `CompilationLibrary.ResolveReferencePaths(params ICompilationAssemblyResolver[] customResolvers)`.

**Comment by eerhardt** [comment]
Note that if the resolvers didn’t have this behavior, an exception would be thrown any time this situation occurred. 

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/managed/Microsoft.Extensions.DependencyModel/CompilationLibrary.cs#L82

**Comment by MarcoRossignoli** [comment]
Understood thank you @eerhardt!
