### ISSUE TITLE
Optimize placement of VZEROUPPER

### ISSUE THREAD

**Issue by voinokin** [dotnet/runtime#10484]
Which rules CLR JIT uses to place VZEROUPPER, and how do I opt-out ?

The live example is - one flavor of distribution sorting algorithm uses insertion sort subroutine for basic case sorting of small buckets, and it gets called quite often esp. for of 2- and 3-record cases.  The insertion sort subroutine itself is highly optimized - it uses SIMD registers (XMMs in my case), HW intrinsics and just basic RSP-based stack frame for couple values. Still VZEROUPPER is generated at the beginning and at the end of subroutine, which adds some perfmormance hit. There is natural desire to avoid such penalty knowing that caller will always be other CLR JITted code, and all nested method invocations are inlined (checked this manually).

category:cq
theme:vector-codegen
skill-level:expert
cost:medium

**Comment by pentp** [comment]
Linking similar issue with some overlapping discussion: #11496

**Comment by BruceForstall** [comment]
Going to close this in favor of #11496
