### ISSUE TITLE
JIT: SVE Cleanup - Remove `unsafe` from APIs that do not use pointers.

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#104845]
Because we have been copying and pasting from the generated code for SVE, the generation always marked the APIs as `unsafe`. We need to remove `unsafe` from them if the API does not use any pointers.

Relevant files:
- src\libraries\System.Runtime.Intrinsics\ref\System.Runtime.Intrinsics.cs
- src\libraries\System.Private.CoreLib\src\System\Runtime\Intrinsics\Arm\Sve.PlatformNotSupported.cs
- src\System\Runtime\Intrinsics\Arm\Sve.cs

**Comment by a74nh** [comment]
I recommend doing this after making the files alphabetical in https://github.com/dotnet/runtime/issues/104834

**Comment by a74nh** [comment]
priority:2 for RC1 snap : User visible API

**Comment by tannergooding** [comment]
This is more rather priority 3, or could even be pushed out to .NET 10.

Marking an API as `unsafe` has no impact to the public signature, it simply allows the internal implementation to use pointers and the public signature to contain pointers.

In many cases we've just marked the entire class as `unsafe` to simplify long term revisions/changes to known lowlevel code.

**Comment by JulieLeeMSFT** [comment]
Pushing out to .NET 10 because we have many issues for RC1 snap.
