### ISSUE TITLE
LoggerMessage generator fails with primary constructor logger, if the logger is used elsewhere

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#104801]
### Description

Even with the recent changes to support primary constructors with the `[LoggerMessage]` source generator, invalid code is generated if the primary constructor `ILogger` is accessed in user code (which results in the compiler generating a backing field for the parameter).

### Reproduction Steps

csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0-preview.6.*" />
    </ItemGroup>

</Project>
```

C.cs:

```c#
using Microsoft.Extensions.Logging;

partial class C(ILogger<C> logger)
{
    [LoggerMessage(LogLevel.Information)]
    partial void Log();

    void M()
    {
        logger.LogInformation("M");
    }
}
```

### Expected behavior

The generator generates valid and working code.

### Actual behavior

Compilation fails with:

> LoggerMessage.g.cs(13,17,13,18): error CS1525: Invalid expression term '<'
> LoggerMessage.g.cs(15,31,15,32): error CS1525: Invalid expression term '<'
> LoggerMessage.g.cs(13,25,13,26): error CS0103: The name 'P' does not exist in the current context
> LoggerMessage.g.cs(15,39,15,40): error CS0103: The name 'P' does not exist in the current context

The generated code looks like this:

```c#
// <auto-generated/>
#nullable enable

    partial class C
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "9.0.10.32707")]
        private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.Exception?> __LogCallback =
            global::Microsoft.Extensions.Logging.LoggerMessage.Define(global::Microsoft.Extensions.Logging.LogLevel.Information, new global::Microsoft.Extensions.Logging.EventId(1579320335, nameof(Log)), "", new global::Microsoft.Extensions.Logging.LogDefineOptions() { SkipEnabledCheck = true }); 

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "9.0.10.32707")]
        partial void Log()
        {
            if (<logger>P.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
            {
                __LogCallback(<logger>P, null);
            }
        }
    }
```

### Possible fix

This could probably be fixed by checking `IFieldSymbol.CanBeReferencedByName` inside `FindLoggerField` in the generator code.

**Comment by tarekgh** [comment]
Thanks @svick for your report. 

https://github.com/dotnet/runtime/issues/91121
https://github.com/dotnet/runtime/pull/101660

CC @kimsey0
