### ISSUE TITLE
JIT: SVE Cleanup - In the importer, always `ConvertToMask` on SVE APIs that require a mask.

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#104836]
Discussion: https://github.com/dotnet/runtime/pull/104704#discussion_r1674822469

Code:
```cpp
        if (!varTypeIsMask(op))
        {
            op = gtNewSimdCvtVectorToMaskNode(TYP_MASK, op, simdBaseJitType, simdSize);
        }
```

The idea is that we shouldn't have to check for `varTypeIsMask(op)`; meaning at this point, `op` should be returning `TYP_SIMD`. Therefore, we should always add a `ConvertToMask` node:
```cpp
        assert(varTypeIsSIMD(op));
        op = gtNewSimdCvtVectorToMaskNode(TYP_MASK, op, simdBaseJitType, simdSize);
```

**Comment by a74nh** [comment]
priority:3 for RC1 snap : Code is correct but not optimal.
