### ISSUE TITLE
Accessing constructors with UnsafeAccessor throws exception on generic types in .NET9

### ISSUE THREAD

**Issue by yushroom** [dotnet/runtime#104879]
### Description

Accessing constructors with UnsafeAccessor throws exception on generic types in .NET9 preview 6.

### Reproduction Steps

```csharp
using System.Runtime.CompilerServices;

class Program
{
    static List<int> CallConstructorByUnsafeAccessor()
    {
        var c = (List<int>)RuntimeHelpers.GetUninitializedObject(typeof(List<int>));
        CtorAsMethod(c);
        return c;

        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = ".ctor")]
        extern static void CtorAsMethod(List<int> c);
    }

    static void Main()
    {
        var c = CallConstructorByUnsafeAccessor();
        Console.WriteLine(c.Count);
    }
}

```

### Expected behavior

The code works on .NET 8 and .NET 9

### Actual behavior

- No error on .NET 8
- Fails on .NET 9 preview 6

> Unhandled exception. System.InvalidProgramException: Generic type constraints do not match.

Also fails with NativeAOT

`dotnet publish -r win-x64 -c Debug /p:PublishAot=true`

> EXEC : error : Index was outside the bounds of the array.

### Regression?

Yes as it works on .NET 8

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
So most generic support was deemed broken in .NET 8. I tried to capture that in https://github.com/dotnet/runtime/issues/89439. It clearly wasn't properly expressed nor was the fact that generic parameters now must match in location and number. The documentation for [`UnsafeAccessor` was recently updated specifically talking about generics](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.unsafeaccessorattribute#remarks).

For context, this was part of type parameters must be type parameters and method parameters must be method parameters so signature matching was simpler. The result is that we match signatures precisely. For the above scenario it is relatively simple and we could make it work, but it quickly becomes much more complicated when generic parameters are involved. I'm inclined to report a breaking change issue here for .NET 8 instead.

The workaround is to follow the supported generic way to handle this:
```csharp
    static List<int> CallConstructorByUnsafeAccessor()
    {
        var c = (List<int>)RuntimeHelpers.GetUninitializedObject(typeof(List<int>));
        Accessor<int>.CtorAsMethod(c);
        return c;
    }

    class Accessor<T>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = ".ctor")]
        public extern static void CtorAsMethod(List<T> c);
    }

    static void Main(string[] args)
    {
        var c = CallConstructorByUnsafeAccessor();
        Console.WriteLine(c.Count);
    }
```

**Comment by AaronRobinsonMSFT** [comment]
>  I'm inclined to report a breaking change issue here for .NET 8 instead.

Re-reading through the history of the original feature PR, specifically [here](https://github.com/dotnet/runtime/issues/81741#issuecomment-1648751339), this sounds like this could be considered a bug. I genuinely don't think that is fair so think a breaking change issue is more appropriate because it wasn't blocked in .NET 8.

**Comment by AaronRobinsonMSFT** [comment]
After some additional discussion, we've decide to document this as a breaking change. It can be tracked at https://github.com/dotnet/docs/issues/41769.
