### ISSUE TITLE
JIT: SVE Cleanup - Remove unneeded comments from API surface area

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#104846]
In these files:
- src\libraries\System.Private.CoreLib\src\System\Runtime\Intrinsics\Arm\Sve.PlatformNotSupported.cs
- src\System\Runtime\Intrinsics\Arm\Sve.cs

There are comments related to the SVE APIs that are not part of the summary blocks.
Example:
```csharp
        ///  CreateTrueMaskDouble : Set predicate elements to true

        /// <summary>
        /// svbool_t svptrue_pat_b8(enum svpattern pattern)
        ///   PTRUE Presult.B, pattern
        /// </summary>
        public static unsafe Vector<double> CreateTrueMaskDouble([ConstantExpected] SveMaskPattern pattern = SveMaskPattern.All) => CreateTrueMaskDouble(pattern);
```

We need to remove the `        ///  CreateTrueMaskDouble : Set predicate elements to true` line.

**Comment by a74nh** [comment]
> We need to remove the ` /// CreateTrueMaskDouble : Set predicate elements to true` line.

We just change it to a double quote ` // CreateTrueMaskDouble : Set predicate elements to true` ??

**Comment by a74nh** [comment]
priority:2 for RC1 snap : End users will see the API
