### ISSUE TITLE
Add a type static class  at the CLR level

### ISSUE THREAD

**Issue by ZhuYajunFly** [dotnet/runtime#104869]
Add a type static class  at the CLR level，when any app the  static class load in CLR, then all apps get only one Instance.
For multi-threaded safety，may add a key-word to decorate the static class.

For detail:
https://github.com/ZhuYajunFly/StaticClassDemo

I creat three project,the GlobalData provide data to other project, the App1 and App2 use the static class name of ShareData, i hope the static data in clr only one instance,but not.For easy to show,the static class only has one prop.
![image](https://github.com/user-attachments/assets/ad90cd1e-e206-4488-9afe-05456a5996c6)
![image](https://github.com/user-attachments/assets/c66f9ad1-8f56-41ea-8dbf-8df88503eb87)
The App1 and App2 both  ref the GlobalData project,gui is simple,a textbox to show,two btns for read and write data.
![image](https://github.com/user-attachments/assets/99d2e4a7-1db8-46db-8d72-a75a7f640118)
![image](https://github.com/user-attachments/assets/aecce30c-4d16-42a5-afca-0f344d1c8e97)
When you read write data,you will find the static class are diff instance in clr.
![image](https://github.com/user-attachments/assets/4a96df6c-433d-45b2-8a4c-0f261f98934f)
So,I hope has a specicl static class in clr only one instance for diff apps to share datas,For multi-threaded safety，may add a key-word to decorate the static class.I know someting about redis,but it a little bit heavy,and use it not like static class with flexible  and strong type cheack.

**Comment by ZhuYajunFly** [comment]
For multi-threaded safety，may add a key-word to decorate class.

**Comment by huoyaoyuan** [comment]
Can you explain what does "type static class" mean? It's unclear in the original post.

**Comment by timcassell** [comment]
Do you mean the [Singleton Pattern](https://www.c-sharpcorner.com/UploadFile/8911c4/singleton-design-pattern-in-C-Sharp/)?

**Comment by ZhuYajunFly** [comment]
> Do you mean the [Singleton Pattern](https://www.c-sharpcorner.com/UploadFile/8911c4/singleton-design-pattern-in-C-Sharp/)?

thank you,singleton maybe not work with diff app to share data,because the static class not work.

**Comment by ZhuYajunFly** [comment]
> Can you explain what does "type static class" mean? It's unclear in the original post.

thank you, i add more detil in head,and to example. i hope you can understand witch i want that .

**Comment by timcassell** [comment]
Oh, you want to share data between multiple processes. I think you can do that using the singleton pattern and a file (for serialized data) and a named [Mutex](https://learn.microsoft.com/en-us/dotnet/api/system.threading.mutex). I'm not sure this is a good thing to add to the runtime.

**Comment by ZhuYajunFly** [comment]
> Oh, you want to share data between multiple processes. I think you can do that using the singleton pattern and a file (for serialized data) and a named [Mutex](https://learn.microsoft.com/en-us/dotnet/api/system.threading.mutex). I'm not sure this is a good thing to add to the runtime.

Sure,serialized data should work,but not flexible and not like memory-exchange that so high-performance.If one day,that you can easy to exchange data with a special static class(by class name and namespace),oh, so amazing!

**Comment by huoyaoyuan** [comment]
So you are asking for static data sharing between different processes.

It's indeed a complex problem that can't be solved with such simple solution. How about the scope of sharing? How to handle processes with different privilege? How to verify the partner process is trusted, not malicious? It will also face the same safety problem with the already-deprecated implicit remoting and binary serialization.

The best solution would be provided by the operating system, to properly share R/W data between processes. We can then build some API upon it at best.

**Comment by ZhuYajunFly** [comment]
> So you are asking for static data sharing between different processes.
> 
> It's indeed a complex problem that can't be solved with such simple solution. How about the scope of sharing? How to handle processes with different privilege? How to verify the partner process is trusted, not malicious? It will also face the same safety problem with the already-deprecated implicit remoting and binary serialization.
> 
> The best solution would be provided by the operating system, to properly share R/W data between processes. We can then build some API upon it at best.

yes,with multi-threaded safety, not easy,but we can limit only .net apps can R/W,clr runtime know which app which thread use it,then can do something.also,we can use private prop,use method to R/W data , the method use lock to protect data multi-threaded safety;

**Comment by ZhuYajunFly** [comment]
> So you are asking for static data sharing between different processes.
> 
> It's indeed a complex problem that can't be solved with such simple solution. How about the scope of sharing? How to handle processes with different privilege? How to verify the partner process is trusted, not malicious? How about compatibility between different CLR versions? It will also face the same safety problem with the already-deprecated implicit remoting and binary serialization.
> 
> The best solution would be provided by the operating system, to properly share R/W data between processes. We can then build some API upon it at best.

https://en.wikipedia.org/wiki/Shared_memory   Shared memory，it work like.but now  Shared memory use it not easy,should more improve it.

**Comment by huoyaoyuan** [comment]
> Shared memory，it work like.but now  Shared memory use it not easy,should more improve it.

It's not shared memory to be not easy. It's the **problem itself** to be complex.

Shared memory is not fully owned by current process, so it's not a simple work or even impossible to adapt it with object and GC model.

**Comment by AaronRobinsonMSFT** [comment]
Runtime instances are independent of one another from each runtime's perspective. Having a built-in shared state mechanism is a non-goal of .NET. Creating a solution using a [memory mapped file](https://learn.microsoft.com/dotnet/standard/io/memory-mapped-files) is the recommendation.
