### ISSUE TITLE
Move the HWIntrinsic Load/Store operations to use GenTreeIndir nodes

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#10488]
Currently, the x86 Hardware Intrinsics handle the load/store operations directly. This was done both for quick bring up and in order to easily represent the various new memory operation types.

However, it would be ideal if we could merge this functionality back in with the normal Indir handling that already exists.

category:implementation
theme:vector-codegen
skill-level:expert
cost:extra-large

**Comment by BruceForstall** [comment]
I'm going to go ahead and close this, and if we have new proposals, we can create new issues or re-open as necessary.
