### ISSUE TITLE
CI failure for System.Net.Security.Tests.TelemetryTest

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#104886]
This networking test failed running on CoreCLR while my PR only touched files in the NativeAOT runtime.

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=740741
Build error leg or test failing: System.Net.Security.Tests.TelemetryTest.SuccessfulHandshake_ActivityRecorded
Pull request: https://github.com/dotnet/runtime/pull/104851

## Error Message

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 2
Actual:   1
   at System.Net.Test.Common.ActivityRecorder.VerifyActivityRecorded(Int32 times) in /_/src/libraries/Common/tests/System/Net/ActivityRecorder.cs:line 73
   at System.Net.Security.Tests.TelemetryTest.<>c.<<SuccessfulHandshake_ActivityRecorded>b__3_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 50
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65
Child process:

System.Net.Security.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <SuccessfulHandshake_ActivityRecorded>b__3_0(System.String)

```json
{
  "ErrorMessage": "src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 50",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=740741
**Error message validated:** `[src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 50`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/15/2024 10:17:09 AM UTC

**Comment by rzikm** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/104883
