### ISSUE TITLE
Error in blazor 8 intective auto mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#104814]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-in-blazor-8-intective-auto-mode/10698113)._

---
[severity:I'm unable to use this version] [regression]
I am getting this error "raw cwrap mono_wasm_copy_managed_pointer not found" from the jiterpreter.ts in console browser in my Blazor 8 interactive auto mode when I reload the page 

---
#### Feedback Bot on 7/7/2024, 07:05 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@lewing FYI
