### ISSUE TITLE
ICorDebugRegisterSet.GetThreadContext fails on macOS arm64

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#104816]
### Description

In .NET 9 preview 7 builds, ICorDebugRegisterSet.GetThreadContext is failing on macOS arm64 with HRESULT_FROM_WIN32(ERROR_INSUFFICIENT_BUFFER) (-2147024774). 

### Reproduction Steps

1. Install latest .NET
2. Create a console application
3. Open the folder in VS Code
4. Set a breakpoint on the Console.WriteLine line
5. Run

### Expected behavior

Debugger should successfully produce a call stack

### Actual behavior

Debugger fails to produce a call stack when the breakpoint is hit

### Regression?

Regression from preview 6

**Comment by tommcdon** [comment]
Regression caused by https://github.com/dotnet/runtime/pull/103801
