### ISSUE TITLE
System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch failure

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#104905]
```
System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(value: WeakReference { IsAlive = True, Target = https://dot.net/, TrackResurrection = True }, _: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue]) [FAIL]
  Assert.Equal() Failure: Values differ
  Expected: 242
  Actual:   85
  Stack Trace:
    /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/FormattedObject/BasicObjectTests.cs(40,0): at System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(Object value, TypeSerializableValue[] _)
        at System.Object.InvokeStub_BasicObjectTests.BasicObjectsRoundTripAndMatch(Object , Span`1 )
    /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(136,0): at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=739427
Build error leg or test failing: System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch
Pull request: https://github.com/dotnet/runtime/pull/104749

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["BasicObjectsRoundTripAndMatch", "Expected:"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 8/14/2024 10:23:52 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[791827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=791827)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=791827&view=ms.vss-test-web.build-test-results-tab&runId=20365018&resultId=149118)|dotnet/runtime#107117|
|[790572](https://dev.azure.com/dnceng-public/public/_build/results?buildId=790572)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=790572&view=ms.vss-test-web.build-test-results-tab&runId=20323930&resultId=147002)|dotnet/runtime#106965|
|[790309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=790309)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=790309&view=ms.vss-test-web.build-test-results-tab&runId=20316014&resultId=130697)|dotnet/runtime#107050|
|[784110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=784110)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=784110&view=ms.vss-test-web.build-test-results-tab&runId=20129664&resultId=139405)|dotnet/runtime#106409|
|[779942](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779942)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779942&view=ms.vss-test-web.build-test-results-tab&runId=19993814&resultId=144559)|dotnet/runtime#106613|
|[779313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779313)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779313&view=ms.vss-test-web.build-test-results-tab&runId=19971070&resultId=137267)|dotnet/runtime#106578|
|[777681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777681)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777681&view=ms.vss-test-web.build-test-results-tab&runId=19915124&resultId=130904)||
|[777119](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777119)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777119&view=ms.vss-test-web.build-test-results-tab&runId=19897378&resultId=143134)|dotnet/runtime#106474|
|[776563](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776563)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776563&view=ms.vss-test-web.build-test-results-tab&runId=19875454&resultId=175614)|dotnet/runtime#106437|
|[776146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776146)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776146&view=ms.vss-test-web.build-test-results-tab&runId=19864872&resultId=136727)|dotnet/runtime#106416|
|[775754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775754)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775754&view=ms.vss-test-web.build-test-results-tab&runId=19853312&resultId=151554)|dotnet/runtime#106398|
|[775106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775106)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775106&view=ms.vss-test-web.build-test-results-tab&runId=19828364&resultId=131799)|dotnet/runtime#106218|
|[769299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769299)|dotnet/runtime|[System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769299&view=ms.vss-test-web.build-test-results-tab&runId=19637904&resultId=135356)|dotnet/runtime#106108|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|3|13|

**Comment by ericstj** [comment]
Adding some detail about the failure.  Seems this was deserializing a WeakReference object:
```
System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(value: WeakReference { IsAlive = True, Target = https://dot.net/, TrackResurrection = True }, _: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue]) [FAIL]
      Assert.Equal() Failure: Values differ
      Expected: 242
      Actual:   85
      Stack Trace:
        /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/FormattedObject/BasicObjectTests.cs(40,0): at System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(Object value, TypeSerializableValue[] _)
           at System.Object.InvokeStub_BasicObjectTests.BasicObjectsRoundTripAndMatch(Object , Span`1 )
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(136,0): at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-104749-merge-d99a4fd2282b40b389/System.Resources.Extensions.BinaryFormat.Tests/1/console.d365210d.log?helixlogtype=result

Here's the corresponding test data:
https://github.com/dotnet/runtime/blob/66ae90f3b7ec4f13fffcd71913eca0b45777e58c/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/BinaryFormatterTestData.cs#L717-L720

Seems pretty odd to me that this would be flaky.  Any theories, @adamsitnik?

**Comment by adamsitnik** [comment]
> Any theories, @adamsitnik?

The test failed when comparing the lengths of a streams that contained:
- serialized `WeakReference`
- deserialized and serialized `WeakReference`

https://github.com/dotnet/runtime/blob/bec59708182682410afb4014a729149c1cf3439f/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/FormattedObject/BasicObjectTests.cs#L39-L40

My theory: `WeakReference` was no longer pointing to an alive object when the value was serialized to another stream, so the content was different and hence the stream length difference.

Repro:

```cs
using System.Runtime.Serialization.Formatters.Binary;

Uri? dotnetUri = new("https://dot.net");
WeakReference weakReference = new(dotnetUri, true);

BinaryFormatter binaryFormatter = new();
MemoryStream memoryStream = new();

binaryFormatter.Serialize(memoryStream, weakReference);
Console.WriteLine($"IsAlive: {weakReference.IsAlive}, Length: {memoryStream.Length}");

memoryStream.Position = 0;
memoryStream.SetLength(0);

dotnetUri = null;

do
{
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
} while (weakReference.IsAlive);

binaryFormatter.Serialize(memoryStream, weakReference);
Console.WriteLine($"IsAlive: {weakReference.IsAlive}, Length: {memoryStream.Length}");
```

```log
IsAlive: True, Length: 242
IsAlive: False, Length: 85
```

**Comment by stephentoub** [comment]
I just hit this in https://github.com/dotnet/runtime/pull/105339, which was opened after and which includes the fix for this issue...
```
Data Driven SubResults
❌ System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(value: WeakReference { IsAlive = True, Target = https://dot.net/, TrackResurrection = True }, _: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue])
Exception Message
Assert.Equal() Failure: Values differ
Expected: 242
Actual:   85
Stack Trace
   at System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(Object value, TypeSerializableValue[] _) in /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/FormattedObject/BasicObjectTests.cs:line 40
   at System.Object.InvokeStub_BasicObjectTests.BasicObjectsRoundTripAndMatch(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 136
```

**Comment by adamsitnik** [comment]
In #105072 I've rooted the target of `WeakReference` by storing it in a static field:

https://github.com/dotnet/runtime/blob/a47eeecf12361751b494e83fd49adc9a28969687/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/BinaryFormatterTestData.cs#L55-L58

https://github.com/dotnet/runtime/blob/a47eeecf12361751b494e83fd49adc9a28969687/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/Legacy/BinaryFormatterTestData.cs#L723

I was expecting that this is going to prevent the GC from feeing it.

@stephentoub do you have any idea what I am missing here?

**Comment by stephentoub** [comment]
Thanks. Let's close this again and see if any further occurrences are reported separately. It's possible there was some kind of staleness happening.

**Comment by mdh1418** [comment]
I hit this in #106040 
```
Data Driven SubResults
❌ System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(value: WeakReference`1 { }, _: [BinaryFormatTests.TypeSerializableValue, BinaryFormatTests.TypeSerializableValue])
Exception Message
Assert.Equal() Failure: Values differ
Expected: 479
Actual:   407
Stack Trace
   at System.Resources.Extensions.Tests.FormattedObject.BasicObjectTests.BasicObjectsRoundTripAndMatch(Object value, TypeSerializableValue[] _) in /_/src/libraries/System.Resources.Extensions/tests/BinaryFormatTests/FormattedObject/BasicObjectTests.cs:line 40
   at InvokeStub_BasicObjectTests.BasicObjectsRoundTripAndMatch(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 136
```

Config: net9.0-windows-Release-x64-coreclr_checked-Windows.10.Amd64.Open

**Comment by adamsitnik** [comment]
I am moving it to 10 as it's not a product issue, but a flaky test.
