### ISSUE TITLE
Inconsistency between documentation and implementation for EnumerationOptions.MaxRecursionDepth

### ISSUE THREAD

**Issue by rameel** [dotnet/runtime#104997]
In the documentation, it is stated that if `MaxRecursionDepth` is set to a negative number, the default value `int.MaxValue` is used. However, the current implementation throws an exception when attempting to assign a negative value.

[Documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.maxrecursiondepth?view=net-8.0)
[EnumerationOptions.cs](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Private.CoreLib/src/System/IO/EnumerationOptions.cs#L91)
```csharp
/// <summary>Gets or sets a value that indicates the maximum directory depth to recurse while enumerating, when <see cref="RecurseSubdirectories" /> is set to <see langword="true" />.</summary>
/// <value>A number that represents the maximum directory depth to recurse while enumerating. The default value is <see cref="int.MaxValue" />.</value>
/// <remarks>If <see cref="MaxRecursionDepth" /> is set to a negative number, the default value <see cref="int.MaxValue" /> is used.
/// If <see cref="MaxRecursionDepth" /> is set to zero, enumeration returns the contents of the initial directory.</remarks>
public int MaxRecursionDepth
{
    get => _maxRecursionDepth;
    set
    {
        ArgumentOutOfRangeException.ThrowIfNegative(value);
        _maxRecursionDepth = value;
    }
}
```

**Expected Behavior:**
When `MaxRecursionDepth` is set to a negative number, it should be assigned the default value `int.MaxValue` as per the documentation.

**Actual Behavior:**
An `ArgumentOutOfRangeException` is thrown when `MaxRecursionDepth` is set to a negative number.

**Comment by adamsitnik** [comment]
Hi @rameel 

I've checked and this code was added in https://github.com/dotnet/runtime/pull/48148 and was always throwing for negative values. Since `int.MaxValue` is the default value, there is no need to use negative numbers to set that default. So I am just going to update the docs.

Thanks!
