### ISSUE TITLE
Incompatibility between ref and lib binary versions for System.Componentmodel.Annotations nuget package

### ISSUE THREAD

**Issue by aparajit-pratap** [dotnet/runtime#104910]
The `System.ComponentModel.Annotations` [nuget package](https://www.nuget.org/packages/System.ComponentModel.Annotations) has 2 incompatible compile time and runtime versions of the DLL. The binary version in the `ref` subfolder is 4.2.0, while the one in the `lib` subfolder is 4.2.1, which are seemingly binary incompatible from testing it. 

At runtime in my app targeting .NET 4.8, I get `filenotfound` exception, that the 4.2.0 version of the assembly cannot be found, due to which one either needs to use assembly binding redirects in their app or implement a custom assembly resolver to load the appropriate assembly at runtime.

**Comment by tarekgh** [comment]
In the package I see both the ref and the lib having the same version `4.2.1.0`. This is from the Nuget package version `4.7.0`. 

My question is, why are you referencing the NuGet package at all in .NET Framework and not using the assembly reference from 4.8? The libraries in the NuGet package are type-forward the types anyway and not carrying any implementation.

**Comment by tarekgh** [comment]
CC @eiriktsarpalis @ericstj

**Comment by aparajit-pratap** [comment]
@tarekgh a lot of nuget package versions including 4.7.0 contain different versions of the DLL:
![image](https://github.com/user-attachments/assets/c9cdd22c-72d3-4f87-b951-6647cdc6b80a)

I realize this issue has also been called out in the past: https://github.com/dotnet/runtime/issues/61778

**Comment by tarekgh** [comment]
@aparajit-pratap thanks for your response. Could you please answer the question I mentioned earlier?  `Why are you referencing the NuGet package at all in .NET Framework and not using the assembly reference from 4.8?`

**Comment by aparajit-pratap** [comment]
> My question is, why are you referencing the NuGet package at all in .NET Framework and not using the assembly reference from 4.8? 
I'm referencing the latest nuget package, version 5.0 from my multi-targeted solution targeting both .net framework and .net 8.0. I don't see issues with my app running in .net 8 as I think the .NET runtime in .NET Core and higher resolve assemblies differently.

**Comment by tarekgh** [comment]
Thanks again. 

The comment https://github.com/dotnet/runtime/issues/41221#issuecomment-680069034 describes you need to have a binding redirect on .NET Framework as it looks this version differences are intended. https://github.com/dotnet/corefx/blob/8b6f40185c25372943ac4a8ab94b860008ad2120/src/System.ComponentModel.Annotations/ref/System.ComponentModel.Annotations.csproj#L6

**Comment by aparajit-pratap** [comment]
@tarekgh is this documented somewhere more publicly other than on an issue that has already been closed? Is this common among other packages? I have wasted numerous development cycles narrowing it down.

**Comment by tarekgh** [comment]
Sorry @aparajit-pratap for inconvenience. I'll try to double check if there is any doc describing the situation. We can use https://github.com/dotnet/runtime/issues/61778 to track adding some public doc.
