### ISSUE TITLE
[browser][AOT][ST] table index is out of bounds

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#105010]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=743972
Build error leg or test failing: WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/104758

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "MONO_WASM: table index is out of bounds",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=743972
**Error message validated:** `[MONO_WASM: table index is out of bounds`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/17/2024 5:32:46 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[773348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773348)|dotnet/runtime|[WasmTestOnV8-ST-System.Linq.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773348&view=ms.vss-test-web.build-test-results-tab&runId=19771808&resultId=136406)||
|[772273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772273)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772273&view=ms.vss-test-web.build-test-results-tab&runId=19735924&resultId=100001)|dotnet/runtime#106167|
|[763399](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763399)|dotnet/runtime|[WasmTestOnV8-ST-System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763399&view=ms.vss-test-web.build-test-results-tab&runId=19608002&resultId=144345)||
|[767427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767427)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767427&view=ms.vss-test-web.build-test-results-tab&runId=19566382&resultId=100001)|dotnet/runtime#106026|
|[766025](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766025)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766025&view=ms.vss-test-web.build-test-results-tab&runId=19519712&resultId=100001)|dotnet/runtime#105802|
|[765436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765436)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765436&view=ms.vss-test-web.build-test-results-tab&runId=19490208&resultId=100001)|dotnet/runtime#105909|
|[765139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765139)|dotnet/runtime|[WasmTestOnChrome-ST-System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765139&view=ms.vss-test-web.build-test-results-tab&runId=19472016&resultId=138147)||
|[762147](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762147)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762147&view=ms.vss-test-web.build-test-results-tab&runId=19365822&resultId=100001)|dotnet/runtime#104562|
|[758343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758343)|dotnet/runtime|[WasmTestOnChrome-ST-System.Linq.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758343&view=ms.vss-test-web.build-test-results-tab&runId=19243522&resultId=149441)||
|[756458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756458)|dotnet/runtime|[WasmTestOnV8-ST-System.Formats.Asn1.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756458&view=ms.vss-test-web.build-test-results-tab&runId=19179240&resultId=147080)||
|[755747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747)|dotnet/runtime|[WasmTestOnV8-ST-System.Linq.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747&view=ms.vss-test-web.build-test-results-tab&runId=19160710&resultId=142607)||
|[752637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752637)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752637&view=ms.vss-test-web.build-test-results-tab&runId=19068312&resultId=100001)|dotnet/runtime#105299|
|[751970](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751970)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751970&view=ms.vss-test-web.build-test-results-tab&runId=19048354&resultId=100001)|dotnet/runtime#105312|
|[751577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751577)|dotnet/runtime|[WasmTestOnV8-ST-System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751577&view=ms.vss-test-web.build-test-results-tab&runId=19035478&resultId=145907)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|14|

**Comment by pavelsavara** [comment]
This is AOT and memory corruption. I think it could be same as https://github.com/dotnet/runtime/issues/104956

**Comment by pavelsavara** [comment]
I hope the the root cause is https://github.com/dotnet/runtime/issues/106200 and fix https://github.com/dotnet/runtime/pull/106313
