### ISSUE TITLE
Undocumented Change in behavior for GetTempPath in .NET 6.0.32 and Framework 4.8.1

### ISSUE THREAD

**Issue by FreeApophis** [dotnet/runtime#105012]
### Description

We detected this week a behaviour change for Path.GetTempPath on serveral of our machines and our customers:

According to the documentation there was a change in .NET 7, but it looks like this was backported to at least .NET 6.0.32 in this commit: https://github.com/dotnet/runtime/commit/64331033cae32fd6166b321301baaf8f004e2336

Even though I am not sure what the MS_IO_REDIST IfDef is doing, it looks very much like this change induced the behaviour change in .NET 6, because in both cases it now can use `GetTempPath2W` which is the new behaviour.

According to the commit it is implied that this change was also done in .NET Framework. And our tests suggests that this also happens in .NET Framework 4.8.1. But we are still investigating which versions exactly. (It looks like the source here is the newest windows update, still investigating)

If available it calls the Win32 API `GetTempPath2W`, this function unconditionally returns "Windows/SystemTemp" and cannot be overridden by an enviroment variable.

### Reproduction Steps

We wrote a service in Framework 4.8 and in .NET 6 and run it as a service and the TempPath it returns is "Windows/SystemTemp" instead of the TempPath given by `GetTemPathW`.

### Expected behavior

The behaviour documented here:

https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-6.0&tabs=windows

### Actual behavior

The behaviours described for .NET 7+ only.

### Known Workarounds

Running the Service as a non-system account.

### Configuration

.NET 6.0.32
.NET 4.8 (**Old behaviour**: Windows 11: 22631.3737  **New behaviour**: Windows 11: 22631.3880)

**Comment by huoyaoyuan** [comment]
Using `GetTempPath2W` is intentional, and treated as a security fix. See #72452 and #104621. It's a part of security update of this month. @rbhanda 

> According to the documentation there was a change in .NET 7

It was #72452, which wasn't considered as security issue.

**Comment by FreeApophis** [comment]
Why is the documentation not updated accordingly? In the documentation it is still stated that this behaviour is only present in .NET 7 and above. If you make breaking changes, at least document it in your own documentation.

> > According to the documentation there was a change in .NET 7
> It was #72452, which wasn't considered as security issue.

And it wasn't considered as breaking and ignored. The problem beeing that they did not consider that people using the Win32-API directly (via a C++-Program) and C#.

Anyway, please fix the documentation.

**Comment by adamsitnik** [comment]
> Why is the documentation not updated accordingly?

Since this was a security fix, we had to update the product first and then update the docs (not in the opposite order, as somebody could use it as a vector of attack for unpatched apps). But the delay should be minimal, please excuse us for any inconvenience. 

> Anyway, please fix the documentation.

I've just send a PR with a fix, PTAL and let me know if this is enough: https://github.com/dotnet/dotnet-api-docs/pull/10118

**Comment by FreeApophis** [comment]
Thank you for the fast answer. My co-worker has a little suggestion in the PR, otherwise the issue is closed for us.

**Comment by Jabe** [comment]
We ran into the same issue, affecting customers.
