### ISSUE TITLE
Not able to load or resolve assembly and dependencies

### ISSUE THREAD

**Issue by JohanPetersson** [dotnet/runtime#1050]
### Background

I'm developing a CLI tool where one should be able to load assemblies from any .NET Core app directory and then use reflection.
I locate all dll files in the directory (requires that the application has been compiled) and try to load them and have custom code to try to load all dependencies not available in the directory. But I'm not able to load all dependencies, following exception is thrown:

> Could not load file or assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. An operation is not legal in the current state. (0x80131509)'

If I change my tool to use the `Microsoft.NET.Sdk.Web` SDK instead, then I'm able to load all assemblies since all dependencies are already loaded.

If I explicitly add a fallback path to `ReferenceAssemblyPathResolver` (see unit tests below) I'm at least able to resolve the dependencies, but not load them.

```c#
var path = "c:\\projects\\dotnetapp\\";

foreach (var assemblyPath in Directory.EnumerateFiles(path, "*.dll", SearchOption.AllDirectories))
{
    using (var loader = new AssemblyResolver(assemblyPath))
    {
        // Throws exception 
        var types = loader.Assembly.GetExportedTypes();
    }
};

internal sealed class AssemblyResolver : IDisposable
{
    private readonly AssemblyLoadContext _loadContext;
    private readonly DependencyContext _dependencyContext;
    private readonly ICompilationAssemblyResolver _assemblyResolver;

    public AssemblyResolver(string path)
    {
        _loadContext = new AssemblyLoadContext(path, true);

        Assembly = _loadContext.LoadFromAssemblyPath(path);

        _dependencyContext = DependencyContext.Load(Assembly);

        _assemblyResolver = new CompositeCompilationAssemblyResolver(new ICompilationAssemblyResolver[]
        {
            // Probe the app's bin folder.
            new AppBaseCompilationAssemblyResolver(Path.GetDirectoryName(path)),

            // Probe reference assemblies.
            new ReferenceAssemblyPathResolver(),

            // Probe NuGet package cache
            new PackageCompilationAssemblyResolver()
        });

        _loadContext.Resolving += OnResolving;
    }

    public Assembly Assembly { get; }

    public void Dispose()
    {
        _loadContext.Resolving -= OnResolving;
        _loadContext.Unload();
    }

    /// <summary>
    /// Called when the assembly's dependencies couldn't be loaded.
    /// </summary>
    /// <param name="context">The context.</param>
    /// <param name="name">The assembly.</param>
    /// <returns>Returns the resolved dependent assembly otherwise null.</returns>
    private Assembly? OnResolving(AssemblyLoadContext context, AssemblyName name)
    {
        // Try to resolve the dependent assembly by looking in the dependency ({assembly}.deps.json) file.
        var compileLibrary = _dependencyContext.CompileLibraries
            .FirstOrDefault(x => x.Name.Equals(name.Name, StringComparison.OrdinalIgnoreCase));

        if (compileLibrary == null)
        {
            // If the application has PreserveCompilationContext set to 'false' we also need to check runtime libraries.
            // This shouldn't be the case with projects using Microsoft.NET.Sdk.Web, which defaults to 'true'.
            var runtimeLibrary = _dependencyContext.RuntimeLibraries
                .FirstOrDefault(x => x.Name.Equals(name.Name, StringComparison.OrdinalIgnoreCase));

            if (runtimeLibrary != null)
            {
                compileLibrary = new CompilationLibrary(
                    runtimeLibrary.Type,
                    runtimeLibrary.Name,
                    runtimeLibrary.Version,
                    runtimeLibrary.Hash,
                    runtimeLibrary.RuntimeAssemblyGroups.SelectMany(g => g.AssetPaths),
                    runtimeLibrary.Dependencies,
                    runtimeLibrary.Serviceable);
            }
        }

        if (compileLibrary == null)
        {
            return null;
        }

        var assemblyPaths = new List<string>();

        if (_assemblyResolver.TryResolveAssemblyPaths(compileLibrary, assemblyPaths))
        {
            try
            {
                return _loadContext.LoadFromAssemblyPath(assemblyPaths.First());
            }
            catch
            {
            }
        }

        return null;
    }
}
```

The `dotnetapp`'s deps.json has following (removed lines for brevity) information:

```json
"targets": {
  ".NETCoreApp,Version=v3.0": {
    "dotnetapp/1.0.0": {
      "dependencies": {
        ...
        "Microsoft.AspNetCore.Components": "3.0.0.0",
        ....
     },
     ...
     "Microsoft.AspNetCore.Components/3.0.0.0": {
        "compile": {
          "Microsoft.AspNetCore.Components.dll": {}
        },
        "compileOnly": true
      },
      ...
}
```

I'm able to manually locate `Microsoft.AspNetCore.Components` in my NuGet cache and also among my shared framework files in Explorer.

I've added a few unit tests to check whether any of the `ICompilationAssemblyResolver`s were able to locate the assembly, but they all fail:

```c#
[Fact]
public void PackageCompilationAssemblyResolver_ResolveAssemblyPaths()
{
    var lib = new CompilationLibrary(
        type: "package",
        name: "Microsoft.AspNetCore.Components",
        version: "3.0.0.0",
        hash: string.Empty,
        assemblies: new[] { "Microsoft.AspNetCore.Components.dll" },
        dependencies: new Dependency[0],
        serviceable: false
    );

    var subject = new PackageCompilationAssemblyResolver();

    var assemblyPaths = new List<string>();

    var resolved = subject.TryResolveAssemblyPaths(lib, assemblyPaths);

    Assert.True(resolved);
    Assert.NotEmpty(assemblyPaths);
}

[Fact]
public void ReferenceAssemblyPathResolver_ResolveAssemblyPaths()
{
    var lib = new CompilationLibrary(
        type: "referenceassembly",
        name: "Microsoft.AspNetCore.Components",
        version: "3.0.0.0",
        hash: string.Empty,
        assemblies: new[] { "Microsoft.AspNetCore.Components.dll" },
        dependencies: new Dependency[0],
        serviceable: false
    );

    var subject = new ReferenceAssemblyPathResolver();

    var assemblyPaths = new List<string>();

    var resolved = subject.TryResolveAssemblyPaths(lib, assemblyPaths);

    Assert.True(resolved);
    Assert.NotEmpty(assemblyPaths);
}
``` 

My `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App` directory contains

- 2.1.14
- 3.0.1
- 3.1.0

But not 3.0.0. If I explicitly add the 3.0.1 directory then the `ReferenceAssemblyPathResolver` is able to resolve the assembly at least:

```c#
[Fact]
public void ReferenceAssemblyPathResolver_ResolveAssemblyPaths()
{
    var lib = new CompilationLibrary(
        type: "referenceassembly",
        name: "Microsoft.AspNetCore.Components",
        version: "3.0.0.0",
        hash: string.Empty,
        assemblies: new[] { "Microsoft.AspNetCore.Components.dll" },
        dependencies: new Dependency[0],
        serviceable: false
    );

    var subject = new ReferenceAssemblyPathResolver(string.Empty, new[] { "C:\\Program Files\\dotnet\\shared\\Microsoft.AspNetCore.App\\3.0.1" });

    var assemblyPaths = new List<string>();

    var resolved = subject.TryResolveAssemblyPaths(lib, assemblyPaths);

    Assert.True(resolved);
    Assert.NotEmpty(assemblyPaths);
}
``` 

If I add the fallback path to my custom `AssemblyResolver` as well I'm at least able to load `Microsoft.AspNetCore.Components` but then the code fails on `'Microsoft.AspNetCore.Mvc.RazorPages` with following exception.

> Could not load file or assembly 'Microsoft.AspNetCore.Mvc.RazorPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER))

### Questions

Is this even doable, or should I take another approach?

Since I don't have the 3.0.0 shared framework directory, is the "rollForward" functionality taking care of resolving the correct assembly? If so, how can I do the same in my custom assembly resolver?

**Comment by vitek-karas** [comment]
Re roll-forward: The exact roll-forward behavior is currently only implemented in `hostfxr` and not really exposed as a managed API anywhere. The basic rules are simple to implement, but the fully featured functionality is pretty tricky. The [spec](https://github.com/dotnet/runtime/blob/master/docs/design/features/framework-version-resolution.md) has all the details if you're interested.

The `.deps.json` parsing is implemented in two components. The `Microsoft.Extensions.DependencyModel` which is what you're using. That doesn't implement fully the actual resolution logic though. It implements most of it, but there might be holes. The second implementation is in `hostpolicy` which is what the runtime uses when running the app. Most of the functionality is exposed via `AssemblyDependencyResolver` and you might be able to use that in some cases - that said it was not designed to load applications, it's main purpose is to load plugins.

Just curious: When you say reflection does it mean:
* Actual runtime reflection (as in `Activator.CreateInstance` and similar) where you load the code for real with the intent to run it?
* "Reflection-only-load" where you only intend to inspect the assemblies without ever running the code in them? (This would be done best by using [MetadataLoadContext](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext?view=dotnet-plat-ext-3.1&viewFallbackFrom=netcore-3.1))

Side note: Based on your description - your tool consumes fully compiled apps as input. With that I find it really weird that you need to resolve reference assemblies (compile-only assets in `.deps.json`). Those should basically never show up at runtime.

**Comment by JohanPetersson** [comment]
Thanks for the reply. I wasn't able to resolve this issue with any of the aforementioned approaches. Yes, I'm intending to just use reflection, not run the code. What eventually worked for me was following (removed some code for brevity):

```
// Subscribe to assembly loading in the current app domain
AppDomain.CurrentDomain.AssemblyResolve += ResolveAssembly;

// Then just do a simple assembly load
var assembly = Assembly.LoadFrom(path);

// Handle dependencies and assemblies we're not able to load
private Assembly? ResolveAssembly(object? sender, ResolveEventArgs args)
{
    if (string.IsNullOrEmpty(args.Name) || args.RequestingAssembly == null)
    {
        return null;
    }

    var assemblyName = new AssemblyName(args.Name);
    var basePath = Path.GetDirectoryName(args.RequestingAssembly.Location);

    if (string.IsNullOrEmpty(basePath))
    {
        return null;
    }

    foreach (var extension in new[] { ".dll", ".exe" })
    {
        var path = Path.Combine(basePath, assemblyName.Name + extension);

        if (File.Exists(path))
        {
            try
            {
                return Assembly.LoadFrom(path);
            }
            catch
            {
            }
        }
    }

    return null;
}
```

Much less code, but I guess this also means we're loading the assemblies into the current app domain and not in a isolated context where we can then unload them. I don't think that's an issue here anyway and I noticed Entity Framework Core is doing the same in their CLI tool.

**Comment by vitek-karas** [comment]
You could tweak this to work in isolated load context. Keep the global resolve handler (on the appdomain) but load the assembly into the same assembly as the requesting assembly, so something like:
``` C#
AssemblyLoadContext.GetLoadContext(args.RequestingAssembly).LoadFromAssemblyPath(path)
```

And start the process by creating a new load context and loading the first assembly into it explicitly via `LoadFromAssemblyPath`.

If you're only using these for discovery (no intent to ever run the code), then I would also suggest to look into using `MetadataLoadContext` as mentioned in my previous reply. That is not tied to ALCs or runtime in any way and is fully collectible (as in - will get freed once you're not using it anymore via GC). It's also probably faster and uses less memory in your scenario. And it will let you load any app (even .NET Framework apps for example, if you can resolve all the dependencies) regardless of the version it uses and what version your tool is running on.

**Comment by JohanPetersson** [comment]
Thanks for your feedback. I will try it out.

**Comment by JuhBoy** [comment]
I'm in the same situation with a Post build tool i'm developing. However, the previous implementation which are close to what I have done is not working.

**Context:** 
My AssemblyResolver is living inside a .netstandard 2.1 lib. The lib itself is referenced by a Dotnet Core 3.1 console app. The target assembly - i'm trying to load - is a Dotnet Core 3.1 console app.

**Exception:** "Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'."

**Code:** if you wan't to see the actual resolver: https://github.com/JuhBoy/interface-transpiler/blob/dev/EasyTranspiler/src/Core/Utils/AssemblyResolver.cs

i'm in a dead end situation, i tried a lot of different things, but none seems working. I know i'm wrong somewhere but if you guys can give me a little hint, i'd love it ! :D

**Comment by JuhBoy** [comment]
Ok i fixed by making the assembly loader's project as "Microsoft.NET.Sdk.Web" and not just "Microsoft.NET.Sdk" which makes some depencies available... I don't know if it's more a trick than a solution but... atm it's working. :p

**Comment by vitek-karas** [comment]
This is a known limitation of `AssemblyDependencyResolver` - it will not load additional frameworks into the process. So if the host is only dependent on `Microsoft.NETCore.App` framework (as visible in `.runtimeconfig.json`) and it tries to dynamically load a component which requires `Microsoft.AspNetCore.App` - it won't work. Basically the host must depend on all framework which all the components in it might need.

So your fix is one way to do this correctly. Another one might be to keep the same SDK but add `FrameworkReference` to the `Microsoft.AspNetCore.App` framework into the project.

**Comment by JuhBoy** [comment]
Thank you very much for your reply. It helps a lot !
