### ISSUE TITLE
No-op incremental libs build spends most of the time in compiling asn files

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#105077]
I ran a fully incremental build an produced a binlog via the following command: `build.cmd libs -allconfigurations -c Release && build.cmd libs -allconfigurations -c Release -bl`

The binlog shows 0 csc task invocations as expected but **it shows asn files are compiled**:

![image](https://github.com/user-attachments/assets/53a71861-281b-40f2-8e1f-f1eb2615e1bd)

Looking further, the binlog shows that the `CompileAsn` target runs for the following projects:

![image](https://github.com/user-attachments/assets/33309ba5-a892-46cc-b256-5ae60f559be8)

The `CompileAsn` target uses incremental features by declaring inputs and outputs but the binlog tells us that msbuild believes that the input files is newer than the output file:

![image](https://github.com/user-attachments/assets/ee50c27e-03a5-40b5-a1b2-de09ae8d8028)

I checked the modified dates of those files:

![image](https://github.com/user-attachments/assets/4541894b-0b4e-44e0-98cb-10bf843493b1)

```cmd
PS C:\git\runtime4\src\libraries\Common\src\System\Security\Cryptography\Asn1> forfiles /M asn.xslt /C "cmd /c echo @fdate @ftime"
7/2/2024 5:00:53 PM
PS C:\git\runtime4\src\libraries\Common\src\System\Security\Cryptography\Asn1> forfiles /M AlgorithmIdentifierAsn.xml.cs /C "cmd /c echo @fdate @ftime"
7/2/2024 5:00:53 PM
```

**Comment by ViktorHofer** [comment]
This regressed with https://github.com/dotnet/runtime/commit/b88785f22d6a6d0618ebb63490b4a87e3b61c9f6

cc @vcsjones @am11 @bartonjs

**Comment by ViktorHofer** [comment]
It looks to me that the current target implementation is wrong. If a target defines inputs and outputs and msbuild runs it because the input is newer than the output, then the target must update the output. cc @rainersigwald on that

https://github.com/dotnet/runtime/blob/66ae89812794186ee10da590a5d31d04125237ea/src/libraries/Common/src/System/Security/Cryptography/Asn1/AsnXml.targets#L32-L60

**Comment by am11** [comment]
> `PS C:\git\runtime4\src\libraries\Common\src\System\Security\Cryptography\Asn1> forfiles /M asn.xslt /C "cmd /c echo @fdate @ftime"`

Could you try getting the full timestamps, e.g. pwsh: `(Get-Item "asn.xslt").LastWriteTimeUtc.Ticks`?

**Comment by am11** [comment]
`CompareFilesIgnoreLineEndings` is called inside `CompileAsn`. If you mean `CompileAsn` shouldn't be called 422 times, then `CompareFilesIgnoreLineEndings` is unrelated, no?

**Comment by vcsjones** [comment]
We could just unconditionally copy by removing this

https://github.com/dotnet/runtime/blob/66ae89812794186ee10da590a5d31d04125237ea/src/libraries/Common/src/System/Security/Cryptography/Asn1/AsnXml.targets#L55

But only show the `<Warning...` if the contents differ.

**Comment by vcsjones** [comment]
Though I am perplexed how b88785f regressed this, as conditionally copying was in place before.

**Comment by am11** [comment]
@vcsjones, correct, besides:
> ![image](https://private-user-images.githubusercontent.com/7412651/349936757-53a71861-281b-40f2-8e1f-f1eb2615e1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDcwMzgsIm5iZiI6MTcyMTMwNjczOCwicGF0aCI6Ii83NDEyNjUxLzM0OTkzNjc1Ny01M2E3MTg2MS0yODFiLTQwZjItOGUxZi1mMWViMjYxNWUxYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTI0NTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWVlNDRlZTIxZGM3NWFiMjEyZTJjNDA2NjRkY2U3OTQ1MThlNjU2NmI5NDU2M2Q1MGQ1MDBkOTY5YzRkOTk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kskZwQqb38uzQl6ZFqf33LSsXbQ6LqdRVySSYiJ07p0)
> 

is suggesting XslTransformation tasks is the one where most time is spent which is called _before_, so https://github.com/dotnet/runtime/commit/b88785f22d6a6d0618ebb63490b4a87e3b61c9f6 is unrelated to the perf issue in question.

**Comment by ViktorHofer** [comment]
No, it's not unrelated. The `XmlTransormation` task shouldn't be called in a no-op incremental build but is now called because the output never gets updated and so the target always runs.

> Though I am perplexed how https://github.com/dotnet/runtime/commit/b88785f22d6a6d0618ebb63490b4a87e3b61c9f6 regressed this, as conditionally copying was in place before.

There was conditional copying in place, yes but from what I can see, that was conditioned differently and so the output file always got updated when the target ran.

**Comment by am11** [comment]
@ViktorHofer are we talking about the same code? XmlTransormation is called before CompareFilesIgnoreLineEndings so your claim https://github.com/dotnet/runtime/commit/b88785f22d6a6d0618ebb63490b4a87e3b61c9f6 is somehow realted is not correct.

**Comment by ViktorHofer** [comment]
It doesn't matter if `CompareFilesIgnoreLineEndings` is called before or after the `XmlTransormation` msbuild task. What matters is that the target's output doesn't get updated anymore when the target runs so a subsequent (no-op) build fully executes the target and it doesn't get skipped.

I'm pretty sure that this change is related as I had a no-op build from months before where this target didn't rrun.

**Comment by vcsjones** [comment]
I'll admit my MSBuild knowledge is mediocre at best.

@ViktorHofer would adding something like this after `Copy` resolve the issue?

```xml
<Touch Files="@(AsnXml -> '%(Identity).cs')" />
```

**Comment by ViktorHofer** [comment]
OK my theory is disproven. I checked out https://github.com/dotnet/runtime/tree/4681f6318feef5d0d0bdba9f88876e266e65f2aa which is one commit before your change and I still see `CompileAsn` target running in a fully no-op build:

![image](https://github.com/user-attachments/assets/be9e75c3-bbca-4ea0-9129-701deefb6b00)

So this problem already existed before but for whatever reason didn't show up on my earlier investigations last year. No idea why.

**Comment by ViktorHofer** [comment]
> @ViktorHofer would adding something like this after Copy resolve the issue?

Yes, the `Touch` is usually used to avoid such problems in incremental targets by updating the modified timestamp of the output file.

**Comment by vcsjones** [comment]
Okay. I can reproduce this and adding a `<Touch />` to the output of the target fixes it.

When doing an incremental build of just `System.Security.Cryptography`

<img width="319" alt="image" src="https://github.com/user-attachments/assets/47ab96ed-eaf9-4582-8eee-56166de5177e">


After adding `<Touch />`:

<img width="268" alt="image" src="https://github.com/user-attachments/assets/e0641039-eac1-40bf-8b0c-48d985ce9498">

Thanks for pointing it out @ViktorHofer.

**Comment by vcsjones** [comment]
> So this problem already existed before but for whatever reason didn't show up on my earlier investigations last year. No idea why.

It likely only happens (noticeably) when `asn.xslt` changes (and how it changes). If that file changes a bunch of C# files are considered out-of-date, but if they don't get updated, so we just keep doing XSLT transformations over and over, never updating the C# file.
