### ISSUE TITLE
System.Uri.TryCreate succeeds where new System.Uri fails.

### ISSUE THREAD

**Issue by SetTrend** [dotnet/runtime#105024]
### Description

While `new System.Uri()` throws `System.UriFormatException` exception: "**_Invalid URI: The URI scheme is not valid._**", `System.Uri.TryCreate()` returns `true` on the same URI.

### Reproduction Steps

```c#
static void Main(string[] args)
{
  string testUri = "#EXTVDJ:<filesize>989800</filesize>";

  if (Uri.TryCreate(testUri, UriKind.RelativeOrAbsolute, out Uri? result)) result = new Uri(testUri);
}
```

### Expected behavior

`System.Uri.TryCreate()` should fail/succeed when `new System.Uri()` fails/succeeds and vice versa.

### Actual behavior

While `new System.Uri()` throws `System.UriFormatException` exception: "**_Invalid URI: The URI scheme is not valid._**" with above example, `System.Uri.TryCreate()` returns `true` on the same URI and returns a useless `System.Uri` object.

### Configuration

This supposedly erroneous behaviour occurs with .NET Framework and .NET.

**Comment by DL444** [comment]
Note that `new Uri(testUri)` is not equivalent with `Uri.TryCreate(testUri, UriKind.RelativeOrAbsolute, out Uri? result)`. `new Uri(testUri, UriKind.RelativeOrAbsolute)` is, and it does not throw in your case.

**Comment by SetTrend** [comment]
To what extend does the **out** argument change the behaviour? This seems very obscure to me.

Is this documented somewhere?

**Comment by stephentoub** [comment]
> To what extend does the out argument change behaviour? This seems very obscure to me.

It's not the out argument. It's that the ctor uses UriKind.Absolute but you're calling TryCreate passing in UriKind.RelativeOrAbsolute rather than UriKind.Absolute.
