### ISSUE TITLE
JIT: SVE - Add FFR lifetime tracking as well as test coverage for NonFaulting APIs 

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#105163]
Since we have already merged the NonFaulting SVE APIs, we need to add additional testing on their first-faulting behavior since they share the similar behavior as the FirstFaulting APIs. See https://github.com/dotnet/runtime/pull/104502

**Comment by a74nh** [comment]
priority:2 for RC1 snap : Missing testing

**Comment by JulieLeeMSFT** [comment]
@mikabl-arm, PTAL.

**Comment by kunalspathak** [comment]
Note: This is not just test coverage, but we need to also model FFR register lifetime for non-faulting APIs. So this also needs product change.
