### ISSUE TITLE
x86 Interop Call stack incorrect when stopped in native exception filter

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#105116]
### Description

In .NET 9 preview 6 there is a regression in x86 interop call stacks. When stopped in a native exception filter, the leaf native code range is hidden and only the managed range is shown.

### Reproduction Steps

1. Extract this solution: [x86InteropTest.zip](https://github.com/user-attachments/files/16289299/x86InteropTest.zip)
2. Open the solution in Visual Studio
3. Open NativeLib\dllmain.cpp, and set a breakpoint on line 25
4. Start debugging

### Expected behavior

ICorDebugThread.EnumerateChains should return a leaf chain which is unmanaged

### Actual behavior

ICorDebugThread.EnumerateChains returns a managed leaf chain. Here is the chain object (mscordbi.dll!ShimChain):

| Name | Value | Type |
|-|-|-|
| ICorDebugChain | {...} | mscordbi.dll!ICorDebugChain |
| m_context | {ContextFlags=0x00010007 Dr0=0x07d1c9b0 Dr1=0x5b68240b ...} | mscordbi.dll!DT_CONTEXT |
| m_fpRoot | {m_sp=0x00c0eeb4 } | mscordbi.dll!FramePointer |
| m_pStackWalk | 0x0873c430 {m_stackChains={...} m_stackFrames={...} m_pChainEnumList=0x086eb860 {m_pStackWalk=0x0873c430 {...} ...} ...} | mscordbi.dll!ShimStackWalk * |
| m_refCount | {m_val=0x00000002 } | mscordbi.dll!Volatile<unsigned long> |
| m_chainIndex | 0x00000000 | unsigned int |
| m_frameStartIndex | 0x00000000 | unsigned int |
| m_frameEndIndex | 0x00000001 | unsigned int |
| m_chainReason | CHAIN_ENTER_MANAGED (0x00000080) | mscordbi.dll!CorDebugChainReason |
| m_fIsManaged | 0x00000001 | int |
| m_fIsNeutered | 0x00000000 | int |

### Regression?

This is a regression from .NET 9 preview 5

### Known Workarounds

None

### Configuration

Interop debugging is only on win-x86 and win-x64. Of the two, this only repros on x86.

**Comment by tommcdon** [comment]
@janvorli

**Comment by tommcdon** [comment]
This was likely caused by https://github.com/dotnet/runtime/pull/102774.  The top internal frame is being identified as an Exception frame and so it is not reporting the unmanaged frame chain to the debugger.
