### ISSUE TITLE
GZipStream decompression bug

### ISSUE THREAD

**Issue by danwulff1** [dotnet/runtime#105183]
### Description

I have encountered a problem when using GZipStream to decompress a stream that was compressed by another GZipStream.
It throws an error claiming that the compressed data is using an unsupported method.

### Reproduction Steps

uncompress the attached file data.zip
then put data.bin in the appropriate bin folder
run the below test program.

```c#
using System.IO.Compression;

class Program
{
    static void Main()
    {
        byte[] data = new byte[65536];
        // Open the file
        using (FileStream file = new FileStream("test.bin", FileMode.Open))
        {
            file.Read(data, 0, 65536);
 
            // Create a MemoryStream to hold the uncompressed data
            using (MemoryStream dataStream = new MemoryStream(data))
            {
                // Create a GZipStream for compression
                using (GZipStream zip = new GZipStream(dataStream, CompressionLevel.Optimal, leaveOpen: true))
                {
                    // Create a GZipStream for decompression
                    using (GZipStream unzip = new GZipStream(zip.BaseStream, CompressionMode.Decompress))
                    {
                        // To read the decompressed data into another memory stream
                        using (MemoryStream decompressedStream = new MemoryStream())
                        {
                            unzip.CopyTo(decompressedStream);
                            Console.WriteLine(decompressedStream.Length);
                        }
                    }
                }
            }
        }
    }
}
```
[test.zip](https://github.com/user-attachments/files/16321537/test.zip)

### Expected behavior

writing the length of decompressed data on the console.

### Actual behavior

InvalidDataException with the message "The archive entry was compressed using an unsupported compression method".
when trying to decompress.

### Configuration

dotnet 8.0.7

**Comment by Tornhoof** [comment]
> file.Read(data, 0, 65536);

You're ignoring the result of FileStream Read. It does not guarantee  to fill the Buffer you've passed in. This is a common mistake and a recent Change in the gzip code made it more visible.

**Comment by huoyaoyuan** [comment]
> You're ignoring the result of FileStream Read. It does not guarantee to fill the Buffer you've passed in.

Does it really matter in this case? The file is used as uncompressed data. Incomplete read or random content shouldn't matter.

**Comment by danwulff1** [comment]
I just realized that it was the CopyTo that threw the error.
If I change 
unzip.CopyTo(decompressedStream);
to
unzip.BaseStream.CopyTo(decompressedStream);
it works as intended.

I don't know if the abve should be considered a bug, though.

**Comment by Miizukii** [comment]
`zip` stream never does anything, `dataStream` is the output stream that only gets correctly compressed data if  data is written into `zip` and closed before the data is read

`unzip` is failing correctly when trying to read the raw bytes that have no zip header.

```c#
using var compressedStream = new MemoryStream();
{
    using var zip = new GZipStream(compressedStream, CompressionLevel.Optimal, leaveOpen: true);
    using var file = new FileStream("test.bin", FileMode.Open);
    file.CopyTo(zip);
    Console.WriteLine(file.Length);
}

compressedStream.Position = 0;
using var unzip = new GZipStream(compressedStream, CompressionMode.Decompress);
using var decompressedStream = new MemoryStream();

unzip.CopyTo(decompressedStream);
Console.WriteLine(decompressedStream.Length);
```


also `unzip.BaseStream.CopyTo(decompressedStream);` works since that copies the unchanged `dataStream` into `decompressedStream` completely bypassing the GZip streams

**Comment by ericstj** [comment]
@Miizukii's response is correct.  

The repro in the original post never does compression.  It just creates a stream with the uncompressed data in memory stream as the backing stream but never writes to it.
