### ISSUE TITLE
Static destructors not called after Environment.Exit() is called.

### ISSUE THREAD

**Issue by testcocoon** [dotnet/runtime#1051]
After a call of Environment.Exit() in dotnet on Linux, the application exits but the static destructors are not called. This behavior is completely different as with Visual Studio on Windows.

Example: we take the following  code sample:
`
    class Program
    {
        static void Main(string[] args)
        {
            Foo.Init();
            Environment.Exit(0);
        }
    }

    static class Foo
    {
        private static readonly Destructor ist = new Destructor();

        static public void Init(){}

        private sealed class Destructor
        {
            ~Destructor()
            {
                Console.WriteLine("Foo Destructor");
            }
        }
            
    }
}
`

With Visual Studio .NET, "Foo Destructor" is printed on the console because the destructor is called after an Environment.Exit(). On Linux, with dotnet it is not the case.
This is a bit problematic because it does not permits a proper cleanup on exit.

As attachment there are a project with permits to reproduce this issue.
[Exit_Issue.zip](https://github.com/dotnet/runtime/files/3983696/Exit_Issue.zip)

The same sample is available for dotnet core and for Visual Studio .NET.

**Comment by ayende** [comment]
I'm pretty sure that there are no guarantees that finalized will run, ever

**Comment by DaZombieKiller** [comment]
This is intentional: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors

> In .NET Framework applications (but not in .NET Core applications), finalizers are also called when the program exits.

**Comment by jkotas** [comment]
This was intentional behavior change for .NET Core. More discussion about it is in https://github.com/dotnet/corefx/issues/5205
