### ISSUE TITLE
Redundant null check in JIT

### ISSUE THREAD

**Issue by jods4** [dotnet/runtime#105191]
I noticed that JIT (at least CLR 8 on both x86 and x64) sometimes performs duplicate null checks in seemingly simple situations.

I was comparing `x is ""` and `x is string { Length: 0 }`.
They're 100% equivalent except that the former performs a redundant null-check, so it's 9 bytes longer with an extra jump.
Check it out here: https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACR2DC2A3utmbjgPYBGAVgKYDGwA/NgJ4Dcp5PZW2apUoAbbAFkkACkIAPAJTE+5fgHZssgHTtsASwjYARIe5oVAX2XKBQ0RIQyNikmZXk46rTv24kABmJsABl6ADsAc2AACxBsAPNTC3RzIA==

```
; Core CLR 8.0.624.26715 on x86

; Disassembly of 
; class C { object y }
; bool M(C x) => x.y is ""

    L0000: push ebp
    L0001: mov ebp, esp
; eax = x.y
    L0003: mov eax, [edx+4]
; First check of x.y is null ?
    L0006: test eax, eax
    L0008: je short L0026
; x.y is string ?
    L000a: cmp dword ptr [eax], 0x9881158
    L0010: jne short L0026
; Redundant check of x.y is null !!
    L0012: test eax, eax
    L0014: je short L0022
; x.y.Length == 0 ?
    L0016: cmp dword ptr [eax+4], 0
    L001a: sete al
    L001d: movzx eax, al
    L0020: jmp short L0024
    L0022: xor eax, eax
    L0024: pop ebp
    L0025: ret
    L0026: xor eax, eax
    L0028: pop ebp
    L0029: ret
```

### Other minor perf difference
I also noticed that the common `ldstr ""` incurs an extra memory access compared to `ldsfld string.Empty`.
The latter is inlined with its constant value so something like `mov eax, 0x1234`.
I guess the former loads the string from an interned string table and has a memory access `mov eax, [0x5678]`.
So it would seem beneficial to automatically compile `ldstr ""` as if it was `ldsfld string.Empty`.

**Comment by EgorBo** [comment]
Here is the codegen for these two functions on .NET 9.0 x64 (your sharplab snippet uses 32bit runtime btw):
```asm
; Assembly listing for method C:M1(C):ubyte:this (FullOpts)
G_M44900_IG01:
G_M44900_IG02:
       mov      rax, gword ptr [rdx+0x08]
       test     rax, rax
       je       SHORT G_M44900_IG06
G_M44900_IG03:
       mov      rcx, 0x7FF7E2F6B878      ; System.String
       cmp      qword ptr [rax], rcx
       jne      SHORT G_M44900_IG06
G_M44900_IG04:
       cmp      dword ptr [rax+0x08], 0
       sete     al
       movzx    rax, al
G_M44900_IG05:
       ret      
G_M44900_IG06:
       xor      eax, eax
G_M44900_IG07:
       ret      


; Assembly listing for method C:M2(C):ubyte:this (FullOpts)
G_M9383_IG01:
G_M9383_IG02:
       mov      rax, gword ptr [rdx+0x08]
       test     rax, rax
       je       SHORT G_M9383_IG06
G_M9383_IG03:
       mov      rcx, 0x7FF7E2F6B878      ; System.String
       cmp      qword ptr [rax], rcx
       jne      SHORT G_M9383_IG06
G_M9383_IG04:
       cmp      dword ptr [rax+0x08], 0
       sete     al
       movzx    rax, al
G_M9383_IG05:
       ret      
G_M9383_IG06:
       xor      eax, eax
G_M9383_IG07:
       ret      
```

I don't see any issues here

**Comment by jods4** [comment]
@EgorBo Great to see it was improved in .net 9.0! (sharplab is .net 8.0) 🎉

> (your sharplab snippet uses 32bit runtime btw)

I tried both and on .net 8.0 x86 and x64 gave similar results.

> We do the opposite - we compile ldsfld string.Empty as ldstr ""

This is a .net 9.0 improvement as well, right?

Because on .net 8.0 they aren't the same, check this out (x86 and x64 are similar):
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunHjyADAwAK5BgF4AfE0EA6AKL4ADhgCeAbi496MocNITpAIiObqAXyA===

And if you had to pick one, `ldstr ""` seems to be the worst codegen of the pair:

```cs
public class C {
    public string P1 => string.Empty;
    public string P2 => "";
}
```

C# performs a very literal compilation
```il
    .method public hidebysig specialname instance string get_P1 () cil managed 
    {
        IL_0000: ldsfld string [System.Runtime]System.String::Empty
        IL_0005: ret
    }

    .method public hidebysig specialname instance string get_P2 () cil managed 
    {
        IL_0000: ldstr ""
        IL_0005: ret
    }
```

ASM is different, `ldstr ""` has an extra memory access:
```asm
C.get_P1()
    L0000: mov rax, 0x179a7670008
    L000a: ret

C.get_P2()
    L0000: mov rax, 0x176634d5fb8
    L000a: mov rax, [rax]
    L000d: ret
```

**Comment by EgorBo** [comment]
> This is a .net 9.0 improvement as well, right?

> Because on .net 8.0 they aren't the same, check this out (x86 and x64 are similar):

Yes, there is a small inefficiency in .NET 8.0 compared to .NET 9.0, but we don't backport small perf improvements like this to LTSes - they won't meet the bar.

> ASM is different, ldstr "" has an extra memory access:

It happens because Sharplab uses a dynamic context to show asm code, you won't see any difference in normal code unless you do some Reflection Emit or use unloadable Assembly Load Contexts.
