### ISSUE TITLE
nativeaot\\SmokeTests\\Reflection\\Reflection\\Reflection.cmd fails with Access Violation

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#105136]
NativeAOT smoketests fail on all PRs

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=747256
Build error leg or test failing: System.Reflection.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/105118

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["Process terminated", "Access Violation: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. The application will be terminated since this platform does not support throwing an AccessViolationException"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=747256
**Error message validated:** `[Process terminated Access Violation: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. The application will be terminated since this platform does not support throwing an AccessViolationException`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/19/2024 10:47:22 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[748218](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748218)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/748218/logs/59)|dotnet/runtime#105162|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[748914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748914)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748914&view=ms.vss-test-web.build-test-results-tab&runId=18944386&resultId=100022)|dotnet/runtime#105162|
|[747813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747813)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747813&view=ms.vss-test-web.build-test-results-tab&runId=18942064&resultId=100024)|dotnet/runtime#105145|
|[748705](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748705)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748705&view=ms.vss-test-web.build-test-results-tab&runId=18937776&resultId=100024)|dotnet/runtime#105162|
|[748320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748320)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748320&view=ms.vss-test-web.build-test-results-tab&runId=18930620&resultId=100024)|dotnet/runtime#105167|
|[748460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748460)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748460&view=ms.vss-test-web.build-test-results-tab&runId=18929740&resultId=129032)|dotnet/runtime#104583|
|[748457](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748457)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748457&view=ms.vss-test-web.build-test-results-tab&runId=18929654&resultId=100024)|dotnet/runtime#104955|
|[748451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748451)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748451&view=ms.vss-test-web.build-test-results-tab&runId=18929614&resultId=100024)|dotnet/runtime#104502|
|[748408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748408)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748408&view=ms.vss-test-web.build-test-results-tab&runId=18927996&resultId=100024)|dotnet/runtime#105152|
|[748350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748350)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748350&view=ms.vss-test-web.build-test-results-tab&runId=18925368&resultId=100024)|dotnet/runtime#105151|
|[748345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748345)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748345&view=ms.vss-test-web.build-test-results-tab&runId=18925056&resultId=100024)|dotnet/runtime#104686|
|[748340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748340)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748340&view=ms.vss-test-web.build-test-results-tab&runId=18924990&resultId=100024)|dotnet/runtime#105169|
|[748332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748332)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748332&view=ms.vss-test-web.build-test-results-tab&runId=18924878&resultId=100024)|dotnet/runtime#104399|
|[748298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748298)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748298&view=ms.vss-test-web.build-test-results-tab&runId=18924136&resultId=100024)|dotnet/runtime#105166|
|[748279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748279)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748279&view=ms.vss-test-web.build-test-results-tab&runId=18923212&resultId=128064)|dotnet/runtime#105007|
|[748272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748272)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748272&view=ms.vss-test-web.build-test-results-tab&runId=18923188&resultId=127628)|dotnet/runtime#105164|
|[748257](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748257)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748257&view=ms.vss-test-web.build-test-results-tab&runId=18922978&resultId=129032)|dotnet/runtime#104811|
|[748254](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748254)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748254&view=ms.vss-test-web.build-test-results-tab&runId=18922838&resultId=127628)|dotnet/runtime#105036|
|[748251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748251)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748251&view=ms.vss-test-web.build-test-results-tab&runId=18922674&resultId=100024)|dotnet/runtime#103755|
|[748217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748217)|dotnet/runtime|[nativeaot/SmokeTests/UnitTests/UnitTests/UnitTests.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748217&view=ms.vss-test-web.build-test-results-tab&runId=18920560&resultId=100023)|dotnet/runtime#105162|
|[748234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748234)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748234&view=ms.vss-test-web.build-test-results-tab&runId=18922016&resultId=129032)|dotnet/runtime#103504|
|[748230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748230)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748230&view=ms.vss-test-web.build-test-results-tab&runId=18921420&resultId=129032)||
|[748206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748206)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748206&view=ms.vss-test-web.build-test-results-tab&runId=18920802&resultId=127628)|dotnet/runtime#105161|
|[748176](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748176)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748176&view=ms.vss-test-web.build-test-results-tab&runId=18919428&resultId=129032)|dotnet/runtime#105160|
|[748179](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748179)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748179&view=ms.vss-test-web.build-test-results-tab&runId=18919424&resultId=100024)|dotnet/runtime#105113|
|[747478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747478)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747478&view=ms.vss-test-web.build-test-results-tab&runId=18918738&resultId=129003)|dotnet/runtime#103585|
|[747671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747671)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747671&view=ms.vss-test-web.build-test-results-tab&runId=18918408&resultId=129003)|dotnet/runtime#105105|
|[748156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748156)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748156&view=ms.vss-test-web.build-test-results-tab&runId=18918154&resultId=127628)|dotnet/runtime#105119|
|[748151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748151)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748151&view=ms.vss-test-web.build-test-results-tab&runId=18917950&resultId=129032)|dotnet/runtime#104906|
|[748136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748136)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748136&view=ms.vss-test-web.build-test-results-tab&runId=18917642&resultId=129032)|dotnet/runtime#105158|
|[748131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748131)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748131&view=ms.vss-test-web.build-test-results-tab&runId=18917142&resultId=129032)|dotnet/runtime#105152|
|[748115](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748115)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748115&view=ms.vss-test-web.build-test-results-tab&runId=18916760&resultId=129032)|dotnet/runtime#103528|
|[748100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748100)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748100&view=ms.vss-test-web.build-test-results-tab&runId=18916458&resultId=123366)|dotnet/runtime#105143|
|[748068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748068)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748068&view=ms.vss-test-web.build-test-results-tab&runId=18915644&resultId=128764)|dotnet/runtime#104352|
|[748050](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748050)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748050&view=ms.vss-test-web.build-test-results-tab&runId=18914666&resultId=123366)|dotnet/runtime#105104|
|[748036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748036)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748036&view=ms.vss-test-web.build-test-results-tab&runId=18914420&resultId=126767)|dotnet/runtime#104999|
|[748007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748007)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748007&view=ms.vss-test-web.build-test-results-tab&runId=18913754&resultId=129032)|dotnet/runtime#103755|
|[748000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748000)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748000&view=ms.vss-test-web.build-test-results-tab&runId=18913548&resultId=129032)|dotnet/runtime#104961|
|[747989](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747989)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747989&view=ms.vss-test-web.build-test-results-tab&runId=18913502&resultId=127628)|dotnet/runtime#105151|
|[747992](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747992)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747992&view=ms.vss-test-web.build-test-results-tab&runId=18913482&resultId=100024)|dotnet/runtime#105113|
|[747939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747939)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747939&view=ms.vss-test-web.build-test-results-tab&runId=18912408&resultId=129024)|dotnet/runtime#104835|
|[747923](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747923)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747923&view=ms.vss-test-web.build-test-results-tab&runId=18912152&resultId=129027)|dotnet/runtime#105103|
|[747591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747591)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747591&view=ms.vss-test-web.build-test-results-tab&runId=18911938&resultId=127623)|dotnet/runtime#105141|
|[747857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747857)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747857&view=ms.vss-test-web.build-test-results-tab&runId=18911002&resultId=129027)|dotnet/runtime#105149|
|[747836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747836)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747836&view=ms.vss-test-web.build-test-results-tab&runId=18910594&resultId=127623)|dotnet/runtime#105148|
|[747528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747528)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747528&view=ms.vss-test-web.build-test-results-tab&runId=18910592&resultId=129003)|dotnet/runtime#105027|
|[747270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747270)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747270&view=ms.vss-test-web.build-test-results-tab&runId=18910290&resultId=129003)|dotnet/runtime#104583|
|[747537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747537)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747537&view=ms.vss-test-web.build-test-results-tab&runId=18910172&resultId=129003)|dotnet/runtime#105109|
|[747831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747831)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747831&view=ms.vss-test-web.build-test-results-tab&runId=18909860&resultId=129003)|dotnet/runtime#103528|
|[747806](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747806)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747806&view=ms.vss-test-web.build-test-results-tab&runId=18909128&resultId=119563)|dotnet/runtime#105131|
|[747800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747800)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747800&view=ms.vss-test-web.build-test-results-tab&runId=18908912&resultId=129003)|dotnet/runtime#105106|
|[747252](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747252)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747252&view=ms.vss-test-web.build-test-results-tab&runId=18908878&resultId=129027)|dotnet/runtime#104848|
|[747769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747769)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747769&view=ms.vss-test-web.build-test-results-tab&runId=18907948&resultId=129003)|dotnet/runtime#102882|
|[747756](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747756)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747756&view=ms.vss-test-web.build-test-results-tab&runId=18907580&resultId=129008)|dotnet/runtime#104558|
|[747753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747753)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747753&view=ms.vss-test-web.build-test-results-tab&runId=18907124&resultId=129003)|dotnet/runtime#105129|
|[747740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747740)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747740&view=ms.vss-test-web.build-test-results-tab&runId=18906994&resultId=126655)|dotnet/runtime#105143|
|[747712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747712)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747712&view=ms.vss-test-web.build-test-results-tab&runId=18906450&resultId=129003)|dotnet/runtime#105122|
|[747715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747715)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747715&view=ms.vss-test-web.build-test-results-tab&runId=18906176&resultId=129003)|dotnet/runtime#104856|
|[747696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747696)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747696&view=ms.vss-test-web.build-test-results-tab&runId=18905430&resultId=129003)|dotnet/runtime#104959|
|[747452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747452)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747452&view=ms.vss-test-web.build-test-results-tab&runId=18904444&resultId=129003)|dotnet/runtime#105094|
|[747658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747658)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747658&view=ms.vss-test-web.build-test-results-tab&runId=18903396&resultId=127623)|dotnet/runtime#104972|
|[747638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747638)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747638&view=ms.vss-test-web.build-test-results-tab&runId=18903184&resultId=121957)|dotnet/runtime#104957|
|[747431](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747431)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747431&view=ms.vss-test-web.build-test-results-tab&runId=18902396&resultId=129003)|dotnet/runtime#104961|
|[747581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747581)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747581&view=ms.vss-test-web.build-test-results-tab&runId=18900904&resultId=129003)|dotnet/runtime#105140|
|[747371](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747371)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747371&view=ms.vss-test-web.build-test-results-tab&runId=18899658&resultId=129003)|dotnet/runtime#105131|
|[747532](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747532)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747532&view=ms.vss-test-web.build-test-results-tab&runId=18899584&resultId=123337)|dotnet/runtime#105109|
|[747524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747524)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747524&view=ms.vss-test-web.build-test-results-tab&runId=18899100&resultId=129003)|dotnet/runtime#104352|
|[747517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747517)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747517&view=ms.vss-test-web.build-test-results-tab&runId=18898994&resultId=129003)|dotnet/runtime#105099|
|[747506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747506)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747506&view=ms.vss-test-web.build-test-results-tab&runId=18898750&resultId=129003)|dotnet/runtime#104906|
|[747492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747492)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747492&view=ms.vss-test-web.build-test-results-tab&runId=18898460&resultId=129003)|dotnet/runtime#104972|
|[747481](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747481)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747481&view=ms.vss-test-web.build-test-results-tab&runId=18897916&resultId=129003)|dotnet/runtime#105032|
|[747441](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747441)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747441&view=ms.vss-test-web.build-test-results-tab&runId=18896862&resultId=129003)|dotnet/runtime#105073|
|[747416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747416)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747416&view=ms.vss-test-web.build-test-results-tab&runId=18896080&resultId=129008)|dotnet/runtime#104558|
|[747427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747427)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747427&view=ms.vss-test-web.build-test-results-tab&runId=18896120&resultId=100024)|dotnet/runtime#105133|
|[747395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747395)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747395&view=ms.vss-test-web.build-test-results-tab&runId=18894800&resultId=129003)|dotnet/runtime#104443|
|[747381](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747381)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747381&view=ms.vss-test-web.build-test-results-tab&runId=18894484&resultId=129003)||
|[747345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747345)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747345&view=ms.vss-test-web.build-test-results-tab&runId=18893682&resultId=129003)|dotnet/runtime#104505|
|[747326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747326)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747326&view=ms.vss-test-web.build-test-results-tab&runId=18893180&resultId=129003)|dotnet/runtime#102882|
|[747297](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747297)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747297&view=ms.vss-test-web.build-test-results-tab&runId=18892212&resultId=127623)|dotnet/runtime#103755|
|[747256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747256)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747256&view=ms.vss-test-web.build-test-results-tab&runId=18890852&resultId=129003)|dotnet/runtime#105118|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|36|80|80|

**Comment by MichalStrehovsky** [comment]
The crash is at the last line of:

```
00007ff7`34181ef8 402e40f9 ldr     x0, [xpr, #0x58]
00007ff7`34181efc a21100f0 adrp    x2, Reflection!WKS::gc_heap::mark_queue (7ff7343b8000)
00007ff7`34181f00 42c01191 add     x2, x2, #0x470 (7ff7343b8470 = Reflection!_tls_index)
00007ff7`34181f04 420040b9 ldr     w2, [x2]
00007ff7`34181f08 025862f8 ldr     x2, [x0, w2 uxtw #3]
00007ff7`34181f0c 21004091 add     x1, x1, #0, lsl #0xC
00007ff7`34181f10 21100091 add     x1, x1, #4
00007ff7`34181f14 4000018b add     x0, x2, x1
00007ff7`34181f18 140040f9 ldr     x20, [x0]
```

@kunalspathak Does this look related to ARM64 TLS? We haven't had successful outerloop run in 2 weeks because of TLS and if this now affects innerloop runs, we'll need a revert if we don't have a fix.

**Comment by kunalspathak** [comment]
The fix is in https://github.com/dotnet/runtime/pull/104516 and waiting for review. The outerloop run passed with my fix - https://dev.azure.com/dnceng-public/public/_build/results?buildId=746922&view=results.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/runtime/pull/104516
