### ISSUE TITLE
`Microsoft.Extensions.Diagnostics.Metrics.Tests.DefaultMetricsFactoryTests.MeterDisposeTest` timing out in CI

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#105189]
Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=748576&view=results
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-07088e4a8ca14bedb8/Microsoft.Extensions.Diagnostics.Tests/1/console.cff7e3c3.log?helixlogtype=result

Note this run does not set any stress environment variables except `DOTNET_TieredCompilation=0`.

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=749840
Build error leg or test failing: Microsoft.Extensions.Diagnostics.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/105234

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "'Microsoft.Extensions.Diagnostics.Tests' END OF WORK ITEM LOG: Command timed out",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=748576
**Error message validated:** `['Microsoft.Extensions.Diagnostics.Tests' END OF WORK ITEM LOG: Command timed out`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/22/2024 7:37:09 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[750592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750592)|dotnet/runtime|[Microsoft.Extensions.Diagnostics.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750592&view=ms.vss-test-web.build-test-results-tab&runId=19006188&resultId=215148)|dotnet/runtime#105260|
|[749840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749840)|dotnet/runtime|[Microsoft.Extensions.Diagnostics.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749840&view=ms.vss-test-web.build-test-results-tab&runId=18999110&resultId=215122)|dotnet/runtime#105234|
|[748576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748576)|dotnet/runtime|[Microsoft.Extensions.Diagnostics.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=748576&view=ms.vss-test-web.build-test-results-tab&runId=18933956&resultId=215098)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|3|3|

**Comment by tarekgh** [comment]
Closing this as I believe https://github.com/dotnet/runtime/pull/105259 addressed the issue.
