### ISSUE TITLE
Implement DebugSettings.LayoutCycleTracingLevel

### ISSUE THREAD

**Issue by daltzctr** [dotnet/runtime#105100]
### Description

Tracing LayoutCycleExceptions in MAUI is an impossible problem where MAUI devs just offer the solution of "remove code until it works again". This is unacceptable in large projects. WinUI already has a mechanism for determining the cause of Layout Cycles.

https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.debugsettings.layoutcycletracinglevel?view=windows-app-sdk-1.5

MAUI should implement this in a reasonable manner and enable this functionality default for debug builds.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

Getting the `PlatformView` and applying to that works "somewhat" well. I'm thinking of appending a mapping to every control to handle this.

**Comment by tommcdon** [comment]
Closing this issue as it does not seem related to dotnet/runtime.  I suggest re-opening in https://github.com/dotnet/maui.
