### ISSUE TITLE
Windows build break because of System.Security.Cryptography

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#105126]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=747204
Build error leg or test failing: Build / linux-x64 debug Libraries_AllConfigurations / Build product
Pull request: https://github.com/dotnet/runtime/pull/105113

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Use of unassigned local variable 'symmetricKeyMaterialLength'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Introduced in https://github.com/dotnet/runtime/pull/105121

cc: @stephentoub 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=747204
**Error message validated:** `[Use of unassigned local variable 'symmetricKeyMaterialLength'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/19/2024 5:28:04 AM UTC

**Comment by jkotas** [comment]
Fixed by #105121
