### ISSUE TITLE
`LibraryImportGenerator` fails when `LibraryImportAttribute` is aliased

### ISSUE THREAD

**Issue by karakasa** [dotnet/runtime#105137]
### Description

`LibraryImportGenerator` fails when `LibraryImportAttribute` is aliased with `using` statements and there're >=2 methods in a class.

### Reproduction Steps

```C#
using System.Runtime.InteropServices;

namespace NetPlayground;

using Import = LibraryImportAttribute;

internal static partial class TestImport
{
    [Import("somedll.dll")]
    public static partial void SomeFunction(int a);

    [Import("somedll.dll")]
    public static partial void SomeFunction2(int a);
}
```

### Expected behavior

It compiles.

### Actual behavior

It won't compile:

> Error	CS8795	Partial method 'TestImport.SomeFunction2(int)' must have an implementation part because it has accessibility modifiers.	NetPlayground	D:\XXX\NetPlayground\TestImport.cs	13	Active	

### Regression?

Don't know.

### Known Workarounds

Do not use the alias statement.

Somehow if there's only one import in the class, it compiles:

```C#
using System.Runtime.InteropServices;

namespace NetPlayground;

using Import = LibraryImportAttribute;

internal static partial class TestImport
{
    [Import("somedll.dll")]
    public static partial void SomeFunction(int a);
}
```

### Configuration

IDE: VS Community 2022 17.9.0 Preview 1
.NET: Windows .NET 8.0.1 x64

### Other Information

It seems the second method isn't recognized as in `LibraryImports.g.cs`:

```C#
// <auto-generated/>
namespace NetPlayground
{
    internal static unsafe partial class TestImport
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("somedll.dll", EntryPoint = "SomeFunction", ExactSpelling = true)]
        public static extern partial void SomeFunction(int a);
    }
}
```

### Remarks

The `using` statement can be helpful when the code is targetting at both >=7.0 and older versions:

```C#
using System.Runtime.InteropServices;

namespace NetPlayground;

using Import =
#if NET7_0_OR_GREATER
    LibraryImportAttribute;
#else
    DllImportAttribute;
#endif

internal static partial class TestImport
{
    [Import("somedll.dll")]
    public static
#if NET7_0_OR_GREATER
        partial
#else
        extern
#endif
        void SomeFunction(int a);
}
```

With the bug, the code needs to be like this:
```C#
using System.Runtime.InteropServices;

namespace NetPlayground;

internal static partial class TestImport
{
#if NET7_0_OR_GREATER
        [LibraryImport("somedll.dll")] public static partial
#else
        [DllImport("somedll.dll")] public static extern
#endif
        void SomeFunction(int a);
}
```

**Comment by jkoritzinsky** [comment]
@CyrusNajmabadi could this be a bug in Roslyn's `ForAttributeWithMetadataName`? We don't do additional filtering of methods on attributes after `ForAttributeWithMetadataName` gives its results.

**Comment by CyrusNajmabadi** [comment]
@jkoritzinsky Yup.  It's a bug on my side.  Working on fix now.

**Comment by CyrusNajmabadi** [comment]
Fix at https://github.com/dotnet/roslyn/pull/74468.

**Comment by CyrusNajmabadi** [comment]
@jkoritzinsky This got auto-closed by github.  Just wanted to double-check with you that that's ok with whatever process you guys follow here in dotnet/runtime.  The customer will get the fix whenever they update their SDK to some version that includes a version of the Roslyn compiler containing my fix.

**Comment by jkoritzinsky** [comment]
Yeah this being closed with the PR follows our process.

**Comment by CyrusNajmabadi** [comment]
Thanks!
