### ISSUE TITLE
[API Proposal]: Expose JsonPropertyInfo.MemberName

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#105155]
### Background and motivation

Context: https://github.com/dotnet/aspnetcore/issues/56318#issuecomment-2239542228

As part of investigating writing a OpenAPI transformer to populate schema descriptions from XML documentation for types until https://github.com/dotnet/aspnetcore/issues/39927 is available, I ran into a rough edge where I can't get the canonical name of a property on a class to use to form an XPath expression to find the corresponding documentation for the member.

`JsonPropertyInfo.Name` gets me the name the JSON serializer ues, but when not using PascalCase naming for properties, that doesn't align with the case-sensitive name needed for the XPath expression.

The `JsonPropertyInfo` instance does have the member's proper name, but it's internal:

https://github.com/dotnet/runtime/blob/6aa28625e3b86ae6894ab85ce592786f7c440ae0/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs#L224

Exposing it would be useful for a scenario such as this, rather than needing to infer it by convention in some way (e.g. find all the members with reflection separately then use a case-insensitive lookup to find it using the serialized name).

/cc @captainsafia

### API Proposal

```diff
System.Text.Json.Serialization.Metadata;

public abstract class JsonPropertyInfo
{
+   public string? MemberName { get; }
}
```

### API Usage

Illustrative example (ignore how unperformant it would be):

```csharp
public Task TransformAsync(
    OpenApiSchema schema,
    OpenApiSchemaTransformerContext context,
    CancellationToken cancellationToken)
{
    // Find the XML documentation file
    var thisAssembly = GetType().Assembly;
    var path = Path.GetDirectoryName(thisAssembly .Location) ?? Environment.CurrentDirectory;
    var xml = Path.Combine(path, $"{thisAssembly.Name}.xml");

    // Load it
    using var reader = XmlReader.Create(xml);
    var xpath = new XPathDocument(reader);
    var navigator = xpath.CreateNavigator();

    // Find the <summary> for the property, if any
    var propertyName = $"{context.JsonPropertyInfo.DeclaringType.FullName}.{context.JsonPropertyInfo.MemberName}";
    var description = navigator.SelectSingleNode(
        $"/doc/members/member[@name='P:{propertyName}.']/summary");

    // Use it for the description's text
    if (!string.IsNullOrEmpty(description?.InnerXml))
    {
        schema.Description = description.Value.Trim();
    }

    return Task.CompletedTask;
}
```

### Alternative Designs

Have the `System.Reflection.PropertyInfo` associated with the schema's member made available via in the `OpenApiSchemaTransformerContext` instance, if available, instead.

### Risks

Unsure.

**Comment by eiriktsarpalis** [comment]
You can always peek inside the `JsonPropertyInfo.AttributeProvider` property which effectively gives you the `MemberInfo`. Starting with .NET 9 it's also being populated by the source generator.

**Comment by martincostello** [comment]
Thanks for the tip - I'll take a look 👀

**Comment by martincostello** [comment]
Thanks -that works enough for what I'm trying to achieve until there's an in-box solution for XML documentation:

```csharp
string? typeName = context.JsonPropertyInfo.DeclaringType.FullName;
string propertyName;

if (context.JsonPropertyInfo.AttributeProvider is PropertyInfo property)
{
    propertyName = property.Name;
}
else
{
    // Hacky assumptions to derive the name from context.JsonPropertyInfo.Name
}

var description = navigator.SelectSingleNode(
    $"/doc/members/member[@name='P:{typeName}{Type.Delimiter}{propertyName}']/summary");
```

**Comment by eiriktsarpalis** [comment]
That pattern match should be against MemberInfo since it could also be backed by a field. Otherwise this looks good.
