### ISSUE TITLE
Type <class name> appears to be immutable, but no constructor found to accept values.

### ISSUE THREAD

**Issue by FAAAAT** [dotnet/runtime#105318]
Hi guys, could someone help me with a werid issue about immutable class? I have a class looks like this:
![image](https://github.com/user-attachments/assets/956d5b5f-a461-4629-a2cd-d479393caa31)
As you can see I am using command line parser to create a command line tools. 

I can run debug output successfully but not with release output. The error is:

```
Unhandled exception. System.InvalidOperationException: Type SugonBMCMegarac.ScriptVerb appears to be immutable, but no constructor found to accept values.
   at CommandLine.Core.InstanceBuilder.BuildImmutable[T](Type, Maybe1, IEnumerable1, IEnumerable1, List1)
   at CommandLine.Core.InstanceBuilder.<>cDisplayClass1_01.<Build>b5()
   at CommandLine.Core.InstanceBuilder.Build[T](Maybe1, Func3, IEnumerable1, StringComparer, Boolean, CultureInfo, Boolean, Boolean, Boolean, IEnumerable1)
   at CommandLine.Parser.ParseArguments[T](IEnumerable1)
   at SugonBMCMegarac.Program.Main(String[])
```

My ENV:
Visual Studio 2022 preview
Dotnet Core 8.0
OS: windows&linux

**Comment by EgorBo** [comment]
I believe this issue belongs to https://github.com/commandlineparser/commandline and has nothing to with dotnet/runtime

**Comment by julealgon** [comment]
@FAAAAT in the future, when asking these types of questions, check if the repository you are targeting has the "Discussions" tab active. That's a more appropriate place for these questions, when available:
![image](https://github.com/user-attachments/assets/0e7c7e9a-2d4c-4e44-8ce4-e43b1299fa38)

**Comment by FAAAAT** [comment]
Thanks guys. I just thought this is related with the "Immutable Class". Silly me.
