### ISSUE TITLE
Invalid Zero Length check expression

### ISSUE THREAD

**Issue by MikeAlhayek** [dotnet/runtime#105383]
### Description

I noticed many invalid expression when checking for a zero elements in a collection.

Here is explanation

```
List<string> items = null;

if(items?.Count == 0)
{
    // This will evaluate false since null does not equals 0.
}

if(items?.Any() ==false)
{
    // This will evaluate false since items is null. which is translated to items != null && items.Count == 1
}
if(items == null || items.Count == 0)
{
    // This will evaluate true since items either null OR is not null and it's count is 0.
}

if(items?.Count > 0)
{
    // This check is okay because null items will return false and if the Count is 0 will also false.
}
```

### Reproduction Steps

na

### Expected behavior

correct check for 0 elements

### Actual behavior

invalid check for null or zero element

**Comment by huoyaoyuan** [comment]
These cases are not invalid - they are intentionally *not* handling null in this case.

**Comment by DL444** [comment]
Seeing your proposed changes in the PR, I would say that most of them doesn't really change the behavior in any way since they have preliminary explicit null checks (which begs the question on usefulness of null-coalescing operator in those cases).

For example, this change also doesn't change anything since `?.` evaluates to `default` if the operand is null. The only thing changed is style.

```diff
- if (metadataConstraints?.Count == 0)
+ if (metadataConstraints == null || metadataConstraints.Count == 0)
```

Some changes do have observable behavioral changes, but I doubt that the original behavior is intended. For example, here null meaning "default" seems pretty reasonable for me.

```diff
- bool isDefaultImplementedInterfaces = implementedInterfaces?.Length == 0;
+ bool isDefaultImplementedInterfaces = implementedInterfaces != null && implementedInterfaces.Length == 0;
```

**Comment by huoyaoyuan** [comment]
> For example, this change also doesn't really change anything since `?.` evaluates to `default` if the operand is null. The only thing changed is style.

This is incorrect. `?.` with value type will result in `(T?)null` instead of `(T?)default`. So `?.Count == 0` really means `!= null` **&&** `.Count == 0`.

**Comment by DL444** [comment]
> > For example, this change also doesn't really change anything since `?.` evaluates to `default` if the operand is null. The only thing changed is style.
> 
> This is incorrect. `?.` with value type will result in `(T?)null` instead of `(T?)default`. So `?.Count == 0` really means `!= null` **&&** `.Count == 0`.

You're right. I assumed `metadataConstraints` to be a reference type here.

**Comment by huoyaoyuan** [comment]
> I assumed `metadataConstraints` to be a reference type here.

It's not related to `metadataConstraints`. It's the result type of `Count` (int) being value type. The result type of `?.` is the same as `ResultType?`, which will be nullable value type when `ResultType` is value type.

**Comment by DL444** [comment]
> > I assumed `metadataConstraints` to be a reference type here.
> 
> It's not related to `metadataConstraints`. It's the result type of `Count` (int) being value type. The result type of `?.` is the same as `ResultType?`, which will be nullable value type when `ResultType` is value type.

I see. Can't believe how I did't already know that.

**Comment by stephentoub** [comment]
> I noticed many invalid expression when checking for a zero elements in a collection

Noticed where? I'm trying to understand what action is being requested with this issue. Do you see incorrect comparisons in this repo? Are you suggesting an analyzer? Are you suggesting the compiler is buggy? Thanks.
