### ISSUE TITLE
The Japanese string returned by the DateTime.ToLongDateString and DateOnly.ToLongDateString methods is incorrect.

### ISSUE THREAD

**Issue by niimima** [dotnet/runtime#105381]
### Description

The Japanese string returned by the DateTime.ToLongDateString and DateOnly.ToLongDateString methods is incorrect.

Expected string : 2024年7月24日
Actual string : 2024年7月月24日

![image](https://github.com/user-attachments/assets/5d35ccca-25ae-4717-a028-2c1d00b3c5db)
![2024-07-24_14h11_01](https://github.com/user-attachments/assets/ca75d872-b0a4-44cd-b591-28767f29818e)

### Reproduction Steps

1. Set region as below:
![image](https://github.com/user-attachments/assets/ee45fd1e-fe4b-434c-916e-c9e4003c561c)

2. Set long time string as below:
![image](https://github.com/user-attachments/assets/a623312c-d050-499c-8d92-fadf85077617)

Additional Information:
Sorry, this problem may need more step before step.2.
Calender changes japanese calendar.
![image](https://github.com/user-attachments/assets/edda978b-36d5-4091-accb-de28e81ce31b)

3. Use ToLongDateString methods as below:
```cs
var now = DateTime.Now;
var nowDateOnly = DateOnly.FromDateTime(now);

Console.WriteLine($"{nameof(DateTime)}");
Console.WriteLine($"{nameof(now.ToLongTimeString)} : {now.ToLongTimeString()}");
Console.WriteLine("");

Console.WriteLine($"{nameof(DateOnly)}");
Console.WriteLine($"{nameof(nowDateOnly.ToLongDateString)} : {nowDateOnly.ToLongDateString()}");
Console.WriteLine("");
```

### Expected behavior

DateTime.ToLongDateString() and DateOnly.ToLongDateString() should return "2024年7月24日".

### Actual behavior

DateTime.ToLongDateString() and DateOnly.ToLongDateString()  retrun "2024年7月月24日".

### Regression?

Sorry, I don't know.

### Known Workarounds

Specify a custom string format for DateTime.

### Configuration

.NET : 8.0
OS : Windows10
architecure : x64

> Do you know whether it is specific to that configuration?
Sorry, I don't konw.

**Comment by tarekgh** [comment]
On my machine I have tried the following code which should simulate the same repro but I couldn't get the same results
```C#
      CultureInfo.CurrentCulture = new CultureInfo("ja-JP");
      Console.WriteLine($"CurrentCulture: {CultureInfo.CurrentCulture.Name} ... {CultureInfo.CurrentCulture.DateTimeFormat.LongDatePattern} ");
      Console.WriteLine($"{DateTime.Now.ToLongDateString()} ");
```

This code produces `2024年7月24日水曜日`. 

Could you please run the following code on your machine and send the output? I am suspecting your machine has an older version of ICU library. I am running on Windows 11.

```C#
        public static void PrintEnvironmentInfo()
        {
            try { CultureInfo ci = CultureInfo.GetCultureInfo("ja-JP"); } catch {}

            Console.WriteLine($"{RuntimeInformation.OSDescription}");
            Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");
            try
            {
                foreach (ProcessModule module in Process.GetCurrentProcess().Modules)
                {
                    if (module.FileName.IndexOf("icu", StringComparison.OrdinalIgnoreCase) >= 0)
                        Console.WriteLine($".... {module.FileName}: {module.FileVersionInfo.FileVersion}");
                }

                System.Type? interopGlobalization = System.Type.GetType("Interop+Globalization, System.Private.CoreLib");
                if (interopGlobalization != null)
                {
                    MethodInfo? methodInfo = interopGlobalization.GetMethod("GetICUVersion", BindingFlags.NonPublic | BindingFlags.Static);
                    if (methodInfo != null)
                    {
                        int version = (int)methodInfo.Invoke(null, null)!;
                        Console.WriteLine($".... ICU Version: {new Version(version >> 24, (version >> 16) & 0xFF, (version >> 8) & 0xFF, version & 0xFF)}");
                    }
                }
                Console.WriteLine($".... UseNls:                 {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("UseNls", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
                Console.WriteLine($".... Invariant:              {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("Invariant", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
                Console.WriteLine($".... PredefinedCulturesOnly: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode")!.GetProperty("PredefinedCulturesOnly", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)} ....");
            }
            catch
            {
                Console.WriteLine($".... UseNls: Couldn't Evaluate it ....");
            }
        }
```

**Comment by niimima** [comment]
I run your program.  
The results are as follows: 

> CurrentCulture: ja-JP ... yyyy'年'MMM'月'd'日'  
> 2024年7月月25日  
> Microsoft Windows 10.0.19045  
> .NET 8.0.2  
> .... C:\\Windows\\SYSTEM32\\icu.dll: 64, 2, 0, 0 (WinBuild.160101.0800)  
> .... ICU Version: 64.2.0.0  
> .... UseNls:                 False ....  
> .... Invariant:              False ....  
> .... PredefinedCulturesOnly: False ....
> 
> ![](https://github.com/user-attachments/assets/39154010-46a8-4b94-bb9b-2021887951e8)

**Comment by tarekgh** [comment]
@niimima looks in your settings using long date pattern is `yyyy'年'MMM'月'd'日'`. Note, you have the separator `月` and you want to format the month as `MMM` which is abbreviated name of the month. This `MMM` month formatting will produce `7月`. That make the whole formatted date will look as `2024年7月月25日`. So, this is expected according to the format pattern used in your case.  

Try to check `sLongDate` setting in the registry on your machine `HKEY_CURRENT_USER\Control Panel\International` and change it to something like `yyyy'年'M'月'd'日'` or you can do that manually through the code like 

```C#
            CultureInfo.CurrentCulture = new CultureInfo("ja-JP");
            CultureInfo.CurrentCulture.DateTimeFormat.LongDatePattern = "yyyy'年'M'月'd'日'";
            Console.WriteLine($"{DateTime.Now.ToLongDateString()}");
```

I am closing the issue but feel free to send any more questions if you still have any.
