### ISSUE TITLE
NetworkStream read large data string

### ISSUE THREAD

**Issue by pyrotechnik** [dotnet/runtime#105359]
### Type of issue

Code doesn't work

### Description

Hello,
I'm having a problem receiving a large amount of data. I am creating a client in a c# application that connects to the north and draws data. The data with a string length of approx 10000 characters is no problem, but when I send a string of approx 25000 it only receives approx 14400 characters. When I test the connection through the Socket application I get the whole message. wonder where the problem may be. 
Thank you

```c#
public async Task<string> SendMessage(string message)
 {
            byte[] result = System.Text.Encoding.UTF8.GetBytes(message);
            if(!stream.WriteAsync(result, 0, result.Length).Wait(1000)){
                return "";
            }
            var buffer = new byte[50000];
            int received = await stream.ReadAsync(buffer);
            System.Diagnostics.Debug.WriteLine(buffer.Length);
            System.Diagnostics.Debug.WriteLine(received);
            var messageRecv = Encoding.UTF8.GetString(buffer, 0, received);
            return messageRecv;
}
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.readtimeout?view=net-8.0#system-net-sockets-networkstream-readtimeout

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Net.Sockets/NetworkStream.xml

### Document Version Independent Id

b9d1885f-c97d-9a93-b8d3-c1c62cf9566f

### Article author

@karelz

**Comment by stephentoub** [comment]
> int received = await stream.ReadAsync(buffer);

Read{Async} on a Stream does not guarantee reading as much as you asked for; it may return once it's read something even if it's less than you asked for. If you need the full amount, you can either loop until you've read as much as you need, or you can use an API like Stream.ReadExactly{Async} that does that looping for you.

**Comment by huoyaoyuan** [comment]
**It's a common mistake in network programming with any language.** One receive action can give you literally any non-zero bytes. In stream oriented protocols like TCP, it's especially wrong to not prepend a length information for data.

TCP is *byte sequence*, with no package boundary. See also https://stackoverflow.com/questions/9563563/what-is-a-message-boundary .

**Comment by karelz** [comment]
Triage: Answered above, closing. If you think we missed anything, feel free to reopen with more details.
