### ISSUE TITLE
Add package readmes to shared framework packages

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#105334]
This issue tracks adding package readmes to the shared framework packages:
- Microsoft.NETCore.App.Ref
- Microsoft.NETCore.App.Runtime*
- Microsoft.NETCore.App.Host*
- Microsoft.NETCore.App.Crossgen2*

Other packages under src/installer, next to the shared framework packages which might also be interesting:
- Microsoft.DotNet.ILCompiler
- Microsoft.NETCore.DotNetAppHost

**Comment by ericstj** [comment]
First priority here would be microsoft.netcore.app.ref and microsoft.netcore.app.runtime.* which were identified as important by download counts in an effort being driven by @lyndaidaii.

For these we could probably just include some boilerplate that discourages direct use of these packages which are only meant to be consumed by the SDK.

**Comment by julealgon** [comment]
> For these we could probably just include some boilerplate that discourages direct use of these packages which are only meant to be consumed by the SDK.

A brief explanation or link to what App.Ref packages are and why they exist would also be good to put there IMHO, for people who inadvertently end up there.

And for those who end up there on purpose, I think explicitly listing which DLLs are included would be _really_ nice. I've had this need a couple times already and had to look elsewhere to find that information (I basically just downloaded the package and opened it in NuGet Package Explorer locally to inspect which files were there, which is a bit convoluted and unintuitive for most folks).

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic please investigate and follow up with owners of Readme content.

cc @ashnaga

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/runtime/commit/9c029c935ca7bd796c3d472484f8e98b91a63249
