### ISSUE TITLE
Target framework NET7.0/NET8.0 self-contained console application reserving around 3GB RAM on Windows7 system

### ISSUE THREAD

**Issue by gitjee** [dotnet/runtime#105388]
### Description

Self-contained console application with target framework net7.0 or net8.0. When executing the app on a Windows7 system, causes system memory usage to shoot up to around 3GB. Each separate run of the application causes 3GB increase in system memory usage. 

Issue is not observed when target framework is net6.0

Console application project contains only below two lines of code.
      _Console.WriteLine("Hello, World!");
      Console.ReadKey()_;

**Comment by huoyaoyuan** [comment]
TL;DR:

Windows 7 is end of support for .NET 7 and later. The new changes we've made in GC doesn't work very well with Windows 7.
To mitigate the memory issue, you can set the following to environment variables:
`DOTNET_GCName=clrgc.dll` - use the old gc engine
`DOTNET_EnableWriteXorExecute=0` - disable W^X feature

Windows 7 specific issues won't be fixed anymore.
