### ISSUE TITLE
Git Requirement 

### ISSUE THREAD

**Issue by dhusemann** [dotnet/runtime#1053]
Under windows requirements, [Git](https://github.com/dotnet/runtime/blob/master/docs/workflow/windows-requirements.md#git)
I haven't checked other build requirements, With the recent security issues in versions of GIT before 2.24, Should the requirement be updated?? Windows requirement is 2.22 or higher. 

reviewing GIT releases, each version got an updated 13 days ago. so 2.22.2 or higher??

**Comment by danmosemsft** [comment]
Hello, this value is intended to indicate the minimum version that will work to work in this repo. We don't plan to update the number whenever GFW issues a security release as we assume readers will install the latest version. However if you want to update this, feel free to offer a PR.

**Comment by dhusemann** [comment]
Will leave as is. Closing issue.
