### ISSUE TITLE
SerialPort.GetPortNames() Error

### ISSUE THREAD

**Issue by MaxFun** [dotnet/runtime#105361]
I'm using VS2022, .NET 8, enabled Windows Forms and getting error for " public static string[] GetPortNames();"
My "using System.IO.Ports;" is grayed out.
Tried adding "public class SerialPort : System.ComponentModel.Component{ }" but it did not fix the problem.

How do you use a serial port with VS2022, .NET 8, enabled Windows Forms?

**Comment by danmoseley** [comment]
Do you have a package reference to https://www.nuget.org/packages/System.IO.Ports/

**Comment by MaxFun** [comment]
Thanks for the link, that was the information I was looking for
