### ISSUE TITLE
string.Format() CompositeFormat overloads. Why no overload without IFormatProvider?

### ISSUE THREAD

**Issue by Timo-Weike** [dotnet/runtime#105459]
As written in the title. I came across the new type `CompositeFormat` and the [recommendation](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1863) to use this type for static format strings.

However I noticed that this recommendation bloats the code from `string.Format(<FormatStringVar>, args...)` to `string.Format(null, <CompositeFormatVar>, args...)`. Is there a reason for the missing overload which just takes a `CompositeFormat` instead of a string?

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
