### ISSUE TITLE
JIT: SVE Assertion failed 'targetReg != embMaskOp2Reg' during 'Generate code'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#105474]
```csharp
// Generated by Fuzzlyn v2.0 on 2024-07-25 13:40:05
// Run on Arm64 Windows
// Seed: 6880262867354271142-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armsha1,armsha256,armsve
// Reduced from 171.2 KiB to 0.4 KiB in 00:00:55
// Hits JIT assert in Release:
// Assertion failed 'targetReg != embMaskOp2Reg' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 40; hash 0xade6b36b; FullOpts)
//
//     File: C:\dev\dotnet\runtime\src\coreclr\jit\hwintrinsiccodegenarm64.cpp Line: 525
//
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static Vector<double> s_3;
    public static void Main()
    {
        var vr1 = Vector128.CreateScalar(10).AsVector();
        s_3 = Sve.FusedMultiplyAdd(vr1, s_3, s_3);
    }
}
```

cc @dotnet/jit-contrib  @dotnet/arm64-contrib

**Comment by TIHan** [comment]
cc @SwapnilGaikwad @a74nh

**Comment by a74nh** [comment]
Having trouble reproducing this.

With latest HEAD of Fuzzlyn and the same seed (6880262867354271142-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armsha1,armsha256,armsve) I'm not getting the same code. This is on Arm64-Linux.


Reproducing manually: 

```
        private static Vector<double> s_3;

        public static void RunClassFldScenarioVector128()
        {
            var vr1 = Vector128.CreateScalar(10).AsVector();
            s_3 = Sve.FusedMultiplyAdd(vr1, s_3, s_3);
        }
```

Gives build errors:

```
/home/alahay01/dotnet/runtime_sve/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.FusedMultiplyAdd.double.cs(377,40): error CS1503: Argument 1: cannot convert from 'System.Numerics.Vector<int>' to 'System.Numerics.Vector<double>' 
```

Which doesn't seem surprising.

**Comment by jakobbotsch** [comment]
Yeah, there was a bug in this version of Fuzzlyn that makes the source code version not roundtrip into the internal version used, specifically around numeric literals. I fixed that the other day in https://github.com/jakobbotsch/Fuzzlyn/commit/6c9be0646ae23dc0e2b5ab24c446ae7969b4db7d.

Can you try with manual `d` suffix? i.e.
```csharp
// Generated by Fuzzlyn v2.0 on 2024-07-25 13:40:05
// Run on Arm64 Windows
// Seed: 6880262867354271142-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armsha1,armsha256,armsve
// Reduced from 171.2 KiB to 0.4 KiB in 00:00:55
// Hits JIT assert in Release:
// Assertion failed 'targetReg != embMaskOp2Reg' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 40; hash 0xade6b36b; FullOpts)
//
//     File: C:\dev\dotnet\runtime\src\coreclr\jit\hwintrinsiccodegenarm64.cpp Line: 525
//
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static Vector<double> s_3;
    public static void Main()
    {
        var vr1 = Vector128.CreateScalar(10d).AsVector();
        s_3 = Sve.FusedMultiplyAdd(vr1, s_3, s_3);
    }
}
```

**Comment by jakobbotsch** [comment]
IIUC Kunal was working on this one in #105541. Although since he is OOF now I suppose someone needs to finish that PR.

**Comment by a74nh** [comment]
> Can you try with manual `d` suffix? i.e.

That fixes the build for me

> IIUC Kunal was working on this one in #105541. Although since he is OOF now I suppose someone needs to finish that PR.

Thanks - I should have spotted before diving in.

**Comment by amanasifkhalid** [comment]
> IIUC Kunal was working on this one in https://github.com/dotnet/runtime/pull/105541. Although since he is OOF now I suppose someone needs to finish that PR.

I think Tanner just wanted more patterns covered in the test that PR is adding. I can wrap this one up.

**Comment by a74nh** [comment]
> > IIUC Kunal was working on this one in #105541. Although since he is OOF now I suppose someone needs to finish that PR.
> 
> I think Tanner just wanted more patterns covered in the test that PR is adding. I can wrap this one up.

Awesome, thanks!
