### ISSUE TITLE
How to use Source Generator P/Invoke with Byte[] in struct properly?

### ISSUE THREAD

**Issue by kingsznhone** [dotnet/runtime#105462]
There is a native function that require a struct pointer as a input.
``` C#
[LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf16)]
[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
//[DllImport(LibraryName,CallingConvention = CallingConvention.Cdecl,CharSet = CharSet.Unicode)]
internal static partial nuint get_status(nint context, ref OutBuffer buffer);
```

This is my Struct definition in C#
``` C#
[StructLayout(LayoutKind.Sequential)]
public ref struct OutBuffer
{
    [MarshalAs(UnmanagedType.LPArray)]
    public byte[] src;
    [MarshalAs(UnmanagedType.SysUInt)]
    public nuint size;
    [MarshalAs(UnmanagedType.SysUInt)]
    public nuint pos;
}
```

DllImport work fine on this struct , But when I'm trying to migrate to source generator, IDE tells me 
SYSLIB1051 | The specified type is not supported by source-generated p/invokes.

**Comment by huoyaoyuan** [comment]
Structs used in `LibraryImport` must matches the exact layout of native definition. You need to use pointers, or use a [custom marshaller](https://learn.microsoft.com/dotnet/standard/native-interop/tutorial-custom-marshaller) to convert to such struct.

**Comment by kingsznhone** [comment]
> Structs used in `LibraryImport` must matches the exact layout of native definition. You need to use pointers, or use a [custom marshaller](https://learn.microsoft.com/dotnet/standard/native-interop/tutorial-custom-marshaller) to convert to such struct.

Thanks for reply, I'll go check it out.
