### ISSUE TITLE
Maui Blazor Hybrid app crashes on connected device after splash screen, but works on simulator

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/runtime#105421]
### Description

Hey all,

Been fighting with this for a while now. My app works fine on mac os, but on ios it only works on the simulator.

The same error occurs whether I send it to test flight or use a connected ios device (connected to a mac on my network)

It crashes after the splash screen displays.

Here is my debug config for ios:
```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	<BuildIpa>false</BuildIpa>
	<CodesignKey>iPhone Developer: Mitch Russell (HV48XX6D9U)</CodesignKey>
	<CodesignProvision>iOS Development AI</CodesignProvision>
	<ApplicationTitle>AlzBetter AI</ApplicationTitle>
	<ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
	<ApplicationVersion>1</ApplicationVersion>
	<MtouchLink>None</MtouchLink>
	<MtouchUseLlvm>True</MtouchUseLlvm>
	<EnableSGenConc>True</EnableSGenConc>
	<UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17+

### Did you find any workaround?

no

### Relevant log output

```shell
Here is the VS output window:
`INFO: 
INFO: Creating command connection...
INFO: /Users/mitch/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk.net9.0_17.2/17.2.9714-net9-p6/tools/bin/mlaunch --devname "Mitch’s iPhone" --killdev "/Users/mitch/Library/Caches/Xamarin/mtbs/builds/AbMobileMaui/2664623b18aaf6eba1b99c7c499104288933e927d68fa3e51a7b3eab74c210db/bin/Debug/net9.0-ios/ios-arm64/device-builds/iphone16.2-18.0/AbMobileMaui.app" --launchdev "/Users/mitch/Library/Caches/Xamarin/mtbs/builds/AbMobileMaui/2664623b18aaf6eba1b99c7c499104288933e927d68fa3e51a7b3eab74c210db/bin/Debug/net9.0-ios/ios-arm64/device-builds/iphone16.2-18.0/AbMobileMaui.app" -argument=-monodevelop-port -argument=10000 -argument=-connection-mode -argument=usb --setenv=__XAMARIN_DEBUG_PORT__=10000 --wait-for-unlock   -v --sdkroot "/Applications/Xcode.app/Contents/Developer" -sdk 18.0
INFO: [iOS Debugger] Connecting to "Mitch’s iPhone" over USB on port 10000...
INFO: Launching...
INFO: Starting debugger connection to the app 'AbMobileMaui'. Debugger port: 56501, Device port: 10000
INFO: Launching app 'AbMobileMaui' on device...
INFO: Xamarin.Hosting: Device discovery started
INFO: Using Xcode 15.4 found in /Applications/Xcode.app/Contents/Developer
INFO: Xamarin.Hosting: Connected to Mitch’s iPhone (00008130-000618A61003401C) in 00:00:00.0025563
INFO: Xamarin.Hosting: Device discovery event: GizmoPaired (00008301-A88EF1AA1180202E)
INFO: Xamarin.Hosting: Device discovery event: Connected (00008301-A88EF1AA1180202E)
INFO: Xamarin.Hosting: Device discovery event: Connected (00008130-000618A61003401C)
INFO: Xamarin.Hosting:     Xcode: /Applications/Xcode.app
INFO: Xamarin.Hosting:     Version: 7dbab91212 (refs/heads/main)
INFO: Xamarin.Hosting: Connected to Mitch’s Apple Watch Ultra (00008301-A88EF1AA1180202E) in 00:00:00.0031393
INFO: Xamarin.Hosting:     Xcode Version: 15.4
INFO: Xamarin.Hosting:     Verbosity: 1
INFO: Xamarin.Hosting: Xamarin.Hosting
INFO: xcrun devicectl -j /var/folders/d1/43d729sj4x56j9zw2b13bp7r0000gn/T/tmp8lB6CI.tmp -v device info lockState --device "Mitch’s iPhone"
INFO: 	? unlockedSinceBoot: true
INFO: 	? passcodeRequired: false
INFO: 	Saving JSON output file to /var/folders/d1/43d729sj4x56j9zw2b13bp7r0000gn/T/tmp8lB6CI.tmp
INFO: 	Command Completed, took 1.198 seconds
INFO: 	Using verbose logging.
INFO: 	? deviceIdentifier: 13AE7EF8-6B67-4A3E-966B-E232116C293C
INFO: 	Current device lock state:
INFO: xcrun devicectl -j /var/folders/d1/43d729sj4x56j9zw2b13bp7r0000gn/T/tmp2DYZiy.tmp -v device process launch --terminate-existing --device "Mitch’s iPhone" com.alzbetterai.app --monodevelop-port 10000 --connection-mode usb
INFO: 	Command Completed, took 1.319 seconds
INFO: The app 'com.alzbetterai.app' launched with pid 13367
INFO: 	Saving JSON output file to /var/folders/d1/43d729sj4x56j9zw2b13bp7r0000gn/T/tmp2DYZiy.tmp
INFO: 	Launched application with com.alzbetterai.app bundle identifier.
INFO: 	2024-07-20 18:51:57.867-0400  Acquired usage assertion.
INFO: 	2024-07-20 18:51:57.821-0400  Enabling developer disk image services.
INFO: 	Using verbose logging.
INFO: The application has been launched
INFO: 
INFO: [iOS Debugger] Connected to "Mitch’s iPhone" over USB on port 10000.
INFO: Debugger connection signal received
INFO: 	0x1a08c8ad8 - /usr/lib/system/libsystem_c.dylib : abort

INFO: 	0x100db29f0 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : monoeg_g_logv

INFO: 	0x100db2b38 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : monoeg_g_log

INFO: 	0x1be938734 - /usr/lib/dyld : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1e8c41254):0x1e8c41244  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..).....
INFO: 	0x100ed7b6c - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_jit_init_version

INFO: 	0x100cf58ec - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : xamarin_main

INFO: Debugger connection completed
INFO: Waiting for the debugger connection signal...
INFO: [iOS Debugger] Connected to "Mitch’s iPhone" over USB on port 10000.
INFO: [iOS Debugger] Connecting to "Mitch’s iPhone" over USB on port 10000...
INFO: [iOS Debugger] Connecting to "Mitch’s iPhone" over USB on port 10000...
INFO: [iOS Debugger] Connected to "Mitch’s iPhone" over USB on port 10000.
INFO: Connecting to debug stream from device...
INFO: Connecting to debug console stream...
INFO: Connecting to remote debugger on port 56501...
INFO: Connecting to debug stream from remote debugger...
INFO: 
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates

INFO: a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

INFO: 	0x100cf078c - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : xamarin_bridge_initialize

INFO: .
0x1e8c41254  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91 
INFO: 	0x100ed03c0 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mini_init

INFO: 	0x100e151e4 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_assembly_open

INFO:  ...T.#...{......
0x1e8c41264  31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  1........{...._.
0x1e8c41274  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  
INFO: 	0x100cf5034 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : xamarin_assembly_preload_hook

INFO: 	0x100e13540 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_assembly_request_open

INFO: 	0x100e13a24 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_assembly_request_load_from

INFO: 	0x100dbd2c4 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_log_write_os_log

INFO: 	0x100eda38c - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : load_aot_module

INFO: 	0x21fd43ef8 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill

INFO: 	0x100f022e4 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_runtime_setup_stat_profiler
	0x21fc8fafc - /usr/lib/system/libsystem_platform.dylib : <redacted>

INFO: 	0x10105545c - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : sigabrt_signal_handler.cold.1

INFO: 	0x100eed32c - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_handle_native_crash

INFO: 	0x100f029f4 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_dump_native_crash_info

INFO: 	0x100e15678 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_assembly_load_corlib
	0x100e10cbc - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : mono_init

INFO: 	0x100e15490 - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : invoke_assembly_preload_hook

INFO: .._..'.........T

The app has been terminated.
INFO: Closing debug connection from device (USB)
INFO: 	0x100f4542c - /private/var/containers/Bundle/Application/7EC5EFB6-C63D-4502-A196-4B7255011A81/AbMobileMaui.app/AbMobileMaui : main

INFO: Disposing input and output streams...
INFO: Disposing input and output streams...
INFO: Disposing console and debugger streams...
ERROR: An error occurred while writing to the debug stream. Details: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, UsbStream
ERROR: An error occurred when writing to the output stream. Details: net_io_readfailure, Operation canceled
INFO: Closing debug connection from remote debugger (TCP)
`
```

**Comment by caliberdigitalllc** [comment]
@rolfbjarne @PureWeen? Sorry, don't want to bug you guys too much, but I've been trying to get this going still, no luck.

**Comment by caliberdigitalllc** [comment]
@jeffschwMSFT I was able to get my device connected to my laptop to test with a direct connected device. Here's the logs that come up after the splash screen appears and we go right to the white screen:

Here are the unique errors extracted from the provided log:

Failed to force load assembly - System.Security.AccessControl.dll

Type: System.Security.Policy.Evidence
Exception: 'Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.'
Failed to force load assembly - System.Security.AccessControl.dll

Type: System.Security.AccessControl.AuthorizationRuleCollection
Exception: 'Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.'
Failed to force load assembly - System.Security.AccessControl.dll

Type: System.Security.AccessControl.PrivilegeNotHeldException
Exception: 'Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.'
Failed to force load assembly - System.IO.FileSystem.Watcher.dll

Type: System.IO.FileSystemWatcher
Exception: 'System.IO.FileSystem.Watcher is not supported on this platform.'
Failed to force load assembly - System.IO.FileSystem.Watcher.dll

Type: System.IO.InternalBufferOverflowException
Exception: 'System.IO.FileSystem.Watcher is not supported on this platform.'
Failed to force load assembly - System.Net.Quic.dll

Type: System.Net.Quic.QuicClientConnectionOptions
Exception: 'System.Net.Quic is not supported on this platform: {0}'
Failed to force load assembly - System.Net.Quic.dll

Type: System.Net.Quic.QuicListenerOptions
Exception: 'System.Net.Quic is not supported on this platform: {0}'
Failed to force load assembly - System.Net.Quic.dll

Type: System.Net.Quic.QuicReceiveWindowSizes
Exception: 'System.Net.Quic is not supported on this platform: {0}'
Failed to force load assembly - System.Net.Quic.dll

Type: System.Net.Quic.QuicServerConnectionOptions
Exception: 'System.Net.Quic is not supported on this platform: {0}'
Failed to force load assembly - System.Security.Principal.Windows.dll

Type: Microsoft.Win32.SafeHandles.SafeAccessTokenHandle
Exception: 'Windows Principal functionality is not supported on this platform.'
Failed to force load assembly - System.Security.Principal.Windows.dll

Type: System.Security.Principal.IdentityNotMappedException
Exception: 'Windows Principal functionality is not supported on this platform.'
Failed to force load assembly - System.Security.Principal.Windows.dll

Type: System.Security.Principal.IdentityReferenceCollection
Exception: 'Windows Principal functionality is not supported on this platform.'
Failed to force load assembly - System.IO.Pipes.AccessControl.dll

Type: System.IO.Pipes.PipeSecurity
Exception: 'Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.'
Failed to force load assembly - Microsoft.Win32.Registry.dll

Type: Microsoft.Win32.SafeHandles.SafeRegistryHandle
Exception: 'Registry is not supported on this platform.'
Failed to force load assembly - Microsoft.Win32.Registry.dll

Type: System.Security.AccessControl.RegistrySecurity
Exception: 'Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.'
Failed to force load assembly - System.Runtime.InteropServices.JavaScript.dll

Type: System.Runtime.InteropServices.JavaScript.JSExportAttribute
Exception: 'System.Runtime.InteropServices.JavaScript is not supported on this platform.'
Could not resolve assembly - Microsoft.VisualStudio.DesignTools.MobileTapContracts.dll

Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/9089F844-7390-4E2B-B8DB-E5A41A0088B4/Documents/AbMobileMaui.content/Microsoft.VisualStudio.DesignTools.MobileTapContracts.dll' or one of its dependencies.
Could not resolve assembly - Microsoft.VisualStudio.DesignTools.TapContract.dll

Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/9089F844-7390-4E2B-B8DB-E5A41A0088B4/Documents/AbMobileMaui.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.
UIBackgroundModes Configuration Issue

Message: You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.

**Comment by caliberdigitalllc** [comment]
@mattleibow  so I have a bit more info here - it seems it's iOS18. I just tested the app on an iOS 17 device and it loads fine.

That itself is still concerning though, because iOS 18 will be available to the public in 2 months, so whatever this issue is really needs to be fixed before iOS goes gold.

**Comment by jeffhandley** [comment]
@Redth Could you help us get this triaged from the MAUI side of things first to see it can be narrowed down?

**Comment by Redth** [comment]
@rolfbjarne @dalexsoto could you help take a look?

**Comment by dalexsoto** [comment]
This is fixed in .NET 9 Preview 7 once it is released, this goes back to https://github.com/dotnet/runtime/pull/105813

![Image](https://github.com/user-attachments/assets/d7f3bf78-9028-423f-bf28-a82bd7c5c3c3)

**Comment by caliberdigitalllc** [comment]
@dalexsoto  I'm not 100% convinced - this error is occurring on my testflight build in release mode as well. The exact same build works fine from testflight on iOS 17, but the error occurs on iOS 18.

**Comment by caliberdigitalllc** [comment]
I will of course try it on Preview 7, but if it's a matter of release vs debug, my error occurs on both.

**Comment by dalexsoto** [comment]
@caliberdigitalllc fair enough, I'll re-open this and you let us know :)

**Comment by caliberdigitalllc** [comment]
> @caliberdigitalllc fair enough, I'll re-open this and you let us know :)

Thanks man. Not trying to doubt you in any way, but I do think this fix needs to be validated on a testlight release build to be sure.

FWIW, here's my release build command for test flight:

dotnet publish -f net9.0-maccatalyst -c Release \
    -p:ArchiveOnBuild=true \
    -p:CreatePackage=true \
    -p:EnableCodeSigning=true \
    -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" \
    -p:CodesignProvision="MacOS Distribution" \
    -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist" \
    -p:UseHardenedRuntime=true
    
    
    And here's my config from CS Proj. If any of it's wrong, please do advise.

<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-maccatalyst|AnyCPU'">
    <CodesignKey>Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)</CodesignKey>
    <CodesignProvision>MacOS Distribution</CodesignProvision>
    <ApplicationTitle>AlzBetter AI</ApplicationTitle>
    <MtouchLink>SdkOnly</MtouchLink> 
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <MtouchEnableBitcode>false</MtouchEnableBitcode>
    <MtouchFastDev>false</MtouchFastDev>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
    <MtouchTlsProvider>Default</MtouchTlsProvider>
    <DebugSymbols>false</DebugSymbols>
    <DefineConstants>RELEASE</DefineConstants>
	<ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
	<ApplicationVersion>1</ApplicationVersion>
    <PublishTrimmed>true</PublishTrimmed>
</PropertyGroup>

**Comment by matouskozak** [comment]
> if it's a matter of release vs debug, my error occurs on both.

If it's the same issue as https://github.com/dotnet/runtime/pull/105813, I believe it can happen even in Release if you use `<UseInterpreter>true</UseInterpreter>` on iOS (is that correct @ivanpovazan ?).

**Comment by caliberdigitalllc** [comment]
> > if it's a matter of release vs debug, my error occurs on both.
> 
> If it's the same issue as #105813, I believe it can happen even in Release if you use `<UseInterpreter>true</UseInterpreter>` on iOS (is that correct @ivanpovazan ?).

This sort of speaks to requesting better documentation on what flags should be set for all of the target systems and release types, like what are the "best setups" in the CSProj for each.

**Comment by ivanpovazan** [comment]
hello @caliberdigitalllc!

Regarding the "best setups", ideally when you target iOS platforms you shouldn't have to enable intepreter and the default setting of the project file would give you the best performance. However, it is possible that some apps or referenced nuget packages are not AOT-compatible (require dynamic code) for which the AOT compiler is not able to generate code ahead of time. For such apps, enabling the interpreter is needed as otherwise the app would crash during runtime. This is documented in: https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0

Unfortunately, it seems that you are experiencing a bug with our previous .NET9 preview releases which made these configurations additionally confusing. As @dalexsoto mentioned, we fixed this for our next release and will validate it once it is out.

**Comment by caliberdigitalllc** [comment]
Thanks @ivanpovazan  :) I'll look forward to trying again in a week or two when P7 comes out.

**Comment by ivanpovazan** [comment]
@caliberdigitalllc preview 7 is now publicly available https://dotnet.microsoft.com/en-us/download/dotnet/9.0 

I verified that the template hybrid blazor app does not crash on startup in Release mode when `UseInterpreter=true`.
Could you please check it out with your application as well?

**Comment by caliberdigitalllc** [comment]
> @caliberdigitalllc preview 7 is now publicly available https://dotnet.microsoft.com/en-us/download/dotnet/9.0
> 
> I verified that the template hybrid blazor app does not crash on startup in Release mode when `UseInterpreter=true`. Could you please check it out with your application as well?

Yep! I should be pushing a fresh build out in the next couple of days compiled on P7. I'll let you know.

**Comment by caliberdigitalllc** [comment]
Preview 7 fixed this, thank you!
