### ISSUE TITLE
Inlined Struct wrapper .ctors are non-zero cost

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#10540]
(Some now fixed by https://github.com/dotnet/coreclr/pull/19429)

This is problematic for example when adding formatting and/or buffering capabilities over `Span<T>`

As seen in "Add support for `BufferWriter<T>` to the JsonWriter" https://github.com/dotnet/corefxlab/pull/2366

When a struct wraps a struct (but has no additional fields) it becomes a non-zero cost abstraction for its constructor (but not method calls) e.g. [sharplab.io](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKB3wIDoAlAVwDs4BLVAU2oGEB7VABxYAbdgCcAymIBuLAMbtkpMuUwBmKhHwAmKgHZyAb1y5yx/OsKbMUXADUWiLkJTIAFAEpTxg17PGpiKK4srgAvLiM7ADuuFweSn5mstQAsvG+AL6mvmoa+Db2iOJwovSycAQevj5kif6BuMgEYRHRuOKVkTFx7u4JdU2p6bXGWSNmORYEVgUOxaXlWlXjNXW4AUHIOuFd7Uu7Ha67Pb39iVtDfZnZ47mW+XZzJWVwqstmq3Ubjeo7beJvA77f6dNonU6+PzIVSXM5jSZ5ayPIrPcpQd7eSFmb7IGx/GLidEHQH/YEE0HdDy9CHjKFQWHXWoI+5IwrzF4AVgxuE+iRxHJaBy5ByJ/xJBLJ7QpsSp1KutLMyA5DPGY0SzOmD0KThcri4wU8KyxxmSaXlZjV6tuUxmyPZ5TeHUaBENH2NzpVFshGttbNRr1c4h0W1dmIVxguZrhxp9WqeCwDAJ+oZ57uhntGWNjrPjL3RhMaUBTvLpGdwlom1sRsxRCa54gFSuLaeVUcZ8IoFh0+sMkIA2il2HAABY8AAmAEkBEJXIOR+Op/whAB5fisHiMZDUAByPAnjCELEYR4A5u4ALqQu42M2QktjDu5ZD+qW92n8UQsAJwdixXAAfVkfor3UQ59VkdwwgAPgAkJwiAvwQIeM1oNglVH3UZ8Ez2N8/A/L9EB/KUAMULwkKDQNmmQSDQhg/9kBaRRENpa9cBQ2iSPQ8gVEwl8AVwsx8O/X8gxIpRyMdYMaLohjwiYys/FY9iZK45RO0aPioAE4whMIkT1Ho8SWNA/NMOkkjGKIZjFIsG8PFQ+jVJ4jTsIbbTcF0oiC0M7jjPaesbGohzZMaKyFLMJT7I4xy2zIDIgA)

Given
```csharp
using System.Runtime.CompilerServices;

public static class Program
{  
   public static void ViaClass()
   {
       var c = new C();
       c.M();
   }
 
   public static void ViaStruct1()
   {
       var s1 = new S1(new C());
       s1.M();
   }
     
   public static void ViaStruct2()
   {
       var s2 = new S2(new S1(new C()));
       s2.M();
   }
 
   public static void ViaStruct3()
   {
       var s3 = new S3(new S2(new S1(new C())));
       s3.M();
   }

   public static void ViaStruct4()
   {
       var s4 = new S4(new S3(new S2(new S1(new C()))));
       s4.M();
   }
 
   public static void ViaStruct5()
   {
       var s5 = new S5(new S4(new S3(new S2(new S1(new C())))));
       s5.M();
   }
}

public class C 
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public void M()
    {
    }
}

public struct S1
{
    private C _c;
  
    public S1(C c) => _c = c;    
    public void M() => _c.M();
}

public struct S2
{
    private S1 _s;
  
    public S2(S1 s) => _s = s;    
    public void M() => _s.M();
}

public struct S3
{
    private S2 _s;

    public S3(S2 s) => _s = s;    
    public void M() => _s.M();
}

public struct S4
{
    private S3 _s;

    public S4(S3 s) => _s = s;    
    public void M() => _s.M();
}

public struct S5
{
    private S4 _s;

    public S5(S4 s) => _s = s;    
    public void M() => _s.M();
}
```
Each additional wrapper introduces redundant work in the asm e.g.
```asm
Program.ViaClass()
    L0000: sub rsp, 0x28
    L0004: mov rcx, 0x7ffa88b77008
    L000e: call 0x7ffadf232520
    L0013: mov rcx, rax
    L0016: call C.M()
    L001b: nop
    L001c: add rsp, 0x28
    L0020: ret

Program.ViaStruct1()
    L0000: sub rsp, 0x28
    L0004: mov rcx, 0x7ffa88b77008
    L000e: call 0x7ffadf232520
    L0013: mov rcx, rax
    L0016: call C.M()
    L001b: nop
    L001c: add rsp, 0x28
    L0020: ret

Program.ViaStruct2()
    L0000: sub rsp, 0x28
    L0004: mov rcx, 0x7ffa88b77008
    L000e: call 0x7ffadf232520
    L0013: mov rcx, rax
    L0016: mov rax, rcx
    L0019: mov rcx, rax
    L001c: mov [rsp+0x20], rcx
    L0021: mov rcx, [rsp+0x20]
    L0026: cmp [rcx], ecx
    L0028: call C.M()
    L002d: nop
    L002e: add rsp, 0x28
    L0032: ret

Program.ViaStruct3()
    L0000: sub rsp, 0x28
    L0004: xor eax, eax
    L0006: mov [rsp+0x20], rax
    L000b: mov rcx, 0x7ffa88b77008
    L0015: call 0x7ffadf232520
    L001a: mov rcx, rax
    L001d: mov rax, rcx
    L0020: mov rcx, rax
    L0023: mov rax, rcx
    L0026: mov rcx, rax
    L0029: lea rax, [rsp+0x20]
    L002e: mov [rax], rcx
    L0031: mov rcx, [rsp+0x20]
    L0036: cmp [rcx], ecx
    L0038: call C.M()
    L003d: nop
    L003e: add rsp, 0x28
    L0042: ret

Program.ViaStruct4()
    L0000: push rdi
    L0001: sub rsp, 0x40
    L0005: lea rdi, [rsp+0x28]
    L000a: mov ecx, 0x6
    L000f: xor eax, eax
    L0011: rep stosd
    L0013: mov rcx, 0x7ffa88b77008
    L001d: call 0x7ffadf232520
    L0022: mov rcx, rax
    L0025: mov rax, rcx
    L0028: mov rcx, rax
    L002b: mov rax, rcx
    L002e: xor ecx, ecx
    L0030: mov [rsp+0x30], rcx
    L0035: mov rcx, rax
    L0038: lea rax, [rsp+0x30]
    L003d: mov [rax], rcx
    L0040: mov rcx, [rsp+0x30]
    L0045: mov [rsp+0x28], rcx
    L004a: mov rcx, [rsp+0x28]
    L004f: lea rax, [rsp+0x38]
    L0054: mov [rax], rcx
    L0057: mov rcx, [rsp+0x38]
    L005c: cmp [rcx], ecx
    L005e: call C.M()
    L0063: nop
    L0064: add rsp, 0x40
    L0068: pop rdi
    L0069: ret

Program.ViaStruct5()
    L0000: push rdi
    L0001: sub rsp, 0x50
    L0005: lea rdi, [rsp+0x28]
    L000a: mov ecx, 0xa
    L000f: xor eax, eax
    L0011: rep stosd
    L0013: mov rcx, 0x7ffa88b77008
    L001d: call 0x7ffadf232520
    L0022: mov rcx, rax
    L0025: mov rax, rcx
    L0028: mov rcx, rax
    L002b: mov rax, rcx
    L002e: xor ecx, ecx
    L0030: mov [rsp+0x40], rcx
    L0035: mov rcx, rax
    L0038: lea rax, [rsp+0x40]
    L003d: mov [rax], rcx
    L0040: xor ecx, ecx
    L0042: mov [rsp+0x38], rcx
    L0047: mov rcx, [rsp+0x40]
    L004c: mov [rsp+0x30], rcx
    L0051: mov rcx, [rsp+0x30]
    L0056: lea rax, [rsp+0x38]
    L005b: mov [rax], rcx
    L005e: mov rcx, [rsp+0x38]
    L0063: mov [rsp+0x28], rcx
    L0068: mov rcx, [rsp+0x28]
    L006d: lea rax, [rsp+0x48]
    L0072: mov [rax], rcx
    L0075: mov rcx, [rsp+0x48]
    L007a: cmp [rcx], ecx
    L007c: call C.M()
    L0081: nop
    L0082: add rsp, 0x50
    L0086: pop rdi
    L0087: ret
```

category:cq
theme:structs
skill-level:expert
cost:medium

**Comment by CarolEidt** [comment]
This was previously issue 18542 in dotnet/coreclr, and the repro is captured as JIT\Regression\JitBlue\GitHub_18542.

**Comment by benaadams** [comment]
This is much closer now as this chonk [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCEBXAMy5ilwDcNek1YAlDgDsMAS3wwWAYQj4ADjIA2fAMp8AbjLAxBwxsxYTpchQElpfCKt1QDRk9RoBtAGIbsAc1wAXRoZeyhJbA0GGEkOfAYxYw4NDF8A3AYQBmAATwwYGgBvGgYyhgA5CEkYBgBeBjoEOjRS8sVsSSMtABN6xoRyVupyhmU1LQK+hqbSGgBfGmEAZgZYbB7qjVyGXAwoDjAMRJgNpNwUjGK2srCCiKi1083JbZONgHlX3N0ARw5YkYADx5AoAPgYAH1YBdUpweHwhCNync+JFousXm9zpd0oEoTDcX5AgJRqMFktqJ5tPtDhgADLYXIQDgYAAUjOZrIA0mEeiwAIKsiAAShCtFWmK2Oz2ByODAQADUogDiEhrsjbuF0U8NtL3j0cakCclUkjRqiHhjnvqIMAAFYweWQu3280o7WPKXfXYAC2gx0hGAgAGtYu6tfcdd63sAIBBopDIFY4jAvh1VBgOLAesp7AgMEibgxPABZGAYf09GwTNnlysQasTD6ZmTVXCC/z+GG4GR6GB2DRhML+MXF4irJUqmBqtmup3HUXFkqaskyLgMOf1BpxDQaEXF0YrsknhgAFV9UAgAHcABIwDSqPhskURsmLDyr0Yuh39CBv79k1kVN02wTNsxgXNqgKAt+lpGAAPKINQ1ifo6EQspoVNY4Gh6GAuGwS43w/cdyCQJgUHPS8b3vR9nwPVdj1PSsr2vBgajYgBRBAjFbaoX2IylRgnHJ42iGxcHGVRJkg5dD3KMsKyrGtpLrJTGxUjQW1kdtO27Yxe37Qdh0kUdxVPBh/AreSyiYiyynneVXX6H83SE+zbg3OdfzqHcUn3GyyTsjzymIAB2Bh4Iw993I89dN2cmRMmYRhcAYkKGGCjLwsig4EMC0YSK/U8coIjRcHy4qyg/QqKU/alaSOTkWXZZqeT5QVhTHCVdSxGVGuOBA8y4GR/AgnplQ0VUkAFa9sBkDBsGALQNVGVQoD7bACl6/UpymmdyMhPRpyLVdFIbJtVPrZTmz4yQOwFLsez7AdXhMszi0tHUhuqEaxpzSbptm+bFuWmA2TCBVAYOhhjv2kV6ghI7p36OGAVO0Zzpuq71MurS7oep6DJe4zJBHbrhMnYbRvG6G1WBha+AYABxCsGfuF9EfYmA2J+yQ/tp6d6bmxmoAhyQoTRmBXzqykGrlBkmRajklfayR+SFYNupEmN+oVhVqf+yC6ZmkX7lW8p1s27bdahoXDqlt9iyxjTa2u13pO0tt7r056jLesnTIpj0o0ePmBYB+32efSG9um2HpwRuokal1GTuLcdVjjBMGAkqSZJ6OSqssisueR/aWDzlRpIrSDBOoIqyAYAANC2yhE5hyLuBhS3myQXyLiy45hhA9Bw7neZNtkACIEFyAAvaeZeL8Oacj/bhZBpatAVMAx+wfoOIN361+NqOze38HY7H5eLJynj95YVmMGjsWRUryTq4LhgAH4GHIOgjBsjoWLB+eYQA===):
```asm
    L0051: vxorps xmm0, xmm0, xmm0
    L0055: vmovdqu [rax], xmm0
    L0059: vmovdqu [rax+0x10], xmm0
    L005e: vmovdqu xmm0, [rsp+0xe0]
    L0067: vmovdqu [rsp+0x50], xmm0
    L006d: vmovdqu xmm0, [rsp+0xf0]
    L0076: vmovdqu [rsp+0x60], xmm0
    L007c: vmovdqu xmm0, [rsp+0x100]
    L0085: vmovdqu [rsp+0x70], xmm0
    L008b: vmovdqu xmm0, [rsp+0x50]
    L0091: vmovdqu [rsp+0xb0], xmm0
    L009a: vmovdqu xmm0, [rsp+0x60]
    L00a0: vmovdqu [rsp+0xc0], xmm0
    L00a9: vmovdqu xmm0, [rsp+0x70]
    L00af: vmovdqu [rsp+0xd0], xmm0
    L00b8: vmovdqu xmm0, [rsp+0xb0]
    L00c1: vmovdqu [rsp+0x20], xmm0
    L00c7: vmovdqu xmm0, [rsp+0xc0]
    L00d0: vmovdqu [rsp+0x30], xmm0
    L00d6: vmovdqu xmm0, [rsp+0xd0]
    L00df: vmovdqu [rsp+0x40], xmm0
    L00e5: vmovdqu xmm0, [rsp+0x20]
    L00eb: vmovdqu [rsp+0x80], xmm0
    L00f4: vmovdqu xmm0, [rsp+0x30]
    L00fa: vmovdqu [rsp+0x90], xmm0
    L0103: vmovdqu xmm0, [rsp+0x40]
    L0109: vmovdqu [rsp+0xa0], xmm0
    L0112: mov rax, [rsp+0x80]
    L011a: test rax, rax
```
Has trimmed down significantly; which looks to be copying to output stack?
```asm
       vxorps   xmm0, xmm0
       vmovdqu  xmmword ptr [rsp+48H], xmm0
       vmovdqu  xmmword ptr [rsp+58H], xmm0

G_M7880_IG03:
       vmovdqu  xmm0, xmmword ptr [rsp+38H]
       vmovdqu  xmmword ptr [rsp+08H], xmm0
       vmovdqu  xmm0, xmmword ptr [rsp+48H]
       vmovdqu  xmmword ptr [rsp+18H], xmm0
       vmovdqu  xmm0, xmmword ptr [rsp+58H]
       vmovdqu  xmmword ptr [rsp+28H], xmm0

G_M7880_IG04:
       mov      rax, gword ptr [rsp+08H]
       test     rax, rax
```
So will close
