### ISSUE TITLE
Building tests fails on a system without support for RSA+SHA1

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#105486]
I am trying to build and run the .NET runtime unit tests on a system where RSA+SHA1 is disabled. In general, arcade supports building in such environments (see https://github.com/dotnet/arcade/pull/12749) via the `FullAssemblySigningSupported` flag.

However, we still fail to build/run unit tests in that mode.

```
$ git rev-parse HEAD
4287101242331f7ed43e4ea14e3d2f909b205fd5
$ ./build.sh --subset clr+libs+host+packs+libs.tests /p:FullAssemblySigningSupported=false
...
  System.Text.Json.TestLibrary.Roslyn4.4 -> /home/omajid/runtime/artifacts/bin/System.Text.Json.TestLibrary.Roslyn4.4/Debug/netstandard2.0/System.Text.Json.TestLibrary.Roslyn4.4.dll
  System.Text.Json.SourceGeneration.Roslyn4.4.Tests -> /home/omajid/runtime/artifacts/bin/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/Debug/net9.0/System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll
  Microsoft.Composition.Demos.ExtendedCollectionImports -> /home/omajid/runtime/artifacts/bin/Microsoft.Composition.Demos.ExtendedCollectionImports/Debug/netstandard2.0/Microsoft.Composition.Demos.ExtendedCollectionImports.dll
  System.Text.Json.TestLibrary.Roslyn3.11 -> /home/omajid/runtime/artifacts/bin/System.Text.Json.TestLibrary.Roslyn3.11/Debug/netstandard2.0/System.Text.Json.TestLibrary.Roslyn3.11.dll
  System.Composition.Tests -> /home/omajid/runtime/artifacts/bin/System.Composition.Tests/Debug/net9.0/System.Composition.Tests.dll
  System.Text.Json.SourceGeneration.Roslyn3.11.Tests -> /home/omajid/runtime/artifacts/bin/System.Text.Json.SourceGeneration.Roslyn3.11.Tests/Debug/net9.0/System.Text.Json.SourceGeneration.Roslyn3.11.Tests.dll

Build FAILED.

FSC : error FS2014: A problem occurred writing the binary '/home/omajid/runtime/artifacts/obj/System.Formats.Cbor.Tests.DataModel/Debug/net9.0/System.Formats.Cbor.Tests.DataModel.dll': A call to StrongNameSignatureSize failed (Invalid Public Key blob) [/home/omajid/runtime/src/libraries/System.Formats.Cbor/tests/CborDocument/System.Formats.Cbor.Tests.DataModel.fsproj]
    0 Warning(s)
    1 Error(s)
```

Is there some way to configure fsc to not try to parse the (non-existing) strong name signature?

**Comment by vcsjones** [comment]
This might just be an issue with the F# compiler.

With this fsproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <OtherFlags>--keyfile:KeyPair.snk --publicsign+</OtherFlags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

I still get a compilation error from Fsc.

I don't know if there is anything for us to do here, other than noting that it looks like an issue that belongs in the `dotnet/fsharp` repo.

Note that it fails differently, depending on whether or not `--publicsign+` is used.

Without:

```
A call to SignFile failed (error:03000098:digital envelope routines::invalid digest)
```

Which is the error I would expect from OpenSSL on systems without RSA+SHA1.

And with the flag:

```
A call to StrongNameSignatureSize failed (Invalid Public Key blob)
```

So, the flag is doing _something_, but I don't know why publicsign does not work.

**Comment by omajid** [comment]
Can someone please move this issue to the fsharp repo then? Or shall I file another one there?

**Comment by vcsjones** [comment]
> Can someone please move this issue to the fsharp repo then? Or shall I file another one there?

I'll file a new issue there with a more specific issue for the problem. (But will leave this one open until I get that one opened)

**Comment by omajid** [comment]
Thanks!

**Comment by vcsjones** [comment]
Filed at https://github.com/dotnet/fsharp/issues/17451.

I am going to close this issue as there is nothing actionable for us here.
