### ISSUE TITLE
`Guid(ReadOnlySpan<Byte>)` throws if source span is not precisely sized

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#105473]
**`System.Guid(ReadOnlySpan<Byte>)`**

https://github.com/dotnet/runtime/blob/86cb7b9a5b8ba6fd034fec35602f8014d0ef2ecd/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L65-L68

**`System.Guid(ReadOnlySpan<Byte>)`**

https://github.com/dotnet/runtime/blob/86cb7b9a5b8ba6fd034fec35602f8014d0ef2ecd/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L82-L85

**Comment by stephentoub** [comment]
Thanks, but this is by design. When we added the span-based ctors, we chose to inherit the same constraint from the byte[]-based ctor.
