### ISSUE TITLE
Arm64/Sve: Validation for movprfx in emitter

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#105514]
As noted in https://github.com/dotnet/runtime/pull/100743#discussion_r1563072598 . Everytime we emit SVE instruction, we should check the last emitted instruction and if it is `movprfx`, then validate the things required for `movprfx` placement.

![image](https://github.com/user-attachments/assets/efc7e201-67a5-4b0d-9fd2-7412df265be2)

**Comment by a74nh** [comment]
priority:2 for RC1 snap : This is a functional correctness issue - if the rules are violated then the use is UNPREDICTABLE.

**Comment by mikabl-arm** [comment]
> Everytime we emit SVE instruction, we should check the last emitted instruction ...

Shouldn't this be done for any instruction and not just SVE instructions?

**Comment by a74nh** [comment]
Thoughts:

I'll be adding a new function, something like  `emitInsSanityCheckWithPrevious()`

If this check fails what do we do? Is this just an assert and exit?


We need the previous instruction. Calling `emitNewInstrCns()` (and friends) will set `emitLastIns` to this new instruction. 

One way is to add `emitPrevIns` tracking (I think I remember us trying to add that with the peephole optimisation). Advantage now is we can call the new checks from `emitInsSanityCheck()`.

If we don't have tracking, then we need to do the checking before creating the new instruction, manually passing in the `id`, `reg1`, `reg2` etc etc (just like how `ReplaceLdrStrWithPairInstr()` works).  Now we need to call our new check function before calling `emitNewInstrCns()` and this needs to be done in every Arm64 emit function.
