### ISSUE TITLE
Cannot use CryptoStream with read-only stream

### ISSUE THREAD

**Issue by avivanoff** [dotnet/runtime#105592]
### Description

This is re-opening of #25129 as it 2was over 6 years.

### Reproduction Steps

Create a CryptoStream with the read-only inner stream and perform read operations. Dispose of CryptoStream.

### Expected behavior

Dispose should succeed.

### Actual behavior

Dispose throws an exception.

### Proposed solution

Introduce CryptoStream constructor overload that would allow a proper behavior where CryptoStream.Dispose does not call Flush on the underlying stream when CryptoStreamMode is Read.

**Comment by bartonjs** [comment]
I'm curious... are you using CryptoStream because it's the best tool for the job, or are you using it just because some old samples told you to?

We certainly won't be changing the existing ctor/behavior, but since this is requesting a new overload that has different behavior we could entertain that... but perhaps I can instead convince you to abandon the type altogether :smile:.

**Comment by avivanoff** [comment]
@bartonjs, I would love to hear the alternatives. Here is our scenario. We have a stream with encrypted data (could be FileStream, NetworkSream, PipeStream, request stream from Kestrel, etc.).the data is also deflated. So we construct a chain of DeflateStream->CryptoStream and start reading and processing data. Convenient and easy.

**Comment by teo-tsirpanis** [comment]
You could create a proxy `Stream` class whose `Flush()` method does nothing. And in general it seems to me that doing nothing on `Flush()` is better than throwing `NotSupportedException`, especially on read-only streams.

**Comment by vcsjones** [comment]
As pointed out by @teo-tsirpanis, read-only Stream's should implement `Flush` as a no-op if they are read-only and Flush does nothing useful.

From [the docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.flush?view=net-8.0&redirectedfrom=MSDN#System_IO_Stream_Flush)

> In a class derived from [Stream](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-8.0) that doesn't support writing, [Flush](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.flush?view=net-8.0) is typically implemented as an empty method to ensure full compatibility with other [Stream](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-8.0) types since it's valid to flush a read-only stream.

Are you saying that `DeflateStream` will throw when a `Flush` is issued and it is read-only?

As a work around @teo-tsirpanis's suggestion seems reasonable, but I would also expect that calling `Flush` on a read-only stream does not result in an exception.

**Comment by avivanoff** [comment]
No, DeflateStream does not, [AspNetCore RequestStream](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/HttpSys/src/RequestProcessing/RequestStream.cs) does.

**Comment by stephentoub** [comment]
We should fix that stream in aspnetcore. Its flush should nop rather than always throwing.

**Comment by vcsjones** [comment]
I opened an issue in `aspnetcore` for `RequestStream`. https://github.com/dotnet/aspnetcore/issues/57064

**Comment by vcsjones** [comment]
aspnetcore fixed their stream implementations to not error on `Flush` for read only streams.

Since aspnet fixed their issue, and `CryptoStream` is working "As intended and within the contract of Stream" I don't know that we need a new API or change any behavior with `CryptoStream`.

@avivanoff does fixing the `Flush` implementation in aspnet address your needs?

**Comment by avivanoff** [comment]
It does.

**Comment by vcsjones** [comment]
Thanks! In that case, I am going to close this out as `CryptoStream` is working as intended, and the ASP.NET streams have been fixed.
