### ISSUE TITLE
NET8 : Nested await Task.WhenAll() doesn't work anymore after NET7->NET8 migration and is stuck with excessive CPU usage.

### ISSUE THREAD

**Issue by GitHubProUser67** [dotnet/runtime#105576]
### Description

In this application : https://github.com/GitHubProUser67/MultiServer3/tree/PerformanceImprovements/SpecializedServers/Horizon

(precisely the "performance" fork), the "Horizon" server, which is a sub-server part of the server infrastructure, stopped working after migrating to NET8.

When the server is initialized properly, this message is shown per game instance hosted:

![image](https://github.com/user-attachments/assets/11c45dfe-9fab-4c81-9744-4520a2ced049)

But when using NET8, this error is spammed, which indicate that the initialization process failed:

![image](https://github.com/user-attachments/assets/8a015f51-479c-452e-ba8c-3cd8d0939eb3)

And while the server is failing, the CPU usage goes quite high considering server is not doing anything:

![cpuusage](https://github.com/user-attachments/assets/47a7e866-af8d-4801-8102-985574f252e9)

### Reproduction Steps

Download the zipped folder at this url : https://github.com/GitHubProUser67/MultiServer3/tree/PerformanceImprovements

Switch the "Horizon" server target to NET8, try to boot the server, the initialization process will fail after a little.

### Expected behavior

The server should boot fine, and be usable when booted.

### Actual behavior

The main weird behaviour that I saw, is that NET8 is having some extremly weird starving when doing a "TryDequeue" like here:

![image](https://github.com/user-attachments/assets/e5b51aec-982d-4f3d-b50f-55cb66fc3ff9)

As shown in the performance graph, this code is what causes the CPU usage to get high, but I cannot understand why.

### Regression?

The regression happened with NET8, it works perfectly using NET7.

### Known Workarounds

There is one semi workaround I noticed:

Changing the order of the ticks here, actually make the issue happen, else sooner, or later, which is weird.

![image](https://github.com/user-attachments/assets/bb674ac4-fb5e-4309-9f7c-b6e31fef820d)

### Configuration

The code is running on .NET8 in this test case.

OS : Windows 11

CPU : x86_64

### Other information

The areas to check are mainly here:

https://github.com/GitHubProUser67/MultiServer3/blob/PerformanceImprovements/SpecializedServers/Horizon/MEDIUS/Medius/BaseMediusComponent.cs

and here:

https://github.com/GitHubProUser67/MultiServer3/blob/PerformanceImprovements/SpecializedServers/Horizon/MEDIUS/MediusClass.cs

**Comment by Clockwork-Muse** [comment]
> As shown in the performance graph, this code is what causes the CPU usage to get high, but I cannot understand why.

.... Because you're getting a bunch of unauthenticated connections, so of course what appears to be cleanup code would run?

Are you able to produce a more targeted minimal repro?

**Comment by GitHubProUser67** [comment]
Perhaps I wasn't clear, there is only one connection attempted.

I found weird that a single connection is being cleaned that much.

I will try to cook up a more minimal repo yes.

**Comment by GitHubProUser67** [comment]
OKAY, I found the issue with NET8 runtime, see that code:

![image](https://github.com/user-attachments/assets/d07680ca-e07a-4008-894f-1bc263e61049)

Doing this works:

![image](https://github.com/user-attachments/assets/cb0a2b82-7aa6-4422-9c87-f3a1155c1e87)

I will do a test case ASAP.

**Comment by GitHubProUser67** [comment]
Essentially the design is like follows:

-> Server thread tick various sub-class deriviated from the Medius base class, inside those "Server Ticks" there an other tick for every clients connected to that server.

When debugging the NET8 runtime, I noticed the code mentionned upper makes the software to comepletely crash, and NET8 is stuck on this code:

![image](https://github.com/user-attachments/assets/84b1ca38-8684-4654-84d3-5143fbcce748)

**Comment by danmoseley** [comment]
Checking in the debugger, how many tasks are you passing to WhenAll?

**Comment by GitHubProUser67** [comment]
Well, it varies, there isn't a defined number of tasks. In a server running normally, it can hover around hundreds of tasks multiplied by 5.

When a client connect and request/send a message, this is a task for each operations.

**Comment by GitHubProUser67** [comment]
PS: I forgot, this is also multiplied by the number of DME servers, so it can be up to 25+ multiplier to that already multiplied by 5 number.

**Comment by Clockwork-Muse** [comment]
> OKAY, I found the issue with NET8 runtime, see that code:
> 
> ![image](https://private-user-images.githubusercontent.com/127040195/352715225-d07680ca-e07a-4008-894f-1bc263e61049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjI4NzQsIm5iZiI6MTcyMjEyMjU3NCwicGF0aCI6Ii8xMjcwNDAxOTUvMzUyNzE1MjI1LWQwNzY4MGNhLWUwN2EtNDAwOC04OTRmLTFiYzI2M2U2MTA0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMzIyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjRkODczMWRiNWMwYWRmMWZkZjYzYTY5YzZmZTY0MTNkZWYyN2Q4YjI4Mjc5OWE2M2Y3NzMwNTE0NDAxZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HyjfFZJnjROg817YwNmSvpq1rOS-K2nBPbhB_uKSOQ8)
> 
> Doing this works:
> 
> ![image](https://private-user-images.githubusercontent.com/127040195/352715237-cb0a2b82-7aa6-4422-9c87-f3a1155c1e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjI4NzQsIm5iZiI6MTcyMjEyMjU3NCwicGF0aCI6Ii8xMjcwNDAxOTUvMzUyNzE1MjM3LWNiMGEyYjgyLTdhYTYtNDQyMi05Yzg3LWYzYTExNTVjMWU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMzIyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTEyNGM2NDk2ZjJmMjU0OTgyNDc5Y2MyYjE1MzVhZmNlNDkyMzBjMDA2NDhlODg3MmQ1NmZiNDhmNzU1OWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yGM6mWvvOqoJzBZ6vm-BRH3dBzZ21UCXm25C-Gb0QO0)
> 
> I will do a test case ASAP.

Strictly speaking those two versions don't have equivalent behavior - the first can run the ticks concurrently (whether it actually does is a different question) the second will serialize them.

**Comment by GitHubProUser67** [comment]
Yeah, in the example I posted I did the "quick" fix.

But using a parallel approach still works as long as I use ToArray (which itself is weird because it shouldn't be needed, as the type already is a ienumerable.

https://github.com/GitHubProUser67/MultiServer3/commit/7b0e175fc00aaca5e987e869fb9e2105414a81a1

**Comment by hez2010** [comment]
Exceptions can happen if `_scertHandler.Group` is modified while the `Task.WhenAll` is enumerating it, as we don't support enumerating a modified collection.

**Comment by GitHubProUser67** [comment]
This value is consistently being modified at any time since any input/output can queue/dequeue stuff. But why did it work before in that case?

Because it's true doing the ToArray is best regarding concurrent handling, but then, I have no clue why previous NET versions were apparently handling this case just fine. Did they copied the ienumerable instead?

**Comment by GitHubProUser67** [comment]
I will add 2 things I discovered:

- Doing this  ' await Task.WhenAll(_scertHandler.Group.ToArray().Select(c => Tick(c))); ' doesn't work, it still discard the EXACT same tasks.

- In the MUIS server, the same bug was encontered using the same code, the effect is a little different, this time, only one client at a time could connect, when 2nd client comes in, the WhenAll() simply refuse to work (seems stuck in a CPU loop, like the Medius server) until the first client disconnect. This glitch is fixed in the exact same way, by using the Parallel method:

**Comment by GitHubProUser67** [comment]
OKAY I made a 2nd big discovery, doing this works fine in NET8

' await Task.WhenAll(_scertHandler.Group.ToArray().Select(c => Tick(c))); '

Who is in charge of the DotNetty project in the Azure team?

**Comment by hez2010** [comment]
> This value is consistently being modified at any time since any input/output can queue/dequeue stuff. But why did it work before in that case?
> 
> Because it's true doing the ToArray is best regarding concurrent handling, but then, I have no clue why previous NET versions were apparently handling this case just fine. Did they copied the ienumerable instead?

It does copy the `IEnumerable`, even now this also holds. The issue is that the collection may be modified while `WhenAll` is copying your collection at

```cs
var taskList = new List<Task>();
foreach (Task task in tasks)
{
    taskList.Add(task);
}
```

**Comment by GitHubProUser67** [comment]
Yes, that explains why this code works : ' await Task.WhenAll(_scertHandler.Group.ToArray().Select(c => Tick(c))); '

Because we do a copy of the IEnumerable before the fact, so it essentially work on a copied version of the queue.

But the elephant in the room, is how previous versions of NET could actually work with the Group as is, in DotNetty code it clearly shows that there is multiples serializer possibles, and IEnumerable is one of them : 

![image](https://github.com/user-attachments/assets/cf00fd26-ab6d-4834-a602-825114c56cce)

So that imply that with NET8+ the IEnumerable serializer is not thread-safe anymore? weird.

**Comment by Clockwork-Muse** [comment]
> Because we do a copy of the IEnumerable before the fact, so it essentially work on a copied version of the queue.

Strictly speaking the "fixed" code has the same concurrent modification bug, it's just that the window is shorter.

> So that imply that with NET8+ the IEnumerable serializer is not thread-safe anymore? weird.

It's possible some other optimizations were done under the covers, but that's mostly irrelevant.
Unless an `IEnumerable` is explicitly documented as being threadsafe it is not, and iteration _during the copy_ is a problem.  If you're modifying an unsafe collection from multiple threads, you have larger application design issues that would need to be addressed, that are more likely to be the root cause of your problem.

This is part of why we're asking for a minimal, isolated repro, to eliminate potential issues like this.

**Comment by GitHubProUser67** [comment]
Okay, I will keep that in mind. I kinda started a re-vamp of this very queue to be less sensitive to this kind of issues. That said I used a concurrentBag, that doesn't lock while being read? I can be wrong.

**Comment by Clockwork-Muse** [comment]
> That said I used a concurrentBag, that doesn't lock while being read? I can be wrong.

There's essentially two different thread-safety guarantees.

 1. Object threadsafety, whether your object can be corrupted by concurrent modification/access.  `ConcurrentBag` is safe, `List` is not.
 2. Application threadsafety, where the overall state of your application is as you imagine.  No runtime-provided type can fulfill this.

Use of `ConcurrentBag` can fail at the second if you do something like iterate all elements then clear the collection, since the clear can be over a separate set of items.

**Comment by ericstj** [comment]
If I'm understanding the discussion here correctly, it sounds like external component had a concurrency bug and that became apparent when timing changed through a framework upgrade.  I'm going to resolve this as external.  Let me know if you'd still like help with anything.
