### ISSUE TITLE
HTTP/SSL stress Linux builds broken by PGO update

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#105560]
#105236 contains a PGO update that broke our stress builds on Linux.

```
  [ 63%] Built target cee_wks_core
  make: *** [Makefile:156: all] Error 2
  /repo/src/coreclr
##[error]Failed to build "CoreCLR component".
/repo/src/coreclr/runtime.proj(108,5): error MSB3073: The command ""/repo/src/coreclr/build-runtime.sh" -x64 -release -ci -os linux -pgodatapath "/repo/.packages/optimization.linux-x64.pgo.coreclr/1.0.0-prerelease.24369.3" -outputrid linux-x64 -cmakeargs "-DCLR_DOTNET_HOST_PATH=/repo/.dotnet/dotnet" -cmakeargs "-DCDAC_BUILD_TOOL_BINARY_PATH=/repo/artifacts/bin/coreclr/linux.x64.Release/cdac-build-tool/cdac-build-tool.dll"" exited with code 2.
##[error]/repo/src/coreclr/runtime.proj(108,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command ""/repo/src/coreclr/build-runtime.sh" -x64 -release -ci -os linux -pgodatapath "/repo/.packages/optimization.linux-x64.pgo.coreclr/1.0.0-prerelease.24369.3" -outputrid linux-x64 -cmakeargs "-DCLR_DOTNET_HOST_PATH=/repo/.dotnet/dotnet" -cmakeargs "-DCDAC_BUILD_TOOL_BINARY_PATH=/repo/artifacts/bin/coreclr/linux.x64.Release/cdac-build-tool/cdac-build-tool.dll"" exited with code 2.

Build FAILED.

```

Example build:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=755072&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=ebe1360c-fe50-5ebc-628a-48ef9bf66506&l=3028

**Comment by antonfirsov** [comment]
@jkotas any hints how to troubleshoot this?

**Comment by MichalStrehovsky** [comment]
You need to scroll up for the error message but it's "error: Error in reading profile /repo/.packages/optimization.linux-x64.pgo.coreclr/1.0.0-prerelease.24369.3/data/coreclr.profdata: unsupported instrumentation profile format version".

Likely a mismatched version of clang in whatever docker container is used to build this in that pipeline.

**Comment by jkotas** [comment]
You either need to build with `/p:NoPgoOptimize=true` or use clang that is close enough to clang-18 in official build images.
