### ISSUE TITLE
HttpRequestException Lacks StatusCode Information on ProxyTunnelError

### ISSUE THREAD

**Issue by cenceg** [dotnet/runtime#105546]
### Description

When HttpRequestException is thrown with ProxyTunnelError HttpRequestError, the StatusCode is not included. This behavior may not be ideal for scenarios involving web scraping where backconnecting proxy is utilized extensively.

In web scraping, we mostly do not connect to the proxy directly. Instead, a backconnecting proxy service is employed which dynamically assigns different proxies which is convenient to provide rotating proxies. The CONNECT request is critical as it is the point where the backconnecting proxy might reject a request. Typically, proxies communicate the nature of such rejections via HTTP status codes (e.g., 429 when request rate is too high, 502 when no available proxy). Some will use HTTP headers detailing the reason too.

Currently, we have to parse the Message to find the actual status code

**Comment by wfurt** [comment]
do you have packet capture of such exchange @cenceg ?

**Comment by cenceg** [comment]
Sure, here's the curl of backconnecting proxy response stating no desired proxy is available
![CONNECT error](https://github.com/user-attachments/assets/0fe69be2-223b-4b74-ad05-6c55cffd0111)

**Comment by cenceg** [comment]
> Sure, here's the curl of backconnecting proxy response stating no desired proxy is available ![CONNECT error](https://private-user-images.githubusercontent.com/39481432/352589814-0fe69be2-223b-4b74-ad05-6c55cffd0111.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDkwNDgsIm5iZiI6MTcyMjAwODc0OCwicGF0aCI6Ii8zOTQ4MTQzMi8zNTI1ODk4MTQtMGZlNjliZTItMjIzYi00Yjc0LWFkMDUtNmM1NWNmZmQwMTExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1NDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYTM0NmEzNTU5OWY2M2M3ZTExNzdjZGVjOGUwZGU3OGQxNTI3ODA5Zjc1ZTc0ZjdmMjRmNGYwMjFkMGI0ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V12gCfjoOJh3lAZ_OUp5meOz0KkXk6bX7PTpHcPF7W0)



> do you have packet capture of such exchange @cenceg ?

Sure, here's the curl of backconnecting proxy response stating no desired proxy is available

![CONNECT error](https://github.com/user-attachments/assets/f75692b2-239f-430b-8c40-44009b3461ea)
