### ISSUE TITLE
Arm64/Sve: Add test coverage for *Faulting* cases to make sure inactive lanes are zeroed out

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#105580]
See discussion: https://github.com/dotnet/runtime/pull/104502#discussion_r1693513563

**Comment by a74nh** [comment]
priority:2 for RC1 snap : Missing testing

**Comment by a74nh** [comment]
Assigned to myself, but @mikabl-arm is looking at it

**Comment by a74nh** [comment]
https://github.com/dotnet/runtime/pull/106139

**Comment by a74nh** [comment]
Fixed by #105580
