### ISSUE TITLE
Do I need to use IHostApplicationLifetime in timed background service

### ISSUE THREAD

**Issue by scorpionfly7** [dotnet/runtime#105564]
Hello,
I have implemented Background service in . Net Core API, it is timed background service. And I dont understand from your doc, do I need to use IHostApplicationLifetime somewhere ? or it has the IHostApplicationLifetime already implemented.
It similar to this:

```csharp
namespace TimedBackgroundTasks;

public class TimedHostedService : BackgroundService
{
    private readonly ILogger<TimedHostedService> _logger;
    private int _executionCount;

    public TimedHostedService(ILogger<TimedHostedService> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Timed Hosted Service running.");

        // When the timer should have no due-time, then do the work once now.
        DoWork();

        using PeriodicTimer timer = new(TimeSpan.FromSeconds(1));

        try
        {
            while (await timer.WaitForNextTickAsync(stoppingToken))
            {
                DoWork();
            }
        }
        catch (OperationCanceledException)
        {
            _logger.LogInformation("Timed Hosted Service is stopping.");
        }
    }

    // Could also be a async method, that can be awaited in ExecuteAsync above
    private void DoWork()
    {
        int count = Interlocked.Increment(ref _executionCount);

        _logger.LogInformation("Timed Hosted Service is working. Count: {Count}", count);
    }
}
```

**Comment by DL444** [comment]
You use it when your service needs notifications for application lifecycle events (`ApplicationStarted`, `ApplicationStopped`, `ApplicationStopping`) or to trigger application shutdown (`StopApplication()`). You don't need it if your service do not require these funcionalities. See [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime) for more information.

This is already implemented and registered as a service for you by the hosting infrastructure. Access it by constructor-based [dependency injection](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection). For example:

```diff
public class TimedHostedService : IHostedService, IDisposable
{
    private int executionCount = 0;
    private readonly ILogger<TimedHostedService> _logger;
    private Timer? _timer = null;
+   private IHostApplicationLifetime hostApplicationLifetime;

-   public TimedHostedService(ILogger<TimedHostedService> logger)
+   public TimedHostedService(ILogger<TimedHostedService> logger, IHostApplicationLifetime hostApplicationLifetime)
    {
        _logger = logger;
+       this.hostApplicationLifetime = hostApplicationLifetime;
    }

    public Task StartAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Timed Hosted Service running.");

        _timer = new Timer(DoWork, null, TimeSpan.Zero,
            TimeSpan.FromSeconds(5));

        return Task.CompletedTask;
    }

    private void DoWork(object? state)
    {
        var count = Interlocked.Increment(ref executionCount);

        _logger.LogInformation(
            "Timed Hosted Service is working. Count: {Count}", count);

+       if (count >= 10)
+       {
+           hostApplicationLifetime.StopApplication();
+       }
    }

    public Task StopAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Timed Hosted Service is stopping.");

        _timer?.Change(Timeout.Infinite, 0);

        return Task.CompletedTask;
    }

    public void Dispose()
    {
        _timer?.Dispose();
    }
}
```

**Comment by scorpionfly7** [comment]
@DL444  Thanks for the answer, but what is in my case hosted application? what will be stopped whole API?  I have Background service in .net core API ?

**Comment by DL444** [comment]
> @DL444 Thanks for the answer, but what is in my case hosted application? what will be stopped whole API? I have Background service in .net core API ?

Sorry I do not understand the question clearly. But `IHostApplicationLifetime` provides notifications for the entire application, not individual services. When you call `StopApplication()` the entire application stops.

**Comment by scorpionfly7** [comment]
@DL444 so, if I call StopApplication(), will it stop whole API? Because my Background Service not standalone project. It is just added inside API makes some CRUD operations.
