### ISSUE TITLE
RyuJIT and SIMD - suboptimal codegen when performing bitmask comparisons

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#10560]
```cs
    private static bool TestMask(ref Vector<byte> a, ref Vector<byte> b)
    {
        return (a & b) == Vector<byte>.Zero;
    }
```

This generates the codegen (x64):

```asm
00007FF82F4D1524  vmovupd     ymm0,ymmword ptr [rsi]  
00007FF82F4D1529  vmovupd     ymm1,ymmword ptr [rdi]  
00007FF82F4D152E  vpand       ymm0,ymm0,ymm1  
00007FF82F4D1533  vptest      ymm0,ymm0  
00007FF82F4D1538  sete        al 
```

The `vpand` instruction is unnecessary, as the comparison line could read simply `vptest ymm0,ymm1`, which sets both _ZF_ and _CF_ (see http://www.felixcloutier.com/x86/PTEST.html).

category:cq
theme:vector-codegen
skill-level:expert
cost:medium
impact:medium

**Comment by gfoidl** [comment]
The same CG-issue applies to `Vector128` and `Vector256` too.

Workaround is using `Sse41.TestZ(a, b)` explicitely.

**Comment by tannergooding** [comment]
Fixed by https://github.com/dotnet/runtime/pull/87089 as part of the general fixes to improve mask handling.

`x & y == Zero`, `~x & y == Zero` are generally handled across all 3 now; with AVX-512 also handling the cases that would emit `vptestnm+kortest`
