### ISSUE TITLE
JIT: Assertion failed '!varTypeIsMask(tree)' during 'Linear scan register alloc'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#105623]
```csharp
// Generated by Fuzzlyn v2.1 on 2024-07-28 20:13:41
// Run on X64 Linux
// Seed: 1985194660224925106-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 33.0 KiB to 0.5 KiB in 00:00:30
// Hits JIT assert in Release:
// Assertion failed '!varTypeIsMask(tree)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Linear scan register alloc' (IL size 55; hash 0xade6b36b; FullOpts)
// 
//     File: /__w/1/s/src/coreclr/jit/lsraxarch.cpp Line: 3113
// 
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static void Main()
    {
        uint[, ][] vr4 = default(uint[, ][]);
        var vr5 = Vector256.Create<sbyte>(0);
        var vr6 = vr4[0, 0][0];
        var vr7 = (sbyte)Sse42.Crc32(vr6, 0);
        var vr8 = Vector256.Create<sbyte>(vr7);
        Vector256<sbyte> vr9 = Avx512BW.VL.CompareLessThan(vr5, vr8);
        System.Console.WriteLine(vr9);
    }
}
```

SPMI collection captured on 0912e94a attached.
[6890D5D7.zip](https://github.com/user-attachments/files/16414023/6890D5D7.zip)

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch, PTAL.

**Comment by jakobbotsch** [comment]
@tannergooding Any idea why we mark the compare intrinsics as `HW_Flag_NoEvexSemantics`? From what I can tell over on https://www.felixcloutier.com/x86/pcmpgtb:pcmpgtw:pcmpgtd, these instructions do have an EVEX encoding form.

The assert here hits inside `BuildEvexIncompatibleMask` which does not expect to see a `TYP_MASK` tree.

**Comment by jakobbotsch** [comment]
Ah, it should be using the `Mask` variant of the intrinsic... looks like we end up flipping it into the non-mask variant at some point.

**Comment by jakobbotsch** [comment]
It looks like `fgMorphHWIntrinsic` flips the intrinsic from `CompareLessThanMask` to `CompareGreaterThan` (not preserving the "Mask" part). This logic was added in #104875 it looks like, so you can take a look @tannergooding?

**Comment by tannergooding** [comment]
> Any idea why we mark the compare intrinsics as HW_Flag_NoEvexSemantics? From what I can tell over on https://www.felixcloutier.com/x86/pcmpgtb:pcmpgtw:pcmpgtd, these instructions do have an EVEX encoding form.

The EVEX encodings here have different semantics due to returning the result in a `kmask` rather than a vector register, so they require additional handling and are only meant to be done via explicit conversion using the `NI_EVEX_Compare*Mask` ID instead + potentially a `ConvertMaskToVector` node if the consumer needs a vector. This helps ensures we get optimal code generation since the conversion back to a vector is extra code size and cost that is undesirable for 128/256-bit vectors if we can't consume it directly as a mask.

> This logic was added in https://github.com/dotnet/runtime/pull/104875 it looks like, so you can take a look @tannergooding?

Can do. We should definitely be preserving the mask part here, it's likely just a simple issue.
