### ISSUE TITLE
[API Proposal]: Overload ArgumentNullException.ThrowIfNull

### ISSUE THREAD

**Issue by Zombach** [dotnet/runtime#105644]
### Background and motivation

[CA1062: Validate arguments of public methods](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062)
For public APIs, you often have to check for ArgumentNullException
It is common for most public APIs to accept 3-4 or more arguments as input.

For example [Aspire](https://github.com/dotnet/aspire)
```csharp
public static IResourceBuilder<PythonProjectResource> AddPythonProject(
        this IDistributedApplicationBuilder builder, string name, string projectDirectory, string scriptPath,
        string virtualEnvironmentPath, params string[] scriptArgs)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(name);
        ArgumentNullException.ThrowIfNull(projectDirectory);
        ArgumentNullException.ThrowIfNull(scriptPath);
        ArgumentNullException.ThrowIfNull(virtualEnvironmentPath);
        ArgumentNullException.ThrowIfNull(scriptArgs);
       
       ..........
}
```
For example, add a method overload so that you can check 1-x at a time.
```csharp
public static void ThrowIfNull(
    [NotNull] object? argument,
    [NotNull] object? argument2,
    [NotNull] object? argument3,
    [CallerArgumentExpression(nameof(argument))] string? paramName = null,
    [CallerArgumentExpression(nameof(argument))] string? paramName2 = null,
    [CallerArgumentExpression(nameof(argument))] string? paramName3 = null)
{
    if (argument is null)
    {
        throw new ArgumentNullException(paramName);
    }

    if (argument2 is null)
    {
        throw new ArgumentNullException(paramName2);
    }

    if (argument3 is null)
    {
        throw new ArgumentNullException(paramName3);
    }
}

string argument= null!;
string argument2 = null!;
string argument3 = null!;
ArgumentNullException.ThrowIfNull(argument, argument2, argument3);
```

### Alternative Designs

Or even a method extension
```csharp
public static class ArgumentNullExceptionExtension
{
    public static void ThrowIfNull<T>([NotNull] this T? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
        where T: class
    {
        ArgumentNullException.ThrowIfNull(argument);
    }
}

string argument = null!;
argument.ThrowIfNull();
```

An attribute that triggers auto-validation
```csharp
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
public sealed class ThrowIfNullAttribute : Attribute
{
    public ThrowIfNullAttribute([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
    {
        if (argument is null)
        {
            throw new ArgumentNullException(paramName);
        }
    }
}

public void Method([ThrowIfNull] string argument)
{
    Code
}
```

**Comment by EgorBo** [comment]
> `ArgumentNullException.ThrowIfNull(argument, argument2)` would not be able to check both arguments individually if _argument2_ is a string. Such a call would go to the existing `public static void ThrowIfNull([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)` method rather than your new four-parameter method.

I guess this could be solved by appending `s` to the API name 🙂

**Comment by tannergooding** [comment]
This probably deserves some weigh in from @stephentoub and @bartonjs.

I'm not personally a fan of the proposed shape as I'd expect its very easy to get wrong or to misread and not see the failure.
Having many sequential assert checks is more verbose, but I don't think that's necessarily bad especially for something important like validation.

Happy to take it forward to API review if other people on the team feel differently, however.

**Comment by Zombach** [comment]
There are really a lot of questions.
But this topic is quite in demand.
That's why I brought this up for discussion.

**Comment by stephentoub** [comment]
Ooh, we could add C# syntax for this, maybe two exclamation points. (Ducks)

FWIW, I'm not personally excited at the idea of adding such ThrowIfNull(s) methods. I'd rather each check be its own thing, especially in light of other throw helpers that take multiple arguments that are all part of a single check.

**Comment by Zombach** [comment]
Of course, ideally it would be possible to do this through an attribute, but I can’t imagine how this could be implemented.
public void Method([ThrowIfNull] string argument)owIfNull] string argument)

**Comment by bartonjs** [comment]
I don't think it makes sense to do.  No matter how deeply we overload it, it will always compile with N+1 arguments when the (N+1)th element is a string... but then it means something different.

Sure, we can boost that with an analyzer that says "you passed in something other than a literal for a paramName", but that would false-positive on any wrapper.

Nothing stops individual projects from making their own version, of course... I just think it's a bit too much of a foot-gun vs the amount of utility it provides to be part of the BCL.

**Comment by bartonjs** [comment]
> Ooh, we could add C# syntax for this, maybe two exclamation points.

Yeah, but then someone would want to convert all of dotnet/runtime to use that, and where are you going to find someone willing to spend the day and a half it would take to review that big of a change?  Doesn't seem feasible to me... :smirk:

**Comment by jeffhandley** [comment]
@Zombach Thanks for submitting this and starting a good conversation about this idea. I'm closing it as not planned, but by all means if there are alternate approaches we can keep the comments going and reopen if a different approach emerges.
