### ISSUE TITLE
The `ICorProfilerInfo::GetModuleMetaData` function returns `CORPROF_E_UNSUPPORTED_CALL_SEQUENCE`, while another approach with `IMetaDataDispenserEx` works

### ISSUE THREAD

**Issue by yegor-pelykh** [dotnet/runtime#105603]
### Description

The `ICorProfilerInfo::GetModuleMetaData` function returns `0x80131363`, while another approach with getting metadata using `IMetaDataDispenserEx` works.

I need to get the method name by its `mdToken` from the .NET module.
I'm trying 2 approaches:
1) Call chain: `ICorProfilerInfo::GetModuleMetaData` -> `IMetaDataImport::GetMethodProps`
2) Call chain: `CoCreateInstance` to get `IMetaDataDispenserEx` -> `IMetaDataDispenserEx::OpenScope` -> `IMetaDataImport::GetMethodProps`

With the 1st method, `0x80131363` is sometimes returned when calling `ICorProfilerInfo::GetModuleMetaData`.
With the 2nd method, everything works correctly, and I can get the method name.

That is, there is a problem with the Profiler API.

I wouldn't want to use the second approach in my code in case of an error with the 1st method, since it requires initialization/uninitialization of COM, which I really want to avoid.

Moreover, despite the fact that `0x80131363` may indicate a too early call, other calls to `ICorProfilerInfo::GetModuleMetaData` occur **before these calls**, and the result is `S_OK`. Apparently, the problem is not the early call.
And why would the early call be so important if we are talking about just reading metadata from the module, located in the PE header?

Please could you fix this so that it is possible to get metadata with the profiler API anytime.

### Reproduction Steps

Call `ICorProfilerInfo::GetModuleMetaData`

### Expected behavior

return `S_OK`

### Actual behavior

return `CORPROF_E_UNSUPPORTED_CALL_SEQUENCE`

### Known Workarounds

Get method name using `IMetaDataDispenserEx` (call chain: `CoCreateInstance` to get `IMetaDataDispenserEx` -> `IMetaDataDispenserEx::OpenScope` -> `IMetaDataImport::GetMethodProps`)

**Comment by mdh1418** [comment]
Hi @yegor-pelykh, [`GetModuleMetaData`'s implementation macro](https://github.com/dotnet/runtime/blob/8ad16ce1597d78440b33b89865a25e32e8c3287f/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L4149) indicates that it is a synchronous ICorProfiler API. If synchronous APIs are not invoked through a callback, [the `CORPROF_E_UNSUPPORTED_CALL_SEQUENCE` error will be thrown](https://github.com/dotnet/runtime/blob/8ad16ce1597d78440b33b89865a25e32e8c3287f/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L250), so I'm suspecting that is what is happening in your case.

Only for Asynchronous APIs, those that are decorated with the Async version of the macro `PROFILER_TO_CLR_ENTRYPOINT_ASYNC_EX`, like `SetEventMask`, are APIs that the profiler can invoke directly.

For `GetModuleMetaData`, from this [note](https://github.com/dotnet/runtime/blob/f251b170fb1d1be8552e7e1f3238aca9bcc6bb7a/src/coreclr/inc/corprof.idl#L1064-L1065) it looks like the ModuleLoadFinished callback is [guarded](https://github.com/dotnet/runtime/blob/f251b170fb1d1be8552e7e1f3238aca9bcc6bb7a/src/coreclr/inc/profilepriv.inl#L677C24-L677C53) by the [IsProfilerTrackingModuleLoads condition](https://github.com/dotnet/runtime/blob/f251b170fb1d1be8552e7e1f3238aca9bcc6bb7a/src/coreclr/inc/profilepriv.inl#L649) requires the `COR_PRF_MONITOR_MODULE_LOADS` event mask to be set (settable directly by the async API `SetEventMask`), typically done during initialization of the profiler.

For example, in the GC basic profiler test, [the `COR_PRF_HIGH_BASIC_GC` event mask is set](https://github.com/dotnet/runtime/blob/f251b170fb1d1be8552e7e1f3238aca9bcc6bb7a/src/tests/profiler/native/gcbasicprofiler/gcbasicprofiler.cpp#L18), so once the runtime is hitting `GarbageCollectionStarted` and `GarbageCollectionFinished`, `GCBasicProfiler::GarbageCollectionStarted` and `GCBasicProfiler::GarbageCollectionFinished` are the respective callbacks.

So to invoke `GetModuleMetaData`, the event mask `COR_PRF_MONITOR_MODULE_LOADS` needs to be set while the profiler is initializing. Then the profiler will need to implement a callback for `::ModuleLoadFinished(ModuleID moduleId, HRESULT hrStatus)` within which it should be able to invoke `GetModuleMetaData` from its `ICorProfilerInfo` instance.


For the other calls in which `ICorProfilerInfo::GetModuleMetaData` returned `S_OK`, do you know how they were called? I'm thinking they were invoked through callbacks.
