### ISSUE TITLE
Source code compiled into `runtime.native.*` NuGet packages

### ISSUE THREAD

**Issue by fviernau** [dotnet/runtime#105732]
I'm trying to understand the applicable license for a couple of `runtime.native.*` packages.
In order to do so, I try to understand where the source code is located which can end up in the
compiled binaries. This was pretty much straight forward for non-native libs, but the following 

I wonder whether these are open source at all. Some of these do not have any code repository
linked in the NuGet package metadata and use the proprietary .NET library license, such as [1].
Any hints which are Open source and which source dirs are relevant for each would be awesome:

- `runtime.native.System.IO.Ports` 8.0.0
  - `runtime.linux-x64:runtime.native.System.IO.Ports` 8.0.0
- `runtime.native.System.Security.Cryptography.OpenSsl` 4.3.2
  - `runtime.ubuntu:16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl` 4.3.2
- `runtime.native.System.Net.Http` 4.3.0
- `runtime.native.System.IO.Compression` 4.3.0
- `runtime.win-arm64.runtime.native.System.Data.SqlClient.sni` 4.4.0

[1] https://www.nuget.org/packages/runtime.native.System.Security.Cryptography.OpenSsl

**Comment by teo-tsirpanis** [comment]
The source code for the first four native packages is located [here](https://github.com/dotnet/runtime/tree/c92fe4b55e4c40137423093d224f120ce8feeb54/src/native/libs/), except for `runtime.native.System.Net.Http` which is discontinued (the last version is [here](https://github.com/dotnet/corefx/tree/v3.1.32/src/Native/Unix/System.Net.Http.Native)). The middle three have at some point (I think .NET Core 2.0 but am not 100% sure) stopped being distributed in separate NuGet packages, and are instead bundled in the shared framework.

The `runtime.win-***.runtime.native.System.Data.SqlClient.sni` packages are proprietary.

**Comment by fviernau** [comment]
Thank you @teo-tsirpanis, this really helps me!

I have one follow up question, I hope you can also help me with. Let's just pick
`runtime.ubuntu:16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl` to illustrate the underlying general question: I suppose the code is located under `src/native/libs/System.Security.Cryptography.Native`.
Could any could code from outside of `src/native/libs/System.Security.Cryptography.Native` get compiled into the NuGet package? e.g. from `src/native/libs/Common` or maybe even from outside of `src/native/libs`, such as `src/native/external` ?

**Comment by fviernau** [comment]
Thank you @teo-tsirpanis ! 

> What are you trying to achieve BTW?

I'm trying to understand _what license terms apply_ to these packages. So, I want to figure out which code gets compiled in
and under what licenses that code is.

My understanding here is that for
- `runtime.native.System.IO.Ports`: There is only a bit code included from `Common` (sibling dir)
- `runtime.native.System.Security.Cryptography.OpenSsl`: is a metapackage, which does not contain a binary
- `runtime.*.runtime.native.System.Security.Cryptography.OpenSsl`:
  - This includes some headers from libraries and links against them `dynamically`, so
    the libraries won't get _included_ into the package but will needed to be _provided_  on the system..
