### ISSUE TITLE
Adding certificates to store using X509Certificate2 still fails ssl for Microsoft Ubuntu containers

### ISSUE THREAD

**Issue by Cjewett** [dotnet/runtime#105786]
### Description

We're mounting certificates in .pem format to a Linux container using Microsoft's Ubuntu Jammy images (not chiseled) and then using logic similar to this to add them to the store.
```
using X509Store store = new(Store.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite);
using X509Certificate2 certificate = new("/mnt/certificates/certificate.pem");
store.Add(certificate);
```
The connections still fail due to certs not being valid though. I can see it was added to the expected store path `home/app/.dotnet/corefx/cryptography/x509stores/my/12345.pfx` . We're using user and group 1654 (non-root container defaults). Is adding certs to the store at runtime (health check time for us) and have those certs be applied later during runtime supposed to work?

If I mount the .pem file to `/etc/ssl/certs` the connections work just fine. Also verified .pem works using curl and openssl s_client from within the container. We have one working path forward but a bit confused why the above didn't work if anyone has ideas or docs outlining how to approach this.

### Reproduction Steps

1. Add .pem file to store using X509Certificate2
2. Make request using HttpClient to a domain that would fail without the certificate existing

### Expected behavior

We would expect adding certificates to the store programmatically would allow us to hit the successfully validate. 

### Actual behavior

Receive error like we don't have the certificates added to store

### Known Workarounds

We can mount the .pem file to `/etc/certs/ssl` and it works fine

### Configuration

.NET 8
Microsoft's Ubuntu Jammy images (non-chiseled)
Running as root 1654

### Other information

We're mainly curious what the expected behavior is if there is documentation or an explanation on what to expect. Would be much appreciated, thank you!

**Comment by vcsjones** [comment]
> using X509Store store = new(Store.My, StoreLocation.CurrentUser);

The `My` store does not mean "trust this certificate". It's a collection of certificates that persist across application runs, and a store that .NET might look in to find a non-root certificate like for mTLS.

If you want to add it to a store and treat it as a certificate, you should add it to `StoreName.Root`.

**Comment by Cjewett** [comment]
@vcsjones I see. Thanks for the explanation and swapping to StoreName.Root did solve the problem! 

Possible you could shed light on why mounting certs to `/etc/ssl/certs` works and is loaded? We're trying to understand the different flows and land on a long-term solution that will jive well with non-root user, read-only root access, and move towards chiseled images. It looks like something created the .aspnet directory and does some stuff in there at runtime, but not clear to us how that all works.

**Comment by vcsjones** [comment]
> Possible you could shed light on why mounting certs to /etc/ssl/certs works and is loaded?

This is logically the "system" trust store. Putting a certificate there trusts it by OpenSSL (and any other software that happens to use the OS certificate bundle). This is reflected in .NET as `using X509Store store = new(StoreName.My, StoreLocation.LocalMachine);`. However that store is read-only from .NET, you add to it like you have been with the file system.

OpenSSL / Linux have no real concept of a user trust store, so .NET has its own concept of it. Certificates that go in the user root store only apply to .NET.

If you want the certificate trusted broadly by OpenSSL for all users in your container, it should go in `/etc/ssl/certs`.

If you want the certificate trusted for just the current user and only for .NET, you should use `X509Store` like you were originally trying to use.

**Comment by Cjewett** [comment]
Understood, thanks again for another explanation! Going to close this one. 

Figured I'd provide additional context incase anyone else might find it helpful.
- We don't want to bake the certificates into the container image because that requires a re-build of the image if changes occur. For us that means waiting on the CI/CD flow which isn't quick (legacy processes, etc). 
- Certificates issues happen suddenly (see DigiCert chaos today https://status.digicert.com/history). The ability for the operations team to make those changes quickly is important to us.
- We want to run non-root.
- We want to enable read only root filesystem.
- We'd like to avoid something like a startup script wrapper as the entrypoint to keep things simple. `dotnet run.dll` and move on with life. 

Certs are in k8s as config-maps.
Certs are mounted to container at deployment time.
Volume mounted to `/home` or `/home/.dotnet`.
Certificate installation health check that installs mounted health checks to volume and also continuously verifies communication with those certs are valid.
