### ISSUE TITLE
Name parsing in System.IO.Compression.ZipArchive

### ISSUE THREAD

**Issue by Clive321A** [dotnet/runtime#105729]
### Description

When a zip file contains a colon, the "Name" property is truncating the file name
See Attached debug.
![image](https://github.com/user-attachments/assets/27474f15-f019-4fd7-bc7b-c52b6508f2d5)

### Reproduction Steps

Create a zip file and add a file in with a colon in it.

### Expected behavior

Name is rendered correctly

### Actual behavior

Name is truncated

### Known Workarounds

None,

### Configuration

.NET 8 x64

**Comment by karakasa** [comment]
https://github.com/dotnet/runtime/blob/c86bcbb7a573bb09fcb1f4fcd7bc24323e9d6f44/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L1139-L1148

I can see `:` is treated like `/` or `\` on Windows. Is it because of NTFS ADS?

**Comment by Clive321A** [comment]
Ah damn good spot, I've been supplied a zip file with files that can not be extracted to windows.
