### ISSUE TITLE
Cross-Platform COM Interop

### ISSUE THREAD

**Issue by hypersw** [dotnet/runtime#10572]
**Goal: enable interop with native libraries with COM ABI and a reasonable subset of COM features on all supported platforms.**

*Related issue with generic discussion: https://github.com/dotnet/coreclr/issues/11279*
This issue is to list specific work areas required to achieve the functionality:

* RCW (Runtime Callable Wrappers).
	* Managed proxy for a native VTable.
	* AddRef on native IUnknown until managed proxy is finalized (or Marshal Release/FinalRelease).
	* Turn managed casts into QI calls to native IUnknown.
	* Turn reflection/dynamic into IDispatch(Ex) calls to native object.

* CCW (COM Callable Wrappers).
	* Generate VTable, expose native pointer to it.
	* Keep GC root until final release from native side.
	* Turn IDispatch calls into reflection/dynamic calls on the managed object.

* Marshalling.
	* Mostly the same as in PInvoke.
	* Non-preserve-sig handling:
		* HRESULT into Exception for RCW; Exception into HRESULT for CCW.
		* Out parameter vs. return value transform.
		* Pointer<->RCW and object<->CCW transform.
		
Supposedly, most of the implementation should already be available from the .NET Framework code. WinAPI implementations should be substituted with crude fallbacks for trivial cases (no activation scenarios, no cross-apartment call marshalling, no proxy/stubs).
	
Activation: manual from a DLL file, or possibly side-by-side scenarios. At first, activation is out of scope, suppose we create the first COM object with external means (e.g. Pinvoke + GetObjectForIUnknown).

Here are example scenarios for possible application of this functionality.
* CLR Debugger interfaces (ICorDebug et al). We have a success story of running the cross-platform implementation of debugger with native COM interop from C#, with Mono on Linux and Mac. Mono has huge problems with correctness of the implementation, yet if you're using only core features and trivial marshalling it's working enough to have a functioning debugger. The problems do not look fundamental, just of the quality sort. Obviously, we would now like to run the same code on CoreCLR.
* Visual Studio COM interfaces have proven a working example of a large-scale native-managed interop with native and managed parts mixed together with no clear separation. That's not exactly about porting, but that's a good example of a multi-technology app with native/managed interop API.
* A few of our own helper libraries on Windows are exposing COM interfaces for object-oriented interaction with the app. This experience is nice to have on any platform.

**Comment by AaronRobinsonMSFT** [comment]
Now that the [`ComWrappers`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers) API has been [enabled on all platforms](https://github.com/dotnet/runtime/issues/36582) where CoreCLR runs, I am considering this issue closed as it is now possible. What is still missing is a source generation tool similar to [C#/WinRT](https://github.com/microsoft/CsWinRT) but for COM.
