### ISSUE TITLE
Avoid building `StringBuilder` in `DefaultInterpolatedStringHandler`

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#105775]
When passing a builder to an interpolation `$".. {stringBuilder} .."` the builder is first converted to an string, duplicating the total allocation needed to evaluate this expression. Could `DefaultInterpolatedStringHandler` specially handle builders so that this doesn't happen?

**Comment by stephentoub** [comment]
I'm not excited at the idea of special-casing StringBuilder in DefaultInterpolatedStringHandler. If it's a problem to be solved, I'd rather it be solved by having StringBuilder implement ISpanFormattable.

**Comment by karakasa** [comment]
So is this an api-suggestion?

**Comment by stephentoub** [comment]
> So is implementing ISpanFormattable on StringBuilder an api-suggestion?

yup

**Comment by karakasa** [comment]
OK. Let me propose an issue.

**Comment by jeffhandley** [comment]
Closed with the creation of #105870
