### ISSUE TITLE
[9.0.100-preview.7.24375.12] Markdig nuget package thrown "The parser is in an invalid infinite loop while trying to parse inlines for block..." exception when parsering markdown string to html

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#105792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running 3rd part application with the latest .NET 9 build, BlazorStrap and Blog apps failed load page content during switching pages in applications. And the command prompt window throws ```"The parser is in an invalid infinite loop while trying to parse inlines for block [ParagraphBlock] at position ($0, 0, 0-107" exception```.

**Application Name**: BlazorStrap, Blog, OpenBullet2
**OS**： Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-9.0.100-preview.7.24375.12
**App or App Source checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174456

**Github Link:** 
https://github.com/chanan/BlazorStrap
https://github.com/sagebind/blog

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.303: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24371.4: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24375.12: Fail

### Expected Behavior

Switch back from "Shared Parameters" to "Contribute" successfully.
![image](https://github.com/user-attachments/assets/88b4feac-3f4d-40b2-9b6b-1d9a09b0e5db)

### Steps To Reproduce

The machine has dotnet-sdk-9.0.100-preview.7.24375.12 installed.
1. Copy BlazorStrap app from the location mentioned in the [devdiv bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174456).
2. Change the "BlazorStrap.Server.runtimeconfig.json" file to let the app run against with dotnet-sdk-dotnet-sdk-9.0.100-preview.7.24375.12. 
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.7.24374.12"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "9.0.0-preview.7.24373.9"
      }
    ],
3. Launch BlazorStrap.Server.exe.
4. Access http://localhost:5000/ from browser.
5. Click "Contribute" menu.
6. Click "Shared Parameters" menu.
7. Click "Contribute" menu.

### Exceptions (if any)

**Actual Result:**
Switch back from "Shared Parameters" to "Contribute" failed.
![image](https://github.com/user-attachments/assets/0c2cbb81-b1b1-43f2-801b-0fed4345a7d2)

**Stack Trace from Command Prompt:**
```
Unhandled exception rendering component: The parser is in an invalid infinite loop while trying to parse inlines for block [HeadingBlock] at position ($0, 0, 0-19
      System.InvalidOperationException: The parser is in an invalid infinite loop while trying to parse inlines for block [HeadingBlock] at position ($0, 0, 0-19
         at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
         at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
         at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
         at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
         at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
         at BlazorStrap_Docs.Helper.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in C:\Users\v-zhiyang\Desktop\YOURSELF\BlazorStrap\src\BlazorStrap-Docs\Helper\MarkdownToComponent.cs:line 93
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'cwy0vMhNv_dIuMXmt46dyA7Bj5ivmQY-xXaGYDTlK6s'.
      System.InvalidOperationException: The parser is in an invalid infinite loop while trying to parse inlines for block [HeadingBlock] at position ($0, 0, 0-19
         at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
         at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
         at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
         at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
         at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
         at BlazorStrap_Docs.Helper.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in C:\Users\v-zhiyang\Desktop\YOURSELF\BlazorStrap\src\BlazorStrap-Docs\Helper\MarkdownToComponent.cs:line 93
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### .NET Version

9.0.100-preview.7.24375.12

### Anything else?

**Minimal Repro steps (repro demo attached 
[MarkdownToHtmlDemo.zip](https://github.com/user-attachments/files/16425861/MarkdownToHtmlDemo.zip)):**
1.Create a Blazor Server App project.
2. Install Markdig nuget package.
3. Add a MarkdownToComponent.cs class file with following content:
```
    public class MarkdownToComponent : ComponentBase
    {
        [Parameter] public RenderFragment? ChildContent { get; set; }
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {

            string s = @"The following are **guide lines** on howto contribute. You input is always **welcomed** and **appreciated**.

### Feature Request
---
If you feel BlazorStrap is lacking a feature you need or just want please create a issue with the following.
* What does it do
* Why you feel it should exist
* How can it help others";
            string ms = Markdown.ToHtml(s);
        }
    }
```
5. Add above component to Counter.razor page.
```
<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
<MarkdownToComponent>Test</MarkdownToComponent>
```
7. Build the project.
8. Update the runtime.config file to run against with dotnet-sdk-dotnet-sdk-9.0.100-preview.7.24375.12. 
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.7.24374.12"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "9.0.0-preview.7.24373.9"
      }
    ],
```
10. Launch the project.
11. Access http://localhost:5000/ from browser.
12. Navigate to Counter page.
13. Refresh the Counter page 7 times.

Expected Result:
The Counter page refresh 7 time successfully.

Actual Result:
The Counter page refresh failed at the 7th refresh with following error:
```
System.InvalidOperationException: 'The parser is in an invalid infinite loop while trying to parse inlines for block [ParagraphBlock] at position ($0, 0, 0-107'

Stack Trace:
   at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
   at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
   at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
   at MarkdownToHtmlDemo.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in E:\Demos\MarkdownToHtmlDemo\MarkdownToHtmlDemo\MarkdownToComponent.cs:line 26
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```
**Findings:**

- 2 apps are all referenced Markdig nuget package and the exception in 2 apps are both thrown from Markdown.ToHtml() method which is used to convert a markdown file sting to html.
- We tried to reference the [Markdig (version 0.37.0) source code](https://github.com/xoofx/markdig/archive/refs/tags/0.37.0.zip) instead of install it from nuget package manager, it doesn't repro in debug mode. But if we enable compiler optimizations on debug mode for Markdig project, this issue will repro again. It doesn't have this issue on build#dotnet-sdk-9.0.100-preview.7.24371.4 . We think something changed with optimization code in 9.0.100-preview.7.24375.12 which cause this issue.
- The [Markdig](https://github.com/xoofx/markdig) nuget package is used by 5.8k users. It may affect more users in real world.
- This issue will occurs after switching pages in applications multiple times or refresh the page multiple times. The first time load the page can successful.

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Thanks @jeffschwMSFT for helping check this issue. Could you please help confirm if this is a blocker for .NET 9 Preview7?  
There is one another app also affected by this issue and that is 3 apps affected in our lab,

**Comment by jeffschwMSFT** [comment]
It would need investigation.  @jeffhandley could y'all take a look?  It looks like a 3rd party nuget break, but perhaps we had a subtle change causing the break.

**Comment by krwq** [comment]
I was able to pinpoint to https://github.com/dotnet/runtime/pull/104752 as a source of regression (f455188a11c).

This was done by doing semi-manual (rejecting obviously not culprits and repro requires refreshing the page) binary search between commits 1f70f0cc663b5d45f77840e9728386e5fa7944f9 and eedf30ebac80ca81b88c4c452614522a5ece1b27. I had to do it twice because first time I was getting AVs caused by https://github.com/dotnet/runtime/pull/104336 and then had to do it second time with revert of that commit - the AV is already reverted by https://github.com/dotnet/runtime/pull/105234 though.

I tried to run original repro after reverting https://github.com/dotnet/runtime/pull/104752 but I hit non-obvious merge conflict and it's already end of the day for me so will leave it here.

I didn't have much luck narrowing down the repro (other than removing Counter page and putting MarkDownToComponent directly in the Index but that also causes you need to refresh a bit more than 7 times) - it seems to be somewhere between Razor and Markdig - I've tried isolating Markdig piece (i.e. stressed this under multiple threads) but without luck and I'm not familiar with Razor enough to simplify this further quickly.

**Comment by AndyAyersMS** [comment]
Using the standalone repro the issue is in the codegen for 
```
1652: JIT compiled Markdig.Parsers.InlineProcessor:ProcessInlineLeaf(Markdig.Syntax.LeafBlock):this [Tier1 with Dynamic PGO, IL size=763, code size=6019, hash=0x0f931e6b]
```
This method has phi-refinements but does not leverage them for copyprop. Will need to dig in to see where things change.

**Comment by AndyAyersMS** [comment]
Here's a simple repro case 
```C#
// DOTNET_TieredCompilation=0
// Should return 100, but returns 99

using System.Runtime.CompilerServices;
class Runtime_105792
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Problem(int x)
    {
        int y = 0;
        while (x != 0)
        {
            if (y == x) return -1;
            y = x;
            Update(ref x);
        }
        return x;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Update(ref int x) 
    {
        x = x - 1;
    }

    public static int Main() => 100 + Problem(10);
}
```
`x` is not in SSA since it is address exposed. 

Phi refinement kicks in for the while loop in `Problem`, and gives `y`'s back edge phi arg the same value number as `x` has at the point of the assignment.

This enables RBO to decide that if we come along the loop back edge, we know that `x == y`, and so we can return -1.

```
***** BB03 [0001]
STMT00008 ( ??? ... ??? )
N004 (  0,  0) [000023] DA---------                         *  STORE_LCL_VAR int    V01 loc0         d:3 $VN.Void
N003 (  0,  0) [000022] -----------                         \--*  PHI       int    $181
N001 (  0,  0) [000025] ----------- pred BB04                  +--*  PHI_ARG   int    V01 loc0         u:4 <l:$182, c:$83>
N002 (  0,  0) [000024] ----------- pred BB02                  \--*  PHI_ARG   int    V01 loc0         u:2 $42

***** BB03 [0001]
STMT00002 ( 0x004[E-] ... 0x006 )
N004 (  7,  6) [000009] ----G------                         *  JTRUE     void   $VN.Void
N003 (  5,  4) [000008] N---G--N-U-                         \--*  NE        int    <l:$1c3, c:$1c4>
N001 (  1,  1) [000006] -----------                            +--*  LCL_VAR   int    V01 loc0         u:3 (last use) $181
N002 (  3,  2) [000007] ----G------                            \--*  LCL_VAR   int   (AX) V00 arg0          <l:$182, c:$82>
```

Not sure how to fix this. Seems like we might need to do something similar to hoisting here, where we realize that a VN is loop dependent?

@dotnet/jit-contrib any thoughts?

**Comment by jakobbotsch** [comment]
> Not sure how to fix this. Seems like we might need to do something similar to hoisting here, where we realize that a VN is loop dependent?
> 
> @dotnet/jit-contrib any thoughts?

Hmm yeah, I agree, I think the refinement can only be done with VNs that we can prove to be invariant in the loop we are refining for. Otherwise the same VN can take on different values, as in this example.

**Comment by Junjun-zhao** [comment]
Verified this issue with dotnet-sdk-9.0.100-rc.1.24417.9, it has been fixed.
