### ISSUE TITLE
Enable PGO Optimization for More Platforms / Architectures

### ISSUE THREAD

**Issue by brianrob** [dotnet/runtime#10579]
The following platforms currently don't get PGO optimized.

 - Windows arm32
 - Windows arm64
 - Linux arm32
 - Linux arm64
 - OSX x64

**Comment by jashook** [comment]
I will continue to push. @brianrob should this issue be closed or updated?

**Comment by brianrob** [comment]
I think it's fair to close this for now.  We can re-file individual bugs as necessary.
