### ISSUE TITLE
`BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds_WithEtwListener` fails with `System.NullReferenceException`

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#105807]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=762567
Build error leg or test failing: BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds_WithEtwListener
Pull request: https://github.com/dotnet/runtime/pull/105777

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds_WithEtwListener [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=762567
**Error message validated:** `[BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds_WithEtwListener [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/1/2024 1:37:41 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[762567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762567)|dotnet/runtime|[BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds_WithEtwListener](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762567&view=ms.vss-test-web.build-test-results-tab&runId=19382046&resultId=125048)|dotnet/runtime#105777|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by tommcdon** [comment]
Closing as duplicate to https://github.com/dotnet/runtime/issues/96968
