### ISSUE TITLE
DefaultValueAttribute support change introduce new linker warnings

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#105857]
See https://github.com/dotnet/sdk/pull/42496#issuecomment-2263663666

Disabling the test temporarily so we can unblock codeflow, filing this issue to track reenabling it.

**Comment by ericstj** [comment]
@akoeplinger  mentioned that https://github.com/dotnet/runtime/pull/105766 introduced a new linker warning
```
+ ILLink : Trim analysis warning IL2026: System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(Type, String): Using member 'System.ComponentModel.DefaultValueAttribute.<.ctor>g__TryConvertFromInvariantString|5_0(Type, String, Object&)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DefaultValueAttribute usage of TypeConverter is not compatible with trimming.
```

Seems the [test](https://github.com/dotnet/sdk/pull/42496/commits/7bf1d513b8cb12d7f9bf82ec8fc9dad903b7e027#diff-94165635db8a2e728d8befd1d2d7458a3a9175dd7cd4f21d020009d03b0eae0aR832) just creates a [very simple hello world](https://github.com/dotnet/sdk/blob/b149a156f2a3d699bee08c577bcd586b8468da2f/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs#L2131).

@steveharter @LakshanF can you have a look and see if this is expected?

**Comment by akoeplinger** [comment]
Ah thanks, makes sense. I'll open an SDK PR.

**Comment by steveharter** [comment]
> Ah thanks, makes sense. I'll open an SDK PR.

Closing this issue then.
