### ISSUE TITLE
Return an unsafe writable ref in ImmutableArray.Builder

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#1058]
Return an unsafe writable ref from ImmutableArray.Builder

https://github.com/dotnet/runtime/blob/2ca8277e543116ee02f67dffeb0cc84ec0824baa/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Builder.cs#L170

Today Builder only has ItemRef, which is ref readonly, to preserver invariants when used together with MoveToImmutable. For performance it would be helpful if there was an unsafe itemref that returns the writable ref from the underlying array.

This is helpful with large structs where you want to get the value and change it with one array access.

**Comment by stephentoub** [comment]
To cast away the safety, use Unsafe.AsRef.
https://github.com/dotnet/runtime/blob/2ca8277e543116ee02f67dffeb0cc84ec0824baa/src/libraries/System.Runtime.CompilerServices.Unsafe/ref/System.Runtime.CompilerServices.Unsafe.cs#L19
We do not want to propagate such unsafe methods around and instead have this Unsafe helper in one place.

**Comment by NinoFloris** [comment]
Ah right, that's exactly what I need, closing!
