### ISSUE TITLE
JIT: Bad result with `AdvSimd.ShiftRightLogical`

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#105817]
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-01 14:37:47
// Run on Arm64 MacOS
// Seed: 14773448547728333023-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 270.2 KiB to 0.4 KiB in 00:01:48
// Debug: Outputs 0
// Release: Outputs 1
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static void Main()
    {
        var vr6 = Vector128.Create<short>(1);
        var vr7 = AdvSimd.ShiftRightLogical(vr6, 16);
        var vr8 = AdvSimd.Extract(vr7, 0);
        System.Console.WriteLine(vr8);
    }
}
```

cc @dotnet/jit-contrib

**Comment by amanasifkhalid** [comment]
I can take this. I suspect this is related to my fix for #105621.

**Comment by tannergooding** [comment]
If the intrinsics are overshifting here, then yes and it's likely that the comment is just wrong.

It might be good to double check the behavior of `ShiftLogical` here as well, I believe it takes the first 8-bits, but we shouldn't be constant folding those today and intrinsics like `AdvSimd.ShiftRightLogical` should be taking the shift amount as `byte` (so restricted to 8-bits already).

**Comment by tannergooding** [comment]
May also need to double check `ShiftRightArithmetic`, looks like `SSHR` is also `[1, sizeof(T) * 8]`

**Comment by amanasifkhalid** [comment]
> May also need to double check ShiftRightArithmetic, looks like SSHR is also [1, sizeof(T) * 8]

You're right, the `GT_RSH` path also had to be updated. I've added test coverage for both paths in #105847.

> It might be good to double check the behavior of ShiftLogical here as well, I believe it takes the first 8-bits, but we shouldn't be constant folding those today and intrinsics like AdvSimd.ShiftRightLogical should be taking the shift amount as byte (so restricted to 8-bits already).

I believe you're correct. The [docs](https://www.scs.stanford.edu/~zyedidia/arm64/ushl_advsimd.html) say `ShiftLogical` reads only the LSB of the register containing the immediate, and there doesn't seem to be any constant folding path for it (`GenTreeHWIntrinsic::GetOperForHWIntrinsicId` returns `GT_NONE` for it), so I don't think anything needs to be done for that intrinsic.
