### ISSUE TITLE
Circular DI causes endless loop instead of exception

### ISSUE THREAD

**Issue by wvpm** [dotnet/runtime#105900]
### Description

_To be honest, I am doubting between this being a bug and this being a feature request. I reported it because if this happens, you are left clueless._

Using Microsoft.Extensions.DependencyInjection you can create a circular dependency problem. This would be my fault as the user. Some cases of circular dependencies trigger a clear and helpful exception. The case below causes an endless loop.

### Reproduction Steps

```cs
ServiceCollection serviceCollection = new();
serviceCollection.AddSingleton<IDummy, DummyService>();
serviceCollection.AddSingleton<ServiceWithDependency>();
serviceCollection.AddSingleton<IDummy>(p => p.GetRequiredService<ServiceWithDependency>());
using ServiceProvider serviceProvider = serviceCollection.BuildServiceProvider(new ServiceProviderOptions() {
	ValidateOnBuild = true,
	ValidateScopes = true
});
var dummy = serviceProvider.GetService<IDummy>(); //never completes
```

```cs
class ServiceWithDependency(IDummydependency) : IDummy{
	private readonly IDummy _dependency = dependency;
}

class DummyService : IDummy{ }

interface IDummy{ }
```

### Expected behavior

System.InvalidOperationException: A circular dependency was detected for the service of type ....

### Actual behavior

Execution does not finish

### Regression?

Not regression

### Known Workarounds

1. Don't make circular dependencies.
2. Test your DI by resolving all publicly resolvable services.
(I discovered it during some playful testing).

### Configuration

.NET 8.0 + Microsoft.Extensions.DependencyInjection 8.0.0

### Possible solutions

1. A hard time limit to resolve a service could be a solution.
2. You could also track a set of types you are trying to resolve and if the type requested while resolving is in the set, throw.
    So IDummy (added to set) > ServiceWithDependency (added to set) > IDummy (already in set) => throw.
    
    Edit: [CallSiteChain](https://github.com/dotnet/runtime/blob/f120fff4838fbae622123c6578734275d909a3f2/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteChain.cs) is supposed to do this but doesn't recognise this scenario.
3. Another alternative would be adding way more reflection for factory registrations to ensure they will complete.

I think the loop is caused by [the lock inside the CallSiteFactory](https://github.com/dotnet/runtime/blob/f120fff4838fbae622123c6578734275d909a3f2/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteFactory.cs#L197). I might be wrong, but it's a good place to look for the bug.

I think changing the code as follows might work:
```cs
            var callsiteLock = _callSiteLocks.GetOrAdd(serviceIdentifier, static _ => new object());
+           callSiteChain.CheckCircularDependency(serviceIdentifier);
            lock (callsiteLock)
            {
-               callSiteChain.CheckCircularDependency(serviceIdentifier);

                ServiceCallSite? callSite = TryCreateExact(serviceIdentifier, callSiteChain) ??
                                           TryCreateOpenGeneric(serviceIdentifier, callSiteChain) ??
                                           TryCreateEnumerable(serviceIdentifier, callSiteChain);

                return callSite;
            }
```

**Comment by wvpm** [comment]
This issue may seem made up and the user's fault. Sure, it is.
But imagine someone makes this mistake in say a package or shared software via any of the `serviceProvider.AddXyZ` methods. You better have DI testing for all code paths.

The following is typically used to detect DI issues early, yet it doesn't complain here.
```
serviceCollection.BuildServiceProvider(new ServiceProviderOptions() {
	ValidateOnBuild = true,
	ValidateScopes = true
})
```

If you don't have DI tests for the code that resolves the circular registration, your tests will pass and the code can be deployed. All works fine...

Until one day someone lands on the code that resolved the circular registration and you basically have a DOS.
Engineers may simply restart the service thinking it 'just hang'. All is fine again :D 

Except it isn't. Whenever the code is executed again, you have another DOS. This time the engineers look into it more closely and try rolling back some unrelated work (remember this DOS can remain undetected for a long time).

Only when the engineers find the code path that triggers the DOS can they get closer to finding the issue. Even then, the code looks fine. The tests all pass (remember DI wasn't tested for this path). It takes time to figure out the DI is causing issue.

Having experience as devops I can imagine this would be a tough issue to find.
By throwing an exception the issue would be much easier to find and resolve.

**Comment by davidfowl** [comment]
Dupe of https://github.com/dotnet/runtime/issues/36458

**Comment by wvpm** [comment]
I'll move my info there.
