### ISSUE TITLE
ColorTranslator.ToWin32 is inefficient

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#105992]
Known colors are looked up with every property access. With system colors on windows this will cause 3 PInvokes.

https://github.com/dotnet/runtime/blob/77fb0389ba7b67f7e31a79c93dc444469622c94f/src/libraries/System.Drawing.Primitives/src/System/Drawing/ColorTranslator.cs#L33-L36

Need to grab the full ARGB value and work with it instead to limit to a single lookup.

**Comment by stephentoub** [comment]
> With system colors on windows this will cause 3 PInvokes.

What's the call stack of the P/Invokes here?

**Comment by JeremyKuhne** [comment]
Effectively this:

`Color.R -> Color.Value -> KnownColorTable.KnownColorToArgb -> KnownColorTable->GetSystemColorArgb -> Interop.User32.GetSysColor`

**Comment by ericstj** [comment]
@JeremyKuhne is this something you need for 9.0.0 or is it just something we want to fix up in future?

**Comment by JeremyKuhne** [comment]
> @JeremyKuhne is this something you need for 9.0.0 or is it just something we want to fix up in future?

No, just trying to track it. I'll make a PR for it as it is pretty trivial.
