### ISSUE TITLE
Error when calling a method from the NativeAOT static library.

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#105915]
![image](https://github.com/user-attachments/assets/0aca0571-e7ac-457f-80fd-22c91a3803ca)
![image](https://github.com/user-attachments/assets/05d0fa73-5ec9-43aa-9c0d-c7c44348d30a)
![image](https://github.com/user-attachments/assets/7180f99f-7e0c-4c22-bd1c-75bbce536532)
After linking a static library and a C++ project, an error occurs when calling it, namely when switching to the call instruction with a call to the RhpReversePInvoke method.
![image](https://github.com/user-attachments/assets/ec9e3634-b3cc-4758-9cbd-83d95dfa4e34)
![image](https://github.com/user-attachments/assets/7099da3e-3ed5-499e-81a8-063d76d8980e)
![image](https://github.com/user-attachments/assets/5eb0180a-380b-4f36-bf37-ccccf6314e45)

**Comment by dadavadd** [comment]
I would be grateful for your help. If you need more information, I’m ready to provide it!

**Comment by jkotas** [comment]
Can you share disassembly of the code around the crash? What's the .NET version that you are using?

**Comment by dadavadd** [comment]
> Можете ли вы поделиться дизассемблированным кодом вокруг сбоя? Какую версию .NET вы используете?

.NET 8. 
Csproj: https://pastebin.com/zyzC4dJc
Screen:

![exception](https://github.com/user-attachments/assets/1469331b-6005-4832-b88c-65cfa91db7b7)

**Comment by dadavadd** [comment]
> Можете ли вы поделиться дизассемблированным кодом вокруг сбоя? Какую версию .NET вы используете?

Additional linker dependencies:
"D:\Games and Programs\VisualStudioProjects1\sqlsecure\bin\Release\net8.0\win-x64\native\sqlsecure.lib"
"C:\Users\User\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\Runtime.WorkstationGC.lib"
"C:\Users\User\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\eventpipe-disabled.lib"
"C:\Users\User\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\Runtime.VxsortDisabled.lib"
"C:\Users\User\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\System.Globalization.Native.Aot.lib"
"C:\Users\User\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\System.IO.Compression.Native.Aot.lib"
"advapi32.lib"
"bcrypt.lib"
"crypt32.lib"
"iphlpapi.lib"
"kernel32.lib"
"mswsock.lib"
"ncrypt.lib"
"normaliz.lib"
"ntdll.lib"
"ole32.lib"
"oleaut32.lib"
"secur32.lib"
"user32.lib"
"version.lib"
"ws2_32.lib"
"libucrt.lib"
"ucrt.lib"

**Comment by dadavadd** [comment]
> > Можете ли вы поделиться дизассемблированным кодом вокруг сбоя? Какую версию .NET вы используете?
> 
> Additional linker dependencies in CPP project: "D:\Games and Programs\VisualStudioProjects1\sqlsecure\bin\Release\net8.0\win-x64\native\sqlsecure.lib" "C:\Users\User.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\Runtime.WorkstationGC.lib" "C:\Users\User.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\eventpipe-disabled.lib" "C:\Users\User.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\Runtime.VxsortDisabled.lib" "C:\Users\User.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\System.Globalization.Native.Aot.lib" "C:\Users\User.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.4\sdk\System.IO.Compression.Native.Aot.lib" "advapi32.lib" "bcrypt.lib" "crypt32.lib" "iphlpapi.lib" "kernel32.lib" "mswsock.lib" "ncrypt.lib" "normaliz.lib" "ntdll.lib" "ole32.lib" "oleaut32.lib" "secur32.lib" "user32.lib" "version.lib" "ws2_32.lib" "libucrt.lib" "ucrt.lib"

**Comment by dadavadd** [comment]
> Можете ли вы поделиться дизассемблированным кодом вокруг сбоя? Какую версию .NET вы используете?

If you dig deeper into the code, this is where the exception occurs:
![image](https://github.com/user-attachments/assets/4aabe455-803f-470c-86d0-f91888f8f31c)

**Comment by MichalStrehovsky** [comment]
This looks like a mismatch in the C runtime libraries. It likely has to do with how the LIB file got linked with rest of the code - the initializers in Runtime.WorkstationGC.lib probably didn't run. We don't really [support/encourage people to use NativeLib=Static](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/libraries) (see the big Note) because it results in failure modes that are hard to troubleshoot. If you're not able to figure this out, please switch to NativeLib=Shared.

**Comment by dadavadd** [comment]
> Похоже, это несоответствие в библиотеках времени выполнения C. Скорее всего, это связано с тем, как файл LIB был связан с остальной частью кода — инициализаторы в Runtime.WorkstationGC.lib, вероятно, не запустились. Мы на самом деле не [поддерживаем/не рекомендуем людям использовать NativeLib=Static](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/libraries) (см. большое примечание), потому что это приводит к режимам сбоя, которые трудно устранить. Если вы не можете разобраться, переключитесь на NativeLib=Shared.


Will it ever be possible to create static NativeAOT libraries with proper compatibility? (Without linking there are 20+ additional static libraries).
