### ISSUE TITLE
Segmentation Fault while debugging

### ISSUE THREAD

**Issue by Martin521** [dotnet/runtime#105917]
### Description

In a certain, reproducible situation, while debugging a .net program (the F# compiler in this case) in VS Code, a segmentation fault happens.

### Reproduction Steps

1. Prerequisite: VS Code with Dev Containers
2. Clone https://github.com/dotnet/fsharp
3. Open repository in VS Code, install recommended extensions.
4. Reopen repository in the devcontainer.
5. Build compiler in dev container with `dotnet build ./FSharp.Compiler.Service.sln -c Debug`.
6. In repository root, create a file, named `test.fs`, containing the following:
	```fsharp
	module A
	printfn "hello world"
	```
7. Press F5, chose launch configuration `Launch FSC (Debug)`, enter `test.fs` at the popped up prompt. FSC compiles `test.fs` and exits normally
8. Add a breakpoint [here](https://github.com/dotnet/fsharp/blob/d8e2f21729d4bced94265c9a5e52e2bdba40117a/src/Compiler/Driver/FxResolver.fs#L471) (`src/Compiler/Driver/FxResolver.fs:471`).
9. Press F5, wait for the breakpoint to be reached, press F5 again => "Segmentation fault" is printed on stdout.

### Expected behavior

no segmentation fault

### Actual behavior

see above

### Regression?

It used to work on `preview 5`

### Known Workarounds

Downgrade to preview 5.

### Configuration

9.0.100-preview.6.24328.19
Windows 11 x64 host, dev container using mcr.microsoft.com/dotnet/sdk:9.0.100-preview.6

**Comment by Martin521** [comment]
@thaystg Thanks for the fix. Did it land in preview 7?

**Comment by thaystg** [comment]
No, landed in RC1.
