### ISSUE TITLE
[IILink] UnsafeAccessor work for CorLib

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#106009]
### Description

It seems that ILLink doesn't process `UnsafeAccessorAttribute` when used inside another method.

```cs
     internal static Task RegisterWasiPollable(IPoll.Pollable pollable) 
     { 
         return CallRegisterWasiPollable((Thread)null!, 123); 
  
         [UnsafeAccessor(UnsafeAccessorKind.StaticMethod, Name = "RegisterWasiPollable")] 
         static extern Task CallRegisterWasiPollable(Thread t, int handle); 
     } 
```

### Reproduction Steps

See
https://github.com/dotnet/runtime/blob/d606c601510c1a1a28cb6ef3550f12db049c0776/src/libraries/System.Net.Http/src/System/Net/Http/WasiHttpHandler/WasiHttpHandler.cs#L464-L475

https://github.com/dotnet/runtime/blob/d606c601510c1a1a28cb6ef3550f12db049c0776/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.Unix.cs#L15-L23

### Expected behavior

[UnsafeAccessor] on the nested external method will protect `Thread.RegisterWasiPollable` from trimming

### Actual behavior

```
System.AggregateException: One or more errors occurred. (Could not find RegisterWasiPollableHandle)
   ---> System.MissingMethodException: Could not find RegisterWasiPollable
     at System.Net.Http.WasiHttpHandler.WasiEventLoop.RegisterWasiPollable(Pollable )
     at System.Net.Http.WasiHttpHandler.SendRequestAsync(OutgoingRequest )
     at System.Net.Http.WasiHttpHandler.SendAsync(HttpRequestMessage , CancellationToken )
     at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , CancellationToken )
     at Test.Work()
```

### Known Workarounds

use `ILLink.Descriptors.WASI.xml`

### Configuration

Net9 Prev 7

### Other information

Discovered [here](https://github.com/dotnet/runtime/pull/105879#discussion_r1701943596)

**Comment by vitek-karas** [comment]
Hmm - I tried a simple repro in ILLink tests and there it works just fine. This has to be something a bit subtle. @pavelsavara how would one go about reproducing this (as in running the linker)?

Or alternatively - please use this https://github.com/vitek-karas/illinkrepro to capture a illink repro and share it (probably internally over email to me and Sven).

Also, did you check the target method is missing from the IL after trimming? It could be a runtime problem where the runtime doesn't find the method even if it's there...

**Comment by pavelsavara** [comment]
For a while I thought this was caused by `UnsafeAccessor` being in inside of another method, but it happens also when it's top level in class.

It reproduces for me when I build [current main](https://github.com/dotnet/runtime/tree/8d7e3b58f75dba5fbadf6b6b3c3cf54f3d6bc16b) for WASI on my machine.
The methods are really gone, I looked at the DLLs.

And I confirmed that with CI test in my PR - [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105879-merge-27339f9a976f41b4a7/Workloads-ST-Wasm.Build.Tests/1/console.82540b9a.log?helixlogtype=result)

And so I'm preventing that on the [PR](https://github.com/dotnet/runtime/pull/105879) by adding `src/mono/System.Private.CoreLib/src/ILLink/ILLink.Descriptors.WASI.xml` into [src/mono/System.Private.CoreLib/System.Private.CoreLib.csproj](https://github.com/dotnet/runtime/pull/105879/files#diff-4accdf2622952296e1e5354de533c41c4b6cf2b2678ca800e47c6548ca2e9aa9R137)

**Comment by vitek-karas** [comment]
Discussed offline with Pavel.

Trimmer behaves correctly, this is an artifact of library trimming in the runtime repo (Library Build). We run the trimmer separately on each assembly - so when it gets executed on CoreLib it doesn't get System.Net.Http as input and so it doesn't see the `UnsafeAccessor` and thus removes the target methods.

The correct "fix" for this is to root the methods in the `ILLink.Descriptor.LibraryBuild.xml` files as we already do for several other methods.

/cc @sbomer - closing as resolved, but please double check my reasoning here :-)
