### ISSUE TITLE
How to post-processing binaries before bundling when use Publish AOT?

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#106003]
### Description

![{3957178A-629B-46C0-84BD-4CCD90339DCF}](https://github.com/user-attachments/assets/482fd824-dd3e-4bfa-ab4a-f3ca9c44bd4a)
![{485B3F06-6D13-49D5-8DAF-DE978E1EF595}](https://github.com/user-attachments/assets/bc025119-4f1d-4512-9cc5-8588b900cdc0)
https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

Some workflows require post-processing of binaries before bundling. A common example is signing. The dotnet SDK provides MSBuild extension points to allow processing binaries just before single-file bundling.
某些工作流需要在捆绑之前对二进制文件进行后处理。 一个常见示例是签名。 dotnet SDK 提供 MSBuild 扩展点，以允许在单文件捆绑之前处理二进制文件。

In https://github.com/dotnet/sdk, however, we found that when using AOT release, this Task will not be implemented, so dependent on the Task of the custom Task did not run normally, so there is no other way to perform the same logic?
然而在 https://github.com/dotnet/sdk ,我们发现在使用 AOT 发布的时候，这一 Task 并不会被执行，所以依赖于该 Task 的自定义任务也没有正常运行，所以有没有其他方法来执行相同的逻辑？
![{B69E1D6D-9FD6-4B38-B910-8EFA2DAE0384}](https://github.com/user-attachments/assets/a6360046-3a43-4345-b500-8738a1f61b17)
https://github.com/dotnet/sdk/blob/fdf4527ea9bb52bffd6068bb8f93b4e3a96286d9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets

### Reproduction Steps

See description

### Expected behavior

post-processing binaries before bundling when use Publish AOT

### Actual behavior

Not post-processing binaries before bundling when use Publish AOT

### Regression?

None

### Known Workarounds

None

### Configuration

.NET 9.0.0-preview6
Windows 11 26100
X64
No
No

### Other information

None

**Comment by Gaoyifei1011** [comment]
> AOT doesn't **use** the same process of single file bundling. It's just applicable to similar limitations.
> 
> There's no promise to support post-processing for IL. See #100646 and #104522



> AOT doesn't **use** the same process of single file bundling. It's just applicable to similar limitations.
> 
> There's no promise to support post-processing for IL. See #100646 and #104522

Thank you very much.

**Comment by MichalStrehovsky** [comment]
I'll close as answered. Native AOT doesn't bundle executables. Single file deployment is different in the sense that it glues together files and (sometimes) extracts them back to disk as part of executing the glued bundle. PublishAot is native compilation. The assemblies do not exist after compilation.

**Comment by Gaoyifei1011** [comment]
> I'll close as answered. Native AOT doesn't bundle executables. Single file deployment is different in the sense that it glues together files and (sometimes) extracts them back to disk as part of executing the glued bundle. PublishAot is native compilation. The assemblies do not exist after compilation.

Thanks for your answer
