### ISSUE TITLE
failure in BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#106086]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=767302
Build error leg or test failing: System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11
Pull request: https://github.com/dotnet/runtime/pull/106019

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11()",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=767302
**Error message validated:** `[at System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11()`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/7/2024 5:08:51 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[773518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773518)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773518&view=ms.vss-test-web.build-test-results-tab&runId=19778254&resultId=153123)||
|[770220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770220)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770220&view=ms.vss-test-web.build-test-results-tab&runId=19672522&resultId=183636)||
|[770217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770217)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770217&view=ms.vss-test-web.build-test-results-tab&runId=19672510&resultId=193633)||
|[768830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768830)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768830&view=ms.vss-test-web.build-test-results-tab&runId=19625772&resultId=184791)||
|[768833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768833)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768833&view=ms.vss-test-web.build-test-results-tab&runId=19622868&resultId=174099)||
|[767302](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767302)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767302&view=ms.vss-test-web.build-test-results-tab&runId=19564852&resultId=167565)|dotnet/runtime#106019|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|6|

**Comment by lewing** [comment]
not sure how prevalent this is but it definitely couldn't have been caused by the change where I saw it

**Comment by carlossanlop** [comment]
This is supposed to be fixed in staging. I suspect you saw it in the base branch? cc @liveans I think it was you who fixed this, correct?

**Comment by liveans** [comment]
> cc @liveans I think it was you who fixed this, correct?


Yes, this is fixed in staging
