### ISSUE TITLE
A call to `string.Replace` does not terminate

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/runtime#1060]
Compile and run:
```csharp
using System;

static class Program
{
    static void Main()
    {
        var s = "hi".Replace("\u0640", "", StringComparison.InvariantCulture);
        Console.WriteLine(s);
    }
}
```

**ACTUAL:**
The call to method `Replace` does not terminate (apparently, there is an infinite loop).

**EXPECTED:**
The program prints `hi`.

---
OS `ver` is `Microsoft Windows [Version 10.0.17763.914]`

`%SystemRoot%\System32\kernel32.dll`
File version: `10.0.17763.475`
File SHA1: `8de080d3295fb21475715d4051ec9dbc3df972ba`

---
The issue occurs both on:

`%ProgramFiles%\dotnet\shared\Microsoft.NETCore.App\3.1.0\.version`
`65f04fb6db7a5e198d05dbebd5c4ad21eb018f89`
`3.1.0`

and 

`%ProgramFiles%\dotnet\shared\Microsoft.NETCore.App\5.0.0-alpha.1.19564.1\.version`
`c77948d92a2f950140f09384f057cb893ec3955a`
`5.0.0-alpha.1.19564.1`

**Comment by GrabYourPitchforks** [comment]
This and https://github.com/dotnet/runtime/issues/1062 are likely NLS bugs. I'll follow up with the Windows localization team offline.

**Comment by VladimirReshetnikov** [comment]
There is a possibly relevant call to `FindNLSStringEx` in `kernel32.dll`:

`%SystemRoot%\System32\kernel32.dll`
File version: `10.0.17763.475`
Product version: `10.0.17763.475`
File SHA1: `8de080d3295fb21475715d4051ec9dbc3df972ba`

**Comment by GrabYourPitchforks** [comment]
Followed up with the NLS team. They helped walk me through the scenario and we've determined that this is in fact a .NET bug. We'll make the change on our side.

**Comment by GrabYourPitchforks** [comment]
I'm reopening the issue because it may be a candidate for servicing.
