### ISSUE TITLE
Android API 23, Runtime Crash in .NET 9

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#106025]
### Description

We have a nightly test pipeline that runs our test suite on older Android emulators.

The API 23 emulator crashes at runtime with:
```
08-06 03:33:12.480  2745  2745 F mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: Nested exception detected.
08-06 03:33:12.480  2745  2745 F mono-rt : Original Exception: at System.Threading.Thread.get_CurrentThread () [0x00009] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Threading.Monitor.Exit (object) [0x0000e] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.AppContext.GetData (string) [0x00037] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.AppContext.TryGetSwitch (string,bool&) [0x00040] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.AppContextConfigHelper.GetBooleanConfig (string,bool) [0x00000] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.LocalAppContextSwitches.GetDefaultShowILOffsetSetting () [0x00014] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Diagnostics.StackTrace.ToString (System.Diagnostics.StackTrace/TraceFormat,System.Text.StringBuilder) [0x002ee] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Diagnostics.StackTrace.ToString (System.Diagnostics.StackTrace/TraceFormat) [0x0000b] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.GetStackTrace () [0x00007] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.get_StackTrace () [0x00023] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.ToString () [0x0001f] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.ToString () [0x0000c] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.ToString () [0x0000c] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : 
08-06 03:33:12.480  2745  2745 F mono-rt : Nested exception:at System.Threading.Thread.get_CurrentThread () [0x00009] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Threading.Monitor.Exit (object) [0x0000e] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.AppContext.GetData (string) [0x00037] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.AppContext.TryGetSwitch (string,bool&) [0x00040] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.AppContextConfigHelper.GetBooleanConfig (string,bool) [0x00000] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.LocalAppContextSwitches.GetDefaultShowILOffsetSetting () [0x00014] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Diagnostics.StackTrace.ToString (System.Diagnostics.StackTrace/TraceFormat,System.Text.StringBuilder) [0x002ee] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Diagnostics.StackTrace.ToString (System.Diagnostics.StackTrace/TraceFormat) [0x0000b] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.GetStackTrace () [0x00007] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.get_StackTrace () [0x00023] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.ToString () [0x0001f] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.ToString () [0x0000c] in <d7679677bb2b4cc291070c60be6bf246>:0
08-06 03:33:12.480  2745  2745 F mono-rt : at System.Exception.ToString () [0x0000c] in <d7679677bb2b4cc291070c60be6bf246>:0
```

This appears to be working fine on newer API levels.

### Reproduction Steps

Run this test project on an API 23 emulator:
* https://github.com/dotnet/android/blob/main/tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj

### Expected behavior

Our test suite passes on API 23 emulators.

### Actual behavior

Our test suite crashes on API 23 emulators.

### Regression?

Yes, this is working in .NET 8.

### Known Workarounds

n/a

### Configuration

Noticed with:
* .NET SDK 9.0.100-rc.1.24381.10
* Runtime 9.0.0-rc.1.24380.7

I think this was also happening in .NET 9 Preview 7 builds.

### Other information

[logcat-Release23-Mono.Android.NET_Tests.txt](https://github.com/user-attachments/files/16512755/logcat-Release23-Mono.Android.NET_Tests.txt)

**Comment by akoeplinger** [comment]
This looks like two issues in one: it's trying to throw an exception but then crashes because of the nested exception.

**Comment by steveisok** [comment]
@jonathanpeppers from the logcat, it appears libSystem.Native could not be loaded. Is there something wrong with your setup?

**Comment by grendello** [comment]
@jonathanpeppers 32-bit shared libraries are aligned to 4k, 16k applies only to 64-bit targets. That's what NDK r27 does, so I followed suit, but it might be still a system error.  We store the [`dlerror` message](https://github.com/dotnet/android/blob/07cb311e10d30fe94a29b7804ab01393786958a6/src/native/runtime-base/monodroid-dl.hh#L46-L52) when loading the shared library and pass it back to Mono via the [dlopen hook here](https://github.com/dotnet/android/blob/07cb311e10d30fe94a29b7804ab01393786958a6/src/native/runtime-base/monodroid-dl.hh#L106).

@steveisok @akoeplinger does Mono log the `err` when it sees one?

**Comment by akoeplinger** [comment]
No, looks like we don't do anything with the error:
https://github.com/dotnet/runtime/blob/dec456802525f73944de05a59c4b7db7d67b4a8a/src/mono/mono/utils/mono-dl.c#L269-L271

**Comment by akoeplinger** [comment]
@grendello isn't that the real error?
> dlopen failed: cannot find "libc.so" from verneed[1] in DT_NEEDED list for "/data/app/Mono.Android.NET_Tests-1/split_config.x86.apk"

**Comment by grendello** [comment]
@akoeplinger on one hand yes, it is, on the other... how do we even **run** the app if `libc.so` cannot be found? :)

**Comment by BrzVlad** [comment]
Can't reproduce this. Tried running on my apple chip with arm64 AVD, failed to reproduce, then noticed that in the report the device was android-x86. I then tried the following the following:
 - on my intel macbook, I created a Pixel 5 AVD with the following system image `Android 6.0, API Level 23, x86`
 - cloned `dotnet/android` with recent main checked out
 - `make prepare; make jenkins`
 - `./dotnet-local.sh build -t:RunTestApp tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj /p:RuntimeIdentifier=android-x86`
 - logcat output: `09-17 12:59:39.991  4617  4632 I NUnit   : Passed: 859, Failed: 0, Skipped: 7, Inconclusive: 0, Total: 0, Filtered: 0`

**Comment by jonathanpeppers** [comment]
Our nightly CI is failing, because we dropped 32-bit by default:
```
[BT The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [arm64-v8a, x86_64].
```
Let me fix these tests and find out if latest is working.

**Comment by jonathanpeppers** [comment]
Fixing our tests here:
* https://github.com/dotnet/android/pull/9308

This should find out if this is still an issue with recent-ish RC 2.

**Comment by jonathanpeppers** [comment]
@BrzVlad I think I'm still seeing that `libSystem.Native.so` not loading might be the underlying issue:
```
09-17 14:41:32.839  2758  2758 I monodroid-assembly: Failed to load shared library '/data/app/Mono.Android.NET_Tests-1/split_config.x86.apk!/lib/x86/libSystem.Native.so'. dlopen failed: cannot find "libc.so" from verneed[1] in DT_NEEDED list for "/data/app/Mono.Android.NET_Tests-1/split_config.x86.apk"
```
It looks like this works on API 21 and fails on API 23? And then x86 is the only emulator option for those old Android versions.

**Comment by jeffhandley** [comment]
@jonathanpeppers / @steveisok -- Checking in on this. Does it still need resolution before .NET 9 GA? If so, who should be assigned to bring it to closure?

**Comment by jonathanpeppers** [comment]
It looks like this combination isn't working:
* `libSystem.Native.so` cannot be loaded on...
* x86 (this is the only emulator option, for older Android versions they don't have x86_64)
* API 23 or older

So, it's unknown how impacting this will be for customers. It's hard to know if you would see the same thing on arm64 devices.

**Comment by jeffhandley** [comment]
@jonathanpeppers -- @tannergooding pointed out that API 23 and older appear to be completely out of support by Google now.

See https://developer.android.com/google/play/requirements/target-sdk:

> New apps and app updates must target Android 14 (API level 34) or higher to be submitted to Google Play; except for Wear OS and Android TV apps, which must target Android 13 (API level 33) or higher.
>
> Existing apps must target Android 13 (API level 33) or higher to remain available to new users on devices running Android OS higher than your app's target API level. Apps that target Android 12 (API level 31) or lower (Android 10 (API level 29) or lower for Wear OS and Android 11 (API level 30) or lower for Android TV), will only be available on devices running Android OS that are the same or lower than your app's target API level.

I'm inclined to close this out based on that info. What do you think?

**Comment by tannergooding** [comment]
Notably I'm not sure its "completely out of support" but rather that it isn't supported if you're wanting to target the "latest devices".

There's still reasons to target downlevel API levels to support some older devices, but there's an overall balance required and I don't think an official page for what versions are supported across devices still exist.

**Comment by jonathanpeppers** [comment]
The “target” is what API you compiled against, Google Play requires very recent for this. “Minimum” API level is what you can run on. .NET has a minimum of API 21.

**Comment by steveisok** [comment]
> It looks like this combination isn't working:
> 
> * `libSystem.Native.so` cannot be loaded on...
> * x86 (this is the only emulator option, for older Android versions they don't have x86_64)
> * API 23 or older
> 
> So, it's unknown how impacting this will be for customers. It's hard to know if you would see the same thing on arm64 devices.

Based on @BrzVlad's previous analysis, are we sure this is a runtime issue?

**Comment by jonathanpeppers** [comment]
We are checking if a newer version of the API 23 emulator solves it:
* https://github.com/dotnet/android/pull/9414

Does something test "hello world" on Android on an API 23 emulator? Is there a Helix lane for this?

If you have that running somewhere, and it would load `libSystem.Native.so` we can close this.

**Comment by matouskozak** [comment]
> We are checking if a newer version of the API 23 emulator solves it:
> 
> * [[tests] run `sdkmanager update` before installing emulators android#9414](https://github.com/dotnet/android/pull/9414)
> 
> Does something test "hello world" on Android on an API 23 (or 21) emulator? Is there a Helix lane for this?
> 
> If you have that running somewhere, and it would load `libSystem.Native.so` we can close this.

There are Helix queues with 21/23 emulators, `ubuntu.2204.amd64.android.[21/23]` that you can use. By default, we only run tests on API 29 though.

**Comment by jonathanpeppers** [comment]
@matouskozak if one of those is succeeding with latest .NET 9 builds we can close this.

If you can find a build, would there be a log message saying `libSystem.Native.so` is successfully loaded?

**Comment by matouskozak** [comment]
> [@matouskozak](https://github.com/matouskozak) if one of those is succeeding with latest .NET 9 builds we can close this.
> 
> If you can find a build, would there be a log message saying `libSystem.Native.so` is successfully loaded?

Does this issue need Android SDK to reproduce? If so, I think we don't run any tests with the dotnet/android code inside runtime. 

We did run a .NET 9 runtime validation on Android API 21 - 32 (https://github.com/dotnet/runtime/pull/106951) and I don't recall any issues with loading `libSystem.Native.so`. However, it is possible we could had missed this as there was a lot of flakiness on the older Android APIs (21 and 22 especially). 

@jonathanpeppers if there is a repro only using dotnet/runtime I can setup a PR with older Android emulators to test it. Or if dotnet/android can use Helix we could open the PR there.

**Comment by jonathanpeppers** [comment]
After more investigation, we think this is some kind of bug in the x86, API 23 emulator image. API 21 is also working on our same pipeline, so this covers our minimum supported devices. API 23 was when Android first introduced some changes to loading native libraries, and its likely buggy.

We can close this, as we don't think it's a runtime issue.

There is some conversation on discord here for details:

* https://discord.com/channels/732297728826277939/732297837953679412/1296764055654240317
