### ISSUE TITLE
CI failure RegularExpressions didn't throw expected TimeoutException

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#106096]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=768415
Build error leg or test failing: System.Text.RegularExpressions.Tests.RegexMatchTests.Match_TestThatTimeoutHappens
Pull request: https://github.com/dotnet/runtime/pull/106014

## Error Message

Assert.Throws() Failure: No exception was thrown
      Expected: typeof(System.Text.RegularExpressions.RegexMatchTimeoutException)

```json
{
  "ErrorMessage": "Expected: typeof(System.Text.RegularExpressions.RegexMatchTimeoutException)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=768415
**Error message validated:** `[Expected: typeof(System.Text.RegularExpressions.RegexMatchTimeoutException)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/7/2024 10:13:42 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[772461](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772461)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexMatchTests.Match_TestThatTimeoutHappens](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772461&view=ms.vss-test-web.build-test-results-tab&runId=19743014&resultId=213469)||
|[769435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769435)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769435&view=ms.vss-test-web.build-test-results-tab&runId=19645944&resultId=218544)||
|[768415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768415)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexMatchTests.Match_TestThatTimeoutHappens](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768415&view=ms.vss-test-web.build-test-results-tab&runId=19607758&resultId=216089)|dotnet/runtime#106014|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|3|

**Comment by ericstj** [comment]
@stephentoub did we make regex too fast that we need to shorten the timeout?

**Comment by stephentoub** [comment]
> [@stephentoub](https://github.com/stephentoub) did we make regex too fast that we need to shorten the timeout?

Actually, yes. Though we can't really shorten the timeout, it's already set at 1ms. It's just that a couple of the inputs/patterns being tested now only take around 10ms to run, at least on my machine. If there's any hiccup in CI, things could stretch in a way where it would sporadically pass.

We should just delete these:
https://github.com/dotnet/runtime/blob/68511fd27fe4055ce5203742998ba12019dfcbd4/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Match.Tests.cs#L1267-L1268
