### ISSUE TITLE
[Analyzer Proposal]: Anlyzer for wrong usage of interpolated string with Logger methods

### ISSUE THREAD

**Issue by Meir017** [dotnet/runtime#106041]
### Background and motivation

https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors#avoid-string-interpolation-in-logging

found multiple usages in https://github.com/microsoft/garnet
searched for `.Log(.*)\(\$`  in vscode
![image](https://github.com/user-attachments/assets/5eca455f-97a5-46b0-aa0e-7323e42eaf00)

FYI @badrishc

### API Proposal

using any of the methods in https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerExtensions.cs and passing in an interpolated string should trigger a diagnostic

### API Usage

N/A

**Comment by tarekgh** [comment]
@Meir017 isn't already covered by https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254?

**Comment by Meir017** [comment]
@tarekgh there are cases where an interpolated string might be useful when having constant values in it.

example from garnet:
https://github.com/microsoft/garnet/blob/84d4f5192dffb2814c873f6c48db425da5558d2c/libs/cluster/Server/Replication/ReplicationManager.cs#L262

```cs
logger?.LogError($"An error occurred at {nameof(ReplicationManager)}.{nameof(Start)} {{error}}", Encoding.ASCII.GetString(errorMessage));
```

I think this log line should not trigger the analyzer as it's a constant string

**Comment by Meir017** [comment]
I think I missed something, this doesn't trigger the analyzer
