### ISSUE TITLE
[mono][ios] Mono prevents crash logs from being generated in case `SIGSEGV` is raised from native code

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#106064]
### Description

While investigating the behavior of the crash reported in: https://github.com/dotnet/runtime/issues/105245 on iOS device we noticed that such error does not: 
1) Produce any useful information in the `Console.app`
2) It did not generate a crash report on a device

### Repro

1. Install official .NET 9 preview 6 release
2. Install MAUI workloads
3. Create a MAUI template app
4. Build/run it on a physical device in `Debug` mode:
```
dotnet build -f net9.0-ios -r ios-arm64 -t:Run -p:_DeviceName=XXXXXX
```
5. `Console.app` shows only that the program exited:
```
default  14:14:51.131793+0200  SpringBoard  [app<com.companyname.myapp(80F7F2DD-E9BB-43D8-AB25-7A0DE1A64558)>:6714] Process exited: <RBSProcessExitContext| voluntary>.
```
6. No crash logs are generated on a device

### Investigation

As initially assumed, the crash was not caused by asserting from the runtime (where we `abort()` properly), but instead the code was trying to read from an invalid memory address (something like 0xa8) so `SIGSEGV` was raised.
The mono's signal handler catches this, but does not remove it self as a `SIGSEGV` handler when it starts handling the signal. 
After the handling is done, the handler returns, but the same signal is caught again and on second handling the program exits out with -1 in case of double faulting: 
https://github.com/dotnet/runtime/blob/fdb741523a090a1bc31f70e336cc7783912bd089/src/mono/mono/mini/mini-posix.c#L789-L792 
This causes the app to silently exit not including any information about the crash.
Additionally, the messages from the signal handler (like information about the native and managed stack traces) that are using `g_async_safe_printf` are not shown in the system log.

FWIW In the signal handler we do unregister the runtime for some signals, but not for `SIGSEGV`: https://github.com/dotnet/runtime/blob/d606c601510c1a1a28cb6ef3550f12db049c0776/src/mono/mono/mini/mini-exceptions.c#L2932-L2942 

### Proposal

1. Investigate if we can unregister the `SIGSEGV` handler if we've detected that the signal it's not coming from managed code (to distinguish `NullReferenceException`)
5. Try using a platform specific logging mechanism so that messages from the signal handler end up in the system log when a fatal error occurs

PS Thanks @lambdageek for assistance

**Comment by ivanpovazan** [comment]
> This didn't happen (presumably because there was no previous signal handler), and in that case Mono will print native crash info and call abort:
> 
> https://github.com/dotnet/runtime/blob/af1b3b0446650765814381fead7cc88bf60315b9/src/mono/mono/mini/mini-posix.c#L225-L226
> 
> But that didn't happen?
> 

If I am not mistaken the code you linked is the `SIGABRT` handler. 

---

We are instead reaching this code: 
https://github.com/dotnet/runtime/blob/af1b3b0446650765814381fead7cc88bf60315b9/src/mono/mono/mini/mini-runtime.c#L3808

which further handles the signal and returns since signal chaining is enabled:
https://github.com/dotnet/runtime/blob/af1b3b0446650765814381fead7cc88bf60315b9/src/mono/mono/mini/mini-runtime.c#L3908-L3912

**Comment by rolfbjarne** [comment]
> If I am not mistaken the code you linked is the `SIGABRT` handler.

Ah my bad, sorry about the confusion.

I'm just really surprised this isn't a regression, because I'm certain I've seen crash reports for SIGSEGVs originating in native code before (but then again I might be misremembering - I just tried in .NET 8, and I got the double fault with no crash report).

**Comment by rolfbjarne** [comment]
FWIW I've seen customers run into this now.

**Comment by ivanpovazan** [comment]
> FWIW I've seen customers run into this now.

Do we have a specific issue to link to this one + raise a priority on fixing this?

**Comment by rolfbjarne** [comment]
> > FWIW I've seen customers run into this now.
> 
> Do we have a specific issue to link to this one + raise a priority on fixing this?

The customer in question is the one who reported this: https://github.com/dotnet/runtime/issues/107641

Although much of the interaction happened via email, so reading the issue isn't all that useful.

**Comment by Redth** [comment]
@ivanpovazan @steveisok @vitek-karas this one is happening more frequently with customers now - could we get this prioritized?  I think @StephaneDelcroix can provide a repro...

**Comment by steveisok** [comment]
> I think [@StephaneDelcroix](https://github.com/StephaneDelcroix) can provide a repro...

If you have a repro, great and I'll work with @vitek-karas to get this prioritized.

**Comment by ivanpovazan** [comment]
I just synced with @vitek-karas I will look into this as soon as possible.
