### ISSUE TITLE
[NativeAOT] How to compile linux-musl-arm64 shared libraries on Ubuntu( x64)

### ISSUE THREAD

**Issue by CeSun** [dotnet/runtime#106029]
I want to compile a shared library for the arm64 platform that libc is musl.
But I only have ubuntu (wsl) on x86
I found a cross-platform compiler: aarch64-linux-musl-cross
However, dotnet's publish command does not recognize the compiler, it seems that it only recognizes clang and gcc

![image](https://github.com/user-attachments/assets/7e2493a6-de65-40fc-b2a2-291d09676341)
![image](https://github.com/user-attachments/assets/810e96c9-53f0-42cc-b8f1-e719b2a987dd)

**Comment by MichalStrehovsky** [comment]
If you have a correctly configured cross toolchain, adding `-p:CppCompilerAndLinker=aarch64-linux-musl-gcc` should be all that's needed.

You might want to also look at https://www.nuget.org/packages/PublishAotCross#readme-body-tab.

**Comment by CeSun** [comment]
> If you have a correctly configured cross toolchain, adding `-p:CppCompilerAndLinker=aarch64-linux-musl-gcc` should be all that's needed.
> 
> You might want to also look at https://www.nuget.org/packages/PublishAotCross#readme-body-tab.

Thank you.
PublishAotCross is a good project, But I encountered a new problem, maybe I should raise an issue?
```EXEC : error : unsupported linker arg: -e0x0```
![QQ_1723006528549](https://github.com/user-attachments/assets/46325886-d5ce-4654-b403-e116d2f5b7da)

**Comment by MichalStrehovsky** [comment]
> PublishAotCross is a good project, But I encountered a new problem, maybe I need add an issue?

Can you try finding clang.cmd in your NuGet package cache (the contents should look like this: https://github.com/MichalStrehovsky/PublishAotCross/blob/master/src/clang.cmd) and add `set args=%args:-Wl,-e0x0 =%` after line 20? If that works, we can just upstream it to PublishAotCross.

**Comment by CeSun** [comment]
> > PublishAotCross is a good project, But I encountered a new problem, maybe I need add an issue?
> 
> Can you try finding clang.cmd in your NuGet package cache (the contents should look like this: https://github.com/MichalStrehovsky/PublishAotCross/blob/master/src/clang.cmd) and add `set args=%args:-Wl,-e0x0 =%` after line 20? If that works, we can just upstream it to PublishAotCross.

It worked!
