### ISSUE TITLE
[API Proposal]: TypeName.MakeSimpleTypeName(AssemblyNameInfo) to avoid type name reparsing

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#106022]
### Background and motivation

In https://github.com/dotnet/runtime/issues/102263, we have approved a set of APIs for creating new `TypeName` instances without reparsing the input again.

I took a stab at it in https://github.com/dotnet/runtime/pull/103713 and realized that I can not use the approved `TypeName.CreateSimpleTypeName` because it expects unescaped input. It's also supposed to escape such input (https://github.com/dotnet/runtime/issues/102263#issuecomment-2265482973). In order to find out whether it needs to escape the input, it needs to reparse the input (search for multiple characters that need to be escaped). It's exactly what I need to avoid in NRBF, so I need a new method.

### API Proposal

```diff
namespace System.Reflection.Metadata;

public partial class TypeName
{      
    public TypeName MakeSZArrayTypeName();
    public TypeName MakeArrayTypeName(int rank);
    public TypeName MakePointerTypeName();
    public TypeName MakeByRefTypeName();
    public TypeName MakeGenericTypeName(ImmutableArray<TypeName> typeArguments);
+   public TypeName MakeSimpleTypeName(AssemblyNameInfo? assemblyInfo);

    public static TypeName CreateSimpleTypeName(
        string metadataName,
        TypeName? declaringType = null,
        AssemblyNameInfo? assemblyInfo = null);
}
```

### API Usage

```csharp
static TypeName WithAssemblyName(this TypeName typeName, AssemblyNameInfo assemblyName)
{
    if (!typeName.IsSimple)
    {
        if (typeName.IsArray)
        {
            TypeName newElementType = typeName.GetElementType().WithAssemblyName(assemblyName);

            return typeName.IsSZArray
                ? newElementType.MakeSZArrayTypeName()
                : newElementType.MakeArrayTypeName(typeName.GetArrayRank());
        }
        else if (typeName.IsConstructedGenericType)
        {
            TypeName newGenericTypeDefinition = typeName.GetGenericTypeDefinition().WithAssemblyName(assemblyName);

            // We don't change the assembly name of generic arguments on purpose.
            return newGenericTypeDefinition.MakeGenericTypeName(typeName.GetGenericArguments());
        }
        else
        {
            // BinaryFormatter can not serialize pointers or references.
            ThrowHelper.ThrowInvalidTypeName(typeName.FullName);
        }
    }

    return typeName.MakeSimpleTypeName(assemblyName);
}
```

### Risks

Having two methods with similar names: `MakeSimpleTypeName` and `CreateSimpleTypeName` may be confusing to the end users.

**Comment by jkotas** [comment]
> I can not use the approved TypeName.CreateSimpleTypeName because it expects unescaped input. 

I think you can use it. I agree that `TypeName.CreateSimpleTypeName` is a less efficient in the BF use case when compared to the API proposed here, but there is no fundamental problem doing what the BF needs to achieve using the approved APIs.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Reflection.Metadata;

public partial class TypeName
{
    public TypeName MakeSimpleTypeName(AssemblyNameInfo? assemblyInfo);
}
```

**Comment by adamsitnik** [comment]
Based on online (https://github.com/dotnet/runtime/pull/103713#discussion_r1706380392) and offline discussions with @jkotas I would like to discuss renaming the method from `MakeSimpleTypeName` to `WithAssemblyName`.

```csharp
namespace System.Reflection.Metadata;

public partial class TypeName
{
    public TypeName WithAssemblyName(AssemblyNameInfo? assemblyInfo);
}
```

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Reflection.Metadata;

public partial class TypeName
{
    public TypeName WithAssemblyName(AssemblyNameInfo? assemblyInfo);
}
```
