### ISSUE TITLE
JIT: Bad codegen with `Avx512F.VL.RotateLeftVariable` and `Avx512F.VL.RotateRightVariable` on win-x86

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#106142]
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-06 15:26:23
// Run on X86 Windows
// Seed: 17786759086488605032-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86bmi1,x86bmi2,x86fma,x86lzcnt,x86pclmulqdq,x86popcnt,x86sse,x86sse2,x86sse3,x86sse41,x86sse42,x86ssse3,x86x86base
// Reduced from 186.1 KiB to 0.4 KiB in 00:13:36
// Debug: Outputs <4611686018427387904, 0, 0, 0>
// Release: Outputs <0, 0, 0, 0>
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static void Main()
    {
        var vr7 = Vector256.Create(1, 0, 0, 0);
        var vr8 = Vector256.CreateScalar(18446744073709551614UL);
        var vr9 = Avx512F.VL.RotateLeftVariable(vr7, vr8);
        System.Console.WriteLine(vr9);
    }
}
```

```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-06 15:23:25
// Run on X86 Windows
// Seed: 4121896490095390139-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86bmi1,x86bmi2,x86fma,x86lzcnt,x86pclmulqdq,x86popcnt,x86sse,x86sse2,x86sse3,x86sse41,x86sse42,x86ssse3,x86x86base
// Reduced from 31.4 KiB to 0.4 KiB in 00:01:15
// Debug: Outputs <9007199254740992, 1, 1, 1>
// Release: Outputs <0, 1, 1, 1>
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static void Main()
    {
        var vr2 = Vector256.Create<long>(1);
        var vr3 = Vector256.CreateScalar(9945469575827037067UL);
        Vector256<long> vr4 = Avx512F.VL.RotateRightVariable(vr2, vr3);
        System.Console.WriteLine(vr4);
    }
}
```
cc @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
@anthonycanino, PTAL.
cc @tannergooding.

**Comment by DeepakRajendrakumaran** [comment]
Looking into this

**Comment by DeepakRajendrakumaran** [comment]
The foll morph code seem to be the cause : https://github.com/dotnet/runtime/blob/0d70f72bd373bd4359b6767ba710e71965331b71/src/coreclr/jit/simd.h#L672-L681
This doesn't fit with how the intrinsic actually works - https://www.felixcloutier.com/x86/vprord:vprorvd:vprorq:vprorvq


`If the value specified by the count operand is greater than 31 (for doublewords), or 63 (for a quadword), then the count operand modulo the data size (32 or 64) is used.`

![image](https://github.com/user-attachments/assets/17cd9c6d-0309-457c-b964-993f6c4d4d76)

**Comment by DeepakRajendrakumaran** [comment]
The main issue here is because we are reusing the helpers for RSZ- which are functionally different in this case.

ShiftRightLogical([link](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.avx2.shiftrightlogical?view=net-8.0#system-runtime-intrinsics-x86-avx2-shiftrightlogical(system-runtime-intrinsics-vector256((system-uint64))-system-runtime-intrinsics-vector128((system-uint64))))) creates vpsrlq(https://www.felixcloutier.com/x86/psrlw:psrld:psrlq) which results in zeros in these cases

![image](https://github.com/user-attachments/assets/8e46c39e-b5c0-4217-98ee-1c5977d0d8bc).

So the foll will need to be reworked

![image](https://github.com/user-attachments/assets/ffadd4e5-72d7-488a-8d1b-bcafc91bc2e4)

**Comment by DeepakRajendrakumaran** [comment]
@tannergooding @JulieLeeMSFT @EgorBo @jakobbotsch Can we add this patch to 9.0?

https://github.com/dotnet/runtime/commit/f251b170fb1d1be8552e7e1f3238aca9bcc6bb7a

**Comment by JulieLeeMSFT** [comment]
We are still in .NET 9 main. 
@anthonycanino is looking into this.

**Comment by DeepakRajendrakumaran** [comment]
> We are still in .NET 9 main. @anthonycanino is looking into this.

@JulieLeeMSFT Can you please confirm that the fail is present in main? or if the tests were run on .NET 9 preview?

**Comment by jakobbotsch** [comment]
Yes, this bug is in main (and also in previews). We should fix this for .NET 9.

**Comment by DeepakRajendrakumaran** [comment]
Thanks for the info. I'm able to repro it on main for x86. I'll update with more details today
