### ISSUE TITLE
Conversion from UTC to EET depends on system time zone when it shouldn't

### ISSUE THREAD

**Issue by georgiosd** [dotnet/runtime#106120]
### Description

Unless I am misunderstanding the documentation, I am seeing an issue where `TimeZoneInfo.ConvertTimeFromUtc` calculates a different UTC offset for EET timezone, depending on the system timezone.

If I set my computer to CET, I get a +2 offset:

![image](https://github.com/user-attachments/assets/6a5a67d0-696b-40c0-a5f7-b2bc743ad65d)

If I set my computer to EET, I get the correct +3 offset:

![image](https://github.com/user-attachments/assets/22994a52-fe1f-4df9-9655-25ddc942ec99)

Since this is a conversion from UTC to a specific timezone, this seems to be a bug.

### Reproduction Steps

1. Set computer timezone to CET (Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna on Windows 11)
2. Execute this code
```
void Main()
{
	TimeZoneInfo EETTz = TimeZoneInfo.FindSystemTimeZoneById("Europe/Athens");
	DateTimeOffset now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, EETTz);
	
	Console.WriteLine(now);
}
```
3. Set computer timezone to EET (Athens, Bucharest on Windows 11)

### Expected behavior

The UTC offset produced should be +3 regardless of the host computer's TZ.

### Actual behavior

The UTC offset is +2 when the host computer TZ is CET and +3 when the host computer TZ is EET.

### Known Workarounds

Use NodaTime :)

### Configuration

Tested on .NET 6.0 and .NET 7.0, on Windows 11.

**Comment by lilinus** [comment]
`TimeZoneInfo.ConvertTimeFromUtc` returns a `DateTime` which then is implicitly converted into a `DateTimeOffset`.

How about using `ConvertTime` instead?
```
TimeZoneInfo EETTz = TimeZoneInfo.FindSystemTimeZoneById("Europe/Athens");
DateTimeOffset offset = TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, EETTz);
```

**Comment by georgiosd** [comment]
You guys are right, that solves the issue. Apologies for the false positive.

**Comment by georgiosd** [comment]
Exactly that! I kept getting my date calculations one hour off on the server because it's in CET and every time I tested locally, I was like "but it works" 😄
