### ISSUE TITLE
InlineArray in generic class

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#106129]
**Steps to Reproduce**:

This example code does nothing with the parametric type value except to read and return as a result.
Therefore, it was surprising to find a strong difference in the code size and performance for value and reference types.
Is this expected?

See  [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkYMBuG+hgZQAW2KAAcAMtmAsASgFcAdhgCW+GD2o0G2hgG1msxSrUsAwhHyjlAGxhR+dgG7KwMXCwCSC68oUwAglBQ2ACeABSkAJQAulo6vhh2CtjWDLgYUHJgGAwAKgDuEABCwQpggm4APLlsEAAmMOIw2ABmAHxx2gDenTraolDKjtiJebUNTa0A/AwA+rAtdBp9AL69xADMTKQM4zDVe5PtvT3UfX0JSSl5hSXYZRW4lXsH9Y3N7W0Mdw9uy+faS5QZKpYAQCCpDy4I7/AFAkFjN5HGaHD6whhrTTUXQAKWUGAA4jA/IMwGEMCFRDAIC0wglIjFeFsyHk3BhTNY8LhyNUjl9Tn1NnlkQwALLkOlKBjAfFoXZvXkfL5QcEYSInXp9XIi2C4OTWHIAXgYDRa2H13E1Ohe2qVDDAciCxIwewYxoU+us6L6Vu0Nr5M2ApXKbvtjtgSj2LB+5TcuhlGGi3viLQYYSD9xDylwDA91ms6rOAIYAuLOmIAHYGLqLcntJiy5Xq25a71MZiaLj8USSS5yZTqbSPAAFfx1Oq63AM2K0Zk7XJsjlc0iK1r89ZbW3TMWkSU5BNy/12lUQNUaosArctGY1g2h03mg11+UNVftMNOyNvUN5r2+hj/kea6BsGgihg6n4um80agXGCZJv+yipumoEMNmuaeoWZalmWTBVreloXucDbFk2BHou2NA0EAA=)

**Expected Behavior**:

Code for value types and reference types is almost the same, performance is almost the same.

**Actual Behavior**:

Code for reference types is much larger and works 2-3 times _slower_.

**Comment by jakobbotsch** [comment]
The generic type is used for `InlineArrayAsSpan` calls generated under-the-hood by Roslyn. The JIT does not manage to remove all those runtime lookups as some of them feed control flow (in the end, there is no difference in taking the true and false path for these tests, but the JIT's DCE is not able to reason that far).
We could clean this up if we taught the early liveness passes how to DCE other things than stores, since then we can do it before we expand the runtime lookups into control flow here.

**Comment by iSazonov** [comment]
For current 9.0 milestone I'd ask to add a warning in docs "Don't use InlineArray with _reference_ types for performance reason". This will save someone a lot of time searching for the reasons why their code is slow.

**Comment by jakobbotsch** [comment]
Can you share a benchmark that shows a perf problem warranting such a statement? Your code here always throws `NullReferenceException`.

**Comment by iSazonov** [comment]
Yes, sharplab example is  minimal asm demo.

I attached working benchmark project for you.
[genericlist.zip](https://github.com/user-attachments/files/16559193/genericlist.zip)

**Comment by jakobbotsch** [comment]
In general we expect shared generic code to be slightly slower than unshared code. For example, you will also see a slowdown when for `List<string>.set_Item` compared to `List<int>.set_Item`. We don't try to document this anywhere, so I'm not sure it's warranted to do it for this case either, especially considering that I expect we can improve on this (either by improving our DCE, or by implementing #105586).

Thoughts @dotnet/jit-contrib @jkotas?

**Comment by iSazonov** [comment]
> In general we expect shared generic code to be slightly slower than unshared code. For example, you will also see a slowdown for List<string>.set_Item compared to List<int>.set_Item. 

While I was researching this problem, I measured this example too and the differences there are scanty, there is an understanding of this and it is acceptable.

If we compare 1 and 3 lines (InlineArray code - value vs referense) - diff is 2.47!
```
| Method      | Mean      | Error     | StdDev    | Ratio | RatioSD | Code Size |
|------------ |----------:|----------:|----------:|------:|--------:|----------:|
| Array       | 13.817 ns | 0.1581 ns | 0.1479 ns |  1.00 |    0.00 |      81 B |
| Array2      |  9.376 ns | 0.2055 ns | 0.1922 ns |  0.68 |    0.02 |      47 B |
| IPAddress1  | 34.252 ns | 0.4945 ns | 0.4129 ns |  2.47 |    0.04 |     184 B |
| IPAddress21 | 11.089 ns | 0.2526 ns | 0.2363 ns |  0.80 |    0.02 |      54 B |
```

I don't insist on documenting. But the problem is that there are intuitive expectations that the new InlineArray is designed for high-performance code, although it works worse than the usual language constructs.

**Comment by jakobbotsch** [comment]
I think we can get a fix for this into .NET 9. #106183 and #106185 both fix the performance disparity here.
