### ISSUE TITLE
PosixSignalRegistration.Create hangs debugger on MacOS (Rider & VSCode)

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#106194]
### Description

```cSharp
using System.Runtime.InteropServices;

PosixSignalRegistration.Create(PosixSignal.SIGINT, context => Console.WriteLine("Terminated"));
while (true) {
  Console.Write(".");
  Task.Delay(1000).Wait();
  // press CTRL+C in debug
}
```

### Reproduction Steps

run code in debugger
press CTRL+C

### Expected behavior

stop debugging (process terminated)

### Actual behavior

debugger hangs

### Configuration

MacOS Arm64
net 8

**Comment by mikelle-rogers** [comment]
Hello @kefyru, I tried to repro this issue, I created a console app put the code in that you provided and ran it under the debugger. When I got to the last line with the comment, I tried pushing ctrl+c and cmd+c and nothing seemed to happen. Is that what you are calling "the debugger hangs"? Are you able to push the red square in VS Code an have the program terminate correctly?
