### ISSUE TITLE
Compile-time logging source generation does only concat first collection of strings in message

### ISSUE THREAD

**Issue by mu88** [dotnet/runtime#106122]
### Description

Imagine you're using compile-time logging source generation with the following log message template:  
```csharp
public static partial class LoggerExtensions
{
    [LoggerMessage(
        EventId = 1002,
        EventName = nameof(PetsAndNationalitiesInSameOrder),
        Level = LogLevel.Information,
        Message = "---{Pets}---{Nationalities}---",
        SkipEnabledCheck = true)]
    public static partial void PetsAndNationalitiesInSameOrder(this ILogger logger, IEnumerable<string> pets, IEnumerable<string> nationalities);
}
```

When calling it via `logger.PetsAndNationalitiesInSameOrder(["Cat", "Dog"], ["German", "Swiss"])`, this will produce the following log message using a JSON log formatter:
```json
{
  "Timestamp": "06:47:56 ",
  "EventId": 1002,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---System.Collections.Generic.List\u00601[System.String]---",
  "State": {
    "Message": "---dog, cat---System.Collections.Generic.List\u00601[System.String]---",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "Nationalities": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
```

As you can see, this has two flaws:
1. When a log method contains more than one collection (e.g. both `pets` and `nationalities`), .NET only concats the values from the first collection in the log message (see `message`). For the other collections, the collection type name will be logged.
2. The log parameters/structures values passed to the log method (`pets` and `nationalities`) have no special treatment when writing them.

### Reproduction Steps

1. Clone the repro repo https://github.com/mu88/Repro_dotnet_logging_state and checkout [this commit](https://github.com/mu88/Repro_dotnet_logging_state/commit/850c7d7caa0733e918290285d2a99ccef5614b70)
2. Open the solution and start the web app
3. Call `http://localhost:5232/hello`

### Expected behavior

My expectation would be the following:
1. Common log formatters like console or JSON concat the log's `state` string values.
2. Common log formatters like console or JSON concat all string collections in the message, not only the first one.

```json
{
  "Timestamp": "06:47:56 ",
  "EventId": 1001,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---",
  "State": {
    "Message": "---dog, cat---",
    "Pets": "dog, cat",
    "{OriginalFormat}": "---{Pets}---"
  }
}
{
  "Timestamp": "06:47:56 ",
  "EventId": 1003,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---[dog, cat]---[german, swiss]---",
  "State": {
    "Message": "---[dog, cat]---[german, swiss]---",
    "Nationalities": "german, swiss",
    "Pets": "dog, cat",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
{
  "Timestamp": "06:47:56 ",
  "EventId": 1002,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---german, swiss---",
  "State": {
    "Message": "---dog, cat---german, swiss---",
    "Pets": "dog, cat",
    "Nationalities": "german, swiss",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
```

### Actual behavior

```json
{
  "Timestamp": "06:47:56 ",
  "EventId": 1001,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---",
  "State": {
    "Message": "---dog, cat---",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---"
  }
}
{
  "Timestamp": "06:47:56 ",
  "EventId": 1003,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---[dog, cat]---[german, swiss]---",
  "State": {
    "Message": "---[dog, cat]---[german, swiss]---",
    "Nationalities": "System.Collections.Generic.List\u00601[System.String]",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
{
  "Timestamp": "06:47:56 ",
  "EventId": 1002,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---System.Collections.Generic.List\u00601[System.String]---",
  "State": {
    "Message": "---dog, cat---System.Collections.Generic.List\u00601[System.String]---",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "Nationalities": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
```

### Regression?

🤷🏻‍♂️

### Known Workarounds

We've implemented a custom log formatter that both sanitizes the log message and also concatenates the string values of the log's `state` ([see this commit](https://github.com/mu88/Repro_dotnet_logging_state/commit/f6120ca41a19d447ea9a59602e9f5c2d767109ae)). It also logs the state of a log message:
```
06:52:41  level=INFO eventId=1001 eventName=Pets sourceContext="WebApi" message="---dog, cat---" pets="dog, cat" spanId="d873fb97a64194cc" traceId="7b797987ca8bb887f764bb03ad4a59fb" parentId="0000000000000000" connectionId="0HN5RCI19BUOC" requestId="0HN5RCI19BUOC:00000003" requestPath="/hello"
06:52:41  level=INFO eventId=1003 eventName=NationalitiesAndPetsInDifferentOrder sourceContext="WebApi" message="---[dog, cat]---[german, swiss]---" nationalities="german, swiss" pets="dog, cat" spanId="d873fb97a64194cc" traceId="7b797987ca8bb887f764bb03ad4a59fb" parentId="0000000000000000" connectionId="0HN5RCI19BUOC" requestId="0HN5RCI19BUOC:00000003" requestPath="/hello"
06:52:41  level=INFO eventId=1002 eventName=PetsAndNationalitiesInSameOrder sourceContext="WebApi" message="---dog, cat---System.Collections.Generic.List`1[System.String]---" pets="dog, cat" nationalities="german, swiss" spanId="d873fb97a64194cc" traceId="7b797987ca8bb887f764bb03ad4a59fb" parentId="0000000000000000" connectionId="0HN5RCI19BUOC" requestId="0HN5RCI19BUOC:00000003" requestPath="/hello"
```
In case the state contains an instance of `IEnumerable<string>`, it will get concatenated ([see here](https://github.com/mu88/Repro_dotnet_logging_state/blob/f6120ca41a19d447ea9a59602e9f5c2d767109ae/CustomServiceRuntimeContractFormatter.cs#L92-L93)). However, [this line](https://github.com/mu88/Repro_dotnet_logging_state/blob/f6120ca41a19d447ea9a59602e9f5c2d767109ae/CustomServiceRuntimeContractFormatter.cs#L47) breaks the log message.

### Configuration

- .NET: `8.0.303`
- OS: Win11, version 23H2
- Arch: `x64`
- It is probably not related to this particular configuration.

**Comment by mu88** [comment]
Thx for your immediate analysis @KalleOlaviNiemitalo 👍🏻 however, I'm just a little bit unsure whether you need more information from my side or if everything is clear for you 🙂

**Comment by mu88** [comment]
I tested your console app example and can confirm that it also properly formats the log message on my machine. However, in my ASP.NET Core repro app, this is still not the case. Do you have an idea what the difference might be? 🤔

> In the description of this issue, you quoted the following output. How did you configure the console logger for that? The curly braces in {System.Collections.Generic.List`1[System.String]} look especially strange; did they come from the log entry formatter or from the console formatted?

This might be related to the fact that we're using our own implementation of a `Microsoft.Extensions.Logging.Console.ConsoleFormatter`. I can provide you the code if you want, too. However, I tried to remove all custom pieces from the equation, and since I was able to reproduce it with my repro app, I hope we can ignore this (for the moment).

**Comment by mu88** [comment]
Sorry for the confusion, I mixed up several different issues. Let's dissect it piece by piece.

First of all, I've added [this commit](https://github.com/mu88/Repro_dotnet_logging_state/commit/850c7d7caa0733e918290285d2a99ccef5614b70) to my sample repro app:
```csharp
    [LoggerMessage(
        EventId = 1002,
        EventName = nameof(PetsAndNationalitiesInSameOrder),
        Level = LogLevel.Information,
        Message = "---{Pets}---{Nationalities}---",
        SkipEnabledCheck = true)]
    public static partial void PetsAndNationalitiesInSameOrder(this ILogger logger, IEnumerable<string> pets, IEnumerable<string> nationalities);

    [LoggerMessage(
        EventId = 1003,
        EventName = nameof(NationalitiesAndPetsInDifferentOrder),
        Level = LogLevel.Information,
        Message = "---{Pets}---{Nationalities}---",
        SkipEnabledCheck = true)]
    public static partial void NationalitiesAndPetsInDifferentOrder(this ILogger logger, IEnumerable<string> nationalities, IEnumerable<string> pets);
```
Here are the corresponding logs:
```json
{
  "Timestamp": "06:47:56 ",
  "EventId": 1001,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---",
  "State": {
    "Message": "---dog, cat---",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---"
  }
}
{
  "Timestamp": "06:47:56 ",
  "EventId": 1003,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---[dog, cat]---[german, swiss]---",
  "State": {
    "Message": "---[dog, cat]---[german, swiss]---",
    "Nationalities": "System.Collections.Generic.List\u00601[System.String]",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
{
  "Timestamp": "06:47:56 ",
  "EventId": 1002,
  "LogLevel": "Information",
  "Category": "WebApi",
  "Message": "---dog, cat---System.Collections.Generic.List\u00601[System.String]---",
  "State": {
    "Message": "---dog, cat---System.Collections.Generic.List\u00601[System.String]---",
    "Pets": "System.Collections.Generic.List\u00601[System.String]",
    "Nationalities": "System.Collections.Generic.List\u00601[System.String]",
    "{OriginalFormat}": "---{Pets}---{Nationalities}---"
  }
}
```

As you can see, the log message of `PetsAndNationalitiesInSameOrder` is broken whereas `NationalitiesAndPetsInDifferentOrder` logs as expected. So it's quite the opposite behavior of #103338.

The next step was [this commit](https://github.com/mu88/Repro_dotnet_logging_state/commit/f6120ca41a19d447ea9a59602e9f5c2d767109ae) where I added our custom console log formatter. Here's the log output:
```
06:52:41  level=INFO eventId=1001 eventName=Pets sourceContext="WebApi" message="---dog, cat---" pets="dog, cat" spanId="d873fb97a64194cc" traceId="7b797987ca8bb887f764bb03ad4a59fb" parentId="0000000000000000" connectionId="0HN5RCI19BUOC" requestId="0HN5RCI19BUOC:00000003" requestPath="/hello"
06:52:41  level=INFO eventId=1003 eventName=NationalitiesAndPetsInDifferentOrder sourceContext="WebApi" message="---[dog, cat]---[german, swiss]---" nationalities="german, swiss" pets="dog, cat" spanId="d873fb97a64194cc" traceId="7b797987ca8bb887f764bb03ad4a59fb" parentId="0000000000000000" connectionId="0HN5RCI19BUOC" requestId="0HN5RCI19BUOC:00000003" requestPath="/hello"
06:52:41  level=INFO eventId=1002 eventName=PetsAndNationalitiesInSameOrder sourceContext="WebApi" message="---dog, cat---System.Collections.Generic.List`1[System.String]---" pets="dog, cat" nationalities="german, swiss" spanId="d873fb97a64194cc" traceId="7b797987ca8bb887f764bb03ad4a59fb" parentId="0000000000000000" connectionId="0HN5RCI19BUOC" requestId="0HN5RCI19BUOC:00000003" requestPath="/hello"
```

Once again, the log message of `PetsAndNationalitiesInSameOrder` is broken whereas `NationalitiesAndPetsInDifferentOrder` logs as expected. This happens at [this line](https://github.com/mu88/Repro_dotnet_logging_state/blob/f6120ca41a19d447ea9a59602e9f5c2d767109ae/CustomServiceRuntimeContractFormatter.cs#L47) when calling the formatter.

Note: I've also updated the initial description of this issue.

**Comment by mu88** [comment]
@KalleOlaviNiemitalo : friendly ping :)

**Comment by donald93** [comment]
I've also run into this issue where only the first list of strings passed into the log messages has its values present in the message. I made a super simple example before I found this open issue: https://github.com/donald93/LoggingStringListExample

**Comment by mu88** [comment]
@KalleOlaviNiemitalo: after upgrading our app to .NET 9, I can no longer reproduce these problems - everything seems to work properly 🤞🏻 Therefore, I close this issue and will reopen it in case I stumble over any further issues. Thx for your help!
