### ISSUE TITLE
[API Proposal]: IsWeekend() method for struct DateTime instance

### ISSUE THREAD

**Issue by castilhera** [dotnet/runtime#106246]
### Background and motivation

Whenever you want to know if a day is a weekend, you need to check whether the day is Saturday or Sunday;
e.g. using DateTime.Now
```csharp
bool isWeekend = DateTime.Now.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday;
```
So I created an extension method to do this:
```csharp
public static class DateExtensions
{
    public static bool IsWeekend(this DayOfWeek dayOfWeek)
        => dayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday;

    public static bool IsWeekend(this DateTime dateTime)
        => dateTime.DayOfWeek.IsWeekend();

    public static bool IsWeekend(this DateTimeOffset dateTimeOffset)
        => dateTimeOffset.DayOfWeek.IsWeekend();

    public static bool IsWeekend(this DateOnly dateOnly)
        => dateOnly.DayOfWeek.IsWeekend();
}
```
And I was thinking it would be nice to have a built-in method instead.

It can be added to all date structures like DateOnly, DateTime, DateTimeOffset and/or just to the DayOfWeek.

Simple but useful.

### API Proposal

```csharp
namespace System;

public readonly partial struct DateTime
{
    public bool IsWeekend() => DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday;
}

public readonly partial struct DateTimeOffset
{
    public bool IsWeekend() => DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday;
}

public readonly struct DateOnly
{
    public bool IsWeekend() => DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday;
}
```

### API Usage

```csharp
bool isWeekend = DateTime.Now.IsWeekend();
```

**Comment by Symbai** [comment]
> Whenever you want to know if a day is a weekend, you need to check whether the day is Saturday or Sunday;

Just for information: In some regions of the world, Saturday is not part of the weekend. See https://en.wikipedia.org/wiki/Saturday (regional customs section) and https://en.wikipedia.org/wiki/Workweek_and_weekend

**Comment by krwq** [comment]
It's arguable it's just Saturday and Sunday because weekend starts Friday after work 😄 IMO that doesn't sound like something which should be part of the dotnet/runtime - probably some utilities/extension methods in external libraries are better suited for this (and you probably want that to be user-customizable as well).

**Comment by castilhera** [comment]
> > Whenever you want to know if a day is a weekend, you need to check whether the day is Saturday or Sunday;
> 
> Just for information: In some regions of the world, Saturday is not part of the weekend. See https://en.wikipedia.org/wiki/Saturday (regional customs section) and https://en.wikipedia.org/wiki/Workweek_and_weekend

Sorry. I wasn't aware of that. In fact, with that information, I'm going to close the request.

Thanks @Symbai and @krwq .
