### ISSUE TITLE
Build failure: ilc exited with code 139

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#106293]
```
2024-08-12T16:49:02.1056878Z   Generating native code
2024-08-12T16:49:05.5092712Z /__w/1/s/.packages/microsoft.dotnet.ilcompiler/9.0.0-rc.1.24403.1/build/Microsoft.NETCore.Native.targets(313,5): error MSB3073: The command ""/__w/1/s/.packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.1.24403.1/tools/ilc" @"/__w/1/s/artifacts/obj/coreclr/ILCompiler/linux.arm64.Checked/native/ilc.ilc.rsp"" exited with code 139. [/__w/1/s/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=772975
Build error leg or test failing: Build / linux-arm64 Debug Libraries_CheckedCoreCLR / Build product
Pull request: https://github.com/dotnet/runtime/pull/106277

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "The command.*ilc.*exited with code 139.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=772975
**Error message validated:** `[The command.*ilc.*exited with code 139.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/12/2024 8:05:26 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[774926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774926)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/774926/logs/277)|dotnet/runtime#106369|
|[772975](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772975)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/772975/logs/264)|dotnet/runtime#106277|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|2|

**Comment by MichalStrehovsky** [comment]
We had two hits three weeks ago and then it hasn't reproed in more than two weeks. Likely fixed.
