### ISSUE TITLE
[API Proposal]: Add FromFile method to BinaryData

### ISSUE THREAD

**Issue by JoshLove-msft** [dotnet/runtime#106203]
### Background and motivation

Oftentimes, people want to upload local files using BinaryData. In order to do this with the current API, they must write the following code:
```c#
var bd = BinaryData.FromStream(File.OpenRead("foo"));
```
which is not obvious to many users. 
It would be better if they could simply do:
```c#
var bd = BinaryData.FromFile("foo");
```

### API Proposal

```csharp
namespace System.Memory.Data;

public partial class BinaryData
{
    public static BinaryData FromFile(string path);
    public static Task<BinaryData> FromFileAsync(string path, CancellationToken cancellationToken = default);
    public static Task<BinaryData> FromFileAsync(string path, string? mediaType, CancellationToken cancellationToken = default);
}
```

### API Usage

```csharp
var bd = BinaryData.FromFile("foo");
```

**Comment by terrajobst** [comment]
Makes sense.

Given that `FromStream` also has `FromStreamAsync` it seems we'll want a `FromFileAsync` version as well:

```C#
namespace System.Memory.Data;

public class BinaryData
{
    public static BinaryData FromFile(string path);
    public static Task<BinaryData> FromFileAsync(string path);
}
```

**Comment by skyoxZ** [comment]
> ```cs
> namespace System.Memory.Data;
> 
> public partial class BinaryData
> {
>     public static BinaryData FromFile(string path);
>     public static Task<BinaryData> FromFileAsync(string path);
> }
> ```

Also more overloads? For `mediaType` and `cancellationToken`.

**Comment by terrajobst** [comment]
Good call. Fixed.

**Comment by dersia** [comment]
`FromFile()` should probably also have an overload for mediaType. and is there a need for `FromFileAsJson<T>()`? this would be very handy, I can also see a `FromFileAsGzip()` version.

**Comment by terrajobst** [comment]
> `FromFile()` should probably also have an overload for mediaType.

I fixed that, see original comment.

> And is there a need for `FromFileAsJson<T>()`?

Maybe? I don't recall ever having that need but that might just be me. What's the scenario for that?

> I can also see a `FromFileAsGzip()` version

Today there is no compression handling at all in `BinaryData`. I think this should be a separate feature request as it seems unrelated to support files.

**Comment by terrajobst** [comment]
* We should also add `mediaType` to the sync overload

```C#
namespace System.Memory.Data;

public partial class BinaryData
{
    public static BinaryData FromFile(string path);
    public static BinaryData FromFile(string path, string? mediaType);
    public static Task<BinaryData> FromFileAsync(string path, CancellationToken cancellationToken = default);
    public static Task<BinaryData> FromFileAsync(string path, string? mediaType, CancellationToken cancellationToken = default);
}
```
