### ISSUE TITLE
StreamWriter constructor documentation mismatch with implementation

### ISSUE THREAD

**Issue by rameel** [dotnet/runtime#106237]
There is an inconsistency between the documentation and the actual implementation of the `StreamWriter` constructors. The documentation states that passing `null` to the `Encoding` parameter in some constructors, except the main one, will result in an exception being thrown. However, all these constructors pass the `Encoding` argument to the main constructor, which allows `null`.

```csharp
public StreamWriter(Stream stream, Encoding encoding)
    : this(stream, encoding, DefaultBufferSize, false);

public StreamWriter(Stream stream, Encoding encoding, int bufferSize)
    : this(stream, encoding, bufferSize, false);
```
```csharp
public StreamWriter(Stream stream, Encoding? encoding = null, int bufferSize = -1, bool leaveOpen = false);
```
[StreamWriter.cs](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs#L79-L93)
[Documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=net-8.0#system-io-streamwriter-ctor(system-io-stream-system-text-encoding))

**Suggested Fix**:
- Mark the `Encoding` parameter as nullable in these constructors.
- Update the documentation.
```diff
- public StreamWriter(Stream stream, Encoding encoding);
- public StreamWriter(Stream stream, Encoding encoding, int bufferSize);
+ public StreamWriter(Stream stream, Encoding? encoding);
+ public StreamWriter(Stream stream, Encoding? encoding, int bufferSize);
```

**Comment by DaZombieKiller** [comment]
According to the reference sources, all of the constructors appear to throw for a null encoding value in .NET Framework. I suppose this might just be a case where the behavior changed in .NET Core and some of the overloads got missed when updating the docs.
