### ISSUE TITLE
[iOS/tvOS][fullAOT-llvm] Failures inside System.Runtime BigInteger tests

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#106256]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=772314
Build error leg or test failing: `System.Tests.DecimalTests+BigInteger[Add/Div/Mul].Test`
Affected CI: `ios_arm64_release_allsubsets_mono`, `tvos_arm64_release_allsubsets_mono`

The failures are not 100% reproducible on the CI, however, seem to be affecting both iOS and tvOS device queues (fullAOT-llvm).

![image](https://github.com/user-attachments/assets/afe10f1f-0132-4345-9f6f-6e70a6d3ee3c)

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.Tests.DecimalTests.BigInteger",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=772314
**Error message validated:** `[at System.Tests.DecimalTests.BigInteger`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/12/2024 11:22:57 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[773271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773271)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerAdd.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773271&view=ms.vss-test-web.build-test-results-tab&runId=19787870&resultId=106567)|dotnet/runtime#106269|
|[773841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773841)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerAdd.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773841&view=ms.vss-test-web.build-test-results-tab&runId=19785752&resultId=100390)||
|[773818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773818)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerAdd.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773818&view=ms.vss-test-web.build-test-results-tab&runId=19785462&resultId=103983)|dotnet/runtime#106013|
|[773753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773753)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerMul.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773753&view=ms.vss-test-web.build-test-results-tab&runId=19783738&resultId=103284)|dotnet/runtime#106238|
|[773673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773673)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerAdd.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773673&view=ms.vss-test-web.build-test-results-tab&runId=19782528&resultId=109048)|dotnet/runtime#106294|
|[773665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773665)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerDiv.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773665&view=ms.vss-test-web.build-test-results-tab&runId=19780700&resultId=100424)|dotnet/runtime#106166|
|[773066](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773066)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerMul.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773066&view=ms.vss-test-web.build-test-results-tab&runId=19764114&resultId=107463)|dotnet/runtime#106283|
|[772314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772314)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerAdd.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772314&view=ms.vss-test-web.build-test-results-tab&runId=19737038&resultId=102678)||
|[772028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772028)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerMul.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772028&view=ms.vss-test-web.build-test-results-tab&runId=19727144&resultId=103374)|dotnet/runtime#106037|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|9|

**Comment by matouskozak** [comment]
fyi: @BrzVlad

**Comment by matouskozak** [comment]
Likely fixed by https://github.com/dotnet/runtime/pull/106313 @BrzVlad, please re-open if that's not the case but the CI is green.

**Comment by BrzVlad** [comment]
Yes. Used to get a crash at a frequency of about 1/20 runs. With the fix no crashes after 120 runs so I'm pretty confident that it is fixed by that commit.
