### ISSUE TITLE
[Test Failure] iOS.Device.ExportManagedSymbols times out

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#106318]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=772876
Build error leg or test failing: iOS.Device.ExportManagedSymbols.Test.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/106271

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["iOS.Device", "ERROR: WORKLOAD TIMED OUT - Killing user command.."],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=772876
**Error message validated:** `[iOS.Device ERROR: WORKLOAD TIMED OUT - Killing user command..`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/13/2024 9:55:12 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[772876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772876)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772876&view=ms.vss-test-web.build-test-results-tab&runId=19769542&resultId=100006)|dotnet/runtime#106271|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by matouskozak** [comment]
It looks like a regular time out. The device logs don't show much. I'm going to close this issue because this error message is too general and could match builds that have failures as well (and time out is not the "real" cause of failure). This is a known problem for XHarness (see https://github.com/dotnet/xharness/issues/1188).
