### ISSUE TITLE
FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: JsonSerializerIsReflectionDisabled in .NET for Android

### ISSUE THREAD

**Issue by FANMixco** [dotnet/runtime#106315]
### Description

I have built a .NET for Android app with .NET 8 _(not MAUI)_. The app works perfectly when I don't link the libs. But when I tried to link them using: `<TrimMode>link</TrimMode>`, then I get the following error:

> [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: JsonSerializerIsReflectionDisabled
08-13 10:09:59.275 25131 25237 F mono-rt :    at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()

I have tried to exclude the lib, but nothing worked. I have tried to add this to the `.csproj`:

```xml
  <ItemGroup>
    <LinkerDescriptor Include="Linker.xml" />
  </ItemGroup>
``` 

And exclude the full lib but didn't work also:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="System.Text.Json">
    <type fullname="System.Text.Json.JsonSerializer" />
    <type fullname="System.Text.Json.JsonSerializerOptions" />
    <type fullname="System.Text.Json.JsonDocument" />
    <type fullname="System.Text.Json.JsonElement" />
    <type fullname="System.Text.Json.JsonTokenType" />
    <type fullname="System.Text.Json.JsonPropertyName" />
    <type fullname="System.Text.Json.Serialization.JsonConverter" />
    <type fullname="System.Text.Json.Serialization.JsonConverterFactory" />
  </assembly>
</linker>
```

Avoiding the linking increases the size of the app in almost 1 MiB. So, I'd like to know what I should do.

### Reproduction Steps

The code that is failing is the following:

```csharp
         var timetable = JsonSerializer.Deserialize<List<Timetable>>(results);

        public class Timetable
        {
            public int id { get; set; }
            public string member { get; set; }
            public string role { get; set; }
            public string min { get; set; }
            public string opt { get; set; }
            public string max { get; set; }
            public string time { get; set; }
            public string lastColor { get; set; }
            public bool disqualified { get; set; }
        }
```

I also tried to exclude the crashing methods adding this:

```csharp
        //The first line is what I added, yes, I'm calling .NET from JS. This is working if I don't link anything.
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CallJSInterface))]
        [JavascriptInterface]
        [Export]
        public void ExportToExcel(string data)
```

No changes.

### Expected behavior

To don't fails.

### Actual behavior

Fails when it tries to execute the previously provided code. The rest of the app works and also works if it's not linked.

**Comment by FANMixco** [comment]
It might be related to:

https://github.com/dotnet/android/issues/8975

**Comment by eiriktsarpalis** [comment]
This is expected behavior when using the reflection-based serializer in trimmed applications. You should consider switching to the source generated serializer instead:

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0

**Comment by FANMixco** [comment]
> This is expected behavior when using the reflection-based serializer in trimmed applications. You should consider switching to the source generated serializer instead:
> 
> https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0

It didn't work.

```csharp

partial class CallJSInterface
    {
        [JsonSourceGenerationOptions(WriteIndented = true)]
        [JsonSerializable(typeof(List<Timetable>))]
        internal partial class TimetableContext : JsonSerializerContext
        {
        }

        public class Timetable
        {
            public int id { get; set; }
            public string member { get; set; }
            public string role { get; set; }
            public string min { get; set; }
            public string opt { get; set; }
            public string max { get; set; }
            public string time { get; set; }
            public string lastColor { get; set; }
            public bool disqualified { get; set; }
        }
    }

        private static List<Timetable> DeserializeTT(string results)
        {
            return JsonSerializer.Deserialize(results, TimetableContext.Default.ListTimetable);
        }
```

Any idea?
