### ISSUE TITLE
The HttpListener in Linux runtime always throws a "Cannot assign requested address" exception when calling the Start method for regular URLs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#106385]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-HttpListener-in-Linux-runtime-always/10716307)._

---
[severity:It's more difficult to complete my work]
When I execute the following code, the application will throw an exception: 

```
HttpListener listener = new();

listener.Prefixes.Add("http://www.contoso.com:8080/customerData/");
listener.Start();
```

System.Net.HttpListenerException (99): Cannot assign requested address
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()

I have ruled out the issue with the port and there are no other programs occupying the same port or address. But strangely, when the prefix is set to "http://*: 5000/", the program can still run normally. This issue occurs on Debian 12, Ubuntu 22.04, and CentOS. The. net SDK version used is 8.0

---
#### Feedback Bot on 8/6/2024, 03:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by wfurt** [comment]
This seems like misuse. The fragment above vill try to bind on address `www.contoso.com` resolves to
```
pid 13174] bind(55, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("20.112.250.133")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
Unhandled exception. System.Net.HttpListenerException (99): Cannot assign requested address
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at Program.<Main>$(String[] args) in /tmp/listener/Program.cs:line 9
```

and unless you configured it precisely it will fail .... as it should. 

You should use `http://*: 8080/` if you want server on port 8080.

**Comment by KiminoKaslana** [comment]
> This seems like misuse. The fragment above vill try to bind on address `www.contoso.com` resolves to
> 
> ```
> pid 13174] bind(55, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("20.112.250.133")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
> Unhandled exception. System.Net.HttpListenerException (99): Cannot assign requested address
>    at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
>    at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
>    at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
>    at System.Net.HttpListener.Start()
>    at Program.<Main>$(String[] args) in /tmp/listener/Program.cs:line 9
> ```
> 
> and unless you configured it precisely it will fail .... as it should.
> 
> You should use `http://*: 8080/` if you want server on port 8080.

The code comes from the official example: [HttpListener Class]( https://learn.microsoft.com/zh-cn/dotnet/api/system.net.httplistener?view=net-8.0). These codes look very old, but they still run normally in the runtime of Windows. Is there a problem in the document?

**Comment by wfurt** [comment]
I guess the example does not explain that you should change the test domain 'contoso.com' with whatever  domain you have.

**Comment by KiminoKaslana** [comment]
Sure. I really didn't know that this domain name needed to be bound. I thought this process didn't involve DNS. Thank you very much !
