### ISSUE TITLE
[STJ] Disallow property names that conflict with metadata property names

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#106390]
> I think the best course of action is to disallow properties that conflict with type discriminators. It produces JSON with duplicate properties that cannot be roundtripped -- the failure of the schema exporter is merely a side-effect of configuration being invalid.

_Originally posted by @eiriktsarpalis in https://github.com/dotnet/aspnetcore/issues/56575#issuecomment-2288568962_

This should include conflicting type discriminator id's, as well as reference types containing `$id` or `$ref` in cases where reference preservation has been enabled.

**Comment by gregsdennis** [comment]
Does the usage of `$id` or `$ref` have anything to do with JSON Schema, or is it independent/other functionality?

**Comment by eiriktsarpalis** [comment]
Unrelated, it's metadata being emitted when serializing with `ReferenceHandler.Preserve`.

**Comment by gregsdennis** [comment]
Okay. I understand it's existing behavior, but the overlap with JSON Schema is a bit concerning for me.
