### ISSUE TITLE
WebClient() Removal Timeline

### ISSUE THREAD

**Issue by Rishi556** [dotnet/runtime#106325]
As of now, `WebClient()` is just deprecated(https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0014, https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated), since .NET6.0 but I don't see a timeline for it to be removed(if it will be removed at all?). 

Is there plans to keep it around in a deprecated form for the foreseeable future or is there a timeline as to when deprecated classes get removed from .NET?

**Comment by teo-tsirpanis** [comment]
It's highly unlikely that `WebClient` will be removed. Deprecated APIs are typically kept around indefinitely for compatibility, and their functionality is disabled only in extreme cases when necessary to mitigate security vulnerabilities. Such example is `BinaryFormatter`, but the APIs are still present and throw by default.

**Comment by wfurt** [comment]
There is no current plan to remove it. Deprecated APIs will get very little attention and improvements and you may experience performance and functional gaps.
