### ISSUE TITLE
Runtime generates asm to explicitly convert from Span to ReadOnlySpan

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#106458]
### Description

If pass Span argument to a method with ReadOnlySpan parameter Runtime does explicit conversion from Span to ReadOnlySpan. It is not zero cost and it takes some asm commands.
Since a method with ReadOnlySpan parameter can not have a code to change the value by definition the method could directly access Span argument assigned for the ReadOnlySpan parameter.

Since ReadOnlySpan is for performance I'd expect better code gen. I don't expect big benefits, but maybe it's worth it, given that the code is noticeably reduced there and besides, there may be several such parameters.

### Reproduction Steps

See [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkYMBuG+p1jhhYBlCGADWnXD1qNmLAEoBXAHYYAlvhgsAwhHwAHdQBsYUYWYBu6sDGm8AzA1wxspgCZNSDAELqV2FAAngAqUOowNADeNAxxTE7+GAwAMhAQ4koG5AAUAJIACgCC7u6wuLgM2KXluACUsfEx1PGtDMIG2CoAPMBBGDAAfFU1drg+SgBmk2YMALwMKjAA7gx9AwDa5EgAujJt8dVlYyxhQQDq4QM+/XY5R7UT02ZoDBBKyUlrt7iX6hgDFR1fYHEbHCpPGZQeZgx5TKEiYw2GA5OivdZ2P4AmBAkEHL7lJTGZILNIZLJ6WC5B5jSFmYE0RoHYgAdgYhOJeIYAF9GS14gZwpZsAN+EgGF8yZkDJSYLkFK53AB5FTGIIdLq9W7DGkQ+H0pkMZqgiVqBhgJRQWBqPwkhh0LmtSbQBg5L7qGEOiUMbqw2n6qAsFI4gDmGAAFlwJQBqaMNfkHY0m+IWq04jC22OO+K86iG1qs82W60Z/5c3OG4iJM1SrKkfLFUYVP0VeOtJMHDU9DE6pvjAMwparDFbXbZuK63CnYJYmA3Aa4e59ulQV7vT5mjG/K6AhkJtqTlcww8BxHI1Hon5Y3fj03JDl22sy6Awesn55QPf5+KFh/lvmtIK6jCqKzDipK6TSrK9ZdlqAy9uC/Yfm2TTfnEXypiWtqerezrQm6ZoegsXoer674IsGKhhpGMZxmhRr0a0mHppm0a3hW+4FmyzE2mWhocdyQA=)

### Expected behavior

Runtime skip Span to ReadOnlySpan conversion where possible.

### Actual behavior

Runtime creates asm to explicitly convert Span to ReadOnlySpan.

### Regression?

-

**Comment by tannergooding** [comment]
The two methods are identical in .NET 9.

In .NET 8 the assembly was larger by a few bytes due to an additional local existing and getting zeroed out due to the `byref` field it contains. I expect this was mostly resolved with the promotion work that @jakobbotsch has been doing.
