### ISSUE TITLE
JIT: Assertion failed '!fgRngChkThrowAdded' during 'Calculate stack level slots'

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#106401]
On Windows x86:
```csharp
// Found by Antigen
// Reduced from 376.2 KB to 299 B.
public class TestClass
{
    public static void Main(string[] args)
    {
    }
}
/*
Environment:
set DOTNET_JitSkipArrayBoundCheck=1
set DOTNET_EnableHWIntrinsic=0
Assert failure(PID 2496 [0x000009c0], Thread: 36060 [0x8cdc]): Assertion failed '!fgRngChkThrowAdded' in 'System.Diagnostics.Tracing.Statics:MetadataForString(System.String,int,int,int):ubyte[]' during 'Calculate stack level slots' (IL size 71; hash 0xb9469e8f; Tier0)
    File: C:\wk\runtime\src\coreclr\jit\flowgraph.cpp:3642
    Image: C:\wk\runtime\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root\corerun.exe
*/
```

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I don't think we need this for .NET 9 given the non-standard config.

**Comment by amanasifkhalid** [comment]
> I don't think we need this for .NET 9 given the non-standard config.

That's fair; I can take a look at this one after RC1.

> In general I would expect bugs for non-standard configs that we do not test in CI. If we want to make those work, I think we should test them in CI before we try fuzzing them.

Sounds like something we can consider for quality week? Either removing these configs from Antigen, or adding new CI legs...

**Comment by AndyAyersMS** [comment]
We've tried to pare down the number of non-standard things Antigen tests in the past, seems like we need to do a bit more going forward. I would rather see us focus its testing on things our customers are likely to run into.

**Comment by kunalspathak** [comment]
Kept just the switches that are used in CI: https://github.com/kunalspathak/Antigen/commit/6b770423fc6dc93d32e9d8d3efae4e858bf41a44

**Comment by jakobbotsch** [comment]
Let's close this in favor of #106401 since this one was with non-standard configs.
