### ISSUE TITLE
Debugger shows incorrect local variable values following an exception

### ISSUE THREAD

**Issue by f2bo** [dotnet/runtime#106467]
In an `async` method, the debugger can show incorrect values for local variables following an exception.  This happens when `Just My Code` is disabled in Visual Studio.

I apologize if this is not the right place to report this. I'm unclear whether this is a runtime, compiler, or Visual Studio issue. 

### Reproduction Steps
1. Disable `Enable Just My Code` in the debugger settings for Visual Studio.
2. Create a new console app with top-level statements and run the following code:
    ```C#
    Func(27);
    // await Task.CompletedTask;

    void Func(int value)
    {
        var text = "ABC";
        if (text == "ABC") throw new ApplicationException();
    }
    ```
3. Following the exception, verify that the `text` variable has the expected value "ABC".

    ![image](https://github.com/user-attachments/assets/abbb12c8-4c00-4071-9335-2d246cd78b4e)

5. Uncomment the line that awaits the Task and run the program again.
6. Following the exception, notice that the debugger shows the value of the `text` variable as `null`.

    ![image](https://github.com/user-attachments/assets/f57749a9-be1e-4d7d-9d37-158c97bf7dab)

### Known Workarounds
Enable Just My Code

### Configuration
- Tested with Visual Studio 2022 v17.11.0 and Visual Studio 2022 Preview v17.12.0 
- .NET 8.0.8
- Windows 10 22H2 x64

### Other information
This may not be related but it's really the reason why I began to look more closely at this problem. If you attempt to examine the value of the method's `value` argument above, the debugger shows the following message.
```
Local variables and arguments are not available in '[Exception]' call stack frames. To obtain these, configure the debugger 
to stop when the exception is thrown and rerun the scenario.
```
This started happening for the previous few releases of Visual Studio 2022 and has made debugging exceptions really painful ever since given that it's not always possible to anticipate which exceptions should be configured to stop when the exception is thrown or to "rerun the scenario".

**Comment by tommcdon** [comment]
Hi @f2bo!  This does not look like a .NET runtime issue.  Please open a Visual Studio feedback item at https://developercommunity.visualstudio.com/VisualStudio/report.
