### ISSUE TITLE
Possible tiered compilation issue in preview.7

### ISSUE THREAD

**Issue by SeeminglyScience** [dotnet/runtime#106427]
### Description

While updating [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell) to `9.0.0-preview.7.24405.7` we hit a test failure in some unchanged code utilizing [xoofx/markdig](https://github.com/xoofx/markdig). After getting a minimal repro together, it appears to only occur after the method has been invoked a few times. It does not appear to be a logic error in markdig and only occurs in preview.7

### Reproduction Steps

```csharp
using System.Runtime.InteropServices;
using Markdig;

while (true)
{
    DoTest();
}

void DoTest()
{
    Console.WriteLine(RuntimeInformation.FrameworkDescription);
    for (int i = 0; i < 1000; i++)
    {
        Markdown.Parse("Some **test string** to write in a file");
    }

    Thread.Sleep(500);


    for (int i = 0; i < 1000; i++)
    {
        Markdown.Parse("Some **test string** to write in a file");
    }
}
```

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
  </ItemGroup>

</Project>
```

then ran with

```powershell
dotnet publish --configuration release --self-contained --runtime win-x64
.\bin\release\net9.0\win-x64\publish\MarkdigRuntimeIssue.exe
```

### Expected behavior

Loops forever without error

### Actual behavior

After a few loops this exception occurs

```raw
Unhandled exception. System.InvalidOperationException: The parser is in an invalid infinite loop while trying to parse inlines for block [ParagraphBlock] at position ($0, 0, 0-38
   at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
   at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
   at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at Program.<<Main>$>g__DoTest|0_0() in D:\Projects\MarkdigRuntimeIssue\Program.cs:line 15
   at Program.<Main>$(String[] args) in D:\Projects\MarkdigRuntimeIssue\Program.cs:line 7
```

### Regression?

Yes, this does not occur with `9.0.100-preview.6.24328.19`

### Configuration

> Which version of .NET is the code running on?

9.0.0-preview.7.24405.7

> What OS and version, and what distro if applicable?

Microsoft Windows 10.0.22631

> What is the architecture (x64, x86, ARM, ARM64)?

x64

> Do you know whether it is specific to that configuration?

Had someone else test on win-arm64, the issue *does not* occur. So it does appear to be specific to this configuration (ty @jborean93)

### Other information

![image](https://github.com/user-attachments/assets/c6a7bcf1-647e-454a-945a-c7c059753d2e)

**Comment by mmitche** [comment]
@AndyAyersMS

**Comment by AndyAyersMS** [comment]
Latest main is fine (@ ~rc1 snap). So indeed this is the same bug as https://github.com/dotnet/runtime/issues/105792.

@SeeminglyScience thank you for trying preview 7 and reporting this.
