### ISSUE TITLE
Ubuntu 24.04 LTS is not supported by the .NET 9 Preview installer. Please use the dotnet-install script - https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script.

### ISSUE THREAD

**Issue by fmaeseele** [dotnet/runtime#106452]
### Description

From Visual Studio Version 17.12.0 Preview 1.0
Cannot debug WSL .Net9 Preview7 project because .Net9 cannot be installed on Ubuntu 24.04

### Reproduction Steps

Create a .Net9 console project and try to debug it under WSL

### Expected behavior

If .Net9 is not installed, install it, then being able to debug .Net9 project.

### Actual behavior

Visual Studio claims that .Net9 is not installed on WSL. It proposes to install it, then fails to install.

**Comment by NikolaMilosavljevic** [comment]
[Triage] This seems to be an issue with Visual Studio. The following page describes ways to submit feedback and open issues with these products: https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2022
