### ISSUE TITLE
LdapConnection Modify Request Under Linux/AOT Fails with Encoding Error

### ISSUE THREAD

**Issue by stefanc172** [dotnet/runtime#106412]
### Description

Performing an LDAP modify request (Add/Replace) using System.DirectoryServices.Protocols.LdapConnection under Linux with AOT enabled fails with ErrorCode 83 (Encoding error). The same code works under Linux without AOT as well as under Windows with/without AOT.

I made a modified libldap to investigate the problem and it seems that there is a size mismatch for struct berval bv_len, which is of type ber_len_t. The size of ber_len_t is 8 bytes on Linux x64.
Below is the debug output from my modified libldap when running the sample (Replace, attribute: description, value: TEST) compiled without AOT:
```
bvalue[0]:
  bv_len: 0x4
```
Below is the output when running the sample compiled with AOT:
```
bvalue[0]:
  bv_len: 0x73c500000004
```
In the AOT-compiled sample, the lower 4 bytes of the length are correct (4), but the upper 4 bytes are not 0, which seems to cause the encoding error.

### Reproduction Steps

```
using System.DirectoryServices.Protocols;
using System.Net;

internal class Program
{
	static void Main(string[] args)
	{
		try
		{
			LdapDirectoryIdentifier ldapDirectoryIdentifier = new LdapDirectoryIdentifier("oldap1.sample.com", 389, false, false);
			NetworkCredential networkCredential = new NetworkCredential("cn=admin,dc=sample,dc=com", "sample");
			LdapConnection ldapConnection = new LdapConnection(ldapDirectoryIdentifier, networkCredential) { AuthType = AuthType.Basic };
			ldapConnection.SessionOptions.ProtocolVersion = 3;

			ldapConnection.Bind(networkCredential);

			ModifyRequest r = new ModifyRequest();
			r.DistinguishedName = "uid=testuser1, ou=people, dc=sample,dc=com";

			DirectoryAttributeModification a = new DirectoryAttributeModification();
			a.Name = "description";
			a.Operation = DirectoryAttributeOperation.Replace;
			a.Add("TEST");
			r.Modifications.Add(a);

			ModifyResponse re = (ModifyResponse)ldapConnection.SendRequest(r);

			Console.WriteLine("Ok");
		}
		catch (LdapException ldapEx)
		{
			Console.WriteLine($"LDAP Exception: {ldapEx.Message}, ErrorCode: {ldapEx.ErrorCode}");
		}
		catch (Exception ex)
		{
			Console.WriteLine($"Exception: {ex.Message}");
		}
	}
}
```

### Expected behavior

The LDAP modify request should be sent to the LDAP server.

### Actual behavior

The LDAP modify request fails in the function ldap_build_modify_req in file libraries\libldap\modify.c of libldap with LDAP_ENCODING_ERROR.

### Configuration

Tested with Dotnet 8.0.108/400 under Ubuntu 24.04 x64 and various other distributions/dotnet/libldap versions.

**Comment by jkotas** [comment]
> The size of ber_len_t is 8 bytes on Linux x64.

The C# definition in this repo is 4 bytes: https://github.com/dotnet/runtime/blob/c61dc727d5f6d1894969c6f9ff080622c94e555f/src/libraries/Common/src/Interop/Interop.Ldap.cs#L185 . It is correct for Windows, but it is not correct for Linux.

**Comment by steveharter** [comment]
> The C# definition in this repo is 4 bytes... It is correct for Windows, but it is not correct for Linux.

but we have this:

> The same code works under Linux without AOT

Was the Linux without AOT version also x64? If yes, then something else may be going with trimming.

**Comment by steveharter** [comment]
So perhaps under AOT, the struct is byte-aligned (4 + 8 for the two fields) instead of platform-alignment (8 + 8)? That would cause it to work under non-AOT. Currently that struct has just [[StructLayout(LayoutKind.Sequential)]](https://github.com/dotnet/runtime/blob/c61dc727d5f6d1894969c6f9ff080622c94e555f/src/libraries/Common/src/Interop/Interop.Ldap.cs#L182) without `Pack = 1` for example.

I'm not aware of AOT differences around field alignment -- @MichalStrehovsky @jkotas is there a difference?

**Comment by jkotas** [comment]
There should not be any layout difference.

My guess is that the size mismatch leads to reading uninitialized data somewhere. The uninitialized data happens to be zero with non-AOT, but non-zero with AOT.

If you can make a complete repro steps (e.g. by using https://www.forumsys.com/2022/05/10/online-ldap-test-server/ ), I will be happy to take a look.

**Comment by stefanc172** [comment]
I modified the original sample to point to the LDAP server from the link you provided. This LDAP server is not optimally suited for this case because it is read-only. However, the error can still be observed.

I compiled with:
`dotnet publish -r linux-x64 -c Release`

Running the dotnet dll without AOT gives:
`Exception: The user has insufficient access rights.`
This is correct, becasue of the read-only LDAP server.

Running the AOT binary:
`LDAP Exception: An encoding error occurred., ErrorCode: 83`

The modified sample:
```
using System.DirectoryServices.Protocols;
using System.Net;
using System.Runtime.InteropServices;

internal class Program
{
	static void Main(string[] args)
	{
		try
		{
			LdapDirectoryIdentifier ldapDirectoryIdentifier = new LdapDirectoryIdentifier("ldap.forumsys.com", 389, false, false);
			NetworkCredential networkCredential = new NetworkCredential("cn=read-only-admin,dc=example,dc=com", "password");
			LdapConnection ldapConnection = new LdapConnection(ldapDirectoryIdentifier, networkCredential) { AuthType = AuthType.Basic };
			ldapConnection.SessionOptions.ProtocolVersion = 3;

			ldapConnection.Bind(networkCredential);

			ModifyRequest r = new ModifyRequest();
			r.DistinguishedName = "uid=einstein, dc=example,dc=com";

			DirectoryAttributeModification a = new DirectoryAttributeModification();
			a.Name = "description";
			a.Operation = DirectoryAttributeOperation.Replace;
			a.Add("TEST");
			r.Modifications.Add(a);

			ModifyResponse re = (ModifyResponse)ldapConnection.SendRequest(r);

			Console.WriteLine("Ok");
		}
		catch (LdapException ldapEx)
		{
			Console.WriteLine($"LDAP Exception: {ldapEx.Message}, ErrorCode: {ldapEx.ErrorCode}");
		}
		catch (Exception ex)
		{
			Console.WriteLine($"Exception: {ex.Message}");
		}
	}
}
```

**Comment by steveharter** [comment]
> My guess is that the size mismatch leads to reading uninitialized data somewhere. The uninitialized data happens to be zero with non-AOT, but non-zero with AOT.

Thanks; needed to verify the current behavior makes sense before changing that field size on non-Windows.

**Comment by jkotas** [comment]
One of the problems is here: https://github.com/dotnet/runtime/blob/b51e34c09b118ab6947e1ff0399d2b7e12effb4c/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L1351-L1355

We allocate memory for BerValue using `Marshal.AllocHGlobal` and then marshal the BerValue into it. The memory returned by `Marshal.AllocHGlobal` happens to have zeros for non-AOT, but non-zeros for AOT.

**Comment by steveharter** [comment]
As for priority for v9.0, this never appeared to work for AOT (not a regression) and at this point in the release such an issue wouldn't necessarily meet the bar. However, this appears to be a significant broken scenario for AOT, which we may want to backport to v9 anyway, so I think it could\should meet the v9.0 bar. Thoughts?

**Comment by jkotas** [comment]
I think that this is intermittent bug. It can come and go at will depending on the content of uninitialized memory. It is unlikely to be specific to AOT.

**Comment by steveharter** [comment]
I put up a PR for that; updating just the size seems fine. No extra zeroing is necessary since the `Marshal.StructureToPtr` should completely overwrite all bytes.

See the PR for whether that field should be IntPtr or long (still investigating).
