### ISSUE TITLE
WASM: Satellite resources not read as expected in .net9.0 preview7

### ISSUE THREAD

**Issue by dczuo** [dotnet/runtime#106456]
### Description

[wba1.zip](https://github.com/user-attachments/files/16625089/wba1.zip)

### Reproduction Steps

Run wba1

### Expected behavior

Console output: TestChinese

### Actual behavior

Console output: TestInvariant

### Regression?

Yes, preview6 is fine

**Comment by lewing** [comment]
duplicate of https://github.com/dotnet/runtime/issues/105937

**Comment by lewing** [comment]
cc @maraf
