### ISSUE TITLE
Miscellaneous.CopyCtor.ValidateCopyConstructorAndDestructorCalled failing with "Values Differ"

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#106428]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=776122
Build error leg or test failing: ValidateCopyConstructorAndDestructorCalled

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["ValidateCopyConstructorAndDestructorCalled()", "Fail: 0 != 2"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=776122
**Error message validated:** `[ValidateCopyConstructorAndDestructorCalled() Fail: 0 != 2`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/15/2024 12:35:15 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[776265](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776265)|dotnet/runtime|[global::Miscellaneous.CopyCtor.ValidateCopyConstructorAndDestructorCalled()](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776265&view=ms.vss-test-web.build-test-results-tab&runId=19870814&resultId=112602)|dotnet/runtime#106424|
|[776122](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776122)|dotnet/runtime|[global::Miscellaneous.CopyCtor.ValidateCopyConstructorAndDestructorCalled()](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776122&view=ms.vss-test-web.build-test-results-tab&runId=19867798&resultId=112603)|dotnet/runtime#106218|
|[2515708](https://dev.azure.com/dnceng/internal/_build/results?buildId=2515708)|dotnet-runtime|[global::Miscellaneous.CopyCtor.ValidateCopyConstructorAndDestructorCalled()](https://dev.azure.com/dnceng//internal/_build/results?buildId=2515708&view=ms.vss-test-web.build-test-results-tab&runId=54026863&resultId=117062)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|3|3|

**Comment by jkoritzinsky** [comment]
The PR causing this failure has been reverted.
