### ISSUE TITLE
Problem with hitting breakpoints while using Firefox or Firefox Developer Edition in InteractiveWebAssembly render mode, but no issues when using Microsoft Edge or Google Chrome.

### ISSUE THREAD

**Issue by MGabala** [dotnet/runtime#106470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, as the title says:

There is a problem with **InteractiveWebAssembly** when using Firefox or Firefox Developer Edition with the following code:

```
@page
@rendermode InteractiveWebAssembly

<button class="btn btn-primary" @onclick="LoadUserStateAsync">Button</button>

@code {

    [Inject]
    private AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;
    private async Task LoadUserStateAsync()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
    }
}
```

However, the same piece of code works fine with Microsoft Edge or Google Chrome.

If I change **InteractiveWebAssembly** to **InteractiveAuto**, it works fine.

### .NET Version

8.0.400

**Comment by thaystg** [comment]
Are you using VS?

**Comment by MGabala** [comment]
> Are you using VS?

Yes, newest production version

**Comment by thaystg** [comment]
VS does not support debugging on Firefox.

**Comment by thaystg** [comment]
This is a non supported scenario. If this is an important scenario for you please open an issue here: https://developercommunity.microsoft.com/VisualStudio/suggest
