### ISSUE TITLE
Timeout at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#106596]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=779538
Build error leg or test failing: System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits
Pull request: https://github.com/dotnet/runtime.git/pull/106589

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits", 
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=779538
**Error message validated:** `[at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/18/2024 7:42:59 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by liveans** [comment]
It's highly likely that this has the same symptom as `SendStreamLimitRequestsConcurrently_Succeeds`, which was 20 sec timeout and as we've discovered that test was a bit slow when `streamLimit:1000` and decided to increase timeout (#103410). We can do the same thing for this as well.

So this is probably test issue, not a product issue.
Moving milestone to 10.0 and if this becomes pain for `release/9.0` branches, we can increase timeout over there as well.

/cc @ManickaP

**Comment by ManickaP** [comment]
I agree. Are you gonna put up a PR or should I?

**Comment by liveans** [comment]
> I agree. Are you gonna put up a PR or should I?

I can do it

**Comment by ericstj** [comment]
This issue is still being hit in release builds.  Can you port your change to `release/9.0`?

**Comment by liveans** [comment]
> This issue is still being hit in release builds. Can you port your change to `release/9.0`?

This is ported to `release/9.0` in #107120.
