### ISSUE TITLE
System.Numerics.Tensors Non-monotonic constructor errors

### ISSUE THREAD

**Issue by soerenwolfers** [dotnet/runtime#106538]
### Description

```csharp
new TensorSpan<double>(new double[j], lengths: new IntPtr[] {2}, strides: new IntPtr[] {1}); 
```
throws a ArgumentException if `j == 1` but not if `j == 0` or `j > 1`.

### Reproduction Steps

```csharp
using System.Diagnostics.CodeAnalysis;
using System.Numerics.Tensors;

namespace ConsoleApp1;

public abstract class Program
{
	[Experimental("SYSLIB5001")]
	public static void Main()
	{
		new TensorSpan<double>(new double[0], lengths: new IntPtr[] {2}, strides: new IntPtr[] {1});
		new TensorSpan<double>(new double[2], lengths: new IntPtr[] {2}, strides: new IntPtr[] {1});
		new TensorSpan<double>(new double[1], lengths: new IntPtr[] {2}, strides: new IntPtr[] {1}); 
	}
}
```

### Expected behavior

Error when `j <= 1`

### Actual behavior

Error if and only if `j == 1`

### Configuration

.NET8, Ubuntu22, x64

**Comment by michaelgsharp** [comment]
Ok, this should throw when `j = 0 || j = 1`, but not when `j > 1`. I'll fix the 0 case. As long as there is enough backing memory its ok if there is more backing memory than the lengths/span can actually access.
