### ISSUE TITLE
Internal Package vulnerabilities referenced

### ISSUE THREAD

**Issue by Skintkingle** [dotnet/runtime#106528]
### Description

Latest versions of Microsoft.Extensions.Configuration.Json (8.0.0) (and by extension Microsoft.Extensions.Configuration.UserSecrets (8.0.0)) reference Vulnerable Package System.Text.Json (8.0.0)

### Reproduction Steps

Use the (as of writing) latest version of Microsoft.Extensions.Configuration.UserSecrets (8.0.0). Note that the transitive package "System.Text.Json" is 8.0.0, and marked as vulnerable

### Expected behavior

A package version for Microsoft.Extensions.Configuration.UserSecrets is available that doesn't allow a vulnerable package reference.

### Actual behavior

This package doesn't exist

### Known Workarounds

Reference System.Text.Json directly and pin it to version 8.0.4.

### Other information

A fix for System.Text.Json has been released that isn't vulnerable (8.0.4) as per the CVE https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
It would be desirable to have versions of these packages released that demand >= 8.0.4, rather than having 8.0.0 and having to upgrade System.Text.Json manually everywhere it's used.

**Comment by eiriktsarpalis** [comment]
Duplicate of #104669. We generally don't bump packages on account of transitive dependencies that are vulnerable. The recommendation is to manually bump the STJ version in your solution.

**Comment by Skintkingle** [comment]
This will end up being a reasonable overhead, to introduce the package in lots of places it's not already directly referenced, only transitively. And also keep track of the fact we're not actually directly using it, only via the framework version (I would assume). As we would likely want to drop its direct reference when a new version eventually comes out that doesn't allow it anymore. Is this really the recommendation? I feel like i've seen package bumps before when vulnerabilities are transitively associated. Or is that just for high risk vulnerabilities or maybe when there's a "critical mass" of packages that it compels the bump?

Thanks for the swift response.

**Comment by eiriktsarpalis** [comment]
I understand how this might be an issue. I find that using central package management is very helpful when you have a lot of projects in a single repo.

**Comment by Skintkingle** [comment]
I'll take a look at what that entails to use, thanks for the suggestion. Humerously this all came about from a colleague of mine who's checked out the preview version of the next visual studio which includes .Net 9 preview 6, Specifically [this feature](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview6/sdk.md#nugetaudit-now-raises-warnings-for-vulnerabilities-in-transitive-dependencies). I feel like this mixed messaging might get a lot of issues raised in the future. Especially if (as we do) you have warnings as errors enabled.

Further humour (although not an issue for you). It also showed up System.Private.Uri as a referenced vulnerable package, and that package specifically says not to directly reference it. haha.

I'll check out Central Package Management and see if it makes it at least a slightly lesser burden.
