### ISSUE TITLE
Published windows forms application complains about missing runtime on windows 11

### ISSUE THREAD

**Issue by FLAMESpl** [dotnet/runtime#106579]
### Description

I have published winforms application on my windows 10 PC but it does not work on another PC with windows 11.
It complains about missing dotnet desktop 8.0.8 runtime but it is already installed. Reinstalling it does not make any difference.

### Reproduction Steps

Application is published under SDK 8.0.401 with following command:

dotnet publish ./Hobbysta/src/Hobbysta.App/Hobbysta.App.csproj -o $outputPath --nologo --configuration Release --no-self-contained -p:PublishSingleFile=true --runtime win-x64

Project csproj has following options:

```xml
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>CS8600;CS8602;CS8603</WarningsAsErrors>
    <Version>0.9.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
 ```

### Expected behavior

Application is run correctly

### Actual behavior

There is a modal informing about missing dotnet desktop runtime with download link to 8.0.8

### Regression?

Previously I have published this application under dotnet 5 and it worked without problems

### Other information

Along with published executable following config file is produced:

```xml
<?xml version="1.0" encoding="utf-8"?>

<asmv1:assembly
    manifestVersion="1.0"
    xmlns="urn:schemas-microsoft-com:asm.v1"
    xmlns:asmv1="urn:schemas-microsoft-com:asm.v1"
    xmlns:asmv2="urn:schemas-microsoft-com:asm.v2"
    xmlns:asmv3="urn:schemas-microsoft-com:asm.v3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <assemblyIdentity version="1.0.0.0" name="CefSharp.MinimalExample.WinForms.app" />

  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="Win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>

  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <!-- UAC Manifest Options
        If you want to change the Windows User Account Control level replace the 
        requestedExecutionLevel node with one of the following.
        <requestedExecutionLevel  level="asInvoker" uiAccess="false" />
        <requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />
        <requestedExecutionLevel  level="highestAvailable" uiAccess="false" />

        Specifying requestedExecutionLevel node will disable file and registry virtualization.
        If you want to utilize File and Registry Virtualization for backward 
        compatibility then delete the requestedExecutionLevel node.-->
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>

  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true/PM</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>

  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- A list of all Windows versions that this application is designed to work with. 
            Windows will automatically select the most compatible environment.-->

      <!-- Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />
      <!-- Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />
      <!-- Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />
      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
    </application>
  </compatibility>
</asmv1:assembly>
```

**Comment by huoyaoyuan** [comment]
What's the output of `dotnet --info` on target machine?

**Comment by FLAMESpl** [comment]
C:\Users\joasz>dotnet --info

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  [https://aka.ms/dotnet/info](https://aka.ms/dotnet/info?fbclid=IwZXh0bgNhZW0CMTAAAR3ZeUa7t65AznrX8yr-fUK1CGUCNK0wRLPLaZ92WEp9nqdMS74QYgZFOME_aem_wZ9XcwtuosX7OpHud5-98Q)

Download .NET:
  [https://aka.ms/dotnet/download](https://aka.ms/dotnet/download?fbclid=IwZXh0bgNhZW0CMTAAAR0gKqW4t1FP8Om2_Du9jMTSjJQjBw2QaOcFthoR33y1dOJriBf3bQJeIe0_aem_U7MjPp659DSB2GyMTQ-R1g)
