### ISSUE TITLE
How to use CancellationToken with HttpClient

### ISSUE THREAD

**Issue by MhdTlb** [dotnet/runtime#106558]
I'm trying to setup a timeout for each separate [HttpClient.Send][1] call in .net8.0.

So I used `CancellationTokenSource` but It seems that it starts the timer as soon as I create it instead of starting the timer when calling `HttpClient` Send method.
Here is my unit tests result:

    [TestMethod]
    [DataRow(1)]
    [DataRow(10)]
    [DataRow(100)]
    [DataRow(1000)]
    [DataRow(10000)]
    [DataRow(100000)]
    [DataRow(1000000)]
    public void HttpClient_Send_CancellationTokenSource(int timeout)
    {
        var httpClient = new HttpClient();
        var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(timeout));

        var request = new HttpRequestMessage(HttpMethod.Get, "https://google.com");
        Thread.Sleep(2 * timeout);
        var response = httpClient.Send(request, cancellationToken: cts.Token);
    }

So all unit tests failed with this exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.

  [1]: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.send?view=net-8.0

**Comment by wfurt** [comment]
since you sleep _before_ the send, the token will be expired before you get to the send. What are you trying to do here @MhdTlb ?

**Comment by MhdTlb** [comment]
Hmmm I was expecting that the `CancellationTokenSource` timer starts exactly when calling HttpClient.Send. That way the timeout would be really measuring the Http request time and not the .net time to setup and invoke `HttpClient`.

**Comment by wfurt** [comment]
HttpClient is consumer of the token. It does not interact with any any active way and it simply stops processing when token is cancelled e.g. [CancellationToken.IsCancellationRequested ](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.iscancellationrequested?view=net-8.0)

**Comment by colejohnson66** [comment]
In most cases, the overhead of HttpClient itself doesn’t matter; the user cares about overall time spent retrieving a resource, not just the actual HTTP time.

**Comment by ManickaP** [comment]
If your goal is just timeout and not cancellation based on other event, you can use [`HttpClient.Timeout`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-8.0). Note that you can set this only before you send your first request on the client and you cannot change it afterwards. So for different timeouts per request, it's still better to use the `CancellationToken`.

**Comment by MhdTlb** [comment]
Thank you all.
