### ISSUE TITLE
windows-arm64 release CrossAOT_Mono crossaot builds failing on Windows headers

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#106521]
```
 C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\widemath.h(36): error C2143: syntax error: missing ':' before 'constant'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\widemath.h(36): error C2109: subscript requires array or pointer type
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\widemath.h(36): error C2056: illegal expression
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(76): error C2059: syntax error: 'constant'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(77): error C2061: syntax error: identifier '__U128D0'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(77): error C2059: syntax error: ';'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(77): error C2059: syntax error: '<cv-qualifier>'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(78): error C2061: syntax error: identifier '__U128Q0'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(78): error C2059: syntax error: ';'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(78): error C2059: syntax error: '<cv-qualifier>'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(79): error C2061: syntax error: identifier '__U128Q1'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(79): error C2059: syntax error: ';'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\um\softintrin.h(79): error C2059: syntax error: '<cv-qualifier>'
```

Maybe from updates to our build machines? Seems like it started within the past day or so.

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=777468
Build error leg or test failing: Build / windows-arm64 release CrossAOT_Mono crossaot / Build product
Pull request: https://github.com/dotnet/runtime/pull/106505

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "widemath.h(36): error C2143: syntax error: missing ':' before 'constant'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=777468
**Error message validated:** `[widemath.h(36): error C2143: syntax error: missing ':' before 'constant'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/16/2024 2:47:40 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ericstj** [comment]
This is a build failure blocking official builds too.
https://dev.azure.com/dnceng/internal/_build/results?buildId=2517099&view=logs&j=bcd78a6d-74df-5a56-16b0-296c102aaf79&t=9faa9bf0-4bfe-5a4f-f55e-0027707f4529

failure is also in 9.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2516842&view=logs&j=bcd78a6d-74df-5a56-16b0-296c102aaf79&t=9faa9bf0-4bfe-5a4f-f55e-0027707f4529

It looks like it's building `fetchzlibng-build` @carlossanlop

**Comment by lewing** [comment]
This is being worked on.  The new windows sdk `10.0.26100.0` that rolled out with latest helix images is breaking the build inside zlib-ng.

**Comment by jkotas** [comment]
#106578 has workaround that should fix the build break. 

We may still need to figure out the permanent fix as a follow up.

**Comment by jeffschwMSFT** [comment]
removing 'blocking-clea-ci' since it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by jkotas** [comment]
This was fixed in upstream zlibng by https://github.com/zlib-ng/zlib-ng/pull/1771 . We will pick up the proper upstream fix with the next zlibng update.
