### ISSUE TITLE
JIT: Debug/Release diff on ARM32

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#106551]
Hit by Antigen on Linux ARM32: [gist](https://gist.github.com/amanasifkhalid/cd0c1451ee324cb03a0a696e82f2e766). I'm afraid I don't have an ARM32 machine to trim this on. This repro hits an `OverflowException` in Debug, and an OOM exception in Release. cc @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
I get Overflow exception in both cases. It could be that Antigen consuming memory at the time of execution leading to OOM for the test.

<img width="1327" alt="image" src="https://github.com/user-attachments/assets/7e2d6e77-a3b2-4e3d-9bf8-12b2b8610287">
