### ISSUE TITLE
wasi interop failed to work after .net 9 preview 7 release

### ISSUE THREAD

**Issue by ReneeGA2020** [dotnet/runtime#106523]
### Description

Wasm import export seems to be broken in this preview.
It looks like the wasmtime recognize the output wasm file to be a component instead of executable wasm file.

### Reproduction Steps

run the native sample with 
./dotnet.cmd build /p:TargetOS=wasi /p:Configuration=release /t:RunSample src/mono/sample/wasi/native

### Expected behavior

Get correct result

### Actual behavior

> Error: cannot execute a component without --wasm component-model

### Regression?

worked fine before .net 9 preview 7

### Configuration

Tested in windows 11

**Comment by pavelsavara** [comment]
We started producing WASI components and switched to WASI preview2. 
We are not going to support preview 1.

**Comment by ReneeGA2020** [comment]
> We started producing WASI components and switched to WASI preview2. We are not going to support preview 1.

I assume there will be new sample for native interop.

**Comment by pavelsavara** [comment]
Native sample is currently broken because of some trimming issue. I'm looking at it as part of https://github.com/dotnet/runtime/issues/106310

Interop with C code in the same .wasm core module (which is WASM core import/export)  is not related to component-model.
So I guess you need to upgrade your wasmtime ?

**Comment by ReneeGA2020** [comment]
> Native sample is currently broken because of some trimming issue. I'm looking at it as part of #106310
> 
> Interop with C code in the same .wasm core module (which is WASM core import/export) is not related to component-model. So I guess you need to upgrade your wasmtime ?

I added <TrimMode>partial</TrimMode> to the native sample and it worked now.
Thanks for the information. 

So I guess it's actually a trim issue instead.

I will close this issue as the interop itself works fine.
