### ISSUE TITLE
Test failure: "Internal consistency check failed" in System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.InvalidKeySize_DoesNotInvalidateKey

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#106556]
**Important**: This was found in a 9.0 unrelated PR. Please consider submitting a backport to fix it.

## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160
Build error leg or test failing: `System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.InvalidKeySize_DoesNotInvalidateKey` in `net9.0-windows-Release-x64-coreclr_checked-Windows.10.Amd64.Open`

## Error Message

```json
{
  "ErrorMessage" : "CryptographicException : An internal consistency check failed",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/106532
- Queue: `Libraries Test Run checked coreclr windows x64 Release`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160&view=logs&j=51e4640a-c078-5be6-cc1b-f971e75d762f&t=325dd1cc-a862-54bb-9def-23eb1f229981
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-106532-merge-3a3bfa9cf4694a5285/System.Security.Cryptography.Tests/1/console.acc6a7dc.log?helixlogtype=result
- Output:
```
    System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.InvalidKeySize_DoesNotInvalidateKey [FAIL]
      System.Security.Cryptography.CryptographicException : An internal consistency check failed.
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Create.cs(58,0): at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngAlgorithmCore.cs(73,0): at System.Security.Cryptography.CngAlgorithmCore.GetOrGenerateKey(Int32 keySize, CngAlgorithm algorithm)
        /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.SignVerify.cs(147,0): at System.Security.Cryptography.DSACng.ComputeQLength()
        /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.SignVerify.cs(25,0): at System.Security.Cryptography.DSACng.CreateSignature(Byte[] rgbHash)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/DSA.cs(247,0): at System.Security.Cryptography.DSA.SignData(Stream data, HashAlgorithmName hashAlgorithm)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/DSAWrapper.cs(36,0): at System.Security.Cryptography.DSAWrapper.SignData(Stream data, HashAlgorithmName hashAlgorithm)
        /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs(61,0): at System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.SignData(DSA dsa, Byte[] data, HashAlgorithmName hashAlgorithm)
        /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs(123,0): at System.Security.Cryptography.Dsa.Tests.DSASignVerify.InvalidKeySize_DoesNotInvalidateKey()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160
**Error message validated:** `[CryptographicException : An internal consistency check failed`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/16/2024 6:07:43 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[778160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160)|dotnet/runtime|[System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.InvalidKeySize_DoesNotInvalidateKey](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160&view=ms.vss-test-web.build-test-results-tab&runId=19936374&resultId=180794)|dotnet/runtime#106532|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by bartonjs** [comment]
Dupe of #91860
