### ISSUE TITLE
Suspicious move, possible use after move?

### ISSUE THREAD

**Issue by Xazax-hun** [dotnet/runtime#10662]
I think there might be a use after move in `src/jit/lower.cpp`

See: https://github.com/dotnet/coreclr/blob/master/src/jit/lower.cpp#L561

The variable `condRange` might have been moved just before its use.

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

**Comment by BruceForstall** [comment]
I'm going to close this
