### ISSUE TITLE
Invalid Environment.ProcessorCount on AMD EPYC 9554. Shows 64 instead of 128

### ISSUE THREAD

**Issue by nlwolf** [dotnet/runtime#106642]
### Description

Environment.ProcessorCount returns 64 instead of 128 on  AMD EPYC 9554
This CPU has 64 cores, 128 threads.
This has performance implications as my app struggles to use 100% of CPU in calculations.
Setting Environment variable DOTNET_PROCESSOR_COUNT to 128 appears to fix the issue

### Reproduction Steps

Console.WriteLine(Environment.ProcessorCount);

### Expected behavior

128

### Actual behavior

64

### Known Workarounds

Set Environment  variable: DOTNET_PROCESSOR_COUNT=128

### Configuration

AMD EPYC 9554 64-core processor
.NET 8.08
OS:
Edition	Windows Server 2022 Standard
Version	21H2
Installed on	‎8/‎19/‎2024
OS build	20348.2655

### Other information

Interestingly, another system variable NUMBER_OF_PROCESSORS is set to 64. Changing it to 128 has no effect.

**Comment by huoyaoyuan** [comment]
It's possibly related to [CPU groups](https://learn.microsoft.com/windows/win32/procthread/processor-groups). On Windows 11 or Windows Server 2022+, .NET is expected to use all CPU groups by default: https://learn.microsoft.com/dotnet/core/runtime-config/threading#use-all-cpu-groups-on-windows

**Comment by nlwolf** [comment]
This issue was caused by incorrect runtime.config element:  `"System.GC.CpuGroup": 1`
Removing it, or setting it to  `"System.GC.CpuGroup": true` fixed the problem
