### ISSUE TITLE
Serializing Dictionary with nulls with JsonIgnoreCondition.WhenWritingNull emits null values.

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/runtime#106617]
### Description

If you serialize a dictionary with null values and specify `DefaultIgnoreCondition` as `WhenWritingNull`, null values are still emitted.

### Reproduction Steps

F# code here but I think it's pretty obvious:

```fsharp
open System.Collections.Generic
open System.Text.Json

let options =
    JsonSerializerOptions(DefaultIgnoreCondition = Serialization.JsonIgnoreCondition.WhenWritingNull)

let theDict : IDictionary<string, obj> = dict [ "Test", null; "Foo", null ]
let theJson = JsonSerializer.Serialize(theDict, options)
```

### Expected behavior

`theJson` should be an empty JSON object e.g.

```fsharp
theJson : string = "{}"
```

### Actual behavior

`theJson` contains two null fields:

```fsharp
theJson: string = "{"Test":null,"Foo":null}"
```

### Known Workarounds

Manually remove null fields from the dictionary before serializing. However, this is misleading - the `JsonIgnoreCondition` states that null values will be omitted.

### Configuration

.NET 8, Windows, x64

**Comment by elgonzo** [comment]
> However, this is misleading - the JsonIgnoreCondition states that null values will be omitted.

No, it's not misleading. The documentation for `DefaultIgnoreCondition` states that it applies to properties (as well as fields, if `IncludeFields` is set to true). Values in dictionaries are neither properties nor fields.

**Comment by jeffhandley** [comment]
Echoing @elgonzo's comment, values in dictionaries would not have the same behavior. Emitting the null values would likely be needed for scenarios where the presence of the dictionary key is expected in the payload.

Thanks for reporting this nonetheless, @isaacabraham, as I understand why this might have been surprising.
