### ISSUE TITLE
ILCompiler package used in runtime without ensuring matching framework

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#106740]
### Description

See https://github.com/dotnet/runtime/pull/106729

When building the product we run on an older shared framework than the last built and consumed runtime.

### Reproduction Steps

Build dotnet/runtime when it's using a MicrosoftDotNetILCompilerVersion newer than the dotnet version, and ILC depends on an API change in the framework.

### Expected behavior

Build succeeds

### Actual behavior

Failure because the tool framework is missing API required by ILC

### Regression?

Yes, torn state introduced by https://github.com/dotnet/runtime/pull/100845

**Comment by ericstj** [comment]
Probably first introduced in https://github.com/dotnet/runtime/pull/89655#issuecomment-1656559477 where @jkotas predicted this problem.

@sbomer

**Comment by MichalStrehovsky** [comment]
This was resolved in #107583.
