### ISSUE TITLE
Libraries build blocked by `System.TypeLoadException`

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#106731]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=782209
Build error leg or test failing: Build / linux-arm Debug AllSubsets_CoreCLR_ReleaseRuntimeLibs / Build product
Pull request: https://github.com/dotnet/runtime.git/pull/106720

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Could not load type 'System.Runtime.InteropServices.MemoryMarshal' from assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=782209
**Error message validated:** `[Could not load type 'System.Runtime.InteropServices.MemoryMarshal' from assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/20/2024 10:40:20 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[782589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782589)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782589/logs/1018)|dotnet/runtime#106720|
|[782590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782590)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782590/logs/80)|dotnet/runtime#106720|
|[782476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782476)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782476/logs/1896)||
|[782438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782438)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782438/logs/80)|dotnet/runtime#106727|
|[782437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782437)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782437/logs/955)|dotnet/runtime#106727|
|[2520204](https://dev.azure.com/dnceng/internal/_build/results?buildId=2520204)|dotnet-runtime|Build managed CoreCLR components, all libraries, hosts, and packs|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2520204/logs/4056)||
|[2520206](https://dev.azure.com/dnceng/internal/_build/results?buildId=2520206)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2520206/logs/105)||
|[2520205](https://dev.azure.com/dnceng/internal/_build/results?buildId=2520205)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2520205/logs/528)||
|[782209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782209)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782209/logs/1454)|dotnet/runtime#106720|
|[782262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=782262)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/782262/logs/1256)|dotnet/runtime#106723|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|10|10|10|

**Comment by agocke** [comment]
This was a bad merge that should be fixed now.
