### ISSUE TITLE
[mono] Apple mobile runtime tests can't load BigArray_32_1 in ClassLoader tests, the size is too big.

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#106797]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=784159
Build error leg or test failing: `Loader_classloader`
Affected CI: `[tvos,ios]_arm64_release_allsubsets_mono_runtimetests` (`runtime-extra-platforms`)
Range of commits: https://github.com/dotnet/runtime/compare/779baa69...631778a2

Stack trace:
```
[19:39:55.4517280] 2024-08-21 16:39:55.525 Loader_classloader[84744:102779304] System.TypeLoadException: Can't load type BigArray_32_1. The size is too big.
[19:39:55.4517630]    at __GeneratedMainWrapper.Main()
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "Detected exit code 101 from \\/tmp\\/helix\\/working\\/.*\\/uploads\\/net\\.dot\\.Loader_classloader\\.log",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=784159
**Error message validated:** `[Detected exit code 101 from \/tmp\/helix\/working\/.*\/uploads\/net\.dot\.Loader_classloader\.log`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/22/2024 7:07:41 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by matouskozak** [comment]
Likely introduced by the new tests in https://github.com/dotnet/runtime/pull/104393 @lambdageek

**Comment by lambdageek** [comment]
We should probably ifdef the 32-bit/64-bit structs in that test

**Comment by matouskozak** [comment]
> We should probably ifdef the 32-bit/64-bit structs in that test

There is something off with the current Mono support. I tried removing completely the 32-bit code and it failed on `Assert.Throws<TypeLoadException>(() => sizeof(BigArray_64_2));`

```
Xunit.Sdk.ThrowsException: Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.TypeLoadException)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in /_/src/Microsoft.DotNet.XUnitAssert/src/ExceptionAsserts.cs:line 47
   at Xunit.Assert.Throws[TypeLoadException](Func`1 testCode) in /_/src/Microsoft.DotNet.XUnitAssert/src/ExceptionAsserts.cs:line 113
   at LargeStructSize.TestLargeStructSize() in <PATH>/src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs:line 48
```
