### ISSUE TITLE
`CertificateRequest.CreateSelfSigned` fails on macOS Sequoia

### ISSUE THREAD

**Issue by Annny-Cap-Daniel** [dotnet/runtime#106775]
Update: repro app [here](https://github.com/dotnet/runtime/issues/106775#issuecomment-2302734439)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the command `dotnet dev-certs https` fails with the error:
`There was an error creating the HTTPS developer certificate.`

Exception:
```
An error has occurred generating the certificate: Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.CreateSelfSignedCertificate(X500DistinguishedName subject, IEnumerable`1 extensions, DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.CreateAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.EnsureAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter, String path, Boolean trust, Boolean includePrivateKey, String password, CertificateKeyExportFormat keyExportFormat, Boolean isInteractive).
```

What I already tried:

- `dotnet dev-certs https --clean`
- installing the lastest dotnet version
- uninstalling all old dotnet versions
- reinstalling dotnet completely
- restarting the Terminal, reboot, etc.

Nothing changed the behaviour and i still get the same error.

### Expected Behavior

the certificate should be created.

### .NET Version

8.0.401

### Anything else?

```
dotnet --info
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.56cd0383
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [wasm-tools]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.8/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.8/WorkloadManifest.json
   Install Type:        FileBased

 [wasi-experimental]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.8/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.8/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.400
   Manifest Version:    17.5.8020/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.5.8020/WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.400
   Manifest Version:    17.5.8020/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maccatalyst/17.5.8020/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.8
  Architecture: arm64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by amcasey** [comment]
Moving this to `dotnet/runtime` now that there's a repro not involving aspnetcore.

**Comment by bartonjs** [comment]
I don't know when we're going to have a chance to look at this (not "indefinitely far", but probably "at least several days away").  We have a few small fires to deal with for the .NET 9 release on already in-market OSes, and are super-saturated on those tasks.

If anyone from the community at large wants to jump in and help debug what's going on, that'd be appreciated.

**Comment by oumaima-aarabe** [comment]
first try enabling verbose logging to get more detailed error messages using 
```bash
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_MULTILEVEL_LOOKUP=0
dotnet dev-certs https --trust --verbose
```
and several common troubleshooting steps would include to clear existing certificates manually or you use the `security` command to list and delete any certificates related to localhost or dotnet
```bash
security find-certificate -a
security delete-certificate -c "ASP.NET Core HTTPS development certificate"
```

also did you ensure that your user account has the necessary permissions to access the keychain, tried creating a certificate manually using openssl ?

**Comment by vcsjones** [comment]
This almost certainly looks like another lifetime issue. I should be able to take a look by the end of the week.

**Comment by vcsjones** [comment]
Before I get to it, any chance someone can try on .NET 9 preview 7 (or later)?

**Comment by vcsjones** [comment]
Okay, curiosity took over so I had a peek.

The "good news" is that our unit tests fail and reproduce the issue:

```plain
Interop+AppleCrypto+AppleCommonCryptoCryptographicException : The specified item is no longer valid. It may have been deleted from the keychain.
    Stack Trace:
     at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain) in /Users/vcsjones/Projects/runtime/src/libraries/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.X509.macOS.cs:line 279
     at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey) in /Users/vcsjones/Projects/runtime/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AppleCertificatePal.Keys.macOS.cs:line 199
     at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey) in /Users/vcsjones/Projects/runtime/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AppleCertificatePal.Keys.macOS.cs:line 131
     at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey) in /Users/vcsjones/Projects/runtime/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/RSACertificateExtensions.cs:line 53
     at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter) in /Users/vcsjones/Projects/runtime/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs:line 519
     at System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestChainTests.CreateAndTestChain(AsymmetricAlgorithm rootPrivKey, AsymmetricAlgorithm intermed1PrivKey, AsymmetricAlgorithm intermed2PrivKey, AsymmetricAlgorithm leafPubKey) in /Users/vcsjones/Projects/runtime/src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/CertificateRequestChainTests.cs:line 388
     at System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestChainTests.CreateChain_RSA() in /Users/vcsjones/Projects/runtime/src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/CertificateRequestChainTests.cs:line 43
```

The other "good news" is that this is the only thing that fails on macOS 15.

**Comment by vcsjones** [comment]
This is a behavioral change for macOS 15. I have a fix put up for it, but unfortunately there are no reasonable work around at the moment.

The core of the issue is that `X509Certificate2.CopyWithPrivateKey` does not work for RSA/ECDSA when the private key is an ephemeral key that was created or imported in to the internal `Algorithm.Create()`. On macOS, that is `SecurityTransforms`.

`CertificateRequest` uses this API itself, which is why it fails.

**Comment by adityamandaleeka** [comment]
@lewing @vcsjones Just confirming, this is not getting fixed in RC1?

**Comment by vcsjones** [comment]
@adityamandaleeka the fix is not present in the `release/9.0-rc1` branch.

**Comment by ZephiroRB** [comment]
Hey same error MacOs Sequio final version!

**Comment by vcsjones** [comment]
> Hey same error MacOs Sequoia final version!

Yep. This will be fixed in the October patch cycle for .NET. See the [corresponding announcement](https://github.com/dotnet/announcements/issues/324) for additional information.

**Comment by Flight** [comment]
Any update or workaround here? Our team is blocked because of this. Should we just reinstall the old version of Mac OS just to have this command work? `dotnet dev-certs https --trust`

**Comment by ryanmendoza** [comment]
> This shouldn't be closed until there is a release out the door.  And someone internal should be making the call to release an emergency patch release .402 that fixes this.

Agreed. Otherwise pointing to some documented steps on how to manually generate the certification and import it using the dotnet CLI would be better than a "wait until the October update train" hand-waive. 

We don't all have the luxury of not upgrading to Apple's latest OS because we're not all just dotnet developers.

**Comment by Flight** [comment]
So all the users of the modern Mac OS is blocked from using .net and you just tell to wait for the October release? Guys, it looks like a critical issue and the fix should be deployed in hours, not even days...

**Comment by Winter979** [comment]
Dont think its the best but it works for the time being. Generating a self signed crt + key, convert it to a pfx and then configure the app to use that 

appsettings.Development.json
```
"Kestrel": {
  "Endpoints": {
    "Https": {
      "Url": "https://localhost:7209",
      "Certificate": {
        "Path": "../Certs/localhost.pfx",
      }
    }
  }
}
```

At least i can not continue development.

**Comment by octo888** [comment]
> Dont think its the best but it works for the time being. Generating a self signed crt + key, convert it to a pfx and then configure the app to use that
> 
> appsettings.Development.json
> 
> ```
> "Kestrel": {
>   "Endpoints": {
>     "Https": {
>       "Url": "https://localhost:7209",
>       "Certificate": {
>         "Path": "../Certs/localhost.pfx",
>       }
>     }
>   }
> }
> ```
> 
> At least i can now continue development.

it helps me to run webapp (but I had to add config in the Program.cs) but I still can't make requests from android emulator.
I am shocked that this issue was closed and that's it, wait for November

**Comment by pvasek** [comment]
Workaround that worked for me:

1. download the tar.gz version of nightly build of upcoming dotnet, can be found in [package-table.md](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md)
2. Unpack it
3. Go to that unpacked folder
4. Run `./dotnet dev-certs https --trust` (it's important to use `./` otherwise it use the installed `dotnet`)

After that it ask for password install the certificate and debugging of my 8.0 app works again.

**Comment by kalebzettl** [comment]
@pvasek 
Thank you mate, that worked for me too, only thing I had to quarantine the folder, I have SIP enabled and all macOS wanted to do was complain about it being untrusted 🙄

xattr -d com.apple.quarantine -r dotnet-sdk-9.0.100-rc.2.24473.20-osx-arm64 
cd dotnet-sdk-9.0.100-rc.2.24473.20-osx-arm64 
./dotnet dev-certs https --trust

**Comment by MichaelCharles** [comment]
@kalebzettl @pvasek Thanks, that worked for me. Here's a consolidated instruction set:

1. Download the `tar.gz` file of the "main" release from [here](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md). If you're on an Apple Silicon Mac, it'll be [this one](https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-osx-arm64.tar.gz).
2. Unpack the file.
3. Remove the quarantine attribute from the folder by running `xattr -d com.apple.quarantine -r <folderName>`. For example, if the folder name is `dotnet-sdk-9.0.100-rc.2.24473.22-osx-arm64`, you would run `xattr -d com.apple.quarantine -r dotnet-sdk-9.0.100-rc.2.24473.22-osx-arm64`.
4. Navigate to the unpacked folder: `cd dotnet-sdk-9.0.100-rc.2.24473.22-osx-arm64`.
5. From that folder, run `./dotnet dev-certs https --trust`, making sure to include the `./` so that it doesn't use the globally installed version of `dotnet`.

**Comment by camerontucker** [comment]
Has anyone found the 8.0 daily that includes this patch?

https://aka.ms/dotnet/8.0/daily/dotnet-sdk-osx-x64.pkg -> 8.0.306 (nope)
https://aka.ms/dotnet/8.0.4xx/daily/dotnet-sdk-osx-x64.pkg -> 8.0.403 (nope)

**Comment by sergey-tihon** [comment]
[.NET 8.0.10](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.403-macos-x64-installer) is already available and feels like it contains the fix.

**Comment by nikosdelis** [comment]
> @kalebzettl @pvasek Thanks, that worked for me. Here's a consolidated instruction set:
> 
> 1. **Just in case, delete any certs that currently exist.** Open a terminal and run: `dotnet dev-certs https --clean`
> 2. **Download the `tar.gz` file of the "main" release from [the .NET SDK package table](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md).** You can also access the links directly below.
>    
>    * [Apple Silicon](https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-osx-arm64.tar.gz).
>    * [Intel](https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-osx-x64.tar.gz)
> 3. **Unpack the downloaded file.**
> 4. **Remove the quarantine attribute from the unpacked folder.** From your terminal run: `xattr -d com.apple.quarantine -r <folderName>` Replace `<folderName>` with the name of your unpacked folder. For example: `xattr -d com.apple.quarantine -r dotnet-sdk-9.0.100-rc.2.24473.22-osx-arm64`
> 5. **Navigate to the unpacked folder:** `cd dotnet-sdk-9.0.100-rc.2.24473.22-osx-arm64`
> 6. **From within this folder, run the following to generate and trust the certificate.** `./dotnet dev-certs https --trust`

This worked great for me! Thanks!

**Comment by JohnGalt1717** [comment]
> [.NET 8.0.10](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) is already available and feels like it contains the fix.

It doesn't fix it.

This is still broken.  Not sure how this isn't resolved yet. Entire platform completely broken without hacking with pre-release software.

**Comment by vcsjones** [comment]
> It doesn't fix it.

I was not able to reproduce this with Sequoia and .NET 8.0.10.

Can you please be more specific about the error you are getting, steps to reproduce, and the output of `dotnet --info`?

<img width="1566" alt="Screenshot 2024-10-08 at 3 34 18 PM" src="https://github.com/user-attachments/assets/bc07ee4b-f6ae-4308-8a79-061cfa49a909">

**Comment by JohnGalt1717** [comment]
ok, for anyone that hits this: 

dotnet dev-certs https --clean
dotnet dev-certs https --trust

Will work if it doesn't just work automatically.

Thanks @vcsjones for the clean suggestion.

**Comment by MoElwekil** [comment]
I have had the same issue. I have downloaded the latest SDK (SDK 8.0.403) and it worked for me.
I was using (SDK 8.0.402) on Mac OS 15 and I couldn't generate the dev-certs.

Thanks for your help.

**Comment by eltoro83** [comment]
For .NET 6, it doesn't work. I uninstalled all my .NET SDKs and Runtimes and installed the latest .NET 6 version. However, when I create a new certificate and run `dotnet dev-certs https --check`, I get the message: `No valid certificate found`.

![Image](https://github.com/user-attachments/assets/1ddb4068-528b-4b90-895e-1c81f98d344b)



Do you have any suggestions? I'm working on an Intel iMac and currently can't proceed with my .NET Core projects. I need .NET 6 for a customer project.

I also installed version 6.0.427, but the same issue persists.

Thanks in advance!

**Comment by vcsjones** [comment]
@eltoro83 

>  I get the message: No valid certificate found.

This issue is specifically about people getting the error "There was an error creating the HTTPS developer certificate.".

However, it looks you just need to run `dotnet dev-certs https --trust` first. If you continue to have issues with `dotnet dev-certs`, I would recommend opening an issue in [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues).

**Comment by michelo243** [comment]
a workaround to add a functioning localhost certificate  is posted in this post: [HERE](https://dev.to/michaelcharles/fixing-the-https-developer-certificate-error-in-net-on-macos-sequoia-516h)
