### ISSUE TITLE
Double.NegativeZero constant has an incorrect bit format

### ISSUE THREAD

**Issue by jk09** [dotnet/runtime#106857]
### Description

The constant `System.Double.NegativeZero` has the same binary representation as the constant 0.0.

According to the CLI standard the floating-point number binary representation is specified by IEC 60559 (IEEE 774), which suggests that +0.0 has all bits set to 0, and -0.0 all bit the first bit set to 0 (https://en.wikipedia.org/wiki/Signed_zero)

### Reproduction Steps

This code
```
  static string DblRepr(double d) => string.Format(CultureInfo.InvariantCulture, "{0:F}", d);

  Console.WriteLine(DblRepr(double.NegativeZero));
  Console.WriteLine(DblRepr(-0.0));
  Console.WriteLine(DblRepr(1.0/double.NegativeInfinity));
```
returns on .NET 7.0.20
```
0.00
-0.00
-0.00
```

### Expected behavior

When you extract all bits of a `double`, e.g. using `BitConverter.DoubleToUInt64Bits(double)` , negative zero should have the first bit set to 1 and all other to 0.

### Actual behavior

The constant `double.NegativeZero` behaves as `+0.0`, though the values `-0.0` and `1.0/double.NegativeInfinity` assume the correct binary representation of the negative zero.

### Configuration

.NET 7.0.20
Microsoft Windows NT 10.0.22631.0
Intel(R) Core(TM) i9-9900T

**Comment by ufcpp** [comment]
https://github.com/dotnet/runtime/pull/87364

**Comment by jk09** [comment]
ok!

**Comment by filipnavara** [comment]
Thanks for the report. .NET 7 went out of support on May 14, 2024. This was already fixed in .NET 8 and newer releases.
