### ISSUE TITLE
ConfigurationBinder.Get binds empty IDictionary<string, string> as null

### ISSUE THREAD

**Issue by realbart** [dotnet/runtime#106820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When serializing options, I expect an empty JSON-object { } to be serialized to an empty Dictionary.

### Expected Behavior

When reading an options-object using `configuration.GetSection("Foo").Get<FooOptions>();` I expect a dictionary to be empty not null.

### Steps To Reproduce

1. Create a configuration

```json
{
    "Foo" : {
        "Bar": 1,
        "Baz": {
        }
    }  
}
```

2. Create an OPTIONS object

```C#
public record FooOptions
{
    public required int Bar { get; init; }
    public required IDictionary<string, string> Baz{ get; init; }
}
```

3. Read it!

```C#
public void ConfigureServices(IConfiguration configuration, IServiceCollection services, TokenCredential credential)
{
    var fooOptions = configuration.GetSection("Foo").Get<FooOptions>();
    foreach ((var key, var value) in Baz) {
       // do something
    }
}
```

Expected behavior:

    fooOptions.Baz is an empty dictionary, which can be enumerated
    
Actual behavior:

    fooOptions.Baz is null

### .NET Version

8.0.301

### Anything else?

This behavior occurs in a ASP.NET 8 project

**Comment by tarekgh** [comment]
This looks like the current behavior is still acceptable. Think about it why creating objects which do not have any configuration values?  

Currently the configuration only has values and treats the empty nested configuration `{}` as if it does not exist. There is an easy workaround for that which makes the property getter create the dictionary if it is null.

**Comment by realbart** [comment]
I've just pointed out inconsistent and unexpected behavior.
If nobody else has a problem with this, I am not goint to force the issue.

**Comment by tarekgh** [comment]
Thanks @realbart for your response. I am closing the issue for now and watch if we get more demand, we can consider doing something with this issue.
