### ISSUE TITLE
CMS Unable to Add Data to UnsignedAttributes Post-Signing in .NET Framework 4.8

### ISSUE THREAD

**Issue by Dimiikou** [dotnet/runtime#106808]
### Description

In .NET Framework 4.8, the `System.Security.Cryptography.Pkcs.SignerInfo.UnsignedAttributes` property only returns copies of the data, which do not propagate changes back to the root `SignedCms` object. This limitation prevents the modification of unsigned attributes after the signature has been computed.

In contrast, .NET 8 implements the `System.Security.Cryptography.Pkcs.SignerInfo` method `AddUnsignedAttribute(AsnEncodedData unsignedAttribute)`, which allows for the addition of data to `UnsignedAttributes` post-signing.

**Use Case**: The ability to manipulate `UnsignedAttributes` post-signing is crucial for adding the timestamp response from the Time Stamping Authority (TSA) after the signature has been created.

### Reproduction Steps

https://gist.github.com/Dimiikou/aeb676ff63e94267a3a1564526bf093b

### Expected behavior

I expected to be able to add something to `UnsignedAttributes` that is linked to the root `SignedCms` object.

### Actual behavior

I am getting a Copy of `UnsignedAttributes` that is no longer linked to the root `SignedCms` object, so adding my timestamp to the `UnsignedAttributes` collection has no effect.

### Known Workarounds

I've read about a Windows-only workaround using a NuGet package that leverages P/Invoke, but I couldn't find the exact usage or the package itself.

I tried using reflection to access the private fields, but due to the absence of setters, it was not possible to modify the values as intended.

### Configuration

- .NETFramwork 4.8
- Windows 11 Enterprise 10.0.2.22631 Build 22631
- x64
- No

**Comment by vcsjones** [comment]
This repository is for .NET / .NET Core issues. Feedback for .NET Framework should be filed at https://developercommunity.visualstudio.com/home.

Note that .NET Framework 4.x is no longer under active development, so I would not expect any changes or new APIs to add new functionality to `SignedCms` or `SignerInfo`.

**Comment by jeffhandley** [comment]
I'm closing this as it is specific to .NET Framework.

@Dimiikou, since as @vcsjones indicated, we shouldn't expect this capability to be added to .NET Framework, I suggest submitting a StackOverflow question for this topic to see if others have found a viable workaround.

**Comment by bartonjs** [comment]
This has since been asked and answered on StackOverflow: https://stackoverflow.com/a/78950029/6535399
