### ISSUE TITLE
XmlSerializerTests.Xml_DerivedIXmlSerializable is failing on linux-musl legs

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#106865]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=786082
Build error leg or test failing: XmlSerializerTests.Xml_DerivedIXmlSerializable
Pull request: https://github.com/dotnet/runtime/pull/80154

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "BaseIXmlSerializable xmlns:xs.*DerivedIXmlSerializable",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Cause: https://github.com/dotnet/runtime/pull/104173

cc @StephenMolloy

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=786082
**Error message validated:** `[BaseIXmlSerializable xmlns:xs.*DerivedIXmlSerializable`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/23/2024 9:39:20 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[786582](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786582)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786582&view=ms.vss-test-web.build-test-results-tab&runId=20217974&resultId=193161)|dotnet/runtime#106760|
|[786958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786958)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786958&view=ms.vss-test-web.build-test-results-tab&runId=20216244&resultId=192796)|dotnet/runtime#106831|
|[786737](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786737)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786737&view=ms.vss-test-web.build-test-results-tab&runId=20214978&resultId=187329)|dotnet/runtime#103795|
|[786915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786915)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786915&view=ms.vss-test-web.build-test-results-tab&runId=20215122&resultId=192057)|dotnet/runtime#106735|
|[786901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786901)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786901&view=ms.vss-test-web.build-test-results-tab&runId=20214544&resultId=179834)|dotnet/runtime#106901|
|[786875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786875)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786875&view=ms.vss-test-web.build-test-results-tab&runId=20214370&resultId=181991)|dotnet/runtime#80154|
|[786867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786867)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786867&view=ms.vss-test-web.build-test-results-tab&runId=20213976&resultId=197775)|dotnet/runtime#106900|
|[786786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786786)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786786&view=ms.vss-test-web.build-test-results-tab&runId=20213024&resultId=192796)||
|[786775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786775)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786775&view=ms.vss-test-web.build-test-results-tab&runId=20212380&resultId=197424)|dotnet/runtime#106844|
|[786050](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786050)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786050&view=ms.vss-test-web.build-test-results-tab&runId=20211974&resultId=197789)|dotnet/runtime#102498|
|[786719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786719)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786719&view=ms.vss-test-web.build-test-results-tab&runId=20210866&resultId=183917)|dotnet/runtime#106564|
|[786683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786683)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786683&view=ms.vss-test-web.build-test-results-tab&runId=20210374&resultId=192795)|dotnet/runtime#106765|
|[786625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786625)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786625&view=ms.vss-test-web.build-test-results-tab&runId=20208516&resultId=192795)|dotnet/runtime#106889|
|[786614](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786614)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786614&view=ms.vss-test-web.build-test-results-tab&runId=20208152&resultId=194228)|dotnet/runtime#106888|
|[786484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786484)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786484&view=ms.vss-test-web.build-test-results-tab&runId=20208116&resultId=180140)|dotnet/runtime#106660|
|[786597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786597)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786597&view=ms.vss-test-web.build-test-results-tab&runId=20207990&resultId=182211)|dotnet/runtime#105771|
|[786594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786594)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786594&view=ms.vss-test-web.build-test-results-tab&runId=20207788&resultId=183268)|dotnet/runtime#106413|
|[786546](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786546)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786546&view=ms.vss-test-web.build-test-results-tab&runId=20206000&resultId=192795)|dotnet/runtime#106839|
|[786477](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786477)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786477&view=ms.vss-test-web.build-test-results-tab&runId=20206034&resultId=193710)|dotnet/runtime#106779|
|[786528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786528)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786528&view=ms.vss-test-web.build-test-results-tab&runId=20205448&resultId=193196)|dotnet/runtime#103795|
|[786508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786508)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786508&view=ms.vss-test-web.build-test-results-tab&runId=20205382&resultId=179915)|dotnet/runtime#102547|
|[786470](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786470)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786470&view=ms.vss-test-web.build-test-results-tab&runId=20203046&resultId=184132)|dotnet/runtime#106882|
|[785908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785908)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785908&view=ms.vss-test-web.build-test-results-tab&runId=20202638&resultId=197789)|dotnet/runtime#106421|
|[786408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786408)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786408&view=ms.vss-test-web.build-test-results-tab&runId=20199414&resultId=177471)|dotnet/runtime#106403|
|[786355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786355)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786355&view=ms.vss-test-web.build-test-results-tab&runId=20198448&resultId=185286)|dotnet/runtime#106875|
|[786344](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786344)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786344&view=ms.vss-test-web.build-test-results-tab&runId=20198368&resultId=180355)|dotnet/runtime#106874|
|[786361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786361)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786361&view=ms.vss-test-web.build-test-results-tab&runId=20198372&resultId=191260)|dotnet/runtime#106779|
|[786340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786340)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786340&view=ms.vss-test-web.build-test-results-tab&runId=20197790&resultId=180100)|dotnet/runtime#106873|
|[786226](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786226)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786226&view=ms.vss-test-web.build-test-results-tab&runId=20192806&resultId=180654)|dotnet/runtime#80154|
|[786159](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786159)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786159&view=ms.vss-test-web.build-test-results-tab&runId=20192792&resultId=192889)||
|[786131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786131)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786131&view=ms.vss-test-web.build-test-results-tab&runId=20192574&resultId=192654)|dotnet/runtime#106859|
|[785977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785977)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785977&view=ms.vss-test-web.build-test-results-tab&runId=20192480&resultId=180654)|dotnet/runtime#106839|
|[786174](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786174)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786174&view=ms.vss-test-web.build-test-results-tab&runId=20191686&resultId=192795)|dotnet/runtime#106637|
|[786082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786082)|dotnet/runtime|[XmlSerializerTests.Xml_DerivedIXmlSerializable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786082&view=ms.vss-test-web.build-test-results-tab&runId=20189822&resultId=182879)|dotnet/runtime#80154|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|33|34|34|

**Comment by akoeplinger** [comment]
The reason is because of the ICU change that added a different whitespace for date time: https://github.com/dotnet/runtime/issues/83571

**Comment by am11** [comment]
Fixed by https://github.com/dotnet/runtime/pull/106891.
