### ISSUE TITLE
Globalization Invariant Mode string compare issue

### ISSUE THREAD

**Issue by tracktownsoftware** [dotnet/runtime#106828]
### Description

When Globalization Invariant Mode is turned on in csproj:
  \<InvariantGlobalization\>true\</InvariantGlobalization\>

Then this is not always true for strings s1, s2 and s3 using the System.Globalization.CultureInfo.InvariantCulture.CompareInfo.Compare method:
  if s1 < s2 and s2 < s3, it should follow that s1 < s3.

### Reproduction Steps

This code is from https://github.com/tracktownsoftware/NET-GlobalizationInvariantMode-String-Compare-Bug
```C#
    internal class Program
    {
        static void Main(string[] args)
        {
            var s1 = "бал";
            var s2 = "Бан";
            var s3 = "Д";

            var ci = System.Globalization.CultureInfo.InvariantCulture.CompareInfo;

            // First we pass the 3 strings in upper case with no problems.
            Debug.Assert(ci.Compare(s1.ToUpper(), s2.ToUpper(), System.Globalization.CompareOptions.IgnoreCase) < 0);
            Debug.Assert(ci.Compare(s2.ToUpper(), s3.ToUpper(), System.Globalization.CompareOptions.IgnoreCase) < 0);
            Debug.Assert(ci.Compare(s1.ToUpper(), s3.ToUpper(), System.Globalization.CompareOptions.IgnoreCase) < 0);

            // Now we pass the strings without ToUpper() - theoretically yielding the same result.
            Debug.Assert(ci.Compare(s1, s2, System.Globalization.CompareOptions.IgnoreCase) < 0);
            Debug.Assert(ci.Compare(s2, s3, System.Globalization.CompareOptions.IgnoreCase) < 0);

            // if s1 < s2 and s2 < s3, it should follow that s1 < s3.
            // This assertion fails if the project is running in invariant-globalization mode.
            // It succeecds if not running in invariant-globalization mode.
            //
            // To run in invariant-globalization mode, add the following to the property group
            // in StringCompareBug.csproj:
            //              <InvariantGlobalization>true</InvariantGlobalization>
            Debug.Assert(ci.Compare(s1, s3, System.Globalization.CompareOptions.IgnoreCase) < 0);
        }
    }
```

### Expected behavior

The last assertion should not FAIL:
Debug.Assert(ci.Compare(s1, s3, System.Globalization.CompareOptions.IgnoreCase) < 0);

### Actual behavior

The last assertion FAILS:
Debug.Assert(ci.Compare(s1, s3, System.Globalization.CompareOptions.IgnoreCase) < 0);

### Regression?

I don't know, but will investigate and report back.

### Known Workarounds

Do not use InvariantGlobalization, but that is not an option we want to use.

### Configuration

.NET 8.0.303
VS2022 17.10.5
Windows 11 Pro
23H2, 22631.4037

**Comment by Windows10CE** [comment]
After a bit of debugging, I believe this is a bug in the managed implementation of ordinal case-insensitive comparisons. This block causes equality to be done with the ToUpper'd codepoints, but the final return instead uses the original codepoints, causing the comparison itself to still be dependent on casing:
https://github.com/dotnet/runtime/blob/08338fcaa5c9b9a8190abb99222fed12aaba956c/src/libraries/System.Private.CoreLib/src/System/Globalization/InvariantModeCasing.cs#L206-L218
Changing the return to instead be `return (int)aUpper - (int)bUpper;` makes the example given in this issue run without problems, but I do not know for sure if this is a correct change to make in general.

**Comment by JoeErickson** [comment]
Should this be fixed before 10.0.0?

We have added a workaround to our software to use ToUpper before comparing in global-invariant mode, so our software is OK,

But what about software which depends on (a < c) if (a < b && b < c)? It is not hard to imagine code which gets stuck in a loop due to this issue.

**Comment by tarekgh** [comment]
@JoeErickson could you please elaborate more why you are using Invariant globalization mode in the first place?

**Comment by JoeErickson** [comment]
We have a customer who uses our SpreadsheetGear Engine (https://www.nuget.org/packages/SpreadsheetGear) on a version of Linux which only supports invariant globalization mode. We recently added support for this mode in response to our customer and our autotests found this problem due to a QuickSort failing because of the bug.

**Comment by tarekgh** [comment]
Thanks @JoeErickson for the info. I'll look at fixing this in 9.0. 

I am not familiar with `SpreadsheetGear` but doesn't need any Globalization features that Invariant mode will not be suitable for? I am asking to know if would be better to disable the invariant mode on the container?

**Comment by JoeErickson** [comment]
SpreadsheetGear is useful with invariant mode. It was trivial to get SpreadsheetGear working with invariant mode - we just had to remove an assumption that we would always be able to create an "en-US" CultureInfo. We now test against invariant-globalization mode for every hotfix.

Our customer asked for this because they wanted to run on a version of Linux which only supports invariant mode.

**Comment by tarekgh** [comment]
This is fixed now in .NET 9.0 through the PR https://github.com/dotnet/runtime/pull/107311. Please let me know if you have any more questions or asks. Thanks for reporting the issue.
