### ISSUE TITLE
Argument type mismatch error while running asp.net benchmark with net6.0.

### ISSUE THREAD

**Issue by Amaira29** [dotnet/runtime#106855]
### Description

I am getting argument type mismatch error while running asp.net benchmark with net6.0.

Failed Command:

dotnet publish Benchmarks.csproj -c Release -o C:\Users\mayadav1\AppData\Local\Temp\benchmarks-agent\benchmarks-server-19692\bfrcotie.wtx\src\Benchmarks\published /p:MicrosoftNETCoreAppPackageVersion=6.0.33 /p:MicrosoftAspNetCoreAppPackageVersion=6.0.33 /p:GenerateErrorForMissingTargetingPacks=false /p:RestoreNoCache=true /p:MicrosoftWindowsDesktopAppPackageVersion=6.0.33 /p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App --framework net6.0 --self-contained -r win-x64

Error:

C:\Users\mayadav1\AppData\Local\Temp\benchmarks-agent\benchmarks-server-19692\bfrcotie.wtx\src\Benchmarks\Middleware\JsonMiddleware.cs(37,109): error CS1503: Argument 3: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Benchmarks.Middleware.JsonMessage>' to 'System.Threading.CancellationToken' [C:\Users\mayadav1\AppData\Local\Temp\benchmarks-agent\benchmarks-server-19692\bfrcotie.wtx\src\Benchmarks\Benchmarks.csproj]

### Reproduction Steps

crank --config "C:\mk\Benchmarks\scenarios\json.benchmarks.yml" --config .\amd.benchmarks.yml --application.framework net6.0 --application.collectCounters true --application.startTimeout '00:15:00' --profile genoa --scenario https --session 1

### Expected behavior

It should execute. 

### Actual behavior

Error:
C:\Users\mayadav1\AppData\Local\Temp\benchmarks-agent\benchmarks-server-19692\bfrcotie.wtx\src\Benchmarks\Middleware\JsonMiddleware.cs(37,109): error CS1503: Argument 3: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<Benchmarks.Middleware.JsonMessage>' to 'System.Threading.CancellationToken' [C:\Users\mayadav1\AppData\Local\Temp\benchmarks-agent\benchmarks-server-19692\bfrcotie.wtx\src\Benchmarks\Benchmarks.csproj]

### Other information

Please help me in diagnosis of the same issue. Your help will be appreciated.

**Comment by eiriktsarpalis** [comment]
Seems like this should be moved to the benchmark repo?

**Comment by BrennanConroy** [comment]
Can't move issues across orgs.

You're trying to use 6.0 on a benchmark that we don't run on 6.0. And since 6.0 is about to go out of support it's not super interesting for us to fix it.

If you want to fix it yourself. You can just change JsonMiddleware.cs to not use the source generator.

**Comment by eiriktsarpalis** [comment]
Thanks. I'm going to close this assuming it's been answered, but feel free to continue the conversation here.
