### ISSUE TITLE
Last versions of preview like 1-7 don't work with Microsoft ML Benchmarks.

### ISSUE THREAD

**Issue by Amaira29** [dotnet/runtime#106856]
### Description

I am getting error while running Microsoft ML benchmarks with net8.0 preview 1.

Error logs:
Build succeeded in 0.8s
Restore complete (0.4s)
  Reporting succeeded (0.6s) → C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Reporting\Release\netstandard2.0\Reporting.dll
  BenchmarkDotNet.Extensions succeeded (0.7s) → C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\BenchmarkDotNet.Extensions\Release\netstandard2.0\BenchmarkDotNet.Extensions.dll
  Microsoft.ML.Benchmarks net8.0 succeeded (1.5s) → C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Microsoft.ML.Benchmarks\Release\net8.0\Microsoft.ML.Benchmarks.dll

Build succeeded in 3.4s
**You must install or update .NET to run this application.**

Available dotnet version on system:

dotnet --info
.NET SDK:
 Version:           9.0.100-preview.7.24407.12
 Commit:            d672b8a045
 Workload version:  9.0.100-manifests.a8e34f65
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Users\mayadav1\Desktop\ml\dotnet_root\sdk\9.0.100-preview.7.24407.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.7.24405.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.100-preview.1.23115.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\sdk]
  9.0.100-preview.7.24407.12 [C:\Users\mayadav1\Desktop\ml\dotnet_root\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.1.23112.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.1.23110.8 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.1.23112.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [C:\Users\mayadav1\Desktop\ml\dotnet_root]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS C:\Users\mayadav1\Desktop\ml>

Please help me in diagnosis the same issue . Please do the needful. 

### Reproduction Steps

1:
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(PERFLAB_TARGET_FRAMEWORKS)</TargetFrameworks>
    <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net8.0</TargetFrameworks>
  </PropertyGroup>
2:
dotnet build -c release

output :

Restore complete (0.7s)
  Reporting succeeded (0.7s) → C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Reporting\release\netstandard2.0\Reporting.dll
  BenchmarkDotNet.Extensions succeeded (0.7s) → C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\BenchmarkDotNet.Extensions\release\netstandard2.0\BenchmarkDotNet.Extensions.dll
  Microsoft.ML.Benchmarks net8.0 succeeded (1.6s) → C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Microsoft.ML.Benchmarks\release\net8.0\Microsoft.ML.Benchmarks.dll

Build succeeded in 4.2s
PS C:\Users\mayadav1\Desktop\ml\performance\src\benchmarks\real-world\Microsoft.ML.Benchmarks> notepad++ .\Microsoft.ML.Benchmarks.csproj

3:
after reaching to here performance\artifacts\bin\Microsoft.ML.Benchmarks\release\net8.0 .
 .\Microsoft.ML.Benchmarks.exe --filter *

output 

You must install or update .NET to run this application.

App: C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Microsoft.ML.Benchmarks\release\net8.0\Microsoft.ML.Benchmarks.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: C:\Users\mayadav1\Desktop\ml\dotnet_root

The following frameworks were found:
  8.0.0-preview.1.23110.8 at [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]
  9.0.0-preview.7.24405.7 at [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10

Available dotnet version on system:

PS C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Microsoft.ML.Benchmarks\release\net8.0> dotnet --info
.NET SDK:
 Version:           9.0.100-preview.7.24407.12
 Commit:            d672b8a045
 Workload version:  9.0.100-manifests.a8e34f65
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Users\mayadav1\Desktop\ml\dotnet_root\sdk\9.0.100-preview.7.24407.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.7.24405.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.100-preview.1.23115.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\sdk]
  9.0.100-preview.7.24407.12 [C:\Users\mayadav1\Desktop\ml\dotnet_root\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.1.23112.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.1.23110.8 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.1.23112.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [C:\Users\mayadav1\Desktop\ml\dotnet_root]

global.json file:
  C:\Users\mayadav1\Desktop\ml\performance\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Microsoft.ML.Benchmarks\release\net8.0>

### Expected behavior

It should work for me.

### Actual behavior

Error:

You must install or update .NET to run this application.

App: C:\Users\mayadav1\Desktop\ml\performance\artifacts\bin\Microsoft.ML.Benchmarks\release\net8.0\Microsoft.ML.Benchmarks.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: C:\Users\mayadav1\Desktop\ml\dotnet_root

The following frameworks were found:
  8.0.0-preview.1.23110.8 at [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]
  9.0.0-preview.7.24405.7 at [C:\Users\mayadav1\Desktop\ml\dotnet_root\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10

### Other information

Please help me in diagnosis the same issue.

**Comment by huoyaoyuan** [comment]
You need to install 8.0 **stable** versions. Previews are considered lower version than stable.

**Comment by Amaira29** [comment]
@huoyaoyuan , Any other way to use preview version ? I need to capture performance data of different preview versions .

Thanks @huoyaoyuan ,

**Comment by huoyaoyuan** [comment]
Options I can see to run **executables** on preview runtime:
- Use *8.0 preview SDK* to build the test. Executables built with SDK preview N should be able to run on runtime preview N and above.
- Target lower framework version (net7.0 or below), and enable `<RollForward>Major</RollForward>` to allow the executable to run on .NET 8.0.

----

Note that for benchmarks, framework to execute the **entry process** isn't the same with framework to execute the **benchmark**. You need to configure the [toolchains](https://benchmarkdotnet.org/articles/configs/toolchains.html#custom-dotnet-cli-path) used by BenchmarkDotNet.

**Comment by AndyAyersMS** [comment]
@Amaira29 out of curiosity, why are you trying to use .NET 8 preview 1 at this point? You should stall the official .NET 8 release (which I believe will uninstall the preview).

I can understand trying to see the perf of .NET 9 previews....
