### ISSUE TITLE
Timeout in runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#106890]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=785657
Build error leg or test failing: tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=785657
**Error message validated:** `[runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/23/2024 5:29:29 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by mdh1418** [comment]
No recent hits, and no stack trace/dump to investigate. Closing
