### ISSUE TITLE
Test failed: reliability framework test hang

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#106852]
# Description
The following lines are call stacks of test hang error. This error occurs in following cases:
1. DATAS-linux-normal(STRESS_DYNAMIC_HEAP_COUNT enabled)
2. DATAS-Windows-normal(STRESS_DYNAMIC_HEAP_COUNT enabled)
3. DATAS-Windows-finalization(STRESS_DYNAMIC_HEAP_COUNT enabled)

```
Child-SP          RetAddr               Call Site
00007ec3`a1ff9d90 00007f06`ba2e6340     libc_so!wait4+0x57
00007ec3`a1ff9dc0 00007f06`ba2e75e8     libcoreclr!PROCCreateCrashDump+0x410 [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/thread/process.cpp @ 2308]
00007ec3`a1ff9e30 00007f06`ba2e499d     libcoreclr!PROCCreateCrashDumpIfEnabled+0xad8 [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/thread/process.cpp @ 15732480]
00007ec3`a1ff9ed0 00007f06`ba288023     libcoreclr!PROCAbort+0x2d [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/thread/process.cpp @ 2559]
00007ec3`a1ff9ef0 00007f06`ba442050     libcoreclr!invoke_previous_action+0x223 [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/exception/signal.cpp @ 15732480]
00007ec3`a1ff9f40 00007f06`ba2ee711     libc_so!_sigaction+0x40
00007ec3`a1ffac08 00007f06`ba284b52     libcoreclr!DBG_DebugBreak+0x1 [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/arch/amd64/debugbreak.S @ 9]
00007ec3`a1ffac10 00007f06`ba29881b     libcoreclr!DebugBreak+0x2f2 [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/debug/debug.cpp @ 410]
00007ec3`a1ffacf0 00007f06`ba2a9abc     libcoreclr!CreateCurrentThreadData+0xab [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/init/sxs.cpp @ 48]
(Inline Function) --------`--------     libcoreclr!CorUnix::InternalGetCurrentThread+0x1b [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/include/pal/thread.hpp @ 677]
00007ec3`a1ffad10 00007f06`ba2848ec     libcoreclr!EnvironGetenv+0x2c [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/misc/environ.cpp @ 886]
(Inline Function) --------`--------     libcoreclr!DebugBreakCommand+0x11 [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/debug/debug.cpp @ 326]
00007ec3`a1ffad40 00007f06`ba2ea43b     libcoreclr!DebugBreak+0x8c [/home/vbibu/runtime-datas-validate/src/coreclr/pal/src/include/pal/dbgmsg.h @ 404]
00007ec3`a1ffae20 00007f06`ba48f134     libcoreclr!CorUnix::CPalThread::ThreadEntry+0x1ab [/usr/include/x86_64-linux-gnu/bits/stdint-intn.h @ 1759]
00007ec3`a1ffaee0 00007f06`ba50f7dc     libc_so!pthread_condattr_setpshared+0x4d4
00007ec3`a1ffaf80 ffffffff`ffffffff     libc_so!_xmknodat+0x23c
00007ec3`a1ffaf88 00000000`00000000     0xffffffff`ffffffff
```

# Occurrences
## DATAS-linux-normal
| Attributed Error | Count/Total(percentage%) | Dump Name | Log Name(Call Stacks of All Threads)  | Source File Path | Line Number
| :---------- | :---------: | :---------- | :---------- | :---------- | :---------: |
| Test hang | 2/10(20%) | stress_5.dmp | stress_5_callstack_allthreads.txt |  |  |
|  |  | stress_8.dmp | stress_8_callstack_allthreads.txt |  |  |

## DATAS-Windows-finalization
| Attributed Error | Count/Total(percentage%) | Dump Name | Log Name(Call Stacks of All Threads)  | Source File Path | Line Number
| :---------- | :---------: | :---------- | :---------- | :---------- | :---------: |
| Test hang | 1/5(20%) | stress_527c_2024-08-21_06-16-58-375_433c.dmp | stress_527c_2024-08-21_06-16-58-375_433c_callstack_allthreads.txt |  |  |

## DATAS-Windows-normal
| Attributed Error | Count/Total(percentage%) | Dump Name | Log Name(Call Stacks of All Threads)  | Source File Path | Line Number
| :---------- | :---------: | :---------- | :---------- | :---------- | :---------: |
| Test hang | 20/20(100%) | stress_09b0_2024-08-21_03-35-28-768_5bf4.dmp | stress_09b0_2024-08-21_03-35-28-768_5bf4_callstack_allthreads.txt |  |  |
|  |  | stress_0a90_2024-08-21_10-55-34-368_34dc.dmp | stress_0a90_2024-08-21_10-55-34-368_34dc_callstack_allthreads.txt |  |  |
|  |  | stress_11f0_2024-08-21_15-49-05-612_1fb8.dmp | stress_11f0_2024-08-21_15-49-05-612_1fb8_callstack_allthreads.txt |  |  |
|  |  | stress_1be4_2024-08-20_16-37-23-840_2ac4.dmp | stress_1be4_2024-08-20_16-37-23-840_2ac4_callstack_allthreads.txt |  |  |
|  |  | stress_1c10_2024-08-20_20-16-24-216_5f8c.dmp | stress_1c10_2024-08-20_20-16-24-216_5f8c_callstack_allthreads.txt |  |  |
|  |  | stress_26fc_2024-08-21_07-14-37-111_4940.dmp | stress_26fc_2024-08-21_07-14-37-111_4940_callstack_allthreads.txt |  |  |
|  |  | stress_2a48_2024-08-21_09-42-30-179_09ac.dmp | stress_2a48_2024-08-21_09-42-30-179_09ac_callstack_allthreads.txt |  |  |
|  |  | stress_2b7c_2024-08-21_01-09-25-234_3c28.dmp | stress_2b7c_2024-08-21_01-09-25-234_3c28_callstack_allthreads.txt |  |  |
|  |  | stress_2b80_2024-08-21_12-09-32-015_4f34.dmp | stress_2b80_2024-08-21_12-09-32-015_4f34_callstack_allthreads.txt |  |  |
|  |  | stress_2c94_2024-08-20_23-56-49-234_2f40.dmp | stress_2c94_2024-08-20_23-56-49-234_2f40_callstack_allthreads.txt |  |  |
|  |  | stress_3244_2024-08-21_13-22-37-492_2e64.dmp | stress_3244_2024-08-21_13-22-37-492_2e64_callstack_allthreads.txt |  |  |
|  |  | stress_393c_2024-08-21_04-48-02-997_4804.dmp | stress_393c_2024-08-21_04-48-02-997_4804_callstack_allthreads.txt |  |  |
|  |  | stress_3bcc_2024-08-21_08-27-45-511_2970.dmp | stress_3bcc_2024-08-21_08-27-45-511_2970_callstack_allthreads.txt |  |  |
|  |  | stress_4988_2024-08-21_06-01-27-115_4dbc.dmp | stress_4988_2024-08-21_06-01-27-115_4dbc_callstack_allthreads.txt |  |  |
|  |  | stress_4a88_2024-08-21_14-35-37-277_2b1c.dmp | stress_4a88_2024-08-21_14-35-37-277_2b1c_callstack_allthreads.txt |  |  |
|  |  | stress_4eb8_2024-08-20_17-50-38-737_46ec.dmp | stress_4eb8_2024-08-20_17-50-38-737_46ec_callstack_allthreads.txt |  |  |
|  |  | stress_552c_2024-08-20_21-30-09-510_0954.dmp | stress_552c_2024-08-20_21-30-09-510_0954_callstack_allthreads.txt |  |  |
|  |  | stress_5b7c_2024-08-20_22-43-33-633_0f04.dmp | stress_5b7c_2024-08-20_22-43-33-633_0f04_callstack_allthreads.txt |  |  |
|  |  | stress_5ddc_2024-08-21_02-22-34-143_32dc.dmp | stress_5ddc_2024-08-21_02-22-34-143_32dc_callstack_allthreads.txt |  |  |
|  |  | stress_5dec_2024-08-20_19-03-19-214_4cb8.dmp | stress_5dec_2024-08-20_19-03-19-214_4cb8_callstack_allthreads.txt |  |  |

**Comment by mrsharm** [comment]
@VincentBu, can we close these since we discerned that the hangs were really misconfigurations of the test end times?
