### ISSUE TITLE
Upgrade native brotli to version 1.0.10

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#106887]
We're using 1.0.9, released on August 2020: https://github.com/dotnet/runtime/blob/f402418aaed508c1d77e41b942e3978675183bfc/src/native/external/brotli-version.txt#L2

The latest is 1.0.10, released on August 2023: https://github.com/google/brotli/releases/tag/v1.1.0

**Comment by jkoritzinsky** [comment]
I have a branch for this

**Comment by carlossanlop** [comment]
We would like this in .NET 9 before we release it, and we should probably wait until after we have one servicing release of 9 before we backport it to 8.

cc @jkotas

**Comment by jkoritzinsky** [comment]
I was hoping to move our brotli consumption to the FetchContent model to provide a more streamlined experience for system vs local brotli.

I'll do a simple PR for .NET 10/9/8 that just does a source update with the existing methodology and do the FetchContent change later.
