### ISSUE TITLE
NET9 System.TimeSpan.FromSeconds(5) does not compile any more in mixed mode c++ cli with .NET9 preview 7 and VS 2022 17.12 preview due to ambigous type (either long long or double but not int directly)

### ISSUE THREAD

**Issue by mgexo** [dotnet/runtime#106935]
### Description

NET9 System.TimeSpan.FromSeconds(5) does not compile any more in mixed mode c++ cli with .NET9 preview 7 and VS 2022 17.12 preview due to ambigous type (either long long or double but not int directly)

This sounds related https://github.com/dotnet/runtime/issues/93890

### Reproduction Steps

Write System::TimeSpan::FromSeconds(5) into C++ CLI 
and you get this error with VS 2022 17.12 and NET9 preview 7 but it worked in all previous VS and .NET versions e.g. VS 17.10 with .NET 8 

You an type that line into a function of this small test project that I linked there https://github.com/dotnet/winforms/issues/11983#issuecomment-2308864145

```

1>TestClass1.cpp(11,20): error C2668: 'System::TimeSpan::FromSeconds': ambiguous call to overloaded function
1>    TestClass1.cpp(11,33):
1>    could be 'System::TimeSpan System::TimeSpan::FromSeconds(double)'
1>    TestClass1.cpp(11,33):
1>    or       'System::TimeSpan System::TimeSpan::FromSeconds(__int64,__int64,__int64)'
1>    TestClass1.cpp(11,33):
1>    or       'System::TimeSpan System::TimeSpan::FromSeconds(__int64)'
1>    TestClass1.cpp(11,20):
1>    while trying to match the argument list '(int)'
```

### Expected behavior

Simply accept the int

### Actual behavior

Doesnt accept int

### Regression?

probably a compiler regression

### Known Workarounds

Change all existing code to use double or long long (but unclear which one is best for previous .NET versions)

**Comment by mgexo** [comment]
It also affects System::TimeSpan::FromMilliseconds

**Comment by colejohnson66** [comment]
If you need compatibility with older dotnet versions, use the `double` overloads.

**Comment by tarekgh** [comment]
@tannergooding is correct in explaining the change and the suggested workaround. I am closing this as there is no action needed in the runtime. Feel free to send any question or request and we can try to help with.

**Comment by mgexo** [comment]
Ok thanks, we will use double then instead of integer. I just wanted to check if it was intentional / known
