### ISSUE TITLE
[API Proposal]: Having negative indices for indexing from the end and wrapping / circular indexing from a starting index

### ISSUE THREAD

**Issue by sirinath** [dotnet/runtime#106919]
### Background and motivation

It it more convenient at times to use negative numbers to index from last. This can be stored or computed as a regular `int` than a special type. Also the ability specify a starting index also would be extremely helpful in creating circular data structures. These might be able to benefit from intrinsic acceleration which a user rolled out version might not be able to get.

The existing `Index` also can support starting index.

Also a wrapped index can help return to 1st elements after wrapping.

### API Proposal

Create new corresponding methods to use -ve and circular / wrapped indices.

Arrays also can get the special indexing using a opt in. E.g. `a[1]` will be the current way. `a.Idx[-4]` and `a.Cir(3).Idx[-4]`. The mechanism and syntax can change.

### API Usage

```csharp
x.ElementAtIndex(-4); // - (Length + 1) to + Length
x.ElementAtIndex(3, -4); // 3 is the starting index. so the last index is 2, -4 retrieves in circular fashion
```

### Risks

Code explicitly designed to raise and catch exceptions due to negative indexing will fail. But this in most part will be a bug and rarely if it is valid, it will be very bad design. 

For this new methods can be introduced with this behaviour.

**Comment by huoyaoyuan** [comment]
I believe using negative index is less intuitive, and may cause hidden bug when index calculation overflows.

Instead, the existing `Index` overloads work just fine.

**Comment by sirinath** [comment]
@huoyaoyuan What I am proposing is to use different method names so it does not clash with the current scheme. If they use thee new methods, then they should know how it works. No change to existing methods.

The complexity of the index mapping is handled by C# so the chances of errors are reduced.

**Comment by colejohnson66** [comment]
But why should dotnet add/support `myArray.ElementAtIndex(-1)`, when `myArray[^1]` already exists and works just fine.

**Comment by hez2010** [comment]
Also note that in .NET we already supported non-zero and negative indices, such array can be created with reflection APIs.

**Comment by sirinath** [comment]
> But why should dotnet add/support `myArray.ElementAtIndex(-1)`, when `myArray[^1]` already exists and works just fine?

Yes. But it uses `Index`

**Comment by colejohnson66** [comment]
What is wrong with `Index`?

**Comment by Joe4evr** [comment]
Even without an `Index` overload, the compiler still allows using the index syntax when the object has either a `.Length` or `.Count` property available.

**Comment by eiriktsarpalis** [comment]
The platform already uses `System.Index` expressions to achieve this, I don't see a benefit in replicating this functionality in a nonstandard way.
