### ISSUE TITLE
Codify that String.Create can write over the string's null terminator

### ISSUE THREAD

**Issue by PJB3005** [dotnet/runtime#106903]
I am trying to use a native API (specifically, DirectWrite) that gives me a wide string back by writing it to a memory buffer. This would be a perfect use case for `String.Create`, except for one small problem: the API also tries to write the null terminator.

This means that if I allocate a string of the correct size, the span given to `string.Create` will be one char too small to pass to the API in question. Knowing the implementation of `String.Create` I could simply do "`span.Length + 1`" to get the space of the null terminator at the end of the string, but this is obviously no API guarantee and might break in the future.

If it would be possible to codify that this is safe to do, that would allow me to interop (ever so slightly) more efficiently with APIs like DirectWrite, which would be nice to have. 

An alternative design could be to make an alternative to `String.Create` that gives a span that includes the null terminator, and the user is expected (possibly enforced?) to make sure the last char is a null terminator when the callback exits.

**Comment by tannergooding** [comment]
This one is a request for documenting a particular behavior of an existing API and so may fall under the category of things we want to talk about more in depth in API review.

The implementation we have today is that the span directly wraps the memory allocated for the `string` instance and so does indeed have space for a null-terminator immediately after the span. Naturally we don't necessarily want to guarantee that the `span` directly wraps the memory allocated for the string instance (we may want to allow an intermediate buffer to be used, etc), but guaranteeing the intermediate buffer is at least `span.Length + 1` big does seem reasonable and would allow its usage for such interop scenarios.

I think in such a scenario we would say in the API `remarks` section that the buffer space exists, but its contents will be ignored (as we will always overwrite it with the null-terminator before `string.Create` returns).

Thoughts? CC. @dotnet/fxdc

**Comment by terrajobst** [comment]
Is there any downside to codifying this?

Practically, string already guarantees that it's both a BSTR as well as UTF16 C-style string (depending on how you get the address). It doesn't seem that's something we can change any time soon.

**Comment by jkotas** [comment]
We have codified similar invariant for UTF8 string literals where we guarantee that the `ReadOnlySpan<byte>` has an extra null at the end that is not included in the span.

I think the main downside is that these contracts are weird. We are codifying buffer overruns.

**Comment by jkotas** [comment]
> string already guarantees that it's both a BSTR

Nit: System.String is not a BSTR. System.String<->BSTR marshalling has to always create a copy.

**Comment by tannergooding** [comment]
> I think the main downside is that these contracts are weird. We are codifying buffer overruns.

👍 

It's definitely an odd thing, but is likely safe in isolation. `System.String` similarly guarantees that it is null-terminated, but does not include that null-terminator for the purposes of `Length`, but this is strictly relied upon for interop purposes.

So I think this is more just about guaranteeing that for the purposes of `string.Create`, the span passed to the callback can similarly be safely passed into native for interop purposes (and does not include said null-terminator in its length) so that native functions can do the optimal thing.

**Comment by GrabYourPitchforks** [comment]
It's also stating that if the string contents go riiiiight up to a page boundary, we're guaranteeing that the adjoining page containing the null terminator is writable. I don't see why that would ever not be the case (maybe some optimization somewhere?), but it's certainly not a guarantee we have ever made before.

Assuming the runtime team is willing to make this guarantee, we'd probably need to couch it in terms like "your app needs to target net10 or higher for this guarantee to be ironclad." Which kinda implies you'd want a new API for it so that downlevel apps can't call it.

**Comment by tannergooding** [comment]
> It's also stating that if the string contents go riiiiight up to a page boundary, we're guaranteeing that the adjoining page containing the null terminator is writable.

I'm not aware of any memory allocator that would work like this. It would end up as very problematic (and expensive) behavior to have such a setup and manage the state where part of an allocation is in immutable memory but the rest of an allocation is writeable.

We can already trivially guarantee this behavior for all shipped versions of .NET and it is highly unlikely we would ever consider such a change in the future as there would be no way to make it pay for play. An allocation is either all writeable or all readable. A user could only get a mix if they unsafely modified the page protections manually, which would be undefined behavior.

**Comment by jkotas** [comment]
I do not see a problem with guaranteeing it for existing runtimes that shipped this API as well as going forward.

I see the main problem in subtle nature of the codified buffer overruns and making sure that people understand the specific cases where it is ok to depend on them.

**Comment by terrajobst** [comment]
* We're good at guaranteeing that the span points to memory that has space for a least one more element than the span
* We'd guarantee that the span points to zero'd memory, including the null terminator.
* Our docs would say that if you write to the extra location it must be a null terminator. Writing anything else will result corrupting the string and thus is undefined behavior.
