### ISSUE TITLE
New Rules for `Lock` class usage and to avoid public usage of `lock (this)`

### ISSUE THREAD

**Issue by elachlan** [dotnet/runtime#106907]
### Describe the problem you are trying to solve
In C#13 there is a new `system.threading.lock` class (https://github.com/dotnet/csharplang/issues/7104). It may be more performant to use over a standard object lock. An analyzer that identifies object properties which are exclusively used for locking and suggests using the new Lock class instead, with a code fix.

Additionally, it would be nice to have a rule that identifies usages of `lock (this)` inside public classes to discourage the practice.

### Additional context

References:
- https://github.com/dotnet/runtime/issues/34812
- https://github.com/dotnet/csharplang/issues/7104
- https://learn.microsoft.com/en-us/dotnet/api/system.threading.lock?view=net-9.0

**Comment by CyrusNajmabadi** [comment]
Roslyn already added an analyzer for this: https://github.com/dotnet/roslyn/pull/74170

Source: me :-)

**Comment by elachlan** [comment]
@CyrusNajmabadi that just leaves the usage of `lock(this)` on public apis.

**Comment by CyrusNajmabadi** [comment]
That seems entirely different and unrelated to c#13 or the new Lock type.

**Comment by buyaa-n** [comment]
> that just leaves the usage of `lock(this)` on public apis.

@elachlan closed the issue as it was resolved, feel free to open new issue for this or update the description and reopen this

**Comment by elachlan** [comment]
@buyaa-n thanks, I have created a new issue at https://github.com/dotnet/runtime/issues/107269
