### ISSUE TITLE
Analyzer 'Microsoft.Interop.Analyzers.CustomMarshallerAttributeAnalyzer' threw an exception of type 'System.InvalidProgramException

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#106904]
### Analyzer

**Diagnostic ID**: AD0001

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis) 

**Version**: 9.0.100-preview.7.24380.2

### Describe the bug

When building the .NET 9 Preview 7 tag using the VMR on RHEL 9 on arm64, I got this error:

```
CSC : error AD0001: Analyzer 'Microsoft.Interop.Analyzers.CustomMarshallerAttributeAnalyzer' threw an exception of type 'Syst       em.InvalidProgramException' with message 'Common Language Runtime detected an invalid program.'. [/builddir/build/BUILD/dotnet-v9.0.0-preview.7.24405.7-x64-bootstrap/src/sdk/src/BlazorWasmSdk/Tasks/Microsoft.NET.Sdk.BlazorWebAssembly.Tasks.csproj::TargetFramework=net9.0]
```

This seems to be a random error. It doesn't happen on all arm64 platforms, or on all builds.

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. git clone https://github.com/dotnet/dotnet
2. git checkout v9.0.0-preview.7.24405.7
3. ./prep-source-build.sh
4. ./build.sh --source-only  /p:OfficialBuilder=CentOS /p:MinimalConsoleLogOutput=false /p:ContinueOnPrebuiltBaselineError=true /v:n /p:LogVerbosity=n
5. Get this error, randomly

### Expected behavior

The VMR builds, just like it does most of the time

### Actual behavior

This error makes the VMR build fail

**Comment by jkoritzinsky** [comment]
There's no reason for the analyzer to be throwing an InvalidProgramException as it's just regular C#. 

I wouldn't be surprised if the underlying issue for https://github.com/dotnet/dnceng/issues/3305 was related.

**Comment by agocke** [comment]
Agreed, marking this as dup of https://github.com/dotnet/dnceng/issues/3305
