### ISSUE TITLE
IndexOutOfRangeException thrown by NullabilityInfoContext.Create(PropertyInfo)

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#107033]
### Description

We received a bug report in Swashbuckle.AspNetCore that some code using `NullabilityInfoContext.Create(PropertyInfo)` was throwing an `IndexOutOfRangeException`: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3051

From debugging https://github.com/ARKlab/Ark.Tools/pull/221/commits/8c747682219ef6f863b8dd5cfa9d68d4edbabb0d in Visual Studio with Just My Code disabled, the exception appears to be coming from here: https://github.com/dotnet/runtime/blob/493a702b5ce0ac3c98cea5797f74e34e87c2ce26/src/libraries/System.Private.CoreLib/src/System/Reflection/NullabilityInfoContext.cs#L203

For some reason I don't understand, the setter appears to have no parameters, so the index goes out of bounds as the code tries to index element -1.

The property that causes the issue is [this one](https://github.com/ARKlab/Ark.Tools/blob/289bc77c9bcf21a62c9ee6702f8c614ebf188515/Samples/WebApplicationDemo/Dto/Person.cs#L36).

See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3051#issuecomment-2312546973.

The same issue seems to exist in main despite some refactoring:

https://github.com/dotnet/runtime/blob/ef0c712f1ffcc48da481e44fb2981bf4de191eac/src/libraries/System.Private.CoreLib/src/System/Reflection/NullabilityInfoContext.cs#L220

### Reproduction Steps

I don't have a _minimal_ repro as trying to do simple reflection on a type of the same shape in a console app doesn't throw - I'm not sure what the specific trigger is to break things. However the original non-minimal repro demonstrates the issue.

1. Clone and checkout https://github.com/ARKlab/Ark.Tools/pull/221/commits/8c747682219ef6f863b8dd5cfa9d68d4edbabb0d
2. `cd Ark.Tools\Samples\TestProject`
3. `dotnet test`

A test will fail due to an HTTP 500 error, which is caused by the `IndexOutOfRangeException` inside the test server.

### Expected behavior

The nullability of the given property is correctly reported and no exception is thrown.

### Actual behavior

An `IndexOutOfRangeException` is thrown.

### Regression?

Unknown.

### Known Workarounds

None.

### Configuration

.NET SDK 8.0.401.

**Comment by jkotas** [comment]
`RuntimePropertyInfo` is from a module that was emitted using Reflection.Emit at runtime.

This dynamically emitted property setter method does not have any arguments and that's why you seeing the `IndexOutOfRangeException`. The method name is `WebApplicationDemo.Dto.Person.set_Email()`

**Comment by buyaa-n** [comment]
> `RuntimePropertyInfo` is from a module that was emitted using Reflection.Emit at runtime.
> 
> This dynamically emitted property setter method does not have any arguments and that's why you are seeing the `IndexOutOfRangeException`. The method name is `WebApplicationDemo.Dto.Person.set_Email()`

Interesting, apparently we should not expect setter will always have a parameter

**Comment by steveharter** [comment]
I was able to repro locally.

The code to generate the class [looks correct](https://github.com/ARKlab/Ark.Tools/blob/b96d572cc0e613c56c62a457d70cb43acc1bce4d/Ark.Tools.Core/Reflection/DynamicTypeAssembly.cs#L103-L114) but when reflecting on the type's properties ([Person](https://github.com/ARKlab/Ark.Tools/blob/b96d572cc0e613c56c62a457d70cb43acc1bce4d/Samples/WebApplicationDemo/Dto/Person.cs#L8)) in the dynamic assembly, the MethodInfo for each of them (not just Email) GetSetMethod return a method with 0 arguments and a return type of the property type, so the setter method basically looks like the getter method.

Somehow the dynamically assembly is getting corrupted.

**Comment by AndreaCuneo** [comment]
@steveharter I think the generated code, the culprit, is actually in the asp-versioning project and the signature of the setter is indeed incorrect there as described in the issue below.

https://github.com/dotnet/aspnet-api-versioning/issues/1104

I've opened a PR to fix the generator there.

Although it demonstrates that it is possible to generate an incorrect 'setter' via IL.

It may would be worth it to improve the NullabilityInfoContext to check for array length without assuming it to be equal to 1.

**Comment by steveharter** [comment]
I see - so the link I provided for the [generation](https://github.com/ARKlab/Ark.Tools/blob/b96d572cc0e613c56c62a457d70cb43acc1bce4d/Ark.Tools.Core/Reflection/DynamicTypeAssembly.cs#L103-L114) is not the actual generator code that was run and the bug [is here](https://github.com/dotnet/aspnet-api-versioning/blob/3fc071913dcded23eeb5ebe55bca44f3828488bf/src/Common/src/Common.OData.ApiExplorer/OData/DefaultModelTypeBuilder.cs#L420).

> It may would be worth it to improve the NullabilityInfoContext to check for array length without assuming it to be equal to 1.

I think in this case that is not valid IL, so we wouldn't protect against it. That code should work however with properties that are indexers which can have an extra argument for the indexer (or even with properties with more than one extra argument although C# doesn't have support for that).
