### ISSUE TITLE
Audit OOB packages for trimming

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#107111]
We scan the entire shared framework for trim warnings, but some stuff (like System.Memory.Data) seems to have been missed by the scans. We should ensure everything in dotnet/runtime is trimmable.

**Comment by eerhardt** [comment]
> (like System.Memory.Data)

This assembly was taken care of with https://github.com/dotnet/runtime/pull/54980 and https://github.com/dotnet/runtime/pull/69012.

I _think_ this issue is a duplicate of https://github.com/dotnet/runtime/issues/75480.

**Comment by agocke** [comment]
Great! I will close this in favor of https://github.com/dotnet/runtime/issues/75480
