### ISSUE TITLE
`UnsafeAccessorAttribute` doesn't work with generic classes that have any constraint on generic type argument

### ISSUE THREAD

**Issue by stefanomerotta** [dotnet/runtime#107132]
### Description

If you create an generic accessor, like described in the updated docs, that refers to a generic class that have any constraint on generic type argument it throws an `InvalidProgramException` with the message `Generic type constraint do not match`.

### Reproduction Steps

```cs
using System.Runtime.CompilerServices;

var t = new Class<Argument>();
Accessor<Argument>.UnsafeMethod(t, 10);

public interface IInterface 
{ }

public class Argument : IInterface
{ }

public class Class<T> where T : IInterface
{
    private void Method(int value) { }
}

public static class Accessor<T>
    where T : IInterface
{
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "Method")]
    public static extern void UnsafeMethod(Class<T> @this, int value);
}
```

### Expected behavior

The type constraint on `Accessor<T>` matches the type constraint of the referred class `Class<T>` so the code should run fine and invoke the method.

### Actual behavior

The runtime throws an `InvalidProgramException` with the message `Generic type constraint do not match`.

### Regression?

In .NET8 you can implements a non generic accessor with closed generic and it worked as expected.
This implementation doesn't work anymore in .NET9 because of the new generic signature requirement.

```cs
using System.Runtime.CompilerServices;

var t = new Class<Argument>();
Accessor.UnsafeMethod(t, 10);

public interface IInterface 
{ }

public class Argument : IInterface
{ }

public class Class<T> where T : IInterface
{
    private void Method(int value) { }
}

public static class Accessor
{
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "Method")]
    public static extern void UnsafeMethod(Class<Argument> @this, int value);
}
```

### Configuration

- .NET version: 9.0.0-preview.7.24405.7
- O.S.: Windows 10 22H2 (OS build 19045.4780)
- Architecture: x64 (11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz)

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Doh! I tested all the complex constraints on methods but not on types... immense fail. I have a fix and will port to .NET 9.

Thanks for reporting this @stefanomerotta!

**Comment by AaronRobinsonMSFT** [comment]
Will also be fixed in https://github.com/dotnet/runtime/pull/107160.

**Comment by AaronRobinsonMSFT** [comment]
> that refers to a generic class that have any constraint on generic type argument

Also, this isn't strictly true. The issue here is the precise type in the constraint. The following would work as expected.

```csharp
public class Class<T, U> where T : U
{
    private void Method(int value) { }
}
```
