### ISSUE TITLE
[StructLayout(LayoutKind.Sequential)] causes "Could not load type because the format is invalid" error in derived class on coreclr

### ISSUE THREAD

**Issue by Liangjia0411** [dotnet/runtime#107192]
**Steps to Reproduce:**
1. Define a base class without `[StructLayout(LayoutKind.Sequential)]`.
2. Define a derived class with `[StructLayout(LayoutKind.Sequential)]`.
3. Attempt to get the type of derived class on coreclr.

**Code**
```c#

class TempClassA
{ }

[StructLayout(LayoutKind.Sequential)]
class TempClassB : TempClassA
{ }

class Program
{
    public static void Main()
    {
        try
        {
            var type = typeof(TempClassB);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}
```

**Expected Behavior:**
The derived class should load without errors.

**Actual Behavior:**
The derived class throws an error: `Could not load type because the format is invalid.`

**Environment:**
- .NET Runtime version: 8.0.7
- Platform: Windows (other platforms not tested)

**Additional Information:**
This issue does not occur on mono, only on coreclr.

**Comment by huoyaoyuan** [comment]
According to ECMA-335, II.22.8:

> Layout cannot begin part way down the chain.  But it is valid to stop “having layout” at any point down 
the chain. 

![image](https://github.com/user-attachments/assets/f1e7b626-4e1f-4118-bf13-9f80a7c15ab7)

This falls into the H-I scenario and specified as invalid. The behavior of mono is incompliant in this case.

**Comment by Liangjia0411** [comment]
thanks
