### ISSUE TITLE
Inefficient code gen when switching from direct array to Span<T> or Memory<T>

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#107181]
### Description
We are currently trying to optimize our code and with the introduction of `Memory<T>` and `Span<T>` it seemed to be a good time to unify certain operations.

What we currently have is an `Image2D<T>`

```
    public readonly struct Image2D<T>    
    {
        private readonly T[] _data;
        public int SizeX { get; }
        public int SizeY { get; }

        public T this[int idx]
            => _data[idx];

        public Image2D(T[] data, int sizeX, int sizeY)
        {
            _data = data;
            SizeX = sizeX;
            SizeY = sizeY;
        }
    }
```

where thew access to the indexer boils down to a very primitve statement in the JIT asm (in release)

```
    L0000: mov eax, [ecx]
    L0002: cmp edx, [eax+4]
    L0005: jae short L000c
    L0007: mov eax, [eax+edx*4+8]
    L000b: ret
    L000c: call 0x71f92020
    L0011: int3
```

We are now trying to move to `Memory<T>` because it would open use the possibilty to also work with unmanaged memory.
Doing so would make the struct look like:

```
  public readonly struct Image2D<T>    
    {
        private readonly Memory<T> _data;
        public int SizeX { get; }
        public int SizeY { get; }

        public T this[int idx]
            => _data.Span[idx];

        public Image2D(T[] data, int sizeX, int sizeY)
        {
            _data = data;
            SizeX = sizeX;
            SizeY = sizeY;
        }
    }
```

Doing this generates this JIT Asm code (in release)

```
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: push edi
    L0004: push esi
    L0005: push ebx
    L0006: sub esp, 8
    L0009: xor eax, eax
    L000b: mov [ebp-0x14], eax
    L000e: mov [ebp-0x10], eax
    L0011: mov esi, edx
    L0013: lea edi, [ecx+8]
    L0016: xor ebx, ebx
    L0018: xor eax, eax
    L001a: mov ecx, [edi]
    L001c: test ecx, ecx
    L001e: je short L004b
    L0020: mov eax, [ecx]
    L0022: test dword ptr [eax], 0x80000000
    L0028: je short L005a
    L002a: lea ebx, [ecx+8]
    L002d: mov eax, [ecx+4]
    L0030: mov edx, [edi+4]
    L0033: and edx, 0x7fffffff
    L0039: mov ecx, [edi+8]
    L003c: cmp edx, eax
    L003e: ja short L006d
    L0040: sub eax, edx
    L0042: cmp eax, ecx
    L0044: jb short L006d
    L0046: lea ebx, [ebx+edx*4]
    L0049: mov eax, ecx
    L004b: cmp esi, eax
    L004d: jae short L0074
    L004f: mov eax, [ebx+esi*4]
    L0052: lea esp, [ebp-0xc]
    L0055: pop ebx
    L0056: pop esi
    L0057: pop edi
    L0058: pop ebp
    L0059: ret
    L005a: lea edx, [ebp-0x14]
    L005d: mov eax, [ecx]
    L005f: mov eax, [eax+0x28]
    L0062: call dword ptr [eax+0x14]
    L0065: mov ebx, [ebp-0x14]
    L0068: mov eax, [ebp-0x10]
    L006b: jmp short L0030
    L006d: call dword ptr [0xaaeefe8]
    L0073: int3
    L0074: call 0x71f92020
    L0079: int3
```

I provided an example that shows using the direct array indexer access, one with Memory.Span and one with Span:
https://gist.github.com/msedi/f09db39d33540f925a38b4d5f6bd6c4d

It seems the jitter is not able to optimize the access. We try to do further benchmarks, but it seems using Memory<T> or Span<T> introduces problems that we don't want to have ;-)

### Configuration
.NET8 / Windows 11

### Analysis
We will do further analysis, but looking at the code it is already visible that the are much more ASM operations.

**Comment by msedi** [comment]
@jakobbotsch. Thanks for the answer. This is what I also saw before in the code you referenced. I was hoping the Memory<T> is a more lightweight structure and the fear now is when introducing Memor<T> instead of arrays would slow down things.

In general this mean, though that Memory<T> should be used in performance critical situations, right?

**Comment by Suchiman** [comment]
When `_data` is expected to be large or is always on the managed heap, then there's not really a point in switching away from array anyway. You can still write your code using Span then, array implicitly converts to Span and that operation is a lot cheaper than `Memory.Span`, not free but almost so. Depending on how `Image2D<T>` gets used, you might also be able to convert that to a `ref struct`, then you can store `Span<T>` directly inside as a field, which then allows you to construct that `Image2D<T>` from stack allocated data for example as well.

**Comment by tannergooding** [comment]
In general `Memory<T>` is meant to be a storage mechanism that allows abstracting between `T[]`, `T*`, and other potential data storage mechanisms (like `string` or broader scenarios via `IMemoryOwner`)

To actually work with the data, you want to get the `memory.Span` as soon as possible and then simply use `Span<T>` from that point on, until the general control flow or context requirements (like async) no longer allows `Span` to be passed around.

**Comment by msedi** [comment]
@tannergooding @Suchiman @jakobbotsch: Thanks for your answers. I think thats the deal. We have removed the indexer, we already had a Span<T> there, the indexer was mostly for convience to make a higher level structure look like an array. I was maybe expecting a bit too much and in the end that's maybe the better approach.

**Comment by msedi** [comment]
> When `_data` is expected to be large or is always on the managed heap

we need to go to different types of memories (CUDA and unmanaged, also memory from memory-mapped-files). The Array1D and also Array2D/3D are wrappers around this memory variaties.

> The ref struct is problem because we need no transport the object (and the memory) through a processing chain. If its a ref struct I would have to copy data to make it transportable again.

> stackalloc
That would be good, in most cases the size is to high for stackallocs. Each image can have 2-4MB.
