### ISSUE TITLE
Docker : OpenSslCryptographicException: error:0A000410:SSL routines::sslv3 alert handshake failure

### ISSUE THREAD

**Issue by 1KOD** [dotnet/runtime#107172]
I have left no method untried for this problem but to no avail.

### A Simple Line of Code
```
var httpClient = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Post, "https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsesya");
await httpClient.SendAsync(request);
```

Screen Recording

![devenv_Ogvnx4QAw7](https://github.com/user-attachments/assets/f4443d75-7eae-4b42-90c0-f4bac59931c6)

My program is going live and I need urgent help. Thanks to everyone in advance.

**Comment by rzikm** [comment]
This seems to be the same issue as in https://github.com/dotnet/runtime/issues/98797

The server supports only weak RSA key exchange, see e.g. SSL Labs https://www.ssllabs.com/ssltest/analyze.html?d=servis.turkiye.gov.tr

![image](https://github.com/user-attachments/assets/48e5f0ca-1841-46dd-a329-a199c5390242)

In the `aspnet:8.0` Docker image, no explicit default for cipher suites is configured in `/etc/ssl/openssl.cnf`, therefore, .NET applies a rather opinionated strict default which only allows ECDHE key exchange, so client and server have no common cipher suite to communicate with.

You can workaround this by either

copy config from `aspnet:7.0` (where the default config explicitly specifies some chiphers) by adding this to the Dockerfile

    COPY --from=mcr.microsoft.com/dotnet/aspnet:7.0 /etc/ssl/openssl.cnf /etc/ssl/openssl.cnf

Or modify the openssl.cnf, following addition should make it work

```
[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT@SECLEVEL=2
```

**Comment by qryazilim** [comment]
Thank you very much, it helped me.

**Comment by qryazilim** [comment]
> This seems to be the same issue as in #98797
> 
> The server supports only weak RSA key exchange, see e.g. SSL Labs https://www.ssllabs.com/ssltest/analyze.html?d=servis.turkiye.gov.tr
> 
> ![image](https://private-user-images.githubusercontent.com/32671551/363095804-48e5f0ca-1841-46dd-a329-a199c5390242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTQ5NzAsIm5iZiI6MTcyNTAxNDY3MCwicGF0aCI6Ii8zMjY3MTU1MS8zNjMwOTU4MDQtNDhlNWYwY2EtMTg0MS00NmRkLWEzMjktYTE5OWM1MzkwMjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYWQxYTZlYTE0N2VhNGY4OTJjNzg3ZjIxODEzZjhmNWRlNDkxNzU3NmMxNzE5YTNlMjgwOGMwYjUwYmEwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6XipO8tkxcylHvX9ZLAbAZDVxcdLdCHQFk-R0fcINlM)
> 
> In the `aspnet:8.0` Docker image, no explicit default for cipher suites is configured in `/etc/ssl/openssl.cnf`, therefore, .NET applies a rather opinionated strict default which only allows ECDHE key exchange, so client and server have no common cipher suite to communicate with.
> 
> You can workaround this by either
> 
> copy config from `aspnet:7.0` (where the default config explicitly specifies some chiphers) by adding this to the Dockerfile
> 
> ```
> COPY --from=mcr.microsoft.com/dotnet/aspnet:7.0 /etc/ssl/openssl.cnf /etc/ssl/openssl.cnf
> ```
> 
> Or modify the openssl.cnf, following addition should make it work
> 
> ```
> [openssl_init]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> CipherString = DEFAULT@SECLEVEL=2
> ```

Thank you very much, it helped me.

**Comment by 1KOD** [comment]
> This seems to be the same issue as in #98797
> 
> The server supports only weak RSA key exchange, see e.g. SSL Labs https://www.ssllabs.com/ssltest/analyze.html?d=servis.turkiye.gov.tr
> 
> ![image](https://private-user-images.githubusercontent.com/32671551/363095804-48e5f0ca-1841-46dd-a329-a199c5390242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTcxNjAsIm5iZiI6MTcyNTAxNjg2MCwicGF0aCI6Ii8zMjY3MTU1MS8zNjMwOTU4MDQtNDhlNWYwY2EtMTg0MS00NmRkLWEzMjktYTE5OWM1MzkwMjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDExMjEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGU5NTRmY2YwZDc3YjQ0ZWMxZTI3ZTU5YmRjYmQ0ZGRmNDBmOGUyMzExNTk3NGRjMmEwZDVkZmE2NWMxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OWL6PturOe6hvc9mh3383KGVreUO8K4ureONGK2tsaA)
> 
> In the `aspnet:8.0` Docker image, no explicit default for cipher suites is configured in `/etc/ssl/openssl.cnf`, therefore, .NET applies a rather opinionated strict default which only allows ECDHE key exchange, so client and server have no common cipher suite to communicate with.
> 
> You can workaround this by either
> 
> copy config from `aspnet:7.0` (where the default config explicitly specifies some chiphers) by adding this to the Dockerfile
> 
> ```
> COPY --from=mcr.microsoft.com/dotnet/aspnet:7.0 /etc/ssl/openssl.cnf /etc/ssl/openssl.cnf
> ```
> 
> Or modify the openssl.cnf, following addition should make it work
> 
> ```
> [openssl_init]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> CipherString = DEFAULT@SECLEVEL=2
> ```

Thank you very much, it helped me.
