### ISSUE TITLE
DispatchProxy generates methods for final interface methods

### ISSUE THREAD

**Issue by tinmanjk** [dotnet/runtime#107287]
### Description

Since there is very little documentation on the actual methods generated by DispatchProxy I've decided to read the code and came across this [code](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs#L340C1-L343C34):

```
// Skip regular/non-virtual instance methods, static methods, and methods that cannot be overridden
// ("methods that cannot be overridden" includes default implementation of other interface methods).
if (!mi.IsVirtual || mi.IsFinal)
    continue;
```

which was added in the commit for [Add support for default interface methods in DispatchProxy ](https://github.com/dotnet/runtime/commit/4a9113d93067f9e0e0e91a8b8df5ca323dcf8f2f)

### Reproduction Steps

// ("methods that cannot be overridden" includes default implementation of other interface methods).

This is a default implementation of other interface methods:

interface IBase {
    public void DefaultImpl();
}
interface IDerived : IBase {

    //private final hidebysig virtual instance void
    void IBase.DefaultImpl() {
        Console.WriteLine("IDerived DefaultImpl");
    }
}

class D : DispatchProxy {
    protected override object Invoke(MethodInfo targetMethod, object[] args) {
        Console.WriteLine("In Invoke");
        return null;
    }
}

var proxy = DispatchProxy.Create<IDerived, D>();
proxy.DefaultImpl(); // "In Invoke"

### Expected behavior

I would expect that the "final" method is not being able to be stubbed. 

### Actual behavior

It is successfully stubbed and we get inside `DispatchProxy's Invoke`.

### Other information

Now this is due to the very confusing imo combo of `virtual `AND `final` that is emitted for such default implementations. 

Is the code above not aware of how flags are set? Alternatively if is, what is an example of it passing, i.e. being non-virtual AND final?

**Comment by steveharter** [comment]
I assume this is not causing any issues, just a question.

I believe the intent of the "methods that cannot be overridden" comment is to prevent invalid IL that will throw exceptions either with the generated proxy type is created or later at runtime. Since it is possible to replace a DIM method in a class that implements the DIM, I don't see a reason to restrict the proxy generator.

As for why the `final` modifier is added to the DIM method, I'm not sure but suspect it has to do with making it clear that a derived class can't use the `overrides` modifier against a DIM method.

**Comment by tinmanjk** [comment]
This is the bug - it does **NOT** skip the default interface implementation of other interface methods - which are supposed to be "final".

**Comment by tinmanjk** [comment]
Thanks for the reply.

I think the intent of the code is just to get the _declared_ "normal" interface methods only - which are marked as virtual in the metadata.

The IsFinal is to disregard the virtual ones which are EIMIs of other interface methods which we will get anyway as MethodInfos.
