### ISSUE TITLE
Is possible to attach running process which single-file published, with the Visual Studio debugger?

### ISSUE THREAD

**Issue by tp1415926535** [dotnet/runtime#107245]
### Description

I was hoping to debug a single-file publish program by attaching a process (because of I actually need to debug it remotely), but found that it doesn't work. 
Once cancel the `Produce single file` option to publish, debugger works fine.

I've searched some related issues, like [issue#42927](https://github.com/dotnet/runtime/issues/42927) and [issue#84428](https://github.com/dotnet/runtime/issues/84428) , but seems that it's haven't been solved.

### Reproduction Steps

1. Create new Console application. (.Net 6 or 7 or 8)
2. Write code:
``` csharp
while (true)
{
    Console.WriteLine(DateTime.Now);
    await Task.Delay(1000);
}
```
3. Publish with single-file mode (.pubxml file `<PublishSingleFile>true</PublishSingleFile>`)
4. run `ConsoleApp.exe` in publish folder
5. Add breakpoint.
6. VS menu → Debug → Attach to Process... → choose `ConsoleApp.exe` process → Attach

### Expected behavior

Hitting breakpoints

### Actual behavior

The breakpoint show tooltip: `The breakpoint will not currently be hit. No symbols have been loaded for this document`. And the debug Modules window show `ConsoleApp.exe` Symbol Status `Cannot find or open the PDB file`

**Comment by vitek-karas** [comment]
Please make sure the debugger type is set to .NET (Core). The behavior you describe would happen if the debugger is attached as a native debugger only.

**Comment by tp1415926535** [comment]
> Please make sure the debugger type is set to .NET (Core). The behavior you describe would happen if the debugger is attached as a native debugger only.
    

Where can I set the debugger type when I use "Attach to Process..." in source code project? It seems that project properties can only be set when using an exe file as a project.

**Comment by tp1415926535** [comment]
> There's an option for it in the Attach dialog in VS.

Ok, I'm using VS2022  version 17.9.7 and found it in the `Select` option which right of `Attach To` in the center of dialog.
I didn't open this setting before, because I didn't realise it would be renamed. Thanks.
![image](https://github.com/user-attachments/assets/0824b4bf-6e91-421a-8616-74a44ce49b05)

**Comment by agocke** [comment]
Closing as resolved.
