### ISSUE TITLE
System.Text.Json should not be installed successfully on netcoreapp3.1

### ISSUE THREAD

**Issue by RoderickIveans** [dotnet/runtime#107271]
### Description

My project's target framework is netcore3.1, and when I finished installing System.Text.Json, I received the following warning. If netcoreapp3.1 is not supported and is untested, I would rather not be able to install it than receive a warning or have it actively suppressed.

`System.Text.Json 8.0.4 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.`

### Reproduction Steps

NuGet  UI install `System.Text.Json`

### Expected behavior

install failure

### Actual behavior

Install successfully and receive a warning

**Comment by huoyaoyuan** [comment]
Since netcoreapp3.1 supports netstandard2.0, it's *compatible* with System.Text.Json, and probably works. But we do not guarantee any *support* on the configuration.

> If netcoreapp3.1 is not supported and is untested, I would rather not be able to install it than receive a warning or have it actively suppressed.

This is not directly achievable with the current NuGet mechanism.
We do not want to block the users of outdated frameworks forcefully, just discouraging them.

This is not limited to System.Text.Json. Packages provided in dotnet/runtime are all enabling the warning.

**Comment by RoderickIveans** [comment]
> Since netcoreapp3.1 supports netstandard2.0, it's _compatible_ with System.Text.Json, and probably works. But we do not guarantee any _support_ on the configuration.

As you said, it is possible to work, we do not want a half-finished product, we would rather not have it.

**Comment by huoyaoyuan** [comment]
> As you said, it is possible to work, we do not want a half-finished product, we would rather not have it.

Note that .NET Core 3.1 has been out of support for several years. It's more unreliable to continue using the framework than NuGet packages.

The warning message doesn't come with a warning ID. If it does, you can simply turn on `WarnAsError` for the ID. @dotnet/area-infrastructure-libraries

**Comment by RoderickIveans** [comment]
> Note that .NET Core 3.1 has been out of support for several years. It's more unreliable to continue using the framework than NuGet packages.
> 
> The warning message doesn't come with a warning ID. If it does, you can simply turn on `WarnAsError` for the ID. @dotnet/area-infrastructure-libraries

Since .NET Core 3.1 isn't supported anymore, you guys really shouldn't be releasing packages that can be installed on .NET Core 3.1. If these packages can be installed, they should have been thoroughly tested and not feel half-baked. Users shouldn't have to suppress warnings to make things work.

**Comment by timcassell** [comment]
If you install version 6.x or older, you shouldn't get the warning.

The .Net Standard nuget package support is frustratingly bad on Core runtimes.

**Comment by timcassell** [comment]
More info: https://github.com/open-telemetry/opentelemetry-dotnet/issues/3448

**Comment by huoyaoyuan** [comment]
> Since .NET Core 3.1 isn't supported anymore, you guys really shouldn't be releasing packages that can be installed on .NET Core 3.1.

They are not intentionally made installable on .NET Core 3.1. They are just transitively available as the side effect of supporting .NET Standard and .NET Framework.

We won't take additional effort to benefit the users of outdated frameworks, but if it comes for free, we would left things as-is for best availability.

**Comment by filipnavara** [comment]
> we do not want a half-finished product

As previously, pointed out, you start by using .NET Core 3.1 which was out of support since December 13, 2022. System.Text.Json should be the least of your worries. No security updates were released for the core runtime since then while there was plenty of vulnerabilities fixed in the supported releases since then.
