### ISSUE TITLE
TCP Socket Disconnected After Cancelling ReadAsync

### ISSUE THREAD

**Issue by 6bee** [dotnet/runtime#107209]
### Description

Cancelling `NetworkStream.ReadAsync` sets the `Socket` to disconnected. This leads to strange behavior, e.g. `TcpClient.GetStream()` throwing `InvalidOperationException` while the actual stream remains intact and can be continued to be used.
What's more, if cancellation is already set when calling `ReadAsync`, `Socket.Connected` remains true.

### Reproduction Steps

The issue may be reproduced with the following code:
```C#
using System.Net.Sockets;
using System.Net;

// launch server
using var tcpListener = new TcpListener(IPAddress.Any, 1234);
tcpListener.Start();
_ = tcpListener.AcceptTcpClientAsync();

// launch client
using var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
await socket.ConnectAsync(IPAddress.Loopback, 1234);
using var stream = new NetworkStream(socket);
try
{
    var cts = new CancellationTokenSource();
    cts.CancelAfter(0); // NOK: when cancelling async, socket.Connected will be false
    // cts.Cancel(); // OK: when already cancelled, socket.Connected will be true
    await stream.ReadAsync(Array.Empty<byte>(), cts.Token);
}
catch (OperationCanceledException)
{
}

Console.WriteLine($"connected: {socket.Connected}");
```

### Expected behavior

Cancelling an async read operation should leave the socket connection unaffected, i.e. `Socket.Connected` should remains true.

### Actual behavior

Cancelling an async read operation sets socket to disconnected, i.e. `Socket.Connected` returns false.

### Regression?

_unknown_

### Known Workarounds

_unknown_

### Configuration

Tested with:
- .NET 8.0 SDK
- Microsoft.NETCore.App 8.0.8 and Microsoft.WindowsDesktop.App 8.0.8
- Windows 11 Pro 23H2
- PlatformTarget=x64 and PlatformTarget=x86

**Comment by wfurt** [comment]
This is essentially dup of #69397 as far as I can tell. While the use of stream after cancellation is discouraged (as the state is left undefined) it was changes in 9.0. I doubt this would qualify for backport to 8.0.

**Comment by 6bee** [comment]
Hi @wfurt, thanks for your response. 
It's true, I wasn't able to reproduce the issue using .net 9.0 sdk (v9.0.100-preview.7). 
Where can I find information about what exactly changed in 9.0?

**Comment by wfurt** [comment]
https://github.com/dotnet/runtime/pull/99181. It may be interesting to read through the comments @6bee
