### ISSUE TITLE
[Wasm] Support for the mono log profiler for memory profiling

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#107312]
The mono runtime provides a [log profiler](https://github.com/dotnet/runtime/blob/516e81e8a644b96b1e6c0eb930b02d26088fdb4a/src/mono/mono/profiler/log.h), which can generate mlpd files, which can be parsed by the Xamarin Profiler. 

This feature is not enabled in the current main, and considering that https://github.com/dotnet/runtime/pull/105713 may not make its way into .NET 9, being able to profile the memory of wasm apps is still a critical scenario.

If this helps, I have a [net8 patch](https://github.com/unoplatform/Uno.DotnetRuntime.WebAssembly/blob/70ec1d676dd08f41c44cfa77fbc324a2f2505484/patches/0006-enable-log-profiler.patch) that enabled it for Uno's custom runtime, which can certainly be updated for net9 and the wasmhost builds.

**Comment by pavelsavara** [comment]
Looking at the patch, I'm thinking this will add few KB of the native code, do you know how much ?

I wonder if we could move that to be linked only when enabled by some msbuild property in the linking phase of emcc/workload re-link. Together with the other 2 profilers.

cc @maraf
