### ISSUE TITLE
[Infra][NativeAOT-iOS] Runtime tests workitems not getting sent to helix

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#107346]
After https://github.com/dotnet/runtime/pull/107002, NativeAOT on IOS runtime tests are not getting bundled for Helix, reporting `error : SendHelixJob given no WorkItems to send.`

First failing build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=793084&view=logs&j=6ad81d5f-e956-5767-2437-61a9fc4dc8db&t=c71d6c6f-8520-5c9e-5bd9-f9fda7bcc121

![image](https://github.com/user-attachments/assets/ac6265c6-c6a3-4510-9245-1b30375f9584)

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by matouskozak** [comment]
cc: @jkoritzinsky

**Comment by jkoritzinsky** [comment]
I thought that my PR wouldn't have broken existing test runs... Easiest solution would be to build the nativeaot test tree instead of just the smoketests tree.

**Comment by jkoritzinsky** [comment]
Another option (which I'll try to put out a PR for today) would be to set the `BuildAllTestsAsStandalone` environment variable when building the smoke tests. That should put that test tree back on the old system.
