### ISSUE TITLE
System.Text.Json Trim Warning - 'System.Exception.TargetSite.get' which has 'RequiresUnreferencedCodeAttribute'

### ISSUE THREAD

**Issue by thomhurst** [dotnet/runtime#107375]
### Description

I was under the impression that JSON Source Generation was supported for trimmed apps. However I've got a trim warning for `Exception`.

I'm creating a source generated context, and the code it's generating is saying there's a trim warning.

### Reproduction Steps

```csharp
[JsonSourceGenerationOptions(
    WriteIndented = true,
    IgnoreReadOnlyProperties = true,
    IgnoreReadOnlyFields = true,
    Converters = [ typeof(TypeJsonConverter), typeof(MethodInfoJsonConverter), typeof(JsonStringEnumConverter<Status>) ],
    GenerationMode = JsonSourceGenerationMode.Default)]
internal partial class JsonContext : JsonSerializerContext;
```

### Expected behavior

No trim warning.

### Actual behavior

```
JsonContext.Exception.g.cs(188): Trim
  analysis warning IL2026: 
  TUnit.Engine.Json.JsonContext.<>c.<ExceptionPropInit>b__26_10(Object): Using 
  member 'System.Exception.TargetSite.get' which has 
  'RequiresUnreferencedCodeAttribute' can break functionality when trimming 
  application code. Metadata for the method might be incomplete or removed.
```

### Configuration

System.Text.Json 8.0.4

**Comment by huoyaoyuan** [comment]
Are you serializing `Exception`? As the warning message says, accessing some member of `Exception` is not trimming compatible. It's not related to whom accessing it.

**Comment by eiriktsarpalis** [comment]
For all intents and purposes, exception serialization is not supported by System.Text.Json. Ideally we should have included exception types in the list of explicitly disallowed types, but haven't done so.

There's a wider discussion going on regarding exception serialization in https://github.com/dotnet/runtime/issues/43482. Any decision to support exceptions in STJ would flow from that issue.
