### ISSUE TITLE
High Memory Consumption with Server GC Enabled

### ISSUE THREAD

**Issue by kushalshah5** [dotnet/runtime#107345]
**Description**
I have an application running with a memory footprint of around 200 MB when using the Workstation Garbage Collector (GC) or running it on my local machine. However, when I deploy the same application on a server or run it on my local machine with Server GC enabled, the memory usage spikes to approximately 500 MB. My application 
This significant increase in memory usage is unexpected, and I would like to understand the underlying cause and whether there are ways to optimize memory consumption with Server GC enabled.

**Expected Behavior**
Memory usage should remain consistent or within an acceptable range when switching from Workstation GC to Server GC.

**Actual Behavior**
Memory usage increases by approximately 200-300 MB when switching to Server GC.

**Configuration**
OS: Windows 11 x64
Runtime: .NET 8

Portion of Code : 

```
private async Task ReplicateEmployeeMasterData()
{
   await swappableEmployeeCopyRepository.CreateSwappableEmployeeCopyTable();
   var listOfEmployeesToInsert = new List<SwappableEmployeeCopyEntity>();
   const int chunkSize = 10000;
   var counter = 0;
   var EmployeeData =
       EmployeeMasterDataRepository.Queryable(x => true)
           .OrderBy(v => v.Id)
           .AsNoTracking()
           .AsAsyncEnumerable();
   await foreach (var Employee in EmployeeData)
   {
       listOfEmployeesToInsert.Add(mapper.Map<SwappableEmployeeCopyEntity>(Employee));
       counter++;
       if (chunkSize.Equals(counter))
       {
           await swappableEmployeeCopyRepository.
                 BulkInsertEmployees(listOfEmployeesToInsert);
           listOfEmployeesToInsert.Clear();
           swappableEmployeeCopyRepository.ClearChangeTracker();
           counter = 0;
       }
   }

   await swappableEmployeeCopyRepository.BulkInsertEmployees(listOfEmployeesToInsert);
   listOfEmployeesToInsert.Clear();
}
```

```

public async Task CreateSwappableEmployeeCopyTable()
        {
            await dbContext.Database.ExecuteSqlRawAsync(@"
                DO
                $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'SwappableEmployeeCopy') THEN
                        TRUNCATE TABLE ""SwappableEmployeeCopy"";
                    ELSE
                        CREATE TABLE ""SwappableEmployeeCopy"" (
                            ""Id"" bigint,
                            ""Name"" varchar(17),
                            ""CompanyId"" integer NOT NULL,
                            ""Company"" varchar(50) NOT NULL,
                            ""Department"" varchar(100) NOT NULL,
                            ""JobTitle"" varchar(100),
                            ""Salary"" integer,
                            ""CreatedAt"" timestamptz NOT NULL,
                            ""LastModifiedAt"" timestamptz NOT NULL,
                            ""AnnualLeaveBalance"" smallint,
                            ""CommissionRate"" numeric(4,2),
                            ""IsActive"" boolean NOT NULL,
                            CONSTRAINT ""PK_SwappableEmployeeCopy"" PRIMARY KEY (""Id"")
                        );
                    END IF;
                END
                $$;
            ");
        }
```

```
 public async Task BulkInsertEmployees(IEnumerable<SwappableEmployeeCopyEntity> newEmployees)
 {
            await dbContext.AddRangeAsync(newEmployees);
            await SaveChangesAsync();
 }
```

- With Workstation GC

![Workstation_GC](https://github.com/user-attachments/assets/5b8aaa58-736b-42f2-bdab-4cb514de286f)

- With Server GC

![Server_GC](https://github.com/user-attachments/assets/2aacdd86-5817-4a53-b74e-6bc3242b9de3)

**Comment by KeterSCP** [comment]
This is somewhat expected behavior. For the workstation GC there is only one heap, but for server GC there are X heaps, where X is the number of logical CPU your system has. So, your memory footprint for server GC would be much bigger.

This has been a problem for many users, so in .NET 8 the GC team made a great feature called DATAS (Dynamically Adapting To Application Sizes), which can shrink your memory usage on server GC close to what you see with workstation GC.. (more info on @Maoni0's medium post [here](https://maoni0.medium.com/dynamically-adapting-to-application-sizes-2d72fcb6f1ea))

To enable it in .NET 8, you need to add this property group to your .csproj file:

```xml
<PropertyGroup>
  <GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>
</PropertyGroup>
```

Starting with .NET 9m DATAS is enabled by default and you don't need to set any properties.

**Comment by mangod9** [comment]
ServerGC is optimized for throughput not memory, hence the GC will consume more memory to avoid frequent collections. As mentioned above DATAS would help with most scenarios, and if your app performs well with Workstation GC you can continue to use that configuration. Closing this issue for now, hoping this provides relevant information for your original question. Thanks.
