### ISSUE TITLE
JIT incorrectly identify program as invalid

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#107391]
I'm not sure that this is actual bug, but it appear so. I discover this issue troubleshooting Cesium codegen, and dissect problem to this smaller thing

```
  .method public static int32  test() cil managed
  {
    IL_000c:  ldc.i4.1
    IL_0017:  brfalse    IL_0039

    IL_0039:  ldc.i4.0
    IL_006c:  ret

    IL_006d:  nop
    //  ret
  }
```

Even if program always return valid result, it crashes with `Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.`. If I uncomment `ret` on the last line issue will disappear. IL_006d is always unreachable, so I'm a bit confused is this expected or not.

**Comment by huoyaoyuan** [comment]
I have to act as a language lawyer to answer whether it's considered invalid based on ECMA-335 spec. But apparently, no popular compiler emits IL like this.

**Comment by kant2002** [comment]
I have no objections per se. and I have slightly more involved output which I carefully cut. but I`II.3.57 ret – return from method` did not say anything and I still looking for an answer elsewhere

**Comment by SingleAccretion** [comment]
This is invalid IL without a `ret`. You can't "fall out" of a method via a `nop`.

**Comment by MichalStrehovsky** [comment]
"III.1.7.1 The instruction stream" in the ECMA-335 spec seems applicable: "Unreachable code can appear as the result of machine-generated code and is allowed, but it shall always be in the form of properly formed instruction sequences.". I.e. VES can look at unreachable instructions and they need to make sense.

**Comment by kant2002** [comment]
Thank you for your help and clarifications!
