### ISSUE TITLE
[Mono] NetTrace Collected mismatches expected CLR Instance name

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#107315]
### Description

A NetTrace collected from a .NET Android app does not contain a `TraceManagedModule` with a corresponding `TraceLoadedModule` with a name of `"System.Private.CoreLib"`, instead has a name of `"System.Private"`.
![Screenshot 2024-08-29 132902](https://github.com/user-attachments/assets/e10ed1f7-3287-46b0-9fed-de8dece78b20)
![Screenshot 2024-08-29 132805](https://github.com/user-attachments/assets/0f9c28b3-b052-49c6-9609-094a43767aaa)
As a result, dotnet-pgo cannot convert the .nettrace into a .mibc profile.

### Reproduction Steps

Install diagnostics tooling - dotnet-trace + dotnet-dsrouter 
`dotnet tool install --global dotnet-trace`
`dotnet tool install --global dotnet-dsrouter`

Spin up android emulator + setup for tracing
`adb reverse tcp:9000 tcp:9001`
`adb shell "setprop debug.mono.profile '127.0.0.1:9000,suspend,connect'"`

Build and Run .NET Android app
`dotnet new android -o MyAndroidApp`
`dotnet build -t:Run -p:AndroidEnableProfiler=true -f net9.0-android`
(Should see that the app suspends until diagnostics tooling connects

Collect a trace
In one console window `dotnet dsrouter android`
In another console window `dotnet trace collect --name dotnet-dsrouter --providers Microsoft-Windows-DotNETRuntime:0x1F000080018:5 --duration 00:00:00:05`
(Should see the app continues and a trace is collected.

Run dotnet/runtime's public dotnet-pgo tool
Tool gets built as part of building clr subset
`dotnet-pgo create-mibc --trace <nettrace> --compressed false -o <mibc name>`

### Expected behavior

Mibc profile gets created

### Actual behavior

`Error: No managed CLR in target process, or per module information could not be loaded from the trace.`

### Regression?

I believe this was working when https://github.com/dotnet/runtime/pull/90959 was added, not sure if I am forgetting a step

### Known Workarounds

Could add `--clr-instance-id 9`, but then still hitting problems with converting the trace to a .mibc profile

```
Error: Read out of bounds.
System.BadImageFormatException: Read out of bounds.
	at System.Reflection.Throw.OutOfBounds()
	at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(TypeDefinitionHandle handle)
	at System.Reflection.Metadata.TypeDefinition.get_Name()
	at Internal.TypeSystem.Ecma.EcmaType.InitializeName() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 281
	at Internal.TypeSystem.Ecma.EcmaType..ctor(EcmaModule module, TypeDefinitionHandle handle) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 44
	at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 94
	at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 562
	at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 423
	at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 379
	at Microsoft.Diagnostics.Tools.Pgo.TraceRuntimeDescToTypeSystemDesc.ResolveTypeHandle(Int64 handle, Boolean& dependsOnKnownNonLoadableType, Boolean throwIfNotFound) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs:line 409
	at Microsoft.Diagnostics.Tools.Pgo.TraceRuntimeDescToTypeSystemDesc.Init() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs:line 264
	at Microsoft.Diagnostics.Tools.Pgo.Program.InnerProcessTraceFileMain() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/Program.cs:line 1343
	at Microsoft.Diagnostics.Tools.Pgo.Program.Run() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/Program.cs:line 268
	at Microsoft.Diagnostics.Tools.Pgo.PgoRootCommand.<.ctor>g__ExecuteWithContext|96_5(ParseResult result, Boolean setVerbosity) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/PgoRootCommand.cs:line 246
```
```
Error: Invalid TypeParameterCount 2 expected 0 as needed by '[S.P.CoreLib]System.Collections.IEnumerator'
System.Exception: Invalid TypeParameterCount 2 expected 0 as needed by '[S.P.CoreLib]System.Collections.IEnumerator'
	at Microsoft.Diagnostics.Tools.Pgo.TraceRuntimeDescToTypeSystemDesc.ResolveTypeHandle(Int64 handle, Boolean& dependsOnKnownNonLoadableType, Boolean throwIfNotFound) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs:line 415
	at Microsoft.Diagnostics.Tools.Pgo.TraceRuntimeDescToTypeSystemDesc.Init() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs:line 264
	at Microsoft.Diagnostics.Tools.Pgo.Program.InnerProcessTraceFileMain() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/Program.cs:line 1343
	at Microsoft.Diagnostics.Tools.Pgo.Program.Run() in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/Program.cs:line 268
	at Microsoft.Diagnostics.Tools.Pgo.PgoRootCommand.<.ctor>g__ExecuteWithContext|96_5(ParseResult result, Boolean setVerbosity) in /Users/mitchellhwang/projects/runtime/src/coreclr/tools/dotnet-pgo/PgoRootCommand.cs:line 246
```

### Configuration

Host machine OSX arm64
App configuration android arm64 Release (android emulator)

**Comment by mdh1418** [comment]
@lambdageek Do you happen to know what makes a MonoImage's module name have an extension or not?
For android it looks like sometimes the fallback to the module name will just be "System.Private.CoreLib", and because Perfview's TraceEvent library truncates extensions without checking what the extension is, sometimes a NetTrace collected from an .NET Android app cannot be processed by dotnet-pgo because it fails to identify "System.Private" as the CLR instance.

**Comment by lateralusX** [comment]
@mdh1418 Have you looked at the underlying EventPipe events and what the module events it contains, I assume the module file name is just System.Private.CoreLib there as well? The EventPipe library reads out metadata from Mono on these properties, and I know that Android can use bundled assemblies, https://github.com/dotnet/runtime/blob/88f9aba91e11d1695ebe9ab572736ee62ac7ad61/src/native/public/mono/metadata/details/assembly-functions.h#L65 and I believe they even have a custom assembly loader, so maybe that is the case here, the assemblies are bundled and not backed by files and in that case the file name might not be available, so we will take the module name as one of the parameters and that doesn't include any file extensions. I think the implementation for that is here, https://github.com/dotnet/runtime/blob/88f9aba91e11d1695ebe9ab572736ee62ac7ad61/src/mono/mono/eventpipe/ep-rt-mono-runtime-provider.c#L821.

Look in TraceEvent library on what fields it tries to extract and you can backtrack it to the above EventPipe message. Since Mono have the ability to bundle resources not backed by a physical file on disk, only having the real module name is probably a scenario that needs to be handled.

**Comment by brianrob** [comment]
@mdh1418, do I understand correctly that you're seeing a case where the ModuleILPath is System.Private.CoreLib and so TraceEvent is trimming CoreLib?  If so, that feels like a bug, and we should definitely fix that to only trim .dll or .exe.

**Comment by mdh1418** [comment]
That is correct, when mono emits module events, it processes the event data here https://github.com/dotnet/runtime/blob/88f9aba91e11d1695ebe9ab572736ee62ac7ad61/src/mono/mono/eventpipe/ep-rt-mono-runtime-provider.c#L821-L827, attempting to use the filename metadata, and falling back to the modulename.

@jonathanpeppers mentioned, as Johan suspected, that .NET Android apps will not have files on disk in general, and .apk files will remain compressed even when installed, so the filename metadata will not be there. So it seems like the module name will always be used for .NET Android apps.

I still don't know what is leading to the discrepancy between the modulename being `System.Private.CoreLib` for Android, but seems to have the `.dll` extension on wasm, as [noted in the PR adding the fallback](https://github.com/dotnet/runtime/pull/73018#issuecomment-1198509259).

Would updating TraceLog to only trim `.dll` or `.exe` when grabbing the TraceModuleFile's Name work? Just not sure what all the expected/accepted valid extensions are for TraceModuleFiles

**Comment by brianrob** [comment]
I think the code in question is https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L3676.  From the two uses, I think that this code just isn't written defensively enough - it was fine for Windows when the code was written, but not for Android.  Do you want to take a crack at writing up a PR for this?

**Comment by lambdageek** [comment]
>  I know that Android can use bundled assemblies

@mdh1418 @lateralusX dotnet/android does not use the "bundled assemblies" machinery built into the runtime.  It just registers a native callback and hands the runtime a `MonoImage` on its own:

https://github.com/dotnet/android/blob/87f1cd61bef50491ccc7872da0e7cb299097c2b1/src/native/monodroid/mono-image-loader.hh#L53-L86

Called from 

https://github.com/dotnet/android/blob/87f1cd61bef50491ccc7872da0e7cb299097c2b1/src/native/monodroid/embedded-assemblies.cc#L259

and from

https://github.com/dotnet/android/blob/87f1cd61bef50491ccc7872da0e7cb299097c2b1/src/native/monodroid/embedded-assemblies.cc#L398

So the corresponding runtime code is in `mono_image_open_from_data_alc` and `mono_image_open_from_data_with_name`

https://github.com/dotnet/runtime/blob/66e45ef152002a2e1cbea939ded6643dfa48307c/src/mono/mono/metadata/image.c#L1671-L1699

which both pass the same `name` for `name` and `filename`:

https://github.com/dotnet/runtime/blob/66e45ef152002a2e1cbea939ded6643dfa48307c/src/mono/mono/metadata/image.c#L1628-L1668

**Comment by lateralusX** [comment]
> > I know that Android can use bundled assemblies
> 
> @mdh1418 @lateralusX dotnet/android does not use the "bundled assemblies" machinery built into the runtime. It just registers a native callback and hands the runtime a `MonoImage` on its own:
> 
> https://github.com/dotnet/android/blob/87f1cd61bef50491ccc7872da0e7cb299097c2b1/src/native/monodroid/mono-image-loader.hh#L53-L86
> 
> Called from
> 
> https://github.com/dotnet/android/blob/87f1cd61bef50491ccc7872da0e7cb299097c2b1/src/native/monodroid/embedded-assemblies.cc#L259
> 
> and from
> 
> https://github.com/dotnet/android/blob/87f1cd61bef50491ccc7872da0e7cb299097c2b1/src/native/monodroid/embedded-assemblies.cc#L398
> 
> So the corresponding runtime code is in `mono_image_open_from_data_alc` and `mono_image_open_from_data_with_name`
> 
> https://github.com/dotnet/runtime/blob/66e45ef152002a2e1cbea939ded6643dfa48307c/src/mono/mono/metadata/image.c#L1671-L1699
> 
> which both pass the same `name` for `name` and `filename`:
> 
> https://github.com/dotnet/runtime/blob/66e45ef152002a2e1cbea939ded6643dfa48307c/src/mono/mono/metadata/image.c#L1628-L1668

OK, so the end effect will be the same then, no real file name in the MonoImage used by EventPipe since code paths ending up through above callbacks or through the runtime bundling won't have a physical file backing the MonoImage. I think perfview needs to be hardened against this case, alternative is to add module name in a new version of the EventPipe events and let perfview handle the new version with additional attribute, but that is a bigger change with more implications, so just harden perfview is probably the most reasonable approach. This is also the first time I see an issue with this, so most of the nettrace processing from Android seems to either handle this case already or doesn't use the data directly.

**Comment by brianrob** [comment]
>> I think perfview needs to be hardened against this case

Agreed.  @mdh1418 has posted https://github.com/microsoft/perfview/pull/2111.

**Comment by mdh1418** [comment]
After testing out the perfview changes, I think I'm still hitting the errors detailed in the Workaround section. My hunch is that these are mono specific issues with emitting enough details into the TraceEvents, but I'm not well versed with the expectation and what is missing.

But until those are resolved, it seems like ProfiledAOT with mono is broken when tracing apps with the .NET Android workloads.

@lambdageek @lateralusX, do y'all happen to have any suspicions with the `TypeParameterCount` mismatch and what I should look for?

**Comment by lateralusX** [comment]
@mdh1418 AFAIK this worked against Android workloads in the past (at least when running from dotnet/runtime Android app). Could it be the case that dotnetpgo anticipate some specific types that are either not present on Mono or trimmed away in this case? Since it has worked in the past it sounds more like some change to dotnetpgo or that some types have been trimmed away in the Android workload. You can probably look at the callstack above and figure out what type it tries to resolve. Also check if the package has been trimmed in this case.

**Comment by lateralusX** [comment]
I think the best way is to debug dotnetpgo around the failing code paths and figure out what type it fails on and how it gets details on what types to resolve.

**Comment by mdh1418** [comment]
There seems to be some behavior discrepancies between a release/debug version of dotnet-pgo and discrepancies between the assemblies built a ~year ago at https://github.com/dotnet/runtime/commit/fd6d5fd0a330a8a6fd286a3d924f4e832aaeb479 and "now".

The .NetTrace files checked in by https://github.com/dotnet/runtime/pull/90959 were compatible.

The investigation w/ building the [Android Functional AOT_PROFILED test](https://github.com/dotnet/runtime/tree/main/src/tests/FunctionalTests/Android/Device_Emulator/AOT_PROFILED) has three components
1) dotnet-pgo - android-arm64-debug | osx-arm64-release | osx-arm64-debug | win-x64-release
2) FunctionalTest assemblies - "~year ago" | "now"
3) FunctionaTest test_debug.nettrace - Constant 

| | ~1yr Ref Assemblies | "Now" Ref Assemblies |
|--------|--------|--------|
| ~1yr Android debug pgo | :white_check_mark: | `TypeParameterCount 2 expected 0` |
| "Now" Osx debug pgo  | :white_check_mark: | `TypeParameterCount 2 expected 0` |
| "Now" Osx release pgo | Assertion failed | Assertion Failed|
| "Now" win release pgo | `TypeParameterCount 2 expected 1` | `TypeParameterCount 2 expected 0` |
| "Now" win debug pgo | :white_check_mark: | `TypeParameterCount 2 expected 0` |

The TypeParameterCount mismatch is at https://github.com/dotnet/runtime/blob/636c86342a29dfa8f419414bbd4877b882198ed3/src/coreclr/tools/dotnet-pgo/TraceRuntimeDescToTypeSystemDesc.cs#L514, but that immediate code section looks unchanged.

The Assertion Failed looks like https://gist.github.com/mdh1418/564a9c415f258c41980eac87c0e10d79

**Comment by lateralusX** [comment]
@mdh1418 I assume dotnet-pgo reads up data from assemblies on disk based on paths in events and this error indicates that the specific type is different between what's running on the device and what's being read up from disk, so could it be the case that it don't read the right set of assemblies since S.P.C is different between Mono and CoreClr versions of S.P.C. The nettrace file will include description of the types running at the device, meaning that dotnet-pgo must use the same set of assemblies as running at device as its references. I recall there was some parameter where you can point it to the assemblies to use, so maybe that is the step you miss, like --reference or similar so you probably need to make sure it only uses the same assemblies as collected nettrace file.

**Comment by lateralusX** [comment]
> Both assemblies for "Now" and "~1 yr ago" were built for Android arm64 Debug, so it should only have been built for mono.
> 
> Right, we had to add `--reference` to the NetTraceToMibcConverter task [here](https://github.com/dotnet/runtime/blob/4267ab8b52cd4953dd563dd99ab10c5f651dccad/src/tasks/MonoTargetsTasks/NetTraceToMibcConverterTask/NetTraceToMibcConverter.cs#L107-L111) specifically for Android's use case because the nettrace pointed at the assemblies on the device/emulator itself, but as the NetTraceToMibcConverter and MonoAOTCompiler tasks are ran on the host machine, the assemblies had different paths and required the `--reference` to resolve.

So I guess that is the missing step in the commands you run above then, you don't pass the --reference path to make sure dotnet-pgo sees the same assemblies that produced the nettrace file.
