### ISSUE TITLE
Add support for SHA256 thumbprints not supported in X509Certificate2Collection.Find

### ISSUE THREAD

**Issue by blowdart** [dotnet/runtime#107330]
Windows finally added a flag to support SHA256 thumbprint lookup in the certificate stores (even though the Certificate properties still only shows SHA1).

https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certfindcertificateinstore

| Flag | Meaning |
|------|---------|
| CERT_FIND_SHA1_HASH | Searches for a certificate with a SHA1 hash that matches the hash in the CRYPT_HASH_BLOB structure. |
| CERT_FIND_SHA1_SHA256_HASH | Searches for a certificate with a SHA1 + SHA256 hash that matches the hash in the CRYPT_HASH_BLOB structure. |
| CERT_FIND_SHA256_HASH | Searches for a certificate with a SHA256 hash that matches the hash in the CRYPT_HASH_BLOB structure. |

We need to update the [X509FindType Enum](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509findtype) to support the two new flags, and the appropriate parameters, then wire that into the Find methods.

Unknown if this was backported to all supported windows versions, or when it was introduced.

**Comment by bartonjs** [comment]
Duplicate/variant of https://github.com/dotnet/runtime/issues/104643.
