### ISSUE TITLE
Question: CA2012 ValueTask message incorrect for discards?

### ISSUE THREAD

**Issue by osexpert** [dotnet/runtime#107394]
Example:

		private async ValueTask Test()
		{
			throw new NotImplementedException();
		}

		public async Task Start1()
		{
			_ = Test(); // CA2012	ValueTask instances returned from method calls should always be used, typically awaited. Not doing so often represents a functional bug, but even if it doesn't, it can result in degraded performance if the target method pools objects for use with ValueTasks.
		}

		public async Task Start2()
		{
			_ = Test().Preserve(); // ok
		}

		public async Task Start3()
		{
			_ = Test().AsTask(); // ok
		}

		public async Task Start4()
		{
			var vt = Test(); // IDE0059	Unnecessary assignment of a value to 'vt'
		}

		public async Task Start5()
		{
			Test(); // CA2012, CS4014
		}

		public async Task Start6()
		{
			var vt = Test(); // ok
			if (!vt.IsCompletedSuccessfully)
			{
				vt.AsTask().GetAwaiter().GetResult(); // problem: not fire and forget anymore
			}
		}

I don't understand why CA2012 is emitted for the discard case? Possibly an edge case that was forgotten and by accident put on the 'bad' list? Or is perhaps the result reachable by GC even if discarded?

**Comment by stephentoub** [comment]
> I don't understand why CA2012 is emitted for the discard case?

If pooling is being used, not awaiting it means the underlying object will never be returned to the pool.

**Comment by huoyaoyuan** [comment]
It is correct and by design.

`ValueTask` supports pooling with `IValueTaskSource`. It must be consumed exactly once to correctly dispose the state with `IValueTaskSource`. GC is not applicable here because `ValueTask` is a struct.

**Comment by osexpert** [comment]
But are AsTask() and Preserve() acceptable workarounds, or are they hacks?

**Comment by huoyaoyuan** [comment]
> But are AsTask() and Preserve() acceptable workarounds, or are they hacks?

They transform the `ValueTask` into a `Task` in behind, which is more flexible to use and preserve. They are designated ways to consume a `ValueTask` as well as `await`ing it directly.

**Comment by osexpert** [comment]
> > I don't understand why CA2012 is emitted for the discard case?
> 
> If pooling is being used, not awaiting it means the underlying object will never be returned to the pool.

But I see code checking IsCompletedSuccessfully (and in some cases IsCompleted) and not awaiting in this case and just getting the result directly.

**Comment by stephentoub** [comment]
> > > I don't understand why CA2012 is emitted for the discard case?
> > 
> > 
> > If pooling is being used, not awaiting it means the underlying object will never be returned to the pool.
> 
> But I see code checking IsCompletedSuccessfully (and in some cases IsCompleted) and not awaiting in this case and just getting the result directly.

Where?

**Comment by osexpert** [comment]
So I guess the answer is: yes, the message is correct. AsTask() (or Preserve()) is needed and will make sure the value task is returned to the pool (if any).

But will a finalizer or similar eventually return it to the pool, or is it is a permanent loss?

**Comment by osexpert** [comment]
> `Preserve().GetAwaiter().GetResult()` is a much simpler approach. `Task`-backed `ValueTask` can be safely used with blocking `GetResult()`.

Yes, its a lot simpler. Thou my suggestion was an attempt to make optimized versions that does minimum amount of work, but it may be premature optimization:-)
