### ISSUE TITLE
JSON-(de)serialize Base64 string as ImmutableArray<byte>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#107352]
### Description

Today you can (de)serialize a Base64 string as a byte[] but not other TCollection<byte> types.

Today, the following code serializes/deserializes as expected:
```
byte[] Array = [0, 1, 2, 3, 4, 5];

var Data = new {
    Array,
};

var Content = System.Text.Json.JsonSerializer.Serialize(Data);
Console.WriteLine(Content);
```

However, the following code does not:
```
            ImmutableArray<byte> Array = [0, 1, 2, 3, 4, 5];

            var Data = new {
                Array,
            };

            var Content = System.Text.Json.JsonSerializer.Serialize(Data);
            Console.WriteLine(Content);
```

### Reproduction Steps

```
            ImmutableArray<byte> Array = [0, 1, 2, 3, 4, 5];

            var Data = new {
                Array,
            };

            var Content = System.Text.Json.JsonSerializer.Serialize(Data);
            Console.WriteLine(Content);
```

### Expected behavior

I should be able to deserialize a Base64 string to any ```TCollection<byte>``` type.

### Actual behavior

It only works for ```byte[]```

### Regression?

No

### Known Workarounds

If I make my models use ```byte[]``` instead of ```ImmutableArray<byte>``` I get the expected result but I lose the immutable guarantees.

### Configuration

.NET 8.0.8
VS 17.11
x64

**Comment by colejohnson66** [comment]
Your text and title say base64, but your code says JSON.

**Comment by eiriktsarpalis** [comment]
Base64 handling of bytes is only hardcoded for `byte[]`, `Memory<byte>` and `ReadOnlyMemory<byte>` which are the de facto standard types for storing binary data. Other types implementing `IEnumerable<byte>` use JSON array containing individual bytes, and retroactively changing this now would constitute a breaking change.

> If I make my models use byte[] instead of ImmutableArray<byte> I get the expected result but I lose the immutable guarantees.

Have you considered using `ReadOnlyMemory<byte>` instead or use a custom converter?
