### ISSUE TITLE
How to build NativeAOT for Android under Linux (Docker)

### ISSUE THREAD

**Issue by JCash** [dotnet/runtime#107337]
### Description

When building for Android under Linux (in our Docker container), I get:
```
grep: /opt/platformsdk/android/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/etc/os-release: No such file or directory
  Generating native code
  Unhandled exception. System.CommandLine.CommandLineException: Target OS 'android' is not supported
     at System.CommandLine.Helpers.GetTargetOS(String) + 0x4e9
     at System.CommandLine.CliArgument`1.<>c__DisplayClass8_0.<set_CustomParser>b__0(ArgumentResult, Object&) + 0x31
     at System.CommandLine.Parsing.ArgumentResult.ValidateAndConvert(Boolean) + 0x162
     at System.CommandLine.Parsing.CommandResult.ValidateOptions(Boolean) + 0x153
     at System.CommandLine.Parsing.CommandResult.Validate(Boolean) + 0x6e
     at System.CommandLine.Parsing.ParseOperation.Validate() + 0x1b
     at System.CommandLine.Parsing.ParseOperation.Parse() + 0x30
     at System.CommandLine.Parsing.CliParser.Parse(CliCommand, IReadOnlyList`1, String, CliConfiguration) + 0x7a
     at System.CommandLine.CliConfiguration.Invoke(String[]) + 0x15
     at ILCompiler.Program.Main(String[] args) + 0xd8
  Aborted
  ```
  
It complains about both a missing folder, but also says Android is unsupported?
Is it one or the other, or both?
  
I've used the googles sdkmanager to install the Android SDK, which it seems DotNet picks up correctly.
Our setup works for building Android apps just fine, so I'm unclear on what package is missing from the Android install here?
  
Any help appreciated!
  
Regards,
Mathias

### Reproduction Steps

Here is our sdk packaging script:
https://github.com/defold/defold/blob/dev/scripts/package/package_android_sdk.sh#L92-L93

### Expected behavior

It should have all needed to build for Android already?
It would be good if DotNet mentioned which _tool_ was missing, rather than a folder name.

### Actual behavior

It doesn't build.

**Comment by huoyaoyuan** [comment]
NativeAOT for Android is still under development. See https://github.com/dotnet/runtime/issues/106748#issuecomment-2302160443 .
Closing as a duplicate.

**Comment by MichalStrehovsky** [comment]
If you want to build for Bionic libc, this is possible starting with .NET 8, instructions here: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/android-bionic.md

A more complex sample including JNI here: https://github.com/josephmoresena/NativeAOT-AndroidHelloJniLib/tree/main

This target is experimental.

**Comment by JCash** [comment]
Hi!
Thanks for the link.

I'm not sure I understand the target platform though: `linux-bionic-arm64`, is that supported later when I link my Android native app, with arch `armv8-a`?

**Comment by MichalStrehovsky** [comment]
> I'm not sure I understand the target platform though: linux-bionic-arm64, is that supported later when I link my Android native app, with arch armv8-a?

linux-bionic-arm64 is a .NET RID. armv8-a doesn't exist as a RID in .NET.

> Also, "Copy it to an Android device" is a step I cannot do on my (cloud) linux machine.

The instructions just show how to build and run an command line executable to run on Android. If you don't need to run it, don't copy it. I assume you want to build a library to include in a otherwise non-.NET app anyway so the way to package/execute it will be different.
