### ISSUE TITLE
Intermittent issue while fetching windows default credentials using UseDefaultCredentials = true in HttpClientHandler

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#107480]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intermittent-issue-while-fetching-window/10736286)._

---
Hi,

In our application we are trying to use windows credentials while fetching data from an API. Below is the code we have implemented. This is giving intermittent issues while fetching DefaultCredentials. We observed in fiddler that Authorization header("Authorization: Negotiate <token>") is not getting created for this call. This issue is occurring intermittently. Could someone suggest a solution here? Are we missing anything?

We are using net8.0

```
var handler = new HttpClientHandler

{

UseDefaultCredentials = true

};

var client = new HttpClient(handler)

{

Timeout = new TimeSpan(0,0,1,0)

};

client. DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

client. DefaultRequestHeaders.Add("x-bwin-client-machine", Environment.MachineName);

var response = await client. GetAsync(url);
```

---
#### Feedback Bot on 9/2/2024, 01:20 AM: 

(private comment, text removed)
#### Feedback Bot on 9/3/2024, 00:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by wfurt** [comment]
can we get packet capture? The `Negotiate` header should be response to server's request.

**Comment by deryaza** [comment]
If there is redirection happening than try this https://github.com/dotnet/runtime/issues/89300

Stumbled upon similar issue not so long ago
