### ISSUE TITLE
ToString("MMM") outputs September as Sept

### ISSUE THREAD

**Issue by SolentCIS** [dotnet/runtime#107453]
### Description

I want to format months as a 3 character string and used the format "MMM". All months are formatted as 3 characters except September which is formatted as Sept

### Reproduction Steps

Create a .NET 8.0 console application with the following code:

`DateTime now = DateTime.Now;
for (int i = 0; i < 12; i++)
{
    Console.WriteLine(now.ToString("MMM"));
    now = now.AddMonths(1);
}`

### Expected behavior

September should be formatted as Sep

### Actual behavior

Sep is formatted as Sept
![ToStringMMM](https://github.com/user-attachments/assets/f4ed130d-fe66-4198-a055-c0003947979f)

### Regression?

Yes

### Configuration

.NET 8.0
Windows 11 Pro x64
I have used this in a .NET Maui application on Android and Apple which is where I noticed an error

**Comment by gfoidl** [comment]
In [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AJXwwEsBbGZgSTwYYUCAAcAyiIBunMDADOAbmrUAxJwBm9AHIBRACoBhAPKs9AQQAKV6kwCcACnZCeMQZujcAhlwh5mEwkAEUUwKE4xPzwAShUaMicXLl4PL19Of2YAMShvXgB3aABrUIVwyOi4u0THaqo1GDwAEy1VKmDfGAM3ejwIAvoAXnpO4R7eZh0BpXpPKHpHTiF6TmH6Wlm1gB56MhItgGpDmPoAb0Za/oLmAwgJDAi8AHNHACIAWS+3mLi+gfW12YFmazQ+/gwAAsFI4yH8AL5AA==) this can't be reproduced -- but there's not Win 11 available.

**Comment by SolentCIS** [comment]
I always thought the custom format specifier "MMM" meant ToString() must use 3 characters, but it doesn't actually mean that, it means use the abbreviated name of the month.

**Comment by philipborg** [comment]
> I always thought the custom format specifier "MMM" meant ToString() must use 3 characters, but it doesn't actually mean that, it means use the abbreviated name of the month.

Yes, that's correct. Forcing 3 characters wouldn't work in languages where the full name of a month is shorter than 3 character neither.

**Comment by Clockwork-Muse** [comment]
> I always thought the custom format specifier "MMM" meant ToString() must use 3 characters, but it doesn't actually mean that, it means use the abbreviated name of the month.

You're not even guaranteed that the name will be any shorter than the full month name (language dependent).

> .NET nowadays uses data from CLDR by default; but see [Use NLS instead of ICU](https://learn.microsoft.com/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu) for how to override that on Windows.

1. Preferably, still use ICU, and only set NLS mode to work around compat needs while you refactor your code to be correct.
2. NLS makes no guarantees about data stability either, and it's possibly only a matter of time until NLS also changes to this data.

> Create a .NET 8.0 console application with the following code:

For any culture-dependent settings, normally we need your current culture settings (and on Windows, whether there are format overrides set).
