### ISSUE TITLE
HttpWebRequest incorrectly throwing exception on 3xx responses

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#1074]
We are setting up a `HttpWebRequest` object with `AllowAutoRedirect` set to `false` and then later calling `webRequest.GetResponse()`. On .NET Framework calling the `GetResponse` method will succeed for 3xx HTTP statuses returned from the server. On .NET Core it throws a `WebException`.

The relevant code in .NET Core is

https://github.com/dotnet/runtime/blob/0a29c61468f60f815119e52e477d0154351a4abf/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1225

Looking at the [reference source code of .NET Framework](https://referencesource.microsoft.com/#system/net/system/Net/HttpWebRequest.cs,5606) shows this:

```csharp
        // This helper method creates a new exception object with the provided information if this instance
        // of HWR should not return responses with status code other than 2xx (and 3xx if AllowAutoRedirect == false).
        private void SetExceptionIfRequired(string message, Exception innerException, ref Exception e)
```

Looks like the difference of behavior affects only requests with `AllowAutoRedirect` turned off.

**Comment by karelz** [comment]
Triage: Should be fairly straightforward to check for.
