### ISSUE TITLE
[android][infra] Runtime tests on Android are not getting sent to Helix

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#107551]
Some recent changes likely from this range https://github.com/dotnet/runtime/compare/516e81e8...57a4b043 caused that Android runtime tests are not properly bundled and sent Helix (`SendHelixJob given no WorkItems to send.`)

Affected CI:
- `android-x64 Release AllSubsets_Mono_RuntimeTests minijit`
- `android-x64 Release AllSubsets_Mono_RuntimeTests_Interp monointerpreter`

![image](https://github.com/user-attachments/assets/d6fff0b8-0252-4b59-b6b9-a61d04310848)

**Comment by matouskozak** [comment]
@jkoritzinsky do you think that https://github.com/dotnet/runtime/pull/107200 could be the cause? I thought that the changes shouldn't affect Mono/Mobile but only this and https://github.com/dotnet/runtime/pull/107167 from the range looks to be infra related.

**Comment by jkoritzinsky** [comment]
Unless Android was only "running" those tests (which are skipped on Android) and not running any other runtime tests, it couldn't be those. Can you check which tests were running beforehand?

**Comment by matouskozak** [comment]
> Unless Android was only "running" those tests (which are skipped on Android) and not running any other runtime tests, it couldn't be those. Can you check which tests were running beforehand?

I think only the profiler tests where running:
![image](https://github.com/user-attachments/assets/ecf16099-b911-4c70-8d1f-fb9b63c7cff7)

**Comment by jkoritzinsky** [comment]
Well that's really not good....

I'll see if I can get these jobs back to actually doing work. If you want to get these pipelines green in the meantime, you can disable these jobs as you aren't actually losing any test coverage...

**Comment by matouskozak** [comment]
> Well that's really not good....
> 
> I'll see if I can get these jobs back to actually doing work. If you want to get these pipelines green in the meantime, you can disable these jobs as you aren't actually losing any test coverage...

I agree and I'm unsure why we only used to run `profiler` tests even though we appear to be building the rest as well. I'll be OOF starting tomorrow but I'll check it out after I come back.

Thank you for looking into it.

**Comment by jkoritzinsky** [comment]
I found the issue. There was a change to fix an issue in running the runtime tests on desktop platforms about a year and a half ago which broke all mobile platforms. A later fix re-enabled WASM. I'm using that same fix (as it will work for our use case) for Android.
