### ISSUE TITLE
Vector128.GreaterThan returns negative number

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/runtime#107596]
Please help me make sense of this:
Vector128.GreaterThan(Vector128.Create(4,2,0,0), Vector128.Create(0)) returns <-1, -1, 0, 0>.
**Why the negative number?**

Basic mathematics: `bool compareResult  = 4 > 0 ;` //returns true == 1
CompareTo: int i = 4; `int compareResult = i.CompareTo(0);` //returns 1

**Comment by huoyaoyuan** [comment]
It's the contract of underlying CPU instructions to use *all bit set* to represent `true`. The value is `-1` for unsigned type and `MaxValue` for signed type. The value will be `NaN` when interpreted as floating point.

You should compare the result with 0 to get a boolean result, or pass the result vector directly to masking intrinsics.

**Comment by Aniobodo** [comment]
#The value is -1 for unsigned type and MaxValue for signed type. The value will be NaN when interpreted as floating point.
@huoyaoyuan 
Int32 is signed type according to https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types

... But it returned -1 ... Why?

**Comment by huoyaoyuan** [comment]
Sorry for the typo. The value is -1 for *signed type* and MaxValue for *unsigned type*.
You can inspect the value from `Vector128<T>.AllBitsSet.ToScalar()`

**Comment by Aniobodo** [comment]
@huoyaoyuan 
Thank you. Is it possible to add these information to the public documentation here [](https://learn.microsoft.com/de-de/dotnet/api/system.runtime.intrinsics.vector128.greaterthan?view=net-7.0) ?

**Comment by huoyaoyuan** [comment]
The current documentation for return value: 

> A vector whose elements are all-bits-set or zero, depending on if which of the corresponding elements in `left` and `right` were greater.

It does mention the all-bit-set value. It should be sufficient for the target audience of vector intrinsics, who are expected to have knowledge about binary representations of numbers.

**Comment by Aniobodo** [comment]
@huoyaoyuan
No, that is simply making an excuse. The documentation is not complete.

**Comment by huoyaoyuan** [comment]
What sentences do you expect to be included in the documentation?

Documentation has to come with pre-knowledge. It's not expected to replicate too trivial things like elementary school math. Vector intrinsic is a relatively professional area that requires more knowledge than the general part of BCL.

**Comment by Aniobodo** [comment]
@huoyaoyuan 
Sentences like: The value is -1 for signed type and MaxValue for unsigned type.
The above statement is **not elementary school math**.

**Comment by huoyaoyuan** [comment]
It's basic common knowledge far beneath the scope of this particular API set. We may link comparison APIs to `AllBitsSet`, and link `AllBitsSet` to base documentation to explain numbers, then explain the binary representations of numbers there.

**Comment by En3Tho** [comment]
@Aniobodo per link you shared https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.vector128.greaterthan?view=net-7.0
```
Returns
[Vector128<T>](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.vector128-1?view=net-8.0)
A vector whose elements are all-bits-set or zero, depending on if which of the corresponding elements in left and right were greater.
```
It returns presicely what is described in the return section. It returns a mask where bits are either `1` or `0`. I don't see how adding additional information what `AllBitsSet` means for different types is relevant to the Vector apis.

**Comment by Aniobodo** [comment]
@En3Tho 

> a mask where bits are either 1 or 0
The above is clear. Now what about the negativ values returned?

**Comment by huoyaoyuan** [comment]
> Now what about the negativ values returned?

AllBitSet(signed int)  == -1 is trivial pre-knowledge. It's the basic of any course about computer math.
Moreover, the `Vector128` api doesn't inform you to interpret the sign of value. **It doesn't use the contract of `IComparable.CompareTo`**.

**Comment by huoyaoyuan** [comment]
https://en.wikipedia.org/wiki/Two%27s_complement

> Two's complement is the most common [method of representing signed](https://en.wikipedia.org/wiki/Signed_number_representations) (positive, negative, and zero) [integers](https://en.wikipedia.org/wiki/Integer_(computer_science)) on computers

This wikipedia page is the common knowledge that many topics imply, especially the advanced ones.
