### ISSUE TITLE
BinaryFormatter tests are no longer skipped when ran against source-built runtime

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#107534]
When building runtime under the source-build configuration, no functional BinaryFormatter is being built.

Tests that require a functional binary formatter are skipped based on:

https://github.com/dotnet/runtime/blob/aa418fca02995ecfdfe64f89f040fb65ef38557a/src/libraries/System.ObjectModel/tests/ReadOnlyDictionary/ReadOnlyDictionary_SerializationTests.cs#L19

These tests are no longer being skipped on the `main` branch. This causes 1000s of test failures across different test projects.

@adamsitnik I suspect this regressed in https://github.com/dotnet/runtime/pull/106858 by removing the assembly version logic in `DetermineBinaryFormatterSupport`.

cc @ViktorHofer @omajid

**Comment by adamsitnik** [comment]
@ViktorHofer is offline, tagging @ericstj and @carlossanlop who should be able to help, as I am not sure why functional `BinaryFormatter` is not being built for the source-build configuration (I know very little about this config and need help myself).

**Comment by adamsitnik** [comment]
cc @bartonjs js

**Comment by tmds** [comment]
> as I am not sure why functional BinaryFormatter is not being built for the source-build configuration

This is intentional because BinaryFormatter has no use in source-build. We only build the in-box implementation that throws PNSE.

**Comment by am11** [comment]
```diff
diff --git a/Directory.Build.props b/Directory.Build.props
index e887d066f5c..ab8adda9fb2 100644
--- a/Directory.Build.props
+++ b/Directory.Build.props
@@ -473,6 +473,7 @@
   <PropertyGroup Condition="'$(IsTestProject)' == 'true' or '$(IsTestSupportProject)' == 'true' or '$(IsTrimmingTestProject)' == 'true'">
     <!-- we need to re-enable BinaryFormatter within test projects since some tests exercise these code paths to ensure compat -->
     <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
+    <EnableUnsafeBinaryFormatterSerialization Condition="'$(DotNetBuildSourceOnly)' == 'true'">false</EnableUnsafeBinaryFormatterSerialization>
     <!-- don't warn on usage of BinaryFormatter or legacy serialization infrastructure from test projects -->
     <NoWarn>$(NoWarn);SYSLIB0011;SYSLIB0050;SYSLIB0051</NoWarn>
     <!-- don't warn about unnecessary trim warning suppressions. can be removed with preview 6. -->
```

Maybe this should fix it for source bulid?

**Comment by tmds** [comment]
Thanks for the suggestions @am11!

```
+    <EnableUnsafeBinaryFormatterSerialization Condition="'$(DotNetBuildSourceOnly)' == 'true'">false</EnableUnsafeBinaryFormatterSerialization>
```

This would be a good fix if it works. Let me give it a try.

```
#if DOTNET_SOURCE_BUILD
```

Let's try to avoid going this way.

**Comment by ericstj** [comment]
I think we need consistency with how the expectation for support is expressed.

In the past it used to be binary: a platform supported it or it didn't.

Now there are 3 states:
1. Platform doesn't support it.
2. Platform supports it, but the OOB implementation isn't referenced.
3. Platform supports it and the OOB implementation is referenced.

What you don't want to happen is accidentally losing test coverage because you fall into state 2 and treat it like 1. 

Can you state how you want these to be expressed, then adopt them consistently?  I feel like applying different conditions in many places will lead you to a fragile solution.

**Comment by tmds** [comment]
For `System.Numerics.Tensors` there is a separate test project to validate the .NET 8 sources. Perhaps something similar could allow to test the different implementations in upstream CI.

For source-build configuration, we accept lower test coverage. If the OOB implementation isn't buildable, then the tests that depend on its behavior should be skipped.
