### ISSUE TITLE
JsonSerializerOptions.TypeInfoResolver does not apply all the JsonSourceGenerationOptions

### ISSUE THREAD

**Issue by Kumima** [dotnet/runtime#107535]
# May Related
https://github.com/dotnet/aspnetcore/issues/53191
# Code Snippet
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

Todo todo = new(1, Color.Orange, "Walk the dog");
var options = new JsonSerializerOptions { TypeInfoResolver = ApplicationJsonSerializerContext.Default };

Console.WriteLine(JsonSerializer.Serialize(todo, options));
Console.WriteLine(JsonSerializer.Serialize(todo, ApplicationJsonSerializerContext.Default.Todo));

public record Todo(int Id, Color Color, string? Title, DateOnly? DueBy = null, bool IsComplete = false);

public enum Color {
    Red,
    Blue,
    Orange
}

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    UseStringEnumConverter = true)]
[JsonSerializable(typeof(Todo))]
internal partial class ApplicationJsonSerializerContext : JsonSerializerContext;
```

# Behavior
The actual output:
```json
{"Id":1,"Color":"Orange","Title":"Walk the dog","DueBy":null,"IsComplete":false}
{"id":1,"color":"Orange","title":"Walk the dog","due_by":null,"is_complete":false}
```
The expected:
```json
{"id":1,"color":"Orange","title":"Walk the dog","due_by":null,"is_complete":false}
{"id":1,"color":"Orange","title":"Walk the dog","due_by":null,"is_complete":false}
```

# Description
By default, the Enum will be serialized as number value. The outputs indicate that the `JsonSourceGenerationOptionsAttribute.UseStringEnumConverter` works for both. But the `JsonSourceGenerationOptionsAttribute.PropertyNamingPolicy` does not work for `JsonSerializerOptions` way.

Shouldn't the results be the same?

I did not try all the properties, but it seems that if there are `JsonSourceGenerationOptionsAttribute.Converters`, the results will be also different.

Shouldn't all the features defined through `JsonSourceGenerationOptionsAttribute` be applied? If not why `UseStringEnumConverter` is considered.

# Environment
sdk: 8.0.400

**Comment by eiriktsarpalis** [comment]
`JsonSerializerOptions.TypeInfoResolver` is only one aspect of your serializer's configuration. You would additionally need to copy over the rest of the configuration from your generated context. The simplest way to do this is to use the `JsonSerializerOptions` copy constructor:
```C#
var options = new JsonSerializerOptions(ApplicationJsonSerializerContext.Default.Options) 
{ 
    // Additional customization goes here
    WriteIndented = true,
};
```

**Comment by Kumima** [comment]
@eiriktsarpalis
Why still needs that, the `JsonTypeInfo` seems already contains the options, why not just apply the options from `JsonTypeInfo`.

**Comment by eiriktsarpalis** [comment]
Sorry, which `JsonTypeInfo`? In your case you're only passing an `IJsonTypeInfoResolver` which is a different concept.

**Comment by Kumima** [comment]
Doesn't the `IJsonTypeInfoResolver.GetTypeInfo` returns a `JsonTypeInfo`? It should have already provided the options.

**Comment by eiriktsarpalis** [comment]
> Doesn't the `IJsonTypeInfoResolver.GetTypeInfo` returns a `JsonTypeInfo`? It should have already provided the options.

If you take a look of the signature of this method, you'll see that it's a factory for `JsonTypeInfo` that accepts both a `Type` and `JsonSerializerOptions` parameter. If you assign that to a new `JsonSerializerOptions` instance, then that instance will be passed as a parameter.

**Comment by Kumima** [comment]
Well, undertstand now. So this produces the same.
```csharp
JsonSerializer.Serialize(todo, ApplicationJsonSerializerContext.Default.Options);
JsonSerializer.Serialize(todo, ApplicationJsonSerializerContext.Default.Todo);
```

And the reason why ASP.NET Core won't apply `JsonSourceGenerationOptions` is this configures a different option instance.
```csharp
builder.Services.ConfigureHttpJsonOptions(
    options => { options.SerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default); });
```
Well, thanks for the explaination.
