### ISSUE TITLE
Unable to enable server GC in dotnet 8.0.8 on linux

### ISSUE THREAD

**Issue by esskar** [dotnet/runtime#107649]
### Description

I am running a .NET 8.0.8 application on a Kubernetes cluster. To verify the GC configuration, I exposed the output of GC.GetConfigurationVariables() in my application, and I consistently see the gcServer value as false, indicating that server GC is not enabled, despite my attempts to configure it.

### Reproduction Steps

When I run `export` command from with the container i get

```
export ASPNET_VERSION='8.0.8'
export DOTNET_RUNNING_IN_CONTAINER='true'
export DOTNET_VERSION='8.0.8'
export DOTNET_gcServer='1'
```

### Expected behavior

I expect the server GC (gcServer) to be enabled when specified in the configuration.

### Actual behavior

I return the data from GC.GetConfigurationVariables() and it gives me.

```json
{
"ServerGC": false,
"ConcurrentGC": true,
"RetainVM": false,
"NoAffinitize": false,
"GCCpuGroup": false,
"GCLargePages": false,
"HeapCount": 1,
"MaxHeapCount": 0,
"GCHeapAffinitizeMask": 0,
"GCHeapAffinitizeRanges": "",
"GCHighMemPercent": 0,
"GCHeapHardLimit": 402653184,
"GCHeapHardLimitPercent": 0,
"GCHeapHardLimitSOH": 0,
"GCHeapHardLimitLOH": 0,
"GCHeapHardLimitPOH": 0,
"GCHeapHardLimitSOHPercent": 0,
"GCHeapHardLimitLOHPercent": 0,
"GCHeapHardLimitPOHPercent": 0,
"GCConserveMem": 0,
"GCName": "",
"GCDynamicAdaptationMode": 0
},
```

### Configuration

"osArchitecture": "X64",
"osDescription": "Debian GNU/Linux 12 (bookworm)",
"processArchitecture": "X64",
"dotnet": "8.0.8"

pod resources

resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 1000m
      memory: 512Mi
      
`cat myapp.runtimeconfig.json`

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0"
      }
    ],
    "configProperties": {
      "System.GC.Server": true,
      "System.Globalization.Invariant": true,
      "System.Globalization.PredefinedCulturesOnly": true,
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

**Comment by cshung** [comment]
I think it should be `export DOTNET_gcServer=1` without the single quotes?

**Comment by jkotas** [comment]
> cpu: 250m
> cpu: 1000m

Server GC needs more than one core to be performant. If the GC detects one core or less, it will turn-off server GC automatically. You can try increasing the CPU allocation for the container.

**Comment by esskar** [comment]
> > cpu: 250m
> > cpu: 1000m
> 
> Server GC needs more than one core to be performant. If the GC detects one core or less, it will turn-off server GC automatically. You can try increasing the CPU allocation for the container.

changed it to

```yaml
resources:
    requests:
      cpu: 1000m
      memory: 384Mi
    limits:
      cpu: 2000m
      memory: 512Mi
```
which did the trick. thanks.
