### ISSUE TITLE
Runtime Standard - Core CLR / Core RT etc.

### ISSUE THREAD

**Issue by Michael-Baumanns** [dotnet/runtime#1076]
Hello everybody,

First of all I hope this is the right place for my question.

Is there any specification about the expected types / methods who have to be implemented by a runtime implementation like core CLR or core RT? Do you have something like a runtime standard document?

Best regards

Michael

**Comment by huoyaoyuan** [comment]
As I know:
The boundary between runtime and CoreLib isn't concrete. Implementing "special" members in runtime/CoreLib will have different advantages and it may change in the future.
For instance, dotnet/coreclr#27603 moved several members from coreclr to CoreLib to achieve better GC performance.

I suggest treating "runtime+CoreLib" as a tighten group. They are versioned together.

**Comment by Gnbrkm41** [comment]
Not sure if you're thinking about making your custom runtime, but take a look at the whole of the ECMA-335 specification sheet :slightly_smiling_face: it talks about the IL specs and behaviour, and also a few "built-in types". It might be out of date with the implementation with certain things like default implementations of interface members though.

**Comment by ericstj** [comment]
We don't have a defined public contract between the runtime and libraries.  It's an implementation detail that we reserve the right to change as we see fit.  We do document what managed API is exposed by various versions of our frameworks.  This is what is defined by the TargetFramework moniker.

Typically the boundary that the various runtimes like CoreCLR, CoreRT, .NETNative, etc choose to implement is System.Private.Corelib, and react to our changes here over time.  Most of these also share in our sources and build their own version of the sources for System.Private.CoreLib.  This is not a public contract so we provide no guarantees here, but its a fair place to look at if you want to get an idea about what is "implemented" by the run-time.

Let me know if this answers your question.

**Comment by danmosemsft** [comment]
I think this is answered.
