### ISSUE TITLE
I keep getting "Npgsql.NpgsqlException (0x80004005): Exception while performing SSL handshake" when I try to run migrations

### ISSUE THREAD

**Issue by ChristianOConnor** [dotnet/runtime#107600]
I am trying to connect a postgres Db hosted by Digital Ocean to my C# MVC [ASP.NET](http://ASP.NET) .NET 8.0 app. I set up a Postgres Database on Digital Ocean and I can access it with `psql "sslmode=verify-full sslrootcert=C:\\Users\\MY_COMPUTER_USERNAME\\Downloads\\ca-certificate.crt host=PRIVATE_URL_HOST_STRING.ondigitalocean.com port=25060 user=MY_USER_NAME password=MY_PASSWORD dbname=MY_DB_NAME"`. But I can't connect it to my C# MVC [ASP.NET](http://ASP.NET) .NET 8.0 app.  

Here some of the relevant pieces of my code for context.  

Data/ApplicationDbContextFactory.cs:  

    using System;
    using System.IO;
    using System.Net;
    using System.Net.Security;
    using System.Security.Authentication;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Design;
    using Microsoft.Extensions.Configuration;
    using Npgsql;

    namespace Amaranth.Data
    {
        public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
        {
            public ApplicationDbContext CreateDbContext(string[] args)
            {
                // Ensure that the application uses TLS 1.2
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                var builder = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json")
                    .AddEnvironmentVariables();

                var configuration = builder.Build();

                var connectionString = configuration["PostgresConnectionString"]
                    ?? throw new InvalidOperationException("Connection string 'PostgresConnectionString' not found.");

                var rootCertificatePath = configuration["CACertificate"]
                    ?? throw new InvalidOperationException("Root certificate path 'CACertificate' not found.");

                // Ensure SSL Mode is set to Require and include the CA certificate path in the connection string
                connectionString = SetSslMode(connectionString, rootCertificatePath);

                var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
                optionsBuilder.UseNpgsql(connectionString);

                return new ApplicationDbContext(optionsBuilder.Options);
            }

            private string SetSslMode(string connectionString, string rootCertificatePath)
            {
                var builder = new NpgsqlConnectionStringBuilder(connectionString)
                {
                    SslMode = SslMode.Require,
                    RootCertificate = rootCertificatePath, // Path to the CA certificate
                    TrustServerCertificate = true // Trust the server certificate
                };
                return builder.ToString();
            }
        }
    }  

Program.cs:  

    using Amaranth.CustomHttpClients;
    using Amaranth.Data;
    using Amaranth.Models;
    using Azure.Identity;
    using Azure.Security.KeyVault.Secrets;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.EntityFrameworkCore;
    using Azure.Extensions.AspNetCore.Configuration.Secrets;
    using System.Configuration;
    
    var builder = WebApplication.CreateBuilder(args);
    
    // Check if running in design-time for EF commands
    bool isDesignTime = args.Contains("update-database") || args.Contains("ef");
    
    // Fallback values for design-time operations
    if (isDesignTime)
    {
        // Use environment variables for design-time operations
        builder.Configuration["PostgresConnectionString"] = Environment.GetEnvironmentVariable("PostgresConnectionString");
    }
    else
    {
        // Add Azure Key Vault
        var keyVaultEndpoint = new Uri(builder.Configuration["AzureKeyVault:Vault"]);
        builder.Configuration.AddAzureKeyVault(keyVaultEndpoint, new DefaultAzureCredential());
    
        // Secrets should be retrieved from Azure Key Vault
        var secretClient = new SecretClient(keyVaultEndpoint, new DefaultAzureCredential());
        builder.Configuration["PostgresConnectionString"] = secretClient.GetSecret("PostgresConnectionString").Value.Value;
    }
    
    var connectionString = builder.Configuration["PostgresConnectionString"]
        ?? throw new InvalidOperationException("Connection string 'PostgresConnectionString' not found.");
    
    builder.Services.AddDbContext<ApplicationDbContext>(options =>
        options.UseNpgsql(connectionString));
    builder.Services.AddDatabaseDeveloperPageExceptionFilter();
    
    builder.Services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>();
    builder.Services.AddControllersWithViews();
    
    var app = builder.Build();
    
    // Configure the HTTP request pipeline.
    if (app.Environment.IsDevelopment())
    {
        app.UseMigrationsEndPoint();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
        // app.UseHsts(); // Comment out or remove this line to disable HSTS
    }
    
    // app.UseHttpsRedirection(); // Comment out or remove this line to disable HTTPS redirection
    app.UseStaticFiles();
    
    app.UseRouting();
    
    app.UseAuthorization();
    
    app.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
    app.MapRazorPages();
    
    app.Run();  

appsettings.json:  

    {
      "ConnectionStrings": {
        "PostgresConnectionString": "${PostgresConnectionString}"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "AzureKeyVault": {
        "Vault": "https://MY_KEYVAULT_NAME.vault.azure.net/"
      }
    }  

But it fails when I try to run my migrations.  

Look at what happens in the Visual Studio terminal.  

    PM> $env:PostgresConnectionString = "Host=PRIVATE_URL_HOST_STRING.ondigitalocean.com;Port=25060;Username=MY_USER_NAME;Password=MY_PASSWORD;Database=MY_DB_NAME;SSL Mode=Require;Trust Server Certificate=true;"
    PM> Update-Database
    Build started...
    Build succeeded.
    An error occurred using the connection to database 'MY_DB_NAME' on server 'tcp://PRIVATE_URL_HOST_STRING.ondigitalocean.com:25060'.
    Npgsql.NpgsqlException (0x80004005): Exception while performing SSL handshake
     ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'InternalError'.
     ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
       --- End of inner exception stack trace ---
       at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
       at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
       at Npgsql.Internal.NpgsqlConnector.NegotiateEncryption(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, Boolean isFirstAttempt)
       at Npgsql.Internal.NpgsqlConnector.NegotiateEncryption(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, Boolean isFirstAttempt)
       at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
       at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
       at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
       at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
       at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
       at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
       at Npgsql.NpgsqlConnection.Open()
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
       at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
       at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
       at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
       at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.Migrate(String targetMigration)
       at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
    Exception while performing SSL handshake
    PM> 

See how it fails with `Npgsql.NpgsqlException (0x80004005): Exception while performing SSL handshake`?  

This problem only seems to be present when running migrations. I have this C# simple console app.  

    using System;
    using Npgsql;
    
    class Program
    {
        static void Main()
        {
            var connectionString = "Host=PRIVATE_URL_HOST_STRING.ondigitalocean.com;Port=25060;Username=MY_USER_NAME;Password=MY_PASSWORD;Database=MY_DB_NAME;SSL Mode=Require;Trust Server Certificate=true;";
    
            try
            {
                using (var conn = new NpgsqlConnection(connectionString))
                {
                    conn.Open();
                    Console.WriteLine("Connection succeeded!");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Connection failed: {ex.Message}");
            }
        }
    }  

  
And when I run it, it works see:  

    ------------------------------------------------------------------------------
    You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
    Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
    develop and test your applications.
    ------------------------------------------------------------------------------
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/app/bin/Debug/net8.0/testDigitalOceanConnection090124.dll'. Symbols loaded.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/HotReloadAgent/Microsoft.Extensions.DotNetDeltaApplier.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.IO.Pipes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Net.Sockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Net.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Runtime.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/app/bin/Debug/net8.0/Npgsql.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Data.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Transactions.Local.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/app/bin/Debug/net8.0/Microsoft.Extensions.Logging.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Text.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Net.Security.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Security.Cryptography.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Threading.Channels.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Diagnostics.DiagnosticSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Net.NameResolution.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/System.Formats.Asn1.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
    Connection succeeded!
    The program 'dotnet' has exited with code 0 (0x0).  

Do you know what the problem is and/or how to fix it?

**Comment by rzikm** [comment]
The "The message received was unexpected or badly formatted." might happen when app expects TLS records but receives raw unencrypted data.

Since this seems to happen during handshake, capturing the traffic via WireShark/tcpdump could give us useful information.

**Comment by wfurt** [comment]
what platform is this? If Windows, the extra message could be TLS alert. And in the first example you use `ca-certificate.crt ` but I don't see anything about certificates in the c# code.

**Comment by ChristianOConnor** [comment]
> what platform is this? If Windows, the extra message could be TLS alert. And in the first example you use `ca-certificate.crt ` but I don't see anything about certificates in the c# code.

I changed the ApplicationDbContextFactory.cs file to process the CA Certificate. I changed this code in my question but here it is again for reference:  

    using System;
    using System.IO;
    using System.Net;
    using System.Net.Security;
    using System.Security.Authentication;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Design;
    using Microsoft.Extensions.Configuration;
    using Npgsql;

    namespace Amaranth.Data
    {
        public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
        {
            public ApplicationDbContext CreateDbContext(string[] args)
            {
                // Ensure that the application uses TLS 1.2
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                var builder = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json")
                    .AddEnvironmentVariables();

                var configuration = builder.Build();

                var connectionString = configuration["PostgresConnectionString"]
                    ?? throw new InvalidOperationException("Connection string 'PostgresConnectionString' not found.");

                var rootCertificatePath = configuration["CACertificate"]
                    ?? throw new InvalidOperationException("Root certificate path 'CACertificate' not found.");

                // Ensure SSL Mode is set to Require and include the CA certificate path in the connection string
                connectionString = SetSslMode(connectionString, rootCertificatePath);

                var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
                optionsBuilder.UseNpgsql(connectionString);

                return new ApplicationDbContext(optionsBuilder.Options);
            }

            private string SetSslMode(string connectionString, string rootCertificatePath)
            {
                var builder = new NpgsqlConnectionStringBuilder(connectionString)
                {
                    SslMode = SslMode.Require,
                    RootCertificate = rootCertificatePath, // Path to the CA certificate
                    TrustServerCertificate = true // Trust the server certificate
                };
                return builder.ToString();
            }
        }
    }  

I still get the exact same error.  


Also, yes this is Windows 10 which defaults to TLS 1.2. So it's not an error where Windows is trying to force TLS 1.3.

**Comment by wfurt** [comment]
I think packet captures requested by @rzikm would be useful at this point. TLS 1.2 should be easier to debug as most of the handshake is not encrypted.

**Comment by ChristianOConnor** [comment]
> I think packet captures requested by @rzikm would be useful at this point. TLS 1.2 should be easier to debug as most of the handshake is not encrypted.

Okay gotcha, I've never done a packed capture before. I think @rzikm mentioned a program(s) "WireShark/tcpdump?" Are there any resources you recommend on how to do a Visual Studio C# package capture? Should I just go to https://www.wireshark.org/ and follow the docs?

**Comment by wfurt** [comment]
Wireshark is the easiest IMHO. If anything I would suggest to add filter and capture only relevant traffic either by `host 1.2.3.4` or `port 1234`. Github may not let you upload pcap files but it works if you zip them.

**Comment by ChristianOConnor** [comment]
> Wireshark is the easiest IMHO. If anything I would suggest to add filter and capture only relevant traffic either by `host 1.2.3.4` or `port 1234`. Github may not let you upload pcap files but it works if you zip them.

I used Wireshark and capture a ton of stuff but I don't know what to filter for Visual Studio. Is there a port or some unique factor that Visual Studio uses for running migrations to a live db?

**Comment by ChristianOConnor** [comment]
Oh I think I figured out how to get the packets. These are some screenshots of relevant packets that I found.  

![Screenshot (10258)](https://github.com/user-attachments/assets/91adf29f-a60b-4568-82e3-c3c71e07c2ab)
![Screenshot (10259)](https://github.com/user-attachments/assets/cd043e35-e251-4dcc-a661-e7aaa07e6dde)
![Screenshot (10260)](https://github.com/user-attachments/assets/3530bbd1-b6e9-4509-8f15-ccabe4068045)
![Screenshot (10261)](https://github.com/user-attachments/assets/02f5de05-84ad-42c5-852b-13b0011a85b1)

What else do you guys need to see?

**Comment by rzikm** [comment]
Can you compare the contents of the ClientHello TLS message between the successful connection and the failed connection? There has to be something which makes the server error out.

**Comment by ChristianOConnor** [comment]
@rzikm @wfurt I just ran it on my mac and I got a much more verbose error:  

    MYUSERNAME@MYCOMPUTERNAME Amaranth % dotnet ef database update --project Amaranth
    Build started...
    Build succeeded.
    The Entity Framework tools version '8.0.7' is older than that of the runtime '8.0.8'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
    An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
    - EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
    - WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/workloadidentitycredential/troubleshoot
    - ManagedIdentityCredential authentication unavailable. No response received from the managed identity endpoint.
    - Visual Studio Token provider can't be accessed at /Users/MYUSERNAME/.IdentityService/AzureServiceAuth/tokenprovider.json
    - Azure CLI not installed
    - PowerShell is not installed.
    - Azure Developer CLI could not be found.
    Failed executing DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
    CREATE TABLE "__EFMigrationsHistory" (
        "MigrationId" character varying(150) NOT NULL,
        "ProductVersion" character varying(32) NOT NULL,
        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );
    Npgsql.PostgresException (0x80004005): 42501: permission denied for schema public

    POSITION: 14
    at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    at Npgsql.NpgsqlDataReader.NextResult()
    at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
    at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
    at Npgsql.NpgsqlCommand.ExecuteNonQuery()
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
    at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.Migrate(String targetMigration)
    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
    Exception data:
        Severity: ERROR
        SqlState: 42501
        MessageText: permission denied for schema public
        Position: 14
        File: aclchk.c
        Line: 2807
        Routine: aclcheck_error
    42501: permission denied for schema public  

My Azure key store can't be accessed on this computer but it should still work because I set the `PostgresConnectionString` and `CACertificate` in my bash shell with:  

    export PostgresConnectionString="Host=PRIVATE_URL_HOST_STRING.ondigitalocean.com;Port=25060;Username=MY_USER_NAME;Password=MY_PASSWORD;Database=MY_DB_NAME;SSL Mode=Require;Root Certificate=/Users/MYUSERNAME/Downloads/ca-certificate.crt;"
    export CACertificate="/Users/MYUSERNAME/Downloads/ca-certificate.crt"  

Does this more verbose error help you diagnose the problem?

**Comment by vonzshik** [comment]
@ChristianOConnor `permission denied for schema public` means that the postgres user you're logged in doesn't have permissions to create a new table in scheme `public`, it has nothing to do with ssl/tls error.

**Comment by rzikm** [comment]
> Does this more verbose error help you diagnose the problem?

We are diagnosing the TLS handshake error here, anything above (Postgress) is outside of our domain and you would have to create an issue with the developers of the Npsql package.

What about the closer look at TLS Client Hello messages I asked about earlier?
