### ISSUE TITLE
Version 8.0.401 release broke ability to run app with WebDriverAgent from Appium on iOS

### ISSUE THREAD

**Issue by Joost-Jens-Luminis** [dotnet/runtime#107781]
We have been creating tests using Appium for a few months now for our app on Windows, Android and iOS.
Unfortunately, with the release of .Net 8.0.401 and the released iOS workload it broke our ability to test on iOS.

When the WebDriverAgent from Appium is running, it takes to long for the App to start now and it gets killed by the iOS watchdog.
If the WebDriverAgent from Appium is not running, the app is starting up fine and working properly.

With .Net version 8.0.300 (and related workloads) it is still working properly. Unfortunately, as we are using a release version, build in Azure Pipelines, to run the tests we cannot downgrade to an earlier version of the workloads.

The following installation is still working fine with Appium testing on iOS (This is from my PC):
![image](https://github.com/user-attachments/assets/32179b54-1447-423f-b400-2a11496af7b8)

Is there any information on what has changed in net8.0-ios that could have caused this? And how we could work around this issue?

Note: We are a 100% sure Appium didn't cause this, as we hadn't update Appium when the problems started. 
Of course we did try updating Appium and it's drivers to the latest version but to no avail.

**Comment by vitek-karas** [comment]
@rolfbjarne maybe you have some context.
Should we move this to xamarin-macios?

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#21234
