### ISSUE TITLE
Possible regression with [ThreadStatic] in debug builds on .NET 9 RC1

### ISSUE THREAD

**Issue by alexyakunin** [dotnet/runtime#107728]
### Description

One of our tests started to run ~20x slower on .NET 9 RC1, if it's compiled in Debug configuration. 

That's where it spends most of its time:

![image](https://github.com/user-attachments/assets/966ee489-7f6e-476d-a939-9046ffb07606)

There is another branch with similar ~38%, and it's also on the same `ThreadRandom.get_Instance` call.

`ThreadRandom` looks as follows:

```cs
public static class ThreadRandom
{
    [ThreadStatic] private static Random? _instance;

    public static Random Instance {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _instance ??= CreateInstance();
    }

    private static Random CreateInstance()
        => new(Random.Shared.Next());
}
```

What's weird is that all of my attempts to reproduce this perf. regression on isolated console app failed, even though a console app running the code of this specific unit test also manifests the regression.

### Configuration

Windows 11 machine.

### Regression?

Yes, it looks like this is a perf. regression.

### Data

No additional data.

### Analysis

Not sure what it could be.

**Comment by alexyakunin** [comment]
Yes, I'm comparing the perf. of .NET 9 RC1 vs .NET 8 (8.0.8).

**Comment by davidwrighton** [comment]
I've confirmed this is a regression in `CheckRunClassInitThrowing` and several parts of our system could use some checks before doing expensive work. The regression would only likely be visible in a multithreaded application where multiple threads are accessing thread statics, and all of the thread static access was compiled as a DEBUG build, and a few other details..., which is probably why your isolated repro didn't show the slowdown. Our current performance tests do not cover this scenario.

**Comment by alexyakunin** [comment]
Thanks, guys - that was quick!
