### ISSUE TITLE
Unnecessary code in System.Numerics.ConstantHelper ?

### ISSUE THREAD

**Issue by bigworld12** [dotnet/runtime#10773]
most of the methods in [System.Private.CoreLib/shared/System/Numerics/ConstantHelper.cs](https://github.com/dotnet/coreclr/blob/1456a38ed9ee3eda8022b9f162a45334723a0d7a/src/System.Private.CoreLib/shared/System/Numerics/ConstantHelper.cs#L12) are using unsafe/unchecked blocks unnecessarly
shouldn't a simple method like 
```
        [MethodImplAttribute(MethodImplOptions.AggressiveInlining)]
        public static byte GetByteWithAllBitsSet()
        {
            byte value = 0;
            unsafe
            {
                unchecked
                {
                    *((byte*)&value) = (byte)0xff;
                }
            }
            return value;
        }
```
be more like 
```
        [MethodImplAttribute(MethodImplOptions.AggressiveInlining)]
        public static byte GetByteWithAllBitsSet()
        {           
            return (byte)0xff;
        }
```

**Comment by huoyaoyuan** [comment]
No longer applicable - the corresponding files were removed in #42050
