### ISSUE TITLE
[API Proposal]: Add JsonMarshal.GetRawUtf8PropertyName API

### ISSUE THREAD

**Issue by mwadams** [dotnet/runtime#107782]
### Background and motivation

.NET 9.0 Adds the `JsonMarshal` class for low-level access to JSON data.

At the moment, only JSON values are available (including their composite properties with names and values) but not the `JsonProperty` names, directly.

While this is a somewhat less common requirement, it offers significant performance benefits for JSON Schema validation, where e.g. [patternProperties](https://json-schema.org/understanding-json-schema/reference/object#patternProperties) and [propertyNames](https://json-schema.org/understanding-json-schema/reference/object#propertyNames) require the property name for validation purposes, and this cannot be done without allocating a string at present.

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public static class JsonMarshal
{
    // Existing API
    public static ReadOnlySpan<byte> GetRawUtf8Value(JsonElement element);

    // New API
    public static ReadOnlySpan<byte> GetRawUtf8PropertyName(JsonProperty property);
}
```

### API Usage

```csharp
JsonProperty someProperty;

ReadOnlySpan<byte> propertyName = JsonMarshal.GetRawUtf8PropertyName(someProperty);

// Use the span with e.g. rune counting, decoding, etc.
```

### Alternative Designs

With this proposal, we *do not* include quotes wrapping the property name as the property name is *not* a valid JSON value, but always a string (even if it encodes something else in a particular JSON document).

It would be possible to add quotes, but I would consider this "unexpected behavior".

### Risks

`JsonProperty` contains an alternative string backing field that is supported by e.g. the `Name` property, but not e.g. `NameEquals()` and there is no way for a client to determine which is in use in the public API. This API adds an additional method that depends on the property being `JsonElement`-backed.

Otherwise, the risk profile is as for the existing `JsonElement` method.

**Comment by mwadams** [comment]
I have created a [draft pull request](https://github.com/dotnet/runtime/pull/107784) illustrating what might be required to implement this proposal.

**Comment by huoyaoyuan** [comment]
> I have created a [draft pull request](https://github.com/dotnet/runtime/pull/107784) illustrating what might be required to implement this proposal.

Generally this shouldn't be done in prior, especially when the API is trivial to expose something that already exists.

**Comment by mwadams** [comment]
@huioyaoyuan - I realise that it would not normally done prior to API approval but, as I had done it anyway in order to produce a local build for perf-testing experiments in my dependent library, I thought it might help a) illustrate the scope and b) help with thinking through those kind of edge cases.

**Comment by huoyaoyuan** [comment]
> I thought it might help a) illustrate the scope and b) help with thinking through those kind of edge cases.

This doesn't really meet the bar. Only in rare cases the difficulty and complexity of implementation will affect the API shape.

With that said, the draft PR isn't harmful since this API proposal is simple and straight.

**Comment by mwadams** [comment]
@huoyaoyuan - yes; in this case, for me it chiefly served to illustrate the need to consider the quoting/non-quoting of the value returned (which emerged when I implemented the tests) as this was also a consideration for "string" values in the `JsonElement` equivalent.

**Comment by GrabYourPitchforks** [comment]
Just to clarify, this new property returns the raw bytes as they were present on the wire, and it's not guaranteed to return the canonical (I escaped or minimally escaped) representation of the name, right?

(If so, this should be documented, as it means a straight byte-for-byte comparison is not a legal way of checking for equality.)

**Comment by eiriktsarpalis** [comment]
Correct, which is also true of the existing `GetRawUtf8Value` method as well.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Runtime.InteropServices;

public static partial class JsonMarshal
{
    // Existing API
    // public static ReadOnlySpan<byte> GetRawUtf8Value(JsonElement element);

    // New API
    public static ReadOnlySpan<byte> GetRawUtf8PropertyName(JsonProperty property);
}
```

**Comment by mwadams** [comment]
I'm not sure how to associate that PR directly with this issue and/or request review - I don't seem to have permission for the usual mechanisms.

**Comment by terrajobst** [comment]
> I'm not sure how to associate that PR directly with this issue and/or request review - I don't seem to have permission for the usual mechanisms.

FTFY
