### ISSUE TITLE
COM object lifetime is subject to Windows rundown policy (6 minute idle)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#10777]
Call CoMarshalInterface with MSHLFLAGS_TABLESTRONG (as opposed to MSHLFLAGS_NORMAL) to avoid COM rundown timeouts.

https://github.com/dotnet/coreclr/blob/8e48db2c113052ef18cdafb43e114a8633864ec0/src/vm/comcache.cpp#L178

The lifetime issue tends to hit very large applications.  Viable workarounds are: 1) use the COM objects regularly, or 2) avoid the .NET COM cache and get the raw IntPtr then call GetUniqueObjectForIUnknown.

**Comment by AaronRobinsonMSFT** [comment]
An alternative to this would be leverage the [GIT](https://docs.microsoft.com/windows/win32/com/when-to-use-the-global-interface-table) or [`IAgileReference`](https://docs.microsoft.com/windows/win32/api/objidl/nn-objidl-iagilereference) type - depending on platform support.

**Comment by AaronRobinsonMSFT** [comment]
Changing the built-in COM support semantics is something we are attempting to avoid. A source generator with needed semantics could be create using the [`ComWrappers`](https://github.com/dotnet/runtime/issues/1845) API if this is causing issues.
