### ISSUE TITLE
JSON Serialization on records with a Primary Constructor with Properties created from the constructor parameter definition works fine; auto-generated properties does not work unless the properties are decorated with JsonIgnore.

### ISSUE THREAD

**Issue by simkin2004** [dotnet/runtime#107703]
### Description

record class are reference types with Value-type Equals semantics.

How I define that record syntactically should not determine whether it is serializable or not.

This code does not serialize.
<code>
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
    public DateOnly Date { get; } = date;
}
</code>

This code serializes.
<code>
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly Date)
{}
</code>

This code serializes.
<code>
    public record WeatherForecastRecordWithJsonignore(DateOnly date)
    {
        [JsonIgnore]
        public DateOnly Date { get; set; } = date;
    }
</code>

This code serializes.
<code>
    public class WeatherForecastRecordWithJsonignore(DateOnly date)
    {
        public DateOnly Date { get; set; } = date;
    }
</code>

### Reproduction Steps

I can provide a WeatherForecast ASP.NET Web API that demonstrates the problem and the behavior that it causes is a 406-NotAcceptable in ASP.NET .

This code does not serialize.
<code>
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
    public DateOnly Date { get; } = date;
}
</code>

This code serializes.
<code>
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly Date)
{}
</code>

This code serializes.
<code>
    public record WeatherForecastRecordWithJsonignore(DateOnly date)
    {
        [JsonIgnore]
        public DateOnly Date { get; set; } = date;
    }
</code>

This code serializes.
<code>
    public class WeatherForecastRecordWithJsonignore(DateOnly date)
    {
        public DateOnly Date { get; set; } = date;
    }
</code>

### Expected behavior

All examples serialize properly.

### Actual behavior

record with primary constructor and user-defined properties with JsonIgnore does not serialize properly.

### Regression?

Unknown whether earlier fixes patched this problem.  Unable to install earlier releases as I do not have access to install them.

### Known Workarounds

Use JsonIgnoreAttribute.
Use class instead of record and write value equality semantics.
Use record with auto-created properties from the constructor and suppress styling issues because it uses the "wrong" casing for constructor parameters.

### Configuration

.NET 8.0 + ASP.NET Core
All OS
All architectures
Not specific to the configuration.

**Comment by eiriktsarpalis** [comment]
The reason why you're seeing this issue is because you're defining a positional record, which means that the `DateOnly date` declaration [compiles to both a constructor parameter and a property](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgAQCcCmBjAey2AwHUcBDAFwAscsAxI/CgZyoCV8jhSBLWgAUsfALYUsATwDCBAHbssAVzxUiAQTnBhBAA70qfHKwAUAEWo4A8nIA2kjMEsBKZAG9kGL1/QYLVazsHfxwMNwwAcxwqAG4MAF8MAF5HSxjkeKA===). The serializer subsequently fails because of the ambiguity between the `date` and `Date` properties, which is by design behavior. You can work around the issue either by eliminating the secondary property:

```C#
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly Date);
```

or use a regular class with a primary constructor which doesn't result in a public property being generated:

```C#
public class WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
    public DateOnly Date { get; } = date;
}
```

**Comment by chrisoverzero** [comment]
> How I define that record syntactically should not determine whether it is serializable or not.

This is simply not the case.

```csharp
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
  public DateOnly Date { get; } = date;
}
```

…is different from:

```csharp
public class WeatherForecastClass(DateOnly date)
{
  public DateOnly Date { get; set; } = date;
}
```

…in a very important way. The constructor parameters to `record`s become properties. When trying to serialize, the error message is one of these:

> Members 'date' and 'Date' on type 'WeatherForecastRecordWithPrimaryConstructorAndProperties' cannot both bind with parameter 'date' in the deserialization constructor.

> The JSON property name for 'WeatherForecastRecordWithPrimaryConstructorAndProperties.date' collides with another property.

(Depending on the settings to the serialization options.) This is because the parameter `date` has become a property named exactly that, `date`. If you'd like to use a `record class`, the most ergonomic use is likely one of these:

```csharp
public record class WeatherForecast(DateOnly Date);

public record class WeatherForecast
{
  public DateOnly Date { get; init; }
}
```

**Comment by simkin2004** [comment]
When you apply the Principle of Least Astonishment, does it make sense that 
<code>
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
     public DateOnly Date { get; } = date;
}
</code>

compiles to effectively:

<code>
public record WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
   public WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
   {
       this.date = date;
       this.Date = date;
   }
    public DateOnly date { get; private set;}
    public DateOnly Date { get; private set;} 
}
<code>

while 
<code>
public *class* WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
     public DateOnly Date { get; } = date;
}
</code>

compiles to effectively:

<code>
public *class* WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
{
   public WeatherForecastRecordWithPrimaryConstructorAndProperties(DateOnly date)
   {
       this.Date = date;
   }
    public DateOnly Date { get; private set;} 
}
<code>

**Comment by chrisoverzero** [comment]
When I apply the Principle of Least Astonishment, I’m amazed that _any_ computer program works.

That a `record class` and a `class` behave differently is comparatively not a surprise at all. They’re each doing what they were designed to do.

> Use record with auto-created properties from the constructor and suppress styling issues because it uses the "wrong" casing for constructor parameters.

The overwhelming convention is to make these constructor parameters PascalCased. Can I ask, why is this a blocker for you?

**Comment by simkin2004** [comment]
My point is not that they 'behave' differently, it is that a -reference type- COMPILES differently for the same syntax and that the compilation difference is -not- documented in the record keyword documentation.

A "record class" is a special subtype of a class.
If I apply Liskov's notion, then the compiler (and the execution) behavior should be the same for a record and a class.
If you wanted "record" to have completely different compiler semantics, I would argue that it should be a separate keyword, clear and separate from "class" or "struct" which could have very well-defined semantics.

Ultimately, the issue isn't a blocker for me.  I've found (and published above) several different workarounds, but wanted to get the "why".  While I still don't find the "why" compelling, it was how it was done.

As for analyzers, I will have to get special permission to use the pre-release versions of the analyzers that support this as some of the ones my team/company uses have not had a "normal" release in several years.

Thank you for the explanation.  I will close the issue.
