### ISSUE TITLE
Make all compiled strings default utf8

### ISSUE THREAD

**Issue by Mrgaton** [dotnet/runtime#107720]
i see absolutely no point of using utf16 when on utf8 can write the same things with using fewer space, maybe not add this option as default but be able at least to change it

**Comment by huoyaoyuan** [comment]
UTF-8 strings and UTF-16 strings are operated differently. Existing code can't be changed silently.

> utf8 can write the same things with using fewer space

This is only true for ASCII range. Although ASCII is popular, there are other cases. Most Windows APIs are using UTF-16. Using UTF-8 will require additional transcoding on Windows.

You can use the `""u8` literal in C# for cases you need UTF-8.

**Comment by tannergooding** [comment]
Yep, UTF-8 is really only smaller for ASCII and same size as UTF-16 for a small subset, for the rest of the Unicode domain it is larger. 

Additionally, for non-ascii data it is often much less efficient to operate on even for the same size due to the more complex decoding mechanism. In many cases when operating on UTF-8 data that is known to not be ASCII exclusive, it is faster to transcode to UTF-16 and operate on the UTF-16 than it is to operate on the UTF-8 data directly.

It is not so simple as "smaller == better/faster" and there are a lot of tradeoffs to consider. These tradeoffs can also differ based on the target platform, ABI, or scenario under which you're operating.

**Comment by Mrgaton** [comment]
The problem with ""u8 is that you can't use them with normal string function args. And the problem is that mayority of strings are just ASCII, also all you can write with utf8 you can do it on utf16. Don't tell me that you can't just transcode it to memory to utf16 if needed cause is the same but adding a 0 for normal caràcters and when FF just add next 2 bytes.

**Comment by hez2010** [comment]
> The problem with ""u8 is that you can't use them with normal string function args. 

We may have a `U8String` type for this in the future.

**Comment by neon-sunset** [comment]
> We may have a `U8String` type for this in the future. 

Do you mean in CoreLib or the project I'm (very slowly) working on? 😅

**Comment by huoyaoyuan** [comment]
> The problem with ""u8 is that you can't use them with normal string function args.

You can't use anything other than UTF-16 string with functions accepting `string`. They do interprets strings in UTF-16.

> Don't tell me that you can't just transcode it to memory to utf16 if needed

Transcoding is an expensive operation, no matter how trivial the algorithm is. It involves memory allocation/pooling.

**Comment by hez2010** [comment]
> Do you mean in CoreLib or the project I'm (very slowly) working on?

We have one in the runtimelab, it is just that we currently have no plan of bringing it into CoreLib.

**Comment by neon-sunset** [comment]
> We have one in the runtimelab, it is just that we currently have no plan of bringing it into CoreLib.
 
Right, that one. It needs quite a lot of work still. Would be a great opportunity to break away from the current copying slicing as well if it is ever brought back, but that's likely too much of a change for the core of the ecosystem...

**Comment by huoyaoyuan** [comment]
> I'm just asking to save them on the disk as utf8 and then code it to utf16

> Is that expensive when jit loads assembly to transcode it?

The size for transcoding logic will probably exceed the space saved.

> and not by default add a compiler option or something

A compiled .NET assembly is in publicly specified format of 20+ years history. Any change for the format will be huge for the whole ecosystem.

**Comment by huoyaoyuan** [comment]
Additionally, when proposing for saving, you need to show there is something to save first. I only except the size of string table to be significant for facade assemblies that delegates everything to elsewhere. Those assemblies are typically only a few KBs.
