### ISSUE TITLE
ClientWebSocket ignoring custom SPN/UPN for Kerberos authentication

### ISSUE THREAD

**Issue by iconics-milan** [dotnet/runtime#107733]
### Description

In .NET Framework, it is possible to specify a custom SPN or UPN using the AuthenticationManager.CustomTargetNameDictionary. This custom SPN/UPN is respected by the ClientWebSocket when connecting to an authenticated endpoint, and enables the ClientWebSocket to perform proper Kerberos authentication when the target endpoint does not use the customary HTTP/host as its SPN.

In .NET 8, the CustomTargetNameDictionary seems to get ignored.

### Reproduction Steps

It is necessary to have a domain-joined computer, and run the following code under a regular domain user account. It is necessary to fill the UPN of the user account into the code. When the code is run under .NET 4.8.1, it correctly prints Kerberos. When run inder .NET 8, it prints NTLM.

```
internal class Program
{
    static async Task Main(string[] args)
    {
        var upn = "**put your user name in UPN form here**";
        var uri = "http://localhost:44444/";

        var s = Server(uri);
        await Client(uri, upn);
        var authType = await s;
        Console.WriteLine(authType);
    }

    static async Task<String> Server(String uri)
    {
        using (var listener = new HttpListener())
        {
            listener.AuthenticationSchemes = AuthenticationSchemes.Negotiate;
            listener.Prefixes.Add(uri);
            listener.Start();

            var ctx = await listener.GetContextAsync();
            var authType = ctx.User?.Identity.AuthenticationType;
            var wsCtx = await ctx.AcceptWebSocketAsync(null);
            await wsCtx.WebSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, null, CancellationToken.None);
            return authType;
        }
    }

    static async Task Client(String uri, String upn)
    {
        AuthenticationManager.CustomTargetNameDictionary[uri] = upn;

        var webSocket = new ClientWebSocket();
        webSocket.Options.UseDefaultCredentials = true;
        await webSocket.ConnectAsync(new Uri(uri.Replace("http", "ws")), CancellationToken.None);
        await webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, null, CancellationToken.None);
    }
}
```

### Expected behavior

The code should perform Kerberos authentication in .NET 8.

### Actual behavior

The code falls back to NTLM.

### Regression?

Yes.

### Known Workarounds

None known.

### Configuration

.NET 8
Windows 11
x64

**Comment by rzikm** [comment]
The `AuthenticationManager` class is no-op on .NET Core, since .NET 9 will be properly marked as obsolete.

.NET (Core) currently does not support setting custom SPN/UPN, this is tracked also by https://github.com/dotnet/runtime/issues/25320

**Comment by CarnaViire** [comment]
Triage: As answered above, custom SPN/UPN is currently not supported, which is tracked by https://github.com/dotnet/runtime/issues/25320. Closing.
