### ISSUE TITLE
SpawnBrowserAsync on Windows

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#107771]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=806657
Build error leg or test failing: Workloads-NoWebcil-NoFingerprint-ST-Wasm.Build.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/107746

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Exception : Failed to launch browser after 3 attempts",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=806657
**Error message validated:** `[System.Exception : Failed to launch browser after 3 attempts`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/12/2024 10:35:30 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
@ilonatommy please take a look

**Comment by ilonatommy** [comment]
It looks that delay increase mitigated the issue. In case of more problems, consider investigating the Windows image details we're using on CI: https://github.com/microsoft/playwright/issues/32897. The last weeks failures are on net9, the fix will be backported there to clean to count

**Comment by ilonatommy** [comment]
It hasn't been seen for months, we can consider https://github.com/dotnet/runtime/pull/108474 was the fix.
