### ISSUE TITLE
[.NET 9.0 RC1] Inline Array's cannot be deserialized by System.Text.Json

### ISSUE THREAD

**Issue by iamcarbon** [dotnet/runtime#107715]
### Description

We have an inline array type that implements a custom JsonConverter. This works on .NET8.0, but throws System.NotSupportedException on .NET 9.0. It looks like a System.Text.Json may be attempting to real Equals or GetHashCode on .NET 9.0.

### Reproduction Steps

Serializing an inline array with a custom converter fails.

```csharp
Quadrilateral quad = [
    new(0, 3),
    new(0, 8),
    new(3, 9),
    new(12, 3),
];

var data = JsonSerializer.SerializeToUtf8Bytes(quad);          
```

```csharp

[InlineArray(4)]
[CollectionBuilder(typeof(Quadrilateral), "Create")]
[JsonConverter(typeof(QuadrilateralConverter))]
public struct Quadrilateral
{
    private Point _0;

    public static Quadrilateral Create(ReadOnlySpan<Point> elements)
    {
        var box = new Quadrilateral();

        elements.CopyTo(box);

        return box;
    }
}

internal sealed class QuadrilateralConverter : JsonConverter<Quadrilateral>
{
    public override Quadrilateral Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var elements = reader.GetString()!.Split(' ');

        return [
            Point.Parse(elements[0]),
            Point.Parse(elements[1]),
            Point.Parse(elements[2]),
            Point.Parse(elements[3])
        ];
    }

    public override void Write(Utf8JsonWriter writer, Quadrilateral value, JsonSerializerOptions options)
    {
        using var sb = new ValueStringBuilder();

        foreach (var item in value)
        {
            if (sb.Length > 0)
            {
                sb.Append(' ');
            }

            sb.AppendSpanFormattable(item.X);
            sb.Append(',');
            sb.AppendSpanFormattable(item.Y);
        }

        writer.WriteStringValue(sb.AsSpan());
    }
}             
```

### Expected behavior

This works on .NET 8.0, but fails on .NET 9.0 RC1.

### Actual behavior

An exception is throw. 

```
System.NotSupportedException : Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid. 

---- System.NotSupportedException : Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid.

  Stack Trace: 
ThrowHelper.ThrowNotSupportedException(WriteStack& state, Exception innerException)
JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
JsonSerializer.WriteBytes[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
JsonSerializer.SerializeToUtf8Bytes[TValue](TValue value, JsonSerializerOptions options)
DocumentTests.CanSerialize() line 76
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

on .NET 9.0 RC1

### Regression?

Yes. This works in .NET 8.0.

### Known Workarounds

This works with a regular non-inline structure.

### Configuration

.NET 8.0 works
.NET 9.0 RC1 (Windows) does not work.

**Comment by jkotas** [comment]
> System.NotSupportedException : Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid.

This error message is fallout intentional breaking change: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/inlinearrayattribute .

Your repro is incomplete and it won't compile, so it is hard to tell why your custom converter ends up calling the Equals or GetHashCode.

**Comment by iamcarbon** [comment]
I should have caught this breaking change notice.

Turns out this behavior was caused using a JsonIgnore condition (which obviously calls the default function).

 [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
 public Quadrilateral Bounds { get; set; }

Thanks for your trouble! Closing, per design!
