### ISSUE TITLE
Provide a debug clr or enable debug message in the binaries?

### ISSUE THREAD

**Issue by rmannibucau** [dotnet/runtime#107884]
Hi,

Building from sources can be tricky and long, I guess it could benefit everyone to have a debug build available somewhere (dotnet-install?).
Idea is to be able to enable log messages (pal events for ex) very easily without having to build from sources.

**Comment by jkotas** [comment]
> pal events for ex

I assume you mean `ENTRY`/`LOGEXIT` macros under https://github.com/dotnet/runtime/tree/main/src/coreclr/pal. What is the problem that you are trying to solve with these?

We have been slowly working on eliminating this PAL (we call it Win32 PAL - it is a partial Windows API emulator). `src/coreclr/pal` is getting smaller and used in fewer spots with every release, and it should disappear in the fullness of time.

**Comment by rmannibucau** [comment]
Hi  @jkotas , yes exactly this is these macro I'm trying to "see"/materialize.
I'm trying to follow the path of an unhandled exception in a thread (not "main" one) which lead to exiting the application.
The debug messages show it quite easily.
I tried dotnet-trace/counters (I assume these are the replacement?) but since the app exists "by itself" the data were either not relevant or corrupted (dotnet-trace was almost always corrupted).
So ended up building my own runtime but this is a lot of work just to get debug logs - an env var/runtime flag would be so neat coming from java world!

**Comment by jkotas** [comment]
Could you please tell us more about the specific PAL debug messages that you found useful and how they helped you to diagnose the problem?

**Comment by rmannibucau** [comment]
More or less what's in excep.cpp, higher level I don't have any attachment to PAL messages but assume you forget to set an unhandled exception handler on your console app, you start a thread, this one throws an exception (unexpected so unhandled) and the app crashes unexpectedly without any message, this is really bothering and hard to debug with the options I mentionned so any alternative would be great (not requiring sos or gdb, a simple "debug log" mode is great there)

**Comment by jkotas** [comment]
The unhandled exceptions should produce a message error message and stacktrace to give you an idea what went wrong. Have you figured out why there was no error message in your case?

**Comment by rmannibucau** [comment]
> Unhandled exceptions should produce an error message and stacktrace to give you an idea what went wrong. Have you figured out why there was no error message in your case?

not when Thread.Interrupt is called

**Comment by jkotas** [comment]
> not when Thread.Interrupt is called

It is a bug. This problem is tracked by https://github.com/dotnet/runtime/issues/107594

**Comment by jkotas** [comment]
> Here is a (partial) capture

Ah ok, this is the VM logging. This VM logging is partially enabled in release builds as stresslog. Stresslog is a "flight data recorder" that captures recent process events in a circular buffer. Unlike printing all messages to the console, the logging into a circular buffer is very fast. If the process crashes or hangs, you can get print the messages using `dotnet-dump` tool or using a debugger. Here is how you can see it in action:

```
C:\test>set DOTNET_DbgEnableMiniDump=1

C:\test>set DOTNET_StressLog=1

C:\test>bin\Debug\net9.0\test.exe
[createdump] Writing minidump with heap for process 22904 to file C:\Users\jkotas\AppData\Local\Temp\dump.22904.dmp
[createdump] Dump successfully written in 1152ms

C:\test>dotnet tool install --global dotnet-dump
Tool 'dotnet-dump' is already installed.

C:\test>dotnet-dump analyze C:\Users\jkotas\AppData\Local\Temp\dump.22904.dmp
Loading core dump: C:\Users\jkotas\AppData\Local\Temp\dump.22904.dmp ...
Ready to process analysis commands. Type 'help' to list available commands or 'help [command]' to get detailed help on a command.
Type 'quit' or 'exit' to exit the session.
> dumplog
Attempting to dump Stress log to file 'StressLog.txt'
Writing to file: StressLog.txt
Stress log in module 0x00007FFB5ABD0000
Stress log address = 0x00007FFB5B0323B0
.
.................................
SUCCESS: Stress log dumped
> exit
```

StressLog.txt is going to have a log that is similar to your capture. You can further customize the length and verbosity of the log using addional stresslog settings (look for stresslog in https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/clrconfigvalues.h).

**Comment by rmannibucau** [comment]
All good for me - in marticular if the linked issue is fixed which is even better.
We can close this one I think.
Thanks a lot.
