### ISSUE TITLE
Reduce the scope of the CCW cache or consider lock free

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#10787]
In processes that heavy use of COM can have considerable contention on the CCW cache lock.  Currently the lock is for the whole process (eg. per-appdomain).

**Comment by AaronRobinsonMSFT** [comment]
Confirmed @jkoritzinsky's observation. I am going to close this issue since the global lock has changed. We can revisit if we hear additional user feedback.

N.B. The new CCW management API will not suffer from this contention - see https://github.com/dotnet/runtime/pull/32091.
