### ISSUE TITLE
Support using COM Wrappers generators for UnmanagedType.IUnknown

### ISSUE THREAD

**Issue by dongle-the-gadget** [dotnet/runtime#107864]
### Description
It is common in various places to use `UnmanagedType.IUnknown` (https://github.com/search?q=UnmanagedType.IUnknown&type=code). As such, allowing objects that are marshalled using `UnmanagedType.IUnknown` to take advantage of COM Wrapper generators would take the transition to generated COM easier.

### Usage example
```cs
[LibraryImport("mynativelib.dll")]
public static partial int GetComObject([MarshalAs(UnmanagedType.IUnknown)] out object? iUnknown);

[GeneratedComInterface]
[Guid("123e4567-e89b-12d3-a456-426614174000")]
public partial interface ITestInterface
{
    void Method();
}

// The following should work
GetComObject(out object? foo);
if (foo is ITestInterface queried)
    queried.Method();
```

### Open questions
I suppose one cause of concern is that we would need to support both the built-in COM interop mechanism and source-generated mechanism. 

My personal solution is to:
1. Only allow source-generated interfaces to work when the parameter is processed by another source-generated P/Invoke or COM signature, such as this:
```cs
[LibraryImport("mynativelib.dll")]
public static partial int GetComObject([MarshalAs(UnmanagedType.IUnknown)] out object? iUnknown); // iUnknown here supports source-generated COM and built-in COM interop.

[DllImport("mynativelib.dll")]
public static partial int GetComObject([MarshalAs(UnmanagedType.IUnknown)] out object? iUnknown); // iUnknown here only supports built-in COM interop.

[GeneratedComInterface]
[Guid("123e4567-e89b-12d3-a456-426614174000")]
public partial interface ITestInterface
{
    void Method([MarshalAs(UnmanagedType.IUnknown)] out object? iUnknown); // iUnknown here supports source-generated COM and built-in COM interop.
}

[ComInterop]
[Guid("123e4567-e89b-12d3-a456-426614174000")]
public nterface ITestInterface
{
    void Method([MarshalAs(UnmanagedType.IUnknown)] out object? iUnknown); // iUnknown here only supports built-in COM interop.
}
```
2. Modify the existing internal [`ComObject`](https://github.com/dotnet/runtime/blob/0154a2f3403d94ea6d6f93f5a774b6e366969e0a/src/libraries/System.Runtime.InteropServices/src/System/Runtime/InteropServices/Marshalling/ComObject.cs) type to also allow casting to built-in COM interop types.

**Comment by reflectronic** [comment]
`UnmanagedType.Interface` is already supported by the source generator, and it behaves the same as `UnmanagedType.IUnknown` when applied to an `object` parameter. So, this can be used to work around the limitation in the meantime.

**Comment by jkoritzinsky** [comment]
The ComObject type does support built-in COM interop with an opt-in feature switch. This switch is opt-in as it isn't supported in trimming or AOT scenarios and we wanted the default experience to work from the start.

Add the following line to your app's project file to enable the feature:

`<EnableGeneratedComInterfaceComImportInterop>true</EnableGeneratedComInterfaceComImportInterop>`

This will enable you to cast to a built-in COM interface from a GeneratedComInterface instance that wraps a native COM object.
