### ISSUE TITLE
Wrong DateTimeFormat.LongTimePattern in .NET 8 when running in Linux containers

### ISSUE THREAD

**Issue by kvasserman** [dotnet/runtime#107842]
### Description

After upgrading our application from .NET 6 to .NET 8, I've noticed some weird characters are being produced by DateTime.ToString(), but only when the application runs in Linux containers. After some digging with some test code, I can reliably reproduce the issue in both Debian and Alpine containers. Code that runs directly on Windows or Linux machines does not exhibit the same behavior. 

By simply outputting CultureInfo.CurrentCulture.DateTimeFormat.LongTimePattern via Console.WriteLine(), I see the following results:

CurrentCulture in all tests is set to "en_US"
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is set to false in all container images

Windows + .NET 6: "h:mm:ss tt"
Windows + .NET 8: "h:mm:ss tt"

Ubuntu + .NET 6: "h:mm:ss tt"
Ubuntu + .NET 8: "h:mm:ss tt"

Container (mcr.microsoft.com/dotnet/runtime:6.0-alpine): "h:mm:sstt" (NOTE: there is no space after seconds for some reason)
Container (mcr.microsoft.com/dotnet/runtime:8.0-alpine): "h:mm:ss tt" (NOTE: there is, what looks like a space after seconds, but it's actually a char with code: 8239)

Container (mcr.microsoft.com/dotnet/runtime:6.0): "h:mm:ss tt" (NOTE: there is a space after seconds, which matches results from Windows and Ubuntu machines, but is different from Alpine container)
Container (mcr.microsoft.com/dotnet/runtime:8.0): "h:mm:ss tt" (NOTE: there is, what looks like a space after seconds, but it's actually a char with code: 8239. This is the same as with Alpine container)

I've tested .NET 7 too and behavior everywhere matches .NET 6.

Here is an example of my test program output running in alpine dotnet 8 container:

Is Container: true
OS: Alpine Linux v3.20
Framework: 8.0.8
Culture: en-US
Time Format: 'h:mm:ss tt'
char 01: h -> 104
char 02: : -> 58
char 03: m -> 109
char 04: m -> 109
char 05: : -> 58
char 06: s -> 115
char 07: s -> 115
**char 08:   -> 8239**
char 09: t -> 116
char 10: t -> 116

You can see char 08 is 8239, but should be 32 (space) as it is on other platforms.

Because the format suppose to be coming from ICU libraries (data), I thought that something maybe different in ICU data. I have compared sha256sum of /usr/share/icu/74.2/icudt74l.dat on runtime:6.0-alpine and runtime:8.0-alpine images and they are identical.

Moreover, I've ran plain alpine:3.20 container and manually installed both dotnet6-sdk and dotnet8-sdk in the same container, to verify it's not an environmental issue. In the same container .NET 6 and .NET 8 produce different results (the same results as described above).

At this point it feels like a bug in .NET 8. Although, the difference in format of .NET 6 between Windows/Ubuntu and Alpine container is also could be problematic for applications that maybe running components (services) on both platforms and exchange DateTime info via JSON as strings.

But the most worrying problem I think is a strange char in the middle of the time pattern.

### Reproduction Steps

Create a new console project with the following content of Program.cs:

`
using System.Globalization;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;

Console.WriteLine("Is Container: {0}", Environment.GetEnvironmentVariable("DOTNET_RUNNING_IN_CONTAINER") == "true" ? "true" : "false");

if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    Console.WriteLine("OS: {0}", RuntimeInformation.OSDescription);
else
    Console.WriteLine("OS: {0}", Regex.Match(File.ReadAllText("/etc/os-release"), "(?<=PRETTY_NAME=\")[^\"]+").Groups[0].Value);

Console.WriteLine("Framework: {0}", Environment.Version.ToString());

CultureInfo culture = CultureInfo.CurrentCulture; 

Console.WriteLine("Culture: {0}", culture.Name);

string time = culture.DateTimeFormat.LongTimePattern; 
Console.WriteLine("Time Format: '{0}'", culture.DateTimeFormat.LongTimePattern);

for(int i = 0; i < time.Length; i++) 
{
    char c = time[i];
    Console.WriteLine("char {0:00}: {1:X} -> {2}", i + 1, c, (int)c);
}
`

Create a Dockerfile similar to this:
`
FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine AS base
WORKDIR /app

# # Install cultures (same approach as Alpine SDK image)
RUN apk add --no-cache icu-libs tzdata

# # # Disable the invariant mode (set in base image)
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

# USER app
# FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG configuration=Release
WORKDIR /src
COPY ["testdate.csproj", "./"]
RUN dotnet restore "testdate.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "testdate.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "testdate.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "testdate.dll"]

`

Build and run the container and observe the following output:

Is Container: true
OS: Alpine Linux v3.20
Framework: 8.0.8
Culture: en-US
Time Format: 'h:mm:ss tt'
char 01: h -> 104
char 02: : -> 58
char 03: m -> 109
char 04: m -> 109
char 05: : -> 58
char 06: s -> 115
char 07: s -> 115
**char 08:   -> 8239**
char 09: t -> 116
char 10: t -> 116

### Expected behavior

The above steps should result in this output:

Is Container: true
OS: Alpine Linux v3.20
Framework: 8.0.8
Culture: en-US
Time Format: 'h:mm:ss tt'
char 01: h -> 104
char 02: : -> 58
char 03: m -> 109
char 04: m -> 109
char 05: : -> 58
char 06: s -> 115
char 07: s -> 115
**char 08:   -> 32**
char 09: t -> 116
char 10: t -> 116

Or, at the very least, the same output as .NET 6 (which is no space between "ss" and "tt")

### Actual behavior

The actual output is this:

Is Container: true
OS: Alpine Linux v3.20
Framework: 8.0.8
Culture: en-US
Time Format: 'h:mm:ss tt'
char 01: h -> 104
char 02: : -> 58
char 03: m -> 109
char 04: m -> 109
char 05: : -> 58
char 06: s -> 115
char 07: s -> 115
**char 08:   -> 8239**
char 09: t -> 116
char 10: t -> 116

### Regression?

Weird char doesn't appear in .NET 6 and .NET 7.

**Comment by Clockwork-Muse** [comment]
`int 8239` is `hex 202f` which is the [Unicode narrow non-breaking space](https://unicode-explorer.com/c/202F), so the character isn't actually "odd".

The runtime maintains no formatting data on its own, and by default pulls the data from the host OS, if it exists.  On both Windows and Linux, this data comes from ICU, but this is configuration, and **will** differ between operating systems and individual machines (among other situations).  Docker containers usually do not include this information, so a "default" is used.  This data is updated multiple times a year.

If this is part of formatting code for direct user display, generally you _SHOULD NOT_ inspect the results of the formatting and just output straight to the user.
If this is part of interchange code, you _SHOULD_ always explicitly format with the Invariant culture (and optionally specify an explicit format string).

Closing as by-design

**Comment by kvasserman** [comment]
@Clockwork-Muse Thank you for your response. I understand that it suppose to be coming from ICU. How do you explain the fact that in exactly the same container .NET 6 and .NET 8 output different strings for the LongTimePattern (one with the space and the other one with NNBSP)?

**Comment by kvasserman** [comment]
For anyone who comes across this, I have just found that Microsoft's ICU team merged a commit in their latest release ([MS-ICU 72.1.0.3](https://github.com/microsoft/icu/releases/tag/v72.1.0.3) in 2023) that reverts English locales to use normal space instead of NNBSP in time formats. So they did find it to be problematic.

https://github.com/microsoft/icu/pull/134

I have also confirmed that NNBSP is indeed in the latest ICU code: https://github.com/unicode-org/icu/blob/release-75-rc/icu4c/source/data/locales/en.txt

This means that .NET 8 actually gets it as is from ICU, but .NET 6 somehow strips NNBSP from the format (which explains the complete lack of space between seconds and AM/PM).

**Comment by Clockwork-Muse** [comment]
> How do you explain the fact that in exactly the same container .NET 6 and .NET 8 output different strings for the LongTimePattern (one without space and the other one with NNBSP)?

https://github.com/dotnet/runtime/pull/83589 Added explicit support for this character, and was only merged into 8.0+.  That aside, containers should _rarely_ need to care about culture-specific formatting like this.

> For anyone who comes across this, I have just found that Microsoft's ICU team merged a commit in their latest release

That will only affect Windows.  Linux distros use their own source(s - plus allowing user customization), and Mac uses their own as well.
