### ISSUE TITLE
Question/suggestion: SearchValues alternative for finding the first char not in a string: SearchNotValues\Span.IndexOfNotAny(SearchNotValues)

### ISSUE THREAD

**Issue by osexpert** [dotnet/runtime#107829]
I saw that `OptimizedInboxTextEncoder` (to encode json) has SIMD support for finding the first char it need to encode. It does something like finding the first char that is not ascii by using SIMD. It is possible to use `SearchValues `for this too, but `SearchValues `would need to include all the chars _except_ ascii (a lot of chars), and this is not equally speedy.

I am not sure if `SearchValues `can be chaneged to be used like that, but if it could, I suggest: `Span.IndexOfNotAny(SearchValues values)`

If it needs a new struct, I suggest:
`class SearchNotValues`
`Span.IndexOfNotAny(SearchNotValues values)`

If this had existed, OptimizedInboxTextEncoder could be switched to use SearchNotValues\IndexOfNotAny instead:-)

Thanks.

**Comment by pinkfloydx33** [comment]
Isn't that what [`IndexOfAnyExcept`](https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.indexofanyexcept?view=net-8.0#system-memoryextensions-indexofanyexcept-1(system-readonlyspan((-0))-system-buffers-searchvalues((-0)))) is for?

**Comment by osexpert** [comment]
> Isn't that what [`IndexOfAnyExcept`](https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.indexofanyexcept?view=net-8.0#system-memoryextensions-indexofanyexcept-1(system-readonlyspan((-0))-system-buffers-searchvalues((-0)))) is for?

Haha, yes looks like it :-) I did not notice :-) Thanks!

So...then I guess...OptimizedInboxTextEncoder could actually be switched to IndexOfNotAny today, without any extra work :-) So then I will suggest this instead :-)
