### ISSUE TITLE
Potential memory leak in ep_file_write_event error path

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#107970]
`metadata_instance` gets allocated here:
https://github.com/dotnet/runtime/blob/24e7d1b0959234a36fb09a5c64cfd2da20f10618/src/native/eventpipe/ep-file.c#L464

This error path will presumably go to `ep_on_error` which skips the `ep_event_metadata_event_free (metadata_instance);` call:
https://github.com/dotnet/runtime/blob/24e7d1b0959234a36fb09a5c64cfd2da20f10618/src/native/eventpipe/ep-file.c#L468

**Comment by mdh1418** [comment]
I think `ep_file_write_event`'s `ep_on_error` jumps back to `ep_on_exit` because of https://github.com/dotnet/runtime/blob/24e7d1b0959234a36fb09a5c64cfd2da20f10618/src/native/eventpipe/ep-rt-types.h#L51, so I believe it eventually calls the `ep_event_metadata_event_free (metadata_instance);` call.

**Comment by filipnavara** [comment]
Makes sense. Thanks for checking!
