### ISSUE TITLE
Local build of runtime failing when running CDac tool

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#107936]
```
  Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
     at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32
  bufferSize, Boolean leaveOpen)
     at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
     at Microsoft.DotNet.Diagnostics.DataContract.BuildTool.ContractDescriptorSourceFileEmitter.GetTemplateString() in
  C:\src\dnceng\dotnet-runtime\src\coreclr\tools\cdac-build-tool\ContractDescriptorSourceFileEmitter.cs:line 30
     at Microsoft.DotNet.Diagnostics.DataContract.BuildTool.ContractDescriptorSourceFileEmitter.Emit(TextWriter dest) i
  n C:\src\dnceng\dotnet-runtime\src\coreclr\tools\cdac-build-tool\ContractDescriptorSourceFileEmitter.cs:line 60
     at Microsoft.DotNet.Diagnostics.DataContract.BuildTool.ComposeCommand.Run(ParseResult parse, CancellationToken tok
  en) in C:\src\dnceng\dotnet-runtime\src\coreclr\tools\cdac-build-tool\ComposeCommand.cs:line 77
     at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(ParseResult parseResult, CancellationToken cancell
  ationToken)
  [74/302] Building CXX object tools\superpmi\superpmi\CMakeFiles\superpmi.dir\cycletimer.cpp.obj
  FAILED: debug/runtimeinfo/cdac/contract-descriptor.c C:/src/dnceng/dotnet-runtime/artifacts/obj/coreclr/windows.x64.R
  elease/debug/runtimeinfo/cdac/contract-descriptor.c
```

Seems like https://github.com/dotnet/runtime/blob/8ae3796ef109962725833610c26e3f0bb06e2988/src/coreclr/tools/cdac-build-tool/ContractDescriptorSourceFileEmitter.cs#L25 is returning null for resource with name https://github.com/dotnet/runtime/blob/8ae3796ef109962725833610c26e3f0bb06e2988/src/coreclr/tools/cdac-build-tool/ContractDescriptorSourceFileEmitter.cs#L13

Which seems to me like some file is missing from the resources of this assembly.  I can't determine where that is supposed to come from because it looks like a wildcard includes it: https://github.com/dotnet/runtime/blob/8ae3796ef109962725833610c26e3f0bb06e2988/src/coreclr/tools/cdac-build-tool/cdac-build-tool.csproj#L30

But I see nothing that matches the filename https://github.com/dotnet/runtime/tree/8ae3796ef109962725833610c26e3f0bb06e2988/docs/design/datacontracts/data

If I disassemble the tool built in my local build I see the following resource:
![image](https://github.com/user-attachments/assets/23af61cb-dfa1-4f7a-8d1c-22f10ca1bc6a)

@lambdageek @elinor-fung

**Comment by ericstj** [comment]
FWIW I'm hitting this on my clone of the internal mirror of 9.0 RC2 in case that matters.  I have tried starting from clean a few times.  I'm not sure why this is failing.  I see it seems to be trying to load this resource https://github.com/dotnet/runtime/blob/8ae3796ef109962725833610c26e3f0bb06e2988/src/coreclr/tools/cdac-build-tool/cdac-build-tool.csproj#L27

But I don't see that even embedded in the built assembly.

**Comment by ericstj** [comment]
Update - that still fails.  I was able to workaround it by setting `LogicalName` metadata on that resource:
```xml
      <EmbeddedResource Include="Resources/contract-descriptor.c.in" LogicalName="Microsoft.DotNet.Diagnostics.DataContract.Resources.contract-descriptor.c" />
```
I have no idea why this was failing for me without the change.  Once I get done doing the thing I needed to do I'll undo my workaround and see if I can debug it.

**Comment by lambdageek** [comment]
I can't repro with `release/9.0-rc2` from the public repo, compiling on linux-x64 with `./build.sh clr+libs -c Release`.  I'll try a windows build and the internal repo when i'm back in the office.

I think it's maybe https://github.com/dotnet/msbuild/issues/9152  Perhaps because "c" is a valid locale name.
Can you try setting `WithCulture="false"` on the `<EmbeddedResource>` item

**Comment by lambdageek** [comment]
honestly I over-engineered this. there's no reason to embed this stuff into cdac-build-tool. we never run it outside the source tree. I can just pass it the paths of the relevant files as command line arguments from when we call it during the build...

**Comment by lambdageek** [comment]
Tried building on windows-x64. the public 9.0-rc2 branch and the internal one.  no errors.
I'm using a VS 17.12 preview

Not sure if I need more i18n stuff or VS components installed to repro the issue.

This is what I see in the tool from the the internal branch

![Screenshot 2024-09-18 at 10 25 01](https://github.com/user-attachments/assets/5aabb463-3fce-4b2c-bd2a-3108540380e1)

**Comment by ericstj** [comment]
Could it be due to the path I have cloned my internal repo to?  It was cloned to `c:\src\dnceng\dotnet-runtime`.  I haven't had a chance to return to this, but I did have a 100% repro, so I could share a binlog with you if you want.

**Comment by lambdageek** [comment]
@ericstj could you try adding `WithCulture="false"` to the EmbeddedResource items for cdac-build-tool to see if that resolves the issue.  I've mostly convinced myself that I just want to get out of the embedded resource business (#107958), so I'd rather get a quick workaround/fix in than investigate the root cause too deeply...
