### ISSUE TITLE
NET 9.0 RC2 NativeLibrary.Load crashes

### ISSUE THREAD

**Issue by Bluespide** [dotnet/runtime#107993]
Using "NativeLibrary.Load" just crashes the c# programm. Debugging just quits. My example is LibBass.dll from un4seen. Simple c# 9.0.100-rc.2.24461.5 console application:

using System.Runtime.InteropServices;
nint ptr = NativeLibrary.Load(@"C:\Users\Blue\Desktop\LibBass.dll");

The latest working .NET version was 9.0.100-preview.5.24307.3. Every version above crashed for me.
The crash appears in the windows event log with exception code: 0xc0000409, maybe STATUS_STACK_BUFFER_OVERRUN?

Is this behavior known, or did miss something? Will it be fixed?

**Comment by AaronRobinsonMSFT** [comment]
> Is this behavior known, or did miss something? Will it be fixed?

The call to `NativeLibrary.Load` basically defers to the underlying OS to load the binary. Can you please verify using something like `LoadLibrary` or `dlopen` doesn't exhibit the same behavior?

**Comment by jkoritzinsky** [comment]
Could this be from .NET enabling CET by default? CET was enabled in Preview 6. It's possible that LibBass is not CET compatible.

**Comment by Bluespide** [comment]
> The call to `NativeLibrary.Load` basically defers to the underlying OS to load the binary. Can you please verify using something like `LoadLibrary` or `dlopen` doesn't exhibit the same behavior?

It works by just switching the project to .NET 8 or installing 9.0.100-preview.5.24307.3.

> Could this be from .NET enabling CET by default? CET was enabled in Preview 6. It's possible that LibBass is not CET compatible.

Thank you very much. I missed that. With `<CETCompat>false</CETCompat>` in the .csproj file, everything works fine. LibBass seems to be not CET compatible.

**Comment by AaronRobinsonMSFT** [comment]
> > The call to `NativeLibrary.Load` basically defers to the underlying OS to load the binary. Can you please verify using something like `LoadLibrary` or `dlopen` doesn't exhibit the same behavior?
> 
> It works by just switching the project to .NET 8 or installing 9.0.100-preview.5.24307.3.
> 
> > Could this be from .NET enabling CET by default? CET was enabled in Preview 6. It's possible that LibBass is not CET compatible.
> 
> Thank you very much. I missed that. With `<CETCompat>false</CETCompat>` in the .csproj file, everything works fine. LibBass seems to be not CET compatible.

This is unfortunate. @elinor-fung @janvorli @mangod9 Should we think about constructing a way to provide an error message due to CET? This is one of those issues that is likely to cost people a lot of headache as the rest of the ecosystem catches up.

@Bluespide I've not looked at the library in question, but is it free to download and reproduce this locally?

**Comment by mangod9** [comment]
Don't think windows provides a reasonable message for CET issues, but we can follow up.

**Comment by Bluespide** [comment]
@AaronRobinsonMSFT Yes. The website is: https://www.un4seen.com. I used the latest version 2.4.17. Direct download link: https://www.un4seen.com/files/bass24.zip

**Comment by janvorli** [comment]
@Bluespide unless you set Windows to run your .NET app or all apps to run with strict CET mode, .NET should be able to load and use dlls that are not CET compatible just fine except for the cases when a code in the library modifies return addresses on the stack or sets the thread context with Rip that's not on the stack.
But you've said that "Debugging just quits.". Does the problem happen without debugging enabled too? There is a known problem with the debugger and continuing execution / single stepping from a call instruction when the process has CET enabled. The debugger might do such things on its own behalf, so it doesn't necessarily mean you'd do that yourself. So I'd like to better understand the circumstances under which the issue occurs.

**Comment by Bluespide** [comment]
> unless you set Windows to run your .NET app or all apps to run with strict CET mode, .NET should be able to load and use dlls that are not CET compatible just fine

I didn't change any option. Where would I do that?

> you've said that "Debugging just quits.". Does the problem happen without debugging enabled too?

Yes, also without the debugger, by just running the executable the application just crashes. Even build with Release mode. Even build with Native AOT. The crash also appears on the Windows event log:

![grafik](https://github.com/user-attachments/assets/0c0fb836-5f23-4194-810c-ac9e6f29a387)

I redownloaded the bass dll and apparently they changed something without changing the version. But the digital signature now has a new date. Now it's from 08/16/24. With this new dll, the NativeLibrary.Load just works. Therefore I attached my old dll (same version) with digital signature from 10/12/22 where the crash still appears for reproducing/testing.

[LibBass_x64_2_4_17_0.zip](https://github.com/user-attachments/files/17187675/LibBass_x64_2_4_17_0.zip)

I guess I should have just downloaded the new version of the DLL because the one I got seems very old. But it worked up to Preview 6 :)

**Comment by janvorli** [comment]
I can reproduce the problem with the libbass @Bluespide has shared. It crashes down the call chain of the DllMain of the library. Since Windows don't call vectored exception handler for this CET failure, .NET cannot do anything about reporting it in a better way. 
Since the library is closed source, I don't know what's going on in it. So I am glad the new build works fine.
