### ISSUE TITLE
Test.CoreLib is missing DefaultMemberAttribute 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/runtime#107953]
### Description

See https://github.com/dotnet/roslyn/issues/75032

### Reproduction Steps

N/A

### Expected behavior

DefaultMemberAttribute is defined in the core library

### Actual behavior

DefaultMemberAttribute is not defined in the core library

### Other information

Compiler team might decide to report an error for an indexer declaration when the attribute is missing. This will cause a build break of the library after upgrade if the attribute is missing.

**Comment by MichalStrehovsky** [comment]
@AlekseyTs could you link more info about the DefaultMemberNameAttribute? I can't find a definition of it anywhere in this repo.

**Comment by jaredpar** [comment]
FYI: Roslyn team is intending to fix this bug in 17.13 / 9.0.200 SDK. Once we do that will likely result in a build break in `Test.Corelib` until the attribute is added. That's a few months down the road but wanted to give you a heads up that this is coming.

**Comment by MichalStrehovsky** [comment]
> FYI: Roslyn team is intending to fix this bug in 17.13 / 9.0.200 SDK. Once we do that will likely result in a build break in `Test.Corelib` until the attribute is added. That's a few months down the road but wanted to give you a heads up that this is coming.

OK, that sounds like we need to backport to 9.0 then. @AlekseyTs can you verify that #108236 fixes this? I would like to avoid bothering the shiproom with this twice if this doesn't fix it.
