### ISSUE TITLE
[swift interop] Cannot call instance methods with at least one parameter when using `SwiftSelf<T>` 

### ISSUE THREAD

**Issue by jkurdek** [dotnet/runtime#107946]
Our current interop implementation only allows SwiftSelf<T> (representing the self parameter in Swift instance methods) to be specified as the first parameter in function signatures. This design choice leads to issues when interfacing with Swift instance methods that accept additional parameters.

Let's consider following example

```swift
@frozen public struct SampleStruct
{
    public var x1: Int
    public var x2: Int

    public func addWithExtraArgs(x3: Float, x4: Float) -> Float {
        return Float(x1 + x2) + x3 + x4
    }
}
```

`addWithExtraArgs` results in the following LLVM-IR:

```llvm
define protected swiftcc float @"output.SampleStruct.addWithExtraArgs(x3: Swift.Float, x4: Swift.Float) -> Swift.Float"(float %0, float %1, i64 %2, i64 %3) ...
```

`SampleStruct` is expected to be lowered into two `i64` which are passed as **last** parameters.
This would correspond to following csharp signature:
```c#
static extern void AddWithExtraArgs(float a, float b, SwiftSelf<SampleStruct> struct)
```

We should either allow `SwiftSelf<T>`  argument to be specified as the last parameter or we should reorder the parameters in runtime.

\cc: @kotlarmilos, @jakobbotsch, @amanasifkhalid, @matouskozak

**Comment by jakobbotsch** [comment]
> We should either allow `SwiftSelf<T>` argument to be specified as the last parameter or we should reorder the parameters in runtime.

My impression (from playing around on Godbolt, IIRC) was that the Swift compiler always put this first. Does it actually always put it last? Do you know what the rules are for how the lowering of the self arg is placed?

**Comment by jkurdek** [comment]
I am unable to find any piece of Apple documentation which describes this. Playing around in Godbolt: https://godbolt.org/z/1qj8vsf1h it seems that for both frozen and non-frozen structs it is passed as last argument. 

Do you remember any example where it was passed as first argument?

**Comment by jakobbotsch** [comment]
> I am unable to find any piece of Apple documentation which describes this. Playing around in Godbolt: https://godbolt.org/z/1qj8vsf1h it seems that for both frozen and non-frozen structs it is passed as last argument.
> 
> Do you remember any example where it was passed as first argument?

I don't. Looks like we should just switch the requirement to be the last argument then.

**Comment by stephen-hawley** [comment]
> > I am unable to find any piece of Apple documentation which describes this. Playing around in Godbolt: https://godbolt.org/z/1qj8vsf1h it seems that for both frozen and non-frozen structs it is passed as last argument.
> > Do you remember any example where it was passed as first argument?
> 
> I don't. Looks like we should just switch the requirement to be the last argument then.

It was might have been the case in Swift 2.2 when `self` was an implicit first argument like C++.
