### ISSUE TITLE
IdnMapping.GetAscii and GetUnicode throw ArgumentException on Linux

### ISSUE THREAD

**Issue by Bio2hazard** [dotnet/runtime#107900]
### Description

I'm using `IdnMapping.GetAscii` to normalize domain names between unicode and ascii punycode, but my code is consistently failing on my Linux box.
I have searched for other issues with this method, but they all seem to revolve around long urls, which does not apply in my case.

I've tried with:
`var ascii = new IdnMapping().GetAscii("xn--testtest-nz75g.com");`
`var ascii = new IdnMapping().GetAscii("test🙃test.com");`

And several more, and all result in 
```
System.ArgumentException
Decoded string is not a valid IDN name. (Parameter 'unicode')
   at System.Globalization.IdnMapping.IcuGetAsciiCore(String unicodeString, Char* unicode, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
```

I also tried `GetUnicode` (`var ascii = new IdnMapping().GetUnicode("xn--testtest-nz75g.com");`) which fails similarly with
```
System.ArgumentException
Decoded string is not a valid IDN name. (Parameter 'ascii')
   at System.Globalization.IdnMapping.IcuGetUnicodeCore(String asciiString, Char* ascii, Int32 count, UInt32 flags, Char* output, Int32 outputLength, Boolean reattempt)
   at System.Globalization.IdnMapping.IcuGetUnicodeCore(String asciiString, Char* ascii, Int32 count)
   at System.Globalization.IdnMapping.GetUnicode(String ascii, Int32 index, Int32 count)
```

On Windows, these calls all succeed and provide the expected output.

### Reproduction Steps

`var ascii = new IdnMapping().GetAscii("xn--testtest-nz75g.com");`

### Expected behavior

ascii contains `xn--testtest-nz75g.com`

### Actual behavior

Throws
```
System.ArgumentException
Decoded string is not a valid IDN name. (Parameter 'unicode')
   at System.Globalization.IdnMapping.IcuGetAsciiCore(String unicodeString, Char* unicode, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
```

### Configuration

- Version: Runtime 8.0.8 / SDK 8.0.401
- OS: Amazon Linux 2
- Architecture: x64
- Specific to configuration: Yes. Code works on Windows 10

**Comment by ericstj** [comment]
I gave this a try and it's no-repro for me on both 8.0.8 and 9.0.0-preview7 on Linux.

```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
```

I wonder if the failure you're hitting is unique to `Amazon Linux 2`?  Seems like it's failing here:
https://github.com/dotnet/runtime/blob/8ae3796ef109962725833610c26e3f0bb06e2988/src/libraries/System.Private.CoreLib/src/System/Globalization/IdnMapping.Icu.cs#L37-L51

**Comment by tarekgh** [comment]
Amzaon Linux 2 is using outdated version of ICU library `ICU Version: 50.2.0.0`. Try to upgrade the ICU version like run the command `yum install -y libicu60` and this will make it work. I am closing the issue, feel free to respond with any question if you still have any.
