### ISSUE TITLE
Why doesn't the EE save volatile registers for profiler function callbacks?

### ISSUE THREAD

**Issue by jeroen-mostert** [dotnet/runtime#10797]
Apologies in advance if this question is particularly ignorant or does not belong here. I browsed the repo for things tagged `question` and it didn't seem particularly out of order to raise an issue for clarification.

As [corprof.idl](https://github.com/dotnet/coreclr/blob/master/src/inc/corprof.idl) explains for the `FunctionEnter*`, `FunctionLeave*` and `FunctionTailcall*` callbacks (set with `ICorProfilerInfo*::SetEnterLeaveFunctionHooks*`):

> It is VERY IMPORTANT to note that these function implementations must be
> __declspec(naked), since the EE is not saving any registers before calling
> any of them.  YOU MUST SAVE ALL REGISTERS YOU USE, INCLUDING FPU REGISTERS
> IF THE FPU STACK IS NOT EMPTY AND YOU INTEND TO USE IT.

Alright, so... *why* does the EE not save any registers (as opposed to following the platform ABI rules for volatiles)? This mostly leads to profilers doing a predictable [register saving dance](https://github.com/Microsoft/clr-samples/blob/master/ProfilingAPI/ELTProfiler/CorProfiler.cpp#L27) before invoking another function the regular way. This is nasty since it requires some platform-specific assembler that's not covered by intrinsics (the alternative being [IL rewriting](https://github.com/Microsoft/clr-samples/blob/master/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.cpp) of any and all methods you want to instrument, which has its own issues).

What's the design or implementation rationale behind this? Speed? But if every profiler has to save registers anyway (practically speaking, assuming not too many are written in raw asm), where would those savings come in? If no hook is set, surely the EE could just invoke a stub that literally does nothing (as I believe it already does), while if a hook *is* set, it can call a stub to save the volatiles before the profiler proper, removing this burden from profilers?

This requirement gets onerous as you're going cross-platform, as dotnet/runtime#10706 illustrates, but I'm just interested in why this is (or was deemed) necessary/expedient in the first place.

**Comment by davmason** [comment]
If you register ELT hooks with SetEnterLeaveFunctionHooks3 it will call directly in to your callback with no register preservation, but if you call SetEnterLeaveFunctionHooks3WithInfo it will call in to a runtime helper that does back up volatile registers for you. There were some missing registers prior to 5.0 but I did some work in the 5.0 timeframe to make sure we actually back up all the registers we care about.

As far as I know it's not documented that this is the behavior, so we should fix that, but our tests use SetEnterLeaveFunctionHooks3WithInfo and register a C++ stdcall callback so you can safely rely on that behavior.
