### ISSUE TITLE
Add an `OrderedDictionary.TryAdd` overload that returns the `int`-based index of an entry if the key already exists

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#107947]
## Motivation

The `CollectionsMarshal.GetValueRefOrAddDefault` method for dictionaries provides a powerful mechanism for adding or updating a dictionary entry using only one lookup. The newly added `OrderedDictionary<TKey, TValue>` collection would similarly benefit from a such an API, however we don't need to make it as unsafe; simply knowing the `int`-based index of an entry makes it possible to very cheaply look up or update its value using the `GetAt` and `SetAt` methods, respectively. 

## API Proposal

```diff
namespace System.Collections.Generic;

public partial class OrderedDictionary<TKey, TValue>
{
    public bool TryAdd(TKey key, TValue value);
+   public bool TryAdd(TKey key, TValue value, out int index);
}
```

## API Usage

See [this conversation](https://github.com/dotnet/runtime/pull/107944/files/d82ad3be357302c4417606d621b2e94dbefc99ef#r1763769509) for a motivating use case. 

### Before

```C#
if (!dict.TryAdd(propertyName, value))
{
    int index = dict.IndexOf(propertyName); // Second lookup operation
    Debug.Assert(index >= 0);
    JsonNode? replacedValue = dict.GetAt(index).Value;
    DetachParent(replacedValue);
    dict.SetAt(index, value);
}
```

### After

```C#
if (!dict.TryAdd(propertyName, value, out int index))
{
    JsonNode? replacedValue = dict.GetAt(index).Value;
    DetachParent(replacedValue);
    dict.SetAt(index, value);
}
```

**Comment by aromaa** [comment]
I find the parameter name `foundIndex` a bit convoluted. Does this only cover use cases where a duplicate one was found? What is the value for successful insert? In any case, it would be useful to return the index in both cases and rename it to `index`.

Technically the just inserted one would always be `Count - 1` but this avoid the need to special case and the possibility of oversight.

**Comment by eiriktsarpalis** [comment]
Good idea, I was originally thinking that it should be returning `-1` if returning `true` but I like your suggestion better.

**Comment by terrajobst** [comment]
* We should also have an overload for `TryGetValue`

```C#
namespace System.Collections.Generic;

public partial class OrderedDictionary<TKey, TValue>
{
    // Existing
    // public bool TryAdd(TKey key, TValue value);
    // public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TValue value);
    public bool TryAdd(TKey key, TValue value, out int index);
    public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TValue value, out int index);
}
```

**Comment by Ilchert** [comment]
Will index be filled if `TryGetValue` returns `false`? It would be great if it will return nearest index like `BinarySearch`.

**Comment by aromaa** [comment]
> It would be great if it will return nearest index like BinarySearch.

The entries of `OrderedDictionary` are sorted by the insertion order, not by the key. What you are describing is the `SortedDictionary`,
