### ISSUE TITLE
CoreClr should run tests on rolling builds instead of internal

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#108]
We should move the test execution from dnceng/internal to dnceng/public and enable it for rolling builds. @jashook mentioned that this requires significant changes. By doing so we make it possible for community members to track test failures efficiently via the Analytics section. There are also other advantages like limiting the need of dnceng/internal to signing and publishing.

cc @dotnet/runtime-infrastructure

**Comment by safern** [comment]
I believe this is fixed with the single pipeline changes?

**Comment by swaroop-sridhar** [comment]
Yes this issue is fixed. 
https://dev.azure.com/dnceng/public/_build/results?buildId=509813&view=results

https://github.com/dotnet/runtime/pull/1102
https://github.com/dotnet/runtime/pull/1596
