### ISSUE TITLE
Mono / .NET based Program crashing, won't start

### ISSUE THREAD

**Issue by FaRuffo** [dotnet/runtime#108069]
System:  Artix Linux (Arch fork)
Mono: Installed package Mono 6.12

This is not a bug, but I'm seeking help as a noob with mono.  I downloaded the Linux deb package of dwsim, which is based on .NET and written mostly in C#.  I then ran it and got these error messages:

```
Mono: DllImport unable to load library 'libgtk-x11-2.0.so.0'.
: libgtk-x11-2.0.so.0 assembly:<unknown assembly> type:<unknown type> member:(null)
at (wrapper managed-to-native) Gtk.Application.gtk_init_check(int&,intptr&)  (more lines deleted)
```
I then ran ldconfig:

```
# ldconfig -p|grep libgtk-x11-2.0.so.0
#libgtk-x11-2.0.so.0 (libc6,x86-64) => /usr/lib/libgtk-x11-2.0.so.0
```

Gut feel is that I have some config I need to do.

Thanks for your help.

**Comment by jkotas** [comment]
This issue belongs to https://github.com/mono/mono repo.

**Comment by FaRuffo** [comment]
Got it.  Thanks.
