### ISSUE TITLE
Safely receiving bool return value from C++ using unmanaged delegate in C#

### ISSUE THREAD

**Issue by Liangjia0411** [dotnet/runtime#108047]
How to safely receive `bool` type `return value` when `interacting with C++` using `unmanaged delegate`

---

### Testing Environment
- **Platform:** Windows
- **.NET Version:** 8.0.7

#### C# Code
```csharp
// Call C++ methods to get a bool return value
internal static bool TestBoolParam4() => TestBoolParam4_Internal();
private static delegate* unmanaged<bool> TestBoolParam4_Internal = null;

internal static bool TestBoolParam5() => TestBoolParam5_Internal();
private static delegate* unmanaged<bool> TestBoolParam5_Internal = null;
```

#### C++ Code
```cpp
// C++ methods called by C#

// Return int to simulate a 4-byte bool in C++
static int TestBoolParam4_Internal()
{
    return 256;
}

// Return a 8-byte uint64
static uint64 TestBoolParam5_Internal()
{
    return 4294967296; //0x100000000
}
```

### Test Results
When C++ returns an int, C# gets true.
When C++ returns an 8-byte value, will crash.

### Question
Why does C# get true when C++ returns an int?

---

**Comment by huoyaoyuan** [comment]
> Why does C# get true when C++ returns an int?

Because bool is indeed an int. What are you expecting the bool to represent?

I assume you are on x86 because returning 64 bit value is different on 32 bit platform.

The calling convention of unmanaged C# is the same as platform C. You need to define the function pointer in the same shape. If the C function returns uint64, you should use `delegate* unmanaged<ulong>`.

**Comment by huoyaoyuan** [comment]
Note that the CLR doesn't normalize bools. Any non-0 32bit value will be interpreted as `true`, and can cause unexpected result when performing logical operations. To safely accept a one-byte `bool`, use `byte` and test with `!= 0`. The P/Invoke marshaller and source generator does this for you.

**Comment by Liangjia0411** [comment]
From what you mean, if using unmanaged delegate in C #, C++needs to return a byte to C # instead of directly returning a bool

Below is the relevant code:

#### C# Code
```csharp
public enum NativeBool : byte
{
    True = 1,
    False = 0
}

// Call C++ method to get a bool return value
internal static bool TestBoolParam4() => TestBoolParam4_Internal() != 0;
private static delegate* unmanaged<NativeBool> TestBoolParam4_Internal = null;
```

#### C++ Code
```cpp
// C++ method called by C#
static byte TestBoolParam4_Internal()
{
    return 1;
}
```

**Comment by huoyaoyuan** [comment]
> C++needs to return a byte to C # instead of directly returning a bool

It seems that you **can** use the C++ `bool` - all compilers I tested are normalizing 0 or 1, which matches the CLR `bool`. I'm not sure whether any standard mandates this.

What you can't use is other boolean-like type in C++, which are often typedef'd as integers, for example the `BOOL` type of Windows API.

**Comment by jkoritzinsky** [comment]
When marshalling bool values, .NET provides 2 options:

- marshal a 1byte integer as a bool
- marshal a 4byte integer as a bool (the default)

In both cases, the .NET runtime normalizes the passed value: 0 is false and any non-zero value is true.

Passing an eight byte integer as a bool value is unsupported and can cause crashes.

**Comment by Liangjia0411** [comment]
thanks

**Comment by AaronRobinsonMSFT** [comment]
> It seems that you can use the C++ bool - all compilers I tested are normalizing 0 or 1, which matches the CLR bool. I'm not sure whether any standard mandates this.

The definition of the value of `bool` isn't specified if I recall. Instead one should look to integer conversion rules. In this case C++ `false` converts to zero and `true` converts to one.
