### ISSUE TITLE
WasmTemplateTests.RunWithDifferentAppBundleLocations timeout

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#108074]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=813673
Build error leg or test failing: Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations
Pull request: https://github.com/dotnet/runtime/pull/107639

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": [ "Wasm\\.Build\\.Tests\\.WasmTemplateTests\\.RunWithDifferentAppBundleLocations.*\\[FAIL\\]", "System\\.TimeoutException" ]
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
closing this in favor of https://github.com/dotnet/runtime/issues/108102
