### ISSUE TITLE
Fuzzlyn: Assertion failed 'otherTargetInterval->registerType == TYP_DOUBLE' during 'LSRA allocate'

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#108000]
[This Fuzzlyn run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=811429&view=results) hit this assert, as well as the assert `varDsc->IsAlwaysAliveInMemory() || ((regSet.GetMaskVars() & regMask) == 0)` on Linux arm32. Unfortunately, the trimmed repro doesn't work, and subsequent runs didn't hit these asserts. Here's a SPMI collection for each assert: [repro.zip](https://github.com/user-attachments/files/17050357/repro.zip)

cc @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
https://github.com/dotnet/runtime/pull/109173 should fix this.
