### ISSUE TITLE
dotnet --info shows "commi: static" in the host section

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#108004]
### Description

`dotnet --info` shows commit info as `static`.

### Reproduction Steps

```
$ ~/local/dotnet/microsoft/9.0.100-rc.1-runtime/dotnet --info

Host:
  Version:      9.0.0-rc.1.24431.7
  Architecture: x64
  Commit:       static
  RID:          linux-x64
...
```

### Expected behavior

Actual commit info? Or maybe not show the commit info?

### Actual behavior

`static`, which seems like a very strange value for commit identifier.

**Comment by omajid** [comment]
Same thing happens when using source-build VMR.

**Comment by vcsjones** [comment]
Could this be related to or possibly fixed by https://github.com/dotnet/runtime/pull/107954?

**Comment by jkoritzinsky** [comment]
Yep, #107594 and the backport to 9.0-rc2 fix this issue.

**Comment by omajid** [comment]
Thanks. I will close this issue, then.
