### ISSUE TITLE
Change DefaultAutomaticDecompression to DecompressionMethods.All

### ISSUE THREAD

**Issue by johnterickson** [dotnet/runtime#108163]
It seems odd to me that the default for `DefaultAutomaticDecompression` is `DecompressionMethods.None`.  Browsers default something akin to `All`.  Changing the default to `All` would be backwards-compatible and would support more scenarios.

The only scenario I could think that would break is if a server were just flatly incorrect (e.g. the encoding of the body didn't match what was stated in the `Content-Encoding` header). Of course, that server would be broken from all other tools as well (browsers, curl, wget, etc).

Thanks for the consideration!

Related: https://github.com/dotnet/runtime/issues/25950

**Comment by DL444** [comment]
FYI automatic compression was once enabled and then disabled by dotnet/corefx#17701 to match legacy behavior on .NET Framework. This is documented [here](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.automaticdecompression).

Additionally, using response compression with TLS has security implications. See [this](https://github.com/dotnet/runtime/issues/35987#issuecomment-2219613018) discussion and [this](https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression) documentation page.

**Comment by ManickaP** [comment]
As @DL444 mentioned, the `None` value is there for consistency. On top of that, choosing to enable automatic decompression should be conscious choice on the programmer side since it increases potential attack surface and so has security implications.

Also, we do not advertise `Accept-Encoding` unless the property is set, so you shouldn't see decompressed content coming from the server.
Lastly, it takes just one property to turn it on. So it's not like you need to write your own decompression algorithms. 

If you still think this should be change, could you share the impact the current default has on you? I'd like to understand your motivation behind this issue.

**Comment by wfurt** [comment]
As @ManickaP  mentioned there is penalty for the decompression. I feel it should be enabled only when caller understands the consequences. Places where `HttpClient` is typically different from browsers so I'm not convinced we need to match the default behavior.

**Comment by johnterickson** [comment]
Thanks for all the thoughtful feedback - I had not considered the information disclosure aspect of it though it surprises me that browsers enable it by default. Granted the scenario is different than the modal HttpClient scenario.

Our scenario is a bit odd because we have clients that download directly from Azure Storage and Azure Storage ignores Accept-Encoding and just relays the Content-Encoding that was presented it when the blob was uploaded. 🙄

The ideal for my case would be that by default decompression happens automatically if a Content-Encoding is encountered, but that by default Accept-Encoding is still not sent.  

I admit this is a weird line to walk - feel free to close unless someone has a stroke of genius. 😄 Sigh.

**Comment by wfurt** [comment]
It seems like you can simply set `SocketsHttpHandler.AutomaticDecompression` to whatever you desire and move forward with it, right @johnterickson ? That should be trivial and it is your deliberate decision for your use case.

**Comment by ManickaP** [comment]
> just relays the Content-Encoding that was presented it when the blob was uploaded.

So the server doesn't compress the content, but rather gives you what you put in. I think that makes sense and I would consider this more of an application logic than HTTP layer logic. So it makes sense that you'd need to decompress yourself in this case.

I'll close this for now, feel free to continue the discussion, but I don't believe there's anything we should change in  `HttpClient`.
