### ISSUE TITLE
NativeAOT - prior art for infering custom attributes

### ISSUE THREAD

**Issue by yowl** [dotnet/runtime#108101]
I want to ask if anyone thinks there is prior art for this problem, https://github.com/dotnet/runtimelab/issues/2626

In NativeAOT-LLVM, if a library is referenced that contains `JSExport`, we need to mark it as `UnmanagedCallersOnly` in addition so we can root it, export it, and get the right calling convention.  Example is the `Register` method created by the JSExport source generator.  Rooting can be solved with the` RdXmlRootProvider` but the other problems are harder.  One way is to change the source generator to always add it, and another way, not necessarily correct, is to view this as: "NativeAOT requires additional attributes that the library author might not be aware of", so I was wondering if there is any prior art?

Thanks!

**Comment by yowl** [comment]
Actually realised that the source generator already creates:
```cs
[UnmanagedCallersOnly(EntryPoint = "XpfSimple__GeneratedInitializer__Register_")]
private static void __Register__Export()
{
	__Register_();
}
```
Which looks like it is for this purpose, I'll close this for now.

**Comment by jkotas** [comment]
Optimized reflection-free interop solutions often want to generate some code based on the whole application view.

In case wasm interop runs into this problem too, prior art in this space:
- Generate the extra code during publish, and include the extra code as an input for AOT compiler. WinUI plans to do this. https://github.com/dotnet/runtime/issues/106216 has some context about.
- Run IL linker during publish, generate the extra code based on the trimmed app, and include the additional code as an input for AOT compiler. Xamarin iOS does this today. https://github.com/dotnet/runtime/issues/107211 has some context about it.
