### ISSUE TITLE
[API Proposal]: allow ref struct for linq Select method

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#108131]
### Background and motivation

Should the linq `Select` method support `allows ref struct`?

### API Proposal

```diff
namespace System.Linq;

 public static IEnumerable<TResult> Select<TSource, TResult>(
            this IEnumerable<TSource> source, Func<TSource, TResult> selector)
+       where TResult : allows ref struct

public static IEnumerable<TResult> Select<TSource, TResult>(
      this IEnumerable<TSource> source,
      Func<TSource, int, TResult> selector)
+       where TResult : allows ref struct
```

### API Usage

```csharp
var enumerable = Enumerable.Range(0, 3)
            .Select(_ => new RefStructDemo());
foreach (var v in enumerable)
    Console.WriteLine(v.Name);
```

**Comment by huoyaoyuan** [comment]
While it's technically possible to have an `IEnumerable<RefStruct>` that isn't itself a `ref struct`, it's not much usable since it can't directly hold information about its element. Moreover, `RefStruct[]` and `Dictionary<Key, RefStruct>` are not achievable, which may block implementation of LINQ.
