### ISSUE TITLE
UriBuilder.Query ignores leading ? in the value

### ISSUE THREAD

**Issue by spanglerco** [dotnet/runtime#1081]
When migrating from .NET Framework 4.6.2 to .NET Core 3.1, one of our tests fails due to a behavior change in UriBuilder. The test builds an LDAP URI by setting UriBuilder.Query to "?sub", expecting the result to be something like "ldap://host/??sub" (LDAP URIs typically have 1-3 ?s in them representing different aspects of filtering or attributes to query against).

From some searching, this appears to be on purpose given dotnet/corefx#3646, but [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.query?view=netcore-3.1) still says to "retrieve the property value as a string, remove the leading question mark, append the new query string, and set the property with the combined string" which implies the leading ? is significant in the property setter.

So I wanted to create this issue to help determine the expected way to resolve this behavior change. Does the documentation need to be updated and I should prepend an extra ? to the Query property? Or should there be some other change? Considering the associated PR was merged in 2016, I'm assuming this is the new expected behavior for Core. I haven't tested any other implementations besides Framework and Core.

This is trivially reproduced by running the following console app in net462 and netcoreapp3.1 and comparing outputs:

```csharp
static void Main(string[] args)
{
    var builder = new UriBuilder();
    builder.Query = "?sub";
    Console.WriteLine(builder.Uri.AbsoluteUri);
}
```

**Comment by vcsjones** [comment]
>  this appears to be on purpose given dotnet/corefx#3646

Yes, this was a breaking change that was introduced before .NET Core 1.0 shipped.

> Does the documentation need to be updated and I should prepend an extra ? to the Query property? Or should there be some other change? 

Yeah, it seems like filing an issue in the dotnet-api-docs repo to explain this behavior difference would be beneficial.

For what it's worth, the [`Fragment`][1] setter now also has the same behavior change with the same language in the documentation.

> I should prepend an extra ? to the Query property? 

That seems to be the most sensible thing to do.

[1]: https://github.com/dotnet/corefx/pull/7027

**Comment by spanglerco** [comment]
Moving this to a documentation issue. Thanks for the info @vcsjones.
