### ISSUE TITLE
Wasm.Build.Tests.WasmTemplateTests failing with System.TimeoutException : Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#108102]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=814594
Build error leg or test failing: Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations
Pull request: https://github.com/dotnet/runtime/pull/108094

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "Browser has been disconnected", "Wasm.Build.Tests.WasmTemplateTests", "System.TimeoutException : Timeout 30000ms exceeded." ],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=814594
**Error message validated:** `[Browser has been disconnected Wasm.Build.Tests.WasmTemplateTests System.TimeoutException : Timeout 30000ms exceeded.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/22/2024 3:45:44 AM UTC

**Comment by lewing** [comment]
I'm not sure why https://github.com/dotnet/runtime/issues/108074 wasn't matching either

**Comment by lewing** [comment]
this was missing the array brackets, closing in favor of #108107
