### ISSUE TITLE
CS8795 on GeneratedRegex attributed method

### ISSUE THREAD

**Issue by iKingNinja** [dotnet/runtime#108133]
### Description

According to [this article](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators?pivots=dotnet-8-0) when you have a static regex you should make it source generated.

However the compiler is throwing `Partial method 'RegexHelper.GameUrlRegex()' must have an implementation part because it has accessibility modifiers.`

### Reproduction Steps

Create a source generated regex like this
```cs
using System.Text.RegularExpressions;

public static partial class RegexHelper
{
    [GeneratedRegex("^https?:\\/\\/(www\\.)?example\\.com(?:\\/([a-zA-Z]{2}|[a-zA-Z]{2}-[a-zA-Z]{2,3}))?\\/games\\/\\d+(?:\\/([\\d\\w-]+))$", RegexOptions.IgnoreCase)]
    public static partial Regex GameUrlRegex();
}
```
Changing the access modifier from `public` to `private` doesn't make any difference and you can't declare the method without one because it has a non void return type.

### Expected behavior

I expect the compiler not to throw CS8795 when marking a method with the `[GeneratedRegex]` attribute.

### Actual behavior

The compiler is throwing CS8795.

**Comment by huoyaoyuan** [comment]
The error message means that Regex generator fails to run. It's usually not reproducible with minimal setup.
I saw this error temporarily in VS and it disappears after rebuild.

**Comment by stephentoub** [comment]
Is this only an issue with design-time errors or do you actually get this when you build?

If the former, it's likely https://github.com/dotnet/roslyn/issues/74031#issuecomment-2176170091.

cc: @CyrusNajmabadi

**Comment by iKingNinja** [comment]
Building removes the error so it's only design-time.

**Comment by stephentoub** [comment]
@CyrusNajmabadi, another example of this causing confusion.

@iKingNinja, the workaround is https://github.com/dotnet/roslyn/issues/74032#issuecomment-2174107562.
