### ISSUE TITLE
Access violation with Native AOT when calling an abstract property

### ISSUE THREAD

**Issue by KubaZ2** [dotnet/runtime#108154]
### Description

Access violation occurs when invoking the getter of an abstract property which has an abstract override which has another override, each with different type, when running with Native AOT.

### Reproduction Steps

```cs
A c = new C();

_ = c.P;

abstract class A
{
    public abstract AA P { get; }
}

abstract class B : A
{
    public abstract override BB P { get; }
}

class C : B
{
    public override CC P { get; } = new();
}

abstract class AA
{
}


abstract class BB : AA
{
}

class CC : BB
{
}
```

### Expected behavior

No AV

### Actual behavior

Getting the value of `P` from `C` casted to `A` causes
```
0xC0000005: Access violation executing location 0x0000000000000000.
```

### Configuration

.NET 8
Windows 11
x64

**Comment by MichalStrehovsky** [comment]
> Looks like duplicate of #106468

Yes, this is fixed as of .NET 9 RC2. Thanks for the report and nice repro steps!
