### ISSUE TITLE
Guid.Version does not return correct version in all situations

### ISSUE THREAD

**Issue by swtrse** [dotnet/runtime#108267]
### Description

If you generate an Guid with a Version Number that starts binary with bit 1. For Example Version 8.
The Version Property will return 1048568 instead of 8. This is because of a missing & 0xF After the shift operation

### Reproduction Steps

Generate a Guid with version number set to 8.
Get the value of the Guid.Version property.

### Expected behavior

Returns the correct Version number.

### Actual behavior

Returns the wrong Version number

### Regression?

Unknown

### Known Workarounds

When combined with the bit operation & 0xF the result is correct.

### Configuration

.NET9 RC2

**Comment by swtrse** [comment]
I run into this Problem when preparing #108268

**Comment by huoyaoyuan** [comment]
> If you generate an Guid with a Version Number that starts binary with bit 1. For Example Version 8.
> The Version Property will return 1048568 instead of 8. This is because of a missing & 0xF After the shift operation

Not exactly, it's because the short was *sign extended* to int before the *unsigned right shift*:

https://github.com/dotnet/runtime/blob/79a71fc750652191eba18e19b3f98492e882cb5f/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L287

**Comment by swtrse** [comment]
> > If you generate an Guid with a Version Number that starts binary with bit 1. For Example Version 8.
> > The Version Property will return 1048568 instead of 8. This is because of a missing & 0xF After the shift operation
> 
> Not exactly, it's because the short was _sign extended_ to int before the _unsigned right shift_:
> 
> https://github.com/dotnet/runtime/blob/79a71fc750652191eba18e19b3f98492e882cb5f/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L287

Of course you are right. I did miss the >>> operator. I could have sworn that there were only >> before you mentioned it.
Anyway, the conversion to int before the shift operation leads to the same wrong behavior.
