### ISSUE TITLE
Cannot see system.net debug log after using winhttphandler

### ISSUE THREAD

**Issue by datanglibai** [dotnet/runtime#1082]
I'm running a .net framework 461 console application, and have below config in app.config
 `<system.diagnostics>
    <sources>
      <source name="System.Net">
        <listeners>
          <add name="MyTraceFile" />
        </listeners>
      </source>
    </sources>
    <sharedListeners>
      <add name="MyTraceFile" type="System.Diagnostics.TextWriterTraceListener" initializeData="System.Net.trace.log" traceOutputOptions="DateTime" />
    </sharedListeners>
    <switches>
      <add name="System.Net" value="Verbose" />
    </switches>
  </system.diagnostics>
`

If I simply use HttpClient to send http11 request, the network debugging log is ok

but when I use WinHttpHandler to send http2.0 request, the log disappear, here is my code to use the handler.
public class Http2CustomHandler : WinHttpHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            request.Version = new Version("2.0");            
            return base.SendAsync(request, cancellationToken);
        }
    }
How can I see the network debug log in this case?

**Comment by wfurt** [comment]
This repo only tracks .NET Core issues. For the framework you should follow https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=df2c02f6-9610-d46d-2d76-fa570bd8c86a

cc: @davidsh in case he know the answer anyway.

**Comment by davidsh** [comment]
>cc: @davidsh in case he know the answer anyway.

>How can I see the network debug log in this case?

For .NET Framework applications, normally you would follow these instructions to see .NET networking traces:

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing

However, for .NET Core, networking tracing has switched to ETW (EventSource) based tracing. That includes the WinHttpHandler component (System.Net.Http.WinHttpHandler NuGet package) as well.

See:
https://github.com/dotnet/runtime/blob/master/docs/workflow/debugging/libraries/windows-instructions.md  and using PerfView section.

Unfortunately, I will say that using WinHttpHandler on .NET Framework will have much reduced network logging present compared to using the built-in .NET Framework HTTP stack or the .NET Core HTTP stack (SocketsHttpHandler).
