### ISSUE TITLE
Any plan to add Microsoft.SqlServer.Replication

### ISSUE THREAD

**Issue by JaieParker** [dotnet/runtime#108223]
Hey guys,
I can see that this ticket (ref: https://github.com/dotnet/runtime/issues/26963#issue-558406017)  was raised back on Jul 26, 2018, but I cant see there being any resolution or information about whether you plan to move this to .net core

I found reference to this in the Microsoft SQL Server 2022 documentation eg: https://learn.microsoft.com/en-us/sql/relational-databases/replication/configure-publishing-and-distribution?view=sql-server-ver16#PShellExample

Is there any plan to move this or an alternative that I could use appart from using SQL directly?

Cheers

**Comment by huoyaoyuan** [comment]
System.Data.SqlClient has been deprecated in favor of [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient). Feature requests should be opened into that repo.
