### ISSUE TITLE
System.Text.Json Serialization of Empty Collections

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/runtime#108237]
### The problem
In most DTOs lists and other collections are directly initialized to cut down boilerplate code to create new collections before they are created, so in general something like this is used for the ``Values`` property
```csharp
   public sealed class MyClass
    {
        public string Name { get; set; } = default!;
        public List<int> Values { get; set; } = new();
    }
```

Serialization of an empty collection results in something like ``"values": []``

As soon as someone has a few more of these, it gets a bit annoying as they should likely be ignored and increase serialization/deserialization time, payload size etc.

### A bit of history
Multiple closed issues, mostly as duplicated of #55781 and that one was closed in favor for https://github.com/dotnet/runtime/issues/63686

But I don't think the intended result of the original problem was ever achieved in #63686, because it does not work properly with source generated S.T.J.  TypeInfoResolvers.

### Thoughts
Let's assume the following code:

``` csharp
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ConsoleApp35
{
    internal class Program
    {
        private static readonly JsonSerializerOptions Options = new (JsonSerializerDefaults.Web)
        {
            TypeInfoResolverChain = { SerializionContext.Default, }
        };

        static void Main(string[] args)
        {
            var input = new MyClass {Name = "Hello World", Values = [1, 2, 3]};
            var serialized = JsonSerializer.Serialize(input, Options);
            Console.WriteLine(serialized);
            input = new MyClass { Name = "Hello World", Values = [] };
            serialized = JsonSerializer.Serialize(input, Options);
            Console.WriteLine(serialized);
        }

    }


    public sealed class MyClass
    {
        public string Name { get; set; } = default!;
        public List<int> Values { get; set; } = new();
    }

    [JsonSerializable(typeof(MyClass))]
    [JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
    public partial class SerializionContext : JsonSerializerContext;
}

```
The above code snippet outputs:
```ini
{"name":"Hello World","values":[1,2,3]}
{"name":"Hello World","values":[]}
```
So that's the status quo at the moment, without custom ``IJsonTypeInfoResolvers``, according to the issue above we need to modify the ``ShouldSerialize`` logic for a specific property, let's build one

```csharp
    public sealed class EmptyCollectionTypeInfoResolver : IJsonTypeInfoResolver
    {
        public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)
        {
            // where to get the actual existing JsonPropertyInfo?
            var existing = SerializionContext.Default.GetTypeInfo(type);
           //  infinte loop  var existing = options.TypeInfoResolver?.GetTypeInfo(type, options);
            if (existing is not null)
            {
                foreach (var existingProperty in existing.Properties)
                {
                    if (existingProperty.PropertyType.IsAssignableTo(typeof(IList)))
                    {
                        // doesn't work, the context is read-only
                        existingProperty.ShouldSerialize = (_, child) => child is IList {Count: > 0};
                    }
                }
            }

            return existing;
        }
    }
```
The above code throws at runtime, the source generated one is read-only, can't modify it.

Yes, we can derived from DefaultTypeInfoResolver and modify that one, that one is mutable, but that one is using reflection and needs to be put on first position of the ``TypeInfoResolverChain`` and then it will never use the source generated one(s).

```csharp
    public sealed class DefaultEmptyCollectionTypeInfoResolver : DefaultJsonTypeInfoResolver
    {
        public override JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options)
        {
            var existing = base.GetTypeInfo(type, options);
            foreach (var existingProperty in existing.Properties)
            {
                // this is simplified, other collection types would need to be considered or something like TryGetNonEnumeratedCount
                if (existingProperty.PropertyType.IsAssignableTo(typeof(IList)))
                {
                    existingProperty.ShouldSerialize = (_, child) => child is IList {Count: > 0};
                }
            }

            return existing;
        }
    }

```

### Conclusion
So from my point of view, with source generation, the rather simple requirement of not serializing empty collections does not really work.

I can see two possible directions, the original idea of something like:
``[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingEmptyCollection)]``

which then could be integrated into the source generator and produce code similar to the following (see the part with ``.Count > 0``)

```csharp
        private void MyClassSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::ConsoleApp35.MyClass? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            string __value_Name = ((global::ConsoleApp35.MyClass)value).Name;
            if (__value_Name != null)
            {
                writer.WriteString(PropName_Name, __value_Name);
            }
            global::System.Collections.Generic.List<int> __value_Values = ((global::ConsoleApp35.MyClass)value).Values;
            if (__value_Values != null && __value.Values.Count > 0)
            {
                writer.WritePropertyName(PropName_Values);
                ListInt32SerializeHandler(writer, __value_Values);
            }

            writer.WriteEndObject();
        }
```
This would be the most obvious solution (and likely user friendly), but I do understand that there is a rather fancy contract modification system in place, but for that the following is missing imho:

Instead of ``var existing = base.GetTypeInfo(type, options)`` above in the code snippet for ``DefaultEmptyCollectionTypeInfoResolver``, that one needs to take the Resolver Chain into account and modifying it will then need to clone/copy the ``JsonPropertyInfo`` and allow for modification. 

Personally I still prefere the ``WhenWritingEmptyCollection`` approach as it will properly work with the fast path serialization logic, which I doubt will be easy with the contract resolvers.  From a performance point of view the contract logic will certainly be slower.

Maybe I'm missing something crucial in here, but I think the the original requirement simply fell through the cracks, somewhere between source generation and the contract modification.

**Comment by elgonzo** [comment]
If i am not mistaken, it seems the root of your problems is not being able to use/merge a custom JsonTypeInfoResolver with the STJ-produced resolver.

To get around this, STJ provides the [`WithAddedModifier`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.metadata.jsontypeinforesolver.withaddedmodifier?view=net-8.0) extension method that derives a new resolver from a given resolver (including one produced by the STJ source gen) plus a modifier method. The modifer method's logic is what would otherwise typically go into a custom resolvers `GetTypeInfo` method override.

An example of the `WithAddedModifier` approach that allows configuring/customizing serialization behavior at runtime: https://github.com/dotnet/runtime/discussions/103824#discussioncomment-9842215 (including a dotnetfiddle link). Note how the example modifier method employs the `ShouldSerialize` delegate to customize the serialization behavior.

**Comment by Tornhoof** [comment]
@elgonzo 
Thank you for your help with with the ``WithAddedModifier``, that makes it atleast more usable, need to experiment with ``JsonTypeInfoResolver.Combine`` to see combine the different src gen contexts so I can apply the modifier only once.
Still need to benchmark that to figure out how much impact it has, but that's unrelated.

And yeah, I wrote my demo code for IList and later realized it needs to apply to ICollection, just never changed the demo code.

This is good enough. Closing this.

If someone ever stumbles over this, this then looks like this:
```csharp
namespace ConsoleApp55
{
    internal class Program
    {
        private static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web)
        {
            TypeInfoResolverChain = { SerializationContext.Default.WithAddedModifier(ContractModifier_Collection) },
        };

        static void Main(string[] args)
        {
            var input = new MyClass { Name = "Hello World", Values = [1, 2, 3] };
            var serialized = JsonSerializer.Serialize(input, Options);
            Console.WriteLine(serialized);
            input = new MyClass { Name = "Hello World", Values = [] };
            serialized = JsonSerializer.Serialize(input, Options);
            Console.WriteLine(serialized);
        }

        private static void ContractModifier_Collection(JsonTypeInfo contract)
        {
            if (contract.Kind != JsonTypeInfoKind.Object)
            {
                return;
            }
            foreach (var prop in contract.Properties)
            {
                if (prop.PropertyType.IsAssignableTo(typeof(ICollection)))
                {
                    prop.ShouldSerialize = static (_, child) => child is ICollection { Count: > 0 };
                }
            }
        }

    }

    public sealed class MyClass
    {
        public string Name { get; set; } = default!;
        public List<int> Values { get; set; } = new();
    }

    [JsonSerializable(typeof(MyClass))]
    [JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
    public partial class SerializationContext : JsonSerializerContext;
}

```

**Comment by huan086** [comment]
I needed this to work on generic `IList<>`, i.e.

```csharp
public sealed class MyClass
{
    public string Name { get; set; } = default!;
    public IList<int> Values { get; set; } = new List<int>();
}
```

Since `IList<>` does not implement `ICollection`, I've modified @Tornhoof's code

```csharp
private static void ContractModifier_Collection(JsonTypeInfo jsonTypeInfo)
{
    if (jsonTypeInfo.Kind != JsonTypeInfoKind.Object)
    {
        return;
    }

    foreach (var property in jsonTypeInfo.Properties)
    {
        if (property.PropertyType.IsValueType)
        {
            continue;
        }

        bool isCollection =
            (property.PropertyType.IsGenericType
                && property.PropertyType.GetGenericTypeDefinition() == typeof(ICollection<>))
            || Array.Exists(
                property.PropertyType.GetInterfaces(),
                i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(ICollection<>));

        if (!isCollection)
        {
            continue;
        }

        Type genericType = property.PropertyType.GetGenericArguments()[0];
        Type collectionType = typeof(ICollection<>).MakeGenericType(genericType);

        ParameterExpression param = Expression.Parameter(collectionType, "value");
        MemberExpression countProperty = Expression.Property(param, "Count");
        var lambda = Expression.Lambda(
            typeof(Func<,>).MakeGenericType(collectionType, typeof(int)),
            countProperty,
            param);
        Delegate getCount = lambda.Compile();
        property.ShouldSerialize = (_, value) =>
        {
            return getCount.DynamicInvoke(value) is int count && count > 0;
        };
    }
}
```
