### ISSUE TITLE
Incorrect value provided by DirectoryInfo.Attributes when directory does not exist

### ISSUE THREAD

**Issue by DWAK-ATTK** [dotnet/runtime#108345]
### Description

When DirectoryInfo.Exists is `false`, DirectoryInfo.Attributes == -1.

However, DirectoryInfo.Attributes is an enum (FileAttributes) with the [Flags] attribute applied.  So when you do DirectoryInfo.Attributes.HasFlag(any flag value here) on a directory that doesn't exist, HasFlag(...) always returns true.  But since the directory does not exist, a more correct result would be **false**.

Of course we can check Exists before Attributes.HasFlag(), but that seems more like a workaround and something that should be handled by the library.  

Rather than setting DirectoryInfo.Attributes == -1, perhaps make it == 0 (zero; FileAttributes.None)

### Reproduction Steps

```
DirectoryInfo dir = new DirectoryInfo(@"J:\hot-potato\something-that-will-never-exist");
bool exists = dir.Exists;    // false
bool isEncrypted = dir.Attributes.HasFlag(FileAttributes.encrypted);  // true
```

### Expected behavior

DirectoryInfo.Attributes.HasFlag(...) should return false if the directory does not exist.

### Actual behavior

It returns true.

### Regression?

No idea.

### Known Workarounds

Check the Directory.Info.Exists property fist.

### Configuration

dotnet 8.0 on Windows 11

**Comment by jkotas** [comment]
This is expected documented behavior. From https://learn.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.attributes: "If the path doesn't exist as of the last cached state, the return value is (FileAttributes)(-1).". Changing it would be a breaking change.

**Comment by DWAK-ATTK** [comment]
Thank you Jan. It is not intuitive, given the nature of Flags. Perhaps it is a breaking change worth making. Personally, I would prefer a language and environment that did expected things. I don’t care for the idea that my tools can’t be made better because we didn’t think of that when they were designed. On Sep 28, 2024, at 8:05 AM, Jan Kotas ***@***.***> wrote:﻿
This is expected documented behavior. From https://learn.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.attributes: "If the path doesn't exist as of the last cached state, the return value is (FileAttributes)(-1).". Changing it would be a breaking change.

**Comment by jeffhandley** [comment]
Thanks for filing this and for the feedback, @DWAK-ATTK. It's understandable that this wasn't intuitive for your experience. This particular breaking change would be very disruptive and risky, so it wouldn't be justified. We will need to continue relying on the documentation explaining the behavior.
