### ISSUE TITLE
[wasm] LibraryTests_Threading test failure during assembly load

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#108394]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=811917
Build error leg or test failing: LibraryTests_Threading

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Could not load type of field 'System.Runtime.InteropServices.JavaScript.JSSynchronizationContext",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 9/30/2024 2:37:43 PM UTC

**Comment by pavelsavara** [comment]
Duplicate https://github.com/dotnet/runtime/issues/102615 https://github.com/dotnet/runtime/issues/106067
