### ISSUE TITLE
Unable to Install dotnetcore2 on macOS ARM64 (M1, M2, M3) Using Poetry

### ISSUE THREAD

**Issue by elisasimoni** [dotnet/runtime#108316]
**Environment:**

**OS**: macOS ARM64 (M3 Silicon)
**Tool**: Poetry
**Description**: I am unable to install the dotnetcore2 package as a dependency for my project. The installation fails with the following error:

```
Cannot install azureml-dataprep-rslex.

  - Installing dotnetcore2 (3.1.23): Failed

  RuntimeError

  Unable to find installation candidates for dotnetcore2 (3.1.23)

  at ~/.pyenv/versions/3.10.15/lib/python3.10/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install dotnetcore2.

```
**Steps to Reproduce:**

- Use a macOS ARM64 device (M1, M2, M3).
- Create a new Poetry project or use an existing one.
- Add dotnetcore2 as a dependency in pyproject.toml.
- Run poetry install.

**Expected Behavior**: The dotnetcore2 package should be installed successfully.

**Actual Behavior:** The installation fails with the error mentioned above.

**Additional Information:**

- Workarounds using Docker or Conda are not acceptable for this project.
- It would be ideal to fix this issue as it affects many users, and a solution has been awaited for years.
- Any guidance or workaround to resolve this issue would be greatly appreciated.

**Comment by jkotas** [comment]
cc @leecow

**Comment by leecow** [comment]
As mentioned in the 2 issues you reference, we are not contributors to the dotnetcore2 project. Whoever owns the wheel will need to provide the update. Given how long it's been since the last update, I would encourage you to choose a different path (such as [dotnet-install.sh](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)) to acquire the official, and up to date, .NET builds.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing per recent comments.
