### ISSUE TITLE
RandomAccess.Write throws System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by miroslavp** [dotnet/runtime#108322]
### Description

`RandomAccess.Write(SafeFileHandle handle, IReadOnlyList<ReadOnlyMemory<byte>> buffers, long fileOffset)` throws `IOException` on Windows platform when the bytes in the `buffers` list exceed `Int32.MaxValue`

Here's the relevant stack trace
```
System.IO.IOException: The parameter is incorrect.
 at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
 at System.IO.RandomAccess.WriteGatherAtOffset(SafeFileHandle handle, IReadOnlyList`1 buffers, Int64 fileOffset)
```
I suspect the problem is in the `bytesWritten` variable, because it is `int` and it overflows

https://github.com/dotnet/runtime/blob/01aa3d96bb2160144f167b1065e081521d133b48/src/libraries/System.Private.CoreLib/src/System/IO/RandomAccess.Windows.cs#L435-L446

### Reproduction Steps

Just call RandomAccess.Write(handle, buffers, 0) on Windows machine where `buffers` parameter contains multiple `ReadOnlyMemory<byte>` buffers that collectively are larger than 2GB

### Expected behavior

It should save the buffers to the file and not throw IOException

### Actual behavior

throws System.IO.IOException: The parameter is incorrect.

### Regression?

Haven't tried it on .NET 6

### Known Workarounds

I guess you can split the buffers in multiple smaller lists and call the method multiple times

### Configuration

Which version of .NET is the code running on?
**.NET 7**

What OS and version, and what distro if applicable?
**Windows 10**

What is the architecture (x64, x86, ARM, ARM64)?
**x64**

Do you know whether it is specific to that configuration?
**I believe the problem is in the Windows implementation only**

**Comment by adamsitnik** [comment]
@miroslavp thank you for a detailed bug report. You are right, it's a bug. Since you have found the place that requires the fix, would you like to send a PR with a fix?

**Comment by NicoAvanzDev** [comment]
I've opened a pull request with the fix for this issue. Let me know if it's ok for you guys. Thanks you all !

**Comment by miroslavp** [comment]
> @miroslavp thank you for a detailed bug report. You are right, it's a bug. Since you have found the place that requires the fix, would you like to send a PR with a fix?

Thank you, but I prefer not to. I don't feel confident enough to do that. If you guys can fix it, that would be awesome.

**Comment by NicoAvanzDev** [comment]
> > @miroslavp thank you for a detailed bug report. You are right, it's a bug. Since you have found the place that requires the fix, would you like to send a PR with a fix?
> 
> Thank you, but I prefer not to. I don't feel confident enough to do that. If you guys can fix it, that would be awesome.

I've created a PR with the fix and performed testing on it https://github.com/dotnet/runtime/pull/108380
