### ISSUE TITLE
Allow a single Span to have multiple underlying buffers "stiched" together as one

### ISSUE THREAD

**Issue by toupswork** [dotnet/runtime#108313]
### Background and motivation

It would be nice if I had multiple buffers of the same type, and I could provide a new virtual buffer that is composed of those buffers as if they were joined together, end-to-end, as one buffer, and could be accessed via a span. Otherwise, you would have to create a new instance of a buffer that is the size of the sum of the other buffers, then copy the values into the new instance. So maybe something like Span.Join(). That way you could reduce heap allocations.

### API Proposal

```csharp
namespace System.Collections.Generic;

public ref struct Span<T> 
{
    public Span<T> Join(Span<T> other);
}
```

### API Usage

```csharp
byte[] buffer1 = [1, 2 , 3];
byte[] buffer2 = [4, 5, 6];

Span<byte> composite = buffer1.AsSpan().Join(buffer2.AsSpan());
foreach (var v in composite)
    Console.Write(v);  // 123456
```

### Alternative Designs

Make a new type that is for this purpose

### Risks

Span would no longer be representing a contiguous set of memory, which will probably be a non-starter for this idea. It would have to hold multiple pointers for each join. Slicing would be challenging..

**Comment by huoyaoyuan** [comment]
> Span would no longer be representing a contiguous set of memory, which will probably be a non-starter for this idea.

This is the critical blocker. All of the low level methods are accessing spans continuously with SIMD instructions. There has to be another type for this.

Further more, since spans can't be stored onto heap, it's hard to make a dynamic list of it. This proposal is barely not actionable.

On the other hand, chaining buffers on the heap is much more actionable, and there's already `ReadOnlySequence<T>` for this.

**Comment by toupswork** [comment]
> > Span would no longer be representing a contiguous set of memory, which will probably be a non-starter for this idea.
> 
> This is the critical blocker. All of the low level methods are accessing spans continuously with SIMD instructions. There has to be another type for this proposal.
> 
> Further more, since spans can't be stored onto heap, it's hard to make a dynamic list of it. This proposal is barely not actionable.
> 
> On the other hand, chaining buffers on the heap is much more actionable, and there's already `ReadOnlySequence<T>` for this.

Oh WOW. Thank you! That will work. Let me close this.
