### ISSUE TITLE
[API Proposal]: ValidationResult constructor with a single member name

### ISSUE THREAD

**Issue by mariusz96** [dotnet/runtime#108338]
### Background and motivation

When implementing `IValidatableObject` it is common to return only a single `memberName` but `ValidationResult` requires a collection:
```csharp
public class SomeDto : IValidatableObject
{
    public string SomeProperty { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (SomeProperty.Contains("Invalid"))
        {
            yield return new ValidationResult("Some property is invalid.", [nameof(SomeProperty)]);
        }
    }
}
```

### API Proposal

```diff
namespace System.ComponentModel.DataAnnotations;

public ValidationResult
{
+    public ValidationResult(string? errorMessage, string memberName)
}
```

### API Usage

```csharp
public class SomeDto : IValidatableObject
{
    public string SomeProperty { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (SomeProperty.Contains("Invalid"))
        {
            yield return new ValidationResult("Some property is invalid.", nameof(SomeProperty));
        }
    }
}
```

**Comment by tarekgh** [comment]
Can't you do 

```C#
            ValidationResult vr = new ValidationResult("Some property is invalid.", [nameof(SomeProperty)]);
```

I am not seeing this worth exposing a new API to avoid writing two extra bracket characters. Note, even if we exposed this the implementation will still need to convert it to `IEnumerable<string>` anyway.

**Comment by mariusz96** [comment]
> Can't you do
> 
> ```cs
>             ValidationResult vr = new ValidationResult("Some property is invalid.", [nameof(SomeProperty)]);
> ```
> 
> I am not seeing this worth exposing a new API to avoid writing two extra bracket characters. Note, even if we exposed this the implementation will still need to convert the member's name to `IEnumerable<string>` anyway.

Yes, that would be a convenience constructor. It kinda does not make sense to require a collection when that's a minority of cases.

**Comment by tarekgh** [comment]
> Yes, that would be a convenience constructor. It kind of does not make sense to require a collection when that's a minority of cases.

`ValidationResult` designed to return a collection anyway. Considering it is easy to provide a single value the way I mentioned before, I am going to close this issue and watch out if we get more demand on this request which we can consider in the future. Thanks for your report.
