### ISSUE TITLE
Polymorphic JSON deserialization hangs indefinitely in native AOT since .NET 9 Preview 7

### ISSUE THREAD

**Issue by cfbao** [dotnet/runtime#108329]
### Describe the bug

When used in native AOT apps, System.Text.Json's polymorphic deserialization hangs the program indefinitely.

### To Reproduce

Create project with `dotnet new console --aot` and use the following code:

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

Console.WriteLine("start");
var res = JsonSerializer.Deserialize(
	"""
	{
		"$type": "person",
		"Name": "John"
	}
	""",
	MyJsonContext.Default.Base
);

Console.WriteLine($"result: {res}");

[JsonDerivedType(typeof(Person), "person")]
abstract record Base();

record Person(string Name) : Base;

[JsonSerializable(typeof(Base))]
internal partial class MyJsonContext : JsonSerializerContext;
```

Then publish the app with `dotnet publish` and start the resulting executable.
The program will hang before printing `result: ...`.

### Further technical details

Issue did not exist in .NET SDK 9.0.100-preview.6.24328.19.
Issue started appearing in .NET SDK 9.0.100-preview.7.24407.12 and persists in 9.0.100-rc.1.24452.12.
Issue can be observed on both Windows 10 and WSL2 (Ubuntu 22.04).

**Comment by eiriktsarpalis** [comment]
Sounds like a potential duplicate of https://github.com/dotnet/runtime/issues/107740. Are you able to reproduce using the RC2 bits?

**Comment by cfbao** [comment]
Took some fiddling to figure out how to use RC2 but got it working.
I can no longer repro with RC2. Seems like it's resolved then. Great!
