### ISSUE TITLE
Allowing SortedDictionary.Remove while enumerating

### ISSUE THREAD

**Issue by szmcdull** [dotnet/runtime#108374]
### Description

Similar to https://github.com/dotnet/runtime/issues/26314
It is especially useful when removing all keys smaller/bigger than a value in a SortedDictionary.

**Comment by Clockwork-Muse** [comment]
A better way to phrase this would be "Provide SortedDictionary.RemoveAll with predicate", which is what the other issue is actually about for Dictionary.  

Note that allowing concurrent modification during iteration is an inherently hard problem, and unlikely to happen, while the implementation proposed and implemented in the other issue has advantages due to working with internal state.

**Comment by Clockwork-Muse** [comment]
If this is an API proposal, reviewing the docs and then conforming this issue to the template as listed [here](https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#writing-a-good-api-proposal) would be appreciated

**Comment by szmcdull** [comment]
Emm, I'm asking for exactly what the title says. Simply allowing Remove() inside an iteration, no need to allow concurrent modification, no need to change the API definition.

**Comment by Clockwork-Muse** [comment]
> Simply allowing Remove() inside an iteration, no need to allow concurrent modification

That _is_ a concurrent modification - modifying a collection while iterating it is not supported on any (non-threadsafe) collection, because it requires certain implementation constraints which were not taken.  It is extremely unlikely this will be relaxed, **especially** on a combination of ordered/map collection like this, which has additional internal burdens.

**Comment by rampaa** [comment]
> modifying a collection while iterating it is not supported on any (non-threadsafe) collection

https://github.com/dotnet/runtime/issues/31303#issuecomment-546482254

**Comment by PranavSenthilnathan** [comment]
In the `Dictionary<T,R>` case, there were two conditions that informed the decision:
1) The internal data structures are amenable to enumeration while removal is happening (when not done concurrently)
2) Providing removal while iteration was an improvement over the alternative which would be to `ToArray` the dictionary and Remove while iterating the array instead.

The sorted dictionary (and sorted set) is implemented in a way that removal(s) can change the internal data structure significantly. It's a balanced binary tree so removal can rotate its nodes and result in a tree that could be significantly different. So without changing the implementation of the tree (e.g. adding parent pointers would make this easier but would cost an extra storage slot per node), condition (1) is not met.

As for condition (2), there are no optimizations that we could do inside the sorted dictionary that you wouldn't be able to do in your code. For example, if you look at the following: https://github.com/dotnet/runtime/blob/643ffd83faf035ed7a8398773f64a18d06777356/src/libraries/System.Collections/src/System/Collections/Generic/SortedSet.cs#L1428-L1454

You can see that all we are doing is just creating a `List<T>` of items to remove, populating the list by enumerating the dictionary, and then removing each item one-by-one.

As an aside, there is a argument to be made if you wanted to do this without allocating a `List<T>` in which case a `bool TryGetNextItem(T item current, out T item)` API might be helpful so you could iterate with 
```cs
while (dictionary.TryGetNextItem(currentKey, out KeyValuePair<K,V> next)) 
{
  currentKey = next.Key;
  /* remove or add to dictionary */ 
}
```

The downside is that `TryGetNextItem` would be `O(log(n))` so it's slower if you're not modifying the dictionary. Either case, this is a separate issue and would need its own API review/approval if you wanted this.

/cc @stephentoub for his thoughts

**Comment by stephentoub** [comment]
I agree with @PranavSenthilnathan. While being able to remove while enumerating is helpful, allowing it was only possible opportunistically in dictionary based on its exact implementation. A similarly-simple "just allow it" isn't possible for a tree-based structure like SortedDictionary.
