### ISSUE TITLE
Dependency changes when building a self contained application in SDK version 8.0.303 to 8.0.401

### ISSUE THREAD

**Issue by MartBentNedap** [dotnet/runtime#108354]
### Describe the bug
The library depedencies of our self-contained dotnet application change when building with version 8.0.401 instead of 8.0.303. As far as I can tell this should not be possible since it is a minor version change.

### To Reproduce
We reproduce the issue by building our application with the follow command:

`dotnet publish TestApplication/TestApplication.csproj -c Release -p:Version=$VERSION -o $CI_PROJECT_DIR/out/ -r linux-arm /p:PublishTrimmed=true --self-contained /p:PublishSingleFile=true -f net6.0`

The docker image used is **mcr.microsoft.com/dotnet/sdk:8.0**. This image contains SDK version 8.0.401.

When running the application on our Linux device, we run into the following error:
`./TestApplication: /lib/libc.so.6: version 'GLIBC_2.27' not found (required by ./TestApplication)`

But when we build with image: **mcr.microsoft.com/dotnet/sdk@sha256:e9f45219cca08134f09cb973de3e8364d5a22ad30dfff1343830003c6494a735** This error does NOT occur, this image uses SDK version 8.0.303.

It is not easily reproduce able since it is a non-public Linux distribution. Let me know if any more information is required.

### Further technical details
- output of `uname -a` on our device: `Linux FX96006B9E16 4.9.182-rt131-yocto-standard dotnet/sdk#1 PREEMPT Mon Aug 14 11:47:31 IST 2023 armv7l GNU/Linux`

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/pull/103266 switched from building linux-arm on [ubuntu-16.04-cross-20210719121212-8a8d3be](https://github.com/dotnet/runtime/pull/103266/files#diff-2881651e1406daa378c20fc4e5f44076627224ba2f8e76f09fc8d067df17f382L41) to [ubuntu-18.04-cross-arm-20220907130538-70ed2e8](https://github.com/dotnet/runtime/pull/103266/files#diff-4a6db477eddd66599614e0f5e26b2639059b6ff777cc975c02c5a72866ff55dcR8). It explains the bump in the minimal glibc version.

@amanasifkhalid Was this intentional change?

**Comment by amanasifkhalid** [comment]
#108396 has been merged. @MartBent are you ok with using an older SDK until the next release?

**Comment by MartBentNedap** [comment]
Yes that is fine with me. Which version will include the fix? or will I get notified when it has been released?

**Comment by amanasifkhalid** [comment]
The fix should be included in the .NET Runtime 6.0.36 release. If you'd like, I can ping you here once it's available.

**Comment by MartBentNedap** [comment]
That would be great! thanks for solving this in such a promptly manner.

**Comment by amanasifkhalid** [comment]
Hi @MartBentNedap, just following up to let you know 6.0.36 is now available; you can download it from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). Please note that .NET 6 has reached end of support, though I'd appreciate it if you could report back here and let me know if your issue has been resolved with 6.0.36. Thanks!

**Comment by MartBentNedap** [comment]
> Hi [@MartBentNedap](https://github.com/MartBentNedap), just following up to let you know 6.0.36 is now available; you can download it from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). Please note that .NET 6 has reached end of support, though I'd appreciate it if you could report back here and let me know if your issue has been resolved with 6.0.36. Thanks!

We use docker image mcr.microsoft.com/dotnet/sdk:8.0 to build our application. 
The output of of `dotnet --list-sdks` is: `8.0.404 [/usr/share/dotnet/sdk]`

does this fix also apply for dotnet sdk 8.0.404? or am I missing something? we use the `-f net6.0` flag to build the app

**Comment by amanasifkhalid** [comment]
> does this fix also apply for dotnet sdk 8.0.404? or am I missing something? we use the -f net6.0 flag to build the app

Your SDK version should be fine for building with `-f net6.0`, but without updating your .NET 6 runtime version to `6.0.36`, I would expect you to get the same error as above (`./TestApplication: /lib/libc.so.6: version 'GLIBC_2.27' not found (required by ./TestApplication)`) when you try to run your app. Could you please try installing the latest .NET 6 runtime, re-running your application, and let me know how it goes? Thanks!

**Comment by MartBentNedap** [comment]
> > does this fix also apply for dotnet sdk 8.0.404? or am I missing something? we use the -f net6.0 flag to build the app
> 
> Your SDK version should be fine for building with `-f net6.0`, but without updating your .NET 6 runtime version to `6.0.36`, I would expect you to get the same error as above (`./TestApplication: /lib/libc.so.6: version 'GLIBC_2.27' not found (required by ./TestApplication)`) when you try to run your app. Could you please install the latest .NET 6 runtime, rerun your application, and let me know how it goes? Thanks!

I just tested the new runtime and the application now runs without any issues. So the issue is resolved for us. Thanks again for the quick reply and for fixing this issue.
