### ISSUE TITLE
[API Proposal]: GeneratedCodeAttribute should have additional constructors

### ISSUE THREAD

**Issue by baywet** [dotnet/runtime#108443]
### Background and motivation

When applying a GeneratedCodeAttribute, the generator might not want to set the tool name or version.
The version is especially challenging when the generation tool gets updated, generated code refreshed. Now all of a sudden all generated files produce a diff, even if they have no other changes.
This class currently has single constructor where the parameters are nullable. And it does not perform any validation on the passed values. Nor does it use them afterwards beyond exposing them as properties.
Yes a generator could pass null for the version, but this is not elegant and slows down compilation for large code bases (one more symbol to link * n attributes)

My suggestion is to either make the parameters optional or to add two more constructors (one without parameters, one with just the name)

### API Proposal

```csharp
namespace System.CodeDom.Compiler;

[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
public sealed class GeneratedCodeAttribute : Attribute
{
    //This constructor exists like that today
    public GeneratedCodeAttribute(string? tool, string? version)
    {} //omitted for brevity
    // suggesting to update to this
    public GeneratedCodeAttribute(string? tool = null, string? version = null)
    {} //omitted for brevity 
}
```

### API Usage

```csharp
[GeneratedCode]
public class Foo
{}
```

### Alternative Designs

Overload constructors like this

```csharp
namespace System.CodeDom.Compiler;

[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
public sealed class GeneratedCodeAttribute : Attribute
{
    //This constructor exists like that today
    public GeneratedCodeAttribute(string? tool, string? version)
    {} //omitted for brevity
    // suggesting to add these
    public GeneratedCodeAttribute(string? tool):this(tool, null) {}
    public GeneratedCodeAttribute():this(null, null) {}
}
```

### Risks

none I can think of.

**Comment by CyrusNajmabadi** [comment]
> Yes a generator could pass null for the version, but this is not elegant and slows down compilation for large code bases (one more symbol to link * n attributes)

I don't see why elegance matters here. It's generated code.  There's also no slowdown here.  The compiler is going to be faster going through the route where two literals are passed to required arguments vs no arguments passed to optional arguments.

**Comment by baywet** [comment]
Thank you for the additional information.

So the advice here would be to pass null and move on?

**Comment by buyaa-n** [comment]
> The version is especially challenging when the generation tool gets updated, generated code refreshed. Now all of a sudden all generated files produce a diff, even if they have no other changes.

Could you explain this part more, it looks to me when passing a same value or null for `tool` and `version` would not produce any diff. Seems really depend your usage.

System.CodeDom is a mature and legacy library, we don't consider new APIs or API changes unless there is a good reason, and I don't see a value of making this change this API, please check the [contribution bar](https://github.com/dotnet/runtime/tree/main/src/libraries/System.CodeDom#contribution-bar) for this library

**Comment by baywet** [comment]
> The compiler is going to be faster going through the route where two literals are passed to required arguments vs no arguments passed to optional arguments.

Assuming this is true passing null to the version in my scenario should mitigate the diff issue.
Closing.
