### ISSUE TITLE
Bug in IndexOf with InvariantCultureIgnoreCase in .NET 5 and above?

### ISSUE THREAD

**Issue by rhalaly** [dotnet/runtime#108424]
### Description

We found a weird behavior in the `IndexOf` method of strings.

 The official Unicode specs regarding [Special Casing](https://unicode.org/Public/UNIDATA/SpecialCasing.txt) claims that the upper case of the character `ﬆ` is `ST`.

And as expected the following comparison, returns true.
```csharp
string.Equals("eﬆ", "est", System.StringComparison.InvariantCultureIgnoreCase) // returns True
```

When we go to the `IndexOf` method, the following code returns 0, which is expected, as we saw that both string are equivalent under invariant culture and ignore case.
```csharp
"eﬆ".IndexOf("est",  System.StringComparison.InvariantCultureIgnoreCase) // returns 0
```

However, when we use any letters from the English alphabet or spaces at the beginning of the string, we starting to get -1. But if we use some other letters (Cyrillic, Arabic, Hebrew, Latin with umlauts), it gives proper result again. Example in the next section.

### Reproduction Steps

```csharp
"eﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 0 ✅
" eﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // -1 (Why?)
" ﬆ".IndexOf("st", System.StringComparison.InvariantCultureIgnoreCase); // 1 ✅
"ccceﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // -1 (Why?)
"ćććeﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
"אאאeﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
"фффeﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
```

### Expected behavior

The expected behavior is that `IndexOf` will behave in the same way no matter the other characters in the string. So in the examples where we got -1
```csharp
" eﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // -1 (Why?)
"ccceﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // -1 (Why?)
```
We will get 1 and 3, respectively.

### Actual behavior

The actual behavior is that `IndexOf` with InvariantCultureIgnoreCase is not constant and may return wrong output based on surrounding string content.

```csharp
" eﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // -1 (Why?)
"ccceﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // -1 (Why?)
```

### Regression?

We get the observed results under .NET 5 and above. In .NET Framework 4.7.2 we get the expected results:

```csharp
"eﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 0 ✅
" eﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 1 ✅
" ﬆ".IndexOf("st", System.StringComparison.InvariantCultureIgnoreCase); // 1 ✅
"ccceﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
"ćććeﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
"אאאeﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
"фффeﬆ".IndexOf("est", System.StringComparison.InvariantCultureIgnoreCase); // 3 ✅
```

### Known Workarounds

Turning of the usage of ICU can solve that issue, but this is unwanted workaround, since other part of the code uses the ICU logic.

### Configuration

.NET 5, .NET 6, .NET 7, .NET 8
Windows 11
x64, x86

**Comment by tarekgh** [comment]
This is fixed now, and the fix is ported to 8.0 and 9.0 releases too.
