### ISSUE TITLE
FileStream Not Suppressing Finalization on Dispose Call

### ISSUE THREAD

**Issue by StasPerekrestov** [dotnet/runtime#108465]
### Description

Hello,
I’ve been monitoring my app running in a Docker container and recently examined its memory dump. 
One thing that stood out was the presence of FileStream instances in the Finalization Queue.
![image](https://github.com/user-attachments/assets/85b91a4c-1187-4a4a-9c15-d2b6a3f7700f)

These instances are created by the `OpenTelemetry.Instrumentation.Process` library, which I use to gather metrics. 
On Linux, the library reads from the /proc/self/status file pretty often, using FileStream for this task(via System.Diagnostics.Process), and it appears to dispose of the streams correctly.

However, during my investigation, I noticed something interesting about the FileStream class. 
When Dispose is called, FileStream does not suppress finalization, meaning it remains in the Finalization Queue. 
In contrast, calling DisposeAsync [does suppress finalization](https://github.com/dotnet/runtime/blob/e6d9f74bb6383daf71ed70a5a6ec4b07d58f9d9b/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L529).

```c#
        // _strategy can be null only when ctor has thrown
        protected override void Dispose(bool disposing) => _strategy?.DisposeInternal(disposing);

        public override async ValueTask DisposeAsync()
        {
            await _strategy.DisposeAsync().ConfigureAwait(false);

            // For compatibility, derived classes must only call base.DisposeAsync(),
            // otherwise we would end up calling Dispose twice (one from base.DisposeAsync() and one from here).
            if (!_strategy.IsDerived)
            {
                Dispose(false);
                GC.SuppressFinalize(this);
            }
        }
```

Is this behavior intentional, or is there an opportunity for improvement in the Dispose implementation to align it with DisposeAsync?

Thank you in advance.

### Reproduction Steps

1. Open a file and obtain a FileStream instance.
2. Call Dispose on the FileStream instance.
3. Inspect the Finalization Queue to verify if the FileStream remains in it.

### Expected behavior

The FileStream shouldn't appear in the Finalization Queue

### Actual behavior

The FileStream gets into the Finalization Queue

### Regression?

Related task https://github.com/dotnet/runtime/pull/80439

**Comment by stephentoub** [comment]
cc: @adamsitnik

**Comment by bartonjs** [comment]
`Dispose()` on `FileStream` comes from `Stream`:

https://github.com/dotnet/runtime/blob/a593d9cd39355593e87c6cb8c876c52f4bf5145f/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L156-L165

Assuming that `FileStream.Dispose(true)` isn't throwing an exception, it will return to `FileStream.Close()` which calls `GC.SuppressFinalize(this)`.

FileStream values might end up on the finalizer queue if they aren't being disposed of, which you might be seeing.

A quick sample shows that disposing is calling SuppressFinalize.  If you're seeing something different, please share a repro.

```C#
using System;
using System.IO;

namespace FileStreamFinal
{
    internal static class Program
    {
        internal static void Foo()
        {
            using (new DerivedFileStream("Program.cs")) {}
            new DerivedFileStream("FileStreamFinal.csproj");
        }

        internal static void Main()
        {
            Foo();

            GC.Collect();
            GC.Collect();
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.WaitForPendingFinalizers();
            GC.WaitForPendingFinalizers();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Done");
        }
    }

    internal sealed class DerivedFileStream : FileStream
    {
        private readonly string _path;

        internal DerivedFileStream(string path)
            : base(path, FileMode.Open)
        {
            _path = path;
        }

        ~DerivedFileStream()
        {
            Console.WriteLine($"Finalized {_path}");
        }
    }
}
```

Prints only "Finalized FileStreamFinal.csproj", showing the other one was correctly suppressed.

**Comment by StasPerekrestov** [comment]
@bartonjs I've created a demo repo. https://github.com/StasPerekrestov/FileStreamFinalizerDemo

Please run it in a docker.

From what I can see, it prints "Done" only.

Thank you.

**Comment by jkotas** [comment]
The runtime is free to extend the lifetimes of local variables till end of the method.

In your example, there is a hidden variable created for the result `new DerivedFileStream("FileStreamFinal.csproj");` that keeps the instance alive till end of the method and prevents the garbage collection from collecting it. It explains the behavior that you are seeing.

If you want to be certain that the instance gets collected by garbage collector, you have to exit the method where it was referenced and mark that method with `[MethodImpl(MethodImplOptions.NoInlining)]` attribute.

**Comment by sperekrestov** [comment]
Indeed, the `GC.SuppressFinalize(this);` is called in Stream. 
I appreciate the clarification and am sorry for the false report.

It looks like the [original issue](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2100#issue-2546012797) I've been dealing with has a different nature and results in FileStreams leaking into the finalization queue.

I'll try to get a 100% reproducible scenario before getting back.
