### ISSUE TITLE
.NET 8: String interpolation with IPAddress has breaking change

### ISSUE THREAD

**Issue by justinswork** [dotnet/runtime#108491]
### Description

When I do string interpolation for a class that extends `System.Net.IPAddress`, it does not use the `ToString` override that is defined on that class.

### Reproduction Steps

```
using System.Net;

namespace ConsoleApp1
{
	public class Program
	{
		static void Main()
		{
			var ip = GenerateIPAddress();
			var string1 = $"http://{ip}";
			Console.WriteLine(string1);
			// Creating a URI with an IPv6 address throws in .NET 8
			var uri = new Uri(string1);
			Console.WriteLine("URI created");
		}

		static MyIpAddress GenerateIPAddress()
		{
			byte[] bytes = new byte[16];
			new Random().NextBytes(bytes);
			return new MyIpAddress(bytes);
		}
	}

	public class MyIpAddress : IPAddress
	{
		public MyIpAddress(byte[] address) : base(address)
		{
		}

		public override string ToString()
		{
			return $"[{base.ToString()}]";
		}
	}
}
```
### Expected behavior

In .NET 6/7, the IPAddress string is wrapped in `[]` and the URI works as expected
```
http://[2303:e4ab:41c5:37c1:35e7:8350:a32f:8f9]
URI created
```

### Actual behavior

In .NET 8, the IPAddress string is not wrapped, and the URI throws a `UriFormatException: Invalid URI: Invalid port specified`
```
http://6fad:a2e6:4b12:6839:775b:702c:2cc1:b448
```

### Regression?

This is a regression for IPv6 addresses.

**Comment by MihaZupan** [comment]
Interesting, this is likely because `IPAddress` now implements `ISpanFormattable`, which is preferred by the string interpolation over `ToString`.

You should be able to get back the expected behavior if you override the `TryFormat` method.

**Comment by antonfirsov** [comment]
Is there a reason the `ISpanFormattable` implementation omits `[]`?

**Comment by justinswork** [comment]
@MihaZupan has string interpolation always preferred that over `ToString`? Can you show this documented somewhere?

**Comment by MihaZupan** [comment]
> Is there a reason the ISpanFormattable implementation omits `[]`?

Our implementation is the same for both ToString and ISpanFormattable.
The issue is that the existence of the new interface means the user-defined ToString overload won't be called anymore. In this case that means the lack of square brackets that the derived type wanted to add.

> has string interpolation always preferred that over ToString?

I believe that has been the case since the initial introduction of [interpolated string handlers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/improved-interpolated-strings#the-handler-pattern).
It'll depend on the handler implementation, but at least the default one prefers the `ISpanFormattable`.

What changed in .Net 8 is that IPAddress now implements this interface.

**Comment by justinswork** [comment]
> You should be able to get back the expected behavior if you override the `TryFormat` method.

It looks like `TryFormat` is not a virtual method. Am I misunderstanding what you meant?

**Comment by justinswork** [comment]
I wonder if any consideration was given to just including the `[]` in both the `ToString` and `TryFormat` of the `IPAddress` for IPv6 addresses? The fact that URI doesn't work without them seems like it should be included by default.

**Comment by justinswork** [comment]
> While it's not virtual, you can implement the `ISpanFormattable` interface on your derived type, and any calls to it will then bind to your implementation instead.

I see...

Well for anybody who may stumble across this post in the future, this is how I solved the problem. A bit more clunky than I'd like just to add the necessary square brackets, but it solves the problem.

```
	public class MyIpAddress : IPAddress, ISpanFormattable
	{
		public MyIpAddress(byte[] address) : base(address)
		{ }

		public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
		{
			TryFormat(destination, out charsWritten);
			ShiftSpan(destination, 0);
			destination[0] = '[';
			charsWritten++;
			ShiftSpan(destination, charsWritten);
			destination[charsWritten] = ']';
			charsWritten++;
			return true;
		}

		private static void ShiftSpan(Span<char> span, int startIndex)
		{
			if (span.Length <= 1 || startIndex < 0 || startIndex >= span.Length - 1)
			{
				return; // No need to shift if the span is too small or if startIndex is out of bounds.
			}

			// Save the last element that will be shifted.
			char last = span[span.Length - 1];

			// Shift each element starting from startIndex to the right.
			for (int i = span.Length - 1; i > startIndex; i--)
			{
				span[i] = span[i - 1];
			}

			// Set the element at startIndex to the saved last element.
			span[startIndex] = last;
		}
	}
```

**Comment by teo-tsirpanis** [comment]
@justinswork you can simplify `TryFormat` like this and remove `ShiftSpan` (disclaimer, I haven't tested it):

```csharp
public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
{
	if (!TryFormat(destination[1..], out charsWritten) || destination.Length < charsWritten + 2)
	{
		// Not enough space
		return false;
	}
	destination[0] = '[';
	charsWritten++;
	destination[charsWritten] = ']';
	charsWritten++;
	return true;
}
```

**Comment by MihaZupan** [comment]
It can be as simple as
```c#
public override string ToString() => $"[{base.ToString()}]";

bool ISpanFormattable.TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) =>
	destination.TryWrite($"{ToString()}", out charsWritten);
```

> I wonder if any consideration was given to just including the [] in both the ToString and TryFormat of the IPAddress for IPv6 addresses?

I don't know whether it was an oversight initially, but at this point changing the behavior would break tons of users since the type has always worked like this.

**Comment by justinswork** [comment]
@MihaZupan thanks!

**Comment by MihaZupan** [comment]
Triage: If we see more people running into this issue, we should document it as a breaking change, but we're unlikely to change behavior here. The workaround is to implement the `ISpanFormattable` interface as discussed above.
