### ISSUE TITLE
[cdac] Implement GetPEFileBase

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#108450]
For the ["clrma" APIs](https://github.com/dotnet/diagnostics/blob/main/documentation/clrma.md), we need to implement the `ISOSDacInterface::GetPEFileBase` DAC API

The brittle DAC version is here:

https://github.com/dotnet/runtime/blob/68d84782674ffaa16edb7f0b42b4eeaf9ca7751c/src/coreclr/debug/daccess/request.cpp#L2606-L2627

Part of https://github.com/dotnet/runtime/issues/99298

**Comment by lambdageek** [comment]
This will be very similar to https://github.com/dotnet/runtime/pull/106358

**Comment by max-charlamb** [comment]
Implemented in #108602
