### ISSUE TITLE
AV in clr in CI during `CEEInfo::getArgType` call

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#108586]
Not much to go on here... Only have the CI run and haven't been able to repro locally.

Pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=827029&view=ms.vss-test-web.build-test-results-tab&runId=21503658&resultId=211149&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
Console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-ab9ace9939a746d080/System.Collections.Immutable.Tests/1/console.39c50eaa.log?helixlogtype=result

```scala
C:\h\w\B4ED097B\w\A7EC092A\e>"C:\h\w\B4ED097B\p\dotnet.exe" exec --runtimeconfig System.Collections.Immutable.Tests.runtimeconfig.json --depsfile System.Collections.Immutable.Tests.deps.json xunit.console.dll System.Collections.Immutable.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Collections.Immutable.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Immutable.Tests (found 4292 of 4397 test cases)
  Starting:    System.Collections.Immutable.Tests (parallel test collections = on [4 threads], stop on fail = off)

Assert failure(PID 3968 [0x00000f80], Thread: 4892 [0x131c]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffa`5c015316)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffa`5bfc31a6)
CORECLR! CEEInfo::getArgType + 0xA0C (0x00007ffa`5bec434c)
CLRJIT! Compiler::lvaInitTypeRef + 0x349 (0x00007ffa`5b93fdf9)
CLRJIT! Compiler::compCompileHelper + 0x319 (0x00007ffa`5b80a6c9)
CLRJIT! Compiler::compCompile + 0x8F8 (0x00007ffa`5b809ba8)
CLRJIT! `jitNativeCode'::`8'::__Body::Run + 0xE2 (0x00007ffa`5b805b72)
CLRJIT! jitNativeCode + 0x155 (0x00007ffa`5b810055)
CLRJIT! CILJit::compileMethod + 0x169 (0x00007ffa`5b817899)
CORECLR! invokeCompileMethod + 0x203 (0x00007ffa`5bee8b53)
CORECLR! UnsafeJitFunction + 0x83B (0x00007ffa`5bebd22b)
CORECLR! MethodDesc::JitCompileCodeLocked + 0x1D2 (0x00007ffa`5bf94962)
CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x50D (0x00007ffa`5bf951ed)
CORECLR! MethodDesc::JitCompileCode + 0x5A9 (0x00007ffa`5bf94689)
CORECLR! MethodDesc::PrepareILBasedCode + 0x4F2 (0x00007ffa`5bf97012)
CORECLR! MethodDesc::PrepareCode + 0xF3 (0x00007ffa`5bf96ac3)
CORECLR! MethodDesc::PrepareInitialCode + 0x132 (0x00007ffa`5bf971b2)
CORECLR! MethodDesc::DoPrestub + 0xCF5 (0x00007ffa`5bf8f555)
CORECLR! PreStubWorker + 0x476 (0x00007ffa`5bf9bdb6)
```

There is a win-x64 dump available.

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
Dup of #108360 #107892 #107891

The crashing HasCustomModifier call was added recently in https://github.com/dotnet/runtime/pull/106424/files#diff-98b4e379205d747e922689cb993f985be190fedb509fd486e99280c842703472R9471-R9477 . cc @jkoritzinsky

**Comment by jkotas** [comment]
This is a bug in the checks added by #106424. The problem is that `PeekElemTypeClosed` substitutes the element type found in the signature using generic context and ELEMENT_TYPE_INTERNAL. If any of this substitution takes place.  `HasCustomModifier ` is going to interpret unexpected bytes in the signature. If these bytes look like a custom modifier, we may see the crash above or other types of misbehavior.

@jkoritzinsky PTLA
