### ISSUE TITLE
More frequent timeout on outbound request after upgrading to .net 8

### ISSUE THREAD

**Issue by dxynnez** [dotnet/runtime#108599]
### Description

After upgrading from .net 6 to .net 8 without any functional change, we observed more frequent timeouts for outbound requests:
 1) made using the httpclient (hitting the default 100s timeout and the target never received the request) 
 2) made using the StackExchange.Redis client (which is based on the socket & pipeline) - For redis, the symptom is quite similar to an issue reported a while back: https://github.com/dotnet/runtime/issues/102312

**Is there any guidance on how to troubleshoot such issue? We suspect this might have something to do with the threadpool but couldn't find any obvious change between .net 6 & .net 8 that might have caused the issue.**

Note: the test was performed on an Azure VM with 2 vCores.

### Configuration

* Which version of .NET is the code running on? .Net 8
* What OS version, and what distro if applicable? Windows and not AOT
* What is the architecture (x64, x86, ARM, ARM64)? x64
* If relevant, what are the specs of the machine? Azure VM with 2 vCPUs and 8GB memory

### Regression?

more outbound request timeout than .Net 6 & the average duration for outbound request significantly increased than .Net 6.

**Comment by ManickaP** [comment]
@dxynnez you can always do a packet capture and/or collect .NET counters/telemetry. On top of that, elimination method might help as well: try it out with pure HttpClient and reduce the code as much sa possible, try it out with .NET 7, try it out on Linux...

Either way, there isn't enough info for us to provide more help atm.

**Comment by ManickaP** [comment]
> is that something we can start with?

Yep, please share them.

> that's why we suspect that the problem might be inside the thread pool

Have you tried debugging this? Collecting dump and looking into it if there's contention.

Some more questions that may or may not help: Is your usage concurrent (many requests in parallel)? Do you do sync-over-async somewhere? Could you try with the latest greatest .NET 9?

Either way, as I said earlier, this is guessing from my side and throwing random suggestions. Without repro, without some reduction of the problem, without logs/traces/packet capture, this is just not actionable. It's up to you to debug this in your environment.
