### ISSUE TITLE
Cannot step over Debugger.Break() in m3 lldb

### ISSUE THREAD

**Issue by successgo** [dotnet/runtime#108541]
### Description

Using lldb and sos to debug .net, while write below C# code:

```csharp
Debugger.Break();
```

it will generate below asm:

```asm
->  0x10087ba38 <+0>: brk    #0
    0x10087ba3c <+4>: ret
```

but it never step over the `brk`, the only way to modify `pc` register manually.

### Reproduction Steps

```
using System.Diagnostics;

namespace ConsoleApp1;

class Program
{
    static void Main(string[] args)
    {
        Debugger.Break();
    }
}
```

Compile and launch with lldb and run it.

### Expected behavior

Enter `ni` to step over `brk`.

### Actual behavior

Always hitting the `brk`.

### Known Workarounds

Modify the `pc` register manully.

**Comment by janvorli** [comment]
I believe that's a limitation of lldb.

**Comment by janvorli** [comment]
However, maybe using another brk instruction flavor might help: https://stackoverflow.com/questions/75934525/stepping-over-brk-instructions-in-lldb-on-aarch64

**Comment by janvorli** [comment]
I will try to make such a change and see.

**Comment by janvorli** [comment]
That worked! I am going to create a PR with a fix
