### ISSUE TITLE
Geo Spatial Analysis in .NET Core 10

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/runtime#108536]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to do Geo spatial analysis, and feature collection and mapping with real time data analysis.

### Describe the solution you'd like

If we can build a .NET library in .NET 10 such like, assume there is a satellite and in another way, there is a drone, carrying a LiDAR to map the field, buildings and objects, using C# and .NET libraries it enhance the technology to detect the area, plot the area into mapping and render the 3D image on the real time data.

**Comment by jeffhandley** [comment]
I concur with @amcasey -- this is a very domain-specific area that would be too specialized for building as part of the core .NET libraries.

**Comment by SoumyadipYT-OSS** [comment]
Thank you @jeffhandley Sir I will check this issue on dotnet-runtime community.
