### ISSUE TITLE
Enable arcade -sign functionality in runtime

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#108605]
Right now runtime uses a bit of custom infra to sign (a separate job that gathers intermediate artifacts and signs them). For the VMR, it also needs to support the ability to do the traditional arcade-based signing. When -sign is passed, Sign.proj is invoked, items to sign is populated, etc. etc.

**Comment by ViktorHofer** [comment]
@jkoritzinsky please see my PR https://github.com/dotnet/runtime/pull/100004 which does a lot of what we want here. We don't need the PostBuildSign stuff in it but everything else uses the Arcade integration.
