### ISSUE TITLE
 Error in RuntimeInstance::GetThreadStore when calling a method from a static library.

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#108644]
The project compiles successfully, but upon startup an exception appears with code -1073741819.

The line in the code that is causing the error:
https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/RuntimeInstance.cpp#L43

My csproj file: https://pastebin.com/raw/mZi6k33s

```csharp
        [UnmanagedCallersOnly(EntryPoint = "console_writeLine", CallConvs = [typeof(CallConvCdecl)])]
        public static void Write()
        {
            Console.WriteLine("Hello World!");
        }
```
exception:
![image](https://github.com/user-attachments/assets/3903b908-4df8-4f02-b233-3c38f3488ea9)

Disassembled code at the exception location:
![image](https://github.com/user-attachments/assets/a77d85be-d84e-499c-8d53-b9ae83012c51)

Linker Console Options: https://pastebin.com/raw/YFmgq5SH

```cpp
#include <stdio.h>

void __cdecl console_writeLine(void);

int main()
{
    console_writeLine();

    return getchar();
}
```

I would be grateful for your help.

**Comment by MichalStrehovsky** [comment]
This typically happens when the runtime wasn't initialized. C standard library is supposed to ensure this before anything else in the module runs through this code:

https://github.com/dotnet/runtime/blob/43295bb5378453d2ec4d9272cb44c6f50b4faa1f/src/coreclr/nativeaot/Bootstrap/main.cpp#L239-L245

Looks like this didn't happen in your case, probably because of how the static library was linked.

Building static libraries [is unsupported](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/libraries) because of problems like this. We can't troubleshoot this for you. Can you use a shared library instead?

**Comment by dadavadd** [comment]
> Обычно это происходит, когда среда выполнения не была инициализирована. Стандартная библиотека C должна гарантировать это до того, как что-либо еще в модуле пройдет через этот код:
> 
> https://github.com/dotnet/runtime/blob/43295bb5378453d2ec4d9272cb44c6f50b4faa1f/src/coreclr/nativeaot/Bootstrap/main.cpp#L239-L245
> 
> Похоже, в вашем случае этого не произошло, вероятно, из-за способа подключения статической библиотеки.
> 
> Создание статических библиотек [не поддерживается](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/libraries) из-за таких проблем. Мы не можем устранить эту неполадку за вас. Можете ли вы использовать общую библиотеку вместо этого?

What other information should I provide you with? Where is the initialization location, and how do I call it? I really need the static library to work
.

**Comment by dadavadd** [comment]
> Обычно это происходит, когда среда выполнения не была инициализирована. Стандартная библиотека C должна гарантировать это до того, как что-либо еще в модуле пройдет через этот код:
> 
> https://github.com/dotnet/runtime/blob/43295bb5378453d2ec4d9272cb44c6f50b4faa1f/src/coreclr/nativeaot/Bootstrap/main.cpp#L239-L245
> 
> Похоже, в вашем случае этого не произошло, вероятно, из-за способа подключения статической библиотеки.
> 
> Создание статических библиотек [не поддерживается](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/libraries) из-за таких проблем. Мы не можем устранить эту неполадку за вас. Можете ли вы использовать общую библиотеку вместо этого?

What information should I provide you with? Can you tell me which initialization is in question

**Comment by MichalStrehovsky** [comment]
Building static libraries is possible, but unsupported. This has been inactive for a month. It's unlikely to get any more traction, closing.
