### ISSUE TITLE
[API Proposal]: And Uri.TryCreate(params...) Equivalent API: Uri.Create(params....)

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#108652]
### Background and motivation

Looking through the documentation for the System.Uri class, I found that the Uri class has only a static TryCreate() method that returns a Boolean value and a Uri value with other parameters that need to be qualified with out. There is no static Create method in the document that directly returns the Uri value. So I want to extend the Uri class to implement a static Create() method.

I mainly use the static Create() method that can be used directly in the Xaml binding of UWP or WinUI with no additional operations.
A similar combination API exists in other classes, such as Enum.Parse(params...). And Enum.TryParse(params...) , Guid.Parse(params...) And Guid.TryParse(params...)

###-----------------------------------------

我查阅有关 System.Uri 类的相关文档中，发现 Uri 类只有一个静态的 TryCreate() 方法，该方法返回布尔值，通过其他参数（该参数需要使用 out 修饰）返回 Uri 值。在文档中没有静态的 Create 方法直接返回 Uri 值。所以希望能扩展 Uri 类，实现一个静态的 Create() 方法。

我主要使用静态的 Create() 方法可以直接用在 UWP 或 WinUI 的 Xaml 绑定中，而不需要额外的操作。
这样相似的组合 API 在其他类也出现过，比如 Enum.Parse(params...) 和 Enum.TryParse(params...)，Guid.Parse(params...) 和 Guid.TryParse(params...)

### API Proposal

```csharp
namespace System;

public class Uri : ISpanFormattable, System.Runtime.Serialization.ISerializable
{
    public static Uri Create (Uri? baseUri, Uri? relativeUri);

    public static Uri Create (Uri? baseUri, string? relativeUri);

    public static Uri Create (string? uriString, UriKind uriKind);

    public static Uri Create (string? uriString, in UriCreationOptions creationOptions);
}
```

### API Usage

```csharp
// Fancy the value
Uri uri = Uri.Create("https://github.com",UriKind.Absolute);
Console.WriteLine(uri.AbsolutePath)


### Alternative Designs

None

### Risks

None

**Comment by huoyaoyuan** [comment]
The functionalities are exposed by the constructors.

> I mainly use the static Create() method that can be used directly in the Xaml binding of UWP or WinUI with no additional operations.

It's specifically non-goal to duplicate API surface just for satisfying restrictions from any application model. You should create your own helper methods. I had create quite a lot of them for constructing many different types in xaml.

**Comment by MihaZupan** [comment]
Closing as answered as per the above comment - the methods exist as constructors, and it's trivial for the user to expose wrappers if you need a static method equivalent.

**Comment by Gaoyifei1011** [comment]
> Closing as answered as per the above comment - the methods exist as constructors, and it's trivial for the user to expose wrappers if you need a static method equivalent.

Since you mentioned this, I am curious to know why these phenomena exist in other classes. For example, the KeyValuepair. Create static method and new KeyValuePair. The KeyValuepair.create static method is a wrapper around the new KeyValuePair in the source code

###---------------

既然您提到了这个，所以我很想知道在其他类为什么会存在这些现象？比如 KeyValuePair.Create 静态方法和 new KeyValuePair。在源代码中 KeyValuePair.Create 静态方法是对 new KeyValuePair 的一个包装

![{547391B4-B1D7-482A-85F4-D7B6423335DA}](https://github.com/user-attachments/assets/20a54236-d119-4e22-9aee-050d6474efa8)

**Comment by Gaoyifei1011** [comment]
> The functionalities are exposed by the constructors.
> 
> > I mainly use the static Create() method that can be used directly in the Xaml binding of UWP or WinUI with no additional operations.
> 
> It's specifically non-goal to duplicate API surface just for satisfying restrictions from any application model. You should create your own helper methods. I had create quite a lot of them for constructing many different types in xaml.

Since you mentioned this, I am curious to know why these phenomena exist in other classes. For example, the KeyValuepair. Create static method and new KeyValuePair. The KeyValuepair.create static method is a wrapper around the new KeyValuePair in the source code

###---------------

既然您提到了这个，所以我很想知道在其他类为什么会存在这些现象？比如 KeyValuePair.Create 静态方法和 new KeyValuePair。在源代码中 KeyValuePair.Create 静态方法是对 new KeyValuePair 的一个包装

![{547391B4-B1D7-482A-85F4-D7B6423335DA}](https://github.com/user-attachments/assets/20a54236-d119-4e22-9aee-050d6474efa8)

**Comment by huoyaoyuan** [comment]
> For example, the KeyValuepair. Create static method and new KeyValuePair

They are for generic inference. The pattern is used for `KeyValuePair`, `Tuple`, `ValueTuple`, `ImmutableArray`, `Vector128` etc. They are all simple containers for generic elements.

**Comment by julealgon** [comment]
@huoyaoyuan on that front... is there an open proposal for adding proper generic type inference support for constructors? If so, would you mind linking it?

**Comment by huoyaoyuan** [comment]
> is there an open proposal for adding proper generic type inference support for constructors?

It's covered in https://github.com/dotnet/csharplang/discussions/7467 . No concrete decision yet.
