### ISSUE TITLE
How to run unit tests with corerun?

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#108768]
I ran in to a case where I needed to run tests with `corerun` because I cannot use the SDK. This is how I used to do that.

```shell
../../../testhost/net10.0-linux-Debug-arm64/dotnet exec --runtimeconfig \
    System.Security.Cryptography.Tests.runtimeconfig.json xunit.console.dll \
    System.Security.Cryptography.Tests.dll -notrait category=failing -notrait category=OuterLoop
```

It looks like as of #106721, `xunit.console.dll` is no longer in the artifact directory of a test build. I could not find it in `artifacts/bin/System.Security.Cryptography.Tests/Debug/net10.0-unix`

I managed to unblock myself by throwing in `/p:BundleXunitRunner=true` when building the tests.

A couple of questions though

1. What is the "right" way to run the tests with corerun these days?
2. There are a few places where we refer to `xunit.console.dll`, like [here](https://github.com/dotnet/runtime/blob/5cc1eb52d79d5dd4b11205699410dba72b6286b5/docs/workflow/debugging/libraries/debugging-vscode.md?plain=1#L16). Are there various places in documentation that need to be updated?

**Comment by EgorBo** [comment]
You can run any test suite with `$REPO_ROOT/./dotnet.sh build /t:Test` and then you'll see the exact command passed to testhost's corerun, e.g: ` "C:\prj\runtime-main\artifacts\bin\testhost\net10.0-windows-Checked-x64\dotnet.exe" exec --runtimeconfig System.Collections.Immutable.Tests.runtimeconfig.json --depsfile System.Collections.Immutable.Tests.deps.json C:\Users\egorb\.nuget\packages\microsoft.dotnet.xunitconsolerunner\2.9.0-beta.24504.4\build\..\tools\net9.0\xunit.console.dll System.Collections.Immutable.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing` (I am on Windows) for `System.Collections.Immutable.Tests`

**Comment by vcsjones** [comment]
>  C:\Users\egorb\.nuget\packages\microsoft.dotnet.xunitconsolerunner\2.9.0-beta.24504.4\build\..\tools\net9.0\xunit.console.dll

Ah, it has it from nuget. That explains why I couldn't find it anywhere in artifacts.
