### ISSUE TITLE
ARM - Snap Dragon X ELITE - The SDK 'Microsoft.NET.S dk' specified could not be found suddenly since this morning

### ISSUE THREAD

**Issue by ValerioFG** [dotnet/runtime#108749]
### Description

Hi, 
I've logged in to work this morning and I found an odd surprise while trying to debug one of my azure functions. 

c:\test.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

Dotnet info: 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.427
 Commit:    93fddcf4f6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.427\

global.json file:
  Not found

Host:
  Version:      6.0.35
  Architecture: arm64
  Commit:       b357f86ce3

.NET SDKs installed:
  6.0.427 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

Donet --list-sdks: 

`6.0.427 [C:\Program Files\dotnet\sdk]`

Env variables relevant to dotnet: 

`%USERPROFILE%\.dotnet\tools`

I've tried to: 
unistall - reinstall dotnet 6

Create a new project in a new folder with:
dotnet new cosole

When it tries to restore / build the error is produced. 

PS C:\DevOps\> dotnet restore
C:\DevOps\Process.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk
' specified could not be found.
PS C:\DevOps\Process> dotnet build
MSBuild version 17.3.4+a400405ba for .NET
C:\DevOps\Process.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk
' specified could not be found.

Build FAILED.

C:\DevOps\ELCI v2\ELCI\Modules\TrustID\TrustIdProcess\TrustIdProcess.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk
' specified could not be found.
    0 Warning(s)
    1 Error(s)

Csporj file: 
```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```
Any help with this? 

I'm having issue since I switched to ARM and always have to add/fix stuff manually.

### Reproduction Steps

dotnet build / dotnet restore

### Expected behavior

code should compile 

### Actual behavior

c:\test.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

**Comment by am11** [comment]
This belongs to dotnet/sdk repository. You may want to try https://stackoverflow.com/a/78618480/863980 or similar solutions or install dontet 8 sdk alongside dotnet 6, so the dotnet host is newer (with more robust handling for non-x64 architectures).

side note: net6. will be out of support next month, maybe it's a good time to upgrade to net8.0 LTS. 🙂

**Comment by ValerioFG** [comment]
Hi Am11, 
thank you for your answer.

An update on my side: 

-Adding MSBuildSDKsPath as C:\Program Files\dotnet\sdk\6.0.427\Sdks\ worked. I can now build / run code again.

Not sure why it was suddenlty gone.
