### ISSUE TITLE
[macos]  ld: library not found for -ld_classic when using non-xcode clang

### ISSUE THREAD

**Issue by jkurdek** [dotnet/runtime#108717]
While setting up the dotnet/runtime repository on a test macOS machine (macOS 12), I ran into an issue with conflicting versions of clang. The machine had LLVM installed via Homebrew, which made the LLVM version of clang take priority in the system’s PATH over the Xcode version.

This mix-up caused flags meant for a higher Xcode version to be included, leading to the error ld: library not found for -ld_classic when trying to build dotnet/runtime tests.

https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L256-L263

**Comment by jkotas** [comment]
Both the repo build script and native AOT build targets expects that the native build toolchain is properly configured. If your native build toolchain is misconfigured, you can see all sorts of weird errors.

**Comment by MichalStrehovsky** [comment]
What Jan said. I don't know what we could do here.

The error message could be better (I would expect it to complain "-ld_classic is an unrecognized parameter" or something), but the decision to encode the new parameter in a way that makes it ambiguous between "I want to link to library named d_classic" and "I want classic linker in the apple-specific build of clang" is on Apple.
