### ISSUE TITLE
SslStream.AuthenticateAsClientAsync has periodically spikes (every 5 minutes).

### ISSUE THREAD

**Issue by predatorfromekb** [dotnet/runtime#108721]
### Description

Hello everyone,

I have a .NET application running in Docker. This application connects to a server using the MQTT protocol with SSL at regular intervals (every few seconds).

While monitoring connection times, I observed that every **5 minutes**, the connection time shows a spike. Typically, the connection time is around **20 ms**, but every 5 minutes it jumps to about **100 ms**. These spikes are evenly distributed and look like this on Grafana: 

![Image](https://github.com/user-attachments/assets/e2372a0f-c585-45ae-817a-b810cc0aa0e6)

So after investigating, i found that this delay is caused by the following method:
```
await sslStream.AuthenticateAsClientAsync(sslOptions);
```
[source code](https://source.dot.net/#System.Net.Security/System/Net/Security/SslStream.cs,394)

Diving deeper into the problem, I discovered that the majority of the delay occurs between [Line 1049](https://source.dot.net/#System.Net.Security/System/Net/Security/SslStream.Protocol.cs,1049) and [Line 1109](https://source.dot.net/#System.Net.Security/System/Net/Security/SslStream.Protocol.cs,1109) lines in the SslStream class. This part of the code is where the remote certificate is validated after being downloaded.

No one settings from class SslClientAuthenticationOptions was helpful for this case. The best way i found is to set field _remoteCertificate using reflection https://source.dot.net/#System.Net.Security/System/Net/Security/SslStream.Protocol.cs,ad240959828f0ecc, but its not a good solution.

So the best solution is to find a reason of this behavior (maybe some env variable/ value in os config/ some constaint in some class responsible for this interval)

I create a small demo-project, where i left only the elements necessary for the demonstration: https://github.com/predatorfromekb/ssl-connect-delay-example

to build and start, you need to run `docker-compose up --build`

### Configuration

.net 8
docker images: mcr.microsoft.com/dotnet/runtime:8.0, mcr.microsoft.com/dotnet/sdk:8.0, but also used some other tags (for ubuntu, alphine, ...)

### Regression?

The problem reproduces only in docker container. On pc with windows it works fine.

### Analysis

I think that [this code](https://source.dot.net/#System.Net.Security/System/Net/Security/SslStream.Protocol.cs,1100) can executes conditionally, but didnt find how to do this.

**Comment by wfurt** [comment]
Can you reproduce this when using `SslStreamCertificateContext` instead of just the certificate? The server _should_ send all the intermediate certificates but if it does not the client would try to download them (by default) to construct chain for validation. You can try to do packet capture to see if there is additional network traffic. 

And it seems like the authentication is mutual. Do you ee the spikes without client certificate? 

Also .NET tries to keep cache if $HOME is writable. You may check if that works as expected. You can perhaps just call `X509Chain.Build` directly to see if you can isolate it to validation.

**Comment by predatorfromekb** [comment]
@bartonjs thanks!

**Comment by rzikm** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/106394
