### ISSUE TITLE
iOS UI Culture for Localisation

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/runtime#108753]
### Description

When the app launches the `SetCulture` method is called, set the apps culture to what the user has saved.
![Image](https://github.com/user-attachments/assets/e8e6a7c7-ddf7-4d6c-9b5f-911f02a685d4)

This works completely fine on Android, but on iOS `StringFormat` in the xaml doesn't use the set culture, and stays as english - 
![Image](https://github.com/user-attachments/assets/edee9ab9-ae9e-498d-ba08-83005b53b008)

I've also tried doing the StringFormat in the model, and it also doesn't work - 
![Image](https://github.com/user-attachments/assets/da0dec60-5ce9-4057-80d0-bd2cd554a89c)

Even setting the culture manually doesn't work - 
![Image](https://github.com/user-attachments/assets/3b607a37-ef7d-4e21-9139-a03682cff801)

_____

It all worked fine in Xamarin.Forms, and it is a valid .NET Culture - 
https://dotnetfiddle.net/lyJP18
![Image](https://github.com/user-attachments/assets/82a4f8fc-66ff-4eb6-a62f-92799add8017)

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No, unless this is fixed, the only way I can see to work around it is to add a property to the API and perform the translation there.

**Comment by matouskozak** [comment]
@IeuanWalker 
The reason is likely the missing culture in the ICU we use for mobile as mentioned by @baaaaif. We try to make a trade-off between supporting full ICU and resulting app size on iOS, so we only included the most common culture names.

I just checked, and it works as expected with .NET 9 RC1. That is because, in .NET 9, we switched from using our own ICU to using the Apple ICU found on devices.

**Comment by IeuanWalker** [comment]
thanks @matouskozak, so in .NET 9 it should just work?

or would I still need to add this to the info.plist?
```xml
<key>CFBundleLocalizations</key>
<array>
    <string>cy</string>
</array>
<key>CFBundleDevelopmentRegion</key>
<string>en</string>
```

**Comment by matouskozak** [comment]
> thanks [@matouskozak](https://github.com/matouskozak), so in .NET 9 it should just work?
> 
> or would I still need to add this to the info.plist?
> 
> <key>CFBundleLocalizations</key>
> <array>
>     <string>cy</string>
> </array>
> <key>CFBundleDevelopmentRegion</key>
> <string>en</string>

Yes, the code that you sent 
```
DateTime now = DateTime.Now;
  		
Console.WriteLine("English: " +  now.ToString("dddd, dd MMMM", new CultureInfo("en-GB")));
Console.WriteLine("Welsh: " +  now.ToString("dddd, dd MMMM", new CultureInfo("cy-GB")));
```
should work as is. 

I believe that https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/localization?view=net-maui-8.0#ios-and-mac-catalyst is necessary if you plan to use localized resources.

**Comment by matouskozak** [comment]
Closing this issue as resolved in .NET 9. Feel free to reopen if needed.
