### ISSUE TITLE
Intermittent "IL Trimmer has encountered an unexpected error"

### ISSUE THREAD

**Issue by robertoberkstresser-faa** [dotnet/runtime#108710]
### Description

Sorry I am not able to provide a lot of detail. It asked me to report the issue. So I did. Error is intermittent. It seems to appear for a build or two and then disappear for a while.

ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink [/Users/builduser/build/workspace/TAP_MOBILE_CLIENT_IOS/TAP_MOBILE_CLIENT_IOS/TAP Mobile/TAP Mobile.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.TypeReferenceWalker.WalkTypeScope(MethodBody body)
     at Mono.Linker.TypeReferenceWalker.WalkScopes(TypeDefinition typeDefinition)
     at Mono.Linker.TypeReferenceWalker.Process()
     at Mono.Linker.Steps.SweepStep.SweepAssemblyReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
/Users/builduser/.nuget/packages/microsoft.net.illink.tasks/8.0.0/build/Microsoft.NET.ILLink.targets(87,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. 

### Reproduction Steps

It seems to be intermittent. Jenkins runs fail and then pass. Then after a while fail again.

### Expected behavior

Not to fail the build

### Actual behavior

Fails the build

### Configuration

.net: 8.0

**Comment by robertoberkstresser-faa** [comment]
Here is a snippet of my project file listing my package references. I don't think any of them are obfuscated. 
 <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="sqlite-net-sqlcipher" Version="1.8.116" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.7" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.7" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.1.7" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlcipher.ios" Version="2.1.7" />
    <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.7" />
    <PackageReference Include="SQLitePCLRaw.provider.internal" Version="2.1.7" />
    <PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.7" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.8.0" />
  </ItemGroup>

**Comment by robertoberkstresser-faa** [comment]
The build is being done on an x86 Mac mini using Mac OS Sonoma 14.5

**Comment by am11** [comment]
> x86

x86-64 right? Just making sure, because in this ecosystem x86 is the 32-bit one and we don't support 32 bit mac binaries. ;)

**Comment by MichalStrehovsky** [comment]
From the above stack it seems like you're using a year old version of the .NET SDK (one that comes with 8.0.0 version of ILLink.Tasks package). Could you try updating to the latest .NET 8 SDK? There have been various reliability fixes in the past year that might have fixed this problem.

**Comment by robertoberkstresser-faa** [comment]
x86-64 correct. I updated to .NET SDK 8.0.403 and that seems to have resolved the issue.

**Comment by agocke** [comment]
Thanks! Closing as resolved
