### ISSUE TITLE
[Apple][x64] EndsWithNoMatch_StringComparison test failure

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#108747]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=827900
Build error leg or test failing: System.Tests.StringTests.EndsWithNoMatch_StringComparison
Affected CI: `maccatalyst_x64_release_allsubsets_mono ( runtime-extra-platforms )` and `iossimulator_x64_release_allsubsets_mono ( runtime-extra-platforms )`
Range of commits: Sometime before https://github.com/dotnet/runtime/commit/fd4d0a9ae99d88f0dca7b5c95005149c641c2211

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.StringTests.EndsWithNoMatch_StringComparison",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[827900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=827900)|dotnet/runtime|[System.Runtime.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=827900&view=ms.vss-test-web.build-test-results-tab&runId=21530986&resultId=206797)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by ivanpovazan** [comment]
Unfortunately, the pattern wasn't recognized by Build Analysis tool.
I would try with:
```json
"ErrorMessage": "[FAIL] System.Tests.StringTests.EndsWithNoMatch_StringComparison"
```

**Comment by matouskozak** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/108832
