### ISSUE TITLE
Difference in Windows and Linux platform for short date format "t", for culture code "zh-CN" (Chinese - People's Republic of China)

### ISSUE THREAD

**Issue by arkadeepsaha-ten** [dotnet/runtime#108845]
### Description

Execution of the following code yields separate results when the API is running directly in Windows vs when it is dockerised and executed in a Linux container

```csharp

var culture = CultureInfo.GetCultureInfo("zh-CN");
return DateTime.UtcNow.ToString("t", culture);

```

On Windows, the output contains an AM/ PM designator with a 12 hr time

```
下午1:00
```

but on executing the code inside a docker container (same windows host machine), the time is in 24hr format

```
13:00
```

Please find attached the screenshots of the same

Output from Windows

![Image](https://github.com/user-attachments/assets/59c1ca41-ba36-468b-a567-d5bc909398e3)

Output from Linux
![Image](https://github.com/user-attachments/assets/2908b06b-888a-4aa3-8d43-5e9c26815cfd)

My dockerfile is as follows. This is a standard dockerfile that is part of the Web Application template. 

```dockerfile
# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["WebApplication1/WebApplication1.csproj", "WebApplication1/"]
RUN dotnet restore "./WebApplication1/WebApplication1.csproj"
COPY . .
WORKDIR "/src/WebApplication1"
RUN dotnet build "./WebApplication1.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./WebApplication1.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```

### Reproduction Steps

1. Open Visual Studio and click on "Create a New Project"
2. Select C# ASP.NET Core Web API as the starter template
3. Give the project a name, Location Path and Solution Name. Click Next
4. For Framework select `.NET 8.0 (Long Term Support)`. The following are the configs I am using. Note that the Container OS is Linux. Click Create.
![Image](https://github.com/user-attachments/assets/555432e4-5b86-4b7b-9c33-3cbf2bf947ba)
5. Visual studio will create an starter project for you. The project has 1 controller called `WeatherForecastController`
6. Replace the implementation of the Get() method with the following
```csharp
[HttpGet(Name = "GetWeatherForecast")]
public string Get()
{
    var culture = CultureInfo.GetCultureInfo("zh-CN");
    return DateTime.UtcNow.ToString("t", culture);
}
```
You will need to include the namespace `System.Globalization`
7. Now you have a minimum working piece of code to be able to reproduce the issue.
8. When this code is executed on a Linux container, the output is different that when it is executed on my windows machine directly
### Expected behavior

For the same given short time format "t", I was expecting the output should be consistent between the 2 platforms. Either both of them should be in 12hr format, or both should be in 24hr format.

### Actual behavior

The expected output is platform dependent

### Configuration

Framework details:
- .NET 8 (LTS)
- Windows version: 
```
Edition: Windows 11 Enterprise
Version: 23H2
Installed on: ‎12-‎07-‎2023
OS build: 22631.4169
Experience: Windows Feature Experience Pack 1000.22700.1034.0
```
- Docker image details provided above. Link for docker hub page: https://hub.docker.com/r/microsoft/dotnet-aspnet
- This is the only culture code which causes this issue in our code base. Not sure if this exists for other culture codes or system configs as well
- I had found a similar issue for dates (https://github.com/dotnet/runtime/issues/18345), but nothing for time

**Comment by huoyaoyuan** [comment]
The cultural formats data are defined by Unicode CLDR and provided by the operating system. They do vary from version to version. See also #108742 and similars.

To require a change, you should go to https://cldr.unicode.org/ .

**Comment by Clockwork-Muse** [comment]
In general:
 - If it's for display to the user, take whatever the localization system gives you and output it without further inspection or modification.  Note this can and will be different on different machines, including otherwise identical ones (and potentially even different processes on the same machine).
 - If it's for persistence/transmission/logging, use the invariant culture (and normally one of the roundtrip formats).

**Comment by tarekgh** [comment]
@huoyaoyuan is correct. To give more info:

In the latest CLDR data, the zh-CN locale inherits the short time format from the root locale which uses `HH:mm` without the AM/PM designators. 

https://github.com/unicode-org/cldr/blob/62f93db946d955158f4f4e4afa79d931e7888608/common/main/root.xml#L1345

Linux container is using ICU v72 which reflects that. Most likely running on Windows, using an older version of the ICU (v68 or so). 

In general, please use the guidelines mentioned by @Clockwork-Muse.

**Comment by arkadeepsaha-ten** [comment]
Thank you for the insight. Is this mentioned anywhere in the official docs?

**Comment by Clockwork-Muse** [comment]
I don't know of anything where we explicitly spell this out.

There's some comments around this in the [testing recommendations](https://learn.microsoft.com/en-us/dotnet/core/extensions/best-practices-for-developing-world-ready-apps#recommendations-for-robust-testing) and immediately before that.

Generally this is just one of those "you're expected to learn about this" (somehow?) topics, like the issues with floating point.

**Comment by arkadeepsaha-ten** [comment]
Thank you @tarekgh 
I came across the following link after looking as the discussion here and searching for "ICU globalization C#" on Google
https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

Earlier, I was looking at https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings and could not find any mention of this, which is why I put in that comment. It will probably be helpful to mention this as part of https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#how-standard-format-strings-work

**Comment by tarekgh** [comment]
@arkadeepsaha-ten thanks for the feedback. Feel free to log doc issue in https://github.com/dotnet/dotnet-api-docs/ or even open PR to add your suggestion.

**Comment by huoyaoyuan** [comment]
Tested on Windows 24H2, `DateTime.UtcNow.ToString("t", new CultureInfo("zh-CN"))` is printing the 24H format. It seems that Windows has updated to the latest data in newer version.
