### ISSUE TITLE
Process.StandardOutput.ReadAsync read data super slowly

### ISSUE THREAD

**Issue by vivek4434** [dotnet/runtime#108894]
### Description

I am trying to spin up ssh.exe as sub-process to interact with network device using ConsoleApp (.net8). I have to use ReadAsync API as i need to read complete data (irrespective of the fact if there is a newline or not). I am observing ReadAsync is responding super slow (compared to when i try to manually run ssh.exe). I have a waittime for 20ms to ensure data is available for read.

### Data

To even read 500 bytes it is taking multiple seconds.

### Analysis
When i am running `show version` command, i need to wait upto 20 secs to receive the device prompt (which indicate command finished).

```c#
private async Task GetIncomingBuffer()
        {
            ushort noDataAvailableAttempt = 0;
            try
            {
                char[] window = new char[1024];
                StringBuilder buf = new StringBuilder();
                bool pendingRead = true;
                while (!cancellationTokenSource.Token.IsCancellationRequested)
                {
                    var len = await process.StandardOutput.ReadAsync(window, 0, 1024).ConfigureAwait(false);

                    if (len > 0)
                    {
                        // Resetting counter.
                        noDataAvailableAttempt = 0;
                        for (int i = 0; i < len; i++)
                        {
                            buf.Append(window[i]);
                            if (window[i] == '\n' || window[i] == '\r')
                            {
                                this.incoming.Enqueue(buf.ToString());
                                buf.Clear();
                                pendingRead = false;
                                continue;
                            }

                            pendingRead = true;
                        }

                        if (pendingRead)
                        {
                            // last line do not have \n or \r so explicitly add it.
                            this.incoming.Enqueue(buf.ToString());
                            buf.Clear();
                            pendingRead = false;
                        }
                    }
                    else
                    {
                        noDataAvailableAttempt++;
                        if (noDataAvailableAttempt % noDataReadLogFrequency == 0)
                        {
                            this.logger.LogInfo("No data availabe for read...");
                            noDataAvailableAttempt = 0;
                        }
                    }

                    await Task.Delay(20).ConfigureAwait(false);
                }
            }
            catch (Exception ex)
            {
                this.logger.LogWarning($"Error in GetIncomingBuffer: {ex.Message}");
            }
        }
```

**Comment by huoyaoyuan** [comment]
The reading code looks questionable. `ReadAsync` returns 0 means the stream has reached its end (EOF), not "no data available".

**Comment by vivek4434** [comment]
@huoyaoyuan - since ssh is will be an interactive session meaning, i need to keep trying to read the data. If i stop (assuming EOF) then it won't make sense and for the same reason i added a message - "No data available".

**Comment by huoyaoyuan** [comment]
If the stream is still active but no data available, the `Task` from `ReadAsync` will block until any byte is available. EOF isn't "you stop" - it's the stream has already stopped.

Is `StandardOutput.ReadLineAsync` functioning well?

**Comment by vivek4434** [comment]
Else condition should be harmless right?

ReadLineAsync, ReadBlockAsync skips the last line (as there is no new line). But for my case i need complete data specifically the last line because based on that i need decide if next command needs to be ran or not.

**Comment by stephentoub** [comment]
@vivek4434 asked the same question offline and it was resolved as not being a .NET issue.
