### ISSUE TITLE
Suggestion: Support Member Functions and Static Functions in C# Enumerations

### ISSUE THREAD

**Issue by soul-soft** [dotnet/runtime#108897]
Dear .NET Community Team,

I would like to propose a suggestion regarding the C# language, discussing the possibility of supporting member functions and static functions within enumeration types. As application requirements grow more complex, we find that enumerations need more flexible functionalities to better manage and extend related business logic.

Background
Currently, enumerations in C# are primarily used to define a fixed set of constant values. While this is sufficient for simple scenarios, we encounter limitations when dealing with logic related to enumeration values. The inability to directly include methods within enumeration types leads to less intuitive implementations, often causing reduced maintainability of the code.

Scenario Example
Consider the following scenario where I define an enumeration named FileExtensionsType, representing different file extensions.

``` C#
public enum FileExtensionsType
{
    Png,
    Jpeg,
    Gif,
    Doc,
    Pdf,
    Xls,

    // Assuming we could define a static function here
    public static IEnumerable<FileExtensionsType> GetImageTypes()
    {
        yield return FileExtensionsType.Png;
        yield return FileExtensionsType.Jpeg;
        yield return FileExtensionsType.Gif;
    }

    // Assuming we could define a member function here
    public string GetDescription()
    {
        switch (this)
        {
            case FileExtensionsType.Png:
                return "Portable Network Graphics";
            case FileExtensionsType.Jpeg:
                return "Joint Photographic Experts Group";
            case FileExtensionsType.Gif:
                return "Graphics Interchange Format";
            case FileExtensionsType.Doc:
                return "Microsoft Word Document";
            case FileExtensionsType.Pdf:
                return "Portable Document Format";
            case FileExtensionsType.Xls:
                return "Microsoft Excel Spreadsheet";
            default:
                return "Unknown File Type";
        }
    }
}
```

In this example, I wish to embed both the GetImageTypes static method and the GetDescription member function directly within the enumeration, making the related logic clearer and more straightforward.

## Need for Member Functions

1. Behavior Related to State: Allowing enumerations to define behaviors related to their own state would be beneficial. For instance, the GetDescription method can provide detailed descriptions for each file type, enabling a more intuitive understanding of each enumeration value without referencing external documentation or conversion tables.
2. Code Readability and Maintainability: By binding related logic directly to the enumeration, we reduce reliance on external utility classes or dictionaries, thereby improving the readability and maintainability of the code.## Need for Static Functions

1.Common Helper Methods: Supporting static functions like GetImageTypes within enumerations would allow for the provision of relevant helper methods, simplifying the way developers utilize that enumeration.

**Comment by colejohnson66** [comment]
Language requests go in [dotnet/csharplang](https://github.com/dotnet/csharplang).

**Comment by soul-soft** [comment]
ok!

**Comment by huoyaoyuan** [comment]
Kindly reminder that it's helpful to find the existing discussion link in csharplang. Most of proposed language features would be covered by existing ones.
