### ISSUE TITLE
runtimeconfig.json does not work with Single File App

### ISSUE THREAD

**Issue by ppekrol** [dotnet/runtime#108814]
### Description

According to https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

```
Runtime configuration files, such as *.runtimeconfig.json and *.deps.json, are included in the single file. If an extra configuration file is needed, you can place it beside the single file.
```

I've tried doing that with our app, but it does not work.

### Reproduction Steps

1. Create console app

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
		<RetainVMGarbageCollection>true</RetainVMGarbageCollection>
	</PropertyGroup>

</Project>
```

Program.cs
```
using System.Runtime;

Console.WriteLine($"IsServerGC: {GCSettings.IsServerGC}");
```

2. `dotnet publish -c Release -r win-x64 --self-contained`
3. Run exe
Output:
```
IsServerGC: True
```
4. Edit ConsoleApp1.runtime.config in the publish directory and change "System.GC.Server" to false
5. Run exe
Output:
```
IsServerGC: False
```

Now let's publish Single File App:

6. `dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true`
7. Run exe
Output:
```
IsServerGC: True
```
8. Place beside exe file `ConsoleApp1.runtimeconfig.json` (tried also `runtimeconfig.json`
9. Run exe
Output:
```
IsServerGC: True
```

### Expected behavior

Single File App should respect runtimeconfig.json according to the documentation.

### Actual behavior

Single File App does not respect runtimeconfig.json

**Comment by am11** [comment]
@elinor-fung, should the logs indicate that runtimeconfig.json is read from the bundle? Currently, logs do not depict the reality:

```zsh
% COREHOST_TRACE=1 dist/app1
...snip...
DepsJson Offset:[494fab0] Size[6354]
RuntimeConfigJson Offset:[a50000] Size[177]
.net core 3 compatibility mode: [No]
--- Executing in a native executable mode...
Using dotnet root path [/Users/am11/app1/dist/]
App runtimeconfig.json from [/Users/am11/app1/dist/app1.dll]
Runtime config is cfg=/Users/am11/app1/dist/app1.runtimeconfig.json dev=/Users/am11/app1/dist/app1.runtimeconfig.dev.json
Attempting to read dev runtime config: /Users/am11/app1/dist/app1.runtimeconfig.dev.json
Attempting to read runtime config: /Users/am11/app1/dist/app1.runtimeconfig.json
Mapped bundle for [/Users/am11/app1/dist/app1.runtimeconfig.json]
Unmapped application bundle
Runtime config [/Users/am11/app1/dist/app1.runtimeconfig.json] is valid=[1]
Executing as a self-contained app as per config file [/Users/am11/app1/dist/app1.runtimeconfig.json]
Using internal hostpolicy
Reading from host interface version: [0x16041101:248] to initialize policy version: [0x16041101:248]
...snip...
```

(`Executing as a self-contained app as per config file` gets printed regardless that file exists 😅)

**Comment by agocke** [comment]
@elinor-fung's description matches my understanding as well. Closing now that docs have been updated.

**Comment by ppekrol** [comment]
Ok, that makes thing more clean, but I do have a question now. Is there a possibility to not embedd the runtimeconfig.json in the Single File App and place it beside the executable?
