### ISSUE TITLE
CET breaks function call evaluation while debugging on corerun

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#108812]
### Description

After #103311 Visual Studio is no longer able to evaluate function calls while debugging coreclr with corerun.

### Reproduction Steps

To reproduce, set a breakpoint in coreclr code and run debug session against corerun. After hitting the breakpoint, use the watch window in VS to execute some function calls, for example, if you set the breakpoint in JIT code you can try executing `m_compiler->compCodeOpt()`.

### Expected behavior

Function call being evaluated correctly.

### Actual behavior

Occurred an unhandled exception during evaluation, the evaluation has been terminated.

**Comment by tommcdon** [comment]
Hi @hez2010! Can you confirm that this only reproduces with native expression evaluation (while using the native debug engine in Visual Studio)?  If yes, then I suggest opening a Visual Studio feedback item and closing this issue - https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022.

**Comment by hez2010** [comment]
I only tested the native debug engine. Not sure whether this repros with the managed one. 
I'll open an item on Visual Studio feedback.

**Comment by tommcdon** [comment]
Thanks! I will close this issue as this is likely a VS debugger issue.
