### ISSUE TITLE
Base64Url.Try* should not throw

### ISSUE THREAD

**Issue by silmon27** [dotnet/runtime#108834]
### Description

Should the `Base64Url.Try*` methods really throw exceptions for invalid data? It is my understanding that `Try*` methods are supposed to not throw exceptions, but rather to return false to indicate failure.
Currently the `Base64Url.TryDecodeFromUtf8` and `Base64Url.TryDecodeFromChars` methods return false for some cases but throw exceptions for others (such as invalid characters). This behavior is unexpected, deviates from the standard convention and has unnecessary performance impact.

### Reproduction Steps

Base64Url.TryDecodeFromChars("invalid data", bytes, out var bytesWritten)

### Expected behavior

Should return false for all invalid inputs rather than throwing an exception.

### Actual behavior

Throws a System.FormatException "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."

### Configuration

.NET 9 RC 2

**Comment by MihaZupan** [comment]
`Try` methods are expected to only use the return value for one failure case.
In this case, that is whether the destination buffer is large enough to fit the whole result. The expectation is that the caller will react to a `false` result by expanding the buffer and calling the method again. If the method returned `false` for invalid data as well, the caller wouldn't know how to react, as growing the buffer wouldn't help.

If you need to distinguish between the two without the overhead of exceptions, you should use the [`DecodeFromUtf8`](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.text.base64url.decodefromutf8?view=net-9.0#system-buffers-text-base64url-decodefromutf8(system-readonlyspan((system-byte))-system-span((system-byte))-system-int32@-system-int32@-system-boolean)) overload that returns an `OperationStatus` enum.

**Comment by silmon27** [comment]
I see. I wasn't aware of that "one failure case" convention.

However, isn't this approach very confusing? How is one supposed to know what this specific failure case is without looking at the source code? The Base64 counterpart handles it more logically: `Convert.TryFromBase64Chars` has the same method signature and does the same thing as `Base64Url.TryDecodeFromChars`, yet it simply returns false and doesn't throw an exception for invalid data. This behavior is consistent with most, if not all, TryParse-like methods in .NET. I believe this is the more expected behavior.

**Comment by stephentoub** [comment]
> How is one supposed to know what this specific failure case is without looking at the source code?

By looking at the documentation. If the docs are insufficient, we should fix the docs.

> This behavior is consistent with most, if not all, TryParse-like methods in .NET. I believe this is the more expected behavior.

It's not. Such methods also only return false for one logical condition, e.g. Int32.TryParse will still throw an exception if you pass in invalid options.

> The Base64 counterpart handles it more logically: Convert.TryFromBase64Chars has the same method signature and does the same thing as Base64Url.TryDecodeFromChars, yet it simply returns false and doesn't throw an exception for invalid data. 

Which is problematic for other reasons. In particular, consider a common formatting loop with a try method: you pass in some destination space, and if the space isn't sufficiently long, you need to grow the buffer and try again. If the Try method returned false for conditions other than that one case meaning lack of available destination space, this loop would run until it OOM'd when presented with invalid input.

The fact that Convert.TryFromBase64Chars deviates from that is a known deficiency / bug in the method but one we can no longer fix as it would be too breaking to do so.

**Comment by silmon27** [comment]
I see your point, that makes sense.

My assumption was that TryParse methods main scenario is parsing input, returning false if it can’t because e.g. the input is invalid. While incorrect arguments or options should indeed throw exceptions, i.e. like Int32.TryParse. But I see how this approach becomes problematic in cases like this.

The documentation does mention the FormatException, but also states "returns true if bytes decoded successfully, otherwise false," which aligns with the behavior of classic methods like Int32.TryParse.

Thank you for clarifying this.

**Comment by stephentoub** [comment]
@buyaa-n, can you look at improving the docs here? Thanks.

**Comment by bartonjs** [comment]
99.99% of the time, if a "Try" method is writing to a destination Span, the false return means the destination is too small, and any other error will be an exception.  In Framework Design Guidelines, 3rd edition, this is called the "TryWrite" pattern.

This is different from TryParse, where 99.99% of the time the false means "the input does not conform", which is called the "TryParse" pattern in the book.
