### ISSUE TITLE
Impossible to use LINQ with System.Text.RegularExpressions.EnumerateMatches method in .NET 7.0+

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#108940]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Impossible-to-use-LINQ-with-SystemText/10763494)._

---
[severity:It bothers me. A fix would be nice]
In .NET 7.0+, `System.Text.RegularExpressions.EnumerateMatches` method returns `System.Text.RegularExpressions.Regex.ValueMatchEnumerator` type which is a ref struct. The problem with that enumerator is that LINQ does not work with ref structs, rendering the following code impossible to compile:

```c#
var tocGroup = tocRegex.EnumerateMatches(text).Select(x => x.Groups["toc"]).Where(x => x.Success).SingleOrDefault();
if (tocGroup == null)
    throw new InvalidOperationException("Cannot find TOC section.");
```

The compile error is:

```
error CS1061: 'Regex.ValueMatchEnumerator' does not contain a definition for 'Select' and no accessible extension method 'Select' accepting a first argument of type 'Regex.ValueMatchEnumerator' could be found (are you missing a using directive or an assembly reference?)
```

The same code compiles and works well in .NET 6.0.

While the ref struct enumerator provides memory usage efficiency, it does not implement `IEnumerable<T>` interface, rendering functional interoperability impossible.

---
#### Feedback Bot on 10/8/2024, 08:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by KeterSCP** [comment]
> The same code compiles and works well in .NET 6.0.

This code will never compile on .NET 6 as `Regex.EnumerateMatches` method was added only in .NET 7

**Comment by steveharter** [comment]
> The same code compiles and works well in .NET 6.0.

>> This code will never compile on .NET 6 as Regex.EnumerateMatches method was added only in .NET 7

Closing as not an issue \ needs additional feedback.
