### ISSUE TITLE
OverloadResolutionPriority does not work for extension methods accross different classes

### ISSUE THREAD

**Issue by BarionLP** [dotnet/runtime#108960]
### Description

the new `OverloadResolutionPriorityAttribute` introduced in https://github.com/dotnet/runtime/issues/102173 does not work for extension methods accross different classes.

I came across this issue while trying to fix the problem described here
https://github.com/thomhurst/TUnit/blob/main/TUnit.Assertions/Assertions/Generics/GenericIsExtensions_Namespaced.cs#L14

### Reproduction Steps

```csharp
1.IsEqualTo(0); //ambiguous call
static class A
{
    [OverloadResolutionPriority(1)]
    public static bool IsEqualTo<T>(this T left, T right) where T : INumber<T>
    {
        return left == right;
    }
}

static class B
{
    [OverloadResolutionPriority(-1)]
    public static bool IsEqualTo<T>(this T left, T right)
    {
        return EqualityComparer<T>.Default.Equals(left, right);
    }
}
```

### Expected behavior

`1.IsEqualTo(0)` should choose `A.IsEqualTo` because it has a higher priority

### Actual behavior

ambiguous call

### Configuration

.NET 9 RC 2
Windows

**Comment by hez2010** [comment]
This is by design. 
`OverloadResolutionPriority` only works in the same class.
