### ISSUE TITLE
Non-english languages bug in terminal in .Net 8

### ISSUE THREAD

**Issue by borleias** [dotnet/runtime#108918]
The closed issue "Swedish characters bug in terminal with .Net 7" (#92009, https://github.com/dotnet/runtime/issues/92009) is back with .Net 9 RC 2 (and other versions) on Windows 11.
Even on the machine where i could not reproduce it in August '24 it is now reoccurring.

**Comment by jeffhandley** [comment]
Weird! Is it repro'ing again with both .NET 8 and .NET 9 RC2? We've not changed anything on our end, so I suspect something is affecting state in the terminal. Does it repro after a fresh reboot, a bare profile launched in Terminal, and without running any other programs before the repro?
