### ISSUE TITLE
LINQ Sum extension returns 0 instead of null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#108985]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/LINQ-Sum-extension-returns-0-instead-of-/10745585)._

---
[severity:It bothers me. A fix would be nice]
LINQ Sum extension returns 0 instead of null when all members of IEnumerable are null.
Here is the way to reproduce the issue:
            
```
//some IEnumerable which should return null as result of Sum extension
            var list = new List<(decimal? amount, decimal? rate)>()
            {
                (1000m, null), 
                (2000m, null), 
                (3000m, null)
            };
            //returns 0 (not expected)
            var sum1 = list.Sum(v => v.amount * v.rate);
            Console.WriteLine($"sum1: {sum1}");
            //simple summing returns null as expected
            var sum2 = (list[0].amount * list[1].rate) + (list[1].amount * list[2].rate) + (list[2].amount * list[2].rate);
            Console.WriteLine($"sum2: {sum2}");
```

---
#### Feedback Bot on 9/13/2024, 10:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by eiriktsarpalis** [comment]
This appears to be by-design behavior that is present in all `Sum` overloads [acting on nullable inputs](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum?view=net-8.0#system-linq-enumerable-sum(system-collections-generic-ienumerable((system-nullable((system-decimal)))))):

> Items in source that are null are excluded from the computation of the sum. This method returns zero if source contains no elements or all elements are null.

Changing this today would be a breaking change.
