### ISSUE TITLE
Disable constant folding in JIT resulting in NaN, infinities etc

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#10905]
As it was discussed and agreed in dotnet/coreclr#19395 JIT should not statically evaluate expressions resulting in NaNs, infinities, or any cases left implementation-defined by IEEE754. 

category:correctness
theme:expression-opts
skill-level:beginner
cost:small

**Comment by SingleAccretion** [comment]
This has been fixed in #53782.
