### ISSUE TITLE
Android App .Net 8-Consume WCF with large data time out

### ISSUE THREAD

**Issue by ariktoledano** [dotnet/runtime#109068]
Hi I have an android app which I migrated from Xamarin.Android (API level 33) into Android APP .net 8 sdk (API level 34)
I am trying to make a client call to one of my WCF service methods - this method may return large amount of data
if the data is large for example 60 mb the call fails in timeout 

Such a call in Xamarin.Android Succeeded no problem even with larger amount of data e.g - 200 mb 

I also tried to make the same call from WPF test application .NET 8 and it succeeded.

my question is there a limitation or different setting for WCF binding that I m missing in Android App .net 8 platform.

I would appreciate any help

adding sample code for demonstration purpose - this code work in WPF app .net 8 and in Xamarin Android API 33

string _Email = "someemail@xxxxx";

BasicHttpBinding _ChannelBinding = new BasicHttpBinding();
_ChannelBinding.OpenTimeout = new TimeSpan(0, 10, 0);
_ChannelBinding.CloseTimeout = new TimeSpan(0, 10, 0);
_ChannelBinding.SendTimeout = new TimeSpan(0, 10, 0);
_ChannelBinding.ReceiveTimeout = new TimeSpan(0, 10, 0);

_ChannelBinding.MaxBufferSize = int.MaxValue;
_ChannelBinding.MaxReceivedMessageSize = int.MaxValue;
_ChannelBinding.Security.Mode = BasicHttpSecurityMode.Transport;

ChannelFactory<RestoreServiceClient.IDataRestoreServiceChannel> factory = new ChannelFactory<RestoreServiceClient.IDataRestoreServiceChannel>(_ChannelBinding, new EndpointAddress("https://www.sabaza.com/wcfservices/datarestoreservice.svc"));
RestoreServiceClient.IDataRestoreServiceChannel dataRestoreService = factory.CreateChannel();
           
RestoreServiceClient.UserInfo user = new RestoreServiceClient.UserInfo()
{
    FirstName = "SomeName",
    Email = _Email,
    UserId = _Email,  
};

var job = await dataRestoreService.DownloadJobAsyncAsync(new RestoreServiceClient.DownloadJobSubmitInfo()
{
    JobId = 890,
    User = user,
    SourceType = RestoreServiceClient.DownloadEntitySourceType.DB
});

**Comment by ariktoledano** [comment]
I tried several options:
the System.ServiceModel related packages
thoses versions
4.10.0
6.0.0
6.2.0
8.0.0

all failed on Android App  .Net 8

**Comment by grendello** [comment]
The only thing that comes to mind for me is the default HTTP client handler.  In Xamarin.Android, IIRC, it was the managed one but in .NET6+ it's the `AndroidMessageHandler` one which wraps the "native" Java HTTP client.  Perhaps try setting the [`AndroidHttpClientHandlerType`](https://github.com/dotnet/android/blob/main/Documentation/docs-mobile/building-apps/build-properties.md#androidhttpclienthandlertype) MSBuild property as described, to see whether the managed HTTP client fixes your issue.

**Comment by ariktoledano** [comment]
Thank you very much- as your suggestion I added to my Android csproj file the bold line - to prevent using native java http
now it's downloading - it's slower than before but works :)
see:
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.sabaza.sabazaapp</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	**<UseNativeHttpHandler>false</UseNativeHttpHandler>**
  </PropertyGroup>
