### ISSUE TITLE
System.Net.Http.HttpRequestException: Normally only one use of each socket address (protocol/network address/port) is allowed

### ISSUE THREAD

**Issue by zhenlei520** [dotnet/runtime#109141]
Scenario:
    Continuously send a large number of short requests. Their request time is very short, but the number is large. They are requested through IP. The IP and port are fixed. The exception message `System.Net.Http.HttpRequestException: Normally only one use of each socket address (protocol/network address/port) is allowed` will appear from time to time

CallerClient is a global static

```
public class CallerClient : IDisposable
{
    private HttpClient _httpClient = null;

    public CallerClient()
    {
        _httpClient = new HttpClient(
            new HttpClientHandler()
            {
                AutomaticDecompression = System.Net.DecompressionMethods.GZip,
                MaxConnectionsPerServer = 65535,
                UseProxy = false,
                Proxy = null,
            });
        _httpClient.DefaultRequestHeaders.AcceptEncoding.Add(new System.Net.Http.Headers.StringWithQualityHeaderValue("gzip"));
        _httpClient.Timeout = TimeSpan.FromMinutes(15);
    }

    public async Task<string> GetString(string url, HttpMethod method, object options, int timeout, Dictionary<string, IEnumerable<string>> headers)
    {
        var resp = await GetResponse(url, method, options, timeout, headers).ConfigureAwait(false);
        return await resp.Content.ReadAsStringAsync().ConfigureAwait(false);
    }

    public async Task<HttpResponseMessage> GetResponse(string url, HttpMethod method, object options, int timeout, Dictionary<string, IEnumerable<string>> headers)
    {
        var resp = await GetResponseIgnoreHttpStatusCode(url, method, options, timeout, headers).ConfigureAwait(false);
        return resp.EnsureSuccessStatusCode();
    }

    public async Task<HttpResponseMessage> GetResponseIgnoreHttpStatusCode(string url, HttpMethod method, object options, int timeout, Dictionary<string, IEnumerable<string>> headers)
    {
        var opts = new RequestOptions
        {
            ContentBody = options,
            Timeout = timeout,
            Headers = headers,
        };
        return await GetResponseCoreAsync(url, method, opts).ConfigureAwait(false);
    }

    private async Task<HttpResponseMessage> GetResponseCoreAsync(string url, HttpMethod method, RequestOptions opts)
    {
        if (opts == null) throw new ArgumentNullException($"options");
        int timeout = opts.Timeout;
        object body = opts.ContentBody;
        Dictionary<string, IEnumerable<string>> headers = opts.Headers;
        if (timeout <= 0) timeout = Convert.ToInt32(_httpClient.Timeout.TotalMilliseconds);
        using (var cts = new CancellationTokenSource(timeout))
        {
            var buffer = body == null ? null : JsonSerializer.SerializeToUtf8Bytes(body);
            var requestUri = new Uri(url);

            var request = new HttpRequestMessage()
            {
                Method = method,
                RequestUri = requestUri,
            };

            if (buffer != null)
            {
                request.Content = new ByteArrayContent(buffer);
                request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");;
            }

            if (headers != null && headers.Count > 0)
            {
                foreach (var kv in headers)
                {
                    request.Content.Headers.Add(kv.Key, kv.Value);
                }
            }

            var resp = await _httpClient.SendAsync(request, opts.CompletionOption, cts.Token).ConfigureAwait(false);

            return resp;
        }
    }

    private class RequestOptions
    {
        public object ContentBody { get; set; }
        public int Timeout { get; set; } = 0;
        public Dictionary<string, IEnumerable<string>> Headers { get; set; }
        public HttpCompletionOption CompletionOption { get; set; } = HttpCompletionOption.ResponseContentRead;
    }

    public void Dispose()
    {
        _httpClient.Dispose();
        _httpClient = null;
    }
}
```

**Comment by zhenlei520** [comment]
.net version: .net6.0
system: Windows Server 2022

**Comment by antonfirsov** [comment]
This looks like a symptom of port exhaustion.

> `MaxConnectionsPerServer = 65535`

Note that this is the total number of TCP ports, the number of available dynamic ports is typically 16384. If you want to resolve this by limiting `MaxConnectionsPerServer` you'd need a much lower number. I would recommend against this since it may hurt throughput.

A couple of ideas:

1.  .NET 6.0 will reach end of support on November 12, 2024. We strongly recommend to update. Since there were many changes in the connection pooling implementation there is some chance that the issue will go away.

2. If your server supports HTTP/2, you may try to use HTTP/2 eg. by setting `client.DefaultRequestVersion = HttpVersion.Version20`, and potentially setting `DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact` to prefer errors over HTTP/1 fallback.

3. Since you are on Windows, you can try to configure an auto-reuse port range on the machine:
https://devblogs.microsoft.com/dotnet/dotnet-6-networking-improvements/#handle-port-exhaustion-by-utilizing-auto-reuse-port-range-on-windows

**Comment by MihaZupan** [comment]
Is the server you're talking to in this case your YARP configuration described in https://github.com/microsoft/reverse-proxy/issues/2427?
Since you're setting `Connection: close` on every response, that would explain why you'll quickly run into port exhaustion that Anton described.

**Comment by zhenlei520** [comment]
> Is the server you're talking to in this case your YARP configuration described in [microsoft/reverse-proxy#2427](https://github.com/microsoft/reverse-proxy/issues/2427)? Since you're setting `Connection: close` on every response, that would explain why you'll quickly run into port exhaustion that Anton described.

Yes, it is currently impossible to track why `Connection: close` was added at that time. We need some time to test and verify this issue.

**Comment by zhenlei520** [comment]
> Is the server you're talking to in this case your YARP configuration described in [microsoft/reverse-proxy#2427](https://github.com/microsoft/reverse-proxy/issues/2427)? Since you're setting `Connection: close` on every response, that would explain why you'll quickly run into port exhaustion that Anton described.

No, this is not a same problem. It seems that the problem is caused by the reused port when the client port creates a connection. Today, I tried to change the registry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters` MaxUserPort=65534 and TcpTimedWaitDelay=5 to solve this problem. But in addition to this, I saw some netizens say that ServicePointManager.ReusePort = true to reuse the port can also avoid this problem, but I don’t know what the risks are.

**Comment by MihaZupan** [comment]
Port reuse can help if you're talking to multiple different servers, it won't do anything if you're only establishing connections to a single server.

Note that `ServicePointManager` is obsolete and that option does nothing when using `HttpClient`, but you can set the relevant flags on the sockets themselves. See https://learn.microsoft.com/dotnet/fundamentals/networking/http/httpclient-migrate-from-httpwebrequest.

If you're establishing tons of connections to a single endpoint, it is expected that you may run out of available ports and observe these exceptions.

**Comment by antonfirsov** [comment]
Not sure how does the `MaxUserPort` registry key work, but using `netsh` to configure it is superior, since you are then in control of the entire port range. See point 3 in https://github.com/dotnet/runtime/issues/109141#issuecomment-2432468850.

`SO_REUSE_UNICASTPORT` aka. `ServicePoint.ReusePort` is automatically enabled on .NET 6+, but you need to tweak some global Windows settings to enable it, see point 4 in https://github.com/dotnet/runtime/issues/109141#issuecomment-2432468850.

Please let us know if any of these recommendations helped.

**Comment by zhenlei520** [comment]
> Not sure how does the `MaxUserPort` registry key work, but using `netsh` to configure ephemeral ports is superior, since you are then in control of the entire port range. See point 3 in [#109141 (comment)](https://github.com/dotnet/runtime/issues/109141#issuecomment-2432468850).
> 
> `SO_REUSE_UNICASTPORT` (aka. the setting that is exposed as `ServicePoint.ReusePort` on .NET Framework) is automatically enabled on .NET 6+, but you need to tweak some global Windows settings to make it actually work, see point 4 in [#109141 (comment)](https://github.com/dotnet/runtime/issues/109141#issuecomment-2432468850).
> 
> Please let us know if any of the recommendations helped.

I am glad to receive your reply. The project is currently migrating from .net461 to .net8.0. After the migration is completed, we will try point 4 in https://github.com/dotnet/runtime/issues/109141#issuecomment-2432468850.
