### ISSUE TITLE
Tag 9.0.0-preview.6.24327.7 is missing the `v` prefix

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#109158]
### Description

See https://github.com/dotnet/runtime/releases/tag/9.0.0-preview.6.24327.7 or all tags https://github.com/dotnet/runtime/tags

Compare that to all other tags which have a `v` prefix.
![Image](https://github.com/user-attachments/assets/8049f20f-54a0-4117-95e7-57b803e9bbd3)

This inconsistency causes tags to sort wrong and messes up the range display when looking at commits.  For example, see https://github.com/dotnet/runtime/commit/57839c4c8a28006aacae49a1ddf8e9239fdc7edb

![Image](https://github.com/user-attachments/assets/c392fe4f-4867-470d-8859-eb667f0a680e)
Then if you expand:
![Image](https://github.com/user-attachments/assets/4ca8ff6f-849a-45b7-a41a-605059a450bb)
You'll see there are many more tags that don't match the range implied by the collapsed view.

### Reproduction Steps

Look at https://github.com/dotnet/runtime/tags

### Expected behavior

Consistent sorted order for tags that matches chronological / source order

### Actual behavior

`v` is missing from 9.0 p6 tag causing it to sort before all other tags.

**Comment by ericstj** [comment]
@rbhanda please make sure we delete the one without the `v` otherwise nothing is fixed.

**Comment by rbhanda** [comment]
> [@rbhanda](https://github.com/rbhanda) please make sure we delete the one without the `v` otherwise nothing is fixed.

deleted the tag https://github.com/dotnet/runtime/releases/tag/9.0.0-preview.6.24327.7
