### ISSUE TITLE
[NativeAOT] LibraryImport resolves to own exported functions with the same name, even if a custom module name is specified

### ISSUE THREAD

**Issue by slxdy** [dotnet/runtime#109150]
### Description

I have a NativeAOT dll project which exports the function `VerQueryValueW`. It's supposed to be a proxy for other modules loading Version.dll.
However, while trying to use `FileVersionInfo` in the same project, I ran into the issue where the internal LibraryImport for `VerQueryValueW` links back to the exported function in my project, which shouldn't be the case because the internal LibraryImport states it should be loaded from `version.dll` (note that my project name is NOT `version` during compile-time).

Here is the decompiled internal LibraryImport:
![Image](https://github.com/user-attachments/assets/ae72ddb6-c83c-4479-9c34-0c88bfc55f79)

It calls this function:
![Image](https://github.com/user-attachments/assets/dd4a7fa4-6a8b-4ac8-b62d-e4530767331f)

This function is my exported function. Compare the address from the exports list:
![Image](https://github.com/user-attachments/assets/ea48bbb2-9e54-4e9f-a312-197899db0e6e)

### Reproduction Steps

1. Create a NativeAOT DLL (use any name other than `Version`)
2. Export a function named `VerQueryValueW`
3. Get an instance of `FileVersionInfo` for any file

### Expected behavior

The internal LibraryImport for `VerQueryValueW` should resolve the function from `C:\Windows\System32\version.dll`

### Actual behavior

The compiler links the internal LibraryImport to the exported function in the project

### Known Workarounds

You can replicate the behavior of `FileVersionInfo` and load the exports from `version.dll` manually

### Configuration

- .NET 9 (latest available through VS)
- Windows 11
- All archs
- No idea if it's specific to Windows only

**Comment by jkotas** [comment]
`VerQueryValueW` is in the list of Windows OS APIs that are opted into DirectPInvoke in the default build configuration: https://github.com/dotnet/runtime/blob/9e59acb298c20658788567e0c6f0793fe97d37f6/src/coreclr/nativeaot/BuildIntegration/WindowsAPIs.txt#L2202 . 

The behavior that you are seeing is expected. It is not possible to have multiple definitions of the same public C symbol in a native project. Once you override the OS provided definition, your override will be used to satisfy all references of the C symbol.

**Comment by slxdy** [comment]
Mhm, I see. Is there maybe any workaround or config so I could avoid this behavior (without directly interacting with the original dll)?

**Comment by MichalStrehovsky** [comment]
> Mhm, I see. Is there maybe any workaround or config so I could avoid this behavior (without directly interacting with the original dll)?

Name your export something else (e.g. InternalVerQueryValueW) and then pass a DEF file to the linker that renames it:

```
EXPORTS
    VerQueryValueW=InternalVerQueryValueW
```

[You can pass](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking) a def file using the `<LinkerArg>` item in MSBuild. I don't know if link.exe accepts multiple DEF files, we already pass a DEF file to it. If it doesn't accept multiple, you might need more MSBuild hackery.

**Comment by slxdy** [comment]
Perfect! Thanks. At the end, I decided to remove the `ExportsFile` property and link the same def file using `LinkerArg`, which allows for way more freedom.
