### ISSUE TITLE
Regression: 'dotnet msbuild' publish fails with 'PublishAot' unless 'SelfContained' is also set

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#109154]
### Description

As of .NET 9, neither 'dotnet msbuild' nor Desktop MSBuild can publish with Native AOT anymore unless `SelfContained` is also set. This is especially impactful for WinUI 3 and UWP on .NET 9 apps. Eg. the default templates for WinUI 3 are also broken because of this, when on .NET 9.

### Reproduction Steps

- Create a new console project, targeting .NET 9, with Native AOT enabled
- Do the following:
```ps
dotnet msbuild /restore -t:publish .\TheConsoleApp.csproj /p:RuntimeIdentifier=win-x64
```

### Expected behavior

Should publish just fine.

### Actual behavior

![Image](https://github.com/user-attachments/assets/656b0b81-2165-4b58-83f0-d0ee3c41037c)

> "D:\.nuget\packages\microsoft.net.illink.tasks\9.0.0-rc.2.24473.5\build\Microsoft.NET.ILLink.targets(207,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app."

### Regression?

Yes. Works fine on .NET 8.

### Known Workarounds

Manually set `SelfContained` as well.

### Configuration

- .NET 9.0.100-rc.2.24474.11

**Comment by MichalStrehovsky** [comment]
This was intentional. See #95496 and the discussion on it. It never actually worked without SelfContained=true, but you may not have ran into the bug. SDK needs to know this is a SelfContained publish and PublishAot and PublishTrimmed are always SelfContained.

The fix is to put SelfContained=true in the csproj (or just run `dotnet publish` that sets it automatically).

**Comment by Sergio0694** [comment]
> "just run `dotnet publish` that sets it automatically"

Right, but my question was why can we not do the same in .targets that MSBuild can also see, so it's automatic in either case? 😅

**Comment by Sergio0694** [comment]
The problem is that `dotnet publish` just does not work at all for MSIX. You _have_ to use MSBuild. I suppose we can just leave `SelfContained=` true in the .pubxml files so that it's only going to get picked up when doing an actual publish, and that way you can still just keep `PublishAot=true` in the .csproj to get the analyzers and the CoreCLR AOT emulation mode 🤔

Thank you for confirming though!

> "We only want Publish to be SelfContained, not Build."

I'm still not entirely sure I get why can the SDK not automatically set that _only_ when you're actually publishing 😅

**Comment by Sergio0694** [comment]
Ooh gotcha, I see. Thank you for sharing the additional context! 🙂
