### ISSUE TITLE
X500DistinguishedName with ForceUTF8Encoding causes Country encoded as UTF8String on .NET 8 Linux

### ISSUE THREAD

**Issue by aaronenberg-msft** [dotnet/runtime#109156]
### Description

According to the documentation for [`X500DistinguishedNameFlags.ForceUTF8Encoding`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x500distinguishednameflags?view=net-8.0):

> Forces the distinguished name to encode specific X.500 keys as UTF-8 strings rather than printable Unicode strings. For more information and the list of X.500 keys affected, see the [X500NameFlags enumeration](https://learn.microsoft.com/en-us/windows/win32/api/certenroll/ne-certenroll-x500nameflags).

Then according to the documentation for `X500NameFlags.XCN_CERT_NAME_STR_FORCE_UTF8_DIR_STR_FLAG`:

> Forces the following X.500 keys to be encoded as UTF-8 strings rather than printable Unicode strings. The following is the list of the keys and their corresponding object identifiers (OIDs).
> 
> 
> CN - XCN_OID_COMMON_NAME
> G - XCN_OID_GIVEN_NAME
> GivenName - XCN_OID_GIVEN_NAME
> GN - XCN_OID_GIVEN_NAME
> I - XCN_OID_INITIALS
> Initials - XCN_OID_INITIALS
> L - XCN_OID_LOCALITY_NAME
> O - XCN_ORGANIZATION_NAME
> OU - XCN_OID_ORGANIZATIONAL_UNIT_NAME
> S - XCN_OID_STATE_OR_PROVINCE_NAME
> SN - XCN_ID_SUR_NAME
> ST - XCN_OID_STATE_OR_PROVINCE_NAME
> STREET - XCN_OID_STREET_ADDRESS
> T - XCN_OID_TITLE
> Title - XCN_OID_TITLE

As expected, this list does not contain 'C - XCN_OID_COUNTRY_OR_REGION_NAME` as this would violate [RFC5280](https://datatracker.ietf.org/doc/html/rfc5280#appendix-A) which states country RDN is a PrintableString.

This appears to be a regression in the smart encoding behavior on Linux.

### Reproduction Steps

```csharp
var dn = new X500DistinguishedName("C=US", X500DistinguishedNameFlags.Reversed | X500DistinguishedNameFlags.ForceUTF8Encoding);
var base64 = Convert.ToBase64String(dn.RawData);
Console.WriteLine(base64);
```

### Expected behavior

This should output the following base64 string representation regardless of OS and .NET version:

`MA0xCzAJBgNVBAYTAlVT`

### Actual behavior

On .NET 8 running on Linux, the base64 string representation is:

`MA0xCzAJBgNVBAYMAlVT`

**Comment by vcsjones** [comment]
Thanks for the report. As a work around for now, `X500DistinguishedNameBuilder` encodes this as a PrintableString. In general, this builder offers more flexibility in encoding.

```
using System.Security.Cryptography.X509Certificates;

X500DistinguishedNameBuilder builder = new();
builder.AddCountryOrRegion("US");
X500DistinguishedName dn = builder.Build();
Console.WriteLine(Convert.ToBase64String(dn.RawData));
```

**Comment by vcsjones** [comment]
Well, Windows clearly does something different than what it is documented as doing.

This will also encode as UTF-8, even though Description is not on that list from the Win32 documentation:

```C#
using System;
using System.Security.Cryptography.X509Certificates;

X500DistinguishedName dn = new("DESCRIPTION=sample", X500DistinguishedNameFlags.ForceUTF8Encoding);
Console.WriteLine(Convert.ToHexString(dn.RawData));
```

```plain
Sequence   Length: 19 Offset: 0
    SetOf   Length: 17 Offset: 2
        Sequence   Length: 15 Offset: 4
            ObjectIdentifier  2.5.4.13 (Description) Length: 5 Offset: 6
            UTF8String  sample Length: 8 Offset: 11
```

My hunch is that `ForceUTF8Encoding` forces anything that _can_ be forced to UTF-8. e.g. a `DirectoryString` or `UnboundedDirectoryString`.

CountryOrRegion is not eligible to be forced since the X.520 syntax says it's a PrintableString, so that is why it is left alone.

The tricky thing here is that for the managed encoder, we don't have a lookup of every X.520 attribute to know what their encoding rules are.
