### ISSUE TITLE
Very slow access to certain site when IPv6 is enabled

### ISSUE THREAD

**Issue by datvm** [dotnet/runtime#109195]
### Description

.NET on Windows (including .NET used by PowerShell) takes **exactly** 43s to access my company website. See details at [this StackOverflow question](https://stackoverflow.com/questions/79123318/net-http-request-on-windows-takes-a-very-long-time).

Browser and cUrl do not have this issue. Other websites do not have this issue when accessed by .NET as well.

The problem goes away as soon as I disable IPv6 in the Adapter Properties, and come back when I re-enable it. Worse, the problem does NOT happen when I use OpenVPN (however, my OpenVPN is open through IPv4 only so that may be why).

![Image](https://github.com/user-attachments/assets/ebc2e380-8899-4cfd-af47-be36150d125c)

![Image](https://github.com/user-attachments/assets/b74701a8-1af4-41ef-bc3a-f86d2a29a379)

### Reproduction Steps

Run this in PowerShell, or put similar code in .NET

```
$http = New-Object System.Net.Http.HttpClient
$http.GetStringAsync("https://company-domain.com/").GetAwaiter().GetResult()
```

### Expected behavior

It should not take 43s to complete the HTTP request.

### Actual behavior

It takes 43s to complete HTTP requests. The response is actually correct though including when it should be 200, 401 or 404.

### Known Workarounds

Disable IPv6.

### Other information

Please tell me if you need any info I can provide. I think this may be related to https://github.com/NuGet/Home/issues/12926

**Comment by huoyaoyuan** [comment]
It's likely because your ipv6 environment is not properly config. .NET prefers ipv6 when possible, getting a timeout and fallback to ipv4. If you are using some VPN that only provides ipv4, .NET will attempt to use ipv4 only.

**Comment by datvm** [comment]
@huoyaoyuan you are right. I guess this is not a .NET issue then. `curl -6` encounters the same issue. I think it's either DNS or my domain config issue (our website is proxied by Cloudflare so I am not sure what's the problem).

**Comment by wfurt** [comment]
Note that .NET would prefer IPv6 when available. That is different from browsers and once in while it leads to problems like this when IPv6 is configured but not actually functional.

**Comment by datvm** [comment]
@wfurt is there anyway I can configure this for a while as I believe the issue is with Cloudflare but I can't really get a quick support from them to resolve this issue?

**Comment by wfurt** [comment]
You can set `DOTNET_SYSTEM_NET_DISABLEIPV6` environment variable  or `System.Net.DisableIPv6` AppContext.
