### ISSUE TITLE
.NET 8.0 MAUI App: TimeZoneInfo.ConvertTimeToUtc(datetime) returns inconsitent results on different paltforms

### ISSUE THREAD

**Issue by aripp** [dotnet/runtime#109106]
### Description

**When running the .NET 8.0 MAUI App on Windows 11:**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:00:00 PM

**When running the .NET 8.0 MAUI App on the Android Emulator (Android 14):**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:06:00 PM
Note that the time is of by 6 minutes.

**When running the .NET 8.0 MAUI App on a Android Device (Android 14):**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:25:00 PM
Note that the time is of by 25 minutes.

**When running the same code within a Xamarin.Forms application on the Android Emulator or a device:**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:00:00 PM

### Reproduction Steps

1. Create a .NET MAUI App in Visual Studio 2022
2. Open MauiProgram.cs
3. Add the code below before the return statement, then run the App on the different platforms.

            int year = 2000;

            while (year > 1700)
            {
                DateTime dt = new DateTime(year, 1, 1, 0, 0, 0 );
                DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(dt);

                Debug.WriteLine(dt.ToString());

                if(dtu.Minute == 0)
                {
                    Debug.WriteLine(dtu.ToString());
                }
                else
                {
                    Debug.WriteLine(dtu.ToString() + " <=== ????");
                }
                year--;
            }

**When running the .NET 8.0 MAUI App on the Android Emulator (Android 14) the output is:**

....
[0:] 12/31/1899 11:00:00 PM
[0:] 1/1/1899 12:00:00 AM
[0:] 12/31/1898 11:00:00 PM
[0:] 1/1/1898 12:00:00 AM
[0:] 12/31/1897 11:00:00 PM
[0:] 1/1/1897 12:00:00 AM
[0:] 12/31/1896 11:00:00 PM
[0:] 1/1/1896 12:00:00 AM
[0:] 12/31/1895 11:00:00 PM
[0:] 1/1/1895 12:00:00 AM
[0:] 12/31/1894 11:00:00 PM
[0:] 1/1/1894 12:00:00 AM
[0:] 12/31/1893 11:00:00 PM
[0:] 1/1/1893 12:00:00 AM
[0:] 12/31/1892 11:06:00 PM <=== ????
[0:] 1/1/1892 12:00:00 AM
[0:] 12/31/1891 11:06:00 PM <=== ????
[0:] 1/1/1891 12:00:00 AM
[0:] 12/31/1890 11:06:00 PM <=== ????
[0:] 1/1/1890 12:00:00 AM
[0:] 12/31/1889 11:06:00 PM <=== ????
[0:] 1/1/1889 12:00:00 AM
[0:] 12/31/1888 11:06:00 PM <=== ????
[0:] 1/1/1888 12:00:00 AM
[0:] 12/31/1887 11:06:00 PM <=== ????
[0:] 1/1/1887 12:00:00 AM
[0:] 12/31/1886 11:06:00 PM <=== ????
....

### Expected behavior

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Expected output on all platforms is:
12/31/1753 11:00:00 PM

### Actual behavior

**When running the .NET 8.0 MAUI App on Windows 11:**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:00:00 PM

**When running the .NET 8.0 MAUI App on the Android Emulator (Android 14):**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:06:00 PM
Note that the time is of by 6 minutes.

**When running the .NET 8.0 MAUI App on a Android Device (Android 14):**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:25:00 PM
Note that the time is of by 25 minutes.

**When running the same code within a Xamarin.Forms application on the Android Emulator or a device:**

DateTime dtu = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1753, 1, 1, 0, 0, 0));
Debug.WriteLine(dtu.ToString());

Output is:
12/31/1753 11:00:00 PM

### Configuration

.NET 8.0, Android 14

**Comment by aripp** [comment]
TimeZoneInfo.Local: (UTC+01:00) Central European Time (Berlin)

I'm located in Switzerland.
Switzerland uses Central European Time (CET) during the winter as standard time, which is one hour ahead of Coordinated Universal Time (UTC+01:00), and Central European Summer Time (CEST) during the summer as daylight saving time, which is two hours ahead of Coordinated Universal Time (UTC+02:00).

**Comment by Clockwork-Muse** [comment]
This isn't an issue with the runtime - we usually source the information from the OS, which is what you're seeing here.

> What is TimeZoneInfo.Local in these tests?
> 
> Perhaps the time zone actually changed its rules between 1893 and 1894, and the change was later recorded in the IANA time zone database but never in the Windows time database. Knowing which time zone you are using would make this easier to check.

This is actually super common.  Windows doesn't have most of the really-old historical zone changes for any timezones.

And pretty much every zone in the IANA database has an initial "true up" shift when it first moves from local solar time to a UTC offset.  These go from ~1860ish or something to past 1945.  

> I'm located in Switzerland.
Switzerland uses Central European Time (CET) during the winter as standard time, which is one hour ahead of Coordinated Universal Time (UTC+01:00), and Central European Summer Time (CEST) during the summer as daylight saving time, which is two hours ahead of Coordinated Universal Time (UTC+02:00).

Those offsets might be true _now_, but that may not hold for historical data.  For instance, there are a number of zones where DST was suspended for one reason or another, or a country decided they wanted to be at a different offset, or whatever.

DO NOT attempt to second-guess or massage the zone info to match what you think you know - you will be wrong.

If you absolutely need accurate/consistent historical zones on all platforms, look at NodaTime (you will need to bundle their data source with your application).
Note that even with that, you can still get info/config drift as different people update their apps at different times - distributed data for something like this is essentially a nightmare.
