### ISSUE TITLE
[Question] Path.GetFullPath doesn't take ~ on unix in account

### ISSUE THREAD

**Issue by YaMoef** [dotnet/runtime#109250]
### Issue summary
I noticed that `Path.GetFullPath("~/test")` gives me `{PROJECT_PATH}~/test`.  For example: `/usr/lib/NetPad vNext/resources/netpad-server/~/test`. I would expect it that it would return in my case: `/home/brent/test` Is this designed behavior? I haven't found anything in the docs either or a relevant issue.
To me, it seems that this behavior is incorrect. Running `cd ~/test` from cmd points me to `/home/brent/test`. The `$HOME` env variable is available since creating a dirty workaround like this is possible:
```
string GetFullPath(string path) {
    if(path.StartsWith("~")){
        path = path.Substring(1);
        if (path.StartsWith("/"))
            path = path.Substring(1);

        path = Path.Combine(Environment.GetEnvironmentVariable("HOME"), path);
    }

    return Path.GetFullPath(path);
}
```

### Steps to reproduce
Get LinqPad or NetPad on any linux (and possibly MacOS), and execute:
```
("Path.GetFullPath: " + Path.GetFullPath("~/")).Dump();
("Workaround: " + GetFullPath("~/")).Dump();

string GetFullPath(string path) {
    if(path.StartsWith("~")){
        path = path.Substring(1);
        if (path.StartsWith("/"))
            path = path.Substring(1);

        path = Path.Combine(Environment.GetEnvironmentVariable("HOME"), path);
    }

    return Path.GetFullPath(path);
}
```

### My env
- NetPad vNext v0.8.0
- Dotnet SDK 8.0.204
- Ubuntu 22.04.5 LTS

**Comment by huoyaoyuan** [comment]
`~` is a feature resolved by shell, not the OS. You can make a directory named `~` with native OS commands with `mkdir '~'`.

**Comment by DL444** [comment]
Also note that shells also resolve `~username` to the home directory of user "username". I believe `System.IO` isn't the right place for this behavior as well.

**Comment by am11** [comment]
Agreed, shell rules can be nuanced. Here’s an example in ZSH:

```zsh
mkdir ~existinguser         # Not allowed, as ~existinguser expands to an existing user's home directory
mkdir '~existinguser'       # Allowed; creates a directory literally named '~existinguser' in the current directory
ls ~existinguser            # Expands to existing user's home directory
ls '~existinguser'          # Locates a literal file or directory named `~existinguser` in the current directory (same as ./~existinguser)
```

There are many details like this, and to make things more complex, different shells (e.g., POSIX `sh`, `zsh`, `bash`, `dash`, `tcsh`, `ash`) each handle certain expansions and syntax differently. Rather than manually trying to handle these variations in code, it's often best to let the target shell process the expansion.

Here’s a C# example of how you can use the target shell directly for expansion:

```csharp
using System;
using System.Diagnostics;

// Test how Almquist Shell (ash) on Alpine Linux handles tilde expansion
Console.WriteLine(ExpandPathInShell("/bin/ash", "~existinguser/testdir"));

string ExpandPathInShell(string shell, string path)
{
    var process = Process.Start(new ProcessStartInfo
    {
        FileName = shell,
        Arguments = $"""-c "echo {path}""",
        RedirectStandardOutput = true,
        UseShellExecute = false
    });

    return process.StandardOutput.ReadToEnd().Trim();
}
```

**Comment by YaMoef** [comment]
Makes sense. Will close this, since my question is resolved now
