### ISSUE TITLE
WASM publish on Ubuntu 24.04 mishandles staticwebassets

### ISSUE THREAD

**Issue by eylvisaker** [dotnet/runtime#109266]
### Description

I'm trying to setup the build for a wasm application that uses some external packages. But I'm finding a difference between how dotnet publish organizes the output files between Windows and Ubuntu. I'm probably I'm missing something here, but I'm not sure what.

Specifically, dotnet publish on Windows puts the static web assets from my imported nuget packages into the publish/wwwroot/_framework directory, but dotnet publish on Linux puts them into the publish/wwwroot. Unfortunately, since the webapp itself expects to retrieve those files from the _framework directory, this results in the Linux app being just completely broken.

### Reproduction Steps

Minimal reproduction steps:

Start from an empty directory.
```
dotnet new install avalonia.templates
dotnet new avalonia.xplat
dotnet publish *.Browser
dir *.Browser/bin/Release/net8.0-browser/publish/wwwroot/_framework/avalonia.js
```

### Expected behavior

The avalonia.js (and other static web assets) of my nuget packages should be dropped into the publish/wwwroot/_framework folder, where the web app expects them.

### Actual behavior

Static web assets of imported nuget packages get dropped into the output folder publish/wwwroot. 

### Configuration

I've tested this on a small variety of installations:

* Windows 11 with dotnet 8.0.200 : Works perfectly
* Ubuntu 24.04 with dotnet 8.0.10 from `apt install dotnet8` : Broken
* Ubuntu 24.04 with dotnet 8.0.403 from `snap install dotnet-sdk-8.0` : Broken
* Ubuntu 22.04 with dotnet 8.0.110 from `apt isntall dotnet8` : Broken
* (WSL) Ubuntu 22.04 with dotnet 8.0.403 from ??? : Works (not sure how to repro this setup)
* (WSL) Debian 12 with dotnet 8.0.403 from `dotnet-install.sh`: Broken

**Comment by maraf** [comment]
The problem is not specific to OS, but whether the `wasm-tools` workload is installed or not. Avalonia relies on `WasmRuntimeAssetsLocation` in https://github.com/AvaloniaUI/Avalonia/blob/a06ae34732d5c897b9a627cbe13836e0bafb1943/src/Browser/Avalonia.Browser/build/Microsoft.AspNetCore.StaticWebAssets.props#L13, but `WasmRuntimeAssetsLocation` is set only when workload is installed.

**Comment by maraf** [comment]
I'm going to this issue in favor of https://github.com/AvaloniaUI/Avalonia/issues/17388 and https://github.com/dotnet/runtime/issues/90979
