### ISSUE TITLE
[NativeAOT] Failing to resolve symbols of static libraries on win-x86

### ISSUE THREAD

**Issue by slxdy** [dotnet/runtime#109268]
### Description

Whenever I try to LibraryImport a function from a static library when compiling for win-x86, it fails to resolve the symbols. Works fine when compiled for win-x64.

### Reproduction Steps

- Compile a static library with VC++ for win-x86 and export a function
Example:
```cpp
#include <iostream>

extern "C" __declspec(dllexport) int HelloWorldTestFunc()
{
	std::cout << "Hello world from C++!" << std::endl;
	return 123;
}
```

- Create a new .NET 9 AOT project and include the following in the csproj:
```xml
<ItemGroup>
    <NativeLibrary Include="Path/To/Your/StaticLib.lib" />
</ItemGroup>
```

- Make a LibraryImport for the function
```cs
[LibraryImport("*", EntryPoint = "HelloWorldTestFunc")]
public static partial int HelloWorldTest();
```

- Call the function anywhere
- Publish for win-x86

### Expected behavior

The function `HelloWorldTestFunc` should be resolved from the static library

### Actual behavior

It fails and throws the following error: `unresolved external symbol _HelloWorldTestFunc@0`.

Works fine when the static lib is compiled for win-x64 and the AOT project is published for win-x64.

### Configuration

- .NET 9 (latest for VS Preview)
- Windows 11
- x86
- Specific to x86

**Comment by slxdy** [comment]
If there is a quick workaround without having to compile a dynamic library, please let me know

**Comment by huoyaoyuan** [comment]
You are missing calling convention. On x86 the default calling convention of C is `cdecl`, while the default for .NET is `stdcall`. The compiled symbol name for different calling conventions are different.

On x64 the difference of calling conventions are eliminated.

**Comment by slxdy** [comment]
Oh wow, didn't think of that. Thanks for the quick response! (and sorry for bothering the devs)
