### ISSUE TITLE
OrderedDictionary perf with bad hashing

### ISSUE THREAD

**Issue by PranavSenthilnathan** [dotnet/runtime#109293]
### Description

There's an edge case with bad hashing that can cause complexity of generic `OrderedDictionary` to be worse than expected. Note, this is a contrived example and won't happen by chance, but there shouldn't be any negative impact to fix it. Creating this issue as suggested by @eiriktsarpalis here: https://github.com/dotnet/runtime/pull/109273#issuecomment-2441070776. See that PR for more details about the cause/fix.

```csharp
public void Run1()
{
    var timer = Stopwatch.StartNew();
    var dict = new OrderedDictionary<int, int>(new BadComparer2());
    for (int i = 1; i <= 2000; i++)
    {
        if (i % 500 == 0)
        {
            logger.WriteLine($"i = {i}, time = {timer.Elapsed}");
        }
        dict.Insert(0, i, 42);
    }
}

public void Run2()
{
    int N = 100_000;
    var dict = new OrderedDictionary<int, int>(2 * N, new BadComparer2());
    for (int i = 1; i <= N; i++)
    {
        if (i == 100 || i == 1_000 || i == 10_000 || i == 100_000)
        {
            var timer = Stopwatch.StartNew();
            dict.Insert(0, i, 42);
            logger.WriteLine($"i = {i}, time = {timer.Elapsed}");
        }
        else
        {
            dict.Add(i, 42);
        }
    }
}

private class BadComparer2 : IEqualityComparer<int>
{
    public bool Equals(int x, int y) => x == y;
    public int GetHashCode(int obj) => 0;
}
```

The total time in Run1 should be O(n^2) but it's O(n^3). The single insert time in Run2 should be O(n) but it's O(n^2).

Run1:

i = 500, time = 00:00:00.1417676
i = 1000, time = 00:00:01.0615544
i = 1500, time = 00:00:03.5316435
i = 2000, time = 00:00:08.2965112

(Note for example, doubling i from 1000 to 2000 makes the perf get 2^3 = 8 times as bad.)

Run2:

i = 100, time = 00:00:00.0003756
i = 1000, time = 00:00:00.0034780
i = 10000, time = 00:00:00.3094147
i = 100000, time = 00:00:30.6661944

With the suggested fix in #109273, the times are:

Run1:

i = 500, time = 00:00:00.0087732
i = 1000, time = 00:00:00.0287575
i = 1500, time = 00:00:00.0588899
i = 2000, time = 00:00:00.1012805

Run2:

i = 100, time = 00:00:00.0003152
i = 1000, time = 00:00:00.0000518
i = 10000, time = 00:00:00.0004255
i = 100000, time = 00:00:00.0039128

### Configuration

.NET 9 rc 2, Windows, x64

### Regression?

No

**Comment by eiriktsarpalis** [comment]
What's the implementation of `BadComparer`? I would recommend using `BenchmarkDotNet` when sharing performance data since it captures performance differences in a standardized way.

**Comment by PranavSenthilnathan** [comment]
```cs
    private class BadComparer2 : IEqualityComparer<int>
    {
        public bool Equals(int x, int y) => x == y;
        public int GetHashCode(int obj) => 0;
    }
```

**Comment by eiriktsarpalis** [comment]
Closing as by-design behaviour.
