### ISSUE TITLE
Update RyuJIT overview and LSRA doc

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#10937]
A number of changes have been made to the register allocator, in particular dotnet/coreclr#16517, and the documentation needs to be updated accordingly.

category:documentation
theme:ir
skill-level:expert
cost:medium

**Comment by kunalspathak** [comment]
There were some updates recently by Carol that documented these things:
https://github.com/dotnet/runtime/pull/39492
https://github.com/dotnet/runtime/pull/45235
https://github.com/dotnet/runtime/pull/45609

**Comment by CarolEidt** [comment]
Thanks for closing this @kunalspathak !
