### ISSUE TITLE
Why there's no constructor defined for DateOnly and TimeOnly to take DateTime object as an input

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/runtime#109353]
### Is your feature request related to a problem? Please describe.
Trying a create an instance of a `DateOnly` or `TimeOnly` object from a `DateTime` instance.

### Describe the solution you'd like
If an overload exists for the `DateTime` object to be instantiated from the `DateOnly` and `TimeOnly` instances, why not vice versa?

### Additional context
Simplified APIs.

**Comment by tarekgh** [comment]
Here's a revised version for clarity:

I'm curious about why you think `FromDateTime` might not be a good choice. Including `DateTime` in the constructor could encourage its use, even though we want to minimize potential confusion around `DateTime.Kind`. Initially, the proposal included an implicit operator to convert `DateTime` to `DateOnly`/`TimeOnly`, but during the review, it was recommended to avoid the implicit operator and instead use factory methods like `FromDateTime`. Feel free to watch the review video for more details.
