### ISSUE TITLE
ThreadLocal<T> memory leak

### ISSUE THREAD

**Issue by aloraman** [dotnet/runtime#109387]
### Description

Inspired by https://x.com/shipilev/status/1851676605275607068 from @shipilev

ThreadLocal<T> objects survive garbage collection in release mode, even though they are not GC roots.

### Reproduction Steps

```csharp
using System.Threading;
while (true)
{
    var tls = new ThreadLocal<object>(); // create thread-local
    tls.Value = tls; // strongly reached by itself
}
```

### Expected behavior

ThreadLocal object successfully collected after becoming unreachable.

### Actual behavior

Used memory continuously grows under Release configuration until it reaches Out-of-Memory state.
If you comment out the line with "strongly reached by itself", it still goes into OOM, but much slower.

### Regression?

Not really.
Observed on multiple runtimes.

### Configuration

Observed on x86 and x64; targeting net8.0, net6.0, netcoreapp3.1 and net472, as well as on sharplab.io

### Other information

I've found out the snippet by @shipilev - so I've got an idea to check .Net behavior in similar conditions. The repro is nonsensical, still I haven't found anything in documentation about ThreadLocal<T> being expected to survive until the thread dies.

**Comment by stephentoub** [comment]
Thanks. This is a duplicate of https://github.com/dotnet/runtime/issues/23103.

**Comment by aloraman** [comment]
@stephentoub thanks for a quick reply!

I've read through #23103 - and it seems it's only about circular reference to ThreadLocal<T>
Here, however, this circular reference can be removed, i.e.

```csharp
using System.Threading;
while (true)
{
    var tls = new ThreadLocal<object>(); // create thread-local
}
```
And still, without circular reference, the memory usage keep growing until OOM.
While
```csharp
while(true)
{
    var obj = new object();
    GC.KeepAlive(obj);
}
```
immediately reaches a steady state.

P.S. Maybe it's just an oversaturation of a finalizer queue?

**Comment by aloraman** [comment]
Yep, it's an oversaturation of finalizer queue.
Either
```csharp
while(true)
{
    var tls = new ThreadLocal<object>();
    tls.Dispose();
}
```
or
```csharp
while(true)
{
   var tls = new ThreadLocal<object>();
   GC.WaitForPendingFinalizers();
}
```
reach a steady state as well.

Thanks!
