### ISSUE TITLE
(De)Serialization of list of objects containing polymorphic generics in C# .Net8 with System.Text.Json

### ISSUE THREAD

**Issue by oragain** [dotnet/runtime#109307]
When trying to serialize a list where objects are derived types of generic and generic base, I end up with the error: System.InvalidOperationException: 'Specified type 'CSharpLanguageTestingApp.CustomResult1[T]' is not a supported derived type for the polymorphic type 'CSharpLanguageTestingApp.CustomResult1[CSharpLanguageTestingApp.AggregateTwo]'. Derived types must be assignable to the base type, must not be generic and cannot be abstract classes or interfaces unless 'JsonUnknownDerivedTypeHandling.FallBackToNearestAncestor' is specified.'

FallBackToNearestAncestor does nothing for me at this time

Example class:
```csharp
using System.Text.Json.Serialization;

namespace CSharpLanguageTestingApp
{
    public class AggregateOne
    {
        int iAmAggregateOne { get; set; } = 1;
    }

    public class AggregateTwo
    {
        public int iAmAggregateTwo { get; set; } = 2;
    }

    [JsonPolymorphic(UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToNearestAncestor)]
    [JsonDerivedType(typeof(CustomResult<>), "CustomResult")]
    [JsonDerivedType(typeof(dbCustomResult<>), "dbCustomResult")]
    [JsonDerivedType(typeof(sbCustomResult<>), "sbCustomResult")]
    [JsonDerivedType(typeof(apiCustomResult<>), "apiCustomResult")]
    public class  CustomResult<T>
    {
        public int iAmAResult { get; set; } = 0;
    }

    public class  dbCustomResult<T> : CustomResult<T>
    {
        public int iAmADbResult { get; set; } = 0;
    }

    public class sbCustomResult<T> : CustomResult<T>
    {
        public int iAmASbResult { get; set; } = 0;
    }

    public class apiCustomResult<T> : CustomResult<T>
    {
        public int iAmAnApiResult { get; set; } = 0;
    }

    public class CompositeResult
    {
        public string Name { get; set; } = "CompositeResult";

        [JsonConverter(typeof(PolymorphicListConverter))]
        public List<object> IndividualResults { get; set; } = new();
    }


}
```

Converter:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Threading.Tasks;

namespace CSharpLanguageTestingApp
{

    public class PolymorphicListConverter : JsonConverter<List<object>>
    {
        public override List<object> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var results = new List<object>();

            // Ensure we're at the start of the array
            if (reader.TokenType == JsonTokenType.StartArray)
            {
                while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
                {
                    if (reader.TokenType == JsonTokenType.StartObject)
                    {
                        using (JsonDocument doc = JsonDocument.ParseValue(ref reader))
                        {
                            JsonElement root = doc.RootElement;

                            if (root.TryGetProperty("$type", out JsonElement typeElement))
                            {
                                string typeName = typeElement.GetString();
                                Type type = Type.GetType(typeName);
                                if (type != null)
                                {
                                    var json = root.GetProperty("Data").GetRawText();
                                    var obj = JsonSerializer.Deserialize(json, type, options);
                                    results.Add(obj);
                                }
                            }
                        }
                    }
                }
            }

            return results;
        }

        public override void Write(Utf8JsonWriter writer, List<object> value, JsonSerializerOptions options)
        {
            writer.WriteStartArray();

            foreach (var result in value)
            {
                if (result != null)
                {
                    try
                    {
                        // Get the runtime type of the object
                        var resultType = result.GetType();

                        writer.WriteStartObject();
                        writer.WriteString("$type", resultType.AssemblyQualifiedName);
                        writer.WritePropertyName("Data");

                        // Serialize the object as is
                        string json = "";
                        try
                        {
                            json = JsonSerializer.Serialize(result, options); // try 1
                        }catch (Exception ex)
                        {
                            Console.WriteLine($"Error serializing object of type {result.GetType()}: {ex.Message}");
                        }
                        try
                        {
                            JsonSerializer.Serialize(writer, result, resultType, options); // try 2
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Error serializing object of type {result.GetType()}: {ex.Message}");

                        }

                        writer.WriteEndObject();

                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error serializing object of type {result.GetType()}: {ex.Message}");
                        throw; // Rethrow or handle the exception as needed
                    }
                }
            }

            writer.WriteEndArray();
        }

    }


}
```

Program to test with:
```csharp
CompositeResult compositeResult = new CompositeResult();
compositeResult.IndividualResults.Add(new dbCustomResult<AggregateOne>());
compositeResult.IndividualResults.Add(new CustomResult<AggregateTwo>());
compositeResult.IndividualResults.Add(new sbCustomResult<AggregateTwo>());
compositeResult.IndividualResults.Add(new apiCustomResult<AggregateOne>());

var options = new JsonSerializerOptions();
options.Converters.Add(new PolymorphicListConverter());
string json = "";
try
{
    json = System.Text.Json.JsonSerializer.Serialize(compositeResult, options);
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
}
Console.WriteLine(json);
```

Removing: `compositeResult.IndividualResults.Add(new CustomResult<AggregateTwo>());`

Actually works:
```json
{"Name":"CompositeResult","IndividualResults":[{"$type":"CSharpLanguageTestingApp.dbCustomResult\u00601[[CSharpLanguageTestingApp.AggregateOne, CSharpLanguageTestingApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], CSharpLanguageTestingApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Data":{"iAmADbResult":0,"iAmAResult":0}},
{"$type":"CSharpLanguageTestingApp.sbCustomResult\u00601[[CSharpLanguageTestingApp.AggregateTwo, CSharpLanguageTestingApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], CSharpLanguageTestingApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Data":{"iAmASbResult":0,"iAmAResult":0}},
{"$type":"CSharpLanguageTestingApp.apiCustomResult\u00601[[CSharpLanguageTestingApp.AggregateOne, CSharpLanguageTestingApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], CSharpLanguageTestingApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Data":{"iAmAnApiResult":0,"iAmAResult":0}}]}
```

So, how can I get my base class to work in the same fashion as my derived types?

**Comment by eiriktsarpalis** [comment]
Per the error message, JsonDerivedType annotations are not supported for generic types. This is due to ambiguity that can arise when dealing with hierarchies of generic types.

**Comment by oragain** [comment]
Hi,
Not sure i understand. If i remove the jsonderivedtype attribut targeting
customresult, i still error out with a slightly different error where the
serializer tries to match customresult to one of its children.
I do kot understand why, if the derived types can serialize properly, why
cant the parent resolve?
Base and derived types are both generics.
Regards

**Comment by eiriktsarpalis** [comment]
> Hi, Not sure i understand.

Adding `JsonDerivedTypeAttribute` to generic types is not a supported scenario because of ambiguities like the following:

```csharp
[JsonDerivedType(typeof(Derived<>), "generic")]
[JsonDerivedType(typeof(Derived<int>), "int")]
[JsonDerivedType(typeof(Derived<string>), "string")]
class Base<T>;

class Derived<T> : Base<T>;
```

In your specific use case we could try to make the serializer a bit smarter and fill the generic parameter of the attribute with the generic parameter of the base type, however these do not always coincide 1-1 for example:

```csharp
[JsonDerivedType(typeof(Derived<>), "generic")]
class Base<T>;

class Derived<T> : Base<Dictionary<string, T>>;
```

or 

```csharp
[JsonDerivedType(typeof(Derived<>), "generic")]
class Base;

class Derived<T> : Base;
```

For this reason, `JsonDerivedType` only supports monomorphized derived types like so:

```csharp
[JsonDerivedType(typeof(Derived<int>), "int")]
[JsonDerivedType(typeof(Derived<string>), "string")]
class Base<T>;
```

**Comment by oragain** [comment]
Hmm, this is where I am getting lost. If I have:
`    public class CustomResultNoDerivative<T>
    {
        public int iAmAResult { get; set; } = 0;

        public T Agg { get; set; }
    }
`
I can serialize no problem:
`CustomResultNoDerivative<AggregateTwo> res = new CustomResultNoDerivative<AggregateTwo>();
res.Agg = new AggregateTwo();
json = System.Text.Json.JsonSerializer.Serialize(res, options);
`

But as soon as I add derived types to my CustomResultNoDerivative<T> (cf CustomResult<T>), then only the derived types are serializable but not the base class anymore. And that is what is throwing me off. Why the dichotomy.

But if that is the way it is. I guess a workaround would be to never make use of my base class

**Comment by eiriktsarpalis** [comment]
> But as soon as I add derived types to my CustomResultNoDerivative (cf CustomResult), then only the derived types are serializable but not the base class anymore. And that is what is throwing me off. Why the dichotomy.

The base class is not serializable if you add `JsonDerivedType` attributes with unsupported arguments. Polymorphic configuration on the base type has no impact on the configuration of the derived type which will therefore still work if you try to serialize using that type.

**Comment by oragain** [comment]
And now the kicker for me, if I create a base of my base class and apply the jsonderivedtypes to that base of a base, i can serialize any level of derived types under it:
`using System.Text.Json.Serialization;

namespace CSharpLanguageTestingApp
{
    public class AggregateOne
    {
        int iAmAggregateOne { get; set; } = 1;
    }

    public class AggregateTwo
    {
        public int iAmAggregateTwo { get; set; } = 2;
    }

    [JsonPolymorphic(UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToNearestAncestor)]
    [JsonDerivedType(typeof(CustomResult<>), "customResult")]
    [JsonDerivedType(typeof(dbCustomResult<>), "dbCustomResult")]
    [JsonDerivedType(typeof(sbCustomResult<>), "sbCustomResult")]
    [JsonDerivedType(typeof(apiCustomResult<>), "apiCustomResult")]
    public class Base<T>
    {
        public int iAmBase { get; set; } = 0;

        public T Agg { get; set; }
    }


    public class CustomResult<T> : Base<T>
    {
        public int iAmAResult { get; set; } = 0;
    }

    public class dbCustomResult<T> : CustomResult<T>
    {
        public int iAmADbResult { get; set; } = 0;
    }

    public class sbCustomResult<T> : CustomResult<T>
    {
        public int iAmASbResult { get; set; } = 0;
    }

    public class apiCustomResult<T> : CustomResult<T>
    {
        public int iAmAnApiResult { get; set; } = 0;
    }

    public class CompositeResult
    {
        public string Name { get; set; } = "CompositeResult";

        [JsonConverter(typeof(PolymorphicListConverter))]
        public List<object> IndividualResults { get; set; } = new();
    }


}
`

So, by doing what I consider to be somewhat of an unnecessary workaround, I can serialize properly.
