### ISSUE TITLE
Microsoft.Management.Infrastructure.CimSession.Create  Error

### ISSUE THREAD

**Issue by dongzhaosheng73** [dotnet/runtime#109368]
### Description

An exception occurred using CimSession.Create(null))  

windows system name：Windows 10 Home China

ver：10.0.19045.3208

Microsoft.Management.Infrastructure ver 2.0.0

Microsoft.Management.Infrastructure.Runtime.Win ver 2.0.0

.net runtime ver 6.0
### Reproduction Steps

An exception occurred using CimSession.Create(null))  

Microsoft.Management.Infrastructure.CimException: CimSessionOptions instance is invalid: unsupported protocol or unrecognized custom option.  Verify parameter passed to the CimSessionOptions(string) constructor and/or parameters passed to the CimSessionOptions.SetCustomOption(string, string) or CimSessionOptions.SetCustomOption(string, int) method.
   at Microsoft.Management.Infrastructure.CimSession.Create(String computerName, CimSessionOptions sessionOptions)
   at Microsoft.Management.Infrastructure.CimSession.Create(String computerName)

### Expected behavior

using CimSession.Create(null))   not  error

### Actual behavior

using CimSession.Create(null))    error

**Comment by huoyaoyuan** [comment]
MMI belongs to PowerShell, not .NET. The repository is at https://github.com/PowerShell/MMI . You can navigate from package page in NuGet gallery.

However, the repo is now archived and PowerShell team was not active about it. At least you can try the latest 3.0.0 version.

**Comment by dongzhaosheng73** [comment]
> MMI belongs to PowerShell, not .NET. The repository is at https://github.com/PowerShell/MMI . You can navigate from package page in NuGet gallery.
> 
> However, the repo is now archived and PowerShell team was not active about it. At least you can try the latest 3.0.0 version.

I also posted the same question on powershell, as you said it is not very active there, so I have no choice but to post a post here to ask everyone for help. So far I do not know which MMI or WMI is the real API of Microsoft, from the results of my current search MMI seems to be a new cross-platform API to be maintained, but at present MMI documentation is poor, no one even discusses it.

**Comment by jeffschwMSFT** [comment]
sorry to hear that the home repo is not providing a timely reply, but we need to move this issue to the place where it can get assistance.  I am going to close this issue and I recommend cross linking with the issue within powershell
