### ISSUE TITLE
Avoid hardcoded TFM in illink

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#109335]
https://github.com/dotnet/runtime/blob/e476b43b5cb42eb44ce23b1c7b793aa361624cf6/src/tools/illink/src/ILLink.Tasks/LinkTask.cs#L272

There are ways to avoid this hardcode, i.e. by passing in an additional parameter to the msbuild task or by inferring it somehow else. I would assume that the linker.dll and the ILLink.Tasks.dll TFM should be in sync and could be read from the assembly metadata.

@sbomer @agocke

**Comment by am11** [comment]
>  I would assume that the linker.dll and the ILLink.Tasks.dll TFM should be in sync and could be read from the assembly metadata.

Perhaps with this approach: https://github.com/dotnet/runtime/blob/e476b43b5cb42eb44ce23b1c7b793aa361624cf6/src/coreclr/tools/r2rtest/Commands/CompileNugetCommand.cs#L61-L62

**Comment by ViktorHofer** [comment]
That looks good. @am11 do you want to submit a PR?

**Comment by am11** [comment]
During this transition period, VMR is looking for net10.0, while the hardcoded version is net9.0. Do you mean if we use `Environment.Version` then VMR will succeed but the regular runtime build will fail (until the transition is completed)? In which case, your approach it is; get current assembly (of `ILLink` class) and read the version from metadata.

**Comment by ViktorHofer** [comment]
> Do you mean if we use Environment.Version then VMR will succeed but the regular runtime build will fail (until the transition is completed)?

Correct. If we would switch to Environment.Version now, the runtime PR with that change would fail. I would prefer to avoid coupling the version of SPC with the linker.dll TFM.

**Comment by am11** [comment]
I tried three variants: `Environment.Version`, `typeof(ILLink)..InformationalVersion` and `executingAssembly..InformationalVersion`, none of them worked because in current state of runtime, all live assemblies have 10.0 version, yet illink.dll lands in net9.0:

```sh
% find artifacts/bin -name illink.dll
artifacts/bin/ILLink.Tasks/Debug/net9.0/illink.dll
artifacts/bin/Mono.Linker/ref/Debug/net9.0/illink.dll
artifacts/bin/Mono.Linker/Debug/net9.0/illink.dll
```

**Comment by am11** [comment]
If it is guaranteed to either have the same version or N-1, one simple approach is to probe paths (in more likely to less likely order) https://github.com/dotnet/runtime/compare/main...am11:runtime:patch-17.

**Comment by ViktorHofer** [comment]
If we want to / can rely on reflection then we could probably directly read from the `TargetFrameworkAttribute` assembly attribute.

**Comment by am11** [comment]
@ViktorHofer, side question: i'm a bit confused by this comment in LinkTask.cs:

`// IL Linker always runs on .NET Core, even when using desktop MSBuild to host ILLink.Tasks.`

if this is true, why do we build it against netfx TFM?

**Comment by am11** [comment]
`typeof(ILLink).Assembly.GetCustomAttribute<TargetFrameworkAttribute>`

I think this will fail in netfx case.

**Comment by ViktorHofer** [comment]
Oh I wasn't aware that the .NET Framework task invokes the .NETCoreApp illink.dll. Interesting.

**Comment by ViktorHofer** [comment]
I think what we really want here is to include source, either via a source generator or an msbuild task that creates a C# file (to avoid overhead of a separate project). Or is there another way to include information at build time?

**Comment by am11** [comment]
We can inject the exact version in csproj:

```csproj
<!-- in ILLink.Tasks.csproj add version info of illink.dll -->
<ItemGroup>
  <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
    <_Parameter1>ILLinkImplAssemblyVersion</_Parameter1>
    <_Parameter2>$(NetCoreAppCurrentVersion)</_Parameter2>
  </AssemblyAttribute>
</ItemGroup>
```
and read it with:
```c#
Version version = Version.Parse(assembly.GetCustomAttributes<AssemblyMetadataAttribute>()
    .Single(attr => attr.Key == "ILLinkImplAssemblyVersion").Value);
```

**Comment by ViktorHofer** [comment]
@sbomer is it fine to use reflection in that code path? Just double checking.

**Comment by am11** [comment]
That method has existing reflection usage via Assembly.GetExecutingAssembly(), so I guess it's fine (well, each reflection call adds additional overhead so it cannot be perfectly fine 😅).

Alternatively, we can generate an old school code fragment, if we want to avoid the full sourcegen project setup.

```csproj
  <Target Name="GenerateBuildMetadata" BeforeTargets="BeforeBuild">
    <WriteLinesToFile
      File="$(IntermediateOutputPath)Generated_BuildMetadata.cs"
      Lines="// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
internal static class BuildMetadata
{
    public static readonly Version NetCoreAppCurrentVersion = new Version(&quot;$(NetCoreAppCurrentVersion)&quot;);
}
"
      Overwrite="true" />

    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)Generated_BuildMetadata.cs" />
    </ItemGroup>
  </Target>
```
and use `BuildMetadata.NetCoreAppCurrentVersion.Major`.

**Comment by ViktorHofer** [comment]
Agreed, we should avoid that hardcode in the props file as well but it doesn't block the in-tree use of linker when upgrading the SDK as we set the path to a different value.

**Comment by am11** [comment]
Perhaps we could use the existing testing .template approach: https://github.com/dotnet/runtime/blob/026f615b/eng/testing/linker/project.csproj.template (copy to artifacts/obj, followed by string replacement https://github.com/dotnet/runtime/blob/026f615b/eng/testing/linker/trimmingTests.targets#L94)

**Comment by ViktorHofer** [comment]
We now have a better mechanism for that: https://github.com/dotnet/runtime/blob/026f615bdecc40a6627fdbbdd6d578d35a8da1e7/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest.pkgproj#L54-L57

`GenerateFileFromTemplate` is an arcade task that makes this easier
