### ISSUE TITLE
[API Proposal]: When using File APIs, if the given path is a directory rather than a file, an appropriate error should be raised

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/runtime#109326]
### Background and motivation

When using File APIs, an appropriate error should be raised if the given path is a directory rather than a file.

Here's the code sample that took me over an hour of clueless debugging.

Although the below code snippet looks ok, but when the value of the path parameter is a directory, it raises an **UnauthorizedAccessException** with the message **Access to the path 'E:\\' is denied**.

Here starts the confusion, clearing read-only attributes, checking permissions, etc.

However, none of this would help since the expected value should be a file path, not a directory path, making it difficult to correlate with the exception and the error message.
```
var path = @"E:\"; // Some directory path. For the sample, have hard-coded but if it's dynamically generated.
var content = "Hello, World!";
// ... Somewhere else
await File.WriteAllTextAsync(path, content);
```

### API Proposal

More appropriate error messages for File APIs.

### API Usage

More appropriate error messages for File APIs.

**Comment by huoyaoyuan** [comment]
See also #70275 . ACCESS_DENIED is what the OS returns from raw.

**Comment by egvijayanand** [comment]
I'm referring only to File APIs, which are very specific as the name implies.

**Comment by huoyaoyuan** [comment]
> IMO, this shouldn't call the underlying implementation as the value of the method parameter itself is invalid

There is no way to determine whether the parameter is valid without actually calling OS api. Windows allows you to access a file as `path\to\file\` **with trailing slash present**.

**Comment by egvijayanand** [comment]
> There is no way to determine whether the parameter is valid without actually calling OS api. Windows allows you to access a file as `path\to\file\` **with trailing slash present**.

Then, catch the **UnauthorizedAccessException** and perform a check to see if the directory exists for the given path. If it does, raise the appropriate error message.

**Comment by huoyaoyuan** [comment]
> Then, catch the **UnauthorizedAccessException** and perform a check to see if the directory exists for the given path.

This is the common mistake for handling this. File system is an external system and can change between two calls. The information must be acquired from one syscall or handle provided by OS.

**Comment by egvijayanand** [comment]
I understand that file systems can change rapidly, but the modified exception will be raised only after the directory existence check, which is a single call.

**Comment by MichalPetryka** [comment]
Could just the exception message be changed here? Do note that changing the type would by itself be a breaking change and probably not possible to do fully reliably.

**Comment by egvijayanand** [comment]
Any meaningful error message is perfectly acceptable, as long as it leads to a resolution without any ambiguity.

**Comment by huoyaoyuan** [comment]
As a low level framework, the classes provided by the BCL should be reliable and precise about what's provided by the OS. Applications and utilities built on top it can apply some heuristic about what's happening.

**Comment by huoyaoyuan** [comment]
> but the modified exception will be raised only after the directory existence check

Directory existence check is an additional syscall than the original file opening attempt, which make this approach unreliable and unacceptable.

> Any meaningful error message is perfectly acceptable

The priority of diagnostic clarity is less than reliability. If there is any way to check this within a single syscall, it may be considered.

**Comment by Clockwork-Muse** [comment]
> Directory existence check is an additional syscall than the original file opening attempt, which make this approach unreliable and unacceptable.

Granted that from a _probability_ standpoint this is likely to "succeed" the way OP wants for normal end-users ... however there are so many ways this will fail for everything else.

@egvijayanand - Here's a short list of things that can happen to the file system between the initial attempted open and any other check;
 - Drive no longer mapped (removable, network, unmounted, ....)
 - Permissions on some part of path changed (inherited permissions on Windows)
 - Some part of path deleted
 - Directory changed to file, or vice versa (_possibly_ atomically)

> Could just the exception message be changed here? Do note that changing the type would by itself be a breaking change and probably not possible to do fully reliably.

@MichalPetryka - You shouldn't have changing coding behavior based on exception messages, which aren't stable.  
That's not to say we might not update the message, but it's probably not as "helpful" as OP would like.

**Comment by Clockwork-Muse** [comment]
Closing as duplicate.
