### ISSUE TITLE
Comparer interface restrition problem

### ISSUE THREAD

**Issue by careless6666** [dotnet/runtime#109487]
Now in net 8 we have interface

```
 public abstract partial class Comparer<T> : IComparer, IComparer<T>
{
         public abstract int Compare(T? x, T? y);

        int IComparer.Compare(object? x, object? y)
}
```

and we have some generic types but it is impossible use as generic 

```
PriorityQueue<long, long> lo = new (Comparer<int>.Create((a, b) => b-a));
```
We will get an error: `Cannot implicitly convert type 'long' to 'int'`

Unfortunately there is no way to use PriorityQueue for other types such as long and uint

**Comment by careless6666** [comment]
As possible solution to use extra class only

```
PriorityQueue<long, MyLongClass> lo = new (Comparer<MyLongClass>.Create((a, b) =>
        {
            if (b.Value > a.Value)
                return 1;
            
            else return -1;
        })); // max heap

class MyLongClass(long val)
{
    public long Value { get; } = val;
}

```

**Comment by huoyaoyuan** [comment]
`IComparer<int>` and `IComparer<long>` are different types. You should use `Comparer<long>.Create`. What's the question here?

**Comment by careless6666** [comment]
PriorityQueue<long, long> lo = new (Comparer<long>.Create((a, b) => b-a)); 

It is not compile too

**Comment by skyoxZ** [comment]
```
public delegate int Comparison<in T>(T x, T y);
```
The return type should be `int`, not `T`.

**Comment by stephentoub** [comment]
```C#
PriorityQueue<long, long> lo = new (Comparer<long>.Create((a, b) => b.CompareTo(a)));
```

**Comment by careless6666** [comment]
Thanks @stephentoub
