### ISSUE TITLE
[API Proposal]: Extend `JsonPropertyName` attribute to record member declarations

### ISSUE THREAD

**Issue by zorgoz** [dotnet/runtime#109411]
### Background and motivation

Records are a simple way of defining DTOs and alike. Their immutability and simplicity make them suitable for all kinds of purposes, and serialization/deserialization is one of them. Unfortunately, `JsonPropertyName` can't be applied to their members as the definition of the attribute does not align with how the record definition syntax is. Could be extended to other serialization-related attributes currently applicable to members.

### API Proposal

- extend `JsonPropertyNameAttribute` usage with `AttributeTargets.Parameter`
- add analyzer to enforce their applicability only on record primary constructor parameters
- alter helper functionality to take these into consideration during TypeInfo generation and reflection-based serialization information gathering

### API Usage

```csharp
public record User([JsonPropertyName("i")] int Id, string [JsonPropertyName("n")] Name)
```

### Risks

LOW: If the code analyzer is inhibited by the developer, could be applied to other parameters. But that wouldn't have more side-effects it currently has, as the attribute can be applied to fields and properties never involved in serialization.

**Comment by eiriktsarpalis** [comment]
You can apply property-level annotations on positional record parameters using the following syntax:
```C#
public record User([property: JsonPropertyName("i")] int Id, [property: JsonPropertyName("n")] string Name)
```

**Comment by WeihanLi** [comment]
linked to a similar issue https://github.com/dotnet/runtime/issues/60690

**Comment by zorgoz** [comment]
yepp, that works! Thank you.

**Comment by julealgon** [comment]
@zorgoz consider switching the issue close reason to `Not planned` so as to not mislead people that this was actually implemented the way it was proposed.

**Comment by zorgoz** [comment]
Chanced reason

**Comment by zorgoz** [comment]
Reopen

**Comment by zorgoz** [comment]
Solution exist, outside library's scoow.
