### ISSUE TITLE
AssemblyResolve invoked

### ISSUE THREAD

**Issue by syrompetka** [dotnet/runtime#109403]
### Description

Our application stores shared libraries in separate "Libs" folder. Dependencies of that libraries also stored in same  "Libs" folder.
The app uses `Assembly.LoadFrom` to load required library.

When library is loaded such way for each dependency of that library `AppDomain.CurrentDomain.AssemblyResolve` is raised.
The handler of this event returns `null` but dependency library is still loaded someway.

### Reproduction Steps

Sample App reproducing the problem attached
[ConsoleApp4.zip](https://github.com/user-attachments/files/17584788/ConsoleApp4.zip)

### Expected behavior

The documentation of `AssemblyResolve` event states that it 'Occurs when the resolution of an assembly fails'.
But  dependant library is still loaded if there is no `AssemblyResolve` event handler or if event handler returns `null`.

My expectation was that no `AssemblyResolve` event is raised at all.

### Actual behavior

`AssemblyResolve` is raised and even if handler returns `null` assembly is still loaded.

### Configuration

.net6 win-x64
.net8 win-x64

**Comment by jkotas** [comment]
`Assembly.LoadFrom` installs a `AssemblyResolve` handler to resolve the dependencies that are next to the library loaded `Assembly.LoadFrom`. `Assembly.LoadFrom` is implemented using more primitive assembly loader operations. You can find the implementation at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs#L375-L404 . It explains why you see `AssemblyResolve` event called.

`Assembly.LoadFrom` exists for compatibility with .NET Framework. It is best effort to match the .NET Framework behavior. This API has number of disadvantages documented at https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfrom . You may want to replace calls to this API with something more appropriate for your scenario.

**Comment by syrompetka** [comment]
Thanks.
So the flow is following:
1. Assembly.LoadFrom installs additional handler.
2. The runtime fails to resolve assembly and calls AssemblyResolve
3. Additional handler from 1 is called.

May be calling that additional handler before AssemblyResolve event makes more sense, i.e. switching 2 and 3?

At least there is lack of documentation for this behaviour. AssemblyResolve event doc clearly states 'Occurs when the resolution of an assembly fails' but assembly is still loaded. And this causes questinons in the first place.

**Comment by jkotas** [comment]
There can be many AssemblyResolve handlers registered by different libraries. The handler registered by Assembly.LoadFrom acts as one of the many potential AssemblyResolve handlers. If your AssemblyResolve handler does not recognize the request, it should leave it alone and let the other event subscribes handle it.

**Comment by jkotas** [comment]
This is documented at https://learn.microsoft.com/en-us/dotnet/standard/assembly/resolve-loads#what-the-event-handler-does

**Comment by syrompetka** [comment]
Thanks.
