### ISSUE TITLE
The same code pinvoke will not generate. dmp in. net8, but it will generate. dmp in. net4.7.2

### ISSUE THREAD

**Issue by dotecxy** [dotnet/runtime#109402]
### Description

The same code pinvoke will not generate. dmp in. net8, but it will generate. dmp in. net4.7.2

### Reproduction Steps

Click button

### Expected behavior

. net8 wants to generate dmp when pinvoke crashes, but it won't

### Actual behavior

![Image](https://github.com/user-attachments/assets/a39471da-0a90-4926-bdc4-5cc58cdbae69)

### Configuration

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>

### Other information

```csharp
public partial class Form1 : Form
{
    private const string SDK_PATH = @"E:\Projects\sinsam\bin\app\bin\VZDirectorSdk.dll";

    public Form1()
    {
        InitializeComponent();

        EnumRTCCaptureDevice_x64(0, new EnumeratorDeviceCallback((json, p) => { }),IntPtr.Zero);
    }

    [System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.StdCall)]
    internal delegate void EnumeratorDeviceCallback([MarshalAs(UnmanagedType.LPWStr)] string deviceInfo, IntPtr userPtr);
    [DllImport(SDK_PATH, EntryPoint = "EnumRTCCaptureDevice")]
    private extern static void EnumRTCCaptureDevice_x64(int deviceType, EnumeratorDeviceCallback callback, IntPtr userPtr);


    [DllImport(SDK_PATH)]
    public extern static void SetStreamMode(int sourceId, int eid, int mode);
    private void button1_Click(object sender, EventArgs e)
    {
        SetStreamMode(-1, 1, 1);
    }
}
```

//Executing tStreamMode will cause a crash, and then the crash server will generate dmp

![Image](https://github.com/user-attachments/assets/3e85a458-6749-4ec4-af79-0c089896a0d3)

![Image](https://github.com/user-attachments/assets/69b76270-8e95-40be-a8f9-e64d52039da8)

**Comment by dotecxy** [comment]
E:\迅雷下载\SysinternalsSuite>procdump.exe 33168 -accepteula -mm -e -o C:\Users\Administrator\AppData\Roaming\sinsam\crash

ProcDump v9.0 - Sysinternals process dump utility
Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Process:               CrashTest.exe (33168)
Process image:         E:\Projects\HelloWrold\CrashTest\bin\Release\net472\CrashTest.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           C:\Users\Administrator\AppData\Roaming\sinsam\crash\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[15:18:29] Exception: C0000005.ACCESS_VIOLATION
[15:18:29] Unhandled: C0000005.ACCESS_VIOLATION
[15:18:29] Dump 1 initiated: C:\Users\Administrator\AppData\Roaming\sinsam\crash\CrashTest.exe_241031_151829.dmp
[15:18:30] Dump 1 complete: 52 MB written in 0.7 seconds
[15:18:30] Dump count reached.

____________________________________________________________________________________________________________________________________________________________________________________________

E:\迅雷下载\SysinternalsSuite>procdump.exe 28924 -accepteula -mm -e -o C:\Users\Administrator\AppData\Roaming\sinsam\crash

ProcDump v9.0 - Sysinternals process dump utility
Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Process:               CrashTest.exe (28924)
Process image:         E:\Projects\HelloWrold\CrashTest\bin\Release\net8.0-windows\CrashTest.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           C:\Users\Administrator\AppData\Roaming\sinsam\crash\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[15:19:46] Exception: C0000005.ACCESS_VIOLATION
[15:19:46] The process has exited.
[15:19:46] Dump count not reached.

**Comment by huoyaoyuan** [comment]
>  `EnumRTCCaptureDevice_x64(0, new EnumeratorDeviceCallback((json, p) => { }),IntPtr.Zero);`

This is incorrect for reverse P/Invoke. The temporary delegate will be garbage collected.

You can either store the delegate to a field, or use function pointer for callback like this:

```csharp
[DllImport(SDK_PATH, EntryPoint = "EnumRTCCaptureDevice")]
private extern static unsafe void EnumRTCCaptureDevice_x64(int deviceType, delegate*unmanaged[Stdcall]<char*, IntPtr, void> callback, IntPtr userPtr);

[UnmanagedCallersOnly(CallConvs = [typeof(CallConvStdcall)])]
static unsafe void Callback(char* str, IntPtr userPtr)
{
    string json = new string(str);
    // do whatever
}

EnumRTCCaptureDevice_x64(0, &Callback);
```

**Comment by huoyaoyuan** [comment]
And also, using **static** lambda **directly** will probably work because C# compiler caches the delegate object for you:

```csharp
EnumRTCCaptureDevice_x64(0, static (json, p) => { }, IntPtr.Zero);
```

However, this is an optimization detail that may change in the future. Anyway, DO NOT use `new` to create delegate.

**Comment by dotecxy** [comment]
> And also, using **static** lambda **directly** will probably work because C# compiler caches the delegate object for you:
> 
> EnumRTCCaptureDevice_x64(0, static (json, p) => { }, IntPtr.Zero);
> However, this is an optimization detail that may change in the future. Anyway, DO NOT use `new` to create delegate.
Thank you for your suggestion

SetStreamMode(-1, 1, 1);  at C++ code
SetStreamMode(int a,int b,int c){
       Falsifying a wild pointer is abnormal
}

**Comment by huoyaoyuan** [comment]
> Falsifying a wild pointer is abnormal

The pointer invalidates because the corresponding delegate is collected by GC.

**Comment by dotecxy** [comment]
> > Falsifying a wild pointer is abnormal
> 
> The pointer invalidates because the corresponding delegate is collected by GC.

When called by a non main thread,. dmp will be generated

**Comment by jhudsoncedaron** [comment]
>>  EnumRTCCaptureDevice_x64(0, new EnumeratorDeviceCallback((json, p) => { }),IntPtr.Zero);

> This is incorrect for reverse P/Invoke. The temporary delegate will be garbage collected.

A little story. We have this particular crash commented in source code as compiler bug lurks here because the documentation for old versions of .NET Framework said the delegate was live until the call returned. This also means we know how to fix the crashes. The following call crashes in release builds but not debug builds:

```
EnumeratorDeviceCallback callback =  (json, p) => { };
EnumRTCCaptureDevice_x64(0, new EnumeratorDeviceCallback(callback),IntPtr.Zero);
```

The following does not crash:

```
EnumeratorDeviceCallback callback =  (json, p) => { };
EnumRTCCaptureDevice_x64(0, new EnumeratorDeviceCallback(callback),IntPtr.Zero);
GC.KeepAlive(callback);
```

**Comment by jkotas** [comment]
> the delegate was live until the call returned

That's still correct. If the runtime is not keeping the delegate alive while the PInvoke is executing, it is a bug.

**Comment by jhudsoncedaron** [comment]
@jkotas : I'll let you and @huoyaoyuan duke it out. If it's a bug it has amazing seniority. I first observed it in .NET Framework 2 in 2007.

**Comment by jkotas** [comment]
> I first observed it in .NET Framework 2 in 2007.

It is possible that some versions of .NET Framework 2 had issues in this logic. As far as I know, there are not issues in this logic in the fully serviced .NET Framework 2.x and .NET Framework 4.x.

For reference, this is the code responsible for keeping the delegate alive for the duration of the P/Invoke call: https://github.com/dotnet/runtime/blob/3218072c88b9fa3bf677317936b3fe8b20034cf4/src/coreclr/vm/ilmarshalers.cpp#L121-L124

**Comment by dotecxy** [comment]
> > I first observed it in .NET Framework 2 in 2007.
> 
> It is possible that some versions of .NET Framework 2 had issues in this logic. As far as I know, there are no issues in this logic in the fully serviced .NET Framework 2.x and .NET Framework 4.x.
> 
> For reference, this is the code responsible for keeping the delegate alive for the duration of the P/Invoke call:
> 
> [runtime/src/coreclr/vm/ilmarshalers.cpp](https://github.com/dotnet/runtime/blob/3218072c88b9fa3bf677317936b3fe8b20034cf4/src/coreclr/vm/ilmarshalers.cpp#L121-L124)
> 
> Lines 121 to 124 in [3218072](/dotnet/runtime/commit/3218072c88b9fa3bf677317936b3fe8b20034cf4)
> 
>  if (IsCLRToNative(m_dwMarshalFlags)) 
>  { 
>      EmitKeepAliveManagedValue(); 
>  }

Thank you for your reply.
What I want to express is not the crash caused by callback activation, but rather.
SetStreamMode 100% will trigger a crash.

[DllImport(SDK_PATH)]
public extern static void SetStreamMode(int sourceId, int eid, int mode);
private void button1_Click(object sender, EventArgs e)
{
    SetStreamMode(-1, 1, 1);
}

This way of writing will not be caught crashing by procdump


---------------------------------------------------------------------------------------------------
[DllImport(SDK_PATH)]
public extern static void SetStreamMode(int sourceId, int eid, int mode);
private void button1_Click(object sender, EventArgs e)
{
    Thread  th=new Thread((_)=>{
SetStreamMode(-1, 1, 1);
}); 
th.Start();
}
Writing in this way will be caught crashing by procdump

**Comment by dotecxy** [comment]
![Image](https://github.com/user-attachments/assets/b2307c06-0a2d-4377-ace7-becce9748bfa)

**Comment by AaronRobinsonMSFT** [comment]
The fact that moving this to another thread and this being in a WinForms applications would seem to indicate there is something different about the main thread in WinForms. @dotecxy Can you please try this on a simple Console application?

**Comment by dotecxy** [comment]
https://github.com/dotnet/runtime/issues/103000
