### ISSUE TITLE
'RuntimeType.TypeHandle' throws 'NotSupportedException' on NativeAOT after publishing with 0 ILC warnings

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#109496]
### Description

Noticed a runtime crash in some IDIC scenarios while porting the Microsoft Store to Native AOT (.NET 9). This happens after publishing with 0 trim/AOT warnings from ILC (as well as the analyzers), so I'm inclined to think it's some issue in ILC not correctly tracking things during trimming.

### Reproduction Steps

I don't really have a minimal repro, as this also requires all the preview UWP on .NET 9 tooling (this repros with some internal UWP XAML interface, so I don't have an equivalent for WinUI 3). However I can easily share repro steps if you're willing to clone the Store (eg. like we did in #109272 and related issues). I can also share crash dumps or anything else that can help.

### Expected behavior

Code should work correctly on Native AOT.

### Actual behavior

> 0x80049d08c0 [Type: S_P_CoreLib_System_NotSupportedException * (derived from S_P_CoreLib_System_Exception *)]
>
>    [+0x008] _message         : 0x80049d0c48 : "'ABI.Windows.UI.Xaml.IFrameworkElementProtected7' is missing native code or metadata. This can happen for code that is not compatible with trimming or AOT. Inspect and fix trimming and AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility" [Type: String &]

![Image](https://github.com/user-attachments/assets/2fee2dba-d268-4120-9fae-6081cf336e33)

### Regression?

No.

### Known Workarounds

This seems to do the trick:

```csharp
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(ABI.Windows.UI.Xaml.IFrameworkElementProtected7))]
```

### Configuration

- VS 17.12 P5
- .NET 9 RC2

**Comment by MichalStrehovsky** [comment]
Has been broken since .NET 7.

We optimize away type handles when possible because one cannot do much with them without hitting actual trim-unsafe code. This case however can run into needing the type handle for trim safe code.

Repro:

```csharp
using System.Reflection;
using System.Runtime.InteropServices;

object o = new CastableThing();
((IMyInterface)o).Method();

class CastableThing : IDynamicInterfaceCastable
{
    RuntimeTypeHandle IDynamicInterfaceCastable.GetInterfaceImplementation(RuntimeTypeHandle interfaceType)
    {
        return Type.GetTypeFromHandle(interfaceType).GetCustomAttribute<TypeAttribute>().TheType.TypeHandle;
    }

    bool IDynamicInterfaceCastable.IsInterfaceImplemented(RuntimeTypeHandle interfaceType, bool throwIfNotImplemented)
    {
        return Type.GetTypeFromHandle(interfaceType).IsDefined(typeof(TypeAttribute));
    }
}

[Type(typeof(IMyInterfaceImpl))]
interface IMyInterface
{
    void Method();
}

[DynamicInterfaceCastableImplementation]
interface IMyInterfaceImpl : IMyInterface
{
    void IMyInterface.Method() => Console.WriteLine("Hello");
}

class TypeAttribute : Attribute
{
    public Type TheType { get; }

    public TypeAttribute(Type t) => TheType = t;
}
```
