### ISSUE TITLE
CultureInfo on iOS doesn't have all the information that Windows or Android have.

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#109444]
_From @Joost-Jens-Luminis on Fri, 01 Nov 2024 08:10:37 GMT_

### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

8.0.402

### Description

I am creating a language select UI in our app. On WIndows and Android I can use "CultureInfo.NativeName" to show the name in the native language. On iOS it just shows the language code.

Screentshots for maximum effect: (Using Korean to clearly show it, but it applies to all cultures).
Windows:
![image](https://github.com/user-attachments/assets/c7ac5cd8-c36c-41b8-88f2-2bb06eb7e4a9)

Android:
![image](https://github.com/user-attachments/assets/541b13b8-55b9-4e18-b003-31afa27f754a)

iOS:
![image](https://github.com/user-attachments/assets/e4b7c6b6-cc8b-4e41-8eed-d05233a3088d)

### Steps to Reproduce

I use the following code to get all the cultures:
```C#
                var allCultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
                foreach (var c in allCultures)
                {
                    if (c.Name.StartsWith("ko-"))
                    {
/// Breakpoint here to see the culture info :)
                    }
                }
```

_Copied from original issue xamarin/xamarin-macios#21567_

**Comment by Joost-Jens-Luminis** [comment]
Thanks for relocating this @rolfbjarne .

Another issue I just noticed, my iOS device doesn't have ko-KP, only ko-KR. Not that I need north korean culture specifically but though it was interesting enough to mention. This indicates there is also a discrepancy on the list of cultures itself.

My iOS device has 240 cultures, while Android has 754 and Windows has 869 cultures.

**Comment by Clockwork-Muse** [comment]
_Maybe_.

I don't have an iOS device to test with, so don't know what's available for use here.

**Comment by tarekgh** [comment]
@matouskozak could you please have a look? Thanks!

**Comment by karakasa** [comment]
possibily useful:

https://stackoverflow.com/questions/65049438/how-to-get-human-friendly-current-local-language-name-in-ios

**Comment by matouskozak** [comment]
This should be fixed in .NET 9 release. In .NET 8, we were using so-called "hybrid" approach where we used a combination of .NET shipped ICU with the native ICU provided by Apple. The "hybrid" approach was used to provide a compromise between size and the supporting all globalization functionality.

In .NET 9, we switched to using the full native ICU provided by Apple which should contain the correct native names. It also contains both KO-KP and KO-KR (and also KO-CN) cultures.

From .NET 9 RC1 MAUI Mac Catalyst app:
![Image](https://github.com/user-attachments/assets/2f241551-412b-476a-865b-1444e1bc7785)

**Comment by Joost-Jens-Luminis** [comment]
@matouskozak That is good to know. 

Just to clarify though, there will remain a difference between the supported culture lists on each platform (e.g. between Windows and iOS) as the lists are platform specific. The only thing that is fixed in .Net 9.0 is that the culture information now completely comes from the platform.

Does this about sum it up?

**Comment by matouskozak** [comment]
> [@matouskozak](https://github.com/matouskozak) That is good to know.
> 
> Just to clarify though, there will remain a difference between the supported culture lists on each platform (e.g. between Windows and iOS) as the lists are platform specific. The only thing that is fixed in .Net 9.0 is that the culture information now completely comes from the platform.
> 
> Does this about sum it up?

Yes, correct. For the iOS case, the difference should be getting smaller and smaller as we polish the retrieval of globalization data from the native ICU. However, there still might be differences if the shipped ICU by Apple and Windows fundamentally differ.

**Comment by Joost-Jens-Luminis** [comment]
Ok, thanks for the clarification. I am not sure i necessarily agree with that decision, but I guess if you think parity with .net apps on other platforms, or parity with non dotnet apps on the same platform is more important.
Knowing Apple they might even require the latter, if not now then in the future.

This issue can be closed then as far as I am concerned.

**Comment by matouskozak** [comment]
> with that decision, but I guess if you think parity with .net apps on other platforms, or parity with non dotnet apps on the same platform is more important. Knowing Apple they might even require the latter, if not now then in the future.
> 
> This issue can be closed then as far as I am concerned.

Both ways have its pros and cons. For iOS, the reason to use Apple ICU instead of shipping a standardized ".NET ICU" is the size of the app as including an extra ICU with full set of cultures increases the app size significantly.

**Comment by Clockwork-Muse** [comment]
It's possible to bundle [your own copy of the ICU libraries/data](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu), which would make the behavior the same.  This is not recommended.

Besides increasing the size of your app, there are additional downsides.  But _generally_ this is extra work for little gain, as few users would notice the differences (and if your code is sensitive to the changes, you have larger problems).
