### ISSUE TITLE
X.509 Cert

### ISSUE THREAD

**Issue by raselldev** [dotnet/runtime#109478]
### Description

I just install some nuget package with some warning,

```
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.403/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.403/trustedroots/timestampctl.pem'.
```

i just run dotnet dev-certs https --trust and still get error like above

```
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'security add-trusted-cert -p basic -p ssl -k <<login-keychain>> <<certificate>>'
This command might prompt you for your password to install the certificate on the keychain. To undo these changes: 'security remove-trusted-cert <<certificate>>'
```

IDE: Jetbrains Rider (Mac M1)
Terminal: iTerm2

### Reproduction Steps

1. running dotnet add package SomePackage
2. Get warning

### Expected behavior

Not showing error

### Actual behavior

-

**Comment by vcsjones** [comment]
My understanding is that these are not errors, they are just informational text that comes from NuGet.

/cc @dtivel

**Comment by dtivel** [comment]
These are informational messages that tell you what root stores will be used during NuGet signed package verification:

```
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.403/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.403/trustedroots/timestampctl.pem'.
```

They are not errors.  Errors would start the line with "error".

**Comment by vcsjones** [comment]
I am going to close this issue as all questions have been answered, and there appears to be no further action needed on our part.

Please feel free to re-open the question if there are any outstanding concerns or issues. For more questions or feedback about NuGet, I would recommend filing those issues over at https://github.com/nuget/Home, where the appropriate team can address the question or issue.
