### ISSUE TITLE
R2RDump - List of sections not yet parsed

### ISSUE THREAD

**Issue by acmyu** [dotnet/runtime#10948]
- [ ] `READYTORUN_SECTION_EXCEPTION_INFO`
- [x] `READYTORUN_SECTION_DEBUG_INFO`
- [ ] `READYTORUN_SECTION_DELAYLOAD_METHODCALL_THUNKS`
- [ ] `READYTORUN_SECTION_INLINING_INFO`
- [ ] `READYTORUN_SECTION_PROFILEDATA_INFO`
- [ ] `READYTORUN_SECTION_IMPORT_SECTIONS` is not yet parsed correctly

**Comment by nattress** [comment]
We implemented this already
