### ISSUE TITLE
Culture-Info for no-No appears to differ between MacOs and Linux runtime

### ISSUE THREAD

**Issue by mrBoie** [dotnet/runtime#109409]
### Description

When creating a test with formatting of a decimal to currency in no-NO the resulting string seems to differ depending on if i am running on my local macbook or running in a github action.

Guessing that the `CultureInfo.NumberFormat.CurrencyPositivePattern` differs

### Reproduction Steps

```*.cs
    [Fact]
    public void TestNoLocale()
    {
        var magicNumber = 123.456m;
        var cultureInfo = new CultureInfo("no-NO");
        var formattedPriceWithCurrency = magicNumber.ToString("C", cultureInfo);

        // Fails on mac, passes on github actions
        Assert.Equal("kr 123,46", formattedPriceWithCurrency);

        // Fails on github actions, passes on mac
        Assert.Equal("123,456 kr", formattedPriceWithCurrency);
    }
```

### Expected behavior

Same behaviour on all runtimes in relation to culture specific formatting of currencies

### Actual behavior

Different behaviour between mac and github actions when formatting a decimal to currency using the no-NO culture-info

### Configuration

Mac version: 15.0.1 (24A348)
Github action

Current runner version: '2.320.0'
- Operating System
  Ubuntu
  [2](https://github.com/polestar/fsa-back/actions/runs/11609133256/job/32325778400?pr=1314#step:1:2)2.04.5
  LTS
- Runner Image
  Image: ubuntu-22.04
  Version: 20241015.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241015.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241015.1

**Comment by Clockwork-Muse** [comment]
>Expected behavior
>
> Same behaviour on all runtimes in relation to culture specific formatting of currencies

Your expectation is wrong - culture information is normally sourced from the OS, and varies per host.  There is no guarantee that the data will match anywhere, or even multiple processes/applications on the same machine.  

> When creating a test with formatting of a decimal to currency in no-NO the resulting string seems to differ depending on if i am running on my local macbook or running in a github action.

Don't do this.  Instead:
 - For most tests, simply verifying that you get non-empty output for formatting will be sufficient.
 - If you really need to validate something about the output, create a custom psuedo-locale that you provide all the culture data for, and validate that.  

Under no circumstances should you ever assume culture data is stable - it can change at any time, without warning, so such a test is already brittle and can break in the future.

Closing as by-design
