### ISSUE TITLE
typeof() prevents the assembly from unloading

### ISSUE THREAD

**Issue by vblegend** [dotnet/runtime#109479]
### Description

The typeof() operator prevents assembly unloading of AssemblyLoadContext,
The Delegate is always strongly referenced and cannot be accessed by GC

## Caller (can uninstall the assembly)

``` csharp
   var weakIsTypeEqual = state.CreateDelegate<Func<Type, Boolean>>("ScriptExample", "IsTypeEqual"); // use Delegate.CreateDelegate(typeof(T), instance, MethodInfo);
   if (weakIsTypeEqual.TryGetTarget(out var isTypeEqual))
   {
       var type = typeof(Console);
       var bol = isTypeEqual(type);
       Console.WriteLine(bol);
       isTypeEqual = null;
   }
```

## Caller (assembly cannot be uninstalled)

``` csharp
   var weakIsTypeEqual = state.CreateDelegate<Func<Type, Boolean>>("ScriptExample", "IsTypeEqual"); // use Delegate.CreateDelegate(typeof(T), instance, MethodInfo);
   if (weakIsTypeEqual.TryGetTarget(out var isTypeEqual))
   {
       var bol = isTypeEqual(typeof(Console));
       Console.WriteLine(bol);
       isTypeEqual = null;
   }
```

##  The referenced assembly
``` csharp
public class ScriptExample
{
    public Boolean IsTypeEqual(Type type)
    {
        return type == typeof(AbstractScript);
    }
}
```

### Expected behavior

Using typeof(Console) directly in a method argument should not prevent assembly uninstallation

### Actual behavior

Calling method delegates directly with isTypeEqual(typeof(Console)) results in isTypeEqual being strongly referenced all the time

There is no problem if typeof(Console) is passed in by defining a variable

### Configuration

.net 8 
windows 11 X64

**Comment by huoyaoyuan** [comment]
Possibly related to #109441. The two snippets generates exactly the same assembly code under Release: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYRoG8aHunHiUGAWXIAKAOoxsAawBKMAGYxYAOzAwAPMQCs6gCoBPAA4w0DAEIQIAG0nKAfHYYB3SVICSuA8YCiARwCu2FYAlFw8nNQ8UQCW8gwiLtIeXjB+gVYAdLpQ+gDiMBi62FAA5gUiEP4YDABuxQzRnkapAUHBoZFR3BFdvXVQDBjNDAC8g80Q8iIsEMq41jDBANxhvTz9DMDWow1NPq1WIkPGy6trTOQAnCJbISud57spaUE7yv5WVvdrAL5nfw8GGd6EwBIJSOJXHJFCo1JodClTBYFth7I5Eu49i10h0oj1erF4hjks0XplsnkCkVSuVKtUNo1ngd2mdwqy+vVbjtGaSDkcJlMZnMFu1vo8LtdbqdAWseft0m8Pl92QwAVEAT8gA==

Make sure to fully exist the caller method when testing for GC. Otherwise, the result will often be wrong due to debugging information and optimizations.

**Comment by vblegend** [comment]
> Possibly related to [#109441](https://github.com/dotnet/runtime/issues/109441). The two snippets generates exactly the same assembly code under Release: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYRoG8aHunHiUGAWXIAKAOoxsAawBKMAGYxYAOzAwAPMQCs6gCoBPAA4w0DAEIQIAG0nKAfHYYB3SVICSuA8YCiARwCu2FYAlFw8nNQ8UQCW8gwiLtIeXjB+gVYAdLpQ+gDiMBi62FAA5gUiEP4YDABuxQzRnkapAUHBoZFR3BFdvXVQDBjNDAC8g80Q8iIsEMq41jDBANxhvTz9DMDWow1NPq1WIkPGy6trTOQAnCJbISud57spaUE7yv5WVvdrAL5nfw8GGd6EwBIJSOJXHJFCo1JodClTBYFth7I5Eu49i10h0oj1erF4hjks0XplsnkCkVSuVKtUNo1ngd2mdwqy+vVbjtGaSDkcJlMZnMFu1vo8LtdbqdAWseft0m8Pl92QwAVEAT8gA==
> 
> Make sure to fully exist the caller method when testing for GC. Otherwise, the result will often be wrong due to debugging information and optimizations.



Thank you for your response
the problem may be scope-related, it may be a problem with my test case.
This problem disappeared when I split the code block into a new method.

``` csharp

static void Main()
{
  var result = Compile();
  if (result.Success)
  {
      var stateOptions = StateOptions.Default;
      stateOptions.RegisterProvider(new TimerService());
      var state = scriptManager.CreateState(stateOptions);
      var weakIsTypeEqual = state.CreateDelegate<Func<Type, Boolean>>("ScriptExample", "IsTypeEqual");
      if (weakIsTypeEqual.TryGetTarget(out var isTypeEqual))
      {
          var bol = isTypeEqual(typeof(Console));
          Console.WriteLine(bol);
          isTypeEqual = null;
      }
      state = null;
      scriptManager.Unload(true);
  }

  while (true)
  {
      // Trigger GC, Recycling more memory
      var obj = new byte[1024 * 1024];
      Thread.Sleep(10);
      GC.Collect();
  }

}
```



``` csharp
    public static void CallIsTypeEqual(IMagnetState state)
    {
        var weakIsTypeEqual = state.CreateDelegate<Func<Type, Boolean>>("ScriptExample", "IsTypeEqual");
        if (weakIsTypeEqual.TryGetTarget(out var isTypeEqual))
        {
            var bol = isTypeEqual(typeof(Console));
            Console.WriteLine(bol);
            isTypeEqual = null;
        }
    }

static void Main()
{
  var result = Compile();
  if (result.Success)
  {
      var stateOptions = StateOptions.Default;
      stateOptions.RegisterProvider(new TimerService());
      var state = scriptManager.CreateState(stateOptions);
      CallIsTypeEqual(state );
      state = null;
      scriptManager.Unload(true);
  }

  while (true)
  {
      // Trigger GC, Recycling more memory
      var obj = new byte[1024 * 1024];
      Thread.Sleep(10);
      GC.Collect();
  }

}
```

**Comment by hez2010** [comment]
You can try setting the following to bypass tier-0 compilation:

```xml
<PropertyGroup>
    <TieredCompilation>false</TieredCompilation>
</PropertyGroup>
```

Tier-0 compilation can extend the lifetime of a local in the method.

**Comment by vblegend** [comment]
> TieredCompilation



> You can try setting the following to bypass tier-0 compilation:
> 
> <PropertyGroup>
>     <TieredCompilation>false</TieredCompilation>
> </PropertyGroup>
> Tier-0 compilation can extend the lifetime of a local in the method.

I tried that, but it didn't work.

**Comment by vblegend** [comment]
> [@vblegend](https://github.com/vblegend) the thing is that JIT can create helper locals or extend lifetime of variables, especially in Debug build, but in Release too. So if you want to be sure that a reference in some local is really gone, you need to put that stuff into a separate method marked so that it doesn't get inlined and try to unload only after it returns. Please see my doc on that here: https://learn.microsoft.com/en-us/dotnet/standard/assembly/unloadability
Thank you for your reply
I'm just curious why is it okay to put it in a variable, but it's not okay to use it directly
In fact, I'm doing this too, probably because I don't know much about .NET's mechanics
https://github.com/vblegend/Magnet
