### ISSUE TITLE
ValidateDataAnnotations doesn't work for nullable types

### ISSUE THREAD

**Issue by TristenFielding** [dotnet/runtime#109483]
### Description

Discovered that nullable types aren't being validated when using the `ValidateDataAnnotations` method from the `OptionsBuilderDataAnnotationsExtensions` class.

### Reproduction Steps

Using 
```xml
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0" />
```

Code snippet:
```C#
var builder = new HostApplicationBuilder(args);

builder.Configuration.AddInMemoryCollection([
        new ("WhatIf", "true"),
        new ("TreeMaxDepth", "15")
    ]);

builder.Services.AddOptions();
builder.Services.AddOptions<Settings>().ValidateDataAnnotations().ValidateOnStart();

using var host = builder.Build();

// Should fail here, but it does NOT because MaxDepth is defined as int?. Now change it to just int, and now it does fail.
var settings = host.Services.GetRequiredService<IOptions<Settings>>().Value;

await host.StartAsync();

public class Settings
{
    [TypeConverter(typeof (BooleanConverter))]
    public bool WhatIf { get; set; }

    // Note: ValidateDataAnnotations doesn't work for nullable types.
    //
    [Range(1, 10)]
    [TypeConverter(typeof(Int32Converter))]
    public int? MaxDepth { get; set; }
}
```

### Expected behavior

Should validate nullable types.

### Actual behavior

Skipping validation for nullable types.

### Configuration

Microsoft Visual Studio Professional 2022
Version 17.11.4
VisualStudio.17.Release/17.11.4+35312.102
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

ASP.NET and Web Tools   17.11.231.19466
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.11.231.19466
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.11.231.19466
Azure Functions and Web Jobs Tools

C# Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub Copilot   0.2.1653.9816
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.11.3.2442001+68650a7d94261bc56a1f4bc522c2ee35314b1abb
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.11.47.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.30715.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.11.0-beta.24421.7+af2f522de602281d4ef5a7b71507c428e814c5c1
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by tarekgh** [comment]
You have a couple of problems with your code. 

- First, you have names the configuration field as `TreeMaxDepth` while you should name it as `MaxDepth`
- Second, you need to do the configuration binding which you are missing. Basically no configuration binding was happening in your code. 

Try the following code and this should work fine:

```C#
            var builder = Host.CreateDefaultBuilder(args);

            builder.ConfigureAppConfiguration((context, config) =>
            {
                config.AddInMemoryCollection(new Dictionary<string, string?>
                {
                    { "WhatIf", "true" },
                    { "MaxDepth", "15" } // <------ ensure you have a correct naming to the configuration 
                });
            });

            builder.ConfigureServices((context, services) =>
            {
                services.Configure<Settings>(context.Configuration); // <-------- Ensure your enable binding to your configuration

                services.AddOptions<Settings>().ValidateDataAnnotations().ValidateOnStart();
                services.AddOptions();
            });

            using var host = builder.Build();

            var settings = host.Services.GetRequiredService<IOptions<Settings>>().Value;

            await host.StartAsync();
```
