### ISSUE TITLE
Make SocksException(SR.net_socks_connection_failed) more informative

### ISSUE THREAD

**Issue by alexeev-igor** [dotnet/runtime#109404]
When it's impossible to connect socks5 proxy server dotnet [throws](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocksHelper.cs#L193) SocksException with general [message](https://github.com/dotnet/runtime/blob/d2a2a79b2eaf66d68a02f35917907bd9fbe97ea7/src/libraries/System.Net.Http/src/Resources/Strings.resx#L546) "SOCKS server failed to connect to the destination.". And it's hard to understand what exactly went wrong, because proxy server can return different "errors" bytes (from 0x01 to 0x08).

For example, golang throws/returns different errors for each different byte: https://github.com/golang/net/blob/511cc3a40645a2f6ed3d21a1d0803b5057b9aaa1/internal/socks/client.go#L115
https://github.com/golang/net/blob/511cc3a40645a2f6ed3d21a1d0803b5057b9aaa1/internal/socks/socks.go#L40-L63

So my proposal is include "error" byte (0x01-0x08) in SocksException or make different messages for each byte (how it's done in golang).

**Comment by wfurt** [comment]
That seems reasonable _if_ we get some data back, any more thoughts on this @MihaZupan ? You may still get generic error if fail to connect.

**Comment by alexeev-igor** [comment]
@MihaZupan yea, sure, why not :)
