### ISSUE TITLE
Impossible to JsonSerialize.Serialize(IPAddress.None)?

### ISSUE THREAD

**Issue by jamesivie** [dotnet/runtime#109401]
### Description

It's pretty absurd that System.Net.IPAddress doesn't have a built-in serializer for JsonSerialize.  However, it's much, much worse that it appears to be impossible to build a custom serializer for JsonSerializer that will work for even all system-defined IP addresses.  Serializing IPAddress.None, IPAddress.Any or any of the other static readonly IP Address values appears to be impossible.  With a custom serializer, you can serialize *most* IP addresses, including ones equivalent to those IPAddresses that have been parsed from strings, but not those built-in values.

### Reproduction Steps

```
/// <summary>
/// A JsonConverter for System.Net.IPAddress.
/// </summary>
public class IPAddressConverter : JsonConverter<System.Net.IPAddress>
{
    /// <summary>
    /// Reads the JSON representation of the object.
    /// </summary>
    /// <param name="reader">The <see cref="Utf8JsonReader"/> to read the object from.</param>
    /// <param name="typeToConvert">The type to convert.</param>
    /// <param name="options">The <see cref="JsonSerializerOptions"/> to use to interpret the formatting.</param>
    /// <returns>The <see cref="System.Net.IPAddress"/> that was deserialized.</returns>
    public override System.Net.IPAddress Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? ip = reader.GetString();
        System.Net.IPAddress? ipAddress = (ip == null) ? null : System.Net.IPAddress.Parse(ip);
        return ipAddress ?? System.Net.IPAddress.None;
    }
    /// <summary>
    /// Writes the JSON representation of the object.
    /// </summary>
    /// <param name="writer">The <see cref="Utf8JsonWriter"/> to write the object into.</param>
    /// <param name="value">The <see cref="System.Net.IPAddress"/> to write.</param>
    /// <param name="options">The <see cref="JsonSerializerOptions"/> to use for formatting the data.</param>
    public override void Write(Utf8JsonWriter writer, System.Net.IPAddress value, JsonSerializerOptions options)
    {
#if NET5_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(writer);
#else
        if (writer is null) throw new ArgumentNullException(nameof(writer));
#endif
        writer.WriteStringValue(value?.ToString());
    }
}

[TestMethod]
public void DotNetBug()
{
    JsonSerializerOptions options = new() { WriteIndented = true, NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals };
    options.Converters.Add(new IPAddressConverter());

    Dictionary<string, object?> dictionary = new()
    {
        { "key", System.Net.IPAddress.Parse("0.0.0.0") },
    };

    string json = JsonSerializer.Serialize(dictionary, options);

    dictionary["Key"] = System.Net.IPAddress.Any;

    json = JsonSerializer.Serialize(dictionary, options);
}

```

### Expected behavior

Serialization of System.Net.IPAddress.Any should be possible.

### Actual behavior

System.ArgumentException: 'GenericArguments[1], 'System.ReadOnlySpan`1[System.Byte]', on 'System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[T,TArg0,TArg1,TArg2,TArg3]' violates the constraint of type 'TArg0'.'

### Regression?

No

### Known Workarounds

None

### Configuration

.NET 8.0

**Comment by huoyaoyuan** [comment]
The json converter is not applied at the second call in your example. If you do `JsonSerializer.Serialize(IPAddress.Any, options)`, it runs fine.

**Comment by huoyaoyuan** [comment]
The real reason is that the type of `IPAddres.Any` is not `IPAddress` - it's a sub class `ReadOnlyIPAddress`. When calling with strongly-typed `Serialize`, the converter for base class `IPAddress` is used. When calling with object-typed path like `JsonSerializer.Serialize<object>(IPAddress.Any, options)`, the converter for `IPAddress` is not used.

**Comment by jamesivie** [comment]
Yes, the reason is clear from the source code and the exception, but that's an *implementation detail*.  Of course `IPAddress` is a legacy class from long ago, so I can understand most of why it was the way it is, but as a system-defined class that is widely used, and being logically immutable, it should logically behave something like the way that DateTime does, easily comparable and serializable, (and sortable would make sense too).  However, it's not and I'm not seeing any external way to fix the serialization problem other than not to ever use it in contexts where it gets serialized without strong typing, which makes it less than useless--that makes it so that I (and everyone else trying to do this) have to convert from it (because .NET uses it in plenty of places) to my own custom non-broken implementation, with the only reason for doing that being that the people who own the source won't support serializing it in the only way that would make sense to *any* user of the class.  In my case I'm trying to log things in JSON format, so that's a big problem as values in log entries are generally untyped, and guess what?  I need to log `IPAddress` a *lot*.  The custom serializer works most of the time, but not for these static values, and for a system-defined type that represents something that's more strictly-defined than DateTime, that seems bad.  `DateTime` and all its variants are supported in `JsonSerializer`, so why not `IPAddress`?  From the code, it looks like there may be security reasons for implementing them this way in an attempt to prevent certain superficial hacks (maybe?  but if so, why don't the IPv6 versions of the same thing do it the same way then?), but that kind of alteration should be implemented in a way that doesn't interfere with expected standard functionality.

**Comment by huoyaoyuan** [comment]
> but that's an _implementation detail_

No, it's feature application for converter of inherit class.

> but as a system-defined class that is widely used

The term "system-defined" is very vague. System.Text.Json knows nothing about System.Net. It's not as low-level as numbers or `DateTime`. See the discussion in #97494.

**Comment by huoyaoyuan** [comment]
Note that there can be some improvements done for the default serializing of `JsonSerializer`, not specific for `ReadOnlyIPAddress`: it fails to create the generic converter because the inferred serialization constructor doesn't work, while only deserialization is asked for.

**Comment by huoyaoyuan** [comment]
The behavior is actually consistent. When doing `JsonSerializer.Serialize(IPAddress.Any, options)`, the inferred generic argument is the static type `IPAddress`, not the implementation type `ReadOnlyIPAddress`. This is unrelated to whether built-in support is present. Consider the following snippet:

```csharp
using System;
using System.Text.Json;

Uri ReturnUri() => new MyUri([]);

MyUri ReturnMyUri() => new MyUri([]);

Console.WriteLine(JsonSerializer.Serialize(ReturnUri())); // Success
Console.WriteLine(JsonSerializer.Serialize(ReturnMyUri())); // Fail
Console.WriteLine(JsonSerializer.Serialize<object>(ReturnUri())); // Fail

class MyUri(ReadOnlySpan<byte> _) : Uri("http://example.com")
{

}
```

That's why weakly-type serialization is not recommended.

**Comment by jamesivie** [comment]
Yes, I understand why it's failing with the code the way it is.  However, #97494 completely ignores the fact that a proper custom serializer CANNOT BE WRITTEN.  I don't care so much about where the changes for a fix go.  It's a very commonly used system class representing a well-defined logically-immutable value that also has a well-defined standard string representation.  It then has public system-defined values that, apparently, CANNOT be serialized no matter what any external person does.  That is bad.  I can't even see how the existence of `ReadOnlyIPAddress` provides any useful functionality.  It's just a transparent wrapper on one of the constructors and if there's a security issue it's solving, wouldn't the same issue affect IPv6 too?  Why don't the IPv6 statics use `ReadOnlyIPAddress`?

**Comment by huoyaoyuan** [comment]
Any private class used as implementation detail can't be specified with json converter with weakly-typed serialization. The strategy can be modified to find the nearest base type, but the logic is problematic for interfaces.
The only answer is NOT using weakly-typed serialization. It causes many sort of problems.

**Comment by jamesivie** [comment]
That's true, but I think it's completely reasonable that all IP addresses should be serializable even without strong typing information.  I think most developers would agree with that and would be quite surprised that it doesn't work, as there are plenty of use cases that would require this functionality, and it works with every other system-defined type with the same properties (commonly used, relatively simple types with explicitly standardized binary and string serializations).  

There appear to be three possible solutions to fix this problem to make it work as expected at this point.  The most reasonable one at this point would appear to be to change the `IPAddress` implementation to not use the apparently useless privately-defined `ReadOnlyIPAddress` class for those static instances.  Looking at the code today, I can't fathom why that class exists at all, and why `IPAddress` isn't sealed, unless it was to support some functionality that no longer exists or exists outside of the class itself (but given that everything is private rather than protected, it would seem to not be a very useful thing to derive a class from anyway).  `IPAddress`, from everything I can see is *already* readonly, so a `ReadOnlyIPAddress` class is both redundant and pointless.  However I can understand that there may be some underlying reason that is not apparent from looking at the code.  In that case, adding a custom serializer for `ReadOnlyIPAddress` inside `System.Net` would be the next-best solution (though this would probably require callers to explicitly configure it in their options, which would seem like an unnecessary complication).  The third solution is to create a special case in `JsonSerializer` to handle this particular type.  I hate special cases, and that would only be the proper solution if there are very good reasons to not fix the `IPAddress` implementation (backwards-compatibility comes to mind here).

Not implementing one of these solutions (or another one I haven't thought of) would seem unreasonable in that from a high-level design perspective, there doesn't seem to be a good reason why IP addresses should not be serializable, strong typing or not.

**Comment by yesmey** [comment]
If you are fine with using the same converter for all types derived by IPAddress, you can make a `JsonConverterFactory` that will be used by both `ReadOnlyIPAddress` and `IPAddress`
```csharp
public class IPAddressConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
        => typeToConvert.IsAssignableTo(typeof(System.Net.IPAddress));

    public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        => new IPAddressConverter();
}
```

**Comment by jamesivie** [comment]
@yesmey, excellent!  That's not a solution I knew was possible, but that's a decent workaround.

**Comment by eiriktsarpalis** [comment]
Closing as duplicate of #97494.
