### ISSUE TITLE
[NativeAOT] Creating a new thread from DllMain makes the program get stuck.

### ISSUE THREAD

**Issue by nitrog0d** [dotnet/runtime#109543]
### Description

NativeAOT dlls get stuck when creating a new thread from DllMain using `new Thread()`.
`Task.Run` does similar behavior, instead when I try to sleep inside the Task, it gets stuck.

### Reproduction Steps

- Make NativeAOT dynamic library project for Windows with DllMain.
```cs
using System.Runtime.InteropServices;
using Windows.Win32;

namespace ThreadTesting;

public static class ThreadTest {
    [UnmanagedCallersOnly(EntryPoint = "DllMain")]
    public unsafe static int DllMain(nint hModule, uint ul_reason_for_call, nint lpReserved) {
        // DLL_PROCESS_ATTACH = 1
        if (ul_reason_for_call == 1) {
            Console.WriteLine("Creating new thread");

            var thread = new Thread(SomeFunction);
            // It gets stuck here
            thread.Start();

            Console.WriteLine("Thread created");
        }

        return 1;
    }

    public static void SomeFunction() {
        Console.WriteLine("Hello inside new thread");
        Thread.Sleep(1000);
        Console.WriteLine("Slept successfully");
    }
}
```

- Make a simple C++ console app that loads the library with LoadLibrary.
```cpp
int main()
{
    LoadLibrary(L"ThreadTesting.dll");
}
```

### Expected behavior

The new thread runs correctly.

### Actual behavior

The program gets stuck.

### Known Workarounds

Using Native Windows function CreateThread (PInvoke) works.

### Configuration

- .NET 9.0.0-rc.2.24473.5
- Windows 11 Build 22631
- x64

**Comment by MichalPetryka** [comment]
Running managed code in `DllMain` is not supported, doing so is expected to deadlock or crash.

**Comment by nitrog0d** [comment]
Do I close this issue then?

**Comment by MichalStrehovsky** [comment]
> > Running managed code in `DllMain` is not supported, doing so is expected to deadlock or crash.
> 
> Do I close this issue then?

Yes, we can close. See https://github.com/dotnet/runtime/issues/96345#issuecomment-1871262288.

**Comment by whindsaks** [comment]
DllMain is execute while the loader lock is held. You should not call any functions outside kernel32 and even then, only things like InitializeCriticalSection are guaranteed to be safe.
