### ISSUE TITLE
HttpHeaders.Add() incorrectly rejects empty Content-Type

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#1095]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders.add?view=netcore-3.1

Per https://github.com/whatwg/fetch/issues/332, it is valid for a HTTP header to have empty value.  This is causing a breaking behavior for users of PowerShell webcmdlets moving from 5.1 to 7 (https://github.com/PowerShell/PowerShell/issues/11396)

**Comment by scalablecory** [comment]
In a general sense, yes, headers can have an empty value. However, the [Content-Type header specifically](https://tools.ietf.org/html/rfc2616#section-14.17) must have a valid media-type value.

`HttpHeaders.Add` performs validation for known headers such as Content-Type. You can instead use `TryAddWithoutValidation` to bypass this, but I wouldn't recommend it -- servers may correctly reject such an invalid header/request.

**Comment by scalablecory** [comment]
> This is causing a breaking behavior for users of PowerShell webcmdlets moving from 5.1 to 7

.NET Framework should match the current .NET Core behavior of rejecting an empty Content-Type on `Add`. If you've found differently, can you please provide a repro in C# that demonstrates this? Thanks.

**Comment by karelz** [comment]
No repro for 1 month, closing.
If there is a mininal repro demonstrating a difference in behavior between .NET Framework and .NET Core, please post it and we can reopen. Thanks!
