### ISSUE TITLE
Contract-based polymorphic support only sometimes works, depending on casting

### ISSUE THREAD

**Issue by richard-devyce** [dotnet/runtime#109502]
### Description

I found a pretty nasty surprise waiting for anyone who's trying to set up contract-based polymorphism so that they can get polymorphic (de)serialization working for types that they don't own. I've reproduced the issue with the example out of the docs at https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-8-0.

It turns out that the serialiser will either emit the descriminator property or not depending on the _compile-time_ type of the object being passed in, not the runtime type. Since the `Serialize` method is generic I assume that it's looking up the type information based on `typeof(T)` instead of `obj.GetType()`.

### Reproduction Steps

The following setup code is copied verbatim from the docs at https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-8-0.

```
public class BasePoint
    {
        public int X { get; set; }
        public int Y { get; set; }
    }

    public class ThreeDimensionalPoint : BasePoint
    {
        public int Z { get; set; }
    }

    public sealed class FourDimensionalPoint : ThreeDimensionalPoint
    {
        public int W { get; set; }
    }

    public class PolymorphicTypeResolver : DefaultJsonTypeInfoResolver
    {
        public override JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options)
        {
            JsonTypeInfo jsonTypeInfo = base.GetTypeInfo(type, options);

            Type basePointType = typeof(BasePoint);
            if (jsonTypeInfo.Type == basePointType)
            {
                jsonTypeInfo.PolymorphismOptions = new JsonPolymorphismOptions
                {
                    TypeDiscriminatorPropertyName = "$point-type",
                    IgnoreUnrecognizedTypeDiscriminators = true,
                    UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization,
                    DerivedTypes =
                {
                    new JsonDerivedType(typeof(ThreeDimensionalPoint), "3d"),
                    new JsonDerivedType(typeof(FourDimensionalPoint), "4d")
                }
                };
            }

            return jsonTypeInfo;
        }
    }
```

Write a small console app with the following that instantiates one of the child types and tries to serialise it:

```
var options = new JsonSerializerOptions
{
    WriteIndented = true,
    TypeInfoResolver = new PolymorphicTypeResolver()
};

var point = new ThreeDimensionalPoint();

var json = JsonSerializer.Serialize(point, options);

Console.WriteLine($"Generated json:\n{json}");
```

This *doesn't work* as expected; it prints:

```
Generated json:
{
  "Z": 0,
  "X": 0,
  "Y": 0
}
```

and you can see that the configured property `$point-type` is missing from the serialised object. However, if we modify the code slightly to upcast the serialised object:

```
// Note the base type of `point` here
BasePoint point = new ThreeDimensionalPoint();

var json = JsonSerializer.Serialize(point, options);

Console.WriteLine($"Generated json:\n{json}");
```

Then it works! The resulting json has the correct value for `$point-type`.

```
Generated json:
{
  "$point-type": "3d",
  "Z": 0,
  "X": 0,
  "Y": 0
}
```

### Expected behavior

For any given object I would expect that the same object, running in a the same application and with the same `JsonSerializerOptions` will always serialise to the same (or at least _equivalent_) json.

### Actual behavior

The same object will actually serialise differently depending on the type argument to the `JsonSerializer.Serialize` method. This is, as I said, a very nasty surprise and also a bug that can happen very easily.

I was also unable to remedy this; I tried setting `JsonPolymorphismOptions` for the child types as well as the parent type but the API rejected this with a runtime error explaining that you can't set `JsonPolymorphismOptions` for a type that does not itself have any children.

### Configuration

dotnet: 8.0
OS: Windows 11
Arch: x64
Not specific to any configuration, as far as I know

**Comment by eiriktsarpalis** [comment]
> It turns out that the serialiser will either emit the descriminator property or not depending on the _compile-time_ type of the object being passed in, not the runtime type. Since the `Serialize` method is generic I assume that it's looking up the type information based on `typeof(T)` instead of `obj.GetType()`.

System.Text.Json in general uses type-directed instead of object-directed serialization. This trait isn't specific to polymorphism but applies to any value passed to the `JsonSerializer` methods. It is intended as a protection against accidentally exposing information that might be present in a particular runtime type. For root-level values you can work around this behaviour by serializing them as `object` or passing in `obj.GetType()` as a seprate parameter.

> and you can see that the configured property $point-type is missing from the serialised object.

Polymorphism configuration is scoped to the contract of a particular type, and is not inherited either by its derived or base types. It's set up this way for simplicity: an inheritance-based model creates space for ambiguity when different ancestors (particularly in interfaces) introduce conflicting configuration and also because serializing the derived type without metadata is a common use case. 

As you've pointed out, the best workaround is to cast the value to the type containing the appropriate polymorphic contract.

**Comment by eiriktsarpalis** [comment]
Closing as answered.
