### ISSUE TITLE
Dispose error in System.Drawing.Brush

### ISSUE THREAD

**Issue by ScottProgrammer** [dotnet/runtime#109533]
### Description

Hi I believe I have found an error in the System.Drawing.Brush dispose code
I know you are not supposed to dispose system brushes but it has a check to stop it disposing a system brush that is incorrect

it has this 
 if (!(nativeBrush != IntPtr.Zero))
 {
     return;
 }

one too many !, it should be 
 if (nativeBrush != IntPtr.Zero)
OR
 if (!(nativeBrush == IntPtr.Zero))

my code had a using statement around a brush var that was set to Brushes.DimGray
eg var myBrush = Brushes.DimGray
using myBrush
{
    e.Graphics.DrawString("Test", this.Font,  myBrush, 10, 10);
}
after the using completes its NativeBrush property goes from a set handle to  NativeBrush = &H0000000000000000
and the Brushes.DimGray is no longer usable with out it throwing System.ArgumentException Message=Parameter is not valid. exceptions
  

### Reproduction Steps

var myBrush = Brushes.DimGray
using myBrush
{
    e.Graphics.DrawString("Test", this.Font,  myBrush, 10, 10);
}

// error after that if calling
e.Graphics.DrawString("Test", this.Font,  Brushes.DimGray, 10, 10);

### Expected behavior

the system brushes should not be disposed if dispose is called on them

### Actual behavior

system brushes are allowed to be disposed

### Other information

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.10.4

**Comment by huoyaoyuan** [comment]
Which version are you referring to? Both the latest version and earliest supported version don't have this problem in code:

https://github.com/dotnet/runtime/blob/4b4a745fc0152b887eec20da906b98a229973313/src/libraries/System.Drawing.Common/src/System/Drawing/Brush.cs#L34-L41

https://github.com/dotnet/winforms/blob/b10907a57d1f93d4e1b7676e9a0227ea38d821bf/src/System.Drawing.Common/src/System/Drawing/Brush.cs#L27-L29

**Comment by ScottProgrammer** [comment]
Hi huoyaoyuan
it is in .Net Framewrok 4.8. winforms
System.Drawing.dll runtime version v4.0.30319

**Comment by huoyaoyuan** [comment]
There isn't such code to prevent disposing a system brush, according to [Reference Source](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Brush.cs,a3871853f6b5fc92).

It's very hard to change the behavior in .NET Framework due to the compatibility requirements.

**Comment by ViktorHofer** [comment]
Please use the Developer Community portal to report .NET Framework specific bugs: https://developercommunity.visualstudio.com/dotnet.
