### ISSUE TITLE
CancellationToken.CanBeCanceled returns True for disposed CancellationTokenSource

### ISSUE THREAD

**Issue by epeshk** [dotnet/runtime#109639]
### Description

`CancellationToken.CanBeCanceled` property still returns `True` after disposing underlying `CancellationTokenSource` even though it can't be canceled because `CancellationTokenSource.Cancel()` will throw `ObjectDisposedException`

### Reproduction Steps

```csharp
var cts = new CancellationTokenSource();
var token = cts.Token;
cts.Dispose();
Console.WriteLine(token.CanBeCanceled); // True
cts.Cancel(); // ObjectDisposedException
```

### Expected behavior

`Console.WriteLine(token.CanBeCanceled)` prints `False`

### Actual behavior

`Console.WriteLine(token.CanBeCanceled)` prints `True`

### Regression?

no

### Other information

Currently, `CanBeCanceled` implemented as simple null check:
```csharp
public bool CanBeCanceled => _source != null;`
```

**Comment by epeshk** [comment]
But `token` is obtained before disposing and may be passed to other threads than thread which calls `Dispose`. Is this behavior by design?

**Comment by MihaZupan** [comment]
Sort-of, it's a lifetime management issue if the token is still being used when you call dispose.
Generally you can structure logic in such a way that you're sure the underlying operation either completed (and you can safely dispose the source), or the token has been canceled.

**Comment by stephentoub** [comment]
In addition to Miha's comments, by design both `IsCancellationRequested` and `CanBeCanceled` will never transition to `false` once they've returned `true`. The docs also state:
> If [CanBeCanceled](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.canbecanceled?view=net-8.0) returns false, it is guaranteed that the token will never transition into a canceled state, meaning that [IsCancellationRequested](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.iscancellationrequested?view=net-8.0) will never return true.

That would be violated if a token that was already `IsCancellationRequested`==`true` started having `CanBeCanceled`==`false`.
