### ISSUE TITLE
Environment.GetFolderPath(SpecialFolder.LocalApplicationData) returns empty path on certain macOS

### ISSUE THREAD

**Issue by nazar322** [dotnet/runtime#109614]
### Description

`Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)` returns an empty string on macOS 15.1 and macOS 13.2 instead of a correct path. It returns correct path when the app runs on macOS 14.4 and macOS 11.6.

### Reproduction Steps

`Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)`

### Expected behavior

Expected behavior is to return `/Users/<YOUR_USR_NAME>/.local/share` 

### Actual behavior

The function returns `""`

### Regression?

This information is not known

### Known Workarounds

Not known

**Comment by danmoseley** [comment]
@nazar322 is XDG_DATA_HOME set ?

https://github.com/dotnet/runtime/blob/e133fe4f5311c0397f8cc153bada693c48eb7a9f/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L124-L131

**Comment by danmoseley** [comment]
Oh, correction, this is macOS

https://github.com/dotnet/runtime/blob/e133fe4f5311c0397f8cc153bada693c48eb7a9f/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L102-L103

**Comment by nazar322** [comment]
Both `HOME` and `USER` environment variables are set.

However, I use an app that is built with [Electron.NET](https://github.com/ElectronNET/Electron.NET) which uses .NET 6. 
Recently it got merged with PR that makes it use .NET 8 instead. I will update my app to use updated version of Electron.NET and let you know if that fixes the problem.

If not I will make a demo app to reproduce the case.

**Comment by nazar322** [comment]
When updated the framework to use .NET 8, the problem dissapeared!
