### ISSUE TITLE
Publish Failure in .NET 9 RC 2 for Blazor Web App (.NET 8, Auto Render Mode) and Blazor WASM (.NET 8) with Localization

### ISSUE THREAD

**Issue by BharatRamH** [dotnet/runtime#109604]
### Description

Publishing a Blazor Web App (targeting .NET 8, with Auto Render mode) and a Blazor WASM app (targeting .NET 8), both utilizing the localization feature, fails in .NET 9 RC 2.

### Reproduction Steps

1. Create a Blazor Web App targeting .NET 8 with Auto Render mode.
2. Set up the dynamic localization feature.
3. Attempt to publish the app.

An error occurs during publishing with the message: "Can't find the original satellite assembly in the list of resolved files to publish for asset," as shown in the screenshot below.

![Image](https://github.com/user-attachments/assets/c7f15101-a2c3-45f1-838b-af66b2cd718c)

[Sample.zip](https://github.com/user-attachments/files/17655669/Sample.zip)

**Environment:**
.NET SDK version: 9.0.100-rc.2.24474.11

### Expected behavior

The application should publish successfully with all necessary localization files.

### Actual behavior

Publishing fails due to a missing satellite assembly file.

**Comment by maraf** [comment]
Findings: Workload in .NET 8 doesn't include satellites in `WasmAssembliesFinal`
https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/WasmApp.Common.targets#L486
vs
https://github.com/dotnet/runtime/blob/release/8.0/src/mono/wasm/build/WasmApp.targets#L505

**Comment by Hona** [comment]
We're getting this error building our .net 8 blazor wasm project using the .net 9 sdk

**Comment by williambuchanan2** [comment]
Anyone know of any workarounds for this? It's happening on our Azure Pipeline builds.

**Comment by maraf** [comment]
The workaround now is to use .NET 8 SDK, for example by pinning it in global.json `dotnet new globaljson --sdk-version 8.0.404`

**Comment by williambuchanan2** [comment]
> The workaround now is to use .NET 8 SDK, for example by pinning it in global.json `dotnet new globaljson --sdk-version 8.0.404`

Thanks for the info. This partly worked. It looks like the SDK is also not available now so had to install that as well.

**Comment by LoupaLoupa** [comment]
I am also having this issue on pipelines that builds AOT builds. What is the current official workaround in pipelines and what is ETA on fix to Azure pipelines please?

**Comment by maraf** [comment]
Fixed in https://github.com/dotnet/runtime/pull/109920. It will be released in the next servicing release.
