### ISSUE TITLE
[9.0][wasm] Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange fails: xpected the multithreading runtime pack to be available when running on CI

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#109626]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=861525
Build error leg or test failing: Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange

## Error Message

```json
{
  "ErrorMessage" : "Expected the multithreading runtime pack to be available when running on CI. IsRunningOnCI is true but IsWorkloadWithMultiThreadingForDefaultFramework is false",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/109563
- Queue: `browser-wasm linux Release WasmBuildTests`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=861525&view=logs&j=1fa93050-f528-55d3-a351-f8bf9ce5adbf&t=a9f1a437-3b59-5900-1137-ec6cae9a530c&l=136
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-109563-merge-907b3685bcb2414b9e/Workloads-NoWebcil-ST-Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests/1/console.e303272d.log?helixlogtype=result
- Output:
```
    Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange [FAIL]
      System.TypeInitializationException : The type initializer for 'Wasm.Build.Tests.BuildTestBase' threw an exception.
      ---- System.Exception : Expected the multithreading runtime pack to be available when running on CI. IsRunningOnCI is true but IsWorkloadWithMultiThreadingForDefaultFramework is false.
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(117,0): at Wasm.Build.Tests.BuildTestBase.ConfigWithAOTData(Boolean aot, String config, String extraArgs)
        /_/src/mono/wasm/Wasm.Build.Tests/NativeRebuildTests/FlagsChangeRebuildTest.cs(23,0): at Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.FlagsChangesForNativeRelinkingData(Boolean aot)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
        /_/src/mono/wasm/Wasm.Build.Tests/Common/BuildEnvironment.cs(109,0): at Wasm.Build.Tests.BuildEnvironment..ctor()
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(80,0): at Wasm.Build.Tests.BuildTestBase..cctor()
    Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange [FINISHED] Time: 0s
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=861525
**Error message validated:** `[Expected the multithreading runtime pack to be available when running on CI. IsRunningOnCI is true but IsWorkloadWithMultiThreadingForDefaultFramework is false`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 11/7/2024 11:08:44 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[869949](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869949)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.SatelliteLoadingTests.LoadSatelliteAssemblyFromReference](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869949&view=ms.vss-test-web.build-test-results-tab&runId=22664156&resultId=100123)|dotnet/runtime#109825|
|[869426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869426)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.Build_NoAOT_ShouldNotRelink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869426&view=ms.vss-test-web.build-test-results-tab&runId=22648324&resultId=100112)|dotnet/runtime#109523|
|[869423](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869423)|dotnet/runtime|[Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869423&view=ms.vss-test-web.build-test-results-tab&runId=22648208&resultId=100127)|dotnet/runtime#109298|
|[867737](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867737)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.SatelliteLoadingTests.LoadSatelliteAssemblyFromReference](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867737&view=ms.vss-test-web.build-test-results-tab&runId=22597656&resultId=100127)|dotnet/runtime#109723|
|[867708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867708)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net9.0\", expectedTFM: \"net9.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867708&view=ms.vss-test-web.build-test-results-tab&runId=22595918&resultId=100119)|dotnet/runtime#109297|
|[867695](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867695)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.SatelliteLoadingTests.LoadSatelliteAssemblyFromReference](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867695&view=ms.vss-test-web.build-test-results-tab&runId=22595852&resultId=100125)|dotnet/runtime#109308|
|[867435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867435)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests3.BugRegression_60479_WithRazorClassLib](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867435&view=ms.vss-test-web.build-test-results-tab&runId=22584568&resultId=100122)|dotnet/runtime#109723|
|[864120](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864120)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net9.0\", expectedTFM: \"net9.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864120&view=ms.vss-test-web.build-test-results-tab&runId=22575792&resultId=100115)|dotnet/runtime#109316|
|[866998](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866998)|dotnet/runtime|[Wasm.Build.Tests.HybridGlobalizationTests.AOT_HybridGlobalizationTests](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866998&view=ms.vss-test-web.build-test-results-tab&runId=22570236&resultId=100127)|dotnet/runtime#109709|
|[866991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866991)|dotnet/runtime|[Wasm.Build.Tests.HybridGlobalizationTests.AOT_HybridGlobalizationTests](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866991&view=ms.vss-test-web.build-test-results-tab&runId=22570178&resultId=100118)|dotnet/runtime#109708|
|[866682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866682)|dotnet/runtime|[Wasm.Build.Tests.ConfigSrcTests.ConfigSrcAbsolutePath](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866682&view=ms.vss-test-web.build-test-results-tab&runId=22559438&resultId=100128)||
|[866579](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866579)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net9.0\", expectedTFM: \"net9.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866579&view=ms.vss-test-web.build-test-results-tab&runId=22555706&resultId=100115)|dotnet/runtime#109306|
|[866030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866030)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.Build_NoAOT_ShouldNotRelink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866030&view=ms.vss-test-web.build-test-results-tab&runId=22535514&resultId=100117)|dotnet/runtime#109299|
|[860156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860156)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.Build_NoAOT_ShouldNotRelink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860156&view=ms.vss-test-web.build-test-results-tab&runId=22525718&resultId=100117)|dotnet/runtime#109510|
|[865644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865644)|dotnet/runtime|[Wasm.Build.Tests.WasmSIMDTests.Build_NoAOT_ShouldNotRelink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865644&view=ms.vss-test-web.build-test-results-tab&runId=22524838&resultId=100116)|dotnet/runtime#109305|
|[864887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864887)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.FailOnMissingLazyAssembly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864887&view=ms.vss-test-web.build-test-results-tab&runId=22508478&resultId=100122)|dotnet/runtime#109646|
|[864878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864878)|dotnet/runtime|[Wasm.Build.Tests.TestAppScenarios.SatelliteLoadingTests.LoadSatelliteAssemblyFromReference](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864878&view=ms.vss-test-web.build-test-results-tab&runId=22508014&resultId=100122)|dotnet/runtime#109298|
|[864879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864879)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net9.0\", expectedTFM: \"net9.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864879&view=ms.vss-test-web.build-test-results-tab&runId=22507964&resultId=100115)|dotnet/runtime#109523|
|[864731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864731)|dotnet/runtime|[Wasm.Build.Tests.WasmBuildAppTest.Bug49588_RegressionTest_AOT](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864731&view=ms.vss-test-web.build-test-results-tab&runId=22506028&resultId=100125)|dotnet/runtime#109299|
|[864719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864719)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.BlazorWasm_CannotAOT_InDebug(config: \"Debug\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864719&view=ms.vss-test-web.build-test-results-tab&runId=22505638&resultId=100126)|dotnet/runtime#109305|
|[864134](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864134)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net9.0\", expectedTFM: \"net9.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864134&view=ms.vss-test-web.build-test-results-tab&runId=22487326&resultId=100124)||
|[861525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=861525)|dotnet/runtime|[Wasm.Build.Tests.WasmRunOutOfAppBundleTests.RunOutOfAppBundle](https://dev.azure.com/dnceng-public/public/_build/results?buildId=861525&view=ms.vss-test-web.build-test-results-tab&runId=22413546&resultId=100126)|dotnet/runtime#109563|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|15|22|

**Comment by maraf** [comment]
The root cause seems to be `9.0.0` (actual version) vs `9.0.0-ci` (env var passed to WBT `RUNTIME_PACK_VER9=9.0.0-ci`)
