### ISSUE TITLE
R2RDump - List of bugs when running R2RDump on CoreFX binaries

### ISSUE THREAD

**Issue by acmyu** [dotnet/runtime#10961]
There's an IndexOutOfRangeException when dumping an ARM ReadyToRun System.Private.Corelib.
It happens in R2RDump.NibbleReader.ReadNibble() when decoding fixups.
It also happens in GcTransitions.cs where the slotId is greater than the number of untracked slots

**Comment by nattress** [comment]
We have since fixed up the GCInfo parsing in R2RDump
