### ISSUE TITLE
[BUG] JsonSerializer.Deserialize is not working with some camel case properties. Example: uMLDesign

### ISSUE THREAD

**Issue by nitish-kaushik** [dotnet/runtime#109663]
### JsonSerializer.Deserialize is not working with some camel case properties

As per Microsoft Copilot `uMLDesign` is a valid camel case property but the `JsonSerializer.Deserialize` is ignoring the property even if I set the `JsonSerializerOptions` to `PropertyNamingPolicy = JsonNamingPolicy.CamelCase`

Here is the screenshot from Microsoft copilot

![Image](https://github.com/user-attachments/assets/146addae-1bfb-48ed-a7da-22ae4a76d2cc)

Here is the C# console application code

```
using System.Text.Json;

string json = """{"hTTP":"I am HTTP","sCRUMFramework":"I am SCRUM","uMLDesign":"I am UML"}""";

var options = new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

var deserialize = JsonSerializer.Deserialize<Sample>(json, options);

class Sample
{
    public string HTTP { get; set; }
    public string SCRUMFramework { get; set; }
    public string UMLDesign { get; set; }
}
```

Output: All the proerties will be null;

### Note: This works fine If 
I set the `PropertyNameCaseInsensitive = true` in `JsonSerializerOptions`

```
var options = new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true };
```

Or pass the `JsonSerializerDefaults.Web` in the constructor of `JsonSerializerOptions`.
```
var options = new JsonSerializerOptions(JsonSerializerDefaults.Web) { PropertyNamingPolicy = JsonNamingPolicy.CamelCase};
```

Expected Solution: If this is a valid camel case then the `JsonSerializer` must convert this property.

**Comment by gregsdennis** [comment]
> As per Microsoft Copilot `uMLDesign` is a valid camel case property

I disagree. In code I've worked on and otherwise seen, acronyms are treated as words unto themselves.  I'd say that the proper casing for this is `umlDesign`.

**Comment by huoyaoyuan** [comment]
There are multiple different rules to map consecutive upper-case letters to camel case. System.Text.Json doesn't deserialize from "a valid" camel case, but only the camel case representation from its algorithm. In this case, the mapped property names are `http`, `scrumFramework` and `umlDesign`.

**Comment by martincostello** [comment]
The class you include in your sample isn't "usual" idiomatic C# naming from my experience. This is what I'd expect to see in an app:

```csharp

class Sample
{
    public string Http { get; set; }
    public string ScrumFramework { get; set; }
    public string UmlDesign { get; set; }
}
```

That would then yield camel case naming as given in the previous replies in a "more obvious" way (i.e. acronyms are treated as words).

You can find various usage of such casing for property names (e.g. `HttpClient`).

**Comment by eiriktsarpalis** [comment]
Closing as by-design. Even if we wanted to change this doing so would be a substantial breaking change.

**Comment by nitish-kaushik** [comment]
Thanks everyone replying on this issue.

I know this is not a regular practice to use this type of names (I mentioned this in title some camel case props). But I got this JSON as a response from one external API in one of my recent projects. And thats why I asked Microsoft Copilot (Screenshot attached) to make sure if this is valid came case or not. Though it is not a valid camel case as per ChatGPT.

I am not asking about a workround for this issue. I have already added the solution to quetion itself.

**All I wanted to say is: If this is a valid camel case (As per Microsoft Copilot) so it should be handeled by JsonSerializer.**

**Comment by huoyaoyuan** [comment]
> If this is a valid camel case (As per Microsoft Copilot) so it should be handeled by JsonSerializer.

The serializer doesn't handle **a** valid camel case. It only handles **the** camel case mapping decided by its algorithm. In other words, it has a strict 1:1 mapping for the name it accepts.
