### ISSUE TITLE
TaskCompletionSource performance

### ISSUE THREAD

**Issue by szmcdull** [dotnet/runtime#109662]
### Description

TaskCompletionSource has more than 0.5 ms latency to signal its Task's completion. Considering it is a fundamental construct, such latency is much larger than what i expect. Am I doing something wrong? Is there any better approach to signal another coroutine to run as soon as possible?

### Configuration

```C#
        async Task<DateTimeOffset> Complete(TaskCompletionSource<int> tcs)
        {
            var now = DateTimeOffset.Now;
            tcs.SetResult(111);
            await Task.Delay(1000); // make the current Task yeild
            return now;
        }

        [Test]
        public async Task TestTaskCompletionSource()
        {
            var tcs = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
            var task = Complete(tcs);
            await tcs.Task;
            var end = DateTimeOffset.Now;
            var start = await task;
            Console.WriteLine($"{(end-start).TotalMilliseconds}ms {start:HH:mm:ss.fffffff} {end:HH:mm:ss.fffffff}");
        }
```

```
  Standard Output: 
    0.7022ms 12:22:16.3287856 12:22:16.3294878
```

### Regression?

N/A

### Data

N/A

### Analysis

N/A

**Comment by szmcdull** [comment]
For comparison, I did a similar benchmark in Go+linux, using a chan to signal another coroutine, the latency is less than 0.001 ms (about hundreds of nanoseconds)

**Comment by szmcdull** [comment]
PS, the time resolution in Windows is not good enough to benchmark the Go test

**Comment by huoyaoyuan** [comment]
First of all, it's incorrect to use `DateTimeOffset.Now` to do any performance related measurement, because the overhead itself is unignorable. Replacing with `Stopwatch.GetElapsedTime(0)` reduces the printed delay from 5ms to 2ms on my machine, and it's not stable.

The measurement is also incorrect at all. There's no `await` of incomplete task between the two timestamps, thus it's almost certainly incorrect to see a number of this order of magnitude. It's not the correct way to use a single main method to measure any performance, because it would be measuring startup overhead instead of the target code. See more at https://github.com/dotnet/performance/tree/main/docs and https://benchmarkdotnet.org/ .

With a proper benchmark like this:

```csharp
        [Benchmark]
        public void TestTaskCompletionSourceWait() => TestTaskCompletionSource().Wait();

        async Task Complete(TaskCompletionSource<int> tcs)
        {
            tcs.SetResult(111);
            await Task.Delay(1000); // make the current Task yeild
        }

        public async Task TestTaskCompletionSource()
        {
            var tcs = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
            var task = Complete(tcs);
            await tcs.Task;
        }
```

The result on my machine is:

| Method                       | Mean     | Error    | StdDev   |
|----------------------------- |---------:|---------:|---------:|
| TestTaskCompletionSourceWait | 604.3 ns | 26.55 ns | 77.88 ns |

The order of magnitude is **0.5μs** instead of **0.5ms**.

**Comment by huoyaoyuan** [comment]
> For comparison, I did a similar benchmark in Go+linux, using a chan to signal another coroutine, the latency is less than 0.001 ms (about hundreds of nanoseconds)

Go is AOT compiled and there's no startup overhead of JIT. It's a significant win in single-main measurement. It should only be comparable with NativeAOT publishing.

**Comment by hez2010** [comment]
`Task.Delay` has additional overhead where it needs to setup the timer and tick events.
If you want to make sure it yields you can use `Task.Yield`.

Also as stated above you need to use `BenchmarkDotNet` to measure performance correctly, `DateTime.Now` is not accurate. Besides, .NET has tiered compilation and it only promotes hot path to optimized code, the performance needs to be measured after code being promoted to tier-1 (which will be done automatically if you use `BenchmarkDotNet`).

Here is the benchmark code and the result:

```cs
BenchmarkRunner.Run<Benchmarks>();

public class Benchmarks
{
    async Task Complete(TaskCompletionSource<int> tcs)
    {
        tcs.SetResult(111);
        await Task.Yield();
    }
    
    [Benchmark]
    public async Task TestTaskCompletionSource()
    {
        var tcs = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
        var task = Complete(tcs);
        await tcs.Task;
    }
}
```

Result:

| Method                   | Mean     | Error   | StdDev  |
|------------------------- |---------:|--------:|--------:|
| TestTaskCompletionSource | 180.4 ns | 3.51 ns | 6.34 ns |

As you can see the real cost is `180.4ns` (`0.0001804ms`) instead of `0.7022ms`.

**Comment by szmcdull** [comment]
It is first I observed the 0.5ms delay in production environment, then I did the test. 

The measurement is right although the resolution is bad due to DateTimeOffset.Now. What I'm measuring is the time between SetResult and the orignal Task to be signaled, not the whole test. And I'm using NUnit, not a Main()

**Comment by huoyaoyuan** [comment]
> It is first I observed the 0.5ms delay in production environment, then I did the test.

Latency can be affected by many different factors, from GC to OS thread scheduling. If the task itself has such latency, it would accumulate a lot and result in much larger number observed.

> What I'm measuring is the time between SetResult and the orignal Task to be signaled, not the whole test.

The two timeatamps are in different methods, so JIT overhead would certainly be included.

> And I'm using NUnit, not a Main()

This will only make things worse. Test framework are not for benchmarking. It may do more things unfriendly.

**Comment by huoyaoyuan** [comment]
Just naively run your original unmodified code 100 times:

```csharp
for (int i = 0; i < 100; i++)
{
    await TestTaskCompletionSource();
}
```

The result on my machine is:

```
15.795ms 16:03:16.8141331 16:03:16.8299281
0.0181ms 16:03:17.8504499 16:03:17.8504680
0.0095ms 16:03:18.8486361 16:03:18.8486456
0.0143ms 16:03:19.8605601 16:03:19.8605744
0.0101ms 16:03:20.8748421 16:03:20.8748522
0.0108ms 16:03:21.8830407 16:03:21.8830515
0.0099ms 16:03:22.8940402 16:03:22.8940501
0.0107ms 16:03:23.9055501 16:03:23.9055608
0.0124ms 16:03:24.9194132 16:03:24.9194256
0.0264ms 16:03:25.9334373 16:03:25.9334637
0.0092ms 16:03:26.9390281 16:03:26.9390373
0.0111ms 16:03:27.9478979 16:03:27.9479090
0.0132ms 16:03:28.9555213 16:03:28.9555345
0.0112ms 16:03:29.9725505 16:03:29.9725617
0.0117ms 16:03:30.9842986 16:03:30.9843103
0.0477ms 16:03:31.9873919 16:03:31.9874396
0.0107ms 16:03:32.9958658 16:03:32.9958765
0.0102ms 16:03:33.9977647 16:03:33.9977749
0.0101ms 16:03:35.0053752 16:03:35.0053853
0.0116ms 16:03:36.0191123 16:03:36.0191239
0.0132ms 16:03:37.0430129 16:03:37.0430261
0.0096ms 16:03:38.0386715 16:03:38.0386811
0.0092ms 16:03:39.0480710 16:03:39.0480802
0.0112ms 16:03:40.0621098 16:03:40.0621210
0.0113ms 16:03:41.0763765 16:03:41.0763878
0.0175ms 16:03:42.0842215 16:03:42.0842390
0.0106ms 16:03:43.0965985 16:03:43.0966091
0.0105ms 16:03:44.1124816 16:03:44.1124921
0.0203ms 16:03:45.1226578 16:03:45.1226781
0.0094ms 16:03:46.1233771 16:03:46.1233865
0.0885ms 16:03:47.1318263 16:03:47.1319148
0.0066ms 16:03:48.1439872 16:03:48.1439938
0.0079ms 16:03:49.1476174 16:03:49.1476253
0.0069ms 16:03:50.1562746 16:03:50.1562815
0.0057ms 16:03:51.1681070 16:03:51.1681127
0.0046ms 16:03:52.1756334 16:03:52.1756380
0.0064ms 16:03:53.1869544 16:03:53.1869608
0.0062ms 16:03:54.1960460 16:03:54.1960522
0.0086ms 16:03:55.2133404 16:03:55.2133490
0.0124ms 16:03:56.2206682 16:03:56.2206806
0.0067ms 16:03:57.2231006 16:03:57.2231073
0.0051ms 16:03:58.2361959 16:03:58.2362010
0.0086ms 16:03:59.2504207 16:03:59.2504293
0.0205ms 16:04:00.2629291 16:04:00.2629496
0.0062ms 16:04:01.2673264 16:04:01.2673326
0.0058ms 16:04:02.2805020 16:04:02.2805078
0.0072ms 16:04:03.2929606 16:04:03.2929678
0.0041ms 16:04:04.3036834 16:04:04.3036875
0.0106ms 16:04:05.3100633 16:04:05.3100739
0.0051ms 16:04:06.3180398 16:04:06.3180449
0.0051ms 16:04:07.3204817 16:04:07.3204868
0.0049ms 16:04:08.3302506 16:04:08.3302555
0.014ms 16:04:09.3455669 16:04:09.3455809
0.0055ms 16:04:10.3460122 16:04:10.3460177
0.0061ms 16:04:11.3607683 16:04:11.3607744
0.0167ms 16:04:12.3625584 16:04:12.3625751
0.0049ms 16:04:13.3785810 16:04:13.3785859
0.0081ms 16:04:14.3935624 16:04:14.3935705
0.0091ms 16:04:15.3976586 16:04:15.3976677
0.006ms 16:04:16.4013083 16:04:16.4013143
0.0098ms 16:04:17.4062561 16:04:17.4062659
0.0138ms 16:04:18.4221887 16:04:18.4222025
0.0035ms 16:04:19.4316339 16:04:19.4316374
0.007ms 16:04:20.4679500 16:04:20.4679570
0.0025ms 16:04:21.4738414 16:04:21.4738439
0.0074ms 16:04:22.5183866 16:04:22.5183940
0.0026ms 16:04:23.5322816 16:04:23.5322842
0.0191ms 16:04:24.5413324 16:04:24.5413515
0.0091ms 16:04:25.5475234 16:04:25.5475325
0.0033ms 16:04:26.5553888 16:04:26.5553921
0.0088ms 16:04:27.5646144 16:04:27.5646232
0.004ms 16:04:28.5683183 16:04:28.5683223
0.0033ms 16:04:29.5699813 16:04:29.5699846
0.0029ms 16:04:30.5787864 16:04:30.5787893
0.0069ms 16:04:31.5908057 16:04:31.5908126
0.0066ms 16:04:32.6015074 16:04:32.6015140
0.0211ms 16:04:33.6152554 16:04:33.6152765
0.0041ms 16:04:34.6278540 16:04:34.6278581
0.0033ms 16:04:35.6425867 16:04:35.6425900
0.0037ms 16:04:36.6567094 16:04:36.6567131
0.0269ms 16:04:37.6602886 16:04:37.6603155
0.0498ms 16:04:38.6928598 16:04:38.6929096
0.0046ms 16:04:39.6980724 16:04:39.6980770
0.004ms 16:04:40.7138288 16:04:40.7138328
0.0045ms 16:04:41.7171183 16:04:41.7171228
0.0063ms 16:04:42.7309909 16:04:42.7309972
0.0034ms 16:04:43.7434986 16:04:43.7435020
0.007ms 16:04:44.7596009 16:04:44.7596079
0.004ms 16:04:45.7715894 16:04:45.7715934
0.0032ms 16:04:46.7876658 16:04:46.7876690
0.0066ms 16:04:47.8036687 16:04:47.8036753
0.004ms 16:04:48.8161747 16:04:48.8161787
0.0035ms 16:04:49.8281260 16:04:49.8281295
0.0098ms 16:04:50.8381855 16:04:50.8381953
0.0266ms 16:04:51.8478230 16:04:51.8478496
0.005ms 16:04:52.8571433 16:04:52.8571483
0.012ms 16:04:53.8724142 16:04:53.8724262
0.0041ms 16:04:54.8852702 16:04:54.8852743
0.0415ms 16:04:55.9034322 16:04:55.9034737
0.0038ms 16:04:56.9165850 16:04:56.9165888
```

The time of first invocation is **over 1000 times larger** than subsequent ones. That's why your number is not a thing at all.
