### ISSUE TITLE
Document profiling.md missmatch with code

### ISSUE THREAD

**Issue by loadingcn** [dotnet/runtime#109722]
Cor_Enable_Profiling - only connect with a profiler if this environment variable exists and is set to a non-zero value.
Cor_Profiler - connect with the profiler with this CLSID or ProgID (which must have been stored previously in the Registry). The Cor_Profiler environment variable is defined as a string:
set Cor_Profiler={32E2F4DA-1BEA-47ea-88F9-C5DAF691C94A}, or
set Cor_Profiler="MyProfiler"

These env vars have already been prefixed with CORECLR_:

RETAIL_CONFIG_DWORD_INFO_EX(EXTERNAL_CORECLR_ENABLE_PROFILING, W("CORECLR_ENABLE_PROFILING"), 0, "CoreCLR only: Flag to indicate whether profiling should be enabled for the currently running process.", CLRConfig::LookupOptions::DontPrependPrefix)
RETAIL_CONFIG_STRING_INFO_EX(EXTERNAL_CORECLR_PROFILER, W("CORECLR_PROFILER"), "CoreCLR only: Specifies GUID of profiler to load into currently running process", CLRConfig::LookupOptions::DontPrependPrefix)
RETAIL_CONFIG_STRING_INFO_EX(EXTERNAL_CORECLR_PROFILER_PATH, W("CORECLR_PROFILER_PATH"), "CoreCLR only: Specifies the path to the DLL of profiler to load into currently running process", CLRConfig::LookupOptions::DontPrependPrefix)

Please change them.

**Comment by tommcdon** [comment]
Hi @loadingcn, thanks for reporting the doc issues in the book of the runtime!  Our public docs on https://learn.microsoft.com/en-us/dotnet/core/runtime-config/debugging-profiling seem to be up to date, so I will push this issue to "Future".  Please feel free to send us a PR!

**Comment by loadingcn** [comment]
I see this doc https://learn.microsoft.com/en-us/dotnet/core/runtime-config/debugging-profiling . 
As profiling.md is conspicuous in google search result, I think profiling.md is still an important reference for developers. 
I'll send a PR in a few days.
