### ISSUE TITLE
.NET 9 can not be installed on older macOS

### ISSUE THREAD

**Issue by jledgett** [dotnet/runtime#109750]
I have a iMac 27" that can only support macOS 10.15.7.   It supported .NET 8 perfectly fine.

However today, while trying to install the .NET 9 SDK I receive an error stating that I need macOS 12 or later.   I would ask you to reconsider this decision.

**Comment by marcpopMSFT** [comment]
@richlander for visibility. Here's our release notes support page for reference: https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.md#apple

**Comment by huoyaoyuan** [comment]
The min supported OS version for Apple platforms are bumped in a consistent pace. .NET 7-8 requires 10.15 and .NBT 5-6 requires 10.13, bumping 2 versions for every 2 years.

**Comment by NikolaMilosavljevic** [comment]
[Triage] This is not in our support matrix: https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.md#apple

Closing.
