### ISSUE TITLE
`StringValues`' implementation of `object.Equals(object?)` breaks symmetricity invariant

### ISSUE THREAD

**Issue by YoshiRulz** [dotnet/runtime#109767]
### Description

https://github.com/dotnet/runtime/blob/990ebf52fc408ca45929fd176d2740675a67fab8/src/libraries/Microsoft.Extensions.Primitives/src/StringValues.cs#L707-L730
> The following statements must be true for all implementations of the [Equals(Object)](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals#system-object-equals(system-object)) method.
> [...]
> `x.Equals(y)` returns the same value as `y.Equals(x)` [i.e. symmetricity].

—[`object.Equals`: Notes for inheritors](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-object-equals#notes-for-inheritors)

### Reproduction Steps

```csharp
using Microsoft.Extensions.Primitives;
Console.WriteLine(new StringValues("abc").Equals((object) "abc"));
Console.WriteLine("abc".Equals((object) new StringValues("abc")));
```

### Expected behavior

```
False
False
```

### Actual behavior

```
True
False
```

### Configuration

SDK 8.0.300 / Runtime 8.0.5 from Nixpkgs

### Other information

edit: Oops, used the wrong term there. I should add that I found this after noticing that `StringValues` implemented `IEquatable<T>` multiple times (see also [dotnet/csharplang#2652](https://github.com/dotnet/csharplang/issues/2652))—there may be more such types in the BCL.

**Comment by tarekgh** [comment]
> .Equals(y) returns the same value as y.Equals(x) [i.e. symmetricity].

We cannot guarantee this, nor can we modify the behavior of `StringValues.Equals` to maintain application compatibility. It is important for users to use `StringValues.Equals` consistently when comparing `StringValues` objects.
