### ISSUE TITLE
.NET to COM/ActiveX - params/ParamArray not supported for VB98/VB6 and earlier

### ISSUE THREAD

**Issue by NETSphereSoft** [dotnet/runtime#109751]
### Describe the bug
We want to provide a .NET Framework library for VB98/VB6 developers and take advantage of `ParamArray` usage.

The standard translation from .NET `params`

```cs
[Description("Add item(s)")]
void Add(String item, params Object[] moreItems)
```
to IDL/TLB by [TlbExp.exe](https://learn.microsoft.com/en-us/dotnet/framework/tools/tlbexp-exe-type-library-exporter) is
```c
[id(0x1), vararg, helpstring("Add item(s)")]
void Add([in] BSTR item, [in] SAFEARRAY(VARIANT) moreItems)
```
Which is seen in VB98/VB6 object catalog as
```vb
Sub Add(item As String, ParamArray moreItems() As Variant)
```

But this COM/ActiveX method signature is accessible with `MSScriptControl.ScriptControl` only, not with VB98/VB6. The compiler notices an error of incompatibility:

![Image](https://github.com/user-attachments/assets/d6b78c31-adf4-485d-b935-742181a5a200)

For VB98/VB6 the following IDL/TLB method signature is required (reference of `SAFEARRAY`):

```c
[id(0x1), vararg, helpstring("Add item(s)")]
void Add([in] BSTR item, [in] SAFEARRAY(VARIANT)* moreItems)
  
```
Our current workaround is to change the method signature in .NET:
```cs
[Description("Add item(s)")]
void Add(String item, [In] ref Object[] moreItems)
```
which get generated in IDL/TLB with no `vararg`, but `SAFEARRAY` reference:
```c
[id(0x1), helpstring("Add item(s)")]
void Add([in] BSTR item, [in] SAFEARRAY(VARIANT)* moreItems)
```
Then we need manually to do the following process:

*   Open the exported TLB in [oleview.exe](https://learn.microsoft.com/en-us/windows/win32/com/ole-com-object-viewer)
*   Save the IDL
*   Change the attributation by adding the `vararg`
*   Compile the IDL with [midl.exe](https://learn.microsoft.com/en-us/windows/win32/com/midl-compiler)

You can see this in the sample project:

- `TypeLibParamArrayVB6.IDL` line [59](https://github.com/NETSphereSoft/Bug-Samples/blob/master/dotnet/sdk/44460-TypeLib-ParamArray-VB6/TypeLibParamArrayVB6/TypeLibParamArrayVB6.IDL#L59) and
- `TypeLibParamArrayVB6.VB98.IDL` line [59](https://github.com/NETSphereSoft/Bug-Samples/blob/master/dotnet/sdk/44460-TypeLib-ParamArray-VB6/TypeLibParamArrayVB6/TypeLibParamArrayVB6.VB98.IDL#L59)

### To Reproduce

- Compile the project from [NETSphereSoft/Bug-Samples/dotnet/sdk/44460-TypeLib-ParamArray-VB6](https://github.com/NETSphereSoft/Bug-Samples/tree/master/dotnet/sdk/44460-TypeLib-ParamArray-VB6/TypeLibParamArrayVB6)
- You might to change paths in the post build events
- Create a VB98/VB6 project, add the type library (*.tlb) and use the `Add`  method of `Class1` in your project
- Try to compile
- Now take the provided `TypeLibParamArrayVB6.VB98.IDL` (can be build with `TypeLibParamArrayVB6.VB98.bat`)
- Rename the type library `TypeLibParamArrayVB6.VB98.tlb` to `TypeLibParamArrayVB6.tlb` and place it to your `TypeLibParamArrayVB6.dll`
- Use this changed type library now in you VB98/VB6 references
- Use the `AddVB98`  method of `Class1` in your project now
- Try to compile => should not lead in an error
- You should be able to use it in the following ways:  
  `Call class1.AddVB98("Test 1")`  
  `Call class1.AddVB98("Test 1", "Test 2")`  
  `Call class1.AddVB98("Test 1", "Test 2", "Test 3")`  

### Possible solution

Add a `ParamArrayRef` attribute for placing at the parameter or method additionally to the standard `params` usage

```cs
[Description("Add item(s)")]
void Add(String item, [ParamArrayRef] params Object[] moreItems)
```
or
```cs
[Description("Add item(s)")]
[ParamArrayRef]
void Add(String item, params Object[] moreItems)  
```

And export then the IDL/TLB by `TlbExp.exe` with the requested method signature:

```c
[id(0x1), vararg, helpstring("Add item(s)")]
void Add([in] BSTR item, [in] SAFEARRAY(VARIANT)* moreItems)
```

Alternately a solution with existing `InAttribute` and `OutAttribute`  could be to get the same method signature like VB98/VB6 does:

```cs
[Description("Add item(s)")]
void Add(String item, [In, Out] params Object[] moreItems)
```
to lead into
```c
[id(0x1), vararg, helpstring("Add item(s)")]
void Add([in] BSTR item, [in, out] SAFEARRAY(VARIANT)* moreItems)
```

And a much simplier could be (currently prevented from compiler):

```cs
[Description("Add item(s)")]
void Add(String item, [ParamArray] ref Object[] moreItems)
```
to lead into
```c
[id(0x1), vararg, helpstring("Add item(s)")]
void Add([in] BSTR item, [in, out] SAFEARRAY(VARIANT)* moreItems)
```

### Further technical details
Microsoft Visual Studio Professional 2019
Version 16.11.37
VisualStudio.16.Release/16.11.37+34931.43
Microsoft .NET Framework
Version 4.8.09037

**Comment by AaronRobinsonMSFT** [comment]
> We want to provide a .NET Framework library for VB98/VB6 developers and take advantage of ParamArray usage.
> to IDL/TLB by [TlbExp.exe](https://learn.microsoft.com/en-us/dotnet/framework/tools/tlbexp-exe-type-library-exporter) is

@NETSphereSoft This is a .NET Framework specific query. .NET Core doesn't support `TlbExp.exe` and adding new feature support for VB98/VB6 is a non starter here. As mentioned in https://github.com/dotnet/runtime/issues/109751#issuecomment-2471657354, any .NET Framework specific issues should go through [Developer Community](https://developercommunity.visualstudio.com/home).

Significant business justification will be needed and suggest adding that when supporting the issue.
