### ISSUE TITLE
JsonPolymorphic with JsonDerivedType cannot be serialized / deserialized with System.Text.Json

### ISSUE THREAD

**Issue by sandrohanea** [dotnet/runtime#109755]
### Description

When using [JsonDerivedType] with [JsonPolymorphic] attribute and also mapping the Type discriminator property to a real property, we cannot deserialize a string produced by the derived type serialized.

### Reproduction Steps

1. Create a new console app and paste the following code:
```
using System.Text.Json;
using System.Text.Json.Serialization;

var classA = new ClassA
{
    Id = "Class A ID",
    Type = "a"
};

var jsonValueFromObject = JsonSerializer.Serialize<object>(classA);
var jsonValueFromClassA = JsonSerializer.Serialize(classA);

Console.WriteLine($"Serialized from object: {jsonValueFromObject}");
Console.WriteLine($"Serialized from ClassA: {jsonValueFromClassA}");

try
{
    var deserializedValue1 = JsonSerializer.Deserialize<BaseClass>(jsonValueFromObject);
}
catch (Exception ex)
{
    Console.WriteLine("Deserialization failed from Object");
    Console.WriteLine(ex.Message);
}

try
{
    var deserializedValue2 = JsonSerializer.Deserialize<BaseClass>(jsonValueFromClassA);
}
catch(Exception ex)
{
    Console.WriteLine("Deserialization failed from A");
    Console.WriteLine(ex.Message);
}


public class ClassA : BaseClass
{
    [JsonPropertyName("id")]
    public required string Id { get; set; }
}

public class ClassB : BaseClass
{
    [JsonPropertyName("name")]
    public required string Name { get; set; }
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ClassA), "a")]
[JsonDerivedType(typeof(ClassB), "b")]
public class BaseClass
{
    [JsonPropertyName("type")]
    public required string Type { get; set; }
}
```
2. Executed it

### Expected behavior

I would expect that we can deserialize the string and be able to produce the same JSON value for both `jsonValueFromObject` and `jsonValueFromClassA` but the serialized from object is actually duplicating the `type` property. 

The expected serialized value for both `jsonValueFromObject` and `jsonValueFromClassA` is:

```
{"type":"a", "id":"Class A ID"}
```

But neither of the options is writing that.
Also, it would be expected that both `deserializedValue1` and `deserializedValue2` will have an instance of `ClassA`

### Actual behavior

The output of the following code is:

```
Serialized from object: {"type":"a","id":"Class A ID","type":"a"}
Serialized from ClassA: {"id":"Class A ID","type":"a"}
Deserialization failed from Object
The metadata property is either not supported by the type or is not the first property in the deserialized JSON object. Path: $.type | LineNumber: 0 | BytePositionInLine: 37.
Deserialization failed from A
The metadata property is either not supported by the type or is not the first property in the deserialized JSON object. Path: $.type | LineNumber: 0 | BytePositionInLine: 26.
```

As it can be observed:
 - the first option `JsonSerializer.Serialize<object>(classA)` will produce 2 properties `type` in the output json.
 - the second option `JsonSerializer.Serialize(classA)` will add the `type` property at the end, not at the begging of the ouput json.
 - None of them can be deserialized

Note, if using `JsonSerializer.Serialize<BaseClass>(classA)`, the behavior will be similar with `JsonSerializer.Serialize<object>(classA)`

### Regression?

No

### Known Workarounds

Partial-workaround:
If removing the property mapped in the BaseClass and just living it:

```
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ClassA), "a")]
[JsonDerivedType(typeof(ClassB), "b")]
public class BaseClass
{
}
```

`JsonSerializer.Serialize<BaseClass>(classA)` and `JsonSerializer.Serialize<object>(classA)` will produce the expected json output:
```
{"type":"a","id":"Class A ID"}
```
That can be deserialized back to an instance of ClassA.

However, `JsonSerializer.Serialize(classA)` will only produce a json value with one id property:
```
{"id":"Class A ID"}
```

That one, ofc, cannot be deserialized back to Class A as the type of discriminator is missing.

### Configuration

dotnet version:

8.0.X
9.0.100-rc.2.24474.11

OS: Any OS
Arch: Any Arch
Should't be specific to a configuration, looks like problem with JsonPolymorphic attribute + property with the same name mapped in the model.

**Comment by eiriktsarpalis** [comment]
> I would expect that we can deserialize the string and be able to produce the same JSON value for both jsonValueFromObject and jsonValueFromClassA but the serialized from object is actually duplicating the type property.

> The expected serialized value for both jsonValueFromObject and jsonValueFromClassA is:

This is not the case. In general, STJ follows a type directed serialization approach meaning that the output of a value _can_ differ depending on what type is being used to derive the contract. In your case, serializing `classA` will end up using the contract for `classA.GetType()` which does not specify polymorphism. 

Explicitly specifying `BaseClass` in the angle brackets will result in the serializer adopting the polymorphic configuration specified for `BaseClass`. Assuming you don't know the desired type at compile time, you can also pass it in as a `Type` parameter like so:

```C#
Type baseClass = typeof(BaseClass);
string json = JsonSerializer.Serialize(classA, baseClass);
classA = JsonSerializer.Deserialize(json, baseClass);
Console.WriteLine(classA is BaseClass); // True
```

Hope this helps.

**Comment by sandrohanea** [comment]
Hello @eiriktsarpalis ,
Thanks for the quick response.
I understand now why the STJ won't be serializing ClassA with its polymorphic values when serializing it with its type.

However above, the code:
```
Type baseClass = typeof(BaseClass);
string json = JsonSerializer.Serialize(classA, baseClass);
classA = JsonSerializer.Deserialize(json, baseClass);
Console.WriteLine(classA is BaseClass); // True
```

Is still failing and reproducing the issue of creating 2 `type` properties in the JSON output:
`{"type":"a","id":"Class A ID","type":"a"}`

Is that expected as well, and we shouldn't map the discriminator property to a property in the model?

**Comment by eiriktsarpalis** [comment]
> Is still failing and reproducing the issue of creating 2 type properties in the JSON output:

Ah I missed that detail. Again, this is by design primarily because the type discriminator is a type-level mapping and not an object-level mapping. As such, runtime values of properties do not interact with the polymorphism feature. That being said, the fact that two properties are being emitted is a problem. I believe we have an open issue somewhere about detecting conflicts of property names with discriminators and throwing an error.
