### ISSUE TITLE
JIT: libraries jitstress Assertion failed 'doesVNMatch' during 'Assertion prop'

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#109745]
x86 libraries jitstress

https://dev.azure.com/dnceng-public/public/_build/results?buildId=867933&view=ms.vss-test-web.build-test-results-tab

```
"C:\h\w\A3450896\p\dotnet.exe" exec --runtimeconfig System.Collections.Immutable.Tests.runtimeconfig.json --depsfile System.Collections.Immutable.Tests.deps.json xunit.console.dll System.Collections.Immutable.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Collections.Immutable.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Immutable.Tests (found 4292 of 4397 test cases)
  Starting:    System.Collections.Immutable.Tests (parallel test collections = on [4 threads], stop on fail = off)

DOTNET_JitStress=1
DOTNET_TieredCompilation=0

Assert failure(PID 4116 [0x00001014], Thread: 9356 [0x248c]): Assertion failed 'doesVNMatch' in 'System.Collections.Immutable.Tests.ImmutableArrayTest+<ChangeType>d__192`1[int]:MoveNext():ubyte:this' during 'Assertion prop' (IL size 362; hash 0x08aa2d36; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\assertionprop.cpp:1486
    Image: C:\h\w\A3450896\p\dotnet.exe
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Assertion failed 'doesVNMatch'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=867933
**Error message validated:** `[Assertion failed 'doesVNMatch'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 11/14/2024 12:58:45 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[875331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875331)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875331&view=ms.vss-test-web.build-test-results-tab&runId=22840146&resultId=208127)|dotnet/runtime#109987|
|[873656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873656)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873656&view=ms.vss-test-web.build-test-results-tab&runId=22792908&resultId=208116)|dotnet/runtime#106557|
|[873420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873420)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873420&view=ms.vss-test-web.build-test-results-tab&runId=22785798&resultId=208116)|dotnet/runtime#109826|
|[873272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873272)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873272&view=ms.vss-test-web.build-test-results-tab&runId=22780214&resultId=208116)|dotnet/runtime#109957|
|[872587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=872587)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=872587&view=ms.vss-test-web.build-test-results-tab&runId=22757412&resultId=208095)|dotnet/runtime#109808|
|[871840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871840)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871840&view=ms.vss-test-web.build-test-results-tab&runId=22730096&resultId=208095)|dotnet/runtime#109719|
|[871630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871630)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871630&view=ms.vss-test-web.build-test-results-tab&runId=22723236&resultId=208096)|dotnet/runtime#109861|
|[871309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871309)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871309&view=ms.vss-test-web.build-test-results-tab&runId=22709316&resultId=208269)|dotnet/runtime#109804|
|[871150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871150)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871150&view=ms.vss-test-web.build-test-results-tab&runId=22705474&resultId=208095)||
|[871091](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871091)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871091&view=ms.vss-test-web.build-test-results-tab&runId=22704252&resultId=208095)|dotnet/runtime#109873|
|[871071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871071)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871071&view=ms.vss-test-web.build-test-results-tab&runId=22704030&resultId=208443)|dotnet/runtime#109835|
|[870154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870154)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870154&view=ms.vss-test-web.build-test-results-tab&runId=22671266&resultId=208095)|dotnet/runtime#109503|
|[869691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869691)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869691&view=ms.vss-test-web.build-test-results-tab&runId=22657210&resultId=208192)|dotnet/runtime#109418|
|[867933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867933)|dotnet/runtime|[System.Collections.Immutable.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867933&view=ms.vss-test-web.build-test-results-tab&runId=22605516&resultId=211332)|dotnet/runtime#109714|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|11|14|

**Comment by AndyAyersMS** [comment]
@jakobbotsch possibly from the CSE/SSA change?

**Comment by jakobbotsch** [comment]
Seems likely, I'll take a look

**Comment by jakobbotsch** [comment]
CSEs are keyed by liberal VNs which guarantees that all defs and uses for a single CSE candidate have the same VN. The same is not true for their conservative VNs, however -- each def/use may have a potentially unique conservative VN. However, when VN creates a new `LCL_VAR`, the VN it uses is just a random one from one of the other candidates -- it does not necessarily match the conservative VN that the reaching def has.

The fix will probably be to have the SSA inserter update the VN so that it matches the actual reaching definition.

**Comment by jakobbotsch** [comment]
> CSEs are keyed by liberal VNs which guarantees that all defs and uses for a single CSE candidate have the same liberal VN. The same is not true for their conservative VNs, however -- each def/use may have a potentially unique conservative VN. However, when VN creates a new `LCL_VAR`, the VN it uses is just a random one from one of the other candidates -- it does not necessarily match the conservative VN that the reaching def has.
> 
> The fix will probably be to have the SSA inserter update the VN so that it matches the actual reaching definition.

Things don't look quite that simple as CSE does a bit of post processing over the conservative VNs. Will probably have to refactor things in CSE a bit to now make use of the proper reaching definitions (as a side note, it looks like some things can be cleaned up now that we have this).
