### ISSUE TITLE
Diagnostics eventcommand argument error when run generic host on netframework

### ISSUE THREAD

**Issue by QyQj** [dotnet/runtime#109712]
### Description

I'm trying to use generic host on net480, but when run the host, there will be a `System.ArgumentException` （I enable this exception to terminate when debugging） with message `Bit position in AllKeywords (48) must equal the command argument named "EtwSessionKeyword" (43).` 

The stacktrace is 
```
   在 System.Diagnostics.Tracing.EventSource.DoCommand(EventCommandEventArgs commandArgs)
```

I tried to debug the decompiled source and found that the command is a `Enable` command with one argument `FilterAndPayloadSpecs` and the value is
```
Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting@Activity1Start:-CommandId;Command.CommandText
Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted@Activity1Stop:-CommandId;Duration
Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Command.DataReaderDisposing:-CommandId;ReadCount
Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpened@Activity1Start:-ConnectionId;Connection.ConnectionString
Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Connection.ConnectionClosed@Activity1Stop:-ConnectionId
SqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandBefore:-OperationId;Command.CommandText
SqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandAfter:-OperationId
SqlClientDiagnosticListener/System.Data.SqlClient.WriteConnectionOpenAfter:-ConnectionId;Connection.ConnectionString
SqlClientDiagnosticListener/System.Data.SqlClient.WriteConnectionCloseBefore:-ConnectionId
SqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteCommandBefore:-OperationId;Command.CommandText
SqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteCommandAfter:-OperationId
SqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteConnectionOpenAfter:-ConnectionId;Connection.ConnectionString
SqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteConnectionCloseBefore:-ConnectionId
JetBrains.DPA.SQL/Database.Command.CommandExecuting:-CommandId;CommandText
JetBrains.DPA.SQL/Database.Command.CommandExecuted:-CommandId;Duration
JetBrains.DPA.SQL/Database.Command.DataReaderDisposing:-CommandId;ReadCount
JetBrains.DPA.SQL/Database.Connection.ConnectionOpened:-ConnectionId;ConnectionString
JetBrains.DPA.SQL/Database.Connection.ConnectionClosed:-ConnectionId
Microsoft.AspNetCore/Microsoft.AspNetCore.Mvc.AfterControllerActionMethod:-ActionContext.HttpContext.TraceIdentifier;ActionContext.ActionDescriptor.MethodInfo.Module.ModuleVersionId;ActionContext.ActionDescriptor.MethodInfo.MetadataToken
Microsoft.AspNetCore/Microsoft.AspNetCore.Mvc.BeforeControllerActionMethod:-ActionContext.HttpContext.TraceIdentifier
Microsoft.AspNetCore/Microsoft.AspNetCore.Mvc.AfterHandlerMethod:-ActionContext.HttpContext.TraceIdentifier;HandlerMethodDescriptor.MethodInfo.Module.ModuleVersionId;HandlerMethodDescriptor.MethodInfo.MetadataToken
Microsoft.AspNetCore/Microsoft.AspNetCore.Mvc.BeforeHandlerMethod:-ActionContext.HttpContext.TraceIdentifier
Microsoft.AspNetCore/Microsoft.AspNetCore.Mvc.AfterViewComponent:-ViewComponent.HttpContext.TraceIdentifier;ViewComponentContext.ViewComponentDescriptor.MethodInfo.Module.ModuleVersionId;ViewComponentContext.ViewComponentDescriptor.MethodInfo.MetadataToken
Microsoft.AspNetCore/Microsoft.AspNetCore.Mvc.BeforeViewComponent:-ViewComponent.HttpContext.TraceIdentifier
```

I'm not familia with the runtime library, I don't know if this affect anything.

### Reproduction Steps

Just run a generic host in a dotnet framework console program like this
```
Host.CreateDefaultBuilder().Build().Run();
```
And then the exception occurs

### Expected behavior

No exception occurs

### Actual behavior

`System.ArgumentException` exception occurs

### Regression?

It occurs from net462 which the generic host required to net481 and I tried net6.0 and net8.0 everything works well

### Known Workarounds

Not any

### Configuration

net480

x64 windows11 pro workstations  23h2, os verison 22631.4317

**Comment by huoyaoyuan** [comment]
What version of packages are you using? I can't find the exception message in latest code, only in archived corert version: https://github.com/dotnet/corert/blob/c6af4cfc8b625851b91823d9be746c4f7abdc667/src/System.Private.CoreLib/src/Resources/Strings.resx#L2744

**Comment by QyQj** [comment]
> What version of packages are you using? I can't find the exception message in latest code, only in archived corert version: https://github.com/dotnet/corert/blob/c6af4cfc8b625851b91823d9be746c4f7abdc667/src/System.Private.CoreLib/src/Resources/Strings.resx#L2744

I'm using Microsoft.Extensions.Hosting Version 8.0.1 and I also tried 6.0.1

The exception was throwed from mscorlib
https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/diagnostics/eventing/eventsource.cs#L2700-L2705

I compare the `DoCommand` method in netframework with net8.0, they are different, the code throw the error which under a conditional compilation `FEATURE_ACTIVITYSAMPLING` were removed in net8.0, 

in netframework
https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/diagnostics/eventing/eventsource.cs#L2679-L2735

and in net8.0
https://github.com/dotnet/runtime/blob/c1ae962610643a3c17bcf9621017ac42ff7703f7/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L2685-L2737

**Comment by tommcdon** [comment]
Hi @QyQj!  Would it be possible to share a small, reproducible test case we could use for investigation?   It seems you might be using ASP.NET core on .NET Framework.  Note that the only supported version of ASP.NET Core is 2.1 on .NET framework -https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet/2.1-packages.

**Comment by QyQj** [comment]
Hi @tommcdon, I'm sure I'm not using ASP.NET Core

For a test case, you can use this: https://github.com/QyQj/ForIssue109712

It's just a simple code to run a Generic Host

By the way, today I tried this code on another laptop, the exception was not thrown, really strange

**Comment by mdh1418** [comment]
Hi @QyQj, is this exception always occurring for you, and is it blocking your work?
Are you enabling EventSource via ETW on your machine, like by collecting a trace through PerfView?

I haven't been able to reproduce the issue yet, but if you have a full callstack, that would help pinpoint what eventually triggers DoCommand.

In any case, this issue seems to be specific to .NET Framework. While .NET Framework is still supported, active development is limited and we do not use GitHub to track .NET Framework specific issues. Instead, please submit this issue to the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home). Please note that unless there is a critical reliability concern though, it's unlikely to receive immediate attention.

**Comment by QyQj** [comment]
> Hi [@QyQj](https://github.com/QyQj), is this exception always occurring for you, and is it blocking your work? Are you enabling EventSource via ETW on your machine, like by collecting a trace through PerfView?
> 
> I haven't been able to reproduce the issue yet, but if you have a full callstack, that would help pinpoint what eventually triggers DoCommand.
> 
> In any case, this issue seems to be specific to .NET Framework. While .NET Framework is still supported, active development is limited and we do not use GitHub to track .NET Framework specific issues. Instead, please submit this issue to the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home). Please note that unless there is a critical reliability concern though, it's unlikely to receive immediate attention.

Hi @mdh1418 , thank you for your reply, exactly this issue only out put some strange log when debug at this time, I'll close this issue first and collect more info.
