### ISSUE TITLE
Location (highlighting) of IL2026 diagnostic could be improved

### ISSUE THREAD

**Issue by YoshiRulz** [dotnet/runtime#109823]
```csharp
void Current() => {|IL2026:JsonSerializer.Serialize(obj.LongMethodCallWith(args))|};
void Proposal() => {|IL2026:JsonSerializer.Serialize|}(obj.LongMethodCallWith(args));
```
Apologies if this is the wrong repo. I believe [this](https://github.com/dotnet/runtime/blob/c65320833210f3df7412e2fcd11d6751fa374adc/src/tools/illink/src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs#L16) is the source for the Analyzer, but it's not obvious where the relevant `GetLocation` call is.
I have version 8.0.110 of the SDK installed.
Moved from https://github.com/dotnet/roslyn/issues/75914.

**Comment by jtschuster** [comment]
@sbomer any thoughts? I think it could be helpful to put the warning just on the method reference, especially in cases where the method spans multiple lines and arguments are method calls. Then these calls wouldn't have overlapping warnings:

```C#
MethodWithRUC(
  AnotherMethodWithRuc(),
  MethodWithRuc()
);
```
