### ISSUE TITLE
The new TimeSpan FromMilliseconds overload breaks System.Linq.Expressions

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#109833]
edited by @tarekgh to add the API proposal.

### Description

In .NET 9.0, we introduced overloads for the [`TimeSpan.From...`](https://github.com/dotnet/runtime/issues/93890#issuecomment-1777761585) methods to accept integral types. Unfortunately, the approved proposal included only a single overload with an optional parameter for the `FromMilliseconds` method.

```C#
public static TimeSpan FromMilliseconds(long milliseconds, long microseconds = 0);
```

Unfortunately, this broke the LINQ expression when used as follows, resulting in the error: `error CS0854: An expression tree may not contain a call or invocation that uses optional arguments`.

```C#
Expression<Action> a = () => TimeSpan.FromMilliseconds(1000); // compiles with .NET 8, fails with .NET 9
```

Note, this worked fine in net8 because we didn't have the new overload and we had the one that is accepting `double` parameter.

### Proposal

```diff
public partial struct TimeSpan
{
+    public static TimeSpan FromMilliseconds(long milliseconds);

+    public static TimeSpan FromMilliseconds(long milliseconds, long microseconds);
-    public static TimeSpan FromMilliseconds(long milliseconds, long microseconds = 0);
}
```

### Description

I have seen the breaking change notice with regards to F#, but migrating to .NET 9 has revealed a couple of places in our C# projects, where constructing a TimeSpan is part of a System.Linq.Expressions.Expression. These now don't compile with .NET 9

### Reproduction Steps

```csharp
using System.Linq.Expressions;
Expression<Action> a = () => TimeSpan.FromMilliseconds(1000); // compiles with .NET 8, fails with .NET 9
```

### Expected behavior

Code continues to compile

### Actual behavior

Code breaks in .NET 9

### Regression?

yes

### Known Workarounds

You need to force the `double` overload
```
Expression<Action> a = () => TimeSpan.FromMilliseconds(1000.0);
```
[or provide the optional parameter](https://github.com/dotnet/runtime/issues/109833#issuecomment-2477115423)
```
Expression<Action> a = () => TimeSpan.FromMilliseconds(1000, 0); 
```

### Other information

The reason is that the optional parameters are not supported in expressions.

**Comment by Tragetaschen** [comment]
Introduced with https://github.com/dotnet/runtime/issues/93890

**Comment by julealgon** [comment]
I was under the impression that exposing methods with default parameters in public APIs was frowned upon, and that it was best to just have multiple overloads instead.

Does anybody know if that's not really the case, or if it still applies, why these new APIs for `TimeSpan` didn't follow that practice?

**Comment by Tragetaschen** [comment]
The [approved API](https://github.com/dotnet/runtime/issues/93890#issuecomment-1777761585) said
> The methods should be overloaded to have no default parameters per our normal default parameters usability guideline

But the implementation in #98633 did not include those.

**Comment by bartonjs** [comment]
In general, we still think using default/optional parameters is goodness, but given that all of the other method groups on this type have a "no defaults" option making FromMilliseconds look the same looks "natural", and fixes a compile break here.

```diff
public partial struct TimeSpan
{
+    public static TimeSpan FromMilliseconds(long milliseconds);

+    public static TimeSpan FromMilliseconds(long milliseconds, long microseconds);
-    public static TimeSpan FromMilliseconds(long milliseconds, long microseconds = 0);
}
```

**Comment by julealgon** [comment]
@bartonjs this might be a bit off-topic here, but are there any discussions on what could be done in the future to make optional parameters work "better" and avoid these kinds of breaks when using it?

Wouldn't it be possible to do something where using optional parameters ends up being the same as having multiple overloads behind the scenes?

Conceptually, the fact that that proposal you added "fixes" this issue seems bad. They _should_ be equivalent, but they are not.

**Comment by Tragetaschen** [comment]
I guess in this specific instance, the main culprit is that System.Linq.Expressions has not evolved at all since its inception and there is now quite a large gap between language features and its capabilities. I understand all the things brought up over at https://github.com/dotnet/csharplang/issues/2545 and how hard that problem is in general. Nevertheless, I would be so, so, so happy if there was investment in that area.
