### ISSUE TITLE
window.Module.FS and IDBFS no longer works in .NET 9

### ISSUE THREAD

**Issue by peerem** [dotnet/runtime#109810]
### Description

It no longer works since .NET 9. We always had this switch in the project in .NET 8. Has it been changed again?

`<EmccExtraLDFlags>-lidbfs.js</EmccExtraLDFlags>`

We get now following error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'FS')

`    window.Module.FS.syncfs(async t => {
...
    }`

If we downgrade to .NET 8 it works again fine.

**Comment by Yu-Core** [comment]
I find `Blazor.runtime.Module.FS`
It can work on my application

**Comment by maraf** [comment]
The change was introduced in https://github.com/dotnet/aspnetcore/pull/52732. A way forward is to use `Blazor.runtime`.

**Comment by peerem** [comment]
> I find `Blazor.runtime.Module.FS` It can work on my application

This works fine.

**Comment by peerem** [comment]
> The change was introduced in [dotnet/aspnetcore#52732](https://github.com/dotnet/aspnetcore/pull/52732). A way forward is to use `Blazor.runtime`.

Unfortunately, I couldn't find any further documentation on this. But it works.

**Comment by maraf** [comment]
I'm sorry for the inconvenience, I have posted the announcement at least now in case anybody else is affected by this change https://github.com/aspnet/Announcements/issues/516.
