### ISSUE TITLE
Step Over sometimes executes a lot more than one statement

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#109885]
### Description

When I'm debugging code, I use F10 (Step Over) to walk through one line of code at a time.
In .NET 8x, this worked fine.
In .NET 9x, sometimes it seems like it runs a TON more code until it hits a breakpoint.

I suspect I might be running into some variant of https://github.com/dotnet/runtime/issues/109785 and I specifically notice this happening in ForEach code as described in https://github.com/dotnet/runtime/issues/109812 .

I see this is slated to be fixed in .NET 10.0, however, this is a major annoyance and I am very hopeful this will be approved for servicing.

### Reproduction Steps

Not sure.

### Expected behavior

"Step Over" works like .NET 8.0

### Actual behavior

"Step Over" sometimes works like "Continue"

### Regression?

Yes.

### Known Workarounds

Use .NET 8.0

**Comment by rowi123** [comment]
I have this bug too.
For me it is not related to for each at all
Also i see this is added to the dotnet 10 milestone, that's crazy: this a bug preventing normal debugging workflow 

For me hot reload also doesn't work in dot net 9

More info: 
https://stackoverflow.com/questions/79212086/net-9-debugger-step-over-f10-behaving-like-continue-f5

**Comment by TonyValenti** [comment]
Ya.  Debugging really sucks in .NET 9.0 right now.

If I had to guess, it was added to 10.x as a matter of policy, but I'm about 100% certain that once everybody gets back from holiday (and enough people complain here), this will be approved for servicing pretty quickly.

**Comment by antonkalcikavanade** [comment]
Same here

**Comment by akalcik** [comment]
Same here

**Comment by Woudjee** [comment]
I have the same issue. It happens all the time and is very tricky. I cannot debug effectively currently.

**Comment by Woudjee** [comment]
> I have this bug too. For me it is not related to for each at all Also i see this is added to the dotnet 10 milestone, that's crazy: this a bug preventing normal debugging workflow
> 
> For me hot reload also doesn't work in dot net 9
> 
> More info: https://stackoverflow.com/questions/79212086/net-9-debugger-step-over-f10-behaving-like-continue-f5

Wait what. Is this not going to be fixed anytime soon? Do you have a source?

**Comment by rowi123** [comment]
![Image](https://github.com/user-attachments/assets/9191a152-be1f-48b9-b017-6e033b43ca99)

**Comment by Woudjee** [comment]
This bug is genuinely unworkable for me. When pressing F10, it keeps going significantly further than what I want. I am trying to debug geometrical algorithms. I can only do this when I know exactly where I am in this process. It is impossible to do whent it goes all over the place. I am trying to combat this by putting a breakpoint every other line, but this is simply not working.

When will this be fixed?

**Comment by rowi123** [comment]
Why are you still on 9?
I moved back to 8 i am staying far far away from this for at least a quarter year.

**Comment by Woudjee** [comment]
I put a lot of effort into moving all my projects to .NET 9.0 last week. I need it for MAUI Blazor Hybrid. It is not possible for me to go back. Have been looking forward to .NET 9.0 for a long time.

**Comment by Woudjee** [comment]
I also continue to have try-catches that are not catching errors. Is this also a .NET 9.0 thing?

**Comment by tommcdon** [comment]
Hello all!  Our workflow is to fix issues in main, then backport to servicing as needed.  Since this issue applies to both to main (.NET 10) and .NET 9, we put the issue in the .NET 10 milestone.  Once we have a fix for the problem, we plan to backport a servicing-friendly version of it to .NET 9.

**Comment by tommcdon** [comment]
> I also continue to have try-catches that are not catching errors. Is this also a .NET 9.0 thing?

Hello @Woudjee!  This sounds like a different problem.  Please feel free to open a new github issue to track it.

**Comment by Woudjee** [comment]
> Hello all! Our workflow is to fix issues in main, then backport to servicing as needed. Since this issue applies to both to main (.NET 10) and .NET 9, we put the issue in the .NET 10 milestone. Once we have a fix for the problem, we plan to backport a servicing-friendly version of it to .NET 9.

Thank you for your reply. That makes sense! In your experience, how much time does it usually take for these kinds of issues to be resolved? A week? A month? A quarter? Then I can somewhat anticipate on this during my work the upcoming period 👍

**Comment by rowi123** [comment]
> Hello all! Our workflow is to fix issues in main, then backport to servicing as needed. Since this issue applies to both to main (.NET 10) and .NET 9, we put the issue in the .NET 10 milestone. Once we have a fix for the problem, we plan to backport a servicing-friendly version of it to .NET 9.

Thank you for explaining this,

**Comment by f2bo** [comment]
Disabling CET in the project file seems to help in my case.

``` XML
<CETCompat>false</CETCompat>
```

**Comment by Woudjee** [comment]
@f2bo if that solves this, I consider it a solution. But what does it mean? I’ll try it out next week. 👍👍

**Comment by Woudjee** [comment]
@f2bo of course I understand. It’s more a temporary workaround than an actual solution. But if it - for now - allows me to debug, that’s immensely valuable.

I read the section you highlighted. For the software that I am currently developing I believe it’s fine to turn it off. I will let you know my findings later next week.

**Comment by f2bo** [comment]
@tommcdon I see that you've identified the cause. Just out of curiosity, did this turn out to be related to CET or does disabling it only mask out the problem? I couldn't tell from the PR. I should mention that after disabling it, I haven't seen a single failure whereas previously I could almost never complete a debugging session without an incident.

**Comment by thaystg** [comment]
As far as we understood during our tests with CET enabled would cause the race condition, between the APC call and the stepping on debugger, happens more frequently, that is why disabling the CET you didn't get the problem anymore.

**Comment by Woudjee** [comment]
Well done for figuring it out 👍 when do you expect us to be able to update to the version which contains this fix?

**Comment by TonyValenti** [comment]
I am really hoping a .NET 9.0.1 lands today and includes this fix.

**Comment by thaystg** [comment]
We have addressed the bug in an upcoming patch release. I'll update this issue when the patch has been released. Thanks for reporting it!

**Comment by rowi123** [comment]
Good work.

I had 2 issues: this one and i also noticed hot reload not working (no errors, just no code updates).
Does this patch release include anything on that issue?

**Comment by tommcdon** [comment]
Fixed via #110533

**Comment by Woudjee** [comment]
> Good work.
> 
> I had 2 issues: this one and i also noticed hot reload not working (no errors, just no code updates). Does this patch release include anything on that issue?

I have something similar. I have a web api project that sometimes throws a C# compiler error after changing some code and pressing hot reload. This happens sporadically, I don't have any clear order of steps to reproduce this. Happens to me maybe once per workday.

**Comment by Woudjee** [comment]
> Fixed via [#110533](https://github.com/dotnet/runtime/pull/110533)

Is there a manual download or other action required to retrieve the fix?

**Comment by akalcik** [comment]
@Woudjee It is labeled for milestone 9.0.2 so it should be included in the next upcoming service release of .NET 9

**Comment by Woudjee** [comment]
> [@Woudjee](https://github.com/Woudjee) It is labeled for milestone 9.0.2 so it should be included in the next upcoming service release of .NET 9

Ah good one. After reading your message, I managed to find that as well. Currently the 9.0.2 milestone is 72% completed so that’s looking promising 👍

**Comment by udlose** [comment]
I know that you cannot give a "release date" for the fix, but can you at least provide a ballpark/approximate release?  This is really causing headaches when trying to debug.

**Comment by Woudjee** [comment]
> I know that you cannot give a "release date" for the fix, but can you at least provide a ballpark/approximate release? This is really causing headaches when trying to debug.

In the meanwhile, use CETCOMPAT = true or = false. It is a workaround that triggers this issue almost never. I have been using it since the beginning of this issue and have been able to be productive with it. If you Google it I’m certain you’ll find it somewhere!

**Comment by udlose** [comment]
> > I know that you cannot give a "release date" for the fix, but can you at least provide a ballpark/approximate release? This is really causing headaches when trying to debug.
> 
> In the meanwhile, use CETCOMPAT = true or = false. It is a workaround that triggers this issue almost never. I have been using it since the beginning of this issue and have been able to be productive with it. If you Google it I’m certain you’ll find it somewhere!

 tried both in all of the projects and neither setting solve the intermittent issue. I hope a fix is released soon - this is a big problem.

**Comment by udlose** [comment]
I saw that .NET 9.0.1 was released yesterday. I couldn't find any of the issues mentioned or the PR for the fix included in the [Release Notes](https://github.com/dotnet/runtime/releases/tag/v9.0.1) - maybe I just missed it - but I decided to look in the [Release branch for the fix](https://github.com/dotnet/runtime/blame/release/9.0/src/coreclr/debug/ee/controller.cpp#L7430-L7438C10) and was relieved to find that the fix was included in the .NET 9.0.1 Release!

**Comment by Woudjee** [comment]
@udlose that is awesome news!

**Comment by rowi123** [comment]
Can someone above report back if this version is working for you?

**Comment by udlose** [comment]
> Can someone above report back if this version is working for you?

I have not had the issue since updating yesterday. Seems to be fixed!

**Comment by f2bo** [comment]
>  I decided to look in the [Release branch for the fix](https://github.com/dotnet/runtime/blame/release/9.0/src/coreclr/debug/ee/controller.cpp#L7430-L7438C10) and was relieved to find that the fix was included in the .NET 9.0.1 Release!

@udlose I haven't updated yet but are you sure this is the right place to look? I also noticed that it wasn't mentioned in the release notes, nor [here](https://github.com/dotnet/runtime/issues?q=sort%3Aupdated-desc%20milestone%3A9.0.1%20state%3Aclosed%20label%3Aservicing-approved). Furthermore, the milestone for the [servicing PR](https://github.com/dotnet/runtime/pull/110533) is labeled 9.0.2.

**Comment by Woudjee** [comment]
> > Can someone above report back if this version is working for you?
> 
> I have not had the issue since updating yesterday. Seems to be fixed!

How do I update? By simply updating using Visual Studio Installer?

**Comment by udlose** [comment]
> > I decided to look in the [Release branch for the fix](https://github.com/dotnet/runtime/blame/release/9.0/src/coreclr/debug/ee/controller.cpp#L7430-L7438C10) and was relieved to find that the fix was included in the .NET 9.0.1 Release!
> 
> [@udlose](https://github.com/udlose) I haven't updated yet but are you sure this is the right place to look? I also noticed that it wasn't mentioned in the release notes, nor [here](https://github.com/dotnet/runtime/issues?q=sort%3Aupdated-desc%20milestone%3A9.0.1%20state%3Aclosed%20label%3Aservicing-approved). Furthermore, the milestone for the [servicing PR](https://github.com/dotnet/runtime/pull/110533) is labeled 9.0.2.

I hadn't noticed it was labeled as 9.0.2 milestone. I'm familiar with the branching strategy that MS uses but I do also see the fix included in the `main` branch which AFAIK is the source that is "live" in Production: [https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/ee/controller.cpp#L7588-L7596](https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/ee/controller.cpp#L7588-L7596)

**Comment by udlose** [comment]
> > > Can someone above report back if this version is working for you?
> > 
> > 
> > I have not had the issue since updating yesterday. Seems to be fixed!
> 
> How do I update? By simply updating using Visual Studio Installer?

VS Installer was what I used. It updated me to VS2022 v17.12.4. If you look at the [.NET Downloads page](https://dotnet.microsoft.com/en-us/download/dotnet/9.0) you can see it says 9.0.102 is included in the latest VS version:

<img width="507" alt="Image" src="https://github.com/user-attachments/assets/5d1dca0d-da20-4d3a-a5c1-5fab7c05d9bd" />

**Comment by udlose** [comment]
After some focused debugging, I can confirm that I misspoke and the issue was _not_ included in .NET 9.0.102 :( - apparently I just hadn't hit the intermittent issue yet. My optimism took over lol - I guess we have to wait until 9.0.2 (and I guess the `main` branch is NOT representative of what is out in PROD)....apologies for the confusion :)

**Comment by f2bo** [comment]
@udlose I understand that disabling CET didn't work in your case. I suppose that since the issue is caused by a race condition, not every environment behaves in the same way. But for other people having this problem, I would suggest trying `<CETCompat>false</CETCompat>`  in the project file, at least while debugging and until 9.0.2 is released. This has been **very** effective in my case.

**Comment by Woudjee** [comment]
@f2bo exactly!

@udlose thank you for your insights!

**Comment by TonyValenti** [comment]
This article seems to indicate that this bug is resolved but I am still running into it with VS 17.12.4 with .NET 9.0.1.

**Comment by Sean4572435243** [comment]
> This article seems to indicate that this bug is resolved but I am still running into it with VS 17.12.4 with .NET 9.0.1.

Supposedly fixed for 9.0.2 (as yet unreleased).  This issue was 'closed' so I have to believe it's imminent.  Really looking forward to having my debugger back to normal, lol

**Comment by udlose** [comment]
Based on their release cadence, I'd expect the fix to be available within the next 2 months or so.

**Comment by MrZakos** [comment]
come on MICROSOFT , I can't even  debug my hello world ...........

**Comment by Sean4572435243** [comment]
I have dozen of projects that I'd rather not doctor up for this purpose when hopefully the next release will take care of it.  I have been using the little green continue-to-here button that appears to the left of all executable code during debugging.  It's not quite as useful as the breakpoints, but it does allow you to control the code execution better than the current state of breakpoints does.

**Comment by rowi123** [comment]
can someone confirm this version is fixed and stable?

**Comment by ato321** [comment]
> can someone confirm this version is fixed and stable?

At least it fixed the example I sent, and exceptions in other threads do not cause the bug anymore.

**Comment by PhotonicX7** [comment]
I can at least confirm it seems to have addressed it on the surface. I haven't noticed the behavior since updating.
