### ISSUE TITLE
System.Management 9.0.0 throws an exception

### ISSUE THREAD

**Issue by GitUser200607** [dotnet/runtime#109860]
```
			var query = new WqlEventQuery(string.Format(
			"SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_LOCAL_MACHINE' AND KeyPath = '{0}' AND (ValueName = '{1}' OR ValueName = '{2}')",
			keyPath.Replace("\\", "\\\\"), valueName1, valueName2));
```
The exception is:

> System.PlatformNotSupportedException: 'System.Management currently is only supported for Windows desktop applications.'

But version **8.0.0** does not throw the exception.

**Comment by ViktorHofer** [comment]
What's the OS that you are running on? Please share a small repro so that we can diagnose this further.

**Comment by GitUser200607** [comment]
So what should I do to evade this error? Downgrade the package?

**Comment by ViktorHofer** [comment]
Agreed. If you must to stay on the out-of-support .NET 6 then you will need to downgrade the package to 8.0.0.

**Comment by GitUser200607** [comment]
I changed target .NET to 9.0:
`<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>`
Now it works fine. Thanks!
