### ISSUE TITLE
[NativeAOT] Blazor Hybrid + Windows Forms event bindings after AOT compilation

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#109888]
When using Blazor Hybrid with Windows Forms and NativeAOT compilation, event bindings (@onclick etc.) stop working although the UI renders correctly. The binds work correctly without NativeAOT.

```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	  <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

	  <PublishAot>true</PublishAot>
	  <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
	  <CustomResourceTypesSupport>true</CustomResourceTypesSupport>
	  <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
```

xml files that I used in my project: https://pastebin.com/raw/vhW37bYT
NativeAOT compiling logs: [logs.txt](https://github.com/user-attachments/files/17787114/logs.txt)

MainForm.cs:
```csharp
    public partial class MainForm : Form
    {
        private BlazorWebView _blazorWebView;
        public MainForm()
        {
            InitializeComponent();

			var services = new ServiceCollection();
			services.AddWindowsFormsBlazorWebView();

			_blazorWebView = new BlazorWebView
            {
				HostPage = "wwwroot/index.html",
				Services = services.BuildServiceProvider(),
			};

			_blazorWebView.RootComponents.Add<Main>("#app");

			_blazorWebView.Dock = DockStyle.Fill;

			Controls.Add(_blazorWebView);
		}
    }
```

Main.razor:
```csharp
@using System.Windows.Forms;



<h1>Hello World!</h1>
<button @onclick="OnClickButton">Hello!</button>

@code {
	private void OnClickButton()
	{
		MessageBox.Show("Hello WOrld!");
	}
}
```

**Comment by jkotas** [comment]
Neither WinForms or Blazor are compatible with full trimming and native AOT currently. It is expected that it is not going to work well. You can follow related issues in WinForms and ASP.NET repos: https://github.com/dotnet/winforms/issues/4649, https://github.com/dotnet/aspnetcore/issues/49409, https://github.com/dotnet/aspnetcore/issues/51598

> xml files that I used in my project: https://pastebin.com/raw/vhW37bYT

Manual authoring of RdXml files is not supported https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/rd-xml-format.md . It results into poorly performing apps with hard to diagnose functionality issues as you have found. I am sorry we are not going to help you with authoring of RdXml files to make things "work". It is not a time well spent.
