### ISSUE TITLE
[8.0] Migrate off of Fedora 39 container image

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#109822]
The Helix config in 8.0 references a Fedora 39 image that doesn't even exist (nor has it ever):

https://github.com/dotnet/runtime/blob/c1ae962610643a3c17bcf9621017ac42ff7703f7/eng/pipelines/libraries/helix-queues-setup.yml#L65

https://github.com/dotnet/runtime/blob/c1ae962610643a3c17bcf9621017ac42ff7703f7/eng/pipelines/libraries/helix-queues-setup.yml#L71

This should be investigated to see whether it even needs to be defined. Are there no jobs that run this environment?

**Comment by akoeplinger** [comment]
We're using Fedora 38 in main so this looks like a mistake done as part of https://github.com/dotnet/runtime/pull/101073

https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/helix-queues-setup.yml#L61

We're only running this in the [runtime-extra-platforms](https://dev.azure.com/dnceng-public/public/_build?definitionId=154&_a=summary) pipeline and it indeed fails there in 8.0

**Comment by akoeplinger** [comment]
Fixed with https://github.com/dotnet/runtime/pull/109964
