### ISSUE TITLE
`foreach` will jump to other code in `dotnet9`

### ISSUE THREAD

**Issue by Coloryr** [dotnet/runtime#109812]
### Description

When I upgrade the project to `Dotnet9` and `foreach` the list, I will jump to other code by myself after the list is not fully `foreach`.
dotnet8
https://github.com/user-attachments/assets/5bd3c4cb-2c7f-4b53-ae2f-adc318f6ee80

dotnet9
https://github.com/user-attachments/assets/9ddfc90d-0000-4bc7-a177-d962416d2d83

### Reproduction Steps

1. make a List<T>
2. add some thing
3. foreach it

### Expected behavior

foreach every item

### Actual behavior

foreach some item and exit all code

### Regression?

dotnet9

### Configuration

windows x64

**Comment by am11** [comment]
I have seen this (and stuff like debugger is stepping through both `if` and `else` in single iteration) happening in unclean state. I'd close all VS instances, `kill -name dotnet` in powershell and delete bin and obj directories before retrying.

**Comment by hoyosjs** [comment]
cc: @dotnet/dotnet-diag  

@mikelle-rogers - you might be the most familiar with this codepath right now in case you have cycles. 

@Coloryr - are there any repros for this? 

@tommcdon might be a manifestation of https://github.com/dotnet/runtime/issues/109785. It's async stepping becomes a go and ends up in the next bp set by the user.

**Comment by Coloryr** [comment]
No, it will skip most of the code. For example, in my code, the file will have data in `Dotnet8`, but in `Dotnet9`, there is a probability that there will be data, and there is a probability that there will not be. The execution results of the code are different.

**Comment by Coloryr** [comment]
> I have seen this (and stuff like debugger is stepping through both `if` and `else` in single iteration) happening in unclean state. I'd close all VS instances, `kill -name dotnet` in powershell and delete bin and obj directories before retrying.

Clean everything did't work.

**Comment by tommcdon** [comment]
Reactivated for backport to 9.0

**Comment by tommcdon** [comment]
Fixed via #110533

**Comment by tommcdon** [comment]
The fix for this issue has shipped in 9.0.2 - available from https://dotnet.microsoft.com/en-us/download/dotnet/9.0.
