### ISSUE TITLE
ILCompiler produces wrong code for calli on x64 platform

### ISSUE THREAD

**Issue by HolographicHat** [dotnet/runtime#109883]
### Description

In some cases, ilcompiler uses the `eax` register instead of the `al` register for the return value in the assembly code generated for the il code `calli bool ()`.

### Reproduction Steps

Clone [this repo](https://github.com/HolographicHat/TestCase1) and run `publish_and_run.cmd`, the output should be
```
ILCompiler8
FalseBranch but bar is False
ILCompiler9
TrueBranch but bar is False
```

### Expected behavior

```c#
// c#
var bar = ((delegate*<nint, bool>) foo)(114514);
if (bar) { /* do something */ }
```

```msil
// msil
// [17 9 - 17 57]
IL_0021: stloc.1      // V_1
IL_0022: ldc.i4       114514 // 0x0001bf52
IL_0027: conv.i
IL_0028: ldloc.1      // V_1
IL_0029: calli        bool (native int)
IL_002e: stloc.0      // bar

// [18 9 - 18 17]
IL_002f: ldloc.0      // bar
IL_0030: brfalse.s    IL_005d
```

```assembly
; assembly
mov     ecx, 1BF52h
call    rax
movzx   ebx, al
test    ebx, ebx    ; or test al, al
jz      short loc_1400C2082
```

### Actual behavior

`c#: same as above`

`msil: same as above`

```assembly
; assembly
mov     ecx, 1BF52h
call    rbx
mov     esi, eax    ; wrong
test    esi, esi
jnz     short loc_140044108
```

### Regression?

works fine in 8.0.11, errors in 9.0.0-preview.1.24080.9

### Configuration

.NET Version: 9.0.100
OS: Windows 10.0.19045
Architecture: x64

**Comment by MichalStrehovsky** [comment]
The testcase looks invalid: it's doing a _managed_ calli into something that is not managed code. Did you want to do an unmanaged calli (use `delegate* unmanaged<nint, bool>`)?

**Comment by HolographicHat** [comment]
> The testcase looks invalid: it's doing a _managed_ calli into something that is not managed code. Did you want to do an unmanaged calli (use `delegate* unmanaged<nint, bool>`)?

after add `unmanaged`, the output is
```
ILCompiler8
TrueBranch but bar is True
ILCompiler9
TrueBranch but bar is True
```
but expected output is `FalseBranch but bar is False`

the gernerated assembly code is
```assembly
; ...
mov     rcx, rbx
call    rsi
test    eax, eax ; ???
setnz   al       ; ???
movzx   eax, al
; ...
retn
```

**Comment by MichalStrehovsky** [comment]
`bool` marshals as the Win32 `BOOL` type per docs: https://learn.microsoft.com/en-us/dotnet/standard/native-interop/type-marshalling#default-rules-for-marshalling-common-types. Win32 `BOOL` is a 4 byte integer.

**Comment by HolographicHat** [comment]
got it, thanks for your help
