### ISSUE TITLE
Char.GetUnicodeCategory returns wrong category for certain Latin-1 characters

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#10990]
In a nutshell, there are certain characters where `CharUnicodeInfo.GetUnicodeCategory` returns the correct value, but `Char.GetUnicodeCategory` returns the wrong value. One such character is U+00B6 PILCROW SIGN, where `CharUnicodeInfo` returns _OtherPunctuation_ (which is correct) and where `Char` returns _OtherSymbol_ (which is incorrect). This also affects the behavior of dependent methods like `Char.IsPunctuation` and `Char.IsLower`.

[MSDN says](https://docs.microsoft.com/en-us/dotnet/api/system.char.getunicodecategory) this behavior is intentional to preserve back-compat, but it is extraordinarily confusing to have two methods with the same name have different behavior.  

One solution would be to update `Char.GetUnicodeCategory` to stay in sync with `CharUnicodeInfo.GetUnicodeCategory`. This is a breaking change, but it's the type of breaking change that is normally allowed in side-by-side major version updates.

An alternative is to mark `Char.GetUnicodeCategory`, `Char.IsPunctuation`, `Char.IsLower`, etc. as obsolete and to direct users to call into `CharUnicodeInfo` instead. This preserves existing behavior and provides a migration story to get developers on to the APIs which provide correct results.

**Comment by stephentoub** [comment]
I've run into this difference recently as well. It is quite confusing that the two methods return different results.

We're working on a major release, .NET 5. It is side-by-side. We are not and do not want to be bug-for-bug compatible. Why not just fix the methods to return the same results? Who are we helping by continuing to ship the discrepancy?

**Comment by tarekgh** [comment]
Moving it to 5.0 release as this will be the chance to have such breaking change.
