### ISSUE TITLE
Community notifications

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#109961]
`area-owners.md` says one should submit a PR to modify `.github/fabricbot.json` if they want to be notified for specific tags. However, that file does not exist.

https://github.com/dotnet/runtime/blob/main/docs/area-owners.md?plain=1#L11

https://github.com/dotnet/runtime/blob/main/.github/fabricbot.json

**Comment by huoyaoyuan** [comment]
It was converted into `.github/policies/resourceManagement.yml`
