### ISSUE TITLE
Calling instance-based methods with function pointers is not supported

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#110061]
Calling a managed function pointer on an instance that returns a non-primitive value type (perhaps based on length?) will return random values and causes stack\heap issues later.

__UPDATED_:_ I assume calling a function pointer on an instance method is supposed to work, provided the signature is correct for having the first parameter being the correct type (here "object" was used, but "TestClass" has the same result since it is a reference type). However, the [function pointer spec](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers) says that instance methods are not supported (at least initially; not sure what transpired since then).

Note the IL looks correct, and the method is actually called.

This does not appear to be a regression.

Repro: the `long` property works but `Guid` doesn't, and a subsequent call to the `long` property returns a corrupted value.
```csharp
public class TestClass
{
    public Guid _guid = new Guid("12300000-0000-0000-0000-000000000456");
    public int _long = 42;

    public Guid MyGuid => _guid;
    public long MyLong => _long;
}

internal unsafe class Program
{
    static void Main(string[] args)
    {
        MethodInfo method;
        IntPtr fp;
        
        TestClass testClass = new();
        
        fp = typeof(TestClass).GetMethod("get_MyLong").MethodHandle.GetFunctionPointer();
        delegate* managed<object, long> fpLong = (delegate* managed<object, long>)fp;
        long vLong = fpLong(testClass);
        Console.WriteLine(vLong); //42
        testClass._long++;
        vLong = fpLong(testClass);
        Console.WriteLine(vLong); //43
        
        fp = typeof(TestClass).GetMethod("get_MyGuid").MethodHandle.GetFunctionPointer();
        delegate* managed<object, Guid> fGuid = (delegate* managed<object, Guid>)fp;
        Guid vGuid = fGuid(testClass);
        Console.WriteLine(vGuid);           // 00000000-0000-0000-0000-000000000000 (wrong)
        Console.WriteLine(testClass._guid); // 12300000-0000-0000-0000-000000000456
        
        vLong = fpLong(testClass);
        Console.WriteLine(vLong); // random number (not 43)
    }
}
```

**Comment by steveharter** [comment]
Closing; wrong repro

**Comment by steveharter** [comment]
Reopened; updated repro

**Comment by steveharter** [comment]
Closing for now; the spec proposes "instance" keyword:

```csharp
unsafe class Instance {
    void Use() {
        delegate* instance<Instance, string> f = &ToString;
        f(this);
    }
}
```

**Comment by MichalPetryka** [comment]
> says that instance methods are not supported (at least initially; not sure what transpired since then).

AFAIR LDM decided they're too nieche too expose in C#, but they should be fully functional in IL.

I assume if they were to be exposed in C#, it'd only be `explicitthis` ones since I don't see a way to reasonably handle ones with implicit this.

**Comment by steveharter** [comment]
> AFAIR LDM decided they're too nieche too expose in C#, but they should be fully functional in IL.

Yes the [spec calls out the feature](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/function-pointers.md), but with some unresolved issues. I was assuming explicitthis.

I was looking at this for https://github.com/dotnet/runtime/pull/109901 which would allow, for example, a single C# function pointer signature for a property setter on a reference type + a reference type value (i.e. "system.object" as the declaring type and property type) which would be used by reflection as a fast way to call that setter and without using emit or the slower interpreted path. In that draft PR, for the emit case, uses `il.EmitCalli()` with `CallingConventions.HasThis` which works fine, just no way to do that with C# + function pointers directly.
