### ISSUE TITLE
[area-Tools-ILLink]:

### ISSUE THREAD

**Issue by bvbellomo** [dotnet/runtime#110011]
### Description

I got:
IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink

No other relevant information seems to have been provided

### Reproduction Steps

?

### Expected behavior

I can compile

### Actual behavior

I can't compile

**Comment by jtschuster** [comment]
Thanks for reporting the issue! Can you tell us what you were trying to compile that caused this issue, what commands you ran, what OS you're on, and version of .NET you're using? Also, if theres any exception information in the build log, that would be helpful.

**Comment by bvbellomo** [comment]
This was compiling a .NET Maui project under VS 17.12.1.  I don't think any more information was available in the logs.  I am hoping whoever put the message in asking me to report this error sees this ticket and adds more information (such as a call stack) in the future.  A clean, rebuild all, and fresh install seems to have fixed it.

**Comment by jtschuster** [comment]
Sounds like it might have gotten into a broken state between builds if a clean + rebuild fixed it. I'll close this for now, but please reopen if you run into it again.
