### ISSUE TITLE
mono code line crash my server

### ISSUE THREAD

**Issue by aotto1968** [dotnet/runtime#110006]
### Description

Hi, the following line of code crash my server:
```
GetType().GetMethod("ReadI").Invoke(this,null);
```
The Method-Name `ReadI` is wrong and I expect to get a NULL pointer exception **but** mono crash:

### short

Bug is `method.Invoke(this,null)` with an invalid (null?) method
-> expect: `System.NullReferenceException`
-> get: CORE
-> last GOOD command is `Console.WriteLine("method=" + method);`
-> search for **method=** in attachment

####################################################################################################
### BAD code (core)

```
    # HIGH is a delegate called as "service"
    private void HIGH () {
      var s = ReadSTR() ;
      switch (s) {
        case "SEND_ONE_BUF": {
          var t = ReadSTR();
          //var tt = ReadSTR();
Console.WriteLine("START");
          var type = GetType();
Console.WriteLine("type=" + type);
          var method = type.GetMethod($"Read{t}");  // calling: "ReadI"
Console.WriteLine("method=" + method);
          var read = method.Invoke(this,null);      // !! CORE !!
Console.WriteLine(read);
          var ret = (MkBufferC) Send("W",$"ECOA:{t}@U",read);
          //var ret = (MkBufferC) Send("W",$"ECOA:{t}@U",GetType().GetMethod($"Read{tt}").Invoke(this,null));
          Send("R","U",ret);
          break;
        }
      ...
    }
```

attachment: trace until crash -> [bug_crash.log](https://github.com/user-attachments/files/17828136/bug_crash.log)

####################################################################################################
### GOOD code (reference)
```
using System;

sealed class BugGetMethodCore {
  Object make_core() {
    var type = GetType();
Console.WriteLine("type=" + type);
    var method = type.GetMethod("ReadI");
Console.WriteLine("method=" + method);
    var read = method.Invoke(this,null);
Console.WriteLine(read);
    return read;
  }

  static void Main(string[] argv) {
    var bug = new BugGetMethodCore();
    Console.WriteLine(bug.make_core());
  }
} 
```
test code → OK

attachment: trace until end -> [bug_good.log](https://github.com/user-attachments/files/17828175/bug_good.log)
The message from `MqDisasterSignal` is my crash handler listen on `SIGSEGV`

```
void MqDisasterSetup(void) {
  // once per application
  static bool setup_done = false;
  if (setup_done) return;
  setup_done = true;

  // initialised to all zero (I vote for GCC style breach of standard here)
  struct sigaction sa = {};

  sa.sa_handler = MqDisasterSignal;
  sa.sa_flags = 0 /* | SA_RESETHAND | SA_NODEFER */;  /* To have or have not */
//  sigaction(SIGINT, &MqDisasterSA, NULL);
  sigaction(SIGSEGV, &sa, NULL);
}
```
GOOD error message from reference code
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at BugGetMethodCore.make_core () [0x00034] in <0ad1f995e5b047fe81582953d312d059>:0
  at BugGetMethodCore.Main (System.String[] argv) [0x00007] in <0ad1f995e5b047fe81582953d312d059>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at BugGetMethodCore.make_core () [0x00034] in <0ad1f995e5b047fe81582953d312d059>:0
  at BugGetMethodCore.Main (System.String[] argv) [0x00007] in <0ad1f995e5b047fe81582953d312d059>:0
```

### Reproduction Steps

have reference example but CORE only happen in my server code.

### Expected behavior

expect: System.NullReferenceException

### Actual behavior

get: core

### Configuration

> uname -a
Linux linux02 5.14.21-150500.55.83-default #1 SMP PREEMPT_DYNAMIC Wed Oct 2 08:09:07 UTC 2024 (0d53847) x86_64 x86_64 x86_64 GNU/Linux
> cat /etc/SUSE-brand 
openSUSE
VERSION = 15.5
> mono -V
Mono JIT compiler version 6.8.0.105 (tarball Fri Jun 23 18:47:43 UTC 2023)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by huoyaoyuan** [comment]
> mono -V
> Mono JIT compiler version 6.8.0.105 (tarball Fri Jun 23 18:47:43 UTC 2023)

This is the old, .NET Framework-compatible Mono at https://github.com/mono/mono . It's now sunsetting. If you don't need .NET Framework compatibility, you can move to modern .NET on Linux.

**Comment by aotto1968** [comment]
![Image](https://github.com/user-attachments/assets/4d4a72d9-b615-49e6-9a15-5f388feb0641)

this is the mono OpenSUSE offering I can use → what should I choose?

**Comment by huoyaoyuan** [comment]
> I found a link on MS website: https://learn.microsoft.com/en-us/dotnet/core/install/linux-opensuse
> is this the _official_ C# on linux?

Yes. For modern .NET, there are binaries built by Microsoft, and by distro owners. Both are considered official, supported by whoever builds them. This repo is the upstream and patches will be adopted by distro owners. `dotnet` is the common moniker for package names.

**Comment by aotto1968** [comment]
I download an install this, **but** this is an complete other architecture… this mean I have to rewrite my own build-process… this is now an unplanned task and will be moved into the near future.

**Comment by huoyaoyuan** [comment]
> **but** this is an complete other architecture… this mean I have to rewrite my own build-process…

Unfortunately yes, it's a migration. The effort for maintaining old mono is very low now so it's unlikely to get the bug fixed in time.
