### ISSUE TITLE
[API Proposal]: Missing 64-bit CPU intrinsics (e.g. pmovmskb on mm)

### ISSUE THREAD

**Issue by mgravell** [dotnet/runtime#110005]
### Background and motivation

Example; `Sse2` has methods like `MoveMask(Vector128<byte> value)`, which maps to `PMOVMSKB r32, xmm1` / `int _mm_movemask_epi8 (__m128i a)`, however: according to some sources ([a](https://www.felixcloutier.com/x86/pmovmskb), [b](http://www.nacad.ufrj.br/online/intel/vtune/users_guide/mergedProjects/analyzer_ec/mergedProjects/reference_olh/mergedProjects/instructions/instruct32_hh/vc240.htm)) it is also possible to perform this operation on a 64-bit `mm` register.

Sometimes, you only have 8 bytes, or you only want to work with 8 bytes and don't want to load 128 bits unnecessarily.

***IMPORTANT***: I an not an intrinsics expert; there is a lot of anecdotal reading that basically says MMX registers aren't worth using on modern CPUs (other than storage), and have cost penalties. If that's the reason they are missing, fine: just close me!

I have not scanned for other missing 64-bit intrinsics; I'm guessing this isn't an isolated example.

### API Proposal

``` diff
  class Sse // or possibly Sse.X64
  {
+     //  blah PMOVMSKB r32, mm
+     public static int MoveMask(ulong value);
  }
```

or

``` diff
  class Sse // or possibly Sse.X64
  {
+     //  blah PMOVMSKB r32, mm
+     public static int MoveMask(Vector64<byte> value);
  }
```

I guess the return type could also be `uint`, or possibly even `byte` (although that wouldn't directly match the CPU upcode layout, so is probably best avoided).

### API Usage

Selfishly, I'm interested in this scenario for "varint" decoding (protobuf serialization), using `MoveMask`, `TrailingZeroCount` and `ParallelBitExtract` decode. For context, "varint" is a little-endian packing format where the MSB of each successive byte signals continuation. So: `0x9601` is the value `150`; `0x96`  is `0b10010110`, contributing `0b0010110` at the little end, and signalling continuation; `0x01` gives us `0b0000001` in the next 7-bit segment and does not signal continuation - combining these gives us the value `0b10010110`, or decimal `150`. Quite a nice fit for `PMOVMSKB` and `PEXT`, using `TZCNT` to `switch` on the lengths.

Here's a version that works but isn't optimal under the current code:

``` c#
        if (BitConverter.IsLittleEndian && Sse2.IsSupported && Bmi1.IsSupported && Bmi2.IsSupported && Bmi2.X64.IsSupported)
        {
            if (span.Length >= 16)
            {
                ref byte origin = ref MemoryMarshal.GetReference(span);
                switch (Bmi1.TrailingZeroCount(~(uint)Sse2.MoveMask(Unsafe.ReadUnaligned<Vector128<byte>>(ref origin))))
                {
                    case 0:
                        value = origin; // decoded value
                        return 1; // bytes used
                    case 1:
                        value = Bmi2.ParallelBitExtract(Unsafe.ReadUnaligned<uint>(ref origin), 0x7F7FU);
                        return 2;
                    case 2:
                        value = Bmi2.ParallelBitExtract(Unsafe.ReadUnaligned<uint>(ref origin), 0x7F7F7FU);
                        return 3;
                    case 3:
                        value = Bmi2.ParallelBitExtract(Unsafe.ReadUnaligned<uint>(ref origin), 0x7F7F7F7FU);
                        return 4;
                    case 4:
                        value = checked((uint)Bmi2.X64.ParallelBitExtract(Unsafe.ReadUnaligned<ulong>(ref origin), 0x7F7F7F7F7FU));
                        return 5;
                }
            }
        }
```

I *believe* this could be, if this intrinsic existed:

``` c#
        if (BitConverter.IsLittleEndian && Sse.IsSupported && Bmi1.IsSupported && Bmi2.IsSupported && Bmi2.X64.IsSupported)
        {
            if (span.Length >= sizeof(ulong))
            {
                ref byte origin = ref MemoryMarshal.GetReference(span);
                ulong value = Unsafe.ReadUnaligned<ulong>(ref origin);
                switch (Bmi1.TrailingZeroCount(~(uint)Sse.MoveMask(value))
                {
                    case 0:
                        value = value & 0x7F; // decoded value
                        return 1; // bytes used
                    case 1:
                        value = Bmi2.ParallelBitExtract((uint)value, 0x7F7FU);
                        return 2;
                    case 2:
                        value = Bmi2.ParallelBitExtract((uint)value, 0x7F7F7FU);
                        return 3;
                    case 3:
                        value = Bmi2.ParallelBitExtract((uint)value, 0x7F7F7F7FU);
                        return 4;
                    case 4:
                        value = checked((uint)Bmi2.X64.ParallelBitExtract(value, 0x7F7F7F7F7FU));
                        return 5;
                }
            }
        }
```

I *hope* that this might be faster (albeit marginally, but: paper cuts - this is a high volume path), however I have no good way to validate this currently. I'm not an assembler junkie.

### Risks

Something obscure I don't know about the applicability of this intrinsic to different CPU architectures.

**Comment by huoyaoyuan** [comment]
> there is a lot of anecdotal reading that basically says MMX registers aren't worth using on modern CPUs (other than storage), and have cost penalties.

I believe this is the core reason why we don't use MMX at all. They are not even fully specified in [Windows x64](https://learn.microsoft.com/windows-hardware/drivers/debugger/x64-architecture#registers) [calling convention](https://learn.microsoft.com/cpp/build/x64-calling-convention#floating-point-support-for-older-code).

> Sometimes, you only have 8 bytes, or you only want to work with 8 bytes and don't want to load 128 bits unnecessarily.

`Vector128.CreateScalar<long>` gives you an XMM value with only 64 bits filled.

**Comment by TechPizzaDev** [comment]
The JIT is usually quite good when it comes to codegen, especially with cross-platform intrinsics (Vector128).
The code below emits `vmovq, vpmovmskb` which is just one extra `vmovq` compared to doing just a `PMOVMSKB` on a MM register.

It would be preferable to optimize* `CreateScalar+ExtractMostSignificantBits` into that instruction instead of providing a new intrinsic because that would possibly improve existing code.

*It's likely not faster as mentioned earlier with regard to MM registers etc. and intrinsics have maintenance cost in JIT.
And intrinsics are usually not added if they already have a good alternative like in this case.

I took some liberties when rewriting the code and it's not tested. Not using a switch is nice because no branch :)
```cs
public static int DecodePaddedVarInt32(ReadOnlySpan<byte> span, bool checkOverflow, out uint result) 
{
    if (BitConverter.IsLittleEndian &&
        Bmi2.X64.IsSupported && 
        MemoryMarshal.TryRead(span, out ulong encoded))
    {
        uint highMask = Vector128.CreateScalar(encoded).AsByte().ExtractMostSignificantBits();
        uint maxMask = highMask & 0b11111; // Process 5 bytes at most
        int byteCount = BitOperations.TrailingZeroCount(~maxMask);
        
        // There are 3 leading bits (7b per B * 5B = 35b, 35-32=3).
        // The current mask extracts 35 bits so we can check overflow,
        // but it could be 0x0F_7F_7F_7F_7FU (32 bits) otherwise.
        ulong valueBits = Bmi2.X64.ParallelBitExtract(encoded, 0x7F_7F_7F_7F_7FU);
        if (checkOverflow)
        {
            result = checked((uint)valueBits);
        }
        else 
        {
            result = (uint)valueBits;
        }
        return byteCount;
    }
    result = 0;
    return 0;
}
```

**Comment by mgravell** [comment]
You're right, `CreateScalar` is the more appropriate route here. Nice example implementation, @TechPizzaDev! Not a criticism, purely for reference for any other readers - needs a little fixup, most notably:

```
int byteCount = BitOperations.TrailingZeroCount(~maxMask) + 1;

ulong valueBits = Bmi2.X64.ParallelBitExtract(encoded, 0x7F_7F_7F_7F_7FU >> ((5 - byteCount) << 3));
if (byteCount == 5)
```

(off-by-one on the byte count, we need to not extract bytes that weren't requested, and the overflow condition is tied to the number of bytes)

results (annoyingly worse in the length 1 scenario, I can work on that, but otherwise: very nice):

``` txt
| Method   | Scenario   | Mean      | Error     | StdDev    | Ratio | RatioSD |
|--------- |----------- |----------:|----------:|----------:|------:|--------:|
| Existing | 01         | 0.3191 ns | 0.0048 ns | 0.0042 ns |  1.00 |    0.02 |
| Proposed | 01         | 0.7784 ns | 0.0045 ns | 0.0037 ns |  2.44 |    0.03 |
|          |            |           |           |           |       |         |
| Existing | 9601       | 1.3494 ns | 0.0061 ns | 0.0058 ns |  1.00 |    0.01 |
| Proposed | 9601       | 0.7783 ns | 0.0086 ns | 0.0080 ns |  0.58 |    0.01 |
|          |            |           |           |           |       |         |
| Existing | 969601     | 1.5429 ns | 0.0060 ns | 0.0053 ns |  1.00 |    0.00 |
| Proposed | 969601     | 0.7689 ns | 0.0038 ns | 0.0036 ns |  0.50 |    0.00 |
|          |            |           |           |           |       |         |
| Existing | 96969601   | 1.9163 ns | 0.0072 ns | 0.0064 ns |  1.00 |    0.00 |
| Proposed | 96969601   | 0.7728 ns | 0.0061 ns | 0.0057 ns |  0.40 |    0.00 |
|          |            |           |           |           |       |         |
| Existing | 9696969601 | 2.1137 ns | 0.0110 ns | 0.0103 ns |  1.00 |    0.01 |
| Proposed | 9696969601 | 0.8964 ns | 0.0027 ns | 0.0025 ns |  0.42 |    0.00 |
```

**Comment by TechPizzaDev** [comment]
I actually used a mask once but removed it and forgot to add it back in. My mask was `valueBits & ((1 << (byteCount * 7) - 1)`, which should very slightly reduce latency/time since `pext` can get to work earlier.

That was the reason for me using a constant in the bit extract; the instruction is extremely slow on many CPUs (anything before Zen3 for AMD is 250x slower..., Intel is much better in general), so I was thinking of writing some fallback that always extracts the max bits but I didn't come up with anything.

**Comment by mgravell** [comment]
in that case, it might make sense to explicitly use 32-bit `pext` when we can:

``` c#
            if (byteCount == 5)
            {
                ulong valueBits = Bmi2.X64.ParallelBitExtract(encoded, 0x7F_7F_7F_7F_7FU >> ((5 - byteCount) << 3));
                value = checked((uint)valueBits);
            }
            else
            {
                value = Bmi2.ParallelBitExtract((uint)encoded, 0x7F_7F_7F_7FU >> ((4 - byteCount) << 3));
            }
```

I'll also test that against masking *after* the `pext`, when the run finishes.

**Comment by mgravell** [comment]
32-bit `pext`:

```
| Method   | Scenario   | Mean      | Error     | StdDev    | Ratio |
|--------- |----------- |----------:|----------:|----------:|------:|
| Existing | 01         | 0.3225 ns | 0.0035 ns | 0.0031 ns |  1.00 |
| Proposed | 01         | 0.2970 ns | 0.0015 ns | 0.0012 ns |  0.92 |
|          |            |           |           |           |       |
| Existing | 9601       | 1.3534 ns | 0.0085 ns | 0.0079 ns |  1.00 |
| Proposed | 9601       | 0.7563 ns | 0.0028 ns | 0.0027 ns |  0.56 |
|          |            |           |           |           |       |
| Existing | 969601     | 1.5448 ns | 0.0060 ns | 0.0053 ns |  1.00 |
| Proposed | 969601     | 0.7564 ns | 0.0039 ns | 0.0037 ns |  0.49 |
|          |            |           |           |           |       |
| Existing | 96969601   | 1.9242 ns | 0.0091 ns | 0.0071 ns |  1.00 |
| Proposed | 96969601   | 0.7565 ns | 0.0051 ns | 0.0047 ns |  0.39 |
|          |            |           |           |           |       |
| Existing | 9696969601 | 2.1146 ns | 0.0105 ns | 0.0093 ns |  1.00 |
| Proposed | 9696969601 | 0.7054 ns | 0.0057 ns | 0.0050 ns |  0.33 |
```

32-bit `pext` and mask `pext` result instead of input i.e.

``` c#
            if (byteCount == 5)
            {
                ulong valueBits = Bmi2.X64.ParallelBitExtract(encoded, 0x7F_7F_7F_7F_7FU)
                    & ((1UL << (byteCount * 7)) - 1);
                value = checked((uint)valueBits);
            }
            else
            {
                value = Bmi2.ParallelBitExtract((uint)encoded, 0x7F_7F_7F_7FU)
                    & ((1U << (byteCount * 7)) - 1);
            }
```

:

``` txt
| Method   | Scenario   | Mean      | Error     | StdDev    | Ratio | RatioSD |
|--------- |----------- |----------:|----------:|----------:|------:|--------:|
| Existing | 01         | 0.3100 ns | 0.0042 ns | 0.0040 ns |  1.00 |    0.02 |
| Proposed | 01         | 0.2881 ns | 0.0005 ns | 0.0004 ns |  0.93 |    0.01 |
|          |            |           |           |           |       |         |
| Existing | 9601       | 1.3517 ns | 0.0056 ns | 0.0053 ns |  1.00 |    0.01 |
| Proposed | 9601       | 0.8838 ns | 0.0038 ns | 0.0036 ns |  0.65 |    0.00 |
|          |            |           |           |           |       |         |
| Existing | 969601     | 1.5471 ns | 0.0090 ns | 0.0079 ns |  1.00 |    0.01 |
| Proposed | 969601     | 0.8801 ns | 0.0024 ns | 0.0018 ns |  0.57 |    0.00 |
|          |            |           |           |           |       |         |
| Existing | 96969601   | 1.9190 ns | 0.0071 ns | 0.0063 ns |  1.00 |    0.00 |
| Proposed | 96969601   | 0.8836 ns | 0.0039 ns | 0.0030 ns |  0.46 |    0.00 |
|          |            |           |           |           |       |         |
| Existing | 9696969601 | 2.1110 ns | 0.0061 ns | 0.0057 ns |  1.00 |    0.00 |
| Proposed | 9696969601 | 0.7601 ns | 0.0032 ns | 0.0029 ns |  0.36 |    0.00 |
```

although it is weird that the 5-byte run  is now *faster* than the 2/3/4 runs. Microbenchmarking is fun.

**Comment by tannergooding** [comment]
For additional context, `MMX` uses an artificial 64-bit view over the x87 FPU unit (80-bit registers).

Using it comes with strict requirements and is no longer recommended by both the Intel and AMD optimization manuals. Rather instead it's recommended to use the relevant SSE or later instructions instead. The few interop instructions that were added to SSE/SSE2 were correspondingly not exposed by design and there are no plans to expose them in the future as it leads users into a pit of failure.

If you truly need to use SIMD instructions to operate on a scalar 64-bit value, it's recommended you use one of the `CreateScalar` APIs and then using the relevant instructions. Beyond that, however, its recommended to use an alternative sequence where possible. In many cases, however, this isn't strictly needed and there are much more suitable alternatives instead. For example, the only extra thing that `MoveMask` does is that it compresses the bits into a sequential set. This is often unnecessary and can simply be accounted for with a mask and `tzcnt`/`lzcnt`/`popcnt` and similar instead (accounting for the need ignore 7 extra bits for every one you check). It really just depends on the exact scenario you're wanting to handle.
