### ISSUE TITLE
Change/Remove ClientWebSocket ping packet body

### ISSUE THREAD

**Issue by zxcvqwerasdf** [dotnet/runtime#110158]
As i know, there is no way send ping's with ClientWebSocket directly, only by using
```
_webSocket.Options.KeepAliveInterval
```
But it's sends integer in body
![Image](https://github.com/user-attachments/assets/ead66e46-8a7a-4265-8960-034a604c61d2)
Can you add feature to do not send ping packet body? Only ping opcode?
Thank you.

**Comment by MihaZupan** [comment]
Why do you care whether the extra bytes are sent?

**Comment by zxcvqwerasdf** [comment]
Sorry, checked it in 2 another local proxies and there is no these headers

**Comment by zxcvqwerasdf** [comment]
> Why do you care whether the extra bytes are sent / what's the motivation to avoid it?
I am using custom ping/pong on the server and i need custom data in ping message

**Comment by CarnaViire** [comment]
> custom ping/pong on the server

_// TL;DR: Custom Ping/Pong on the server could only apply to server's Pings, it is fully independent from what the client sends in the client's Pings._

@zxcvqwerasdf 
Ping/Pongs _initiated_ from the _client_ side and from the _server_ side are two separate things.

By [RFC](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.3), the _receiver_ of a Ping frame MUST echo back the data in the Pong response:

```
   A Pong frame sent in response to a Ping frame must have identical
   "Application data" as found in the message body of the Ping frame
   being replied to.
```

What that means:

1) If Ping/Pongs are initiated from the _client_ side:
   - the server must echo the data back, and there could be _nothing custom_ about it. Imagine your server will also have another client that is _not_ on .NET -- this client would be free to send whatever (fitting the RFC requirements), and the server must comply.

2) If Ping/Pongs are initiated from the _server_ side:
   - it only matters what ClientWebSocket _responds_ in the _Pong_ frame. And it will, as well, echo back whatever custom data the server sent in the server's Ping.

**Comment by MihaZupan** [comment]
> custom data in ping message

What sort of information would you want to transmit?
What's the motivation behind using pings instead of regular messages? Note that the size of ping data is very limited whereas regular messages can be arbitrarily large.
