### ISSUE TITLE
JIT: superpmi-replay failing on win-x64 with crashes

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#110145]
supermpi-replay is currently failing for win-x64 replay with some form of crash.

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
I'm looking...

**Comment by jakobbotsch** [comment]
It seems like there is something wrong with the currently uploaded asp.net collection, probably it was produced by some wrong JIT? I deleted it from the storage manually.

**Comment by AndyAyersMS** [comment]
> something wrong with the currently uploaded asp.net, , probably it was produced by some wrong JIT?

Odd... not sure how that could have happened.

**Comment by jakobbotsch** [comment]
Confirmed from recent superpmi-replay runs that this is fixed now.
