### ISSUE TITLE
HttpWebClient always send Cache-Control and Pragma headers when proxy used

### ISSUE THREAD

**Issue by zxcvqwerasdf** [dotnet/runtime#110164]
I tried different ways, but when you use HttpClient with Proxy you will get Cache-Control: no-cache and Pragma: no-cache in request headers.
It's possible to prevent it? I don't need these headers when using proxy.

**Comment by MihaZupan** [comment]
HttpClient on its own will not inject these headers. Could it be that whatever proxy server you're using is doing so for you?

**Comment by zxcvqwerasdf** [comment]
> HttpClient on its own will not inject these headers. Could it be that whatever proxy server you're using is doing so for you?

```
 var socketHandler = new SocketsHttpHandler
 {
     AllowAutoRedirect = false,
     UseCookies = false,
     UseProxy = true
     Proxy = new WebProxy($"http://{proxy.host}:{proxy.port_http}");
 };

 var httpClient = new HttpClient(socketHandler, true);
 HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, URL);
 request.Version = new Version(1, 1);
 var response = await httpClient.SendAsync(request);
```

If you will use local proxy, you will find these headers
![Image](https://github.com/user-attachments/assets/bd359169-e384-4683-af62-942491c116a1)
in request


but if you change
```
UseProxy = false
```
there will be no these headers (you can check it by writing some server that check request header/print it in response headers)

**Comment by zxcvqwerasdf** [comment]
Sorry, checked it in 2 another local proxies and there is no these headers
