### ISSUE TITLE
Process.Start() creates additional process named conhost.exe

### ISSUE THREAD

**Issue by dooann** [dotnet/runtime#110116]
I found that the `Process.Start()` creates additional process named `conhost.exe` for each call while the `subprocess` module in python is not.

Each instance of conhost.exe consumes approximately 5.7 MB of memory, which limits the level of concurrency.

It also affects the pwsh scripts. Actually, I found this issue when writing the pwsh script.

My questions are:
1. Is `conhost.exe` necessary for starting a process? If so, why?
2. Can we remove `conhost.exe` or provide an option to control its behavior?

Thanks.

``` C#
var info = new ProcessStartInfo("ping") {
    RedirectStandardOutput = true,
    RedirectStandardError = true,
    UseShellExecute = false,
    CreateNoWindow = true,
    Arguments = "google.com"
};

var process = Process.Start(info);
```
.Net version: 8.0.401

``` python
subprocess.run(['ping', 'google.com'])
```
Python version: Python 3.12.3

**Comment by stephentoub** [comment]
Closing as answered
