### ISSUE TITLE
`Matrix4x4.CreateTranslation` The result is flipped over?

### ISSUE THREAD

**Issue by Coloryr** [dotnet/runtime#110170]
I try to create a `Matrix4x4`

```
Matrix4x4.CreateTranslation(300, 300, 0);
```

the value is 
```
{{ {M11:1 M12:0 M13:0 M14:0}
 {M21:0 M22:1 M23:0 M24:0}
 {M31:0 M32:0 M33:1 M34:0}
 {M41:300 M42:300 M43:0 M44:1} }}
```
but i saw some doc say it should be
```
{{ {M11:1 M12:0 M13:0 M14:300}
 {M21:0 M22:1 M23:0 M24:300} 
{M31:0 M32:0 M33:1 M34:0}
 {M41:0 M42:0 M43:0 M44:1} }}
```

![Image](https://github.com/user-attachments/assets/744e3ac7-0dc4-4d40-998d-c6982b69da88)

![Image](https://github.com/user-attachments/assets/0fd6ad86-7ce0-4a31-bda3-f2f531f3a914)

**Comment by EgorBo** [comment]
> but i saw some doc say it should be

It's just a different order, see https://en.wikipedia.org/wiki/Row-_and_column-major_order
In case of .NET, it's column-major order here.

**Comment by Coloryr** [comment]
Thanks
