### ISSUE TITLE
Microsoft.Extensions.Http is not being copied

### ISSUE THREAD

**Issue by santo998** [dotnet/runtime#110213]
### Description

I have a DLL which uses Microsoft.Extensions.Http.

Then, I have a project which references my DLL.

When I run my project, it throws the exception:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
...

If I reference Microsoft.Extensions.Http nuget from my project, it doesn't.

But, I shouldn't have to, because it doesn't reference it directly.

I think making the nuget package being transitive or copying the Microsoft.Extensions.Http DLL in some way via nuget would resolve this, so that's why I'm creating this issue.

### Reproduction Steps

Have a DLL which references Microsoft.Extensions.Http, implement some method which uses that nuget package and call that method from another project.

### Expected behavior

The project runs

### Actual behavior

Exception thrown

### Known Workarounds

Including direct reference to the nuget package from the project

### Configuration

I'm running .NET 8 and referencing Microsoft.Extensions.Http 9.0.0

**Comment by huoyaoyuan** [comment]
How are you referencing your dll?

> I think making the nuget package being transitive or copying the Microsoft.Extensions.Http DLL in some way via nuget would resolve this

If you are using ProjectReference or packaging nuget properly, the dependency will be transitive.

**Comment by ViktorHofer** [comment]
Please share a repro. Nuget dependencies are transitive by default.

**Comment by santo998** [comment]
[ConsoleApp1.zip](https://github.com/user-attachments/files/17939798/ConsoleApp1.zip)

@ViktorHofer here is a sample solution where the exception is thrown.

Notice the class library is referenced as assembly, and not as a project.

Also, the Microsoft.Extensions.Http nuget isn't referenced as transitive in the console app project.

Even more, and probably related to this:
In Program.cs there isn't a using to the custom extension method I defined.

**Comment by huoyaoyuan** [comment]
> Notice the class library is referenced as assembly, and not as a project.

It's not recommended, and will never work as intended. Assembly is a lower level concept than projects or packages, it's doesn't have information about packages.

**Comment by ViktorHofer** [comment]
@santo998 as @huoyaoyuan mentioned, using `Reference` doesn't flow package references transitively. We recommend using `ProjectReference` here which also handles building the project as a dependency of the console app.
