### ISSUE TITLE
`JsonSourceGenerator` can fail with `global using` aliases

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/runtime#110242]
### Description

Under some particular conditions, `JsonSourceGenerator` can fail with the following warning:

> CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Unreachable'.

### Reproduction Steps

Build the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>
</Project>
```

```csharp
global using Foo = object;
```

### Expected behavior

I do realize that net6.0 + C# 13 is not officially supported, but I didn't expect a source generator to fail. I expected this to compile successfully without warnings.

### Actual behavior

This compiles successfully but `JsonSourceGenerator` fails.

The stack trace in the binlog is:

```
System.InvalidOperationException: Unreachable
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.RoslynExtensions.GetUnqualifiedName(NameSyntax name)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.CSharpSyntaxHelper.AddAliases(SyntaxList`1 usings, ValueListBuilder`1& aliases, Boolean global)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.CSharpSyntaxHelper.AddAliases(SyntaxNode node, ValueListBuilder`1& aliases, Boolean global)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.SyntaxValueProviderExtensions.<ForAttributeWithSimpleName>g__getGlobalAliasesInCompilationUnit|5_7(SyntaxNode compilationUnit)
at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
```

### Regression?

I don't know. I was introducing this `global using` alias.

### Known Workarounds

- using `System.Object` instead of `object` in the alias
- targeting a different framework version than `net6.0`

I suspect the generator doesn't handle keywords in `global using` aliases.

### Configuration

Tested on Windows 11 x64 and Linux x64 (Ubuntu WSL) with the .NET 9 SDK:

.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

### Other information

I stumbled upon this by writing the following code in a multi-targeted project:

```csharp
﻿#if NET9_0_OR_GREATER
global using Lock = System.Threading.Lock;
#else
global using Lock = object;
#endif
```

Using `System.Object` fixed the issue.

**Comment by MichalPetryka** [comment]
> I do realize that net6.0 + C# 13 is not officially supported, but I didn't expect a source generator to fail. I expected this to compile successfully without warnings.

.NET 6 is out of support now so unless the issue also reproduces on .NET 8, it won't be actioned on.
