### ISSUE TITLE
The name passed to `DbProviderFactories.GetFactory` is case sensitive but the error message indicates the name is "invariant" which isn't correct

### ISSUE THREAD

**Issue by icnocop** [dotnet/runtime#110236]
### Description

In .NET Framework the data provider factory name is case insensitive, but in .NET 8 at least, the name is now case sensitive, but the error message hasn't been updated to reflect the breaking change.

### Reproduction Steps

`<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />`

```
DbProviderFactories.RegisterFactory("System.Data.SqlClient", Microsoft.Data.SqlClient.SqlClientFactory.Instance);

DbProviderFactory factory = DbProviderFactories.GetFactory("system.data.sqlclient");
```

### Expected behavior

I expected the provider name to not be case sensitive, or the error message to be updated.

### Actual behavior

```
System.ArgumentException: The specified invariant name 'system.data.sqlclient' wasn't found in the list of registered .NET Data Providers.
Stack Trace: 
DbProviderFactories.GetFactory(String providerInvariantName, Boolean throwOnError)
DbProviderFactories.GetFactory(String providerInvariantName)
```

### Regression?

Yes, it worked in .NET Framework 4.7.2.

### Known Workarounds

As a work-around, register providers using all lower-case characters, and then call `DbProviderFactory factory = DbProviderFactories.GetFactory(providerName.ToLower());` for example.

### Configuration

.NET 8
Windows 10 64-bit

### Other information

https://github.com/dotnet/runtime/blob/af3393d3991b7aab608e514e4a4be3ae2bbafbf8/src/libraries/System.Data.Common/src/System/Data/Common/DbProviderFactories.cs#L154

https://github.com/dotnet/dotnet/blob/83244d9bd58049da40ce5a822579735dc8ba1f4d/src/runtime/src/libraries/System.Data.Common/src/System/Data/Common/DbProviderFactories.cs#L154

**Comment by roji** [comment]
Makes sense, looks like the error message needs to be fixed.

**Comment by roji** [comment]
@KalleOlaviNiemitalo agreed about invariant, but the exception message seems to show a lower-case version of the invariant name `system.data.sqlclient`, which seems wrong.

**Comment by roji** [comment]
@KalleOlaviNiemitalo oh I see - I read the original issue a bit too quickly, thanks for correcting me on that.

@icnocop if your suggestion/request is indeed to update the exception message to remove the word "invariant" there, then as @KalleOlaviNiemitalo wrote above, invariant does not mean "case-insensitive", and it makes for it to stay there. I'll go ahead and close this issue with that assumption, but feel free to post back here if I've misunderstood or you have further comments.
