### ISSUE TITLE
Error restoring WebAPI project using .NET 9

### ISSUE THREAD

**Issue by FraserElectronics** [dotnet/runtime#110201]
I have created a WebAPI on a Linux machine using:

```
dotnet new webapi -n myapp.
```

I wish to host this API in a docker container so I have followed the instructions here: [https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-9.0](link) 

When I run ```docker build -t myapp .``` I get the error:

```
error NETSDK1045: The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0.
```
If I list the installed sdk's with dotnet --list-sdks I get:

```
9.0.100 [/usr/lib/dotnet/sdk]
```
What am I missing?

Andy

**Comment by julealgon** [comment]
@FraserElectronics do you have a `global.json` file in your solution?

**Comment by vcsjones** [comment]
The Dockerfile on the linked page might need to be updated. It has a line like this:

> `FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build`

If you are using .NET 9, which it looks like you are, you should change the version numbers in the Dockerfile to 9.0 instead of 8.0.

**Comment by Clockwork-Muse** [comment]
Side note: recent version of the SDK have [build-pack-like capabilities](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container) (if not using that tool itself), so you probably don't need to write/maintain the dockerfile yourself.  Unless you're doing something unusual, you probably want to do that instead.

**Comment by FraserElectronics** [comment]
@julealgon No, there is no global.json file in my solution - do I need one?
@vcsjones Thanks for that, I had completely missed the SDK specified in Dockerfile, I was thinking it was an issue with my Linux install.

Thanks all for the help.

Andy

**Comment by julealgon** [comment]
> [@julealgon](https://github.com/julealgon) No, there is no global.json file in my solution - do I need one?

@FraserElectronics Nah you don't need one. I was just wondering if maybe that could be a reason why it was trying to use a different version of the SDK, because you can do stuff like that with a `global.json` file.
