### ISSUE TITLE
Incorrect Parameter Order in ArgumentException Constructor in IfNullOrWhitespace Method

### ISSUE THREAD

**Issue by jgador** [dotnet/runtime#110294]
### Description

The `IfNullOrWhitespace` method in `System.ThrowHelper` uses the `ArgumentException` with the parameters in the wrong order. Currently, it has:

```csharp
throw new ArgumentException(paramName, "Argument is whitespace");
```
However, the correct order for `ArgumentException` parameter is:
1. message
2. paramName

It should be:
```csharp
throw new ArgumentException("Argument is whitespace", paramName);
```

Proposed Fix
Swap the parameters in the `ArgumentException` constructor to the correct order:
```csharp
throw new ArgumentException("Argument is whitespace", paramName);
```

### Reproduction Steps

1. Locate the `IfNullOrWhitespace` method in the `System.ThrowHelper` class.
2. Observe the `throw new ArgumentException` statement.
3. Note that the message and parameter name are swapped

### Expected behavior

The `ArgumentException` constructor should follow the correct order:

- First parameter: error message
- Second parameter: offending parameter name

### Actual behavior

The error message is being passed as the parameter name, and the parameter name is passed as the error message.

**Comment by huoyaoyuan** [comment]
It is intentional to use a different order, because the `paramName` parameter is now optional and can be inferred by compiler. It does not intend to follow the existing order of constructors, which is already inconsistent in `ArgumentNullException`, `ArgumentException` and `ArgumentOutOfRangeException`.

**Comment by danmoseley** [comment]
As mentioned, it's arguably a historical mistake in the constructors. Would be a hugely breaking change, so not acceptable.

At one point there was discussion of an analyzer that would use a heuristic to check whether they were reversed - eg param name should not have spaces in. Not sure whether we did that.
