### ISSUE TITLE
CreateDelegate is failing for value/struct types after upgrade to 9.0

### ISSUE THREAD

**Issue by ackava** [dotnet/runtime#110280]
### Description

`Delegate.CreateDelegate` method fails with an error "Cannot bind to the target method because its signature is not compatible with that of the delegate type.".

The same code was working earlier in .NET 8.

### Reproduction Steps

```c#
Type type = typeof(Guid);

var method = type.GetProperty("Variant");

var fx = method.GetMethod.CreateDelegate<Func<Guid,int>>();

var g = Guid.NewGuid();

var v = fx(g);

```

### Expected behavior

Method should create a new delegate.

### Actual behavior

Method fails with an error "Cannot bind to the target method because its signature is not compatible with that of the delegate type."

### Known Workarounds

Currently there is no alternative except using reflection to invoke method, but this slows down the performance.

### Configuration

.NET 9 Console App

### Other information

I looked upon all breaking changes, there is no mention of `Delegate.CreateDelegate` for any changes in API or any other alternative.

**Comment by hez2010** [comment]
Your code is incorrect, and it doesn't work on any version of .NET already.
While invoking a method which has a value type as `this`, the `this` argument needs to be passed by ref.

The code should be like this:

```cs
Type type = typeof(Guid);

var method = type.GetProperty("Variant");

var fx = method.GetMethod.CreateDelegate<GetVariant>();

var g = Guid.NewGuid();

var v = fx(ref g);

delegate int GetVariant(ref Guid guid);
```

**Comment by ackava** [comment]
@hez2010 Thanks, I will update the code accordingly.
