### ISSUE TITLE
build hit error ijw.cpp(19): error C3611: “System::Numerics::INumb   erBase::System::IUtf8SpanFormattable.TryFormat”: 密封函数不能具有纯说明符

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#110243]
I build v9.0.0 tag local.
hit the ijw.cpp(19): error C3611: “System::Numerics::INumberBase::System::IUtf8SpanFormattable.TryFormat”: 密封函数不能具有纯说明符

I have upgrade vs to 17.12.2 version  and  install the c++/cli to 143 latest version

![Image](https://github.com/user-attachments/assets/d2f61ade-22ad-4d2d-92ef-ba0977b0cc5a)

the compiler version show below:
```
** Visual Studio 2022 Developer Command Prompt v17.12.2
  ** Copyright (c) 2022 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x64'
  BUILD: Regenerating the Visual Studio solution
  Calling "E:\work\netease-gitlab\dotnet\runtime\eng\native\gen-buildsys.cmd" "E:\work\netease-gitlab\dotnet\runtime\src\coreclr" "E:\work\netease-gitlab\dotnet\runtime\artifacts\obj\coreclr\windows.x64.Debug" vs2022 x64 windows "-DCMAKE_BUILD_TYPE=Debug" "-DCLR_CMAKE_TARGET_ARCH=x64" "-DCLR_CMAKE_TARGET_OS=windows" "-DCLI_CMAKE_FALLBACK_OS=win10" "-DCLR_CMAKE_PGO_INSTRUMENT=0" "-DCLR_CMAKE_OPTDATA_PATH=" "-DCLR_CMAKE_PGO_OPTIMIZE=0" "-DCDAC_BUILD_TOOL_BINARY_PATH=E:\work\netease-gitlab\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Debug\cdac-build-tool\cdac-build-tool.dll" "-DCLR_DOTNET_HOST_PATH=E:\work\netease-gitlab\dotnet\runtime\.dotnet\dotnet.exe" 
  Not searching for unused variables given on the command line.
  -- The C compiler identification is MSVC 19.36.32546.0
  -- The CXX compiler identification is MSVC 19.36.32546.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The ASM_MASM compiler identification is MSVC
  -- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/ml64.exe
  -- Performing Test HAVE_DIRENT_D_TYPE
  -- Performing Test HAVE_DIRENT_D_TYPE - Failed
  -- Looking for getauxval
  -- Looking for getauxval - not found
  -- Looking for include file GSS/GSS.h
  -- Looking for include file GSS/GSS.h - not found
  -- Using CMake version 3.27.2
```

**Comment by srxqds** [comment]
the full build log [log.txt](https://github.com/user-attachments/files/17948377/log.txt)

**Comment by MichalPetryka** [comment]
Duplicate of #94998, .NET 8+ requires at least C++/CLI v14.38.

**Comment by srxqds** [comment]
> Duplicate of [#94998](https://github.com/dotnet/runtime/issues/94998), .NET 8+ requires at least C++/CLI v14.38.

I think you didn't look carefully the log details. and I have install the v143 c++/cli latest tools， you can find the picture shot.

**Comment by MichalPetryka** [comment]
> > Duplicate of [#94998](https://github.com/dotnet/runtime/issues/94998), .NET 8+ requires at least C++/CLI v14.38.
> 
> I think you didn't look carefully the log details. and I have install the v143 c++/cli latest tools， you can find the picture shot.

Your VS has 14.36 installed and is using that for the build according to your log.

**Comment by srxqds** [comment]
> that for the build according

ok, but how can I solving it, due to I have installed v143 c++/cli latest tools

**Comment by srxqds** [comment]
I have use `Developer Command Prompt for vs2022`, the error have gone. but how can I solving it without use the Prompt commandline

**Comment by srxqds** [comment]
> > > Duplicate of [#94998](https://github.com/dotnet/runtime/issues/94998), .NET 8+ requires at least C++/CLI v14.38.
> > 
> > 
> > I think you didn't look carefully the log details. and I have install the v143 c++/cli latest tools， you can find the picture shot.
> 
> Your VS has 14.36 installed and is using that for the build according to your log.

"Your VS has 14.36 installed" this is beacuse it hit the error before I installed the 14.36 version, so I try install this version.

so maybe the problem is the build script didn't use the latest tools.

**Comment by huoyaoyuan** [comment]
> I have use `Developer Command Prompt for vs2022`, the error have gone. but how can I solving it without use the Prompt commandline

In this case you should probably check your environment variables, or use `where.exe` to find which version of commands are used.

**Comment by huoyaoyuan** [comment]
Additionally, why do you need to select 17.36 version of C++/CLI along with latest version? The latest version is 17.42 currently.

**Comment by srxqds** [comment]
> Additionally, why do you need to select 17.36 version of C++/CLI along with latest version? The latest version is 17.42 currently.

unrealengine project need the 17.36 version

**Comment by tannergooding** [comment]
As per the above, .NET 8 requires at least C++/CLI v14.38. .NET 9 requires at least the same, but may itself require something even newer in some scenarios.

You would need to upgrade to at least `v14.38` and check if Unreal will work with this or if it actually requires exactly `v14.36`. If Unreal engine does actually require `v14.36` and is incompatible with `v14.38` and later, then you will not be able to use .NET 8/9 with your C++/CLI project

**Comment by srxqds** [comment]
> As per the above, .NET 8 requires at least C++/CLI v14.38. .NET 9 requires at least the same, but may itself require something even newer in some scenarios.
> 
> You would need to upgrade to at least `v14.38` and check if Unreal will work with this or if it actually requires exactly `v14.36`. If Unreal engine does actually require `v14.36` and is incompatible with `v14.38` and later, then you will not be able to use .NET 8/9 with your C++/CLI project

ok，hope you can upgrade the docs
