### ISSUE TITLE
JsonSchemaExporter modifies the static JsonSchema.True when there is a custom converter and TransformSchemaNode is set

### ISSUE THREAD

**Issue by desjoerd** [dotnet/runtime#110241]
### Description

When exporting a JsonSchema with the `System.Text.Json.Schema.JsonSchemaExporter` with a model containing types with a custom json converter, the static `System.Text.Json.Schema.JsonSchema.True` json schema is modified when there is a `TransformSchemaNode` set on the `JsonSchemaExporterOptions`.

The modification seems to happen in the local function `CompleteSchema` in `JsonSchemaExporter.MapJsonSchemaCore`, and it modifies the static True schema because in the `default:` case (which is executed when there is a custom converter) the static `True` version is passed in.

### Reproduction Steps

Example Program.cs showing the side-effect, as `JsonSchema.True` is `internal`

```csharp
using System.Text.Json;
using System.Text.Json.Schema;
using System.Text.Json.Serialization;

var exporterOptions = new JsonSchemaExporterOptions
{
    TransformSchemaNode = (context, node) =>
    {
        Console.WriteLine($"{context.TypeInfo.Type.FullName}, prop: {context.PropertyInfo?.Name}");
        return node;
    }
};

var schema = JsonSchemaExporter.GetJsonSchemaAsNode(JsonSerializerOptions.Default, typeof(Example), exporterOptions);
Console.WriteLine(schema);

public class Example
{
    public Foo Foo { get; set; }

    public Bar Bar { get; set; }
}

[JsonConverter(typeof(FooJsonConverter))]
public class Foo;

[JsonConverter(typeof(BarJsonConverter))]
public class Bar;

public class FooJsonConverter : JsonConverter<Foo>
{
    public override Foo? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => throw new NotImplementedException();
    public override void Write(Utf8JsonWriter writer, Foo value, JsonSerializerOptions options) => throw new NotImplementedException();
}


public class BarJsonConverter : JsonConverter<Bar>
{
    public override Bar? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => throw new NotImplementedException();
    public override void Write(Utf8JsonWriter writer, Bar value, JsonSerializerOptions options) => throw new NotImplementedException();
}
```

Output:
```
Bar, prop: Bar
Bar, prop: Bar
Example, prop: 
{
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "Foo": true,
    "Bar": true
  }
}
```

### Expected behavior

Expected behavior is that

1. TransformSchemaNode would get a different property info for each property in an object.
2. `JsonSchemaExporter.GetJsonSchemaAsNode` is not modifying `JsonSchema.True` becuase that creates side-effects and does make this unsafe with multiple threads

### Actual behavior

When debugging the above example I could see the `JsonSchema.ExporterContext` being modified for the static `JsonSchema.True` property. This causes side-effects.

### Regression?

I suspect not, because the JsonSchemaExporter is introduced in .NET 9

### Configuration

```
dotnet --version
9.0.100
```

### Other information

Related issue on aspnetcore, OpenApi -> https://github.com/dotnet/aspnetcore/issues/59172

**Comment by desjoerd** [comment]
Ok, after some more searching and looking at the current state of the repository, it's this solved issue https://github.com/dotnet/runtime/issues/109868. Closing.

**Comment by eiriktsarpalis** [comment]
You beat me to it. Fix should be made available in the upcoming servicing release.

**Comment by desjoerd** [comment]
I was already thinking you've got a bot doing a thumbsup, I posted it and it got a reaction!
