### ISSUE TITLE
Suggestion: Add RuntimeHelpers.IsDefaultComparable<T>() : bool

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#11035]
This would return true iff the type _T_ is comparable using simple `memcmp` semantics. For instance, the primitive integral types would qualify, as would enums. Types with custom equality operators or which have overridden the `Equals` method would not qualify.

The scenario is that it would simply code like that at https://github.com/dotnet/coreclr/blob/1456a38ed9ee3eda8022b9f162a45334723a0d7a/src/System.Private.CoreLib/shared/System/MemoryExtensions.cs#L191-L206. Currently this code special-cases only `byte` and `char`, but it misses `sbyte`, `ushort`, `short`, enums, and custom structs which are simple wrappers around these types. It would be nice to be able to write something like this:

```cs
if (RuntimeHelpers.IsDefaultComparable<T>()) {
  if (Unsafe.SizeOf<T>() == sizeof(byte)) {
    // pretend that T is byte, even if it's a different type
    return ...;
  } else if (Unsafe.SizeOf<T>() == sizeof(char)) {
    // pretend that T is char, even if it's a different type
    return ...;
  }
}

// If reached this point, do element-by-element comparison
return ...;
```

This will especially come in handy if we introduce a `Utf8Char` type in the future, as extension methods on `ReadOnlySpan<Utf8Char>` would be able to go down the fast paths without the underlying code having special-cased `T = Utf8Char`.

**Comment by reflectronic** [comment]
> Note that I'm not suggesting a public API be added

Seems like this can be closed, then? We have had `RuntimeHelpers.IsBitwiseEquatable` for a number of releases now and are making use of it in places like IndexOf.
