### ISSUE TITLE
Reconsider deleting `linux-instructions.md` and related files

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#110324]
I just noticed https://github.com/dotnet/runtime/pull/107415/files. It deleted a bunch of long-standing files. I expect it broke a ton of links. I've used those links from lots of places. The typical approach is to leave the files and then add links to the new place.

I noticed that there are lots of places within our own repo using the old links, such as https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/testing.md#requirements.

I'd like to see a follow-up PR to resolve this in some way.

@ivdiazsa

**Comment by ivdiazsa** [comment]
Oh I thought I had fixed the changes with the links. Leaving the old files too in this case would be redundant and potentially confusing, so I believe the best approach is to look for the broken links and change them accordingly. I will take a look to find them, but if you could leave here in another comment a list of all the broken links you encounter, that would be awesome. Thanks for bringing this to my attention @richlander!

**Comment by richlander** [comment]
We need to add those files back. We've had those files for years.

- https://github.com/search?q=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fblob%2Fmain%2Fdocs%2Fworkflow%2Fbuilding%2Fcoreclr%2Flinux-instructions.md&type=repositories
- https://grep.app/search?q=https%3A//github.com/dotnet/runtime/blob/main/docs/workflow/building

I'm sure you will be able to find all the links. VS/Code does a good job of finding them.

**Comment by ivdiazsa** [comment]
I will have to disagree on that one Rich. We've had them for years, but that doesn't mean they can't get outdated or that they can't be replaced as the product evolves. The new versions are more complete and get rid of redundant information. But don't worry, I will treat this links fix as a priority as the main goal of the docs refactoring was to improve the experience, and broken links do the opposite.
