### ISSUE TITLE
Local test run experience is systematically degrading

### ISSUE THREAD

**Issue by 4creators** [dotnet/runtime#11030]
Observing recent changes to the test run infrastructure I have been impacted by the following problems:

1. Test run startup is painfully slow
    1. Python script runs very slow and seems to be very inefficient (it may take up to 2 - 3 min before actual tests start
    2. Test discovery after CoreRun is launched takes ad infinitum in comparison to experience from before couple of weeks

2. Test run info:
    1. Std out info is polluted with multiple error messages from python script
    2. There is no summary table after test run if tests fail - it was possible so far to see breakdown of failing tests per XUnit wrapper

**Comment by AaronRobinsonMSFT** [comment]
This is referencing test infrastructure that has been replaced. Closing.
