### ISSUE TITLE
TensorTests.cs and Tensor.cs StdDev calculates Variance rather than Standard deviations

### ISSUE THREAD

**Issue by xela-trawets** [dotnet/runtime#110381]
### Description

The StdDev routine lacks a square root at the end. The test also lacks the square root.
Easy to fix, rename to Variance and add a new function to calaculate the STdDev by taking the square root.

However... This is normally* -( see what we did there) used for sample sets and not usually populations  So it might be best to add and option to define the sample or popukation usage,, but that is a nuance compare to delivering the wrong thing entirely. (difference being adjustment for degrees of freedom which is division by N or (N-1) - because estimating the mean "uses up" some fraction of the variation) 

### Reproduction Steps

Calculate the StdDev of almost anything 
        var t = Enumerable.Range(-32, 64).Select(x => 1.0 * x).ToArray();
        var tt = new ReadOnlyTensorSpan<double> (t.AsSpan()); 
        var s = Tensor.StdDev(tt);
        Console.WriteLine(s);
>341.25

### Expected behavior

Something like 18.47

 

### Actual behavior

341.25

### Known Workarounds

 Take the square root,

### Configuration

dotnet 9

**Comment by xela-trawets** [comment]
would you look at a PR for this?

**Comment by aloraman** [comment]
Btw, in *SqlServer*, for example, there are two different functions for calculating (un)biased standard deviation.
**StDev** computes unbiased version (with division by N-1, for population sample)
**StDevP** computes biased version (with division by N, for population, hence P in the name).

**Comment by lilinus** [comment]
> If the mean is calculated then the N-minus-one, (unbiased), method should be the default. That is the case in this routine.

Agreed, however, I think it should be clarified in the documentation to avoid confusion.
