### ISSUE TITLE
[API Proposal]: JsonUnmappedMemberHandling.DisallowExceptTypeDiscriminator

### ISSUE THREAD

**Issue by aetos382** [dotnet/runtime#110466]
### Background and motivation

If using `JsonUnmappedMemberHandling.Disallow`, an error will occur if there are properties in the JSON that cannot be mapped to objects.

However, it seems that the type discriminator properties used in polymorphic deserialization are not intended to be mapped to objects.

For this reason, I thought it would be useful to have an option that would behave in the same way as `JsonUnmappedMemberHandling.Disallow`, but would ignore type discriminator properties as an exception.

### API Proposal

```csharp
enum JsonUnmappedMemberHandling
{
    Skip,
    Disallow,
    DisallowExceptTypeDiscriminator // new
}
```

### API Usage

```csharp
var options = new JsonSerializerOptions
{
    UnmappedMemberHandling = JsonUnmappedMemberHandling.DisallowExceptTypeDiscriminator
};
```

```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonUnmappedMembeHandling(JsonUnmappedMemberHandling.DisallowExceptTypeDiscriminator)]
interface IData
{
}
```

```csharp
[JsonSourceGenerationOptions(
    UnmappedMemberHandling = JsonUnmappedMemberHandling.DisallowExceptTypeDiscriminator)]
partial class SerializerContext : JsonSerializerContext;
```

### Alternative Designs

Explicitly place the type identification property in the object.

```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonUnmappedMembeHandling(JsonUnmappedMemberHandling.Disallow)]
interface IData
{
    [JsonPropertyName("type")]
    public string Type { get; set; }
}
```

### Risks

Currently, there are some restrictions on type discriminator properties compared to other properties (ex. #110248).

However, in the future, if type discriminator properties can be deserialized in the same way as normal properties, this option may become useless.

**Comment by eiriktsarpalis** [comment]
Our plan per https://github.com/dotnet/runtime/issues/72170 is to completely disallow conflicts between the type discriminator and object properties:
```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
interface IData
{
    [JsonPropertyName("type")]
    public string Type { get; set; }
}
```
In that case, the setting you're proposing should not be necessary correct?

**Comment by aetos382** [comment]
In that case, if I use `JsonUnmappedMemberHandling.Disallow`, will there be no error even if there is no corresponding .NET property for the JSON type discriminator?

**Comment by eiriktsarpalis** [comment]
Like this you mean?

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

var result = JsonSerializer.Deserialize<Data>("{\"type\":\"foo\", \"value\": 42, \"extra\": \"extra\"}");
Console.WriteLine(result);

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(DerivedData), "foo")]
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
record Data(int value);

record DerivedData(int value, string extra) : Data(value);
```

**Comment by aetos382** [comment]
I close it because I can no longer reproduce it.
