### ISSUE TITLE
[Android] CoreCLR uses APIs available only since Android API28

### ISSUE THREAD

**Issue by grendello** [dotnet/runtime#110470]
CoreCLR currently defines the minimum Android API level to be 21, since this is also the base level used by [.NET for Android](https://github.com/dotnet/android).  While trying to build CoreCLR to target Android proper (and not `linux-bionic`), I ran into the issue of CoreCLR PAL [sources using `glob(3)`](https://github.com/dotnet/runtime/blob/8fca0a156dcbb1eba5c79e387a6d8f924bfdd3a6/src/coreclr/pal/src/file/find.cpp#L85) which is available on Android only starting with API28.

The simple fix is to bump the minimum API requirement to 28, however this may limit the reach of CoreCLR on Android devices.  If we don't want to do that, the `glob(3)` functionality would have to be implemented in-tree (or imported from another libc, for instance from musl or picolibc).

**Comment by janvorli** [comment]
It looks like the only use of the FindFirstFile / FindNextFile is in superpmi, so it should be easy to get rid of.

**Comment by janvorli** [comment]
I have removed the glob usage in #110797
