### ISSUE TITLE
IDN test failure on .NET 8.0

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#110499]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=888621
Build error leg or test failing: System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid
Pull request: https://github.com/dotnet/runtime/pull/110492

## Error Message

Expected IdnMapping.GetAscii("xn----ufo9661d.xn--r5gy929fhm4f") to throw an ArgumentException. Line Number: 6126

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "to throw an ArgumentException. Line Number: 6126",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

We made fixes last year that need to be backported to release/8.0. These probably should have been backported at the time of the earlier PR. Not a criticism but just an observation. This type of change typically affects all the distros in a staggered fashion and affects our LTS versions.

Related:

- https://github.com/dotnet/runtime/pull/105282
- https://github.com/dotnet/runtime/pull/110492

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=888621
**Error message validated:** `[Expected IdnMapping.GetAscii to throw an ArgumentException. Line Number: 6126`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 12/7/2024 3:35:12 AM UTC

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=888621
**Error message validated:** `[to throw an ArgumentException. Line Number: 6126`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 12/7/2024 3:36:45 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[894944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894944)|dotnet/runtime|[System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894944&view=ms.vss-test-web.build-test-results-tab&runId=23468262&resultId=129669)|dotnet/runtime#110651|
|[893697](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893697)|dotnet/runtime|[System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893697&view=ms.vss-test-web.build-test-results-tab&runId=23464864&resultId=132328)|dotnet/runtime#110651|
|[894059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894059)|dotnet/runtime|[System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894059&view=ms.vss-test-web.build-test-results-tab&runId=23438700&resultId=120377)|dotnet/runtime#109648|
|[893209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893209)|dotnet/runtime|[System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893209&view=ms.vss-test-web.build-test-results-tab&runId=23410904&resultId=120822)||
|[893212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893212)|dotnet/runtime|[System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893212&view=ms.vss-test-web.build-test-results-tab&runId=23410884&resultId=119930)||
|[888621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888621)|dotnet/runtime|[System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888621&view=ms.vss-test-web.build-test-results-tab&runId=23261692&resultId=115644)|dotnet/runtime#110492|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|5|6|

**Comment by jkotas** [comment]
@tarekgh It is not ok to use "Known Build Errors" to ignore deterministic failures introduced by the PR. Our goal is to have green CI. 

You should disable the failing test against an issue in situations like this instead.

**Comment by tarekgh** [comment]
@jkotas there is no change in the PR caused the failure. It is because the environment is now using an updated version of ICU which is causing the failure. So, there is no real product problem. We have fixed the test in main but back port the fix failed is failed. I am currently off, if I get a chance soon to log in will try to either port the fix manually or disable the test.

**Comment by tarekgh** [comment]
@jkotas I have created the PR https://github.com/dotnet/runtime/pull/110705.

CC @ericstj @carlossanlop if can help merging it when the CI finish.

**Comment by jkotas** [comment]
Thank you!
