### ISSUE TITLE
Uppercase

### ISSUE THREAD

**Issue by EbGu3** [dotnet/runtime#110446]
### Description

# Bug en deserializar

- La api me responde el contenido del `api response` pero no lo deserializa. Por lo que procedí a crear el objeto que estoy recibiendo y serializarlo. lo único diferente que observo son las mayúsculas. El nugget de `Newtonsoft.Json` lo hace sin ningún problema, pero `System.Text.Json` no  

- api response
```json
{
   "result":{
      "actualizada":true
   },
   "message":"¡Tabla, actualizada!",
   "description":"",
   "statusCode":200
}
```

- objeto seralizado
```json
{
   "Result":{
      "Actualizada":false
   },
   "Message":"",
   "Description":"",
   "StatusCode":0
}
```
- clase
```c#
    public class ResponseGeneric<T>
    {
        public required T Result    { get; set; }
        public string Message       { get; set; } = string.Empty;
        public string Description   { get; set; } = string.Empty;
        public int StatusCode       { get; set; }
    }

    public class Resultado
    {
        public bool Actualizado { get; set; }
    }
```

### Reproduction Steps

1. Realize una consulta a una api de c# en .net 8 usando el nugget `RestClientOptions`
2. Uso `JsonSerializer.Deserialize` para extraer la respuesta de la api

### Expected behavior

-

### Actual behavior

-

**Comment by Miizukii** [comment]
https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/character-casing
```c#
var options = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true
};
WeatherForecast? weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(jsonString, options);
```

**Comment by EbGu3** [comment]
Entiendo, agradezco. 🤭👍
Aun que siento que debe de ser un punto de mejora para la librería. Porque si lo uso 10 veces lo tendría que duplicar 10 veces.

**Comment by Miizukii** [comment]
You can create it once and reuse it. 
https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/configure-options#reuse-jsonserializeroptions-instances

**Comment by eiriktsarpalis** [comment]
Closing as answered.
