### ISSUE TITLE
How to use a custom source generator to inform the source generator of System.Text.Json to generate code for the corresponding class

### ISSUE THREAD

**Issue by RRQM** [dotnet/runtime#110428]
Objective:

I'd like to be able to use the System.Text.Json source generator to automatically generate code for the corresponding class, rather than manually adding the JsonSerializable feature.

Problem Description:

For example: For the following method

```
public void Test(MyClass myClass)
{

}
```

I have my own source generator that can search for the Test method and see that the parameter is of type MyClass.

Then I want to automatically generate the Json code for the MyClass class, rather than manually adding the JsonSerializable attribute.

Like what:

My source generator is aware of the AutoJsonSerializable attribute

```
[AutoJsonSerializable]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{

}
```

Then use my own source generator to generate the following code:

```
[JsonSerializable(typeof(MyClass))]
internal partial class AppJsonSerializerContext
{

}
```

The problem is that the two source generators are not visible to each other when generating code. As a result, the Json code of the MyClass class cannot be automatically generated.

I think this question should be useful, especially in the subsequent Aspnetcore, where the program should recognize which classes are used and automatically generate the corresponding Json code. Instead of adding the JsonSerializable feature to the user themselves.

Please let me know if there is a workaround.

**Comment by eiriktsarpalis** [comment]
It would be very useful in a number of applications, but unfortunately it isn't something that the current source generator infrastructure permits.

**Comment by stephentoub** [comment]
I'm going to close this as it's unfortunately not actionable. A fix here would be in the C# compiler supporting source generator layering, at which point it would "just work" (and we don't intend to expose the JSON source generator as a library consumable by other generators). That desire is tracked by https://github.com/dotnet/roslyn/issues/57239. Thanks.
