### ISSUE TITLE
Backport System.Globalization.Extensions.Tests for icu 74/unicode 15.1

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#110498]
We made fixes last year that need to be backported to `release/8.0`. These probably should have been backported at the time of the earlier PR. Not a criticism but just an observation. This type of change typically affects all the distros in a staggered fashion and affects our LTS versions.

Related:

- https://github.com/dotnet/runtime/pull/105282
- https://github.com/dotnet/runtime/pull/110492

**Comment by richlander** [comment]
FYI @omajid

**Comment by tarekgh** [comment]
Created https://github.com/dotnet/runtime/issues/110499 and will close this one.
