### ISSUE TITLE
[nativeaot] nativeaot how can I deploy to run on buildroot

### ISSUE THREAD

**Issue by 17723010593** [dotnet/runtime#110500]
I have a luckfox development board that uses the buildroot image provided by the official, but I heard that he uses uclibc, and I don't know much about compilation.
I used the docker image [azurelinux-3.0-cross-arm-net9.0] to compile the program and put it on the development board Using ldd, the prompt is as follows

![Image](https://github.com/user-attachments/assets/a3166600-04af-44c0-a16e-5e62e68e8bdf)

**Comment by am11** [comment]
dotnet does not support uClibc (which is declining in popularity). OTOH, buildroot supports musl libc as well as glibc (https://github.com/buildroot/buildroot/blob/5f18745057a8bd2e0a3dc40d77ea382c5f6e41f0/Config.in#L660), both of which are supported by dotnet (https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.md#linux-compatibility). You should switch to either musl or glibc based buildroot.
