### ISSUE TITLE
[API Proposal]:Add property to HttpClient

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#110555]
### Background and motivation

I propose adding a property called ClientHandler to HttpClient, which would allow direct access to the underlying HttpClientHandler. When creating an instance of HttpClient, parameters like cookies or connection settings can be configured. However, once the object is passed to a class, there's no way to modify these settings further.

```csharp
сlass Test(HttpClient client)
{
   public void Execute()
    {
     // In this class, it's impossible to configure cookies or other parameters
    }
}
```

### API Proposal

```csharp
class  HttpClient
{
    public HttpClientHandler ClientHandler {get;}
}
```

### API Usage

```csharp
var message = new HttpClientHandler();
var client = new HttpClient(message);

void Execute(HttpClient client)
{
    client.ClientHandler.CookieContainer = null;
}
```

**Comment by MihaZupan** [comment]
An `HttpClient` may not be backed by an `HttpClientHandler` as the user can provide a custom `HttpMessageHandler`.

It's also not possible to change settings on `HttpClientHandler` after you've sent a request. See https://github.com/dotnet/runtime/issues/77668#issuecomment-1332673779

**Comment by Mr0N** [comment]
> An `HttpClient` may not be backed by an `HttpClientHandler` as the user can provide a custom `HttpMessageHandler`.
> 
> It's also not possible to change settings on `HttpClientHandler` after you've sent a request. See [#77668 (comment)](https://github.com/dotnet/runtime/issues/77668#issuecomment-1332673779)
I modified it this way, but I’d like to do it without hacks.

```
    public class Hand : HttpClientHandler
    {
        public static void SetToHandlerCookies(CookieContainer cookies)
        {
            foreach (var item in _hand)
            {
                item.CookieContainer = cookies;
            }
        }
        static ConcurrentBag<Hand> _hand = new ConcurrentBag<Hand>();
        public Hand()
        {
            _hand.Add(this);
        }
    }
```

```
builder.Services.AddHttpClient()
     .ConfigureHttpClientDefaults(http =>
     {
         http.ConfigurePrimaryHttpMessageHandler(() =>
         {
             var handler = new Hand();
             handler.AllowAutoRedirect = true;
             handler.UseProxy = true;
           /// handler.Proxy = new WebProxy("127.0.0.1", 8888);
             return handler;
         });
     });
```

**Comment by DL444** [comment]
Wouldn't sharing `CookieContainer` between primary handlers lead to unexpected information disclosure? IMHO binding cookies to the primary handler is the culprit of most cookie-related issues with `IHttpClientFactory`. Cookies should really be a session-specific state where "session" is defined by the consumers. It's unfortunate that things have historically been designed this way.

**Comment by CarnaViire** [comment]
Per-session / per-request overrides (cookies, proxies, default headers, certs, etc) are already tracked in 
- https://github.com/dotnet/runtime/issues/77668
- https://github.com/dotnet/runtime/issues/23322
- https://github.com/dotnet/runtime/issues/35992
- https://github.com/dotnet/runtime/issues/41191

**Comment by Mr0N** [comment]
> The proposed API is problematic for the reasons called out in [#110555 (comment)](https://github.com/dotnet/runtime/issues/110555#issuecomment-2529849041).
> 
> The scenario itself is already covered by existing discussions that Natalia linked - [#110555 (comment)](https://github.com/dotnet/runtime/issues/110555#issuecomment-2531276935).

Why is it impossible to change cookies after a request? For example, I sent one request and want to send another, but before that, I want to change the cookies or replace the collection of cookies. What is the idea behind the immutability of cookies?

**Comment by Mr0N** [comment]
> An `HttpClient` may not be backed by an `HttpClientHandler` as the user can provide a custom `HttpMessageHandler`.
> 
> It's also not possible to change settings on `HttpClientHandler` after you've sent a request. See [#77668 (comment)](https://github.com/dotnet/runtime/issues/77668#issuecomment-1332673779)

Why is it impossible to change cookies after a request? For example, I sent one request and want to send another, but before that, I want to change the cookies or replace the collection of cookies. What is the idea behind the immutability of cookies?
