### ISSUE TITLE
Test failures in `JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput`

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#110575]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=891042
Build error leg or test failing: JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput
Pull request: https://github.com/dotnet/runtime/pull/110396

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=891042
**Error message validated:** `[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 12/10/2024 3:19:22 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[892047](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892047)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892047&view=ms.vss-test-web.build-test-results-tab&runId=23374224&resultId=101567)|dotnet/runtime#110591|
|[891967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891967)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891967&view=ms.vss-test-web.build-test-results-tab&runId=23373422&resultId=102443)|dotnet/runtime#110198|
|[891974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891974)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891974&view=ms.vss-test-web.build-test-results-tab&runId=23373510&resultId=116130)|dotnet/runtime#110589|
|[891947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891947)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891947&view=ms.vss-test-web.build-test-results-tab&runId=23372970&resultId=101122)|dotnet/runtime#110342|
|[891882](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891882)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891882&view=ms.vss-test-web.build-test-results-tab&runId=23372332&resultId=110979)|dotnet/runtime#110596|
|[891876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891876)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891876&view=ms.vss-test-web.build-test-results-tab&runId=23371852&resultId=108624)|dotnet/runtime#110477|
|[891862](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891862)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891862&view=ms.vss-test-web.build-test-results-tab&runId=23371212&resultId=108515)|dotnet/runtime#110322|
|[891834](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891834)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891834&view=ms.vss-test-web.build-test-results-tab&runId=23370506&resultId=114337)|dotnet/runtime#110554|
|[891796](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891796)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891796&view=ms.vss-test-web.build-test-results-tab&runId=23369692&resultId=112676)|dotnet/runtime#107168|
|[891774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891774)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891774&view=ms.vss-test-web.build-test-results-tab&runId=23369104&resultId=113334)|dotnet/runtime#110342|
|[891768](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891768)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891768&view=ms.vss-test-web.build-test-results-tab&runId=23369060&resultId=111069)|dotnet/runtime#110548|
|[891492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891492)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891492&view=ms.vss-test-web.build-test-results-tab&runId=23368584&resultId=103078)|dotnet/runtime#110579|
|[891733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891733)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891733&view=ms.vss-test-web.build-test-results-tab&runId=23366554&resultId=102663)||
|[891727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891727)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891727&view=ms.vss-test-web.build-test-results-tab&runId=23366528&resultId=104405)|dotnet/runtime#110591|
|[891710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891710)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891710&view=ms.vss-test-web.build-test-results-tab&runId=23366140&resultId=100351)|dotnet/runtime#110534|
|[891667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891667)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891667&view=ms.vss-test-web.build-test-results-tab&runId=23365530&resultId=108838)|dotnet/runtime#110567|
|[891655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891655)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891655&view=ms.vss-test-web.build-test-results-tab&runId=23364920&resultId=110864)|dotnet/runtime#110322|
|[891637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891637)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891637&view=ms.vss-test-web.build-test-results-tab&runId=23364028&resultId=114311)|dotnet/runtime#110589|
|[891613](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891613)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891613&view=ms.vss-test-web.build-test-results-tab&runId=23362216&resultId=121672)|dotnet/runtime#110574|
|[891616](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891616)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891616&view=ms.vss-test-web.build-test-results-tab&runId=23361812&resultId=103688)|dotnet/runtime#110086|
|[891583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891583)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891583&view=ms.vss-test-web.build-test-results-tab&runId=23361084&resultId=102620)|dotnet/runtime#110550|
|[891546](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891546)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891546&view=ms.vss-test-web.build-test-results-tab&runId=23359156&resultId=102891)|dotnet/runtime#110554|
|[891540](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891540)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891540&view=ms.vss-test-web.build-test-results-tab&runId=23359020&resultId=100897)|dotnet/runtime#110322|
|[891157](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891157)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891157&view=ms.vss-test-web.build-test-results-tab&runId=23358404&resultId=101841)|dotnet/runtime#110566|
|[891497](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891497)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891497&view=ms.vss-test-web.build-test-results-tab&runId=23357940&resultId=101396)|dotnet/runtime#110580|
|[891514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891514)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891514&view=ms.vss-test-web.build-test-results-tab&runId=23357912&resultId=112562)|dotnet/runtime#107909|
|[891484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891484)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891484&view=ms.vss-test-web.build-test-results-tab&runId=23357730&resultId=126763)|dotnet/runtime#110330|
|[891469](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891469)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891469&view=ms.vss-test-web.build-test-results-tab&runId=23357272&resultId=125233)|dotnet/runtime#110576|
|[891445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891445)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891445&view=ms.vss-test-web.build-test-results-tab&runId=23356864&resultId=122958)|dotnet/runtime#108750|
|[891442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891442)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891442&view=ms.vss-test-web.build-test-results-tab&runId=23356786&resultId=115256)|dotnet/runtime#110197|
|[891430](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891430)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891430&view=ms.vss-test-web.build-test-results-tab&runId=23356544&resultId=114186)|dotnet/runtime#110574|
|[891327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891327)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891327&view=ms.vss-test-web.build-test-results-tab&runId=23353470&resultId=101415)|dotnet/runtime#110567|
|[891249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891249)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891249&view=ms.vss-test-web.build-test-results-tab&runId=23351218&resultId=101167)|dotnet/runtime#110477|
|[891053](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891053)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891053&view=ms.vss-test-web.build-test-results-tab&runId=23341468&resultId=110167)|dotnet/runtime#103950|
|[891042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891042)|dotnet/runtime|[JSImportGenerator.Unit.Tests.Compiles.ValidateGeneratedSourceOutput](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891042&view=ms.vss-test-web.build-test-results-tab&runId=23340868&resultId=107281)|dotnet/runtime#110396|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|35|35|35|

**Comment by jkotas** [comment]
@pavelsavara Introduced by #110539 ?
