### ISSUE TITLE
linux-armel checked CoreCLR_NonPortable build failing in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#110517]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=889548&view=logs&j=2eda3965-9146-55d1-4226-c3d3f8432d8f
Build error leg or test failing: Build / linux-armel checked CoreCLR_NonPortable / Build product
Pull request: https://github.com/dotnet/runtime/pull/110515

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "ld.lld: error: cannot open crtbeginS.o: No such file or directory",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=889548
**Error message validated:** `[ld.lld: error: cannot open crtbeginS.o: No such file or directory`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 12/9/2024 6:19:26 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[889597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889597)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889597/logs/183)|dotnet/runtime#110518|
|[889586](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889586)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889586/logs/183)|dotnet/runtime#110516|
|[889581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889581)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889581/logs/183)|dotnet/runtime#110501|
|[889548](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889548)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889548/logs/368)|dotnet/runtime#110515|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|4|4|

**Comment by thaystg** [comment]
@akoeplinger the same problem is happening on .net9-staging, do we need to create another issue?

**Comment by akoeplinger** [comment]
@thaystg I opened the backport: https://github.com/dotnet/runtime/pull/110614

**Comment by thaystg** [comment]
@akoeplinger I'm sorry for that, same problem is happening on net8-staging.
https://dev.azure.com/dnceng-public/public/_build/results?buildId=893698&view=logs&jobId=365c353d-16e8-5fe5-6bc7-945e65f72ee2&j=365c353d-16e8-5fe5-6bc7-945e65f72ee2&t=86ef7ae1-a7da-5352-e5b0-3b640b38d38c

**Comment by akoeplinger** [comment]
Thanks, opened https://github.com/dotnet/runtime/pull/110792
