### ISSUE TITLE
Semantic Versioning of Azure packages and the System Namespace

### ISSUE THREAD

**Issue by asifshakir** [dotnet/runtime#110519]
### Description

We are currently consuming Azure.Identity version 1.12.1 in our application which targets .NET Framework 4.8. This version has a transitive dependency on Azure.Core version 1.40.0. This Azure.Core version has a transitive dependency on System.Memory.Data version 1.0.2.

Recently, Azure.Identity version 1.13.0 was released. This version depends on Azure.Core version 1.44.1, which, in turn, upgraded the transitive dependency for System.Memory.Data to version >= 6.0.0.

Given that System.Memory.Data was upgraded from version 1.x to version 6.x, shouldn't this have been considered a major version change according to semantic versioning principles?

Also, I'd like to highlight that System.Memory.Data appears to belong to the System namespace but is retrieved from NuGet rather than being part of the core .NET Framework. This could lead to confusion for developers, as the convention is often that packages in the System namespace are assumed to be part of the framework, not external NuGet packages.

### Reproduction Steps

Upgrading any package from Azure.Identity from 1.12.1 to 1.13.0

### Expected behavior

A change in a major version in a dependency should result in a major version change in the package that consumes it

### Actual behavior

Upgrading Azure.Identity over a minor version (1.12.1 to 1.13.0) causes a dependency to jump up by a major version => System.Memory.Data

**Comment by huoyaoyuan** [comment]
> The NuGet packages built from the https://github.com/dotnet/runtime do not follow semantic versioning.

Strictly speaking, it does follow SemVer, but with much more strict compatibility requirements.

Since NuGet and (default) CLR loading doesn't support loading same assemblies/packages with different version, it's very important to keep API compatiblity even for major version update.

> as the convention is often that packages in the System namespace are assumed to be part of the framework, not external NuGet packages.

There is no such convention. `System` only means developed by first party .NET Team, which is preserved by NuGet. NuGet is used for more flexible delivery for libraries that's not in the core framework.

**Comment by asifshakir** [comment]
> > The NuGet packages built from the https://github.com/dotnet/runtime do not follow semantic versioning.
> 
> Strictly speaking, it does follow SemVer, but with much more strict compatibility requirements.
> 
> Since NuGet and (default) CLR loading doesn't support loading same assemblies/packages with different version, it's very important to keep API compatiblity even for major version update.
> 
> > as the convention is often that packages in the System namespace are assumed to be part of the framework, not external NuGet packages.
> 
> There is no such convention. `System` only means developed by first party .NET Team, which is preserved by NuGet. NuGet is used for more flexible delivery for libraries that's not in the core framework.

Thanks, that clarifies the Microsoft position for me.

Although it can lead to confusion in the future if there are breaking changes since the library would change only by a minor version, dependencies can jump major versions, and I could have a direct dependency on the older version of the same library.

**Comment by huoyaoyuan** [comment]
> and I could have a direct dependency on the older version of the same library.

No, package downgrading is forbidden by NuGet.
The "major" version of `System` packages is mostly yearly bump. It's usually less breaking than "minor" version of third party libraries, if any.
