### ISSUE TITLE
Network-path references in Uri class are not being parsed

### ISSUE THREAD

**Issue by EsgAtWorkleap** [dotnet/runtime#110549]
### Description

Creating a new relative `Uri` with a network-path reference (a relative URI starting with two forward slashes)

### Reproduction Steps

```
var uri = new Uri("//microsoft.com", UriKind.Relative);
Console.WriteLine(uri.Host);
```

### Expected behavior

`uri.Host` should return the hostname of the `Uri`, in this case `microsoft.com`

### Actual behavior

An `InvalidOperationException` is thrown

### Regression?

Not that I could find, same behaviour in .NET 9, 8 and .NET Framework 4.7

### Known Workarounds

Manually parsing, or prefixing `//` with `http:` before parsing

### Configuration

.NET 9
Windows 11
x64

### Other information

Relevant RFC on URIs: https://datatracker.ietf.org/doc/html/rfc3986#section-4.2

**Comment by MihaZupan** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.uri.host?view=net-9.0#exceptions

> Exceptions
[InvalidOperationException](https://learn.microsoft.com/en-us/dotnet/api/system.invalidoperationexception?view=net-9.0)
This instance represents a relative URI, and this property is valid only for absolute URIs.

Querying properties like `Host` is not supported on relative Uris.
In your case, what you want is to parse the input as an absolute Uri.

`new Uri("//microsoft.com").Host` does print `microsoft.com`.

**Comment by MihaZupan** [comment]
It's parsed as a UNC absolute file path.

**Comment by MihaZupan** [comment]
Closing this one as answered, let us know if we've missed anything.
