### ISSUE TITLE
dotnet publish regularly fails with OutOfMemory after update to .NET 9

### ISSUE THREAD

**Issue by weltkante** [dotnet/runtime#110616]
### Describe the bug
I've updated a private project to .NET 9 and started seeing regular build failures when running `dotnet publish`, making it almost impossible to build the project (like 9 out of 10 runs fail). Most of the time they fail with OutOfMemory exceptions, sometimes segmentation faults. Before the build the machine is using 1.25 out of 8 GB RAM during the build it goes up to about 1.58 GB when looking at with htop, so whatever peaks OOM must be doing a huge allocation. Its a virtual ubuntu machine with no swap configured for performance. (This was preconfigured either by the VM hosting company or the ubuntu installation image and not configured by me so I assume its a common setup.)

Command line to publish is `dotnet publish server -c Release -f net9.0 -r linux-x64 --self-contained false -o /game/bin`

We had no issues building the same codebase in .NET 8, first few builds on .NET 9 were fine too, before it suddenly started to regularly fail with OOM. Nothing really changed on the machine side I'm aware of and I'd like to know if there's anything I can do to diagnose this further.

### To Reproduce
The git repo where this occurs is not public and I'd like to know if there's anything I can do to diagnose this short of building a public repro.

### Exceptions (if any)
```
core succeeded (0.5s) → build/bin/core/Release/net9.0/core.dll
gateway succeeded (5.6s) → build/bin/gateway/Release/net9.0/gateway.dll
server net9.0 failed with 1 error(s) (11.2s)
/usr/share/dotnet/sdk/9.0.100/Roslyn/Microsoft.CSharp.Core.targets(89,5): error : Out of memory.
```
or sometimes
```
core succeeded (0.6s) → build/bin/core/Release/net9.0/core.dll
gateway succeeded (0.6s) → build/bin/gateway/Release/net9.0/gateway.dll
server net9.0                                                               CoreCompile (14.9s)
../compile.sh: line 3: 170587 Segmentation fault      dotnet publish server -c Release -f net9.0 -r linux-x64 --self-contained false -o /game/bin
```

### Further technical details
<details><summary>dotnet --info</summary>

```
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.3068a692
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.100/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  7.0.410 [/usr/share/dotnet/sdk]
  9.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

**Comment by baronfel** [comment]
One thing to keep in mind for dump collection is that MSBuild is multi-process, so it can be hard to figure out which node to get dumps from. If you force the build to run on a single node with the `/m:1` flag, then you will know the PID to dump from.

**Comment by weltkante** [comment]
> I'm not an expert on dumps, but I found a blog post that seems fairly comprehensive

Thats for Windows unfortunately, the machine it fails on is a linux machine (see original report) and also taking a dump this way would require the process crashing, which isn't the case here since the OOM is usually caught and terminates the build "normally" without crashing. It'd require some sort of trigger to create a dump on OOM.

I know there's dotnet trace & similar tools to record diagnostic information of applications, but no idea how to collect information about the build process itself.

Worst case, if there are no other options, I could try going for the occasional segmentation fault and try to capture the resulting core dump, but I assumed there should be builtin options to diagnose the build tools just like dotnet trace can diagnose applications.

**Comment by weltkante** [comment]
> One thing to keep in mind for dump collection is that MSBuild is multi-process, so it can be hard to figure out which node to get dumps from. If you force the build to run on a single node with the `/m:1` flag, then you will know the PID to dump from.

Adding `-m:1` to the dotnet publish command line makes the whole build much faster and it always succeeds in the few runs I took so far, contrary to almost always failing without it 🤔

**Comment by Forgind** [comment]
> Thats for Windows

I totally missed that, sorry 😅

> Adding -m:1 to the dotnet publish command line makes the whole build much faster (0.3s instead of 15s+) and it always succeeds in the few runs I took so far, contrary to almost always failing without it 🤔

This seems...odd...it almost reminds me of a bug I saw a while ago where MSBuild could get into a state where it couldn't connect to its own worker nodes, and then it would just keep creating more and more, eventually overloading the machine. That generally led to your machine turning into a brick rather than a clean OOM exception, but perhaps now there's something that requests like 100 mb right off the bat, and that leads to an OOM after making 65 new processes?

**Comment by weltkante** [comment]
I'm aware of the "leftover" msbuild processes and use `dotnet build-server shutdown` as well as manually looking out for leftover processes between builds and killing them ... the whole leftover process issue seems to have improved and (almost) fixed for .NET 9, it was much worse in previous versions, these days I rarely see one

So if its spawning too many processes in one go its fast enough that I don't see it in the standard htop monitoring

**Comment by baronfel** [comment]
FWIW we haven't changed the build-node lifetime for .NET 9 at all, it's still at 15m since the last build. So I wouldn't put any weight on your observation.

**Comment by weltkante** [comment]
it might have been .NET 8 that fixed the issue with leftover msbuild processes, its been a while that I had to worry about those

**Comment by weltkante** [comment]
Looks like `-m:1` doesn't fix the problem, disabling multi-process just lowers the memory usage a bit so it was succeeding more often than with it enabled.

Basically it looks like the build process is just at the edge of failing on this machine, which makes sense because when I first switched to .NET 9 everything seemed to work, only a few weeks later it started failing, while nothing really changed on the machine. People just kept working on the codebase so it slowly grows and the build process probably slowly needed more memory until it tripped over the edge.

If I terminate running all running services (like the SQL server) I can get it also back past the edge where it succeeds without `m:1` but obviously thats inconvenient.

I have the feeling that its the fact the server image was setup without swap space for performance that makes memory failures hard faults and .NET doesn't seem to handle that well, at least thats my guess. The main question being whether using that much memory (>6GB) is intentional and the machine is just not big enough to compile code on it (I would have to start cross compiling instead of pulling the source onto the server and compile locally) - or if the memory spike is actually a bug and shouldn't happen or being handled gracefully. I think I remember having seen runtime issues like that being reported in the past, where the runtime mistakingly allocates large amounts of memory when it only wanted to allocate address space without wanting to map it to physically memory just yet, so I'm wondering whether its that kind of a problem.

Anyways, still would need a way to trace or dump the build process itself to determine what actually makes up these large allocations, so I'd appreciate input if there's anything I can do to investigate further.

**Comment by baronfel** [comment]
The best tools we have to trace the build process itself in a CI scenario are

* [dotnet trace](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace) for low-level perf information
* [MSBuild binlogs](https://msbuildlog.com/) for investigating the MSBuild build logic used
  * these won't really have memory usage information

For a full perf log you'd be looking at something like `dotnet trace collect -- dotnet build <rest of command>` to get an actual trace.

If you're using AspNetCore, there are some performance changes in .NET 9 due to the integrated static web assets compression features, but my understanding is that those have been analyzed and addressed in more recent SDK versions (9.0.101+ I believe)

**Comment by Forgind** [comment]
Do binlogs get produced properly if you oom? I thought that was too hard of a crash for MSBuild to handle it cleanly

**Comment by weltkante** [comment]
> Do binlogs get produced properly if you oom? I thought that was too hard of a crash for MSBuild to handle it cleanly

Probably depends on what kind of OOM and where exactly it happens. For me most of the time it was just the build failing, not msbuild crashing, so probably would have produced a binlog, just not being very useful to have one if the only thing its telling you is the task that failed (which you can also look up from the error message).

> For a full perf log you'd be looking at something like dotnet trace collect -- dotnet build <rest of command> to get an actual trace.

Having trouble getting this to work, `dotnet trace collect --profile gc-collect -- dotnet publish server -c Debug -f net9.0 -r linux-x64 -m:1 --self-contained false` just exits with an error not doing anything (can't reproduce right now though), or it runs idle not consuming CPU nor growing the trace file, so apparently is hanging not building. Doing it without the profile keeps growing the trace but seems not to be making forward progress either.

> If you're using AspNetCore, there are some performance changes in .NET 9 due to the integrated static web assets compression features, but my understanding is that those have been analyzed and addressed in more recent SDK versions (9.0.101+ I believe)

No AspNetCore, just plain .NET Core Console application, and I don't think any of the referenced 3rd party packages have build-time processing either.

Missed the 9.0.101 release, must have been right after I started investigating, having updated to that the errors got less reproducable, i.e. more often succeeding, especially with multiprocess disabled. Not entirely fixed, still getting occasional failures.

I'll keep trying to get dotnet trace working and capture one of the failing runs, but so far it seems not to work, so I'll have to keep experimenting with parameters I guess.

**Comment by am11** [comment]
Assorted notes which may help the investigation:

`dotnet trace collect --format speedscope --providers Microsoft-Build -- dotnet publish <rest of your args>` will generate `dotnet_{timestamp}.speedscope.json` which you can drop in https://www.speedscope.app/ to visualize the activities.

Also, binlogs will show the timing of each task, which might help figuring out if there is abnormal amount of time being spent somewhere.

Did you get a chance to build it on a different machine, like GitHub Actions or Azure DevOps? It might be some cgroup setting limiting the resources if you are seeing this issue on a specific VM and not elsewhere.

Make sure there is no environment variable set (unintentionally) on the VM which alters the runtime behavior:
`export | grep -E 'DOTNET_|COMPlus_|MSBUILD'`

Another option is to run it under the LLVM debugger.

Setup:
```sh
# install lldb on Ubuntu
$ sudo apt install -y lldb

# install .NET SOS plugin for lldb
$ dotnet tool install --global dontet-sos
$ dotnet-sos install

# proactively download native runtime symbols
$ dotnet tool install --global dotnet-symbol
# requires sudo to download .dbg fiels next to ELF binaries
$ find /usr/local/share/dotnet/shared -type f -exec sh -c '
  if grep -q -P "\x7fELF" "$1"; then
    sudo dotnet-symbol --timeout 20 "$1"
  fi
' _ {} \;
```

Debugging session:
```gdb
$ lldb -- dotnet publish <rest of your args>
# inside lldb REPL

# first enable child process mode (as dotnet build etc. spawns a new process)
(lldb) settings set target.process.follow-fork-mode child

# run the dotnet publish command you passed in
(lldb) run
# keep repeating run until it OOMs, once it breaks:
(lldb) clrstack -f
```

You can review and filter out any sensitive info in `clrstack -f` output then share the logs. This will help identifying the issue. Maybe it's related to https://github.com/dotnet/runtime/issues/104123 (which was fixed in 9.0 RTM, so probably not).

**Comment by weltkante** [comment]
> Did you get a chance to build it on a different machine, like GitHub Actions or Azure DevOps? It might be some cgroup setting limiting the resources if you are seeing this issue on a specific VM and not elsewhere.

Builds fine on all the Windows machines we use for development, only when deploying to the production VMs we've hit the issue. While we were on .NET 8 we already had to move from smaller 4GB ram machines (with 2GB free when building) to a larger 8GB ram VM but that was less "surprising" because I could follow in htop that the ram was filling up entirely during the build. The larger machine has 6 GB free instead of 2 GB and it was working fine, then I decided to upgrade to .NET 9, and it still was working for a few weeks (and still is working now when terminating additional services to get a little more free ram). So I'm pretty sure its not the machine in itself or some constraints configured but the amount of ram available and maybe influenced by having no swap.

Considering I was building in 2GB free before in .NET 8 and earlier and now 6GB don't seem to be enough for .NET 9 it looks like a regression at first glance, especially since the ram _does not_ fill up in htop, i.e. its a singular spike with sudden OOM termination.

Update to 9.0.101 made this harder to reproduce unfortunately (or fortunately?), with `m:1` settings I'm not getting OOM anymore (got them occasionally on 9.0.100) and without m:1 I'm now only occasionally getting OOM while before I got it almost always, so 9.0.101 definitely made things "better" in a way, but whatever this memory spike is, isn't gone yet.

The additional thing that causes confusion to me is that you seem to suggest `dotnet trace` should work capturing the build process but it simply doesn't for me. I just noticed I was still running the tooling in the .NET 8 version (and it wasn't complaining about it). Updated it but that makes no difference, the build makes no forward progress when being traced and depending on profile flags the trace doesn't even grow.

I'll try the lldb suggestion above tomorrow, to see if that either hangs as well (and if so where), or if I can get it to break into one of the occasional OOMs

**Comment by weltkante** [comment]
I've not been able to reproduce this regularly enough anymore to get an attempt for lldb debugging. Without m:1 this still happens, but very rarely, like one in twenty builds or something. With m:1 enabled I haven't seen the error again.

I've even artificially reduced free memory from 6gb to 4gb by running some services twice on the machine and that didn't cause the problem to become worse. So I feel like the update to 9.0.101 reduced the impact of the issue enough that I'll not worry about it anymore.

I still didn't figure out how to do a `dotnet trace collect -- dotnet build`, it just hangs, and if you think thats worth looking into I can open a separate issue.
