### ISSUE TITLE
Mono runtime unable to set callspec and utilize them

### ISSUE THREAD

**Issue by AlexeiNaabal** [dotnet/runtime#110601]
### Description

ep_rt_mono_profiler_provider_parse_options setup the callspec callback for the _mono_profiler_provider inside this option parsing stage, but the _mono_profiler_provider will only be available after all option parsed. If I pass --diagnostic-mono-profiler-callspec, the runtime will terminated here since the profiler is null.

Besides, after move the callspec setup after _mono_profiler_provider's instantiation, I use `MONO_DIAGNOSTICS=--diagnostic-mono-profiler=enable --diagnostic-mono-profiler-callspec=T:Program,-N:MyNamespace` to start the runtime, then collect event with `--providers Microsoft-DotNETRuntimeMonoProfiler:20000000:4:` to trace the method_enter/leave, the excluded namespace still present in the nettrace when I inspecting the nettrace with [method-tracer](https://github.com/lateralusX/diagnostics-nettrace-samples).

From the [tracing instruction](https://github.com/dotnet/runtime/blob/main/docs/design/mono/diagnostics-tracing.md) I read that if I instrument specific asm/Type/Namespace and profiling with `Microsoft-DotNETRuntimeMonoProfiler:20000000`, runtime should only emit events under METHOD_TRACING_KEYWORD of these asm/Type/Namespace, do I understand it wrong?

### Reproduction Steps

Add `MONO_DIAGNOSTICS=--diagnostic-mono-profiler-callspec={do some exclude}` exclude can follow [tracing instruction}](https://github.com/dotnet/runtime/blob/main/docs/design/mono/diagnostics-tracing.md), and check if runtime start successfully
Start dotnet-trace with `--providers Microsoft-DotNETRuntimeMonoProfiler:20000000:4:` and inspect with [method-tracer](https://github.com/lateralusX/diagnostics-nettrace-samples)'s aggregate filter to see if the exclude content presented.

### Expected behavior

Expecting the runtime start normally, and the final nettrace contains only instrumented content.

### Actual behavior

Actual behavior are runtime start failed, and after managed to fix the startup issue, callspec seems not filtering.

### Other information

runtime version: 8.0.7

**Comment by tommcdon** [comment]
@mdh1418 
cc @lateralusX

**Comment by lateralusX** [comment]
Fixed by https://github.com/dotnet/runtime/pull/110618

**Comment by lateralusX** [comment]
@AlexeiNaabal, I suspect that the issue is that method tracing includes both enter/leave, but also calls that go over the begin_invoke/end_invoke and those are different kind of calls that doesn't use instrumentation and therefore doesn't use callspec . The method-trace tool need that additional info if it needs to build up callstacks, so for what it looks like, the callspec filtering is working, just that there is no separate mask for enter/leave and begin_invoke/end_invoke events. Will take a look if old Mono log profiler did separate them, if so we could in theory put begin_invoke/end_invoke under a separate profiler keyword.

**Comment by AlexeiNaabal** [comment]
> [@AlexeiNaabal](https://github.com/AlexeiNaabal), I suspect that the issue is that method tracing includes both enter/leave, but also calls that go over the begin_invoke/end_invoke and those are different kind of calls that doesn't use instrumentation and therefore doesn't use callspec . The method-trace tool need that additional info if it needs to build up callstacks, so for what it looks like, the callspec filtering is working, just that there is no separate mask for enter/leave and begin_invoke/end_invoke events. Will take a look if old Mono log profiler did separate them, if so we could in theory put begin_invoke/end_invoke under a separate profiler keyword. Number of methods called using method_begin_invoke/method_end_invoke should be dramatically smaller than enter/leave, so in end not sure its such a big problem, the main thing that could flood files are the enter/leave calls. You can look at the trace file in perfview to see the number of events for the different kinds, the events have the following ids:
> 
> method_begin_invoke == Microsoft-DotNETRuntimeMonoProfiler/EventID(34) method_end_invoke == Microsoft-DotNETRuntimeMonoProfiler/EventID(35) enter == Microsoft-DotNETRuntimeMonoProfiler/EventID(29) leave == Microsoft-DotNETRuntimeMonoProfiler/EventID(30)
> 
> When I ran a simple HelloWorld using callspec T:Program I only get 1 enter and 1 leave (Main method), but 1622 method_begin_invoke/method_end_invoke. If I run without callspec I get 288 820 enter/leave but still only 1622 method_begin_invoke/method_end_invoke on simple HelloWorld, so looks like the callspec does its job.

You are right, the callspec with the fix is working perfectly, my issue comes from other module in the project, I will close this issue.

After dig some possible related module in the project I found the source of those unexpected instrumentation setup => a module in our project create a profiler instance and call the set_instrumentation_callback, hook up method_enter/leave/exception_leave, that explained why I see multiple profiler instance when `mono_profiler_get_call_instrumentation_flags` looping profilers.

Just before closing this issue, I would like to mention that the profiler created on the module record method execution time smaller than the default `_mono_profiler_provider`, like tracing 10000 times execution of certain method, the custom profiler counts less total MSec compare to the `_mono_profiler_provider`, as the custom method_enter/leave callback directly access the recorded data, maybe we can come up a better recording/tracing procedural with lower overhead compare to current `fire_event_enter/exit()` check and `FireEtwMonoProfiler*()` emitter?
