### ISSUE TITLE
PixelFormat Tiff CcittGr4 wrong on linux

### ISSUE THREAD

**Issue by gjmv** [dotnet/runtime#1106]
Hi, i'm working with Tiff CCITTGr4 images (bitonal) and when i test in linux (net core 2.2/3.0/3.1) the Bitmap class give me PixelFormat.Format24bppRgb
When i run in windows, PixelFormat give me Format1bppIndexed (the correct value).

The test code is very simple. Having test.tif file (TIF CCITTGr4)
`
using (Bitmap bmp = new Bitmap("test.tif"))
            {
                Console.WriteLine(bmp.PixelFormat);
            }
`
Regards
Gustavo

**Comment by danmosemsft** [comment]
This is probably an issue in libgdiplus. What version so you have on your system? You should probably reopen this in the mono/libgdiplus repo.

**Comment by gjmv** [comment]
> This is probably an issue in libgdiplus. What version so you have on your system? You should probably reopen this in the mono/libgdiplus repo.

Hi my installed version is
libgdiplus: 4.2-1+b1

You think that this is a libgdiplus problem and should open in mono/libgdiplus?

thanks!

**Comment by danmosemsft** [comment]
In Unix, System.Drawing is a thin  layer over libgdiplus. Let's try there first.
