### ISSUE TITLE
[API Proposal]: Implement `IReadOnlyList<T>` in `LinkedList<T>` or create `IReadOnlyLinkedList<T>` and `IReadOnlyLinkedListNode<T>`

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/runtime#110784]
### Background and motivation

To avoid allocating wrappers, it could be useful to add the index accesor directly to the linked list, at least like a explicit implementation of `IReadOnlyList<T>`. It will be useful for public APIs relying in LinkedList internally, but when the result could be read only.

`IReadOnlyCollection<T>` is ok and implemented, but, technically, a linked list is "ordered/indexed", and therefore it could be a strong candidate for implemented a `IReadOnlyList<T>` interface (if you go further, you could implement `IList<T>`, too).

### API Proposal

```csharp
namespace System.Collections.Generic;

public class LinkedList<T> : ..., IReadOnlyList<T>
{
    T IReadOnlyList<T>.this[int index]
    {
        get
        {
            //Disallow negative numbers to match behaviour of other list types, but with the current implementation it could be 'head.prev'
            ArgumentOutOfRangeException.ThrowIfLessThan(index, 0);

            //Maybe it will be necessary to implement a lock around all of this from here, but all non concurrency-ready lists suffers this.
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Count);
            var element = First ?? throw new Exception("Oops, something is broken");
            for (int i = 0; i < index; i++){
                element = element?.Next ?? null;
                //it is not needed to check '== head' because the count
            }

            if (element is null)
                throw new Exception("Oops");
            return element.Value;
        }

    }
}
```

### API Usage

```csharp
// Fancy the value
 c = new LinkedList<int>();
var value = c[0];

//for-loops, returning readonly interfaces from public APIs...
```

### Alternative Designs

Creating interfaces for the linked list.

```csharp

public interface IReadOnlyLinkedList<T> : IReadOnlyCollection<T> {
    
    IReadOnlyLinkedListNode<T>? First { get; }
    IReadOnlyLinkedListNode<T>? Last { get; }

}

public interface IReadOnlyLinkedListNode<T>
{
    IReadOnlyLinkedList<T> List{ get; }
    IReadOnlyLinkedListNode<T>? Next { get; }
    IReadOnlyLinkedListNode<T>? Previous { get; }
    T Value { get; }
}

public sealed class LinkedListNode<T> : IReadOnlyLinkedListNode<T>
    .....

    public LinkedList<T>? List
    {
        get { return list; }
    }    

    public LinkedListNode<T>? Next
    {
        get { return next == null || next == list!.head ? null : next; }
    }

    public LinkedListNode<T>? Previous
    {
        get { return prev == null || this == list!.head ? null : prev; }
    }

    public T Value
    {
        get { return item; }
        set { item = value; }
    }
}
```

### Risks

The unique risk I see is if there could be a race condition, but all other non concurrency-ready lists suffers from that.

**Comment by colejohnson66** [comment]
I'm not sure that treating a linked list as a list "proper" is a good idea. Indexing one-by-one requires traversing the entire link chain, which is an `O(n.lgn)` (n squared?) operation.

**Comment by DrkWzrd** [comment]
> Ignoring race conditions, I'm not sure that treating a linked list as a list _proper_ is a good idea. Indexing one-by-one requires traversing the entire link chain _each time_, which is an `O(n^2)` operation.

Yeah, the other idea would be create a `IReadOnlyLinkedList<T>` and `IReadOnlyLinkedListNode<T>`.

**Comment by DrkWzrd** [comment]
> We generally don't try to author collection interfaces for every kind of collection, unless there is a strong motivation to do so. For instance there are no `IQueue<T>` or `IStack<T>` abstractions, and we have no plans of introducing these in the future. I don't think linked lists are common enough to justify including a corresponding interface.

I get it, and I'm not asking about creating `ILinkedList<T>` interface, but a read-only interface.

In `Stack<T>` and `Queue<T>` I can understand that it doesn't have sense to create `IReadOnly...`, its core nature of work is being modified (push/pop, enqueue/dequeue), you can't read it without modify it, and therefore a read-only version of that will be nonsensical, but a linked list, as it is a "list" I think it makes sense to have a `IReadOnly...` interface.

**Comment by eiriktsarpalis** [comment]
There's really only one type that would be implementing this interface no? I don't really see what benefits an added layer of abstraction would bring to the table.

**Comment by eiriktsarpalis** [comment]
Closing as not planned.
