### ISSUE TITLE
Loading a linux dynamic library (.so) in C# on Windows

### ISSUE THREAD

**Issue by lindadamama** [dotnet/runtime#110718]
In Windows, can I load Linux dynamic libraries (.so) in C# without installing WSL2?

**Comment by huoyaoyuan** [comment]
No. There must be a Linux environment to load native Linux objects. Even with WSL1, one process can only target one OS subsystem.

**Comment by YoshiRulz** [comment]
Linux libraries need a compliant system to run on, so no.

But you can use the ELF format on Windows if you really wanted to. Our [Waterbox](https://github.com/TASEmulators/BizHawk/tree/2.9.1/waterbox) system does just that: libraries are compiled against a custom libc, then we bridge them into managed code with a translation layer which handles the calling convention as well as memory allocation. (The host is in mixed Rust/C#, but the Rust parts could probably be ported to modern .NET with the same functionality and speed, we're just not in a position to do that.)
