### ISSUE TITLE
Decimal.ToString is missing sign for negative zero

### ISSUE THREAD

**Issue by jwosty** [dotnet/runtime#110712]
### Description

When calling Decimal.ToString on `-0.0m`, the sign is missing from the output. Double.ToString and Single.ToString both include the negative sign.

### Reproduction Steps

```csharp
Console.WriteLine((0.0).ToString("f6", System.Globalization.CultureInfo.InvariantCulture));
Console.WriteLine((-0.0).ToString("f6", System.Globalization.CultureInfo.InvariantCulture));
Console.WriteLine((0.0m).ToString("f6", System.Globalization.CultureInfo.InvariantCulture));
Console.WriteLine((-0.0m).ToString("f6", System.Globalization.CultureInfo.InvariantCulture));
```

### Expected behavior

0.000000
-0.000000
0.000000
-0.000000

### Actual behavior

0.000000
-0.000000
0.000000
0.000000

### Regression?

Unsure

### Known Workarounds

None

### Configuration

Runtime: .NET 9.0.101
OS: Windows 11
Arch: x64

### Other information

Related to: https://github.com/dotnet/runtime/issues/70460

**Comment by jwosty** [comment]
Just noticed that this also affects any negative number which rounds to zero upon display:

```csharp
Console.WriteLine((-0.0000001M).ToString("f6", System.Globalization.CultureInfo.InvariantCulture))
```

**Comment by tannergooding** [comment]
This is by design for the `decimal` type where `-0` is meant to be an unimportant implementation detail of the type, as it was designed for monetary/currency usages, not scientific or other domains where values rounding from a negative might be relevant

**Comment by huoyaoyuan** [comment]
Note that `System.Decimal` isn't an IEEE754 type. It doesn't follow some contracts similar to `Single`/`Double`, or IEEE754 decimal types.

**Comment by jwosty** [comment]
@tannergooding 
> This is by design for the `decimal` type where `-0` is meant to be an unimportant implementation detail of the type, as it was designed for monetary/currency usages, not scientific or other domains where values rounding from a negative might be relevant

Ah ok, fair enough. I almost phrased it as a question instead, i.e. "hey is this intended behavior," rather than a bug. It's a little surprising at first in comparison to IEEE floating-point, but makes sense.

Is this documented? Might be good to mention it somewhere so people know it's intentional (like, a single sentence)

**Comment by Clockwork-Muse** [comment]
... Note that it _is_ possible to get `-0.0d` back out, it does retain the necessary information internally (eg, `decimal.IsNegative(...)` returns `true`).
