### ISSUE TITLE
Build warnings in package restore

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#11077]
From Windows x64 Checked build:
```
   1:2>F:\gh\coreclr10\tests\scripts\scripts.csproj : warning NU1603: scripts depends on Microsoft.DotNet.BuildTools.TestSuite (>= 1.0.0-prerelease-00629-04) but Microsoft.DotNet.BuildTools.TestSuite 1.0.0-prerelease-00629-04 was not found. An approximate best match of Microsoft.DotNet.BuildTools.TestSuite 1.0.0-prerelease-00704-04 was resolved. [F:\gh\coreclr10\tests\build.proj]
   1:5>F:\gh\coreclr10\tests\src\Common\test_dependencies\test_dependencies.csproj : warning NU1603: test_dependencies depends on System.Memory (>= 4.6.0-preview1-26907-04) but System.Memory 4.6.0-preview1-26907-04 was not found. An approximate best match of System.Memory 4.6.0-preview3-26501-01 was resolved. [F:\gh\coreclr10\tests\build.proj]
   1:6>F:\gh\coreclr10\tests\src\Common\test_runtime\test_runtime.csproj : warning NU1603: cijobs 0.0.1.2 depends on Microsoft.DotNet.Cli.Utils (>= 1.0.0-dev-1457) but Microsoft.DotNet.Cli.Utils 1.0.0-dev-1457 was not found. An approximate best match of Microsoft.DotNet.Cli.Utils 1.0.0-preview1-002702 was resolved. [F:\gh\coreclr10\tests\build.proj]
   1:9>F:\gh\coreclr10\tests\src\JIT\config\benchmark\benchmark.csproj : warning NU1603: benchmark depends on System.Memory (>= 4.6.0-preview1-26907-04) but System.Memory 4.6.0-preview1-26907-04 was not found. An approximate best match of System.Memory 4.6.0-preview3-26501-01 was resolved. [F:\gh\coreclr10\tests\build.proj]
   1:9>F:\gh\coreclr10\tests\src\JIT\config\benchmark\benchmark.csproj : warning NU1605: Detected package downgrade: System.Runtime.CompilerServices.Unsafe from 4.6.0-preview3-26501-01 to 4.6.0-preview1-26907-04. Reference the package directly from the project to select a different version. [F:\gh\coreclr10\tests\build.proj]
   1:9>F:\gh\coreclr10\tests\src\JIT\config\benchmark\benchmark.csproj : warning NU1605: benchmark -> System.Memory 4.6.0-preview3-26501-01 -> System.Runtime.CompilerServices.Unsafe (>= 4.6.0-preview3-26501-01) [F:\gh\coreclr10\tests\build.proj]
   1:9>F:\gh\coreclr10\tests\src\JIT\config\benchmark\benchmark.csproj : warning NU1605: benchmark -> System.Runtime.CompilerServices.Unsafe (>= 4.6.0-preview1-26907-04) [F:\gh\coreclr10\tests\build.proj]
  1:10>F:\gh\coreclr10\tests\src\JIT\config\benchmark+intrinsic\benchmark+intrinsic.csproj : warning NU1603: benchmark+intrinsic depends on System.Memory (>= 4.6.0-preview1-26907-04) but System.Memory 4.6.0-preview1-26907-04 was not found. An approximate best match of System.Memory 4.6.0-preview3-26501-01 was resolved. [F:\gh\coreclr10\tests\build.proj]
```

**Comment by BruceForstall** [comment]
This is obsolete

**Comment by trylek** [comment]
Status update: without the warnAsError:0 clause, there are currently three remaining failures in the Pri1 test build:

<pre>
Undefined implementation in ExportedType 'ABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFG' -- ExportType not emitted [/__w/1/s/src/tests/Loader/classloader/rmv/il/RMV-2-5-5-two.ilproj]
Non-sealed value class, made sealed [/__w/1/s/src/tests/reflection/ldtoken/byrefs.ilproj]
Undefined implementation in ExportedType 'ABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGH.ABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFG' -- ExportType not emitted [/__w/1/s/src/tests/Loader/classloader/rmv/il/RMV-2-5-8-two.ilproj
</pre>

**Comment by tannergooding** [comment]
@trylek, is it intended that the conversation is still locked/limited to collaborators only?

**Comment by trylek** [comment]
@tannergooding - not intentional, it looks like the msftbot modified the conversation like this after Bruce closed the issue. At this point I have absolutely no idea how to change that.

**Comment by deeprobin** [comment]
Are these warnings still occuring in upstream? If yes, is there some reference PR for backporting?

**Comment by deeprobin** [comment]
friendly ping @trylek :smile:
