### ISSUE TITLE
Assertion failed 'HBtab->ebdTryBeg == block'

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#110756]
```
    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
      Condition(s) not met: "DebuggerIsAttached"

Assert failure(PID 5226 [0x0000146a], Thread: 1282310 [0x139106]): Assertion failed 'HBtab->ebdTryBeg == block' in 'System.Threading.Tasks.ConcurrentExclusiveSchedulerPair:ProcessAsyncIfNecessary(ubyte):this' during 'Optimize layout' (IL size 417; hash 0xbae16b5b; Tier1)

    File: /Users/runner/work/1/s/src/coreclr/jit/jiteh.cpp:1296
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=896520
Build error leg or test failing: System.Threading.Tasks.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/110749

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Assertion failed 'HBtab->ebdTryBeg == block'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=896520
**Error message validated:** `[Assertion failed 'HBtab->ebdTryBeg == block'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 12/16/2024 8:56:59 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[900821](https://dev.azure.com/dnceng-public/public/_build/results?buildId=900821)|dotnet/runtime|[System.Threading.Tasks.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=900821&view=ms.vss-test-web.build-test-results-tab&runId=23642952&resultId=211973)|dotnet/runtime#110677|
|[898652](https://dev.azure.com/dnceng-public/public/_build/results?buildId=898652)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=898652&view=ms.vss-test-web.build-test-results-tab&runId=23586590&resultId=206179)|dotnet/runtime#110813|
|[896520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=896520)|dotnet/runtime|[System.Threading.Tasks.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=896520&view=ms.vss-test-web.build-test-results-tab&runId=23516364&resultId=211766)|dotnet/runtime#110749|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|3|

**Comment by AndyAyersMS** [comment]
fyi @amanasifkhalid
