### ISSUE TITLE
Dotnet 9 new DLL's not found

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#110786]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Dotnet-9-new-DLLs-not-found/10806253)._

---
[severity:It's more difficult to complete my work]
I created a new project (Console Application) in dotnet 9 for some Benchmarks. I wanted to compare my old code to new code, optimized with features of dotnet 9. Namely, the TensorPrimitives class. This class, and the entire System.Runtime.Tensors-Namespace didnt exist according to Visual Studio. I have installed and verified the installation of the dotnet 9 SKD and the dotnet 9 runtime on my machine. I have tried to repair Visual Studio with the Visual Studio Installer. I have tried reinstalling dotnet 9. I have tried rebuilding my Project, including deleting the "bin" and "obj" folders and rebuilding from there. But i was not successful. I dont know which features are also missing, but this is the most notable one for me. It seems as if it just doesnt exist on my Computer, eventhough it is described as provided with the dotnet 9 SDK. I can find this DLL on Nuget. But i dont want to install every DLL manually from Nuget, when it says, it comes with the SDK.

---
#### Feedback Bot on 12/5/2024, 06:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by richlander** [comment]
Do you have a reference to the `System.Numerics.Tensors` package?

- https://www.nuget.org/packages/System.Numerics.Tensors
- https://learn.microsoft.com/dotnet/core/whats-new/dotnet-9/libraries#tensorprimitives

@tannergooding

**Comment by huoyaoyuan** [comment]
> But i dont want to install every DLL manually from Nuget, when it says, it comes with the SDK.

NuGet is a core part of .NET SDK. Where does it says "it comes with the SDK"? The [documentation](https://learn.microsoft.com/dotnet/api/system.numerics.tensors.tensorprimitives) says clearly "package provided".

**Comment by tannergooding** [comment]
`System.Numerics.Tensors` is not provided in-box currently, it is an independent NuGet package that must be independently referenced.

It may become in-box in the future, but there is no guarantee if that will happen or when it would happen if that does come to pass.

**Comment by richlander** [comment]
This issue is from `vsfeedback`. As a result, I'm going to close it. I think we've answered the question.
