### ISSUE TITLE
[API Proposal]: Record equality compare collection content only

### ISSUE THREAD

**Issue by MickaelThumerel** [dotnet/runtime#110806]
### Background and motivation

When using record i encounter often an equality issue.

Example :
``` csharp
public sealed record class RssItem(string Uid,
                                   string Link,
                                   string Title,
                                   string Description,
                                   string? Content,
                                   string SourceId,
                                   IReadOnlyCollection<string> Categories);
```
**Problem**: Using collection interfaces in records can lead to unexpected behavior in equality comparisons. This is because the default hashCode and equals implementations rely on the specific collection type, which can change after serialization/deserialization.

**Solution**: While manually implementing IEquality<> can address this issue, it reduces the benefits of using records.

Proposal: A simple attribute could be added to the parameter declaration to instruct the code generator to compare the collection's content rather than its type. 

This would streamline the process and maintain the advantages of using records.

``` csharp
public sealed record class RssItem(string Uid,
                                   string Link,
                                   string Title,
                                   string Description,
                                   string? Content,
                                   string SourceId,
                                   [**EqualityContentCheckOnly**] IReadOnlyCollection<string> Categories);
```

**Comment by huoyaoyuan** [comment]
The rule of record equality checking belongs to C# language at https://github.com/dotnet/csharplang/discussions , not the runtime.

Also be aware that the definition of collection equality can be ambiguous between sequence equality or set equality.

See https://github.com/dotnet/csharplang/discussions/8245, https://github.com/dotnet/csharplang/discussions/4845 and so on.
