### ISSUE TITLE
Debugging Issue VS 2022 .net 9

### ISSUE THREAD

**Issue by claimrevolution** [dotnet/runtime#110841]
### Description

Since I upgraded to .net 9 I've noticed a random debugging problem.  When stepping over code the debugger will jump to the next break point as if hit continue. It seems to be random but happens more often than not.  It feels like I'm running something with async and wait and forgot the await part somewhere, but the code I've been using are standard non parallel calls so there are no asyncs going on. 

### Reproduction Steps

debug code, put several break points. I recommend iterating through a list then a break point at the start and then several in deeper methods.  then start stepping over code in those deep methods.  it will magically hit the break point at the start of the loop.

### Expected behavior

it should keep stepping over code and not hit the next break point randomly.

### Actual behavior

the debugger doesn't all ways step over code and going to the next line.  it jumps to the next break point.

**Comment by tommcdon** [comment]
Duplicate to #109785, #109812, #109885
