### ISSUE TITLE
VS IDE - Stepping through code is flaky

### ISSUE THREAD

**Issue by Sean4572435243** [dotnet/runtime#110913]
### Description

I have a complex console app with lots of awaits that when stepping through the code (e.g. F10), will frequently just resume running as if I hit continue.  Nothing predictable about it.  Other than the awaits, it's not inherently parallel code.  Setting breakpoints or clicking the little green inline play buttons works as expected every time.  

### Reproduction Steps

Too flaky to define reproduction steps, though it seems more reliable if I don't delay stepping forward.

### Expected behavior

In my mind, F10 should work like clicking on the inline play button on the next line to execute.

### Actual behavior

Will frequently and unpredictably just continue executing instead of stepping

### Regression?

Honestly not sure when it started happening, feels like this has been broken for a bit and I've been hoping it would have been remedied by now, but now that we're in a AspNetCore 9, probably needs to be pointed out.

### Known Workarounds

been setting breakpoints and using the inline green arrow buttons to better control step execution.  Very cumbersome since if conditions have to be mentally evaluated to know where execution steps to next so I can manually step in that direction.

### Configuration

Latest everything for .Net, VS 2022 and ASPNetCore 9.  High-end recent Lenovo Intel.

**Comment by huoyaoyuan** [comment]
Duplicate to https://github.com/dotnet/runtime/issues/109785, https://github.com/dotnet/runtime/issues/109812, https://github.com/dotnet/runtime/issues/109885, https://github.com/dotnet/runtime/issues/110841

**Comment by Sean4572435243** [comment]
Apolgies!  There was no checkbox for me to confirm this is not a prior issue so I just didn't think about checking for priors first.  I'll close my duplicate.
