### ISSUE TITLE
[API Proposal]: Random.NextArray function

### ISSUE THREAD

**Issue by CypherPotato** [dotnet/runtime#110903]
### Background and motivation

The motivation for this issue is that I needed to perform a similar task, but I couldn't find any native way to do it. I wondered why there isn't something ready in the System.Random class, which already has helpers for generating random data, and I believe this suggestion makes sense.

### API Proposal

The behavior is simple and straightforward. The following extension function does exactly what I am proposing.

```csharp
public static T NextArray<T> ( this Random random, IReadOnlyList<T> items ) {
    return items [ random.Next ( 0, items.Count ) ];
}
```

Or within the Random class:

```csharp
public static T NextArray<T> ( IReadOnlyList<T> items ) {
    return items [ this.Next ( 0, items.Count ) ];
}
```

In .NET 9 we could extend `IReadOnlyList<T>` to allow `params` in the parameter.

### API Usage

```csharp
string [] fruits = [ "Apple", "Mango", "Tomato", "Blueberry" ];
string randomFruit = Random.Shared.NextArray ( fruits );

Console.WriteLine ( randomFruit );
```

### Risks

Perhaps a risk would be trying to access an item after it has been removed and the `Count` has been reduced shortly after accessed. A lock would solve this, but we would have to change the input type, as `IReadOnlyList<T>` does not implement `ICollection.SyncRoot`.

**Comment by huoyaoyuan** [comment]
The proposed name is confusing. `NextArray` means returning an array. The proposed functionality is to return one random element from an array-like.

In real-world usage, there are also usage that requires no duplications while randomly picking items. This is more complicated and can be helped by `Random.Shuffle`. On the other hand, `items[random.Next(0, item.Count)]` is too trivial.

**Comment by CypherPotato** [comment]
@huoyaoyuan `NextItem` maybe? I didn't thinked so much about the method name, but that's not the issue main objective. And, I disagree, it's not so trivial, I've come across some situations like choosing a welcome message from a list of pre-defined messages. Depending on how it is implemented, it leaves room for small errors which can break the code in runtime.

In the case of duplicates, it would only make sense if you were getting several random items from an array in series, not something momentary. If it's the first case and you need to filter results, `NextArray` may not be the best way to do it.

**Comment by colejohnson66** [comment]
`IEnumerable` would not work because the size of the enumeration is unbounded. Randomly sampling it is impossible.

**Comment by KeterSCP** [comment]
This was previously proposed and rejected in https://github.com/dotnet/runtime/issues/80651#issuecomment-1452475498
