### ISSUE TITLE
where `DISABLE_ASSERT_MESSAGES` defined

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#110941]
we have found the browser-wasm have disabled the g_warning by define DISABLE_ASSERT_MESSAGES marco but I can't found where defined it.

**Comment by akoeplinger** [comment]
The DISABLE_ symbols are generated based off of options in options.cmake and this code: https://github.com/dotnet/runtime/blob/2b60d82ef3e87876128b7f71922a1b72908b6fcf/src/mono/CMakeLists.txt#L72-L81

The assert_messages one comes from here: https://github.com/dotnet/runtime/blob/2b60d82ef3e87876128b7f71922a1b72908b6fcf/src/mono/mono.proj#L557
