### ISSUE TITLE
[API Proposal]: Implement Read short, int, long and their unsigned versions to stream

### ISSUE THREAD

**Issue by Mrgaton** [dotnet/runtime#110944]
### Background and motivation

```cs
  public static (PacketType type, byte[] data, bool signed) DecodePacket(byte[] packet)
  {
      using (MemoryStream ms = new(packet))
      {
          PacketType type = (PacketType)ms.ReadByte();

          int dataSize = ms.ReadInt();
      }
  }
```

this could make code a lot shorter and cleaner.

### API Proposal

```csharp
using System.Buffers;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;

namespace System.IO
{
    public abstract class Stream : MarshalByRefObject, IDisposable, IAsyncDisposable
    {
          public virtual int ReadByte()
          {
              var oneByteArray = new byte[1];
              int r = Read(oneByteArray, 0, 1);
              return r == 0 ? -1 : oneByteArray[0];
          }

          public virtual uint ReadUInt()
          {
             //code
          }
          public virtual long ReadLong()
          {
             //code
          }

          public virtual ulong ReadULong()
          {
             //code
          }
     }
}
```

### API Usage

```csharp
using (MemoryStream ms = new(data))
{
    int dataSize = ms.ReadInt();
    long dataLongSize = ms.ReadLong();
}
```

### Alternative Designs

Let your thoughts on the comments

### Risks

No one?

**Comment by huoyaoyuan** [comment]
It's done by `BinaryReader`.

Moreover, the pattern is not optimal for decoding packets in real world practice. Endianness must be specified for type longer than 1 byte. It's also not performance to do a `Read` call to stream for every element.

**Comment by Mrgaton** [comment]
> It's done by `BinaryReader`.
> 
> Moreover, the pattern is not optimal for decoding packets in real world practice. Endianness must be specified for type longer than 1 byte. It's also not performance to do a `Read` call to stream for every element.

For things like this one is very useful for me 

```csharp
public static byte[] EncodePacket(PacketType type, byte[] data, byte[]? privateKey)
{
    using (MemoryStream ms = new())
    {
        ms.WriteByte((byte)type);
        ms.Write(BitConverter.GetBytes(data.Length), 0, sizeof(int));
        ms.Write(data, 0, data.Length);

        if (privateKey != null)
        {
            byte[] signature = ECDsaHelper.SignData(data, privateKey);

            ms.WriteByte((byte)signature.Length);
            ms.Write(signature, 0, signature.Length);
        }
        else
        {
            ms.WriteByte(0);
        }

        return ms.ToArray();
    }
}
```

**Comment by elgonzo** [comment]
Is there a particular reason why you are using a MemoryStream instead of a byte array/buffer directly? Because then you can use Span-related functions to populate the byte array such as those provided by https://learn.microsoft.com/en-us/dotnet/api/system.buffers.binary.binaryprimitives

**Comment by huoyaoyuan** [comment]
It's anti-pattern to invoke `Stream` intensively. The common practice is to fill all the bytes and call `Write` only once.

**Comment by huoyaoyuan** [comment]
Also note that using `BitConverter` is actually a bug. It depends on current endianness, which is unsuitable for network communication. Do use `BinaryPrimitives` to specify endianness.

**Comment by Mrgaton** [comment]
I wanted to do it as low level as possible to make it fast meanwhile the code looks at least good, and why bit converter has endianness.

Also writing multiple times to a stream usually don't directly writes them until you flush it but thanks all for the wisdom.

And I think that span<byte> may be slower.

**Comment by elgonzo** [comment]
> I wanted to do it as low level as possible to make it fast meanwhile 

But you didn't.

It's not low-level, because instead of using and working with a byte array directly (which is what your method is returning), you are using MemoryStream which internally has to manage a byte array / buffer which it potentially has to resize during usage since it doesn't know in advance how much data you are going to write to it.

It's not fast for the same reason: You are using a MemoryStream, which is a layer between your code and the byte array being created as well as the potential cost of MemoryStream possibly having to resize the internal byte array if the initial default size of that array turned out to be not large enough...

**Comment by Mrgaton** [comment]
So do you recommend me declaring a byte array and copy data with marshal.

**Comment by elgonzo** [comment]
> So do you recommend me declaring a byte array and copy data with marshal.

What exactly do you mean by saying "marshal"?

**Comment by huoyaoyuan** [comment]
> I wanted to do it as low level as possible to make it fast meanwhile the code looks at least good

`MemoryStream` is not the correct thing to use for low level.

You can find some examples in this repo for composing packets:

https://github.com/dotnet/runtime/blob/2b60d82ef3e87876128b7f71922a1b72908b6fcf/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocksHelper.cs#L213-L294

**Comment by CyrusNajmabadi** [comment]
> and why bit converter has endianness.

Because there are big endian and little endian machines. And the endianness of the machine you are reading or writing the data on may not match the format of the data being read or written.
