### ISSUE TITLE
JIT fails to resolve MemberRefs and TypeRefs to members added during EnC

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#11107]
The repro below needs a modified version of Roslyn IDE with disabled rude edit detection for this case.

project A:
 
       public class C
       {
              // public void F() { Console.WriteLine(1); }
       }

project B:
 
       class Program
       {
              static void Main(string[] args)
              {
                    new C();
                    G();
              }
 
              static void G()
              {
                     var c = new C();
                    // c.F();
              }
       }
 
Step into Main of ProjectB, then uncomment both comments (in project A and B), then step into G().
 
Actual:
MissingMethodException: "Method void C.F is missing"
 
Expected:
No error.

**Comment by davmason** [comment]
Closing as by design
