### ISSUE TITLE
Endless loop in UnwindManagedExceptionPass1 on ARM64

### ISSUE THREAD

**Issue by chingchenms** [dotnet/runtime#11117]
The exception is because the native dll has some dependence not there, and triggers a type initiation exception, 
This is a bug in this UnwindManagedExceptionPass1, it never exit, using lldb has clear proved it, I hope someone can fix it . 

(lldb) bt
* thread dotnet/coreclr#1, name = 'dotnet', stop reason = signal SIGSTOP
  * frame #0: 0x0000007fa5f3f7ec libcoreclr.so`_ULaarch64_access_reg + 40
    frame dotnet/coreclr#1: 0x0000007fa5f061f0 libcoreclr.so`UnwindContextToWinContext(unw_cursor*, _CONTEXT*) + 224
    frame dotnet/coreclr#2: 0x0000007fa5f06648 libcoreclr.so`PAL_VirtualUnwind + 292
    frame dotnet/coreclr#3: 0x0000007fa5cc66f0 libcoreclr.so`UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 396
    frame dotnet/coreclr#4: 0x0000007fa5cc6950 libcoreclr.so`DispatchManagedException(PAL_SEHException&, bool) + 256
    frame dotnet/coreclr#5: 0x0000007fa5c50ac8 libcoreclr.so`JIT_GetSharedNonGCStaticBase_Helper + 564
    frame dotnet/coreclr#6: 0x0000007f2dab2c8c
    frame dotnet/coreclr#7: 0x0000007f2d50d454
    frame dotnet/coreclr#8: 0x0000007fa5cccf84 libcoreclr.so`CallDescrWorkerInternal + 132
    frame dotnet/coreclr#9: 0x0000007fa5c133b0 libcoreclr.so`MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) + 1120
    frame dotnet/coreclr#10: 0x0000007fa5cec120 libcoreclr.so`RunMain(MethodDesc*, short, int*, PtrArray**) + 660
    frame dotnet/coreclr#11: 0x0000007fa5cec44c libcoreclr.so`Assembly::ExecuteMainMethod(PtrArray**, int) + 380
    frame dotnet/coreclr#12: 0x0000007fa5b60004 libcoreclr.so`CorHost2::ExecuteAssembly(unsigned int, char16_t const*, int, char16_t const**, unsigned int*) + 480
    frame dotnet/coreclr#13: 0x0000007fa5b3b6ec libcoreclr.so`coreclr_execute_assembly + 232
    frame dotnet/coreclr#14: 0x0000007fa62eb9c8 libhostpolicy.so`___lldb_unnamed_symbol1629$$libhostpolicy.so + 144
    frame dotnet/coreclr#15: 0x0000007fa62ddc28 libhostpolicy.so`___lldb_unnamed_symbol1314$$libhostpolicy.so + 4820
    frame dotnet/coreclr#16: 0x0000007fa62de348 libhostpolicy.so`corehost_main + 184
    frame dotnet/coreclr#17: 0x0000007fa63b2664 libhostfxr.so`___lldb_unnamed_symbol1620$$libhostfxr.so + 240
    frame dotnet/coreclr#18: 0x0000007fa63bc05c libhostfxr.so`___lldb_unnamed_symbol1694$$libhostfxr.so + 3628
    frame dotnet/coreclr#19: 0x0000007fa63bce4c libhostfxr.so`___lldb_unnamed_symbol1697$$libhostfxr.so + 432
    frame dotnet/coreclr#20: 0x0000007fa63bc578 libhostfxr.so`___lldb_unnamed_symbol1695$$libhostfxr.so + 796
    frame dotnet/coreclr#21: 0x0000007fa63b28c4 libhostfxr.so`hostfxr_main_startupinfo + 172
    frame dotnet/coreclr#22: 0x000000000040da6c dotnet`___lldb_unnamed_symbol29$$dotnet + 1364
    frame dotnet/coreclr#23: 0x000000000040dcc8 dotnet`___lldb_unnamed_symbol30$$dotnet + 168
    frame dotnet/coreclr#24: 0x0000007fa64338a0 libc.so.6`__libc_start_main(main=0x0000000000000000, argc=0, argv=0x0000000000000000, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=<unavailable>) at libc-start.c:291
    frame dotnet/runtime#3858: 0x000000000040bbb0 dotnet`_start + 40

(lldb) clrstack
OS Thread Id: 0x2773 (1)
        Child SP               IP Call Site
0000007FF741CC90 0000000000000000 [HelperMethodFrame: 0000007ff741cc90]
0000007FF741CE00 0000007F2DAB2C8C System.Fabric.FabricDeployer.DeployerTrace.WriteError(System.String, System.Object[])
0000007FF741CE20 0000007F2D50D454 System.Fabric.FabricDeployer.Program.Main(System.String[]) [/home/chingc/wf/src/prod/Setup/FabricDeployer/Program.cs @ 40]
0000007FF741DD50 0000007fa5ccc934 [HelperMethodFrame: 0000007ff741dd50]
0000007FF741DEC0 0000007F2D50EDFC System.Fabric.FabricDeployer.DeployerTrace.WriteInfo(System.String, System.Object[])
0000007FF741DEE0 0000007F2D50D2D0 System.Fabric.FabricDeployer.Program.Main(System.String[]) [/home/chingc/wf/src/prod/Setup/FabricDeployer/Program.cs @ 23]
0000007FF741E288 0000007fa5cccf84 [GCFrame: 0000007ff741e288]
0000007FF741E688 0000007fa5cccf84 [GCFrame: 0000007ff741e688]    frame dotnet/runtime#3858: 0x000000000040bbb0 dotnet`_start + 40

**Comment by mangod9** [comment]
Closing this issue since this is old. If this still repros please reactivate.
