### ISSUE TITLE
unable to "dotnet restore" to use my own build of coreclr

### ISSUE THREAD

**Issue by peterremote1980** [dotnet/runtime#11137]
i am following https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingDotNetCli.md but can't success, please help

<img width="2560" alt="screen shot 2018-09-22 at 9 23 47 pm" src="https://user-images.githubusercontent.com/36571333/45917687-dd868380-bead-11e8-8f3c-0166768596cd.png">

**Comment by AaronRobinsonMSFT** [comment]
This workflow has been substantially updated - https://github.com/dotnet/runtime/blob/main/docs/workflow/using-dotnet-cli.md.
