### ISSUE TITLE
Add features to help diagnose unloading issues

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#11157]
There are many things that can prevent successful unload of AssemblyLoadContext, like threads running in the context, GC handles holding references to objects of types loaded into the context, other external references to objects of types loaded into the context etc. It is inherently non-trivial to debug such issues and so we need to figure out what we can do to help diagnose such issues. This can be done on the runtime side or the debugger side.

**Comment by raffaeler** [comment]
@janvorli do you have any update on this?
I am currently trying to follow your suggestion to find the AssemblyLoadContext ...

**Comment by raffaeler** [comment]
@janvorli gently pinging :)

**Comment by janvorli** [comment]
@raffaeler I am sorry for missing your previous comment. There were no additions to the diagnostic tools since the SOS commands were fixed to properly handle dependencies for unloadable objects. 
Have you seen my doc https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability? There is a lot of detail on how to debug unloadability issues.
If that's not helpful for your case, please share more details on your problem and I'll be happy to help you to debug it.

**Comment by raffaeler** [comment]
@janvorli Thanks for your answer.
I know that document and it is not always straightforward understanding which is the ALC for each object.
I am currently using the new CLRMD 2.0 release and searching for  System.Reflection.LoaderAllocator instances, it is difficult to understand which objects belong to each ALC.
Do you have any hints? (I am trying to do that programmatically)

**Comment by janvorli** [comment]
Unfortunately, this is the case when you currently need a native debugger (WinDbg on Windows, LLDB on Unix) and follow the steps I've suggested. It is true though that I didn't write these steps in an easy to follow detailed way that one could easily follow, but rather as a brief explanation of the issue. 
If using the native debugger is an option for you, I'd be happy to put down an exact step by step way to get that. 
Obviously, the ideal way would be to add that to the SOS extension so that you can just run a SOS command to get an AssemblyLoadContext for a given object. And having the same ability in clrmd.

**Comment by raffaeler** [comment]
@janvorli thanks again.
Yes, it is a feasable option. I would be very interested in having the detailed information using a native debugger.
BTW I wrote a debugger for a customer and I could integrate that in my code if they will, therefore, it would be really precious.

**Comment by janvorli** [comment]
Ok, let me put it together for you.

**Comment by raffaeler** [comment]
I am reading from my phone and I can't get where did you take the addresses ending as 17f0 and 3672. But tomorrow morning I will try to understand with windbg and replicate it with clrmd which has the access to the while process  memory.
Thanks

**Comment by janvorli** [comment]
Oops, I've done it twice and maybe combined them by the end. Let me fix it.

**Comment by janvorli** [comment]
It should be correct now.

**Comment by raffaeler** [comment]
Bingo, I was able to get the name of the ALC for the object using CLRMD.
The obvious questions is:
how likely the vtable offsets `0x4e0` and `0x160` could change in future releases? (minor, major, ...)

Disclaimer: I absolutely understand and agree that I cannot rely on them in production and that you could change it at any time.
But since this is just a programmatic way to repeat the same actions you do in WinDbg, it's an acceptable risk if they don't change very often (as I would expect).
In any case, I can at least get the offsets from the PDBs, but in this case I would ask you how likely the field names could change in the future.

Thank you

**Comment by weltkante** [comment]
I assume you're asking for name consistency in LTS/service updates? For major releases you already have to test for compatibility anyways, they may have added new features or changed the way you reach the ALC (e.g. another indirection). I don't think its possible to "guarantee" indefinite upwards compatibility without abstracting the process away into the DAC.

**Comment by raffaeler** [comment]
@weltkante as I wrote I am not expecting any assurance for leaving that unchanged.
Anyway, reading many core parts of the runtime, I can see comments where the vtable is considered as a published contract and very unlikely to change in the future.
I just wanted to have an idea from @janvorli, take that as an estimation of probability if you will.

**Comment by janvorli** [comment]
@raffaeler these are not vtable offsets but rather field offsets in the types. I think that they can change any time. Also note that they are different between 32 and 64 bit platforms and may be different between windows / unix or even architectures.

I would rather enable clrmd to be able to access those fields. If I recall it correctly, clrmd uses DAC to access stuff from the managed process. I want to add a SOS command to extract the ALC for object too, so I'd need to expose all the necessary information via DAC and then it might be simple to let clrmd take advantage of that.

**Comment by weltkante** [comment]
clrmd is only doing managed analysis and removed the native PDB reader

**Comment by raffaeler** [comment]
@janvorli That sounds a very good plan.
Any estimated timeframe?

**Comment by janvorli** [comment]
I am not sure how much time it would take. I can see that the whole CLRPrivBinderAssemblyLoadContext is not exposed via DAC and neither is the m_binderToRelease field of AssemblyLoaderAllocator. Exposing some stuff via DAC might have a domino effect (you'd need to expose more types that these depend on).
I'll take an initial look in the next couple of days to get better idea on this.

**Comment by janvorli** [comment]
@raffaeler I have merged in a change that exposes a new method on ISOSDacInterface8, named GetAssemblyLoadContext that gets address of the managed AssemblyLoadContext for a given MethodTable. So I hope it should be easy to consume it in the clrmd. It works for both collectible and non-collectible AssemblyLoadContexts, including the default one. As for the default one, the managed part is created on demand, so the method will return null if it was not created yet.

**Comment by raffaeler** [comment]
Thank you @janvorli!!
I guess the integration should be done/modeled by @leculver now.
Great work :)

**Comment by leculver** [comment]
Yep, I will start on that work this week.

**Comment by tommcdon** [comment]
Closing as the appropriate DAC/CLRMD API's have been added.  Please feel free to open an issue in dotnet/diagnostics to track any needed SOS work.

**Comment by raffaeler** [comment]
Thank you all.
BTW @leculver do you have an issue on this in the CLRMD repo? Maybe it is already done and I didn't notice!

**Comment by leculver** [comment]
The underlying issue with adding this to ClrMD is that I really don't understand this .Net Core feature or what it means to debug it.  There's some code that exposes the raw concepts, here's the test that covers the basics of it:

https://github.com/leculver/clrmd/blob/232a21f5474ae34eb91f15a52e0e329fa3e8247f/src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs#L589

And the properties that expose things in `ISOSDacInterface8` are the properties around here:

https://github.com/leculver/clrmd/blob/232a21f5474ae34eb91f15a52e0e329fa3e8247f/src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs#L59

I'm not really sure if that's sufficient to diagnose problems in this area or not though.

**Comment by raffaeler** [comment]
I am already using `ClrObject.Type.LoaderAllocatorHandle` but you don't go far.
The goal is having the ability to retrieve the AssemblyLoadContext for each managed object.
The procedure requires jumping into native and coming back into managed memory as described by @janvorli [here](https://github.com/dotnet/runtime/issues/11157#issuecomment-642288660)

**Comment by janvorli** [comment]
@raffaeler the description you have mentioned was needed before I've added the the support for getting AssemblyLoadContext for MethodTable to DAC interface. No such jumps should be necessary anymore.

**Comment by raffaeler** [comment]
@janvorli Are you saying I should take `clrObject.Type.AssemblyLoadContextAddress` and get the matching object from there?
I tried on a dump with 2 ALCs but I always see zeros there.
What am I missing?

**Comment by janvorli** [comment]
Are you sure that specific object's type you were trying it with is actually loaded into a non-default ALC? Getting zero means that the object's type is loaded into the default assembly load context.

**Comment by raffaeler** [comment]
Yes, because I can see the other ALC by manually poking the memory as you detailed above

On Oct 15, 2020 00:40, Jan Vorlicek <notifications@github.com> wrote:

Are you sure that specific object's type you were trying it with is actually loaded into a non-default ALC? Getting zero means that the object's type is loaded into the default assembly load context.

**Comment by janvorli** [comment]
I can see that the AssemblyLoadContextAddress would return 0 also when the DAC was too old and didn't have the version 8 of the interface. Can you check that the _sos8.GetAssemblyLoadContext is actually being called?

**Comment by raffaeler** [comment]
I am not sure to fully understand the issue.
I can see `_sos8` field with the debugger, but it is null. Do I need a preview release of CLRMD or whatelse? (I am working with the nuget package that may be too old for this).

**Comment by janvorli** [comment]
> I can see `_sos8` field with the debugger, but it is null

That explains why you are getting always zero from the GetAssemblyLoadContext. Unless there is a bug in ClrMD in getting the _sos8 interface, it means that the mscordaccore.dll ClrMD was using is old and doesn't support the interface to get the AssemblyLoadContext. Since mscordaccore.dll is part of the runtime and matches 1:1 the coreclr.dll, that would mean that you are trying to debug version of runtime that doesn't support that interface. Please note that it is supported in 5.0 only (since preview 7), it was not back ported to 3.1.

**Comment by raffaeler** [comment]
Now I understand!
As you can see below, after recompiling the target app with .NET, it is working now :)

![image](https://user-images.githubusercontent.com/5183152/96111468-84994600-0ee1-11eb-85cf-e622e7b7db6b.png)

Thank you very much

**Comment by janvorli** [comment]
It is great to hear it works now

**Comment by raffaeler** [comment]
@janvorli one last question about this.
When I use `Assembly.LoadFile` and iterate through `AssemblyLoadContext.All` I can see a new `AssemblyLoadContext` named `Assembly.LoadFile(...fullpath...)`.

Anyway when I get a snapshot of the process, I can't find any object having `clrObject.Type.LoaderAllocatorHandle` different from zero.
What is the difference and how can I get the contexts created by the `Assembly.Load` and `Assembly.Load(byte[])` methods? (Am I missing other calls creating load contexts?)

Thank you!

**Comment by janvorli** [comment]
@raffaeler @vitek-karas is more knowledgeable in these areas of non-collectible contexts. I'll let him comment on this.

**Comment by vitek-karas** [comment]
`Assembly.LoadFile`:
The intent of this API is to always load that file - since there could be potentially multiple versions of the same assembly trying to load through this API, it needs to isolate them. So the algorithm is simple - for each file path it creates a new load context and loads the file into it. The load context is very simple - it just hosts that one assembly, and let's all dependency resolution fallback to the default load context.
The load context it uses is defined here: https://github.com/dotnet/runtime/blob/cfa7a19caa72e3655dd240d1becc6b5d25821b1e/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L815-L820

I know next to nothing about the debugger side of things though, so I can't really comment why it doesn't show up on the debugger side. From runtime's perspective it's just like any other secondary load context - there's nothing special about it.

`Assembly.Load(string)` - this one is meant to do something like "Load the specified assembly from/into current load context" - the tricky bit is the "current load context". It looks at the caller of the `Assembly.Load` and finds the load context the caller's type belongs to. It then behaves as if the code called `AssemblyLoadContext.LoadFromAssemblyName` on the caller's context. So for most cases it ends up loading the assembly through the default load context, but it really depends on the caller.

`Assembly.Load` is also affected by [`CurrentContextualReflectionContext` property](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.currentcontextualreflectioncontext?view=net-5.0). If that property is set, it will always load through/into that load context, regardless of the caller.

`Assembly.Load(byte[])` - this one is similar to `LoadFile` it always creates a new load context (uses the exact same one as LoadFile, just gives it a different name `Assembly.Load(byte[], ...)`) and then loads the bytes into it as if `AssemblyLoadContext.LoadFromStream` was called (not exactly the same, but they both end up in the same underlying implementation eventually).

If you're building a new app which uses assembly loading, I would strongly encourage using APIs on `AssemblyLoadContext` and not use any of the `Assembly.Load*` APIs.

**Comment by raffaeler** [comment]
Thank yuou @vitek-karas and @janvorli 

I am just trying to understand how can I identify the object instances that were created from assemblies belonging to a different ALC.
- If I create a collectible ALC, thanks to the DAC changes made by @janvorli , I can now walk from the object to the ALC through the allocator handle.
- If the ALC is created by one of the Assembly.LoadXXX calls you mentioned, I can see different ALCs created, but the allocator handle is always zero (which means default context)

Why are they different? Have I any chances to understand if an object belongs to a different ALC also for those cases?

Thanks!

**Comment by vitek-karas** [comment]
It is possible from the managed code itself, but I don't know if the debugger can do this.

If I assume `myObject` is the instance I'm interested in, then the load context it belongs to can be determined by:
```C#
var alc = AssemblyLoadContext.GetLoadContext(myObject.GetType().Assembly);
```

**Comment by raffaeler** [comment]
>It is possible from the managed code itself, but I don't know if the debugger can do this.

Let's stay in the managed code for the moment.
If I have loaded the assembly twice, in two different ALCs, will `myObject.GetType().Assembly` disambiguate the two?
Thanks

**Comment by raffaeler** [comment]
@vitek-karas Is `collectible = false` the reason why the loader allocator is zero? I don't get why the two cases are different

**Comment by vitek-karas** [comment]
Yes - the `Assembly` will be unique (as in you will get two different instances for each of the loads) and each instance will belong to its own ALC. There's basically a `Dictionary<string, Assembly>` on each ALC, the `ALC.GetLoadContext` does a reverse lookup - that's all.

**Comment by vitek-karas** [comment]
"load allocator" != "load context"
@janvorli would know exactly how this works, but my understanding is that each ALC belongs to some "load allocator". If the ALC is not unloadable I would image it falls into the "default" load allocator used by the default ALC as well. If the ALC is unloadable, then it needs to create its own load allocator.

Paraphrasing a little bit: the operation of freeing the resources during ALC unload is done by freeing the load allocator it belongs to. (but maybe I understand this wrong).

**Comment by raffaeler** [comment]
Makes sense, thank you. If !@janvorli has some idea, it would be more than welcome :)

With regards to the debugging investigation, I guess I should look into the dictionary and do the reverse by myself. I'll try that.
If the ALCs are also stored elsewhere, please let me know @vitek-karas .

**Comment by vitek-karas** [comment]
There's no real dictionary... sorry - I simply used it as a way to describe what happens. Unfortunately all of this is done in native code. I "think" this is exposed to debugger somehow - I remember we worked on fixing the debugger for cases like you mention (the same assembly loaded twice) - it used to crash the debugger, but it works now. I just don't remember the details anymore.
