### ISSUE TITLE
Span bounds checking not fully eliminated in some cases when index is constant and length is known

### ISSUE THREAD

**Issue by gdkchan** [dotnet/runtime#1115]
I have some code that basically reads and writes to a given memory region, with a offset. I had one for each integer type, and also a generic one for structs etc.

I decided, with the use of spans, check if I could remove all the integer read/write methods and just use the generic method instead. So instead of:
```
int x = ReadInt32(offset);
```
I could just do:
```
int x = Read<int>(offset);
```
After checking the code generated for both, I noticed that the one generated for the generic variant was almost as good as the specialized one, with the exception of an odd issue, the bounds check was not fully eliminated.

Here's some test code that highlights the issue:
```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

public class C
{
    private IntPtr _ptr;
    
    public C(IntPtr ptr)
    {
        _ptr = ptr;
    }
    
    public int ReadInt32(int offset)
    {
        return Read<int>(offset);
    }
    
    public unsafe int ReadInt32Fast(int offset)
    {
        return *(int*)(_ptr + offset);
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public T Read<T>(int offset) where T : struct
    {
        return MemoryMarshal.Cast<byte, T>(GetDataSpan(offset, Unsafe.SizeOf<T>()))[0];
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private unsafe Span<byte> GetDataSpan(int offset, int size)
    {
        return new Span<byte>((void*)(_ptr + offset), size);
    }
}
```
SharpLab link [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6mpoDMTUgyE0A3jQYeGYqLwXYMMAxGGAAKGFAMAPpi4RrUngzunsT2QgAUwWERMVAAlEkebvEJntHhDAC8XrEFDAC+tbUpDLw8DGww2AAmwbakaa0YDBAAZiO4MBj5xYW1CcQA7O2dXQA8gwB8aaPjk7lxCQ0zicfN3LjYI4GDy929pABieBgDbTsTU7VFJclLAFSvDB/XJpMoRADUwzGH32tSOCVqAG0ALKTAAWEB64kkaVRGAxWLEkgA8jFeBAuLgWABBADmtNguFwvhgRkkrVatNyAF0mvYACq3Nb8rY3d57BgAdzRMkCgpADFw4Q4YAwXzmvwYqPw0AAnsjsFBcGjsJJhM9VsBdQE0AwRWkAOKTAAi/mwsjE2C422hk1tAFVKZdBLJeAAvGDEkare25OOIujcg6eeGeJF4gkGbG49GYrNE0l8ClUukM1TMhSsrjsricnm1by+fyBc7Bhger2W60wDYMJ0YV0Yd2e71i30YW03ZkR6YJb4/JhLLgwSXtkddgJbNLEFDA0E5BiQ8VTW3TmCw45HOpAA==).
Code generated for the ReadInt32 method:
```
C.ReadInt32(Int32)
    L0000: sub rsp, 0x28
    L0004: mov rax, [rcx+0x8]
    L0008: movsxd rdx, edx
    L000b: add rax, rdx
    L000e: mov edx, 0x1
    L0013: cmp edx, 0x0
    L0016: jbe L0025
    L0018: mov eax, [rax]
    L001a: add rsp, 0x28
    L001e: ret
    L001f: call 0x7fff231aed50
    L0024: int3
    L0025: call 0x7fff231aef00
    L002a: int3
```
This is the odd part:
```
    L000e: mov edx, 0x1
    L0013: cmp edx, 0x0
    L0016: jbe L0025
```
It's doing a comparison with constant values. As far I can tell, 1 is the length and 0 the index. Since they are constant, constant folding should evaluate 1U <= 0U == false, and so we know that the branch is never going to be taken, since the condition is always false. So the comparison and jump should be eliminated, and then the other part of the code would become unreachable. It looks like `L001f` is already unreachable aswell, so I don't know why the code is still there. It looks like that whichever optimization pass is responsible for optimizing length checks runs too late on the compiler pipeline, and so the other optimizations are not kicking in.

The goal is generating the same or as efficient code for ReadInt32 and ReadInt32Fast.

category:cq
theme:value-numbering
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
Naively unblocking the constant eval `VNF_CastOvf` paths in value numbering fixes this (a real fix would need to be more careful about handling overflow). The issue is that we have a dead overflow cast but don't optimize that path away until too late.

```asm
G_M5540_IG01:
       sub      rsp, 40
						;; bbWeight=1    PerfScore 0.25
G_M5540_IG02:
       mov      rax, qword ptr [rcx+8]
       movsxd   rdx, edx
       add      rax, rdx
       mov      eax, dword ptr [rax]
						;; bbWeight=1    PerfScore 4.50
G_M5540_IG03:
       add      rsp, 40
       ret      
						;; bbWeight=1    PerfScore 1.25
G_M5540_IG04:
       call     CORINFO_HELP_OVERFLOW
       int3 
```

So if value numbering handled `VNF_CastOvf` with constant args (or if perhaps we did sparse conditional evaluation to avoid getting confused by at dead stuff), we would be able to simplify this.

Also would be nice to get rid of the dead overflow call.

category:cq
theme:optimization
skill-level:intermediate
cost: medium
