### ISSUE TITLE
Boxing is not optimized away in C# 7.1 `is Type value` expression

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/runtime#1116]
Consider the following C# program:
```csharp
using System;
using System.Runtime.CompilerServices;

class Container<T>
{
    private readonly T value;
    public Container(T value) => this.value = value;

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public TOther TryGet<TOther>() =>
        value is TOther ? (TOther) (object) value : default(TOther);
}

static class Program
{
    static void Main()
    {
        var container = new Container<Guid>(Guid.Empty);
        var count = 0;
        while (true)
        {
            // call a method where boxing may occur
            if (container.TryGet<Guid>() != default)
                Console.WriteLine("...");

            // monitor GC events due to boxing
            var newCount = GC.CollectionCount(0);
            if (newCount != count)
                Console.WriteLine(count = newCount);
        }
    }
}
```

The class `Container<T>` is a simplified version of a class from our production code. If this program is compiled in Release mode and started without debugger, then JIT optimizes away the boxing in `Container<T>.TryGet` method despite an explicit cast to `object` (we need the cast to `object` there because C# does not allow direct casts between unrelated type parameters). Without `[MethodImpl(MethodImplOptions.AggressiveOptimization)]` attribute, the boxing occurs during several initial calls to the method, but is eventually eliminated (apparently, due to profile-guided optimization). So far, so good.

There is an obvious desire to rewrite `Container<T>.TryGet` method using C# 7.1 `is` construct to make it more readable:
```csharp
    public TOther TryGet<TOther>() => value is TOther other ? other : default;
```
This works correctly, but unfortunately, now a boxing occurs at each call because the IL generated by C# compiler now has a different shape. It would be great if the optimizer recognized this different shape of IL and was able to optimize away the boxing in this case as well.

---
**Version:**

`%ProgramFiles%\dotnet\shared\Microsoft.NETCore.App\5.0.0-alpha.1.19564.1\clrjit.dll`
File SHA1: `b02083f0e0106b0bdebffec61e1c0882704467fb`
File version: `5.0.19.56303`
Product version: `5,0,19,56303 @Commit: 2c4fb3250989f014550882f5d165cdc36ebdbd08`

**Comment by EgorBo** [comment]
A bit more simplified example: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAIBlAC2ygAcAZbYAOgCUBXAOwwEt8MANwBYAFDjiAZnLEATOQDC5AN7jx5TeQDaAKT4YA4jG4wofMAAoMAT3owIAM0t9eASkx2Hz1xjduAXQ0taXIAFQB5DGozcJhcDABGAB4wtHComKgAPksw8gA3bAAbThg3YM01MS1a2QB2QpKy8j5cDOjYgH5yPMyzN16IYAArGDA/JtKYchByABMYR2xOYow+zqg3URqtAF9K8kPDvQNjU3MrW3snF3d06+87v0DD0MjNuIS5VPSPrNy+SK0wquyqh1qxEawJabQ6WXIEE+PSRCLmi2WqwwO1qBzEeyAA===

I think there is already an issue for it somewhere.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/coreclr/issues/17670
