### ISSUE TITLE
[Linux/arm64] Test Failed: System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#11177]
```
/home/robox/echesako/git/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Threading.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
===========================================================================================================
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.26927.0)
  Discovering: System.Threading.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tests (found 178 of 206 test cases)
  Starting:    System.Threading.Tests (parallel test collections = on, max threads = 46)
    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999999
  Finished:    System.Threading.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Tests  Total: 396, Errors: 0, Failed: 1, Skipped: 0, Time: 44.019s
```

This took me a while to reproduce - but I got at least five exact failures.

**Comment by v-haren** [comment]
failed again in job: [runtime 20200506.84 ](https://dev.azure.com/dnceng/public/_build/results?buildId=633940&view=ms.vss-test-web.build-test-results-tab&runId=19752174&resultId=142362&paneView=debug)

failed test: System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide


Error message
Assert.Equal() Failure
Expected: 1000000
Actual: 999999


Stack trace
   at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide() in /_/src/libraries/System.Threading/tests/InterlockedTests.cs:line 326

**Comment by VSadov** [comment]
This should no longer be failing. 
Assuming the reason for the failure was outdated Linux kernel.

**Comment by BruceForstall** [comment]
@VSadov This is failing in our CI in every run. So if the reason is an "outdated" Linux kernel, that doesn't really matter, if our CI machines are running such a kernel.

**Comment by VSadov** [comment]
I thought the runs use new enough kernel now. It looked so from the logs.

**Comment by VSadov** [comment]
Reverting- https://github.com/dotnet/runtime/pull/35974

**Comment by VSadov** [comment]
Was the failure actually on Linux?

**Comment by BruceForstall** [comment]
Ah, right, looks like Windows: net5.0-Windows_NT-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

**Comment by VSadov** [comment]
Are other failures on Windows too? 
I wonder if there could be a testcase issue, since Windows implementation is supposed to be reliable.

**Comment by BruceForstall** [comment]
Here's another failure, on mono:

net5.0-Windows_NT-Release-x64-Mono_release-Windows.81.Amd64.Open

https://dev.azure.com/dnceng/public/_build/results?buildId=634699&view=ms.vss-test-web.build-test-results-tab&runId=19761034&paneView=debug

**Comment by BruceForstall** [comment]
The arm64 one: net5.0-Windows_NT-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

https://dev.azure.com/dnceng/public/_build/results?buildId=634482&view=ms.vss-test-web.build-test-results-tab&runId=19756224&paneView=debug

I take back what I said: it doesn't look like the failure is consistent in every run: it has failed on different platforms/architectures.

**Comment by BruceForstall** [comment]
Wow, I really need some coffee or something -- those links I gave are for a whole separate test failure :-(

**Comment by BruceForstall** [comment]
However, the issue opened by v-haren is this test, for Windows arm64.

**Comment by VSadov** [comment]
Yes, the original failure is real, and on Win10, which is a concern

**Comment by VSadov** [comment]
I wonder if there are more failures to see if there is some pattern. 
These kinds of failures often do not repro when you want them, so any extra information would help to narrow the search.

**Comment by BruceForstall** [comment]
Ok, looking at the Kusto data, this test failed only twice in the last 30 days, both on Windows arm64, both this morning.

**Comment by BruceForstall** [comment]
@VSadov I've been working to enable JIT stress testing of libraries test assets with checked CoreCLR. This means many, many more runs of the tests, with various stress modes, and also with a checked CoreCLR (which probably changes the timing compared to most runs). I've seen this failure several times. Multiple times last night for Windows arm64:

https://helix.dot.net/api/2019-06-17/jobs/fab27305-28ce-45fe-bb93-668d48d26279/workitems/System.Threading.Tests/console
with:
```
COMPlus_ReadyToRun=0
COMPlus_TieredCompilation=0
COMPlus_ZapDisable=1

    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999999
```

https://helix.dot.net/api/2019-06-17/jobs/7546e93d-1c70-495f-aab4-157f47307c71/workitems/System.Threading.Tests/console
with:
```
COMPlus_JITMinOpts=1
COMPlus_TieredCompilation=0

    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999978
```

https://helix.dot.net/api/2019-06-17/jobs/daf295dc-bd71-4b8b-941f-09ff6b6b4775/workitems/System.Threading.Tests/console
with:
```
COMPlus_JitStress=2
COMPlus_JitStressRegs=0x1000
COMPlus_TieredCompilation=0

    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999993
```

https://helix.dot.net/api/2019-06-17/jobs/1b78b81e-6003-4a99-85b7-f50485901120/workitems/System.Threading.Tests/console
```
COMPlus_JitStress=2
COMPlus_JitStressRegs=0x80
COMPlus_TieredCompilation=0

    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999997
```

https://helix.dot.net/api/2019-06-17/jobs/ac761b83-2f06-4ca4-b1ae-4d0fcc72e5dd/workitems/System.Threading.Tests/console
with:
```
COMPlus_JitStress=2
COMPlus_JitStressRegs=8
COMPlus_TieredCompilation=0

    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999998
```

https://helix.dot.net/api/2019-06-17/jobs/62be07e6-d52f-4b6f-b7d0-9d377024bb20/workitems/System.Threading.Tests/console
with:
```
COMPlus_JitStress=2
COMPlus_JitStressRegs=4
COMPlus_TieredCompilation=0

    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999998
```

I'm going to disable this test for JIT stress modes, for now.

**Comment by VSadov** [comment]
I have an open PR to re-disable the test - https://github.com/dotnet/runtime/pull/35974
We can merge that for now.

There is clearly an issue. Now on Windows...

**Comment by VSadov** [comment]
@BruceForstall  I have reverted the change that enabled this test

**Comment by BruceForstall** [comment]
This just failed in Linux arm (JitStress=2, JitStressRegs=3):

https://dev.azure.com/dnceng/public/_build/results?buildId=736732&view=ms.vss-test-web.build-test-results-tab&runId=22818246&resultId=174249&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
```
COMPlus_TieredCompilation=0
COMPlus_JitStress=2
COMPlus_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
COMPlus_JitStressRegs=3
COMPlus_DbgEnableMiniDump=1
+ ./RunTests.sh --runtime-path /root/helix/work/correlation
----- start Sat Jul 18 07:27:01 UTC 2020 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Threading.Tests.runtimeconfig.json --depsfile System.Threading.Tests.deps.json xunit.console.dll System.Threading.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem /root/helix/work/workitem
  Discovering: System.Threading.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tests (found 210 of 236 test cases)
  Starting:    System.Threading.Tests (parallel test collections = on, max threads = 4)
    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999999
      Stack Trace:
        /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs(319,0): at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
        /_/src/libraries/System.Threading/tests/InterlockedTests.cs(325,0): at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide()
  Finished:    System.Threading.Tests
=== TEST EXECUTION SUMMARY ===
```

@VSadov Looks like you only disabled it for arm64, not for arm32.

**Comment by VSadov** [comment]
@BruceForstall - the failure was on Windows ARM64. This is something new. Is there only one hit?

**Comment by BruceForstall** [comment]
@VSadov I've only seen one failure of this Linux arm32 case. However, I don't trust the Kusto data because it looks to me like the scripts to upload failures from Linux arm32 to Kusto have been broken.

**Comment by VSadov** [comment]
@BruceForstall - looked at the test again. I think there is a memory ordering issue in the test code.

**Comment by VSadov** [comment]
I think this was fixed in https://github.com/dotnet/runtime/pull/39668
