### ISSUE TITLE
Common job failure: msbuild MSB4166 error

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#11188]
This seems to be a common, non-repeatable, job failure reason for the Linux arm64 jobs (maybe others as well?)
```
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
```

This seems to mostly occur during the Docker build of the tests.

E.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_ubuntu16.04_innerloop/43/consoleFull

**Comment by BruceForstall** [comment]
Haven't seen this in a while, so closing. Feel free to re-open if it occurs again.

**Comment by bliles** [comment]
Seeing this error on our build server whenever two dotnet builds are running at the same time. Setting MSBUILDDISABLENODEREUSE=1 did help.
