### ISSUE TITLE
What will be the future of .NET Standard after .NET 5.0?

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#1118]
As there will be one an unified runtime from upcoming .NET 5.0, my curious question is what will be the future of .NET Standard? or what will be the role of .NET Standard in applications on .NET 5.0+?

Thank you.

**Comment by Symbai** [comment]
> Moving to a single .NET implementation raises important questions. [...] Do we still need .NET Standard? We are working through these issues now and will soon be sharing design docs for you to read and give feedback on.

https://devblogs.microsoft.com/dotnet/introducing-net-5/

More detailed information (last sentence is pretty clear about that): https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/july/csharp-net-reunified-microsoft%E2%80%99s-plans-for-net-5#a-declaration-of-intent

**Comment by TanvirArjel** [comment]
@Symbai That means life of .NET Standard is over!
