### ISSUE TITLE
Return value of System.Numerics.Vector2.Normalize() changes after calling it multiple times with identical inputs.

### ISSUE THREAD

**Issue by waltdestler** [dotnet/runtime#1119]
Here is a simple C# .NET Core 3.1 program that calls [`System.Numerics.Vector2.Normalize()`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector2.normalize?view=netcore-3.1) in a loop (with identical input every call) and prints out the resulting normalized vector:

```
using System;
using System.Numerics;
using System.Threading;

namespace NormalizeTest
{
	class Program
	{
		static void Main()
		{
			Vector2 v = new Vector2(9.856331f, -2.2437377f);
			for(int i = 0; ; i++)
			{
				Test(v, i);
				Thread.Sleep(100);
			}
		}

		static void Test(Vector2 v, int i)
		{
			v = Vector2.Normalize(v);
			Console.WriteLine($"{i:0000}: {v}");
		}
	}
}
```

And here is the output of running that program on my computer (truncated for brevity):

```
0000: <0.9750545, -0.22196561>
0001: <0.9750545, -0.22196561>
0002: <0.9750545, -0.22196561>
...
0031: <0.9750545, -0.22196561>
0032: <0.9750545, -0.22196561>
0033: <0.9750545, -0.22196561>
0034: <0.97505456, -0.22196563>
0035: <0.97505456, -0.22196563>
0036: <0.97505456, -0.22196563>
...
```

As you can see, the return value of `Vector2.Normalize(v)` changes from `<0.9750545, -0.22196561>` to `<0.97505456, -0.22196563>` after calling it 34 times. I realize that floating-point calculations can't be relied upon to be reproducible across architectures/OS'es/runtimes, but having non-reproducible results within the very same process instance seems deeply problematic, so I assume this must be a bug of some sort. I can reproduce this on both `Debug` and `Release` configurations. I have only tested on Windows 10 64-Bit with .NET Core 3.1; I have not tested any other OS'es or runtimes.

I'm not an expert in the .NET runtime internals, but my hunch is that after 34 calls my `Test` method is being re-JITed with more aggressive optimizations that results in different output. Indeed, adding `[MethodImpl(MethodImplOptions.AggressiveOptimization)]` to that method makes it consistently output `<0.97505456, -0.22196563>` (but only in `Release` builds).

**Comment by EgorBo** [comment]
Looks similar to https://github.com/dotnet/coreclr/issues/25857 TC kicks in and replaces MathF.Sqrt with `vsqrtss` for tier1 (it's an InternalCall in tier0)

**Comment by EgorBo** [comment]
Btw, clang doesn't just replaces `sqrtf` with `vsqrtss` as CoreCLR currently does: https://godbolt.org/z/VRMYQQ

**Comment by waltdestler** [comment]
> Or problem is in the `!Vector.IsHardwareAccelerated` fallback (`Vector.IsHardwareAccelerated` is false in R2R?)

Seems plausible: Replacing `Vector2.Normalize(v)` with `v / v.Length();` (equivalent to the `IsHardwareAccelerated` path) consistently produces the "more optimized" result, whereas `v * (1 / v.Length())` (equivalent to the fallback path) consistently produces the "less optimized" result.

It begs the question whether saving a division in the fallback path is worth the additional floating point error and inconsistent output vs the hardware-accelerated path.

**Comment by danmosemsft** [comment]
@tannergooding

**Comment by tannergooding** [comment]
We have a long-standing `up-for-grabs` issue for this here: <https://github.com/dotnet/corefx/issues/14286>

Happy to take a PR fixing it up 😄

**Comment by waltdestler** [comment]
Related answer/discussion on StackOverflow: https://stackoverflow.com/a/59538499/44003

**Comment by sunkin351** [comment]
Anybody else think it would be a wise decision for the JIT to honor all JIT constants even in [T1/debug] optimization? (e.g. `Vector.IsHardwareAccellerated` and the like)

**Comment by john-h-k** [comment]
I'll take this :)

**Comment by john-h-k** [comment]
I'll take this @tannergooding

**Comment by tannergooding** [comment]
Thanks @john-h-k. I've assigned this out to you. Let me know if you need any assistance or have any questions.

**Comment by tannergooding** [comment]
This was resolved in https://github.com/dotnet/runtime/pull/33088 when I was fixing two other bugs.
