### ISSUE TITLE
SemaphoreSlim deadlock in case dispose is called too early

### ISSUE THREAD

**Issue by flxliu** [dotnet/runtime#11202]
My code uses BlockingCollection, in case I dispose the BlockingCollection while some other threads are still waiting on GetConsumingEnumerable(CancellationToken), it may have deadlock.

The reason is that BlockingCollection holds a SemaphoreSlim, its m_lockObj is set to null in Dispose method, the Monitor.Exit(m_lockObj) in SemaphoreSlim.Wait(int millisecondsTimeout, CancellationToken cancellationToken) may throw ArgumentNullException, thus the lock on old m_lockObj is not released and cancellation callback is not unregistered.  If the CancellationToken is in middle of cancellation and wait for m_lockObj, it is blocked as it cannot get the lock on m_lockObj.

I'm not sure SemaphoreSlim is designed to allow calls still running after Dispose. I know CancellationTokenSource allows that. My suggestion is to fix the deadlock issue. If we allow calls running, then fine, otherwise throws a different exception saying Disposed, instead of deadlock.

The fix is easy: save m_lockObj to a stack variable (together with the lockTaken variable) so that the Wait() can work when someone dispose it.

**Comment by kouvel** [comment]
I think [this comment](https://github.com/dotnet/runtime/issues/71706#issuecomment-1179322043) regarding calls to `Dispose` concurrently with other calls also applies here. In any case, it looks like `SemaphoreSlim.Dispose` doesn't clear the lock object anymore.
