### ISSUE TITLE
Suspicious access to element of 'seq' object by a constant index inside a loop

### ISSUE THREAD

**Issue by Marusyk** [dotnet/runtime#1122]
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.Xml/src/System/Xml/Xsl/Runtime/XmlQueryRuntime.cs#L735-L739

The `for` loop is executed, the expression `i < seq.Count` is used as an exit condition. But in the loop, authors access sequence elements not by using the counter — `seq[i]`, but a number literal - zero (`seq[0]`).

Is it by design, or can I prepare PR for this?

**Comment by danmosemsft** [comment]
Hello @Marusyk you are right this code looks suspicious. I am not familiar with it so I can't say for sure it is wrong. Thanks for offering to investigate. Could you first create code that misbehaves due to this? Any PR would need such code for a test case anyway.

**Comment by Marusyk** [comment]
I closed this issue because cannot create any tests for it.
