### ISSUE TITLE
Add Runtime Performance Counters

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#11227]
Historically .NET supported emiting [certain default performance counter data](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/performance-counters) into the Windows Performance Counter system. On non-windows systems there is no such facility, but in its place we now have [EventCounter](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventcounter?view=netcore-2.1) for counters and [EventPipe](https://github.com/dotnet/coreclr/issues/19611) as an underlying transmission method. The goal is to instrument the runtime with similar counters that we had in the past, and have that data emitted via EventPipe. It is a non-goal (of this issue at least) to transmit the data to the Windows Performance Counter system.

This task tracks:
- [x] Identify a set of runtime counters we initially want to support. We should consider what was [originally supported in .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/performance-counters). It is OK if we start with only a high value subset, then add others later as needed. (See Vance's comments below for more detail)
- [ ] Ensure that managed wrappers exist to query the underlying data we care about. For example Process.VirtualMemorySize64 already exists whereas GC.PercentTimeInGC needs to be created.
- [x] Modify EventCounter / RuntimeEventSource to publish counters that are backed by the APIs.

Proposed list of runtime counters for .NET Core 3 (see https://github.com/dotnet/diagnostics/issues/83#issuecomment-446729009):

System Counters
- [x] Working set memory
- [x] CPU
- [ ] Handles

Exception performance counters
- [x] Exceptions thrown

Thread performance counters (see https://github.com/dotnet/corefx/issues/35500) 
- [ ] Threads
- [x] TPL threads
- [x] Total queue length
- [x] work items processed
- [x] Lock contention

Memory

- [x] Bytes in all heaps
- [x] Gen 0/1/2 collections
- [x] % time in GC
- [x] Gen 0/1/2 and LOH size
- [x] Allocation rate

JIT
- [ ] IL bytes Jitted

Loader
- [x] Number of Assemblies currently loaded

**Comment by tommcdon** [comment]
The remaining work on this PR is to add managed API's for .NET core counters.  This is tracked here: https://github.com/dotnet/runtime/issues/36571.
