### ISSUE TITLE
I want Visual Studio to add a new ability to sort the members of a class.

### ISSUE THREAD

**Issue by Dogwei** [dotnet/runtime#1123]
Such as C#: 

Auto sort with right click menus or shortcuts.

![QQ截图20191223100517](https://user-images.githubusercontent.com/14845492/71331153-cd0b0000-256b-11ea-91e7-5dedbdfef397.png)

I want my class members to be orderly, but I'm a lazy man.

**Comment by danmosemsft** [comment]
Hello @Dogwei thanks for the suggestion. The right way to suggest this is to use the feedback feature in Visual Studio itself (in the Help menu). This repo is for the.NET platform. Please file an issue through that system.
