### ISSUE TITLE
Add JIT support for auto-vectorization.

### ISSUE THREAD

**Issue by ArtBlnd** [dotnet/runtime#11263]
Current RyuJIT does not support local variable duplication based on super-scalar. or auto vectorization.
If you have is any discussion or informations. Please feel free to write here. 

To-do Lists.
- [ ] local variable duplication support for super-scalar if loop is simple enough. and also with full unsafe ALUs.
- [x] Implement more cases for estimate range checks. make it unsafe ALUs.
- [ ] Implement auto vectorization for unrolled `Vector<T>` first. and also for unrolled normal ALUs after.

category:design
theme:optimization
skill-level:expert
cost:extra-large

**Comment by BruceForstall** [comment]
This design discussion has played out, for now. The JIT team would love to spend more time thinking about auto-vectorization, but it is unlikely to happen in the near or even mid-term future. And its impact, while potentially great, though very narrow, can also be somewhat achieved using the now-existing hardware intrinsics. So I'm going to close this.
