### ISSUE TITLE
Proposal: Add AsyncEnumerable.Empty<T>()

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/runtime#1128]
# Rationale
I have an interface which is written like this:

```cs
    public interface IItemRetriever
    {
        public IAsyncEnumerable<string> GetItemsAsync();
    }
```

I want to write an empty implementation that returns no item, like so:
```cs
    public class EmptyItemRetriever : IItemRetriever
    {
        public IAsyncEnumerable<string> GetItemsAsync()
        {
           // What do I put here if nothing is to be done?
        }
    }
```

If it was a plain IEnumerable, I would `return Enumerable.Empty<string>();`, but I didn't find any `AsyncEnumerable.Empty<string>()`.

# Proposal
Create an `AsyncEnumerable` static class that contains an `Empty<T>()` static method.

In that case, I would just write:
```cs
return AsyncEnumerable.Empty<string>();
```

# Workarounds
I found this which works but is quite weird:

```cs
        public async IAsyncEnumerable<string> GetItemsAsync()
        {
            await Task.CompletedTask;
            yield break;
        }
```

**Comment by stephentoub** [comment]
We don't currently have any plans to add async LINQ equivalents to dotnet/runtime.  As called out by previous commenters, the System.Linq.Async nuget package provides an extensive set of such helpers, including Empty.  And as was pointed out in the original comments, you can write your own simple version of this:
```C#
#pragma warning disable CS1998
        private static async IAsyncEnumerable<T> Empty<T>()
#pragma warning restore CS1998
        {
            yield break;
        }
```
As such, I'm going to close the issue, but it can always be revisited in the future if it proves to be a significant pain point.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/111685 has added System.Linq.AsyncEnumerable, including Empty.
