### ISSUE TITLE
win32threadpool.cpp should use GetQueuedCompletionStatusEx rather than GetQueuedCompletionStatus

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#11314]
Pulling back multiple events (when available) per kernel call to dispatch rather than a single one per kernel call.

Also maybe use a completion port per core rather than a single completion port (to reduce contention)? (Not sure what strategy to use for attaching handles though; probably something better than round robin)

/cc @stephentoub @kouvel @vancem

**Comment by sandersaares** [comment]
We have a scenario where our app processes very large quantities of packets using IOCP to retrieveing and process batches of events on particular threads. This app is currently written in C++ to ensure we have the fine grained control we need. Making greater use of .NET for more developer-friendly business logic and higher-level feature implementation is something that keeps popping up now and then. The app is quite performance-critical, however. Basically a packet switch.

A quick experiment with a naive .NET Core sockets implementation shows less than 50% of the performance we get from our C++ implementation. It is better than I would have expected a few years ago but not enough. I suspect if we could have greater control over IOCP handling - in particular but not exclusively to take more items at once from the completion port -, we could eliminate one obstacle to greater use of .NET in our suite of services. Our sockets are each also associated with specific CPU cores, which reduces chatter across cores - we do not want our completion handling distributed across different cores.

I have only done a cursory examination of how this is implemented in .NET Core but from what I understand, completions are simply handled by the thread pool, triggered by single-item retrievals from the completion port on whatever thread gets the task.

To better meet our needs, we would be looking for functionality here that allows us to:

1. associate a specific completion port with a specific Socket
2. have completions from each completion port be processed on a specific thread, retrieved in bulk fashion via GetQCSEx
3. do so as efficiently as possible and, ideally, without allocating memory

Of course, we could always simply implement this ourselves via PInvoke but given that we already have a C++ implementation, this does not seem like a worthwhile investment. I hope this feedback can help bring .NET Core closer to our needs one day.

**Comment by geoffkizer** [comment]
@sandersaares Thanks for posting this. As you can see in the above discussion, we've explored doing this like this in the past but we haven't landed on a solution here. 

I would love to get your benchmark code and play with it a bit. Can you post it somewhere or email it to me?

**Comment by sandersaares** [comment]
The app I used for benchmarking the C# Socket performance is https://github.com/sandersaares/Shubar/

This app can generate the test input streams: [grinch.zip](https://github.com/dotnet/runtime/files/5140234/grinch.zip)

In my scenario I used 5 machines running the script in the zip to generate load for 1 benchmark app.

**Comment by davidfowl** [comment]
Ah this is udp, there are some low hanging fruit optimizations that can be made https://github.com/dotnet/runtime/issues/33418, though that's likely only part of the story here.

**Comment by geoffkizer** [comment]
The specific issue for UDP optimization is here: https://github.com/dotnet/runtime/issues/30797

Feedback welcome.

**Comment by kouvel** [comment]
It might be interesting to try using `GetQueuedCompletionStatusEx` again and having it work similarly to how epoll threads work on Linux, only posting to the IO completion port rather than to the thread pool (to preserve the current prioritization).

**Comment by kouvel** [comment]
`GetQueuedCompletionStatusEx` is used after https://github.com/dotnet/runtime/pull/64834. Using multiple IOCPs didn't seem to improve perf.
