### ISSUE TITLE
Investigate if macOS logic for parsing '/usr/bin/vmmap' output

### ISSUE THREAD

**Issue by Eilon** [dotnet/runtime#11310]
See this comment thread from an earlier PR: https://github.com/dotnet/coreclr/pull/20402/files#r227586471

There's code in `src/pal/src/thread/process.cpp` that parses the output of a command line tool on macOS to detect certain metadata of an app, and it includes logic to skip over unwanted parts of metadata.

In the PR a concern was raised that the portion that tries to skip over the `VSIZE  RSDNT  DIRTY   SWAP` metadata columns might have a limitation:

> From @Eilon
> Out of curiosity, can the ` VSIZE  RSDNT  DIRTY   SWAP` fields never have an `M` in there for megabytes? Are they *always* in kilobytes?

So I'm logging this bug so that it can be investigated further:

> From @Eilon 
> Is it possible to create a test case with an app that has a really large "one of those things" to see what it is? E.g. what if an app has more than 99,999KB of VSIZE? (only 5-digit numbers fit in the table)
>
> Is it worth looking into the parsing further? To be clear, I have no background in this at all, just saw something curious.

**Comment by mikem8361** [comment]
The vmmap code has been replaced by the proc_pidinfo API.
