### ISSUE TITLE
Use live IL.SDK (ILASM and ILDASM) in libraries to build .ilproj's

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#1137]
We should be using live IL.SDK and tools for libraries instead of still downloading the SDK in Tools.props and using that.

We could instead of making it an SDK project, import the targets directly from coreclr folder and also resolve ilasm/ildasm from the locally built coreclr outputs.

cc: @dotnet/runtime-infrastructure @danmosemsft

**Comment by ViktorHofer** [comment]
I noticed that even coreclr is using a cached version of the IL SDK when I prepared it for the repo consolidation. We should eliminate all usages of the cached version.

**Comment by jkotas** [comment]
I do not think it make sense to use the live version of ilasm/ildasm. It creates a problem for cross-compilation as noted in #32662 among other things. It is fine for the compilers to come from package.

**Comment by ViktorHofer** [comment]
@jkotas sounds like you don't want us to do this? Should we close the issue then?
