### ISSUE TITLE
[Windows 64-bit] Could not load type 'System.Security.IStackWalk' from assembly 'System.Runtime.Extensions,

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#1139]
At runtime I am getting below error, I have referenced System.Security.Permissions assembly while compiling.  This is on Windows 64-bit, using .NET Core runtime version 2.2

System.TypeLoadException: Could not load type 'System.Security.IStackWalk' from assembly 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by danmosemsft** [comment]
@deokershesh I'm confused, are you using .NET Core, or building it? This issue above relates to using it. I was suggesting you download the 3.1 SDK and build with that.

The issue you are pointing to, #1014 , relates to building your own runtime.

**Comment by deokershesh** [comment]
@danmosemsft, I am building the runtime code for .NET Core 3.1, similar to what I build for .NET Core 2.2. I need to make certain code changes to support .NET Core Provider for Informix database.

**Comment by jkotas** [comment]
>  Could not load type 'System.Security.IStackWalk'

This is duplicate of https://github.com/dotnet/corefx/issues/34308 . This problem occurs when you use older version of `System.Security.Permissions` NuGet package with newer .NET Core. Referencing the latest version (4.7.0) of `System.Security.Permissions` NuGet package will fix it.
