### ISSUE TITLE
Local benchmark instructions are out of date

### ISSUE THREAD

**Issue by NickCraver** [dotnet/runtime#11390]
I'm trying to benchmark some changes to attribute handling, but I'm struggling to get any tests running.

The current guidance (as far as I can tell) is located here: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/performance-guidelines.md#running-the-coreclr-performance-tests-on-windows

It references: `tests\scripts\run-xunit-perf.cmd -arch x64 -configuration Release -testBinLoc <path>`

However, the `tests\scripts\run-xunit-perf.cmd` script was eliminated in dotnet/coreclr#15568, during a conversion to python. So...how do we run benchmarks these days? And can we please update the guidance for everyone to benefit?

**Comment by adamsitnik** [comment]
It has been solved quite a while ago. 

https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md
https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md
