### ISSUE TITLE
[JIT] Improve loop unrolling optimization.

### ISSUE THREAD

**Issue by ArtBlnd** [dotnet/runtime#1140]
Current RyuJIT loop unrolling optimization only supports optimizations for Vector type, with limited threshold also full unrolling. the goal is make loop unrolling optimization to be more relaxed. also SLP-vectorizer friendly.

- [ ] **Make current unrolling code to handle more cases**
Currently, the unrolling codes in RyuJIT is specialized for full unrolling. make it more general to handle more cases such as partial unrolling. at this time, make sure that changed code emits same assembly as previous code

- [ ] **Make it not to unroll only for Vector types (which is SIMD)**
The current code only allows unrolling for vector types, we have to make it support normal ALUs.

- [ ] **Make a documents for partial, full unrolling rules**
All these unrolling rule should based on architecture manuals. be careful because unrolling scheme can be difference because the framework emits bound checks. (check Loop Stream Detector on Intel Optimization Manual)

- [ ] **Make tests for rules**
We need benchmarks and tests for these unrolling rules not to make performance regressed after implement it. 

- [ ] **Implement partial, full unrolling based documented rules.**
Ready to go :)

**Comment by ArtBlnd** [comment]
old issue page from CoreCLR.
https://github.com/dotnet/coreclr/issues/11606

**Comment by ArtBlnd** [comment]
@AndyAyersMS

**Comment by AndyAyersMS** [comment]
@ArtBlnd we are planning to migrate all the issues from coreclr over to this repo, so I suggest we close this and use the original issue to track ongoing discussion about unrolling.

**Comment by ArtBlnd** [comment]
Oh okay.

**Comment by ArtBlnd** [comment]
But can you just check is this plan good to go?

**Comment by AndyAyersMS** [comment]
Since unrolling can be prototyped in source, I would like to see you start out by creating some test cases that show the benefits we can expect to see, and from this, get a picture of the code size growth vs benefit tradeoff.

I'm curious if factors apply that one might not see in the classic (native code) version of this optimization. For instance is it worth unrolling a loop with array accesses if the jit can't eliminate the bounds checks?

I've also been playing around with the do-while transformation (`fgOptWhileLoop`) and wonder if we should focus first on increasing the set of loop nests that we're willing to optimize.

**Comment by ArtBlnd** [comment]
> Since unrolling can be prototyped in source, I would like to see you start out by creating some test cases that show the benefits we can expect to see, and from this, get a picture of the code size growth vs benefit tradeoff.

We already have existing benchmarks in coreclr. also on some issues. maybe we can use it for it?


> get a picture of the code size growth vs benefit tradeoff.

I don't have much informations about its trade-off. do we have any guidelines?
 

> I'm curious if factors apply that one might not see in the classic (native code) version of this optimization. For instance is it worth unrolling a loop with array accesses if the jit can't eliminate the bounds checks?

It still worth to unroll it. but it will not efficient as not its eliminated because maximum threshold of instructions that cpu can handle with ICache or LSD will be limited. L1 Cache based unrolling will still works fine on my expect if branch predictor success to predicate bound check condition. (it will mostly success), but we have to be careful excessed unrolling with bound check can cause huge slowdown. (more than 5% regression)

**Comment by AndyAyersMS** [comment]
What I envision is a set of relatively simple test cases that show methods where unrolling is beneficial and methods where unrolling is not (or not very) beneficial, so that as we implement unrolling, we have a way of keeping score.

For methods where unrolling is beneficial, I'd also like to score them by some sort of benefit/cost metric, eg if we need to increase code size by a factor of X to get a speedup factor Y, we'd have an overall score of Y/X. And ideally the heuristic we implement tries to estimate this as well, and we can see how the heuristic predictions match up with reality.

**Comment by ArtBlnd** [comment]
It is hard to know what slows down if we unrolls the loop. but we can limit it to what loop makes faster. we already have actual proven definitions on architecture manuals, and we must limit heuristic to it. maybe we can extend it out when we need.

What heuristic is on current JIT implements? I don't think there is specific proven heuristic implemented on current full unrolling implements. calculating costs and scoring doesn't seems good way to solve this problem. there will be lots of cases will be slow down(or not be unrolled because of very limited heuristic) on current heuristic because it only calculate total costs. unrolling loop slows down depends its load, store, branch count, etc. not total costs.  (of course it will slow if overs the cost because of code size increment)

**Comment by ArtBlnd** [comment]
Even LLVM does not perform speed-up factor limits. as I known there is existing option `UnrollMaxPercentThresholdBoost` but it is not on use.

**Comment by ArtBlnd** [comment]
Or do you need new heuristic for limiting?

**Comment by AndyAyersMS** [comment]
> Or do we need new heuristic for limiting?

I think we do. The current full unroll heuristic may or may not be a good example, as the number of loops that we will fully unroll is very limited. 

Partial unrolling would likely apply to a larger variety of loops and so we need to make sure we understand the cost and benefit more broadly.

The main concern for a jit is that we properly balance the time spent optimizing with the benefits we can obtain. So I imagine we'll need a different and more conservative heuristic than a native compiler. I would like to see us experiment in source to get a handle on what that heuristic might look like.

**Comment by ArtBlnd** [comment]
before I start to benchmark. So should we find the constant value of cost that some specific code will not unrolled for sure? or some code that will unrolled for sure?

**Comment by AndyAyersMS** [comment]
I would start out very simple, something like summing the elements of an unknown-sized array:
```C#
int Sum(int[] a)
{
   int result = 0;
   for (int i = 0; i < a.Length; i++)
   {
      result += a[i];
   }
   return result;
}
```
Benchmark that version, and then versions that (manually) unroll 2x, 3x, 4x, ...  Look at performance vs code size. Repeat with other simple loop kernels, and different data types (SIMD for instance).

**Comment by ArtBlnd** [comment]
> I would start out very simple, something like summing the elements of an unknown-sized array:

We do not unroll currently if there is unknown trip count on the loop even on the prototype version.

**Comment by ArtBlnd** [comment]
> I would start out very simple, something like summing the elements of an unknown-sized array:
I don't think unrolling loop with unknown trip count in JIT is good idea. we should hang with loop that has invariant trip count.

**Comment by AndyAyersMS** [comment]
In the example above, array length is unknown but is also an invariant; it is probably the most common case we'll see in practice. Looking at known length cases is fine too, so long as you consider cases where the length is not divisible by the unroll factor.

**Comment by ArtBlnd** [comment]
> array length is unknown but is also an invariant
Yes I think I misunderstood. maybe we can use difference heuristic on unknown-sized array. 

> so long as you consider cases where the length is not divisible by the unroll factor.
Yes thank you. :)

**Comment by ArtBlnd** [comment]
I am collecting the model. I'll show all the testcases and its threshold ASAP.
