### ISSUE TITLE
Inefficient codegen for casts between same size types.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#11413]
As per https://github.com/dotnet/coreclr/pull/20788#discussion_r230593200, using `BitConverter.SingleToInt32Bits`, `BitConverter.Int32BitsToSingle`, `BitConverter.DoubleToInt64Bits`, and `BitConverter.Int64BitsToDouble` generates some "inefficient" code.

Currently `BitConverter.SingleToInt32Bits` is generating:
```asm
vmovss   dword ptr [rsp+14H], xmm0
mov      eax, dword ptr [rsp+14H]
```

When it could generate:
```asm
vmovd eax, xmm0
```

Currently `BitConverter.Int32BitsToSingle` is generating:
```asm
mov      dword ptr [rsp+0CH], eax
vmovss   xmm0, dword ptr [rsp+0CH]
```

When it could generate:
```asm
vmovd xmm0, eax
```

The same logic applies to `double <-> long`, but using the `rax` register and `vmovq`.
* For x86, it can use the `movq xmm, [m64]` or `movq [m64], xmm` encoding

category:cq
theme:casts
skill-level:intermediate
cost:medium

**Comment by GrabYourPitchforks** [comment]
Related PR: https://github.com/dotnet/runtime/pull/6864, which makes use of this API

**Comment by tannergooding** [comment]
https://github.com/dotnet/runtime/pull/33476 introduced a fix which works around the issue, but we are leaving this issue open to track the JIT getting a more general codegen improvement that isn't specific to `BitConverter`.

**Comment by Kein** [comment]
I guess this is partially related to aforementioned issue - is there any reason float.isFinite() is safe while the rest of similar extensions using similar tools are `unsafe` (like IsInfinity)?

**Comment by GrabYourPitchforks** [comment]
@Kein Looks like we just forgot to remove the _unsafe_ modifier from the `Single.IsInfinity` method. It doesn't affect callers; they're not required to be unsafe. But it does provide some further evidence that we should consider stripping the _unsafe_ modifier from types and functions that no longer need it, just as an overall code hygiene cleanup.

**Comment by tannergooding** [comment]
> But it does provide some further evidence that we should consider stripping the unsafe modifier from types and functions that no longer need it, just as an overall code hygiene cleanup.

This seems like one of the simpler analyzers we could write, is there an issue suggesting it yet?

**Comment by GrabYourPitchforks** [comment]
There's some limited discussion around it as part of https://github.com/dotnet/runtime/issues/31354. Basically: if we have an analyzer that says "you're not using pointers, remove _unsafe_" alongside a language feature that enforces "this API doesn't use pointers but you need to wrap call sites within an _unsafe_ block", we need to figure out how these two things interact together.

**Comment by deeprobin** [comment]
In .NET 7 it generates

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHuGAHKAJYA3bBhgMBAOwwMAGgAoAZgBsIohooCUHLjz3EA7AwBCAjCwiShMKGKgA6AMpSA5spgAVCAElpdUqYYuEqaANy63AC+NJFAA=
```asm
    L0000: vzeroupper
    L0003: vmovd eax, xmm1
```

**Comment by JulieLeeMSFT** [comment]
With .NET 9 Preview 7, 
`BitConverter.SingleToInt32Bits(float)` generates
```asm
vmovd    eax, xmm0
```

`BitConverter.Int32BitsToSingle(int)` generates
```asm
vmovd    xmm0, ecx
```

`BitConverter.DoubleToInt64Bits(double)` generates
```asm
 vmovd    rax, xmm0
```

`BitConverter.Int64BitsToDouble(long)` generates
```asm
vmovd    xmm0, rcx
```

**Comment by JulieLeeMSFT** [comment]
@tannergooding, please check the generated encoding with .NET 9 above (https://github.com/dotnet/runtime/issues/11413#issuecomment-2299954614).
- `float <-> int` is generating the expected code.
- `double <-> long` is generating `vmovd`, not `vmovq`. Do we need further optimization? 
    > The same logic applies to `double <-> long`, but using the `rax` register and `vmovq`.

cc @dotnet/jit-contrib

**Comment by tannergooding** [comment]
This got resolved some time back (https://github.com/dotnet/runtime/pull/71567, as well as other commits by other JIT team members)

The `movd` for `double <-> long` is actually just a disassembly bug/quirk. `movd` and `movq` are the same instruction, it's just that `movq` is the preferred disassembly when operating on 64-bit registers. Looks like we're not accounting for that when we do the disasm dumping

**Comment by JulieLeeMSFT** [comment]
Very good. 
> This got resolved some time back (#71567, as well as other commits by other JIT team members)

Also checked `SingleToInt32Bits(float)` on x86 

```asm
mov      eax, dword ptr [ebp+0x08]
```

**Comment by JulieLeeMSFT** [comment]
on x86,
`Int32BitsToSingle(int):float`
```asm
       vmovd    xmm0, ecx
       vmovss   dword ptr [ebp-0x04], xmm0
       fld      dword ptr [ebp-0x04]
```

`DoubleToInt64Bits(double):long`
```asm
       vmovsd   xmm0, qword ptr [ebp+0x08]
       sub      esp, 8
       vmovsd   qword ptr [esp], xmm0
       call     [System.BitConverter:DoubleToInt64Bits(double):long]
```

`Int64BitsToDouble(long):double`
```asm
       push     dword ptr [ebp+0x0C]
       push     dword ptr [ebp+0x08]
       call     [System.BitConverter:Int64BitsToDouble(long):double]
       fstp     qword ptr [ebp-0x08]
       vmovsd   xmm0, qword ptr [ebp-0x08]
       vmovsd   qword ptr [ebp-0x08], xmm0
       fld      qword ptr [ebp-0x08]
```

**Comment by tannergooding** [comment]
👍 

x86 is expected to be less efficient for `DoubleToInt64Bits` and the inverse here. There's no singular instruction available since the register size is 32-bits and so we have to do handle the lower and upper halves through memory.

There is notably a way to load a double directly to/from memory using a specialized memory only version of `movq` on 32-bit, but that's a non-trivial amount of work and it hasn't bubbled up in priority yet. That work is tracked instead by https://github.com/dotnet/runtime/issues/11626
