### ISSUE TITLE
How I can use 'Microsoft.NET.Sdk.IL' SDK?

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/runtime#11411]
System.Runtime.CompilerServices.Unsafe package uses 'Microsoft.NET.Sdk.IL', but where I can install it?

**Comment by jkotas** [comment]
https://dotnet.myget.org/ feed was decomissioned.

Microsoft.NET.Sdk.IL is published on nuget.org now: https://www.nuget.org/packages/Microsoft.NET.Sdk.IL
