### ISSUE TITLE
Parallel for loop code with SIMD runs much slower on .NET Core than .NET Framework

### ISSUE THREAD

**Issue by gsuberland** [dotnet/runtime#11425]
I've been experimenting with some code for doing pixel value averaging with SIMD, and ran into an interesting case in which the same code targeting .NET Framework 4.7.2 and .NET Core 2.1 has a significant performance difference (around 300%).

I'm running an i7-4790K, which has AVX and AVX2 but no AVX-512, on Windows 10 build 1803 and the latest release of .NET Core (installed fresh yesterday).

The test case is as follows:

```
/*
using System;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Numerics;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
*/

// ...

using (Bitmap b = (Bitmap)Bitmap.FromFile(@"some_3840x2160_image.jpg"))
{
	var bd = b.LockBits(new Rectangle(Point.Empty, b.Size), ImageLockMode.ReadOnly, PixelFormat.Format24bppRgb);

	Stopwatch sw = new Stopwatch();
	sw.Start();
	sw.Stop();
	sw.Reset();

	sw.Start();

	const int tryCount = 100;
	try
	{
		int bufferSize = bd.Stride * bd.Height;
		int bitmapWidth = bd.Width;
		int bitmapHeight = bd.Height;
		int stride = bd.Stride;
		byte[] buffer = new byte[bufferSize];
		var po = new ParallelOptions
		{
			MaxDegreeOfParallelism = 8,
		};

		for (int tries = 0; tries < tryCount; tries++)
		{
			Marshal.Copy(bd.Scan0, buffer, 0, bufferSize);

			Vector3 sum = Vector3.Zero;
			object sumLock = new object();

			Parallel.For(
				0, bitmapHeight,
				po,
				y =>
				{
					Parallel.For<Vector3>(
						0, bitmapWidth,
						po,
						/* init */ () => Vector3.Zero,
						/* body */ (x, pls, localSum) =>
						{
							int ofs = (y * stride) + (x * 3);
							var pv = new Vector3(buffer[ofs], buffer[ofs + 1], buffer[ofs + 2]);
							pv /= 255.0f;
							return localSum + pv;
						},
						/* final */ (localSum) =>
						{
							lock (sumLock)
							{
								sum += localSum;
							}
						}
					);
				}
			);

			sum /= (bitmapWidth * bitmapHeight);
			/*Console.WriteLine("Size: {0}MB", (bd.Width * bd.Height * 4) / (1024.0 * 1024.0));
			Console.WriteLine("Average:");
			Console.WriteLine("R: {0}", sum.X);
			Console.WriteLine("G: {0}", sum.Y);
			Console.WriteLine("B: {0}", sum.Z);*/
		}
	}
	finally
	{
		b.UnlockBits(bd);
	}

	sw.Stop();
	Console.WriteLine("Time: {0}ms", sw.ElapsedMilliseconds / (double)tryCount);
	Console.ReadKey();
}
```

For .NET Framework 4.7.2 this runs and returns a time of approximately 30ms (assuming a 4K UHD input image) and for .NET Core 2.1 the run time is more like 100ms.

I set the `MaxDegreeOfParallelism` value in case there was a different default value between frameworks, but this made no difference; the benchmark result is identical.

I re-implemented this same solution with `Vector<T>` instead of `Vector3` and found that performance was again inferior, regardless of whether I used `Vector<float>` or re-implemented the algorithm with `Vector<int>` as an accumulator and division done at the end outside of the loop.

**Comment by stephentoub** [comment]
Without the requested self-contained repro, it's difficult to do anything further here.  Closing.  If you can share a runnable repro on .NET Core 3.1 that demonstrates the issue, please re-open this and we can take another look.  Thanks.
