### ISSUE TITLE
JIT: inconsistent codegen CQ for divide by power of 2 idioms for array length

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#11441]
From dotnet/corefx#33367. Shift by 2 has better codegen then divide by 4.

Method | Mean | Error | StdDev | Ratio
-- | -- | -- | -- | --
Div | 192.2 ns | 0.9134 ns | 0.8097 ns | 1.00
BitShift | 151.3 ns | 2.9729 ns | 2.9198 ns | 0.79
```C#
    [Benchmark(Baseline = true)]
    public int Div()
    {
        int result = 0;
        for (int i = 0; i < N; i++)
        {
            result ^= data_2D[i].Length / 4;
        }
        return result;
    }

    [Benchmark]
    public int BitShift()
    {
        int result = 0;
        for (int i = 0; i < N; i++)
        {
            result ^= data_2D[i].Length >> 2;
        }
        return result;
    }
```

category:cq
theme:basic-cq
skill-level:beginner
cost:small

**Comment by EgorBo** [comment]
There is no difference in the codegen between these two anymore
