### ISSUE TITLE
Check Type bases without reflection

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#1144]
Does the CLR or MSIL support a way of determining if a type is cast able to another type without using reflection?

Ie. 

If(T is IEnumerable)...

WhereT is is a type, not an instance of a type.

**Comment by jkotas** [comment]
`Type.IsAssignableFrom` API is the way to do this. Note that this API is the fast light-weight reflection. If there was a other way to do this, it would have very similar performance.
