### ISSUE TITLE
RedirectStandardInput=false has no effect on Console.IsInputRedirected in the spawned process

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#1147]
When the input is redirected to a parent process, the spawned process inherits `Console.IsInputRedirected`, even when `ProcessStartInfo.RedirectStandardInput` is explicitly set to `false`.

Is this by design? Is there a way/workaround to avoid this inheritance?

#### Setup

```sh
# using dotnet core 3.1 on Ubuntu
cd /tmp
dotnet new console -n spawned
dotnet new console -n stdin-test
```

`/tmp/stdin-test/Program.cs`
```c#
using System;
using System.Diagnostics;
class Program
{
    static void Main(string[] args)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = args[0],
            RedirectStandardOutput = true,
            RedirectStandardInput = false,
            UseShellExecute = false
        };

        using (var process = new Process { StartInfo = startInfo })
        {
            process.OutputDataReceived += (sender, e) =>
            {
                if (e.Data != null)
                {
                    Console.WriteLine("=> Message from spawned process:\n=> {0}", e.Data);
                }
            };

            process.Start();
            process.BeginOutputReadLine();
            process.WaitForExit();
        }
    }
}
```

`/tmp/spawned/Program.cs`
```c#
using System;
class Program
{
    static void Main()
        => Console.WriteLine("Console.IsInputRedirected: {0}", Console.IsInputRedirected);
}
```

```sh
# build projects
# cd /tmp
dotnet build spawned
dotnet build stdin-test

# run stdin-test without redirected input
stdin-test/bin/Debug/netcoreapp3.1/stdin-test  spawned/bin/Debug/netcoreapp3.1/spawned

=> Message from spawned process:
=> Console.IsInputRedirected: False

# run stdin-test with redirected input
echo hello | 
  stdin-test/bin/Debug/netcoreapp3.1/stdin-test  spawned/bin/Debug/netcoreapp3.1/spawned

=> Message from spawned process:
=> Console.IsInputRedirected: True

# should it be False?
# any way to adjust ProcessStartInfo to unset IsInputRedirected in spawned process?
```

**Comment by wfurt** [comment]
I think Console.IsInputRedirected checks if stdin is attached to TTY or not. 
cc: @tmds

**Comment by tmds** [comment]
When `RedirectStandardInput=false`, standard input is the same as the parent. So parent and child return the same value for `IsInputRedirected` (attached to TTY or not).
When `RedirectStandardInput=true`, standard input is distinct from the parent. So child returns `IsInputRedirected=true` (not attached to TTY).

This is behaving as expected.

**Comment by am11** [comment]
Thanks!

> When RedirectStandardInput=true, standard input is distinct from the parent. So child returns IsInputRedirected=true (not attached to TTY).

Did you mean <kbd><code>IsInputRedirected=***false***</code> (not attached to TTY)</kbd> or are they reciprocal?

**Comment by tmds** [comment]
When you do `RedirectStandardInput=true`, .NET Core creates a pipe, one end is written to by the parent, the other end becomes stdin of the child.

`IsInputRedirected == !isatty(stdin)`

For a pipe, `isatty` returns `false`, so `IsInputRedirected` is `true`.

**Comment by tmds** [comment]
@am11 this may be closed?

**Comment by am11** [comment]
@tmds, certainly. I was writing unit tests for roslyn compilers after implementing "compile code from stdin" feature: https://github.com/dotnet/roslyn/pull/41166. There I found myself in a situation that test execution was failing when input was redirected to the xunit itself (through `roslyn/test.sh`), but not when I was manually invoking `dotnet test` on the test project. Your explanation has clarified what is going on. The middle process (unit test code) was inheriting `IsInputRedirected: True` from its parent: `xunit`, and so was its child process: `csc`.

Thank you once again! 🎉
