### ISSUE TITLE
Internal API suggestion: bool JitHelpers.IsKnownConstant(uint) to let us optimize certain code paths

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#11484]
There are quite a few places in the Framework where we have specialized knowledge of data structures and algorithms - beyond what the JIT has - where we'd be able to make optimizations beyond what the JIT can provide if the JIT is able to hint to us information about locals.

For example, consider `string.StartsWith(char) : bool`, which is currently implemented as below.

```cs
public bool StartsWith(char value) => Length != 0 && _firstChar == value;
```

If the JIT were able to hint to us information about the local, we could write this as follows, which would allow us to elide the first branch entirely in almost all cases, taking advantage of the fact that empty strings have the null-terminator in the `_firstChar` position.

```cs
public bool StartsWith(char value) {
  if (JitHelpers.IsKnownConstant(value) && value != 0) {
    return _firstChar == value;
  } else {
    return Length != 0 && _firstChar == value;
  }
}
```

It would also allow us to further optimize the `Span.Slice(int start, int length)` logic we checked in earlier, which allows us to do something akin to the below.

```cs
if (JitHelpers.IsKnownConstant(start)) {
  if (start == 0) {
    // case Slice(0, <something>)
    ThrowIf((uint)length > (uint)_realLength);
    return <slice>;
  } else if (JitHelpers.IsKnownConstant(length) && start >= 0 && length >= 0) {
    // case Slice(10, 20)
    ThrowIf((uint)(start + length) > (uint)(_realLength));
    return <slice>;
  }
}

ThrowIf(normal_validation_checks);
return <slice>;
```

This could also have potential applications for methods which are implemented via a giant switch statement which normally doesn't get inlined (see `String.Equals(..., StringComparison)` overload). We could choose to implement the method as an inlineable method that does a very fast dispatch if the _comparison_ parameter is known constant, falling back to a slower non-inlined method if the comparison parameter needs to be evaluated at runtime.

The behavior of `IsKnownConstant` would be such that the JIT would replace it with _true_ if the value is known at JIT time to be constant (perhaps because it is itself a literal or has been calculated from some other const-folding). It would be replaced with _false_ in all other cases, including if the JIT simply doesn't have enough information to make a determination, or if optimizations have been disabled. I'm also assuming branch pruning would kick in to completely elide code that is on the incorrect side of the `IsKnownConstant` check.

category:proposal
theme:optimization
skill-level:expert
cost:extra-large

**Comment by GrabYourPitchforks** [comment]
Per Tanner's comment, I wonder if adding a bunch of `[Intrinsic]` methods would be the way to go here. It's not the cleanest long-term solution, but at least it could allow us to prove / disprove the value of this feature.

**Comment by stephentoub** [comment]
Is there a reason we wouldn't want this to propose this or a variant of it as being public?

And are there other places we should ourselves be using it internally now that we have it internally?

**Comment by EgorBo** [comment]
> Is there a reason we wouldn't want to propose this or a variant of it as being public?
> 
> And are there other places we should ourselves be using it internally now that we have it internally

I personally don't have a strong opinion. If we decide to make it public we will need to address that inline-limit issue and properly implement it in Mono too.

**Comment by GSPP** [comment]
This API can be used to create behavioral differences caused by what the call site looks like, what surrounding code looks like, the runtime version, bitness, ...

This seems like a very dangerous thing to expose publicly. In my opinion, clearly not worth it. At least, the decision should wait for a release or two to gain practical experience with this concept. @stephentoub

**Comment by tannergooding** [comment]
> This seems like a very dangerous thing to expose publicly. In my opinion, clearly not worth it. I don't want to see this show up in libraries causing nasty bugs.

This is no more dangerous than many of the APIs in `System.Runtime.*` ranging from `*.CompilerServices.Unsafe` to `*.InteropServices.MemoryMarshal`, `*.InteropServices.CollectionsMarshal`, or even some of the behaviors of the entire `*.Intrinsics.*` namespace.

Users can already do all sorts of hacks, specializations, and other tricks (including relying on inlining) to force a particularly behavior and this just extends that to one other interesting avenue that we ourselves find worthwhile in various scenarios.

It's not like every app would suddenly start using it and it being exposed somewhere like `RuntimeHelpers` would help ensure that the scenarios its used remain limited for most users. There is a lot of code out there that is far scarier than trying to determine if an input is constant after inlining happens.
