### ISSUE TITLE
[Question] AssemblyRef does not match .deps.json assemblyVersion; why?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/runtime#1148]
Apologies if this is not the correct repo.  I'm sure this has to be correct behavior, but I just can't make sense of it.

I'm using Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework, and targeting a netstandard2.0 class library that references System.ComponentModel.Annotations 4.7 nuget package (assembly version 4.2.1)

I have a `sample.csproj` project that references System.ComponentModel.Annotations, like so:

#### sample.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <PropertyGroup>
    <Authors>John Zabroski</Authors>
    <Description>Common .NET Assembly</Description>
    <Copyright>Copyright © 2020</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
  </ItemGroup>
</Project>
```
Create the following two files to force System.ComponentModel.Annotations to be compiled.

#### ReferenceAttribute.cs
```c#
using System;

namespace Sample
{
    /// <summary>
    /// Adding this attribute forces a reference to the type in code which causes the assembly the type is contained in to be copied to the output directory.
    /// </summary>
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    public class ReferenceAttribute : Attribute
    {
        public ReferenceAttribute(Type type)
        {
            Type = type ?? throw new ArgumentNullException(nameof(type));
        }

        public Type Type { get;  }
    }
}
```
#### dummy.cs
```c#
[assembly: Sample.Reference(typeof(System.ComponentModel.DataAnnotations.DisplayAttribute)]
```

Run the following PowerShell commands to restore/build:

```powershell
& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MsBuild.exe" .\sample.csproj /t:build
```

### Expected Behavior
I expect that if I inspect the CIL for sample.dll, the `System.ComponentModel.Annotations` AssemblyRef will be 4.2.1 and match `sample.deps.json`.

### Actual Behavior
I opened sample.deps.json, and see the following snippet:

```json
      "System.ComponentModel.Annotations/4.7.0": {
        "runtime": {
          "lib/netstandard2.0/System.ComponentModel.Annotations.dll": {
            "assemblyVersion": "4.2.1.0",
            "fileVersion": "4.6.26515.6"
          }
        }
      }
```
<details>
<summary>Click to see my full sample.deps.json</summary>
```json
{
  "runtimeTarget": {
    "name": ".NETStandard,Version=v2.0/",
    "signature": "25075aa34a63eebe013d87973bb4d352e6cb6574"
  },
  "compilationOptions": {},
  "targets": {
    ".NETStandard,Version=v2.0": {},
    ".NETStandard,Version=v2.0/": {
      "sample/1.0.0": {
        "dependencies": {
          "NETStandard.Library": "2.0.3",
          "System.ComponentModel.Annotations": "4.7.0"
        },
        "runtime": {
          "sample.dll": {}
        }
      },
      "Microsoft.NETCore.Platforms/1.1.0": {},
      "NETStandard.Library/2.0.3": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "1.1.0"
        }
      },
      "System.ComponentModel.Annotations/4.7.0": {
        "runtime": {
          "lib/netstandard2.0/System.ComponentModel.Annotations.dll": {
            "assemblyVersion": "4.2.1.0",
            "fileVersion": "4.6.26515.6"
          }
        }
      }
    }
  },
  "libraries": {
    "sample/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "Microsoft.NETCore.Platforms/1.1.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-kz0PEW2lhqygehI/d6XsPCQzD7ff7gUJaVGPVETX611eadGsA3A877GdSlU0LRVMCTH/+P3o2iDTak+S08V2+A==",
      "path": "microsoft.netcore.platforms/1.1.0",
      "hashPath": "microsoft.netcore.platforms.1.1.0.nupkg.sha512"
    },
    "NETStandard.Library/2.0.3": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-st47PosZSHrjECdjeIzZQbzivYBJFv6P2nv4cj2ypdI204DO+vZ7l5raGMiX4eXMJ53RfOIg+/s4DHVZ54Nu2A==",
      "path": "netstandard.library/2.0.3",
      "hashPath": "netstandard.library.2.0.3.nupkg.sha512"
    },
    "System.ComponentModel.Annotations/4.7.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-0YFqjhp/mYkDGpU0Ye1GjE53HMp9UVfGN7seGpAMttAC0C40v5gw598jCgpbBLMmCo0E5YRLBv5Z2doypO49ZQ==",
      "path": "system.componentmodel.annotations/4.7.0",
      "hashPath": "system.componentmodel.annotations.4.7.0.nupkg.sha512"
    }
  }
}
```
</details>
I decompiled sample.dll, and see the following in JetBrains dotPeek:

![image](https://user-images.githubusercontent.com/447485/71431828-d054d780-26a2-11ea-818c-625f970f492e.png)

Why does JetBrains dotPeek and .deps.json disagree on the assembly Version?

**Comment by jkotas** [comment]
You are seeing difference between reference assembly versions and implementation assembly versions. https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies explains what these are.

The assembly metadata contain reference assembly version. If you are using the default setup, you should be able to find refererence assembly at `%USERPROFILE%\.nuget\packages\system.componentmodel.annotations\4.7.0\ref\netstandard2.0\System.ComponentModel.Annotations.dll`.

`.deps.json` contains implementation assembly version. You should be able to find the implementation assembly at "%USERPROFILE%\.nuget\packages\system.componentmodel.annotations\4.7.0\lib\netstandard2.0\System.ComponentModel.Annotations.dll".

What likely happened here was that a bug fix was made in `System.ComponentModel.Annotations.dll` implementation without changing its public surface. It is how we ended up with implementation assembly version to be higher than the reference assembly version.

**Comment by jzabroski** [comment]
Wow, I didn't realize that.  Glad I asked, and thankful for your prompt reply!  Happy Holidays.

**Comment by jzabroski** [comment]
@jkotas Does this behavior mean that _if I specify a nuget package version that is equivalent to whatever 4.2.0 is, that the .NET CLR will allow a third party to use a lower dependency than my nuget PackageReference suggests_?

**Comment by jzabroski** [comment]
Nevermind - I see my question is messed up.  The real issue is that the maintainers of System.ComponentModel.Annotations have two different assemblyVersions, one for net461 and one for netstandard2.0.  Under certain conditions (like referencing an MSBuild Task that loads an assembly that references System.ComponentModel.Annotations), this can create silent link/load failures that aren't detected by the compiler and are difficult to troubleshoot.

@dagood - I suspect this is the root cause of all the issues you recently researched.  This is rather mindblowing, because I would never expect someone to package the same dll with different assemblyVersions.  I guess it's "fair game", but still evil like [putting translucent super glue on the toilets at Home Depot](https://www.huffpost.com/entry/-home-depot-toilet-seat-prank-superglued-video_n_4419353) kind of prank.

![image](https://user-images.githubusercontent.com/447485/71450335-32a6ea00-272e-11ea-9f2a-c7725fe64a1e.png)

![image](https://user-images.githubusercontent.com/447485/71450357-77328580-272e-11ea-98bd-552ef4b27510.png)
