### ISSUE TITLE
Proposal: Add exception-safety support for IDisposable in non-owning context

### ISSUE THREAD

**Issue by wmx16835** [dotnet/runtime#1150]
Note: this issue was initially posted in a wrong channel, [dotnet/csharplang #3052](https://github.com/dotnet/csharplang/issues/3052). Thanks to @YairHalberstadt and @mikedn for their feedback and reminding me about the right place to float the idea.

**The Problem**

Currently, the "using" keyword guarantees exception-safety in a specific context by disposing the associated resources even if an exception is thrown in the block. However, RAII is not always appreciated when using resources. For example:

``` C#
Resource resource = new Resource();   // "Resource" is a class that implements the interface "IDisposable"
Configure(resource, currentContext);  // "Configure" is a method to configure the "resource"; "currentContext" represents a capture of runtime context
return resource;
```

The code will work fine if every function call returns normally. However, when an exception is thrown during configuration (the second line), the "resource" leaks.

We do not have this issue in C++ because of move semantics built on top of value semantics.

In the previous thread, @YairHalberstadt and @mikedn have suggested that this feature should "not belong in the standard library" because it is not general enough. However, I think the motivation should be strong enough, because "whether to dispose a resource or not" is an "yes or no" option in a certain context. The "using" keyword is designed for "yes", while the proposed library feature is for "no". Comparing C# and C++, every scoped value in C++ is a "using" in C#; every call to `UseWithoutOwning` is a "move construction" in C++.

**The Solution**

I would propose a utility method:

``` C#
public static TResource UseWithoutOwning<TResource>(TResource resource, Action<TResource> usingAction) where TResource : IDisposable;
```

It provides the mechanism of using disposable resources in an exception-safe way without binding the ownership to the current context. Its implementation is also straightforward (probably also check for null reference at runtime):

``` C#
public static TResource UseWithoutOwning<TResource>(TResource resource, Action<TResource> usingAction) where TResource : IDisposable
{
    try
    {
        usingAction(resource);
    }
    catch
    {
        resource.Dispose();
        throw;
    }
    return resource;
}
```

With the proposed method above, the motivating example could be refactored into:

``` C#
return UseWithoutOwning(new Resource(), theResource => Configure(theResource, currentContext));
```

It has similar behaviour except for exception-safty -- if the call to "Configure" throws, "resource.Dispose()" will be called automatically.

I am looking forward to your valuable comments.

Thanks,
Mingxin Wang

**Comment by scalablecory** [comment]
I think some language support for move semantics would do this a lot cleaner.

**Comment by wmx16835** [comment]
@scalablecory 

> I think some language support for move semantics would do this a lot cleaner.

Copied from @YairHalberstadt 's comments on [dotnet/csharplang #3052](https://github.com/dotnet/csharplang/issues/3052#issuecomment-568905132):

>I think it extremely unlikely that a special syntax for your current proposed library method would be added. A new language feature is orders of magnitude more expensive than new library features, so if there was doubt whether it's common enough to belong in the standard library, it almost definitely does not belong in the language.
>
>Instead you would need to come up with a more wide ranging design for adding full support for move semantics to C#.

I would much prefer to persue it as a pure library feature since it is apparently implementable, unless there is a sence of strong consensus in this group to make it a language feature.

**Comment by wmx16835** [comment]
Please refer to [the latest revision of this issue](https://github.com/dotnet/runtime/issues/1163).

Thanks,
Mingxin Wang
