### ISSUE TITLE
.net core 2.1  AppDomain.CurrentDomain.UnhandledException

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#11546]
_From @zhaojie on November 26, 2018 6:20_

.net core 2.1
To avoid program crash, I use AppDomain.CurrentDomain.UnhandledException to catch the unhandledexception，but the program still crashes and exits
 
Where to set this property of UnhandledExceptionEventArgs.IsTerminating ?

.net,  can set this legacyUnhandledExceptionPolicy 
` <runtime>
    <legacyUnhandledExceptionPolicy enabled="true" />
  </runtime>
`

but in .net core, hot to do?

_Copied from original issue: dotnet/corefx#33689_

**Comment by nxrighthere** [comment]
I've encountered this problem while working on the [integration](https://github.com/nxrighthere/UnrealCLR) of `hostfxr` into the game engine which should run continuously during development. It operates with dynamically loaded assemblies via `AssemblyLoadContext` and as soon as any unhandled exception occurs in user assemblies, the .NET Core runtime terminating the entire process with the editor of the game engine which leads to loss of all unsaved resources. I would like to get control over this behavior and redirect the exception output using a custom native function to the editor's console window (similar to `hostfxr_set_error_writer` but for the exceptions), then stop the execution of the logic and immediately unload the assembly without terminating the editor.

Any suggestions?

**Comment by janvorli** [comment]
@nxrighthere I have a naïve question - do the dynamically loaded assemblies have some well defined interface so that you could catch all exceptions on it?

**Comment by nxrighthere** [comment]
Nope, but I can implement this. A perfect solution for me would be to handle this globally and transparently for the end-user without involving an additional code into dynamic assemblies.

**Comment by janvorli** [comment]
I think that you can make it work without end user being involved probably in majority of the cases, however if the end user code used e.g. threads, strong GC handles, RegisteredWaitHandles or if it registered an event handler to some event that lives outside of their code (e.g. System.Diagnostics.Process.Exited) , it would need to cooperate on the shutdown by registering AssemblyLoadContext.OnUnload handler and shutting the threads, closing the strong handles, unregistering events etc.

**Comment by janvorli** [comment]
Please see https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability for all the details.

**Comment by nxrighthere** [comment]
@janvorli Yes, but how to prevent termination of the process that embeds `hostfxr`? According to this issue, we don't have an alternative to `legacyUnhandledExceptionPolicy` in .NET Core.

**Comment by janvorli** [comment]
My point was that if you can catch all the exception at the interface, there should not be any unhandled exceptions (other than access violations).

**Comment by nxrighthere** [comment]
Interesting, the process is still get terminated even if the code is wrapped with try/catch block:
```csharp
try {
    throw new Exception("Test exception");
}

catch (Exception exception) {
    return;
}
```

> The process was terminated due to an internal error in the .NET Runtime at IP 00007FFD813C66D9 (00007FFD81180000) with exit code 80131506.

**Comment by janvorli** [comment]
Are you saying that it behaves like this even in the simple block that looks exactly like what you've pasted above or is the throw somewhere in the code running inside of the unloadable context and the catch outside of it?

**Comment by nxrighthere** [comment]
Yes, it behaves like that exactly with this code. A dynamic assembly with a static function is loaded at runtime using `AssemblyLoadContext.LoadFromAssembly`, then a pointer to it is obtained and passed to the native runtime and invoked from there. If there are no exceptions, then the code executes just fine.

**Comment by janvorli** [comment]
So the throw / catch is inside the loaded assembly, right? Does the problem happen also when running without debugging (when running from command line or when running from the VS using "Start without debugging")?

**Comment by nxrighthere** [comment]
> So the throw / catch is inside the loaded assembly, right?

Yes. Exceptions in the parent assembly which was loaded using `hostfxr_get_runtime_delegate` with `load_assembly_and_get_function_pointer` from `coreclr_delegates.h`, are handled properly without any issues. Only in dynamically loaded assemblies, this error occurs.

> Does the problem happen also when running without debugging (when running from command line or when running from the VS using "Start without debugging")?

Nope, it works as intended just like in the parent assembly of `hostfxr`.

**Comment by janvorli** [comment]
Ok, then it is a problem with debugger / debugger support code. It may be the same as #2317.

**Comment by nxrighthere** [comment]
Yes, I have the exact same problem. Thank you for pointing me to this issue.

**Comment by janvorli** [comment]
Closing as dup of #2317
