### ISSUE TITLE
[Question] Profiling: How to get CLR runtime version while profiling

### ISSUE THREAD

**Issue by mihail-vladov** [dotnet/runtime#11555]
I am trying to understand what is the working CLR version while profiling. Until now I have used the [ICorProfilerInfo3::GetRuntimeInformation Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo3-getruntimeinformation-method). However, there are only two possible values for COR_PRF_RUNTIME_TYPE:
(_The runtime type. This parameter returns **COR_PRF_DESKTOP_CLR** for the desktop version of the CLR, or **COR_PRF_CORE_CLR** for the core version of the CLR used in Silverlight._)

How can I unambiguously distinguish the .NET Core CLR version from the desktop and Silverlight versions? I am asking this as ICorProfilerInfo3::GetRuntimeInformation is returning COR_PRF_CORE_CLR for Silverlight and for .NET Core CLR.
I am open to different approaches as well.

**Comment by davmason** [comment]
We fixed GetRuntimeInformation in 5.0 to return a real version, for 2.1, 3.0, 3.1 you can work around it by QI-ing for the right profiler interfaces. Off the top of my head 2.1 will have ICorProfilerInfo9 but nothing more, 3.0 will have ICorProfilerInfo10 but nothing more, and 3.1 will have ICorProfilerInfo11.

**Comment by mihail-vladov** [comment]
Hey David, thank you for the update. I will check it.
