### ISSUE TITLE
build is not incremental because it always writes artifacts/toolset/Common/configuration/configuration.props

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#1156]
`build.sh` from the root always takes me about ~13 minutes even with no changes (on an Alpine docker container in WSL2). 

I traced this back to `                    <Message Timestamp="0001-01-01T00:00:00.0000000">Input file "/runtime/artifacts/toolset/Common/configuration/configuration.props" is newer than output file "/runtime/artifacts/obj/Microsoft.Win32.SystemEvents/ref/netstandard2.0-Debug/Microsoft.Win32.SystemEvents.dll".</Message>`

Which is because `../runtime/artifacts/toolset/Common/configuration/configuration.props` is getting re-written every build in `./packages/microsoft.dotnet.build.tasks.configuration/5.0.0-beta.19617.1/build/Microsoft.DotNet.Build.Tasks.Configuration.targets`. in the `GenerateConfigurationProps` target.

Perhaps we could modify `arcade\src\Microsoft.DotNet.Build.Tasks.Configuration\src\GenerateConfigurationProps.cs` to compare the content of any existing one, and avoid writing a new one if it is has the same content.

cc @ericstj

**Comment by danmosemsft** [comment]
I ["fixed" this thus](https://github.com/dotnet/arcade/compare/master...danmosemsft:incre?expand=1) and the task only writes one file now (for some reason): `/runtime/artifacts/toolset/Common/configuration/setConfiguration.props`. 

The build still has other incrementality problems for example these messages are fairly early: `Input file "/runtime/artifacts/bin/ref/netcoreapp5.0/dotnet-Microsoft.XmlSerializer.Generator.dll" is newer than output file "/runtime/artifacts/obj/netstandard/netcoreapp5.0-Debug//netstandard.Forwards.cs".` and `Output file "/runtime/artifacts/obj/binplacePackages/netstandard2.0-Debug/.NETStandard,Version=v2.0.AssemblyAttributes" does not exist.`

This means there is still essentially a full build (17:26 here is the start of the 2nd build)
```
dan@danmose3:~/git/runtime$ find . -type f -newermt '17:26' | grep -v "log/\|CMake\|obj/"  | sed -n 's/..*\.//p' | sort | uniq -c
      1 Debug/corehost/apphost
      1 Debug/corehost/dotnet
      1 Debug/corehost_test/nativehost
     19 a
      4 dgml
   1066 dll
      5 gz
     70 json
    164 map
     84 nupkg
     33 nuspec
   1028 pdb
     33 pkgpath
    318 props
     25 so
      1 svg
     10 txt
    199 xml
dan@danmose3:~/git/runtime$
```

**Comment by ViktorHofer** [comment]
This was fixed by @Anipik's configuration system work.
