### ISSUE TITLE
The Vector64/128/256 helper methods should be treated as intrinsics on ARM64

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#11560]
https://github.com/dotnet/coreclr/pull/21198 started moving the Vector64/128/256 helper methods to be treated as intrinsics on xarch.

We should additionally ensure that ARM64 receives similar treatment after more of its intrinsic support comes online.

category:correctness
theme:intrinsics
skill-level:intermediate
cost:medium

**Comment by CarolEidt** [comment]
I believe that this has been completed.
