### ISSUE TITLE
HttpClient Proposal - add Connect and Socket timeouts

### ISSUE THREAD

**Issue by starovernet** [dotnet/runtime#11594]
**Problem**

We are writing financial services and have to be compliant with requirements, which force us to have different timeout values for TLS handshake and after connect till getting response. Quote from requirements: "Read timeouts occur while waiting on a transaction response after the connection has been established and the message is sent to the recipient. Connection timeouts occur while
making the initial connection (i.e. completing the TCP/IP connection and TLS handshake).". 

Link to spec:
https://www.emvco.com/terms-of-use/?u=/wp-content/uploads/documents/EMVCo_3DS_Spec_v220_122018.pdf

**Current workaround**

We can start Connection timeout before call `SendAsync`, then use `ServerCertValidationCallback` to stop it and start new timeout until receive response. Problem, that `ServerCertValidationCallback` occurs only for new connections, and if we reuse connection, we don't need to set it. In this case we can't reuse connection and need to set ConnectionClose property, which is bad for performance.

**Proposed Solution**

There is many ways to handle it. For example. 
 - Add 2 properties, like in Apache HttpClient 4 
```c# 
public class HttpClient : HttpMessageInvoker
{
    ...
    public TimeSpan ConnectTimeout { get; set; } 
    public TimeSpan SocketTimeout { get; set; }
    ...
}
```

 - Add new Event to HttpClient class 
```c# 
public event EventHandler Connected; 
```

**Comment by stephentoub** [comment]
ConnectTimeout already exists, just on the handler:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connecttimeout?view=netcore-3.1
You can do:
```C#
new HttpClient(new SocketsHttpHandler() { ConnectTimeout = ... });
```

**Comment by starovernet** [comment]
@stephentoub thanks! That's can help with second part - timeout for TLS hadnshake, but how can i set Read timeout?

**Comment by stephentoub** [comment]
> but how can i set Read timeout?

Can you clarify what it is you're looking for?  I can't tell from your description.  Are you saying that you want every individual ReadAsync call on the response stream to have a timeout (with the timeout resetting each time you call it), or are you saying you want a timeout on the time you issue the request to the time you receive the response headers, or something else?

**Comment by starovernet** [comment]
> Can you clarify what it is you're looking for?

I need to set timeout for every request, starting from moment, when connection established and until i start receiving response.

**Comment by stephentoub** [comment]
> I need to set timeout for every request, starting from moment, when connection established and until i start receiving response.

Why is it important that it not include setting up the connection? In many typical use cases, you're going to be getting an already established connection from the connection pool, and in cases where you don't, from a consumer perspective the setting up if the connection is still part of the time between when the request is sent and the response is received.

If you're comfortable with a timeout that's about the issuing of the request until headers are received, that's what HttpClient.Timeout is if you use The RequestHeadersReceived option when SendAsync'ing the request.

I think it's unlikely we'd add a timeout setting specifically to cover the time between connection being established and first response header byte received. That's a rare need.

**Comment by starovernet** [comment]
> 
Why is it important that it not include setting up the connection?
> 

It's important, because we need to implement different business logic for handle timeout during connection or during request handling, it's in spec of protocol, so, we can't change it..

> 
In many typical use cases, you're going to be getting an already established connection from the connection pool
> 

Yeah, that's our issue.. We have Connect timeout 10 seconds and timeout for request handling 5 seconds. If i want to set 5 seconds timeout, i have to write something like this:

```c#
      var cts = new CancellationTokenSource();
      cts.CancelAfter(TimeSpan.FromSeconds(5));
      return await _httpClient.SendAsync(message, cts.Token);
```

In our production environment sometimes it takes up to 7-10 seconds to finish SSL handshake (another server may be in different part of world or in China). It's mean, cancellation token got triggered even before SSL connection established, which make it non compliant.

**Comment by karelz** [comment]
Triage: We believe this is a very rare and very specific requirement. Currently we do not have intentions to provide such granular timeouts.
We plan to add logging and counters to be able to analyze such situations for diagnostic purposes, but not timeouts.

**Comment by eli-darkly** [comment]
I don't know if comments on closed issues will be seen, but I'd just like to say that for non-.NET developers this is not "a very rare and very specific requirement". The distinction between connection timeout and socket timeout is supported in just about every TCP library I've ever used other than this one. I realize that socket timeout (length of time in between packets) may not be quite the same as the kind of read timeout that @starovernet was talking about, but it is a standard concept. It really is not unusual for clients to want to tolerate slowness if it's due to the server being slow, but give up if handshakes and packets are so delayed as to indicate a major traffic jam on the network.

**Comment by Dinand01** [comment]
We eventually implemented our requirement by using ServerCertificateValidationCallback and disabling the connection pool, but the implementation is quite complicated and disabling the connection pool is not something we wanted to do but we didn't see any other options.
I don't think our scenario is very weird: we need to connect to a server in China, the time it takes until the TLS handshake completes can be up to 20 seconds from that point on everything is normal. 
For us it's a protocol requirement, but I think that having a distinction between timeouts can be useful to anybody with these types of issues (like connecting to China).
