### ISSUE TITLE
Can't use Interaction.InputBox

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#1162]
I have a .NET Core 3.1 WinForms project in which I want to use the `Interaction.InputBox` function. I'm getting the following error:

> 'Interaction' does not contain a definition for 'InputBox'

I already see the API in the repo [here](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/Interaction.vb#L129). So, if it's implemented by .NET Core, why that error shows up ?

**Comment by am11** [comment]
It was included [in 5.0](https://github.com/dotnet/corefx/pull/40365), but has not been ported to [3.x](https://github.com/dotnet/corefx/blob/release/3.1/src/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/Interaction.vb).

**Comment by cston** [comment]
Thanks for reporting this @Youssef1313. As @am11 mentioned, `Interaction.InputBox()` was included in 5.0 only.
