### ISSUE TITLE
Perf regression in some EqualityComparer tests on Linux

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#11650]
![image](https://user-images.githubusercontent.com/10121823/49825403-2e817780-fd39-11e8-8875-2719b4decd4a.png)

Regression is the jump in the blue line (Ubuntu x64).

(Similar slowdowns seen in ValueTupleCompareNoOpt and ValueTupleCompareWrapped).

Benchview tracking indicates regression was from dotnet/coreclr#20141.

@sandreenko can you investigate?
cc @dotnet/jit-contrib 

category:cq
theme:optimization
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
@sandreenko I moved this to 6.0 milestone, with the intention that we either create some new issue that identifies JIT/optimizer work that should be done, or we close the issue.

**Comment by sandreenko** [comment]
I was not able to track this down when it was fresh and with so many changes in that area I an closing it as could not repro.
