### ISSUE TITLE
StackOverflowException fires ICorDebug Exception callback only if on main thread

### ISSUE THREAD

**Issue by albahari** [dotnet/runtime#11677]
Tested on Windows with .NET Core 2.2 and  3.0.100-preview-009812

When a StackOverflowException or other program-terminating exception is thrown on a worker thread, it cannot be debugged because ICorDebugManagedCallback2 does not fire the Exception callback. 

You can reproduce this in Visual Studio as follows:

```
class Program
{
    static void Main (string[] args)
    {
        new Thread (() => Foo ()).Start ();
        Console.ReadLine ();
    }

    static void Foo() => Foo ();
}
```

When running with the VS debugger, the process terminates and no exception dialog appears.

The problem is worse in LINQPad because all query code runs on a worker thread.

**Comment by tommcdon** [comment]
closing as dupe of #10539
