### ISSUE TITLE
Fixup `impPopList` to eliminate the need to normalize SIMD and HWIntrinsic type handles

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#11670]
Currently `impPopList` is validating that the struct handle for a given `TYP_SIMD` matches the struct type we have from the stack's type information: https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L857

However, in `gtGetStructHandleIfPresent` we do not currently differentiate between SIMD types and HWIntrinsic types for the `GT_IND` and `GT_LCL_FLD` cases:
* https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L16446
* https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L16460

This means that we have to force normalization for these cases on 9/10 `Vector<T>` types and all of the HWIntrinsic types. It also means that we needed to update `gtGetStructHandleForSIMD` (https://github.com/dotnet/coreclr/pull/21549) to handle the case where we are trying to get a `HWIntrinsic` struct handle for a `TYP_SIMD` that is larger than the size of `Vector<T>` .

It may be beneficial to update this logic so that we are able to get the correct handle and avoid normalization when the types already line up.

category:implementation
theme:vector-codegen
skill-level:expert
cost:medium

**Comment by SingleAccretion** [comment]
Fixed with #67238, #68748, #70635 and #70888.
