### ISSUE TITLE
Allow SSE/SSE2 intrinsics in R2R and crossgen scenarios

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#11689]
CoreCLR currently requires SSE/SSE2 support as a "min-bar" on x86/x64. However, we have disabled all HWIntrinsic code-paths for the ready-to-run and crossgen scenarios.

Given that these ISAs are a minimum requirement and the JIT will already emit SSE/SSE2 instructions for non-HWIntrinsic code paths, we should look into enabling these two ISAs for the above scenarios.

**Comment by MichalStrehovsky** [comment]
@dotnet/crossgen-contrib I assume this one is okay to close.
