### ISSUE TITLE
Local test failure from `System.Xml.Xsl.XslTransformApi.Tests`

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#1170]
Specifically, `System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform` and `System.Xml.Tests.CTransformResolverTest.TC_AbsolutePath_Transform`; all 12 cases fail for both tests, to a total of 24 failures.  

Stack traces:
```
System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(inputType: URI, readerType: XmlValidatingReader, transformType: Writer, docType: XPathDocument)
   Source: CXslTransform.cs line 477
   Duration: 5 ms

  Message: 
    Assert.True() Failure
    Expected: True
    Actual:   False
  Stack Trace: 
    XsltApiTestCaseBase.VerifyResult(String expectedValue) line 512
    <>c__DisplayClass5_0.<TC_AbsolutePath_Transform>b__0() line 484
    XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction) line 118
    CXmlResolverTest.TC_AbsolutePath_Transform(InputType inputType, ReaderType readerType, TransformType transformType, DocType docType) line 479
```
```
System.Xml.Tests.CTransformResolverTest.TC_AbsolutePath_Transform(inputType: URI, readerType: XmlValidatingReader, transformType: Writer, docType: XPathDocument)
   Source: CXslTransform.cs line 2101
   Duration: 5 ms

  Message: 
    Assert.True() Failure
    Expected: True
    Actual:   False
  Stack Trace: 
    XsltApiTestCaseBase.VerifyResult(String expectedValue) line 512
    <>c__DisplayClass5_0.<TC_AbsolutePath_Transform>b__0() line 2107
    XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction) line 118
    CTransformResolverTest.TC_AbsolutePath_Transform(InputType inputType, ReaderType readerType, TransformType transformType, DocType docType) line 2103
```

It appears that the output from all 24 tests are the exact same.
```
  Standard Output:
    Loading style sheet as URI 
    TestFiles\TestData\XsltApi\xmlResolver_document_function_absolute_uri.xsl
    Loading XML TestFiles\TestData\XsltApi\fruits.xml
    Executing transform
    Expected : <?xml version="1.0" encoding="utf-8"?><result>123</result>
    Actual : <?xml version="1.0" encoding="utf-8"?><result></result>
```

Ran on Windows 10 Pro Insider builds (Build No. 19536), Korean (ko-KR).

**Comment by danmosemsft** [comment]
It is not obvious to me what this problem is from a look at the code. If you are willing to investigate a little, that would be great.

**Comment by Gnbrkm41** [comment]
I would take a look at it, though I'm not entirely sure about the whole Xsl transformation so some hints on ways to investigate would be great 🙂

**Comment by Gnbrkm41** [comment]
Figured out, turns out it had nothing to do with the environment:

* `xmlResolver_document_function_absolute_uri.xsl` is a test data file that's copied to the output folder from the source folder: https://github.com/dotnet/runtime/blob/0647ec314948904319da5eb15e9931f7c85ed1e2/src/libraries/System.Private.Xml/tests/Xslt/TestFiles/TestData/XsltApi/xmlResolver_document_function_absolute_uri.xsl#L5-L11
* `s_temporaryResolverDocumentFullName` is the path to a temp file containing the content of `xmlResolver_document_function.xml`, located in the same folder
https://github.com/dotnet/runtime/blob/0647ec314948904319da5eb15e9931f7c85ed1e2/src/libraries/System.Private.Xml/tests/Xslt/TestFiles/TestData/XsltApi/xmlResolver_document_function.xml#L1-L7
* When all goes well, the transformation should output `<?xml version="1.0" encoding="utf-8"?><result>123</result>` as it reads the content of each `elem` tag from `xmlResolver_document_function.xml` and concatenates them into one

Here, The `ABSOLUTE_URI` of `...absolute_uri.xsl` is replaced to `s_temporaryResolverDocumentFullName` when it's run for the first time, and there is no code that changes it back to `ABSOLUTE_URI`:
https://github.com/dotnet/runtime/blob/0647ec314948904319da5eb15e9931f7c85ed1e2/src/libraries/System.Private.Xml/tests/Xslt/XslTransformApi/XSLTransform.cs#L92-L98

And the content of `s_temporaryResolverDocumentFullName` changes every run, randomly:
https://github.com/dotnet/runtime/blob/0647ec314948904319da5eb15e9931f7c85ed1e2/src/libraries/System.Private.Xml/tests/Xslt/XslTransformApi/XSLTransform.cs#L52

This means that in the subsequent runs `document('PREVIOUS_TEMP_FILE')` function will fail because the xsl file references the old temporary file, which is non-existent, and therefore print nothing.
