### ISSUE TITLE
dotnet build raise error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/runtime#1173]
**Environment**
vs2019 v16.4.0 is installed
last netcore 3.1.100 is installed.
Console project.csproj SDK style , net461
reference a class library project netstandard2.0, net461
The class library reference the package: Microsoft.Net.Compilers.Toolset v 3.4.0 to support  c# 8 nullable in VS2017 .

Building the project using vs2019 IDE success.
Building the project using msbuild command success.: `msbuild /t:build`
Building the project using dotnet build fail with the error
>error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\3.1.100\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct,that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [F:\experiment\test.csproj]

Removing the package `"Microsoft.Net.Compilers.Toolset` and run dotnet build success.

How to stop this error in dotnet build?

**Comment by danmosemsft** [comment]
Hello @moh-hassan I think this probably should go to https://github.com/dotnet/roslyn. Can you close and reopen there?

**Comment by moh-hassan** [comment]
Thanks @danmosemsft  for reply.
Moving the question to [roslyn project](https://github.com/dotnet/roslyn/issues/40602)
