### ISSUE TITLE
RyuJIT bounds checks not eliminated for readonly arrays

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#11797]
Range analysis doesn't take into account readonly arrays and you need to make a function local reference to eliminate the range check.

https://github.com/dotnet/coreclr/issues/5371 regressed due to https://github.com/dotnet/coreclr/pull/15756

It shouldn't need to be conservative for a readonly array?

/cc @briansull @AndyAyersMS @mikedn 

category:cq
theme:bounds-checks
skill-level:expert
cost:medium
impact:medium

**Comment by jakobbotsch** [comment]
@EgorBo maybe your recent changes fixed this?

**Comment by EgorBo** [comment]
> @EgorBo maybe your recent changes fixed this?

Yes, we now fold nullchecks for `static readonly`
