### ISSUE TITLE
Upload symbols to symbol server

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#11793]
With https://github.com/dotnet/coreclr/pull/21769, we publish symbol packages to a blob feed, but they don't yet get uploaded to a symbol server.

- The arcade migration docs mention that `IsShipping` packages have symbols published to the symbol server by default.
- The onboarding samples do pass access tokens for the symbol server in the publish command: `/p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)` `/p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)`.
- Yet the default arcade publish logic appears not to upload to symweb using the SymbolUploader package unless UsingToolSymbolUploader is true, which isn't the case in any of the samples.

Corefx has additional symbol publishing logic using the SymbolUploader package.

**Comment by jashook** [comment]
@dagood is this issue still relevant?

**Comment by dagood** [comment]
Looks like it was completed by moving onto the arcade publish stages and other related efforts.
