### ISSUE TITLE
Differences in Codegen of method with ReadOnlySpan with In parameter modifier and without it

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/runtime#11805]
This is a spinoff of https://github.com/dotnet/corefx/issues/34568#issuecomment-453760485 as @jkotas  suggested that my reported behaviour should not happen.
I tried to reproduce it standalone without Expression Tree codegen and failed, so I tried to gather as much info as possible from the current code.

**Introduction**
In SpanJson I noticed a large ~15% regression in performance for UTF16 deserialization if I remove the ``In`` parameter modifier is removed. The UTF8 version is not affected.
Take the following code snippet
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static ulong ReadUInt64(in ReadOnlySpan<byte> span, int offset)
{
    return Unsafe.ReadUnaligned<ulong>(ref Unsafe.Add(ref MemoryMarshal.GetReference(span), offset));
}
```
(https://github.com/Tornhoof/SpanJson/blob/master/SpanJson/Helpers/SpanHelper.cs)

it is heavily used for the integer based property matching during deserialization, the same code exists for byte, ushort, uint32 and is used for both UTF8 and UTF16 , the difference for UTF16 that prior to that snippet there is a ``MemoryMarshal.AsBytes`` to get the bytes instead of chars for the matching and there are more calls to it as there are twice the bytes for utf16.

If I remove the ``in`` from these methods (and do not change anything else), there is a 15% regression in performance in my nested serializer tests for UTF16 and only UTF16:

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17763.253 (1809/October2018Update/Redstone5)
Intel Core i9-9900K CPU 3.60GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=3.0.100-preview-009844
  [Host]     : .NET Core 3.0.0-preview-27218-01 (CoreCLR 4.6.27217.02, CoreFX 4.7.18.61304), 64bit RyuJIT
  Job-MNYSVC : .NET Core 3.0.0-preview-27218-01 (CoreCLR 4.6.27217.02, CoreFX 4.7.18.61304), 64bit RyuJIT

UnrollFactor=2  

```

**With in**

|                                      Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------------------------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|     DeserializeAnswerWithSpanJsonSerializer | 3.556 us | 0.0209 us | 0.0196 us |      0.2937 |      0.0038 |           - |             1.84 KB |
| DeserializeAnswerWithSpanJsonSerializerUtf8 | 4.129 us | 0.0149 us | 0.0139 us |      0.2899 |           - |           - |             1.84 KB |                                      

**Without In**									  

|         							   Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------------------------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|     DeserializeAnswerWithSpanJsonSerializer | 4.081 us | 0.0462 us | 0.0432 us |      0.2899 |           - |           - |             1.84 KB |
| DeserializeAnswerWithSpanJsonSerializerUtf8 | 4.151 us | 0.0343 us | 0.0287 us |      0.2899 |           - |           - |             1.84 KB |

**Analysis so far** 

***IL Dumps***
I dumped the IL of both variants via WinDbg and the difference is pretty much non-existent.
The only consistent difference is, for each and every call to one of those Read methods is the use of **ldloca.s** in the fast one and **ldloc.s** in the slow one (notice the missing **a**)
This is expected, as we're using byref.
***Fast Version with In***

```csharp
IL_0049: ldloca.s VAR OR ARG 4
IL_004b: ldc.i4.0 
IL_004c: call 6000008 SpanJson.Helpers.SpanHelper.ReadUInt64(System.ReadOnlySpan`1<Byte> ByRef, Int32)
```
***Slow Version without  In***

```csharp
IL_0049: ldloc.s VAR OR ARG 4
IL_004b: ldc.i4.0 
IL_004c: call 6000008 SpanJson.Helpers.SpanHelper.ReadUInt64(System.ReadOnlySpan`1<Byte>, Int32)
```
The full dumps of serialization code is attached (it includes all dynamic method, including a few unrelated ones), if you compare it via WinMerge, the only differences (besides offsets) is that with ``In`` it uses ldloc**a**.s and without ``In`` it uses ldloc.s, sometimes it also uses ldloca.s VAR OR ARG 3 and ldloc.3 in the slow version (I tracked that down to the enum deserialization code, which uses the same concept).

[ILDumpWithoutIn.txt](https://github.com/dotnet/coreclr/files/2753343/ILDumpWithoutIn.txt)
[ILDumpWithIn.txt](https://github.com/dotnet/coreclr/files/2753344/ILDumpWithIn.txt)

For dumping in Windbg I used
<details>

```js

"use strict";

function initializeScript() {
    return [new host.apiVersionSupport(1, 3)];
}

function invokeScript() {
    var ctl = host.namespace.Debugger.Utility.Control;
    var output = ctl.ExecuteCommand("!dumpheap -type DynamicMethod");
    host.diagnostics.debugLog("***> Displaying command output \n");

    for (var line of output) {

        var ilOutput = ctl.ExecuteCommand("!dumpil " + line.split(" ")[0]);
        for (var line2 of ilOutput) {
            host.diagnostics.debugLog(line2 + "\n");
        }
    }

    host.diagnostics.debugLog("***> Exiting RunCommands Function \n");

}
```
</details>

***JIT Dumps***
After the IL dumps didn't help much, I proceeded to dump the disassembly and (as much as possible) the Jit data via COMPlus_JitDisasm and Complus_JitDump.
JitDisasm is the full one as it's small and JitDump is only for lambda_method, which appears to be the name of the deserialization functors.

[jitdisasmwithin.txt](https://github.com/dotnet/coreclr/files/2753346/jitdisasmwithin.txt)
[jitdisasmwithoutin.txt](https://github.com/dotnet/coreclr/files/2753347/jitdisasmwithoutin.txt)

Comparing the disassembly via WinMerge shows a fairly large difference for a lambda_method at the end, according to the var/tmp listing it has 30 extra vars  and the disasm shows quite a bit of extra work for the version without ``In``, the code size of that specific method is ~50% bigger. (starts at line 45257). I think it's safe to assume that's the/a problem there.

One of the more common extra code snippets in the version without ``in`` looks like:
```asm
       lea      rcx, bword ptr [rsp+888H]
       mov      bword ptr [rcx], r14
       mov      dword ptr [rcx+8], r12d

G_M13327_IG36:
       vmovdqu  xmm0, qword ptr [rsp+888H]
       vmovdqu  qword ptr [rsp+878H], xmm0

G_M13327_IG37:
       mov      rcx, bword ptr [rsp+878H]
```

The JitDump for both versions is located here: https://github.com/Tornhoof/SpanJson/blob/InROS/SpanJson.Console/jitdump_lambda_method.zip
(each file is ~150 Mb, WinMerge_x64 is can still compare it usefully though)

**Repro**
1. Clone https://github.com/Tornhoof/SpanJson/tree/InROS
2. cd SpanJson\SpanJson.Benchmarks (there is also .Console which only deserializes a known payload, this decreases the jitdump size)
3. dotnet run -c Release
4. Remove the ``in`` parameter modifiers in https://github.com/Tornhoof/SpanJson/blob/InROS/SpanJson/Helpers/SpanHelper.cs
5. dotnet run -c Release

category:cq
theme:optimization
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
>  I don't think there is much to do here

Based on this, and the age of this, I'm closing this.
