### ISSUE TITLE
Compiling and unloading code at runtime

### ISSUE THREAD

**Issue by daniprog** [dotnet/runtime#1186]
Hello,
im using .net core (raspberry pi) to hosting an telegram bot. The bot should be able to be the most time online. But also when i have an updated code, i want the new code running. I got it already with the AssemblyLoadContext Code from some pages to work. Now the Problem is that i cant recompile the new code. I get everytime AssemblyLoadContext doesnt contain the Function called Unload. And when i dont use this, i get the error The Code with the same name already loaded. But its a fully new source code. Can someone help me maybe?
Thats my code it works 1time compiled. Some variables are useless without context, but they needed. I have the if else case at bottom, to look if the code compiled successfully use the new code, otherwise the old one. And there it runs into failing after recompile other code. Some variables are also to look at the other thread which status is now. Cause i dont found a solution to unload the code at other functions. So thread starting and using in other functions outside this thread.

private static void compilecode()
        {
            threadrunning = true;
            Console.WriteLine("Thraed started...");
            string code = "";
            string path = @"/home/pi/Desktop/program_compile.cs";
            if (File.Exists(path))
                code = File.ReadAllText(path);
            
            var dotnetCoreDirectory = System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory();

            var compilation = CSharpCompilation.Create("Testing")
                .WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
                .AddReferences(
                    MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Console).GetTypeInfo().Assembly.Location),
                    MetadataReference.CreateFromFile(Path.Combine(dotnetCoreDirectory, "mscorlib.dll")),
                    MetadataReference.CreateFromFile(Path.Combine(dotnetCoreDirectory, "netstandard.dll")),
                    MetadataReference.CreateFromFile(Path.Combine(dotnetCoreDirectory, "System.Runtime.dll")))
                .AddSyntaxTrees(CSharpSyntaxTree.ParseText(code));
            /*
            // Debug output. In case your environment is different it may show some messages.
            foreach (var compilerMessage in compilation.GetDiagnostics())
                Console.WriteLine(compilerMessage);
            */
            using (var memoryStream = new MemoryStream())
            {
                var emitResult = compilation.Emit(memoryStream);
                if (emitResult.Success)
                {
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    var context = AssemblyLoadContext.Default;
                    assemblycontext = context;
                    context.IsCollectible = true;
                    code_compiled = context.LoadFromStream(memoryStream);
                    compiling_status = true;
                    compiling_done = true;
                    unloading_assembly = false;
                    while (!unloading_assembly) { }
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    if (context.IsCollectible)
                        context.Unload();
                    else
                        context = null;
                    unloaded_assembly = true;
                    unloading_assembly = false;
                }
                else if (assemblycontext != null)
                {
                    memoryStream.Seek(0, SeekOrigin.Begin);
                    
                    var context = assemblycontext;
                    context.IsCollectible = true;
                    code_compiled = context.LoadFromStream(memoryStream);
                    running_old_code = true;
                    compiling_status = false;
                    compiling_done = true;
                    unloading_assembly = false;
                    while(!unloading_assembly) { }
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    if (context.IsCollectible)
                        context.Unload();
                    else
                        context = null;
                    unloaded_assembly = true;
                    unloading_assembly = false;
                }
                else
                {
                    running_old_code = false;
                    compiling_status = false;
                    compiling_done = true;
                }
            }
            Console.WriteLine("Thread ended...");
            threadrunning = false;
        }

**Comment by Gnbrkm41** [comment]
I'm not sure if there would be a safe / reliable way to unload an assembly after it has been loaded. There could be other threads and stuffs that are already executing with the old assembly.

Not really an answer to this question... but wouldn't it be much easier to make a watcher app/script of some sort and let that download the updated executable (that has been compiled elsewhere), close the old version & launch the new version?

**Comment by bugtesterdani** [comment]
Maybe there could be something. But I wanted it to use it with that😅. When no answer is how to unload it (i forgot to say I can’t unload cause it’s also not Collectiable), I should make it with an bash script you told. It’s not easier I think, but the way it would really work (not the best way).

And there will be no executing anymore in any other threads of this assembly. So there should be no Problem. And the full Programm is paused while unloading and new loading. But not while compiling.

**Comment by Rohansi** [comment]
You need to load your code into a separate `AssemblyLoadContext` instead of `AssemblyLoadContext.Default`.

Every time you unload your separate `AssemblyLoadContext` you must discard it and create a new one when you want to load code again.

Every single use of the code loaded from the collectible ALC must be cleaned up and collected by the GC. This could be instances of classes, event handlers, etc. The GC must also collect the ALC instance before unloading can occur.

Unloading might take a few GC collect cycles to complete as long as the conditions above are followed.

**Comment by vitek-karas** [comment]
Answer by @Rohansi is the correct approach. Please reopen this or open a new issue if you still run into problems.
