### ISSUE TITLE
JIT: Inline optimization for Thread.Volatile methods

### ISSUE THREAD

**Issue by oakio** [dotnet/runtime#1189]
Strange JIT method inlining policy for method `Foo`
```csharp
class Foo
{
    private int _value;
    public void Bar()
    {
        int value = Thread.VolatileRead(ref _value);
        Thread.VolatileWrite(ref _value, value);
    }
}
```
JIT produces:
```
00007FF92AD11DE0 push      rbp
00007FF92AD11DE1 sub       rsp,30h
00007FF92AD11DE5 lea       rbp,[rsp+30h]
00007FF92AD11DEA xor       eax,eax
00007FF92AD11DEC mov       [rbp-4],eax
00007FF92AD11DEF mov       [rbp+10h],rcx
00007FF92AD11DF3 mov       rcx,[rbp+10h]
00007FF92AD11DF7 cmp       [rcx],ecx
00007FF92AD11DF9 mov       rcx,[rbp+10h]
00007FF92AD11DFD add       rcx,8
00007FF92AD11E01 call      0000`7FF9`2ACE`5218h
00007FF92AD11E06 mov       [rbp-4],eax
00007FF92AD11E09 mov       rcx,[rbp+10h]
00007FF92AD11E0D cmp       [rcx],ecx
00007FF92AD11E0F mov       rcx,[rbp+10h]
00007FF92AD11E13 add       rcx,8
00007FF92AD11E17 mov       edx,[rbp-4]
00007FF92AD11E1A call      0000`7FF9`2ACE`5280h
00007FF92AD11E1F nop
00007FF92AD11E20 lea       rsp,[rbp]
00007FF92AD11E24 pop       rbp
00007FF92AD11E25 ret
```
Expected
```
00007FF92AD11DE0 add       rcx,8
00007FF92AD11DE4 mov       rax,rcx
00007FF92AD11DE7 mov       eax,[rax]
00007FF92AD11DE9 mov       [rcx],eax
00007FF92AD11DEB ret
```

> $ dotnet --info                                   
> .NET Core SDK (reflecting any global.json):       
>  Version:   3.1.100                               
>  Commit:    cd82f021f4                            
>                                                   
> Runtime Environment:                              
>  OS Name:     Windows                             
>  OS Version:  10.0.18362                          
>  OS Platform: Windows                             
>  RID:         win10-x64                           
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.100\
>                                                   
> Host (useful for support):                        
>   Version: 3.1.0                                  
>   Commit:  65f04fb6db

**Comment by omariom** [comment]
Try to use [Volatile class](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile?view=netstandard-2.0)

**Comment by oakio** [comment]
@omariom, same results

**Comment by jkotas** [comment]
You are looking at code compiled with optimizations off. The code compiled with optimizations on looks exactly like your expected snippet.

Note that .NET Core 3.0+ has tiered compilation enabled by default. It means that most methods are compiled with optimizations off initially. You may want to either disable tiered compilation by setting `COMPlus_TieredCompilation=0` environment variable, or call the method in a loop and only look at the disassembly once the tiered compilation kicks in.

**Comment by oakio** [comment]
@jkotas Thanks!
