### ISSUE TITLE
How does vtfixup get handled on Unix?

### ISSUE THREAD

**Issue by niklaskarl** [dotnet/runtime#11904]
I have a legacy project using .vtfixup to call into managed from a native application. I am wondering how porting to cross-platform can be accomplished the easiest way. Is it possible to load the assemblies using the Unix-Hosting interface and get the HMODULE (or dlopen equivalent) of the loaded assembly? Are exports and relocations applied on Unix at all or do I have to switch to CreateDelegate?

**Comment by jkotas** [comment]
We have no plans to support vtfixups on Unix. 

Let's use https://github.com/dotnet/runtime/issues/34571 to track the more general scenario of exposing .NET assemblies as native binaries.
