### ISSUE TITLE
How to disable using HTTP_PROXY as default

### ISSUE THREAD

**Issue by dhmuralikrishna** [dotnet/runtime#1191]
#36553

How can we turn off this new default implementation?

I have environment variables HTTP_PROXY. But I want to use system-level proxy default instead of environment variables. I don't want to delete the environment variables because it used by other applications. How can I set to go for system proxy?

**Comment by scalablecory** [comment]
There's currently no way to disable this behavior. You'll need to disable/enable the envvar on a per-app basis to work around it.

**Comment by scalablecory** [comment]
You'll need to remove the envvars, either prior to launching the app or in your app itself prior to using HttpClient:

```c#
Environment.SetEnvironmentVariable("HTTP_PROXY", null);
Environment.SetEnvironmentVariable("HTTPS_PROXY", null);
Environment.SetEnvironmentVariable("ALL_PROXY", null);
Environment.SetEnvironmentVariable("NO_PROXY", null);
```

**Comment by dhmuralikrishna** [comment]
Thanks that works. You are awesome 👏
