### ISSUE TITLE
[Intrinsic] CompareEqual does not use the memory source instruction

### ISSUE THREAD

**Issue by redknightlois** [dotnet/runtime#11921]
I was trying to optimize `SequenceCompareTo` beyond the point where @benaadams pushed it and stumbled upon various JIT issues controlling the output. 

From this code a few are showcased.
```csharp
Avx2.CompareEqual(LoadVector256(ref first, (IntPtr)lengthAndOffset), LoadVector256(ref second, (IntPtr)lengthAndOffset))
```

It generates:
```asm
movsxd      rdi,esi      
vmovupd     ymm0,ymmword ptr [r11+rdi]  # allocation of usable register should prevent the previous instruction
movsxd      rdi,esi      # useless move
vmovupd     ymm1,ymmword ptr [r10+rdi]  
vpcmpeqb    ymm0,ymm0,ymm1   
```

I doubt that the `movsxd` creates a false dependency, but it could use cpu registers which will impact the loop. Probably the worst setback is that is:

```asm
vmovupd     ymm1,ymmword ptr [r10+rdi]  
vpcmpeqb    ymm0,ymm0,ymm1   
```

which could become instead:

```asm
vpcmpeqb    ymm0, ymm0, ymmword ptr [r10+rdi]  
```
using the memory version instead we avoid a data dependency and also using extra physical registers. 

Removing the movs and the compare encoding the code should look like:

```asm
movsxd      rdi,esi   # outside the loop if really necessary
Loop:
vmovupd     ymm0,ymmword ptr [r11+rdi]
vpcmpeqb    ymm0, ymm0, ymmword ptr [r10+rdi] 
vpmovmskb   edi,ymm0  
...
add       rdi, -32
jna         Loop
```

category:cq
theme:hardware-intrinsics
skill-level:expert
cost:medium

**Comment by tannergooding** [comment]
This was fixed in a few different ways a while back.

Not only are most `Unsafe.*` APIs treated directly as intrinsic, but there is also now a `Vector256.LoadUnsafe(ref T source, nuint elementOffset)` API. Using either the original approach or the dedicated API generates the expected codegen with containment working as expected.
