### ISSUE TITLE
could be return actual Packet Length when called ReceiveFromXX ReceiveMessageFromXX

### ISSUE THREAD

**Issue by sgf** [dotnet/runtime#1192]
when we called **ReceiveFrom,ReceiveMessageFrom,ReceiveFromAsync and ReceiveMessageFromAsync**
developer can't get the **UDP Packet Logic-Size(actual length)** from the API.

(im not sure that the data packets are already in the buffer, 
why can't the UDP actual length be returned to the developer while the API copying the buffer in the internal .)

**Comment by scalablecory** [comment]
These APIs all return the actual number of bytes read, which may be less than the size of the buffer passed in.

**Comment by sgf** [comment]
> These APIs all return the actual number of bytes read, which may be less than the size of the buffer passed in.
But the developers do not know the received data if is complete.Especially when I call ReceiveMessageFrom, ReceiveMessageFromAsyncXXX.

**Comment by sgf** [comment]
If I call ReceiveFrom then the data will be lost. If I set SocketFlag.Peek then I need to call the API multiple times.But I still can't get the actual data size anyway.I just know that the buffer length I gave is not enough?

**Comment by poizan42** [comment]
The max size of a udp packet is 64KiB. Unless you have 10000's of read requests in flight simultaneously you should probably just use a buffer that big.

**Comment by sgf** [comment]
> The max size of a udp packet is 64KiB. Unless you have 10000's of read requests in flight simultaneously you should probably just use a buffer that big.

yes (Maximum 64kb per packet), but I am currently building a high-performance UDP server.I have to try to save memory and support for high concurrency.

**Comment by scalablecory** [comment]
Okay, so you're looking for a way to get the exact size of the next packet `ReceiveFrom` will return. This makes sense.

There is no feature exposed to do this. I would follow @poizan42's advice, with a note that for IPv6 you can have larger than 64KiB so it's still not foolproof.

What might work on POSIX platforms -- you'll want to test it and this would only work unofficially and unsupported, but I don't believe we currently do anything that would block this -- is to pass in `SocketFlags.Peek | SocketFlags.Truncated`. This would peek and return the required length. Windows does not support this so it will not be portable, and we might break you in future versions.

**Comment by sgf** [comment]
> Okay, so you're looking for a way to get the exact size of the next packet `ReceiveFrom` will return. This makes sense.
> 
> There is no feature exposed to do this. I would follow @poizan42's advice, with a note that for IPv6 you can have larger than 64KiB so it's still not foolproof.
> 
> What might work on POSIX platforms -- you'll want to test it and this would only work unofficially and unsupported, but I don't believe we currently do anything that would block this -- is to pass in `SocketFlags.Peek | SocketFlags.Truncated`. This would peek and return the required length. Windows does not support this so it will not be portable, and we might break you in future versions.

Because UDP packets have a length field, I thought it might be easier at first.

So, would you suggest me to close this issue or wait for it to achieve someday in the future?
(It may not be possible for a long time, and must wait for the API to be added at the base of the OS.).

**Comment by scalablecory** [comment]
> So, would you suggest me to **close** this issue or **wait** for it to achieve someday in the future?

Closing is reasonable. My feeling is that if there was demand for such a feature, it would have been added to Windows long ago. It seems unlikely at this point that a new significant business need would be found.
