### ISSUE TITLE
JIT generates suboptimal instructions for 2D vector struct

### ISSUE THREAD

**Issue by nickgravelyn** [dotnet/runtime#11940]
I've been [benchmarking](https://github.com/nickgravelyn/math-struct-benchmark) various approaches to implement basic math struct operators for projects like FNA and MonoGame and among the results was the finding that 2D vectors were across the board slower than 3D and 4D. After some digging I [isolated the tests](https://github.com/nickgravelyn/math-struct-benchmark/tree/vector2-focus) and got the disassembly which shows that a struct with 3 float fields generates far more optimized instructions than a struct with 2 floats. This leads to the 2D vector being roughly 6x slower than the 3D vector.

The code for the entire benchmark can be found in https://github.com/nickgravelyn/math-struct-benchmark/blob/vector2-focus/Program.cs and the disassembly generated can be viewed in https://github.com/nickgravelyn/math-struct-benchmark/tree/vector2-focus#disassembly

category:cq
theme:structs
skill-level:expert
cost:medium

**Comment by CarolEidt** [comment]
This was fixed in 5.0 by improvements for enregistering small structs.
