### ISSUE TITLE
Custom internal calls in .NET Core hosting

### ISSUE THREAD

**Issue by NextTurn** [dotnet/runtime#11941]
P/Invoke is not so efficient as internal calls when working with frequent native code calls, for instance, game scripting runtime.

Internal calls in CoreCLR are hard coded in `ecalllist.h` and limited to `mscorlib.dll` scope. While Mono provides a `mono_add_internal_call` API which became the first choice of Unity and CRYENGINE.

Will you provide an API to register custom internal calls?

**Comment by AaronRobinsonMSFT** [comment]
@NextTurn I don't see any current action here so am closing this. Please file a new issue if there is some action that is being suggested or asked about. Thank you.
