### ISSUE TITLE
KeyValuePair is not properly serialized with JsonNamingPolicy.CamelCase - System.Text.Json

### ISSUE THREAD

**Issue by untaught** [dotnet/runtime#1197]
When serializing a collection of KeyValuePair with CamelCase enabled the properties are serialized in PascalCase:

MVC Configuration is: 
```c#
.AddJsonOptions(options =>
{
    options.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
    options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
}
```

The result is:
```
{ Key: "Test", Value: "Test1" }
```

Expected result:
```
{ key: "Test", value: "Test1" }
```

**Comment by ericstj** [comment]
@layomia can you please file a breaking change issue: https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md

**Comment by ericstj** [comment]
Removing breaking change as it is tracked with https://github.com/dotnet/runtime/pull/36424
