### ISSUE TITLE
Jit doesn't recognise ldstr as non-null

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#12011]
```csharp
public ReadOnlySpan<char> Hello() => "Hello".AsSpan();
```
```
.method public hidebysig 
    instance valuetype [System.Memory]System.ReadOnlySpan`1<char> Hello () cil managed 
{
    // Method begins at RVA 0x2050
    // Code size 11 (0xb)
    .maxstack 8

    IL_0000: ldstr "Hello"
    IL_0005: call valuetype [System.Memory]System.ReadOnlySpan`1<char> [System.Memory]System.MemoryExtensions::AsSpan(string)
    IL_000a: ret
}
```
```asm
G_M23320_IG01:
       nop      

G_M23320_IG02:
       mov      rax, 0xD1FFAB1E
       mov      rax, gword ptr [rax]
       test     rax, rax               ; not needed
       jne      SHORT G_M23320_IG03    ; not needed
       xor      rcx, rcx               ; not needed
       xor      r8d, r8d               ; not needed
       jmp      SHORT G_M23320_IG04    ; not needed

G_M23320_IG03:
       mov      ecx, dword ptr [rax]   ; not needed   
       mov      rcx, rax               ; not needed             ?
       cmp      dword ptr [rcx], ecx   ; not needed
       add      rcx, 12                ; r8d, dword ptr [rax+8] ?
       mov      r8d, dword ptr [rax+8] ; add      rax, 12       ?

G_M23320_IG04:
       mov      bword ptr [rdx], rcx   ; bword ptr [rdx], rax   ?
       mov      dword ptr [rdx+8], r8d
       mov      rax, rdx

G_M23320_IG05:
       ret      

; Total bytes of code 56, prolog size 5 for method Program:Hello():struct:this
```

/cc @GrabYourPitchforks 

/cc @KrzysztofCwalina as you mentioned in https://github.com/dotnet/roslyn/pull/24621#issuecomment-371671092

> Sure, but it has nothing to do with ranges. We could do the same optimization for
>
> ```cs
> ReadOnlySpan<char> x = "str"; 
> ```

category:cq
theme:basic-cq
skill-level:expert
cost:large

**Comment by am11** [comment]
> Once the string is materialized the jit can also inspect it, so we can do similar things with readonly static strings.

Do these `static readonly` after materialization get classified as `GT_CNS_STR`, where values are purely runtime constants; i.e. maybe skip cases like:

```c#
static readonly string sm_str = "default";
static X()
{
    if (someRuntimeCondition())
    {
        sm_str = "overwritten";
    }
}
```
(i was thinking if `static readonly` string could take advantage of @EgorBo's optimization for const strings: https://github.com/dotnet/runtime/pull/1378)

**Comment by EgorBo** [comment]
@am11 not sure,
but I think it should work for tier0->tier1 jit - when it re-compiles the methods it sees that the static ctor already inited so it bakes constant into static readonly fields. (not sure it will bake GT_CNS_STR though).

**Comment by EgorBo** [comment]
Can be closed I guess (via https://github.com/dotnet/runtime/pull/1378 + https://github.com/dotnet/runtime/pull/37245)
![image](https://user-images.githubusercontent.com/523221/97293009-1481ad00-185d-11eb-92c0-5f7198e6aba0.png)
