### ISSUE TITLE
Hosting multiple CLR side-by-side

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#12018]
I'm working on a plugin system for a native app, and I was hoping to load multiple CLRs side-by-side (for isolation and other practical reasons).

The [hosting documentation](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting) states it's supported for different versions of the CLR:

> Because .NET Core is able to run side-by-side with itself, it's even possible to create hosts which initialize and start multiple versions of the .NET Core runtime and execute apps on all of them in the same process.

However, when calling `coreclr_initialize` a second time, I always get an error code 0x80131022. Could it be that side-by-side only works when using different versions of the CLR?

Note: I don't know if it's relevant, but I only tried on Linux.

**Comment by joperezr** [comment]
From the above there doesn't seem to be anything actionable on the framework side other than perhaps updating docs so I will go ahead and close this for now. Feel free to reopen if that is not the case.
