### ISSUE TITLE
How to debug System.Private.CoreLib?

### ISSUE THREAD

**Issue by duzenko** [dotnet/runtime#12045]
There is an extensive walk through for the CoreCLR itself but the basic classes e.g. System.Private.CoreLib do not seem to have any docs online on debugging

Since it's a Class Library, it needs a referencing project in the solution but simply providing one results in a number of "type XXX exists in both..." errors as well as "Predefined type XXX is not defined or imported"

**Comment by davmason** [comment]
Closing this since there has been no update in quite some time. If there is any unanswered question feel free to reopen.
