### ISSUE TITLE
How to change the size of default stack?

### ISSUE THREAD

**Issue by KichangKim** [dotnet/runtime#12042]
Hi, I want to know how to change the size of default stack.

It seems that .NET Core uses more stack memory than .NET Framework 4.x, so some application which heavily use stack memory does not work with .NET Core. The only solution is creating Thread with more stack memory manually. But it is not work for built-in threading methods, because it depends ThreadPool and ThreadPool uses default-stack size.

Releated issue is here : https://github.com/Microsoft/CNTK/issues/3368

**Comment by stephentoub** [comment]
Closing as fixed by https://github.com/dotnet/coreclr/pull/24532.
