### ISSUE TITLE
TemporaryFile class

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#1204]
Is there such a thing as a "TemporaryFile" class?  I'm looking for a class that essentially represents a temporary file that is generated with an automatic file name and automatically deleted once it has been disposed and all open readers/writers are also disposed.  Is there such a thing?  If not, I'd like to create a feature request for it.

**Comment by Joe4evr** [comment]
[`Path.GetRandomFileName`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getrandomfilename)?

**Comment by TonyValenti** [comment]
That only seems to generate the file.  It doesn't seem to do anything to ensure that it automatically get's cleaned up.

**Comment by mikedn** [comment]
> and automatically deleted once it has been disposed

The `FileStream` constructor option `FileOptions.DeleteOnClose` might be useful. Not sure how well it works on Linux, as AFAIK it is emulated since it's not directly supported by the underlying IO API.

**Comment by Symbai** [comment]
There is an idea to rework the temp design schema so its getting disposable, more information here: https://github.com/dotnet/corefx/issues/41961#issuecomment-544755014

**Comment by stephentoub** [comment]
> Path.GetRandomFileName()?
> The FileStream constructor option FileOptions.DeleteOnClose might be useful. 

Yup, I think this is about as close as you'll get, e.g.
```C#
using (var fs = new FileStream(Path.GetRandomFileName(), FileMode.Create, FileAccess.ReadWrite, FileShare.None, 0x1000, FileOptions.DeleteOnClose))
{
    // ...
}
```
On Windows, the OS will handle deleting that file when you dispose the FileStream.  On Unix, we explicitly unlink the file as part of FileStream.Dispose:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L262-L270

**Comment by JeremyKuhne** [comment]
@TonyValenti adding API to generate a temporary file in one step is something I've been considering for quite some time. https://github.com/dotnet/runtime/issues/2048 is the current issue tracking adding this sort of functionality.
