### ISSUE TITLE
Cannot specify CipherSuitePolicy on Windows

### ISSUE THREAD

**Issue by Summpot** [dotnet/runtime#1206]
How to specify which cipher suites should be used on Windows or is there any other way to restrict HttpClient to use specific cipher suites when making an Http request?

**Comment by pinkfloydx33** [comment]
You can specify an `HttpMessageHandler` and it's options directly to the client's constructor. Specifically you can use the [`SslOptions`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=netcore-3.1#System_Net_Http_SocketsHttpHandler_SslOptions) property of the `SocketsHttpHandler` which has [various properties](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=Netcore-3.0) of its own related to Ssl and cipher suites

**Comment by Summpot** [comment]
> You can specify an `HttpMessageHandler` and it's options directly to the client's constructor. Specifically you can use the [`SslOptions`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=netcore-3.1#System_Net_Http_SocketsHttpHandler_SslOptions) property of the `SocketsHttpHandler` which has [various properties](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=Netcore-3.0) of its own related to Ssl and cipher suites

But it will throw a PlatformNotSupportedException on Windows,I need to specify the CipherSuites to use on Windows.

**Comment by vcsjones** [comment]
This appears to be a known limitation right now. `CipherSuitePolicy` does not work on Windows, yet. https://github.com/dotnet/corefx/issues/24588#issuecomment-482764511

/cc @krwq

**Comment by krwq** [comment]
Unfortunatelly SChannel (Windows SSL implementation) does not allow controlling cipher suites per session, you will need to do it through Windows registry globally. See https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc

I'm not aware of any plans for Windows to add this feature (although we have requested that when adding CipherSuitesPolicy support for Linux/OSX).

Windows theoretically has some switches to disable certain algorithms per session but support is very limited and not good enough to implement anything sensible cross platform.

**Comment by Summpot** [comment]
How does this python library [urllib3](https://github.com/urllib3/urllib3) implement CipherSuite?
Looks like it [wraps sockets](https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/ssl_.py#L105-L150) via python library [ssl](https://github.com/pypa/ssl)
It is used by [requests](https://github.com/psf/requests) and works fine on Windows and Linux

**Comment by vcsjones** [comment]
@Summpot I would presume it is using a different TLS library on Windows like openssl, NSS, etc. .NET Code on Windows uses SChannel on Windows, and that is the limitation.

**Comment by Summpot** [comment]
Is there any way for me to use openssl on windows?

**Comment by krwq** [comment]
@Summpot not at the moment (only WSL if that counts), you might be able to create a build which does it though

**Comment by Summpot** [comment]
ok,thanks!
