### ISSUE TITLE
What are dynamic symbol files?

### ISSUE THREAD

**Issue by arkadiuszwojcik** [dotnet/runtime#1208]
This is probably general question regarding runtime/compiler but I would like to ask it basing on my particular case. For my project I'm using [OrchardCore](https://github.com/OrchardCMS/OrchardCore) CMS and each time I'm running it in Debug mode using local IIS express hosting model. When this project was using .Net Core 3.0 I had quite fast boot time. Recently, just after whole project switched to .Net Core 3.1 this boot time is quite slow. 

From my initial investigation this slow down is related to dynamic symbol files being generated during startup and also when diffrent components are used for a first time. When I inspect loaded modules (VS: Debug -> Windows -> Modules) there is planty of strange symbol module names like: `nnguhn1d.4lr` or `zpjk1htx.zty` the only informations about those modules are: `Optymized: No`  `User Code: Yes` , generation timestamp and that symbol file is `dynamic`.

It might be related that I have .Net Core 3.1 SDK and when I was working on Orchard Core based on 3.0 such dynamic files were not generated nor loaded (so boot time was way faster) and now when everything was updated to 3.1 I have those dynamic symbols being generated.

Any ideas what is purpose of those dynamic symbol files? Why it was not an issue before when project was on .Net 3.0? Is it possible to find out more for which part of code such files are generated?

**Comment by jkotas** [comment]
These dynamic modules are generated by Reflection.Emit. You can set a breakpoint at https://github.com/dotnet/coreclr/blob/release/3.1/src/System.Private.CoreLib/src/System/Reflection/Emit/AssemblyBuilder.cs#L171 to see who is generating them.

**Comment by arkadiuszwojcik** [comment]
It helped, thank you! Closing issue.
