### ISSUE TITLE
AllConfigurations leg is broken in master for netcoreapp3.0

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#121]
Doing a .\build.cmd -allconfigurations build fails with RAR not being able to resolve assemblies for netcoreapp3.0. I checked the logs and binplacing isn't doing anything.

Strange enough, this doesn't happen in CI. Same behavior in CoreFx.

cc @ericstj @safern @Anipik

**Comment by ericstj** [comment]
I think this is caused by the case where the SDK doesn't need to reference any package.  Fix is https://github.com/dotnet/corefx/commit/1217bc3e0deab6a53d6bcf3b68ae1eb1ed43eb5e.  I'll port it
