### ISSUE TITLE
Targeting RyuJIT Unix/AMD64_ABI from Windows

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#1212]
Hello!

I'm using RyuJIT as an AOT compiler to generate Linux like code with AMD64 ABI and I had to previously patch CoreCLR JIT to have a workable codegen. While trying to rely solely on `linuxnonjit` target, I'm having an issue with this part of the code in compiler.cpp:

https://github.com/dotnet/runtime/blob/e5f3881d5dd1da61efc46f74b6abd783bcc0d0b4/src/coreclr/src/jit/compiler.cpp#L5258-L5262

Here, `info.compMatchedVM` is set to `false` and it is disabling many parts in the codegen. For example, it is disabling report of relocations:

https://github.com/dotnet/runtime/blob/e5f3881d5dd1da61efc46f74b6abd783bcc0d0b4/src/coreclr/src/jit/emit.cpp#L7454-L7457

Is it really correct to set `info.compMatchedVM` to `false` in case of AOT codegen? 
What do you suggest to fix this? I will happily make a PR!

**Comment by mikedn** [comment]
> Is it really correct to set info.compMatchedVM to false in case of AOT codegen?

Well, no. But the linuxnonjit thing is not intended for AOT, it's basically a hack used by the JIT devs to be able to run the Linux version of the JIT on Windows so they don't need to switch back and forth between OSes while working. As such it has its limitations, mostly arising from the fact that it is hosted by a VM that actually targets Windows.

You'd need a custom build of the JIT that acts like the real Linux JIT and not as an altjit.

**Comment by jkotas** [comment]
It should be possible to detect whether the JIT is running in the altjit hack mode or as actual cross compiler by comparing `getEEType()->osType` with the expected target OS.

Also:
- The VM side needs to set `osType` correctly. It sets to `CORINFO_WINNT` unconditionally that is wrong.
- `CORINFO_PAL` should be renamed to something more sensible, e.g. `CORINFO_UNIX`.

**Comment by xoofx** [comment]
> It should be possible to detect whether the JIT is running in the altjit hack mode or as actual cross compiler by comparing getEEType()->osType with the expected target OS.

Han, didn't pay attention about this osType, it could work indeed, I will try to come up with a PR after the new year.

**Comment by xoofx** [comment]
Closing as fixed by PR #1243
