### ISSUE TITLE
Function declaration causes completely unrelated code to perform much worse (2x slower)

### ISSUE THREAD

**Issue by Alan-FGR** [dotnet/runtime#12151]
Hello there. This is my first issue here, I looked for guidelines but I couldn't find anything regarding submitting issues, the closest I could find was the [Contributing Guide](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md) but it's not about how to file an issue, so I'll just use common sense here :P.

I was benchmarking some code when I suddenly noticed some really strange performance deviations in my results, I managed to pinpoint some of the causes, but what is really going on under the hood is still a mystery to me. In any case I managed to make a simplified repro that you can access [here](https://github.com/Alan-FGR/PrimitiveWrapperBenchmarks/blob/616b30be7a7972f9cc58a839c2a1e619961bcf41/PrimitiveWrapperBenchmarks/Program.cs). I couldn't simplify that code further but I believe it's simple enough. Note that the "Break" preprocessor variable simply guards the declaration of a function that does nothing, but for some weird reason that still causes the benchmark to run two times slower (in release builds) as you can see in the results:

without defining "Break":

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|  First | 28.68 ms | 0.5697 ms | 0.6096 ms |

[results](https://github.com/Alan-FGR/PrimitiveWrapperBenchmarks/tree/616b30be7a7972f9cc58a839c2a1e619961bcf41/PrimitiveWrapperBenchmarks/bin/Release/netcoreapp2.1/results)

with "Break" defined (and no attached debugger just in case although there's no difference):

| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|  First | 56.43 ms | 1.081 ms | 1.245 ms |

[results](https://github.com/Alan-FGR/PrimitiveWrapperBenchmarks/tree/616b30be7a7972f9cc58a839c2a1e619961bcf41/PrimitiveWrapperBenchmarks/bin/Release/netcoreapp2.1/results_broken_no_debugger_attached)

I've tried to investigate that issue further, but not only I failed to remove BenchmarkDotNet (BDN) and get the same results (by using a simple StopWatch), but I also couldn't pinpoint what difference in the IL or JIT could justify those results, both the IL and JIT for the "First" (boi I should've rename it) function are exactly the same ([link](https://gist.github.com/Alan-FGR/192c27433210a899e95fa6856f09b72c)) what blew my mind since the loop is inside that function. @saucecontrol suggested it could be alignment, I don't know whether such a difference in performance could happen due to nonalignment, but the code *is* aligned and all `call` instructions in `Main` are calling 8-aligned addresses (but they're calls to BDN).

My first intuition here is that something is wrong with BDN, but I very much doubt it's a bug in it since it's the most popular tool for microbenchmarking and that difference is just too large for something like that to go unnoticed this far. My guess is that there's a bug *somewhere* that BDN somehow triggers and it isn't trivial to reproduce externally. That *somewhere* is the real mystery though, since the native machine code is exactly the same I can only conclude that there's something really hairy going on here, like the code is being invalidated and re-jitted mid-loop or something, but I honestly don't think I'm minimally qualified to even make a reasonable guess here.

Thank you.

category:cq
theme:alignment
skill-level:expert
cost:large

**Comment by kunalspathak** [comment]
We already started aligning methods at 32B boundary in .NET 5 and implemented loop alignment in .NET 6. I am not able to reproduce the slowness.
