### ISSUE TITLE
How to get the "large object heap" size using .net core 3 running on Ubuntu 18.04

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#1217]
_From @ParisRoubaix on Sunday, December 29, 2019 11:47:24 PM_

How do I get the "large object heap" size? 

I'm using .net core 3 running on Ubuntu 18.04.

I posted this on StackOverflow and the only answer was to run dotnet-counters. How can I get this metric inside my running process?

Thanks.

_Copied from original issue: aspnet/AspNetCore#18059_

**Comment by pranavkm** [comment]
_From @blowdart on Monday, December 30, 2019 1:53:29 PM_

This isn't an asp.net question.

Please repost in https://github.com/dotnet/runtime as I don't have the ability to move it.

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/eventcounters.md maybe?

**Comment by jeffschwMSFT** [comment]
@cshung

**Comment by Gnbrkm41** [comment]
@ParisRoubaix, Do you still need assistance regarding your question? The event counter document above does describe runtime counters Incl. LOH size, but I'm happy to provide examples if you require.

**Comment by mangod9** [comment]
Closing since this has been answered. Please reopen if any further clarification is required.
