### ISSUE TITLE
Feature Request: Add `AddOrUpdate` to the Dictionary API

### ISSUE THREAD

**Issue by kgiszewski** [dotnet/runtime#1221]
There is a `Add(TKey key, TValue value)` method but it throws if using a key that is already in use. 

Adding `AddOrUpdate(TKey key, TValue value)` will simply use an existing key or add it.

Simply to be more clear and avoid boilerplate code and possibly an unnecessary lookup.

PR coming soon as it's fairly trivial.

**Comment by omariom** [comment]
Isn't it what the indexer does?

**Comment by kgiszewski** [comment]
Maybe, do you have a link reference?

**Comment by nathan-moore** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.item?view=netframework-4.8#remarks

**Comment by kgiszewski** [comment]
Ah yes, I suppose what I'm advocating is to avoid having to use that syntax. Instead the simple update would look something like this:

```
public static void AddOrUpdate<TKey, TValue>(this Dictionary<TKey, TValue> dictionary, TKey key, TValue value)
{
  dictionary[key] = value;
}

//usage
var dictionary = new Dictionary<string, string>();

dictionary.Add("myKey", "someValue");//succeeds
dictionary.Add("myKey", "someValue");//duplicate key exception

dictionary.AddOrUpdate("myKey", "someValue");//succeeds
dictionary.AddOrUpdate("myKey", "someValue2");//succeeds
```

_Note: that I'm using  it as an extension method at present._

I'll hold on the PR for now.

**Comment by TonyValenti** [comment]
I second the request for ````AddOrUpdate````.  The Indexer does the same thing but you can't pass indexers as Funcs and such.  I'd also request a ````GetOrAdd```` method similar to what ````ConcurrentDictiony```` has.

**Comment by jkotas** [comment]
Related discussion: https://github.com/dotnet/corefx/issues/31126

**Comment by fowl2** [comment]
To match the shape of `ConcurrentDictionary` the return type should be `TValue`.
