### ISSUE TITLE
"createdump" isn't in the Microsoft.NETCore.App package anymore

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#1229]
Starting about 5.0.0-alpha.1.19618.3 the Microsoft.NETCore.App package for Linux doesn't contain the  "createdump" program. It looks like it is built correctly, but the somewhere in the new repo infrastructure it got lost. 

This causing the diagnostics repo tests to fail on the latest 5.x runtime.

**Comment by hoyosjs** [comment]
Ack. Will take a look soon.

**Comment by mikem8361** [comment]
@hoyosjs have you had a chance to look at this? I can't figure out where in the runtime repo the packages are created.

**Comment by hoyosjs** [comment]
The issue in question is here https://github.com/dotnet/runtime/blob/680487ffa4d404034d8d67fb3721fc92db0ec422/src/installer/pkg/projects/netcoreapp/src/netcoreapp.depproj#L35. In general we don't add it to the PropertyGroup `CoreCLRFiles` so it ends up not only missing from the package, but also from all the native Linux installers. Will continue tomorrow.
