### ISSUE TITLE
Add testing for our WinRT-specific marshalers

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#12321]
We currently don't have any automated tests for our WinRT marshalling. Using the `System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeImportAttribute` pseduo-attribute, we can mark specific types within an assembly as Windows-Runtime types and make them use WinRT marshalling semantics without needing reg-free WinRT support. This pseudo-attribute is used within `System.Runtime.WindowsRuntime` in CoreFX to implement WinRT marshalling helpers. 

We should use this feature to add some automated testing for the WinRT marshalling within CoreCLR.

Marshalers to test:

- [x] `System.Nullable<T>` -> `Windows.Foundation.IReference<T>`
- [x] `System.Type` -> `Windows.UI.DirectUI.Xaml.TypeNameNative`
- [x] `System.Exception` -> `HRESULT`
- [x] `System.Collections.Generic.KeyValuePair<K,V>` -> `Windows.Foundation.Collections.IKeyValuePair<K,V>`
- [x] `System.Uri` -> `Windows.Foundation.Uri`
- [x] `System.ComponentModel.INotifyPropertyChanged` and family
- [x] `System.Collections.Specialized.INotifyCollectionChanged` and family
- [x] Hidden-length arrays (implicit length parameter in signature after the array)
- [ ] WinRT Delegates

**Comment by AaronRobinsonMSFT** [comment]
Closing since WinRT support was removed - see https://github.com/dotnet/runtime/pull/36715.
