### ISSUE TITLE
JIT naive assembly code generation

### ISSUE THREAD

**Issue by ebfortin** [dotnet/runtime#1233]
I'm starting to dig into how the JIT works and generate machine code. I have two situations that I find weird and would like to get more information on. For me it's a lack of optimization, and so a potential issue. But I may be wrong, I'm just starting. Please forgive me if it's not the place for that kind of discussion.

First is how constant are handled. Looking at the generated machine code I realized it looks like constants are put in a table and then the address is used. Like the snippet below:

    21: 			Assert.AreEqual(c, 4.0);
00007FFAF152980A C5 FB 10 0D 26 00 00 00 vmovsd      xmm1,qword ptr **[7FFAF1529838h]**  
00007FFAF1529812 C5 FB 10 45 40       vmovsd      xmm0,qword ptr [rbp+40h]  
00007FFAF1529817 E8 E4 E3 FF FF       call        00007FFAF1527C00 

I was expecting 4.0 to be put directly in xmm1, not going through an indirect memory fetch.

The other one is when returning from a méthode. It seems that no matter what, the return value is put in a temporary stack slot. Doesn't seem to be always necessary, as the code below show:

00007FFAF15297F8 FF 50 18             call        qword ptr [rax+18h]  
00007FFAF15297FB C5 FB 11 45 38       vmovsd      qword ptr [rbp+38h],xmm0  
00007FFAF1529800 C5 FB 10 4D 38       vmovsd      xmm1,qword ptr [rbp+38h]  
00007FFAF1529805 C5 FB 11 4D 40       vmovsd      qword ptr [rbp+40h],xmm1 

[rbp+38h] is the temp stack slot. [rbp+40h] is a local variable. There is no need to transit by [rbp+38h] to get the return value into xmm1. I understand we may need the temporary for later in the method. Although maybe not but let's say we need it. Yet xmm1 should get its value from xmm0 directly. No need for a stack access.

**Comment by jkotas** [comment]
You are looking at code compiled with optimizations off. The code compiled with optimizations on won't have the issues you have listed.

Note that .NET Core 3.0+ has tiered compilation enabled by default. It means that most methods are compiled with optimizations off initially. You may want to either disable tiered compilation by setting COMPlus_TieredCompilation=0 environment variable, or call the method in a loop and only look at the disassembly once the tiered compilation kicks in.

**Comment by ebfortin** [comment]
I was expecting something like that. I will do some experiments. However I still find it strange that a constant assignment have to go through a memory fetch even in the non-optimized path.

**Comment by mikedn** [comment]
>  I was expecting 4.0 to be put directly in xmm1, not going through an indirect memory fetch.

There era no SSE instructions that have immediate operands so it's typical to load floating point constants from memory.
