### ISSUE TITLE
StructLayout Pack is not honoured even for blittable types

### ISSUE THREAD

**Issue by ericwj** [dotnet/runtime#12342]
Similar but not equal to dotnet/runtime#10883, I find that `StructLayout.Pack` is ignored even in the most basic cases on .NET Core. I've ran into this on 3.0-preview3, but it does the same with the 2.2 SDK. Or it doesn't work as I expect it to.

```C#
[StructLayout(LayoutKind.Sequential, Pack = Pack)]
public struct Sequential
{
	public const int Pack = sizeof(ulong);
	public ushort W0;
	public ushort W1;
}

[Fact]
public unsafe void SequentialPack()
{
	var s = new Sequential {
		W0 = 0xffff,
		W1 = 0xeeee,
	};
	var w0 = &s.W0;
	var w1 = &s.W1;
	var ul0 = (ulong)w0;
	var ul1 = (ulong)w1;
	var expected = (ulong)Sequential.Pack;
	var actual = ul1 - ul0;

	Assert.Equal(expected, actual);
}
```
![image](https://user-images.githubusercontent.com/9473119/55010992-8640a780-4fe5-11e9-97c9-ffd02eb54195.png)

From that I understand that this struct is blittable so it should honour `StructLayout.Pack`. Is it that `ushort` fits in `Pack` 4 times so it will put them all together? Is there a way short of explicit layout to have this struct layout on top of other structs that I have with fields aligned at 8-byte boundaries?

**Comment by mangod9** [comment]
Hi @ericwj, Looks like the original issue is by design. Could you please open a new issue if there is something you feel needs to be investigated? Thx.

**Comment by ericwj** [comment]
Okay
