### ISSUE TITLE
Type.IsPublic returns wrong answer for pointer and byref types

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#12355]
Even though `int` is public, `int*` and `int&` aren't. Sample code below.

```cs
Console.WriteLine(typeof(int).MakePointerType().IsPublic); // prints 'False', expected 'True'
Console.WriteLine(typeof(int).MakeByRefType().IsPublic); // prints 'False', expected 'True'
```

Perhaps an oversight when copying the elemental Type's visibility attributes into the pointer / byref Type we manfacture behind the scenes?

(Found by @stephentoub)

**Comment by BartoszKlonowski** [comment]
@GrabYourPitchforks I would like to work on that, so please assign me to this issue.
CC: @steveharter @krwq

**Comment by krwq** [comment]
Hey @BartoszKlonowski are you still planning to work on this issue? In the meanwhile I'll move this issue to Future as it's not critical for 6.0

**Comment by BartoszKlonowski** [comment]
@krwq Yes, and sorry for the delay. I had it planned for this week, but it turned out to be busier then I thought.
It will for sure be delivered within next week.

**Comment by BartoszKlonowski** [comment]
@krwq Unfortunately I need to postpone my work on this as I currently don't have enough time to spend to deep into this, sorry for inconvenience.

**Comment by GrabYourPitchforks** [comment]
Thanks for the heads up @BartoszKlonowski! I think we all understand busy schedules interfering with these things. :)
