### ISSUE TITLE
runtest.py doesn't handle both ambient and test_env COMPlus variables

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#12364]
runtest.py will read the ambient set of `COMPlus` variables and unset them in the environment. If it is passed the `-test_env` switch, it will use that specified test environment script when invoking tests, by setting the `__TestEnv` variable to that. However, if runtest.py is not passed the `-test_env` switch, it will create a new test environment setting file, and use that for `__TestEnv`.

Note that if there are ambient `COMPlus` variables *and* a `-test_env` switch, the ambient ones will get lost: runtest.py will clear them, but will not "add them" to an environment script to pass on to the tests via the `__TestEnv` setting.

**Comment by AaronRobinsonMSFT** [comment]
The `runtest.py` script no longer exists.
