### ISSUE TITLE
ICommand interface: Missing nullable annotation

### ISSUE THREAD

**Issue by jbe2277** [dotnet/runtime#1237]
The [ICommand interface](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ObjectModel/src/System/Windows/Input/ICommand.cs) is missing a nullable annotation for

```C#
event EventHandler CanExecuteChanged;    // Actual
event EventHandler? CanExecuteChanged;   // Expected
```

All `EventHandlers` should define the nullable annotation.

**Comment by ehasis** [comment]
A quick search in the repo, I found a couple interfaces that have the same issue. Almost all of them are in the System.ComponentModel.*. In fact, not only in the interfaces, many classes of the same area are missing the nullabel annotation.

**Comment by ericstj** [comment]
@buyaa-n looks like feedback on correctness of the nullable annotations of System.ObjectModel
https://github.com/dotnet/corefx/pull/41808

**Comment by buyaa-n** [comment]
Thank you for reporting it @jbe2277, interested in contributing to the fix? 

> A quick search in the repo, I found a couple interfaces that have the same issue. Almost all of them are in the System.ComponentModel.*. In fact, not only in the interfaces, many classes of the same area are missing the nullabel annotation.

@ehasis could be more specific for where it is exactly missing annotation? Thank you!

**Comment by ehasis** [comment]
@buyaa-n for example, the events in the interfaces [IDesignerEventService](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/IDesignerEventService.cs), [IDesignerHost](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/IDesignerHost.cs), [ISelectionService](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/ISelectionService.cs). Of course, I don't know if this is intended/relevant or no, just wanted to note.

**Comment by buyaa-n** [comment]
> the events in the interfaces IDesignerEventService, IDesignerHost, ISelectionService. 

@ehasis those are interfaces from `System.ComponentModel.TypeConverter` which we haven't annotated yet. I just checked ref assemblies of `System.ComponentModel`, seems only that `event EventHandler CanExecuteChanged;` event is missing `?`

> Edit 1: I would like to add that if is just to add the "?" in front of the events, I would love to contribute doing that.
> Edit 2: Or anything else, if you could guide-me :)

You are welcome to contribute, the `?` need to be added to the source code and ref assembly, and also if there are any nullability warnings are introduced because of that change those errors need to be fixed.

**Comment by danmosemsft** [comment]
@buyaa-n I'm moving to Future as it seems this would not be breaking to fix later. Please reactivate if I'm incorrect.

**Comment by ehasis** [comment]
Yeah, I was working on it, but stopped to do something else. There is alot of code, I'll split and do in parts after finish other issue.

**Comment by buyaa-n** [comment]
@danmosemsft it is for 5.0, as nullability bug, i will raise PR soon

@ehasis this issue apply only for the event mentioned in the description `event EventHandler CanExecuteChanged;`, no more change needed
