### ISSUE TITLE
[x64/windows]Tests failed with System.TimeoutException

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#12389]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs0x1000/704/

**Failed tests:**
System.Net.Http.Functional.Tests.PlatformHandler_IdnaProtocolTests.InternationalUrl_UsesIdnaEncoding_Success(hostname: \"á.com\")
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http11.GetAsync_ReceiveMultipleSetCookieHeaders_CookieAdded
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds
System.Net.Http.Functional.Tests.PlatformHandler_HttpProtocolTests_Dribble.GetAsync_RequestVersion10_Success
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.SetProtocols_AfterRequest_ThrowsException
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler.GetAsync_TrailingHeaders_Ignored(includeTrailerHeader: False)
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.SetDelegate_ConnectionSucceeds(acceptedProtocol: Tls, requestOnlyThisProtocol: False)
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpProtocolTests.GetAsync_ExpectedStatusCodeAndReason_Success(statusLine: \"HTTP/1.1 200 OK\", expectedStatusCode: 200, expectedReason: \"OK\")
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.HttpClientHandler_MultipleAuthenticateHeaders_WithSameAuth_Succeeds(authenticateHeader: \"WWW-Authenticate: Basic realm=\\\"hello1\\\"\\r\\nWWW-Au\"...)
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: True, mode: Token)

**Failed log:**
```
System.Net.Http.Functional.Tests.PlatformHandler_IdnaProtocolTests.InternationalUrl_UsesIdnaEncoding_Success(hostname: "�.com") [FAIL]
        System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms
        Stack Trace:
             at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
          D:\j\workspace\x64_checked_w---5e38e6b2\_\fx\src\System.Net.Http\tests\FunctionalTests\IdnaProtocolTests.cs(43,0): at System.Net.Http.Functional.Tests.IdnaProtocolTests.<>c__DisplayClass2_0.<<InternationalUrl_UsesIdnaEncoding_Success>b__0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          D:\j\workspace\x64_checked_w---5e38e6b2\_\fx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
          D:\j\workspace\x64_checked_w---5e38e6b2\_\fx\src\System.Net.Http\tests\FunctionalTests\IdnaProtocolTests.cs(28,0): at System.Net.Http.Functional.Tests.IdnaProtocolTests.InternationalUrl_UsesIdnaEncoding_Success(String hostname)
          --- End of stack trace from previous location where exception was thrown ---
```

**Comment by jashook** [comment]
Stale
