### ISSUE TITLE
Unstable duration of tests running in ADO

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#12392]
We hit timeouts with GCStress on tests like `baseservices/threading/regressions/beta2/437017` or  `JIT/HardwareIntrinsics/X86/Avx2/Avx2_ro` from time to time. The timeout for GCStress is set to 1 hour per test. Kusto results show that sometimes these tests execution takes 20 minutes, sometimes 40, some fail with 1 hour timeout.

Duratation for beta2_437044_437044_sh Ubuntu.1604 gcstress0x3:
```
807.2075189
3600.1316769
1395.8818172
3558.8521005
794.5199284
778.0971284
1800.0648784
984.1676776
1586.0055026
1431.6268684
1117.4029117
```

The similar picture is for other tests, for example `beta2_437044` on `x64 WIndows.10 minopts`:
```
Duration
10.8403088
9.7603915
4.0987427
23.8235332
10.2850002
7.8984973
23.5484026
29.2190543
4.540873
4.8469147
8.6422568
7.5901681
15.2560697
35.0298974
7.9805417
30.2128801
6.3597494
12.1808179
9.9471955
10.4480389
7.0961536
24.1057954
12.214705
3.0317356
31.2346013
7.5773318
8.5577859
17.8248298
6.1346953
```
So max is 35, min is 3, that doesn't look right.

(queue for this:
```
database('engineeringdata').TestResults
| where Method contains 'beta2_437044' 
| join kind=inner (database('engineeringdata').Jobs) on JobId
| where QueueName contains "Windows.10" and Properties contains "minopts" and Properties contains "x64"
```
 `)

We have seen a similar problem with Jenkins but it was because we used  XUnit `ParallelRun=all` and it was creating more threads than CPU cores and it was fixed by changing it to XUnit `ParallelRun=collections` (#22746). With ADO our understanding was that we run only one assembly on one machine so there were no difference between `all` and `collections`.

**Comment by xiangzhai** [comment]
:mips-interest

**Comment by sandreenko** [comment]
I am going to reenable the disabled tests and see if the issue still reproduces. There were many infrastructure changes since it was open, so it could have been fixed already.

In the past, I was trying to make a change to allocate 2 cores per running test in helix but it did not work well (https://github.com/dotnet/coreclr/pull/24749/files). On some machines I was getting an incorrect number of cores (like 2 cores VM on 64 cores physical arm machine was giving me 32, instead of 1), on others, it still was hitting timeouts, but less frequently, because the tests that hit them did not allocate 2 cores, they were allocating dozen each. The big downside of that change was that on average a test run was taking longer (like ~20% slower).

**Comment by sandreenko** [comment]
As I see from the recent GCStress runs it is still an issue: JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_r/AdvSimd_r.sh
and similar that were not disabled are still failing with timeouts ([example](https://dev.azure.com/dnceng/public/_build/results?buildId=665656&view=ms.vss-test-web.build-test-results-tab&runId=20632554&resultId=109147&paneView=debug))

**Comment by echesakovMSFT** [comment]
> As I see from the recent GCStress runs it is still an issue: JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_r/AdvSimd_r.sh

@sandreenko I am working on splitting those up #37282

**Comment by sandreenko** [comment]
> @sandreenko I am working on splitting those up #37282

Could you please try to reenabled tests from https://github.com/dotnet/runtime/pull/37530/files and close this issue in your PR?

**Comment by echesakovMSFT** [comment]
> Could you please try to reenabled tests from https://github.com/dotnet/runtime/pull/37530/files and close this issue in your PR?

Sure

**Comment by jashook** [comment]
Addressed
