### ISSUE TITLE
ILDASM - wrong endianness

### ISSUE THREAD

**Issue by eli-fin** [dotnet/runtime#12446]
If you call `ildasm /bytes` on an assembly which contains a `brtrue` opcode, it will print the jump target bytes incorrectly (in big endian, rather than little).

It arrives at the code [here](https://github.com/dotnet/coreclr/blob/6a6b5b358034ec08e5f2d83a6d561813beb32019/src/ildasm/dis.cpp#L1646), (because `brtrue` is an `InlineBrTarget`, as defined in [this](https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/ildasm/dasmenum.hpp#L21) macro array, based on [this](https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/inc/opcode.def#L96)).

The `offset` and therefore the `dest` label are calculated correctly, however the `if(g_fShowBytes)` is adding it to `szptr` in the wrong byte order, making `00000050` print as `50000000`.
This seems to be repeated several times in the file.
(it's correct [here](https://github.com/dotnet/coreclr/blob/6a6b5b358034ec08e5f2d83a6d561813beb32019/src/ildasm/dis.cpp#L1756), for example)
Is it actually ever necessary for it to be printed in reverse?

**Comment by briansull** [comment]
I will investigate this

**Comment by danmosemsft** [comment]
What does ILASM expect?

**Comment by briansull** [comment]
These are comments printed by ILDASM when the /bytes option is used.
So no impact to ILASM

**Comment by briansull** [comment]
Fixed by #42848
