### ISSUE TITLE
Performance impact of using Range over span

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/runtime#1244]
I wrote a simple benchmark to compare a copy of a sliced array on another
```
[SimpleJob(RuntimeMoniker.NetCoreApp31)]
[RankColumn, MarkdownExporterAttribute.GitHub, MemoryDiagnoser]
public class RangeCheck {

	[GlobalSetup]
	public void Setup() {
	}


	[Benchmark]
	public void ArrayRange() {
		byte[] arr = new byte[10];
		Span<byte> span1 = arr;

		byte[] arr2 = new byte[20];

		arr2[..10].CopyTo(span1);
	}

	[Benchmark]
	public void AsSpanRange() {
		byte[] arr = new byte[10];
		Span<byte> span1 = arr;

		byte[] arr2 = new byte[20];

		arr2.AsSpan(..10).CopyTo(span1);
	}

	[Benchmark]
	public void ExplicitSlice() {
		byte[] arr = new byte[10];
		Span<byte> span1 = arr;

		byte[] arr2 = new byte[20];
		Span<byte> span2 = new Span<byte>(arr2, 0, 10);

		span2.CopyTo(span1);
	}
}
```

this is the result
![image](https://user-images.githubusercontent.com/5107375/71667393-36a5be00-2d65-11ea-8691-f518c515b138.png)

Couldn't we have IL generate a smarter output for the `AsSpanRange` benchmark, converting the Range `..10` call into an explicit Slice, or something equivalent?

Would be nice to have a range syntax in place of an explicit slice call

**Comment by EgorBo** [comment]
Not sure Roslyn should do that, but indeed probably makes sense to optimize `Range` apis where constants are used (especially things like `0..10` without `^`)

**Comment by stephentoub** [comment]
> Couldn't we have IL generate a smarter output for the AsSpanRange benchmark, converting the Range ..10 call into an explicit Slice, or something equivalent?

C# only special-cases the range syntax to be usable for indexer-based slicing and not for arbitrary methods like AsSpan.  As such, it was decided to add a Range-based overload of AsSpan.  https://github.com/dotnet/coreclr/issues/22079 covers improving optimizations in the JIT around Range.  Any further customization of the IL that's generated by the C# compiler would be better requested in the dotnet/csharplang or dotnet/roslyn repos.

**Comment by MithrilMan** [comment]
Thanks for the reply

I've updated my benchmark to include your suggestions

```
[SimpleJob(RuntimeMoniker.NetCoreApp31)]
   [RankColumn, MarkdownExporterAttribute.GitHub, MemoryDiagnoser]
   public class RangeCheck
   {

      [GlobalSetup]
      public void Setup()
      {
      }


      [Benchmark]
      public void ArrayRange()
      {
         byte[] arr = new byte[10];
         Span<byte> span1 = arr;

         byte[] arr2 = new byte[20];

         arr2[..10].CopyTo(span1);
      }

      [Benchmark]
      public void AsSpanRange()
      {
         byte[] arr = new byte[10];
         Span<byte> span1 = arr;

         byte[] arr2 = new byte[20];

         arr2.AsSpan(..10).CopyTo(span1);
      }

      [Benchmark]
      public void AsSpanRange2()
      {
         byte[] arr = new byte[10];
         Span<byte> span1 = arr;

         byte[] arr2 = new byte[20];

         arr2.AsSpan()[..10].CopyTo(span1);
      }

      [Benchmark]
      public void AsSpanRange3()
      {
         byte[] arr = new byte[10];
         Span<byte> span1 = arr;

         byte[] arr2 = new byte[20];

         ((Span<byte>)arr2)[..10].CopyTo(span1);
      }

      [Benchmark]
      public void ExplicitSlice()
      {
         byte[] arr = new byte[10];
         Span<byte> span1 = arr;

         byte[] arr2 = new byte[20];
         Span<byte> span2 = new Span<byte>(arr2, 0, 10);

         span2.CopyTo(span1);
      }
   }
```

result
![image](https://user-images.githubusercontent.com/5107375/71907745-f1223000-316c-11ea-866f-0be82bf7b026.png)

they are quite close to the explicit Span and `arr2.AsSpan()[..10]` seems a good alternative to explicit slicing
thanks
