### ISSUE TITLE
dev.azure "Tests" view is only available for signed users.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#1246]
Open https://dev.azure.com/dnceng/public/_build/results?buildId=469032&view=results
when you are signed with your Microsoft account, you will see:
![image](https://user-images.githubusercontent.com/22642771/71679902-883a5280-2d3d-11ea-87ca-59c51f3f3a16.png)

but if you are not signed you won't see "Tests":
![image](https://user-images.githubusercontent.com/22642771/71679917-96886e80-2d3d-11ea-87f8-ff7008eae8cd.png)

it is not a desired behavior, because we want external contributors to be able to analyze failures in their PRs.

In the coreclr repo is was working fine, open https://dev.azure.com/dnceng/public/_build/results?buildId=425677&view=ms.vss-test-web.build-test-results-tab without signing in and you will see "Tests" there.

**Comment by sandreenko** [comment]
PTAL @@dotnet/runtime-infrastructure

**Comment by jaredpar** [comment]
Thanks for catching this. Unfortunately I don't believe this is anything that we can control. Rather it looks like a regression in AzDO pipelines. Let me escalate.

**Comment by jaredpar** [comment]
AzDO team acknowledged the regression here and is looking into it.

**Comment by puagarwa** [comment]
I tried repro it but unable to see test tab even when I am login through my msft login, infect I also checked test run summary result for this [api ](https://vstmr.dev.azure.com/dnceng/public/_apis/testresults/resultsummarybybuild?buildId=470764) and there is no run/results associated and hence test tab shouldn't be visible. so, basically it seems that there is some task failure which lead to no test data being published. I do see some task failure in pipeline so I would suggest you to take a look at test task and see if test publishing is successful or not. 
I also found some build instance of same pipeline where it was success and I could see test tab from both msft login and anonymous here is the link, please confirm if you see the same.
https://dev.azure.com/dnceng/public/_build/results?buildId=451456&view=results

**Comment by markwilkie** [comment]
As I commented in the ICM ticket, I can see the test tab just fine, along with the results.  https://dev.azure.com/dnceng/public/_build/results?buildId=451456&view=ms.vss-test-web.build-test-results-tab

**Comment by puagarwa** [comment]
@markwilkie in that case, can you please affected customer to try the same build and confirm they are also able to verify it. basically, the [build ](https://dev.azure.com/dnceng/public/_build/results?buildId=469032&view=results) which customer has provided doesn't have any test in it hence test tab will not be present, if customer has any example of build which has test and still not able to see test tab, I will be happy to assist.

**Comment by sandreenko** [comment]
Thanks, as I see now "Tests" for unsigned users is only invisible when there were no tests run, a signed user in this case sees 
"No test runs are available for this build.".

The issue could be closed.

**Comment by markwilkie** [comment]
Thanks @puagarwa and @sandreenko.  

cc/ @MattGal
