### ISSUE TITLE
Separate Test Build & Test Run in Azure Pipelines

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#12475]
CI often requires rerunning failed legs.
Building tests is time consuming.
If we separated test build from test run, 

- it would be simpler to see that the test build failed.
- it could be more efficient to rerun the failed test run in helix.

/cc @RussKeldorph

**Comment by trylek** [comment]
I fixed this issue by the end of 2019 before the .NET repo consolidation.
