### ISSUE TITLE
Centralize and improve Windows prereq checks

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#1251]
I got the missing DIA SDK error when first building on my laptop just now:
```
Error: DIA SDK is missing at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\DIA SDK". This is due to a bug in the Visual Studio installer. It does not install DIA SDK at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\" but rather at the install location of previous Visual Studio version. The workaround is to copy the DIA SDK folder from the Visual Studio install location of the previous version to "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\" and then build.
Visual Studio Express does not include the DIA SDK. You need Visual Studio 2017 or 2019 (Community is free).
```

In the current machine, I have 15.9.11 Preview 1 and 16.5.0 Preview 2. I am building in the VS 2019 prompt, where `VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\`. However the single DIA SDK folder is under the VS 2017 prompt's `VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise`. 

I copied it from there to solve the problem, so the message may be fully accurate. However, I have seen this prompt at least 3 years ago, so it is not clear that this will solve itself. Can we look in more places for it, to remove this stumbling block when building the repo the first time?

Perhaps it could look under `C:\Program Files (x86)\Microsoft Visual Studio` for `DIA SDK` if it can't find one under VSINSTALLDIR?

**Comment by danmosemsft** [comment]
Hmm, this was likely because I did not have the C++ desktop workload installed for VS2019, but I did for VS2017. After xcopying the folder, I got
```
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
The system cannot find the path specified.
BUILD: Regenerating the Visual Studio solution
CMake Error at CMakeLists.txt:6 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.
```

Perhaps the takeaway here is could we display a message suggesting the C++ desktop development pack is missing, rather than the above messages.

**Comment by BruceForstall** [comment]
Can this really be a bug as the message states? ("This is due to a bug in the Visual Studio installer.") That message was added years ago.

I like the idea of being more specific about checking that the required prereqs are installed; we should verify what we can about the pre-requisites documented here: https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md. E.g., if you ask for an arm64 Windows build, check that the arm64 compilers are installed, and give a better error message if they aren't.

**Comment by danmosemsft** [comment]
Copied from my comment in the PR:

Incidentally, we are happily building in a VS2017 prompt, although we claim that VS2019 is required. (Note, the core-setup repo did not require VS2019 before)

src\installer\corehost\build.cmd
src\coreclr\setup_vs_tools.cmd
src\libraries\Native\build-native.cmd

all use vswhere and need updating to require VS2019.

Also it looks like eng\common\tools.ps1 can help verify that VS2019 is installed, if we set tools.vs.version in eng\global.json. It can also verify the specific workloads are present, see "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -? and tools.ps1.

**Comment by danmosemsft** [comment]
Summarizing comments on the PR and above

1. Centralize prerequisite checks so they are done in one place and at the start of the build.
1. On Windows, verify VS2019 command prompt, and all the necessary workloads
1. Exception: only require DIA SDK for the CLR product build (for dactablegen tool)

It looks like a mechanism might already exist for 1 and 2, based on the JSON output of vswhere.exe
https://github.com/dotnet/runtime/blob/5e2c61bc2a0a5923bd3564b3d646d9bf2dbe0866/eng/common/tools.ps1#L379-L392

**Comment by danmosemsft** [comment]
Ideally what we do here would not further cement our build dependency on VS (https://github.com/dotnet/arcade/issues/64). The prereq's should be for what we need.
