### ISSUE TITLE
The build step which produces the apt linux packages is running on EOL distro version.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#1252]
The `Package Runtime Deps, Runtime, Framework Packs installers - ubuntu.14.04` build step which produces the apt linux packages is running on a EOL distro version.  Specifically it appears to be using [`mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-14.04-debpkg-e5cf912-20175003025046`](https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/installer/installer-matrix.yml#L87).  This build step should be updated to utilize a supported version of Ubuntu.

**Comment by MichaelSimons** [comment]
cc @dagood

**Comment by NikolaMilosavljevic** [comment]
We should the latest LTS supported distro where debpkg works - create 20.04 if not yet available.

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic do we really need this for 5.0? Just discussed this in the infra meeting and we believe this isn't interfering with the 5.0 release.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic do we really need this for 5.0? Just discussed this in the infra meeting and we believe this isn't interfering with the 5.0 release.

I'm fine if we fix it during 6.0 and backport to 5.0 servicing. The sooner the better. I have actually found some blockers in implementation, so this will certainly take more time to get right.

**Comment by NikolaMilosavljevic** [comment]
I tried to use `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-debpkg-cfdd435-20200327183254` and ran into issues with build.

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic are you still looking into this? Unsure if we should keep it for 6.0 or move it into 7.0.

**Comment by NikolaMilosavljevic** [comment]
I'd keep this in 6.0 for now.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Please use the latest available LTS, i.e. 20.04.

**Comment by NikolaMilosavljevic** [comment]
@jamshedd do we have an issue tracking policy regarding build machine OS versions?

**Comment by MichaelSimons** [comment]
[Triage] Pushing to 7 because we don't have the bandwidth to fix this nor does it meet the bar.

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic can you follow up on this issue?

**Comment by NikolaMilosavljevic** [comment]
Closing - fixed with https://github.com/dotnet/runtime/commit/6bc1c947068089879d448a67aeedd59caaa9d601
