### ISSUE TITLE
Can I register a callback to be called before or after GC?

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#12527]
@ygc369 [Commented on another thread](https://github.com/dotnet/coreclr/pull/22866#issuecomment-484040178), but it is a new issue so moving it here:

>  @Maoni0
Can I register a callback to be called before or after GC? Just in my program, not in profile.

And the answer: You might be interested in [this technique](https://blogs.msdn.microsoft.com/maoni/2019/04/08/a-portable-way-to-get-gc-events-in-process-and-no-admin-privilege-with-10-lines-of-code-and-ability-to-dynamically-enable-disable-events/).

**Comment by mangod9** [comment]
@ygc369 the original question seems to have been answered. Please reopen (or create a new issue) if any further clarification is required. Thx.
