### ISSUE TITLE
Add Profiler API : GetObjectReferences

### ISSUE THREAD

**Issue by mjsabby** [dotnet/runtime#12548]
The Profiler API today has [ICorProfilerCallback::ObjectReferences](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-objectreferences-method) which is called after a GC is completed. This is called for remaining object in the heap.

For large heaps and/or heaps with moderate survival rate this can be prohibitively expensive to enable in a production environment.

In conjuction with https://github.com/dotnet/coreclr/issues/24132, this API can be used to selectively traverse object graphs. In fact, with this API you could implement the aforementioned expensive callback that already exists in the profiling API. So this customization is a welcome addition to the Profiler API.

The signature would be:

`GetObjectReferences(ObjectID objectId, ULONG32 cNumReferences, ULONG32 *pcNumReferences, ObjectID references[])`

Passing 0 for `cNumReferences` will fill do a traversal for this object and fill up `pcNumReferences`. A subsequent call with the `cNumReferences` parameter set to the value returned in the first call (`pcNumReferences`) will expect an appropriately allocated array of `ObjectID`s to fill the data in.

A point of discussion could be if field offsets should be included. I'm of the opinion they are superflous for most object graph traversals.

**Comment by davmason** [comment]
@mjsabby have you worked on docs at all?

**Comment by mikelle-rogers** [comment]
Already documented.
