### ISSUE TITLE
[Linux/ARM] Segmentation faults when running precompiled JIT code on ARM (Tizen, 32-bit)

### ISSUE THREAD

**Issue by kfrolov** [dotnet/runtime#12552]
Recently we have discovered new issue which prevents debugging of precompiled application and libraries. Libraries and applications can be precompiled by "crossgen" application. In case when we will try to debug application containing precompiled JIT code, incorrect CoreCLR  behavior will lead do segmentation fault exception and abnormal program termination.

The issue is discovered and reproduced with CoreCLR release 2.1.4 on ARM (32 bit) CPU, on Linux (Tizen). As we know, issue still exists in "master" branch of CoreCLR and related to implementation of "single stepping" routine for 32-bit ARM CPUs in CoreCLR's code. 

In short, the problem might be reproduced in the following way:

* start debugging the application with "netcoredbg" debugger (here and later I assume debugging of managed code only);
* set breakpoint to line of the program;
* when debugger stops on the breakpoint, apply "Step" function -- at this moment process, which runs managed application, crashed due to SIGSEGV signal.

I will provide full description of steps required to reproduce the issue in the separate message

This issue was caused by pull request dotnet/coreclr#11366, which adds some sort of optimization of JIT code, which uses PC-relative addresing to avoid relocations in loadable code segments, and to allow to share these code segments among multiple applications.

**More detailed description**

The root cause of the issue, is how CoreCLR performing "single step" operation during debugging: it tries to perform single stepping at machine instruction level until PC (program counter) not reaches next line of code, or not reaches some other function.  In comparison with CPUs based on x86 architecture (which have "Trap Flag" in flags register), on ARM where is no CPU support for single stepping on ARM CPU. Moreover, Linux removed support of PTRACE_SINGLESTEP function in ptrace(2) system call (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=425fc47adb5bb69f76285be77a09a3341a30799e). So only solution to execute every single machine instruction step by step on ARM CPU is to perform this task manually by one of the following methods:

1. completely emulate all CPU instructions -- this solution might be impractical because of high complexity;
2. or emulate only those instruction, which can't be executed as described below, for example jumps can't be executed directly (because you can't stop  CPU after such instruction in easy way), and run other instructions as is.

Currently CoreCLR implies second option. Most of CPU instructions can be executed as is. But few instruction classes require emulation. Practically this is those instructions, which reference PC (R15) register: because such instruction might perform jump (change PC value), or because this instruction might reference PC to implement PC-relative addressing.

Why latter is important: to execute every single instruction it is placed in thread specific local buffer, then after the instruction special "breakpoint" opcode is placed, and then code executed from this buffer. So, when every single instruction is executed, it is executed with other PC value, than expected by the program. This is why PC-relative addressing might cause problems.

Reason of executing every single instruction from thread specific local buffer is that the program is multithreaded and we can't just replace next instruction in user's code to breakpoint instruction: other threads at same time might execute same piece of code.

This issue exist because CoreCLR doesn't emulate some instructions correctly. Especially it doesn't emulate instruction "ADD Rd, PC" at all and this is root cause of the bug.

**Possible solutions**

We can just add emulation of such instruction and the bug will go away.

But during examination of this issue we have discovered, that CoreCLR currently can emulate only _limited set of instructions_ (see src/vm/arm/armsinglestepper.cpp, ArmSingleStepper::TryEmulate function).  But at same time, CPU can execute much more wider set of instructions which can change or read PC (R15) register value. So, by adding emulation of "ADD Rd, PC" instruction we not solve the problem completely, but just push the problem to the future.  Which problems we see:

1. currently code emulates _very limited set_ of "problematic" instructions and in limited way (it not emulates all "conditional" instructions,  not assigns status register flags based on performed arithmetic operations);
2. we have suspicion, that this code isn't well tested: case, in which it fails, is quite common;
3. code full of "magic numbers", which we can't check easily and in absence of tests this lookс risky: where is guarantee, that it not fail on same single instruction in future?

So, as I think, better solution might be one of the following:

1. modify code to support more complete instructions set and provide complex set of tests, practically this solution complicated by existing structure of the code (we don't want to emulate arithmetic instructions, because this is very complex task and might introduce lot of mistakes -- see below);
2. or rewrite significant part of ArmSingleStepper class at all with the following goals: avoid magic numbers in code (you should have possibility to check code correctness by comparing command descriptions with documentation published by ARM without use of calculations, just by comparing visually), allow to execute wider instruction set.

Regarding to second option, I have proposition, which allows to avoid emulation of almost all commands, with exception of block load commands (like LDM) and jump commands (B, BLX, BX, TBH, TBB, etc...) 

This proposition is follows: instead writing bunch of code for emulation each arithmetic command (because ARM allows to use PC register in arithmetic commands), perform register's substitution in command and use some other register in place of PC, which will contain right value. When executing single command, with exception of block load commands (LDM, STM), not all registers used simultaneously, so we can substitute PC with some "unused" register (of course, we should temporary save it's value). In that way we can just execute modified command, but not emulate it (and again, we should modify context before and after execution of the command). As I think, this approach significantly simplifies the task and reduces risk of making mistake.

**Which commands we should emulate.**

Later I will refer document "ARM DDI 0406C.c" (ID051414), which available by this link: https://static.docs.arm.com/ddi0406/c/DDI0406C_C_arm_architecture_reference_manual.pdf

On page 2487, in section D9.4, you can find, that ARM deprecates using PC in every command, where it is possible, and limits set of the commands, which might reference PC register, to the following:

* load instructions (like LD, MOV), including block load (LDM);
* limited set of arithmetic instructions: ADD, SUB, ADR (including conditional ones);
* all jump instructions (including BX<cond> PC).

So practically we should implement execution of load commands and arithmetic instructions, and implement emulation of block load and jump instructions. This command set not so small as it seems, but much smaller, than whole commands set, which CPU potentially can execute, and which references PC register. As I know, currently clang or gcc will not use "deprecated" instructions, and I assume, that CoreCLR's JIT compiler not use such instructions too.

**Questions**

I want to ask few questions related to this issue:

1. Can you list a sources, from which the code, which might be "single stepped" by CoreCLR, can come?  Currently we know, what JIT code might be generated by CoreCLR itself or created by "crossgen" program and when loaded from a file. So in both cases we can deal with code produced by CoreCLR's JIT compiler.  But where is the possibility, that code might come from other source, this is might be some sort of "native" code created by other compilers, by hand, etc...?   Where is possibility, what CoreCLR might try to "step into" native code (some native library, etc...) ?

2. Do you have any tests for single stepping or can suggest us how we can perform testing the fact, what single stepping works correctly?

3. Which way, by your opinion, we should use to fix this issue?

**Comment by tommcdon** [comment]
@kfrolov it looks like this issue was fixed on dotnet/coreclr#24271, OK to close?

**Comment by tommcdon** [comment]
Closing due to no response
