### ISSUE TITLE
Improve error messages when failing to load IJW assemblies

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#12576]
If we fail to load an IJW assembly as a managed entry-point, we always throw a `BadImageFormatException`, even if the error has to do with something else such as a missing native dependency. Because of where the throw is in the assembly loading code, we catch and re-throw the HRESULT a few times, but we don't pass along any exception message. If we take a look at improving our assembly loading errors, we should try to improve our error messages for the loads.

The throw is at : https://github.com/dotnet/coreclr/blob/edfd95518ace718388d4ef2396b4233635b2d26b/src/vm/peimage.cpp#L1130-L1131

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/runtime/pull/45997.
