### ISSUE TITLE
JIT should be able to optimize `typeof(T) == obj.GetType()`

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#1258]
Once https://github.com/dotnet/runtime/pull/1201 is merged, any type that can have a heap instance, including arrays, will have the TypeHandle -- MethodTable equivalence.

As such, `typeof(T) == obj.GetType()` should be always optimizable into a handle/methodtable compare.

**Comment by VSadov** [comment]
cc: @davidwrighton

**Comment by BruceForstall** [comment]
@AndyAyersMS

**Comment by VSadov** [comment]
Just to be sure - the optimization works for nongeneric cases or when T is a value type. Typehandle is basically a constant in such cases.

It could work for reference type T as well. TypeHandle would not be a constant, but should be  equatable with what `GetType` returns.

**Comment by omariom** [comment]
> Once #1201 is merged, reference types, including arrays, will have the TypeHandle -- MethodTable equivalence.

Each array type will have its own MethodTable?

**Comment by VSadov** [comment]
> Each array type will have its own MethodTable?

They already do. 
https://github.com/dotnet/coreclr/pull/27571 fixed the last few cases where MTs were shared

**Comment by omariom** [comment]
Then may be [this optimization](https://github.com/dotnet/coreclr/issues/5329) can be implemented more easily now?

**Comment by VSadov** [comment]
> Then may be this optimization can be implemented more easily now?

Maybe. 
Note - things like `typeof(int*)` can still produce a handle with a shared method table.

**Comment by omariom** [comment]
I think for these two cases it is irrelevant:
```C#
[obj.]GetType().TypeHandle.Value
typeof(T).TypeHandle.Value
```

**Comment by omariom** [comment]
And btw array types now can be treated as [sealed classes](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABARiQAJiAmCgYQoFgAoAbxYs6vIuAggA2FAIJQo2AJ4AKCMABWMMBgqy5ASgoBeAHwr5AOgDiMDABUJABxhSNmzRQyWYEAGZSAlgDsMAbQC6agDcHFwhnGSUfIIiYpLUMvKKyqq2uqoU7rgZ3v7BzFxM+VwR2b5+MeISAMwJCkp66lpp8hR4pblhhQUlUUIAyjDYAjAAJrVJDakNRibmVjZa9o5WrlJkAAxBnZ09/P2DwyPxqhMpTQ0ZWRt5BTs8GxQDQ6M1J/VnOhdt1ywAvkA==)

**Comment by AndyAyersMS** [comment]
Just to verify, we're now saying, given
```C#
public static bool Is(object o)
{
   return typeof(T) == o.GetType();
}
```
which currently produces the following, because
`canInlineTypeCheckWithObjectVTable` return false for `__Canon`:
```asm
; Assembly listing for method Is(System.Object):bool
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 TypeCtx      [V00,T00] (  4,  4   )    long  ->  rcx
;  V01 arg0         [V01,T01] (  3,  3   )     ref  ->  rsi         class-hnd
;  V02 OutArgs      [V02    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 40

G_M62793_IG01:
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40
       48894C2420           mov      qword ptr [rsp+20H], rcx
       488BF2               mov      rsi, rdx

G_M62793_IG02:
       488B4938             mov      rcx, qword ptr [rcx+56]
       488B09               mov      rcx, qword ptr [rcx]
       E8E61F445F           call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       488BF8               mov      rdi, rax
       488BCE               mov      rcx, rsi
       E83B81B15F           call     System.Object:GetType():System.Type:this
       483BF8               cmp      rdi, rax
       0F94C0               sete     al
       0FB6C0               movzx    rax, al

G_M62793_IG03:
       4883C428             add      rsp, 40
       5E                   pop      rsi
       5F                   pop      rdi
       C3                   ret
```
can now be done via vtable comparsion, and produce something like:
```asm
; Assembly listing for method Is(System.Object):bool
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 TypeCtx      [V00,T00] (  4,  4   )    long  ->  rcx
;  V01 arg0         [V01,T01] (  3,  3   )     ref  ->  rdx         class-hnd
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 8

G_M12531_IG01:
       50                   push     rax
       48890C24             mov      qword ptr [rsp], rcx

G_M12531_IG02:
       488B02               mov      rax, qword ptr [rdx]
       488B5138             mov      rdx, qword ptr [rcx+56]
       488B12               mov      rdx, qword ptr [rdx]
       483B02               cmp      rax, qword ptr [rdx]
       0F94C0               sete     al
       0FB6C0               movzx    rax, al

G_M12531_IG03:
       4883C408             add      rsp, 8
       C3                   ret
```
Looks like maybe we should keep the vestigial `canInlineTypeCheck` callback from jit to runtime, since it looks like (?) maybe crossgen2 will vary behavior here in the future..

**Comment by jkotas** [comment]
> can now be done via vtable comparsion, and produce something like:

Yep.

> like (?) maybe crossgen2 will vary behavior here in the future..

I do not think crossgen2 will vary behavior here.

The only reason I can think of for keeping the callback would be whether the codegen team still cares about running CoreCLR JIT against desktop for testing purposes. If not, it can be deleted to make things simpler. (There is actually quite a bit of other cruft on JIT/EE interface that can be deleted if we do not need that anymore.)

**Comment by VSadov** [comment]
Inlined typecheck looks much better. 
I cannot think of a reason for `canInlineTypeCheckWithObjectVTable` to return false.

**Comment by AndyAyersMS** [comment]
>  (does) the codegen team still care about running CoreCLR JIT against desktop for testing purposes

Not sure; I will follow up on this.

**Comment by AndyAyersMS** [comment]
Codegen team's consensus is that we are not leveraging desktop to test core jit sources anymore and cleanup makes sense. I am running this idea past a few more folks as we speak.

Probably best to do the interface cleanup in one PR to avoid needing to repeatedly churn the GUID. It would be nice if that cleanup was a no-diff change. So perhaps do it before or after fixing this.

**Comment by jkotas** [comment]
After fixing this would be better.

**Comment by MichalStrehovsky** [comment]
Is the plan to keep `canInlineTypeCheck` and only delete `canInlineTypeCheckWithObjectVTable`?

I'm asking because if we ever want to bring e.g. frozen string literals or preinitialized arrays a la .NET Native into CoreCLR (building on top of the existing `FEATURE_BASICFREEZE` in the GC), we would want to keep the ability to disable inline typechecks for those - .NET Native relied on emitting multiple module-local MethodTables for these (to avoid having to do expensive things like patching frozen object headers at startup).

**Comment by jkotas** [comment]
> Is the plan to keep canInlineTypeCheck and only delete canInlineTypeCheckWithObjectVTable?

I guess we can keep `canInlineTypeCheck`. We can discuss what makes sense to cleanup and keep in the JIT/EE interface cleanup PR.

**Comment by pentp** [comment]
Is the sealed array opportunity (comment by @omariom) tracked somewhere or was this also resolved by the same PR?

**Comment by AndyAyersMS** [comment]
Array types that appear in type equality checks now get optimized. For more general is/as checks we have to worry about variance and the like.

**Comment by jkotas** [comment]
@pentp I do not think we have an issue on it. Feel free to open one if you care about this case.

@AndyAyersMS is right that this cannot be done for all arrays. It can be done only when we can prove that the cast cannot be done via variance and the like. For example, `int[]` casts still need to use the helper, on the slow path at least.
