### ISSUE TITLE
Profiler API: Add a new API to determine if object is in RO segment

### ISSUE THREAD

**Issue by mjsabby** [dotnet/runtime#12580]
Adding a new API that given an ObjectID determines if the object is in an RO Segment or not.

I'm not sure if we should call it `IsObjectInReadOnlySegment(ObjectID)` or `IsFrozenObject(ObjectID)`.

**Comment by davmason** [comment]
@mjsabby has there been any progress on the docs for this?

**Comment by mikelle-rogers** [comment]
Already documented.
