### ISSUE TITLE
IJW does not seem to work with dllexport in "pure" managed assembly

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#12611]
from @batzen (https://github.com/dotnet/core-setup/issues/6100)

I am not sure if this issue belongs in this repo but as dotnet/runtime#5927 was tracked here i guessed this would be the correct repo. Please guide me to the correct repo if this is the wrong one.

**Steps to reproduce**
Clone https://github.com/batzen/NativeToManagedTest
Compile NativeToManagedTest.sln (either using VS 2019 or dotnet build NativeToManagedTest.sln)
Run "WPFTestApp.exe" from "bin\Debug\x64\netcoreapp3.0"
Click button labeled "Call managed native"

**Expected behavior**
App should not crash and not show two error message boxes, but show two message boxes from ManagedMethod in class ManagedClass from assembly ManagedWithDllExport.
If working correctly the message boxes should contain the same info about the current runtime etc. as present in the main window.
If you run the net462 version of WPFTestApp everything works as expected.

**Actual behavior**
App crashes or shows two error message boxes.

**Environment data**
TargetFrameworkAttribute.FrameworkName: .NETCoreApp,Version=v3.0
TargetFrameworkAttribute.FrameworkDisplayName:
Environment.Version: 3.0.0
RuntimeInformation.FrameworkDescription: .NET Core 3.0.0-preview5-27617-04
CoreCLR Build: 3.0.0-preview5.27617.71
CoreCLR Hash: df2f4c4feb273545e91fd8d7d170dc424b741f19
CoreFX Build: 3.0.0-preview5.19216.14
CoreFX Hash: f9f88bd7fd774ce433a764b6d388517c6460164a
OS Version
Environment.OSVersion: Microsoft Windows NT 6.2.9200.0
RuntimeInformation.OSDescription: Microsoft Windows 10.0.17763
Bitness
RuntimeInformation.OSArchitecture: X64
RuntimeInformation.ProcessArchitecture: X64
Environment.Is64BitOperatingSystem: True
Environment.Is64BitProcess: True

**Comment by AaronRobinsonMSFT** [comment]
@batzen Is this still something you are working on? No pressure, just trying to determine the current state of the interop workload for .NET 5.0.

**Comment by batzen** [comment]
@AaronRobinsonMSFT Sorry for my late response. I stopped working on it as soon as i realized that it would be way too complicated to ship my own ijwhost in snoop and to support different injection ways over the next few years.
Although i would love to see this feature be available in .NET 5.0 i won't contribute it as i currently have no use case for it anymore.

**Comment by AaronRobinsonMSFT** [comment]
Closing this as "by-design" - unless someone feels there is an opportunity here. The recommended approach is demonstrated in [DNNE](https://github.com/AaronRobinsonMSFT/DNNE).
