### ISSUE TITLE
OpenCover code coverage broken in 3.0 preview 4

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#12632]
I've just noticed in some 3.0 branches of some applications I'm maintaining as the previews ship, that code coverage metrics have stopped being reported with OpenCover in preview 4. The code coverage was being reported using preview 3.

Below are links to two commits of an application and its AppVeyor CI build showing code coverage being reported with preview 3, but not with preview 4. I've observed this with multiple applications, so I do not believe it is specific to this particular application.

| Release | Commit | Build |
|:-:|:-:|:-:|
| 3.0.100-preview3-010431 | https://github.com/martincostello/website/pull/254/commits/f1e71c056818cbc1d7470b3e8806745601dd6cd6 | [Logs](https://ci.appveyor.com/project/martincostello/website/builds/22879215#L218) |
| 3.0.100-preview4-011223 | https://github.com/martincostello/website/pull/254/commits/ac210c0baa6bd56a0826e275056928105107e5be | [Logs](https://ci.appveyor.com/project/martincostello/website/builds/23967773#L229) |
| 3.0.100-preview5-011568 | https://github.com/martincostello/website/pull/254/commits/e6f6627ac312aa62be0de717b3c785a9b88a5bea | [Logs](https://ci.appveyor.com/project/martincostello/website/builds/24344819#L228) |

**Comment by tommcdon** [comment]
Closing since this issue is over a year old and has not had activity since then
