### ISSUE TITLE
<Link>...</Link> vs. Link="..." for Common files

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#1266]
Most libraries .csproj projects use `<Link>...</Link>` to link files from Common. There are a few that use `Link="..."`. We should unify on one style.

**Comment by jkotas** [comment]
See https://github.com/dotnet/runtime/pull/1247#discussion_r362550991 for discussion of pros and cons of each option.

**Comment by danmosemsft** [comment]
It would be nice if there was a heuristic (it has had this behavior since the C# project system was created in VS2002)
https://github.com/dotnet/project-system/issues/5765

**Comment by ViktorHofer** [comment]
I prefer the attribute syntax over the element one here. We usually wrap additional attributes into multiple lines, which should help readability, e.g.: https://github.com/dotnet/runtime/blob/master/src/libraries/pretest.proj#L43-L48.
