### ISSUE TITLE
Support ReadyToRun on mixed-mode assemblies

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#12667]
Right now we explicitly block crossgenning/ready-to-running any mixed mode assemblies (see dotnet/coreclr#24451). We should take a look at enabling it depending on cost of implementation and the perf difference for our partners such as WPF.

Originally part of dotnet/runtime#10333.

**Comment by trylek** [comment]
Closing as a duplicate of https://github.com/dotnet/runtime/issues/83942.
