### ISSUE TITLE
$PYTHON in System.Private.Corlib.csproj is empty when opened via IDE

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#12675]
See https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L431
As far as I understand this variable is computed in build scripts where it's exported for the current process. However if I open the `System.Private.CoreLib.sln` in an IDE (VS/VSfM/Rider) I get
```
System.Private.CoreLib.csproj(418, 5): [MSB3073] The command """ 
/prj/coreclr-egor/src/System.Private.CoreLib/../scripts/check-definitions.py 
...... exited with code 127.
```
`build.cmd` [saves](https://github.com/dotnet/coreclr/blob/2e32f3b92f3a17b5821673babaa6883deb5ab209/build.cmd#L414) PYTHON to `%TEMP%\pythonlocation.txt`  so I guess `System.Private.CoreLib.csproj` could read it from there. (NOTE: build.sh doesn't save the computed path).

**Comment by jkotas** [comment]
This was fixed a while ago.
