### ISSUE TITLE
CLSID_CLRProfiling is absent in metahost.h

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#12689]
There is only one reference in comment: https://github.com/dotnet/coreclr/blob/70300c711b9e507d251f9a31d5c4be9653dd4c8a/src/inc/metahost.idl#L491, but there is no any more declaration for `CLSID_CLRProfiling`

**Comment by davmason** [comment]
Closing this issue as there is nothing to do, CLSID_CLRProfiling is intentionally removed on coreclr
