### ISSUE TITLE
Usage of memset with non-trivial types that results in -Wclass-memaccess

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#12684]
Starting with gcc 8, compiler is warning about several usages of `memset` in case of types that are
[non-trivially copyable](https://rules.sonarsource.com/cpp/RSPEC-4999). This includes `struct`s inheriting `struct ZeroInit`, usage of `FillMemory` and `ZeroMemory` macros (defined in `pal.h`) and other places which are directly calling the function (although some of those places can make use of the defined macro as it stands).

From release notes (https://www.gnu.org/software/gcc/gcc-8/changes.html):

> `-Wclass-memaccess` warns when objects of non-trivial class types are manipulated in potentially unsafe ways by raw memory functions such as `memcpy`, or `realloc`. The warning helps detect calls that bypass user-defined constructors or copy-assignment operators, corrupt virtual table pointers, data members of `const`-qualified types or references, or member pointers. The warning also detects calls that would bypass access controls to data members.

LLVM has included `-Wnontrivial-memaccess` for C structs and there are also considerations to add `-Wclass-memaccess` in future: https://reviews.llvm.org/D45310

Reading the community discussions about practices pertaining to usage of `memset` with non-POD types and how others have responded to the gcc warning, I think there are three ways to fix this (in descending order of preference):

1. Call proper ctor, use `std:fill` and friends for non-trivial data structures.
2. Cast pointer to `void*` to circumvent the type check.
3. Suppress warning in cmake `-Wno-class-memaccess`.

**Comment by RobertHenry6bev** [comment]
There are numerous places gcc-12 complains about memset being called to zero the entire object when the object is not Plain Old Data (POD).  (The C++ standard haas a more encompassing definition than POD.)

Consider https://github.com/dotnet/runtime/blob/3e0a5adaefc0936bdb8ec4b152914b5c996c97c6/src/coreclr/vm/syncblk.h#L631
InteropSyncBlockInfo has a lot of non-trivial data, some of which will (likely?) have constructors fired on them, and the memset is a blunt hammer to zero out everything, perhaps leaving embedded objects in an inconsistent and buggy state.

**Comment by RobertHenry6bev** [comment]
I went through and added gcc diagnostic suppressions throughout the code  base as needed to get to compile with gcc12.

There were 41 files changed with ~50 changes.  See attached  file
[robhenry-memaccess-pragma.txt](https://github.com/dotnet/runtime/files/9311368/robhenry-memaccess-pragma.txt)


It is conceivable that the CONTRACT semantics of some of the callers to memset tell some compiler that memset is safe, but gcc certainly doesn't know about that.
