### ISSUE TITLE
Decide on output paths for shared live components

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#127]
As we transition to a live-live build in the repository and away from packages, we should look at consolidating the output paths of various components to well-known and agreed upon locations so we can limit how much extra copying we need to do to support consumption within the build.

These are the paths the live live build in #494 uses:

- CoreCLR outputs (currently all pulled from the layout of CoreCLR's build output)
	- native components in the shared framework
	- cross-architecture native components in the shared framework (arm and arm64 only)
	- R2R System.Private.CoreLib and PDB
	- IL System.Private.CoreLib and PDB (used for code-coverage via coverlet)
- Libraries outputs (Pulled from various binplace configurations)
	- shared framework ref assemblies and pdbs
	- shared framework implementation assemblies
	- native libraries and symbols
	- out-of-box ref assemblies and pdbs
	- out-of-box implementation assemblies and pdbs
	- packages output (the standard Arcade output location works for here)

Note that this does not include consuming the live hosting bits (hostfxr, hostpolicy, etc) for the libraries test tree. The output path for those binaries is important, but is not as high priority as the items above.

cc: @trylek @safern @jashook

**Comment by ViktorHofer** [comment]
@jkoritzinsky is there anything left to do here?

**Comment by jkoritzinsky** [comment]
I don't think there's any additional work unless we want to change our current output folders.

**Comment by ViktorHofer** [comment]
I don't think there is a need for that at the moment. Closing.
