### ISSUE TITLE
[ARM64/Linux] Inefficiencies when using initializing/cleaning unsafe pointers

### ISSUE THREAD

**Issue by TamarChristinaArm** [dotnet/runtime#12736]
For the following case with `QuickJIT` turned off

```
static int[] Test(int[] a)
{
  unsafe {
    fixed (int *a_ptr = a, b_ptr = b)
    {
    }
  }
  return a;
}
```

The initialization of the pointer correctly uses the zero register

```
        F9000FBF          str     xzr, [fp,#24] // [V05 loc2]
        F9000BBF          str     xzr, [fp,#16] // [V06 loc3]
```
	
However it doesn't use `stp/ldp` when it's possible to.

also when cleaning up the `str`s suddenly don't use `xzr` anymore

```
        D2800001          mov     x1, #0
        F9000FA1          str     x1, [fp,#24]  // [V05 loc2]
        F9000BA1          str     x1, [fp,#16]  // [V06 loc3]
```

/CC @CarolEidt @tannergooding 

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by SwapnilGaikwad** [comment]
The zero reg issue is already fixed by the PR #52269.  

Assembly with and without the above patch is following.
**Without** patch:
```
mov     x0, xzr
str     x0, [fp, #0x38]	// [V04 loc2]
mov     x0, xzr
str     x0, [fp, #0x30]	// [V05 loc3]
```

**With** patch:
```
str     xzr, [fp, #0x38]	// [V04 loc2]
str     xzr, [fp, #0x30]	// [V05 loc3]
```
Regarding ldp/stp usage, there are other issues (for ldp: #35132, #35130; stp: #35133, #35134) tracking it.

**Comment by a74nh** [comment]
@kunalspathak

**Comment by kunalspathak** [comment]
Thanks for checking @SwapnilGaikwad .
