### ISSUE TITLE
Determining whether System.Reflection.DispatchProxy is supported

### ISSUE THREAD

**Issue by darkl** [dotnet/runtime#1275]
Hi,
Is there any way using `netstandard21` to check if `System.Reflection.DispatchProxy` is supported on the current platform?

In [this issue](https://github.com/dotnet/corefx/issues/29258) it is mentioned that `System.Reflection.DispatchProxy` is affected by the `RuntimeFeature` class. Is it possible to use `RuntimeFeature` to determine whether `System.Reflection.DispatchProxy` is supported?

Thanks
Elad

**Comment by MichalStrehovsky** [comment]
What platform are you hitting the problem on? `DispatchProxy` was designed so that it can be reliably supported even without a JIT or interpreter (that's why it works with .NET Native for UWP apps too). AFAIK it's supported everywhere.

**Comment by darkl** [comment]
It used not to work on Xamarin.iOS. Is it now supported there?

**Comment by MichalStrehovsky** [comment]
Might be worth asking over at the https://github.com/xamarin/xamarin-macios repo.

If Xamarin iOS doesn't do any special casing, this is a question about whether it can now do Reflection.Emit (which according to https://devblogs.microsoft.com/xamarin/introducing-xamarin-ios-interpreter/ might now work).
