### ISSUE TITLE
[reflection] Better test coverage for Type.FullName

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#1276]
Bouncing this over after someone reported it in mono/mono: https://github.com/mono/mono/issues/18180

Given this sample, Mono and CoreCLR's output is different, and CoreCLR's seems wrong:
```csharp
using System;
using System.Buffers;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            var t = typeof(ReadOnlySequence<>);
            var m = t.GetMethod("TryGet");
            var p = m.GetParameters()[1];
            Console.WriteLine($"Type.Name: {p.ParameterType.Name}");
            Console.WriteLine($"Type.FullName: {p.ParameterType.FullName}");
        }
    }
}
```

CoreCLR output:
```
Type.Name: ReadOnlyMemory`1&
Type.FullName: 
```

Mono output:
```
Type.Name: ReadOnlyMemory`1&
Type.FullName: System.ReadOnlyMemory`1[T]&
```

Tested with .NET Core 3.1.100 and Mono master (in netcore mode). .NET Framework 4.7.2 appears to have the same output as Core.

**Comment by jkotas** [comment]
It is the documented behavior for FullName. From https://docs.microsoft.com/en-us/dotnet/api/system.type.fullname?view=netcore-3.1:

> The fully qualified name of the type, including its namespace but not its assembly; or null if the current instance represents a generic type parameter, an array type, pointer type, or byref type based on a type parameter, or a generic type that is not a generic type definition but contains unresolved type parameters.

Related: https://github.com/dotnet/corefx/issues/42700

**Comment by jkotas** [comment]
I believe that the motivation for this behavior is to return only names that can round-trip using  `Assembly.GetType`.

**Comment by CoffeeFlux** [comment]
Oh I see, thanks for the clarification. I searched the CoreCLR repo for previous issues about this and not CoreFX :(
Do you know if there are any tests for this (presumably in CoreFX?) If not, I can PR some based on Stephen's example while fixing this in Mono if they'd be welcome, since I'm going to have to make some examples while fixing it anyway.

**Comment by jkotas** [comment]
The only test that I am able to find is here: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Reflection/tests/TypeInfoTests.cs#L1193

So yes, we can certainly use a better coverage.

**Comment by steveharter** [comment]
I'm assuming we can close this - the functionality is by-design and existing doc is adequate.

**Comment by CoffeeFlux** [comment]
The issue is already closed, if that's what you're referring to.

Jan clarified that it's intended behavior, so I fixed it on Mono's end and added tests to clarify that it is indeed intentional, since we didn't previously have any coverage. See #1613 and https://github.com/mono/mono/pull/18385
