### ISSUE TITLE
Support 2MB/1GB page sizes for Large Pages in OS that support specifying the sizes

### ISSUE THREAD

**Issue by mjsabby** [dotnet/runtime#12779]
`NtAllocateVirtualMemoryEx` has a new setting that allows picking large page size in Windows 19H1. We should use this API when we detect we're running on 19H1+.

The benefit is that we can request which size of large pages do we want. For example, we could try 1GB first, and fall back to 2MB if it fails, etc.

**Comment by nico-abram** [comment]
Is that `NtAllocateVirtualMemoryEx` function documented anywhere? Would it need to be loaded from ntdll via GetProcAddress (Like mimalloc does [here](https://github.com/microsoft/mimalloc/blob/master/src/os.c#L152))?

**Comment by mjsabby** [comment]
@nico-abram it is not documented, and yes it needs to be used in the same way.

**Comment by mjsabby** [comment]
@Maoni0 @cshung are either of you working on this one?

**Comment by Myriachan** [comment]
NT API `NtAllocateVirtualMemoryEx` is documented as kernel32 API `VirtualAlloc2` / `VirtualAlloc2FromApp`.

**Comment by Maoni0** [comment]
Windows will automatically use 1GB pages if it can find one. so no action needs to be done by us. so this can be closed.
