### ISSUE TITLE
Cannot build System.Private.CoreLib in Visual Studio

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#12792]
I have issues building System.Private.CoreLib.sln in Visual Studio. What I did:

0. `git clean -xdf`.
1. `build.cmd`. This completes successfully.
2. Open and build System.Private.CoreLib.sln in VS 2017:

    > CSC : error CS1617: Invalid option '8.0' for /langversion. Use '/langversion:?' to list supported values.

    I think this means that VS 2017 is no longer supported, which is fine, but it's still listed in [the documentation](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md).

3. Open and build System.Private.CoreLib.sln in VS 2019 (16.1.1) or VS 2019 Preview (16.2.0 Preview 1.0):

    > C:\Program Files\dotnet\sdk\3.0.100-preview6-011743\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
    > CSC : error CS2001: Source file 'C:\code\coreclr\bin\obj/Windows_NT.x64.Debug/System.Private.CoreLib/netcoreapp2.1\../Eventing/NativeRuntimeEventSource.cs' could not be found.

4. Delete the missing file from the project in an attempt to fix it and build in VS 2019:

    >C:\Program Files\dotnet\sdk\3.0.100-preview6-011743\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
    >shared\System\Reflection\AssemblyMetadataAttribute.cs(10,60,10,61): error CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' context.
    >src\Internal\Console.cs(30,44,30,45): error CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' context.
    > … (thousands instances of the same error follow)

5. Build in VS 2019 Preview with the missing file deleted:

    >C:\Program Files\dotnet\sdk\3.0.100-preview6-011743\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
    >shared\System\Version.cs(32,73,32,99): error CS0117: 'SR' does not contain a definition for 'ArgumentOutOfRange_Version'
    >shared\System\Version.cs(35,73,35,99): error CS0117: 'SR' does not contain a definition for 'ArgumentOutOfRange_Version'
    > … (thousands instances of similar errors follow)

Am I doing something wrong?

**Comment by ericstj** [comment]
Given everything that's changed since Jun 2019 (dotnet/runtime now exists) I'm going to say this issue is too far removed from the initial report.
