### ISSUE TITLE
Codegen: Checking for ISA support affects inline codegen

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#12791]
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkBXfGKASzFwBuGvSasAShwB2GXtxYBhCPgAOvADY8AyjwBu/GEJGNmLSTLkwWASRl8pufkdomJ02fNsZ7jgSwAaABxIwtTGDABSEAAWUgBqMGAY0AwAvGJm7pY2drwOTiwJSdDkpIEAPABm6hDYGAB8oaJaAJ64nPhFyVBpGR08BV3QKKEiAMxMpAwKDADeNAyLDADaALIwGNEQACbWquoAFOubO3sq6gDyKrIQDiwAggDmj7C4jrowtup5eY8MhAxjltdvsrjc7k8XoZ3jAwXJeAAvOq8W4ASgAugslsQJswkAwhlBShVqrUGgx7tttgdCcSqjU6vUGJpKhg0ATEt06aTGQw+I9ohhUVjFvNqEsJQxeJUGActLgrNZcFoOCoVNAMDBtsLxZLRSK9diAOwMeVWSnUllsvm8AVC0KGhgAXxoBolxBN2xglWwHHUGAdSxdusWBrWG2BZ0OQNOoOuKIhz1eMK+PykfwBMZB5zht1wDyT0N4Hzh+ERyLRmJDTFx5HxtLK9LJTItbAgCmiiQA1jTOSVGzzyVb2Q2SQzyfzBTqJWKJQBID2mhUPKkHYc2u2owOLYMSg04sT44goClUtsd7u2AAyEAgKl7xSJA/H9WW6IYuCgYBHfafY+bb4MF6uBCgas6GpUKQHLo2A9LwvR0IIUoMOUH5fiwV4wOmmxIbwADUeHToa4GOosME9B8j69J+YDLLw6LbqRkE9NBsEMAAVghSGcahdbcQRRF6nOJGkXOlHdL0rbtp2YA9uJ0DsvJUBbm6SxzrupGLMBGB0e+6RKYxEoaTuBr7rWR4nhaF6ydet73qOTaMoBNE/o+3IvoB2mCXMqmLMxsrkch6SIchqE0RhWGPDhUoCb5PnVo6gVKdRX66YZEFQYFnHBdxKEMHxHGxQlakiY6Ym/pJq5KYpv4qcVizqXFErabpvQGXFxnOjQTpAA=)

Writing and comparing some intrinsic code for vectors compared to `Sys.Numerics.Vector4` equivalents, I noticed a significant slowdown (~20%) in a tight loop of vectorised addition. I verified the native for the actual add methods is identical, and it is, with the `if (Sse.IsSupported)` check. However, when it is inlined as part of the loop method (as desired), the codegen is not identical, and 
```
vaddps xmm0, xmm0, xmm0
``` 
is transformed to 
```
vmovaps xmm1, xmm0
vaddps xmm0, xmm1, xmm0
```
, which I think is a completely pointless op, as it doesn't have an effect on the end result (and it slows it down, so clearly not for optimization or anything)

Tested on .NET Core preview 5 as well as on whatever preview version SharpLab is running

[Image for easy visualisation of issue](https://imgur.com/a/PmkqmdE)

category:cq
theme:vector-codegen
skill-level:expert
cost:large

**Comment by AndyAyersMS** [comment]
Seems like this is fixed now? 

Sharplab 6.0 codegen is identical between `AddNoCheckInLoop` and `AddCheckInLoop`.

**Comment by tannergooding** [comment]
This is likely resolved due to the work @EgorBo had done to take advantage of the token resolution during inlining support I added.

It means we can actually see its an `IsSupported` call and take that into account when upping the "inline profitability".

**Comment by BruceForstall** [comment]
Since it appears to be fixed, I'm closing.
