### ISSUE TITLE
only cd to current directory works

### ISSUE THREAD

**Issue by quantrpeter** [dotnet/runtime#12794]
Hi
   I have compiled the clr since i need ilasm and ilsasm commands. When i cd to the output directory and run ilasm, it works:

/Users/peter/workspace/coreclr/bin/Product/OSX.x64.Debug>./ilasm

if i add the path to $PATH and run it in other directory by "ilasm". It said:

Segmentation fault: 11

Please help
Thanks
Peter

**Comment by BruceForstall** [comment]
This is the same problem as https://github.com/dotnet/runtime/issues/12690
