### ISSUE TITLE
Re-evaluate defaults in ArrayPool.Shared

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#12800]
Prior to trimming support being added in, `ArrayPool.Shared` was given several hardcoded upperbounds, e.g.
https://github.com/dotnet/coreclr/blob/6631a7a0f9b6268f5e6c0f609a2d0d2a730a2118/src/System.Private.CoreLib/shared/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#L33-L38

Now that we have basic trimming support in place, where unused arrays will be removed from the pool in response to memory pressure, we should re-evaluate these constraints.  For example, that number of buckets limits the size of arrays that can be pooled, which means if you call `ArrayPool<byte>.Shared.Rent(10_000_000)`, it's just going to allocate a new array, always, and returning that array to the pool will just drop it.  Should we increase the number of buckets such that all array sizes can be cached?  Should we increase the number of arrays per size that can be cached?  Etc.

cc: @JeremyKuhne, @jkotas

**Comment by joperezr** [comment]
@stephentoub I'm pushing this to future for now given that it has been logged for a year now, but feel free to pull back to 5.0 if this is something we want to fix there.

**Comment by stephentoub** [comment]
That's fine, thanks.
