### ISSUE TITLE
IDL annotations and implementation differences

### ISSUE THREAD

**Issue by WilliamXieMSFT** [dotnet/runtime#1281]
This is more of a question than a problem, but as an example I noticed that the `pcbMethodSize` parameter in `GetILFunctionBody` is marked with an [out] parameter:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/inc/corprof.idl#L2752

However the resultant header file
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/vm/proftoeeinterfaceimpl.h#L211
makes no indication whether this parameter is optional (nullable) or required and the implementation conducts a null check:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/vm/proftoeeinterfaceimpl.cpp#L4412

MIDL supports translating [IDL annotation to SAL](https://docs.microsoft.com/en-us/windows/win32/midl/-sal) and the [out] parameter gets converted to `_Out_`. According to [SAL](https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-function-parameters-and-return-values?view=vs-2019), `_Out_` requires pointers to not be NULL.

My question is do the IDL annotation follow SAL expectations? Should this be enforced?

**Comment by jkotas** [comment]
We would not want to change the GetILFunctionBody method behavior in a way that it can break existing profilers. If you would like to do something about this, feel free to submit PR to correct the annotation in the .idl file.

**Comment by WilliamXieMSFT** [comment]
It looks like from the Profiler docs that 

>All [out] parameters on the API are optional, unless a function has only one [out] parameter. A profiler simply passes NULL for any [out] parameters it is not interested in. The profiler must also pass consistent values for any associated [in] parameters—e.g., if the NULL [out] parameter is a buffer to be filled with data, the [in] parameter specifying its size must be 0.

The answer is that the SAL annotation produced from MIDL would not be correct. Closing this issue; we'll have to fix our implementation in https://github.com/Microsoft/CLRInstrumentationEngine
