### ISSUE TITLE
Follow-up on renaming suggestions in #24371

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#12815]
This issue is about `pInitRegZeroed` parameter used across many functions in CodeGen

> This method is not zero-ing initReg so it sounds strange to me that an out-parameter is named pInitRegZeroed. It also doesn't know or check that it holds zero on input. IMO, it would be clearer to name the argument pInitRegUsed and set it to true if initReg is used for setting the cookie.

_Originally posted by @erozenfeld in https://github.com/dotnet/coreclr/pull/24371_

> I agree that it's confusing. I might rename it `pInitRegModified`. Theoretically it wouldn't have to set it to false if it had actually zero'd the register, but that doesn't actually happen anywhere. It might be worth a comment here in the header to note that the caller is passing in the `initReg` that it uses in the prolog and therefore it needs to know whether it has been set to a non-zero value (or something to that effect).

_Originally posted by @CarolEidt in https://github.com/dotnet/coreclr/pull/24371_

> While I don't disagree about it being potentially confusing, note that `pInitRegZeroed` is the name used in many functions that do the same thing.

_Originally posted by @BruceForstall in https://github.com/dotnet/coreclr/pull/24371_

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

**Comment by marcusturewicz** [comment]
Not sure why the original PR https://github.com/dotnet/coreclr/pull/25741 was closed, but was this correct?

**Comment by echesakovMSFT** [comment]
> Not sure why the original PR dotnet/coreclr#25741 was closed, but was this correct?

Hmm, good question - I also don't why. IMO, the changes in that PR were going in the right direction - the only part that left missing is renaming `initRegZeroed` to `initRegModified` in `genFnProlog()` where the variable is defined. 

@ivanbuha Would you be interested in finishing up your PR in dotnet/runtime repo?

**Comment by ivanbuha** [comment]
@echesakovMSFT Yes. Thanks for missing part. I will go over once more to make sure everything is correct in PR.

**Comment by ivanbuha** [comment]
Just an update, I run into the issues building locally. Planning to resume the work after making sure I can build the repo locally.

**Comment by echesakovMSFT** [comment]
@ivanbuha Sounds good, let me know if you need some help

**Comment by ivanbuha** [comment]
PR#36321 was created.
