### ISSUE TITLE
Fill in test gaps for Event Pipe

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#12857]
We need to add new tests to cover .net core 3.0 event pipe test scenarios.  These new tests will supercede the following:

- [ ] https://github.com/dotnet/coreclr/issues/23224
- [ ] https://github.com/dotnet/coreclr/issues/22891
- [ ] https://github.com/dotnet/coreclr/issues/20510
- [ ] https://github.com/dotnet/coreclr/issues/20299

**Comment by tommcdon** [comment]
@josalem close?

**Comment by josalem** [comment]
I think we've got decent coverage for EventPipe in the runtime repo now.  There is also some md in the diagnostics repo documenting what is covered.  I'm going to close this.
