### ISSUE TITLE
API Proposal: GC.GetGenerationSize

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#1289]
Gets the GC heap size of a given generation.

```cs
public static class GC
{
    public static long GetGenerationSize(int generation);
}
```

Uses:

This is already implemented and is being used as part of the runtime performance counters. Adding this API as a public API will let customers monitor their LOH heap size or any other generations within their own process without having to write EventListener to consume the counters.

**Comment by Gnbrkm41** [comment]
How would you query for the size of the LOH? as in, does LOH have a specific generation number or something?

**Comment by sywhang** [comment]
LOH heap is gen 3.

**Comment by Maoni0** [comment]
what about other aspects of the generations like the fragmentation and etc? it's better to provide them together instead of having separate APIs so you don't have the other data from one GC and the gen size from another.

**Comment by guitarrapc** [comment]
I do need this API just as other APIs `GC.CollectionCount(int generation)` offers.

**Comment by Maoni0** [comment]
BTW, if we want to add a public API it will need to go through the API review process.

**Comment by Joe4evr** [comment]
Given that very few people would think that there's a Gen3 which is actually the LOH, might it be desirable to define the different heaps as an enum?
```cs
public enum GCHeapGeneration
{
    Gen0,
    Gen1,
    Gen2,
    LargeObjectHeap
}
```

**Comment by jkotas** [comment]
There is `GC.MaxGeneration` that gives you the number of generations. I do not think we would want to codify the generation names and purposed in the API surface - that's hardcoding too much GC implementation details in the API surface.

**Comment by Maoni0** [comment]
after talking to more customers, I've filed an API proposal [#34648](https://github.com/dotnet/runtime/issues/34648) that supersedes this.

**Comment by sywhang** [comment]
Closing this in favor of #34648.
