### ISSUE TITLE
ParameterInfo.DefaultValue returns the raw value if the enum is nullable

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#12924]
Given the following method parameters, the first ParameterInfo's DefaultValue returns `SomeEnum.A`, unlike the RawDefaultValue parameter. The second ParameterInfo's DefaultValue returns `0`, just like the RawDefaultValue parameter:

```cs
enum SomeEnum { A, B }

class Foo
{
    public void Bar(SomeEnum x = SomeEnum.A, SomeEnum? y = SomeEnum.A)
    {
    }
}

public static class Program
{
    public static void Main()
    {
        foreach (var parameter in typeof(Foo).GetMethod(nameof(Foo.Bar)).GetParameters())
        {
            var defaultValue = parameter.DefaultValue;
            Console.WriteLine($"{defaultValue} ({defaultValue.GetType()})");
        }
    }
}
```

Output:

```
A (SomeEnum)
0 (System.Int32)
```

To work around the problems this was causing, you can replace all calls to ParameterInfo.DefaultValue with a call to this method:

```cs
private static object GetDefaultValue(ParameterInfo parameter)
{
    if (parameter.DefaultValue != null)
    {
        var underlyingType = Nullable.GetUnderlyingType(parameter.ParameterType);

        if (underlyingType != null && underlyingType.IsEnum)
        {
            return Enum.ToObject(underlyingType, parameter.DefaultValue);
        }
    }

    return parameter.DefaultValue;
}
```

Someone suggested that I file this in case this is something you would consider changing in a future major version.

**Comment by GrabYourPitchforks** [comment]
This behavior is unfortunate, but it's by-design for compatibility with older versions of the runtime. See the comments at https://github.com/dotnet/coreclr/pull/17977 for further information.
