### ISSUE TITLE
[Windows|Arm32] Native varargs unsupported by the platform

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#12979]
This is an issue to track specifically arm32 Windows not supporting native varargs __arglist and Pinvokes to va_list functions.

See https://github.com/dotnet/coreclr/issues/18377 for information regarding the codegen bring-up on the platform.

category:reach
theme:varargs
skill-level:expert
cost:medium

**Comment by jkotas** [comment]
Windows Arm32 is no longer supported.

**Comment by BrianBohe** [comment]
@jkotas  Test [src/tests/JIT/Directed/PREFIX/unaligned/1/arglist_Target_ARM.ilproj](https://github.com/dotnet/runtime/blob/86bfe2a0e2dc95eb15c124a8d18f4f8ac2bca3f5/src/tests/JIT/Directed/PREFIX/unaligned/1/arglist_Target_ARM.ilproj) is disabled [twice](https://github.com/dotnet/runtime/blob/main/src/tests/issues.targets#L350-L376) but after merging JIT\Directed, the ilproj filename changed got scheduled and is actually passing. I guess we should either remove the test or enable it back. What is the policy here?

**Comment by BrianBohe** [comment]
Same with [JIT/Directed/PREFIX/unaligned/4/arglist_Target_ARM](https://github.com/dotnet/runtime/blob/86bfe2a0e2dc95eb15c124a8d18f4f8ac2bca3f5/src/tests/issues.targets#L494)

**Comment by BrianBohe** [comment]
Again [here](https://github.com/dotnet/runtime/blob/86bfe2a0e2dc95eb15c124a8d18f4f8ac2bca3f5/src/tests/issues.targets#L653-L668)

**Comment by BrianBohe** [comment]
I am not sure whether [this one](https://github.com/dotnet/runtime/blob/86bfe2a0e2dc95eb15c124a8d18f4f8ac2bca3f5/src/tests/issues.targets#L1081) is related also, but was skip for windows and non-windows (its analogous target TargetUnix)

**Comment by jkotas** [comment]
> What is the policy here?

vararg tests should be running on Windows CoreCLR only. vararg tests should be disabled for NativeAOT, Mono and all non-Windows platforms.

**Comment by BrianBohe** [comment]
@jkotas Should we leave the test for non-windows as disabled in case this change in the future then?

**Comment by jkotas** [comment]
Yes, these tests should remain disabled for non-Windows.

**Comment by BrianBohe** [comment]
Thanks @jkotas !
