### ISSUE TITLE
Crash happen when the netperf file path does not exist

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#13023]
Repro change:
Line 34 of file corecl\tests\src\tracing\common\NetPerfFile.cs
Hard code the file path to any path which does not exist, example "F:\NotExistFolder\"

Run Test:
coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.csproj

Actual:
Crash happened.
Expected:
Exit with error message instead of crash.

**Comment by sywhang** [comment]
Closing as not an issue.
