### ISSUE TITLE
Fill uninitialized address-taken locals with poison pattern in debug codegen

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#13072]
C/C++ compilers have this debugging/diagnostic aid for years.

More context: https://github.com/dotnet/coreclr/pull/25674#issuecomment-511118490

Related to: https://github.com/dotnet/csharplang/issues/868

category:testing
theme:testing
skill-level:beginner
cost:small

**Comment by GrabYourPitchforks** [comment]
Honestly, I'd like to see this not just for debug codegen, but also as an opt-in thing that admins could enable in production applications. Going to my cloud hosting portal and hitting a checkbox that says "my app is misbehaving; please enable additional error checking at runtime" is a compelling scenario.
