### ISSUE TITLE
Ensure FileVersion for coreclr.dll doesn't overlap with Silverlight in 5.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/runtime#13096]
We should put some protection in place against coreclr.dll's FileVersion overlapping with versions from Silverlight, now that we're moving to 5.0. 

CC @RussKeldorph @jaredpar

**Comment by ericstj** [comment]
Here's info from a thread with @leculver 

>From the attached offline conversation, this is apparently what we are looking for:
https://www.microsoft.com/getsilverlight/locale/en-us/html/Microsoft%20Silverlight%20Release%20History.htm
 
>For 5.0.*, we are in good shape.  We just have to avoid these exact version numbers (and the volume is so low on each we could collide here and there wouldn’t really be any problems):
5.0.61118
5.0.60818
5.0.60401
 
>For 5.1.*, we might need to avoid more versions.  I see hits on these versions in current Watson:
5.1.50918.0
5.1.50907.0
5.1.40728.0
5.1.10411.0
5.1.20513.0
5.1.20913.0
 
>However, we don’t need 5.1.* versions yet, and by the time we do maybe only the latest versions of Silverlight will be a problem?
 
>My concrete advice here is:  
 
>For 5.0:  Use 5.0.0 – 5.0.59999 for version numbers, but do not ship .Net Core on any version at or higher than 5.0.60000.
 
>For 5.1:  I believe we can ship 5.1.0 - 5.1.49999 without causing any problems with collisions.
 
>Beyond 5.1 we are done with these problems and do not have to worry about this for 5.2+ or 6.0+.
 
So we aren't shipping 5.1 for 5.0 we just need to remember not to exceed .59999 (or add an target to check this), or we could just ignore it as @leculver suggests.

**Comment by ViktorHofer** [comment]
Based on this additional data I don't think _any_ action is necessary. The probability that the versions collide is _very_ low and it doesn't sound like a collision would cause major issues. Hence closing.

**Comment by leculver** [comment]
A collision _would_ cause major issues.  @ViktorHofer What version is embedded in coreclr.dll for 5.0?

**Comment by ViktorHofer** [comment]
> and the volume is so low on each we could collide here and there wouldn’t really be any problems

That's why I assumed a collision wouldn't cause a major problem.

> What version is embedded in coreclr.dll for 5.0?

The latest 5.0 official build produced the following file version: `5.0.20.45102`. The rules for calculating the file version can be found here: https://github.com/dotnet/arcade/blob/c788ffa83b088cafe9dbffc1cbc8155ba88b2553/Documentation/CorePackages/Versioning.md#file-version.

**Comment by leculver** [comment]
Ahh ok, if we are shipping within 5.0.20.* then we can safely close this issue (doing so now).

Sorry, my comment above was from over a year ago, and we are in a significantly worse place with respect to watson as we were at the time.  Ensuring these don't collide is very important, but looking at the link there I agree we are good.  Thanks for double checking!

**Comment by ViktorHofer** [comment]
The File Version is a four-part version number and the last part (the revision number) is never `0`, which means we can never collide with the above provided values.

@leculver thanks for double checking 👍
