### ISSUE TITLE
ProfilerAPI: Is it safe to cache IMetaDataImport

### ISSUE THREAD

**Issue by iskiselev** [dotnet/runtime#13111]
Is it safe for profiler to cache IMetaDataImport for a module for a module lifetime?
I'm asking this question, as ICorProfilerInfo::GetModuleMetaData will fail if it is called from P/Invoke  callback, but looks like calls for cached IMetaDataImport methods works fine even from P/Invoke. 
MSDN documentation does not give any hints about IMetaDataImport lifetime and any problems that may be introduced by preserving IMetaDataImport non-released.

**Comment by davmason** [comment]
Closing as this has been answered
