### ISSUE TITLE
Would the repository benefit from a .vsconfig file for required workloads

### ISSUE THREAD

**Issue by patrickklaeren** [dotnet/runtime#13112]
As listed in the build instructions - and updated regularly according to version - several workloads are required to build CoreCLR (at least on Windows).

With the [addition of `.vsconfig`](https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/) and the ability to determine workloads based on this configuration, there might be value in adding this to the repo.

I'd be happy to contribute if people thought this was something that would improve the developer experience.

**Comment by danmoseley** [comment]
We have had one for a long time.
