### ISSUE TITLE
Test Failed: GetGCMemoryInfo returns negative value on ARM32

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#13115]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190721.1/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.GCTests~2FGetGCMemoryInfo

**Log:**
```
Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: -1844674407689672704
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 35

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
```

**Comment by mangod9** [comment]
@cshung do we know if this is still an issue which needs to be investigated?

**Comment by cshung** [comment]
> @cshung do we know if this is still an issue which needs to be investigated?

@mangod9 

I have double checked our [test exclusion list](https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/issues.targets). It appears to me that the test is no longer excluded.

This issue concerns the [GCTests](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime/tests/System/GCTests.cs), and it is not mentioned in the exclusion list. Searching `GCTests` in that file results in no match.

Searching through the file, there is a match for `GCMemoryInfo`.

https://github.com/dotnet/runtime/blob/168409e0f96f4d96a7e747dff0a5764b59592cfb/src/coreclr/tests/issues.targets#L1089

However, it is not the `GCTests` that is being referred to in this issue. Upon careful inspection, this applies to mono only, so I think we are good to close this issue if the test is indeed running and no failure reported.

@ViktorHofer, who initially disabled the test, to confirm that the test is not currently being disabled.

**Comment by mangod9** [comment]
Closing based on the comment above
