### ISSUE TITLE
R2RDump - Fix coredistools dependency in build

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#13122]
The architecture-specific coredistools.dll is not copied to the build output for R2RDump and has to be done manually to get disassembly. This should happen as part of the build - we should be publishing r2rdump, not just building it, since that deploys NuGet runtime dependencies.

**Comment by davidwrighton** [comment]
While this would be nice, we don't need this for .NET 5. Moving to 6.0

**Comment by mangod9** [comment]
@cshung believe this issue is resolved, or is there some more work required?

**Comment by cshung** [comment]
> @cshung believe this issue is resolved, or is there some more work required?

I did nothing for this bug - but it appears that the issue is probably fixed in https://github.com/dotnet/runtime/pull/44490 by @echesakovMSFT

In particular, I do see `coredistools.dll` is placed in the right directory at the build output, if that is all we wanted, I think we can close this bug.

**Comment by mangod9** [comment]
Ok closing for now, we can reopen if some OS/arch are still broken.
