### ISSUE TITLE
Affinitizing GC threads to available cpuset in containers

### ISSUE THREAD

**Issue by ezsilmar** [dotnet/runtime#13152]
Hello,

After optimizing GC for a [small container scenario](https://devblogs.microsoft.com/dotnet/running-with-server-gc-in-a-small-container-scenario-part-1-hard-limit-for-the-gc-heap/) (commit ed52a006c01a582d4d34add40c318d6f324b99ba) GC threads are not affinitized by default if the app runs with a memory limit. This is fine in most cases but is not convenient if you use cpuset (instead of more default cfs_bandwidth) isolation. 

By cpuset isolation I mean a case when the container is allowed to use only specific cpu cores. For example, if an app asks for 5 cpus, the cgroup will pin the app to some free cores (f.e. 0-2,12,18) and, by using cpuset cgroups on each task, we can guarantee that nobody else is scheduled on these cpus.

In this case, we can certainly benefit from the gc threads affinitizing. With 2.x runtime it works out of the box and gc threads are pinned correctly. However, with 3.0 we need to explicitly pass `COMPlus_GCHeapAffinitizeMask` to activate the feature. This requires the isolator to pass an affinity mask to the application which will unnecessarily couple them tighter.

It would be great if we could just set some flag to say that GC should affinitize its threads to allowed cpuset, the same way we can set `COMPlus_GCNoAffinitize` to 1 in 2.x to say it shouldn't.

I also discovered that the value of `COMPlus_GCHeapAffinitizeMask` is actually ignored in this case. If it's set to any value other than 0 GC threads will be affinitized as in 2.x (resulting in the behavior I want). Not sure though if this behavior was intended or it's a bug?

**Comment by Maoni0** [comment]
fixed by [PR#25963](https://github.com/dotnet/coreclr/pull/25963)
