### ISSUE TITLE
Unit tests for code under src/gc/ and ./src/pal/src/misc/ ?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#13156]
I am looking to port the changes in https://github.com/dotnet/corefx/pull/39686 to coreclr too. The coreclr code is getting a bit hairy and adding unit tests would give me confidence that everything is working as designed.

I am modifying these two files:

./src/gc/unix/cgroup.cpp
./src/pal/src/misc/cgroup.cpp

Are there existing unit tests (as in, tests that always run, irrespective of the environment) for these two files? If not, where would be the best place to add them?

**Comment by Maoni0** [comment]
this was open sourced so closing this...if you have problems running the perf suite (explained in the readme from the link @andy-ms mentioned above please feel free to open an issue at the dotnet/performance repo.
