### ISSUE TITLE
Object.ToString() return value should not be nullable

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#1318]
I'm guessing this was discussed and debated at some point somewhere but I can't find anything. I really think `ToString()` should be marked as a non-nullable return but that is not how it is currently annotated (with NRT). I think this is a **BIG** mistake. 

Standard practice dictates that `ToString()` should never return `null` and pretty much every piece of code ever written that calls `ToString()` assumes it returns a non-null string. Annotating it as nullable makes it appear as though it is acceptable to return null and makes dealing with the returned value (which should never be null) more cumbersome as now we have to use the null forgiveness operator.

As per the [`Object.ToString()` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=netcore-3.1):

>***Notes to Inheritors***
>- Your ToString() override should not return Empty or a null string.

If someone is going to break convention and do something that has a high probability of breaking stuff they should be forced to use the null forgiveness operator in their `ToString()` implementation to remove the warning.

What was the reasoning for marking it as nullable??

**Comment by 333fred** [comment]
@stephentoub for the reasoning here.

**Comment by svick** [comment]
This was discussed at https://github.com/dotnet/coreclr/pull/23466.

**Comment by mikernet** [comment]
Haha, I knew this debate must have happened somewhere, and oh boy it did.

I must say I'm very disappointed with the final decision. Making `ToString()` nullable is objectively wrong and if you disagree with me you are wrong 😏 I know C# isn't a democracy but from that discussion, it seems that the posts with the biggest surge of upvotes all agree with that position as well. 

I will now mourn the death of NRTs in silence.
