### ISSUE TITLE
[feature request] Implement a new await keyword to deal with configureawait

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/runtime#1320]
There is a long time running debate about the fact that `ConfigureAwait(false)` should have been the default behavior, now I understand it's late to change the default await behavior, but what about introducing a new operator like `awaitf` (note f char) or a similar concept, that act as a normal await with a ConfigureAwait(false) behavior?
In my example the f char stands for "free" in the sense that it's not capturing context, but my point is not about the real name but about the concept of having an operator that explicitly define the behavior.

This has the pros of having a clear intention while at the same time being backward compatible

what do you think?

**Comment by jkotas** [comment]
You are proposing a new C# language features. https://github.com/dotnet/csharplang repo is the place to discuss new C# language proposals.

Take a look at the similar proposals in csharplang repo:

https://github.com/dotnet/csharplang/issues/645
https://github.com/dotnet/csharplang/issues/2542
https://github.com/dotnet/csharplang/issues/2746
