### ISSUE TITLE
AV due to non-compliant type infos passed to CLR

### ISSUE THREAD

**Issue by bclothier** [dotnet/runtime#13207]
When using `CImportTlb` to build a CLR type from a type library, we encountered a situation where non-compliant library can cause an AV in CLR, specifically this line:

https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/md/enc/imptlb.cpp#L4602

See [this comment](
https://github.com/rubberduck-vba/Rubberduck/pull/4706#issuecomment-517883758) for details. Basically, the type infos we receive incorrectly have `Vars` filled for a `TKIND_MODULE`, and those `VARDESC`s have flags of `VAR_STATIC`. Some of those do have valid pointers but others won't and thus `lpvarValue` is zero. So resolving the `vt` member causes an AV.

**Comment by AaronRobinsonMSFT** [comment]
Closing since this issue is not specific to .NET Core, but rather .NET Framework.
