### ISSUE TITLE
error : Failed to resolve SDK 'Microsoft.DotNet.Helix.Sdk'. Package restore was successful but a package with the ID of "Microsoft.DotNet.Helix.Sdk" was not installed.

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#13227]
PR and outerloop builds are intermittently hitting this when sending tests to Helix:
```
/__w/2/s/tests/helixpublishwitharcade.proj(7,3): error : Failed to resolve SDK 'Microsoft.DotNet.Helix.Sdk'. Package restore was successful but a package with the ID of "Microsoft.DotNet.Helix.Sdk" was not installed.
```
The strange thing is that it looks like the test run jobs are actually sent and completed after the error.

Examples:
- PR build [293716](https://dev.azure.com/dnceng/public/_build/results?buildId=293716&view=logs&lineStart=49&jobId=6c23f58b-dd4e-59d4-0149-12bcf7fa0bde&taskId=4150e432-679f-5945-da61-a2b1889dc85c)
- PR build [298122](https://dev.azure.com/dnceng/public/_build/results?buildId=298122&view=logs&lineStart=42&jobId=9c532748-9ca4-586a-2db0-c47bd86f8652&taskId=1c6bd9fc-3899-5882-0618-d192d93e914c)
- outerloop build [286673](https://dev.azure.com/dnceng/public/_build/results?buildId=286673&view=logs&lineStart=46&jobId=02288672-4313-54e7-ac78-0c78077b23f1&taskId=7d1b159a-1648-5a13-c85c-cd5b5d582719)
- outerloop build [296676](https://dev.azure.com/dnceng/public/_build/results?buildId=296676&view=logs&lineStart=50&jobId=5df70884-47c0-5c34-2344-7b08ed4395e9&taskId=f3456839-a8d5-574a-8533-4ebf43d189a8)

cc @dotnet/coreclr-infra

**Comment by jashook** [comment]
No repro for a bit
