### ISSUE TITLE
Corelib fails to build in VS due to SR.cs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#13233]
Trying to build Corelib in Visual Studio fails because the relevant SR.cs file isn't generated.  As a result, it ends up with lots of error messages like:
```
1>shared\System\Version.cs(36,73,36,99): error CS0117: 'SR' does not contain a definition for 'ArgumentOutOfRange_Version'
```
and red squigglies all over the place while working in the IDE.

**Comment by stephentoub** [comment]
This works now.  Woo hoo!  Thanks to all who helped fix it.

**Comment by ViktorHofer** [comment]
Nice 👍
