### ISSUE TITLE
Getting native binaries and executables entitled

### ISSUE THREAD

**Issue by jcagme** [dotnet/runtime#13253]
As per the "Getting .NET Core ready for Mac OS Catalina" email we need to add a flag and entitlements to native binaries and executables to get them ready for notarization. 

The steps needed are:

1.	Add a plist which sets CSFlags to ~~65536~~ 0x10000. This is used to preserve the codesign flag “-o runtime” when codesign is called on it. We’d need to do “ld -sectcreate _TEXT __info_plist  plist_name.plist”. [This](https://microsoft.visualstudio.com/Edge/_git/chromium.src/pullrequest/3526425?_a=files) is what the Edge team did.
2.	Add entitlements. “codesign –entitlements <entitlements>  <asset>”. Here we need two things:
a.	Define what entitlements are needed. [This](https://developer.apple.com/documentation/bundleresources/entitlements) enumerates all the supported options. From what I saw I think we need something like: (to be verified by the product teams)
```xml
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
```
b.	Determine what binaries need to be entitled

ETA for this work is November when we release 3.1

fyi: @jashook @janvorli @jkotas

**Comment by jeffschwMSFT** [comment]
.NET Core February servicing update contains notarized packages.
