### ISSUE TITLE
Single exe error

### ISSUE THREAD

**Issue by gerjandev** [dotnet/runtime#1325]
```
Description: A .NET Core application failed.
Application: MyApp.exe 
Path: C:\ProgramData\MyApp\MyApp.exe 
Message: The application to execute does not exist: 'C:\Users\GEBRUI~1\AppData\Local\Temp\.net\MyApp\r5x1y4lc.ahp\MyApp.dll'.
```

We use .NET Core 3.0.

We have an WinForms application that is responsible for auto updating another application. We call this the bootstrapper. I think we can ignore this part, just think of an .NET Core 3.0 application that is packed as a single exe. It is an single exe because of portability and usability.

The problem is that now and then clients report a problem that the application won't start. You can see the error above.
Weird part is that it happens occasionally, our clients report it weekly.

So my guesses are: permissions? virus scan? single exe functionality?

**Comment by jeffschwMSFT** [comment]
cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
@gerjandev I think what happened is that the files within %TEMP%\.net\<appName>\<id>\* were deleted by Windows, but the containing directory itself wasn't deleted yet. So, in this intermediate state, the .net host tries to reuse the extraction, but fails.

We're working on a service fix to re-extract the contents of the bundle on failure within the host.

In the meantime, by setting DOTNET_BUNDLE_EXTRACT_BASE_DIR, you can extract to a non-temporary location where the OS doesn't cleanup the files, thus circumventing the failure.

Dup of dotnet/core-setup#8314.
