### ISSUE TITLE
Use PtrToStructure with UnmanagedType.ByValTStr will lose data, is it a BUG?

### ISSUE THREAD

**Issue by maikebing** [dotnet/runtime#13273]
Code:

```CSharp
using System;
using System.Runtime.InteropServices;

namespace ConsoleApp1
{
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
    public struct MSG_HEAD
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 2)] public string NetNo;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 2)] public string PlazaNo;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 3)] public string LaneID;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 14)] public string DDHM;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 1)] public string LaneType;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 5)] public string MsgLen;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 2)] public string MsgType;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 2)] public string MsgVersion;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 2)] public string Reserved;
    };//------MSG_HEAD Size:32
    class Program
    {
        static void Main(string[] args)
        {
            var data = System.Text.Encoding.ASCII.GetBytes( "0423X9120190805111432100073A0020010333333");
            Type _t_msg_head = typeof(MSG_HEAD);
            int _rs_msg_head = Marshal.SizeOf(_t_msg_head);
            IntPtr _bf_msg_head = Marshal.AllocHGlobal(_rs_msg_head);
            Marshal.Copy(data, 0, _bf_msg_head, _rs_msg_head);
            MSG_HEAD  HEAD = (MSG_HEAD)Marshal.PtrToStructure(_bf_msg_head, _t_msg_head);
            Marshal.FreeHGlobal(_bf_msg_head);
            Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(HEAD));
            Console.ReadLine();
        }
    }
}

```

Actual:
```
{
	"NetNo": "0",
	"PlazaNo": "2",
	"LaneID": "X9",
	"DDHM": "2019080511143",
	"LaneType": "",
	"MsgLen": "0007",
	"MsgType": "A",
	"MsgVersion": "0",
	"Reserved": "0"
}
```
Expect
```
0423X9120190805111432100073A0020010333333
{
	"NetNo": "04",
	"PlazaNo": "23",
	"LaneID": "X91",
	"DDHM": "20190805111432",
	"LaneType": "1",
	"MsgLen": "00073",
	"MsgType": "A0",
	"MsgVersion": "02",
	"Reserved": "00"
}
```

The value of each field is one byte less than the SizeConst specify!

**Comment by maikebing** [comment]
Is there a plan for this problem?

**Comment by AaronRobinsonMSFT** [comment]
>If you want to write the full string, using a char[] field with the [MarshalAs(UnmanagedType.ByValArray)] will do what you were expecting.

@maikebing Have you been able to try the suggestion by @jkoritzinsky? If the above isn't possible, is there some semantic dependency on `UnmanagedType.ByValTStr` that requires its application in the above scenario?

**Comment by AaronRobinsonMSFT** [comment]
@maikebing Just to elaborate on this. Changing/updating the semantics of `UnmanagedType.ByValTStr` isn't something that is likely to happen. This is an area where the cost of any breaking change isn't worth the benefit. This would warrant further consideration if porting from .NET Framework to .NET Core is the scenario and the semantics have changed.

The suggested plan would be to follow @jkoritzinsky's suggestion unless that doesn't address the issue.

**Comment by maikebing** [comment]
`char[][MarshalAs(UnmanagedType.ByValArray)]  
`
Cannot be used for utf8 or Chinese characters

I used  
`byte [][MarshalAs(UnmanagedType.ByValArray)]  
`
 So, every field needs to be converted to a string, which can be done, but I don't think it should be so cumbersome.

So, I hope it can still be done directly in some way.

**Comment by maikebing** [comment]
Is there any way to add a method or option, the last byte does not change to `\0`, and add a `\0 `as the end of the character?

**Comment by maikebing** [comment]
This usage is commonly used to interact with other languages, such as the structure of the C language that is directly mapped to the structure of C# .

**Comment by AaronRobinsonMSFT** [comment]
>char[][MarshalAs(UnmanagedType.ByValArray)]
Cannot be used for utf8 or Chinese characters

Ah ha. That is an important consideration we missed. Thank you for calling it out.

>I used
byte [][MarshalAs(UnmanagedType.ByValArray)]

Yep. That is the appropriate solution here.

>Is there any way to add a method or option, the last byte does not change to \0, and add a \0 as the end of the character?

Possibly, but that would require a new API and therefore a [proposal](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md). I don't know if this particular scenario is so negatively impacted that it would be adopted, but it is worth considering. I would like this area to have better UTF-8 support instead of the very confusing `Ansi` (which is _not_ UTF-8 compatible) and `Unicode` which is only UTF-16.

>This usage is commonly used to interact with other languages, such as the structure of the C language that is directly mapped to the structure of C# .

Agreed. The issue here is that in C/C++ an array of characters without a terminating `\0` is simply an array of characters not a ["string"](https://en.cppreference.com/w/cpp/string). The runtime is following this definition very closely here. I understand the annoyance with this semantic argument, but without that `\0` is really is just an array and the niceties of automatically converting to a `string` are difficult to apply.

**Comment by maikebing** [comment]
Indeed it is.

**Comment by AaronRobinsonMSFT** [comment]
Since we are following the interpretation of string precisely here this is by-design. Strings coming from an unmanaged environment require a `'\0'` terminator.

**Comment by maikebing** [comment]
[How memory mapping files are accessed as a variable?If not, is it possible? #42736](https://github.com/dotnet/runtime/issues/42736 )
