### ISSUE TITLE
Reasons for OutOfMemoryException

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#13284]
Here are the reasons I'm aware of that a .NET process could raise an `OutOfMemoryException`:

1. Explicit throw of `OutOfMemoryException` by developer code (like [Bitmap.Clone](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.clone?redirectedfrom=MSDN&view=netframework-4.8#System_Drawing_Bitmap_Clone_System_Drawing_Rectangle_System_Drawing_Imaging_PixelFormat_)). 
1. Allocation of a single object that exceeds inherent CLR limitations. For instance `new string('c', int.MaxValue)`
1. A 32 bit process actually running out of virtual address space to use and failing on a simple `new` operation. 

I'm sure this is not an exhaustive list though. I'm curious what the other reasons are that a process could OOM in .NET. Is there a good list somewhere I can read through? 

Asking because recently I've been looking into a number of OOM bugs for Roslyn and I'm having problems identifying the cause. Specifically we're seeing the following patterns: 

1. OOM running VBCSCompiler. Given this is a 64 bit process it's hard to understand why this would generate an OOM. 
1. Running our unit tests for dotnet/roslyn. They will fail with an `OutOfMemoryException`. There is no pattern to which test causes the OOM and it happens infrequently enough that we don't have good historical data on it (this is changing going forward). 

Hoping that learning more about `OutOfMemoryException` will give me new insight into these issues.

**Comment by WebDancer69** [comment]
@jaredpar Did you figure out why you got the OOMs in Roslyn?

**Comment by jaredpar** [comment]
@WebDancer69 

@benaadams scenario is a plausible reason for why we get some of our customer reported OOMs (via say Watson). It's hard to verify though from a Watson that this is indeed the cause.

As for our unit tests I haven't found a good answer for that yet.

**Comment by jaredpar** [comment]
@WebDancer69 

@benaadams scenario is a plausible reason for why we get some of our customer reported OOMs (via say Watson). It's hard to verify though from a Watson that this is indeed the cause.

As for our unit tests I haven't found a good answer for that yet.

**Comment by danmosemsft** [comment]
I think this is answered @jaredpar. Please reopen if not.
