### ISSUE TITLE
Make sure that GenTree pointer is stored only in its parent.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#13293]
Right now we can have `fgArgInfo` that has `fgArgTabEntry` that points to a `GenTree`, so every time when we replace one tree with another we have to check for this case and do an expensive linear search in the arg info array. See `ReplaceOperand` for example.

We should get rid of any second edges to `GenTree`, so every time when we replace/remove a tree we need to update only one edge.

category:implementation
theme:ir
skill-level:expert
cost:large

**Comment by jakobbotsch** [comment]
This was fixed as a side effect of #67238.
