### ISSUE TITLE
[2.2] Potential native memory leak from EventPipe

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#13309]
Our microservices were growing at a rate of 40MB per hour (each) because of this issue.  We have turned off the Prometheus.Net collectors that hook up to the event sources as a temporary workaround (https://github.com/djluck/prometheus-net.DotNetRuntime/issues/6).

This is definitely **not** using a circular buffer as I have an instance that's been running for 9 days and is now at an approximate 7GB commit size and still growing!

I have confirmed .Net Core 3 - Preview 8 does not experience the same issue.  I have also confirmed that .Net Core 2.2.0 - 2.2.6 do experience the issue.  I have the same stack trace for the allocations as mentioned in the first reply above.

Please back-port the fix to .Net Core 2.2.

_Originally posted by @tylerohlsen in https://github.com/dotnet/coreclr/issues/23562#issuecomment-523592951_

**Comment by nurevaSaeed** [comment]
I'm experiencing this issue with .NET Core 3.1

This causes the Linux container to hit OOM. Running the app in VS in debugger has the same issue. 

Unfortunately, I cannot share my memory dump. But the summary is that I have the Azure Service Bus  lib in my app. The service bus lib tries to connect to the topic you specify. If the topic does not exists it keeps throwing exceptions indefinitely. This causes the AI to keep gobbling memory.

This also causes the container to fail to swap at release time bc it runs OOM.

**Comment by josalem** [comment]
Closing as the original issue was resolved
