### ISSUE TITLE
Consider ignoring SuppressIldasmAttribute in ILDASM

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#13341]
The `SuppressIldasmAttribute` instructs the ildasm tool to prevent working on assemblies or modules that have this attribute [over here][1].

I'd like to ask re-considering if this is necessary still and if the check can be removed, and documenting the attribute as obsolete.

Some motivation:

The attribute is, as many know, trivial to bypass. Practically every other disassembly tool ignores this attribute. As for why "Well why not keep using that tool" is because ildasm offers some benefits over other tools, such as quickly dumping the IL-text to disk and re-assembling.

The attribute conveys as sense of protection that is really not existent. If the desired outcome is to protect intellectual property, then they should be steered toward 3rd party solutions like a commercial obfuscator.

[1]: https://github.com/dotnet/coreclr/blob/5f0c2f35ec943fcc7a360f059af1fc5b2b9ce1f5/src/ildasm/dasm.cpp#L881-L894

**Comment by dotMorten** [comment]
> The attribute is, as many know, trivial to bypass. Practically every other disassembly tool ignores this attribute. As for why "Well why not keep using that tool" is because ildasm offers some benefits over other tools, such as quickly dumping the IL-text to disk and re-assembling.

I think this is the wrong argument. The attribute is not about security or completely preventing people from decompiling. It's about helping to keep the _honest_ people honest. A lot of commercial software (of not all of it), has a license that explicitly forbids your to decompile their code - regardless of whether it's possible or not. This attribute is useful for those products as it's another indicator that acts in support of this paper license. This especially becomes true with Visual Studio now offering users to decompile libraries when navigating to a definition. This attribute is there to prevent that from happening, as clicking yes to decompile instantly makes you violate that license agreement.

If producers of class libraries wants to make it easy for users to decompile their stuff, all they have to do is _not_ set this attribute on their assembly. Easy peasy. But don't obsolete this attribute, or have ildasm ignore it, or have VS's go-to-definition bypass it.

**Comment by mletterle** [comment]
> > The attribute is, as many know, trivial to bypass. Practically every other disassembly tool ignores this attribute. As for why "Well why not keep using that tool" is because ildasm offers some benefits over other tools, such as quickly dumping the IL-text to disk and re-assembling.
> 
> I think this is the wrong argument. The attribute is not about security or completely preventing people from decompiling. It's about helping to keep the _honest_ people honest.

It may be better to define a standardized `AssemblyMetadataAttribute` for this scenario, something like `[AssemblyMetadata("PlsNoDecompile")]` :P

**Comment by dotMorten** [comment]
@mletterle Aren't we just replacing one attribute with another to cover the exact same scenario?

**Comment by mletterle** [comment]
> @mletterle Aren't we then just replacing one attribute with another to cover the exact same scenario?

Yes, but it would not be `ildasm` specific so it would not seem wrong for `ildasm` to ignore it ;)

**Comment by GrabYourPitchforks** [comment]
FWIW, I believe ildasm and VS don't look for this specific attribute (as it exists in System.Private.CoreLib). I think you can define your own attribute with the same namespace & name in your own assembly, and the behavior today is that those tools will honor the attribute.

In practice, what this means is that if the *only* change we made was to remove this attribute from the reference assemblies, with no other functional changes, the tooling would continue to work as it does today.

**Comment by mletterle** [comment]
On a relevant note, maybe a good compromise is to add an opt-out argument to `ildasm` and have it match just on the attribute's simplename (ignoring namespace) and remove the attribute from CorLib. Users and protection tools could then inject their own versions of `SuppressIldasmAttribute` and "honest" developers could simply never use the opt-out argument.
