### ISSUE TITLE
Consider weakly caching large arrays in the ArrayPool

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#13344]
Currently there is a limit on arrays that ArrayPool can retain. The reason for that is to control over how much memory can be retained by the pool. That makes sense.

However, when user does Rent for an array larger than the limit, ArrayPool just delegates to `AllocateUninitializedArray` and when the array is returned, it is simply dropped. 

There is no problem with correctness here since the memory of the array will be eventually reclaimed by GC and then used again. However, since large arrays do not benefit from generational heuristics of the GC and there could be a substantial delay between the array becoming unreachable and being collected/swept. 
As a result, a rapid rent/return cycle of large arrays could have impact on the heap size due to "floating garbage".

This scenario can be mitigated by caching large arrays in the pool while referring to them weakly: 
-	Logically extend the buckets to the larger than the current limit size, but refer to the "large" arrays via weak references.
-	Do not count these towards the trim threshold since thy are not retained by the pool.
-	Do not trim them either since that would have no effect.

Since arrays need to be allocated anyways, this will not directly contribute to the heap size. However such arrays would be able to recycle without going through GC, when GC is not fast enough, thus masking GC latency.

**Comment by stephentoub** [comment]
All sizes up through 1B elements are now cached.
