### ISSUE TITLE
TextWriter.WriteLine(string? value)

### ISSUE THREAD

**Issue by bzd3y** [dotnet/runtime#13361]
`TextWriter.WriteLine(string? value)` doesn't use `TextWriter.WriteLine()` to append the new line to the string being written like all of the other overloads do. It uses the same code as `TextWriter.WriteLine()`: `Write(CoreNewLineStr)`.

This produces (in my opinion) unexpected override behavior in derived classes. Is this intentional or just something that got overlooked and can be fixed?

**Comment by carlossanlop** [comment]
Triage:
It was probably an oversight but it would be too risky to change.
Overriding `TextWriter.WriteLine(string? value)` to get the desired behavior is the only safe answer.
