### ISSUE TITLE
WeakReference<T> constructor should allow null

### ISSUE THREAD

**Issue by sharwell** [dotnet/runtime#13360]
I believe the two `WeakReference<T>` constructors should have `[AllowNull]` on the `T` parameter. This change makes it easier for clients to adopt nullable reference types, without any impact on use of `TryGetValue`.

https://github.com/dotnet/coreclr/blob/f821e2ac58f096bf5c5a830064345c5b16f1db27/src/System.Private.CoreLib/shared/System/WeakReference.T.cs#L22

**Comment by joperezr** [comment]
@stephentoub when you get a chance can you take a look at @sharwell last comment? If this is also not something we want to take I can go ahead and close this issue.

**Comment by stephentoub** [comment]
@MadsTorgersen / @jcouv, do you have an opinion here?  Implementation-wise, `WeakReference<T>(T target)` can accept null.  If a developer uses a non-nullable `T`, should there be a warning or no warning if a maybe-null value is passed?

**Comment by jcouv** [comment]
> Implementation-wise, WeakReference<T>(T target) can accept null.

I don't have a strong opinion, and I'm still not sure when one would want to pass `null` to the constructor, but this makes me lean towards `[AllowNull]`.

**Comment by MadsTorgersen** [comment]
I don't have a strong opinion either, but I am leaning in the direction of _not_ putting `[AllowNull]`. It seems to me that in an NRT enable world, a consumer of a `WeakReference<C>` would have an expectation that a `false` result from `TryGetTarget` means the target was collected, not that `null` was the target in the first place.

**Comment by stephentoub** [comment]
Thanks for the input.  Let's leave it as-is, then; no attribute.  If we get a lot of feedback about this being an issue, we can always add the attribute later to make it more permissive.  Adding the attribute now and then removing it could introduce warnings.
