### ISSUE TITLE
NYI ReadyToRunHelpers for IJW

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#13388]
Trying to R2R an IJW assembly hits the following unimplemented ReadyToRunHelpers. Missing helpers crash the compiler.
* Stelem_Ref
* PInvokeBegin
* PInvokeEnd

**Comment by trylek** [comment]
@mangod9 - I think we should move this issue to .NET 6 as to my knowledge .NET 5 isn't expected to ship support for Managed C++.

**Comment by mangod9** [comment]
yup makes sense. On a related topic there is a recent issue, where a mc++ assembly is not failing fast.

**Comment by trylek** [comment]
Thanks @mangod for the heads-up, I assume you're talking about https://github.com/dotnet/runtime/issues/39493. I am going to take a look shortly.

**Comment by trylek** [comment]
I believe this is basically a duplicate of https://github.com/dotnet/runtime/issues/38096, closing. Please reopen if you have concerns that the related issue doesn't fully capture the extent of the problem.
