### ISSUE TITLE
ReadyToRunCodegenNodeFactory cleanup / refactor

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#13386]
* This class has gotten very big and contains several groups of unrelated functionality;
* Usefulness of deriving from NodeFactory is questionable, it seems we're using just a fraction of its functionality and overlaps in the various helper names cause repeated aliasing issues;
* If it turns out to be possible to cleanly separate ReadyToRunCodegenNodeFactory from NodeFactory, we should either split it into several classes or at least make it a partial class living in several files:
    * CorInfoImpl utility functions for constructing the various helper cells and signatures;
    * Token collection and lookup engine;
* R2R header table collection management.

**Comment by trylek** [comment]
Some of the suggested cleanups have been carried out since and the rest don't seem super important, closing.
