### ISSUE TITLE
R2R calli breaks compilation because canGetCookieForPInvokeCalliSig isn't implemented

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#13387]
R2R Compiling a ```calli``` instruction triggers a call to ```canGetCookieForPInvokeCalliSig```, which throws a NotImplementedException and crashes compilation. This will block R2R for IJW. 

From a quick look at CoreCLR, ```canGetCookieForPInvokeCalliSig``` can probably just return true, but it will trigger another call to ```GetCookieForPInvokeCalliSig```, which would need to implement cookies.

**Comment by davidwrighton** [comment]
This has been fixed. It now throws a RequiresRuntimeJitException which will cause the compilation to fallback to JIT and work correctly.
