### ISSUE TITLE
Mutex.ReleaseMutex throwing on non-Windows operating systems

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#13403]
Context: https://github.com/dotnet/roslyn/issues/37974 and https://github.com/dotnet/roslyn/issues/38420

Roslyn is getting several reports of crashes on non-Windows operating systems when calling [Mutex.ReleaseMutex](https://docs.microsoft.com/en-us/dotnet/api/system.threading.mutex.releasemutex?view=netframework-4.8). The method is throwing an `ApplicationException` indicating that the non-owning thread attempted to dispose of the value. 

Looking though the code where we acquire and release the `Mutex` is synchronous and can be [seen here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Shared/BuildServerConnection.cs#L132-L181). The code does reside in an `async` method but the `await` operation occurs after this block. I do plan to factor the sync part out to make it clearer but the code is operating synchronously as written.

Is there reason by which `Mutex.ReleaseMutex` would throw an exception? Or perhaps a known issue that we could be running into. A bit stumped on how to proceed with this issue.

**Comment by stephentoub** [comment]
@jaredpar, I see back in September you have a commit adding more logging.  Has this issue happened again?  Any more detailed information arise from that logging?

**Comment by jaredpar** [comment]
@stephentoub 

No we haven't had any other reports of this problem.

**Comment by stephentoub** [comment]
Ok, thanks. I'll close this for now, as it doesn't seem actionable right now without more data.
