### ISSUE TITLE
add a condemned reason field to gc_history_global and corresponding tooling support

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#13406]
most of the condemned gen decision happens per heap so it's in gc_heap::generation_to_condemn, but a few decisions are made globally especially with the addition of the hardlimit support in gc_heap::joined_generation_to_condemn. so we should add a global condemned reason. tooling like TraceEvent will need to know about it.

**Comment by cshung** [comment]
Fixed through https://github.com/dotnet/runtime/pull/1042 and https://github.com/microsoft/perfview/pull/1075
