### ISSUE TITLE
ZipArchiveEntry.ExtractRelativeToDirectory - issue with trailing space

### ISSUE THREAD

**Issue by michalpenka** [dotnet/runtime#1341]
If `destinationDirectoryName` parameter of `ZipArchiveEntry.ExtractRelativeToDirectory` method contains trailing space(s) in front of the path delimiter, two directories are created: one with and one without a trailing space. The extracted content is in the one with the trailing space.

Code to reproduce below, notice the trailing space in the destination directory name:
`ZipFile.ExtractToDirectory("fileSpace .zip", @"C:\temp\fileSpace \", true);`

As per remarks in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.createdirectory?view=netcore-3.1) of  `DirectoryInfo.CreateDirectory(String)`, which is used in `ExtractRelativeToDirectory` method, the trailing spaces in the directory name are omitted. This is not true if the path delimiter is explicitly provided at the end of the path though and I believe the ExtractRelativeToDirectory should follow the same.

**Comment by carlossanlop** [comment]
Trailing spaces in file/folder names are allowed by Windows but are considered an edge case that needs to be handled in a special way:
https://support.microsoft.com/en-us/help/320081/you-cannot-delete-a-file-or-a-folder-on-an-ntfs-file-system-volume

> ### _You cannot delete a file or a folder on an NTFS file system volume_
> ...
> #### _Cause 6: The file name includes an invalid name in the Win32 name space_
>_You may not be able to delete a file if the file name includes an invalid name (for example, the file name has a trailing space or a trailing period or the file name is made up of a space only). To resolve this issue, use a tool that uses the appropriate internal syntax to delete the file. You can use the "\\?\" syntax with some tools to operate on these files, for example:_
> `del "\\?\c:\path_to_file_that contains a trailing space.txt "`
> ...

As suggested in the first paragraph, you need to use a full UNC path:

```cs
ZipFile.ExtractToDirectory(@"fileSpace .zip", @"\\?\C:\temp\fileSpace \", true);
```

I ran this and it works.

cc @JeremyKuhne

**Comment by carlossanlop** [comment]
@michalpenka the provided workaround is the expected way of making trailing spaces work with paths, so I'll close this issue since we don't expect to take any changes around that.
