### ISSUE TITLE
Can't attach to ASP.NET Core application when hostingModel is "InProcess" and .NET CLR version was selected

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#13436]
The attach to `w3wp.exe` which contains .NET Core v3.0.100-rc1 inside (ASP.NET Core v3 application where `web.config` has `hostingModel="InProcess"` ) hangs till the timeout when the IIS application pool configured in the following way:
![netf](https://user-images.githubusercontent.com/2767027/65134987-7db1b280-da05-11e9-8955-f55083c7ba31.png).
The server diagnostic thread in `w3wp.exe` is waiting for incoming connection in `ConnectNamedPipe`:
```
  35  Id: 492c.3dd8 Suspend: 1 Teb: 000000b2`c3498000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000b2`c467f6c8 00007ff8`91965b99 ntdll!NtFsControlFile+0x14
01 000000b2`c467f6d0 00007ff8`49ac225b KERNELBASE!ConnectNamedPipe+0x79
02 000000b2`c467f740 00007ff8`49ad39a4 coreclr!IpcStream::DiagnosticsIpc::Accept+0x7b [f:\workspace.2\_work\1\s\src\debug\debug-pal\win\diagnosticsipc.cpp @ 64] 
03 000000b2`c467f7a0 00007ff8`953c4034 coreclr!DiagnosticsServerThread+0xa4 [f:\workspace.2\_work\1\s\src\vm\diagnosticserver.cpp @ 51] 
04 000000b2`c467f850 00007ff8`955b3691 KERNEL32!BaseThreadInitThunk+0x14
05 000000b2`c467f880 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```
It looks like the server pipe has wrong access rights in this case. It's the reason of timeout in the client application.

The attach works properly when the .NET CLR version set to "No Managed Code":
![no](https://user-images.githubusercontent.com/2767027/65135247-e1d47680-da05-11e9-9128-a61a55a0a712.png)

The detail repro case is here https://youtrack.jetbrains.com/issue/PROF-903.

**Comment by tommcdon** [comment]
Hi @ww898, we are triaging diagnostics issue for .NET 6 and are curious if this is still a problem, or has been narrowed down to a runtime issue.

**Comment by ww898** [comment]
Hi @tommcdon, I can check the issue tomorrow with .NET Core 5.0 RC2.

**Comment by ww898** [comment]
@tommcdon Our QA reproduced the issue with .NET Core 5.0-rc2 today.

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
@ww898 can you both the successful scenario and the failing scenario and provide the output for `gci \\.\pipe\ | findstr dotnet`? That will show us if the app pool suggestion Noah made is right.

**Comment by ww898** [comment]
With error in attach:
```
PS C:\WINDOWS\system32> gci \\.\pipe\ | findstr dotnet
------          1/1/1601   3:00 AM              1 dotnet-diagnostic-6200
```

Without error in attach:
```
PS C:\WINDOWS\system32> gci \\.\pipe\ | findstr dotnet
------          1/1/1601   3:00 AM              1 dotnet-diagnostic-10080
```

**Comment by davmason** [comment]
@ww898 this behavior is due to permissions issues. I set up a repro machine, and running as a regular user I cannot attach dotnet-trace to the process, but when running as adminstrator I can. Can you verify if running as administrator allows you to attach?
