### ISSUE TITLE
[ThreadPool] OOM during gate thread creation and worker thread creation could stall the thread pool

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#13437]
The gate thread is meant to retry worker thread creation periodically, but it also exits when there is no work. When both can't be created due to OOM, work items may not be processed. When a work item is queued, the thread pool would retry creating threads, but in an app that uses the thread pool only for timers, new work items would not be queued and the app would stop processing timer callbacks. Could consider keeping the gate thread alive always such that it can periodically retry creating threads as necessary (as it already does when it is running), but without waking up unnecessarily when there is no work.

**Comment by stephentoub** [comment]
@kouvel, is this something you're planning on addressing in 5.0?  If not, can you please update the milestone?  Thanks!

**Comment by kouvel** [comment]
I would like to fix this in 5.0, keeping it there for now
