### ISSUE TITLE
Remove System.CommandLine dependency

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#13470]
System.CommandLine is a corefxlab package that got abandoned. We shouldn't use it in shipping products.

**Comment by trylek** [comment]
@AntonLapounov - can we close this item based on your https://github.com/dotnet/runtime/pull/43655?

**Comment by AntonLapounov** [comment]
We need to switch ILVerify as well.

**Comment by MichalStrehovsky** [comment]
This issue originally tracked getting rid of the CoreFXLab System.CommandLine since that one is unsupported and we wouldn't be able to service it in shipping products. Since then, we found out that the "new" System.CommandLine sucks perf-wise and we're better off taking the sources of System.CommandLine from CoreFXLab and running with them (and servicing them ourselves).

I see that both ILVerify and R2RDump got switched over to the "new" System.CommandLine. Since I don't think we have specific concerns about startup perf of either of those and neither is a shipping product, I think these are fine as-is.

I would close this. It would be nice to get rid of the "new" System.CommandLine dependency for consistency, but I don't believe it meets the bar for a Milestone 6.0.0 issue.

**Comment by trylek** [comment]
@AntonLapounov, do you agree with Michal's suggestion to close this issue for now? Or would you prefer to keep it and just re-target it to "future" i.o.w. remove it from the envisioned scope of work for .NET 6?

**Comment by AntonLapounov** [comment]
@trylek I am fine with closing this one. We can use #42637 to track the issue with ILVerify.
