### ISSUE TITLE
TaskFactory.CommonCWAnyLogic

### ISSUE THREAD

**Issue by EynsherKiel** [dotnet/runtime#13503]
Hello!

I want to use CommonCWAnyLogic, what do you think about it? That method can removed or changed, but Task.WhenAny always copy array.

**Comment by stephentoub** [comment]
This functionality is exposed through both Task.WhenAny and TaskFactory.ContinueWhenAny. The cited method is just an internal helper to consolidate the implementation, and we don't plan to expose that implementation detail. Thanks.
