### ISSUE TITLE
Review crossgen documentation page for R2R scenarios

### ISSUE THREAD

**Issue by fadimounir** [dotnet/runtime#13510]
There are some areas that need to be reviewed, and make sure that we distinguish between fragile NIs and R2R images (ex: when loading .dlls, the runtime won't automatically load the .ni.dll R2R images even if it lives next to the .dll)

**Comment by mangod9** [comment]
@nattress could you please take a look if any doc updates are still required here?

**Comment by davidwrighton** [comment]
@mangod9 I don't actually know which docs are referred to here. Do you have context?

**Comment by mangod9** [comment]
No I dont have much context, just moved this issue over since it was assigned to Fadi. Perhaps the original intent was to discuss Fragile images, but from Jan's comment above not something which we should doc. Guess ok to close for now.
