### ISSUE TITLE
[crossgen2] Making sure Vector64/128/256 are not generated unless CoreLib is part of the version bubble

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#13522]

**Comment by mangod9** [comment]
@janvorli is there anything actionable here?

**Comment by janvorli** [comment]
I believe @davidwrighton has fixed that in one of his changes a long time ago, but I am not 100% sure.

**Comment by davidwrighton** [comment]
I'll look into this in depth tomorrow.

**Comment by davidwrighton** [comment]
This didn't get implemented, but I've just put together a PR that identifies where the ABI may be unstable and surgically disables code gen for those cases. It preserves the ability to use Vector intrinsics even in the presence of unstable abi.
