### ISSUE TITLE
'Vector{nnn}.Create' methods have non ideal codegen for `CreateScalar`

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#13525]
Current codegen for `Vector128.CreateScalar(float|double)` and `Vector256.CreateScalar(float|double)` is sub par.
Ideal codegen would be

```x86asm
vxorps xmm0, xmm0, xmm0
vmovss xmm0, [src]
```

however, the [currently generated code](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8ovLrl5hcAbhr0mrTj36CRGMRKm4WADQAcSOdXkBmBt1zYAZjCakGAYQY0A3jQaem55kgYA1GDAMaHJSfQAeawAbCGwMAD4nWHiYAGUwbGjsKDD9AAoYuIwAKgYABwBKF2ovBndauq9iAHYAoJDc8JZHFIx0zOyofJKq4zqAXw8vac9iH3I/QODoUgBWJCjY+KTemFSMrJz1pELt0orq2frrutb2lagTnr6Bo+HRyvGvKeoJoA==) for `Vector128.CreateScalar(float)` is

```x86asm
vmovss xmm0, dword [src]
vxorps xmm1, xmm1, xmm1
vmovss xmm0, xmm1, xmm0
```

(exact same for ideal and generated with `double`, just `sd/pd` instead

which is less efficient.

This also applies to `Vector256.CreateScalar(float|double)`.

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Referenced https://github.com/dotnet/runtime/issues/10033 was closed with https://github.com/dotnet/runtime/pull/35857; closing
