### ISSUE TITLE
Process.Modules doesn't return the full module list of a Windows process when the architecture of the Process and the program don't match

### ISSUE THREAD

**Issue by Dewera** [dotnet/runtime#1353]
Currently accessing the `Modules` property of a `Process` class doesn't return the full list of modules when the architecture of the `Process` doesn't match that of the compiled architecture of the program.

As an example, if a WOW64 process is running and you create a program that is compiled under x64 and create a Process object around the WOW64 process, when you access `Process.Modules` you will only be able to see the x64 modules i.e. the x64 version of ntdll and the accompanying wow64 DLLs. 

If I remember correctly, the current runtime uses `EnumProcessModules` to resolve a module list of a remote process. This API call unfortunately doesn't parse both PEB's of a WOW64 process for a complete module list, hence why the module list is incomplete in the `Process` class.

**The solution that I propose**

Use `CreateToolhelp32Snapshot` with the `TH32CS_SNAPMODULE` and `TH32CS_SNAPMODULE32` flags accompanied by `Module32First` and `Module32Next`

This will always get a full module list for the process regardless of if the architecture of the process and program match as opposed to `EnumProcessModules` and also doesn't require any manual parsing of the PEB(s)

**Comment by Symbai** [comment]
This would be a breaking change since it has this behavior probably since the first .NET version. See also https://github.com/dotnet/runtime/issues/1287

**Comment by Dewera** [comment]
Not sure if I would classify this as a breaking change as all the information that originally existed in the property would still be there, with the addition of the 32 bit modules if your `Process` object represented a WOW64 process and you were compiled under x64.

If the process architecture is being considered to be added to the object then would not make sense to implement this change? I can just see it being quite confusing for a lot of people if they create a Process object and have the architecture property marked as WOW64 only for the module list to reflect the true list of modules.

If nothing else there should be a warning in the documentation explicitly stating that this is the case, however, I don't personally believe it is good to force people to compile their application as x86 just so they can access the module list of a WOW64 process when a solution to do so already exists.
