### ISSUE TITLE
Unable to retrieve types from a referenced Assembly

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/runtime#13536]
I'm attempting to use reflection to identify classes marked with a given attribute in an assembly that is referenced but no type in the assembly seems to show up unless a type in the assembly is first created/used? can someone please advise how I may find classes with a given attribute in a referenced assembly without first used a type in the same assembly?

**Comment by GrabYourPitchforks** [comment]
Like David said, using a plugin model is the best solution for this scenario. You'll be able to load assemblies dynamically at runtime (such as from a specific folder) and inspect their attributes and types to light up implementations.
