### ISSUE TITLE
add `compilationNumber` field to `Compiler*` and use it for dumps.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#13534]
We should create a Compiler member that captures this once and then use that for all output, and use InterlockedIncrement to update this static.

_Originally posted by @BruceForstall in https://github.com/dotnet/coreclr/pull/27017_

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

**Comment by sandreenko** [comment]
@kunalspathak have not you fixed than recently?

**Comment by kunalspathak** [comment]
I have added a field to capture methodNum in https://github.com/dotnet/runtime/pull/32578. Is it different from `compilationNumber`?

**Comment by AndyAyersMS** [comment]
Seems like it is the same concept, so I'm going to close this.
