### ISSUE TITLE
Announcement: Consolidated repo names

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#13550]
[ann]: https://github.com/dotnet/coreclr/issues/26175

As we announced earlier, we're [planning on consolidating][ann] some of the repositories in the dotnet org. While this is still work in progress, we'd like to give you an update on where we are.

So far, we've identified the following repos:

* dotnet/**runtime**
	- Will contain [coreclr](https://github.com/dotnet/coreclr), [corefx](https://github.com/dotnet/corefx), [core-setup](https://github.com/dotnet/core-setup), [aspnet/Extensions](https://github.com/aspnet/Extensions), and some of [mono/mono](https://github.com/mono/mono)
* [dotnet/**sdk**](https://github.com/dotnet/sdk)
	- Will contain [toolset](https://github.com/dotnet/toolset), [sdk](https://github.com/dotnet/sdk), [cli](https://github.com/dotnet/cli)
* dotnet/**installer**
	- Renamed from [core-sdk](https://github.com/dotnet/core-sdk)
* dotnet/**aspnetcore**
	- Moved from [aspnet/AspNetCore](https://github.com/aspnet/AspNetCore) and will also contain [aspnet/AspNetCore-Tooling](https://github.com/aspnet/AspNetCore-Tooling)
* dotnet/**efcore**
	- Moved from [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore)
* [dotnet/**winforms**](https://github.com/dotnet/winforms)
	- Unchanged, but listed for clarity
* [dotnet/**wpf**](https://github.com/dotnet/wpf)
	- Unchanged, but listed for clarity

### Name changes

You might notice that we changed our mind on naming from our [earlier announcement][ann]. Based on your feedback, we decided to go with **dotnet/runtime** instead of **dotnet/platform** and **dotnet/sdk** instead of **dotnet/cli**.

Several people pointed out that the previous names weren't relatable to how we talk about the product, for example on download pages. So, we decided to match the product distributions as the primary design point for the new names. We generally refer to the bits you need to run your app as *the runtime* and the bits you need to build apps as *the SDK*. This also matches the naming chosen by other platforms.

### New repos can't be used for .NET Core 3.x or earlier

The consolidated repositories are going to be about .NET 5 and going forward. It will not be possible to build .NET Core 3.1 or earlier from these repositories. As such, only the master branch from each of the repositories will be brought forward. There will be no porting of the individual release branches in the source repositories.

### Personal names and email addresses

Since we're planning on rebasing the history in the merged repositories, we can map your name and email address to new values as well. We primarily do this to support our friends in the LGBTQ+ community who have changed their names to reflect their identities. However, anybody is welcome to use this to change their email and name.

Whatever your reason might be: we value your contributions and we hope this small gesture makes your life a little bit better. So if you changed your name/email – or simply prefer us to use different values – please [submit a request](mailto:dotnet@microsoft.com&subject=.NET%20repo%20consolidation%3A%20request%20for%20name%20change&body=Hey%2C%20%0A%0AI%E2%80%99d%20like%20to%20change%20my%20email%2Fdisplay%20name%20in%20the%20consolidated%20repo%20from%20%0A%0A%20%20%20%20%20%20%20%20My%20Old%20Name%20%3Cold.me%40example.org%3E%20%0A%0Ato%20%0A%0A%20%20%20%20%20%20%20%20My%20New%20Name%20%3Cnew.me%40example.org%3E%20%0A%0AThanks%21%20%0A).

### More is coming

We'll share more updates in the upcoming months. Please let us know of any concerns that we haven't addressed yet!

**Comment by Varorbc** [comment]
@terrajobst why not move core-sdk to sdk repo?

**Comment by terrajobst** [comment]
> @terrajobst why not move core-sdk to sdk repo?

Because it really contains the setup/installer.

**Comment by danmosemsft** [comment]
This issue has served its purpose.
