### ISSUE TITLE
Random freezes with using TryStartNoGCRegion

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/runtime#13572]
Following up on  dotnet/runtime#6526 and @mattwaren's [blog post](https://mattwarren.org/2016/08/16/Preventing-dotNET-Garbage-Collections-with-the-TryStartNoGCRegion-API/). 

We've been observed large (>20 seconds) random pauses when using TryStartNoGCRegion on a aspnetcore3.0 endpoint - similar CPU usage to what is mentioned in dotnet/runtime#8656 - with 1 core at 100%.

Expected behavior (and observed on smaller instances or running on windows) is no extra delay when calling GC.TryStartNoGCRegion( ..., disallowFullBlockingGC:false). 

If it helps, the setup is:
- GC mode: Background Concurrrent Server
- RHEL6 - tried already to disable large pages, no change
- Docker container, limited to30 CPUs, 300GB RAM
- Used memory at rest ~50GB (so plenty of free RAM)

The issue happens even on a clear restart of the container and/or server, so it doesn't seem related to memory fragmentation.

It seems like the issue is triggered by having two requests in sequence calling into TryStartNoGCRegion - I'm assuming from multiple threads. Only solution we found for now is to stop using TryStartNoGCRegion - but this still leads to random (even if infrequent) GC pauses on this endpoint - which is undesirable for the application - specially when there is still plenty of RAM free for the container.

From @maoni0's [comment](https://github.com/dotnet/coreclr/issues/6809#issuecomment-241842292):

> First of all, people are not calling the NoGCRegion API all the time so we can be afford to sacrifice a bit of perf in exchange of code simplicity. Secondly, we might need to do what I call a "minimal gc" which is just to add a new segment. For that we do want to suspend threads.

It is also a bit confusing when is NoGCRegion supposed to be used. How much of a performance  impact is acceptable / expected for using NoGCRegion? If this hangs are expected behavior, maybe some clarification on the docs would be helpful.

**Comment by mangod9** [comment]
@theolivenbaum are you able to repro this on latest versions of the runtime? Ideally on .net 5?

**Comment by theolivenbaum** [comment]
Have to check, to be honest haven't seen this issue on our code since netcore3.1, but will double check if we just didn't remove the calls all together.

**Comment by mangod9** [comment]
ok thanks, please let us know, else will close the issue. Thx.

**Comment by mangod9** [comment]
closing for now based on above. Please reopen if you repro it again. Thanks
