### ISSUE TITLE
Finish adding back arm intrinsics that existing before refactoring

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#13575]
dotnet/coreclr#25508 did a large refactoring of the ARM intrinsic infrastructure.

There were a number of the AdvSimd APIs that were not exposed in order to help keep the PR small. These APIs should be re-exposed in the appropriate location:
- [ ] And
- [ ] AndNot
- [x] BitwiseSelect
- [x] CompareEqual
- [x] CompareEqualZero
- [x] CompareGreaterThan
- [ ] CompareGreaterThanZero
- [x] CompareGreaterThanOrEqual
- [ ] CompareGreaterThanOrEqualZero
- [x] CompareLessThan
- [ ] CompareLessThanZero
- [x] CompareLessThanOrEqual
- [ ] CompareLessThanOrEqualZero
- [x] CompareTest
- [ ] Divide
- [ ] Extract
- [ ] Insert
- [x] LeadingSignCount
- [x] LeadingZeroCount
- [ ] Max
- [ ] Min
- [ ] Multiply
- [ ] Negate
- [x] Not
- [x] Or
- [x] OrNot
- [x] PopCount
- [ ] Sqrt
- [ ] Subtract
- [ ] Xor

category:implementation
theme:vector-codegen
skill-level:expert
cost:medium

**Comment by echesakovMSFT** [comment]
The remaning intrinsics (Extract and Insert) that are left unimplemented tracked by #24588

We decided not expose comparison operations with zero and instead implement functionality in the JIT that would allow to determine when one of the operands is either `Vector128<T>.Zero` or `Vector64<T>.Zero` and choose an appropriate encoding based on that analysis.
