### ISSUE TITLE
Add tests for remaining ARM intrinsics

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#13570]
https://github.com/dotnet/coreclr/pull/25508 did a large refactoring of the ARM intrinsic infrastructure.

There were a few APIs that are no longer exposed that should be and there were a few APIs (namely ArmBase) that didn't have tests added.

The PR was merged to unblock other work going on and this is just tracking tests being added for the APIs exposed that don't have them yet.

category:implementation
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
@tannergooding @echesakovMSFT Is this bug still required, or has the appropriate work been done?

If it is still active, it might be helpful if the bug were more explicit about the work remaining to be done.

**Comment by tannergooding** [comment]
I believe they have all been covered now. I will give it a pass and update shortly.

**Comment by echesakovMSFT** [comment]
I believe I added all of the missing tests and intrinsics

**Comment by tannergooding** [comment]
Yes. Looks like everything is covered now.
