### ISSUE TITLE
PR testing (coreclr-ci) has an unstable job that is not part of coreclr-outerloop

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#13596]
[CI PR testing](https://dev.azure.com/dnceng/public/_build?definitionId=228&_a=summary) has `Run Test Pri0 CoreFX Windows_NT x64 checked` that sometimes fails with test timeouts ([example ](https://dev.azure.com/dnceng/public/_build/results?buildId=390097&view=ms.vss-test-web.build-test-results-tab&runId=12097244&resultId=165634&paneView=debug)),
that job is not part of [coreclr-outerloop](https://dev.azure.com/dnceng/public/_build?definitionId=98&_a=summary) that is tracked for ci health measurements.

Because of that outerloop testing is not a superset of PR testing and it makes PRs testing more unstable than outerloop.

**Comment by jashook** [comment]
Outdated.
