### ISSUE TITLE
CrossGen can't support GCPOLL_INLINE

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#13591]
During the [suppress GC transition](https://github.com/dotnet/coreclr/pull/26458) work, it was discovered that CrossGen can't support indirect memory addresses that are required for `GCPOLL_INLINE`. This work was discussed with @davidwrighton and attempted, but was blocked by issues referenced in https://github.com/dotnet/coreclr/issues/27186.

/cc @davidwrighton @MichalStrehovsky @sergiy-k

**Comment by erozenfeld** [comment]
@jkotas #13582 is done so should be unblocked.
