### ISSUE TITLE
EventSource.GetGuid can differ from EventSource.Guid

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#1360]
If you write an EventSource that specifies a name dynamically in the constructor but does not provide the name statically in an EventSource attribute then GetGuid(Type) and the Guid property will compute different values. The GetGuid(Type) return value no longer correlates to the GUID used to register the EventSource with ETW. Although it is intended that users will provide the EventSourceAttribute in this scenario nothing enforces that they do so.

I don't see any obvious way to change the API design to mitigate this issue without also introducing the potential for compat problems, but at minimum we should make the requirements clear in the docs, such as where GetGuid() is described and on the constructors that take a string name.

**Comment by noahfalk** [comment]
Adding repro case:
using System;
using System.Diagnostics.Tracing;
 
namespace GuidProblemRepro
{
    class Program
    {
        static int Main(string[] args)
        {
            Console.WriteLine("Hello World!");
 
            MyEventSource mes = new MyEventSource();
 
            Console.WriteLine( "                                        mes.Guid: {0}", mes.Guid );
            Console.WriteLine( "MyEventSource.GetGuid( typeof( MyEventSource ) ): {0}", MyEventSource.GetGuid( typeof( MyEventSource ) ) );
 
            return 0;
        }
 
 
        private class MyEventSource : EventSource
        {
            public MyEventSource()
                : base( "Microsoft.Blah.WhateverEventSource",
                        EventSourceSettings.EtwSelfDescribingEventFormat | EventSourceSettings.ThrowOnEventWriteErrors )
            {
            }
 
            [Event( 1 )]
            public void WriteMessage( string msg )
            {
                WriteEvent( 1, msg );
            }
        } // end class MyEventSource
    }
}

**Comment by tommcdon** [comment]
FYI @sywhang as this is a documentation issue
