### ISSUE TITLE
HashSet<T>.Remove(T) should allow nulls

### ISSUE THREAD

**Issue by Logerfo** [dotnet/runtime#1361]
`Remove(null)` does not throw an exception, only returns `false`. It doesn't make sense to warn the caller when the input may be null.

**Comment by Gnbrkm41** [comment]
```
#nullable enable
HashSet<string?> hashSet = new HashSet<string?>();
hashSet.Remove(null);
```
seems to work fine? it should allow nulls as long as T is nullable. How does it warn you?

**Comment by stephentoub** [comment]
Right.  If you want to use nullable values, TValue should be nullable.

**Comment by Logerfo** [comment]
The point is that `TValue` is not nullable in my case, but I don't see a reason to necessarily expect a `notnull` value as input for the `Remove` method, since it will only return `false` and the program execution can go on.

**Comment by stephentoub** [comment]
HashSet's implementation allows null values, not just for Remove, but for Add, TryGetValue, etc.  The nullable reference types language feature is layered on top, and you get to decide based on the type of TValue whether you want the language to warn you if you're potentially passing null where you explicitly stated you didn't want to allow null.  If you're declaring TValue as non-nullable, then the compiler is dutifully warning you when you pass null.  If you want to be able to pass null without warning, you need to make TValue nullable.  This is the design of nullable reference types.
