### ISSUE TITLE
Unexpected application crash (internal error in the .NET Runtime)

### ISSUE THREAD

**Issue by cheesi** [dotnet/runtime#13638]
Hello!

I expected a kind of strange issue on one of our test clients.
There was only this message in the event log:
![image](https://user-images.githubusercontent.com/5590254/67486392-3e156080-f66c-11e9-9d02-b102db963c82.png)

Error message: `The process was terminated due to an internal error in the .NET Runtime at IP 000007FEF7794523 (000007FEF75E0000) with exit code c0000005.`

There was no other error message, and it wasn't logged into our log file.

I honestly don't know where to start, so I will provide some Information about or application:
ASP.NET Core Application, running as Windows Service. Running .NET Core 3.0 on Windows 7 x64.

Please let me know, if there is anything I can do to help to resolve this issue. (And no, I cannot reproduce it, it hit a single time in about 1-2 weeks)

**Comment by mangod9** [comment]
@cheesi checking in to see if you have been able to get dump for this issue?

**Comment by cheesi** [comment]
Unfortunately, we were not able to reproduce this issue. So no, I don't have a dump for this issue.

**Comment by mangod9** [comment]
ok, thanks for your response. Is it ok to close the issue since its been a few months without a repro? Thanks!

**Comment by cheesi** [comment]
Yeah, I think, we can close it.
