### ISSUE TITLE
Determine what to do with "async ValueTask" caching

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#13633]
PR https://github.com/dotnet/coreclr/pull/26310 added in an experimental feature, guarded by an environment variable feature flag, that uses cached objects behind the scenes to implement `async ValueTask` and `async ValueTask<T>` methods.  For .NET 5, we need to decide how to proceed with this feature:
1. Delete it
2. Keep it as opt-in
3. Keep it as opt-out
4. Always on (delete the fallback)

We need more data to decide how to proceed, and in particular:
- Are there workloads where it yields a significant performance benefit when it's enabled?
- Are there workloads where it measurably harms performance when it's enabled?
- What kind of impact does it have on code size in a representative app?
- What is a good strategy to use for the employed cache?

If we decide to keep it, and especially if we decide to keep it as opt-out or always-on, we also need to validate diagnostics, in particular tracing to ensure we're not regressing anything impactful.

Functionally, there's also a behavior change associated with it.  While `ValueTask`/`ValueTask<T>` are documented to only be used in very specific ways, the fact that instances produced by `async` methods before .NET 5 were backed by `Task` meant that you could get away with violating the contract.  This change generally ends up requiring that the contract be enforced.  We would want to ensure we had good analyzers in place to help catch any misuse: https://github.com/dotnet/corefx/issues/40739.

#### Please try out the bits with your app and share your results: throughput, memory load, etc.

To enable the feature, set the `DOTNET_SYSTEM_THREADING_POOLASYNCVALUETASKS` environment variable to either `1` or `true`.

This will only impact `async ValueTask` and `async ValueTask<T>` methods, so you may also want to look through your code to switch some internal and private `async Task`/`async Task<T>` methods to instead use `ValueTask`/`ValueTask<T>`... just make sure to only do so when the consumers abide by the rules, which is that an instance must only be consumed once: if callers are doing anything other than directly awaiting the result of the method, be careful.

**Comment by benaadams** [comment]
Initial test [(code)](https://gist.github.com/benaadams/cd2969e13c582ab4070489b5c585024e)  for HttpClient with http; its quite light on async depth, Tasks aren't the dominant form of allocation and they can't be completely removed (public api); however it does make a difference.

On of the things I like about this pooling is the lifetime of async statemachines is very indeterminate compared to a lot of other allocations. They aren't long life in terms of cpu, but are in terms of elapsed time which means they end up moving to higher GC generations perhaps more than the "sync" style of async programming would suggest.

`master` (Task)
```
Threads: 1, Request/s: 11,478.0, Time: 87,122 ms, Allocated/Request: 3,200
Threads: 2, Request/s: 24,753.7, Time: 40,398 ms, Allocated/Request: 3,200
Threads: 3, Request/s: 40,130.3, Time: 24,918 ms, Allocated/Request: 3,200
Threads: 4, Request/s: 50,418.6, Time: 19,833 ms, Allocated/Request: 3,199
```

`PR` https://github.com/dotnet/runtime/pull/31623 (ValueTask) `SET DOTNET_SYSTEM_THREADING_POOLASYNCVALUETASKS=0`
```
Threads: 1, Request/s: 11,308.8, Time: 88,426 ms, Allocated/Request: 3,200
Threads: 2, Request/s: 24,235.0, Time: 41,262 ms, Allocated/Request: 3,200
Threads: 3, Request/s: 39,305.8, Time: 25,441 ms, Allocated/Request: 3,200
Threads: 4, Request/s: 50,888.5, Time: 19,650 ms, Allocated/Request: 3,199
```

`PR` https://github.com/dotnet/runtime/pull/31623 (ValueTask) `SET DOTNET_SYSTEM_THREADING_POOLASYNCVALUETASKS=1`
```
Threads: 1, Request/s: 11,424.4, Time: 87,531 ms, Allocated/Request: 3,024
Threads: 2, Request/s: 25,417.1, Time: 39,343 ms, Allocated/Request: 3,024
Threads: 3, Request/s: 41,144.7, Time: 24,304 ms, Allocated/Request: 3,024
Threads: 4, Request/s: 52,013.2, Time: 19,225 ms, Allocated/Request: 3,025
```

```json
"configProperties": {
  "System.GC.Server": true,
  "System.GC.HeapHardLimit": 20971520
}
```

**Comment by mgravell** [comment]
I wasn't able to get my previous bits updated to .NET 5 (too many moving parts), however: here's an update that I did using RESP using @davidfowl's "Bedrock" pieces (with some minor tweaks to make it run on the .NET 5 version of the Kestrel API):

## Baseline (environment variable `0`):

Name	Total (Allocations)
 - System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1	73808
 - System.Threading.QueueUserWorkItemCallbackDefaultContext`1	24601

``` txt
c:\Code\Bedrock.Resp\tests\SimpleClient>dotnet run -c Release
Enabled: 0
ExecuteBedrock: time for 25000 ops (val-type): 2162ms

c:\Code\Bedrock.Resp\tests\SimpleClient>dotnet run -c Release
Enabled: 0
ExecuteBedrock: time for 25000 ops (val-type): 2171ms
```

---

## Comparison (environment variable `1`):

Name	Total (Allocations)
 - System.Threading.QueueUserWorkItemCallbackDefaultContext`1	24909

``` txt
c:\Code\Bedrock.Resp\tests\SimpleClient>dotnet run -c Release
Enabled: 1
ExecuteBedrock: time for 25000 ops (val-type): 2166ms

c:\Code\Bedrock.Resp\tests\SimpleClient>dotnet run -c Release
Enabled: 1
ExecuteBedrock: time for 25000 ops (val-type): 2171ms
```

---

So: no noticeable negative impact on perf, but a big reduction in allocs. The `QueueUserWorkItemCallbackDefaultContext` is a known thing that is being handled separately. Basically, this makes things zero-alloc as expected. Nice work, if we can keep it!

**Comment by stephentoub** [comment]
Thanks, @mgravell. One of the issues here is that allocations are for the most part a secondary indication of perf, in that the hope is that by reducing allocation, you improve throughout. But here to reduce allocation, we're pooling, which has its own costs. So a decrease in allocations that doesn't improve throughput at all isn't necessarily a win, especially if it brings with it other downsides. It'd be great if you can try out real workloads when you get a chance to see if there's any meaningful gain.

**Comment by davidfowl** [comment]
Does the working set get better as a result? You should be able to run dotnet counters before and after to get a glimpse of what the metics look like.

**Comment by stephentoub** [comment]
(Working set is good to look at it, but working set improvements could also instead suggest tweaks to GC configuration, as such pooling should primarily help working set if the GC has determined it's not worth doing a collection yet.  Even so, as David suggests, it's a good data point.)

**Comment by YairHalberstadt** [comment]
Thought I'd add a link to your blogpost here @stephentoub:

https://devblogs.microsoft.com/dotnet/async-valuetask-pooling-in-net-5/

**Comment by stephentoub** [comment]
Thanks, @YairHalberstadt.

**Comment by aL3891** [comment]
Coming from the blog post, this is really really cool :)

I haven't done any measurements but I can see this being beneficial for some places in our code, but I'd be worried to enable it globally. Perhaps it could be enabled with an attribute, that way you could choose the scope (method, class,assembly) and then down the line if we want it do be the default it could be a default msbuild parameter that works the same as the other assembly info attributes

**Comment by stephentoub** [comment]
Thanks, @aL3891.  Technically it could be done in a manner you suggest, and I considered something like that.  The main problem I hit is it adds a non-trivial amount of expensive reflection on first use of every async method, and that can contribute non-trivially to things like start-up time costs.  If we could figure out how to avoid that, it might be a very reasonable opt-in path to consider.

**Comment by aL3891** [comment]
I was thinking the attribute could be checked at compile time similar to CallerMemberNameAttribute (atleast that's how I think that attribute works, apologies if I'm incorrect)
Perhaps that is not possible/practical though 

Still, a very cool feature for micro service apps with very chatty APIs

**Comment by stephentoub** [comment]
For .NET 5, the plan is to leave the code for this in but off by default.
