### ISSUE TITLE
R2R: add a bit that indicates whether IBC data was used when producing the code

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#13631]
It's currently impossible to figure out reliably whether code in an R2R image was produced using IBC training data. This issue is to add a bit to allow that.

@davidwrighton

**Comment by mangod9** [comment]
@davidwrighton is this available already? Regardless doesnt seem like its a requirement for 6, so moving to 7

**Comment by davidwrighton** [comment]
We don't have a clear use case for this
