### ISSUE TITLE
Clean up the argument list for MarshalInfo::MarshalInfo

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#13630]
The constructor for MarshalInfo in `mlinfo.h` and `mlinfo.cpp` has a ton of arguments, many of which are booleans. We should clean up this argument list and create a structure/flags that describe the various settings to make calls to the constructor readable.

**Comment by AaronRobinsonMSFT** [comment]
Given we are looking at source generators going forward, I don't think this is worth doing.
