### ISSUE TITLE
Switch to label.N form for pre-release label

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#13641]
In order to facilitate better preview sorting, switch to label.N form for the pre-release label.

Requires a recent version of arcade, so filing an issue rather than opening a PR.  See https://github.com/dotnet/windowsdesktop/pull/104 for an example of how this is done.

**Comment by jashook** [comment]
@mmitche this seems stale can we close?

**Comment by mmitche** [comment]
Yeah this is well and done.
