### ISSUE TITLE
SecurityElement.FromString returns null.

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#13655]
The following code fragment which is causing  null to be returned.. This works in .net framework 4.x

            string x = @"<values><value name= ""guid"" type =""string"">""1659a891-2720-422c-b45b-b2dc74391802""</value></values>";

            SecurityElement se = SecurityElement.FromString(x);
            if (se == null)
            {
                Console.WriteLine("why are we null?");
            }

In https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Security/SecurityElement.cs it appears that  .FromString method does nothing.

Regards..

**Comment by krwq** [comment]
I'm in favor of just updating documentation but not changing the implementation to throw at this point (I feel like the ship has already sailed), any objections?
