### ISSUE TITLE
Asynchronous FileStream I/O can throw in the completion port callback thread

### ISSUE THREAD

**Issue by joshudson** [dotnet/runtime#13658]
This is the second of a class of bugs of the same form that we call the heart of darkness. They're all of the same basic form, doing something dodgy inside of an IO completion callback. We have disabled all asynchronous FileStream code as a workaround.

src/System.Private.CoreLib/shared/System/IO/FileStreamCompletionSource.Win32.cs: 189:
````
                        Exception e = Win32Marshal.GetExceptionForWin32Error(errorCode);
                        e.SetCurrentStackTrace();
                        TrySetException(e);
````

Should clearly read:
````
                        try {
                            Exception e = Win32Marshal.GetExceptionForWin32Error(errorCode);
                            e.SetCurrentStackTrace();
                            TrySetException(e);
                        } catch (Exception e2)
                        {
                            TrySetException(e2);
                        }
````

This time around, no equivalent bug exits on the Unix side because Unix doesn't provide async read/write on local disks.

**Comment by JeremyKuhne** [comment]
@stephentoub Is catching arbitrary exceptions and setting them with `TrySetException` the right pattern for using `TaskCompletionSource`?

@joshudson Do you have a call stack where this actually happened? There might be mitigations we can consider when generating IO exceptions.

**Comment by stephentoub** [comment]
> Is catching arbitrary exceptions and setting them with TrySetException the right pattern for using TaskCompletionSource?

Yup

**Comment by joshudson** [comment]
Most of the time it dies with OutOfMemoryException in the log. No stacktrace.

**Comment by joshudson** [comment]
I'll gladly update the PR.

**Comment by adamsitnik** [comment]
@joshudson We are currently working on a `FileStream` rewrite and I am trying to get the right prioritization for every task.

Could you please provide a small repro app of the problem that you are facing and describe exactly what is wrong and why?

From the description above I understand that you hit `OutOfMemoryException` when the framework code calls `SetCurrentStackTrace` or `TrySetException` and would like us to handle this specific scenario and rethrow a different exception?

**Comment by joshudson** [comment]
@adamsitnik : To repro, set up the following:

1) Find a way to reliably get an IO error after `async` so that it doesn't fail immediately. I haven't been able to do this reliably.

2) Change `Win32Marshal.GetExceptionForWin32Error(errorCode);` to `throw new OutOfMemoryException`. This is most likely the line that fails, though I can't prove its not `e.SetCurrentStackTrace();`

The failure mode is simple. Since there's somewhere to send the `OutOfMemoryException` from `GetExceptionForWin32Error`, it should be sent. The fix I wrote looks really fancy only because I bothered to ensure that if `e.SetCurrentStackTrace()` is the one that threw, the original exception would be thrown with no stacktrace rather than the OutOfMemoryException but I doubt that you actually need to do this. Just wrapping the whole method in `try { } catch(Exception e) { TrySetException(e); }` would accomplish my purpose.

**Comment by adamsitnik** [comment]
The code that you have [referenced](https://github.com/dotnet/runtime/blob/f818e296aebbc6b555fb94e6b4d051f2773e25d8/src/libraries/System.Private.CoreLib/src/System/IO/FileStreamCompletionSource.Win32.cs#L188-L190) tries to allocate an exception and the stack trace (this is quite a small allocation request). When there is not enough free memory to fulfill the allocation request, GC tries to free memory from Gen 0, 1 & 2 or asks OS for more. If it fails to get enough free memory, an `OutOfMemoryException` is thrown.

OOM almost always means that there is a memory leak. You should identify the memory leak and just fix it. The best way to do that is to try to repro it on a dev machine. I've described how to do this [here](https://github.com/dotnet/runtime/issues/45315#issuecomment-740714288).

If you can't repro it outside of the Production environment, you can set up your Windows prod machine to automatically take a full memory dump when `OutOfMemoryException` occurs, analyze the dump, identify and fix the dump. For that, you might want to read [this blog post](https://www.informit.com/articles/article.aspx?p=1409801&seqNum=5) or "SCENARIO 6-1. OUT OF MEMORY" paragraph from the [Pro .NET Memor Management book](https://learning.oreilly.com/library/view/pro-net-memory/9781484240274/html/430794_1_En_6_Chapter.xhtml).

Having said that, I am going to close the issue as we don't plan to add special handling for OOM.
