### ISSUE TITLE
.net core Console app closes with Segmentation fault

### ISSUE THREAD

**Issue by BramEsendam** [dotnet/runtime#13678]
I am using .net core 3.0.0 on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-66-generic x86_64)

I have been running into a Segmentation fault error on linux it runs fine on windows.

I have tried debugging it with GDB and [this](https://pastebin.com/q4N3TSqS) is the result from that. 
The Segment fault error happened in Thread 25.
This is my first time doing any debugging on Linux so I'm not sure if that was the right backtrack.

**Comment by joperezr** [comment]
From reading the thread this seems to be a problem comming from an external component and not a problem with the framework, so I'm closing the issue for now. @BramEsendam feel free to re-open if that is not the case.
