### ISSUE TITLE
Provide block counts in tiered compilation from R2R images

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#13672]
Tiered compilation can reduce the performance of application by replacing IBC tuned R2R code with non-tuned jitted code. See dotnet/runtime#13451 Consider enhancing the R2R format to allow method block counts to be stored in R2R images and used by the runtime. This is causing a ~20% regression in the performance of the StringBuilder.Append code

**Comment by davidwrighton** [comment]
This work won't make .NET 5.

**Comment by davidwrighton** [comment]
EgorBo is working on this with #70941

**Comment by mangod9** [comment]
@EgorBo do we expect this to make it into 7?

**Comment by davidwrighton** [comment]
We implemented this particular feature with `--embed-pgo-data` which we use only for System.Private.CoreLib. @EgorBo's work provides the ability to get live runtime based pgo data, which is even better.
