### ISSUE TITLE
Announcement: Repository Consolidation Timeline

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#13688]
As we [announced](https://github.com/dotnet/announcements/issues/119) [earlier](https://github.com/dotnet/announcements/issues/127) we are planning on consolidating some of the repositories in the dotnet org. Our planning has reached a point where we have a schedule for the coreclr, corefx and core-setup moves into dotnet/runtime that we want to share out with the community.

### November 13th
We’ll move all changes from the original repositories into dotnet/runtime up to 5PM on November 13th PST (1AM November 14th UTC). We’ll try to help as many pull requests as possible get merged by then. At that point, if there’s any pull requests still open we’ll have to close them. If you’d still like to continue those pull requests, we’d encourage you to bring them to dotnet/runtime in a new pull request.

The repositories themselves will be effectively archived at this point. The state of the “master” branch will be recorded with a tag, named “master-archive”, but the branch itself will be deleted. The default branch for the repositories will be named “archive” and it will be a single commit with a README.md and CONTRIBUTING.md file pointing to our dotnet/runtime repository.

The repositories will remain active for servicing changes to .NET Core 3.1 and earlier hence we will not be using the GitHub archive capability. 

### November 22nd
The dotnet/runtime repository will be made public and available for community contribution. Even though the repository will be created on November 13th it will take several days to get it back into a working order: fixing up our build scripts, recreating our Azure Dev Ops build definitions, etc … Until those tasks are completed it will not be possible to accept pull request and hence the repository will remain private. Once we are in a state that pull requests can be merged again the repository will be made public.

Our expectation is that will occur on November 22nd. If it is ready sooner it will be made public sooner. If the work takes longer than we planned then we will add an update to this announcement with a new expected date.

==== as of November 27th, we are currently here ====

### December 1st-2nd (Delayed)
**Currently delayed, will update with a new date once it's known**

All issues, open and closed, will be migrated from corefx, coreclr and core-setup into dotnet/runtime. This will be using GitHub’s existing issue transfer feature in a bulk migration. This means all of the existing issue links will continue to function via redirects.

This does mean though that labels will not transfer with the issues. Labels will be re-applied as a post processing step by our engineering team once the issue migration completes.

Even though our issues won’t be fully migrated until this time we’d like the community to begin filing issues on dotnet/runtime as soon as it’s public rather than continuing to file issues on the original repositories.

### Migrating Commits
The dotnet/runtime repository will be a new commit history from the original repositories. We are using this consolidation as an opportunity to clean up our history with the goal of having a cleaner, smaller history as a starting point. This means commits will be rewritten in the following ways as they are migrated to dotnet/runtime:

1. Author information, contributor information, changed file list and time stamps from the original commit will be preserved.
1. Links to issues, pull requests or commits in the repository using GitHub short links will be rewritten so they continue to point the original repository. 
1. Every commit will be appended with a link to the original commit it was mapped from.

The actual contents of the commit though will be updated to match the new directory layout of the dotnet/runtime repository.

**Comment by danmosemsft** [comment]
This has fulfilled its purpose.
