### ISSUE TITLE
Eliding inlined null checks against string constants at JIT time

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#1368]
Here, the null check against the `nameof` constant is not elided ([SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYmpBkJoBvGgzNNdEYACsYYDAwCyACiu37DAGYQIASlPmJtTmIV4+LAAqABZQEADuAJKeAHIckpLOXNgCEJ7O3n6+GsGhZsQA7GEQxSEAvjT11Fq6zEh6DACiCBgwXLi8EH3GAWYA2o4wGFEQACYJ4hkTU7PzYpIA8mJ8g7gsAIIA5gewuP0KMAlckrxcNwe+ALojFkzkbREM0bGJKWmSADwRAB8zimvFwnwYCmwkg4MDQr0YYmwUGyyWyMH8JTMQVKZl4ngYzmRqPw6IEDHBDC4f18DCm32pMDiDD2UAOHAEPFS6S6Ki2Ay4mQxuWJKLRGN8RWeIQqUJhcIYAH4lfSYvEmSy2RyuRgeZI+TABYMxaTyZiauZGrUgA==)):

```cs
using System;
using System.Runtime.CompilerServices;

public class C
{
    public object M(object foo)
    {
        foo.ThrowIfNull(nameof(foo));
        return foo;
    }
}

public static class Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T ThrowIfNull<T>(this T value, string paramName)
    {
        if (paramName is null) throw new ArgumentNullException(nameof(paramName));
        return value ?? throw new ArgumentNullException(paramName);
    }
}
```

Could this be improved?

category:cq
theme:null-checks
skill-level:intermediate
cost:medium

**Comment by mikedn** [comment]
https://github.com/dotnet/coreclr/issues/22511

**Comment by jnm2** [comment]
Is this one an obvious duplicate? I don't know enough to know if fixing dotnet/coreclr#22511 would fix the scenario that combines it with inlining.

**Comment by mikedn** [comment]
> Is this one an obvious duplicate? I don't know enough to know if fixing dotnet/coreclr#22511 would fix the scenario that combines it with inlining.

Well, 22511 is actually a bit more complicated so I'm going to fix just this one for now. Should have been done a long time ago.

**Comment by BruceForstall** [comment]
cc @erozenfeld

**Comment by EgorBo** [comment]
Fixed via https://github.com/dotnet/runtime/pull/37245 (basically via mikedn's https://github.com/dotnet/runtime/pull/1377)

New codegen:
```asm
G_M62216_IG01:
       push     rsi
       sub      rsp, 32
						;; bbWeight=1    PerfScore 1.25

G_M62216_IG02:
       test     rdx, rdx   ;; <-- foo is not null, not ldstr one.
       je       SHORT G_M62216_IG05
						;; bbWeight=1    PerfScore 1.25

G_M62216_IG03:
       mov      rax, rdx
						;; bbWeight=1    PerfScore 0.25

G_M62216_IG04:
       add      rsp, 32
       pop      rsi
       ret      
						;; bbWeight=1    PerfScore 1.75

G_M62216_IG05:
       mov      rcx, 0xD1FFAB1E
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       mov      ecx, 5
       mov      rdx, 0xD1FFAB1E
       call     CORINFO_HELP_STRCNS
       mov      rdx, rax
       mov      rcx, rsi
       call     System.ArgumentNullException:.ctor(System.String):this
       mov      rcx, rsi
       call     CORINFO_HELP_THROW
       int3     
						;; bbWeight=0    PerfScore 0.00
; Total bytes of code: 77
```
