### ISSUE TITLE
Avoid continue parsing the signature in case of missing reference assembly

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#13695]
In general, when the reference assembly is not available, continue parsing the signature is impossible. There are cases in the code where we are swallowing the exception and continue, and we should fix them.

A canonical example is this one:
https://github.com/dotnet/coreclr/blob/21d651bb4613ca480cd97793fe5d854af36b765c/src/tools/r2rdump/R2RReader.cs#L476-L486

The decoding at line 479 failed due to missing reference assembly (for example, a generic instantiation that references an assembly missed from the reference assembly set) and then exception is swallowed within it, and then on line 486, we are continuing to interpret the bytes that are supposed to be belonging to the signature as something else, causing downstream failure.

There is probably more than one place we are doing this, this needs to stop.

**Comment by davidwrighton** [comment]
Moving to 6.0 as r2rdump is not a shipping part of .NET 5 (its an internal development tool at this time).
