### ISSUE TITLE
FreeBSD mscordac.exports

### ISSUE THREAD

**Issue by ComradeSlice** [dotnet/runtime#13694]
When building on FreeBSD I get:

```
make[2]: make[2]: don't know how to make src/dlls/mscordac/mscordac.exports. Stop

make[2]: stopped in /usr/home/james.shuriff/src/coreclr/bin/obj/FreeBSD.x64.Debug
--- src/dlls/mscordac/CMakeFiles/mscordaccore_exports.dir/all ---
*** [src/dlls/mscordac/CMakeFiles/mscordaccore_exports.dir/all] Error code 2
```

I've also had various other build issues I was able to fix with -Wno-implicit-function-declaration for libunwind and adding an explicit -L/usr/local/lib to the genLttngProvider.py linker arguments but I'm stumped on this one. Building on x86_64 FreeBSD 12.0-RELEASE with the release/2.2 branch.

**Comment by joperezr** [comment]
Closing as this has been fixed. Feel free to reopen if you keep hitting this issue.
