### ISSUE TITLE
Ambiguity in what `Environment.ProcessorCount` returns

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#13691]
We seem to also have ambiguity about what `Environment.ProcessorCount` returns. According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=netcore-3.0), it should return "the number of processors on the current machine".

- On Windows without NUMA, it returns [`SYSTEM_INFO::dwNumberOfProcessors`](https://github.com/dotnet/coreclr/blob/db8fc1b420be60f6a2afb153dd9e645ec231ec82/src/classlibnative/bcltype/system.cpp#L350). This sounds correct. I assume that this number cannot change during the process lifetime.
- On Windows with NUMA, it returns [`CPUGroupInfo::GetNumActiveProcessors`](https://github.com/dotnet/coreclr/blob/db8fc1b420be60f6a2afb153dd9e645ec231ec82/src/classlibnative/bcltype/system.cpp#L341). Can this number change during the process lifetime?
- On Unix, with `HAVE_SCHED_GETAFFINITY`, it returns the process affinity at the process start: https://github.com/dotnet/coreclr/blob/6ce179a17061abbbe9f904f878943a28c8041a62/src/pal/src/misc/sysinfo.cpp#L161
- On Unix ARM and ARM64, it returns `_SC_NPROCESSORS_CONF`. This sounds correct.
- On Unix on other platforms, it returns `_SC_NPROCESSORS_ONLN` at the process start. That does not sound right.

cc @janvorli @kouvel

_Originally posted by @jkotas in https://github.com/dotnet/coreclr/pull/27543#issuecomment-547887677_

**Comment by AntonLapounov** [comment]
The documentation has been clarified by dotnet/dotnet-api-docs#6668.  I think this can be closed now.
