### ISSUE TITLE
Excessive use of memory on linux compared to windows

### ISSUE THREAD

**Issue by kysel** [dotnet/runtime#13702]
Hi there,

I've just encountered a kind of weird issue, we are using [OpenCvSharp](https://github.com/shimat/opencvsharp) in production on Windows machines and it does run pretty well. But now, we've tried to run some services in docker containers and it always ends with OOM, even after allocating more than 3 times the memory needed on windows using the docker' `-m` parameter.

I have been trying to pin down the issue but I am not able to do so. I have created a small repro solution here: https://github.com/kysel/OcvsMemIssueRepro, project `AllocTest` simplifies the repro. It basically just allocates some OpenCV's `Mat` and then explicitly disposes them and force GC. All other projects are part of OpenCvSharp library and are there to simplify debugging.

I hope you can point me in the right direction on how to fix this issue, maybe it's related to dotnet/runtime#7740 🧐.

### Repro steps (same for windows and Linux):
0. On Linux, install OpenCV dependencies [this should help](https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu.18.04-x64/Dockerfile)
1. Run the `AllocTest` project (`dotnet run` in `AllocTest` directory will do the job)
2. Monitor memory use
    * I've used command `dotnet-counters monitor -p [pid]` on Linux,
    * and diagnostics tools in VS on windows
3. Click the *enter* key in running `AllocTest` to _step_ through 3 phases - pre alloc, post alloc, post GC
4. Usually, the first loop is okay on both platforms starts at ~30MB of working set memory (*Working Set* in dotnet-counters), peaks to ~850MB after allocating OpenCvSharp's `Mat` and drops down to under ~80MB after GC.
But after the second iteration has passed allocated memory on Linux stays at ~870M and never drops again below let's say 100MB. As opposed to windows where memory always drops back to _normal_ values <100MB

### `dotnet-trace` dumps from a Linux machine

To help you diagnose the issue I have created 3 memory dumps using the command
`dotnet-trace collect --format NetTrace --providers Microsoft-Windows-DotNETRuntime:1980001 -p [pid] -o [name].nettrace`
If there is anything more I can do for you please tell me and I'll happily provide more information.

1. Initial state before any unmanaged allocation [here](https://github.com/kysel/OcvsMemIssueRepro/raw/master/dumps/preAlloc.nettrace)
2. Ok state after the first allocation and forced GC [here](https://github.com/kysel/OcvsMemIssueRepro/raw/master/dumps/post1GC.nettrace)
3. Not ok state after the second iteration [here](https://github.com/kysel/OcvsMemIssueRepro/raw/master/dumps/post2GC.nettrace)

#### Linux
Ubuntu 18.04 running in WSL2, but the same issue applies to bare-metal Linux, as well as docker image `mcr.microsoft.com/dotnet/core/aspnet:3.0`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

#### Windows
There is a preview SDK, but it behaves the same on the latest stable `3.0.100`.
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18985
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
```

**Comment by Maoni0** [comment]
have we gotten the tooling issue figured out on this? please let us know if you still need help; otherwise this will be closed.

**Comment by kysel** [comment]
I've tried it now with the latest .Net core 3.1 docker image
```
#dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
``` 
And the results are the same, the app keeps ~800MB working set after second iteration. 
There is a [gcdump after couple of iterations](https://github.com/kysel/OcvsMemIssueRepro/blob/docker/OcvsMem.gcdump) 
![image](https://user-images.githubusercontent.com/2399369/78315946-ba3a9b00-755e-11ea-8dbf-6f85f82be1dc.png)

Meanwhile, I've created a branch with [easier repro](https://github.com/kysel/OcvsMemIssueRepro/tree/docker) just 
- run it the repository root `docker build -t ocvmem31 -f .\netcore31.Dockerfile .`
- start the image interactively from within vscode or cli `docker run -m 900m --rm -it  ocvmem31:latest`
- run the app `./bin/Release/netcoreapp3.1/ubuntu.18.04-x64/OcvLinuxTest` and click enter :)


Tomorrow I'll try to run it on .Net5 preview, to see if anything changes.

**Comment by Maoni0** [comment]
right, I didn't mean you will see different results with 3.1 (or even 5.0 since we dunno why you are seeing what you are seeing); I just meant does the tool work for you so we can debug this. 

from the screenshot it looks like perfview doesn't have most of the memory accounted for; so either most of the memory isn't used by the GC or perhaps we have some problems with tooling. @billwert @brianrob would it be possible that you could take a look? there's an easy repro.

**Comment by kysel** [comment]
this issue is IMO related to the #13301
After setting env var `MALLOC_TRIM_THRESHOLD_` to 100000 the working set size drops back to *normal* values (~75MB) after every single iteration.

So I guess there is no direct issue in the .Net CG, but the behavior is still weird and some proper fix would be nice.

**Comment by jkotas** [comment]
Thanks for sharing the workaround that you have found.

When it comes to memory allocators, it is hard to come up with one universal policy that works great for everybody. The glibc [memory allocator](https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation-Tunables.html) has tunable setting for this very reason, so that the policy can be customized when the default one does not work for you.

Closing - improving glibc malloc policies is outside the realm of .NET runtime.
