### ISSUE TITLE
Span CopyTo Span - Crashes .Net

### ISSUE THREAD

**Issue by abbotware** [dotnet/runtime#13701]
There appears to be some sort of threading issue in the  System.Memory 4.5.3 running on .Net Framework for the following code:

`Memory<byte> memory = new byte[100];`
`ReadOnlySpan<byte> temp = new byte[30];`
`temp.CopyTo(memory.Span);`

attached is a sample program that will crash the error: 

The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE09357BFD (00007FFE091A0000) with exit code 80131506.

category:correctness
theme:gc-info
skill-level:expert
cost:medium

**Comment by Anipik** [comment]
It seems like it was fixed for net core by https://github.com/dotnet/runtime/pull/1059
@jkotas any update on fix for .NetFramework ?

**Comment by jkotas** [comment]
The fix for .NET Framework is tracked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1026837 in the internal bug database.

@JulieLeeMSFT Could you please look into what we want to do here?

cc @dotnet/jit-contrib @eerhardt @GrabYourPitchforks

**Comment by JulieLeeMSFT** [comment]
@briansull please port the .NET Core fix to Framework.

**Comment by GrabYourPitchforks** [comment]
Huh, not sure why that internal issue was assigned to me. I've given it to Brian.

**Comment by briansull** [comment]
@jkotas 
Is there a repro that can be run on the desktop?

```
D:\Public\Bugs\Runtime_13818>csc /o /unsafe repro.cs
Microsoft (R) Visual C# Compiler version 3.6.0-4.20251.5 (910223b6)
Copyright (C) Microsoft Corporation. All rights reserved.

repro.cs(18,18): error CS0103: The name 'Unsafe' does not exist in the current context
```

**Comment by eerhardt** [comment]
> repro.cs(18,18): error CS0103: The name 'Unsafe' does not exist in the current context

You need to add a reference to https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/

**Comment by briansull** [comment]
How do I add that reference?

**Comment by eerhardt** [comment]
1. Create an empty directory and a `Repro.csproj` with the following contents:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.7.1" />
  </ItemGroup>
</Project>
```
2. Add the code from https://github.com/dotnet/runtime/issues/13818 to a `repro.cs` file next to the above `.csproj` file.
3. `dotnet run -c Release` from the directory with `Repro.csproj` and `repro.cs` files.

**Comment by briansull** [comment]
Thanks,  I have a repro case and have tested the fix.  It looks good

**Comment by briansull** [comment]
I have checked in the fix for this issue into the Desktop .Net runtime for 4.8 and 4.7

The fix is expected to ship in the latter part of September as part of that month’s non security release. (barring any unexpected issues)

**Comment by briansull** [comment]
1026837 | [4.8] Possible data corruption in .NET Framework when using  Span-based APIs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1026837

**Comment by CarolEidt** [comment]
Thanks @briansull!
