### ISSUE TITLE
Conditional format specifier and negative zero

### ISSUE THREAD

**Issue by jeremybparagon** [dotnet/runtime#13712]
I am looking for a way to make something like `(-0.01).ToString("0.#;-0.#")` produce `"0"`. In .NET Core 3.0, it produces `"-0"`. This makes the conditional format specifier unusable for me.

During my experimentation, I noticed that `(-0.01).ToString("p0.#;n0.#")` produces `"-p0"`. Thus, it seems that the statement "negative values are always displayed without a minus sign when section separators are used" at https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#the--section-separator is not followed here.

**Comment by huoyaoyuan** [comment]
The documentation has already been updated:

<html>
<body>


Two sections | The first section applies to positive values and zeros, and the second section applies to negative values.If the number to be formatted is negative, but becomes zero after rounding according to the format in the second section, the resulting zero is formatted according to the first section.
-- | --



</body>
</html>

**Comment by jeremybparagon** [comment]
@huoyaoyuan I see that the bug confirmed by @tannergooding is still present in .NET 7: `(-0.01).ToString("p0.#;n0.#")` still prints `-p0`. Should this issue remain open?

Also, when that is fixed, the documentation you quoted will not be correct. It says, "If the number to be formatted is negative, but becomes zero after rounding according to the format in the second section, the resulting zero is formatted according to the first section." But here we have `-0.01` which will become zero after rounding but will be formatted according to the second section.

Thanks.

**Comment by huoyaoyuan** [comment]
Sorry I didn't test this locally. Can you confirm the behavior in .NET 7? Could you also examine the expected behavior according to doc?

**Comment by jeremybparagon** [comment]
@huoyaoyuan I tested it in .NET 7, and `(-0.01).ToString("p0.#;n0.#")` still outputs `"-p0"`. This goes against the documentation that says, "If you want the final formatted value to have a minus sign, you should explicitly include the minus sign as part of the custom format specifier." Here I did not include a minus sign in the format specifier, but it is being added nonetheless.

The underlying issue is that the intended spec has changed as of .NET Core 3.0. Negative zero is now presented as `-0` rather than `0`. So the behavior specified by @tannergooding [above](https://github.com/dotnet/runtime/issues/13712#issuecomment-548982623) as the intended behavior goes against the spec that says, "If the number to be formatted is negative, but becomes zero after rounding according to the format in the second section, the resulting zero is formatted according to the first section." The current behavior needs to change, and the documented behavior needs to change.
