### ISSUE TITLE
Type object in assembly loaded with Assembly.LoadFile is different from the same type which is directly referenced

### ISSUE THREAD

**Issue by zgabi** [dotnet/runtime#13723]
Hi,

I have a problem with migrating our application to .net core 3.0.

I've created a small example which shows the same problem as I have in my application:

ClassLibrary1, netstandard2.0 has the following class:
```
    public class MyTestClass
    {
    }

```

ConsoleApp1 has a reference to ClassLibrary1, netcoreapp3.0
```
            string path = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ClassLibrary1.dll");
            var types = Assembly.LoadFile(path).DefinedTypes.Select(x => x.AsType());
            var ok = types.Contains(typeof(MyTestClass));

```

When the ConsoleApp1 targets .NET 4.7.2 the value of the `ok` variable is `true`. In .NET Core 3.0 it is `false`. Why?

**Comment by vitek-karas** [comment]
If this is still an issue, please feel free to reopen or open a new one.
