### ISSUE TITLE
[crossgen2] Support custom modifier

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#13726]
In various places in the type system code, there are comments like this:

https://github.com/dotnet/coreclr/blob/5a381e7c8507777f71746ec564a6b75e38ebe089/src/tools/crossgen2/Common/TypeSystem/Ecma/EcmaSignatureParser.cs#L126

or this:

https://github.com/dotnet/coreclr/blob/5a381e7c8507777f71746ec564a6b75e38ebe089/src/tools/crossgen2/Common/TypeSystem/Common/InstantiatedType.cs#L148

We need to actually support custom modifier.

**Comment by nattress** [comment]
We support custom modifiers now
