### ISSUE TITLE
[Pinned Object Heap] `DAC_NUMBERGENERATIONS`  may need to be adjusted

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#13736]
`DAC_NUMBERGENERATIONS`  is currently 4 and changing it is a compat issue. 

We should think what to do with this. 

Merge POH into LOH data, have a separate field, etc...

**Comment by tommcdon** [comment]
@VSadov  do you plan on addressing this issue in .NET 5 timeframe?

**Comment by VSadov** [comment]
Yes, the plan is to address this for 5.0
From the feedback I hear that this should be addressed sooner rather than later. I'll try to get to this this week.

**Comment by davmason** [comment]
@VSadov have you had a chance to work on this yet? We're getting close to the feature complete date and I haven't seen any changes.

**Comment by Maoni0** [comment]
API to get # of generations added via [this PR](https://github.com/dotnet/runtime/pull/37853)

**Comment by davmason** [comment]
Fixed in #37853
