### ISSUE TITLE
[Pinned Object Heap] `DacpAllocData` needs to support Pinned Object Heap

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#13735]
`DacpAllocData` has a field for allocated LOH bytes. 
It  needs to handle POH somehow - include it in the number or have a separate field.

```c++
struct MSLAYOUT DacpAllocData : ZeroInit<DacpAllocData>
{
    CLRDATA_ADDRESS allocBytes;
    CLRDATA_ADDRESS allocBytesLoh;
};
```

**Comment by tommcdon** [comment]
@VSadov do you plan on addressing this issue in the Net 5.0 timeframe?

**Comment by VSadov** [comment]
Yes, the plan is to address this for 5.0
From the feedback I hear that this should be addressed sooner rather than later. I'll try to look at https://github.com/dotnet/runtime/issues/13736 first, unless this needs to be handled at the same time.

**Comment by davmason** [comment]
DacpAllocData is currently unused in SOS, to determine alloc data SOS scans the GC heap and does not rely on the runtime to report it (see https://github.com/dotnet/diagnostics/blob/b27e6ad70f01ff638eef02dac50de4bebfcaa40e/src/SOS/Strike/eeheap.cpp#L768-L850).

@leculver or @noahfalk do you know of any use for DacpAllocData/DacpGenerationAllocData/ISOSDacInterface::GetHeapAllocData? I suspect these are unused and do not need updating.

**Comment by noahfalk** [comment]
I'm not aware of any specific usage and I think its fine to consider it unused.

**Comment by davmason** [comment]
Thanks Noah. Closing this issue out and leaving the API as-is. If anyone knows of a use, feel free to reopen.

**Comment by leculver** [comment]
Sorry my internet has been really spotty all day.  @davmason I can confirm that ClrMD doesn't use that structure, and doesn't call "GetThreadAllocData" which is the only function that uses it.
