### ISSUE TITLE
Reconcile how LOH allocations are tracked in allocation contexts

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#13734]
`Alloc` uses per-thread context
`AllocLHeap` uses per-heap context.

We probably should use only one way. Using per-heap context consistently is attractive, since we can make allocation contexts smaller by removing `alloc_bytes_loh`

However, consider `GetAllocatedBytesForCurrentThread` API - does it actually see allocations done via `AllocLHeap` ? Should it?

**Comment by Maoni0** [comment]
the reason why AllocLHeap was there was to allocate objects smaller than LOH threshold on LOH. I have not looked at your PR yet, but I hope that was kept in mind.

**Comment by VSadov** [comment]
@Maoni0 - yes, forcing allocations to go into POH is still possible. I also plan to use similar mechanism (flags) as a way to request POH allocations.
Thanks for reviewing!!

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/runtime/pull/33402
