### ISSUE TITLE
valuenum should use `target_size_t` for `TYP_BYREF`

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#13745]
There are ~7 calls to `VNForByrefCon(size_t cnsVal)` and they should be changed into `VNForByrefCon(target_size_t cnsVal)` calls.

That change will convert 64bit constants to 32bit constants for byrefs when doing cross-crossgen for arm32 on arm64 . We should see diffs on the test added in dotnet/coreclr#27702.

_Originally posted by @echesakovMSFT in https://github.com/dotnet/coreclr/pull/27702_

category:correctness
theme:ir
skill-level:beginner
cost:small

**Comment by AndyAyersMS** [comment]
@sandreenko @briansull should we fix this for 5.0?

**Comment by AndyAyersMS** [comment]
I'm going to move to future; if you think this needs to be in 5.0 please make a case for it.
