### ISSUE TITLE
Netcore2.2 app aborts in release configuration on a Linux machine

### ISSUE THREAD

**Issue by rossgurbutt** [dotnet/runtime#13749]
We have an issue with the attached (heavily cut down) project which targets netcoreapp2.2.
We build and publish the app in both Release and Debug configurations.
When running on Windows, Release and Debug both complete successfully.
When running on Linux, Debug completes successfully, however Release aborts with one of the following errors:
- System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
- Segmentation fault

The program is very simple, contains no unmanaged code, no third party dependencies, and almost no logic at all.

Linux machine details (however this happens on all the different Linux machines / OSs available to us):
```
Operating system: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-862.11.6.el7.x86_64
```

dotnet --info:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```
[Program.zip](https://github.com/dotnet/coreclr/files/3820061/Program.zip)

category:correctness
theme:calling-convention
skill-level:beginner
cost:small

**Comment by jkotas** [comment]
.NET Core 2.2 is out of support.
