### ISSUE TITLE
FileSystemWatcher doesn't notice watched directory rename

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/runtime#13753]
`FileSystemWatcher` doesn't notice when its watched directory is renamed.

.Net Core 3.0
Windows 10 x64 1903 build 18362.10024

Code that reproduces the issue:

```csharp
var path = Path.Join(Path.GetTempPath(), Guid.NewGuid().ToString());
Directory.CreateDirectory(path);
using var watcher = new FileSystemWatcher(path)
{
    EnableRaisingEvents = true
};
watcher.Changed += (o, e) => Console.WriteLine("Changed " + e.FullPath);
watcher.Created += (o, e) => Console.WriteLine("Created " + e.FullPath);
watcher.Deleted += (o, e) => Console.WriteLine("Deleted");
watcher.Error += (o, e) => Console.WriteLine("Error");
watcher.Renamed += (o, e) => Console.WriteLine("Renamed");
            
var movedPath = path + " moved";
Directory.Move(path, movedPath); // Does not raise any events
File.WriteAllText(Path.Combine(movedPath, "file.txt"), "Hello, world!"); // Raises event with incorrect FullPath (has old directory, not new one)
Thread.Sleep(-1);
```

**Comment by JeremyKuhne** [comment]
This has always been the behavior and is an artifact of the underlying Win32 API- https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw. You need to watch the parent directory. You can mitigate cost by not watching recursively and adding as many filters as possible.

**Comment by matthew-a-thomas** [comment]
> This has always been the behavior and is an artifact of the underlying Win32 API- https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw. You need to watch the parent directory. You can mitigate cost by not watching recursively and adding as many filters as possible.

@JeremyKuhne Even so, the problem remains that `e.FullPath` contains an incorrect path as shown in my example. IMHO the API is broken: it promises to give the correct full path and it doesn't but gives non-existent paths. Apparently the only portion of that property's string that is guaranteed to be correct is the very last path segment, but that's not a "full" path in any sense.
