### ISSUE TITLE
Marshal.PtrToStructure<T> does not permit constructed generics

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/runtime#13756]
PtrToStructure<T> does not permit a constructed generic argument for T.  Attempts to use one result in an exception with the diagnostic:  'The specified Type must not be a generic type definition.'  This message seems to indicate that the check in PtrToStructure for IsGenericType (which identifies both unbound and constructed types) should actually have been IsGenericTypeDefinition (which only identifies unbound types).  In experiments, stepping over the IsGenericType check allows PtrToStructure to succeed, as long as T is blittable. 

Note that Mono does not have this restriction:
https://github.com/mono/mono/blob/bd278dd00dd24b3e8c735a4220afa6cb3ba317ee/netcore/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.Mono.cs#L311-L316 (Note specifically line 314).

**Comment by AaronRobinsonMSFT** [comment]
@Scottj1s This is looking less likely to happen. Do you feel this is still needed for your work?

**Comment by Scottj1s** [comment]
> @Scottj1s This is looking less likely to happen. Do you feel this is still needed for your work?

No, not any more.  I have a reasonable workaround in Expression.GetDelegateType
