### ISSUE TITLE
.NET Core 3.1 Assembly resolution bug in specific circumstances involving C++/CLI

### ISSUE THREAD

**Issue by thoros1179** [dotnet/runtime#13760]
# Environment: 
.NET Core 3.1 Preview 2 
Visual Studio Enterprise 2019 16.4.0 Preview 4.0
Windows 10 Professional 1903

# Description
We waited desperately for C++/CLI support in .NET Core (due to some legacy burdens). Now with 3.1 Preview we tested it, and it works in the first place. But in certain circumstances the runtime is not able to resolve managed assemblies. This is the exact sequence of steps for the error to reproduce:

1. .NET Core 3.1 Application P/Invokes an unmanaged function in a mixed mode (C++/CLI) library: **works**
2. mixed mode library switches from unmanaged to managed environment **works**
3. mixed mode library (managed) calls another managed library, which is located elsewehere (not in working directory) **fails**

Usually, in Full .NET Framework, on step 3 the **System.AppDomain.AssemblyResolve**-Handler is called for the application to provide the requested assembly. But in .NET Core 3.1 this never happens (tried **System.AppDomain.AssemblyResolve** and **System.Runtime.Loader.AssemblyLoadContext.Default.Resolving**) and the process crashes with **EEFileLoadException**.

If I run steps 1-3 instad with a Full .NET Framework Application instead of the .NET Core 3.1 Application in step 1 this works flawlessly. Also if I don´t take the route via the p/invoked mixed mode library the assembly resolution in .NET Core 3.1 works.

I attached a small demo solution in which the error can be reproduced.

[NETCore31_AssemblyResolutionFail.zip](https://github.com/dotnet/coreclr/files/3823348/NETCore31_AssemblyResolutionFail.zip)

There are 4 projects:

- **TestManagedApp** (Full .NET Framework managed app, if you set this as startup project it **works**)
- **TestManagedAppCore31** (.NET Core 3.1 managed app, if you set this as startup project it **fails**)
- **UnmanagedExample** (mixed mode C++/CLI library which gets called by P/Invoke, switches to managed and then calls ManagedLibrary)
- **ManagedLibrary** (Full .NET Framework library which just shows a Messagebox)

I hope someone can attend to this or maybe point me to what I´m doing wrong.

**Comment by agocke** [comment]
Closing for now. The root problem is libraries not compiled for Core, which we do not plan to support.
