### ISSUE TITLE
Regression in Inlining.InlineGCStruct.WithoutFormat

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#13771]
There is a 24% regression in Inlining.InlineGCStruct.WithoutFormat between 3.0->3.1

![image](https://user-images.githubusercontent.com/9439069/68520939-f1777b00-0250-11ea-973c-87f4f961110b.png)

category:cq
theme:benchmarks
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
Still don't think there is anything actionable here, so I'm going to close this.
