### ISSUE TITLE
Regression in PerfLabTests.LowLevelPerf.InterfaceInterfaceMethodLongHierarchy for Windows x86

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#13782]
PerfLabTests.LowLevelPerf.InterfaceInterfaceMethodLongHierarchy regressed by 20% from 3.0->3.1.

![image](https://user-images.githubusercontent.com/9439069/68626569-7c928400-0490-11ea-8cb2-c1ff44af05dd.png)

**Comment by danmosemsft** [comment]
@DrewScoggins is there still action to be taken here? Should this be closed or moved out of 5.0?

**Comment by DrewScoggins** [comment]
This feels like it should be closed.
