### ISSUE TITLE
Consider re-compling CoreCLR's unmanaged code to mitigate JCC erratum (Nov. 2019)

### ISSUE THREAD

**Issue by damageboy** [dotnet/runtime#13794]
Intel has recently released a microcode update that adversely affects the performance of... all jumps (!):

https://www.intel.com/content/dam/support/us/en/documents/processors/mitigations-jump-conditional-code-erratum.pdf

I've personally had the "pleasure" of encountering this whilst benchmarking CoreCLR 3.0 `Array.Sort()` on clearlinux which seems to have pushed this microcode update earlier than others:

https://twitter.com/damageboy/status/1194751035136450560?s=20

For context, Here's the before/after perf hit on `Array.Sort()`:
Before:
![image](https://user-images.githubusercontent.com/125730/68856066-46e7d800-06e8-11ea-9092-1627bfb910aa.png)

After:
![image](https://user-images.githubusercontent.com/125730/68856091-55ce8a80-06e8-11ea-977a-f28f169d31c8.png)

Very specifically, I was hit with a 20% drop in `Array.Sort()`, and a smaller (by sheer luck I presume?) hit with my own code. Intel claims that the average drop in performance should be in the %0-%4 range.

The erratum claims that the microcode update adversely effects:
> In this context, Jump Instructions include all jump types: conditional jump (Jcc), macro-
fused op-Jcc (where op is one of cmp, test, add, sub, and, inc, or dec), direct
unconditional jump, indirect jump, direct/indirect call, and return.

The recommended fix, per the erratum, is to recompile the code with (Section 3.1.1):
`-mbranches-within-32B-boundaries`

In theory, this could end with a relatively minor(?) CoreCLR runtime release. Or incorporated into the 3.1 release cycle?

In addition, I think we should have a discussion about possibly applying similar (conditional) fixes to the JIT itself w.r.t the generated code on Intel processors, as it doesn't seem this issue is about to simply go away on its own.

I will open a separate issue for the JIT related discussion.

**Comment by danmosemsft** [comment]
@brianrob is work planned here? Can you provide guidance on what to do with this and https://github.com/dotnet/runtime/issues/13795

**Comment by brianrob** [comment]
I hope to have all of the data in a format for sharing shortly.  The short answer is that I don't think there is any immediate work that needs to be done here, but I will provide more context on this once I have all of the data compiled.
