### ISSUE TITLE
winrt cpp make_weak failing in .net core - IWeakReferenceSource, no such interface supported

### ISSUE THREAD

**Issue by ranjeshj** [dotnet/runtime#13792]
We now have a repro for an issue which was closed before.

https://github.com/dotnet/coreclr/issues/22324

The repro steps and standalone app can be found in this bug
https://github.com/microsoft/microsoft-ui-xaml/issues/1600

**Comment by AaronRobinsonMSFT** [comment]
The built-in WinRT support is being removed in favor of the CsWinRT generated tool chain. See https://github.com/dotnet/runtime/issues/35318 for complete details.
