### ISSUE TITLE
Add linux-musl-arm, linux-musl-arm64 PR validation coverage

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1380]
We don't appear to test Linux musl arm/arm64 in PR validation. Having these platforms may have avoided an official build break: https://github.com/dotnet/runtime/issues/1363.

I don't know if simply adding the platforms would have been enough to catch that specific RID calculation issue, we may want another issue for that. However, the bad RID would have been visible in the PR validation build logs, at the very least.

**Comment by am11** [comment]
It seems like they are available in `runtime-installers` pipeline, which just didn't invoked with gh-1337.

**Comment by safern** [comment]
I do see that we already build these platforms for coreclr checked, coreclr release, libraries, installer build with coreclr and we run tests against a checked coreclr when the PR contains a coreclr change. So I think we're good on closing this issue.
