### ISSUE TITLE
JIT Optimization (Stack Usage?)

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#13814]
On the surface, it seems like the JIT shouldn't have a problem producing the optimal code here as it is doing the proper branch elimination but that is not what's happening. Take the following method:

```c#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool HasFlag(T value, T flag) where T : struct, Enum
{			
    int size = Unsafe.SizeOf<T>();

    if (size == 1)
        return (Unsafe.As<T, byte>(ref value) | Unsafe.As<T, byte>(ref flag)) == Unsafe.As<T, byte>(ref value);
    else if (size == 2)
        return (Unsafe.As<T, short>(ref value) | Unsafe.As<T, short>(ref flag)) == Unsafe.As<T, short>(ref value);
    else if (size == 4)
        return (Unsafe.As<T, int>(ref value) | Unsafe.As<T, int>(ref flag)) == Unsafe.As<T, int>(ref value);
    else // size == 8
        return (Unsafe.As<T, long>(ref value) | Unsafe.As<T, long>(ref flag)) == Unsafe.As<T, long>(ref value);
}
```

With the branch elimination it is doing it should be able to produce the optimal ASM, i.e.:

```
    L0000: or edx, ecx
    L0002: cmp edx, ecx
    L0004: setz al
    L0007: movzx eax, al
    L000a: ret
```

It gets somewhat close but produces this instead (for size 4 types):

```
    L0000: mov [rsp+0x8], ecx
    L0004: mov [rsp+0x10], edx
    L0008: mov eax, [rsp+0x8]
    L000c: mov edx, [rsp+0x10]
    L0010: or edx, eax
    L0012: cmp edx, eax
    L0014: setz al
    L0017: movzx eax, al
    L001a: ret
```

Which runs about half as fast and uses 16 additional bytes (26 instead of just 10). I'm not sure exactly what is going on here but I believe it has to do with the way the stack is used when there are multiple branches that use locals causing some optimizations not to be done because this produces the optimal ASM:

```c#
public static bool HasFlag(T value, T flag) where T : struct, Enum
{			
    int size = Unsafe.SizeOf<T>();

    if (size == 4)
        return (Unsafe.As<T, int>(ref value) | Unsafe.As<T, int>(ref flag)) == Unsafe.As<T, int>(ref value);
    
    throw new NotSupportedException();    
}
```

I imagine that improving this could reduce JITted code size and bump performance in many cases. One of the concerns about adding generic enum methods is the JIT bloat it will produce and this could potentially help with that given that most of the methods would be simple bitwise operations like the one above.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by jakobbotsch** [comment]
Using `Unsafe.SizeOf<T>()` in every branch gets the ideal codegen today, so I'm going to close this.
