### ISSUE TITLE
Add Unsafe.As() non-ref overload

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#13815]
The ref parameter prevents being able to one-line code using `Unsafe.As` and adds a bunch of temp variables so I find myself often adding this utility method:

```c#
private static TTo UnsafeAs<TFrom, TTo>(TFrom value) => Unsafe.As<TFrom, TTo>(ref value);
```

To turn code like this:

```c#
byte v = processor.ReadByte();
value = Unsafe.As<byte, T>(ref v);
```

Into this:

```c#
value = UnsafeAs<byte, T>(processor.ReadByte());
```

Is there a reason not to add that overload? The asm generated by the JIT is the same in all the cases where I've done this.

**Comment by huoyaoyuan** [comment]
Is this covered by `Unsafe.BitCast` in #81334 ?

**Comment by jkotas** [comment]
Yes, this is covered by `Unsafe.BitCast`.
