### ISSUE TITLE
Move ILVerify tool to dotnet/runtime repo

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#13827]
https://github.com/dotnet/coreclr/issues/27934#issuecomment-558193025

**Comment by am11** [comment]
Another use-case - https://github.com/dotnet/roslyn/pull/41166#discussion_r374846217 - is to unit test compiler's output in roslyn repo against netcoreapp: https://github.com/dotnet/roslyn/blob/2ed60699f9961a451f60d560da8bd4788c0182fc/src/Test/Utilities/Portable/Platform/CoreClr/CoreCLRRuntimeEnvironment.cs#L104-L114.

**Comment by GSPP** [comment]
Another use case is verifying custom generated DLLs as a debugging aid. Invalid IL can be hard to detect and diagnose from just execution alone.

**Comment by ViktorHofer** [comment]
Would it make more sense to move the sources into the Arcade repository which allows easier packaging and serves as a central place for other repositories to consume assets?

**Comment by jkotas** [comment]
ilverify is in the same category as ilasm or ildasm. It is a generally applicable tool, not tied to .NET product engineering infrastructure. .NET Framework SDK includes equivalent tool called peverify. ilverify is the replacement for peverify.

Also, 90% of the ilverify code is shared with other components in CoreCLR. If we were to build it somewhere else, we would need to setup a source mirroring for this.

**Comment by ViktorHofer** [comment]
> Also, 90% of the ilverify code is shared with other components in CoreCLR

I see, then it makes sense to live in dotnet/runtime. Thanks for clarifying.

**Comment by BruceForstall** [comment]
@agocke @jkotas After https://github.com/dotnet/runtime/pull/35038, is this complete (can be closed)?

**Comment by jkotas** [comment]
Yes, this can be closed. I have verified that the package is produced by the official build.
