### ISSUE TITLE
JIT: Dead code at runtime not completely removed

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/runtime#13824]
The JIT doesn't properly remove dead code in certain instances. [Here's an example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ovLrmW4WADQAcSDdU0BmJqQZCaAbxoNfTF8xIDMAQEJIMBrgAggoIshxiYtAYMAAmABQAlD5+3tR+BUwA7AwxCCyR8YnJaQ4FAL40Ob7EAeRBxCil6aYYDNhoDLJi2FwAPMAAnikAfMHZ+bnNhbwAZgzpkWVVSVApGZkLhUuLxwXEAKxl6QPzdWeNp4UwkrgwywV5Z4WXAHIQ11uwEy92OjwaTSerW0HS6UVIPR4/UGw1GE2mMDmwOWXzOaw2ZQquB2NVSRzOuO+LSusRug2BoMK4LOLzeHxOVL8fwBtKBIPZvmZgsh5zasNKTkRfVuqPGU1m8xxAoY+M20ViJL2aSy5OOlKpl0B9P5Twhpr8rPe5t8+u+AHo7Qw2DB8BAFGkGMqhQxHssANoAWRgGAAFhBUgZxJJ0kHQ+HI2JJAB5MR8CBmFj/IySUymADmmQAustoYEmF1DbTesihiM5RisZkGJ4fSK/IHg2GI1GY5341GU2mM1muDmuPmiyWxeWmBd/tdqzK6+iFcDm63qPUgA==) that does some method dispatching based on CPU features:
```
public class C
{
    public static bool IsAvxSupported()
    {
        return Avx.IsSupported;
    }

    public static void A(int a, Span<byte> b)
    {
        if (IsAvxSupported())
            FuncAvx(a, b);
        else
            FuncNoAvx(a, b);
    }

    public static void A2(int a, Span<byte> b)
    {
        if (Avx.IsSupported)
            FuncAvx(a, b);
        else
            FuncNoAvx(a, b);
    }

    public static void A3(int a, Span<byte> b)
    {
        if (IsAvxSupported())
            FuncAvx(a, b);
        else
        {
            // Removed 
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void FuncAvx(int a, Span<byte> b) { }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void FuncNoAvx(int a, Span<byte> b) { }
}
```

`A1` Moves some arguments around on the stack unnecessarily.
```
G_M13277_IG01:
       sub      rsp, 56
       vzeroupper 
       xor      rax, rax
       mov      qword ptr [rsp+28H], rax

G_M13277_IG02:
       vmovdqu  xmm0, qword ptr [rdx]
       vmovdqu  qword ptr [rsp+28H], xmm0

G_M13277_IG03:
       lea      rdx, bword ptr [rsp+28H]
       call     C:FuncAvx(int,struct)
       nop      

G_M13277_IG04:
       add      rsp, 56
       ret
```

Manually inlining `IsAvxSupported` or removing the code from the `false` branch like in `A2` and `A3` make the JIT remove all those instructions, leaving just the call.
```
G_M62574_IG01:
       sub      rsp, 40
       nop      

G_M62574_IG02:
       call     C:FuncAvx(int,struct)
       nop      

G_M62574_IG03:
       add      rsp, 40
       ret   
```

category:cq
theme:optimization
skill-level:expert
cost:large

**Comment by AndyAyersMS** [comment]
Fixed by #1751.
