### ISSUE TITLE
System.Threading.Timer Not Running On Ubuntu server

### ISSUE THREAD

**Issue by andrewmcclellankibo** [dotnet/runtime#13839]
# System.Threading.Timer Not Running On Ubuntu server

# General
Created a worker service project, used a background service to create a timer function that followed:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio

When executing: running locally on windows, timer events trigger as expected.

Deployed to ubuntu server: timer events are never triggered.
Verified that the app is running, and no issues instantiating the timer, it just never actually triggers the timer.

**Comment by mangod9** [comment]
Hey @andrewmcclellankibo, I am unable to repro this issue -- I have created a fork of your repro here: https://github.com/mangod9/simpleworkerservice.  I updated the Timer to fire every 10s and I do see it firing in an Ubuntu 18.04 container. Could you please try and check if that works for you too -- If you have docker installed you can directly run it via VS. 

Thanks.

**Comment by mangod9** [comment]
Here is the output from bash:

```root@e721f3365f66:/app/bin/Debug/netcoreapp3.1# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
root@e721f3365f66:/app/bin/Debug/netcoreapp3.1# dotnet WorkerService.dll
info: WorkerService.Worker[0]
      Update Service running at: 04/15/2020 07:43:30 +00:00
info: WorkerService.UpdaterService[0]
      Updating Sales Information
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app/bin/Debug/netcoreapp3.1
info: WorkerService.Worker[0]
      Email Service running at: 04/15/2020 07:43:40 +00:00
info: WorkerService.EmailerService[0]
      Running Email Service
info: WorkerService.Worker[0]
      Email Service running at: 04/15/2020 07:43:50 +00:00
info: WorkerService.EmailerService[0]
      Running Email Service
info: WorkerService.Worker[0]
      Email Service running at: 04/15/2020 07:44:00 +00:00
info: WorkerService.EmailerService[0]
      Running Email Service
^Cinfo: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...```

**Comment by mangod9** [comment]
I am going to close this issue for now, @andrewmcclellankibo please reopen if you can still repro. Thx!
