### ISSUE TITLE
JIT: Optimize simple arithmetic with GT_NEG

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#13837]
I was surprised it's not handled in `morph`, e.g. `-a + b` => `b - a`.
```csharp
int M1(int a, int b) => -a +  b; // optimize to  "b - a"
int M2(int a, int b) =>  a + -b; // optimize to  "a - b"
int M3(int a, int b) =>  a - -b; // optimize to  "a + b"
int M4(int a, int b) => -a - -b; // optimize to  "b - a"
```
Current codegen:
```asm
; Method CC:M1(int,int):int:this
G_M48868_IG02:
       mov      eax, edx
       neg      eax
       add      eax, r8d

; Method CC:M2(int,int):int:this
G_M15271_IG02:
       mov      eax, r8d
       neg      eax
       add      eax, edx

; Method CC:M3(int,int):int:this
G_M13857_IG02:
       mov      eax, r8d
       neg      eax
       sub      edx, eax
       mov      eax, edx

; Method CC:M4(int,int):int:this
G_M28384_IG02:
       mov      eax, edx
       neg      eax
       mov      edx, r8d
       neg      edx
       sub      eax, edx
```
Expected codegen: https://godbolt.org/z/nmZxv8

Also:
```csharp

int M5(int a) =>  -a / 10;  // optimize to  "a / -10"
int M6(int a) => -(a / 10); // optimize to  "a / -10"
int M7(int a) =>  -a * 10;  // optimize to  "a * -10"
int M8(int a) => -(a * 10); // optimize to  "a * -10"
```

category:cq
theme:basic-cq
skill-level:beginner
cost:small

**Comment by JulieLeeMSFT** [comment]
With the help with Eugene, I was able to get optimized code for M1 to M4 as shown in https://godbolt.org/z/nmZxv8. 
Found some issues during jit-diff that does not handle cases where exception is thrown from both operands, and investigation WIP.

**Comment by JulieLeeMSFT** [comment]
That seems the best solution. We will skip transforming NEG when non negated operand is constant. Will check if bitwise shift pattern needs to be revisited where NEG was replaced with SUB pattern.

**Comment by JulieLeeMSFT** [comment]
Completed optimizing + and - operators. Will open a new issue to track * and /.
