### ISSUE TITLE
BUILD: Error: Failed to generate version headers . And System.TimeoutException

### ISSUE THREAD

**Issue by Kevin920920** [dotnet/runtime#13846]
E:\Downloads\coreclr-3.1.0>build.cmd
BUILD: Starting Build at 15:58:14.03
BUILD: Searching for Visual Studio 2017 or later installation
BUILD: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.1
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
BUILD: Commencing CoreCLR product build
BUILD: Checking prerequisites
BUILD: Number of processor cores 4
  未能从“https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.net.compilers.toolset/3.3.0-beta2-19367-02/microsoft.net.compilers.toolset.3.3.0-beta2-19367-02.nupkg”下载包“Microsoft.Net.Compilers.Toolset.3.3.0-beta2-19367-02”。
  由于在 60000 毫秒内未接收到数据，“https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.net.compilers.toolset/3.3.0-beta2-19367-02/microsoft.net.compilers.toolset.3.3.0-beta2-19367-02.nupkg”的下载超时。
    Exception of type 'System.TimeoutException' was thrown.
  未能从“https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.net.compilers.toolset/3.3.0-beta2-19367-02/microsoft.net.compilers.toolset.3.3.0-beta2-19367-02.nupkg”下载包“Microsoft.Net.Compilers.Toolset.3.3.0-beta2-19367-02”。
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
    远程主机强迫关闭了一个现有的连接。
  E:\Downloads\coreclr-3.1.0\eng\empty.csproj 的还原在 17.91 min 内完成。
E:\Downloads\coreclr-3.1.0\.packages\microsoft.build.tasks.git\1.0.0-beta2-19367-01\build\Microsoft.Build.Tasks.Git.targets(24,5): error : 无法定位包含目录 'E:\Downloads\coreclr-3.1.0\eng' 的存储库。 [E:\Downloads\coreclr-3.1.0\eng\empty.csproj]
E:\Downloads\coreclr-3.1.0\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\Version.targets(53,5): error : SourceRevisionId is not set, which means the SourceLink targets are not included in the build. Those are needed to produce a correct sha for our build outputs. [E:\Downloads\coreclr-3.1.0\eng\empty.csproj]

生成失败。

E:\Downloads\coreclr-3.1.0\.packages\microsoft.build.tasks.git\1.0.0-beta2-19367-01\build\Microsoft.Build.Tasks.Git.targets(24,5): error : 无法定位包含目录 'E:\Downloads\coreclr-3.1.0\eng' 的存储库。 [E:\Downloads\coreclr-3.1.0\eng\empty.csproj]
E:\Downloads\coreclr-3.1.0\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\Version.targets(53,5): error : SourceRevisionId is not set, which means the SourceLink targets are not included in the build. Those are needed to produce a correct sha for our build outputs. [E:\Downloads\coreclr-3.1.0\eng\empty.csproj]
    0 个警告
    2 个错误

已用时间 00:17:55.82
Build failed.
BUILD: Error: Failed to generate version headers.

**Comment by AaronRobinsonMSFT** [comment]
@Kevin920920 We are going to close this due to non-activity. If you are still having issues please respond here and we can reopen. Thank you.
