### ISSUE TITLE
MatchingRefApiCompat issues in System.ServiceModel.Syndication

### ISSUE THREAD

**Issue by weshaggard** [dotnet/runtime#1393]
See baseline file
https://github.com/dotnet/corefx/blob/master/src/System.ServiceModel.Syndication/src/MatchingRefApiCompatBaseline.netstandard.txt

We should do one of the following:
1. Expose the APIs publicly in the reference assembly
2. Make the APIs in the implementation internal
3. Add a comment to the baseline file why you cannot do either (1) or (2) and keep them baselined.

See PR https://github.com/dotnet/corefx/pull/27881/ for extra context.

**Comment by StephenBonikowsky** [comment]
If this still applies in the current build system please feel free to re-open.
