### ISSUE TITLE
FileSystem cross platformness and testability

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#13946]
Building cross platform applications that talk to the file system is painful. There are several issues like case sensitivity, slash differences and other bizarre restrictions and differences.

On another front, testability of the file system has always been impossible with .NET. Any application/library that uses the FileSystem uses something like https://www.nuget.org/packages/System.IO.Abstractions or a custom abstraction to allow mockability. 

 Are there any plans to improve the System.IO API to solve some of these problems?

**Comment by carlossanlop** [comment]
This issue is too wide. We already have individual issues tracking each one of the requests listed in this comment: https://github.com/dotnet/runtime/issues/13946#issuecomment-69137144

So I'll close this in favor of the individual API proposals and issues requesting improvements.

**Comment by rmunn** [comment]
@carlossanlop - It would be nice to have a list of the individual issues tracking those requests so I can subscribe to them. Some of them I might be able to search for, but some I don't know what search keywords to use. Since you already know what those issues are, perhaps you could add a comment listing them? Would be appreciated.

**Comment by carlossanlop** [comment]
- For file casing: https://github.com/dotnet/runtime/issues/14321
- For Unix ACLs: https://github.com/dotnet/runtime/issues/928
- Project tracking FileSystem related issues and PRs: https://github.com/dotnet/runtime/projects/42
- Project tracking Symbolic links/Reparse points/Junctions issues and PRs: https://github.com/dotnet/runtime/projects/41

Please feel free to open new issues for individual feature requests, it's easier to track than a general issue.

cc @Jozkee
