### ISSUE TITLE
Xml_TypeWithReadOnlyMyCollectionProperty failing on CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#1395]
on all configurations.

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38676~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.40/workItem/System.Xml.XmlSchemaSet.Tests

**Comment by HongGit** [comment]
@Benjie-Liu  could you please see if this still repro?

**Comment by HongGit** [comment]
@ViktorHofer is this still an issue for you?

**Comment by HongGit** [comment]
@ViktorHofer we couldn't repro the issue, can you please let us know whether this test  still fails in recent runs?

**Comment by krwq** [comment]
@joperezr I'm removing this from our project board since this is owned by serialization team (assuming they can even repro)

**Comment by krwq** [comment]
@HongGit I think we can close this and wait if repros again since it's not actionable at the moment and we haven't seen any reports in the last year
