### ISSUE TITLE
String comparer for sorting numeric strings logically

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/runtime#13979]
## Rationale

For sorting purposes it's common to need portions of strings containing numbers to be treated like numbers. Consider the list of strings `"Windows 7", "Windows 10"`.

Using the `Ordinal` `StringComparer` to sort the list one would get

```
Windows 10
Windows 7
```

but the desired ascending logical sort would be

```
Windows 7
Windows 10
```

## Proposed API

```diff
 namespace System {
     public class StringComparer {
+        public static StringComparer Create(CultureInfo culture, CompareOptions options);
     }
 }
 namespace System.Globalization {
     public enum CompareOptions {
+        NumericOrdering = 0x00000020
     }
 }
```

## Usage

```cs
var list = new List<string> { "Windows 10", "Windows 7" };
list.Sort(StringComparer.Logical); // List is now "Windows 7", "Windows 10"
```

This would also be good for sorting strings containing IP addresses.

## Details

* `Logical` is a convenience property equivalent to the result of `Create(CultureInfo.CurrentCulture, CompareOptions.Logical)`
* `LogicalIgnoreCase` is a convenience property equivalent to the result of `Create(CultureInfo.CurrentCulture, CompareOptions.Logical | CompareOptions.IgnoreCase)`
* Non-numeric sequences will be evaluated with the culture provided.
* Numeric sequences will be determined by the result of `Char.IsDigit`.
* All UTF-16 digits will be supported and are manually parsed using `Char.GetNumericValue`.
* Only positive integral values without digit separators will be supported directly.
* Numbers will be treated as `ulong`s. Logic for overflows will have to be considered.
* The string `Windows 8.1` would be considered 4 sequences. The `Windows ` would be a string sequence, the `8` would be a numeric sequence, the `.` would be another string sequence, and the `1` would be another numeric sequence.
* This API could later be expanded to include support for allowing signs, decimals, and digit separators through the use of overloads accepting a `NumberStyles` parameter.
* When a numeric and string sequence are considered at the same time the numeric sequence always comes before the string sequence so when sorting the following list, `"a", "7"` the number `7` will be sorted before the letter `a`.
* Existing methods that take a `CompareOptions` parameter as input will need to be updated to support the new `Logical` member.

## Open Questions

* Should `CompareOptions.Logical` be implemented as the flag option `SORT_DIGITSASNUMBERS` to the `dwCmpFlags` parameter of [`CompareStringEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317761(v=vs.85).aspx)? Using it's implementation should be more efficient but later expanding support for `NumberStyles` will require a re-implementation with matching behavior.

## Updates

* Added `Logical` and `LogicalIgnoreCase` properties.
* Added support for all UTF-16 digits.
* Added more `CreateLogical` overloads to match the `Create` method.
* Added retrieval of the `NumberFormatInfo` from the `StringComparer` parameter when not explicitly provided and is a `CultureAwareComparer`.
* Removed `CreateLogical` overloads that matched the `Create` method.
* Switched to only supporting positive integral values without digit separators.
* Added consideration of comparing a numeric sequence with a string sequence.
* Added the flag member `CompareOptions.Logical` and changed `CreateLogical` to be just an overload of `Create`.

**Comment by BrianH12345** [comment]
Is this useful?:   https://natsort.readthedocs.io/en/master/index.html

**Comment by rixtech** [comment]
In addition to the natural sort order for PowerShell/PowerShell#12931 as a user I want a natural sorting order when listing files using the `dir` command in `CMD.exe`. An additional sortorder switch will be required , _N_ is already in use, so perhaps _L_.  Also, the new switch should be treated as a valid preset by `%DIRCMD%`

**Comment by jnm2** [comment]
@rixtech This repository is not related to cmd.exe.

**Comment by rixtech** [comment]
> @rixtech This repository is not related to cmd.exe.
Fair enough, but PowerShell/PowerShell#12931 issue said to vote here as the PowerShell natural sort is dependent on this issue. When PowerShell gets the fix, I would want cmd.exe to get the fix too for consistency.

**Comment by KalleOlaviNiemitalo** [comment]
@rixtech, some `CMD.exe` issues are tracked in <https://github.com/microsoft/terminal/issues?q=is%3Aissue+label%3AProduct-Cmd.exe>, but changes are usually rejected because of compatibility risks.

**Comment by madelson** [comment]
Has the interaction with various `CompareOptions` flags been considered? For example, does `IgnoreNonSpace`/`IgnoreSymbols` affect the detection of numeric segments or does it only affect comparison within non-numeric segments? Are there any flags that should throw when combined with `Logical`?

Also, are leading zeros supposed to receive any special treatment? For example, does `"a 01 b"` compare equal to `"a 1 b"`?

**Comment by tarekgh** [comment]
@madelson when we implement this feature (with ICU), we'll use [UCOL_NUMERIC_COLLATION](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucol_8h.html#a583fbe7fc4a850e2fcc692e766d2826c). This will enable sorting digits only (no separator, symbols, or negative signs is supported). 

```
UCOL_NUMERIC_COLLATION | When turned on, this attribute makes substrings of digits sort according to their numeric values.This is a way to get '100' to sort AFTER '2'. Note that the longest digit substring that can be treated as a single unit is 254 digits (not counting leading zeros). If a digit substring is longer than that, the digits beyond the limit will be treated as a separate digit substring.A "digit" in this sense is a code point with General_Category=Nd, which does not include circled numbers, roman numerals, etc. Only a contiguous digit substring is considered, that is, non-negative integers without separators. There is no support for plus/minus signs, decimals, exponents, etc.Stable:ICU 2.8
```

> re leading zeros supposed to receive any special treatment? For example, does "a 01 b" compare equal to "a 1 b"?

Yes, these 2 strings will be equal. 

In short, we are not going to perform this numeric sorting manually, instead we'll use the underlying libraries (ICU or NLS) to do the job.

**Comment by pompushko** [comment]
voting for that

**Comment by victorgoebel** [comment]
This issue has been open since 2015 so assuming it won't get done?

I'm using **[NaturalStringExtensions](https://github.com/augustoproiete/NaturalStringExtensions)** for now which seems to work well.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/73068340/202322895-72c7c52c-62ca-44c2-9bb2-44976f68c518.png">

**Comment by Gnbrkm41** [comment]
Wow, it has been 8 years since this issue was first opened. What's the status on this?

So the current status is that we have these APIs approved:
```diff
namespace System {
     public class StringComparer {
+        public static StringComparer Create(CultureInfo culture, CompareOptions options);
     }
}
namespace System.Globalization {
     public enum CompareOptions {
+        NumericOrdering = 0x00000020
     }
 }
```

and from what I see we decided that we'll just use the default available sorting available in the globalisation library (either ICS or NCU) without implementing those ourselves, at least for now.... Is there any other things that we might be missing, that prevents this from going forward?

**Comment by tannergooding** [comment]
Just needs someone with time to implement it. There's been tons of other work and this hasn't bubbled up such that I've been able to do it myself yet.

**Comment by Gnbrkm41** [comment]
I haven't touched the dotnet/runtime repo for quite a while but I'm willing to give it a go if that's the only thing blocking it from happening. I might even have something I was working on a while ago (although it was years ago and I imagine it'll need to be torn down to fit what we have now...).

**Comment by zotabee** [comment]
I hope this will be implemented one day!

This is a critical lacking feature.

**Comment by zotabee** [comment]
> > This is a critical lacking feature.
> 
> `dotnet add package NaturalSort.Extension` gives you `StringComparison.OrdinalIgnoreCase.WithNaturalSort()` https://github.com/tompazourek/NaturalSort.Extension#usage not everything has to come from bcl to make it count

Thanks,. But is this usuable in PowerShell for example or only in C# ?

**Comment by siegfriedpammer** [comment]
> > This is a critical lacking feature.
> 
> `dotnet add package NaturalSort.Extension` gives you `StringComparison.OrdinalIgnoreCase.WithNaturalSort()` [tompazourek/NaturalSort.Extension#usage](https://github.com/tompazourek/NaturalSort.Extension#usage) not everything has to come from bcl to make it count

@kasperk81 Unfortunately, the implementation has a Unicode bug, when compared to `StrCmpLogicalW`: https://github.com/tompazourek/NaturalSort.Extension/issues/74

I'd argue that it would make a lot of sense to have this added to the BCL to prevent others falling into the same Unicode traps over and over again. Also, googling for this yields a lot of different approaches that all have similar bugs or are just badly implemented. If there were a comparer provided by the BCL it could be highly optimized and it would quickly become the first search result and people would just use that.

I agree with @sharwell that using `StrCmpLogicalW` as a reference is problematic, but my point still stands that correct Unicode support is necessary but tricky.

**Comment by siegfriedpammer** [comment]
It's a bug when certain characters that are seen as "natural" numbers in some cultures and even recognized by the Unicode Standard are not treated as such, imho. Similarly, as a native speaker of German, I would be annoyed if Ä was sorted after Z instead of after A, just because the guy implementing the "natural" sort didn't see it as natural or didn't know about it.

**Comment by siegfriedpammer** [comment]
Yes, as I already pointed out

> I agree with @sharwell that using StrCmpLogicalW as a reference is problematic, but my point still stands that correct Unicode support is necessary but tricky.

I am solely interested in getting proper Unicode support and the Win API does a better job at that than the alternatives I found. At this point for me it's only about Unicode and nothing else.

**Comment by CyrusNajmabadi** [comment]
Could you submit that support to that open source library you reported the bug to?

**Comment by tompazourek** [comment]
> Could you submit that support to that open source library you reported the bug to?

I think it's my library and this issue: https://github.com/tompazourek/NaturalSort.Extension/issues/74

I just added the Unicode support.

**Comment by CyrusNajmabadi** [comment]
@tompazourek thanks very much! :)

**Comment by iSazonov** [comment]
@tannergooding @tarekgh ICU is now well integrated into Runtime and probably most of the work has already been done. Is there a chance to include this in .Net 9?

**Comment by IDisposable** [comment]
@tannergooding I would like to take getting this over the finish line... are the API reviews current and approved still?

**Comment by tarekgh** [comment]
This will be risky to do it now. Let's plan doing it early next cycle.

**Comment by jeffhandley** [comment]
Assigning to @PranavSenthilnathan to try to get this in for .NET 10 Preview 1.
