### ISSUE TITLE
Improve DCS/DCJS's Performance in ReflectionOnly Mode

### ISSUE THREAD

**Issue by shmao** [dotnet/runtime#1397]
We did a few performance optimization for ReflectionOnly mode, see the following PRs,
- https://github.com/dotnet/corefx/pull/9702
- https://github.com/dotnet/corefx/pull/9547

But the reflection based serialization is still much slower than serialization using IL generation. We'd like to further optimize it.

**Comment by StephenBonikowsky** [comment]
Perf improvements will be triggered when adding new features/functionality.
