### ISSUE TITLE
Add Enum.SetFlag and Enum.RemoveFlag to make bitwise flagging easier

### ISSUE THREAD

**Issue by yufeih** [dotnet/runtime#14084]
To maintain multiple bool states in a class, instead of declaring many bool fields, an enum flag can be used to compact these states in to a single member to optimize for memory usage.

``` c#
[Flags] enum DirtyFlags { X = 1, Y = 1 << 1, Z = 1 << 2 };

DirtyFlags dirtyFlags = DirtyFlags.X | DirtyFlags.Y | DirtyFlags.Z;
```

It is simple to test if a flag is set using `Enum.HasFlag(DirtyFlags.X)`, but the scenario is not complete. Without the ability to set and remove a flag, the following code needs to be maintained manually:

``` c#
// Setting a flag
dirtyFlags |= DirtyFlags.X;
// Removing a flag, this is harder to remember :(
dirtyFlags &= ^DirtyFlags.X;
```

The suggestion is to add 2 methods to Enum to help set and clear a flag.

``` c#
public bool HasFlag(Enum flag); // This method already exists
public bool SetFlag(Enum flag);
public bool RemoveFlag(Enum flag);
```

These methods should be aggressively inlined since bitwise manipulations is very likely to be used in a performance sensitive scenario.

**Comment by danmosemsft** [comment]
This isn't required to ship 5.0

**Comment by adamsitnik** [comment]
@danmosemsft Is there any chance we could introduce this API in 6.0? I find myself implementing it in every project I use ;)

**Comment by danmosemsft** [comment]
@adamsitnik if you are passionate about it your next step would be to get to api-ready-for-review and represent at API review.

**Comment by zgabi** [comment]
There should be a non-generic version of the SetFlag/WithFlags/RemoveFlags/WithoutFlags, too.

For example: 
public static object SetFlag(Type enumType, object value, object flag)
Or with ref parameter.

Similar to the Parse/TryParse methods: https://github.com/dotnet/runtime/issues/14083

**Comment by mburbea** [comment]
I would propose the following api to solve this:
```diff
public class Enum: ValueType
{
+public T SetFlag<T>(T flag, bool condition = true) where T:struct,Enum;
+public T UnsetFlag<T>(T flag) where T:struct,Enum => SetFlag(flag, false);
}
```
I wrote this as an extension recently while updating a wpf application that bound several checkboxes to a single flagged enum. This made the properties I bound to on my object model nice and symmetric.
e.g.
```cs
        public bool IsStolen
        {
            get => _flags.HasFlag(InventoryFlags.IsFromStolenSource);
            set => _flags = _flags.SetFlag(InventoryFlags.IsFromStolenSource, value);
        }
```

Unfortunately the implementation itself was super hideous.
```cs
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static T SetFlag<T>(this T @enum, T flag, bool on = true)
            where T:unmanaged,Enum
        {
            if (Unsafe.SizeOf<T>() == 1)
            {
                byte x = (byte)((Unsafe.As<T, byte>(ref @enum) & ~Unsafe.As<T, byte>(ref flag))
                    | (-Unsafe.As<bool, byte>(ref on) & Unsafe.As<T, byte>(ref flag)));
                return Unsafe.As<byte, T>(ref x);
            }
            else if (Unsafe.SizeOf<T>() == 2)
            {
                ushort x = (ushort)((Unsafe.As<T, ushort>(ref @enum) & ~Unsafe.As<T, ushort>(ref flag))
                    | (-Unsafe.As<bool, byte>(ref on) & Unsafe.As<T, ushort>(ref flag)));
                return Unsafe.As<ushort, T>(ref x);
            }
            else if (Unsafe.SizeOf<T>() == 4)
            {
                uint x = (Unsafe.As<T, uint>(ref @enum) & ~Unsafe.As<T, uint>(ref flag))
                   | ((uint)-Unsafe.As<bool, byte>(ref on) & Unsafe.As<T, uint>(ref flag));
                return Unsafe.As<uint, T>(ref x);
            }
            else
            {
                ulong x = (Unsafe.As<T, ulong>(ref @enum) & ~Unsafe.As<T, ulong>(ref flag))
                   | ((ulong)-(long)Unsafe.As<bool, byte>(ref on) & Unsafe.As<T, ulong>(ref flag));
                return Unsafe.As<ulong, T>(ref x);
            }
        }
```

**Comment by NN---** [comment]
Another possible implementation: https://github.com/rsdn/CodeJam/blob/master/CodeJam.Main/EnumHelper.cs#L375

**Comment by hopperpl** [comment]
What is the state of this now? Before I start yet another round of API suggestions for Enum.HasAnyFlag() et al.

Enum.HasFlag is now inlined without performance penalty and it makes code look better, imo. And as a bonus in DEBUG it comes with a type check. Set/Unset/Has/HasAny will also avoid endless castings to/from int as the compiler is not smart enough to do it automatically.

This is 6.5 years old. There should be a decision now if it will be added or dropped.

**Comment by tannergooding** [comment]
@jkotas, any concerns on adding additional APIs to `System.Enum` here. It sounds like there would be 1-3 APIs and there has been continued interest since the initial proposal 7 years ago.

The three core scenarios are "set", "clear", and "toggle". Which could be handled via a single API:
```csharp
public static TEnum SetFlag<TEnum>(TEnum value, TEnum flag, bool value);
```

or a set of APIs:
```csharp
public static TEnum ClearFlag<TEnum>(TEnum value, TEnum flag);
public static TEnum SetFlag<TEnum>(TEnum value, TEnum flag);
public static TEnum ToggleFlag<TEnum>(TEnum value, TEnum flag);
```

names up for debate, as would be whether they are instance or static.

**Comment by danmoseley** [comment]
cc @stephentoub here, since as I recall in a previous issue, he argued against providing alternative syntactic sugar to do basic flags operations. Instead we should just make sure that the standard way of writing such things (which is not C# specific) is efficient. I have to say I agree. When I see one of these methods, I would wonder which one to use.

Apologies for overlooking the ping to me higher up.

**Comment by stephentoub** [comment]
We've closed other related proposals, e.g. https://github.com/dotnet/runtime/issues/66261. @jkotas has also expressed an opinion similar to mine, e.g. https://github.com/dotnet/runtime/issues/55455#issuecomment-877635897, and also highlighted that just doing the idiomatic bit operations are guaranteed to be efficient where such named methods aren't, e.g. https://github.com/dotnet/runtime/issues/55455#issuecomment-877639565.

**Comment by tannergooding** [comment]
Closing as per the comments above.
