### ISSUE TITLE
Implement ForEachAsync in System.Collections.Concurrent

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#14088]
@stephentoub has some great blog posts about higher level operations that can be implemented all using public API that exists today. Some of these would be great to see in the library itself:

http://blogs.msdn.com/b/pfxteam/archive/2012/03/05/10278165.aspx

In particular

``` C#
public static Task ForEachAsync<T>(this IEnumerable<T> source, Func<T, Task> body) 
{ 
    return Task.WhenAll( 
        from item in source 
        select Task.Run(() => body(item))); 
}
```

And 

``` C#
public static Task ForEachAsync<T>(this IEnumerable<T> source, int dop, Func<T, Task> body) 
{ 
    return Task.WhenAll( 
        from partition in Partitioner.Create(source).GetPartitions(dop) 
        select Task.Run(async delegate { 
            using (partition) 
                while (partition.MoveNext()) 
                    await body(partition.Current); 
        })); 
}
```

**Comment by eiriktsarpalis** [comment]
Echoing @stephentoub's comments, I think it might make sense to encourage users to author their own variations of the above helper methods. I'm going to close this issue.

**Comment by stephentoub** [comment]
This is a dup anyway of https://github.com/dotnet/runtime/issues/1946, where much more discussion has happened.
