### ISSUE TITLE
Is there any way to change Transaction's MaxTimeout or any plan to make possible it?

### ISSUE THREAD

**Issue by JP3BGY** [dotnet/runtime#1418]
https://github.com/dotnet/corefx/blob/a4f5f13ec1fa0d51ce0964c126e35ef0046ea7be/src/System.Transactions.Local/src/System/Transactions/Configuration/MachineSettingsSection.cs#L7-L26

It seems there is no way to change Transaction's MaxTimeout in .NET Core.
Is there any way to change it or any plan to make it possible?

**Comment by davilko** [comment]
> https://github.com/dotnet/corefx/blob/a4f5f13ec1fa0d51ce0964c126e35ef0046ea7be/src/System.Transactions.Local/src/System/Transactions/Configuration/MachineSettingsSection.cs#L7-L26
> 
> It seems there is no way to change Transaction's MaxTimeout in .NET Core.
> Is there any way to change it or any plan to make it possible?

What about reflection ?
It seems to me that it should work 
`public static class MaxTransactionHack
    {
        public static void SetMaxTransactionTimeout(TimeSpan value)
        {
            var assembly = Assembly.GetAssembly(typeof(TransactionManager));
            var instance = assembly?.CreateInstance("System.Transactions.Configuration.MachineSettingsSection");
            var instanceType = instance?.GetType();
            var sMaxTimeout = instanceType?.GetFields(BindingFlags.Static | BindingFlags.NonPublic)
                .SingleOrDefault(f => f.Name.Contains("maxTimeout", StringComparison.OrdinalIgnoreCase));
            sMaxTimeout?.SetValue(null, value); 
        }
    }`

**Comment by aperisic** [comment]
static private void ConfigureTransactionTimeout(TimeSpan value)
        {
            SetTransactionManagerField("s_cachedMaxTimeout", true);
            SetTransactionManagerField("s_maximumTimeout", value);
        }

 

        static private void SetTransactionManagerField(string fieldName, object value)
        {
            var cacheField = typeof (TransactionManager).GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Static);
            cacheField.SetValue(null, value);
        }
 
In .NetCore 3.1 (the internal names might be different in other versions)

**Comment by NikitaEgorov** [comment]
NServiceBus already documented reflection way for .net core
https://docs.particular.net/samples/azure-service-bus-netstandard/lock-renewal/

```csharp
static void ConfigureTransactionTimeoutCore(TimeSpan timeout)
{
    SetTransactionManagerField("s_cachedMaxTimeout", true);
    SetTransactionManagerField("s_maximumTimeout", timeout);

    void SetTransactionManagerField(string fieldName, object value) =>
        typeof(TransactionManager)
            .GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Static)
            .SetValue(null, value);
}
```

**Comment by aperisic** [comment]
Quite sure it was not there last time I looked at it.

**Comment by HebaruSan** [comment]
> Why not adding a Set on TransactionManager.MaximumTimeout? I don't see the point of requiring a machine configuration setting or something else utterly complex.

That would be an improvement, but then they might as well just _eliminate_ this property and unconditionally honor whatever timeout the calling code passes to `TransactionScope`'s constructor. After all, it's my transaction, and I know what it's doing and the context in which it runs. Why bother imposing _any_ arbitrary time limit?

**Comment by ethanbishop** [comment]
Just ran into this in .NET 6 - ghost and @NikitaEgorov 's reflection workaround still works a treat.

> That would be an improvement, but then they might as well just _eliminate_ this property and unconditionally honor whatever timeout the calling code passes to `TransactionScope`'s constructor. After all, it's my transaction, and I know what it's doing and the context in which it runs. Why bother imposing _any_ arbitrary time limit?

Totally agree with this, I don't think there's any point in this maximum any more. As long as `TransactionManager.DefaultTimeout` is honoured when not providing a timeout (you probably should have to opt in to "no timeout", and only if you *really* know what you're doing), I don't see the point in a silent restriction you need to find out about.

Looking at the source of [https://github.com/dotnet/runtime/blob/main/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionManager.cs#L393](TransactionManager), setting `s_maximumTimeout` to `TimeSpan.Zero` should just disable the maximum altogether, so I ended up with this very similar workaround:

```cs
static void DisableGlobalTransactionTimeout()
{
    SetTransactionManagerField("s_cachedMaxTimeout", true);
    SetTransactionManagerField("s_maximumTimeout", TimeSpan.Zero);

    void SetTransactionManagerField(string fieldName, object value) =>
        typeof(TransactionManager)
            .GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Static)?
            .SetValue(null, value);
}
```

**Comment by ktrace2** [comment]
I also just hit this issue when migrating a .NET Framework application to .NET 6. Having the ability to customize or disable this maximum through code would be very useful. Using the workaround above worked.

**Comment by roshandangol1** [comment]
> ```
>       static private void ConfigureTransactionTimeout(TimeSpan value)
>         {
>             SetTransactionManagerField("s_cachedMaxTimeout", true);
>             SetTransactionManagerField("s_maximumTimeout", value);
>         }
> 
>         static private void SetTransactionManagerField(string fieldName, object value)
>         {
>             var cacheField = typeof (TransactionManager).GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Static);
>             cacheField.SetValue(null, value);
>         }
> ```
> 
> In .NetCore 3.1 (the internal names might be different in other versions)

**Comment by hangy** [comment]
With .NET 7, the reflection workaround should not be required any more. #71703

**Comment by StephenMolloy** [comment]
This was fixed in .Net 7 by #71703. We are unable to add new API's to .Net 6, so the reflection workaround will be necessary on .Net versions earlier than 7.
