### ISSUE TITLE
System.Runtime.Caching.MemoryCacheStatistics.SetTrimStats DivideByZeroException

### ISSUE THREAD

**Issue by StephenMolloy** [dotnet/runtime#1423]
From VS Feedback for .Net 4.5.2 - https://developercommunity.visualstudio.com/content/problem/539608/net-452-systemruntimecachingmemorycachestatisticss.html

1. private readonly MemoryCache messageStore = new MemoryCache("Message Store");
2. Thread 1: this.messageStore.Add(messageId, message, new CacheItemPolicy { AbsoluteExpiration = DateTimeOffset.UtcNow.AddMinutes(5), RemovedCallback = arguments => { if (arguments.RemovedReason == CacheEntryRemovedReason.Expired) { // Logging ... } } })
3. Timer Thread (System.Threading.Timer):this.messageStore.GetCount();
4. Thread 2: this.messageStore.Get
5. Thread Pool (TPL): this.messageStore.Remove

System.DivideByZeroException: Es wurde versucht, durch 0 (null) zu teilen. bei System.Runtime.Caching.MemoryCacheStatistics.SetTrimStats(Int64 trimDurationTicks, Int64 totalCountBeforeTrim, Int64 trimCount) bei System.Runtime.Caching.MemoryCacheStatistics.CacheManagerThread(Int32 minPercent) bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) bei System.Threading.TimerQueueTimer.CallCallback() bei System.Threading.TimerQueueTimer.Fire() bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() bei System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by wanxms** [comment]
Hi @StephenMolloy, we also hit this exception in one of our internal services. However I cannot find much information except this thread. I wonder do we have a workaround for this issue currently?

**Comment by StephenMolloy** [comment]
From the Feedback issue linked in the description, there is a simple workaround:

> As a workaround, you may find that adding a single non-removable sentinel item to the cache when it is created should help avoid this issue.

I hope to look at this issue again for 6.0, but I am currently balancing other priorities in other areas that are more impactful and don't have workarounds.
