### ISSUE TITLE
MemoryCache use of seldom used fields

### ISSUE THREAD

**Issue by zerogouki** [dotnet/runtime#1425]
I've noticed that a portion of the memory allocated by [MemoryCache ](https://github.com/dotnet/corefx/blob/0cc22ccba707d7552159363d586262fa9c4e8a2a/src/System.Runtime.Caching/src/System/Runtime/Caching/MemoryCacheEntry.cs) is on this internal class called [SeldomUsedFields](https://github.com/dotnet/corefx/blob/0cc22ccba707d7552159363d586262fa9c4e8a2a/src/System.Runtime.Caching/src/System/Runtime/Caching/MemoryCacheEntry.cs#L33) and it seems to me that it is being allocated without reason most of the time.
MemoryCacheEntry, which is the object holding the value on the cache store, checks whether there are interested parties to receive notifications but it does so by checking if the collection is null 
https://github.com/dotnet/corefx/blob/0cc22ccba707d7552159363d586262fa9c4e8a2a/src/System.Runtime.Caching/src/System/Runtime/Caching/MemoryCacheEntry.cs#L149-L154

however it will never be null when a cache policy is present since CacheItemPolicy will not allow it 

https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Runtime.Caching/src/System/Runtime/Caching/CacheItemPolicy.cs#L25-L35

Therefore I dont see how it is posible to tell MemoryCache to use an expiration offset (or any other kind of directive) and at the same time avoid SeldomUsedFields allocations. Is the condition (checking for nulls) wrong or is there another way to skip SeldomUsedFields to reduce allocated memory? We're trying to store between 300k and 500k objects and it would make an impact on that effort.

**Comment by StephenBonikowsky** [comment]
Impacting perf.
