### ISSUE TITLE
MonoTests.System.Runtime.Caching.MemoryCacheTest.Contains failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#1429]
https://dev.azure.com/dnceng/public/_build/results?buildId=203415&view=ms.vss-test-web.build-test-results-tab&runId=4922022&resultId=158673&paneView=debug
netfx-Windows_NT-Release-x86-Windows.10.Amd64.ClientRS5.Open
```

Error message
Assert.True() Failure\r\nExpected: True\r\nActual: False

Stack trace
   at MonoTests.System.Runtime.Caching.MemoryCacheTest.Contains() in /_/src/System.Runtime.Caching/tests/System.Runtime.Caching/MemoryCacheTest.cs:line 274
```

**Comment by StephenMolloy** [comment]
I don't believe this should be failing. But just in case some funky thread timings were getting in the way, there was some leeway in the test for using more forgiving timings without lengthening the test. So I will re-enable this test.
