### ISSUE TITLE
Proposal: Add new property for getting process path

### ISSUE THREAD

**Issue by Giorgi** [dotnet/runtime#14319]
## Rationale and Usage

In order to get process path you need to use `someProcess.MainModule.FileName` property. However it suffers from a couple of issue:
- Accessing MainModule of 64 bit process from a 32 bit one throws an exception
- You can't access MainModule of elevated process from a non elevated one

As you can see many developers [encounter](http://stackoverflow.com/q/8431298/239438) [these](http://stackoverflow.com/q/9501771/239438) issues.

I suggest adding a new property which returns the path to executable of the Process. To overcome the issues that I described we can use `QueryFullProcessImageName` together with `PROCESS_QUERY_LIMITED_INFORMATION` access right.

## Api Proposal

```csharp    
namespace System.Diagnostics
{
     public class  Process : Component
     {
           public string MainModuleFilePath { get; }
     }
}
```

## Open Questions
Should the new property be called `MainModuleFilePath` or something else? From my own experience most of people use `Path` when asking question on stackoverflow but @Priya91 suggested calling it `MainModuleFilePath` as it is returning Path of the `MainModule` property.

## Cross Platform Support
To implement this property on other platforms on Linux we can use `readlink` to read the value of `"/proc/%d/exe"` symlink and on OS X we can use `proc_pidpath` which returns process path given process pid.

**Comment by eiriktsarpalis** [comment]
This seems like a reasonable request, however given there has been limited interest for producing an API proposal, perhaps we should close?

**Comment by Giorgi** [comment]
@eiriktsarpalis As I have [already said](https://github.com/dotnet/runtime/issues/14319#issuecomment-348340938) I haven't sent a PR because the suggested api was rejected but I can't think of a better api for getting process path.
