### ISSUE TITLE
Provide ConcurrentDictionary the ability to set initial capacity with DefaultConcurrencyLevel

### ISSUE THREAD

**Issue by dotnetchris** [dotnet/runtime#14376]
It's absurdly difficult to create a ConcurrentDictionary with an initial capacity. This forces you to set the arcane DefaultConcurrencyLevel integer. I absolutely want to defer that to the platform. This leads to using this horrific code:

``` c#
(int)typeof(ConcurrentDictionary<,>).MakeGenericType(typeof(int), typeof(int))
    .GetProperty("DefaultConcurrencyLevel", BindingFlags.Static | BindingFlags.NonPublic)
    .GetValue(new ConcurrentDictionary<int, int>());
```

So either add a constructor that allows this. Add magic number support that providing < 1 results in this, or just make DefaultConcurrencyLevel be a public property.

**Comment by eiriktsarpalis** [comment]
Triage: `DefaultConcurrencyLevel` value is just `Environment.ProcessorCount`, so the problem can be worked around by doing `new ConcurrentDictionary<_,_>(Environment.ProcessorCount, myCapacity, ...)` without using reflection. 

Given there haven't been any API proposals in quite some time, I'm closing this.
