### ISSUE TITLE
Environment.SetEnvironmentVariable() messing up system variables and registry keys

### ISSUE THREAD

**Issue by vexx32** [dotnet/runtime#1438]
This issue was first reported here: https://github.com/microsoft/dotnet-framework-early-access/issues/58

Again here: https://github.com/dotnet/corefx/issues/36449

And now I'm reporting it here. This API is _broken_. There is currently no safe way in **any** version of .NET to set the windows PATH variables without breaking them beyond repair, as there is no support for expandable tokens.

## Issue Details

Information from the original issue(s) is quoted below:

> If you use `Environment.SetEnvironmentVariable()` to change `PATH` environment variable it will lead to the expansion of its content (any `%var%` contained in `PATH` variable will get replaced with its content), and the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\Path` type will be changed from `REG_EXPAND_SZ` to `REG_SZ`.
> 
> What is worse, if you are running a 32-bit application on a 64-bit OS, expansions for system variables such as `%CommonProgramFiles%`, `%COMSPEC%`, `%PROCESSOR_ARCHITECTURE%`, or `%ProgramFiles%`, will be incorrect due to WOW64 redirection so if you had for example `%ProgramFiles%\7-Zip` in your `PATH` that will be expanded to `C:\Program Files (x86)\7-Zip` instead of `C:\Program Files\7-Zip`.
> 
> Finally, given that `ComSpec`, `PSModulePath`, and `windir` registry keys are also by default `REG_EXPAND_SZ`, if this function is used to change any of them it will mess them up as well.
> 
> **Actual behavior:**
> 
> 1. Registry key type is changed
> 2. Variable contents are expanded
> 
> **Expected behavior**
> 
> 1. Registry key type is preserved
> 2. Variable contents are not expanded

### Suggested solution
_quoted from https://github.com/dotnet/corefx/issues/36449#issuecomment-567582433:_

> If you're adding / removing entries to the PATH, the only way that currently works is to use the `Microsoft.Win32.Registry` APIs. This API remaining in production is a serious hazard. If you try to pull the unexpanded PATH values via the registry APIs so you can do proper modification without ruining the original values, you cannot set values to the PATH variables with this API without breaking a _significant_ portion of the OS.
> 
> I would suggest a threefold solution:
> 
> 1. Add an overload to `GetEnvironmentVariable()` that allows the caller to pass a flag to indicate whether they _want_ variables to be expanded or to be left unaltered.
> 2. Add an overload to `SetEnvironmentVariable()` that allows the caller to pass a flag indicating if the value contains variables and thus should be set as `ExpandString` in the Registry APIs instead of just `String`.
> 3. When calling `SetEnvironmentVariable()` without the above explicit flag, the API should first query the currently-set type of the value in the registry, and _never change the stored type_ of the value. `ExpandString` values should remain `ExpandString`, and `String` values should remain `String`. If someone wants to explicitly change that, they can use the new overload from point 2.

Also of note is that in many cases, attempting to set the PATH value(s) from the registry API fails with an access denied error, even from an administrative context. The result? There's often _no way at all_ to set PATH values in .NET (any version of either Framework or Core).

**Comment by jkotas** [comment]
I have transferred the original corefx issues to this repo. Resolving it as duplicate - the original corefx has more context.
