### ISSUE TITLE
enumerable.AsParallel().LongCount() can only count int.MaxValue elements

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/runtime#14435]
... as well as `enumerable.AsParallel().LongCount(x => true)` (I thought this override had a successful run, but it isn't now)

The overflow is encountered at [PartitionedDataSource.cs, line 967](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/src/System/Linq/Parallel/Partitioning/PartitionedDataSource.cs#L697).  The problem is that these partitioned data sources all presume to only operate over `int.MaxValue` elements, and the rest of the file (and related infrastructure) depend on that.  Some sort of re-architecting (rather than simply switching the key from `int` to `long`) is probably required.

Repro test:

```
[Fact]
// Extremely long-running
public static void LongCount_LargeCount()
{
    Assert.Equal(int.MaxValue + 1L, new OverlyLargeEnumerable().AsParallel().LongCount());
}

private class OverlyLargeEnumerable : IEnumerable<long>
{
    public IEnumerator<long> GetEnumerator()
    {
        return new OverlyLargeEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    private class OverlyLargeEnumerator : IEnumerator<long>
    {
        private long _current = -1;

        public long Current
        {
            get
            {
                return _current;
            }
        }

        object IEnumerator.Current
        {
            get
            {
                return Current;
            }
        }

        public void Dispose()
        {
            _current = int.MaxValue;
        }

        public bool MoveNext()
        {
            // Adds one _after_ compare, so final value is int.MaxValue + 1
            return _current++ < int.MaxValue;
        }

        public void Reset()
        {
            _current = -1;
        }
    }
}
```

Vanilla LINQ is fine.
This behavior is present on the current consumer release.

("You had one job!  ONE!  JOB!")
(side note - I'm a little surprised by how much slower this runs in parallel compared to doing it sequentially - by about 6 times, or ~120 seconds vs 20 seconds)

**Comment by stephentoub** [comment]
https://github.com/dotnet/dotnet-api-docs/pull/3940
