### ISSUE TITLE
Vector<T> should allow variable length based size of available registers.

### ISSUE THREAD

**Issue by mburbea** [dotnet/runtime#14531]
Currently, it seems that `Vector<T>` will always be the size of the largest available register, and has no support for using a smaller register.
E.g. if you have AVX2, you currently can only build `Vector<T>` of 256bit. For some algorithms it can be very useful to be able to use either a vector of size 16 or a vector of size 32.

**Comment by tannergooding** [comment]
Going to close this for now. This hasn't gained much traction and likely needs more thought/scenarios before it could be moved forward.
