### ISSUE TITLE
Update cross build-rootfs for modern world

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#1466]
As part of building docker image for arm64 cross compiling I spent a lot of time looking at build--rootfs.sh.  The following seem like changes which should be done...

+ Add latest Ubuntu version: Artful and Bionic
+ Remove unsupported Ubuntu versions: Vivid and Wily
+ Add latest lldbdev versions: 4.0, 5.0, 6.0
+ Update lldb default to 3.9 to be consistent with non-cross build
+ Drop old lldb versions 3.6 and 3.8

Similar changes should be made in corefx and coreclr

@janvorli FYI

**Comment by dagood** [comment]
Moved from core-setup during triage to make sure the info isn't lost if it's still relevant.

**Comment by wfurt** [comment]
This seems like core-setup clone of https://github.com/dotnet/corefx/issues/28140.
That one was fixed and scripts moved to Arcade. After repo consolidation this issue should not be relevant as we use Arcade now for all old repos. 
If we need further updates we should open new issue in Arcade.
