### ISSUE TITLE
Consider caching of results of CreateObjectArrayDelegateRefEmit

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#14662]
Tracking TODO in 
     src/Common/src/System/Dynamic/Utils/DelegateHelpers.cs 

The method manufactures thunk functions that could often have same signature, but bound to different handlers. It is not cleare whether such caching is possible/beneficial, but it is worth a thought.

**Comment by cston** [comment]
It looks like this issue refers to `DelegateHelpers.CreateObjectArrayDelegateRefEmit()`.

**Comment by cston** [comment]
Closing. We should re-open this issue if we see a performance issue.
