### ISSUE TITLE
XmlSerializer doesn't encode/escape Unicode characters when serializing

### ISSUE THREAD

**Issue by miloszkukla** [dotnet/runtime#1469]
XmlSerializer doesn't encode/escape Unicode characters (e.g. German quotation marks as illustrated below) during serialization when TextWriter with non-Unicode encoding e.g. ISO-8859-1 is used. Tested on .NET Framework 4.5.2, 4.7.2 and .NET Core 2.2.

Since mentioned characters are part of Unicode and are not known to ISO-8859-1 the expected behavior would be the same as when using XmlWriter so they should be encoded with their character entity references. I understand this would be a breaking change so probably this issue will get closed but perhaps someone will find this helpful in future.

Execution of the following code results in incorrect XML and consequently deserialization exception:

```
public class Foo
{
    [XmlAttribute("bar")]
    public string Bar { get; set; } = new string(new[]
    {
        '\u201A', // ‚ replaced with 44 ,
        '\u2018', // ‘ replaced with 39 '
        '\u201E', // „ replaced with 34 "
        '\u201C'  // “ replaced with 34 "
    });
}

var iso88591 = Encoding.GetEncoding("ISO-8859-1");
var ms = new MemoryStream();
var sw = new StreamWriter(ms, iso88591);
var sr = new StreamReader(ms, iso88591);
var serializer = new XmlSerializer(typeof(Foo));

serializer.Serialize(sw, new Foo());
var charPreview = iso88591.GetString(ms.GetBuffer()).ToCharArray();
ms.Position = 0;
serializer.Deserialize(sr); //fails due XML containing extra quotation marks
```

The workaround would be to use Serialize method overload accepting XmlWriter e.g.:
```
var xmlWriter = XmlWriter.Create(ms, new XmlWriterSettings() { Encoding = iso88591 });
serializer.Serialize(xmlWriter, new Foo());
```

**Comment by GrabYourPitchforks** [comment]
This behavior is called out in [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlwriter.create). See specifically the two sections which begin with the text:

 * If you use a Create overload that doesn't accept an XmlWriterSettings object, the following default writer settings are used
 * XmlWriter always writes a Byte Order Mark (BOM)

**Comment by miloszkukla** [comment]
I think that's not exactly the reason by thanks for pointing this out - I've just looked into https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs#L302
and Deserialize method creates XmlTextWriter with StreamWriter passed by the user so I would guess the reason for the behavior is that XmlTextWriter simply uses StreamWriter to write without encoding unknown characters like XmlWriter created by XmlWriter.Create method would do.
