### ISSUE TITLE
Unable to dotnet restore from Manjaro linux, fresh install

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#1471]
_From @LimpingNinja on Monday, January 6, 2020 8:58:18 PM_

Installed dotnet-sdk via Snap and the first thing I did was attempt to restore: 

/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [path.to.sln]
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [path.to.sln]
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [path.to.sln]

I am migrating to Manjaro from OSX and didn't have this issue, possibly related to openssl or some manual certificate management I have to do that wasn't in the install directions?

_Copied from original issue: dotnet/sdk#4133_

**Comment by wli3** [comment]
_From @LimpingNinja on Monday, January 6, 2020 9:09:41 PM_

This appears to be an issue with the Snap install method of installation. I rebooted and still no success, but before going down the rabbit hole I installed via tar.gz direct installation and dotnet restore ran perfectly fine.

**Comment by wli3** [comment]
_From @LimpingNinja on Monday, January 6, 2020 9:11:06 PM_

Additionally: The snap install works after manual install+run.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
