### ISSUE TITLE
Verify algorithmic complexity of ImmutableList<T>.Builder.ToImmutable

### ISSUE THREAD

**Issue by sharwell** [dotnet/runtime#14713]
Currently the documentation for `ImmutableList<T>.Builder.ToImmutable()` includes the following remark:

> This method is an O(n) operation, and approaches O(1) time as the number of actual mutations to the set since the last call to this method approaches 0.

The problem with this statement is the complexity of this operation is only O(1) when the number of mutations is _exactly_ equal to 0. As the number of mutations _approaches_ 0, the complexity is actually approaching O(log n).

**Comment by eiriktsarpalis** [comment]
> As the number of mutations approaches 0, the complexity is actually approaching O(log n).

Assuming this is correct, it would probably make sense to clarify in the docs.
