### ISSUE TITLE
Improve ConcurrentBag<T> GetEnumerator performance

### ISSUE THREAD

**Issue by MarkusSintonen** [dotnet/runtime#14835]
Currently `ConcurrentBag<T>` `GetEnumerator()` causes list copying everytime enumerator is accessed eg. through `foreach`. This causes strain on the GC and list copying is also heavy operation on large bags.

There should be alternative methods to enumarate the bag contents or implement `GetEnumerator()` so that it does not cause list copying. I have presented here 3 possbile solutions to this problem.

**Solution 1)**
Add `ForEach` method to `ConcurrentBag<T>`:

``` CSharp
public void ForEach(Func<T, bool> action)
{
    // Short path if the bag is empty
    if (_headList == null)
        return;

    bool lockTaken = false;
    try
    {
        FreezeBag(ref lockTaken);

        ThreadLocalList currentList = _headList;
        while (currentList != null) // Go through thread lists
        {
            Node currentNode = currentList._head;
            while (currentNode != null) // Go through thead specific linked list
            {
                if (!action(currentNode._value))
                    return; // User wanted to break the operation
                currentNode = currentNode._next;
            }
            currentList = currentList._nextList;
        }
    }
    finally
    {
        UnfreezeBag(lockTaken);
    }
}
```

`ForEach` function takes user specified `Func<T,bool>` delegate. This delegate takes the bag item as an argument and returns true/false depending on whether the user wants to continue or stop the enumeration operation.

Here `ForEach` operation would lock the bag so that other threads would need to wait for the operation to finish. Therefore results of this operation would represent the bag as a moment-in-time snapshot.

**Solution 2)** 
Add `GetEnumerableSlim` function:

``` CSharp
public IEnumerable<T> GetEnumerableSlim()
{
    ThreadLocalList currentList = _headList;
    while (currentList != null)
    {
        Node currentNode = currentList._head;
        while (currentNode != null)
        {
            yield return currentNode._value;
            currentNode = currentNode._next;
        }
        currentList = currentList._nextList;
    }
}
```

This would require an additional change to the internal class `Node`:

``` CSharp
internal class Node
{
    public Node(T value)
    {
        _value = value;
    }
    public readonly T _value;
    public volatile Node _next; // This needs to be marked as volatile
    public Node _prev;
}
```

`GetEnumerableSlim` would enumerate the bag contents concurrently without locking the bag. The proposed implementation is thread safe from memory model point of view. The fields `ConcurrentBag<T>._headList`, `ThreadLocalList._head` and `Node._next` are all volatile variables. Therefore all the threads always have the newest value available. In addition the `Node._value` reference/value is immutable. `GetEnumerableSlim` is safe to use concurrently.

Of course here the enumerator would miss some of the concurrent additions/removals from the bag. Also enumerator could contain modification after the `GetEnumerator` was called. Similiar behaviour is also used in `ConcurrentDictionary<K,T>`, `GetEnumerator` which may also miss some of the concurrent changes or contain new changes after the `GetEnumerator` was called. Therefore the `GetEnumerableSlim` is consistent with other concurrent collections and their enumerator implementations. (It would be intresting to know why `ConcurrentBag<T>` `GetEnumerator` was originally implementeted so that it copies the bag contents to a list where as the other concurrent collections enumerate the contents concurrently eg. `ConcurrentQueue<T>`.)

**Solution 3)**
Replace `GetEnumerator` with `GetEnumeratorSlim` implementation. This solution would totally eliminate the risk of performance degradation due to list allocations. But this might not be possible if the existing code relies on the fact that `GetEnumerator` returns moment-in-time representation of the bag.

**Comment by eiriktsarpalis** [comment]
Triage: this looks like a nice-to-have performance improvement, which however is only meant to address a corner case of ConcurrentBag usage. Given that the issue hasn't seen much activity, I'll leave open and assign to the future milestone.
