### ISSUE TITLE
System.Net.Mail does not encode headers on code point boundaries

### ISSUE THREAD

**Issue by atheken** [dotnet/runtime#1485]
In order for unicode headers to be transmitted over SMTP, they must be encoded using the encoding outlined in RFC-2047. This is sometimes known as "Encoded-Word" or "Q-Encoding." 

SMTP headers should also be limited in line length, and RFC-2047 sets a maximum line length of 76 characters. Therefore, when encoding unicode headers, it is typical to need to fold headers onto multiple lines.

A common example might be something like the following:

```plain
Subject: =?ISO-8859-1?B?SWYgeW91IGNhbiByZWFkIHRoaXMgeW8=?=
 =?ISO-8859-2?B?dSB1bmRlcnN0YW5kIHRoZSBleGFtcGxlLg==?=
```

It is really important to note that the base64 encoding in the above example uses two different character sets, this is not a particularly common example, but this is definitely legal. The binary data for an individual code point should never be split between two "Encoded Words."

A more practical example is Unicode Emojis. Emojis frequently span multiple (and variable) bytes. In the case of UTF-8 individual code-points could be 1-4 bytes. Splitting emoji bytes on to multiple lines can result in the "unicode block (�)" appearing in some mail clients because the multi-byte characters are decoded separately. In other cases, spurious spaces are included.

The current `Base64Stream` (and `QuotedPrintableStream`, it would seem) do not account for the byte boundaries of the encoded code points:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Mail/src/System/Net/Base64Stream.cs#L230-L246

At this level, the streams are (mostly) unaware of any text encoding semantics, and just write as many bytes as possible on each line.

Instead, these encoding streams need to account for code-point byte boundaries, and fold the line preemptively, if only part of a code point can be included in the line before the next line fold would occur.

I'm a little bit concerned that the stream is the wrong level of abstraction for this type of handling. Perhaps including some sort of "look-ahead" on the `WriteState` is a better option for determining the next smallest block of bytes that can be written is.

I have a fork of Corefx and will be fixing it on my own. Please let me know if this is something the team is interested in fixing, and I can provide a patch.

**Comment by logiclrd** [comment]
I just ran into this same bug in the course of my work. An e-mail with subject line:

> 🚨 Service Down on IQ-RGINTW025 🚨

...ends up with the line split in the middle of the second 🚨 character. Some mail implementations happen to decode this correctly, some definitely don't.

Postel's rubustness principle states:

> ...: be conservative in what you do, be liberal in what you accept from others

Based on this principle, I think it is entirely reasonable that there exist clients that can reassemble characters split across separately-encoded byte sequences -- but .NET's implementation should not be making them do so in the first place.
