### ISSUE TITLE
Add ImmutableArray.Builder.AddRange, MoveToArray methods

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#14860]
The builder currently has APIs:

``` C#
public void AddRange(T[] items, int length);           
public ImmutableArray<T> MoveToImmutable();
```

but is missing the following:

``` C#
public void AddRange(T[] items, int start, int length);           
public T[] MoveToArray();
```

**Comment by eiriktsarpalis** [comment]
Triage: given that the issue has not seen a lot of activity recently, I'm going to close this. We can maybe reopen in the future provided we have a more concrete api proposal.
