### ISSUE TITLE
System.Net.Mime.MediaTypeNames missing types

### ISSUE THREAD

**Issue by snebjorn** [dotnet/runtime#1489]
https://github.com/dotnet/corefx/blob/3f0bd5d8c3d019ad8b1561395030a58bc38ddfe9/src/System.Net.Mail/ref/System.Net.Mime.cs#L44

I tried using `System.Net.Mime.MediaTypeNames` in my asp net core api to remove "magic strings"

```c#
[Consumes(System.Net.Mime.MediaTypeNames.Application...)]
public IActionResult Post(...)
{ ... }
```

But it's missing quite a few MIME types.

These come to mind:

> text/css
> text/javascript
> 
> application/json
> application/json-patch+json
> application/xml
> application/javascript
> application/x-www-form-urlencoded
> 
> multipart/form-data
> multipart/byteranges
> 
> image/png
> image/bmp
> image/webp
> image/svg+xml
> 
> audio/midi
> audio/mpeg
> audio/webm
> audio/ogg
> audio/wav
> 
> video/webm
> video/ogg

**Comment by alexandra142** [comment]
Hello could you please add "application/merge-patch+json" ?

**Comment by rjperes** [comment]
Hi, this seems to be a very simple change, doesn't break anything and adds useful MIME types. Why can't we get this to move forward?

**Comment by karelz** [comment]
@rjperes see the above discussion: https://github.com/dotnet/runtime/issues/1489#issuecomment-541385535

**Comment by Bilal-io** [comment]
@karelz I am looking at the API review process you linked above, which step did this issue reach?
Step one is someone creating an issue (this issue), step two is for the team to assign an owner, why hasn't that happened yet?

Here is my proposal for the common mime types that I believe should exist under the System.Net.Mime.MediaTypeNames namespace. I have checked the existing ones in the list below. I also went with the assumption that mime types of executable files will not be added, is that fair? Maybe not.

# Proposal
### System.Net.Mime.MediaTypeNames.Text
- [x] Plan = "text/plain"
- [x] Html = "text/html"
- [x] Xml = "text/xml"
- [x] RichText = "text/richtext"
- [ ] Csv = "text/csv"

### System.Net.Mime.MediaTypeNames.Application
- [x] Soap = "application/soap+xml"
- [x] Octet = "application/octet-stream"
- [x] Rtf = "application/rtf"
- [x] Pdf = "application/pdf"
- [x] Zip = "application/zip"
// perhaps add all different kinds of non-executable MS mimetypes?
- [ ] Docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
- [ ] Xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
- [ ] Pdf = "application/pdf"
- [ ] Json = "application/json"
- [ ] JsonPatch = "application/json-patch+json"
- [ ] JsonLd = "application/ld+json"
- [ ] Xml = "application/xml"
- [ ] FormUrlencoded = "application/x-www-form-urlencoded"

### System.Net.Mime.MediaTypeNames.Image
- [x] Gif = "image/gif"
- [x] Tiff = "image/tiff"
- [x] Jpeg = "image/jpeg"
- [ ] Png = "image/png"
- [ ] Svg = "image/svg+xml"
- [ ] Webp = "image/webp"
- [ ] Bmp = "image/bmp"

## Additional Categories

### System.Net.Mime.MediaTypeNames.Multipart
- [ ] FormData = "multipart/form-data"
- [ ] Byteranges = "multipart/byteranges" // Use case: Send part of a document

### System.Net.Mime.MediaTypeNames.Font
- [ ] Collection = "font/collection"
- [ ] Otf = "font/otf"
- [ ] Sfnt = "font/sfnt"
- [ ] Ttf = "font/ttf"
- [ ] Woff = "font/woff"
- [ ] Woff2 = "font/woff2"

### System.Net.Mime.MediaTypeNames.Video
- [ ] Webm = "video/webm"
- [ ] Ogg = "video/ogg"
- [ ] Mp4 = "video/mp4"
- [ ] Mpeg = "video/mpeg"
- [ ] Mp2t = "video/mp2t"

### System.Net.Mime.MediaTypeNames.Audio
- [ ] Midi = "audio/midi"
- [ ] Mp3 = "audio/mpeg"
- [ ] Webm = "audio/webm"
- [ ] Ogg = "audio/ogg"
- [ ] Wav = "audio/wav"

Sourced from [IANA - Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml) with the help of [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) to pick some common mime types.

If I have missed anything that you believe is useful, add it in a comment.

**Comment by karelz** [comment]
@Bilal-io thanks for your proposal with names!
Were you able to get some information about the usage of each of them? (as mentioned above - https://github.com/dotnet/runtime/issues/1489#issuecomment-541385535 https://github.com/dotnet/runtime/issues/1489#issuecomment-537625716)
I have to admit some of these are not known to me. For some I would expect they are on decline these days (e.g. Midi?) ... some usage data would make decisions here easier.

Regarding your question:

> step two is for the team to assign an owner, why hasn't that happened yet?

You are right that we deviate from the process a bit -- unless the API is super-active, we consider the area owners to be the owners (though not assigned explicitly).
In case of Networking area, it is the members of our Networking team (incl. myself). Once API is ready, we discuss proposals in our team meeting to get more thoughts before marking it ready for API review.
Also note that in principal we try to not assign issues unless someone works on them actively (otherwise we would be back in place where people had hundred and more issues assigned to them -- which made assignments useless).
Hopefully that makes sense ...

**Comment by snebjorn** [comment]
Unable to find any usage data for MIME types. However Mozilla have a list of [Common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

**Comment by markwhitaker** [comment]
If it's useful as a workaround, I've implemented lots of missing MIME types in a very lightweight NuGet package ([NuGet](https://www.nuget.org/packages/Mainwave.MimeTypes/), [source](https://github.com/markwhitaker/MimeTypes.NET)). (An older version is also available as an [MIT-licensed gist](https://gist.github.com/markwhitaker/b29c0142360714688a7cf863ab33e5c9)).

**Comment by Marusyk** [comment]
I need text/csv. Any plans?

**Comment by AraHaan** [comment]
It's also missing the csv media type name as well.

**Comment by bgilner-rgg** [comment]
text/json
text/x-json
text/javascript

**Comment by AraHaan** [comment]
application/zlib-stream

**Comment by ldeluigi** [comment]
Please add text/csv too. This issue is from 2017

**Comment by mmarinchenko** [comment]
https://github.com/dotnet/runtime/issues/1489#issuecomment-537625716
> Triage: We are open to add a few of the MIME type enums. Next step: Create proposal with most used ones (with some links to usage ideally) and with names how they should be exposed.

@karelz I can agree that the audio, video, and office mime types have special uses and are not found in every application. But can we start with the file types used in the [ASP.NET Core project templates](https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates/content), with the addition of related and some other well-known formats? I found most of the font and image formats there, in the `wwwroot` directories.

Additional sources are: [IANA Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml) and [ASP.NET Core FileExtensionContentTypeProvider](https://github.com/dotnet/dotnet/blob/main/src/aspnetcore/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs).

## The Proposal

### Application
- [ ] FormUrlEncoded = "application/x-www-form-urlencoded"
- [x] Json = "application/json"
- [ ] JsonPatch = "application/json-patch+json"
- [ ] JsonSeq = "application/json-seq"
- [ ] Manifest = "application/manifest+json"
- [x] Octet = "application/octet-stream"
- [x] Pdf = "application/pdf"
- [ ] ProblemJson = "application/problem+json"
- [ ] ProblemXml = "application/problem+xml"
- [x] Rtf = "application/rtf"
- [x] Soap = "application/soap+xml"
- [ ] Wasm = "application/wasm"
- [x] Xml = "application/xml"
- [ ] XmlDtd = "application/xml-dtd"
- [ ] XmlPatch = "application/xml-patch+xml"
- [x] Zip = "application/zip"

### Font
- [ ] Collection = "font/collection"
- [ ] Otf" = "font/otf"
- [ ] Sfnt = "font/sfnt"
- [ ] Ttf" = "font/ttf"
- [ ] Woff = "font/woff"
- [ ] Woff2 = "font/woff2"

### Image
- [ ] Avif = "image/avif"
- [ ] Bmp = "image/bmp"
- [ ] Icon = "image/x-icon"
- [x] Gif = "image/gif"
- [x] Jpeg = "image/jpeg"
- [ ] Png = "image/png"
- [ ] Svg = "image/svg+xml"
- [x] Tiff = "image/tiff"
- [ ] Webp = "image/webp"

### Multipart
- [ ] ByteRanges = "multipart/byteranges"
- [ ] FormData = "multipart/form-data"

### Text
- [ ] Css = "text/css"
- [ ] Csv = "text/csv"
- [x] Html = "text/html"
- [ ] JavaScript = "text/javascript"
- [ ] Markdown = "text/markdown"
- [x] Plain = "text/plain"
- [x] RichText = "text/richtext"
- [ ] Rtf = "text/rtf"
- [x] Xml = "text/xml"

**Comment by wfurt** [comment]
The proposed list above seems quite reasonable. I can try to take it through API review @karelz. While I personally see the benefit small,  the effort is also somewhat small and we get help from the community.

**Comment by karelz** [comment]
@wfurt yeah, if you can bring it to Networking meeting first, let's check that we have "reasonability" agreement. Then we can push it through API review.

**Comment by karelz** [comment]
Triage: The team discussed it on Thu 3/16. There was general agreement with the latest proposal - thank you @mmarinchenko!
@wfurt will update the proposal into form ready for API review and mark it as such. We should be able to get it into 8.0 without any troubles.

**Comment by AraHaan** [comment]
> Triage: The team discussed it on Thu 3/16. There was general agreement with the latest proposal - thank you @mmarinchenko! @wfurt will update the proposal into form ready for API review and mark it as such. We should be able to get it into 8.0 without any troubles.

Will this include adding ``zlib-stream`` to the enum as ``ZlibStream`` (to let the people know to use the ZlibStream class in .NET to decompress the stream data?)

**Comment by wfurt** [comment]
I was not planning to @AraHaan. Do you have example of public sites using it or is that something you applications do internally? https://www.rfc-editor.org/rfc/rfc6713 shows `application/zlib` and `application/gzip` so I'm note sure from where the `-stream` is coming. The mime type should be specific to the content not the implementation producing it, right?

**Comment by AraHaan** [comment]
I am not sure, it might have been a random case where I noticed an ``zlib-stream`` version of it.
