### ISSUE TITLE
Libraries native build fails on VS 16.5.0 Preview 1.0 with CMake 3.16.0-rc4

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#149]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5
): error MSB8065: Custom build for item "P:\runtime\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\CMakeFiles\84e
020d515ecc51b04c20b308fc709be\INSTALL_force.rule" succeeded, but specified output "p:\runtime\artifacts\obj\native\netc
oreapp-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work in
correctly. [P:\runtime\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\install.vcxproj] [P:\runtime\src\libraries\
Native\build-native.proj]
 
Same issue as: https://github.com/dotnet/corefx/issues/41077 which was fixed by
https://gitlab.kitware.com/cmake/cmake/issues/19737

We should investigate what changed and why it fails only in 3.16.0-* as with CMake 3.15.5 it doesn't fail.

cc: @jaredpar

**Comment by safern** [comment]
I tried this out with latest VS Preview (v16.5.0-pre.2.0) and latest CMake 3.16.1 and it didn't repro. Please re-open if you hit this with a CMake version greater or equal than 3.15.5.

**Comment by deokershesh** [comment]
I am facing same issue, I am using CMake version 3.15.6, kindly refer issue https://github.com/dotnet/runtime/issues/1014 , it may require to reopen this issue as well.

**Comment by safern** [comment]
@deokershesh what version of VS do you have?
