### ISSUE TITLE
Stop shipping and building WebSocketsProtocol assembly

### ISSUE THREAD

**Issue by buybackoff** [dotnet/runtime#1493]
ManagedWebSocket in [System.Net.WebSockets.WebSocketProtocol](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.WebSocketProtocol/src/System/Net/WebSockets/ManagedWebSocket.netstandard.cs) is different from the implementation in [System.Net.WebSockets](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.netcoreapp.cs) for .NET 2.1. The former NuGet package is updated on May 5 as `4.5.0-rc1 (current)`, on the same day when [Microsoft.NETCore.App](https://www.nuget.org/packages/microsoft.netcore.app) package that includes the newest `System.Net.WebSockets` for .NET Core 2.1 was released as `2.1.0-rc1`. 

I had to dig into the source to find out that [Microsoft.AspNetCore.WebSockets](https://www.nuget.org/packages/Microsoft.AspNetCore.WebSockets), also released on that day as `2.1.0-rc1-final`, depends on `System.Net.WebSockets.WebSocketProtocol` and not on `System.Net.WebSockets` on [this line](https://github.com/aspnet/WebSockets/blob/ee4fec48e72daeb22f668789cfd08e94cf4948d3/src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs#L122). Unfortunately, that doesn't allow to enjoy the performance benefits from https://github.com/dotnet/corefx/issues/27445 when running ASPNETCore 2.1 apps.

Is this for a reason? How to use the latest low-allocations implementation currently in ASPNETCore 2.1 apps?

**Comment by stephentoub** [comment]
@karelz, this got triaged to future.  Wouldn't it make sense to fix it for .NET 5 so that we don't need to produce new packages for it?  Or would we still need to anyway for some reason? @ericstj?

**Comment by zlatanov** [comment]
What is the current status of this item? I've started working on implementing websocket compression (issue [here](https://github.com/dotnet/runtime/issues/31088)) and I've noticed that the actual websocket implementation exists as a shared source and cross compiled in both in `System.Net.WebSockets` and `System.Net.WebSockets.WebSocketProtocol`.

How should I proceed with the implementation:

1. Continue to support `WebSocketProtocol` and add the implementation here - https://github.com/dotnet/runtime/tree/master/src/libraries/Common/src/System/Net/WebSockets.
2. Ignore `WebSocketProtocol` and add the implementation inside `System.Net.WebSockets` project only.

/cc @stephentoub @karelz @davidfowl

**Comment by stephentoub** [comment]
> What is the current status of this item?

I believe we've all agreed it should be done but no one's done it.  @karelz, can this be prioritized?

**Comment by karelz** [comment]
@CarnaViire will take care of this one. Thanks @CarnaViire! (expected start next week)

**Comment by stephentoub** [comment]
Cool, thanks.
