### ISSUE TITLE
HTTP2 code coverage: add tests that cause us to send a CONTINUATION frame

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#1496]
See code here, line 1096: file://clrmain/public/writable/users/geoffrek/http2codecoverage/System.Net.Http_Http2Connection.htm#file0_line1035

To force a CONTINUATION frame, we need to send a header block > max frame size, i.e. 16K.

**Comment by karelz** [comment]
We have found bug related to this, we should add the test.
