### ISSUE TITLE
NameValueHeaderValue throws FormatException if header value contains a colon

### ISSUE THREAD

**Issue by lmolkova** [dotnet/runtime#1504]
According to RFC 7231 colon (':') seems to be valid character in header *value*.
Examples of known headers with the colon are `Date: Tue, 15 Nov 1994 08:12:31 GMT` or `Host: server.example.com:80`

However when I try to create a new `NameValueHeaderValue` with the value containing a colon 
```csharp
var header = new NameValueHeaderValue("host", "server.example.com:80");
```

I get `FormatException`. 

```
Unhandled Exception: System.FormatException: The format of value 'server.example.com:80' is invalid.
   at System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(String value)
   at System.Net.Http.Headers.NameValueHeaderValue.CheckNameValueFormat(String name, String value)
   at System.Net.Http.Headers.NameValueHeaderValue..ctor(String name, String value)
```

Expected: `host=server.example.com:80`

**Comment by MarcoRossignoli** [comment]
I did a PR waiting review https://github.com/dotnet/runtime/pull/794
