### ISSUE TITLE
HTTP2: Optimize handling of HPACK static table decoding

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#1505]
Currently, when we decode a header from the static table, we convert it to the ASCII header name/value and then parse this again in order to determine if it's a known header. 

We should optimize this by avoiding the conversion to ASCII and simply map it directly to a known header.

**Comment by aik-jahoda** [comment]
I'm working on #1588 and faced the same issue as part of the dynamic encoding. I changed the headers from bytes[] to strings and it eliminates all the ASCII conversion. With dynamic encoding and decoding, it basically removes the need for extra allocation. 

Currently, I'm finishing the feature and will provide benchmarks. For that reason, I would postpone this ticket.

**Comment by geoffkizer** [comment]
HPackEncoder support for this is getting added in https://github.com/dotnet/runtime/pull/40689.

Remaining work for us is really just to have a big table that maps static header ID => KnownHeader. And possibly some small special handling for known values like ":method: GET".
