### ISSUE TITLE
Propose Adding a GetOrAdd(TKey key, Func<TKey, TValue> valueFactory) to Dictionary<TKey, TValue>

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/runtime#15059]
On `ConcurrentDictionary<TKey, TValue>` there is the very useful function `TValue GetOrAdd(TKey key, Func<TKey, TValie> valueFactory)`. The pattern that the method represents is one that issued commonly on the "normal" `Dictionary<TKey, TValue>` as well. I propose adding such a method for this common use case. Besides simplifying it will also make switching between the two dictionaries simpler.

**Comment by eiriktsarpalis** [comment]
Triage: if the main motivation for this addition is to minimize number of lookups, then presumably adding ref-return methods woulds be the preferable approach? c.f. https://github.com/dotnet/runtime/issues/22121. Given the lack of recent activity in the issue, I'd be inclined to close this for now.

**Comment by jnm2** [comment]
@eiriktsarpalis Looking at what you linked, ref-returning methods methods aren't happening except maybe in the future on a CollectionsMarshal class: https://github.com/dotnet/runtime/issues/27062

Because of the inherent lack of safety in ref-returning methods due to the backing store changing, I think GetOrAdd is still interesting.

**Comment by eiriktsarpalis** [comment]
@jnm2 just so I understand your requirements, would having the extension method you proposed above solve your issue? IOW is this about double lookups or avoiding creating values when not needed or both?

**Comment by jnm2** [comment]
@eiriktsarpalis It's about double lookups but also with the expectation that creating a value may be expensive and should be avoidable. Two overloads would be nice, one with `TValue value` and one with `Func<TKey, TValue> valueFactory` or maybe even `Func<TState, TValue> valueFactory`.

**Comment by danmosemsft** [comment]
> maybe even Func<TState, TValue> valueFactory.

@jnm2  can you clarify what the "state" would be here?

With respect to ref-returns, this is what [DictionarySlim ](https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/DictionarySlim.cs#L217) does (the k-Neucleotide benchmark it was used for needs to increment values held in a map). As you point out, that makes it easy to corrupt the backing store. I wonder whether the "update the value" scenario is interesting. If it is, a possible middle ground might be for the `valueFactory` to accept the current value. Perhaps that's what you mean by `TState` ? 

cc @GrabYourPitchforks  since we were talking about it.

**Comment by jnm2** [comment]
@danmosemsft I was thinking of TState in the same sense as ThreadPool.QueueUserWorkItem. It would be a way to avoid allocating a delegate per call when the key alone does not provide enough information to obtain the value. However, I don't often need to avoid this allocation, so this could wait until someone does have the need.

```cs
public static TValue GetOrAdd<TKey, TValue>(
    this IDictionary<TKey, TValue> dictionary,
    TKey key,
    TState state,
    Func<TState, TValue> valueFactory);
```

**Comment by eiriktsarpalis** [comment]
Carrying over from #36942, we should consider evaluating an [`AddOrUpdate`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.addorupdate?view=netcore-3.1#System_Collections_Concurrent_ConcurrentDictionary_2_AddOrUpdate__0_System_Func__0__1__System_Func__0__1__1__) method as well cc @layomia

**Comment by GrabYourPitchforks** [comment]
@eiriktsarpalis This is marked as needs-work, but what is left to address for this? I see the final API as falling under one of two cases:

```cs
public class Dictionary<TKey, TValue>
{
    public TValue GetOrAdd([NotNull] TKey key, Func<TKey, TValue> valueFactory);
}

/* OR */

public class Dictionary<TKey, TValue>
{
    public TValue GetOrAdd<TState>([NotNull] TKey key, TState state, Func<TKey, TState, TValue> valueFactory);
}
```

Passing a _TState_ parameter might be more useful for the majority of scenarios (is the key by itself sufficient to create the value?), but introducing a generic method on a generic type could introduce codegen explosion. @jkotas might be able to speak as to whether that's a deal-breaker.

If it is a deal-breaker, we might be able to simplify by saying "state is always provided as _object?_; no generic state parameter is available."

**Comment by jkotas** [comment]
Yes, I am not trilled about adding more features to Dictionary. Every new feature in Dictionary makes all existing Dictionary uses more expensive given how generics work, especially in AOT scenarios.

I do not see a significant usability advantage of this method over writing a simple straightforward code: 
```
if (!dictionary.TryGetValue(...))
    dictionary.Add(...);
```
This straightforward code is also going to have better performance in number of cases. It avoids overhead of creating and passing around the lamda or state. I understand that there are situations where it is not the case (e.g. the hash code computation is very expensive or it is rare for TryGetValue to find the element).

I think https://github.com/dotnet/runtime/issues/27062 is better answer for cases that needs a method like this for performance micro-optimizations.

**Comment by GrabYourPitchforks** [comment]
`CollectionsMarshal` would definitely be more powerful. For example, if we modified the linked proposal to instead read:

```cs
public static class CollectionsMarshal
{
    public static ref TValue GetValueOrAddDefault<TKey, TValue>(Dictionary<TKey, TValue> @this, [NotNull] TKey key, out bool exists);
}
```

Then a "compute the hash code once" code sample would look like:

```cs
ref TValue refToMyValue = CollectionsMarshal.GetValueOrAddDefault(dict, "myKey", out bool exists);
if (!exists)
{
    // the dictionary just performed the equivalent of Add("myKey", default(TValue)) - let's overwrite it now
    refToMyValue = CreateValue();
}
```

As Jan said, this would avoid the generic explosion problem, and it moves the micro-perf API to its own type. The downside is that `CollectionsMarshal` is by its nature somewhat unsafe. Not in the "violates type safety" sense, but more in the "you're juggling knives and could corrupt the dictionary's internal state" sense.

**Comment by svick** [comment]
@jkotas 

> I do not see a significant usability advantage of this method over writing a simple straightforward code:

Keep in mind it's not really about simplifying from two lines of code to one, it's about changing this code:

```c#
Foo GetFoo(int id)
{
    if (!dictionary.TryGetValue(id, out var foo))
    {
        foo = CreateFoo(id);
        dictionary.Add(id, foo);
    }
    return foo;
}
```

to this code:

```c#
Foo GetFoo(int id) => dictionary.GetOrAdd(id, CreateFoo);
```

The latter seems much easier to understand to me.

**Comment by GrabYourPitchforks** [comment]
As mentioned, one of the problems with providing the factory is "is the key by itself sufficient to create the value, or does creation of the value rely on more information than just the key?" If the latter (which I believe is common), you really need to provide a state object.

**Comment by alrz** [comment]
>you really need to provide a state object.

And that easily gets convoluted:
```cs
    if (!dictionary.TryGetValue(id, out var foo))
        dictionary.Add(id, foo = CreateFoo(id));
    Use(foo);
```
```cs
    var foo = dictionary.GetOrAdd(id, static t => t.self.CreateFoo(t.id), (self: this, id))
    Use(foo);
```
I'd personally prefer the first one.

**Comment by FiniteReality** [comment]
> ```cs
>     var foo = dictionary.GetOrAdd(id, static t => t.self.CreateFoo(t.id), (self: this, id))
>     Use(foo);
> ```

Wouldn't passing the state as a second parameter be way better, like ConcurrentDictionary?

```cs
var dict = new ConcurrentDictionary<ulong, Client>();

// ...

var clientSocket = await serverSocket.AcceptAsync();
var client = dict.GetOrAdd(clientId, CreateClient, socket);
HandleClient(client);

// ...

static Client CreateClient(ulong clientId, Socket clientSocket)
{
    return new Client(clientSocket);
}
```

**Comment by GrabYourPitchforks** [comment]
@FiniteReality We need to be careful about adding generic instance methods to generic types. There's a real risk that it could cause significant footprint or memory bloat, even for people who don't use the new feature. Generally we want new features to be pay-for-play and to incur no overhead if you don't use them.

**Comment by FiniteReality** [comment]
@GrabYourPitchforks Understandable, but doesn't that somewhat fly in the face of being able to supply a state object? From what I can tell, the API @alrz suggested would have had the same issues, but would have been even more awkward to interact with.

**Comment by GrabYourPitchforks** [comment]
Yes, it does fly in the face of being able to provide a state object, unless the parameter is typed as _object?_ or some similar non-generic type.

**Comment by FiniteReality** [comment]
> typed as _object?_ or some similar non-generic type.

Oh joy! That's one of the things I hate most about using System.Threading.Timer :sweat_smile:

**Comment by alrz** [comment]
>There's a real risk that it could cause significant footprint or memory bloat, even for people who don't use the new feature. 

I don't understand this claim. Could you elaborate?

**Comment by eiriktsarpalis** [comment]
Agreed that a `CollectionsMarshall` approach is the preferred solution here. It would let users author their own variants of `GetOrAdd` as extension methods, without having to do double lookups.

**Comment by layomia** [comment]
I'm closing this issue in favor of https://github.com/dotnet/runtime/issues/27062 which offers a more capable solution. See that issue for more details.
