### ISSUE TITLE
new X509Certificate2(byte[]) should return the signing cert for PKCS#7 on Unix

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#15073]
The Windows code supports reading a PKCS#7 signed or PKCS#7 signed-and-enveloped structure; but in single certificate mode it doesn't return certs[0], it returns the certificate which signed the structure.

My test files (produced by Windows (certmgr.msc and X509Certificate2Collection::Export)) aren't signed, so Windows emits an exception (`new CryptographicException(ErrorCode.CRYPT_E_SIGNER_NOT_FOUND)`).

Without a sample to see what's going on here, it's hard to make compatible behavior.  So, for now, the Unix implementation will just throw, even if it could have worked.

**Comment by secana** [comment]
_TODO(2910): Figure out how to extract the signing certificate, when it's present._
Getting the signing certificate on Linux from a PE file (taken from [PeNet](https://github.com/secana/PeNet)) is pretty straight forward.

Get the serial number of the signing certificate:
```csharp
private string? GetSigningSerialNumber()
        {
            var asn1 = _contentInfo?.Content;
            if (asn1 is null) return null;
            var x = (Asn1Integer)asn1.Nodes[0].Nodes[4].Nodes[0].Nodes[1].Nodes[1]; // ASN.1 Path to signer serial number: /1/0/4/0/1/1
            return x.Value.ToHexString().Substring(2).ToUpper();
        }
```

Get the signing certificate from the PE file with the `SignerSerialNumber` from above.

```csharp
private X509Certificate2 GetSigningCertificateNonWindows(PeFile peFile)
        {
            var collection = new X509Certificate2Collection();
            collection.Import(peFile.WinCertificate?.BCertificate.ToArray());
            return collection.Cast<X509Certificate2>().FirstOrDefault(cert =>
                string.Equals(cert.SerialNumber, SignerSerialNumber, StringComparison.CurrentCultureIgnoreCase));
        }
```

But I'm not sure on how to get access to the Asn1 of the PE file in the `PkcsFormarReader.cs` @bartonjs linked, so I'm stuck with any implementation attempt before I even get started :(

**Comment by bartonjs** [comment]
@secana There are two different issues.

* Get the signature from a PKCS#7 file
  * We now have a SignedCms implementation, and do quite a lot of work with the data type already.  We mainly need complex tests to make sure that we have the same behavior on Windows and non-Windows; and to move the relevant parsing files (e.g. https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Asn1/SignedDataAsn.xml.cs) into shared source, so we can reuse them.
* Get the signature from an Authenticode file
  * It looks like years ago I bucketed those problems into this one, but as you saw, understanding how to find the signature in various file formats is problematic.  This part wasn't in my set of expectations for .NET 5, since I had mis-remembered it as a separate issue.

**Comment by vcsjones** [comment]
I think I can pick this one up to get `X509Certificate(byte[] contents)` handling PKCS#7/CMS data.

> but in single certificate mode it doesn't return certs[0], it returns the certificate which signed the structure.

@bartonjs Do you know off the top of your head if it is actually validating anything? Maybe it isn't going so far as to validate a certificate chain or anything, but I wonder what happens if the `EncapsulatedContentInfo` has been tampered with. The testing scenarios for this are going to be complex regardless, so I suppose I will find out.

If we actually need to validate something, we can't add a reference to S.S.C.Pkcs due to circular references.

**Comment by NGame1** [comment]
OMG! After about 7 years of opening this issue. Again is it postponed?
No way!

**Comment by NGame1** [comment]
@jeffhandley 
OMG! After about 7 years of opening this issue. Again is it postponed?
No way!

**Comment by et1975** [comment]
@jeffhandley This issue was in the 7.0.0 bucket that's now marked as completed. Is the fix in .NET 7?

**Comment by vcsjones** [comment]
> This issue was in the 7.0.0 bucket that's now marked as completed. Is the fix in .NET 7?

No. This is currently marked "Future" and still open. This did not get complete for 7.0.

**Comment by bryandam** [comment]
I've been hitting this issue (I think), reading up on it, and am wondering if someone can confirm that I'm understanding the implications corrects.
Does this imply that there is currently _no_ cross-platform way in .NET to sign files or verify file signatures? In this case, files signed in Windows can't be verified on Unix/Linux?

**Comment by vcsjones** [comment]
> Does this imply that there is currently no cross-platform way in .NET to sign files or verify file signatures? In this case, files signed in Windows can't be verified on Unix/Linux?

If you mean a file signed with Windows Authenticode, then correct - .NET does not provide an API to verify Authenticode signatures.

But `new X509Certificate2(byte[])` on Windows does not do that either. It returns the signing cert, or the first cert-looking thing it can find in the file, but it does not actually check the signature.

**Comment by bryandam** [comment]
Thanks. Part of what I was struggling to determine was if _all_ code signing in Windows was Authenticode or not as a lot of info just refers to 'digital signature'. In any case, I think it's safe to say that Window's signtool.exe is Authenticode.

Quite right, getting the cert from the file isn't validating the cert, that was a subsequent step I was taking. I just wanted to be sure that my actual goal of validating the file wasn't possible some other way that didn't necessitate actually having the cert object itself.

**Comment by wstaelens** [comment]
what is the status of this? as we think we experience invalid exports of PKCS#7 in .net 7 and seeing this makes me believe things are not fully implemented yet?

**Comment by vcsjones** [comment]
> we think we experience invalid exports of PKCS#7 in .net 7

This issue is specifically about importing a PKCS#7 blob from `X509Certificate{2}` and it has not been implemented.

@wstaelens do you have a code snippet of what is not working for you?

**Comment by wstaelens** [comment]
We tried several things. Maybe missing something, not sure how to get it working.

```
  static void ExportTo(X509Certificate2 cert, string location, string baseFileName, string pwd)
    {
      // Create PFX (PKCS) with private key
      File.WriteAllBytes(Path.Combine(location, baseFileName + ".pfx"), cert.Export(X509ContentType.Pfx, pwd));
      var collection = new X509Certificate2Collection(cert);
      File.WriteAllBytes(Path.Combine(location, baseFileName + ".pk7"), collection.Export(X509ContentType.Pkcs7));
 
      // Create Base 64 encoded CER (public key only)
      File.WriteAllText(Path.Combine(location, baseFileName + ".cer"),
          "-----BEGIN CERTIFICATE-----\r\n"
          + Convert.ToBase64String(cert.Export(X509ContentType.Cert), Base64FormattingOptions.InsertLineBreaks)
          + "\r\n-----END CERTIFICATE-----");
    }
```

If we do ```cert.export(pkcs7```  this does not work, doesn't seem to be supported?

If we put it in a collection and export it the file is about 30% smaller and when importing it it isn't valid (can't debug it is being loaded into an external device).

**Comment by vcsjones** [comment]
@bartonjs I think we can close this as "won't fix". I don't think we are going to add any new functionality to the X509Certificate constructors, and the "right" way to get certs out of a PKCS#7/CMS is to use `SignedCms`.

**Comment by bartonjs** [comment]
Yeah, we probably should be adding features to `[Obsolete]` members (unless we get a compelling compat/square-the-circle scenario).
