### ISSUE TITLE
Apply MaxConnectionsPerServer to HTTP/2?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#1509]
SocketsHttpHandler.MaxConnectionsPerServer currently doesn't apply to HTTP/2.  In general with HTTP/2, the system behaves as if MaxConnectionsPerServer is 1 (since every request tends to reuse the same connection by spec and by design), and thus we implicitly respect MaxConnectionsPerServer (which will always be >= 1)... most of the time.  There are times, however, where the client will create a new connection to the server, such as if SocketsHttpHandler.PooledConnectionLifetime is set such that by the time the next request arrives, the connection is considered not usable for additional requests.  In such cases, we may actually end up with multiple live connections to the server, all of which are handling active request/responses, and thus could be violating MaxConnectionsPerServer if it was set to a low enough value.

Technically this is a bug. In practice, we could decide it's not worth enforcing.  But we should think through it, decide, and either close this or implement the gating.

**Comment by JamesNK** [comment]
Allowing additional connections to be made when SETTINGS_MAX_CONCURRENT_STREAMS limit is hit would also use MaxConnectionsPerServer with HTTP/2.

Context: https://github.com/dotnet/runtime/issues/35088

**Comment by karelz** [comment]
Triage: For 5.0 we decided to go without limit (there's a boolean for enabling multiple connections). We should revisit if we need to look at the Max post 5.0 (moving to Future).

**Comment by alnikola** [comment]
Implementation was mostly complete in #38748, but then moved post 5.0 due to high complexity and high risk of changes.

**Comment by stephentoub** [comment]
This issue was about MaxConnectionsPerServer.  That's the limit for 1.1. Wasn't it already decided we wouldn't use the same limit for HTTP/2?  If so, this can simply be closed.  Or is this now being used to track something other than MaxConnectionsPerServer?

**Comment by geoffkizer** [comment]
> Wasn't it already decided we wouldn't use the same limit for HTTP/2?

Yes. Closing.
