### ISSUE TITLE
Remove FEATURE_TRACING conditional compilation from System.Composition

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/runtime#15096]
The System.Composition source code has some conditional compilation for FEATURE_TRACING.  If the flag is enabled, it uses TraceSource, If not, it looks like logging is disabled entirely.

Since TraceSource is available on .NET Core, I think we can enable the TraceSource code and get rid of the conditional compilation.

**Comment by jkotas** [comment]
This was cleaned up a while ago.
