### ISSUE TITLE
Add static method to create an IEnumerable with one element

### ISSUE THREAD

**Issue by benjamin-hodgson** [dotnet/runtime#15136]
I find that I need the following static method quite often:

``` csharp
public static class MoreEnumerableMethods
{
    // ...
    public static IEnumerable<TResult> Singleton<TResult>(TResult element)
    {
        return Repeat(element, 1);
    }
}
```

This seems like a really good fit for `Enumerable` itself, where it would live alongside `Repeat`, `Empty`, and `Range`. I want to be able to say `Enumerable.Singleton(x)`, not `MoreEnumerableMethods.Singleton(x)`.

Even Eric Lippert has [complained](http://ericlippert.com/2013/03/18/monads-part-eight/) about the lack of this method:

> I wish there was a static method on Enumerable specifically for making a one-element sequence.

I have the code (and tests) ready on [a branch in my fork](https://github.com/dotnet/corefx/compare/master...benjamin-hodgson:singleton#diff-95a14d3b4ae14339b623dd95c7537fd0R1497). I can open a pull request right away, subject to any required API reviews. I'm happy to discuss things like the method name (perhaps `One` or `Singular` would be a better choice?).

**Comment by NetMage** [comment]
Simple things certainly move slowly for .Net...

**Comment by eiriktsarpalis** [comment]
It seems there is consensus for the API as proposed in https://github.com/dotnet/runtime/issues/15136#issuecomment-315083390.  Is there anything blocking us from marking this ready for review?

**Comment by bartonjs** [comment]
API Review:

We're not really clear how this would be used in practice, and why something other than `new[] { item }` would be better in that context.  It also seems like the best name for a single item is `Single`, but that has a bad collision with the existing `Single` semantics.  (Yield doesn't seem like it's discoverable, just easily explained.)

With new data (e.g. sample usage) we might come to different conclusions, but it doesn't seem like there's enough utility and there's a dearth of good names.

**Comment by terrajobst** [comment]
I think a more useuful API proposal might be `ConcatElements`:

```C#
namespace System.Linq
{
    public static class Enumerable
    {
        public static IEnumerable<TResult> ConcatElements<TResult>(this IEnumerable<T> source, T element1);
        public static IEnumerable<TResult> ConcatElements<TResult>(this IEnumerable<T> source, T element1, T element2);
        public static IEnumerable<TResult> ConcatElements<TResult>(this IEnumerable<T> source, T element1, T element2, T element3);
        public static IEnumerable<TResult> ConcatElements<TResult>(this IEnumerable<T> source, params T[] elements);
    }
}
```

At least for me, this the common problem I have when dealing with elements

```
T single1 = ...
T single2 = ...
T[] data = ...
IEnumerable<T> results = data.Concat(new[] {single1, single2})
                             .Where(e => condition(e));
```

feel less "ugly":

```
IEnumerable<T> results = data.ConcatElements(single1, single2)
                             .Where(e => condition(e));
```

I concede that it's a completely aesthetic argument, but I also believe that aesthetics matter.

**Comment by bartonjs** [comment]
> I think a more useuful API proposal might be ConcatElements:

"Concat" one element exists, but it's called Append (or, from the other direction, Prepend). Having previously missed that I'm perfectly happy to say that it's somewhat hard to discover (particularly once your mind has settled on the word "Concat" for the operation you're doing).

We could certainly consider adding overloads to Append and Prepend; but that's still a different scenario than "turn one item into an IEnumerable of that one item"

With the existing Append:

```C#
IEnumerable<T> results = data.Append(single1).Append(single2).Where(condition);
```

Or with some more overloads:

```C#
IEnumerable<T> results = data.Append(single1, single2).Where(condition);
```

**Comment by terrajobst** [comment]
> "Concat" one element exists, but it's called Append (or, from the other direction, Prepend). Having

Hah! I forgot about that. That's cool!

> but that's still a different scenario than "turn one item into an IEnumerable of that one item"

Agreed. It would be good if @benjamin-hodgson (or anyone else) could chime and state what the scenario for a single element would be. If the use is outside of Linq, then I think a the existing language syntax is good enough. And for Linq, I think the `Append`/`Prepend` methods are probably more useful anyways.
