### ISSUE TITLE
System.Runtime.InteropServices native library call to SendInput works in .net framework but not in .net core

### ISSUE THREAD

**Issue by naddeoa** [dotnet/runtime#1515]
I'm porting an application that uses the SendInput native API from .net framework to .net core. While copying over the bindings from the original project ([link](https://github.com/naddeoa/strokes/blob/master/ConsoleApplication1/NativeBindings/SendInputBindings.fs#L5-L47)) I found that the exact same marshaling code I'm using in the .net framework version doesn't work when I use it in a .net core project.

I tried to get some help online and filing a bug here was the best suggestion I got. I'll include some useful links here.

- [.net framework code that works](https://github.com/naddeoa/strokes/blob/master/ConsoleApplication1/NativeBindings/SendInputBindings.fs#L5-L47)
- [Demo of the issue in .net core](https://github.com/naddeoa/dotnet-core-marshal-error/blob/master/src/Native/SendInput.fs#L10-L52)
- [SO question I opened with some more details](https://stackoverflow.com/questions/59640635/f-system-runtime-interopservices-native-library-call-to-sendinput-works-in-net)
- [It apparently repros in C# as well, so I don't think it's an F# issue](https://github.com/Angr1st/SendInput).

You should be able to check out the demo and run with `dotnet run`. I'm using .net c ore 3.1 on Windows 10. Some useful observations:

- While the code does work in .net framework, I get error code 5 from `Marshal.GetLastWin32Error`, though it doesn't seem to stop my keys from pressing.
- In .net core I just get error code `87 The parameter is incorrect` each time I attempt to call the api.
- In a ton of trial and error, I managed to get key presses working (I explain in the SO question) but it really doesn't make sense why. It just makes me suspect that marshaling isn't happening like I expected it to.
- The size reported by `Marshal.SizeOf(input)` ([here](https://github.com/naddeoa/dotnet-core-marshal-error/blob/master/src/Native/SendInput.fs#L91)) is `28` in both cases currently, but I've tried other marshaling schemes that appear to give different results across the two projects.

**Comment by tannergooding** [comment]
Are you running as 64-bit under .NET Core?

Your `MOUSEINPUT` struct doesn't take 32-bit vs 64-bit into account and incorrectly declares the type of `dwExtraInfo` as `int` when it should be `UIntPtr` (or `IntPtr`, but that doesn't preserve that the native side is `unsigned`).

**Comment by tannergooding** [comment]
The natural alignment of `MOUSEINPUT` and `KEYBDINPUT` will also differ due to `dwExtraInfo` becoming `64-bits` and their offset in `LPINPUT` should be `8` (rather than `4`).

You may have better luck defining a struct such as the following, which will work on both 32-bit and 64-bit platforms (although accessing the union isn't the nicest):
```csharp
    public partial struct INPUT
    {
        public uint type;

        public _Anonymous_e__Union Anonymous;

        [StructLayout(LayoutKind.Explicit)]
        public partial struct _Anonymous_e__Union
        {
            [FieldOffset(0)]
            public MOUSEINPUT mi;

            [FieldOffset(0)]
            public KEYBDINPUT ki;

            [FieldOffset(0)]
            public HARDWAREINPUT hi;
        }
    }
```

**Comment by naddeoa** [comment]
Porting your sample to F# does get it working

```f#

[<StructLayout(LayoutKind.Explicit)>]
type private InputUnion = struct
    [<FieldOffset(0)>]
    val mutable mi : MOUSEINPUT

    [<FieldOffset(0)>]
    val mutable ki : KEYBDINPUT

    [<FieldOffset(0)>]
    val mutable hi : HARDWAREINPUT 
end

[<StructLayout(LayoutKind.Sequential)>]
type private LPINPUT  = struct
    val mutable ``type``: int // 1 is keyboard
    val mutable u: InputUnion
end
```

I suppose that means I was running 32bit in the project I made with visual studio on .net framework. I guess there is more to the .net runtime than I originally thought ([docs](https://docs.microsoft.com/en-us/dotnet/framework/64-bit-apps)).

I still get an error code of `5` from calling SendInput but it doesn't seem to stop anything from actually working and I'm seeing that in my original program too.

Thanks for clearing that up.
