### ISSUE TITLE
API Proposal: Add ReadOnlySpan<T> overload for List<T> AddRange and InsertRange

### ISSUE THREAD

**Issue by rabbitism** [dotnet/runtime#1517]
```csharp
public void AddRange(ReadOnlySpan<T> span)
{
}

public void InsertRange(int index, ReadOnlySpan<T> span)
{
}
```

By Adding this API, it eliminates one extra step of copying span elements into a new array.

**Comment by eerhardt** [comment]
Looks like a duplicate of https://github.com/dotnet/corefx/issues/36198.

**Comment by safern** [comment]
Closing as dupe of: https://github.com/dotnet/runtime/issues/1530

@rabbitism if you're interested on this, please add your motivations on that issue to push it through.
