### ISSUE TITLE
System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly throws NullReferenceException from native host

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#1518]
When hosting .NET Core in a native application, `Assembly.GetEntryAssembly()` returns `null`. The `System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(Type, string, out XmlSerializerImplementation)` method is not prepared for this and throws `NullReferenceException`.

https://github.com/dotnet/runtime/blob/7c24ebc18b3714142b823fe2869b249d155f49c5/src/libraries/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs#L167

**Comment by StephenBonikowsky** [comment]
@AArnott Thanks for reporting this!

**Comment by ericstj** [comment]
Looks to me like this was assuming GetEntryAssembly() would never return null, but it does in this case as mentioned here: https://github.com/dotnet/runtime/issues/25027#issuecomment-374465368

A fix for this would be to handle null, and fall back to something like `AppContext.BaseDirectory` instead.  Perhaps just replace this with `AppContext.BaseDirectory`.

**Comment by vladimir-cheverdyuk** [comment]
I have exactly the same problem

**Comment by StephenMolloy** [comment]
Looks like this was already fixed by #40598. But #52429 also reworks this area of code to improve experiences here. Either way, I believe this issue has been addressed.
