### ISSUE TITLE
Process.ToString() can throw

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#1520]
System.Diagnostics.Process.ToString() throws if the process is already terminated.

[Guideline](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=netcore-3.1#notes-to-inheritors) says:
```
Your ToString() override should not throw an exception.
```

If the process is not terminated the method returns "System.Diagnostics.Process (process name)"
If the process is terminated I'd expect the method returns "System.Diagnostics.Process"

**Comment by danmosemsft** [comment]
On what OS is this? On both Windows and Linux, I started a dotnet process, let it exit, and then got ToString() and I got `System.Diagnostics.Process (dotnet)`

I do believe you -- the state inside VerifyState is not something I can evaluate by looking briefly at it.

Anyway -- yes, it should not throw.

**Comment by iSazonov** [comment]
@danmosemsft It was on Windows. You can see how it was discovered in reference above to PowerShell repo PR.

Interesting, I discovered the same with AccountManagement.Principal.ToString() too.
https://source.dot.net/#System.DirectoryServices.AccountManagement/System/DirectoryServices/AccountManagement/Principal.cs,9947ba7370a8b6cd

It is based on Name property and if context (_ctx) was disposed ToString() throws.
The context is created before for search and can be disposed after the search is finished but finded Principal object is still live. (Although perhaps the throw protects from wrong using the API. )

**Comment by danmosemsft** [comment]
Thanks. We'd take PR's to stop either of these throwing.
