### ISSUE TITLE
InstallLocation registry key doesn't exist for .NET Core 3.1

### ISSUE THREAD

**Issue by tjmoore** [dotnet/runtime#1522]
According to https://github.com/dotnet/core-setup/issues/4904 and https://github.com/dotnet/designs/blob/master/accepted/install-locations.md I should be able to check the version of .NET Core installed from 3.0 onwards in the following registry location...

`HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\<arch>\InstallLocation`

However this is not the case on my machine. I only have...

`HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost` with a `Version` key. No other folders or keys under `HKLM\SOFTWARE\dotnet`.

I realise this may be related to having Visual Studio 2019 installed on my development machine (WIndows 10 Pro) which I assume installed .NET Core SDK (3.1) rather than the runtime.

Is there a reliable way of simply detecting programmatically if .NET Core 3.1 exists for both runtime and SDK? Or has the registry key location changed since 3.0?

My requirement is to check it's installed in an Inno Setup installer and install the runtime if missing. I can't rely on the 'dotnet' command as I have no idea if it's on the PATH and don't want to go trawling around the filesystem to find it with potential for it to be in a non-standard location.

**Comment by Symbai** [comment]
The `InstallLocation`  gets only created by SDK installers. `Dotnet` command is not available when the runtime is installed by install script. And other .NET Core versions may behave completely different.

That's why I am super thankful that since .NET Core 3.1 the apphost automatically checks for .NET Core 3.x runtime (the runtime it needs to host your application) is installed and prompt when missing. So if you develop a windows desktop application and target .NET Core 3.1 or higher you won't need to check it yourself unless you plan to auto install it when missing.

**Comment by tjmoore** [comment]
Hmm, I'm not installing a desktop application, just a .NET Core web API hosted in a service and couple of console apps.

That's not going to prompt I suspect? Especially as the first run of any code would be on service start during the installer, and that's running local system without desktop interaction.

I could resort to making a self contained build including the runtime, but I wanted to keep the package size down and also take advantage of Windows updates patching .NET Core rather than have to issue updates to the installer for runtime fixes.

**Comment by Symbai** [comment]
As far as I know Windows Update does not install .NET Core runtime at all see https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/#comment-2976 and that make sense when .NET Core is side-by-side which would bloat up at some point when distributed through Windows Update. I'm not sure if this is different for .NET Core web hosting stuff.

For .NET 3.x I think checking sharedhost version registry key is probably the best you can do (although I know about situations where this failed for a reason I dont know) if you don't want to take the safe and recommend route via filesystem / hostfxr. There is also a guide about writing your own apphoster which you can catch exceptions to know if a runtime is missing. See https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting and https://github.com/dotnet/samples/tree/master/core/hosting but that is also a bit of effort.

**Comment by danmosemsft** [comment]
This active PR is relevant, as it pops a dialog in this case. @vitek-karas @mateoatr 
https://github.com/dotnet/runtime/pull/1222

**Comment by tjmoore** [comment]
> As far as I know Windows Update does not install .NET Core runtime at all see https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/#comment-2976 and that make sense when .NET Core is side-by-side which would bloat up at some point when distributed through Windows Update. I'm not sure if this is different for .NET Core web hosting stuff.

The deployment documentation states a benefit of FDD is to use the latest patched versions without having to repackage your application. Though I'm talking about updates to the runtime rather than it being installed in the first place by Windows Update. I'm happy to do the first install if necessary.

From https://docs.microsoft.com/en-us/dotnet/core/deploying/ ...

> _Unless overridden, FDDs will use the latest serviced runtime installed on the target system. This allows your application to use the latest patched version of the .NET Core runtime._

If that's not the case then the only reason to not choose SCD is the package size. If target systems aren't getting patches automatically in the shared runtime then it's surely bad practice to use FDD.

**Comment by vitek-karas** [comment]
@danmosemsft #1222 will only happen for GUI apps. The apphost will not popup dialog for non-GUI apps. So for example ASP.NET services are console apps, those will get the errors written to stderr.

**Comment by tjmoore** [comment]
Answering one of my questions on compatibility, according to documentation framework-dependent apps to support roll forward.

https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward

So if I read this right, if I target 3.1, then it will match any minor version of 3.1.x. Not 3.2 though? I want to target 3.1 specifically as it's on LTS.

**Comment by vitek-karas** [comment]
The policy is based on rollForward setting which you can read about here: https://github.com/dotnet/designs/blob/master/accepted/runtime-binding.md
The default setting is "Minor" which means roll forward to closest equal or higher version as long as it has the same major version. So if you specify 3.1.0 it will roll to closest match in 3.*.*.
On top of that it applies "LatestPatch" always, so once it find the closest minor version - could be 3.2.* (if there's no 3.1.* on the machine) then it will take the latest patch, so could be something like 3.2.5 (even if there is 3.2.1).

If you want to stick to a specific minor version , so for example 3.1.*, you can specify version 3.1.0 and rollForward=LatestPatch. In that case it will only consider 3.1.* and take the latest in that range (latest patch policy).

**Comment by tjmoore** [comment]
>  if you don't want to take the safe and recommend route via filesystem / hostfxr. 
Problem I can see is there is the option of global install in a custom location. That means hunting through the file system.

That's my point. The install locations guide specifies a registry key in a known location to show the location. Not that I'm looking for the files really, I just want the version installed.

https://github.com/dotnet/designs/blob/master/accepted/install-locations.md#global-install-to-custom-location

**Comment by vitek-karas** [comment]
Please make sure you're looking into 32bit registry tree - the doc specifically states:
>Windows - the installer will store the install location in 32-bit registry (for both 32-bit and 64-bit installations):
HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\<arch>\InstallLocation - where <arch> is one of the x86, x64, arm or arm64. Note that this registry key is "redirected" that means that 32-bit processes see different copy of the key then 64bit processes. So it's important that both installers and the host access only the 32-bit view of the registry.

When looking at it using regedit on a 64bit OS the actual path is:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions

Using APIs there are flags to ask for 32bit view of the registry.
The 64bit tree has the dotnet/Setup keys in it, but those will not contain the InstallLocation values.

**Comment by tjmoore** [comment]
Ah, I see now, thanks. I believe with Inno Setup which I'm using I can specifically query 32bit view.

Thinking though that this is still complicated and maybe I should go about it in a different way. For example it would seem complicated if in my installer I determine 3.1 isn't installed, do I install 3.1 but then can I know if there's a "compatible" higher version so don't need to install? Though maybe there's no harm installing 3.1 anyway even if it picks up a newer version.

As said, my application is a windows service so can't rely on the UI pop-up, but then I could write a simple bootstrap type executable for .NET Core 3.1 which does nothing other than either trigger the pop-up install or otherwise confirm/log valid version is installed.

**Comment by vitek-karas** [comment]
You could use the native hosting APIs to try to "Start" an app with your custom `.runtimeconfig.json` (which would contain the right version you depend on) - during install. That would be calling the `hostfxr_initialize_for_runtime_config` - see [native hosting](https://github.com/dotnet/runtime/blob/master/docs/design/features/native-hosting.md). And if that fails you can ask the user to install it. That is basically programatic way of what you suggested (an empty app which just causes the popup).

**Comment by tjmoore** [comment]
So the empty app approach doesn't work well for me. All it does is launch a browser directed at the .NET download page and leaves the end user in limbo not knowing what to download (Core, Framework, runtime, sdk, desktop or hosting runtime ?).

While I know what to pick, the typical users for our application won't have a clue. Up to now with .NET Framework we've been able to supply a direct link to the framework required based on the links here https://docs.microsoft.com/en-us/dotnet/framework/deployment/deployment-guide-for-developers#redist. We just detect if current runtime is lower than required, download the installer exe direct from the link and run it, waiting for success and continue the install.

What I want is something similar with ,NET Core runtime.

I've looked at the native hosting link provided but this may be beyond me to integrate into an Inno Setup script (or otherwise create an executable which I guess has to be C/C++).

Possibly may have to resort to documentation specifying user must install the runtime before install, which is likely to not be read, or bundle the runtime as a self-contained deployment. This I think forces building 64bit and 32bit specific installs and have always tried to avoid this for a number of reasons, though dropping 32bit might be an option.

A further alternative is to just target .NET Framework instead.

**Comment by Symbai** [comment]
> 
> 
> So the empty app approach doesn't work well for me. All it does is launch a browser directed at the .NET download page and leaves the end user in limbo not knowing what to download (Core, Framework, runtime, sdk, desktop or hosting runtime ?). It also hits major issues with Windows Server as by default security blocks everything including Microsoft web sites, and blocks downloads also.
> 

This sounds familiar https://github.com/dotnet/core-setup/issues/8902.

**Comment by vitek-karas** [comment]
The web-server side of the solution is still in the works: https://github.com/dotnet/core-setup/issues/8902
Eventually it should point to the exact installer to download.

As for the Windows Server - any kind of download link will lead to the same problem. The only solution here would be direct integration with the OS (which is what .NET Framework has) - but that is something we have no plans on doing for .NET Core.

If you have an installer already - it should be possible to chain the installer for the runtime. Maybe a simple check if the "empty app" works at all - if not, simply download/execute the runtime installer you know will fix it. I'm no MSI expert, but I would expect there to be a way to tell it "install this if it's not already installed". This would be basically the same thing you're doing today for .NET Framework - just the detection will look different (either registry check, or running an empty app, ...) and a different link.

**Comment by tjmoore** [comment]
The empty app does set the error level to a value which appears to indicate no runtime installed. However it would still trigger the pop-up which would get confusing.

Alternatively, if a console app returns the same code in the absence of the runtime, then that would do it as it doesn't have the pop-up. I'll check if that's the case.

I already chain the installer for .NET Framework runtime sucessfully (based on https://blogs.msdn.microsoft.com/davidrickard/2015/07/17/installing-net-framework-4-5-automatically-with-inno-setup/, but tweaked for .NET 4.7.2 which is our current target for the Framework part of the app).

Important thing though is I need to rely on the direct links to the installer executables being permanent (or long enough for the lifetime of the product). With .NET Framework it appears I can rely on them (based on the published links in the document above). If the links expire, then it's no use.

**Comment by vitek-karas** [comment]
For a silent detection: the registry key check should be the cleanest. After that a console app (that won't popup anything) and the error codes are described here: https://github.com/dotnet/runtime/blob/master/docs/design/features/host-error-codes.md

As for the link I would be super surprised if they were not permanent for .NET Core. @richlander should know for sure what is the policy around download links for released versions. What's probably an interesting question also for @richlander: Is there a link to get the latest patch for major.minor? (since there's no windows update, so you would not get patches automatically).

**Comment by tjmoore** [comment]
With a console app I get the following when the runtime is not installed

CoreHostLibMissingFailure (0x80008083)

As for the registry check, same issues apply as before where I may need complex logic to work out if what is installed is compatible with what I want. Getting the host to just tell me having done it's own comprehensive set of checks, then that simplifies the installer's work, I hope.

Unless I have to do some complex checks on the error codes to cover all bases. Then again, maybe if I just get non-zero I suggest installing the target runtime and attempt to install it. If it already exists then it would handle that I assume. If there's a newer compatible version then it doesn't matter if I install the runtime I want also I guess. The app itself might pick up the newer compatible version anyway.

**Comment by vitek-karas** [comment]
The other error code to watch for is  
FrameworkMissingFailure (0x80008096) 

(That would happen if there already is .NET Core on the box, but not high enough version to run your app).

Otherwise I agree with what you wrote.

**Comment by tjmoore** [comment]
ps just spotted a security patch for 3.1 already released as 3.1.1

We're looking at deploying the hosting bundle for our use, so this link would be what I want now I assume: https://download.visualstudio.microsoft.com/download/pr/c9206d6d-a11a-4b0b-834b-6320c44d0a2d/993571f75a96b6a64f8bca001797c4f0/dotnet-hosting-3.1.1-win.exe

Am still concerned about patches if they're not applied through Windows Update. It means keeping an eye on the releases and advising customers to install the patch. Though at least we don't have to create and test a new build each time.

**Comment by tjmoore** [comment]
Of further interest, had I stuck with the WinExe, it would still prompt if I only installed the runtime or hosting runtime, as it wants the desktop runtime. So that wouldn't have been a good approach.

![dotnet-prompt](https://user-images.githubusercontent.com/1078106/72554114-f6305f00-3891-11ea-89fd-25cf3b56a1ed.png)

The console app is fine though. Targets 3.0, detected no install. Installed 3.1.1 only and re-run and it runs fine.

**Comment by richlander** [comment]
I am unaware of a perma-link, as is being asked for. Is the goal to setup a web query that always provides the runtime desired? Like "latest 3.1 runtime for x64, as an msi"? Is that the sort of expectations?

**Comment by tjmoore** [comment]
I'm currently trying this link for our installer:

https://download.visualstudio.microsoft.com/download/pr/c9206d6d-a11a-4b0b-834b-6320c44d0a2d/993571f75a96b6a64f8bca001797c4f0/dotnet-hosting-3.1.1-win.exe

This is for the hosting bundle. I notice it doesn't specify x86 or x64 unlike the other runtime downloads.

If that link is permanent, then that's okay. Though perma-links like with .NET Framework as described here would be great if not or to provide a short link.

https://docs.microsoft.com/en-us/dotnet/framework/deployment/deployment-guide-for-developers#redist

My requirement is simply to get the installer executable directly for the version I want to install. I don't necessarily need a query URL, but if that works reliably then it's okay. I'm cautious about query pages that may redirect as I'm relying on the Inno Download Plugin for Inno Setup, but it might handle it.

**Comment by richlander** [comment]
That link is for a patch version (as I'm sure you understand). Next month, we'll be on to 3.1.2.  I thought you were asking for a link that would be be to just "3.1" and would move forward with each patch. If you are familiar with Docker, this is similar to what the "3.1" tag does in our repos @ https://hub.docker.com/_/microsoft-dotnet-core-runtime. Make sense?

**Comment by centreboard** [comment]
@richlander For querying latest version and its download link, is  
https://dotnetcli.azureedge.net/dotnet/release-metadata/3.1/releases.json the best link?

This is used by [dotnet install script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).

The links for each major.minor version can be found https://github.com/dotnet/core/blob/master/release-notes/releases-index.json

**Comment by richlander** [comment]
Understood. That's why I asked if @tjmoore was looking for a web url. I'm wanting to understand the use case he is after.

**Comment by tjmoore** [comment]
Yes, thinking about it, I just picked 3.1.1 as being the current latest but it wouldn't install a later patch. A 3.1 link that would get the latest patch compatible with 3.1 sounds more ideal.

The use case is simply I'm installing a framework dependent service targeting 3.1 and need to ensure the correct runtime is installed globally before the installer starts the service, but also want the service app to run on newer compatible patch versions if they are installed.

The hope was it would install 3.1 and then Windows would get an update to latest patch, basically same as we do with .NET Framework, i.e. we install 4.7.2 via a fixed link unless a newer version is installed and Windows gets updates to the framework.

Parsing JSON is a bit more tricky with Inno Setup scripts I think. The [Inno Download Plugin](https://mitrichsoftware.wordpress.com/inno-setup-tools/inno-download-plugin/) is what I use to download dependencies in the installer. Anything that works with that would be great.

Though the dotnet install script is perhaps another option but needs to involve no user prompts and I notice it says for non-admin installs but I need to install globally which would need admin rights (our installer runs as admin anyway).

**Comment by tjmoore** [comment]
On the error codes to check, during test the version check app I'm using has returned error -2147450726 (0x8000809a). Oddly it hasn't come up before on the same machine I believe and yet there's no change to the app binary and it runs fine on my machine and various others.

_LibHostAppRootFindFailure (0x8000809a) - Returned by apphost if the imprinted application path doesn't exist. This would happen if the app is built with an executable (the apphost) and the main app.dll is missing._

**Comment by vitek-karas** [comment]
You can try to get corehost tracing - that should have a bit more info:
`COREHOST_TRACE=1`
`COREHOST_TRACEFILE=t.txt`

Run the app - and let it fail.
Open the `t.txt` it should have more details.

**Comment by NikolaMilosavljevic** [comment]
> Ah, I see now, thanks. I can see the registry key now under WOW6432Node. I believe with Inno Setup which I'm using I can specifically query 32bit view.
> 
> This issue can probably be closed.
> 

Closing, no repro.
