### ISSUE TITLE
How can I obtain a folder with CoreRun and all runtime and reference assemblies after recent build changes?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#1523]
### Background

Some time ago we have switched to BenchmarkDotNet which runs every benchmark in a dedicated process (to achieve process-level isolation and reproducible results). It also generates some boilerplate code to help the users avoid common benchmarking pitfalls (consuming the method result etc).  So **it needs to be able to build and run some code**.

To work with local builds of CoreCLR|FX, we have decided to use **CoreRun** as a runner. It loads the `System*.dlls` that are next to it without checking the version numbers and just executes the code.

The feature got exposed via console line argument `--coreRun` and is very frequently used by devs who work on the Team.

https://github.com/dotnet/performance/blob/master/docs/benchmarkdotnet.md#CoreRun

### The problem

When we have initially switched to the new mono repo, I've tested that everything worked properly.

But before I've started my winter holidays I was told by few team members that it does not work anymore.

I've pulled the recent changes and built entire repo using following command:

```cmd
build -c Release
```

I can find `CoreRun.exe` in two folders:

```log
C:\Projects\runtime\artifacts\bin\coreclr\Windows_NT.x64.Release
C:\Projects\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\hosts\corerun\Release
```

The problem is that **none of these folders contains System.dll assemblies required to run the benchmarks** and benchmarking fails with following error:

```log
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

### Solution

I've tried to read the docs and run a few extra commands (`build.cmd -c Release -buildtests` for example), but I was not able to get what I wanted. Did I miss something?

I don't know why `CoreRun` is not copied to the folder with `System*.dlls` anymore. @ViktorHofer @ericstj  Could we just restore the old behavior? Or expose it via some optional script argument? I would really like to keep it simple to make sure that benchmarking and profiling local builds is easy for everyone.

/cc @stephentoub

**Comment by hnrqbaggio** [comment]
When I had to test with CoreRun a few weeks ago, I've followed the instructions from [this page](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/using-corerun.md) about using the CORE_LIBRARIES env var to point to the right location of the libraries' DLLs. It worked, but then I had to remember doing that on every new cmd tab I've used, so it's still not as simple as the old flow.

**Comment by adamsitnik** [comment]
@ViktorHofer ping

**Comment by ericstj** [comment]
Those folders are the build output of CoreCLR.  If you had CoreRun before, it was likely the output of some restore operation that was not maintained in the live/live work.  /cc @jkoritzinsky 

> I don't know why CoreRun is not copied to the folder with System*.dlls anymore.

Likely because it's not needed by the official build nor CI.  I bet folks just cleaned it up.  If you do work to bring it back, make sure to include comments about what its for, or merely construct what you need yourself from stable build outputs.

**Comment by jkoritzinsky** [comment]
The reason you don’t see them is because the coreclr test build isn’t wired up to the root build scripts. You’ll want to run the build_test scripts in src/coreclr to get Core_Root generated.

**Comment by danmosemsft** [comment]
this may simply be a matter of having the build copy corerun.exe into `artifacts\bin\testhost\netcoreapp5.0-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\5.0.0` . Every other necessary file seems to be in there. Right?

**Comment by danmosemsft** [comment]
or use corerun.exe from wherever and set CORE_ROOT and CORE_LIBRARIES

**Comment by adamsitnik** [comment]
> Right?

100% right

> or use corerun.exe from wherever and set CORE_ROOT and CORE_LIBRARIES

this makes it hard to compare multiple versions at the same time (now we just pass multiple paths to `--corerun`)
