### ISSUE TITLE
Add opt-in setting for ensuring strong random numbers

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#15285]
There have been some reports that Linux and OpenSSL in particular may not use enough entropy in all scenarios

https://www.blackhat.com/docs/us-15/materials/us-15-Potter-Understanding-And-Managing-Entropy-Usage-wp.pdf

We need to ensure we are properly seeding OpenSSL's PRNG.

There are some conflicting articles/sites that say using /dev/urandom is sufficient:
http://www.2uo.de/myths-about-urandom/
http://security.stackexchange.com/questions/7718/openssl-rand-poll-good-enough
http://security.stackexchange.com/questions/3259/howto-seed-the-prng-in-openssl-properly?rq=1

One idea is to use the new [getrandom()](http://man7.org/linux/man-pages/man2/getrandom.2.html) syscall, which will block if there isn't enough entropy in the system.  When that isn't available, we need to decide whether we should:
1. block
2. fail
3. continue

**Comment by bartonjs** [comment]
There really hasn't been a lot of interest in this issue; and any workload that was genuinely concerned can just have a startup script with a higher execution order that calls into the blocking read from the PRNG pool, or reads a single byte from /dev/random.  There's not a strong reason we need to move that into our runtime.
