### ISSUE TITLE
API for inserting a Span<T> into a List<T> efficiently

### ISSUE THREAD

**Issue by josetr** [dotnet/runtime#1530]
EDITED 9/22/2022 by @stephentoub:

```diff
namespace System.Collections.Generic
{
    public class List<T>
    {
+        public void AddSpan(ReadOnlySpan<T> span);
+        public void InsertSpan(int index, ReadOnlySpan<T> span);

+        public void CopyTo(Span<T> span);
    }
}
```

- We can't just add an AddRange overload as it's ambiguous for anything convertible to both span and enumerable, like array. We could alternatively call it AddRange and add overloads as well for arrays and strings. 

--- 

Perhaps an `AddRange` overload taking a `Span<T>` can be added to the `List` class?

```
var list = new List<byte>();
list.AddRange(new Span<byte>());
```

**Workarounds**

```
foreach(var b in span)
    list.Add(b); // Inefficient only copying one byte at a time
```

```
var list = new List<byte>();
var span = new Span<byte>();
list.AddRange(span.ToArray()); Silly allocation
```

**Comment by Raymonf** [comment]
Since this is now closed (I didn’t see the comment by the bot from 2 weeks ago), what is the preferred solution for doing this while avoiding the allocation that would come from `ToArray()`? Does one exist?

**Comment by eiriktsarpalis** [comment]
@Raymonf to my knowledge the only known workarounds are the ones listed in the OP. In the future it might be possible to do this using the [CollectionsMarshall.AsSpan](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal.asspan?view=net-5.0) method, however we're still missing a method for presizing lists (cf. #55217). In pseudocode it would look as follows:

```csharp
public static void AddRange<T>(this List<T> list, ReadOnlySpan<T> items)
{
    int initialCount = list.Count;
    list.Resize(initialCount + items.Length); // !!! NB this method is currently not implemented
    Span<T> buffer = CollectionsMarshal.AsSpan(list);
    items.CopyTo(buffer.Slice(initialCount));
}
```

**Comment by MihaZupan** [comment]
@eiriktsarpalis how come we're closing this? Was there a decision to reject the proposal altogether?

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/1530#issuecomment-952111787

**Comment by MihaZupan** [comment]
I guess the question is "why was `no-recent-activity` added"

**Comment by eiriktsarpalis** [comment]
See #60288 for context.

**Comment by stephentoub** [comment]
I updated the top post.  I think we should add this.  `List<T>` is the primary growable array type we push people to use, and `ReadOnlySpan<T>` is now a critically-important data type; you should be able to add the latter to the former efficiently.

**Comment by eiriktsarpalis** [comment]
Are there opportunities for adding other span overloads? At quick glance, a constructor accepting `ROS<T>` and a `CopyTo(Span<T>)` overload seem like obvious candidates.

**Comment by tfenise** [comment]
Adding the proposed overload `public void AddRange(ReadOnlySpan<T> collection);` (as well as `InsertRange`) would be a source code breaking change, because there would be an ambiguity when passing a `T[]` as the argument `collection`. Potential solutions include introducing another overload taking a `T[]` as parameter, or adding the proposed overload as an extension method, or maybe renaming the proposed overload (but we may want an argument of type `T[]` to go through the overload with parameter `ReadOnlySpan<T>` instead of `IEnumerable<T>`).

**Comment by stephentoub** [comment]
> Are there opportunities for adding other span overloads? At quick glance, a constructor accepting ROS<T> and a CopyTo(Span<T>) overload seem like obvious candidates.

CopyTo would be reasonable.  It does have a workaround today, which is that someone can use CollectionsMarshal.AsSpan to get a span for the list, and then CopyTo with that as the source... there's no good workaround today for AddRange.

A ctor is going to have the same ambiguity problem that tfenise calls out, and we can't workaround that with a name.

**Comment by terrajobst** [comment]
* We should talk to @jaredpar / @dotnet/ldm about whether his proposal for "binary compatibility only" could be used here to avoid having to add new method group. We could also make them extension methods in which case they wouldn't cause ambiguities but only be used for spans. That being said, given that F# and VB wouldn't have the hypothetical feature so we probably would do the extension method for a core type anyway.
* There is another concern about generic instantiations and lack of pay-for-play for methods only used for some `T`s.

This would be the desired API:

```C#
namespace System.Collections.Generic;

public partial class List<T>
{
    public void AddRange(ReadOnlySpan<T> span);
    public void InsertRange(int index, ReadOnlySpan<T> span);
    public void CopyTo(Span<T> span);
}
```

If we go down the extension method route, it would look like this:

```C#
namespace System.Collections.Generic;

public static class CollectionExtensions
{
    public static void AddRange<T>(this List<T> list, ReadOnlySpan<T> source);
    public static void InsertRange<T>(this List<T> list, int index, ReadOnlySpan<T> source);
    public static void CopyTo<T>(this List<T> list, Span<T> destination);
    // We discussed this but decided against this until there is a need.
    // public static bool TryCopyTo<T>(this List<T> list, Span<T> destination);
}
```

We're inclined to approve the extension method shape and simultaneously work with the compiler team to see whether we can use a language feature to avoid using the extension methods.
