### ISSUE TITLE
System.Media.SoundPlayer doesn't exist.

### ISSUE THREAD

**Issue by themightyjohn** [dotnet/runtime#1532]
Hello,

I have been trying to use System.Media.SoundPlayer in a dotnet Core 3.1 Console Application however Visual Studio just complains it doesn't exist.

The documentation says that its available in 3.0 and 3.1.
https://docs.microsoft.com/en-us/dotnet/api/system.media.soundplayer?view=netcore-3.1

Looking at the code in this repository and an issue raised from last year (https://github.com/dotnet/corefx/issues/32413) it looks like it just doesn't.

Is it worth removing the compatibility from the documentation to avoid confusion?

Is there an ETA yet for SoundPlayer?

Thanks,
John.

**Comment by jkotas** [comment]
You need to add https://www.nuget.org/packages/System.Windows.Extensions/ nuget package. It is not part of cross-platform .NET Core API set that you get by default.

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs is the sources in case you need it.
