### ISSUE TITLE
System.Net.Quic outstanding TODOs

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#1533]
The first draft of a System.Net.Quic implementation has been merged with MsQuic, however there are many outstanding TODOs and issues remaining in it:

- [x]  Improve exception model and return better error messages: https://github.com/dotnet/runtime/pull/427/files#diff-7de745b7b8a7c7ef4bdbda8bf8e556b0R29
- [x] Use SocketAddress instead of native struct for IPEndpoint https://github.com/dotnet/runtime/pull/427/files#diff-51b7a0f017df755ef4017a8475265089R27
- [x] Make sure security configurations work for client certificates https://github.com/dotnet/runtime/pull/427/files#diff-6e5315cfb2b55631260080af621476cdR9
- [x] Expose SNI callback for certificate selection https://github.com/dotnet/runtime/pull/427/files#diff-c955a111c9d2555293bd97d040fb4bf7R43
- [x] Review graceful shutdown vs abort https://github.com/dotnet/runtime/pull/427/files#diff-c955a111c9d2555293bd97d040fb4bf7R62
- [x] Remove all IntPtrs with SafeHandles
- [x] Investigate why a static function callback didn't work under stress https://github.com/dotnet/runtime/pull/427/files#diff-9b479f458439af3be82141201059672fR29
- [ ] Figure out how Session objects can be abstracted in a way that allows for 0-RTT in the future.
- [x] Improve error propagation in event loop https://github.com/dotnet/runtime/pull/427/files#diff-9b479f458439af3be82141201059672fR160
- [x] Investigate why calling session close blocks in listener shutdown https://github.com/dotnet/runtime/pull/427/files#diff-c87b76a7ba30883ba5ddb299f715d8e6R113
- [ ] Don't return pending if we have already resolved the security configuration https://github.com/dotnet/runtime/pull/427/files#diff-c87b76a7ba30883ba5ddb299f715d8e6R163
- [ ] Consider Interlocked.Exchange instead of a lock here: https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R66
- [x] Consider buffering calls to read https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R221
- [x] Make AbortRead thread safe. https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R258
- [x] Make sure all writes are stopped https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R282
- [x] Remove sync of async for all blocking calls https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R308 
- [x] Handle canceled writes from MsQuic https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R673
- [x] Support overlapping SendAsync calls without awaiting. https://github.com/dotnet/runtime/pull/427/files#diff-ab674bd5c6a7a2f76e39c73622f97a01R718
- [x] Figure out what max limits are for bidirectional and unidirectional streams. https://github.com/dotnet/runtime/pull/427/files#diff-06e88f670d0b4d26bd01dcc21d89dae3R34

**Comment by scalablecory** [comment]
I've split this out into separate issues; closing.
