### ISSUE TITLE
Expression interpreter - Remove dead code

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/runtime#15440]
There's some unused code in a variety of places of the expression interpreter that can be removed to reduce code size.

**Comment by deeprobin** [comment]
If you like you can assign the issue to me. I'd be happy to take it over once some of my open PRs are merged.

**Comment by cston** [comment]
Closing as per [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/README.md).
