### ISSUE TITLE
Compression.ZipFile support for Unix Permissions

### ISSUE THREAD

**Issue by ianhays** [dotnet/runtime#1548]
Split from dotnet/corefx#17067 

# Proposal

We should add support in the Unix ZipFile for working with zips that contain entries with associated file permissions information. Right now the only way to capture or check the permissions info of an entry is to do some manual bit shifting of the `ExternalAttributes` field. We can do better than that.

Wanting your zips to unzip with the same permissions they were zipped with is a very common scenario that we do not currently support. I propose that we do two things:
1. Make our ZipFile.Create* Apis check the permissions of a file (on Unix) and store them in the entries
2. Add new ZipFile.Extract* overloads to apply the permissions stored in a zip to the output files on disk.

# New API
```c#
namespace System.IO.Compression
{
    public static partial class ZipFile
    {
        public static void ExtractToDirectory(string sourceArchiveFileName, string destinationDirectoryName, System.Text.Encoding entryNameEncoding = null, bool overwriteFiles = false, bool preservePermissions = false) { }
    }
    public static partial class ZipFileExtensions
    {
        public static void ExtractToDirectory(this System.IO.Compression.ZipArchive source, string destinationDirectoryName, bool overwriteFiles = false, bool preservePermissions = false) { }
        public static void ExtractToFile(this System.IO.Compression.ZipArchiveEntry source, string destinationFileName, bool overwrite = false, bool preservePermissions = false) { }
    }
}
```

# Implementation

The follow-through here is relatively easy - stat files on creation, chmod them on extraction. The somewhat bothersome part is that we will need to make the System.IO.Compression.ZipFile assembly platform-specific because the new permissions support will be Unix-only. 

Work-in-Progress solution available here: https://github.com/ianhays/corefx/commits/zipfile_perms

# Benefit

Zips created using ZipFile on Unix will be usable interchangeably with those created using the `zip` command as far as permissions are concerned. Using ZipFile to unzip zips created with `zip` will create files that have the same permissions as they were created with. Makes our Unix users happy. @eerhardt is happy.

PTAL: @stephentoub @JeremyKuhne @terrajobst  @eerhardt @ViktorHofer

**Comment by eerhardt** [comment]
> We could also expose the permissions in the ZipArchiveEntry.

We are already exposing `ExternalAttributes` on `ZipArchiveEntry`, which contains the permissions.

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.IO.Compression/ref/System.IO.Compression.cs#L110

It was done with https://github.com/dotnet/corefx/pull/18565

**Comment by marcwittke** [comment]
How is it supposed to be used? Like this? I don't get it :man_shrugging: 

```csharp
ZipArchiveEntry entry = zipArchive.CreateEntry("file.txt");
entry.ExternalAttributes = 644;
```

**Comment by svick** [comment]
@marcwittke The original issue (https://github.com/dotnet/runtime/issues/20603) links to [a Stack Exchange answer](https://unix.stackexchange.com/a/14727/2303), which explains the format. It's certainly not as simple as using the octal notation of the permissions you want.

**Comment by marcwittke** [comment]
yeah, found it, read the cryptic part (hey, I am writing code in .net for *not* having to shift bits :rofl: ) and came up with this:

```csharp
entry.ExternalAttributes = entry.ExternalAttributes | (Convert.ToInt32("664", 8) << 16);
```

key is that the permission is an octal literal, that does not exist out-of-the-box in .net.

**Comment by RoguePointer80** [comment]
This issue is now more than 3 years old, and the implementation is not *that* difficult; the conclusion from the discussion was that no API change was needed at this point since permissions save/apply on Unix is by-default, like other Unix tools (ZipInfo).
I see that Ian Hays started the work a while back, maybe I can get inspiration from that work and start a new branch.
Is there anything special holding back this issue?

**Comment by eerhardt** [comment]
> Makes our Unix users happy. @eerhardt is happy.

4 years later, @eerhardt is happy 😃

**Comment by jeffhandley** [comment]
Thanks for doing this, @eerhardt!!
