### ISSUE TITLE
Re-evaluate various #define symbols in System.Linq.Expressions

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/runtime#15549]
The following symbols are used in the code but are never set in corefx:
- FEATURE_DLG_INVOKE
- FEATURE_FAST_CREATE
- FEATURE_MAKE_RUN_METHODS
- FEATURE_THREAD_ABORT
- FEATURE_STACK_TRACES
- NO_FEATURE_STATIC_DELEGATE

We should re-evaluate whether those are useful to enable in some build flavors e.g. to improve performance of the interpreter.

**Comment by cston** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/19107.
