### ISSUE TITLE
Make the ZipArchiveEntry OffsetOfCompressedData property public

### ISSUE THREAD

**Issue by mashles** [dotnet/runtime#1554]
Is it possible for the ZipArchiveEntry OffsetOfCompressedData property to change to public? 

It is useful to be able to store the offset and compressed length, so a particular files byte range can be downloaded from a blob to save time/bandwidth.

It works fine but we had to write our own zip parser to get the offset, it would be great if we could just use the existing property thats private right now.

**Comment by danmosemsft** [comment]
No update - closing.
