### ISSUE TITLE
Expression interpreter - Reflection calls could be made cheaper

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/runtime#15556]
Blocked by https://github.com/dotnet/coreclr/issues/7253

Spotted while looking into dotnet/runtime#15553. The calls to MethodBase.Invoke in various places ultimately call into MethodBase.CheckArguments which performs a copy of the arguments array passed in. In cases such as the interpreter's where the caller is trusted to transfer ownership of the array, this copy is redundant.

Both dotnet/runtime#15553 and this issue could possibly get resolved by controlling more of those behaviors (i.e. Type.Missing checks in dotnet/runtime#15553 and argument copying in this issue) through the Binder that's passed to the Invoke method. An (internal-only) specialized fast-path binder could be passed by the interpreter.

**Comment by deeprobin** [comment]
@cston Is this issue still relevant, because `System.Linq.Expressions` is eff. archived?

**Comment by cston** [comment]
Closing as per [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/README.md).
