### ISSUE TITLE
Support serialization of Microsoft.Extensions.Primitives.StringValues

### ISSUE THREAD

**Issue by joshmouch** [dotnet/runtime#1559]
I'm switching to System.Text.Json from Json.Net, and the following is no longer serializable:
`Microsoft.AspNetCore.Http.FormFile`

The exception is:
```
System.NotSupportedException : The collection type 'Microsoft.AspNetCore.Http.IHeaderDictionary' on 'Microsoft.AspNetCore.Http.FormFile.Headers' is not supported.`
```

Will this be supported? Are there any workarounds?

**Comment by bergi9** [comment]
This following code fails for me even when it's empty
```c#
class Test
{
    public IList<IFormFile> file { get; set; }
}

...

var str = JsonSerializer.Serialize(new Test());
```

```
System.NotSupportedException: The collection type 'Microsoft.AspNetCore.Http.IHeaderDictionary' on 'Microsoft.AspNetCore.Http.IFormFile.Headers' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonPropertyInfo.get_ElementClassInfo()
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
```

**Comment by terenceng2010** [comment]
> 
> 
> I don't have this issue anymore. The problem was caused by what I RETURNED from the Controller method instead of the parameter of the method.
> 
> For the input of the method I want to have the uploaded file IFormFile type, but also the meta data. So what I did was create a base class (CustomFile) with attributes like name and such. Then I created a subclass (UploadFile) that inherits from CustomFile and adds the IFormFile as a field.
> 
> As the standard method to implement this is the POST method, the standard return is CreatedAtAction("GetCustomFile", ...). What I did here before was return the UploadFile - and this causes the error. But I don't want to return the file to the client, but just the meta data (CustomFile). When I changed that, error was gone.
> 
> Does this help for you? I hope I explained it in a way you can understand it :)

This works for me. Basically the FileInfo that consists of the upload file should NOT be returned to the CreatedAtAction method.

**Comment by arham-anees** [comment]
> I don't have this issue anymore. The problem was caused by what I RETURNED from the Controller method instead of the parameter of the method.
> 
> For the input of the method I want to have the uploaded file IFormFile type, but also the meta data. So what I did was create a base class (CustomFile) with attributes like name and such. Then I created a subclass (UploadFile) that inherits from CustomFile and adds the IFormFile as a field.
> 
> As the standard method to implement this is the POST method, the standard return is CreatedAtAction("GetCustomFile", ...). What I did here before was return the UploadFile - and this causes the error. But I don't want to return the file to the client, but just the meta data (CustomFile). When I changed that, error was gone.
> 
> Does this help for you? I hope I explained it in a way you can understand it :)

thanks, it helped me.
i was trying to upload file using IFormFile as paramter, process it and at the end send back to client. 
during this process, the file uploaded successfully but response was coming with status code 500.
Visual studio thrown that "could not open file '...**undefined**'
After reading you comment, i just removed the file from response and gave a message in string and it return 200 status code.
may this help someone else too.
thanks again

**Comment by layomia** [comment]
The issue here is that the element type StringValues is currently not supported for deserialization as it doesn't have a public parameterless ctor. The serializer would need to implement a new convention where we check for ctors that take a T array (T[]). 

Moving to future as a custom converter can be written to handle this.

**Comment by binnetramesh** [comment]
The best way to resolve this while retrieving [Get] is to use the [JsonIgnore] attribute,

class FileModel
{
    [JsonIgnore]
    public List<IFormFile> file { get; set; }
}

**Comment by eiriktsarpalis** [comment]
> The serializer would need to implement a new convention where we check for ctors that take a T array (T[]). Moving to future as a custom converter can be written to handle this.

Note that `StringValues` exposes a [two constructors](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.stringvalues.-ctor?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Primitives_StringValues__ctor_System_String_). I don't see how we could resolve the inherent ambiguity here (unless we applied a `JsonConstructor` attribute on the definition of `StringValues` itself).

**Comment by krwq** [comment]
Moving to 8.0 as we won't have time to fix this in 7.0 and there seem to be several workarounds for this

**Comment by krwq** [comment]
We're moving this to Microsoft.Extensions.Primitives. We don't believe this is a good converter to add to System.Text.Json. Microsoft.Extensions.Primitives owner should consider adding JsonConverterAttribute on that class and provide converter. Otherwise it's a won't fix.

**Comment by tarekgh** [comment]
@krwq if there is enough demand for this, then it makes sense to provide the converter in `System.Text.Json` like other types supported there. If there is not enough demand for that, the provided workaround should be enough for users. right?

**Comment by eiriktsarpalis** [comment]
Both `System.Text.Json` and the `Microsoft.Extensions.Primitives` libraries target `netstandard2.0`, as such adding STJ support for `StringValues` would one way or another require one type to take dependency on the other. There is always the option of using a built-in converter that targets the type using reflection but that won't work well in source gen scenaria.

As already mentioned in this thread, we don't believe that this scenario is common enough to warrant OOTB support. Suggested workaround is writing a custom converter for `StringValues`.

**Comment by krwq** [comment]
If community is interested in us support this the right approach would be to create API suggestion with new library with JsonConverters and compile list of converters you'd like in there. As is we'd need to take dependency just for this specific type or Microsoft.Extensions.Primitives.StringValues would need extra dependency on us which doesn't seem worth it.
