### ISSUE TITLE
Additional coverage for GetEnvironmentVariable for empty variable

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/runtime#15660]
We should add some more tests around GetEnvironmentVariable when the value of the environment variable is an empty string. 

This is not possible on Windows, but should be possible on other platforms.

**Comment by marcusturewicz** [comment]
I have tried running the following test on OSX, but the `getValue` returned is null rather than the expected empty string. Is this what you were intending?

```csharp
        [Fact]
        [PlatformSpecific(TestPlatforms.AnyUnix)]
        public void VariableWithEmptyValueCanBeSetOnUnix()
        {
            var name = "VariableWithEmptyValueCanBeSetOnUnix";
            var setValue = string.Empty;
            Environment.SetEnvironmentVariable(name, setValue);

            var getValue = Environment.GetEnvironmentVariable(name);

            Assert.Equal(setValue, getValue);
        }
```

**Comment by danmosemsft** [comment]
It's it indeed the case that on macos the empty and undefined values are distinct? If so the API should probably distinguish. (What about Linux?)

**Comment by marcusturewicz** [comment]
Not sure about Linux, but I'm able to set an empty env variable on macos:

<img width="383" alt="Screen Shot 2020-04-13 at 12 10 42 pm" src="https://user-images.githubusercontent.com/24448509/79086566-dff64a00-7d7f-11ea-8dec-e41daf1f6aae.png">

This cannot be set via .NET, as per above test, so is this a bug then?

**Comment by danmosemsft** [comment]
As pointed out above, SetEnvironmentVariable in .NET Core and .NET Framework unfortunately treat empty value as null, which removes the variable. This would be too breaking to change now, I think.
https://github.com/dotnet/runtime/blob/65d5a72c5d13a4d69225a72bb4dcd4e6dce44034/src/libraries/System.Private.CoreLib/src/System/Environment.cs#L189

BTW it does appear that Win32 allows you to create an environment variable with an empty value eg., with `setx foo ""` . The cmd.exe shell doesn't seem to recognize them (`echo %foo%` just gives `%foo%`) but you can see them if you go to the UI to edit environment variables. 

Assuming this cannot be changed now -- then there simply needs to be a test for it -- and I see at least one
https://github.com/dotnet/runtime/blob/110282c71b3f7e1f91ea339953f4a0eba362a62c/src/libraries/System.Runtime.Extensions/tests/System/Environment.SetEnvironmentVariable.cs#L265

If we want to discuss adding support for creating variables with empty values, probably best open a new issue. 

BTw a little related discussion here https://github.com/dotnet/runtime/issues/34446
