### ISSUE TITLE
Add support for calling a varargs constructor through IlGenerator.EmitCall 

### ISSUE THREAD

**Issue by mburbea** [dotnet/runtime#15705]
## Rationale

Emitting code which calls vararg method is good, but emitting code to invoke **vararg constructor** is different tricky (via symbol lookup).

## Proposed API

Goal: Unify emitting of vararg constructor calls with any other vararg method calls

```diff
public partial class System.Reflection.Emit.ILGenerator
{
+ public virtual void EmitCall(OpCode opcode, ConstructorInfo constructorInfo, Type[] optionalParameterTypes);
  public virtual void EmitCall(OpCode opcode, MethodInfo methodInfo, Type[] optionalParameterTypes);
}
```
Context:
  * [ILGenerator methods - apisof.net](https://apisof.net/catalog/System.Reflection.Emit.ILGenerator)
  * [EmitCall on msdn](https://msdn.microsoft.com/en-us/library/system.reflection.emit.ilgenerator.emitcall(v=vs.110).aspx)

## Usage
```c#
public class V {
    public V(__arglist) { /* ... */ }
    public int MyMethod(__arglist) { /* ... */ }
}

// Emitting calls - code snippets
{
    var il = mb.GetIlGenerator();

    // Emitting call to static vararg method
    il.EmitCall(Opcodes.Call, 
                typeof(V).GetMethod("MyMethod", BindingFlags.Public), 
                new[] { typeof(string), typeof(string), typeof(int) } );

    // Emitting call to vararg constructor - today requires MetaData token
    var token = mb.GetConstructorToken(
        typeof(V).GetConstructors()[0], // or other way to get to ConstructorInfo
        new[] { typeof(string),typeof(string), typeof(int) } );
    il.Emit(Opcodes.Call, token.Token);

    // Emitting call to vararg constructor - with the newly proposed API
    il.EmitCall(Opcodes.Call, 
                typeof(V).GetConstructors()[0], // or other way to get to ConstructorInfo
                new[] { typeof(string), typeof(string), typeof(int) } );
}
```

# Original Proposal

Currently, the only way to call a varargs constructor through an `IlGenerator` is through the usage of a symbol, which is weird and poorly documented.
I propose `EmitCall` which is the supported way to call varargs methods should have an overload to take `MethodBase` instead of a `MethodInfo`.

see: http://stackoverflow.com/a/24041217/468672

edit:
I propose adding the following method to the `IlGenerator` base type:

``` csharp
public virtual void EmitCall(OpCode opcode, ConstructorInfo constructor, Type[] optionalParameterTypes);
```

This overload would allow support for calling a `vararg` constructor. 
Consider the following class `V`

``` csharp
public class V
{
       public int Count{get;}
       public V(__arglist)
       {
              this.Count = new ArgIterator(__arglist).GetRemainingCount();
       }
       public static int F(__arglist)
       {
               return new ArgIterator(__arglist).GetRemainingCount();
       }
}
```

To generate a method that calls the static method F, we can do the following:

``` csharp
public void BuildCallFMethod(TypeBuilder tb)
{
      var mb = tb.DefineMethod("CallFMethod", MethodAttributes.Public | MethodAttributes.Static);
      var il = mb.GetIlGenerator();
      il.Emit(OpCodes.Ldstr, "one");
      il.Emit(OpCodes.Ldstr, "two");
      il.Emit(OpCodes.Ldc_I4_3);
      il.EmitCall(Opcodes.Call, typeof(V).GetMethod("F", BindingFlags.Static | BindingFlags.Public), new[]{typeof(string), typeof(string), typeof(int)});
      il.Emit(OpCodes.Ret);
}
```

However, if we wanted to create a type that extended `V`, despite needing to emit a `call` opcode on the constructor, we cannot use `EmitCall` and instead need to look up a symbol. This is asymmetric and is bad api design.

``` csharp
public void BuildCtorForExtenderOfV(TypeBuilder tb, ModuleBuilder mb)
{
      var ctor = tb.DefineConstructor(MethodAttributes.HideBySig | MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName, CallingConventions.HasThis, Type.EmptyTypes);
      var il = ctor.GetIlGenerator();
      var token = mb.GetConstructorToken(typeof(V).GetConstructors()[0], new[]{typeof(string),typeof(string), typeof(int)});
      il.Emit(OpCodes.Ldarg_0);
      il.Emit(OpCodes.Ldstr, "one");
      il.Emit(OpCodes.Ldstr, "two");
      il.Emit(OpCodes.Ldc_I4_3);
      il.Emit(Opcodes.Call, token.Token);
      il.Emit(OpCodes.Ret);
}
```

Instead, I propose we allow this overload, allowing the two calls to have the same IlGenerator code pattern. The benefit is that `EmitCall`, does some validation beforehand, where as the token variant basically only validates when you build the method/ctor.

As an additional benefit, I also recommend we allow using the `OpCode.NewObj` for the first parameter of `EmitCall` as well.

**Comment by SingleAccretion** [comment]
> I take it this issue is no longer valid?

For anyone who happens to stumble on this issues next: varargs are now supported, but only on Windows.
