### ISSUE TITLE
JsonElement and JsonDocument should be deserializable from JSON payloads

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#1573]
This works for `JsonElement` today:

```C#
var element = JsonSerializer.Deserialize<JsonElement>("{\"data\": 12}");
Console.WriteLine(element);
```

but fails for `JsonDocument`:

```C#
var document = JsonSerializer.Deserialize<JsonDocument>("{\"data\": 12}");
Console.WriteLine(document);
```

> **System.NotSupportedException**: 'Deserialization of reference types without parameterless constructor is not supported. Type 'System.Text.Json.JsonDocument''

Equally, `Serialize` should also work for both, but only works for `JsonElement`.

/cc @steveharter

**Comment by marcusturewicz** [comment]
I'd like to take this one. Any guidance or things to be aware of?
