### ISSUE TITLE
Synchronous deserialize and serialize to a stream with JsonSerializer.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/runtime#1574]
We have a serializer interface (https://github.com/FoundatioFx/Foundatio/blob/master/src/Foundatio/Serializer/ISerializer.cs#L6-L9) which takes a stream as the input and we have extensions that work from it. In our use cases the payloads are usually very small and fit inside normal buffer lengths. Now I totally understand async io and the benefits but we use in memory streams for our serialization and we don't want to do async serialization as it totally kills performance and really complicates some scenarios (esp in messaging handlers at scale). Can you add overloads for this? It would make  it a little bit easier for this use case?

I propose that we add overloads to both `System.Text.Json.JsonSerializer.Serialize` and `System.Text.Json.JsonSerializer.Deserialize` that take streams. As @ahsonkhan provided the following code which sums up what needs to happen signature wise.

```cs
public static partial class JsonSerializer
{
    // Existing APIs:
    public static ValueTask<object> DeserializeAsync(Stream utf8Json, 
        Type returnType, 
        JsonSerializerOptions options = null, 
        CancellationToken cancellationToken = default);
    
    public static ValueTask<TValue> DeserializeAsync<TValue>(Stream utf8Json,
        JsonSerializerOptions options = null,
        CancellationToken cancellationToken = default);

    public static Task SerializeAsync(Stream utf8Json, 
        object value, 
        Type inputType, 
        JsonSerializerOptions options = null, 
        CancellationToken cancellationToken = default);
    
    public static Task SerializeAsync<TValue>(Stream utf8Json, 
        TValue value, 
        JsonSerializerOptions options = null, 
        CancellationToken cancellationToken = default);

    // Proposal to add following synchronous APIs:
    public static object Deserialize(Stream utf8Json, 
        Type returnType, 
        JsonSerializerOptions options = null);
    
    public static TValue Deserialize<TValue>(Stream utf8Json,
        JsonSerializerOptions options = null);

    public static void Serialize(Stream utf8Json, 
        object value, 
        Type inputType, 
        JsonSerializerOptions options = null);
    
    public static void Serialize<TValue>(Stream utf8Json, 
        TValue value, 
        JsonSerializerOptions options = null);
}
```

**Edit by @ahsonkhan:** Just modified some indentation/spacing so the API surface aligns better.

**Comment by ahsonkhan** [comment]
@niemyjski - were you able to find benchmarks that showcased performance regressions when doing async serialization compared to sync only (preferable ones that are reproducible/isolated)?

**Comment by ahsonkhan** [comment]
From @CodeBlanch in https://github.com/dotnet/runtime/issues/31669:

> # Proposed API
> The current System.Text.Json API supports these two methods:
> 
> ```cs
> Task SerializeAsync<TValue>(Stream utf8Json, TValue value, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default);
> Task SerializeAsync(Stream utf8Json, object? value, Type inputType, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default);
> ```
> 
> I'm proposing we add:
> 
> ```cs
> void Serialize<TValue>(Stream utf8Json, TValue value, JsonSerializerOptions? options = null);
> void Serialize(Stream utf8Json, object? value, Type inputType, JsonSerializerOptions? options = null);
> ```
> 
> Which are basically overloads for synchronized writing to a Stream.
> 
> # Rationale & Usage
> I have a logging library that maintains its own dedicated thread for pumping messages to a file via FileStream. The current API does not provide an efficient way to handle this.
> 
> Using the existing async API:
> 
> ```cs
> 		private void DrainMessagesThreadBody()
> 		{
> 			Stream LogFile = _LogFileManager.FindCurrentLogFile();
> 
> 			while (true)
> 			{
> 				if (!_Messages.TryDequeue(out Message Message))
> 					break;
> 
> 				SerializeMessageToJson(LogFile, Message).GetAwaiter().GetResult();
> 			}
> 		}
> 
> 		private async Task SerializeMessageToJson(Stream stream, Message message)
> 		{
> 			await JsonSerializer.SerializeAsync(stream, message, _JsonOptions).ConfigureAwait(false);
> 
> 			await stream.WriteAsync(s_NewLine, 0, s_NewLine.Length).ConfigureAwait(false);
> 
> 			await stream.FlushAsync().ConfigureAwait(false);
> 		}
> ```
> 
> This is the "Sync over Async" anti-pattern. There is a dedicated thread but it has to use the pool to do its work.
> 
> Using the existing sync API:
> 
> ```cs
> 		private void DrainMessagesThreadBody()
> 		{
> 			Stream LogFile = _LogFileManager.FindCurrentLogFile();
> 
> 			while (true)
> 			{
> 				if (!_Messages.TryDequeue(out Message Message))
> 					break;
> 
> 				SerializeMessageToJson(LogFile, Message);
> 			}
> 		}
> 
> 		private void SerializeMessageToJson(Stream stream, Message message)
> 		{
> 			BufferWriter BufferWriter = new BufferWriter();
> 			using (Utf8JsonWriter Writer = new Utf8JsonWriter(BufferWriter))
> 			{
> 				JsonSerializer.Serialize(Writer, message, _JsonOptions);
> 			}
> 			BufferWriterr.WriteToStream(stream);
> 			stream.Write(s_NewLine, 0, s_NewLine.Length);
> 			stream.Flush();
> 		}
> ```
> 
> Works fine, but the problem is `BufferWriter` doesn't exist. I had to roll that based on the System.Text.Json `PooledByteBufferWriter`, which is internal. That is a lot of heavy lifting in order to make the usage efficent via buffer reuse. What I really wanted to do is reuse the pooling buffer code already in the lib (used by SerializeAsync calls).
> 
> Here's how it would look using the proposed API:
> 
> ```cs
> 		private void DrainMessagesThreadBody()
> 		{
> 			Stream LogFile = _LogFileManager.FindCurrentLogFile();
> 
> 			while (true)
> 			{
> 				if (!_Messages.TryDequeue(out Message Message))
> 					break;
> 
> 				SerializeMessageToJson(LogFile, Message);
> 			}
> 		}
> 
> 		private void SerializeMessageToJson(Stream stream, Message message)
> 		{
> 			JsonSerializer.Serialize(stream, message, _JsonOptions);
> 			stream.Write(s_NewLine, 0, s_NewLine.Length);
> 			stream.Flush();
> 		}
> ```
> 
> With the new API caller doesn't need to worry about correct usage (buffer pooling), it just happens under the hood as it does with SerializeAsync calls.

**Comment by niemyjski** [comment]
@ahsonkhan I was not able to find the benchmarks when I looked :\. I thought I wrote them down for release notes but I must have lost them when my mac mother board went...

**Comment by Mpdreamz** [comment]
Has this API change been accepted? Noticed it was put in the `5.0` milestone, looking to confirm. Performance reasons aside it would be great to have these overloads ship out of the box for method signature parity reasons.

**Comment by steveharter** [comment]
The workaround is to manually convert to\from byte[]. For deserialize:
```cs
ReadOnlySpan<byte> utf8Json = DrainStream(stream); // DrainStream manages the buffer allocation(s) and pooling
Poco poco = JsonSerializer.Deserialize<Poco>(utf8Json);    
```
and for serialize:
```cs
byte[] utf8Json = JsonSerializer.SerializeToUtf8Bytes(poco);
stream.Write(uf8Json.AsSpan());
```

Besides avoiding having to implement "DrainStream()", the main benefit of having `JsonSerializer.Deserialize(stream)` do this is that the serializer, as it also does for the DeserializeAsync(), doesn't drain the Stream upfront and thus minimizes the buffer size - it would do this by calling `stream.Read()` in manageable chunks (~16K each time by default) while deserializing a graph. The same also applies to `JsonSerializer.Serialize(stream, value)` where `stream.Write()` is called multiple times to minimize the buffer size.

However, given the original description of small payloads, the workaround is probably sufficient for that scenario. In any case, the API request is valid and avoids large buffer issues and having to implement "DrainStream()".

**Comment by bartonjs** [comment]
Adding synchronous method parity sounds good.

```C#
namespace System.Text.Json
{
    partial class JsonSerializer
    {
        // Proposal to add following synchronous APIs:
        public static object Deserialize(Stream utf8Json, 
            Type returnType, 
            JsonSerializerOptions options = null);
        
        public static TValue Deserialize<TValue>(Stream utf8Json,
            JsonSerializerOptions options = null);
    
        public static void Serialize(Stream utf8Json, 
            object value, 
            Type inputType, 
            JsonSerializerOptions options = null);
        
        public static void Serialize<TValue>(Stream utf8Json, 
            TValue value, 
            JsonSerializerOptions options = null);
    }
}
```

Also add the overloads for the new `JsonTypeInfo<T>` versions from the source generator.
