### ISSUE TITLE
Missing CFB cipher mode

### ISSUE THREAD

**Issue by lextm** [dotnet/runtime#15771]
Currently only three modes are supported by .NET Core,  (CBC = 1, CTS = 5, ECB = 2). Is there any plan to add CFB support as it has been required by some network protocols (such as SNMP v3)? This mode is available on .NET Framework though.

From where does the limitation of three modes come? The comment in `CipherMode` does not reveal enough background information.

https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CipherMode.cs

**Comment by nechvatalp** [comment]
I also need this for usage of SNMPv3. Hope it gets done in 5.0.
