### ISSUE TITLE
HTTP2: optimize HPACK decoding.

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#1578]
Our HPACK decoder looks like it can be improved. We should write some benchmarks and see if any optimizations can be made.

**Comment by JamesNK** [comment]
HPack decoding shows up when profiling HTTP/2 Kestrel. I think this is a place to optimize and get gains on the client and server.

Here is the decoder today - https://github.com/dotnet/runtime/blob/b2eaf5c60a99e0527c232a99fec2da6fd8fde8c9/src/libraries/Common/src/System/Net/Http/aspnetcore/Http2/Hpack/HPackDecoder.cs

It looks like it is designed to be stateful and parse a byte at a time. Do we need that capability? Checking the state of every new byte is inefficient. Perf could be improved by looking at the first byte of a header, then branching into a specialized method for parsing the incoming data.

Both Kestrel and SocketsHttpHandler process frame bytes once the whole HEADER/CONTINUATION frame is available. The only reason I can think for keeping state is if an individual header can span frames. Kestrel doesn't support headers than are bigger than a frame, but I'm not certain whether this is a requirement, or done to simplify implementation.

@halter73 @Tratcher

**Comment by Tratcher** [comment]
> Kestrel doesn't support _writing_ headers that are bigger than a frame, but I'm not certain whether this is because of a requirement in a spec, or done to simplify implementation.

I'm pretty sure it was an implementation choice rather than a spec limitation.

Re-writing it to not use state machines would probably be a lot easier to understand as well.

**Comment by halter73** [comment]
Headers being limited by the max frame size is a spec limitation. There's no way for a HEADER/CONTINUATION frame to indicate that it's a partial header. I found a [draft proposal](https://tools.ietf.org/html/draft-johndoe-http2-large-header-blocks-00) for "large header blocks". I don't think the proposal ever got anywhere, but it was pretty clear about its motivation:

```
   The Hypertext Transfer Protocol version 2 (HTTP/2 [http2]) introduced
   a framing-based transport layer with multi-stream multiplexing.
   HTTP/2 also introduced header compression.  However, HTTP/2 header
   blocks are restricted to the size of the payload of a single frame
   (currently 16383 bytes).
```

https://tools.ietf.org/html/draft-johndoe-http2-large-header-blocks-00#section-1

**Comment by Tratcher** [comment]
A header block in that context is all headers, not a single header. Continuation frames are part of the main spec now, I'm not sure why that draft treats them otherwise unless it was incorporated later?

**Comment by Tratcher** [comment]
https://tools.ietf.org/html/rfc7540#section-4.3

A receiving endpoint reassembles the header block by concatenating
   its fragments and then decompresses the block to reconstruct the
   header list.

**Comment by JamesNK** [comment]
So we're all onboard with the same terminology:

* Header field = name + value
* Header list = all the fields in the headers or trailers
* Header block = serialized form of header list
* Header block fragment = header block divided up so it fits in maximum frame size

The question is can a header field span across header block fragments? I haven't seen it answered in the spec definitively one way or the spec.

**Comment by scalablecory** [comment]
> The question is can a header field span across header block fragments? I haven't seen it answered in the spec definitively one way or the spec.

Headers can cross fragments. HttpClient supports this today, Kestrel does not.

**Comment by JamesNK** [comment]
Gotcha. I've been looking at Java and Go and they both support support fields across multiple fragments.

Different options for improvements:

* Improve the current state machine approach so it has less impact
* If there are CONTINUATION frames then read the HEADERS plus CONTINUATION frames data into a data source until we get the end bit, and then parse all at once. No state machine required.
* Have the hpack decoder take control of reading for the incoming stream (this is what Java does). For us this would mix async and parsing code, and we'd also need another abstraction to support Kestrel's PipeReader and SocketHttpHandler's Stream. Don't like this.

Thoughts? Additional suggestions?

**Comment by scalablecory** [comment]
Ultimately this is a Try It And See, but where I'd start is:

- Replace the big `if((x & maska) == maskb)` chain with a `switch(BitOperations.LeadingZeroCount(x))`, similar to what I did in the HTTP/3 QPackDecoder.
- Optimistically decode entire integers, not 1 byte at a time through main loop.
- Optimistically copy entire string values, not 1 byte at a time through main loop.

These should be relatively easy changes and wouldn't need any modifications to the API signature or to the state machine.

If that doesn't get us where we want to be, or we'd like to go further to the point of removing state or changing API:

My preference would be to keep it as parsing a `Span`, but I can see arguments for using `ReadOnlySequence`. `ROS`'s allocatey nature would complicate `HttpClient`'s buffering implementation though, so I would avoid it for now unless prototyping shows a good win. I would generally not want it doing I/O in the parse method.

The size of the state machine could be scaled back (all the way down to zero). The more we reduce it in size, the less optimized we will be for extra-large header values (maybe cookies?). HttpClient could probably be fine with that, but I don't know if that makes sense for Kestrel.

**Comment by JamesNK** [comment]
I agree that we should keep parsing a Span. Using a ROS would pollute low-level parsing logic with having to consider multiple spans in a sequence everywhere.

My suggestion for 3 doesn't work well in Kestrel because the payload is in a ROS, and we don't want to start copying it to a contigious buffer each time the headers frame is not a single span.

In consideration, I think option 1 and improving what we have are probably the best option.

**Comment by scalablecory** [comment]
> Using a ROS would pollute low-level parsing logic with having to consider multiple spans in a sequence everywhere.

My hope is we eventually get a `ref struct` generic constraint so we can have our cake and eat it too... write parser once, works for both `SpanReader` and `SequenceReader`, etc.

**Comment by Tratcher** [comment]
Yeah, trying to make incremental improvements to the state machine seems like a good place to start.

**Comment by JamesNK** [comment]
Can this issue be closed?

Huffman decoding hasn't been touched, but it has its own issue - https://github.com/dotnet/runtime/issues/1506

**Comment by scalablecory** [comment]
Yep, lets close this until we get something more actionable. Thanks for your PR.
