### ISSUE TITLE
HttpStress: Automate stress runs

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#1579]
Forking from conversation started in dotnet/corefx#41069 per @ViktorHofer's request.

We keep a [standalone console app](https://github.com/dotnet/corefx/tree/master/src/System.Net.Http/tests/StressTests/HttpStress) in the corefx repo which stress tests using the existing sdk. Currently, we run this by manually building corefx and running the suite against compiled bits. We're looking for a way to trigger this automatically against PR branches, ideally using an `/azp` subcommand.

Things to consider:

* Should probably support multiple OSes (e.g. Windows, Linux & OSX).
* Should be allowed to run for arbitrary amounts of time.
* Manual auditing of stress run logs (as opposed to automatically passing or failing runs).
* More long-term, we should probably consider hosting client and server in separate VMs for a variety of reasons.
* Want to use the httpstress as a pilot project for adding additional networking stress/performance tests. We're also looking at [aspnet/benchmarks](https://github.com/aspnet/benchmarks) for ideas here.
* Should stress/performance projects live in the corefx repo? We already have the [performance](https://github.com/dotnet/performance) repo for hosting microbenchmarks, so wondering if it makes sense to do something similar with networking.

I should note that @jkotalik has created an Azure pipeline that [just runs the stress suite](https://dnceng.visualstudio.com/public/_build?definitionId=560&_a=summary). I'd argue for the sake of simplicity that we should probably do just that and iterate as necessary.

**Comment by karelz** [comment]
We already can trigger it via `/azp`.
