### ISSUE TITLE
Indexer for SortedSet 

### ISSUE THREAD

**Issue by hickford** [dotnet/runtime#15802]
```
var set = new SortedSet<double>();
set.Add(5.6);
set.Add(2.1);
set.Add(3.4);
var x = set[1]; 
Assert.AreEqual(3.4, x);

CS0021 Cannot apply indexing with [] to an expression of type 'SortedSet<double>'
```

It would be useful if SortedSet had an indexer for random access. Would this be possible? Reading the code I see SortedSet is implemented using a red-black tree.

Also useful would be an IndexOf method. 

https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs

**Comment by artkpv** [comment]
Recently it was dissappointment that SortedSet or SortedDictionary doesn't have O(log(n)) index. ElementAt() works in O(N). So this is in 5.0 milestone? How hard is it to add this now? As I see there is some API review process. Does supporting size / count in `SortedSet<T>.Node` entails some underwater issues?

**Comment by eiriktsarpalis** [comment]
I'm assuming that tracking counts on tree nodes adds O(log(n)) complexity on each update, right? Asymptotically that shouldn't have an impact but presumably it would make sense to measure whether it has noticeable impact on benchmarks.

**Comment by NiPersson** [comment]
Looking forward to these features being added. Would be really useful for my work.
