### ISSUE TITLE
Escaping quotes - portable way

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#15812]
How do you escape quotes the portable way when using Process with UseShellExecute and Arguments?

EDIT:
UseShellExecute:

```
System.PlatformNotSupportedException:  UseShellExecute must always be set to false.
   at System.Diagnostics.ProcessStartInfo.set_UseShellExecute(Boolean value)
```

Process could perhaps have an option of taking string[] to match Main and be able roundtrip

**Comment by stephentoub** [comment]
Closing as dup.
