### ISSUE TITLE
Synchronize HTTP/2 Framing and HPACK code with ASP.NET Core

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#1584]
**Things to share:**
- HPACK (Encoding/Decoding), These are similar today, so it should be a simple unification
- Framing code, different representations/organization, but not a lot of code.

Primary is corefx, with ASP.NET Core as secondary. This means all changes to shared code should start in corefx and merged up to ASP.NET Core. We also have a script for inner loop development to test against each repo as well as potentially a unit test to verify shared source is up to date.

The hardest part of this change will be creating a bot to copy source from corefx to aspnetcore. This needs to work on each branch from 3.0 up. Hypothetically this is a simple bot:
check if a subfolder in corefx has a new commit/new commits in it. If it does, checkout aspnetcore and copy the contents. @mmitche can we sync about this?

**Actionable items:**
- [x] Synchronize aspnetcore and corefx HPACK implementation (still need a reaction PR in AspNetCore)
- [x] Readme
- [x] Inner loop copy script (both directions)
- [x] Move more unit tests from ASP.NET Core to corefx 
- [x] Create github group/ code owners to make sure all stakeholders are added to PRs
- [x] Update script paths after the corefx repo merger/restructure.
- [x] Create a bot to sync code from corefx to aspnetcore.
- [x] Validation/verification to make sure code is "in sync" 
- [ ] How to share resource strings across assemblies? We got this working in AspNetCore but not CoreFx.

**Open questions:**
- Copyrights
- Namespaces
- Resource strings

cc @Tratcher @scalablecory

**Comment by Tratcher** [comment]
I have a proposal and demo for the automation:

I've created a Github Action in AspNetCore that I'll schedule to run once per day. The action will:
1. Checkout the master branch of the runtime and aspnetcore repos.
1. Run the existing CopyToAspNetCore.cmd script
1. Diff to see if that caused any changes in AspNetCore
1. If yes, export the diff as an artifact and notify us 

Here's a demo with steps 1-3 working:
https://github.com/Tratcher/aspnetcore/runs/432661335?check_suite_focus=true
Here's the script:
https://github.com/Tratcher/aspnetcore/actions/runs/36033734/workflow

We'll need to decide what kind of notification is appropriate.
A. Fail the Action which will automatically notify people based on their github settings. The docs are vague on just who would be notified. Repo owners? Committers? Subscribers? Regardless this will likely be too many people unrelated to the h2/3 projects.
B. Open an issue or ping an existing one?
C. Open a PR? I don't recommend this for two reasons: A) many changes to shared code will require reactions in the other repo. B) This script does not prove which repo is out of date, only that they are different, and so it doesn't know if it needs to open a PR in runtime or aspnetcore (or both).
D. Email a list of people? There are a few [existing](https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=email) Actions for that.

Once notified we'll assign someone to follow up and resolve the diff. That leans towards using (B) an issue as the notification mechanism.
