### ISSUE TITLE
HTTP2: Inbound flow control - default settings vs. adaptive algorithm

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#1587]
[EDIT] We need to decide if we want to expose just default setting, or if we want to do something fancier (adaptive algorithm) and how it would interact with such setting (or we can skip the setting).

HTTP2 allows us to define our window size using the SETTINGS_INITIAL_WINDOW_SIZE setting. The default is 64K.
Currently we simply always use the default. Should we expose a setting to control this?
Note that this setting would basically control the receive buffer size for a response body. 
Flow control is managed both per-stream and per-connection, but the interesting case here is per-stream.

Merged with issue dotnet/corefx#35388:
[EDIT] Pipelines has some logic already to reach an optimal receive window -- should we leverage that?

Currently, our stream-level response window is 64K (the default). This is probably too small for many scenarios, and will end up stalling the server as it sends response data.
We should increase this, but it's not clear what the right amount is. Further perf investigation is needed here.
As part of this, we should probably switch our response buffering strategy from using a single array buffer to using linked buffers that are allocated from the pool.

**Comment by antonfirsov** [comment]
Fixed in #54755.
