### ISSUE TITLE
Investigate adding common Linux crypto algorithms

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#15936]
Most of the crypto algorithms that .NET supports on Windows are now included in CoreFX. However, there are a number of algorithms in common use on Linux that .NET doesn't support. We should investigate if there are some from that set that we should support for better integration with other Linux components. That would include assessing the current security of the algorithms. This would likely also require finding a way to have them work on Windows (and other OSes). Some possibilities include:
- BCrypt hash algorithm
- Blowfish (possibly only for BCrypt)
- TwoFish
- ThreeFish
- GPG

**Comment by MythreyaK** [comment]
Is this something a beginner can handle?

**Comment by bartonjs** [comment]
> Is this something a beginner can handle?

Not fully. We're currently limited (by various policies) to only using system-provided cryptography; so there's no way to do any of these algorithms on Windows (unless Windows has added some new algorithm support that we've missed), and we don't really like adding new things that don't work on all of our main console app OSes (Windows, macOS, various Linux distros)... though we do it from time to time.

Doing type modelling for the algorithms is reasonable, but until we also figure out a release mechanism it's hard to justify the work.

**Comment by MythreyaK** [comment]
Thanks for the info!

**Comment by bartonjs** [comment]
While the thrust of this does align with being more Linux-friendly, we'd need individual issues for individual algorithms and those to also, ideally, come up with individual API proposals.

I don't think anyone has ever mentioned any of the fish algorithms outside this issue; BCrypt might make the cut if there was enough demand (even if it'd have to have an `IsSupported => false` on Windows).  GPG/PGP/RFC-4880 feels more like EnvelopedCms/SignedCms than an algorithm, so it'd also be doable... if we had enough demand for it.

**Comment by lonix1** [comment]
Since this has been closed I'd like to mention that some of the newer algorithms mentioned - **especially bcrypt** - are very common, and it has nothing to do with linux.

Also for future readers, given this won't be built-in, just use [BouncyCastle](https://www.nuget.org/packages/BouncyCastle/).
