### ISSUE TITLE
RegEx unable to parse "(\d)(?(1)yes|no)(\d)(\2)"

### ISSUE THREAD

**Issue by pgovind** [dotnet/runtime#1595]
Pattern: @"(\d)(?(1)yes|no)(\d)(\2)"
Input: "0yes11"
Current Match: "0yes"
Correct Match: "0yes11"

I found this while reading through our `CountCaptures()` routine. The bug is that we set  `_ignoreNextParens` to `true` when we parse an alternation construct and never set it back to `false`. As a result, we don't detect any subsequent captures.

**Comment by pgovind** [comment]
Up for grabs if somebody wants it. Otherwise, I'll pick it up the next time I go through here.

**Comment by hannan-m** [comment]
Which version of the Dotnet core are you using? I just test tested with the same regex and input on .Net core 3.1 and it worked as expected.

![Annotation 2020-01-20 204542](https://user-images.githubusercontent.com/55412422/72739690-fa2bec00-3bc5-11ea-8036-43eda0a7c2d2.png)

**Comment by pgovind** [comment]
Interesting. I tested this on Regexstorm.net when I repro'd the bug. It seems to be working now. It could be that the new changes that went into the RegEx library fixed this. I'll review the code here and close this once I figure out why/how this was fixed.

**Comment by pgovind** [comment]
This actually works fine. `_ignoreNextParens` is being set to false in the next iteration. Closing this.
