### ISSUE TITLE
Documentation needed on System.Collections.Immutable (what exist is seriously lacking)

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#16012]
The documentation for how to use System.Collections.Immutable is the worst I have seen of any general microsoft libraries. No general introduction and very few examples. + Most stuff that google can find on the net is outdated and may no longer work. I need quite some detective work just to find out how to instantiate an instance of an immutable list with specific values, how to convert a IEnumerable etc.

**Comment by eiriktsarpalis** [comment]
Triage: Closing as it looks like the issue has been addressed with #18186
