### ISSUE TITLE
Design initialization API for Vector<T> that supports padding

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#16094]
The size of `Vector<T>` is hardware dependent. When constructing a vector, we either accept the value coming from an array or a raw pointer. However, the number of elements being read is always `Vector<T>.Length`.

In many cases, the number of inputs to be processed is extrinsically defined and might not be a multiplier of `Vector<T>.Length`, i.e. it's likely that there is a remainder.

It might be beneficial to support constructing a vector and if there are fewer values than `Vector<T>.Length` we pad with, for instance, zeroes.

@mellinoe @CarolEidt

**Comment by tannergooding** [comment]
Going to close this for now as it hasn't garnered much attention and is more readily handled on the user side now that we have constructors taking in `Span<T>`.
Much of the discussion has also centered around `Vector<T>` growing in size in the future and how to best handle that, which will need a bit more thought/design.

If someone feels strongly about this, please feel free to open a new issue. Our API review process is detailed here with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.
