### ISSUE TITLE
Improve full platform manifest generation implementation (harvesting approach)

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1616]
The PR to re-enable full platform manifest harvesting in dotnet/runtime (https://github.com/dotnet/runtime/pull/1594) has some known bad bits. It didn't seem worth it to me to fix them in the harvesting implementation, because I believe we need to replace the harvesting approach altogether for source-build.

The list:

* It downloads a decent amount more data during the build. This hasn't added more than 3 or so minutes in my testing builds, but could be a problem at some point.
  * @safern suggested piecing together the platform manifest data during the CoreCLR and Libraries builds and transferring that rather than the entire set of artifacts, to reduce size: https://github.com/dotnet/runtime/pull/1594#issuecomment-572884435
* There's a redundant download: each Installer job downloads one of the platform's artifacts twice. Once to use to create the runtime being built on that machine, again *specifically* for platform manifest harvesting.
* The full manifest infra isn't tested in PR validation. The main runtime pipeline doesn't currently include all the platforms necessary to assemble a full platform manifest.
* It adds 21 build steps to each installer job. 1 to download all the artifacts, 20 to extract each artifact using the built-in unzip step while preserving folder names.
* It is difficult to run locally. You have to download every artifact manually, unzip/untargz them, and arrange them properly. (Let alone trying to run every local build yourself on a bunch of your own machines!)
* The RID => Platform mapping is hard to read. It seems like items would be significantly clearer: https://github.com/dotnet/runtime/pull/1594#discussion_r365371744
  * https://github.com/dotnet/runtime/blob/a773bc3b315f6284f568f20f221b396f7390033c/eng/liveBuilds.targets#L30-L37

**Comment by ViktorHofer** [comment]
@jkoritzinsky can you please give an update on this issue / close it with your SharedFramework SDK work?

**Comment by safern** [comment]
> @jkoritzinsky can you please give an update on this issue / close it with your SharedFramework SDK work?

@jkoritzinsky I assigned to you given the SharedFramework SDK. Please remove the assignment if this won't be fixed with that work.

**Comment by jkoritzinsky** [comment]
This will be fixed by adopting the new shared framework SDK.
