### ISSUE TITLE
Framework Design Guidelines Updates to Consider

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/runtime#16182]
This list represents some guidelines that we often run into and feel like they should be updated:
- [ ] Event design guidelines (should we use Func/Action? do we need sender, etc.)
- [ ] Async pattern (task based async, cancellations)
- [ ] Default parameters
- [ ] Exceptions
- [ ] Nested types

**Comment by ericstj** [comment]
Framework design guidelines are not part of this repository and I don't think we should be tracking them with issues here.  Perhaps dotnet/core or dotnet/designs.
