### ISSUE TITLE
Proposal for minimalistic imaging platform

### ISSUE THREAD

**Issue by dajuric** [dotnet/runtime#16307]
## Proposal for minimalistic imaging platform

.NET does not provide a truly portable image format nor portable image IO operations. 
For example System.Drawing.Bitmap nor WPF's BitmapSource and does not provide generic interface which imposes compile-time constraints. EmguCV's generic image provides the generic interface but is heavily coupled with OpenCV. 

All mentioned image types do not provide a unified interoperability needed when mixing image-processing algorithms from different libraries.
### Goals:
- [ ] to create a portable module for image reading/writing
- [x] to create a portable, slim image format such as [DotImaging](https://github.com/dajuric/dot-imaging) has (native array Bgr&lt;byte&gt;[,])
- [x] to create system drawing primitives - such as in [DotImaging.Primitives2D](https://www.nuget.org/packages/DotImaging.Primitives2D/)
- [ ] _optionally to create portable video reading and web-camera access module_
### Proposal

To leverage existing structure and components of [DotImaging](https://github.com/dajuric/dot-imaging) framework, but to replace the backing OpenCV part needed for image IO.
The first step would be to create a portable image reading/writing module with the most simplistic API (e.g. ImageIO.LoadColor(), LoadGray()...).  
Options:
- a wrapper arround LibGD (@ dotnet/runtime#14706)
- trim down and reuse the existing platform specific module of: [Eto.Forms](https://github.com/picoe/Eto) - includes drawing capabilities as well, or [Splat](https://github.com/paulcbetts/splat).
### Related issues

[Proposal for Cross-plat Server-side Image Manipulation Library](https://github.com/dotnet/corefx/issues/2020) - proposal of much broader scale - this proposal resolves the core issue and levaes out separates image processing part  managed by other libraries [Accord.NET](http://accord-framework.net/), [Accord.NET Extensions](https://github.com/dajuric/accord-net-extensions), [EmguCV](http://www.emgu.com/wiki/index.php/Main_Page).

[.NET core should have primitive drawing types](https://github.com/dotnet/corefx/issues/1563) - already done in [DotImaging.Primitives2D](https://www.nuget.org/packages/DotImaging.Primitives2D/)

**Comment by JeremyKuhne** [comment]
As System.Drawing.Common is a GDI/GDI+ wrapper and only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now, this feature request is out of scope. Please see our [recommendations](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) for other libraries to consider.
