### ISSUE TITLE
[SRM] Mark assembly as [CLSCompliant(true)] and mark individual APIs as [CLSCompliant(false)]

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#16355]
Some APIs use pointers (e.g. MetadataReader constructor). Provide an alternative CLS compliant API. Such APIs could also improve usability in C# when the caller has byte[] or ImmutableArray<byte> and no interest in dealing with pointers.

**Comment by charlesroddie** [comment]
If CLScompliance annotations were just deleted in dotnet5, would any .Net language be affected? For example a language that hasn't been updated for 15 years: could it still reference dotnet5 assemblies and make use of the CLSCompliant parts?

> https://github.com/dotnet/fsharp/issues/634#issuecomment-141498603
> the "CLS" (Common Language Subset) doesn't seem to be an active, working specification effective at arranging cross-language interop beyond the basics since at least C# 3.0.

Assuming that it is irrelevant in modern .Net, it's confusing to users to see CLScompliance messages in docs such as 
> https://docs.microsoft.com/en-us/dotnet/api/system.math.clamp?view=netcore-3.1
> Important This API is not CLS-compliant.

**Comment by ericstj** [comment]
@charlesroddie please open a different issue if you wish to discuss CLSCompliant and docs.  This issue is referring to the use of array vs pointers only in the System.Reflection.Metadata APIs.

@tmat did you want to make an API suggestion here or do you think this scenario is now covered in our current API?

**Comment by steveharter** [comment]
Closing; doesn't seem actionable any longer.
