### ISSUE TITLE
Win32 FileStream will issue a seek on every ReadAsync call

### ISSUE THREAD

**Issue by ayende** [dotnet/runtime#16354]
Full description is here:
https://ayende.com/blog/173345/the-cost-of-async-i-o?key=227b21e219594be48ca03bc8312b08b9

But the gist of it is that we are trying to call ReadAsync on a file that is located on a remote share.
Using ReadAsync, we saw a really horrible performance degradation. 

We tracked it down to this issue:

![image](https://cloud.githubusercontent.com/assets/116915/12979633/159bc0ae-d0e1-11e5-85f8-ba055fa313fb.png)

And here is the problematic code:
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/Win32FileStream.cs#L1201

Given that all async calls are always passing the position they use in the overlap, and how expensive this call is, it make for a very bad combination.

**Comment by adamsitnik** [comment]
Another problem with `seek` and `read` is that it's not a single operation, so it's not atomic (and not thread-safe).

An excellent read for Linux: https://learning.oreilly.com/library/view/The+Linux+Programming+Interface/9781593272203/xhtml/ch05.xhtml#ch05lev1sec06

I am going to try to figure a way to use `pread`  instead (and find a similar solution for Windows implementation)

**Comment by stephentoub** [comment]
> it's not a single operation, so it's not atomic

Why is that a problem?

**Comment by adamsitnik** [comment]
> Why is that a problem?

We perform the extra seek to verify that nobody else has changed the file offset in the meantime (because we want to throw in such situations). Despite doing it and paying the perf price for it we can still miss the situation when it got modified after the call to seek and before the call to read?

**Comment by stephentoub** [comment]
> because we want to throw in such situation

Personally,  I think this existing attempt at protection is inherently flawed in purpose. The implementation doesn't try to make it work, but rather simply tries to detect misuse, and as you say,  such protection is broken, anyway.  Maybe I'm misunderstanding the suggestion,  but switching to pread suggests to me you're not just trying to be more accurate in the misuse detection,  but actually aim to make the scenario work (rather than detect misuse). I don't think that needs to be a goal; personally I think we can just delete the flawed attempt at protection. What did you have in mind for pread?

**Comment by ayende** [comment]
It is allowed to have multiple concurrent `ReadAsync` ?

On `Unix`, it looks like there is a semaphore for it:

https://github.com/dotnet/runtime/blob/c7fda3b94a50297e6ece9db4ddc79ed039394dd3/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L523-L530

So that will ensure that the position is changed in step. That make me think that on Linux, you can just drop this (assuming that the semaphore applies to write as well).

But on Windows, there is this comment that is interesting:

https://github.com/dotnet/runtime/blob/c7fda3b94a50297e6ece9db4ddc79ed039394dd3/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Windows.cs#L879-L883

Seems to indicate that the position may change unexpected with writes.
However, this is already handled because you are using overlapped I/O.

It looks like the `Seek` is there because it wants to set the position for the _next_ call. But all the calls on the FileStream are actually using the overlapped, no? So the scenario in question is trying to keep it in sync for someone who passed a handle and is also using that in conjunction with async reads?

Seems far fetched.

**Comment by adamsitnik** [comment]
Fixed by #49975, please expect a blog post with all the details and perf numbers in April (before we ship preview 4)
