### ISSUE TITLE
Expose cancellation due to exceptions and breaking with Parallel loops

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#16372]
The `Parallel` loops break when an exception is thrown or when the loop is aborted using `ParallelLoopState` members.

When that happens the existing work items that are still executing have no (built-in) way to find out. They cannot cancel themselves to speed up the failure/exit case.

`ParallelLoopState` should expose a `CancellationToken` that becomes signaled when the loop aborts for any reason.

There is a workaround for this available: Users can catch all exceptions, signal a custom token, then `throw;`. It would be nicer and possibly faster if this was built-in, though.

**Comment by stephentoub** [comment]
> So maybe it's not a good idea to do this because of the overhead. The alternative is to do nothing and let user code implement this manually.

Yeah, I think we should just close this.  We could revisit if there's significant demand, but this is such a rarely used corner of the library, there hasn't been and I suspect there won't be.

Thanks for the suggestion and discussion.
