### ISSUE TITLE
Question: Are local functions guaranteed to be inlined by the JIT?

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#1638]
Unlike for `MethodImpl(MethodImplOptions.AggressiveInlining)` there is no statement in the documentation https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions about whether or not local functions are guaranteed to be inlined by the JIT.

Calls can be expensive especially in loops and I would like to know if its worth switching to local functions, continue to use `MethodImpl(MethodImplOptions.AggressiveInlining)` or consider writing a writing a large method for more performance and less readability.

**Comment by EgorBo** [comment]
> whether or not local functions are guaranteed to be inlined by the JIT.

Why do you expect them to be always inlineable? E.g. in BCL in some places local functions are used for "slow path" logic. I think inliner doesn't care if it's a local function or a normal one. Also it's not currently possible to use attributes on top of local functions (see https://github.com/dotnet/csharplang/issues/1888) to be able to use `MethodImpl`.

**Comment by Symbai** [comment]
Talking about `MethodImpl` I'm not talking about local functions anymore then. Just wondering how I can maintain readability while avoid unnecessary calls. If you do something small but repetitive its more readable and maintainable to put this into a new method but if the JIT does not inline it (I wish it would do because I don't care how large the method in memory will be) it will become expensive.

And only a very few solutions do exist as far as I know: Using MethodImpl attribute (but there is no guarantee the JIT does what you want here) or local functions or writing your repetitive stuff at the cost of readability and maintainability within the function so the jit WILL inline, I guess.

In order to find the best solution for my needs I would need to know if local functions are guaranteed to be inlined. Which kinda makes sense because they are not used anywhere else. On the other hand I have no idea, that's because I am asking.

Here is an example of a small piece of code I've put outside of a function which runs in multiple threads and which calls this function within a loop and gets called a few times within this loop. Its actually a bit more than that but just to get an idea.
```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
 int DoStuff(int a, int b, MyEnum option) {
	if (option == MyEnum.Add)
		return a + b;
	if (option == MyEnum.Sub)
		return a - b;
	if (option == MyEnum.Div)
		return a / b;
	if (option == MyEnum.Mul)
		return a * b;
}
```

**Comment by jkotas** [comment]
The inlining rules for local functions are exactly same as inlining rules for regular functions. Nothing guarantees them to be inlined.
