### ISSUE TITLE
Make Linq, Dynamic and Expressions use the same coding style as the rest of corefx

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#16390]
At least for consistency sake.

It could be as simple as running the formatter tool, but could be a fairly big change. In particular for Linq.

**Comment by deeprobin** [comment]
@cston Is this issue still relevant since `System.Linq.Expressions` is effectively archived?

**Comment by cston** [comment]
Thanks @deeprobin. I'll close this.

**Comment by cston** [comment]
Closing as per [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/README.md).

**Comment by deeprobin** [comment]
@cston Gladly. Now that we're on the subject. When you have time, can you go through the label `area-System.Linq.Expressions` and see what is still relevant?
