### ISSUE TITLE
What about adding a ConcurrentSet<T>?

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/runtime#16443]
The need for it comes up every now and then. To me it would make sense next to `ConcurrentDictionary<TKey, TValue>`

**Comment by MgSam** [comment]
So no one ever made an API proposal for this? Maybe you guys should add the up-for-grabs label.

**Comment by LeaFrock** [comment]
@MgSam I can't stand it anymore, so I've spent some time on the api proposal.

Details see #39919 . Let's promote it and finally make it.

**Comment by jkotas** [comment]
Duplicate of #39919 that has actual API proposal
