### ISSUE TITLE
Question: unaligned generic read/write

### ISSUE THREAD

**Issue by buybackoff** [dotnet/runtime#1650]
`Unsafe.[Write/Read]Unligned` accept `byte` ref or pointer. Is it correct to use `Unsafe.As<T,byte>` to get a byte reference for any possible type `T` - both reference and value types? Correct means no GC holes or subtle behavior that could bite randomly once per gazillion operations.

```
public void DangerousSetUnaligned<T>(int index, T value)
{
    // For underlying pointers it just works as casting pointers/refs is simple.
    // For refs/non-blittable types it's more complicated:
    // `As<T, byte>` is a simple `ret` instruction, so we get
    // ```
    // unaligned. 0x01
    // stobj !!T
    // ```
    // to !!T&

    ref var desitantionT = ref DangerousGetRef<T>(index); // same as Span[index]
    ref var destinationByte = ref Unsafe.As<T, byte>(ref desitantionT);
    Unsafe.WriteUnaligned(ref destinationByte, value);
}
```
ECMA-335 doesn't say anything about that .unaligned could only be applied to value types. "The operation of the stobj instruction can be altered by an immediately preceding unaligned. prefix instruction." So I couldn't find anything that forbids using the prefix before `stobj !!T`, but maybe I missed something.

The use case is to be unconstrained generic but at the same time support writing unaligned structs to contiguous memory, e.g. to an array such as `Struct17[]`:

```
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 17)]
struct Struct17
{
    public long Field1;
    public long Field2;
    public byte Field3;
}
```

**Comment by jkotas** [comment]
Yes, this should work fine.

Note that the object references are always aligned in memory. It is side-effect of GC needing to know where all object references are stored in memory. There is no way to create a valid storage for object reference in memory that is misaligned.

**Comment by buybackoff** [comment]
@jkotas thanks! I understand that references are aligned, but was confused by putting `unligned` prefix before ref types.

I wonder why/how `SpanHelper.IndexOf<T>` works without unaligned prefix for all generics?

```
[StructLayout(LayoutKind.Sequential, Pack = 1)]
struct Struct17 : IEquatable<Struct17>
{
    public long Field1;
    public long Field2;
    public byte Field3;

    public bool Equals(Struct17 other)
    {
        return Field1 == other.Field1 && Field2 == other.Field2 && Field3 == other.Field3;
    }
}

[Test]
public unsafe void SpanUnalignedIndexOf()
{
    var arr = new Struct17[2];
    var value = new Struct17() {Field1 = 1};
    arr[1] = value;

    var span = arr.AsSpan();
    Assert.AreEqual(1, span.IndexOf(value));

    Assert.AreEqual(17, (long)Unsafe.AsPointer(ref arr[1]) - (long)Unsafe.AsPointer(ref arr[0]));
}
```

`span.IndexOf()` here goes via [this method](https://github.com/dotnet/runtime/blob/0812d49aeb7ae83bf04a6799f47594ad8a47cfdd/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.T.cs#L120) and particularly via a line `if (value.Equals(Unsafe.Add(ref searchSpace, index)))`, that is directly dereferencing from `Unsafe.Add` returned reference.

If .NET Core works only on architectures where unaligned reads work (maybe slow but without faults) then one could happily forget about prefixing reads/writes with `unaligned`. Or maybe for architectures where alignment is critical JIT does the right thing and one could also forget about that as well and use references directly?

**Comment by jkotas** [comment]
>  .NET Core works only on architectures where unaligned reads work

There are cases where unaligned reads do not just work on ARM. For example, access to misaligned `double` will throw DataMisalignedException on .NET Core, unless it is the slower unaligned variant.

> `[StructLayout(LayoutKind.Sequential, Pack = 1)]`

If you are manually controlling struct layout like this, you are on your own. You have to make sure that all places in your code use unaligned reads as appropriate. For example, if one of the fields of your struct was "double" and you wanted to make sure that the code works well on ARM, your Equals method would need to the appropriate `Unsafe.ReadUnaligned` methods to read the fields.

**Comment by buybackoff** [comment]
> your Equals method would need to the appropriate Unsafe.ReadUnaligned methods to read the fields.

I read it as dereferencing `T` is opaque memcpy, does it work this way? I need tight packing for storage to avoid empty regions and alignment calculations. Memcpy from storage to the stack is actually a desired behavior.

If I add these lines to the test:

```
var v0 = arr[0];
var v1 = arr[1];
Assert.AreEqual(24, (long)Unsafe.AsPointer(ref v0) - (long)Unsafe.AsPointer(ref v1));
```
it shows that on the stack the structs are aligned to 8 bytes and `long`s inside the structs become aligned.

So now I understand that the problem could be if I dereference a field from a storage directly, without copying to the stack, but `Span.IndexOf` does copy a value to the stack before calling `value.Equals([deref and store to the stack here]Unsafe.Add`. 

And since the original question is about _unconstrained generics_ I cannot dereference some (e.g. double) field from inside of a `T` struct directly. Every return by value from a container that wraps the tightly packed storage will be copied to the stack and on the stack the `T` value will be aligned to 8 bytes. Therefore alignment is only a concern when accessing fields, not copying them from storage to the stack.

If I change the layout to

```
public long Field1;
public byte Field3;
public long Field2;
```
then `Field2` is unaligned on the stack
```
Assert.AreEqual(15, (long)Unsafe.AsPointer(ref v0) - (long)Unsafe.AsPointer(ref v1.Field2));
```
and only for this case I need to use unaligned access inside the `Equals` method.

I was thinking that dereferencing of such structs itself could cause a fault.

Thank you very much for explanation!
