### ISSUE TITLE
Question: does CLR support for coroutines make sense?

### ISSUE THREAD

**Issue by bert2** [dotnet/runtime#1651]
I was very impressed how coroutines where built into C++20 by generalizing the calling conventions<sup>1</sup>. Is this considered for the CLR? Would it even be worth it?

I assume that features like `async`/`await` and `yield` would greatly benefit from that performance-wise, but the cost to change their implementations would be immense. However, laying the groundwork in the CLR might actually not be that costly...?

I'm just wondering whether this is on someones radar, because, so far, I could only find [this comment](https://github.com/dotnet/csharplang/issues/317#issuecomment-322828975) in a charplang issue asking which CLR changes would benefit C# language features.

---

<sup>1</sup> [This summary](https://lewissbaker.github.io/2017/09/25/coroutine-theory) of the feature (before it got standardized) gives a nice overview.

**Comment by jkotas** [comment]
As far as I know nobody has done analysis of the estimated benefits and costs of having built-in coroutines support in the runtime. I agree that it would be useful to have such analysis so that we can compare the cost/benefit of doing this with other work.

**Comment by stephentoub** [comment]
Closing as answered.
