### ISSUE TITLE
Wrong value when using Unsafe.As<,> between byte? and byte

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#1652]
The following code returns 1 when non-nullable and 5 when nullable. If this is intended whats the fastest way to convert from a nullable byte array to a value type like byte / int / etc?

```
byte?[] b = new byte?[] { 5 };

var one = Unsafe.As<byte?, byte>(ref MemoryMarshal.GetReference(b.AsSpan())); // => 1
var two = Unsafe.As<byte?, byte?>(ref MemoryMarshal.GetReference(b.AsSpan())); // => 5
```

**Comment by jkotas** [comment]
> whats the fastest way to convert from a nullable byte array to a value type like byte / int / etc

Allocate a new array and convert each element. `byte?` and `byte` have different layout, so there is no shortcut you can take.
