### ISSUE TITLE
[crossgen(2)] Cross Compilation from a single platform?

### ISSUE THREAD

**Issue by cyraid** [dotnet/runtime#1653]
I apologize if this seems too much like a question, but it may serve to be a milestone for the future. I don't want to assume, but is crossgen or crossgen2 meant as a native cross compiler?

.NET would hugely benefit from being able to cross compile to [arm/arm64/x86/x64/wasm]-[win32/win64/linux/mac] all from a single platform. This would be huge, and would make it ahead of Java, which seems to be moving forward with GraalVM.

If this isn't what I was thinking, is there such a Tool? I've looked at CoreRT, but as I understand, you can only compile to the same platform you're on? Which would mean you'd need a Mac, if you were to compile to Mac? (_oh Apple and your extreme greed that you can't allow Mac to be run on any other hardware than Apple_)

**Comment by jeffschwMSFT** [comment]
@fadimounir

**Comment by fadimounir** [comment]
Thanks for your question @cyraid.

The crossgen compiler is meant to be a native compiler/cross-compiler, but it only supports a limited set of scenarios (currently, only ARM/ARM64 cross-architecture compilations). There is no cross-platform support with crossgen currently.

Crossgen2 is intended in the long run to replace crossgen, and the plan is to be able to use crossgen2 for more cross compilation scenarios, given its architecture.

>  I've looked at CoreRT, but as I understand, you can only compile to the same platform you're on?

The CoreRT compiler currently cannot do any form of cross-compilations, and is not a compiler that we are actively developing and supporting at the moment.

**Comment by cyraid** [comment]
Okay thank you.
