### ISSUE TITLE
TestWrappers get built to wrong location

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#1655]
After a coreclr test build, the following directories exist (Windows, x64, Checked):

```
f:\gh\runtime2\artifacts\tests>dir /b f:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.SIMD
JIT.SIMD.XUnitWrapper.cs
JIT.SIMD.XUnitWrapper.csproj

f:\gh\runtime2\artifacts\tests>dir /b f:\gh\runtime2\artifacts\tests\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.SIMD\JIT.SIMD.XUnitWrapper
JIT.SIMD.XUnitWrapper.AssemblyInfo.cs
JIT.SIMD.XUnitWrapper.AssemblyInfoInputs.cache
JIT.SIMD.XUnitWrapper.assets.cache
JIT.SIMD.XUnitWrapper.csproj.CopyComplete
JIT.SIMD.XUnitWrapper.csproj.FileListAbsolute.txt
JIT.SIMD.XUnitWrapper.csproj.nuget.cache
JIT.SIMD.XUnitWrapper.csproj.nuget.dgspec.json
JIT.SIMD.XUnitWrapper.csproj.nuget.g.props
JIT.SIMD.XUnitWrapper.csproj.nuget.g.targets
JIT.SIMD.XUnitWrapper.dll
project.assets.json
```

The built version of the wrappers are getting the wrong directory.

@dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
I'm changing this in an upcoming PR but just to make sure, what would be the correct directory? We shouldn't mix the source directory with the output directory.

**Comment by BruceForstall** [comment]
> We shouldn't mix the source directory with the output directory.

But isn't the source also generated? So does it matter if the generated source and generated build outputs are mixed?

My main concern was the `artifacts\tests\artifacts\tests` oddity.

If you want the generated source and builds separate, then maybe something like:
```
artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers.src\JIT.SIMD
artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers.build\JIT.SIMD
```
?

**Comment by jashook** [comment]
Is this issue still ongoing?

**Comment by BruceForstall** [comment]
@jashook Yes.
