### ISSUE TITLE
JIT: Subobtimal codegen for zero-terminated loops

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/runtime#1656]
Given the following zero-terminated loop:

```C#
public void M(int i) {
    for (; i != 0; i--)
        Console.WriteLine("foo");
}
```

Current asm looks like:

```asm
C.M(Int32)
    L0000: push rsi
    L0001: sub rsp, 0x20
    L0005: mov esi, edx
    L0007: test esi, esi
    L0009: jz L0023
    L000b: mov rcx, 0x1389b488b28
    L0015: mov rcx, [rcx]
    L0018: call System.Console.WriteLine(System.String)
    L001d: dec esi
    L001f: test esi, esi  <-- ???
    L0021: jnz L000b
    L0023: add rsp, 0x20
    L0027: pop rsi
    L0028: ret
```

Note the extra `test` emitted, when the zero flag could be checked immediately after the `dec`

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunHiUGAWQAUASwB2GBqICUHLj0UAzaA2EBuaQwCEAXgYAGTaLhwZCxZabkAnMIBEKiPZnqLDAL40PQA)

**Comment by saucecontrol** [comment]
Ah yes, and a very similar one here: https://github.com/dotnet/coreclr/issues/19074

I'm fine to close this as a dupe if the others are getting migrated over here

**Comment by GrabYourPitchforks** [comment]
Yeah, I'd close this as a dupe of https://github.com/dotnet/coreclr/issues/19074 and include your test scenario as a comment back in that tracking issue. That way the scenario doesn't get lost.

**Comment by saucecontrol** [comment]
Will do, thanks
