### ISSUE TITLE
Kerberos ticket is not fetched when target is a user

### ISSUE THREAD

**Issue by vijaykota** [dotnet/runtime#16576]
The xplat NegotiateStream implementation is able to successfully use Kerberos auth when the target of `AuthenticateAsClientAsync` is a service principal eg. HOST/machine, HTTP@machine etc. However, if the target is a user like foo@domainfqdn, the auth is failing. Perhaps in this case, the `gss_import_name` needs to be called with some OID other than `GSS_KRB5_NT_PRINCIPAL_NAME`

**Comment by wfurt** [comment]
Do you feel this is still important @mconnew ? It is pretty old issue and we would probably need more specific repro if we want to approach it.

**Comment by mconnew** [comment]
@wfurt, yes it is still important. I should be able to create a solution using CoreWCF and WCF Client relatively easily, along with a WCF equivalent on .NET Framework. Super backed up with tasks right now though. Ping me a couple of weeks before you want to start work on this and I will put something together for you.
