### ISSUE TITLE
Make appropriate GC environment variables available in runtimeconfig.json

### ISSUE THREAD

**Issue by andy-ms** [dotnet/runtime#166]
A few GC environment variables have no `runtimeconfig.json` equivalent.
This proposal is to add new `runtimeconfig.json` settings with the same effect as existing environment variables.
Proposed new settings:

* "System.GC.CpuGroup": Same as `COMPlus_GCCpuGroup`
* "System.GC.HighMemoryPercent": Same as `COMPlus_GCHighMemPercent`
* "System.GC.LargePages": Same as `COMPlus_GCLargePages`
* "System.GC.HeapAffinitizeRanges": Same as `COMPlus_GCHeapAffinitizeRanges`

**Comment by mangod9** [comment]
@cshung it appears LargePages is enabled in runtimeconfig, but other settings were not? Do we plan to add them in 5?

**Comment by cshung** [comment]
My commit https://github.com/dotnet/runtime/commit/44ed52a8cd71d4dedc58943725a1fe3a14f4b38d introduced in PR https://github.com/dotnet/runtime/pull/34797 provided the capability to enable a configuration to be read from `runtimeconfig.json` simply by adding the expected name in the third column of the gcconfig table like this:

https://github.com/dotnet/runtime/blob/824d7709f03d093e48b1ea23f0bad771de6d12dc/src/coreclr/src/gc/gcconfig.h#L78-L80

This makes exposing a configuration through `runtimeconfig.json` an easy task. This only three things we need to do are:

1. Decide on the list of configurations to be exposed. The full list of configurations that the GC uses is already specified in the table.
2. Decide on the names that we will use for those we wanted to expose, and
3. Make sure the documentation is up to date, the last column of the table already described the configuration, we just needed to expand on them making sure readers will understand it.

@Maoni0, can you please help with the first two items?

**Comment by mangod9** [comment]
These are specifically called out in the original comment: 

"System.GC.CpuGroup": Same as `COMPlus_GCCpuGroup`
"System.GC.HighMemoryPercent": Same as `COMPlus_GCHighMemPercent`
"System.GC.LargePages": Same as `COMPlus_GCLargePages`
"System.GC.HeapAffinitizeRanges": Same as `COMPlus_GCHeapAffinitizeRanges`

**Comment by Maoni0** [comment]
all 4 mentioned at the top should be exposed via runtimejson; I'm fine with the names suggested.

the ones you added to specify SOH/LOH/POH separately for hardlimit should also be exposed, following the same naming convention - `System.GC.HeapHardLimitSOH`, `System.GC.HeapHardLimitSOHPercent`, etc.

also I just noticed..it's very odd that GCHeapHardLimit itself is not exposed via runtimejson but GCHeapHardLimitPercent is. they should both be in runtimejson (I thought they were?). 

```
    INT_CONFIG   (GCHeapHardLimit,        "GCHeapHardLimit",        NULL,                             0,                 "Specifies a hard limit for the GC heap")                                                 \
    INT_CONFIG   (GCHeapHardLimitPercent, "GCHeapHardLimitPercent", "System.GC.HeapHardLimitPercent", 0,                 "Specifies the GC heap usage as a percentage of the total memory")                        \
```
