### ISSUE TITLE
Propose, API change: DispatchProxy instantiation

### ISSUE THREAD

**Issue by Semyntax** [dotnet/runtime#16614]
The current API for instancing the DispatchProxy is counter intuitive name- and usage-wise. 
Especially when injecting dependencies into the proxy.

``` cs
public static T Create<T, TProxy>() where TProxy : DispatchProxy 
```

Currently `Create` will return the proxied instance of T, which then oddly needs to be cast to the TProxy type in order to inject any dependencies into the proxy instance itself:

``` cs
ISomeServiceInterface proxiedInstance = DispatchProxy.Create<ISomeServiceInterface, MyProxy>(); 
var actualProxy = proxiedInstance as MyProxy;
actualProxy.MyDependency = dependency;
```

Instead consider returning the proxy instance itself, and add a property in order to retrieve the proxied instance to allow following usage:

``` cs
MyProxy proxy = DispatchProxy.Create<IServiceInterface, MyProxy>(); 
proxy.MyDependency = dependency;
IServiceInterface proxiedInstance = actualProxy.ProxiedInstance;
```

**Comment by GrabYourPitchforks** [comment]
IMHO this is a docs issue. The scenario works (cast the returned proxy to your base type and set properties), but it's not intuitive. We need to amend the existing docs with sample code showing how to accomplish these common scenarios.

If there's still an API change that needs to take place after the docs are updated then we can consider that through a separate issue.

**Comment by paulovila** [comment]
Agree, It's confusing, compared to RealProxy in Dotnet Framework, the functionality is broken already because the expected is that ```DispatchProxy.Create ``` returns **a class** rather than an interface. At this point the DispatchProxy.Create is equivalent to implementing your own interface.

**Comment by steveharter** [comment]
Created the docs issue.

Changing to API-needs work.

Moving to future based on schedule.

**Comment by steveharter** [comment]
It is possible to wrap the DispatchProxy.Create() with your own static "Create()" method and set state on your proxy after it's created. This will hide some of the casting ugliness from the consumer. See my comment at https://github.com/dotnet/runtime/issues/42858#issuecomment-1007762857

**Comment by steveharter** [comment]
For new possible API, I think a `public void TProxy AsProxy()` added to `DispatchProxy` would be convenient; it would simply due the cast to `TProxy` so that any state\dependency properties added to `TProxy` (for example, the target object) can be set.

**Comment by steveharter** [comment]
>> It is possible to wrap the DispatchProxy.Create() with your own static "Create()" method ... This will hide some of the casting ugliness from the consumer.

> Who are the "you" and "consumer" in this statement? When I read this, I find myself filling both roles. I am a consumer of DispatchProxy, and I am also a person who wants to use a prettier API.

The author of the proxy can add static "Create()" method that takes the additional parameters. The consumer then needs to be aware of that method.

**Comment by steveharter** [comment]
> (Also, should we close one of these threads so the discussion gets combined in the same place?)

Yes thanks. I'll close this one and add some additional detail to https://github.com/dotnet/runtime/issues/42858
