### ISSUE TITLE
Misconfiguration of runtime-coreclr gcstress0x3-gcstress0xc

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#1666]
The runtime-coreclr gcstress0x3-gcstress0xc pipeline fails with:

```
Job run_test_p1__Linux_x64_checked depends on unknown job coreclr_test_build_p1_OSX_x64_checked.
```

e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=480199&view=results

@dotnet/runtime-infrastructure

**Comment by safern** [comment]
@trylek maybe you can take a look at this one?

**Comment by trylek** [comment]
Sure, will fix.
