### ISSUE TITLE
New Magnitude class for System.Numerics

### ISSUE THREAD

**Issue by varocarbas** [dotnet/runtime#16676]
Supporting magnitudes (values + units) might be a good complement for the current vector functionalities of `System.Numerics`. It would allow .NET to deal with any Physics-based situation in an intuitive and easy way. What I am proposing here might also be adapted to other not-related-to-Physics requirements, like angles or computing units (e.g., bit/byte).

The new `Magnitude` class is expected to be defined in such a way that all the operations and unit conversions might be easily performed. The idea is allowing programmers to interact with values+units as intuitively as they currently do with just values. For example: having 5 m/s and wanting to convert it to in/s or to add it to 3 ft/h.

Rough sketch of what I have in mind:

``` C#
public class Magnitude
{
    public static Magnitude operator +(Magnitude first, Magnitude second)
    {
        //It is necessary to confirm whether "type" & "measurement" are compatible and eventually perform all the required conversions.
        return new Magnitude((decimal)first.value + (decimal)second.value, first.measurement.unit.ToString());
    }

    //Further basic operator overloads.

    //Other methods performing basic operations among Magnitude instances.


    public readonly MagnitudeType type; //The type of the instance has to remain unaltered.
    public object value { get; set; }  //The getter will be defined on account of the "measurement" properties.
    public Measurement measurement { get; set; }

    public Magnitude(decimal value, string unit)
    {
        this.value = value;

        //The "unit" value will be adequately parsed and analysed. 
        //The version below is a simplistic version to show the idea.
        if (unit == "m")
        {
            this.type = MagnitudeType.Length;
            this.measurement = new Measurement(UnitSystem.InternationalSystem, LengthInternational.Meter);
        }
        else if (unit == "ft")
        {
            this.type = MagnitudeType.Length;
            this.measurement = new Measurement(UnitSystem.ImperialSystem, LengthImperial.Foot);
        }
    }

    //Other overloads accepting different arguments.
}

public class Measurement
{
    public UnitSystem system { get; set; }
    public object unit { get; set; }

    public Measurement(UnitSystem system, object unit)
    {
        this.system = system;
        this.unit = unit;
    }
}

//Very simplified versions showing how the enums are expected to look like.
public enum MagnitudeType { Length, Weight }
public enum UnitSystem { InternationalSystem, ImperialSystem };
public enum LengthInternational { Millimeter, Centimeter, Meter };
public enum LengthImperial { Inch, Foot };

```

Simple example showing how the aforementioned code is expected to be used:

``` C#
Magnitude var1 = new Magnitude(1.234m, "m"); 
Magnitude var2 = new Magnitude(5.678m, "ft");
Magnitude var3 = var1 + var2;
```

I can only think of one drawback for the proposed approach: relying on enums in a situation like this (i.e., with many alternatives and classifications) implies hardcoding a relevant amount of different scenarios. In any case, I think that it would be worthy anyway.

CLARIFICATION (from my previous contributions, I understand that this issue should be evident, but just in case...): I am expecting to take care of the proposed implementation completely by my own and also to deliver a comprehensive-enough first version. The initial lack of detail is exclusively motivated by the fact that I prefer to not spend too much time on this before confirming that the .NET community/team likes it.

**Comment by tannergooding** [comment]
Going to close this for now. I agree with @mellinoe's previous statement and I don't see this having gained much traction since then.

There are a lot of open ended questions still and I would ideally like to see a prototype of this library and is usage out in the wild before considering first class support in the .NET Libraries.

**Comment by juliusfriedman** [comment]
@tannergooding,

https://github.com/juliusfriedman/net7mma_core/blob/2b0fb75ad5e7f498a7660ea518d03facd1a8148b/Concepts/Classes/Units.cs

https://www.codeproject.com/Articles/578116/Complete-Managed-Media-Aggregation-Part-III-Quantu

I think it also can serve as a `Unit` type once you have the `IdealUnit` and `IndirectionUnit`
