### ISSUE TITLE
Is generating IL containing LDELEMA and STIND without pinning safe?

### ISSUE THREAD

**Issue by IntelOrca** [dotnet/runtime#1673]
I am not sure whether this is the best place to ask, but I know there will be some CLR experts here to help. We would appreciate any advice we could get on generating some particular IL.

We develop a compiler that compiles COBOL directly to .NET IL. For each COBOL data item that the user defines, we attempt to optimise it by mapping the data item directly to an IL field. In some cases though we must preserve the intended COBOL byte structure, we do this by storing the entire data for a COBOL program in a single byte array. Method code will then directly read and write bytes from and to that byte array.

In order to maximise performance, we use `LDELEMA` to obtain the address of the position in the byte array we want to write, and then use `STIND` to write the value. At the moment, the address of the array is only pushed onto the evaulation stack, it is never stored in a local. We also do not pin the byte array whilst the address of the byte array is used. Here is an example of such generated IL:

```
IL_00b3: ldarg.1
IL_00b4: ldfld uint8[] MfSoap/_MF_LCTYPE_1::'_MF_LINK_lk-mfsoap-node-name-ptr'
IL_00b9: ldarg.1
IL_00ba: ldfld int32 MfSoap/_MF_LCTYPE_1::'_MF_LNKO_lk-mfsoap-node-name-ptr'
IL_00bf: ldelema uint8
IL_00c4: ldarg.1
IL_00c5: ldfld uint8[] MfSoap/_MF_LCTYPE_1::'_MF_LINK_lk-x'
IL_00ca: ldarg.1
IL_00cb: ldfld int32 MfSoap/_MF_LCTYPE_1::'_MF_LNKO_lk-x'
IL_00d0: ldc.i4.0
IL_00d1: ldarg.0
IL_00d2: call int32 [MicroFocus.COBOL.Runtime]MicroFocus.COBOL.Program.Reference::GetPointer32(uint8[], int32, int32, class [MicroFocus.COBOL.Runtime]MicroFocus.COBOL.Program.IObjectControl)
IL_00d7: unaligned. 1
IL_00da: stind.i4
```

We are worried that the garbage collector may potentially move the memory of the byte array between calling `LDELEMA` and `STIND`. However the sort of code we generate above has been used and run for well over 15 years and we have not come across any reports that suggest this is an issue. This makes us very uncertain as to whether it is just extremely rare or impossible. We would like to know whether we should definitely be storing the byte array in a pinnable local or not and whether doing that will affect the performance / throughput of all similarly generated code. From studying the machine code that is generated by C# when pinning objects and this [article](https://mattwarren.org/2016/10/26/How-does-the-fixed-keyword-work/), there is rarely much change but rather just extra metadata added for the GC to inspect. This makes me think that the performance degrade will be negligible, but it will be nice to get some insight on this.

Articles such as this [one](https://mattwarren.org/2016/08/08/GC-Pauses-and-Safe-Points/) indicate that the GC only pauses managed threads at safe points. Could it be that that there is never a safe point between the `LDELEMA` and `STIND` instructions in the code we generate? How does the CLR determine where to insert safe points?

**Comment by MichalStrehovsky** [comment]
For the exact semantics of IL opcodes it's the best to refer to the ECMA-335 specification: https://www.ecma-international.org/publications/standards/Ecma-335.htm

LDELEMA produces a managed pointer on the evaluation stack (type `&` referenced in the spec). This type is properly tracked by the GC and there's no need to pin the referenced array. STIND accepts type `&` as its input and does a GC-aware store for it.

The only way to break this is if you would e.g. place a CONV.I instruction in-between those two. This would convert the managed pointer to an unmanaged pointer and all GC tracking would be lost.

**Comment by IntelOrca** [comment]
@MichalStrehovsky Thanks, that is really good to know. I think that answers of my questions.
