### ISSUE TITLE
Incorrect verification of type parameter constraints by CLR verifier

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#1674]
Probably invalid behavior of CLR verifier caused by default generic interface method while C# compiler telling that everything is OK:
```csharp
static class Program
{
        private interface ILogEntry
        {
            long Index { get; }
        }

        private interface IAuditTrail<TRecord>
            where TRecord : class, ILogEntry
        {
            ValueTask AppendAsync<TRecordImpl>(TRecordImpl impl, CancellationToken token)
                where TRecordImpl : notnull, TRecord => new ValueTask();
        }

        private interface IRaftLogEntry : ILogEntry
        {
            long Term { get; }
        }

        private sealed class AuditTrail : IAuditTrail<IRaftLogEntry>
        {
        }

        private readonly struct EmptyLogEntry : IRaftLogEntry
        {
            long IRaftLogEntry.Term => 0L;

            long ILogEntry.Index => 0L;
        }

        static void Main(string[] args)
	{
            IAuditTrail<IRaftLogEntry> auditTrail = new AuditTrail();
            auditTrail.AppendAsync<EmptyLogEntry>(new EmptyLogEntry(), CancellationToken.None);
	 }
}
```
The exception is
```
System.Security.VerificationException
  HResult=0x8013150D
  Message=Method ConsoleApp1.Program+IAuditTrail`1[ConsoleApp1.Program+IRaftLogEntry].AppendAsync: type argument 'TRecordImpl' violates the constraint of type parameter 'TRecordImpl'.
  Source=ConsoleApp1
  StackTrace:
   at ConsoleApp1.Program.Main(String[] args)
```
If implementation of `AppendAsync` method moved to class instead of interface then everything is fine. 

Version information:
- .NET Core version 3.1.100
- Windows 10 Enterprise 1809 64-bit

**Comment by AndyAyersMS** [comment]
This isn't a codegen issue; reclassifying.

Seems like the runtime is properly rejecting the program as `EmptyLogEntry` does not satisfy the constraints, but the error message could be improved.

**Comment by sakno** [comment]
@AndyAyersMS could you please provide more details? Why the runtime decided that this program is invalid? And why Roslyn compiler doesn't show anything? The source of this issue is the default implementation of interface method. If you move implementation to the class then everything is fine. It makes default implementation of generic interface methods unusable.

I can only guess but verifier cannot recognize generic constraints correctly if interface method has default implementation. From IL perspective, `Main` method looks similar for both cases.

**Comment by DrJohnMelville** [comment]
I ran into what I think is the same issue: here is my repro code.

`void Main()
{
	((IBuggy<int>)new Worky()).Foo<int>();
	((IBuggy<object>)new Worky2()).Foo<string>();
	((IBuggy<Open>)new Buggy()).Foo<Open>();
}

interface IBuggy<T1>
{
	public void Foo<T2>() where T2 : T1 => Console.WriteLine($"Works for type: {typeof(T1)}");
}
public class Worky : IBuggy<int> { }
public class Worky2 : IBuggy<object> { }
public class Buggy : IBuggy<Open> { }
public class Open { }`

**Comment by mangod9** [comment]
looks like this should just fail compilation?

**Comment by DrJohnMelville** [comment]
Why should it fail at all.  A class of type Open satisfies the constraint that the class be of type Open or one of its descendants.  It is frequently useful to define generic methods which require a subclass of the generic type of the main method.  (This is especially helpful if you want to return one of the arguments and allow the subtype information to "flow through" the method call.

**Comment by mangod9** [comment]
hmm.. the original issue was that the `class` contraint was broken since `EmptyLogEntry` is a struct. Your repro is different and needs to be investigated.

**Comment by sakno** [comment]
@mangod9 , `EmptyLogEntry` is a struct, yes. However it is implementing interface which contains default implementation of the method. I still don't understand why it's incorrect.

**Comment by Joe4evr** [comment]
@sakno You misunderstand your own code: `EmptyLogEntry` isn't implementing anything that contains a default implementation.

If I'm reading this right, the appropriate fix here should be for the compiler to expand `where TRecordImpl : TRecord` as all of `TRecord`'s constraints, and because those include the `class` constraint, it becomes a compiler error to pass a struct implementation.

**Comment by DrJohnMelville** [comment]
@sakno The following code:
    private interface IAuditTrail<TRecord> where TRecord : class, ILogEntry

requires that the type argument to IAuditTRail much be a class.
      private sealed class AuditTrail : IAuditTrail<IRaftLogEntry>

attempts to instantiate IAuditTrail with an interface.  An interface is not a class, therefore IRaftLogEntry is not a valid type parameter to IAuditTrail, and the compiler should have rejected it.

**Comment by Joe4evr** [comment]
@DrJohnMelville Interfaces will actually satisfy the `class` constraint perfectly fine.

**Comment by DrJohnMelville** [comment]
Thanks.  I just learned something.  I checked and you are right.

**Comment by sakno** [comment]
Once again, the code from my original post can be compiled successfully by Roslyn compiler and produces valid IL code. I understanding that calling of interface method with default implementation which is not overridden by value type should cause boxing. This is fine. However, instead of this CLR just crashes.

**Comment by sakno** [comment]
@Joe4evr , thanks for fixing me. The original post was a long time ago)

**Comment by Joe4evr** [comment]
According to a chat with @CyrusNajmabadi, this appears to be legal according to the C# spec and maybe it *should* be fixed in the runtime:
> It is valid for `S` to have the value type constraint and `T` to have the reference type constraint. Effectively this limits `T` to the types `System.Object`, `System.ValueType`, `System.Enum`, ***and any interface type***.

(Emphasis mine) [Source](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#type-parameter-constraints) (several paragraphs down, [image](https://files.gitter.im/dotnet/roslyn/nGuM/image.png)).

**Comment by CyrusNajmabadi** [comment]
this is also legal and both compiles and runs today:

```c#
using System;

interface IFoo
{
}

struct Foo : IFoo
{
}

class C<T> where T : class
{
    public void M<S>(S s) where S : T
    {
        Console.WriteLine(s);
    }
}

class Program
{
    static void Main(string[] args)
    {
        new C<Enum>().M<ConsoleColor>(ConsoleColor.Red);
        new C<IFoo>().M<Foo>(new Foo());
    }
}
```

The `class` constraint only impacts the type parameter it is actually declared against.  It doesn't require a dependent type parameter also have that constraint.  It would also be a large breaking change to reuqire that (as it would break those simple examples demonstrated above).

**Comment by mangod9** [comment]
Thanks for the follow up, I believe we have a fix which will validate.

**Comment by mangod9** [comment]
fix is merged.
