### ISSUE TITLE
Increase CI build verbosity level

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#1678]
Especially for libraries build on CI it's very hard to know from the current "no-log" output which configuration failed and what are the settings in `-allConfigurations` mode.

It'd be beneficial to increase the CI log verbosity to higher level instead of asking developers to reproduce the build failure locally to see the actual details.

**Comment by ViktorHofer** [comment]
Triage: We believe the current log output make sense for most people. If you need further details of the build, you can look into the binlog that we upload into the artifacts of the AzDO build.
