### ISSUE TITLE
Consider exposing CollectionsMarshal.AsSpan

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#1680]
Please consider exposing System.Runtime.InteropServices.CollectionsMarshal. It would be a huge benefit of avoiding the additional allocation of `ToArray()`.

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L202-L205

**Comment by stephentoub** [comment]
What do you mean? It's public.

**Comment by Symbai** [comment]
I was using 3.1 until I figured out it  was made in public for 5. Sorry about that
