### ISSUE TITLE
can't parse datetime using c# only at linux and macos

### ISSUE THREAD

**Issue by aryumin86** [dotnet/runtime#1681]
When parsing date using dotnet core 3.1 (also I tried dotnet core 2.2) that has a format like that: "Вс, 1 дек 2019 20:40:00 +0300" (russian language) I faced with problems on linux (ubuntu) and macos - the date could't be parsed correctly by DateTime.TryParse() and DateTime.TryParseExact(). At the same time when I use the same c# code on windows parsing is correct. 
This is a sample code I used for parsing a date with several formats I tried to use:

`string dateStr = "Вс, 1 дек 2019 20:40:00 +0300";
        string dateStr2 = "Вс, 1 дек 2019 20:50:00";
        DateTime result = default(DateTime);
        DateTime result2 = default(DateTime);
        string[] dateFormats = new string[]{
            "ddd, d MMM yyyy HH:mm:ss",
            "ddd, d MMM yyyy HH:mm:ss K",
            "ddd, d MMM yyyy H:mm:ss",
            "ddd, d MMM yyyy H:mm:ss K"
        };
        var ruRu = System.Globalization.CultureInfo.GetCultureInfo("ru-RU"); 

        if(!DateTime.TryParse(dateStr, ruRu, DateTimeStyles.None, out result)){
            DateTime.TryParseExact(dateStr, dateFormats,
            //System.Globalization.CultureInfo.CurrentCulture,
            ruRu,
            System.Globalization.DateTimeStyles.AssumeUniversal, out result);
        }

        if (!DateTime.TryParse(dateStr2, ruRu, DateTimeStyles.None, out result2)){
            DateTime.TryParseExact(dateStr2, dateFormats,
            //System.Globalization.CultureInfo.CurrentCulture,
            ruRu,
            System.Globalization.DateTimeStyles.AssumeUniversal, out result2);
        }

        Console.WriteLine(result);
        Console.WriteLine(result2);`

The couse is different values of array with monthes names in Russian which is located at CulturyInfo object: DateTimeFormat.AbbreviatedMonthNames: in windows they are:
 ":янв;фев;мар;апр;май;июн;июл;авг;сен;окт;ноя;дек;"
and in linux and macos:
"янв.;февр.;март;апр.;май;июнь;июль;авг.;сент.;окт.;нояб.;дек.;": there are dots at the end of some monthes. As a result the string "Вс, 1 дек 2019 20:40:00 +0300" is not recognized as a valid datetime due to dot at the end of 'дек.' (December) in DateTimeFormat.AbbreviatedMonthNames.

**Comment by Clockwork-Muse** [comment]
Generally speaking, localization is delegated to the host OS, so this is "by design".  This is because people are allowed to create custom localization formats, among other things; that is, we can't tell _what_ the result is going to be, because we don't have all the inputs to the function.

This behavior usually isn't an issue - date/time input in user-facing applications should usually be using things like calendars or date spinners, and data interchange between systems should be using an invariant format like ISO 8601.

**Comment by aryumin86** [comment]
> Generally speaking, localization is delegated to the host OS, so this is "by design". This is because people are allowed to create custom localization formats, among other things; that is, we can't tell _what_ the result is going to be, because we don't have all the inputs to the function.
> 
> This behavior usually isn't an issue - date/time input in user-facing applications should usually be using things like calendars or date spinners, and data interchange between systems should be using an invariant format like ISO 8601.

Thank you a lot for this explanation!
