### ISSUE TITLE
System.Diagnostics.Process doesn't allow to "wait and kill" without a race

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/runtime#16848]
Suppose I have a `System.Diagnostics.Process` bound to some running process. I want to wait until that process exits and if it fails to exit in five seconds I want that process terminated. Here's a piece of pseudocode:

```
if( !process.WaitForExit( 5000 ) ) {
    process.Kill();
}
process.Dispose();
```

The problem is the process might exit between `WaitForExit()` and `Kill()` and then this code gets a rather generic exception. There's no way to write the code above such that there's no potential for the race condition between the other process exiting and this process making the decision of whether to terminate the other process or not.

Same problem on desktop.

There're three approaches to how this can be resolved.

The first one is that `Kill()` does nothing if the process has exited. This would violate the contract stated in the documentation but it's actually the right thing to do. The purpose of `Kill()` is "get rid of the process" and if it so happens the process has exited - okay, nothing to do. I cannot imagine a reasonable case where someone would blindly call `Kill()` and then catch the possible exception and make any decisions on what to do based on whether there was an exception.

The second one is that a parameter with a default value is added to `Kill()` - such that it turns into `Kill( bool throwIfExited = true )`. This prevents violating the current contract but honestly it's stupid.

The third one is crafting some special exception exactly for this case - such that the caller can reliably detect that the process has exited by programmatically inspecting the exception. This would break the contract and it's also stupid.

**Comment by eiriktsarpalis** [comment]
Triage: we feel that eating the exception is an adequate workaround in this instance. Given that the issue hasn't seen a lot of traction in recent years, I am going to close this. Feel free to reopen if you feel otherwise.
