### ISSUE TITLE
BinaryFormatter yields 'Invalid BinaryFormatter Stream' error when deserializing large files multiple times

### ISSUE THREAD

**Issue by buddhashrestha** [dotnet/runtime#1689]
I'm serializing, compresssing and encrypting C# object and save it to the file. That works fine.
Then I need to decrypt, decompress and deserialize it back again (like when opening a project). Now, this works fine for the first time when I start my application, but if I try to retry in the same session, it fails and throws me the following exception with Message: **Invalid BinaryFormatter Stream**

   ```
at System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(Int32 index)
   at System.Runtime.Serialization.Formatters.Binary.SizedArray.set_Item(Int32 index, Object value)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
```

**Note:** This happens only when I'm trying to deserialize a large file. (**>40MB**)

Following is the code I use:

```
var rm = new AesCryptoServiceProvider();
                        rm.Key = this.CryptoKey;
                        rm.IV = this.CryptoIV;

                        using(var sourceStream =  new TempFileStreams().FromBytes(rawData))
                        using (var outStream = new TempFileStreams().GenerateTemp())
                        {
                            using (CryptoStream cryptoStream = new CryptoStream(sourceStream, rm.CreateDecryptor(), CryptoStreamMode.Read))
                            {
                                using (GZipStream gzipStream = new GZipStream(cryptoStream, CompressionMode.Decompress))
                                {
                                    gzipStream.CopyTo(outStream);
                                }
                            }
                            outStream.Position = 0;
                            dataStore = (MyObjectType)BinaryFormatter.Deserialize(outStream);
                        }
```

The above code refers to the following stackexchange implementation: https://codereview.stackexchange.com/questions/158632/rijndael-compression-encryption-class

**Comment by buddhashrestha** [comment]
@danmosemsft is there any reason why BinaryFormatter is discouraged? Since we have circular reference, this was convenient to use for us.

**Comment by danmosemsft** [comment]
@buddhashrestha because arbitrary input can cause it to instantiate arbitrary types, it has caused reliability and security issues over the years. In .NET Core, we have limited the number of our own types that we marked `[Serializable]` as you may have noticed:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization

You should make sure that you completely control what is being serialized, and the payload cannot be tampered with.

@GrabYourPitchforks are there other serializers we recommend that handle cycles?

**Comment by GrabYourPitchforks** [comment]
Cycle handling is inherently dangerous. Even the "safe" `BinaryFormatter`-compatible serializer I was working on forbids cycles by default, requiring the caller to opt-in explicitly.

If you're willing to post a self-contained repo somewhere of the "Invalid BinaryFormatter Stream" error you're getting I can take a look. Even though we discourage `BinaryFormatter`, I don't recall any change offhand that may have led to that error on deserialization.

**Comment by buddhashrestha** [comment]
Sure @GrabYourPitchforks. For now, I had a fix by increasing the application memory using _largeaddressaware_ header (was using 32bit .netframework). In the long term will need to look into designing the models without cycles. This was a good conversation though. Thank you!.
