### ISSUE TITLE
ImportedFromTypeLibAttribute should be available on netstandard2.0

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#1692]
Can we get an update of the System.Runtime.InteropServices package that includes a `netstandard2.0` targeted assembly that adds `System.Runtime.InteropServices.ImportedFromTypeLibAttribute`? 

The attribute is already present on .NET Core 2.0 and .NET Framework, but we can't access it from .NET Standard 2.0 libraries. :(

**Comment by jkotas** [comment]
cc @terrajobst

**Comment by AArnott** [comment]
FYI this is blocking compiling at least some of our VS SDK assemblies to target .netstandard2.0.

**Comment by jkotas** [comment]
.NET Standard 2.0 is "done". I will let @terrajobst comment on what he things about adding new APIs to it, but I believe it would cause more harm than good.

Why can't you multi-target these libraries for .NET Framework and .NET Core? I expect that you will need to do multi-targeting for number of libraries anyway for other reasons.

**Comment by AArnott** [comment]
> .NET Standard 2.0 is "done".

Yes, I understand that. I'm not proposing that you add it to `netstandard.dll`. I'm proposing you add it to the `System.Runtime.InteropServices` package.

> Why can't you multi-target these libraries for .NET Framework and .NET Core?

We need this attribute in the most basic of our SDK assemblies. If we can't target netstandard2.0 there, it will ripple to requiring hundreds of other assemblies to target net472 and netcoreapp3.0 instead of just one. The cost of doing that would be substantial.

We may need to multitarget some of our assemblies, but we'd like to keep that to a minimum, and we expect most of the ones that need it would *not* be reference assemblies, so it wouldn't cause any ripple effect.

**Comment by jkotas** [comment]
> I'm not proposing that you add it to netstandard.dll.

I do not understand. netstandard.dll describes what .NET Standard 2.0 is. If you want to add something to .NET Standard 2.0, it has to be added to netstandard.dll.

> you add it to the System.Runtime.InteropServices package.

`System.Runtime.InteropServices` package was published on https://www.nuget.org/packages/System.Runtime.InteropServices/ last time in 2016 (.NET Core 1.x era).

`System.Runtime.InteropServices.dll` is simply part of netcoreapp since .NET Core 2.0. It is no longer package.

**Comment by AArnott** [comment]
I hadn't noticed how old that package was. But could it be updated to include a ref\netstandard2.0 assembly that does nothing other than define this extra attribute, and a lib\net472 assembly that type forwards to mscorlib? 
I guess it's not that I care whether it's in netstandard.dll or not. It's that an assembly that targets netstandard2.0 ought to have access to this attribute.

I imagine I could do it myself by defining my own package with some assembly name in it but that defines the attribute and type forwards as appropriate on each runtime. So it seems like corefx could do it too, but hopefully without a special package and a special assembly load at runtime.

**Comment by AArnott** [comment]
I suppose another solution would be to go ahead and compile for just net472 and then package it up as if it were a netstandard2.0 assembly, essentially lying about the TFM so that nuget won't complain. Since we know all the applicable runtimes actually define the attribute it ought to be ok.

**Comment by jkotas** [comment]
You can even package it as net472 and use the [.NET Framework compatibility mode](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-0/) to reference it.

**Comment by AArnott** [comment]
If you mean that nuget is willing to restore a net472 package in a netstandard2.0 project, that's a non-starter IMO. It produces warnings that users should pay attention to rather than completely suppress, and you can't even suppress it for the one package unless you have a direct dependency to it. I'd rather lie within the package and claim it's a netstandard2.0 assembly since either way I'll be telling customers the package can be consumed by netstandard2.0 assemblies, so I might as well let the package indicate that too.

**Comment by danmosemsft** [comment]
> I hadn't noticed how old that package was. But could it be updated to include a ref\netstandard2.0 assembly that does nothing other than define this extra attribute, and a lib\net472 assembly that type forwards to mscorlib?

@jkotas would that work? 

cc @ericstj

**Comment by jkotas** [comment]
`System.Runtime.InteropServices.dll` ships inbox on .NET Framework. You would need to use assembly redirects to replace the inbox one with your NuGet OOB version to do this properly (unless you want to have orphaned references at runtime). It gets you into a hell of overriding inbox .NET Frameworks components with NuGet packages, like what we have been with System.Net.Http.

What would work is creating a brand new NuGet package that just has a tiny .dll with a single forwarder for System.Runtime.InteropServices.ImportedFromTypeLibAttribute. Anybody can make a glue package like this. It does not need to build in dotnet/runtime.

**Comment by danmosemsft** [comment]
@AArnott do you see any issues with creating such a type forward yourself as suggested?

**Comment by AArnott** [comment]
> System.Runtime.InteropServices.dll ships inbox on .NET Framework

@jkotas In that case, the `lib\net472` folder can just contain the `_._` file so that nothing actually ships with a .NET Framework targeted app. No need to replace inbox assemblies with the nuget package content then, right?

@danmosemsft Yes, we *could* do that. At the cost of an assembly load in VS, likely in the startup path, where we typically monitor assembly loads very closely.

**Comment by AArnott** [comment]
@jkotas (cont.)... oh, but I guess the .NET Framework in-box version of System.Runtime.InteropServices doesn't have the type forwarder for the attribute. So we *do* need to provide a runtime facade assembly for this. That would be fine, but it's a bummer that it would mean another assembly load in VS.

**Comment by danmosemsft** [comment]
I suggest to go this way for now and see whether it pops out of performance measurements you do when everything's working - I have no doubt there will be some things to fix.

**Comment by AArnott** [comment]
sounds good. I guess we can close this issue for now then.

**Comment by ericstj** [comment]
One hack would be to define an mscorlib assembly with this type in it.  That'll work on both .NETFramework and .NETCoreApp and not require an assembly at runtime.  (ducks to avoid rotten fruit)

**Comment by AArnott** [comment]
Nice. The strong name public key token would have to match, but I wouldn't have to worry about real signing since I can open source sign the ref assembly, and no runtime assembly is needed. :)

**Comment by ericstj** [comment]
We do something similar in our build to make winmd's work: https://github.com/dotnet/runtime/tree/master/src/libraries/mscorlib.WinRT-Facade/ref.

**Comment by AArnott** [comment]
FYI, I've written a .NETStandard2.0 library that adds the necessary attributes: https://github.com/AArnott/Nerdbank.NetStandardBridge
