### ISSUE TITLE
Add UTF8 to CharSet

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#17000]
The CharSet enumeration is used to specify how strings should be marshaled:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L3019-L3023

``` C#
public enum CharSet
{
    Ansi = 2,
    Unicode = 3,
}
```

`Unicode` specifies that UTF16 should be used, regardless of platform, but `Ansi` is interpreted differently based on platform: on Windows it's interpreted to mean the ANSI format, whereas on Unix it's interpreted to mean UTF8.  This means that on Windows we lack the ability to specify UTF8 as the marshaling, and more generally we lack the ability to specify UTF8 marshaling regardless of platform, making writing cross-platform managed components more difficult.

We should add a new UTF8 enum value:

``` C#
public enum CharSet
{
    Ansi = 2,
    Unicode = 3,
    UTF8 = 5,
}
```

that when used will cause the runtime's marshaling to be done with UTF8, which is the standard for modern services.

[Added-by-Yi]

We should also add a new corresponding UnmanagedType enum in UnmanagedType for UTF8 as well, for finer control and parity (between UnmanagedType and CharSet):
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices.PInvoke/ref/System.Runtime.InteropServices.PInvoke.cs

``` C#
public enum UnmanagedType
{
    LPUTF8Str = 0x30
}
```

And new Marshal helpers while we are at it:

``` C#
public class PInvokeMarshal
{
    public static string PtrToStringUTF8(System.IntPtr ptr);
    public static string PtrToStringUTF8(System.IntPtr ptr, int len);
    public static System.IntPtr StringToAllocatedMemoryUTF8(string s);
    public static System.IntPtr ZeroFreeMemoryUTF8(System.IntPtr s);
}
```

**Comment by lahma0** [comment]
After 5 long years, why has this feature still not been implemented? Is there some technical or policy-related issue that is holding this up or is the can just being kicked down the road as a result of other priorities? It appears that most of the necessary discussions concerning technical matters ended in 2017 yet its implementation was skipped over in .NET Core 3.0, then skipped over in .NET Core 3.1, it was then added as a "5.0 milestone", then several months later removed as a "5.0 milestone", and finally was added as a "Future milestone" (which I have to assume just means "something we are going to ignore and don't want to worry about any time in the foreseeable future"). Not having this functionality implemented unnecessarily complicates both cross-platform development and working with native libraries which use/expect UTF8 strings. UTF8 is the most common character encoding method in use and has been for a long time... Will this ever be implemented?

**Comment by jkoritzinsky** [comment]
@lahma0 due to a number of implementation difficulties, we have generally been exploring other improvements. We have been working on a [source-generated interop solution](https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator) (see https://github.com/dotnet/runtime/issues/4257#issuecomment-636478321 for a little more information) that should enable solutions similar to this issue without the [far reaching changes in the runtime itself](https://github.com/dotnet/coreclr/pull/18186) that the tentative implementation of this API had.

In the meantime, you can use `[MarshalAs(UnmanagedType.LPUTF8Str)]` for each string parameter/return value to get identical behavior to what a `CharSet.UTF8` API would provide on P/Invokes

**Comment by lahma0** [comment]
@jkoritzinsky I appreciate your very quick response and I apologize if my comment came across as a little bitter. While implementing these type of things might not look like that large of a hurdle to outsiders (such as myself), I know they tend to be much more nuanced/difficult and can create a cascade of other problems. I read about the plans for the source-generated interop stuff quite a while back but I haven't kept up to date on its progress. I will definitely check out the links your provided. Thanks again.

**Comment by stephentoub** [comment]
@dotnet/interop-contrib, have we decided not to do this?  If so, we should close it.

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub The plan was to wait till we get the source generator for DllImport productized and then close these issues. However, I suppose we could just point to the productization issue now.

**Comment by AaronRobinsonMSFT** [comment]
Closing this request in lieu of first-class support we are adding to the DllImport source generator. See https://github.com/dotnet/runtime/issues/60595
