### ISSUE TITLE
Add StringContent ctor providing tighter control over charset

### ISSUE THREAD

**Issue by guardrex** [dotnet/runtime#17036]
# API Approval - iteration 2

This is being submitted again for approval because we decided additional APIs were needed.
Copied from proposal in https://github.com/dotnet/runtime/issues/17036#issuecomment-843683612

```diff
public class StringContent
{
   public StringContent(string content);
+  public StringContent(string content, MediaTypeHeaderValue mediaType); // Already approved in iteration 1
   public StringContent(string content, Encoding encoding);
   public StringContent(string content, Encoding encoding);
   public StringContent(string content, Encoding encoding, string mediaType);
+  public StringContent(string content, Encoding encoding, MediaTypeHeaderValue mediaType); // NEW API proposal
}

public class MediaTypeHeaderValue
{
    public MediaTypeHeaderValue(string mediaType)
+   public MediaTypeHeaderValue(string mediaType, string charSet);  // NEW API proposal
}
```

Previous API approval is here: https://github.com/dotnet/runtime/issues/17036#issuecomment-579398933

# Original post

Consider the following code ...

``` c#
string contentType = "application/atom+xml";
string requestPayload = "some data";
var stringContent = new StringContent(requestPayload, Encoding.UTF8, contentType);
```

According to Wireshark, I'm seeing a POST using `HttpClient` with this ...

```
Content-Type: application/atom+xml; charset=utf-8
```

![capture](https://cloud.githubusercontent.com/assets/1622880/14647964/a1396782-0625-11e6-9c7a-3cdc1b92e4a2.PNG)

Shouldn't that `Content-Type` value just be ...

```
Content-Type: application/atom+xml
```

?? Confused, because something is choking my Azure Table Storage requests with ...

```
string stringToSign = 
    $"{requestMethod}\n\n{contentType}\n{dateInRfc1123Format}\n{canonicalizedResource}";
```

... and since `SharedKeyLite`, which only requires the date and resource, **works** with my `dateInRfc1123Format` and `canonicalizedResource`, I've sort of narrowed it down to the `contentType` of the request (shown above) not matching what I'm putting into the signature sting, namely just `application/atom+xml`.

**Comment by stephentoub** [comment]
How is the ctor taking `string content, MediaTypeHeaderValue mediaType` supposed to get the correct Encoding to use for getting the bytes from the string?

**Comment by benaadams** [comment]
Same way passing `null` or not giving the encoding does, by using `HttpContent.DefaultStringEncoding` (i.e. `Encoding.UTF8`); with the change of **not** adding `charset=utf-8` to the header

**Comment by stephentoub** [comment]
But it may already have a charset that's not utf8.

**Comment by benaadams** [comment]
Then you'd call one of the overloads that takes an Encoding?

Currently it assumes a utf8 encoding; if its unspecified anyway?

Also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset

> UTF-8 is now well-supported and the overwhelmingly preferred character encoding. 
> To guarantee better privacy through less configuration-based entropy, all browsers omit the
> Accept-Charset header: Internet Explorer 8+, Safari 5+, Opera 11+, Firefox 10+ and Chrome 27+ no longer send it.

**Comment by stephentoub** [comment]
> Then you'd call one of the overloads that takes an Encoding?

There isn't one that takes an Encoding and a MediaTypeHeaderValue.

**Comment by benaadams** [comment]
Ah; I understand; the `MediaTypeHeaderValue` may have a `string` charset but that doesn't help to determine the encoding (without some really slow parsing)

**Comment by stephentoub** [comment]
Exactly

**Comment by ericsampson** [comment]
So is the proposal:
```
public StringContent(string content, System.Text.Encoding encoding, MediaTypeHeaderValue mediaType);
var mediatype = new MediaTypeHeaderValue("application/json") { CharSet = string.Empty });
```
is it useful to have this for discoverability?
```
public StringContent(string content, System.Text.Encoding encoding, string mediaType, string charset)
```

**Comment by albigi** [comment]
hi all, is the above API part of a roadmap yet? is it safe to expect it in .NET 5 or will it be included in 6 only?
thanks

**Comment by karelz** [comment]
@albigi no, it is not part of our roadmap yet -- there are way too many more pressing things to do first.
.NET 5 is already out, we do not add new APIs in servicing. Currently it is not scheduled even for .NET 6. We are open to contributions though, if you are interested.

**Comment by DaveSenn** [comment]
I would like to create a PR for this.

After the API review stephentoub mentioned the problem with the "missing" encoding.
Is this still the desired API:
```c#
public StringContent(string content, MediaTypeHeaderValue mediaType)
```

Or should it be (as proposed by ericsampson ):

```c#
public StringContent(string content, System.Text.Encoding encoding, string mediaType, string charset)
```


..To avoid parsing the `CharSet` of the provided `MediaTypeHeaderValue ` and still be able to reuse the same `MediaTypeHeaderValue` instance, this could be an option:

```c#
public StringContent(string content, Encoding encoding, MediaTypeHeaderValue mediaType)
```

**Comment by scalablecory** [comment]
I'm fine with both of the APIs proposed in https://github.com/dotnet/runtime/issues/17036#issuecomment-722116733, but this needs to go back to API review before we can accept a PR for it.

**Comment by karelz** [comment]
Triage: We would like to know details about the user scenarios to make sure we understand which APIs we should add and why.
It was not clear if the current APIs are unusable, or if there is performance concern.

**Comment by DaveSenn** [comment]
@karelz sure np, thanks for the info.

**Comment by benaadams** [comment]
> We would like to know details about the user scenarios to make sure we understand which APIs we should add and why.

Want to be abe to add a `Content-Type` without a `charset` being added; which the current api doesn't make easy.

> It was not clear if the current APIs are unusable, 

Currenty unusable for this purpose

> or if there is performance concern.

Performance concern with the proposed api that was previously accepted as it introduces requirement for secondary parsing https://github.com/dotnet/runtime/issues/17036#issuecomment-640328557

**Comment by geoffkizer** [comment]
I think the current proposal is the following:

```csharp
public class StringContent
{
  public StringContent(string content, MediaTypeHeaderValue mediaType);
  public StringContent(string content, Encoding encoding, MediaTypeHeaderValue mediaType);
}
```

Is that correct? Any further suggestions/concerns?

@scalablecory also suggested the following, which seems like something we should do as well (or at least get approved to do in the future):

```csharp
public class MediaTypeHeaderValue
{
   public MediaTypeHeaderValue(string mediaType, string charSet);
}
```

**Comment by ericsampson** [comment]
Sounds good, it would definitely be nice to get the new constructor at the same time if possible :)

**Comment by ericsampson** [comment]
@scalablecory would it make sense to add a second new constructor to make the OP case easier/discoverable? 
```cs
public class MediaTypeHeaderValue
{
   public MediaTypeHeaderValue(string mediaType, string charSet);
   public MediaTypeHeaderValue(string mediaType);
}
```

**Comment by geoffkizer** [comment]
I marked this as 6.0 so it will get reviewed in the near future. That doesn't mean this is committed for 6.0.

**Comment by bartonjs** [comment]
Looks good as proposed.  We even discussed the casing on "charSet", and decided it's correct since it matches the existing property.

```diff
namespace System.Net.Http.Headers
{
    public class StringContent
    {
       public StringContent(string content);
+      public StringContent(string content, MediaTypeHeaderValue mediaType); // Already approved in iteration 1
       public StringContent(string content, Encoding encoding);
       public StringContent(string content, Encoding encoding);
       public StringContent(string content, Encoding encoding, string mediaType);
+      public StringContent(string content, Encoding encoding, MediaTypeHeaderValue mediaType); // NEW API proposal
    }
    
    public class MediaTypeHeaderValue
    {
        public MediaTypeHeaderValue(string mediaType)
+       public MediaTypeHeaderValue(string mediaType, string charSet);  // NEW API proposal
    }
}

**Comment by danmoseley** [comment]
Is there anyone in this issue interested in offering a PR?

**Comment by brianmed** [comment]
> Is there anyone in this issue interested in offering a PR?

I am currently coding up an attempt at creating the new APIs.

In addition, I will try a PR after done.

**Comment by stephentoub** [comment]
Implemented by https://github.com/dotnet/runtime/pull/63231
