### ISSUE TITLE
AssemblyLoadContext crash when collectible assembly use XmlSerializer

### ISSUE THREAD

**Issue by zengqinglei** [dotnet/runtime#1707]
Please see https://github.com/dotnet/runtime/issues/1388

I also encountered the same problem, is there a temporary solution?

**Comment by vitek-karas** [comment]
@zengqinglei I'm curious why you filed a new issue? Is there something different in your case to the issues mentioned in #1388?

**Comment by zengqinglei** [comment]
> @zengqinglei I'm curious why you filed a new issue? Is there something different in your case to the issues mentioned in #1388?

I didn't find a solution available from it. I want to ask again if there are any temporary solutions available. Can you guide me?

**Comment by vitek-karas** [comment]
(Sorry for the late reply)
AFAIK there are no available workarounds currently.

Closing this in favor of #1388 .
