### ISSUE TITLE
Cancellation behavior of ChannelReader<>.ReadAsync is unclear

### ISSUE THREAD

**Issue by GoldenCrystal** [dotnet/runtime#1710]
When calling `ChannelReader<>.ReadAsync`, one could reasonably expect that it would never consume an item from the channel if the operation is cancelled.
However, without being privy of implementation details, one could assume that some implementations do occasionally consume items when the operation is cancelled. (i.e. throws `OperationCanceledException`)
Should that be the case, it is easy for one to implement its own "safe" version of `ReadAsync` using `WaitToReadAsync` and `TryRead`, but I'd ideally want to avoid doing that unless strictly necessary.

One case where having such a guarantee would important, would be when using the channel to reuse a limited set of tokens across operations:
````csharp
// Create a channel of available tokens to use for async operations
var channel = Channel.CreateUnbounded<Token>();
channel.Writer.TryWrite(new Token(1));
channel.Writer.TryWrite(new Token(2));
channel.Writer.TryWrite(new Token(3));

var (reader, writer) = (channel.Reader, channel.Writer);

// Function that could be called externally, and which is implicitly concurrency-limited by the Channel.
async Task DoSomethingAsync(CancellationToken ct)
{
	// If the ReadAsync method ever throws while having consumed a token, we lose one concurrency slot.
	var token = await reader.ReadAsync(ct);
	try
	{
		await DoSomethingWithTheToken(token, ct);
	}
	finally
	{
		writer.TryWrite(token); // Should always succeed for unbounded channels
	}
}
````

It seems that the [default implementation of `ChannelReader<>.ReadAsync`](https://github.com/dotnet/runtime/blob/2c54bd95ab18962fa6a2c51ef9871d8b6f57d91b/src/libraries/System.Threading.Channels/src/System/Threading/Channels/ChannelReader.cs#L45) is indeed "safe" to use in that regard, but the method is `virtual` and could have different behavior in other implementations.
Notably, it is [overriden by `UnboundedChannel`](https://github.com/dotnet/runtime/blob/2c54bd95ab18962fa6a2c51ef9871d8b6f57d91b/src/libraries/System.Threading.Channels/src/System/Threading/Channels/UnboundedChannel.cs#L136), whose implementation seems to provide the same guarantees.

It would be great if we could either:

- Document that the intended behavior of `ReadAsync` is to never consume (lose) an item when `OperationCanceledException` is thrown.
- Or document that `ReadAsync` could have consumed (lost) an item if `OperationCanceledException` was thrown, and
  - Provide a list of known Channel implementations for which items will not be consumed when `OperationCanceledException` is thrown.
  - Or provide a non-optimized, non-virtual, version of `ReadAsync` that is strictly guaranteed to not consume an item upon cancellation

**Comment by stephentoub** [comment]
> the intended behavior of ReadAsync is to never consume (lose) an item when OperationCanceledException is thrown.

Correct
