### ISSUE TITLE
Are types VBCallSiteDelegate0…7 missing?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/runtime#17137]
There's code in src/Common/src/System/Linq/Expressions/Compiler/DelegateHelpers.Generated.cs defining and using public types `VBCallSiteDelegate0<T>` through `VBCallSiteDelegate7<T>`.

Because these are wrapped in `#if !FEATURE_COMPILE` they aren't active.

Since however the compiler and interpreter used to be mutually exclusive, `!FEATURE_COMPILER` used to entail `FEATURE_INTERPRET` perhaps this should in fact be wrapped with `#if FEATURE_INTERPRET` and hence lit up?

Has a type that was public in some contexts been removed due to this?

CC @VSadov @bartdesmet

**Comment by cston** [comment]
The types `VBCallSiteDelegate0<T>`, ..., `VBCallSiteDelegate7<T>` are `public` members of `internal class DelegateHelpers` so the types were never actually `public`. 

We will include or remove these types as part of handling `FEATURE_COMPILE` generally - see https://github.com/dotnet/runtime/issues/32878.
