### ISSUE TITLE
Add a way to wait for a Task without throwing and without allocating

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#17148]
At the moment there does not seem to be ay direct API that you can use to wait for a task to complete without throwing in case the task completes cancelled or faulted.

This forces using exceptions for control flow:

```
try {
 task.Wait();
}
catch (AggEx) { } //Do nothing.
```

This is ugly and _very_ slow. Exceptions seem to cost ~0.1ms of CPU time to process.

So if you are writing a port scanner using async IO you will find that you cannot scan more that 10k ports per second because the CPU is pegged from exception processing(!). Also, I don't know if exceptions scale across CPUs. I know that `ExceptionDispatchInfo` uses a global lock internally. So at least some of the processing does not scale at all.

It might not be too common to have many faulted tasks. But it is more likely to rely on a greater number of cancelled tasks.

I know of two workarounds:

```
Task.WhenAny(task); //params overload
task.CW(() => { }, ExecuteSynchronously).Wait();
```

Both allocate, add overhead and both make it unclear what you want to achieve.

Please add a simpler and faster way to wait for a task to complete regardless of the terminal state it ends up in.

The same problem exists with `await`. There is no direct way to wait for completion without throwing. Maybe `ConfigureAwait` can be extended with an `AwaitOptions` enum that has the values `IgnoreContext, NoThrow`.

**Comment by stephentoub** [comment]
This is possible now with ConfigureAwait as of https://github.com/dotnet/runtime/pull/87067, e.g.
```C#
task.ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing).GetAwaiter().GetResult();
```
While it's not the prettiest line of code ever, it gets the job done.  I don't see us adding an additional mechanism, so I'm going to close this out. Thanks.
