### ISSUE TITLE
Range check method

### ISSUE THREAD

**Issue by Entomy** [dotnet/runtime#1726]
This is more-or-less a minor convenience, but I believe it would be handy to have a method to check for existence of a value within a range. Since the introduction of [`Range`](https://docs.microsoft.com/en-us/dotnet/api/system.range) my desire for such a method has gone up, as it would be even more feasible.

Part of the problem is that this isn't just a matter of convenience. I am familiar with three different ways to do a range check.

~~~~csharp
Lower <= Value && Value <= Upper
~~~~
~~~~csharp
(Value - Lower) * (Upper - Value) >= 0
~~~~
~~~~csharp
(Value - Lower) <= (Upper - Lower)
~~~~

The first is the most obvious. It's what most programmers seem to write, and I've seen it in a huge number of projects. However, it is generally slower.

The latter two are far less obvious, but generally faster. I've been getting very mixed and inconsistent benchmark results between them, and a very limited amount of machines to test on, but I'd expect the lattermost to generally perform better, and has the distinct advantage of being precomputable in the case of repeated comparisons.

What I propose, is a new method who's implementation is the appropriate one of these, so that users don't need to concern themselves with "what is the most optimal range check". Not that this is a particularly common bottleneck by any means. But if you "just get" the faster implementation without having to concern yourself with the details, that's better.

The way I see it, there's two possible approaches for this method.

~~~~csharp
5.Within(1..10)
~~~~
~~~~csharp
(1..10).Contains(5)
~~~~

Exact naming doesn't matter, those were just the first things to come to mind.

**Comment by GrabYourPitchforks** [comment]
We almost certainly wouldn't expose this on the `Range` type, as `Range` instances are generally meaningless unless also bound to a _length_ value (such as from a collection). Additionally, `Range`'s inclusive / exclusive bounds behaviors would likely be confusing for most developers doing these checks.

There are lots of other internal helper methods in the Framework which perform these sorts of checks. They generally all follow the pattern of `Test(value, minInclusive, maxInclusive)`. Here's one example:

https://github.com/dotnet/runtime/blob/81bf79fd9aa75305e55abe2f7e9ef3f60624a3a1/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.cs#L34-L35

Would making a method like this public work for your scenario?

**Comment by Entomy** [comment]
It's not so much my scenario as much as noticing a lot of use of the inoptimal check. A named method seems like it would avoid any readability concerns while also providing the most optimal check and not requiring developers concern themselves with different approaches for something so trivial.

I don't particularly care how it's provided. Those were just some thoughts.

As it seems like these helpers exist in a few places (the one I saw was involving Unicode), wouldn't making it a first class API provide the option to slim down the runtime as well? I doubt this would shave off much, but it would at least consolidate 2 instances at this point.

**Comment by GrabYourPitchforks** [comment]
There was a separate tracking issue to have the JIT recognize these patterns and to optimize them without the need for a special `InRange` utility method. In particular it was because the pattern `if (value < 0 || value > someAllowedMax) { /* throw */ }` appears all over the place in the code base. I don't remember the tracking issue link offhand though.

**Comment by Entomy** [comment]
Oh, if that's the case then this should be a non-issue. I just figured it would be easier to do this way, but if the work is already in progress, then that solves the issue.
