### ISSUE TITLE
Restore the use of reflection methods with binding flags in Linq.Expressions

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#17298]
Reflection used to expose APIs like

``` C#
// allocates nothing in steady state
return type.GetMethod(name, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, ...);
```

In CoreFX the surface was reduced to minimum "GetMethods() forcing the following solution:

``` C#
       // allocates array with all methods each time
       MethodInfo[] methods = type.GetMethods();
       foreach (var method in methods)
       {
            if (method.IsStatic && method.Name == name)
          return methods;
       }
```

The second is wore performance-wise and we should be getting the original API with binding flags back.
Make sure that Linq.Expression is switched back to using that API

**Comment by cston** [comment]
> As such while there might be room for improvement in all or some of them, they can't be replaced by a single call to GetMethod() and unless I'm missing something this issue can be closed.

Agreed.
