### ISSUE TITLE
Restore the use of reflection methods with binding flags in Microsoft.VisualBasic

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#17301]
Reflection used to expose APIs like

``` C#
// allocates nothing in steady state
return type.GetMethod(name, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, ...);
```

In CoreFX the surface was reduced to minimum "GetMethods() forcing the following solution:

``` C#
       // allocates array with all methods each time
       MethodInfo[] methods = type.GetMethods();
       foreach (var method in methods)
       {
            if (method.IsStatic && method.Name == name)
          return methods;
       }
```

The second is wore performance-wise and we should be getting the original API with binding flags back.
Make sure that Microsoft.VisualBasic is switched back to using that API

**Comment by cston** [comment]
@VSadov, it looks like there are no uses of `Type.GetMethods()` in Microsoft.VisualBasic.Core currently. Please re-open if I've overlooked something. Thanks.
