### ISSUE TITLE
BinaryFormatter.Deserialize swallows the SecurityException after #35491 fix.

### ISSUE THREAD

**Issue by DmitryGaravsky** [dotnet/runtime#1733]
**Issue description:** 
After the source code changes merged in the context of https://github.com/dotnet/corefx/pull/40215 the `BinaryFormatter.Deserialize` method wraps the SecurityException in the SerializationException:

```cs
    try
    {
        var parser = new BinaryParser(serializationStream, reader);
        return reader.Deserialize(parser, check);
    }
    catch (SerializationException)
    {
        throw;
    }
    catch (Exception e) // issue here
    {
        throw new SerializationException(SR.Serialization_CorruptedStream, e);
    }
```
**Expected Behavior:**
According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.deserialize?view=netframework-4.8) the `BinaryFormatter.Deserialize` method must not swallow the SecurityException.
To resolve the current issue, you can re-throw the SecurityException:
```cs
    catch (SerializationException)
    {
        throw;
    }
    catch (SecurityException ) // fix
    {
        throw;
    }
```

**Affected .Net Version**: 
.Net Core 5+ (there is no issue in .Net Core 3.1 LTS and below).

**The impact**: Breaking Change.
This change breaks [Securing deserialization with custom SerializationBinder](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/controlling-serialization-and-deserialization-with-serializationbinder) approach.

**Comment by danmosemsft** [comment]
It does appear from the docs that SecurityException is special here.

**Comment by GrabYourPitchforks** [comment]
The `SecurityException` type is very specific to Code Access Security and shouldn't be thrown anywhere within a coreclr-based application. A serialization binder certainly shouldn't be throwing such an exception since it's not involved with Code Access Security.

What's the particular scenario broken here?

**Comment by DmitryGaravsky** [comment]
Hi guys, thank you for participating.
Let me describe a particular scenario in details.

As you know, the `SerializationBinder` can be used for securing deserializing some data from an untrusted source. The binder gives us an opportunity to inspect what types are being loaded in our application.

So we can have the following environment:
```
[Serializable]
public class UserSettings { /*...*/ }
```
This is how the handling of user setting looks like(this is a sample):
```
try {
    // deserializing from some untrusted source
    var userSettings = SafeBinaryFormatter<UserSettings>.Deserialize(untrustedBytes);
}
catch(SerializationException) {
    // bypass the error,  log an issue and continue with unchanged settings
}
catch(System.Security.SecurityException) {
    // raise panic and stop the execution
}
```
The `SafeBinaryFormatter` class is defined as follows:
```
sealed class SafeBinaryFormatter<T> {
    SafeBinaryFormatter() { }
    readonly static BinaryFormatter safeFormatter = new BinaryFormatter() { Binder = new SafeBinder() };
    public static T Deserialize(byte[] bytes) {
        using(MemoryStream ms = new MemoryStream(bytes))
            return (T)safeFormatter.Deserialize(ms);
    }
    sealed class SafeBinder : SerializationBinder {
        public override Type BindToType(string assemblyName, string typeName) {
            if(typeof(T).FullName == typeName && typeof(T).Assembly.FullName == assemblyName)
                return typeof(T);
            throw new NonTrustedTypeDeserializationException(typeName);
        }
    }
    sealed class NonTrustedTypeDeserializationException : System.Security.SecurityException {
        const string messageFormat = "The {0} type is not trusted and therefore is not deserialized due to security reasons.";
        internal NonTrustedTypeDeserializationException(string typeName)
            : base(string.Format(messageFormat, typeName)) {
        }
    }
}
```

With the change, I have mentioned in the context of this issue, the code above is totally broken. Due to the changes the real execution flow is changed. **Our unit tests are warned about this immediately** (yes, we maintain unit test for all the released and preview environments like .net core 5 in our codebase). Thus **it is an important breaking change for us** from our point of view.

At this moment of time, we should decide **whether to add some deep handling of SerializationException on our side** or this is real BC in .net codebase that will be fixed in the release.
Thank you for understanding.

**Comment by GrabYourPitchforks** [comment]
> As you know, the `SerializationBinder` can be used to safely deserialize some data from an untrusted source.

This is not an accurate statement.

The `BinaryFormatter.Deserialize` method must not be called with untrusted data. [Our docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.deserialize) are clear on this: "Calling this method with untrusted data is a security risk. Call this method only with trusted data." There's no escape clause which says that using a `SerializationBinder` allows calling this method with untrusted data. If you do come across documentation stating such please let me know because it's something that needs immediate correction!

Meanwhile I'll mark this as a breaking change so that it bubbles up to the right folks. Thanks for describing your scenario!

**Comment by DmitryGaravsky** [comment]
>If you do come across documentation stating such please let me know because it's something that needs immediate correction!
There is nothing incorrect in the documentation and we'll be the happiest developers in the world if our programs work only in a trusted environment. But in the real world, we have to deal with various data from different sources (databases/communication protocols/file formats/external APIs). The solutions like above appear only because we clearly understand all the risks and do our best to guarantee the required security level for our customers. That is why our customers pay for our work ;-)

>Meanwhile I'll mark this as a breaking change so that it bubbles up to the right folks.
Happy to hear and will stay tuned, thank you!

**Comment by GrabYourPitchforks** [comment]
This will be captured in the breaking change document (see https://github.com/dotnet/docs/issues/19604). Thank you for reporting the issue!
