### ISSUE TITLE
Azure DevOps error: Unable to locate dotnetcore on build agent.

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#1736]
It looks like many/most/all pipelines fail with multiple cases of
```
Unable to locate dotnetcore on build agent.
```
in "CoreCLR Product Build Linux_musl x64 checked - Component Detection (auto-injected by policy)" and "Libraries Build Linux_musl x64 Release - Component Detection (auto-injected by policy)"

E.g.:
https://dev.azure.com/dnceng/public/_build/results?buildId=482702&view=results

**Comment by jashook** [comment]
Have not seen this in a while, if it happens again we can re-open another issue.

**Comment by wmpauli** [comment]
@jashook , I'm experiencing this issue, after following these installation instructions: https://gist.github.com/richlander/467813274cea8abc624553ee72b28213 (installed it in /usr/local/dotnet instead of /usr/share/dotnet, but that shouldn't be and issue, right?)
