### ISSUE TITLE
Issue with QuoteSnippetStringCStyle when parsing '\u0085' character

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#1740]
Another line needs to be added after [this](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.cs#L127), which would be
```cs
case '\u0085':
```
This is because it is recognised as a newline character in C# ([see here](https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md)), which cannot be in literal strings.
If the CSharpCodeGenerator class was used to make code with a string in it that has [U+0085](http://www.unicode-symbol.com/u/0085.html) in it, it would generate invalid C# code.
NB: this is also an issue on the .NET Framework ([see here](https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/System/compmod/microsoft/csharp/csharpcodeprovider.cs#L450))

I would like to implement this change, thanks!

**Comment by GrabYourPitchforks** [comment]
Thanks for reporting this! Your reasoning seems sound to me. Feel free to look through our contribution guidelines then send a PR with your proposed fix. Remember also to update any appropriate unit tests to validate your change

**Comment by hamarb123** [comment]
@GrabYourPitchforks, what sort of a test would I need, a test that checks if it can parse a generated c# file, with a string with some newline characters maybe? Also, where should I put the test?
Thank you.

**Comment by GrabYourPitchforks** [comment]
That looks like a fine test. The area owners might have further feedback regarding naming once you submit the PR.

**Comment by hamarb123** [comment]
The PR is at #1853

**Comment by hamarb123** [comment]
This has now been solved, see PR #1853.
