### ISSUE TITLE
Optimize BigInteger "DataTip" speed

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#17453]
For very big BigIntegers the Visual Studio DataTip (the thing that appears when hovering over a variable with the mouse) takes a long time to load. I assume that's because the ToString processing takes too long.

The result is not visible anyway because it is aborted by a timeout as it seems.

Can the DataTip be made faster for super long BigIntegers? Maybe it could just show the first and last 20 digits instead of all digits. It's still possible to see all digits by calling ToString using the debugger.

Maybe the output could be `$"{firstDigits} ... {lastDigits} ({totalDigits} digits in total, {byteCount} bytes}"`. That would be useful to both see the data and to get a feel for memory consumption.

The ToString output would stay unchanged.

**Comment by tannergooding** [comment]
It might be better to do `1.234E+123`. It would then be in a format similar too how float/double display large values.
