### ISSUE TITLE
Need to update ActiveIssue uses to be unambiguous 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#1746]
The uses of [ActiveIssue](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/filtering-tests.md#activeissueattribute) today which use a single `int` are becoming ambiguous in the runtime repository. Before consolidation the `int` referred to an issue id within the corefx repository. Now though the id can refer to an issue in runtime or corefx. The ambiguity will grow once all of the issues migrate from corefx, coreclr and core-setup as there will be a significant number of overlapping ids.

There are two approaches we could take to this:

- Post issue migration update all uses to point to the new issue id in runtime. From that point going forward all ids would be assumed to point to runtime only.
- Change the issues to use the `string` constructor and use the full URL of the issue instead.

**Comment by danmosemsft** [comment]
I’d prefer keeping numbers for this repo, and URLs otherwise. That is compact, unambiguous and generally what we did before, I think.

To fix up existing ones we would need  to find the mapping. I guess it would not be hard to  use a script to navigate to the old URL and see where it redirects to. Perhaps CTI could help with the edits.

**Comment by jaredpar** [comment]
This should be fairly scriptable. We had a similar issue in Roslyn ~4 years ago. In that case though there were roughly four different possible sources for the issues. Took a couple hours but eventually were able to script an update to all our tests.

https://github.com/dotnet/roslyn/commit/e4989ef1d1ad18de41c4bfc6ccc390c48a9d0f5c

**Comment by akoeplinger** [comment]
I'd prefer removing the int constructor and force the URI. It's much easier to keep those valid while migrating through different issue tracking systems.
