### ISSUE TITLE
How do I use Span like a pointer?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#1750]
unsafe:
```C#
string str = "1234";
fixed (char* c = str)
{
      var temp = *(ulong*)(c + 0);
}
```
How do I use Span like a pointer?

span:
```C#
string str = "1234";
var span = str.AsSpan();
var temp = *(ulong*)(span);  //????
```

**Comment by GrabYourPitchforks** [comment]
You can pin a `Span<T>` just like you can pin a `T[]` or a `string`.

Example:

```cs
char[] chars = new char[] { '1', '2', '3', '4' };
fixed (char* pch = chars)
{
    // use 'pch' here
}

Span<char> span = chars.AsSpan();
fixed (char* pch = span)
{
    // use 'pch' here
}
```

Note: pinning a `string` instance results in a null-terminated `LPCWSTR`. Pinning a `Span<T>` or a `T[]` is not guaranteed to be null-terminated. This is particularly important if you're using pointers for p/invoke purposes.

**Comment by NMSAzulX** [comment]
@GrabYourPitchforks  @jkotas   Thank you!

**Comment by jkotas** [comment]
Also, you may consider using the helper methods on MemoryMarshal to achieve what you have shown above. Unlike raw pointer access, the helper methods on MemoryMarshal will bounds check for you and avoid buffer overruns if you have bug in your code.

```csharp
char[] chars = new char[] { '1', '2', '3', '4' };
var temp = MemoryMarshal.Read<Int64>(MemoryMarshal.AsBytes(chars.AsSpan()));
```

**Comment by NMSAzulX** [comment]
@jkotas  Thanks. I tried another way :
```C#
var bytes = MemoryMarshal.AsBytes(str.AsSpan());
ref var addr = ref Unsafe.AsRef(bytes[0]);
var temp = Unsafe.ReadUnaligned<int>(ref Unsafe.Add(ref addr, 4);
```
This method is still not as good as using point directly.  

|                      Method |     Mean |     Error |    StdDev |
|---------------------------- |---------:|----------:|----------:|
|              IntPtr | 3.285 ns | 0.1030 ns | 0.2218 ns |
|              Unsafe | 4.340 ns | 0.1204 ns | 0.1566 ns |

> By the way, I wrote a "Dynamic Search Tree" algorithm, which can optimize the performance of the dictionary, but requires roslyn to do dynamic compilation, the effect is very good. I don't know if the NetCore Team has a plan for this.  

|     Method |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio | RatioSD | Allocated |
|----------- |----------:|----------:|----------:|----------:|----------:|----------:|------:|--------:|----------:|
|     Origin |  2.304 ns | 0.0421 ns | 0.0352 ns |  2.296 ns |  2.235 ns |  2.370 ns |  1.00 |    0.00 |      - |
|       Dynamic Search Tree|  5.127 ns | 0.1415 ns | 0.1573 ns |  5.094 ns |  4.803 ns |  5.548 ns |  2.23 |    0.08 |         - |
|    Dynamic |  9.252 ns | 0.2176 ns | 0.2905 ns |  9.106 ns |  8.841 ns |  9.860 ns |  4.05 |    0.18 |        - |
| Dictionary | 20.597 ns | 0.2650 ns | 0.2479 ns | 20.654 ns | 20.194 ns | 20.982 ns |  8.93 |    0.21 |        - |

**Comment by jkotas** [comment]
Interesting approach. We do not plan to use dynamic compilation for the core Dictionary type.

**Comment by NMSAzulX** [comment]
Yeah. Of course！ This idea can be used as an extension of the dictionary.

```C#
public static HashCache<TKey, TValue> HashTree<TKey, TValue>(this IDictionary<TKey, TValue> dict)
{
     return new HashCache<TKey, TValue>(dict);
}




public static FuzzyCache<TValue> FuzzyTree<TValue>(this IDictionary<string, TValue> dict)
{
     return new FuzzyCache<TValue>(dict);
}



public static PrecisionCache<TValue> PrecisionTree<TValue>(this IDictionary<string, TValue> dict)
{
      return new PrecisionCache<TValue>(dict);
}
```

> and so on: https://github.com/night-moon-studio/DynamicCache/blob/master/test/UTProject/HashTest.cs

Thank you for your answer today.
