### ISSUE TITLE
Interruptable read on a pipe

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#17513]
Challenge: Try reading from System.Console.StandardInput.BaseStream without blocking a thread such that another thread can interrupt the read without resorting to P/Invoke.

ReadAsync does indeed return immediately, but the Task's cancellation token isn't bound to the task thanks to "Tuple.Create(this, buffer, offset, count), CancellationToken.None, " in Stream.cs and no descendant path to WindowsConsoleStream attempts to fix this. This means that attempting to gather the completion result wedges the thread.

Both the Windows and the Unix APIs are capable of solving this, but each do so completely differently. I've got thousands upon thousands of lines of code written attempting this problem and still more to go before it works at all.

**Comment by carlossanlop** [comment]
Triage:
@jhudsoncedaron if you can provide a small repro illustrating the problem, we can take a look at this in more detail. For now, we are closing it.
