### ISSUE TITLE
Proposal: support reference semantics for IComparable<T>, IEquatable<T>

### ISSUE THREAD

**Issue by BenjaminGopp** [dotnet/runtime#1755]
Now that we have reference semantics for structs, it would be nice if we got specialized interfaces / types that support these semantcis, e.g. for comparision and equality.

### e.g. sorting
Sorting in .NET requires the IComparable<T> or IComparer<T> interface. Classes are passed as reference to the CompareTo method, but structs are copied!

With a new interface IStructComparable<T>, structs are passed by reference.
This should give sorting of a list of structs a nice speed up. Especially for large structs.

``` csharp
  interface IStructComparable<T> where T : struct
  {
    int CompareTo(in T other);
  }
```
``` csharp
  public struct LargeStruct : IComparable<LargeStruct>, IStructComparable<LargeStruct>
  {

    private readonly double A, B, C, D, E;


    int IStructComparable<LargeStruct>.CompareTo(in LargeStruct other) //no copy
    {
      return 0;
    }

    int IComparable<LargeStruct>.CompareTo([AllowNull] LargeStruct other) //copy
    {
      return 0;
    }
  }
```
### other interface suggestions
``` csharp
  interface IStructEquatable<T> where T : struct
  {
    bool Equals(in T other);
  }
```

``` csharp
  interface IStructComparer<T> where T : struct
  {
    int Compare(in T x, int T y);
  }
```

**Comment by DaZombieKiller** [comment]
Now that we have default interface implementations, wouldn't it be better to just extend `IEquatable` and `IComparable` directly?

```CSharp
using System.Diagnostics.CodeAnalysis;

namespace System
{
    public interface IEquatable<T>
    {
        bool Equals([AllowNull] T other);
        bool Equals(in T other) => Equals(other);
    }

    public interface IComparable<in T>
    {
        int CompareTo([AllowNull] T other);
        int CompareTo(in T other) => CompareTo(other);
    }
}
```

**Comment by jkotas** [comment]
> This should give sorting of a list of structs a nice speed up. Especially for large structs.

And make sorting of a list of small structs significantly slower?

**Comment by BenjaminGopp** [comment]
> And make sorting of a list of small structs significantly slower?
The Jitter can certainly optimize that!

**Comment by jkotas** [comment]
How?

If you ask for the structs to be passed by reference (e.g. using `in`), the JIT has to respect it and it significantly reduces optimizations that the JIT can perform.
