### ISSUE TITLE
Add static hash helper methods

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#17590]
_Edit by @GrabYourPitchforks on 20 Jan 2020_: Formal API proposal written at https://github.com/dotnet/corefx/issues/9369#issuecomment-576445733.

Computing a hash code currently requires this code:

```
        byte[] hashBytes;
        using (var hashAlgo = SHA256.Create())
            hashBytes = hashAlgo.ComputeHash(bytes);
```

Or the more awkward `HashAlgorithm.Create("SHA256")`.

This code is alright. It's not the end of the world. But I think it should be slimmer than that:

```
var hashBytes = SHA256.ComputeHash(bytes);
```

Benefits:
1. This is more terse.
2. It's an expression as opposed to a statement. That makes it more composable. It can be a subexpression for example in a LINQ query.
3. No way to forget resource cleanup or mess up code quality otherwise.
4. `SHA256.ComputeHash` can look at it's input size and dynamically pick the fastest implementation. I found the following to be optimal through testing on Windows x64: `estimatedDataLength <= 512 ? new SHA1Managed() : HashAlgorithm.Create("SHA1")`. Apparently, using the Windows crypto API has quite some per-hash cost.

I request that static helper method be added to the framework. This seems like an attractive case for a community contribution.

----
Proposal:

Using this pattern on all of the HashAlgorithm-derived types that are not KeyedHashAlgorithm-derived types (MD5, SHA1, SHA256, SHA384, SHA512):

```C#
public partial class SHA256
{
    public static byte[] Hash(byte[] source) => throw null;
    public static byte[] Hash(ReadOnlySpan<byte> source) => throw null;
    public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;
    public static bool TryHash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination, out int bytesWritten) => throw null;
}
```

**Comment by bartonjs** [comment]
Approved as proposed

```C#
public partial class MD5
{
    public static byte[] Hash(byte[] source) => throw null;
    public static byte[] Hash(ReadOnlySpan<byte> source) => throw null;
    public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;
    public static bool TryHash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA1
{
    public static byte[] Hash(byte[] source) => throw null;
    public static byte[] Hash(ReadOnlySpan<byte> source) => throw null;
    public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;
    public static bool TryHash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA256
{
    public static byte[] Hash(byte[] source) => throw null;
    public static byte[] Hash(ReadOnlySpan<byte> source) => throw null;
    public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;
    public static bool TryHash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA384
{
    public static byte[] Hash(byte[] source) => throw null;
    public static byte[] Hash(ReadOnlySpan<byte> source) => throw null;
    public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;
    public static bool TryHash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA512
{
    public static byte[] Hash(byte[] source) => throw null;
    public static byte[] Hash(ReadOnlySpan<byte> source) => throw null;
    public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;
    public static bool TryHash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination, out int bytesWritten) => throw null;
}
```

**Comment by vcsjones** [comment]
> `public static int Hash(ReadOnlySpan<byte> source, ReadOnlySpan<byte> destination) => throw null;`

I assume `destination` should be `Span<byte>`?

**Comment by bartonjs** [comment]
Grumble, grumble, copy pasta. Fixed.

**Comment by vcsjones** [comment]
@bartonjs okay, one more. There is already a member on `HashAlgorithm` named [`Hash`][1].

The `Hash` methods will hide that property. (CS0108). We either need to hide (`new` keyword) or come up with a new name. 

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.hash?view=netcore-3.1

**Comment by bartonjs** [comment]
Well.  That's a bad job on my part.

Any better name suggestion?  I don't think the name masking will work, because of the legacy interaction with ICryptoTransform.

**Comment by vcsjones** [comment]
>  I don't think the name masking will work

Regardless of working or not, it is also a breaking change:

```c#
public static void Main() {
    var f = new Frob();
    _ = f.Hash;
}

public class Foo {
    public byte[]? Hash { get; set; }
}

public class Frob : Foo {
    // Uncomment and `Main` will not compile anymore.
    //public new byte[] Hash(byte[] cat) => Array.Empty<byte>();
}
```

> Any better name suggestion?

... nothing with precedent. We could, though it's somewhat redundant, add the hash name?

```c#
public byte[] HashSHA256(...);
public bool HashMD5(...); // or whatever the "right" casing is.
```

There's also `Digest`, but that hasn't been used as a verb in the framework as far as I can see, and feels like more using new terminology that might confuse developers just to avoid a name collision.

The alternative is we put the methods on a different class or new class. `IncrementalHash` seems wrong because it isn't... incremental... I don't think there is anything existing there would work.

I'm starting to warm up to the idea of a new class: during API review I asked 'why not on `HashAlgorithm`?' to which you gave a good answer about inheritance. But we still have that problem on `SHA256` (and others) since they are also abstract. Consider a developer that has done:

```c#
public sealed class MySHA256 : SHA256
{
    // impl
}
```

Calling `MySHA256.Hash(someBytes)` will call our implementation, not theirs. This wouldn't exactly be a new problem, as the `Create` factory methods exhibit the same problem.

So this was a very long way of me to say `¯\_(ツ)_/¯`

**Comment by vcsjones** [comment]
re-reading through the proposal, I will now suggest / endorse:

```c#
namespace System.Security.Cryptography {
    public static class Hash {
        public static byte[] HashMD5(byte[] source) => throw null;
        public static byte[] HashMD5(ReadOnlySpan<byte> source) => throw null;
        public static int HashMD5(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
        public static bool TryHashMD5(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
    
        public static byte[] HashSHA1(byte[] source) => throw null;
        public static byte[] HashSHA1(ReadOnlySpan<byte> source) => throw null;
        public static int HashSHA1(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
        public static bool TryHashSHA1(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;

        public static byte[] HashSHA256(byte[] source) => throw null;
        public static byte[] HashSHA256(ReadOnlySpan<byte> source) => throw null;
        public static int HashSHA256(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
        public static bool TryHashSHA256(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;

        public static byte[] HashSHA384(byte[] source) => throw null;
        public static byte[] HashSHA384(ReadOnlySpan<byte> source) => throw null;
        public static int HashSHA384(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
        public static bool TryHashSHA384(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;

        public static byte[] HashSHA512(byte[] source) => throw null;
        public static byte[] HashSHA512(ReadOnlySpan<byte> source) => throw null;
        public static int HashSHA512(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
        public static bool TryHashSHA512(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
    }
}
```

**Comment by vcsjones** [comment]
And, while I'm at it, can throw in bonus API:

```c#
namespace System.Security.Cryptography {
    public static class Hash {
        public static byte[] HashName(HashAlgorithmName hashAlgorithmName, byte[] source) => throw null;
        // etc
    }
}
```

and maybe we don't even need the `MD5`, `SHA1`, dedicated methods anymore.

**Comment by bartonjs** [comment]
A standalone Hash class, using the algorithm names as verbs, would certainly solve the problem in-framework, but doesn't create an extensible pattern, so there's nothing for someone to really follow if they wanted to "bring back" RIPEMD160, or wanted to provide historical algorithms the framework never had, like MD4.

> you gave a good answer about inheritance. But we still have that problem on SHA256 (and others) since they are also abstract.

Assuming that the derived type of SHA256 is still implementing SHA256, there's room for "but I thought SHA256CryptoServiceProvider.SomeVerb(data) used CAPI...", but it's always SHA256.  That's better (in my head) than "SHA256.SomeVerb(algName, data)" actually being MD5.  (You could also say the same thing about RSACryptoServiceProvider, but we made that type "just (mostly) work" on non-Windows, showing sometimes "right answer" is good enough.)

"OneShot" is what I'd call this functionality for an internal method, or perhaps "StaticHash".  "OneShot" doesn't feel right for public API, and while "StaticHash" is still a little on-the-nose it does avoid combining "Hash" from the instance members and type name with "Digest" as the synonym verb.

Another reasonable thing is "StatelessHash", separating it from ComputeHash which has a stateful mix with the object (Disposed or not, and poor interaction with the TransformBlock method).  (Or "HashStateless", but that feels less good in my gut)

**Comment by vcsjones** [comment]
Okay, if we want to stick with statics on existing algs, I am not terribly concerned with the name. Could do any of yours, or `SingleHash`, `InstantHash`, etc. or just throw the word `Data` in there somewhere, `HashData`. That might have the benefit of being generic enough that folks don’t read too much in to the name.

**Comment by GSPP** [comment]
Maybe `HashBuffer`? That would signal that a *single* buffer is being processed. This is in contrast to the other more general APIs (`TransformBlock`, ...).

Alternatives: `HashBytes`, `GetHash`.

**Comment by bartonjs** [comment]
We discussed this again, and accepted HashData.

```C#
public partial class MD5
{
    public static byte[] HashData(byte[] source) => throw null;
    public static byte[] HashData(ReadOnlySpan<byte> source) => throw null;
    public static int HashData(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
    public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA1
{
    public static byte[] HashData(byte[] source) => throw null;
    public static byte[] HashData(ReadOnlySpan<byte> source) => throw null;
    public static int HashData(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
    public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA256
{
    public static byte[] HashData(byte[] source) => throw null;
    public static byte[] HashData(ReadOnlySpan<byte> source) => throw null;
    public static int HashData(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
    public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA384
{
    public static byte[] HashData(byte[] source) => throw null;
    public static byte[] HashData(ReadOnlySpan<byte> source) => throw null;
    public static int HashData(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
    public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
}
public partial class SHA512
{
    public static byte[] HashData(byte[] source) => throw null;
    public static byte[] HashData(ReadOnlySpan<byte> source) => throw null;
    public static int HashData(ReadOnlySpan<byte> source, Span<byte> destination) => throw null;
    public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten) => throw null;
}
```

**Comment by vcsjones** [comment]
I think I can squeeze this one in over the weekend.

**Comment by bartonjs** [comment]
Regarding the suggestion of "HashBytes": there are existing methods named (Try)HashData... admittedly, they're all protected; but there aren't any named "HashBytes", so "HashData" is more platform-consistent.

**Comment by bartonjs** [comment]
> I think I can squeeze this one in over the weekend.

If you want to PAL through to native one-shots, that'd be best.  If you want to go quicker with `[ThreadStatic]`, that's fine too.

**Comment by vcsjones** [comment]
> If you want to PAL through to native one-shots, that'd be best

That's the intention.

We don't really have a native PAL for CNG (do we?) and CNG's one-shot `BCryptHash` is Windows 10+, so maybe both?

**Comment by bartonjs** [comment]
> We don't really have a native PAL for CNG (do we?) 

Well, we have the PAL (split build for the OS), we just don't carry a native shim.

**Comment by vcsjones** [comment]
New APIs are in. Work left to be done:

- [ ] Cache results of `EVP_sha1`, `EVP_sha256`, etc in `HashAlgorithmToEvp` to avoid a P/Invoke call.
- [ ] Optimize CNG implementation to not allocate a stateful hash object.
