### ISSUE TITLE
No PartConventionBuilder.Export(Type) method

### ISSUE THREAD

**Issue by dkharlap** [dotnet/runtime#17613]
There is no PartConventionBuilder.Export(Type) method, only PartConventionBuilder.Export&lt;Type&gt;(), thus there is no way to export a dependency unless its interface or class is known at compile time. At the same time, there are methods like:

CompositionHost.GetExport(Type)
ConventionBuilder.ForType(Type)

etc., so I assume the PartConventionBuilder limitation is not there by design? Besides, as far as I can see in the source code, this is going to be really easy to add new PartConventionBuilder.Export(Type) method, as it's pretty much there already.

Thank you!

**Comment by ericstj** [comment]
Closing as there is no API proposal in 4 years.  If you'd like to reopen please go ahead and fill in a proposal.
