### ISSUE TITLE
Crossgen2 incorrectly takes Size into account for Auto layout

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#1770]
Should return 4 but returns 16.

```csharp
using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Auto, Size = 16)]
    struct GUID
    {
        private int align;

        static unsafe int Main()
        {
            return sizeof(GUID);
        }
    }
```

**Comment by tannergooding** [comment]
We should update the documentation of `StructLayoutAttribute` to explicitly call out the cases where `Size` is ignored (if it is less than the actual size of the struct and apparently for `LayoutKind.Auto` as well).

**Comment by briansull** [comment]
In your example above you should name your arbitrary struct something other than GUID.
As the size of the well known Windows type "GUID" is actually 16 bytes.

**Comment by MichalStrehovsky** [comment]
I just copy pasted the name from a struct in the loader test mentioned in #1763 when I was playing with it. That struct is not a guid either but at least it's 16 bytes.

We can rename it for the regression test to Foo, in line with good naming practices.

**Comment by jkotas** [comment]
> We should update the documentation of `StructLayoutAttribute` to explicitly call out the cases where `Size` is ignored 

It is never ignored (as long it is valid). It is always respected for the unmanaged layout of the type. The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute?view=netframework-4.8) says that `StructLayoutAttribute` controls the unmanaged layout of the type, and that it controls the managed layout only when the type is blittable.

**Comment by MichalStrehovsky** [comment]
> Would the above case not qualify as blittable?

It doesn't qualify because it doesn't have layout (only Sequential/Explicit types "have layout").

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/vm/class.h#L2301-L2308

**Comment by tannergooding** [comment]
Wouldn't that mean that `Size` is effectively ignored/invalid on `StructLayout=Auto` then?

Auto can't be marshalled and therefore can't have an unmanaged size, it also isn't blittable and therefore won't be impactful on the managed side either.

**Comment by jkotas** [comment]
> Wouldn't that mean that Size is effectively ignored/invalid on StructLayout=Auto then?

Right, it is useless on StructLayout=Auto, just like all other managed/unmanaged marshaling directives.
