### ISSUE TITLE
List.Contains, IndexOf should accept a [MaybeNull] parameter

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/runtime#1775]
Both of these methods work fine with null values, and it is perfectly acceptable to check if a list of not null items contains an object which might be null.

I would suggest marking the parameters to both these methods with [MaybeNull].

**Comment by jnm2** [comment]
Other collection types like ImmutableArray would be similar.

**Comment by GrabYourPitchforks** [comment]
@stephentoub Related to a discussion we had the other day.

Is the idea that if you want to allow nulls, the application should declare the field of type `List<MyObject?>` instead of `List<MyObject>`, and all methods which accept type parameter _T_ as an argument implicitly become _\[MaybeNull\] T_?

**Comment by stephentoub** [comment]
The `List<T>` implementation allows null values in all of its methods, not just IndexOf and Contains, but also Add, Remove, etc.  The nullable reference type annotations are layered on top of this and allow you to choose the domain for your values and whether the language warns you about nullable values or not.  If you define your list as `List<string?>`, then the compiler won't warn if you pass a value that may be null to Add/Remove/IndexOf/Contains/etc.   If you instead define your list as `List<string>`, then the compiler will warn if you pass a value that may be null to Add/Remove/IndexOf/Contains.  This is the nature and design of nullable reference types.  We don't plan on special-casing some of the methods on `List<T>` to disregard the developer's intention as expressed in how they specify the generic.

**Comment by jnm2** [comment]
> We don't plan on special-casing some of the methods on List<T> to disregard the developer's intention as expressed in how they specify the generic.

In the case where I ran into this, the generic type argument was inferred.

```cs
void M(IEnumerable<string> foo)
{
    if (foo is null)
        throw new ArgumentNullException("...", nameof(foo));

    var list = foo
        .Distinct(...)
        .ToList();

    if (list.Contains(null!))
        throw new ArgumentException("...", nameof(foo));

    switch (list.Count)
    {
        // ...
}
```

This is not a case of disregarding the developer's intention any more checking public non-nullable reference parameters for null. (https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062)

**Comment by jnm2** [comment]
@stephentoub 

> The `List<T>` implementation allows null values in all of its methods, not just IndexOf and Contains, but also Add, Remove, etc.

`Remove` should be treated the same as `IndexOf`, but `Add` is not the same. Adding `null` to a list would risk exposing `null` from subsequent calls even though T is non-nullable.

> We don't plan on special-casing some of the methods on List<T> to disregard the developer's intention as expressed in how they specify the generic.

In the case where I ran into this, the generic type argument was inferred.

```cs
void M(IEnumerable<string> foo)
{
    if (foo is null)
        throw new ArgumentNullException("...", nameof(foo));

    var list = foo
        .Distinct(...)
        .ToList();

    if (list.Contains(null!))
        throw new ArgumentException("...", nameof(foo));

    switch (list.Count)
    {
        // ...
}
```

This is not a case of disregarding the developer's intention any more than checking public non-nullable reference parameters for null. (https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062)

Is what you're saying that I should cast to to `List<string?>` before calling `Contains`? I wouldn't want the variable type of `list` to be `List<string?>` or I'd have to silence more warnings below in the code that assumes no elements are null, since Roslyn does not understand `list.Contains(null)` to be a null check.

**Comment by YairHalberstadt** [comment]
@stephentoub 

I really do not understand this logic.

It's obvious why `add`ing a null reference to a not null list is a bad idea, but why can't I check if a not null list contains a maybe null value?

Essentially `Contains` is contravariant in nature. It would probably be a bad idea to make it accept object because of boxing and because it would not warn if you checked whether a string list accepted eg. a stream.

However with a nullable reference type neither of these objections apply. On the other hand backwards compatibility will require checking if a not null list contains maybe null items.

**Comment by stephentoub** [comment]
Reopening as the discussion continues...

I understand the covariance argument.  But from my perspective, the developer has said that anywhere T shows up, it should be non-nullable, and the compiler is then warning that nulls are being used in a domain where they weren't intended.  To me it's as simple as that.  Even if my action involving a null won't corrupt the collection, I'm still using a value that is explicitly stated as not being possible, and the compiler is saying "ummm... do you really know what you're doing?"  If you do, you can answer it with a `!`.  If I have a list of integers and I try to use Contains with a double, it won't let me.  If I have a list `List<ArgumentException>` and I try to call `Contains(operationCanceledException)`, it won't let me (even though I could have violated the various contracts and gotten one into the list, albeit in a very unsafe manner).  I see nullable reference types in the same light.  The type is defined as being non-null.  null is an invalid value.  It's not part of the domain of the type.

(And to clarify, it wouldn't be [MaybeNull]; it would be [AllowNull].)

If a change were to be made here, it would be a sweeping change.  We must not make it for just the aforementioned methods.  It would affect much, much, much more than that.

**Comment by YairHalberstadt** [comment]
Thanks for reopening.

I definitely do see where you're coming from.

I think I would make a pragmatic exception to checking if a list contains a nullable type compared to checking if a list contained any object:

1. If you check whether a `List<ArgumentException>` contains an `InvalidOperationException` you are almost certainly making a mistake and would want to be warned. However NRTs are much easier to fool, and so it is very likely you would want to check if a `List<string>` contained null.

2. Backwards compatibility means this is already done. You'll have a value come from somewhere which can happen to be null. You have a List which is definitely not, and you check whether the list contains the value. It would be unfortunate to force people to either refactor this perfectly valid, working code, or use a null suppression operator.

**Comment by stephentoub** [comment]
@MadsTorgersen, can you chime in?

**Comment by stephentoub** [comment]
I spoke offline with several folks, including @MadsTorgersen and @agocke.  General consensus was the current annotations are the right ones.  We don't, for example, have a `List<T>.Contains(object value)` overload that lets you search a `List<T>` for arbitrary objects that may be outside of the valid domain of `T`; `null` is a similarly invalid value to pass to `Contains` when the `T` is explicitly declared with `null` being an invalid value.

**Comment by YairHalberstadt** [comment]
Thanks for considering this further @stephentoub - your efforts are greatly appreciated!
