### ISSUE TITLE
Preserved references should avoid calling object converter

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#1776]
As of now, if the JSON object that is passed to the internal converter for an `object` type is a reference `{ "$ref": "#" }` we create a `JsonElement` for such object/property.

Instead we could search into the map of references and take the value from there.

Repro:
```cs
private class Node
{
    public Node Child { get; set; }
    public object Sibling { get; set; }
}

[Fact]
public static void PreserveReferenceOnTypesWithObjectConverter()
{
    Node root = new Node();
    root.Child = new Node();
    root.Sibling = root.Child;
    // Ok.
    Assert.Same(root.Child, root.Sibling);

    JsonSerializerOptions opts = new JsonSerializerOptions
    {
        ReferenceHandling = ReferenceHandling.Preserve
    };

    string json = JsonSerializer.Serialize(root, opts);
    /* serialized object:
    {
        "$id": "1",
        "Child": {
            "$id": "2"
        },
        "Sibling": {
            "$ref": "2"
        }
    }
    */

    Node rootCopy = JsonSerializer.Deserialize<Node>(json, opts);
    // Fails, rootCopy.Sibling is a JsonElement.
    Assert.Same(rootCopy.Child, rootCopy.Sibling);
}
```

cc @ahsonkhan, @steveharter, @layomia

**Comment by ahsonkhan** [comment]
Marked is as 5.0, since we should resolve this issue before shipping the feature (including the decision whether to do it or not). Otherwise, this behavior change might be considered breaking, if we do it in the future.

**Comment by Jozkee** [comment]
Should we enforce the same semantic rules that we use for non-object types? 
I would suggest to not throw and instead fallback on the object converter and return a `JsonElement`.
