### ISSUE TITLE
CS0019: Comparing a Nullable enum type with null results in compiler error

### ISSUE THREAD

**Issue by TsengSR** [dotnet/runtime#17774]
The StackOverflow user "Warren P." posted this issue on StackOverflow, which sounds like a bug or oversight to me. 

You can find the original issue [here](http://stackoverflow.com/questions/38191166/c-sharp-optional-enum-type-property-setter-compiles-in-classic-net-but-not-in). 

Comparing an optional/Nullable Enum type property to null results in CS0019 compiler error.

```c#
/// <remarks>This uses the native .NET datatype, rather than the FHIR equivalent</remarks>
[NotMapped]
[IgnoreDataMemberAttribute]
public Hl7.Fhir.Model.RemittanceOutcome? Outcome
{
    get { return OutcomeElement != null ? OutcomeElement.Value : null; }
    set
    {
        if(value == null) // CS00019
          OutcomeElement = null; 
        else
          OutcomeElement = new Code<Hl7.Fhir.Model.RemittanceOutcome>(value);
        OnPropertyChanged("Outcome");
    }
}
```

The resulting compiler error:

```
CS0019  Operator '==' cannot be applied to operands of type 
'RemittanceOutcome?' and '<null>'  
```

`if(value.HasValue)` works however. 

Seems like the == operator override is missing in .NET Core implementation of `Nullable<T>`. Is th is by design or a bug/oversight?

**Comment by stephentoub** [comment]
Closing as no repro.
