### ISSUE TITLE
Unexpected neg operation in `C - X`

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#1779]
```csharp
int Test(int x) => 42 - x;
```
Codgen:
```asm
   mov eax, edx
   neg eax
   add eax, 0x2a
   ret
```
For some reason, JIT converts `C - X` into `C + (-X)` (see [here](https://github.com/dotnet/runtime/blob/e17f25c565340e21a7b47202d0fa593dd1921771/src/coreclr/src/jit/morph.cpp#L12445)). Is it intentional?

**Comment by saucecontrol** [comment]
Seems right to me... 

```asm
neg reg0
add reg0, imm
```

is smaller code than

```asm
mov reg1, imm
sub reg1, reg0
```

and it uses one less register

**Comment by EgorBo** [comment]
@saucecontrol fair enough
