### ISSUE TITLE
Proposal: LegacyAttribute

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/runtime#17865]
# The Problem

A good thing about the .NET Core 1.0 surface area is that it made it clear what classes/methods were considered obsolete because for the most part, they just didn't exist. With the larger surface area planned for v2 a lot of this missing functionality is being brought back purely for compatibility reasons.
How does a developer get informed that a given API is no longer recommended for use?

`ObsoleteAttribute` is the heavy handed version of this which says "You should stop using this immediately, it will be removed in a future version". There needs to be an "Info" level version of this for things that are _considered_ to be obsolete but it's not appropriate to mark it is such.

`[EditorBrowsable(EditorBrowsableState.Never)]` assists when writing new code but doesn't help someone identify usages in existing code.

If I am using something that is no longer recommended I want to know about, and I would like my IDE to be able to tell me. Marking up libraries with a `LegacyAttribute` would be the first step to having that metadata.
# Solution

``` c#
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum |
        AttributeTargets.Interface | AttributeTargets.Constructor | AttributeTargets.Method |
        AttributeTargets.Property  | AttributeTargets.Field | AttributeTargets.Event | 
        AttributeTargets.Delegate, Inherited = false)]
    public sealed class LegacyAttribute : Attribute
    {
        public LegacyAttribute()
        public LegacyAttribute(string message)

        public string Message { get; }       
    }
```

**Semantic Meanings**
"This exists for backwards compatibility. Nothing to see here. Move along"
"This will work for as long as you need it but we recommend you use something else"
# Examples

TimeZone can't be marked obsolete https://github.com/dotnet/corefx/issues/10074
Analyzers need metadata https://github.com/DotNetAnalyzers/Proposals/issues/37
Legacy collections can't be marked obsolete https://github.com/dotnet/corefx/issues/370 (It's common for Java developers to use ArrayList on .net, how do we educate that's not recommended anymore?)
CharSet.Unicode inappropriate to mark obsolete https://github.com/dotnet/corefx/issues/7804
BitVector32 https://github.com/dotnet/corefx/issues/373
# Summary

Compatibility has been one of the full .NET frameworks great strengths. There needs to be a way to deal with the downside of that which is education of APIs that still exist only for that compatibility story.

**Comment by Joe4evr** [comment]
This is handled now that the [Better Obsoletion properties are merged in](https://github.com/dotnet/runtime/pull/33248), it's just a matter of waiting for the compilers to honor the new properties.

**Comment by bbowyersmyth** [comment]
ObsoleteAttribute now has additional features https://github.com/dotnet/runtime/issues/33089
