### ISSUE TITLE
[EventPipe] Does EventCounter work across containers in the same pod?

### ISSUE THREAD

**Issue by enihcam** [dotnet/runtime#1791]
I have a .net core 3.1 application deployed in K8S pod, and i would like to consume the EventCounter metrics from a side-car container. Is it possible?

**Comment by hoyosjs** [comment]
Currently there's work under flight to enable these scenarios. @josalem could give you a better idea of this.

**Comment by josalem** [comment]
This isn't supported _yet_.  Keep an eye on the work in #1600 and some follow up work in the dotnet/diagnostics repo to make the tools work under this scenario.

**Comment by josalem** [comment]
This work is shipping in 5.0.
