### ISSUE TITLE
Virtualizing Observable Collection

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/runtime#17969]
In .NET Standard 2.0, I would like to see an Virtualizing Observable Collection. Since Windows 8 (WinRT) a new design principle of Microsoft is “fast and fluid”. But in the full .NET Framework no class is available to virtualize the loading of data. There should be for all UI technologies from Microsoft (WPF, UWA, Xamarin.Forms, ASP.NET) a simple built-in way to load data by page (paging). There are some community projects that have addressed this issue, but I think that Microsoft should provide a uniform solution.
- [Virtualizing Observable Collection (Andrew Whiddett, Alpha Chi Technology)](https://alphachitech.wordpress.com/2015/01/31/virtualizing-observable-collection/), [NuGet](https://www.nuget.org/packages/VirtualizingObservableCollection), [GitHub](https://github.com/anagram4wander/VirtualizingObservableCollection)
- [WPF: Data Virtualization (Paul McClean)](http://www.codeproject.com/Articles/34405/WPF-Data-Virtualization)
- [WPF Data Virtualization (DevZest)](https://datavirtualization.codeplex.com/)
- [AsyncVirtualizingCollection (Bea Stollnitz)](http://web.archive.org/web/20111201001632/http://bea.stollnitz.com/blog/?p=378)

**Comment by eiriktsarpalis** [comment]
Triage: From a System.Collections perspective this issue doesn't appear to be very actionable. I'm going to close this, but feel free to reopen. Most likely this will require creating separate issues containing concrete proposals on required api changes.
