### ISSUE TITLE
Question: OS threads in .NET processes

### ISSUE THREAD

**Issue by shantanu1singh** [dotnet/runtime#1797]
I am currently working on some dotnet-core based docker containerized applications (base image mcr.microsoft.com/dotnet/core/runtime:3.0.0-bionic-arm64v8) and I'm trying to understand how the dotnet runtime creates threads.

When the container starts up, I used the following block of code to determine the number of OS threads created by the process and the number of threads created by the CLR runtime

```
            logger.LogInformation($"Number of threads {Process.GetCurrentProcess().Threads.Count}.");

            using (DataTarget target = DataTarget.PassiveAttachToProcess(
                Process.GetCurrentProcess().Id))
            {
                ClrRuntime runtime = target.ClrVersions.First().CreateRuntime();
                foreach (ClrThread thread in runtime.Threads)
                {
                    logger.LogInformation($"Thread {thread.ManagedThreadId}, StackBase: {thread.StackBase}"
                        + $", IsUserSuspended: {thread.IsUserSuspended}"
                        + $", IsMTA: {thread.IsMTA}"
                        + $", IsSTA: {thread.IsSTA}"
                        + $", IsAborted: {thread.IsAborted}"
                        + $", IsAlive: {thread.IsAlive}"
                        + $", IsBackground: {thread.IsBackground}"
                        + $", IsUnstarted: {thread.IsUnstarted}");
                }
            }
```

I noticed that the number of OS threads returned by `Process.GetCurrentProcess().Threads` is much higher in number (11-12) compared to the number of threads returned by the `ClrRuntime` object (3-4). I was curious on what these other threads are created for?

Additionally, the threads that are returned by the `ClrRuntime` are non-threadpool threads. Is there a way to limit the total number of threads created overall as part of this process and/or by the `ClrRuntime`? I know that the total number of threads in the threadpool can be limited but wasn't sure if the threads outside of that can be controlled.

The reason I have this question is because we're trying to run these .NET containers on a single-core device and having a large proliferation of threads on that device might not be ideal.

**Comment by jkotas** [comment]
`Process.GetCurrentProcess().Threads` returns all threads in the process. ClrRuntime only returns threads that the managed code ever run on.

>  I was curious on what these other threads are created for?

They are helper threads of various subsystems. For example, the PAL layer creates a helper thread [here](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/pal/src/synchmgr/synchmanager.cpp#L1490), primarily to implement `WaitHandle.WaitAny/WaitAll` APIs.

> Is there a way to limit the total number of threads created overall as part of this process and/or by the ClrRuntime?

There is not. The managed API to create a new thread (`Thread.Start`) will just ask the underlying OS to create a new thread. .NET programs can create as many threads as they want, as long as the underlying OS allows it.

**Comment by shantanu1singh** [comment]
Got it. Thank you!

**Comment by danmosemsft** [comment]
>  we're trying to run these .NET containers on a single-core device

@shantanu1singh is there anything you can publicly share about your overall scenario here? Just curiosity.

**Comment by shantanu1singh** [comment]
> > we're trying to run these .NET containers on a single-core device
> 
> @shantanu1singh is there anything you can publicly share about your overall scenario here? Just curiosity.

@danmosemsft the dotnet containers that I am working with are [Azure IoT Edge Agent](https://github.com/Azure/iotedge/tree/master/edge-agent) and [Edge Hub](https://github.com/Azure/iotedge/tree/master/edge-hub).

I'm trying to run these containers on a device that has the following specs:

1 A57 core -> 1.5 GHz clock speed
Memory -> 2 GB ram
Disk -> 2 GB

We've been trying to evaluate whether controlling the maximum number of threads on a single-core device might help performance (including startup time) but I couldn't do so because .NET doesn't allow imposing such a max limit on the total number of threads per application. 

We also noticed CPU spiking to a 100% on this device when these two containers were started and therefore were wondering how we can improve resource utilization on this resource constrained device.
