### ISSUE TITLE
[iOS][System.Net.Http][Nuget] *NotImplementedException* is thrown when setting MaxConnectionsPerServer

### ISSUE THREAD

**Issue by tuyen-vuduc** [dotnet/runtime#1800]
# Issue Title

*NotImplementedException* is thrown when setting MaxConnectionsPerServer if referencing System.Net.Http nuget package

# General

When referencing System.Net.Http nuget package in iOS project then initializing a HttpClientHandler, it throws *Not ImplementedException*

```c#
var handler = new HttpClientHandler {
      MaxConnectionsPerServer = 20
};
```
This happens even if we reference to System.Net.Http DLL in Xamarin.iOS framework.

If we remove the nuget package reference, it works well.

**Comment by karelz** [comment]
@marek-safar how do we mark iOS specific bugs -- I assume this is from iOS native Handler

**Comment by tuyen-vuduc** [comment]
From my understanding, it looks like `System.Net.Http.dll` embedded in Xamarin.iOS framework isn't in use when we add `System.Net.Http` nuget package.  

If we could make System.Net.Http.dll of platform specific implementation is always in use, the issue will be fixed.

Cheers.

**Comment by marek-safar** [comment]
@karelz yes, this is from ios handler. I'd add `os-ios` label to the issue.

**Comment by steveisok** [comment]
As of right now, `MaxConnectionsPerServer` is not going to be supported by the native iOS and Android handlers.  If you need this property, you can set `UseNativeHttpHandler` to `false` in your iOS csproj and that will enable `SocketsHttpHandler`.
