### ISSUE TITLE
Inconsistent performance of pointer vs. Span

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#1801]
Group 1：

Define an array within a method.

```C#
[Benchmark]
public unsafe void ByteSpan()
{

     var array = new byte[1024];
     var span = array.AsSpan();
     for (var i = 0; i < span.Length; i += 1)
     {
            span[i] = byte.MinValue;
     }

}

//Faster
[Benchmark]
public unsafe void BytePointer()
{
            
     var array = new byte[1024];
     fixed (byte* pointer = array)
     {
           for (var i = 0; i < array.Length; i += 1)
           {
                 *(pointer + i) = byte.MinValue;
           }
     }

}
```
|      Method |     Mean |    Error |   StdDev |
|------------ |---------:|---------:|---------:|
|    ByteSpan | 625.4 ns | 22.13 ns | 22.73 ns |
| BytePointer | 499.2 ns |  8.13 ns |  7.21 ns |

Group 2：

Use an array defined by a member.

```C#

private static readonly byte[1024] = new byte[1024];


//Faster
[Benchmark]
public unsafe void ByteSpan()
{

     var span = array.AsSpan();
     for (var i = 0; i < span.Length; i += 1)
     {
            span[i] = byte.MinValue;
     }

}

[Benchmark]
public unsafe void BytePointer()
{
            
     fixed (byte* pointer = array)
     {
           for (var i = 0; i < array.Length; i += 1)
           {
                 *(pointer + i) = byte.MinValue;
           }
     }

}
```
|      Method |     Mean |    Error |   StdDev |
|------------ |---------:|---------:|---------:|
|    ByteSpan | 472.8 ns |  5.23 ns |  4.89 ns |
| BytePointer | 580.0 ns | 11.36 ns | 18.02 ns |

I don't know how this difference came about. Who can explain it in detail for me? :)

**Comment by huoyaoyuan** [comment]
I think this is likely the same with dotnet/coreclr#20862 . Minor codegen difference leads to significant performance difference because of alignment.

**Comment by jkotas** [comment]
Closing as duplicate

**Comment by NMSAzulX** [comment]
@jkotas @huoyaoyuan  Isn't that GC's problem? I don't think it's the same issue as 20862 .

**Comment by NMSAzulX** [comment]
@huoyaoyuan @jkotas Sorry, I got it. It's 20862 issue.... haha
