### ISSUE TITLE
Web Hosting Bundle 2.2.4 - It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by AdamRiddick** [dotnet/runtime#1803]
**Steps to reproduce**
Unknown - We've been unable to reliably reproduce, but have seen this across a handful of servers.

Note this works fine on 

**Expected Behaviour**
`dotnet myapp.dll` starts up the apps process

**Actual behavior**
`dotnet myapp.dll` throws the following;
![image](https://user-images.githubusercontent.com/5352471/72514948-ff480e80-3846-11ea-8a05-4065b92ae780.png)

**Diagnostics**
After enabling tracing (COREHOST_TRACE=1) the following trace is obtained where this occurs;

```
Tracing enabled
--- Invoked dotnet [version: 2.2.4, commit hash: f95848e5243fafee7e535d6db4f8a7d227346cc3] main = {
dotnet
myapp.dll
}
Reading fx resolver directory=[C:\Program Files\dotnet\host\fxr]
Considering fxr version=[1.1.0]...
Considering fxr version=[2.0.0]...
Considering fxr version=[2.0.7]...
Considering fxr version=[2.2.4]...
Detected latest fxr version=[C:\Program Files\dotnet\host\fxr\2.2.4]...
Resolved fxr [C:\Program Files\dotnet\host\fxr\2.2.4\hostfxr.dll]...
Loaded library from C:\Program Files\dotnet\host\fxr\2.2.4\hostfxr.dll
Invoking fx resolver [C:\Program Files\dotnet\host\fxr\2.2.4\hostfxr.dll] v2
Host path: [C:\Program Files\dotnet\dotnet.exe]
Dotnet path: [C:\Program Files\dotnet\]
App path: [C:\Program Files\dotnet\dotnet.dll]
Tracing enabled
--- Invoked hostfxr v2 [commit hash: f95848e5243fafee7e535d6db4f8a7d227346cc3] main
Checking if CoreCLR path exists=[C:\Program Files\dotnet\coreclr.dll]
--- Executing in muxer mode...
Using the provided arguments to determine the application to execute.
Using dotnet root path [C:\Program Files\dotnet\]
App runtimeconfig.json from [E:\myapp\myapp.dll]
Runtime config is cfg=E:\myapp\myapp.runtimeconfig.json dev=E:\myapp\myapp.runtimeconfig.dev.json
Attempting to read runtime config: E:\myapp\myapp.runtimeconfig.json
Attempting to read dev runtime config: E:\myapp\myapp.runtimeconfig.dev.json
Runtime config [E:\myapp\myapp.runtimeconfig.json] is valid=[1]
--- Resolving FX directory, name 'Microsoft.AspNetCore.App' version '2.2.0'
Searching FX directory in [C:\Program Files\dotnet]
Attempting FX roll forward starting from [2.2.0]
'Roll forward on no candidate fx' enabled with value [1]. Looking for the least production greater than or equal to [2.2.0]
No production greater than or equal to [2.2.0] found. Looking for the least preview greater than [2.2.0]
No preview greater than or equal to [2.2.0] found.
Applying patch roll forward from [2.2.0]
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download

```

**Fix**
As this affected client instances we were pressed to find a solution. 

Repairing the dot net hosting bundle solved this issue.

We are trying to understand why this happens to we can prevent any re-occurrences in the future.

**Environment data**
Windows server 2012 Standard / Windows Server 2016 Standard
Dot Net Hosting Bundle 2.2.4 installed
 <TargetFramework>netcoreapp2.2</TargetFramework>

**Comment by elinor-fung** [comment]
The fact that repairing the hosting bundle resolves the issue makes me think something went wrong with the installation itself such that the `Microsoft.AspNetCore.App` framework wasn't put down properly.

On a machine in this state, could you:
- see what `dotnet --info` lists
- get the installer logs (should be under `%TMP%` with names following the pattern `dd_*.log`)

**Comment by AdamRiddick** [comment]
Thanks,

I'll keep an eye on this and if we do experience this on any further servers I'll try the above steps - unfortunately we haven't been able to reproduce and we've had to apply quick solutions, so we don't currently have a machine in this state.

I can re-open when I have the above info, should we experience this again.

**Comment by AdamRiddick** [comment]
Hi,

We've now experienced a very similar issue while updating to the Web Hosting Bundle 2.2.8. This time the application could be run using the `dotnet` tool, but could not be ran through IIS.

Unfortunately support were unable to grab the full error, however I am seeing this in the event log from the first install of the bundle; 

`Failed to end a Windows Installer transaction C:\ProgramData\Package Cache\{B5A48714-6F03-43FD-BB4D-5C0C08E45723}v12.2.19282.0\aspnetcoremodule_x64_en_v2.msi. Error 1603 occurred while ending the transaction.`

I have the installer logs, but only from the repair installation. 

Could these provide some insight? If so, please let me know an email address to send them to.

**Comment by elinor-fung** [comment]
@jkotalik would you / your team be the ones that would know about install errors with the aspnetcoremodule MSI?

**Comment by jkotalik** [comment]
cc @joeloff

**Comment by joeloff** [comment]
1603 is the catch-all error code, but the logs for the MSI itself might shed some light on this. There's a log for the hosting bundle itself that provides a summary of all the installs and then there should be a separate log for each MSI. The MSI log should contain AspNetCoreModule in its name and will usually be in the %temp% folder.

**Comment by AdamRiddick** [comment]
I'm going to close this issue as we are unable to reproduce and we have no servers remaining to update that this issue could affect. Back to where we were previously - if this does re-occur and I manage to get a copy of the logs from the failed installation I will re-open or open a new issue.

Thanks.
