### ISSUE TITLE
Difficult (not possible?) to redirect binary output between Linux processes

### ISSUE THREAD

**Issue by brendandixon** [dotnet/runtime#18109]
A common pattern in Linux is to pipe output between commands. And such output is not always text (e.g., imagine a series of openssl commands). Unfortunately, the System.Diagnostic.Process class _assumes_ that output and input is textual. Such an assumption violates Linux conventions.

**Comment by eiriktsarpalis** [comment]
Triage: using `StandardOutput.BaseStream` should in principle provide an adequate workaround for handling non-textual data. I am going to close this, but assuming there are issues with that particular workaround we can take a closer look at those.
