### ISSUE TITLE
CodeGen diff for ternary vs if blocks

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#1814]
Hey team, not an issue, I'm just curious to know why these two methods generate different code.
In this case it looks like FromHex1 is doing some more stack pushes/pops.

```c#

public class SomeApi
{
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static int FromHex1(char digit) =>
        CharHelper.IsAsciiDigit(digit) ? digit - '0' :
        CharHelper.IsHexDigitLetter(digit) ? (digit | 0x20) - 'a' + 10 :
        ThrowArgumentException();

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static int FromHex2(char digit)
    {
        if (CharHelper.IsAsciiDigit(digit))
            return digit - '0';

        if (CharHelper.IsHexDigitLetter(digit))
            return (digit | 0x20) - 'a' + 10;

        return ThrowArgumentException();
    }

    private static int ThrowArgumentException() => throw new ArgumentException("digit");
}

internal static class CharHelper
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsAsciiDigit(char c) =>
        (uint)(c - '0') <= ('9' - '0');

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsHexDigitLetter(char c) =>
        (uint)((c - 'A') & ~0x20) <= ('F' - 'A');
}
```

```asm
// FromHex1
push      rsi
movzx     esi,cx
lea       eax,[rsi-30h]
cmp       eax,9
jbe       short 0000`7FF8`E927`21EFh
lea       eax,[rsi-41h]
and       eax,0`FFFF`FFDFh
cmp       eax,5
jbe       short 0000`7FF8`E927`21E5h
mov       rax,7FF8`E925`0590h
pop       rsi
jmp       rax
mov       eax,esi
or        eax,20h
add       eax,0`FFFF`FFA9h
pop       rsi
ret
pop       rsi
ret

// FromHex2
movzx     edx,cx
lea       eax,[rdx-30h]
cmp       eax,9
ja        short 0000`7FF8`E94E`27CCh
ret
lea       eax,[rdx-41h]
and       eax,0`FFFF`FFDFh
cmp       eax,5
ja        short 0000`7FF8`E94E`27E0h
mov       eax,edx
or        eax,20h
add       eax,0`FFFF`FFA9h
ret
mov       rax,7FF8`E925`0590h
jmp       rax
```

[SharpLab for IL reference](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgBgAJDSA6AJQFcA7DbAWxiYDCEHgAc8MKAGUJAN2xgYAZwDcVKoQDMDYnUnCYAQTFUA3lToW6AbQCyMDAAsIAEwCSo3AAo7jl+5G4APIi3BAcikwGAOZRsIqK2DIwwdw82ABeAIahHACUALrmlpoMpEh02Fx0AGJQwgASMAiknmAOmVB0zthR2Bi5dAC8AHxFlpYC7VCNuCISTK6KBopg2NgAIj19nt29/XQA/F1bGHRwdADkNBd0IGPjdJMdM3NQC4qNCJt7ADL2GBIdicBkcgXs6Pg6DQEMQaANzhdMjcANR0Uj0O6UB6WAAqDjqAHcDFAomw+FwAKIIBQhbBhTy5VSUe62exONwebxsvweFJ08KRGJxBJJPlpLI5Ar3EqMcqVU61BpNYitKbHPa5e5mLHYioAMzonie0xgs3mi2Wqw2JzBfVymp1uuKAHZ1X0zpdrkz7uNsAajVMXuaPk1vn0/hgAVBbf0HU7xoRXTGIVCYXCPYiUWiaN7HQ9E3Q8YTiaTyRgqTScgymeMAL5qPMiKCJbIwUpyqpFiBEklkmCU6kwWn0gYjOiOQl0DgwAl0Et9geV/meABEuz6K8ZVHrzMo8okHEyuHb2kegdNr1MLJ87P8XhvPICfLCEWisSUIpgrg4uEqlSiUp5jKZR0MAEAQMeForGsYYYKqHR0GAo6jHm4yeGw8q5K0GbXAMAA8gyGhcACcNwIrhubjKyvgcgEXI0Xez4Cm+wqJF+P5/hwAGFEBWiyqB4GQSGXwnBGUbwZ0SFDChTroZhnjYQiBgXAMABkdAAH7QrC+GEZ4FzVGRlzKVulC1kAA==)

**Comment by stephentoub** [comment]
The C# compiler produces different IL for these. Is your question why it produces different IL? or why the JIT doesn't produce the same asm for different IL?

**Comment by MihaZupan** [comment]
I suppose the question is mostly about the JIT.
To me it looks like the different IL *could* still yield the same asm, as I don't see any behavioural differences between them, only inverted branch conditions.
I am curious as to whether writing code by nesting ternaries, where all branches end up returning, can have different behaviour than writing out separate ifs, as I have assumed (never looked into it) that they would be lowered to the same representation (either in Roslyn/Jit).

**Comment by AndyAyersMS** [comment]
I can't speak for Roslyn, but the jit codegen is fairly sensitive to the exact expression of the method in IL. Arguably, as you point out here, it is too sensitive.

I'm not aware of any specific plans to try and "normalize" things better in the jit's IR, though as a matter of principle it would be a good ambition to take on...

**Comment by AndyAyersMS** [comment]
@MihaZupan I'll probably close this unless you have more questions...

**Comment by MihaZupan** [comment]
Good to close. Thank you for the answer
