### ISSUE TITLE
CallerMemberName faster than nameof()

### ISSUE THREAD

**Issue by OleksiiYatsenko** [dotnet/runtime#1815]
# Issue Title
**CallerMemberName faster than nameof() in netcore 3.1 and net4.8**

# General
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-9850H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.1.100
  [Host]     : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT
  Job-YBVATM : .NET Framework 4.8 (4.8.4075.0), X64 RyuJIT
  Job-FZSPSC : .NET Framework 4.8 (4.8.4075.0), X64 RyuJIT
  Job-AZPDUX : .NET Framework 4.8 (4.8.4075.0), X64 RyuJIT
  Job-FLWVID : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT
Benchmark code:
`
namespace PerformansBenchmarks.Strings
{
    [SimpleJob(RuntimeMoniker.Net462)]
    [SimpleJob(RuntimeMoniker.Net472)]
    [SimpleJob(RuntimeMoniker.NetCoreApp30)]
    [SimpleJob(RuntimeMoniker.Net48)]
    public class NameOfRuntime
    {
        [Benchmark]
        public string NameOfPerformance()
        {
            return nameof(NameOfPerformance);
        }
        [Benchmark]
        public string RuntimeAttributePerformance()
        {
            return ReflectionExtensions.GetCurrentMethodName();
        }
    }
}
public static class ReflectionExtensions
    {
        public static string GetCurrentMethodName([CallerMemberName] string caller = null)
        {
            return caller;
        }
    }
`
Results: 
![image](https://user-images.githubusercontent.com/12793270/72533737-50272980-387e-11ea-974a-1f94a7b543ab.png)

Looks like nameof() performance slower than custom ad-hoc. However nameof() on my mind is recommended approach for receiving names. Why it is happens?

**Comment by jkotas** [comment]
Both these methods just return constant string. The micro-benchmark performance variations you are seeing is due to micro-architectural issues like code alignment. You will see similar variations, e.g. if you change the micro-benchmarks order.

Similar issues: #1801 https://github.com/dotnet/coreclr/issues/20862

**Comment by scalablecory** [comment]
Your benchmark is so small (doing basically no work), that the numbers will likely be wildly variable. What I can see on sharplab is that the [codegen is identical between the two](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcAMACOSB0ASgK4B2wAllAKb4DCA9lAA4UA21ATgMpcBuFAMbUIAbnTo4AZlwJsdbAG902VbhlwALPLBs2AQQAUAShVrlaNVexHj4y2oC+Z1S/W5tdXWwBCJtxbWan6kYDQMAGaGXno+xnZuzg6uye5aNoYA2jEcnACy1FAARlwAcmHUALp4OBEMDNgAvNikxHqmqYFBuEgAnIZ1DAmpSVZu0h7YfjXYgx1WXUF4/XP2VkmOQA=):

```c#
public class C {
    public void CallA()
    {
        A();
    }
    
    public void CallB()
    {
        B(nameof(CallB));
    }
    
    public void A([CallerMemberName]string foo = null)
    {
        Console.WriteLine(foo);
    }
    
    public void B(string foo)
    {
        Console.WriteLine(foo);
    }
}
```

Code generation:
```
C.CallA()
    L0000: mov ecx, [0x10f19728]
    L0006: call System.Console.WriteLine(System.String)
    L000b: ret

C.CallB()
    L0000: mov ecx, [0x10f1972c]
    L0006: call System.Console.WriteLine(System.String)
    L000b: ret

C.A(System.String)
    L0000: mov ecx, edx
    L0002: call System.Console.WriteLine(System.String)
    L0007: ret

C.B(System.String)
    L0000: mov ecx, edx
    L0002: call System.Console.WriteLine(System.String)
    L0007: ret
```

**Comment by jkotas** [comment]
If you use this in real-world code, the performance of both approaches will be identical. These micro-benchmarks are laying to you about what will happen in practice.
