### ISSUE TITLE
FileStream.Dispose silently fails on Dispose when disk has run out of space

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#1816]
On Unix, when the disk runs out of space before a `FileStream` is disposed and the buffer is flushed to disk, Dispose silently succeeds, causing files to be corrupted and preventing the user from taking corrective action.

On Windows we throw at the expected moment, allowing the user to react appropriately.

Interestingly, the Mono implementation of Dispose(disposing) [checks the close return status](https://github.com/mono/mono/blob/bafdd7865f1d407cd2fe9ce98bbcd40f7086eda6/mcs/class/corlib/System.IO/FileStream.cs#L899).

An example shared by @arunjvs reproing the problem:

```cs
using System;
using System.IO;

namespace ConsoleApp
{
    class Program
    {
        // dotnet run ~/largefile ~/largefile2 4194304
        static int Main(string[] args)
        {
            try
            {
                using (Stream source = new FileStream(args[0], FileMode.Open, FileAccess.Read))
                {
                    using (Stream dest = new FileStream(args[1], FileMode.Create, FileAccess.Write))
                    {
                        source.CopyTo(dest, Convert.ToInt32(args[3]));
                    }
                }
            }
            catch (Exception ex)
            {
                // If FS got full on Windows before copy could complete, we arrive here with ex as IOException and know that the copy hasn't succeeded.
                Console.WriteLine(ex);
                return ex.HResult;
            }

            // If FS got full on Linux before copy could complete, we arrive here with no exception as though copy succceded.
            // But file is actually truncated to the nearest FS block boundary. That is, it is corrupt.
            // Happens when close() fails instead of write() when we are just 1 or a few blocks away from FS full.

            return 0;
        }
    }
}
```

**Comment by carlossanlop** [comment]
@arunjvs I ran your code in my Ubuntu machine (18.04) which has the dotnet/runtime repo cloned and synced to the latest bits. I was not able to repro the issue. Here's what I did:

- Created a small partition of 8MB.
- Attempted to copy a 10MB file from my Desktop to that partition.
- I gave the `CopyTo` method a buffer size of 1.
- After multiple buffer iterations, the `CopyTo` method threw an exception when attempting to write and going beyond the maximum size. The exception message was "Not enough disk space".

Next steps for me:
- Run this in Release mode (the enlistment was built in Debug).
- Test this code in 3.1, in case this is already fixed in 5.0 and I need to identify the change that may have fixed it.

**Comment by joshudson** [comment]
Try again with btrfs as your filesystem. 

In any case, deciding to throw the disk error in ` Dispose ()` is equivalent to selecting the second API review proposal.

**Comment by arunjvs** [comment]
As discussed offline with Carlos, one common scenario is SMB mount of a file share with quota. You could create an Azure File Share (AFS) in a storage account and mount them on a Linux machine using the SMB endpoint.

**Comment by carlossanlop** [comment]
@arunjvs I was able to repro the issue using the Azure File Share instructions you sent me offline.

1. I mounted the AFS into my machine.
2. I ran your test, making sure to copy the largest zip file in your AFS into a new zip file inside the same AFS folder.
3. Once the AFS ran out of space, CopyTo finished without throwing, the two usings disposed without throwing, and I reached the end of the method.
4. I inspected the AFS folder, and the file I tried to copy was created, but it had a size of 0.

**Comment by joshudson** [comment]
Since nobody seems to be able to decide if  CA1065 should stand or fall, I came up with an option 3.

    enum FileOptions {
       //...
       DontThrowInDispose = 65536,
    }

This allows calling code to be upgraded in stages, or perhaps not at all.

I've been waiting for somebody to actually be able to decide which path to take before I write one giant patch for handling of `close(2)` failing.

**Comment by danmosemsft** [comment]
@carlossanlop am I understanding correctly, we have a repro -- do we have an understanding of the correct fix, or does that need more investigation?

**Comment by joshudson** [comment]
@danmosemsft : I'm just waiting for the hard choice to be made. I posted a pair of choices for the API review team.

**Comment by danmosemsft** [comment]
@carlossanlop is reaching out
