### ISSUE TITLE
Add Enum method to remove not defined flags.

### ISSUE THREAD

**Issue by magol** [dotnet/runtime#18190]
Suppose I have an enum type defined by `FlagsAttribute`and has an enum value that is outside the limit of the enum type. I then want to hace a way to easily remove the flags that are not defined. 

This can be useful if I eg get an enum value from an external API, and all the flags are not defined in the internal enum type. I would then want clear the unsupported flags.

Alternative solution proposals:
**Alternative 1**

``` C#
[ComVisibleAttribute(true)]
public static object ToObject(
    Type,
    int,
    bool=false
)
```

If you set the the new boolena value to `true`, unknown flags is removed. This should only be valid for enum types that are defined with `FlagsAttribute`, or else the function throw a exception. (By the way, why are not `ToObject`generic to avoid having to cast like dotnet/runtime#14083 ?)

**Alternative 2**

``` C#
public int BitMask { get; }
```

It returns a bit mask that can be used like this:
`var cleanedEnumValue = myEnumValue & myEnumValue.BitMask;`

**Alternative 3**

``` C#
public object RemoveUndefinedFlags { get; }
```

It returns a enum where the undefined flags have been masked away. Or if the enum is not defined with `FlagsAttribute`, it throw a exception.

**Comment by stephentoub** [comment]
This hasn't had a lot of interest in years, and it's easily achieved by just defining said mask one's self.  I'm going to close this.  Thanks.
