### ISSUE TITLE
Add Quarters to DateTime formats

### ISSUE THREAD

**Issue by jods4** [dotnet/runtime#18233]
I suggest that you add support for quarters when formatting a `DateTime`.
`q` would display the date quarter (1..4).

Example: 
`new DateTime(2016, 8, 19).ToString("Qq yyyy") == "Q3 2016"`

This is quite common in financial applications and the lack of it can sometimes require convoluted workarounds.

**Comment by tannergooding** [comment]
@tarekgh, is this feasible now that we have standardized on ICU?

If not, I'd like to close the issue as it has had no updates in 4.5 years and we are unlikely to make progress on an API proposal ourselves.

**Comment by tarekgh** [comment]
Closing it for now and we can revisit that in the future as needed. Thanks.
