### ISSUE TITLE
build/test issues on WSL

### ISSUE THREAD

**Issue by ericeil** [dotnet/runtime#18258]
Tracking current issues blocking CoreFx testing on Ubuntu on Windows:

(Note that basically nothing works prior to rs_preview build 14905, which introduced "restartable syscall" support.)

rs_preview build 14936 has a [known bug](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14936) that causes a BSOD when running our networking tests.
- [x] Need to update the dotnet cli to a more recent version with the "execstack" bit set correctly on native modules (https://github.com/dotnet/corefx/issues/11058).
- [x] System.Diagnostics.Process: https://github.com/Microsoft/BashOnWindows/issues/967.
- [x] System.Diagnostics.Process: https://github.com/Microsoft/BashOnWindows/issues/968.
- [x] System.Diagnostics.Process: https://github.com/Microsoft/BashOnWindows/issues/974
- [x] System.Diagnostics.Process: https://github.com/dotnet/corefx/issues/11072.
- [x] System.IO.Pipes: _hangs_ due to https://github.com/Microsoft/BashOnWindows/issues/975.
- [x] System.IO.Pipes: https://github.com/Microsoft/BashOnWindows/issues/1011
- [x] System.IO.Pipes: https://github.com/Microsoft/BashOnWindows/issues/1012
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/982.
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/987
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/989
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/990
- [x] System.Linq.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Linq.Expressions.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Numerics.Vectors.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Runtime.Numerics.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Dynamic.Runtime.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.IO.FileSystem.Tests: https://github.com/Microsoft/BashOnWindows/issues/1008
- [x] System.IO.FileSystem.Watcher.Tests: https://github.com/Microsoft/BashOnWindows/issues/216 (fixed in Windows build 14926)
- [x] System.IO.FileSystem.DriveInfo.Tests: https://github.com/dotnet/corefx/issues/11570
- [x] System.Net.Ping.Functional.Tests: https://github.com/Microsoft/BashOnWindows/issues/561 (fixed in Windows build 14926)
- [x] System.Net.NetworkInformation.Functional.Tests: https://github.com/Microsoft/BashOnWindows/issues/308
- [x] Intermittent failures in System.Net.Http tests: https://github.com/Microsoft/BashOnWindows/issues/1068.
## Still need investigation:
- [x] NuGet package restore occasionally hangs.  Killing it and retrying usually gets past this.
- [x] Intermittent hangs in System.Net.Http tests.

**Comment by danmosemsft** [comment]
The remaining ones are all networking except 1. Moving to networking area. We'd welcome anyone who would like to take the attributes off and see which now pass in WSL2.
```
C:\git\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:
 2544:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.Proxy.cs:
  223:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.HttpListener\tests\HttpResponseStreamTests.cs:
  458:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  498:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.NetworkInformation\tests\FunctionalTests\IPGlobalPropertiesTest.cs:
   30:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
   55:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
   81:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  112:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\ExecutionContextFlowTest.cs:
  339:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\OSSupport.cs:
   68:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SelectTest.cs:
  181:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:
 1199:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
 1240:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
 1312:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
 1341:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs:
  384:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  396:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  420:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\TcpClientTest.cs:
  261:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  271:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\TcpListenerTest.cs:
   26:         [ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\UdpClientTest.cs:
  286:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Private.Xml\tests\XmlReader\Tests\AsyncReaderLateInitTests.cs:
   90:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]

C:\git\runtime\src\libraries\System.Text.Encoding\tests\Encoder\EncoderConvert2.cs:
  212:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  232:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
  254:         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsSubsystemForLinux))] // [ActiveIssue("https://github.com/dotnet/runtime/issues/18258")]
```

**Comment by bitcrazed** [comment]
@danmosemsft - do let @craigloewen-msft know if you need any assistance etc. from WSL

**Comment by danmosemsft** [comment]
It's @bitcrazed himself 😃 

Sure, although I don't plan to look at this in the near future - these are just test failures, they may not be failing because of issues that would actually impact a customer.

These attributes were all added on WSL1. First task here is for a volunteer to just remove the attributes and see how many pass on WSL2.

**Comment by tarekgh** [comment]
@danmosemsft I'll try that with WSL2 during next week or so and will report what I find.

**Comment by tarekgh** [comment]
@danmosemsft looking at the method `PlatformDetection.IsNotWindowsSubsystemForLinux` used in the attribute, this method detect if we are running inside WSL by checking the content of the `/proc/version`

```C#
        private static bool GetIsWindowsSubsystemForLinux()
        {
            // https://github.com/Microsoft/BashOnWindows/issues/423#issuecomment-221627364
            if (IsLinux)
            {
                const string versionFile = "/proc/version";
                if (File.Exists(versionFile))
                {
                    string s = File.ReadAllText(versionFile);

                    if (s.Contains("Microsoft") || s.Contains("WSL"))
                    {
                        return true;
                    }
                }
            }

            return false;
        }
```

on WSL2 (Ubuntu 18.04), I am seeing the content of the file is 

```
Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019
```

Which will make the detection always fail. note that `String.Contains` is case sensitive, which means "Microsoft" will not equal "microsoft". 

in another word, setting the attribute will have the same effect as removing it when running on WSL2.

**Comment by danmosemsft** [comment]
@tarekgh I guess we need to decide whether we want to have a separate condition for WSL1 vs WSL2. It would be nice if tests run clean on both but WSL2 is more interesting I think.

**Comment by tarekgh** [comment]
I ran all the tests and looks they are passing. I didn't remove the attributes manually because is not really affecting the run and I am not seeing any test skipped because of this attribute. 

I am seeing the run of some of the networking tests (e.g. `System.Net.Http.Functional.Tests`) has skipped many tests because we are not running stress mode.

**Comment by wfurt** [comment]
WSL2 is conceptually different beast. I don't think we should lump them together. WSL1 lacked many /proc entries and had different behavior since there was no real Linux kernel. 

As far as I know, @ManickaP did not encounter any issues with WSL2. She is probably the best person to comment on the stability of networking on WSL flavors.

**Comment by danmosemsft** [comment]
I guess what I was wondering about is whether we care about WSL1 any more. As I understand it, WSL2 is strictly better unless you are doing heavy IO against the Windows file system. @bitcrazed ?

Also, I don't think we got many customers asking about it. We mostly did this exercise originally to enable our own dev team to work on it.

**Comment by ViktorHofer** [comment]
I don't think we should continue supporting WSL1 for building/testing. That's just a waste of resources.

**Comment by tarekgh** [comment]
Note that WSL2 is not fully released. I suggest waiting for a little keeping the attributes for WSL1. We don't have to provide extra support or work for WSL1 though.

**Comment by wfurt** [comment]
I think there are two aspects: making product working on WSL1 and making all tests pass on such platform. I would agree with @ViktorHofer that fixing second maybe waste of resources. We can still respond to real customer issues as WSL1 is still valid MS product even if WSL2 is available.

**Comment by ViktorHofer** [comment]
> making product working on WSL1

How do you define working? Building the repo on WSL1 or running .NET application on it? I wouldn't do any of that as I don't think we ever stated to officially support WSL1 as a distro for .NET.

**Comment by wfurt** [comment]
I don't think we need to build on or for WSL1. We shall triage bug reports from official releases and prioritize them accordingly. (and the priority may be low)

**Comment by ManickaP** [comment]
Yep, WSL2 is not considered as "WSL" in our tests (the conditional attribute is not hit and these tests are executed). AFAIK, we don't have any tests disabled against it, the list above is for WSL1.

We have also already decided in some issues that we're not making changes just to support WSL1 (e.g. #26730)

Lastly, WSL2 is not without its issues, e.g. https://github.com/microsoft/WSL/issues/4322 hit in here https://github.com/dotnet/runtime/issues/687

**Comment by danmosemsft** [comment]
If the goal is simply "make sure developers working on our libraries can get a clean test run on WSL2" then if I understand @tarekgh correctly, there is nothing to do, except remove the attributes (purely for tidiness)

**Comment by tarekgh** [comment]
> if I understand @tarekgh correctly, there is nothing to do, except remove the attributes (purely for tidiness)

Right, in addition to closing all WSL1 issues. I don't know if there are any specific build/test scripts handle WSL1 though. @ViktorHofer may know better about that.

**Comment by ViktorHofer** [comment]
No there's is no infra related to WSL1 except the PlatformDetection.IsWindowsSubsystem property. FWIW I think Santi did some networking work in the past specifically for WSL1 in the product.

**Comment by ManickaP** [comment]
@danmosemsft I'd personally keep the attributes until WSL2 is officially out. If you get rid of them now, the only thing it will do is to make test failing on WSL1. We're not running them anywhere, it's just for people working on WSL1, who usually do not want to do Insider Preview. And we might see some issues pop up due to it.

Though we should be clear on not supporting WSL1 and decide to what extent we will support WSL2 and be unified in this towards community.

**Comment by danmosemsft** [comment]
Either seems reasonable

**Comment by wfurt** [comment]
I'm wondering if it would make sense to update the name to *1 for clarity as well as add some explicit notes to building instructions to avoid wasted time for people who may try on WSL1 ... and fail.

**Comment by ManickaP** [comment]
@wfurt That's actually a great idea. We might need detection for WSL2 in the future and this would make it easier and more clear.

**Comment by tarekgh** [comment]
I think we don't want this detection. users can run `wsl -l -v` and that will give them the needed information.

**Comment by ViktorHofer** [comment]
Sure we could do that or wait another month until Win10 2004 is released and remove the property and all the attributes with it.

**Comment by ManickaP** [comment]
So let's wait for official WSL2 rollout, then get rid of the `PlatformDetection.IsNotWindowsSubsystemForLinux` and if any issues for WSL1 pops up afterwards, we'll steer the users to use WSL2.

**Comment by geoffkizer** [comment]
WSL2 is generally available now, right? Should we address this issue now?

There are a bunch of tests in System.Net.Sockets that are disabled via `IsNotWindowsSubsystemForLinux`; I'm concerned that I'm missing test coverage when I develop with WSL2.

**Comment by ViktorHofer** [comment]
> There are a bunch of tests in System.Net.Sockets that are disabled via IsNotWindowsSubsystemForLinux; I'm concerned that I'm missing test coverage when I develop with WSL2.

Those conditions don't apply on WSL2 anyway so it shouldn't be a concern but as we don't support WSL1 officially we should just get rid off them.

**Comment by geoffkizer** [comment]
> Those conditions don't apply on WSL2 anyway so it shouldn't be a concern

I'm running WSL2 and I saw that these tests were skipped. So it looks to me like the conditions apply to WSL2 as well.

**Comment by wfurt** [comment]
https://github.com/dotnet/runtime/blob/3846a9c4e5529ab1da1d58058f86502da85fead6/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Windows.cs#L110-L123

This could possibly misfire for Azure cloud linux https://en.wikipedia.org/wiki/CBL-Mariner

My suggestion would be to  either bound `WindowsSubsystemForLinux` to WSL1 or simply remove it completely and live with fact that some tests would fail on WSL1

**Comment by ViktorHofer** [comment]
We don't support WSL1 both from an infra and product code perspective and should just remove these attributes entirely.

**Comment by ViktorHofer** [comment]
So here's the proc/version string on my Ubuntu WSL2 instance: `Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021`.

The condition applies to WSL2 as well because the code checks for "WSL". I will submit a PR to remove this check and the attributes entirely.
