### ISSUE TITLE
Exception message for AmbiguousMatchException should include the name

### ISSUE THREAD

**Issue by bradwilson** [dotnet/runtime#18255]
Fundamentally, this is an indication of a bad argument, without telling you what the bad value is, which usually demands that you fire up the debugger to figure it out. It would be helpful to know what the ambiguous name actually was.

```
System.Reflection.AmbiguousMatchException : Ambiguous match found.
Stack Trace:
    at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
    at System.Type.GetMethod(String name)
```

**Comment by GrabYourPitchforks** [comment]
Let's tentatively try to make this a little better in 5.0 for debuggability. Though it's low-priority compared to other reflection work so it may still slip below the cut line.

**Comment by terrajobst** [comment]
Like #34703

**Comment by danmosemsft** [comment]
My 2c. Many times issues first show up in logs. A debugger may not be available - nor dump file - nor even a repro. If by changing some localized places to add some value that we have easily available into that message, we can make some of these diagnosable without further work. It seems a place where relatively small work in a library is highly leveraged. This is why we added keys to key not found exceptions, paths to file not found exceptions. Of course there are cases where it is not worth it but there are still plenty of cases we we do not have a good reason to not do it.

> GetMethodImpl is just one of the places where the exception gets thrown. In order to get a consistent behavior, 

I don't think consistency for its own sake is important in these messages. In making changes of this sort in the past, I just skipped cases where it is difficult/impossible to supply the value. Eg., some of the IO exception paths. Most of our exception types were originally designed to have an optional "parameter" -- they already come in helpful and less helpful forms. We just prefer the more helpful form if we can.

**Comment by danmosemsft** [comment]
Not required to ship 5.0 product. Setting milestone.

**Comment by steveharter** [comment]
Still seems like a valid request; there are ~24 cases currently: https://github.com/dotnet/runtime/search?q=%22new+AmbiguousMatchException%22&type=code

**Comment by IDisposable** [comment]
If I were to take this on, would it be reasonable to add a format string to `Strings.resx` for the new formatted versions of the error messages? 
Something like these two new ones paralleling the current messages that don't name the ambiguity:
```xml
  <data name="Arg_AmbiguousMatchExceptionNamed" xml:space="preserve">
    <value>Ambiguous match found for {0}.</value>
  </data>
  <data name="AmbiguousImplementationException_NullMessageNamed" xml:space="preserve">
    <value>Ambiguous implementation found for {0}.</value>
  </data>
```
Then in the throw-sites, would grab the argument string of whatever we're ambiguous about format away.

For the throw-sites where where we HAVE a `MemberInfo`, we could use the `MemberInfo.DeclaringType.Name` and `MemberInfo.Name` or something like that (and emit it is "type.member" in the exception). Would that case warrant _two_ new format strings or is there a standard helper I would use to gen up a runtime-safe human-readable name of the class/member?

**Comment by IDisposable** [comment]
Maybe `Console.WriteLine("Ambiguous implementation found for {0} {1}", data.DeclaringType.ToString(), data.ToString());` which results in `Ambiguous implementation found for System.String Int32 Length`?

**Comment by IDisposable** [comment]
Additionally, it's plausible in cases like [DefaultBinder.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/DefaultBinder.cs#L387) we actually have a lot more than just one method... is there value in having this exposed in more detail?

**Comment by danmoseley** [comment]
re parallel strings, we do this for IO, eg.,
```
  <data name="UnauthorizedAccess_IODenied_NoPathName" xml:space="preserve">
    <value>Access to the path is denied.</value>
  </data>
  <data name="UnauthorizedAccess_IODenied_Path" xml:space="preserve">
    <value>Access to the path '{0}' is denied.</value>
  </data>
```
and of course try our best to only use the one with the more info, but they are both there.

**Comment by danmoseley** [comment]
I don't own this area but I think you'd be welcome to take it @IDisposable. do you want me to assign to you?

**Comment by IDisposable** [comment]
Cool, thoughts on [formatting](https://github.com/dotnet/runtime/issues/18255#issuecomment-1500548382) and if emitting details where we have [multiple ambiguous possibilities](https://github.com/dotnet/runtime/issues/18255#issuecomment-1500554614)?

I'm thinking that (for example in DefaultBinder), we could just emit the `CurMin`'s details... otherwise we would have to add some state to hold the information... seem like too much work.

**Comment by IDisposable** [comment]
Updated example format strings per replacement standard [mentioned above](https://github.com/dotnet/runtime/issues/18255#issuecomment-1500570726)

**Comment by danmoseley** [comment]
I think an area owner like @steveharter should advise.

**Comment by IDisposable** [comment]
Draft PR #84512 for commentary as to my approach and to let the build bots test it :)

**Comment by buyaa-n** [comment]
I think the issue is asking for adding a member info in case no member info is provided. i.e:
instead of just `Ambiguous match found.` add member info: `Ambiguous match found for: {0}`

I don't feel we really need to change `Ambiguous match found for: '{0}'.` with `"Ambiguous implementation found for: '{0} {1}'`. Not sure if adding a `memberInfo.DeclaringType` info adds much clarification here:
```cs
    internal static AmbiguousMatchException GetAmbiguousMatchException(MemberInfo memberInfo)
    {
        Type? declaringType = memberInfo.DeclaringType;
            return (declaringType is not null)
                ? new AmbiguousMatchException(SR.Format(SR.Arg_AmbiguousMatchException_Detailed, declaringType, memberInfo))
                : new AmbiguousMatchException(SR.Format(SR.Arg_AmbiguousMatchException_Simple, memberInfo));
    }
```
