### ISSUE TITLE
.NET Standard Library vs. .NET Platform Standard vs. NETStandard.Library

### ISSUE THREAD

**Issue by tthiery** [dotnet/runtime#18312]
There are some [references ](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) that the ".NET Standard Library" is covered in the `NETStandard.Library` package. However, there are libraries (especially agnostic libraries) like `System.Xml.XPath` or `System.Collcetions.Immutable` which seem to be [part](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) of the ".NET Standard Library" and/or ".NET Platform Standard" but are not added as a dependency to `NETStandard.Library`.

Do I misunderstand something here, or is the naming/documentation of the meta package `NETStandard.Library` just a bit odd?

**Comment by ericstj** [comment]
Closing this out as it is now 2 years old.

In general what is in NETStandard can be defined by *types* not assemblies.  Those types are the ones defined in `netstandard.dll`.

There are many packages that target NETStandard.  Those packages can be used on NETStandard but are not "part of" NETStandard.

The benefit here is that we can still evolve the API of packages that support NETStandard on existing platforms, whereas the content of "netstandard.dll" is fixed once it is defined.
