### ISSUE TITLE
Reintroduce the use of reflection methods in DynamicObject

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/runtime#18407]
It's using `GetMember` with `OfType<MethodInfo>` to filter the members in `IsOverridden`. Also noticed that the `Bind*` methods create a closure that's only needed in a conditional branch that typically won't be taken, but that may not be a big deal because these should only be called once per dynamic call site.

**Comment by cston** [comment]
> @bartdesmet dealt with this himself between dotnet/corefx#13963 and dotnet/corefx#13969 so this can be closed.

Thanks. Closing.
