### ISSUE TITLE
StringBuilder should have all functionality of String

### ISSUE THREAD

**Issue by int19h** [dotnet/runtime#18417]
`StringBuilder` is, essentially, just a mutable version of `String`. Consequently, it would make sense for it to have all the functionality that `String` has, with in-place mutating versions where appropriate. Right now it has a subset that doesn't seem particularly coherent - e.g. there's indexing, but no `Substring`. Some other missing members include `IndexOf`, `Contains`, `Find`, `Pad...`, `ToLower` and `ToUpper` etc. Basically, it should be possible to do anything you could do with a `String` without actually creating a string (to avoid unnecessary copies).

There is also a matter of consistency - the same pattern with an immutable value class and a mutable builder version is also repeated with `Uri` and `UriBuilder`, but there the builder does actually reproduce the API surface of the immutable class much closer.

**Comment by GrabYourPitchforks** [comment]
A reminder: this issue as currently stated is not actionable by the team. Since there's not a general desire to add the entire suite of `string` APIs to `StringBuilder` we'd need a list of specific APIs that everybody feels are missing.

**Comment by manigandham** [comment]
@jnm2 

.NET Core 3.0 released with `StringBuilder.GetChunks()` that allows for scanning through all the buffers inside. (Issue #26207)

There's no built in `IndexOf` method but here's a simple example (you can make it an extension method):

```csharp
public static int IndexOf(StringBuilder sb, char c)
{
    var pos = 0;
    foreach (var chunk in sb.GetChunks())
    {
        var span = chunk.Span;
        for (var i = 0; i < span.Length; i++)
            if (span[i] == c)
                return pos + i;

        pos += span.Length;
    }

    return -1;
}
```

**Comment by GrabYourPitchforks** [comment]
Per comment at https://github.com/dotnet/runtime/issues/18417#issuecomment-586568423, issue is not currently actionable by the team. Closing. Please reopen the issue if further discussion is warranted. Thanks!
