### ISSUE TITLE
Set sensible default value for HttpClientHandler.MaxConnectionsPerServer

### ISSUE THREAD

**Issue by dannsam** [dotnet/runtime#1844]
Sending a few thousands requests to a single server resulted in running out of socket connections in our azure webapp.

Mostly because every concurrently executed request was creating a new connection.
The default value for HttpClientHandler.MaxConnectionsPerServer is `int.MaxValue`.
.Net framework has the default value set to 2 (or 10 for ASP.nET hosted applications).

> On **.Net Full framework**, you can control the number of outgoing client connections by setting `ServicePointManager.DefaultConnectionLimit` to the desired number. It is 2 by default.
> On **.Net Core**, you can set it by changing `HttpClientHandler.MaxConnectionsPerServer` to your desired limit. The default is `int.MaxValue` -- much higher than the default for the full framework.
from https://docs.microsoft.com/en-gb/archive/blogs/timomta/controlling-the-number-of-outgoing-connections-from-httpclient-net-core-or-full-framework

The default value is not realistic - not enough ports to open 2 billion connections, the max would be at most 65535 or actually smaller considering the reserved ports (https://stackoverflow.com/questions/113224/what-is-the-largest-tcp-ip-network-port-number-allowable-for-ipv4).

I wonder if it's possible to set the default value to something much more realistic to avoid apps running out of sockets. Dropping it to 2 or 10 can be a very breaking change, but even setting it to 256 would be a much better default.

**Comment by scalablecory** [comment]
I don't know that I'd want to change the default here, but what I might be okay with is if we can detect port exhaustion and throw an exception that leads users to setting that value themselves.

**Comment by wfurt** [comment]
I agree with @scalablecory . The current default is generally `unlimited` and restricted by OS and TCP constrains. 65535 may not necessarily be the cap if server is reachable by multiple IP addresses. 

Right now all the connection handling is opaque to the caller. I'm wondering if it would be useful to expose some metrics - like connections used. I personally feel that if we detect port exhaustion it is too late. Alternatively one could use HTTP/2. I think the crux is to reuse existing connections as much as possible to avoid deployment issues.

**Comment by dannsam** [comment]
> 65535 may not necessarily be the cap if server is reachable by multiple IP addresses

It may not be the cap for the destination server, but your server still has a limited number of ports. Azure web apps have much lower connection limits - 1920 for basic and standard tiers.

There are a few of reasons why I think it's an issue that needs to be fixed with a more realistic default:
- Default values in .NET Framework and .NET core are very very different 2 vs 2 billions. 
- It's not always possible to pass HttpClient or handlers to nuget packages, eg Azure Storage SDK does not allow configuring HttpClient. As the result, it seems that I have to wrap some calls with Semaphores to avoid socket exhausting.
- The default value is not realistic - why not change it if it's an incorrect value in pretty much 100% cases?

**Comment by alnikola** [comment]
I also think we shouldn't change the default here since it can negatively affect existing applications (even setting it to 256 can cause a throughput degradation). In my opinion, it might be better to ask Azure Storage SDK team to expose this parameter through their API.

**Comment by karelz** [comment]
Triage:
* Are you running out of ephemeral ports? That would mean you are not reusing same `HttpClient`. One would hit this case only if they are connecting truly to 2K+ different endpoints. E.g. a web crawler scenario. Is that the case here?

Overall, we think that hitting the limit on too many endpoints is fairly rare. The libraries that want to be part of such scenarios should expose the setting and apply it to the Handlers they are creating.
We do not believe that having static global setting of `MaxConnectrionsPerServer` is a reasonable thing to expose (note: it is reasonable for app-config settings like default proxies).
Closing.
