### ISSUE TITLE
Proposal Max, Min for IComparable

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#18481]
``` csharp
public static class Math
{
    public static T Min<T>(T val1, T val2) where T : IComparable<T>;
    public static T Min<T>(T val1, T val2, IComparer<T> comparer);

    public static T Max<T>(T val1, T val2) where T : IComparable<T>;
    public static T Max<T>(T val1, T val2, IComparer<T> comparer);

    // ref returning version?
    public static ref T Min<T>(ref T val1, ref T val2) where T : IComparable<T>; 
    public static ref T Max<T>(ref T val1, ref T val2) where T : IComparable<T>;
}
```

/cc @NickCraver @DamianEdwards @terrajobst

**Comment by Tratcher** [comment]
Today I really wanted `Max(timeSpan1, timeSpan2);`. Yes there are many other ways to write this, but none so concise.

**Comment by tannergooding** [comment]
This is essentially the same as https://github.com/dotnet/runtime/issues/85979

A generic `Max`/`Min` method already exists as `INumber<T>.Max/Min`. If we were to expose any generic `Max/Min` on Math it would match this behavior, and not the behavior of `IComparable<T>`. That is, it would be constrained to `where T : INumber<T>`

In particular, `IComparable` takes into account `.NET Equality` rules, such as are suitable for hash based collections or sorting. It doesn't necessarily do the same as the underlying relational operators (`<`, `<=`, `>`, `>=`, `==`, and `!=`) which are more oriented towards the types and their "mathematical properties". The simplest example of this difference is with the `floating-point` types where `NaN` exists.

I don't think we have a good place to expose such an `IComparable.Clamp` method (nor Min/Max/etc) and they are simple enough that any developer could roll their own if they desired it for their own codebases.

A separate proposal to expose `Min`, `Max`, and `Clamp` explicitly on `TimeSpan` would not be unreasonable and might be worth suggesting.

**Comment by svick** [comment]
@tannergooding Since it's three methods now (+ overloads?), and not just one, maybe that's getting close to making it worth having a separate class for this, called something like `Comparable`?

With a name like that, it should be fairly clear that it uses `IComparable<T>` and not the operators, so it shouldn't be *that* surprising that e.g. `Comparable.Clamp<float>` doesn't behave the same as `float.Clamp`.

**Comment by tannergooding** [comment]
I would be amenable to someone opening such a proposal and would be willing to take it to API review.

**Comment by tannergooding** [comment]
Closing this as not something we're planning, as per the above I'd be open to someone opening a proposal covering an explicit `static class Comparable` that exposes `Min`/`Max`/`Clamp` with the relevant constraints.
