### ISSUE TITLE
Load assemblies with nuget package dependencies

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [dotnet/runtime#18527]
I have been trying to dynamically load assemblies that have dependencies on nuget packages, of course the nuget packages have been restored and the proper dlls are present in the output folder.

I do this to load the assembly:
`var aName = AssemblyLoadContext.GetAssemblyName(file.FullName);`
`var library = Assembly.Load(aName);`
And then I load the types like this:
`types = library.GetTypes();`
When the assembly does not uses any dependency, the types are loaded correctly, but when the assembly uses a nuget package I get an exception with a loader exception like this:
`Message = "Could not load file or assembly 'needletail_dotnet_core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified."`

I can dynamically load the assemblies that are part of the nuget packages and get their types.

So my question is how to load assemblies that have nuget packages(or any other) depenency on dotnet core?

I am using dotnet version 1.0.1 Build cee57bf6c981237d80aa1631cfe83cb9ba329f12.

Some suggested answers on the internet use beta versions of dotnet core.

**Comment by TobiasKoller** [comment]
I had to load multiple assemblies and all its dependend assemblies (local and nuget) in a custom context because each assembly could have references to an assembly with different versions.

I first tried to load each assembly by using `DependencyContext.Load(myassembly)` but this returned always `null` which drove me crazy :-).

So I figured out that `DependencyContext.Load(myassembly)` only returns a context when you load .net core assemblies which have a deps.json-file with the same name as the used assembly in the same directory. All dependend (including none .net core) will resolved by using the `Resolving`-Method.

my.example.dll
my.example.deps.json


Here is my code which worked for me (I used this [[Link](https://www.codeproject.com/Articles/1194332/Resolving-Assemblies-in-NET-Core)] codeproject and made my modifications to it.).
It finds local dependencies and nuget assemblies.


```
public sealed class AssemblyResolver : IDisposable
    {
        private readonly ICompilationAssemblyResolver _assemblyResolver;
        private readonly DependencyContext _dependencyContext;
        private readonly AssemblyLoadContext _loadContext;
        public Assembly InitialAssembly { get; }

        public AssemblyResolver(string assemblyPath)
        {
            //this assemblyPath has to have a deps.json-file in the same directory.
            InitialAssembly = Assembly.LoadFile(assemblyPath);
                        
            _dependencyContext = DependencyContext.Load(InitialAssembly);

            var resolver = new ICompilationAssemblyResolver[]
            {
                new AppBaseCompilationAssemblyResolver(Path.GetDirectoryName(assemblyPath)),
                new ReferenceAssemblyPathResolver(),
                new PackageCompilationAssemblyResolver()
            };

            _assemblyResolver = new CompositeCompilationAssemblyResolver(resolver);
            
            _loadContext = AssemblyLoadContext.GetLoadContext(InitialAssembly);
            _loadContext.Resolving += OnResolving;
        }

        /// <summary>
        /// returns all assemblies of the current context.
        /// </summary>
        /// <returns></returns>
        public List<Assembly> GetAssemblies()
        {
            return _loadContext.Assemblies.ToList();
        }

        /// <summary>
        /// Resolving dependencies of the assembly
        /// </summary>
        /// <param name="context"></param>
        /// <param name="name"></param>
        /// <returns></returns>
        private Assembly OnResolving(AssemblyLoadContext context, AssemblyName name)
        {
            bool NamesMatch(RuntimeLibrary runtime)
            {
                var res = string.Equals(runtime.Name, name.Name, StringComparison.OrdinalIgnoreCase);
                if(!res)
                {
                    //iterate through every assemblygroup. This will recognize also assemblies in nuget-packages.
                    foreach(var group in runtime.RuntimeAssemblyGroups)
                    {
                        foreach(var l in group.RuntimeFiles)
                        {
                            if (Path.GetFileNameWithoutExtension(l.Path) == name.Name) //optional version-check:  && l.AssemblyVersion == name.Version.ToString())  
                                return true;
                        }
                    }
                }

                return res;
            }

            RuntimeLibrary library = _dependencyContext.RuntimeLibraries.FirstOrDefault(NamesMatch);
            if (library == null)
                return null;

            var wrapper = new CompilationLibrary(
                                library.Type,
                                library.Name,
                                library.Version,
                                library.Hash,
                                library.RuntimeAssemblyGroups.SelectMany(g => g.AssetPaths),
                                library.Dependencies,
                                library.Serviceable
                            );

            var assemblies = new List<string>();
            _assemblyResolver.TryResolveAssemblyPaths(wrapper, assemblies);
            var assembly = assemblies.FirstOrDefault(a => Path.GetFileNameWithoutExtension(a) == name.Name);

            return assembly==null
                    ? null
                    : _loadContext.LoadFromAssemblyPath(assembly);

        }

        public void Dispose()
        {
            _loadContext.Resolving -= this.OnResolving;
        }
    }
```

**Comment by WaleedNaveed** [comment]
I am getting the same issue with Quartz NuGet package. Can anyone help me to resolve it ?

**Comment by NMSAzulX** [comment]
Hi! Everyone! 
I've done something similar before, which requires include two tags into the csproj file, 
```C#
  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>
```
and then using :
```C#
DependencyContext
            .Default
            .CompileLibraries   //todoSth
```

We use it in Web services and in some console programs. It works well, but it creates an extra refs folder, which increases the size of App, which makes me miserable. I don't know if there's a better way. This size is unacceptable to my customers, which gives me a headache.
