### ISSUE TITLE
X509Extension.Format() in .NETFramework\v4.5\System.dll failed to return the full result

### ISSUE THREAD

**Issue by shidouli** [dotnet/runtime#1852]
In c#, trying to do format an X509Extension object, the result is just half, not the full string

string caStr = caExt.Format(false); // caExt is X509Extension object

The caStr is: '[1]Authority Info Access: Access Method=On-line Certificate Status
Protocol (1.3.6.1.5.5.7.48.1), Alternative Name=URL=http://ocsp.digicert.com'.

But in powershell, we can get the full result of the Format():
PS C:\WINDOWS\system32> $ext.Format($false)
[1]Authority Info Access: Access Method=On-line Certificate Status Protocol (1.3.6.1.5.5.7.48.1), Alternative Name=URL=http://ocsp.digicert.com, [2]Authority Info Access: Access Method=Certification Authority Issuer (1.3.6.1.5.5.7.48.2), Alternative Name=URL=http://cacerts.digicert.com/DigiCertSHA2HighAssuranceServerCA.crt

Please help to take a look to see how to get the full result of the Format() in c#, thanks!

**Comment by wfurt** [comment]
If the issue is really .NETFramework , this repo is wrong place to file it.

cc: @bartonjs

**Comment by shidouli** [comment]
Thanks wfurt, then where is the right place for this issue?

**Comment by wfurt** [comment]
You can try https://developercommunity.visualstudio.com/content/problem/post.html?space=61
Also did you try it with 4.8 and possibly .Net Core? 
It seems unlikely issue like this would get approval for 4.5 back-port.

**Comment by shidouli** [comment]
I tried it with 4.7.2, and also the .net core

**Comment by shidouli** [comment]
Thanks wfurt, has filed https://developercommunity.visualstudio.com/content/problem/891290/x509extensionformat-in-netframeworkv45systemdll-fa.html

**Comment by wfurt** [comment]
That seems like right place. If you can reproduce it with .Net Core, please post simple runnable repro.

**Comment by shidouli** [comment]
Yes, this issue could be reproduced in windows, linux. And for mac os, it has another issue, it even cannot format the X509Extension to a string (https://github.com/dotnet/corefx/issues/41775#issuecomment-542035240).

And to repro it, here is the special certificate string:

-----BEGIN CERTIFICATE-----
MIIG6TCCBdGgAwIBAgIQDjBmqUSf4l8L25iehJFEnjANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0xODEyMjAwMDAwMDBaFw0yMTAzMTUxMjAwMDBa
MHUxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRIwEAYDVQQHEwlQ
YWxvIEFsdG8xFTATBgNVBAoTDFZNd2FyZSwgSW5jLjELMAkGA1UECxMCSVQxGTAX
BgNVBAMMECouZW5nLnZtd2FyZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQDEjiAJ6gdGIwsST8o5lutXHBHkoQp31lsuMv/INkcv4W5bzX1iTDN+
l5OsTt9qVR1ILDUFmIrybSsjxErVvFn2L3luFiWybK9YjNbgSRU+iktgGKoNw7PC
5lTf3PmyQblh2cVrzVAJYrVL4BQqxvaV9ri0TyPAg9vSca4U2dvADFJ81qzhBkvF
owvWb7ExEzvsU9JmKgK/8LIqq7xd0bVWdkwIkRuv8cMEHd0Tx3FLBIkYtDY5Fq03
YpzIT5Ks8pXuscP0wFIAAhO1pWmSPvWHfSIII5FpE/RkgrYu2aGVwQMJ6r2wnYfF
C0oqEecE8BSo2WG9x26ZymwMNAIQzpW3AgMBAAGjggN4MIIDdDAfBgNVHSMEGDAW
gBRRaP+QrwIHdTzM2WVkYqISuFlyOzAdBgNVHQ4EFgQUujfU0+h7t1RVYxLgTY4U
V5bCQ8MwKwYDVR0RBCQwIoIQKi5lbmcudm13YXJlLmNvbYIOZW5nLnZtd2FyZS5j
b20wCwYDVR0PBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB1
BgNVHR8EbjBsMDSgMqAwhi5odHRwOi8vY3JsMy5kaWdpY2VydC5jb20vc2hhMi1o
YS1zZXJ2ZXItZzYuY3JsMDSgMqAwhi5odHRwOi8vY3JsNC5kaWdpY2VydC5jb20v
c2hhMi1oYS1zZXJ2ZXItZzYuY3JsMEwGA1UdIARFMEMwNwYJYIZIAYb9bAEBMCow
KAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EM
AQICMIGDBggrBgEFBQcBAQR3MHUwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
Z2ljZXJ0LmNvbTBNBggrBgEFBQcwAoZBaHR0cDovL2NhY2VydHMuZGlnaWNlcnQu
Y29tL0RpZ2lDZXJ0U0hBMkhpZ2hBc3N1cmFuY2VTZXJ2ZXJDQS5jcnQwDAYDVR0T
AQH/BAIwADCCAX4GCisGAQQB1nkCBAIEggFuBIIBagFoAHcApLkJkLQYWBSHuxOi
zGdwCjw1mAT5G9+443fNDsgN3BAAAAFnzd5JuwAABAMASDBGAiEAtydhgdY+E4/Y
HTPmT91aN0JBNqKOm0CspS1FEdfr9n0CIQC3dZUIMiiWsZ1ZhHSr1+uUbL07q5eD
wxgqoh8hAGsiIwB2AId1v+dZfPiMQ5lfvfNu/1aNR1Y2/0q1YMG06v9eoIMPAAAB
Z83eSpgAAAQDAEcwRQIgS867YZm6bn6xCHMJNKHnKK39+LyJeeCkhigAffmQPSwC
IQDYRqfqADWYDiC39ANlaKM7uDbCzZFtXAPHEyytcoq1ZQB1AG9Tdqwx8DEZ2JkA
pFEV/3cVHBHZAsEAKQaNsgiaN9kTAAABZ83eSxsAAAQDAEYwRAIgJ7wiJA8Uz+Ro
rxE85YM6gQ9asYpWW9PVYnTMtDxTU4ACIGOk9Lx2a/741DMZLGIPbdvzmMnVk7CO
RSlrL5dyLJSUMA0GCSqGSIb3DQEBCwUAA4IBAQBpyl22ECchxGP2dAbY5TaE4MF7
YPFLEW7SaEdm4SOoWP6PqBHLj9XmVa3besC8+GzlEJAYT1NVLPZd0SDs3Ssbmvuz
LdAUi2z36rOl3t7gyTQUFJszXjjZewRdNCHf4fFbErYjCBf1L8gV/OnG9Sa37Se8
q3P8lbWs0kRhp4i+tjEClSNyli2WHpmSD09Yd5XjArRNPuC6Yit6RWEo5fGD5si0
afngN2ZDSKBvNMG4o3HB/2V9FEY7t5YiaIpnIjhh6RMK530kVJI4+tfH7Mk5NPQU
sFw6AFEh+ylNvTxMLH+8zDkL0THzFBYG+4HiKupH+CpfRNOOAcG3pCIapExl
-----END CERTIFICATE-----

The code is:

private void RetrieveCAUrl (X509Certificate2 certificate,
                                                string file, out string uri) {
         X509Extension caExt = null;
         foreach (X509Extension ext in certificate.Extensions) {
            if (ext.Oid.Value.Equals("1.3.6.1.5.5.7.1.1")) {
               caExt = ext;
               break;
            }
         }

         if (caExt == null) {
            throw new Exception("Failed to find out the CA authority info from the given certificate!");
         }

         string caStr = caExt.Format(false);

         if (!caStr.Contains("Issuer")) {
            throw new Exception("Failed to find the CA Issuer info from the given certificate: " + caStr);
         } else {
            int idx = caStr.IndexOf("Issuer");
            caStr = caStr.Substring(idx);
         }

         uri = null;
         if (caStr.Contains("http")) {
            int idx = caStr.IndexOf("http");
            uri = caStr.Substring(idx);
         }

         if (string.IsNullOrEmpty(uri)) {
            throw new Exception("Failed to find out the CA authority URL from the given certificate!");
         }

         // if there are multiple URLs in the certificate
         int idx2 = uri.LastIndexOf("http");
         string tempUri = uri.Substring(idx2 + 4);
         if (tempUri.Contains("http")) {
            int tidx = tempUri.IndexOf("http");
            tempUri = tempUri.Substring(tidx);
            if (tempUri.EndsWith(")")) {
               tempUri = tempUri.Substring(0, tempUri.Length - 1);
            }

            uri = tempUri;
         }

         Console.WriteLine("The uri retrieved is: " + uri);
      }

**Comment by bartonjs** [comment]
With your provided certificate, I see both values being printed on .NET Framework, and both values being printed on .NET Core 2.1 for Windows.

The output of `Console.WriteLine(ext.Format(false));`:

```
[1]Authority Info Access: Access Method=On-line Certificate Status Protocol (1.3
.6.1.5.5.7.48.1), Alternative Name=URL=http://ocsp.digicert.com, [2]Authority In
fo Access: Access Method=Certification Authority Issuer (1.3.6.1.5.5.7.48.2), Al
ternative Name=URL=http://cacerts.digicert.com/DigiCertSHA2HighAssuranceServerCA
.crt
```

The output of `Console.WriteLine(ext.Format(true));`:
```
[1]Authority Info Access
     Access Method=On-line Certificate Status Protocol (1.3.6.1.5.5.7.48.1)
     Alternative Name:
          URL=http://ocsp.digicert.com
[2]Authority Info Access
     Access Method=Certification Authority Issuer (1.3.6.1.5.5.7.48.2)
     Alternative Name:
          URL=http://cacerts.digicert.com/DigiCertSHA2HighAssuranceServerCA.crt
```


These strings are produced by the OS, not .NET (.NET just proxies the call to the OS).

Instead of parsing the string, you'd be better served to interpret the payload (ext.RawData) using something like the AsnReader from https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Security.Cryptography.Asn1.Experimental/0.1.1-e200121-1

**Comment by shidouli** [comment]
Yep, great, thanks bartonjs, I saw the root cause, as I downloaded the ca file recursively, the half-string got is from the 1st downloaded certificate.
