### ISSUE TITLE
Support equivalent of ComposeExportedValue in System.Composition

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/runtime#18624]
System.ComponentModel.Composition (MEF1) has the ability to supply imports to an already-instantiated object, via the `ComposeExportedValue<T>(T exportedValue)` method.  As requested by @ZigMeowNyan and @jabbera in dotnet/runtime#15362, it would be useful to have this ability in System.Composition (MEF2).

**Comment by ericstj** [comment]
I believe this is now tracked with  #29400
