### ISSUE TITLE
HttpWebRequest.GetRequestStreamAsync doesn't open the connection to the server - we always buffer the content

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#18632]
The corefx implementation of HttpWebRequest.GetRequestStreamAsync effectively just returns an in-memory stream.  The connection to the server isn't made and the data isn't uploaded until Stream.Dispose is called on the that Stream.  This is problematic for several reasons, including that the actual asynchronous operation ends up happening in the synchronous Dispose call on the stream, and deadlocks can easily happen if code assumes that the server will respond once the supplied data has been written (but before Dispose is called).

**Comment by liveans** [comment]
Fixed by https://github.com/dotnet/runtime/pull/95001
