### ISSUE TITLE
Update Fedora version used for testing

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#1864]
It looks like Fedora 2 9 is out of support.  See:
https://fedoraproject.org/wiki/End_of_life
https://fedoraproject.org/wiki/Releases

Discussed here:
https://github.com/dotnet/core-eng/issues/8619

We also need to port this fix back to servicing where we originally noticed this.

We should also designate someone as our distro-lifecycle-champion so that we can proactively plan for these things rather than react to breaks that occur afterwards.

**Comment by ericstj** [comment]
@bartonjs is this something that you track?

**Comment by bartonjs** [comment]
"track" is apparently a generous word, but I think I'm the one currently responsible for it... barring anyone wanting to take it over (or getting voluntold).
