### ISSUE TITLE
SortedDictionary.First performance

### ISSUE THREAD

**Issue by mjp41** [dotnet/runtime#18668]
Getting the `First` element of a `SortedDictionary` causes allocation of a stack that is log sized in the number of elements in the dictionary.  This can be done without any allocation.

Currently, `First` is only an extension method for `SortedDictionary`.  This means it builds an `Enumerator`, and then uses that to get the first element.  The enumerator creates a stack to aid its traversal of the underlying RedBlack tree.  This seems the correct thing for the enumerator to do, but in the context of getting the single first element it is very costly.  There does not seem to be a sensible way to alter the enumerator to special case this use, without introducing conditionals and hence costs elsewhere. 

Would it be possible to make `First` a method of `SortedDictionary`, rather than an extension method, then it would be able to call `SortedSet.Min` directly?  I am not familiar with the repurcussions of making an extension method into an actual method.  Is there a way for this to break existing code, or not?

I can submit a Pull Request if that is the right way forward.

**Comment by TimLovellSmith** [comment]
@mjp41 So what you really wanted was a priority queue right? What did you do in the end, roll your own?

**Comment by bennidhamma** [comment]
Two more very useful properties that the Java TreeMap has are floorEntry and ceilingEntry

ceilingEntry(K key)
Returns a key-value mapping associated with the least key greater than or equal to the given key, or null if there is no such key.

floorEntry(K key)
Returns a key-value mapping associated with the greatest key less than or equal to the given key, or null if there is no such key.

**Comment by marcospgp** [comment]
Was surprised to find out there is no way to get the largest key of a Sorted Dictionary in C#. Is the only point of having one to be able to traverse it in order?

**Comment by danmoseley** [comment]
Noting in case others find this, since the above discussion a PriorityQueue<T> was added for .NET 6: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.priorityqueue-2?view=net-6.0

**Comment by yashl** [comment]
> Was surprised to find out there is no way to get the largest key of a Sorted Dictionary in C#. Is the only point of having one to be able to traverse it in order?

If you are looking to traverse in order, an OrderedDictionary will be more optimal given it is implemented using a combination of hashmaps and a double linked list instead of a heap https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary?view=net-5.0. 
With @danmoseley recent comment suggesting a recent implementation of a PriorityQueue, we have to no longer find packages to implement a heap, yay!

**Comment by marcospgp** [comment]
@yashl An ordered dictionary seems to be another thing entirely, it's not generic and does not maintain the keys in a sorted state.

The priority queue does seem to apply for this use case! Thank you @danmoseley

**Comment by danmoseley** [comment]
I think I can close this then, or is there any more to resolve here?

**Comment by marcospgp** [comment]
Priority queues are unfortunately not available in the .NET version shipping with the latest long term support version of Unity. Does anyone know of an alternative?

**Comment by danmoseley** [comment]
@marcospgp you could copy/paste the PriorityQueue code, it's MIT licensed. It's likely just PriorityQueue.cs and PriorityQueueDebugView.cs. However if you do distribute it, please change the namespace to avoid confusion.

**Comment by marcospgp** [comment]
@danmoseley Where can I find the source code? [Is this it](https://referencesource.microsoft.com/#PresentationCore/Shared/MS/Internal/PriorityQueue.cs)?

**Comment by samsosa** [comment]
@marcospgp
https://github.com/dotnet/runtime/tree/main/src/libraries/System.Collections/src/System/Collections/Generic

**Comment by danmoseley** [comment]
Right. I wasn't actually aware of the WPF one and I would recommend ours.

**Comment by marcospgp** [comment]
I tried copying the source code but run into a few issues with names not existing in context, such as with `SR`, `EnumerableHelpers`, `MaybeNullWhen`, and `Array.MaxLength`. I'm not sure how to include and where to find these.

**Comment by danmoseley** [comment]
SR is generated at build time -- if you build it will be in your artifacts folder. Or you could ILSPY System.Collections.Generic.dll after installing .NET 6.0 RC1.
The other three you can find in this repo and should be easy to either grab or snip the usage.

**Comment by marcospgp** [comment]
Hmm at that point it becomes complex enough that implementing a custom solution starts to seem like a good idea. Thanks for your help though!

**Comment by eiriktsarpalis** [comment]
I presume this has been addressed by the inclusion of PriorityQueue in .NET 6.
