### ISSUE TITLE
Stop producing Crossgen2 transport package (use Crossgen2 pack downstream instead)

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1869]
The Crossgen2 pack (https://github.com/dotnet/runtime/issues/906) will be built using live bits in the dotnet/runtime official build, so the transport pack is no longer necessary for that flow.

I'm not deleting the transport package infra right away because there may be some external dependencies on it. We should determine if there are any, and delete the redundant nupkg.

@fadimounir

**Comment by mangod9** [comment]
@AntonLapounov is there any work required here?

**Comment by AntonLapounov** [comment]
@dagood It seems we stopped producing `transport.Microsoft.NETCore.Crossgen2` package in February 2020. Can this be closed now?
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&view=versions&package=transport.Microsoft.NETCore.Crossgen2&version=5.0.0-alpha.1.20104.1&protocolType=NuGet

**Comment by dagood** [comment]
Yep. Seems fine to assume that either someone checked for dependencies before doing the removal, or if there were some unknown dependency, someone would have filed an issue about it since then.
