### ISSUE TITLE
 aspnet core 3.1    linux        ThreadPool.SetMinThreads is not work

### ISSUE THREAD

**Issue by gaojiandonggg** [dotnet/runtime#1872]
### To Reproduce

hello 
aspnet core 3.1  
 int processorCount = Environment.ProcessorCount;
 ThreadPool.SetMinThreads(processorCount * 5, processorCount * 100); 
run in docker  is not working by linux ,
but can working in  windows ,why?
 who can help me, thinks

**Comment by stephentoub** [comment]
> is not working by linux

How does that manifest?

What is the value of processorCount?

What is the return value of SetMinThreads?

**Comment by gaojiandonggg** [comment]
For example, if the system has 4 cores, then processorCount should be 4. In Windows and Linux systems, I can normally get the value from a container of Linux docker run, but if I start the instance with k8s, it will display as follows:

ThreadPool.ThreadCount: 16, Minimum work threads: 16, Minimum completion port threads: 16)



It might have something to do with the k8s Settings

**Comment by stephentoub** [comment]
Thanks, but I'm trying to understand what you mean by "is not working".  What is the symptom that you're reporting?  Is SetMinThreads returning false?  Are you querying GetMinThreads after you call SetMinThreads and it's not reporting the values you passed in?

**Comment by jeffschwMSFT** [comment]
cc @kouvel

**Comment by dktue** [comment]
We're having the same issue: It shows exactly like you told, @stephentoub .

**Comment by maxtyutmanov** [comment]
Same trouble on .net core 2.2.8 in docker under linux, using microsoft/dotnet:2.2-aspnetcore-runtime as base image. 
The code snippet that we use for thread pool configuration:

```
private static void ConfigureThreadPool(IConfiguration configuration)
{
	ThreadPool.GetMinThreads(out var currentMinWorkerThreads, out var currentMinIoThreads);

	System.Console.WriteLine(
		"Current thread pool config: min worker threads - {0}, min IO threads - {1}", 
		currentMinWorkerThreads, currentMinIoThreads);

	var newMinWorkerThreads = configuration.GetValue<int?>("MinThreadPoolWorkerThreads") ?? currentMinWorkerThreads;

	System.Console.WriteLine("Reconfiguring thread pool: min worker threads - {0}", newMinWorkerThreads);

	var success = ThreadPool.SetMinThreads(newMinWorkerThreads, currentMinIoThreads);
	if (success)
	{
		ThreadPool.GetMinThreads(out currentMinWorkerThreads, out currentMinIoThreads);
		System.Console.WriteLine(
			"Successfully reconfigured thread pool: min worker threads - {0}, min IO threads - {1}",
			currentMinWorkerThreads, currentMinIoThreads);
	}
	else
	{
		System.Console.WriteLine("Could not reconfigure thread pool");
	}
}
```

and this is the output I am getting:

> Current thread pool config: min worker threads - 80, min IO threads - 2
> Reconfiguring thread pool: min worker threads - 128
> Successfully reconfigured thread pool: min worker threads - 80, min IO threads - 2

The same code works fine when run locally on my Windows 10 machine.
I also tried setting System.Threading.ThreadPool.MinThreads in runtimeconfig.template.json, no success.
Any idea what could cause such behavior?

**Comment by kouvel** [comment]
It sounds like it might already be configured somehow. Could be through System.Threading.ThreadPool.MinThreads, can you check in <app>.runtimeconfig.json in the build output folder? It may also be overridden using an environment variable `COMPlus_ThreadPool_ForceMinWorkerThreads=0x50` using a hex value. Those settings would override the value set by `ThreadPool.SetMinThreads` despite it returning true.

**Comment by maxtyutmanov** [comment]
@kouvel `COMPlus_ThreadPool_ForceMinWorkerThreads=0x50` was exactly the reason, thank you!
The behavior of SetMinThreads looks non-intuitive to me though: it reported success, but did not change the settings.

**Comment by kouvel** [comment]
Yea looks like historical behavior, perhaps it was intended that returning true means that the values provided are valid rather than that the values were changed. Probably could fix.
