### ISSUE TITLE
Add support cross building Linux DAC to run on Windows

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#1874]
We have needs to do **Linux dump triage** on machines running Windows.

The current default plan is to simply cross compile the Linux DACs to run on Windows.  

The initial prototyping effort was #757.  It demonstrated the feasibility of making a cross OS compiled Linux DAC.

- [ ] Design DOC. Document findings and plans
- [x] Clean up existing usage of the term platform. 
- [x] Modify CMake files to make C++ defines depend on Target OS
- [x] Fix warnings and errors found by MSVC compiler
- [x] Temporary resolve code which doesn't compile when compiling cross OS
- [x] Fix type layout differences introduced by differences in compiler.  
- [x] Fix differences introduced by differences in #defines
- [x] Enable cross OS building Linux DAC in Windows build scripts
- [x] Enable cross OS building in CI
- [x] Build, sign and upload to symbol server during builds
- [x] Resolve functional limitations to support full SOS feature set
- [ ] Add tests

**Comment by tommcdon** [comment]
@sdmaclea can this issue be closed?

**Comment by sdmaclea** [comment]
Moved the remaining work to future as all 5.0 blocking work is complete.

On second thought closing as the remaining work is not for this repo.
