### ISSUE TITLE
HWIntrinsics: Avx/Avx2.InsertVector128 second arg not contained

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/runtime#1877]
From what I can tell, the `InsertVector128` overloads that accepted an address arg were removed with the undertanding that a load could be contained for the second vector arg.  That isn't happening currently, although I see it specifically mentioned in https://github.com/dotnet/coreclr/pull/22886

```C#
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
unsafe static float Insertf128()
{
    float* ptr = stackalloc float[20];

    var v = Sse.LoadVector128(ptr).ToVector256Unsafe();
    v = Avx.InsertVector128(v, Sse.LoadVector128(ptr + 16), 1);

    return v.ToScalar();
}
```

Current asm for the insert is

```asm
vmovups     xmm0,xmmword ptr [rax]  
vmovups     xmm1,xmmword ptr [rax+40h]  
vinsertf128 ymm0,ymm0,xmm1,1  
```

Same goes for `vinserti128` from AVX2

 cc @tannergooding

**Comment by tannergooding** [comment]
That's strange, the logic for saying a node can be contained looks to be here: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/lowerxarch.cpp#L2660.

Let me dig in a bit.

**Comment by tannergooding** [comment]
Ah, that was simple. The corresponding check is missing from: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/lowerxarch.cpp#L3396

**Comment by tannergooding** [comment]
I've marked this `up-for-grabs` since the fix is rather trivial. I'll also mark it as 5.0 milestone so I can do the fix myself if no one else grabs it first.

**Comment by saucecontrol** [comment]
Cool, thanks.  I haven't familiarized myself with the test setup for HWIntrinsics yet.  Would the fix for this require new tests, or would a jitdiff on the existing tests be sufficient to demonstrate it's working?

**Comment by tannergooding** [comment]
The current tests should validate the code is still correct, so just getting a diff to show the codegen improvement should be sufficient.
