### ISSUE TITLE
Intermittent failures downloading dot.net/dotnet-install.sh on ARM/ARM64 jobs 

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#1880]
Example failure:
`curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.:

Build links:
- https://dev.azure.com/dnceng/public/_build/results?buildId=488176&view=logs&jobId=0b1815a7-03b5-522f-cae6-ed3679ae3541&j=0b1815a7-03b5-522f-cae6-ed3679ae3541&t=6826b195-ec7f-582e-6676-c51056a0504e
- https://dev.azure.com/dnceng/public/_build/results?buildId=506571&view=logs&jobId=0b1815a7-03b5-522f-cae6-ed3679ae3541

First Responder Thread: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1580841106240?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1580841106240&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1580841106240

Seems to be intermittent. Opening as a tracking issue for #702.

**Comment by jkotas** [comment]
Hit by: https://github.com/dotnet/runtime/pull/2348

**Comment by jkotas** [comment]
Failed in https://github.com/dotnet/runtime/pull/2381/

**Comment by jaredpar** [comment]
Looks like we're hitting this frequently enough now that I opened a first responder thread https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1580841106240?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1580841106240&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1580841106240

**Comment by MattGal** [comment]
We lack retry logic there, opened https://github.com/dotnet/arcade/issues/4740 to address this and I have an FR engineer working on it.

**Comment by ViktorHofer** [comment]
This was fixed with https://github.com/dotnet/arcade/pull/4766. Closing.
