### ISSUE TITLE
ParameterInfo.HasDefaultValue throws System.FormatException on optional DateTime parameter

### ISSUE THREAD

**Issue by epsitec** [dotnet/runtime#18844]
When accessing `ParameterInfo.HasDefaultValue` for a parameter of type `System.DateTime`, I
get an unexpected `System.FormatException`.

`ParameterInfo.Attributes` is correctly set to `Optional | HasDefault`.

If the parameter is of any other value type (e.g. `decimal` or some custom _struct_) the
property works as expected. There is something specific to `DateTime` in the implementation
of `RuntimeParameterInfo.GetDefaultValueInternal()` which is broken.

Code snippet to test:

``` c#
public void Usage()
{
    var type = typeof (Foo);
    var ctor = type.GetConstructors ()[0];
    var para = ctor.GetParameters ()[0];
    // This throws an exception...
    Assert.True (para.HasDefaultValue);
}

static class Foo
{
    public Foo(System.DateTime value = default (System.DateTime)) { }
}
```

Exception:

![default-value](https://cloud.githubusercontent.com/assets/3872435/19062968/c8793004-89fe-11e6-9db3-b203f4c900d3.png)

**Comment by SingleAccretion** [comment]
@steveharter Given https://github.com/dotnet/coreclr/pull/17877 has been merged for quite some time now and the titular bug does not repro on .NET Core 3.1, maybe it is time to close this issue?

**Comment by danmosemsft** [comment]
I'm going to resolve based on comment above.

**Comment by danmosemsft** [comment]
I'm going to resolve based on comment above.
