### ISSUE TITLE
RSACryptoServiceProvider.KeySize setter not respected

### ISSUE THREAD

**Issue by morganbr** [dotnet/runtime#18863]
The RSACryptoServiceProvider.KeySize setter doesn't get respected when generating keys, or even when getting the value back through the getter. This is true on both core and full framework. This is more problematic on full framework since RSACryptoServiceProvider is returned from RSA.Create. For example:

```
            using (RSA rsa = new RSACryptoServiceProvider()) // Key size 1024 by default
            {
                rsa.KeySize = 2048;
                Console.WriteLine(rsa.KeySize); // outputs 1024
                var parameters = rsa.ExportParameters(false); // returns a key with a 1024 bit modulus
            }
```

**Comment by bartonjs** [comment]
Since .NET Framework is effectively frozen now, "no one" should be using RSACryptoServiceProvider on .NET (nee Core), and no one outside the product team has ever mentioned this (hi @morganbr, we miss you), it seems safe to just call it Won't Fix at this point.
