### ISSUE TITLE
ResourceManager doesn't properly support non string resources (track MSBuild fix)

### ISSUE THREAD

**Issue by alexperovich** [dotnet/runtime#18932]
The following tests fail on Unix platforms:
- System.Resources.Tests.ResourceManagerTests.GetObject(key: \"Int\", expectedValue: 42)
- System.Resources.Tests.ResourceManagerTests.GetObject(key: \"Float\", expectedValue: 3.14159)
- System.Resources.Tests.ResourceManagerTests.GetObject(key: \"Bytes\", expectedValue: [41, 42, 43, 44, 192, ...])
- System.Resources.Tests.ResourceManagerTests.GetStream
- System.Resources.Tests.ResourceManagerTests.GetResourceSet_NonStrings(key: \"Int\", expectedValue: 42)
- System.Resources.Tests.ResourceManagerTests.GetResourceSet_NonStrings(key: \"Float\", expectedValue: 3.14159)
- System.Resources.Tests.ResourceManagerTests.GetResourceSet_NonStrings(key: \"Bytes\", expectedValue: [41, 42, 43, 44, 192, ...])

See dotnet/corefx#12468

**Comment by buyaa-n** [comment]
@tarekgh seems microsoft/msbuild#2221 resolved and closed, should we close this issue?

**Comment by tarekgh** [comment]
@buyaa-n yes we don't have any action we can take in runtime repo so I am closing it.
