### ISSUE TITLE
Sockets uses ~30x more CPU in linux vs Windows?

### ISSUE THREAD

**Issue by wegel** [dotnet/runtime#1897]
I'm playing with a toy torrent download-only client (here: https://github.com/wegel/SimpleTorrentLeecher). Performance seems **very** nice on Windows: ~3-4% CPU, 30Mb RAM while maxing out my 400MBps connection with 50 peers.

However, the exact same test in linux (Ubuntu 18.04, 5.0.0-37 kernel, dotnet version 3.1.101) results in ~120% (1.2 cores) CPU (RAM is about the same, and global download peformance seems OK).

This is using TCP sockets exclusively, nothing fancy.

Can you tell me what I might be doing wrong? Thanks!

**Comment by wegel** [comment]
I'm using a System.IO.Pipelines.PipeReader to process incoming data, [here](https://github.com/wegel/SimpleTorrentLeecher/blob/master/SimpleTorrentLeecher.Client/PeerClient.cs#L88). I tried removing that PipeReader and just using a fixed buffer; doesn't seem to affect CPU usage, unfortunately.

**Comment by wegel** [comment]
Did some profiling using Rider in linux, and at first look it seems that most of the CPU time is spent in unmanaged code:

![image](https://user-images.githubusercontent.com/1017404/72668669-4aa11f00-39f7-11ea-96d7-a8bf95ff7a8c.png)

**Comment by scalablecory** [comment]
Are you able to make a self-contained sample that demonstrates this?

**Comment by wegel** [comment]
Basically, no, not really; the CPU usage might be triggered by connecting to actual remote peers with real latency, as far as we know. Have you looked at the code? It's only a few hundred lines of actual processing code, I'm pretty sure you'd be able to profile/trace it to your satisfaction.

You can try with Ubuntu's 18.04 Desktop torrent, [available here](http://releases.ubuntu.com/18.04/ubuntu-18.04.3-desktop-amd64.iso.torrent?_ga=2.17592187.31831378.1579463496-1348547383.1578635628).

I ran the program like so:
`/usr/bin/time dotnet SimpleTorrentLeecher.Demo/bin/Debug/netcoreapp3.1/SimpleTorrentLeecher.Demo.dll "/home/wegel/torrents/ubuntu-18.04.3-desktop-amd64.iso.torrent" "1 gib"`

Which gave me:
```
88.64user 44.18system 0:50.86elapsed 261%CPU (0avgtext+0avgdata 60204maxresident)k
0inputs+0outputs (0major+7156minor)pagefaults 0swaps
```
Running Ubuntu in Windows:
```
51.20user 42.10system 0:55.91elapsed 166%CPU (0avgtext+0avgdata 45824maxresident)k
0inputs+0outputs (0major+12777minor)pagefaults 0swaps
```

So even with that layer of "emulation", it's still taking significantly less CPU. Running in "pure" Windows, CPU seems to hover at 10-12% (versus 261% or 166% above), but I can't seem to find a way to get that figure from the console, or any kind of report, outside of actually looking at Task Manager.

**Comment by stephentoub** [comment]
> CPU seems to hover at 10-12% (versus 261% or 166% above)

Just to make sure we're comparing apples to apples, Windows reports percentage out of 100%, whereas on Linux 100% == 1 core. In other words, waving my hands, 12% CPU usage on Windows on an 8-logical core system would be 1 full core, and equivalent to a report of 100% on Linux.

**Comment by wegel** [comment]
Correct; however 100% is still significantly different than 266%.

**Comment by stephentoub** [comment]
Understood. But it's not 30x.

**Comment by wegel** [comment]
Closing this as the problem is most probably elsewhere, eg, it's around [here](https://github.com/wegel/SimpleTorrentLeecher/blob/d2662aef18bfc19b7cabbe7322fd4bb3b8bff344/SimpleTorrentLeecher.Client/BlockTransport.cs#L70) or [here](https://github.com/wegel/SimpleTorrentLeecher/blob/d2662aef18bfc19b7cabbe7322fd4bb3b8bff344/SimpleTorrentLeecher.Client/BlockTransport.cs#L48). Still don't know why the difference in CPU usage for those functions between windows and linux is so big, but it's not socket related, so I'll re-open a ticket if I find a way to reproduce this in the 2 environments in a reliable manner.
