### ISSUE TITLE
Inconsistence usage of type KeySizes in AesGcm (size in byte vs. size in bit)

### ISSUE THREAD

**Issue by dhcgn** [dotnet/runtime#1910]
In AesGcm.cs the properties NonceByteSizes and TagByteSizes represents the size in **Byte**.

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/AesGcm.cs#L11-L13

But the used type KeySizes represent valid key sizes in **Bit**.

```xml
<summary>Specifies the maximum key size in bits.</summary>
<value>The maximum key size in bits.</value>
```

see https://github.com/dotnet/dotnet-api-docs/blob/01e31683fa1feea031c94a1243b01d8ee0255a6d/xml/System.Security.Cryptography/KeySizes.xml#L135

In the namespace System.Security.Cryptography properties like "*Size*" vary between amount of bit and bytes. In this case the documentation is not consistent with the name of the property, `ByteSizes` to `Specifies the maximum key size in bits`.

I hope this description meets your quality standards for new issues.

**Comment by vcsjones** [comment]
I see. The properties of `KeySizes` are documented as returned values in bits while `AesGcm` and `AesCcm` use it to represent octets.

The properties on `AesGcm` and `AesCcm` have "Byte" in their name, perhaps to try and be super clear they really are bytes.

If anything were to be changed, I think the only think that can realistically be done is relax the documentation of `KeySizes` properties to not specify bits / bytes and add documentation in the members the use `KeySizes`.

/cc @bartonjs @krwq

**Comment by krwq** [comment]
Yes agreed, since we already shipped like that I guess the only reasonable option is to update the docs and consider adding second API which returns values in Bits :roll_eyes:
