### ISSUE TITLE
The test is failing on 2 platforms with this change

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#1913]
Please read PR #1853 and issue #1740 first, thanks.

It seems like the test is failing on 2 platforms: Windows_NT netfx x86 Release, and Windows_NT x64.
I imagine the reasoning behind the netfx failure is because it must still have the old code, but can anyone tell me what the other one is, its error messages don't make sense to me.
Also, what should I do to fix the netfx platform?

_Originally posted by @hamarb123 in https://github.com/dotnet/runtime/pull/1853#issuecomment-575776850_

https://github.com/dotnet/runtime/pull/1853/checks?check_run_id=395012296

**Comment by Gnbrkm41** [comment]
The EventPipe failures appear to be the same as https://github.com/dotnet/runtime/issues/1892.

Unless the fix can be made in .NET Framework as well, I believe that you should conditionally compile with `#if NETFRAMEWORK` to use different test data for .NET Framework.

**Comment by hamarb123** [comment]
@Gnbrkm41, do you know where the .NET Framework equivalent of [this](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.cs#L127) is? Is it [this](https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/System/compmod/microsoft/csharp/csharpcodeprovider.cs#L450), should I PR there too?

**Comment by Gnbrkm41** [comment]
.NET Framework sources are read-only, so it would be the folks at MS that would make the fix.

**Comment by hamarb123** [comment]
@Gnbrkm41, so I should just make it conditional and then they can change it later for netfx if they want?

**Comment by Gnbrkm41** [comment]
That's my understanding of it, yes.
