### ISSUE TITLE
Assertion failure: System.Reflection.Emit.Tests.ModuleBuilderDefineEnum.DefineEnum_ValueType(name: "a\0b\0c", visibility: NotPublic, underlyingType: typeof(byte))

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/runtime#19171]
See dotnet/coreclr#7669

Corelib is asserting.  The proper fix is probably in there, but until that is resolved, we should disable this test.

**Comment by GrabYourPitchforks** [comment]
This issue no longer appears to exist. The test was disabled in the _release/1.1_ branch (see https://github.com/dotnet/corefx/pull/13239), but no similar change was ever made in corefx's _master_ branch. @steveharter and I looked through the code base but we don't see any remaining test suppressions for this issue. Closing.
