### ISSUE TITLE
Idea: Use pooling for List backing arrays

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/runtime#1917]
When a List grows larger than it's backing array, it resizes, by default to an array double the size of the previous one.

It would be possible for the List to put it's old array in an ArrayPool when it does so, and check to see if the pool contains any arrays of the right size. List would not have to disposable/finalizable - the final backing array will simply be GCed instead of returned to the pool.

This should hopefully reduce GC pressure in a large percentage of real world workloads.

Because the vast majority of the backing arrays will be powers of 2, if we limit the pooling to such backing arrays is possible to optimize the pool to provide an array of exactly the right size very efficiently in a lock free manner.

For example:

```csharp
using System.Threading;

#nullable enable

public static class ListPool<T>
{
     private static int _maxLogSize = 100;
     public static T[]?[] _arrays = new T[_maxLogSize][];

     public static T[]? TryGetArray(int logSize)
     {
         return logSize > _maxLogSize ? null : Interlocked.Exchange(ref _arrays[_maxLogSize], null);
     }

     public static void ReturnArray(int logSize, T[] array)
     {
         if(logSize < _maxLogSize)
              _arrays[logSize] = array;
     }
}
```

Do you think this is worth investigating further?

**Comment by scalablecory** [comment]
> Do you think this is worth investigating further?

This would be a very significant change. Benchmarks demonstrating a benefit will definitely be helpful.

**Comment by stephentoub** [comment]
> the final backing array will simply be GCed instead of returned to the pool.

This is problematic. When things are working well, the arrays in the pool will have been around for awhile and be in gen2. Lists are frequently constructed and dropped. Such a change would likely do more harm than good in real code.

**Comment by DaZombieKiller** [comment]
You can use this if you want pooled collections: https://github.com/jtmueller/Collections.Pooled
Although of course, you don't get it for free since it's a custom type and not a change to `List<T>`.

**Comment by YairHalberstadt** [comment]
> This is problematic. When things are working well, the arrays in the pool will have been around for awhile and be in gen2. Lists are frequently constructed and dropped. Such a change would likely do more harm than good in real code.

That makes sense. This idea seemed obvious enough that I figured there must be some reason why this wasn't already done :-).

Thanks for your feedback - I'll close this now.
