### ISSUE TITLE
Assembly version of `Microsoft.CSharp` and `System.Runtime.CompilerServices.Unsafe` in 5.0 is older than the ones in 3.1?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/runtime#1918]
Tested with nightly builds of netcoreapp5.0, this will make app use out of box assembly instead of inbox ones when they are reference from other place.

Seems they are the only two assembly which have older version:

Microsoft.CSharp: 4.0.4 in 5.0, and 4.0.5 in 3.1 and nuget(4.7.0)
System.Runtime.CompilerServices.Unsafe: 4.0.5 in 5.0, and 4.0.6 in 3.1 and nuget(4.7.0)

**Comment by jkotas** [comment]
cc @ericstj @Pilchie

**Comment by ericstj** [comment]
@Anipik can you review these versioning dependencies?

It looks like you included these in 3.1 changes: https://github.com/dotnet/corefx/commit/eaa464046559e4e1d616e1e3274b60d91432ad3a

But they were missing from 5.0 changes:
https://github.com/dotnet/corefx/pull/41723

**Comment by jkoritzinsky** [comment]
This is blocking #2115 which in turn is blocking dotnet/sdk#3884.

**Comment by jkotas** [comment]
The fix was reverted.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/runtime/pull/2354

**Comment by yyjdelete** [comment]
@Anipik 
Seems the buildin version of System.Runtime.CompilerServices.Unsafe in net5.0(preview) now has two AssemblyRef at the same time: System.Runtime 4.0.0.0 and 5.0.0.0. But it works well and seems nothing is affacted . So is this by design or another issue?

**Comment by jkotas** [comment]
@yyjdelete Thanks for letting us know. I have submitted a fix in https://github.com/dotnet/runtime/pull/34870

**Comment by ericstj** [comment]
That fix was incomplete.  We need to update all versions of the assembly.
