### ISSUE TITLE
Optimize int parsing

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#19208]
Int64.Parse was too slow for Kestrel. They wrote their own: 

https://github.com/aspnet/KestrelHttpServer/commit/fff0adeaaf55b23f2173be25c59202a322f8eda6

Their code only handles the simple case nevertheless we should examine whether we can optimize the general case, or consider a new API like Int64.ParseFast that they can call instead.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Number.cs#L709

/cc @davidfowl

**Comment by joperezr** [comment]
From the discussion above, this seems to be resolved as a no-op for us for now so I'll go ahead and close this issue. @danmosemsft  feel free to reopen if that is not the case.
