### ISSUE TITLE
Proposal: operator `/` overload for path combination

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#1928]
### Background
Current if we need to combine two strings into one path, we need to use `Path.Combine(...)`, however, what's worse is that most developers use `path1 + "\\" + path2` to combine paths which may lead to unnecessary memory allocation and exceptions (if they try to use `\` on *nix platforms).

### Proposal
My proposal is to add an operator `/` overload for string:
```csharp
public static string operator /(string x, string y) => Path.Combine(x, y);
```
Then we can use `/` to combine paths conveniently.

### Usage
```csharp
var filename = "a.txt";
var path = Path.GetTempPath() / filename; // %temp%\a.txt on Windows, or /tmp/a.txt on Linux

var longPath = path1 / path2 / path3 / path4 / path5;
```

### What's more
The operator `/` overload can also be added for any other path-like types, such as `Uri`, `Path` and etc.

**Comment by Gnbrkm41** [comment]
While the code might look pretty with it, it feels weird to have this very domain-specific operation of path combining, in a type that's literally used for everything (which frankly isn't paths most of the time).

**Comment by stephentoub** [comment]
Interesting idea, thanks, but this falls under the heading off being "cute" with operator overloads, which we avoid doing. The '/' operator is about division, and using it for path combination would be confusing.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads

"X DO NOT be cute when defining operator overloads. Operator overloading is useful in cases in which it is immediately obvious what the result of the operation will be. For example, it makes sense to be able to subtract one DateTime from another DateTime and get a TimeSpan. However, it is not appropriate to use the logical union operator to union two database queries, or to use the shift operator to write to a stream."

**Comment by DaZombieKiller** [comment]
All of that said, you could implement this yourself rather easily when/if shapes & 'extension everything' get implemented.

**Comment by danmosemsft** [comment]
Closing for reasons above. Thanks for the idea though.
