### ISSUE TITLE
Instructions for Native Build of x86_64 - Not available

### ISSUE THREAD

**Issue by krishvoor** [dotnet/runtime#1930]
Whilst re-compiling _dotnet/runtime_ post consolidation of repos I cannot find instructions to do so. However figured out via reading https://github.com/dotnet/runtime/blob/master/build.sh 
_./build.sh /p:subsetcategory=CoreClr /p:os=Unix /p:arch=arm64 /p:configuration=Debug /p:v=n -b_

I expect this to go into README.md - I can help contribute if there's one.
Can anyone help point ?

**Comment by marek-safar** [comment]
The documentation for building coreclr is at https://github.com/dotnet/runtime/tree/master/docs/workflow/building/coreclr

**Comment by harsha544** [comment]
Glad to see documentation is updated.
@marek-safar can you provide your insights into https://github.com/dotnet/runtime/issues/1862 as well ?

**Comment by jashook** [comment]
Our documentation has changed since this issue was opened. Closing it, if the issue still exists please open a new issue and tag me.
