### ISSUE TITLE
Mono release build produces Debug System.Private.CoreLib

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#1932]
Using `./mono.sh -c Release` still builds a Debug corelib:

```
System.Private.CoreLib -> /...path.../artifacts/bin/mono/OSX.x64.Debug/IL/System.Private.CoreLib.dll
```

**Comment by Gnbrkm41** [comment]
Noticed `src/mono/netcore/System.Private.CoreLib` in the source folder, perhaps it's that? (not sure why there's a duplicate though, [perhaps it's something that could be removed and combined with `src\libraries\System.Private.CoreLib` in the future?](https://github.com/dotnet/corefx/blob/release/3.1/src/Common/src/CoreLib/README.md))
