### ISSUE TITLE
Mono Windows tests cause asserts: condition var->opcode == OP_REGOFFSET not met

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#1933]
A lot of the tests cause an assert in Mono on Windows:

```
  * Assertion at C:\Users\Alexander\Desktop\Dev\runtime\src\mono\mono\mini\method-to-ir.c:12522, condition `var->opcode == OP_REGOFFSET' not met
```

e.g. src\libraries\System.Collections.Concurrent\tests

/cc @lateralusX

**Comment by lewurm** [comment]
x86 or amd64?

**Comment by akoeplinger** [comment]
amd64

**Comment by akoeplinger** [comment]
A temp fix to disable SIMD went in with https://github.com/mono/mono/pull/19172, reassigning to Johan for a proper fix.

**Comment by lateralusX** [comment]
Looks like https://github.com/dotnet/runtime/pull/46812 will address this issue, re-enabling SIMD on Windows x64 netcore.

**Comment by lateralusX** [comment]
#46812 merged, closing this issue.
