### ISSUE TITLE
ExpandoObject key and value collections are too agressive with version checking.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/runtime#19357]
Consider:
```C#
IDictionary<string, object> dict = new Dictionary<string, object>();
var keys = dict.Keys;
dict["x"] = 1;
Console.WriteLine(keys.Contains("x")); // True
string[] array = new string[1];
keys.CopyTo(array, 0);                         // array now {"x"}
Console.WriteLine(keys.Count);           // 1
```
However if `dict` is set to `= new ExpandoObject();` then the three commented lines error. The collection versioning used to throw on continuing an enumeration after modification is blocking these calls too.

The same is also true of the `Values` collection.

**Comment by cston** [comment]
The current behavior matches .NET Framework, throwing `System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'` for the following:
```C#
IDictionary<string, object> dict = new ExpandoObject();
var keys = dict.Keys;
dict["x"] = 1;
Console.WriteLine(keys.Contains("x")); // InvalidOperationException
```
The existing behavior seems appropriate. Given that the behavior matches .NET Framework, we should leave the behavior unchanged.
