### ISSUE TITLE
Proposal: Add new GetValue method to System.Reflection

### ISSUE THREAD

**Issue by Esidar** [dotnet/runtime#19484]
This new method would accept an "object" to which a Value could be copied instead of being unnecessarily boxed. Example of use would look like this:

```
static object boxedFloat = null;
....
boxedFloat = fieldInfo.GetValue( myObject, boxedFloat );

```
Boxing of the value would occur only once. This would eliminate unnecessarily memory allocations in situations when GetValue is called many times. When method is used on a class types, copying would not occur and stored object would be returned instead.

One of the uses of GetValue method is User Interface based on MVVM (Model View Viewmodel) where values used to control an UI are pulled directly from the data. In realtime applications (like games) this boxing makes hundreds if not thousands of unnecessary memory allocations every second.

Another use of GetValue is serialization, and having ability to serialize hundreds of values without the need of boxing/unboxing, would greatly improve memory usage and performace.

There was also an idea https://github.com/dotnet/coreclr/issues/8277 that this new GetValue method would take a form of generic method, but I think this would limit the use as one of the advantages of working with System.Object is this abstraction that makes some parts of the code simpler.

So, ideally this new method should remove the unnecessary boxing while keeping convenience of System.Object. Additionally please bear in mind this should work with both FieldInfo and PropertyInfo, as well as give option to get values from nested Value as in following example:
```
struct Vector3
{
   float x,y,z;
}
struct Transform
{
    Vector3 position { get; set }
}

transform = positionProperty.GetValue( transformObject, transform );
boxedX = xField.GetValue( transform, boxedX );
DisplayValue( boxedX );

```
(note intermixing fields with property)

**Comment by GrabYourPitchforks** [comment]
Faster `FieldInfo` accessors are being tracked by https://github.com/dotnet/runtime/issues/23716.

**Comment by Ziflin** [comment]
@GrabYourPitchforks Where exactly did this proposal end up? I'm still looking for a non-boxing solution similar to this one, but didn't see where #23716 was either.

**Comment by steveharter** [comment]
Assuming https://github.com/dotnet/runtime/issues/45152 supersedes this.
