### ISSUE TITLE
LINQ: Consider adding overloads that capture variables for operators that currently don't

### ISSUE THREAD

**Issue by divega** [dotnet/runtime#19528]
Many LINQ operators on `Enumerable` and `Queryable` take arguments of some `Func<>` type (or `Expression<Func<>>` in the case of `Queryable`) which allow them to capture variables. This results in the following behavior:

``` C#
var letter = "";
var q = from db.Beattles.Where(p => p.Name.StartsWith(letter)); // variable letter gets captured
letter = "P";
var beattle1 = q.First(); // Returns Paul

letter = "J";
var beattle2 = q.First(); // Returns John
```

A few operators like `Skip`, `Take`, `ElementAt`, `DefaultIfEmpty`, `Aggregate` and `Contains` (#13842 proposes a couple of additions) however accept arguments of simple types. Unless these operators appear nested inside other expressions, variables won't be captured but values. This pattern results in the following behavior:

``` C#
var position = 1;
var q = from db.Orders.Skip(position - 1); // a value of 0 gets captured

position = 10;
var tenth = q.First(); // returns the first Order
position = 20;
var twentieth = q.First(); // still returns the first Order
```

Each of these behaviors can be seen as correct, but IMO the fact that they are different can be subtle and confusing unless you know about the closures. 

A possible way to address this is to add overloads that capture, e.g. for `Enumerable.Skip(int)` the signature of the new overload would be:

``` C#
public static IEnumerable<TSource> Skip<TSource>(
    this IEnumerable<TSource> source, 
    Func<int> countAccessor)
```

Usage would be as follows:

``` C#
var position = 1;
var q = from db.Orders.Skip(() => position - 1); 

position = 10;
var tenth = q.First(); 
position = 20;
var twentieth = q.First(); 
```

Another side effect manifests in specific translating LINQ providers such as the one contained in EF6 in which whether a value or a variable is captured influences whether a literal or a parameter is generated in the resulting SQL query. 

This simple rule enables some control over the SQL that gests generated but in the past it was the reason that repeated execution of queries that contained paging (i.e. `Skip` and `Take`) operations would pollute the database query cache (see http://stackoverflow.com/questions/9201403/force-entity-framework-to-use-sql-parameterization-for-better-sql-proc-cache-reu for more details). For this reason EF6 already defines overloads of `Skip()` and `Take()` that accept `Expression<Func<int>>` arguments.

**Comment by eiriktsarpalis** [comment]
Using closures that capture mutable state is considered bad practice, and as such exposing an overload dedicated to facilitating this for `Skip` seems odd to me. I don't think we could accept this, so I'm going to close this issue. Feel free to continue the conversation or reopen the issue.

**Comment by divega** [comment]
@eiriktsarpalis, I think it is fine to close the issue if there are no plans to ever do it. However, I need to add that the argument you made seems a bit strange. These query operators that don't take lambdas are the odd ones. The majority of the methods on `Queryable` and `Enumerable` do take lambdas.
