### ISSUE TITLE
Most of the markdown documentation could use improvement.

### ISSUE THREAD

**Issue by DouglasAllen** [dotnet/runtime#19542]
I use the vs-code editor a lot these days and I would suggest that if you are writing markdown documents
a lot that you take a look at the linters for markdown then we could all enjoy less green squiggly underlines. Also you don't need to let the text roll on in one line. Markdown will wrap it as needed.
There is help here on github for this markdown linter.
see:  https://github.com/DavidAnson/markdownlint/blob/v0.3.1/doc/Rules.md

**Comment by joperezr** [comment]
We haven't had any more reports about markdown problems with VS Code and we recently changed all documentation when migrating to the runtime repo, So I'll go ahead and close this one.
