### ISSUE TITLE
Get value of ref struct property via Reflection

### ISSUE THREAD

**Issue by vitaaaly** [dotnet/runtime#1955]
In my app (.Net Core 3.1) I have ref struct like this:

```csharp
    ref struct SomeRefStruct
    {
        public int Property1 { get; set; }

        public string Property2 { get; set; }
    }
```

This ref struct used in class:
```csharp
    class SomeClass
    {
        public SomeRefStruct Property1 => new SomeRefStruct();
    }
```

I try to get value of Property1 via Reflection:

```csharp
    var some = new SomeClass();
    var properties = some.GetType().GetProperties();

    foreach (var propertyInfo in properties)
    {
        var value = propertyInfo.GetValue(some);
    }
```

When called method GetValue throw "NotSupportedException: 'Specified method is not supported.'".
StackTrace:
```
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
```

Are you planning to add this functionality in future releases?

Example:
[ReflectionTestApp.zip](https://github.com/dotnet/runtime/files/4089841/ReflectionTestApp.zip)

**Comment by GrabYourPitchforks** [comment]
The reason this cannot be done today is that `PropertyInfo.GetValue` returns `object`, and ref structs cannot be boxed. The tracking issue for this is https://github.com/dotnet/coreclr/issues/17296, and there are also links from that to other related issues.

I'm closing this for now as a dupe. If you feel that this has been closed incorrectly please feel free to reopen.

**Comment by sakno** [comment]
It's because `GetValue` method from Reflection API returns `object` data type. ref struct cannot be boxed. Not sure that it is error at all.
However, you can use workaround like this:
```csharp
internal static class ReflectionHelpers
{
  delegate SomeRefStruct PropertyGetter(SomeClass obj);
  internal static readonly PropertyGetter Property1Getter = typeof(SomeClass).GetProperty(nameof(SomeClass.Property1)).GetMethod.CreateDelegate(typeof(PropertyGetter)) as PropertyGetter;
}
``` 
Now you have instance of open delegate that can be used to obtain property value of the arbitrary instance of `SomeClass`.
