### ISSUE TITLE
publish -f netcoreapp1.1 -r fedora.32-x64 doesn't produce executable file

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#1956]
Hi! Is it possible? If not, would you mind pointing this restriction in the code?

```
[root@889c1e907a44 myApp]# ../dotnet publish -r fedora.32-x64 -f netcoreapp1.1 -o tmp
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 53.16 ms for /root/dotnet-sdk/myApp/myApp.csproj.
  myApp -> /root/dotnet-sdk/myApp/bin/Debug/netcoreapp1.1/fedora.32-x64/myApp.dll
  myApp -> /root/dotnet-sdk/myApp/tmp/
[root@889c1e907a44 myApp]# ls ./tmp/myApp*
./tmp/myApp.deps.json  ./tmp/myApp.dll  ./tmp/myApp.pdb  ./tmp/myApp.runtimeconfig.json
```

**Comment by vscodewinodws** [comment]
you have used wrong runtime identifier , use linux-x64

correct syntax would be dotnet publish yourprojectname -r linux-x64

i tried in one of the my .net core 3.1 project and I was able to generate executables for Linux

**Comment by k15tfu** [comment]
@vscodewinodws linux-x64 doesn't work either. I think the reason in the target framework netcoreapp1.1.

**Comment by jeffschwMSFT** [comment]
@leecow

**Comment by NikolaMilosavljevic** [comment]
.NET 1.1 is no longer supported. Please try with a supported version: https://dotnet.microsoft.com/platform/support/policy/dotnet-core
