### ISSUE TITLE
Feedback on ClaimsPrincipal handling of arrays and complex types

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#19578]
As originally reported by @nathan-alden in https://github.com/aspnet/mvc/issues/5532

Were I to use ClaimsPrincipal, I'd be forced to rely on the broken Claim class implementation that doesn't handle arrays properly and can't handle more complex types of claim values like JSON objects.

**Comment by bartonjs** [comment]
Issue cleanup:

This seems to have been marked as `api-needs-work` before we had our current meaning of that label.  The issue doesn't seem to have a specific complaint, and it's approaching 6 years old.  It doesn't seem very actionable, so closing it.

If there's still a problem here and you think that API can help, please feel encouraged to open a new issue (or we can reactivate this one)
