### ISSUE TITLE
PipeReader CopyToAsync to a PipeWriter doesn't notice when the destination Pipe is closed.

### ISSUE THREAD

**Issue by chriswelles** [dotnet/runtime#1958]
With .NET Core 3.1, I'm using a PipeReader.CopyToAsync to copy to a destination pipe.  When I close the pipe, the CopyToAsync doesn't notice until the buffer is full.

`await Request.BodyReader.CopyToAsync(receivePipe.Pipe.Writer);`

I would expect an exception or something.  As it is, the PipeReader.Complete seems kind of useless.

Looking in PipeReader.cs, it appears that it pays attention and throws an exception for a cancellation, but doesn't do anything about IsComplete.

            return CopyToAsyncCore(destination, async (destination, memory, cancellationToken) =>
            {
                FlushResult result = await destination.WriteAsync(memory, cancellationToken).ConfigureAwait(false);

                if (result.IsCanceled)
                {
                    ThrowHelper.ThrowOperationCanceledException_FlushCanceled();
                }
            },
            cancellationToken);

I've managed to work around this by passing along a cancellation token along with the pipe, but I feel kind of ridiculous writing:

            cancellationSource.Cancel();
            receivePipe.Reader.Complete();

This stuff is fantastic though.  Even with the occasional hiccup, it's such a huge leap forward.

**Comment by davidfowl** [comment]
Agreed. This should be fixed.

**Comment by manandre** [comment]
Fixing this issue requires first to solve another one identified during implementation. See #51272 for more details
