### ISSUE TITLE
Path.Combine doesnt work correctly on linux

### ISSUE THREAD

**Issue by ofarukcebir** [dotnet/runtime#1960]
I am using .net 3.1 on linux. 
I expect to get path of /home/pi/Desktop/logfile.txt by combining paths the cross platform way

Here is my code

`
            string[] paths = { @"home", "pi", "Desktop","logfile.txt" };
            string fullPath = Path.Combine(paths);

            using (StreamWriter writer = System.IO.File.AppendText(fullPath))
            {
              writer.WriteLine(edit1);
            }
`

But this is the path string I get.

DirectoryNotFoundException: Could not find a part of the path '/home/pi/Desktop/WebApplication2/WebApplication2/bin/Release/netcoreapp3.1/linux-arm/home/pi/Desktop/logfile.txt'.

My code works ok on windows, Is this a bug? Or am I doing something wrong?

**Comment by stephentoub** [comment]
Your path isn't rooted, and as such it's going to be relative to the current directory. Add a `/` at the beginning of `home`.

**Comment by ofarukcebir** [comment]
Yes, thats the problem, thanks for support.
