### ISSUE TITLE
Improve code coverage for Microsoft.VisualBasic.dll (8.9%)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#19615]
There are [almost zero tests](https://github.com/dotnet/corefx/blob/master/src/Microsoft.VisualBasic/tests/StringsTests.cs) so there is [essentially zero code coverage](https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/).

**Comment by cston** [comment]
Closing. If we identify specific types in Microsoft.VisualBasic.Core that require additional test coverage, we can address those cases with specific issues.
