### ISSUE TITLE
Review CA2002:DoNotLockOnObjectsWithWeakIdentity errors in System.Console

### ISSUE THREAD

**Issue by alexperovich** [dotnet/runtime#19631]
The System.Console project has many cases of locking on bad objects. Review the usages and suppress in source with justifications if the risk of deadlocks is okay.

https://github.com/dotnet/corefx/blob/master/src/System.Console/src/FxCopBaseline.cs

**Comment by carlossanlop** [comment]
Triage: Looking at the past discussion, the suppression of the messages seemed like the correct pattern. Unless there are still FxCop related issues in the dotnet/runtime repo, then we should close this.
