### ISSUE TITLE
Support plan for parsing of Binary numeric literal strings, e.g., Convert.Int32("0b1011")

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/runtime#19642]
Related to the roslyn issue https://github.com/dotnet/roslyn/issues/215, do you have a plan to support Binary literals in `Convert.ToInt32("0b1011", 2)`?

As for the current corefx specification, `Convert.ToInt32` (and other similar methods) method can convert Hexadecimal string, which starts from `0x`, to integer (or other Numeric types) if `fromBase` is 16. `int.Parse` and `int.TryParse` method can't parse Hexadecimal string. 
So do you have a plan to support converting Binary literals in `Convert.ToInt32` if `fromBase` is 2?

**Comment by tannergooding** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/83619

The referenced issue, if approved, would allow this using `int.Parse(s, NumberStyles.BinaryNumber)`. Much as is already done for `HexNumber`

This would then be supported from generic contexts via `T.Parse()` given `where T : INumberBase<T>`
