### ISSUE TITLE
Reflection should check mscorlib for types

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#19689]
In NetFX `Type.GetType()` would find types that weren't fully qualified in mscorlib. Now that we're going to ship the mscorlib facade we should probably mimic that behavior.

See the following discussion: https://github.com/dotnet/corefx/pull/14498#discussion_r92474847

@weshaggard, @ericstj

**Comment by jkotas** [comment]
This fix was meant for better compat with .NET Framework. We have not seen it to be a problem in practice and fixing this now would be breaking change between .NET Core versions. Closing.
