### ISSUE TITLE
Consider integration with third party incremental hash algorithms

### ISSUE THREAD

**Issue by Genbox** [dotnet/runtime#19709]
Incremental/stateful hashing was refactored into its own class called [IncrementalHash](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/IncrementalHash.cs) according to @bartonjs in issue dotnet/runtime#17621

I think this is a good change, however, the refactoring left out the possibility of integration with third-party stateful (incremental) hash algorithms. The IncrementalHash class is a simple wrapper for the real implementation  [HashProvider](https://github.com/dotnet/corefx/blob/master/src/Common/src/Internal/Cryptography/HashProvider.cs), but users can't implement HashProvider as it is internal, and the IncrementalHash wrapper is not extensible as well.

In good design, I'd want hash algorithms to be exchangeable in an API, which is possible with HashAlgorithm, but not with IncrementalHash or HashProvider. Arguably, most people could take in [HashAlgorithmName](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithmName.cs) and give it to IncrementalHash.Create(), but that does not support third party hash algorithm implementations.

I'd propose the API is refactored once more (while IncrementalHash is not widely used), to support integration of third party stateful/incremental hash algorithms.

**Comment by bartonjs** [comment]
This is one piece of an overall "bring your own crypto stack" / 3rd party extensibility for our crypto stack.

Right now that's not a priority for us, and we'd really need to be partnering with someone to try to make sense out of it overall... a design without a concrete usage is bound to be inadequate.
