### ISSUE TITLE
Introduce System.IString interface and implement it on System.String

### ISSUE THREAD

**Issue by pharring** [dotnet/runtime#19711]
### Proposal
Introduce an interface called ```IString``` in the System namespace. The purpose of the interface is to identify string-like objects and provide a minimal set of methods over them. The native ```System.String``` type should implement this new interface.

### Motivation
The motivation for this proposal is to allow library authors to implement efficient alternative representations of 'string-like' objects. An ```IString```, therefore, represents the essence of a string: An *immutable*, *finite* sequence of Unicode characters that supports enumeration and random access.

### Rationale
In code which does heavy text processing, strings are invariably the most frequently allocated type. Many strings are short-lived, but few are "novel". By "novel", I mean that most strings are realized by transforming existing data - they don't spring into existence out of thin air. Some common examples:
1. A substring of an existing string.
2. A concatenation of two or more existing strings or characters.
3. The result of de-serializing a stream via an encoding.

In each of these cases (and many others), since public APIs tend to be built around the ```System.String``` primitive, early realization of the transformations is unavoidable. Both callers and implementors are forced to use the primitive representation, even when it would be inefficient. e.g. Trimming off the last character of a string by creating a substring with length = Length - 1.

By using ```IString``` instead of ```string``` in both the public APIs and internal implementations, library authors have an opportunity to reduce these hard-to-avoid allocations. Indeed, if we had something like this from the beginning in Roslyn, I feel we would have used it extensively.

### Details
The proposed definition of IString is:

```C#
namespace System
{
    using System.Collections.Generic;

    interface IString : IEnumerable<char>
    {
        char this[int index] { get; }
        int Length { get; }
    }
}
```

Note that this definition is very similar to ```System.Collections.Generic.IReadOnlyList<char>``` except:
1. The length property is named ```Length``` instead of ```Count```, and
2. It's easier to type (fewer chars) and discover (lives in the System namespace)

### Examples
By way of an example for an alternative representation of a string-like thing using ```System.IString```, here is a canonical "SubString" implementation:

```C#
using System;
using System.Collections;
using System.Collections.Generic;

sealed class SubString : IString
{
    private readonly IString _original;
    private readonly int _start;
    private readonly int _length;

    public SubString(IString original, int start, int length)
    {
        // TODO: Decide whether to throw on invalid start/length or just clamp the values.
        _original = original;
        _start = start;
        _length = length;
    }

    public char this[int index]
    {
        get
        {
            if (index < 0 || index >= _length)
            {
                throw new IndexOutOfRangeException(nameof(index));
            }

            return _original[_start + index];
        }
    }

    public int Length => _length;

    public IEnumerator<char> GetEnumerator()
    {
        // TODO: If _start is zero, then use the underlying enumerator.
        for (int i = 0; i < _length; i++)
        {
            yield return _original[i + _start];
        }
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

Here is a simpler example of an ```IString``` representing a single ```char```:
```C#
using System;
using System.Collections;
using System.Collections.Generic;

sealed class CharString : IString
{
    private readonly char _ch;

    public CharString(char ch)
    {
        _ch = ch;
    }

    public char this[int index]
    {
        get
        {
            if (index != 0) throw new IndexOutOfRangeException();
            return _ch;
        }
    }

    public int Length => 1;

    public IEnumerator<char> GetEnumerator()
    {
        yield return _ch;
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```
And, finally, here's a wrapper over a char array:
```C#
using System;
using System.Collections;
using System.Collections.Generic;

sealed class CharArrayWrapper : IString
{
    private readonly char[] _array;

    public CharArrayWrapper(char[] array)
    {
        _array = array;
    }

    public char this[int index] => _array[index];

    public int Length => _array.Length;

    public IEnumerator<char> GetEnumerator() => (IEnumerator<char>)_array.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => _array.GetEnumerator();
}
```
### Comparison with ```IReadOnlyList<char>```
There is an existing proposal, dotnet/runtime#19609, to add ```IReadOnlyList<char>``` to the set of interfaces implemented by ```System.String```.

While that would be a sufficient alternative, the big downside is that it's harder to type ```System.Collections.Generic.IReadOnlyList<char>```. For code that consumes such strings, one could mitigate that with a using alias, but it doesn't help the public API surface area. Consumers probably already have a using statement for the System.Collections.Generic namespace, but it's still hard to discover, and not immediately obvious to the uninitiated, that ```IReadOnlyList<char>``` is the _'I behave like a string'_ marker. I believe it's only a coincidence that ```IReadOnlyList<char>``` has the exact shape required to be that marker. We'll Ignore, for now, the different ways of spelling 'Length'.

```IReadOnlyList<char>``` has an advantage, though, because ```char[]``` already implements it. i.e. a ```char[]``` would also be a valid 'string-like' implementation without modification. That would _not_ be the case with ```System.IString```, hence the need for the CharArrayWrapper shown above.

If we're willing to entertain _both_ proposals, then we could redefine ```System.IString``` as:

```C#
namespace System
{
    using System.Collections.Generic;

    interface IString : IReadOnlyList<char>
    {
    }
}
```
and accept the (mis-)spelling of 'Length' ;-)

### Limitations
It's hard to come up with a concatenation implementation that performs well in all cases: Do you chain to the left, to the right, or try to keep the 'tree' balanced? However, for specific cases where you're building "compound" strings by concatenation, sometimes a special-purpose object will do. e.g. It's possible to create a custom ```IString``` implementation to represent a fully-qualified type name from its parts while avoiding allocating the final string.

In some cases, it _is_ better to do eager string realization. For example, if you're going to do a lot of random access operations on an ```IString``` that is actually a complex, compound implementation (e.g. a concatenation of a bunch of substrings of a UTF8-encoded text buffer). Advanced library implementations would detect when to switch to a more efficient implementation (e.g. rebalance a tree, or decode the entire UTF8 buffer). For other cases, clients can always use the ```.ToString()``` escape hatch. Certainly, we assume that library authors will strive to make most situations no worse than using ```System.String``` directly.

### Future
If ```System.IString``` is adopted, there are plenty of places in the Framework where we could/should provide new overloads for methods that currently take ```System.String```. e.g. Serialization, formatting, encoding, path building/parsing).

Of course, none of the performance benefits will be realized if a consumer of an ```IString```-returning API immediately turns around and calls ```.ToString()``` on the result (perhaps in order to call another API which accepts only ```System.String```). Without broad library support, this proposal is likely to falter. We have to start somewhere, though, and, if we're willing to entertain a new interface on ```string```, then I humbly suggest that it has a name that is easy to discover and type.

**Comment by stephentoub** [comment]
With the advent of `ReadOnlySpan<char>`, it has become the canonical way to write operations that can process strings, substrings, arrays of chars, etc., effectively making it an exchange type similar to what's been requested here.  I don't see us creating another.  I'm going to close this.  Thanks.

**Comment by pharring** [comment]
Reading back through the thread, I'm impressed by my younger self. That fellow made a convincing case! However, I'm glad that more enlightened people ignored him and found an even better solution. Yes, `Span<T>` and `ReadOnlySpan<T>` really are superior, covering more scenarios.

**Comment by stephentoub** [comment]
Heh. Thanks, Paul :smile:
