### ISSUE TITLE
Mono rsp files should be removed and replaced by xunit arguments

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#1980]
Tracking issue to replace the mono rsp files with xunit test arguments in libraries.

cc @safern @marek-safar @akoeplinger

**Comment by ViktorHofer** [comment]
Accidentally assigned myself. Removing assignment.

**Comment by ViktorHofer** [comment]
@akoeplinger @steveisok what's the status on this? I would really want to remove the rsp file as it bloats non Mono test builds as well.

**Comment by akoeplinger** [comment]
We removed the main .rsp file with https://github.com/dotnet/runtime/pull/2087, the macOS one with https://github.com/dotnet/runtime/pull/32585 and Windows is in progress here: https://github.com/dotnet/runtime/pull/32592.

The remaining .rsp files are just a couple lines so there's no "bloat" :)

**Comment by ViktorHofer** [comment]
Thanks for the update. Is somebody working on the remaining ones: linux, interpreter and interpreter_arm64?

> The remaining .rsp files are just a couple lines so there's no "bloat" :)

I wasn't just talking about file size bloat here but also about infrastructure: https://github.com/dotnet/runtime/blob/5aff3becf9d9e9f3bc77ee6e3442b3ec0e3d1605/eng/testing/tests.targets#L79-L90. This is currently running always, as we share built libraries test assemblies between coreclr and mono.

**Comment by steveisok** [comment]
Yeah, @MaximLipnin is working on removing the rest.
