### ISSUE TITLE
The official build doesn't produce Crossgen2 pack RPM or Debian packages

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#1985]
The official build produces e.g. `dotnet-crossgen2-pack-5.0.0-alpha.1.20071.1-win-x64.msi`, but no corresponding `dotnet-crossgen2-pack-5.0.0-alpha.1.20071.1-win-x64.rpm` or `.deb` for use on Linux. These are required for the SDK to incorporate them properly--I think not having them will make it harder to integrate SDK support.

I'm taking a look, I would expect these to be created.

/cc @fadimounir @dotnet/crossgen-contrib

**Comment by dagood** [comment]
I think it's because of this line:

https://github.com/dotnet/runtime/blob/4e72737a8ec246297bce916ad747e4a2fb1265ac/src/installer/pkg/projects/netcoreapp/pkg/crossgenRIDs.props#L5

The Debian package production step runs as `ubuntu.14.04`, which isn't in the list of valid RIDs. Same for `rhel.7` and RPMs.

I think a simple fix would be to add `ubuntu.14.04` and `rhel.7` to the list of RIDs in that file. That doesn't really represent what's going on, though--we're actually packaging up `linux` bits.

I'm going to try using a target to manipulate the process instead, and have it condition based on `InstallerSourceOSPlatformConfig = linux-x64.Release` passed in during lab builds. That's the RID that actually matches up with the *content* here.

**Comment by jkotas** [comment]
> .msi

Does it mean that I need to be an admin to install crossgen2?

I though that crossgen2 is going to be a nuget package, and you will acquire it by adding a nuget package reference somewhere.

**Comment by dagood** [comment]
It's both, the `.msi` is there so that it can be chained into the SDK Windows installer. Similar for Deb/RPM, they require admin to install, but can be depended on by the SDK RPM/Debs. If the user doesn't install it through these methods, it'll be acquired from nuget.org.

We may decide not to include the crossgen2 pack in any SDK installation method, like runtime packs. Didn't actually consider that before... I don't object to doing a little work now to keep it unblocked though.

**Comment by jkotas** [comment]
I think the only packaging for crossgen2 we need to worry about is nuget. .msi/.rpm./.deb does not matter for foreseeable future or ever.

**Comment by dagood** [comment]
Ok, thanks. It makes sense to me for this to be similar to the runtime packs in that way. I'll go ahead and close and note that on https://github.com/dotnet/runtime/issues/1867.
