### ISSUE TITLE
RFC: Refine C++ define usage for cross (OS) builds

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#1987]
In order to enable cross OS DAC builds, we need to minimize changes in #define between different hosts when compiling for the same target

This issue is intended for discussion around the policies for revising #define usage in C++ runtime code.

**Draft plan**

- `FEATURE_PAL` in many cases is synonym to *_UNIX
  - For the prototype, I set `FEATURE_PAL` based on `CLR_CMAKE_TARGET_UNIX`
  - When cross compilation issues were observed, I changed the `FEATURE_PAL` to `FEATURE_HOST_PAL`
  - Another option: Replace all instances with `TARGET_UNIX`.  Then convert to `HOST_UNIX` as needed?
  - **For 3.1 backport, use `FEATURE_PAL` and `FEATURE_HOST_PAL`**
  - **For 5.0+, use `TARGET_UNIX` and `HOST_UNIX`**

- `PLATFORM_UNIX` and `PLATFORM_WINDOWS` are ambiguous
  -  For the prototype so far I have mostly ignored this issue. In one case I switched `PLATFORM_UNIX` to `FEATURE_PAL` 
  - Replace all instances with `TARGET_UNIX` or `!defined(TARGET_UNIX)`. Convert to `HOST_UNIX` as needed?
  - **For 3.1, minimize changes...**
  - **For 5.0+, use `TARGET_UNIX` and `HOST_UNIX`**

- In some cases code will not easily cross compile. When cross compilation is not currently possible:
  - ~~Add  ASSERT macro to easily catch issue in debug/checked builds~~
  - ~~Add logging to easily detect issue in release builds~~
  - **Use `DacNotImpl()`**

- Controlling type padding
  - Initial testing has not seen any need of this
  - May only occur in cross bitness builds
  - **If/when needed use the packing includes...**

- Multiple inheritance
  - The biggest type layout issue has been around multiple inheritance
  - For empty base classes, the MSVC pads the type by default, but clang does not.
  - ~~The plan is to #if remove these empty base types from the DAC~~
  - ~~Preferably from all DAC builds~~
  - ~~Possibly only cross DAC builds~~
  - **Add macro `EmptyBaseClassOptimization` as needed**
    - **`__declspec(empty_bases)` for MSVC**

- Use of OS specific data structures in types
  - This has been observed once.  CRITICAL_SECTION
  - When cross compiling this structure size is unknown
  - Ideally these structures would not be contained in runtime structures
    1. Replace with references/pointers
    2. Place in a union with appropriate padding and static_asserts
    3. #if replace with padding
  - In the prototype I chose option b.
  - **Define a new alias type in src/inc/crosscomp.h**

- Avoid usage of compiler specific defines to control type layout or code generation
  - Examples: `__APPLE__`, `WIN32`, `WINVER` …
  - Prefer: FEATURE* or CMAKE added defines
  - OK for warning suppression
  - OK in packing control headers (which are really compiler specific)
  - **Fix as needed**

- Changes in runtime layout between debug, checked and release.
  - Ideally a debug DAC could be used to test a release runtime.
  - ~~Remove type layout (or important algorithm) differences between release, checked and release~~
  - For the prototype I chose to ignore this wishlist item
  - **Defer**

/cc @noahfalk @hoyosjs @jkotas

**Comment by jkotas** [comment]
> FEATURE_PAL in many cases is synonym to *_UNIX

I would not mind renaming `FEATURE_PAL` to `*_UNIX`.

> In some cases code will not easily cross compile. When cross compilation is not currently possible:

There is a similar problem with DACization in general. We  use `DacNotImpl();` in these cases. I think we should do the same here. Ideally, we would not have these DacNotImpls specific for cross-compilation. If something does not cross-compile, it should not be in the DAC.

> CRITICAL_SECTION

There are many other similar types in src\inc\crosscomp.h that deal with the same problem between CPU architectures. The solution for this should be to define a new type (e.g. `T_CRITICAL_SECTION`) that is alias to the native or cross-targeting critical section as appropriate.

> Changes in runtime layout between debug, checked and release.

These additional members in debug exists for additional consistency checks to catch bugs early, and to make runtime devs life easier by e.g. having convenient strings describing the object. I do not think we would want to add these extra members in release. If we were to remove them, we should make sure that we understand what we are losing.

**Comment by jkotas** [comment]
cc @janvorli

**Comment by sdmaclea** [comment]
> These additional members in debug … If we were to remove them, we should make sure that we understand what we are losing.

If we moved them to the end of the structures, perhaps the DAC could simply ignore them.  Maybe they could move into a debug info member struct...

**Comment by jkotas** [comment]
> we moved them to the end of the structures, 

The key runtime structures that this affect are dynamically sized for maximum packing and have a lot of optional members at the end. Moving these to the end of the structure is not easy and it would lose some of the appeal of these debug-only members.

**Comment by hoyosjs** [comment]
> > These additional members in debug … If we were to remove them, we should make sure that we understand what we are losing.
> 
> If we moved them to the end of the structures, perhaps the DAC could simply ignore them. Maybe they could move into a debug info member struct...

Wouldn't then nesting also become an issue? Some of these are life-savers when debugging things like methoddescs and critical sections. The DAC has historically had problems with resizing of structures even with appends as things end up nesting on other structures and then you have offset mismatches that can be hard to track.

**Comment by sdmaclea** [comment]
OK....

I guess the remaining option would be to build a debug DAC for release/checked target...

Probably best to just defer this for now.

**Comment by noahfalk** [comment]
In cases where we don't currently distinguish host vs target (FEATURE_PAL, PLATFORM_UNIX) I think its fine to insert HOST or TARGET to disambiguate. In terms of which one is the default for code that is initially untested/unanalyzed I'd guess TARGET is more likely to be the right choice but I'm happy either way. Your experience doing the review for code so far is probably the best data we have on it.

I'm not sure how shiproom folks will react to a backporting a change into servicing that has a large amount of non-functional define renaming. On the one hand its very mechanical and seems low risk, on the other its been historical practice to minimize changes to only the required differences. I suppose worst case if shiproom didn't like it you could always pick whichever TARGET or HOST was more numerous and rename that back to the existing name.

+1 for everything Jan and Juan said above : )

**Comment by janvorli** [comment]
> * `FEATURE_PAL` in many cases is synonym to *_UNIX

It is in fact always a synonym to that now, so I'm fine doing such a rename. 



> * Avoid usage of compiler specific defines to control type layout or code generation

As for the `__APPLE__`, it is used at a single place in the VM to select exception message resource id for .so not found / .dylib not found. There are few usages in the debug/shimremotedatatarget.cpp that could be completely removed, making one struct field unconditional.
The rest of the usage is in the PAL / debug-pal, which is fine and should not need any treatment.

> * For empty base classes, the MSVC pads the type, but clang does not.

There is a `__declspec(empty_bases)` in VS2015 update 2 and later that makes MSVC to behave the same was as clang w.r.t. empty base classes (it is applied per class). See https://devblogs.microsoft.com/cppblog/optimizing-the-layout-of-empty-base-classes-in-vs2015-update-2-3/ for more details.  So we could use that.

**Comment by sdmaclea** [comment]
Thanks for all the feedback.  I have updated the original post to reflect current consensus.
