### ISSUE TITLE
Replace modulo with fastmodulo in HashSet and Hashtable

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#1989]
The performance optimization by @benaadams in `Dictionary<K,V>` in https://github.com/dotnet/coreclr/pull/27299 should be applied to 

- [x] `Hashset<T>` 
- [ ] `Hashtable`

**Comment by GrabYourPitchforks** [comment]
`HashSet<T>` should also get the non-randomized string hash code optimization that `Dictionary<TKey, TValue>` enjoys. That optimization should pay healthy dividends.

**Comment by eanova** [comment]
I took a peek at this last night.  Few test errors but I think I can resolve those and push a PR by tomorrow for HashSet<T>.

**Comment by danmosemsft** [comment]
Sounds good. It would be good to share perf numbers before/after in your PR: https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md

**Comment by danmosemsft** [comment]
That doc just got updated for 50 and this new repo, so if you see any glitch in it, let us know!

**Comment by eanova** [comment]
I'll post back here if I get stuck on the performance tests.

**Comment by danmosemsft** [comment]
OK! @adamsitnik owns that excellent doc.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/pull/55467 was unsuccessful attempt to update Hashtable to use fastmod.
