### ISSUE TITLE
Create x-plat System.Security.Principal.Identity

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#19909]
`WindowsIdentity` is tied to Windows concept of 1 identity per user. Linux can have multiple identities (in various locations on different distros) per user.
Create common `Identity` which would abstract both approaches and provide Identity API which can be used on any OS.

Details here https://github.com/dotnet/corefx/issues/7325#issuecomment-270967064

**Comment by stephentoub** [comment]
This has been open for years with little demonstrated interest or need. Closing.
