### ISSUE TITLE
GCStress=3 timeout with Loader\binding\tracing\BinderTracingTest\BinderTracingTest.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#1990]
I've seen this test time out on both Windows x86 and Windows x64 in the "runtime-coreclr gcstress0x3-gcstress0xc" AzDO pipeline:

https://dev.azure.com/dnceng/public/_build/results?buildId=491282&view=ms.vss-test-web.build-test-results-tab&runId=15658870&resultId=110324&paneView=debug
https://dev.azure.com/dnceng/public/_build/results?buildId=481714&view=ms.vss-test-web.build-test-results-tab&runId=15290148&resultId=110320&paneView=debug

It appears to be running for an hour before timeout.

Should it be marked GCStressIncompatible? Or the timeout increased?

**Comment by BruceForstall** [comment]
Run with:
```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0x3
```

**Comment by elinor-fung** [comment]
Looks like it is occasionally needing longer than the timeout to run. Successful runs were regularly 50-55 minutes. There is nothing inherently incompatible with GC stress for these. This is actually a bunch of test cases wrapped into one project, so we could just split them up.

**Comment by BruceForstall** [comment]
55 minutes is a huge amount of time for a single test (even under GCStress=3), given that there are ~10,000 pri-1 tests. Is there a reason why they are so slow in this mode? How long do they take in a normal (non-stress) run?

It's reasonable to mark these not to run under GCStress if doing so improves overall test run performance, and losing this single test coverage isn't critical.

**Comment by elinor-fung** [comment]
It is 2-3 minutes in normal (checked) runs. The single test goes through >50 test cases; I think the main contributor is that some of those spin off and wait for child processes that run some test scenarios. Avoiding running those ones under GCStress sounds reasonable. I tried that and split the test cases into basic vs. more complex scenarios which brings us to ~5 minutes total.
