### ISSUE TITLE
Add variations of SocketTestServer to increase test coverage in System.Net.Sockets.Tests

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#19952]
Currently, we have this "SocketTestServer" abstract class that allows us to run the same tests in two variations: (1) APM-style (IAsyncResult) and (2) SocketAsyncEventArgs.

We should add new implementations of this class that cover:
(1) Synchronous APIs
(2) Non-blocking operations (i.e. socket.Blocking = false)
(3) Task-based APIs

**Comment by antonfirsov** [comment]
We don't have socket stress tests today, when we will seriously consider to re-add them we should open a separate issue; without that there is little value, I recommend to close this.

**Comment by wfurt** [comment]
triage: we have functional tests and indirect testing through HttpClient. That seems sufficient at the moment.
