### ISSUE TITLE
SortedSetEqualityComparer seems to ignore the comparer from CreateSetComparer

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#19994]
Discovered during dotnet/corefx#15376

[`SortedSetEqualityComparer`](https://github.com/dotnet/corefx/blob/adb0f13d7aafdbee95ae13f970c8ad25f77558c5/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L2631) has a `_comparer` field that is always set to the `Comparer<T>.Default`. This is because although it has a constructor that allows a different comparer to be passed in, that constructor is never actually called. And during `Equals`, it uses that default comparer for comparing two sorted sets and leaves the equality comparer which was handed to it from `CreateSetComparer` completely out of the equation.

The fix would be to remove the `_comparer` field and use the equality comparer for everything.

**Comment by eiriktsarpalis** [comment]
Per feedback in https://github.com/dotnet/runtime/issues/18931#issuecomment-954074409 and https://github.com/dotnet/runtime/issues/19644#issuecomment-954096188 I believe this is a fundamental flaw with defining general-purpose equality comparers for HashSet's encapsulating arbitrary `IEqualityComparer<T>` values.

I would recommend not attempting to fix this, potentially obsoleting the method. A potential alternative approach is described in https://github.com/dotnet/runtime/issues/19644#issuecomment-954977243
