### ISSUE TITLE
Developers can use Compression in WebSocket

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#20004]
[AB#1118550](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1118550)
https://tools.ietf.org/html/rfc7692
https://github.com/aspnet/WebSockets/issues/19

Implementation notes:
The System.Net.WebSockets.WebSocket.SendAsync API is poorly suited to compression/extension. Compression is a per-message flag set on the first frame using the RSV1 bit. SendAsync sends frames and only takes the buffer, message type, an EndOfMessage bool, and a cancellationToken. There's no simple way to indicate if the data is or should be compressed / transformed. Possible solutions:
- Enable compression for all messages, don't provide a per message option
- Add a new overload of SendAsync with a compression / RSV1 flag. (Requires changing the core WebSocket abstraction)
- Add a property to WebSocket bool CompressOutput that can be toggled between messages (Requires changing the core WebSocket abstraction)
- Overload WebSocketMessageType with CompressedBinary and CompressedText. As an enum we may be able to temporarily pass data through here by casting non-standard values. The enum values already do not map directly to the WebSocket frame type values.

ReceiveAsync is easier, it could: 
- Decompress the content internally
- Add a flag to WebSocketReceiveResult indicating if the content was compressed.
- Use the same WebSocketMessageType overloads from above indicating if the content is compressed (but only if it does not decompress it internally, don't want to confuse consumers).

The compression extension could not be correctly implemented as wrapper over the current WebSocket API due to the framing requirement. Compression either needs to be built in or the API needs to expose additional frame fields (e.g. RSV1).

## Dev work:

- [x] Add compression support in WebSocket - #31088
- [x] Add WebSockets compressions support - https://github.com/dotnet/aspnetcore/issues/2715

**Comment by BrennanConroy** [comment]
Close via https://github.com/dotnet/runtime/pull/49304?

**Comment by davidfowl** [comment]
We have to enable it.

**Comment by karelz** [comment]
@davidfowl what has to be enabled where? Is there a tracking work item?

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/issues/2715

**Comment by BrennanConroy** [comment]
Is there a difference between this issue and the one in aspnetcore? Can we close this one if there isn't

**Comment by karelz** [comment]
@BrennanConroy This is User Story plugged into overall .NET 6 planning, the ASP.NET Core is a child.

**Comment by karelz** [comment]
The remaining work was addressed in https://github.com/dotnet/aspnetcore/issues/2715 by PR https://github.com/dotnet/aspnetcore/pull/32600
