### ISSUE TITLE
Enum Improvements

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/runtime#20008]
Enums are essential commonly used types but have several areas in need of improvement. For each non-generic `Enum` method there should be an equivalent generic version.

## Rationale and Usage
1. Nearly all of `Enum`'s static methods are non-generic leading to the following issues.
   * Requires boxing for methods with enum input parameters losing type-safety, eg. `IsDefined` and `GetName`.
   * Requires casting/unboxing for methods with an enum return value, eg. `ToObject` and `GetValues`.
   * Requires the enum type to be explicitly specified as an argument.
   * Requires invocation using static method syntax.

With this proposal implemented what used to be this to validate a standard enum value

```c#
MyEnum value = ???;
bool isValid = Enum.IsDefined(typeof(MyEnum), value);
```

now becomes this

```c#
MyEnum value = ???;
bool isValid = value.IsDefined();
```

With this implemented it will address dotnet/runtime#18063.

## Proposed API
```c#
namespace System {
    public abstract class Enum : ValueType, IComparable, IConvertible, IFormattable {
        public static TEnum Parse<TEnum>(ReadOnlySpan<char> value) where TEnum : struct, Enum;
        public static TEnum Parse<TEnum>(ReadOnlySpan<char> value, bool ignoreCase) where TEnum : struct, Enum;
        public static object Parse(Type enumType, ReadOnlySpan<char> value);
        public static object Parse(Type enumType, ReadOnlySpan<char> value, bool ignoreCase);
        public static bool TryParse<TEnum>(ReadOnlySpan<char> value, out TEnum result) where TEnum : struct, Enum;
        public static bool TryParse<TEnum>(ReadOnlySpan<char> value, bool ignoreCase, out TEnum result) where TEnum : struct, Enum;
        public static bool TryParse(Type enumType, ReadOnlySpan<char> value, out object result);
        public static bool TryParse(Type enumType, ReadOnlySpan<char> value, bool ignoreCase, out object result);

        // Generic versions of existing methods
        public static string GetName<TEnum>(this TEnum value) where TEnum : struct, Enum;
        public static IReadOnlyList<string> GetNames<TEnum>() where TEnum : struct, Enum;
        public static IReadOnlyList<TEnum> GetValues<TEnum>() where TEnum : struct, Enum;
        public static bool IsDefined<TEnum>(this TEnum value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(object value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(sbyte value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(byte value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(short value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(ushort value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(int value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(uint value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(long value) where TEnum : struct, Enum;
        public static TEnum ToObject<TEnum>(ulong value) where TEnum : struct, Enum;
        public static int CompareTo<TEnum>(TEnum value, TEnum other) where TEnum : struct, Enum;
        public static bool Equals<TEnum>(TEnum value, TEnum other) where TEnum : struct, Enum;
        public static byte ToByte<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static short ToInt16<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static int ToInt32<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static long ToInt64<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static sbyte ToSByte<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static string ToString<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static string ToString<TEnum>(TEnum value, string format) where TEnum : struct, Enum;
        public static ushort ToUInt16<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static uint ToUInt32<TEnum>(TEnum value) where TEnum : struct, Enum;
        public static ulong ToUInt64<TEnum>(TEnum value) where TEnum : struct, Enum;
    }
}
```

## API Details
This proposal makes use of a `C#` language feature that needs to be added in order for this proposal to make the most impact.

This proposal specifies extension methods within `System.Enum` and as such requires `C#` to allow extension methods within non-static classes as is proposed in [csharplang#301](https://github.com/dotnet/csharplang/issues/301). Promoting these to extension methods later would be a breaking change due to [csharplang#665](https://github.com/dotnet/csharplang/issues/665) but I feel this is acceptable.

Alternatively, the extension methods could be defined in a separate static `EnumExtensions` class. This is uglier but would avoid this issue and the extension methods would be available immediately instead of needing to wait for a later `C#` version to support this.

## Open Questions
* Is promoting the `System.Enum` extension methods later an acceptable breaking change due to [csharplang#665](https://github.com/dotnet/csharplang/issues/665)? If not should we wait for a later `C#` version that supports extension methods in `System.Enum` or should we introduce a separate `EnumExtensions` class?

## Implementation Details
This proposal stems from my work on the open source library [Enums.NET](https://github.com/TylerBrinkley/Enums.NET) which addresses each of these issues and will be the basis for an implementation. For efficiency this is how `Enums.NET` is implemented.

First, using `Enum` as a generic type argument causes generic code-explosion in today's runtimes so it's essential that it's included sparingly. For this reason most logic is contained in an [`EnumCache<TInt, TIntProvider>`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/EnumCache.cs#L42) object where `TInt` is the underlying type and `TIntProvider` is the underlying type's operations provider which implements the interface [`INumericProvider<TInt>`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/Numerics/INumericProvider.cs#L31) which provides the bitwise operations and other needed operations. Including the `TIntProvider` as a type parameter allows the runtime to inline calls to its methods so there's no interface method dispatch, a technique described in this [generic calculations article](https://www.codeproject.com/articles/8531/using-generics-for-calculations).

Now how can one access this `EnumCache` object when the caller only has the enum type as a generic type argument? This is solved by the bridge-like object [`EnumInfo<TEnum, TInt, TIntProvider>`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/EnumInfo.cs#L45) which implements the interfaces [`IEnumInfo<TEnum>`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/IEnumInfo.cs#L101) for generic methods and [`IEnumInfo`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/IEnumInfo.cs#L44) for non-generic methods. It simply acts as a bridge to delegate calls from the interfaces to `EnumCache<TInt, TIntProvider>`. In order to do that it needs to be able to efficiently convert values between `TEnum` and `TInt`. This is performed by the conversion methods [`ToInt`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/EnumInfo.cs#L61) and [`ToEnum`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/EnumInfo.cs#L71) which are declared as `extern` methods for efficiency so that they're simply defined as casts from one type to the other. These method's functionality can be achieved with the `Unsafe.As` method. This `EnumInfo<TEnum, TInt, TIntProvider>` is created via reflection upon it's first call and is stored in the static field [`Enums<TEnum>.Info`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/Enums.cs#L1592) as an `IEnumInfo<TEnum>` which is then called by [`Enums`](https://github.com/TylerBrinkley/Enums.NET/blob/ca49e29a8effe0460135eeb10eed6cc1ec907188/Src/Enums.NET/Enums.cs#L38)'s generic methods.

For non-generic methods the `RuntimeType.GenericCache` property will be set to the `IEnumInfo` to use.

## Updates
* Added more implementation details.
* Added more API details.
* Added enumerating members usage example.
* Added generic versions of instance methods for performance reasons.
* Removed the `System.Enums` namespace and moved its members into the `System` namespace.
* Moved `PrimaryAttribute` into the `System.ComponentModel` namespace and switched to using the existing `System.ComponentModel.AttributeCollection`.
* Removed `IsValid` method as it's meaning is rather subjective and promoted `IsValidFlagCombination` as an extension method.
* Renamed `GetAllFlags` to `AllFlags` as it more closely resembles a property but can't be because it is generic. Similar naming to `Array.Empty`.
* Removed `EnumComparer` as one can just use `Comparer<T>.Default` and `EqualityComparer<T>.Default` instead.
* Split the proposed API to a base API addition and an `EnumMember` support API addition.
* Added `ReadOnlySpan<char>` parse overloads.
* Moved `FlagEnum.IsFlagEnum` into `System.Enum`.
* No longer proposes adding the `Enum` constraint to existing methods.
* Split `EnumMember` API addition into the separate issue dotnet/corefx#34077.
* Split generic API additions that don't necessitate the performance improvements of this implementation to separate issue dotnet/runtime#2364.
* Split Flag API additions to separate issue dotnet/corefx#34079.
* Split `PrimaryAttribute` addition to separate issue dotnet/corefx#34080.
* Moved `Format` to dotnet/runtime#2364 as well.
* Moved proposed methods from dotnet/runtime#2364 back to this issue.
* Removed `Format` as it's no different from `ToString(string format)` except it throws an `ArgumentNullException` for a `null` `format` parameter.

**Comment by koszeggy** [comment]
Ha! It's funny to see that almost everyone implemented their well-performing enum library when it used to be so slow in the .NET Framework era. [So did I](https://github.com/koszeggy/KGySoft.CoreLibraries#fast-enum-handling), of course. :)

I'm really happy to see the improvements made in .NET Core. I would've never created my alternative version if `System.Enum` was always that fast. In fact, I needed to do a massive refactoring in my libraries, just to justify its today's existence and make it [faster](https://dotnetfiddle.net/xNTnLE) again than the Core version. :) But to be frank, maybe its last really useful feature that it supports `ReadOnlySpan<char>`, which is still not implemented in the System version.

Anyhow, if it helps anything, feel free to re-use any solutions from it. Maybe it hasn't as many [features](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_CoreLibraries_Enum_1.htm) as Tyler's version and my approach was also much simpler in some aspects, but who knows... maybe you can find some useful parts in it.

**Comment by xaviergxf** [comment]
How about this api? Humanizr could use this...

```
public static ReadOnlySpan<char> GetName<TEnum>(this TEnum value) where TEnum : struct, Enum;
```

**Comment by huoyaoyuan** [comment]
> `public static ReadOnlySpan<char> GetName<TEnum>(this TEnum value) where TEnum : struct, Enum;`

Returning a span is never an option because of lifetime issue. Any api with result in span would require caller to allocate the span.

**Comment by tannergooding** [comment]
As with https://github.com/dotnet/runtime/issues/14084 this isn't a direction we'd like to move forward on.

The idiomatic bit operations are guaranteed to be efficient where-as these named methods aren't and potentially push users towards a pit of failure.
