### ISSUE TITLE
HMACXxx is throwing NRE when passing a null key

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/runtime#2002]
When instanciating a derived class from `HMAC` like `HMACSHA256`, there is not validation of the `byte[]` provided as key. This is causing a `NullReferenceException`.
```
new System.Security.Cryptography.HMACSHA256(null);
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Internal.Cryptography.HMACCommon.ChangeKey(Byte[] key)
   at System.Security.Cryptography.HMACSHA256..ctor(Byte[] key)
```

Passing a null key is probably not a good practice 🙄  , but the exception may be more explicit.

**Comment by vcsjones** [comment]
@bartonjs 

.NET Framework also throws a `NullReferenceException` instead of `ArgumentNullException`. Seems like it would still be an okay change, but not sure how important exception compatibility is here.

**Comment by bartonjs** [comment]
Changing NullReferenceException to ArgumentNullException is a thing we allow, since it shouldn't be in anyone's real program flow but improves diagnosability.

**Comment by vcsjones** [comment]
@bartonjs This actually uncovered something interesting. It looks like with the changes to `HMACCommon` to support HKDF, the passing a null key now results in a null key being used.

https://github.com/dotnet/runtime/commit/32388df1ad99d616377b5ec6ca4966d60f10b365#diff-1dbe8392724503f18cb198f4d5dd270dR46

**Comment by bartonjs** [comment]
The empty key is, sadly, legal (if it works in .NET Framework and .NET Core 3.1, we can't and shouldn't stop it).  Rejecting the null key before it gets converted to the empty span (I really, really hate that we made that conversion work) has virtue; and apparently is a wonderful timing on adding tests to make sure we reject null keys :smile:.
