### ISSUE TITLE
System.Configuration.ConfigurationManager needs more test coverage (51.8%)

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#20040]
dotnet/runtime#19296 ported the code for System.Configuration to facilitate porting existing .NET code. Test coverage is relatively sparse as this effort was meant to be demand driven. Adding additional tests (unit and scenario) is a good opportunity to get one's feet wet in CoreFX.

`ConfigurationPermission` is the only class that wasn't ported (Code Access Security isn't supported in CoreFX). The only known non-working class is `RsaProtectedConfigurationProvider` which is dependent on System.Security.Cryptography.Xml working (#14950).

**Comment by danmosemsft** [comment]
Hi @FireAlkazar  @vnwonah are you folks still working on this one? Also do either of you know the current coverage %?

**Comment by danmoseley** [comment]
I'm going to close this as it seems like a low priority given we plan to make no changes to this library and recommend against its use in new code.
