### ISSUE TITLE
GenerateThisAssemblyCS.targets file should be removed

### ISSUE THREAD

**Issue by weshaggard** [dotnet/runtime#20043]
cc @saurabh500 

We should either completely remove the GenerateThisAssemblyCS.targets (https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/GenerateThisAssemblyCs.targets) file or if we really need the functionality it should be merged into our Assembly information generation (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets).

**Comment by cheenamalhotra** [comment]
Closing as No-op for Microsoft.Data.SqlClient.
