### ISSUE TITLE
JIT: Get fixed size buffer item by index

### ISSUE THREAD

**Issue by oakio** [dotnet/runtime#2007]
Why JIT emit `cmp` instruction without any `jump` instruction for method `Baz`?
```csharp
public unsafe struct Foo
{
    public fixed int Bar[8];

    public int Baz(int i) => Bar[i];
}
```
JIT produces [(sharplab):](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACAVwDtdsAzGBshgYQYBvGg1EMRY+szaduuDFCZgMDAGIQIE0cOpi9PRhwCWCGABMGRlioBC2KAG0AHAF0A3DS36pV29gBeABS+lgCUDAC8AHwMdo5G7l4AvjRJQA==)
```
00007FFD16A10B40 nop       dword [rax+rax]
00007FFD16A10B45 cmp       [rcx],ecx
00007FFD16A10B47 movsxd    rax,edx
00007FFD16A10B4A mov       eax,[rcx+rax*4]
00007FFD16A10B4D ret
```

> $ dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.100
>  Commit:    cd82f021f4
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.100\
> 
> Host (useful for support):
>   Version: 3.1.0
>   Commit:  65f04fb6db

**Comment by AndyAyersMS** [comment]
It is a null check on `this`.

**Comment by oakio** [comment]
Thanks a lot!
