### ISSUE TITLE
Add exchange type for a scheduler

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#20070]
For pipelines, I'd like to be able to pass a `Scheduler` that determines where the continuation should run (could also be useful for other things). The closet thing we have today is a `SynchronizationContext` but it's really not appropriate for this. There's also a TaskScheduler but that's about scheduling tasks not arbitrary callbacks.

```C#
public interface IScheduler
{
   void Run(Action action);
}
```

Not sure what other options we'd need here. this is similar to Java's executor https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executor.html. 

/cc @stephentoub 

**EDIT: Current proposal**

```C#
public interface IScheduler
{
   void Schedule(Action<object> action, object state);
}
```

## Proposed API implemenations

**Scheduler**

```C#
public abstract class Scheduler : IScheduler
{
   public static IScheduler Default => ThreadPool.Global;
   public static IScheduler Inline { get; } 

   public abstract void Schedule(Action<object> action, object state);
}
```

The scheduler base class just has the default inline scheduler which runs actions inline. There are concerns about stack diving here but it's required for cases where the consumer wants to stay on the caller's thread.

**ThreadPool**

```C#
public class ThreadPool
{
    public static IScheduler Local { get; }  // QueueUserWorkItem (preferLocal:true)
    public static IScheduler Global { get; } // QueueUserWorkItem (preferLocal:false)
}
```

Here we're exposing 2 schedulers from the ThreadPool type. These map to QueueUserWorkItem with various arguments.

**SynchronizationContext**

```C#
public class SynchronizationContext : IScheduler
{
    public void Schedule(Action<object> action, object state)
    {
        Post(new SendOrPostCallback(action), state);
    }
}
```

Exposing the SynchronizationContext as an IScheduler would call Post on the sync context. Since most of the "dispatchers" in .NET already implement a sync context (WPF, System.Web, WinForms, UWP, Xamarin etc) this would be the way to bridge the existing tech with this new interface.

**TaskScheduler**

It should be possible to run Task continuations on any arbitrary IScheduler. We should be able to convert use any IScheduler as a TaskScheduler. This means any thing that uses an TaskScheduler today would just work with the IScheduler via a simple factory.

```C#
public class TaskScheduler
{
    public static TaskScheduler CreateFromScheduler(IScheduler scheduler);
}
```

## Potential APIs Consumers

Once we have the above types exposed we can start looking at places where using a scheduler might be beneficial. Generally, we can look at places that call directly into QueueUserWorkItem and determine if it makes sense to allow callers to specify which IScheduler should be used instead.

More specifically, here are some places it might be useful (we'd of course need to dig into the details more).

**SocketAsyncEventArgs**

SocketAsyncEventArgs has a callback that executes whenever any IO operation completes (read/write/connect/accept). Currently the thread that callback runs on is either a thread pool thread (in the linux case) or the IOCP completion thread on windows. There are some cases where the calling code wants fine grain control over where continuations run to avoid unnecessary context switches. In these cases it would be ideal if the SocketAsyncEventArgs exposed an IScheduler property that determined where completions ran.

```C#
public class SocketAsyncEventArgs
{
    public IScheduler Scheduler { get; set; }
}
```

This would allow callers to specify where continuations should run (it could even be OS specific).

**Timer**

Timer callbacks are always scheduled on threadpool threads. Adding a scheduler would allow using the timer API but would also allow callers to control where callbacks execute.

```C#
public Timer(TimerCallback callback, object state, int dueTime, int period, IScheduler scheduler);
public Timer(TimerCallback callback, object state, long dueTime, long period, IScheduler scheduler);
public Timer(TimerCallback callback, object state, TimeSpan dueTime, TimeSpan period, IScheduler scheduler);
public Timer(TimerCallback callback, object state, uint dueTime, uint period, IScheduler scheduler);
```

**Task continuations**

Running task continuations on specific threads when using async/await syntax today isn't possible without changing the current task scheduler (AFAIK). Ideally you would be able to do something like:

```C#
await task.ContinueOn(scheduler);
```

Today Task has very specific knowledge about the SynchronizationContext capturing because it's the most common scenario. There are scenarios where the caller whats to continue on another scheduler or TaskScheduler and wants to specify that at the point of the await.

```C#
public class Task
{
      public TaskAwaiter ContinueOn(TaskScheduler scheduler);
}
```

**CancellationToken**

CancellationTokens allow for the registration of callbacks that execute of callbacks upon cancellation. A scheduler can be specified to determine where these callbacks should run. This would be more efficient than scheduling the call to Cancel to run on another thread since doing if efficiently requires knowledge that callbacks are registered (see https://github.com/dotnet/corefx/issues/23716 for a related issue). There could be an overload of cancel that takes an IScheduler.

```C#
public class CancellationTokenSource
{
     public void Cancel(IScheduler scheduler);
}
```

**Comment by stephentoub** [comment]
This has been hanging out for five years now.  Is there a _real_ need at this point?  We've lived without it for so long, and introducing a brand new scheduler exchange type is a big deal.

The current proposal is:
```C#
public interface IScheduler
{
   void Schedule(Action<object> action, object state);
}
```
which is simple enough to add obviously, and implementing this on types like TaskScheduler and SynchronizationContext isn't hard.  I'm more concerned at this point about where it would actually end up getting used. We're not going to add overloads to every method that might possibly schedule work... that's effectively inclusive of every method that uses async/await today, which basically means every public {Value}Task-returning method could in the extreme "need" an overload that takes a scheduler, ala CancellationToken, and all await infrastructure would need to be taught how to interact with it (and in doing so there'd likely be a negative perf hit or a lot of code to work around said perf hit), and everywhere that explicitly uses ThreadPool, and Timer, and Task.Run, and so on.  Where would this actually end up getting consumed in higher-level APIs?  Where would ASP.NET expose use of this, for example?

I completely understand the desire for such an abstraction.  I'm tempted to say at this point it's just not worth it.
