### ISSUE TITLE
The CoreCLR artifacts path does not exist

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/runtime#2008]
Build with
```
build -subsetCategory coreclr -c Release
build -subsetCategory libraries -coreclrConfiguration Release
```
when I build src lib in debug I get error 
```
C:\git\runtime\src\libraries\System.Memory (getoffset -> origin)
λ msbuild /t:rebuild /v:m src
Microsoft (R) Build Engine version 16.5.0-preview-19562-03+d72e25031 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\git\runtime\eng\liveBuilds.targets(89,5): error : The CoreCLR artifacts path does not exist 'C:\git\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\'. The CoreCLR subset category must be built before bu
ilding this project. [C:\git\runtime\src\libraries\System.Memory\src\System.Memory.csproj]
```
Is it expected?

cc: @ViktorHofer @safern

**Comment by Gnbrkm41** [comment]
I believe it's `/p:CoreCLRConfiguration=Release`, at least for the `libraries.cmd` file; Not sure if it works with build.cmd.

**Comment by MarcoRossignoli** [comment]
I understood that switch was for "build libraries in debug with release version of coreclr".

**Comment by Gnbrkm41** [comment]
Ah, sorry. I didn't look at the full thing apparently...

**Comment by safern** [comment]
The build commands are correct. The problem you’re hitting here is that you’re building System.Memory which has a reference from runtime to System.Private.CoreLib, so we need to resolve it from somewhere, the path contains the coreclr configuration in it, so when building a project which has a reference to System.Private.CoreLib you need to pass down /p:CoreCLRConfiguration if the configuration you’re building the project for doesn’t matches what you build coreclr against.

**Comment by MarcoRossignoli** [comment]
Ok Santiago thank's, btw I build also debug version of coreclr and fixed.

**Comment by safern** [comment]
>  btw I build also debug version of coreclr and fixed.

But be careful with that, because tests will be super slow if you accidentally end up using that, because it will not be optimized and have a lot of Debug.Asserts.

**Comment by MarcoRossignoli** [comment]
You mean something like `msbuild /t:rebuild /v:m src /p:CoreCLRConfiguration=Release`

**Comment by ViktorHofer** [comment]
Just a note, because of now having two runtimes, the `coreclrConfiguration` script argument was just renamed to `runtimeConfiguration`.

**Comment by safern** [comment]
> You mean something like msbuild /t:rebuild /v:m src /p:CoreCLRConfiguration=Release

Yeah.
