### ISSUE TITLE
Improve performance of Package testing leg

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#2017]
Related dotnet/corefx#35693

A couple ideas we can use to shorten this:
1. Do a sparse matrix of RIDs for all the older frameworks.  The self-contained restores and tests are really the longest part of this work.  We end up doing a dozen tests for each framework, all of which have to download the entire shared framework for those RIDs.
2. Pre-restore the framework packages on the build machine and add them to a package folder that gets shared with all helix clients.  This has the potential of saving multiple clients from hitting nuget servers to download old packages.  They still end up downloading through helix though, so I don't this alone is a sufficient without also doing 1.

**Comment by ViktorHofer** [comment]
Package leg failing because of a 500 during the package download: https://dev.azure.com/dnceng/public/_build/results?buildId=519038&view=ms.vss-test-web.build-test-results-tab&runId=16410288&resultId=100064&paneView=attachments.

**Comment by ericstj** [comment]
Last we discussed we were going to eliminate RID-specific restores from this test process and make the RID-less run test all runtime-targets of the package against references instead of implementation.
