### ISSUE TITLE
SetCreationTime, SetLastAccessTime, SetLastWriteTime Should not open a new stream to obtain a SafeFileHandle

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dotnet/runtime#20234]
## API Proposal

``` c#
namespace System.IO
{
    public static class FileHandleExtensions
    {
        public static DateTime GetLastWriteTimeUtc(this SafeFileHandle fileHandle);
        public static void SetLastWriteTimeUtc(this SafeFileHandle fileHandle, DateTime time);
        public static DateTime GetLastAccessTimeUtc(this SafeFileHandle fileHandle);
        public static void SetLastAccessTimeUtc(this SafeFileHandle fileHandle, DateTime time);
        public static DateTime GetCreationTimeUtc(this SafeFileHandle fileHandle);
        public static void SetCreationTimeUtc(this SafeFileHandle fileHandle, DateTime time);
    }
}
```

## Original post

I know that in many cases it is ok to do so, but we found ourself in the case where we need to set file times without closing the actual `FileStream`, and this is possible via Windows API.
To do so we had to write **unsafe** code which mimic the functionality of the [existing functions](https://referencesource.microsoft.com/#mscorlib/system/io/file.cs,63bd669b43be5f17,references).
(which include rewriting [`System.IO.__Error.WinIOError()`](https://referencesource.microsoft.com/#mscorlib/system/io/file.cs,63bd669b43be5f17), this is obviusly a bad thing, because we have to maintain code wich already exist)
This could be extremely more usable and **maintainable** if the framework exposed those methods as `SafeFileHandle` Method/ExtensionMethod.

My proposal is to leave those functions unaltered but move the actual implementation in an ipotetic function:
`SafeFileHandle.SetFileTimesUtc(DateTime? creationTimeUtc, DateTime? lastAccessTimeUtc, DateTime? lastWriteTimeUtc)` which should be public.

**Comment by terrajobst** [comment]
* The scenario makes sense, but defining them as extension methods on `SafeFileHandle` seems odd
* It seems more logical to define them as overloads to the `string` based APIs on `File`.

```C#
namespace System.IO
{
    public static class File
    {
        public static DateTime GetCreationTime(SafeFileHandle fileHandle);
        public static DateTime GetCreationTimeUtc(SafeFileHandle fileHandle);
        public static DateTime GetLastAccessTime(SafeFileHandle fileHandle);
        public static DateTime GetLastAccessTimeUtc(SafeFileHandle fileHandle);
        public static DateTime GetLastWriteTime(SafeFileHandle fileHandle);
        public static DateTime GetLastWriteTimeUtc(SafeFileHandle fileHandle);
    }
}```

**Comment by danmosemsft** [comment]
Any volunteers interested in adding these?

**Comment by fowl2** [comment]
> The scenario makes sense, but defining them as extension methods on `SafeFileHandle` seems odd

They could be extension methods on `SafeFileHandle` _in_ `File` for discoverability?

**Comment by fowl2** [comment]
There is an advantage to putting these on `FileStream` (perhaps in addition) beyond paths in exceptions and that is that we could avoid the `SafeFileHandle` property accessor [which does this](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.safefilehandle#remarks):

> The SafeFileHandle property automatically flushes the stream and sets the current stream position to 0. This allows the file to be moved or the stream position to be reset by another stream using the SafeFileHandle returned by this property.

**Comment by terrajobst** [comment]
@fowl2 

> They could be extension methods on `SafeFileHandle` _in_ `File` for discoverability?

We don't define any extension methods in the `File` class today, but wouldn't be a blocker IMHO. What I find odd is that we don't really treat handles as things you invoke methods on (modulo anything related to the life time of said handle). Not that it's wrong, but it's just not the pattern.

> There is an advantage to putting these on `FileStream` (perhaps in addition) beyond paths in exceptions and that is that we could avoid the `SafeFileHandle` property accessor [which calls `Flush` on every read].

Is there a key scenario where avoiding flushing is necessary? Given that `Flush()` will only persist what it's pending in the buffer it seems that's generally desired.

**Comment by TrabacchinLuigi** [comment]
I avoided replying till now because i have absolutely zero experience on mantaining a framework.
But to me seems a desired behaviour to flush BEFORE setting LastWriteTime or LastAccessTime, because that would be the actual last access time, after flushing.

I see no weirdness in using SafeFileHandle extensions, what really matter to me is not getting an exception doing it, i don't want to give up the handle to that file and be able to set those values.

Just to give some context i had to do that because i'm writing an usermode filesystem, so my code get's called by a driver and it expect to be able to do that, obviusly, i could write my own logic to overcome that necessity, but it is WAY faster like that. and i want it to be fast.
Also it could be specified in the function annotations what the behaviour will be, and the user could just save the position before calling this and then reset it.

**Comment by fowl2** [comment]
> Is there a key scenario where avoiding flushing is necessary

Given this is primarily a performance optimisation - a 66% syscall reduction going from `Open()`->`SetXx()`->`Close()` to just `SetXx()` - going back to `Write()`->`SetXx()` could be significant. 

Resetting the stream position to 0 is what I'm be more worried about - that's surprising and could potentially cause data loss if mixing Read/Write and SetXx() calls. Unlikely, I guess?

> what really matter to me is not getting an exception

I think that would be a separate issue about getting Try*/result-code-returning versions of most of System.IO? I'm surprised I can't find an issue for that already actually.

**Comment by TrabacchinLuigi** [comment]
> > what really matter to me is not getting an exception
> 
> I think that would be a separate issue about getting Try*/result-code-returning versions of most of System.IO? I'm surprised I can't find an issue for that already actually.


Sorry i think i mis-phrased that. The exception was not the issue (but i agree, exception workflow isn't so great, and alternative methods would be nice), the issue was that wasn't possible without closing the filestream first .
So i had to close it, set the lastwrite, reopen it, seek to the end, that part was quite slow.

**Comment by terrajobst** [comment]
> Resetting the stream position to 0 is what I'm be more worried about - that's surprising and could potentially cause data loss if mixing Read/Write and SetXx() calls.

`Flush()` wouldn’t change the stream’s position. Or do I misunderstand what you’re saying?

**Comment by fowl2** [comment]
> `Flush()` wouldn’t change the stream’s position. Or do I misunderstand what you’re saying?

Accessing the `SafeFileHandle` property on a `FileStream` _does_ reset the position, which - as you've just demonstrated - is unexpected!

**Comment by terrajobst** [comment]
> Accessing the `SafeFileHandle` property on a `FileStream` _does_ reset the position, which - as you've just demonstrated - is unexpected!

Do you have a repro for .NET Core? Looking at the code, that doesn't seem intentional. Rather, it should merely validate that you don't advance the underlying file pointer that is baked by the file handle by calling OS APIs yourself

**Comment by fowl2** [comment]
[Indeed](https://github.com/dotnet/runtime/blob/6179582ab9d15180216e7b26e3f55cbc1d936483/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L595), it seems the docs are wrong.

**Comment by terrajobst** [comment]
Cool, sanity restored 😀 I’ll file a doc bug.

**Comment by fowl2** [comment]
Ok so reading a bit more, it also sets `_exposedHandle` true, which does end up causing an extra seek(0) syscall from `VerifyOSHandlePosition()` _every read/write_. Which seems like bad, and if you squint kinda vaguely relates to what the docs say.

**Comment by terrajobst** [comment]
Yes, but [it uses](https://github.com/dotnet/runtime/blob/6179582ab9d15180216e7b26e3f55cbc1d936483/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L636) `SeekCore(_fileHandle, 0, SeekOrigin.Current)` which seeks to `0` relative to current, which means it shouldn't change, assume the underlying handle wasn't seeked.

**Comment by fowl2** [comment]
Ahh, right I have no idea what the docs mean then. It's still an extra syscall though.

**Comment by deeprobin** [comment]
I would like to implement this :). If you want you can assign me the issue 😄

**Comment by Liryna** [comment]
Hi @deeprobin , it would be awesome! Please open a pull request when you are ready and ping me directly:) I would be glad to review your code !
