### ISSUE TITLE
Incompatibility warning when referencing System.ComponentModel.Composition.Registration from .NET Core

### ISSUE THREAD

**Issue by lothrop** [dotnet/runtime#2025]
I'm getting this warning when indirectly referencing the Nuget package `System.ComponentModel.Composition.Registration` in my .NET Core 3.1 project (through `Microsoft.Windows.Compatibility` version 3.1.0). I'm not sure what's causing this or what do do about it.

```
Package 'System.ComponentModel.Composition.Registration 4.7.0' was restored using
 '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7,
 .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8'
 instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not
 be fully compatible with your project.
```

This is the only package that is causing issues and I haven't figured out why. From what I can tell, the package contains a .NET Standard 2.1 version but my project chooses not to use that one.

**Comment by nkolev92** [comment]
When I restore the following project with 3.1.200-preview-014883, I don't get any warnings. 
I think a repro project + version of the tooling would be helpful.

```xml

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>_2025</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" /> 
  </ItemGroup>
</Project>
```

**Comment by mj1856** [comment]
I also get no warnings or errors installing `Microsoft.Windows.Compatibility` in a fresh .NET Core 3.1 project.

Do you have any other packages referenced? Try removing them one by one until you land on the one that changes the behavior.  Or alternatively, start with a clean project and add packages from your other project back in one-by-one until the behavior appears.

**Comment by lothrop** [comment]
Thanks, I will try to create a reproducing project.

**Comment by lothrop** [comment]
I have found the problem. Our Jenkins was using `nuget.exe restore`. Switching to `dotnet restore` fixed the problem. Not sure why it only happened on this module.
