### ISSUE TITLE
API Change: Restore CompileToMethod in S.L.Expressions

### ISSUE THREAD

**Issue by JonHanna** [dotnet/runtime#20270]
At https://github.com/dotnet/corefx/issues/11408#issue-174928345 @bartdesmet notes:

> I'm not clear why this method was removed. In fact, we tend to use it quite often (despite its limitations to emit only to static methods) in Bing, so I'd be interested in getting it back in .NET Core. All the code still seems to be there; just the entry-point was removed rather than conditionally excluded.

The entry-point came back conditionally excluded when that issue was closed. I also agree it can be useful, while I've only used it a handful of times myself, it was really useful those few times.

That Xamarin is now using this feature adds another advantage, in that we can't test it, and hence catch regressions that could break Xamarin, without it.

Mostly though I just think it can be useful, and is worth having.

`CompileToMethod()` has dependencies on most of what is covered by `FEATURE_COMPILE` so replacing `FEATURE_COMPILE_TO_METHODBUILDER` with `FEATURE_COMPILE` would bring it back in those builds that can feasibly use it (i.e. have support for Emit).

<S>The mechanism for testing across both interpreter and compiler could be extended to test across all three possibities of interpreter, compiler and `CompileToMethod()` with dynamic methods, but other cases should probably be separate choices.</S>

`CompileToMethod()` would require a separate set of tests.

- [ ] Approve change.
- [ ] Replace `FEATURE_COMPILE_TO_METHODBUILDER` with `FEATURE_COMPILE`
- [ ] Update `TryEmitConstants` to handle `TypeBuilder` constants when not emitting to `DynamicMethod` (may do this separately anyway if @marek-safar needs it).
- [ ] Update tests to include `CompileToMethod()` with `DynamicMethod`s
- [ ] Add tests for compiling to static methods.

**Comment by jaredpar** [comment]
Closing as we are not accepting new features, including bringing back old APIs, into the library at this time as it is effectively archived. More information is contained in the library [README.md](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/README.md)

**Comment by ltrzesniewski** [comment]
@jaredpar could you reconsider it for this particular feature, please?

All of the code is already there but disabled behind a `FEATURE_COMPILE_TO_METHODBUILDER` flag, and is missing when you migrate a project from .NET Framework to .NET Core. I think it wouldn't really be a risk to enable it: since it has been working on the .NET Framework, it's not exactly a "new" feature.

**Comment by EdinaLewis** [comment]
This missing feature has been the primary reason for my team not adopting .NET Core. Am I to understand then that this will not be part of .Net 5 either?

Please reconsider!
