### ISSUE TITLE
CMake version is broken on newer alpine container images

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#2030]
When trying to update the alpine container image the required cmake version isn't found on CoreClr builds. @akoeplinger thinks this is due to a general problem with alpine.

```
Error relocating /usr/bin/cmake:
_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

Meanwhile we added another path to only use the new image on Mono. We should remove that extra path to be consistent with our used container images.

When this is fixed, the #ifdef [here](https://github.com/dotnet/runtime/blob/5a948f14ad1c02edd4469321c137aa54913b5fc9/eng/pipelines/common/platform-matrix.yml#L90-L94) should be removed.

cc @akoeplinger @safern

**Comment by safern** [comment]
Thanks for filing the issue.

@jkoritzinsky might know more about this.

**Comment by jkoritzinsky** [comment]
This looks to be a variant of https://github.com/dotnet/runtime/issues/1723. We've been installing cmake from the Alpine edge package repository to get a new enough version. It looks like their `edge` version moved up. We can change this to install from the `v3.11` package repository to get back to a working version. I'll take this one.

**Comment by ViktorHofer** [comment]
Thanks Jeremy!

**Comment by jkoritzinsky** [comment]
Ok after some testing, we're going to have to drop back to the CMake that ships in Alpine Linux 3.10 (this issue is also present in 3.11), which is version 3.14.5. Our CMake scripts currently only require a minimum of 3.14.2, so we should be ok, but its kinda disappointing that we're going to have split minimum CMake versions again.
