### ISSUE TITLE
Improve System.Numerics.Matrix* hash codes

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#20308]
Currently, the fields' hash codes are simply added: https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Matrix4x4.cs#L2209-L2212, https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Matrix3x2.cs#L805-L807. It seems like it would be better to change this to use [`HashHelpers.Combine()`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Numerics/Hashing/HashHelpers.cs#L11).

**Comment by tannergooding** [comment]
This fix should use the new `System.HashCode` type to construct the final hash.

**Comment by danmosemsft** [comment]
There are other cases of feeding hashcodes rather than objects to `HashCode.Combine` eg

https://github.com/dotnet/runtime/blob/1c742872229ffc8d6a6056dcbcec270cf50bf42e/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L567-L568

Should those all be fixed?

**Comment by tannergooding** [comment]
@stephentoub was saying we might need further investigation and profiling.
The two will be basically equivalent with the former producing less generic explosion due to everything taking `int`
