### ISSUE TITLE
JIT misses removing an unnecessary null check

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#2032]
A common pattern in native code for getting the offset of a field is:
```
&((T*)0)->Field
```

The JIT actually seems to optimize this nicely and folds it down to a constant:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgDkBXfGKASzFwG4BYAKD+IBmSgCZyAYXIBvPuTmVh1JOQYA7XNgBmMcq1UZyAeU2bcMDMYAUASmmz5D4gHZylvRmsAyS5YBqMMAxoFAAqa1JrOAA+AC0eXgcAXz5EoA===

However, it fails to remove the `null` check (which is no longer needed as the variable is never actually accessed) leading to an AV at runtime:
```
    L0000: xor eax, eax
    L0002: cmp [rax], eax
    L0004: mov eax, 0x8
    L0009: ret
```

It would be nice if the runtime could elide this so that the pattern can be used without needing to declare an otherwise unused local.

**Comment by jkotas** [comment]
> It would be nice if the runtime could elide this

It would be invalid optimization. The spec requires field access to be null checked. From ECMA-335, ldfld: "System.NullReferenceException is thrown if obj is null and the field is not static."

**Comment by tannergooding** [comment]
That seems unfortunate, especially since there is no actual memory access going on (and the JIT otherwise recognizes and optimizes for that).

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/issues/33706 has discussion about the best way to expose field offsets.
