### ISSUE TITLE
Using `include_directories(SYSTEM...` for openssl and curl breaks cross compilation for Yocto Linux

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#20364]
While taming the build process to run in a Yocto Linux cross compile environment, one road block was the explicit inclusion of the curl and openssl include directories [here](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Net.Http.Native/CMakeLists.txt#L26) and [here](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Security.Cryptography.Native/CMakeLists.txt#L16).

The effect of these statements is (with clang 3.9.1) that the `${SYSROOT}/usr/include` folder (where curl and openssl headers reside in a Yocto build environment) becomes an `-isystem` parameter to clang and this reorders that folder above the C++ include folders. When clang now tries to resolve C++ header files, it fails on an `#include_next <stdlib.h>`, because that file isn't found in a folder that comes after the C++ header folders.

Blaming the two CMakeLists points to build issues for OSX and BSD, but I cannot build for those targets. Otherwise I would check if the entire `include_directories` statement is actually necessary, or if removing the `SYSTEM` argument still makes the build succeed (it should).

See also dotnet/core-setup#1598

**Comment by ViktorHofer** [comment]
@Tragetaschen do you have time to verify if this is still broken? Thanks.

**Comment by Tragetaschen** [comment]
Upon reviewing, https://github.com/dotnet/runtime/commit/47d738a2ae78b3ec762dfc8d37d625da7453960d should have fixed this issue here as well
