### ISSUE TITLE
Expose general purpose Crc32 APIs

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#2036]
### Rationale

Computing a Cyclic Redundancy Check (CRC) is a common algorithm used for error detection in things like networks or storage. Additionally, modern hardware provides instruction level support for computing these values. It would be beneficial if we exposed a set of general-purpose methods which allow iterative CRC32 computation.

### Proposed API
```csharp
namespace System.Numerics
{
    public static class BitOperations
    {
        public static uint Crc32(uint crc, byte data);
        public static uint Crc32(uint crc, ushort data);
        public static uint Crc32(uint crc, uint data);
        public static uint Crc32(uint crc, ulong data);
    }
}
```

### Open Questions

The output is generally treated as unsigned, however .NET considers unsigned integers (other than byte) as non-CLS compliant. It would be possible to expose both versions (those that take/return `int` and those that take/return `uint`). It would likewise be good on the input data to determine if they should be signed, unsigned, or both.

**Comment by Wraith2** [comment]
Is this using a specific polynomial? and if so which one? and can there be a way for the user to choose?

**Comment by tannergooding** [comment]
> can there be a way for the user to choose?

Not if we want these accelerated by the underlying hardware.
* X86 uses: 0x1EDC6F41
* ARM uses: 0x04C11DB7 or 0x1EDC6F41 (depending on the instruction)

**Comment by Wraith2** [comment]
So if someone is dealing with zip or something using the old polynomial they'll still need to make their own. That's a bit of a shame. 

Given that at least half of the time you want to calculate a crc you will be validating incoming data it might make sense to have a `ReadOnlySpan<byte>` overload (that works on a fixed length, leave looping to users).

**Comment by GrabYourPitchforks** [comment]
If we were to expose a CRC32 API over a buffer rather than an integral type I'd probably push for it not to be on the `BitOperations` class.

**Comment by Wraith2** [comment]
If `BitOperations` and these methods only exist to provide access to the hardware intrinsics I agree. 
It would be useful to have a `CRC32HashAlgorithm` available which uses these operations if they are available.

**Comment by tannergooding** [comment]
> If BitOperations and these methods only exist to provide access to the hardware intrinsics I agree

Right, this is namely meant to be a "cross-platform" version of the hardware intrinsics (much like the other functions on `System.Numerics.BitOperations`) and should allow users to easily get:
```
if (X86.Sse42.IsSupported) { }
else if (Arm.Crc32.IsSupported) { }
else { /* software fallback */ }
```

I agree that having a more general purpose class that allows polynomial customization and trivial operation over spans of data would be useful, but that isn't the immediate goal of this API.

**Comment by danmosemsft** [comment]
If I understand right, given the caller can't choose the polynomial, and we will use the fixed CPU specific algorithm if available, this API would only be useful for callers that are (a) not interoperating with some other format that has a chosen polynomial (such as zlib), and (b) do not need to exchange the value across architectures. Is that right?

**Comment by tannergooding** [comment]
We likely could provide both and we might even be able to expose the API in such a way that the JIT specially handles the method if the polynomial given is constant.

But as proposed, it would be limited to the given polynomials.

**Comment by danmosemsft** [comment]
I guess I'm wondering whether there's examples when this API with the "undefined" polynomial would be useful. But maybe that's not that different to asking when the intrinsics we already have would be useful. It would have to be when you're producing/consuming on the same machine. (Unless I misunderstand)

**Comment by terrajobst** [comment]
* Looks good as proposed
* We can add overloads with custom polynomials later, but we should document the ones that we're using here.

```C#
namespace System.Numerics
{
    public static class BitOperations
    {
        public static uint Crc32(uint crc, byte data);
        public static uint Crc32(uint crc, ushort data);
        public static uint Crc32(uint crc, uint data);
        public static uint Crc32(uint crc, ulong data);
    }
}
```

**Comment by danmosemsft** [comment]
I watched the video and I still need clarification on my questions I think 😄 
1. How will we choose the polynomial?
1. Whatever we pick, it it will only be hardware accelerated on x64/x86 OR ARMxx, or neither, but not both, right? But it will give the same results on all CPU/platforms?
1. Are we targeting a specific standard (eg., zlib, or some other RFC or file format) or is this primarily for when I don't care about the polynomial because I'm both calculating the CRC and verifying the CRC in my own app?

**Comment by tannergooding** [comment]
The polynomial is `0x1EDC6F41`, it is accelerated on both x86/x64 and ARM64 (I'm not sure about ARM32). ARM64 has an additional polynomial that it can also accelerate, `0x04C11DB7`, which would require something like `Crc32(uint crc, byte data, uint polynomial)` to support. The JIT could then optimize it when `polynomial` is a constant of that value.

The polynomial being used is for CRC32-Castagnoli, which is fairly popular/prevalent and adopted in several standards; but which is not universaly used.

**Comment by tannergooding** [comment]
In particular, wikipedia lists `Castagnoli` as used by `iSCSI, SCTP, G.hn payload, SSE4.2, Btrfs, ext4, Ceph`. Arm64's other polynomial is used by `ISO 3309 (HDLC), ANSI X3.66 (ADCCP), FIPS PUB 71, FED-STD-1003, ITU-T V.42, ISO/IEC/IEEE 802-3 (Ethernet), SATA, MPEG-2, PKZIP, Gzip, Bzip2, POSIX cksum,[52] PNG,[53] ZMODEM, many others`, but has no built-in acceleration for x86/x64.

**Comment by danmosemsft** [comment]
I see. That also seems to be the one used by the most popular package (CRC32C.NET)

**Comment by shaggygi** [comment]
Any plans to add Crc8 and Crc16 support, as well?

**Comment by Wraith2** [comment]
Not as part of this work because I don't believe there is hardware intrinsic that provides either of those.
There does seem to be some interest in having CRC algorithms in general but I think that would need a separate api proposal and it's too late in the release cycle to get them into 5 even if approved.

**Comment by Gnbrkm41** [comment]
Could I give this a try?

**Comment by tannergooding** [comment]
Sure thing, thanks @Gnbrkm41!

**Comment by Gnbrkm41** [comment]
Looks like I forgot to ask getting this particular issue unassigned - could I get it unassigned? Sorry for the absence.

**Comment by tannergooding** [comment]
No worries and thanks for the update!

**Comment by MichalPetryka** [comment]
Since the software fallback would need a lookup table, would that be hardcoded in a source file for max performance or generated in runtime in a static constructor (which could be a bit punishing due to a big amount of calculations on the first call to other APIs even when not using CRC32C) or lazily using `??=` or something like that in each method?

**Comment by MichalPetryka** [comment]
Also, I'd consider indicating the polynolmial in the method names by calling them for example `Crc32Castagnoli` to avoid potential confusion, especially since CRC32 is usually used to refer to the `0x04C11DB7` polynolmial and CRC32C for the `0x1EDC6F41` which the API will be using, this would also cause less issues in the future if you'd decide to make a method with the `0x04C11DB7` polynolmial with ARM acceleration.

**Comment by tannergooding** [comment]
> Since the software fallback would need a lookup table, would that be hardcoded in a source file for max performance or generated in runtime in a static constructor (

We typically encode tables as `private static readonly` fields, but it ultimately depends on how large the table will be vs its cost of computing at runtime.

**Comment by tannergooding** [comment]
> Also, I'd consider indicating the polynolmial in the method names by calling them for example Crc32Castagnoli to avoid potential confusion

IIRC, we had discussed this in API review and had decided against this.
However, someone would need to go back and watch the API review to confirm if we had just discussed future overloads or specifically calling this one `Crc32C` or similar

**Comment by reflectronic** [comment]
The review only discussed adding the overload which takes a polynomial as a parameter.

**Comment by MichalPetryka** [comment]
> > Since the software fallback would need a lookup table, would that be hardcoded in a source file for max performance or generated in runtime in a static constructor (
> 
> We typically encode tables as `private static readonly` fields, but it ultimately depends on how large the table will be vs its cost of computing at runtime.

The table I'd use would consist of 2048 uints, so it's pretty big. Runtime computation would take a while (67.31 us on my machine according to Benchmark.Net which doesn't include the JIT cost, first run would be much slower) but putting it in code would make a bit of a mess, making the class partial and putting it in a separate file would improve it a bit though.
Embedding it in code would also save a bit of memory due to the .Net optimization with ReadOnlySpans that creates them over the module data section instead of allocating an array.

**Comment by tannergooding** [comment]
The `CRC32` hardware acceleration support on x86/x64 has been around since approx. late 2008 so the likelihood that the software fallback path gets executed for these platforms is going to be fairly slim.

On the other hand, `CRC32` is optional in ARMv8.0 (approx. 2013) but required in ARMv8.1 (approx. 2016). Likewise, ARM32 currently has no hardware acceleration support.
* Based on the wikipedia list for released ARMv8-A cores

Given this, it would be good to see what the perf difference is between using the lookup table, an implementation with no lookup, and one with a dynamically computed lookup table. 8KB is a lot of metadata to add and may end up impacting certain workloads negatively, particularly if the software fallback never actually gets used on most hardware that runs .NET

**Comment by MichalPetryka** [comment]
Some points regarding the software fallback:
1. On x86 processes (32bit) the ulong overload will also take the software path if I understand correctly?
2. According to Steamworks hardware statistics, in our game (which requires x64) about 1.5% of users (from 35.5k that agreed to collection of statistics last month) have CPUs that don't support SSE 4.2.
3. The software path would be really common on ARM, due to ARMv8.1 being fairly recent.
4. In some cases, things like OS configuration might make the accelerated path unsupported on CPUs that do support it.

Regarding the benchmarks, I'm gonna compare them soon, I've already compared the SSE instruction with my software fallback with a table generated in a static constructor and the results were `0.0544 ns` for SSE and `5.4726 ns` for software while computing a crc of a ulong.

**Comment by MichalPetryka** [comment]
I've tried to benchmark it, but I'm having an issue: awful results with the precomputed table make me think that the optimization from https://github.com/dotnet/roslyn/pull/24621 seems to not kick in, could somebody check what's going on? https://github.com/MichalPetryka/Crc32CBenchmark/blob/master/Crc32CBenchmark/CrcPrecomputedTable.Table.cs#L7

The results I got:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 8.1 (6.3.9600.0)
Intel Core i3-4130 CPU 3.40GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
Frequency=3319351 Hz, Resolution=301.2637 ns, Timer=TSC
.NET Core SDK=5.0.102
  [Host]        : .NET Core 5.0 (CoreCLR 5.0.220.61120, CoreFX 5.0.220.61120), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.2 (CoreCLR 5.0.220.61120, CoreFX 5.0.220.61120), X64 RyuJIT

Job=.NET Core 5.0  Runtime=.NET Core 5.0  

```
|                     Method |          Mean |      Error |     StdDev |        Median | Ratio |
|--------------------------- |--------------:|-----------:|-----------:|--------------:|------:|
|                        SSE |     0.0044 ns |  0.0093 ns |  0.0073 ns |     0.0010 ns | 0.000 |
|        &#39;Precomputed Table&#39; | 4,892.2823 ns | 94.6793 ns | 88.5631 ns | 4,871.3613 ns | 1.000 |
| &#39;Static constructor table&#39; |     5.3446 ns |  0.0295 ns |  0.0276 ns |     5.3356 ns | 0.001 |
|                 &#39;No table&#39; |    90.3318 ns |  0.1761 ns |  0.1561 ns |    90.2537 ns | 0.018 |

**Comment by jkotas** [comment]
That optimization only kicks in for byte and sbyte arrays. You would need to store the table as byte array. 

I do not think the precomputed table makes sense for this. Computing the table on the fly for the fallback case should be just fine.

**Comment by MichalPetryka** [comment]
> That optimization only kicks in for byte and sbyte arrays. You would need to store the table as byte array.
> 
> I do not think the precomputed table makes sense for this. Computing the table on the fly for the fallback case should be just fine.

The description of that PR says `arrays of primitive literals.` so I assumed that `uint`s would also count.

**Comment by MichalPetryka** [comment]
I've changed the table to be stored in a `uint[]` and added a benchmark using `??=`, which seems to have only a minimal impact on performance. As we can see, all table based implementations are roughly the same, while the no table one (which I've taken from https://medium.com/@nxtchg/crc-32-without-lookup-tables-1682405aa048 and adapted into C#) is noticeably slower.

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 8.1 (6.3.9600.0)
Intel Core i3-4130 CPU 3.40GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
Frequency=3319351 Hz, Resolution=301.2637 ns, Timer=TSC
.NET Core SDK=5.0.102
  [Host]        : .NET Core 5.0 (CoreCLR 5.0.220.61120, CoreFX 5.0.220.61120), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.2 (CoreCLR 5.0.220.61120, CoreFX 5.0.220.61120), X64 RyuJIT

Job=.NET Core 5.0  Runtime=.NET Core 5.0  

```
|                     Method |       Mean |     Error |    StdDev |  Ratio | RatioSD |
|--------------------------- |-----------:|----------:|----------:|-------:|--------:|
|                        SSE |  0.0468 ns | 0.0103 ns | 0.0091 ns |  0.008 |    0.00 |
|        &#39;Precomputed Table&#39; |  5.7565 ns | 0.0564 ns | 0.0528 ns |  1.000 |    0.00 |
| &#39;Static constructor table&#39; |  5.7247 ns | 0.0299 ns | 0.0265 ns |  0.995 |    0.01 |
|     &#39;Lazy generated table&#39; |  5.8886 ns | 0.0319 ns | 0.0283 ns |  1.023 |    0.01 |
|                 &#39;No table&#39; | 90.6089 ns | 0.1864 ns | 0.1653 ns | 15.743 |    0.16 |

**Comment by tannergooding** [comment]
The `ReadOnlySpan<byte> => new[] { }` trick only works for `byte` due to endianness.

You need to do `readonly T[] = new [] { }` for other types for it to be efficient: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ6QA5QCWAbgIYAuM5OSUgCUYnACYB5AHYAbAJ4BlJpykAeAK6sp3AHykAKp2AyYOUgF49UmAHcA2gF1ahAJCNSABgQefvnwFUAGk8EADEsJAAhAA5iD2IgkIBRHGJIgHYPUPTEr1SAViziUJRchEp0gE4AQUr0nFCy4nzQnBwUHEoyiOqcJPSk6LKAERRKatQkyKD6RgBfAG5ZhmXmNi5efkFYcQhZOVJNbUcDIxMsC1Jreyc6AjdGLz8/MvCo2PiylLTM7LKCoolMoVGp1BpNFptDpdYJeHp9AZDWEIUbjSbTQKrRaEOZAA

**Comment by MichalPetryka** [comment]
Yeah, noticed after reading the commets on that PR, was my fault for not checking them.

**Comment by tannergooding** [comment]
This came up as part of https://github.com/dotnet/runtime/issues/24328, and we probably want to use `Crc32C` as the name to match what will likely be exposed in the more general-purpose hashing algorithms:
```csharp
namespace System.Numerics
{
    public static class BitOperations
    {
        public static uint Crc32C(uint crc, byte data);
        public static uint Crc32C(uint crc, ushort data);
        public static uint Crc32C(uint crc, uint data);
        public static uint Crc32C(uint crc, ulong data);
    }
}
```

CC. @bartonjs, @terrajobst, @GrabYourPitchforks could we confirm this is desired and that the above is the desired implementation shape?

**Comment by terrajobst** [comment]
Makes sense to us (@dotnet/fxdc)

**Comment by wiz0u** [comment]
Can you expose as well a method for Crc32 computation on buffers ? I don't think .NET has a public one.

For example, simply turning System.IO.Compression.Crc32Helper public would be nice.

**Comment by tannergooding** [comment]
@wiz0u have you seen https://github.com/dotnet/runtime/issues/24328? This includes general purpose Crc32 APIs and will be in .NET 6 (under System.IO.Hashing: https://source.dot.net/#System.IO.Hashing/System/IO/Hashing/Crc32.cs,6471de2466bb4aa7).

**Comment by wiz0u** [comment]
> @wiz0u have you seen #24328? This includes general purpose Crc32 APIs and will be in .NET 6 (under System.IO.Hashing: https://source.dot.net/#System.IO.Hashing/System/IO/Hashing/Crc32.cs,6471de2466bb4aa7).

ah great! thanks!

**Comment by deeprobin** [comment]
I would suggest adding another method to the proposal with the nuint parameter type.

**Comment by MichalPetryka** [comment]
> I would suggest adding another method to the proposal with the nuint parameter type.

I wouldn't find that necessarily useful, the point of the overloads is to hash multiple bytes at once so it usually involves reading byte array values as different types, which gets a bit unclean when the type we read isn't constant size.

**Comment by tannergooding** [comment]
> I wouldn't find that necessarily useful, the point of the overloads is to hash multiple bytes at once so it usually involves reading byte array values as different types, which gets a bit unclean when the type we read isn't constant size.

The type is a constant size for a given run (32-bits on 32-bit machines and 64-bits on 64-bit machines), as is the result (32-bits). It only makes a difference on how efficiently you can process the bits for large inputs (`nuint` allowing you to process a full register of bits every iteration, incrementing is still ``+ sizeof(nuint)` bytes per iteration).

**Comment by bartonjs** [comment]
@tannergooding I can't tell if you're arguing for, against, or just providing data :smile:.

```C#
        public static uint Crc32C(uint crc, nuint data);
```

seems like a reasonable addition on the surface of things, but won't it produce different answers on 32-bit and 64-bit executions for the same 32-bit compatible value, since a 64-bit run sees 4 extra bytes in the payload?

I'm probably leaning toward not having it and making the caller be clear if they always want 64-bit semantics or if they wanted platform native, on the assumption that `nuint val = 5; return Crc32C(0, val);` would give different answers on different CPUs.

**Comment by MichalPetryka** [comment]
> @tannergooding I can't tell if you're arguing for, against, or just providing data .
> 
> ```cs
>         public static uint Crc32C(uint crc, nuint data);
> ```
> 
> seems like a reasonable addition on the surface of things, but won't it produce different answers on 32-bit and 64-bit executions for the same 32-bit compatible value, since a 64-bit run sees 4 extra bytes in the payload?
> 
> I'm probably leaning toward not having it and making the caller be clear if they always want 64-bit semantics or if they wanted platform native, on the assumption that `nuint val = 5; return Crc32C(0, val);` would give different answers on different CPUs.

It will produce different values.

**Comment by tannergooding** [comment]
@bartonjs, these are the primitive building blocks and so it's up the the author of a more general Crc32 loop to correctly handle any trailing bytes.\

I would expect, for example, if you have 11 bytes that you'd do: 1 or 2 iterations using `nuint` and then handle the remaining 3 bytes independently of the main loop, likely using the `ushort` or `byte` overloads, rather than explicitly loading up a `nuint` sized value. The same goes for if you were using `uint` or `ulong` directly.

The only difference between all of these is how many bytes get operated on "per iteration".

**Comment by kasperk81** [comment]
inconsistency between `System.Numerics.BitOperations.Crc32C(uint crc, byte data)` and `System.IO.Hashing.Crc32C.Hash(byte[] data)` is the initial value of `crc` is hardcoded (`0xFFFF_FFFFu`) in System.IO.Hashing one. should there be a matching overload `System.IO.Hashing.Crc32C.Hash(uint crc, byte[] data)`?

**Comment by Wraith2** [comment]
I don't think that's required. The System.IO.Hashing is a oneshot not an additive so you pass it the total data and then it computes it all which will include the final mask which is normally used to tell the difference between a hash of 0 entries and an empty hash. The intrinsic is just the underlying platform instruction being exposed for use.

**Comment by bartonjs** [comment]
In addition to the things @Wraith2 already pointed out, the System.IO.Hashing.Crc32 type is computing a different 32-bit CRC than this primitive.  System.IO.Hashing.Crc32 computes the same CRC-32 used for Ethernet; this one is used for "CRC-32C", which is used in ext4.

https://stackoverflow.com/questions/26429360/crc32-vs-crc32c

CRC-32: https://reveng.sourceforge.io/crc-catalogue/17plus.htm#crc.cat.crc-32-iso-hdlc
CRC-32C: https://reveng.sourceforge.io/crc-catalogue/17plus.htm#crc.cat.crc-32-iscsi

**Comment by deeprobin** [comment]
This issue is blocked by https://github.com/dotnet/runtime/issues/62692.

@tannergooding can you please remove the `up-for-grabs` label :smile:?
