### ISSUE TITLE
Proposal: ConfigurationManager.OpenExeConfiguration overloads

### ISSUE THREAD

**Issue by MgSam** [dotnet/runtime#20361]
### Proposal
Currently, `ConfigurationManager` can only load new settings by giving it the file path to an app.config file. This is annoying if you want to embed your configuration as a resource string or file in your DLL. 

I propose adding two overloads to `ConfigurationManager.OpenExeConfiguration`, one that accepts a string of the config xml and another that accepts a stream.

``` C#
ConfigurationManager.OpenExeConfiguration(string content);

ConfigurationManager.OpenExeConfiguration(Stream stream);
```

I believe the implementation may require changes to the `Configuration` class as well.

### Benefits
Potentially easier and more efficient ways to load settings into ConfigurationManager.

### Drawbacks
None that I can see.

### Related
This issue has been vexing the community for years:
http://stackoverflow.com/questions/9779962/using-net-configurationmanager-to-read-settings-from-a-string-instead-of-an-app
http://stackoverflow.com/questions/4079393/load-configuration-file-from-stream-instead-of-file
http://stackoverflow.com/questions/4738/using-configurationmanager-to-load-config-from-an-arbitrary-location

**Comment by ericstj** [comment]
We don't plan any investments in System.Configuration.ConfigurationManager.  This was ported largely for legacy code to be able to move to .NETCore.   If there were some low-risk / high-value changes we would consider them, but this doesn't appear to be one of those.

`ConfigurationManager.OpenExeConfiguration(string content);`

This [already exists](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.openexeconfiguration?view=dotnet-plat-ext-3.1#System_Configuration_ConfigurationManager_OpenExeConfiguration_System_String_) and accepts the Exe base to probe for config files.  

`ConfigurationManager.OpenExeConfiguration(Stream stream);`

Currently the entire ConfigurationManager system has file-probing baked down to a very low level.  Plumbing a stream from API from the top would likely require a significant rewrite.
