### ISSUE TITLE
MSBuild condition for runtime identifier "family"

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/runtime#2037]
So, I'm experimenting with some of the new [compile/deploy options](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#compiledeploy). Maybe I want to do something different depending on the runtime identifier that I'm passed. But, I might not really know if I'm going to get `win`, `win-x64`, or `win7-x64`, for example.

```xml
<PropertyGroup Condition="'$(RuntimeIdentifier)'=='win-x64'">
```

Is there anyway to detect the ["family"](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#rid-graph) of runtime identifier or to have access to the entire graph in MSBuild?

Are you going to tell me to use a [string property function](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2015&redirectedfrom=MSDN#BKMK_String)? Would that be reliable? Is this a bad idea?

```xml
<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win')">
```

**Comment by jeffschwMSFT** [comment]
@nguerrera

**Comment by AnthonyMastrean** [comment]
Seems like I might be able to use something like [`IsOSPlatform`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform) in a condition?

**Comment by jeffschwMSFT** [comment]
Moved to https://github.com/dotnet/sdk/issues/10606
