### ISSUE TITLE
Detect incompatible platform for ReadyToRun builds

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/runtime#2041]
If I'm using the new [ReadyToRun](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#readytorun-images) feature, I need to pass a specific runtime identifier. But, I also need to build on a compatible platform (for example, build `win-x64` on Windows 10 and `linux-x64` on Ubuntu).

Is there anyway to detect, in MSBuild, that my platform is not compatible _before_ I build and get this gnarly warning?

> usr/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(270,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false.

My specific use-case is that my build infra. is all Docker based... so, I can't build ready to run osx-x64 binaries. I'd like to fallback to a runtime dependent build.

```xml
<PropertyGroup Condition="...">
    <PublishReadyToRun>false</PublishReadyToRun>
</PropertyGroup>
```

**Comment by jeffschwMSFT** [comment]
@fadimounir

**Comment by fadimounir** [comment]
@AnthonyMastrean Unfortunately, there's currently no way in MSBuild to detect if the host platform you are using supports publishing ReadyToRun for a certain target platform.

Documentation on the compatibility matrix can be found in the initial blog post that was published for the Preview6 build of .Net Core 3.0: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/ (@richlander might have more info on where to find the equivalent of this post for the final release of 3.0).

**Comment by AnthonyMastrean** [comment]
Seems like I might be able to use something like IsOSPlatform in a condition?

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform

**Comment by fadimounir** [comment]
You could use `IsOSPlatform` yes if you wanted to implement your own checks
