### ISSUE TITLE
System.Security.Cryptography.Xml feature requests

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#20429]
This is an issue to collect all the feature requests after we finish stabilizing.
Some of them might be already implemented on Mono and might need a port.
cc: @anthonylangsworth @tintoy @peterwurzinger 

Feature requests:
- [ ] Add support for adding algorithms

Features resulting from failing tests: (there is no compat break between Desktop so marking as future) - they can be possibly Mono bugs
- [ ] SignedXmlTest.DataReferenceToNonDataObject (There is an existing test with this - currently this is also not working on Desktop but likely is on Mono)
- [ ] SignedXmlTest.GetIdElement_Null (throws ArgumentNullException on Desktop, seems to be valid on Mono)
- [ ] SignedXmlTest.HmacMustBeMultipleOfEightBits (Desktop does not throw, Mono throws CryptographicException)
- [ ] SignedXmlTest.VerifyHMAC_ZeroLength (Desktop does not throw, Mono throws CryptographicException)
- [ ] SignedXmlTest.VerifyHMAC_SmallerThanMinimumLength (Mono has it with category "NotWorking") - verify if should be fixed
- [ ] SignedXmlTest.VerifyHMAC_MinimumLength (Failing also on Desktop - seems to be passing on Mono)
- [ ] SignedXmlTest.VerifyHMAC_SmallerHalfLength (Failing also on Desktop - seems to be passing on Mono)
- [ ] SignedXmlTest.VerifyHMAC_HalfLength (Failing also on Desktop - seems to be passing on Mono)
- [ ] SignedXmlTest.VerifyHMAC_HMACOutputLength_Signature_Mismatch (Failing also on Desktop - seems to be passing on Mono)
- [ ] SignedXmlTest.VerifyHMAC_HMACOutputLength_Invalid (Failing also on Desktop - seems to be passing on Mono)
- [ ] XmlDsigExcC14NWithCommentsTransformTest.LoadInputAsXmlNodeList, LoadInputAsXmlNodeList2 (Failing also on Desktop - seems to be working on Mono)
- [x] EncryptedXmlTest.GetDecryptionIV_StringNull (Failing also on Desktop - seems to be working on Mono) - https://github.com/dotnet/corefx/pull/17221
- [ ] SignedInfoTest.GetXmlWithSetProperty (Failing also on Desktop - seems to be working on Mono)

**Comment by bartonjs** [comment]
It's been 7 years since this TODO list made progress.  It's apparently about as done as it's ever going to get.
