### ISSUE TITLE
Extension method to number

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#20461]
I think it would be useful if number have some extension method as helper in many trivial function instead of static class

First I would like to suggest `To` and `Range`

```C#
namespace System.Linq;

public static IEnumerable<int> To(this int start,int end)
{
    var sign = Math.Sign(end - start);
    end += sign;
    while(start != end)
    {
         yield return start;
         start += sign;
    }
}

public static IEnumerable<int> Range(this int start,int count)
{
    return Enumerable.Range(start,end);
}
```

The usage will make code more compact and easier to write

```C#
foreach(var i in 1.To(100))
     Console.WriteLine(i);

foreach(var i in 1.Range(99))
     Console.WriteLine(i);
```

Second. I would like to suggest that, most of `Math` and `DateTime` should move into `System.Numerics` as an extension method to number itself

for example

```C#
namespace System.Numerics;

public static double Pow(this double value,double power)
{
    return Math.Pow(value,power);
}

public static float Pow(this float value,float pow)
{
    return (float)Math.Pow(value,power);
}

public static TimeSpan AsMilliseconds(this long millisec)
{
    return DateTime.FromMilliseconds(millisec);
}
public static TimeSpan AsMilliseconds(this double millisec)
{
    return DateTime.FromMilliseconds(millisec);
}
```

Same as above

```C#
var sqrt2 = 2f.Pow(0.5f);

var timeSpan = 1000L.AsMilliseconds();
```

Both of these proposal should be contained in namespace. So it would be hidden unless explicit using, would not hamper in normal life

**Comment by tannergooding** [comment]
Going to close this as it hasn't gotten much traction and I would agree that it does not mesh well with the rest of the BCL.
