### ISSUE TITLE
Microsoft.Private.CoreFx.Uap builds on non-Windows platforms

### ISSUE THREAD

**Issue by chcosta** [dotnet/runtime#20495]
If you're running on Linux and you build with "-BuildAllConfigurations=true", it will attempt to build the Microsoft.Private.CoreFx.UAP package.  

We need some way to build all OS-applicable packages on Linux so that we can produce Microsoft.NETCore.Platforms.  

As a temporary work-around, we will just explicitly build the Platforms package, but I think the real fix is as simple as adding "-Windows_NT" to build BuildConfigurations in https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Private.CoreFx.UAP/Configurations.props

@ericstj @weshaggard @ellismg

**Comment by ViktorHofer** [comment]
We don't produce that package anymore. Closing.
