### ISSUE TITLE
API Proposal: Ceil, Floor for Vector<T>

### ISSUE THREAD

**Issue by mjmckp** [dotnet/runtime#20509]
This is a proposal of the ideas discussed in issue dotnet/runtime#20147.

There are a few SIMD operations on `System.Numerics.Vector<T>` missing that are required to implement vectorized versions of `log`, `exp`, `sin`, and `cos`.

There is a C implementation of these methods using AVX intrinsics [here](http://software-lisc.fbk.eu/avx_mathfun/), which I have translated into a C# implemention using `Vector<T>` [here](https://github.com/mjmckp/VectorMathFuns).   In the implementation, I have added fake versions of the missing intrinsics.

@mellinoe suggested creating two separate issues for the missing methods (the other issue is dotnet/corefx#16835), so the purpose of this issue is to propose the addition of the following methods:

[Updated proposal with comments below]
```C#
namespace System.Numerics
{
    public static class Vector
    {
        public static Vector<float> Floor(Vector<float> value);
        public static Vector<double> Floor(Vector<double> value);
        public static Vector<float> Ceiling(Vector<float> value);
        public static Vector<double> Ceiling(Vector<double> value);
    }
}
```

which map directly to the following AVX intrinsics:
```
_mm256_floor_ps
_mm256_floor_pd
_mm256_ceil_ps
_mm256_ceil_pd
```
respectively.

**Comment by Gnbrkm41** [comment]
Should this throw for any non-floating point types, like `int`/`short`/etc? it really doesn't make to ceil/floor those data types because they are integral types.

**Comment by tannergooding** [comment]
> Should this throw for any non-floating point types, like int/short/etc? it really doesn't make to ceil/floor those data types because they are integral types.

@Gnbrkm41, The proposed and approved API surface is only for `float`/`double`, so we shouldn't need to consider the integral types.

**Comment by tannergooding** [comment]
Resolved in https://github.com/dotnet/runtime/pull/31993
