### ISSUE TITLE
.NET Core SDK 3.1 is blocked by macOS Catalina 10.15 because it cant be validated

### ISSUE THREAD

**Issue by Jay-Madden** [dotnet/runtime#2051]
**System Version:**	macOS 10.15 (19A583)

This block can be overridden in settings and the installation will proceed normally however.
<img width="443" alt="Screen Shot 2020-01-22 at 7 46 02 PM" src="https://user-images.githubusercontent.com/25359755/72947581-70f4f080-3d50-11ea-8277-55a99895569a.png">

**Comment by wfurt** [comment]
cc: @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
Thanks for reporting this @Jay-Madden.  We are working on a plan to release notarized packages in an update that should be shipping soon.  In the meantime you can still install, but you have to do the following (only temporary):
•	Download via curl (the url is on the download page):
curl -o ~/Downloads/dotnet-sdk.pkg https://download.visualstudio.microsoft.com/download/pr/787e81f1-f0da-4e3b-a989-8a199132ed8c/61a8dba81fbf2b3d533562d7b96443ec/dotnet-sdk-3.1.100-osx-x64.pkg
•	Install directly:
sudo installer -pkg ~/Downloads/dotnet-sdk.pkg -target /

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing since notarized packages were released.
