### ISSUE TITLE
Proposal: Convenience API for throwing exceptions

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#20604]
## Background

It's quite verbose to validate arguments because you have to write an if-statement and `throw new XXXException` for each validation. Even with C# 7's new throw-expressions, you still have to write out the latter part. This makes people write their own helper classes for validating arguments, e.g. [here](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/Validation/Requires.cs) or [here](https://github.com/xunit/xunit/blob/master/src/common/Guard.cs). It would be nice if we had such a helper class as part of the framework.

## Proposal

```cs
namespace System
{
    public static class Verify
    {
        public static void Argument(bool condition, string message, string argumentName);

        public static void InRange(bool condition, string argumentName);
        public static void InRange(string s, int index, int count, string sName, string indexName, string countName);
        public static void InRange<T>(T[] array, int index, int count, string arrayName, string indexName, string countName);

        public static void NotEmpty<T>(IEnumerable<T> source, string sourceName);

        public static void NotNegative(int argument, string argumentName);

        public static void NotNull(bool condition, string argumentName);
        public static void NotNull<T>(T argument, string argumentName) where T : class;

        public static void Positive(int argument, string argumentName);
    }
}

// Sample usage:
T MyGenericMethod<T>(T[] array, int index, int count)
{
    // Note: All of this is equivalent to Verify.InRange(array, index, count, nameof(array), nameof(index), nameof(count)).
    // The arguments are validated manually for demo purposes.
    Verify.NotNull(array, nameof(array));
    Verify.NotNegative(index, nameof(index));
    Verify.NotNegative(count, nameof(count));
    Verify.InRange(array.Length - index >= count, nameof(index));
}
```

A sample implementation [can be found here](https://gist.github.com/jamesqo/13dded2757a8f9f9eb57bbaf944dee1b#file-verify-cs-L79).

## Remarks

- In my experience, it's common to validate things like a signed integer being positive/nonnegative, so those patterns will get their own `Positive` / `NotNegative` methods. This will enable us to [provide a better error message](https://gist.github.com/jamesqo/13dded2757a8f9f9eb57bbaf944dee1b#file-verify-cs-L79) if such a check fails. These methods throw the same exception type as `InRange`.
  - Same applies for `InRange`, `NotEmpty`

- The class will work nicely with `using static`:

```cs
using static System.Verify;

T MyGenericMethod<T>(T[] array, int index, int count)
{
    NotNull(array, nameof(array));
    NotNegative(index, nameof(index));
    NotNegative(count, nameof(count));
    InRange(array.Length - index >= count, nameof(index));
}
```

- The extra `NotNull` overload taking a `bool` covers the rare cases when people are writing generic code, and the parameter might be null but the compiler can't guarantee that it's a class. e.g. [Like here](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableDictionary.cs#L300). It also covers the rare times when someone would want to verify a nullable is non-null.
  - I didn't include a `NotNull<T>(T?, string) where T : struct` nullable overload since if someone thinks a nullable is non-null they would likely 1) not accept a nullable parameter in the first place, or 2) if they're calling some method they know returns a non-null nullable, they're likely to cast the `T?` to a `T` or call `.Value`, which do the validation automatically, instead of bothering to validate themselves.

---

This is a follow-up to https://github.com/dotnet/corefx/issues/12509 after putting some thought into the API.

**Comment by olivier-spinelli** [comment]
Seems that the focus here is on arguments. However there's also InvalidOperationExceptions that are also somehow "sent" to the caller of the method.
```csharp
public bool CanRun => ...;

public void Run()
{
   if( !CanRun ) throw new InvalidOperationException( nameof(CanRun) );
   ...
}
```
This is "State" rather than "Argument" (there is no argument at all). And one can add another "group" that turns around the InvalidDataException (that is not Argument, nor directly State but external data that must participate to the process AND must be valid by design).
(This is just my 2 cents: this Argument/State/Data distinction is often a good guide for me.)

Whatever helpers exist they ideally should be able to work on (at least) these 3 fundamental aspects.

**Comment by huoyaoyuan** [comment]
We are now having throw helpers in the exception classes: #58047 #62628 #69590 #77749

I believe this can be closed and follow the latest designs.
