### ISSUE TITLE
Add all remaining IEEE754 float types (binary16, binary128, decimal32, decimal64, decimal128), BigDecimal and BigRational to System.Numerics

### ISSUE THREAD

**Issue by Happypig375** [dotnet/runtime#20681]
While BigInteger is useful for really big integers, it cannot represent really big decimals.

BigRational would be useful in fractional operations (think of 1/3) while BigDecimal could represent something like the square root of 23E-234.

BigDecimal could be straight forked from the J# library source (which Microsoft should have) and BigRational could also be straight forked from [another pile of Microsoft code](https://github.com/microsoftarchive/bcl/blob/master/Libraries/BigRational/BigRationalLibrary/BigRational.cs) so it is easy to implement.

I would like to see these two get added :)

[Also from @tannergooding:](https://github.com/dotnet/runtime/issues/20681#issuecomment-288430429)
>I think completing out the five basic formats from IEEE spec would be desirable. That is:
>- binary32
>- binary64
>- binary128
>- decimal64
>- decimal128

>It also directly defines:
>- binary16 
>    - Several graphics formats use it today and it is available in some graphics hardware.
>    - The x86 F16C instruction set also provides hardware support for converting between single and half-precision.
>- decimal32

>It also sets a 'precedent' for a BigRational and BigDecimal format:
>>This standard defines binary interchange formats of widths 16, 32, 64, and 128 bits, and in general for any multiple of 32 bits of at least 128 bits. Decimal interchange formats are defined for any multiple of 32 bits of at least 32 bits.

**Comment by erjicles** [comment]
Just my 2 cents - I think BigRational (based on BigInteger) should be (re)added to this list. Arbitrary-precision rational numbers would be very useful in many applications, and after much sleuthing around the internet, it seems that a lot of people wind up having to roll their own half baked versions of it because it's not provided as managed code anywhere. 

Also, it seems it was scratched from this thread because it was tracked [here](https://github.com/dotnet/runtime/issues/14853), but that thread has been closed for a long time, and I want to keep it on your radar.

**Comment by danielwcarey** [comment]
Here is an implementation that I find quite useful.
https://github.com/tompazourek/Rationals

**Comment by Happypig375** [comment]
@erjicles Re-included `BigRational` :)

**Comment by tannergooding** [comment]
I'm going to close this issue as it will be unactionable for the purposes of the [API review process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

If someone feels strongly about a particular type, they should feel free to open a new issue following the layout of the "good example" given under step 1 of the review process linked above. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections. You can also see the proposal for `Half` (binary16) here: https://github.com/dotnet/runtime/issues/936
