### ISSUE TITLE
A few exception strings aren't pulled from resources

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#20758]
Almost all our resource strings are for exceptions and it looks like >99% of our exceptions are indeed thrown with localized strings. About 68 aren't:

examples
```c#
 throw new InvalidOperationException("Attempted to pend a read when _failAsyncPends test hook was enabled");
```
```c#
throw new InvalidOperationException("Trying to start an Activity that was already started");
```

(hits in the CoreFX product sources for `throw new .*Exception\("[^ "]+ .*"`)

**Comment by Marusyk** [comment]
Seems it already fixed in https://github.com/dotnet/corefx/pull/40402

**Comment by weltkante** [comment]
There are still plenty left matching the regex from OP, but on a first glance none of them seems relevant for UI validation, so I'm not too worried about those

**Comment by Marusyk** [comment]
> There are still plenty left matching the regex from OP

@weltkante, where? There are only 14 results and all of them in `tt` files.

**Comment by weltkante** [comment]
Maybe I'm getting confused by the repo merge, I pulled `dotnet/runtime` and get 70 matches in 50 files when searching the `src\libraries` subtree. Am I doing something wrong?

**Comment by danmosemsft** [comment]
@Marusyk note that we now have a few new ones in Mono code: https://github.com/dotnet/runtime/issues/34056

I have a PR up for a handful but no plans to do more, so if you're motivated that would be welcome!

You may possibly be also interested in this one: https://github.com/dotnet/runtime/issues/33763#issuecomment-604123104

**Comment by Marusyk** [comment]
@weltkante sorry, my bad. You are right, there are a lot of matches

**Comment by danmosemsft** [comment]
@Marusyk missed your reply. Yup, assigned to you now. Thanks!

**Comment by ViktorHofer** [comment]
@Marusyk are you still working on this?

**Comment by Marusyk** [comment]
Oh, missed this task, sorry. Yes, I will try to prepare PR for this in a couple of days

**Comment by danmosemsft** [comment]
Closing - fixed by @Marusyk thanks!
