### ISSUE TITLE
Problems with desktop application Publish

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/runtime#2091]
I have a command-line Windows application that targets .NET Framework 4.7.2. It runs fine but now I need to provide the bits needed for it to run on my client's computer. I've never had the need to do this before.

It looks like there is a Publish command that does this. But it provides very few options and the resulting SETUP program is not working for me.

My client needs to run the app and provide it with command line arguments (from VBA). But he can't even find where it's installed. After installing it myself, I had trouble finding it too. It's added to the Start menu as a link to a Application Reference file, which contains the following content?

>file:///D:/Users/Jonathan/Desktop/Deploy/CsvToXml.application#CsvToXml.application, Culture=neutral, PublicKeyToken=cf1b20217ddbb1df, processorArchitecture=msil

I don't see how my client will be able to make use of this.

Is there any way to do a *normal* installation? Like to install it under Program Files and have a regular EXE file that I can refer to. Or, better yet, put all the needed files in a folder that he can just copy to his system? (I don't think it's a safe bet that he has the targeted version of .NET on his computer.)

**Comment by scalablecory** [comment]
This repo is for help with .NET Core. Requests for help with .NET Framework should be made over at the [MSDN Forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?category=netdevelopment).

You published you app as a ClickOnce deployment. These are installed into the User's folder under an obscure directory involving GUIDs.

**Comment by SoftCircuits** [comment]
> You published you app as a ClickOnce deployment. These are installed into the User's folder under an obscure directory involving GUIDs.

Right, which doesn't work. I'm trying to find out if Visual Studio has options that might work in my case. I've posted online elsewhere but apparently no one else knows the answer either so far.

**Comment by jkotas** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/deployment/ lists the different option for deploying .NET Framework applications.

**Comment by SoftCircuits** [comment]
> https://docs.microsoft.com/en-us/dotnet/framework/deployment/ lists the different option for deploying .NET Framework applications.

So is there any interest in feedback that these options don't cover a basic scenario?

**Comment by jkotas** [comment]
Yes. You can leave feedback by clicking you Feedback button at the top of the docs page.

I believe all that the options described on the docs do cover the basic scenarios. It is not just described well.
