### ISSUE TITLE
Update/replace System.Threading.Tasks.Dataflow internal ConcurrentQueue with Concurrent.Collections changes

### ISSUE THREAD

**Issue by nietras** [dotnet/runtime#20915]
Apparently, DataFlow has it's own copy of `ConcurrentQueue`, but this does not seem to have been updated with the great optimizations that @stephentoub did to the Concurrent.Collections version see:

https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Dataflow/src/Internal/ConcurrentQueue.cs

Either update this with the changes or use Concurrent.Collections.

**Comment by stephentoub** [comment]
Thank you for the suggestion.  I'm going to close this.  If we end up removing the old netstandard build, then we'll remove the private queue implementation at the same time, as it'll then be dead code.  If we don't, it's not worth the churn to try to consolidate to the single implementation used in corelib.
