### ISSUE TITLE
Add RIPEMD160 to System.Security.Cryptography.Algorithms

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#2094]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/891132/add-ripemd160-to-systemsecuritycryptographyalgorit.html)._

---
<p>In .NET Core, RIPEMD160 hashing algorithm was dropped from the System.Security.Cryptography.Algorithms package. Please add an implementation for it, just like the one we have in .NET Framework.</p>

---
#### Fiona Niu[MSFT] on 1/22/2020, 00:44 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by bartonjs** [comment]
RIPEMD160 is not an algorithm that is provided by the OS crypto layers, and .NET Core no longer carries managed implementations of cryptographic algorithms.
