### ISSUE TITLE
Make `System.Runtime.InteropServices.SafeHeapHandle` Public

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#20990]
@SamuelEnglard commented on [Mon May 02 2016](https://github.com/dotnet/coreclr/issues/4730)

`System.Runtime.InteropServices.SafeHeapHandle` is a class that almost every developer who has used unmanaged memory has had to write. Having it built in would solve many issues and increase the odds of developers who don't know they needed it finding it.

cc: @terrajobst 

---

@terrajobst commented on [Tue May 03 2016](https://github.com/dotnet/coreclr/issues/4730#issuecomment-216668417)

@weshaggard @stephentoub @yizhang82

**Comment by stephentoub** [comment]
Thanks for the suggestion.  It's been years and there's been little interest in this.  There are also numerous APIs now for allocating/freeing memory, e.g. with the newer NativeMemory type.  If someone needs a safe handle for one of these APIs, it can be done in a few lines of code.  So, I'm going to close this.  Thanks.
