### ISSUE TITLE
InvalidOperationException from HttpHeaders.CheckHeaderName when _invalidHeaders contains the header

### ISSUE THREAD

**Issue by KuroThing** [dotnet/runtime#21000]
When using [`HttpHeaders.Contains`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L210) method, [this](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L1137) if statement will throw an `InvalidOperationException` when the header *does* exist it throws the exception which seems incorrect?

What is even more confusing is that there is a `TryCheckHeaderName` which will return a boolean instead of throwing an exception right below that method, which seems more appropriate for the `HttpHeaders.Contains` method.

Sorry if this isn't the place to report this, using the 'file a bug' links in the readme doesn't work for me.

**Comment by MihaZupan** [comment]
We added a `NonValidated` view over the header collection in #35126.
`headers.NonValidated.Contains` will not throw for invalid header names.

Closing this in favour of #61968
