### ISSUE TITLE
XML signing: no way to override default transforms

### ISSUE THREAD

**Issue by espenrl** [dotnet/runtime#2102]
In .NET Framework it was possible to override default transforms. In .NET Core it is not due to this line:

https://github.com/dotnet/runtime/blob/653cf01273242935f85290a131ccf7dc966e9d37/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs#L58

See code in [.NET Framework](https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/utils.cs,461).

This breaks our application as we need our own implementation of `XmlDsigXPathTransform`.

**Comment by danmosemsft** [comment]
@krwq

**Comment by krwq** [comment]
I think it might make sense to swap the order: `(CryptoConfig.CreateFromName(name) ?? CreateFromKnownName(name)) as T` or provide some way to override the default behavior (new API) - swapping might cause some perf hit but considering the signing and transformations are relatively slow anyway that shouldn't make significant difference (I think)

cc: @bartonjs

**Comment by bartonjs** [comment]
Perhaps.  I think we just did it because we needed the accelerator for the hash algorithms at one point, and then we added everything else there to avoid CryptoConfig... or we did it all when CryptoConfig didn't exist.

We might be able to just entirely remove the CreateFromKnownName method; or reduce it to the 4 items at the bottom.

**Comment by espenrl** [comment]
Sounds great! As a temporary fix I cloned `System.Security.Cryptography.Xml` and reordered the mentioned line to:

```
return (CryptoConfig.CreateFromName(name) ?? CreateFromKnownName(name)) as T;
```

We run it in production now, processing 2 million xml documents a day. Works like a charm.

**Comment by danmosemsft** [comment]
@espenrl glad to hear you're unblocked! Perhaps you'd like to offer a PR?

**Comment by espenrl** [comment]
@danmosemsft  I've done a PR with the same change I did on the cloned code.
