### ISSUE TITLE
BitConverter.ToDouble is much slower than calling ReadInt64LittleEndian and Int64BitsToDouble

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#2106]
Given this simple benchmark:

```C#
    public class Program
    {
        private static byte[] _buffer = new byte[8];

        static void Main(string[] args)
        {
            BitConverter.TryWriteBytes(_buffer, 8.125);
            BenchmarkRunner.Run<Program>();
        }

        [Benchmark]
        public double ToDouble() => BitConverter.ToDouble(_buffer);

        [Benchmark]
        public void ReadInt64LittleEndianInt64BitsToDouble() => 
            BitConverter.Int64BitsToDouble(BinaryPrimitives.ReadInt64LittleEndian(_buffer));
    }
```

I get results:

```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.100
  [Host]     : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT
  DefaultJob : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT
```

|                                 Method |      Mean |     Error |    StdDev |
|--------------------------------------- |----------:|----------:|----------:|
|                               ToDouble | 1.7844 ns | 0.0790 ns | 0.0941 ns |
| ReadInt64LittleEndianInt64BitsToDouble | 0.2727 ns | 0.0115 ns | 0.0108 ns |

Looking at the resulting [x86 assembly](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCEBXAMy5il3YBLAHbYoATwDcNGsQDMTUgwDCDAN40GWpgoAmEDsAA2MBgFkAFAEp1m7fYDKAB2zCAPMHEYYAPgbBuXigGAF4GXAxsMABrbCMjCDB/LxgAbQAOAF1pant7YgB2BjZBDGUIYQA3Pm8oFgBJYQxUEoxcABUIABEDYxgLEtEJAAUoQXxSwWqBACUYbF1G5pQAGVKMEwBRYV1BVwsAnj4rKxy7LQBfc4Zr+QZ9QxNzUmtbXLytZ1cPFL9DoNC4UiMTiCSSnm8GWy13yRVa5SqNT4LE6PUe/X+xzO70uNAuQA=), my assumption is that most of this slow down is caused by `BitConverter.ToDouble` not having an `[MethodImpl(MethodImplOptions.AggressiveInlining)]` attribute on it.

Should we add the aggressive inline attribute to `BitConverter.ToDouble` and similar functions?

/cc @tannergooding

**Comment by GrabYourPitchforks** [comment]
Strange, you would think the method would be small enough to be inlined. Is the JIT seeing the two call instructions `Unsafe.As` and `MemoryMarshal.GetReference` and pessimistically marking the method not an inlining candidate?

**Comment by AndyAyersMS** [comment]
The method is a bit too large to "always inline" --  there are 4 calls --  so it gets evaluated by the heuristics. 
```
.method public hidebysig static float64  ToDouble(valuetype System.ReadOnlySpan`1<uint8> 'value') cil managed
{
  .custom instance void System.Runtime.CompilerServices.NullableContextAttribute::.ctor(uint8) = ( 01 00 00 00 00 ) 
  // Code size       28 (0x1c)
  .maxstack  8
  IL_0000:  ldarga.s   'value'
  IL_0002:  call       instance int32 valuetype System.ReadOnlySpan`1<uint8>::get_Length()
  IL_0007:  ldc.i4.8
  IL_0008:  bge.s      IL_0010
  IL_000a:  ldc.i4.7
  IL_000b:  call       void System.ThrowHelper::ThrowArgumentOutOfRangeException(valuetype System.ExceptionArgument)
  IL_0010:  ldarg.0
  IL_0011:  call       !!0& System.Runtime.InteropServices.MemoryMarshal::GetReference<uint8>(valuetype System.ReadOnlySpan`1<!!0>)
  IL_0016:  call       !!0 Internal.Runtime.CompilerServices.Unsafe::ReadUnaligned<float64>(uint8&)
  IL_001b:  ret
} // end of method BitConverter::ToDouble
```
The currently heuristics actually likely overestimate the benefit of inlining in the current model (this is neither a wrapper nor has an arg that feeds a constant test), but they still come up short:
```
Inline candidate looks like a wrapper method.  Multiplier increased to 1.
Inline candidate has an arg that feeds a constant test.  Multiplier increased to 2.
Inline candidate callsite is boring.  Multiplier increased to 3.3.
calleeNativeSizeEstimate=540
callsiteNativeSizeEstimate=105
benefit multiplier=3.3
threshold=346
Native estimate for function size exceeds threshold for inlining 54 > 34.6 (multiplier = 3.3)
```
This case is running into known limitations of the current model; it does the analysis above without resolving any of the tokens in the callee, so has no way of knowing that some of those calls will optimize down to very little code.

So adding `AggressiveInlining` seems reasonable.

**Comment by tannergooding** [comment]
Thanks for the insight!

I'm going to mark this as up-for-grabs as its a small fix to add the `AggressiveInlining` here.
