### ISSUE TITLE
API Proposal: StructuralComparer<T>

### ISSUE THREAD

**Issue by kzu** [dotnet/runtime#21123]
Currently there is no built-in comparer that can be used with a `HashSet<T>` or the [ToImmutableHashSet<T>](https://docs.microsoft.com/en-us/dotnet/api/System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet--1?view=netcore-1.1.0#System_Collections_Immutable_ImmutableHashSet_ToImmutableHashSet__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEqualityComparer___0__). 

Just like `Comparer<T>` provides a convenient `Default`, it would be great to also provide such a structural comparer, which is basically:

```c#
    public class StructuralComparer<T> : IEqualityComparer<T>
    {
        public static IEqualityComparer<T> Default { get; } = new StructuralComparer<T>();

        public bool Equals(T x, T y) => StructuralComparisons.StructuralEqualityComparer.Equals(x, y);

        public int GetHashCode(T obj) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(obj);
    }
```

I'm using the above when working with Roslyn's `ImmutableArray<T>` and `ImmutableHashSet<T>` and it is quite convenient.

**Comment by malaterre** [comment]
Just FYI, should be more like:

```
    public class StructuralComparer<T> : IEqualityComparer<T> where T : IStructuralEquatable
    {
        public static IEqualityComparer<T> Default { get; } = new StructuralComparer<T>();

        public bool Equals([AllowNull] T? x, [AllowNull] T? y) => StructuralComparisons.StructuralEqualityComparer.Equals(x, y);

        public int GetHashCode([DisallowNull] T obj) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(obj);
    }

```

**Comment by eiriktsarpalis** [comment]
It seems like this is proposing adapter from `IEqualityComparer` to `IEqualityComparer<T>`. Why not just offer that and specifically wrap the `StructuralEqualityComparer`?

If I'm honest I don't think we should be including this in the BCL. It's a fairly straightforward adapter to write if needed.
