### ISSUE TITLE
[Uri] System.Uri decoding automatically and incorrectly

### ISSUE THREAD

**Issue by MikeKenyon** [dotnet/runtime#2113]
Consider the following block:

```c#
var uri = new Uri($"https://sample.com/api/go?o=Presentation%20of%20%E2%80%9CGreen%E2%80%9D%20data");
var original = uri.OriginalString;
var modified = uri.ToString();
```

The URL contains contents that are not necessarily valid ASCII characters.  In this regard, the modified version of the string shows the content there decoded, while the original (as provided) contains encoded versions of those.

This is important because a number of uses for a URL require them to comply to with, [HTTP Headers](https://tools.ietf.org/html/rfc7230#section-3.2.4) for example.  The URI provided was valid as a header.  The URL returned does not.    This comes up when say doing a redirect to it.

This can be avoided by using a String to represent the URL location, but that's generally considered a bad practice and anti-pattern.  

It would be amazing if we could indicate somehow that while the decoding that gets performed automatically is to be used in such a way that any encoding provided should not be undone.

I'm thinking a constructor parameter or property.

**Comment by wfurt** [comment]
cc: @MihaZupan

**Comment by MihaZupan** [comment]
I don't see what the problem here is.

`OriginalString` returns the original string you passed to the ctor as the name suggests and ToString returns a different one as is documented.

See [`Uri.ToString`](https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring):
> A String instance that contains the unescaped canonical representation of the Uri instance. All characters are unescaped except #, ?, and %.

> The following example creates a new Uri instance from a string. It illustrates the difference between the value returned from OriginalString, which returns the string that was passed to the constructor, and from a call to ToString, which returns the canonical form of the string.

You probably want to be using `Uri.AbsoluteUri`.

**Comment by MikeKenyon** [comment]
Let's take the case in point.  I have an API that's going to store and retreive a URI.  That URI is going to get used for a referrer header on a later HTTP request.  

1. If I write the store API to take a URI, it will automatically strip the callers good works in encoding.  

2. Requiring the storer to encode it for the specific use of being used in a header requires the caller to be prescient of what's going to be done with it by other parties.

3. Even if I store it properly, there's no way to write the API to return a URI without it striping the encoding.

4.  That still requires the service to know what the caller intends to do with it.

If URI is not intended to be used in API definitions, then what is the point of having it?  You could always use a string.  URI provides a way to denote the intent of content passed across that boundary.

- ceding you could right custom middleware maybe to have the URI return the OriginalString rather than the default interpretation.  That seems imposing.

**Comment by MihaZupan** [comment]
I think that the problem here is misunderstanding the use-case of ToString. If you want to keep the encoding, you **should not** use ToString, but `AbsoluteUri`.

**Comment by MikeKenyon** [comment]
Okay, if I make say a WebApi method that returns a URI, how do I tell the framework that it should preserve the encoding because both versions aren't shipped over the wire?

**Comment by MihaZupan** [comment]
Are you asking about a scenario like this (method in an api controller)? Otherwise if you can provide a short example of what you mean.

```c#
[HttpGet]
public async Task<Uri / string> GetRedirectUri(string someUserInput)
{
    // Stuff here
}
```

**Comment by MikeKenyon** [comment]
Yes.  As an example.  Though any case where you are using the URI type on an API definition it's an issue, but vastly more so when it's serialized.

In the example given:

You two options here are take and return string ... Defeating the purpose of having a URI type. 

Or you can take and return a URL and th URL being passed will not be appropriate for some purposes. 

In general:
If I have you a System.Uri how do you know which representation you should use - OriginalString or ToString().  Both are hazardous assumptions depending on what the original string passed in was and what your intended usage for that string is.

**Comment by MihaZupan** [comment]
> If I have you a System.Uri how do you know which representation you should use - OriginalString or ToString(). Both are hazardous assumptions depending on what the original string passed in was and what your intended usage for that string is.

Use `OriginalString` whenever you want to know the originally used string. For example, Json.Net will use this value, so if you want the Json representation to be in escaped form, you have to use an escaped representation when constructing the Uri.
If the string that was originally used was not escaped, `OriginalString` obviously won't be either.

If for whatever reason, you wish to look at the unescaped representation (including spaces), use `ToString`. If you always want to use the escaped representation (which is what I am getting from your answers), you should NOT use `ToString` - ever.

When converting full URLs (https://foo.bar/...) to a string, use the `AbsoluteUri` property.

In the example above, if your intent is to return Json-serialized URIs that are in escaped form, you can do so by constructing the URI in escaped representation initially
```c#
[HttpGet]
public Uri GetRedirectUri(string someUserInput)
{
    return new Uri("https://sample.com/api/go?o=" + Uri.EscapeDataString(someUserInput));
}
```

**Comment by MikeKenyon** [comment]
`OriginalString` requires three things that you don't always have.  

1. Foreknowledge that some person who may use this URL months or years from now needs it encoded in this particular fashion.
2. Knowledge that the Uri that a random Uri that you've been handed which was created by someone other than  you was encoded in a particular fashion that would make `OriginalString` useful and the default not.
3. The Uri must never have passed through a serialization boundary because if it did the `OriginalString` is gone.  Vamoose.  No longer present. 

Your examples revolve around a single individual being the sole producer and consumer of a Uri and that individual knowing exactly how it's to be used.  I completely grant that if you claim all roles in the system this is not necessary.   That caveat is not reasonable for even a medium-sized company and certainly not for any open-source project or public API that may have a URI on it's boundary.

There are over a thousand developers at my company and 100 on my project.  When I take a Uri as input, the person giving it to me may not know how it will be used.  When I return a Uri it may be used by a dozen different consumers many of whom will not exist at the time that I'm writing my interface who will use that Uri in ways I had never intended.   It is not a reasonable assumption that the person who gave me a Uri knew that it'd be put into a header by a different application that didn't exist at the time they provided that string.   Its not a reasonable assumption for the person who's taking a Uri to assume that the person receiving it knows that it contains a high-order content and needs to use OriginalString instead of ToString() where ToString() is the correct choice 99% of the time.  

Most importantly, the whole point of having a Uri type that has instances rather than a static class is that the Uri can be put in an interface to indicate that you take or return a Uri to indicate what is being returned or taken from a method to an extent that a string cannot.  Compare with Math in that regard.  Because Uri universally only serializes the altered content in every serialization mechanism I'm aware of, the sample provided above would immediately lose the original string if you sent it over REST or gRPC or SOAP an even if you caught it with a Uri on the client-side it would have lost the information necessary to use that as a workable solution.

**Comment by MihaZupan** [comment]
> The Uri must never have passed through a serialization boundary because if it did the `OriginalString` is gone.  Vamoose.  No longer present. 

You have to decide. Do you care about the original representation or do you care about the functional aspects of the Uri.
By comparrison, do you care whether a number 3 was originally "2 + 1", "0b11" or "iii" or do you only care about the value.


The way I read your comment is that you can't make assumptions about all producers/consumers of Uris. Completely reasonable.
The solution is to **not make assumptions - don't use OriginalString.** As the name suggests, if you use OriginalString, you are either interested in the exact form of the original or you are making assumptions. If you don't have the guarantees that the original string was in the form you require - don't use OriginalString. That means, unless you are creating the Uri yourself from known-good input, don't use OriginalString. I never recommended you do.



You can pass a Uri around in your api contract freely. When you are consuming a Uri you are expected to know what you want to do with it. If you did not create it yourself, don't make assumptions about what form it was originally in.
**OriginalString and ToString are not the only APIs Uri offers**. If you are writing it to header fields, you should use the encoding that headers expect. That means you should **not** use OriginalString or ToString. You can use other Uri APIs to extract sections of the Uri in the forms you require (Scheme, IdnHost, AbsoluteUri, GetComponents ...). Using those properties/methods makes no assumptions about whether/to what extent the original input was escaped, using OriginalString does.

> Because Uri universally only serializes the altered content in every serialization mechanism I'm aware of, the sample provided above would immediately lose the original string if you sent it over REST or gRPC or SOAP an even if you caught it with a Uri on the client-side it would have lost the information necessary to use that as a workable solution.

The purpose of serialization formats is to allow for unambiguous round-tripping during serialization/deserialization. If you are sending a Uri, they will assure that when you reconstruct it you are getting a functionally equivalent Uri. It doesn't lose information that changes the Uri.

If all you care about is the exact representation that was used originally, use OriginalString and not Uri.

Like the analogy above, if you get a number 3 from some json, you can't tell whether that was originally represented as "2 + 1", "0b11" or roman "III". If you care about that information and not the actual value, you shouldn't have used a number, but a string.

**Comment by karelz** [comment]
It is answered, closing.
