### ISSUE TITLE
Regex Bug

### ISSUE THREAD

**Issue by peni4142** [dotnet/runtime#2114]
Hi guys,
I have a test for you

[x] Bug Report

The following regex test will return an empty string in the group[0], which in my opinion can't be true.

```C#
        [TestMethod()]
        public void BugTest()
        {
            Match matchEnsureObject = new Regex("^\\[MERGE-CMD: ENSURE OBJECT\\(([^)]+)\\)\\]$").Match("[MERGE-CMD: ENSURE OBJECT(aLong) AT 1]");
            if(matchEnsureObject.Groups[0].Value == "")
            {
                throw new Exception("Match can't be an empty value");
            }
        }
```

**Comment by danmosemsft** [comment]
@peni4142 I do not reproduce this in 3.1.

		Match matchEnsureObject = new Regex("^\\[MERGE-CMD: ENSURE OBJECT\\(([^)]+)\\)\\]$").Match("[MERGE-CMD: ENSURE OBJECT(aLong) AT 1]");
		if (matchEnsureObject.Success)
		{
			Console.WriteLine("match: `" + matchEnsureObject.Groups[0].Value + "`");
			if (matchEnsureObject.Groups[0].Value == "")
			{
				Console.WriteLine(matchEnsureObject.Groups[0].Value);
				throw new Exception("Match can't be an empty value");
			}
		}
```
match success is false, but if I make it match: `Match matchEnsureObject = new Regex(@"^\[MERGE-CMD: ENSURE OBJECT\(([^)]+)\)\]$").Match("[MERGE-CMD: ENSURE OBJECT(aLong) AT 1]");` then success is true and the match has a proper value.
