### ISSUE TITLE
System.Management.ManagementException fails to serialize

### ISSUE THREAD

**Issue by danlyons-softek** [dotnet/runtime#2116]
ManagementException is currently decorated with SerializableAttribute.  However, it contains a ManagementBaseObject field, and the ManagementBaseObject class is not currently decorated with SerializableAttribute.  As a consequence, attempts to serialize ManagementException fail:

```System.Runtime.Serialization.SerializationException: Type 'System.Management.ManagementBaseObject' in Assembly 'System.Management, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.```

**Comment by danmosemsft** [comment]
Thanks for pointing this out, @danlyons-softek . Did you just happen to notice or do you need it to be serializable? We do not want to make ManagementBaseObject serializable. We would take a change to either add `[NonSerializable]` to this `ErrorInformation` field (the error code would still serialize), or alternatively to remove `[Serializable]` from `ManagementException` itself -- clearly it won't break anyone as it doesn't work.

**Comment by danlyons-softek** [comment]
My project has some legacy remoting components that I have been porting to .NET Core, and the remote end of one of them was performing WMI calls to interact with the Windows DNS service.

It had been passing the ManagementException through the remoting boundary, likely because it was convenient to do so, as both objects appear to be serializable in .NET Framework (based on referencesource [ManagementException](https://referencesource.microsoft.com/#System.Management/managementexception.cs,589) and [ManagementBaseObject](https://referencesource.microsoft.com/#System.Management/managementbaseobject.cs,178)).

The replacement used for the remoting code still uses serialization via BinaryFormatter so we didn't have to convert all our data objects to use something else (e.g., protobuf, data contracts, etc.) right away.  This was one of a handful of objects that stopped stopped serializing, but it was a little surprising to see that it still had a SerializableAttribute yet failed to serialize.

For my immediate purposes, I'll transfer the error information some other way, but I thought it useful to bring attention to the issue.

**Comment by GrabYourPitchforks** [comment]
I think the easiest thing to do would be Dan's suggestion of annotating the field with `[NonSerializable]` in the Core implementation. From looking at the `ManagementBaseObject` type it's pretty clear that the type itself isn't meant to be serializable, and third parties are not expected to create serializable subclasses.

**Comment by danmosemsft** [comment]
@danlyons-softek any interest in offering a PR for this? I assume not since you've worked around it, but you'd be welcome.

**Comment by fagnercarvalho** [comment]
Hey @danmosemsft, can I work on this one? I would add a `[NonSerializable]` attribute into the `ErrorInformation` property in the `ManagementException` class.

**Comment by danmosemsft** [comment]
Sure!
