### ISSUE TITLE
Static method Mutex.TryOpenExisting(String, MutexRights, Mutex) is not available in .NET Core

### ISSUE THREAD

**Issue by gomathip02** [dotnet/runtime#2117]
@edward-a commented on [Wed Jan 22 2020](https://github.com/dotnet/wpf/issues/2473)

We weren't able to migrate our WPF app to .NET Core 3.1 because MutexRights wasn't available. Hope it gets implemented soon.

Unsupported (per Portability Analyzer): 
M:System.Threading.Mutex.TryOpenExisting(System.String,System.Security.AccessControl.MutexRights,System.Threading.Mutex@)

---

@weltkante commented on [Thu Jan 23 2020](https://github.com/dotnet/wpf/issues/2473#issuecomment-577573285)

This requests is not WPF-specific and probably belongs to corefx (now in the [dotnet/runtime](https://github.com/dotnet/runtime) repo)

That said as far as I can tell [`MutexRights`](https://source.dot.net/#System.Threading.AccessControl/System/Security/AccessControl/MutexSecurity.cs,32) still exists and is public. The `TryOpenExisting` method seems to have moved and the functionality now be covered by [`MutexAcl.Create`](https://source.dot.net/#System.Threading.AccessControl/System/Threading/MutexAcl.cs,22) or [`Mutex.OpenExisting`](https://source.dot.net/#System.Private.CoreLib/Mutex.cs,42) if you don't need the rights check and just want to open a cross process mutex.

---

@edward-a commented on [Thu Jan 23 2020](https://github.com/dotnet/wpf/issues/2473#issuecomment-577578434)

> 
> 
> This requests is not WPF-specific and probably belongs to corefx (now in the [dotnet/runtime](https://github.com/dotnet/runtime) repo)
> 
> That said as far as I can tell [`MutexRights`](https://source.dot.net/#System.Threading.AccessControl/System/Security/AccessControl/MutexSecurity.cs,32) still exists and is public. The `TryOpenExisting` method seems to have moved and the functionality now be covered by [`MutexAcl.Create`](https://source.dot.net/#System.Threading.AccessControl/System/Threading/MutexAcl.cs,22) or [`Mutex.OpenExisting`](https://source.dot.net/#System.Private.CoreLib/Mutex.cs,42) if you don't need the rights check and just want to open a cross process mutex.

I posted this feature request here because it was related to migrating WPF app to .NET Core. 

As for MutexRights, it's not there and we need to specify MutexRights.Synchronize.

**Comment by danmosemsft** [comment]
One of those @carlossanlop  did?

**Comment by danmosemsft** [comment]
Nope, it's not -- that added new CreateXXX methods as an alternative to the missing constructors on Mutex, Semaphore, EventWaitHandle, FileInfo, DirectoryInfo, FileSecurity, DirectorySecurity.

In this case we're missing OpenExisting and TryOpenExisting on Mutex, Semaphore and WaitHandle. I would have expected to see these implemented as extension methods in System.Threading.ThreadingAclExtensions, but they're not.

Seems to be just an oversight that can be remedied. All the necessary XXXRights types already exist. @carlossanlop do you see any issue?

```
MembersMustExist : Member 'System.Threading.Mutex.OpenExisting(System.String, System.Security.AccessControl.MutexRights)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Threading.Mutex.TryOpenExisting(System.String, System.Security.AccessControl.MutexRights, System.Threading.Mutex)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Threading.Semaphore.OpenExisting(System.String, System.Security.AccessControl.SemaphoreRights)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Threading.Semaphore.TryOpenExisting(System.String, System.Security.AccessControl.SemaphoreRights, System.Threading.Semaphore)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Threading.EventWaitHandle.OpenExisting(System.String, System.Security.AccessControl.EventWaitHandleRights)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Threading.EventWaitHandle.TryOpenExisting(System.String, System.Security.AccessControl.EventWaitHandleRights, System.Threading.EventWaitHandle)' does not exist in the implementation but it does exist in the contract.
```

**Comment by danmosemsft** [comment]
@edward-a MutexRights does exist, as @weltkante says. Not sure why you're not seeing it. But the method you want that accepts it does not exist. Is it possible for you to modify the code to use the TryOpenExisting overload that does not take MutexRights -- without reducing the security of your app?

Otherwise, your only near-term option is to achieve this with Pinvoke yourself. Create the mutex similar to how .NET Core does ie 
```c#
SafeWaitHandle myHandle = Interop.Kernel32.OpenMutex(AccessRights, false, name);
```
where 
```c#
        [DllImport(Libraries.Kernel32, EntryPoint = "OpenMutexW", SetLastError = true, CharSet = CharSet.Unicode)]
        internal static extern SafeWaitHandle OpenMutex(uint desiredAccess, bool inheritHandle, string name);
```
where `uint desiredAccess` is just your `MutexRights` cast to a `uint`. You should have `MutexRights`, but anyway, you can use your own value if you want.

Then you have the handle, and to create a regular `Mutex` object around it you do:
```c#
                Mutex mutex = new Mutex(initiallyOwned);
                SafeWaitHandle old = mutex.SafeWaitHandle;
                mutex.SafeWaitHandle = handle;
                old.Dispose();
```
This is exactly analogous to how @carlossanlop implemented Create:
https://source.dot.net/#System.Threading.AccessControl/System/Threading/MutexAcl.cs,22

**Comment by carlossanlop** [comment]
@danmosemsft  

They were not included in [the original API Proposal](https://github.com/dotnet/corefx/issues/41662).

@JeremyKuhne was it just oversight or was there a particular reason to avoid including them?

If Jeremy has no issue, I'd be happy to help prepare a new API Proposal for these methods.

Should we also consider backporting them?

**Comment by danmosemsft** [comment]
@carlossanlop yup, didn't mean to suggest it was _your_ oversight 😺 

Someone should probably add them but they seem easy to work around. Perhaps the community can contribute. @bartonjs do we need API review to add the exact same APi that exists in .NET Framework albeit as an extension method? I assume not...

**Comment by JeremyKuhne** [comment]
> @JeremyKuhne was it just oversight or was there a particular reason to avoid including them?

Oversight on my part.

**Comment by bartonjs** [comment]
> do we need API review to add the exact same APi that exists in .NET Framework albeit as an extension method?

@danmosemsft Yes. Especially if it's an extension method (we want to see what type/assembly/package it's going into).  If it was just a resurrection then it'd be a very fast nod, but we still do it so we're consistent that editing a ref.cs involved an API review.

**Comment by danmosemsft** [comment]
Ok @carlossanlop maybe a low pri task for you (@edward-a I suggest to work around as above)

**Comment by warrenlbrown** [comment]
As we try migrating to .Net Core 3.1 primarily to focus on Mac, it was an unexpected bump in the road to discover this problem, which also impacts named EventWaitHandle.OpenExisting(). Will this be patched for .Net Core 3.1?  Will it definitely be in .Net Core 5.0? Thank you.

**Comment by svick** [comment]
@warrenlbrown This issue is still open and the API hasn't even been reviewed. Since 5.0 already branched off of the master branch, I'd say the chances of this getting in are fairly low. And the chances for 3.1 are near zero, since already released versions don't get new APIs, only bugfixes.

**Comment by carlossanlop** [comment]
@warrenbrown did you try the suggested workaround @danmosemsft gave you [here](https://github.com/dotnet/runtime/issues/2117#issuecomment-577982767)?

**Comment by warrenlbrown** [comment]
I did not try the workaround, because we primarily need this for the Mac Core3.1 target. Many thanks for continuing to look into it for us.

**Comment by bartonjs** [comment]
> we primarily need this for the Mac Core3.1 target

Even if we create the method, I think it's just going to throw PlatformNotSupportedException on macOS... in general anything with rights/permissions/ACLs is Windows-only.

What are you wanting to do with it on macOS?

**Comment by carlossanlop** [comment]
@gomathip02 @edward-a @svick the APIs have been merged: https://github.com/dotnet/runtime/pull/43134
@warrenlbrown Note that these APIs are Windows-specific. If you need something for MacOS, let's discuss it in a new issue.
