### ISSUE TITLE
Review use of unreached() in the JIT

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#2120]
In the JIT, `unreached()` maps to a noway assert. This will cause the compile to be aborted and retried. When we are 1) in a phase that is run even under MinOpts, and 2) the situation has a reasonable fallback (e.g. for unsupported/unrecognized intrinsics I think the intrinsic recognizing methods should be returning `nullptr`) we should simply call `assert` with a reasonable message, and then take the appropriate fallback action.
See also comments on #1280.

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:medium

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
This makes sense. `unreached()` should only be used for things that can truly never happen and can't be recovered from (leading to unknown behavior). It sounds like unrecognized intrinsics is a case where there is a reasonable possibility of it happening in some circumstance (mismatched JIT/VM/library?), and there is a simple recovery that would work.

**Comment by tannergooding** [comment]
I'm working on updating the `hwintrinsic*` files to remove unnecessary `unreached` calls.
`simd*` is likely another easy one I could handle.

**Comment by BruceForstall** [comment]
Closing
