### ISSUE TITLE
Use RuntimeHelpers.GetHashCode instead of obj.GetHashCode

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#2128]
https://github.com/dotnet/runtime/blob/996e66882c41ee57a751de4433b976987366988b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReferenceEqualsEqualityComparer.cs#L24
Replace above line with the following to avoid misbehavior when comparing objects that use a bad implementation of `GetHashCode`
```
return RuntimeHelpers.GetHashCode(obj!);
```
Having a bad `GetHashCode` causes the Dictionary to always add an entry, even for objects that are identical.

Also update related tests.

**Comment by ntovas** [comment]
I would like to fix this, can you assign me?

**Comment by Marusyk** [comment]
@ntovas are you working on this?

**Comment by ahsonkhan** [comment]
@Marusyk - it's been a few days and I haven't heard back from @ntovas. Would you like to take this on?

**Comment by Marusyk** [comment]
yes, please

**Comment by ahsonkhan** [comment]
Go for it :)
