### ISSUE TITLE
Review related code to find potential infinitely recursive equality check bug

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#213]
Follow up on PR feedback [here](https://github.com/dotnet/runtime/pull/187#discussion_r349394709)

**Comment by bartonjs** [comment]
I'm not sure that an analyzer can even do a great job.  I think this just comes down to testing.

I'm closing this issue as not-very-actionable.  If someone has a good idea for analyzers to detect something like this, a new code-analyzer issue would be welcome.
