### ISSUE TITLE
Major CPU Usage difference (~7% vs ~30%) between Windows and linux

### ISSUE THREAD

**Issue by wegel** [dotnet/runtime#2130]
I'm playing with a toy bittorent leecher [here](https://github.com/wegel/SimpleTorrentLeecher), and noticed a major CPU usage difference between Windows and linux: about 7% vs 30% of 8 cores (or 56% vs 241%, or 0.56 core vs 2.41 cores), using the same hardware, Windows 10 and Ubuntu 18.04 running 5.3.0-26.

I'm having a real hard time diagnosing the problem, because the difference seems to come from the runtime itself. For example, running `dotnet-counters monitor` shows around 1-2% CPU usage while running in Windows (Task Manager shows ~7%), while `dotnet-counters monitor` in linux shows around 25-30% (top shows 170-220%). Both downloads at around ~10MBps.

I'm not sure what to look for, or is the CPU usage difference "normal" for dotnet core running on linux vs Windows, or am I doing something wrong?

You can try with [Ubuntu's torrent](http://releases.ubuntu.com/18.04/ubuntu-18.04.3-desktop-amd64.iso.torrent?_ga=2.142038704.325211861.1579841380-1348547383.1578635628):
`SimpleTorrentLeecher.Demo.exe ubuntu-18.04.3-desktop-amd64.iso.torrent 1gib`.

dotnet-counters sample from Windows:
```
[System.Runtime]
    # of Assemblies Loaded                            45
    % Time in GC (since last GC)                       0
    Allocation Rate (Bytes / sec)              2,091,544
    CPU Usage (%)                                      2
    Exceptions / sec                                   0
    GC Heap Size (MB)                                  6
    Gen 0 GC / sec                                    60
    Gen 0 Size (B)                             6,399,336
    Gen 1 GC / sec                                     0
    Gen 1 Size (B)                               276,336
    Gen 2 GC / sec                                     0
    Gen 2 Size (B)                             2,141,184
    LOH Size (B)                               2,014,720
    Monitor Lock Contention Count / sec               21
    Number of Active Timers                           44
    ThreadPool Completed Work Items / sec          6,695
    ThreadPool Queue Length                            0
    ThreadPool Threads Count                          19
    Working Set (MB)                                  48
```

dotnet-counters sample from linux:
```
[System.Runtime]
    # of Assemblies Loaded                            43    
    % Time in GC (since last GC)                       0    
    Allocation Rate (Bytes / sec)              1,165,408    
    CPU Usage (%)                                     31    
    Exceptions / sec                                   0    
    GC Heap Size (MB)                                  9    
    Gen 0 GC / sec                                     0    
    Gen 0 Size (B)                                91,960    
    Gen 1 GC / sec                                     0    
    Gen 1 Size (B)                               836,488    
    Gen 2 GC / sec                                     0    
    Gen 2 Size (B)                             2,618,528    
    LOH Size (B)                               2,014,720    
    Monitor Lock Contention Count / sec              222    
    Number of Active Timers                           29    
    ThreadPool Completed Work Items / sec          4,093    
    ThreadPool Queue Length                            0    
    ThreadPool Threads Count                           8    
    Working Set (MB)                                  63
```

**Comment by billwert** [comment]
What precise environment are you running in? What's the base OS? Are you using virtualization or rebooting to a different partition?

[This doc](https://github.com/dotnet/runtime/blob/master/docs/project/linux-performance-tracing.md) describes perf tracing on linux. [This doc](https://github.com/dotnet/runtime/blob/master/docs/project/performance-guidelines.md#profiling-and-performance-tracing) is for perf tracing on Windows. It would be super helpful if you could get representative traces of each scenario for analysis.

**Comment by scalablecory** [comment]
Related: https://github.com/dotnet/runtime/issues/1897

**Comment by wegel** [comment]
Sorry for the late reply.

Environments: different partitions on the same computer (Lenono P50, i7-6820HQ with 64Gb RAM); one Windows 10 Version 10.0.18362 Build 18362, one Ubuntu 18.04 running kernel 5.3.0-26. In theory the software isn't touching the disk so disk IO shouldn't matter. Used the same wired connection for both traces below.

linux trace: https://drive.google.com/open?id=1r0RyHDd83KXP-0hmqYGS3An6i51FNTOv
widnows trace: https://drive.google.com/open?id=1nGgzR0Hd_8jXAt-LcA0wcBKOrb8D7P0F
software archive: https://drive.google.com/open?id=1lq-QNb-Zw_VgjtBIfXlYsPU3lT__aiGP
torrent file: https://drive.google.com/open?id=1bP0EXPn9Q2myjj7MWoOwuByEgb6Q2l2H (or http://releases.ubuntu.com/18.04/ubuntu-18.04.3-desktop-amd64.iso.torrent?_ga=2.86768984.1379514654.1580856048-292732758.1579464964)

Software was run as: `dotnet SimpleTorrentLeecher.Demo.dll ubuntu-18.04.3-desktop-amd64.iso.torrent 512mb`

Please tell me if I can help with anything else, or if I did anything wrong with the traces; first time using those tools in both environment.

**Comment by wegel** [comment]
Is the difference in CPU usage normal between Windows and linux, or does it look like it's something that needs fixing in linux ?

**Comment by karelz** [comment]
Triage: Thanks for your report. We are aware of Linux vs. Windows perf differences and we have bunch of effort lined up in upcoming months to address that (e.g. io_uring exploration, etc.)
As this issue is not simply actionable (lots of custom code which may have its own perf bottlenecks), we recommend to close this issue for now. We will track perf micro-benchmarks instead. Once we are competitive on micro-benchmarks, we would recommend to remeasure your scenario and if there is still a difference, then the best next step would be to isolate the perf difference by minimizing the repro to avoid tracking down higher-level code inefficiencies (e.g. not ideal threading patterns, etc.).
