### ISSUE TITLE
SHA1.HashSize does not behave the same as in .NET Framework

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#2133]
Code:

```csharp
using System;
using System.Security.Cryptography;

public class CustomSHA1 : SHA1
{
    static void Main()
    {
        Console.WriteLine(new CustomSHA1().HashSize);
    }

    public CustomSHA1()
    {
    }

    public override void Initialize()
    {
        throw new NotImplementedException();
    }

    protected override void HashCore(byte[] array, int ibStart, int cbSize)
    {
        throw new NotImplementedException();
    }

    protected override byte[] HashFinal()
    {
        throw new NotImplementedException();
    }
}
```

On .NET Framework, this prints `160`. On .NET Core, it prints `0`. Of course, it's a fairly easy fix to just override `HashSize`, but this seems like an incompatibility that might need to be addressed. I'd imagine there's a good chance it affects other algorithms as well.

**Comment by wfurt** [comment]
cc: @bartonjs

**Comment by alexrp** [comment]
The relevant refsrc code (notable that it sets `HashSizeValue` rather than overriding `HashSize`): https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/sha1.cs,18

**Comment by bartonjs** [comment]
Seems an easy enough fix (move setting HashSizeValue from the opaque implementation type down to the algorithm base class type).

Might I inquire as to why you're overriding SHA1 (or any other hash algorithm type)?

**Comment by alexrp** [comment]
It's for interoperation with another product that turned out to use a *very slightly* non-standard SHA-1 variant.

This was written quite a few years ago, but I think the fact that I inherited from `SHA1` might just have been out of early convenience (to get things like `HashSize` and being able to just pass it into existing code expecting a `SHA1` instance), and never having gotten around to cleaning up the code, actually. I've since changed the code to just inherit from `HashAlgorithm`.

**Comment by vcsjones** [comment]
> Seems an easy enough fix (move setting HashSizeValue from the opaque implementation type down to the algorithm base class type).

The Implementation is getting the value from `HashProviderDispenser` which asks the platform for the size (e.g. BCryptGetProperty). Would it makes sense to pull this down in to the abstract `SHA1` or simply know that "SHA1 is 160 bits" like .NET Framework was doing?

Seems kind of a waste to ask the platform the size of the digest for a user-implemented version.

**Comment by GrabYourPitchforks** [comment]
I'd pull it down into the abstraction. The scenario for subclassing `SHA1` and changing the hash size to anything other than 160 bits seems unrealistic. But the subclassed type could nonetheless override the virtual if they really need to provide a different value.

**Comment by vcsjones** [comment]
@GrabYourPitchforks Just so I'm clear on my question...

`SHA1+Implementation` gets the digest algorithm's size using:

https://github.com/dotnet/runtime/blob/cb1fc80f020c87a8720ea895e203c1f14cb456b8/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/SHA1.cs#L30-L31

Are you suggesting moving that to the base abstract SHA1? My suggestion was "Set it to 160" (and repeat for SHA2) since I don't think we need to waste creating a HashProvider, creating handles, and asking the platform "What is the size of SHA1" when it's really never going to be another other than 160.

**Comment by GrabYourPitchforks** [comment]
I guess what I'm thinking is something like this:

```cs
public abstract class SHA1 : HashAlgorithm
{
    protected SHA1()
    {
        HashSizeValue = 160; // hardcoded
    }
}
```

Where everything else stays the same. The internal subclass of `SHA1` would remain line-for-line as it is today. That should be the minimal change that would fix the problem.

**Comment by bartonjs** [comment]
For some reason, when I was looking at it this morning I thought that the SHA1+Implementation had a literal 160, hence "move it up".  We can leave the implementation assigning it accurately (or, maybe just asserting that it's right), but hard-coding the value in the algorithm base class protected ctor seems legit.
