### ISSUE TITLE
Behavior of Math.Cos and Sin of double.MaxValue differs between 32- and 64-bit Windows

### ISSUE THREAD

**Issue by mellinoe** [dotnet/runtime#21372]
This is a behavior difference inherited from the underlying C-runtime library functions we are now using. Some of our higher-order functions, like `Complex.Cos`, etc. inherit some quirkiness in their behavior when interacting with `double.MaxValue`.

32-bit Windows:
```
Cos(min) == 0.90578110220707
Cos(max) == 0.90578110220707
Sin(min) == 0.423745908398588
Sin(max) == -0.423745908398588
```

64-bit Windows
```
Cos(min) == -0.99998768942656
Cos(max) == -0.99998768942656
Sin(min) == -0.00496195478918406
Sin(max) == 0.00496195478918406
```

FYI: @tannergooding

**Comment by tannergooding** [comment]
Going to close this as current unactionable.

I'm aggregating this along with the other similar issues locally and will write up a proposal on how to address these cross platform differences moving forward.
