### ISSUE TITLE
Change xml docs for Activity.OperationName

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/runtime#21412]
The new `Activity` type from DiagnosticSource is based on OpenTracing's `span` type. However, I've noticed that Activity's meaning of "OperationName" is different than OpenTracing's.

Definition from the [OpenTracing specification](https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span):
> An operation name, a human-readable string which concisely represents the work done by the Span (for example, an RPC method name, a function name, or the name of a subtask or stage within a larger computation). The operation name should be the most general string that identifies a (statistically) interesting class of Span instances. That is, "get_user" is better than "get_user/314159".
>
> For example, here are potential operation names for a Span that gets hypothetical account information:
>
> | Operation Name | Guidance |
> |--------|--------|
> | get | Too general |
> | get_account/792 |Too specific |
> |get_account | Good, and account_id=792 would make a nice Span tag |

With Activity however, the OperationName is used as a compile-time constant that is used for the DiagnosticSource event names - e.g. "System.Net.Http.HttpRequestOut".

Depending on how much you'd like to follow the OpenTracing standard, it might be good to rename the property to reduce confusion. I think that your usage might come closest to OpenTracing's standard tag "[component](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table)" however using that might be confusing as well. Maybe it's best to call it just `Name` (and `activityName` if used as a parameter)?! In the [HttpClient](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandlerLoggingStrings.cs#L17) instrumentation code you already use `ActivityName` anyway.

Also, the comment for `Activity.OperationName` still contains an explanation for an OpenTracing-like usage and therefore should be changed as well.
```csharp
/// <summary>
/// An operation name is a COARSEST name that is useful grouping/filtering. 
/// The name is typically a compile-time constant.   Names of Rest APIs are
/// reasonable, but arguments (e.g. specific accounts etc), should not be in
/// the name but rather in the tags.  
/// </summary>
public string OperationName { get; }
```

/cc @lmolkova @vancem

**Comment by tarekgh** [comment]
Closing this issue as we didn't get a response. If the issue id a doc issue, I would suggest to open a new issue in the https://github.com/dotnet/doc repo
