### ISSUE TITLE
SignedXml - refuses valid signed XML file

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#21451]
Created based on Connect report: http://connect.microsoft.com/VisualStudio/feedback/details/1765025/verify-xml-signature-getc14ndigest-problem-in-signedxml-class (internal bug [144292](https://devdiv.visualstudio.com/DevDiv/_workitems?id=144292&_a=edit))

**Description:** I've a problem with verifying XML signature file. The signature is done by third-party application and I am verifying the signature of that XML file in .NET framework 4.0 (check with latestes 4.6 and there is no difference).

To identify the problem, I've taken a sample.xml
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><a><b>A</b></a>
```

When I sign the xml with the third-party app, I get signed.xml:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<a>
  <b>A</b>
  <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xds="http://uri.etsi.org/01903/v1.1.1#">
    <ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <ds:Reference URI="">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <ds:DigestValue>/l5xchvEjxgLdPNt9RiB3TTQTcc=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>
    <ds:SignatureValue>
      cSUDo87XVNqbo+ljCZRAXvcuIXkak/10XyVWks9BNz5EdUmcVbiU84Y5qrJoAkMd
      yHPiIFkz8Dx5v5psK5oZjGtRleQ67nm1BryHA8F7EW4Otxe/8hEHsqVFK0zz3P79
      XzKD2vl4lUaTTOLlCMD+SbpbekyLkDIjXS/6IylPWbNNF3sH9MclGGhSSjREwOuJ
      Ayj8xqqibQEDvIytLN23+bZJtOGAU54ERXPnh4rccBvzByno08DHVnkQrSQCgY4E
      CvVbocIFo7GGtq8v9oj6rK3KpWUQnL1V1Aqj5fXRNRC8VnxJyIkHAXOBWC3Wr+DQ
      zEm4W0Xa+vZ8o0x/2Ct2cg==
    </ds:SignatureValue>
    <ds:KeyInfo>
      <ds:X509Data>
        <ds:X509Certificate>
          MIIEejCCA+OgAwIBAgIIBg5jkS3DgTkwDQYJKoZIhvcNAQEFBQAwOjETMBEGA1UE
          CxMKSW5mcmF4STRDQTEWMBQGA1UEChMNSW5mcmF4IGQuby5vLjELMAkGA1UEBhMC
          U0kwHhcNMTEwNTAzMDkxMzU2WhcNMTYwNTAxMDkxMzU2WjBfMRcwFQYDVQQDEw5Q
          cnZpIFVwb3JhYm5pazEQMA4GA1UECxMHaTQgdXNlcjEUMBIGA1UEChMLVGVzdCBk
          Lm8uby4xDzANBgNVBAcTBlRvbG1pbjELMAkGA1UEBhMCU0kwggEiMA0GCSqGSIb3
          DQEBAQUAA4IBDwAwggEKAoIBAQCkkkadn/Uapod4N0f7GVgDNNN/vRoNUzqbdsER
          vUA7f/MoARF0LoXAoxpAEk2DDf24oIkGjL60uqwx4di5LQr83zsdA/7Wh7RHb73j
          Cv0glfwK/YpfJcsxfLi/OajWNX5p63D9ISSDYtIgUb4k4JFElg+mbMsRFlPQNyR6
          bADQTWputmTE+reWRiHLlnXLNSH3wGO008BfYuBnsuWupK8ar5UQ5I2IyafZJONO
          4UQjsXsanYGqivWm147bihj7zfDjqEmVg0yYm9NS/jbhQSXRV9n8348engtu48ND
          g7Jsr363Ou1nvThzsxIyRBbqSCNSJPAiEYl/jF4WRO2zGmZzAgMBAAGjggHeMIIB
          2jAMBgNVHRMBAf8EAjAAMCAGA1UdJQEB/wQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
          BDAfBgNVHSMEGDAWgBSjdHM8IbieDPxF1rwNvMKR0T6WQDB3BgNVHR8EcDBuMGyg
          aqBohmZodHRwOi8vY2EuaW5mcmF4LnNpL2VqYmNhL3B1YmxpY3dlYi93ZWJkaXN0
          L2NlcnRkaXN0P2NtZD1jcmwmaXNzdWVyPU9VPUluZnJheEk0Q0EsTz1JbmZyYXgg
          ZC5vLm8uLEM9U0kwDgYDVR0PAQH/BAQDAgSwMB0GA1UdDgQWBBSKMErpxIQp6TQ8
          Jqr0ywYrYla4NzCB3gYIKwYBBQUHAQEEgdEwgc4wgYkGCCsGAQUFBzAChn1odHRw
          Oi8vY2EuaW5mcmF4LnNpL2VqYmNhL3B1YmxpY3dlYi93ZWJkaXN0L2NlcnRkaXN0
          P2NtZD1pZWNhY2VydCZpc3N1ZXI9T1UlM2RJbmZyYXhJNENBJTJjTyUzZEluZnJh
          eCtkLm8uby4lMmNDJTNkU0kmbGV2ZWw9MDBABggrBgEFBQcwAYY0aHR0cDovL2Nh
          LmluZnJheC5zaTo4MDgwL2VqYmNhL3B1YmxpY3dlYi9zdGF0dXMvb2NzcDANBgkq
          hkiG9w0BAQUFAAOBgQAms5UL/f0AIavlVo9C5W5Ijdt12g/59PIZeAEDWzoEKi+W
          rE7ORaq527UHgcVGw7Gr2HhOEHmggUe6k43edQ0fkNg5WXfJzf18hHA+foVqsxra
          DxBeot442A1zw9GjRnIDCl2r91tHgkneqg2EE8kf7lkRtMRck1MUbHBnLnppKg==
        </ds:X509Certificate>
      </ds:X509Data>
    </ds:KeyInfo>
  </ds:Signature>
</a>
```

(**Note**: The original issue had no (non-required) whitespace in the XML, it was pretty-printed here to allow for better human understanding)

This signed XML is valid, according to let's say this (https://www.signatur.rtr.at/en/elsi/Pruefung.html) tool, and I've verified it with a few other tools and all confirm that it's OK, except when I verify it with SignedXml class from .NET Framework.
The code I'am using to verify the XML.

Now the problem as I've managed to identify is in the SignedXml class in function [`GetC14NDigest`](https://github.com/dotnet/corefx/blob/378b1e398a40e78f3c40363f91a2359e14c9940c/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs#L791-L817) where `Utils.GetPropagatedAttributes(m_context)` is called. `m_context` is signed XML document, but the namespace `xmlns:xds="http://uri.etsi.org/01903/v1.1.1#"` is only in Signature node, which was propagated into the `SignedInfo` node, but the `Utils.GetPropagatedAttributes(m_context)` did not return that one, and the SignedInfo node is missing that one, so the SignedInfo node is not the same as it was when the signature was constructed.

I've tried to sign an xml like this:
```xml
<a xmlns:xds="http://uri.etsi.org/01903/v1.1.1#">
  <b>A</b>
</a>
```
and this signed XML I was able to verify successfully with SignedXml class.

**Comment by phax** [comment]
This issue still exists in .NET 5.0 - any update would be appreciated...

**Comment by da9l** [comment]
I'm having this problem with .NET 6 and the failure of validating the SignedInfo element. 

Either I'm doing something wrong or this is a live bug.

These links suggest that the .NET implementation fails to propagate the namespaces correctly to the SignedInfo element during the Inclusive C14N Canonicalization process.
https://www.di-mgt.com.au/docs/ia_071912.pdf
https://www.aleksey.com/pipermail/xmlsec/2012/009463.html

I've also managed to enable the Debug logging of the SignedXml.CheckSignature method and it clearly shows that it is the  SignedInfo validation that fails.

```fsharp
let traceSource = 
    Assembly.Load("System.Security.Cryptography.Xml")
        .GetType("System.Security.Cryptography.Xml.SignedXmlDebugLog")
        .GetField("s_traceSource", (BindingFlags.Static ||| BindingFlags.NonPublic))
        .GetValue(null) :?> TraceSource

let added = traceSource.Listeners.Add(new TextWriterTraceListener(System.Console.Out))
traceSource.Switch.Level <- SourceLevels.Verbose
```

Given time I'll see if it's possible to create a proper reproduction repo.

**Comment by da9l** [comment]
I've recreated @karelz reproduction as a public reproduction repo in dotnet 6.0.203 with the debug info enabled.
https://github.com/da9l/SignedXmlCheckSignatureBug

**Comment by karelz** [comment]
Tagging @bartonjs @GrabYourPitchforks who own the area now.

**Comment by willisd2** [comment]
I ran into an issue similar to this which I think others in this thread are running into as well (@da9l and @phax). It looks like what we're running into is described pretty well in this issue https://github.com/dotnet/runtime/issues/27500 

From what I can tell it looks like the fix should be a part of .NET 7.

**Comment by ThiemeNL** [comment]
The issue still exist in .NET 7, is there any update?

**Comment by willisd2** [comment]
> The issue still exist in .NET 7, is there any update?

Not sure exactly what your situation is, and I'm going to completely hack this explanation cause I'm going from memory... 

My situation was validating a SAML token. The token had the overall Document signed and the Assertion Element signed. The overall Document signature checked out fine prior to .NET 7, but the Assertion signature was failing due to this issue. After the 'fix' was in, my Assertion signature still wasn't passing. I eventually figured out it was because the Assertion Element was isolated from the main XmlDocument, and a new XmlDocument was created out of it. This was the way it was done on about every example you would find on the internet. When I checked the Assertion signature based off of referencing the element in the original XmlDocument, then the signature checked out.

**Comment by ThiemeNL** [comment]
@willisd2 my issues is exactly the sames as @phax mentioned. Maybe there are two seperated issues discussed in this thread. Mine is also the same as: https://stackoverflow.com/questions/47694541/wrong-canonicalization-c14n-made-by-signedxml-it-removes-line-breaks-13

**Comment by yelvert** [comment]
so, year 6 of this same issue, completely prevents anyone from making a secure saml implementation in dotnet

**Comment by totszwai** [comment]
I just happened to stumble the need of this too. Welcome to 2024. Subscribed.
