### ISSUE TITLE
coreclr build-test.cmd can quietly fail to update files

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#2148]
Common failure is to inadvertently have an active debug session while you're building. Any files kept open by the debugger will quietly fail to update in Core_Root. Next time you debug you're looking at a stale binary.
```
.\build-test.cmd x86 checked skipmanaged skipnative
...
C:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root_Stage\clrjit.dll
Sharing violation
BUILDTEST: Test build succeeded.  Finished at  9:05:45.36
BUILDTEST: Test binaries are available at C:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x86.Checked
```
This failure should be more prominent.

**Comment by agocke** [comment]
I believe this should be fixed after the move to ninja. Feel free to re-open if you've seen this again.
