### ISSUE TITLE
Possible JIT inlining optimization: removing multiple argument null checks

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#2156]
Would it make sense for the JITer to eliminate redundant "if null then throw" (i.e. `if (arg == null) throw Exception();`) checks for a given argument if it is not possible for that argument value to have changed between the checks? As far as I can tell this does not currently happen, even for simple cases.

For example:
```c#
void M1(string value) => M2(value ?? throw new ArgumentNullException();

[MethodImpl(MethodImplOptions.AggressiveInlining)]
void M2(string value) => M3(value ?? throw new ArgumentNullException();

[MethodImpl(MethodImplOptions.AggressiveInlining)]
void M3(string value) => M4(value ?? throw new ArgumentNullException();

[MethodImpl(MethodImplOptions.AggressiveInlining)]
void M4(string value)
{
    if (value == null)
        throw new ArgumentNullException();
}

// After inlining M1 effectively becomes:

void M1(string value)
{
    if (value == null) throw new ArgumentNullException();
    // These can be removed:
    if (value == null) throw new ArgumentNullException();
    if (value == null) throw new ArgumentNullException();
    if (value == null) throw new ArgumentNullException();
}

```

**Comment by benaadams** [comment]
Think it does? [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYmpBkJoBvGgzNMUDALLkAFM0YLskjjACUDALwA+a6VtOLjAMAPwhDBgAFlAQAO4MXDDxAIJQAOYcAjwAchySkgCiCCpifBBctm5uGtSm5gDaVjBREAAmAJLikrZNLR1dAPKlvOW4LMlpabC4uLwKMO1ckrxcK2luALp1ZsSWVv4ODIGuHj7W2gHOrqHhUTHxiSnpmTA5eYXFMMPlldWa1OYGI1mpE2p0xN1eqD+hChmUuGMJlNVLN5otlqsuOstgDzLtzvZyI4ru4vL4rChLkEbhFonEEkkGKkMlkMLl8kUSvDfjVtkCoWCuj0QYLYd8EeNJtNUQslis1ps+fiKYTiUE3HyTLjAWZeAAzBhU66eTwJd4a7U6wF3emPJnPVnsj5ckYVP6WgC+NA9QA==)
```
C.M1(System.String)
    L0000: push rsi
    L0001: sub rsp, 0x20
    L0005: test rdx, rdx
    L0008: jz L001c
    L000a: mov rax, 0x7ffecbff0080
    L0014: add rsp, 0x20
    L0018: pop rsi
    L0019: jmp rax
    L001c: mov rcx, 0x7ffec35ec980
    L0026: call 0x7fff23084690
    L002b: mov rsi, rax
    L002e: mov rcx, rsi
    L0031: call System.ArgumentNullException..ctor()
    L0036: mov rcx, rsi
    L0039: call 0x7fff2303a4f0
    L003e: int3
```

**Comment by mikernet** [comment]
Hmmm....
```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-3770 CPU 3.40GHz (Ivy Bridge), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.100
  [Host]     : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT
  DefaultJob : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT


| Method |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |----------:|----------:|----------:|------:|------:|------:|----------:|
|     M1 | 49.655 us | 0.3723 us | 0.3109 us |     - |     - |     - |      24 B |
|     M2 | 39.078 us | 0.7637 us | 0.9091 us |     - |     - |     - |      24 B |
|     M3 | 24.838 us | 0.1931 us | 0.1806 us |     - |     - |     - |      24 B |
|     M4 |  5.553 us | 0.0498 us | 0.0442 us |     - |     - |     - |         - |
```

**Comment by benaadams** [comment]
Tiered Compilation? Try adding to the .csproj:
```xml
<TieredCompilation>false</TieredCompilation>
```

**Comment by mikernet** [comment]
Same result

**Comment by benaadams** [comment]
Or pop in a `[GlobalSetup]` that calls your benchmark methods a many times, then sleeps for 300ms; so get Tier1 to kick in
```csharp
[GlobalSetup]
public void Setup()
{
    for (int i = 0; i < 200; i++)
    {
        M1();
        M2();
        M3();
        M4();
    }
    
    Thread.Sleep(300);
}
```

**Comment by benaadams** [comment]
Tier0 doesn't do any inlining

**Comment by mikernet** [comment]
Tiered on/off and adding global setup don't change the results for any of my tests. Interestingly enough, if I make the methods static instead of instance I get this result:
```
| Method |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |----------:|----------:|----------:|------:|------:|------:|----------:|
|     M1 | 24.775 us | 0.1740 us | 0.1628 us |     - |     - |     - |         - |
|     M2 |  5.536 us | 0.0672 us | 0.0596 us |     - |     - |     - |         - |
|     M3 |  5.555 us | 0.0892 us | 0.0745 us |     - |     - |     - |         - |
|     M4 |  5.533 us | 0.0440 us | 0.0390 us |     - |     - |     - |         - |
```
What that means, I don't know :)

**Comment by benaadams** [comment]
Have gist with the benchmark code?

**Comment by mikernet** [comment]
https://gist.github.com/mikernet/342634b69265d73cdd5ee3e035553bf0

**Comment by mikernet** [comment]
Oh wait, the static result might makes sense...M1 probably isn't; getting inlined...? The instance one I'm a bit confused about though.

**Comment by mikernet** [comment]
Applying aggressive inlining to M1 fixes the static case, all ate 5us now.

**Comment by stephentoub** [comment]
So this can be closed, right?

**Comment by mikernet** [comment]
No - the instance methods still exhibit the problematic behavior.

**Comment by AndyAyersMS** [comment]
In the instance case, CSC is producing IL that the jit isn't quite prepared to handle in an inlinee -- there is a throw with more than one element on the evaluation stack.
```
.method public hidebysig instance void  M1(string 'value') cil managed
{
  // Code size       23 (0x17)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldarg.1
  IL_0002:  dup
  IL_0003:  brtrue.s   IL_0011
  IL_0005:  pop
  IL_0006:  ldstr      "value"
  IL_000b:  newobj     instance void [mscorlib]System.ArgumentNullException::.ctor(string)
  IL_0010:  throw
  IL_0011:  call       instance void C::M2(string)
  IL_0016:  ret
} // end of method C::M1
```
End result is a failure to inline, despite the aggressive inline attribute:
```
Inlines into 06000006 X:X1(C)
  [0 IL=0006 TR=000002 06000001] [FAILED: throw with invalid stack] C:M1(System.String):this
```
I think this inlining restriction is bogus, but will have to look deeper.

**Comment by AndyAyersMS** [comment]
Seems straightforward to remove the inlining limitation. With my local changes I now see identical code for callers of `M1` through `M4`. I am generally in favor of removing arbitrary inlining blockers but would also like to see this help improve code somewhere specific.

@mikernet, is this a pattern you've seen used frequently somewhere? 

There are a few new inlines now happening in FX code, but not many. The results would be better if the exceptions used the throw helper pattern as exception object construction tends to be fairly heavyweight...
```
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary of Code Size diffs:
(Lower is better)
Total bytes of diff: 566 (0.00% of base)
    diff is a regression.
Top file regressions (bytes):
         180 : System.Composition.AttributedModel.dasm (29.80% of base)
         161 : System.Private.CoreLib.dasm (0.00% of base)
         133 : System.Security.Cryptography.Pkcs.dasm (0.03% of base)
          63 : System.DirectoryServices.Protocols.dasm (0.07% of base)
          29 : System.Runtime.Numerics.dasm (0.04% of base)
5 total files with Code Size differences (0 improved, 5 regressed), 160 unchanged.
Top method regressions (bytes):
         161 (22.39% of base) : System.Private.CoreLib.dasm - CustomAttributeData:get_NamedArguments():IList`1:this
         133 (36.34% of base) : System.Security.Cryptography.Pkcs.dasm - PkcsHelpers:DeepCopy(CmsRecipientCollection):CmsRecipientCollection
          96 (457.14% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor(String):this
          84 (400.00% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor():this
          63 (14.58% of base) : System.DirectoryServices.Protocols.dasm - AddRequest:.ctor(String,String):this
          29 ( 7.67% of base) : System.Runtime.Numerics.dasm - BigNumber:HexNumberToBigInteger(byref,byref):bool
Top method regressions (percentages):
          96 (457.14% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor(String):this
          84 (400.00% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor():this
         133 (36.34% of base) : System.Security.Cryptography.Pkcs.dasm - PkcsHelpers:DeepCopy(CmsRecipientCollection):CmsRecipientCollection
         161 (22.39% of base) : System.Private.CoreLib.dasm - CustomAttributeData:get_NamedArguments():IList`1:this
          63 (14.58% of base) : System.DirectoryServices.Protocols.dasm - AddRequest:.ctor(String,String):this
          29 ( 7.67% of base) : System.Runtime.Numerics.dasm - BigNumber:HexNumberToBigInteger(byref,byref):bool
6 total methods with Code Size differences (0 improved, 6 regressed), 244490 unchanged.
```

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L251-L254
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/Reflection/CustomAttributeNamedArgument.cs#L38-L42

**Comment by mikernet** [comment]
Won't using a throw helper guarantee that the multiple checks won't get eliminted?

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4am6jQa69u4gGYmpBkJ369AbwuXLAbQCyMDAAsIAEwCS4yQApnN08fMUkAeTE+CC5cFgBBAHME2FxcXgUYLy5JXi5chIBKAF1bOz0jJhQGR3I/ZkYFbEkOGAKGAF4APmrSP0bmmAYAfiGGABVXKAgAdwA1Jpa4qASOAR4AOQ5JfwKCjW1qModA929fAJdTkPDI3mjYxOTVNIysnLyuQpLDo/LjYiqjl69QY/RabS61UMfQWgxG40mM3mAyWKzWGE22z8u32pSOTkuwXOJyJoQiURi8SSKRemWyuXyxTxZQqAKhdXIDVhEO6jhQMIGw1GEymc1hqNWMA2Wx2ey0vz0BKCZ1CF2V13Jd0pjxp6Tp70Z3wVBn+gP5ILBrWZdhsP2Nel4ADMGAKWh12gwuDKCtb7QjRcjFstJdKsXK7b8AL7y41iKDpbAYQbMJBMTn+pHi4PozE7DrdNyiz0waYMCU5mUAUQQKlu0T8ACJLQ3w0dI0A==

**Comment by mikernet** [comment]
Throw helpers make a lot of sense in the BCL to reduce JIT code size, but then you have to add a bunch of internal `M1Impl()`, `M2Imple()`, etc. methods which skip the null check to avoid rechecking the same argument multiple times, which adds complexity to the code. Throw helpers also impede the JIT's ability to cleverly rearrange asm to push the throw code to the end of a method because it doesn't treat the throw helper call like an exit point.

Optimizing for JIT code size in higher level libraries / app code often doesn't make a lot of sense for the reasons above, among others. Regardless, anecdotally I don't believe most libraries and projects tend to use throw helpers in most cases, so if this is a relatively easy fix it could help for a lot of code outside the BCL.

**Comment by mikernet** [comment]
Or maybe you mean this pattern, which keeps the throw statement in the original method:

```c#
        public class C
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void M1(string value) => M2(value ?? throw GetValueArgumentNull());

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void M2(string value) => M3(value ?? throw GetValueArgumentNull());

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void M3(string value) => M4(value ?? throw GetValueArgumentNull());

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void M4(string value)
            {
                if (value == null)
                    throw GetValueArgumentNull();
            }

            [DoesNotReturn]
            [MethodImpl(MethodImplOptions.NoInlining)]
            private static ArgumentNullException GetValueArgumentNull() => new ArgumentNullException("value");
        }
```

I got the same result with this throw helper as before, with and without `[MethodImpl(MethodImplOptions.NoInlining)]` applied to the throw helper.

**Comment by AndyAyersMS** [comment]
Hmm, you're right -- the throw helper pattern does not get properly cleaned up here. Will have to follow up on this. I suspect the fact that the helper must look like it returns a value is a contributor

> if this is a relatively easy fix it could help a lot of code outside the BCL.

It is a relatively easy fix.

> Throw helpers also impede the JIT's ability to cleverly rearrange asm  to push the throw code to the end of a method because it doesn't treat the throw helper call like an exit point.

That should no longer be the case, at least most of the time, see eg dotnet/coreclr#6103

**Comment by mikernet** [comment]
Yeah, it seems that the helper return value in this case causes the issue. It cleans it up properly if I rearrange things so there is no return value, which is pleasantly surprising, I didn't expect that. 

It's kind of interesting that it doesn't actually inline the throw helper but acts kind of like it has been  inlined...yet if you ask it to be inlined or not inlined then everything kinda falls apart, haha. Note to self: don't mark throw helpers with `NoInling`.

I find it curious that it eliminates the redundant null checks with a throw helper but not in what seems like the seemingly simpler case of directly throwing ANE.

**Comment by mikedn** [comment]
>  it seems that the helper return value in this case causes the issue

AFAIR the problem with returning a value from the helper is that the JIT needs to discard the part of the tree that uses the return value (in this case it looks like it is assigned to a lclvar). Given that the inliner anyway splits the tree and then merge it again at `RET_EXPR` it may be that this isn't difficult to fix.
