### ISSUE TITLE
Add Path.Exists -- to replace inefficient FileExists || DirectoryExists

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#21678]
We should implement the code for this internally and look at adding a public API for it.  Probably `Path.Exists(string path)`.

The internal helper should avoid any sort of path validation/normalization if possible. A bad path, by definition, doesn't exist. At least on the Windows side pre normalizing isn't needed (and wasteful). We should also consider exposing overloads such as `Path.Exists(string path, bool normalize)` to allow users to skip this as well (or perhaps a config switch).

[added by @danmoseley --]

### Background and motivation

It's fairly common to want to know whether a file path is available to write to, without writing the file. For example, in order to prompt the user for a default save file name. In order to do this using our standard API, one must separately check whether the path matches an existing file, or an existing directory:
```c#
if (File.Exists(path) || Directory.Exists(path))
{
     // choose another name, bail out, etc
}
```
A new API can unify both these checks into one call, which is less verbose but more importantly potentially more efficient -- the underlying implementation (eg `lstat`, `GetFileAttributesEx`) generally returns all this info with a single call. While it's likely caching at some layer below .NET means that the above will not cause two disk reads, there's certainly inefficiency in performing two syscalls to get the same information.

### API Proposal

```c#
    public static partial class Path
    {
        // Implementation is logically equivalent to File.Exists(path) || Directory.Exists(path)
        public static bool Exists([System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? path) { .... };
    }
```
### API Usage
```c#
if (Path.Exists(path))
{
     // choose another name, bail out, etc
}
```

### Alternative Designs

There is already an abstract method `FileSystemInfo.Exists` which but to make that useable, it would have to change from abstract to virtual, as would the `FileSystemInfo` class, which would also need to expose a public constructor. This would also change its nature from representing either a directory or file (chosen at construction time) to representing something that is possibly either. As an instance method it would require newing up an object, which is wasteful. Finally, `FileSystemInfo.Exists` is likely less discoverable and readable than `Path.Exists` and discoverability is important since this is a fairly basic operation.

### Risks

"Paths" in the broadest sense can represent more than traditional files and directories, and `Path.Exists` might imply to some that it could for example on Windows be used to test for the existence of a named pipe or other OS object. I suspect that is unlikely though, as the overwhelming use of the Path class is not with such objects.

**Comment by danmoseley** [comment]
@JeremyKuhne do you have opinions on API review feedback above?

**Comment by JeremyKuhne** [comment]
> Is FileSystemInfo.Exists better place for the API?

There is already a `FileSystemInfo.Exists`. Having to create multiple `FileSystemInfo` derived classes to check if a path exists is even more wasteful. Putting a new static there doesn't follow the existing usage. `Path`, `Directory` and `File` are the statics classes.

> Would it return true for named pipes and similar things?

Whatever the OS says for the path that would be the logical amalgam of `File.Exists` and `Directory.Exists`.

> Can it be implemented consistently and efficiently on both Windows and Linux? (esp. non-file resources)

Yes, if there is a question it should match `File.Exists(path) || Directory.Exists(path)`. You can see that https://source.dot.net/#System.Private.CoreLib/FileSystem.Exists.Unix.cs,35 is effectively a "filter out directories" set of logic. You'd just trim out the special directory logic (the trim and the check for the directory flag). This would be an even more substantial perf benefit on Unix than Windows (removes a potential extra string allocation as well).

**Comment by danmoseley** [comment]
Thanks @JeremyKuhne. I've edited your proposal to match the standard format . @dotnet/area-system-io I've marked `api-ready-for-review`. Feel free to remove if you have concerns/alternative preferences.

**Comment by GSPP** [comment]
Can this method (or a variant of it) return whether an existing path is a file or a directory? That seems useful.

**Comment by adamsitnik** [comment]
@danmoseley thank you for improving  the proposal! I've assigned myself and I'll get it moving from here.

**Comment by terrajobst** [comment]
* We considered returning whether it was a file or directory but
    - It seems rarely useful
    - It's more expensive in case of symlinks

```C#
namespace System.IO
{
    public static partial class Path
    {
        // Implementation is logically equivalent to File.Exists(path) || Directory.Exists(path)
        public static bool Exists([NotNullWhenAttribute(true)] string? path);
    }
}
```

**Comment by danmoseley** [comment]
Up for grabs...

**Comment by Tarun047** [comment]
Hey Guys, I'd like to take up this issue, I've created a simple implementation here: https://github.com/Tarun047/runtime/commit/81349ba279302d26d566863eb6277216c772dc80

But I am not sure, where or if I should add tests.

**Comment by danmoseley** [comment]
Hi @Tarun047  tests could go with existing Path tests? Thanks!

**Comment by adamsitnik** [comment]
@Tarun047 To be able to consume the new API from the tests you need to add it to a reference assembly here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/ref/System.Runtime.cs

The Path tests can be found here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Extensions/tests/System/IO/PathTests.cs

You can reuse some of the tests that were written for `File.Exists` and `Directory.Exists`:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem/tests/File/Exists.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem/tests/Directory/Exists.cs

I am OK with adding `Path.Exists` tests to `src/libraries/System.IO.FileSystem/tests/`

Here you can find how to run the tests: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md

Usually what I do is building the entire product and running selected tests from the repo root:

```cmd
.\build.cmd -c Release -subset clr+libs+libs.tests
dotnet build .\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj /p:Configuration=Release /t:Test
```
