### ISSUE TITLE
add method to directly round double to decimal

### ISSUE THREAD

**Issue by coderb** [dotnet/runtime#21670]
the current version of the API requires 2 rounding operations to convert from a `double` to a `decimal` with `n` places of precision.

eg
```
double d = ...;
decimal m1 = (decimal)d; // first rounding operation
decimal m2 = Math.Round(m1, n, MidpointRounding.AwayFromZero); // second rounding operation
```
ideally we would have an API that allows a direct conversion/round in a single operation:

in class `Decimal`:

```
public static decimal Round(double d, int n, MidpointRounding rouding) {}
```
this is both for performance and correctness reasons.  rounding twice may introduce inaccuracies (albeit subtle and infrequent) and also inccurs an extra unnecessary step.

**Comment by coderb** [comment]
@tannergooding any chance of getting this on the dev plan?  it doesn't seem like it would be that difficult to implement.  thanks.

**Comment by dakersnar** [comment]
@coderb do you have an example input that is rounded incorrectly using the existing method?

**Comment by coderb** [comment]
@dakersnar no, but if i had the direct rounding method i'm sure i could write a program to find an example ;-).

**Comment by dakersnar** [comment]
Got it. For clarity, I have a double to decimal conversion fix (https://github.com/dotnet/runtime/pull/72217) in the works that may or may not be related to this issue. I'll keep this in mind as that gets wrapped up.  keep this in mind as that gets wrapped up.

**Comment by coderb** [comment]
@dakersnar i salute you sir!

**Comment by dakersnar** [comment]
This api suggestion needs to be formalized to be considered. If you are interested in driving it forward yourself, please feel free to open a new issue that follows the API suggestion template. Our API review process and a link to the template/good example is here:  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps. For now, I'm closing this issue.
