### ISSUE TITLE
[Proposal] String.Format specifier for IEnumerable

### ISSUE THREAD

**Issue by ashmind** [dotnet/runtime#21820]
I feel like I have to include lists in strings quite often, which end up something like:
```
$"Name not found. Allowed names are: {string.Join(", ", names)}."
```

This has two problems:  
1. It's verbose (even has nested quotes)
2. It allocates extra string for the result of Join (potentially large)

I would like to propose a custom format specifier instead (name is up for consideration):

```
$"Name not found. Allowed names are: {names:J', '}."
```

And for lists of formattables (saves N+1 allocations instead of 1):
```
$"Byte is incorrect. Allowed bytes are: {string.Join(", ", bytes.Select(b => b.ToString("X2")))}"
// could become
$"Byte is incorrect. Allowed bytes are: {bytes:J', ':X2}."
```

**Comment by ericstj** [comment]
New API without any progress since 2017.  Definitely not in scope for 5.0.0.  @ashmind is this still of interest to you?

**Comment by ashmind** [comment]
I would be keen to have it for convenience and allocation reasons, but I am not sure on specific format and compatibility.

**Comment by stephentoub** [comment]
> but I am not sure on specific format and compatibility

Given that, and that it's been years and there's been little interest, I'm going to close this.

Note that you can always implement your own ICustomFormatter that does whatever you want, and with the string interpolation improvements in .NET 6 and C# 10, you can still use the interpolated string syntax, e.g. this:
```C#
string[] names = new[] { "Mirabel", "Bruno", "Isabela" };
Console.WriteLine(string.Create(EnumerableFormatter.Instance, $"Name not found. Allowed names are: {names:J', '}."));

class EnumerableFormatter : IFormatProvider, ICustomFormatter
{
    public static readonly EnumerableFormatter Instance = new();
    public object? GetFormat(Type? formatType) => formatType == typeof(ICustomFormatter) ? this : null;
    public string Format(string? format, object? arg, IFormatProvider? formatProvider) =>
        format == "J', '" && arg is IEnumerable<object> e ? string.Join(", ", e) :
        arg is IFormattable f ? f.ToString(format, formatProvider) ?? "" :
        arg?.ToString() ?? "";
}
```
outputs:
```
Name not found. Allowed names are: Mirabel, Bruno, Isabela.
```
