### ISSUE TITLE
DualModeConnectAsync_DnsEndPointToHost_Helper failed with Timed out waiting for Connection

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#21853]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170521.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DualModeConnectAsync~2FDualModeConnectAsync_DnsEndPointToHost_Helper(listenOn:%20::,%20dualModeServer:%20True)

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Timed out while waiting for connection\nExpected: True\nActual:   False
Stack Trace :
   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 630
```

**Comment by karelz** [comment]
Failures during 3/12-5/11 (incl. PRs):

Date | Build / PR | OS
-- | -- | --
3/13 | PR #49540 | Windows.10.Amd64.Server19H1.ES.Open
3/19 | PR #49855 | Windows.10.Amd64.Server19H1.ES.Open
3/29 | PR #50346 | Windows.10.Amd64.Server19H1.ES.Open

**Comment by antonfirsov** [comment]
This test still isn't stable yet, there were failures in October.

**Comment by wfurt** [comment]
I don't see recent failures. Perhaps really fixed  by https://github.com/dotnet/runtime/pull/80715. 
Closing for now, we should open new issue if we see new failures.
