### ISSUE TITLE
System.IO.FileSystem.Watcher.Tests failing on Libraries OSX Outerloop CI runs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#2185]
There is no explicit failure listed in the logs. Possible these are just timing out. 

```
Executed on dci-mac-build-059
+ ./RunTests.sh --runtime-path /tmp/helix/working/BCEB09AF/p
----- start Tue Jan 21 03:39:10 PST 2020 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/BCEB09AF/p/dotnet exec --runtimeconfig System.IO.FileSystem.Watcher.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Watcher.Tests.deps.json xunit.console.dll System.IO.FileSystem.Watcher.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing -notrait category=nonnetcoreapptests -notrait category=nonosxtests 
popd
===========================================================================================================
/private/tmp/helix/working/BCEB09AF/w/B274097E/e /private/tmp/helix/working/BCEB09AF/w/B274097E/e
  Discovering: System.IO.FileSystem.Watcher.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Watcher.Tests (found 19 of 184 test cases)
  Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 4)
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:02:11
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:04:12
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:06:13
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:08:13
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:10:14
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:12:15
   System.IO.FileSystem.Watcher.Tests: [Long Running Test] 'System.IO.Tests.DangerousFileSystemWatcherTests.FileSystemWatcher_Unix_DoesNotLeak', Elapsed: 00:14:16

```

Builds
- https://dev.azure.com/dnceng/public/_build/results?buildId=493872
- https://dev.azure.com/dnceng/public/_build/results?buildId=491012
- https://dev.azure.com/dnceng/public/_build/results?buildId=490329

Test Runs
- netcoreapp5.0-OSX-Release-x64-OSX.1013.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-OSX.1013.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-OSX.1014.Amd64.Open

**Comment by wfurt** [comment]
This test is generally very slow test and as `*DangerousFileSystemWatcherTests*` suggests not really safe to run as it is trying to exhaust system limits. I saw similar failures recently and I'm wondering if anything changed somewhat recently with OSX infrastructure. 

I think we should disable the test for CI if we cannot run it reliably. 

cc: @safern @MattGal

**Comment by safern** [comment]
Nothing change. I believe this is an outerloop test and it is failing on outerloop runs, I guess that is the intention of that test. 

If you look at the build link it is happening in outerloop osx:
https://dev.azure.com/dnceng/public/_build/results?buildId=493872

**Comment by wfurt** [comment]
I'm sure there was time this test was passing reliably as I wrote this test and did many runs in various configurations. Relevant Watcher code did not change AFAIK. 
I will take a look.

**Comment by wfurt** [comment]
It seems like a system limit for open files has changed. With the current limit ~ 10K, it takes more than 20 minutes to exhaust system resources on my MacBook. I have some ideas on how to fix the test to be more predictable.

**Comment by MattGal** [comment]
> It seems like a system limit for open files has changed. With the current limit ~ 10K, it takes more than 20 minutes to exhaust system resources on my MacBook. I have some ideas on how to fix the test to be more predictable.

Yes, at the request of folks from the runtime team our Macs should have:
```
ulimit -c unlimited
ulimit -n 10240
```
... this was requested specifically so various folks' tests could pass.
