### ISSUE TITLE
jit\HardwareIntrinsics\X86\Bmi1\Bmi1_ro fails under jitstress/gcstress

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#2186]
With
```
set COMPlus_GCStress=0xC
set COMPlus_JitStress=2
set COMPlus_TieredCompilation=0
```
we get a runtime assertion failure:
```
Assert failure(PID 24128 [0x00005e40], Thread: 21576 [0x5448]): 
!CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner + 0x65D (0x5e94950d)
CORECLR! Object::Validate + 0x181 (0x5e948e71)
CORECLR! Object::ValidatePromote + 0xB (0x5e9495c1)
CORECLR! WKS::GCHeap::Promote + 0x79 (0x5ec2e1b9)
CORECLR! GcEnumObject + 0x57 (0x5eb76ff7)
```
Failing method is `JIT.HardwareIntrinsics.X86.ScalarBinaryOpTest__BitFieldExtractUInt32:RunClassLclFldScenario`

The jit reports `eax` as gc live just after the `bextr`, when it has just been killed.
```asm
000035 call     CORINFO_HELP_NEWSFAST
00003A mov      byte  ptr [eax+10], 1
00003E mov      dword ptr [eax+4], 0x1E000000
000045 mov      word  ptr [eax+8], 0x419
00004B mov      dword ptr [classVar[0x7a034c0]], 0x1E000000
000055 mov      word  ptr [classVar[0x7a034d0]], 0x419
00005E movzx    edx, word  ptr [eax+8]
000062 mov      ecx, dword ptr [eax+4]
000065 bextr    eax, ecx, edx                       
00006A mov      dword ptr [V02+0x2 esp+06H], eax   ;; eax's gc life should end here
00006E push     edx
00006F mov      edx, dword ptr [V02+0x2 esp+06H]
000073 push     edx
000074 mov      edx, gword ptr [05EF34BCH]      'RunClassLclFldScenario'
00007A push     edx
00007B mov      edx, ecx
00007D mov      ecx, esi
00007F call     ...ValidateResult
000084 cmp      dword ptr [V06 esp+0CH], 0x1234567

F3 75          | 0025        reg ESI becoming live
4E             | 002B        reg ECX becoming live
0D             | 0030        reg ECX becoming dead
F0 42          | 003A        reg EAX becoming live
F5 B5          | 006F        push non-ptr (1)
B5             | 0074        push non-ptr (2)
56             | 007A        reg EDX becoming live
12             | 007D        reg EDX becoming dead
4A             | 007F        reg ECX becoming live
05             | 0084        reg EAX becoming dead
```
Have not done stress mode isolation yet.

**Comment by tannergooding** [comment]
@CarolEidt, @BruceForstall. @echesakovMSFT 

Looking at the JIT Stress test logs, it seems like this along with https://github.com/dotnet/runtime/issues/2182, https://github.com/dotnet/runtime/issues/2181, and others not logged yet all started failing around the same time.

Was there any recent change that could be attributed to these?

**Comment by tannergooding** [comment]
Looking at just the "Scheduled" jobs for "master: https://dev.azure.com/dnceng/public/_build?definitionId=658&_a=summary

It was passing for ea9bfd2 (https://dev.azure.com/dnceng/public/_build/results?buildId=492108&view=ms.vss-test-web.build-test-results-tab)
It was failing for fd7a5e8 (https://dev.azure.com/dnceng/public/_build/results?buildId=493690&view=ms.vss-test-web.build-test-results-tab)

There was also a manually triggered in between those two that was passing: 0dcdbac (https://dev.azure.com/dnceng/public/_build/results?buildId=492598&view=ms.vss-test-web.build-test-results-tab)

**Comment by tannergooding** [comment]
The delta between the passing/failing should be: https://github.com/dotnet/runtime/compare/0dcdbac75870a63cb92300b6aa6a7d6fc0cdc08e...fd7a5e8cf1748b7aefa90dd8e6966af2cbb4fe8b (or https://github.com/dotnet/runtime/compare/ea9bfd213bd025db11ff7c8477d81ad822f53335...fd7a5e8cf1748b7aefa90dd8e6966af2cbb4fe8b, if you exclude the manually scheduled run)

But nothing immediately pops out as a potential culprit.

**Comment by AndyAyersMS** [comment]
The "special stress modes" enabled by JitStress=2 don't announce themselves in the log, so they are easy to overlook when doing stress mode isolation.

**Comment by BruceForstall** [comment]
@tannergooding I look at your "It was failing for" link, and it is for the "runtime-coreclr jitstress" pipeline, and I don't see any x86 failure, or any Bmi1 failure. But this issue is for gcstress+jitstress. Is the AzDO link wrong?

**Comment by AndyAyersMS** [comment]
Seems like xarch `emitOutputRRR` needs a gc kill clause at end like a lot of other emit methods. Will put up a PR.

**Comment by AndyAyersMS** [comment]
Couple of random thoughts I had while looking at this:
* I wonder if we could have a stress mode that increases the chances we will spot a missing GC kill like was the case here. Seemingly this bug has been in the code a while, but spotting it requires a combination of things: the register being killed must have a GC live reference, and we must have a GC in the window after the instruction overwrites the register with a non-GC value and before the register is set to a GC ref or is validly GC killed. Likely we saw this on x86 because the small number of allocatable registers makes killing a GC ref more likely, and running under gcstress makes observing a missing kill in a vulnerable window more likely.  The idea would be that after register allocation runs, we keep track of which registers are dead, and insert fake GC live spans into their dead regions (likely we can just set the register to null and catch most cases). Then register kills by random instructions are much more likely to be killing a GC live range than a non-GC range, and will likely set these registers to invalid GC ref values, so gcstress can spot them.
* The emitter somewhat lazily kills GC refs. Instead of killing them after the last use, it waits until the next def and/or the next non-extending IG boundary, or for things like calls where we reconcile GC state. I don't think this extension causes any particular problems, these extensions are small, but setting things up this way puts the burden on the `emitxxx` forms to kill GC refs when it seems like we could perhaps handle this differently and just kill them directly (and a bit sooner, sometimes) based on true liveness...?
* I find the overall architecture for emitting GC info somewhat confusing. It always takes me a while to figure out which bit of code is responsible for which aspects of emission; there are multiple bits of ambient state floating around in codegen, emitter, gcinfo, and lots of layering. Would be nice to have a writeup somewhere on how it is all supposed to work.

**Comment by BruceForstall** [comment]
> The emitter somewhat lazily kills GC refs. 

I think this is to reduce the size of GC info, by only killing refs as late as possible, possibly batching the kills at a block boundary. Possibly no kill happens at all if it gets replaced by another gc ref.

**Comment by tannergooding** [comment]
> Is the AzDO link wrong?

Yes, looks to be. Let me see if I can find the other jobs...
