### ISSUE TITLE
Tests failed: System.Net.Sockets.Tests.DnsEndPointTest / *

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#21924]
## Type of failures

Affected tests:
* Socket_StaticConnectAsync_HostNotFound
* Socket_StaticConnectAsync_Success
* Socket_StaticConnectAsync_ConnectionRefused
* Socket_ConnectAsyncDnsEndPoint_HostNotFound
* Socket_ConnectAsyncDnsEndPoint_Success (CI only)
* Socket_ConnectAsyncDnsEndPoint_SetSocketProperties_Success (CI only)

### Timeout

```
Timed out while waiting for connection
Expected: True
Actual:   False
at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(SocketImplementationType type)

OR

at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_ConnectionRefused()

OR

at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_HostNotFound() in /root/corefx-1213655/src/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 373
```

### Assert failure

Test `Socket_StaticConnectAsync_Success`:
```
Assert.True() Failure
Expected: True
Actual:   False
at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(SocketImplementationType type) in /root/corefx-1134004/src/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 312
```

## History of failures

Day | Build | OS | Failure | Test
-- | -- | -- | -- | --
**2017** | | | |
5/31-7/25 | N/A | Linux only | Timeout | <ul><li>51x Socket_StaticConnectAsync_HostNotFound</li><li>4x Socket_ConnectAsyncDnsEndPoint_HostNotFound,</li><li>1x Socket_StaticConnectAsync_Success</li></ul>
8/23 | 20170823.05 | Win10 | Timeout | Socket_StaticConnectAsync_Success
8/24 | 20170824.03 | Win8.1 | Timeout | Socket_StaticConnectAsync_ConnectionRefused
9/10 | 20170910.02 | Win10 | Timeout | Socket_StaticConnectAsync_Success
9/14 | 20170914.01 | Win7 | Timeout | Socket_StaticConnectAsync_Success
11/13 | 20171113.01 | Centos73 | Assert failure | Socket_StaticConnectAsync_Success
12/3 | 20171203.01 | RedHat73 | Assert failure | Socket_StaticConnectAsync_Success
12/11 | 20171211.05 | Fedora25 | Timeout | Socket_StaticConnectAsync_HostNotFound
12/23 | 20171223.02 | OSX10.12 | Timeout | Socket_StaticConnectAsync_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171223.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DnsEndPointTest~2FSocket_StaticConnectAsync_Success(type:%20APM))
1/5 | 20180105.01 | Win7 | Timeout | Socket_ConnectAsyncDnsEndPoint_HostNotFound - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180105.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DnsEndPointTest~2FSocket_ConnectAsyncDnsEndPoint_HostNotFound)
1/5 | 20180105.01 | Win7 | Timeout | Socket_StaticConnectAsync_HostNotFound - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180105.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DnsEndPointTest~2FSocket_StaticConnectAsync_HostNotFound)
1/9 | 20180109.01 | Win7 | Timeout | Socket_StaticConnectAsync_ConnectionRefused - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180109.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DnsEndPointTest~2FSocket_StaticConnectAsync_ConnectionRefused)
3/5 | 20180305.02 | Fedora26 | Assert failure | Socket_StaticConnectAsync_Success
3/6 | 20180306.01 | Win7 | Timeout | Socket_StaticConnectAsync_Success
3/6 | 20180306.01 | Win7 | Timeout | Socket_StaticConnectAsync_Success
3/8 | 20180308.06 | Fedora26 | Timeout | Socket_StaticConnectAsync_HostNotFound
3/21 | 20180321.05 | Win7 | Timeout | Socket_StaticConnectAsync_Success

# Original report

Opened on behalf of @Jiayili1

The test `System.Net.Sockets.Tests.DnsEndPointTest/Socket_StaticConnectAsync_HostNotFound` has failed.

```
Timed out while waiting for connection
    Expected: True
    Actual:   False
at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_HostNotFound() in /root/corefx/src/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 373
```
Build : Master - 20170524.01 (Portable Core Tests)
Failing configurations:
- suse.422.amd64-x64
  - Release

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170524.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DnsEndPointTest~2FSocket_StaticConnectAsync_HostNotFound

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26912004&paneView=debug&resultId=102989)

failed test: System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(type: Async)

net6.0-Linux-Release-x64-CoreCLR_release-Debian.9.Amd64.Open

Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False

Stack trace
   at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(SocketImplementationType type) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 333
~~~

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20201025.2](https://dev.azure.com/dnceng/public/_build/results?buildId=865290&view=ms.vss-test-web.build-test-results-tab&runId=27710478&paneView=debug&resultId=102941)

failed test: System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(type: Async)

net6.0-Linux-Release-x64-CoreCLR_release-Debian.9.Amd64.Open


Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(SocketImplementationType type) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 333
~~~

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210311.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1033393&view=ms.vss-test-web.build-test-results-tab&runId=32069186&resultId=103586&paneView=debug)

Failed tests:
```
System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_HostNotFound
System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_ConnectionRefused
```

**Error message:**
```
Timed out while waiting for connection
Expected: True
Actual:   False


Stack trace
   at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_HostNotFound() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 383
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210321.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1049708&view=ms.vss-test-web.build-test-results-tab&runId=32442964&resultId=103063&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200601195603-e06dc59
 -System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(type: Async)
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(SocketImplementationType type) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 341
```

**Comment by karelz** [comment]
Failures during 3/12-5/11 (incl. PRs):

Date | Build / PR | OS | Test
-- | -- | -- | --
3/21 | Official run | Alpine.312.Amd64.Open | Socket_StaticConnectAsync_Success
4/22 | Official run | Alpine.312.Amd64.Open | Socket_StaticConnectAsync_Success
4/30 | Official run | Windows.10.Amd64.Server19H1.Open | Socket_ConnectAsyncDnsEndPoint_Success
5/2 | Official run | Fedora.30.Amd64.Open | Socket_StaticConnectAsync_Success
5/12 | Official run | Alpine.312.Arm64.Open | Socket_StaticConnectAsync_Success
5/12 | Official run | OSX.1014.Amd64.Open | Socket_StaticConnectAsync_ConnectionRefused

**Comment by wfurt** [comment]
triage: no recent failures. Part of the DNS failures are infrastructure issues. If we see new failures we should open new issue to start clean. Since this depends on external services it if very difficult to make it 100% reliable.
