### ISSUE TITLE
Expression bodied property vs Jagged Arrays

### ISSUE THREAD

**Issue by Blumster** [dotnet/runtime#2193]
Hey! I hope I've opened this to the right place.

I was debugging my code and noticed that I can not set the value of the inner arrays with an expression bodied property containing a jagged array. The code compiles perfectly just doesn't act like one would expect it.

I've attached an example program that compiles and fails to set up the inner arrays.

I'm using .NET Core 3.1.

```
using System;

namespace JaggedArrayTest
{
    class Program
    {
        static int[][] JaggedArray => new int[10][];

        static void Main(string[] args)
        {
            // Property or indexer 'Program.JaggedArray' cannot be assigned to -- it is read only
            // JaggedArray = new int[10][];

            for (var i = 0; i < 10; ++i)
            {
                JaggedArray[i] = new int[10];
            }

            for (var i = 0; i < 10; ++i)
            {
                Console.WriteLine("JaggedArray[{0}] == {1}", i, JaggedArray[i] == null ? "null" : JaggedArray[i].ToString());
            }
        }
    }
}

```

**Comment by stephentoub** [comment]
Your repro is returning a new array every time you access "JaggedArray":
```C#
static int[][] JaggedArray => new int[10][];
```
If you want to have it create just once and return the same array on every access, write it instead like:
```C#
static int[][] JaggedArray { get; } = new int[10][];
```
