### ISSUE TITLE
HttpClient throws TaskCanceledException on timeout

### ISSUE THREAD

**Issue by awithy** [dotnet/runtime#21965]
HttpClient is throwing a TaskCanceledException on timeout in some circumstances. This is happening for us when the server is under heavy load. We were able to work around by increasing the default timeout. The following MSDN forum thread captures the essence of the experienced issue: https://social.msdn.microsoft.com/Forums/en-US/d8d87789-0ac9-4294-84a0-91c9fa27e353/bug-in-httpclientgetasync-should-throw-webexception-not-taskcanceledexception?forum=netfxnetcom&prof=required

Thanks

**Comment by ericsampson** [comment]
Thanks @alnikola and @scalablecory and @davidsh and @karelz and everyone else involved in this discussion/implementation, I really appreciate it.

**Comment by adydeshmukh** [comment]
Don't see a Timeout exception wrapped inside TaskCanceledException on PostAsync() call, it is returning under aggregate exception - .net version 4.5

**Comment by wfurt** [comment]
This discussion his not relevant to .NET Framework @adydeshmukh. That is completely different implementation.
