### ISSUE TITLE
System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent failing on Libraries Outerloop Windows Job

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#2198]
This just began failing last night but it's failing across enough runs that it looks like a real failure:

```
Child exception:
  Xunit.Sdk.DoesNotContainException: Assert.DoesNotContain() Failure
Found:    (filter expression)
In value: ConcurrentQueue<EventWrittenEventArgs> [EventWrittenEventArgs { ActivityId = 00000000-0000-0000-0000-000000000000, Channel = None, EventId = 0, EventName = "EventSourceMessage", EventSource = EventSource(System.Threading.Tasks.TplEventSource, 2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5), ... }]
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.<>c.<DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0() in /_/src/libraries/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs:line 594

Child process:
  System.Threading.Tasks.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<>c Void <DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0()
```

Builds
- https://dev.azure.com/dnceng/public/_build/results?buildId=496826

Test Runs
- netcoreapp5.0-Windows_NT-Release-x64-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-61052b7-20190723211353
- netcoreapp5.0-Windows_NT-Release-x64-Windows.10.Amd64.Server19H1.Open
- netcoreapp5.0-Windows_NT-Release-x64-Windows.10.Amd64.ServerRS5.Open
- netcoreapp5.0-Windows_NT-Release-x64-Windows.7.Amd64.Open
- netcoreapp5.0-Windows_NT-Release-x64-Windows.81.Amd64.Open
- netcoreapp5.0-Windows_NT-Release-x86-Windows.10.Amd64.Server19H1.Open
- netcoreapp5.0-Windows_NT-Release-x86-Windows.10.Amd64.ServerRS5.Open
- netcoreapp5.0-Windows_NT-Release-x86-Windows.7.Amd64.Open
- netcoreapp5.0-Windows_NT-Release-x86-Windows.81.Amd64.Open

**Comment by stephentoub** [comment]
EventID == 0 means there's some kind of EventSource error happening. We'll need to see more of the event details to know what's wrong. If I can repro locally when I'm back at my computer, I'll see, otherwise we can submit an update to the test to print out more details overall of that "...".

**Comment by stephentoub** [comment]
@jaredpar, how do I see on what build configurations this is failing? e.g. in the above queues you listed, are these all using a release coreclr, or a checked coreclr, or a mix?  I haven't reproduced it locally yet.

**Comment by wfurt** [comment]
This now seems to fails with NRE on Linux & OSX

```
  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Tests (found 177 of 719 test cases)
  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 2)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.Tracing.EventWrittenEventArgs.get_Keywords() in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs:line 4707
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.<>c.<DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0() in /_/src/libraries/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs:line 602
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 91
    System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          System.NullReferenceException: Object reference not set to an instance of an object.
        /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs(4707,0): at System.Diagnostics.Tracing.EventWrittenEventArgs.get_Keywords()
        /_/src/libraries/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs(602,0): at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.<>c.<DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0()
        
        Child process:
          System.Threading.Tasks.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<>c Void <DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0()
        
        
  Finished:    System.Threading.Tasks.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Tasks.Tests  Total: 181, Errors: 0, Failed: 1, Skipped: 0, Time: 12.973s

```

**Comment by jaredpar** [comment]
@stephentoub 

> how do I see on what build configurations this is failing?  e.g. in the above queues you listed, are these all using a release coreclr, or a checked coreclr, or a mix?

Not sure there is a good way from the test run name. The name listed there is the label our YML adds as it expands out the templates. I agree it's unclear at a glance if the "Release" portion refers to libraries, runtime or both. 

@ViktorHofer is there a way to decipher these in their current form?

**Comment by wfurt** [comment]
You can do this in Kusto explorer. (and that also give you stack traces)
```
Jobs | project JobId, Name, Source, Type, Started ,Finished,  QueueName, Properties |where Source contains "runtime" and  Started >= ago(90d) | join kind=inner (TestResults | project Method, Result, JobId, WorkItemName, WorkItemFriendlyName , EventId , Arguments, Type , Exception , StackTrace , Message , Duration, Reason, Attempt , Traits, WorkItemId   | where   Result == "Fail" and Method contains "DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent"  ) on JobId | join kind=inner (WorkItems | project JobId, MachineName, WorkItemId) on WorkItemId |  order by Finished desc  nulls last
```

I currently see 302 failures. In the last 90 days, it only failed on 2020-01-25 11:36:00.1750000 GMT and consistently after. It is failing on mix of OS and both Release and Debug builds.

**Comment by wfurt** [comment]
One more note, that if you have a link to console like:
https://helix.dot.net/api/2019-06-17/jobs/33f64f22-23da-4692-8be1-b87e3cd3473d/workitems/System.Threading.Tasks.Tests/console

going all the way up to above `workitems` gives you basic info:
https://helix.dot.net/api/2019-06-17/jobs/33f64f22-23da-4692-8be1-b87e3cd3473d/

`Properties` will have OS, Configuration (release/debug) and Architecture.

The date in the link is API version and it is now the same for all jobids.

**Comment by ViktorHofer** [comment]
>@jaredpar, how do I see on what build configurations this is failing? e.g. in the above queues you listed, are these all using a release coreclr, or a checked coreclr, or a mix? I haven't reproduced it locally yet.

Libraries Outerloop only runs on coreclr Release at the moment: https://github.com/dotnet/runtime/blob/ec7aac66c36bf12bf649b803568ca882d052205b/eng/pipelines/libraries/outerloop.yml#L23.

**Comment by jaredpar** [comment]
> One more note, that if you have a link to console like:

Working on getting console log links into the tooling I've been using to file bugs like this. Want to minimize distance between issues and actionable data.

**Comment by stephentoub** [comment]
I'll take a look at the get_Keywords null ref.

**Comment by wfurt** [comment]
I do agree @jaredpar. I know some parts you can get via REST but it would be nice to have essential info either in build output or console itself. OS/Container and link to tested bits would be nice IMHO.

**Comment by safern** [comment]
> in the above queues you listed, are these all using a release coreclr,

I just put up a PR to include the runtime and configuration in the test run so that people don't get confused: https://github.com/dotnet/runtime/pull/12715

**Comment by stephentoub** [comment]
The PRs I put up to gather more data resulted in us catching the problem.  Something is going on with EventSource.  Closing this in favor of https://github.com/dotnet/runtime/issues/31675 that has the updated error.
