### ISSUE TITLE
Linux - Enforce running as root

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#2204]
How do I enforce a .NET Core app to run as root under Linux? The application manifest file is only valid for targeting Windows.

**Comment by jkotas** [comment]
Linux does not have equivalent of Windows application manifests. 

If you need launch your app as root on Linux, you need to do it explicitly, e.g. via `sudo <your app>`.

**Comment by Symbai** [comment]
I've seen Linux apps enforcing root rights using policyconfig & desktop file, something like this https://unix.stackexchange.com/questions/411251/unable-to-execute-gui-application-as-a-different-user-using-pkexec. When opening the application via double click in Ubuntu it prompts for root login. No sudo is required. Isn't that an equivalent? Is there a way this can be added to .NET Core Linux applications?

**Comment by jkotas** [comment]
You should be able to create the Linux desktop policy for .NET Core app just like you create it for any other app.

**Comment by wfurt** [comment]
The `double click` depends on what UI  and application you running and there is no general solution for Linux AFAIK. (to for example work from shell or systemd) 
You can set SUID bit on your app to always grant it root access but of course that creates security weakness as access is granted automatically.  
You can also check within the  app and fail with an explanation if the application was not started elevated (the equivalent of"run as" from windows)  

I agree with the comment above that there is nothing really .NET specific. 

cc @tmds in case there are other suggestions.

**Comment by tmds** [comment]
> I've seen Linux apps enforcing root rights using policyconfig & desktop file, something like this https://unix.stackexchange.com/questions/411251/unable-to-execute-gui-application-as-a-different-user-using-pkexec. When opening the application via double click in Ubuntu it prompts for root login. No sudo terminal is required. Isn't that an equivalent? Is there a way this can be added to .NET Core Linux applications?

If you want to create a pop-up that asks for root credentials, you do try something like this:
```cs
int Main:
if (!RunningAsRoot)
{
     string commandLine = GetCommandLine();
     var process = Process.Start("pkexec", commandLine);
     return process.ExitCode;
}
else
{
    ...
}

string GetCommandLine:
    // based on https://github.com/tmds/Tmds.ExecFunction/blob/f5dd7db58a274bf634ff331836637fb4c93be0ce/src/Tmds.ExecFunction/ExecFunction.cs#L201
```

**Comment by Symbai** [comment]
@tmds Thanks, this is what I want.
