### ISSUE TITLE
[BlockingCollection] Add TimeSpan parameter to TryAdd and TryTake (and a few questions)

### ISSUE THREAD

**Issue by Nippius** [dotnet/runtime#22052]
Hi!

I would like to start contributing to open source projects and since I love C# and the .NET environment, this looks like a great place to start. However, I'm quite new to all this and so, I have a few questions on how to proceed.

First of all, what I want to do is relatively simple. I want to add the following methods to the
BlockingCollection classe:

```c#
public bool TryAdd(out T item, TimeSpan timeout, CancellationToken cancellationToken);
public bool TryTake(out T item, TimeSpan timeout, CancellationToken cancellationToken);
```

The original reason for this is that I usually prefer using a TimeSpan object wherever possible since it makes the intention clear and recently had to use BlockingCollection for a project and noticed that some of the Try* methods don't have a overload that takes a TimeSpan parameter. Since this is an easy addition (unless I'm missing something) I though it would be a nice way to start contributing. Besides, it adds consistency.

Also, I know this could be implemented as an extension method but that defeats the purpose of contributing :)

Regarding my questions.

- I need to open a issue for every pull request? If so, can I use this one or should I open new one?
- Since this is an API change, do I need to do something special besides opening the issue and if approved, submit the PR?
- What are the naming conventions for testing method names? BlockingCollectionTest have some of the following:
    - TestConcurrentAddAnyTakeAny
    - TestAddAnyTakeAny_Longrunning
    - Test17_AddExceptions

Is there anything else I'm missing?

Thank you!

**Comment by layomia** [comment]
Thanks for opening this issue. Given that there are related overloads that provide the desired functionality, I'll close this issue. As you mention, an extension method or wrapper can be written to get the specific overloads you are requesting. We'd like to see a significant reason to add new API, e.g. a blocked scenario, potential perf improvements, or great community demand.
