### ISSUE TITLE
System.Data.Common classes should implement an interface containing the async methods

### ISSUE THREAD

**Issue by adriangodong** [dotnet/runtime#22071]
`System.Data.Common.DbConnection` and `System.Data.Common.DbCommand` are abstract classes that declares additional async methods not defined in `System.Data.IDbConnection` and `System.Data.IDbCommand`, respectively.

This makes migration towards async methods and/or mocking the async methods for testing difficult. I am proposing we introduce an intermediary interface `IDbConnectionAsync` that is derived from `IDbConnection` and will be implemented by `DbConnection`. Similarly, introduce `IDbCommandAsync` between `IDbCommand` and `DbCommand`. These interfaces will contain `public async` methods that is missing from the original interfaces.

## Rationale and Usage

Consider the following snippet illustrating an `IDbCommand` factory. There are two factory methods, one for regular and one for the async variant. I've included unit test methods to verify the factory calls `CreateCommand()` and `Open()`.

```c#
public class CommandFactory
{
    public IDbCommand CreateCommand(IDbConnection connection)
    {
        var command = connection.CreateCommand();
        connection.Open();
        return command;
    }

    public async Task<DbCommand> Create​CommandAsync(DbConnection connection)
    {
        var command = connection.CreateCommand();
        await connection.OpenAsync();
        return command;
    }
}

[TestClass]
public class CommandFactoryTests
{
    [TestMethod]
    public void TestCreateCommand()
    {
        // Arrange
        var commandFactory = new CommandFactory();
        var mockConnection = new Mock<IDbConnection>();
        var mockCommand = new Mock<IDbCommand>();
        mockConnection
            .Setup(mock => mock.CreateCommand())
            .Returns(mockCommand.Object);

        // Act
        var command = commandFactory.CreateCommand(mockConnection.Object);

        // Assert
        Assert.IsNotNull(command);
        Assert.AreEqual(mockCommand.Object, command);
        mockConnection.Verify(mock => mock.Open(), Times.Once);
    }

    [TestMethod]
    public async Task TestCreateCommandAsync()
    {
        // Arrange
        var commandFactory = new CommandFactory();
        var mockConnection = new Mock<DbConnection>();
        var mockCommand = new Mock<DbCommand>();
        mockConnection
            .Setup(mock => mock.CreateDbCommand()) // problematic line
            .Returns(mockCommand.Object);

        // Act
        var command = await commandFactory.Create​CommandAsync(mockConnection.Object);

        // Assert
        Assert.IsNotNull(command);
        Assert.AreEqual(mockCommand.Object, command);
        mockConnection.Verify(mock => mock.OpenAsync(), Times.Once);
    }
}
```

The regular variant passed with flying colors. The async variant, on the other hand, failed to compile because `CreateDbCommand()` method in `DbConnection` is `protected`, thus not accessible to the mocking library. The workaround for this is to create an abstract class that derives from `DbCommand` and implement `CreateDbCommand` and return an instance of `Mock<DbCommand>`. This can be easily avoided if there's an interface definition that the mocking library can use instead of the abstract class.

`DbCommand` has a similar problem, all overloads of `ExecuteReaderAsync()` eventually calls non-mockable `ExecuteDbDataReader()` because it is a `protected` method.

Lastly, while I believe I can mock `DbDataReader` easily, it would be great to follow the same hierarchy by having `IDataReaderAsync`. Implementing this will also avoid `IDbCommand` importing `System.Data.Common`. 

## Proposed API

```c#
public interface IDbConnection
{
    // as-is
}

public interface IDbConnectionAsync : IDbConnection
{
    new System.Data.IDbCommandAsync Create​Command ();
    System.Threading.Tasks.Task OpenAsync ();
    System.Threading.Tasks.Task OpenAsync (System.Threading.CancellationToken cancellationToken);
}

public abstract class DbConnection : IDbConnectionAsync
{
    ...
}

public interface IDbCommand
{
    // as-is
}

public interface IDbCommandAsync : IDbCommand
{
    Task<int> ExecuteNonQueryAsync (CancellationToken cancellationToken);
    Task<int> ExecuteNonQueryAsync ();
    Task<IDataReaderAsync> ExecuteReaderAsync ();
    Task<IDataReaderAsync> ExecuteReaderAsync (CommandBehavior behavior);
    Task<IDataReaderAsync> ExecuteReaderAsync (CommandBehavior behavior, CancellationToken cancellationToken);
    Task<IDataReaderAsync> ExecuteReaderAsync (CancellationToken cancellationToken);
    Task<object> ExecuteScalarAsync (CancellationToken cancellationToken);
    Task<object> ExecuteScalarAsync ();
}

public abstract class DbCommand : IDbCommandAsync
{
    ...
}
```

## Details

* The async interfaces should include async public methods defined in the abstract classes but not defined in the base interfaces.
* External API changes will be minimal. We can implement `IDbConnection.CreateCommand` and `IDbConnectionAsync.CreateCommand` explicitly on `DbConnection` and maintain `DbConnection.CreateCommand` signature -- it will return the abstract class `DbCommand`. `DbCommand.ExecuteReaderAsync` overloads can use similar approach, albeit with a small hack because of invariant `Task<T>`.
* Proposed change diff: https://github.com/dotnet/corefx/compare/master...adriangodong:system-data-async

[EDIT] Added C# syntax highlighting by @karelz

**Comment by roji** [comment]
The System.Data interfaces in general have been more or less abandoned since .NET Framework 2.0 (IIRC) precisely because it was impossible to evolve them without breaking existing implementations; all modern consumption of ADO.NET (System.Data) happens through the abstract base classes instead. What would be the advantage of bringing the old interfaces back by adding default implementations to them? If people are looking to mock, why not mock the abstract base classes?

**Comment by ajcvickers** [comment]
System.Data and many applications built on System.Data assume that the interfaces can be cast to the base types. This greatly reduces the usefulness of the interfaces since in many cases different implementations than expected with result in exceptions. This means that, even with default interface implementations now available, we still don't plan to evolve these interfaces.
