### ISSUE TITLE
Nullable with TaskCompletionSource

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#2210]
Not sure if there is anything tracking nullable changes so filing this one off issue.

`TrySetResult` and `SetResult` should allow null, Task was changed to allow null
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs#L368 
and `TaskCompletionSource` calls that method.

cc @stephentoub

**Comment by stephentoub** [comment]
If your TResult is nullable, you can set something that's null. I'm not understanding the concern.
