### ISSUE TITLE
Question: How to store Activity.Id before start it?

### ISSUE THREAD

**Issue by shawnzxx** [dotnet/runtime#2213]
### Context:
I have a special requirement to store "dependencyActivity.id" in a transaction, see a line of code attached below:
**await SaveOutgoingEventAsync(String.Empty);**
I am currently storing an empty string as a temp version of dependencyActivity.id, and update it to the actual value of dependencyActivity.Id after I start the dependencyActivity. Use this way to pass down the parent and child relationship to the next external process, dependencyActivity.Id as my downstream service's operationParentId.

### Question:
1: What is the best practice to store dependent id before I start and stop telemetry operation?

### Code:
```
public async Task<ReturnOrderDto> SubmitOrderAsync(SubmitOrderDto order)
{
    var executionStrategy = _orderDbContext.Database.CreateExecutionStrategy();
    await executionStrategy.ExecuteAsync(async () =>
    {
        using (var transaction = _orderDbContext.Database.BeginTransaction(IsolationLevel.ReadCommitted))
        {
            //Some processing code
            ......
            ......

            //Store empty string as dependencyActivity.Id in database
            await SaveOutgoingEventAsync(String.Empty);
            // Commit incoming, business and outgoing entities together in outbox pattern
            await transaction.CommitAsync();
        }
    });

    var dependencyActivity = new Activity("Publish Message");
    dependencyActivity.SetParentId(Activity.Current.Id);
    dependencyActivity.Start();
    var operation = _telemetryClient.StartOperation<DependencyTelemetry>(dependencyActivity);
    var messageHeader = new KafkaMessageHeader(dependencyActivity.TraceId.ToString(), dependencyActivity.Id);
    kafkaMessage.UpdateHeader(messageHeader);
    await _publisher.ProduceAsync(kafkaMessage);
    _telemetryClient.StopOperation(operation);
    
    //update previous stored empty Id to dependencyActivity.Id
    outgoingEvent.UpdateOutgoingIntegrationEvent(dependencyActivity.TraceId.ToString(), dependencyActivity.Id);
    outgoingEvent.MarkAsSent();
    await _outgoingEventRepository.SaveChangesAsync();

    return new ReturnOrderDto { OrderId = _orderEntity.OrderId };
}
```

**Comment by noahfalk** [comment]
A typical order of operations looks like:

1) Start Activity
2) Record the activity information
3) Do some work
4) Stop the activity

It is a domain specific judgement what work belongs inside the scope of the activity (step 3). The ID is created by invoking start so it is impossible to log the id before Start() has occurred, but you can delay it until later if you want to (as your example does).

The main risk of doing it later is that if the operation fails you might want the ID to diagnose but not have it. For example if await _publisher.ProduceAsync(kafkaMessage); threw an exception then outgoingEvent.UpdateOutgoingIntegrationEvent(…) would be skipped. You can either try to handle such failures (try/finally), decide that you don't need the ID in failure cases, or move the logging to occur before the failure.

Was that the info you were looking for or something else?


One other random note, "dependencyActivity.SetParentId(Activity.Current.Id);" isn't needed, this will happen by default when an Activity is started.

**Comment by noahfalk** [comment]
Going to close this assuming the question is answered : ) If not we can always re-open.
