### ISSUE TITLE
Wildcard question marks don't collapse right on Unix

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#22168]
`?` runs before periods and end-of-string should collapse. When they are there they are `.{0,n}` in regex-speak. So `Foo???.txt` would be `Foo.{0,3}\.txt` as a regex. Not sure if something equivalent is possible with `fnmatch(3)`.

See discussion in dotnet/runtime#22123 

Matching behavior is described [here](https://blogs.msdn.microsoft.com/jeremykuhne/2017/06/04/wildcards-in-windows/).

**Comment by Jozkee** [comment]
@JeremyKuhne my understanding is that the only thing left to do here is re-enable the tests, is that correct?
And the same applies for https://github.com/dotnet/runtime/issues/22169 and https://github.com/dotnet/runtime/issues/22170.

**Comment by JeremyKuhne** [comment]
I believe so.
