### ISSUE TITLE
[uapaot] ComAwareEventInfo and ComEventInterfaceAttribute duplicated

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#22174]
See https://github.com/dotnet/corefx/pull/20697/files#r120782465

ComAwareEventInfo and ComEventInterfaceAttribute should be deleted in System.Private.Interop, and we should always use the impl in corefx.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Is this still worth fixing? I was about to put out a PR for moving `ComEventInterfaceAttribute` into `System.Runtime.InteropServices`? It seems like the rebuild will need to happen anyways with .NET5 so I assume this is fine to move out of SPCL.

**Comment by AaronRobinsonMSFT** [comment]
Decided this is not worth addressing. Closing.
