### ISSUE TITLE
Framework dependent self contained windows app locks the file

### ISSUE THREAD

**Issue by Logerfo** [dotnet/runtime#2226]
## Steps to reproduce
1. Open a framework dependent self contained windows application. The contents will be extracted into something like `%temp%/.net/$AppName/$RandomKey`.
2. Try to rename the original file (not the temp one) with the application open. It will do just fine, since the file is not locked.
3. Close the application.
4. Open the application again (using the original file, not the temp one). Notice that the extraction process will not occur again.
5. Try to rename the original file again.

## Expected behavior
- Just like the first time, the renaming process should happen gracefully.

## Actual behavior
- The renaming process will fail, since the file is being used by another process (itself).

## Why it matters
- Self renaming operation is often part of application binary self updating processes.

## Disclaimer
- I'm not sure if it's necessary for the self contained application to be framework dependent in order to reproduce this issue.

**Comment by jkotas** [comment]
Looks like a dup of #1260. cc @swaroop-sridhar

**Comment by Logerfo** [comment]
Thanks, @jkotas! I'm close this one.
