### ISSUE TITLE
Understand disallowed PInvoke in System.Drawing.Primitives

### ISSUE THREAD

**Issue by mellinoe** [dotnet/runtime#22275]
System.Drawing.Primitives uses `user32.dll!GetSysColor`, which seems to be disallowed in OneCore. Our Windows Nano runs do not fail, but we should still understand whether we need to avoid calling this function on Windows Nano. If we can't call the function, we should simply fall back to the cross-platform implementation, which has a hard-coded color table.

**Comment by safern** [comment]
@danmosemsft it seems like we can close this issue?

**Comment by danmosemsft** [comment]
Yup.
