### ISSUE TITLE
[Mac] Tests failed: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#22287]
## Type of failures

Note: Might be related to dotnet/corefx#23364 (UWP) for some overlapping tests.

### Operation timed out

Tests returning only this error:

Test Name | # | Test Type
-- | -- | --
SendRecv_Stream_TCP_AlternateBufferAndBufferList | 6x | System.Net.Sockets.Tests: SendReceiveApm / SendReceiveSpanSyncForceNonBlocking / SendReceiveMemoryNativeTask
BufferZeroCountThenNormal_ZeroCountIgnored | 3x | System.Net.Sockets.Tests.SendPacketsAsync
SendTimesOut_Throws | 3x | System.Net.Sockets.Tests.TimeoutTest
SendPacketsElement_FileLargeOffset_Throws | 2x | System.Net.Sockets.Tests.SendPacketsAsync
ClientAsyncAuthenticate_MismatchProtocols_Fails | 2x | System.Net.Security.Tests.ClientAsyncAuthenticateTest
BeginConnectV6IPAddressToV6Host_Success | 2x | System.Net.Sockets.Tests.DualModeBeginConnectToIPAddress
ConnectV6IPEndPointToV6Host_Success | 2x | System.Net.Sockets.Tests.DualModeConnectToIPEndPoint
NormalBufferRange_Success | 1x | System.Net.Sockets.Tests.SendPacketsAsync
BeginConnectV6IPEndPointToV6Host_Success | 1x | System.Net.Sockets.Tests.DualModeBeginConnectToIPEndPoint
ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success | 1x | System.Net.Security.Tests.ClientAsyncAuthenticateTest
BufferZeroCount_Ignored | 1x | System.Net.Sockets.Tests.SendPacketsAsync
ConnectV6IPEndPointToDualHost_Success | 1x | System.Net.Sockets.Tests.DualModeConnectToIPEndPoint
SendPacketsElement_MissingFile_Throws | 1x | System.Net.Sockets.Tests.SendPacketsAsync
SendFile_Synchronous | 1x | System.Net.Sockets.Tests.SendFileTest
SendPacketsElement_FileMultiPart_Success | 1x | System.Net.Sockets.Tests.SendPacketsAsync
ConnectV6IPAddressToDualHost_Success | 1x | System.Net.Sockets.Tests.DualModeConnectToIPAddress
Accept_Success | 1x | System.Net.Sockets.Tests.AcceptApm
EmptyBuffer_Ignored | 1x | System.Net.Sockets.Tests.SendPacketsAsync
NormalBuffer_Success | 1x | System.Net.Sockets.Tests.SendPacketsAsync
SendPacketsElement_EmptyFileName_Throws | 1x | System.Net.Sockets.Tests.SendPacketsAsync
Connect_Success | 1x | System.Net.Sockets.Tests.ConnectEap
SendPacketsElement_FilePart_Success | 1x | System.Net.Sockets.Tests.SendPacketsAsync
BeginConnectV6IPAddressToDualHost_Success | 1x | System.Net.Sockets.Tests.DualModeBeginConnectToIPAddress

Test `BufferZeroCountThenNormal_ZeroCountIgnored`:
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Operation timed out [::1]:50462
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4589
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 825
at System.Net.Sockets.Tests.SendPacketsAsync.BufferZeroCountThenNormal_ZeroCountIgnored(SocketImplementationType type) in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs:line 211
```

### Connection refused

Tests returning only this error:

Test Name | # | Test Type
-- | -- | --
GetContext_InvalidRequest_DoesNotGetContext | 14x | GetContext_InvalidRequest_DoesNotGetContext
StatusDescription_GetWithCustomStatusCode_ReturnsExpected | 6x | System.Net.Tests.HttpListenerResponseHeadersTests
KeepAlive_GetProperty_ReturnsExpected | 2x | System.Net.Tests.HttpListenerRequestTests
ContentEncoding_GetProperty_ReturnsExpected | 2x | System.Net.Tests.HttpListenerRequestTests
Cookies_SetAndSend_ClientReceivesExpectedHeaders | 2x | System.Net.Tests.HttpListenerResponseCookiesTests
DualModeConnect_LoopbackDnsToHost_Helper | 1x | System.Net.Sockets.Tests.DualModeConnectToHostString
DualModeConnect_DnsEndPointToHost_Helper | 1x | System.Net.Sockets.Tests.DualModeConnectToDnsEndPoint
DualModeConnect_IPAddressListToHost_Success | 1x | System.Net.Sockets.Tests.DualModeConnectToIPAddressArray
AppendHeader_NullOrEmptyName_ThrowsArgumentNullException | 1x | System.Net.Tests.HttpListenerResponseHeadersTests
Cookies_SetInHeader_ClientReceivesExpectedHeaders | 1x | System.Net.Tests.HttpListenerResponseCookiesTests
IsWebSocketRequest_GetProperty_ReturnsExpected | 1x | System.Net.Tests.HttpListenerRequestTests
Redirect_Invoke_SetsRedirectionProperties | 1x | System.Net.Tests.HttpListenerResponseTests
SetCookie_ValidCookie_AddsCookieToCollection | 1x | System.Net.Tests.HttpListenerResponseCookiesTests
StatusDescription_SetCustom_Success | 1x | System.Net.Tests.HttpListenerResponseHeadersTests
StatusDescription_SetNull_ThrowsArgumentNullException | 1x | System.Net.Tests.HttpListenerResponseHeadersTests
ContentLength64_NotSetAndGetAfterSendingHeaders_ReturnValueDependsOnStatusCode | 1x | System.Net.Tests.HttpListenerResponseHeadersTests
CopyFrom_AllValues_ReturnsClone | 1x | System.Net.Tests.HttpListenerResponseTests
TransportContext_GetChannelBinding_ReturnsExpected | 1x | System.Net.Tests.HttpListenerRequestTests

Test `StatusDescription_GetWithCustomStatusCode_ReturnsExpected`:
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1300
at   System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress   socketAddress) in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line   4589
at System.Net.Sockets.Socket.Connect(EndPoint   remoteEP) in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line   825
at   System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line   930
--- End of stack trace from previous location where exception was   thrown ---
at   System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line   940
at System.Net.Sockets.Socket.Connect(String   host, Int32 port) in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line   889
at   System.Net.Tests.HttpListenerFactory.GetConnectedSocket() in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.HttpListener/tests/HttpListenerFactory.cs:line   156
at   System.Net.Tests.HttpListenerResponseTestBase..ctor() in   /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.HttpListener/tests/HttpListenerResponseTests.cs:line   21
at   System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean   skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in   /Users/buildagent/agent/_work/153/s/src/mscorlib/src/System/RtType.cs:line   4840
```

## History of failures

Day | Build | OS | Error message | Test
-- | -- | -- | -- | --
5/3 | 20170503.04 | OSX10.12 | Connection refused | ContentEncoding_GetProperty_ReturnsExpected
6/27 | 20170627.03 | OSX10.12 | Operation timed out | ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success
7/7 | 20170707.02 | OSX10.12 | Operation timed out | BufferZeroCountThenNormal_ZeroCountIgnored
7/18 | 20170718.02 | OSX10.13 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
7/20 | 20170720.01 | OSX10.12 | Connection refused | SetCookie_ValidCookie_AddsCookieToCollection
7/21 | 20170721.01 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
8/2 | 20170802.01 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
8/18 | 20170818.02 | OSX10.12 | Connection refused | ContentEncoding_GetProperty_ReturnsExpected
8/23 | 20170823.03 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
8/25 | 20170825.02 | OSX10.12 | Connection refused | Cookies_SetInHeader_ClientReceivesExpectedHeaders
8/31 | 20170831.01 | OSX10.12 | Connection refused | StatusDescription_GetWithCustomStatusCode_ReturnsExpected
8/31 | 20170831.01 | OSX10.12 | Connection refused | IsWebSocketRequest_GetProperty_ReturnsExpected
9/2 | 20170902.02 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
9/4 | 20170904.02 | OSX10.12 | Operation timed out | SendRecv_Stream_TCP_AlternateBufferAndBufferList
9/8 | 20170908.02 | OSX10.12 | Connection refused | KeepAlive_GetProperty_ReturnsExpected
9/9 | 20170909.01 | OSX10.12 | Operation timed out | SendPacketsElement_FileLargeOffset_Throws
9/13 | 20170913.01 | OSX10.12 | Connection refused | StatusDescription_SetNull_ThrowsArgumentNullException
9/18 | 20170918.03 | OSX10.12 | Operation timed out | BufferZeroCount_Ignored
9/20 | 20170920.02 | OSX10.12 | Operation timed out | ConnectV6IPEndPointToDualHost_Success
9/20 | 20170920.03 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
9/21 | 20170921.01 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
9/22 | 20170922.01 | OSX10.12 | Operation timed out (exception assert) | SendPacketsElement_MissingFile_Throws
9/25 | 20170925.03 | OSX10.12 | Operation timed out (exception assert) | ClientAsyncAuthenticate_MismatchProtocols_Fails
9/26 | 20170926.05 | OSX10.12 | Connection refused  | Cookies_SetAndSend_ClientReceivesExpectedHeaders
10/10 | 20171010.03 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
10/11 | 20171011.02 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
10/13 | 20171013.01 | OSX10.12 | Operation timed out | BufferZeroCountThenNormal_ZeroCountIgnored
10/20 | 20171020.01 | OSX10.12 | Connection refused | StatusDescription_SetCustom_Success
10/20 | 20171020.02 | OSX10.12 | Connection refused | StatusDescription_GetWithCustomStatusCode_ReturnsExpected
10/21 | 20171021.02 | OSX10.12 | Connection refused | Redirect_Invoke_SetsRedirectionProperties
10/25 | 20171025.05 | OSX10.12 | Connection refused | StatusDescription_GetWithCustomStatusCode_ReturnsExpected
10/28 | 20171028.03 | OSX10.12 | Connection refused | StatusDescription_GetWithCustomStatusCode_ReturnsExpected
10/29 | 20171029.01 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
10/30 | 20171030.01 | OSX10.12 | Operation timed out | SendRecv_Stream_TCP_AlternateBufferAndBufferList
10/30 | 20171030.01 | OSX10.12 | Connection refused | AppendHeader_NullOrEmptyName_ThrowsArgumentNullException
10/30 | 20171030.02 | OSX10.12 | Connection refused | DualModeConnect_IPAddressListToHost_Success
10/30 | 20171030.02 | OSX10.12 | Operation timed out | BufferZeroCountThenNormal_ZeroCountIgnored
10/31 | 20171031.01 | OSX10.12 | Operation timed out | BeginConnectV6IPAddressToV6Host_Success
11/1 | 20171101.03 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
11/2 | 20171102.03 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext
11/29 | 20171129.01 | OSX10.12 | Connection refused | DualModeConnect_DnsEndPointToHost_Helper
12/7 | 20171207.02 | OSX10.12 | Operation timed out | SendTimesOut_Throws
12/10 | 20171210.01 | OSX10.12 | Operation timed out | SendPacketsElement_FileLargeOffset_Throws
12/10 | 20171210.03 | OSX10.12 | Connection refused | KeepAlive_GetProperty_ReturnsExpected
12/10 | 20171210.03 | OSX10.12 | Operation timed out | BeginConnectV6IPEndPointToV6Host_Success
12/13 | 20171213.10 | OSX10.12 | Connection refused | DualModeConnect_LoopbackDnsToHost_Helper
12/24 | 20171224.01 | OSX10.12 | Operation timed out | SendRecv_Stream_TCP_AlternateBufferAndBufferList - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171224.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveApm~2FSendRecv_Stream_TCP_AlternateBufferAndBufferList(listenAt:%20::1))
12/24 | 20171224.01 | OSX10.12 | Operation timed out | SendTimesOut_Throws - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171224.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.TimeoutTest~2FSendTimesOut_Throws(forceNonBlocking:%20False))
1/4 | CI | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext - [link](https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/d0572e85122eaf8e180c52e196997ab96195e26c/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.InvalidClientRequestTests~2FGetContext_InvalidRequest_DoesNotGetContext)
1/6 | 20180106.01 | OSX10.12 | Operation timed out | SendFile_Synchronous - only in [catastrophic failure logs](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180106.01/workItem/System.Net.Sockets.Tests/wilogs)
1/8 | 20180108.02 | OSX10.12 | Connection refused | GetContext_InvalidRequest_DoesNotGetContext - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180108.02/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.InvalidClientRequestTests~2FGetContext_InvalidRequest_DoesNotGetContext)
1/10 | 20180110.03 | OSX10.12 | Operation timed out | SendRecv_Stream_TCP_AlternateBufferAndBufferList - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180110.03/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveMemoryNativeTask~2FSendRecv_Stream_TCP_AlternateBufferAndBufferList(listenAt:%20::1))
1/10 | 20180110.03 | OSX10.12 | Operation timed out | SendPacketsElement_FileMultiPart_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180110.03/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendPacketsAsync~2FSendPacketsElement_FileMultiPart_Success(type:%20APM))
1/11 | 20180111.02 | OSX10.12 | Connection refused | ContentLength64_NotSetAndGetAfterSendingHeaders_ReturnValueDependsOnStatusCode - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180111.02/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerResponseHeadersTests~2FContentLength64_NotSetAndGetAfterSendingHeaders_ReturnValueDependsOnStatusCode(statusCode:%20204,%20expectedContentLength64:%200,%20expectedNumberOfBytes:%20114))
1/19 | 20180119.02 | OSX10.12 | Operation timed out | ConnectV6IPAddressToDualHost_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DualModeConnectToIPAddress~2FConnectV6IPAddressToDualHost_Success)
1/19 | 20180119.04 | OSX10.12 | Operation timed out | Accept_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.04/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.AcceptApm~2FAccept_Success(listenAt:%20::1))
1/19 | 20180119.06 | OSX10.12 | Operation timed out | EmptyBuffer_Ignored - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.06/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendPacketsAsync~2FEmptyBuffer_Ignored(type:%20APM))
1/21 | 20180121.01 | OSX10.12 | Operation timed out | NormalBuffer_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendPacketsAsync~2FNormalBuffer_Success(type:%20APM))
1/23 | 20180123.04 | OSX10.12 | Operation timed out | SendPacketsElement_EmptyFileName_Throws - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.04/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendPacketsAsync~2FSendPacketsElement_EmptyFileName_Throws(type:%20APM))
1/24 | 20180124.06 | OSX10.12 | Connection refused | StatusDescription_GetWithCustomStatusCode_ReturnsExpected - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180124.06/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerResponseHeadersTests~2FStatusDescription_GetWithCustomStatusCode_ReturnsExpected(statusCode:%20407,%20expectedDescription:%20%5C%22Proxy%20Authentication%20Required%5C%22))
1/26 | 20180126.07 | OSX10.12 | Operation timed out | ClientAsyncAuthenticate_MismatchProtocols_Fails - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180126.07/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ClientAsyncAuthenticateTest~2FClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol:%20Tls11,%20clientProtocol:%20Tls12,%20expectedException:%20typeof(System.IO.IOException)))
2/2 | 20180202.05 | OSX10.12 | Connection refused | CopyFrom_AllValues_ReturnsClone - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180202.05/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerResponseTests~2FCopyFrom_AllValues_ReturnsClone)
2/6 | 20180206.02 | OSX10.12 | Connection refused | StatusDescription_GetWithCustomStatusCode_ReturnsExpected - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180206.02/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerResponseHeadersTests~2FStatusDescription_GetWithCustomStatusCode_ReturnsExpected(statusCode:%20501,%20expectedDescription:%20%5C%22Not%20Implemented%5C%22))
2/16 | 20180216.01 | OSX10.12 | Operation timed out | ConnectV6IPEndPointToV6Host_Success
2/25 | 20180225.01 | OSX10.12 | Operation timed out | Connect_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180225.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.ConnectEap~2FConnect_Success(listenAt:%20::1))
2/27 | 20180227.01 | OSX10.12 | Operation timed out | NormalBufferRange_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180227.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendPacketsAsync~2FNormalBufferRange_Success(type:%20Async))
2/28 | 20180228.05 | OSX10.12 | Operation timed out | SendTimesOut_Throws
3/13 | 20180313.01 | OSX10.12 | Operation timed out | SendRecv_Stream_TCP_AlternateBufferAndBufferList 
3/24 | 20180324.02 | OSX10.12 | Connection refused | Cookies_SetAndSend_ClientReceivesExpectedHeaders
3/24 | 20180324.03 | OSX10.12 | Operation timed out | ConnectV6IPAddressToV6Host_Success
3/27 | 20180327.04 | OSX10.12 | Operation timed out | SendRecv_Stream_TCP_AlternateBufferAndBufferList
3/29 | 20180329.02 | OSX10.12 | Operation timed out | SendPacketsElement_FilePart_Success
3/31 | 20180331.05 | OSX10.12 | Operation timed out | BeginConnectV6IPAddressToDualHost_Success
4/2 | 20180402.05 | OSX10.12 | Operation timed out | ConnectV6IPEndPointToV6Host_Success
4/3 | 20180403.04 | OSX10.12 | Connection refused | TransportContext_GetChannelBinding_ReturnsExpected

**Comment by wfurt** [comment]
This is too old and the code changed a lot. I don't think it make sense to drag this forward. If we see failures, we should open new issue(s) with relevant details. The assert is still real issue and it is tracked by #36466.
