### ISSUE TITLE
BigInteger should have a less strictly typed constructor

### ISSUE THREAD

**Issue by bazzilic** [dotnet/runtime#22293]
`BigInteger` should have a `public BigInteger(IList<byte>)` constructor instead of the existing `public BigInteger(Byte[])` constructor.

### Rationale
First, asking for an interface instead of a specific type seems more in line with the ideology of the language. Second, there are situations when this would have been more convenient.

As an example, we are implementing some public key cryptosystems and use big integers internally. Many PK cryptosystems ([example](https://en.wikipedia.org/wiki/ElGamal_encryption#Encryption)) produce ciphertexts that are actually a pair of big integers, which are stored as a single concatenated byte array; e.g., a `byte[96]` stores two big integers, 48 bytes long each. Reconstructing these would require an extra step of copying first and second halves of the array into individual arrays — an expensive operation.

These add up when we are processing large data sets. Especially, considering that modern PK cryptosystems often work with ciphertexts 256 or 512 bytes long. Instead, if there was an `IList<byte>` constructor, we could have used `ArraySegment<byte>` and skip an unnecessary array copying.

### Details

`BigInteger` from `System.Numerics` could be "serialized" to a byte array using `.ToByteArray()` method, and "deserialized" from a byte array using one of the constructors.

However, currently, it only has a constructor that takes `byte[]`. Since the constructor (according to the [reference source](https://referencesource.microsoft.com/#System.Numerics/System/Numerics/BigInteger.cs,531)) actually only uses `.Length` property and indexed access, it would have been enough to require `IList<byte>` as an argument.

The proposal is to replace an existing constructor with `public BigInteger(IList<byte>)`. Since `byte[]` implements `IList<byte>`, I don't see any compatibility issues that could arise from that change. As I understand, just adding it to the list of constructors would create ambiguity, but I didn't verify that.

Hopefully, this could also be backported to the .NET Framework.

**Comment by tannergooding** [comment]
Going to close this as it hasn't garnered much attention and the primary scenario should be covered by the constructor overloads that take a `Span<byte>`.

If someone feels strongly about this, please feel free to open a new issue. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.

**Comment by bazzilic** [comment]
As I understand, neither Core nor .Net Framework support the `Span<byte>` constructor as of now, though?

**Comment by tannergooding** [comment]
It has existed since .NET Core 2.1: <https://apisof.net/catalog/System.Numerics.BigInteger..ctor(ReadOnlySpan%3CByte%3E,Boolean,Boolean)>

**Comment by tannergooding** [comment]
.NET Framework is not getting any new APIs as per https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net
