### ISSUE TITLE
Add Roslyn analyzer to build to check nothing has [Serializable] that's not on the approved list

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#22343]
Relates to changes introduced in https://github.com/dotnet/corefx/issues/19119
Add Roslyn analyzer to build to check nothing has [Serializable] that's not on the approved list

cc @danmosemsft @morganbr

**Comment by joperezr** [comment]
This doesn't seem to belong on System.Runtime area. Moving it to infrastructure so that it gets triaged there in case we want to add any analyzer as part of our build infra to cover this.

**Comment by safern** [comment]
@ericstj @ViktorHofer is this something we still need/want? It seems we have lived without it for 3 years already.

**Comment by ViktorHofer** [comment]
Closing as we don't plan to add the `SerializableAttribute` to any new types and changes on existing types should be easy to spot in PR reviews.

**Comment by ericstj** [comment]
cc @GrabYourPitchforks
