### ISSUE TITLE
Remove System.Drawing dead code

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#22394]
Attached is a zip containing removed.htm which shows everything ILLink thinks is dead and all.htm which shows everything, with removed in red. Everything red should be safe to delete.

[removed.zip](https://github.com/dotnet/corefx/files/1090302/removed.zip)

@mellinoe @hughbe do you think it is safe for folks to do this without tests?

**Comment by deeprobin** [comment]
> [removed.debug.zip](https://github.com/dotnet/corefx/files/1090336/removed.debug.zip) Debug build .. a bit more helpful.

Is this still up-to-date?

I could theoretically remove all members without references of the project (using R#), but I don't know if I would catch everything.

**Comment by ViktorHofer** [comment]
After https://github.com/dotnet/runtime/pull/64623 is merged we could ask @danmoseley if he can generate the dead report again.

**Comment by deeprobin** [comment]
https://github.com/dotnet/runtime/pull/64623 is merged

**Comment by ViktorHofer** [comment]
@danmoseley do you think you could re-generate your report (the one from 2017) to see if there's dead code left?

**Comment by ViktorHofer** [comment]
Closing as of age.
