### ISSUE TITLE
Add APIs like "int? int.TryParse(string? s)" to the Framework

### ISSUE THREAD

**Issue by canthonyparkinson** [dotnet/runtime#2241]
TryParse method in many ValueTypes is very useful, but would be more useful if it supported fluent API.

**### Rationale and Usage**

Many classes in .NET (Int32, Int16, Int64, Decimal, Double, ...) have a method called TryParse.  The existing signature (I will use Int32 as an example) is:

`public static bool TryParse(string? s, out int result)`

There are additional overloads, but my proposal will work equally for all of them.

The issue with the existing method is that it uses _out_ parameters and therefor cannot participate in fluent API approach.  

Since the two outputs are just a Boolean and a atomic value type, my idea is to have the method return a Nullable<T> for example

`public static Nullable<int> TryParse(string? s)`

Of course this same approach would be applied to all existing overloads for all classes that have TryParse (and TryParseExact).

so instead of 

`            int value;
            if (Int32.TryParse(input, out value))
            {
                Process(value);
            } else
            {
                Process(0);
            }
`

we could have 

`Process(Int32.TryParse(input).GetValueOrDefault(0);`

### **Proposed API**

For Int32.

`public static Nullable<int> TryParse(string? s)`
`public static Nullable<int> TryParse(ReadOnlySpan<char> s)`
`public static Nullable<int> TryParse(string? s, NumberStyles style, IFormatProvider? provider)`
`public static Nullable<int> TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider)`

### **Details**

These overloads will be easily created as wrappers around the existing methods or else we could move the existing logic into these new methods and refactor the old methods to be wrappers around these new methods.  Please provide guidance on this question.

### **Open Questions**

I see that a similar request  [https://github.com/dotnet/corefx/issues/25885](25885) has been rejected, but I hope I have given a better explanation of the idea.  

I have been using my own variation on this (implemented in a utility static class ever since .NET 2.0 in 2005 and I find it extremely convenient.  The existing API will still work as before, but an additional way if using it will be available.  .NET has recently added a complete duplicating set of overloads to the TryParse methods to allow both String and ReadOnlySpan<char> input types.  I see this as a similar exercise.

**Comment by GrabYourPitchforks** [comment]
As previously mentioned, dupe of https://github.com/dotnet/corefx/issues/25885. Specific scenario mentioned is fluent design, but the justification (and the API shape) is particularly opinionated as to how things like errors should be handled, and that behavior differs from existing `TryParse` methods.

**Comment by Gnbrkm41** [comment]
I agree with what has been decided in dotnet/corefx#25885; While I wouldn't veto against such methods in user codebases, having this in BCL seems like a lot of work to be done for no functional gains.

**Comment by canthonyparkinson** [comment]
I am disappointed that no one will back me on this, I accept the decision.  BTW, usability and productivity gains are just as valid reasons as functional gains to make an improvement.
