### ISSUE TITLE
Add CopyToAsync with Func overload to Stream 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#22472]
## Latest proposal

```c#
public abstract class Stream
{
    public virtual void CopyTo(ReadOnlySpanAction<byte, object> callback, object state, int bufferSize);
    public virtual Task CopyToAsync(Func<object, ReadOnlyBuffer<byte>, CancellationToken, Task> callback, object state, int bufferSize, CancellationToken cancellationToken);
    ...
}
```

See https://github.com/dotnet/corefx/issues/21472#issuecomment-321669769 for details.

## Original Proposal

Today `Stream` as `CopyToAsync` which acts more like a write operation than a read operation but it can also be used as a way to have a `Stream` push data to a consumer. Instead of forcing people to write a dummy `Stream` implementation that handles incoming data on `WriteAsync`, a callback could be provided to get the data that `Stream` has to hand out.

API shape:

```C#
public class Stream
{
    public Task CopyToAsync(Func<object, ArraySegment<byte>, Task> callback, object state);
    public Task CopyToAsync(Func<object, ArraySegment<byte>, CancellationToken, Task> callback, CancellationToken cancellationToken, object state);
    public Task CopyToAsync(Func<object, ArraySegment<byte>, CancellationToken, Task> callback, Int32 bufferSize, CancellationToken cancellationToken, object state);
}
```

The underlying implementation would just have a dummy stream that forwarded to callback on calls to `WriteAsync`:

```C#
CopyToAsync(new InternalCopyToAsyncStream(callback, state), bufferSize, cancellationToken);
```

/cc @stephentoub

**Comment by carlossanlop** [comment]
@stephentoub @manandre with https://github.com/dotnet/coreclr/pull/27639 merged, are there still any stream classes that need to get a `CopyToAsync` override, or can we consider this API Proposal fixed and close it?

For reference, [here's Stephen's reply](https://github.com/dotnet/coreclr/pull/27639#issuecomment-551076380) with a list of streams that we wanted to benefit from this new API, and it seems they were all addressed in Emmanuel's PR.

**Comment by manandre** [comment]
Initial intent of this API change request is reached. I propose to close it.

**Comment by stephentoub** [comment]
I've left it open because I'm not convinced there's enough value in actually keeping the API, and I think we should consider removing it prior to shipping .NET 5.  Very few streams are currently overriding it, and there's currently zero consumption of it anywhere in the stack as far as I can tell.  That's not promising for adding a new virtual like this to Stream.  Are we expecting more overrides, and if so, where?  Are we expecting more consumption anywhere in the stack?

**Comment by carlossanlop** [comment]
@davidfowl there seemed to be interest in consuming these APIs in ASP.NET. Were you able to consume them?

**Comment by danmosemsft** [comment]
Ping @davidfowl

**Comment by davidfowl** [comment]
We haven’t used this at all

**Comment by davidfowl** [comment]
Should we revert this? We probably don't have any plan to use it in the short term (.NET 5) either. We've changed strategy a bit here.

**Comment by stephentoub** [comment]
Yes, I'm removing them in https://github.com/dotnet/runtime/pull/37750.

**Comment by davidfowl** [comment]
A new use case appeared for this that was interesting:

Single input stream and N destination streams doing transforms:

- Reading incoming data from the request and hashing it the same time.

```C#
using var incrementalSha256 = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
await using fs = File.Create("backup.txt");
await inputStream.CopyToAsync(async (state, buffer, token) => 
{
     await ProcessBufferAsync(buffer, token);
     await fs.WriteAsync(buffer, token);
     incrementalSha256.Append(buffer.Span);
}, null, 4096, token);

var hashBase64 = Convert.ToBase64String(incrementalSha256.GetHashAndReset());
```
