### ISSUE TITLE
New HttpClient API design

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/runtime#22505]
Following the discussion here https://github.com/dotnet/designs/issues/9 there are several issues with current `HttpClient` implementation. The idea with this issue is to discuss the design of a proposed _new_ implementation and API surface for `HttpClient` as part of the original issue. 

Some points discussed on that issue:

1. There are 2 different implementations of `HttpClient`. One on Windows (based on WinHttp) and other on *NIX world (based on libcurl)
2. It does not release all resources right away as most of people expect by a class implementing `IDisposable` (the TCP socket still leaking for a while by default for 240s due to `TIME_WAIT` state which makes you run out of available socket connections under high load)
3. There could be a internal pool similar to what exist in `SqlConnection`. However, it would probably hit worse issues with DNS cache, since it is managed by the OS networking stack and this implementation try to be 100% managed on top of the new *Foundation* layer proposed on the previous issue.

**Comment by Cephei** [comment]
Please consider exposing the backing `HttpMessageHandler` through the `HttpClient` API. If only in a limited capacity - perhaps through a slimmed down facade or interface. I understand the handler's settings are mostly immutable by point-after-creation, but things like modifying the `CookieContainer`'s items within the handler are not. With `IHttpClientFactory` and `.AddHttpClient()` now being touted as best practice for managing clients, there is no clear way to manage cookies except per-request via headers. Sometimes you may want to add default cookies - but don't have them at point of creation. e.g. maybe you cache them somewhere

This can obviously be done during the factory delegate, but it's really hard for me to imagine pulling all of this customized code into the composition root of `Programs.cs`. There are plenty of reasons to want to encapsulate this logic in the application component using the `HttpClient`

**Comment by CarnaViire** [comment]
- big part of the issue and discussion seems quite outdated since 2017 (e.g. "There are 2 different implementations of HttpClient. One on Windows (based on WinHttp) and other on *NIX world (based on libcurl)" is not true anymore for a long time)
- some other parts are covered by other existing issues (e.g. DNS resolution, per-session cookies, LLHTTP etc)

This really _is_ a cleanup candidate, but we need to verify nothing important is left out (and if needed, create a separate issue scoped to the specific ask, or expand one of the existing issues)

I'm assigning it to myself temporarily for the investigation/triage purposes

**Comment by galvesribeiro** [comment]
@CarnaViire hey!

Yes, I agree. This is from 2017 when things are different. With most of the things now on the managed world, and with the introduction of `HttpClientFactory`, I think we have most of the requests on this issue implemented.

The only one that I still haven't seen workarounds is the DNS cache management. That may still bite us in some scenarios where intentionally we don't want to rely on caches.

**Comment by CarnaViire** [comment]
## Solved issues:

- Unify implementation -> `SocketsHttpHandler`, and `HttpClientHandler` uses `SocketsHttpHandler` underneath (where supported)
- Connection pooling / lifetime management / reacting to DNS changes -> `HttpClientFactory` or `SocketsHttpHandler` with `PooledConnectionLifetime` + [docs](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines)
- Use custom DNS resolution -> `ConnectCallback` in `SocketsHttpHandler`
- Resilience strategies (circuit breaker, rate limiter, hedging, etc) -> [Microsoft.Extensions.Http.Resilience](https://www.nuget.org/packages/Microsoft.Extensions.Http.Resilience) (integration with Polly)

## Tracked issues:

- Low-level HTTP APIs (LLHTTP)
    - https://github.com/dotnet/runtime/issues/525
    - https://github.com/dotnet/runtime/issues/66223
- DNS
    - DNS client and custom queries
        - https://github.com/dotnet/runtime/issues/19443
        - https://github.com/dotnet/runtime/issues/102105
    - DNS round-robin / happy eyeballs and other strategies
        - https://github.com/dotnet/runtime/issues/68967
        - https://github.com/dotnet/runtime/issues/26177
    - Revalidating DNS https://github.com/dotnet/runtime/issues/60390
- ConnectCallback improvements
    - User-friendly connect callback https://github.com/dotnet/runtime/issues/78989
    - Simpler TCP APIs https://github.com/dotnet/runtime/issues/63162
- Proactively closing HTTP connections https://github.com/dotnet/runtime/issues/62256
- Considering globally-available "default" instances
    - Singleton http handler https://github.com/dotnet/runtime/issues/33124
    - HttpClient.Shared https://github.com/dotnet/runtime/issues/65380
- Per-session / per-request overrides (cookies, proxies, default headers, certs, etc)
    - https://github.com/dotnet/runtime/issues/77668
    - https://github.com/dotnet/runtime/issues/23322
    - https://github.com/dotnet/runtime/issues/35992
    - https://github.com/dotnet/runtime/issues/36378
    - https://github.com/dotnet/runtime/issues/41191 

------

Triage: I believe the list covers all the topics discussed in the issue. Closing this "mega-issue" in favor of the issues linked above.
