### ISSUE TITLE
Investigate using Span in BigInteger implementation

### ISSUE THREAD

**Issue by axelheer** [dotnet/runtime#22609]
As already mentioned within dotnet/runtime#22387 the all-new Span should bring many benefits to BigInteger.

* We currently use pointers to spare some index calculations (performance) and "abstract" the differences between ordinary arrays and stackalloc based stuff --> use spans instead
* We currently copy the array containing the actual number after every operation to trim leading zeros --> use span.slice instead?
* And maybe there's more...

We cannot get grid of unsafe code completely since there are stack-vs-heap paths based on stackalloc, but all the pointer based stuff should gracefully disappear; I think.

I'm interested to dive into this, after the summer or so.

**Comment by tannergooding** [comment]
Marking this as `up-for-grabs`. Anyone should feel empowered to pick this up and prototype the improvements detailed.
