### ISSUE TITLE
DualModeAcceptAsync.AcceptAsyncV*BountTo* tests failed with TimeoutException

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#22620]
Tests:
* `System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV6BoundToAnyV6_Success ` (any platform test)
* `System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV4BoundToSpecificV6_CantConnect` (Windows-only test)
* `System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV6BoundToSpecificV4_CantConnect` (Windows-only test)

Opened on behalf of @Jiayili1

```
System.TimeoutException : Timed out while waiting for either of client and server connections...
Stack Trace:
at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /Users/buildagent/agent/_work/28/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1016
```
```
Build : 2.0.0 - 20170704.01 (Core Tests)
Failing configurations:
- OSX.1012.Amd64-x64
- Release
```
Detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170704.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DualModeAcceptAsync~2FAcceptAsyncV6BoundToAnyV6_Success

**Comment by karelz** [comment]
Failures during 3/12-5/11 (incl. PRs):

Date | Build / PR | OS | Test
-- | -- | -- | --
4/1 | PR #50239 | Windows.10.Amd64.Server19H1.ES.Open | AcceptAsyncV4BoundToSpecificV6_CantConnect

**Comment by ViktorHofer** [comment]
Failed again in https://github.com/dotnet/runtime/pull/57833

Configuration: `net6.0-windows-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open`

Console: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57833-merge-c22d475e6a2e444585/System.Net.Sockets.Tests/1/console.8ade567c.log?sv=2019-07-07&se=2021-09-09T16%3A07%3A09Z&sr=c&sp=rl&sig=l2DKYMt5GVG1%2Ba0LpXKlRwO2TNuxAynru%2BS%2FVOmjZCc%3D

```
    System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV6BoundToAnyV6_Success [FAIL]
      System.TimeoutException : Timed out while waiting for either of client and server connections...
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(976,0): at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(908,0): at System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV6BoundToAnyV6_Success()
```

**Comment by wfurt** [comment]
triage: dup of #1481. We should make dual mode more reliable. No recent failures.
