### ISSUE TITLE
[QUIC] QuicListener.ListenEndPoint returns a port of 0 if Start() hasn't been called

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#2262]
We should probably make this property throw if the listener hasn't been started.

```c#
var listener = new QuicListener(new IPEndPoint(IPAddress.Loopback, 0), sslOpts);
IPEndPoint endPoint = listener.ListenEndPoint; // will have a port of 0.
listener.Start();
endPoint = listener.ListenEndPoint; // will now have a valid port.
```

CC @jkotalik

**Comment by geoffkizer** [comment]
Related: #43000

**Comment by geoffkizer** [comment]
Having a property throw usually isn't great, but I suppose you can argue that this is incorrect usage and thus reasonable.

I do think it raises the question: why do we have a separate call to Start()? 

What would you ever do between calling the QuicListener constuctor and Start()? Seems like the answer is "nothing useful", and as such we should just get rid of Start.

**Comment by geoffkizer** [comment]
I suppose another option would be to make the constructor do the equivalent of calling Socket.Bind, but not Socket.Listen. This would at least give you a useful value for LocalEndPoint. Then, Start() would do the equivalent of Listen.

**Comment by karelz** [comment]
Triage: We want to merge `Start` into constructor -- no point in having them separate.
Affects API.

**Comment by scalablecory** [comment]
@jkotalik @Tratcher we're considering getting rid of Start()/Stop() and just having ctor/Dispose() do these things. How will this impact Kestrel?

**Comment by Tratcher** [comment]
@halter73 @JamesNK

**Comment by Tratcher** [comment]
Not much, Kestrel, immediately calls Start:
https://github.com/dotnet/aspnetcore/blob/ea2f5594e4f817c828904421b33bed3f921907ec/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs#L46-L47
