### ISSUE TITLE
"runtime-coreclr r2r" AzDO pipeline misconfigured?

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#2267]
The "runtime-coreclr r2r" pipeline hasn't run any jobs:

https://dev.azure.com/dnceng/public/_build?definitionId=670&_a=summary

It appears to have no triggers and no cron jobs.

In contrast, the "runtime-coreclr r2r-extra" pipeline (https://dev.azure.com/dnceng/public/_build?definitionId=663&_a=summary) is running on weekends.

I believe this is intended to be a normal outerloop run but with ReadyToRun enabled for the framework and tests. Should it be scheduled nightly?

@dotnet/runtime-infrastructure

**Comment by trylek** [comment]
Hmm, I guess that's probably my overlooking, I can easily set it up to run daily.

**Comment by BruceForstall** [comment]
I manually ran the pipeline, and it's clean:

https://dev.azure.com/dnceng/public/_build/results?buildId=499679&view=results

Hopefully it does what it is supposed to do, but I don't know how to check that with the current system not saving success logs.

**Comment by BruceForstall** [comment]
fixed by https://github.com/dotnet/runtime/pull/2358
