### ISSUE TITLE
Add X509SubjectAlternativeName as a rich type

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#22699]
SubjectAltName is an extension from RFC 3280 that's fairly important to the people who need it.  Currently applications make programmatic decisions for it via `ToString()` which has a couple of problems:

* It's localized on Windows
* It's not the same on Windows and !Windows.

Rather than exposing the whole GeneralName concept (and dealing with X400Address) the type would

* Exist
* Allow enumerating the DNSName entries
* Maybe allow enumerating the IPAddress entries
* Probably have a `MatchesHostname(string)` method
* Maybe have a `MatchesIPAddress(IPAddress)` method.

It might make sense to put `MatchesHostname` on X509Certificate2, just to make things easier.

---

# API Proposal

```C#
namespace System.Security.Cryptography.X509Certificates
{
    public partial class X509Certificate2
    {
        // Performs RFC 6125 matching of a hostname against a certificate and the
        // Subject Alternative Names.
        //
        // Uses IPAddress.TryParse to determine DNS match vs IP match
        public bool MatchesHostname(string hostname) { throw null; }
        public bool MatchesHostname(string hostname, bool allowWildcards = true, bool allowCommonName = true) { throw null; }
    }

    public sealed class X509SubjectAlternativeNameExtension : X509Extension
    {
        public X509SubjectAlternativeNameExtension() { }
        public X509SubjectAlternativeNameExtension(byte[] rawData, bool critical = false) { }
        public X509SubjectAlternativeNameExtension(ReadOnlySpan<byte> rawData, bool critical = false) { }

        public IEnumerable<string> EnumerateDnsNames() { throw null; }
        public IEnumerable<IPAddress> EnumerateIPAddresses() { throw null; }
    }
}
```

**Comment by bartonjs** [comment]
Related to https://github.com/dotnet/runtime/issues/28771.  (This issue focuses more on "make the extension type for the cert.Extensions collection", that issue focuses more on "be able to answer the question from a certificate").

**Comment by stephenjust** [comment]
Would it make sense to support enumerating each of the names that SubjectAlternativeNameBuilder allows you to specify? I do think DnsName and IP Address cover the most common use cases, but from a consistency point of view it seems like we should at least support easily reading the values that we can write.

**Comment by stephenjust** [comment]
Can we specify that when enumerating DNS names and IP addresses, sort order will be maintained? i.e. the records may be interleaved in the raw data, but the first returned DNS name will be the first record if that type specified in raw data?

We definitely have some scenarios where services only look at the first DNS Name specified in the alternative names, I think to match the behavior of win32. It's a niche use case, but it seems like a desirable property in general for ordering to be predictable.

In contrast, X509Certificate2.GetNameInfo does not define which of multiple names will be returned, and the ambiguity is can lead to incorrect assumptions.

**Comment by bartonjs** [comment]
> Can we specify that when enumerating DNS names and IP addresses, sort order will be maintained? 

Yeah.  But if the order is DNSName1/IPAddress1/DNSName2/DNSName3/DNSName4/IPAddress2/IPAddress3 all that the output knows is

DNSNames: DNSName1/2/3/4
IPAddresses: IPAddress1/2/3

>  X509Certificate2.GetNameInfo does not define which of multiple names will be returned,

The docs don't call it out, but there's a pretty extensive set of tests to make sure the same answer is always given on Windows and non-Windows.  Looks like "first one wins".

https://github.com/dotnet/runtime/blob/d55a1dfa4e39a26a8ea8d161f733c72805f31f7f/src/libraries/System.Security.Cryptography.X509Certificates/tests/PropsTests.cs#L406-L514

**Comment by deeprobin** [comment]
Is there any reason not to seal this type?

**Comment by bartonjs** [comment]
@deeprobin Just a transcription error, thanks for noticing.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Security.Cryptography.X509Certificates
{
    public partial class X509Certificate2
    {
        // Performs RFC 6125 matching of a hostname against a certificate and the
        // Subject Alternative Names.
        //
        // Uses IPAddress.TryParse to determine DNS match vs IP match
        public bool MatchesHostname(string hostname) { throw null; }
        public bool MatchesHostname(string hostname, bool allowWildcards = true, bool allowCommonName = true) { throw null; }
    }

    public sealed class X509SubjectAlternativeNameExtension : X509Extension
    {
        public X509SubjectAlternativeNameExtension() { }
        public X509SubjectAlternativeNameExtension(byte[] rawData, bool critical = false) { }
        public X509SubjectAlternativeNameExtension(ReadOnlySpan<byte> rawData, bool critical = false) { }

        public IEnumerable<string> EnumerateDnsNames() { throw null; }
        public IEnumerable<IPAddress> EnumerateIPAddresses() { throw null; }
    }
}
```
