### ISSUE TITLE
Use Uri.ToString() instead of Uri.OriginalString when serializing Uri

### ISSUE THREAD

**Issue by cmeeren** [dotnet/runtime#2279]
When serializing a `Uri`, System.Text.Json seems to use `Uri.OriginalString`. Unfortunately this may not be correct if the Uri has been transformed by a UriBuilder, see https://github.com/dotnet/corefx/issues/41679. Specifically, `OriginalString` may contain a port that was not in the original `Uri` and which can be avoided by using `Uri.ToString()`.

Quoting @davidsh https://github.com/dotnet/corefx/issues/41679#issuecomment-539992890:

> Not sure why .OriginalString is used here. That property is not recommended for most use cases of Uri because it is not a normalized representation of the URI.

**Comment by MihaZupan** [comment]
Related: dotnet/corefx#41733 microsoft/OpenAPI.NET#441 JamesNK/Newtonsoft.Json#2190

Changing the value used to ToString would mean writing different json than Json.Net, as Uris that were originally escaped would be written in unescaped form. While such Uris can be reconstructed, this would break anyone depending on the serialization behavior.
I doubt Json.Net would consider making such a change and I assume System.Text.Json wants to keep compatibility with it as far as behavior goes. cc @JamesNK 

Perhaps we should be looking at why UriBuilder modifies "OriginalString", and whether it should.

**Comment by layomia** [comment]
Closing - `Uri.OriginalString` is used for reasons mentioned above - see https://github.com/dotnet/corefx/pull/39015 for more discussion.
