### ISSUE TITLE
Add more Math operation support System.Numerics.Vectors

### ISSUE THREAD

**Issue by dangi12012** [dotnet/runtime#22857]
Support for some SIMD instructions are missing in Numerics.Vectors

Vector.RootN //Only SquareRoot is implemented
Vector.Exp //Every element of the result is exp(a,b) where a,b are input vectors
Vector.LShift //Shift elements in a by elements in b
Vector.RShift //Like above would simulate a = b >> c for all elements

It wondsers me because Or and XOr is there but not shift. 
Code where Vectors would be perfect but are not supported yet:
```
while (pbuf < pend)
{
    uint tx = x ^ (x << 11);
    uint ty = y ^ (y << 11);
    uint tz = z ^ (z << 11);
    uint tw = w ^ (w << 11);
    *(pbuf++) = x = w ^ (w >> 19) ^ (tx ^ (tx >> 8));
    *(pbuf++) = y = x ^ (x >> 19) ^ (ty ^ (ty >> 8));
    *(pbuf++) = z = y ^ (y >> 19) ^ (tz ^ (tz >> 8));
    *(pbuf++) = w = z ^ (z >> 19) ^ (tw ^ (tw >> 8));
}
```

**Comment by tannergooding** [comment]
Going to close this as it hasn't garnered much attention and is at least user implementable with the new APIs for converting between the S.N.Vector and S.R.Intrinsic.Vector types.

If someone feels strongly about this, please feel free to open a new issue. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.
