### ISSUE TITLE
Constructor Using Dynamic Type Not Visible When Using InternalsVisibleTo

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#22893]
_From @adamrodger on July 23, 2017 16:35_

I have a class in `ClassLibrary1` like this:
```csharp
[assembly: InternalsVisibleTo("OtherLibrary")]
public class Foo
{
    internal Foo(dynamic bar)
    {
        Console.WriteLine(bar.Bar);
    }
}
```
And then in `OtherLibrary` I have a test:
```csharp
[Fact]
public void Test1()
{
    dynamic bar = new { Bar = "Success!" };
    Foo x = new Foo(bar);
}
```

**Expected Result**: Running the test passes and "Success!" is written to the console
**Actual Result**:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : 'ClassLibrary1.Foo.Foo(object)' is inaccessible due to its protection level
   at CallSite.Target(Closure , CallSite , Type , Object )
   at CallSite.Target(Closure , CallSite , Type , Object )
   at OtherProject.UnitTest1.Test1()
```

If I change the constructor to take an explicitly typed object (e.g. pass a string directly) then the test passes. If I make the constructor public then the test also passes. It's only when `Foo` has an internal constructor with a `dynamic` argument.

_Copied from original issue: dotnet/coreclr#12988_

**Comment by cston** [comment]
With current .NET 5 builds, the call to the constructor succeeds. As @JonHanna reported, there is an exception trying to access `Bar` in that constructor because the anonymous type is inaccessible.

@adamrodger, please re-open this issue if we've overlooked something, thanks.
