### ISSUE TITLE
Cannot get Header value back when it includes special chars.

### ISSUE THREAD

**Issue by EmmaZhu** [dotnet/runtime#22938]
Just encountered an issue when trying to get azure blob's properties, that it cannot get the property value back when the value string includes special chars like "<" or ">" with following code:
```c#
HttpClient client = new HttpClient();
HttpRequestMessage httpRequestMessage = new HttpRequestMessage(HttpMethod.Head, "http://emmahk2.blob.core.windows.net/container1/overwritetest/Program.cs");
httpRequestMessage.Headers.Add("x-ms-version", "2017-04-17");
HttpResponseMessage response = client.SendAsync(httpRequestMessage).Result;
response.EnsureSuccessStatusCode();
Console.WriteLine(response.Content.Headers.Contains("ContentDisposition"));
```
Value for "ContentDisposition" is "\<fd\>". From the response got from fiddler, Azure Storage Server returns the value correctly, while the value is null in `HttpResponseMessage response` of the above codes.

I can get the value back with following code:
```c#
HttpWebRequest req = WebRequest.CreateHttp(new Uri("http://emmahk2.blob.core.windows.net/container1/overwritetest/Program.cs"));
req.Method = "HEAD";
req.Headers["x-ms-version"] = "2017-04-17";

var result = req.GetResponseAsync().Result;
Console.WriteLine(result.Headers["Content-Disposition"]);
```

It seems weird that the behavior of `HttpClient `and `HttpWebRequest`  is different.

Could anyone help to take a look?

[EDIT] Add C# syntax highlighting by @karelz

**Comment by MihaZupan** [comment]
We added a NonValidated view over the header collection in https://github.com/dotnet/runtime/issues/35126.
You can use that to enumerate invalid headers like this.
