### ISSUE TITLE
Disable System.Drawing tests expected to fail on Server Core

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#22946]
•	All the Drawing tests fail.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170726.03/workItem/System.Drawing.Common.Tests
I assume this is because GDI doesn’t exist, like on Nano. 

Currently these all have
[ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
Which we should bulk edit now to
[ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotHeadlessWindows))]

after https://github.com/dotnet/corefx/pull/22653/files

**Comment by JeremyKuhne** [comment]
System.Drawing.Common has moved to WinForms which requires full Windows.
