### ISSUE TITLE
Stop dotnet/runtime from building NETStandard.Library.Ref 2.1.0?

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#2294]
Right now, dotnet/runtime produces and publishes packages like `NETStandard.Library.Ref.2.1.0-alpha.1.20078.2.nupkg` from the official build.

This isn't *too* unexpected: dotnet/runtime is responsible for creating NETStandard targeting packs until dotnet/standard is able to build them itself: https://github.com/dotnet/standard/issues/1209.

I don't think we should be building version `2.1.0` though. https://github.com/dotnet/runtime/issues/639#issuecomment-575788698:

> * dotnet/runtime `master` produces `2.1.0-alpha-...`
> * dotnet/core-setup `release/3.0` is set up to produce 2.1.1 (disabled by `PatchVersion="0"`)
> * dotnet/core-setup `release/3.1` is set up to produce 2.1.1 (disabled by `PatchVersion="0"`)
> 
> It's strange that dotnet/runtime `master` is producing new NETStandard 2.1.0-alpha targeting packs, even though 2.1.0 is already released.
> 
> I would argue that dotnet/runtime `master` should be set up to produce NETStandard 2.1.1, 2.2.0, or nothing at all. We can also set it up as 2.2.0 but still disable it using `PatchVersion="N/A"`.

The simplest way to disable it is set the `ProjectServicingConfiguration PatchVersion="N/A"`. This avoids implying we know what vnext is for NETStandard. (See https://github.com/dotnet/runtime/pull/2291 for details on the project disable infra.)

@wtgodbe @terrajobst does this make sense?

/cc @NikolaMilosavljevic

**Comment by wtgodbe** [comment]
> The simplest way to disable it is set the ProjectServicingConfiguration PatchVersion="N/A". This avoids implying we know what vnext is for NETStandard.

I think that sounds good, though I'd be curious to know what the plan is going forward for the Standard repo

**Comment by terrajobst** [comment]
We're working through this. My expectation is that this repo will become similar to CoreFX/CoreCLR in that it's only used for servicing older releases and the moving forward it'll be replaced by the runtime repo. However, this doesn't mean we need to build netstandard assets from the runtime repo. My expectation is that the `net5` TFM will subsume both netcoreapp and netstandard.

**Comment by NikolaMilosavljevic** [comment]
Fixed with  https://github.com/dotnet/runtime/pull/33484

**Comment by ViktorHofer** [comment]
Reopening to discuss if we should delete the infra for this in dotnet/runtime as well, mainly this: https://github.com/dotnet/runtime/tree/master/src/installer/pkg/projects/netstandard

@terrajobst any concerns about that?

**Comment by NikolaMilosavljevic** [comment]
Closing - question of infra removal should go into its own issue.
