### ISSUE TITLE
How to compare previous version source code

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/runtime#22991]
I have a library that targets `netstandard2.0` with the following line of code:

```
            return new HttpClientHandler
            {
                AllowAutoRedirect = false,
                CookieContainer = null,
                UseCookies = false
            };
```

When running in an application that's targeting `netcoreapp2.1` the piece of code seems to work fine when running on Ubuntu 16.04 Linux with .NET Core Runtime `Microsoft.NETCore.App 2.1.13` installed.

However, when I update my application to `netcoreapp3.1` the above code fails with an `ArgumentNullException`, indicating you can't set `CookieContainer` to null.

Obviously, from looking at the current source code you can see there is an argument check on it:

https://github.com/dotnet/runtime/blob/f6f4ab624bd3e55afab4262ba9207f3f6329039a/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L55

My question isn't so much why it's failing, but instead how I can see the source code at version `2.1.13`, and be able to compare it to `3.1.0`.

When looking at the branches and tags in this repository, I don't see anything that references any historical releases / versions.

How would I be able to view previous versions of the source code, and be able to compare versions from a source code level?

**Comment by Clockwork-Muse** [comment]
You'd want to look at [dotnet/corefx](https://github.com/dotnet/corefx) for historical code.

**Comment by MatthewLymer** [comment]
Ah okay, that works for me, thanks!
