### ISSUE TITLE
A mechanism for specifying alignment on a field or struct should be supported.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#22990]
### Rationale

In certain high performance or specialized data structures/algorithms, it is desirable to enforce an alignment for structs, fields, or locals.

Today, CoreFX provides several specialized data structures for which the runtime either has special alignment handling (`System.Numerics.Vector`) or for which they have some specialized padding (https://github.com/dotnet/corefx/pull/22724).

As such, the framework/runtime should provide a mechanism for encforcing a specified alignment for structs and fields. Locals should also be included if that is feasible (I'm not sure if that is readily possible today given that attributes cannot be specified on locals).

### Additional Thoughts
It might be worthwhile to additionally expose this on the existing `StructLayoutAttribute` as an `Alignment` property.

An alignment of `0` should be treated as "Automatic" (the current behavior of letting the runtime decide alignment).

A mechanism for aligning to the cache would be ideal (https://github.com/dotnet/corefx/pull/22724#issuecomment-319075196). This could perhaps be a special value that would otherwise be invalid (such as `Alignment=-1`). Other special alignments could also be allowed in a similar manner.

If a field specifies an alignment less than that of the struct, it should be aligned to the alignment of the struct. For example, if you do `Alignment=8` on a `Vector4` (which has an `Alignment=16`), the field should be treated as `Alignment=16`.

[Design Decision] If a struct specifies an alignment less than that of its first field it should either:
A. Align the struct as specified and add the appropriate padding so that the first field is also aligned as specified
-or-
B. Align the struct as per the requirements of the first field

[EDIT] Make reference to the PR a link by @karelz

**Comment by Unknown6656** [comment]
what is the current state of this proposal?

**Comment by tannergooding** [comment]
Closed/inactive. It would require substantial GC work to support and is low priority.

Data is already naturally aligned according to the primitive elements it contains and in the cases of things like arrays and large data processing there are often better ways to deal with the data (which you'll often have as part of your core algorithm anyways) such as doing opportunistic alignment.

If you'd like to manually manage memory, convenience APIs such as `NativeMemory.AlignedAlloc` exist and most BCL APIs take `Span` which allows you to transparently work with managed or native memory.
