### ISSUE TITLE
Add docker image for cross compiling armel (Or post source to docker images)

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#2302]
Cross compiler docker images for compiling arm and aarch exist, and it would be really nice if an armel docker image was added, seeing as it is supported by the build system.

Also, I couldn't find the source for the docker images, if those were posted somewhere this might be possible to do myself.

**Comment by jkotas** [comment]
The sources for docker images that use to build .NET Core are in
https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo.
