### ISSUE TITLE
Support for Console.MoveBufferArea() on Linux & Mac

### ISSUE THREAD

**Issue by nilslueders** [dotnet/runtime#23073]
Is there a plan to support Console.MoveBufferArea() on Linux & Mac? Currently it throws a PlatformNotSupportedException on these platforms.

Without this feature it seems to me not possible to write in the bottom right corner of the console without losing the first line of the buffer (due to the resulting jump to the next line of the cursor), which is not very useful for text user interfaces.

**Comment by adamsitnik** [comment]
We did not know how to implement it in 2017 and there was no proposal|suggestion since then so I am just closing it.

If somebody has a good idea for how we can implement that, please feel free to reopen the issue.
