### ISSUE TITLE
Automatically harvest dependencies for .NET Framework compat meta-package

### ISSUE THREAD

**Issue by weshaggard** [dotnet/runtime#23085]
After https://github.com/dotnet/corefx/pull/22665 the updating and validation of the Microsoft.NETFramework.Compatibility meta-package is all manual. We should provide some mechanism to automatically consume the right set of packages. We should at a minimum  provide a mechanism to validate that the package list and versions being referenced are correct.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/27503 to cover the validation part.
