### ISSUE TITLE
System.Net.WebSockets doesn't allow setting of socket options in any way.

### ISSUE THREAD

**Issue by rowanG077** [dotnet/runtime#23183]
The current API surface of .NET core doesn't expose the underlying TCPSocket so there is no way to set socket options.

My specific use cases requires me to disable naggle algorithm. If I don't there are stalls that make it unuseable in my application.

I would really like it if we could either access the underlying TCP socket object or allow us to set the socket options in some way.

Currently I am forced to disable naggle system wide...

**Comment by stephentoub** [comment]
@karelz, this is marked as blocked. What is it blocked on at this point? SocketsHttpHandler allows you to configure socket options now.

**Comment by stephentoub** [comment]
I'm going to close this as addressed at this point.  First, with regards to the initial issue, nagle is disabled by default in .NET Core. Second, SocketsHttpHandler lets you control connections via ConnectCallback, and ClientWebSocket in .NET 7 now lets you pass in the invoker to use, so you can pass in one configured however you like.  (On top of that, WebSocket.CreateFromStream has long allowed you to provide any Stream representing an established connection.) Thanks.
