### ISSUE TITLE
File.WriteAllTextAsync performance issues

### ISSUE THREAD

**Issue by fabio-muramatsu** [dotnet/runtime#23196]
System configuration:
* `dotnet --version`: 2.0.0
* OS: Arch Linux

I'm facing performance issues using `File.WriteAllTextAsync` in .NET core 2.0. I'm relatively new to .NET core, so I don't know if I'm doing something wrong here. For testing purposes, have written 3 methods that do the same thing in different ways: all of them write some content to a random file, and then delete it.

```c#
static async Task WriteAllTextAsync()
{
    string fileName = System.Guid.NewGuid().ToString();
    await File.WriteAllTextAsync($"write/{fileName}.txt", content);
    File.Delete($"write/{fileName}.txt");
}

static void WriteAllText()
{
    string fileName = System.Guid.NewGuid().ToString();
    File.WriteAllText($"write/{fileName}.txt", content);
    File.Delete($"write/{fileName}.txt");
}

static async Task WriteWithStreamWriter()
{
    string fileName = System.Guid.NewGuid().ToString();
    using (StreamWriter outputFile = new StreamWriter($"write/{fileName}.txt"))
    {
        await outputFile.WriteAsync(content);
    }
    File.Delete($"write/{fileName}.txt");
}
```

I am using the following loop to call these methods:
```c#
for (int i = 0; i < 200; ++i)
{
    //"method()" or "await async_method()"
}
```

I've noticed that `WriteAllTextAsync` is significantly slower than the other methods and results in higher disk usage (no fancy benchmarks here, the HDD led on my pc just stays turned on when using this method). Using `time` on each method gives the following results:
```
WriteAllTextAsync
real	0m14.579s
user	0m4.314s
sys	0m0.460s

WriteAllText
real	0m4.244s
user	0m4.116s
sys	0m0.418s

WriteWithStreamWriter
real	0m4.243s
user	0m4.133s
sys	0m0.432s
```

As expected, the results using `File.WriteAllText` (synchronously) and StreamWriter.WriteAsync (asynchronously) are very close, but `File.WriteAllTextAsync` is much slower.

**Comment by jeffhandley** [comment]
@Jozkee / @adamsitnik - Do you think this is still going to make 6.0.0, or should we move it out to 7.0.0/Future?

**Comment by adamsitnik** [comment]
I've tried to repro the problem using [these](https://github.com/dotnet/performance/pull/1881) benchmarks, but I was not able to. For small inputs (100 or 1000 characters) all four methods report very similar time. For big input (100_000 characters), all async methods are noticably slower than sync.

```ini
BenchmarkDotNet=v0.13.0.1559-nightly, OS=ubuntu 18.04
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100-preview.7.21354.4
  [Host]     : .NET 6.0.0 (6.0.21.35216), X64 RyuJIT
  Job-TUMXCU : .NET 6.0.0 (6.0.21.35216), X64 RyuJIT
```

|                 Method |   size |      Mean | Allocated |
|----------------------- |------- |----------:|----------:|
|           WriteAllText |    100 |  35.22 us |      6 KB |
|      StreamWriterWrite |    100 |  35.99 us |      6 KB |
| StreamWriterWriteAsync |    100 |  34.11 us |      6 KB |
|      WriteAllTextAsync |    100 |  36.41 us |     10 KB |
|           WriteAllText |   1000 |  35.02 us |      9 KB |
|      StreamWriterWrite |   1000 |  34.37 us |      9 KB |
| StreamWriterWriteAsync |   1000 |  34.91 us |      9 KB |
|      WriteAllTextAsync |   1000 |  36.02 us |     10 KB |
|           WriteAllText | 100000 | 162.73 us |      9 KB |
|      StreamWriterWrite | 100000 | 160.14 us |      9 KB |
| StreamWriterWriteAsync | 100000 | 566.94 us |     35 KB |
|      WriteAllTextAsync | 100000 | 499.13 us |     20 KB |

@fabio-muramatsu what was the size of the `content` used in your benchmark? Does it contain any unusual characters or was it a simple ascii text?

**Comment by fabio-muramatsu** [comment]
@adamsitnik I ran these tests years ago, so I don't remember what was the exact input that I used. If I remember correctly, they were about 100 characters long (the first paragraph of Lorem Ipsum).

I reran my tests using a Ubuntu 20.04 VM with HDD as the storage layer, and it looks like the issue is resolved in .NET 6:

```
.NET Core 2.1.816
WriteAllTextAsync: 4390 ms
WriteAllText: 90 ms
WriteWithStreamWriter: 93 ms

.NET Core 3.1.410
WriteAllTextAsync: 4707 ms
WriteAllText: 129 ms
WriteWithStreamWriter: 92 ms

.NET 5.0.301
WriteAllTextAsync: 4575 ms
WriteAllText: 101 ms
WriteWithStreamWriter: 81 ms

6.0.100-preview.5.21302.13
WriteAllTextAsync: 162 ms
WriteAllText: 171 ms
WriteWithStreamWriter: 261 ms
```

**Comment by adamsitnik** [comment]
@fabio-muramatsu thank you!
