### ISSUE TITLE
Official build break in publish stage: NuGet library mismatch vs. SDK

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#2319]
First repro: https://dev.azure.com/dnceng/internal/_build/results?buildId=499590&view=results

> D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20071.3\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Method not found: 'NuGet.Versioning.NuGetVersion NuGet.Packaging.Core.PackageIdentity.get_Version()'.

This is a common class of issue where the Arcade SDK is built against a certain NuGet version, but the SDK contains another that is incompatible when used at runtime. We recently updated the SDK, triggering it.

We need to update the Arcade SDK to take this fix: https://github.com/dotnet/arcade/issues/1965

https://github.com/dotnet/runtime/blob/110af6e057e28736f69acfde306780d8649175ad/global.json#L15

We need at least `5.0.0-beta.20074.6`.

**Comment by jkoritzinsky** [comment]
Our maestro PR is currently blocked on something. It looks like it might be linker issues. https://github.com/dotnet/runtime/pull/2074

**Comment by dagood** [comment]
Alternative: downgrade the SDK. (Optionally, disable restoring internal tools to also remove flakiness.)

**Comment by dagood** [comment]
FYI @dotnet/runtime-infrastructure

**Comment by safern** [comment]
> (Optionally, disable restoring internal tools to also remove flakiness.)

I just merged a PR which should hopefully help with that.

**Comment by jkoritzinsky** [comment]
I’d rather not downgrade the SDK since to unblock #2115 and dotnet/sdk#3884 I need to update to an SDK with #2264 once that’s published (which would be after we fix this, but would lead us back to the same problem very quickly).

I think we should either update our dotnet/arcade subscription or back out the linker upgrade from the Maestro PR until the blocking issue is fixed.

**Comment by ViktorHofer** [comment]
I just removed the linker update (again) and disabled the subscription (again) to get the Arcade update in. @marek-safar is following-up on the break illink.

https://github.com/dotnet/runtime/pull/2074

**Comment by dagood** [comment]
Thanks all, new build is green: https://dev.azure.com/dnceng/internal/_build/results?buildId=502394&view=results. 🎉
