### ISSUE TITLE
Jit double zeros

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#2325]
Given [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BYAKAAEAGAAnIEYA6AIQFcAzNmKXAbjKtqMASiwB2GAJb4YDAMIR8ABwkAbLgGUuANwlgYvMvwDMtAEzVZ1MgG8y1e7RPkU1ALIAKAJRXSD6rd8/By1sKGpsfGBqAF5qAEFcAE9RMAA1bBUWGHIkVxgMAAsIABNWVWKuAB4hGGximtwWFQwAPjlYbAwYLz5A+wBfMkHSY2oO4ohRFUTqXAwoFjAMahq6hqaMGzsHCXEuUQyx2ompmdXigHlTzQBHLJSYSuBErpbqAH1YRubWDi5evy7LpQA4qI51SbTahAj5fDYAMRU2AA5gZSP0gA)
```csharp
using System.Buffers;
using System.Runtime.CompilerServices;

public class C 
{
    public void M() 
    {
        var amb = AsyncValueTaskMethodBuilder<ReadResult>.Create();
    }
}

public readonly struct ReadResult
{
    internal readonly ReadOnlySequence<byte> _resultBuffer;
    internal readonly int _resultFlags;
}
```
The Jit zeros in the preamble with `rep stosd` and then zeros in the body with `vmovdqu`
```asm
L0000: push rdi
L0001: push rsi
L0002: sub rsp, 0x38
L0006: vzeroupper
L0009: mov rsi, rcx
L000c: lea rdi, [rsp+0x8]           ;
L0011: mov ecx, 0xc                 ;
L0016: xor eax, eax                 ;
L0018: rep stosd                    ; clear stack
L001a: mov rcx, rsi
L001d: lea rax, [rsp+0x8]           ;
L0022: vxorps xmm0, xmm0, xmm0      ; 
L0026: vmovdqu [rax], xmm0          ; 
L002a: vmovdqu [rax+0x10], xmm0     ; 
L002f: vmovdqu [rax+0x20], xmm0     ; clear stack again
L0034: add rsp, 0x38
L0038: pop rsi
L0039: pop rdi
L003a: ret
```
Would it be possible for the Jit to skip the second set of zeroing given its already zeroed the stack at the start?

category:cq
theme:prolog-epilog
skill-level:expert
cost:medium

**Comment by AndyAyersMS** [comment]
cc @erozenfeld

**Comment by benaadams** [comment]
A more specific/common example is async, for example ReadResults in System.IO.Pipelines; which may be more problematic as currently the C# statemachine generation inserts the saving of parameters before the call to `.Create` and assign, which does the second zeroing.
```csharp
using System.IO.Pipelines;

public async ValueTask<ReadResult> OuterMethod(object o)
{
    return await InnerMethod(o);
    
    static async ValueTask<ReadResult> InnerMethod(object o) 
    {
        return default;
    }
}
```
```asm
G_M16490_IG01:
    push     rdi
    push     rsi
    sub      rsp, 136
    vzeroupper 
    mov      rsi, rcx                 ;
    lea      rdi, [rsp+20H]           ;
    mov      ecx, 26                  ;
    xor      rax, rax                 ;
    rep stosd                         ; zero
    mov      rcx, rsi
    mov      rsi, rdx
						;; bbWeight=1    PerfScore 30.00
G_M16490_IG02:
    mov      gword ptr [rsp+20H], r8          ; save param
    xor      ecx, ecx                         ; re-zero
    vxorps   xmm0, xmm0                       ; re-zero
    vmovdqu  xmmword ptr [rsp+30H], xmm0      ; re-zero
    vmovdqu  xmmword ptr [rsp+40H], xmm0      ; re-zero
    mov      qword ptr [rsp+50H], rcx         ; re-zero
    mov      dword ptr [rsp+28H], -1
    lea      rcx, [rsp+20H]
    call     System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start(byref)
    lea      rcx, bword ptr [rsp+30H]
    mov      rdx, rsi
    call     System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[ReadResult][System.IO.Pipelines.ReadResult]:get_Task():System.Threading.Tasks.ValueTask`1[ReadResult]:this
    mov      rax, rsi
						;; bbWeight=1    PerfScore 9.08
G_M16490_IG03:
    add      rsp, 136
    pop      rsi
    pop      rdi
    ret      
						;; bbWeight=1    PerfScore 2.25
```

**Comment by erozenfeld** [comment]
I'll investigate.

**Comment by erozenfeld** [comment]
#31677 reduces the code for the first example to a single `ret` instruction.

The second one is harder to deal with. We are very conservative with address-exposed locals and don't try to figure out any liveness information for them. I'm trying to find an inexpensive way to do better at least in some simple cases.

**Comment by benaadams** [comment]
@erozenfeld would this roslyn change help, or not make any difference? https://github.com/dotnet/roslyn/pull/41253

**Comment by benaadams** [comment]
Or would changing it to move all the zeroing above that first assignment to non-zero (which would be a much more complex refactoring in Roslyn)

**Comment by erozenfeld** [comment]
Neither of these two changes will help the jit. It has trouble with double initialization in much simpler cases, e.g., #1007. In your example there are 3 blockers for the jit. Any of them will currently result in double zero-initialization.
1. The local is marked as address-exposed and the jit doesn't do any liveness tracking for such locals.
Here the explicit initialization happens in the first basic block so maybe we can special-case this somehow.
2. We are initializing a field of struct type. There is some unfinished work on better morphing such fields that could help here, e.g., https://github.com/dotnet/runtime/blob/2cf4433f64cd10070f19de0c091295108a982b7f/src/coreclr/src/jit/lclmorph.cpp#L1012
3. The struct has gc fields. We are very conservative in initializing such structs in the prolog: https://github.com/dotnet/runtime/blob/8bd94d1a1be116d28672d08f09a15af3fcc0d6aa/src/coreclr/src/jit/codegencommon.cpp#L4636-L4640

**Comment by benaadams** [comment]
Am wondering given 3. (prolog initialization); then specialising the first block might be a good route/stopgap?

i.e. if its going to do `rep stosd` which has a high fixed cost; then its better to use its low variable cost to zero rather than try to anything else, and its probably a common case? e.g. All the examples in #1007 are first block and C# forces explicit initialization; as well as picking up every `async` Start method which all have this pattern.

The first block can assume prolog initialization in certain circumstances e.g. (1.) (3.) above, and only needs to consider itself (e.g. given this type will be zero; has it been overwritten in my block, requiring re-zero); whereas I assume full tracking to eliminate double writes across the entire method would be a lot more involved?

Obviously I'm just armchairing this and don't have any idea of the complexity to do that; so feel free to disregard 😉

**Comment by erozenfeld** [comment]
The jit needs additional analysis in order to remove one of the zero initializations safely.

To remove a zero-initialization of a struct with GC fields in the prolog the jit must make sure that the struct is initialized explicitly before any use (if initlocals is set on the method) and also before any GC-safe point. Note that initlocals is stripped in almost all framework assemblies, so that helps a bit.

To remove an explicit zero-initialization of a struct with GC fields the jit must ensure that the struct is not written-to on any path between the prolog and the explicit initialization. It also needs to check that the explicit initialization is not in a loop.

The jit doesn't currently have that information for address-exposed structs. I don't see a cheap and easy way to get the information. Yes, doing the analysis for explicit initializations in the first basic block may be a good compromise but even that is not straightforward to implement. In your case we are zero-initializing a field of type struct rather than a local struct, which is another complication for the jit. I'll keep exploring the possibilities here.

**Comment by benaadams** [comment]
While reviewing changes from https://github.com/dotnet/runtime/pull/32538, I noticed  `DateTimeParse` class is probably a good example e.g.

``DateTimeParse:ParseExact(ReadOnlySpan`1,ReadOnlySpan`1,DateTimeFormatInfo,int):DateTime``

```asm
G_M60356_IG01:
    push     rdi
    push     rsi
    sub      rsp, 184
    xor      rax, rax                 ---------+
    mov      qword ptr [rsp+28H], rax          |
    xorps    xmm4, xmm4                        |
    movups   xmmword ptr [rsp+30H], xmm4       |
    movups   xmmword ptr [rsp+40H], xmm4       |
    mov      rax, -96                          | ; zero 28H -> B8H
    movups   xmmword ptr [rsp+rax+B0H], xmm4   |
    movups   xmmword ptr [rsp+rax+C0H], xmm4   |
    movups   xmmword ptr [rsp+rax+D0H], xmm4   |
    add      rax, 48                           |
    jne      SHORT  -5 instr                   |
    mov      qword ptr [rsp+B0H], rax ---------+
						
G_M60356_IG02:
    xorps    xmm0, xmm0
    movups   xmmword ptr [rsp+38H], xmm0 ------+
    movups   xmmword ptr [rsp+48H], xmm0       |
    movups   xmmword ptr [rsp+58H], xmm0       |
    movups   xmmword ptr [rsp+68H], xmm0       | ; zero 38H -> B8H
    movups   xmmword ptr [rsp+78H], xmm0       |
    movups   xmmword ptr [rsp+88H], xmm0       |
    movups   xmmword ptr [rsp+98H], xmm0       |
    movups   xmmword ptr [rsp+A8H], xmm0 ------+
    mov      rax, bword ptr [rcx]
    mov      r10d, dword ptr [rcx+8]
    lea      r11, bword ptr [rsp+98H]    ------+
    mov      bword ptr [r11], rax              |
    mov      dword ptr [r11+8], r10d           |
    mov      dword ptr [rsp+60H], -1           |
    mov      dword ptr [rsp+64H], -1           |
    mov      dword ptr [rsp+68H], -1           |
    movsd    xmm0, qword ptr [reloc @RWD00]    | ; assign  
    movsd    qword ptr [rsp+58H], xmm0         | ; in range 28H -> A0H
    mov      dword ptr [rsp+78H], -1           |
                                               |
G_M60356_IG03:                                 |
    movups   xmm0, xmmword ptr [rcx]           |
    movups   xmmword ptr [rsp+28H], xmm0 ------+
```

**Comment by benaadams** [comment]
`DateTimeParse:ParseExact` looks like a post inline zero of `DateTimeResult::Init`

**Comment by benaadams** [comment]
Second zeroing in `DateTimeParse:ParseExact` is an explicit `initobj System.DateTimeResult` call; might be able to change the C#

**Comment by benaadams** [comment]
Can't use `Unsafe.SkipInit<T>` as its a `ref struct` :sad`

**Comment by pentp** [comment]
You can still use the `_ = &local;` trick to get the same effect.

**Comment by benaadams** [comment]
Alas can't do that either as it contains object references
![image](https://user-images.githubusercontent.com/1142958/75697315-cd7af200-5ca4-11ea-9aea-4cba8aba20e6.png)

**Comment by benaadams** [comment]
Can't drop the `initobj` before codegen as don't know if its going to be fully cleared in the prolog until then. Doesn't seem a quick win here 😢

**Comment by pentp** [comment]
Maybe it's actually better to focus on reducing the prolog zeroing by only doing it for GC tracked locals/fields? There were a couple of comments in the PR about this: https://github.com/dotnet/runtime/pull/32538#issuecomment-588462187

`DateTimeResult` has only 6 GC refs (48 bytes + maybe some params?), but 136 bytes are zeroed in the prolog.
This struct could make use of `[StructLayout(LayoutKind.Auto)]` together with reducing the flags and failure enum width to shave off a few bytes maybe and group all GC refs together?

**Comment by benaadams** [comment]
> Maybe it's actually better to focus on reducing the prolog zeroing by only doing it for GC tracked locals/fields?

Would only save a few instructions, would also need to sort the stack locations as GC clearing currently jumps about (though I think you are also suggesting binning the zeroing so xmm could still be used); however it would then still re-zero the whole 128 block; which is still more significant than the savings.

**Comment by erozenfeld** [comment]
I'm seriously considering adding an analysis for the first basic block to detect locals that are initialized there before the first use and before any gc-safe points. Then we'll be able to eliminate redundant zero init in cases like `DateTimeParse:ParseExact` I expect significant wins from that. I hope to get to this in the next couple of weeks.

**Comment by AndyAyersMS** [comment]
@erozenfeld also marking this as 5.0.

**Comment by erozenfeld** [comment]
@benaadams #36918 addresses 
```DateTimeParse:ParseExact(ReadOnlySpan`1,ReadOnlySpan`1,DateTimeFormatInfo,int):DateTime```
case:

```diff
G_M60355_IG01:
       sub      rsp, 184
       vzeroupper 
       xor      rax, rax
-      mov      qword ptr [rsp+28H], rax
+      mov      qword ptr [rsp+38H], rax
       vxorps   xmm4, xmm4
-      vmovdqa  xmmword ptr [rsp+30H], xmm4
       vmovdqa  xmmword ptr [rsp+40H], xmm4
       mov      rax, -96
       vmovdqa  xmmword ptr [rsp+rax+B0H], xmm4
       vmovdqa  xmmword ptr [rsp+rax+C0H], xmm4
       vmovdqa  xmmword ptr [rsp+rax+D0H], xmm4
       add      rax, 48
       jne      SHORT  -5 instr
       mov      qword ptr [rsp+B0H], rax
G_M60355_IG02:
-      vxorps   xmm0, xmm0
-      vmovdqu  xmmword ptr [rsp+38H], xmm0
-      vmovdqu  xmmword ptr [rsp+48H], xmm0
-      vmovdqu  xmmword ptr [rsp+58H], xmm0
-      vmovdqu  xmmword ptr [rsp+68H], xmm0
-      vmovdqu  xmmword ptr [rsp+78H], xmm0
-      vmovdqu  xmmword ptr [rsp+88H], xmm0
-      vmovdqu  xmmword ptr [rsp+98H], xmm0
-      vmovdqu  xmmword ptr [rsp+A8H], xmm0
       mov      rax, bword ptr [rcx]
       mov      r10d, dword ptr [rcx+8]
       lea      r11, bword ptr [rsp+98H]
       mov      bword ptr [r11], rax
       mov      dword ptr [r11+8], r10d
       mov      dword ptr [rsp+60H], -1
       mov      dword ptr [rsp+64H], -1
       mov      dword ptr [rsp+68H], -1
       vmovsd   xmm0, qword ptr [reloc @RWD00]
       vmovsd   qword ptr [rsp+58H], xmm0
       mov      dword ptr [rsp+78H], -1

G_M60355_IG03:
       vmovdqu  xmm0, xmmword ptr [rcx]
       vmovdqu  xmmword ptr [rsp+28H], xmm0
						;; bbWeight=1    PerfScore 3.00
G_M60355_IG04:
       lea      rcx, [rsp+38H]
       mov      qword ptr [rsp+20H], rcx
       lea      rcx, bword ptr [rsp+28H]
       call     DateTimeParse:TryParseExact(ReadOnlySpan`1,ReadOnlySpan`1,DateTimeFormatInfo,int,byref):bool
       test     eax, eax
       je       SHORT G_M60355_IG06
       mov      rax, qword ptr [rsp+90H]
G_M60355_IG05:
       add      rsp, 184
       ret      
G_M60355_IG06:
       lea      rcx, [rsp+38H]
       call     DateTimeParse:GetDateTimeParseException(byref):Exception
       mov      rcx, rax
       call     CORINFO_HELP_THROW
       int3     
RWD00  dq	BFF0000000000000h


-; Total bytes of code 282, prolog size 84, PerfScore 71.27, (MethodHash=de53143c) for method DateTimeParse:ParseExact(ReadOnlySpan`1,ReadOnlySpan`1,DateTimeFormatInfo,int):DateTime
+; Total bytes of code 215, prolog size 78, PerfScore 54.23, (MethodHash=de53143c) for method DateTimeParse:ParseExact(ReadOnlySpan`1,ReadOnlySpan`1,DateTimeFormatInfo,int):DateTime

```

**Comment by erozenfeld** [comment]
Regarding your second example where we first assign to a gc field and then initialize the struct field: currently my optimization doesn't handle that. It's possible to extend it to handle that case but that would require keeping track of field initializations and may be a little tricky.

However, now the answer to your question 
>> Or would changing it to move all the zeroing above that first assignment to non-zero (which would be a much more complex refactoring in Roslyn) help?

is yes.

If the struct field zero initialization was done before the first assignment, it would be eliminated by the new optimization.

**Comment by benaadams** [comment]
💜 Thank you; sounds like this issue would be resolved then and the other fixed by a tweak in Roslyn (though that proved a bit hard when I looked; might give it another go though)

**Comment by benaadams** [comment]
Resolved by https://github.com/dotnet/runtime/pull/36918

Thank you @erozenfeld 🎉

**Comment by benaadams** [comment]
Looks like the tweak in Rosyn https://github.com/dotnet/roslyn/pull/45262 doesn't enable the zero init optimization

```csharp
public async ValueTask<ReadResult> OuterMethod(object o)
{
    return await InnerMethod(o);

}

static async ValueTask<ReadResult> InnerMethod(object o)
{
    return default;
}
```

IL code if easier to work with
```
.method public hidebysig 
	instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult> OuterMethod (
		object o
	) cil managed 
{
	.custom instance void [System.Runtime]System.Runtime.CompilerServices.AsyncStateMachineAttribute::.ctor(class [System.Runtime]System.Type) = (
		01 00 13 43 2b 3c 4f 75 74 65 72 4d 65 74 68 6f
		64 3e 64 5f 5f 31 00 00
	)
	// Method begins at RVA 0x2054
	// Code size 55 (0x37)
	.maxstack 2
	.locals init (
		[0] valuetype C/'<OuterMethod>d__1'
	)

	IL_0000: ldloca.s 0
	IL_0002: call valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<!0> valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult>::Create()
	IL_0007: stfld valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult> C/'<OuterMethod>d__1'::'<>t__builder'
	IL_000c: ldloca.s 0
	IL_000e: ldarg.1
	IL_000f: stfld object C/'<OuterMethod>d__1'::o
	IL_0014: ldloca.s 0
	IL_0016: ldc.i4.m1
	IL_0017: stfld int32 C/'<OuterMethod>d__1'::'<>1__state'
	IL_001c: ldloca.s 0
	IL_001e: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult> C/'<OuterMethod>d__1'::'<>t__builder'
	IL_0023: ldloca.s 0
	IL_0025: call instance void valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult>::Start<valuetype C/'<OuterMethod>d__1'>(!!0&)
	IL_002a: ldloca.s 0
	IL_002c: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult> C/'<OuterMethod>d__1'::'<>t__builder'
	IL_0031: call instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<!0> valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [System.IO.Pipelines]System.IO.Pipelines.ReadResult>::get_Task()
	IL_0036: ret
} // end of method C::OuterMethod

```
Output
```asm
G_M51821_IG01:
       push     rsi
       sub      rsp, 144
       vzeroupper 
       xor      rax, rax
       mov      qword ptr [rsp+28H], rax
       vxorps   xmm4, xmm4
       mov      rax, -96
       vmovdqa  xmmword ptr [rsp+rax+90H], xmm4
       vmovdqa  xmmword ptr [rsp+rax+A0H], xmm4
       vmovdqa  xmmword ptr [rsp+rax+B0H], xmm4
       add      rax, 48
       jne      SHORT  -5 instr
       mov      rsi, rdx
						;; bbWeight=1    PerfScore 8.58
G_M51821_IG02:
       xor      ecx, ecx
       vxorps   xmm0, xmm0
       vmovdqu  xmmword ptr [rsp+38H], xmm0
       vmovdqu  xmmword ptr [rsp+48H], xmm0
       mov      qword ptr [rsp+58H], rcx
       mov      gword ptr [rsp+28H], r8
       mov      dword ptr [rsp+30H], -1
       lea      rcx, [rsp+28H]
       call     System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start(byref)
```

**Comment by benaadams** [comment]
Will raise new issue; have an easier repo

**Comment by benaadams** [comment]
Opened new issue with a simpler repo https://github.com/dotnet/runtime/issues/38070
