### ISSUE TITLE
HttpClient specify interface to bind to / make requests from

### ISSUE THREAD

**Issue by narciero** [dotnet/runtime#23267]
On a machine with multiple NICs, how can i specify (if possible) which interface IP to use for making requests? 

I am sometimes on a server where the default management interface is not connected to the internet, however there are multiple other NICs that are internet-facing that I would like to be able to use. 

With .NET Framework + ServicePointManager I believe you could use [BindIPEndPoint](https://msdn.microsoft.com/en-us/library/ms144146(v=vs.110).aspx).

**Comment by Lewington-pitsos** [comment]
> @tundeanderson It not available for `.NET Core` only. In the classic framework you can use [BindIPEndPoint](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepoint.bindipendpointdelegate)
> 
> Or you can switch to a lower level and use other primitives instead.

Would you be able to specify which "lower level" primitives you were thinking of? I'm not sure where to start looking for alternatives to `HttpClient`

**Comment by georgiosd** [comment]
Amazing that in two years, a feature with all these comments and legit requests hasn't been actioned on. 

Is this even going to be in 5.0 @karelz ?

**Comment by bonesoul** [comment]
@georgiosd also the request is about a common functionality where you expect it have already in by default in any framework / language.

**Comment by georgiosd** [comment]
@bonesoul it's a long thread already with arguments for either side so given that hasn't worked out too well I don't think there's a point in continuing. 

I get @karelz need to prioritize based on what the majority of users "need" but frankly I think it's bad for business to piss any one group of people off for such a long time, no matter how small the group.

**Comment by karelz** [comment]
Things often are not as simple as they seem. This is part of larger proposal (#28721) which morphed into more general solution in #1793 (which is in active development since November - experiments, architecture review rounds, things to consider and unify with ASP.NET models, compromises on the way). So, yes, it will be part of 5.0 unless something super horrible happens (the API is scheduled for larger API review next week).

I am sorry that you've ran into `HttpWebRequest` limitations -- those APIs are compat-only to ease migration from .NET Framework, quite a few of their properties are no-ops. Starting with 5.0 it seems we will have finally built-in mechanism to convey this information to developers in a reasonable way via Roslyn analyzers.

**Comment by shaggygi** [comment]
@karelz  
> So, yes, it will be part of 5.0 unless something super horrible happens (the API is scheduled for larger API review next week).

By chance is this review going to be recorded like Immo usually does?

BTW... looking forward to your ZBB as 5.0 release nears. 😄

**Comment by karelz** [comment]
Yes, it should be part of normal streamed/recorded API review (cc @scalablecory).

**Comment by scalablecory** [comment]
@shaggygi please feel free to review #1793 and participate in API review. Barring last minute rescheduling, we will be reviewing this on 5/12.

**Comment by GuerrillaCoder** [comment]
Is this feature scheduled?

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/1793 is planned for .NET 5 and should address this.

**Comment by scalablecory** [comment]
Closing this -- resolved by https://github.com/dotnet/runtime/issues/1793.

**Comment by scalablecory** [comment]
This has been resolved via the API added here in .NET 5: https://github.com/dotnet/runtime/issues/41949

**Comment by Pro100AlexHell** [comment]
I have simple task - detect remote IP address to which http client is connected. I don't want to DNS resolve, but need exactly remote IP.
I didn't understand how to detect remote IP in net core 3.1.
Also I have no time for reading all of topics regarding breaking changes and new API.

I have found solution for .net - https://stackoverflow.com/questions/6655713/how-to-get-ip-address-of-the-server-that-httpwebrequest-connected-to but it doesn't work as it is for dot net, but not core.

Answer please, my simple question.
I can use WebRequest or HttpClient or anything you suggest.

**Comment by bonesoul** [comment]
@scalablecory is there a sample for usage?

**Comment by stephentoub** [comment]
> is there a sample for usage?

https://github.com/dotnet/runtime/blob/7b93881c6c7725fa77fb71fa58277608bd873399/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L2394-L2401

**Comment by bonesoul** [comment]
for anyone that may be interested a created a sample repo as an example: https://github.com/bonesoul/dotnet_5_httpclient_rest_bind

**Comment by geoffkizer** [comment]
@bonesoul Nice, thanks. BTW you can just create SocketsHttpHandler directly, instead of creating HttpClientHandler and then doing the reflection stuff. The tests do the latter because that's how some of the underlying test infra code is set up.
