### ISSUE TITLE
Consider including AssemblyDefinition/AssemblyReference.GetAssemblyName in netstandard1.1 build

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#23300]
The APIs added by https://github.com/dotnet/corefx/pull/23396 are currently only available in netstandard2.0.

In order to include the APIs in netstandard1.1 we would need to work around the lack of AssemblyName.CultureName setter, which is not available in netstandard1.1. We can use a light-up.

**Comment by steveharter** [comment]
Closing; 5 year old netstandard 1.1 discussion
