### ISSUE TITLE
order of DeclaredMethods

### ISSUE THREAD

**Issue by ufcpp** [dotnet/runtime#2330]
I found order of `DeclaredMethods` is a bit strange when the number of members are greater than 85.

step to repro:

https://gist.github.com/ufcpp/06e2c9e82c0c518b654c0e30eeb9cd63#file-methodorder-cs

expected result:

All of the result of `Console.Write` are

```txt
M00M01M02M03M04M05M06M07M08 ...
```

actual result:

The result using Type.GetMethods/TypeInfo.DeclaredMethods [on .NET Core 3.0](https://gist.github.com/ufcpp/06e2c9e82c0c518b654c0e30eeb9cd63#file-netcoreapp3-0-txt) or later is

```txt
M85M86M87M88M89M00M01M02M03 ...
```

FYI, that [on .NET Core 2.2](https://gist.github.com/ufcpp/06e2c9e82c0c518b654c0e30eeb9cd63#file-netcoreapp2-2-txt) or earlier is as expected.

**Comment by vitek-karas** [comment]
Please note that the user code must not rely on the ordering of the methods returned from reflection - DeclaredMethods is one such example. The API officially specified that the returned order is "undefined". The reason for the differences is that the method doesn't internally sort the list before returning it (for performance reasons), it simply walks the runtime structures. So any change to how the runtime stores these internally will be potentially observable in the order reported through the API. You might also see different order on different platforms (X86/X64, or Windows/Linux, ...). Also note that for example using Ready2Run on the assembly will likely change the order as well.

That said we could track down what exact change in the runtime caused the difference between .NET Core 2.* and .NET Core 3.*, but I don't think it's worth the effort.

**Comment by steveharter** [comment]
Closing; reflection order is non-deterministic.
