### ISSUE TITLE
Use globally defined AssemblyVersion and FileVersion in ilproj

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#2332]
Currently we hardcode the file and assembly version in our IL-only assemblies. See  https://github.com/dotnet/runtime/blob/ec7aac66c36bf12bf649b803568ca882d052205b/src/libraries/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L44.

We should `ifdef` in the .il files and introduce those defines centrally for ilproj project files.

cc @ericstj @Anipik

**Comment by ericstj** [comment]
Small correction: no ifdefs, just define values and use as macro, similar to how we use CORE_ASSEMBLY macro already.

We can generate a header file that defines the assembly version etc, similar to what the SDK already does for C# and VB.   If we wanted to do even better we could move all the assembly attributes that have MSBuild properties out of the checked-in IL file and just generate it.  We'd need to be careful when doing this generation to not break incremental build (only regenerate when things change).

**Comment by ViktorHofer** [comment]
Example: https://github.com/dotnet/runtime/blob/80d8920a54b0d73eb8423fe705583a0fd7ad1723/src/libraries/System.Runtime.CompilerServices.Unsafe/src/include/netcoreapp5.0/coreassembly.h#L8

**Comment by ViktorHofer** [comment]
@Anipik would you be interested in picking this up? We definitely need it, ideally before we branch to net6.

**Comment by Anipik** [comment]
I can pick it up during sometime during next week
