### ISSUE TITLE
Clean up or pragma disable warnings 0169, 0414, and 0649 in System.Private.Xml.csproj

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#23331]
See https://github.com/dotnet/corefx/commit/84c6a81f7d1343a038850c6aa6286bd50f210a29#diff-f942094b67f3b93600fc4729053f8bccR9

The new build of roslyn started catching unused fields.  System.Private.Xml.csproj had too many for me to fix.  Please remove the warnings and either fix these by deleting the unused fields, or pragma disable and add a comment about how they are used if accessed through reflection or kept for serialization (for example).

**Comment by lennartb-** [comment]
What exactly is to do here? I build System.Private.Xml, but can't spot either of the warnings mentioned.

**Comment by ericstj** [comment]
Looks to me like this was already cleaned up with https://github.com/dotnet/runtime/commit/071bb6ba5d1ca9eaca0b07061edaf05ed3c398ef#diff-b4bc4f3b730c582acec0d7fe15ce3d1325dde683bf1ef343474140201b2be95c
