### ISSUE TITLE
[QUIC] open-source QUIC provider

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#2333]
The prototyping efforts for QUIC, HTTP/3 are being done using the "msquic" library.

To make this usable in open-source builds of .NET Core, an open-source quic provider is needed. This allows source-build .NET Core packages to reference/include it.

If there are some QUIC providers that come with popular distros, it would be good to consider those. That avoids having to build yourself, and may cover some security qualification.

cc @scalablecory @anurse @omajid @crummel @dagood @dotnet/ncl

**Comment by tmds** [comment]
@karelz shouldn't this be 5.0 milestone?

**Comment by karelz** [comment]
@tmds we won't be able to ship QUIC in 5.0 milestone -- the spec won't be finalized yet. Hence Future for now.

**Comment by scalablecory** [comment]
🎉🎉🎉 [MsQuic is now Open Source](https://techcommunity.microsoft.com/t5/networking-blog/msquic-is-open-source/ba-p/1345441) 🎉🎉🎉

**Comment by karelz** [comment]
Looks like we can now close this issue ;)

**Comment by tmds** [comment]
> MsQuic is now Open Source

cool!

@karelz @scalablecory are there some thoughts how this lands in a Linux distro so .NET Core can use it?

**Comment by karelz** [comment]
We are keeping it in mind for when we will be ready to productize it fully. I expect second half of the year to have serious discussions about it 
Right now even the OpenSsl dependency does not exist and we are limited by what they do / consider alternatives.

**Comment by omajid** [comment]
OpenSSL is looking into supporting QUIC: https://www.openssl.org/blog/blog/2020/02/17/QUIC-and-OpenSSL

> So in conclusion; QUIC is on our minds, but it will not be included in the OpenSSL 3.0 release. We expect more tangible action to happen after we’ve released OpenSSL 3.0.
