### ISSUE TITLE
Add conversion from Task -> CancellationToken method

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#23346]
There should be a built in way to convert a task to a cancellation token. Tasks can be used to represent one shot events (see https://github.com/dotnet/corefx/issues/16221) and lots of manual code needs to be written to convert a Task to a CancellationToken.

```C#
public class Connection
{
    // This task will continue with the connection is terminated
    public Task ConnectionLifetime { get; }
}

var connection = new Connection();

var buffer = new byte[1024];

var cts = new CancellationTokenSource();

await Task FireToken()
{
  await connection.ConnectionLifetime.NoThrow(); // I want this extension method too
  cts.Cancel();
}

_ = FireToken();

await stream.ReadAsync(buffer, cts.Token);
```

I really just want to write something like:

```C#
// This would require an implicit conversion to CancellationToken
await stream.ReadAsync(buffer, connection.ConnectionLifetime);
```

It could also be a method (extension or otherwise):

```C#
await stream.ReadAsync(buffer, connection.ConnectionLifetime.ToCancellationToken());
```

The benefit of the method would be that you could pass options that determined how the token should fire (only on failure, on any completion etc).

```C#
public class Task
{
     ...
     public CancellationToken ToCancellationToken();
     public CancellationToken ToCancellationToken(TaskContinuationOptions options);
     ...
}
```

Another alternative might be to add an overload to `CancellationTokenSource` but that still sucks and isn't as nice to use as the above method:

```C#
var cts = new CancealltionTokenSource();
cts.CancelAfter(task);
```

/cc @stephentoub

**Comment by stephentoub** [comment]
Thanks for the suggestion.  I'm going to close this.  We don't see this come up frequently enough to warrant additional API here.

**Comment by davidfowl** [comment]
Really? We should do an internal and external search for the following pattern:

```C#
Task.Delay(-1, token)
```

**Comment by stephentoub** [comment]
That's the opposite of AsCancellationToken.  `await Task.Delay(-1, token)` is about creating a Task from a CancellationToken, and as you just highlighted, there's already a method for that.

**Comment by davidfowl** [comment]
Oh my bad. That seems fine. I think I typically see the other way more often...

**Comment by davidfowl** [comment]
> as you just highlighted, there's already a method for that.

Unintuitive though.
