### ISSUE TITLE
Microsoft.XmlSerializer.Generator 2.2.0 - created assemblies are not added to the nuget package

### ISSUE THREAD

**Issue by sheitmann** [dotnet/runtime#2335]
I followed this guide/example https://docs.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator and used the workaround mentioned in #1390 to generate the XmlSerializer assembly.
When I enable the nuget package creation in the project settings the package is created but the XmlSerializer assembly is not included.

**Comment by StephenBonikowsky** [comment]
@sheitmann Thank you for reporting this, looks like we did not anticipate the output of the tool needing to be packaged.
You can probably work around this by manually making sure that the generated assembly gets added to the package .
We will further investigate to determine what's involved for us to fix this on our side.

**Comment by jeffschwMSFT** [comment]
@HongGit .NET 5 ga is into only ship blocking issues.  Is this still on the list for consideration for 5?  If not can you change the milestone appropriately?  Thanks

**Comment by karelz** [comment]
@HongGit are you considering it for 5.0 servicing (5.0.x milestone), or 6.0/Future?

**Comment by StephenMolloy** [comment]
Fixed in 7.0-rc1 by #73550
