### ISSUE TITLE
Add ParallelEnumerable.WithTaskScheduler

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/runtime#23351]
Full .NET has internal method to do PLINQ with [custom scheduler](https://github.com/Microsoft/referencesource/blob/master/System.Core/System/Linq/ParallelEnumerable.cs#L303).  Current .NET Core does not have such method in [ParallelEnumerable](https://github.com/dotnet/corefx/blob/a38c5000be0d4b98445ef43d642614d0e8d8f82d/src/System.Linq.Parallel/src/System/Linq/ParallelEnumerable.cs).

Could we have `WithTaskScheduler` public in `ParallelEnumerable` or any other viable alternative? 
I see that [underlying classes do have task scheduler configuration build in](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/QuerySettings.cs#L28).

Why this is needed?

We have product which did not setup default task scheduler for whole process/appdomain. So we do that that manually. I am afraid to set scheduler process/appdomain wide to avoid regression. Same time I want to use PLINQ instead of Tasks/Parallel, where PLINQ is best fit. But I cannot use PLINQ as customer scheduler is must for us.

Another possible reason for such api is virtual isolation. I have witnessed that applications do more and more isolation not on process/appdomain levels, but in process via type loading and di/ioc containers. Another level of isolation could be done with parallelism, but for this all API should accept custom schedulers.

**Comment by stephentoub** [comment]
I'm going to close this.  We've considered such a WithTaskScheduler method multiple times in the past, and decided against it for reasons like that outlined in https://github.com/dotnet/coreclr/issues/2184#issuecomment-160673747.  And for the purposes of this thread, it sounds like `AsyncLocal<T>` does fit the bill, and the only concern was around what version of .NET was needed for it, but any new methods introduced in PLINQ wouldn't be added to those older .NET's anyway.  Thank you for the discussion.
