### ISSUE TITLE
WindowsRuntimeBufferExtensions.ToArray incorrectly checks Capacity

### ISSUE THREAD

**Issue by jefffhaynes** [dotnet/runtime#23383]
The following code will throw an ArgumentException:

```c#
var buffer = new Windows.Storage.Streams.Buffer(0);
var array = buffer.ToArray();
```

WindowsRuntimeBufferExtensions.ToArray checks the buffer capacity as a precondition, which isn't used in the method.  Obviously the expected behavior would be to return an array of length zero.

I also can't find a unit test for this case.

**Comment by iSazonov** [comment]
@jeffschwMSFT Is WindowsRuntimeBufferExtensions removed from the repository?

**Comment by jeffschwMSFT** [comment]
In .NET 5 Preview 6 we removed the built in WinRT support.  You can see our blog for details (https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-6/).  The WinRT support is now being handled by https://github.com/microsoft/CsWinRT.

cc @AaronRobinsonMSFT @jkoritzinsky

**Comment by iSazonov** [comment]
@jeffschwMSFT Thanks! I wonder that the issue is still open here.

**Comment by jkoritzinsky** [comment]
I think we just missed this issue. I think we should move this issue to microsoft/CsWinRT, but I don't have the right tools installed to do that transfer. @jeffschwMSFT can you port this issue to microsoft/CsWinRT?

**Comment by jeffschwMSFT** [comment]
@jkoritzinsky I think the best option would be to copy this content into a new issue and close this one.

**Comment by AaronRobinsonMSFT** [comment]
Moved to CsWinRT: https://github.com/microsoft/CsWinRT/issues/334
