### ISSUE TITLE
Invariant Arrays

### ISSUE THREAD

**Issue by mjp41** [dotnet/runtime#23393]
# Rationale and Proposed Usage

.NET arrays are covariant.  These leads to many complexities in the implementation of the runtime for dealing with checking if assignments to the array are valid.  For example,
```csharp
object [] a = ...; //A
a[1]= "hello";  //B
```
The assignment labelled `//B` must check if the `a` allows `string`s to be stored in it. If the initialisation, had been:
```csharp
object [] a = new Node[10];
```
this would raise an exception at `//B`.

There are clever/ugly workarounds to remove the runtime type checks, such as https://codeblog.jonskeet.uk/2013/06/22/array-covariance-not-just-ugly-but-slow-too/. But they do not provide nice interop as moving between covariant arrays and invariant arrays using this approach requires coping. 

Generics negates many of the reasons for covariant subtyping on arrays.  Let's add arrays that are invariantly typed, and thus do not require type checks for assignments.

This proposal is to wrap standard covariant arrays with a generic struct to make its use invariantly typed, and thus enable optimization at the runtime level. If we had 
```csharp
InvariantArray<Node> a = new InvariantArray<Node>(10);
```
We would simply not be allowed to cast it to a different type as generic parameters to classes and structs are invariant with respect to subtyping.

I think an initially beneficiary of this addition would be `System.Collections.Generic.List`, where this is used to store lots of objects the runtime type checking can be noticeable.  

# Proposed API
```csharp
public struct InvariantArray<T>
{
    public InvariantArray(T[] array) {}
    public InvariantArray(int length) {}
    public ref T this[int index] { get }
    public int Length { get; }
    public T[] AsArray() { return null; }
    public static implicit operator T[](InvariantArray<T> ia) { return null; }
    public static void Copy<S,U>(InvariantArray<S> dst, U[] src) where U : S {}
    /// Other things from ArrayNative
}
```
This should be expanded to cover most of the things in System.Array.

# Implementation sketch
I believe this could be implemented using similar tricks to those used in `Span`.

```csharp
public struct InvariantArray<T>
{
    private T[] inner;

    public InvariantArray(T[] array)
    {
        if (array.GetType() == typeof(T[]))
        {
            inner = array;
        }
        else 
        {
            throw new Exception();
        }
    }

    public InvariantArray(int length)
    {
        inner = new T[length];
    }

    public ref T this[int index] 
    {
        get
        {
            // Replace with something like the following unverifiable code:
            // ldloc inner
            // ldloc index
            // readonly ldelema T
            return ref inner[index];
        }
    }

    public int Length => inner.Length;

    public T[] AsArray()
    {
        return inner;
    }
    
    public static implicit operator T[](InvariantArray<T> ia)
    {
        return ia.AsArray();
    }

    public static void Copy<S,U>(InvariantArray<S> dst, U[] src) where U : S
    {
        // Implement array copy without requiring type checking
    }

    /// Other things from ArrayNative
}
```

* This could be initially implemented as an internal struct inside CoreCLR, where a few collections could be ported to use it.  Most notably `System.Collections.Generic.List`. This could demonstrate the performance benefits. 
* There may need to be an additional Jit helper to implement the index property efficiently, but I believe this may just work with unsafe IL.  So it could be possible to prototype on Corefxlab as was done with Span.
* This approach would allow zero allocation interop with existing array code, where covariant subtyping has not be used. It is wrapping the covariant array, rather than making an internal wrapper, hence the private field can be returned to get a standard array.

# Issues

* The API needs fleshing out to reach parity with System.Array, but I wanted to gauge if invariant arrays might be taken before doing that work.

**Comment by Neme12** [comment]
I think instead of a separate type, there should be a runtime mode that would disable array variance, and this would be enabled for new projects.
