### ISSUE TITLE
System.Console should support "Indentation Levels"

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#23402]
# Rationale

It is often desired to print text that is properly indented to make it easy to read. However, in order to track indentation across method calls you have to either implement some wrapper class or pass the indentation level around.

As such, `System.Console` should be extended to natively support indentation levels in a similar manner to `Sytem.Diagnostics.Debug`

# Proposal

`System.Console` should be extended to support the following APIs:

```csharp
public static partial class Console
{
    // The indentation character, defaults to ' ' (space)
    public static char IndentChar { get; set; }

    // The indentation level, defaults to and will not decrease below 0
    public static int IndentLevel { get; set; }

    // The number of times `IndentChar` is repeated per `IndentLevel`, defaults to 4
    public static int IndentSize { get; set; }

    // Increases `IndentLevel` by one
    public static void Indent();

    // Decreases `IdentLevel` by one
    public static void Unindent();
}
```

Then, there are two sub-proposals:

## Proposal A

Additionally expose a `public static void WriteIndented()` and `public static void WriteLineIndented()`, each with all of the corresponding overloads that `Console.Write` and `Console.WriteLine` have.

## Proposal B

`System.Console` should internally track when the last `WriteLine` occurred and only prefix the indentation on the next `Write` or `WriteLine`.

This may end up being confusing to some users initially, but reduces the overall new APIs considerably.

**Comment by carlossanlop** [comment]
@tannergooding @bartonjs should the design discussion continue, or should we make the decision of staying with `IndentedTextWriter` as the preferred option to add indentation?

**Comment by tannergooding** [comment]
Likely the latter.
