### ISSUE TITLE
Enable Edit and Continue support for Mac

### ISSUE THREAD

**Issue by therealjohn** [dotnet/runtime#2349]
From what I understand, Edit and Continue (EnC) is only supported in Core CLR on Windows. We'd like to have EnC support for .NET Core projects in Visual Studio for Mac.

**Comment by tommcdon** [comment]
Thanks for the suggestion!  This has shipped as a feature on .NET 8 and is documented on https://learn.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022#support-for-net-applications and https://code.visualstudio.com/docs/csharp/debugging#_hot-reload.
