### ISSUE TITLE
ClientAsyncAuthenticate_MismatchProtocols_Fails - fails with ObjectDisposedException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#2352]
Test: `System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails`

From https://github.com/dotnet/corefx/pull/42027

Test failure on `Windows Build x64_Debug`, specifically netcoreapp-Windows_NT-Debug-x64-(Windows.Nano.1809.Amd64.Open)

https://dev.azure.com/dnceng/public/_build/results?buildId=398356

System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls11, expectedException: typeof(System.IO.IOException))

https://helix.dot.net/api/2019-06-17/jobs/3dbb8c60-c089-470e-a02a-0c5f75146ef9/workitems/System.Net.Security.Tests/console
```text
 System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls11, expectedException: typeof(System.IO.IOException)) [FAIL]
      Assert.IsAssignableFrom() Failure
      Expected: typeof(System.IO.IOException)
      Actual:   typeof(System.ObjectDisposedException)
      Stack Trace:
        /_/src/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs(79,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols serverProtocol, SslProtocols clientProtocol, Type expectedException)
        --- End of stack trace from previous location where exception was thrown ---
  Finished:    System.Net.Security.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Security.Tests  Total: 4397, Errors: 0, Failed: 1, Skipped: 20, Time: 26.038s
----- end Wed 10/23/2019  9:03:05.68 ----- exit code 1 ----------------------------------------------------------

cc @davidsh, @wfurt, @scalablecory, @eiriktsarpalis

**Comment by wfurt** [comment]
I see 3 failures in the last 90 days. All on Windows, last one 1/25

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstressregs 20200712.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=726304&view=ms.vss-test-web.build-test-results-tab&runId=22490830&resultId=138030&paneView=debug)

failed test: System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls11, clientProtocol: Tls, expectedException: typeof(System.Security.Authentication.AuthenticationException))


Error message
~~~
Assert.IsAssignableFrom() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.ObjectDisposedException)


Stack trace
   at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols serverProtocol, SslProtocols clientProtocol, Type expectedException) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs:line 78
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstress2-jitstressregs 20201017.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=857188&view=ms.vss-test-web.build-test-results-tab&runId=27424818&resultId=139687&paneView=debug)

failed test: System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls12, expectedException: typeof(System.Security.Authentication.AuthenticationException))

net6.0-Windows_NT-Release-x64-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open


Error message
~~~
Assert.IsAssignableFrom() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.IO.IOException)


Stack trace
   at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols serverProtocol, SslProtocols clientProtocol, Type expectedException) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs:line 78
--- End of stack trace from previous location ---
~~~

**Comment by karelz** [comment]
Failures during 3/12-5/11 (incl. PRs):

Date | Build / PR | OS | Details
-- | -- | -- | --
4/18 | Official run | Windows.10.Arm64v8.Open | Expected: typeof(System.Security.Authentication.AuthenticationException) <br/> Actual: typeof(System.ObjectDisposedException)
4/29 | Official run | Windows.10.Amd64.Open | Expected: typeof(System.Security.Authentication.AuthenticationException) <br/> Actual: typeof(System.ObjectDisposedException)

**Comment by rzikm** [comment]
No more recent failures with `ObjectDisposedException`, other types of failure of this test are tracked in https://github.com/dotnet/runtime/issues/65098
