### ISSUE TITLE
Unload assembly with shared assemblies.

### ISSUE THREAD

**Issue by cedricmelancon** [dotnet/runtime#2357]
Framework: .Net Core 3.1

I am developing a plugin manager that loads and unloads plugin and I'm having issues while unloading. I have an interface in a nuget package that is used by my host application and the plugin. If I load the interface DLL in an AssemblyLoadContext, I have a problem while casting an instance to the interface (as described in https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#how-are-dependencies-shared).

I tried the solution from the link to put the shared assembly in the default context, but if I do so, the unload hang because of, I presume the shared assembly that is still in use.

What would be the solution to unload of shared assemblies?

Thank you

**Comment by vitek-karas** [comment]
The unload should work as long as nothing holds any reference to the assemblies loaded into the "plugin" context. Having the interface in the default load context should not violate that.

Unless the interface dll holds references to the loaded plugins - that would obviously make it impossible to unload the plugin.

Maybe if you could share a bit more about who holds references to the plugins, or what the plugins do? Note that there are certain parts of the framework which have basically bugs around unloadability and using those with plugins will make the plugins unable to unload. But if your plugin doesn't really do anything yet, this should not happen.
