### ISSUE TITLE
Consider Span<char> overloads on Regex classes

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#23602]
**edit by @ViktorHofer, moved initial post down.**

Spanifying Regex removes (a) unnecessary string allocations that tend to decrease perf and (b) allows different types of Memory to be processed.
**API proposal and implementation:** https://github.com/ViktorHofer/corefx/pull/1

## Proposed APIs
This diff contains the Memory overloads and the MatchEvaluator overloads. See discussion above if we should introduce new ref types for Match, Group & Capture.
```diff
namespace System.Text.RegularExpressions
{
    public partial class Capture
    {
        internal Capture() { }
        public int Index { get { throw null; } }
        public int Length { get { throw null; } }
        public string Value { get { throw null; } }
+       public ReadOnlySpan<char> ValueSpan { get { throw null; } }
        public override string ToString() { throw null; }
    }
    public partial class Match : System.Text.RegularExpressions.Group
    {
        internal Match() { }
        public static System.Text.RegularExpressions.Match Empty { get { throw null; } }
        public virtual System.Text.RegularExpressions.GroupCollection Groups { get { throw null; } }
        public System.Text.RegularExpressions.Match NextMatch() { throw null; }
        public virtual string Result(string replacement) { throw null; }
+       public virtual bool TryResult(string replacement, Span<char> destination, out int charsWritten) { throw null; }
        public static System.Text.RegularExpressions.Match Synchronized(System.Text.RegularExpressions.Match inner) { throw null; }
    }
    public partial class Regex : System.Runtime.Serialization.ISerializable
    {
+       public ref struct SplitEnumerator
+       {
+           public ReadOnlySpan<char> Current { get { throw null; } }
+           public SplitEnumerator GetEnumerator() { throw null; }
+           public bool MoveNext() { throw null; }
+       }
        protected internal System.Collections.Hashtable caps;
        protected internal System.Collections.Hashtable capnames;
        protected internal int capsize;
        protected internal string[] capslist;
        protected internal System.Text.RegularExpressions.RegexRunnerFactory factory;
        public static readonly System.TimeSpan InfiniteMatchTimeout;
        protected internal System.TimeSpan internalMatchTimeout;
        protected internal string pattern;
        protected internal System.Text.RegularExpressions.RegexOptions roptions;
        protected Regex() { }
        protected Regex(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
        public Regex(string pattern) { }
        public Regex(string pattern, System.Text.RegularExpressions.RegexOptions options) { }
        public Regex(string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { }
        public static int CacheSize { get { throw null; } set { } }
        [System.CLSCompliant(false)]
        protected System.Collections.IDictionary Caps { get { throw null; } set { } }
        [System.CLSCompliant(false)]
        protected System.Collections.IDictionary CapNames { get { throw null; } set { } }
        public System.TimeSpan MatchTimeout { get { throw null; } }
        public System.Text.RegularExpressions.RegexOptions Options { get { throw null; } }
        public bool RightToLeft { get { throw null; } }
        public static string Escape(string str) { throw null; }
+       public static bool TryEscape(ReadOnlySpan<char> str, Span<char> destination, out int charsWritten) { throw null; }
        public string[] GetGroupNames() { throw null; }
        public int[] GetGroupNumbers() { throw null; }
        public string GroupNameFromNumber(int i) { throw null; }
        public int GroupNumberFromName(string name) { throw null; }
        protected void InitializeReferences() { }
        public bool IsMatch(string input) { throw null; }
+       public bool IsMatch(ReadOnlySpan<char> input) { throw null; }
        public bool IsMatch(string input, int startat) { throw null; }
        public static bool IsMatch(string input, string pattern) { throw null; }
        public static bool IsMatch(string input, string pattern, System.Text.RegularExpressions.RegexOptions options) { throw null; }
        public static bool IsMatch(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }
+       public static bool IsMatch(ReadOnlySpan<char> input, string pattern, System.Text.RegularExpressions.RegexOptions options = System.Text.RegularExpressions.RegexOptions.None, System.TimeSpan? matchTimeout = null) { throw null; }
        public System.Text.RegularExpressions.Match Match(string input) { throw null; }
+       public System.Text.RegularExpressions.Match Match(ReadOnlyMemory<char> input) { throw null; }
        public System.Text.RegularExpressions.Match Match(string input, int startat) { throw null; }
        public System.Text.RegularExpressions.Match Match(string input, int beginning, int length) { throw null; }
        public static System.Text.RegularExpressions.Match Match(string input, string pattern) { throw null; }
        public static System.Text.RegularExpressions.Match Match(string input, string pattern, System.Text.RegularExpressions.RegexOptions options) { throw null; }
        public static System.Text.RegularExpressions.Match Match(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }
+       public static System.Text.RegularExpressions.Match Match(ReadOnlyMemory<char> input, string pattern, System.Text.RegularExpressions.RegexOptions options = RegexOptions.None, System.TimeSpan? matchTimeout = null) { throw null; }
        public System.Text.RegularExpressions.MatchCollection Matches(string input) { throw null; }
+       public System.Text.RegularExpressions.MatchCollection Matches(ReadOnlyMemory<char> input) { throw null; }
        public System.Text.RegularExpressions.MatchCollection Matches(string input, int startat) { throw null; }
        public static System.Text.RegularExpressions.MatchCollection Matches(string input, string pattern) { throw null; }
        public static System.Text.RegularExpressions.MatchCollection Matches(string input, string pattern, System.Text.RegularExpressions.RegexOptions options) { throw null; }
        public static System.Text.RegularExpressions.MatchCollection Matches(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }
+       public static System.Text.RegularExpressions.MatchCollection Matches(ReadOnlyMemory<char> input, string pattern, System.Text.RegularExpressions.RegexOptions options = RegexOptions.None, System.TimeSpan? matchTimeout = null) { throw null; }
        public string Replace(string input, string replacement) { throw null; }
        public string Replace(string input, string replacement, int count) { throw null; }
+       public bool TryReplace(ReadOnlySpan<char> input, string replacement, Span<char> destination, out int charsWritten, int count = -1) { throw null; }
        public string Replace(string input, string replacement, int count, int startat) { throw null; }
        public static string Replace(string input, string pattern, string replacement) { throw null; }
        public static string Replace(string input, string pattern, string replacement, System.Text.RegularExpressions.RegexOptions options) { throw null; }
        public static string Replace(string input, string pattern, string replacement, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }
+       public static bool TryReplace(ReadOnlySpan<char> input, string pattern, string replacement, Span<char> destination, out int charsWritten, System.Text.RegularExpressions.RegexOptions options = System.Text.RegularExpressions.RegexOptions.None, System.TimeSpan? matchTimeout = null) { throw null; }
        public static string Replace(string input, string pattern, System.Text.RegularExpressions.MatchEvaluator evaluator) { throw null; }
        public static string Replace(string input, string pattern, System.Text.RegularExpressions.MatchEvaluator evaluator, System.Text.RegularExpressions.RegexOptions options) { throw null; }
        public static string Replace(string input, string pattern, System.Text.RegularExpressions.MatchEvaluator evaluator, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }
+       public static bool TryReplace(ReadOnlySpan<char> input, string pattern, System.Text.RegularExpressions.MatchEvaluator evaluator, Span<char> destination, out int charsWritten, System.Text.RegularExpressions.RegexOptions options = System.Text.RegularExpressions.RegexOptions.None, System.TimeSpan? matchTimeout = null) { throw null; }
        public string Replace(string input, System.Text.RegularExpressions.MatchEvaluator evaluator) { throw null; }
        public string Replace(string input, System.Text.RegularExpressions.MatchEvaluator evaluator, int count) { throw null; }
+       public bool TryReplace(ReadOnlySpan<char> input, System.Text.RegularExpressions.MatchEvaluator evaluator, Span<char> destination, out int charsWritten, int count = -1) { throw null; }
        public string Replace(string input, System.Text.RegularExpressions.MatchEvaluator evaluator, int count, int startat) { throw null; }
        public string[] Split(string input) { throw null; }
        public string[] Split(string input, int count) { throw null; }
        public string[] Split(string input, int count, int startat) { throw null; }
+       public SplitEnumerator Split(ReadOnlySpan<char> input, int count = 0) { throw null; }
        public static string[] Split(string input, string pattern) { throw null; }
        public static string[] Split(string input, string pattern, System.Text.RegularExpressions.RegexOptions options) { throw null; }
        public static string[] Split(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }
+       public static SplitEnumerator Split(ReadOnlySpan<char> input, string pattern, RegexOptions options = RegexOptions.None, TimeSpan? matchTimeout = null) { throw null; }
        void System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo si, System.Runtime.Serialization.StreamingContext context) { }
        public override string ToString() { throw null; }
        public static string Unescape(string str) { throw null; }
+       public static bool TryUnescape(ReadOnlySpan<char> str, Span<char> destination, out int charsWritten) { throw null; }
        protected bool UseOptionC() { throw null; }
        protected bool UseOptionR() { throw null; }
        protected internal static void ValidateMatchTimeout(System.TimeSpan matchTimeout) { }
    }
}
```

### Ref struct for Match and siblings (Capture & Group).

I had a discussion with Jan offline and he pointed out that we might want to introduce a `ref struct MatchValue` type that is returned by APIs that take Span/Memory as an input. 

> The problem with just using the current `class Match` is that it gives you unsecure access to the Span. For example, you can send the Match object to other thread and start working on the Span there, while the current thread unwinds and frees the memory.
ref struct MatchValue would avoid this issue
(And also saved the alllocation)

The issues with that is that we currently have the following hiearchy: Match --> Group --> Capture and that Groups and Match contain collections of Captures/Groups.

> Yes, the flip from class to valuetype tends to be like this. E.g. when we have introduced ValueTask to CoreFX, a bunch of parallel ValueSomething types went with it.
It is a topic for API review discussion
One option is to just not have Span version of the APIs that returns these collections or have callbacks

### startat overload

> For things like Regex.Replace, the startat argument means copy everything up to startat to the destination Span, and then run regular Replace that does not take startat method. So this looks like a convenience method to me - it saves you from typing a tiny bit of code in rare cases to achieve the same effect.

Should we add these startat convenience overloads for Span also?
If yes, this commit should be reverted https://github.com/ViktorHofer/corefx/pull/1/commits/bf7d7f986faaa212476ceeac09ab71c8ab6c7fd5

### RegexSplitEnumerator RTL yield order

If you call the Span version of Regex.Split and pass `RegexOptions.RightToLeft` to it the yield order of the enumerator will also be right to left as we start looking for matches from right to left. The current implementation (which is not an enumerator!) reverses the captured strings before returning.

### RegexSplitEnumerator GetEnumerator (see ref diff)
> I'm not aware of any other cases in the BCL where we have a GetEnumerator method like this on a struct enumerator. I understand you want it to be able to directly foreach the results without introducing an enumerable struct to serve as the return type, but I'm not sure this is a pattern we want to introduce. You should be sure to highlight this as part of any API review discussion.

**Comment by michaelherndon** [comment]
Are there any plans to look at adding ReadOnlySpan<char> overloads or a different implementation for Regex for .NET 6?

**Comment by danmoseley** [comment]
@michaelherndon there are not plans for .NET 6. If anyone is passionate about this, the next step is to finalize an API proposal. That would probably need a fair bit of thought -- see detailed comments by @terrajobst above.

One other thing to consider is that there are 2 regex engines (the mode that compiles at runtime and the interpreter). We are considering adding others -- a source generator one, which would be a variation of compiled but at build time using C# instead of ref-emit, and possibly a [DFA based engine which would provide stronger execution time guarantees.](https://github.com/dotnet/runtimelab/tree/feature/regexsrm). Neither of these will be in .NET 6, but the first one is probably funded for post .NET 6, possibly as an out of band release.

**Comment by michaelherndon** [comment]
@danmoseley thanks for the update.  That definitely sounds like a bit of work.

**Comment by michaelherndon** [comment]
I was debating about trying to rewrite C# code based on rails Inflector logic for pluralization and singularization.   Inflector uses a fair amount of regular expressions.  Humanizer has similar logic.  Using ReadOnlySpan<char> for changing code styles and capitalization is pretty straightforward.  

Transforming something like Inflector into a parser to leverage ReadOnlySpan<char> would be a bit of work, so I looking to see if Regex started implementing it to leave it as-is and still benefit from lowering allocations/copies of strings.

**Comment by moh-hassan** [comment]
Four years passed and the issue is still open. I hope it's implemented in NET6.

**Comment by terrajobst** [comment]
At this point it seems unlikely, given that we still don't have a design.

**Comment by electricessence** [comment]
Uhg.  Why!  Why can't this happen?!  It's such a logical step.  Why can't we just provide a `.ValueSpan` (readonly) as part of groups/captures?

**Comment by terrajobst** [comment]
See [my comment](https://github.com/dotnet/runtime/issues/23602#issuecomment-374701936) above. It's not that it can't, just that it requires design work. And generally speaking the run way for .NET 6 is closing.

**Comment by michaelherndon** [comment]
As the rando internet person that bumped the thread:  I get the frustration of a 4-year-old feature request and obviously I do see the benefits of Regex having lower allocations. Conversely, I also get that only so many things can go into the release of a widely used framework that values backwards compatibility.  Even for a company like Microsoft, there are still only so many resources and hours.  

Personally, I'd still take the improvements in System.Security, the new Metrics API, or the elusive Assembly Neutral Interfaces over a new Regex API surface.

**Comment by electricessence** [comment]
Ok... So I have to admit that I'm a bit frustrated at this one.
I've observed that it would be easy to write extensions for this, BUT `Capture.Text` is `internal`.
If it was exposed, then implementing my own `.AsSpan()` would obviously be easy.  Right now, I'm crippled to passing the original source in order to get a `ReadOnlySpan<char>` or `ReadOnlyMemory<char>`.
Is there a serious reason the original `.Text` property is hidden?
Why not just write these simple extensions in .NET now?

**Comment by BenjaBobs** [comment]
This is probably not the solution you're looking for, but since the [source is available](https://source.dot.net/#System.Text.RegularExpressions/System/Text/RegularExpressions/Capture.cs,0de6615fb778fed0,references), you could do some surgery:

```csharp
public static class CaptureSurgery
{
    private static readonly PropertyInfo _textProperty = typeof(Capture).GetProperty("Text", BindingFlags.Instance | BindingFlags.NonPublic);

    public static ReadOnlySpan<char> AsSpan(this Capture capture)
    {
        return ((string)_textProperty.GetValue(capture)).AsSpan();
    }
}
```

Although since the point is improved performance, this is hardly a solution.

**Comment by svick** [comment]
@BenjaBobs If you're worried about performance, create and cache a delegate to the getter. Also, you need to slice the text to get the value of the capture:

```c#
public static class CaptureSurgery
{
    private static readonly Func<Capture, string> _textDelegate =
        typeof(Capture).GetProperty("Text", BindingFlags.Instance | BindingFlags.NonPublic)
            .GetGetMethod(nonPublic: true)
            .CreateDelegate<Func<Capture, string>>();

    public static ReadOnlySpan<char> AsSpan(this Capture capture) =>
        _textDelegate.Invoke(capture).AsSpan(capture.Index, capture.Length);
}
```

**Comment by electricessence** [comment]
@BenjaBobs @svick  I didn't know that was possible!  That's awesome to know.  Thank you!

**Comment by electricessence** [comment]
And just a note, performance? YES (obviously that's important).
Superior memory usage? YES (that's the whole point of this).

**Comment by electricessence** [comment]
@svick What version of .NET has the generic call for `.CreateDelegate<T>()`?  I'm implementing this in .NET Standard.

**Comment by silkfire** [comment]
@electricessence As of right now only .NET, i.e. 5 and 6+.

**Comment by electricessence** [comment]
@silkfire Got it to work in .NET Standard without the generic methods.  I wonder if there's a boxing cost.

**Comment by stephentoub** [comment]
@joperezr, this overlaps with the span work you already did for 7 and with https://github.com/dotnet/runtime/issues/65011. We should determine if there are any other APIs from this we want to add in 7 as part of the span effort or if it's all covered and can be closed.
