### ISSUE TITLE
NTFS Permissons needed to run .NET Core differ from versions and systems

### ISSUE THREAD

**Issue by RomBrz** [dotnet/runtime#2362]
# Issue Title

I'm having problems with some .NET Core versions related to NTFS permissions

# General

Since .NET Framework 4.x and Windows Server 2012 (IIS 8.5), i'm using Application Pool Identity as Microsoft recomendation to have a more secure server publishing:
https://docs.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities
And this works very well, just give the "AppPoolId" the NTFS "Read only" permission to it's home directory and the site/system works great with least permission, giving the server more security.
However, if the application executes something or has to write some files, i need to give explicit NTFS permission to that folder.
When i start to work with .NET Core, i'm giving the same behavior: Application Pool user configured as "Application Pool Identity", and NTFS home directory's permission with "Read Only".
However, recently, i'm having problems with some systems running from .NET Core 2.x to 3.x. Seems like this is not standard to .NET Core framework, to run with less privileges (and i was shocked to see for example https://github.com/dotnet/cli/issues/5262 telling to change to LocalSystem to make it work).
Seems like some libraries are asking more permissions to work. After some debug, i find that i need to give "Traverse" permission on home directory of the system to make it work with "Read Only", because without that Traverse, the system tries to load things from C:\Windows\System32\Inetsrv as "LocalPath" instead of, for example, C:\Inetpub\SYSTEMXXXXXXX.

I tried to find a recomendation of permissions, something "official" to work with NTFS Permissions, i didn't find. So my suggestion to the .NET Core project it's that set the any default .NET Core app/system runs with "Read Only" NTFS permissions, and force libraries to work with that.

Today if you want to put a DLL inside your project, you are "forced" to set NTFS Permission on root folder to Read and Execute, potencially insecure as any code injected in your site could be executed remotely.

**Comment by danmosemsft** [comment]
setting area-interop since sni.dll is loaded with regular managed interop.

**Comment by RomBrz** [comment]
> We don't aim for "fewest permissions"
I know that i'm nobody to disagree with what MS do with it owns products, but in my modest opition, this case wasn't a question about "aiming for fewer permissions", but the fact that this is the default behavior since ASP.NET Framework 2.0 (i have some legacies apps that run with 2.0 and work with "Read" without Traverse), Framework 4.x, Core 1.x, Core 2.x... The apps basically just know the root folder and work with that (maybe using relative paths, i don't know). Something happen with Core 3.x to now just need Traverse.

>  if those require additional permissions then this will sometimes change from release to release
So, if additional permissions could change "from release to release", may i ask that ASP.NET Team make an official documentation about "best practices" and "minimun needed permissions" when running ASP.NET Core?
Because in this case (2.x -> 3.x) troubleshooting the code to understand that "Traverse" on root folder is now needed caused a lot of work. Now i updated my internal documentation about creating ASP.NET Core 3.x applications (as Core 2.x and older doesn't need Traverse, i will not give Traverse to then, following the "fewest permissions needed".)

But, again, @anurse and others, sorry for anything and thanks for helping!

**Comment by jeffschwMSFT** [comment]
@AaronRobinsonMSFT @jkoritzinsky

**Comment by vitek-karas** [comment]
I didn't try to track down which exact package brings in the sni.dll dependency, but what you describe sounds very much like:
* In .NET Core 2.* the dependent packages didn't need native libraries. In this case the app was loading only managed assemblies which are all in the app's base folder.
* In .NET Core 3.* the dependent packages now do have a native library. Since you're probably building the app as "portable", the SDK will put multiple versions of the native library into the output (kind of one for each target platform). To do this it creates the runtime folder and the subtree in it. This means that app is now doing two new things it didn't do in 2.* - it traverses subdirectories and it calls `LoadLibrary` on files from the app's folder. The former requires the traversal permission (I assume), the latter requires the execute permission.

You can probably get around the traversal permission by publishing the app for just one target platform `dotnet publish -r win-x64 --self-contained false`, that should put the native libraries into the base folder (as there is only one version now). But there's no simple way around the execute permission I can think of (other than loading that dependency from some other location for which the user has execute permission).

**Comment by RomBrz** [comment]
@vitek-karas sorry for delaying the answer.
I asked the developer to publishing in this way (only for x64), and this give me the following: The sni.dll was inside the base folder, but in this way i need execute permission for not only sni.dll but other dlls. BUT i didn't need Traverse, as, like you told, everything was inside base folder.

Without the "one target only", i just need execute for the "sni.dll" that was inside other folders, but i didn't need Execute on base folder, but need Traverse.

Unfortunately, seems like Asp.Net Core just need Execute permission instead of "Read" to work, too bad that "this is the way"... 

Maybe if the "dotnet.exe" could execute the dlls instead of the "w3wp.exe" and/or maybe giving only to the "dotnet.exe" the Execute permission instead of entire folder could be a better workaround?
(this happens with roslyn.exe in Asp.Net Framework 4.5.x, i just need to give Execute to the roslyn instead of the entire folder).

**Comment by vitek-karas** [comment]
@RomBrz If you would run the app via `dotnet.exe` it would be a separate process. I think that's possible with ASP.NET, but it comes with a perf cost (as the `w3wp.exe` must forward the request to the other process). And even with that I don't see how using `dotnet.exe` would solve the problem.

I think the reason it requires "Execute" permissions is that CoreCLR uses `LoadLibrary` on definitely the native dlls. We also use it on managed assemblies which are precompiled with Ready2Run (with that the .dll contains not just the managed code but also native code). Publishing the app as self-contained, which is what happens by default if you run `dotnet publish -r win-x64` will include the framework assemblies which are almost all precompiled with R2R. So lot of those dlls will also need "Execute" permission.

You can publish the app as framework dependent (the framework comes from the global location, typically program files) and for a specific platform. Just run `dotnet publish -r win-x64 --self-contained false`. With that I think only the `sni.dll` may need "Execute", but I might be wrong.
