### ISSUE TITLE
PrintingServices.Unix.cs is not thread safe

### ISSUE THREAD

**Issue by mellinoe** [dotnet/runtime#23656]
The function `LoadPrinters` is called in multiple places within this class, and modifies a static Hashtable storing the system's discovered printers. This function may also be called multiple times (even after initialization) if the system does not have any installed printers. It is possible for multiple calls to this function to occur at the same time, which will result in unpredictable problems, because access to the hashtable is not synchronized in any way.

This is unlikely to be a problem in real app code, because it can generally only occur during initialization, and because you need specific circumstances to trigger any issues. I have seen a local test run fail because of this.

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
