### ISSUE TITLE
Regex performance compare with other programming languages

### ISSUE THREAD

**Issue by doggy8088** [dotnet/runtime#23683]
There is a [mariomka/regex-benchmark](https://github.com/mariomka/regex-benchmark) repo that run regex benchmark for different programming languages.  I'm just wondered why **C#** `Regex` performance is the last and way slower than any other programming languages.  Is there any way to speed up `Regex` performance in .NET or any reason why .NET `Regex` is that slow?

**Comment by stephentoub** [comment]
> For what it's worth, here's my results (on Ubuntu) using the benchmark at the top of this issue, targeting 2.2 and with the compile flag switched back on (it looks like they removed it)

@danmosemsft, can you run your test again, but using .NET 5 master?

**Comment by danmosemsft** [comment]
Pasted from https://github.com/mariomka/regex-benchmark/pull/14#issuecomment-623038745

**PHP** | 26.57 | 24.27 | 8.20 | 59.05
**C PCRE2** | 29.40 | 25.70 | 7.15 | 62.25
**Rust** | 30.90 | 29.14 | 8.29 | 68.33
**C++ Boost** | 62.97 | 62.49 | 23.13 | 148.58
**Javascript** | 95.32 | 67.16 | 2.19 | 164.68
**Perl** | 151.18 | 90.58 | 33.98 | 275.74
**Crystal** | 172.62 | 148.42 | 19.01 | 340.04
**C# .Net Core 50 ECMA** | 215.35 | 172.11 | 17.35 | 404.80
**D ldc** | 223.99 | 221.51 | 6.71 | 452.21
**C# .Net Core 50** | 314.79 | 254.98 | 17.40 | 587.17
**D dmd** | 292.91 | 303.55 | 8.84 | 605.29
**Ruby** | 365.49 | 324.14 | 59.95 | 749.58
**Kotlin** | 237.89 | 300.62 | 408.42 | 946.93
**Java** | 233.96 | 317.21 | 429.29 | 980.46
**Python 2** | 317.74 | 210.41 | 521.91 | 1050.06
**Go** | 411.11 | 399.17 | 634.96 | 1445.24
**C++ STL** | 604.55 | 488.13 | 422.20 | 1514.88
**C# .Net Core** | 1504.76 | 1256.17 | 104.65 | 2865.57
**C# Mono** | 3923.71 | 3301.79 | 218.56 | 7444.07

**Comment by iSazonov** [comment]
> since none of the C, Rust, C++ and Java versions are doing Unicode matching.

I wonder if Rust dies not understand Utf8.

**Comment by danmosemsft** [comment]
@iSazonov  see https://github.com/mariomka/regex-benchmark/pull/26

**Comment by danmosemsft** [comment]
Note that https://github.com/dotnet/runtime/pull/35824 should take this down substantially further. But still a fair bit off Rust

**Comment by EgorBo** [comment]
I've tested recent Mono (llvm-jit mode) vs daily .net 5 on this benchmark
Mono is 30% slower than CoreCLR.

**Comment by danmosemsft** [comment]
@EgorBo that woudl be recent Mono with all of @stephentoub improvements to the library, I assume. How does it compare with/without RegexOptions.Compiled. Are both regressed or is it specific to ref-emit?

**Comment by EgorBo** [comment]
> @EgorBo that woudl be recent Mono with all of @stephentoub improvements to the library, I assume. How does it compare with/without RegexOptions.Compiled. Are both regressed or is it specific to ref-emit?

Yes, it's a mono built from `dotnet/runtime` master so it uses all the latest Regex changes.
Numbers for "Compiled" mode:
```
coreclr:
7.1213 - 5
51.5561 - 92
54.7056 - 5301

mono-llvm-jit:
13.63 - 5
86.0223 - 92
87.768 - 5301

mono-jit:
13.1713 - 5
101.0694 - 92
103.0671 - 5301
```

**Comment by danmosemsft** [comment]
Thanks. What's your interpretation of the numbers - is this hitting an area in mono that is known to have a perf gap?

**Comment by EgorBo** [comment]
> Thanks. What's your interpretation of the numbers - is this hitting an area in mono that is known to have a perf gap?

Not sure, had a quick profiler run (via xcode instruments) and it looks a lot of time is spent in GC.

**Comment by eerhardt** [comment]
We did a lot of perf work in this area in 5.0. Can this issue be closed now?

**Comment by danmosemsft** [comment]
I think so - we're doing very substantially better on both regex-redux and the mariomka benchmark. If there's more work, it should probably be driven by a new benchmark or insights. Also, @EgorBo there's a Mono specific issue, that should have it's own issue not least because it would be different engineers working on it. (Perhaps it is important for Blazor? @marek-safar )

**Comment by eerhardt** [comment]
> Perhaps it is important for Blazor?

One of the 3 Blazor test apps we are working with uses Regex - 

https://github.com/SteveSandersonMS/CarChecker/blob/e9c7e7114e7936e38389074f1b5005e4b27a0e8e/Shared/VehiclePart.cs#L43-L50

Note that on WASM, `RuntimeFeature.IsDynamicCodeCompiled` always returns `false`, which means the Regex will never use the IL Compiler and instead will always be interpreted.

https://github.com/dotnet/runtime/blob/54a09d24142864767d50c83c2a64c0e1e37a34c2/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs#L76-L81

**Comment by marek-safar** [comment]
I'm not aware of any regex perf problems/asks for browser
