### ISSUE TITLE
Drive formatting APIs

### ISSUE THREAD

**Issue by jp2masa** [dotnet/runtime#23709]
I searched a lot about this topic, and I think that drive formatting should be supported in .NET Core. I understand that these APIs may seem unnecessary and dangerous, but there are use cases for it.

## Use Cases
My use case is preparing USB drives to boot, in a cross platform way and avoiding the creation of separate processes (which would require a separate application, not managed).

There are probably other use cases, but I can't think of any at the moment.

## Proposed APIs
I suggest something like this:

```cs
namespace System.IO
{
    [Flags]
    public enum FileSystemType
    {
        NTFS,
        FAT32
        // others
    }

    public class DriveInfo
    {
        // Flags or IEnumerable<FileSystemType> ?
        public FileSystemType SupportedFileSystems { get; }
        
        public void Format(FileSystemType fileSystemType);
        public Task FormatAsync(FileSystemType fileSystemType);
    }
}
```

## Open Questions
This would be a dangerous method, what security checks should be done?

**Comment by jkotas** [comment]
This is too specialized API to add to the core platform. It may be a good candidate for a standalone NuGet package.
