### ISSUE TITLE
Proposal for System.Runtime.CompilerServices.ICastable .NET Core public API

### ISSUE THREAD

**Issue by shrah** [dotnet/runtime#23727]
We need the System.Runtime.CompilerServices.ICastable for building the CoreCLR version of [System.Private.Interop](https://github.com/dotnet/corert/blob/master/src/System.Private.Interop/src/System.Private.Interop.CoreCLR.csproj).

**Current Workarounds:**

Today we use a hack by publishing the System.Private.ICastable.dll though myget and consume it from CoreRT.

**Discussion:**

The ideal solution would be to expose it as a public .NET Core API possibly in System.Runtime.InteropServices.dll

**Comment by AaronRobinsonMSFT** [comment]
Closing this issue in lieu of #36654
