### ISSUE TITLE
TextEncoderSettings AllowCharacters '<' '>' don't work with JavaScriptEncoder

### ISSUE THREAD

**Issue by gstester** [dotnet/runtime#2374]
# Issue Title

TextEncoderSettings AllowCharacters '<' '>' don't work with JavaScriptEncoder

# General

Trying to serialize xml string to json don't work as expected. It produces escaped '<' and '>':

```C#
private static void EncodeXml() {
            var data = "<Data><XML><ObjectRevision>1</ObjectRevision></XML></Data>";
            var settings = new TextEncoderSettings();
            settings.AllowRange(UnicodeRanges.All);
            settings.AllowCharacters('<', '>');

            var encoder = JavaScriptEncoder.Create(settings);

            var result = encoder.Encode(data);

            System.Diagnostics.Debug.WriteLine(result);
        }
```

result is:
`\u003CData\u003E\u003CXML\u003E\u003CObjectRevision\u003E1\u003C/ObjectRevision\u003E\u003C/XML\u003E\u003C/Data\u003E`

How we can serialize an xml-field of an object.

ProjectSettings:
Project Sdk="Microsoft.NET.Sdk.Web"

 TargetFramework>netcoreapp3.1

PackageReference Include="Microsoft.Extensions.WebEncoders" Version="3.1.1"

**Comment by GrabYourPitchforks** [comment]
The default `TextEncoderSettings` behavior always disallows `<`, `>`, and `&` as a defense-in-depth mechanism. The reason for this is that it's extremely common for JSON payloads to end up within HTML or within a web page's `<script>` block. This defense-in-depth behavior makes it less likely that malicious payloads can cause XSS vulnerabilities on your web site.

If you wish to suppress this behavior, see https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialize-all-characters. Pay close attention to the _Caution_ section that immediately follows the code sample in that section.
