### ISSUE TITLE
Can something be done about the Microsoft.Tpl.Dataflow package?

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#23792]
[The `Microsoft.Tpl.Dataflow` package](https://www.nuget.org/packages/Microsoft.Tpl.Dataflow/) is outdated and generally shouldn't be used anymore. The replacement is [the `System.Threading.Tasks.Dataflow` package](https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/).

But people keep using the old package (see e.g. https://github.com/dotnet/corefx/issues/202#issuecomment-335470737), not knowing they should switch to the new one. Is there something that can be done  to help those people?

Some options I considered:

1. Add an analyzer to [dotnet/platform-compat](https://github.com/dotnet/platform-compat) that will consider `Microsoft.Tpl.Dataflow` deprecated.
2. Release a new version of `Microsoft.Tpl.Dataflow` that will contain no code of its own and will "redirect" to `System.Threading.Tasks.Dataflow` by having a dependency on it. (And then keep releasing a new version every time `System.Threading.Tasks.Dataflow` updates?)

cc: @stephentoub

**Comment by stephentoub** [comment]
@terrajobst, it looks like NuGet added the necessary feature to properly deprecate packages.  Can you help get that taken care of here?

@svick, I'm not seeing the bad reference in the docs, so either I'm missing it or it's been fixed in the interim.  Is there still an issue there?

**Comment by svick** [comment]
@stephentoub It seems the old MSDN article has been redirected to the updated docs.microsoft.com article since 2018. So I think the docs are okay now.

**Comment by terrajobst** [comment]
> @terrajobst, it looks like NuGet added the necessary feature to properly deprecate packages. Can you help get that taken care of here?

Good call. Done. It will take a few hours before NuGet has updated its caches, tho.

**Comment by stephentoub** [comment]
Thanks, Immo.  Seems like everything here has been done, so I'll close.
