### ISSUE TITLE
Add Microseconds and Nanoseconds to TimeStamp, DateTime, DateTimeOffset, and TimeOnly

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/runtime#23799]
Currently, the value of a single `Tick` in .NET is 100ns, however there is no API surface for accessing microseconds or nanoseconds other than using `Ticks` to manually calculate these numbers. In order to allow for working with these higher precision times, I am proposing the following new APIs:

# Approved API
```csharp
namespace System {
    public struct DateTime {
        /// <exception cref="ArgumentOutOfRangeException">When microsecond is not between 0 and 999.</exception>
        public DateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond);
        /// <exception cref="ArgumentOutOfRangeException">When microsecond is not between 0 and 999.</exception>
        public DateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond, System.DateTimeKind kind);
        /// <exception cref="ArgumentOutOfRangeException">When microsecond is not between 0 and 999.</exception>
        public DateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond, System.Globalization.Calendar calendar);
        /// <returns>The microseconds component, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanoseconds component, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
        /// <exception cref="ArgumentOutOfRangeException">The resulting DateTime is less than DateTime.MinValue or greater than DateTime.MaxValue.</exception>
        public DateTime AddMicroseconds(double value);
    }
    public struct DateTimeOffset {
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTimeOffset(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond, System.TimeSpan offset);
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTimeOffset(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond, System.TimeSpan offset, System.Globalization.Calendar calendar);
        /// <returns>The microseconds component, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanoseconds component, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
        /// <exception cref="ArgumentOutOfRangeException">The resulting DateTimeOffset is less than DateTimeOffset.MinValue or greater than DateTimeOffset.MaxValue.</exception>
        public DateTimeOffset AddMicroseconds(double value);
    }
    public struct TimeSpan {
        public const long TicksPerMicrosecond = 10L;
        public const long NanosecondsPerTick = 100L;
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public TimeSpan(int days, int hours, int minutes, int seconds, int milliseconds, int microseconds);
        /// <returns>The microseconds component, expressed as a value between 0 and 999.</returns>
        public int Microseconds { get; }
        /// <returns>The nanoseconds component, expressed as a value between 0 and 900.</returns>
        public int Nanoseconds { get; }
        /// <returns>The total number of microseconds represented by this instance.</returns>
        public double TotalMicroseconds { get; }
        /// <returns>The total number of nanoseconds represented by this instance.</returns>
        public double TotalNanoseconds { get; }
        /// <exception cref="OverflowException">When value is less than TimeSpan.MinValue or greater than TimeSpan.MaxValue.</exception>
        public static TimeSpan FromMicroseconds(double microseconds);
    }
    public struct TimeOnly {
        /// <param name="microsecond">The microsecond (0 through 999).</param>
        /// <exception cref="ArgumentOutOfRangeException">When microsecond is not between 0 and 999.</exception>
        public TimeOnly(int day, int hour, int minute, int second, int millisecond, int microsecond);
        /// <returns>The microsecond component of the time represented by this instant, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanosecond component of the time represented by this instant, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
    }
}
```

# Original API Proposal
```C#
namespace System {
    public struct DateTime {
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microseconds);
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microseconds, System.DateTimeKind kind);
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microseconds, System.Globalization.Calendar calendar);
        /// <returns>The microseconds component, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanoseconds component, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
        /// <exception cref="ArgumentOutOfRangeException">The resulting DateTime is less than DateTime.MinValue or greater than DateTime.MaxValue.</exception>
        public DateTime AddMicroseconds(int microseconds);
    }
    public struct DateTimeOffset {
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTimeOffset(int year, int month, int day, int hour, int minute, int second, int millisecond, int microseconds, System.TimeSpan offset);
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public DateTimeOffset(int year, int month, int day, int hour, int minute, int second, int millisecond, int microseconds, System.TimeSpan offset, System.Globalization.Calendar calendar);
        /// <returns>The microseconds component, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanoseconds component, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
        /// <exception cref="ArgumentOutOfRangeException">The resulting DateTimeOffset is less than DateTimeOffset.MinValue or greater than DateTimeOffset.MaxValue.</exception>
        public DateTimeOffset AddMicroseconds(int microseconds);
    }
    public struct TimeSpan {
        public const long TicksPerMicrosecond = 10L;
        public const double TicksPerNanosecond = 0.01D;
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public TimeSpan(int days, int hours, int minutes, int seconds, int milliseconds, int microseconds);
        /// <returns>The microseconds component, expressed as a value between 0 and 999.</returns>
        public int Microseconds { get; }
        /// <returns>The nanoseconds component, expressed as a value between 0 and 900.</returns>
        public int Nanoseconds { get; }
        /// <returns>The total number of microseconds represented by this instance.</returns>
        public double TotalMicroseconds { get; }
        /// <returns>The total number of nanoseconds represented by this instance.</returns>
        /// <exception cref="OverflowException">When value starts to approach TimeSpan.MinValue or TimeSpan.MaxValue.</exception>
        public double TotalNanoseconds { get; }
        /// <exception cref="OverflowException">When value is less than TimeSpan.MinValue or greater than TimeSpan.MaxValue.</exception>
        public static TimeSpan FromMicroseconds(double value);
    }
    public struct TimeOnly {
        /// <param name="microsecond">The microsecond (0 through 999).</param>
        /// <exception cref="ArgumentOutOfRangeException">When microsecond is not between 0 and 999.</exception>
        public TimeOnly(int day, int hour, int minute, int second, int millisecond, int microsecond);
        /// <returns>The microsecond component of the time represented by this instant, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanosecond component of the time represented by this instant, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
    }
}
```

# Example Usage
```csharp
public class Samples
{
    public void DateTimeSamples()
    {
        new DateTime(0001, 01, 01, 00, 00, 00, 00, 999).Ticks;      // 9990
        DateTime.Parse("0001-01-01 00:00:00.0009990").Microsecond;  // 999
        DateTime.Parse("0001-01-01 00:00:00.0000009").Nanosecond;   // 900
        DateTime.Zero.AddMicroseconds(999).Ticks;                   // 9990
    }

    public void DateTimeOffsetSamples()
    {
        new DateTimeOffset(0001, 01, 01, 00, 00, 00, 00, 999, TimeSpan.FromHours(-7)).Ticks;        // 9990
        DateTimeOffset.Parse("0001-01-01 00:00:00.0009990 -7").Microsecond;                         // 999
        DateTimeOffset.Parse("0001-01-01 00:00:00.0000009 -7").Nanosecond;                          // 900
        new DateTimeOffset().AddMicroseconds(999).Ticks;                                            // 9990
    }

    public void TimeSpanSamples()
    {
        new TimeSpan(999 * TimeSpan.TicksPerMicrosecond).Ticks;            // 9990
        new TimeSpan((long)(900 * TimeSpan.TicksPerNanosecond)).Ticks;  // 9
        new TimeSpan(0001, 01, 01, 00, 00, 00, 00, 999).Ticks;          // 9990
        TimeSpan.Parse("0001-01-01 00:00:00.0009990").Microsecond;      // 999
        TimeSpan.Parse("0001-01-01 00:00:00.0000009").Nanosecond;       // 900
        TimeSpan.Zero.AddMicroseconds(999).Ticks;                       // 9990
    }
}
```

## Notes
- `TimeSpan.TotalMicroseconds` and `TimeSpan.TotalNanoseconds` return double still since that is what the other `Total` properties return. This could be long but I kept it as double for consistency.
- `TimeSpan.FromMicroseconds` takes a double to keep the API consistent with the other `From` methods.

**Comment by jundl77** [comment]
Regarding use-cases, I'd like to further point out that anytime you measure time in a hot-spinning loop, nanosecond timestamps are very useful. This a pattern that's at the core of two industries a the very least (gaming and finance), and I'm sure there are many others.

As a little anecdote, we used timestamps to order processed work-items in a hot spinning loop, and it turned out that we had many timestamp collisions, due to lack of resolution of the 100ns. I don't think nanoseconds are an edge-case anymore.

**Comment by tarekgh** [comment]
@jundl77 thanks for the feedback. Just to understand more regarding the use-case. in the scenarios you mentioned, can you acquire the time to measure it in nanoseconds? I imagine measuring the time will require getting the current time which usually in 100-nanoseconds and not nanoseconds. no?

**Comment by jundl77** [comment]
@tarekgh Exactly, we would like to measure time with nanosecond precision (and by extension, you might be handed a time with nanosecond precision from another server running somewhere), and right now this is only possible with 100ns precision using .NET from my understanding.

**Comment by Clockwork-Muse** [comment]
Note that no "standard" computer is going to be able to do (much, if at all) better than ~100ns Ticks on a clock at all.

For hot loops in games, they usually use [QPCs](https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps) (on windows, anyways, dunno about Linux) which are _practically_ limited to ~333ns Ticks.

High performance trading computers in theory might have dedicated clock boards, but you're not going to be using C# to run those programs...

**Comment by tannergooding** [comment]
`DateTime` and `TimeSpan` have an internal limit of `100ns` ticks

**Comment by jundl77** [comment]
@Clockwork-Muse sure, but if you do collect nano-second timestamps somewhere, then they are suddenly in your system. If you now pass them on to a windows server, then you do suddenly have them there, and it would be nice if they can be supported out of the box.

**Comment by tannergooding** [comment]
It can be supported already, `DateTime` and `TimeSpan` have constructors that take `ticks` where `1 tick` is `100 ns`. It incurs no conversion cost and is just stored directly (with minimal checks for `DateTime` to ensure the ticks is in range):
* https://source.dot.net/#System.Private.CoreLib/DateTime.cs,943ac78ef8dd0f5f,references
* https://source.dot.net/#System.Private.CoreLib/TimeSpan.cs,9cf98f5e237ce8fb,references

So if you have nanosecond timestamps, you just need to divide by 100 and store (accounting for any rounding if that is desired).

**Comment by tarekgh** [comment]
Yes DateTime/DateTimeOffset/TimeSpan cannot support less than 100ns unit. If need something to support less than that, means cannot be done in such types. but anyway, the proposed APIs here are not about that. The proposed APIs are just to allow create time by specifying microseconds or 100ns. which still can be done.

**Comment by tarekgh** [comment]
@mj1856 I think the proposed APIs are good enough. The only open issue we need to take care with before we proceed is handling the overflow in the following TimeSpan APIs:

```C#
        public double TotalMicroseconds { get; }
        public double TotalNanoseconds { get; }
        public static TimeSpan FromMicroseconds(double value);
```

I think we can limit the double values we are returning to some max/min which will guarantee not overflow when reconstructing the TimeSpan with such values. Also for `FromMicroseconds` we can limit the input to that max/min values too. Of course, we'll have to document the behavior as we'll truncate in some edge cases.
will you have any more concerns if we do that?

**Comment by Thaina** [comment]
Should we also have `double DateTimeOffset.ToUnixTimeSecondsDouble()` ?

Suppose we have `DateTimeOffset` `today 12:30:15.1244` and want to get unix time seconds but with milliseconds as decimal

I would like to have `FromUnixTime***` in all precision that receive `double` too

**Comment by danmoseley** [comment]
@tarekgh @mattjohnsonpint it seems from above this API proposal is almost ready for review with just one question?

Just came across it as @deeprobin would have used it in one of his changes.

**Comment by tarekgh** [comment]
@danmoseley yes this proposal is almost ready. I was waiting for @mattjohnsonpint to know if he is ok with what I mentioned in my comment https://github.com/dotnet/runtime/issues/23799#issuecomment-618041088

**Comment by ChristopherHaws** [comment]
@tarekgh Would it be safe to say that the following changes should be added to the proposal?

```csharp
namespace System {
    public struct TimeOnly {
        /// <exception cref="ArgumentOutOfRangeException">When microseconds is not between 0 and 999.</exception>
        public TimeOnly(int days, int hours, int minutes, int seconds, int milliseconds, int microseconds);
        /// <returns>The microsecond component of the time represented by this instant, expressed as a value between 0 and 999.</returns>
        public int Microsecond { get; }
        /// <returns>The nanosecond component of the time represented by this instant, expressed as a value between 0 and 900.</returns>
        public int Nanosecond { get; }
    }
}
```

**Comment by tarekgh** [comment]
@ChristopherHaws that is a good point. Note that, TimeOnly is limited to 24 hours. Do you think having Micro and Nano seconds support will be beneficiary? Who really will care to get this precision on the time of the day?

**Comment by ChristopherHaws** [comment]
@tarekgh I don't have any personally but it feels weird to add these properties to every "tick" based type except this one. I suppose you could say "who cares" about Milliseconds too but that was included. I could see scientific workloads maybe needing this level of precision. :)

**Comment by mattjohnsonpint** [comment]
Sorry, I hadn't really looked too close at this until now.  My only real concern is consistency.  In light of #66815, learning about how `TimeSpan.FromSeconds` was rounding to the nearest millisecond, even having a `TimeSpan.FromMicroseconds` is strange, unless all of them (including `TimeSpan.FromSeconds`, `DateTime.AddSeconds`, etc.) have their rounding logic removed.  Or rather, they should keep as much precision as possible, and not apply arbitrary rounding - even if that's a breaking behavior from what they did in the past.

Otherwise, fine by me. 👍

**Comment by tarekgh** [comment]
Looks we are good with the proposal then. We are tracking fixing the rounding issue that @mattjohnsonpint mentioned in https://github.com/dotnet/runtime/issues/66815. 

@ChristopherHaws I don't mind adding TimeOnly part to the proposal. Please update the proposal with the final and let me know. Thanks.

**Comment by ChristopherHaws** [comment]
@tarekgh I've added the TimeOnly bits to the proposal. Thanks!

**Comment by billknye** [comment]
Regarding this added method:
```C#
public DateTimeOffset AddMicroseconds(double value);
```
On `DateTimeOffset` the parameters are the unit and not just `value`:
https://apisof.net/catalog/1f37f3b1-c31e-90f9-990a-f9fc968b0752
```C#
public DateTimeOffset AddSeconds(double seconds);
```

**Comment by Thaina** [comment]
Do we have any plan for time that more precise than tick in any future?

I just wonder than the `TimeOnly` still have tick precision, while some system represent time in nanosec and we need to convert it to tick, which then lose their precision

**Comment by tannergooding** [comment]
> Do we have any plan for time that more precise than tick in any future?
>
> I just wonder that the TimeOnly still have tick precision, while some system represent time in nanosec and we need to convert it to tick, which then lose their precision

Just because the underlying OS API returns `nanoseconds` doesn't mean the hardware actually supports `nanoseconds`. Most hardware/operating systems have about a 100-300ns latency on querying the hardware timer + normalizing it to account for frequency changes, cross-core queries, etc. Anything more precise and you start hitting latency issues with the actual instructions as well.

Nanosecond level accuracy requires a 1GHz timer and the ability to query and return that information on the CPU in the same amount of time. Considering that most CPUs are 2-3GHz (and the world record is 8.7GHz), this would require the ability to query the information from user mode and return it in under `10 cycles`, which is less latency than cached memory access in many cases.

Users, realistically, shouldn't expect or rely on nanosecond level precision and I doubt that will substantially change (outside extremely domain specific scenarios) in any near future.

**Comment by tannergooding** [comment]
> Users, realistically, shouldn't expect or rely on nanosecond level precision and I doubt that will substantially change (outside extremely domain specific scenarios) in any near future.

Also noting that users shouldn't even really try to rely on `100ns` level accuracy as the latency required to query the OS API is often up to 300ns. Its generally "safe"/"best" to try and target microsecond (at most) if you are wanting to do "high performance" work. There are many other considerations required even for accurate `microsecond` level accuracy, such as upping the process/thread priority and often opting into various multimedia light-up APIs.

**Comment by Thaina** [comment]
> > Do we have any plan for time that more precise than tick in any future?
> > I just wonder that the TimeOnly still have tick precision, while some system represent time in nanosec and we need to convert it to tick, which then lose their precision
> 
> Just because the underlying OS API returns `nanoseconds` doesn't mean the hardware actually supports `nanoseconds`. Most hardware/operating systems have about a 100-300ns latency on querying the hardware timer + normalizing it to account for frequency changes, cross-core queries, etc. Anything more precise and you start hitting latency issues with the actual instructions as well.
> 
> Nanosecond level accuracy requires a 1GHz timer and the ability to query and return that information on the CPU in the same amount of time. Considering that most CPUs are 2-3GHz (and the world record is 8.7GHz), this would require the ability to query the information from user mode and return it in under `10 cycles`, which is less latency than cached memory access in many cases.
> 
> Users, realistically, shouldn't expect or rely on nanosecond level precision and I doubt that will substantially change (outside extremely domain specific scenarios) in any near future.

It's not about precision of the hardware but precision of the data we get from the system. To be honest I just get the time in nanosec from firebase database. Which manage their timestamp data in that precision

Arguably firebase also not really that precise on their time, they also always convert their `timeStamp` into C# `DateTimeOffset`. But they could use that time for ID and proof of edit. And I just thought that it might be possible to use that precise time as a data in database. It will become problem when try to query for it. Suppose there is scientist record nanosec precision data from LHC in database for example

**Comment by deeprobin** [comment]
> We appreciate that. Do you think you can get this soon? I am asking because I would like to include these APIs in our next > preview to have a chance of getting early feedback.

@tarekgh 

I think this week should still be feasible. 
I would start right away because I would like to consume this API as well since I had to 'workaround' this in another PR - See https://github.com/dotnet/runtime/pull/64860#discussion_r831729020.

**Comment by tannergooding** [comment]
It would need to be an independent proposal. My own view is that its not worth exposing such domain specific functionality and that's better relegated to a community provide NuGet package or domain specific code solution.

You should feel free to open an API proposal and note that others may have their own view/opinion.

**Comment by deeprobin** [comment]
@tarekgh 

The constructor using `Calender` uses `ToDateTime(int year, int month, int day, int hour, int minute, int second, int millisecond)`.

This is based on an abstract method which is Public API.
Thus the calendar overload would also need a new API in `Calendar`.

With the current API, our only option is to ignore the `microsecond` parameter in the constructor in conjunction with `Calendar`.

I would propose:
```cs
public virtual DateTime ToDateTime(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond, int era);
```

See https://github.com/dotnet/runtime/blob/16b2cf5baa8c14650261f957d7ea31d4ae723561/src/libraries/System.Private.CoreLib/src/System/Globalization/Calendar.cs#L616

**Comment by tarekgh** [comment]
@deeprobin

Let's not block on that. We can just use `ToDateTime(int year, int month, int day, int hour, int minute, int second, int millisecond)` and manually add the extra ticks passed in the microseconds parameter inside the DateTime constructor. This still will hold correct result.

**Comment by ChristopherHaws** [comment]
> ```cs
> public DateTimeOffset AddMicroseconds(double value);
> ```

@bartonjs The other `DateTimeOffset` methods use the unit name instead of value (its the opposite of `DateTime`). Should we switch this one back to `microseconds` for consistency?

```csharp
public struct DateTimeOffset : IComparable, IComparable<DateTimeOffset>, IEquatable<DateTimeOffset>, IFormattable
{
    public DateTimeOffset AddMilliseconds(double milliseconds);
}
```

**Comment by tarekgh** [comment]
@ChristopherHaws this is already noted here https://github.com/dotnet/runtime/issues/23799#issuecomment-1089090379 and I am already following up. Let's go with `public DateTimeOffset AddMilliseconds(double milliseconds);` and will let you know if there will be any objection.

**Comment by ChristopherHaws** [comment]
@tarekgh Perfect. Would you like me to update my original proposal with the changes? Thanks!

**Comment by tarekgh** [comment]
> Would you like me to update my original proposal with the changes?

Sure, I appreciate that.  Keeping the old one is good too for the record. I mean you can have 2 sections, one titled with `Approved Proposal` and the second titled with `Original Proposal`.

**Comment by ChristopherHaws** [comment]
Also in the [review meeting](https://youtu.be/WuIdjTRbD50?t=581), you talked about the overflow exception on `TotalNanoseconds` being wrong. Should this exception be removed as well?

```csharp
public struct TimeSpan {
    /// <returns>The total number of nanoseconds represented by this instance.</returns>
    /// <exception cref="OverflowException">When value starts to approach TimeSpan.MinValue or TimeSpan.MaxValue.</exception>
    public double TotalNanoseconds { get; }
}
```

**Comment by tarekgh** [comment]
> in the [review meeting](https://youtu.be/WuIdjTRbD50?t=581), you talked about the overflow exception on TotalNanoseconds being wrong. Should this exception be removed as well?

Yes, please remove it. We'll have the triple slashes docs on the new APIs reviewed to match the final behavior. 

> BTW, thanks for all your work on this issue. It's been 5 years in the making! I'm excited to get my hands on this in the next preview (hopefully) :)

Thanks to you too and all community members contributed to this issue. I am excited too to see these new APIs in the product.

**Comment by deeprobin** [comment]
> Thanks to you too and all community members contributed to this issue. I am excited too to see these new APIs in the product.

@tarekgh 

I have basically implemented the proposal. Only a few small things like tests and the reference assembly are missing. These will come tomorrow.

But if I may give you a little foretaste: [My branch](https://github.com/deeprobin/runtime/tree/issue-23799)

**Comment by tarekgh** [comment]
@deeprobin cool!

I'll wait for the official PR. Take your time for adding the tests and doing any polishing there. Thanks for your help!

**Comment by tarekgh** [comment]
@deeprobin thanks for your comment https://github.com/dotnet/core/issues/7378#issuecomment-1099456830, that issue intended to list the preview 4 release notes and not of discussions. Could you move this comment here instead?

**Comment by deeprobin** [comment]
@tarekgh done 👍🏼 

> _@tarekgh With pleasure. It makes me happy every time to improve the .NET ecosystem a bit more._ _I now also follow up with yet another API for the next preview:_
> ## .NET Libraries: Use TimeSpan everywhere we use an int for seconds, milliseconds, and timeouts (Group 1/3) [dotnet/runtime#64860](https://github.com/dotnet/runtime/pull/64860)
> 
> ```cs
> namespace System {
>     public static class GC {
>        public static GCNotificationStatus WaitForFullGCApproach(TimeSpan timeout);
>        public static GCNotificationStatus WaitForFullGCComplete(TimeSpan timeout);
>     }
> }
> 
> namespace System.ComponentModel.DataAnnotations {
>     public class RegularExpressionAttribute {
>        public TimeSpan MatchTimeout { get; } 
>     }
> }
> 
> namespace System.Diagnostics {
>     public class Process {
>        public bool WaitForExit(TimeSpan timeout);
>        public bool WaitForInputIdle(TimeSpan timeout);
>     }
> }
> 
> namespace System.IO {
>     public class FileSystemWatcher {
>        public WaitForChangedResult WaitForChanged(WatcherChangeTypes changeType, TimeSpan timeout);
>     }
> 
>     public sealed class NamedPipeClientStream : PipeStream {
>        public void Connect(TimeSpan timeout);
>        public Task ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken);
>     }
> }
> 
> namespace System.Net.NetworkInformation {
>     public class Ping {
>        public PingReply Send(IPAddress address, TimeSpan timeout, byte[]? buffer, PingOptions? options);
>        public PingReply Send(string hostNameOrAddress, TimeSpan timeout, byte[]? buffer, PingOptions? options);
>        public Task<PingReply> SendPingAsync(IPAddress address, TimeSpan timeout, byte[]? buffer, PingOptions? options, CancellationToken cancellationToken);
>        public Task<PingReply> SendPingAsync(string hostNameOrAddress, TimeSpan timeout, byte[]? buffer, PingOptions? options, CancellationToken cancellationToken);
>     }
> }
> 
> namespace System.Net.Sockets {
>     public class NetworkStream : Stream {
>        public void Close(TimeSpan timeout);
>     }
> 
>     public class Socket {
>        public bool Poll(TimeSpan timeout, SelectMode mode);
>        public static void Select(IList checkRead, IList checkWrite, IList checkError, TimeSpan timeout);
>     }
> }
> 
> namespace System.ServiceProcess {
>     public class ServiceBase {
>        public void RequestAdditionalTime(TimeSpan time);
>     }
> }
> 
> namespace System.Threading.Tasks {
>     public class Task {
>        public bool Wait(TimeSpan timeout, CancellationToken cancellationToken);
>     } 
> } 
> 
> namespace System.Timers {
>     public class Timer {
>        public Timer(TimeSpan interval);
>     }
> }
> ```
> 
> /cc @danmoseley @reflectronic
