### ISSUE TITLE
Broke ability to use RuntimeFlavor in local builds

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#23800]
Execute the following command:

```cmd
.\build.cmd /p:RuntimeFlavor=Mono
```
Will lead to the following error:

> P:\runtime\eng\liveBuilds.targets(91,5): error : The CoreCLR artifacts path does not exist 'P:\runtime\artifacts\bin\coreclr\Windows_NT.x64.netcoreapp5.0-Windows_NT-Debug\'. The CoreCLR subset category must be built before building this project. [P:\runtime\src\libraries\System.Reflection.Primitives\src\System.Reflection.Primitives.csproj]

There are two issues at hand here that need to be addressed:
1. The runtime configuration logic in our build files is not properly accounting for times when `$(Configuration)` is set but `$(ConfigurationGroup)` is not. 
1. There are still places in the build logic that do not properly condition grabbing runtime files based on the chosen runtime

This was a regression introduced with #2093. That means we have the following chain of sadness: PR #1934 leads to runtime config breaks leads to #2093 which leads to this.

**Comment by akoeplinger** [comment]
Is there still something to be done after https://github.com/dotnet/runtime/pull/24077? seems to be working here.

**Comment by jaredpar** [comment]
@akoeplinger 

I was keeping it open for the second part of the issue 

> There are still places in the build logic that do not properly condition grabbing runtime files based on the chosen runtime

That's a separate issue. Can track separately.
