### ISSUE TITLE
Proposal : Full RFC 4122  for Guids

### ISSUE THREAD

**Issue by sandorfr** [dotnet/runtime#23868]
# Description
Provide full implementation of [RFC 4211](https://tools.ietf.org/html/rfc4122) for UUID as part of the Guid type.

Having hash based predictible Guids (v5) which could be derived from string and don't collide with random based guids (v4) can be extremely useful in some scenarios. RFC4122 proposes a standard around UUIDs to address that.

# Possible Use Cases

Here are some of the use cases I see:
* Slug projection to Guid primary key (eliminate the need to maintain an index for that matter, allows using the primary key which is usually the clustered index to get the data)
* Mixing potentially identical ids but namespaced in the same keyspace.
* Reducing a composite key to a single Guid.
* More broadly every scenario where a hash is a good fit (not from a security perspective) but where we need guids. 

# Proposed API
```
public partial struct Guid {
    public static readonly Guid DnsNamespace // 6ba7b810-9dad-11d1-80b4-00c04fd430c8
    public static readonly Guid UrlNamespace // 6ba7b811-9dad-11d1-80b4-00c04fd430c8

    public static Guid NewGuid();

    public static Guid NewUuidV1();
    public static Guid NewUuidV4();
    public static Guid NewUuidV5(string value, Guid namespace);
    public static Guid NewUuidV5(byte[] value, Guid namespace);
}
```
# Details
We would obviously keep the existing NewGuid() which in windows calls [`UuidCreate`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379205(v=vs.85).aspx). It seems that it uses UUID v4 under the hood.

In addition we would add NewGuidV1, NewGuidV4 et NewGuidV5 methods. They would map to the adequate UUID generation method.

# Related Issues

# Open Questions
Currently the byte order from the constructor and [ToByteArray is a bit unatural as it just reflect the underlying struct](https://stackoverflow.com/questions/10190817/guid-byte-order-in-net) as we could expect a more natural byte order. It could be worth it to add methods overload to read and write guid using the natural order.

# See also
* Current implementation:
 [part 1](https://source.dot.net/#System.Private.CoreLib/shared/System/Guid.cs,b622ef5f6b76c10a) and [part 2](https://source.dot.net/#System.Private.CoreLib/src/System/Guid.CoreCLR.cs,b622ef5f6b76c10a) 
* [Node JS implementation](https://www.npmjs.com/package/uuid)
* [Unoptimized quick and dirty Guid V5 c# implementation](https://github.com/geeklearningio/gl-dotnet-primitives/blob/feature/guid-v5/src/GeekLearning.Primitives/GuidV5.cs)

# Updates
* December 12, 2017: Provide a first API proposal
* January 18, 2017: Add use cases

**Comment by om-ha** [comment]
For reference, found a good implementation [here](https://github.com/StephenCleary/Guids)

**Comment by om-ha** [comment]
Please note version 4 requires specific bitwise manipulation. Also to be cryptographically secure it must not be generated with `Guid.NewGuid();`

**Comment by sandorfr** [comment]
> For reference, found a good implementation [here](https://github.com/StephenCleary/Guids)

Nice. The real problem here is to get the proposal/API approved to make this a thing :)

**Comment by om-ha** [comment]
@sandorfr In fact I ended up using [GuidOne](https://github.com/myquay/GuidOne). Which accounts for Endianness unlike other libraries. It completed my Stackoverflow answer [here](https://stackoverflow.com/a/59437504/10830091).

**Comment by SamuelEnglard** [comment]
I'm happy to provide my implementation if wanted.

**Comment by GrabYourPitchforks** [comment]
Thanks all for the discussion. Some random thoughts on this:

- I don't think we should add any surface area to the `Guid` type. If we add factory methods, it's going to add confusion. "What's the difference between all of these, and which one should I use?" is going to come up.

- For the same reason, I wouldn't add a `Uuid` type. The range of valid `Guid` and `Uuid` values would be identical, so IMO there's no reason to have two exchange types. It would again lead to confusion.

- Creation of a v5 UUID involves using the SHA-1 hash algorithm. Introducing new code paths that leverage SHA-1 is generally forbidden across Microsoft codebases unless it's needed for some core compatibility or interop scenario. The demand for version 5 UUIDs is not high enough to justify an exception here.

Given all of these I'm inclined to say that we should close this issue. If there's evidence that there's significant community need for this functionality and that it's too onerous for devs to roll the implementation themselves, then we should reconsider. But so far I don't think either threshold is met.

**Comment by PSanetra** [comment]
> I don't think we should add any surface area to the Guid type. If we add factory methods, it's going to add confusion. "What's the difference between all of these, and which one should I use?" is going to come up.

I think that is just a reason to document those new methods.

> For the same reason, I wouldn't add a Uuid type. The range of valid Guid and Uuid values would be identical, so IMO there's no reason to have two exchange types. It would again lead to confusion.

I agree

> Creation of a v5 UUID involves using the SHA-1 hash algorithm. Introducing new code paths that leverage SHA-1 is generally forbidden across Microsoft codebases unless it's needed for some core compatibility or interop scenario. The demand for version 5 UUIDs is not high enough to justify an exception here.

I guess the reason behind avoiding SHA-1 is that it is partially broken for cryptographic use cases. In case of creating UUID v5 this seems to be irrelevant as the hash is truncated to 128 bit anyway for creating the UUID.

**Comment by SamuelEnglard** [comment]
> I don't think we should add any surface area to the `Guid` type. If we add factory methods, it's going to add confusion. "What's the difference between all of these, and which one should I use?" is going to come up.

Personally, I agree

> For the same reason, I wouldn't add a `Uuid` type. The range of valid `Guid` and `Uuid` values would be identical, so IMO there's no reason to have two exchange types. It would again lead to confusion.

I disagree. This is a square and rectangle case. All `Guid`s are valid `Uuid`s but not all `Uuid`s are valid `Guid`s. 

> Creation of a v5 UUID involves using the SHA-1 hash algorithm. Introducing new code paths that leverage SHA-1 is generally forbidden across Microsoft codebases unless it's needed for some core compatibility or interop scenario. The demand for version 5 UUIDs is not high enough to justify an exception here.

v3 UUID is created using MD5, another cracked algorithm. I would argue that since in both cases it is not being used for cryptography but ID usage.

> Given all of these I'm inclined to say that we should close this issue. If there's evidence that there's significant community need for this functionality and that it's too onerous for devs to roll the implementation themselves, then we should reconsider. But so far I don't think either threshold is met.

How often this is needed I can't say, but implementing correctly can be a pain, even more so if you must do so in a performant way.

**Comment by sandorfr** [comment]
> I don't think we should add any surface area to the Guid type. If we add factory methods, it's going to add confusion. "What's the difference between all of these, and which one should I use?" is going to come up.

I strongly disagree with this one. That's a terrible reason not to offer an API. Yes there will be people who can't read the docs, it's not for them that you should design things.

>  Introducing new code paths that leverage SHA-1 is generally forbidden across Microsoft codebases unless it's needed for some core compatibility or interop scenario.

SHA-1 vulnerability in the context of cryptography really is irrelevant here.

> If there's evidence that there's significant community need for this functionality and that it's too onerous for devs to roll the implementation themselves, then we should reconsider. But so far I don't think either threshold is met.

Given how long it's been opened and the low activity and reactions on this, I agree with this one. 
Also there's some decent implementations in some packages mentioned above.

**Comment by GrabYourPitchforks** [comment]
> I would argue that since in both cases it is not being used for cryptography but ID usage.

> SHA-1 vulnerability in the context of cryptography really is irrelevant here.

@SamuelEnglard @sandorfr I understand the arguments here, but "it's not used for cryptographic purposes" is not a valid argument for granting an exception. "Broken" algorithms like SHA1 are __forbidden for all purposes__ across Microsoft code bases unless it's needed for legacy compat reasons or to support some core scenario for the product. (That last category is generally for allowing things like networking protocols.)

Unless we can demonstrate clearly that usage of MD5 or SHA1 in UUID generation is a critical scenario that we absolutely must support, we would not get signoff from release management to ship this functionality.

**Comment by SamuelEnglard** [comment]
> I understand the arguments here, but "it's not used for cryptographic purposes" is not a valid argument for granting an exception. "Broken" algorithms like SHA1 are forbidden for all purposes across Microsoft code bases unless it's needed for legacy compat reasons or to support some core scenario for the product. (That last category is generally for allowing things like networking protocols.)

I can't say I agree but at the same time I'm not the person who implemented these rules.

> Also there's some decent implementations in some packages mentioned above.

Getting approval to include a dependency for exactly one type isn't always easy. If it comes as part of .NET though, no arguing needed.

**Comment by KalleOlaviNiemitalo** [comment]
.NET Runtime already implements a SHA-1 GUID algorithm as part of EventSource, albeit with a hardcoded namespace. I guess that is justified by legacy compat. <https://github.com/dotnet/runtime/blob/53976d38b1bd6917b8fa4d1dd4f009728ece3adb/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1525-L1714>

**Comment by GrabYourPitchforks** [comment]
> I guess that is justified by legacy compat.

Correct. You have no idea the sheer amount of paperwork we have to deal with every single release because of this and other compat-only usages. There's an increasing amount of bureaucracy every year. I think the goal is to make it so obnoxious that at a certain point we relent and say "fine, we're yanking it!" :)

**Comment by mdonoughe** [comment]
Note: the EventSource implementation of this algorithm is not compliant with the RFC. It generates UUIDs that match ETW, which is what matters for EventSource, but it does not generate UUIDs that match standard implementations. The problems are related to endianness of the byte arrays and not setting the RFC variant flag.

**Comment by GrabYourPitchforks** [comment]
Triaged this morning with the area owners. We don't believe this belongs in the BCL, and as mentioned in this thread there are good fully-featured packages in the ecosystem which provide this capability.
