### ISSUE TITLE
Assembly.EscapedCodeBase does not correctly escape

### ISSUE THREAD

**Issue by bitbonk** [dotnet/runtime#2395]
The Property `Assembly.EscapedCodeBase` does not always return a path that is correctly escaped when the path contains the `#` character under Windows (I haven't tried this in any other OS).

When I run an a simple `notecoreapp3.1` console application if a folder named `C:\temp\C#\ConsoleApp1`, the following code

```
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(Assembly.GetEntryAssembly().EscapedCodeBase);
    }
}
``` 

Will yield the following text which is **not escaped correctly**: 
`file:///C:/temp/c#/ConsoleApp1/ConsoleApp1/bin/Debug/netcoreapp3.1/ConsoleApp1.dll`

Running exaclty the same code under .NET 4.6.1 will yield the following text which is **escaped correctly**:
`file:///C:/temp/c%23/ConsoleApp1/ConsoleApp1/bin/Debug/ConsoleApp1.exe`

This breaks a lot of code for us because we need to determine the actual location of the entry assembly, which to my knowledge can only be done 100% reliably (because of shadow copying) by using `EscapedCodeBase` in Combination with `System.Uri.LocalPath`:

``` 
var entryAssemblyActualDirectory = 
    Path.GetDirectoryName(new Uri(Assembly.GetEntryAssembly().EscapedCodeBase).LocalPath);
```

Because the string passed to the `Uri` constructor is not properly escaped, `LocalPath` will return a truncated string.

**Comment by jkotas** [comment]
`Assembly.CodeBase` and `Assembly.EscapedCodeBase` properties have many problems. Please avoid using them. We are going to mark them as obsolete - https://github.com/dotnet/corefx/issues/41695 .

**Comment by bitbonk** [comment]
@jkotas How can I get the actual location of an assembly in the current process then? In a way that works even when the assembly was shadow copied?

**Comment by jkotas** [comment]
There is not 100% reliable way to do that in .NET Framework. `Assembly.Codebase` can lie in number of different ways. For example, it can be the `http://...` URL that the assembly was download from in some cases.

**Comment by bitbonk** [comment]
@jkotas So according to the issues you linked, the normal `Assembly.Location` should be a reliable way in .NET Core, correct?

**Comment by jkotas** [comment]
Correct.
