### ISSUE TITLE
Test failure on some platforms when (de)serializing Queue, Stack

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#2396]
Creating this to flag tests as `ActiveIssue` to unblock PR https://github.com/dotnet/runtime/pull/2259

These tests are failing:
```
System.Text.Json.Serialization.Tests.ValueTests.ReadPrimitiveQueue
System.Text.Json.Serialization.Tests.ValueTests.ReadStackOfArray
System.Text.Json.Serialization.Tests.ValueTests.ReadGenericStackOfStack 
System.Text.Json.Serialization.Tests.ValueTests.ReadArrayOfStack 
```
on

```
Linux
OSX
Windows_NET net472
```
Apparently due to the wrong converter being selected. Message is like:

`System.NotSupportedException : Deserialization of reference types without parameterless constructor is not supported. Type 'System.Collections.Queue'`

**Comment by Jozkee** [comment]
https://github.com/Jozkee/runtime/commit/5a8ea52345bfbfcf859b3d3831e4dc7ee1fb09c9
This should fix it, for some reason I am not able to create a PR against your fork...

cc @layomia @GrabYourPitchforks
