### ISSUE TITLE
Need a way to ignore build configurations when library is inbox

### ISSUE THREAD

**Issue by weshaggard** [dotnet/runtime#23972]
For libraries like DirectoryServices which are inbox on a framework (https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/pkg/System.DirectoryServices.pkgproj#L10) and only have a netstandard configuration without a netfx configuration because it shares the same identity as desktop, we need a way to tell our build system to ignore the netstandard configuration when building the netfx vertical. Without that we will end up selecting the netstandard asset and building and testing that when doing our netfx vertical testing. 

We can probably add a new property called something like IgnoreBuildConfigurations or InboxOnFramework and teach our configuration system (likely somewhere in https://github.com/dotnet/corefx/blob/master/buildvertical.targets#L70) to filter out and skip such configurations.

**Comment by ViktorHofer** [comment]
ping @safern. Would love to close this again, can you please scan tests and remove/diagnose the active issues?

**Comment by safern** [comment]
Yeah. I just have had other priorities. I just wrote this down on my pending tasks to not forget. Will get to it in the coming days, thanks.

**Comment by ViktorHofer** [comment]
@safern I wouldn't spend too much time on this as with https://github.com/dotnet/runtime/pull/35606 we will stop using the RefPath for anything != `NetCoreAppCurrent` and I'm considering  getting rid of the `RuntimePath` for OOB libraries 
as well and build them app-local instead, which is the way they are being used by customers. I talked about this with @ericstj in the past.

As an example, a .NET Framework Test Library would either use a P2P (to the ref&impl, if the live built assets should be used) or a simple name reference (if the assembly should be resolved from the GAC).
