### ISSUE TITLE
Linux: unable to cancel async read of /dev/input/input0 file

### ISSUE THREAD

**Issue by Const-me** [dotnet/runtime#24052]
I’m using System.IO.FileStream to read touch screen events. More specifically, I have an endless loop that calls `await stream.ReadAsync(…)` API on that file.

It works OK and I’m getting my touch events (well, almost, because no multi-touch, but I don’t think .NET is responsible for that).

I’m having problems implementing graceful shutdown.

I’ve tried closing and disposing the stream, I.ve tried passing CancellationToken to ReadAsync() call, the result is the same, ReadAsync() only cancels with an exception when the next touch event becomes available. Which is kinda later than I’d like it to.

I don’t have much experience with Linux, but it looks like there’s a bug in CoreFX here?

**Comment by radioegor146** [comment]
Are there any workarounds about this?

**Comment by Const-me** [comment]
@radioegor146 That software is long in production. The workaround I’ve implemented — I don’t wait for that task, I only unset the listener in my code. This way, when a user touches the screen after they initiated shutdown but before the process quits, my touch screen class won’t generate any events. Shutdown sequence is complicated in my case and takes considerable time, as the product contains multiple peripheral devices attached to that SoC, some of them are even custom hardware.

Fortunately, that blocked IO thread doesn’t keep the process alive. When the process quits, Linux kernel closes all the handles, including that touchscreen device.

**Comment by wfurt** [comment]
`FileStream` was never designed to work on anything but regular files. For something like stdin (or other character devices) we would need something more like a NamedPipe code. I was thinking about this more and there are generally two strategies one can take: (aside of rewriting FileStream)
Either 1) override `Read()` method to avoid blocking read or 2) figure out how to wake up the blocking call. I did some experiments with the second option and cancellation token. However, even if I wake OS Read(), the cancellation request is not respected. I'm still looking into it.

BTW If the only thing you care about is a quick exit, you can send SIGINT signal to the process itself.
