### ISSUE TITLE
NetCore package description commit hash could use some explanation?

### ISSUE THREAD

**Issue by rrelyea** [dotnet/runtime#24074]
Microsoft.NETCore.App has the following description in its nuspec:
```
    <description>A set of .NET API's that are included in the default .NET Core application model. 
e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d 
When using NuGet 3.x this package requires at least version 3.4.</description>
```

I just got a question asking if this was a NuGet.org or NuGet client bug...

Perhaps changing that to something like the following would make it more helpful to more people?
```
    <description>A set of .NET API's that are included in the default .NET Core application model. 
Commit hash: e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d 
When using NuGet 3.x this package requires at least version 3.4.</description>
```

**Comment by ViktorHofer** [comment]
@ericstj do you know where we set the Commit SHA?

**Comment by ericstj** [comment]
It's done here: https://github.com/dotnet/arcade/blob/988d74184dc8069591a80b0a58ba6f7af79afcc9/src/Microsoft.DotNet.Build.Tasks.Packaging/src/build/Packaging.targets#L889

Perhaps now that we embed the actual source control info in the packages via NuGet's https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository we can just remove this.  The former pre-dates the latter.

**Comment by ViktorHofer** [comment]
Sounds like a plan. Maybe you have a few "minutes" sometime to remove that code? (panda face)

**Comment by ericstj** [comment]
Let's add it to pkgproj epic

**Comment by ViktorHofer** [comment]
The commit SHA got removed from the packages and its now part of the nuspec and displayed via nuget.org or NuGet Package Explorer.
