### ISSUE TITLE
Document that CancellationToken in Stream.ReadAsync() is advisory

### ISSUE THREAD

**Issue by binki** [dotnet/runtime#24093]
At https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=netframework-4.7.1 I read:

> If the operation is canceled before it completes, the returned task contains the [`Canceled`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskstatus.canceled?view=netframework-4.7.1) value for the [`Status`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.status?view=netframework-4.7.1) property.

As described in dotnet/runtime#19867, this is not true in actual practice. Especially because `NetworkStream.ReadAsync()` ignores the `CancellationToken` altogether.

Thus, I think the documentation for `Stream.ReadAsync()` should be changed to indicate that the parameter is advisory. For code accepting a `Stream`, there is no way (without reflection which should not be required of consumers—and, even with reflection, one may be consuming a stream which wraps `NetworkStream`) to tell if the `CancellationToken` will be ignored or not. So such code always needs to be written in such a way as to support streams with uncancellable read (and write?) operations.

**Comment by stephentoub** [comment]
At this point, I don't see anything actionable in this issue, so I'm going to close it.  If there are places where the docs could be more informative, we'd welcome PRs to https://github.com/dotnet/dotnet-api-docs to do so.  And if there are places where the implementation isn't as prompt in responding to cancellation as it could/should be, we'd also welcome PRs to https://github.com/dotnet/runtime to improve things.  Thanks.
