### ISSUE TITLE
Add libraries outerloop runs running on Mono

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#24101]
We currently only run our outerloop tests on coreclr, we should add mono as well so that outerloop tests are tested on Mono.

cc @dotnet/runtime-infrastructure

**Comment by safern** [comment]
I agree. As a note, when doing this we can do similar thing as we do in runtime.yml which is switch to use the run-test-job.yml template (with the right runtimeFlavor) and build-test-job.yml template. That way we don't have to build libraries and tests twice.

**Comment by jaredpar** [comment]
Not sure precisely where you want to add Mono here. There are two interpretations:

1. Add another configuration to the existing runtime build definition which runs more mono legs
1. Add another build definition, similar to the existing libraries CI jobs, which run mono. 

If it's the latter I'm definitely supportive but I have one big concern: how do we get it to quality? For context there are four libraries outerloop jobs at the moment:

| Outerloop | Full Name | Pass Rate (last 10 builds) |
| --- | --- | --- | 
| libraries | [runtime-libraries outerloop](https://dev.azure.com/dnceng/public/_build?definitionId=675) | 0% | 
| libraries windows | [runtime-libraries outerloop-windows](https://dev.azure.com/dnceng/public/_build?definitionId=676) | 20% | 
| libraries linux | [runtime-libraries outerloop-linux](https://dev.azure.com/dnceng/public/_build?definitionId=677) | 0% | 
| libraries osx | [runtime-libraries outerloop-osx](https://dev.azure.com/dnceng/public/_build?definitionId=678) | 20% | 

As you can see the quality here is really low at the moment (and is currently trending downwards). 

Before we add Mono to the mix here I think we need to be proving that we can get these jobs to a level of quality that adds value to our product. Adding Mono in the current state is just adding more runs which are in perpetual failing state.

**Comment by ViktorHofer** [comment]
Triage: we need this for 5.0 as the Mono runtime is used on WASM. Assigning @safern

**Comment by ericstj** [comment]
@safern, do you know if this already happened?

**Comment by safern** [comment]
Not yet. I'll take care of this this week.

**Comment by ViktorHofer** [comment]
Handing off to @trylek as @safern already has enough on his plate :)

**Comment by safern** [comment]
@ViktorHofer thanks for the intention but I had already started working on this 😕

**Comment by ViktorHofer** [comment]
@safern @trylek sorry for the conflict here. I should have checked first if you haven't already started with this. The intention was to reduce your workload for 5.0.

**Comment by safern** [comment]
Yeah I appreciate that 😄 -- just wanted to raise that I had already made progress on this... I was planning on adding a separate outerloop build that runs just mono outerloop runs... what do you think about doing that? The reason for that is because they can have multiple modes like interpreter and others they plan to add: https://github.com/dotnet/runtime/issues/41365

However I don't know if that would make us introduce silent bugs by people that just run the outerloop leg that runs against coreclr only and unintentionally forget that the libraries outerloop tests against mono are in a separate pipeline.
