### ISSUE TITLE
cant cross build arm64 on Ubuntu 17.10

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#24167]
simply put i cant cross build arm64 on Ubuntu 17.10
all i need is a arm64 mscorlib.dll
cant built the crossbuild rootfs to compile and cant compile it based on the guide

https://github.com/dotnet/corefx/blob/master/Documentation/building/cross-building.md

nothing in the guide appears to work

**Comment by jkotas** [comment]
The lldb package version can be specified as argument for build-rootfs.sh.

E.g. this is how we call build-rootfs.sh to produce docker images used for building in CI:

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/298d36ffa4db46bf9ec19aae78aa3c8404e23e0f/src/ubuntu/16.04/cross/arm64/hooks/pre-build#L3
