### ISSUE TITLE
PerformanceCounter_IncrementBy_IncrementByReadOnly Failure for Windows 8.1

### ISSUE THREAD

**Issue by Drawaes** [dotnet/runtime#24176]
The failure on Windows is only on Windows.81.Amd64.Open (the test is skipped on a number of the win10 versions)
System.Diagnostics.Tests.PerformanceCounterTests/PerformanceCounter_IncrementBy_IncrementByReadOnly

Assert.NotEqual() Failure
Expected: Not 0
Actual: 0

https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/95937940636258caa156046fa21fca91a45682d3/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_IncrementBy_IncrementByReadOnly

Trace

```
at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs:line 71
   at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType) in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 297
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly() in D:\j\workspace\windows-TGrou---6368dffa\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 228
```

**Comment by danmoseley** [comment]
@dotnet/area-system-diagnostics-performancecounter we should clean up issues like this that were test failures _four_ years ago. It's easy to check there were no recent hits:

Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAG1QX0sCQRB%2fD%2fwOy71YL55GGT0YaCYoaOVJPcZ6O3qbuzOxM4sd9OG7M0IvehuY3%2f8Zrbl19qX2BQRQmeggYNSd0ls673fNRessTX%2b%2fq%2fIDFNcQ3lspVCLAkm4i5mIJtUtzZ9PklJFRDDmonFC0RVZJgA2nBWjDqdcsEBrwUbTOqMFAtS%2b7vdvuVe%2bm02%2fX6d7JotpZNAOLCEGtKuMlcHTCilDNaD01xxY%2fn1onmWjrGhbPESIstAeFJMdcy%2by6AZuDFHSIkoxJxpBbr93DpwTweohmQZhJsLh90S4CN6ivFHZTAT8JFtC48mBWC2VlVdh35uAplJ26Av%2fxZNbb5sJDZgjSWRWB9jX6n3xPEDYUvMYc7ilitenbFPMqKKCMytN7We3%2biK6sdL4BSxcT0vcBAAA%3d) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG1QX0sCQRB%2fD%2fwOy71YL55GGT0YaCYoaOVJPcZ6O3qbuzOxM4sd9OG7M0IvehuY3%2f8Zrbl19qX2BQRQmeggYNSd0ls673fNRessTX%2b%2fq%2fIDFNcQ3lspVCLAkm4i5mIJtUtzZ9PklJFRDDmonFC0RVZJgA2nBWjDqdcsEBrwUbTOqMFAtS%2b7vdvuVe%2bm02%2fX6d7JotpZNAOLCEGtKuMlcHTCilDNaD01xxY%2fn1onmWjrGhbPESIstAeFJMdcy%2by6AZuDFHSIkoxJxpBbr93DpwTweohmQZhJsLh90S4CN6ivFHZTAT8JFtC48mBWC2VlVdh35uAplJ26Av%2fxZNbb5sJDZgjSWRWB9jX6n3xPEDYUvMYc7ilitenbFPMqKKCMytN7We3%2biK6sdL4BSxcT0vcBAAA%3d&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAG1QX0sCQRB%2fD%2fwOy71YL55GGT0YaCYoaOVJPcZ6O3qbuzOxM4sd9OG7M0IvehuY3%2f8Zrbl19qX2BQRQmeggYNSd0ls673fNRessTX%2b%2fq%2fIDFNcQ3lspVCLAkm4i5mIJtUtzZ9PklJFRDDmonFC0RVZJgA2nBWjDqdcsEBrwUbTOqMFAtS%2b7vdvuVe%2bm02%2fX6d7JotpZNAOLCEGtKuMlcHTCilDNaD01xxY%2fn1onmWjrGhbPESIstAeFJMdcy%2by6AZuDFHSIkoxJxpBbr93DpwTweohmQZhJsLh90S4CN6ivFHZTAT8JFtC48mBWC2VlVdh35uAplJ26Av%2fxZNbb5sJDZgjSWRWB9jX6n3xPEDYUvMYc7ilitenbFPMqKKCMytN7We3%2biK6sdL4BSxcT0vcBAAA%3d&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG1QX0sCQRB%2fD%2fwOy71YL55GGT0YaCYoaOVJPcZ6O3qbuzOxM4sd9OG7M0IvehuY3%2f8Zrbl19qX2BQRQmeggYNSd0ls673fNRessTX%2b%2fq%2fIDFNcQ3lspVCLAkm4i5mIJtUtzZ9PklJFRDDmonFC0RVZJgA2nBWjDqdcsEBrwUbTOqMFAtS%2b7vdvuVe%2bm02%2fX6d7JotpZNAOLCEGtKuMlcHTCilDNaD01xxY%2fn1onmWjrGhbPESIstAeFJMdcy%2by6AZuDFHSIkoxJxpBbr93DpwTweohmQZhJsLh90S4CN6ivFHZTAT8JFtC48mBWC2VlVdh35uAplJ26Av%2fxZNbb5sJDZgjSWRWB9jX6n3xPEDYUvMYc7ilitenbFPMqKKCMytN7We3%2biK6sdL4BSxcT0vcBAAA%3d&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
Jobs
| where Started > ago(60d)
| join kind=inner TestResults on JobId
| where Result == "Fail"
| where Method == "PerformanceCounter_IncrementBy_IncrementByReadOnly"
```

There is no  value keeping such issues open.
