### ISSUE TITLE
Investigate and categorize Linux/Windows performance discrepancies

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#24192]
Most of our performance benchmarking has been against Windows, except for the key public benchmarks like Techempower and CLBG. Our xunit `[Benchmark]` tests are run on Linux and Windows, and there are some areas where Linux does not match Windows performance on the same hardware. Investigate, categorize and triage.

**Comment by danmosemsft** [comment]
There was substantial work done here mostly by @adamsitnik . If there are new issues - we should open a new one.

**Comment by adamsitnik** [comment]
If anybody is interested in seeing the full list, please filter by `tenet-performance` and `os-linux` labels: https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Atenet-performance+label%3Aos-linux
