### ISSUE TITLE
Try to reduce overhead of abstraction in Utf-8 integer formatter APIs

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#24211]
Currently, the overhead to calling the Utf-8 integer formatter APIs is high for the simple/default case.

**Any ideas on what we can do to reduce this overhead caused by the abstraction layer and the desire to reduce code duplication?**

Let's say we just want to write an integer starting from the end of the provided buffer (instead of the front), and we provide a StandardFormat 'R' to support that (see scenario in [SignalR](https://github.com/aspnet/SignalR/pull/1128) here: https://github.com/aspnet/SignalR/pull/1128/files#diff-d04b54105a83f4a2e21723409df7b9b1R37).

The function calls look like this:
TryFormat(int value, ..., 'R') => TryFormatInt64(value, 0xffffffff, buffer, out bytesWritten, format) => if check + switch statement => TryFormatInt64R
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Integer.Signed.cs#L18

Even if TryFormatInt64R is essentially a no-op, the overhead is higher than implementing your own (relatively naiive) method and calling it directly.
```C#
private static bool TryFormatInt64R(long value, Span<byte> buffer, out int bytesWritten)
{
    bytesWritten = 0;
    return false;
}
```

```C#
// Note: Not tested, just an example
public static bool MyReverseFormat(uint value, Span<byte> buffer, out int bytesWritten)
{
    int digits = 0;
    bytesWritten = 0;
    do
    {
        int index = buffer.Length - 1 - digits;
        if (index < 0) 
        {
            buffer.Clear();
            return false;
        }
        buffer[index] = (byte)('0' + value % 10);
        value /= 10;
        digits++;
    } while (value > 0);

    bytesWritten = digits;
    return true;
}
```

**Overhead of calling no-op TryFormat:**
![image](https://user-images.githubusercontent.com/6527137/33107176-e63797b6-ceea-11e7-8f32-3d45b416ac53.png)

**We never overcome the overhead, even though the per loop iteration performance of our algorithm is better:**
![image](https://user-images.githubusercontent.com/6527137/33107144-ba032dae-ceea-11e7-9612-2ddeb87b9cf1.png)

![image](https://user-images.githubusercontent.com/6527137/33107156-d08d0aea-ceea-11e7-8bc5-7019bf4176cb.png)

Related PR: https://github.com/dotnet/corefx/pull/25424

cc @KrzysztofCwalina, @AtsushiKan, @jkotas

**Comment by stephentoub** [comment]
As written so present, I don't see anything actionable here. Closing.
