### ISSUE TITLE
ExpressionTree serialization and reflection fallback?

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#24234]
The expression tree is a great tools for making standard dynamic script. But there is 2 features I think we need to let it contain in expression tree library

One is standardize serialization/deserialization for making it portable and could transfer the logic across network and also save it as data in a file or database

Another is fallback to reflection in addition to `Compile()` to delegate. In place where we can't do a runtime code generation such as when we doing AoT compilation

**Comment by cston** [comment]
@Thaina, are there still questions or bugs here that should be addressed or can this issue be closed? Thanks.
