### ISSUE TITLE
Overload to String.Replace that can take multiple strings to replace

### ISSUE THREAD

**Issue by magol** [dotnet/runtime#24318]
Sometime I want to replace multiple texts from a string, and the code become something like this:

```C#
var toReplace = new[] {"aaa", "bbb", "ccc"};
var replaceWith = "";

foreach (var s in toReplace )
{
    foo = foo.Replace(s, replaceWith );
}
```

Of course, I can use `Regex `for such situations, but it feels a bit unnecessarily complicated for such a common case.

I suggest to create an overload to String.Replace with following signature:

```C#
string Replace(IEnumerable<string>, string)
```

Whit this, I can rerwite the example to following:
```C#
var toReplace = new[] {"aaa", "bbb", "ccc"};
var replaceWith = "";

foo = foo.Replace(toReplace , replaceWith );
```

**Comment by GrabYourPitchforks** [comment]
What's wrong with using `StringBuilder` for this scenario? If you have many (let's strawman at 4 or more) replacement strings to search for, using `StringBuilder` would generally cut down on the number of allocations when compared to calling `string.Replace` in a loop.

(And remember, when you have multiple calls to `Replace`, order does matter.)

**Comment by joperezr** [comment]
Closing for now due to lack of activity plus the suggestion above of using StringBuilder instead for something like this. Feel free to reopen if you think otherwise.
