### ISSUE TITLE
ArrayPool.Shared.Rent should support returning a zero-inited array

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#24416]
Currently calling `ArrayPool<T>.Shared.Rent` does not guarantee that the returned buffer is zero-inited. While good for performance, this could cause correctness issues in applications, especially those that simply use `byte[] xyz = ArrayPool<byte>.Shared.Rent(...)` as a drop-in replacement for `byte[] xyz = new byte[...]`.

I propose changing the signature of `ArrayPool.Rent(int minimumLength)` to `ArrayPool.Rent(int minimumLength, bool clearArray = true)`. Thus the default behavior is to zero-init the returned array, and consumers who want the highest possible performance and don't care about the initial values can pass _false_ for this parameter. (I know we shouldn't default optional arguments to anything other than _default(T)_. Haven't fully reconciled this API design mentally yet.)

**Comment by koszeggy** [comment]
I just wanted to suggest the same API change right now. I hope it will be implemented soon.

I have rather performance grounds than security reasons: If I use the shared pool I cannot be sure whether the array I get is clean. Of course, if I need a clean array I can call `Array.Clear` also on rented ones but if the array was newly created by the pool, which I cannot tell, then calling `Clear` at my side is a pure waste of performance.

**Comment by GrabYourPitchforks** [comment]
Going through some old stale bugs. Seems that this is probably a non-actionable issue and should be closed?
