### ISSUE TITLE
Add IAsyncEnumerable file enumerators

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#24436]
This presents a problem when enumerating slow/remote or offline/asleep volumes.

Things to consider:

- Work being done around extensibility https://github.com/dotnet/designs/blob/master/accepted/file-enumeration.md
- Potential `IAsyncEnumerable<T>` https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md
- Lack of low-level OS support (at least on Windows, not sure about Unix)

Related issue: dotnet/runtime#24427 

@danmosemsft, @pjanotti

**Comment by stephentoub** [comment]
I'm not aware of any way to actually implement this asynchronously on any OS we support. Maybe io_uring would enable us to do this in the future on Linux, but at present (and for the last five years) this issue isn't actionable. Closing.
