### ISSUE TITLE
Multiple thread pools per appdomain and correspond ThreadpoolTaskScheduler

### ISSUE THREAD

**Issue by ForkBug** [dotnet/runtime#24439]
Current thread pool implementation is based on old windows thread pool api(https://msdn.microsoft.com/en-us/library/windows/desktop/ms686766(v=vs.85).aspx). 
Windows support multiple thread pools per process since Vista.

Multiple thread pools per appdomain is useful for advanced scenarios, especially in the TPL scenario. 
For example, some tasks may take more priority than others. These tasks should be executed as soon as they are queued. Complicated customized TaskScheduler could achieve this goal. But multiple thread pools per appdomain and correspond ThreadpoolTaskScheduler may achieve this goal by few lines, with elegant and robust code.

**Comment by stephentoub** [comment]
This is essentially asking for the ability to create instances of ThreadPool (TaskScheduler is just an abstraction that would sit on top of that).  We've considered this in the past and have decided against doing it; I don't expect we'll do so in the foreseeable future.  Anyone can of course implement a simple thread pool, with tools like BlockingCollection, and put it behind a TaskScheduler.  There are a variety of samples online for doing exactly that.
