### ISSUE TITLE
SupportedFramework apply to all versions of a reference assembly

### ISSUE THREAD

**Issue by weshaggard** [dotnet/runtime#24458]
When applying SupportedFramework metadata to a reference assembly in pkgproj it applies to all files in all configurations for the reference assembly project. This causes some invalid validation errors when the reference assembly pins the assembly version for some configurations but not others. 

It ends up expecting some frameworks to support both versions of the reference assembly instead of just the lower version.

**Comment by ViktorHofer** [comment]
Closing as we don't use pkgprojs anymore for our libraries.
