### ISSUE TITLE
Implement public partial sort Array API

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#24468]
## Rationale
- In [PowerShell repo](https://github.com/PowerShell/PowerShell) we have Sort-Object cmdlet enhanced with `-Top` and `-Bottom` parameters  - their implementation is based on partial sorting.
 - Currently Linq uses [`Array.Sort`](https://github.com/dotnet/corefx/pull/24116) but own internal (not public API) implementation of [PartialQuickSort](https://github.com/stephentoub/corefx/blob/a6aff797a33e606a60ec0c9ca034a161c609620f/src/System.Linq/src/System/Linq/OrderedEnumerable.cs#L592).
- It seems this is a very popular scenario for web interface to show sorted result by pages. Users use only top items and rarely go to the following pages.

## Proposed API ##
```c#
public abstract partial class Array : System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.IList, System.Collections.IStructuralComparable, System.Collections.IStructuralEquatable, System.ICloneable
{
    public static void SortPartial(array array, int index, int length) { }
    public static void SortPartial(array keys, array items, int index, int length) { }
    public static void SortPartial(array array, int index, int length, System.Collections.IComparer comparer) { }
    public static void SortPartial(array keys, array items, int index, int length, System.Collections.IComparer comparer) { }
    public static void SortPartial[T](T[] array, int index, int length) { }
    public static void SortPartial[TKey, TValue](TKey[] keys, TValue[] items, int index, int length) { }
    public static void SortPartial[T](T[] array, int index, int endIndex, System.Collections.Generic.IComparer[T] comparer) { }
    public static void SortPartial[TKey, TValue](TKey[] keys, TValue[] items, int index, int length, System.Collections.Generic.IComparer [TKey] comparer) { }
}

public partial class List<T> : System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.Generic.IList<T>, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlyList<T>, System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.IList
{
    public void SortPartial(int index, int count, System.Collections.Generic.IComparer<T> comparer) { }
}
```
## Useful links ##
https://en.wikipedia.org/wiki/Partial_sorting
https://blogs.msdn.microsoft.com/devdev/2006/01/18/efficient-selection-and-partial-sorting-based-on-quicksort/
## Updates ##
1. Replace `startIndex` and `endIndex` with `index` and `length`.
2. Add class names.

**Comment by ericstj** [comment]
Now that we have Span.Sort is this proposal still interesting?
https://github.com/dotnet/runtime/blob/f0ede2b86b0f1b86744aa1e020ba1df3ac3d2744/src/libraries/System.Memory/ref/System.Memory.cs#L87-L92

I think it addresses the original scenario.

**Comment by iSazonov** [comment]
Now this proposal is interesting if we want modernize the old Array type.

**Comment by KalleOlaviNiemitalo** [comment]
I don't see how the MemoryExtensions.Sort methods address the original scenario. Those methods fully sort the span given, so they are not efficient for partial sort tasks like "what are the five largest of these 100000 integers?"

In C++, [std::partial_sort](https://en.cppreference.com/w/cpp/algorithm/partial_sort) sorts the smallest `middle - first` elements to the start of the range. @iSazonov's [proposed API](https://github.com/dotnet/runtime/issues/24468#issue-558313526) looks more capable, as it takes both `int index` and `int length` parameters, allowing it to sort the largest elements to the end of the range, or median elements to the middle of the range. However, I don't think the current parameter sets of the PowerShell `Sort-Object` cmdlet would benefit from that capability.

If that capability is not needed, then partial sorts of Span could have these signatures:

```diff
 public static partial class MemoryExtensions
 {
     public static void Sort<T>(this System.Span<T> span) { }
     public static void Sort<T, TComparer>(this System.Span<T> span, TComparer comparer) where TComparer : System.Collections.Generic.IComparer<T>? { }
     public static void Sort<T>(this System.Span<T> span, System.Comparison<T> comparison) { }
     public static void Sort<TKey, TValue>(this System.Span<TKey> keys, System.Span<TValue> items) { }
     public static void Sort<TKey, TValue, TComparer>(this System.Span<TKey> keys, System.Span<TValue> items, TComparer comparer) where TComparer : System.Collections.Generic.IComparer<TKey>? { }
     public static void Sort<TKey, TValue>(this System.Span<TKey> keys, System.Span<TValue> items, System.Comparison<TKey> comparison) { }
+    public static void PartialSort<T>(this System.Span<T> span, int count) { }
+    public static void PartialSort<T, TComparer>(this System.Span<T> span, int count, TComparer comparer) where TComparer : System.Collections.Generic.IComparer<T>? { }
+    public static void PartialSort<T>(this System.Span<T> span, int count, System.Comparison<T> comparison) { }
+    public static void PartialSort<TKey, TValue>(this System.Span<TKey> keys, System.Span<TValue> items, int count) { }
+    public static void PartialSort<TKey, TValue, TComparer>(this System.Span<TKey> keys, System.Span<TValue> items, int count, TComparer comparer) where TComparer : System.Collections.Generic.IComparer<TKey>? { }
+    public static void PartialSort<TKey, TValue>(this System.Span<TKey> keys, System.Span<TValue> items, int count, System.Comparison<TKey> comparison) { }
 }
```

i.e. copy each overload of `Sort` to `PartialSort` and add `int count` after the Span parameters. These would throw ArgumentOutOfRangeException if `count < 0` or `count > span.Length`. After PartialSort returns:

- `span.Slice(0, count)` contains the `count` smallest original elements of `span` in ascending order.
- `span.Slice(count)` contains the other original elements of `span` in unspecified order.

If a caller instead wants `span.Slice(0, count)` to be the `count` largest elements, it can provide a reverse `comparer`.

If a caller instead wants `span.Slice(span.Length - count)` to be the `count` smallest elements, it can swap them after PartialSort has returned.

**Comment by ericstj** [comment]
I see. I misunderstood partial sort. This makes a lot more sense and I see the value.  Let’s keep it open and continue discussion in 6.0.

**Comment by iSazonov** [comment]
@ericstj I see it is for 6.0 but not assigned to any UserStory.

**Comment by ericstj** [comment]
That means it's in the backlog for consideration but not committed.  System.Runtime owners -- @jeffhandley @pgovind @tannergooding thoughts on this one?

**Comment by tannergooding** [comment]
This needs to go to API review.

I'd expect we want the same APIs to exist for Span and for the array APIs, if they will exist, to simply forward to the span implementation.
Provided the original post gets updated with the Span APIs, I'm fine with taking this to API review.

I'd be interested in @jkotas' opinion on if we should also expose the array variants for parity, or if we expect users (including F# where implicit conversions don't exist) to just call the Span variants.

**Comment by jkotas** [comment]
The .NET Framework design guidelines says "CONSIDER providing array-accepting alternatives for methods that accept Span or Memory values.". 

I assume that the implementation of these APIs is going to be several thousands lines of code. Is that right? Adding this to CoreLib for very niche use case sounds more concerning than a few dozen lines of array wrappers.

**Comment by tannergooding** [comment]
> I assume that the implementation of these APIs is going to be several thousands lines of code. Is that right?

I'll let @isazonov comment since they are the proposer, but I'd guess we could reuse most of the existing sorting algorithm. My understanding is its largely just an optimization that allows you to avoid sorting the remaining tail elements after you sort up to `endIndex`

**Comment by iSazonov** [comment]
If I remember correctly in version 3 there was duplication of implementation in coreclr and libraries, as well as for generic and non-generic. And it was the main stopper of innovations in this area. If this is already solved, then there should not be a lot of new code - we just need to stop sorting as soon as we get the top sorted elements and not sort the tail - it seems quicksort supports this.
Also, if the code is now shared, then I see no obstacles to making new API on Span.

**Comment by iSazonov** [comment]
> Provided the original post gets updated with the Span APIs, I'm fine with taking this to API review.

What classes does it make sense to cover? Array, List<T> - something else?

**Comment by jkotas** [comment]
> there was duplication of implementation in coreclr and libraries,

We have moved the entire implementation in C# under libraries, but there is still a fair amount of redundancy for best performance and to prevent denial-of-service issues. Is adding this feature to the existing implementation to avoid duplication going to regress performance of the existing Sort methods? Is that regression going to be acceptable? 

> it seems quicksort supports this.

Note that the existing Sort methods are implemented as combination of 3 different sorting algorithms.

> Array, List

It does not make sense to add it to List. It would make List (one of the most frequently used collection classes) footprint more expensive for everybody.

**Comment by iSazonov** [comment]
> Note that the existing Sort methods are implemented as combination of 3 different sorting algorithms.

https://en.wikipedia.org/wiki/Partial_sorting says that many algorithms support partial sorting.

>  Is adding this feature to the existing implementation to avoid duplication going to regress performance of the existing Sort methods? Is that regression going to be acceptable?

I suppose nobody would want that.
If I understand quicksort correctly, one additional check is needed to get a partial quicksort.

> It does not make sense to add it to List. It would make List (one of the most frequently used collection classes) footprint more expensive for everybody.

This could be as simple as enhancing:
```c#
public void Sort (int index, int count, System.Collections.Generic.IComparer<T>? comparer);
```
with
```c#
public void Sort (int index, int count, System.Collections.Generic.IComparer<T>? comparer, int top);
```
where `top` parameter says to do a partial sort.

**Comment by tannergooding** [comment]
For `List` in particular, users needing it can always use `CollectionsMarshal.AsSpan` and then use partial sort on that.

It has additional considerations, but allows adding the additional wrapper method or extension method to `List<T>`

**Comment by iSazonov** [comment]
Partial sort is a useful feature but not used _very often_ so I suppose there is no need to add a _full_ set of overloads to _every_ class.
If LINQ is not taken into account, then the following would be enough (new `top` parameter is for partial sort - how many sorted elements to return):
```c#
namespace System
{
    public abstract partial class Array : ICloneable, IList, IStructuralComparable, IStructuralEquatable
    {
        public static void Sort(Array keys, Array? items, int index, int length, IComparer? comparer, int top);
        public static void Sort(Array array, int index, int length, IComparer? comparer, int top);
    }
}

namespace System.Collections.Generic
{
    public class List<T> : IList<T>, IList, IReadOnlyList<T>
    {
        public void Sort(int index, int count, IComparer<T>? comparer, int top);
    }
}

namespace System
{
    public static partial class MemoryExtensions
    {
        public static void Sort<T, TComparer>(this Span<T> span, TComparer comparer, int top)
            where TComparer : IComparer<T>?;
        public static void Sort<T>(this Span<T> span, Comparison<T> comparison, int top);
    }
}
```

**Comment by iSazonov** [comment]
Are we ready for API review?
