### ISSUE TITLE
Consolidate HashAlgorithmName->HashAlgorithm lookup tables

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#24471]
There are a fair number of copies of HashAlgorithmName to HashAlgorithm resolvers.  They should be consolidated into one place, and probably just be public API.

`HashAlgorithm.Create(HashAlgorithmName algName)`, perhaps?

**Comment by stephentoub** [comment]
@bartonjs, is this still an issue?  The API is simple: I suggest we either just go ahead and do it (API review it) or close this.  Thanks.

**Comment by vcsjones** [comment]
I think we can close this. Most of the places where we had these type of lookups have moved to the one-shot helpers, or `IncrementalHash` which natively takes a `HashAlgorithmName`. Most of the mappings are done to/from PAL identifiers.

> For PKCS/X.509 there may also be some Oid <-> HashAlgorithm(Name) resolvers that should be addressed, too.

We have `HashAlgorithmname.FromOid` for this now.
