### ISSUE TITLE
Mark Write7BitEncodedInt and Read7BitEncodedInt as public

### ISSUE THREAD

**Issue by vermorel** [dotnet/runtime#24473]
_Edit by @GrabYourPitchforks on 20 Jan 2020_: See detailed API proposal at https://github.com/dotnet/corefx/issues/25950#issuecomment-404841837.

7-bits encoding are useful in many situations. Yet, the method [BinaryWriter.Write7BitEncodedInt(int)](https://msdn.microsoft.com/en-us/library/system.io.binarywriter.write7bitencodedint(v=vs.110).aspx) is `protected` (idem for [BinaryReader.Read7BitEncodedInt](https://msdn.microsoft.com/en-us/library/system.io.binaryreader.read7bitencodedint(v=vs.110).aspx)) are not public. As a result, codebases end-up implementing a variant of `DummyBinaryReader` just access through inheritance the two properties. It would be much nicer if those two methods could be made public directly.

**Comment by terrajobst** [comment]
* We should reuse the existing methods, which are protected (since the method isn't virtual, making it public isn't a breaking change).
* We don't want to add `BigInteger` support because reader/writer has no support for `BigInteger`. This should be a separate proposal.

```C#
namespace System.IO
{
    public class BinaryReader
    {
        public int Read7BitEncodedInt();
        public long Read7BitEncodedInt64();
    }
    public class BinaryWriter
    {
        public int Write7BitEncodedInt(int value);
        public int Write7BitEncodedInt64(long value);
    }
}
```

**Comment by GrabYourPitchforks** [comment]
FYI the _Write*_ methods should be `void`-returning, not `int`-returning. The PR which addresses this issue has the correct signatures.

**Comment by jjxtra** [comment]
As long as we are introducing new public methods why not return the number of bytes written? What is the downside?

**Comment by GrabYourPitchforks** [comment]
It's not a new method. It's an existing protected method which is being converted to public. Changing the visibility in this manner is ok, but changing the signature would break existing applications.

Additionally, when dealing with abstract source+sink APIs like this there's no real need to know how many bytes were written. Unlike APIs that write directly to buffers, the caller here isn't expected to slice the destination buffer or take any similar action.
