### ISSUE TITLE
Simplify Nullable<T> usage with deconstruction semantics 

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/runtime#24505]
Recently I upgraded to using C# 7.* and I finally got to do more with tuples. I love the `.Deconstruct` capabilities and how they extend into anything. I have found this to be particularly useful for `Nullable<T>`. I tweeted about it <a href="https://twitter.com/davidpine7/status/941759704363085825" target="_blank">here</a> and it caught a lot of positive attention from the developer community. In fact, I was inspired to make a pull request as @jaredpar and @VSadov seemed to think it "should just be added to Nullable".

# Rationale and Usage

This feature will simplify the usage of `Nullable<T>` access, as the consumer will have two variables namely `hasValue` and `value` - instead of an instance of the `Nullable<T>` that they would then have to `.` into.

```csharp
public void TakeActionOnNullable<T>(Nullable<T> nullable)
{
    // Leveraging the generic nullable deconstruction extension method
   var (hasValue, value) = nullable;
}
```

# Proposed API

This is my first PR in coreclr / corefx, is this what you're looking for?

```csharp
[EditorBrowsable(EditorBrowsableState.Never)]
public static void Deconstruct<T>(this T? nullable, out bool hasValue, out T value)
    where T : struct
{
    hasValue = nullable.HasValue;
    value = nullable ?? default;
}
```

# Details

This extension method is generic and will support all variations of `Nullable<T>`, this means that any `Nullable<T>` can easily be deconstructed. This is obviously an opt-in, no developer will be forced to use this. It is however an option that could be considered a more terse approach. 

# Pull Request

Here is the PR: https://github.com/dotnet/coreclr/pull/15605

**Comment by GrabYourPitchforks** [comment]
There doesn't seem to be a large audience clamoring for this. Any reason it can't be implemented as an extension method in the projects which need it? Here's a somewhat more optimized version of what was proposed earlier in the issue:

```cs
[EditorBrowsable(EditorBrowsableState.Never)]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static void Deconstruct<T>(in this T? nullable, out bool hasValue, out T value)
    where T : struct
{
    hasValue = nullable.HasValue;
    value = nullable.GetValueOrDefault();
}
```

**Comment by ericstj** [comment]
Closing for now due to lack of recent interest as well as a good workaround from @GrabYourPitchforks.
