### ISSUE TITLE
Add implementation for SetTcpKeepAlive in ServicePoint

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/runtime#24500]
Hi

I am porting my .NetFramework project to .NetStd 2.0.

I have long running workloads. I need to set Tcp Keep-Alive messages. This is supported in .NetFramework.
Its implementation in corefx is not doing anything after validation.
https://github.com/dotnet/corefx/blob/master/src/System.Net.ServicePoint/src/System/Net/ServicePoint.cs#L101

Hence, my HttpClient Api calls don't send tcp keep alive messages.

Is there any workaround ? 
When can we expect full implementation of `SetTcpKeepAlive` ?

**Comment by TalAloni** [comment]
If you need it now - I did a backport of SocketsHttpHandler to .NET Standard 2.0 and added a SocketCreated event that allows you to configure TCP Keepalive on the socket, it's on [NuGet](https://www.nuget.org/packages/StandardSocketsHttpHandler) / [GitHub](https://github.com/TalAloni/StandardSocketsHttpHandler/).

I also ported the Microsoft tests for your peace of mind.

**Comment by ManickaP** [comment]
I think we can keep this closed, `ServicePoint*` has been deprecated. We've also put up a detailed docs about migration to `HttpClient`, e.g.: https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-migrate-from-httpwebrequest#usage-of-socketshttphandler-and-connectcallback for `ConnectCallback` that can be used to set TCP keep alive.
