### ISSUE TITLE
Windows installer should warn about missing required updated

### ISSUE THREAD

**Issue by anurse** [dotnet/runtime#2452]
## Steps to reproduce
1. Provision/find/etc. a machine running Windows Server 2008 R2 Server Core and DO NOT apply updates.
2. Install the Windows x64 Installer from https://github.com/dotnet/cli/blob/rel/1.0.0/README.md
3. Upon completion, run "C:\Program Files\dotnet\dotnet.exe --help"
## Expected  behavior

The install should warn or block because the required hotfix [KB2533623](https://support.microsoft.com/en-us/kb/2533623) has not been installed
## Actual behavior

The install succeeds and attempts to invoke dotnet.exe result in:

```
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\1.0.1\hostfxr.dll], HRESULT: 0x80070057
```
## Environment data

`dotnet --info` output:

```
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\1.0.1\hostfxr.dll], HRESULT: 0x80070057
```

`ver` output:

```
Microsoft Windows [Version 6.1.7601]
```

**Comment by NikolaMilosavljevic** [comment]
We are deprioritizing this as it is Win7 only. Confirmed that it is already documented and users have a way to install the prereq.

**Comment by mirh** [comment]
It's already documented, but the point of the issue was avoiding clueless users to spin in circles after an apparently successful installation.
