### ISSUE TITLE
Proposal: add GetEnvironmentVariableAsBool to netstandard

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#24535]
@diddledan commented on [Tue Dec 19 2017](https://github.com/dotnet/standard/issues/608)

Currently the dotnet cli has a function which is located at: [src/Microsoft.DotNet.Cli.Utils/EnvironmentProvider.cs Line 106](https://github.com/dotnet/cli/blob/fffe3142ad8043743d83885df2166fd2f80dceca/src/Microsoft.DotNet.Cli.Utils/EnvironmentProvider.cs#L106)

I think it would be useful to consider this functionality for inclusion into the `System.Environment` namespace.

This issue is to raise the idea and garner discussion. I do not believe it would conflict with anything already present, though I've not performed a thorough examination to prove it.

---

@danmosemsft commented on [Wed Dec 27 2017](https://github.com/dotnet/standard/issues/608#issuecomment-354183176)

@diddledan the right place to propose new API is the corefx repo...

**Comment by ericstj** [comment]
Closing this due to lack of recent interest + complexities with languages.  As @justinvp mentioned this can be developed outside of dotnet/runtime.
