### ISSUE TITLE
SIMD Numeric Arrays Operations

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#24625]
I suggest to add some SIMD operations to Array class, such as:

```
int[] a = {1, 2, 3, 4, 5, 6, 7, 8};
int[] b = {1, 2, 3, 4, 5, 6, 7, 8};
var c = a + b ;
```

C# should contain {2, 4, 6, 8, 10, 12, 14, 16}
If a and b have different  lengths, C# can raise exception, or conceder missed elements in the shortest array to be zeroes.
If we want to do so, we can use Vector4 to calculate the result:
var Result1 = new Vector4(1, 2, 3, 4) + new Vector4(1, 2, 3, 4);
var Result2 = new Vector4(5, 6, 7, 8) + new Vector4(5, 6, 7, 8);
Then add the elements from the two results to the array. This will be verbose and ugly long code to write! It's better to write this in a low level SIMD directly without the need for Vector4.
Likewise, you can provide these operations for numeric arrays:
```
c = a - b ;
c = a * b ;
c = a / b ;
```
Also, b can a scalar value that operates on all array elements:
```
c = a + 1 ;
c = a - 1 ;
c = a * 2 ;
c = a / 3 ;
```

Maybe it's better to add a class Named Simd to the System.Numerics namespace, that performs these operations on numeric arrays.

```
c = Simd.Add (a, b)
c = Simd.Add (a, 1)
```
The same for Simd.Subtract , Simd.Multiply, Simd.Divide, Simd.Pow, Simd.Aggregate, etc.
Add as many common array tasks as you can, that can be use the SIMD feature.

Edit:
Is there a plan to use Span< T > with Vectors?
 It can be faster than copying array elements to the Vector.
 Also, the static Vector calss can use it to do operations on two arrays in slices. Ecah method in the Vector class can have another overload with two T[] params instead of Vector< T > param and returns T[] or Memory< T >. If Vector< T > can make use of Span slices (by adding a new constuctor that accepts Span< T >), it will be easy and fast to repeat the same operations on the array slices.

**Comment by tannergooding** [comment]
Going to close this for now. This hasn't gained much traction and likely needs more thought/scenarios before it could be moved forward.

If someone feels strongly about this, please feel free to open a new issue. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.
