### ISSUE TITLE
Static Simd Class to Apply SIMD operations on Arrays, Tuples, Points, Sizes And Rectangles

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#24637]
Edit:
Point, Size and Rectangle structures ar commenly used in image processing calculations, so it can be faster if SIMD operations aplied to them directly. This can be done by extention methods, or by implementing some interface, or as I suggested in dotnet/runtime#24625#26251, SIMD Numeric Arrays Operations , by using static methods of a SIMD Class, Where each method is overloaded to deal with numeric arrays, Point, Size and Rectangle structures.

Tuples, Vectors, Points, Sizes And Rectangles are related. It will be conferrable to make converting between them easier, by adding suitable constructors, deconstructions, To[Type] methods, and implicit/explicit conversion operators to each type. 
- Vectors to Tuples, and suitable Tuples to corresponding Vectors.
- Vector2 to PointF and SizeF and vise versa. Point and Size also can be converted to Vector2.
- Vector4 to RectangleF and vise versa. Rectangle to Vector4.
- Point, PointF, Size, SizeF, Rectangle and RectangleF to Tuples, and suitable Tuples to these types.

Vectors should also have a literal notation. The ToString method give us the <1 , 2 , 3, 4> format. I think it is suitable to write:
var v = <1, 2, 3, 4>;
that means:
var v = new Vector4(1, 2, 3, 4);

**Comment by tannergooding** [comment]
Going to close this for now. This hasn't gained much traction and likely needs more thought/scenarios before it could be moved forward.

If someone feels strongly about this, please feel free to open a new issue. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.

Part of this also appears to be a language request which would need to be filed against dotnet/csharplang
