### ISSUE TITLE
Undefined symbol "pthread_create" under FreeBSD when running apps

### ISSUE THREAD

**Issue by sec** [dotnet/runtime#2463]
When running core apps using dotnet cli under FreeBSD I get:
`/usr/home/asus/sdk/shared/Microsoft.NETCore.App/1.0.0/System.Native.so: Undefined symbol "pthread_create"`

The fix is to link pthread, adding following code to https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/exe/CMakeLists.txt fixed this for me:

```
if(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD") 
target_link_libraries (dotnet "pthread") 
endif()
```

**Comment by wfurt** [comment]
This looks pretty old. I assume we can close it @sec @Thefrank  ?

**Comment by Thefrank** [comment]
yes. FreeBSD links against pthreads

**Comment by wfurt** [comment]
thanks for confirmation.
