### ISSUE TITLE
JIT.Methodical failing on coreclr outerloop

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#24664]
From one of the logs

```
Assert failure(PID 18 [0x00000012], Thread: 1308 [0x051c]): activeCodeVersion == methodDesc->GetCodeVersionManager()->GetActiveILCodeVersion(methodDesc).GetActiveNativeCodeVersion(methodDesc)
    File: /__w/2/s/src/coreclr/src/vm/callcounting.cpp Line: 518
    Image: /root/helix/work/correlation/corerun
```

Builds
- https://dev.azure.com/dnceng/public/_build/results?buildId=503076
- https://dev.azure.com/dnceng/public/_build/results?buildId=502600

Test Runs
 - Linux arm Checked @@(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 - Linux arm Checked `@ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open`@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

**Comment by jaredpar** [comment]
@BruceForstall

**Comment by BruceForstall** [comment]
Failure in tiering:
```
JIT/Methodical/MDArray/basics/stringarr_cs_ro/stringarr_cs_ro.sh
JIT/Methodical/MDArray/basics/stringarr_cs_do/stringarr_cs_do.sh
```

@kouvel @janvorli

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/22786
