### ISSUE TITLE
API Proposal: Add Tau to System.Math(F) class

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/runtime#24678]
This is an API proposal for adding `Tau` to `System.Math` and `System.MathF`. These values would be exactly equal to 2 times `Math.PI` and 2 times `MathF.PI` respectively, and would represent a full rotation around the unit circle in radians.

# Rationale and usage

The `System.Math` class currently has `PI`, but there is one other circle constant that is quite common and useful that is missing: Tau (`τ`), which is `2π`, or about `6.283185307179586476925`.

Tau represents a rotation all the way around the circle, in radians. As demonstrated in the [Tau manifesto](https://tauday.com/tau-manifesto), this value is extremely common throughout numerous mathematical functions.

In my own experience writing code that works with angles and rotations, I have found that using Tau results in much cleaner code. Some examples:

* If you need to write down a rotation in your code, it is much easier to understand when expressed in terms of Tau. 

  * It is immediately clear that `double rotation = Math.Tau / 3;` is a rotation one third of the way around the unit circle in radians, and `double rotation = Math.Tau * 0.6;` is a rotation 60% of the way around the unit circle in radians.

  * Using Pi, those values would have to be written as `Math.PI * 2 / 3` and `Math.PI * 1.2` (or `* 2 * 0.6`) respectively, which is much less clear.

  * Here's an image pulled from the Tau manifesto to illustrate the point:

![](https://tauday.com/assets/figures/tau-angles-28c61fd12cff5934bc32c9a8644e577da69f6f19b657c3aabe2cccc6188e1e42.png)

* If you have rotation represented as a ratio (0 to 1) of how far it is around the unit circle, then you can multiply that ratio by Tau to get a rotation around the unit circle of radians.

  * If you have code that works iteratively, and you have a variable called `delta` which represents the time passed since last frame, code like `rotation += delta * Math.Tau;` will rotate once per second. This can then simply be multiplied with the desired rate per second. Without `Math.Tau`, you would need to multiply by 2, adding complexity and confusion.

* If you are accepting input as a rotation and need to normalize the input, you could use `value % Math.Tau` to normalize the input. With Pi, you would need to write `value % Math.PI * 2`

  * Note that if you need to handle negative values, you would also need [a helper method](https://github.com/dotnet/csharplang/issues/1408).

* While I'm not an expert on audio, just from a search in Godot's source code, it seems that code working with audio waveforms deals with Tau (or 2*Pi) very frequently as well.

Tau is used commonly in the [Godot game engine](https://godotengine.org/).

Obviously I could just create my own helper class for this, but it would be better if it was implemented in .NET and C#, available for all users of .NET and C#.

Not everyone would use it, and that's fine, but I think it is best if .NET and C# encourage writing cleaner code by allowing developers to use `Tau` in addition to `PI` "out of the box".

# Proposed API

The following line would be added to `System.Math`:

    public const double Tau = 6.283185307179586476925;

The following line would be added to `System.MathF`:

    public const float Tau = 6.283185307f;

# Details

If you need more details, consider reading through the [Tau manifesto](https://tauday.com/tau-manifesto).

## Open Questions

The name `TwoPi` has also been suggested. It should be considered, but I think `Tau` is a better choice. The name `Tau` has been popularized by articles such as the [Tau manifesto](https://tauday.com/tau-manifesto). The Greek letter `τ` (tau) resembles a T, which can stand for "turn", and it is visually similar to the Greek letter `π` (pi).

## Pull Request

None so far.

## Updates

https://github.com/dotnet/runtime/issues/24678#issuecomment-639654359

**Comment by GrabYourPitchforks** [comment]
This issue hasn't seen activity in over a year. Is there demand for this API? If not, we should probably close the issue if we're not still collecting information on whether these would be useful in the public surface area.

**Comment by aaronfranke** [comment]
There really isn't much to discuss, it's a simple feature.

I use `Tau` all the time, but I usually use C# in the context of Godot, which has its own `Mathf` static class, so `Tau` in `System.Math` is not a dire need or anything but it would be greatly appreciated for any time I'm using C# outside of Godot.

**Comment by gfoidl** [comment]
I'm against exposing `Tau` as constant in `System.Math` as tau can have several meanings (also with regards to different cultures, i.e. Europe and US), depending on the context. 
The same is somewhat true for pi, but there it is quite obvious that 3.141592... is meant.

Furthermore it's quite easy to expose "derived" constants via `const` or `static readonly` (which the JIT will treat as constants after static initialization is done, especially for Tier-1).

So let's keep it simple and clear.

**Comment by tannergooding** [comment]
@aaronfranke, I'll take this to API review if you could update the original post to follow the "good example" listed under step 1 of our [API Review Process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md. You don't strictly speaking need all the sections, but providing the rationale/usage and proposed API sections would be ideal as it helps the API review process overall.

For `Tau` in particular, I'm fine with taking it to API review as `Tau`, but the other possible names (such as `TwoPi`) will likely get brought up as well.
If possible, it would be great if you could also list some of the other common math constants as part of the proposal, so they can all be reviewed at once (I believe https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html lists the most common ones, but there may be others).
Any constants proposed for `System.Math` should likewise be proposed for `System.MathF`.

**Comment by aaronfranke** [comment]
@tannergooding Thanks, I've went ahead and done that (using my Color proposal as a reference).

**Comment by GrabYourPitchforks** [comment]
@tannergooding Interestingly, the CRT math constants you linked to define all kind of other variants, but not the specific value 2π. :)

**Comment by tannergooding** [comment]
@GrabYourPitchforks, ah you're right, from the `corecrt_math_defines.h` file with MSVC:
```cpp
    // Definitions of useful mathematical constants
    //
    // Define _USE_MATH_DEFINES before including <math.h> to expose these macro
    // definitions for common math constants.  These are placed under an #ifdef
    // since these commonly-defined names are not part of the C or C++ standards
    #define M_E        2.71828182845904523536   // e
    #define M_LOG2E    1.44269504088896340736   // log2(e)
    #define M_LOG10E   0.434294481903251827651  // log10(e)
    #define M_LN2      0.693147180559945309417  // ln(2)
    #define M_LN10     2.30258509299404568402   // ln(10)
    #define M_PI       3.14159265358979323846   // pi
    #define M_PI_2     1.57079632679489661923   // pi/2
    #define M_PI_4     0.785398163397448309616  // pi/4
    #define M_1_PI     0.318309886183790671538  // 1/pi
    #define M_2_PI     0.636619772367581343076  // 2/pi
    #define M_2_SQRTPI 1.12837916709551257390   // 2/sqrt(pi)
    #define M_SQRT2    1.41421356237309504880   // sqrt(2)
    #define M_SQRT1_2  0.707106781186547524401  // 1/sqrt(2)
```

**Comment by aaronfranke** [comment]
@tannergooding It sounds like we also have the opportunity to introduce this constant with the `Tau` name into MSVC/GCC/etc, though that's a separate discussion for another time and repo :)

**Comment by bartonjs** [comment]
Approved as Tau:

```C#
public partial class Math
{
    public const double Tau = 6.283185307179586476925;
}
public partial class MathF
{
    public const float Tau = 6.283185307f;
}
```

**Comment by john-h-k** [comment]
Can I take this?

**Comment by tannergooding** [comment]
Assigned out, thanks @john-h-k!
