### ISSUE TITLE
Interlocked.CompareExchange missing for uint, ulong and (if possible) general structs.

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#24694]
_From @redknightlois on May 18, 2017 19:47_

I recently needed to use ```Interlocked.CompareExchange``` inside a function with the following form:

```csharp
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private bool TryClaimSlot(ref uint entryKey, int key)
        {
            var entryKeyValue = entryKey;
            //zero keys are claimed via hash
            if (entryKeyValue == 0 & key != 0)
            {
                entryKeyValue = Interlocked.CompareExchange(ref entryKey, key, 0);
                if (entryKeyValue == 0)
                {
                    // claimed a new slot
                    this.allocatedSlotCount.Increment();
                    return true;
                }
            }

            return key == entryKeyValue;
        }
```

problem is that it can´t be done because the ```Interlocked.CompareExchange<T>``` requires it to be a class.

Also if anyone knows a workaround for it, I would appreciate it. 

_Copied from original issue: dotnet/coreclr#11723_

**Comment by terrajobst** [comment]
* Makes sense, we added unsinged for the APIs approved in #23819

```C#
namespace System.Threading
{
    public static partial class Interlocked
    {
        // New proposed APIs, pretty much a carbon copy of the above but unsigned
        // All of these would be marked [CLSCompliant(false)]

        public static uint Add(ref uint location1, uint value);
        public static ulong Add(ref ulong location1, ulong value);
        public static uint CompareExchange(ref uint location1, uint value, uint comparand);
        public static ulong CompareExchange(ref ulong location1, ulong value, ulong comparand);
        public static UIntPtr CompareExchange(ref UIntPtr location1, UIntPtr value, UIntPtr comparand);
        public static uint Decrement(ref uint location);
        public static ulong Decrement(ref ulong location);
        public static uint Exchange(ref uint location1, uint value);
        public static ulong Exchange(ref ulong location1, ulong value);
        public static UIntPtr Exchange(ref UIntPtr location1, UIntPtr value);
        public static uint Increment(ref uint location);
        public static ulong Increment(ref ulong location);
        public static ulong Read(ref ulong location);

        // Since this were approved in #23819 we should add them:
        // All of these would be marked [CLSCompliant(false)]

        public static int And(ref uint location1, uint value);
        public static long And(ref ulong location1, ulong value);
        public static int Or(ref uint location1, uint value);
        public static long Or(ref ulong location1, ulong value);
        public static int Xor(ref uint location1, uint value);
        public static long Xor(ref ulong location1, ulong value);
    }
}
```

**Comment by tannergooding** [comment]
@stephentoub, we should probably clarify that `Xor` wasn't added in #32216 

I'm not sure I like that we added the first two (`And` and `Or`), but not the third; as they usually come together (even if we didn't have an immediate use case in the framework).

**Comment by stephentoub** [comment]
> as they usually come together

There are lots of other operations that weren't included.  What about Interlocked.Not, for example?

We should only add methods when there's a demonstrated need.  I've never seen C# code that needed Interlocked.Xor; if such a need appears, we can add it then.

**Comment by tannergooding** [comment]
> What about Interlocked.Not

It wasn't part of the API review.

>  Interlocked.Mul? Interlocked.EverythingCsharpHasAnOperatorFor?

Not supported by most/any hardwar:
* x86 supports: `ADD, ADC, AND, BTC, BTR, BTS, CMPXCHG, CMPXCH8B,
CMPXCHG16B, DEC, INC, NEG, NOT, OR, SBB, SUB, XOR, XADD, and XCHG`
* Arm64 supports basically the same, but also atomic min, max

> We should only add methods when there's a demonstrated need.

I think there is a slight difference when it comes to "primitive" operations. Interlocked operations are some of the most basic operations on top of which other threading/locking algorithms are implemented.
Providing them gives a foundation on which other things can be built (and which certain things cannot be built without them)

**Comment by stephentoub** [comment]
> It wasn't part of the API review.

My point was that there are lots of other things beyond these.

> Not supported by most/any hardwar

So?  This isn't about hardware support.  These APIs were checked in without hardware support.  We can ship the product without hardware support.

> Providing them gives a foundation on which other things can be built

.NET has existed for almost 20 years without these variants.  We shouldn't be adding effectively dead code until it'll actually be used.

**Comment by tannergooding** [comment]
> we didn't spend time in API review discussing the merits of each individually; we should in the future.

I agree. I think we should try to bring these points up in API review so we don't approve and then immediately turn around and not implement them.

> .NET has existed for almost 20 years without these variants.

While I don't know of any usages in the framework, a search shows there are various existing usages of equivalents from other languages/frameworks. For example `InterlockedXor` (C++ Intrinsic and HLSL for GPU compute) or `atomic::fetch_xor` (C++ stdlib, similar exists in other languages like JS, Java, and Rust), so there are valid scenarios under which `Interlocked.Xor` could be used in .NET.

> So? This isn't about hardware support

Right, and you don't need anything except CompareExchange support of the appropriate size (to prevent tearing) for most single operations to be implemented.

But, I think hardware support is a reasonable baseline for what other languages/frameworks implement and expose. It also represents something that users cannot implement themselves, as we don't have a way for users to emit something like `lock xor` or `ldeor` without the JIT intrinsifying some method (indirect calls and while loops using cmpxchg add overhead and can be non beneficial, but are still better than nothing).

**Comment by stephentoub** [comment]
> I think we should try to bring these points up in API review so we don't approve and then immediately turn around and not implement them.

Agreed.  In this case, when I actually looked at it, I turned around and asked the dev that proposed the API, and he agreed we could do without it.

> It also represents something that users cannot implement themselves

Sure.  But even per your list, And/Or/Xor was incomplete in this regard.  If the goal is completeness as compared to some set of hardware primitives, that should be a separate issue.  From my perspective, this issue was about something actually being needed, and I see no evidence that C# developers are clamoring for Interlocked.Xor.

> a search shows there are various existing usages of equivalents from other languages/frameworks

Any in C#?

**Comment by tannergooding** [comment]
> Any in C#?

Not that immediately popped up in a search. Most of the results were around the C++ intrinsic and grepping code for sequence of `^` followed by a `CompareExchange` isn't exactly easy 😄 

> Sure. But even per your list, And/Or/Xor was incomplete in this regard. If the goal is completeness as compared to some set of hardware primitives, that should be a separate issue. From my perspective, this issue was about something actually being needed, and I see no evidence that C# developers are clamoring for Interlocked.Xor. In contrast, I've seen a multitude of projects implement their own And/Or, including some of ours.

I think that is reasonable. There were others (like atomic bitwise select/clear/reset) which were mentioned during the review that we likewise said should be in a separate "completeness" proposal.

**Comment by redknightlois** [comment]
> From my perspective, this issue was about something actually being needed, and I see no evidence that C# developers are clamoring for Interlocked.Xor. In contrast, I've seen a multitude of projects implement their own And/Or, including some of ours.
Most people that need atomic Xor won't be clamoring for it, those that don't have them just disregard certain types of high-performance algorithms that require them. It is a completeness issue, no one will clamor for anything that they cannot implement; most will just throw their hands in the air, and you won't hear a thing. Having said so, I haven't stumbled on an algorithm that uses XOR atomically, but probably the reason is that as there are not many providing implementations it either as it is a very niche thing today. For the long term, completeness is always best for a platform, but if that delays the current proposal, I would just go with the partial one.

**Comment by jkotas** [comment]
> algorithm that uses XOR atomically, but probably the reason is that as there are not many providing implementations of it

If you need atomic XOR (or any other bit transformation), you can trivially implement it using `CompareExchange`. Compared to the specialized atomic instructions, the implementation using `CompareExchange` is not that much slower to make it a deal breaker.

**Comment by stephentoub** [comment]
> Most people that need atomic Xor won't be clamoring for it

If they "need" it, they'll implement it (CompareExchange loop... and if they can't implement it, personally I'd prefer they not be trying to use lock-free code and the Interlocked type at all). That's what I meant by clamoring for it. Can you please point to real C# examples where someone implemented it? If not, adding such a method in the name of completeness is just adding functionality that'll needto be implemented/tested/documented/maintained/etc. for zero actual benefit. If/when such need is demonstrated in the future, it can be added.

**Comment by sunkin351** [comment]
If you guys are gonna be adding unsigned variants to `Interlocked`, may I suggest that you add some sort of atomic Subtraction method? At least for unsigned, as its not too obvious as to how to do that without a subtraction method...
