### ISSUE TITLE
System.Security.Cryptography.OpenSsl is breaking OSX outerloop

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#24736]
From the log

```
===========================================================================================================
/private/tmp/helix/working/B2560951/w/B7430A6F/e /private/tmp/helix/working/B2560951/w/B7430A6F/e
  Discovering: System.Security.Cryptography.OpenSsl.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.OpenSsl.Tests (found 598 of 602 test cases)
  Starting:    System.Security.Cryptography.OpenSsl.Tests (parallel test collections = on, max threads = 8)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1043264b2 - /private/tmp/helix/working/B2560951/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_dump_native_crash_info
	0x1042c89c5 - /private/tmp/helix/working/B2560951/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_handle_native_crash
	0x104320e0d - /private/tmp/helix/working/B2560951/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : altstack_handle_and_restore
	0x1088544d9 - /usr/local/ssl/macos-x86_64/lib/libcrypto.1.0.0.dylib : BN_div
	0x108860db0 - /usr/local/ssl/macos-x86_64/lib/libcrypto.1.0.0.dylib : BN_generate_prime_ex
	0x1088bc94e - /usr/local/ssl/macos-x86_64/lib/libcrypto.1.0.0.dylib : RSA_generate_key_ex
	0x108dd8279 - Unknown
```

Builds
- https://dev.azure.com/dnceng/public/_build/results?buildId=503305
- https://dev.azure.com/dnceng/public/_build/results?buildId=503113
- https://dev.azure.com/dnceng/public/_build/results?buildId=503063

Test Runs
- netcoreapp5.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-Mono_release-OSX.1015.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-Mono_release-OSX.1015.Amd64.Open
- netcoreapp5.0-OSX-Release-x64-Mono_release-OSX.1015.Amd64.Open

**Comment by jaredpar** [comment]
Based on the evidence we should pretty quickly disable this series of tests on OSX. It's the primary reasons why outer loops are failing at the moment.

**Comment by jaredpar** [comment]
@bartonjs

**Comment by bartonjs** [comment]
Well, really the question is "where did this OpenSSL 1.0 come from?"  As far as I know/knew, the macOS images all updated to OpenSSL 1.1.

Something built a crashing OpenSSL on those machines.  Whoever / whatever did that should stop doing that.

**Comment by jaredpar** [comment]
> Something built a crashing OpenSSL on those machines. Whoever / whatever did that should stop doing that.

Agree. But in the meantime these tests are blocking all outer loop run. Should disable while we work out the root.

**Comment by bartonjs** [comment]
If you're hoping that I'll open a PR to disable the tests, first you'll have to teach me what such a PR would look like :smile:

**Comment by jaredpar** [comment]
@bartonjs 

Good news. @danmosemsft has added just such documentation

https://github.com/dotnet/runtime/blob/9900dfb4b2e32cf02ca846adaf11e93211629ede/docs/workflow/testing/libraries/filtering-tests.md#platformspecificattribute

**Comment by bartonjs** [comment]
If the tests are only failing in OuterLoop, I'm not going to allow them to be disabled in the inner loop.

**Comment by danmosemsft** [comment]
@bartonjs please do let’s do all we can to help @jaredpar get outerloop clean.

**Comment by bartonjs** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=503063 seems to be inner; so it's an all-up machine configuration problem, not just a special outerloop config problem.

I guess I'll just mark the entirety of the OpenSSL test library as skip-macOS, and be more aggressive about deciding if maybe we just stop supporting OpenSSL interop on that platform.

**Comment by bartonjs** [comment]
And now I've learned, what I know of as "Outer Loop" (e.g. the runs that do networking tests off-box) and what @jaredpar is referring to as "outer loop" aren't the same thing.  (This seems to be more what I understood to be a "fullMatrix" run, and is specific to macOS 10.15, which got turned on just a couple days ago)

**Comment by danmosemsft** [comment]
Thanks!

**Comment by jaredpar** [comment]
> And now I've learned, what I know of as "Outer Loop"

Yeah I hadn't realized how our naming here may be confusing given some how outer loop in the name and others don't. Basically though outer loop is any of our build definitions that run on CI (aka Rolling builds). The main ones we're tracking at the moment are the following:

| Outerloop | Full Name |
| --- | --- |
| runtime | [runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686) | 
| coreclr | [runtime-coreclr outerloop](https://dev.azure.com/dnceng/public/_build?definitionId=655) |
| libraries | [runtime-libraries outerloop](https://dev.azure.com/dnceng/public/_build?definitionId=675) |
| libraries windows | [runtime-libraries outerloop-windows](https://dev.azure.com/dnceng/public/_build?definitionId=676) |
| libraries linux | [runtime-libraries outerloop-linux](https://dev.azure.com/dnceng/public/_build?definitionId=677) |
| libraries osx | [runtime-libraries outerloop-osx](https://dev.azure.com/dnceng/public/_build?definitionId=678) |
| crossgen2 | [runtime-coreclr crossgen2 outerloop](https://dev.azure.com/dnceng/public/_build?definitionId=701) | 

The `runtime` one is effectively our PR loop but post merge. It's what CI Council end up looking at for quality hence the one we spend the most time monitoring.

**Comment by bartonjs** [comment]
This was addressed already.
