### ISSUE TITLE
Support equivalent of IQueryable<ComposablePartDefinition> Parts in System.Composition

### ISSUE THREAD

**Issue by tedescomicchidev** [dotnet/runtime#24763]
`System.ComponentModel.Composition` (MEF1) has the ability to list available `Parts` through `System.ComponentModel.Composition.Primitives`. It would be useful to have this ability in `System.Composition` (MEF2).
If possible, since there could be multiple `[Export]`s for the same `type`, it would be great to be able to query also by `[Export]` name.

**Comment by ericstj** [comment]
Can you make write up the suggested API and behavior?
