### ISSUE TITLE
Respect IReadOnlyList<T> in the BCL

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/runtime#24793]
The following condition appears in many variations plenty of times throughout the BCL, especially in LINQ, (From [`ElementAt`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/ElementAt.cs#L28-L31)):
 
```c#
if (source is IList<TSource> list)
{
    return list[index];
}
```

But there is also `IReadOnlyList<T>` which provides the same thing and is not considered because it doesn't overlap with `IList<T>`, and the fact that random access is provided by it is neglected in the BCL.
Why is that?

Similar to `ICollection<T>` and `IReadOnlyCollection<T>`, see dotnet/runtime#23337.

**Comment by Soon5** [comment]
> This is one thing that I would consider API design flaw as you can't implement `IReadOnlyList<T>` only or you will get random access.

I second that. I was just implementing a new class with only Implementing IReadOnlyList. If I also have to implement IList so I can use it with LINQ properly, the whole Idea of having a ReadOnly Interface is gone.

Also the additional Type check performance argument brought up I don't really agree with. If the 2nd Check is done after the IList check, for all legacy code already implementing IList, the execution path is not changing, and for all the others, the fallback in case of LINQ is anyway IEnumerable which is slow anyway.

**Comment by eiriktsarpalis** [comment]
This is related to #42254, I'm going to close this so that we can consolidate the conversation in one issue.
