### ISSUE TITLE
[API Proposal]: Add a generic OrderedDictionary class

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/runtime#24826]
EDITED on 4/10/2024 by @stephentoub to update proposal

Often times I've come across places when needing a `Dictionary` where the insertion order of the elements is important to me. Unfortunately, .NET does not currently have a generic `OrderedDictionary` class. We've had a non-generic `OrderedDictionary` class since .NET Framework 2.0 which oddly enough was when generics were added but no generic equivalent. This has forced many to roll their own solution, typically by using a combination of a `List` and `Dictionary` field resulting in the worst of both worlds in terms of performance and resulting in larger memory usage, and even worse sometimes users instead rely on implementation details of `Dictionary` for ordering which is quite dangerous.

## Proposed API
```c#
namespace System.Collections.Generic;

public class OrderedDictionary<TKey, TValue> :
    IDictionary<TKey, TValue>, IReadOnlyDictionary<TKey, TValue>, IDictionary,
    IList<KeyValuePair<TKey, TValue>>, IReadOnlyList<KeyValuePair<TKey, TValue>>, IList
    where TKey : not null
{
    public OrderedDictionary();
    public OrderedDictionary(int capacity);
    public OrderedDictionary(IEqualityComparer<TKey>? comparer);
    public OrderedDictionary(int capacity, IEqualityComparer<TKey>? comparer);
    public OrderedDictionary(IDictionary<TKey, TValue> dictionary);
    public OrderedDictionary(IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey>? comparer);
    public OrderedDictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection);
    public OrderedDictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection, IEqualityComparer<TKey>? comparer);

    public IEqualityComparer<TKey> Comparer { get; }
    public OrderedDictionary<TKey, TValue>.KeyCollection Keys { get; }
    public OrderedDictionary<TKey, TValue>.ValueCollection Values { get; }
    public int Count { get; }
    public TValue this[TKey key] { get; set; }

    public void Add(TKey key, TValue value);
    public void Clear();
    public bool ContainsKey(TKey key);
    public bool ContainsValue(TValue value);
    public KeyValuePair<TKey, TValue> GetAt(int index);
    public OrderedDictionary<TKey, TValue>.Enumerator GetEnumerator();
    public int IndexOf(TKey key);
    public void Insert(int index, TKey key, TValue value);
    public bool Remove(TKey key);
    public bool Remove(TKey key, [MaybeNullWhen(false)] out TValue value);
    public void RemoveAt(int index);
    public void SetAt(int index, TValue value);
    public void SetAt(int index, TKey key, TValue value);
    public void TrimExcess();
    public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TValue value);

    public struct Enumerator : IEnumerator<KeyValuePair<TKey, TValue>>
    {
        public KeyValuePair<TKey, TValue> Current { get; }
        public void Dispose();
        public bool MoveNext();
    }

    public sealed class KeyCollection : IList<TKey>, IReadOnlyList<TKey>, IList
    {
        public int Count { get; }
        public bool Contains(TKey key);
        public void CopyTo(TKey[] array, int arrayIndex);
        public OrderedDictionary<TKey, TValue>.KeyCollection.Enumerator GetEnumerator();

        public struct Enumerator : IEnumerator<TKey>
        {
            public TKey Current { get; }
            public bool MoveNext();
            public void Dispose();
        }
    }

    public sealed class ValueCollection : IList<TValue>, IReadOnlyList<TValue>, IList
    {
        public int Count { get; }
        public void CopyTo(TValue[] array, int arrayIndex);
        public OrderedDictionary<TKey, TValue>.ValueCollection.Enumerator GetEnumerator();

        public struct Enumerator : IEnumerator<TValue>
        {
            public TValue Current { get; }
            public bool MoveNext();
            public void Dispose();
        }
    }
}
```

Perhaps one of the reasons there was no generic `OrderedDictionary` added initially was due to issues with having both a key and index indexer when the key is an `int`. A call to the indexer would be ambiguous. Roslyn prefers the non-generic parameter so in this case the index indexer will be called.

## API Details
* `Insert` allows `index` to be equal to `Count` to insert the element at the end.
* `SetAt(int index, TValue value)` requires `index` to be less than `Count` but `SetAt(int index, TKey key, TValue value)` allows `index` to be equal to `Count` similar to `Insert`.
* Performance will be the same as `Dictionary` for all operations except `Remove` which will necessarily be `O(n)`. `Insert` and `RemoveAt` which aren't members of `Dictionary` will also be `O(n)`.

## Open Questions
* Should the namespace be `System.Collections.Generic` when it could easily be `System.Collections.Specialized` where the non-generic version is located? I just felt this collection is far more useful to be relegated to that namespace.
* Should the non-generic interfaces `ICollection`, `IList`, and `IOrderedDictionary` be implemented?

## Updates
* Added constructor overloads for `IEnumerable<KeyValuePair<TKey, TValue>>`.
* Added `ContainsValue` method due to being needed for the `ValueCollection.Contains` method.
* Proposal no longer advocates for throwing an exception when using an indexer while the key is an int.

**Comment by ahdung** [comment]
Any news?

**Comment by eiriktsarpalis** [comment]
We have no plans on adding such a type in our immediate roadmap. We will post an update on this thread as soon as anything changes.

**Comment by alelom** [comment]
This has been around in various forms and other issues for years now. Is there really no priority in closing a glaring gap in Microsoft Collections? Especially given the mess of its various implementations - moved from a repo to another, without a stable nuget available. I dislike having to resort to third-party implementations for stuff like this.

**Comment by fdcastel** [comment]
Just passing to say I am just another guy missing this.

For reference: Here is a [StackOverflow answer with a solution](https://stackoverflow.com/a/9844528/33244) from @mattmc3 (in 2012).

Quoting the initial part of the answer: 

> Implementing a generic OrderedDictionary isn't terribly difficult, but it's unnecessarily time consuming and frankly this class is a huge oversight on Microsoft's part.

This answer has over +100 votes in StackOverflow.

**Comment by MV10** [comment]
Thanks to @alelom ... I got here from a StackOverflow question looking for this feature _13 years ago_...

**Comment by AndriySvyryd** [comment]
Also consider adding these methods
``` C#
void Sort()
void Sort(IComparer<TKey> Comparer)
void SortedInsert(TKey key, TValue value)
void SortedInsert(TKey key, TValue value, IComparer<TKey> Comparer)
```

**Comment by JoshuaNitschke** [comment]
Came here to say I would like this too.

**Comment by claudiudc** [comment]
> Thanks for putting that chart together. The implementation will be nearly identical to [`Dictionary<K,V>`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs) with a bucket and entries array except the entries in the entries array will be contiguous and ordered.
> 
> Below is the chart filled out
> Operation 	Dictionary<K,V> 	SortedDictionary<K,V> 	SortedList<K,V> 	OrderedDictionary<K,V>
> this[key] 	O(1) 	O(log n) 	O(log n) or O(n) 	O(1)
> this[index] 	n/a 	n/a 	n/a 	O(1)
> Add(key,value) 	O(1) 	O(log n) 	O(n) 	O(1)
> Remove(key) 	O(1) 	O(log n) 	O(n) 	O(n)
> RemoveAt(index) 	n/a 	n/a 	n/a 	O(n)
> ContainsKey(key) 	O(1) 	O(log n) 	O(log n) 	O(1)
> ContainsValue(value) 	O(n) 	O(n) 	O(n) 	O(n)
> IndexOf(key) 	n/a 	n/a 	n/a 	O(1)
> Insert(index,key,value) 	n/a 	n/a 	n/a 	O(n)
> Space efficiency 	good 	worst 	medium 	good
> Insert/Remove sorted data 	n/a 	O(log n) 	O(n) 	n/a
> From sorted data 	n/a 	? 	better? 	n/a

Why Remove(key) and RemoveAt(index) are O(n)?
They should be O(1)

Implementation should keep the index as a (int, TValue) in the value of the key itself.

**Comment by tjpalmer** [comment]
Different solutions are possible, and remove is the hard part of ordered dictionaries.

- Keeping the index with the entry makes for fast add and remove but slow iteration. Also potentially limits the lifetime of a dictionary with lots of add and remove.
- Current non-generic OrderedDictionary instead has O(n) removal but allows for O(1) ordered access.
- Allowing sparsity in the entry array (like in CPython and V8, if I understand correctly) allows for faster removal at increased memory cost.
- Other options like the Rust crate IndexMap lose insertion order on remove but are fast otherwise.
- LinkedHashMap in Java needs lots of individually allocated objects and has to jump around for iteration.
- Making a dense array of entries with indices for linked list avoid lots of objects but has a bit more overhead than just the order number and still requires jumping around on iteration.

Different decisions make different presumptions about how something's being used and/or what the user cares about.

**Comment by claudiudc** [comment]
This is just a possible impl(not smart enough) of such a need, however without having detailed checking, sync for updates, sync of capacity(size of dict + list) and many more. And the concept can be optimized a lot to use less than 3 objects(self and 2 collections)
I will try to see if I can get some time to give a clean one

Short objective: an ordered dictionary(dictionary + ordered elements used in foreach, based on insertion order)
- so not an ordered dictionary + an ordered list that overcomplicates thinks with indexed, we don't need indexes for this requirement.


Obs: I do not see a problem on iterations
I do not see a lifetime problem
So: add, set, remove, iterate would have O(1), when the capacity of collection is not reached yet
Of course, you pay for what you need: memory

```

[DebuggerDisplay($"{{{nameof(ToDebuggerDisplay)}(),nq}}")]
internal class SortedDictionary<Tkey,TValue> :IReadOnlyCollection<TValue>
{
    [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
    private readonly LinkedList<TValue> _valuesNodes;
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private readonly Dictionary<Tkey, LinkedListNode<TValue>> _toProbePropertyNodesByName;

    public SortedDictionary()
    {
        _valuesNodes = new LinkedList<TValue>();
        _toProbePropertyNodesByName = new Dictionary<Tkey, LinkedListNode<TValue>>();
    }

    IEnumerator<TValue> IEnumerable<TValue>.GetEnumerator()
    {
        return _valuesNodes.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return _valuesNodes.GetEnumerator();
    }


    public void Add(Tkey key, TValue value)
    {
        lock (_valuesNodes)
        {
            ref LinkedListNode<TValue> valueByRef = ref CollectionsMarshal.GetValueRefOrAddDefault(_toProbePropertyNodesByName, key, out bool exists);
            if (exists)
            {
                throw new ArgumentException($"An item with the same key has already been added. Key: {key}'");
            }
            else
            {
                valueByRef = _valuesNodes.AddLast(value);
            }
        }
    }

    public bool Remove(Tkey key)
    {
        bool entryWasRemoved;
        lock (_valuesNodes)
        {
            entryWasRemoved = _toProbePropertyNodesByName.Remove(key, out var removedValue);
            if (entryWasRemoved)
            {
                _valuesNodes.Remove(removedValue);
            }
        }
        return entryWasRemoved;
    }

    public IEnumerator<TValue> GetEnumerator()
    {
        return _valuesNodes.GetEnumerator();
    }

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    public int Count
    {
        get { return _valuesNodes.Count; }
    }

    public TValue this[Tkey key]
    {
        get { return Get(key); }
        set { Set(key, value); }
    }

    public bool Contains(Tkey key)
    {
        return _toProbePropertyNodesByName.ContainsKey(key);
    }

    public TValue Get(Tkey key)
    {
        ref LinkedListNode<TValue> valueByRef = ref CollectionsMarshal.GetValueRefOrNullRef(_toProbePropertyNodesByName, key);
        if (Unsafe.IsNullRef(ref valueByRef))
        {
            throw new KeyNotFoundException($"The given property name '{key}' was not present in the collection.");
        }
        else
        {
            return valueByRef.Value;
        }
    }

    public void Set(Tkey key, TValue value)
    {
        lock (_valuesNodes)
        {
            ref LinkedListNode<TValue> valueByRef = ref CollectionsMarshal.GetValueRefOrAddDefault(_toProbePropertyNodesByName, key, out bool exists);
            if (exists)
            {
                valueByRef.Value = value;
            }
            else
            {
                
                valueByRef = _valuesNodes.AddLast(value);
            }
        }
    }

    public bool TryGet(Tkey key, out TValue value)
    {
        ref LinkedListNode<TValue> valueByRef = ref CollectionsMarshal.GetValueRefOrNullRef(_toProbePropertyNodesByName, key);
        if (Unsafe.IsNullRef(ref valueByRef))
        {
            value = default;
            return false;
        }
        else
        {
            value = valueByRef.Value;
            return true;
        }
    }

    internal string ToDebuggerDisplay()
    {
        return $"Count = {_valuesNodes.Count}";
    }
}
```

**Comment by tjpalmer** [comment]
> LinkedHashMap in Java needs lots of individually allocated objects and has to jump around for iteration.

**Comment by tjpalmer** [comment]
From .NET documentation:

> Each element of the [LinkedList<T>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlist-1?view=net-8.0) collection is a [LinkedListNode<T>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlistnode-1?view=net-8.0).

Also:

> public sealed class LinkedListNode<T>

Lots of individually allocated objects.

**Comment by claudiudc** [comment]
> From .NET documentation:
> 
> > Each element of the [LinkedList](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlist-1?view=net-8.0) collection is a [LinkedListNode](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlistnode-1?view=net-8.0).
> 
> Also:
> 
> > public sealed class LinkedListNode
> 
> Lots of individually allocated objects.

As I said, this is just a possible idea, do not take it 1:1, I am aware that a linked node is allocated for every entry. 
I do not have enough time to write an impl from scratch but as I mention, similar(it does not have to be base on linked list) can be made with o(1) remove.

**Comment by MV10** [comment]
Interesting that only 73 issues have been tagged with the _wishlist_ label (and just 36 if you also include _api-suggestion_). I'd have expected such a small number of features to get a bit more attention.

**Comment by ian-g-holm-intel** [comment]
I too am in need of this. I need to be able to serialize an OrderedDictionary. Currently we're using the non-generic version and it requires every value object to include the type information. If there was a generic OrderedDictionary<> the type information would only be serialized once with the dictionary object type.

**Comment by alexrp** [comment]
I am actually genuinely curious what it would take to move this forward. It's entirely unclear to me what the *criteria* might be, given these observations:

* In the time that this issue has existed, it has accumulated more upvotes than the accepted and implemented [priority queue](https://github.com/dotnet/runtime/issues/43957) and [frozen collections](https://github.com/dotnet/runtime/issues/67209) proposals combined.
    * See also #64829 which is similar, but not quite the same thing.
* The BCL already has a [non-generic version](https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary) and the (rather unfortunate) recommendation you'll often see online is to use a generic wrapper around it and eat the boxing penalty.
* [This EF Core pull request](https://github.com/dotnet/efcore/pull/32124) is also telling and it's a first-party project.
* [The BCL itself](https://github.com/dotnet/runtime/blob/8b082e10aa8e7ca3764f8aea29f4aa961b79c0f2/src/libraries/System.IO.Packaging/src/System/IO/Packaging/OrderedDictionary.cs) could apparently use it.
* [This GitHub code search](https://github.com/search?q=%22class+ordereddictionary%22+language%3Ac%23&type=code) speaks for itself, I think.
* I don't know if the offer still stands, but @TylerBrinkley [offered in 2018](https://github.com/dotnet/runtime/issues/24826#issuecomment-363536088) to do the implementation work.
* [Microsoft.Experimental.Collections](https://www.nuget.org/packages/Microsoft.Experimental.Collections) (containing Tyler's implementation) has quite a lot of downloads and some notable dependents for an experimental package.
* This isn't even getting into other platforms like SO and Discord where an ordered dictionary is a very common ask.

Evidently there is real-world demand here. It is not a niche ask. It seems like the only real blocker is getting this through API review? Why can that not happen? I would just like to get some insight into the decision-making process here, because all available evidence leaves me very confused.

**Comment by eiriktsarpalis** [comment]
You're right to point out that the primary bottleneck is getting the proposal lined up for API review. This does require some prep-work, including evaluating prototypes and ensuring that the API shape is on par with other designs that have already been shipped. Not all API proposals are created equal from a complexity standpoint however, and championing brand new collection types can be a long-running and expensive process. It's unlikely we could get around to such a proposal unless it registers high in our prioritization.

**Comment by alexrp** [comment]
Thanks for the reply! I totally understand and agree with most of what you bring up, save for this point:

> It's unlikely we could get around to such a proposal unless it registers high in our prioritization.

This is the part I was really getting at. What *would* make it register high in your prioritization? As I mentioned, it's unclear to me how e.g. frozen collections could have registered higher going by the indicators I posted. (I don't say that to knock them, by the way - I use them myself! - they're just an example to illustrate the point.)

If the answer is "we simply decided we really cared about maximizing read performance for collections in that release cycle" then, hey, fair enough. Like I said, I'm just looking for some insight into the process here. I think a lot of folks have the impression that prioritization of API proposals is to a large extent driven by the volume of demand. If that isn't the case, I think it would be good to just clarify what the factors are.

**Comment by eiriktsarpalis** [comment]
> What would make it register high in your prioritization? As I mentioned, it's unclear to me how e.g. frozen collections could have registered higher going by the indicators I posted. 

While our planning does take upvotes into consideration, it is not the only driving factor. In the interest of transparency, frozen collections were added because they were a first-party team requirement at the time. There are other factors as well: as you mention an implementation is already available via a NuGet package which plays a role as well. Not everything needs to be part of the BCL, or at least it doesn't urgently need to be part of the BCL.

**Comment by eiriktsarpalis** [comment]
> If the answer is "we simply decided we really cared about maximizing read performance for collections in that release cycle" then, hey, fair enough.  I think a lot of folks have the impression that prioritization of API proposals is to a large extent driven by the volume of demand.

It goes without saying that our resources aren't infinite and our backlog is substantial. Oftentimes we might not invest on collections at all in a particular release cycle, simply because the team is pursuing different opportunities.

**Comment by alexrp** [comment]
To this particular point:

> There are other factors as well: as you mention an implementation is already available via a NuGet package which plays a role as well.

This is true of course, but with some caveats: Microsoft.Experimental.Collections is pre-release, so you will get [NU5104](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104) if you use package validation. There's also the fact that, with corefxlab archived, the package is deprecated and unmaintained, and even finding the source code requires a fair bit of digging.

To be fair, nothing stops anyone from taking that code and publishing a new package. But I suspect part of the problem here is that, rightly or wrongly, .NET doesn't really have a culture of publishing small utility packages that are narrowly focused on one specific thing, as you'd see in e.g. Node.js and Rust. And on top of that, maintainers of libraries don't seem to like taking dependencies on such small utility packages. So, many who aren't using Microsoft.Experimental.Collections just end up copying an implementation into their project. I think several of the links I provided earlier at least partially substantiate this line of thinking.

**Comment by danmoseley** [comment]
> NET doesn't really have a culture of publishing small utility packages that are narrowly focused on one specific thing, as you'd see in e.g. Node.js and Rust.

I wonder why this is. But that is off topic ..

**Comment by stephentoub** [comment]
We should just do this. As has been noted, there a plethora of implementations floating around, including very close to home in System.IO.Packaging, EF Core, WCF, MAUI, and WPF, and then also as noted there a multitude of implementations in a myriad of other projects. We can do it once in the core libraries and avoid all that duplication, for something where we already have a non-generic implementation and just need a generic one. We can also start with minimal surface area and add to it in the future if we're missing anything.

Some notes on the original proposal:
- We should not have an indexer for both int and TKey: that's ambiguous if TKey is an int.
- The KeyCollection should have its Contains be public.
- I don't know why Dictionary's KeyCollection/ValueCollection have public ctors. That should not be necessary there or here.
- There's no need for GetValue or SetValue: that's just the indexer.
- Rather than two overloads of GetAt, I suggest there's just one that returns a KeyValuePair.

I've updated the top proposal and marked it ready for review.

**Comment by TylerBrinkley** [comment]
When `TKey` is an `int` C# will prefer the explicit `int` overload instead of `TKey` but I can see how that could cause users problems so if we're not including both indexers that seems okay.

**Comment by stephentoub** [comment]
> When `TKey` is an `int` C# will prefer the explicit `int` overload instead of `TKey` but I can see how that could cause users problems so if we're not including both indexers that seems okay.

The ambiguity is there are then two overloads with the exact same arguments but that do two completely different things, e.g. this will successfully augment a histogram:
```C#
public static void AddToHistogram(OrderedDictionary<string, int> counts, IEnumerable<string> source)
{
    foreach (var item in source) counts[item] = counts.TryGetValue(item, out int count) ? count + 1 : 1;
}
```
but this will likely either blow up or produce meaningless results:
```C#
public static void Histogram(OrderedDictionary<int, int> counts, IEnumerable<int> source)
{
    foreach (var item in source) counts[item] = counts.TryGetValue(item, out int count) ? count + 1 : 1;
}
```

**Comment by TylerBrinkley** [comment]
Thanks, yeah I agree it would likely cause issues for some users and using the `GetAt` and `SetAt` methods instead is not too burdensome even if wouldn't be necessary for most collections when `TKey` is not an `int`.

**Comment by terrajobst** [comment]
* Looks good as proposed
* We might want to add an overload of `GetAt()`/`SetAt` that takes `Index`
* Should probably go into `System.Collections.dll`

```C#
namespace System.Collections.Generic;

public class OrderedDictionary<TKey, TValue> :
    IDictionary<TKey, TValue>, IReadOnlyDictionary<TKey, TValue>, IDictionary,
    IList<KeyValuePair<TKey, TValue>>, IReadOnlyList<KeyValuePair<TKey, TValue>>, IList
    where TKey : not null
{
    public OrderedDictionary();
    public OrderedDictionary(int capacity);
    public OrderedDictionary(IEqualityComparer<TKey>? comparer);
    public OrderedDictionary(int capacity, IEqualityComparer<TKey>? comparer);
    public OrderedDictionary(IDictionary<TKey, TValue> dictionary);
    public OrderedDictionary(IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey>? comparer);
    public OrderedDictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection);
    public OrderedDictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection, IEqualityComparer<TKey>? comparer);

    public IEqualityComparer<TKey> Comparer { get; }
    public OrderedDictionary<TKey, TValue>.KeyCollection Keys { get; }
    public OrderedDictionary<TKey, TValue>.ValueCollection Values { get; }
    public int Count { get; }
    public TValue this[TKey key] { get; set; }

    public void Add(TKey key, TValue value);
    public void Clear();
    public bool ContainsKey(TKey key);
    public bool ContainsValue(TValue value);
    public KeyValuePair<TKey, TValue> GetAt(int index);
    public OrderedDictionary<TKey, TValue>.Enumerator GetEnumerator();
    public int IndexOf(TKey key);
    public void Insert(int index, TKey key, TValue value);
    public bool Remove(TKey key);
    public bool Remove(TKey key, [MaybeNullWhen(false)] out TValue value);
    public void RemoveAt(int index);
    public void SetAt(int index, TValue value);
    public void SetAt(int index, TKey key, TValue value);
    public void TrimExcess();
    public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TValue value);

    public struct Enumerator : IEnumerator<KeyValuePair<TKey, TValue>>
    {
        public KeyValuePair<TKey, TValue> Current { get; }
        public void Dispose();
        public bool MoveNext();
    }

    public sealed class KeyCollection : IList<TKey>, IReadOnlyList<TKey>, IList
    {
        public int Count { get; }
        public bool Contains(TKey key);
        public void CopyTo(TKey[] array, int arrayIndex);
        public OrderedDictionary<TKey, TValue>.KeyCollection.Enumerator GetEnumerator();

        public struct Enumerator : IEnumerator<TKey>
        {
            public TKey Current { get; }
            public bool MoveNext();
            public void Dispose();
        }
    }

    public sealed class ValueCollection : IList<TValue>, IReadOnlyList<TValue>, IList
    {
        public int Count { get; }
        public void CopyTo(TValue[] array, int arrayIndex);
        public OrderedDictionary<TKey, TValue>.ValueCollection.Enumerator GetEnumerator();

        public struct Enumerator : IEnumerator<TValue>
        {
            public TValue Current { get; }
            public bool MoveNext();
            public void Dispose();
        }
    }
}
```

**Comment by kronic** [comment]
@stephentoub @terrajobst 
Maybe it's worth adding more methods
```csharp
public void Move(int oldIndex, int newIndex);
public void Stort(IComparer<TValue> comparer);
```

**Comment by AndriySvyryd** [comment]
Also consider these methods, that can be more efficient if implemented in the type itself.
```C#
int EnsureCapacity(int capacity)
void TrimExcess(int capacity)
TValue GetOrAdd(TKey key, TValue value)
TValue GetOrAdd(TKey key, Func<TValue> valueFactory)
bool TryAdd(TKey key, TValue value)
```
