### ISSUE TITLE
SelectNonNull extension method

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#24851]
Could we have this in `System.Linq` ?

```C#
public static IEnumerable<V> SelectNonNull<T,V>(this IEnumerable<T> items,Func<T,V> func) where V : class
{
	foreach(var item in items)
	{
		var value = func(item);
		if(value != null)
			yield return value;
	}
}

public static IEnumerable<V> SelectNonNull<T,V>(this IEnumerable<T> items,Func<T,V?> func) where V : struct
{
	foreach(var item in items)
	{
		var value = func(item);
		if(value.HasValue)
			yield return value.Value;
	}
}
```

I don't know what name it should but this extension method is convenient

**Comment by virzak** [comment]
I ran into the same need when converting code base of a project to NRT.

A pattern that keeps appearing in my code is:

```csharp
public IEnumerable<Guid> GetAllGuids1(IEnumerable<SomeClass> instances)
{
    return instances
        .Where(x => x.SomeGuid.HasValue)
        .Select(x => x.SomeGuid!.Value);
}

public class SomeClass
{
    public Guid? SomeGuid { get; set; }
    public string? Name { get; set; }
}
```

Couldn't find anything in the framework which would allow to easily convert from T? to T without the use of null-forgiving operator. Eliminating the need for ! is what makes this combination valuable. @stephentoub

**Comment by stephentoub** [comment]
> Eliminating the need for ! is what makes this combination valuable

I don't think adding new LINQ APIs is the right way to address this. From my perspective, it should be done via language/compiler support.
https://github.com/dotnet/roslyn/issues/39586
https://github.com/dotnet/csharplang/issues/3868
cc: @jcouv

**Comment by eiriktsarpalis** [comment]
This is effectively a duplicate of #30381. Closing this one to focus the conversation.
