### ISSUE TITLE
Test failure: System.Collections.Concurrent.Tests.ConcurrentBagTests/ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#24868]
Opened on behalf of @Sunny-pu

The test `System.Collections.Concurrent.Tests.ConcurrentBagTests/ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)` has failed.

Assert.DoesNotContain() Failure\r
    Found:    0\r
    In value: Int32[] [0]

        Stack Trace:

           at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(Double seconds) in E:\A\_work\400\s\corefx\src\System.Collections.Concurrent\tests\ProducerConsumerCollectionTests.cs:line 912
Build : Master - 20180201.01 (UWP F5 Tests)
Failing configurations:
- Windows.10.Arm64-arm
  - Release

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180201.01/workItem/System.Collections.Concurrent.Tests/analysis/xunit/System.Collections.Concurrent.Tests.ConcurrentBagTests~2FManyConcurrentAddsTakes_ForceContentionWithToArray(seconds:%201)

**Comment by eiriktsarpalis** [comment]
The test hasn't been disabled, and it seems to be passing in recent test history. I'm going to close this issue.
