### ISSUE TITLE
Feature Request: .ToDictionary overload for IEnumerable<KeyValuePair<IKey,IValue>> returning Dictionary<IKey,IValue>

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/runtime#24900]
Often it would be useful to be able to create a Dictionary<IKey, IValue>from an IEnumerable<KeyValuePair<IKey, IValue>>. With that, it would be easier to initialize Dictionaries from LINQ Expressions. Furthermore, it would make the code for initializing Dictionaries far more readable. The Method would be defined as below:
```c#
public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(
     this IEnumerable<KeyValuePair<TKey, TValue>> src)
{
     return src.ToDictionary(keyValuePair => keyValuePair.Key, keyValuePair => keyValuePair.Value);
}
```
or

```c#
public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(
     this IEnumerable<KeyValuePair<TKey, TValue>> src)
{
     return new Dictionary<TKey, TValue>(src);
}
```
(Credit to @benaadams)
[EDIT] Add C# syntax highlighting by @karelz

**Comment by eiriktsarpalis** [comment]
Assuming we wanted to add this, I would also prefer a tuple instead of KeyValuePair in the interest of terseness.

**Comment by Thaina** [comment]
I want to second this and maybe for more benefit convenient, I would like to propose nullable tuple keyvalue

```C#
public static Dictionary<K,V> ToDictionary<T,K,V>(this IEnumerable<(K,V)> source,Func<T,(K,V)?> selectWhere);

////

array.ToDictionary((item) => item != null && item.IsAlive ? (item.UID,item.Value) : null);
```

With the API we could write both select and filter by return null to filter out unwanted value
