### ISSUE TITLE
Add Convert.ToString(sbyte value, int toBase) And Allow _ separator

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#24910]
1. Why there is no
Convert.ToString(sbyte value, int toBase)
Overloaded method?
When I use:
```
sbyte n = -1;
var x = Convert.ToString(n, 2);
Console.WriteLine(x);

```
the output is "1111111111111111" because the ToString casts n to short!
The strange thing is that Convert.ToSByte has an overload for doing the opposite task!
`sbyte n = Convert.ToSByte("11111111", 2);`

But the parser fails to deal with the _ separator:
` sbyte n = Convert.ToSByte("1111_1111", 2);`
I think you should update the binary parser to accept this separator.

Edit:
Maybe Convert class can have a new ToNumSystem(value, base) Method.
It can have overloads to deal with deferent numeric data types, including SByte, BigInteger and Vectorts. Vectors can be converted to array containing  string representations.
May be a new FromNumSystem<T>(string, base) is useful too.

**Comment by ericstj** [comment]
Closing as this API request doesn't have a sponsor and has been stale for over 2 years.
