### ISSUE TITLE
MethodBodyStreamEncoder.AddMethodBody ignores attributes for tiny methods.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#24948]
RelatedTo:https://github.com/dotnet/roslyn/issues/23951

MethodBodyStreamEncoder.AddMethodBody checks if it is possible to emit Tiny method header, and if it otherwise fits in Tiny, InitLocals flag get effectively ignored.

There is a case where we may need Fat format specifically because we want the InitLocals flag.
That happens if a method otherwise meets requirements of a Tiny format, but has `stackalloc` in it. If Tiny is used in such case, the caller will `stackalloc` a piece of nondeterministic garbage.

Overall - it should be up to the caller to decide whether the InitLocals is needed. 
AddMethodBody should ensure that the flag is emitted if asked by the caller.

**Comment by ericstj** [comment]
Moving to 6.0.0

Remaining work is to re-enable these tests.
