### ISSUE TITLE
Add Quaternion.Divide(Quaternion, float)

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#24964]
I noticed that Quaternion.Divide Method has no overload to dived a quaternion by a scalar value, unlike the Multiply method! so I suggest to add it!
I used this:
```
Dim Q1 = New Quaternion(1, -1, 2, -4)
Dim Q2 = New Quaternion(-1, 1, -2, -4) * (1 / Q1.LengthSquared())
```

Edit:
After looking at the Inverse Methode source code, it appears it is the Reciprocal Method but with a confusing name! Inverse in math can mean addative Inverse  or multiplicative inverse. SIMD-enabled types are not consistant with naming conventions of .net. One odd examole is implementing the Length of these types as a method not a property! I expected to find a Quaternion.Reciprocal as there is a Complex.Reciprocal, but found an Inverse method instead. Having a consistant naming convention makes new features easy to learn and thier methods names easy to remember.
Also I think many of static members need to be instance members.

**Comment by stephentoub** [comment]
The original poster of this issue deleted their account and is now a "ghost", so I'm going to close this issue.  Thanks.
