### ISSUE TITLE
Add new overload to System.Reflection.Assembly to load from Stream

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#24985]
## Rationale

Currently we can load an assembly from byte array or by file name:
```c#
        public static Assembly Load(byte[] rawAssembly);
        public static Assembly Load(byte[] rawAssembly, byte[] rawSymbolStore);
        public static Assembly Load(AssemblyName assemblyRef);
        public static Assembly Load(string assemblyString);
        public static Assembly LoadFile(string path);
        public static Assembly LoadFrom(string assemblyFile, byte[] hashValue, Configuration.Assemblies.AssemblyHashAlgorithm hashAlgorithm);
        public static Assembly LoadFrom(string assemblyFile);
```

If we compile dynamically in a memory stream we have to do extra allocations to load the assembly:
```c#
using (var ms = new MemoryStream())
{
    emitResult = compilation.Emit(peStream: ms, options: _emitOptions);
    if (emitResult.Success)
    {
        ms.Flush();
        ms.Seek(0, SeekOrigin.Begin);
        Assembly assembly = Assembly.Load(ms.ToArray());
    }
}
```

### Proposed API

```c#
    // Load the assembly from Stream.    
    public static Assembly Load(Stream assemblyStream);
```

### Update

There is `AssemblyLoadContext.Default.LoadFromStream()` in `System.Reflection.Loader` but its hard to find.

**Comment by GrabYourPitchforks** [comment]
Loading an assembly is very expensive. The extra one-time allocation of converting a `Stream` to a `byte[]` is not going to show up in any realistic performance profile when compared against the other costs in this code path.

**Comment by iSazonov** [comment]
The question was not even performance, but an inconsistent design when we can compile into a stream, but cannot load it directly as possible for a file.
