### ISSUE TITLE
[Feature-Request] N-bit sized int and floating point types

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#25004]
@hamarb123 commented on [Fri Feb 09 2018](https://github.com/dotnet/standard/issues/647)

I propose we should be able to have N-bit sized int and floating point types.
Here is how it could work:

Obviously we already have the following:
- int 1 / uint 1 (bool)
- uint 8 (byte)
- int 8 (sbyte)
- uint 16, 32 and 64 (ushort, uint and ulong)
- int 16, 32 and 64 (short, int and long)
- float 32 (single)
- float 64 (double)

But what about the following:
- (u)int 2 (2 bits)
- (u)int 4 (4 bits)
- (u)int 128 (128 bits)
- (u)int 256 (256 bits)
- (u)int 2^n (2^n bits)
- (float 1 makes no sense but you could still add it)
- float 2 (2 bits)
- float 4 (4 bits)
- float 8 (8 bits)
- float 16 (16 bits)
- float 128 (128 bits)
- float 256 (256 bits)
- float 2^n (2^n bits)

The classes could be called the following:
For integers: `intj` where j is a power of 2 for a j bit integer
For unsigned integers: `uintj` where j is a power of 2 for a j bit unsigned integer
For floats: `floatj` where j is a power of 2 for a j bit float
And there could be special names for floats between `float8` and `float256` ranging from `quarter`, `half`, `single` (already in .NET), `double` (already in .NET), `quadruple`, `octuple`

Why do I need this in my beloved c#?
1. Because it will give you more/less precise floats to use
2. It will give you more integers to use
3. There are no good floating point (bigger than double) libraries out there that do not just use System.Math which reduces it to double precision anyway

Won't this ruin my IDE with millions of different type names?
1. Not if you make a maximum for the types (say 1024) or make it so that the IDE can have the ability to only show you some (say up to 1024) then it will not give you millions of types suggested

**Comment by tannergooding** [comment]
Going to close this as currently unactionable. The issue covers a good number of types and doesn't represent something that we could easily take to API review.

If someone feels strongly about any particular type, please feel free to open a new issue for that type. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.
