### ISSUE TITLE
Add a special Numeric structure or INumeric Interface

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#25058]
_Intrinsic_ numeric types (byte, int, float, ….etc) are structures, so unfortunately, they have no base class that can gather all basic methods and operators! 
So I suggest to add a special Numeric structure that can accept numeric values of any type. It should contain the value and the underling type of it, as Object class does. Numeric structure should have the basic arithmetic and logical operators. Or it can be an interace (say INumeric) that all numeric data types implement. This will not break any existing code.

Usage: 
Numeric structure (or INumeric Inrerface) can be used in generic methods where T is expected to be a numeric type, to carry out the basic arithmetic and logical operators without writing a dozen if statements for each individual numeric type. Objects doesn't have the basic arithmetic and logical operators and have to be converted to numeric types to work with. For example, I tried to do this but failed:

  ```
  public struct Numeric
    {
        public object Value { get; set; }

        public static Numeric operator +(Numeric n1, Numeric n2)
        {
            return (Numeric)(n1.Value + n2.Value);
        }
    }

```
C# refuses n1.Value + n2.Value because it doesn't know how to add objects. Many if statements are needed to deal with different types of n1 and n2, regarding the larger type to use as the output type. This is a hell of code to something that should be easy and direct if there was a general numeric type that can contain any numeric type.

I face the same situation when I use the base Enum class in any method, because Enum can have any numeric type as an underling type!

I saw similar problem in the source code of Vector<T>, where tons of code lines are repeated just to cover all cases of each numeric type!

Note: If you add the numeric type, C# and VB.net should add a new constraint for generic parameters to be numerics.
where T: numeric
this means T can only be of type Numeric or any intrinsic numeric data types.

So, If this Numeric Type or INumeric Interface exists, one can write
```
public static Enum SetFlag(Enum value, Enum flag)
{
var result = (Numeric)value | (Numeric)flag);
return (Enum)result; 
}
```

instead of:
 
```
public static Enum SetFlags(Enum value, Enum flag)
{
   if (Enum.GetUnderlyingType(value.GetType()) == typeof(byte))
      return (Enum)(object)((byte)(object)value | (byte)(object)flag);

   if (Enum.GetUnderlyingType(value.GetType()) == typeof(int))
      return (Enum)(object)((int)(object)value | (int)(object)flag); 
   //
   //
   // etc
}
```

and the same  when writing  generic types that deal with numeric data types only.
This can be extended based on this proposal https://github.com/dotnet/csharplang/issues/1233, I also suggest to add these interfaces:
numeric constraint.
IIntegral: for integer tyoes (byte, sbyte, int, uint, short, ushort, long, ulong)
IFloating: (float, double, decemal)
IValue: (numerics and dates).
ILetiral (Char and string).
IPrimitive (numerics, dates, char, string)

These Interfaces will make writting generics easier. IPerimative can help you 
format or parsing or using + operation depending on where T: IPerimative. 
Also it can be usefull when defining generic lists and dictionaries that can contain different values.  This will make them more specialized than using objects.

**Comment by tannergooding** [comment]
Closing this. As mentioned above we are looking into the correct surface area to expose here as part of the `static abstracts in interfaces` feature the language and runtime are adding.

This is currently being tracked in our dotnet/designs repo and I've added the initial rough draft of the surface area here: https://github.com/dotnet/designs/pull/205

Further discussion or suggestions should happen there and in future PRs that further refine the proposed surface area.
