### ISSUE TITLE
API Proposal: Add PipeReader.ReadAsync overloads to allow waiting for a specific amount of data

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#25063]
Often a protocol knows how much data it is waiting for (TLS frames being one example, size headered binary protocols being another).

Instead of ReadAsync() then you check the header and you see you don't have enough, so you ReadAsync() check if you have enough and continue doing loops until you have a complete frame. If you could do a "ReadAsync(xxxxx)" and it wouldn't return unless there was an error/complete or at least that amount of data was available it would solve extra looping in every downstream protocol

**Proposed API**

```diff
public abstract partial class PipeReader
{
+    public virtual ValueTask<ReadResult> ReadAsync(int minimumBytes, CancellationToken cancellationToken = default);
}
```

/cc @Drawaes

**Comment by bartonjs** [comment]
* Since there's a parameter that should be validated (if negative, throw), it should use the Template Method Pattern (ReadAsync => virtual ReadAsyncCore)
* To enhance discoverability we feel like not being an overload is better: ReadAsync => ReadAtLeastAsync

```C#
namespace System.IO.Pipelines
{
    partial class PipeReader
    {
        public ValueTask<ReadResult> ReadAtLeastAsync(int minimumBytes, CancellationToken cancellationToken = default);
        protected virtual ValueTask<ReadResult> ReadAtLeastAsyncCore(int minimumBytes, CancellationToken cancellationToken);
    }
}
```

@GrabYourPitchforks seems to have had some existential concerns with this.  The shape is approved as long as we don't outright axe the feature.

**Comment by GrabYourPitchforks** [comment]
My concern specifically was with this API being promoted as a way to deal with TLV-structured data. What I absolutely __do not__ want to have happen is for this pattern to become commonplace:

```cs
int payloadLength = await reader.ReadInt32Async();
await reader.ReadAtLeastAsync(payloadLength); // buffer data
// consume buffer once await returns
```

If the untrusted payload contains a TLV header which says "2GB of data follows," then flowing this value as-is to `ReadAtLeastAsync` could result in a denial of service attack against the application.

I don't think this is an existential threat to the API as proposed, since we have lots of APIs which misbehave when given untrusted input. But we _really_ need to be careful with documentation and sample code here. And if we don't think docs are sufficient then we should consider placing restrictions on how large a number this API is willing to accept by default.

**Comment by danmoseley** [comment]
If we want to bound the size (4K or something?), the first release is the time to do it. I see length prefixed values were even called out in the top proposal as a scenario.

**Comment by davidfowl** [comment]
We don't need to bound anything, the nice thing about pipelines is that it'll give you nice split buffers up by without destroying the heap. Now we can talk about the fact that memory is being bloated but that's not a concern here, let the upper layers deal with maximum message sizes before calling this API. It's what all sterilizers of this form do already.

**Comment by GrabYourPitchforks** [comment]
> Now we can talk about the fact that memory is being bloated but that's not a concern here

That was my specific concern. Ultimately it doesn't matter whether the API allocates a single 100MB buffer or 10,000 x 10KB buffers. That's an implementation detail. The problem fundamentally is that we don't want the untrusted remote endpoint to coerce the application into doing significantly more work / consuming significantly more resources than the application intended.

> let the upper layers deal with maximum message sizes before calling this API

If we put a blurb like this in the doc and sample code, I think that would address the concerns. Thanks!

**Comment by davidfowl** [comment]
> That was my specific concern. Ultimately it doesn't matter whether the API allocates a single 100MB buffer or 10,000 x 10KB buffers. That's an implementation detail. The problem fundamentally is that we don't want the untrusted remote endpoint to coerce the application into doing significantly more work / consuming significantly more resources than the application intended.

It should be one of your concerns though because there are 2 common "issues" here. Code like this:

```C#
int payloadLength = await stream.ReadInt32Async();
var buffer = new byte[payloadLength]; // Untrusted length, did the client even send this much data? Why are we assuming they did before actually reading it
await stream.ReadAsync(buffer); // read the data
```

This pattern is one of the traps this API helps you avoid.

> If we put a blurb like this in the doc and sample code, I think that would address the concerns. Thanks!

That's absolutely reasonable since it's already a concern today but in another scenario (since the pipe helps you buffer).

**Comment by davidfowl** [comment]
I notice we didn't define the behavior of ReadAtLeast(0). I think it should signify, wait until you have any data (since we have TryRead for synchronous attempts).

**Comment by tmds** [comment]
> let the upper layers deal with maximum message sizes before calling this API

When using this API it's important to have a timeout in case `ReadAtLeast` can't complete in a reasonable time.
Maybe that's also something upper layers will handle, and not something a user should do manually using the `CancellationToken`? It would be good to have something about it in the docs too.

**Comment by davidfowl** [comment]
How is that different from any other  async API? That is what cancellation is for

**Comment by tmds** [comment]
Some timeouts happen without the use of a `CancellationToken`.

It depends on the API how important the timeout case is. For this API (and related) it's important.

**Comment by davidfowl** [comment]
What API times out without a token?

**Comment by tmds** [comment]
For the `PipeWriter`, `KestrelServerLimits.MinResponseDataRate` controls a timeout that works without the user specifying a `CancellationToken`.

**Comment by tmds** [comment]
I'm fine if it's done through a `CancellationToken` for `ReadAtLeast`. My request is to mention how timeouts should be handled in the docs/example.

**Comment by davidfowl** [comment]
Those aren't APIs in the same vein as this so not comparable. Timeouts are handled via cancellation for async APIs.
