### ISSUE TITLE
Consider adding Span<char> overloads to TextEncoder

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#25091]
Seems like these were missed in the Spanification of the BCL. https://github.com/dotnet/corefx/blob/01fa16ffd618846a913cad719269c8bb441ceb28/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/TextEncoder.cs

/cc @stephentoub @KrzysztofCwalina @GrabYourPitchforks

**Comment by danmosemsft** [comment]
@GrabYourPitchforks I have marked this future based on above comment, seems like a migration glitch?
