### ISSUE TITLE
Translation vector of Transformation matrix works incorrect when PageUnit is Point.

### ISSUE THREAD

**Issue by RusKnyaz** [dotnet/runtime#25122]
The issue is observed on linux platform, but not observed on the Windows. Its looks like graphics.PageUnits does not taken into account on applying of translation vector to the graphical objects.

1. Run the following code:

```c#
    var bmp = new Bitmap(200, 50);
    using (var graphics = Graphics.FromImage(bmp))
    using(var font = new Font("Arial", 10))
    using(var brush = new SolidBrush(Color.Black))
    using(var bgBrush = new SolidBrush(Color.White))
    {
            //Fill background
            graphics.PageUnit = GraphicsUnit.Pixel;
            graphics.FillRectangle(bgBrush, 0, 0, 200, 100);
                
            // Draw text with 10 pixel offset
            graphics.PageUnit = GraphicsUnit.Pixel;
            graphics.Transform = new Matrix(1,0,0,1,10,0);
            graphics.DrawString("|<- 10 pixels offset", font, brush, 0,0);
                
            // Draw text with 10 points offset
            graphics.PageUnit = GraphicsUnit.Point;
            graphics.DrawString("|<- 10 points offset", font, brush, 0,10);
                
            Console.WriteLine("Actual Dpi is: " + graphics.DpiX);//96
        }
    bmp.Save("units.png", ImageFormat.Png);
}
```
2. Open generated png file

Observed: both line of the text have the same offset - 10px (see attached units_linux.png)
![units_linux](https://user-images.githubusercontent.com/16118282/36460187-e2537272-16e9-11e8-98dd-56b8600c4d8d.png)

Expected: Second line should have 10 points offset (or ~13px for 96 dpi) (see attached units_win.png)
![units_win](https://user-images.githubusercontent.com/16118282/36460193-e6d3a786-16e9-11e8-8ada-047c220fa28b.png)

**Comment by ZeroRyogi** [comment]
With:

- dotnet 6.0.100-rc.2.21505.57
- libgdiplus-5.6.1-3

I can't get to reproduce this issue. On my Linux box I'm getting the following result:

![units](https://user-images.githubusercontent.com/560074/141598877-47320722-de35-43f9-89a2-ed93bf1ab0f2.png)

**Comment by safern** [comment]
Thanks @ZeroRyogi. Will close the issue.
