### ISSUE TITLE
Graphics.MeasureString wrong result in case of the text broken into lines

### ISSUE THREAD

**Issue by RusKnyaz** [dotnet/runtime#25124]
charsFilled output parameter value is wrong in case of text broken into lines. The issue is reproducible under linux, but not reproducible under windows.

Run the following code:
```c#
    var bmp = new Bitmap(200, 50);
    using (var graphics = Graphics.FromImage(bmp))
    using(var font = new Font("Arial", 10))
    {
        graphics.MeasureString("H E L L O", font, new SizeF(20, float.MaxValue),
                    StringFormat.GenericTypographic, out var chars, out var lines);
                
        Console.WriteLine($"Chars fitted: {chars}");
        Console.WriteLine($"Lines fitted: {lines}");
    }
```

Observed: console output is
Chars fitted: 3
Lines fitted: 4

Expected: console output is 
Chars fitted: 9
Lines fitted: 4

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
