### ISSUE TITLE
Requesting a net35 target for the S.R.Metadata package

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#25198]
Projects like https://github.com/nunit/nunit-console (including the engine shared by the console and adapter) and https://github.com/OpenCover/opencover allow users to execute their assemblies on desktop CLR v2 and therefore cannot target net40 or greater.

Without a net35 target, or maintaining such a port, we can't move away from Mono.Cecil. Mono.Cecil has a major drawback for projects that use rely on it, crashing when reading portable PDB information. It hasn't been updated in a while. S.R.Metadata is also better-designed for efficient low-level reading.

This would make it desirable to publish a net35 build of S.C.Immutable. @sharwell has one at https://github.com/tunnelvisionlabs/dotnet-collections, though adding a net35 target to the S.C.Immutable package would also be welcome for even more projects than stated above.

It looks like this would make the difference for me between days and months of work, so I'm happy to contribute here!

**Comment by jkotas** [comment]
We have no plans to add any net35 targets in this repo.
