### ISSUE TITLE
Build warnings when targeting System.* nuget packages from projects targeting .NET 4.7.1

### ISSUE THREAD

**Issue by camp-007** [dotnet/runtime#25257]
I have a problem with a very simple repro:

1) Using VS 2017 15.5.7 create a new project using the template "Console App (.NET Framework) targeting .net 4.7.1
2) Add a nuget package reference for the package "System.Net.Http" v4.3.3.  Use the 'packages.config' package manager format when prompted.  Several other System.* nuget package dependencies are also added.
3) Compile the project.  No build errors or warnings.
4) Close and re-open the solution
5) Compile the project.  **Several build warnings of "The referenced component 'System.IO' could not be found" appear**.  Many of the references in the solution explorer appear with an exclamation mark.  The project seems to build successfully, but the warnings cause concern that something is wrong.

These build warnings don't seem like they should be expected or desirable.  Is there something obvious I'm doing wrong or misunderstanding?

I do not get these build warnings if I follow all the above steps but instead target .NET 4.6.1.

You may ask why I'd want to reference System.* nuget packages when I'm targeting .NET 4.7.1.  Instead I should use the 'in box' System.* references from the .net framework.  My real problem is in trying to reference the nuget package ['IdentityModel' v3.3.1](https://www.nuget.org/packages/IdentityModel/).  This brings in a dependency on the System.Net.Http nuget package (not the built in framework reference) and thus, I get these warnings.  My repro is just the basic scenario of directly referencing the System.Net.Http nuget package, but in my case I want to use IdentityModel and don't have any choice or control over the dependencies.

IdentityModel is part of the popular "Identity Server" OSS product, so I would expect my scenario to be very natural/mainstream.

**Comment by ViktorHofer** [comment]
We aren't actively building most of these System packages anymore. I tend towards closing this. Feel free to reopen if you disagree.
