### ISSUE TITLE
Provide a default linux friendly installer

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/runtime#2530]
Moving from https://github.com/dotnet/cli/issues/3714 on behalf of @gochev.

CLI's ability to provide a cross-linux-distro installer depends on a matching Shared Framework, so putting the issue in the right repo.

----

Currently you have provided downloads for 7-8 linux distributions, however there are 1000 of linux distros out there.

Please provide a unix friendly installation method from source. This way distributions like Arch, Gentoo, Slackware and other non deb,rpm based can use dotnet core.
## Expected  behavior

`wget http://.....source.tar.gz`
`./configure` - should show you if some dependancy is missing 
`make` - should build it if configure was successful
`make install` - should install it on the right folders and should add dotnetcore and other commands in /usr/bin or similar

Also when distribute source or binary always include an md5 checksum of the file.

**Comment by NikolaMilosavljevic** [comment]
Source-build is available publicly. We also provide Snap and native installers.
