### ISSUE TITLE
File.ReadAllTextAsync not behaving asynchronously when called on inaccessible network files

### ISSUE THREAD

**Issue by cjwainwright** [dotnet/runtime#25314]
When accessing a file on a network share that for some reason cannot be accessed (e.g. server not existent), `File.ReadAllTextAsync` appears to block, rather than running asynchronously, until the file request fails. This can be reproduced with the following console app:

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ReadAllTextAsync
{
    class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Beginning");

            int count = 20;
            var files = Enumerable.Range(0, count).Select(i => $@"\\server_{i}\file.txt").ToList();
            var tasks = new List<Task>();

            foreach (string file in files)
            {
                tasks.Add(_ReadFile(file));
            }

            Console.WriteLine("Waiting...");

            Task.WhenAll(tasks).Wait();

            Console.WriteLine("Ending");
        }

        private static async Task _ReadFile(string file)
        {
            try
            {
                // await Task.Delay(1); // Uncomment this line allows calls to execute in parallel
                string text = await File.ReadAllTextAsync(file);
            }
            catch
            {
                Console.WriteLine($"Error reading file: {file}");
            }
        }
    }
}
```
The result of running the above code is a regular stream of (the expected) "Error reading file" messages but they come in slowly one after the other.

When uncommenting the `await Task.Delay(1)` line, the messages all come in nearly simulataneously. I would have expected this behaviour without this line.

I believe this is to do with the behaviour of the `new FileStream` object in https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.IO.FileSystem/src/System/IO/File.cs

```csharp
        private static StreamReader AsyncStreamReader(string path, Encoding encoding)
        {
            FileStream stream = new FileStream(
                path, FileMode.Open, FileAccess.Read, FileShare.Read, DefaultBufferSize,
                FileOptions.Asynchronous | FileOptions.SequentialScan);

            return new StreamReader(stream, encoding, detectEncodingFromByteOrderMarks: true);
        }
```
which is called before any code is awaited.

**Comment by lostmsu** [comment]
Just wasted >1h debugging my app only to discover this.

Guys, this is a popular method, and this issue violates the most basic expectation about it.

**Comment by adamsitnik** [comment]
> Guys, this is a popular method, and this issue violates the most basic expectation about it. The whole point of using it is to ensure the calling thread is not blocked.

The problem here is that none of the OSes that we support provides a way to **asynchronously open** a file. Reads and writes can be async, but not the opening.

https://stackoverflow.com/questions/41300873/how-to-open-a-file-in-windows-asynchronously

**Comment by lostmsu** [comment]
@adamsitnik is there any reason this can't be done by queuing a task on the default threadpool?

**Comment by stephentoub** [comment]
> @adamsitnik is there any reason this can't be done by queuing a task on the default threadpool?

You can do the same:
```C#
Task.Run(() => File.ReadAllTextAsync(...))
```

As a general policy we only add asynchronous APIs when they can actually be implemented with asynchronous I/O / using other asynchronous implementations.

https://devblogs.microsoft.com/pfxteam/should-i-expose-asynchronous-wrappers-for-synchronous-methods/

**Comment by lostmsu** [comment]
I don't see how the logic in this post applies to this case. Nobody is suggesting wrapping a synchronous `FileStream` constructor in `FileStream.CreateAsync`. This is a different case, as `ReadAllTextAsync` is already asynchronous method, and it breaks the async expectation with the current implementation.

**Comment by stephentoub** [comment]
>  and it breaks the async expectation with the current implementation

It does what it can do with async I/O. It doesn't artificially do any async-over-sync work. The point was we generally don't do that.

**Comment by Jozkee** [comment]
Closing as this seems to be non-actionable.
