### ISSUE TITLE
Investigate generating matching strings for test regexes and adding to testbed

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#25372]
The regexes we may port in https://github.com/dotnet/corefx/issues/27618 will exercise our parser but not our runner.

Experiment with using REX (https://www.microsoft.com/en-us/research/project/rex-regular-expression-exploration/) to generate interesting strings for each of those interesting patterns. Then preserve some of those strings in the tests - so we have a large body of new positive tests for regex matching.

We could also generate negative tests, for example by making small changes to the positive matching strings until they did not match, and preserving those also. Those should continue to not-match.

@CyrusNajmabadi @ViktorHofer @maryamariyan

**Comment by ViktorHofer** [comment]
@stephentoub @danmosemsft is this issue still valid? I remember that we ported over a bunch of additional test data recently. Asking as I know some people that might be interested in help out.

**Comment by danmosemsft** [comment]
I think it's probably fine to close since we don't know there's any tool that would generate useful patterns in a reasonably amount of time and nobody seems interested in trying .
https://github.com/dotnet/runtime/issues/43314 demonstrates theres room for better coverage though.

**Comment by danmosemsft** [comment]
Oh, I misread - of someone is interested in trying, that would be great.

**Comment by stephentoub** [comment]
We have a test doing this now, utilizing capabilities of the NonBacktracking implementation to also generate matching and non-matching inputs for arbitrary expressions.  Right now it's only being used in a limited capacity, but we can expand it to a much larger number of expressions, or at least a more comprehensive set in terms of the constructs exercised.
https://github.com/dotnet/runtime/blob/25237fab429814b57268bc84e40e44a3c7733490/src/libraries/System.Text.RegularExpressions/tests/RegexExperiment.cs#L437-L480

**Comment by GSPP** [comment]
If IntelliTest gets ported to .NET Core, it also can be used to generate regular expressions. IntelliTest uses an SMT solver to create inputs to exercise all possible code paths. It should be able to drill into the regex implementation just fine. It can exercise parsing and execution.

Making IntelliTest available for .NET Core is an open issue: https://developercommunity.visualstudio.com/t/add-intellitest-support-for-net-corestandard/359250

Fans of IntelliTest should vote and possibly comment on that issue to make their interest known. It's a remarkable technology.

**Comment by CyrusNajmabadi** [comment]
Please let me know if that happens.  I'd like to port those tests to roslyn.  or, if you want to have your system generate roslyn parsing tests, that would be great!
