### ISSUE TITLE
Getting error on windows => System.PlatformNotSupportedException: 'System.IO.Ports is currently only supported on Windows.'

### ISSUE THREAD

**Issue by harvinders** [dotnet/runtime#25375]
I have a .net standard 2.0 dll (Drivers.CommunicationLocal) which is referencing SerialPort class. When I try to use this from a .Net 4.6.1 console app or a xUnit (.net core 2.0) on windows 10, I get the following exception. Using it from UWP app works fine.

> System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
>    at System.IO.Ports.SerialPort..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits)
>    at Drivers.CommunicationLocal.CommunicationLayerSerialPortLocal..ctor(SettingSerialPortLocal settings) in C:\Users\abc\Documents\Visual Studio 2017\Projects\experiment\senna\src\Drivers.CommunicationLocal\CommunicationLayerSerialPortLocal.cs:line 24

 I am using nuget package `System.IO.Ports`.

**Comment by JonasGoldt** [comment]
Maybe to add to this issue, we have a smiliar problem in our project and I tried to boil it down into this simple repo https://github.com/JonasGoldt/PortsPackageProblem
There are two projects, both targeting dotnet core 3.1. One class lib and one test. The test references the class lib. 

The problem occurs with the library reference "Test"->"Library". When running the test, it loads the System.IO.Ports directly from the output folder, instead of the correct runtimes/win... version.

The workaround mentioned by @danmosemsft works, but we have more complicated cases, e.g where we load unknown libs at runtime. 

For now, we copy the correct Ports assembly into the output folder ourselves.

**Comment by markusschweitzer** [comment]
Still persists in v5

**Comment by JonasGoldt** [comment]
I switched my minimal repo (https://github.com/JonasGoldt/PortsPackageProblem) to .NET5 and System.IO.Ports 5.0.0 and it seems to be fixed.

**Comment by JonasGoldt** [comment]
Sorry, forget my previous comment, it is still not working. I just made a mistake. 

I "fixed" my repo and switched to System.IO.Ports 5.0.1, the test still fails:
https://github.com/JonasGoldt/PortsPackageProblem/runs/2278155935

**Comment by danmoseley** [comment]
Adding untriaged so the crew sees this update.

**Comment by djanri** [comment]
I've stuck with this issue in my WPF project after migrating from .netframework to .NET 6. My library and main projects have TargetFramework as "net6.0-windows". Installing package System.IO.Ports 6.0.0 does not fix the issue. Only copying dll from runtime "net6.0" fixes it.

**Comment by JanJorgensen** [comment]
I also have this problem since I migrated to .NET5 from .NET Framework 4x.
In my project I have addon assemblies loaded with reflection, and that breaks the addon that uses System.IO.Ports.dll.
As a temporary fix I have added the addon project directly as a reference from the WPF and console applications in the project, and that's not the right solution.
I have created a test project [here on github](https://github.com/JanJorgensen/Net5AddonLoadProblemDemo).
The fix from @djanri does not work for me, maybe because I haven't done the procedure described by @joperezr, because I can see that the assembly is in runtimes\win\lib\netstandard2.0 !
I can see that @adamsitnik pushed this issue to 7.0.0, so I guess there's no solution anytime soon :-(

**Comment by Juniorsnet** [comment]
> I've stuck with this issue in my WPF project after migrating from .netframework to .NET 6. My library and main projects have TargetFramework as "net6.0-windows". Installing package System.IO.Ports 6.0.0 does not fix the issue. Only copying dll from runtime "net6.0" fixes it.
> 
> For automation I added next code to the .csproj file:
> 
> ```
> <Target Name="PostBuild" AfterTargets="PostBuildEvent">
>    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
>      <Output TaskParameter="Assemblies" ItemName="CurrentAssembly" />
>    </GetAssemblyIdentity>
>    <Exec Command="xcopy /F /Y /E $(TargetDir)\\runtimes\\win\\lib\\net6.0\\ $(TargetDir)\\" />
>  </Target>
> ```

I have a serialport project:
On Ubuntu 18.04, dotnet 6.0.200, System.IO.Ports 6.0.0, works OK
On Manjaro, dotnet 6.0.102, System.IO.Ports 6.0.0, Error "only support on windows"
The package System.IO.Ports was installer vía nuget (dotnet add package)
On Manajaro, the @djanri suggestion works OK.

**Comment by djanri** [comment]
> I also have this problem since I migrated to .NET5 from .NET Framework 4x. In my project I have addon assemblies loaded with reflection, and that breaks the addon that uses System.IO.Ports.dll. As a temporary fix I have added the addon project directly as a reference from the WPF and console applications in the project, and that's not the right solution. I have created a test project [here on github](https://github.com/JanJorgensen/Net5AddonLoadProblemDemo). The fix from @djanri does not work for me, maybe because I haven't done the procedure described by @joperezr, because I can see that the assembly is in runtimes\win\lib\netstandard2.0 ! I can see that @adamsitnik pushed this issue to 7.0.0, so I guess there's no solution anytime soon :-(

@JanJorgensen
Please look at [fork on github](https://github.com/djanri/Net5AddonLoadProblemDemo). In the [TheApp.csproj](https://github.com/djanri/Net5AddonLoadProblemDemo/blob/master/TheApp/TheApp.csproj) file you could find postbuild event which fixes you issue.

**Comment by JanJorgensen** [comment]
> @JanJorgensen Please look at [fork on github](https://github.com/djanri/Net5AddonLoadProblemDemo). In the [TheApp.csproj](https://github.com/djanri/Net5AddonLoadProblemDemo/blob/master/TheApp/TheApp.csproj) file you could find postbuild event which fixes you issue.

@djanri 
Thanks for your tip, but I don't have a "runtimes" folder in the target dir. In my case the target type is a class library. I'm not an expert in the build- and deploy-stuff, but I can see that there's a difference from building a class library and an executable. For executable projects, it works fine, but for class libraries loaded by reflection it doesn't.

**Comment by Jozkee** [comment]
> The package isn't correctly authored, my guess here is that the way that net461 project is consuming the package is via packages.config which won't produce an assets file so it's just bringing the same implementation picked by the netstandard assembly. It would really help if we could get a binlog to confirm my suspicions.

Could anyone here facing the issue assist with the binlog @joperezr is asking for?

**Comment by Juniorsnet** [comment]
> > The package isn't correctly authored, my guess here is that the way that net461 project is consuming the package is via packages.config which won't produce an assets file so it's just bringing the same implementation picked by the netstandard assembly. It would really help if we could get a binlog to confirm my suspicions.
> 
> Could anyone here facing the issue assist with the binlog @joperezr is asking for? https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md#creating-a-binary-log-during-a-build

Here is my binlog.
I testing more and the version of .net maybe the problem.
On manjaro I remove the 6.0.0.102 from packages.
I install manually the 6.0.0.202 from dotnet-install.sh
Now the project runs.
The function SerialPort.GetPortNames() returns nothing but at least not crash with System.PlatformNotSupportedException
What is the diference between 6.0.0.1xx vs 6.0.0.2xx?
[msbuild.binlog.gz](https://github.com/dotnet/runtime/files/8474394/msbuild.binlog.gz)
