### ISSUE TITLE
System.Net.Http not the same types for .Net461 when using System.Threading.Tasks.Extensions

### ISSUE THREAD

**Issue by rhyous** [dotnet/runtime#25385]
Visual Studio: 2017
Project: .Net4.6.1
Package:   `<package id="System.Threading.Tasks.Extensions" version="4.4.0" targetFramework="net461" />`

### Problem
.NET 4.6.1 doesn't see the System.Net.Http as the same types. I get type exceptions or missing method exceptions when trying to call code from System.Net.Http namespace. 

It seems to fail in many uses of the System.Net.Http namespace.
Once particular example, I have an IHttpClient interface and an HttpClientWrapper class to wrap HttpClient and allow for unit test. My unit tests don't work.

### Workaround

The csproj is pointing at the Netstandard2.0 version of the dll, which must have some bug that makes the System.Net stuff look like they are different types.

```xml
    <Reference Include="System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\..\packages\System.Threading.Tasks.Extensions.4.4.0\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
```

Manually edit the project. Change it to point to the portable-net45+win8+wp8+wpa81.

```xml
    <Reference Include="System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\..\packages\System.Threading.Tasks.Extensions.4.4.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
```

### Expectation
I shouldn't have to manually edit my project every time I update System.Threading.Tasks.Extensions in a NuGet package.

I expect referenced dlls to work with .Net461. 

### Issues
1. Why does netstandard2.0 not work? Why does it thinks the types are different? I have no idea what the cause of this is or how long it would take to fix.
2. Why does the NuGet package install choose netstandard2.0 over portable-net45+win8+wp8+wpa81 when dlls in the netstandard2.0 don't work and dlls int the portable-net45+win8+wp8+wpa81 do work? My guess is precedence or preference. NuGet is coded to prefer netstandard2.0 dlls over dlls in portable-net45+win8+wp8+wpa81. Is that precedence correct? Probably.
3. Since System.Threading.Tasks.Extensions dlls in the netstandard2.0 folder of the NuGet package do not work, why does the NuGet package not have a net45, net461, or such folder that will take precedence of netstandard2.0? Adding a folder for Net461 with dlls that work takes a few minutes. 

So until the first issue is fixed, can we get an updated NuGet package that properly points net461 projects to working dll?

**Comment by ViktorHofer** [comment]
Closing as there are workarounds available:
- Upgrade to net472 or later
- Enable binding redirects and use the PackageReference RestoreStyle.
