### ISSUE TITLE
API Proposal: Helper to get ReadOnlySpan<char> from string with terminator

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#25444]
In some cases we want null terminated spans of char (interop for example). There isn't a convenient helper to get a span from a string with the terminator included.

``` diff
namespace System
{
    public static partial class MemoryExtensions
    {
        public static ReadOnlySpan<char> AsSpan(this string text);
+       public static ReadOnlySpan<char> AsSpanWithTerminator(this string text); 
    }
}
```

This is useful when you want to take a ReadOnlySpan<char> as a parameter that you then need to pass to something (notably a native API) that expects a null terminated string. We can easily validate that we have a null and not have to copy.

``` C#
public static void Foo(ReadOnlySpan<char> bar)
{
    if (bar.Length > 0 && bar[bar.Length - 1] == '\0')
    {
        NativeFoo(ref MemoryMarshal.GetReference(path));
    }
    else
    {
        // make a copy, add a null, and call NativeFoo()
    }
}
```

** Notes **

- Perhaps this should live in `MemoryMarshal` as it is a little more advanced? It isn't a terribly difficult concept though.
- Should also return default if passed null for string.

cc: @KrzysztofCwalina, @terrajobst, @ahsonkhan, @jkotas

**Comment by jkotas** [comment]
dotnet/runtime uses Span a lot. There do not seem to be any cases that would benefit from this API in dotnet/runtime libraries. This API is unlikely to be useful.
