### ISSUE TITLE
Consider adding a Regex.Split options overload similar to StringSplitOptions

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#25453]
```csharp
namespace System.Text.RegularExpressions
{
    public class Regex
    {
        public string[] Split(string input, int count, int startat, RegexSplitOptions options);
    }

    public enum RegexSplitOptions
    {
        None,
        IgnoreEmptyEntries
    }
}
```

## Rationale
In cases where you want to split by a specified pattern which is a capturing group itself i.e. (\d+) you will get empty entries back for the following inputs:

| Input | Output | Desired |
| ------ | -------- | ---------- |
| ABC123456DEF | "ABC", "123456", "DEF" | "ABC", "123456", "DEF" |
| 123456 | "", "123456", "" | "123456" |
| ABC123456 | "ABC", "123456", "", | "ABC", "123456" |
| 123456DEF | "", "123456", "DEF" | "123456", "DEF" |

Also see examples in https://msdn.microsoft.com/en-us/library/ze12yx1d(v=vs.110).aspx

**Comment by danmosemsft** [comment]
This has sat for a while, if customer scenarios emerge we can reconsider.
