### ISSUE TITLE
Proposal: ImmutableArray.UnsafeFreeze<T>(T[])

### ISSUE THREAD

**Issue by benjamin-hodgson** [dotnet/runtime#25461]
Use case: efficiently creating an `ImmutableArray` with a fixed (>4) number of elements.

Presently if you need to create an `ImmutableArray<T>` with a known collection of elements, the most efficient way to do so is to create an `ImmutableArray<T>.Builder`, set its `Capacity` to allocate an array of the correct size, fill the `Builder` with repeated calls to `Add`, and then use `MoveToImmutable` to create the `ImmutableArray`. (This strategy can be marginally improved by storing a cached `Builder` in a `ThreadLocal`.)

For element counts smaller than 4, there are [overloads of `ImmutableArray.Create`](https://github.com/dotnet/corefx/blob/99d4271b02b4b0408fa0879651d964bebd3c5cf1/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs#L85) which are implemented by creating an array and then immediately turning it into an `ImmutableArray`, but for more than 4 `Create` takes a `params[]` and [copies it](https://github.com/dotnet/corefx/blob/99d4271b02b4b0408fa0879651d964bebd3c5cf1/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs#L157) into an `ImmutableArray`. There is no way to create an array directly, fill it, and freeze it into an `ImmutableArray` without copying while pinky-promising never to mutate the original array again.

I set up a microbenchmark (see below) which uses codegen to call `ImmutableArray<T>`'s private `T[]` constructor, and it's around 4-5 times faster for an array of 1000 `long`s. I found that a library of mine was spending a reasonable chunk of its time creating `ImmutableArray`s, and [implementing this hack](https://github.com/benjamin-hodgson/Eighty/commit/92a84c826b00a61158a5d17a50e88fb8c925c37a) led to a global ~10% speedup in my end-to-end benchmarks. I'm not entirely happy about depending upon private implementation details like that though.

I propose adding a officially-supported static method to freeze an array into an `ImmutableArray` without copying it. I suggest calling it `UnsafeFreeze` to emphasise the fact that this method is risky: to use it correctly you have to make sure never to mutate the array that you passed in. (This name may be confusing given that it doesn't have anything to do with C#'s `unsafe`; I'm open to alternative suggestions.)

```csharp
public static class ImmutableArray
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    // might wanna add [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ImmutableArray<T> UnsafeFreeze<T>(T[] array)
        => new ImmutableArray<T>(array);
}
```

There may be a use case for a similar `UnsafeThaw` method which turns an `ImmutableArray<T>` into a `T[]` without copying, but I can't think of one right now.

NB. There is precedent in the BCL for APIs which ask you to relinquish ownership of the argument. `ArrayPool.Return` requires you not to continue using the array you returned because it is liable to get handed out to a future caller of `Rent`.

----------

Here's the code for the microbenchmark I mentioned above (using BenchmarkDotNet):

```csharp
public class Bench
{
    static readonly ThreadLocal<ImmutableArray<long>.Builder> _cachedBuilder = new ThreadLocal<ImmutableArray<long>.Builder>(ImmutableArray.CreateBuilder<long>);
    static readonly Func<long[], ImmutableArray<long>> _unsafeFreeze = GetUnsafeFreeze<long>();

    [Benchmark(Baseline = true)]
    public void CachedBuilder()
    {
        var builder = _cachedBuilder.Value;
        builder.Capacity = 1000;
        for (long i = 0; i < builder.Capacity; i++)
        {
            builder.Add(i);
        }
        builder.MoveToImmutable();
    }
    [Benchmark]
    public void UnsafeFreeze()
    {
        var array = new long[1000];
        for (long i = 0; i < array.Length; i++)
        {
            array[i] = i;
        }
        _unsafeFreeze(array);
    }

    static Func<T[], ImmutableArray<T>> GetUnsafeFreeze<T>()
    {
        var ctor = typeof(ImmutableArray<T>)
            .GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance)
            .Single(c => c.GetParameters().Count() == 1 && c.GetParameters().Single().ParameterType.Equals(typeof(T[])));
        var param = Expression.Parameter(typeof(T[]));
        var body = Expression.New(ctor, param);
        var func = Expression.Lambda<Func<T[], ImmutableArray<T>>>(body, param);
        return func.Compile();
    }
}
```

And the results:
```
        Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |
-------------- |---------:|----------:|----------:|-------:|---------:|
 CachedBuilder | 8.439 us | 0.1667 us | 0.4089 us |   1.00 |     0.00 |
  UnsafeFreeze | 1.944 us | 0.0399 us | 0.1169 us |   0.23 |     0.02 |
```

**Comment by Sergio0694** [comment]
I just stumbled upon this as well, and strongly agree with @jkotas here:

> "I think it is a much worse situation than having officially santioned unsafe interop methods. Maybe we should reconsider?"

> "The question is whether we should have a API to codify the unsafe pattern instead of telling everybody to depend on internal implementation details."

Not having an API for this forces library authors to either take an extra copy **when they can guarantee the array doesn't have other owners that could mutate it**, or just use the `Unsafe.As` hack, which is not ideal for several reasons. I get that the layout of `ImmutableArray<T>` is exactly just a single `T[]` array by design (for perf, etc.) but still relying on an internal implementation detail like this just doesn't feel right, especially when we already have other safe APIs to do this kind of things in the BCL (eg. the various `MemoryMarshal` extensions that Jan called out).

To add context, in my case I'm getting some bytecode from native APIs and wanted to return it as an `ImmutableArray<byte>`.

Consider the following code (ignore the details):

```csharp
using ComPtr<IDxcBlob> dxcBlobBytecode = ShaderCompiler.Instance.CompileShader(hlslSource.AsSpan());

byte* buffer = (byte*)dxcBlobBytecode.Get()->GetBufferPointer();
int length = checked((int)dxcBlobBytecode.Get()->GetBufferSize());

byte[] array = new ReadOnlySpan<byte>(buffer, length).ToArray();

// This is fine, as I can guarantee I'm the sole owner of the array.
// Why should we waste a second allocaiton/copy of the whole buffer here?
return Unsafe.As<byte[], ImmutableArray<byte>>(ref array);
```

I reckon this is a case where having a proper `ImmutableArray.UnsafeFreeze<T>(T[])` (or whatever name) API would be very nice. I would be perfectly fine with it being in some other more obscure class/namespace as well, if we didn't want to have it be on `ImmutableArray` directly. I do think there's plenty of good reasons for introducing it though.

**Comment by krwq** [comment]
@Sergio0694 @svick's code seem to be working acceptably fast without any hacks (https://github.com/dotnet/runtime/issues/25461#issuecomment-373950250) - it would be better if capacity version also worked equally fast but IMO it's better to spend time on making this optimization work than adding new API. byte array is an implementation detail and it should not be exposed as public API. Obscuring API it doesn't change anything here.

**Comment by svick** [comment]
@Sergio0694 I think the approved `Span`-based additions to the `ImmutableArray` API (https://github.com/dotnet/runtime/issues/22928#issuecomment-855154372) will work well for that use case:

```c#
var span = new ReadOnlySpan<byte>(buffer, length);

return ImmutableArray.Create(span);
```

**Comment by Sergio0694** [comment]
Hey @krwq, thank you for chiming in! @svick's code will not work in my scenario, as I'm working with a native buffer, so the best I can do is getting a `ReadOnlySpan<byte>` from it, which unfortunately won't work with the builder approach as there currently doesn't seem to be an overload of `AddRange` taking a `ReadOnlySpan<T>`. If that was added, then I guess I could just switch to that, if the difference is just about 20% (which arguably is still not negligible, but that's another topic).

To recap:

```csharp
using ComPtr<IDxcBlob> dxcBlobBytecode = ShaderCompiler.Instance.CompileShader(hlslSource.AsSpan());

byte* buffer = (byte*)dxcBlobBytecode.Get()->GetBufferPointer();
int length = checked((int)dxcBlobBytecode.Get()->GetBufferSize());

ImmutableArray<byte>.Builder builder = ImmutableArray.CreateBuilder<byte>(length);

builder.AddRange(new ReadOnlySpan<byte>(buffer, length)); // This API is missing (also, why?)

ImmutableArray<byte> bytecode = builder.MoveToImmutable();
```

Should we open a separate proposal for that? I don't really understand why a `ReadOnlySpan<T>` overload isn't there already, so it seems to me that would be a nice addition regardless, unless there was a specific reason why that wasn't added?

> "byte array is an implementation detail and it should not be exposed as public API"

I have to say, the current approach of considering `Unsafe.As<TFrom, TTo>` a "valid solution" is exposing the underlying implementation detail much more than a public facing API like the one proposed here would do 🤔
