### ISSUE TITLE
Test failure: ReadAndWrite/OutputEncodingPreamble

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#25466]
Opened on behalf of @Sunny-pu

The test `ReadAndWrite/OutputEncodingPreamble` has failed.

System.IO.IOException : The parameter is incorrect

        Stack Trace:

           at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
       at System.Console.set_OutputEncoding(Encoding value)
       at ReadAndWrite.OutputEncodingPreamble()
Build : 2.0.0 - 20180314.01 (Core Tests)
Failing configurations:
- windows.10.amd64.iot-x64
  - Release

Details:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.01/workItem/System.Console.Tests/analysis/xunit/ReadAndWrite~2FOutputEncodingPreamble

**Comment by carlossanlop** [comment]
Triage:
The specific configuration in which this test was failing (windows.10.amd64.iot-x64) does not show up anymore, but the test is passing consistently in all other configuration.
Closing this. Feel free to reopen if it shows up again.
