### ISSUE TITLE
Inconsistent null parameter handling in IEqualityComparer.GetHashCode(Object)

### ISSUE THREAD

**Issue by ohadschn** [dotnet/runtime#25498]
The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.iequalitycomparer.gethashcode?view=netframework-4.7.1#System_Collections_IEqualityComparer_GetHashCode_System_Object_) state that `IEqualityComparer.GetHashCode(Object)` should throw `ArgumentNullException` when "The type of `obj` is a reference type and `obj` is `null`".

However, this contract is inconsistently implemented across the framework:
1. `null` parameter leads to `ArgumentNullException` as expected: https://github.com/dotnet/corefx/blob/2b805ce320feab0d7d9b72123767cc017c32948f/src/Common/src/CoreLib/System/StringComparer.cs#L305
1. `null` parameter results in no exception and returns 0: https://github.com/dotnet/corefx/blob/6dd451f51451a7d0ceea6104b51bd17005e9a0e6/src/System.Collections/src/System/Collections/Generic/HashSetEqualityComparer.cs#L34
1. `null` parameter is not checked at all, leading to `NullReferenceException`: https://github.com/dotnet/corefx/blob/1514f1cb419ada9461730b05c1b67caef4aba0e2/src/System.Private.Xml/src/System/Xml/Core/SecureStringHasher.cs#L28

**Comment by sharwell** [comment]
> The docs state that IEqualityComparer.GetHashCode(Object) should throw ArgumentNullException

This is not correct, at least not in practice. The docs state that IEqualityComparer.GetHashCode(object) _may_ throw `ArgumentNullException` if the input is null. Current guidance would recommend the following:

* Implementations of IEqualityComparer (non-generic) _should not_ throw for this case
* Implementations of `IEqualityComparer<T>` should respect the nullability of the generic type parameter for this case

**Comment by ohadschn** [comment]
When the docs say:

> Exceptions
> ArgumentNullException
> The type of obj is a reference type and obj is null.

I read that as `ArgumentNullException` is thrown if and only if the type of `obj` is a reference type and `obj` is `null`. Applying your interpretation of "may" equally to all of MS docs would be a huge change to how the vast majority of devs read it IMHO...

**Comment by joperezr** [comment]
Given that the ask here is not to correct existing behavior but more to clarify what should be done in new APIs (and this has been answered) I'll go ahead and close this issue for now. @ohadschn feel free to reopen if you think there is still some action item to track here.
