### ISSUE TITLE
Allow custom equality comparer on ConcurrentDictionary TryUpdate

### ISSUE THREAD

**Issue by skarllot** [dotnet/runtime#25559]
The method `TryUpdate` from `ConcurrentDictionary` should allow to set a custom equality comparer for the value.

## Rationale and Usage

A custom equality comparer for `TryUpdate` can target three problems.

### Ahead Of Time

On some platforms is demanded static compilation ahead of time. On those platforms code generation is not allowed.
When the method `TryUpdate` use `EqualityComparer<T>.Default` for value type comparison, it attempts to use Reflection to instantiate a new type which implements the `IEqualityComparer<T>` interface. That operation is not allowed on AOT compiled code.

### Performance

Currently the method `TryUpdate` uses the equality comparer instance from `EqualityComparer<T>.Default` which not be the most optimized comparison for the case.

### Custom comparison

For external types not controlled by the user that does not implement the intended comparison it is needed to create a wrapper to overcome the lack of a proper comparison.
The same is true if a qualified comparison is needed for specific `TryUpdate` call.

### Usage

Given those types:

```csharp
readonly struct Person : IEquatable<Person>
{
    public long Id { get; }
    public string Name { get; }
    public string Email { get; }
    public int Version { get; }

    public Person(int version)
    {
        Id = default;
        Name = default;
        Email = default;
        Version = version;
    }

    public bool Equals(Person other) => Id == other.Id && Name == other.Name && Email == other.Email && Version == other.Version;
    public override bool Equals(object obj) => obj is Person other && Equals(other);
    public override int GetHashCode() => Id.GetHashCode();
}

sealed class VersioningComparer : IEqualityComparer<Person>
{
    public bool Equals(Person first, Person second) => first.Version == second.Version;
    public int GetHashCode(Person obj) => obj.Version;
}
```

Can be used as:

```csharp
private readonly ConcurrentDictionary<long, Person> personDictionary;
private readonly VersioningComparer versionComparer;
// ...
public bool UpdatePerson(Person value)
{
    Person previousVersion = new Person(value.Version - 1);
    return personDictionary.TryUpdate(value.Id, value, previousVersion, versionComparer);
}
```

## Proposed API

```csharp
public class ConcurrentDictionary<TKey, TValue>
{
// ...
    public bool TryUpdate(TKey key, TValue newValue, TValue comparisonValue);
    public bool TryUpdate(TKey key, TValue newValue, TValue comparisonValue, System.Collections.Generic.IEqualityComparer<TValue> comparer);
// ...
}
```

## Pull Request

A PR with the proposed changes is available: dotnet/corefx#28142

**Comment by eiriktsarpalis** [comment]
I suspect that [this proposal](https://github.com/dotnet/runtime/issues/23644#issuecomment-955024497) might cover your use case.
