### ISSUE TITLE
NamedPipeServerStream.EndWaitForConnection throws SocketException on x86/Linux

### ISSUE THREAD

**Issue by liserdarts** [dotnet/runtime#25615]
I've been running the same code one multiple platforms (amd64/Win 10, amd64/Debian 9, arm64/Rasbian, and x86/Debian 9). In every case making a call to NamedPipeServerStream.Dispose will cause EndWaitForConnection to throw ObjectDisposedException. However when I move the same dll to x86/Debian 9 it throws System.Net.Sockets.SocketException.

Unexpected exception in background thread caused a crash.

> Unhandled Exception: System.Net.Sockets.SocketException: Operation canceled
>    at System.IO.Pipes.NamedPipeServerStream.<<WaitForConnectionAsync>g__WaitForConnectionAsyncCore|23_0>d.MoveNext() in /home/nick/Documents/builds/branches/corefx/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs:line 80
>    at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult) in /home/nick/Documents/builds/branches/corefx/src/Common/src/System/Threading/Tasks/TaskToApm.cs:line 87
>    at System.IO.Pipes.NamedPipeServerStream.EndWaitForConnection(IAsyncResult asyncResult) in /home/nick/Documents/builds/branches/corefx/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs:line 155

I built from the v2.1-preview1 branch for x86/Linux using the process outlined here.
https://github.com/liserdarts/dotnetcore-build-x86-Linux

**Comment by wfurt** [comment]
triage: we should re-test with current code. Fixing exception consistence should be easy and valuable.
