### ISSUE TITLE
Two System.Drawing Test failues

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/runtime#25717]
>      System.Drawing.Tests.BitmapTests.MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException [FAIL]
>         Assert.Throws() Failure
>         Expected: typeof(System.Runtime.InteropServices.ExternalException)
>         Actual:   (No exception was thrown)
>         Stack Trace:
>            C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\BitmapTests.cs(964,0): at System.Drawing.Tests.BitmapTests.MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException()
>      System.Drawing.Imaging.Tests.MetafileTests.Ctor_RectangleFEmpty_Success(description: null) [FAIL]
>         System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
>         Stack Trace:
>            C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\src\System\Drawing\Imaging\Metafile.Windows.cs(325,0): at System.Drawing.Imaging.Metafile..ctor(String fileName, IntPtr referenceHdc, RectangleF frameRect, MetafileFrameUnit frameUnit, EmfType type, String description)
>            C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\Imaging\MetafileTests.cs(571,0): at System.Drawing.Imaging.Tests.MetafileTests.Ctor_RectangleFEmpty_Success(String description)

I'm at commit 54d131f4174491bc2a7f5d6e4b0b8b725d299a8f.

**Comment by JeremyKuhne** [comment]
Closing as there have been no other reports.
