### ISSUE TITLE
Consider putting the runtime in a sub folder

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/runtime#2572]
## Steps to reproduce
Publish a standalone app

## Expected  behavior
My app is in the root and all the runtime goo is hidden in a sub folder

## Actual behavior
I publish my app and I get over 100 binaries that aren't mine. They are just noise for my users who try to launch my app from my folder.

## Environment data

**Comment by nmocruz** [comment]
I would like to have this to. Someting like <BinPath>bin</BinPath>to place all dlls. Many it managers are very pitty when comes to changes, they are used to have a package with a web.config and bin folder now they get an ugly bunch of files, and they have to find config files mixed with hundreds off dlls. I have some project that I want to migrate to donet core, almost ready to go, but the It doesn't like much this putting any change as an obstacle to move to donet core.

**Comment by swaroop-sridhar** [comment]
@nmocruz  @menasheh  
Please take a look at the proposed [single-file design](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md) for .net 5 to see if it suits your requirements. 

Changing the file layout for all apps requires substantial changes, definitely beyond the scope of .net 5. 
* Debuggers and tools need to understand the new layout 
* Certain hosting scenarios require `hostfxr.dll` `hostpolicy.dll` to be separate files. Therefore, if these dlls are linked together with the runtime, there should be an option to generate them separately and produce appropriate packages for consumption by the SDK.

**Comment by liesauer** [comment]
@nmocruz @menasheh if single-file is not suitable for you, you can have a try at [NetCoreBeauty](https://github.com/nulastudio/NetCoreBeauty), it supports both net core 2.x and 3.x. and it only moves dlls into sub-folder, other files will be left at where then should be.

**Comment by nmocruz** [comment]
I really prefer a solution like NetCoreBeauty
<https://github.com/nulastudio/NetCoreBeauty>
Thanks for the advise
