### ISSUE TITLE
Shared framework MSI has embedded cab

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/runtime#2574]
(Moved from dotnet/cli#3062)

## Steps to reproduce
- Install DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe.
## Expected  behavior

Like dotnet-dev-win-x64.1.0.0-preview1-002702.msi, the cab for dotnet-sharedframework-win-x64.1.0.0-rc2-3002702.msi should be external. That ~20MB is duplicated in the package cache and the MSI cache (\Windows\Installer).
## Actual behavior
- Note ~20MB installed for dotnet-sharedframework-win-x64.1.0.0-rc2-3002702.msi.
- https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/sharedframework/sharedframework.wxs#L9
## Environment data

`dotnet --info` output:
- n/a

**Comment by NikolaMilosavljevic** [comment]
Closing - not an easy fix with Wix toolset that we use to build MSIs. It does not seem like a high priority.
