### ISSUE TITLE
Problems with ASP.NET projects when consuming .NET Standard assets

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#25770]
It has been reported by users that if you are building an ASP.NET web app which consumes an asset that is .NET Standard-based, the app may encounter errors at runtime given that it can't find assemblies. This is an example of the errors one might get when hitting this issue:
```
System.IO.FileNotFoundException occurred HResult=0x80070002
Message=Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

One other symptom of this is that your project will complain that it needs some binding redirects added to your web.config, which you will have to add by double-clicking the warning from the error list in VS.

The reason behind what is happening is that because of [this known issue](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/514195-Targeting%20.NET%20Framework%204.7.1%20copies%20extra%20files%20to%20your%20bin%20directory.md) we end up requiring a few extra assemblies to be loaded in order to be able to run a .NET Standard-based component on .NET Framework. Because of how ASP.NET handles deployments, in some scenarios these extra files won't be copied over to the application directory, causing most of the issues.

This issue is created so that we can track the problem separate from issue dotnet/runtime#24382 as it was dicussed on this comment: https://github.com/dotnet/corefx/issues/25773#issuecomment-378341475

cc: @AlexGhiondea

**Comment by ViktorHofer** [comment]
@joperezr is this issue still tracking an external issue (see label)? https://github.com/dotnet/sdk/issues/2221 is already closed so I'm wondering if this issue is actionable on our side. Thanks

**Comment by joperezr** [comment]
I don't think this issue is actionable on our side. The problem people hit here is that not all deployment strategies take into consideration that there may be additional files that need to be deployed with your app. We control assemblies that get published to the bin folder, so when the netstandard facades are needed we include them there, but not all deployment mechanisms copy those for execution. This issue was mostly logged as a catch-all net for folks using ASP.NET and running into deployment issues leading to assemblies not found at runtime, and has been used for folks to post their repro and for us to help them fix it, but fixes of course vary case-by-case.

**Comment by ViktorHofer** [comment]
Thanks for the explanation. Given this issue isn't actionable anymore, I'm closing it.
