### ISSUE TITLE
Add Time value type in System

### ISSUE THREAD

**Issue by Gimly** [dotnet/runtime#25816]
# Rationale
Today, we have a `DateTime` struct in System that represents a specific date and time, which supports time zones. We also have a `TimeSpan` object that represents a duration (for example the time between two `DateTime`). I feel that we are missing a simple `Time` object that represents a time of day, without it being linked to a particular day.

There are a lot of reasons for representing time without dates. Alarms of an alarm clock, work shifts in a company, etc. T-Sql has a [time](https://docs.microsoft.com/en-us/sql/t-sql/data-types/time-transact-sql) type that cannot today be mapped to a type in .Net.

`DateTime.TimeOfDay` today returns a  `TimeSpan`, but it feels out of place, `TimeSpan` represents a duration and not a specific time of day.

## Implementation

Implementation would be pretty simple, it would have properties Hours, Minutes, Seconds, Milliseconds, Ticks and a few comparison / transformation methods.

`DateTime.TimeOfDay` would return this new `Time` struct instead of the current `TimeSpan`.

**Comment by ilmax** [comment]
@terrajobst I may have missed something but I don't know what's the story about these two types and I'm not sure why they didn't made their way into the framework yet, can you please share some info?

**Comment by iSazonov** [comment]
It seems it was implemented in https://github.com/dotnet/runtime/pull/50980

**Comment by stephentoub** [comment]
DateOnly and TimeOnly were added in .NET 6.
