### ISSUE TITLE
Add a GetEncodings method to System.Text.EncodingProvider to support enumerating available character encodings

### ISSUE THREAD

**Issue by mklement0** [dotnet/runtime#25819]
This API proposal arose out of dotnet/runtime#25804.

**This proposal was approved before but we discovered the original proposal was returning EncodingInfo object while we didn't expose any public constructor for this type.
The delta change in this proposal is exposing a public constructor for EncodingInfo to allow creating such objects**

## Rationale and Use Cases

As of this writing:

* [`System.Text.Encoding.GetEncodings()`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getencodings?view=netcore-2.1#System_Text_Encoding_GetEncodings) only ever enumerates the _default_ encodings available.

* [`System.Text.CodePagesEncodingProvider.Instance`](https://docs.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider.instance?view=netcore-2.1#System_Text_CodePagesEncodingProvider_Instance) lacks a method for enumerating _additional_ encodings registered via [`System.Text.Encoding.RegisterProvider(EncodingProvider)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.registerprovider?view=netcore-2.1), which - via a call to `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance)` - makes the [Windows code-page character encodings](https://msdn.microsoft.com/en-us/library/dd317756(v=vs.85).aspx) available to .NET Core.

However, **it is desirable to have the ability to enumerate _all_ available encodings**:

* Even in the abstract it seems like an awkward omission not to be able to reflect on the available encodings; more concretely, consider the following use cases, both related to [PowerShell Core](https://github.com/PowerShell/PowerShell):

* PowerShell Core commands such as `Get-Content` for reading text files support an `-Encoding` parameter that directly accepts `System.Text.Encoding` instances, so  users expect to be able to _discover_ all available encodings and/or be assisted in selecting a specific encoding with _tab completion_:
```powershell
Get-Content file.txt -Encoding <tab-keypress>  # should show all available encodings
```

*  Similarly, a [green-lighted, but not yet implemented](https://github.com/PowerShell/PowerShell/issues/6201) `Convert-TextFile` command will allow conversion between all available character encodings, so their discovery / ease of selection is important there too.

## Proposed API

Add a `GetEncodings()` method to abstract class [`System.Text.EncodingProvider`](https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/Text/EncodingProvider.cs):

```csharp
namespace System.Text
{
    public abstract class EncodingProvider
    {
      // ...
      // New virtual method, analogous to System.Text.Encoding.GetEncodings()
      public virtual System.Text.EncodingInfo[] GetEncodings ();
      // ...
    }
    
    public sealed class EncodingInfo // already exposed class 
    {
       // This is internal constructor and we are making it public
        public EncodingInfo(int codePage, string name, string displayName); 
    }
}
```

And [`System.Text.CodePagesEncodingProvider`](https://github.com/dotnet/corefx/blob/master/src/System.Text.Encoding.CodePages/src/System/Text/CodePagesEncodingProvider.Default.cs) would then implement that method to return the encodings it provides.

Specifically, a call to `System.Text.CodePagesEncodingProvider.Instance.GetEncodings()` would then return the array of `System.Text.EncodingInfo` instances representing that provider's encodings.

As with `System.Text.Encodings.GetEncodings()`, no particular enumeration order is guaranteed.

---

### Integration into `System.Text.Encodings.GetEncodings()`

Once `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance)` has been called, `System.Text.Encodings.GetEncodings()` will enumerate the additional encodings too, using the newly introduced method on the provider _if_ registered.

In other words: `System.Text.Encodings.GetEncodings()` will return whatever encodings are _currently available_ - whether just the default set by default or the _union_ of the default set and the additional encodings after provider registration.

As with the existing enumeration, the encodings (`EncodingInfo` instances) are returned in no guaranteed order.

If there is more than one registered provider that supports a given encoding, the returned list will contain only one entry for it.

## Updates (most recent ones first)

* Clarification re returning only distinct encodings.
* Return  behavior clarified again - no particular enumeration order is guaranteed
* Made new `GetEncodings` method `virtual` rather than `abstract`.
* Open question removed in favor of unconditionally outputting all then-available encodings.
* Return behavior clarified (ordering).

**Comment by iSazonov** [comment]
@tarekgh Have you any news about EncodingInfo?

**Comment by tarekgh** [comment]
> Have you any news about EncodingInfo?

No update yet because it is kind of low priority for now. But I suggest adding the following public constructor to `EncodingInfo`

```C#
 public EncodingInfo(Encoding encoding) { }
```

**Comment by terrajobst** [comment]
* `EncodingInfo.GetEncoding()` calls the static `Encoding.GetEncoding()` method, which means getting encoding infos and using `EncodingInfo.GetEncoding()` might create an encoding that isn't tied to that encoding.
    - `EncodingInfo` should take an `EncodingProvider` that we'll use in `EncodingInfo.GetEncoding()` and call `EncodingProvider.GetEncoding(codePage)`.

```C#
namespace System.Text
{
    public partial class EncodingProvider
    {
        public virtual System.Text.EncodingInfo[] GetEncodings();
    }
    
    public partial class EncodingInfo
    {
        public EncodingInfo(EncodingProvider provider, int codePage, string name, string displayName);
    }
}
```
