### ISSUE TITLE
CoreFx still builds packages that have desktop reference assemblies

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#25858]
Related https://github.com/dotnet/corefx/issues/23830, part 3

We still have some packages that have reference assemblies in their ref folder.  We've found numerous tools that don't like this and shouldn't expect all those tools to get fixed.

As such, we need to tactically remove ref folders, or use the implementation instead in these cases.

**Comment by ViktorHofer** [comment]
cc @Anipik as you are looking into reducing the number of reference assemblies in package while migrating pkgprojs to csprojs.

**Comment by ViktorHofer** [comment]
Closing as we don't include reference assemblies in packages anymore.
