### ISSUE TITLE
FriendlyName not supported in Unix

### ISSUE THREAD

**Issue by ferantivero** [dotnet/runtime#25870]
it might be worth to mention from the [Cross-Platoform Cryptography doc](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md) that FriendlyName(s) are not supported in Unix.

provided you try to use Friendly Names in Unix-based systems it will result in this:
System.PlatformNotSupportedException : The FriendlyName value cannot be set on Unix.

**Comment by vcsjones** [comment]
`FriendlyName` has since been annotated with `SupportedOSPlatform` to indicate that it is Windows-only starting in .NET 6. I'm not sure it makes sense to do anything beyond that anymore (SOSP did not exist when discussions last occurred).

**Comment by bartonjs** [comment]
I agree, the SupportedOSPlatform attribute is designed for describing boundary conditions like this.  The Cross-Platform Cryptography document is more about high level concepts.
