### ISSUE TITLE
ApiProposal: string.Create method which takes an additional Span as data parameter

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/runtime#25898]
With the new ``Span<>`` based Apis an additional method to create strings was added which takes the length and an action + state as parameter to allow alloc-free modification of the string based on the action.
The signature is:
```csharp
 public static string Create<TState>(int length, TState state, SpanAction<char, TState> action)
```
An example of the usage is in @stephentoub's article https://msdn.microsoft.com/en-us/magazine/mt814808.aspx

I propose an additional method taking a ``ReadonlySpan<char>`` as parameter to be able to populate the new string more easily. It is currently not possible to use a custom TState with ``ReadOnlySpan<char>`` as a field, because such byref structs can't be type parameters, so the current method does not solve the problem.

**Rationale and Usage**
With span it is easy to create a substring and trim and such apis are included with ``Span``. Sometimes it might be useful to simply remove certain characters from a string, where you know the new length of the string in advance. One example is unescaping data, see the code snippet below for usage, the new length of the string can be easily calculated in advance, so a fixed size buffer is enough.

**Proposed API**

```csharp
 public delegate void SpanDataAction<T, in TArg>(Span<T> span, in ReadOnlySpan<T> data, TArg arg);
 public static string Create<TState>(int length, in ReadOnlySpan<char> data, TState state, SpanDataAction<char, TState> action);
```
The new delegate is necessary to be able to use the data in the action.

**Example usage**
A shortened example of how to unescape a possible JSON span, in this example state is not used, but I imagine that State will be equally useful as in the original string.Create, so it is included in the proposal.
```csharp
ReadOnlySpan<char> data = "Hello\\nWorld"; // escaped newline
int length = data.Length - 1;
var output = Create(length, data, new State(),
    delegate(Span<char> span, in ReadOnlySpan<char> input, State state)
    {
        var counter = 0;
        for (int i = 0; i < input.Length; i++)
        {
            var c = input[i];
            if (c == '\\')
            {
                i++;
                c = input[i];
                switch (c)
                {
                    case 'n':
                        c = '\n';
                        break;
                }
            }

            span[counter++] = c;
        }
    });
private readonly struct State {}	
```

**Proposed Implementation**

Modified from the existing string.Create
```csharp
public static string Create<TState>(int length, in ReadOnlySpan<char> data, TState state, SpanDataAction<char, TState> action)
{
    if (action == null)
        throw new ArgumentNullException(nameof(action));

    if (length <= 0)
    {
        if (length == 0)
            return string.Empty;
        throw new ArgumentOutOfRangeException(nameof(length));
    }

    //Span<char> span = stackalloc char[length];
    //action(span, data, state);
    //return span.ToString();
    string result = FastAllocateString(length);
    action(new Span<char>(ref result.GetRawStringData(), length), data, state);
    return result;
}
```

**Impact**
Currently, as to my knowledge, you need to use either unsafe pointer logic and/or Unsafe.Write methods to replace the existing chars in the string.

**Open Questions**
* Better name for the delegate
* Better workarounds than unsafe logic?

**Comment by stephentoub** [comment]
> Currently I have to manually calculate the trimmed length of the source string, which duplicates that same work

There are multiple ways around that, e.g.
```C#
public static unsafe string TrimToLower(this string source)
{
    ReadOnlySpan<char> trimmed = source.AsSpan().Trim();
    fixed (char* ptr = trimmed)
    {
        return string.Create(trimmed.Length, (IntPtr)ptr, (dest, ptr) =>
            new ReadOnlySpan<char>((void*)ptr, dest.Length).ToLowerInvariant(dest));
    }
}
```
or if you really wanted to avoid the unsafe, e.g.
```C#
public static string TrimToLower(this string source)
{
    ReadOnlySpan<char> trimmed = source.AsSpan().Trim();
    source.AsSpan().Overlaps(trimmed, out int offset);
    return string.Create(trimmed.Length, (source, offset), (dest, state) =>
        state.source.AsSpan(state.offset, dest.Length).ToLowerInvariant(dest));
}
```

Adding a new overload here that takes a single span as input doesn't add enough value IMO; it let's you pass in a single span, but what if you wanted to pass in two, or three, or some other ref struct, or a span and something else. Etc.  C# 12 is likely to include a `ref struct` constraint, at which point we either take a small breaking change to add a `TState : ref struct` to the existing method (which would codify the fact that the delegate would be unable to do with the state something you couldn't do with a ref struct), or if that was too big of a break, we'd add a new method with such a constraint.

**Comment by stephentoub** [comment]
This is no longer needed now that string.Create's TState is allows ref struct.
