### ISSUE TITLE
[API Proposal] ClientWebSocket upgrade response details 

### ISSUE THREAD

**Issue by amrmahdi** [dotnet/runtime#25918]
*Updated by @CarnaViire*

## Background and motivation

`ClientWebSocket` currently doesn't provide any details about upgrade response. However, the information about response headers and status code might be important in both failure and success scenarios.

In case of failure, the status code can help to distinguish between retriable and non-retriable errors (server doesn't support web sockets at all vs just a small transient error). Headers might also contain additional information on how to handle the situation.

The headers are also useful even in case of a success web socket connect, e.g. they can contain a token tied to a session, or some info related to subprotocol version, or that the server can go down soon, etc.

There are three asks on GH for this ATM with a total of *21 distinct upvotes* — #28331, #62474 and #25918 (this issue).

## API Proposal

There are two alternatives, that are usable regardless of success/failure scenario, and also both opt-in, in order not to regress the existing usages in size and perf.

### Option 1. ConnectAsync overload with a result object to fill in

```c#
// NEW
class WebSocketConnectResult
{
    public int? HttpStatusCode { get; set; }
    public IReadOnlyDictionary<string, IEnumerable<string>>? HttpResponseHeaders { get; set; }
}

// EXISTING
class ClientWebSocket
{
    // EXISTING
    public Task ConnectAsync(Uri uri, CancellationToken cancellationToken);
    // NEW
    public Task ConnectAsync(Uri uri, WebSocketConnectResult result, CancellationToken cancellationToken);
}
```

Usage:
```c#
ClientWebSocket ws = new();
WebSocketConnectResult result = new();
try
{
    await ws.ConnectAsync(uri, result, default);
    // success scenario
    ProcessSuccess(result.HttpResponseHeaders);
}
catch (WebSocketException)
{
    // failure scenario
    if (connectResult.HttpStatusCode != null)
    {
        ProcessFailure(result.HttpStatusCode, result.HttpResponseHeaders);
    }
}
```

Pros:
- Provides data that is essentially a connect result, from an overload of `ConnectAsync` method
- User can reuse the result objects
- Result object is independent from the `ClientWebSocket` object and its ownership/lifetime is "naturally" in hands of the user

Cons:
- Need to manually create additional object (no `out var` syntax here)
- User needs to ensure thread-safety, especially if reusing result objects

### Option 2. WebSocket property with opt-in setting

```c#
// EXISTING
class ClientWebSocketOptions
{
    // NEW
    public bool CollectHttpResponseDetails { get; set; } = false;
}

// EXISTING
class ClientWebSocket
{
    // EXISTING
    public string? SubProtocol { get; }
    // NEW
    public int? HttpStatusCode { get; }
    public IReadOnlyDictionary<string, IEnumerable<string>>? HttpResponseHeaders { get; set; } // setter to clean up when not needed anymore
}
```

Usage:
```c#
ClientWebSocket ws = new();
ws.Options.CollectHttpResponseDetails = true;
try
{
    await ws.ConnectAsync(uri, default);
    // success scenario
    ProcessSuccess(ws.HttpResponseHeaders);
    ws.HttpResponseHeaders = null; // clean up (if needed)
}
catch (WebSocketException)
{
    // failure scenario
    if (ws.HttpStatusCode != null)
    {
        ProcessFailure(ws.HttpStatusCode, ws.HttpResponseHeaders);
    }
}
```

Pros:
- `SubProtocol`, which also can be treated as "connect result", is already a part of `ClientWebSocket` object
- No additional objects

Cons:
- Expanding `ClientWebSocket` object leads to increased memory footprint
- Even though it is possible to clean up by setting headers to null, user needs to be aware of that approach.

### Other alternatives considered, but rejected:
- Returning result object from the method itself (`Task<WebSocketConnectResult>`) would either only work in success scenario or will require unconventional handling of every possible exception by storing it into the result object
- Having different approaches for success and failure scenarios doubles the API changes needed and is harder to use, plus adding a new derived exception is bad for discoverability.
- Using full `HttpResponseMessage` is dangerous, it is easy to misuse (and end up breaking the protocol/aborting connection by disposing/etc)
- In general, we want to distance from `System.Net` types in favor of plain types like `int` and `IDictionary` to enable wider usage.

--------

*Original post by @amrmahdi*

Related to dotnet/runtime#19405 

ClientWebSocket on .NET Core does not provide the upgrade request errors in the exception details as it does on the .NET Framework.

### Repro code 

```csharp
var client = new ClientWebSocket();

client.ConnectAsync(new Uri("wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1"), CancellationToken.None).GetAwaiter().GetResult();
```

### Behavior on .NET 462
```
Unhandled Exception: System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.Main(String[] args)
```

### Behavior on .NET Core 2.1 preview 2
```
   Unhandled Exception: System.Net.WebSockets.WebSocketException: Unable to connect to the remote server
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args)
```

As you can see on .NET 462, the inner exception is a ```WebException``` with the error details.

### Proposed Fix
Create an inner exception of type ```WebException``` in a similar fashion to 
https://github.com/dotnet/corefx/blob/6acd74dda7bc4f585d2c4006da4a8b2deb0261ad/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1211 
and throw if the response is not 200. 

The original WebException in .NET framework was thrown from```HttpWebRequest.GetResponseAsync()```, so I think the exception needs to be bubbled up in a similar way.

**Comment by karelz** [comment]
Looks like this is API addition -- per https://github.com/dotnet/runtime/issues/25918#issuecomment-382158285 we should add property on exception.
Sadly, it is too late for 5.0, moving to 6.0 (and fixing labels to capture API addition).

**Comment by cmsteffey** [comment]
@karelz Is there any chance the team could try to get something like this into .NET 7?
I don't think it'd be too bad to build a small exception with one extra property of the HttpResponse, and set that as the InnerException of the one that's thrown. Then people could get response content, status codes, headers, etc

**Comment by cmsteffey** [comment]
Thinking about it now, in regards to my above comment, there could actually be properties on the ClientWebsocket to get the UpgradeRequest and UpgradeResponse :)
Instead of trying to run the data through the exception
Just a thought

**Comment by karelz** [comment]
@cmsteffey it would be nice to have it, however I can't promise it for .NET 7 as we are fairly overbooked already :(

One of the planned features in .NET 7 is WebSockets for HTTP/2, so perhaps we could do it then (as we will be touching the code anyway and likely we will be adding new APIs) - @greenEkatherine @CarnaViire FYI.

**Comment by cmsteffey** [comment]
@karelz sounds good! If you want me to help, I'd love to
We might have to implement it in the underlying WebSocketHandle though which could be more difficult, due to ConnectAsync being run through the ConnectedWebSocket prop object

**Comment by MihaZupan** [comment]
Minor comment about
```c#
public Task ConnectAsync(Uri uri!!, CancellationToken cancellationToken, out HttpResponseHeaders? httpResponseHeaders);
```

We can't have an `out` on an `async` method. Given the existing overload, we can't just change the return type either.

**Comment by CarnaViire** [comment]
Updated proposal after team discussion:

```c#
// NEW
class WebSocketConnectResult
{
    public bool IsSuccess => Error == null;

    public WebSocketError? Error { get; internal set; }
    public string? ErrorMessage { get; internal set; }

    public int? HttpStatusCode { get; internal set; }
    public IDictionary<string, IEnumerable<string>>? HttpResponseHeaders { get; internal set; }
}

// EXISTING
public class ClientWebSocket
{
    // EXISTING
    public Task ConnectAsync(Uri uri!!, CancellationToken cancellationToken);
    // NEW
    public Task<WebSocketConnectResult> TryConnectAsync(Uri uri!!, CancellationToken cancellationToken);
}
```

All handshake validations (status code, header presence and format etc) that throw in `ConnectAsync`, would just fill a result object in `TryConnectAsync`. So in both success scenario and validation-fail scenario, the result will contain info about status code and headers (if they were available).

*Limitations:* in case of a cancellation, `Abort` from a parallel thread, or some exception thrown outside of `ClientWebSocket` code (e.g. IOException), `TryConnectAsync` would still throw. I wonder whether the info about the response headers would still be needed in that case? It seems that most of the time such exceptions would happen while the response is not available yet.

**Comment by karelz** [comment]
Team discussion:
- Original proposal needs `TryConnectAsync` to be renamed as it can still throw -- to `ConnectAsyncEx` / `ConnectAsyncWithResult`
- We are undecided among the 3 options
- New exception is hard to discover (one needs to look at docs to know it can be thrown)

@stephentoub what do you think? We should discuss on Thu / when you can join us.

**Comment by stephentoub** [comment]
Another option:
ClientWebSocket already exposes details about how the connection was established, e.g. its SubProtocol property, and it already exposes details about how the connection was closed, e.g. its CloseStatus and CloseStatusDescription properties.  You could imagine this feature would just be additional properties on ClientWebSocket providing more details about the connection, e.g.
```C#
public class ClientWebSocket : WebSocket
{
    // Existing
    public override string? SubProtocol { get; }
    public override WebSocketCloseStatus? CloseStatus { get; }
    public override string? CloseStatusDescription { get; }
    ...
    
    // New
    public int? ConnectStatusCode { get; }
    public IDictionary<string, IEnumerable<string>>? ConnectResponseHeaders { get; }
}
```
It continues with the tradition of exposing such connection-level info on the ClientWebSocket, it doesn't require any new Connect methods or new patterns or new exception types, and it shouldn't meaningfully impact the performance of existing use (the ClientWebSocket will grow by a few fields, and everything else can be pay-for-play).

Was this approach considered?

**Comment by CarnaViire** [comment]
I considered this approach, but I didn't like that there is no "opt-out" option in that case... I might be wrong, but don't think that full response headers, especially in success scenario, would be used a lot. And we will be holding on that data, which doesn't have much significance outside of connect context, for the whole lifetime of a WebSocket, which may be long. So it felt more natural to me to have them as a connect result.
That being said, we will be growing a client websocket, not a server one, so the size might not matter that much.

**Comment by davidfowl** [comment]
> That being said, we will be growing a client websocket, not a server one, so the size might not matter that much.

I would avoid this assumption in general going forward with things like YARP. We create a ClientWebSocket today per incoming client connection websocket. Size absolutely matters. If those headers can be cleared to release the memory then that would be a fine tradeoff.

**Comment by stephentoub** [comment]
That could be addressed by:
- making a property like `ConnectResponseHeaders` settable, and someone can null it out after they're done with it (or make the property instead a method that gets and clears)
- making it opt-in by adding to ClientWebSocketOptions a bool property that's false by default and that you set to true if you want these various Connect members to be filled in

**Comment by davidfowl** [comment]
> making a property like ConnectResponseHeaders settable, and someone can null it out after they're done with it (or make the property instead a method that gets and clears)

I prefer this.

> making it opt-in by adding to ClientWebSocketOptions a bool property that's false by default and that you set to true if you want these various Connect members to be filled in

This is tempting as it won't regress in .NET 7 but it's an extra API.

What about a hybrid? If you assign ConnectResponseHeaders to a non null value, then set the headers otherwise, it won't be. That allows for an opt-in model without the additional bool.

Thoughts?

**Comment by CarnaViire** [comment]
I believe that (especially hybrid approach) might be bad for discoverability.

Imagine you use ClientWebSocket, and at some point you realize you need to look at headers. You press '.' and see there's a property with headers. How convenient! But you access it and it is always null. Where are the headers, you ask.

Now if you think to look at the options, you can find the opt-in there, so you might end up successful. But without the property, it seems a bit counter-intuitive and you have no other way than to learn the way to use it from the docs.

That made me thinking, maybe we can have the option with opt-out instead. So if you are highly concurrent scenario and the size growth ended up being too much, you can go and opt out, or if you need the headers, then clean it up after using. Otherwise, if you just have one client, you wouldn't really notice anything, and if you need the headers, they would be easily discoverable.

(The cleaning up by setting the property to null also seems questionable.... as a user, how can you be sure you will not break anything, if you mess up with the properties of a library object that's currently in use?)

(In the end, I am still not convinced that this would be better than having a connect method with full result...)

**Comment by davidfowl** [comment]
> That made me thinking, maybe we can have the option with opt-out instead. So if you are highly concurrent scenario and the size growth ended up being too much, you can go and opt out, or if you need the headers, then clean it up after using. Otherwise, if you just have one client, you wouldn't really notice anything, and if you need the headers, they would be easily discoverable.

This isn't great because it means things compiled for earlier versions of .NET that use websockets that *run* on .NET 7 will use more memory and the only way to fix it would be to have that library specifically target .NET 7 so it can set the property to false (this is what YARP would have to do). 

I prefer something opt in.

**Comment by CarnaViire** [comment]
Thanks!
I believe now we are down to two alternatives -- both of them opt-in and both of them usable regardless of success/failure scenario:

### Option 1. ConnectAsync overload with a result object to fill in

```c#
// NEW
class WebSocketConnectResult
{
    public int? HttpStatusCode { get; set; }
    public IDictionary<string, IEnumerable<string>>? HttpResponseHeaders { get; set; }
}

// EXISTING
class ClientWebSocket
{
    // EXISTING
    public Task ConnectAsync(Uri uri, CancellationToken cancellationToken);
    // NEW
    public Task ConnectAsync(Uri uri, CancellationToken cancellationToken, WebSocketConnectResult result);
}
```

Usage:
```c#
ClientWebSocket ws = new();
WebSocketConnectResult result = new();
try
{
    await ws.ConnectAsync(uri, default, result);
    // success scenario
    ProcessSuccess(result.HttpResponseHeaders);
}
catch (WebSocketException)
{
    // failure scenario
    if (connectResult.HttpStatusCode != null)
    {
        ProcessFailure(result.HttpStatusCode, result.HttpResponseHeaders);
    }
}
```

Pros:
- Provides data that is essentially a connect result, from an overload of `ConnectAsync` method
- User can reuse the result objects
- Result object is independent from the `WebSocket` object and its ownership/lifetime is "naturally" in hands of the user

Cons:
- Need to manually create additional object (no `out var` syntax here)
- User needs to ensure thread-safety, especially if reusing result objects

----------

### Option 2. WebSocket property with opt-in setting

```c#
// EXISTING
class ClientWebSocketOptions
{
    // NEW
    public bool CollectHttpResponseDetails { get; set; } = false;
}

// EXISTING
class ClientWebSocket
{
    // EXISTING
    public string? SubProtocol { get; }
    // NEW
    public int? HttpStatusCode { get; }
    public IDictionary<string, IEnumerable<string>>? HttpResponseHeaders { get; set; } // setter to clean up when not needed anymore
}
```

Usage:
```c#
ClientWebSocket ws = new();
ws.Options.CollectHttpResponseDetails = true;
try
{
    await ws.ConnectAsync(uri, default);
    // success scenario
    ProcessSuccess(ws.HttpResponseHeaders);
    ws.HttpResponseHeaders = null; // clean up (if needed)
}
catch (WebSocketException)
{
    // failure scenario
    if (ws.HttpStatusCode != null)
    {
        ProcessFailure(ws.HttpStatusCode, ws.HttpResponseHeaders);
    }
}
```

Pros:
- `SubProtocol`, which also can be treated as "connect result", is already a part of `WebSocket` object
- No additional objects

Cons:
- Expanding `WebSocket` object leads to increased memory footprint
- Even though it is possible to clean up by setting headers to null, user needs to be aware of that approach.

--------

*Other alternatives considered, but rejected:*
- Returning result object from the method itself (`Task<WebSocketConnectResult>`) would either only work in success scenario or will require unconventional handling of every possible exception by storing it into the result object
- Having different approaches for success and failure scenarios doubles the API changes needed and is harder to use, plus adding a new derived exception is bad for discoverability.
- Using full `HttpResponseMessage` is dangerous, it is easy to misuse (and end up breaking the protocol/aborting connection by disposing/etc)
- In general, we want to distance from `System.Net` types in favor of plain types like `int` and `IDictionary` to enable wider usage.

-------
cc @stephentoub @davidfowl @dotnet/ncl
Does this sound all right? Let me know if you have any concerns or additional ideas, otherwise I would proceed with this proposal.

**Comment by MihaZupan** [comment]
Nit: CT should be the last parameter
```diff
-public Task ConnectAsync(Uri uri, CancellationToken cancellationToken, WebSocketConnectResult result);
+public Task ConnectAsync(Uri uri, WebSocketConnectResult result, CancellationToken cancellationToken);
```

**Comment by MihaZupan** [comment]
Also should the headers be an `IReadOnlyDictionary`?

**Comment by CarnaViire** [comment]
Team reached agreement on the updated proposal. Marking as ready for review.

**Comment by CarnaViire** [comment]
Hi @cmsteffey, you've previously expressed interest in helping us with the implementation. We are currently still going through the API review process, but once it's finalized, would it be something you're still interested in?

**Comment by bartonjs** [comment]
We generally liked option (2) over option (1).

* We don't particularly feel like the nullable return value on the HttpStatusCode is needed, the code should always be populated and can use a sentinel value for "I haven't attempted connecting yet"
* The HttpStatusCode property seems like it should be using `System.Net.HttpStatusCode` instead of `int` as its return type.  If there's a layering problem, or other technical constraint, then `int` is OK.

```C#
namespace System.Net.WebSockets
{
    public partial class ClientWebSocketOptions
    {
        public bool CollectHttpResponseDetails { get; set; } = false;
    }

    public partial class ClientWebSocket
    {
        // EXISTING
        //public string? SubProtocol { get; }

        // NEW
        public System.Net.HttpStatusCode HttpStatusCode { get; }
        public IReadOnlyDictionary<string, IEnumerable<string>>? HttpResponseHeaders { get; set; } // setter to clean up when not needed anymore
    }
}
```
