### ISSUE TITLE
arm and clang 5.0

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#25943]
Due to bugs in clang3.9 on arm, coreclr changed builds to require >=clang4.0, and official build and CI system docker container was updated to use clang5.0. It seems like corefx should match this.

The coreclr change: https://github.com/dotnet/coreclr/pull/17422

**Comment by ViktorHofer** [comment]
@janvorli I think we addressed this now?

**Comment by janvorli** [comment]
Yes, the compiler setup is now common for all the distros and we use clang 9 for all of our official builds.
