### ISSUE TITLE
System.Reflection.Emit: ILGenerator.Emit(OpCodes.Ldtoken, <MethodInfo>) produces incorrect metadata for methods with C# 7.2 `in` parameters in generic types

### ISSUE THREAD

**Issue by stakx** [dotnet/runtime#25958]
@TAGC recently noted in https://github.com/castleproject/Core/issues/339#issuecomment-372605885 that DynamicProxy-based mocking libraries (e.g. Moq, NSubstitute) appear to have problems mocking the following generic interface:

> ```csharp
> public interface IGenericStructByRefConsumer<T>
> {
>     T Consume(in Struct message);
> }
> ```

Mocking such a type will typically result in a `MissingMethodException`. It only seems to occur with generic types/methods, and in the presence of a C# 7.2 `in` parameter modifier.

I've been able to track this down to what appears to be a bug in System.Reflection.Emit. A brief description follows below; if more detail or code is required, I can probably provide it... please ask.

---

Given this C# 7.2+ interface:

```csharp
public interface WithIn<T>
{
    void Method(in int arg);
}
```

<details>
<summary>(Expand to see the equivalent type definition in IL.)</summary>

```
.class public abstract interface auto ansi WithIn`1<T>
{
  .method public hidebysig newslot abstract virtual instance void Method([in] int32& modreq([mscorlib]System.Runtime.InteropServices.InAttribute) arg) cil managed
  {
    .param [1]
    .custom instance void [mscorlib]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() = ( 01 00 00 00 ) 
  }
}
```
</details>
<br>

DynamicProxy would need to generate the following IL instruction sequence using a `System.Reflection.Emit.ILGenerator` (because it caches `MethodInfo` for proxied methods):

```
ldtoken    method instance void class WithIn`1<int32>::Method(int32& modreq([mscorlib]System.Runtime.InteropServices.InAttribute))
ldtoken    class WithIn`1<int32>
call       class [mscorlib]System.Reflection.MethodBase 
```

This is how one would supposedly do it with `ILGenerator`:

```csharp
var methodType = typeof(WithIn<int>);
var method = methodType.GetMethod("Method");
var getMethodFromHandle = typeof(MethodBase).GetMethod("GetMethodFromHandle", new[] { typeof(RuntimeMethodHandle), typeof(RuntimeTypeHandle) });

ilGenerator.Emit(OpCodes.Ldtoken, method);  // <-- !!!
ilGenerator.Emit(OpCodes.Ldtoken, methodType);
ilGenerator.EmitCall(OpCodes.Call, getMethodFromHandle, null);
```

I've verified (by saving the dynamic assembly to disk using the .NET Framework 4.7, then dumping it with ILDASM) that the following IL is generated instead:

```
ldtoken    method instance void class WithIn`1<int32>::Method(int32&)
ldtoken    class WithIn`1<int32>
call       class [mscorlib]System.Reflection.MethodBase [mscorlib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [mscorlib]System.RuntimeMethodHandle,
```

Note the absence of the `modreq` in the first instruction's method reference. This will result in a `MissingMethodException` (because method signatures don't match) when the generated code is run:

> System.MissingMethodException: Method not found: 'Void IWithIn`1.Method(Int32 ByRef)'.

The same `MissingMethodException` occurs with .NET Core 2.0, so I suspect it inherited the exact same problem from the .NET Framework. If you'd rather have repro code for .NET Core, you'll find it below.

<details>
<summary>(Expand for an error reproduction on .NET Core.)</summary>

```csharp
using System;
using System.Diagnostics;
using System.Reflection;
using System.Reflection.Emit;

public interface WithIn<T>
{
    void Method(in int arg);
}

class Program
{
    static void Main()
    {
        var methodType = typeof(WithIn<int>);
        var method = methodType.GetMethod("Method");
        var getMethodFromHandle = typeof(MethodBase).GetMethod("GetMethodFromHandle", new[] { typeof(RuntimeMethodHandle), typeof(RuntimeTypeHandle) });

        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("DynamicAssembly"), AssemblyBuilderAccess.Run);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule("DynamicModule");
        var typeBuilder = moduleBuilder.DefineType("DynamicType", TypeAttributes.Public | TypeAttributes.Abstract | TypeAttributes.Class);

        var methodBuilder = typeBuilder.DefineMethod("Get", MethodAttributes.Public | MethodAttributes.Static, typeof(MethodBase), new Type[0]);
        var ilBuilder = methodBuilder.GetILGenerator();
        ilBuilder.Emit(OpCodes.Ldtoken, method);
        ilBuilder.Emit(OpCodes.Ldtoken, methodType);
        ilBuilder.EmitCall(OpCodes.Call, getMethodFromHandle, null);
        ilBuilder.Emit(OpCodes.Ret);

        var type = typeBuilder.CreateType();

        var il = type.GetMethod("Get").GetMethodBody().GetILAsByteArray();
        Debug.Assert(il[0] == OpCodes.Ldtoken.Value, "First op-code is not `ldtoken`.");

        var ilMethodMetadataToken = BitConverter.ToInt32(il, 1);
        Debug.Assert(type.Module.ResolveMethod(ilMethodMetadataToken) == method, "First `ldtoken` does not refer to the correct method.");
    }
}
```
</details>
<br>

Note again that this problem only occurs for methods in generic types/methods, and in the presence of an `in` parameter modifier.

/cc @jonorossi (for DynamicProxy), @zvirja (for NSubstitute), @thomaslevesque (for FakeItEasy)

**Comment by steveharter** [comment]
Changing milestone to 6.0 for risk (5.0 is almost in ask-mode and no more previews); see the PR for more information. cc @GrabYourPitchforks

**Comment by dsyme** [comment]
@steveharter Just to check, is it likely that #40587 fixes this problem https://github.com/dotnet/fsharp/issues/9401#issuecomment-680102473

That is, a Reflection emit call to `ReadOnlySpan get_Item` code?

**Comment by wzchua** [comment]
It does not fix that. It appears return type also have custom modifiers that aren't being included in the signature

**Comment by wzchua** [comment]
hmm, the methodInfo seems wrong
```
typeof(ReadOnlySpan<char>).GetMethod("get_Item", BindingFlags.Public | BindingFlags.Instance)
```
The string signature shows `Char& get_Item(Int32)`
The customAttribute is `[System.Runtime.CompilerServices.IsReadOnlyAttribute()]`

From sharplab, the call uses this signature
```
IL_000a: call instance !0& modreq([System.Private.CoreLib]System.Runtime.InteropServices.InAttribute) valuetype [System.Private.CoreLib]System.ReadOnlySpan`1<char>::get_Item(int32)
```


```
var a = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("aa"), AssemblyBuilderAccess.Run);
var m = a.DefineDynamicModule("MyDynamicAsm");
var t = m.DefineType("MyDynamicType", TypeAttributes.Public);

var mb = t.DefineMethod("foo", MethodAttributes.Public | MethodAttributes.Static, CallingConventions.Standard, typeof(char), new Type[] { typeof(string) });
var ilg = mb.GetILGenerator();
var minfo1 = typeof(MemoryExtensions).GetMethod("AsSpan", new Type[] { typeof(string) });
var minfo2 = typeof(ReadOnlySpan<char>).GetMethod("get_Item", BindingFlags.Public | BindingFlags.Instance);
ilg.Emit(OpCodes.Ldarg_0);
ilg.Emit(OpCodes.Call, minfo1);
ilg.Emit(OpCodes.Stloc_0);
ilg.Emit(OpCodes.Ldloca_S, 0);
ilg.Emit(OpCodes.Ldc_I4_0);
ilg.Emit(OpCodes.Call, minfo2);
ilg.Emit(OpCodes.Ldind_U2);
 ilg.Emit(OpCodes.Ret);
t.CreateType();

var m2 = t.GetMethod("foo");
byte[] il = m2.GetMethodBody().GetILAsByteArray();
int ilMethodMetadataToken = BitConverter.ToInt32(il, 2);
MethodBase resolvedMethod = t.Module.ResolveMethod(ilMethodMetadataToken);
int ilMethodMetadataToken2 = BitConverter.ToInt32(il, 14);
MethodBase resolvedMethod2 = t.Module.ResolveMethod(ilMethodMetadataToken2);
var c = (char)m2.Invoke(null, new object[] { "abc" });
```
I can confirm that the token can now be resolved but the method still throws an exception when invoked
