### ISSUE TITLE
System.Diagnostics.Activity does not use Correlation-Context: Id in GetRootId

### ISSUE THREAD

**Issue by ngbrown** [dotnet/runtime#25962]
While `Activity` is implementing the hierarchical request id spec, in the case of a mixed hierarchical and non-hierarchical scenario, if the parent service only supports the flat request id, but it sets the `Correlation-Context: Id` header, then that `Id` should have made it into the baggage and would be available to pull from.

I think `Activity.RootId` should also check the baggage keys in addition to the `Id` and `ParentId`.

@lmolkova as an author of the spec and `Activity` implementation.

**Comment by tarekgh** [comment]
Closing this as no much activity on that. Feel free to respond if there is still any requests here.
