### ISSUE TITLE
PhysicalAddress.Parse should support more formats

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#26188]
## Motivation 

From https://www.lifewire.com/introduction-to-mac-addresses-817937 currently follow formats and separators is used by different vendors:

MMMMMMSSSSSS
MM:MM:MM:SS:SS:SS
MM-MM-MM-SS-SS-SS
MMM.MMM.SSS.SSS

We need an API to support this.

1. We could have method like `mac.ToString(":");` with custom separator/format provider to get MACs in all common and custom formats.
2. Many APIs add TryParse() in addition to Parse() for hot code paths to avoid exceptions that could be important for networking scenarios.

(Related dotnet/corefx#41518)

## Proposal

```c#
namespace System.Net.NetworkInformation
{
    public class PhysicalAddress
    {
        public static bool TryParse(string address, out PhysicalAddress mac);

        //public string ToString(); -- Existing API
        public string ToString(string? format);
        public string ToString(string? format, IFormatProvider? provider);
    }
}
```

----------------
Original issue for history:
--------------

[System.Net.NetworkInformation.PhysicalAddress.Parse()](http://source.dot.net/#System.Net.NetworkInformation/System/Net/NetworkInformation/PhysicalAddress.cs,118) method [currently support](https://msdn.microsoft.com/en-us/library/system.net.networkinformation.physicaladdress.parse%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) only following formats:
```
001122334455

00-11-22-33-44-55
```

Really we can find that [more formats](https://www.lifewire.com/introduction-to-mac-addresses-817937) is used by verdors and humans:

```
00:11:22:33:44:55
0011:2233:4455
```
So we could have extention method `mac.ToString(":");` with custom separator and we should parse mac address with ':' or custom separator.

Many APIs add TryParse() in addition to Parse().

Also docs says that the Parse() method only support upper-case letters as hexadecimal digits but some application and humans can type macs in lower-case - it will be not so big overhead to make the method _case-insensitive_.

```c#
namespace System.Net.NetworkInformation
{
    public class PhysicalAddress
    {
        public static bool TryParse(string address, out PhysicalAddress mac);

        public static PhysicalAddress Parse(string address); // make case-insensitive

        public string ToString();
        public string ToString(string? format);
        public string ToString(string? format, IFormatProvider? provider);
    }
}
```

**Comment by danmosemsft** [comment]
Hi @iSazonov did you get a chance to provide info requested?

**Comment by iSazonov** [comment]
@danmosemsft All info about formats was explicitly added.
```
MMMMMMSSSSSS
MM:MM:MM:SS:SS:SS
MM-MM-MM-SS-SS-SS
MMM.MMM.SSS.SSS
```
