### ISSUE TITLE
Enable .NET Core on Yocto Linux

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#2621]
In https://github.com/Tragetaschen/meta-aspnet/tree/master/recipes-dotnet/corehost, there are some bitbake recipes that compile CoreCLR, CoreFX and core-setup for inclusion a in Yocto Linux based distribution for ARM.

The git commits used follow the versions in `pkg/projects/Microsoft.NETCore.App/project.json.template`, to get to a consistent set of packages for core-setup to pick up from a local NuGet folder.

As a RID, this setup currently (mis)uses `ubuntu.16.04-arm`, but of course it's not Ubuntu. I haven't yet found a good way to get to a better RID since Yocto/OpenEmbedded is a meta-distribution used to create actual, embedded distributions depending on ones needs. I'll try to summarize my thoughts below.

The recipes currently contain a handful of patches that tame the build environment to actually compile. I'll create some issues in the appropriate repos.

And before I forget:
Many thanks to @ernstp for doing all the hard work enabling the 2.0 Yocto builds!
And of course to all the people that ported .NET Core to ARM in the first place!

**Comment by NikolaMilosavljevic** [comment]
Discussion seems to be closed. Thank you for your input!
