### ISSUE TITLE
[Uri] Consider adding query string manipulation

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#26234]
Web APIs are everywhere these days and there's still no way to manipulate them in the framework.

`System.Web` has one. `System.ServiceModel` has another. And pretty much every library that needs it has one.

It would be nice to have something that:

* Parses a query string into a `NameValueCollection`.
* Allows manipulating the values
* Renders que query string

**Comment by MihaZupan** [comment]
Closing in favour of #32606
