### ISSUE TITLE
StartInfo_TextFile_ShellExecute failing consistently on Server Core

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#26231]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180521.01/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessStartInfoTests~2FStartInfo_TextFile_ShellExecute

Apparently Process.Start on foo.txt with UseShellExecute=true is returning a null process object. 

```
Could not start C:\\Users\\runner\\AppData\\Local\\Temp\\ProcessStartInfoTests_x1e54hcw.eri\\StartInfo_TextFile_ShellExecute_993_88c6de27.txt UseShellExecute=True
Association details for '.txt'
------------------------------
Open command: C:\\Windows\\system32\\NOTEPAD.EXE %1
ProgID: txtfile

Expected: True
Actual:   False
Stack Trace :
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() in E:\A\_work\63\s\corefx\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 990
```

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201008.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26906848&paneView=debug&resultId=101952)

failed test: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
Could not start C:\Users\ContainerAdministrator\AppData\Local\Temp\ProcessStartInfoTests_al0dwaqt.vqn\StartInfo_TextFile_ShellExecute_972_7a0fec40.txt UseShellExecute=True
Association details for '.txt'
------------------------------
Open command: C:\Windows\system32\NOTEPAD.EXE %1
ProgID: txtfile

Expected: True
Actual:   False

Stack trace
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 984
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201025.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=865290&view=ms.vss-test-web.build-test-results-tab&runId=27710548&paneView=debug&resultId=100049)

failed test: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Could not start C:\Users\ContainerAdministrator\AppData\Local\Temp\ProcessStartInfoTests_kwazcwda.oda\StartInfo_TextFile_ShellExecute_972_0738839a.txt UseShellExecute=True
Association details for '.txt'
------------------------------
Open command: C:\Windows\system32\NOTEPAD.EXE %1
ProgID: txtfile

Expected: True
Actual:   False


Stack trace
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 984
~~~

**Comment by danmosemsft** [comment]
@v-haren did the build of Windows change here recently do you know? Also, is it passing on other Windows queues?

**Comment by v-haren** [comment]
Sorry, I'm not sure about that

**Comment by danmosemsft** [comment]
Closing as I don't think there is any action we would realistically take here.
