### ISSUE TITLE
Add Complete and TryComplete methods to the System.Threading.Channels.ChannelReader

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/runtime#26235]
The problem:
When consuming processing block has been stopped(due some error for example) and does not pulling ChannelReader the producing block does not know about that and still produces items and writes them into the ChannelWriter.

Producer ---> ChannelWriter==>Channel==>ChannelReader--X-->Consumer

```CSharp
public Task DoReading(ChannelReader<MyItem> reader)
{
    try
    {
        while(true)
        {
            // Do processing
        }
    }
    catch(Exception ex)
    {
        // Some how notify producer to stop, may be due to error.
    }
}
```

The solution:
Add symmetric methods like ChannelWriter.Complete and ChannelWriter.TryComplete
```CSharp
public class ChannelReader<T>
{
    // ...
    public abstract bool TryComplete(Exception error = null);
    public abstract void Complete(Exception error =null);
    // ...
}

public class ChannelWriter<T>
{
     // Completes when ChannelReader.Complete or ChannelReader.TryComplete is called.
     public abstract Task ReadCompletion { get; }
}
```
Items that are stored in the channel should be able to read even after Complete or TryComplete has been called.

With that feature large processing graphs can be organized many times simpler.

**Comment by stephentoub** [comment]
Given the discussion that took place previously, and that there hasn't been additional interest expressed in several years, I'm going to close this.  Thanks.
