### ISSUE TITLE
Debian Packages Strip Symbols from Shared Object Files

### ISSUE THREAD

**Issue by brianrob** [dotnet/runtime#2624]
The process of producing the .deb package files strips symbols out of the .so files.  However, we explicitly include function-level symbols in native binaries for use during performance tracing.  tar.gz files are unaffected.

## Steps to reproduce
1. Install the .deb files for the shared framework for any of the Ubuntu distros either directly or via apt-get.
2. Run nm </path/to/libcoreclr.so>

## Expected  behavior
Function-level symbols are displayed.

## Actual behavior
No symbols are displayed.

## Environment data

**Comment by NikolaMilosavljevic** [comment]
@brianrob is this still an issue for perf tracing or do you utilize a workaround? Is this needed for 5.0?

**Comment by brianrob** [comment]
@NikolaMilosavljevic I think its safe to close this now.  We have a tool for downloading symbols now.  Thanks.
