### ISSUE TITLE
Enable "Hacking Mode" for host

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/runtime#2625]
It would be really nice to be able to set something that would allow an application to load even if files in its deps file aren't present. In this mode, I would also like to be able to drop additional dll's in my app and have them be allowed to load.

**Comment by vitek-karas** [comment]
This can be done with .NET 8 (at least mostly):
* The host doesn't perform file existence checks anymore for assets listed in `.deps.json` - we did this for performance reasons mostly, but side effect is that the app will start with missing files and might run just fine it they're never requested. (They are still listed in TPA and such)
* You can add runtime property `Microsoft.NETCore.DotNetHostPolicy.SetAppPaths` and set it to `true` - this will make the host add the app's directory into the list of probe paths used by the runtime - which will effectively mean that the runtime will be able to resolve assemblies from the app's directory even if they're not listed in `.desp.json` - this is an "obsolete" feature which we maintain for backward compat, but ideally should not be used.
* If you omit `.deps.json` from the app, then you can put any dlls into the app directory and the host will simply list all the files there.
