### ISSUE TITLE
MemoryManager<T>.Dispose() is not public

### ISSUE THREAD

**Issue by aalmada** [dotnet/runtime#26262]
MemoryManager<T> implements IDisposable explicitly. It passes all the unit tests as these use the pattern: ` using (manager = new CustomMemoryForTest<int>(a)) { ... }`
The issue is that if I create the manager in one method and want to dispose later, I have to cast it first: `((IDisposable)manager).Dispose();`

**Comment by stephentoub** [comment]
Given @GrabYourPitchforks's comments, and that this issue has been open now for almost four years and garnered little visible interest, and this is a very niche area, and this would only save a cast, I'm going to close it.  Thanks for the suggestion.
