### ISSUE TITLE
Add overload of StreamReader.ReadLine() to include line endings

### ISSUE THREAD

**Issue by dfoverdx** [dotnet/runtime#26296]
I'm writing code that parses a file which has mixed line endings--`\n` and `\r\n`. New lines within quoted strings use `\n`, while new lines out of strings use `\r\n`. For simplicity, I would like to use `StreamReader.ReadLine()` rather than implementing my own method using a buffer, but I need to preserve the line endings from the file. As far as I know, it is not currently possible to detect which line ending was read when using `StreamReader.ReadLine()`.

**Comment by melanchall** [comment]
I want this feature too. I'm writing CSV parser using `StreamReader` and can't get exact line ending when CSV value includes `\r` or `\n` or both.

**Comment by carlossanlop** [comment]
@dfoverdx @melanchall here are the instructions for requesting the addition of a new API: https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md . Let me know if you have any questions.

**Comment by melanchall** [comment]
@carlossanlop Thanks for link! I have a question.

In the doc you've provided the first step states that issue should be created under **dotnet/corefx**. I see that current issue was transferred for some reason from **corefx**. Should we create new one under **corefx** with detailed description or continue with this issue?

**Comment by carlossanlop** [comment]
@melanchall use the dotnet/runtime repo. Don't use the corefx repo anymore.

We recently migrated to runtime, but some documents like this one have not been updated to reflect that. Thanks for pointing it out.

**Comment by melanchall** [comment]
@carlossanlop Thanks.

So should a new issue be created or we can proceed with this one?

**Comment by carlossanlop** [comment]
Either way is fine, your choice.
If you decide to reuse this issue, add your API Proposal in a new comment, and make sure to edit the main issue description to add a link to your proposal comment, so people can jump to it quickly. This is the most common way.
If you decide to open a new issue, make sure to mark this as duplicate and close it. This way is a bit cleaner.

**Comment by melanchall** [comment]
It's not my issue so I can't edit comments of other users. If I create new issue, will you be able to mark this as duplicate?

**Comment by carlossanlop** [comment]
@melanchall yes, I can close this as duplicate for you.

**Comment by melanchall** [comment]
@carlossanlop I've created the issue #32128. Please close this one as duplicate.
