### ISSUE TITLE
API Proposal: Public interface ISpanFormattable

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/runtime#26374]
@davidfowl  suggested in dotnet/runtime#26373 that I make a formal proposal.
**Motivation**
There is an internal interface ``ISpanFormattable``
The only member is:
https://github.com/dotnet/corefx/blob/d7f120a01ac6ea09a2139c99e43d7811950d2f73/src/Common/src/CoreLib/System/ISpanFormattable.cs#L9

This interface is the ``Span`` version of ``IFormattable`` and is implemented by many of the primitive types to allow formatting into a ``Span``. It would be useful make this interface public for users wanting to use ``TryFormat`` with these types or implement their own formatting methods for ``Span``.

Example:
The Utf8Formatter for float currently is using ToString() to format float/double
https://github.com/dotnet/corefx/blob/d7f120a01ac6ea09a2139c99e43d7811950d2f73/src/System.Memory/src/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Float.cs#L68

If the interface would be public it could replace the type constraint ``IFormattable`` in the method above and it would be possible to optimize the allocations in the method above, by using stackalloc and ``TryFormat``. As double/float formatting is a complex process the utf8 version formats the value into a string and then copies the ascii characters into the utf8 byte array.

**Alternatives**
@davidfowl  pointed out, that it could be possible to make the interface generic, e.g. ``ISpanFormattable<T>`` with ``ISpanFormattable<char>`` and ``ISpanFormattable<byte>``
This would add quite a bit of additional work, e.g. moving pretty much everything from Utf8Formatter into the relevant types and/or writing new formatter methods. This idea is currently not in my scope, it might be interesting to revisit the idea after ``Utf8String`` is finished.
Having a public generic interface where ``char`` and ``byte`` (and maybe ``uint`` for UTF32) are the only ``valid`` type constraints is a bit weird imho, this might change with future constraint possibilities.

**Intended Audience**
- Everyone formatting values to ``Span``, e.g. serializers, logging libraries etc.

**Open points**
- How to get the interface into System.Memory, do a conditional include for netstandard and type-forward for netcoreapp work?

**Comment by Gnbrkm41** [comment]
I opened an issue some time ago about adding TryFormat to IFormattable as a DIM (https://github.com/dotnet/runtime/issues/30547). I *personally* think that it wouldn't be too bad if we were to have it as part of the existing interface as behaviourally they do the same thing.

**Comment by TylerBrinkley** [comment]
Has this been API reviewed? Where are the comments regarding that and the update to the labels?

**Comment by davidfowl** [comment]
https://github.com/dotnet/runtime/issues/50601
