### ISSUE TITLE
Microsoft.Extensions.DependencyModel and plugin based applications

### ISSUE THREAD

**Issue by gokarnm** [dotnet/runtime#2643]
Microsoft.Extensions.DependencyModel package which contains classes read deps files and provides list of dependencies, depends on internal mechanisms that make it difficult to use this package in a plugin based application. 
I'm have a host application that loads one or more plugins. Each plugin is loaded from a different base directory that contains the plugin DLL and plugin deps.json file. Each plugin runs in a custom AssemblyLoadContext(ALC).

Microsoft.Extensions.DependencyModel contains classes that depend on the values passed to the .NET hosting API using the [APP_CONTEXT_BASE_DIRECTORY](https://github.com/dotnet/core-setup/blob/a3aa7554141425971e82fb3e75d2431b3604a101/src/corehost/cli/hostpolicy.cpp#L74) and APP_CONTEXT_DEPS_FILES parameters. Here are the classes where this data is used.

1. [AppContext.BaseDirectory](https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/AppContext/AppContext.cs#L38) returns the APP_CONTEXT_BASE_DIRECTORY hosting API parameter. AppContext.BaseDirectory is used by [ApplicationEnvironment.GetApplicationBasePath()](https://github.com/dotnet/core-setup/blob/afdc2ba4a62c860ac62265f8fc64081d465dc725/src/Microsoft.DotNet.PlatformAbstractions/ApplicationEnvironment.cs#L20)

1. [DependencyContextPaths.Application](https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/src/Microsoft.Extensions.DependencyModel/DependencyContextPaths.cs#L7) and DependencyContextPaths.SharedRuntime properties return paths to application and shared runtime deps file from the APP_CONTEXT_DEPS_FILES hosting API parameter. DependencyContextPaths is used by [DependencyContextLoader](https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/src/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L22) and there is no way to customize the paths it uses.

An example is, MVC uses DependencyContext class from Microsoft.Extensions.DependencyModel package extensively and it breaks when the MVC engine is run inside a plugin. It breaks because the base directory and deps files for the host application is picked up instead of the plugin's base directory and deps file.

Is there a way to support Microsoft.Extensions.DependencyModel in a plugin based application as described above, so that I can get list of dependencies for each plugin?

**Comment by eerhardt** [comment]
In .NET Core 3 we've added a few APIs to support plugin based applications. Check out https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support.

For the DependencyModel, if you know the plug-in assembly, you can get a DependencyContext for that assembly by calling `DependencyContext.Load(Assembly)`. If the `.deps.json` file exists next to that Assembly, it will read the `.deps.json` file for that assembly.

I'm closing this issue since it is quite old, but if there are more questions feel free to re-open or log a new issue.
