### ISSUE TITLE
Allow narrow scope of correlation context collection in DiagnosticSource Activity

### ISSUE THREAD

**Issue by SergeyKanzhelev** [dotnet/runtime#26465]
## Motivation

ASP.NET applications support correlation context propagation. Correlation context is a collection of name/value pairs used to enrich distributed tracing telemetry. App author can add new name/value pair in a service and this pair will be available in every dependent service. For instance, user-facing frontend service that implements an A/B testing experiment can set a `flight-id` parameter in correlation context of a distributed trace. And this parameter will be available in business logic and API gateway services. So any failed call to API can be attributed with the original `flight-id`. This way flights can be easily compared be reliability and performance.

We found it highly inconvenient that correlation context API only supports adding properties and doesn't support mutating of them. Original idea was that correlation context is append-only collection that scoped to the entire distributed trace, but we found use cases when one distributed trace can fork into sub-traces. Each with it's own set of correlation context name/value pairs.

What we need:
    - Ability to set a tags and baggage for individual Activity
    - Set different baggage for different children of Activity
    - Set baggage and tags for automatically-tracked Activities
    - Same tags and baggage can be used for metrics and logs
    - Ability to remove tags from the context

CC: @seth-capistron, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl

## Proposed API

New class representing the scope can define `Tags` and `Baggage` name/value pairs. Those tags and baggage items will be applied to every Activity tracked inside this scope. 

API is separate from the Current "Activity" as we need to allow single Activity to "parent" multiple parallel scopes with the different settings. Removal of the `Tags` and `Baggage` items cannot be made via scoping API.

``` csharp
namespace System.Diagnostics
{
    public class Activity
    {
        public class Scope
        {
            public Scope(ICollection<KeyValuePair<string, string>> tags, ICollection<KeyValuePair<string, string>> baggage);

            public ICollection<KeyValuePair<string, string>> Tags { get; }
            public ICollection<KeyValuePair<string, string>> Baggage { get; }
        }

        ...
        // <summary>
        // </summary>
        public static IDisposable BeginScope(Scope scope);
        ...
    }
}
```

## Usage

``` csharp
DiagnosticListener httpListener = new DiagnosticListener("listener");

Activity activity = new Activity("Main Activity");
activity.SetParentId("parent");
foreach (var pair in new Dictionary<string, string>() { { "key1", "value1" }, { "key2", "value2" } })
{
    activity.AddBaggage(pair.Key, pair.Value);
}
httpListener.StartActivity(activity, new object());

try
{
    using (var scope = Activity.BeginScope(new Scope({ { "tagName1", "tagValue1" } }, { "plugin-name", "first plugin"})))
    {

        Activity activity1 = new Activity("First dependency");
        httpListener.StartActivity(activity, new object());

        // Activity.Current returns Tags "tagName2" 
        // and Baggage with the key "plugin-name" and value "second plugin"

        httpListener.StopActivity(activity, new object());
    }


    using (var scope = Activity.BeginScope(new Scope({ { "tagName2", "tagValue2" } }, { "plugin-name", "second plugin"})))
    {
        Activity activity2 = new Activity("Second dependency");
        httpListener.StartActivity(activity, new object());

        // Activity.Current returns Tags "tagName2" 
        // and Baggage with the key "plugin-name" and value "second plugin"

        httpListener.StopActivity(activity, new object());
    }
}
finally
{
    //stop activity
    httpListener.StopActivity(activity, new object());
}
```

**Comment by tarekgh** [comment]
I am closing this as we have a different discussions to support OTel Baggage. 

CC @noahfalk
