### ISSUE TITLE
PrivateFontCollection not working in Linux

### ISSUE THREAD

**Issue by bbrewder** [dotnet/runtime#26460]
I've created a .Net Core 2.1 app that I want to run on Linux that creates a graphic with text rendered using a custom font (.ttf). 

This attached file contains the code necessary to use `dotnet run` (CustomFonts.csproj, Program.cs, and Drift.ttf). The font is just a random TTF font I found that is easy to recognize as something other than a system installed font.

[CustomFonts.zip](https://github.com/dotnet/corefx/files/2094927/CustomFonts.zip)
```c#
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        using (var customFamilies = new PrivateFontCollection())
        {
            customFamilies.AddFontFile("Drift.ttf");
            var family = customFamilies.Families[0];

            //using (var family = new FontFamily("Drift Wood", customFamilies))
            using (var myfont = new Font(family, 40, FontStyle.Regular, GraphicsUnit.Point))
            using (var bmp = new Bitmap(500, 500))
            using (var g = Graphics.FromImage(bmp))
            {
                g.FillRectangle(Brushes.White, 0, 0, bmp.Width, bmp.Height);

                // Make sure we can use the font.
                g.DrawString("Linux Test!", myfont, Brushes.Black, 10, 10);

                var path = "Test.bmp";
                bmp.Save(path, ImageFormat.Bmp);
                Console.WriteLine($"Saved to: {Path.GetFullPath(path)}");
            }
        }
    }
}
```

When the app runs on Windows, the custom font is used as expected.

For Linux (Ubuntu 16.04 subsystem on Windows), the code runs without errors (once you get the required Linux libraries installed anyway), but it doesn't use the custom font. I assume the font that is actually used is just the default font for Linux. 

I've tried adding the font as both a file and a memory font and get the same result.

I am pretty much a Linux newb (just installed yesterday, haven't used Linux in years), so it's certainly possible that I'm doing something wrong (perhaps I don't have some required library installed or something). It would be great if the code could be made to work as-is on Linux, but if that's not possible, a work-around would be appreciated.

**Comment by elzero** [comment]
3.1 there is still the same problem, when can it be fixed?

**Comment by IshmaZX82** [comment]
The text measuring also not working with these fonts .....

**Comment by deremakif** [comment]
Same issue!

**Comment by llorch19** [comment]
Same issue! Linux's PrivateFontCollection doesn't behave as Microsoft Windows'.

**Comment by evilpilaf** [comment]
Same issue, any workaround?

**Comment by sstraus** [comment]
Workaround for Azure App Service?

**Comment by ol2dd** [comment]
Same issue

**Comment by guygreenleaf** [comment]
Same issue! 10 hours of looking for why fonts weren't loading into devexpress led me here!

**Comment by sunilshahi** [comment]
Same issue here.

**Comment by anitsh** [comment]
**Issue still persists.**


.NET Core Version =  7.0.0
Operating System =  Ubuntu 20.04.5 LTS
System.Drawing.Common Version= 7.0.0


Exception Thrown = Unhandled exception. System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.


This is disappointing. I was migrating ASP.NET MVC to Core and in the got stuck with this.

Any fix or work around hint would be much appriciated.

Thank you.

**Comment by ViktorHofer** [comment]
As already noted, System.Drawing.Common is only supported on Windows starting with .NET 6. See https://github.com/dotnet/announcements/issues/228 for more details. Closing the issue as by design. Feel free to file a new issue if you want to discuss this further.
