### ISSUE TITLE
ApiCompat does not compare implementations to netstandard when a more specific ref is present

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#26485]
Issue dotnet/runtime#26484 was caused by the netfx build of System.Security.Cryptography.Pkcs running ApiCompat against the netfx ref for System.Security.Cryptography.Pkcs.  Both of those libraries have System.Security.Cryptography.Pkcs.CmsSigner as a type-forward to System.Security.dll.  There doesn't seem to be any portion of a build which compared the netfx build to the netstandard ref.  It seems similarly possible that when a netcoreapp and a netstandard ref are both present for a library that the netcoreapp implementation will only compare against the netcoreapp ref.  If the netstandard ref happened to be contradictory nothing would seem to notice.

It's probably sufficient for the ApiCompat task to compare "most specific" and "netstandard"; though perhaps a more generalized "all applicable RIDs" is warranted.

cc @weshaggard

**Comment by wtgodbe** [comment]
CC@dougbu in case this is relevant to what you were discussing in standup today

**Comment by wtgodbe** [comment]
CC @dougbu in case this is relevant to what you were discussing in standup today

**Comment by dougbu** [comment]
@wtgodbe I doubt the two conversations overlap much. The above is about what compatibility checks are done. My comments earlier today were about odd ApiCompat errors we've seen (perhaps doing checks that don't work so well).

**Comment by ViktorHofer** [comment]
cc @Anipik and @safern as this might be interesting for the package validation and api compat feature work.

**Comment by ViktorHofer** [comment]
Closing as we now have full coverage based on the tools that we use:
- If the library is packable, APICompat's PackageValidation compares contract and implementation assemblies with each other.
- If the library is non-packable then there's only a single target framework exposed in the contract, which is `$(NetCoreAppCurrent)`. In the future we might want to add a similar heuristic to ApiCompat when inspecting non-packable projects, to what PackageValidation already provides for packages.
