### ISSUE TITLE
Use Func<T1, T2> instead of IComparer and Comparison<T>

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#26523]
When we compare two objects, we need to write a custom comparer. In most cases, its only job is to determine which property of the object is used for comparison. I think this can be simplified by using methods that accept Func<T1, T2> param instead of a full comparer. Func<T1, T2> receives the object and returns the value of the property we want to use in comparison. For example, if we want to sort an array of students based on their IDs:
```
Strudent[] A = ….. ;
Array.Sort(A, (std) => std.ID);
```

Sort Method will pass each element to the Func<Student, int> to get the value of its ID then use it in comparisons needed for the sort.
Likewise, if we want to sort them by name:

```
Array.Sort(A, (std) => std.Name);
```

So, Sort Method is defined like this:
```
public static void Sort<T1, T2> 
(Array A, Func<T1, T2> ValueToCompare) 
where T2 : IComparable
{
   Array.Sort<T1>(A, (x, y) => ValueToCompare(x).CompareTo(ValueToCompare(y)));
}
```

So, my suggestion is to add a new overload to each method in framework that accepts custom comparer as a param, where the new overload accepts Func<T1, T2> as a param.

**Comment by stephentoub** [comment]
The original poster of this issue deleted their account and is now a "ghost", so I'm going to close this issue.  Thanks.
