### ISSUE TITLE
Feature Request: IParseable<T> interface for all types implementing Parse() and TryParse()

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/runtime#26538]
It would be nice if there was an `IParseable<T>` interface providing `static T Parse(string toParse)` and `static bool TryParse(string toParse, out T val)`
Optionally there could be `IFormattableParseable<T> :  IParseable<T>, IFormattable` providing `static T Parse(string toParse, IFormatProvider provider)` and  `static bool TryParse(string toParse, IFormatProvider provider, out T val)` . 
The  IParseable<T> interface should be implemented by all types providing the Parse() and TryParse() method, IFormattableParseable<T> should be implemented by all types additionally implementing IFormattable. T should always be the type itself.

**Comment by hrrrrustic** [comment]
I guess this one should be closed since we have [`IParseable<TSelf>`](https://source.dot.net/#System.Private.CoreLib/IParseable.cs,16) in generic math

**Comment by TheMinefighter** [comment]
Yes, I also think we can close this. IDK why MS didn't do this while implementing the Interface mentioned above. Feature Request Tracking seems to be a challenge.
