### ISSUE TITLE
Bring back dependency model funtional tests

### ISSUE THREAD

**Issue by pakrym** [dotnet/runtime#2654]
They got lost during CLI - core-setup migration:

https://github.com/dotnet/cli/commit/ee1474c161f6c862ebfaa31506840cbbc449b1ac#diff-f2e26b66d6ee9d609fe65e5877080cf4 

https://github.com/dotnet/core-setup/commit/e416af6140697699d9d6533e1f534faf22d7770a#diff-f2e26b66d6ee9d609fe65e5877080cf4

There were also couple test projects that were in `/TestAssets/DependencyContextValidator` directory but I can't find when they were removed.

/cc @eerhardt

**Comment by eerhardt** [comment]
Closing. These tests are not necessary. We've shipped multiple versions without them.
