### ISSUE TITLE
Crypto interop needs to be consolidated under src\Common\src\Interop\

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#26541]
There is duplication we really want to avoid.  For example, CertNameToStr is used by both System.Security.Cryptography.X509Certificates and by System.Security.Cryptography.Pkcs, and they both contain their own copies of DllImports and higher-level helpers on top of them.

cc: @bartonjs

**Comment by bartonjs** [comment]
A current scan for `LibraryImport` or `DllImport` in the cryptography projects shows nothing outside of src\Common\src\Interop (for product code, tests have a couple)
