### ISSUE TITLE
Different AssemblyVersions of target DLLs in NuGet package System.Reflection.DispatchProxy 4.5.1

### ISSUE THREAD

**Issue by channeladam** [dotnet/runtime#26595]
Should the AssemblyVersions be different for the different target DLLs in the NuGet package System.Reflection.DispatchProxy 4.5.1 ?

For example:
- lib\net461\System.Reflection.DispatchProxy.dll has an AssemblyVersion of "4.0.4.0".
- lib\netstandard2.0\System.Reflection.DispatchProxy.dll has an AssemblyVersion of "4.0.4.0".

BUT
- lib\netstandard1.3\System.Reflection.DispatchProxy.dll has an AssemblyVersion of "4.0.2.0".

This causes the following error when in a solution where a .NET 4.7.2 automated test project is referencing a .NET Standard 1.3 library. 

`System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.DispatchProxy, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I have worked around the problem by adding an assembly binding redirect... but not sure I should have had to...
`      <dependentAssembly>
        <assemblyIdentity name="System.Reflection.DispatchProxy" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.4.0" newVersion="4.0.4.0" />
      </dependentAssembly>`

**Comment by danmosemsft** [comment]
Seems resolved.
