### ISSUE TITLE
MemoryMappedFile.CreateFromFile constraints on Unix should be loosened to support IFCHR

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#26626]
MemoryMappedFile.CreateFromFile enforces a variety of constraints about the target file.  Those constraints make sense when working with disk-based files, but they don't all make sense when working with special files.  For example, it should be possible to create a map for /dev/mem, but such a special file has zero length, which causes a bunch of the checks in both MemoryMappedFile and MemoryMappedView to fail.

**Comment by hopix** [comment]
@wurf 
> It would be great to do some verification with GPIO or some other HW.

When fix will be available I could do some test on my ARM device. Then hope to back port it to my [.net 3.1 fork for linux-arm-vfpv3-d16](https://github.com/hopix/coreclr/commits/3.1-linux-arm-vfpv3-d16)

**Comment by wfurt** [comment]
closed by #2183
