### ISSUE TITLE
API proposal: bitwise operations on Span(of byte) buffers

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#26651]
Currently we have some bitwise operators for the `Vector<T>` type. It would be useful for some scenarios (especially cryptography, where xoring two long buffers is common) to extend these bitwise operators to arbitrary-length spans.

A strawman API follows.

```cs
namespace System.Buffers {
    public static class Span {
        public static void And(ReadOnlySpan<byte> a, ReadOnlySpan<byte> b, Span<byte> output);
        public static void AndNot(ReadOnlySpan<byte> a, ReadOnlySpan<byte> b, Span<byte> output);
        public static void Not(ReadOnlySpan<byte> input, Span<byte> output);
        public static void Or(ReadOnlySpan<byte> a, ReadOnlySpan<byte> b, Span<byte> output);
        public static void Xor(ReadOnlySpan<byte> a, ReadOnlySpan<byte> b, Span<byte> output);
    }
}
```

Since these are all _bitwise_ operations, they operate on a bit-by-bit level. (This means that `Not` is actually the bitwise inverse operation.)

If we had a `T : numeric` constraint, we could use that and have generic `Span<T>` overloads instead of simply `Span<byte>`. I don't think it would be good to have a broad `T : struct` constraint because it's not valid to perform bitwise operations over arbitrary structs, even if those structs don't contain references.

Proposed behaviors: The input length(s) must match the output length _exactly_, otherwise an exception is thrown. It should also be possible to pass one of the input buffers as the destination buffer as long as the buffers overlap _exactly_. Passing an output buffer that _partially_ overlaps with one of the input buffers will have undefined behavior.

The implementations can take advantage of vectorization or hardware intrinsics when available. But the APIs should be able to accept inputs of arbitrary length, even if the length isn't an exact multiple of the platform's native SIMD size.

**Comment by tannergooding** [comment]
Worth noting that most elsewhere we've exposed `Not` as `OnesComplement`.

Its typically been: `BitwiseAnd`, `BitwiseOr`, `AndNot`, `OnesComplement`, `Xor`. It's definitely not the most consistent overall, however.

**Comment by stephentoub** [comment]
These are now available on TensorPrimitives.
