### ISSUE TITLE
EventCounter should have option to pass additional payload data

### ISSUE THREAD

**Issue by Expecho** [dotnet/runtime#26727]
Would it be possible to extend [`EventCounter`](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/src/System/Diagnostics/Tracing/EventCounter.cs) in such a way that additional payload values are supported?

Context: I am working with Azure Service Fabric where I have the need to use EventCounter to log some metrics. Those metrics are bound to a specific partition Id. Currently there is no way to identify an EventCounter other than by name, which (afiak) must be known/set when the `EventSource` is constructed.

Initially I tried to circumvent this limitations by generating a dynamic name like this:

```csharp
[EventSource(Name = "Test")]
public class ServiceEventSource : EventSource
{
	public static ServiceEventSource Log = new ServiceEventSource();
	private Dictionary<string, EventCounter> counters = new Dictionary<string, EventCounter>();
	
	private ServiceEventSource()
	{

	}

	[NonEvent]
	public void Invocations(int count, Guid partitionId)
	{
		var name = $"invocations-{partitionId}";
		EventCounter counter;
		if (!counters.TryGetValue(name, out counter))
		{
			counter = new EventCounter(name, this);
			counters.Add(name, counter);
		}
		counter.WriteMetric(count);
	}
}
```

but that does not work. I guess the EventCounter needs to be created in the constructor of the `EventSource`. Event if it would work it would at best be a workaround since the name property should not be used for these kind of things. So it would be really great if I could instead do this in my `EventSource`:

```csharp
counter.WriteMetric(count, partitionId);
```

What do you think?

**Comment by joacar** [comment]
Hi,

I'm trying to create counters dynamically and it works all though I'm not sure it's the recommended approach. The upper limit of http clients (see zip) is bounded by 50. 

The gist of my solution:
1. Create DiagnosticListener and listen to `System.Net.Http.RequestOut.Start` and `Stop`
1. A static instance of EventSource that has a `ConcurrentDictionary` to keep a metric for each http client making a request on `RequestStart` and `RequestStop`.

I loaded the .trace file into perfiew and can't see the formatted message. Read some article on MSDN that the number of arguments sent to method should be sent in the same order to `WriteEvent` for it to work. Thing is, I don't use raw `EventCounter` instead I rely on `PollingCounter` et al.

Thanks

[WebApplication1.zip](https://github.com/dotnet/runtime/files/4257005/WebApplication1.zip)

**Comment by noahfalk** [comment]
@joacar - it wasn't clear if the issue you were reporting was the same or different from the one here so I opened issue #32877 to track it independently.

**Comment by joacar** [comment]
Hi @noahfalk, Sorry for not expression my question clearly, which isn’t really a question more seeking guidance in for me unexplored land (eventing). The code is provided to showcase current solution and get some feedback on the implementation and show my use case. So that “question” belongs in this thread and the other correctly moved. I’ll provide some screenshots to that tomorrow as well as code snippet.
Thanks
