### ISSUE TITLE
Support generating random 64-bit values.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#26741]
### Rationale

It is sometimes desirable to generate random numbers as inputs to tests. This works nicely for the majority of the primitive types, but not for `long`/`ulong`.

As such, I propose a method be exposed that allows the generation of random 64-bit integer values.

### Proposed API
```C#
public class Random
{
    public virtual long NextInt64();
    public virtual long NextInt64(long maxValue);
    public virtual long NextInt64(long minValue, long maxValue);
}
```

**Comment by joperezr** [comment]
@tannergooding I believe this looks ready to review, so feel free to flag it as such, unless @stephentoub's concern above makes this not viable.

**Comment by Symbai** [comment]
Any update on this? I was about to request the same APIs before I saw this old discussion.

**Comment by colgreen** [comment]
> Any update on this? I was about to request the same APIs (edit: and an API for `ulong` as well) before I saw this old discussion.

Feel free to use https://www.nuget.org/packages/Redzen/ in the meantime :)

**Comment by danmosemsft** [comment]
Building on @colgreen comments, perhaps we could use this as an opportunity to offer a better PRNG just for the 64-bit API. It would probably be odd to have to generators in the same type, but perhaps it could be a derived class ie
```c#
public class Random64 : Random
{
    public virtual long NextInt64();
    public virtual long NextInt64(long maxValue);
    public virtual long NextInt64(long minValue, long maxValue);
}
```
We could use the opportunity to override Next, NextBytes, etc and implement them with the same improved PRNG.

**Comment by terrajobst** [comment]
* Makes sense
* Let's also add `NextSingle()`

```C#
namespace System
{
    public class Random
    {
        public virtual long NextInt64();
        public virtual long NextInt64(long maxValue);
        public virtual long NextInt64(long minValue, long maxValue);
        public virtual long NextSingle();
    }
}
```

**Comment by danmosemsft** [comment]
@tannergooding @GrabYourPitchforks did we resolve the question of whether the 64 bit values could use a "better" PRNG? There is no back compat burden on these new API's, and they could use the same seed value as determined today (which is not perfect as after using hardware entropy, if unspecified it will use regular r.NextInt -- but that could be changed without a break, as well). The only drawback would be two codepaths in Random - which is a small burden on us, only.

**Comment by stephentoub** [comment]
@tannergooding, @GrabYourPitchforks, any progress on how this should be implemented?  https://github.com/dotnet/runtime/pull/46890/commits/f56fe491785d48dffe5aea82043a112bb473d228 is attempting to add a custom 64-bit generator, based on changing the 32-bit one to 64-bit, and that doesn't seem like a good path.

**Comment by colgreen** [comment]
I will describe the approach I took in Redzen (my own little side project and nuget package) - just as food for thought really.

All code is here: https://github.com/colgreen/Redzen/tree/master/Redzen/Random

I defined an interface `IRandomSource` that more or less mirrors the API of `System.Random`, but with updates/additions, so e.g. there exist methods `Next()`, `Next(int)`, `NextBytes(Span<byte>)`, etc.

There are multiple implementations of that interface, each named after a specific PRNG algorithm/method, e.g. `Xoshiro256StarStarRandom.cs is` one of the current PRNGs published by David Blackman and Sebastiano Vigna. There is also a legacy PRNG in there for backwards compatibility reasons - as that was originally the only PRNG in the redzen library.

The next layer is a static class `RandomDefaults` which has these static methods:

```
public static IRandomSource CreateRandomSource()
public static IRandomSource CreateRandomSource(ulong seed)
```

Hence, as owner of the library, I have chosen what I think is a good default PRNG right now, and will construct instances of it behind those general purpose static methods. A user of the lib can choose to use those methods (trust my choice of PRNG), or construct a specific PRNG class directly.

In future I may add new PRNGs and change the default PRNG behind those static methods, e.g. there's a reasonable chance I will switch to wyrand/wyhash at some point (see https://github.com/colgreen/Redzen/issues/10)

The point being that non-crypto PRNGs are an area of ongoing research, so it's good to acknowledge this in the design of the library and API. I.e. whatever PRNG we choose today may not be desirable in the future.

With regards to 64bit random generation, the redzen PRNGs are all fundamentally 64 bit under the hood, and any methods that require less bits just take the high bits they need (for many PRNGs the high bits are higher quality randomness). And for e.g. wyrand, I think it can use CPU intrinsics in some way to greatly improve performance for 'chunks' of 64 bits.

**Comment by tannergooding** [comment]
> any progress on how this should be implemented? f56fe49 is attempting to add a custom 64-bit generator, based on changing the 32-bit one to 64-bit, and that doesn't seem like a good path.

Assuming we are confident that `InternalSample()` is producing 32 random bits, then I think we are fine with just getting two `int` and combining them for `long NextInt64()`.

For `long NextInt64(long maxValue)`, I think we need to create a new `GetSampleForLargeRange()`. This is because while `double` is 64-bits, the returned sample is effectively between `0.0` and `1.0` which is only `0x3FF0000000000000` unique values (and with those values impacting scaling in various interesting ways given they themselves aren't evenly distributed.

**Comment by stephentoub** [comment]
> Assuming we are confident that InternalSample() is producing 32 random bits, then I think we are fine with just getting two int and combining them for long NextInt64().

If I'm understanding the current implementation correctly, I think it's producing 31 bits... ish, in that it's producing a value in the range [0, int.MaxValue).

**Comment by GrabYourPitchforks** [comment]
IMO, @stephentoub's latest PR hits the right notes. Provide the option to do a better thing (with no concrete implementation details promised) in the common case of the parameterless ctor being called. And if a seed is provided, the results are still repeatable, even for calls to the new _NextInt64_ API.

Since it also seems that our stance is that calling the parameterless ctor is not guaranteed to result in any particular implementation and is not guaranteed to be repeatable, this also puts to rest once and for all that we're not going to mark this type `[Serializable]`.
