### ISSUE TITLE
Proposal, async, await, promise, holistic, language improvement tweak, with idea of were Javascript, TypeScript, nodeJS, c# have and are heading, to simplify things

### ISSUE THREAD

**Issue by wesleyolis** [dotnet/runtime#26757]
Hi,

I feel that it would be a good thing that dotnet be aware of this proposal that will affect both typescript and javascript in the future as they may want to contribute at a technical level to any insight they may have, because this has been done with a focus on the bigger picture of all languages, however, small the little roll they play, it also suggestions that c# may follow suit with this proposal.

tc39/ecma262#1258

Document:

https://docs.google.com/document/d/1QigfqvlM2vMNl-4szjuPj9tFXIQle2zsbrsnze9bAIU/edit?usp=sharing

**Comment by stephentoub** [comment]
I'm going to close this as non-actionable. If/when the issues can be distilled into something concrete, new issues should be opened. Thanks.
