### ISSUE TITLE
Freeze netstandard refs that have a package and are inbox

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#26758]
We don't want to accidently ship new APIs in a netstandard ref in a package that is already inbox on any platform. We should harvest those configurations and if they are referenced by other contracts we should also binplace them into the ref folder by adding a PackageReference here: https://github.com/dotnet/corefx/blob/master/external/netstandard/netstandard.depproj#L15.

When doing this we should also consider harvesting the impl but this needs to be considered project-wise. Freezing could also be interpreted as removing if there are no live assets going into the package.

cc @weshaggard @ericstj

**Comment by ericstj** [comment]
These have all been removed.
