### ISSUE TITLE
Are synchronous Sockets thread-safe?

### ISSUE THREAD

**Issue by AnthonySteele** [dotnet/runtime#26843]
Are the `Socket` methods `Send` or `SendTo` thread-safe?  i.e. can they be used in a re-entrant manner similar to `HttpClient.SendAsync` and co?

Our use is for StatsD, sending data over Ip or Udp, in order to to send multiple messages to the same server.

If yes it is thread-safe, then the docs don't mention that, and they should.
If not, then we could also use a fast thread-safe socket pool instead as per dotnet/runtime#26287

**Comment by antonfirsov** [comment]
>  i.e. can they be used in a re-entrant manner similar to `HttpClient.SendAsync` and co

@geoffkizer isn't this kind of re-entrance that you are suggesting to remove as part of  #24138 ? Or am I confusing things?

**Comment by geoffkizer** [comment]
No, #24138 is unrelated.

**Comment by wfurt** [comment]
triage: we should document current behavior. It seems like we have some gaps e.g. some operations are safe and some are not.
