### ISSUE TITLE
Port remainder of Microsoft.VisualBasic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#26866]
This tracks porting to .NET Core the rest of the types in Microsoft.VisualBasic, now that we've published the original sources.

Contributions are welcome! The porting process is essentially

1. Pick some types.
1. Get the original .NET Framework code from [referencesource](https://github.com/Microsoft/referencesource/tree/master/Microsoft.VisualBasic)
1. Add it to the [src project](https://github.com/dotnet/corefx/blob/master/src/Microsoft.VisualBasic/src/Microsoft.VisualBasic.vbproj), make it compile. Fix style to match style guidelines, update license headers to match existing code.
1. Add the API to the [ref](https://github.com/dotnet/corefx/blob/master/src/Microsoft.VisualBasic/ref/Microsoft.VisualBasic.cs). [Here's an example ](https://gist.github.com/danmosemsft/88da57da7f11a9a3345abb5ec508d5e7) of a complete ref generated from the .NET Framework binary.
1. Write tests, add to the [tests project](https://github.com/dotnet/corefx/blob/master/src/Microsoft.VisualBasic/tests/Microsoft.VisualBasic.Tests.csproj), and make them pass.
1. Put up a PR then we can check the type off.

[Here](https://github.com/dotnet/corefx/commit/5a6f230836006184c923b8c0e38631225c172e33) is an example change that ported some more of Strings.

To track progress, here is a list of classes/structs that aren't in .NET Core (or are present, but missing some members). I am not listing the members nor any enums: that detail is here: https://gist.github.com/danmosemsft/d34ec1055c4c23aefcd047089538d3a1
 
**namespace Microsoft.VisualBasic**
- [x] Collection
- [x] ComClassAttribute
- [x] Constants
- [x] ControlChars
- [x] Conversion
- [x] DateAndTime
- [x] ErrObject
- [x] FileSystem
- [x] Financial
- [x] Globals
- [x] HideModuleNameAttribute
- [x] Information
- [x] Interaction  (*)
- [x] MyGroupCollectionAttribute
- [x] SpcInfo
- [x] Strings
- [x] TabInfo
- [x] VBFixedArrayAttribute
- [x] VBFixedStringAttribute
- [x] VBMath

**namespace Microsoft.VisualBasic.ApplicationServices**
- [x] ApplicationBase
- [x] AssemblyInfo
- [ ] BuiltInRoleConverter
- [ ] CantStartSingleInstanceException
- [x] ConsoleApplicationBase
- [x] NoStartupFormException
- [x] StartupEventArgs
- [x] StartupNextInstanceEventArgs
- [x] UnhandledExceptionEventArgs
- [x] User
- [ ] WebUser
- [x] WindowsFormsApplicationBase (*) (see https://github.com/dotnet/winforms/issues/2056)
 
**namespace Microsoft.VisualBasic.CompilerServices**
- [x] BooleanType
- [x] ByteType
- [x] CharArrayType
- [x] CharType
- [x] Conversions
- [x] DateType
- [x] DecimalType
- [x] DesignerGeneratedAttribute
- [x] DoubleType
- [x] ExceptionUtils
- [ ] FlowControl
- [x] HostServices
- [x] IncompleteInitialization
- [x] IntegerType
- [x] InternalErrorException
- [x] LateBinding
- [x] LikeOperator
- [x] LongType
- [x] NewLateBinding
- [x] ObjectFlowControl
- [x] ForLoopControl
- [x] ObjectType
- [x] Operators
- [x] OptionCompareAttribute
- [x] OptionTextAttribute
- [x] ProjectData
- [x] ShortType
- [x] SingleType
- [x] StandardModuleAttribute
- [x] StaticLocalInitFlag
- [x] StringType
- [x] Utils
- [x] Versioned

**namespace Microsoft.VisualBasic.Devices**
- [x] Audio (*)
- [x] Clock
- [x] Computer
- [x] ComputerInfo
- [x] Keyboard (*)
- [x] Mouse (*)
- [x] Network (* - progress dialog)
- [x] NetworkAvailableEventArgs
- [ ] Ports
- [x] ServerComputer

**namespace Microsoft.VisualBasic.FileIO**
- [x] FileSystem
- [x] MalformedLineException
- [x] SpecialDirectories
- [x] TextFieldParser

**namespace Microsoft.VisualBasic.Logging**
- [ ] AspLog
- [x] FileLogTraceListener (*)
- [x] Log

**namespace Microsoft.VisualBasic.MyServices**
- [x] ClipboardProxy (*)
- [x] FileSystemProxy
- [x] RegistryProxy
- [x] SpecialDirectoriesProxy

**namespace Microsoft.VisualBasic.MyServices.Internal**
- [x] ContextValue<T>

A few types may not be portable yet because of dependency issues - either they depend on something that isn't quite yet in .NET Core (principally Windows Forms) or that is, but is in a higher dependency level (Windows Forms again). I have marked some of these with (*). This problem can be solved but I suggest that we skip these for the moment.

ccing folks who have expressed interest in the past: this is now unblocked.
@KathleenDollard @OmarTawfik @karelz @jaredpar 
@amshekar @bbowyersmyth @iainnicol @EdwinEngelen @kaiukdevelopment @ocdtrekkie @ericmutter @MohammadHamdyGhanem

**Comment by nikeee** [comment]
Looking at the [source](https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic), the checklist seems to be outdated.

**Comment by cston** [comment]
I've updated the checklist. Note that types that depend on `System.Windows.Forms` have been ported to dotnet/winforms rather than dotnet/runtime.

**Comment by cston** [comment]
Closing. If there are additional types that need to be ported, we can follow up with specific issues.
