### ISSUE TITLE
Add HTTP URI support to SignedXml

### ISSUE THREAD

**Issue by MariusVolkhart** [dotnet/runtime#26893]
The `System.Security.Cryptography.Xml.Reference` class has support for `Reference` elements with ID `URI` attributes. This feature request is to add support for HTTP URIs as well.

The [W3 specification](https://www.w3.org/TR/2001/PR-xmldsig-core-20010820/#sec-URI) states:

> XML signature applications MUST be able to parse URI syntax. We RECOMMEND they be able to dereference URIs in the HTTP scheme.

The source code in question is https://github.com/dotnet/corefx/blob/faad2e63b35bed10fe18195987a413308b97eded/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Reference.cs#L364

**Comment by bartonjs** [comment]
Following the W3C's recommendation to dereference the URI is a security risk, and the code that does so was intentionally omitted when bringing SignedXml to .NET Core (now just ".NET").

Any solution to this would require a level of investment that is not consistent with our stated contribution bar for this library (https://github.com/dotnet/runtime/tree/main/src/libraries/System.Security.Cryptography.Xml#readme), so I'm closing this issue.
