### ISSUE TITLE
LINQ SelectAggregate

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#26945]
I wish we could have select that could also keep state of aggregation and continue the iteration, send the aggregation to the next select

It should be simple to add this

```C#
public static IEnumerable<V> SelectAggregate<T,V>(this IEnumerable<T> items,V seed,Func<V,T,V> func)
{
	foreach(var item in items)
	{
		seed	= func(seed,item);
		yield return seed;
	}
}

////

var array = new int[]{ 1,2,3 };
var sumArray = array.SelectAggregate(0,(seed,item) => seed + item).ToArray();
// { 1,3,6 }
```

**Comment by eiriktsarpalis** [comment]
In the interest of keeping the Linq API surface small, we would need to assess the popularity of such an addition before we commit to it. My impression is that `fold`/`scan`-like constructs are kind of niche in the context of an imperative language. c.f. #20330

**Comment by Thaina** [comment]
@eiriktsarpalis I don't think `scan` is actually niche. But people don't actually know its usage and then just fall back to normal `for` loop (arguably most linq in general face this same problem). While actually it could all be rewritten into linq language

Another issue is `scan` can be imitate by create cache variable outside of linq chain. But in turn its destroy immutibility and scope of variable. This actually is the usage of scan but people just workaround it carelessly

Another usage of scan is using in conjunction with `TakeWhile`. Such as summing the element but cap limit before its reach some value. This work with any cumulative logic

**Comment by eiriktsarpalis** [comment]
> But people don't actually know its usage and then just fall back to normal for loop (arguably most linq in general face this same problem).

I mean that sounds fine to me. Alternatively folks that need such a pattern can easily either write their own extension method or use one of the many third-party libraries that provide LINQ extensions.
