### ISSUE TITLE
EventSource is not emitting events to the Windows Event Log

### ISSUE THREAD

**Issue by hjc4869** [dotnet/runtime#27002]
EventSource on .NET Core 2.1.300 x64 (Running on Windows 10.0.14393.2368 x64) is not emitting event logs, thus logs cannot be viewed in eventvwr.msc  
I'm not sure if it is unavailable by design, or I'm missing something important.

Sample code to reproduce:  
EventSourceTest.Logging.dll
```cs
using System.Diagnostics.Tracing;

namespace EventSourceTest.Logging
{
    [EventSource(Name = "SampleEventSource", Guid = "b10d9bdd-6939-484f-93a9-be419202e3ac")]
    public sealed class SampleEventSource : EventSource
    {
        public static SampleEventSource Log = new SampleEventSource();
        [Event(1, Message = "MyEvt1", Level = EventLevel.Critical, Channel = EventChannel.Admin)]
        public void MyEvt1(string arg1)
        {
            WriteEvent(1, arg1);
        }
    }
}
```

EventSourceTest.dll
```cs
using System;
using EventSourceTest.Logging;

namespace EventSourceTest
{
    class Program
    {
        static void Main(string[] args)
        {
            SampleEventSource.Log.MyEvt1("test");
        }
    }
}
```

Use `eventRegister.exe` tool to generate manifest, and use `wevtutil` to register the manifest
```
eventRegister EventSourceTest.Logging.dll
wevtutil im EventSourceTest.EventSourceTest.etwManifest.man /rf:<Full/Path/To/etwManifest.dll> /mf:<Full/Path/To/etwManifest.dll>
```

When published with `dotnet publish -c Release -f net47 -r win-x64`, after running the program, the log shows correctly in Event Viewer. While with `dotnet publish -c Release -f netcoreapp2.1 -r win-x64`, nothing appears.

**Comment by yodasad** [comment]
Hello, @vancem!
Could you please confirm that there is no channel support in the 'EventSource' for .NET Core at the moment?

**Comment by yodasad** [comment]
Well, it seems like there **is** a channel support in .NET Core.
If you add and EventAttribute to your EventSource method and specify the Keywords parameter with the value -9223108154064109568 everything is working, EventViewer starts to see all events.

````
[Event(5, Channel = EventChannel.Admin, Level = EventLevel.Critical, Keywords = ((EventKeywords)(-9223108154064109568)),
            Message = "Instance: {0}\nSource: {1}\nMessage: {2}")]
public override void Critical(string instanceId, string loggerName, string message)
{
    this.WriteEvent(5, instanceId, loggerName, message);
}
````

Don't ask how I found this constant -9223108154064109568.

**Comment by Masus** [comment]
@yodasad brute force?:) Excellent finding! A pain to change all the manifests for our products but if this is the official way to do it I guess it will have to do. Any comments Microsoft (@vancem ?)?

**Comment by noahfalk** [comment]
@vancem retired a good while ago, I think ownership of this issue should have passed to my team. Sorry this has been causing trouble. I updated the title to reflect that this issue is about supporting EventLog and changed the milestone back to .NET 6. That doesn't mean we are promising to fix it, but I'd like to at least understand what is involved. While I have a fair amount of knowledge about EventSource I know nothing specific to the integration with Windows Event Log so that will take some research.

 I can't say yet why setting that strange keyword caused a change though it is an interesting finding! If anyone has a simple repro of this problem to share that would be helpful, otherwise I'll guess that it effects any EventSource and start from there.

**Comment by KalleOlaviNiemitalo** [comment]
I tried to debug this on .NET 5.0.1. `eventRegister.exe` from Microsoft.Diagnostics.Tracing.EventRegister/1.1.28 could not load EventSourceTest.Logging.dll, so I added code to write the manifest out:

```C#
            string manifest = SampleEventSource.GenerateManifest(
                typeof(SampleEventSource),
                "dummy.dll");
            Console.WriteLine(manifest);
```

and then built a DLL for it:

```bat
bin\Debug\net5.0\EventSourceTest.exe > EventSourceTest.man
mc EventSourceTest.man
rc EventSourceTest.rc
csc  /target:lib /win32res:EventSourceTest.res /out:mani.dll
wevtutil install-manifest EventSourceTest.man /resourceFilePath:%CD%\mani.dll /messageFilePath:%CD%\mani.dll
```

<details>
<summary>EventSourceTest.man</summary>

```XML
<instrumentationManifest xmlns="http://schemas.microsoft.com/win/2004/08/events">
 <instrumentation xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:win="http://manifests.microsoft.com/win/2004/08/windows/events">
  <events xmlns="http://schemas.microsoft.com/win/2004/08/events">
<provider name="SampleEventSource" guid="{b10d9bdd-6939-484f-93a9-be419202e3ac}" resourceFileName="dummy.dll" messageFileName="dummy.dll" symbol="SampleEventSource">
 <channels>
  <channel chid="Admin" name="SampleEventSource/Admin" value="16" type="Admin" enabled="true"/>
 </channels>
 <tasks>
  <task name="MyEvt1" message="$(string.task_MyEvt1)" value="65533"/>
  <task name="EventSourceMessage" message="$(string.task_EventSourceMessage)" value="65534"/>
 </tasks>
 <opcodes>
 </opcodes>
 <keywords>
  <keyword name="Session3" message="$(string.keyword_Session3)" mask="0x100000000000"/>
  <keyword name="Session2" message="$(string.keyword_Session2)" mask="0x200000000000"/>
  <keyword name="Session1" message="$(string.keyword_Session1)" mask="0x400000000000"/>
  <keyword name="Session0" message="$(string.keyword_Session0)" mask="0x800000000000"/>
 </keywords>
 <events>
  <event value="0" version="0" level="win:LogAlways" symbol="EventSourceMessage" task="EventSourceMessage" template="EventSourceMessageArgs"/>
  <event value="1" version="0" level="win:Critical" symbol="MyEvt1" message="$(string.event_MyEvt1)" task="MyEvt1" channel="Admin" template="MyEvt1Args"/>
 </events>
 <templates>
  <template tid="EventSourceMessageArgs">
   <data name="message" inType="win:UnicodeString"/>
  </template>
  <template tid="MyEvt1Args">
   <data name="arg1" inType="win:UnicodeString"/>
  </template>
 </templates>
</provider>
</events>
</instrumentation>
<localization>
 <resources culture="en-US">
  <stringTable>
   <string id="event_MyEvt1" value="MyEvt1"/>
   <string id="keyword_Session0" value="Session0"/>
   <string id="keyword_Session1" value="Session1"/>
   <string id="keyword_Session2" value="Session2"/>
   <string id="keyword_Session3" value="Session3"/>
   <string id="task_EventSourceMessage" value="EventSourceMessage"/>
   <string id="task_MyEvt1" value="MyEvt1"/>
  </stringTable>
 </resources>
</localization>
</instrumentationManifest>
```

</details>

Then ran that in WinDbg with [dotnet-sos](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-sos), with breakpoints at [`ntdll!EtwEventWriteTransfer`](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/nf-evntprov-eventwritetransfer) and [`ntdll!EtwEventRegister`](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/nf-evntprov-eventregister).

After many `ntdll!EtwEventRegister` calls from other components, I got the one from `SampleEventSource`:

* LPCGUID ProviderId = rcx = {b10d9bdd-6939-484f-93a9-be419202e3ac}, matching EventSourceAttribute.Guid
* [PENABLECALLBACK](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/nc-evntprov-penablecallback) EnableCallback = rdx = 0x00007ff93c743144; set a breakpoint there
* PVOID CallbackContext = r8 = 0
* PREGHANDLE RegHandle = r9 = 0x000001e90c45f5b8

The EnableCallback was called with arguments:

* LPCGUID SourceId = rcx = {00000000-0000-0000-0000-000000000000}
* ULONG IsEnabled = rdx = 1
* UCHAR Level = r8 = 0xff
* ULONGLONG MatchAnyKeyword = r9 = 0x8000000000000000
* ULONGLONG MatchAllKeyword = 0
* PEVENT_FILTER_DESCRIPTOR FilterData = 0
* PVOID CallbackContext = 0

Soon after, `ntdll!EtwEventWriteTransfer` was called from within `EventSource.SendManifest`, with arguments:

* REGHANDLE RegHandle = rcx = 0x002d01e90c3e3820
* [PCEVENT_DESCRIPTOR](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/ns-evntprov-event_descriptor) EventDescriptor = rdx = { Id = 0xfffe, Version = 0x01, Channel = 0x00, Level = 0x00, Opcode = 0xfe, Task = 0xfffe, Keyword = 0x00ffffffffffffff }
* LPCGUID ActivityId = r8 = 0
* LPCGUID RelatedActivityId = r9 = 0
* ULONG UserDataCount = dwo(rsp+0x28) = 2
* [PEVENT_DATA_DESCRIPTOR](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/ns-evntprov-event_data_descriptor) UserData = poi(rsp+0x30) = { { Ptr = 0x00000045cd57d2a8, Size = 8, Type = 0 }, { Ptr = 0x000001e9`0c464d00, Size = 0x0000093a, Type = 0 } }. That's the manifest, all right.

Another `ntdll!EtwEventWriteTransfer` call, now from within `SampleEventSource.MyEvt1`:

* REGHANDLE RegHandle = rcx = 0x002d01e90c3e3820
* [PCEVENT_DESCRIPTOR](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/ns-evntprov-event_descriptor) EventDescriptor = rdx = { Id = 0x0001, Version = 0x00, Channel = 0x10 (Admin), Level = 0x01, Opcode = 0x00, Task = 0xfffd, Keyword = 0x0000f00000000000}
* LPCGUID ActivityId = r8 = 0
* LPCGUID RelatedActivityId = r9 = 0
* ULONG UserDataCount = dwo(rsp+0x28) = 1
* [PEVENT_DATA_DESCRIPTOR](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/ns-evntprov-event_data_descriptor) UserData = poi(rsp+0x30) = { { Ptr = 0x000001e90c44b644 = L"test\0", Size = 0xa, Type = 0 } }. 

Keyword = 0x0000f00000000000 is nonzero (see EVENT_ENABLE_PROPERTY_IGNORE_KEYWORD_0 in [ENABLE_TRACE_PARAMETERS_V1](https://docs.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-enable_trace_parameters_v1)) but does not match MatchAnyKeyword = 0x8000000000000000, so ETW discards the event, I think.

Indeed, if I force EVENT_DESCRIPTOR::Keyword to zero in the debugger, then the event appears in Event Viewer.

I wonder whether older versions of EventSource have implicitly set the 0x8000000000000000 keyword.

**Comment by KalleOlaviNiemitalo** [comment]
I suspect this part of ManifestBuilder.GetChannelKeyword should compare `channelKeyword == 0` rather than `channelKeyword != 0`: <https://github.com/dotnet/runtime/blob/d4d50db6768f729857b27ced3b68067bf30d18de/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L5332-L5344>

**Comment by noahfalk** [comment]
Great detective work @KalleOlaviNiemitalo! I took a look at the code and started getting some understanding how the channel filtering works. I agree that line you highlighted looks highly suspicious and swapping it to "channelKeyword==0" appears that it would cause channelKeyword = 0x8000000.... That in turn would cause the event keyword to include that bit when it is processed here:
https://github.com/dotnet/runtime/blob/2ef14c3ff6319d838211f9c30832c003744c8f09/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L3113
And that should cause the event not to be filtered out when it is emitted to ETW and compared against the 0x80000... matchAnyKeyword value by the OS.

@KalleOlaviNiemitalo - are you interested in submitting that PR and confirming it fixes the issue? If not no worries, I'll search for someone on my team to do it (@josalem do you have a little time to tackle this?)

**Comment by KalleOlaviNiemitalo** [comment]
@noahfalk - No, I don't intend to submit a PR.

**Comment by noahfalk** [comment]
Sure thing, thanks for letting us know and for the investigation already done! : )

**Comment by josalem** [comment]
@noahfalk  I have a few things ahead of this, but I can put it in the queue to look at!
