### ISSUE TITLE
Marshal.GetObjectForNativeVariant with IRecordInfo doesn't match netfx behaviour

### ISSUE THREAD

**Issue by hughbe** [dotnet/runtime#27015]
From dotnet/corefx#31461

```cs
[Fact]
[PlatformSpecific(TestPlatforms.Windows)]
[ActiveIssue()]
public void GetObjectForNativeVariant_Record_ReturnsExpected()
{
    int record = 10;
    var recordInfo = new RecordInfo { Guid = typeof(int).GUID };
    IntPtr pRecord = Marshal.AllocHGlobal(Marshal.SizeOf<int>());
    IntPtr pRecordInfo = Marshal.GetComInterfaceForObject<RecordInfo, IRecordInfo>(recordInfo);
    try
    {
        Marshal.StructureToPtr(record, pRecord, fDeleteOld: false);

        Variant variant = CreateVariant(VT_RECORD, new UnionTypes
        {
            _record = new Record
            {
                _record = pRecord,
                _recordInfo = pRecordInfo
            }
        });
        Assert.Equal(10, GetObjectForNativeVariant(variant));
        GetObjectForNativeVariant_NestedVariant_ReturnsExpected(variant, record);

        variant.m_Variant.vt |= VT_BYREF;
        Assert.Equal(10, GetObjectForNativeVariant(variant));
    }
    finally
    {
        Marshal.DestroyStructure<int>(pRecord);
        Marshal.FreeHGlobal(pRecord);
        Marshal.Release(pRecordInfo);
    }
}
```

This passes with netfx

On netcoreapp:
```
Discovering: System.Runtime.InteropServices.Tests
  Discovered:  System.Runtime.InteropServices.Tests
  Starting:    System.Runtime.InteropServices.Tests
     System.Runtime.InteropServices.Tests.GetObjectForNativeVariantTests.GetObjectForNativeVariant_Record_ReturnsExpect
  ed [FAIL]
        System.ArgumentException : The specified record cannot be mapped to a managed value class.
        Stack Trace:
              at System.Runtime.InteropServices.Marshal.GetObjectForNativeVariant(IntPtr pSrcNativeVariant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetObjectForNativeVariantTests.cs(1027,0): at System.Runtime.InteropServices.Tests.GetObjectForNativeVaria
  ntTests.GetObjectForNativeVariant(Variant variant)
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\GetObjectForNativeVariantTests.cs(700,0): at System.Runtime.InteropServices.Tests.GetObjectForNativeVarian
  tTests.GetObjectForNativeVariant_Record_ReturnsExpected()
  Finished:    System.Runtime.InteropServices.Tests
```

**Comment by AaronRobinsonMSFT** [comment]
This is an annoying issue and what to do isn't entirely obvious. What should probably happen is support querying the registry for the type, but in this case that entire code path has been removed. In .NET Framework this path was relying on TLB generation to get the COM layout based on the managed metadata. Since that entire code path has been removed it seems like the correct solution here is by-design.

I am torn because we could make this work for blittable types like the test is using. I am going to close this for now and wait for additional feedback from users before doing the work to actually support aspects of this.

**Comment by jkotas** [comment]
We should delete `ActiveIssue` link from the test to this issue before closing this. We do not want to have `ActiveIssue` links to closed bugs.

**Comment by hughbe** [comment]
So was looking at things in https://github.com/dotnet/winforms/pull/3197

 I sort of think we should really be throwing `PlatformNotSupportedException` if we encounter VT_RECORD in variants.

Currently the handling is completely broken and doesn't work.

/cc @weltkante

**Comment by AaronRobinsonMSFT** [comment]
@hughbe I would file a new bug with the desired behavior. Feel free to reference this issue.

**Comment by weltkante** [comment]
Thanks for pinging me, wasn't aware of this. We might actually have some of these left over in our applications, saves me from debugging when it comes to porting those libraries.

In general the behavior makes sense considering TLB support is mostly (completely?) "do it yourself" in .NET Core, I don't really care what kind of exception is thrown here, "The specified record cannot be mapped to a managed value class." seems good enough to me though.

As far as WinForms is concerned I'm not aware of any API which needs this, maybe some of the more advanced ActiveX support may have this, but I personally never came across this outside of user-defined TLB contracts.
