### ISSUE TITLE
AsnWriter doesn't wrap EncoderFallbackException in CryptographicException

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#27080]
`AsnSerializer.Serialize` throws `CryptographicException` for most errors. One exception is the `EncoderFallbackException` when trying to serialize a string that couldn't be encoded using specified encoding. `EncoderFallbackException` is not wrapped and has to be handled separetely, resulting in a code that is harder to read:

https://github.com/dotnet/corefx/blob/8d2407974c88b50c54f29ee20fd9deb8e6d00b1f/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/SubjectAlternativeNameBuilder.cs#L92-L106

I propose the exception should be caught and wrapped to make the life easier for the API consumers. The underlying `EncoderFallbackException` should still be available in `InnerException`.

/cc @bartonjs

**Comment by bartonjs** [comment]
This came up when making the API public, and the consensus seemed to be to let the EncoderFallbackException be what gets thrown.
