### ISSUE TITLE
PipeReader.OnWriterCompleted callback exception will crash the process

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#27109]
Apparently `PipeReader.OnWriterCompleted` (and perhaps `PipeWriter.OnReaderCompleted`?) execute their callbacks directly on the threadpool, with no `Task` or other means of wrapping exceptions thrown. As a result, if these callbacks throw an exception, the process crashes.

I find this very unexpected, since it is not clear how the callback will be invoked, and it's not documented to be directly on the threadpool. Most callback systems do not crash the process when the callback throws.

**Comment by BrennanConroy** [comment]
The OnXCompleted methods have been deprecated, closing the issue.
