### ISSUE TITLE
Opensuse Tumbleweed - No usable version of the libssl was found

### ISSUE THREAD

**Issue by joshfree** [dotnet/runtime#27113]
_From @livarcocc on March 29, 2018 21:20_

_From @luisantoniojr on March 29, 2018 21:9_

After a clean installation of opensuse tumbleweed, first thing i done, after update the system, was try to install dotnet sdk. So after follow this tutorial, https://www.microsoft.com/net/learn/get-started/linux/opensuse, i had this problem:

openssl is installed:
teste@linux-my0x:~> sudo zypper search openssl
i  | libopenssl-1_1-devel            | Development files for OpenSSL                                                | pacote
i+ | libopenssl-devel                | Include Files and Libraries mandatory for Development                        | pacote
i  | libopenssl1_1                   | Secure Sockets and Transport Layer Security                                  | pacote
i  | openssl                         | Secure Sockets and Transport Layer Security                                  | pacote
i  | openssl-1_1                     | Secure Sockets and Transport Layer Security                                  | pacote

## Steps to reproduce
dotnet new

## Expected  behavior
list of all options like: new console, new webapi and so on...

## Actual behavior
teste@linux-my0x:~> dotnet new
No usable version of the libssl was found
Aborted (recorded core image)

## Environment data
`dotnet --info` output:

teste@linux-my0x:~> dotnet --info
Ferramentas de Linha de Comando do .NET (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     opensuse
 OS Version:  20180326
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

_Copied from original issue: dotnet/cli#8939_

_Copied from original issue: dotnet/core-setup#3931_

**Comment by bartonjs** [comment]
This is leftover from before we supported OpenSSL 1.0/1.1 in a hybrid model, and has no further action.
