### ISSUE TITLE
Could not load assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0

### ISSUE THREAD

**Issue by minaairsupport** [dotnet/runtime#27121]
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?

Could any one guide me how to solve this issue I tried to make walk around  but it dosent work 

<Reference Include="System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\..\packages\System.Threading.Tasks.Extensions.4.5.1\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>

**Comment by ViktorHofer** [comment]
Closing as this was already tracked and presumably fixed.
