### ISSUE TITLE
Non-enumerating Count Linq Method

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/runtime#27183]
## Rationale
When dealing with collections it isn't uncommon that one needs to be able to get the count of an `IEnumerable<T>` as a default value for a new collection's capacity. The naive thing to do would be to simply use the `Enumerable.Count` extension method however if the `IEnumerable<T>` isn't an `ICollection<T>` or any of the other interfaces or types with a `Count` or `Length` property that method results in enumerating the collection which isn't desirable when just wanting a default value for a new collection's capacity. Instead of manually checking for those various interfaces each time someone needs this functionality I would like a non-enumerating count linq method added.

## Proposed API
```diff
 namespace System.Linq {
     public static class Enumerable {
+        public static bool TryGetNonEnumeratedCount(IEnumerable<T> source, out int count);
     }
 }
```

## Details
It would essentially retrieve the count so long as it doesn't necessitate enumerating the collection.

This would be a somewhat fragile method in that it should be updated whenever the next interface or type with a `Count` or `Length` property is introduced and thus may exhibit different behavior between versions.

## Use Cases
It could be used in collection constructors where initializing a collection with an `IEnumerable<T>` is common and a good initial capacity is important to reduce resizing costs such as in the `Dictionary<TKey, TValue>` constructor [here](https://github.com/dotnet/runtime/blob/e29b83934e7ceef9905f82bd6328cbc72db2278b/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L99) or the `HashSet<T>` constructor [here](https://github.com/dotnet/runtime/blob/e29b83934e7ceef9905f82bd6328cbc72db2278b/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs#L103). Unfortunately, since this method will be implemented at a higher level than these corelib types we won't be able to use it there.

## Updates
* Switched to `Count` with an `allowEnumeration` boolean parameter.
* Switched to `TryGetCount`.
* Switched to `TryGetNonEnumeratedCount`.

**Comment by eiriktsarpalis** [comment]
Ad-hoc implementations that try to calculate the count without enumerating are pretty common, so I think it would make sense to expose a method that does it in a correct and complete way. That being said, I don't think it should be called `Count` and it probably shouldn't be an extension method either. How about something like
```csharp
public static class Enumerable
{
    public static bool TryGetCount(IEnumerable<T> source, out int count);
}
```

**Comment by TylerBrinkley** [comment]
I agree it shouldn't be an extension method. I like the `TryGetCount` method name, works for me.

**Comment by eiriktsarpalis** [comment]
@TylerBrinkley would you be able to update the original post? I'll see if I can submit this for review.

**Comment by TylerBrinkley** [comment]
@eiriktsarpalis I've updated the original post.

**Comment by LeaFrock** [comment]
I think it will cause developers confused when returning `false`...
``` C#
Enumerable.TryGetCount(mySource, out int count)
```

> ...method results in enumerating the collection which isn't desirable when just wanting a default value for a new collection's capacity.

I know it's reasonable but I prefer to handle it by users themself. Or, `public static int NonEnumeratingCountOrDefault(this IEnumerable<TSource> source, int defaultValue = default);` should be better. At least it informs users what this method does and users won't have to understand the actual meaning of "**Try**" then deal with failure result.

**Comment by eiriktsarpalis** [comment]
> I think it will cause developers confused when returning false

How so? The point of this addition is to provide its user a clear signal as to whether a count can be obtained without enumerating. Roughly it would translate into the following code:
```csharp
if (Enumerable.TryGetCount(source, out int count))
{
    T[] fixedBuffer = new T[count];
    ConsumeUsingFixedBuffer(source, fixedBuffer);
}
else
{
    List<T> resizingBuffer = new List<T>();
    ConsumeUsingResizingBuffer(source, resizingBuffer);
}
```

> At least it informs users what this method does and users won't have to understand the actual meaning of "Try" then deal with failure result.

I think you are right in pointing out that the currently proposed name `TryGetCount` is ambiguous in what it is doing. How about `TryGetNonEnumeratedCount`?

**Comment by LeaFrock** [comment]
Well, it's better.

**Comment by TylerBrinkley** [comment]
I changed the proposal to `TryGetNonEnumeratedCount` and added a few use cases.

**Comment by terrajobst** [comment]
* The concept makes sense but it seems nicer as an extension method

```C#
namespace System.Linq
{
    public static class Enumerable
    {
        public static bool TryGetNonEnumeratedCount(this IEnumerable<T> source, out int count);
    }
}
```
