### ISSUE TITLE
MacOS 10.13.6 Console.SetWindowSize() exception

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/runtime#27216]
I'm opening this on behalf of a user from VS Feedback. https://developercommunity.visualstudio.com/content/problem/318400/macos-10136-consolesetwindowsize-exception.html

dotnet core 2.1 document say support macos

```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowSize(Int32 width, Int32 height)
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at ColorConsoleDemo.Program.Main(String[] args) in /Users/zhm/OneDrive/CodeStudy/dotnetcore/ColorConsoleDemo/Program.cs:line 26
```

code:
```c#
using System;
using System.Collections.Generic;

namespace ColorConsoleDemo {
    class Program {
        static void Main (string[] args) {
            List<ConsoleColor> colors = new List<ConsoleColor> ();
            // 遍历枚举的写法，高级用法，把各种颜色保存到List里
            foreach (ConsoleColor color in Enum.GetValues (typeof (ConsoleColor))) {
                colors.Add (color);
            }


            int i = 0;


            // 清楚屏幕，屏幕会被刷为空的背景色
            Console.Clear ();
            // 指定前景色
            Console.ForegroundColor = colors[i % colors.Count];
            // 指定背景色
            Console.BackgroundColor = colors[(i + 1) % colors.Count];
            Console.Write ("Hello");
            Console.ForegroundColor = colors[(i + 2) % colors.Count];
            int origWidth = Console.WindowWidth;
            int origHeight = Console.WindowHeight;
            Console.SetWindowSize (origWidth / 2, origHeight / 2);
            Console.Write (" world!", Console.WindowWidth, Console.WindowHeight);
            Console.SetCursorPosition (80, 15);
            Console.Write ("test");
            Console.SetCursorPosition (81, 16);
            Console.Write ("test");
            Console.SetCursorPosition (82, 17);
            Console.Write ("test");
            Console.SetCursorPosition (83, 18);
            Console.Write ("test");
            Console.SetCursorPosition (84, 19);
            Console.Write ("test");
            System.Threading.Thread.Sleep (1000);
            i++;
        }
    }
}
```

**Comment by devklick** [comment]
I understand that this will be a pretty low priority, as there really arent that many use cases for setting the console size, but I'd love to see this functionality implemented on Linux, if possible.

**Comment by wfurt** [comment]
It is not a matter of priority but more so technical feasibility. Unix "Console" is text-based and does not have window. When starting .NET console app, the app does not own or control the window - it is owned by the terminal app. There is more technical discussion here: https://github.com/dotnet/runtime/issues/31658

cc: @tmds

**Comment by junzhou98** [comment]
this problem has resolve?

**Comment by junzhou98** [comment]
it can't resolve?

**Comment by junzhou98** [comment]
help

**Comment by junzhou98** [comment]
urgent

**Comment by wfurt** [comment]
Are you on 2.1 @junzhou98? 2.1 support will expire in ~ month. Just catch the exception if you cannot avoid the call. 
Alternatively you can p/invoke the icon but that may or may not work. And if it is not, there is no real way IMHO how .NET can make it.

**Comment by CAMOBAP** [comment]
I assume there is the same exception for Linux/Docker

P.S. related https://github.com/breadbyte/ConsoleInteractive/issues/9

**Comment by adamsitnik** [comment]
The issue got fixed by https://github.com/dotnet/runtime/pull/75824, which is included in .NET 8.

Some OSes still don't support it, but there is nothing we can do about it:
https://github.com/dotnet/runtime/blob/0e6e35f3e378e299736fbe07d83ebc339658bbf7/src/libraries/System.Console/src/System/
Console.cs#L440C1-L450
