### ISSUE TITLE
Provide a way to get the information about the actual command line used when using Process's ArgumentList

### ISSUE THREAD

**Issue by kichalla** [dotnet/runtime#27251]
I like that there's now a new property called `ArgumentList` on `ProcessStartInfo`. 

For diagnostic purposes, I was looking to print out the actual command that was used to create the process. i.e I would like to see the command after any of its arguments were escaped etc.

**Comment by adamsitnik** [comment]
> For diagnostic purposes, I was looking to print out the actual command 

Hi @kichalla

I am the new owner of `System.Console` area.

Before I proceed with this proposal I would like to get a better understanding of what you need.

1. Do you need this information only during debugging? If so we could just add `[DebuggerDisplay]` attribute for the `ArgumentList` property (no need for new API or API review) and whenever you would hover your mouse this particular property of an instance of this type, you would see the final value.
2. Do you need this information for logging purposes? On Windows, there is an ETW event that contains this information. Is that enough or perhaps you are using some other logging mechanism and need this information anyway?

![obraz](https://user-images.githubusercontent.com/6011991/85402712-6f786000-b55c-11ea-81b4-873e8e3c97b7.png)

**Comment by kichalla** [comment]
Thanks @adamsitnik. Thanks for reaching out to me regarding this.

In my case I was trying to use in both debugging and logging. In my team we try to use Process api to run docker containers in our tests and when ever a test fails we try printing out the command that was run as part of the test. We develop on Windows machines but run our tests on Linux machines, so logging could be helpful too if there are any subtle differences, but if you think there would not be any such kind of differences and is easier to do DebuggerDisplay, I think that should be enough.
