### ISSUE TITLE
Add DivMod instrinct for intel x86/x64

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet/runtime#27292]
Please add hw instrinct support for divide on intel platforms.

# Rationale and Usage 

The intel instruction div is a bit special since 32bit divide takes a 64 dividend and 32bit divisor and returns both quotient and remainder as result. 

It would be very useful, not only for speeding up Math.DivRem (https://github.com/dotnet/coreclr/issues/757 ) but especially for several decimal operations which would make it more feasible to move decimal code to C# (and maybe several number functions).
Significant speedup using div in C++ provided significant speedups  in https://github.com/dotnet/coreclr/issues/10642)

Example:

The following code perfomes division of a 96bit unsigned number by a 32bit number.
Updating the 96bit number in-pace and returning the remainder
The example is simplified from actual code and contains only the "worst case" execution path.

```C#
public uint Div96By32(uint [] num,  uint denominator)
{
  if (System.Runtime.Intrinsics.X86.X86Base.IsSupported)
  {
    uint remainder;
    num[2] = System.Runtime.Intrinsics.X86.X86Base.DivMod(0, num[2], denominator, out remainder);   
    num[1] = System.Runtime.Intrinsics.X86.X86Base.DivMod(remainder, num[1], denominator, out remainder);
    num[0] = System.Runtime.Intrinsics.X86.X86Base.DivMod(remainder, num[0], denominator, out remainder);
    return remainder;
  }
 else { ... }
}
```` 

It performs the same logic as in https://github.com/dotnet/corert/blob/d82d460a8530a57e4915060be37fb42c7a661f48/src/System.Private.CoreLib/shared/System/Decimal.DecCalc.cs#L228

That code has 2 64bit divides (_much_ slower, especially in 32bit mode), and several multiplications (workarounds instead of using '%' which would double the executed div instructions currently).

# Proposed API

The API might need some design, but I think it makes sense to keep it similar to `Math.DivRem` as below.

```C#

namespace System.Runtime.Intrinsics.X86
{
  public static class X86Base 
  { 
    /// Perform unsigned division of 64 bit (hi, low) by 32bit divisor
    /// returning quotient, and returning remainder as an out parameter
    public uint DivRem(uint hi, uint low, uint divisor, out uint remainder);

    /// Perform unsigned division of 64 bit (hi, low) by 32 bit divisor
    /// returning quotient, and returning remainder as an out parameter
    public int DivRem(int hi, uint low, int divisor, out int remainder);
 
    [Intrinsic]
    public static class X64
    {
        /// Perform unsigned division of 128 bit (hi, low) by 64bit divisor
        /// returning quotient, and returning remainder as an out parameter
        public ulong DivRem(ulong hi, ulong low, ulong divisor, out ulong remainder);

        /// Perform unsigned division of 128 bit (hi, low) by 64 bit divisor
        /// returning quotient, and returning remainder as an out parameter
        public long DivRem(long hi, ulong low, long divisor, out long remainder);
      }
}
```

Related functionality which would make sense to add.
It could use the instrinct for god performance on x86 platforms.

```csharp
class System.Math
{
   // unsigned overload of  public static int DivRem (int a, int b, out int result);
   public static uint DivRem (uint a, uint b, out uint result);

   // unsigned overload of  public static int DivRem (int a, int b, out int result);
   public static ulong DivRem (ulong a, ulong b, out ulong result);
}
```

# Details 

Full description of instruction can be found in https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf

# Updates

* 2018-09-04 I've tried to add signed divide, and tried to restructure the post.
I am unsure about which versions would be useful so I am adding both that came to my mind.
 * 2020-06-15 
  * updated to use new X86Base https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/X86Base.cs
   * Removed 32 by 32 bit, and 64 by 64 bit division since it is better to add the missing overloads to Math and recognize them as instrincts

**Comment by Daniel-Svensson** [comment]
I've updated the description to match that there is now a X86Base instrinct class.
@tannergooding is there anything else that should/can be changed to increase the likelihood of getting this included for 5.0?

**Comment by tannergooding** [comment]
I can mark it ready-for-review now but I don't know if this will get on the backlog before we lock everything down.

The API review will also need to go over whether this is actually worthwhile to expose. As @jkotas indicated, this may be sufficiently covered (for the most common cases) via `Math.DivRem` and we should just optimize it (which I believe is dependent on some work @CarolEidt has been doing around multi-reg returns).

The remaining reason for the intrinsic is to support `128-bit / 64-bit = 64-bit` and `64-bit / 32-bit = 32-bit`. However, it might also be possible to just handle those via new "general-purpose" Math APIs.

**Comment by Thaina** [comment]
In addition to `DivMod` I would like to also propose `Absolute` and `IntFraction`. I don't know it exist in low level instruction but it would be convenient to have

```C#
int abs = Math.Abs(value,out int sign); // int for -1/0/1
long l = Math.IntFraction(123.456f,out float f); // 123 and 0.456f
l = Math.IntFraction(123.456,out double d); // 123 and 0.456
```

Is it possible?

**Comment by tannergooding** [comment]
> Is it possible?

Those are possible but they should be distinct proposals following the API proposal issue template: https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md

The APIs you mention are also different in that they aren't intrinsics supported by hardware.
`IntFraction` is also better known as `ModF` and is internally supported but not publicly exposed: https://source.dot.net/#System.Private.CoreLib/src/System/Math.CoreCLR.cs,135

**Comment by bartonjs** [comment]
* Since the original proposal, the return+out style for intrinsics has changed to named tuples `(Quotient, Remainder)` for these.
* "hi" should be "upper", "low" should be "lower"
* The canonical order in these APIs is (lower, upper), not (upper, lower).
* Added n(u)int as well
* The signedness of things is probably correct, but if not, it's an API review typo and should just be fixed as appropriate.

```C#
namespace System.Runtime.Intrinsics.X86
{
  partial class X86Base 
  { 
    public (uint Quotient, uint Remainder) DivRem(uint lower, uint upper, uint divisor);

    public (int Quotient, int Remainder) DivRem(uint lower, int upper, int divisor);

    public (nuint Quotient, nuint Remainder) DivRem(nuint lower, nuint upper, nuint divisor);

    public (nint Quotient, nint Remainder) DivRem(nuint lower, nint upper, nint divisor);
 
    [Intrinsic]
    public static class X64
    {
        public (ulong Quotient, ulong Remainder) DivRem(ulong lower, ulong upper, ulong divisor);

        public (long Quotient, long Remainder) DivRem(ulong lower, long upper, long divisor);
    }
}
```

**Comment by deeprobin** [comment]
With the implementation of this issue, should the [`DivRem`](https://github.com/dotnet/runtime/blob/02ac5c3ea455eb4298eb939ff6e7ab5e91c78419/src/libraries/System.Private.CoreLib/src/System/Math.cs#L332-L455)[^1] methods in `Math` also be changed to use the intrinsic methods if they are available on the corresponding platform?

And does anything need to be changed/added to preview features (e.g. generic math)?

[^1]: [.NET 6 documentation - `DivRem` - `System.Runtime.dll`](https://docs.microsoft.com/de-de/dotnet/api/system.math.divrem?view=net-6.0)

**Comment by huoyaoyuan** [comment]
I looked into this, but found it's not easy, since the only tuple-returning intrinsic was CPUID, which is not optimal in implementation (calls a function).

Ideally, the JIT should be updated to handle multi-reg returning instructions better, and the LSRA can be tuned to handle instructions with fixed register input (namely DIV/IDIV), which can also improve the codegen for BigMul.

@tannergooding This one is too hard for community contribution. Maybe some JIT expert should also be called for this.

**Comment by deeprobin** [comment]
@huoyaoyuan 
I've seen that too, that we return a ValueTuple. And as far as I know CPUID is also an InternalCall and not an Intrinsic or?
We could try to mimic a ValueTuple, but I'm not sure if that would work so well, since `ValueTuple` has the `StructLayout` `Auto` and not `Sequential`.

Alternatively, we could create another `private static` intrinsic which is easier to represent (for ex. using a ptr) and then which is then exposed via the proposed intrinsic

@tannergooding, what do you think?

**Comment by huoyaoyuan** [comment]
If such mechanism has already been used, I should be able to complete this. I have already done managed parts.

**Comment by deeprobin** [comment]
@stephentoub Why was this reopened? I thought its implemented?

**Comment by stephentoub** [comment]
> Why was this reopened? I thought it is implemented?

Because it's currently marked as:
```C#
[RequiresPreviewFeatures("DivRem is in preview.")]
```
https://github.com/dotnet/runtime/pull/82221

**Comment by pentp** [comment]
The remaining work is being tracked in #82194, so this one could still be closed?
