### ISSUE TITLE
Test failure: System.Globalization.Tests.NumberFormatInfoCurrentInfo/CurrentInfo_CustomCulture(newCurrentCulture: en)

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#27293]
Opened on behalf of @Sunny-pu

The test `System.Globalization.Tests.NumberFormatInfoCurrentInfo/CurrentInfo_CustomCulture(newCurrentCulture: en)` has failed.

System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.

        Stack Trace:

        
    Child exception:
      Xunit.Sdk.SameException: Assert.Same() Failure
    Expected: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
    Actual:   NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }
       at System.Globalization.Tests.NumberFormatInfoCurrentInfo.<>c.<CurrentInfo_CustomCulture>b__1_0(String cultureName) in E:\A\_work\2\s\corefx\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoCurrentInfo.cs:line 28
    
    Child process:
      System.Globalization.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Globalization.Tests.NumberFormatInfoCurrentInfo+<>c Int32 <CurrentInfo_CustomCulture>b__1_0(System.String)
    
    Child arguments:
      en
    
Build : 3.0 - 20180903.01 (UWP F5 Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS4-x86
  - Release

Details: https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180903.01/workItem/System.Globalization.Tests/analysis/xunit/System.Globalization.Tests.NumberFormatInfoCurrentInfo~2FCurrentInfo_CustomCulture(newCurrentCulture:%20en)

**Comment by tarekgh** [comment]
Closing this as it looks not a priority.
