### ISSUE TITLE
Inject existing object into MEF2

### ISSUE THREAD

**Issue by gthvidsten** [dotnet/runtime#27324]
Say I have an object:
```csharp
IMyObject obj = SomeFactory.CreateMyObject();
obj.NeedsSomeConfiguration()
    .NeedsMoreConfiguration();
```
and I've set up MEF to use the current assembly (of which IMyObject is defined)
```csharp
ContainerConfiguration containerConfig = new ContainerConfiguration()
    .WithAssembly(Assembly.GetExecutingAssembly())
```

How can I inject the specific instance of `obj` into this configuration so that I can do the following in an exported class
```csharp
[Export(typeof(IOtherObject))]
public class OtherObject : IOtherObject
{
    [Import] public IMyObject MyObject { get; set; }
}
```

**Comment by CZEMacLeod** [comment]
I'm fairly sure this is partially answered in #29400 by @nblumhardt
The 4 files in [Microsoft.Composition.Demos.ExtendedPartTypes](https://github.com/microsoftarchive/mef/tree/master/oob/demo/Microsoft.Composition.Demos.ExtendedPartTypes/Extension) give you the ability.
It would be nice if these were bundled up and either included in one of the existing `System.Composition.*` packages or a new `System.Composition.???` package.

Regardless, with the extensions available you can do

```
ContainerConfiguration containerConfig = new ContainerConfiguration()
    .WithAssembly(Assembly.GetExecutingAssembly())
    .WithExport<IMyObject>(obj);
```
or even
```
ContainerConfiguration containerConfig = new ContainerConfiguration()
    .WithAssembly(Assembly.GetExecutingAssembly())
    .WithFactoryDelegate<IMyObject>(() => {
        IMyObject obj = SomeFactory.CreateMyObject();
        obj.NeedsSomeConfiguration()
            .NeedsMoreConfiguration();
        return obj;
    });
```
or maybe
```
    .WithFactoryDelegate<IMyObject>(() => SomeFactory.CreateMyObject()
        .NeedsSomeConfiguration()
        .NeedsMoreConfiguration());
```

**Comment by tarekgh** [comment]
Closing as dups of https://github.com/dotnet/runtime/issues/29400#issuecomment-1098667828
