### ISSUE TITLE
Proposal: extension methods for numeric types

### ISSUE THREAD

**Issue by bugproof** [dotnet/runtime#27377]
So instead of 

```csharp
decimal.Round(1.112m, 2)
``` 

we could write
```csharp
1.112m.Round(2)
```

Basically, give the ability to use all those static functions as methods. It would be much easier to write.

Also compare this:

```csharp
var x = 1.213415m;
var y = 1.511213m;
var rounded = (x * y).Round(2); // looks much nicer!!! 
var rounded2 = decimal.Round(x * y, 2); // feels like C or C++ or python
```

https://stackoverflow.com/questions/961038/how-do-i-properly-write-math-extension-methods-for-int-double-float-etc

This applies not only for numeric but for other types as well, C# would feel more expressive with extensions like that. Now it feels more like coding in C (that is procedural).

Some projects that implement this:

- https://github.com/atesz77/System.Useful.NetSandard/tree/1fd407b8d98e8b538e416f1a7fcc871851694f35/src/System.Useful.NetStandard
- https://github.com/m5knt/ThunderEgg.Extensions

I immediately thought why isn't it built-in to make our life easier? C# allows this, so I think it might be a great addition to write a cleaner code

Rust has similar syntax for this: https://stackoverflow.com/questions/28655362/how-does-one-round-a-floating-point-number-to-a-specified-number-of-digits

so does ruby: https://apidock.com/ruby/Float/round

Tell me what you think

**Comment by tannergooding** [comment]
Going to close this as it hasn't garnered much attention and doesn't seem to mesh with the general look and feel of APIs exposed on .NET (these type of methods are typically static, not instance methods).
Users wanting this type of functionality could trivially add their own extension methods that call the existing static methods exposed and could provide this via a 3rd party NuGet package.

If someone feels strongly about this, please feel free to open a new issue. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.
