### ISSUE TITLE
System.Threading.Tasks.Extensions with net462 pulls nearly 100 dependencies instead of 1

### ISSUE THREAD

**Issue by petedavis** [dotnet/runtime#27387]
Using Visual Studio 2017 (15.8.4)

Trying to upgrade to System.Reactive 4.1, which takes a dependency on System.Threading.Tasks.Extensions 4.5.1 on a solution using framework 4.6.2, I am getting all files from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib` copied into my build output folder.

This is because when installed the hint path is:
`<HintPath>..\packages\System.Threading.Tasks.Extensions.4.5.1\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll</HintPath>`

and not:
`<HintPath>..\packages\System.Threading.Tasks.Extensions.4.5.1\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll</HintPath>`

Given that the package states that for net 4.5+ the only dependency should be System.Runtime.CompilerServices.Unsafe, and that package is listed as having no dependencies, this is not an expected result.

This is simple to reproduce. Create a new Net Framework project targeting framework 4.6.2. Install System.Threading.Tasks.Extensions version 4.3.0 and there will only be two dll's in the build folder.

Update to 4.4.0+ and there will be over 100 files for a package that states it has a single dependency.

The main issue now is that you can control the reference by using the mentioned workaround to point to the net45 version by manually editing the hint path. However if you migrate to package references, you can no longer control this. Which is the case for many of our project files.

**Comment by ViktorHofer** [comment]
Closing as this has been fixed in master. Until net5 ships, the workaround is to add a PackageReference to System.Runtime.CompilerServices.Unsafe with a 5.x version, i.e. https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/5.0.0-preview.6.20305.6.
