### ISSUE TITLE
Add new() constraint to LazyInitializer::EnsureInitialized<T>(ref T target)

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#27396]
The proposed new signature

```c#
public static T EnsureInitialized<T>(ref T target) where T : class, new()
```

I know it's possibly breaking change and new method would have to be introduced to avoid that but I still see that to be beneficiary. Right now the implementation assumes there is a default constructor available on type `T` and when there is not it throws an exception but as this code path is in threading primitive it might not be hit ever in testing thus makes it harder to track for something that could be a simple compilation error.

**Comment by stephentoub** [comment]
I agree with Jan that there's not enough demonstrated benefit here to be worth the break. If it becomes important for tools like the linker, it can be reconsidered. Thanks.
