### ISSUE TITLE
some backtracking regexes slower on .NET

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#27402]
eg `(\w*)+\.` on `aaaaaaaaaaaaaaaaaaaaaaa` takes a while:
 
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19041
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-alpha.1.20079.6
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.7203, CoreFX 5.0.20.7203), X64 RyuJIT
  DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.7203, CoreFX 5.0.20.7203), X64 RyuJIT

|         Method |       Mean |    Error |    StdDev |
|--------------- |-----------:|---------:|----------:|
|          Bench | 2,593.0 ms | 51.76 ms | 131.75 ms |
| Bench_Compiled |   669.2 ms | 12.96 ms |  11.49 ms |

But on `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` it takes substantially longer - minutes at least, even with `RegexOptions.Compiled`, using current master. I gave up waiting.

On this long text, where .NET is very slow, Rust is almost instant, PHP, Python and Golang are 100-300ms or so. Adding a period on the end to make it a match makes no difference.

Is there something we can do to optimize this pattern? I have no reason to believe it's an important one - I just reduced it from the disabled one in `Docs_Backtracking_LookaheadAssertions`

cc @stephentoub

**Comment by stephentoub** [comment]
> Is there something we can do to optimize this pattern?

Use a DFA to avoid backtracking.

**Comment by stephentoub** [comment]
> (\w*)+

This is the quitessential "catastrophic backtracking" example.

There's lots of discussion you can find on the net, but a quick example:
https://www.regular-expressions.info/catastrophic.html
>Preventing Catastrophic Backtracking
The solution is simple. When nesting repetition operators, make absolutely sure that there is only one way to match the same match. If repeating the inner loop 4 times and the outer loop 7 times results in the same overall match as repeating the inner loop 6 times and the outer loop 2 times, you can be sure that the regex engine will try all those combinations.

**Comment by danmosemsft** [comment]
Yeah, I was wondering whether any of them were doing something simple like recognizing that the last character `.` cannot match. But they are equally fast when I put a `.` on the end so that check does not help.

**Comment by stephentoub** [comment]
We could do that if desired.  There are optimizations we don't currently do but could do where we search for characters we know must exist for the expression to match, and fail the match if we can't find it.  Such checks can help in cases like this, but also hurt in other cases where it ends up being wasted work.

**Comment by stephentoub** [comment]
Actually, in this particular case, we should be able to do better. If it weren't for the capture in there, we would see that the loop could be made atomic. But the capture shouldn't affect that. We should be able to improve our atomicity logic (added recently) to see through the capture.
