### ISSUE TITLE
Process should have a TryGetProcessById method

### ISSUE THREAD

**Issue by mnmr** [dotnet/runtime#27411]
Process currently only provides GetProcessById, which throws an exception instead of returning null when no such process exists. The only alternative to this is to enumerate all processes, but this can take a while and is for our use case completely unnecessary.

It would be really nice if there was a TryGetProcessById method to attempt to find the process without triggering an exception.

**Comment by jkotas** [comment]
Duplicate of #101582 that is formatted as proper API proposal.
