### ISSUE TITLE
.Net Core 2.1 and 2.2 Vector Inconsistency

### ISSUE THREAD

**Issue by dangi12012** [dotnet/runtime#27435]
.Net Framework does not support System.Numerics.Vector and Span<T> interoperability.
.Net Core does have a construction overload: new Vector<float>(Span<T> values)

What is critical and missing (for performance and consistency) at the moment is the method:
`v.CopyTo(mySpan)`

So we can construct a Vector<T> from a span but we can not output it to one. This is really a missing method since Span and Vector is all about more performance.

**Comment by tannergooding** [comment]
Going to close this.

`Vector(Span<T>)` was added in .NET Core 2.1.
`Vector(ReadOnlySpan<T>)` and `Vector.CopyTo(Span<T>)` were added in .NET Core 3.0
