### ISSUE TITLE
Please add ReadOnlySequence<byte> Overloads to Socket.SendAsync

### ISSUE THREAD

**Issue by AceHack** [dotnet/runtime#27486]
```c#
System.Net.Sockets.Socket
{
    public ValueTask<int> SendAsync(ReadOnlySequence<byte> buffer, SocketFlags socketFlags, CancellationToken cancellationToken = default(CancellationToken))
}
```

See this gist for example usage.

https://gist.github.com/AceHack/786e558f14b2d9c0d46a1ea330c158f7

**Comment by davidfowl** [comment]
We can replace this with https://github.com/dotnet/runtime/issues/49941. We'd need this other API anyways since we'd need to transform the ReadOnlySequence into a `List<ReadOnlyMemory<byte>>` anyways. Once we get a new socket API then we can add a helper to transform the ROS
