### ISSUE TITLE
Add a way to force-initialize a System.Lazy

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#27509]
`Lazy` should have a way to make it compute the value on demand. This could be as simple as this:

```
    void ForceValue()
    {
      var dummy = Value;
    }
```

This is useful if `Lazy` is used as a cache and you want to pre-initialize that cache. That pre-initialization could be done in the background by `Task.Run(() => myLazy.ForceValue())`. I'm sure a `ForceValue` is handy in other situations as well. It does not clutter the class much and is trivial to implement.

**Comment by stephentoub** [comment]
> If the team is not convinced at this point, I think it's time to let this go

Thanks for the suggestion.
