### ISSUE TITLE
Api suggestion: Monitor.TryEnter() with CancellationToken

### ISSUE THREAD

**Issue by JanEggers** [dotnet/runtime#27520]
Im having a method that relies on a lock.

currently I do:

```c#
void DoStuff(CancellationToken ct) {
    lock(_lock) {
        ct.ThrowIfCancellationRequeted();

       // the actual work
   }
}
```
what I would prefere is that i can Monitor.TryEnter() or lock(_lock) with (ct) so that my function gets canceled as soon as the token is set.

**Comment by GrabYourPitchforks** [comment]
@stephentoub Is this actionable by us? From what I know of APIs like `EnterCriticalSection` this wouldn't really be feasible to bolt on to the existing infrastructure. If there were different non-`Monitor` synchronization primitives perhaps those could honor a `CancellationToken`?

**Comment by stephentoub** [comment]
> Is this actionable by us?

I mean, it's "just" software... if we really cared a lot we could make it happen.  But it would be very far from trivial and I don't think it's worth it.  It's why we haven't done it in the last decade even though it's an obvious thing to want.

> If there were different non-Monitor synchronization primitives perhaps those could honor a CancellationToken?

They mostly do.  ManualResetEventSlim, SemaphoreSlim, etc., all expose CancellationToken-based support.

**Comment by stephentoub** [comment]
Closing, per above comments. Thanks.
