### ISSUE TITLE
Add basic tests for RPM and Debian packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#2754]
In the old build system we had a step that would test our debian installers by installing them.

We don't have that in the new build system.

We should port the old installer tests to the new system.

**Comment by NikolaMilosavljevic** [comment]
Closing - low ROI on test.

**Comment by NikolaMilosavljevic** [comment]
@jcagme , consider for build validation rings.

**Comment by jcagme** [comment]
What sort of testing should these have?
