### ISSUE TITLE
Proposal: ForEach in Linq

### ISSUE THREAD

**Issue by hajirazin** [dotnet/runtime#27560]
Background:
I have seen many libraries have been Implementing custom extension method for LINQ. Most of the project I have work with has this extension method. Not all projects need all the methods from Libraries like MoreLinq.
Proposal:
My Proposal is to have ForEach extension method as part of LINQ.

**Comment by eiriktsarpalis** [comment]
Duplicate of #40409.

Closing, for the reasons already described in that issue.

**Comment by hajirazin** [comment]
@eiriktsarpalis i think this is the older issue than the other one, and i see community giving comments and understanding the needs of it. We could achieve even .Where or .Select with foreach but .Do method is syntactical sugar and i've in many projects that people create this extension by them selfs. And if we want to support in ORM, then it should be query terminator like toList, query should be executed and forEach should be performed on that.
