### ISSUE TITLE
Should HasValue property of a nullable type be accessible through reflection when value is null?

### ISSUE THREAD

**Issue by jbhensley** [dotnet/runtime#27596]
The `HasValue` property of nullable types is only accessible through reflection when the `Value` is not null.

![nullable](https://user-images.githubusercontent.com/13544395/46762018-d374cb00-cc8a-11e8-8be8-8088aa715be0.png)
This is inconsistent with the fact that `<nullableObject>.HasValue` is always accessible. At least one real-world bug has cropped up as a result (see issue dotnet/runtime#27531). The purpose of this issue is to hopefully start a discussion of whether `HasValue` should be accessible through reflection when `Value` is null and to possibly change the behavior.

**Comment by GrabYourPitchforks** [comment]
I don't think it's wise for us to make this change. A nullable type such as `int?` is logically two values: a _T_ and a _bool_. The special value _null_ just means that the Boolean is set to _false_. But the _T_ and the _bool_ do nevertheless exist on the stack (if you have a local of type `T?`) or in the object contents (if you have a field of type `T?`).

In the case of `PropertyInfo.GetValue(null)`, there's no _T_ or _bool_ for us to query at all. Did the caller inadvertently pass us the wrong value? Did the caller intend for us to hydrate a fresh `T?` (defaulting the _bool_ to _null_) and invoke the property getter on that? Why would we hydrate `default(int?)` in this situation and not - say - `default(int)` if we were trying to call a property hanging off of `System.Int32`? It gets ambiguous fairly quickly.
