### ISSUE TITLE
Can't use System.Diagnostic.Tracing.EventSource based classes in .NET Core for Linux

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#27635]
The code is here:

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs

When I try to use EventSource execution fails with "Exception during construction of EventSource Microsoft-Diagnostics-DiagnosticSource: Unsupported type IEnumerable`1 in event source.".
It looks like IEnumerable parameters aren't supported in .NET Core for Linux.

**Comment by stephentoub** [comment]
The original poster of this issue deleted their account and is now a "ghost", and no repro was provided in response to a request, so I'm going to close this issue.  Thanks.
