### ISSUE TITLE
Add EnumMemberAttribute constructor

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/runtime#27655]
## Rationale
Instead of having to specify the `Value` property name everytime you apply the `EnumMemberAttribute`, it would be nice if an additional constructor was added with a `value` parameter. As it's the only settable property on the attribute I think this makes a lot of sense.

What was this

```c#
public enum Operation
{
    [EnumMember(Value = "+")]
    Add,
    [EnumMember(Value = "-")]
    Substract
}
```

can now become just this

```c#
public enum Operation
{
    [EnumMember("+")]
    Add,
    [EnumMember("-")]
    Substract
}
```

## Proposed API
```diff
 namespace System.Runtime.Serialization {
     public sealed class EnumMemberAttribute : Attribute {
+        public EnumMemberAttribute(string value);
     }
 }
```

**Comment by joperezr** [comment]
I'm sorry that this got missed somehow, I think that the Api suggestion is reasonable so mariking this as ready for review.

**Comment by bartonjs** [comment]
Since the property is already settable, our guidelines say that it can't also be a constructor parameter -- largely because it makes reading attributes harder via metadata readers.

> DO NOT provide constructor parameters to initialize properties corresponding to the optional arguments.

**Comment by TylerBrinkley** [comment]
Thanks for the consideration.
