### ISSUE TITLE
Proposal: Timer static Create methods that make rooting behavior explicit

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#27654]
**Background**

The rooting behavior employed by `Timer` isn't obvious, and can lead to unexpected leaks like those in https://github.com/dotnet/corefx/pull/32793 and https://github.com/dotnet/corefx/pull/32794.

When you create a `Timer` with `new Timer(delegate, state, dueTime, period)`, the resulting `Timer` object that gets created isn't rooted by the implementation, so if all references to it are dropped, a finalizer will end up canceling the timer. However, the implementation does root the `delegate` and `state` objects as long as the timer is scheduled; when the `Timer` gets dropped and the finalizer unschedules the underlying object, the `delegate` and `state` will be unrooted... however, if either the `delegate` or the `state` reference the `Timer` object, they will keep that from happening.  This kind of cycle happens in a situations like:
```C#
var s = new State();
s.Timer = new Timer(delegate, s, dueTime, period);
```
in which case this `Timer` will end up being rooted by the rooted `State` object until the timer is explicitly unscheduled via a call to `Change(Timeout.Infinite, Timeout.Infinite)`.

Further, when the `new Timer(delegate)` constructor is used, the implementation effectively does the equivalent of `Timer t = new Timer(delegate); t.State = t; t.Change(dueTime, period);` such that the Timer implicitly keeps itself rooted as long as it's scheduled.

There is a non-trivial amount of code that depends on these behaviors, either to keep the `Timer` rooted because that's what's needed (e.g. if you want to create a fire-and-forget timer where it'll go off at a particular due time but without you needing to explicitly keep the Timer rooted), or to ensure it's not rooted (e.g. to have a periodic timer that'll fire only as long as other state is alive and to go away when it's not).  But keeping track of which is which can be difficult.

@davidfowl and I have been discussing ways to address this.  Changing the existing behavior would be a huge breaking change, and since there are actually multiple modes that are desirable at different times, changing to one or the other wouldn't actually fix things.

**Proposal**

The issue https://github.com/dotnet/corefx/issues/26523 suggests adding the API:
```C#
public static Timer UnsafeCreate(TimerCallback callback, object state, TimeSpan dueTime, TimeSpan period);
```
in order to be able to avoid flowing ExecutionContext. I suggest instead we do this:
```C#
public enum TimerLifetimeMode
{
    RootedState, // Timer won't be rooted by the implementation, but delegate/object state will as long as it's scheduled, same as the existing Timer(delegate, state, dueTime, period) ctor
    Rooted, // Timer will be rooted as long as it's scheduled, same as the existing Timer(delegate) ctor
    Unrooted, // Neither Timer nor the TimerCallback nor the object state will be rooted
}
...
public static Timer Create(TimerCallback callback, object state, TimeSpan dueTime, TimeSpan period, TimerLifetimeMode mode = TimerLifetimeMode.RootedState);
public static Timer UnsafeCreate(TimerCallback callback, object state, TimeSpan dueTime, TimeSpan period, TimerLifetimeMode mode = TimerLifetimeMode.RootedState);
```
(There may of course be better names for the enum and enum values.)

That way:
- All of the interesting modes are available and called out in the API / IntelliSense.
- You have all of the options available to you whether you want to flow ExecutionContext or not.
- The default when using {Unsafe}Create still matches the equivalent ctor with the same number of required arguments.

Note that while `Unrooted` would avoid having the implementation maintain rooted references to the `Timer`, delegate, and state, it would still maintain a rooted reference to any captured `ExecutionContext`, as it's extremely unlikely the caller would be maintaining that and it's a critical part of the ability to invoke the callback, so there's still the rare but possible situation where some `AsyncLocal` in that `ExecutionContext` references the `Timer`, in which case it would still be kept alive.  I don't see a good way around that, other than using `UnsafeCreate` to not capture the `ExecutionContext`.

Also, implementation-wise, I expect this would likely end up increasing the size of the objects involved by a few fields, and maybe using `WeakReference`s in the implementation, and maybe adding some casting when firing timers.  For example, the `Rooted` mode could be achieved easily just by adding a `Timer` field to the internal `TimerQueueTimer` object (it would then also likely avoid the need to allocate the finalizable TimerHolder object, if we also added a TimerQueueTimer field to Timer).  But to implement `Unrooted`, `TimerQueueTimer` will no longer be able to store a strong reference to the delegate or object state as it currently does, so for that mode, it would probably need a field that could store either a `WeakReference<DelegateAndState>` (or one for each object) or a `WeakReference<Timer>`, then adding the delegate and object as fields to the `Timer`, or potentially use a `WeakReference<TimerQueueTimer>` for the whole object, keeping it alive only by a `_timerQueueTimer` field on the `Timer`.  Or some such thing.  I don't think it would be prohibitive, but we'd want to do some perf testing to confirm before going ahead with it if/when the APIs are approved.

cc: @kouvel, @davidfowl, @vancem

**Comment by theo-albers** [comment]
Why don't you simply allow:
GC.DisableCollect(....)

We are used to play with GC for the IDisposable pattern. I feel terminology as "rooted" and "unrooted" not very intuitive for a managed programming language.

**Comment by weltkante** [comment]
> Why don't you simply allow:
GC.DisableCollect(....)

You can already do that through various means, the point is that Timers currently do it implicitely, and you want overloads which make that implicit "disable collect" explicit so the caller is aware that the timer disables garbage collection.

**Comment by danmosemsft** [comment]
@stephentoub I'm going through the api-approved -- is this one approved, if so should it be up for grabs? I see mention above of going back to review, maybe labels got messed up?

**Comment by stephentoub** [comment]
I think we should hold off on adding this until we decide what to do with https://github.com/dotnet/runtime/issues/31525.

**Comment by stephentoub** [comment]
With https://github.com/dotnet/runtime/issues/31525 added, I'm going to close this until we see further need.
