### ISSUE TITLE
Feature Request: Overload for Distinct to receive a func.

### ISSUE THREAD

**Issue by RubenMateus** [dotnet/runtime#27665]
I noticed in the Distinct there is no overload for receiving a func, we always have to create a new lambdacomparer and put the func inside the comparer, is it possible to have that abstracted and use it like:
`Distinct((a, b) => a.Stuff == b.Stuff && a.Stuff1 == b.Stuff1)`
Does this even make sense?
If so i think i have a simple solution for this.

**Comment by RubenMateus** [comment]
any news on this? will it enter in any release?

**Comment by jnm2** [comment]
I recently learned that Distinct has a documented guarantee that values will be returned in the original order in which they are seen, but GroupBy documentation explicitly does not guarantee that groups will be returned in the original order in which each key was first seen.

**Comment by svick** [comment]
@jnm2 Where did you see that? [The documentation for `GroupBy<TSource,TKey>(IEnumerable<TSource>, Func<TSource,TKey>)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.groupby?view=netcore-3.1#System_Linq_Enumerable_GroupBy__2_System_Collections_Generic_IEnumerable___0__System_Func___0___1__) says:

> The ` IGrouping<TKey,TElement>` objects are yielded in an order based on the order of the elements in `source` that produced the first key of each ` IGrouping<TKey,TElement>`. Elements in a grouping are yielded in the order they appear in `source`.  
 
So, at least this overload does guarantee the order. (Though not all overloads have this note.)

**Comment by jnm2** [comment]
Oh no, I had them exactly backwards! GroupBy preserves ordering and [Distinct does not](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.distinct?view=netcore-3.1#remarks).

**Comment by eiriktsarpalis** [comment]
So, something like this?
```csharp
public static class Enumerable
{
    public static IEnumerable<TSource> DistinctBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector);
}
```
FWIW F# core has a [similar method](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#distinctBy).

**Comment by eiriktsarpalis** [comment]
This request is already covered by #27687. Closing this one.
