### ISSUE TITLE
Easy reference equality comparer API

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#27683]
_Edit by @GrabYourPitchforks on 20 Jan 2020_: API proposal is at https://github.com/dotnet/corefx/issues/32931#issuecomment-576453361.

There is an existing internal [`ReferenceEqualityComparer`](https://github.com/dotnet/corefx/blob/8bd1d3becae98fff2859e0a033694fe44648c0e1/src/Common/src/System/Collections/Generic/ReferenceEqualityComparer.cs#L9). 

I would like to be able to do something like this:

```c#
if (list.SequenceEqual(originalItems, EqualityComparer.ByReference))
{
    // ...
}
```

Even if I'm not already overriding Equals to consider properties that mutate, using the default equality comparer is dangerous. Future distant changes would silently render this check ineffective. It should be explicitly a reference comparison.

The existing `EqualityComparer<>` class probably shouldn't be used because there's no way to constrain `T : class` for the `ByReference` member. (If C#'s Extension Everything work makes it through, a static extension method would allow putting the generic constraint on the extension method which would only show up on `EqualityComparer<T>` for referenced-typed `T`.)

Not having to specify a type parameter is even nicer. A `ByReference` member wouldn't have to be generic. So long as it returns `IEqualityComparer<object>`, contravariance allows it to just work for all reference types and blocks it for value types:

```c#
// Works
new[] { new MyClass() }.SequenceEqual(new[] { new MyClass() }, (IEqualityComparer<object>)comparer)

// CS1929: 'int[]' does not contain a definition for 'SequenceEqual' and the best
// extension method overload 'Queryable.SequenceEqual<int>(IQueryable<int>, IEnumerable<int>,
// IEqualityComparer<int>)' requires a receiver of type 'IQueryable<int>'
new[] { 1 }.SequenceEqual(new[] { 1 }, (IEqualityComparer<object>)comparer)

// On argument: Argument type 'System.Collections.Generic.IEqualityComparer<object>' is not
// assignable to parameter type 'System.Collections.Generic.IEqualityComparer<int>'
new[] { 1 }.SequenceEqual<int>(new[] { 1 }, (IEqualityComparer<object>)comparer)
```

There is no non-generic EqualityComparer class and it could be confusing to introduce one in the `System.Collections.Generic` namespace given the existing `Comparer`/`Comparer<T>` classes. Even so, it does provide the nicest syntax: `EqualityComparer.ByReference`.
Similar to what the non-generic immutable collection classes do, folks might expect `EqualityComparer.Default<T>()` to exist.

Alternatively, `ReferenceEqualityComparer.Instance` would work. It doesn't seem as cool to me as `EqualityComparer.ByReference`, but demand for it has obviously been low.

If nongeneric IEqualityComparer support is something you'd definitely want from this new API, it would have to return a class type which implements both. Variance is out, so the class would have to be generic and the syntax would have to specify a type parameter.

**Comment by terrajobst** [comment]
* Let's put it in `System.Collections.Generic` (because `System.Collections` doesn't have a `EqualityComparer` anyway).
* We don't want to put it on `EqualityComparer<T>` because it wouldn't vary by `T`
* But let's follow the pattern and have a non-generic `EqualityComparer` with a property named `Reference`.

```C#
namespace System.Collections.Generic
{
    public sealed class EqualityComparer : IEqualityComparer, IEqualityComparer<object>
    {
        private ReferenceEqualityComparer();
        public static ReferenceEqualityComparer Reference { get; }
    }
}
```

**Comment by ahsonkhan** [comment]
cc @Jozkee - once this is implemented, we should consider removing the custom comprarer used within JSON:
https://github.com/dotnet/runtime/blob/840ba6d0b454dcf2e2dc947454094a40761805ec/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReferenceEqualsEqualityComparer.cs#L13

**Comment by Jozkee** [comment]
@ahsonkhan I will take a look at #31753. Thanks!
