### ISSUE TITLE
API over QueryThreadCycleTime

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#27711]
A 1st party service running on .NET Framework use this in order to time out individual requests when they have used too much CPU. They are looking at Linux hosting longer term, if there is a similar Linux concept we should consider an API to abstract the OS.

@janvorli do you know?

**Comment by stephentoub** [comment]
@danmosemsft, is there an API you're proposing here?

**Comment by danmosemsft** [comment]
@stephentoub no. I was just recording the ask from the partner above. I believe they are using pinvoke today, as far as I know this is not blocking them in any way. I see a note from that time asking for other pinvokes they were doing that they believed suggested platform holes, but I don't have a record of such a list.

**Comment by danmosemsft** [comment]
Closing since we haven't had an add-ref on this.
