### ISSUE TITLE
Use SequenceEqual() in String.Replace()

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#27720]
As metioned in dotnet/corefx#16214 ( https://github.com/dotnet/coreclr/pull/16214/files#r166095689 ) we ~~should~~ could use [SequenceEqual](https://source.dot.net/#System.Private.CoreLib/shared/System/MemoryExtensions.cs,643) in [String.Replace()](https://source.dot.net/#System.Private.CoreLib/shared/System/String.Manipulation.cs,1083)

**Comment by stephentoub** [comment]
If someone wants to experiment with this and open a PR with appropriate performance numbers, please do. In the meantime, we don't need to track the possibility of an improvement. Thanks.
