### ISSUE TITLE
Add List<T>.CopyTo(Span<T>) overloads

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#27721]
We have `List<T>` CopyTo methods that all take an array:

```C#
        public void CopyTo(int index, T[] array, int arrayIndex, int count);
        public void CopyTo(T[] array, int arrayIndex);
        public void CopyTo(T[] array);
```

We should add similar overloads that take in a `Span<T>`.

```diff
public partial class List<T> : System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.Generic.IList<T>, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlyList<T>, System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.IList
{
+       public void CopyTo(int index, Span<T> span, int count);
+       public void CopyTo(Span<T> span);
}
```

I know you can work around not having this API by looping over the `List<T>` yourself. But since List is backed by an array, it is faster to use `memcpy` (or similar) than it is doing one element at a time.  (That is the same reason why we have `CopyTo(T[])` in the first place.)

**Comment by safern** [comment]
Given the above discussion and https://github.com/dotnet/runtime/pull/891#issuecomment-583071806 I'm going to close this issue. If people disagree or have any other thoughts, feel free to add them and we can always re-consider.
