### ISSUE TITLE
Add `Task.WithCancellation(CancellationToken)` method

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#27722]
[The `WithCancellation` extension method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.threadingtools.withcancellation?view=visualstudiosdk-2017) is super-useful. Should we add it to the .NET Framework / .NET Standard itself?

The risk is that folks will misunderstand the subtle yet important difference between using this method and passing the CancellationToken into the original async method properly.

Preferably this is *not* an extension method so it doesn't conflict with extension methods that folks have already defined. It should just override them, assuming the semantics are equivalent (the type of exception thrown, etc.)

See also [the source code for its definition in the vs-threading library](https://github.com/Microsoft/vs-threading/blob/34c6eae89e0514ca6c6e72d411629cdb4cd88d2e/src/Microsoft.VisualStudio.Threading/ThreadingTools.cs#L54-L102).

As discussed in https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/pull/8 with @davidfowl.

**Comment by StephenCleary** [comment]
[I really prefer the `Task.WaitAsync(CancellationToken)` naming](https://github.com/StephenCleary/AsyncEx/blob/5ede2ebad24bb3696fd730de2d7e11cda92bf8dc/src/Nito.AsyncEx.Tasks/TaskExtensions.cs#L20) over `WithCancellation`. I think `WaitAsync` makes it much more clear that it is the *wait* that is canceled and not the task.

**Comment by NN---** [comment]
What do you think about [WithTimeout](https://github.com/rsdn/CodeJam/blob/master/CodeJam.Main/Threading/TaskHelper.WithTimeout.cs#L26) extension method as well?
It can useful too.
