### ISSUE TITLE
System.IO.Pipelines: The default MemoryPool is suboptimal

### ISSUE THREAD

**Issue by JeffCyr** [dotnet/runtime#27748]
`MemoryPool<byte>.Shared` is used as the default memory pool for pipes which is backed by `ArrayPool<T>.Shared` (`TlsOverPerCoreLockedStacksArrayPool<T>`).

`ArrayPool<T>.Shared` only keeps [8 arrays per bucket size per core](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#L38). Typical usage of pipe will contain memory spike, the default pool will quickly echaust its buffers and will start allocating.

`ArrayPool<T>.Shared` is optimal when the array is returned shortly after being rent by the same thread ([example](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Globalization/CompareInfo.Windows.cs#L144)). It uses Thread Local Storage and per-core stacks. The PipeReader and PipeWriter will typically run concurrently on different threads, this is the worst case for `ArrayPool<T>.Shared` and will likely consume more CPU than having a single global stack.

cc @davidfowl

**Comment by davidfowl** [comment]
I think I've finally hit a scenario that shows how badly this behaves. I'm still gathering more data but it's looking like the shared array pool is a poor default for pipelines in some cases

**Comment by davidfowl** [comment]
Assigning this to myself to take a deeper look.

**Comment by davidfowl** [comment]
Closing this as there's nothing actionable right now outside of rewriting a new pool
