### ISSUE TITLE
Add ref for folders that are missing one

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#27762]
Some libraries in corefx have a `src` folder but no `ref` folder. In this case the src surface area will be used directly as the ref. This has some disadvantages such as 
1. Ref folder is nice for quickly looking at the surface area and its history
1. Ref reduces the size of the references package
1. Possibly a build race, per dotnet/runtime#19584.

We should be consistent and have a ref folder. We already did a pass in dotnet/runtime#19584. We should do that again and this time ideally add a build step so that new libraries must have one.

These look like they need a ref:
```
System.Composition
System.Composition.AttributedModel
System.Composition.Convention
System.Composition.Hosting
System.Composition.Runtime
System.Composition.TypedParts
System.Text.Encodings.Web
```
These do not have one but I believe they produce code that is in a ref in another project (might need special casing in the build step)
```
System.Private.DataContractSerialization
System.Private.Reflection.Metadata.Ecma335
System.Private.Uri
System.Private.Xml
System.Private.Xml.Linq
```

Not sure about these, I assume not
```
Microsoft.Diagnostics.Tracing.EventSource.Redist
Microsoft.IO.Redist
Microsoft.XmlSerializer.Generator
```

cc @ericstj @weshaggard

**Comment by ViktorHofer** [comment]
Closing as not planned. Ref assemblies don't ship inside packages anymore and only remain to be used with targeting packs.
