### ISSUE TITLE
Running .Net Core with permissions more restrictive than current user

### ISSUE THREAD

**Issue by theAshenfire** [dotnet/runtime#27807]
# Description

As part of our product we need to run untrusted code created by users. As such we use a runner process which loads the user assembly at runtime and executes the code.
Since the code is untrusted we would like to limit its access to resources such as network/File System etc. However, .Net Core does not support AppDomain/ACL in-program.

I have found in [this article](https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/) that the recommended solution would be to use virutualization, user permissions or containers such as docket. However, none of these solutions are feasible.
How could i make a .Net Core process run with restricted access per execution?

**Comment by GrabYourPitchforks** [comment]
Looks like the previous comments have answered the original question. If I've closed this in error please reopen.
