### ISSUE TITLE
Consider partial implementation of System.Drawing.Region class

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#27814]
Parts of [System.Drawing](https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=netcore-2.1) is implemented and part of the .NET Standard, while other parts (which are wrappers over GDI) are part of the Windows Compatibility Pack.

Consider a partial implemention of the [System.Drawing.Region](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.region?view=netcore-2.1) class which implements the methods dealing with math while leaving the implementation of the methods overloads with the `Graphics` parameter overload to the  Windows Compatibility Pack.

Example of methods to be implemented:
- IsVisible(Single, Single, Single, Single)
- IsVisible(Int32, Int32, Int32, Int32)
- IsVisible(Single, Single)
- IsVisible(Point)

Example of methods not to be implemented:
- IsVisible(Single, Single, Single, Single, Graphics)
- IsVisible(Int32, Int32, Int32, Int32, Graphics)
- IsVisible(Single, Single, Graphics)
- IsVisible(Int32, Int32, Graphics)

**Comment by JeremyKuhne** [comment]
There is still a dependency on GDI+ for what you're asking for so I'm afraid this isn't plausible.
