### ISSUE TITLE
API Proposal: SafeBuffer Span<T> methods

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#27831]
Proposal:

```csharp
namespace System.Runtime.InteropServices
{
    public abstract unsafe class SafeBuffer
    {
        public void ReadSpan<T>(ulong byteOffset, Span<T> buffer) where T : struct => throw null;
        public void WriteSpan<T>(ulong byteOffset, ReadOnlySpan<T> data) where T : struct => throw null;
    }
}
```

The purpose of this is to be a Span-based equivalent of `ReadArray`. The motivation for this is for a later API proposal to add the same methods to `UnmanagedMemoryAccessor` which will work for memory mapped views.

This would make it possible to work efficiently and safely with stackalloc'ed data.

**Comment by AaronRobinsonMSFT** [comment]
@vcsjones Where did we land on this? Did I miss the PR?

**Comment by stephentoub** [comment]
This is marked as api-approved.  Presumably what's next is just for someone to implement it :smile:

**Comment by vcsjones** [comment]
Hm, I guess that can be me. I see I offered a little while ago but failed to follow through. Apologies.

**Comment by stephentoub** [comment]
No need to apologize :)  Thanks for the offer.
