### ISSUE TITLE
System.Drawing - bmp resolution

### ISSUE THREAD

**Issue by k0st1x** [dotnet/runtime#27900]
Bitmap restored from the BMP file has empty HorizontalResolution & VerticalResolution property values

```C#
var client = new HttpClient();
byte[] bytes = client.GetByteArrayAsync("https://www.w3.org/People/mimasa/test/imgformat/img/w3c_home.bmp").Result;
using(var stream = new MemoryStream(bytes))
using(Bitmap bmp = new Bitmap(stream)) {
    Console.WriteLine(bmp.HorizontalResolution);
    Console.WriteLine(bmp.VerticalResolution);
}
```
the output on windows platform is "96" & "96"
but on the linux platform is "0" & "0"

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
