### ISSUE TITLE
microsoft/dotnet:2.1-aspnetcore-runtime-alpine  has something wrong  to display Chinese

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#27969]
@dustdragonpzc commented on [Thu Nov 15 2018](https://github.com/dotnet/dotnet-docker/issues/816)

## Steps to reproduce the issue
1. in dockerfile  I use  microsoft/dotnet:2.1-aspnetcore-runtime-alpine as a base image
2.  in my application, I got zh-HANS through   this variable System.Globalization.CultureInfo.CurrentUICulture.Name,but the correct is zh-Hans
3. so I can not get my Chinese configuration file to display Chinese .like xxx.zh-Hans.xml

---

@MichaelSimons commented on [Tue Nov 20 2018](https://github.com/dotnet/dotnet-docker/issues/816#issuecomment-440299752)

This does not seem like something specific to the `microsoft/dotnet` alpine images but rather the CoreFx alpine behavior.  Moving to CoreFx.

**Comment by tarekgh** [comment]
Closing it as we didn't get answer to the raised question.
