### ISSUE TITLE
Question: Furthering use of Span<T> and ReadOnlySpan<T> with string manipulation.

### ISSUE THREAD

**Issue by electricessence** [dotnet/runtime#27982]
I've noticed that the System.Text.RegularExpressions namespace is using Span<char> for some processes.
And was thinking possibly a fundamental change is in order for string?

Operations like `.Trim()`, or even the `.Value` of `Capture` should return a `ReadOnlySpan<char>` or at least have exposed access like .AsSpan().

Thoughts?

**Comment by stephentoub** [comment]
Capture has a ValueSpan property in. NET 6, and in .NET 7 we've added span-based IsMatch and Count methods, and https://github.com/dotnet/runtime/issues/65011 tracks additional span-based API on regex. Thanks.
