### ISSUE TITLE
Reading Windows Logs efficiently and fast

### ISSUE THREAD

**Issue by lucasalvarezlacasa** [dotnet/runtime#27981]
Hello everybody!. What I'm trying to accomplish is a C# application that will read logs from the Windows Event Logs and store them somewhere else. This has to be fast, since some of the devices where it will be installed generate a high amount of logs/s.

I have tried three approaches so far:

1) Local WMI: it didn't work good, there are too many errors and exceptions caused by the size of the collections that need to be loaded. 
2) EventLogReader: I though this was the perfect solution, since it allows you to query the event log however you like by using XPath expressions. The problem is that when you want to get the content of the message for each log (by calling FormatDescription()) takes way too much time for long collections.
E.g: I can read 12k logs in 0.11s if I just go over them.
If I add a line to store the message for each log, it takes nearly 6 minutes to complete exactly the same operation, which is totally crazy for such a low number of logs.

I don't know if there's any kind of optimization that might be done to EventLogReader in order to get the message faster, I couldn't find anything either on MS documentation nor on the Internet.

3) I also found that you can read the log entries by using a class called EventLog. However, this technology does not allow you to enter any kind of filters so you basically have to load the entire list of logs to memory and then filter it out according to your needs.
Here's an example:

> EventLog eventLog = EventLog.GetEventLogs().FirstOrDefault(el => el.Log.Equals("Security", StringComparison.OrdinalIgnoreCase));
> var newEntries = (from entry in eventLog.Entries.OfType<EventLogEntry>()
>                                       orderby entry.TimeWritten ascending
>                                       where entry.TimeWritten > takefrom
>                                       select entry);

Despite of being faster in terms of getting the message, the use of memory might be high and I don't want to cause any issues on the devices where this solution will get deployed.

Can anybody help me with this? I cannot find any workarounds or approaches to achieve something like this.

Thank you!.

**Comment by Anipik** [comment]
Related to https://github.com/dotnet/runtime/issues/34568

**Comment by ericstj** [comment]
Now that #34568 is fixed the scenario of using EventLogReader for this purpose should be more feasible.  @lucasalvarezlacasa can you give this a try with the latest 5.0 packages and see if it works for you?

**Comment by ericstj** [comment]
Closing due to lack of response.  Let me know if you have a chance to try and it and still find issues.
