### ISSUE TITLE
Documentation - Cross-Platform-Cryptography Update OAEP SHA-2 Padding Support Matrix

### ISSUE THREAD

**Issue by miketheitguy** [dotnet/runtime#28018]
Cross Platform Cryptography document mentions that OAEP SHA-2 padding is not available on Linux. But it looks like support for this was added per: https://github.com/dotnet/corefx/issues/2523

Also appears to be called out here: https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1#api-changes

And using RSA.Encrypt & Decrypt on Linux specifying OAEP-SHA256 Padding appears to work without an error (using .NET Core 2.1 and PowerShell  6.1.1).

**Comment by vcsjones** [comment]
Closing this out as the [Cross-platform cryptography in .NET](https://learn.microsoft.com/dotnet/standard/security/cross-platform-cryptography#rsa) guide is up-to-date and correctly notes that OAEP SHA-2 is supported on Linux/OpenSSL.
