### ISSUE TITLE
Option to allow HttpClient to follow HTTPS -> HTTP redirects

### ISSUE THREAD

**Issue by martin-heralecky** [dotnet/runtime#28039]
API Proposal:
```c#
class SocketsHttpHandler
{
    bool DangerousAllowHttpsToHttpRedirection { get; set; }
}
```

---------------------------------------------

Currently `HttpClient` does not follow HTTPS -> HTTP redirects. However, even though this increases security, sometimes it is necessary to follow these redirects.

I suggest to add an option which would make HttpClient follow HTTPS -> HTTP redirects.

**Comment by TonyValenti** [comment]
Is there any ETA on this?  We could really use this as well.

**Comment by karelz** [comment]
@TonyValenti no ETA.
The demand is not that strong (please upvote top post to help us keep track of that) and there are some workarounds.
Given that the last +1 took 2 years, I am tempted to close it as Won't Fix at this moment.

**Comment by karelz** [comment]
Closing as Won't Fix for now due to complexity, security concerns and low demand.
If you stumble upon it and need it, please upvote top post and reply here. Thanks!
