### ISSUE TITLE
Enumerable.Repeat should allow for infinite repetition

### ISSUE THREAD

**Issue by ahoka** [dotnet/runtime#28041]
Enumerable.Repeat should have an overload with the following signature:

public static System.Collections.Generic.IEnumerable<TResult> Repeat<TResult> (TResult element);

The behavior would be repeating the value infinitely to allow composing lazy sequences without having to provide int.MaxValue or similar workarounds (which have the obvious limitation of having a bound).

~~~cs
static class Example
{
    public static IEnumerable<bool> ToBinary(uint i) => Enumerable.Repeat(i)
              .Select((num, shift) => num >> shift)
              .TakeWhile(x => x != 0)
              .Select(x => (x & 1) == 1);
}
~~~

**Comment by stephentoub** [comment]
Thanks for the suggestion.  It's been years since this was opened, it's a niche use case, and it's garnered little interest.  It's also trivial to write an iterator that provides this behavior if it's desired:
```C#
static IEnumerable<T> Repeat<T>(T item)
{
    while (true) yield return item;
}
```
Given that, I'm going to close this.  Thanks.
