### ISSUE TITLE
Dynamic call dispatch prefers implicit conversion to a type to implement interface over simple overload with object parameter. 

### ISSUE THREAD

**Issue by lostmsu** [dotnet/runtime#28050]
Subj.

The code below throws at `RuntimeHelpers.EnsureSufficientExecutionStack();`

What happens is `Accept((dynamic)container)` in `Main` and `Accept((dynamic)container.Get())` both choose `Accept<T>(IContainer<T>)` overload via a call to `Container<T>` implicit conversion operator (e.g. they wrap passed value back into `Container<T>` box).

What blew my mind is that creating identical `Container2<T>` does not cause it to fail due to ambiguity.

```csharp
using System;
using System.Runtime.CompilerServices;

class Program {
    static void Main(string[] args) {
        var container = new Container<object>("42");
        Accept((dynamic)container);
    }

    static void Accept(object obj) { Console.WriteLine(nameof(obj)); }
    static void Accept(int i32) { Console.WriteLine(nameof(i32)); }

    static void Accept<T>(IContainer<T> container) {
        RuntimeHelpers.EnsureSufficientExecutionStack();
        Accept((dynamic)container.Get());
    }
}

public interface IContainer<out T>{
    T Get();
}

public struct Container<T>: IContainer<object> {
    readonly T value;
    public Container(T value){ this.value = value; }
    public static implicit operator Container<T>(T value) => new Container<T>(value);
    public object Get() => this.value;
}
```

The issue on SO: https://stackoverflow.com/questions/53608414/why-does-dynamic-call-dispatch-prefer-double-conversion-to-invoking-object-overl

**Comment by jaredpar** [comment]
Closing as this bug is not specific to .NET Core as it also reproduces on .NET Framework. This library is effectively archived and this does not meet [our bar](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/README.md) for changes.
