### ISSUE TITLE
Inconsistent GetRuntimeProperties() Behavior

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#28056]
In the following example:
```c#
public class Test : TestBase
{	
	public new string Value { get; }
}

public class TestBase
{
	public string Value { get; }
}
```

If you call `typeof(Test).GetRuntimeProperties()` it only returns 1 property. If you change the property type in the `Test` class to something else (i.e. `int`) then it returns 2 properties. That behavior clearly doesn't make sense - I believe it should be returning both properties in both situations.

**Comment by steveharter** [comment]
It does appear to be a bug - according to the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.runtimereflectionextensions.getruntimeproperties?view=netcore-3.1#remarks) inherited members should be included, and in this case these are two independent (non-virtual) methods so both should be returned.

We need to get approval for changing this as it could be classified as a "breaking change".

cc @GrabYourPitchforks

**Comment by steveharter** [comment]
Moving to future based on schedule + priority.

**Comment by buyaa-n** [comment]
This bug been there since dotnet .NET Framework 1.0 so fixing this now could be quite breaking, as it is quite edge case scenario does not feel it is worth fixing. 

@mikernet how important the fix for you? What is the scenario where you need this hidden parent property?
