### ISSUE TITLE
System.IO.Compression assembly load failure in Net47

### ISSUE THREAD

**Issue by jwang98052** [dotnet/runtime#28081]
I got the following error at runtime:
"Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified."

This is in my csproj file:
<TargetFramework>net47</TargetFramework>

I see System.IO.Compression.dll 4.2.0.0 is at my working folder. And AutoGenerateBindingRedirects in app.config point to 4.2.0.0. But still get this runtime exception. 

Similar error happens for System.Net.Http.dll
"cannot find the file specified.,Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.,Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.]"

**Comment by ViktorHofer** [comment]
Closing because we haven't heard back for a while.
