### ISSUE TITLE
[Android] cross build script seems out of date?

### ISSUE THREAD

**Issue by yanzhenms** [dotnet/runtime#28103]
Is Android cross build tested on current master branch?

After fix the package version issue, I run cross/build-android-rootfs.sh, it prompts to run 
```CONFIG_DIR=`realpath cross/android/arm64` ROOTFS_DIR=`realpath /home/yanzhen/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot` ./build-native.sh -debug -buildArch=arm64 -- verbose cross``` but the native-build.sh doesn't exist here any more.

Then I found it in /src/Native/, but build with this script still generate a lot of errors. Is it tested on current master branch or not?

**Comment by ViktorHofer** [comment]
Closing as these scripts don't live anymore in the repository.
