### ISSUE TITLE
Add NullIfEmpty and NullIfWhitespace for string

### ISSUE THREAD

**Issue by wanton7** [dotnet/runtime#28113]
Add `string.NullIfEmpty(str)` and `string.NullIfWhitespace(str)` or add them as extension methods for string like @jnm2 described here https://github.com/dotnet/csharplang/issues/183

**Comment by GrabYourPitchforks** [comment]
Is there any reason it's not feasible to introduce these as extension methods inside your own project? They're each one-liners.

**Comment by Thaina** [comment]
> Is there any reason it's not feasible to introduce these as extension methods inside your own project? They're each one-liners.

It's not feasible to include it in each and every projects on every platform I could use C#

**Comment by jnm2** [comment]
I've stopped carrying them around at this point, but I carry around so many other helpers that I would have said it was feasible to continue the trail of copy/paste for me personally.

**Comment by stephentoub** [comment]
There are a huge number of possible trivial helpers one could imagine wanting for things like this, and we're not going to add them all to the core libraries.  These are simple to just open-code, e.g.
```
Method(str == "" ? null : str);
```
if that behavior is needed, or one can easily define their own extension methods to help with this if they really find themselves doing it frequently.  I appreciate the suggestion, but I'm going to close this. Thanks.
