### ISSUE TITLE
Extend ProcessStartInfo to allow setting LOGON_NETCREDENTIALS_ONLY

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#28114]
In the current [code](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L530), the only logon flag that is settle is `LOGON_WITH_PROFILE`.  However, as a security precaution, enterprises are starting to enable policy to restrict service accounts to use non-interactive logon token.  `ProcessStartInfo` doesn't provide a way to specify the `LOGON_NETCREDENTIALS_ONLY` logon flag.  Ask is to add a new boolean property `AsNetCredentialOnly` to `ProcessStartInfo` that will set the appropriate logon flag.

**Comment by eiriktsarpalis** [comment]
Hi @SteveL-MSFT, this seems like a useful addition, but I'm not sure that `AsNetCredentialOnly` is a good name for such a property. I would probably use the following:
```diff
namespace System.Diagnostics.Process
{
    public class ProcessStartInfo 
    {
        public bool LoadUserProfile { get; set; }
+       public bool LoadNetCredentialsOnly { get; set; }
    }
}
```
Specifying both flags should result in an `ArgumentException` being thrown, unless running on non-windows platforms where the flag should be a no-op.

**Comment by terrajobst** [comment]
* The existing API already deviated from the Win32 naming convention (`Load`)
* We should give it a better name, to make it clear what it does
* We should mark the API as Windows-specific

```C#
namespace System.Diagnostics.Process
{
    public class ProcessStartInfo
    {
        public bool LoadUserProfile { get; set; }
        public bool UseCredentialsForNetworkingOnly { get; set; }
    }
}
```

**Comment by am11** [comment]
> Windows-specific

In case of Unix, `bash` for instance has `--norc` and `--noprofile` args, which can be implied with:

```c#
psi.LoadUserProfile = false;
psi.UseShellExecute = true;
```

**Comment by eiriktsarpalis** [comment]
Pushing to future. I wasn't able to get the happy path to work on my prototype, so will need to spend more time on this implementation. At the same time, the test for `ProcessStartInfo.LoadUserProfile` is long disabled (#18978). We should probably attempt to address the two issues at the same time.
