### ISSUE TITLE
[arm32/Windows] Microsoft.Win32.SystemEvents failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28144]
Running the arm32 tests on windows for Microsoft.Win32.SystemEvents produced the following results: passed 1/207 tests.

All (but 1) tests fail when running the tests on Windows10 IoT core. Most likely this is because FindWindow PInvoke doesn't work on Windows IoT. Should we generate an arm implementation that just throws PlatformNotSupported?

cc: @ericstj

**Comment by jkotas** [comment]
Windows Arm32 is no longer supported.
