### ISSUE TITLE
[arm32/Windows] System.IO.FileSystem.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28165]
Running the arm32 tests on windows for System.IO.FileSystem.Tests produced the following results: passed 5919/5926 tests.

The 7 failures are caused by different issues. Attaching the testresults.xml in order to investigate further.

[testResults.zip](https://github.com/dotnet/corefx/files/2673255/testResults.zip)

**Comment by jkotas** [comment]
Windows Arm32 is no longer supported.
