### ISSUE TITLE
[arm32/Windows] System.Net.Http.Functional.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28172]
Running the arm32 tests on windows for System.Net.Http.Functional.Tests produced the following results: passed 5856/5911 tests.

All 55 test failures seem to be caused due to different root causes. Attaching the testResults.xml for further diagnosis.

[testResults.zip](https://github.com/dotnet/corefx/files/2673507/testResults.zip)

**Comment by jkotas** [comment]
Windows Arm32 is no longer supported.
