### ISSUE TITLE
Removal of reference assemblies left behind a ref placeholder

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#28193]
The [change](https://github.com/dotnet/corefx/commit/03bad43b5b063b46fdea07c2e292cf880bafb063) to set ExcludeReferenceAssets isn't excluding the placeholders added by InboxOnTargetFramework: https://github.com/dotnet/buildtools/blob/64e2e93c0560ceb2108c69fdb0d8795d2f7b52ba/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L328-L332

**Comment by ViktorHofer** [comment]
Based on 2.x being out of support the priority for fixing this is low. @ericstj is this issue also observable in our LTS branhces (3.x and master)?

**Comment by ericstj** [comment]
I don't think I'd service for this.  In 6.0 we use the property here: https://github.com/dotnet/runtime/search?q=ExcludeReferenceAssets

Of these, only https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Text.Encoding.CodePages/pkg/System.Text.Encoding.CodePages.pkgproj uses "InboxOnTargetFramework".

I expect we can just fix this when converting that to CSProj.  No need to add the ref placeholders.  cc @Anipik

**Comment by ViktorHofer** [comment]
Agreed, I don't see a reason to service for this either. Closing the issue then.
