### ISSUE TITLE
Add flag Enum methods

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/runtime#28199]
Moved from dotnet/runtime#20008 

Enums are essential commonly used types but have several areas in need of improvement. There should be better support for flag enums, bit-masked enums with the `FlagsAttribute` applied. Support for enum validation should be improved to support flag enums.

## Rationale and Usage
1. Support for flag enums is limited to just the `HasFlag` method which isn't type-safe, is inefficient, and is ambiguous as to whether it indicates if the value has all or any of the specified flags. It's also visible to all enum values whether it's a flag enum or not.
2. Built-in support for enum validation is currently limited to the `IsDefined` method which doesn't support flag enum combinations and is inefficient due to a lack of caching of reflection results.

What used to be this to validate a flag enum value

```c#
MyFlagEnum value = ???;
bool isValid = (value & Enum.GetValues(typeof(MyFlagEnum))
    .Cast<MyFlagEnum>()
    .Aggregate((working, next) => working | next)) == value;
```

now becomes just this

```c#
MyFlagEnum value = ???;
bool isValid = value.IsValidFlagCombination();
```

With this implemented it will address dotnet/runtime#14084 and dotnet/runtime#18190.

## Proposed API
```diff
 namespace System {
     public abstract class Enum : ValueType, IComparable, IConvertible, IFormattable {
-        public bool HasFlag(Enum flag);
+        [Obsolete("Use FlagEnum.HasAllFlags or FlagEnum.HasAnyFlags instead"), EditorBrowsable(EditorBrowsableState.Never)] public bool HasFlag(Enum flag);
+        public static bool IsFlagEnum<TEnum>() where TEnum : struct, Enum;
+        public static bool IsFlagEnum(Type enumType);
     }
 }
 // Separate namespace and class to make flag enum extension methods' visibility optional
+namespace System.Flags {
+    public static class FlagEnum {
         // Generic API
+        public static TEnum AllFlags<TEnum>() where TEnum : struct, Enum;
+        public static TEnum CombineFlags<TEnum>(this TEnum value, TEnum flags) where TEnum : struct, Enum;
+        public static TEnum CombineFlags<TEnum>(TEnum flag0, TEnum flag1, TEnum flag2) where TEnum : struct, Enum;
+        public static TEnum CombineFlags<TEnum>(TEnum flag0, TEnum flag1, TEnum flag2, TEnum flag3) where TEnum : struct, Enum;
+        public static TEnum CombineFlags<TEnum>(TEnum flag0, TEnum flag1, TEnum flag2, TEnum flag3, TEnum flag4) where TEnum : struct, Enum;
+        public static TEnum CombineFlags<TEnum>(params TEnum[] flags) where TEnum : struct, Enum;
+        public static TEnum CombineFlags<TEnum>(IEnumerable<TEnum> flags) where TEnum : struct, Enum;
+        public static TEnum CommonFlags<TEnum>(this TEnum value, TEnum flags) where TEnum : struct, Enum;
+        public static IEnumerable<TEnum> GetFlags<TEnum>(this TEnum value) where TEnum : struct, Enum;
+        public static bool HasAllFlags<TEnum>(this TEnum value) where TEnum : struct, Enum;
+        public static bool HasAllFlags<TEnum>(this TEnum value, TEnum flags) where TEnum : struct, Enum;
+        public static bool HasAnyFlags<TEnum>(this TEnum value) where TEnum : struct, Enum;
+        public static bool HasAnyFlags<TEnum>(this TEnum value, TEnum flags) where TEnum : struct, Enum;
+        public static bool IsValidFlagCombination<TEnum>(this TEnum value) where TEnum : struct, Enum;
+        public static TEnum RemoveFlags<TEnum>(this TEnum value, TEnum flags) where TEnum : struct, Enum;
+    }
+}
```

### `Enum` API Details
* `HasFlag` is being deprecated as it's ambiguous and clutters up the intellisense as it's always accessible to all enum values. Using `System.Flags.FlagEnum.HasAllFlags` removes the naming ambiguity and since it's in a separate namespace it'll only be visible within a source file when the file explicitly includes `System.Flags`.
* `IsFlagEnum` indicates if the enum has the `FlagsAttribute` applied.

### `FlagEnum` API Details
The flag enum operations are defined in the separate `FlagEnum` class in the `System.Flags` namespace to make flag enum extension methods' visibility optional.

* `CombineFlags` returns the bitwise OR of the values. The name was chosen as it mirrors the naming of `Delegate.Combine`.
* `CommonFlags` returns the bitwise AND of the values.
* `AllFlags` returns all enum members' values that are powers of two bitwise ORed together.
* `GetFlags` retrieves each valid flag included in the value in increasing significance bit order.
* `HasAllFlags` indicates if the value contains all of the specified flags, equivalent to the current `HasFlag`.
* `HasAnyFlags` indicates if the value contains any of the specified flags.
* `IsValidFlagCombination` is defined as `(value & AllFlags) == value`.
* `RemoveFlags` returns value with all of the specified flags removed and is defined as `(value & (~flags))`. The name was chosen as it mirrors the naming of `Delegate.Remove`.

## Implementation Details
Utilizes performance improved implementation from dotnet/runtime#20008.

## Open Questions
* Should the `FlagEnum` class members be instead moved into `System.Enum` and their extension methods would then be visible on all enum values?

## Updates
* Removed non-generic members until good use cases for each are proposed.

**Comment by tannergooding** [comment]
As with https://github.com/dotnet/runtime/issues/14084 this isn't a direction we'd like to move forward on.

The idiomatic bit operations are guaranteed to be efficient where-as these named methods aren't and potentially push users towards a pit of failure.
