### ISSUE TITLE
Make a new interface IRandom

### ISSUE THREAD

**Issue by WenceyWang** [dotnet/runtime#28229]
`System.Random` is using an obscure algorithm and do not support XML Serialization or data contract or sth else.

We have to write another pRNG generator to cover these requirements. It is not wise to let these new class to inheritance `System.Random` because it's not an inheritance, They just have a same interface.

We need a new interface which `System.Random` implement it, which make it possible to write some extension function work for both `System.Random` and other classes that implement this interface.

**Comment by GrabYourPitchforks** [comment]
Going through some old issues which haven't had activity in a while. I don't see anything actionable by the team here. Should this be closed?

**Comment by stephentoub** [comment]
Yup. Thanks.
