### ISSUE TITLE
Activator.CreateInstance<T> with params?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/runtime#28264]
Can we have another overload of the generic [`Activator.CreateInstance<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netcore-2.2#System_Activator_CreateInstance__1) such that accepts a `params object[] args` like the [non-generic one](https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netcore-2.2#System_Activator_CreateInstance_System_Type_System_Object___)?

**Comment by GrabYourPitchforks** [comment]
Closing this out as there has been no response and the scenario for adding this over using the existing API is not clear. Please reopen if the scenario can be clarified.
