### ISSUE TITLE
Have a Type.IsUnmanaged property

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#28286]
Currently we have `Type.IsPointer/IsEnum/IsClass/IsDelegate/IsValueType`, but for unmanaged types (both for taking address of and the unmanaged generic type constraint, there is no easy way to check whether a type T is unmanaged. I suggest there is a `Type.IsUnmanaged` property to reflect this

(Unmanaged type = one with no reference types at any level of the struct)

**Comment by GrabYourPitchforks** [comment]
As mentioned previously, the existing `RuntimeHelpers` API can tell you if a type is unmanaged or not.

For the scenario of being able to take arbitrary binary data and bitblt it across the wire, a proposed `IsUnmanaged` API cannot tell you when it is safe to do this. The type may contain pointers, or the type's ctor may have logic that controls what bit patterns are valid for instances of the type. (`DateTime` is an example of the latter, even though it's "unmanaged".)
