### ISSUE TITLE
Cross-project navigation experience of corefx in VS

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#283]
Loading all corefx projects into VS might be achievable, since the code base is not so much larger than roslyn. (~14k files in roslyn\src, ~20k files in runtime\src\libraries)

**Comment by ViktorHofer** [comment]
For that @stephentoub recently added the following script which generates a solution file for all the libraries: https://github.com/dotnet/runtime/blob/master/src/libraries/GenerateLibrariesSln.ps1

**Comment by stephentoub** [comment]
Closing as addressed by the script.

**Comment by huoyaoyuan** [comment]
Glad to know about it. Please also mention it in the docs.

**Comment by huoyaoyuan** [comment]
@stephentoub  After having a try, F12 is still navigating to binary, because the projects aren't using project references.
I know the progress building corefx is very different from building "normal" projects. Can we setup IDE-only projects, or use some condition only set by IDE, to let the projects consuming project reference?

**Comment by ViktorHofer** [comment]
That's not possible because of targeting reference assemblies instead of the implementation assemblies. That said, @ericstj is experimenting to enable this scenario.
