### ISSUE TITLE
System.Drawing - Font is not scaled on Bitmap with scaled Resolution (Linux platform)

### ISSUE THREAD

**Issue by k0st1x** [dotnet/runtime#28361]
On the Windows platform the Font size (with GraphicsUnit.Point) will increase proportionally depending on the resolution of the Bitmap.
but not on the Linux platform.
sample code:
```C#
const string outputFile = "output";
const int max = 5;
const int originalBitmapSize = 128;
for(int i = 1; i < max + 1; i++) {
    float resolution = 96 * i * 0.75f;
    int size = (int)(originalBitmapSize * resolution / 96);
    using(var bitmap = new Bitmap(size, size))
    using(var font = new Font("Arial", 20f, FontStyle.Regular, GraphicsUnit.Point)) {
        bitmap.SetResolution(resolution, resolution);
        using(var graphics = Graphics.FromImage(bitmap)) {
            graphics.FillRectangle(Brushes.LightBlue, 0, 0, bitmap.Width, bitmap.Height);
            graphics.DrawString("test", font, Brushes.Black, 0, 0);
            bitmap.Save(outputFile + i + ".png", ImageFormat.Png);
        }
    }
}
```
the output "test" string on the Linux platforms will not be enlarged.

**Comment by tarekgh** [comment]
I added Servicing consider as it looks there is some customer need the fix.

**Comment by safern** [comment]
I debugged this and it seems like it is a problem in `libgdiplus.DrawString` my findings are that we're calculating the size in points for the Font correctly and passing down the same values on windows and linux. So it seems like `DrawString` is probably not considering the resolution when writing this. 

There is: https://github.com/mono/libgdiplus/issues/524 copy of this issue in mono. @akoeplinger should we close this?

**Comment by danmosemsft** [comment]
Let's close as this is tracked and owned in mono/libgdiplus.

**Comment by danmosemsft** [comment]
Actually, since we have an active case, maybe it is good to have for a while

**Comment by safern** [comment]
@tarekgh investigated this a couple of months ago and he provided a workaround for this by doing:

```cs
 static Font CreateScaledFont(string familyName, float pointSize, FontStyle style, float dpiResolution)
{
        float fontPointSize = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? pointSize : pointSize * dpiResolution / 96;
        return new Font(familyName, fontPointSize, style, GraphicsUnit.Point);
}
```

`dpiResolution` is the bitmap resolution, if it is not known beforehand it can be read from `Bitmap.HorizontalResolution`.

This is a sample code using this workaround:

```cs
const string outputFile = "output";
const int max = 5;
const int originalBitmapSize = 128;

for (int i = 1; i < max + 1; i++)
{
    float resolution = 96 * i * 0.75f;

    int size = (int)(originalBitmapSize * resolution / 96);

    using (var bitmap = new Bitmap(size, size))
    using (var font = CreateScaledFont("Arial", 20f, FontStyle.Regular, resolution))
    {
        bitmap.SetResolution(resolution, resolution);

        using(var graphics = Graphics.FromImage(bitmap))
        {
            graphics.FillRectangle(Brushes.LightBlue, 0, 0, bitmap.Width, bitmap.Height);
            graphics.DrawString("test", font, Brushes.Black, 0, 0);
            bitmap.Save(outputFile + i + ".png", ImageFormat.Png);
        }
    }
}
```

I will close this issue as we're providing a workaround and also, I will post some of @tarekgh's results there from the investigation he did.
