### ISSUE TITLE
Proposal: Non-generic IReadOnlyDictionary interface

### ISSUE THREAD

**Issue by epa** [dotnet/runtime#28402]
We have non-generic IDictionary but there is no non-generic IReadOnlyDictionary.  Sometimes the non-generic form is useful, even in new code.  I suggest adding non-generic IReadOnlyDictionary and having the generic IReadOnlyDictionary<K,V> implement it, with default implementations provided by the interface (if that is possible in .NET itself and isn't just a C# language feature).

If the generic interface can't start to implement the non-generic one, then the Dictionary<K,V> class should directly implement the non-generic IReadOnlyDictionary, just as it currently implements the generic version.

**Comment by TobiasKnauss** [comment]
A non-generic IReadOnlyDictionary would be helpful on my current problem:
I need to cast an object into a IReadOnlyDictionary, but I don't know the type of key and value.
If the object implemented non-generic IDictionary, I could cast into that, but it does not.
And as there is no non-generic IReadOnlyDictionary, I have no chance but working around it with the dynamic-Keyword. :(

**Comment by danmosemsft** [comment]
Does IReadOnlyDictionary<object, object> help?

**Comment by TobiasKnauss** [comment]
@danmosemsft : Were you talking to me? No, it does not help.

**Comment by epa** [comment]
`IReadOnlyDictionary<object, object>` doesn't help my use case either.

**Comment by danmoseley** [comment]
As with all api-suggestions, the next step here is for someone interested to write up the proposal in the form in the "new API proposal" issue template, and paste here.

**Comment by epa** [comment]
Hi @eiriktsarpalis , please see my comment earlier in this issue, the `GetWithType<T>` extension method.  By taking a non-generic `IDictionary`, the user only has to specify one type parameter, rather than three.  And the generic dictionary classes do implement the non-generic interface so it all works.

However, I'd also like it to work on read-only dictionaries.  But there is no non-generic `IReadOnlyDictionary`.  Symmetry suggests it should exist, and be implemented by both read-only and read-write dictionary classes.

If I change my method to take `IReadOnlyDictionary<K,V>` then the caller can no longer say `mydict.GetWithType<MyClass>(mykey)` but instead has to say `mydict.GetWithType<MyClass,k,v>(mykey)`, where `k` and `v` are the exact key and value types of the dictionary.  That makes the extension method less useful, since its main purpose is to handle dictionaries containing a less specific type and cast to a more specific type at run time.

If C# supported partially inferred type parameters, so the caller could somehow specify the type `T` and leave the other two implicit, then neither the non-generic `IDictionary` or the proposed non-generic `IReadOnlyDictionary` would be needed for my use case.  However, I think that would be a much bigger ask than adding a non-generic read-only dictionary interface, which can be done with no changes to the core language, only an addition to the standard library.

**Comment by eiriktsarpalis** [comment]
I'm still not sure I understand the motivation for this request. Clearly your use case can be fulfilled by `IDictionary`: all read-only and immutable dictionaries shipped in BCL I'm aware of do implement `IDictionary`. For custom dictionary implementations recommendation would be to either implement `IDictionary` or (assuming throwing `NotSupportedException` in write methods is undesirable) `IReadOnlyDictionary<object, object>` can be used instead.

> Symmetry suggests it should exist, and be implemented by both read-only and read-write dictionary classes.

Adding more interface implementations to types is not cheap from a runtime performance perspective. While we do maintain non-generic collections out of backward compatibility concerns, we're not actively adding new features in that space.

**Comment by epa** [comment]
Hi, for the record let me explain a little better.
```
using System;
using System.Collections;
using System.Collections.Generic;

public class A { }
public class B : A { }
public class MyClass
{
    // Export a dictionary for people to look at.
    // They should have read-only access, but for now we have to grant read-write.
    public static Dictionary<string, A> Dict = new Dictionary<string, A>();
}
public static class ExtensionMethods
{
    public static T GetWithType<T>(this IDictionary dictionary, object key)
    {
        if (!dictionary.Contains(key))
            throw new KeyNotFoundException($"No {typeof(T).Name} in dictionary with key={key}");
        object o = dictionary[key];
        if (o is T t) return t;
        throw new ApplicationException(
            $"looking up key {key} gives type {o?.GetType().Name} but type {typeof(T).Name} is required");
    }
}
public class Caller
{
    public static void f()
    {
        // The dictionary is declared to hold base type A,
        // but we know here that the particular key will hold a B.
        // Check that at run time.
        B b = MyClass.Dict.GetWithType<B>("key");
    }
}
```

The `Dict` field has to be a full-blown `Dictionary` type.  This grants other classes write access but I want to give them read access only.  However, I can't do that and still have the extension method work.

- If I change the declared type to `IReadOnlyDictionary<string, A>` then the extension method cannot compile because this doesn't implement `IDictionary`.
- If I change the extension method to accept `IReadOnlyDictionary<K,V>` instead of the generic `IDictionary` then all callers now have to specify three type parameters instead of one.
- However, if a non-generic `IReadOnlyDictionary` existed as a base type of non-generic `IDictionary`, and were implemented by `Dictionary` and other classes, it would all fit together.

**Comment by eiriktsarpalis** [comment]
> If I change the extension method to accept IReadOnlyDictionary<K,V> instead of the generic IDictionary then all callers now have to specify three type parameters instead of one.

I understand the concern however this seems like a niche corner case (the value type being different than the requested type) that wouldn't justify the cost of including yet another interface. Here are a few suggested workarounds you could use instead:

* Use [`ReadOnlyDictionary<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.readonlydictionary-2?view=net-5.0) which implements both generic and non-generic `IDictionary` interfaces and prevents other classes from modifying contents at runtime.
* Write a `GetWithType` extension method that isn't generic on `TKey` and `TValue`.
* Create a subtype of `IReadOnlyDictionary<K, V>` (e.g. `IMyReadOnlyDictionary<K,V>`) that exposes a `GetWithType` method as a default interface method. It should then be trivial to define subclasses of `Dictionary<K,V>` that implement the new interface.
