### ISSUE TITLE
DispatchProxy needs a non-generic Create API 

### ISSUE THREAD

**Issue by AmirShokr** [dotnet/runtime#28419]
Currently DispatchProxy just provides the following Generic API to create a proxy :
  public static T Create<T, TProxy>() {..}

However, when you want to create Proxies dynamically (on the fly) , you need a non-generic method like this:
  public static object Create(Type contract, Type DispatchProxy)

the proposed implementation would be very simple like:

  public static object Create(Type contract, Type DispatchProxy)
        {
            return DispatchProxyGenerator.CreateProxyInstance(DispatchProxy, contract);
        }

**Comment by GrabYourPitchforks** [comment]
As mentioned at https://github.com/dotnet/runtime/issues/28419#issuecomment-454160328, the generic-only implementation is beneficial to our core scenarios. The workaround of using `MakeGenericMethod` has already been talked about here, and it should solve the problem satisfactorily. A custom wrapper or extension method could also assist with this inside your application.
