### ISSUE TITLE
RegularExpressions Groups are assigned even when conditionally not supposed to, unlike PowerShell

### ISSUE THREAD

**Issue by ParadoxGBB** [dotnet/runtime#28427]
This is inconsistent with the PowerShell -match syntax, which is the most confusing part to me because my understanding is that both PowerShell and .NET regular expression are handled by the same library / .NET code. So there shouldn't be a difference in behavior.

My specific application / script needs to use the RegEx.Matches() call for reasons I won't go into here.

Essentially, for a pattern like the example below, there are conditional named groups to capture. If none of those conditions match, no group "title" should be even assigned.

<meta itemprop="name" content="((?:The Late Show[^"]+)|(?:Season[^"]+)|(?<title>[^"]+))"/?>

Sample code (.NET):

```c#
            string input = "<meta itemprop=\"name\" content=\"Season 4\"/>";
            string pattern = "<meta itemprop=\"name\" content=\"((?:The Late Show[^\"]+)|(?:Season[^\"]+)|(?<title>[^\"]+))\"/?>";
            MatchCollection matches = Regex.Matches(input, pattern);
```

Sample code (PowerShell):

For this case, the input text doesn't match any of the preceding conditions, therefore the "title" group is assigned the string between the quotes. This is expected.

```
PS C:\Users\paradox> [RegEx]::Matches('<meta itemprop="name" content="12/20/18 (John C. Reilly, Senator Jeff Flake)"/>', '<meta itemprop="name" content="((?:The Late Show[^"]+)|(?:Season[^"]+)|(?<title>[^"]+))"/?>')


Groups   : {0, 1, title}
Success  : True
Name     : 0
Captures : {0}
Index    : 0
Length   : 79
Value    : <meta itemprop="name" content="12/20/18 (John C. Reilly, Senator Jeff Flake)"/>
```

For this case, because the inut string matches the second condition, the expectation is that the "title" group is not matched (or even assigned). However, "title" is assigned as group with an empty string. This seems like a bug to me.

```
PS C:\Users\paradox> [RegEx]::Matches('<meta itemprop="name" content="Season 4"/>', '<meta itemprop="name" content="((?:The Late Show[^"]+)|(?:Season[^"]+)|(?<title>[^"]+))"/?>')


Groups   : {0, 1, **title**}
Success  : True
Name     : 0
Captures : {0}
Index    : 0
Length   : 42
Value    : <meta itemprop="name" content="Season 4"/>
```

For completeness, note below the discrepancy with PowerShell's -match syntax (and how it works in a more expected fashion). Here's the positive case that is supposed to capture the "title" group:

```
PS C:\Users\paradox> '<meta itemprop="name" content="12/20/18 (John C. Reilly, Senator Jeff Flake)"/>' -match '<meta itemprop="name" content="((?:The Late Show[^"]+)|(?:Season[^"]+)|(?<title>[^"]+))"/?>'
True
PS C:\Users\paradox> $matches

Name                           Value
----                           -----
title                          12/20/18 (John C. Reilly, Senator Jeff Flake)
1                              12/20/18 (John C. Reilly, Senator Jeff Flake)
0                              <meta itemprop="name" content="12/20/18 (John C. Reilly, Senator Jeff Flake)"/>
```

And in this case it matches the second condition. In this case, there is no named capture for "title" (as expected):

```
PS C:\Users\paradox> '<meta itemprop="name" content="Season 4"/>' -match '<meta itemprop="name" content="((?:The Late Show[^"]+)|(?:Season[^"]+)|(?<title>[^"]+))"/?>'
True
PS C:\Users\paradox> $matches

Name                           Value
----                           -----
1                              Season 4
0                              <meta itemprop="name" content="Season 4"/>
```

OS / .NET Versioning (all patches are up to date):

(note that this also reproduces for a configuration on the fast ring)

```
PS C:\Users\paradox> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by stephentoub** [comment]
This is by design.  PowerShell is layering on additional policy.  We're not going to change what Regex due to choices one consumer makes in how to consume the exposed data.
