### ISSUE TITLE
Several BlockingCollection.TryTake inefficiencies

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#28426]
- [ ] It's allocating a new CancellationTokenSource for every call.
- [ ] It's using an OperationCanceledException for control flow in case of CompleteAdding.

I noticed the second issue here as it was causing a measurable perf degradation in a particular scenario with the debugger attached (which makes exceptions even more expensive), and the former is related.

**Comment by verdie-g** [comment]
Hello @stephentoub, is there any alternative to TryTake with no allocations?
