### ISSUE TITLE
FileStream.Flush(true) doesn't flush device buffer on macOS, while it does so on Windows

### ISSUE THREAD

**Issue by maxim-saplin** [dotnet/runtime#28444]
Actual:
FileStream.Flush(OS) calls fsync() on macOS, on Windows it calls FlushFileBuffers().

fsync() - doesn't force device's write buffer flush, Window's FlushFileBuffers() does.

Expected:
macOS's implementation of the Flush() method forces device's buffer flush via fcntl(F_FULLFSYNC)

**Comment by carlossanlop** [comment]
@ptoonen I'll remove the assignment. If you get a chance to take a look at this again, feel free to reassign the issue to yourself.

**Comment by Jozkee** [comment]
> My preference is (2). We just need to convince ourselves that we're ok in a major release taking the behavioral change that FlushAsync no longer has the stronger flushToDisk semantics.

@stephentoub I would personally prefer suggestion 3 over 2; that is keep using fsync for FlushAsync() and change Flush(true) to use fcntl(F_FULLFSYNC). Wouldn't be better to just avoid the breaking change? I guess the downside would be that we wouldn't be consistent between sync and async.

**Comment by stephentoub** [comment]
The consistency is key. Stream.Flush / FlushAsync should be functionally equivalent except for the one piece that one does sync writes and the other async writes. They shouldn't have different levels of strength/ reliability. But more importantly,  FlushAsync doing the equivalent of Flush(true) means it's failing at its one goal,  to be async.

**Comment by stephentoub** [comment]
Actually,  I already fixed that part,  two years ago:
https://github.com/dotnet/coreclr/pull/24902
