### ISSUE TITLE
DispatchProxy doesn't handle Span

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#28468]
This fails with:

System.InvalidProgramException: 'Cannot create boxed ByRef-like values.'

Not sure we can do anything with the existing structure, but this doesn't point to where the problem is.

```csharp
using System;
using System.Reflection;

unsafe interface IFoo
{
    int Frob(Span<int> x);
}

unsafe class Program : DispatchProxy
{
    static void Main(string[] args)
    {
        IFoo myProxy = DispatchProxy.Create<IFoo, Program>();
        int result = myProxy.Frob(default);
        Console.WriteLine($"myProxy.Frob returned {(IntPtr)result}");
    }

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        Console.WriteLine($"Invoked method {targetMethod.Name} with {args.Length} arguments");
        return 42;
    }
}

```

**Comment by GrabYourPitchforks** [comment]
Not being able to pass `Span<T>` and other byref-like types though APIs like `MethodInfo.Invoke` is an existing limitation of the reflection stack. There are no current plans to make this scenario work in .NET 5. Unfortunately this also means `DispatchProxy` and other types which rely on the `MethodInfo.Invoke` infrastructure will not be enlightened to support these concepts.

**Comment by MichalStrehovsky** [comment]
@GrabYourPitchforks i opened the issue because the exception is unactionable. It doesn't say what's wrong. We just fall at JIT time. I would think we would want to be more helpful to customers than generate bad code and let JIT fall.
