### ISSUE TITLE
DispatchProxy doesn't handle ref returns

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#28467]
Not sure if anything can be done with the existing structure to make this work, but this fails with:

System.ArgumentException: 'Cannot get TypeToken for a ByRef type.'

This doesn't really point to where the problem is.

```csharp
using System;
using System.Reflection;

unsafe interface IFoo
{
    ref int Frob();
}

unsafe class Program : DispatchProxy
{
    static void Main(string[] args)
    {
        IFoo myProxy = DispatchProxy.Create<IFoo, Program>();
        int result = myProxy.Frob();
        Console.WriteLine($"myProxy.Frob returned {(IntPtr)result}");
    }

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        Console.WriteLine($"Invoked method {targetMethod.Name} with {args.Length} arguments");
        return 42;
    }
}
```

**Comment by steveharter** [comment]
Same issue as https://github.com/dotnet/runtime/issues/28468 - the reflection layer doesn't support this.

**Comment by MichalStrehovsky** [comment]
@steveharter Also same as #28468 - I opened this because the exception message is unactionable. DispatchProxy generates bad IL and lets some other component fail with a cryptic message. I would think we can do better than that, but it's your call whether that's an acceptable customer experience.
