### ISSUE TITLE
LdapConnection BeginSendRequest Throws PlatformNotSupportedException in .NET Core 2.2

### ISSUE THREAD

**Issue by gh5692** [dotnet/runtime#28470]
LdapConnection.BeginSendRequest uses BeginInvoke which is not supported in .NET Core.

`<TargetFramework>netcoreapp2.2</TargetFramework>`

`<PackageReference Include="System.DirectoryServices.Protocols" Version="4.5.0" />`

> System.PlatformNotSupportedException: Operation is not supported on this platform.
>    at System.DirectoryServices.Protocols.GetLdapResponseCallback.BeginInvoke(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeout, Boolean exceptionOnTimeOut, AsyncCallback callback, Object object)
>    at System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, TimeSpan requestTimeout, PartialResultProcessing partialMode, AsyncCallback callback, Object state)
>    at System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, PartialResultProcessing partialMode, AsyncCallback callback, Object state)

**Comment by Telison** [comment]
If this library is a complete rewrite it would make sense to expose a method that looks something like this:

Task<DirectoryResponse> LdapConnection.SendAsync(DirectoryRequest request, ...)

**Comment by mackie1001** [comment]
`BindAsync()` would be nice too.

**Comment by stephentoub** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/36690 which was fixed by https://github.com/dotnet/runtime/pull/37774 for .NET 5.
