### ISSUE TITLE
Ref assemblies should not drop [Pure] attribute from APIs

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#28488]
The Pure attribute is checked by Rule CA1806 in Microsoft.CodeQuality.Analyzers. The `[Pure]` attribute helps prevent many bugs, particular around APIs such as the immutable collections where folks frequently make such mistakes as this:

```cs
    public static void FOo()
    {
        var list = ImmutableList.Create<int>();
        list.Add(3);
    }
```

If `ImmutableList<T>.Add(T)` had the `[Pure]` attribute on it, the CA1806 analyzer mentioned above would produce an error in the above snippet, thereby helping the developer avoid a bug.

In fact the `Add` method *does* have a `[Pure]` attribute on it:

https://github.com/dotnet/corefx/blob/abc7e38a7a6bb0eed6a972127438685d7e9cbc98/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs#L222-L223

But the ref assembly drops these attributes, rendering all the effort we went to in tagging these pure methods to no effect.

In the below example, the call to `ImmutableList<int>.Add` does not produce a warning, but the next call to the sample's own `Add` method _does_ produce a warning, because the `[Pure]` attribute is actually there.

```cs
    public static void FOo()
    {
        var list = ImmutableList.Create<int>();
        list.Add(3);
        Add(3, 5);
    }

    [Pure]
    public static int Add(int a, int b) => a + b;
```

Can whatever build process that generates these ref assemblies be fixed to preserve this attribute?

_Originally posted by @AArnott in https://github.com/dotnet/corefx/pull/31071_

**Comment by ViktorHofer** [comment]
@ericstj what should we do here? I know that we made changes to GenAPI and our other tools, so this might already be fixed?

**Comment by AArnott** [comment]
@ViktorHofer There is still no `[Pure]` attribute on `ImmutableList<T>.Add` on the very latest preview of the package on nuget.org.

**Comment by ericstj** [comment]
Yeah, this is not fixed.  I think we should just consider adding CONTRACTS_FULL as a default define in the dotnet/runtime build then updating the reference assemblies that are impacted.  Any objections?

**Comment by ericstj** [comment]
So Immutable.Collections is the only assembly that actually needs this, so I'll just constrain the Define to that assembly.

**Comment by AArnott** [comment]
@ericstj If no other assembly has `[Pure]` attributes in it, that's a shortcoming of other assemblies, IMO, as there are certainly other APIs that are side-effect free and *should* be attributed as such. Have you confirmed that indeed no other assembly uses this attribute? 
If/when we add this attribute in other appropriate places, is propagating this "fix" as simple as adding the Define to its project?

**Comment by ericstj** [comment]
> that's a shortcoming of other assemblies, IMO

I'm not going to debate on the value of Contracts here.

> Have you confirmed that indeed no other assembly uses this attribute?

Yes.  The only other place its used is internally in System.Runtime.WindowsRuntime, so it has no impact on that reference assembly.

> is propagating this "fix" as simple as adding the Define to its project?

Yes, and this is actually consistent with what you'd need to do in a customer project if you wanted to ship the usage of the Pure attribute.  If a create a new project with "[Pure]" on APIs and compile normally the attribute doesn't perist in the assembly.  If I add a define of CONTRACTS_FULL then it does.

**Comment by ericstj** [comment]
Per discussion we're actually planning to remove the Pure attribute usage: https://github.com/dotnet/runtime/pull/35118#discussion_r410679735

**Comment by ericstj** [comment]
m,nj ?M Y(9/'-

**Comment by stephentoub** [comment]
@ericstj, should this be closed now, or is it still tracking work?

**Comment by ViktorHofer** [comment]
Triage: @ericstj will take a look

**Comment by ericstj** [comment]
We agreed to stop using Pure and removed its usage from the codebase.  We could now remove the exception from our attribute lists; @Anipik feel free to clean that up.  Closing this as the OP is addressed
