### ISSUE TITLE
Expression Tree switch: cannot compile if labels inside the body

### ISSUE THREAD

**Issue by marco6** [dotnet/runtime#28485]
I am facing a very strange problem while playing with Expression Trees. Take this simple code:

```
var label = Expression.Label();
var parameter = Expression.Parameter(typeof(string));
var test = Expression.Lambda<Action<string>>(
    Expression.Switch(
        parameter,
        Expression.Block(
            Expression.Label(label),
            Expression.Call(
                typeof(Console).GetMethod("WriteLine", new[] { typeof(string) }),
                Expression.Constant("Default case")
            )
        ),
        Enumerable.Range(0, 7).Select(i => Expression.SwitchCase(
            Expression.Call(
                typeof(Console).GetMethod("WriteLine", new[] { typeof(string) }),
                Expression.Constant($"I am {i}")
            ),
            Expression.Constant($"{i}")
        )).ToArray()
    ),
    parameter).Compile();
```
This is a very simple switch statement and should be equivalent to:
```
value => {
	switch(value)
	{
		case "0":
			Console.WriteLine("I am 0");
			break;
		case "1":
			Console.WriteLine("I am 1");
			break;
		case "2":
			Console.WriteLine("I am 2");
			break;
		case "3":
			Console.WriteLine("I am 3");
			break;
		case "4":
			Console.WriteLine("I am 4");
			break;
		case "5":
			Console.WriteLine("I am 5");
			break;
		case "6":
			Console.WriteLine("I am 6");
			break;
		default:
			mylabel:
			Console.WriteLine("Default case");
			break;
	}
};
```

The main problem is that the compilation of this expression will fail, but **only if** the number of cases is >= 7 (not including the default one). 

By looking at the [source code](https://github.com/dotnet/corefx/blob/bc0cfc49d1a8c1681fb09603f3389ef65342d542/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.Statements.cs#L636) the problem is with the implementation of the HashTable (so, only if strings are used in the switch statement). On line [734](https://github.com/dotnet/corefx/blob/bc0cfc49d1a8c1681fb09603f3389ef65342d542/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.Statements.cs#L734) a new switch case gets created and checked for the presence of labels wich in turn were already defined when the first expression was analyzed.

The only work-around I can think of includes using a custom method to compare (so that the expression generates if-else statements instead of a switch, but it has a performance hit on the application we are developing and it just doesn't _feel_ the right thing to do.

As a side-note, what I'm trying to achieve (not in the sample code) is a:
`goto default;`
instruction inside my switch cases, so if there is any way to generate it without a label, I am open to use it!

**Comment by jaredpar** [comment]
Closing as this bug is not specific to .NET Core as it also reproduces on .NET Framework. This library is effectively archived and this does not meet [our bar](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/README.md) for changes.

**Comment by marco6** [comment]
@jaredpar so where should I file this bug?

**Comment by jaredpar** [comment]
@marco6 this is the appropriate place to file the bug as it contains the .NET Core implementation and we can also make decisions about whether to backport fixes to .NET Framework. As noted above though the bug doesn't meet our current servicing bars.
