### ISSUE TITLE
API Proposal: Console.CancellationToken

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#28510]
To compose better with `async` and particularly `Task Main(...)` it would be good to have a `CancellationToken` for Console
```csharp
public partial sealed class Console
{
    public static CancellationToken CancellationToken { get; }
    public static void ResetCancellation(); // reissues the CancellationToken so a new cancellation can be listened to
}
```

Other signals would be desirable like `sighup`, but that might be unix only?

/cc @terrajobst @vcsjones

**Comment by carlossanlop** [comment]
Triage:
We feel that CancellationToken is not the appropriate abstraction for representing keyboard cancellation events. As Stephen demostrated in [his code snippet](https://github.com/dotnet/runtime/issues/28510#issuecomment-457444141), it is fairly straightforward to represent key cancellations as CancellationTokens.

We are inclined to close this. Feel free to reopen if you'd like to continue the conversation.
