### ISSUE TITLE
Add target to ApiCompat.proj that determines when the baseline shrinks

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/runtime#28571]
Right now, unless a dev manually updates the baseline files for APICompat, we have no way of knowing if a check that's currently in the baseline has stopped triggering. We get an error when new checks pop up, so we'll know if the baseline grows, but nothing happens when old checks disappear, so we don't know if the baseline shrinks.

We could try writing to the baseline during every build, in addition to throwing an error if we trigger checks that weren't previously in the baseline.

CC @ericstj @terrajobst

**Comment by ViktorHofer** [comment]
Closing as I recently leveraged the ApiCompat's `ValidateBaseline` switch in ApiCompat.proj. That said, it's disabled right now because of a temporary issue tracked in https://github.com/dotnet/runtime/issues/68730.
