### ISSUE TITLE
Mishandled serialization on some Exception types with non-serializable fields

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#28607]
Not all Exception types are serializable but for those (listed below) they serialize a private field of arbitrary type that may not be serializable:

- SwitchExpressionException
- InvalidOperationException
- ArgumentOutOfRangeException
- RuntimeWrappedException 
- XmlSchemaValidationException
- SecurityException

For them, we need to use the ToString() value for the non serializable types.

Sample snippet to use:
```c#
        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            base.GetObjectData(info, context);
            if (UnmatchedValue is null) 
            {
                info.AddValue(nameof(UnmatchedValue), null, typeof(object));
            }
            else
            {
                info.AddValue(nameof(UnmatchedValue), UnmatchedValue.GetType().IsSerializable ? 
                    UnmatchedValue : UnmatchedValue.ToString(), typeof(object));
            }
        }
```

Refer to: https://github.com/dotnet/corefx/pull/34954#discussion_r252381080

cc: @danmosemsft

**Comment by joperezr** [comment]
Marked as up for grabs to fix only the XmlException as suggested above.

**Comment by danmosemsft** [comment]
I'm going to close this one because we don't want to increase the functionality of binary serializer. We could reconsider if someone was seriously impacted.
