### ISSUE TITLE
LockBits return wrong BitmapData when rectangle has smaller width and height

### ISSUE THREAD

**Issue by vano-maisuradze** [dotnet/runtime#28600]
Here is the 5X4 image, which has different colors. Download it from here: ![source](https://user-images.githubusercontent.com/22524885/52162218-fddf0e00-26e9-11e9-9fc3-d5c541198419.png)

Colors from interesting locations are given below:
...
(1,1) -> Blue 
(2,1) -> Green
(3,1) -> Black
(4,1) -> White
(1,2) -> Red
(2,2) -> Yellow
(3,2) -> Magenta
...

If I use the code below, rgb array will have pixel data from (1,1), (2,1), (3,1), (4,1) which is wrong (basically it ignores rectangle's width and height and just returns next 4 pixel bytes). 
As you can see, I've used rectangle which starts from (1,1) and has width and height 2. So correct value would be bytes from (1,1), (2,1), (1,2), (2,2) locations, otherwise, it doesn't make sense why should I use rectangle at all.

    var bitmap = new Bitmap($"{Environment.CurrentDirectory}\\source.png");

    // Lock the bitmap's bits.  
    var rect = new Rectangle(1, 1, 2, 2);
    var bmpData = bitmap.LockBits(rect, ImageLockMode.ReadWrite, bitmap.PixelFormat);

    // Get the address of the first line.
    IntPtr ptr = bmpData.Scan0;
            
    var depth = Image.GetPixelFormatSize(bitmap.PixelFormat);
    var pixelCount = rect.Width * rect.Height; // 2 X 2 = 4
    var rgb = new byte[pixelCount * (depth / 8)]; // 12 bytes

    // Copy data from pointer to array
    System.Runtime.InteropServices.Marshal.Copy(ptr, rgb, 0, rgb.Length);

rgb array will have following value (values from index 6 are incorrect):
[0]  255
[1]  0
[2]  0
[3]  0
[4]  255
[5]  0
[6]  0
[7]  0
[8]  0
[9]  255
[10] 255
[11] 255

p.s. I understand Marshal.Copy just copies bytes from pointer, but there should be some way to read bytes from specified rectangle.

**Comment by JeremyKuhne** [comment]
[Answered above](https://github.com/dotnet/runtime/issues/28600#issuecomment-477494328)
