### ISSUE TITLE
New System.Data.Common batching API

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#28633]
This proposal has been approved in principle, subject to confirmation by several database providers that the API shape is good.

Issues tracking provider implementations:

* SqlClient: https://github.com/dotnet/SqlClient/issues/19
* Npgsql: https://github.com/npgsql/npgsql/issues/2317
* MySqlConnector: https://github.com/mysql-net/MySqlConnector/issues/650

---

This issue is based on previous discussions in dotnet/runtime#15375 and dotnet/runtime#17445.

# Background

Batching multiple SQL statements can be critical for database performance, as they can be executed in a single roundtrip rather than waiting for each statement to complete before sending the next one. System.Data.Common doesn't currently provide a first-class API for this, but some providers (e.g. SqlClient) allow batching statements by concatenating them together into DbCommand.CommandText, separated by semicolons:

```c#
var cmd = connection.CreateCommand();
cmd.CommandText = "INSERT INTO table (1); INSERT INTO table (2)";
```

The problem with this approach, is that most databases require separate protocol messages for each statement (e.g. PostgreSQL, MySQL), forcing the database's ADO.NET provider to parse the SQL client-side and to split on semicolons. This is both unreliable (parsing SQL is difficult) and bad for performance - ideally an ADO.NET provider should simply forward user-provided SQL to the database, without parsing or rewriting it (see dotnet/runtime#25022 for a related issue forcing providers to parse SQL).

As a specific case, SQL Server does natively support the multi-statement commands, but even there this has drawbacks for performance, detailed by @GSPP in dotnet/SqlClient#19. Also, as @bgribaudo [pointed out](https://github.com/dotnet/corefx/issues/3688#issuecomment-342158814), the current concatenation-based approach doesn't allow invoking multiple stored procedures in batching fashion. SqlClient does include SqlCommandSet, which performs efficient, non-concatenation-based batching, but that class is internal and currently usable only via DbDataSet, and not for general usage ([NHibernate apparently accesses this via reflection](https://github.com/nhibernate/nhibernate-core/blob/ad4c2ef101cbf8ba798220973f4f78dd795e0896/src/NHibernate/AdoNet/SqlClientSqlCommandSet.cs)). This proposal would allow exposing SqlCommandSet via a public API.

Goals
-----
* Provide a structured way to execute multiple SQL statements in a single roundtrip, without any need for client-side parsing of SQL.
* Keep the API consistent with other ADO.NET APIs, and specifically close to DbCommand (both are "executable"), to reduce the conceptual complexity for adoption.
* Allow mixing in different types of statements in the same batch (insert, update, select). The current concatenation approach supports this, and so does our reader API (multiple resultsets).
* Provide non-aggregated access to the number of rows affected, for each individual command in the batch.

# Proposed API

```c#
public abstract class DbBatch : IDisposable, IAsyncDisposable
{
    public DbBatchCommandCollection BatchCommands => DbBatchCommands;
    protected abstract DbBatchCommandCollection DbBatchCommands { get; }

    public DbBatchCommand CreateBatchCommand() => CreateDbBatchCommand();
    protected abstract DbBatchCommand CreateDbBatchCommand();

    #region Execution (mirrors DbCommand)

    // Delegates to ExecuteDbDataReader
    public DbDataReader ExecuteReader(CommandBehavior behavior = CommandBehavior.Default);
    protected abstract DbDataReader ExecuteDbDataReader(CommandBehavior behavior);

    // Delegate to ExecuteDbDataReaderAsync
    public Task<DbDataReader> ExecuteReaderAsync(CancellationToken cancellationToken = default);
    public Task<DbDataReader> ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken = default);

    protected abstract Task<DbDataReader> ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken);

    public abstract int ExecuteNonQuery();
    public abstract Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken = default);

    public abstract object ExecuteScalar();
    public abstract Task<object> ExecuteScalarAsync(CancellationToken cancellationToken = default);

    #endregion

    #region Execution properties (mirrors DbCommand)

    public abstract int Timeout { get; set; }

    // Delegates to DbConnection
    public DbConnection Connection { get; set; }
    protected abstract DbConnection DbConnection { get; set; }

    // Delegates to DbTransaction
    public DbTransaction Transaction { get; set; }
    protected abstract DbTransaction DbTransaction { get; set; }

    #endregion
    
    #region Other methods mirroring DbCommand
    
    public abstract void Prepare();
    public abstract Task PrepareAsync(CancellationToken cancellationToken = default);
    public abstract void Cancel();
        
    #endregion

    #region Standard dispose pattern

    public void Dispose() { ... }
    protected virtual void Dispose(bool disposing) {}

    #endregion
}

public class DbBatchCommandCollection : Collection<DbBatchCommand>
{
}

public abstract class DbBatchCommand
{
    public abstract string CommandText { get; set; }
    public abstract CommandType CommandType { get; set; }
    public abstract int RecordsAffected { get; }
    
    public DbParameterCollection Parameters => DbParameterCollection;
    protected abstract DbParameterCollection DbParameterCollection { get; }
}

public class DbConnection
{
    public DbBatch CreateBatch() => CreateDbBatch();
    protected virtual DbBatch CreateDbBatch() => throw new NotSupportedException();
    
    public DbBatchCommand CreateBatchCommand() => CreateDbBatchCommand();
    protected virtual DbBatchCommand CreateDbBatchCommand() => throw new NotSupportedException();
    
    // Covers both CreateBatch and CreateBatchCommand
    public virtual bool CanCreateBatch => false;
}

public class DbProviderFactory
{
    public virtual DbBatch CreateBatch() => throw new NotSupportedException();
    public virtual DbBatchCommand CreateBatchCommand() => throw new NotSupportedException();
    
    // Covers both CreateBatch and CreateBatchCommand
    public virtual bool CanCreateBatch => false;
}

public class DbException
{
    public DbBatchCommand BatchCommand => DbBatchCommand;
    protected virtual DbBatchCommand DbBatchCommand => null;
}
```

# General usage and examples

Usage is fairly trivial and aligned with the existing DbCommand APIs. Users first create a new DbBatch, either by calling `DbCommandFactory.CreateBatch()`, or by instantiating one directly. Commands are added into the batch, execution properties (e.g. `Timeout`) are set on it, and finally on of the `Execute*()` methods are called on it. `Connection`, `Transaction` and `Timeout` are specified on the DbBatch, like they are set on DbCommand for un-batched operations.

Here is a code sample using DbProviderFactory for database portability:

```c#
using var batch = dbProviderFactory.CreateBatch();

var cmd1 = dbProviderFactory.CreateBatchCommand();
cmd1.CommandText = "UPDATE table SET f1=@p1 WHERE f2=@p2";
var p1 = dbProviderFactory.CreateParameter();
var p2 = dbProviderFactory.CreateParameter();
p1.Value = 8;
p2.Value = 9;
cmd1.Parameters.Add(p1);
cmd1.Parameters.Add(p2);
batch.Add(cmd1);

var cmd2 = dbProviderFactory.CreateBatchCommand();
cmd2.CommandText = "SELECT * FROM table WHERE f2=@p3";
var p3 = dbProviderFactory.CreateParameter();
p3.Value = 8;
cmd2.Parameters.Add(p3);
batch.Add(cmd2);

batch.Connection = conn;
batch.Transaction = transaction;

using var reader = batch.ExecuteReader();
// read contains one resultset, from SELECT
```

The verboseness of this API corresponds to how ADO.NET currently looks. General usability improvements are planned for later.

Here is a suggested code sample working against a specific provider and using initializers for better readability and terseness:

```c#
using var batch = new XyzBatch
{
    Connection = conn,
    Transaction = transaction,
    BatchCommands =
    {
        new XyzBatchCommand("UPDATE table SET f1=@p1 WHERE f2=@p2")
        {
            Parameters =
            {
                new XyzParameter("p1", 8),
                new XyzParameter("p2", 9),
            }
        },
        new XyzBatchCommand("SELECT * FROM table WHERE f2=@p1")
        {
            Parameters =
            {
                new XyzParameter("p1", 8),
            }
        }
    }
};

using var reader = batch.ExecuteReader();
// read contains one resultset, from SELECT
```

# Design and naming motivations

The original proposal had the batch holding a list of DbCommand instead of the new DbBatchCommand type. The change, originally proposed by @bgribaudo, was motivated by the following reasons:
* DbCommand would have had some dead properties when executed as part of a batch (Connection, Transaction, CommandTimeout).
* DbCommand is disposable, raising various questions around its lifespan (does the command get disposed with the batch or not, is it OK for DbException to reference a disposable object...).

The name DbBatchCommand will hopefully convey the similarity between that type and DbCommand (both hold SQL, parameters and a CommandType), while at the same time keeping them distinct (DbBatchCommand isn't executable outside of a DbBatch). The name DbStatement was also considered, although it seems this would introduce more confusion:
* It's not directly identifiable as a batch component ("why can't I execute it?")
* On some providers (e.g. SqlClient) a single DbBatchCommand can still contain concatenation batching, so a DbStatement would actually contain multiple statements.

# Affected rows

DbCommand has APIs for finding out how many rows were affected by the command:

* The return value of `ExecuteNonQuery[Async]()` returns an int
* The `DbDataReader.RecordsAffected` property

However, both of these provide an aggregate number; if the command contained more than one statement, it's currently impossible to find out how many rows were affected by each statement separately.

Providing non-aggregate affected rows could be done via an overload of `ExecuteNonQuery[Async]()` which returns an `int[]`, or which accepts a user-provided `int[]` and populates it. The approaches have their complexities (perf, array management...), and as we're introducing a new DbBatchCommand dedicated to batching, we propose to simply add a `RecordsAffected` property on it instead. The provider would populate this property for each DbBatchCommand to indicate how many rows were affected by that command.

As with [DbDataReader.RecordsAffected](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.recordsaffected?view=netframework-4.8), this property would contain -1 for SELECT statements, and 0 if no rows were affected or the statement failed.

# Command behavior

`DbCommand.ExecuteReader()` accepts a [`CommandBehavior`](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=netframework-4.7.2) enum which allows execution behavior to be tweaked. Even if it seems to be a rare case, users may need to specify different behaviors for different batch commands. As a result, `DbBatch.ExecuteReader()` does not accept a behavior parameter, and DbBatchCommand has a CommandBehavior property instead.

This requires the user to set any non-default behavior on each and every batch command. A batch-wide default could be accepted by `DbBatch.ExecuteReader()`, but that would require a way to distinguish between the batch default and the enum's default value (`CommandBehavior.Default`), e.g. by making it nullable on the DbCommandBatch. The introduced complexity doesn't seem to be worth it.

Note that not all providers will support all command behaviors on batched commands - it is expected that in some cases the entire batch will have to share the same behavior. Also, CommandBehavior.CloseConnection makes no sense on batched commands except the last, and the provider should probably throw on this.

# DbException.Command

Since we now execute batches, we should provide a way of letting users know which command in the batch triggered an exception. We propose to do this by introducing a new virtual property on DbException, called `BatchCommand`, pointing to the relevant DbBatchCommand instance. In non-batched command execution this property would be left unassigned.

# Notes on batch size management

In some cases, there may be some value in having the provider's batching implementation implicitly manage batch sizes. Examples:

* There may be some database hard limit (on the number of statements, on the number of parameters). The implementation could break down the user-provided batch into several sub-batches, to save the user the trouble of doing that. This would mean wrapping multiple internal readers with a single reader, which isn't trivial (although we could provide an implementation).
    * Note: it seems that the SQL Server 2100-parameter limit will not apply here, as it applies to each individual statement rather than to the batch. So we're not sure we have a good real-world example.
* It may be inefficient to batch statements below a certain number (because of overheads associated with batches). In this case the implementation would simply not batch.
    * For example, with current concatenation-based batching on SQL Server, batching 2 statements performs worse than not batching.

The pro here is to free the user from knowing low-level, database-specific details, transparently increasing perf and reducing friction for everyone (we're assuming the user has no special knowledge which would assist in the decision-making). The con here is more complexity and a general uncertainty that this is needed - any examples from the community would be helpful.

Regardless, this can be viewed as an implementation detail of a provider; although we can provide guidelines, at the end of the day each provider will implement the behavior they desire.

# Backwards-compatibility

As a new API, no breakage is being introduced, but it has been proposed to provide a backwards compatibility shim for the new API that either performs concatenation-based batching, or simply executes without batching at all.

As of now, the decision is to not provide any sort of shim: trying to use the new batching API with providers that haven't implemented support for it will throw a NotSupportedException. The reasons for this are:

* Silently falling to non-batching execution would give the false expectation/illusion of batching without delivering on it.
* Concatenation-based batching doesn't work if the different batched commands have named parameters with the same name (since parameter lists would need to be unified and names must be unique). This is expected to be a common scenario as multiple identical statements are executed with different parameter values (but identical names).
* We want to avoid the complexity and effort of implementing the shim. For example, a non-batching shim would need to somehow combine the readers from the individual commands into a single reader interface for user consumption. We don't think this is worth the effort.
* Most applications work against a single database type, and so can either use the new API or not, based on knowledge of what the provider supports. Multi-database applications (and layers) are much more rare, and it's expected they can take the added burden of detecting whether batching is supported or not, and implementing two code paths.

# Feature detection

As the API will throw for providers which don't implement it, a way must be provided for consumers to know whether the API is supported. The proposal is to add a `CanCreateBatch` bool property to both DbProviderFactory and DbConnection, alongside the `CreateCommandSet()` methods.

# Additional Notes

* No guarantees are made with regards to batch transactionality (do the batch commands execute in an implicit transaction) or to error handling (if a command fails, are later commands automatically skipped). These details are provider-dependent. However, wherever possible, it is suggested that implementations provide both transactionality and skip-on-failure behavior.
* DbBatch is disposable, like DbCommand. This is to allow for cases where it maps to a native resource that needs to be freed, and may also help with pooling/recycling of instances (to be elaborated in a separate proposal).
* We hope to add a `DbBatch.Add(string commandText)`, which would create the CommandText internally and be a lighter API, but some design issues need to resolved around parameter management. We're deferring this for now as it's non-critical sugar.
* An alternative proposal was made by @bgribaudo in #28794, in which a separate DbDataReader is returned for each DbBatchCommand, instead of one covering the entire batch. The goal was to help user identify command boundaries in resultsets when commands return more than one resultset (or even a variable number of resultsets). Due to the assumed rareness of the problem and the existence of other workarounds we think it's better to leave on DbDataReader for the entire batch.

# Open questions

* DbCommand and DbBatch share a lot of surface APIs. In theory there could be an interface capturing those similarities, allowing users to abstract away what's being executed (but suffers from the same versioning flaws of interfaces, modulu default interface methods).
* Does DbBatch need to implement System.ComponentModel.Component, like all other ADO objects (for Visual Studio designer)? There seems to be little change that VS would be updated for this, but possibly for consistency.

# Edit history

Date       | Modification
---------- | ------------
2019-02-14 | DbCommandSet now implements `IEnumerable<DbCommand>` and includes the two `GetEnumerator()` methods, as per @bgrainger's suggestion
2019-02-18 | Updated proposal with different concrete options for backwards compatibility, batch size management, and added a usage example.
2019-02-22 | Updated with the current decision on backwards compatibility (no shim), added feature detection discussion, added non-aggregated rows affected to goals.
2019-02-23 | Added missing `DbConnection.CreateCommandSet()` and renamed `DbProviderFactory.CreateCommandSet()` (it previously had a Db which doesn't belong). Added `CanCreateCommandSet` property to DbProviderFactory, DbConnection.
2019-02-25 | Added public non-virtual `DbConnection.CreateCommandSet()` along protected virtual `CreateDbCommandSet()`
2019-03-04 | Added DbConnection, DbTransaction to DbCommandSet. Corrected ExecuteReaderAsync overloads, corrected some comments.
2019-03-06 | DbCommandSet now includes a Commands list instead of implementing `IEnumerable<DbCommand>` itself.
2019-03-12 | Renamed DbCommandSet to DbBatch, and changed it to hold a new DbBatchCommand type instead of DbCommand. Added readable/terse code sample, added explanatory notes and rearranged sections slightly.
2019-04-18 | Added `CommandBehavior` to DbBatchCommand and removed the `commandBehavior` parameter to `DbBatch.ExecuteReader()`; added a section to explain. Added `RecordsAffected` to DbBatchCommand and updated the affected rows section.
2019-04-20 | Final typo pass (thanks @bgrainger) and added sentence on CommandBehavior support.
2019-05-14 | Note on values of RecordsAffected (for SELECT, for failed statements), add standard Dispose pattern methods to DbBatch, fixed issues raised by @bgrainger |
2019-05-23 | Apply standard ADO.NET pattern to DbBatch with virtual ExecuteDbDataReader and non-virtual ExecuteDataReader
2019-06-17 | Removed DbBatch.CancelAsync() following removal of DbCommand.CancelAsync() in dotnet/runtime#28596, thanks @Wraith2. Replaced `IList<DbBatchCommand>` with `DbBatchCommandCollection`.
2021-06-21 | Make DbException.DbBatchCommand protected
2021-06-29 | Move CommandBehavior from DbBatchCommand to DbBatch.ExecuteReader
2021-07-01 | Remove the setter for DbBatchCommand.RecordsAffected
2021-07-01 | Added DbBatch.CreateBatchCommand and CreateDbBatchCommand

**Comment by cheenamalhotra** [comment]
@roji 

I was referring to `public DbDataReader ExecuteDbReader();` in the proposal if it should be `public DbDataReader ExecuteReader();` instead since it's async counter API is `ExecuteReaderAsync()`?

**Comment by roji** [comment]
Because it's getting quite late in the 5.0 release cycle and a lot of other work remains, we'll be postponing this to 6.0. It's a bit risky to merge such a large/significant API addition at the last minute; I'll likely merge this early for 6.0, to have enough lead-time to get feedback from implementing providers and adjust as needed.

Sorry for anyone expecting this for 5.0...

**Comment by expcat** [comment]
Not pushing.
Any news for this in 6.0?
or still be postponed?

**Comment by roji** [comment]
@expcat still in the plan for 6.0 - this is very high up on my priority list.

**Comment by roji** [comment]
I've just submitted #54467, apologies to all involved in the original discussions that this took so long. I've more or less implemented this proposal for Npgsql in https://github.com/npgsql/npgsql/pull/3860, giving us further confidence that the API shape is correct (beyond @bgrainger's implementation in MySqlConnector and @Wraith2 experimental implementation in SqlClient).

Note that we ideally need to merge this in time for preview6 (in three weeks) to ensure it goes in for .NET 6.0.

Following my implementation, I'm proposing the following two tiny changes to the API proposal:

* DbBatch.BatchCommands
    * This was originally proposed as an `IList<DbBatchCommand>`. [During API review](https://github.com/dotnet/runtime/issues/28633#issuecomment-492347155), it was recommended to make this into a dedicated type (DbBatchCommandCollection), in order to avoid exposing an interface (which users would then likely cast down into a concrete type).
    * Originally, it was proposed that this type extend `Collection<DbBatchCommand>`, which wraps an `IList<T>` (`List<T>` by default); however, during implementation of Npgsql batching support this got in the way; for example, it isn't possible to make it wrap a `List<NpgsqlBatchCommand>` (since `IList<T>` isn't covariant).
    * As a result, I propose that DbBatchCommandCollection simply extend `IList<DbBatchCommand>` directly; this entails a bit more boilerplate for provider implementors, but provides greater flexibility.
* I propose moving DbConnection.CreateBatchCommand and CreateDbBatchCommand to DbBatch, similar to how CreateParameter is on DbCommand and not on DbConnection.

**Comment by roji** [comment]
One additional, possibly more controversial thing...

Our proposal allows specifying different command behaviors for different commands in the batch. Looking at this now, it seems to introduce quite a bit of complexity, as well as API inconsistency with DbCommand, for what would very likely be a very rare edge case. I think we should consider reverting to the DbCommand API of accepting CommandBehavior in ExecuteReader.

Some objections:

* This breaks the symmetry between the DbCommand/DbBatch APIs which we've tried to maintain. This symmetry reduces conceptual load for users understanding the new DbBatch API, and could also be captured in an interface down the road if needed.
* To apply the same behavior to the entire batch, users must manually apply it to each and every batch command.
* From the experience of implementing the batching proposal in Npgsql, this requirement requires quite a bit of rewriting, since behavior currently applies to the resulting DbDataReader as a whole. I can't say for sure this applies to other drivers, and in general implementation concerns shouldn't affect the abstraction design too much, but I sense that the possibility to actually have different behaviors would not be widely supported (@bgrainger any input on this?)
* It's important to remember that it's always possible to split the batch into two for different command behaviors. That does mean an extra roundtrip, but assuming these are exotic edge cases, that seems more than reasonable.

Here are some notes per value of [CommandBehavior](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=net-5.0):

### CloseConnection

This makes no sense in batching, except possibly in the very last DbBatchCommand. We'd have to define the behavior for when it's specify in non-last commands (ignore? apply after the batch?). This value in itself is a an argument for not allowing per-command behavior.

### SchemaOnly

Wanting to mix real command execution (non-SchemaOnly) with SchemaOnly in a batch seems very exotic. You typically either execute or retrieve the schema, but not both in the same batch.

### KeyInfo

This is used to receive extra metadata information when using SchemaOnly. Wanting to get this extra information for some queries and absolutely not wanting it for others doesn't seem useful.

### SequentialAccess

This is the one option which seems remotely plausible - you want to execute multiple commands, one of which has a huge column and should be traversed sequentially. Without per-command behavior, you can still process the entire batch sequentially - there isn't a big downside of that (aside from not being able to access result columns in random fashion).

### SingleResult and SingleRow

As far as I know, these are mainly useful in cases where a stored procedure is being executed, but only the first resultset or row of that sproc is needed, and it's not possible to modify the sproc to accept a parameter managing that. It's possible this could be useful when executing multiple sprocs in a batch, but overall it seems like quite the corner case.

**Comment by bgrainger** [comment]
> From the experience of implementing the batching proposal in Npgsql, this requirement requires quite a bit of rewriting, since behavior currently applies to the resulting DbDataReader as a whole. I can't say for sure this applies to other drivers, and in general implementation concerns shouldn't affect the abstraction design too much, but I sense that the possibility to actually have different behaviors would not be widely supported (@bgrainger any input on this?)

In MySqlConnector, MySqlDataReader does have a (single) `CommandBehavior` associated with the reader as a whole. However, this was only used to support `CommandBehavior.CloseConnection`, which is explicitly disallowed by MySqlConnector for batch commands (even for the last command in a batch). (It seems like this restriction could be relaxed to allow `CloseConnection` only for the last command in a batch, and that would be fairly simple to implement in MySqlConnector.)

Per-command `CommandBehavior` is supported for `SchemaOnly`, `SingleRow`, and `SingleResult`; this does result in `SET sql_select_limit=1;` (or similar) being sent to the MySQL as an optimisation hint (and all other rows are silently discarded). There is one integration test for `CommandBehavior.SingleRow` but the others are untested (so conceivably don't actually work).

No other `CommandBehavior` enum values (`KeyInfo`, `SequentialAccess`) are supported by MySqlConnector (with or without batching).

**Comment by bgrainger** [comment]
> SingleResult and SingleRow
> As far as I know, these are mainly useful in cases where a stored procedure is being executed, but only the first resultset or row of that sproc is needed, and it's not possible to modify the sproc to accept a parameter managing that. It's possible this could be useful when executing multiple sprocs in a batch, but overall it seems like quite the corner case.

FWIW, the only feature request MySqlConnector has had for `CommandBehavior.SingleRow` was for a non-sproc query: https://github.com/mysql-net/MySqlConnector/issues/679.

It does seem like the easier solution would be to add `LIMIT 1` to the query, but I can imagine simple SQL generation scenarios where that's not trivial to add. Dapper automatically adds `SingleRow` to its `QueryFirstOrDefault` call: https://github.com/DapperLib/Dapper/blob/42987a597b9c6b8844b0876e3facfc640f08a5cc/Dapper/SqlMapper.cs#L1182-L1184

In MySql.Data (and now MySqlConnector), this triggers an optimisation that sends a hint to MySQL that only one row should be returned, which can result in a dramatic speed-up in query execution.

I can still see the value of this on a per-command basis.

**Comment by bgribaudo** [comment]
> To apply the same behavior to the entire batch, users must manually apply it to each and every batch command.

Hmm...would it help if the per-batch command CommandBehavior behaved as an override which is applied **only** if it is set? If it is not set then the CommandBehavior from the parent DbCommand would be used (so the parent DbCommand's CommandBehavior applies to all commands in the batch except for any commands whose CommandBehavior is set directly).

**Comment by roji** [comment]
@bgribaudo this was briefly discussed in https://github.com/dotnet/runtime/issues/28633. The problem is that at that point we need a distinction between set-to-default and no-set-at-all, e.g. making behavior nullable on the individual batch commands. While this is possible, it introduces even further complexity for what is really edge-casey.

@bgrainger thanks for the added info. I can also see scenarios where per-command behavior could be useful, but I'm not sure they're useful enough (and often enough) when weighed against the disadvantages (i.e. consistency with the DbCommand API, having to set on all commands, etc.). It's also important to remember that users don't always have to batch everything in every case - there's always the option of not batching for the specific edge case which requires different behaviors; the downside is only an extra roundtrip, rather than blocking some functionality etc.

But I'm definitely OK with going with what people think here.

**Comment by bgrainger** [comment]
> users don't always have to batch everything

This is a good counterpoint.

It also seems plausible to me that some database backends might not even support customising the behaviour on a per-command basis (in order to provide high-efficiency batching). So there's a question of whether the API should expose something that may not be feasible for some providers. (`CommandBehavior.CloseConnection` is perhaps an obvious example of a behaviour that can only be applied to the batch as a whole, not to individual batch commands. OTOH, `CommandBehavior.SingleResult` doesn't really make much sense for a batch (which would frequently be used to retrieve multiple result sets) but could make sense for individual commands.)

I have no objection to moving the `CommandBehavior` to the batch.

**Comment by Wraith2** [comment]
I haven't investigated from the SqlClient perspective so I don't know if any can be used. 
It doesn't really matter, if there is one implementation that can use it at that level it should go into the shared api and the others can ignore or partial implement however they choose.
