### ISSUE TITLE
Add validation for packages with inbox API that is not included in the package

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#28643]
We may cross-compile for netcoreapp and not include new API in the package.

This is problematic if a new version of the package is produced with higher version and less API.

EG: System.Memory.  See https://github.com/dotnet/corefx/commit/11f957988b7e2e9642fa99ab11f50fbf6f74ce13

**Comment by ViktorHofer** [comment]
@ericstj as tfms aren't filtered out anymore when generating packages, do we still want validation for this? I imagine we wouldn't add new APIs during servicing which is the only where we only publish a subset of packages.

**Comment by ericstj** [comment]
Yeah, we can close this now.
