### ISSUE TITLE
Request Thread.Abort to be marked [Obsolete]

### ISSUE THREAD

**Issue by lcsondes** [dotnet/runtime#28664]
We're in the middle of porting a legacy Framework project to Core, and `Thread.Abort()` was a sore point. It compiles without a single warning, and at runtime it just throws a PNSE. Given the legacy status of our code cleanups tend to be wrapped in `catch(Exception)` so this went unnoticed until we saw the memory leaks and traced them back. That one is entirely on us, of course.

If `Abort` doesn't work and it is planned that it never will (which is my understanding) then I think it at the very least should be marked as `[Obsolete]`, maybe even with `IsError=true`.

**Comment by stephentoub** [comment]
@terrajobst, how should issues like this feed into your obsoletion/tooling plans?

**Comment by terrajobst** [comment]
This has been done for .NET 5 so this can be closed. Thanks @jeffhandley for pointing this out to me!
