### ISSUE TITLE
AggregateException.ToString() prints terrible message

### ISSUE THREAD

**Issue by Denis535** [dotnet/runtime#28695]
Let's throw )
```
throw new AggregateException(
    "Error",
    new Exception( "Error 1" ),
    new AggregateException( "Error 2", new Exception( "Error 3" ) ) );
```

If we catch and print this exception then we get a such message:
```
System.AggregateException: Error (Error 1) (Error 2 (Error 3)) ---> System.Exception: Error 1
   --- End of inner exception stack trace ---
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\Den\Desktop\ConsoleApp2\ConsoleApp2\Program.cs:line 17
---> (Inner Exception #0) System.Exception: Error 1<---

---> (Inner Exception dotnet/corefx#1) System.AggregateException: Error 2 (Error 3) ---> System.Exception: Error 3
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: Error 3<---
<---
```

May be for you it's good format, but in my opinion it is terrible. 
I'd like to see something like following:
```
 System.AggregateException: Error
 stack-trace ...
 |-- System.Exception: Error 1
 |   stack-trace ...
 |-- System.AggregateException: Error 2
 |   stack-trace ...
     |-- System.Exception: Error 3
     |   stack-trace ...
```

**Comment by pentp** [comment]
The Flatten() issue was mostly resolved with #605

**Comment by stephentoub** [comment]
Thanks

**Comment by danmosemsft** [comment]
Partly related, last year I made two failed attempts to improve ToString() for nested exceptions

https://github.com/dotnet/coreclr/pull/25045
https://github.com/dotnet/coreclr/pull/27333

I'm not planning to have another go for 5.0 although I do think it's worthy of improvement. I don't think there is an active issue tracking this so anyond reading this should feel free to open one if they care about it.
