### ISSUE TITLE
Add ReadOnlySpan<char> overloads to StringInfo APIs

### ISSUE THREAD

**Issue by ajtribick** [dotnet/runtime#28704]
Currently it is possible to process a string using text elements via the `StringInfo` class and `TextElementEnumerator`. Unfortunately these do not provide overloads for `ReadOnlySpan<char>`. Similarly there are no `ReadOnlySpan<char>` overloads for `CharUnicodeInfo`, where this would be useful to deal with characters outside the Basic Multilingual Plane. This could be very useful for parsers.

### Proposed API (edited by @GrabYourPitchforks)

```cs
public class StringInfo
{
    // EXISTING overloads
    public static string GetNextTextElement(string str);
    public static string GetNextTextElement(string str, int index);

    // PROPOSED NEW overload, non-allocating
    public static ReadOnlySpan<char> GetFirstTextElement(ReadOnlySpan<char> str);
}
```

Proposed behavior: Returns the first text element (extended grapheme cluster) in _str_. The return value will always start at offset = 0 in _str_, and the length of the returned span is the length (in chars) of the cluster. If you want to call this in a loop, slice and party on. If the input is empty, returns the empty span.

**Comment by jzabroski** [comment]
I would like to see an allocation-free `StringInfo.ParseCombiningCharacters`.  I would also like to see improved documentation/visibility around this awesome API that has been around since .NET 1.0, but nobody seems to know about.

It would also probably be helpful if there was a "Unicode Waffle Text Generator" that could help people when testing Unicode characters.  It is so painful to test correctness of Unicode handling, even when using the helper APIs.

**Comment by GrabYourPitchforks** [comment]
I've modified the original post to include the API proposal.

**Comment by bartonjs** [comment]
* Returning the length instead of a span allows the method to be more versatile (ReadOnlySpan, Span, ReadOnlyMemory, Memory, etc)
* GetNextTextElementLength allows for better association in IntelliSense

```C#
namespace System.Globalization
{
    public partial class StringInfo
    {
        public static int GetNextTextElementLength(string str);
        public static int GetNextTextElementLength(string str, int index);
        public static int GetNextTextElementLength(ReadOnlySpan<char> str);
    }
}
```

**Comment by GrabYourPitchforks** [comment]
Updated title to reflect that we're adding APIs only to `StringInfo`, not to `CharUnicodeInfo`.
