### ISSUE TITLE
Consider moving System.IO.Pipelines into the shared framework

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#28760]
**Motivation:**
The recent in-box JSON serializer APIs (see https://github.com/dotnet/corefx/issues/34372 / https://github.com/dotnet/apireviews/tree/master/2019/System.Text.Json-Serialization) expect to take `PipeReader`/`PipeWriter`. This results in `System.Text.Json` depending on `System.IO.Pipelines`. However, the Pipelines package is not part of the shared framework and hence cannot be referenced by S.T.Json.

See discussion here:
https://github.com/dotnet/apireviews/pull/91#discussion_r256595035

**Can we move parts of `System.IO.Pipelines` (or all of it) in-box?**

If we consider Pipeline APIs "siblings" to streams, then they could be pushed down low enough within the stack for S.T.Json to take a dependency on it (but maybe not low enough to be pushed to corelib). Is that an appropriate view of pipelines? What are the risks/constraints with moving System.IO.Pipelines inbox?

**Possible alternatives to resolve the motivation differently:**
1) The JSON serializer instead accepts some other abstraction that is implemented within System.Memory (an assembly it already depends on).
    - For example, on the writer/serializer side, an extension of the `IBufferWriter` interface, `IAsyncBufferWriter` which `PipeWriter` would implement (TBD for the reader/deserializer side).
2) We invert the dependency where Pipelines depends on S.T.Json and PipeReader/Writer themselves provide serialize methods.
3) We only move parts of S.IO.Pipelines in-box (i.e. only what's required - PipeReader/PipeWriter) as part of a new assembly. Does that result in freezing the OOB package?
4) The JSON serializer doesn't provide direct `PipeReader`/`PipeWriter` support at all (less than ideal).

cc @davidfowl, @steveharter, @pakrym, @joshfree, @terrajobst, @jkotas, @stephentoub, @bartonjs, @ericstj, @KrzysztofCwalina

**Comment by davidfowl** [comment]
Anything preventing us from doing this in 6.0? It ended up getting punted in 5.0.0 because we backed out System.Net.Connections but it isn't related to that effort. Could we get this in for 6.x?

**Comment by stephentoub** [comment]
In general I want to avoid adding assemblies to netcoreapp unless there's an actual need to do so.  What drives that need here at this point?

**Comment by davidfowl** [comment]
It's already in the ASP.NET Core shared framework and it's generally useful outside of that. If the bar is that it has to be used by other code in Microsoft.NetCore.App (and I can find counter examples...), but I understand. We don't really have any hard and fast rules for this.
