### ISSUE TITLE
Add API IndexNotOf 

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#28795]
```csharp
public static partial class MemoryExtensions
{
    int IndexNotOf(this Span<T> span, T value) where T : IEquatable<T>;
    int IndexNotOfAny(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
    int IndexNotOfAny(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int IndexNotOfAny(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

    int IndexNotOf(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
    int IndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
    int IndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int IndexNotOfAny(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

    int LastIndexNotOf(this Span<T> span, T value) where T : IEquatable<T>;
    int LastIndexNotOfAny(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
    int LastIndexNotOfAny(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int LastIndexNotOfAny(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

    int LastIndexNotOf(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
    int LastIndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
    int LastIndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int LastIndexNotOfAny(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
}
```
Example usage:
```csharp
var firstNonSpace = span.IndexNotOf(' ');
if (firstNonSpace > 0)
{
    return span.Slice(firstNonSpace);
}

return span;
```

**Comment by danmosemsft** [comment]
Would we want all the variety of overloads we have for IndexOf, etc? That would give us 
```c#
public static int IndexNotOf<T>(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
public static int IndexNotOf<T>(this Span<T> span, T value) where T : IEquatable<T>;
public static int IndexNotOf<T>(this Span<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>;
public static int IndexNotOf<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>;
public static int IndexNotOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType);
public static int IndexNotOfAny<T>(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
public static int IndexNotOfAny<T>(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
public static int IndexNotOfAny<T>(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
public static int IndexNotOfAny<T>(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
public static int IndexNotOfAny<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
public static int IndexNotOfAny<T>(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
public static int LastIndexNotOf<T>(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
public static int LastIndexNotOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType);
public static int LastIndexNotOf<T>(this Span<T> span, T value) where T : IEquatable<T>;
public static int LastIndexNotOf<T>(this Span<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>;
public static int LastIndexNotOf<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>;
public static int LastIndexNotOfAny<T>(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
public static int LastIndexNotOfAny<T>(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
public static int LastIndexNotOfAny<T>(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
public static int LastIndexNotOfAny<T>(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
public static int LastIndexNotOfAny<T>(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
public static int LastIndexNotOfAny<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
```

**Comment by FiniteReality** [comment]
I'm implementing JsonPatch using System.Text.Json (the existing ASP.Net Core JsonPatch support is based on Newtonsoft) and this would be incredibly useful to parse array indexes as part of implementing JSON Pointer.

The JSON Pointer RFC defines a valid array index as:
```
   array-index = %x30 / ( %x31-39 *(%x30-39) )
                 ; "0", or digits without a leading "0"
```
So ideally, I'd love to use this as my validation for that:
```cs
var isValidArrayIndex =
    span.SequenceEqual(Zero) ||
    (span.IndexOfAny(OneThroughNine) == 0 &&
        span.IndexNotOfAny(Digits) == -1);
```

**Comment by danmosemsft** [comment]
Thanks for the info. Perhaps someone wants to share thoughts about whether it should be the full set of overloads or not. Then perhaps this is ready for API review.

**Comment by benaadams** [comment]
Don't think the `StringComparison` ones are needed unless someone asks specifically; ordinal should be fine as normally looking for a special delimiter (spaces, slashes, brackets, etc)
```
IndexNotOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType)
```

**Comment by danmosemsft** [comment]
Are there good scenarios for `LastIndexNotOfXXX` if we wouldn't use them for `TrimXXX` ? 

In the top proposal ther'es a mixture of `Span` and `ReadOnlySpan` maybe we could clean up which we need.

**Comment by benaadams** [comment]
`Span` and `ReadOnly` span are both needed as they are extension methods;  e.g. `string` only converts to `ReadOnlySpan` but array would convert to `Span`.

Don't have any strong feelings for `LastIndexNotOf...` dropped from summary

**Comment by benaadams** [comment]
`IndexNotOf<T>(this Span<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>` would be a bit strange as is a multichar delimiter

**Comment by benaadams** [comment]
Another example where it could be used
https://github.com/dotnet/runtime/blob/effaf28d0ca74ab9ae11fc947f524393e545af0d/src/libraries/System.Private.CoreLib/src/System/IO/PathInternal.Windows.cs#L406-L411
```csharp
return path.IndexNotOf(' ') < 0
```

**Comment by krwq** [comment]
@benaadams for single char/element scenario perhaps might be better to try to optimize Linq to do that fast (perhaps detect patterns similar to `path.Any(c => c == ' ')`).

**Comment by benaadams** [comment]
It's a not pattern so would be
```csharp
path.All(c => c == ' ')
```
However having Linq autovectorize from a `IEnumerable` and indirect `Func` would be a challenge?
```csharp
public static bool All<char>(this IEnumerable<char> source, Func<char, bool> predicate)
```
Could change the predicate to be `Expression<Func<T>>` and then parse it (which would be a big task in itself); however the `IEnumerable` doesn't imply contiguous data for vectorization.

`Span`/`ReadOnlySpan` are also `ref struct`s so can't convert to `IEnumerable`; so would need to add them explicitly; as which point its just changing namespace from `MemoryExtensions` where all the `Span`/`ReadOnlySpan` extensions currently are to `Linq`?

Some kind of Linq-style autovectorization for Span would be interesting via C# source generators where it converts the expressions to platform intrinsics e.g.
```csharp
public static bool All<TSource>(this ReadOnlySpan<TSource> source, Expression<Func<TSource, bool>> predicate)
    where TSource : unmanaged
```
but it's probably also a multi year research project?

**Comment by danmosemsft** [comment]
> Span and ReadOnly span are both needed as they are extension methods; e.g. string only converts to ReadOnlySpan but array would convert to Span.

Yeah, I was confused because you originally had ROS for LastIndexOfAny, and not IndexOfAny. 😄 

It looks good to me -- @GrabYourPitchforks ?

**Comment by GrabYourPitchforks** [comment]
Ben's original proposal (plus their _Last\*_ counterparts) looks ready to go forward to review. We shouldn't provide `StringComparison` overloads since we're not comparing a sequence of elements against a sequence of elements. Instead, we're looking at each element in the source sequence in isolation without regard to any adjacent elements in the source sequence. By definition this means we're not providing a linguistic text search.

Steve already provided reasons for not rewriting `string.Trim` atop these newly-introduced APIs. I agree with his reasoning. I would even go further and suggest that we _not_ vectorize the implementations of these newly-introduced methods, as I believe the use cases for these methods (much like the use cases for `Trim`) will terminate very early and won't benefit from vectorization.

**Comment by benaadams** [comment]
Added the Last ones back

**Comment by danmosemsft** [comment]
> suggest that we not vectorize the implementations of these newly-introduced methods,

@stephentoub when you mentioned taking advantage in Regex, were you hoping they'd be faster than the naive loop it currently does? Unfortunately the number of characters that the regex might scan could be anything from one to megabytes. For regex, a vectorized approach might be a better tradeoff across all patterns/texts.

**Comment by GrabYourPitchforks** [comment]
FWIW the implementation nit I mentioned above doesn't have to be resolved before API review. We can always create the appropriate implementation as we become aware of various scenarios.

The only real requirement from an SDL perspective is that given this:

```cs
int idx = source.IndexNotOfAny(values);
```

The runtime complexity of this method must be bound by `O(idx * values.Length)`. (Unless idx = -1, at which point the runtime complexity may be bound by `O(source.Length * values.Length)`. Vectorization vs. non-vectorization simply changes the constant factor, but it won't change the runtime complexity.

**Comment by stephentoub** [comment]
> when you mentioned taking advantage in Regex, were you hoping they'd be faster than the naive loop it currently does?

There are two benefits for regex:
1. Simpler code getting generated whenever the relevant pattern comes up, i.e. being able to emit a method call rather than open-coding it each time it occurs, with that method call performing at least as well as the open-coded loop would have
2. Having that method call perform better than the open-coded loop would have

Just the first is a reasonable place to start.  If that can be done, it's worth using in regex.  Then if the implementation can be made even faster, yay, regex just gets better implicitly.

I do agree with Levi, though; I think it's likely that even in the regex scenarios we'd find in common cases the loops to have very short iteration counts.  But it'd be worth looking at what the opportunities are for using the method and then looking at common patterns and inputs to see what we think the win would actually be.

**Comment by benaadams** [comment]
Implementation details... ;)

Sounds like is ready to mark for review?

**Comment by GrabYourPitchforks** [comment]
> Sounds like is ready to mark for review?

Marked. :)

**Comment by terrajobst** [comment]
* These APIs seem fairly specialized; it feels this might open up a large amount of potential new APIs due to combinations
* These seem to live in user code
* So unless there is more evidence that suggests this API is useful

```C#
namespace System
{
    public static partial class MemoryExtensions
    {
        int IndexNotOf(this Span<T> span, T value) where T : IEquatable<T>;
        int IndexNotOfAny(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
        int IndexNotOfAny(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
        int IndexNotOfAny(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

        int IndexNotOf(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
        int IndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
        int IndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
        int IndexNotOfAny(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

        int LastIndexNotOf(this Span<T> span, T value) where T : IEquatable<T>;
        int LastIndexNotOfAny(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
        int LastIndexNotOfAny(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
        int LastIndexNotOfAny(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

        int LastIndexNotOf(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
        int LastIndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
        int LastIndexNotOfAny(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
        int LastIndexNotOfAny(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
    }
}
```

**Comment by stephentoub** [comment]
> These APIs seem fairly specialized; it feels this might open up a large amount of potential new APIs due to combinations

I think we should reconsider this one.  There are a variety of places it's useful, e.g.
- In bit maps, determining whether the set is empty (`IndexNotOf(0) < 0`) or full (`IndexNotOf(0xFF) < 0`), or finding the first element that has a bit set in order to start processing from there (`int pos = IndexNotOf(0)`), etc.
- In text searching, looking for the first non-space (`IndexNotOf(' ')`), as in an expression like "\w+ *\w+" to find two words with any number of spaces in between.

**Comment by EgorBo** [comment]
Use-case: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/IO/PathInternal.Windows.cs#L379-L390

could be just `IndexNotOf(' ') == -1`

**Comment by stephentoub** [comment]
I just had another case, where I wanted to determine whether some memory was all zero'd.  We don't have a great helper for that built-in today, but `IndexNotOf(0)` would do it.

**Comment by adamsitnik** [comment]
In the original proposal, there was 16 methods being proposed. @stephentoub from what you have wrote it seems that a single one would be enough for our current needs. Is that correct? If so, would you like to update the proposal and present it in the API review?

**Comment by terrajobst** [comment]
* We'd prefer a less-Yoda like name such as `IndexOfAnyExcept` which would also allow us to fold the single case into the multiple case.

```C#
namespace System;

public static partial class MemoryExtensions
{
    int IndexOfAnyExcept(this Span<T> span, T value) where T : IEquatable<T>;
    int IndexOfAnyExcept(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
    int IndexOfAnyExcept(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int IndexOfAnyExcept(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

    int IndexOfAnyExcept(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
    int IndexOfAnyExcept(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
    int IndexOfAnyExcept(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int IndexOfAnyExcept(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

    int LastIndexOfAnyExcept(this Span<T> span, T value) where T : IEquatable<T>;
    int LastIndexOfAnyExcept(this Span<T> span, T value0, T value1) where T : IEquatable<T>;
    int LastIndexOfAnyExcept(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int LastIndexOfAnyExcept(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;

    int LastIndexOfAnyExcept(this ReadOnlySpan<T> span, T value) where T : IEquatable<T>;
    int LastIndexOfAnyExcept(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T>;
    int LastIndexOfAnyExcept(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T>;
    int LastIndexOfAnyExcept(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T>;
}
```
