### ISSUE TITLE
On Windows ARM64, serial ports are not found by SerialPort class

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#28851]
This means that in Windows IoT, ports were not found under HKLM\HARDWARE\DEVICEMAP\SERIALCOMM (by product) that were found under QueryDosDevice (by test)

This was discussed here https://github.com/dotnet/corefx/issues/18023 and apparently it hides real ports. 
```
COM3 is not present in SerialPort.GetPortNames result
PortHelper Ports: COM3,COM5
SerialPort Ports: 

Expected: True
Actual:   False
Stack Trace :
   at System.IO.Ports.Tests.GetPortNames.AllHelperPortsAreInGetPortNames() in F:\vsagent\5\s\src\System.IO.Ports\tests\SerialPort\GetPortNames.cs:line 49
```
https://mc.dot.net/#/user/dotnet-mc-bot-2/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Farm64/test~2Ffunctional~2Fcli~2F/20190302.5/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.GetPortNames~2FAllHelperPortsAreInGetPortNames

**Comment by carlossanlop** [comment]
Triage:
@PRIMETSS will you have a chance to continue looking into this? You shared your commit:  https://github.com/PRIMETSS/corefx/commit/f7368d696304c9a7abd3cbb45dad85857f693a01

**Comment by PRIMETSS** [comment]
Thanks Carlos,

I think this can be closed.

Since the code base move, lots have happened and Ive not had time to get up to speed with this move yet. I’d probably rather plan to revisit it and submit a new Issue/PR after checking if the problem still exits and re-submit more succinctly.

Paul

**Comment by danmosemsft** [comment]
OK thanks!
