### ISSUE TITLE
Support for ISO8601 durations in TimeSpan

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/runtime#28862]
# Rationale
As far as I know, there is currently no support for ISO8601 durations for `TimeSpan.Parse` and `TimeSpan.ToString`.

Per [wikipedia's definition](https://en.wikipedia.org/wiki/ISO_8601#Durations) , it would allow to write durations like `P10M1D` for a duration of ten month and one day, `P1DT2H10M` for 1 day, 2 hours and 10 minutes, or `PT0,5M` for 30 seconds.

# Proposition

- Make `TimeSpan.Parse()` accept arguments like the values quoted above
- Create a new `ToString()` format specifier to output values like `P1DT2H` or, if it is not possible for compatibility reasons, add a new `.ToISOString()` method.

# Use cases

- Interoperability with other language and tools by using a standard for representing durations.
   - [PHP's DateInterval](http://php.net/manual/fr/dateinterval.construct.php)
   - [Java's Duration.parse](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-)
   - [moment.js](https://momentjs.com/docs/#/durations/creating/)
- Allows to fix a [JSON deserialization issue](https://github.com/JamesNK/Newtonsoft.Json/issues/863) in the popular's JSON.net library
- Avoids a reference to `XmlConvert.ToString()` to convert this, as suggested [here](https://stackoverflow.com/questions/12466188/how-do-i-convert-an-iso8601-timespan-to-a-c-sharp-timespan)

**Comment by lomholdt** [comment]
Is there any timeline on this suggestion, or is it currently only a thing on the backlog?
Also, does anyone have a recommended/good way to handle this until support has been added natively?
I have searched but only found some relatively unused libs.

**Comment by eiriktsarpalis** [comment]
Related to #29932. In the context of System.Text.Json we have decided that ISO8601 durations (which represent duration relative to a point in time) are somewhat incompatible with `TimeSpan` (which represents an absolute timespan counted in ticks).

**Comment by tthiery** [comment]
Also interested. I understand that it conflicts with TimeSpan but there are tons of use cases to express duratoins in something else than days (and hours/minutes). Especially since DateTime itself has suitable AddMonths which are adhering the difference between "P1M" and "P30D" (checked at least for months).

Would not be there a case for a Iso8601TimeSpan?

.NET 8 maybe? 😉 I know it is painful since TimeSpan is so ... fundamental ... but so ISO8601 compliance ;) 

FYI: @terrajobst

**Comment by eiriktsarpalis** [comment]
> Would not be there a case for a Iso8601TimeSpan?

I would recommend filing a separate API proposal for a potential `System.Duration` type. In the meantime, I'm going to close this issue as we made the definitive decision back in .NET 6 to not support the ISO 8601 duration format for `System.TimeSpan`.
