### ISSUE TITLE
Problem with Assembly.LoadFile and Activator.CreateInstance in .net core 2.2

### ISSUE THREAD

**Issue by joshfree** [dotnet/runtime#28870]
_From @tamasVajda on March 1, 2019 13:47_

Problem with Assembly.LoadFile and Activator.CreateInstance

.net core version: 2.2 
dll to load: .net framework 2.0

We tried to implement a kind of dependency injection in .net standard what could use out client from .net framework side and our server from .net core 2.0.

The location of class described in json configuration file, like following:

```json
"Namspace1.SomeData": {
      "class": "Namespace2.ClassName",
      "Assembly": "MyAssambly.dll"
    }
```

our Factory class implemented in .net standard what can provide an instance from a required object:

```c#
               Assembly assembly = Assembly.LoadFile("assemplyPath/MyAssambly.dll");

                Type objtype = assembly.GetType("Namespace2.ClassName");
                var objectInstance = Activator.CreateInstance(objtype);
                return objectInstance as IMyClassInterface;
```

Of coarse ClassName class implement IMyClassInterface interface.

The factory class works well, if called from .net framework side, create an instance from the loaded dll and can cast it to interface type.

BUT can not work if it's called this factory method from .net core project: the assembly load success, there is all types according to configuration, but the cast fail, this function return null (or invalid cast if i try other way to cast it)!  It seems to not working a reflection in .net core properly, if the types are defined in .net standard dll? Why lost all instantiated classes his interfaces? 

We tried some comvisibility attributes, without any result.

Have you any idea how could we solve this issue?

_Copied from original issue: dotnet/core#2352_

**Comment by steveharter** [comment]
This doesn't appear to be a supported scenario since there are two contexts.

**Comment by GrabYourPitchforks** [comment]
@tamasVajda As others have mentioned, using `Assembly.LoadFile` loads the assembly into a different context, separate from the default context that other assemblies are loaded into. Your earlier example of using `assembly.CreateInstance(...)` instead of the static factory method `Type.GetType(...)` or `Activator.CreateInstance` is the best way of creating instances of types from such assemblies. `Type.GetType` and `Activator.CreateInstance` will not correctly see types from such asseblies.
