### ISSUE TITLE
Introduce abstractions for buffer managed reading and writing

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#28884]
The goal here is to introduce a minimal abstraction into the stack that supports asynchronous buffered reading and asynchronous buffered writing. **System.IO.Pipelines** would implement these interfaces and various places in the stack that wanted to support buffered reading and writing would take these as arguments. Exposing them as interfaces also means that we can potentially implement these on specific Streams that implemented buffering behavior.

```C#
namespace System.IO
{
    public interface IAsyncBufferedReader<T>
    {
        ValueTask<ReadResult<T>> ReadAsync(CancellationToken cancellationToken = default);
        void AdvanceTo(SequencePosition consumed, SequencePosition examined);
    }

    public interface IAsyncBufferedWriter<T> : IBufferWriter<T>
    {
        ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default);
        ValueTask FlushAsync(CancellationToken cancellationToken = default);
    }

    public readonly struct ReadResult<T>
    {
        public ReadResult(in ReadOnlySequence<T> buffer, bool isCompleted)
        {
            Buffer = buffer;
            IsCompleted = isCompleted;
        }

        public ReadOnlySequence<T> Buffer { get; }
        public bool IsCompleted { get; }
    }
}
```

Here's an example of what the `JsonSerializer.ReadAsync<T>` would look like with this overload:

```C#
private static async ValueTask<TValue> ReadAsync<TValue>(IAsyncBufferedReader<byte> utf8Json, Type returnType, JsonSerializerOptions options = null, CancellationToken cancellationToken = default)
{
    if (options == null)
        options = s_defaultSettings;

    ReadObjectState current = default;
    JsonClassInfo classInfo = options.GetOrAddClass(returnType);
    current.ClassInfo = classInfo;
    if (classInfo.ClassType != ClassType.Object)
    {
        current.PropertyInfo = classInfo.GetPolicyProperty();
    }

    var readerState = new JsonReaderState(options: options.ReaderOptions);
    List<ReadObjectState> previous = null;
    int arrayIndex = 0;

    ReadResult<byte> result;
    do
    {
        result= await utf8Json.ReadAsync(cancellationToken).ConfigureAwait(false);
        buffer = result.Buffer;

        ReadCore(
            ref readerState,
            returnType,
            result.IsCompleted,
            buffer,
            options,
            ref current,
            ref previous,
            ref arrayIndex);

        utf8Json.AdvanceTo(readerState.Position, buffer.End);

    } while (!result.IsCompleted);

    return (TValue)current.ReturnValue;
}
```

Notes:
- The semantics of ReadAsync match those of Stream, an empty `ReadOnlySequence` means end of data and cancellation throws an operation cancelled exception
- AdvanceTo takes 2 arguments, consumed (how much excluded from the next ReadAsync call, and examined, determines how much of the buffer was observed by the caller).
- ~To avoid the `ReadResult` concept that exists in pipelines, if there's data remaining in the buffer and we've advanced to the end, it would throw. Alternatively, we could introduce a similar ReadResult concept (but it might clash with the one in pipelines)~. I prefer the `ReadResult<T>` approach, it looks a bit cleaner.

cc @stephentoub @terrajobst @ahsonkhan @jkotas @pakrym @jkotalik @KrzysztofCwalina

**Comment by oliverjanik** [comment]
I believe we .NET needs a more lightweight Stream alternatives akin to Golangs Reader/Writer. The proposed interfaces look like they fit the purpose nicely 👍 

Without these, all the work that has been done on Spans, Memory and others feels a bit incomplete. I find myself reverting back to byte[] or Streams in a lot of situations.

**Comment by jkotas** [comment]
Similar to https://github.com/dotnet/runtime/issues/66611
