### ISSUE TITLE
Assembly.CreateInstance returning null instead of throwing an ArgumentException

### ISSUE THREAD

**Issue by non-conformances-research** [dotnet/runtime#28898]
According to the specification, Assembly.CreateInstance method should throw an ArgumentException to the above program.

```
using System;
using System.Reflection;

public class A {
  public static void Main() {
    Assembly assem = typeof(A).Assembly;
    A a = (A)assem.CreateInstance(" ");
    if (a == null) {
      Console.WriteLine("Null");
    } else {
      Console.WriteLine(a);
    }
  }
}
```

## Steps to Reproduce

1. Compile above program.
2. Run it.

### Current Behavior

Null

### Expected Behavior

ArgumentException thrown.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

.NET Core SDK 2.1.401

**Comment by steveharter** [comment]
This doesn't appear to be a valid\real user scenario, so priority is very low. Closing
