### ISSUE TITLE
decimal forgotten by Span<T> APIs

### ISSUE THREAD

**Issue by gbieging** [dotnet/runtime#28904]
_Edit by @GrabYourPitchforks on 29 Jan 20: API proposal is in a comment at https://github.com/dotnet/corefx/issues/35877#issuecomment-471004904_

I was recently toying  with making a serialization library and found out that there are no `Span<T>` APIs for serializing and deserializing decimals.

I searched for the issues related to the `Span<T>` APIs and found dotnet/runtime#18969 and dotnet/runtime#18970 for decimal, but when they where closed for tracking in dotnet/runtime#19444 decimal was forgotten.

I know 3.0 is near but it would be nice to have it in 2.x too.

**Comment by terrajobst** [comment]
* `TryGetBits` should follow the span pattern
* Given the size is known, we should also have a throwing `GetBits()`

```C#
namespace System
{
    public readonly partial struct Decimal
    {
        public Decimal(ReadOnlySpan<int> bits);
        public static bool TryGetBits(decimal d, Span<int> destination, out int valuesWritten);
        public static int GetBits(decimal d, Span<int> destination);
    }
}
```

**Comment by ArjunVachhani** [comment]
@stephentoub how to use new Span<T> APIs  with Net Standard 2.1 library? will it work with only .net 5?

**Comment by stephentoub** [comment]
They're new in .NET 5, and thus aren't available via .NET Standard 2.1.
