### ISSUE TITLE
System.Console unexpectedly uses a UTF-8 encoding *with BOM* on Windows

### ISSUE THREAD

**Issue by mklement0** [dotnet/runtime#28929]
Note: dotnet/runtime#27258 (since fixed) addressed the same issue, but for Unix-like platforms only, because at the time I didn't realize that it should be fixed on Windows also.

**On Windows too the preamble (BOM) should be removed from the UTF-8 encoding that the `Console` class uses when code page `65001` (`chcp 65001`) is in effect**, given that `cmd.exe` - rightfully - has always operated _without BOM_ in that case:

After all, **any programs relying on the _active code page_ should be able to _blindly_ assume that stdin input / stdout output  is encoded accordingly and _shouldn't have to deal with a BOM_** (neither to redundantly imply the same code page nor to potentially signal a different encoding).

The presence of a BOM, in fact, breaks PowerShell's background-jobs feature (via `Start-Job`), as detailed here:

* https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/14915283-job-cmdlets-fail-with-utf-8-codepage

Follow-on bugs:

* https://github.com/Microsoft/azure-pipelines-tasks/issues/9766
* https://github.com/ansible/ansible/issues/15770

It's fair to assume that other applications/languages/frameworks may be affected as well, which can range from outright failure, as in PowerShell's case, to mistakenly considering the BOM part of the data.

---

Demonstration of `cmd`'s current behavior:

`cmd`'s stdout output has always created _BOM-less_ output with `chcp 65001` in effect; e.g. the following creates `t.txt` as a _BOM-less_ UTF-8 file.

```powershell
C:\> chcp 65001
C:\> (echo hü)> t.txt
C:\> powershell -noprofile -c Format-Hex t.txt

           Path: C:\Users\jdoe\t.txt

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   68 C3 BC 0D 0A                                   hÃ¼..

```

The above shows that the file contains _no_ BOM (and that [char. `ü`](http://www.fileformat.info/info/unicode/char/fc/index.htm) was correctly encoded as UTF-8 as 2-byte sequence `0xC3 0xBC`).

**Comment by carlossanlop** [comment]
@mklement0 would you like to work on this issue?

**Comment by mklement0** [comment]
Thanks for asking, @carlossanlop, but I'm hoping someone else can take this on.

**Comment by eiriktsarpalis** [comment]
As far as `Console.Out` is concerned, it would seem like [the current implementation is stripping the preamble](https://github.com/dotnet/runtime/blob/b41f1c5f2fde25d752d857a54c3af24145060cdd/src/libraries/System.Console/src/System/Console.cs#L220) for Windows as well. I tested the following console app:

```csharp
    class Program
    {
        static void Main()
        {
            Console.Write(Console.OutputEncoding.CodePage);
        }
    }
```
Using the latest .NET 5.0 preview sdk:
```
chcp 65001
dotnet run > foo.txt
powershell -noprofile -c Format-Hex foo.txt
```
Produces no BOM artifacts:
```
           Path: C:\Users\eitsarpa\source\repos\ConsoleApp14\ConsoleApp14\foo.txt

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   36 35 30 30 31                                   65001
```

It should be noted however that `System.Console.OutputEncoding` does not strip the preamble, so applying it to the raw stdout stream should not have the same effect.

Perhaps I'm misunderstanding what is broken here?

**Comment by mklement0** [comment]
My bad, @eiriktsarpalis - I missed that the referenced PR _did_ fix the problem on Windows too:

https://github.com/dotnet/runtime/blob/d8ca3562358b036afc14c6f1abc517154c98b095/src/libraries/System.Console/src/System/Console.cs#L220

Sorry for the noise - I'm closing this.

---

P.S.: It's a moot point now, but the example you gave is the one that showed that _in `cmd.exe`_ it always worked as expected.

The true test would be to use a PowerShell Core 7.1.0-preview.5 console (`pwsh.exe`), which is based on a fairly recent 5.0 preview, from a `cmd.exe` window in which `chcp 65001` was run first:

```cmd
C:\>chcp 65001 && pwsh.exe -c "[Console]::OutputEncoding.WebName; ([Console]::OutputEncoding).Preamble.Length"
utf-8
0
```

The `0` confirms that no preamble is indeed used.
