### ISSUE TITLE
Recommended asynchronous usage pattern of SerialPort

### ISSUE THREAD

**Issue by LeonidVasilyev** [dotnet/runtime#28968]
The question is about common command scenario when you send a command to a device and want to check a response to see the result or simply to check that the command is acknowledged. What is the recommended way to organize that in a non blocking fashion in general and in an UI application? 

Currently I see three options. First is `SerialPort.BaseStream.*Async` methods. `SerialPort.BaseStream.ReadAsync()` uses `Stream.ReadAsync()` implementation and ignores `SerialPort.BaseStream.ReadTimeout` and most of the time ignores `CancellationToken` instance. If you use `Task.Delay()` alongside `Task.WhenAny()` with `SerialPort.BaseStream.ReadAsync()` there is read task and byte buffer left to hang forever. So it doesn't seem like a good option. 

Another options is to use `SerialPort.DataRecieved` event. But in this case you basically probaby need to organize state machine so the event handler behaves differently depending on which command is currently in process.

The third option is to use synchronous methods and offload the work  to a Thread pool thread which seems the best of three:
```cs
static async Task OnClick(object sender, EventArgs args, CancellationToken cancellationToken)
{
    var jobTask = Task.Run(() => {
        // Organize critical sections around logical serial port operations somehow.
        lock (_syncRoot) 
        {
            return SomeCommand();
        }
    });
    if (jobTask != await Task.WhenAny(jobTask, Task.Delay(Timeout.Infinite, cancellationToken)))
    {
        // Timeout;
        return;
    }
    var response = await jobTask;
    // Process response.
}

static byte[] SomeCommand()
{
    // Assume serial port timeouts are set.
    _serialPort.Write(...);

    int offset = 0;
    int count = ...; // Expected response length.
    byte[] buffer = new byte[count];
    while (count > 0)
    {
        var readCount = _serialPort.Read(buffer, offset, count);       
        offset += readCount;
        count -= readCount;
    }
    return buffer;
}
```

**Comment by carlossanlop** [comment]
It seems the questions have been responded. @mikkleini @LeonidVasilyev feel free to reopen if you have any additional questions.
