### ISSUE TITLE
Expose GetPipePath on System.IO.Pipes.PipeStream

### ISSUE THREAD

**Issue by casperOne** [dotnet/runtime#28979]
Add a new `System.IO.Pipes.PipeStream.PipePath` public property (read only) so developers can see what is the valid platform-specific normalized path of their pipe instance.

Make the `System.IO.Pipes.PipeStream.GetPipePath` static method public so developers can create valid pipe paths for a specific server name and pipe name combination.

##### PipePath

Developers currently don't have a public API to check what is the path that represents their pipe instance in the current platform.

If we add this property, with only a get property accessor, they can consult the pipe name and can pass it across processes and across platforms.

The property could be accessed like this:

```cs

NamedPipeServerStream server = new NamedPipeServerStream(pipeName: "MyPipeName");
string serverPath = server.PipePath;

NamedPipeClientStream client = new NamedPipeClientStream(serverName: ".", pipeName: "MyPipeName");
string clientPath = client.PipePath;

// The value for both serverPath and clientPath would be:
// Windows  =   \\.\pipe\MyPipeName
// Unix     =   /tmp/CoreFxPipe_MyPipeName
```

##### GetPipePath

The existing `GetPipePath` static method is used internally to generate a valid platform-specific normalized pipe path using the passed server name and pipe name.

Developers currently don't have a public API to determine if a server name + pipe name combination can form a valid pipe path for the current platform. The only available workaround is to copy the `GetPipePath` code, which is not ideal: if our code changes, their code will be outdated.

If we expose this method, we can call it like this:

```cs
string path = PipeStream.GetPipePath(serverName: ".", pipeName: "MyPipeName");
// The value of path would be:
// Windows  =   \\.\pipe\MyPipeName
// Unix     =   /tmp/CoreFxPipe_MyPipeName
```

## Proposed API

The internal method already exists, we only need to make it public:
```cs
namespace System.IO.Pipes
{
    ...
    public abstract partial class PipeStream : Stream
    {
        ...
        public virtual string PipePath { get; }
        public static string GetPipePath(string serverName, string pipeName);
    }
    ...
}
```

Classes that inherit from PipeStream can optionally override `PipePath`.
The `NamedPipe*Stream` classes should override it, while the `AnonymousPipe*Stream` classes may not (pending open question):

```cs
    public sealed partial class NamedPipeClientStream : PipeStream
    {
        ...
        public override string PipePath { get { ... } }
        ...
    }

    public sealed partial class NamedPipeServerStream : PipeStream
    {
        ...
        public override string PipePath { get { ... } }
        ...
    }

    public sealed partial class AnonymousPipeClientStream : PipeStream
    {
        ...
        public override string PipePath { get { ... } }
        ...
    }

    public sealed partial class AnonymousPipeServerStream : PipeStream
    {
        ...
        public override string PipePath { get { ... } }
        ...
    }
```

## Details

- The `GetPipePath` method is static and currently none of the classes that inherit from `PipeStream` is overriding this method.

- We should add unit tests that perform the following checks on the `GetPipePath` method:

  - Windows:
    - The returned string has been normalized to the format: `\\<serverName>\pipe\<pipeName>`
    - Throws `ArgumentOutOfRangeException` if the returned pipe path is equal to the anonymous pipe name, which is reserved.
    - Throws the `Path.GetFullPath` [exceptions](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netcore-3.0) if their conditions are met with the passed normalized formatted sting.
  - Unix:
    - If the pipe name is rooted, the pipe name string itself is returned.
    - If the pipe name is not rooted, the pipe prefix + the pipe name string is returned.
    - Throws `PlatformNotSupportedException` if:
      - The server name is anything else besides `.` or the current machine's hostname.
      - The pipe name contains invalid path name characters.
      - The pipe name ends in a directory separator character when the pipe name is rooted.
    - Throws `ArgumentOutOfRangeException` if the returned pipe path is equal to the anonymous pipe name, which is reserved by Windows.

- We should decide if the `PipePath` property getter should return the default value (either `string.Empty` or `null`) or if it should throw.

## Open Questions

- What should the `AnonymousPipe*Stream.PipePath` property getter return? Should it return the `\\.\pipe\anonymous` string in Windows (and whatever the equivalent constant string in Unix)? Should it return `null` or should it return `string.Empty`?
- What should the default value of `PipeStream.PipePath` be, in case a child class does not override it?
- If the Windows anonymous pipe is expected to be `\\.\pipe\anonymous`, then what is the Unix equivalent? Is it `\\tmp\CoreFxPipe_anonymous`?
- Should we use the name `PipePath` or should we use another name to keep it consistent with similar APIs that expose a path? Update: could we use `LocalPath`, as it it already being used by `Uri`?

## Pull Request

Pending approval of this API proposal.

## Updates

- Edited the description to the official API Proposal format, copied the original description into a comment for historical purposes.
- Answered question of virtual vs abstract: Making the property `abstract` would break classes inheriting from `PipeStream`.

**Comment by stephentoub** [comment]
Several unanswered questions and no response in a few years.  Closing.  We can reopen if there's further demand.
