### ISSUE TITLE
System.Drawing.Printing.PrintingServices.LoadPrinterSettings NullReferenceException

### ISSUE THREAD

**Issue by ATrzeciakiewicz** [dotnet/runtime#28995]
I have a problem with PrintDocument from System.Drawing.Common when I use this on Linux, to be more specific, the problem comes from PrintingServices.LoadPrinterSettings, which is using in PrinterSettings.Unix

here the content of the error:

```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object. at System.Drawing.Printing.PrintingServices.LoadPrinterSettings(String printer, PrinterSettings settings)

```
On Windows everything working correctly.

**Comment by huoyaoyuan** [comment]
Unix support for System.Drawing.Common has been removed.
