### ISSUE TITLE
XslTransformException: Methods with same name and same number of parameters not allowed.

### ISSUE THREAD

**Issue by mstaal** [dotnet/runtime#29053]
I tried to invoke a method in an XSLT Extension Object names IsDateTime, and since there are two method declarations with the same name and number of parameters I got this Exception:

> XslTransformException: Ambiguous method call. Extension object 'ext:xslt' contains multiple 'IsDateTime' methods that have 1 parameter(s)

Why is that I cannot have multiple methods with different signatures? One of the methods takes a string as a parameter, the second takes an XPathNodeIterator.

**Comment by mstaal** [comment]
I still want for this to be fixed!

**Comment by krwq** [comment]
@mstaal, can you please share a minimal repro?
