### ISSUE TITLE
Opening and closing brackets must be escaped when used inside a character class "[\\[\\]]", but not when used outside character class. Regex.Escape doesn't escape "]".

### ISSUE THREAD

**Issue by tagcode** [dotnet/runtime#29068]
Regex.Escape("[]") produces "\\\\[]". "]" isn't escaped. When used in a pattern as is, it works as expected.
```C#
            {
                // Works.
                Regex pattern = new Regex(Regex.Escape("[]"));
                Match match = pattern.Match("[]");
                bool ok = match.Success; // Match
            }
            {
                // Works.
                Regex pattern = new Regex("\\[\\]");
                Match match = pattern.Match("[]");
                bool ok = match.Success; // Match
            }
```

However, when used inside a character class, it doesn't work as expected.
```C#
            {
                // Doesn't work. "[\\[]]" doesn't match either "[" or "]"
                Regex pattern = new Regex("["+Regex.Escape("[]")+"]");
                var matches = pattern.Matches("aa]aa");
                bool assertOk = matches.Count == 1; // no matches
            }
            {
                // Works with pattern "[\\[\\]]"
                Regex pattern = new Regex("[\\[\\]]");
                var matches = pattern.Matches("aa]aa");
                bool assertOk = matches.Count == 1; // matched
            }
```

Character class is closed by first "]". The obvious fix is to escape the "]" as "\\\\]".

**Comment by ygra** [comment]
Behaves as documented, though:

> Escapes a minimal set of characters (\, *, +, ?, |, {, [, (,), ^, $, ., #, and white space) by replacing them with their escape codes.

And the docs even include the following warning:

> While the Escape method escapes the straight opening bracket ([) and opening brace ({) characters, it does not escape their corresponding closing characters (] and }). In most cases, escaping these is not necessary. If a closing bracket or brace is not preceded by its corresponding opening character, the regular expression engine interprets it literally. If an opening bracket or brace is interpreted as a metacharacter, the regular expression engine interprets the first corresponding closing character as a metacharacter. If this is not the desired behavior, the closing bracket or brace should be escaped by explicitly prepending the backslash (\) character.

That being said, is there that much of a benefit of escaping a _minimal_ set of characters? Even if escaping were very naïve, the string would only double in length (and even with this change it wouldn't be that naïve).

**Comment by tagcode** [comment]
> Is there that much of a benefit of escaping a _minimal_ set of characters?
Well I was looking for the minuscule benefit of being able to _rely_ on Regex.Escape() to do just that in context of character class as well. 


>If this is not the desired behavior, the closing bracket or brace should be escaped by explicitly prepending the backslash () character.
I must have missed that. So the case was considered and purposefully excluded by the designer of the method.
