### ISSUE TITLE
System.Drawing.Common runs on Linux with BUGS

### ISSUE THREAD

**Issue by iexapl** [dotnet/runtime#29075]
Hello!
System.Drawing.Graphics.DrawString function, under the Linux system,
Problem:
1, the Chinese with some text processing problems (such as "张"), as long as the text appears such text, it and the text behind it will not be drawn on the picture;
2, in addition in the specified rectangular range can not be wrapped, at present I am a word a word drawn, when reaching the rectangular width will switch to the next line to start drawing, in this way after processing, the problem 1 has also been resolved; 
3, the use of System.Drawing.Drawing2D.GraphicsPath，System.Drawing.Graphics.FillPath to deal with rounded corners, the results of the fillet will appear gray circular lines.

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
