### ISSUE TITLE
GetTypes(string className) and GetTypes(string className,Type baseType)

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#29076]
I wish we could have these method for `Type` and `Assembly` class

```C#
class Type
{
    public static Type[] GetTypes(string className);
    public static Type[] GetTypes(string className,Type baseType);
    public static Type[] GetTypes(string className,params Type[] baseOrInterfaceType);
}

class Assembly
{
    public Type[] GetTypes(string className);
    public Type[] GetTypes(string className,Type baseType);
    public Type[] GetTypes(string className,params Type[] baseOrInterfaceType);
}
```

So it would be easier to query for a type with just class name and base type, which I think it is very common use cases

**Comment by GrabYourPitchforks** [comment]
The issue as currently described is too vague / not actionable by us at this time. I'm closing the issue for now. But if it's blocking a scenario please let us know so that it can be reopened. Thanks!
