### ISSUE TITLE
ImmutableHashSet.Contains is few times slower that HashSet.Contains

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#29085]
How to run the benchmarks:

```cmd
git clone https://github.com/dotnet/performance.git
# if you have .NET Core 3.0 installed
dotnet run -c Release -f netcoreapp3.0 -p .\performance\src\benchmarks\micro\MicroBenchmarks.csproj --filter *Contains*HashSet --join
# if you don't have .NET Core 3.0 installed
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --filter *Contains*HashSet --bdn-arguments="--join true"
```

|                  Type |           Method | Size |      Mean |
|---------------------- |----------------- |----- |----------:|
|  ContainsFalse&lt;Int32&gt; |          HashSet |  512 |  6.267 us |
| ContainsFalse&lt;String&gt; |          HashSet |  512 | 18.695 us |
|   ContainsTrue&lt;Int32&gt; |          HashSet |  512 |  6.843 us |
|  ContainsTrue&lt;String&gt; |          HashSet |  512 | 22.733 us |
|  ContainsFalse&lt;Int32&gt; | ImmutableHashSet |  512 | 26.277 us |
| ContainsFalse&lt;String&gt; | ImmutableHashSet |  512 | 48.434 us |
|   ContainsTrue&lt;Int32&gt; | ImmutableHashSet |  512 | 26.218 us |
|  ContainsTrue&lt;String&gt; | ImmutableHashSet |  512 | 50.863 us |

Full docs for the new benchmarking workflow: https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md

**Comment by robertDurst** [comment]
I just ran

```
dotnet run -c Release -p .\performance\src\benchmarks\micro\MicroBenchmarks.csproj --filter *Contains*HashSet --join
```

with `netcoreapp3.1` and `net5.0` and got pretty similar numbers.

Is this still up for grabs?

**Comment by adamsitnik** [comment]
> got pretty similar numbers.

@robertDurst what number are you getting?

For me it's:

|                         Type |           Method | Size |  3.1 Mean |  5.0 Mean |
|----------------------------- |----------------- |----- |----------:|----------:|
|  ContainsTrueComparer&lt;Int32&gt; |          HashSet |  512 |  6.709 us |  6.035 us |
| ContainsTrueComparer&lt;String&gt; |          HashSet |  512 | 29.449 us | 25.784 us |
|  ContainsTrueComparer&lt;Int32&gt; | ImmutableHashSet |  512 | 26.942 us | 26.075 us |
| ContainsTrueComparer&lt;String&gt; | ImmutableHashSet |  512 | 54.356 us | 53.694 us |
|         ContainsFalse&lt;Int32&gt; |          HashSet |  512 |  5.076 us |  2.887 us |
|        ContainsFalse&lt;String&gt; |          HashSet |  512 | 19.125 us |  8.904 us |
|          ContainsTrue&lt;Int32&gt; |          HashSet |  512 |  6.719 us |  3.475 us |
|         ContainsTrue&lt;String&gt; |          HashSet |  512 | 21.438 us | 10.982 us |
|         ContainsFalse&lt;Int32&gt; | ImmutableHashSet |  512 | 25.046 us | 24.749 us |
|        ContainsFalse&lt;String&gt; | ImmutableHashSet |  512 | 43.490 us | 33.484 us |
|          ContainsTrue&lt;Int32&gt; | ImmutableHashSet |  512 | 26.984 us | 26.511 us |
|         ContainsTrue&lt;String&gt; | ImmutableHashSet |  512 | 47.016 us | 39.144 us |

And when I reorder the rows to make  it easier to see the difference between the `HashSet` and `ImmutableHashSet`:

|                         Type |           Method | Size |  3.1 Mean |  5.0 Mean |
|----------------------------- |----------------- |----- |----------:|----------:|
|  ContainsTrueComparer&lt;Int32&gt; |          HashSet |  512 |  6.709 us |  6.035 us |
|  ContainsTrueComparer&lt;Int32&gt; | ImmutableHashSet |  512 | 26.942 us | 26.075 us |
|                              |                  |      |           |           |
| ContainsTrueComparer&lt;String&gt; |          HashSet |  512 | 29.449 us | 25.784 us |
| ContainsTrueComparer&lt;String&gt; | ImmutableHashSet |  512 | 54.356 us | 53.694 us |
|                              |                  |      |           |           |
|         ContainsFalse&lt;Int32&gt; |          HashSet |  512 |  5.076 us |  2.887 us |
|         ContainsFalse&lt;Int32&gt; | ImmutableHashSet |  512 | 25.046 us | 24.749 us |
|                              |                  |      |           |           |
|        ContainsFalse&lt;String&gt; |          HashSet |  512 | 19.125 us |  8.904 us |
|        ContainsFalse&lt;String&gt; | ImmutableHashSet |  512 | 43.490 us | 33.484 us |
|                              |                  |      |           |           |
|          ContainsTrue&lt;Int32&gt; |          HashSet |  512 |  6.719 us |  3.475 us |
|          ContainsTrue&lt;Int32&gt; | ImmutableHashSet |  512 | 26.984 us | 26.511 us |
|                              |                  |      |           |           |
|         ContainsTrue&lt;String&gt; |          HashSet |  512 | 21.438 us | 10.982 us |
|         ContainsTrue&lt;String&gt; | ImmutableHashSet |  512 | 47.016 us | 39.144 us |

So it's 2x up to 4x slower depending on the scenario.

> Is this still up for grabs?

yes!

**Comment by robertDurst** [comment]
Those numbers look about right - I was double/triple checking my numbers and getting different results +/- 5-20us depending on the measured mean (more if bigger). I suppose this makes sense given the scale of the tests?

Also, I wanted to test against the locally built version of `dotnet/runtime`. Is this the correct command: 
```
 dotnet run -c Release -f netcoreapp3.1 --filter *Contains*HashSet --join --corerun .\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\6.0.0\CoreRun.exe
```

**Comment by adamsitnik** [comment]
> I suppose this makes sense given the scale of the tests?

These benchmarks are 100% CPU bound and should rather be stable. To get them more stable you can specify the affinity mask via `--affinity`. (Use `--help` to find out more)

> Is this the correct command

It is.  https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md#dotnet-runtime-prerequisites

**Comment by adamsitnik** [comment]
> Giving it a deeper look this week. Wanted to check-in since I hadn't responded in a little over a week. Cheers!

@robertDurst thanks for looking at this!

> The first is a traversal of the Root of the ImmutableHashSet, an AVL tree. Without a different data structure, not sure any gains here. Not as familiar with GetHashCode .

My suggestion would be to look at the past performance optimizations that we have applied to non-immutable `HashSet<T>` @benaadams might be able to provide some hints here

**Comment by eiriktsarpalis** [comment]
> The first is a traversal of the Root of the ImmutableHashSet, an AVL tree. Without a different data structure, not sure any gains here.

I concur, lookup in AVL trees is _O(log n)_ whereas in hashtables it's _O(1)_, so a divergence in performance is to be expected. @adamsitnik if you're refering to the fastmod optimization I don't believe that is applicable here.

> System.Private.CoreLib.dll!System.Marvin::ComputeHash32 0x0
>
> Not as familiar with GetHashCode .

Presumably this is related to string hashcode generation, not `ImmutableHashSet` per se.

I feel like we can close this issue. Feel free to reopen if you feel that there is opportunity to optimize `ImmutableHashSet` here.

**Comment by sharwell** [comment]
As @eiriktsarpalis pointed out, `ImmutableHashSet<T>` is implemented using an AVL tree. This storage mechanism is designed _exclusively_ for ease of implementation among algorithms with O(log n) speed and O(n) storage, but leaves significant room for improvement. The primary tracking issue to replace the AVL implementation is #14477, with my personal ongoing experiments in [tunnelvisionlabs/dotnet-trees](https://github.com/tunnelvisionlabs/dotnet-trees/).

**Comment by adamsitnik** [comment]
@eiriktsarpalis @sharwell thank you for the full explanation. 👍 

PS I have high hopes for #14477 as I always prefer `Immutable` over mutable collections and the most frequently used method of `HashSet` should be fast ;)

**Comment by stephentoub** [comment]
> PS I have high hopes for #14477 as I always prefer Immutable over mutable collections and the most frequently used method of HashSet should be fast ;)

FWIW, that's still not going to turn an O(log N) operation into an O(1) operation.
