### ISSUE TITLE
Queue<T>.Enqueue and Stack<T>.Push are slower than List<T>.Add

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#29084]
All 3 collections are just `Array` wrappers so adding an element should be on par.

How to run the benchmarks:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 --filter '*CreateAddAndClear*.List' '*CreateAddAndClear*.Stack' '*CreateAddAndClear*.Queue' --bdn-arguments "--join true"
```

|                   Type | Method | Count |     Mean |
|----------------------- |------- |------ |---------:|
|  AddDefaultSize&lt;Int32&gt; |   List |   512 | 1.427 us |
| AddDefaultSize&lt;String&gt; |   List |   512 | 2.891 us |
|  AddDefaultSize&lt;Int32&gt; |  Queue |   512 | 2.480 us |
| AddDefaultSize&lt;String&gt; |  Queue |   512 | 3.549 us |
|  AddDefaultSize&lt;Int32&gt; |  Stack |   512 | 1.587 us |
| AddDefaultSize&lt;String&gt; |  Stack |   512 | 3.616 us |

Full docs for the new benchmarking workflow: https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md

**Comment by adamsitnik** [comment]
`Queue<T>.Enqueue` and `Stack<T>.Push` are still slower than `List<T>.Add`. I am going to reopen it and mark it as up-for-grabs & Future

**Comment by eiriktsarpalis** [comment]
The benchmarks should be rerun using .NET 6 to validate that the performance differences are still measurable.

**Comment by adamsitnik** [comment]
> The benchmarks should be rerun using .NET 6 to validate that the performance differences are still measurable.

Good point. I've ru-run them using following command:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 --filter '*CreateAddAndClear*.List' '*CreateAddAndClear*.Stack' '*CreateAddAndClear*.Queue' --bdn-arguments "--join true"
```

`Stack` is now as fast as `List` and `Queue` is just slightly slower for value types, so I think that we can just close it.

<details>

```ini
BenchmarkDotNet=v0.13.1.1616-nightly, OS=Windows 10.0.22000
AMD Ryzen Threadripper PRO 3945WX 12-Cores, 1 CPU, 24 logical and 12 physical cores
.NET SDK=6.0.101
```

|                      Type | Method | Size |     Mean |     Error |    StdDev |   Median |      Min |      Max |  Gen 0 |  Gen 1 | Allocated |
|-------------------------- |------- |----- |---------:|----------:|----------:|---------:|---------:|---------:|-------:|-------:|----------:|
|  CreateAddAndClear&lt;Int32&gt; |   List |  512 | 1.144 us | 0.0030 us | 0.0025 us | 1.145 us | 1.140 us | 1.149 us | 0.5138 | 0.0046 |      4 KB |
|  CreateAddAndClear&lt;Int32&gt; |  Stack |  512 | 1.130 us | 0.0019 us | 0.0018 us | 1.129 us | 1.127 us | 1.134 us | 0.5127 | 0.0045 |      4 KB |
|  CreateAddAndClear&lt;Int32&gt; |  Queue |  512 | 1.476 us | 0.0039 us | 0.0037 us | 1.476 us | 1.470 us | 1.483 us | 0.5146 | 0.0059 |      4 KB |
| CreateAddAndClear&lt;String&gt; |   List |  512 | 2.254 us | 0.0045 us | 0.0042 us | 2.254 us | 2.244 us | 2.260 us | 0.9958 | 0.0272 |      8 KB |
| CreateAddAndClear&lt;String&gt; |  Stack |  512 | 2.409 us | 0.0035 us | 0.0031 us | 2.408 us | 2.405 us | 2.415 us | 1.0012 | 0.0289 |      8 KB |
| CreateAddAndClear&lt;String&gt; |  Queue |  512 | 2.199 us | 0.0065 us | 0.0058 us | 2.200 us | 2.191 us | 2.209 us | 1.0027 | 0.0264 |      8 KB |

```ini
BenchmarkDotNet=v0.13.1.1616-nightly, OS=ubuntu 18.04
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.101
```

|                      Type | Method | Size |     Mean |     Error |    StdDev |   Median |      Min |      Max |  Gen 0 |  Gen 1 | Allocated |
|-------------------------- |------- |----- |---------:|----------:|----------:|---------:|---------:|---------:|-------:|-------:|----------:|
|  CreateAddAndClear&lt;Int32&gt; |   List |  512 | 1.218 us | 0.0019 us | 0.0016 us | 1.218 us | 1.216 us | 1.222 us | 0.5471 | 0.0049 |      4 KB |
|  CreateAddAndClear&lt;Int32&gt; |  Stack |  512 | 1.255 us | 0.0014 us | 0.0013 us | 1.255 us | 1.253 us | 1.257 us | 0.5448 | 0.0050 |      4 KB |
|  CreateAddAndClear&lt;Int32&gt; |  Queue |  512 | 1.560 us | 0.0026 us | 0.0024 us | 1.560 us | 1.557 us | 1.566 us | 0.5453 | 0.0063 |      4 KB |
| CreateAddAndClear&lt;String&gt; |   List |  512 | 2.877 us | 0.0045 us | 0.0040 us | 2.877 us | 2.870 us | 2.884 us | 1.0650 | 0.0347 |      8 KB |
| CreateAddAndClear&lt;String&gt; |  Stack |  512 | 2.818 us | 0.0044 us | 0.0041 us | 2.817 us | 2.811 us | 2.827 us | 1.0589 | 0.0338 |      8 KB |
| CreateAddAndClear&lt;String&gt; |  Queue |  512 | 3.057 us | 0.0058 us | 0.0054 us | 3.059 us | 3.048 us | 3.065 us | 1.0593 | 0.0244 |      8 KB |

</details>

**Comment by eiriktsarpalis** [comment]
Thanks @adamsitnik!

**Comment by danmoseley** [comment]
Was curious why `Queue<T>.Enqueue` was slower and I guess part of it is that it has to write to `_tail` as it's circular.

But I guess some microoptimization is possible -- changing to `if ((uint)_size < (uint)_array.Length)` and also extracting the resize path.
```
        public virtual void Enqueue(object? obj)
        {
            if (_size == _array.Length)
            {
                int newcapacity = (int)((long)_array.Length * (long)_growFactor / 100);
                if (newcapacity < _array.Length + MinimumGrow)
                {
                    newcapacity = _array.Length + MinimumGrow;
                }
                SetCapacity(newcapacity);
            }
```

**Comment by adamsitnik** [comment]
@danmoseley this issue was referring to the generic `Queue<T>` for which the resize path has already been extracted:

https://github.com/dotnet/runtime/blob/17d8fe58ca7aaa2bd924050a82cf0cada39c06df/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Queue.cs#L179-L190
