### ISSUE TITLE
ImmutableDictionary.ContainsKey is few times slower than Dictionary.ContainsKey or even ConcurrentDictionary.ContainsKey

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#29088]
How to run the benchmarks:

```cmd
git clone https://github.com/dotnet/performance.git
# if you have .NET Core 3.0 installed
dotnet run -c Release -f netcoreapp3.0 -p .\performance\src\benchmarks\micro\MicroBenchmarks.csproj --filter *ContainsKey*Dictionary --join
# if you don't have .NET Core 3.0 installed
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --filter *ContainsKey*Dictionary --bdn-arguments="--join true"
```

|                             Type |                    Method | Size |       Mean |
|--------------------------------- |-------------------------- |----- |-----------:|
|   ContainsKeyFalse&lt;Int32, Int32&gt; |                Dictionary |  512 |   4.209 us |
| ContainsKeyFalse&lt;String, String&gt; |                Dictionary |  512 |  12.358 us |
|    ContainsKeyTrue&lt;Int32, Int32&gt; |                Dictionary |  512 |   4.264 us |
|  ContainsKeyTrue&lt;String, String&gt; |                Dictionary |  512 |  14.792 us |
|   ContainsKeyFalse&lt;Int32, Int32&gt; |               IDictionary |  512 |   6.413 us |
| ContainsKeyFalse&lt;String, String&gt; |               IDictionary |  512 |  13.542 us |
|    ContainsKeyTrue&lt;Int32, Int32&gt; |               IDictionary |  512 |   5.764 us |
|  ContainsKeyTrue&lt;String, String&gt; |               IDictionary |  512 |  14.916 us |
|   ContainsKeyFalse&lt;Int32, Int32&gt; |          SortedDictionary |  512 |  59.212 us |
| ContainsKeyFalse&lt;String, String&gt; |          SortedDictionary |  512 | 640.896 us |
|    ContainsKeyTrue&lt;Int32, Int32&gt; |          SortedDictionary |  512 |  56.822 us |
|  ContainsKeyTrue&lt;String, String&gt; |          SortedDictionary |  512 | 501.203 us |
|   ContainsKeyFalse&lt;Int32, Int32&gt; |      ConcurrentDictionary |  512 |   5.960 us |
| ContainsKeyFalse&lt;String, String&gt; |      ConcurrentDictionary |  512 |  19.438 us |
|    ContainsKeyTrue&lt;Int32, Int32&gt; |      ConcurrentDictionary |  512 |   6.338 us |
|  ContainsKeyTrue&lt;String, String&gt; |      ConcurrentDictionary |  512 |  23.710 us |
|   ContainsKeyFalse&lt;Int32, Int32&gt; |       ImmutableDictionary |  512 |  16.871 us |
| ContainsKeyFalse&lt;String, String&gt; |       ImmutableDictionary |  512 |  41.192 us |
|    ContainsKeyTrue&lt;Int32, Int32&gt; |       ImmutableDictionary |  512 |  22.649 us |
|  ContainsKeyTrue&lt;String, String&gt; |       ImmutableDictionary |  512 |  47.884 us |
|   ContainsKeyFalse&lt;Int32, Int32&gt; | ImmutableSortedDictionary |  512 |  36.014 us |
| ContainsKeyFalse&lt;String, String&gt; | ImmutableSortedDictionary |  512 | 588.991 us |
|    ContainsKeyTrue&lt;Int32, Int32&gt; | ImmutableSortedDictionary |  512 |  29.912 us |
|  ContainsKeyTrue&lt;String, String&gt; | ImmutableSortedDictionary |  512 | 489.999 us |

Full docs for the new benchmarking workflow: https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md

**Comment by AqlaSolutions** [comment]
Yeah, what's the point to use ImmutableDictionary if it's slower than ConcurrentDictionary on get operations?

**Comment by eiriktsarpalis** [comment]
This is not an apples-to-apples comparison, `ImmutableDictionary` stores hash buckets using an AVL tree and as such its performance profile for lookups should sit between `Dictionary` and `SortedDictionary`, which it does seem to do.

See https://github.com/dotnet/runtime/issues/14477 for a proposal on potentially improving performance for immutable collections.
