### ISSUE TITLE
Incorrect behavior of SortedDictionary when used with OrdinalIgnoreCase comparer

### ISSUE THREAD

**Issue by AndreyChechel** [dotnet/runtime#29112]
Number of entries added to a `SortedDictionary` shouldn't be affected by the order of insertion.
The issue is reproducible in non-Windows environments (checked in .NET Core 2.1 / 2.2).
See [playground](https://tio.run/##vZLBbtNAEIbvfopRT45EXMVxLhgqoVAhBFUQqcoBcVjW07CSPRvNrkMjFKlqbuU1uPXSqufeeID0GfIgYb1NUOpCEVIUH9be@Wf/Hc980jSlZlwsSqNoAP2xsVikwfou6uo8R2mVJhO9QkJWspbxHo@XGXWhJKsKjI6QjVOdkgbBsPycKwkyF8bAO9YDFkXwLQBYCsYK614jrTI4EIrChtMqHaDratA5Rh9YWXyrCMN9GinWVCDZqNdf3tNwt1Tpu7vQ3Oizcj1EY6ErDEJrFdo/GboWYAa6tMPSPoVkpbyQthT5w/iGS/O2I8GQKWlb8BwIv0Jfs6vppfLDETx@Ziy7KTwBRXYv7PtNVxdDwchRjzNFIn89IIdE9XerPnrHjzuVAe18ctatdD0@u5ld3p7efp/deDFOa4d@XtHd6uV2XVbkFy8m98T59Hw@vZif/ZhPr9e/fWpnWdxDJvxph62Dr5FWne751htIoAm9N1tjI4ZQfhE0qKDgDBn0seu7Qa6G0fhvcDrbACfeODjxX8CJHwMn/sfw22nN/z5jSV1eZ@xxcOI/gdOB8PeYkmpyk2CyWPwC).

There are 5 entries being inserted in the sample below. The dictionary is supposed to have 4 entries, since two records have the equal keys in terms of `OrdinalIgnoreCase` comparer, 
- `["narınnarın"] = 3`
- `["narinnarin"] = 4`

Proving [snippet](https://tio.run/##LY5BCsIwEEX3OcXQVQraHqC4Ki4Ei4KC6zGGEkgndaYRRTyUd/BeNa1uZvjzPvO/kaUJbMcxiqMWDg8ZbFcp1cezdwaMRxHYc2gZO/VUAH8gAw5p3YK7QIOOdJ7YxAFuyGCvET2sko3T22I9SdEZIX/e9JvZAibtaB5JHWZvHbo@HSRQseOLI/SbllLDGsXm1RxQB5LgbXFiN9itI6vnuLyCsoTsyNFmoANBQvFeNmimbi/1Gscv):
```cs
var equal = string.Equals("narınnarın", "narinnarin", StringComparison.OrdinalIgnoreCase);
Console.WriteLine(equal); // "True" (on Linux/Mac)
```

## Sample

```cs
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.Versioning;

public class Program
{
  public static void Main()
  {
    Console.WriteLine(Environment.OSVersion);

    // ------------------------------------------------------------------------------
    // Test Case 1
    // Expected output: 4
    // Actual output: 4
    // ------------------------------------------------------------------------------

    var dict1 = new SortedDictionary<string, int>(StringComparer.OrdinalIgnoreCase);

    dict1["naryn"] = 1;
    dict1["нарын"] = 2;
    dict1["narınnarın"] = 3;
    dict1["narinnarin"] = 4;
    dict1["ナルインナルイン"] = 5;

    Console.WriteLine(dict1.Count); // Outputs 4 - OK

    // ------------------------------------------------------------------------------
    // Test Case 2 (changed order of insertion)
    // Expected output: 4
    // Actual output: 5
    // ------------------------------------------------------------------------------

    var dict2 = new SortedDictionary<string, int>(StringComparer.OrdinalIgnoreCase);

    dict2["naryn"] = 1;
    dict2["нарын"] = 2;
    dict2["ナルインナルイン"] = 3;
    dict2["narınnarın"] = 4;
    dict2["narinnarin"] = 5;

    Console.WriteLine(dict2.Count); // Outputs 5 (Expected 4)
  }
}
```

## Actual Output
```
Unix 5.0.3.200
4
5
```

## Expected Output
```
Unix 5.0.3.200
4
4
```

**Comment by GrabYourPitchforks** [comment]
Seems like it might be an ICU bug? Per @pgovind's comment, the collation engine is returning `s1 < s2`, `s1 > s3`, and `s2 == s3`. Those three relationships when taken together are nonsensical.
