### ISSUE TITLE
Provide an abstraction for the system clock

### ISSUE THREAD

**Issue by lukepuplett** [dotnet/runtime#29139]
Should we have a standard abstraction for the wall-clock that returns the local `DateTimeOffset`?

The idea is to break the hard dependency on the system clock and be able to inject a different clock for system level testing of time and ageing impacts, especially useful in finance.

I've rarely seen anyone do this but often seen people that wish they had. I think its just a habit we haven't learned yet.

If we saw more types taking `IWallClock` or whatever we'd maybe think more about this. Sure its super easy to implement but like `ILogFactory` life's better when we're all using a uniform interface.

**Comment by terrajobst** [comment]
Let's close this in favor of #36617 (because it has more comments)
