### ISSUE TITLE
[API] Add ASCIIEncoding.IsEquivalentOrdinal(ROS<char>, ROS<byte>)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#29134]
From https://github.com/aspnet/AspNetCore/pull/8374#discussion_r270713249

Cross encoding compare
```csharp
namespace System.Text
{
    public partial class ASCIIEncoding : Encoding
    {
        public static bool IsEquivalentOrdinal(
            ReadOnlySpan<char> chars, 
            ReadOnlySpan<byte> asciiBytes);
    }
}
```

This is method to test whether a sequence of ascii bytes is the same as a string; without having to first convert the bytes to a sting and allocate and then use string equality. (e.g. compare ascii bytes to a UTF-16 string)

Used in https://github.com/aspnet/AspNetCore/pull/8374 to drop steady state string allocations to zero (as previous materialized strings can be reused when they match the on-wire bytes) 

e.g.

![image](https://user-images.githubusercontent.com/1142958/55302126-9fa78080-5437-11e9-9976-77ad6fac8fa9.png)

Could extend with an `bool ignoreCase = false` if desired, however that is not required for this particular use case. 

/cc @GrabYourPitchforks @davidfowl @halter73

**Comment by GrabYourPitchforks** [comment]
Tracked by https://github.com/dotnet/runtime/issues/28230.
