### ISSUE TITLE
API Addition: `ExcludeFromCodeCoverageAttribute(string reason)`

### ISSUE THREAD

**Issue by hughbe** [dotnet/runtime#29185]
Frequently I want to add a reason why something is excluded from code coverage. In the vein of the `Justification` property of `SurpressMessageAttribute`, maybe this addition would be useful:

```cs
public class ExcludeFromCodeCoverageAttribute
{
        public ExcludeFromCodeCoverageAttribute();
        public ExcludeFromCodeCoverageAttribute(string reason);

        public string Reason { get; set; }
}
```

**Comment by stephentoub** [comment]
@terrajobst, this is marked api-approved.  What is the approved design?

**Comment by terrajobst** [comment]
> @terrajobst, this is marked api-approved. What is the approved design?

Can't tell. This issue was approved before I started to explicitly put comments on everything we approved. I assume we thought the design as outlined in the description was sufficient to approve.

**Comment by stephentoub** [comment]
Ok.  In #38520 I merged just adding a `string? Justification` property, per https://github.com/dotnet/runtime/issues/29185#issuecomment-571726362

**Comment by terrajobst** [comment]
Makes sense. We probably didn't consider the suppress message attribute.

**Comment by GrabYourPitchforks** [comment]
Yes, sorry. That was unclear in my comment. This came through API review on Jan 7, and the feedback was "approved, but instead of using a new constructor parameter add an optional _Justification_ property to match  _SuppressMessageAttribute_'s shape."
