### ISSUE TITLE
Fixing build for src/shims/manual to use appropriate configurations

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#29206]
The build for manual shims against netcoreappaot is currently broken. This is due to the fact that some of projects use a different version of System.Private.CoreLib.
We can add ```netcoreappaot``` in all those projects but we have to verify that this is not interfering with other msbuild properties and items being defined. 
The error can be reproduced by running ```build.cmd -f netcoreappaot ```

```
Build FAILED.

C:\git\corefx\artifacts\obj\mscorlib\netcoreappaot-Debug\mscorlib.Forwards.cs(1073,93): error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [C:\git\corefx\src\shims\manual\mscorlib.csproj]
C:\git\corefx\artifacts\obj\mscorlib\netcoreappaot-Debug\mscorlib.Forwards.cs(1073,12): error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [C:\git\corefx\src\shims\manual\mscorlib.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:03:27.72
```

The newGenfacades  bring forward a lot of issues with manual facades. Some of them were handled in https://github.com/dotnet/corefx/pull/36126 but in a little hacky way.

Manual shims have a dependency on System.Private.CoreLib as it uses some public types which are not exposed in the reference assembly. 
me and @ericstj tried aliasing these types and removing the reference to System.Private.CoreLib while generating facades but the compiler doesn't allow aliasing of SPC

We require a new approach to handle these manual shims

@ericstj feel free to edit the description.

**Comment by ViktorHofer** [comment]
@ericstj while triaging the `untried` issues I stumbled upon this. I noticed this as well in my local build. Giving this another thought I don't think we want to build the manual shims against the ref assemblies as we probably don't want to add the internals that we type forwarding to. Am I missing something here?

**Comment by ViktorHofer** [comment]
Based on our earlier discussion, there is value in being able to construct the shared framework without OOB libraries being built. If we do something about this issue we should keep that in mind.

**Comment by ericstj** [comment]
> we probably don't want to add the internals that we type forwarding to

There are varying opinions on this.  One opinion might be that we ought to include them since they've become defacto public surface area via binary serialization and putting it in the ref allows us to track it and test it (via API compat).  Another opinion is that we may some day remove binary serialization completely and do away with these.

**Comment by ViktorHofer** [comment]
Closing as shims now target the right tfm: https://github.com/dotnet/runtime/blob/6762f54b4193dcf5103f3c03e7ebd0ef95578c54/src/libraries/shims/Directory.Build.props#L6. Also, it's already possible to build just the sfx with the `libs.sfx` subset which then skips the shims.
