### ISSUE TITLE
System.Json: JsonValue.Parse small bug

### ISSUE THREAD

**Issue by erin-knight** [dotnet/runtime#29203]
I noticed when using JsonValue.Parse that JSON syntax errors are caught, except for this one, where the opening quote is omitted on the last value in the JSON string, and it is a number, it considers it valid JSON:

```c#
var jsonString = "{\"Age\": 5"}"; // Without escaped characters for readability: { "Age": 5" }

try
{
    jsonObject = JsonValue.Parse(jsonString);
    return true;
}
catch
{
    jsonObject = null;
    MessageErrors.Add("Message contains invalid JSON.");
    return false;
}
```

**Comment by stephentoub** [comment]
This lib had been removed from dotnet/runtime.
https://github.com/dotnet/runtime/pull/32329
Any further changes to it would need to meet a high servicing bar.
