### ISSUE TITLE
File path and byte array based X509Certificate2 constructors

### ISSUE THREAD

**Issue by ritchxu** [dotnet/runtime#29216]
I read this article talking about the difference between using two constructors of X509Certificate2 class (Tip 5 http://paulstovell.com/blog/x509certificate2). I did profile the two usages and found the constructor using file path did outpace the other one. But it surprised me that accessing disk is faster than memory (byte array). Is the profiler giving me wrong impression? Does it only apply to .NET Framework not Core?

**Comment by bartonjs** [comment]
For Windows, at least, the two behaviors are determined by the OS (we just pass the bytes or the string, with a flag saying which it is, into the same native API). I believe the problem might be that some codepaths in the "here are some bytes" path might need to create temporary files.  But that's a detail of the OS function we call, we can't really give guidance on it.
