### ISSUE TITLE
API proposal: BinaryPrimitives.ToLittleEndian / FromLittleEndian

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#29222]
There are some scenarios (see https://github.com/dotnet/coreclr/pull/21948#discussion_r273272627) where we want to take a value in machine-endian order and convert it to little-endian. This is the opposite of normal APIs like `htonl` and `ntohl`, which convert between machine-endian and big-endian.

__Proposed API additions__

```cs
namespace System.Buffers.Binary
{
    // NEW methods added to EXISTING type
    public static class BinaryPrimitives
    {
        // convert from machine-endian to little-endian
        public static uint ToLittleEndian(uint value);

        // convert from little-endian to machine-endian
        public static uint FromLittleEndian(uint value);
    }
}
```

There would be overloads matching the existing overloads on `ReverseEndianness`: `byte`, `sbyte`, `short`, `ushort`, `int`, `uint`, `long`, `ulong`.

Open question: Do we also have `ToBigEndian` / `FromBigEndian` for parity and discoverability? Those APIs already exist on `IPAddress.HostToNetworkOrder` and `IPAddress.NetworkToHostOrder`. But those APIs require your application to pull in the package __System.Net.Primitives__, whereas these would all be contained within a single type.

**Comment by terrajobst** [comment]
We need a more compelling reason. Sorry Levi :-)

**Comment by alfredmyers** [comment]
It's unfortunate it's being rejected. Although I don't remember the specifics, I clearly remember months ago finding it odd that this functionality was buried in [IPAddress](
https://github.com/dotnet/runtime/blob/af1090c27b82373d30d1ec9c3cefacf3827f3d8b/src/libraries/System.Net.Primitives/src/System/Net/IPAddress.cs#L390) instead of being made available in a more generalized way.

**Comment by GrabYourPitchforks** [comment]
The reasoning that we settled on in API review is that we should be encouraging developers to use the APIs that read from / write to `Span<byte>`, and those APIs can handle endianness conversions appropriately.
