### ISSUE TITLE
Designing an [AttributeCtorUsageAttribute] that constrains the constructor of a custom attribute to declare the specified target

### ISSUE THREAD

**Issue by xljiulang** [dotnet/runtime#29243]
For a custom attribute, we already have the [AttributeUsage] to constrain its targets, but when it has multiple constructors, we can't limit a constructor to declare at one or more sub target. So I hope to design this new [AttributeCtorUsageAttribute].

>  AttributeCtorUsage

```c#
[AttributeUsage(AttributeTargets.Constructor, AllowMultiple = false)]
public sealed class AttributeCtorUsageAttribute : Attribute
{
    public AttributeTargets Targets { get; }

    public AttributeCtorUsageAttribute(AttributeTargets targets)
    {
        this.Targets = targets;
    }
}
```
>  Custom attribute

```c#
[AttributeUsage(AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Parameter, AllowMultiple = false, Inherited = true)]
public class TimeoutAttribute : ApiActionAttribute, IApiParameterAttribute
{
    [AttributeCtorUsage(AttributeTargets.Parameter)]
    public TimeoutAttribute()
    {
    }

    [AttributeCtorUsage(AttributeTargets.Interface | AttributeTargets.Method)]
    public TimeoutAttribute(int milliseconds)     
    {
    }
}
```

I need this feature in my project, and now I can only detect [AttributeCtorUsage] by the extended diagnostic analyzer.

**Comment by stephentoub** [comment]
> I need this feature in my project, and now I can only detect [AttributeCtorUsage] by the extended diagnostic analyzer.

Thanks for the suggestion.   This would require changes to both the runtime and language, and it is too niche to warrant such changes.  As you noted, you can achieve this yourself via your own analyzer you ship with your library; if you find it valuable, you can publish it on nuget and others that are in a similar boat can consume your package.  This has garnered too little interest in the last three years to warrant an investment here, so I'm going to close it.  Thanks.
