### ISSUE TITLE
API proposal: Add AppContext.ApplicationConfig

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#29271]
While `app.config` isn't the way we configure Core, plenty of ported libraries still use `System.Configuration`. We don't expose `ConfigurationFile` on `AppDomainSetup` any more and we hack it's path directly in `System.Configuration`.

A common pattern, particularly for testing frameworks, is to fire up a new `AppDomain` with a custom config file. As we only have a single `AppDomain` on Core this isn't possible and is creating some serious pain in porting larger more complicated projects. We can provide the customization at the hosting level by exposing a property like `APP_CONTEXT_CONFIGURATION_FILE` much like we do `APP_CONTEXT_BASE_DIRECTORY`.

``` C#
public partial class AppDomainSetup
{
    // This API exists on NetFX
    // Populated with APP_CONTEXT_CONFIGURATION_FILE by default
    public string ConfigurationFile { get; set; }
}
```

See dotnet/runtime#931 and linked issues for more.

We could also add another field to `AppContext` to see what this setting is, but it isn't strictly necessary. For `APP_CONTEXT_BASE_DIRECTORY` we expose it from `AppContext.BaseDirectory`. To follow suit we would add (and populate the default for `AppDomainSetup` above from this):

``` C#
public static partial class AppContext
{
    // Populated with "APP_CONTEXT_CONFIGURATION_FILE" much like "APP_CONTEXT_BASE_DIRECTORY"
    public static string ConfigurationFile { get; }
}
```

**Comment by JeremyKuhne** [comment]
@maryamariyan Fyi, this is `System.Configuration` specific.

**Comment by jkotas** [comment]
I do not think it makes sense to add this API to support legacy configuration system since we have lived for multiple releases without it now.
