### ISSUE TITLE
Activity.Current should allow association with the active Asp.Net Core app

### ISSUE THREAD

**Issue by SergeyKanzhelev** [dotnet/runtime#29285]
There are scenarios when multiple apps are running in a single process. It may be service fabric hosting multiple ASP.NET apps or Azure Functions host tearing down and loading the new function.

In scenarios like this telemetry configuration is typically set up per app, not per host. Thus when DiagnosticsListener is created and listens for the Activity events - there is no way to react differently depending on on the current app settings.

Ideally there should be some way to get to the app definition, or better of DI container from the `Activity.Current` or from some other package in `AsyncLocal`.

So it may be either `Activity` feature or the feature of DI in ASP.NET Core.

CC: @davidfowl @lmolkova @glennc @anurse

**Comment by tarekgh** [comment]
Closing this as it looks answered by David. Feel free to reopen if still think there is more need to be done.
