### ISSUE TITLE
Suggestion: Add generic interface, SQL protocol directly mapped to entity classes.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#29335]
I'm a new guy.

I've envisioned a SQL processing process, It is roughly as follows: 
`
SQL Request -> Get Reponse -> Store Buffer -> ConvertTo  TClass -> Return TClass
`

```C#

SqlCommand cmd = new SqlCommand(sql, conn, typeMappings);//typeMappings:SqlType->EntityType
TClass entity = cmd.EntityReader<TClass>();

```
```C#

public interface  IDbCommand<T> {
    T EntityReader<T>();
}

```
Is this proposal feasible?

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to implement.
