### ISSUE TITLE
Suggestions: Add .UniqueOrDefault() to handle multiple occurrences without Exception

### ISSUE THREAD

**Issue by LWChris** [dotnet/runtime#29398]
### Problem

Currently, providing `First`, `Last` and `Single` (and their `…OrDefault` variants), LINQ offers three ways of retrieving **one** element that meets certain criteria out of many candidates.

The `…OrDefault` variants provide a way to avoid the `InvalidOperationException` for `n == 0`. So we're good on that side.

However LINQ does currently not provide an easy way allowing you to differentiate between `n == 1` and `n > 1` without the necessity to introduce exception handling: `FirstOrDefault` and `LastOrDefault` return an element whether or not it's the only matching one. `SingleOrDefault` only returns an element for `n == 1`, but throws an `InvalidOperationException` for `n > 1`.

### Proposed solution

I'm proposing `UniqueOrDefault` as an addition to the LINQ API. The method retrieves an element in case it's the only matching element, and `default(T)` in case of `n == 0` **and** `n > 1`.

![UniqueOrDefault](https://user-images.githubusercontent.com/845152/56851276-79c5ac80-690d-11e9-98f5-d77233c59b94.png)

### Use Case

I used this method in various projects for pre-selecting a value:

```cs
private string TryGetAutoCompletion(string input) {
    return CurrentEntries.UniqueOrDefault(e => e.StartsWith(input));
}
```

```cs
var availableOptions = options.Where(o => IsOptionApplicable(o, currentSetup));

// If there's only one option applicable, use that,
// otherwise select default option if unambiguous.
var selectedOption = availableOptions.UniqueOrDefault()
    ?? availableOptions.UniqueOrDefault(o => o.IsDefault);

if (selectedOption == null) {
    // No unambiguous go-to option. Let the user pick one.
    selectedOption = ShowOptionSelectDialog(availableOptions);
}
```
### Remarks

One important characteristic of my use cases is that you don't need to distinguish between `n == 0` and `n > 1`, because all you're asking is "Is there an unambiguous choice?". So it doesn't matter _why_ we don't have a result, it's enough to know _that_ we didn't get one.

With the possiblity of returning tuples in C# and VB.NET 2017, we _may_ consider returning a tuple `(int count, T value)` to enable differentiating that as well, but I don't know if (a) **all** languages with access to LINQ are capable of tuple returns, and (b) I'd rather stick closer to the API of `SingleOrDefault` instead of introducing the first and only method to the LINQ API that makes use of tuple return values.

Note that I do not recommend to add the `Unique` function as well. Maintaining the current pattern, that method would have to throw for `n == 0` but return `default(T)` for `n > 1`.

Although this combination is indeed missing in the grid, I find that the question of uniqueness is binary, not ternary. Either there is a unique choice, or there isn't. And if there isn't, you would either want it to throw always or never consistently. That is, you want `Single` (always throw) or `UniqueOrDefault` (never throw).

I feel this is a question of naming though. While having varying behavior for a method named "Unique" doesn't feel intuitive to me, other names may do a better job there. So if you have a method name that intuitively conveys it will throw for `n == 0` but return `default(T)` for `n > 1` and that can be extended by `…OrDefault` to gain the functionality of my proposed `UniqueOrDefault`, then I'm all for it. Because then you **truly** have free choice of how to handle `n == 0` and `n > 1` individually according to your needs.

### Implementation

The implementation is identical to `SingleOrDefault` but with `return default(TSource);` instead of `ThrowHelper.ThrowMoreThanOneElementException();`. Not much more to say about that I think.

**Comment by eiriktsarpalis** [comment]
I'll admit I'm not particularly sold on the `UniqueOrDefault` name, since the term "unique" has very different connotations, at least in my mind. Really this is a `FirstOrDefault` variant that does not throw, so assuming we wanted to go ahead with this, we should probably just give it a suffix, like `FirstOrDefaultThatDoesNotThrow`.

That being said, I'm not convinced this would be a very commonly used addition, and it can be defined trivially using an extension method.

**Comment by LWChris** [comment]
> Really this is a `FirstOrDefault` variant that does not throw, so assuming we wanted to go ahead with this, we should probably just give it a suffix, like `FirstOrDefaultThatDoesNotThrow`.

If you look at the table, `FirstOrDefault` and `UniqueOrDefault` behave totally different. `UniqueOrDefault` would actually behave exactly like `Single`, but return `default(TSource)` where `Single` would throw.

So either you made a mistake and meant `Single` instead of `FirstOrDefault`, or you have not yet understood the function. 😄 

If anything, `UniqueOrDefault` would be `SingleThatDoesNotThrow`, but I doubt that naming a function `SameAsXJustDifferent` is any better than coming up with a name that you can easily learn to understand.

I also disagree with the sentiment that `it can be defined trivially using an extension method`. That extension method would either have to use `Single` + `try catch` (which I think most agree is bad style), or you have to program your own iterator consumer loop, which is not too advanced, but already more than your typical one-liner extension.

**Comment by eiriktsarpalis** [comment]
> So either you made a mistake and meant Single instead of FirstOrDefault, or you have not yet understood the function. 😄

Indeed I was talking about SingleOrDefault. Again, I believe my argument still stands: the name "Unique" doesn't do a great job at communicating in what differentiates it from "Single". 

Also, the term "unique" has [very specific connotations in logic](https://en.wikipedia.org/wiki/Uniqueness_quantification): it should be reserved for a LINQ method between `Any` and `All` that returns true iff there exists exactly one element (any element) that satisfies a provided predicate.

> I also disagree with the sentiment that it can be defined trivially using an extension method. That extension method would either have to use Single + try catch (which I think most agree is bad style), or you have to program your own iterator consumer loop, which is not too advanced, but already more than your typical one-liner extension.

Trivial != one-liner. It should take no more than 5 minutes to write and test (no exception handling required).

**Comment by LWChris** [comment]
In my opinion, the idea of uniqueness is only tied to the "iff there exists exactly one element that satisfies a provided predicate" part. The "returns true" part is arbitrary to me. I'd argue retrieving the matching element is often more useful than just knowing it exists but still not having it.

* `Where` returns `n elements`. (Group: Retrieval)
* `Count` returns `n`. (Group: Cardinality)
* `Any` returns `if n > 0`. (Group: Existance)

Your idea would belong to `Any`. My idea would belong to `Where`. Both are existing concepts in the LINQ framework. And while I totally get the idea of Ǝ = `Any` and Ɐ = `All`, I don't see why `n = 1` needs a special function. I do see why `n = 1` is special in the `Where` group; after all that's what `First`, `Last` and `Single` do already, it's just that `Single` throws exceptions all the time.

> the term "unique" has very specific connotations in logic: it should be reserved for a LINQ method [...] that returns true iff there exists exactly one element [...] that satisfies a provided predicate.

Replace "returns true" with "returns the element", and return `default(T)` instead of `false` otherwise, and you get `UniqueOrDefault`.

That's the only difference, and that's why I think the term "Unique" is not a bad fit per se. It's just that the method without `OrDefault` doesn't make too much sense (throw if there is none, but not if theres more than one).

**Comment by LWChris** [comment]
It would be nicer to have a different word (say "Foo") that conveys that calling `Foo()` will

* throw for `n = 0`
* return the element for `n = 1`
* return `default(T)` for `n > 1`

so that calling `FooOrDefault()` will naturally become

* return `default(T)` for `n = 0`
* return the element for `n = 1`
* return `default(T)` for `n > 1`

That's the only reservation about using "Unique" as our "Foo", because it works out for `UniqueOrDefault` but not for `Unique`.

**Comment by eiriktsarpalis** [comment]
> The "returns true" part is arbitrary to me. 

Well, no. Uniqueness quantifiers return a boolean result by definition.

> I'd argue retrieving the matching element is often more useful than just knowing it exists but still not having it.

It depends. What is useful in returning `default` in an enumerable of value types?

In the interest of advancing the conversation, I'd be happy to accept that any talk about connotation is subjective. My main issue is how does the proposed name self-document the behaviour of the function when contrasted with `First*`?

>  after all that's what First, Last and Single do already, it's just that Single throws exceptions all the time.

I'll be the first to admit that I'm not the biggest fan of the `SingleOrDefault` design, but I can see what its originators might have wanted there. While providing method variants that don't throw is desirable in general, I'm not convinced that returning `default` is better (since it really only works well with non-nullable reference types). Given that upcoming C# releases will have support for discriminated unions, I wouldn't be surprised if it might include a true optional type, which could be used to better express what you are trying to achieve.

**Comment by LWChris** [comment]
> Uniqueness quantifiers return a boolean result by definition.

Yes, but why should the function try to become a uniqueness quantifier? The function can serve any purpose that's best suited for solving a problem at hand; why restrict it to conform with a mathematical definition that was unnecessarily imposed on it?

> What is useful in returning default in an enumerable of value types?

You are correct, `default(T)` is not particularly useful for non-nullable structs.* But that is also true for all existing `...OrDefault` LINQ methods. `UniqueOrDefault` would be perfectly in line with the other functions, by name and behavior. I don't think it's a problem.

Basically, if you don't want `default(T)` as return value, don't use that function; it's the same for `UniqueOrDefault` as for `[First|Last|Single]OrDefault`.

I gave two examples in the first post that illustrate use cases. The extension is most powerful for reference types in combination with null coalescing or null conditionals. Of course that's not always the case, so there are situations where the function does not fit your needs. But that is probably true for almost _any_ future addition to the framework. It can't be a reason to not include a function. The function has useful applications in some common scenarios (assuming autocompletion and smart pre-selection are common scenarios).

---

&#42; On a side note, if you want to solve **that** problem, we should consider to add `OrDefault` overloads that have an additional `T defaultValue` parameter.

**Comment by eiriktsarpalis** [comment]
Closing per feedback.
