### ISSUE TITLE
Proposal: Inject existing object into MEF2

### ISSUE THREAD

**Issue by gthvidsten** [dotnet/runtime#29400]
MEF1 has method `ComposeExportedValue<T>(T exportedValue)`. MEF2 should have a similar functionality in `System.Composition.Hosting.ConfigurationContainer` (as discussed in dotnet/runtime#18624 and dotnet/runtime#15362)

**Suggested API**

```
public ContainerConfiguration WithInstance<TExport> (TExport instance);
public ContainerConfiguration WithInstance<TExport> (string contractName, TExport instance);
public ContainerConfiguration WithInstance (Type t, object instance);
public ContainerConfiguration WithInstance (Type t, string contractName, object instance);
```

*(Thanks to @NEKIT-Boss for the examples in dotnet/runtime#18624)*

**Usage**

```
ContainerConfiguration containerConfig = new ContainerConfiguration()
    .WithAssembly(GetType().Assembly)
    .WithInstance<IExample>(new Example());

var container = containerConfig.CreateContainer();
var example = container.GetExport<IExample>();
```

**Comment by ericstj** [comment]
Thanks for the input @nblumhardt, I've gone ahead and marked this one ready-for-review.  Cheers!

**Comment by terrajobst** [comment]
I'd go with @nblumhardt's proposal:

```C#
namespace System.Composition.Hosting
{
    public class ContainerConfiguration
    {
        public ContainerConfiguration WithExport<T>(T exportedInstance, string contractName = null, IDictionary<string, object> metadata = null);
        public ContainerConfiguration WithExport(object exportedInstance, Type contractType, string contractName = null, IDictionary<string, object> metadata = null);
    }
}  
```

**Comment by bartonjs** [comment]
After some discussion on the name of the methods, the use of defaults parameters, and the name of the generic, it's approved as

```C#
namespace System.Composition.Hosting
{
    public class ContainerConfiguration
    {
        public ContainerConfiguration WithExport<TExport>(TExport exportedInstance);
        public ContainerConfiguration WithExport<TExport>(TExport exportedInstance, string? contractName = null, IDictionary<string, object>? metadata = null);

        public ContainerConfiguration WithExport(Type contractType, object exportedInstance);
        public ContainerConfiguration WithExport(Type contractType, object exportedInstance, string? contractName = null, IDictionary<string, object>? metadata = null);
    }
}

**Comment by ericstj** [comment]
@gthvidsten @nblumhardt this API was approved, were either of you going to drive the implementation in?  If we want this in .NET 5.0 it would need to be merged before 8/18 or sooner.

**Comment by nblumhardt** [comment]
I may get a chance - a bit short of time, though, so I'll be pleased if someone else beats me to it :-)

**Comment by danmosemsft** [comment]
Setting milestone to indicate this is not a required part of the 5.0 product.

**Comment by ZigMeowNyan** [comment]
Should also close issue #27324.

As the person who originally opened #15362 back in 2015, I'm glad to see this finally make it into the official packages. It drastically simplifies migration from MEF1 to MEF2 for people who don't need the flexibility of MEF1 and want to avoid the potentially higher performance cost. Refactoring a project to use plugins is a lot easier when you don't have to fully rearchitect to fit design assumptions and can just export an existing instance.

I'll be glad to review my legacy projects and adjust for this. Might even have time to swap out the old handwritten context classes for `AssemblyLoadContext`.
