### ISSUE TITLE
API: Single File Bundle APIs

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#29456]
This issue proposes adding a few APIs to support operations corresponding to .Net core apps that are published as single-file bundles. The APIs are based on customer requests.

## Proposed API

```cs
namespace System.Runtime.Loader
{
    public partial class Bundle
    {
        /// <summary>
        /// Check whether the current application is running from a single-file bundle.
        /// </summary>
        /// <returns>
        /// True if the app is a bundle, false otherwise.
        /// </returns>
        public static bool IsBundle();

        /// <summary>
        /// Get the location where contents of the bundle are extracted
        /// </summary>
        /// <returns>
        /// The absolute path to the directory containing the extracted files, 
        ///    if any files were extracted.
        /// null otherwise.   
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// If invoked in an app that is not a single-file bundle.
        /// </exception>
        public static string GetContentRoot();

        /// <summary>
        /// Open a file embedded within the single-file bundle.
        /// </summary>
        /// <param name="path">
        /// Relative path to a file within the single-file bundle
        /// </param>
        /// <returns>
        /// The IO stream corresponding to the file requested.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// If invoked in an app that is not a single-file bundle.
        /// </exception>
        /// <exception cref="ArgumentNullException">
        /// If path is null
        /// </exception>
        /// <exception cref="ArgumentException">
        /// If the file requested is not embedded in the bundle.
        /// </exception>
        public static System.IO.Stream GetFileStream(string path);
    }
}
```

### IsBundle()

It is likely that some apps are used in both single-file and normal publish modes (ex: for testing vs distribution, distributed differently on different platforms, etc). The app may use the information about whether it is running from a bundle to:
* Alter certain behavior about the way content files are processed
* Collect the information in telemetry or crash dumps
* etc.

### GetContentRoot()

When apps are published, it may expect certain content files to be present in the same location. For single-file apps, the embeded contents are extracted to a different directory. Apps can find the location of extracted files through this API.

In particular, ASP.NET Core apps currently set their “ContentRoot” to the current directory which includes for things like serving static files; when deployed as single-files, they'll need this API to set the "ContentRoot".  

### GetFileStream()

The binaries that are published in the project are expected to be handled transparently by the host. However, explicit access to the embedded files is useful in situations such as:

- Reading additional files packaged into the app (ex: data files).
- Open an assembly for reflection/inspection

Therefore, we propose adding an API similar to [GetManifestResourceStream](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getmanifestresourcestream?view=netframework-4.7.2#System_Reflection_Assembly_GetManifestResourceStream_System_String_) to obtain a stream corresponding to an embedded file. 

The implementation of this API may return: 
* A `FileStream` to the requested file is extracted out to disk, or 
* A `MemoryStream` to the file's contents embedded within the bundle. 

## Further Work

* We currently only have single-file app EXEs. In future, we may implement single-file class-libs that can be loaded into apps as plugins. For single-file plugins, we'll need to expand the above APIs to query with respect to the an assembly. The `assembly` argument is the main assembly into which its dependencies are embedded.

```cs
namespace System.Runtime.Loader
{
    public partial class Bundle
    {
        public static bool IsBundle(Assembly assembly);
        public static string GetContentRoot(Assembly assembly);
        public static System.IO.Stream GetFileStream(Assembly assembly, string name);
    }
}
```

* We can provide a variant of `GetFileStream()` API that abstracts away the details of whether an app is bundled or not. That is, if the app is bundled into a single-file, it fetches the file from the bundle (or extracted directory). If not, it finds the file on disk alongside the app binary. 
However such abstractions can easily be built outside of `CoreFX`.

## References

* Single-file distribution [work-item](https://github.com/dotnet/coreclr/issues/20287) 
* Single-file publishing [design doc](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md)

**Comment by tomrus88** [comment]
Why wasn't this added to .NET 5.0?

**Comment by jkotas** [comment]
We do not plan to add the APIs proposed above. The existing APIs are sufficient to address the scenarios that these APIs are trying to solve.

The suggested replacements are documented in https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility
