### ISSUE TITLE
There is no easy way to create an isolated dotnet installation

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#2948]
## Steps to reproduce

Install a copy of dotnet 2.0.0 to a non-default location, such as C:\private\.dotnet using the DotNet-Install.ps1 
Put the private copy of dotnet on the path
Run a command such as dotnet store

## Expected  behavior

The dotnet app loads all dotnet binaries from within C:\private\.dotnet\

## Actual behavior

Some binaries are loaded from global locations, such as C:\Program Files\dotnet\sdk\15.5.0-preview-007044\dotnet.dll

## Environment data

dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\github\JitBench\.dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

## Comments

This behavior is by design as far as I can tell, however I am proposing this design is not ideal and we should investigate changing it in the scope of this scenario at least. The current design has several downsides:

- It isn't the behavior users expected. The commonly held belief among devs I've spoken with is that creating a copy of the dotnet directory at a private location and executing dotnet.exe there has given them an isolated installation that loads dependencies from the same folder.
- Development and testing is more error-prone. The current design makes it very easy to accidentally load a binary from the global location instead of the one you thought you were testing.
- Repro environments are much harder to capture and reproduce accurately. For example see the environment data in this bug. If that is all the info we knew and I hadn't separately debugged/explicitly called out that 15.5.0-preview is actually the dotnet that loads its very likely any bug I hit in that configuration would have been resolved 'no repro'.

## Workarounds
I am currently using the environment var DOTNET_MULTILEVEL_LOOKUP=0 as a workaround. It is better than nothing, but I don't think it is a high quality solution on its own:

- Developers don't know about it, and because they don't expect this behavior in the first place they won't think to look for it.
- Environment variables do not persist for the lifetime of an installation. It is easy to forget to set it when running many commands over multiple sessions or switching between shells.
- It is incomplete (https://github.com/dotnet/core-setup/issues/3360)

**Comment by vitek-karas** [comment]
This is effectively fixed in .NET 7 because multi-level lookup is disabled by default.
