### ISSUE TITLE
.NET 5. Built-in DI -> Injectable Attributes #Discussion

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/runtime#29497]
Hi to all!
[NET 5.0 - great news](https://devblogs.microsoft.com/dotnet/introducing-net-5/)

Metadata, reflection, runtime code generation,  is why I love .NET so much.

Attributes. They have significant disadvantages.
1. They are static
2. Immutable
3. They are limited (definition) 

It is unlikely that I was the first to think about how to make attributes dynamic.
I want to suggest entering the interface
```
public interface ICustomAttributeDescriptor
    {
        IEnumerable<Attribute> GetCustomAttributes(ICustomAttributeProvider provider, bool inherit);
        IEnumerable<Attribute> GetCustomAttributes(ICustomAttributeProvider provider, Type attributeType, bool inherit);
        bool IsDefined(ICustomAttributeProvider provider, Type attributeType, bool inherit);
    }
```
By default, it should retrieve attributes as it is happening now. **Directly not necessarily at all to contact him. For compatibility, the default implementation should be used.**
for normal code
```Attribute.GetCustomAttributes```

Plus, I propose to add the ability to override attributes, add, delete, etc.
This is another interface.
This raises us almost to the level of DI and the use of attributes will be much more convenient.
It will be possible to change the attributes of other people's libraries.

There may be some problems with libraries like [Fody](https://github.com/Fody/Fody). Re-building will require original assemblies, this is not critical.

What do you think about it?

[My draft. Injectable Attributes](https://github.com/lobster2012-user/Lobster.Home.Dependency.InjectableAttributes)

_I apologize for my English._
And not sure I chose the right place for this discussion.
Coreclr?

**Comment by ericstj** [comment]
I don't think we'd want to add such a support to reflection.  Reflection is meant to reflect the real assembly, no funny business.   Allowing someone to add attributes to any type also feels like a security problem.  Just think if you could add attributes like Serializable to a type you don't own... 

What you are suggesting sounds very similar to how TypeDescriptor works today.  Check out [TypeDescriptor.AddAttributes](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typedescriptor.addattributes?view=netcore-3.1).  I think this sort of thing belongs above Reflection, and given we already have one system I don't imagine we'd add another unless there was a good problem definition of what was wrong with existing system and/or implementing at DI level.

@steveharter, thoughts?
