### ISSUE TITLE
Unable to run asyncronous tasks on the foreground thread by any means

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#29496]
dotnet/runtime#18449 was closed as unactionalbe but the root issue exists with no resolution.

If a threadpool thread (think any MVC thread) calls into a library that eventually calls `Task.Result`; the entire application is subject to deadlock.

The general rule of pushing `async` down by replacing `Object.MethodAsync().Result` with `await Object.Method()` and adding `async` to the caller has finally failed by trying to push into interface `IEnumerable<out T>` and rewrite all `Linq` methods.

Issue described here as well: https://what.thedailywtf.com/topic/22986/async-await-with-ienumerable-in-c

I'm not sure what exactly the resolution should be, but this problem needs a real resolution. Random deadlocking by thread pool exhaustion is not appropriate.

It really feels like the solution ought to be a way to actually say "run this async method on this thread".

I have constructed a demonstration that deliberately crushes the threadpool size to 1 to make reproduction trivial.

**Comment by stephentoub** [comment]
I'm unable to determine at this point what this issue is tracking.

From the comments it sounds like the previously posted repro had a flaw.  Is there a new repro that shows exactly what bug is being highlighted?

Or is this just a general "the thread pool should handle sync-over-async better" issue?

**Comment by joshudson** [comment]
The issue is async -> sync -> async can deadlock.

We ended up "fixing" this by writing a replacement for HttpClient using a synchronous streaming model.

**Comment by stephentoub** [comment]
> The issue is async -> sync -> async can deadlock.

Right, that's what I meant by  "a general "the thread pool should handle sync-over-async better" issue".  It's known that the thread pool's current thread injection heuristics don't always do well with significant blocking.  There are other issues, like https://github.com/dotnet/runtime/issues/7657, about that.

As for HttpClient, there are proposals for synchronous APIs here:
https://github.com/dotnet/runtime/issues/32125

Thanks.
