### ISSUE TITLE
Add overload to int? Sum(this IEnumerable<int?>) to allow null returning (and other Sum functions)

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#29508]
With the implementation of the  overload of IEnumerable.Sum that takes a list of nullable int as parameter and returns a nullable int, a null value is actually never returned.

        public static int? Sum(this IEnumerable<int?> source)
        {
            if (source == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
            }

            int sum = 0;
            checked
            {
                foreach (int? v in source)
                {
                    if (v != null)
                    {
                        sum += v.GetValueOrDefault();
                    }
                }
            }

            return sum;
        }

The same problem exists in other overloads taking nullable  parameters.

**Comment by eiriktsarpalis** [comment]
I don't think the value provided by the proposed overload justifies the added API complexity. I'm going to close this issue, but feel free to reopen if you would like this conversation to continue. Thank you for your contribution!
