### ISSUE TITLE
Will JsonSerializer support parsing to existing object?

### ISSUE THREAD

**Issue by gongdo** [dotnet/runtime#29538]
When I need to call deserializer for the same type inside a long running loop, I prefer to overwrite to existing instance rather than create a new instance every time.

`Json.NET` has a feature for it: `JsonConvert.PopulateObject(string, object)`
(I think the target should be the first argument of it, but it doesn't matter.)

For `System.Text.Json`, its usage might look like this:
```CSharp
using System.Text.Json
var tmp = new MyClass();
JsonSerializer.ParseTo(ref tmp, "{\"some\":\"json\"}");
```

I found an option `ClassMaterializerStrategy` that might do similar thing, but it was an internal option. Even if it was not an internal, I believe a direct method like `ParseTo` would be better.

**Comment by mwadams** [comment]
@reazhaq - this is exactly the scenario we have - I have a custom `JsonConverter<object>` which examines a type discriminator to instantiate the relevant type.

It then wants to populate the contents of the type it has instantiated, using the default behaviour, otherwise you get into an infinite recursion.

It would be nice to be able to do a `JsonDocument.ParseValue()` over the reader so I could inspect the document and pull out the discriminator without having to handle the reading ahead myself [we find it generally unsafe to assume that the discriminator is first property on the object], create a Utf8JsonReader _over that document_ to avoid allocating extra buffers, and pass it on to the default `ObjectConverter<T>` (now we know what `T` is) to be populated.

**Comment by BrunoBlanes** [comment]
With C#8 nullable types, we get a warning for not initializing a non-nullable list, but `System.Text.Json` doesn't make use of initialized lists and so we can't and therefore can't dismiss the warning. Am I doing something wrong or is that just the way it is for now?

**Comment by rwkarg** [comment]
> With C#8 nullable types, we get a warning for not initializing a non-nullable list, but `System.Text.Json` doesn't make use of initialized lists and so we can't and therefore can't dismiss the warning. Am I doing something wrong or is that just the way it is for now?

Our workaround for DTOs is to create an empty constructor (if there isn't one already) and wrap it in:
```
#nullable disable
public MyClass() {}
#nullable restore
```

This will stop the analysis for uninitialized properties. We only use this for DTOs where we have knowledge that something in the system stack has already ensured that the property won't be null when deserialized.

The other option is to place the `#nullable` directives around each property that is marked as non-nullable but isn't initialized. This is more specific, but also more verbose.

**Comment by BrunoBlanes** [comment]
Yes, I figured suppressing the warning would be a workaround, but was kind of hopping that it wouldn't be necessary. I wish `System.Text.Json` would make use of initialized lists, that way I didn't have to deal with it in this way.

**Comment by layomia** [comment]
Linking https://github.com/dotnet/runtime/issues/30258 which is concerned with an option to reuse rather than replace object properties on deserialization. They should be considered together during design and implementation.

**Comment by eiriktsarpalis** [comment]
Triage: we want to eventually add this feature but unfortunately it won't fit our schedule for .NET 6, moving to future.

**Comment by olivermue** [comment]
By the way, even Microsoft itself needs a `Populate()` method in some places: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/57861dc4aea6c33908838915c97fc02105b6e788/src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs#L112-L114

**Comment by kierenj** [comment]
This would be fantastic for reducing memory allocations in my app; I want to re-use target objects to avoid allocaitons / GC pauses. Unless there's another route to achieving this?

**Comment by BreyerW** [comment]
@kierenj  Once public `ContractResolver` is available and u port this snippet to STJ
 
```csharp

using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace Sharp.Serializer
{
	public class ReferenceConverter : JsonConverter
	{
		public override bool CanWrite => false;
		public override bool CanConvert(Type typeToConvert)
		{
			return (typeToConvert.IsClass || typeToConvert.IsInterface) && typeToConvert != typeof(string);
		}
		public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
		{
			reader.Read();
			if (reader.TokenType is JsonToken.StartObject)
				reader.Read();
			var id = string.Empty;
			var valueId = string.Empty;
			if (reader.Value is string and "$id" or "$ref")
			{
				id = reader.Value as string;
				reader.Read();
				valueId = reader.Value as string;
				reader.Read();
			}
			if (reader.Value is string and "$type")
			{
				reader.Read();
				reader.Read();
			}
			var contract = serializer.ContractResolver.ResolveContract(objectType) as JsonObjectContract;
			var target = serializer.ReferenceResolver.ResolveReference(null, valueId) ?? RuntimeHelpers.GetUninitializedObject(objectType);
			if (id is "$ref")
			{
				reader.Read();
				return target;
			}
			else
				serializer.ReferenceResolver.AddReference(null, valueId, target);

			while (reader.TokenType is not JsonToken.EndObject)
			{
				var propName = (string)reader.Value;
				reader.Read();
				var p = contract.Properties.GetClosestMatchProperty(propName);
				if (p.Ignored)
				{
					reader.Skip();
					reader.Read();
				}
				else
				{
					p.ValueProvider.SetValue(target, serializer.Deserialize(reader, p.PropertyType));
					//while (depth != reader.Depth && reader.TokenType is not JsonToken.PropertyName)
					if (reader.TokenType is not JsonToken.PropertyName)
						reader.Read();
				}
			}
			return target;
		}

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
		{
			throw new NotImplementedException();
		}
	}
}

```

it should be possible to achieve deep `PopulateObject` effect using standard Serialize/Deserialize methods. Few notes: this snippet is minimal it doesnt support any knobs nor polymorphism (should be kinda easy to add tho if you change `if (reader.Value is string and "$type")` and below). Keep this converter as last in your chain if you have any custom. Also to have deep `PopulateObject` all the way you have to make sure custom converters for reference objects also have customized `ReferenceHandler` behaviour like in this snippet (calling `ResolveReference` before `AddReference` on deserialize which is different from default)

**Comment by TonyValenti** [comment]
Is there a .NET6 / .NET7 way to deserialize JSON onto an existing object?  I'm hoping to be able to provide a JSON snippet that overrides properties on an existing object.

**Comment by BreyerW** [comment]
@TonyValenti built-in no neither on 6 or 7 but with public contract in NET 7 (should be available in next preview or right now if ur willing to build BCL yourself from this repo) you can build it almost trivially yourself (unless you want to support all the knobs in which case it becomes cumbersome and time-consuming but not particularly difficult).

**Comment by eiriktsarpalis** [comment]
@RicoSuter that's a cool idea, however one issue I'm seeing is that you're creating a fresh `JsonSerializerOptions` instance on every serialization. This would result in metadata needing to be recomputed every time, killing serialization performance. I've adapted your example somewhat so that the same metadata can be used across serializations:
```C#
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

var value = new MyPoco();
JsonSerializerExt.PopulateObject("""{"Value":42}""", typeof(MyPoco), value);
Console.Write(value.Value); // 42

public class MyPoco
{
    public int Value { get; set; }
}

public static class JsonSerializerExt
{
    // Dynamically attach a JsonSerializerOptions copy that is configured using PopulateTypeInfoResolver
    private readonly static ConditionalWeakTable<JsonSerializerOptions, JsonSerializerOptions> s_populateMap = new();

    public static void PopulateObject(string json, Type returnType, object destination, JsonSerializerOptions? options = null)
    {
        options = GetOptionsWithPopulateResolver(options);
        PopulateTypeInfoResolver.t_populateObject = destination;
        try
        {
            object? result = JsonSerializer.Deserialize(json, returnType, options);
            Debug.Assert(ReferenceEquals(result, destination));
        }
        finally
        {
            PopulateTypeInfoResolver.t_populateObject = null;
        }
    }

    private static JsonSerializerOptions GetOptionsWithPopulateResolver(JsonSerializerOptions? options)
    {
        options ??= JsonSerializerOptions.Default;

        if (!s_populateMap.TryGetValue(options, out JsonSerializerOptions? populateResolverOptions))
        {
            JsonSerializer.Serialize(value: 0, options); // Force a serialization to mark options as read-only
            Debug.Assert(options.TypeInfoResolver != null);

            populateResolverOptions = new JsonSerializerOptions(options)
            {
                TypeInfoResolver = new PopulateTypeInfoResolver(options.TypeInfoResolver)
            };

            s_populateMap.TryAdd(options, populateResolverOptions);
        }

        Debug.Assert(options.TypeInfoResolver is PopulateTypeInfoResolver);
        return populateResolverOptions;
    }

    private class PopulateTypeInfoResolver : IJsonTypeInfoResolver
    {
        private readonly IJsonTypeInfoResolver _jsonTypeInfoResolver;
        [ThreadStatic]
        internal static object? t_populateObject;

        public PopulateTypeInfoResolver(IJsonTypeInfoResolver jsonTypeInfoResolver)
        {
            _jsonTypeInfoResolver = jsonTypeInfoResolver;
        }

        public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)
        {
            var typeInfo = _jsonTypeInfoResolver.GetTypeInfo(type, options);
            if (typeInfo != null && typeInfo.Kind != JsonTypeInfoKind.None)
            {
                Func<object>? defaultCreateObjectDelegate = typeInfo.CreateObject;
                typeInfo.CreateObject = () =>
                {
                    object? result = t_populateObject;
                    if (result != null)
                    {
                        // clean up to prevent reuse in recursive scenaria
                        t_populateObject = null;
                    }
                    else
                    {
                        // fall back to the default delegate
                        result = defaultCreateObjectDelegate?.Invoke();
                    }

                    return result!;
                };
            }

            return typeInfo;
        }
    }
}
```

**Comment by maxreb** [comment]
Very nice! I created a Benchmark for this to compare it with Newtonsoft. Its faster and uses far less memory. I also created a generic method `PopulateObject<T>` to have exact the same overload as Newtonsoft has (and its even a little bit faster).

The Benchmark Results:

> |                                            Method |     Mean |   Error |   StdDev |   Gen0 | Allocated |
> |-------------------------------------------------- |---------:|--------:|---------:|-------:|----------:|
> |              PopulateClass_FromInt_WithNewtonsoft | 458.7 ns | 9.16 ns | 16.52 ns | 0.3152 |    2640 B |
> |          PopulateClass_FromInt_WithSystemTextJson | 318.4 ns | 1.58 ns |  1.40 ns | 0.0219 |     184 B |
> | PopulateClass_FromInt_WithSystemTextJson_AsObject | 326.4 ns | 1.03 ns |  0.91 ns | 0.0219 |     184 B |

The code gist: https://gist.github.com/maxreb/947dd57b159d82aa75ac6943d66679e5

**Comment by eiriktsarpalis** [comment]
Nice! I should point out that this technique would only work with the synchronous serialization methods, thread statics stop working when async methods are being used and you might need to use something like `AsyncLocal<T>` instead.

**Comment by RicoSuter** [comment]
My main gripe with this is that STJ should expose this natively - it must have a internal populate method where they actually populate the object created with CreateObject, no?

**Comment by eiriktsarpalis** [comment]
There is work happening in this space currently tracked by #78556. I think it might make sense to close this issue in favor of the other one since its proposal already includes `Populate` methods.
