### ISSUE TITLE
System.Buffers nuget package 4.5.0 miss full framework package

### ISSUE THREAD

**Issue by alkampfergit** [dotnet/runtime#29544]
Hi, I got a little problem with latest version of system buffers:

I have a project targeting full framework (ex 4.6.1) and if I reference nuget package system.buffers 4.5.0, even if the package tells me that there is the 4.5 version, I got netstandard version referenced.

This is what I see in nuget
![image](https://user-images.githubusercontent.com/358545/57681509-1edfc500-7630-11e9-97cb-fdce2f8edfa0.png)

This is the reference to the project after I added reference to the packages, as you can see it will reference netstandard

![image](https://user-images.githubusercontent.com/358545/57681556-374fdf80-7630-11e9-82d0-b680c9b10948.png)

Actually uncompressing the nuget package, full framework version is not present.

![image](https://user-images.githubusercontent.com/358545/57681590-45056500-7630-11e9-9d5d-41f5ca808bf2.png)

I'd like it to have correct .NET 4.5 version that does not forces me to have a reference to a netstandard dll.

**Comment by akoeplinger** [comment]
System.Buffers 4.5.1 does have a `lib/net461/System.Buffers.dll` now so this issue should no longer occur.

**Comment by ericstj** [comment]
Indeed this is was fixed in https://github.com/dotnet/corefx/commit/7601f4f6225089ffb291dc7d58293c7bbf5c5d4f
cc @joperezr 
https://github.com/dotnet/runtime/issues/1625
