### ISSUE TITLE
Kerberos impersonation level 'impersonation' instead of 'delegation'.

### ISSUE THREAD

**Issue by pan-theis** [dotnet/runtime#29587]
### Situation
I have a .NET Core CLI 2.2. or 3.0 preview5 client, that sends a REST request to an server, secured with Kerberos. The impersonation level should be "delegation", but only "impersonation" is achieved.

### Problem
I cannot achieve **delegation** level with the .net core client **from .NET Core 2.1 and up**. It works on ** .NET Core 2.0**.

```c#
var handler = new HttpClientHandler();
handler.UseDefaultCredentials = true;

HttpClient httpClient = new HttpClient(handler) { BaseAddress = new Uri(baseUri) };
httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

var response = await httpClient.GetAsync("");

var json = await response.Content.ReadAsStringAsync();

**Comment by stolzitservices-Ben** [comment]
Same problem here. I think there is a relation with https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/iis/www-authentication-authorization/kerberos-double-hop-authentication-edge-chromium (even if edge and .Net Core haven´t something in common). What do you think?
