### ISSUE TITLE
FileSystemInfo doesn't work correctly on Linux when file name encoding is incorrect

### ISSUE THREAD

**Issue by sergei66666** [dotnet/runtime#29586]
Hello.

I copy file via FTP from Windows to Linux. The file has Cyrillic characters. This leads to the fact that file names are displayed incorrectly.

And now the description of the problem.
I'm trying to get a list of all the files in a folder on Linux, and then delete them.

`
var filesToDelete = dir.EnumerateFileSystemInfos("*", SearchOption.AllDirectories).ToList();
FileSystemInfo file = filesToDelete.First();
`

At first, I used `File.Delete(file.FullName)` but without success. And this is logical, because the file name is incorrect.

Then I suggested that the call `file.Delete()` should work. But no.

I checked the `file.Attributes` property and it is -1.

But I expected to see the correct attributes.

My guess is the following.
The file name comes to `FileSystemInfo` as an array of bytes, then it is converted to a string as UTF8, and this string used to request all properties and `Delete` operation. But the string turns out to be incorrect due to the encoding mismatch and all operations failed.

Expected behavior (from my point of view):
Regardless of the encoding of the file name, we can request all attributes and delete the file if necessary.

ps. 
I use russian locale on windows 10.
ubuntu 16.04 with .net core 2.2.2 to run app.

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/runtime/issues/513 is the same issue, closing and tracking there.
