### ISSUE TITLE
One-shot PEM reader

### ISSUE THREAD

**Issue by owlstead** [dotnet/runtime#29588]
I was giving some hints on this [StackOverflow question](https://stackoverflow.com/questions/56144550/loading-an-ecc-private-key-in-net?noredirect=1#comment98936659_56152165) where the idea of a PEM reader / writer for .NET was coming up. Jeremy then posted that if such a reader was available that it would be a nice idea to make it a one-shot, [RFC 7468](https://tools.ietf.org/html/rfc7468) compliant reader using the new `Span<char>` framework.

So I've created a sample implementation / API proposal which performs the parsing of the "lax"  (i.e. permissive). I've used the following additional goals / non-goals:

Goals:

 - no dynamic memory allocation that depends on the size of the input;
 - possibility to skip a description (in front) of the PEM structure;
 - possibility to detect the end of the PEM structure, if present;
 - related: allow for parsing multiple PEM structures from a single `Span`;
 - design in the spirit of other methods that use `Span`;

Non-goals:

 - returning the description in front of the PEM file;
 - detailed error reporting;
 - streaming implementation (requiring state machine or buffering);
 - parsing the base64 inside the header / footer lines (pre/post encapsulation boundaries);
 - support for stricter versions of PEM;
 - return or comparison of the label in the footer.

Niceties:

 - validation of the base64 inside the header / footer lines
 - return the amount of bytes so that a correctly sized buffer can be created in advance for the base64 decryption (yes, implemented).

Parsing the base64 is easily done afterwards with the existing parser, and we may just want to skip the PEM.

Note that I didn't get my Unit testing working for Core 3, so the implementation has not yet received any significant testing. First let me know what you think.

Implementation notes: this implementation searches for the post-encapsulation boundary (footer) before validating the base64. It might be possible to use a state machine instead to create a single pass parser. This adds significant complexity to the parsing though, and searching for a static string should be relatively performant already.

Code in followup comment for now, as I don't know yet where to put it.

-----
(Edited in):
## API Proposal

```C#
namespace System.Security.Cryptography
{
    public static class PemEncoding
    {
        public static bool TryFind(ReadOnlySpan<char> pemData, out PemFields fields) => throw null;
        public static PemFields Find(ReadOnlySpan<char> pemData) => throw null;

        public static int GetEncodedSize(int labelLength, int dataLength) => throw null;
        public static bool TryWrite(ReadOnlySpan<char> label, ReadOnlySpan<byte> data, Span<char> destination, out int charsWritten) => throw null;
        public static char[] Write(ReadOnlySpan<char> label, ReadOnlySpan<byte> data) => throw null;
    }

    public readonly struct PemFields
    {
        internal PemFields(Range label, Range base64data, Range location, int decodedDataLength) => throw null;

        public Range Location { get; }
        public Range Label { get; }
        public Range Base64Data { get; }
        public int DecodedDataLength { get; }
    }
 }
```

**Comment by bartonjs** [comment]
@vcsjones Once we can close down on `DecodedByteSize` vs `DecodedDataLength` I think this is ready to go back through review. (If you actually prefer DecodedByteSize, I'd like to understand why; perhaps I'll come around :smile:)

**Comment by vcsjones** [comment]
@bartonjs I amended my comment here which I think is the most "current" proposal with changes: https://github.com/dotnet/runtime/issues/29588#issuecomment-571784499

>If you actually prefer DecodedByteSize, I'd like to understand why

No preference, I don't think? Maybe I had a stronger opinion a month ago that I am unable to recall. Regardless, `DecodedDataLength` seems sensible.

**Comment by terrajobst** [comment]
* The constructor on `PemFields` isn't public to avoid having to validate well-formedness
* Should `PemFields` implement IEquatable<PemFields>`?

```C#
namespace System.Security.Cryptography
{
    public static class PemEncoding
    {
        public static bool TryFind(ReadOnlySpan<char> pemData, out PemFields fields);
        public static PemFields Find(ReadOnlySpan<char> pemData);

        public static int GetEncodedSize(int labelLength, int dataLength);
        public static bool TryWrite(ReadOnlySpan<char> label, ReadOnlySpan<byte> data, Span<char> destination, out int charsWritten);
        public static char[] Write(ReadOnlySpan<char> label, ReadOnlySpan<byte> data);
    }

    public readonly struct PemFields
    {
        public Range Location { get; }
        public Range Label { get; }
        public Range Base64Data { get; }
        public int DecodedDataLength { get; }
    }
 }
 ```

**Comment by danmosemsft** [comment]
Is anyone interested in implementing this? I would like to get it in 5.0. @owlstead @vcsjones

**Comment by vcsjones** [comment]
@danmosemsft It looks like @owlstead has already invested a good chunk of time in to it, but if @owlstead is unable to or no longer wishes to, I can probably do this next after I wrap up #2406.
