### ISSUE TITLE
Add Span.StackAlloc<T> method

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/runtime#29605]
C# allows to allocate objects in the stack to be used with Span<T> and Memory<T>:
`Span<byte> bytes = stackalloc byte[10];`
I suggest to add a `StackAlloc` method to these classes to allow other languages like VB.NET an F# to do the same:
`dim bytes = Span.StackAlloc(of byte)(10)`

**Comment by stephentoub** [comment]
Closing as a dup of https://github.com/dotnet/runtime/issues/25423.
