### ISSUE TITLE
Add ToList(capacity) and ToDictionary(capacity) to System.Linq.Enumerable

### ISSUE THREAD

**Issue by sonnemaf** [dotnet/runtime#29620]
## Background and Motivation

The class `System.Linq.Enumerable` currently has a [ToList()](https://github.com/dotnet/corefx/blob/143df51926f2ad397fef9c9ca7ede88e2721e801/src/System.Linq/src/System/Linq/ToCollection.cs) and a few [ToDictionary()](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.todictionary?view=net-5.0) methods. I propose to add extra overloads with a capacity parameter to them.

The normal `ToList()` methods will create an empty `List<T>` with the capacity of 4 and then adds all values in the Enumeration to it. This can cause a lot of Array resizes. Especially with large lists this can lead to many [LOH](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap) allocations. To avoid these allocations the new overload of the ToList() method has a extra capacity parameter which is used to create the `List<T>` with this capacity. This can reduce the number of allocations on the LOH if the capacity is chosen wisely. 

## Proposed API

Public API signature diff 

```diff
namespace System.Linq
{
     public static class Enumerable {
+        public static List<TSource> ToList<TSource>(this IEnumerable<TSource> source, int capacity) { }

+        public static Dictionary<TKey, TSource> ToDictionary<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, int capacity) where TKey : notnull;
+        public static Dictionary<TKey, TSource> ToDictionary<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer, int capacity) where TKey : notnull;
+        public static Dictionary<TKey, TElement> ToDictionary<TSource, TKey, TElement>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, int capacity) where TKey : notnull;
+        public static Dictionary<TKey, TElement> ToDictionary<TSource, TKey, TElement>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, IEqualityComparer<TKey>? comparer, int capacity) where TKey : notnull;

     }
}
```

## Usage Example 

```cs
var qry = Enumerable.Range(1, 20_000).Select(n => new Employee(name: "Fons" + n, salary: n));

var list = qry.ToList(20_000);

var dict1 = qry.ToDictionary(emp => emp.Name, 20_000);
var dict2 = qry.ToDictionary(emp => emp.Name, emp => emp.Salary, 20_000);

// do something with the list and the dicts
```
## Risks
Low, extra overloads only

## Benefits
Less memory allocations. The List and Dictionary don't have to be resized.

```cs
IEnumerable<Employee> qry = GetData();

var list = qry.ToList();
```

Suppose a LINQ query "returns" 18000 employees. Each Employee is a 8 bytes pointer (in a 64bit app). The Array would resize 13 times. Twice to use the LOH. The 16K size is only used very shortly can can be garbage collected but it causes fragmentation of the LOH because it is not compacted. The ToList(20000) would not resize at all and not cause a fragmented LOH. 

```
4 -> 8 -> 16 -> 32 -> 64 -> 128 -> 256 -> 512 -> 1K -> 2K -> 4K -> 8K -> 16K (LOH) -> 32K (LOH) 
```

The capacity of this List is 32K. With ToList(20000) you also save ~12K of 8 bytes (32K - ~20K) memory. 

## Other notes
PLINQ implementation is also required

A PR with the proposed changes to `ToList()` is available dotnet/corefx#25545. It is closed. It needed this API Review first.

**Comment by eiriktsarpalis** [comment]
Just so I understand this better, would this expression 
```csharp
Enumerable.Range(1,10).ToArray(20_000);
```
return an array of length 20000? If so, how would I be able to tell how many elements were written to the buffer in more complex LINQ queries?

**Comment by sonnemaf** [comment]
You could have an ToArray with a maxCapacity parameter. This would always return an array in the correct size (length) but without using the resize logic (4,8,16,32, etc). The example code below throws an exception when the capacity is too small. This can also be done differently.

```cs
public static TSource[] ToArray<TSource>(this IEnumerable<TSource> source, int maxCapacity) {
    if (source == null) {
        throw new ArgumentNullException(nameof(source));
    }
    if (maxCapacity < 0) {
        throw new ArgumentOutOfRangeException(nameof(maxCapacity), "Non-negative number required.");
    }
    var a = new TSource[maxCapacity];
    int index = -1;
    foreach (var item in source) {
        if (++index == maxCapacity) {
            throw new ArgumentOutOfRangeException(nameof(maxCapacity), "Insufficient maxCapacity, make it larger");
        }
        a[index] = item;
    }

    return index < maxCapacity ? new ArraySegment<TSource>(a, 0, index + 1).ToArray() : a;
}
```

The length of your array would be 10.

```cs
var l = Enumerable.Range(1,10).ToArray(20_000).Length;
```

I haven't created any benchmark yet. Maybe replacing the ArraySegment with a Span may improve it.

I think the ToList() would benefit more from an extra capacity parameter.

**Comment by En3Tho** [comment]
1) Why it's max capacity for array and start capacity for list?
2) You have to resize array again if you really meant start capacity.
3) If you compare index with count then you should not start with -1. Because index of 0 means 1 item, not 0 items. Just use auto bound check and that's it. 
4) This overload is very tricky as basically it's better to use array pool for large arrays but then if you have to resize the thing like that then for 10 elements it's better to just use new. 
So instead of creating new array of 10 elements maybe it's better to return tuple of (array, count) but again it feels weird as other methods do not return tuples

**Comment by eiriktsarpalis** [comment]
For whatever reason I assumed that the proposed method was `ToArray(int)` as opposed to `ToList(int)`, so the question I posted earlier isn't really applicable here. Apologies for any confusion caused there.

The addition sounds reasonable, however I should point out it can be expressed rather trivially using List directly:
```csharp
public static IEnumerable<T> ToArray<T>(this IEnumerable<T> source, int startCapacity)
{
    var list = new List<T>(startCapacity);
    list.AddRange(source);
    return list.ToArray();
}
```
Given that LINQ prioritizes convenience and simplicity over performance, it might be worth considering if the benefits of adding such an overload outweigh the cost of exposing yet another LINQ method.

**Comment by Joe4evr** [comment]
I've thought about wanting an overload like this a few weeks back. In that case it ended up not mattering since the internal `IListProvider` interface allocates a correctly-sized result, but of note is that I considered to name the parameter `sizeHint` to be more indicative of its behavior. The developer can supply a *hint* of what the expected capacity should be, but if it ends up being wrong, that's going to cost them.

**Comment by eiriktsarpalis** [comment]
I wouldn't mind bringing this for API review. `ToList` and `ToDictionary` seem ok but I don't think we would consider `ToArray` due to concerns already discussed. I'm not sure `ToLookup` makes sense since it's a grouping operation: size can be hard to predict and might not be too meaningful from a performance perspective.

@sonnemaf would you be able to update the original post following the [template from the API review guidelines](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md#steps)?

**Comment by sonnemaf** [comment]
@eiriktsarpalis something like this?

**Comment by Joe4evr** [comment]
Looks alright. Just wondering if it would be more beneficial if the parameter was named something like `capacityHint`, since I could expect the implementations don't necessarily have to respect the supplied value in certain cases, such as if the `IEnumerable` is the internal `IIListProvider` which already carries its size.

**Comment by sonnemaf** [comment]
Would a Fill() method like this one be an alternative for a ToArray(capacity);

```cs
static class Program {

    static void Main(string[] args) {

        var l = new List<Employee> {
            new Employee("Fons", 2000),
            new Employee("Jim", 4000),
            new Employee("Ellen", 3000),
            ...
        };

        var array = ArrayPool<Employee>.Shared.Rent(200);
        try {

            int length = qry.Fill(array);

            for (int i = 0; i < length; i++) {
                Console.WriteLine(array[i]);
            }
        } finally {
            ArrayPool<Employee>.Shared.Return(array);
        }
    }

    public static int Fill<TSource>(this IEnumerable<TSource> source, Span<TSource> destination) {
        int index = 0;
        foreach (var item in source) {
            if (index >= destination.Length) {
                throw new ArgumentOutOfRangeException(nameof(destination), "Span is too small");
            }
            destination[index++] = item;
        }
        return index;
    }
}
```

**Comment by eiriktsarpalis** [comment]
> @eiriktsarpalis something like this?

Thanks for that. I hadn't anticipated that `ToDictionary` would result in so many new overloads, I'm having second thoughts about it.

> Would a Fill() method like this one be an alternative for a ToArray(capacity);

I don't think we should be adding overloads that take span, that type is typically reserved for more performance conscious APIs.

**Comment by sonnemaf** [comment]
@eiriktsarpalis  The use of span in the Fill() method allows me to use any type of array: stackallocated, unmanged and normal (including pooled) ones.

**Comment by NetMage** [comment]
> Thanks for that. I hadn't anticipated that `ToDictionary` would result in so many new overloads, I'm having second thoughts about it.

It seems the current `ToDictionary` passes a `0` for `capacity` when it can't get it quickly - would just adding an optional parameter with a default value of `0` be just as good?

I'd also note that `Enumerable.ToDictionary` already has `ICollection`, `List` (would this be better `IList`?), and `T[]` specializations to get a quick capacity. `Enumerable.ToList` would need some modification to take an optional `capacity` parameter, but it already has an `IIListProvider` and `ICollection` specialization.

**Comment by jjanuszkiewicz** [comment]
I wanted to propose literally the same API change, but I've found this one. I just want to express my support for the change, it will be a very useful API.

**Comment by spydacarnage** [comment]
I also have arrived here with the express intention of raising the exact same change, so adding more support instead :)

**Comment by YairHalberstadt** [comment]
```csharp
var qry = Enumerable.Range(1, 20_000).Select(n => new Employee(name: "Fons" + n, salary: n));

var list = qry.ToList(20_000);
```

It seems to me that this could be achieved for free by making Rangeiterator implement [IPartition](https://source.dot.net/#System.Linq/System/Linq/IPartition.cs,7dbde8276a8c7002,references).

In general, most cases where the user knows enough to be able to make this hint accurately, could be optimized by Linq automatically.

**Comment by YairHalberstadt** [comment]
Wait, it already does: https://source.dot.net/#System.Linq/System/Linq/Range.SpeedOpt.cs,635de868c5dbb1f5

As such in the given example, there wouldn't be any benefit at all.

**Comment by YairHalberstadt** [comment]
To be clear, there's 2 cases here:

1: You know the exact size
If so then in most cases Linq will also know the exact size.
2: You can guess about what the size will be
Here the benefit is much smaller - the cost of the collecting the temporary arrays is much greater for the larger arrays than smaller ones. So if your suggested capacity is one size too small, you'll lose most of the potential benefit. And if your suggested size is 1 too large, then you're paying a significant overhead.

Now there's certainly scenarios where this could be useful - for example, I might have a source containing n elements, filter out nulls, and know that at most 1% of the elements will be null. But for such cases this API is pretty easy to write yourself.

The risk is that people see this overload, assume that they should just guestimate the capacity and doing so will improve performance, regularly get it wildly wrong (or the number changes over time), and end up with both worse performance, and a whole load of magic constants in their code.

**Comment by eiriktsarpalis** [comment]
Related to #45679 and #24900. On second thought I don't believe that the proposed method should be added to LINQ. I think though that there might be an opportunity for optimizing the [`ToDictionary` methods](https://github.com/dotnet/runtime/blob/759057fea4ddadc10d068a74ec7f3fc55d561ab8/src/libraries/System.Linq/src/System/Linq/ToCollection.cs#L48) e.g. by pre-sizing the dictionary via the new `TryGetNonEnumeratedCount` method.
