### ISSUE TITLE
ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails test failure

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#29642]
I just saw this test failed in one CI run:

> Assert.IsAssignableFrom() Failure\nExpected: typeof(System.Security.Authentication.AuthenticationException)\nActual: typeof(System.TimeoutException)

Stack Trace
```
at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols serverProtocol, SslProtocols clientProtocol, Type expectedException) in /_/src/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=198444&view=ms.vss-test-web.build-test-results-tab&runId=4812722&resultId=483559&paneView=debug

Failed on: https://github.com/dotnet/corefx/pull/37888
cc: @ViktorHofer @stephentoub @wfurt

**Comment by karelz** [comment]
Fixed by PR https://github.com/dotnet/runtime/pull/35549#issuecomment-622100060

**Comment by wfurt** [comment]
It failed again. It is curious it timed out after 1.3s (in Debug OSX build)

``` 
     <test name="System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls12, clientProtocol: Tls11, expectedException: typeof(System.Security.Authentication.AuthenticationException))" type="System.Net.Security.Tests.ServerAsyncAuthenticateTest" method="ServerAsyncAuthenticate_MismatchProtocols_Fails" time="1.1337415" result="Fail">
        <failure exception-type="Xunit.Sdk.IsAssignableFromException">
          <message><![CDATA[Assert.IsAssignableFrom() Failure\nExpected: typeof(System.Security.Authentication.AuthenticationException)\nActual:   typeof(System.TimeoutException)]]></message>
          <stack-trace><![CDATA[   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols serverProtocol, SslProtocols clientProtocol, Type expectedException) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 62
--- End of stack trace from previous location ---]]></stack-trace>
        </failure>
      </test>
```

**Comment by safern** [comment]
Adding builds impacted by this. I just saw instances of this in rolling builds and PRs:

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#635584](https://dev.azure.com/dnceng/public/_build/results?buildId=635584)|#35566|1|
|[#635689](https://dev.azure.com/dnceng/public/_build/results?buildId=635689)|#36047|1|
|[#635943](https://dev.azure.com/dnceng/public/_build/results?buildId=635943)|#35366|1|
|[#636029](https://dev.azure.com/dnceng/public/_build/results?buildId=636029)|#36082|1|
|[#636084](https://dev.azure.com/dnceng/public/_build/results?buildId=636084)|#36088|1|
|[#636157](https://dev.azure.com/dnceng/public/_build/results?buildId=636157)|#36098|1|
|[#636424](https://dev.azure.com/dnceng/public/_build/results?buildId=636424)|#36104|1|
|[#636769](https://dev.azure.com/dnceng/public/_build/results?buildId=636769)|#35366|1|
|[#636778](https://dev.azure.com/dnceng/public/_build/results?buildId=636778)|Rolling|1|
|[#636800](https://dev.azure.com/dnceng/public/_build/results?buildId=636800)|#35925|1|
|[#636821](https://dev.azure.com/dnceng/public/_build/results?buildId=636821)|#35936|1|
### Configurations
- net5.0-Linux-Debug-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open
- net5.0-Linux-Debug-x64-CoreCLR_release-Ubuntu.1604.Amd64.Open
- net5.0-Linux-Debug-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open
- net5.0-Linux-Release-x64-CoreCLR_release-(Fedora.29.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-29-helix-a12566d-20191210224553
- net5.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open
- net5.0-OSX-Debug-x64-CoreCLR_release-OSX.1013.Amd64.Open
- net5.0-Windows_NT-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#635584](https://dev.azure.com/dnceng/public/_build/results?buildId=635584)|#35566|[console.log](https://helix.dot.net/api/2019-06-17/jobs/d308fa3d-27a5-4fc9-bda3-286e56390741/workitems/System.Net.Security.Tests/files/console.90cca0ca.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/d308fa3d-27a5-4fc9-bda3-286e56390741/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35566-merge-d308fa3d27a54fc9bd/System.Net.Security.Tests/4db0af30-492f-456a-86e9-0e435f5e1309.log?sv=2019-02-02&se=2020-05-27T23%3A35%3A10Z&sr=c&sp=rl&sig=sp02eIfVwd9ZGlR8m44Tu6fHURxF9zEpEbLfgDTo2Gg%3D)|
|[#635689](https://dev.azure.com/dnceng/public/_build/results?buildId=635689)|#36047|[console.log](https://helix.dot.net/api/2019-06-17/jobs/59089df3-0bc8-454d-b0c8-473850cded1a/workitems/System.Net.Security.Tests/files/console.77882e5d.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/59089df3-0bc8-454d-b0c8-473850cded1a/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-36047-merge-59089df30bc8454db0/System.Net.Security.Tests/66e45644-a3b1-4784-b4ec-93a55fff8467.log?sv=2019-02-02&se=2020-05-27T23%3A02%3A46Z&sr=c&sp=rl&sig=n9kaOfyjD4l6gdeSOpBn%2FzncezGkXyeFtNHYPS00pPY%3D)|
|[#635943](https://dev.azure.com/dnceng/public/_build/results?buildId=635943)|#35366|[console.log](https://helix.dot.net/api/2019-06-17/jobs/a653bfc2-e7e4-42b5-89f8-66726cc69b40/workitems/System.Net.Security.Tests/files/console.fc098c57.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/a653bfc2-e7e4-42b5-89f8-66726cc69b40/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35366-merge-a653bfc2e7e442b589/System.Net.Security.Tests/a80d26d5-49a4-4a52-af86-7222e13f2ca9.log?sv=2019-02-02&se=2020-05-28T01%3A50%3A39Z&sr=c&sp=rl&sig=LrjvXtj%2F9ojvrNA3lsWVpe%2F7doqSBc9esuPNq%2F2vbYY%3D)|
|[#636029](https://dev.azure.com/dnceng/public/_build/results?buildId=636029)|#36082|[console.log](https://helix.dot.net/api/2019-06-17/jobs/062ccb37-bd99-4d70-885f-d5a0798c70dc/workitems/System.Net.Security.Tests/files/console.6136b4fc.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/062ccb37-bd99-4d70-885f-d5a0798c70dc/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-36082-merge-062ccb37bd994d7088/System.Net.Security.Tests/4685ad4c-fa0b-46c9-a219-19b3ff47d2df.log?sv=2019-02-02&se=2020-05-28T02%3A45%3A34Z&sr=c&sp=rl&sig=znMERBrAvQ2PpiXgBc14cGL3sa2M1Pqd3btVO%2BtJqxc%3D)|
|[#636084](https://dev.azure.com/dnceng/public/_build/results?buildId=636084)|#36088|[console.log](https://helix.dot.net/api/2019-06-17/jobs/5403f31b-09bc-4e60-8e48-62ab5a420a65/workitems/System.Net.Security.Tests/files/console.ca850667.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/5403f31b-09bc-4e60-8e48-62ab5a420a65/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-36088-merge-5403f31b09bc4e608e/System.Net.Security.Tests/b3ead049-4fe4-4b4c-8691-7cefb664b622.log?sv=2019-02-02&se=2020-05-28T03%3A50%3A03Z&sr=c&sp=rl&sig=w6ZQBpeeP88f4U2%2Fix3ldQLOSjTb1lAF0cCGC3RNRaQ%3D)|
|[#636157](https://dev.azure.com/dnceng/public/_build/results?buildId=636157)|#36098|[console.log](https://helix.dot.net/api/2019-06-17/jobs/dde0a152-e64b-426d-87eb-0ef7b03d6276/workitems/System.Net.Security.Tests/files/console.101f87af.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/dde0a152-e64b-426d-87eb-0ef7b03d6276/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-36098-merge-dde0a152e64b426d87/System.Net.Security.Tests/1e81ef69-c098-433f-9496-bad22c0b87c5.log?sv=2019-02-02&se=2020-05-28T04%3A22%3A28Z&sr=c&sp=rl&sig=p26wXxbSW4LF0mw6qD7uysd75B%2Bj8b7WsD9s0a27%2Fjc%3D)|
|[#636424](https://dev.azure.com/dnceng/public/_build/results?buildId=636424)|#36104|[console.log](https://helix.dot.net/api/2019-06-17/jobs/49bfe14f-8b66-40bd-bb05-97321badf79e/workitems/System.Net.Security.Tests/files/console.f1b62bbc.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/49bfe14f-8b66-40bd-bb05-97321badf79e/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-36104-merge-49bfe14f8b6640bdbb/System.Net.Security.Tests/08656400-571c-44ac-b566-4206ac280d02.log?sv=2019-02-02&se=2020-05-28T09%3A28%3A36Z&sr=c&sp=rl&sig=m0b9tg8LiiHjzGvIXddNG93Bkj6X4fQLZeQb28mJMwE%3D)|
|[#636769](https://dev.azure.com/dnceng/public/_build/results?buildId=636769)|#35366|[console.log](https://helix.dot.net/api/2019-06-17/jobs/b048bac5-1234-4cd2-8efa-ea8a272de45a/workitems/System.Net.Security.Tests/files/console.cfe28bd5.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/b048bac5-1234-4cd2-8efa-ea8a272de45a/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35366-merge-b048bac512344cd28e/System.Net.Security.Tests/64a6bcb3-c726-4985-ba11-7769da7d398c.log?sv=2019-02-02&se=2020-05-28T15%3A14%3A17Z&sr=c&sp=rl&sig=1h0xrkGmVhYDtjgtbPgrCL4sS6YFKdsx5B0c8gspaWg%3D)|
|[#636778](https://dev.azure.com/dnceng/public/_build/results?buildId=636778)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/90d26640-e26b-4cf6-b637-4c78d20c6223/workitems/System.Net.Security.Tests/files/console.3faca452.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/90d26640-e26b-4cf6-b637-4c78d20c6223/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-90d26640e26b4cf6b6/System.Net.Security.Tests/23e3ed42-b19c-42a0-a770-4e6d8c89cdce.log?sv=2019-02-02&se=2020-05-28T15%3A49%3A18Z&sr=c&sp=rl&sig=6XaQ43XEQGT4I626aBdaZqkl5ThnjbDuyPqQj6wug8k%3D)|
|[#636800](https://dev.azure.com/dnceng/public/_build/results?buildId=636800)|#35925|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4ef239b6-500d-48a5-a7d9-dc4e6b587fe8/workitems/System.Net.Security.Tests/files/console.21d98c41.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/4ef239b6-500d-48a5-a7d9-dc4e6b587fe8/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35925-merge-4ef239b6500d48a5a7/System.Net.Security.Tests/d5e90234-b503-4d61-8f2d-1c72bfa19cb7.log?sv=2019-02-02&se=2020-05-28T15%3A41%3A39Z&sr=c&sp=rl&sig=Q8lYywdqAbtmG8n%2B%2FncXsc38loIDJmDHXkzP5II8Stw%3D)|
|[#636821](https://dev.azure.com/dnceng/public/_build/results?buildId=636821)|#35936|[console.log](https://helix.dot.net/api/2019-06-17/jobs/0a0ad37a-1fc8-4ee5-8da1-19620f79a6ee/workitems/System.Net.Security.Tests/files/console.35e600d6.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/0a0ad37a-1fc8-4ee5-8da1-19620f79a6ee/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35936-merge-0a0ad37a1fc84ee58d/System.Net.Security.Tests/41bf2b23-0512-445f-9c66-1964c46f566a.log?sv=2019-02-02&se=2020-05-28T16%3A22%3A16Z&sr=c&sp=rl&sig=a1XNAfWtUGKaPixsGGv7tjXzp4WDh55vvXF62uQM%2FCA%3D)|
