### ISSUE TITLE
GetSchema Async

### ISSUE THREAD

**Issue by tanbchr** [dotnet/runtime#29658]
I was curious to know why there is not an `async` version of the `GetSchema`?

Basically, for each collection information name, it is doing queries to retrieve the metadata.

I know that we can query directly the database to retrieve the same information. However, we are using multiple ADO.NET providers and we are not depending on the implementation of the `GetSchema` function nor on the type of the connection.

Getting the metadata is really heavy and requires a lot of time to fetch everything. By having an asynchronous version, we can free the current thread.

**Comment by roji** [comment]
Duplicate of #38028

**Comment by roji** [comment]
@tanbchr FYI this will probably be going in for .NET 5.0.

**Comment by bilalchraibi** [comment]
@roji  This is great news!
