### ISSUE TITLE
File allocation inconsistency between Windows and Linux and sparse allocations

### ISSUE THREAD

**Issue by andrewaggb** [dotnet/runtime#29666]
My basic problem.  I want to pre-allocate files (reserving space) ahead of time so that it's not possible to run out of space at a later time.  

Sample Code:
```c#
using (var fs = File.Open(fileName, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None)) 
{
       fs.SetLength(1024L * 1024L * 1024L * 2);
}
```

On my ntfs windows 10 machine this creates a 2gb file and decreases the free space reported on the drive by 2gb.

On my ext4 linux machine with Centos 6.10, the file was created and it shows the correct length but the free space did not decrease.  I'm assuming this is due to sparse allocation.  I can re-rest on Centos 7 and Ubuntu 18 if necessary.

Is windows sparsely allocating the file as well and just reporting the free space differently or is windows fully allocating and linux sparsely allocating?

If I create the file using 'fallocate -l 2G 2gbfile' on linux I get the same apparent behavior as windows ntfs in that I quickly allocate a large file and free space decreases.  That's the behavior I want and it's consistent (in my opinion) with the windows behavior.  That said, I suspect other people may want to be able to sparsely allocate files.

**Comment by carlossanlop** [comment]
Triage:
This requires a new API Proposal for a new set of flags likely in FileOptions, making sure to be mindful of avoiding conflicts with existing (unexposed) Windows flags:
https://source.dot.net/#System.Private.CoreLib/FileOptions.cs,11

 @andrewaggb would you be interested in writing the API Proposal? See https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

**Comment by andrewaggb** [comment]
@carlossanlop 

Sorry for the late response.  I am not able to write a proposal at this time.

**Comment by adamsitnik** [comment]
In #51111 we have introduced a set of new APIs that allow to specify the file allocation size up-front.  Example:

```cs
using (var fs = File.Open(fileName, new FileStreamOptions { Mode = FileMode.CreateNew, Access = FileAccess.ReadWrite, Share = FileShare.None, PreallocationSize = 1024L * 1024L * 1024L * 2 })) 
{
}
```


For syscalls implementation details please refer to https://github.com/dotnet/runtime/pull/51111#issue-613590592

Since the new API solves the problem and we don't intend to change the behavior of `FileStream.SetLength`, I am closing the  issue
