### ISSUE TITLE
build-native.cmd expects "Program Files (x86)" to exist when running it in a 32-bit OS

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#29716]
I have two identical Windows 7 VMs where I configured and installed everything so I could run corefx unit tests.

I followed the instructions on both VMs at the same time. I am able to successfully build x64, but x86 fails to build.

With the help of @wtgodbe , we found that build-native.cmd expects the "Program Files (x86)" folder to exist so it can find the VS installation. But since it's not found, build fails.

Should we be checking for the architecture and based on that, decide if we want to look for "Program Files" (the only folder that exists in x86) or "Program Files (x86)" (which only exists in x64)?

This is the line:

https://github.com/dotnet/corefx/blob/02f649e60f3a8ea0b947ea0eaf64f2fa3c287816/src/Native/build-native.cmd#L52

I made sure to run:

`build.cmd -arch x86`

This is the error I get:

```
EXEC: error : Visual Studio 2017 or 2019 required [C:\repos\corefx\src\Native\build-native.proj]
       Please see https://github.com/dotnet/corefx/tree/master/Documentation for build instructions.
C:\repos\corefx\src\Native\build-native.proj(50,5): error MSB3073: The command ""C:\repos\corefx\src\Native\build-native.cmd" x86 Debug Windows_NT outconfig netcore-app-Windows_NT-Debug-x86" existed with code 1.
Build FAILED.
```

After modifying that line in build-native.cmd, I was able to go past the check for the VS installation and build (although it was an unsuccessful build, but for different reasons unrelated to this).

**Comment by ViktorHofer** [comment]
@carlossanlop can you please try this again since we changed the relevant code paths since you filed this issue. Thanks.
