### ISSUE TITLE
Add JSONPath to the exception thrown by JsonDocument while parsing invalid JSON

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#29715]
As an extension to https://github.com/dotnet/corefx/issues/37768, the JsonDocument class should support setting the `Path` property on `JsonReaderException`.

In addition, once this is complete, the serializer should re-throw `JsonReaderException` (as it does today) but now with the `Path` property pre-pended with the results from `JsonReaderException` to include the full Path of the serializer + JsonDocument.

See also PR https://github.com/dotnet/corefx/pull/37938

**Comment by layomia** [comment]
Triage: action item is to remove this test and close this issue.

https://github.com/dotnet/runtime/blob/d4b06b1a9e3c56e343c42efad2211c04c196a0cf/src/libraries/System.Text.Json/tests/Serialization/ExceptionTests.cs#L366-L380

**Comment by anreton** [comment]
It would be great if it was implemented.

For example, there is JsonConverter:
```csharp
public class Options
{
	public Options(bool a, bool b, bool c)
	{
		this.A = a;
		this.B = b;
		this.C = c;
	}

	public bool A { get; }
	public bool B { get; }
	public bool C { get; }
}

public class OptionsJsonConverter : JsonConverter<Options>
{
	public override Options Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		using var jsonDocument = JsonDocument.ParseValue(ref reader);
		var rootElement = jsonDocument.RootElement;

		var a = rootElement.GetProperty("A").GetBoolean();
		var b = rootElement.GetProperty("B").GetBoolean();
		var c = rootElement.GetProperty("C").GetBoolean();

		return new Options(a, b, c);
	}

	public override void Write(Utf8JsonWriter writer, Options value, JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		{
			writer.WriteBoolean(nameof(value.A), value.A);
			writer.WriteBoolean(nameof(value.B), value.B);
			writer.WriteBoolean(nameof(value.C), value.C);
		}
		writer.WriteEndObject();
	}
}
```

We are trying to deserialize:
```csharp
const string json = @"""A"": 42";

var jsonOptions = new JsonSerializerOptions();
jsonOptions.Converters.Add(new OptionsJsonConverter());

var options = JsonSerializer.Deserialize<Options>(json, jsonOptions);
```

and get:
>System.InvalidOperationException: 'The requested operation requires an element of type 'Object', but the target element has type 'String'.'

It would be great to get the path and line number.
