### ISSUE TITLE
NegotiatedCipherSuiteTest timeout test failures

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#29720]
System.Net.Security.Tests.NegotiatedCipherSuiteTest had a number of timeout exceptions (Alpine run):

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38039~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190530.55/workItem/System.Net.Security.Tests

NegotiatedCipherSuite_SslProtocolIsLowerThanTls13_ShouldMatchTheProtocol(protocol: Tls)
NegotiatedCipherSuite_SslProtocolIsLowerThanTls13_ShouldMatchTheProtocol(protocol: Tls11)
NegotiatedCipherSuite_SslProtocolIsLowerThanTls13_ShouldMatchTheProtocol(protocol: Tls12)
Tls13IsSupported_GetValue_ReturnsTrue

All failed similarly:

```
System.TypeInitializationException : The type initializer for 'System.Net.Security.Tests.NegotiatedCipherSuiteTest' threw an exception.
---- System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.)
-------- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
```

**Comment by karelz** [comment]
@wfurt thinks this was addressed in his recent PR. Check test history in a week to confirm and close please.

**Comment by wfurt** [comment]
I don't see any recent failures. closing.
