### ISSUE TITLE
Test failure: System.IO.Pipelines.Tests.ReadAsyncCancellationTests/FlushAsyncCancellationDeadlock 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#29741]
Test `System.IO.Pipelines.Tests.ReadAsyncCancellationTests/FlushAsyncCancellationDeadlock `has filed.

Message :
```
Assert.True() Failure
Expected: True
Actual:   False
```

Stack Trace :
```
 at System.IO.Pipelines.Tests.ReadAsyncCancellationTests.FlushAsyncCancellationDeadlock() in /_/src/System.IO.Pipelines/tests/ReadAsyncCancellationTests.cs:line 169
```

Build: -[20190602.20](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190602.20)(Master)

Failing configurations:

- Ubuntu.1804.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190602.20/workItem/System.IO.Pipelines.Tests/analysis/xunit/System.IO.Pipelines.Tests.ReadAsyncCancellationTests~2FFlushAsyncCancellationDeadlock

**Comment by jkotalik** [comment]
@jaredpar how can we get data on flaky tests in runtime? I'd like to check if ReadAsyncCancellationDeadlock has failed recently at all.

**Comment by jaredpar** [comment]
@jkotalik the easiest way right now is to use the runfo global too. With that you can grab test history like this 

```
P:\roslyn> runfo tests -d runtime -c 100 -pr -n ReadAsyncCancellationDeadlock
Cannot get test info for 729254 https://dev.azure.com/dnceng/public/_build/results?buildId=729254
Response status code does not indicate success: 503 (Service Unavailable).
P:\roslyn>
```

This command looks for failures with the name `ReadAsyncCancellationDeadlock` over the last 100 builds of runtime (`-c 100`) and includes pull requests in the results (`-pr`). There don't seem to be any other failures here (the 503 is just AzDO failing to get test data on a single build). Generally 100 builds is a good amount to look through. I did a similar search for non-pr builds and got the same feedback.

**Comment by davidfowl** [comment]
Closing this as it doesn't look like it's happening often enough. We'll keep an eye out
