### ISSUE TITLE
JsonSerializer should support private setters as an opt-in feature

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/runtime#29743]
Updated by @layomia:
*There's a lot of overlap between this feature and [field support](https://github.com/dotnet/runtime/issues/876) wrt. public API proposal. See https://github.com/dotnet/runtime/issues/34558 for combined API proposal and discussion.*

---

Non-public setters for public properties are not used when deserializing. Other serializers have this feature. As a workaround, user's have to write custom converter's for such POCOs, which isn't trivial in case of a complex object. This feature provides an opt-in for the serializer to use non-public setters.

Enabling non-public getter usage is included for parity with `Newtonsoft.Json` which supports this when the `JsonProperty` attribute is used, and to prevent complicating the API surface if this is ever desired in the future.

This feature was scoped out of v1 (3.x), as the objective was to support simple POCOs. We elected to make this feature opt-in due to security concerns with non-public support.

This feature does not include support for non-public properties.

A related feature that allows deserialization of immutable objects through parameterized constructors was recently added in https://github.com/dotnet/runtime/pull/33444.

**Comment by bnayae** [comment]
work around:
use Obsolete attribute in order to prevent direct code access (serialization is using reflection therefore ignore it)

        private string _microServiceVersion = string.Empty;
        public string MicroServiceVersion
        {
            get => _microServiceVersion;
            [Obsolete("for serialization", true)]
            set => _microServiceVersion = value; 
        }

**Comment by chrisdpratt** [comment]
@bnayae That's not a workaround. The point is to not expose a setter at all.

About the best "workaround" I've found for this is using interfaces. All my public methods return the interface, which only exposes a getter, and then the actual implementation has a setter for the sake of serialization. It doesn't stop someone from casting to the concrete type to access the setter, but using an interface is at least explicit that it should be treated as readonly.

**Comment by Felk** [comment]
Will this also work for init-only properties? 

I could not get init properties to work with the .NET 5 preview 6, so I assumed that they simply aren't supported yet in the preview build. Therefore unfortunately I was unable to test how System.Text.Json interacts with them myself.

**Comment by montyclt** [comment]
This will support init modifier of C# 9?

**Comment by steveharter** [comment]
> I could not get init properties to work with the .NET 5 preview 6, so I assumed that they simply aren't supported yet in the preview build. Therefore unfortunately I was unable to test how System.Text.Json interacts with them myself.

Are you referring to using a `record` type and having the serializer calling the appropriate constructor? If so, that was fixed in preview 7 via https://github.com/dotnet/runtime/issues/38539.

If you just are using the `init` modifier directly on a property (not a record type) that should have worked in 6.0 since the runtime doesn't prevent reflection or IL Emit'd code from calling the setter AFAIK.

**Comment by Felk** [comment]
> If you just are using the `init` modifier directly on a property (not a record type) that should have worked in preview 6 since the runtime doesn't prevent reflection or IL Emit'd code from calling the setter AFAIK.

I was running into this issues which has since been resolved: https://stackoverflow.com/q/62648189/3688648
