### ISSUE TITLE
AssemblyMetadataAttribute should be applicable to everything

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#29756]
We added the `AssemblyMetadataAttribute` as a catch-all mechanism to apply key-value pairs of metadata. There is nothing to be gained by restricting this attribute to `AttributeTargets.Assembly`. I propose to remove that restriction:

```diff
 namespace System.Reflection
 {
-    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
+    [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
     public sealed class AssemblyMetadataAttribute : Attribute
     {
         public AssemblyMetadataAttribute(string key, string? value);
         public string Key { get; } 
         public string? Value { get; }
     }
 }
```

This has come up in API reviews before. /cc @dotnet/fxdc @KrzysztofCwalina @stephentoub @steveharter

**Comment by KalleOlaviNiemitalo** [comment]
Would `AssemblyMetadataAttribute` then have to override the `Attribute.TypeId` property and return something that depends on `AssemblyMetadataAttribute.Key` as well?

**Comment by bartonjs** [comment]
The general feeling was that since the name says "Assembly" the target being Assembly-only is appropriate.  If we want a more general key-value pair bucket then we can make a more general name for a new thing.
