### ISSUE TITLE
System.PlatformNotSupportedException from NameObjectCollectionBase

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/runtime#29789]
This unsupported method was discovered while working to port the Enterprise Library Composite UI Application block. I'm receiving a System.PlatformNotSupportedException from the NameObjectCollectionBase class and can see that the corefx implementation has [three platform not supported exception scenarios](https://github.com/dotnet/corefx/blob/1fd3717d73da3ae7440841e8fded4adbba5b0770/src/System.Collections.Specialized/src/System/Collections/Specialized/NameObjectCollectionBase.cs).

It looks like a reference implementation for this is also available https://referencesource.microsoft.com/#System/compmod/system/collections/specialized/nameobjectcollectionbase.cs,80d0316befb424f2,references

It would be great if we could migrate at least the (GetObjectData) method which is the current blocker.

**Comment by GrabYourPitchforks** [comment]
Closing per https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md.
