### ISSUE TITLE
aspnetcore linux docker X509Certificate2 error not enough data

### ISSUE THREAD

**Issue by liu123456789** [dotnet/runtime#29799]
error: 0D06B08E:asn1 encoding routines:ASN1_D2I_READ_BIO:not enough data

`X509Certificate2 cert = new X509Certificate2(path, "password", X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);`

Who can help me?

**Comment by bartonjs** [comment]
There's not enough data in this issue to act on it, and it has been dormant for a long time, so closing it.
