### ISSUE TITLE
Api Proposal: Enumerable.Type() extension

### ISSUE THREAD

**Issue by yahorsi** [dotnet/runtime#29809]
Hi Guys!

Imagine we have a ```IEnumerable<T>``` where T is a bit ugly to declare explititly. Like big tuple full of names and types. And we need to iterate over that enumerable using cycle where we have to explicitly declare variable type of T. That EXPLICIT DECLARATION will look ugly and actually hard to declare/maintain.

If we could have an extension for the IEnumerable that returns just default of T than we could use compiler to infer the type of T and avoid explicitly declaring T.

Something like:
```C#
    public static class Enumerable
    {
        public static TSource Type<TSource>(this IEnumerable<TSource> source)
        {
            return default;
        }
    }

```

Then if we need to iterate over IEnumerable explicitly using foreach/for/while/... we could declare variable like
```C#
var current = MyEnumerableOfUglyBigTuplesEgFromDatabase.Type();
```

Thanks

**Comment by stephentoub** [comment]
Closing for all the cited reasons. We're not planning to add this. Thanks.
