### ISSUE TITLE
Improve System.IO.StreamReader buffer allocation

### ISSUE THREAD

**Issue by wdolek** [dotnet/runtime#29825]
## Description

Got bitten by `System.IO.StreamReader` last week. Long story short, I found out that default `bufferSize` is set to [1024](./../blob/master/src/Common/src/CoreLib/System/IO/StreamReader.cs#L26) _and_ [new byte array](./../blob/master/src/Common/src/CoreLib/System/IO/StreamReader.cs#L169) of that size is allocated when `StreamReader` is instantiated. It is OK for small buffers, but if you leave it with its default size or use bigger buffer, one could be surprised by allocated memory - especially when reading short data too often (in my case JSON stream deserialization within web app).

## Solution(s)?

I can see that `Memory<T>` or `Span<T>` are already used when processing data, would it be worth using `ArrayPool<T>` for renting `_byteBuffer` instead of allocating new byte array?

Keep in mind that making buffer smaller seems to be good-enough solution. Is this even worth improving? Has this been discussed before?

(I had also more crazy ideas, such as passing own buffer or buffer factory - but that would expose internal state of reader; or introducing new pooled-buffer stream reader - but that would just duplicate existing code...)

**Comment by carlossanlop** [comment]
Triage:
Closing this issue to track with this proposal - https://github.com/dotnet/runtime/issues/23486
