### ISSUE TITLE
Improve Enumerable.Single(predicate), Enumerable.First(predicate) and Enumerable.Count(predicate) Logic

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#29824]
### Problem

I noticed some unexpected performance hit when using `.Single(predicate)` in comparison to `.Where(predicate).Single()`. 
<details> 
  <summary>Here is code used for testing</summary><p>

``` cs
public class Program
{
    public class WhereVsPredicate
    {
        private const int N = 10000;
        private static Random R = new Random();
            
        private readonly int selector;

        [ParamsSource(nameof(ValuesForData))]
        public IntArrayArgs data;

        public WhereVsPredicate()
        {
            selector = R.Next(0, N);
        }

            
        [Benchmark]
        public int SingleWithPredicate()
        {
            return data.Values.Single(x => x == selector);
        }

        [Benchmark(Baseline = true)]
        public int WhereSingle()
        {
            return data.Values.Where(x => x == selector).Single();
        }
            
        public IEnumerable<object> ValuesForData()
        {
            yield return new IntArrayArgs(Enumerable.Range(0, 10 * N));
            yield return new IntArrayArgs(Enumerable.Range(0, 10 * N).ToArray());
            yield return new IntArrayArgs(Enumerable.Range(0, 10 * N).ToList());
        }

        public class IntArrayArgs
        {
            public IntArrayArgs(IEnumerable<int> initialValues) => Values = initialValues;

            public IEnumerable<int> Values { get; }

            public override string ToString()
            {
                if (Values.GetType().IsArray)
                {
                    return "int[]";
                }
                else if (Values is IList)
                {
                    return "List<int>";
                }
                else
                {
                    return "IEnumerable<int>";
                }
            }
        }
    }

    public static void Main(string[] args)
    {
        var summary = BenchmarkRunner.Run<WhereVsPredicate>();
        Console.ReadKey();
    }
}
```
</p></details>

And here are test results:

``` ini
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.503 (1809/October2018Update/Redstone5)
Intel Core i7-8550U CPU 1.80GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=2.2.105
  [Host]     : .NET Core 2.2.3 (CoreCLR 4.6.27414.05, CoreFX 4.6.27414.05), 64bit RyuJIT
  DefaultJob : .NET Core 2.2.3 (CoreCLR 4.6.27414.05, CoreFX 4.6.27414.05), 64bit RyuJIT
``` 

|              Method |                 data |     Mean |     Error |    StdDev |   Median | Ratio | RatioSD |
|-------------------- |--------------------- |---------:|----------:|----------:|---------:|------:|--------:|
| Single(predicate) | IEnumerable\<int>| 709.5 us | 14.600 us | 37.947 us | 690.3 us |  1.04 |    0.08 |
| Where(predicate).Single() | IEnumerable\<int> | 713.9 us | 20.252 us | 21.669 us | 706.0 us |  1.00 |    0.00 |
|                     |                      |          |           |           |          |       |         |
| Single(predicate) |            List\<int> | 874.7 us |  3.675 us |  2.869 us | 875.2 us |  2.41 |    0.02 |
| Where(predicate).Single() |            List\<int> | 363.3 us |  2.888 us |  2.411 us | 363.4 us |  1.00 |    0.00 |
|                     |                      |          |           |           |          |       |         |
| Single(predicate) |                int[] | 752.0 us |  9.163 us |  8.123 us | 749.3 us |  3.55 |    0.04 |
| Where(predicate).Single() |                int[] | 211.6 us |  1.831 us |  1.529 us | 211.3 us |  1.00 |    0.00 |

As you can see `Single(predicate)` takes on average **3 times longer** than `Where(predicate).Single()`.

Previously it was thought that this difference was caused by the non-optimized implementation of `Single(predicate)` where there was needless looping over the entire enumerable even if the count of elements that match the predicate was greater than one, as seen in this issue: https://github.com/dotnet/corefx/issues/25079 (and similar [ones](https://github.com/dotnet/corefx/issues/1254)).

But in current version this behavior is fixed: execution of the `Single` method is terminated as soon as it encounters second element that match the predicate:
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Linq/src/System/Linq/Single.cs#L71

I double checked with ILSpy that method being executed is identical to one in source control.

Nonetheless performance difference is still apparent. And it also present in such methods like `First(predicate)` and `Count(predicate)`:

|              Method |             data |      Mean |     Error |    StdDev | Ratio | RatioSD |
|-------------------- |----------------- |----------:|----------:|----------:|------:|--------:|
| First(predicate) | IEnumerable\<int> | 44.042 us | 0.8651 us | 1.8247 us |  1.49 |    0.10 |
| Where(predicate).First() | IEnumerable\<int> | 29.697 us | 0.4178 us | 0.3488 us |  1.00 |    0.00 |
|                     |                  |           |           |           |       |         |
| First(predicate) |        List\<int> | 50.766 us | 0.1905 us | 0.1688 us |  1.49 |    0.01 |
| Where(predicate).First() |        List\<int> | 34.052 us | 0.2688 us | 0.2383 us |  1.00 |    0.00 |
|                     |                  |           |           |           |       |         |
| First(predicate) |            int[] | 20.215 us | 0.4155 us | 0.5547 us |  2.05 |    0.06 |
| Where(predicate).First() |            int[] |  9.869 us | 0.1947 us | 0.2242 us |  1.00 |    0.00 |

|              Method |             data |     Mean |     Error |    StdDev |   Median | Ratio | RatioSD |
|-------------------- |----------------- |---------:|----------:|----------:|---------:|------:|--------:|
| Count(predicate) | IEnumerable<int> | 726.5 us |  4.038 us |  3.778 us | 725.4 us |  1.02 |    0.01 |
| Where(predicate).Count() | IEnumerable<int> | 713.2 us |  6.187 us |  5.166 us | 711.8 us |  1.00 |    0.00 |
|                     |                  |          |           |           |          |       |         |
| Count(predicate)|        List<int> | 913.0 us | 18.366 us | 23.227 us | 901.3 us |  2.90 |    0.07 |
| Where(predicate).Count() |        List<int> | 316.0 us |  6.230 us |  6.119 us | 314.2 us |  1.00 |    0.00 |
|                     |                  |          |           |           |          |       |         |
| Count(predicate) |            int[] | 773.9 us | 15.362 us | 33.396 us | 757.7 us |  2.97 |    0.21 |
| Where(predicate).Count() |            int[] | 267.2 us |  8.013 us |  9.841 us | 262.4 us |  1.00 |    0.00 |

### Proposal

It seems like performance difference comes from optimizations in `Where` method, so it should be optimal to implement `Single(predicate)` and similar methods based on `Where` and their version without predicate:

``` cs
public static TSource Single<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
{
    return source.Where(predicate).Single();
}

public static TSource SingleOrDefault<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
{
    return source.Where(predicate).SingleOrDefault();
}
```

**Comment by eiriktsarpalis** [comment]
We'd be happy to accept a PR that adds special casing for this method.

**Comment by eiriktsarpalis** [comment]
Closing, due to concerns already stated in https://github.com/dotnet/runtime/issues/19382#issuecomment-734524103. We can re-evaluate if new evidence shows measurable performance gains in key real-world scenaria.
