### ISSUE TITLE
`System.Drawing.Common.Bitmap` throws `ArgumentException` instead of `ObjectDisposedException` when attempted to access properties

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#29841]
* Runtime Ver.: .NET Core 3.0 P5 27626-15
  * System.Drawing.Common package Ver.: 4.6.0-preview5-19224.8
* OS Ver.: Windows 10 Home (Build No. 18912)

Consider the following code:
```cs
System.Drawing.Common.Bitmap bm = new Bitmap(100, 100);
bm.Dispose();
int width = bm.Width;
```

Normally I'd expect this to throw `ObjectDisposedException` as the object is being used after its disposal. However, on both .NET Core and Framework, this results in `ArgumentException` being thrown instead:
```
Parameter is not valid.
Stack trace:
   at System.Drawing.Image.get_Width()
   at dotnet_trace.Program.Main(String[] args) in C:\Users\gotos\source\repos\ConsoleApp21\ConsoleApp21\Program.cs:line 13
```

It seems rather absurd to see getter (which gets no parameter) throwing ArgumentException; Is this a design decision? Is there any plans to fix this to throw correct exception instead, given that it's more of a Windows component & port of .NET Framework (Mono?) therefore potentially it being a 'breaking change'?

**Comment by JeremyKuhne** [comment]
Introducing disposed checks and totally different exceptions would be a pretty substantial breaking change for existing users so we won't be able to change this.
