### ISSUE TITLE
WIP API Proposal - AssemblyBuilder.DefineDynamicAssembly for AssemblyLoadContext

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#29842]
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder.definedynamicassembly?view=netcore-3.0

`AssemblyBuilder` is implemented as a type of `RuntimeAssembly`, but there seems to be no mechanism to create it directly in a specific `AssemblyLoadContext`.

I assume we need at least one mechanism.

This issue is highly similar to that described in dotnet/runtime#29042

If we chose a similar solution, we would need 2 changes.
1. Make existing APIs sensitive to AssemblyLoadContext.CurrentContextualReflectionContext 
2. Add new explicit APIs

We may be able to support 1 above in 3.0 as this may be a simple PR.
It would be nice to add the new APIs for 3.1, but this may not meet the shiproom approval process

/cc @vitek-karas @jkotas @cablooshe @elinor-fung @jeffschwMSFT @sbomer

**Comment by Ap0k** [comment]
Please see this PR #48072

**Comment by vitek-karas** [comment]
I filed https://github.com/dotnet/dotnet-api-docs/issues/5321 for some of the documentation issues around this (mentioned by several comments above).

**Comment by vitek-karas** [comment]
#48072 implemented the change in existing APIs. I'm leaving this issue opened to track the work to add a new API which can explicitly state the load context to use.

**Comment by Ap0k** [comment]
@vitek-karas DefineDynamicAssembly API Extension PR #48353
