### ISSUE TITLE
ProcessStartInfo.Arguments follows Windows conventions on all platforms

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#29857]
Related issue in Mono: https://github.com/mono/mono/issues/14724

It seems that currently in .NET Core, ProcessStartInfo.Arguments follows Windows argument conventions on all platforms. As shown in the linked issue, this leads to significant differences in common scenarios, single quotes being an easy example. 

I wanted to open this issue to clarify whether that is intended, or if there's any chance of Core using POSIX shell conventions on platforms when appropriate. I'm somewhat concerned that Mono customers depend on the current behavior, which is what I would personally expect to see on non-Windows platforms, but I don't know how similar platform differences are typically handled in Core. If following Windows conventions on all platforms is intentional, we'll figure out how to deal with that along with existing applications, but I wanted to clarify/see if there's any chance for a change here.

**Comment by tmds** [comment]
This issue can be closed. As explained above, this behavior is intentional.
