### ISSUE TITLE
Feature request: CancellationToken as a cross-cutting concern

### ISSUE THREAD

**Issue by dmytro-gokun** [dotnet/runtime#29881]
So, i was looking at this issue here: https://github.com/dotnet/corefx/issues/32615 and then at my code where i have to pass CancellationToken all the way down through the call stack.. And then it struck me: why do we have to do all that crap manually in 2019? Is not this CancellationToken a clear example of a cross-cutting concern and best served by the infrastructure? Should not we have something like CancellationScope (similar to TransactionScope) and everything that needs access to CancellationToken can have it somehow (think of Transaction.Current).

I'm sure someone already have thought about this and the idea was rejected because it has some critical flaws. Or was it? :)

Any comment is welcome. Otherwise, I will not be able to sleep tonight, thinking about all those CancellationTokens passed around while there was a way to avoid that :).

**Comment by stephentoub** [comment]
Thanks for the discussion.  Closing.
