### ISSUE TITLE
Should test restore be part of build or build-tests?

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#29953]
With the test project restore work test projects need to be individually restored before building.

Today this was added to the overall build.cmd, but this is not a necessary step for build and lengthens the time it takes for a build to complete.  On my machine an incremental build with no work to do, this is taking 2 minutes for a no-op restore of the test projects on my notebook.

Can we consider moving this to the build-tests phase?  So long as an un-restored test project still errors correctly when trying to build without restoring it seems like a reasonable optimization.  

Thoughts @stephentoub @safern @wtgodbe @ViktorHofer?  Anyone else have numbers here?

**Comment by safern** [comment]
@ViktorHofer re-opening this as the PR that fixed it is being reverted.
