### ISSUE TITLE
[OLEDB] Text file created in US locale not readable on others as delimited file

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#29969]
Found this issue while running OLEDB outerloop tests on the CI machines with Spanish locale. (Initially reported in PR https://github.com/dotnet/corefx/pull/38024)

The failure seems to be in Spanish SKU of Windows: where a text file created in US locale cannot be read on other computers as a delimited file. (For more info check [here](https://support.microsoft.com/en-us/help/173828/access-step-by-step-page-11-cannot-import-01client-txt))

cc: @tarekgh @saurabh500

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to fix.
