### ISSUE TITLE
System.Text.Json deserializing of object[bool] does not produce boolean

### ISSUE THREAD

**Issue by radek7210** [dotnet/runtime#29960]
I understand that the System.Text.Json is still in development. However, I would like to point out that the new deserializer produces very different results than the previous one.

Scenario:

``` csharp
public class MyRequest
{
  public string ParamName { get; set; }
  public object ParamValue { get; set; }
}
```

Controller method:
``` csharp
[HttpPost]
public ActionResult<string> Post([FromBody] MyRequest myRequest)
{
  return Content($"Type of '{myRequest.ParamName}' is {myRequest.ParamValue.GetType()}; value is {myRequest.ParamValue}");
}
```

Posting this json:
``` json
{
  "ParamName": "Bool param",
  "ParamValue": false
}
```

In .net core 2.1, the false value deserializes as boolean:
Type of 'Bool param' is **System.Boolean**; value is False

However, in .net core 3.0 preview 6, the false value deserializes as System.Text.Json.JsonElement:
Type of 'Bool param' is **System.Text.Json.JsonElement**; value is False

Will there be any chance to make the new deserializer work the same as in 2.1?

Note: we declare the ParamValue as object, as in the real app the values are of several different types, and so far the deserializer handled all them for us without issues. In 3.0, all this functionality is broken.

Thanks.

**Comment by Zetanova** [comment]
Is JsonElement now a new type for POCO?

Any news about this issue?

I am trying to deserialize a response with a value-list as object.
expected values types are dynamic and i made a List<object> property in my model.

Currently with dotnet 3.1 the System.Text.Json Serializer is putting the values as JsonElement
into the List<object>, but there is no option to cast the object instance to anything.
Not even to a string

```csharp
(string)model.Values[0]; //will fail
(DateTimeOffset)model.Values[1]; //will fail
(double)model.Values[2]; //will fail
```

The only option what i see is to change from Object[] to JsonElement[]

**Comment by ahsonkhan** [comment]
> Is JsonElement now a new type for POCO?

It's a struct that holds the JSON itself and provides ways for you to walk the document object model (DOM), programmatically. 
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement?view=netcore-3.1

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?view=netcore-3.1#use-jsondocument-for-access-to-data

> I am trying to deserialize a response with a value-list as object.
expected values types are dynamic and i made a List property in my model.

You can cast the `object model` to `JsonElement` and then get the values you need.

So:
```C#
object model = JsonSerializer.Deserialize<object>("[\"str\", \"2020-02-22T05:50:46.3605858+00:00\", 25.5]");
if (model is JsonElement element)
{
    string str = element[0].GetString(); // returns "str"
    DateTimeOffset date = element[1].GetDateTimeOffset();
    double num = element[2].GetDouble(); //returns 25.5
}
```

**Comment by Zetanova** [comment]
@ahsonkhan Thx for your answere, but it is not answering it. 
Because there is no generic option to cast/read the value from JsonElement, 
the consumer of the POCO need to know about the JsonElement Type 
and so it would be a new POCO type. 
This would be somehow against the naming of Plain-Old-CLR-Object.

**Comment by johnwc** [comment]
For those looking to convert JSON object to Hashtable, feel free to use my example. It should cover all JSON types. But, I have not tested it thoroughly, only for what we are needing it for. I have not used the write either, as we are only reading.

```CSharp
var options = new JsonSerializerOptions();
options.Converters.Add(new JsonHashtableConverter());
var obj = JsonSerializer.Deserialize<Hashtable>(object, options);


public class JsonHashtableConverter : JsonConverterFactory
{
	private static JsonConverter<Hashtable> _valueConverter = null;

	public override bool CanConvert(Type typeToConvert)
	{
		return typeToConvert == typeof(Hashtable);
	}

	public override JsonConverter CreateConverter(Type type, JsonSerializerOptions options)
	{
		return _valueConverter ?? (_valueConverter = new HashtableConverterInner(options));
	}

	private class HashtableConverterInner : JsonConverter<Hashtable>
	{
		private JsonSerializerOptions _options;
		private JsonConverter<Hashtable> _valueConverter = null;

		JsonConverter<Hashtable> converter
		{
			get
			{
				return _valueConverter ?? (_valueConverter = (JsonConverter<Hashtable>)_options.GetConverter(typeof(Hashtable)));
			}
		}

		public HashtableConverterInner(JsonSerializerOptions options)
		{
			_options = options;
		}

		public override Hashtable Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		{
			if (reader.TokenType != JsonTokenType.StartObject)
			{
				throw new JsonException();
			}

			Hashtable hashtable = new Hashtable();

			while (reader.Read())
			{
				if (reader.TokenType == JsonTokenType.EndObject)
				{
					return hashtable;
				}

				// Get the key.
				if (reader.TokenType != JsonTokenType.PropertyName)
				{
					throw new JsonException();
				}

				string propertyName = reader.GetString();
				reader.Read();

				hashtable[propertyName] = getValue(ref reader, options);
			}
			return hashtable;
		}

		private object getValue(ref Utf8JsonReader reader, JsonSerializerOptions options)
		{
			switch (reader.TokenType)
			{
				case JsonTokenType.String:
					return reader.GetString();
				case JsonTokenType.False:
					return false;
				case JsonTokenType.True:
					return true;
				case JsonTokenType.Null:
					return null;
				case JsonTokenType.Number:
					if (reader.TryGetInt64(out long _long))
						return _long;
					else if (reader.TryGetDecimal(out decimal _dec))
						return _dec;
					throw new JsonException($"Unhandled Number value");
				case JsonTokenType.StartObject:
					return JsonSerializer.Deserialize<Hashtable>(ref reader, options);
				case JsonTokenType.StartArray:
					List<object> array = new List<object>();
					while (reader.Read() &&
						reader.TokenType != JsonTokenType.EndArray)
					{
						array.Add(getValue(ref reader, options));
					}
					return array.ToArray();
			}
			throw new JsonException($"Unhandled TokenType {reader.TokenType}");
		}

		public override void Write(Utf8JsonWriter writer, Hashtable hashtable, JsonSerializerOptions options)
		{
			writer.WriteStartObject();

			foreach (KeyValuePair<string, object> kvp in hashtable)
			{
				writer.WritePropertyName(kvp.Key);

				if (converter != null &&
					kvp.Value is Hashtable)
				{
					converter.Write(writer, (Hashtable)kvp.Value, options);
				}
				else
				{
					JsonSerializer.Serialize(writer, kvp.Value, options);
				}
			}

			writer.WriteEndObject();
		}
	}
}
```

**Comment by thinkards** [comment]
For others wanting to do something similar...

I needed an object property that accepts bool, number, or string for binding through ASP.NET core controller actions:

```csharp
    public class MyConverter : JsonConverter<object>
    {
        public override object Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options)
        {
            long longValue = 0;
            Decimal decimalValue = 0.0M;

            if (reader.TokenType == JsonTokenType.Number)
            {
                if (reader.TryGetInt64(out longValue))
                {
                    return longValue;
                }
                else
                {
                    if (reader.TryGetDecimal(out decimalValue))
                    {
                        return decimalValue;
                    }
                }
            }
            else if (reader.TokenType == JsonTokenType.True)
            {
                return true;
            }
            else if (reader.TokenType == JsonTokenType.False)
            {
                return false;
            }
            else if (reader.TokenType == JsonTokenType.String)
            {
                return reader.GetString();
            }
            throw new JsonException($"Invalid type {reader.TokenType}");

        }

        public override void Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options)
        {
            throw new InvalidOperationException("Directly writing object not supported");
        }
    }
```

Which I applied to my model for ASP.NET core binding:

```csharp

    public class MyModel
    {
        ...
        [JsonConverter(typeof(MyConverter))]
        public object Value { get; set; }
        ...
    }
```

And used in my Controller Action:

```csharp
        public async Task Create([FromBody]MyModel model)
        {
            await DoWork(model);
        }
```

**Comment by mguinness** [comment]
Microsoft docs now has section [Deserialize inferred types to object properties](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#deserialize-inferred-types-to-object-properties) w/ an example JSON object converter.

When using [Bind(IConfiguration, Object)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.bind#Microsoft_Extensions_Configuration_ConfigurationBinder_Bind_Microsoft_Extensions_Configuration_IConfiguration_System_Object_) with JSON provider, it will deserialize as a string, i.e. 1 as "1" & true as "True".

**Comment by Banyc** [comment]
Is there a concrete solution for the controllers in ASP.NET Core? The `object` in parameter `IDictionary<string, object> request` is always `JsonElement`, which does not support a typecast.

**Comment by steveharter** [comment]
As mentioned above, the current design avoids deserializing JSON string and bool to CLR string and bool because this would not be consistent with how JSON numbers are deserialized (since we don't know the CLR number type and don't want to "guess").

Imagine having a CLR `object[]` property and if the JSON has mixed values (strings, bools, numbers), some array elements would be are CLR `string`, some `bool` and the numbers would be `JsonElement` -- that would be more confusing IMHO. Also, Newtonsoft deserializes JSON `string` sometimes as a GUID or DateTime, which can also be confusing and\or unexpected.

So if we want to add a Newtsonsoft custom converter that is possible, but we can't change the default behavior in any case since that would break backwards compat.

**Comment by layomia** [comment]
Per comments above, I'll close this issue. Changing the default behavior would be a breaking change, and there are workarounds described in System.Text.Json documentation: https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#deserialize-inferred-types-to-object-properties.

**Comment by johnwc** [comment]
@steveharter there was a few shared examples in these comments that gave you great examples of how to test if a JavaScript Number type can safely be deserialized as a valid CLR type. 

As for the bool type you keep through into the mix with Number, what other bool type is there in JavaScript and CLR other than Bool? Why are you not at least converting bool types to valid CLR bool type? I can somewhat see your point about Number type; even though there is simple ways to test for valid serialization, but I don't get the reason for not allowing to do one-to-one bool type.

**Comment by steveharter** [comment]
@johnwc can you share some scenarios where the CLR type is `System.Object` for numbers and why it can't be strongly typed as `System.Decimal` or `System.Double`?

> JavaScript Number type can safely be deserialized as a valid CLR type.

If the only known JSON producer\consumer is JavaScript, then I recommend using a custom converter that converts to `double` only.

The two main issues with using `double` for JSON numbers:
- Loss of precision when dealing with multiple monetary values (such as adding several values and doing an `Equals()` -- example below).
- Large integers must be converted to `decimal` and\or `BigNumber` or lose precision.

Neither `Utf8JsonReader` or `JsonElement` automatically perform JSON number conversions (it leaves it up to the user to explicitly call `GetDouble(`), etc), so the serializer follows that same logic and doesn't "guess". However, it does support using a custom converter (in a relatively easy manner) to do this in whatever fashion is appropriate.

To avoid precision loss when dealing with monetary values, `decimal` should be used, not `double`. If JSON numbers are converted to `double` (when the CLR type is unknown via `System.Object`) that means the corresponding user logic will need to use `double` which may cause various [precision issues](https://docs.microsoft.com/en-us/dotnet/api/system.double?view=net-5.0#floating-point-representation-and-precision): 
```cs
using System;

public class Example
{
   public static void Main()
   {
      Double[] values = { 10.0, 2.88, 2.88, 2.88, 9.0 };
      Double result = 27.64;
      Double total = 0;
      foreach (var value in values)
         total += value;

      if (total.Equals(result))
         Console.WriteLine("The sum of the values equals the total.");
      else
         Console.WriteLine("The sum of the values ({0}) does not equal the total ({1}).",
                           total, result);
   }
}
// The example displays the following output:
//     The sum of the values (27.639999999999997) does not equal the total (27.64).
```

Note Newtonsoft behavior; not exactly intutitive IMHO:
```cs
    object oDouble = JsonConvert.DeserializeObject("1.0");
    Console.WriteLine(oDouble.GetType()); // "System.Double
    object oLong = JsonConvert.DeserializeObject("1");
    Console.WriteLine(oLong.GetType()); // System.Int64
    object oBigInteger = JsonConvert.DeserializeObject(decimal.MaxValue.ToString());
    Console.WriteLine(oBigInteger.GetType()); // System.Numerics.BigInteger
```

**Comment by johnwc** [comment]
@steveharter again, you keep focusing on doubles and Number type. Use decimals... or use doubles... but not to some arbitrary JsonElement object. It really does not matter what it converts it to, when there is a way to have the ability to overwrite it for exactly how you need it to be outside of the default. Truthfully, I think you're getting caught up on something that is not really an issue for 99% of use cases. As most will not be using an object type for when needing to do math or working with monetary values. With the way it is now, you are forcing the 99% to now write more custom functionality, instead of just using OoB functionality.

Can you please answer the main part of the comment that was about Bool types not being deserialized?

**Comment by steveharter** [comment]
> Can you please answer the main part of the comment that was about Bool types not being deserialized?

Here's what I mentioned prior:

> Imagine having a CLR object[] property and if the JSON has mixed values (strings, bools, numbers), some array elements would be are CLR string, some bool and the numbers would be JsonElement -- that would be more confusing IMHO

Thus if we auto-convert JSON bool to `System.Boolean` the doc and behavior would be somewhat ambiguous: "When the CLR type is `System.Object` then all JSON values are converted to JsonElement except a JSON bool which is converted to System.Boolean". 

And if we do that one-off behavior, the next question is what about JSON string (`System.String`), JSON arrays (`System.Array`) and then of course numbers.

Going forward, since we can't break default behavior, here are two options to address:
1) Add values to the `JsonUnknownTypeHandling` enum (which is set on `JsonSerializerOptions` to make this easier such as:
  `JsonUnknownTypeHandling.AutoPrimitivesThenJsonElement`
  `JsonUnknownTypeHandling.AutoPrimitivesThenJsonElement`
2) Provide a "SystemObjectPrimitiveConverter" or "SystemObjectNewtonsoftCompat" custom converter that must be manually added to `JsonSerializerOptions`.

**Comment by steveharter** [comment]
FWIW the new `JsonNode` may help in certain scenarios since it at least allows explicit casts to primitives:

```cs
// If you can use JsonNode\JsonArray in the signature:
JsonArray nodes = JsonSerializer.Deserialize<JsonArray>("[1,1.1,\"Hello\"]");
long l = (long)nodes[0];
double d = (double)nodes[1];
string s = (string)nodes[2];
```

If you must have `System.Object`, you can still leverage nodes:
```cs
JsonSerializerOptions options = new();
options.UnknownTypeHandling = JsonUnknownTypeHandling.JsonNode;
object[] objects = JsonSerializer.Deserialize<object[]>("[1,1.1,\"Hello\"]", options);

long l = (long)(JsonNode)objects[0];
// or alternatively:
l = ((JsonValue)objects[0]).GetValue<long>();
double d = (double)(JsonNode)objects[1];
string s = (string)(JsonNode)objects[2];
```

**Comment by johnwc** [comment]
I was under the assumption that strings where actually being deserialized as CLR strings, and that only bool and Number types where for some reason being left as JsonElement.

**Comment by Zetanova** [comment]
Is there a reason for that `JsonElement` has no explicit cast operators implemented?

**Comment by John0King** [comment]
> Per comments above, I'll close this issue. Changing the default behavior would be a breaking change

In fact , I think you can not break anyone who use .net to build their application,  because no one use `System.Text.Json` , 
unless, they are writing demos 🤣.

and for the scenario that use `System.Text.Json` in  Authentication,  well , you already break us before , why you so afraid to break us again ?   and  beside , break change comes anyway ,  if it's not here, then it will be there .  

so  breaking change should not effect what we talk here,   we should talk about  what does it should be (the best practice)

**Comment by steveharter** [comment]
> so breaking change should not effect what we talk here, we should talk about what does it should be (the best practice)

Best practice IMO is to be explicit on the CLR type. This mean either:
- Change the consuming code to use an explicit type and not `System.Object`. This avoids the ambiguity (and is faster).
- Use the current explicit behavior of `JsonElement` \ `JsonNode` to obtain the appropriate CLR type from the JSON primitive, possibly calling helper methods to parse the string if the Type is not directly supported:
- JSON bool: Boolean
- JSON string: String, DateTime, Guid, Uri, etc
- JSON number: Long, Ulong, Decimal, etc
