### ISSUE TITLE
ExcludeFromCodeCoverageAttribute should have Justification property

### ISSUE THREAD

**Issue by vixisoft** [dotnet/runtime#29968]
Hi,

I've wrote an issues on https://github.com/dotnet/standard/issues/1242 and I was tell to write it here!

I dont know if i need to write it back here, so tell me if it's required but everything is in the other issues!

**Comment by StingyJack** [comment]
We would like this also, specifically so we can require a justification be provided. Contrary to the[ statements in the linked issue](https://github.com/dotnet/runtime/issues/29996#issuecomment-501585790) regarding the reasons for using the attribute would be obvious, the Justification given is from the developer who added it, and who is not always going to know everything and may need to indicate that they lack the expertise or even a note that the unit testing will be deferred to a follow-up user story. 

The developers that are in the same org/team or that consume the excluded code will be the ones to determine if the reason given is legitimate or not. We aren;t asking anyone from Microsoft to do that, we just want the parameter/property made available as it is for other suppression attributes..

**Comment by RealDotNetDave** [comment]
This Attribute only has one property. Why do I have to use it's name?

`[ExcludeFromCodeCoverage(Justification ="Not needed due to just using the DateTime type.")]`

Also, can this be added to the attribute in the .NET Framework too?

**Comment by stephentoub** [comment]
This has existed since .NET 5:
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute.justification?view=net-7.0#system-diagnostics-codeanalysis-excludefromcodecoverageattribute-justification

**Comment by stephentoub** [comment]
> Also, can this be added to the attribute in the .NET Framework too?

No, we're not adding new API to .NET Framework.
