### ISSUE TITLE
CancellationTokenSource is hard to use correctly

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#29970]
`CancellationTokenSource` is hard to use correctly, especially in concurrent scenarios.

Most CancellationTokenSource methods are booby-trapped with `ThrowIfDisposed`, especially tricky with `.Token` and `.Cancel()`. As for both cases there's something to say for silently returning a None token or not Cancelling, but also something to say for being explicit about it and throwing if it happens.

The problem with that last option though is that there's no way to actually check if the CancellationTokenSource is already disposed, now checking could obviously race but there are no `Try##` variants of these methods either. This leads to over cautious behavior, wrapping each call in a try block.

Concurrent success and cancellation/failure cases are also fun as `Cancel` throws if the CTS was already disposed. But for timer based CTS's you really do want to `Dispose` once some piece of code sucessfully completed. This is prone to races between timeouts that try to cancel and success that tries to dispose. This is 'fixable' by locking on the CTS but it all feels brittle.

The current `Cancel` api is in my opinion the most egrigious, `TryCancel` would be a valuable api to add.

Lastly there's the matter of having to Dispose a CTS — but really only in some cases. When the CTS is timer based, to keep the timer queue clean. Failing to do so isn't easy to diagnose and I believe it's a pervasive problem in any corporate codebase not familiar with all the details. Having some diagnostic help like `UnobservedTaskException` but for unobserved timer based CTS's would be amazing.  

Right now `CancellationTokenSource` feels far from the pit of success while it really doesn't have to.

**Comment by wazzamatazz** [comment]
Is there a particular reason that `CancellationTokenSource` does not cancel its token when it is disposed? I've been caught out by this a couple of times when I have a class that kicks off one or more background tasks that should gracefully exit when the class is disposed. The class has a `CancellationTokenSource` that is used to provide a `CancellationToken` to the background tasks. When it comes to implementing `Dispose()`, it feels strange that I need to explicitly cancel the `CancellationTokenSource` instead of this being done automatically when it is disposed.

**Comment by stephentoub** [comment]
Primarily because Dispose is only supposed to be used with objects no longer in use, and if the implementation needs to cancel, it's because it's still in use.

**Comment by wazzamatazz** [comment]
I understand where you're coming from, but by that logic, you could argue that a `DbConnection` should stay open after disposing it unless you explicitly call `Close` on it too. Either way, I think it would be helpful if the documentation for `CancellationTokenSource` clearly stated that disposing the object does not cancel the token.

**Comment by stephentoub** [comment]
> but by that logic, you could argue that a DbConnection should stay open after disposing it unless you explicitly call Close on it too

In the DbConnection case, you wouldn't call Dispose on it if some other code was still using it; that would be a problematic race condition.  Similarly, the ideal is you shouldn't be calling Dispose on a CancellationTokenSource while some other thread is using it, which is what's happening if code elsewhere is registered with its CancellationToken, using its CancellationToken, etc.

> Either way, I think it would be helpful if the documentation for CancellationTokenSource clearly stated that disposing the object does not cancel the token.

Sure.  The docs are open source.  Please consider submitting a PR to https://github.com/dotnet/dotnet-api-docs.

**Comment by wazzamatazz** [comment]
Will do, thanks!

**Comment by NN---** [comment]
@stephentoub I understand that disposing CancellationTokenSource is not recommended unless created using CreateLinkedTokenSource, correct ?

**Comment by stephentoub** [comment]
> I understand that disposing CancellationTokenSource is not recommended unless created using CreateLinkedTokenSource, correct ?

No.  It's good to dispose of disposable things in general.  But sometimes, especially when dealing with asynchronous code, or when dealing with code where ownership or lifetimes isn't clear, that such a general guideline needs to be weighed for its benefits / risks.  With CTS, it's most important to Dispose of it when created with CreateLinkedTokenSource, and secondarily when it's used with a timeout.

**Comment by NN---** [comment]
So the issue is just asking how to improve usage of potentially disposed CancellationToken. Correct ?

**Comment by stephentoub** [comment]
> So the issue is just asking how to improve usage of potentially disposed CancellationToken. Correct ?

That is my understanding of the request.

**Comment by NinoFloris** [comment]
Closing since TryReset made it into 6.0
