### ISSUE TITLE
Enum API

### ISSUE THREAD

**Issue by Hosch250** [dotnet/runtime#29999]
The `System.Enum` class implements an API that would have readability, type safety, and performance enhanced by implementing the methods with generics. Now that .NET Core supports the `Enum` filter on generic type members it should be easy to implement.

# Rational and Usage
Currently, to get the name of an enum value, you must do:

```cs
MyEnum value;
Enum.GetName(typeof(MyEnum), value);
```

Or to get all values of an enum type, you must do:

```cs
var values = Enum.GetValues(typeof(MyEnum)).Cast<MyEnum>();
```

With generics, we could make these calls more clear and concise as:

```cs
MyEnum value;
Enum.GetName<MyEnum>(value);

var values = Enum.GetValues<MyEnum>();
```

# Proposed API
I propose we add the following members to `System.Enum`:

```cs
public static string GetName<T>(T value)          where T : System.Enum, struct;
public static IEnumerable<string> GetNames<T>()   where T : System.Enum, struct;
public static IEnumerable<T> GetValues<T>()       where T : System.Enum, struct;
public static T Parse<T>(T value)                 where T : System.Enum, struct;
public static object ToObject<T>(T value)         where T : System.Enum, struct;
```

# Notes

While one implementation of these could just call back to the non-generic version, they could be made slightly more performant by using the generics to their full potential and avoiding boxing when getting the values.

# Open Questions

Should the `IEnumerable<T>` members be `IList<T>` or `Array<T>` instead?

**Comment by stephentoub** [comment]
All of the proposed APIs (with the exception of `ToObject<T>`) now exist, and we've seen little need/interest for a generic ToObject.  Given that, I'm going to close this.  Thanks for the issue.
