### ISSUE TITLE
DispatchProxy does not allow for building collectible assemblies.

### ISSUE THREAD

**Issue by cablooshe** [dotnet/runtime#30032]
Currently when you create a DispatchProxy, it makes the DynamicAssembly that generates the IL an noncollectable assembly (it's hardcoded to use AssemblyBuildAccess.Run [here](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs#L204 )). This makes it impossible to create DispatchProxies inside collectible AssemblyLoadContexts.

If you try and use this create within a collectible AssemblyLoadContext, it fails with `System.NotSupportedException: 'A non-collectible assembly may not reference a collectible assembly.'`

```C#
public class ExampleDispatch<I> : DispatchProxy
{
    public object instance;
    internal static I Create<Dispatch>(Type type)
    {
        object proxy = Create<I, ExampleDispatch<I>>(); //Error throws here
        ((ExampleDispatch<I>)proxy).SetParameters(type, new Type[] { }, new object[] { });
        return (I)proxy;
    }

    private void SetParameters(Type instanceType, Type[] argTypes, object[] constructorArgs)
    {
        instance = instanceType.GetConstructor(argTypes).Invoke(constructorArgs);
    }

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        return targetMethod.Invoke(instance, args);
    }
}
```

A few options to fix this could be to change DispatchProxy's dynamic assembly to run with `AssemblyBuildAccess.RunAndCollect`, or allow for manually entering an option in `DispatchProxy.Create<T, TProxy>()` to decide if it should be collectible or not.

**Comment by steveharter** [comment]
> or allow for manually entering an option in DispatchProxy.Create<T, TProxy>() to decide if it should be collectible or not.

This seems to be a viable option since it won't break existing users.

However, DispatchProxy investment is not our roadmap for 5.0. If there are additional demand for this, we change reconsider.

cc @GrabYourPitchforks
