### ISSUE TITLE
SystemEvents.SessionSwitch event is not getting fired in macOs mojave

### ISSUE THREAD

**Issue by bhaskar-majumder** [dotnet/runtime#30035]
# Issue Title

`SystemEvents.SessionSwitch` event is not getting fired in macOs mojave.
`SystemEvents.SessionSwitch += new SessionSwitchEventHandler(SystemEvents_SessionSwitch);` is working fine for Windows 10 but it is not working in Mac.

# General

Trying to listen to system events like lock/unlock, user sign in/out etc. for our dotnet core application which runs on both Windows and Mac. 
To achieve this `SystemEvents.SessionSwitch` seemed a good option but it is not working in macOs mojave. 
I am currently using dotnet core 2.2
Please suggest a solution for this.

**Comment by Anipik** [comment]
Here is some info on events on mac https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/MonitoringEvents/MonitoringEvents.html
