### ISSUE TITLE
Method to determine current stack size

### ISSUE THREAD

**Issue by monty241** [dotnet/runtime#30034]
Our software runs on various platforms, both on framework 4.7.2 (W7..W10) as well as .NET Core 2.1 and 2.2 on Linux, Mac and Windows.

With increasing use of .NET Core on Linux, we get some errors on the restrained stack size. For instance, our Exact Online drivers require at stack size of at least close to 256 KB during initialization due to CLR issues.

I would like to add some checks to the base classes which guide users and system administrators when the stack size is expected to be too small to run the software.

On Windows 7 it is quite hard to get the stack size, On win8..10 it is easy, but on .NET Core I seem unable to find a valid approach.

Would be great when a method could be added which just returns the current stack size of the running thread.

**Comment by stephentoub** [comment]
@monty241, can you propose what API you'd hope to see here?
https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

**Comment by stephentoub** [comment]
Closing due to no response.  Please feel free to re-open if this is still an issue and you can propose the API in question.  Thanks.
