### ISSUE TITLE
Add Task.Wait(TimeSpan, CancellationToken) api

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#30067]
The current api might tempt people to directly cast `TimeSpan.TotalMilliseconds` to int (guilty) without realizing that there may be super rare cases where this truncates high ranges.

There is a `Task.Wait(TimeSpan)` overload to pair with the `Task.Wait(int)` method so it would only be good if the same would be true for `Task.Wait(int, CancellationToken)`.

This came up in a review of an Npgsql PR https://github.com/npgsql/npgsql/pull/2508#discussion_r298261063

**Comment by stephentoub** [comment]
Closing as one specific case of https://github.com/dotnet/runtime/issues/14336.  It'd be good to address this holistically if it's going to be addressed.
