### ISSUE TITLE
Allow Multiplication between Vector and Matrix

### ISSUE THREAD

**Issue by disks86** [dotnet/runtime#30089]
I think we need Multiply(Vector4,Matrix4x4) and Multiply(Matrix4x4,Vector4) support. It would be ideal if * worked but at least having named methods would be helpful.

**Comment by tannergooding** [comment]
Going to close this as multiplication between a vector and matrix is already supported via the `Transform` methods.

If you have a more specific ask, such as exposing an explicit multiplication operator, please feel free to open a new issue detailing that. Our API review process is detailed [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with a "good example" being listed under step 1. Ideally the new issue would provide many of the sections given, but would at a minimum provide the base rationale and proposed API surface sections.
