### ISSUE TITLE
Question: Activity User Guide Sample Issue

### ISSUE THREAD

**Issue by krispenner** [dotnet/runtime#30112]
Regarding: [Activity User Guide](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#starting-and-stopping-activity)

I'm questioning the sample given which uses `if (httpListener.IsEnabled("Http_In"))` _to avoid creating activities when no-one is listening to them and to enable event name-based filtering or sampling_. It would also prevent the actual activity tracked underlying process from executing if the above returns false. I would assume that would not be wanted unless I'm not understanding its use correctly.

Would a clearer working example look more like:

```cs
public void OnIncomingRequest(DiagnosticListener httpListener, HttpContext context)
{
    Activity activity = httpListener.IsEnabled("Http_In") ? new Activity("Http_In") : null;

    if (activity != null)
    {
        //add tags, baggage, etc.
        activity.SetParentId(context.Request.headers["Request-id"])
        foreach (var pair in context.Request.Headers["Correlation-Context"])
        {
            var baggageItem = NameValueHeaderValue.Parse(pair);
            activity.AddBaggage(baggageItem.Key, baggageItem.Value);
        }     
        httpListener.StartActivity(activity, new  {context});
    }

    try
    {
        //process request ... (THIS IS NOW ALWAYS EXECUTED)
    }
    finally
    {
        if (activity != null)
        {
            //stop activity
            httpListener.StopActivity(activity, new {context} );
        }
    }
}
```

The above sample now ensures that the underlying process is still executed regardless of whether the activity tracking it is to be enabled or not.
This is not meant to complain about the example but just to confirm my understanding of it and possibly suggest proper usage of it.
Same applies to the [Creating Child Activities](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#creating-child-activities) sample as well.

**Comment by tarekgh** [comment]
@krispenner feel free to submit a PR for updating the sample.
