### ISSUE TITLE
.NET runtime on RPI - Segmentation fault

### ISSUE THREAD

**Issue by florrain** [dotnet/runtime#3013]
## Steps to reproduce
- Install the runtime on a Raspberry PI 2 model B, Raspbian Lite:
- `sudo apt-get install curl libunwind8 gettext`
- `curl -sSL -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-latest-linux-arm.tar.gz`
- `sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet`
- `sudo ln -s /opt/dotnet/dotnet /usr/local/bin`

## Expected  behavior
The runtime should run with no segfault.

## Actual behavior
```
$ dotnet
Segmentation fault
```

Whatever the options passed to the executable are, it always gives a segfault. Tried on Raspbian and on DietPi.

## Environment data
I'm not sure what would be valuable for debugging so please tell me.

**Comment by gnraju20411** [comment]
### There is any way to install ASP.net core on Raspberry pi Zero W device?
![Capture](https://user-images.githubusercontent.com/17039448/74231762-54aff800-4ced-11ea-84ee-ffc2cf820849.PNG)

**My device configuration:**
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 997.08
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 00000000f6bd1450

**Comment by janvorli** [comment]
@gnraju20411 no, it cannot be installed there. We don't support the ARMv6, only ARMv7. The ARMv6 doesn't support THUMB2 instruction encoding that our JIT generates and runtime requires. Some effort to make runtime work on ARMv6 was initiated by @franksinankaya (PR #657), but I am not aware of any work done on the JIT side.
Also see #7764 for more details.
