### ISSUE TITLE
Few re-enabled System.Console tests are failing on CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#30130]
- ExitDetectionNotBlockedByHandler
- HandlerInvokedForSigInt
- HandlerInvokedForSigQuit

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38676~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190702.9/workItem/System.Console.Tests

Tests have existed in the code-base for some time but were missing Fact attribute. When the Fact attribute was added, it started running & failing.

**Comment by carlossanlop** [comment]
@tmds did you get a chance to re-enable these tests?

**Comment by adamsitnik** [comment]
@tmds ping
