### ISSUE TITLE
Select in certain cases is run after enumerator disposal

### ISSUE THREAD

**Issue by BratWiekszy** [dotnet/runtime#30137]
Consider following invocations on the same enumerable (enumerator):  
```c#
1: enumerable.Where((_, i) => i == 4).Select(x => x.Foo()).First();
2: enumerable.Select(x => x.Foo()).ElementAt(4);
3: enumerable.Skip(4).Select(x => x.Foo()).First();
4: enumerable.Select(x => x.Foo()).Take(5).Last();
5: enumerable.Take(5).Select(x => x.Foo()).Last();
```

All of them should return the same element with Foo() selector applied, and it happens. Also some of them use optimisations, which limit number of calls of selector (to 1, by calling only on 5th):
  
 - 1: limit exists and it's desired,
 - 2: limit does not exist, and it's weird because 5. has limit, even tho 2. is more suitable for such optimisation, but it's not a problem,
 - 3: limit exists and it's desired,
 - 4: limit does not exist but it's fine,
 - 5: limit exists but it's fine.

 In case of 3. and 5. selector function is run after a call to `Dispose()` on enumerator and it's problematic because it does not comply will exprected behavior of something disposable - it usually is usuable and its data unavailable. Also, in my case, enumerator fetches data headers in MoreNext() before returning, and in next call it decides whether to fetch full data based on call in Foo(). When no next call is made, this fetching is done in Dispose, at last point where it could be done, and then data source is closed. Even if i put full fetching code inside Foo(), it being called after Disposal completely invalidates this workaround.
 
Since now I know about this quirk, i can fix my calls, but consumers of my code may not have even slightest idea why their data is missing. I see two possible fixes:
  
 - Althought implementation of SelectIPartitionIterator, EnumerablePartition and respective TryGetLast() or TryGetFirst() methods of Enumerable are negligible detail, it does influence behavior of calls, and as such it should be mentioned somewhere in docs.
 - TryGetLast<T>(IEnumerable<T>, out bool) and TryGetFirst<T>(IEnumerable<T>, out bool) code that now looks like:
 ```c#
if (source is IPartition<TSource> partition)
{
    return partition.TryGetLast(out found);
}
``` 
could be replaced with something like this:
```c#
if (source is IPartition<TSource> partition)
{
    var result = partition.TryGetLast(out found);
    Dispose();
    return result;
}
```
and IPartition<T> methods like TryGetLast() and TryGetFirst() shouldn't dispose own enumerator before their dispose is called.

**Comment by eiriktsarpalis** [comment]
Closing as by-design.
