### ISSUE TITLE
What is the recommended solution to mscorlib having a reference to System.Security.Permissions

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#30148]
I find it really weird that `mscorlib` has an assembly reference (and type forwarders) to an assembly which is not shipping in the `Microsoft.NETCore.App` framework.

I understand that trying to build a new app using  these types results in an error which directs users to install the assembly:
```
Program.cs(10,66): error CS1069: The type name 'DataProtectionPermission' could not be found in the namespace 'System.Security.Permissions'. This type has been forwarded to assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [E:\AppModel\repro\secper1\secper1.csproj]
```
(Note though that the error says add a reference to an assembly - which doesn't exist, one has to know to go to NuGet and install the package for it - and to pick the right version).

But if I have an existing code, like a library built for .NET Framework which uses these types, there's no way to know this.

What is our guidance to people running into this issue?

**Comment by bartonjs** [comment]
Since the question was answered and there hasn't been any recent activity, closing the issue.
