### ISSUE TITLE
A Generic error occurred in GDI+ in the Graphics.MeasureString method

### ISSUE THREAD

**Issue by MrB0nd** [dotnet/runtime#30147]
When we tried to measure a specific string using the Graphics.MeasureString method, we got an error. Here is the code that can be used to reproduce the issue:
```
string str = new string(new char[] { (char)160, (char)773 });
Graphics g = Graphics.FromImage(new Bitmap(10, 10));
var size = g.MeasureString(str, new Font("Arial", 10));
```
This issue is reproduced on Windows 10, Version 1809, but we didn't get this error on Windows 7.

**Comment by JeremyKuhne** [comment]
As this appears to be a GDI+/Windows issue there isn't much we can do here.
