### ISSUE TITLE
Implement Regex.CompileToAssembly for netcoreapp

### ISSUE THREAD

**Issue by mjsabby** [dotnet/runtime#30153]
https://github.com/dotnet/corefx/pull/24158 ported over the implementation from desktop to support in-memory compiled regex.

This issue is tracking bringing back the remaining piece which allows saving the generated MSIL to an assembly.

The implementation will have to diverge from desktop because the the APIs needed to do this are unavailable on netcoreapp surface area. Instead we'll need to use S.R.M to implement this.

**Comment by pgovind** [comment]
Just linking this to the source generator story: https://github.com/dotnet/runtime/issues/44676

**Comment by stephentoub** [comment]
.NET 7 will have a source generator for this purpose, and CompileToAssembly was obsoleted. Thanks.
