### ISSUE TITLE
WebSocket doesn't amortize its ValueTask ReadAsync calls

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#30167]
In usage a WebSocket normally has very many ReadAsync calls made on it.  (Use case WebSockets/SignalR over TLS)

Using the ValueTask overloads for WebSocket read allocates 2x AsyncStateMachineBox per read (when data is not immediately available)

![image](https://user-images.githubusercontent.com/1142958/60764376-7de61700-a080-11e9-85ac-6cbb37053893.png)

However it could allocate once; backing with an IValueTaskSource objects that get allocated for the first async and reused when the read goes async again.

**Comment by karelz** [comment]
Closing as it should be solved by the linked PR - https://github.com/dotnet/coreclr/pull/26310

**Comment by benaadams** [comment]
Not entirely; it does an `.AsTask()` in one of the paths converting a `ValueTask` to a Task; which could be avoided with some refactoring (though isn't completely straightforward)

**Comment by stephentoub** [comment]
> which could be avoided with some refactoring

What kind of refactoring are you thinking about?  The challenge here I've faced whenever I've sat down to address this (and then sighed and walked away) is the potential consumption by not only the consumer of the receive but also a potentially concurrent close.

**Comment by benaadams** [comment]
> What kind of refactoring are you thinking about? 

I did attempt it; it was on the basis that close could only happen once so I reversed the dependency, however the knock on effects turned out to be a lot more wide reaching than I was anticipating so I never finished it 😢

Leading me to the assessment:

>  isn't completely straightforward

😉

**Comment by stephentoub** [comment]
> I did attempt it; it was on the basis that close could only happen once so I reversed the dependency

Can you elaborate?  I'm interested :)
