### ISSUE TITLE
Consider providing a `string.Create` method which accepts a ROS<T> or ROS<char> as state

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#30175]
Currently, `string.Create` only accepts a generic `TState` as the state, which means `ReadOnlySpan<T>` and `Span<T>` can't be used as state. In situations where, for example, the state is a stackalloc'd buffer which can't be converted to a ROM<T>. It can be unpleasantly worked around with pinning and passing pointer and length manually, but it is ugly and clunky. It seems simple enough to add

```cs
public delegate void SpanReadOnlySpanAction<TSpan, TReadOnlySpan>(Span<TSpan> span, ReadOnlySpan<TReadOnlySpan> readOnlySpan)
```

( with potentially nicer naming )

and provide a `string.Create<TState>(int length, ReadOnlySpan<TState> state, SpanReadOnlySpanAction action` that is basically the same as the current impl.

**Comment by joperezr** [comment]
In order to consider this we would need a formal API proposal with rationale and usage examples.

**Comment by Aragas** [comment]
As a workaround for people trying to solve the issue without copying the context - pinning the span via `fixed` and then passing the pointer as `IntPtr` can also work!
You can also pass the length via a tuple `((IntPtr) pOutput, length)` if needed.
```csharp
int outputLength = 128;
Span<char> output = stackalloc char[outputLength];
// Some operation on output

fixed (void* pOutput = output)
{
    var str = string.Create(outputLength, (IntPtr) pOutput, static (span, ptr) =>
    {
        new Span<char>(ptr.ToPointer(), span.Length).CopyTo(span);
    });
}
```

And if I understand correctly, it should be possible to do the same thing without pinning now
```csharp
int outputLength = 128;
Span<char> output = stackalloc char[outputLength];
// Some operation on output

ref var outputRef = ref MemoryMarshal.GetReference(output);
var outputPtr = (IntPtr) Unsafe.AsPointer(ref outputRef);
var str = string.Create(outputLength, outputPtr, static (span, ptr) =>
{
    new Span<char>(ptr.ToPointer(), span.Length).CopyTo(span);
});
```

**Comment by stephentoub** [comment]
> it should be possible to do the same thing without pinning now

Yes, e.g.
```C#
int outputLength = 128;
Span<char> output = stackalloc char[outputLength];
...
var str = string.Create(outputLength, &output, static (span, ptr) =>
{
    Span<char> output = *(ReadOnlySpan<char>*)ptr;
    ...
});
```

**Comment by dakersnar** [comment]
> In order to consider this we would need a formal API proposal with rationale and usage examples.

Closing this issue for now. If you are interested in driving it forward yourself, please feel free to open a new issue that follows the API suggestion template. Our API review process and a link to the template/good example is here:  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps.
