### ISSUE TITLE
 HttpClient still forcing spaces into Accept headers 

### ISSUE THREAD

**Issue by parxal** [dotnet/runtime#30171]
HttpClient forcing spaces into Accept headers with parameters breaking non-conforming REST.
When setting httpClient accept header.  Strings are forced with a space between the ;
This as been reported here :
https://github.com/dotnet/corefx/issues/18449
https://github.com/dotnet/corefx/issues/22472

But still happens in version 2.2
```c#
 static void Main(string[] args)
        {
            var httpClient = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Get, "http://google.com");
            request.Headers.Add("Accept", "application/json;version=1");
            var result = httpClient.SendAsync(request).Result;
            Console.ReadLine();
        }
```

If you check Fiddler, accept is : "application/json; version=1" and not "application/json;version=1" , there's a space after ; 

Unfortunately some API's don't work well with this space.  Is there any workaround?

WebRequest have the same behaviour as well. witch didn't happen in net  framework 4.5 
```c#
var webRequest = (HttpWebRequest)System.Net.WebRequest.Create($"http://google.com");
webRequest.Method = "POST";
webRequest.Accept = "application/json;version=1";
webRequest.GetResponse().GetResponseStream();
```

**Comment by carloluisito** [comment]
Is this fixed on .Net core 3.1? I can still replicate the issue.

`_httpClient.DefaultRequestHeaders.TryAddWithoutValidation("Accept", "application/vnd.airselangor.portal.api+json;channel=apiv2");`

![image](https://user-images.githubusercontent.com/33120739/132391653-5a0db25f-1273-48b4-814a-aae83902b6eb.png)

**Comment by karelz** [comment]
Per linked PR, it is addressed in .NET 5+ - see https://github.com/dotnet/runtime/pull/792#issuecomment-611125494

**Comment by karelz** [comment]
Closing as fixed (in .NET 5+) per https://github.com/dotnet/runtime/pull/792#issuecomment-611125494 -- it should be achievable via `TryAddWithoutValidation`.
We can reopen if it turns out to be incorrect.

**Comment by carloluisito** [comment]
Hi @karelz please ignore my message above seems to be there's a problem with my vscode. Anyways, it is working fine now. Thank you very much!
