### ISSUE TITLE
API Proposal: Setting to disable overlapping Timer callbacks

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#30193]
By default timer callbacks are queued to the thread pool and not waited on. This results in potentially overlapping timer callbacks firing (which can be problematic when code doesn't expect this). It seems like it would be extremely useful to have an option to disable this behavior (block overlapping calls to the callback). 

It should be a constructor parameter but Timers already have 5 constructors and I don't want to explode things. Open to ideas on how to enable this type of functionality.

cc @stephentoub @kouvel

**Comment by stephentoub** [comment]
Closing as dup of the proposed solution in https://github.com/dotnet/runtime/issues/31525.
