### ISSUE TITLE
StringInfo.ParseCombiningCharacters returns incorrect values on Linux

### ISSUE THREAD

**Issue by leppie** [dotnet/runtime#302]
```
var c = StringInfo.ParseCombiningCharacters("लो");
Console.WriteLine(c.Length);
```
The following prints 2 on Windows, but 1 on Linux (Ubuntu 19.04 x64). (Mono also prints 1)

**Comment by tarekgh** [comment]
@GrabYourPitchforks would this be fixed by your coming changes?

**Comment by GrabYourPitchforks** [comment]
Yes, this would be addressed by https://github.com/dotnet/runtime/pull/328. See in particular [UAX\#29](https://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules), Sec. 3.1.1, Rule GB9a, which handles this case.

I agree that it would be good to expose a new allocation-free API for this. The PR I have open introduces such an API, but it's internal-only for now because we haven't gone through an API review process.

(For reference, the correct answer should be __1__.)

**Comment by tarekgh** [comment]
Thanks @GrabYourPitchforks I assigned this issue to you so you can close it when you merge your changes.

**Comment by leppie** [comment]
> (For reference, the correct answer should be **1**.)

Why is the answer 1? `"लो"` is not a single code point as `StringInfo` is meant to iterate over. I used the static method just to show the inconsistency.

**Comment by GrabYourPitchforks** [comment]
StringInfo isn't meant to iterate over code points; it's meant to iterate over graphemes. In the 2-char string you provided in your sample, the second char is U+094B DEVANAGARI VOWEL SIGN O, which combines as a diacritic with the preceding consonant. So the two chars together are intended to be a single grapheme. See also the "Grapheme_Cluster_Break" property of https://unicode.org/cldr/utility/character.jsp?a=094b&B1=Show for more information.

**Comment by leppie** [comment]
Thanks. Not sure where I read it as code points, but clearly I read wrong. :D

Still an inconsistency.

**Comment by GrabYourPitchforks** [comment]
Fixed by https://github.com/dotnet/runtime/pull/328.

**Comment by jzabroski** [comment]
@GrabYourPitchforks Just curious, what versions of .NET can I use the allocation-free API from?  Thanks for your awesome work!

**Comment by GrabYourPitchforks** [comment]
@jzabroski The allocation-free APIs aren't available in any framework version yet. If there are any status updates they'll be posted to https://github.com/dotnet/runtime/issues/28704. Feel free to comment there about the APIs you'd like to see.

**Comment by jzabroski** [comment]
> (For reference, the correct answer should be **1**.)

Also, just to clarify, I think what you're saying here is that this issue should be retitled as "StringInfo.ParseCombiningCharacters returns incorrect values on **Windows**."  When I ran the code on Windows 10 Pro using legacy .NET Framework, I got 1.  .NET Core on Windows was the only scenario I got 2.
