### ISSUE TITLE
Will DateTime.Parse be able to deal with nanoseconds?

### ISSUE THREAD

**Issue by goldenbull** [dotnet/runtime#30204]
# Issue Title

`DateTime` can not deal with the fraction of second more than 7 digits.

# General

Scientific applications often need to handle timestamp with precision of nanosecond. Although the `DateTime` datatype do not need to actually save the nanosecond precision, it could be very helpful if `DateTime.ToString` and `DateTime.ParseExact (and other parser methods)` could generate and recognize nanoseconds.
Just think about `double.Parse` , `double.Parse("1.12345678901234567890123")` will return `1.12345678901235`, similarly, it is reasonable if `DateTime.ParseExact("20190705 10:20:30.123456789", "yyyyMMdd HH:mm:ss.fffffffff", null)` returns `2019-07-05 10:20:30.1234568`

**Comment by joperezr** [comment]
Seems like this issue was originally a question which was answered so I'm closing this for now. Feel free to reopen if there is anything that needs to be done on the BCL side.
