### ISSUE TITLE
Xml resources have invalid formatter

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#30218]
i.e. https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/Resources/Strings.resx#L1722

`{facets}` instead of i.e. `{0}`. This is likely causing some random exceptions to some people

**Comment by mrj001** [comment]
I'd like to tackle this as a first contribution.  I was not able to find any way to claim this issue.  I think I need to be added for this to be assigned to me.

I've created pull request #33890 for one of the 13 resources for feedback before tackling all of them.

**Comment by danmosemsft** [comment]
Hi @mrj001 glad to have you on board. I assigned you this issue.
