### ISSUE TITLE
Improve JsonException.Path accuracy

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#30259]
Per discussion about JSON path support, the accuracy may be "off by one" when referencing arrays in certain conditions. See https://github.com/dotnet/corefx/pull/37938#discussion_r296458694.

This is essentially related to reader functionality, since the deserializer doesn't handle the parsing.

**Comment by layomia** [comment]
Merging this with https://github.com/dotnet/runtime/issues/31955.
