### ISSUE TITLE
Support modifying (rather than replacing) already-initialized properties and fields when deserializing

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#30258]
Per comment in https://github.com/dotnet/corefx/issues/38435#issuecomment-504686914 and the original design before "replace" semantics in https://github.com/dotnet/corefx/pull/39442 was added is to allow a collection to:
- Not have a property setter.
- Previously instantiated from POCO ctor.
- Allow that collection to have elements added to during deserialization.

The existing semantics ignore the property on deserialization.

To turn on this mode, a custom attribute could be created to enable and placed on the property, and\or a global option. Doing this by default would be a breaking change (if added post 3.0).

cc @JamesNK @YohDeadfall

**Comment by Sandeep321** [comment]
Any updates on the roadmap for this. Any idea on when this could be released?

**Comment by steveharter** [comment]
This is still a valid issue; it just hadn't been prioritized for 5.0 (yet).

Strawman proposal:
- Add a new attribute to place on properties (`JsonObjectCreation`).
- Add a new JsonSerializerOptions (`JsonObjectCreation`) to define the global behavior. 

The attribute and option would likely be an enum similar to https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_ObjectCreationHandling.htm (Auto, Reuse, Replace) except that the default would be `Replace`.

Note this attribute works on objects as well as collections.

For the re-use cases, I don't think we ever want to attempt to call a "Clear" method on collections (we always append).

**Comment by gaensebluemchenritter** [comment]
With the behaviour as of now we actually need to suppress CA2227 for collections in our DTOs we want to deserialize into. So the out of the box coding standards actually prevent usage of the Deserializer ...

From where I'm standing an additional JsonSerializerOption would probably be the best way to proceed.

**Comment by layomia** [comment]
From @dbc2 in https://github.com/dotnet/runtime/issues/32197#issue-564328723:

> If I have a **get-only, preallocated** `[JsonExtensionData]` property on my model, then the dictionary will be serialized successfully, but will silently fail to be populated on deserialization. This seems wrong. Details as follows.
> 
> Say I have the following model:
> 
> ```
> public class Model
> {
>     [JsonExtensionData]
>     public Dictionary<string, object> ExtensionData { get; } = new Dictionary<string, object>();
> }
> ```
> 
> And the following test method:
> 
> ```
> public class TestClass
> {
>     [TestMethod]
>     public void TestReadOnlyExtensionDataProperty()
>     {
>         var model1 = new Model { ExtensionData = { { "item", "item value" } } };
> 
>         var json = JsonSerializer.Serialize(model1);
> 
>         Debug.WriteLine(json); // Prints {"item":"item value"} as expected
> 
>         Assert.AreEqual(json, "{\"item\":\"item value\"}"); // Passes.
> 
>         var model2 = JsonSerializer.Deserialize<Model>(json);
> 
>         Assert.AreEqual(model1.ExtensionData.Count, model2.ExtensionData.Count, "model2.ExtensionData.Count"); // FAILS!
>     }
> }
> ```
> 
> Then the first assert will succeed, because `model1` is correctly serialized as `{"item":"item value"}`. However, the second assert fails, because `model2.ExtensionData` is empty when deserialized.
> 
> Demo fiddle 1 [here](https://dotnetfiddle.net/HvBx9c) reproducing the problem.
> 
> Conversely, Json.NET is able to round-trip this model successfully, see demo fiddle 2 [here](https://dotnetfiddle.net/cvEuVy).
> 
> And if I modify `Model.ExtensionData` to have a setter **that throws an exception**, then deserialization also succeeds:
> 
> ```
> public class Model
> {
>     readonly Dictionary<string, object> extensionData = new Dictionary<string, object>();
> 
>     [JsonExtensionData]
>     public Dictionary<string, object> ExtensionData { get => extensionData; set => throw new NotImplementedException(); }
> }
> ```
> 
> Demo fiddle 3 [here](https://dotnetfiddle.net/zp7OEh), which passes.
> 
> This seems wrong. Since the dictionary is preallocated it should be populated successfully during deserialization even without a setter -- especially since the setter isn't actually called.

**Comment by layomia** [comment]
*This work should also consider sub-objects without setters, not just collections.*

From @johncrim in https://github.com/dotnet/runtime/issues/3145:

> If a parent object doesn't contain setters for all sub-object properties, the sub-objects are not deserialized. This is inconsistent with other JSON serializers, and seems like a major oversight - current behavior requires a large amount of mutability in the deserialized object model.
> 
> It's also a normal pattern to provide sub-objects with default values before deserialization.
> 
> For example, in this class, the `SubObject1` property won't be deserialized, and no exception is thrown.
> 
> ```cs
>     public class Container1
>     {
>         // Not deserialized due to missing setter. No exceptions thrown.
>         public SubObject1 SubObject1 { get; } = new SubObject1();
>     }
> ```
> 
> Full test project:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <Description>Unit tests demonstrating JsonSerializer bugs</Description>
>     <TargetFramework>netcoreapp3.0</TargetFramework>
>     <Platform>x64</Platform>
>     <Platforms>x64</Platforms>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
>     <PackageReference Include="xunit" Version="2.4.1" />
>     <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" PrivateAssets="All"/>
>   </ItemGroup>
> 
> </Project>
> ```
> 
> ```cs
> using System.Text.Json;
> using Xunit;
> 
> namespace JsonSerializer_SubObjects
> {
>     public class JsonSerializerTest
>     {
>         [Fact] // Fails
>         public void DeserializesSubObjectsWithoutSetters()
>         {
>             const string jsonFooValue = "str1";
>             var json = "{ \"SubObject1\": { \"Foo\": \"" + jsonFooValue + "\" }}";
> 
>             var c1 = JsonSerializer.Deserialize<Container1>(json);
> 
>             // BUG dotnet/corefx#1: Value isn't deserialized (this assertion fails)
>             Assert.Equal(jsonFooValue, c1.SubObject1.Foo);
>             // BUG dotnet/corefx#2: If value can't be deserialized, exception should be thrown
>         }
> 
>         [Fact] // Passes
>         public void DeserializesSubObjectsWithSetters()
>         {
>             const string jsonFooValue = "str1";
>             var json = "{ \"SubObject1\": { \"Foo\": \"" + jsonFooValue + "\" }}";
> 
>             var c2 = JsonSerializer.Deserialize<Container2>(json);
> 
>             Assert.Equal(jsonFooValue, c2.SubObject1.Foo);
>         }
> 
>     }
> 
>     public class Container1
>     {
>         // Not deserialized due to no setter. No exceptions thrown.
>         public SubObject1 SubObject1 { get; } = new SubObject1();
>     }
> 
>     public class Container2
>     {
>         public SubObject1 SubObject1 { get; set; } = new SubObject1();
>     }
> 
>     public class SubObject1
>     {
>         public string Foo { get; set; } = "foo";
>     }
> }
> ```

**Comment by layomia** [comment]
From @componentspace in https://github.com/dotnet/runtime/issues/35388:

> In the following code Newtonsoft.Json correctly deserializes but System.Text.Json doesn't with the dictionary being empty. If the IDictionary<string, string> property has a setter, the deserialization works. However, I don't control the class that requires serialization/deserialization and it includes IDictionary<string, string> properties with getters only.
> 
> `
> using Newtonsoft.Json;
> using System.Collections.Generic;
> using System.Text.Json;
> 
> namespace TestConsoleApp
> {
> class Test
> {
> public IDictionary<string, string> Items { get; } = new Dictionary<string, string>();
> }
> 
> ```
> class Program
> {
>     static void Main(string[] args)
>     {
>         var test = new Test();
>         test.Items["a"] = "1";
>         test.Items["b"] = "2";
> 
>         var json = System.Text.Json.JsonSerializer.Serialize(test);
> 
>         // Dictionary is empty.
>         var test2 = System.Text.Json.JsonSerializer.Deserialize<Test>(json);
> 
>         // Correctly deserialized.
>         var test3 = JsonConvert.DeserializeObject<Test>(json);
>     }
> }
> ```
> 
> }
> 
> `

**Comment by rrelyea** [comment]
Would really love to be able to follow [.net design guidelines for collections](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values) to not have settable collection properties.

Strongly believe this should be the default behavior.
If it wasn't supported...i would have expected an exception if the property was set in json, but the collection had no setter.

XAML supported save/load of objects like this w/o needing the setter or any extra attribute.
(i was architect of system.xaml)

**Comment by layomia** [comment]
From @Symbai in https://github.com/dotnet/runtime/issues/38705:

> ### Description
> The pull request #34675 added support for private setters. And the default value for `IgnoreReadOnlyProperties` is `false`. So I would have assumed something like: `[JsonInclude] public ObservableCollection<int> MyInt { get; } = new ObservableCollection<int>();` would work but it does not. It still requires the `private set;` to explicit written.
> 
> ### Configuration
> * .NET Core 5.0 (5.0.100-preview.5.20279.10)
> 
> ### Other information
> ```
>     class Program
>     {
>         public static JsonSerializerOptions Options =>  new JsonSerializerOptions {IgnoreReadOnlyProperties = false};
>         static void Main(string[] args)
>         {
>             var readonlySetter = new MyClass_Readonly();
>             readonlySetter.MyInt.Add(1);
>             var readonlyJson = JsonSerializer.Serialize(readonlySetter);
>             Console.WriteLine("Readonly JSON: " + readonlyJson);
>             var newReadonlySetter = JsonSerializer.Deserialize<MyClass_Readonly>(readonlyJson);
>             Console.WriteLine("Readonly List Count: " + newReadonlySetter.MyInt.Count);
> 
>             var privateSetter = new MyClass_PrivateSetter();
>             privateSetter.MyInt.Add(1);
>             var privateJson = JsonSerializer.Serialize(privateSetter);
>             Console.WriteLine("Private JSON: " + privateJson);
>             var newPrivateSetter = JsonSerializer.Deserialize<MyClass_PrivateSetter>(privateJson);
>             Console.WriteLine("Private List Count: " + newPrivateSetter.MyInt.Count);
>         }
>     }
>     class MyClass_Readonly
>     {
>         [JsonInclude] public ObservableCollection<int> MyInt { get;  } = new ObservableCollection<int>();
>     }
>     class MyClass_PrivateSetter
>     {
>         [JsonInclude] public ObservableCollection<int> MyInt { get; private set; } = new ObservableCollection<int>();
>     }
> ```
> 
> Output:
> 
> ```
> Readonly JSON: {"MyInt":[1]}
> Readonly List Count: 0
> Private JSON: {"MyInt":[1]}
> Private List Count: 1
> ```

**Comment by layomia** [comment]
Updating the title here to generalize this to a problem where we need to modify an already initialized property or field. An equivalent to `Newtonsoft.Json`'s [ObjectCreationHandling](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_ObjectCreationHandling.htm) should help solve this issue.

**Comment by layomia** [comment]
From @mtaylorfsmb in https://github.com/dotnet/runtime/issues/39630:

> I couldn't find this written up anywhere in here so if it is a dup then feel free to close this one.
> 
> As documented System.Text.Json always creates a new object and assigns it to the public settable fields. This is different than Json.NET and introduces problems that may not be easily solvable. Here is a simple example.
> 
> ```cs
> public class Template
> {
>     public Dictionary<string, string> DataFields { get; set; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
> }
> ```
> 
> The `Template` class is used in a REST API wrapper around a third party library. It allows a series of key-value data fields to be provided. This information is sent to a lower level API that is case sensitive on keys. The caller of the API knows the case for the fields in its template and sets them accordingly.
> 
> There are 2 problems with how this works with System.Text.Json.
> 
> 1. The field has to be settable otherwise the deserializer won't set it. This makes it so that calling code can mess this up as well but we could isolate the client and server side types to protect this somewhat. Ideally we shouldn't need a setter to set dictionaries unless the property wasn't initialized.
> 2. The deserializer will create a case sensitive comparer irrelevant. We have no control over this easily.
> 
> Note: This is just one example. There could be any # of other types with other scenarios.
> 
> The recommended workarounds, while doable, create more work that shouldn't be necessary.
> 
> 1. Creating a value converter would work if all dictionaries in your code work the same way or if you used separate serializer settings for each one but that is inefficient and would require a separate converter for each combination (plus the serializer options).
> 2. Create a derived type from Dictionary that calls the base constructor. This is recommended for types that don't have public default constructors. But this may introduce additional fields in the serializer/deserializer JSON that are unexpected depending upon how the serializer treats dictionaries.
> 
> The proposal I make is that the deserializer should, out of the box without the need for any additional code, allow fields to be initialized by the owning type AND not overwrite the object if it is not null. This would save the allocation if the property is already initialized, allow for the owning type to ensure the object is initialized properly and eliminate the need for a setter on a field that shouldn't be settable anyway. The current workarounds add undue complexity and potential risk with no real value. If performance is a concern (although I cannot imagine a null check being expensive) then make it an opt-in option in the serializer.

**Comment by layomia** [comment]
From @CodeBlanch in https://github.com/dotnet/runtime/issues/30688:

> Adds a new attribute JsonDeserializeAttribute which turns on a new feature to deserialize into read-only properties.
> 
> # Proposed API
> ```cs
>     /// <summary>
>     /// Flags a private property for inclusion during deserialization.
>     /// </summary>
>     /// <remarks>
>     ///   <para>
>     ///     By default only properties with public get &amp; set operations defined will be deserialized.
>     ///     Use <see cref="JsonDeserializeAttribute"/> to indicate the instance returned by the get method should be used
>     ///     to deserialize a property.
>     ///   </para>
>     ///   <para>
>     ///     For collections the instance returned should implement <see cref="System.Collections.IList"/>. For dictionaries
>     ///     the instance returned should implement <see cref="System.Collections.IDictionary"/>. In both cases the instance
>     ///     should not be read-only or fixed-size (arrays).
>     ///   </para>
>     ///   <para>
>     ///     <see cref="JsonDeserializeAttribute"/> is ignored when a public set operation is defined or property is a value type.
>     ///   </para>
>     /// </remarks>
>     [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
>     public sealed class JsonDeserializeAttribute : JsonAttribute
>     {
>         /// <summary>
>         /// Initializes a new instance of <see cref="JsonDeserializeAttribute"/>.
>         /// </summary>
>         public JsonDeserializeAttribute() { }
>     }
> ```
> 
> # Rationale & Usage
> Consider this class...
> 
> ```cs
>         public class SimpleTestClassUsingJsonDeserialize
>         {
>             [JsonDeserialize]
>             public SimpleTestClass MyClass { get; } = new SimpleTestClass();
>         }
> ```
> 
> ...and this json…
> 
> ```cs
> {"MyClass":{"MyInt32":18}}
> ```
> 
> Previously the MyClass property would be ignored during deserialization because it does not have a public setter. What [JsonDeserialize] does is direct the (de)serializer to use the getter to access the instance and then deserialize on to that.
> 
> Why do this? Primarily to allow people to use patterns that satisfy [CA2227](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only?view=vs-2019). It also helps people using C#8 nullable reference.
> 
> Example of a class expressed precisely:
> 
> ```cs
> public class Document
> {
>         public ChildDoc? Parent { get; set; }
> 
>         [JsonDeserialize]
>         public IEnumerable<ChildDoc> Children { get; } = new List<ChildDoc>();
> }
> ```
> 
> We can access Children without fear of null.
> 
> Same class with trade-offs to make existing API happy:
> 
> ```cs
> 	public class Document
> 	{
> 		public ChildDoc? Parent { get; set; }
> 
> #pragma warning disable CA2227 // Collection properties should be read only
> 		public List<ChildDoc>? Children { get; set; }
> #pragma warning restore CA2227 // Collection properties should be read only
> 	}
> ```
> 
> Access to Children now needs to have null checking. If we define like this...
> 
> ```cs
> public List<ChildDoc> Children { get; set; } = new List<ChildDoc>();
> ```
> 
> We're newing up an instance that will be thrown away during deserialization, and someone could come along and replace the value leading to inconsistent state. A little less performant and a little more error-prone.
> 
> # Details
> In order to safely deserialize into these properties some strict rules are in place. Collections must be of type IList, not fixed-size, and not read-only. Dictionaries must by of type IDictionary, not fixed-size, and not read-only. Whatever exists before serialization will be replaced by deserialization.
> 
> # Considerations
> Obviously this is meant for reference types. If you use this attribute on a value field it can't really do anything with that. Should it throw an exception when it is building the property info? Current implementation ignores value types.
> 
> I went with the attribute primarily for backwards compatibility. People can opt-in to this if they want it.
> 
> # Implementation
> See [dotnet/corefx#40517](https://github.com/dotnet/corefx/pull/40517)

**Comment by layomia** [comment]
From offline discussion with @GrabYourPitchforks about JsonSerializer support for init-only properties:

> Something you might want to consider: skipping init-only properties when you're patching an existing object. Only allow setting them when you've constructed a fresh instance of the object.

**Comment by JulienM28** [comment]
Is there any chance to have ths fixed for .Net 5.0 ?

**Comment by layomia** [comment]
@JulienM28 due to time constraints, this won't come in .NET 5. It will be considered for .NET 6.

**Comment by paulodero** [comment]
@layomia Do you know when this feature support would be made available?

**Comment by julealgon** [comment]
@layomia 
> Adds a new attribute JsonDeserializeAttribute which turns on a new feature to deserialize into read-only properties.

I think requiring a special attribute on each property is a very intrusive solution. I'd personally not be very happy if that was the only way to configure the serializer with this behavior. It pollutes the model and could be seen as a SRP violation since the model shouldn't necessarily know how it will be serialized/deserialized and by which library.

I'd suggest at least having a way to configure this on the serializer itself as an option, and perhaps have the attribute approach as a secondary way of doing it.

**Comment by Shayan-To** [comment]
Will this find its way into .NET 6?

**Comment by layomia** [comment]
@julealgon - yes a global option on `JsonSerializerOptions` is desirable here, along with a per-property/field attribute.

---

@Shayan-To - it is proposed for .NET 6.0, but not committed. Will try to get it in, but it will not stop the release of .NET 6.0 if we don't. See https://github.com/dotnet/runtime/issues/45190.

**Comment by julealgon** [comment]
@layomia can you elaborate why this is being tied to framework releases? Isn't it a separate package now that can be updated independently?

**Comment by qsdfplkj** [comment]
How about moving the initiazlization to the constructor?
 
 public class Data
    {
        [JsonConstructor]
        public Data(List<int> values)
        {
            _values = values ?? new List<int>();
        }

        private List<int> _values;

        public List<int> Values
        {
            get { return _values; }
        }
    }

**Comment by eiriktsarpalis** [comment]
Triage: we want to eventually add this feature but unfortunately it won't fit our schedule for .NET 6, moving to 7.0.0 milestone.

**Comment by gaensebluemchenritter** [comment]
Which means the only way to go when using 3rd party models is to use Newtonsoft Json. Which is a bummer, honestly. So moving over from Newtonsoft (reducing 3rd party dependencies) is out of question for those of us who do not exclusively use their own model definitions (which btw. have to break MS’s own rule of not having a setter for collections). So we have to hope that Newtonsoft is still around through .NET 6 ...

Nonetheless: whenever this gets implemented, please do it in a way that it can be used for 3rd party models, otherwise we still face the same problem as now. With our own models we can mitigate this issue rather easily by using setters for collections in our dtos, which reside in their own projects, and set the GlobalSuppressions accordingly; it‘s 3rd party models that effectively stop us from switching to System.Text.Json

**Comment by johncrim** [comment]
I don't rant much about .NET, because it's fantastic overall. But it's ridiculous that baseline features like this weren't included in .NET Core 3.0, let alone .NET 6.

I like the performance of System.Text.Json, and some of the internal design is good, but the functionality is quite limited. Seems like there's a need for a better open-source JSON serializer (and/or generalized serialization framework) ...

**Comment by Shayan-To** [comment]
This is really a much needed feature. Can't it be released in a minor release of .NET 6 before .NET 7 arrives?

**Comment by rajeshaz09** [comment]
You are promoting to use STJ but not feature rich like NSJ.  We are waiting to remove NSJ in 20 plus microservices since 2 years  but this feature is blocking us.

**Comment by rajeshaz09** [comment]
After 3 years,  comment from Microsoft.... We tried had but this feature will not be part of .Net 9. We will consider in .net 10

**Comment by eiriktsarpalis** [comment]
This should likely be tackled in conjunction with #63686 cc @krwq

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/grpc/grpc-dotnet/issues/167

**Comment by JamesNK** [comment]
Something to consider with this feature is adding `Populate` methods on JsonSerializer. e.g.

```csharp
var user = new User();
JsonSerializer.Populate(json, user.Roles);
```

https://www.newtonsoft.com/json/help/html/PopulateObject.htm

**Comment by perason** [comment]
> Something to consider with this feature is adding `Populate` methods on JsonSerializer. e.g.
> 
> ```cs
> var user = new User();
> JsonSerializer.Populate(json, user.Roles);
> ```
> 
> https://www.newtonsoft.com/json/help/html/PopulateObject.htm
> 
> Usage in the real world: https://cs.github.com/?q=jsonconvert.populateobject+language%3AC%23&p=1&scopeName=All+repos

There's a [thread for that already](https://github.com/dotnet/runtime/issues/29538), created just a couple of months before a [post I added at StackOverflow](https://stackoverflow.com/questions/56835040/net-core-3-0-jsonserializer-populate-existing-object)

**Comment by krwq** [comment]
FWIW it will be possible to partially address this with https://github.com/dotnet/runtime/issues/63686 - you will be able to use `Set` on the JsonPropertyInfo but it will create an extra allocation (first it will create a collection using default constructor and you will be able to move values into the existing collection) but you will be able to achieve most of the scenarios.

My initial prototype had callback to address this specific scenario exactly but it needs more design as it wouldn't work with async + some other tiny issues so for now at least this will make life slightly easier

**Comment by eiriktsarpalis** [comment]
> but it will create an extra allocation (first it will create a collection using default constructor and you will be able to move values into the existing collection) but you will be able to achieve most of the scenarios.

How so? Wouldn't it be possible to (roughly) do something like the following in the object converter
```C#
// inside the property deserialization loop of ObjectConverter
if (jsonPropertyInfo.ReuseInitializedValue && jsonPropertyInfo.Get(parentObject) is object initializedValue)
{
    state.Current.ReturnValue = initializedValue; // signal to the converter of the property type that the type has been initialized.
}
```

**Comment by krwq** [comment]
I'm unassigning myself since I don't work on this now and we don't have specific plans for 8.0 yet

**Comment by krwq** [comment]
I'm closing this issue in favor of https://github.com/dotnet/runtime/issues/78556 - anyone interested please share your thoughts below so that we can adjust proposal if needed.
