### ISSUE TITLE
Bi-modal execution time of System.Net.Http outerloop tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#30257]
When running the System.Net.Http tests on my local Windows machine with outerloop, the tests either take ~70 seconds or ~170 seconds.  It would be nice to figure out what's sometimes causing the ~100 second delay (which is coincidentally or not the same as the default request timeout on HttpClient) and fix it.

**Comment by ManickaP** [comment]
Removing the backlog labels, given the age of the issue, this is probably many times different than it was then so I consider this correctly closed. We can always re-open if we observe similar behavior again.
