### ISSUE TITLE
System.Text.Json: (De)serialization support for quoted numbers 

### ISSUE THREAD

**Issue by NickCraver** [dotnet/runtime#30255]
<details>
<summary>
Original proposal by @NickCraver (click to view)
</summary>

Apologies if this issue exists already...I hunted and couldn't find one.

I've been trying to switch a lot of usages over to `System.Text.Json` from Newtonsoft and Jil, but a recurring theme is handling external APIs and their not-quite-right returns of JSON.

Unfortunately, an example I'm seeing over and over is:
```json
{ "field":"12345" }
```

They're numbers, but as strings. `int`, `double`, `decimal`, whatever. It happens _all the time_. And since it's someone's API, it's unlikely we'll get the world to fix this.

Note: this is something Newtonsoft handles _by default_, which is why I don't think most people realize it's an issue.

Is there any chance we can let `System.Text.Json` handle number types being quoted when deserializing? Something a user opts-into via `JsonSerializerOptions`?

Small repro example:
```c#
void Main()
{
	JsonSerializer.Parse<Foo>(@"{""Bar"":""1234""}");
}
public class Foo
{
	public int Bar { get; set; }
}
```

cc @ahsonkhan @steveharter 
</details>

---

_Edited by @layomia:_

Users want to be able to deserialize JSON strings into number properties. Scenarios include deserializing "NaN", "Infinity" and "-Infinity" (https://github.com/dotnet/runtime/issues/31024).

We should add an option to enable this scenario, and possibly allow serializing numbers as strings.

These semantics allow better interop with various API endpoints accross the web.

## API Proposal

```cs
namespace System.Text.Json
{
    public partial sealed class JsonSerializerOptions
    {
        public JsonNumberHandling NumberHandling { get; set; }
    }
}

namespace System.Text.Json.Serialization
{
    [Flags]
    public enum JsonNumberHandling : byte
    {
        /// <summary>
        /// No specified number handling behavior. Numbers can only be read from <see cref="JsonTokenType.Number"/> and will only be written as JSON numbers (without quotes).
        /// </summary>
        None = 0x0,
        /// <summary>
        /// Numbers can be read from <see cref="JsonTokenType.String"/>. Does not prevent numbers from being read from <see cref="JsonTokenType.Number"/>.
        /// </summary>
        AllowReadingFromString = 0x1,
        /// <summary>
        /// Numbers will be written as JSON strings (with quotes), not as JSON numbers.
        /// </summary>
        WriteAsString = 0x2,
        /// Floating point constants represented as <see cref="JsonTokenType.String"/> tokens
        /// such as "NaN", "Infinity", "-Infinity", can be read when reading, and such CLR values
        /// such as <see cref="float.NaN"/>, <see cref="double.PositiveInfinity"/>, <see cref="float.NegativeInfinity"/> will be written as their corresponding JSON string representations.
        AllowNamedFloatingPointLiterals = 0x4
    }

    public partial sealed class JsonNumberHandlingAttribute : JsonAttribute
    {
        public JsonNumberHandling Handling { get; }
    
        public JsonNumberHandlingAttribute(JsonNumberHandling handling)
        {
            Handling = handling;
        }
    }
}
```

#### Allow reading numbers from strings; write numbers as strings.

```cs
public class ClassWithInts
{
    public int NumberOne { get; set; }
    public int NumberTwo { get; set; }
}

var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.WriteAsString 
};

string json = @"{""Number1"":1,""Number2"":""2""}";

ClassWithInts @class = JsonSerializer.Deserializer<ClassWithInts>(json, options);
Console.WriteLine(@class.NumberOne); // 1
Console.WriteLine(@class.NumberTwo); // 2

json = JsonSerializer.Serialize(@class, options);
Console.WriteLine(json); // @"{""Number1"":""1"",""Number2"":""2""}";
```

#### Allow reading numbers from floating point constants; write floating point constants

Given a class:

```cs
public class ClassWithNumbers
{
    public int IntNumber { get; set; }
    public float FloatNumber { get; set; }
}
```

Without the new option, reading floating-point-constant representations fails:

```cs
string json = @"{""IntNumber"":1,""FloatNumber"":""NaN""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json);

// Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Single. Path: $.FloatNumber | LineNumber: 0 | BytePositionInLine: 34.
```

Writing also fails:

```cs
var obj = new ClassWithNumbers
{
    IntNumber = -1,
    FloatNumber = float.NaN
};

string json = JsonSerializer.Serialize(obj);

// Unhandled exception. System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON.
```

With the new option, reading floating-point-constant representations works:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals
};

string json = @"{""IntNumber"":1,""FloatNumber"":""NaN""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);

Console.WriteLine(obj.IntNumber); // 1
Console.WriteLine(obj.FloatNumber); // NaN
```

Writing floating-point-constant representations also works:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals
};

var obj = new ClassWithNumbers
{
    IntNumber = -1,
    FloatNumber = float.NaN
};

string json = JsonSerializer.Serialize(obj, options);
Console.WriteLine(json); // {"IntNumber":-1,"FloatNumber":"NaN"}
```

#### Allow reading numbers from string; support reading and writing floating point constants

Reading:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals
};

string json = @"{""IntNumber"":""1"",""FloatNumber"":""NaN""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);

Console.WriteLine(obj.IntNumber); // 1
Console.WriteLine(obj.FloatNumber); // NaN
```

Writing:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.WriteAsString | JsonNumberHandling.AllowNamedFloatingPointLiterals
};

var obj = new ClassWithNumbers
{
    IntNumber = -1,
    FloatNumber = float.NaN
};

string json = JsonSerializer.Serialize(obj, options);
Console.WriteLine(json); // {"IntNumber":-1,"FloatNumber":"NaN"}
```

#### Write numbers as strings; support reading and writing floating point constants

Reading:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.WriteAsString | JsonNumberHandling.AllowNamedFloatingPointLiterals
};
```

```cs
string json = @"{""IntNumber"":""1""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);

Console.WriteLine(obj.IntNumber); // 1
Console.WriteLine(obj.FloatNumber); // 0
```

```cs
string json = @"{""IntNumber"":""1"",""FloatNumber"":""NaN""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);

// Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.IntNumber | LineNumber: 0 | BytePositionInLine: 16.
```

Writing:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.WriteAsString | JsonNumberHandling.AllowNamedFloatingPointLiterals
};

var obj = new ClassWithNumbers
{
    IntNumber = -1,
    FloatNumber = float.NaN
};

string json = JsonSerializer.Serialize(obj, options);
Console.WriteLine(json); // {"IntNumber":"-1","FloatNumber":"NaN"}
```

#### Read semantics are the same as the serializer's default (no quotes)

For example, integers cannot have decimal places:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowReadingFromString
}

string json = @"{""IntNumber"":""1.0""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);
// Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.IntNumber | LineNumber: 0 | BytePositionInLine: 17.
```

Similarly, there can't be any leading or trailing trivia:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowReadingFromString
}

string json = @"{""IntNumber"":""1a""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);
// Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.IntNumber | LineNumber: 0 | BytePositionInLine: 15.
```

Leading or trailing whitespace is also not allowed:

```cs
var options = new JsonSerializerOptions
{
    NumberHandling = JsonNumberHandling.AllowReadingFromString
}

string json = @"{""IntNumber"":""1 ""}";
ClassWithNumbers obj = JsonSerializer.Deserialize<ClassWithNumbers>(json, options);
// Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.IntNumber | LineNumber: 0 | BytePositionInLine: 15.
```

Note that formats such as the currency and percentage formats are not allowed. Commas (,), the percent symbol (%), and underscores (_) are not permitted in input strings.

### Newtonsoft compat

- Newtonsoft.Json allows implicit conversions from strings to numbers on deserialization, i.e, no custom logic or setting is required. We will require that users explictly opt in to this behavior.
- Newtonsoft.Json does not provide a built-in way to serialize numbers as strings. Custom logic, e.g. a custom converter needs to provided for this behavior. This proposal includes an easy way to specify this behavior.

### Read/write semantics
- The number reading and writing behavior of this feature is exactly the same as if no quotes were specified, except that surrounding quotes can be allowed on deserialization, and can be written on serialization.
    - Reading/writing is not culture aware (i.e InvariantCulture). A custom converter has to be specified for culture-aware handling.
    - The ["G17" standard numeric format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-general-g-format-specifier) is used when reading and writing `double` representations.
    - The ["G9"](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-general-g-format-specifier) standard format is used when reading and writing `float` representations.
    - Percentage and currency formats are not supported.
- Numbers represented as `JsonTokenType.String` tokens will be unescaped if needed when deserializing. This is in keeping with other string-based parsing for types like `DateTime` and `Guid`.
- Only the literal "NaN", "Infinity", and "-Infinty" values are allowed. This is in keeping with the most common variations on the web. The matching is case-sensitive. We can be more permissive in the future, based on user feedback.

**Comment by JohnGalt1717** [comment]
I've added the example above to JsonSerializerOptions for the AddJsonOptions on mvc but it isn't called when sent a string that should be deserialized as a number.  Does this work with .net core 3.1 final?

**Comment by rodion-m** [comment]
Here is an improved code from @manigandham:
```csharp
    public class StringToLongJsonConverter : JsonConverter<long>
    {
        private readonly bool _writeValueAsString;

        public StringToLongJsonConverter(bool writeValueAsString)
        {
            _writeValueAsString = writeValueAsString;
        }

        /// <summary>
        ///     Reads long value from quoted string
        /// </summary>
        public override long Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.String)
            {
                var span = reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan;
                if (Utf8Parser.TryParse(span, out long number, out var bytesConsumed) && span.Length == bytesConsumed)
                    return number;

                var strNumber = reader.GetString();
                if (long.TryParse(strNumber, out number))
                    return number;

                throw new InvalidOperationException($"{strNumber} is not a correct long value!")
                {
                    /*
                     * Here is a source from internal const System.Text.Json.ThrowHelper.ExceptionSourceValueToRethrowAsJsonException
                     * to restore a detailed info about current json context (line number and path)
                     */
                    Source = "System.Text.Json.Rethrowable"
                };
            }

            return reader.GetInt64();
        }

        /// <summary>
        ///     Writes a long value as number if <see cref="_writeValueAsString" /> is false
        ///     or as string if <see cref="_writeValueAsString" /> is true
        /// </summary>
        public override void Write(Utf8JsonWriter writer, long value, JsonSerializerOptions options)
        {
            if (_writeValueAsString)
                writer.WriteStringValue(value.ToString());
            else
                writer.WriteNumberValue(value);
        }
    }
```

**Comment by JohnGalt1717** [comment]
Where does this get registered for it to work with WebAPI REST?

**Comment by VictorioBerra** [comment]
@rodion-m Someone should toss that in a NuGet package for super easy consumption.

**Comment by VictorioBerra** [comment]
Also, can we make sure the converter supports nullable numbers as well as decimals, longs, integers?

**Comment by JohnGalt1717** [comment]
This should just be fixed in .NET 5 so that it just works properly like Newtonsoft.json and handles nullables properly too.

And allows us to set default serialization and deserialization options so that it doesn't have to be passed with every use.

**Comment by VictorioBerra** [comment]
Oh, and bools! That worked before as well.

**Comment by VictorioBerra** [comment]
Another thing, @rodion-m `Utf8Parser.TryParse` returns false for `""`. Which will throw. Before, sending `""` in JSON for a number worked just fine. Your code, and the new .NET 5 fix should account for this.

**Comment by JohnGalt1717** [comment]
Shouldn't need a nuget package. This should have been baked in from day one just like serialization defaults etc. It should never have been released until it had parity with Newtonsoft.json.

But since unwise decisions were made, this should be iterated on quickly and fixed in the core product.

**Comment by logic01** [comment]
One more thumbs up for System.Text.Json doing the work native like Newtonsoft.Json. We should not need to decorate every property in our models. We had to replace System.Text.Json with Newtonsoft to avoid the fiasco of code bloat due to custom converters for ever numeric type. Not to mention the communication issue of informing every new developer on our team that they have to tag their properties with our custom converters. 

Easy to use, hard to misuse.

**Comment by Jozkee** [comment]
> @NickCraver I think it's just "there's a whole lot of policy here, and we would need to completely spec it out, and we're trying to be feature complete 30 days ago... so this isn't required for v1 (.NET Core 3.0)"
> 
> * Is there an option to say if deserializing should be strict vs coercive? (Personally, I hate coercive APIs, so I would always want it in "this data better conform to schema" mode)
> * If numbers are deserialized through either JSON Number or JSON String, how are they written?
>   
>   * Do we need per property toggles other than the converters?
> * Is only invariant format supported? Or also CurrentCulture? Or CurrentUICulture?
> * How should the deserialization handle it if the property is typed as `int` but the value is the string "3.0"? Is that 3, or an exception?  (Currently (IIRC) if it's a JSON number that says 3.0 and the field is int it throws)
> * Should it ignore trailing spaces if they ended up in the string?  Leading spaces?
> * Should it support the percentage format? The currency format?
> 
> It's a simple-sounding request, but there are a lot of details and many of them are hard to change once the feature first ships. So the .NET Core 3.0 answer is "deserialization doesn't coerce numbers out of JSON strings; but the converters feature lets you effectively opt-in on a property-by-property basis".

What about escaped characters? Should we allow them or should we stick to the JSON Number spec?

For `Dictionary<float/double, >` support (https://github.com/dotnet/runtime/issues/30524), the value might include '+' e.g. `3.40282347E+38` which makes me wonder these questions:
* On serialization, should we serialize the dictionary key as is, given that a number written as a number value is not changed by the `JsonSerializerOptions.Encoder` OR should we escape '"+" given that we are writing the number as a property name (string) and hence the `Encoder` should take action and escape "+" if needed?

* On deserialization, using the same example, should we allow the escaped "+" (\u002b) only and unescape it or should we allow any amount of escaped characters and unescape them all?

**Comment by logic01** [comment]
Not to oversimplify a complex set of questions @Jozkee , but how does Newtonsoft do it? 

Newtonsoft has been the industry standard for a long time and they have answered these questions. If Microsoft want's to replace them as the industry standard then MS should provide an implementation that is as user friendly as Newtonsoft otherwise why switch?

If I switch now I have to make sure that every developer across dozens of teams, dozens of products, hundreds of microservices all conform to our company standard for serialization so all our services can communicate. In any organization of scale that is a big ask.

**Comment by terrajobst** [comment]
```C#
namespace System.Text.Json
{
    public partial sealed class JsonSerializerOptions
    {
        public JsonNumberHandling NumberHandling { get; set; }
    }
}
namespace System.Text.Json.Serialization
{
    [Flags]
    public enum JsonNumberHandling : byte
    {
        None = 0x0,
        AllowReadingFromString = 0x1,
        WriteAsString = 0x2,
        AllowNamedFloatingPointLiterals = 0x4
    }

    // Attribute targets: Field & Property
    public partial sealed class JsonNumberHandlingAttribute : JsonAttribute
    {
        public JsonNumberHandlingAttribute(JsonNumberHandling handling);
        public JsonNumberHandling Handling { get; }    
    }
}
```

**Comment by paulhickman-a365** [comment]
I'd like to this proposal include an overload on ````Utf8JsonWriter.WriteNumberValue```` to specify if it should be quoted or not. e.g.

```cs
int x= 5;
writer.WriteNumberValue(x,true) // writes "5"
writer.WriteNumberValue(x,false) // writes 5
```

This avoids having to do the extra memory allocation in
```cs
writer.WriteStringValue(x.ToString()) // writes "5"
```

and it allows you to write efficient code when the JSON schema you have to comply with has some numbers quoted but not all of them.

**Comment by layomia** [comment]
@paulhickman-a365 this issue addresses support at the serializer level only. Please open a new issue with the "API proposal" format for your suggestion for the writer to be considered.

**Comment by ironpython2001** [comment]
It seems this is a missing feature. Better to add this feature like newtonsoft.json

**Comment by layomia** [comment]
@ironpython2001 this feature is checked in and coming in .NET 5. You can try it in .NET 5 RC1 - https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/.
