### ISSUE TITLE
SystemNative_ForkAndExecProcess can potentially hang forever

### ISSUE THREAD

**Issue by JennyLawrance** [dotnet/runtime#30266]
We are seeing an issue in our environment where the code to Process.Start never returns back.
Reviewing the code in this function: SystemNative_ForkAndExecProcess, the waitpid in case of failure can also be called after the child process has called into execve. If the child process then gets stuck due to some reason (let's say a kernel bug), then the parent process also gets stuck, as per the waitpid call at Line 472:

https://github.com/dotnet/corefx/blob/5c83394112febe1b481ab1c0b61a45c850677165/src/Native/Unix/System.Native/pal_process.c#L472

The mono version of this code path doesn't have WaitPid in the Process.Start() code path, and we suspect that is the reason why we didn't see this issue when running the same code in MONO. We have been running this in mono for the past 2 years, but the issue only occurs when we migrated to .NET core (version 2.1)

**Comment by adamsitnik** [comment]
> We will try to get a strace if we find a live repro.

@JennyLawrance is there any chance that you could share the repro?
