### ISSUE TITLE
Bigger coverage on BigInteger class

### ISSUE THREAD

**Issue by igormcoelho** [dotnet/runtime#30273]
I've been trying to reproduce behavior of C# BigInteger class on C++/Python/JavaScript (https://github.com/neoresearch/csbiginteger), and it would be helpful if more tests were available.
For example, I couldn't find any tests with negative divisions and mods, and found most of the tests on text documentation (rather than on corefx repo).
My reference is here: https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Numerics/tests/BigInteger

I know this project is huge and this is just a tiny part, anyway, this is a suggestion ;)

**Comment by marcusturewicz** [comment]
BigInteger has the following coverage (as of today):

<img width="560" alt="Screen Shot 2020-04-14 at 5 19 05 pm" src="https://user-images.githubusercontent.com/24448509/79196981-5a07fb00-7e74-11ea-9b0f-0cdd9465d32e.png">

The following lines could be improved:

<img width="824" alt="Screen Shot 2020-04-14 at 5 18 32 pm" src="https://user-images.githubusercontent.com/24448509/79197074-83288b80-7e74-11ea-8ec2-b2cb3ab2892b.png">
<img width="793" alt="Screen Shot 2020-04-14 at 5 18 28 pm" src="https://user-images.githubusercontent.com/24448509/79197083-858ae580-7e74-11ea-9768-4dd255d1abf4.png">
<img width="740" alt="Screen Shot 2020-04-14 at 5 18 23 pm" src="https://user-images.githubusercontent.com/24448509/79197085-86bc1280-7e74-11ea-84aa-631562ebcac6.png">
<img width="870" alt="Screen Shot 2020-04-14 at 5 18 15 pm" src="https://user-images.githubusercontent.com/24448509/79197087-8754a900-7e74-11ea-84d4-0d717485cccd.png">
<img width="836" alt="Screen Shot 2020-04-14 at 5 18 10 pm" src="https://user-images.githubusercontent.com/24448509/79197089-8885d600-7e74-11ea-831a-07735d4a0d17.png">
<img width="828" alt="Screen Shot 2020-04-14 at 5 18 01 pm" src="https://user-images.githubusercontent.com/24448509/79197091-8885d600-7e74-11ea-9f7b-18d453b304ed.png">
<img width="821" alt="Screen Shot 2020-04-14 at 5 17 52 pm" src="https://user-images.githubusercontent.com/24448509/79197095-891e6c80-7e74-11ea-8ba1-b3b8a987f39d.png">
<img width="688" alt="Screen Shot 2020-04-14 at 5 17 47 pm" src="https://user-images.githubusercontent.com/24448509/79197096-89b70300-7e74-11ea-8b15-8bc5878370fc.png">
<img width="923" alt="Screen Shot 2020-04-14 at 5 17 41 pm" src="https://user-images.githubusercontent.com/24448509/79197098-8a4f9980-7e74-11ea-9fd0-f822827bfc1f.png">
<img width="1090" alt="Screen Shot 2020-04-14 at 5 17 35 pm" src="https://user-images.githubusercontent.com/24448509/79197099-8ae83000-7e74-11ea-8045-fd1d2f92b1c4.png">
<img width="718" alt="Screen Shot 2020-04-14 at 5 17 30 pm" src="https://user-images.githubusercontent.com/24448509/79197101-8c195d00-7e74-11ea-9589-3946dbb9786e.png">
<img width="876" alt="Screen Shot 2020-04-14 at 5 17 18 pm" src="https://user-images.githubusercontent.com/24448509/79197103-8cb1f380-7e74-11ea-942f-ffb44dc5d53d.png">
<img width="730" alt="Screen Shot 2020-04-14 at 5 17 06 pm" src="https://user-images.githubusercontent.com/24448509/79197106-8de32080-7e74-11ea-86da-b754ff0914be.png">
<img width="768" alt="Screen Shot 2020-04-14 at 5 17 01 pm" src="https://user-images.githubusercontent.com/24448509/79197109-8e7bb700-7e74-11ea-88e0-761e77bc468d.png">
<img width="1069" alt="Screen Shot 2020-04-14 at 5 16 56 pm" src="https://user-images.githubusercontent.com/24448509/79197111-8f144d80-7e74-11ea-9367-47b2524675d3.png">
<img width="925" alt="Screen Shot 2020-04-14 at 5 16 46 pm" src="https://user-images.githubusercontent.com/24448509/79197114-90457a80-7e74-11ea-8cb0-b81b6ce6bb5b.png">
<img width="1059" alt="Screen Shot 2020-04-14 at 5 16 37 pm" src="https://user-images.githubusercontent.com/24448509/79197118-90de1100-7e74-11ea-9a6f-91cb784a1bf5.png">
<img width="822" alt="Screen Shot 2020-04-14 at 5 16 31 pm" src="https://user-images.githubusercontent.com/24448509/79197120-920f3e00-7e74-11ea-950f-c40f1d350784.png">
<img width="836" alt="Screen Shot 2020-04-14 at 5 16 25 pm" src="https://user-images.githubusercontent.com/24448509/79197123-920f3e00-7e74-11ea-9535-a85aec792212.png">
<img width="897" alt="Screen Shot 2020-04-14 at 5 16 19 pm" src="https://user-images.githubusercontent.com/24448509/79197125-93406b00-7e74-11ea-89c0-bf619b1ad7c2.png">
<img width="902" alt="Screen Shot 2020-04-14 at 5 16 13 pm" src="https://user-images.githubusercontent.com/24448509/79197132-94719800-7e74-11ea-9257-6d1935d6192a.png">
<img width="946" alt="Screen Shot 2020-04-14 at 5 16 07 pm" src="https://user-images.githubusercontent.com/24448509/79197133-950a2e80-7e74-11ea-9683-3428ce3452c1.png">
<img width="762" alt="Screen Shot 2020-04-14 at 5 15 57 pm" src="https://user-images.githubusercontent.com/24448509/79197135-963b5b80-7e74-11ea-8104-936b448a34a4.png">
<img width="764" alt="Screen Shot 2020-04-14 at 5 15 50 pm" src="https://user-images.githubusercontent.com/24448509/79197138-976c8880-7e74-11ea-94d5-0d6ada5991e7.png">
<img width="822" alt="Screen Shot 2020-04-14 at 5 15 38 pm" src="https://user-images.githubusercontent.com/24448509/79197140-98051f00-7e74-11ea-80c2-aaf017227456.png">
<img width="801" alt="Screen Shot 2020-04-14 at 5 15 28 pm" src="https://user-images.githubusercontent.com/24448509/79197142-98051f00-7e74-11ea-9379-2cd11e41ba3f.png">
<img width="826" alt="Screen Shot 2020-04-14 at 5 15 19 pm" src="https://user-images.githubusercontent.com/24448509/79197144-989db580-7e74-11ea-9f14-0e0fff62140a.png">
<img width="737" alt="Screen Shot 2020-04-14 at 5 15 12 pm" src="https://user-images.githubusercontent.com/24448509/79197146-99364c00-7e74-11ea-865c-33c235c8b554.png">

**Comment by danmosemsft** [comment]
That seems pretty good (although it looks like there are some paths still reachable).

I'm going to close this as good enough for now: if anyone would like to add more tests, they would be welcome. Thanks @marcusturewicz
