### ISSUE TITLE
Transport packages should not be signed

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#30301]
Per discussion here https://github.com/dotnet/corefx/pull/36022#discussion_r265347843
we should not sign symbol and *.Private.* packages as it adds some observable amount of time to the overall signing time (few minutes?) - we currently do it in parallel with testing so overall time might be similar.

Related code:
https://github.com/dotnet/corefx/blob/master/eng/Signing.props#L13

cc: @mmitche

**Comment by safern** [comment]
We can close this as we no longer produce transport packages.

**Comment by ViktorHofer** [comment]
We still produce at least the `Microsoft.Private.CoreFx.OOB` transport package.

**Comment by dagood** [comment]
Looking at a recent build, don't we still produce quite a few? Here's a list from a recent build of 122 packages that look like transport packages to me: https://gist.github.com/dagood/171bda76e272a2897a4fdbfdcfe858ee

**Comment by safern** [comment]
Then should this issue be repurposed to remove those packages?

**Comment by safern** [comment]
Sorry, clicked the wrong button now 🤦‍♂

**Comment by ViktorHofer** [comment]
The title says

> Transport packages should not be signed

which we still do for at least `Microsoft.Private.CoreFx.OOB`. That packages is used by dotnet/performance, cc @adamsitnik, why would we want to remove it? We should consider renaming it as some point but this issue is about not signing such packages. @mmitche is changing how we sign going forward so he might have additional context here.

**Comment by mmitche** [comment]
I think we can close this. The signing will be moving out of the build altogether so it's probably not worth the risk (e.g. downstream repos forget to sign the transport contents) and effort to go and keep these from being signed under the current infra.

**Comment by ViktorHofer** [comment]
Sounds good. Closing.
