### ISSUE TITLE
API Proposal: Regex.IsMatch with 'out Match' parameter

### ISSUE THREAD

**Issue by anurse** [dotnet/runtime#30308]
**NOTE**: The API proposal was changed from TryMatch to IsMatch after discussions in https://github.com/dotnet/corefx/issues/39622#issuecomment-513427430. I have edited it inline for clarity.

I find myself doing this a lot with `Regex`es:

```csharp
// Some example regex. Don't judge me!!
var myRegex = new Regex(@"^https?://(www\.)?github.com/(?<owner>[^/]+)/(?<repo>[^/]+)/?.*$");

var match = myRegex.Match(inputString);
if (match.Success)
{
    var owner = match.Groups["owner"].Value;
    // ... work with the match
}
else
{
    // Do something else
}
```

I think this could be made a little more ergonomic through a new method on Regex, `IsMatch`. With such a method, this code could become:

```csharp
// Some example regex. Don't judge me!!
var myRegex = new Regex(@"^https?://(www\.)?github.com/(?<owner>[^/]+)/(?<repo>[^/]+)/?.*$");

if (myRegex.IsMatch(inputString, out var match))
{
    var owner = match.Groups["owner"].Value;
    // ... work with the match
}
else
{
    // Do something else
}
```

Yes, it's only a small change (one line), but it feels more _ergonomic_ to me. Before `out var` support in C#, this would've been just as clumsy as the current model, but now that we have `out var` this syntax feels like a valuable and simple addition.

I get that "ergonomics" and "aesthetics" are subjective measures though, so would welcome other input here.

## Proposed API

```csharp
public class Regex
{
    // EXISTING methods
	public bool IsMatch(string input) { throw null; }
	public bool IsMatch(string input, int startat) { throw null; }
	public static bool IsMatch(string input, string pattern) { throw null; }
	public static bool IsMatch(string input, string pattern, System.Text.RegularExpressions.RegexOptions options) { throw null; }
	public static bool IsMatch(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout) { throw null; }

	// NEW methods
	public bool IsMatch(string input, out Match match) { throw null; }
	public bool IsMatch(string input, int startat, out Match match) { throw null; }
	public static bool IsMatch(string input, string pattern, out Match match) { throw null; }
	public static bool IsMatch(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, out Match match) { throw null; }
	public static bool IsMatch(string input, string pattern, System.Text.RegularExpressions.RegexOptions options, System.TimeSpan matchTimeout, out Match match) { throw null; }
}
```

## Implementation

It's trivial to implement this, here's an example extension method I use (for **illustrative purposes only**):

```csharp
public static class RegexExtensions
{
    public static bool IsMatch(this Regex regex, string input, out Match match)
    {
        match = regex.Match(input);
        return match.Success;
    }
}
```

Note that in this implementation, the value of `match` is *valid* in both branches of an `if(IsMatch(...)) {} else {}` because the match object is always returned, even in the case of an unsuccessful match. I'm certainly open to having a discussion on that. I don't feel strongly either way.

In the end, I have my extension methods so I can do just fine with those, but I think this could be useful and more discoverable if it was in the BCL.

I'd be willing to submit a PR if this was approved for consideration.

**Comment by pgovind** [comment]
With the evolution of pattern matching, I think the need for this goes away (very similar to https://github.com/dotnet/runtime/issues/45959). Copy-pasting a comment from there:

``` csharp
if (Regex.Match("I have 1 apple", "\\d+") is {Success: true} match) 
{
    Console.WriteLine("You have {0} apple", match.Value);
}
```

**Comment by stephentoub** [comment]
Closing per previous comment. Thanks.
