### ISSUE TITLE
Enable Utf8JsonReader to read json from stream

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#30328]
Basically, implement analogue of [JsonTextReader(TextReader)](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonTextReader__ctor.htm).

My scenario is reading the result of: `docker inspect [image]` (which produces a json document), either called via Process.Start() or piped in via standard input. Both scenarios result in TextReader objects. I’d like to see either a new constructor to enable this scenario or some straightforward collaborative mechanism between the two readers. 

Related: https://github.com/dotnet/corefx/issues/38581

**Comment by om-ha** [comment]
I hope this gets fixed.

@dazinator from the same answer you linked, in the comments somebody found it a few bugs and fixed them in [this repo](https://github.com/evil-dr-nick/utf8jsonstreamreader).

**Comment by alexandrvslv** [comment]
I came here to figure out `DeserializeAsync` errors:

> ']' is an invalid start of a property name. Expected a '"'. LineNumber: XXXXX | BytePositionInLine: XX. 

>'0x0D' is invalid within a JSON string. The string should be correctly escaped. Path: $[5] | LineNumber: XXXXX | BytePositionInLine: XX.

> Or similar depending on order of items in json array of source stream. 

And i have custom `JsonConverter` witch can process full item type with referencing properties.

Reason: `Utf8JsonReader` buffer size is not enough to cover one item in array. 

Decision: Increasing `JsonSerializerOptions.DefaultBufferSize` to cover item size(i my case: to 128KB)

**Comment by peterduniho** [comment]
I get the point above that `Utf8JsonReader` may not be the best place for deserializing from a stream. But given that the docs for DataContractJsonSerializer direct people to this namespace, there should be _some_ entry point in the System.Text.Json namespace that handles this.

Especially since `Utf8JsonWriter` _does_ support `Stream` as a data sink. It's weird that the API is not symmetric.

**Comment by sergeyt** [comment]
I came up with the following code. It reads JSON dataset as `IAsyncEnumerable` sequence of `Dictionary<string, object>` records:

```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Threading;
using Opw.HttpExceptions;

namespace YourApp
{
    using Record = IEnumerable<KeyValuePair<string, object>>;
    
    public static class JsonArrayReader
    {
        public static IAsyncEnumerable<Record> ReadJsonRecords(this Stream input, CancellationToken cancellationToken)
        {
            bool isArrayStart = true;
            return Parse(input, cancellationToken, (ref Utf8JsonReader reader) =>
            {
                if (isArrayStart)
                {
                    ReadArrayStart(ref reader);
                    isArrayStart = false;
                }
                return ReadRecords(ref reader);
            });
        }

        private delegate IEnumerable<T> Parser<T>(ref Utf8JsonReader reader);

        // inspired by https://github.com/scalablecory/system-text-json-samples/blob/master/json-test/JsonParser.ParseSimpleAsync.cs
        private static async IAsyncEnumerable<T> Parse<T>(Stream input, [EnumeratorCancellation] CancellationToken cancellationToken, Parser<T> parser)
        {
            var buffer = new byte[4096];
            var fill = 0;
            var consumed = 0;
            var done = false;
            var readerState = new JsonReaderState();

            while (!done)
            {
                if (fill == buffer.Length)
                {
                    if (consumed != 0)
                    {
                        buffer.AsSpan(consumed).CopyTo(buffer);
                        fill -= consumed;
                        consumed = 0;
                    }
                    else
                    {
                        Array.Resize(ref buffer, buffer.Length * 3 / 2);
                    }
                }

                int read = await input.ReadAsync(buffer.AsMemory(fill), cancellationToken).ConfigureAwait(false);

                fill += read;
                done = read == 0;

                foreach (var item in ParseBuffer())
                {
                    yield return item;
                }
            }
            
            IEnumerable<T> ParseBuffer()
            {
                var reader = new Utf8JsonReader(buffer.AsSpan(consumed, fill - consumed), done, readerState);
                var result = parser(ref reader);
                consumed += (int)reader.BytesConsumed;
                readerState = reader.CurrentState;
                return result;
            }
        }

        private static void ReadArrayStart(ref Utf8JsonReader reader)
        {
            if (!reader.Read())
            {
                throw new BadRequestException("Unexpected EOF");
            }

            // skip comments
            while (reader.TokenType == JsonTokenType.Comment)
            {
                reader.Skip();
            }

            if (reader.TokenType != JsonTokenType.StartArray)
            {
                throw new BadRequestException($"Expect JSON array, but got {reader.TokenType}");
            }
        }

        private static IEnumerable<Record> ReadRecords(ref Utf8JsonReader reader)
        {
            var records = new List<Record>();
            while (true)
            {
                if (!reader.Read())
                {
                    if (reader.TokenType == JsonTokenType.EndArray)
                    {
                        break;
                    }
                    throw new BadRequestException("Unexpected EOF");
                }

                if (reader.TokenType == JsonTokenType.EndArray)
                {
                    break;
                }
                
                if (reader.TokenType != JsonTokenType.StartObject)
                {
                    throw new BadRequestException($"Expect {JsonTokenType.StartObject}, but got {reader.TokenType}");
                }
                
                var record = ReadRecord(ref reader);
                if (record == null)
                {
                    break;
                }
                records.Add(record);
            }

            return records;
        }

        private static Record ReadRecord(ref Utf8JsonReader reader)
        {
            try
            {
                var savePoint = reader;
                var result = JsonSerializer.Deserialize<Dictionary<string, object>>(ref savePoint);
                reader = savePoint;
                return result;
            }
            catch (JsonException)
            {
                return null;
            }
        }
    }
}
```

It reuses idea from https://github.com/scalablecory/system-text-json-samples/blob/master/json-test/JsonParser.ParseSimpleAsync.cs.

**Comment by ahsonkhan** [comment]
> I came here to figure out `DeserializeAsync` errors:
> 
> > ']' is an invalid start of a property name. Expected a '"'. LineNumber: XXXXX | BytePositionInLine: XX.
> 
> > '0x0D' is invalid within a JSON string. The string should be correctly escaped. Path: $[5] | LineNumber: XXXXX | BytePositionInLine: XX.
> 
> > Or similar depending on order of items in json array of source stream.
> 
> And i have custom `JsonConverter` witch can process full item type with referencing properties.
> 
> Reason: `Utf8JsonReader` buffer size is not enough to cover one item in array.
> 
> Decision: Increasing `JsonSerializerOptions.DefaultBufferSize` to cover item size(i my case: to 128KB)

@alexandrvslv, **can you please file a separate issue with a simplified repro test app of the issue you were seeing.** At first glance, this seems like a bug, and you shouldn't need to increase the `DefaultBufferSize` to fix it. It would be good for us to understand what our JSON payload looks like, your custom JsonConverter implementation, and the root cause of the issue you were seeing (also include our TFM or STJ package version).

**Comment by alexandrvslv** [comment]
> @alexandrvslv, can you please file a separate issue with a simplified repro test app of the issue you were seeing. At first glance, this seems like a bug, and you shouldn't need to increase the DefaultBufferSize to fix it. It would be good for us to understand  what our JSON payload looks like, your custom JsonConverter implementation, and the root cause of the issue you were seeing (also include our TFM or STJ package version).

@ahsonkhan, i will try to reproduce the issue, it may take some time to implement test for serialize to json with custom [formater](https://github.com/alexandrvslv/datawf/blob/d98710badbc6093e2a6e1e8e93230e2bfc5cd5ed/DataWF.WebService.Common/Json/DBItemOutputFormatter.cs#L84), process data with some pipe, and deserialize it with custom [parser](https://github.com/alexandrvslv/datawf/blob/d98710badbc6093e2a6e1e8e93230e2bfc5cd5ed/DataWF.WebClient.Common/Json/SystemJsonClientConverter.cs#L46). 
i have a lot of changes since 2020 Feb. even model is simplified and transfer separated to sub request's.

**Comment by schalling** [comment]
Im getting similar deserialization errors as @alexandrvslv 
I gave the JsonSerializerOptions.DefaultBufferSize a size of 128Kb. That helped for a few files - but now I have hit a new file that throws an exception. The json object been deserialized i only 21 properties (flat object). We changing buffer sizes the exception changes to where it reached in the file.. 
I can deserialize the whole file in one go - that just gives me a major memory footprint which is what I want to avoid - and later I'll work with larger files..

Im not using a custom JsonConverter to deserialize - just POCO.
The files im working on are each a list of objects serialized into json.

Did you find out anything about this buffer issue ?
