### ISSUE TITLE
Low overhead hashing

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#30331]
In some scenarios, it is necessary to hash small amounts of data with very high frequency. This happens for example in authentication scenarios. Another case is processing of blockchain data. Transactions are fairly small pieces of data that must be hashed at a high rate.

The existing framework APIs have fairly high per-hash overhead. I benchmarked this on .NET Core 2.2:

    public class HashOverheadRepro
    {
        public static void Run()
        {
            Console.WindowWidth = 160;

            var manualConfig = new ManualConfig();

            manualConfig.Add(JitOptimizationsValidator.DontFailOnError);

            manualConfig.Add(DefaultConfig.Instance.GetLoggers().ToArray());
            manualConfig.Add(DefaultConfig.Instance.GetExporters().ToArray());
            manualConfig.Add(DefaultConfig.Instance.GetColumnProviders().ToArray());
            manualConfig.Add(Job.InProcess.RunOncePerIteration().WithEvaluateOverhead(false).WithInvocationCount(1).WithLaunchCount(1).WithIterationCount(1).WithWarmupCount(1));

            BenchmarkRunner.Run<HashOverheadRepro>(manualConfig);
        }

        readonly byte[] data = new byte[32];
        readonly int hashCount = 100000;

        [Benchmark]
        public void SimpleUsage()
        {
            for (int i = 0; i < hashCount; i++)
            {
                using (var hashAlgorithm = SHA1.Create())
                {
                    hashAlgorithm.ComputeHash(data);
                }
            }
        }

        [Benchmark]
        public void ReuseObject()
        {
            using (var hashAlgorithm = SHA1.Create())
            {
                for (int i = 0; i < hashCount; i++)
                {
                    hashAlgorithm.ComputeHash(data);
                }
            }
        }

        [Benchmark]
        public void ReuseObject_EfficientAPI()
        {
            using (var hashAlgorithm = SHA1.Create())
            {
                for (int i = 0; i < hashCount; i++)
                {
                    hashAlgorithm.TransformFinalBlock(data, 0, data.Length);
                    hashAlgorithm.Initialize();
                }
            }
        }
    }

Here, I have compared various API usage styles. The most efficient style is about 2.5x as fast as the most inefficient style.

![image](https://user-images.githubusercontent.com/12032350/61620965-3cee2500-ac72-11e9-90e0-81fc50736ff6.png)

Where is the time spent?

![image](https://user-images.githubusercontent.com/12032350/61621057-6e66f080-ac72-11e9-82dd-7e6283f2be6e.png)

There seems to be a lot of overhead that has nothing to do with computing the hash. This is easier to see when profiling native code as well:

![image](https://user-images.githubusercontent.com/12032350/61627094-3914cf80-ac7f-11e9-846e-b913885a5484.png)

The bcrypt invocations account for merely about 40% of time spent. A lot of time is spent on handle management. The 20% spent on `Clone` is for cloning the `byte[]` I believe.

I wonder how much more overhead exists inside of `bcrypt`.

Does it make sense to add a very low overhead hashing API? Something like:

```
public class HashAlgorithm
{
    public abstract void ComputeHash(ReadOnlySpan<byte> data, Span<byte> hashOutput);
}
```

This API should essentially just enter the actual hashing code without anything else going on. It should be stateless and threadsafe so that the same `HashAlgorithm` object can be reused (put into a static variable). Note, that the existing `ComputeHash` is not threadsafe.

I imagine this as similar to how it would work in C++. There, one would create a hash object on the stack and directly call an instance method on it to process the data. After that call completes the hash exists in the object to be used in place. There would be very little indirection and copying.

Is this achievable?

<hr>

Also note, that the managed hash implementations on .NET Framework have a lot less overhead than the native ones. I believe that .NET Core no longer has managed implementations. What was the reason for removing them?

Benchmark on .NET Framework:

        [Benchmark]
        public void SHA1Managed()
        {
            using (var hashAlgorithm = new SHA1Managed())
            {
                for (int i = 0; i < hashCount; i++)
                {
                    hashAlgorithm.ComputeHash(data);
                }
            }
        }

        [Benchmark]
        public void SHA1CryptoServiceProvider()
        {
            using (var hashAlgorithm = new SHA1CryptoServiceProvider())
            {
                for (int i = 0; i < hashCount; i++)
                {
                    hashAlgorithm.ComputeHash(data);
                }
            }
        }

        [Benchmark]
        public void SHA1Cng()
        {
            using (var hashAlgorithm = new SHA1Cng())
            {
                for (int i = 0; i < hashCount; i++)
                {
                    hashAlgorithm.ComputeHash(data);
                }
            }
        }

|                    Method |       Mean |
|-------------------------- |-----------:|
|               SHA1Managed |   841.6 ms |
| SHA1CryptoServiceProvider | 2,080.1 ms |
|                   SHA1Cng | 2,779.5 ms |

So we get three different speeds. The managed version is 2.5x faster than the best native one.

Profile for `SHA1Managed`:

![image](https://user-images.githubusercontent.com/12032350/61628478-b7bf3c00-ac82-11e9-9533-b21d36818bbb.png)

Still looks like 50% overhead for non-hashing work.

**Comment by bartonjs** [comment]
IncrementalHash is the path forward for incremental hashing.  #17590 tracks making one-shot hashing easier.  I don't think there's anything else unique in this issue, so closing it as already-tracked.
