### ISSUE TITLE
Task WhenAll WhenAny support for ReadOnlyMemory

### ISSUE THREAD

**Issue by Duranom** [dotnet/runtime#30339]
Currently `Task.WhenAll` and `Task.WhenAny` currently only accept an Array or IEnumerable of tasks to await. However with the introduction of Span, Memory it would be nice if it would be able to accept a ReadOnlyMemory. I guess ReadOnlySpan could be possible as the implemenations are not async but that would make impossible for later to be changed if needed.

A sample where we currently trying to get it into is a heavy consumer class that handles a lot of tasks with Task.WhenAny on a min/max threshold basis and after every WhenAny a custom extension splits the completed and ongoing and some processing and then starts the WhenAny loops again with the new view.
The use of MemoryPool, Span and Segment helped making it less allocating heavy but the only niche weird feeling is that at the moment for Task.WhenAny and Task.WhenAll it is required to do a ToArray() because of the defensive copy that is being made inside.

**Comment by stephentoub** [comment]
Closing for the aforementioned reasons.  Thanks.
