### ISSUE TITLE
A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) Kali Linux 2019.2

### ISSUE THREAD

**Issue by Kool-Koder** [dotnet/runtime#30330]
I have a project running inside Kali Linux. The project works in both visual studio 2019 as well as in Windows 10. I am using .NET Core 2.2. I am hitting the error as shown below, but it runs well in Windows. Not too sure if this is a bug. Thank you very much.

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)`

**Comment by karelz** [comment]
Closing as there is not response and it is not actionable for us. If there is more info, feel free to reopen. Thanks!
