### ISSUE TITLE
LINQ IndexWhere extension method

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#30342]
I recently found myself writing up yet another ad-hoc `IndexWhere` extension method for `IEnumerable<T>` in yet another project.  Every time the need for it comes up, I'm a bit surprised that it's never been put in `System.Linq.Enumerable`, given how common an operation it turns out to be.

We should fix that.  Let's add a standard LINQ operator that works exactly like `Where`, except that instead of returning `IEnumerable<T>`, it returns `IEnumerable<int>`, with the indices of all the values that match the predicate.

This can currently be emulated with existing standard LINQ operators, but the best solution I've found takes three: `input.Select((x, i) => new KeyValuePair<T, int>(x, i)).Where(kvp => predicateOperation(kvp.Key)).Select(kvp => kvp.Value)`, which is ugly and inefficient.  Let's do it in one instead.

Reference implementation, with error checking elided for clarity:

```
        public static IEnumerable<int> IndexWhere<T>(this IEnumerable<T> value, Func<T, bool> predicate)
        {
            int i = 0;
            foreach (var item in value)
            {
                if (predicate(item))
                {
                    yield return i;
                }
                ++i;
            }
        }
```

**Comment by Reza1024** [comment]
Related to #31156

**Comment by eiriktsarpalis** [comment]
> No, that will give a sequence 0, 1, 2, 3, ... because Select only sees the items that passed the predicate successfully.

Fundamentally this is why I'm not a big fan of dealing with indices in LINQ: they don't compose in chained calls. In the rare case that I do need to use them I find that the `Select` and `Where` overloads are a good enough workaround (like the one you already provided in the original post). However in most cases you are better off just using a `foreach` loop with an index variable.

My impression is that the proposed method isn't general-purpose enough to warrant inclusion to System.Linq. It is also fairly trivial to roll your own extension method that does this. So I am going to close this issue, feel free to reopen if you would like to continue this conversation.
