### ISSUE TITLE
Inconsistent summation of nullable doubles.

### ISSUE THREAD

**Issue by DavidKiff** [dotnet/runtime#30358]
Why does the following not output the same value?

var x = null + 10d; // Correctly returns null.

var y = new[] { (double?)null, 10d }.Sum(); // Incorrectly returns 10

If I wanted 10, then I could have null coalesced the nullable double to 0 in a select or filtered out nulls.  This way around, I cant "fix" it, without writing my own Sum.  This perhaps should be named SumWithoutNulls!

**Comment by eiriktsarpalis** [comment]
I second @bartdesmet's comments, closing as by-design.
