### ISSUE TITLE
IndentedTextWriter Async methods don't indent properly

### ISSUE THREAD

**Issue by markrendle** [dotnet/runtime#30351]
[System.CodeDom.Compiler.IndentedTextWriter](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/CodeDom/Compiler/IndentedTextWriter.cs) wrapped around a `StringWriter` doesn't indent properly when using the `WriteLineAsync` methods.

- First write is not indented
- Writes following empty lines (i.e. from `await WriteLineAsync();`) are not indented
- Lines following lines with content are indented correctly.

Gist: https://gist.github.com/markrendle/01b8b70d2b7c4f023bf196e96562c14a

N.B.: I know there's no point using `*Async` on a `StringWriter`, but the code in question is used with both `StringWriter` and `StreamWriter`.

N.B. 2: I'd just submit a PR to fix this, but I don't know if that would constitute a breaking change.

Using .NET Core 3.0 Preview 7 win-x64.

**Comment by carlossanlop** [comment]
Triage: @markrendle would you be interested in submitting a PR to get this fixed?

**Comment by carlossanlop** [comment]
Assigning to @samtrion
