### ISSUE TITLE
Is there an API to do something before the application exit?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#30353]
Is there an API to do something before the application exit?
For example, I wanna make sure some resource disposed or do some custom operations before 
the application exit?

**Comment by ericstj** [comment]
>  I wanna make sure some resource disposed

Typically you should handle resource disposal through IDisposable, potentially a finalizer (though prefer things like SafeHandles over writing your own finalizable objects).   In general OS resources (file handles, sockets, memory, etc) are designed in such a way that process shutdown will automatically reclaim the resource so you shouldn't need to do things on process shutdown for most resources.

> However a system crash or quitting via the TaskManager (kill) never triggers these events.

We cannot actually run any code when a process is killed, the OS forcefully will stop running the application.

I believe the best event in those listed is `AppDomain.CurrentDomain.ProcessExit`

Related: https://github.com/dotnet/runtime/issues/36089

**Comment by danmosemsft** [comment]
Note also https://github.com/dotnet/runtime/issues/36089 in this context

**Comment by danmosemsft** [comment]
Oh, and that was already mentioned.
