### ISSUE TITLE
"dotnet test" in corefx produces no console output ever

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#30383]
```
:\git\corefx\src\System.Text.RegularExpressions\tests>..\..\..\.dotnet\dotnet.exe test

C:\git\corefx\src\System.Text.RegularExpressions\tests>
```
Note it's quiet even if tests failed. Looking at the binlog it's because dotnet test passes `/v:quiet`. If this is going to work, that should be higher verbosity. 

We could probably reduce the amount of output we have historically, but it should at least have the line like `   System.Text.RegularExpressions.Tests  Total: 1452, Errors: 0, Failed: 0, Skipped: 0, Time: 10.931s` and if there's a failure include the path to the xml log. 

@viktorhofer
cc @stephentoub

**Comment by ViktorHofer** [comment]
Dotnet test now works in master. Closing.
