### ISSUE TITLE
Runtime can't find COM object #1408

### ISSUE THREAD

**Issue by grubioe** [dotnet/runtime#30412]
Copying from WPF #[1408](https://github.com/dotnet/wpf/issues/1408), author @cbaysinger

- 3.0.0-preview8-28376-13
- Windows version: Windows version: 1809 (OS Build 17763.615)
- Does the bug reproduce also in WPF for .NET Framework 4.8?: No

**Problem description:**
At runtime a COM interface can't be created because the file can't be found as in the following error displayed in the Output window: Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll and wasn't handled before a managed/native boundary
Could not load file or assembly 'Interop.MSComDlg, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Actual behavior:**
A simple COM object such as MSComDlg can be added to a project and it appears in the Object Browser and in IntelliSense however at run time the following exception is thrown before the MainWindow.xaml.cs static members are constructed:
System.IO.FileNotFoundException
HResult=0x80070002
Message=Could not load file or assembly 'Interop.MSComDlg, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Source=
StackTrace:

[CoreApp.zip](https://github.com/dotnet/wpf/files/3437746/CoreApp.zip)

**Expected behavior:**
The component should be found so that the following line of code will create an interface:
m_Dlg = (MSComDlg.CommonDialog)System.Activator.CreateInstance( m_objDlgType );

**Minimal repro:**
See the attached zip file.

Cc: @rladuca

**Comment by AaronRobinsonMSFT** [comment]
@cbaysinger Apologies for the lack of response - it seems I missed your reply. Are you still facing this issue?

**Comment by AaronRobinsonMSFT** [comment]
@cbaysinger I again apologize for the very late reply. Please open a new issue and tag me if this behavior is still present.
