### ISSUE TITLE
Delay Sign CertificateRequest with ECSDA key pair

### ISSUE THREAD

**Issue by jlchavez** [dotnet/runtime#30424]
I've been trying to delay sign a CertificateRequest with a CA Certificate that has ECSDA Key Pair.
Since .net core has not way of loading the CertificteRequest from a CER File, I've tried BouncyCastle.NetCore 1.8.5. to load it to a CertificationRequestInfo.

The CA Certificate is stored on Windows or on a .PFX file with password.
For purposes of signing I need to build the ECSDA Private Key again, or provider a AsymmetricCipherKeyPair with the ECPublicKeyParameters and ECPrivateKeyParameters (both from BouncyCastle), 

`            string curveName = "P-521";
            X9ECParameters ecP = NistNamedCurves.GetByName(curveName);
            var ecdomain = new ECDomainParameters(ecP.Curve, ecP.G, ecP.N);
            var pr = new ECPrivateKeyParameters("ECDSA", new BigInteger(signer.GetECDsaPrivateKey().ExportParameters(true).D), ecdomain);
            var signatureFactory = new Asn1SignatureFactory("SHA512WITHECSDA", pr, random);
`

When getting to the ExportParameters(true) call I get

`Unhandled Exception: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The requested operation is not supported`

The certificate has the private key, the code is running as an administrator, and also the certificate has been granted access to the private key with ACLs. I've also tested that I can encrypt, decrypt, sign and verify the signature, with no problem at all.

Any suggestions on what is wrong? any alternate way to delay sign my certificate with ECSDA keys? or how to get the Certificate's Private Key? Should I also store it on Cng? Wouldn't I have the same problem?

**Comment by bartonjs** [comment]
@jlchavez Were you successful / is there anything left for us to do for this issue?

**Comment by bartonjs** [comment]
Since there hasn't been any followup in a while, closing the issue.
