### ISSUE TITLE
Improve JsonNumber performance

### ISSUE THREAD

**Issue by kasiabulat** [dotnet/runtime#30454]
`JsonNumber` uses `string` as a backing field, which requires unnecessarily expensive conversions.

Alternatives to consider:
- Span<byte> or array of Utf8String/Char8 (once they come online in the future) / byte 
- Internal types that are specific to each numeric type in .NET with factories to create JsonNumber (https://github.com/dotnet/corefx/pull/39954#discussion_r309889640)
- Internal struct field which has all the supported numeric types
- Unsigned long field accompanying string to store types that are <= 8 bytes long (https://github.com/dotnet/corefx/pull/39917#discussion_r311784609)

Additionally, in `JsonNumber.SetFormattedValue`:

```csharp
JsonWriterHelper.ValidateNumber(Encoding.UTF8.GetBytes(value).AsSpan());
``` 

unnecessarily allocates a `byte[]`. We can try and avoid that (and the solution depends on how perf critical this is).
- stackalloc the span for length < 256
- use array pool otherwise
- use the span-based overload of [Encoding.UTF8.GetBytes](https://apisof.net/catalog/System.Text.Encoding.GetBytes(ReadOnlySpan%3CChar%3E,Span%3CByte%3E)) on .NET Core (and char* overload on netfx) OR the helper in `JsonWriterHelper.ToUtf8` similar to:
https://github.com/dotnet/corefx/blob/97d5957fc71853961082e22873d926269b291b92/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteProperties.Helpers.cs#L207-L214

_Originally posted by @ahsonkhan in https://github.com/dotnet/corefx/pull/39917#discussion_r309503776 and https://github.com/dotnet/corefx/pull/39917#discussion_r311780744

**Comment by miloszkukla** [comment]
Which internal type would be chosen when parsing or converting from JsonElement? In Json.NET it is first parsed as int (or BigInt) and if it fails there is FloatParseHandling enum deciding whether to parse into float or decimal.  Would there be something similar here?
For json writing in Json.NET there is also FloatFormatHandling enum worth mentioning.

**Comment by eiriktsarpalis** [comment]
Closing, since the issue concerns an issue that was not eventually shipped (cf. #34099).
