### ISSUE TITLE
Bitmap Clone throws away all metadata on Linux

### ISSUE THREAD

**Issue by codars** [dotnet/runtime#30467]
## Development Environment

.Net Core: 2.2.401
System.Imaging.Common: 4.5.1

## Operating System
Windows: 10
Linux: Ubuntu 18.04

## Sample Code
```csharp
Bitmap source(path);
var cloned = source.Clone(new Rectangle(0, 0, source.Width, source.Height), PixelFormat.Format24bppRgb);
Console.WriteLine($"Length: {cloned.PropertyItems.Length}");
```

## Repro Steps:
1. Build & Run on Linux with a Bitmap having metadata
2. On Linux, prints "Length: 0"
3. On Windows, prints non zero

**Comment by safern** [comment]
Closing as this is a `libgdiplus` issue as @gfoidl pointed out.

There is also: https://github.com/mono/mono/issues/9903
