### ISSUE TITLE
Use GetPathOfFileAbove where appropriate

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#30468]
Following up from CoreCLR's repo Issue 20582, there are certain places in the source code where GetPathOfFileAbove usage is preferred to the more verbose GetDirectoryNameOfFileAbove. The following example illustrates both calls:

Change:
- `"$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props"`

To:
- `"$([MSBuild]::GetPathOfFileAbove(dir.props))"`

The second one is easier to read and less prone to mistakes if edition is ever required. Are there any reasons to not use GetPathOfFileAbove in CoreFX?

**Comment by TaurahSP** [comment]
@ivdiazsa can i work on this bug as a first time contribution?

**Comment by danmosemsft** [comment]
@TaurahSP Sure, I've assigned it to you. Post here if you have questions !

**Comment by TaurahSP** [comment]
@danmosemsft  Thanks, can you point me out where i should be looking first?

**Comment by danmosemsft** [comment]
@ivdiazsa (or @ViktorHofer ) maybe can do that.

**Comment by ViktorHofer** [comment]
That would be in the whole repo... We use that pattern all over the place.

Search for `"$([MSBuild]::GetDirectoryNameOfFileAbove(` and replace it with `"$([MSBuild]::GetPathOfFileAbove(` for anything that imports a file "from above" which hasn't the same name as the calling msbuild file.

**Comment by FatTigerWang** [comment]
I tried searching the repo for the wrong use of `GetDirectoryNameOfFileAbove`, but I didn't find it. I believe this issue has been resolved.
@danmoseley
