### ISSUE TITLE
FileSystemWatcher not reporting file moves on Mac OSX 10.15 Catalina

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#30491]
One test failing from System.IO.FileSystem.Watcher.Tests on Mac Catalina:
```xml
<test name="System.IO.Tests.File_Move_Tests.File_Move_From_Unwatched_To_Watched" type="System.IO.Tests.File_Move_Tests" method="File_Move_From_Unwatched_To_Watched" time="4.1481931" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Created event did not occur as expected\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 272
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 182
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 152
   at System.IO.Tests.File_Move_Tests.FileMove_FromUnwatchedToWatched(WatcherChangeTypes eventType) in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs:line 164
   at System.IO.Tests.File_Move_Tests.File_Move_From_Unwatched_To_Watched() in /Users/dotnet/Documents/dotnet/corefx/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs:line 55]]></stack-trace>
        </failure>
      </test>
```

**Comment by 616E64726173** [comment]
is this issue still open for Catalina? it's a pretty big deal for anybody working on filesync applications.

**Comment by cyperous** [comment]
There is a workaround that I have found, not sure if it would solve your particular issue.

[https://github.com/dotnet/runtime/issues/31194](https://github.com/dotnet/runtime/issues/31194)

[https://github.com/dotnet/runtime/issues/31194#issuecomment-548244074](https://github.com/dotnet/runtime/issues/31194#issuecomment-548244074)

I really only noticed an issue in Catalina when trying to watch files or directories that were on an APFS volume.  For me, I was trying to watch files for changes (aka monitor access times) on an external drive that was formatted with APFS.

The workaround was to run this (`sudo mount -vuwo strictatime /Volumes/Drive`) on the mounted drive.

**Comment by mattdefoor** [comment]
> There is a workaround that I have found, not sure if it would solve your particular issue.
> 
> #31194
> 
> [#31194 (comment)](https://github.com/dotnet/runtime/issues/31194#issuecomment-548244074)
> 
> I really only noticed an issue in Catalina when trying to watch files or directories that were on an APFS volume. For me, I was trying to watch files for changes (aka monitor access times) on an external drive that was formatted with APFS.
> 
> The workaround was to run this (`sudo mount -vuwo strictatime /Volumes/Drive`) on the mounted drive.

I wouldn't consider this a feasible workaround for those that are shipping software. It is unlikely that you'll get a customer to change their mount options for a given drive, especially a system mounted one.

**Comment by cyperous** [comment]
@mattdefoor True, that's why I said 

> not sure if it would solve your particular issue.

**Comment by carlossanlop** [comment]
Triage:
@wfurt this appears to be a Catalina bug. Does it look correct to you?

**Comment by wfurt** [comment]
We should look into this @carlossanlop. May be fixed with changes @aik-jahoda submitted. 
(and he may have better memory than me)

As far as the access time, I would not call it bug. It is more behavior of a given file system e.g. This would work on Catalina if another file system type is used. On the same note, you can configure this on Linux as well to improve performance - it just happens that all distros we test on do not have that enabled. If we have any tests depending on that we should check first if the given file system supports (or was configured) with atime. (e.g. get atime, access file, wait, access it again and get atime and check it is different)
For the product, we can silently ignore it e.g. never emit event or we can throw if a change notification was requested on file which does not support it.

**Comment by aik-jahoda** [comment]
This should be fixed by https://github.com/dotnet/corefx/pull/41963. I run the tests several times and all were passing.

**Comment by buyaa-n** [comment]
Thank you @aik-jahoda for fix, test enabled back, closing
