### ISSUE TITLE
ConventionsBuilder and open generic export with constructor dependencies (see also #10627)

### ISSUE THREAD

**Issue by ioancrisan** [dotnet/runtime#30514]
See this test:

``` C#
        [Test]
        public void SystemComposition_generic_export_with_ctor_dependency()
        {
            var conventions = new ConventionBuilder();

            conventions
                .ForType<Dependency>()
                .Export<Dependency>();
            conventions
                .ForType(typeof(MoreOpenWithDependency<>))
                .ExportInterfaces(
                    i => i.GetGenericTypeDefinition() == typeof(IOpen<>),
                    (type, builder) => builder.AsContractType(typeof(IOpen<>)))
                .SelectConstructor(ctors => ctors.First());

            var configuration = new ContainerConfiguration()
                .WithParts(new[] { typeof(IOpen<>), typeof(MoreOpenWithDependency<>) })
                .WithAssembly(this.GetType().Assembly, conventions);

            using (var container = configuration.CreateContainer())
            {
                var myService = container.GetExport(typeof(IOpen<object>));
            }
        }

        public class MoreOpenWithDependency<T> : IOpen<T>
        {
            // [ImportingConstructor]
            public MoreOpenWithDependency(Dependency dep) { }
        }

        public class Dependency { }
```

When explicitly adding the [ImportingConstructor] attribute, everything works fine, but without it, even if indicating the constructor in the conventions, it throws an:
```
System.Composition.Hosting.CompositionFailedException : No importing constructor was found on type 'Kephas.Tests.Composition.Mef.MefAmbientServicesBuilderExtensionsTest+MoreOpenWithDependency`1
```
Due to an automatic parts registration using implicit conventions it is not possible to add the [ImportingConstructor] attribute.

**Comment by ericstj** [comment]
I've confirmed the repro and also confirmed that this doesn't happen for a type that is non-generic.  I believe this is a valid bug.

While confirming I did a bit of debugging and noticed that this appears to be the problem: 
https://github.com/dotnet/runtime/blob/54a09d24142864767d50c83c2a64c0e1e37a34c2/src/libraries/System.Composition.Convention/src/System/Composition/Convention/ConventionBuilder.cs#L257-L261

The `MemberInfo` examined at the time of part construction is on a closed generic (`MoreOpenWithDependency<object>`.ctor(dependency)`) and thus does not match that which was registered with conventions (`MoreOpenWithDependency<T>.ctor(Dependency)`). 

As a workaround you can register the closed generic, this worked for me:
```c#
            conventions
                .ForType(typeof(MoreOpenWithDependency<object>))
                .SelectConstructor(ctors => ctors.First());
```

**Comment by ericstj** [comment]
Fix is probably to do another pass here when the type is a generic, to scan the open generic's ctors:
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Composition.TypedParts/src/System/Composition/TypedParts/Discovery/DiscoveredPart.cs#L87-L99

**Comment by ericstj** [comment]
Not a regression, moving to 6.0.  We'd accept a fix + unit tests here, if you'd like to give it a try.

**Comment by RaymondHuy** [comment]
Hi @ericstj I have created a PR for this issue. Could you review if it is satisfied ?
