### ISSUE TITLE
[Proposal] CancellationToken.Register<T>

### ISSUE THREAD

**Issue by deinok** [dotnet/runtime#30529]
Add the required overloads to accept generics. The following code better explains the idea:

```cs
public static CancellationTokenRegistration Register<T>(this CancellationToken cancellationToken, Action<T> callback, T state) {
    return cancellationToken.Register(s => callback.Invoke((T) s), state);
}
```

**Comment by stephentoub** [comment]
This would simply save the developer having to write out a cast, which doesn't seem worth the surface area.

The performance benefit would be if boxing for a value type T could be eliminated, but a) it's rare that I see value types as the state in calls to {Unsafe}Register, and b) supporting that would be non-trivial complication in the implementation, which pools the nodes that store the objects created by register, and such objects would then need to be generic and pooling would need to be utilized that appropriately partitioned by generics.

**Comment by stephentoub** [comment]
Closing per the comments in https://github.com/dotnet/runtime/issues/30529#issuecomment-771018370. Thanks.

**Comment by deinok** [comment]
@stephentoub Okey I see your point
