### ISSUE TITLE
Annotate corefx build artifacts with commit hashes

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#30520]
I would be nice if assemblies produced by the corefx repo were annotated with git metadata. For example:
```csharp
[assembly: AssemblyMetadata("GitBranch", "release/3.0")]
[assembly: AssemblyMetadata("GitHash", "abc123")]
```
Having this information available at runtime would help a great deal in traceability when investigating issues.

**Comment by ViktorHofer** [comment]
Triage: we support this but not necessary for 5.0.

**Comment by ViktorHofer** [comment]
Marking as up-for-grabs as I don't see us getting to this anytime soon. Since this issue was opened, we consolidated the corefx, coreclr, core-setup and mono repositories into the a new home: dotnet/runtime. Regarding SHA, it might be sufficient to just emit the repo's SHA and not the one from the SDK.

**Comment by am11** [comment]
I think these days we emit this info in both, managed and native artifacts.

#### Managed
```sh
$ dotnet tool install --global mooware.showassemblyinfo

$ dotnet-assemblyinfo ~/.dotnet7/shared/Microsoft.NETCore.App/7.0.0-preview.5.22258.4/System.IO.dll | grep Version
System.Runtime.Versioning.TargetFramework: .NETCoreApp,Version=v7.0
System.Reflection.AssemblyFileVersion: 7.0.22.25804
System.Reflection.AssemblyInformationalVersion: 7.0.0-preview.5.22258.4+3e5517beb897faf4592d23f036446561da1e5c23
System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

`AssemblyInformationalVersion` has the commit hash.

#### Native
```sh
$ strings ~/.dotnet7/shared/Microsoft.NETCore.App/7.0.0-preview.5.22258.4/libSystem.Native.so | grep '@(#)'
@(#)Version 7.0.22.25804 @Commit: 3e5517beb897faf4592d23f036446561da1e5c23
```

**Comment by ViktorHofer** [comment]
Awesome, thanks for validating that. For reference, https://github.com/dotnet/sdk/commit/aee0d72f5329d3a13c160ca4a4de46bc5f34c86c is the relevant change that enabled this in the SDK (which of course requires the SourceLink package to be referenced so that `SourceRevisionId` get set).
