### ISSUE TITLE
Reconsider Debug.Listeners API exposure

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#30536]
I am staring at a use case right now that I need to listen for ``System.Diagnostics.Debug.WriteLine`` messages and a listener would be just what I need to get the job done. Therefore, I strongly suggest [reconsidering Debug.Listeners exposure](/dotnet/standard/issues/84). Absent that we must look at adding unnecessary layers of overhead to our ``Debug.WriteLine`` listening efforts when a listener would fit the bill nicely.

**Comment by stephentoub** [comment]
Closing as addressed.
