### ISSUE TITLE
Question: Runtime type checking for method parameters.

### ISSUE THREAD

**Issue by Vake93** [dotnet/runtime#30546]
I have being experimenting with the ILGenerator and I found that if I pass an object of a different type than what is in the method signature the runtime doesn't throw any exceptions and still pass the object of the incorrect type into the method.

My question is: isn't there any runtime type checking to see if parameters passed to a method matches what's defined by the method signature? 

I've attached the minimal code to test this behavior as well.

[Program.zip](https://github.com/dotnet/corefx/files/3487004/Program.zip)

**Comment by steveharter** [comment]
Repro summary: dynamic method is defined with wrong parameter type and called with no runtime verification (random behavior more or less in the called method).

In .NET 4.7.2 the repro causes an exception:
```
[System.Security.VerificationException: Operation could destabilize the runtime.]
   at MethodA()
[System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.]
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.Emit.DynamicMethod.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Program.Main() :line 17
```

We should determine why the verification no longer occurs, and if it is desired in 5.0 (performance concerns for example).

cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
@jkotas Could this be because of the removal of the transparency infrastructure? I remember in the past needing to jump through hoops in order to get a `DynamicMethod` to accept an unverifiable IL stream.

**Comment by jkotas** [comment]
Yes, this looks like by design to me. We are not doing IL verification at runtime under any circumstances in .NET Core.
