### ISSUE TITLE
Proposal - Document the System.Reflection.PortableExecutable namespace

### ISSUE THREAD

**Issue by Akaion** [dotnet/runtime#30556]
This namespace has been part of framework & core for a while and has yet to receive official documentation both on MSDN and XML comments describing what each class / method does. I understand that this namespace is probably more for internal use, however, I have personally found it extremely useful when working with portable executable's and I think it would help a lot of developers out if you were to officially document this namespace.

**Comment by steveharter** [comment]
Closing as fixed (doc added).

cc @GrabYourPitchforks
