### ISSUE TITLE
JsonElement - Support Reading As Custom type

### ISSUE THREAD

**Issue by ares128** [dotnet/runtime#30593]
Sugguest add` JsonElement.GetObject<T>()` like `JToken.ToObject<T>` that support custom converter.

The json data structure we get from the external api will change depending on the situation, so it cannot be processed using the JsonSerializer.Deserialize method.

The `JToken.ToObject<T>` method from Json.net suits well. I hope New JSON API can have a equivalent method.

**Comment by layomia** [comment]
This scenario can be solved with https://github.com/dotnet/runtime/issues/31274 by reading first as JsonElement, perform validation, then deserialize with the serializer.
