### ISSUE TITLE
Several COM interop features marked as obsolete

### ISSUE THREAD

**Issue by bclothier** [dotnet/runtime#30605]
Referencing [this issue](https://github.com/dotnet/coreclr/issues/26207)

> The documentations for .NET Framework for various methods / objects defined within `System.Runtime.InteropServices` has been marked with `Obsolete,` mainly with comment that it may be unavailable in future releases. I'm including few samples:
> 
> [ICustomQueryInterface](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.icustomqueryinterface?view=netframework-4.8)
> [DispatchWrapper](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dispatchwrapper?view=netframework-4.8)
> [Marshal.GetObjectForNativeVariant](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getobjectfornativevariant?view=netframework-4.8)

There are several more but the concern here is that they are marked as obsolete and there is no indication that there will be a substitute. Because we depend on those, it worries me that they are marked as obsolete. Given that .NET Core has made compatibility a priority, I would suggest that marking them obsolete is premature until there's an actual suitable replacement for us to use.

**Comment by jozefizso** [comment]
Also `ICustomAdapter` from `System.Runtime.InteropServices`

**Comment by clairernovotny** [comment]
There are additional types that need to be fixed:

`ComEventInterfaceAttribute` and the two enum properties here https://github.com/dotnet/runtime/issues/720

**Comment by AaronRobinsonMSFT** [comment]
@clairernovotny The `ComEventInterfaceAttribute` is no longer marked `Obsolete`. What version of dotnet is being used?

https://github.com/dotnet/runtime/blob/1c18e8c038bbf2cca8297922519ebe05bb003f3c/src/libraries/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L219-L226

**Comment by clairernovotny** [comment]
I'm using 5.0.100-preview.4.20258.7
