### ISSUE TITLE
Obsolete the SecureString type

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#30612]
The `SecureString` type does not actually fulfill the promises it makes to developers. MSDN [already disrecommends](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring) its use in new code, and there's [other documentation](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md) listing some technical reasons why it can't fulfill its promises.

We've already seen customers who use this type in server applications in an effort to fulfill auditing / compliance requirements, then those customers get bitten because they fail their audits. I detailed this a little more [on Twitter](https://twitter.com/LeviBroderick/status/1154039234388381696), including suggesting mechanisms that customers could use to meet compliance requirements.

This legacy type is a different scenario than legacy types like `ArrayList` (the non-generic collection type). Types like `ArrayList` aren't recommended for new code because there are better alternatives available, but there's no real harm in keeping those older types around for compatibility reasons. Contrast this against `SecureString`, where the existence of the type is causing active harm to customers who use it and subsequently fail audits.

Since the type purports to make security promises to developers, and since it cannot fulfill those promises, it should be obsoleted in the next version of .NET Core.

/cc @blowdart @bartonjs

**Comment by sterenas** [comment]
Very interesting discussion around SecureString.  We've got some services that connect to Azure SQL DB from a WinForms app (No ASP.NET).  Need to encrypt the ConnectionString's password (this password is not typed, by an user, it's hardcoded in the ConnectionString itself).  I'm not able to use Azure's AKS as I'd still need to hardcode at least one secret.  Would you recommend SecureString or any other approach to get this done securely?  Thanks!

**Comment by GrabYourPitchforks** [comment]
@sterenas Your scenario involves encryption of data at rest, such as connection strings being read from a config file? `SecureString` never helped with those scenarios; it only ever worked on ephemeral data.

If you've got persisted data you need to encrypt on the local box, using X.509 certificates (for server farms) or DPAPI (for consumer machines) is a typical solution. The data is encrypted at rest. Your application decrypts the payload locally and then can operate on the plaintext as it sees fit.

**Comment by jhoneill** [comment]
> Your scenario involves encryption of data at rest, such as connection strings being read from a config file? `SecureString` never helped with those scenarios; it only ever worked on ephemeral data.

This may be technically true - in that when creating (for example) a PowerShell credential object it uses a secure string, but when we export that credential (e.g. `get-credential | export-clixml cred.xml`) the data is a long series of digits printed to a text file (not technically a secure string). That gets turned back into a secure string, and back into a credential. In that sense `SecureString` is pivotal to a process of securing keys and passwords at rest.

With a certificate the problem is merely moved. Whatever has the private key can authenticate. So now instead of having to keep a password or API key secure, the need is to keep the Private Key both secure secure at rest, AND available transparently.

**Comment by GrabYourPitchforks** [comment]
> _So now instead of having to keep a password or API key secure, the need is to keep the Private Key both secure secure at rest, AND available transparently._

Certificate private keys can be marked non-exportable. As long as the cert is in the personal or machine store, the calling process never has access to the raw private key material. That's why using certs is so popular especially in headless environments like production servers. For consumer environments, DPAPI offers a similar capability.

**Comment by GrabYourPitchforks** [comment]
Updated proposal at https://github.com/dotnet/designs/pull/147.
