### ISSUE TITLE
Suggestion/Question - Why is there no string type that enforces non-null, non-empty, non-whitespace strings?

### ISSUE THREAD

**Issue by BenjaminCharlton** [dotnet/runtime#30624]
# Why is there no string type that enforces non-null, non-empty, non-whitespace strings?

# BACKGROUND
I was reading about this great new feature coming in C# 8 of nullable reference types. See here:
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types

This new language feature allows the developer to specify whether or not a variable of a complex type is intended to allow null values or not and the compiler will issue warnings about the correct use of them.

This got me thinking that we have a similar problem with empty/whitespace string values. We always have to check them and throw an ArgumentException or ArgumentNullException, creating tedious and trivial lines of code.

# IDEA
My code is littered with checks for empty strings, null strings and whitespace-only strings.

I would guess that in most cases, a developer intends that a string argument should be non-null, non-empty and not just whitespace, so why is there no "safe" way to create and use such a string?

I appreciate that this wouldn't provide the same compile-time checking that non-nullable reference types provide in C# 8 but it would still be advantageous as it would drastically reduce the number of lines of code used to diligently check the validity of a string argument. It would provide run-time errors of invalid string arguments early on to facilitate debugging.

Probably I'm not the first person to think of this, and maybe there a good reasons not to do it, but I couldn't see any examples on a casual Google search.

Is this a good idea or a bad idea, and why/why not? Below is my attempt at creating such a class.

# CODE
`public class SafeString
    {
        private string _value;
        private readonly bool _shouldTrim;

        public SafeString(string value, bool shouldTrimNewValues = true)
        {
            if (value.IsNullOrWhiteSpace())
                throw new ArgumentException($"The value \"{value}\" is not valid." +
                    $" The value passed to the constructor of {nameof(SafeString)} must be a non-null, non-empty string" +
                    $" and it cannot be composed solely of whitespace.", nameof(value));

            _shouldTrim = shouldTrimNewValues;
            SetValue(value);
        }

        public string Value
        {
            get
            {
                return _value;
            }
            set
            {
                if (value.IsNullOrWhiteSpace())
                    throw new ArgumentException($"The value \"{value}\" is not valid." +
                        $" The new value assigned to the {nameof(Value)} property of an instance of {nameof(SafeString)} must be a non-null, non-empty string" +
                        $" and it cannot be composed solely of whitespace.", nameof(value));

                SetValue(value);
            }
        }

        private void SetValue(string value)
        {
            _value = _shouldTrim ? value.Trim() : value;
        }
    }`

# USAGE

`
SafeString name = new SafeString(" "); //  throws an error

name = new SafeString("Bernard"); // works fine

name.Value = "Bernie"; // we can change the value

name.Value = ""; // throws an error

string someName = name.Value; // we can get the value like this

Person person = new Person(name); // No need to check here that the string is empty or contains only whitespace as we know it's safe. Also no need for the constructor of the Person class to check because it knows that it's safe too.
`

**Comment by GrabYourPitchforks** [comment]
Is there anything actionable by the libraries team here? Seems the discussion has firmly settled on "this is scenario-specific and there's not really a good generalized concept we can add to the BCL."

**Comment by tannergooding** [comment]
Closing based on the discussion above.
