### ISSUE TITLE
Compiler Optimization problem and (Fma.MultiplyAdd) why does vfmadd231ps instruction not exists?

### ISSUE THREAD

**Issue by faruknane** [dotnet/runtime#30634]
I'd like to invite the net core team to discuss why there is only 1 VFMADD instruction in C# intrinsics in FMA class.

The first issue I want to mention is that when I want to do `x = x + y*z;` with vectors, C# compiler can't optimize the code by using VFMADD instructions. 

Here is the code:

```
                Vector<float> sum = new Vector<float>();
                Vector<float> v1 = new Vector<float>(left);
                Vector<float> v2 = new Vector<float>(right);
                sum = sum + v1 * v2;
                sum = v1 * v2 + sum ;
                sum += v1 * v2;
```
In assembly code I don't see any vfmadd being used (maybe its to make the code available in many devices as possible) . Anyway c# compiler should optimized this. So I stop using the vectors which you provide.  I started using **`Vector256<float>`** type.

Here my next code was like below:

```
                Vector256<float> sum = new Vector256<float>(); // assume sum is not zero
                Vector256<float> v1 = Avx2.LoadVector256(ptr_a);
                Vector256<float> v2 = Avx2.LoadVector256(ptr_b);
                sum = Fma.MultiplyAdd(v1, v2, sum);
```
Here is the equivalent assembly code:

![image](https://user-images.githubusercontent.com/37745467/63347220-5a8cd800-c35f-11e9-9d9b-b56d11a01530.png)

Problematic part:
```
00007FF7A60B1546  vfmadd213ps ymm1,ymm2,ymm0  
00007FF7A60B154B  vmovaps     ymm0,ymm1 
```
This code should be optimized like this:
00007FF7A60B1546  vfmadd231ps ymm0, ymm1, ymm2

I am new at this area. I m not sure if this affects the performance at all. The effect might be little. I'm trying to contest Intel MKL. I have to get my code optimized as possible as I can do. So please someone enlighten me about the issue above.

(In memory bottleneck case, this won't affect  the performance. However, in martix multiplication case where we use each number more than 1 time, If the code is written in the right way without being memory bottlenecked, using vfmadd231 might affect the speed. I'd like to hear about this topic from experts)

**Comment by tannergooding** [comment]
Closing as this is largely a register allocator issue and is already tracked by other issues such as https://github.com/dotnet/runtime/issues/12984
