### ISSUE TITLE
file in use exception

### ISSUE THREAD

**Issue by foxjazz** [dotnet/runtime#30640]
Create a project use process threading to start a process first to create a document for writing. And write to document every 2 seconds. During first write trigger separate thread to read same document. Use document sharing for both read and write. Notice when trying to access the second document (even if locks are around using of the documents) exception is thrown File is in use when trying to access the document from one or other thread.

**Comment by carlossanlop** [comment]
Triage: @foxjazz if you can get a repro for this issue, feel free to share it with us so we can take a look.
