### ISSUE TITLE
Should RID changes require rebuilding CoreFX and Core-Setup?

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#30689]
Currently the (primary) RID graph is built from CoreFX (`pkg/Microsoft.NETCore.Platforms`).

Even though CoreFX doesn't use any distro-specitic packaging, the RID tree we publish contains all of the distros we support, and some distros (and OSes) that we've gotten close to supporting.

When a new version of an existing distro releases while one of our releases is in the "released-and-supported" state we have to include the RID graph change as part of a monthly servicing release, and in extreme cases it could be the only change which causes a release to happen in a particular month.

Since the package is published to NuGet it also goes through the corefx published package flow, which requires extra manual processing every time a change is required.

If I understand the flow correctly, there's a step beyond corefx (in core-setup, I think) that consumes the data from the package either as a repackaging step, or it ingests it into a binary... or there's just a second manual copy somewhere.

(Primary) RID Graph contents questions:

* What belongs in the Microsoft.NETCore.Platforms package, and what should be in its own extension?
  * If the answer is only configurations that are important to .NET Core (coreclr.dll) and/or .NET CLI (dotnet[.exe]), should the Microsoft.NETCore.Platforms package contain "Mono-only" CPU architectures for distros that are important to both?
* Do we ever remove unsupported OS/distro versions from the RID graph?
* If the runtime (coreclr, mono, etc) is also considered in the RID graph do we do a combinatoric explosion? (distro/arch/runtime)

And while CoreFX builds this data, it doesn't have any tests or anything for the data beyond the build (so if CI triggers it was pointless and just wasting time and CPU somewhere).  If anywhere has tests for the RID graph there's the potential for an error to get caught much later than the change.

To me this all suggests the RID graph belongs somewhere else.

cc: @ericstj @jkotas @dagood @nguerrera

**Comment by ericstj** [comment]
There is no action for this in 5.0 since we need the runtime graph in dotnet/runtime to build the shared framework, it must remain here for the time being. 

> What belongs in the Microsoft.NETCore.Platforms package, and what should be in its own extension?

All runtimes supported by .NET, both coreclr and mono.

> Do we ever remove unsupported OS/distro versions from the RID graph?

At the moment no as size of the graph to support these is not yet a problem, though I could see us doing so in the future on major revisions.

> If the runtime (coreclr, mono, etc) is also considered in the RID graph do we do a combinatoric explosion? (distro/arch/runtime)

We are not representing this via RIDs (at the moment).  I don't expect it to be combinatoric explosion.  Whenever that feature is designed we can have that input.

Closing this as I don't think it's tracking any work and questions have been addressed.
