### ISSUE TITLE
Dogfooding docs need some love

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#30685]
Using these instructions, at the "dotnet restore" step I consistently get errors like "package not found netcoreapp x.x.x.x"

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#more-advanced-scenario---using-your-local-corefx-build

.@ViktorHofer mentioned it looks out of date. Can we get them updated?

**Comment by ViktorHofer** [comment]
Dup of https://github.com/dotnet/runtime/issues/30574
