### ISSUE TITLE
Alternative to attributes for System.Text.Json serialization metadata

### ISSUE THREAD

**Issue by orcun** [dotnet/runtime#30694]
Attributes restrict the usage, especially for auto-generated codes. A type safe code based run-time configuration would be preferable in many scenarios. In other words, a generic fluent builder API to configure serialization per class and properties would be a great improvement.

Frankly I was surprised to find that there were just attributes.

**Comment by layomia** [comment]
Triage: we don't have enough data around the customer need to build this sort of extension point at this time. A workaround here is to use a custom converter to handle ignore semantics.

We can reopen this issue if an end-to-end scenario is clearly defined.

**Comment by orcun** [comment]
@layomia Custom converters look powerful but too verbose. I guess benefits of fluent builder API is not so straightforward to explain. Perhaps I should develop such functionality as an external library instead. Thanks for your consideration.

**Comment by layomia** [comment]
@orcun, if you want to prototype this in https://github.com/dotnet/corefxlab, we could collaborate with you.
