### ISSUE TITLE
Throwing Error for Gdip when creating a SolidBrush variable

### ISSUE THREAD

**Issue by devilnest** [dotnet/runtime#30704]
I found this is a common problem which can be resolved with installing libgdiplus but this 'trick' doesnt help in my case.

My spec:
Linux: centos-release-7-5.1804.el7.centos.2.x86_84
.NET Core version: 2.1
System.Drawing.Common (4.5.1)
libgdiplus: libgdiplus-2.10-10.el7.x86_64
also installed libgdipls-devel

Code which delivers a error:
```csharp
class CardBuilder
{
   private readonly Brush _secondInformationColor = new SolidBrush(Color.FromArgb(179, 179, 179));

   public CardBuilder(){}
}
```
And the error is:
The type initializer for 'Gdip' threw an exception.
at System.Drawing.SafeNativeMethods.Gdip.GdipCreateSolidFill(Int32 color, IntPtr& brush)
at System.Drawing.SolidBrush..ctor(Color color)

If I find a solution, I will put the answer in the current issue

[EDIT:]
Changing to NET CORE 2.2 : doesn't help

**Comment by safern** [comment]
Thanks @devilnest 

This is definitely that we're not finding libgdiplus installed in the OS and that is why we're failing when GDI is initialized.

This thread has a bunch of instructions on how to set it up correctly. https://github.com/dotnet/core/issues/2746

Please let me know if that doesn't help.
