### ISSUE TITLE
Exact column names to be passed in IDataReader

### ISSUE THREAD

**Issue by kontacthimanshu** [dotnet/runtime#30707]
Starting with .Net Core 2.2 I am having to pass column names exactly matching with database table. Before .Net Core 2.2 it was not the case I could pass either exactly matching or in block or small letters and it would work just fine. Though the document on MSDN still suggest that .NET Core 2.2 is behaving like previous versions but that is not the case. Please take a look at urgent basis.

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by roji** [comment]
No repro was ever provided.
