### ISSUE TITLE
Feature request: Make it possible to determine where a CancellationToken was canceled

### ISSUE THREAD

**Issue by zarenner** [dotnet/runtime#30713]
A difficulty with using cancellation tokens today is that when an `OperationCanceledException` is thrown, it's often hard or impossible to determine where the cancellation occurred, or even which cancellation token is responsible as it may not be in scope to check against. Linked tokens add additional complexity, since it isn't possible to compare them against original tokens in a meaningful way (https://github.com/dotnet/corefx/issues/20787's "IsDerivativeOf").

Since there are obviously performance and memory concerns around storing stack traces that might make this infeasible to go into the framework itself, an alternative would be to add some extensibility that would allow a separate library to implement this. For example, a very naive solution might be a static hook any time `Register` is called on any token, so that it can be tracked. I'm sure there are better solutions as well.

This isn't something that necessarily needs to be enabled all the time - being able to enable it just when debugging would be sufficient. Today it's just frustrating that hunting down the source of an `OperationCanceledException` (especially one that somewhat infrequently repros) is often difficult without making code changes.

**Comment by chenxinyanc** [comment]
I come across this issue recently and would like to provide a use case of such feature request. Consider the following code [[.NET Fiddle]](https://dotnetfiddle.net/Ws3jRt):
```c#
using System;
using System.Threading.Tasks;

Task GetCancellingTask() {
	var tcs = new TaskCompletionSource();
	tcs.SetCanceled();
	return tcs.Task;
}

Console.WriteLine(System.Environment.Version);
await GetCancellingTask();
```
The output is
```
5.0.0
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at <Program>$.<<Main>$>d__0.MoveNext()
--- End of stack trace from previous location ---
   at <Program>$.<Main>(String[] args)
Command terminated by signal 6
```

There is no hint in the slightest about where this Task gets cancelled in the stack trace. All we know is the exception is thrown when `await`ing the result of `GetCancellingTask`. This can lead to much trouble if the actual `TaskCompletionSource` is cancelled from some function deeply nested inside the call stack of `GetCancellingTask`.

Note that if you throw a `TaskCanceledException` by yourself or via [`CancellationToken.ThrowIfCancellationRequested`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.throwifcancellationrequested?view=net-5.0), you should have information about where the cancellation happens. For example [[.NET Fiddle]](https://dotnetfiddle.net/isc41h):
```c#
using System;
using System.Threading.Tasks;

Task GetCancellingTask() {
	var tcs = new TaskCompletionSource();
	// tcs.SetCanceled();
	try {
		throw new TaskCanceledException();
	} catch (Exception e) {
		tcs.SetException(e);
	}
	return tcs.Task;
}

Console.WriteLine(System.Environment.Version);
await GetCancellingTask();
```

The output is
```
5.0.0
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at <Program>$.<<Main>$>g__GetCancellingTask|0_0()              <-- here!
--- End of stack trace from previous location ---
   at <Program>$.<<Main>$>d__0.MoveNext()
--- End of stack trace from previous location ---
   at <Program>$.<Main>(String[] args)
Command terminated by signal 6
```

What we needed is something like this.

**Comment by stephentoub** [comment]
I understand and can sympathize with the goal here.  I'm not sure how it could be done in a pay-for-play manner, though.  To make progress here, someone would need to propose a concrete API(s) for this and prototype it in corelib. To be feasible, this could not increase the size of CancellationTokenSource or CancellationToken, nor negatively impact the cost of common APIs like ctor/Register/Unregister, as that would negatively impact the super common code paths.  I'm skeptical there's a good answer here, but I'm happy to be proven wrong.
