### ISSUE TITLE
API Proposal: Type.IsAssignableTo(Type)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#30714]
Background
----
The api `Type.IsAssignableFrom(Type)` is [quite common to mistakenly use backwards](https://twitter.com/Nick_Craver/status/1166820786818179072) because it flows unexpectedly with surrounding code (swapping the subject and object; the type you are interested in becoming a parameter rather than staying as the caller).

Proposal
----
To alleviate this introducing a reversal of the parameters either as extension or method would be helpful to differentiate and provide clarity:

```csharp
partial class Type
{
    public bool Type.IsAssignableTo(Type type) 
        => type.IsAssignableFrom(this);

    public static bool IsAssignableTo<T>()
        => typeof(T).IsAssignableFrom(this);
}
```
or
```csharp
partial static class TypeExtensions
{
    public static bool Type.IsAssignableTo(this Type type, Type assignableType)
        => assignableType.IsAssignableFrom(type);

    public static bool IsAssignableTo<T>(this Type type)
        => typeof(T).IsAssignableFrom(type);
}
```

Precedence
----
`Type.IsSubclassOf(Type)` works in this direction so currently the syntax is
```csharp
typeof(derived).IsSubclassOf(typeof(base));

typeof(base).IsAssignableFrom(typeof(derived)); // swapped subject object

typeof(IInterface).IsAssignableFrom(typeof(Implementation)); // swapped subject object
``` 

While reversing 
```csharp
typeof(derived).IsSubclassOf(typeof(base)); 

typeof(derived).IsAssignableTo(typeof(base)); 

typeof(Implementation).IsAssignableTo(typeof(IInterface)); 
``` 

Example usage
----
Given
```csharp
public class ConstrainedGeneric<T> where T : Stream
{}
```
Rather than writing
```csharp
public static void Main()
{
    Type genericT = typeof(ConstrainedGeneric<>);
    Type genericParam = genericT.GetGenericArguments()[0];
    
    if (typeof(Stream).IsAssignableFrom(genericParam))
    {
        Console.WriteLine(true);
    } 

    // Displays True.
}
```

You can write
```csharp
public static void Main()
{
    Type genericT = typeof(ConstrainedGeneric<>);
    Type genericParam = genericT.GetGenericArguments()[0];
    
    if (genericParam.IsAssignableTo(typeof(Stream)))
    {
        Console.WriteLine(true);
    } 

    // Displays True.
}
```

/cc @NickCraver @davkean @davidfowl

**Comment by bartonjs** [comment]
Approved with a parameter name that better helps with usage.

```C#
public partial class Type
{
    public bool IsAssignableTo(Type? targetType) =>
        targetType == null ? false : targetType.IsAssignableFrom(this);
}
```

We also discussed renaming the parameter for IsAssignableFrom, but we would tackle that as a separate proposal.

**Comment by davidfowl** [comment]
FINALLY!

**Comment by john-h-k** [comment]
FWIW, as @reflectronic  pointed out
> For whoever mentioned this in API review, the parameter name for IsAssignableFrom is not `type`, it's `c`
