### ISSUE TITLE
Read from location on console

### ISSUE THREAD

**Issue by Happypig375** [dotnet/runtime#30738]
So that `SetCursorPosition` + `ReadLine` can be called without the input overwriting the console. Currently on Windows, this requires P/Invoke: https://stackoverflow.com/questions/12355378/read-from-location-on-console-c-sharp

**Comment by adamsitnik** [comment]
No answer to the question asked in September 2019, closing.

@Happypig375 Please feel free to respond to the question and reopen the issue. Thanks!
