### ISSUE TITLE
System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout hangs in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#30732]
https://dnceng.visualstudio.com/public/_build/results?buildId=332322&view=ms.vss-test-web.build-test-results-tab&runId=9745396&resultId=175895&paneView=attachments

Configuration: netcoreapp-Linux-Release-x64-(Alpine.38.Amd64.Open)ubuntu.1604.amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-09ca40b-20190620184125

```
  Discovering: System.Net.Mail.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Mail.Functional.Tests (found 137 test cases)
  Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 2)
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:02:10
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:04:10
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:06:10
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:08:10
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:10:10
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:12:10
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestZeroTimeout', Elapsed: 00:14:10
```

@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by safern** [comment]
Failed again here: https://dev.azure.com/dnceng/public/_build/results?buildId=505562&view=ms.vss-test-web.build-test-results-tab&runId=16050798&resultId=177375&paneView=attachments

**Comment by safern** [comment]
I guess we can close this in favor of: https://github.com/dotnet/runtime/issues/31719 which has all the builds and coredumps information. 

We should just make sure to include the test name in the title for discoverability.

**Comment by ViktorHofer** [comment]
Closing in favor of #31719
