### ISSUE TITLE
Kestrel server does not get grade A in SSL tests because it has no cipher suit preference

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#30767]
_From @ChrML on Thursday, September 5, 2019 7:09:29 AM_

### Description
From ASP Core 3.0 preview6 and newer it is now possible to get a grade B, instead of a previous grade F, on the SSL test (https://www.ssllabs.com/ssltest/). Because from 3.0 the insecure cipher suits are now disabled by default.

But still in 3.0-preview8, the Kestrel server does not have any cipher suit preference. This caps the SSL test grade to B instead of A. Grade A servers are regarded the most secure servers.

### Describe the solution you'd like
The server should prefer the "Perfect Forward Secrecy" compliant cipher suits (ECDHE) over the weaker cipher suits.

### Additional context
Here is the SSL report from the cipher suit chapter (on a 3.0-preview8 application):

> # Cipher Suites
> ## TLS 1.2 (server has no preference)
> TLS_RSA_WITH_AES_128_CBC_SHA (0x2f) WEAK 128
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013) ECDH secp521r1 (eq. 15360 bits RSA) FS WEAK 128
> TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c) WEAK 128
> TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c) WEAK 128
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027) ECDH secp521r1 (eq. 15360 bits RSA) FS WEAK 128
> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f) ECDH secp521r1 (eq. 15360 bits RSA) FS 128
> TLS_RSA_WITH_AES_256_CBC_SHA (0x35) WEAK 256
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014) ECDH secp521r1 (eq. 15360 bits RSA) FS WEAK 256
> TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d) WEAK 256
> TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d) WEAK 256
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028) ECDH secp521r1 (eq. 15360 bits RSA) FS WEAK 256
> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030) ECDH secp521r1 (eq. 15360 bits RSA) FS 256
> TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8) ECDH secp521r1 (eq. 15360 bits RSA) FS 256

Here is the description from SSL labs why the Kestrel server is capped to grade B:

> ## Penalty for not using forward secrecy (B)
> Forward secrecy (FS) also known as perfect forward secrecy (PFS), is a property of secure communication protocols in which compromises of long-term keys does not compromise past session keys. Forward secrecy protects past sessions against future compromises of private key. The very popular RSA key exchange doesn’t provide forward secrecy. You need to support and prefer ECDHE suites in order to enable forward secrecy with modern web browsers.

> SSL Labs will start penalizing servers that don’t support forward secrecy; Grade will be capped to B. We will not penalize sites that use suites without forward secrecy provided they are never negotiated with clients that can do better.

Simply making the server prefer the existing ECDHE cipher suits over the weak cipher suits will suffice for getting a grade A.

_Copied from original issue: aspnet/AspNetCore#13700_

**Comment by wfurt** [comment]
is there something we need to do for 5.0 @bartonjs or should we just close it for now and document it via issue @davidfowl linked?

**Comment by bartonjs** [comment]
It's something I'm actively working on for 5.

**Comment by wfurt** [comment]
is there separate issue or should I assign this to you and perhaps change area? If you proceed with the plan we talk about it while back, there won't by any changes to SslStream, right?

**Comment by wfurt** [comment]
oops. missed the self assignment.

**Comment by bartonjs** [comment]
> there won't by any changes to SslStream, right?

Currently it looks like the changes will be in the native shim; but since SslStream is the only affected component the area path seems correct.

**Comment by karelz** [comment]
We need to verify the E2E tests tp make sure this covers everything.
@Tratcher is it something you can run easily?

We also need to document the behavior and how to opt-out.

**Comment by Tratcher** [comment]
Running the SslLabs test is hard because it requires public IPs, DNS, certs, etc..

Writing functional or integration tests for Kestrel to ensure it's meeting certain standards is quite easy, we just need to know what to check for. Does someone have a list of the criteria?

Tests that need to tweak a machine wide resource like openssl.cnf are a different issue though.

**Comment by davidfowl** [comment]
We should do a manual test once we get all the features integrated.

**Comment by bartonjs** [comment]
https://github.com/drwetter/testssl.sh/ is pretty useful in this regard.

**Comment by wfurt** [comment]
I did manual testing on Azure image with Ubuntu18.04.
```
dotnet new mvc
dotnet run
```

- default app with default self signed certificate.

![SSL2](https://user-images.githubusercontent.com/14356188/91522936-4489ef80-e8b0-11ea-8928-2142ed0e974a.png)

It would get A without trust issue. So we seems to be good there. 

I also did check with https://en.internet.nl mentioned above. It does pass the cipher test failed before and the scanner only complain about lack of HSTS (and trust of course) 

![image](https://user-images.githubusercontent.com/14356188/91523345-5750f400-e8b1-11ea-9700-887fc5d78851.png)


Unless somebody objects or want more tests I'm going to close this as finished.

**Comment by karelz** [comment]
Thanks @wfurt, that is awesome result!
What is the "trust issue"? Is it the fact we do not support self-signed certificates?

**Comment by ChrML** [comment]
> Thanks @wfurt, that is awesome result!
> What is the "trust issue"? Is it the fact we do not support self-signed certificates?

Agree, this is awesome, and exactly what I was hoping for. A new application should be secure by default.

Trust issue has nothing to do with our application. It's just that the tested application was configured with a self-signed certificate that is not trusted by any root authority. It's expected unless you obtain a signed certificate for the test, or automate this test with a service like Lets Encrypt.

**Comment by wfurt** [comment]
yes, this is because I used self-signed certificate and there is no good how to make it "trusted" by the tools. 
As well as I used the default dev cert with "localhost" and I'm scanning "toweinfu.westus2.cloudapp.azure.com" so the name does not match. It should not really matter since the work was focus on protocol versions and ciphers. 

Not that this is not applicable to old systems with OpenSSL 1.0. Since they cannot do CipherPolicy and configurations, we excluded them for compat reasons.

**Comment by wfurt** [comment]
fixes with sequence of linked PRs

**Comment by shoe-diamente** [comment]
Using the Docker image `mcr.microsoft.com/dotnet/core/aspnet:3.1` and the settings specified in this [other issue](https://github.com/natemcmaster/LettuceEncrypt/issues/142) it doesn't seem to work.

I'm also using Lettuce Encrypt which might be overriding some configurations (but doesn't seem so looking at the source code).

Even though I explicitly disable TLS 1.1 and TLS 1.0 via:

```
httpsOptions.SslProtocols = System.Security.Authentication.SslProtocols.Tls12 | System.Security.Authentication.SslProtocols.Tls13;
```

for example, I still get:

![Screen Shot 2020-09-11 at 11 48 28](https://user-images.githubusercontent.com/40760781/92906460-c4719700-f424-11ea-952b-ffff534d389b.png)

**Comment by ChrML** [comment]
@shoe-diamente I don't think these changes have made it to .NET Core 3.1. It's scheduled for .NET 5.

**Comment by shoe-diamente** [comment]
@ChrML I see, thanks.
