### ISSUE TITLE
[CodeDom] Empty lines are indented

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#30761]
By using the [CodeDom example](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-create-a-class-using-codedom#example) from [How to: Create a Class Using CodeDOM](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-create-a-class-using-codedom) you can see with a `cat -e SampleCode.cs` that empty lines are empty as they should be but are indented as any other lines.
```csharp
namespace CodeDOMSample {^M$
    using System;^M$
    ^M$
    ^M$
    public sealed class CodeDOMCreatedClass {^M$
        ^M$
        // The width of the object.^M$
        private double widthValue;^M$
```

**Comment by danmosemsft** [comment]
@verdie-g missed your reply. Publicly visible API changes are to be avoided. Hopefully that answers you questions..

**Comment by jeffhandley** [comment]
I'm closing this as "Won't Fix" as the amount of effort required to fix this fully and properly isn't justified. Unfortunately, the `IndentedTextWriter` is too stateful, relying on side effects from one write to affect the next write, and unwinding that proved to be more challenging than is worthwhile here. https://github.com/dotnet/runtime/pull/61587#issuecomment-968684470

Thanks for filing the issue though, @verdie-g; it was worth a shot!
