### ISSUE TITLE
Future of System.Data.SqlClient for 5.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#30772]
This issue is mainly to discuss the future of System.Data.SqlClient package.
Currently it is shipped as an out of box package and public surface area of this freezed.

Do we want to keep shipping this package in 5.0.0 or should we just want to remove this from 5.0 onward ?

cc @cheenamalhotra, @Gary-Zh , @david-engel, @safern @ericstj

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/runtime/pull/2275
