### ISSUE TITLE
PipeReader.ReadAsync can return empty segments

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/runtime#30786]
I just noticed that segments in a ReadResult can be empty:

![grafik](https://user-images.githubusercontent.com/10261186/64445911-ce590f80-d0d7-11e9-846d-ae255df18171.png)
I assumed that the first segment was never empty, so I often use `result.Buffer.First.Span[0];` to access the first byte.

Is this intended behaviour? Can this be caused by me writing to the pipe in a wrong way? This is how I fill my pipe from a `System.IO.Compression.DeflateStream`:

```c#
private async Task Decompress(PipeWriter writer, ReadOnlyMemory<byte> data, int count)
{
    InflateInputStream.Position = 0;
    InflateInputStream.Write(data.Span.Slice(0, count));
    InflateInputStream.Position = 0;
    InflateInputStream.SetLength(count);
    int read;

    do
    {
        Memory<byte> memory = writer.GetMemory(data.Length * 2);
        read = InflateOutputStream.Read(memory.Span);
        writer.Advance(read);
    }
    while (read != 0);
    await writer.FlushAsync();
}
```

**Comment by Trolldemorted** [comment]
A year has past, can you estimate when this will be fixed? I see you removed it from the 5.0 milestone, which is unfortunate.

**Comment by freddyrios** [comment]
so, what's the idiomatic way to get the first byte, since this is unsafe: `ros.First.Span[0]`
what about the second byte, is this also problematic? `ros.Slice(1).First.Span[0]`

**Comment by Trolldemorted** [comment]
I have built a repro project here: https://github.com/Trolldemorted/EmptySegmentsBug/tree/371c7ceca7412f4313257c720965162a1b56ae76/EmptySegmentsBug

**Comment by davidfowl** [comment]
So I upgraded the repro to  use netcoreapp3.1 and the System.IO.Pipelines 6.0.3 and I get an empty segment at the end. When I upgrade to .NET 6 the problems goes away (likely from changes to the Stream).

PS: The code is also incorrect [here](https://github.com/Trolldemorted/EmptySegmentsBug/blob/371c7ceca7412f4313257c720965162a1b56ae76/EmptySegmentsBug/Program.cs#L66), it should be:

```
if (result.Buffer.Length == 0 && (result.IsCanceled || result.IsCompleted))
```

We should fix any bugs that result in the PipeReader producing empty segments though. Narrowing down this repro more might help figure out the exact reason why there's an empty segment at the end.

**Comment by davidfowl** [comment]
OK I have a repro. Generally when the length is passed into GetMemory we need to handle the case where's there's an existing segment allocated with nothing written into it, but more space is being requested than is available:

```C#
using System;
using System.IO.Pipelines;
using System.Threading.Tasks;

namespace EmptySegmentsBug
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var pipe = new Pipe();
            
            // Get a new block but don't write anything
            var buffer = pipe.Writer.GetMemory();
            pipe.Writer.Advance(0);
            await pipe.Writer.FlushAsync();

            // Get a new block
            buffer = pipe.Writer.GetMemory(4096 * 2);
            pipe.Writer.Advance(buffer.Length);
            await pipe.Writer.FlushAsync();

            await ReadAndDump();

            async Task ReadAndDump()
            {
                var result = await pipe.Reader.ReadAsync();
                Console.Write("[");
                bool first = true;
                foreach (var segment in result.Buffer)
                {
                    if (!first)
                    {
                        Console.Write(",");
                    }

                    Console.Write(segment.Length);
                    first = false;
                }
                Console.WriteLine("]");
                pipe.Reader.AdvanceTo(result.Buffer.End);
            }
        }
    }
}
```

This prints: `[0,8192]`
