### ISSUE TITLE
CookieContainer do not handle session cookies (when Expires is not specified)

### ISSUE THREAD

**Issue by M-Boukhlouf** [dotnet/runtime#30798]
# CookieContainer do not handle session cookies (when Expires is not specified)

According to this page: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

> The maximum lifetime of the cookie as an HTTP-date timestamp. If not specified, the cookie will have the lifetime of a session cookie. A session is finished when the client is shut down meaning that session cookies will get removed at that point.

Yet, in this case when the Expires is not specified in this Set-Cookie header:
`Set-Cookie: name=value; path=/store; httponly`
The CookieContainer set the Expires property to "1/1/0001 12:00:00 AM"
Which is expired and the cookie is not used in the following requests.

**Comment by karelz** [comment]
Closing as we do not have repro to make it actionable for us.
