### ISSUE TITLE
Cannot serialize F# dictionary

### ISSUE THREAD

**Issue by xperiandri** [dotnet/runtime#30803]
``` F#
let parameters = dict <| seq { ("Secret", "secret") }
let contentJson = JsonSerializer.Serialize parameters
```

Throws `NotSupportedException` https://github.com/dotnet/corefx/blob/da1f8120aeec867bbd81829358ed348d323b1d14/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.HandleDictionary.cs#L144

Why can it happen if parameters variable is of type `IDictionary<string,string>`?

**Comment by layomia** [comment]
Closing - this work/investigation is part of https://github.com/dotnet/runtime/issues/29812.
