### ISSUE TITLE
Add generic overloads for MethodInfo.CreateDelegate

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/runtime#30800]
Currently usages of `Delegate.CreateDelegate` tend to be along these lines:

`(Func<object>)Delegate.CreateDelegate(typeof(FuncObject), methodInfo)`

For complicated delegates, this can be quite annoying and error prone.

it would be relatively simple to add generic overloads and it would make the API much nicer to use.

#### API suggestion

```csharp
public partial class MethodInfo
{
    // Current
    public virtual Delegate CreateDelegate(Type delegateType);
    public virtual Delegate CreateDelegate(Type delegateType, object target);

    // New
    public T CreateDelegate<T>() where T : Delegate => (T)CreateDelegate(typeof(T));
    public T CreateDelegate<T>(object? target) where T : Delegate => (T)CreateDelegate(typeof(T), target);
}
```

The generic methods would not be virtual, as they're just syntactic sugar around the existing virtual.

**Comment by terrajobst** [comment]
* We discussed dropping the generic constraint (because it makes the new API less useful to code that is generic and not constrained, because the constraint is recent).
* We'll keep it for now and will drop it if we see issues with the constraint.

```C#
public partial class MethodInfo
{
    // Current
    public virtual Delegate CreateDelegate(Type delegateType);
    public virtual Delegate CreateDelegate(Type delegateType, object target);

    // New
    public T CreateDelegate<T>() where T : Delegate => (T)CreateDelegate(typeof(T));
    public T CreateDelegate<T>(object? target) where T : Delegate => (T)CreateDelegate(typeof(T), target);
}
```
