### ISSUE TITLE
Race in Socket.BeginSendTo

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#30804]
There is a race in `Socket` when `BeginSendTo` is used on an unbound socket. You can see code for setting `_rightEndPoint`:

https://github.com/dotnet/corefx/blob/da1f8120aeec867bbd81829358ed348d323b1d14/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L2700-L2737

`SocketTaskExtensions.SendToAsync` wraps this and so is also affected.

`_rightEndPoint` is also used in `BeginReceiveFrom` in a way that could cause a parameter check to be "skipped" if `BeginSendTo` resets it to null.

**Comment by wfurt** [comment]
triage: we should run the repro to see if this is still applicable. Then close it if this is no longer issue or bring it to further triage. Currently no customer hit so probably low priority.

**Comment by wfurt** [comment]
I look at the relevant code and the linked fragments do not exist any more. This whole APM pattern was replaced by `Task` based implementation and Begin/End methods are on top of that. Closing.
