### ISSUE TITLE
Add .Net Framework TFM to System.Reflection.MetadataLoadContext

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet/runtime#30810]
Please add a net4* target such as (net46 or net461 ?) to System.Reflection.MetadataLoadContext as recommended by your own [Open-source library guidance
](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting).

I want to consume it in a msbuild (distributed via nuget) task which should run on VS2015+ and I really do not want to have to ship the extra netstandard support assemblies.
They have given me problem before and I really cannot change target framework or which version of netstandard assemblies msbuild is bundled with.

**Comment by joperezr** [comment]
This has now been fixed with package 4.7.2 via https://github.com/dotnet/corefx/pull/42901 and will be ported down for 5.0 release. The package is already available in NuGet.

**Comment by Daniel-Svensson** [comment]
Thank you
