### ISSUE TITLE
Build.cmd/Build.sh Help OS List

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#30826]
Build.cmd/Build.sh help lists only 2 possible options for OS: ` Windows_NT` and `Unix`. [This page](https://github.com/dotnet/corefx/blob/de38804d52f6b65f0f290b81383f01e6943a6d8f/Documentation/project-docs/developer-guide.md) lists: `Windows_NT`, `Unix`, `Linux`, or `OSX`. And in [Directory.Build.props](https://github.com/dotnet/corefx/blob/master/Directory.Build.props) can also be found `NetBSD` and `FreeBSD`.

What is the actual list of supported OSes? Could the help be of build scripts be updated to reflect that?

**Comment by ViktorHofer** [comment]
This was done with https://github.com/dotnet/runtime/commit/da97f17219da1cea3a53fbdb7f80b0a2012b982f#diff-891b50b7d5fe7380fc246ed310019d61.
