### ISSUE TITLE
Cleaning up packageIndex.json file to just have live building versions.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#30844]
Currently we record a bunch of stuff in our packageIndex.json file like

- Baseline Versions
- stable Package Version
- assembly-package relationship
- Inbox information

Currently we store all the stable versions and also specify the assembly version associated with that stable version.

The target here is to remove as much stuff possible and generate all this stuff at runtime.
This will help in maintaining the package and assembly versions.

cc @ericstj @ViktorHofer @danmosemsft

**Comment by ViktorHofer** [comment]
Closing as we are going to remove the packageIndex.json file entirely by migrating all pkgprojs to csprojs.
