### ISSUE TITLE
Add TaskCompletionSource.SetCanceled(CancellationToken)

### ISSUE THREAD

**Issue by Frassle** [dotnet/runtime#30862]
`TaskCompletionSource` currently has three methods to set it to canceled. `void SetCanceled()` which throws if the source is already completed, `bool TrySetCanceled()` which just returns false if the source is already cancelled, and `bool TrySetCanceled(CancellationToken)` which is like `TrySetCanceled` but also allows linking in a `CancellationToken`.

Can we also add `void SetCanceled(CancellationToken)` to use in cases where you want to make it clear that this should set the canceled state but you also want to link a `CancellationToken` in.
This is doable by writing your own that just throws if `TrySetCanceled` returns false but this can't easily get the `TaskT_TransitionToFinal_AlreadyCompleted` resource string to match the error message thrown by corefx. It also leads to people just writing `TrySetCanceled` and ignoring the result, which leads to less clear code and potentially hides bugs, or alternatively they write `SetCanceled` and throw away the token information (Me trying to fix one case of this in FSharp.Core is what lead to me raising this issue).

```C#
public class TaskCompletionSource<TResult>
{
    ...
    public void SetCanceled(CancellationToken cancellationToken);
    ...
}
```

**Comment by terrajobst** [comment]
* Looks good as proposed and follows the guidelines for `Try`-APIs

```C#
public class TaskCompletionSource<TResult>
{
    ...
    public void SetCanceled(CancellationToken cancellationToken);
    ...
}
```

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/runtime/pull/32696
