### ISSUE TITLE
FileSystemWatcher with a filter set to a specific file does not work on Ubuntu

### ISSUE THREAD

**Issue by iconics-janb** [dotnet/runtime#30871]
This code is expect to raise Changed event when file text.txt is changed:

                FileSystemWatcher watcher = new FileSystemWatcher("/usr/share", "text.txt");
                watcher.Changed += Watcher_Changed;
                watcher.NotifyFilter = NotifyFilters.LastWrite;
                watcher.EnableRaisingEvents = true;

It works OK in Windows, but in Ubuntu the event Changed is never raised. When the second parameter (filter) in FileSystemWatcher constructor is omitted and file "text.txt" is modified, then the Changed event is raised, but the FileSystemEventArgs.Name is different from "text.txt" (it was ".goutputstrem=ZJ8U7Z" in my case).

**Comment by JeremyKuhne** [comment]
Triage: As we weren't able to reproduce closing until/unless we get more info.
