### ISSUE TITLE
WebClient - Connection: Keep-Alive ALWAYS present.

### ISSUE THREAD

**Issue by kulashaker30** [dotnet/runtime#30927]
# Issue Title

WebClient is always sending 'Connection: Keep-Alive'

# General

I am having trouble with WebClient always getting timeout exception because the Connection header is always present in the request.

**Comment by davidsh** [comment]
>I am using now HttpWebRequest because I can remove the Connection header from it unlike in WebClient which I am getting an error when I try to remove it.

It's good you found a workaround by using 'HttpWebRequest' instead of 'WebClient'.

We don't plan to fix 'WebClient' for this scenario since it is a legacy class and we expect customers to move to either 'HttpWebRequest' or 'HttpClient' (most recommended).
