### ISSUE TITLE
System.Numerics.Vectors and System.Threading.Tasks.Extensions still in preview?

### ISSUE THREAD

**Issue by nick2893** [dotnet/runtime#30937]
With the release of .NET Core 3.0, I thought these would become official releases as well.  What are the plans to make these two packages "final" releases?

**Comment by tannergooding** [comment]
For System.Numerics.Vectors, these are now in-box and they don't ship out of box anymore, so I don't believe we will have any future releases.

@stephentoub, @terrajobst. Could you confirm and loop in the relevant owner for System.Threading.Tasks.Extensions?

**Comment by stephentoub** [comment]
System.Threading.Tasks.Extensions shipped.  It's not preview.

**Comment by terrajobst** [comment]
Looks we had one bad build with a higher number for `System.Threading.Tasks.Extensions`:

![image](https://user-images.githubusercontent.com/5169960/76023536-34cfb680-5ede-11ea-8af8-86ccbb753031.png)

That seems messed up. I'm not sure can obsolete that build but anybody on that drop will never gets updates. Can we bump the number and fix that?

**Comment by danmosemsft** [comment]
cc @ericstj

**Comment by ericstj** [comment]
We stopped shipping new versions of these packages in 3.x because they were absorbed into netstandard and we no longer had a reason to ship new versions.  In other words you use the old packages if you want to target older frameworks, if you want to target newer frameworks no package is needed.  @nick2893 was there something specific you were wanting from the new packages?

**Comment by nick2893** [comment]
I'm targeting .NET 4.6.1.  Among other reasons, nuget keeps pestering me to get the latest versions of all the packages.  Also, when I downloaded these particular ones, everything else was in preview (pre .NET Core release), and now there are non-preview versions for the other ones.  So, with the latest posted version being a preview build for so long, I am simply confused.

**Comment by ericstj** [comment]
I've unlisted those versions so hopefully that will clear things up.  Let me know if you have further questions.

**Comment by nick2893** [comment]
Thanks!  Do we know what was the difference in the content between the rogue versions and ones that preceded them?

**Comment by ericstj** [comment]
Nothing observable, API was frozen.  They weren't "rogue" they were just built along with the rest of the product for a few previews before they were dead-ended.  This is what happens for all of our packages when they get absorbed by the framework.
