### ISSUE TITLE
Remove dependencies on System.ComponentModel.TypeConverter.dll

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#30931]
We have several assemblies, e.g. System.Data.Common.dll, System.Diagnostics.EventLog.dll, etc., which are pulled in by the default ASP.NET Core app templates (either directly or because of ASP.NET dependencies) and that in turn reference stuff from System.ComponentModel.TypeConverter.dll.  It has a gigantic closure with lots of stuff explicitly rooted, and is adding a huge amount of state to a trimmed app.

**Comment by eerhardt** [comment]
> It has a gigantic closure with lots of stuff explicitly rooted, and is adding a huge amount of state to a trimmed app.

In .NET 5 we have removed the explicitly rooted entries in `System.ComponentModel.TypeConverter`. Taking the latest build, I created an ASP.NET webapp and added:

```xml
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
```

And `dotnet.exe publish -c Release -r win-x64`. This produced an app with ~36 MB of assets in the `publish` directory. Of that ~32 MB is `.dlls`. The resulting `System.ComponentModel.TypeConverter.dll` is 74 KB.

I believe this concern here has been addressed as only what is necessary in `System.ComponentModel.TypeConverter` is being preserved when linking. I'm going to close this issue. If this isn't the case, feel free to re-open.
