### ISSUE TITLE
Missing API: Guid.TryWriteBytes(..., out int bytesWritten)

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#30940]
Per API review, our `Guid.TryWriteBytes` method should have an overload which outs the number of bytes written to the destination buffer.

@tannergooding - you had also mentioned adding a similar API to `decimal`, but I don't see offhand which overload would be affected.

```C#
namespace System
{
    public partial struct Guid
    {
        public bool TryWriteBytes(Span<byte> destination, out int bytesWritten);
    }
}
```

**Comment by stephentoub** [comment]
@GrabYourPitchforks, @bartonjs, we should either just mark this as api-ready-for-review or close the issue :)

**Comment by dakersnar** [comment]
@GrabYourPitchforks @bartonjs bump, is this ready for review?

**Comment by bartonjs** [comment]
Added the missing member proposal, marked it ready for review.

Decimal's [TryGetBits](https://learn.microsoft.com/en-us/dotnet/api/system.decimal.trygetbits?view=net-7.0) does have an out parameter: `public static bool TryGetBits(decimal d, Span<int> destination, out int valuesWritten);`, so it probably got fixed before release.

**Comment by bartonjs** [comment]
Looks good as proposed.

Marking the non-out variant with EditorBrowsable.Never, but we decided to defer that to a later discussion (or never, as the case may be).  It may be more related to adding a non-try `int WriteBytes(destination)` than this overload.

```C#
namespace System
{
    public partial struct Guid
    {
        public bool TryWriteBytes(Span<byte> destination, out int bytesWritten);
    }
}
```

**Comment by hrrrrustic** [comment]
Maybe it would make sense to add more general method?
```C#
public static class MemoryMarshal
{
    public static unsafe bool TryWrite<T>(Span<byte> destination, ref T value, out int bytesWritten) where T : struct
}
```

The current implementation without `out int bytesWritten` anyways calculate required size that can be returned
https://github.com/dotnet/runtime/blob/dfa8efcf63eedae5331b0570ec9849ec0235d9ca/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/MemoryMarshal.cs#L477-L484

This will also help to avoid extra `if` to check result and set `16` or `0` in approved API
https://github.com/dotnet/runtime/blob/dfa8efcf63eedae5331b0570ec9849ec0235d9ca/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L862-L866

**Comment by AlexRadch** [comment]
Should be closed as a duplicate? https://github.com/dotnet/runtime/issues/86798

**Comment by tannergooding** [comment]
Resolved with https://github.com/dotnet/runtime/pull/87993
