### ISSUE TITLE
OdbcCommand ExecuteReaderObject SchemaOnly Confusion

### ISSUE THREAD

**Issue by Gavvers** [dotnet/runtime#30952]
Hello,

I was reading through the [OdbcCommand source](https://github.com/dotnet/corefx/blob/master/src/System.Data.Odbc/src/System/Data/Odbc/OdbcCommand.cs) and became confused about a couple of if-statements that seemed contradictory. 

The code in question starts at [708](https://github.com/dotnet/corefx/blob/ac99a1b7168bd32046a954c3f06012c0fa909bed/src/System.Data.Odbc/src/System/Data/Odbc/OdbcCommand.cs#L708)

```
if (!localReader.IsBehavior(CommandBehavior.SchemaOnly))
 {
     // Can't get the KeyInfo after command execution (SQL Server only since it does not support multiple
    // results on the same connection). Stored procedures (SP) do not return metadata before actual execution
    // Need to check the column count since the command type may not be set to SP for a SP.
    if ((localReader.IsBehavior(CommandBehavior.KeyInfo) || localReader.IsBehavior(CommandBehavior.SchemaOnly))
        && (CommandType != CommandType.StoredProcedure))
    {
    ...
```

So on 708, SchemaOnly command behaviors are excluded from the following code block, but inside said code block, SchemaOnly is tested again. It seems to me that that SchemaOnly test will always fail, no?

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to implement.
