### ISSUE TITLE
Make WCF dependency on compat pack automatic via a darc subscription

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/runtime#30962]
- [x] release/3.0
         Update the WCF packages in the compat pack to version 4.6.0 for the next servicing release '3.0.1'.

- [x] release/3.1 and master
         The WCF master branch (vNext for us is release 3.1) has numerous new APIs not added in release/3.0.0 which we would like to see reflected in the 'apisof.net'.
         Our master branch default channel: `(497)  https://github.com/dotnet/wcf @ refs/heads/master -> .NET Core 5 Dev`

**Comment by ericstj** [comment]
I believe the versions have been updated, should we set up a subscription here?

**Comment by safern** [comment]
The biggest challenge in setting up a subscription is that, whenever we try to release a stable coherent build, that would mean that WCF would be at the bottom of the stack because `dotnet/runtime` depends on it now, so I don't know if that makes sense and if we want to do that. cc: @mmitche

**Comment by mmitche** [comment]
If it's just updating to released package versions, we should just keep this on-demand.

**Comment by ViktorHofer** [comment]
@StephenBonikowsky do we still need this? I don't see any 5.0 preview packages shipped.

**Comment by StephenBonikowsky** [comment]
I'm not on the WCF team anymore, adding @HongGit and @mconnew

**Comment by ViktorHofer** [comment]
The wcf packages don't change often anymore and I just recently updated the patch version of the packages with https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f. Closing.
