### ISSUE TITLE
Enable Git LFS and merge the corefx-testdata repo with corefx

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#30973]
From my conversation with @ericstj, the steps would be:

- Make corefx-testdata adopt arcade.
- Create a rolling build.
- Have corefx subscribe to the output of that build.

cc @safern @joperezr @ViktorHofer @Anipik

**Comment by ViktorHofer** [comment]
We decided against merging these two repositories and instead

1) renamed corefx-testdata to https://github.com/dotnet/runtime-assets
2) added CI integration
3) Arcadified the repository
4) and enabled dependency flow
