### ISSUE TITLE
System.Security.Principal.Windows different versions lib vs ref

### ISSUE THREAD

**Issue by Jmales** [dotnet/runtime#30988]
I'm using the latest 4.6.0 version of the package and noticed after a while that the assembly version for netstandard2.0 in lib is **4.1.2.0** while in ref, for the same framework it is **4.1.1.0**.

This is causing problems at runtime because the build numbers are different. I tried using **bindingRedirect**  in the meanwhile but I couldn't get it to work so far.

The error at runtime:

`=== Pre-bind state information ===
LOG: DisplayName = System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)`

`LOG: Assembly Name is: System.Security.Principal.Windows, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.`

**Comment by bartonjs** [comment]
@safern / @joperezr Is there anything that needs to be done here?  (Maybe there was already a big sweep across all packages?)

**Comment by safern** [comment]
I believe we unified AssemblyVersions to be 5.0.0.0 now and I don't see this project setting it's own AssemblyVersion anymore so it should be using the default which is 5.0.0.0

So I think this can be closed.
