### ISSUE TITLE
Out of bounds error with CryptoStream.Write using FromBase64Transform

### ISSUE THREAD

**Issue by freefalling** [dotnet/runtime#30993]
The following code worked fine in .net framework 4.7.1, but in .net core 2.1/2.2/3.0 throws an ArgumentException `Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection` on the `CryptoStream.Write` method.

 ```csharp
public byte[] DecryptBase64(byte[] data)
{
      FromBase64Transform tBase64 = new FromBase64Transform();
      MemoryStream streamDecrypted = new MemoryStream();
      CryptoStream stream = new CryptoStream(streamDecrypted, tBase64, CryptoStreamMode.Write);

      stream.Write(data, 0, data.Length);
      stream.FlushFinalBlock();
      stream.Close();

      return streamDecrypted.ToArray();
}
```
The  `data` param has 2316 elements (0-2315), the offset is 0 and length is 2316. It does not make any sense to me an out of bounds error when calling  `stream.Write(data, 0, data.Length)`.

This issue seems to be related to dotnet/runtime#23550 and dotnet/runtime#23206, the problem for my team is that we can't make use of the `DES.Create()` workaround because, as you can see, we are using `FromBase64Transform`

**Comment by bartonjs** [comment]
(Sorry for it being a long time)

It looks like the bug was introduced in the original port to .NET Core, the only workaround that I can think of for 2.1 is to pre-filter whitespace out of your input before letting the FromBase64Transform process it.  The probably easier answer is to upgrade to 3.1, since the bug is fixed in that release.

**Comment by bartonjs** [comment]
.NET Core 2.1 is no longer in support, and no supported versions have this error, closing.
