### ISSUE TITLE
CertificateRequest Crashing (SIGILL) on MacOS

### ISSUE THREAD

**Issue by daeken** [dotnet/runtime#31020]
I've run into an odd issue where I'm hitting a SIGILL on MacOS 10.14.6 during the CertificateRequest constructor on Mac. I've tried every combination of hash methods, key sizes and types (RSA and ECDSA), padding methods, etc and they all appear to fail.  The test case below shows the behavior: 

	using System;
	using System.Security.Cryptography;
	using System.Security.Cryptography.X509Certificates;

	namespace MacCertCrash {
		class Program {
			static void Main(string[] args) {
				Console.WriteLine("Step 1");
				var rsa = RSA.Create(2048);
				Console.WriteLine("Step 2");
				var name = new X500DistinguishedName("C=US/ST=Foo/L=Bar/O=Baz/OU=Hax/CN=tempest");
				Console.WriteLine("Step 3");
				var req = new CertificateRequest(name, rsa, HashAlgorithmName.SHA512,
					RSASignaturePadding.Pss); // CRASH HERE
				Console.WriteLine("Step 4");
				var cert = req.CreateSelfSigned(DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddYears(10));
				Console.WriteLine("Done?");
				Console.WriteLine(cert);
			}
		}
	}

The crash occurs in standard debug or release builds.

**Comment by bartonjs** [comment]
Since no one else was able to reproduce this crash there's not much we can do to investigate.  We'd be happy to look with more data.
