### ISSUE TITLE
'GroupCollection' does not contain a definition for 'Count'

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/runtime#31027]
I recently tried to move my web application from .net cor 2.2 to 3.0. While the following code used to compile and run just fine, it now gives the error at every occurrence where Count is invoked on a System.Text.RegularExpressions.Match object

internal virtual bool IsValidKeywordFormat(Match m, out string error)
        {

            int matches = m.Groups.Count(t => t.Success);
            ......

Error: CS1061 : 'GroupCollection' does not contain a definition for 'Count' and no accessible extension method 'Count' accepting a first argument of type 'GroupCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by danmosemsft** [comment]
Marking 5.0 since we should add the compat note.

**Comment by danmosemsft** [comment]
Fixed by https://github.com/dotnet/docs/issues/19545
