### ISSUE TITLE
Building .NET Core 3.0 RTM on FreeBSD

### ISSUE THREAD

**Issue by FeodorFitsner** [dotnet/runtime#31039]
I hope this is the right place to ask.

As .NET Core 3.0 matured to RTM are there any works to have an official distro for FreeBSD or at least building guidelines? Right now, top google result is [Building .NET Core 3.x on FreeBSD](https://github.com/dotnet/corefx/wiki/Building-.NET-Core-3.x-on-FreeBSD) guide by @wfurt, but it looks like it's not updated/working with .NET Core 3.0 RTM.

Thank you!

**Comment by zezba9000** [comment]
Any plans to do this for .NET Core 6 runtime?
How difficult was porting this btw?

**Comment by wfurt** [comment]
Active discussion is under https://github.com/dotnet/runtime/issues/14537 @zezba9000.

**Comment by wfurt** [comment]
3.0 is way old. There is separate issue to track general effort.
