### ISSUE TITLE
System.Composition.ImportAttribute cannot be used on fields

### ISSUE THREAD

**Issue by dnickless** [dotnet/runtime#31041]
I am getting some compilation issue after updating an older codebase to System.Composition.

![image](https://user-images.githubusercontent.com/985774/66028363-3b0bd200-e4fd-11e9-88a1-b9a7da8507ba.png)

Is it possible that `AttributeUsage.Field` should be added to the declaration here?

https://github.com/dotnet/corefx/blob/dcc9f626eeb0751d4ba4499f623aac42d2e95c10/src/System.Composition.AttributedModel/src/System/Composition/ImportAttribute.cs#L13

The documentation on https://docs.microsoft.com/en-us/dotnet/api/system.composition.importattribute?view=dotnet-plat-ext-3.0 states:

> Specifies that a property, **field**, or parameter value should be provided by the host container.

**Comment by ericstj** [comment]
The documentation is wrong.  This can only be specified on properties and parameters.  We should fix the docs.
