### ISSUE TITLE
System.Threading.Tasks.Tests.ParallelForTests.TestInvokeDOPAndCancel failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#31048]
https://dev.azure.com/dnceng/public/_build/results?buildId=374084&view=ms.vss-test-web.build-test-results-tab&runId=11444164&resultId=132449&paneView=debug

Configuration: `netcoreapp-Linux-Debug-x64-Debian.9.Amd64.Open`

```
TestInvokeDOPAndCancel: > FAILED! Cancellation+exception not effected.\nExpected: False\nActual: True

   at System.Threading.Tasks.Tests.ParallelForTests.TestInvokeDOPAndCancel() in /_/src/System.Threading.Tasks.Parallel/tests/ParallelForTests.cs:line 1074
```

cc @stephentoub

**Comment by stephentoub** [comment]
From a quick skim, the test looks correct to me.  I'm going to assume there was something broken lower in the stack when this occurred, and close this. If it happens again, we should definitely investigate.
