### ISSUE TITLE
IPInterfaceProperties.DhcpServerAddresses does not work on Ubuntu

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#31054]
This collection always returns empty list even if DHCP is configured and used.  

Code to process DHCP is hardcoded  in `System/Net/NetworkInformation/NetworkFiles.cs`
```c#
 public const string DHClientLeasesFile = "/var/lib/dhcp/dhclient.leases";System/Net/NetworkInformation/NetworkFiles.cs:        public const string DHClientLeasesFile = "/var/lib/dhcp/dhclient.leases";
```
But on Ubuntu (and perhaps other Linux distributions) DHCP configuration is files specific to interface. That makes more sense and you many need more instances and writing to single global file hard.

```
furt@net-dale:/var/lib/dhcp$ ps axu| grep dhcp
root      1952  0.0  0.0  25660  3356 ?        Ss   Apr24   0:00 /sbin/dhclient -1 -4 -v -pf /run/dhclient.eno1.pid -lf /var/lib/dhcp/dhclient.eno1.leases -I -df /var/lib/dhcp/dhclient6.eno1.leases eno1
```

**Comment by webczat** [comment]
And what happens if you have another dhcp client? For example dhcpcd or systemd-network builtin client or... Not sure if I know anything else.

**Comment by karelz** [comment]
@webczat what would yo recommend that should happen?
I believe that the natural answer is: we will try to understand the most used schemas/files.

**Comment by webczat** [comment]
well. generally I am for either making it unsupported, or return empty collection. It is of course only my opinion and may be unacceptable, but there is no way to implement it in a way that will always work, at least no way that I know of. It is a bit of hit or miss, because it will depend on arbitrary user decisions, and more about the preferred software doing dhcp than about it's configuration. Also at least in case of systemd-networkd I am not even sure you can get this info without dbus. And I believe it would be used this way when someone tries to use systemd-nspawn containers with default private networking. There is generally no standard interface for that.

**Comment by wfurt** [comment]
I think we can make improvements - like in this particular case. As use of systems becomes more common, we will need to figure out how to talk to it  - and not just for DHCP. We should probably open separate issues. cc: @tmds

**Comment by webczat** [comment]
sure. note however that systemd-network is not replacing network-manager or at least it still didn't. As in, the situation with that particular feature can probably be improved only by adding each possible case, like info from dhclient specific files, info from dhcpcd specific files, info from dbus, you could even get info from network-manager... I am not sure what is the maintenance cost of all that. I am also not sure if all these files/interfaces are readable by non-root to begin with.

**Comment by webczat** [comment]
Sorry for spamming, but just discovered that and wanted to separate that for it to be more clear:

I am using archlinux, and networkmanager now has a builtin dhcp client. I am not sure how it works, I even didn't realize which update introduced that. I am not sure if this writes lease files at all or not. At first glance it looks like it does, but it is more difficult to predict the names, as they don't only encode interface names, they seem to also encode connection uuids. Getting that from dbus should still be possible (not sure if it is exposed though).

That change in network manager seems to me like being relatively new.
