### ISSUE TITLE
Dotnet runtime aarch=arm64 fails execute asp.net core MVC wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by GrilleGustav** [dotnet/runtime#3106]
## Steps to reproduce
Install dotnet core runtime arm64.
dotnet publish -c Release -r linux-arm // asp.net core mvc example generated by VS. 2017

## Expected  behavior
start Kestrel server and host website

## Actual behavior
rock64@rock64:~/publish$ dotnet PluginSystem.dll
Failed to load PI▒7, error: /home/rock64/publish/libhostpolicy.so: wrong ELF class: ELFCLASS32
An error occurred while loading required library libhostpolicy.so from [/home/rock64/publish/]

## Environment data
Rock64 
bionic-minimal-rock64-0.6.28-197-arm64.img.xz
Linux rock64 4.15.10 dotnet/core-setup#1 SMP Sun Apr 1 14:42:24 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by elinor-fung** [comment]
Per https://github.com/dotnet/runtime/issues/3106#issuecomment-377825743, the application should be published targeting arm64. Please open another issue if you continue to hit problems on the latest version of .NET.
