### ISSUE TITLE
XmlDocument incorrectly serializes elements with an empty-string child text node when pretty-printing

### ISSUE THREAD

**Issue by mklement0** [dotnet/runtime#31079]
`System.Xml.XmlDocument` - unlike `System.Xml.Linq.XDocument` - incorrectly serializes an element that has an empty-string child text node when producing pretty-printed output.

(The idea behind creating an empty-string child text node - as opposed to using a _truly empty_ (childless) element - is to force serialization of such an element in the `<tag></tag>` form, as opposed to in the self-closing empty-tag form (`<tag />`).
For a real-world scenario and manifestation of this bug, see [this StackOverflow question](https://stackoverflow.com/q/58246585/45375).)

### Steps to reproduce:

```csharp
using System;
using System.Xml;
using System.IO;

public static class Program
{
  public static void Main()
  {

    var xd = new XmlDocument();
    xd.LoadXml("<root><Elem/></root>");

    // Add an empty-string child text node to <Elem>
    xd.DocumentElement.FirstChild.InnerText = "";
    
    xd.Save("t.xml");

    Console.WriteLine(File.ReadAllText("t.xml"));
 }

}
```

### Expected output:

```none
<root>
  <Elem></Elem>
</root>
```
That is, the element should serialize in the `<tag>...</tag>` form, with the empty string as the (implied) inner text.

### Actual output:

```
<root>
  <Elem>
  </Elem>
</root>
```

That is, the element unexpectedly serialized across _two lines_, which introduced extraneous whitespace as the value of the `<Elem>` element (the value of its child text node).

**Comment by buyaa-n** [comment]
Thank you for informing the issue @mklement0, it is sounds like a bug first, but turns out it was by design, and the behavior is documented, so I don't think we want to fix this 
![image](https://user-images.githubusercontent.com/45579687/73702709-6288cc00-46a2-11ea-98bd-2a338e139c69.png)

**Comment by mklement0** [comment]
Thanks, @buyaa-n; while this may be by design, the behavior is flawed:

The resulting representation _does not faithfully represent the original document_ because the text child node of `Element` now contains `\n<space><space>`, not the empty string, as originally.

**Comment by mklement0** [comment]
Thanks, @buyaa-n; while this may be by design, the behavior is flawed:

The resulting representation _does not faithfully represent the original document_ because the text child node of `Element` now contains `\n<space><space>`, not the empty string, as originally.

Unlike the whitespace between `<root>` and `<Elem>` and `</Elem>` and `</root>` the parser (at least by default) parses the `\n<space><space>` _as an explicit child text node_.

While serializing as `<Elem></Elem>` (on the same line, with no interior whitespace)  is arguably an _ambiguous_ representation (does the element have an empty-string text child node, or does the element have no children?), it makes for more sensible behavior on parsing it again: `<Elem>` is parsed as having  _no_ child elements.

(I don't knpw enough about XML to tell whether it's even possible in textual representations to distinguish between a childless element one and one with an empty-string text child node.)

**Comment by buyaa-n** [comment]
@mklement0 understand your point, i have looked up XMl specification, there is no guidance about how we should treat empty string in such case, that means it's up for the API's and it is our design
 not a bug. As it is even documented this way it mean our customers used and expecing it as it is and if we change this behavior that will be breaking change for them

> The resulting representation does not faithfully represent the original document because the text child node of Element now contains \n<space><space>, not the empty string, as originally.

`\n<space><space>` is added because of indention only, which by default on `XmlDocument`, it is not like we are updating user's original input.

**Comment by mklement0** [comment]
Understood, @buyaa-n; my mistaken assumption was that the current representation introduces _significant_ whitespace and thereby alters the document's content, but with the default parsing methods that turns out _not_ to be true (see bottom).

In the absence of this problem, the current behavior is then indeed a design decision - and I get the concern about changing existing behavior.

It's a moot point now, but I personally think that `<Elem></Elem>` would have made more sense and it makes for a more compact representation without sacrificing readability (the explicit empty-string child-node information is lost in _both_ representation).

---

The reason for the mistaken assumption was that I had used PowerShell's [`Select-Xml`](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/select-xml) cmdlet for testing, which with _file_ input (only) unexpectedly preserves the whitespace stemming from pretty-printing on parsing; I've created in the PowerShell repo for that: https://github.com/PowerShell/PowerShell/issues/11771

**Comment by mklement0** [comment]
P.S.: In case someone stumbles upon this in need of the `<Elem></Elem>` serialization: with the trick in the initial post you _do_ get this representation if you use the `.Save()` method of type [`System.Xml.Linq.XDocument`](https://docs.microsoft.com/en-US/dotnet/api/System.Xml.Linq.XDocument) instead of type [`System.Xml.XmlDocument`](https://docs.microsoft.com/en-US/dotnet/api/System.Xml.XmlDocument) (an unfortunate inconsistency).
