### ISSUE TITLE
When are crossgen images loaded?

### ISSUE THREAD

**Issue by livarcocc** [dotnet/runtime#3107]
_From @Alois-xx on April 2, 2018 0:1_

## Steps to reproduce
1. Create a new Console application for netstandard. Used runtime is 2.0.6 x64/x86 e.g. NetCoreExe on Windows 
2. Copy all dependencies into one directory via dotnet publish 
    **NetCoreExe>dotnet publish -r win-x64 -c release  /p:TargetFramework=netcoreapp2**
3. Move exe and associated files to publish folder
    **NetCoreExe\bin\Release\netcoreapp2\win-x64>move \*.\* publish**
3. Crossgen assemblies in publish folder
   **NetCoreExe\bin\Release\netcoreapp2\win-x64\publish>for %i in (*.dll) do %USERPROFILE%\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.6\tools\crossgen.exe /JITPath "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\clrjit.dll"  /Platform_Assemblies_Paths "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6" %i**
4. Execute 
   **NetCoreExe.exe**
    or 
   **dotnet  NetCoreExe.dll**
   ...

## Expected  behavior
Generated Native images are loaded into the hosting application

## Actual behavior
No crossgen images are used. 
This is also the case for pure dotnet called processes. When the .NET Runtime is installed a precompiled "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Private.CoreLib.ni.dll" is supplied but I never see this loaded. 

Is there an obvious trick I did miss? I did compile .NET Core ca. one year ago by myself where I could use crossgen and directly debug loading issues. But the released 2.0.6 runtime seems to be ignore crossgen images. I have downloaded a fresh x86 dotnet core 2.0.6 but that did also not change things. 
When setting corehost_trace=1 I did not find any output related to crossgen images. 

## Environment data
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

_Copied from original issue: dotnet/cli#8963_

**Comment by davidwrighton** [comment]
Compilation with Crossgen is now integrated into the sdk, and "does the right thing".

**Comment by Alois-xx** [comment]
I have installed .NET 5.0 RC1. Where is crossgen located? I have searched for all exes below C:\Program Files\dotnet\ and have not found crossgen.exe. Will it be part of .NET 5.0?

**Comment by jkotas** [comment]
crossgen is part of runtime pack NuGet package (e.g. https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.win-x64/5.0.0-rc.1.20451.14). The runtime pack is downloaded by .NET SDK on demand.
