### ISSUE TITLE
 Could not load type 'System.Text.Json.JsonDocumentOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by pc-tradelab** [dotnet/runtime#31086]
Hi I am having this issue when trying to migrate my identityserver4 server to dotnetcore3.0 : 

`TypeLoadException: Could not load type 'System.Text.Json.JsonDocumentOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
Microsoft.AspNetCore.Authentication.Google.GoogleHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
Microsoft.AspNetCore.Authentication.Google.GoogleHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)
Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler<TOptions>.HandleRemoteAuthenticateAsync()
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()`

The version I am using : 
`
Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

`

Thanks !

**Comment by ericstj** [comment]
I took a look at this repro and found the cause.  The references are coming from Microsoft.AspNetCore.ProtectedBrowserStorage which is very old and was built against a pre-release version of System.Text.Json prior to some type renames.  I did find that the newer version of the package (0.1.0-alpha.19521.1) avoids these TypeLoadExceptions.  Given this package was never shipped stable, I'm guessing there is a different place for you to get this API.  https://www.nuget.org/packages/Microsoft.AspNetCore.ProtectedBrowserStorage

It looks to me like you should probably be getting those types from https://github.com/dotnet/aspnetcore/blob/ed5034eb8ecde1e0151f70da43203affd1375c46/src/Components/Web.Extensions/src/Microsoft.AspNetCore.Components.Web.Extensions.csproj instead.  cc @mkArtakMSFT @MackinnonBuck
