### ISSUE TITLE
FileSystemWatcher leaks when EnableRaisingEvents set

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#31100]
Related to dotnet/runtime#30954 (at least this was found while debugging the same issue). Creating a `FileSystemWatcher` and `EnableRaisingEvents` set to true will root the `FileSystemWatcher` instance by the handle table. 

We had a customer creating a `FileSystemWatcher` per request (indirectly) in an ASP.NET Core and it lead to a memory leak.

```
> gcroot -all 000001ff54786c20                                                                                                                                     HandleTable:
    000001FBD45913C8 (async pinned handle)
    -> 000001FF54788E28 System.Threading.OverlappedData
    -> 000001FF54788DE0 System.Threading.ThreadPoolBoundHandleOverlapped
    -> 000001FF54788D80 System.Threading.IOCompletionCallback
    -> 000001FF54786C20 System.IO.FileSystemWatcher
```

**Comment by stephentoub** [comment]
Closing, since no one's demonstrated a strong need for 3.1.
