### ISSUE TITLE
[Feature request] A way to customize the line separator in StringBuilder

### ISSUE THREAD

**Issue by kekekeks** [dotnet/runtime#31115]
Right now it's impossible to get consistent behavior across platforms. Which is kind of important when working with file formats or network protocols that are sensitive to the line separator.

A commonly used workaround is an extension method like:
```cs
public static StringBuilder AppendLineLf(this StringBuilder sb, string line)
   => sb.Append(line).Append('\n');
```
but this approach can't be used when we are passing the StringBuilder to a library from nuget.

The proposal is to add a separate constructor that accepts a line separator.

**Comment by matt-psaltis** [comment]
Cross platform snapshot testing is painful due to this hardcoded behaviour. Please consider :D

**Comment by danmoseley** [comment]
We need an API proposal here in the same form as the new API proposal template. It can either be here or in a new issue.

**Comment by dakersnar** [comment]
As stated above, this proposal needs to be formalized. Closing this issue for now. Please feel free to open a new issue that follows the API suggestion template. Our API review process and a link to the template/good example is here:  https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps.
