### ISSUE TITLE
Mark Assembly.CodeBase as obsolete

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#31127]
`Assembly.Location` and `Assembly.CodeBase` are very similar, but not the same thing. To reduce confusion, we should mark it as obsolete.

### Reason

Having two things that are similar, but not identical always causes confusion. Here is [an example](https://github.com/aspnet/AspNetCore/issues/14501#issuecomment-537286033).

As @jkotas [said](https://github.com/aspnet/AspNetCore/issues/14501#issuecomment-538606720):

> `Assembly.Location` is strictly better than `Assembly.CodeBase`.
> 
> `Assembly.CodeBase` is an obsolete property. The only reason why it was included in .NET Core was .NET Framework compatibility. The original purpose of `Assembly.CodeBase` was CAS (Code Access Security). It was meant to describe where the assembly was downloaded from for the Internet Zone security checks. It also explains some of its weird behaviors. For example, if the assembly is loaded as byte array, it returns the location of the caller of the `Assembly.Load` method.

### Proposed API

```C#
namespace System.Reflection
{
    public partial class Assembly
    {
        [Obsolete("Use Location instead.")]
        public virtual string CodeBase { get; }
    }
}
```

**Comment by JoshSchreuder** [comment]
I [started looking at this](https://github.com/JoshSchreuder/runtime/commit/653f1bdbdb33cefeebe9bd27d543c7648dfefafb), but might need a clarification as I'm unfamiliar with the code structure.

With my change, I'm getting the following errors where `CodeBase` / `EscapedCodeBase` are used elsewhere (`DesigntimeLicenseContext`, `Helper.Win32Unix`, `RoAssembly`). Can I please get some tips on the best way to resolve these?

```
System\ComponentModel\Design\DesigntimeLicenseContext.cs(88,56): error CS0618: 'Assembly.EscapedCodeBase' is obsolete: 'EscapedCodeBase is only included for .NET Framework compatibility. Use Location instead.' [C:\Work\dotnetruntime\src\libraries\System.ComponentModel.TypeConverter\src\System.ComponentModel.TypeConverter.csproj]
System\ComponentModel\Design\DesigntimeLicenseContext.cs(111,45): error CS0618: 'Assembly.EscapedCodeBase' is obsolete: 'EscapedCodeBase is only included for .NET Framework compatibility. Use Location instead.' [C:\Work\dotnetruntime\src\libraries\System.ComponentModel.TypeConverter\src\System.ComponentModel.TypeConverter.csproj]
System\IO\IsolatedStorage\Helper.Win32Unix.cs(57,36): error CS0618: 'Assembly.CodeBase' is obsolete: 'CodeBase is only included for .NET Framework compatibility. Use Location instead.' [C:\Work\dotnetruntime\src\libraries\System.IO.IsolatedStorage\src\System.IO.IsolatedStorage.csproj]
System\Reflection\TypeLoading\Assemblies\RoAssembly.cs(44,39): error CS0672: Member 'RoAssembly.CodeBase' overrides obsolete member 'Assembly.CodeBase'. Add the Obsolete attribute to 'RoAssembly.CodeBase'. [C:\Work\dotnetruntime\src\libraries\System.Reflection.MetadataLoadContext\src\System.Reflection.MetadataLoadContext.csproj]
System\Reflection\TypeLoading\Assemblies\RoAssembly.cs(45,39): error CS0672: Member 'RoAssembly.EscapedCodeBase' overrides obsolete member 'Assembly.EscapedCodeBase'. Add the Obsolete attribute to 'RoAssembly.EscapedCodeBase'. [C:\Work\dotnetruntime\src\libraries\System.Reflection.MetadataLoadContext\src\System.Reflection.MetadataLoadContext.csproj]
```

**Comment by jkotas** [comment]
`System.ComponentModel.TypeConverter` should be switched to use `Assembly.Location`. The rest should use #pragmas to disable the warnings.

> does this need something done per Better Obsoletions?

@jeffhandley is working on the plan for better obsoletions IDs. You can leave the ID as TODO in the PR.

**Comment by JoshSchreuder** [comment]
Cheers @jkotas, I've raised #39261

**Comment by jkotas** [comment]
> We should also mark it as `[EditorBrowsable(Never)]`

@terrajobst Is marking it as `[EditorBrowsable(Never)]` still valid with the new obsoletion plan? We are marking a lot of other methods obsolete, but we are not marking them as `[EditorBrowsable(Never)]`. What is special about this method that it deserves to be marked with `[EditorBrowsable(Never)]`? 

cc @jeffhandley

**Comment by jeffhandley** [comment]
Per the [non-goals](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/better-obsoletion.md#non-goals) of the better obsoletion spec, it is not expected that we'll mark `[EditorBrowsable(Never)]` in conjunction with the obsoletion but that they should be independent decisions.  I took the approach to _not_ apply the `EditorBrowsable` attribute in the big obsoletion PR.

I recommend we remove the `EditorBrowable` attributes from the obsoletions here too.

**Comment by JoshSchreuder** [comment]
Updated PR with the new Obsoletion stuff, and removed the `EditorBrowsable` attribute, thanks all!

**Comment by vitek-karas** [comment]
Should we also look into `AssemblyName.CodeBase` and `AssemblyName.EscapedCodeBase` - they are very similar to `Assembly.CodeBase`:
* Runtime fills in the same values for loaded assemblies
* When constructed manually the value is preserved
* Runtime never actually consumes these values - calling `Assembly.Load(AssemblyName)` completely ignores these properties on the name.

**Comment by danmosemsft** [comment]
Was there an answer to this question?

> Should we also look into AssemblyName.CodeBase and AssemblyName.EscapedCodeBase - they are very similar to Assembly.CodeBase:

**Comment by terrajobst** [comment]
Yes, @jkotas mentioned it [above](https://github.com/dotnet/runtime/issues/31127#issuecomment-580388364):

> Assembly.EscapedCodeBase should be marked as obsolete as well.

And the [PR marked it](https://github.com/dotnet/runtime/pull/39261/files#diff-1d02aa10f6540e37197ff9f090ca1d9eR7572-R7573).

**Comment by vitek-karas** [comment]
What about the `AssemblyName` variants - they return basically the exact same thing... and AFAIK are not marked right now.
