### ISSUE TITLE
System.Text.Json Datetimeoffset should support +0000 offset

### ISSUE THREAD

**Issue by msmolka** [dotnet/runtime#31138]
Currently only offset presented by `+00:00` is supported, but `+0000` or `+00` is also allowed in ISO standard so these should be supported as well. 

`+02:00`, `+0200`, `+02`

`
An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00". 
`

**Comment by layomia** [comment]
We decided to strictly follow the ISO profile described in the [JSON DateTime/DateTimeOffset docs](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#the-extended-iso-8601-12019-profile-in-systemtextjson). This doc shows how to add custom support to the reader, writer, serializer, and JsonDocument/Element.
