### ISSUE TITLE
XmlSchemaAnyAttribute.Namespace throws NRE when not set before

### ISSUE THREAD

**Issue by martin-frydl** [dotnet/runtime#31134]
When I have "empty" instance of XmlSchemaAnyAttribute and access Namespace property, it throws NullReferenceException. This is caused by commit 2c22af8903522e54f71225c40ddd383b15632ae0 which now calls NamespaceList.ToString().

According to XML schema specification, namespace attribute is optional so it is valid to have it set to null. For example when I read XML schema with <xs:anyAttribute/>, .NET XML reader will create exactly the same instance - with null _ns field and also null NamespaceList. Later when I try to access the field, I get NRE. I get it also when I try to save schema back to serialized form. This time the exception is thrown from serialization due to optimization - the line of code in XmlSchemaAnyAttribute is not visible in exception stack trace.

How to reproduce:
var x = new XmlSchemaAnyAttribute().Namespace;

**Comment by buyaa-n** [comment]
3.0 port merged in Nov, closing
