### ISSUE TITLE
X509Extension.Format() doesn't work well in macOS system 

### ISSUE THREAD

**Issue by shidouli** [dotnet/runtime#31165]
MacOs:
PS > $ext.Format($false)
3042304006082B06010505073002863468747470733A2F2F73632D7072642D636F6D702D76633035342E656E672E766D776172652E636F6D2F6166642F766563732F6361

While the same certificate in Ubuntu:
PS > $ext.Format($false) CA Issuers - URI:https://sc-prd-comp-vc054.eng.vmware.com/afd/vecs/ca

Expected behavior
In the MacOs, it should return the same result with the one in Ubuntu

**Comment by bartonjs** [comment]
The more general item for this is #15445 (X509Extension extends AsnEncodedData).
