### ISSUE TITLE
API proposal: Unsafe.NullRef, IsNullRef

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#31170]
Proposed API
---
``` csharp
namespace System.Runtime.CompilerServices
{
    public class Unsafe
    {
        public bool IsNullRef<T>(ref T);
        public ref T NullRef<T>();
    }
}
```

`ref` cannot be null pointer in C#, but it is perfectly valid in IL. `ref` containing null pointers are useful for low-level optimizations. For example, https://github.com/dotnet/coreclr/pull/27195 uses them to make Dictionary lookups about 10% faster. There are several other examples in the .NET Core framework where we have used `ref` containing null pointers.

The Unsafe class does have building blocks that allow operations on null `ref` pointers (e.g. `Unsafe.AsPointer<T>(null)` creates null ref), but it obfuscates the intent and it is not as straightforward and lean as it can be. The proposed APIs will make it easier.

**Comment by broudy3** [comment]
What about `out` reference? Could the null check be added also for that? Something like:
  ```
public static bool IsNullOut<T>(out T value)
{
     SkipInit(out value);
     return IsNullRef(ref value);
}

example : IsNullOut(out NullRef<int>());
```

**Comment by GrabYourPitchforks** [comment]
@broudy3 what's the scenario for caring about 'out'?

**Comment by tannergooding** [comment]
That's really the C# contract however, not necessarily the IL contract. There are plenty of native methods, for example, which take a `T** result` where the other inputs are validated or special values are looked up if `result` is null and otherwise they perform the operation as normal.

**Comment by GrabYourPitchforks** [comment]
I agree, but we're talking about an API specifically for C# callers.

**Comment by tannergooding** [comment]
> for C# callers.

and F#, IL, C++/CLI, or any of the other languages the framework supports.

It is incredibly niche, but one you get into interop land, it's entirely reasonable, and if we are adding a version for `IsNullRef` and `IsNullReadOnlyRef`, it only seems reasonable to just expose `IsNullOut` for parity.
We only need `NullRef`, however, because `ref` can be narrowed to either `in` or `out`.

**Comment by GrabYourPitchforks** [comment]
> It is incredibly niche

That sounds like a good argument against adding it, especially since it's already doable by stringing together existing APIs. :) In IL and C++/CLI you can already trivially compare the reference against null using existing language syntax. No special function needed. I don't know enough about F# to make a statement there.

> and if we are adding a version for `IsNullRef` and `IsNullReadOnlyRef`

I'm still not personally convinced on the utility of the _in_ function. But I'm willing to cede that point.

**Comment by jkotas** [comment]
> > It is incredibly niche

> That sounds like a good argument against adding it, especially since it's already doable by stringing together existing APIs

+1 . `S.R.CS.Unsafe` is designed around C# `ref`s. `ref`s are the safest type to write unsafe byref arithmetic with. If you have something else, we can add methods to convert it to `ref`.

> I'm still not personally convinced on the utility of the in function.

+1. `in` is optional and it easy to get make mistakes in when writing unsafe byref arithmetic code.

**Comment by GrabYourPitchforks** [comment]
FWIW, we do seem to have a bunch more folks using byref arithmetic in high-performance code bases. I know that Tanner has been fielding questions along these lines lately. Is there any chance we might get first-class language support to make these scenarios a bit less error-prone? It should also obviate the need for some of the APIs as proposed here.

Strawman example:

```cs
public unsafe void DoIt(int* ip)
{
    // 'ip' is non-gc tracked pointer to int
    int* jp = i + 1; // jp points to an address 4 bytes after ip
    bool isNull = (ip == null);
    int deref = *ip;
}

public unsafe void DoIt(int& ip)
{
    // 'ip' is gc tracked pointer to int
    int& jp = i + 1; // jp points to an address 4 bytes after ip
    bool isNull = (ip == null);
    int deref = *ip;
}
```

One pit of failure from this is that the second example resembles a standard pointer, but it's a gc-tracked pointer. If you perform the arithmetic incorrectly you could end up making the GC very angry. But you already have that situation today if you use the `Unsafe` APIs improperly.

**Comment by jkotas** [comment]
This sounds like a proposal for https://github.com/dotnet/csharplang. I do not see one on this yet.

**Comment by jkotas** [comment]
> It should also obviate the need for some of the APIs as proposed here.

FWIW, `Unsafe` has been originally designed as a shortcut to get things done before we have something better. Some of the Unsafe APIs were obliviated by language features already.

**Comment by tannergooding** [comment]
Is there anything blocking this from being marked `ready-for-review`? Also, I think this should be milestone future as (AFAIK) it isn't critical for 5.0

**Comment by jkotas** [comment]
This was API reviewed once already and sent back with the `ref` vs `in` question. Do we like the proposal at the top after the follow up discussion?

I agree that this is not critical for 5.0.

**Comment by GrabYourPitchforks** [comment]
Your API as proposed LGTM.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Runtime.CompilerServices
{
    public class Unsafe
    {
        public bool IsNullRef<T>(ref T);
        public ref T NullRef<T>();
    }
}
```
