### ISSUE TITLE
API: long Math.BigMul(long, long, out long)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#31184]
### API Shape

To return 128 bit result (as per `long BigMul(int a, int b)`)
```csharp
partial class Math
{
    ulong BigMul(ulong a, ulong b, out ulong low);
    long BigMul(long a, long b, out long low);
}
```

### Use case

Manual multiply high is [now being used for Dictionary](https://github.com/dotnet/coreclr/blob/e532bf642a3a381d53ff52c234f29deb7d11e7a0/src/System.Private.CoreLib/shared/System/Collections/HashHelpers.cs#L103-L104)

Which looks like
```csharp
(uint)((((ulong)(uint)left * right >> 32) + (left >> 32) * right) >> 32)
```
When ideally it would be
```csharp
(uint)Math.BigMul(left, right, out _)
```

### Other langs
While it is what the asm does (i.e. `RDX:RAX ← RAX ∗ SRC`) the apis either use a 128bit value or the split pair.

MSVC: 
```cpp
__int64 _mul128(__int64 Multiplier, __int64 Multiplicand, __int64 *HighProduct)
__int64 __mulh(__int64 a, __int64 b)
```
Others use `*` overloading on a `__uint128_t` type

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System
{
    public partial class Math
    {
        public ulong BigMul(ulong a, ulong b, out ulong low);
        public long BigMul(long a, long b, out long low);
    }
}
```

**Comment by stephentoub** [comment]
Implemented in https://github.com/dotnet/runtime/pull/35975
