### ISSUE TITLE
System.Text.Json does not serialize values in Dictionary<string, IInterface>

### ISSUE THREAD

**Issue by zachsaw** [dotnet/runtime#31186]
Serializing `Dictionary<string, IInterface>` causes the output to be like Dictionary with null values when they're not nulls.

e.g.
```C#
    JsonSerializer.Serialize(new Dictionary<string, IFoo> {{"test", new Foo {X = 100}}});

    public class Foo : IFoo
    {
        public int X { get; set; }
    }

    public interface IFoo
    {
    }
```

Wrong output:
```
{"test":{}}
```

Newtonsoft produces the correct output:
```
{"test":{"X":100}}
```

If you explicitly cast Value to object, serialization works correctly.
e.g. 
```C#
JsonSerializer.Serialize(new Dictionary<string, IFoo> {{"test", new Foo {X = 100}}}
.ToDictionary(kvp => kvp.Key, kvp => (object) kvp.Value));
```

Correct output:
```
{"test":{"x":100}}
```

**Comment by layomia** [comment]
This falls under polymorphic serialization where we will call .GetType() on every options to serialize as the runtime type. Closing as a duplicate of https://github.com/dotnet/runtime/issues/29937.
