### ISSUE TITLE
CustomAttribute with Array Properties sets nulls incorrectly

### ISSUE THREAD

**Issue by JamesAshworth** [dotnet/runtime#31195]
An attribute with two array properties does not behave as expected if the first array property is set to a value and the second array property is set to null. If the two arrays are of the same type, the second property is set to the same value as the first property. If the two types are incompatible, an exception is thrown when the attribute is constructed, stating that the second property cannot be found.

Attached are two variations on a simple program that replicates each issue.

[Same Type](https://github.com/dotnet/corefx/files/3737962/Program.txt)
[Incompatible Types](https://github.com/dotnet/corefx/files/3737971/Program.2.txt)

**Comment by steveharter** [comment]
Moving to future based on priority + schedule.
