### ISSUE TITLE
ElapsedEventArgs doesn't have a public constructor

### ISSUE THREAD

**Issue by ashelleyPurdue** [dotnet/runtime#31204]
System.Timers.ElapsedEventArgs doesn't have a public constructor, despite just being a data class containing one property.  This makes it unnecessarily awkward to write a mock for something that uses an ElapsedEventHandler, because you need to use a workaround just to create this one object.

It's impossible to solve this by subclassing ElapsedEventArgs, because the SignalTime property is read-only and therefore cannot be set by your constructor.

**Comment by ericstj** [comment]
This seems like a reasonable request.

**Comment by ericstj** [comment]
At this point it's too late for this to go into 6.0.0.

**Comment by JasonDWilson** [comment]
Did this make it into 7?  It really is a pain

**Comment by vcsjones** [comment]
> Did this make it into 7?

It has not. Since this issue was originally filed, https://github.com/dotnet/runtime/pull/44853 changed the constructor to take a `DateTime` instead of a `long`. So now it really is just a matter of making the constructor public. 

@dotnet/area-system-componentmodel this seems like an easy enough one I can take care of if we want to put this through API review. Proposal at https://github.com/dotnet/runtime/issues/31204#issuecomment-543307307

**Comment by terrajobst** [comment]
* Currently people can't derive from this type (because there are no public constructors), we should seal it

```C#
namespace System.Timers;

public sealed class ElapsedEventArgs : EventArgs
{
    public ElapsedEventArgs(DateTime signalTime);
}
```

**Comment by TheMaximum** [comment]
I'd be interested to make this change. A quick look at the existing class shows there's already an internal constructor taking a DateTime argument (see below), wouldn't it be sufficient to change this to public (and seal the class)?

https://github.com/dotnet/runtime/blob/4d2ef11dff1d6426450916d18af49dbc05b29000/src/libraries/System.ComponentModel.TypeConverter/src/System/Timers/ElapsedEventArgs.cs#L6-L14

**Comment by vcsjones** [comment]
> wouldn't it be sufficient to change this to public (and seal the class)?

Yep. 

> Do we need to add any argument validation?

We discussed this further in the API review and we didn't think of any reasonable validations that should be applied as the input.
