### ISSUE TITLE
System.Diagnostics.PerformanceCounter leaks memory

### ISSUE THREAD

**Issue by FeodorFitsner** [dotnet/runtime#31232]
Our .NET Core app uses `System.Diagnostics.PerformanceCounter` class to poll Hyper-V VM's statistics.
The typical usage pattern is shown below. Counters are being polled in a loop every second until cancelled. The code is shown for 1 counter, but there are 10 counters polled in the same loop.

Everything was fine in .NET Core 2.2 until the app was migrated to 3.0 RTM and the code below started leaking "unmanaged" memory.
`<ServerGarbageCollection>false</ServerGarbageCollection>` is set during the publishing.

```csharp
private async Task PollPerformanceCounters(CancellationToken cancellationToken)
{
	var _workerName = "vm-1";
	PerformanceCounter nicBytesReceivedCounter = null;
	
	// here are 10 more counters like above
	// ...

	try
	{
		var nicCategoryName = "Hyper-V Virtual Network Adapter";
		var nicInstanceName = PerformanceCounterCategory.GetCategories()
			.Single(category => category.CategoryName == nicCategoryName)
			.GetInstanceNames().FirstOrDefault(i => i.StartsWith(_workerName));

		nicBytesReceivedCounter = new PerformanceCounter(nicCategoryName, "Bytes received/sec", nicInstanceName);

		while (!cancellationToken.IsCancellationRequested)
		{
			// query NIC performance counters
			var bytesReceivedSec = Convert.ToInt32(nicBytesReceivedCounter.NextValue());

			// Save counter in the database
			SaveMetadata();

			await Task.Delay(1000);
		}
	}
	finally
	{
		// dispose counters
		if (nicBytesReceivedCounter != null)
		{
			nicBytesReceivedCounter.Dispose();
		}
	}
}
```

Are we doing something wrong here (like wrong pattern or something is not called additionally to free resources) or there is a regression/bug in .NET 3.0?

**Comment by buyaa-n** [comment]
Hello @FeodorFitsner, is your issue solved by any chance? If not, would you mind leave a memory dump with some GFlags option set as mentioned in the VS developer community [issue ](https://developercommunity.visualstudio.com/content/problem/803951/systemdiagnosticsperformancecounter-leaks-memory.html)
