### ISSUE TITLE
Add alternative variant for get encoding by string name

### ISSUE THREAD

**Issue by rstm-sf** [dotnet/runtime#31244]
Hello!

Add alternative variant for get encoding by string name.

Since the `System.Text.Encoding.CodePages.dll` library is now part of the framework, I would like to see the method without additional code in the form `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)`

**Comment by GrabYourPitchforks** [comment]
Closing this because per @tarekgh's comment the scenario seems to work. There are good reasons for not wanting to include these features enabled by default across all .NET Core processes.

**Comment by rstm-sf** [comment]
> There are good reasons for not wanting to include these features enabled by default across all .NET Core processes.
@GrabYourPitchforks 

Optional to include. We can make an additional method that will call consecutively registered providers, and then either `CodePagesEncodingProvider` or `utf*` by order. 

We have two problems:
- How this method will look?
- What will be the first in order -  `CodePagesEncodingProvider` or  `utf*`?
I like to put  `utf*` first, but then you will need to change the source code a bit so that the exception is raised elsewhere. Now we have to write [in a way](https://github.com/CharsetDetector/UTF-unknown/blob/f1aa5fd2f05a728ee9f74010c00d04f74dec43e3/src/DetectionDetail.cs#L86) that doesn't look good
