### ISSUE TITLE
Timeout or Keep-Alive for open connection from HttpCompletionOption.ResponseHeadersRead ?

### ISSUE THREAD

**Issue by Bio2hazard** [dotnet/runtime#31259]
Hi,

we have noticed that some of the background workers on our services occasionally just stop. 

Investigating the issue, I found that a library we use is using ResponseHeadersRead and that the workers stop because the target machine disappeared without explicitly closing the socket.

Our workers have stopped working for many hours ( before we inevitably restart them ), so it does not seem like these open connections have any timeouts or keep-alives on them.

My questions are:

1) Is there any way we can set a application-wide timeout or keep-alive or even maximum read time for these open stream connections?

2) Is there any way to abort an on-going read? I have tried disposing of stream, but the other thread remains blocked trying to read from the socket.

3) Can you offer some guidance or best practices around the problem? Streams are very abstract, and if all your method receives is a Stream, it's next to impossible to know how to safely work with the given stream. Furthermore, none of the convenience methods seem to support cancellation tokens, and any synchronous reads appear doomed to begin with. 
    - `HttpContent.ReadAsStringAsync` ? No CTS Support => Application Deadlock Potential
    - `HttpContent.ReadAsByteArrayAsync` ? No CTS Support => Application Deadlock Potential
    - `HttpContent.ReadAsStreamAsync` > `StreamReader.ReadToEndAsync` ? No CTS Support => Application Deadlock Potential
    - `HttpContent.ReadAsStreamAsync` > `StreamReader.ReadLineAsync` ? No CTS Support => Application Deadlock Potential
    - `HttpContent.ReadAsStreamAsync` > Any synchronous call that reads from a stream => Application Deadlock Potential

It feels like the exact situation that `Stream.CanTimeout` , `Stream.ReadTimeout` and `Stream.WriteTimeout` was made for, but for some reason they are not supported either.

**Comment by karelz** [comment]
Triage:
* `HttpContent.ReadAsStringAsync` and `HttpContent.ReadAsByteArrayAsync` are addressed in PR #686 (in .NET 5).
* `StreamReader` overloads are tracked in #20824

Closing.
