### ISSUE TITLE
Equivalent of DefaultContractResolver in System.Text.Json

### ISSUE THREAD

**Issue by xsoheilalizadeh** [dotnet/runtime#31257]
I used to [`DefaultContractResolver`](https://www.newtonsoft.com/json/help/html/ContractResolver.htm) in Json.NET for ignoring empty collections and sometimes for changing json values. Currently I switched to System.Text.Json and haven't any idea about how to implement equivalent process in new JSON APIs. Also tried `JsonConverter` but it doesn't act as `DefaultContractResolver`. 

_Ignoring empty collections_

```c#
public class IgnoreEmptyCollectionsContract : DefaultContractResolver
{
    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        var property = base.CreateProperty(member, memberSerialization);

        if (property.PropertyType.GetInterface(nameof(ICollection)) != null)
        {
            property.ShouldSerialize = o =>
            {
                var value = o?.GetType().GetProperty(property.PropertyName)?.GetValue(o) as ICollection;

                if (value == null)
                {
                    return false;
                }
                
                return value.Count > 0;
            };
        }

        return property;
    }
}

```

**Comment by paymerich** [comment]
Any new traction/workarounds on this issue ?

**Comment by steveharter** [comment]
For 5.0 we are likely going to add a virtual property "HandleNullValue" (pending naming). Then you will be able to write a System.String converter, override that property and return true, and then implement Read\Write to treat nulls as empty strings.

**Comment by trinitrotoluene** [comment]
So you're essentially saying stj will not be supporting a way to ignore a value at runtime?

e.g. a `ShouldSerialize(T value)` method available to override in converters that does the equivalent to annotating the property with `[JsonIgnore]`.

An easy use-case to demonstrate this being necessary would be an `Option<T?>` implementation where you only want to serialize the inner value if the option has a value. Often there is a difference between an API explicitly returning `null` or omitting a field entirely, and this is something that can't currently be achieved with stj in its present form.

**Comment by techfan101** [comment]
I was honestly very excited to see a standardized version of JSON serialization option finally making its way into .NET.  Wrote a bunch of code, started testing, and then I came across this issue.

I MINIMALLY need an EASY option for preventing serialization of properties with the any of the following characteristics: null value, default value, empty string (zero length), and empty collection (zero count).

While more would be better, the above would cover the majority of code I've ever written.  Without this minimal support, this package is simply unusable.   I'm forced to return to using XML serialization or Newtonsoft's JSON.NET.

Why not support the "ShouldSerializeXXX" convention?  It is supported by pretty much every other serializer out there.

Is its absence simply to differentiate this product?  Or, are you concerned about performance issues?

If its the latter, perhaps provided a parameter/option to the serializer that selectively enables/disables "ShouldSerializeXXX" support?  I suggest this anyway to lessen the burden on developers refactoring pre-existing code (to use this package).

I'm really bummed out now :(  I was so happy to see this package.  Now, I need to eliminate dependencies on this package and revert to a different solution.

**Comment by rosieks** [comment]
I have different use case for ShouldSerialize (configured in `CreateProperty`). I use it to hide GDPR sensitive data depending on requestor permissions.

**Comment by andreykosteley** [comment]
Is there more information on this issue?
Perhaps there is a workaround in NET 5 RC1?

**Comment by KamranShahid** [comment]
I again needed similar thing for converting one implementation as mentioned in my stackoverflow post
https://stackoverflow.com/questions/64729381/defaultcontractresolver-equivalent-in-system-text-json

Basically trying equivalent of 
```
public class CustomDataContractResolver : DefaultContractResolver
    {
        public Dictionary<string, string> FieldNameChanges { get; set; }
        public List<FieldValueReplica> FieldValueReplica { get; set; }

        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var property = base.CreateProperty(member, memberSerialization);
            if (property.DeclaringType != typeof(logEvent)) return property;

            if (FieldNameChanges.Count > 0 && FieldNameChanges.TryGetValue(property.PropertyName, out var newValue))
                property.PropertyName = newValue;
            
            return property;
        }
   }
```

Any help in it?

**Comment by RicoSuter** [comment]
@KamranShahid same is done here: https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SystemTextJsonUtilities.cs#L45

But not sure whether this is a “sustainable” solution.

**Comment by KamranShahid** [comment]
> @KamranShahid same is done here: https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SystemTextJsonUtilities.cs#L45
> 
> But not sure whether this is a “sustainable” solution.

I am looking for solution within System.Text.Json. Not wanted to have NewtonSoft dependency anymore

**Comment by gokhanabatay** [comment]
Please support a way to handle NHibernate Proxy objects serialization:

```c#
 public class NHibernateContractResolver : CamelCasePropertyNamesContractResolver
    {
        protected override JsonContract CreateContract(Type objectType)
        {
            if (typeof(NHibernate.Proxy.INHibernateProxy).IsAssignableFrom(objectType))
            {
                return base.CreateContract(objectType.BaseType);
            }
            else
            {
                return base.CreateContract(objectType);
            }
        }
    }
```

**Comment by CuriouserThing** [comment]
> An easy use-case to demonstrate this being necessary would be an `Option<T?>` implementation where you only want to serialize the inner value if the option has a value. Often there is a difference between an API explicitly returning `null` or omitting a field entirely, and this is something that can't currently be achieved with stj in its present form.

As is, this use-case can lead to very many instances of a `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]` attribute when it's not feasible to set `DefaultIgnoreCondition`.

I appreciate that a `ShouldSerialize` API would unnecessarily duplicate the efforts of a full-fledged contract resolver (as @layomia [notes in #36275](https://github.com/dotnet/runtime/issues/36275#issuecomment-628948963)). Though I hope `ShouldSerialize` is considered as a fallback.

**Comment by steveharter** [comment]
Closing this; it is referenced by https://github.com/dotnet/runtime/issues/36785. Note two features (serialization order and OnSerialize callbacks) were added that will be able to unblock some "DefaultContractResolver" scenarios.

For 6.0, there was [prototyping ](https://github.com/steveharter/runtime/tree/ObjectExt) that exposed the object and property metadata with callbacks that allowed editing such as adding or modifying properties. However, since the prototyping was done later in the release, it would have received little feedback and usage information so the effort was closed and focus was switched to implement property ordering + OnSerialize callbacks.

**Comment by RicoSuter** [comment]
In order to implement correct schema definition generation, we probably need "prototyping" so that all metadata is available... do you have a link to the issue for this feature?
