### ISSUE TITLE
Error (sudden death) for System.Drawing.Image.FromStream in docker for almost empty images

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [dotnet/runtime#31276]
.Net Core version affected: 2.2

I can reproduce the problem in my development environment; please see the following repository to have a working example:

https://github.com/LeonSebastianCoimbra/ImageFromStreamError

The tools used are:

- Windows 10
- Docker Desktop CE (latest stable version: 2.1.0.4)
- Visual Studio 2019 preview (but the same thing happens also with VS2017)

For the details of the execution, please see the Dockerfile on the project; as summary, i can say that it is a Linux Alpine (latest official microsoft/dotnet2.2-aspnetcore-runtime from dockerhub) plus the latest available version of libgdiplus.

The problem arise when we try to open a particular image with System.Drawing.Image.FromStream: if the image is nearly empty (see the example posted) a native exception is executed and the program end abruptly, without even giving the chance to manage the error. The same image opened with System.Drawing.Image.FromFile works fine (except that it is locked by the GDI+ engine).

To reproduce the problem:
- download a copy or clone the project in the repository https://github.com/LeonSebastianCoimbra/ImageFromStreamError
- open the solution in Visual Studio 2019
- place some breakpoints at you will to follow step by step the flow of the program (it is all in the "Program.cs" file)
- execute (in debug) the docker-compose

You'll see that the fist two attempts to open the file with "FromFile" will work, while the last one will fails.

**Comment by safern** [comment]
@LeonSebastianCoimbra looking at this deeply, it definitely looks like a libgdiplus issue, so I will open the issue in https://github.com/mono/libgdiplus -- thanks for reporting the issue. Will close and transfer it to mono/libgdiplus.
