### ISSUE TITLE
Non-support of PrincipalPermissionAttribute

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/runtime#31279]
As best I can determine from my own test code (against 3.0.0) and as mentioned in dotnet/runtime#17693, PrincipalPermissionAttribute exists as a type but has no effect. MSDN also states "This attribute has no effect in .NET Core."

This seems dangerous, as a user porting existing code might expect that, if the attribute compiles, that it also functions. Since the purpose of this attribute is security, the consequences of a false assumption could be significant.

Is it a well-considered opinion that the attribute should exist yet be non-functional (not even a compiler warning...) or is this a decision warranting review?

**Comment by GrabYourPitchforks** [comment]
@jkotas This makes me think we should obsolete some types (like `PrincipalPermission`) as error. Since we don't support the CAS infrastructure in Core we should fail at compilation when these types are involved, as otherwise they'll incorrectly give the illusion that they work properly.

**Comment by GrabYourPitchforks** [comment]
Quite possibly all of the CAS-related attributes, now that I think more on it. If you manually new up a permission object and call `Demand` you'll get PNSE as expected. But since the runtime isn't looking at the attributes at all there's nobody to trigger the PNSE.

**Comment by jkotas** [comment]
I fully support marking all CAS-related APIs as obsolete, once we get the more fine grained controls for obsolete warnings in place.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/runtime/issues/1698#issuecomment-573956351, which ponders the consequences of a "fail open" policy where developers don't expect it.
