### ISSUE TITLE
System.IO.Packaging NuGet package lists System.IO.FileSystem.Primitives as a dependency, even for net472 where the later is part of the framework

### ISSUE THREAD

**Issue by robdalsanto** [dotnet/runtime#31298]
Our application makes use of the NuGet package ClosedXML. Through a chain of dependencies from there we get the System.IO.Packaging package. This package lists System.IO.FileSystem.Primitives as a dependency, even for net472, which finds the assembly in the "Reference Assemblies". This dependency should be fixed, at least for net472 and higher, though it might have some benefit to look at early .NET Framework versions for others.

Note that we are using packages.config still, rather than the Package References. Issue [30910](https://github.com/dotnet/corefx/issues/30910) looks similar/related.

**Comment by teo-tsirpanis** [comment]
The issue has been fixed since version 6.0.0 of the package. (https://www.nuget.org/packages/System.IO.Packaging/6.0.0#dependencies-body-tab)
