### ISSUE TITLE
Consider updating 'BenchmarksGame' benchmarks to use HWIntrinsics

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#31292]
The "BenchmarkGames" for C# have been updated to use .NET Core 3.0: https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharp.html

Given that .NET Core 3.0 now supports [Hardware Intrinsics](https://devblogs.microsoft.com/dotnet/hardware-intrinsics-in-net-core/), it may be beneficial to updates these benchmarks to use them and see how much faster we can be.

We track our implementations of these toy benchmarks in the dotnet/performance repo: https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/coreclr/BenchmarksGame and they would ideally also be contributed back to the Benchmark Games repo.

**Comment by danmosemsft** [comment]
@AnthonyLloyd i assume this is your submission them? Nice result!
https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/spectralnorm-csharpcore-5.html

@KoziLord any interest in taking a shot?

**Comment by KoziLord** [comment]
@danmosemsft I've tried a couple benchmarks in the past however I didn't get any improvements worth submitting. There's people more qualified to this than me, however if I do end up with something worthwhile I'll make sure to submit it.

**Comment by saucecontrol** [comment]
Looks like there are HWIntrinsics implementations for all applicable benchmarks now.  n-body was the last I remember being very slow, and it's now in line with other language/platform implementations.

**Comment by danmosemsft** [comment]
Thanks @saucecontrol . 

Looking at the [list](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharp.html) we are slower than Java only on reverse-complement. Could that use intrinsics?

https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/revcomp-csharpcore-6.html

**Comment by saucecontrol** [comment]
Oh yeah, looks like there's a [relatively new C++ version](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/revcomp-gpp-2.html) that uses a clever SIMD LUT implementation.  It's quite a bit faster than the others, despite being single-threaded.

**Comment by danmosemsft** [comment]
Any interest in trying it in C# ? 😉

**Comment by saucecontrol** [comment]
I can give it a look next time I have a free day, unless @john-h-k beats me to it ;)

Also of interest is that the 'official' hardware was fairly recently upgraded from the very old Intel Q6600 to a slightly newer Intel i5-3330, meaning SSE4.1 and AVX are now fair game (still no AVX2).  Could be an opportunity to improve on all the scores again.

**Comment by danmosemsft** [comment]
Oh - interesting, I did not know about the hardware upgrade. 

Perhaps [Spectral Norm](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/spectralnorm-csharpcore-5.html) could benefit from the upgrade to AVX?

"nbody" is [already using AVX](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-csharpcore-1.html) -- although there is a comment in there about random crashes. It was contributed by "Derek Ziemba" - not sure whether he has a Github ID.

Mandelbrot is using Vector<double>.

**Comment by AnthonyLloyd** [comment]
I'll take another look at these. I have a new thing CsCheck that will be useful and it makes a good demo.

**Comment by AndyAyersMS** [comment]
Would also be nice if we didn't have to delegate the heavy lifting to native libs (gmp, pcre) on some of those tests.

**Comment by AnthonyLloyd** [comment]
Spectral Norm doesn't seem to benefit from AVX at least on my laptop:
```
2.6%[-1..+0] slower, sigma=6.1 (19 vs 79)
```

**Comment by danmosemsft** [comment]
@AnthonyLloyd nice -- I"ll take it. Maybe we'll compare well with Java on all of them, after that goes in. Thank you!

**Comment by AnthonyLloyd** [comment]
And Go too I hope: https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/go-csharpcore.html

**Comment by tannergooding** [comment]
We and the community have already updated many of the benchmarks to use HWIntrinsics or other vectorization where feasible.

Users should feel free to continue optimizing as appropriate.
