### ISSUE TITLE
Add API to get bit length of BigInteger

### ISSUE THREAD

**Issue by andrew-boyarshin** [dotnet/runtime#31308]
Gets the number of bits required for shortest two's complement representation of a `BigInteger` instance without the sign bit.

The method returns the minimum non-negative number of bits in two's complement notation without the sign bit.

This method returns `0` _iff_ value of the `BigInteger` instance is equal to `0` or `-1`. For positive integers the return value is equal to the ordinary binary representation string length.

[Java docs for equivalent method](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/math/BigInteger.html#bitLength())

Implementation implies zero impact on existing code, maintenance cost is expected to be low.

# Current story
```cs
private static long SlowBitLength(BigInteger integer)
{
    return (long)Math.Ceiling(BigInteger.Log(integer.Sign < 0 ? -integer : integer + 1, 2.0));
}
```

* Slower
* Imprecise for huge (`2^(32*int.MaxValue)`) values (`correct ± 1`)

# Proposed API
```cs
public struct BigInteger : <...>
{
	<...>
    public long GetBitLength();
	<...>
}
```

# Sample results
![samples](https://user-images.githubusercontent.com/3063662/84646107-c6ae7d00-af2b-11ea-85d5-d3ba98c5b1e0.png)

# Open Questions
* Should it be property, or method? It implies some computation, so it's cheap, not free. `IsPowerOfTwo` is a property and has approximately the same complexity. — **Chosen method approach.**

# References
dotnet/runtime#29193 contains a similar method as one of the points, however this method is different.

# Changelog
* [2019-11-02] Rewritten as method (was property initially).
* [2020-06-15] Fixed description to take two's complement representation as the basis.

**Comment by andrew-boyarshin** [comment]
@tannergooding it might be a great time to mark this as `api-ready-for-review`, otherwise it'll never be looked at.

**Comment by terrajobst** [comment]
* Makes sense as proposed
* We considered `GetBitCount()` to be consistent with `GetByteLength()` but it seems confusing because it sounds like `GetPopCount()`.

```C#
namespace System.Numerics
{
    public struct BigInteger
    {
        public int GetBitLength();
    }
}
```

**Comment by andrew-boyarshin** [comment]
Turns out `BigInteger` is inconsistent with bit length being `int` or `long`. Correct return type is `long` (see #15925, yeah, it really can overflow!). @tannergooding @terrajobst  does this change require additional API review?

**Comment by tannergooding** [comment]
It will need to get sign-off at a minimum. Given that we currently use `int` as the backing type, you only need an array that is 67 million elements before `BitLength` risks overflowing, so using `long` makes sense to me.

I'd suggest prepping the PR assuming that `long` is fine and I'll get sign-off either offline or in Tuesday's API review. CC @dotnet/fxdc

**Comment by stephentoub** [comment]
long makes sense

**Comment by andrew-boyarshin** [comment]
For API re-review:
1. `long` instead of `int` as the return type
2. Bit length is that of the two's-complement representation. This detail was discovered when testing against Java's `BigInteger` and thanks to @KalleOlaviNiemitalo. The only difference is for negative power-of-2 numbers.

**Comment by tannergooding** [comment]
Brought this up first thing this morning and it was approved. I've unblocked the associated PR.
