### ISSUE TITLE
Streaming HttpContent and ReadAsStreamAsync

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#31316]
The default implementation of `HttpContent.ReadAsStreamAsync` copies content into a buffer stream and doesn't return until `HttpContent.SerializeToStreamAsync` is complete. This becomes a problem with duplex streaming implementations, as someone could called `ReadAsStreamAsync` expecting to get content as it is written rather than waiting until the stream is complete.

Related issue in how ASP.NET Core's TestServer using HttpContent: https://github.com/aspnet/AspNetCore/pull/15591

I'm searching for guidance and discussion here about this situation. Which of these are right?
1. Is the current default buffer behavior correct? - https://github.com/dotnet/corefx/blob/26d7b6626ab0385a1158e674855f81ab73f628e0/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L453-L459
Maybe it should do something different when AllowDuplex is set to true - https://github.com/dotnet/corefx/blob/26d7b6626ab0385a1158e674855f81ab73f628e0/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L320-L326
Or perhaps there should be a new abstract HttpContent type to inherit from that is designed for duplex scenarios.
2. Or should we rely on all [custom streaming implementations](https://github.com/grpc/grpc-dotnet/blob/9e39edb0a3fc7a625085490bf64c2794870a519e/src/Grpc.Net.Client/Internal/PushStreamContent.cs) overriding `HttpContent.CreateContentReadStreamAsync`? It's relatively simple to do using a `Pipe` and Stream adapters with the reader and writer (see linked PR in ASP.NET Core), but it forces the implementation to take a dependency on all of Pipes just in case someone calls `ReadAsStreamAsync` in a delegating handler.
3. Or `ReadAsStreamAsync` is not designed for this scenario. Tell anyone who is using `ReadAsStreamAsync` like this to stop.

**Comment by karelz** [comment]
Triage: We believe this should be best covered by documentation as this is fairly rare scenario. Adding a sample + conceptual doc on how to make custom `HttpContent`.
Breaking the behavior with the exception is not desirable per our discussion.

**Comment by msschl** [comment]
> I would be interested in a `ReadAsStreamAsync` that explicitly doesn't buffer.
I would be interested in this as well. Or, is there an API for getting the `HttpContent` as a `Pipe`?

My scenario is this:
We have an Elasticsearch cluster with an [Pelias](https://github.com/pelias/pelias) backend deployed. [Pelias](https://github.com/pelias/pelias) is a modular, open-source search engine for our world. In front of this we have our own geocoding backend were we do some more stuff. In case of auto-completion, which is the most performance critical task, the flow is as following:
The client makes a grpc request to our geocoding backend -> our geocoding backend makes a request to -> the pelias autocomplete endpoint which returns geojson -> our backend parses this geojson and strips quite a few stuff away as we essentially only need the position (latlng) and the label to display.

- We started by using the `System.Text.Json.JsonSerializer` and deserialize into a model which has only those properties set, which we need for our scenario. This model was iterated and transformed into the grpc response model.
- We than created our own low level parser using `System.Text.Json.Utf8JsonReader` to directly parse the JSON `Stream` into the grpc response c# model.

```c#
var response = await this.client.GetAsync("v1/autocomplete?boundary.country=DE&text=" + HttpUtility.UrlEncode(query),
    HttpCompletionOption.ResponseHeadersRead, cancellationToken);

try
{
    response.EnsureSuccessStatusCode();

    if (response.Content is not object)
        throw new HttpRequestException();

    var stream = await response.Content.ReadAsStreamAsync();
    // NOTE(msschl): Uses a `PipeReader` and a `Utf8JsonReader` to parse the json to the grpc autocomplete response
    // This is actually about 18%ish faster and uses about 55%ish less memory
    return await PeliasAutocompleteParser.ParseAsync(stream, cancellationToken);
}
finally
{
    response.Dispose();
}
```

Therefore, I really liked getting a pipe to read from as data flows in from the network or have the stream not be buffered.

**Comment by stephentoub** [comment]
> or have the stream not be buffered.

The stream returned from ReadAsStreamAsync doesn't buffer the full response here.  What is the concern?

**Comment by msschl** [comment]
Well the docs state the task completes after all of the stream that represents content has been read.

> This operation will not block. The returned Task<TResult> object will complete after all of the stream that represents content has been read.

Also looking in the [`HttpContent`](https://github.com/dotnet/runtime/blob/837785f9ca4abbc3cffa77af1b94623121567b70/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L287) class it looks like it's read into a `MemoryStream` first. Not sure, though.

Or did I understand that incorrectly?

**Comment by stephentoub** [comment]
That's what the base stream does.  But the method is virtual, with the intent that any self-respecting implementation overrides it to do something better... which all the HttpContents produced by SocketsHttpHandler / HttpClient do.

**Comment by msschl** [comment]
Thanks @stephentoub, that's good to know.
It was a concern that I had after reading the documentation and reading this issue.
