### ISSUE TITLE
TimeZoneInfoTests.ConvertTimeFromToUtc_UnixOnly broken by daylight savings

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#31314]
```
System.Tests.TimeZoneInfoTests.ConvertTimeFromToUtc_UnixOnly }
Error message
Assert.Equal() Failure\nExpected: 2019-10-27T01:04:19.5612844Z\nActual: 2019-10-27T00:04:19.5612844Z

Stack trace
   at System.Tests.TimeZoneInfoTests.ConvertTimeFromToUtc_UnixOnly() in /_/src/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 2052
```
Also failed this time 3 years ago..
https://github.com/dotnet/corefx/issues/13156

**Comment by joperezr** [comment]
@danmosemsft did this ever got fixed? I don't see the test disabled and it doesn't seem to be failing so I'm inclined to close this unless we expect it to fail again with next DST

**Comment by danmosemsft** [comment]
Probably not. I don't mind closing since it is so low priority.
