### ISSUE TITLE
System.Net.Quic initial API review

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#31337]
This is the first cut at APIs for using the QUIC protocol.

A brief overview of QUIC is available here: https://blog.cloudflare.com/the-road-to-quic/

```csharp
namespace System.Net.Quic.Experimental
{
    public sealed class QuicConnection : IDisposable
    {
        public QuicConnection(IPEndPoint remoteEndPoint, System.Net.Security.SslClientAuthenticationOptions sslClientAuthenticationOptions, IPEndPoint localEndPoint = null, bool mock = false);
        public System.Threading.Tasks.ValueTask ConnectAsync(System.Threading.CancellationToken cancellationToken = default);
        public bool Connected { get; }
        public IPEndPoint LocalEndPoint { get; }
        public IPEndPoint RemoteEndPoint { get; }
        public SslApplicationProtocol NegotiatedApplicationProtocol [ get; }
        public QuicStream CreateUnidirectionalStream();
        public QuicStream CreateBidirectionalStream();
        public System.Threading.Tasks.ValueTask<QuicStream> AcceptStreamAsync(System.Threading.CancellationToken cancellationToken = default);
        public void Close();
    }
    public sealed class QuicListener : IDisposable
    {
        public QuicListener(IPEndPoint listenEndPoint, System.Net.Security.SslServerAuthenticationOptions sslServerAuthenticationOptions, bool mock = false);
        public IPEndPoint ListenEndPoint { get; }
        public System.Threading.Tasks.ValueTask<QuicConnection> AcceptConnectionAsync(System.Threading.CancellationToken cancellationToken = default);
        public void Close();
    }
    public sealed class QuicStream : System.IO.Stream
    {
        internal QuicStream() { }
        public long StreamId { get; }
        public void ShutdownRead();
        public void ShutdownWrite();
    }
}
```

Notes:

Generally, this object model is inspired by the existing System.Net.Sockets API -- Connect, Accept, LocalEndPoint, RemoteEndPoint, etc. Some differences worth noting:

(1) QuicListener and QuicConnection take SSL options classes, since QUIC always uses TLS
(2) These classes use IPEndPoint, since they are IP-specific (vs Socket which uses EndPoint and AddressFamily etc)
(3) Since QUIC supports multiplexing, there is a distinction here between QuicConnection and QuicStream that doesn't exist in Sockets

The "mock" arguments to the QuicListener and QuicConnection constructors cause the "mock QUIC" implementation to be used. This is meant as a temporary measure while real QUIC protocol support is implemented and matures. This allows us to make progress on HTTP3 in parallel. These arguments will be removed before shipping.

There are currently no synchronous equivalents defined for async APIs like ConnectAsync. This matches HttpClient API definition.

I've added "Experimental" to the namespace here to position this work as experimental and not yet committed.

**Comment by karelz** [comment]
The initial API was checked in. We will do full API later when QUIC is mature and finalized (post 5.0).
