### ISSUE TITLE
XML documentation for some methods in System.Runtime.Intrinsics is inconsistent

### ISSUE THREAD

**Issue by MichalBrylka** [dotnet/runtime#31338]
Hi,

I've created a Roslyn based scanner that goes through System.Runtime.Intrinsics codebase and tries to rewrite intrinsics methods so that they have names equal to related CPU instructions (this might be useful for porting C++ code and fast prototyping):
https://github.com/nemesissoft/IntrinsicsGenerator/tree/master/IntrinsicsGenerator

in which a simple regex scans XML docs to look for instruction names. Most methods are documented but these are not:
https://github.com/nemesissoft/IntrinsicsGenerator/blob/master/IntrinsicsGenerator/StillNotHandled.txt

I reckon this has to be the case for some methods marked with _"The native signature does not exist. We provide this additional overload for completeness."_ but it would be good if other methods would be consistently documented.  
@tannergooding mentioned on twitter that this can be treated as issue

**Comment by danmosemsft** [comment]
@MichalBrylka are you still planning to contribute? Checking you are not waiting on more info?

**Comment by MichalBrylka** [comment]
@danmosemsft 
I opened this issue on corefx repo. I reckoned that project was abandoned. My changes are already merged: https://github.com/dotnet/runtime/pull/382

I'm closing this then

**Comment by danmosemsft** [comment]
Oh good thank you @MichalBrylka
