### ISSUE TITLE
API proposal: SequenceReader.TryReadTo(out ReadOnlySpan<T> sequence, ReadOnlySpan<T> delimiter)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#31355]
Today there's no overload of TryReadTo that returns (via out parameter) a `ReadOnlySpan<T>` and allows passing a `ReadOnlySpan<T>` delimeter.

```C#
public partial ref struct SequenceReader
{
    public bool TryReadTo(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true);
}
```

@JeremyKuhne do you recall why we left this out?

**Comment by terrajobst** [comment]
* We have an existing API that returns the sequence.
* We don't want to offer an API that implicitly allocates.

```C#
namespace System.Buffers
{
    public ref struct SequenceReader<T>
    {
        // Existing API
        // public bool TryReadTo(out ReadOnlySequence<T> sequence, T delimiter, bool advancePastDelimiter = true);

        public bool TryReadTo(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true);
    }
}
```

**Comment by davidfowl** [comment]
Uhhhhh yes we do.

**Comment by terrajobst** [comment]
> Uhhhhh yes we do.

Watch the video, I kind of predicted you'd say that :-)

**Comment by benaadams** [comment]
You are looking at the wrong existing api. The existing apis are: 
```csharp
namespace System.Buffers
{
    public ref struct SequenceReader<T>
    {
        public bool TryReadTo (out ReadOnlySpan<T> span, T delimiter, bool advancePastDelimiter = true);
        public bool TryReadTo (out ReadOnlySpan<T> span, T delimiter, T delimiterEscape, bool advancePastDelimiter = true);
    }
}
```
However there isn't one that takes multiple delimiters (e.g. `,`, `\n` or `\r`)

**Comment by benaadams** [comment]
Hm, maybe I got it wrong as there is already an existing api for multiple delimiters
```csharp
namespace System.Buffers
{
    public ref struct SequenceReader<T>
    {
        public bool TryReadToAny(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true)
    }
}
```
So its this for a multi T delimiter? (e.g. `\r\n`)

**Comment by benaadams** [comment]
Ah is definitely for using a multielement delimiter `\r\n`

Every other `TryRead` api has an `(out ReadOnlySpan<T> span, ` except multielement delimiter which only has a `(out ReadOnlySequence<T> sequence, ` variant
```csharp
/// <summary>
/// Try to read data until the entire given <paramref name="delimiter"/> matches.
/// </summary>
/// <param name="sequence">The read data, if any.</param>
/// <param name="delimiter">The multi (T) delimiter.</param>
/// <param name="advancePastDelimiter">True to move past the <paramref name="delimiter"/> if found.</param>
/// <returns>True if the <paramref name="delimiter"/> was found.</returns>
public bool TryReadTo(out ReadOnlySequence<T> sequence, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true)
```

QED it is a missing api

**Comment by benaadams** [comment]
Every other `TryRead` api has an `(out ReadOnlySpan<T> span, ` except multielement delimiter e.g.  `\r\n` which only has a `(out ReadOnlySequence<T> sequence, ` variant

```csharp
namespace System.Buffers
{
    public ref struct SequenceReader<T>
    {
        // Existing api pairs: out ReadOnlySequence
        public bool TryReadTo(out ReadOnlySequence<T> sequence, T delimiter, bool advancePastDelimiter = true);
        public bool TryReadTo(out ReadOnlySequence<T> sequence, T delimiter, T delimiterEscape, bool advancePastDelimiter = true);
        public bool TryReadToAny(out ReadOnlySequence<T> sequence, ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);

        // Existing api pairs: out ReadOnlySpan
        public bool TryReadTo(out ReadOnlySpan<T> span, T delimiter, bool advancePastDelimiter = true);
        public bool TryReadTo(out ReadOnlySpan<T> span, T delimiter, T delimiterEscape, bool advancePastDelimiter = true);
        public bool TryReadToAny(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiters, bool advancePastDelimiter = true);

        // Missing pair: out ReadOnlySpan
        public bool TryReadTo(out ReadOnlySequence<T> sequence, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true)
    }
}
```

QED it is a missing api

**Comment by davidfowl** [comment]
I'm going to re-open this so we can re-discuss it 😄

**Comment by reflectronic** [comment]
I brought up how we rejected the ReadOnlySpan version of https://github.com/dotnet/runtime/issues/30778 for this same reason reason in the chat during API review. If we go through with this API, we should look at that API again as well. I talked about my opinions on the Span returning APIs in that issue https://github.com/dotnet/runtime/issues/30778#issuecomment-589432873

**Comment by bartonjs** [comment]
After much debate, approved as proposed:

```C#
public partial ref struct SequenceReader
{
    public bool TryReadTo(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true);
}
```

**Comment by benaadams** [comment]
@bartonjs to follow up on api review, you can't mimic the behaviour with an extension method and the `ReadOnlySequence<T>` overload; because the `SequenceReader` has a `ReadOnlySpan<T>` internally so it has a much faster path when its contained in the current page as it already has the span and doesn't need to access the sequence; whereas an extension would always be starting on a slow path
