### ISSUE TITLE
Socket errors in a reverse proxy

### ISSUE THREAD

**Issue by Pilchie** [dotnet/runtime#31360]
_From @colutti on Tuesday, October 29, 2019 4:36:24 PM_

We have developed a reverse proxy to send requests to different endpoints. It has been working so far, but we see a lot of socket errors with timeout exceptions. We are using a singleton instance of httpclient but the issue still happens. 

The code with the repro steps can be found here:

https://github.com/colutti/tr-reverse-proxy

_Copied from original issue: aspnet/Extensions#2573_

**Comment by karelz** [comment]
No response for 4 months, closing.
If there is more details, feel free to reopen and we can take a look.
