### ISSUE TITLE
API proposal: Add new ConfigureAwait methods with additional TimeSpan as timeout or CancellationToken parameter. 

### ISSUE THREAD

**Issue by zlatanov** [dotnet/runtime#31365]
Consider introducing new awaitables (for both Tasks and ValueTasks) that can time out (throw OperationCanceledException) when awaited:

Proposed API
---
``` csharp
public class Task
{
    public TimeoutConfiguredAwaitable ConfigureAwait( 
        bool continueOnCapturedContext, TimeSpan timeout);

    public TimeoutConfiguredAwaitable ConfigureAwait( 
        bool continueOnCapturedContext, CancellationToken cancellationToken);
}

public class Task<TResult>
{
    public new TimeoutConfiguredAwaitable<TResult> ConfigureAwait<TResult>( 
        bool continueOnCapturedContext, TimeSpan timeout);

    public new TimeoutConfiguredAwaitable<TResult> ConfigureAwait<TResult>( 
        bool continueOnCapturedContext, CancellationToken cancellationToken);
}

public readonly struct ValueTask
{
    public TimeoutConfiguredValueTaskAwaitable ConfigureAwait( 
        bool continueOnCapturedContext, TimeSpan timeout);

    public TimeoutConfiguredValueTaskAwaitable ConfigureAwait( 
        bool continueOnCapturedContext, CancellationToken cancellationToken);
}

public readonly struct ValueTask<TResult>
{
    public new TimeoutConfiguredValueTaskAwaitable<TResult> ConfigureAwait<TResult>( 
        bool continueOnCapturedContext, TimeSpan timeout);

    public new TimeoutConfiguredValueTaskAwaitable<TResult> ConfigureAwait<TResult>( 
        bool continueOnCapturedContext, CancellationToken cancellationToken);
}
```

Rationale and Usage
---
Consider the following situations:

We have an expensive task that should be executed only once, but can be observed by many. We can use TaskCompletionSource<T> for this. However there is no built in mechanism for consumers to await the result for a given amount of time or some other condition (which can be linked easily to CancellationToken).

Another example is a singleton implementation where an application needs to have only one instance of a given type at any one time. The factory for this instance is asynchronous (for example establishing I/O connection). Consumers of this can await the factory to establish the connection (which may take longer than anticipated or even be impossible at the moment), but they need to be able to specify how much time they are willing to do that. Real world example in Azure AMQP library: https://github.com/Azure/azure-amqp/blob/c161ce1c5abd182a4751295f0bc2757481404c8a/src/Fx/Singleton.cs#L113. Here the implementation is incorrect and is not honoring the timeout passed in when awaiting the factory task.

Here is an old popular question from stackoverflow: https://stackoverflow.com/questions/4238345/asynchronously-wait-for-taskt-to-complete-with-timeout.

Example of how the usage of this would look like:
``` csharp
await _tcs.Task.ConfigureAwait(timeout: TimeSpan.FromSeconds(5));

// Or another example if I'm using it inside ASP.NET Core Request
await _tcs.Task.ConfigureAwait(cancellationToken: HttpContext.RequestAborted);
```

Here is an example of how this can be implemented without having access to the internals of the Tasks - https://gist.github.com/zlatanov/8ed79f1897e5b737307532b10062ec39. I am hoping that there might be a better implementation and support if done here internally.

**Comment by stephentoub** [comment]
This was opened first, but consolidating with https://github.com/dotnet/runtime/issues/47525.
cc: @eiriktsarpalis
