### ISSUE TITLE
NegoState creates an ObjectDisposedException during Close() that might never be thrown?

### ISSUE THREAD

**Issue by TimLovellSmith** [dotnet/runtime#31364]
Noticed this because i found a small source of lock contention in .net Framework is that SslStream.Dispose() does this upfront exception construction during .net Framework's _SslState.Close() - and then tracked down that NegoState seems to be the equivalent in corefx, and AFAiCS follows the same pattern, though the exception might not actually ever get raised. [The contention actually seems to be due to localization of the exception message being done in ctor.]

**Comment by scalablecory** [comment]
Triage: looks like perf; leaving for future. If you'd like to take a look and see if PR is doable, please do.

**Comment by davidsh** [comment]
PR #36583 refactored the NegotiateStream class and removed the separate NegoState class. So, this issue appears moot now.

**Comment by stephentoub** [comment]
It's still there, just now in NegotiateStream:
https://github.com/dotnet/runtime/blob/49f40c34e4e18a4b80c7aa5d11104c9624a2667e/src/libraries/System.Net.Security/src/System/Net/Security/NegotiateStream.cs#L73
