### ISSUE TITLE
Proposal: CancellationToken with Timeout

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/runtime#31370]
When using time based cancellations, there are a few potential problems.

* Setting a timeout on a `CancellationTokenSource` requires starting a timer.
* If the `CancellationTokenSource` is disposed, the timeout will never fire and the ``CancellationToken` will not be cancelled. This isn't clear in the documentation. 
* The `CancellationTokenSource` must be tracked in some way so it can be properly disposed. Otherwise a memory leak can occur. 

For one-offs this is not a big deal. But as we increasingly use `CancellationToken`, it can become an significant expense in terms of memory and system resources.

An alternative would be to allow the `CancellationToken` itself to have an optional DateTime field that can be checked. While it would make the `CancellationToken` slightly more expensive in terms of memory, it would eliminate the need for an expensive timer. 

> What I think would make more sense would be to make CancellationToken struct itself smarter about timeouts. When you create a CancellationTokenSource with a timeout, it should calculate the timestamp of the expiration, and bake that into the token. Then various properties on the CancellationToken, such as IsCancellationRequested, would check the current time against that timestamp and return appropriately if that timestamp is in the past.

https://www.reddit.com/r/programming/comments/dqbnz3/the_autocancelling_cancellationtoken_that_doesnt/f61xwdn/

**Comment by stephentoub** [comment]
Thank you for the suggestion.  Given the conversation, I'm going to close this as not being actionable.  As noted, if you see opportunities in the implementation to make it more efficient, we'd welcome a PR, but we don't need an issue tracking that possibility.
