### ISSUE TITLE
Microsoft.Data.SqlClient is not compatible with AssemblyLoadContext unloading

### ISSUE THREAD

**Issue by AlbertoCe** [dotnet/runtime#31377]
Hello,

when I load a plugin that uses EntityFrameworkCore (using a custom collectible AssemblyLoadContext) and try to unload it, it does not get unloaded: the IsActive property of the context's weakreference remain true even after multiple GC.Collect() and GC.WaitForPendingFinalizers().

It works well if I comment out all the EntityFrameworkCore related code from the plugin.

**Comment by joperezr** [comment]
@janvorli Is there anything we want to fix around this for 5.0 or is it ok to move to future?

**Comment by danmosemsft** [comment]
Leaving in 5.0 so loader folks can triage

**Comment by agocke** [comment]
Sounds like this is an issue with Microsoft.Data.SqlClient. Created an issue at https://github.com/dotnet/SqlClient/issues/1687. Closing this one.
