### ISSUE TITLE
Some networking tests failing in Outerloop on Windows 7

### ISSUE THREAD

**Issue by davidsh** [dotnet/runtime#31382]
A few SslStream and WebSocket tests are always failing on Windows 7 with the same SocketException due to a likely RST being sent/received with the remote server.

>System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok [FAIL]
      System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
      ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1111,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
        /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1077,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)

>System.Net.WebSockets.Tests.WebSocketTests.WebSocketProtocol_CreateFromConnectedStream_CloseAsyncClosesStream(echoUri: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx, explicitCloseAsync: False) [FAIL]
      System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
      ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)

>System.Net.WebSockets.Tests.WebSocketProtocolCreateTests.WebSocketProtocol_CreateFromConnectedStream_CloseAsyncClosesStream(echoUri: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx, explicitCloseAsync: False) [FAIL]
      System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
      ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/System.Net.Security/src/System/Net/FixedSizeReader.cs(57,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
        /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs(843,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)

**Comment by rzikm** [comment]
Windows 7 test runs have been disabled some time ago
