### ISSUE TITLE
[Uri] Uri.EscapeUriString should be deprecated

### ISSUE THREAD

**Issue by lostmsu** [dotnet/runtime#31387]
Please, see the relevant [StackOveflow thread](https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring/34189188#34189188).

From my understanding of the issue, there is no valid and/or safe use case for `EscapeUriString`. Either one wants to escape a URI component, in which case they should call `EscapeDataString`, or they construct URI incorrectly in the first place.

**Comment by karelz** [comment]
Triage: We should likely make it part of Roslyn Analyzers. @MihaZupan can you please summarize our approach and recommendation.
Overall we don't believe most people are using it correctly.

**Comment by lostmsu** [comment]
@karelz I think Roslyn Analyzers is insufficient, as they are rarely used. It should at very least be marked with `[Obsolete]`.

Here's another link, that might convince you: https://github.com/search?q=org%3Amicrosoft+EscapeUriString&type=Code

**Comment by karelz** [comment]
@lostmsu we have plans to add default Roslyn Analyzers. The rule would be default if 99% cases are incorrectly used. If it is more than that, we may have to make the rule off by default.
Bringing false positives to devs is troublesome -- no matter if it is Obsolete or Analyzer. Analyzers have the nice property of ability to be updated and fine-tuned if necessary.

**Comment by karelz** [comment]
@aik-jahoda please add the Obsolete attribute, @MihaZupan will help with writing the right docs later.

**Comment by aik-jahoda** [comment]
### Obsoletion status
tracking comment to see status of all necessary steps

- [ ] #41501 - Runtime obsoletion
- [ ] dotnet/dotnet-api-docs#???
- [ ] dotnet/docs#???
- [ ] Redirect https://aka.ms/dotnet-warnings/SYSLIB0013 link to: ???

**Comment by karelz** [comment]
Moving to 6.0 -- we won't backport it to 5.0 this late in the game.

**Comment by karelz** [comment]
> @MihaZupan That said, I am having trouble finding a uri example where using `EscapeUriString` is necesarry before passing the string to the ctor.

Just found a corner case where it differs:
```c#
Console.WriteLine(new Uri("http://my/%20").AbsoluteUri);                      // Output: http://my/%20
Console.WriteLine(new Uri(Uri.EscapeUriString("http://my/%20")).AbsoluteUri); // Output: http://my/%2520
```

**Comment by jeffhandley** [comment]
@karelz I'm moving this to 7.0 (along with some other obsoletions). Feel free to pull this back into 6.0 if you were still planning to do this for RC1.

**Comment by karelz** [comment]
@jeffhandley given that this is missing just docs, I think it makes sense to have it in 6.0. I expect that docs will happen post RC1 fork ...

**Comment by jeffhandley** [comment]
Ah; cool. I overlooked that aspect. Thanks.

**Comment by MihaZupan** [comment]
The documentation effort seems to be complete here, I linked the relevant PRs where changes happened. Closing.

>> @MihaZupan That said, I am having trouble finding a uri example where using EscapeUriString is necesarry before passing the string to the ctor.

> Just found a corner case where it differs:
> `"http://my/%20"` vs `EscapeUriString("http://my/%20")`

The output may differ, but the `Uri` ctor will accept the value regardless. Escaping the `%` to `%25` is most likely an unintended consequence of using `EscapeUriString` for the user.
