### ISSUE TITLE
Http tests hanging: ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed

### ISSUE THREAD

**Issue by davidsh** [dotnet/runtime#31380]
Both HttpClient and HttpWebRequest tests are hanging with similar patterns:

https://helix.dot.net/api/2019-06-17/jobs/d5c29930-eea7-42ae-89a1-259a59bb94fc/workitems/System.Net.Http.Functional.Tests/files/console.48c41834.log

>System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DefaultProxyCredentials_Test.ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed

https://helix.dot.net/api/2019-06-17/jobs/d5c29930-eea7-42ae-89a1-259a59bb94fc/workitems/System.Net.Requests.Tests/files/console.3091abbb.log

>System.Net.Tests.HttpWebRequestTest.ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed

Sometimes the test generates an error:

https://helix.dot.net/api/2019-06-17/jobs/ad5f6171-9e64-4f2e-bb62-ea3fc716a3d2/workitems/System.Net.Http.Functional.Tests/files/console.2e2c133e.log

>    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_DefaultProxyCredentials_Test.ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(useProxy: True) [FAIL]
      System.IO.IOException : Unexpected EOF trying to read request header
      Stack Trace:
        /_/src/Common/tests/System/Net/Http/LoopbackServer.cs(597,0): at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync()
        /_/src/Common/tests/System/Net/Http/LoopbackServer.AuthenticationHelpers.cs(28,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass33_0.<<AcceptConnectionPerformAuthenticationAndCloseAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/Common/tests/System/Net/Http/LoopbackServer.cs(127,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
        /_/src/Common/tests/System/Net/Http/LoopbackServer.AuthenticationHelpers.cs(89,0): at

**Comment by MihaZupan** [comment]
The test is still disabled against this issue
https://github.com/dotnet/runtime/blob/8303e25d3e53abe23d4188b1d9af6098c187b3b9/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs#L1571
