### ISSUE TITLE
HttpConnection.EnsureReadAheadAndPollRead assumes that NetworkStream.ReadAsync(0) returns synchronously

### ISSUE THREAD

**Issue by dmitryvk** [dotnet/runtime#31399]
(this a cross-post from https://github.com/mono/mono/issues/17710 because HttpClient code is in corefx repo)

HttpConnection.EnsureReadAheadAndPollRead method (https://github.com/dotnet/corefx/blob/97d9fb9d6c7e1d50f527e290ef8e18767dbc6bbf/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L170) assumes that NetworkStream.ReadAsync will return synchronously completed task if there is already data to be received (or is socket is shut down).

But this is not guaranteed (since Streams are not specified to return synchronously completed tasks) and such assumptions lead to reuse of already closed sockets (which manifests as HttpRequestException from HttpClient.PostAsync due to TCP RST when trying to write into closed TCP connection).

**Comment by karelz** [comment]
Triage: We believe this is problem in Mono Desktop (not .NET 5, but mono/mono repo) -- it should be fixed there as suggested above in https://github.com/dotnet/runtime/issues/31399#issuecomment-565200477
