### ISSUE TITLE
Introduce Distributed Context API (distributed http context)

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#31393]
This issue tracking the work as the part of the issue dotnet/runtime#31372

Distributed context should support 
- string/string (key-value pairs)
- Support scoping 
- Not attached to Activity

**Comment by danmosemsft** [comment]
@tarekgh I found this one in https://themesof.net/?q=is:open%20kinds:teui as it was under a (closed) Epic. Do you believe it is properly part of the .NET 6 wave? I added it to the Cloud Native Epic instead so it is a sibling of your Metrics story, but I am not sure whether it is really part of .NET 6. If so we should remove its parenting or possibly close it.

**Comment by tarekgh** [comment]
@danmosemsft No this issue is not part of 6.0 planning and I am not aware of anyone need it urgently. I'll close it.

**Comment by danmosemsft** [comment]
thanks!
