### ISSUE TITLE
Api Proposal: Stats/Callback when PipeWriter threshold is reached

### ISSUE THREAD

**Issue by rohits79** [dotnet/runtime#31407]
For slow consumers, it would be good to detect that is potential back pressure building up i.e. pipe reader is not advancing fast enough. Would be good see some statistics, or callback so we could debug and analyze if so.

**Comment by BrennanConroy** [comment]
Triage: We think we'll close this after we have some discussion

**Comment by BrennanConroy** [comment]
Using https://github.com/dotnet/runtime/issues/48913 for tracking adding "stats". We can start with unflushed bytes and add more later if there is need.
