### ISSUE TITLE
Error in validation for BitVector32

### ISSUE THREAD

**Issue by oznetmaster** [dotnet/runtime#31410]
It appears that there is an error in the code for the validation of a new Section in BitVector32.

The code:
```
        private static Section CreateSectionHelper(short maxValue, short priorMask, short priorOffset)
        {
            if (maxValue < 1)
            {
                throw new ArgumentException(SR.Format(SR.Argument_InvalidValue_TooSmall, nameof(maxValue), 1), nameof(maxValue));
            }

            short offset = (short)(priorOffset + CountBitsSet(priorMask));
            if (offset >= 32)
            {
                throw new InvalidOperationException(SR.BitVectorFull);
            }
            return new Section(CreateMaskFromHighValue(maxValue), offset);
        }
```
creates a new section, given the previous section and the maxValue for the new section.

However, the lines:
```
            short offset = (short)(priorOffset + CountBitsSet(priorMask));
            if (offset >= 32)
            {
                throw new InvalidOperationException(SR.BitVectorFull);
            }
```
test for the previous section being invalid, not the new one being created.

It would seem like the code should be:

```
            short offset = (short)(priorOffset + CountBitsSet(priorMask));
            if (offset + CountBitsSet (CreateMaskFromHighValue(maxValue)) >= 32)
            {
                throw new InvalidOperationException(SR.BitVectorFull);
            }
```
Obviously, there is better ways to actually write the code.  I am just demonstrating the issue.

The documentation states that the InvalidOperationException should be thrown if "maxValue is greater than the  highest value that can be represented by the number of bits after previous."

**Comment by tannergooding** [comment]
@eiriktsarpalis @layomia, would this fall under `System.Collections`? I'm not sure if this was mislabeled or not...

The issue does look like a bug:
```csharp
var section1 = BitVector32.CreateSection(short.MaxValue);           // 0x0FFF, 0x00     0b0000_0000_0000_0000_0000_1111_1111_1111   Bits 00 to 11
var section2 = BitVector32.CreateSection(short.MaxValue, section1); // 0x0FFF, 0x0C     0b0000_0000_1111_1111_1111_0000_0000_0000   Bits 12 to 23
var section3 = BitVector32.CreateSection(short.MaxValue, section2); // 0x0FFF, 0x18     0b1111_1111_0000_0000_0000_0000_0000_0000   Bits 24 to 35!
```

**Comment by eiriktsarpalis** [comment]
Yes, looks like it. Relabeling..

**Comment by huoyaoyuan** [comment]
There is a test expecting highest section to be truncated:

https://github.com/dotnet/runtime/blob/a822d3909b90139b642b143e889505ab7157b10c/src/libraries/System.Collections.Specialized/tests/BitVector32Tests.cs#L388-L405

And the exception documentation implies that:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.bitvector32.createsection?view=net-5.0

> previous includes the final bit in the BitVector32.
> -or-
> maxValue is greater than the highest value that can be represented by the number of bits after previous.

What should we do here? @eiriktsarpalis

**Comment by eiriktsarpalis** [comment]
I suppose we could close the issue as by-design, but the behavior still bothers me.

cc @Clockwork-Muse

**Comment by Clockwork-Muse** [comment]
... I tried to fix this a long time ago, https://github.com/dotnet/corefx/pull/2920 , but was told not to bother since it was a legacy type, so wrote the test as documentation of as-current behavior (although I left the existing validation alone, for some reason).

**Comment by eiriktsarpalis** [comment]
Thanks for the context. In that case I'm going to close this issue as by-design.
