### ISSUE TITLE
System.Drawing.Bitmap.LockBits not implemented on linux

### ISSUE THREAD

**Issue by hanabi1224** [dotnet/runtime#31416]
Hello, I got below exceptions running program with docker image mcr.microsoft.com/dotnet/core/aspnet:3.0 (While it works fine on windows)  Are there any alternatives?

System.NotImplementedException: Not implemented.
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)

```csharp
var rect = new Rectangle(x: 0, y: 0, width: width, height: height);
var destBmpData = destBmp.LockBits(rect, ImageLockMode.ReadOnly, PixelFormat.Format16bppRgb565);
```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
