### ISSUE TITLE
[Bug] - System.Net.Http.HttpClient randomly throws 'Host not found' exception

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/runtime#31422]
> Do re-route this bug to the right repo if this is not the right one

I have found that ` System.Net.Http.HttpClient` randomly throws "Host not found" or "No such host is known" exceptions. This is especially true if this is used during app spin up. A restart of the app "fixes" it until a random point of time in the future. There is nothing "special" about the hosts it throws this for, it can be anything, including `localhost`! 

In my scenarios, this happens with ASP.NET Core applications, where the error is annoying especially after a new deployment when you find the app is not running and you go into the logs to find this to be the issue.

NOTE: When the exception happens, app restart seems to be the only way to cure it. If you try to recover by re-firing the request that failed, you still end up with the same exception. Looks like some internal state is permanently set?

**Comment by davidsh** [comment]
@sujayvsarma Are you still having this issue? We don't have enough information to diagnose at this time.

**Comment by sujayvsarma** [comment]
No. Over the past 3 months, the number of these exceptions over time have fallen off drastically. Not sure what caused the tail off (to point to the "fix"), but this bug can be safely closed at this time.

**Comment by deadmann** [comment]
HttpClient .Net Core 3.1 is buggy... for example: if i use 
BaseAddress: xyz.com/api/
and partial address: vwk/lmn
it will send request too: 

xyz.com/vwk/lmn 
yet if you look inside httpClient, it stored base address fully...
![Untitled](https://user-images.githubusercontent.com/1919241/82444889-23e41980-9ab9-11ea-978f-199d087c5f9f.jpg)


This is so unexpected to face so much lack or bugs in Microsoft products in this new platform, and i'm grateful to these 5 past years, which i didn't had to working with .net core. I hope by the day .Net Core fix it's bugs and shortage it could still claim that it's faster and better than the old .net framework.

**Comment by stephentoub** [comment]
@deadmann, that is unrelated to this issue.  If you're having a different problem, please open a new issue.

That said, if the relative address begins with a '/', then it'll replace the whole path.  In your screenshot, the `partialUrl` is `/accounting/getToken`.  If you execute:
```
new Uri(new Uri("http://sandbox.safarbooking.com/api/"), "/accounting/getToken")
```
you'll see that will give you:
```
http://sandbox.safarbooking.com/accounting/getToken
```
whereas if you execute:
```
new Uri(new Uri("http://sandbox.safarbooking.com/api/"), "accounting/getToken")
```
you'll see that'll give you:
```
http://sandbox.safarbooking.com/api/accounting/getToken
```

**Comment by deadmann** [comment]
is it why in api controller you define a route, it can be both partial and in whole at same time? but yet they shouldn't ship it to a working old existing code

**Comment by stephentoub** [comment]
> but yet they shouldn't ship it to a working old existing code

If you have a repro of something that previously worked and broke upon upgrade, it'd be great if you could open a new issue that includes the repro that can be run on both the previous and new runtimes in order to see the difference.  Thanks.

**Comment by deadmann** [comment]
yes, i wrote this in 4~5 year of working inside Ravis company, who wrote flight reservation systems, and also gather itself and others services data, inside a flight search engine software.

https://github.com/deadmann/AdvanceRestHandler

but I got 3 minutes before my class start, so i gotta go.
