### ISSUE TITLE
Imprecise use of Base64 in Request-Ids

### ISSUE THREAD

**Issue by jenspiir** [dotnet/runtime#31427]
In [the spec for Hierarchical Request-Id]s(https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HierarchicalRequestId.md), the following is stated:

> Root Request-Id MUST contain only Base64 and "-" (hyphen) characters.

Should this be understood as:
a) The Request-Id MUST only consist of the characters allowed in Base64, with hyphens occurring in arbitrary places.
*or*
b) The Request-Id MUST only consist of Base64 encoded values that may be separated by hyphens.

The latter might require one to ensure proper padding and such.

How should I interpret this?

**Comment by noahfalk** [comment]
Sorry this has sat unanswered a long time. I think (a) is the correct interpretation. The code that observes new IDs from the wire and appends a child suffix is [here](https://github.com/dotnet/runtime/blob/129c8ca06935da5fe52afd3faf682d98b522485a/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L1090-L1103). The source that generates new ID for root Activities is [here](https://github.com/dotnet/runtime/blob/129c8ca06935da5fe52afd3faf682d98b522485a/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L1107-L1108).

The .NET code doesn't base64 encode or decode any data so I assume the reference to base64 was solely a useful way to reference the character set. The original author of the spec has retired so I can't know his intent for certain, but the code wouldn't align well with the other option.

FWIW, starting from .NET Core 3.0 DiagnosticSource also supports [W3C TraceContext](https://www.w3.org/TR/trace-context/) specification for IDs and in .NET 5.0 W3C IDs are used by default. Hierarchical remains supported for any applications that want to use it but we expect most .NET customers will prefer the emerging W3C industry standard.
