### ISSUE TITLE
Support of SFTP and SCP

### ISSUE THREAD

**Issue by chrgraefe** [dotnet/runtime#31437]
Please add support of sftp and scp protocols in the "System.Net" Namspace. Since FTP isn't a reliable protocol any more, it is time to support more secure and widly supported protocols for .net core.

**Comment by MattMcL4475** [comment]
@tmds +1 for native SSH support in .NET Core.  SSH.NET is effectively broken on macOS Catalina due to https://github.com/sshnet/SSH.NET/issues/355

**Comment by drieseng** [comment]
@MattMcL4475 I'll be fixing that issue some time this week. I know it's long overdue.

**Comment by martinvobr** [comment]
Maintained list of all known 3rd party SFTP client libraries for .NET (both free and commercial) is here:  https://www.sftp.net/client-libraries

**Comment by drieseng** [comment]
@MattMcL4475 In case you didn't see the announcement, the issue you mentioned (https://github.com/sshnet/SSH.NET/issues/355) is fixed in version [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) of [**SSH.NET**](https://github.com/sshnet/SSH.NET).

**Comment by danmosemsft** [comment]
Is there a reason to keep this open now? Is there an unmet need that can only reasonably be met in the platform itself?

**Comment by chrgraefe** [comment]
This is right, there is no reason to keep this issue open.

**Comment by danmosemsft** [comment]
Thanks @chrgraefe
