### ISSUE TITLE
Regressions in System.Collections.IterateForEach

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#31452]
There is a 28% regression in System.Collections.IterateForEach<Int32>.LinkedList(Size: 512) between 3.0->3.1.

![image](https://user-images.githubusercontent.com/9439069/68520833-f2f47380-024f-11ea-8ea4-ad92e6852abb.png)

**Comment by danmosemsft** [comment]
@DrewScoggins any updated data on this one?

The runtime and libraries barely changed from 3.0 to 3.1 so that is curious.

**Comment by DrewScoggins** [comment]
No update, and my guess is that we probably just close this issue.

**Comment by danmosemsft** [comment]
@layomia?
