### ISSUE TITLE
Regression in System.Tests.Perf_String.ToLowerInvariant

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#31453]
There is a regression of 138% in System.Tests.Perf_String.ToLowerInvariant(s: "TEST") between 3.0->3.1.

![image](https://user-images.githubusercontent.com/9439069/68520855-27682f80-0250-11ea-8e2c-72096ed1669f.png)

**Comment by danmosemsft** [comment]
@DrewScoggins is this issue still relevant/useful? Should we track everytihng in https://github.com/dotnet/runtime/issues/37816?

**Comment by DrewScoggins** [comment]
Yeah, we should close this and do the tracking in the other bug.
