### ISSUE TITLE
Setting SerialPort.ReadBufferSize property doesn't seem to affect the tty buffer

### ISSUE THREAD

**Issue by ss4adam** [dotnet/runtime#31476]
`_serialPort.ReadBufferSize = 3000000; // three megabytes,` this works fine in windows and lets me read a massive chunk of data, but in Linux I can't seem to read anything past 4096 bytes.

later if I use` _serialPort.Read(dataBuffer, 0, dataBuffer.Length);` then I miss anything outside of this 4K range. I like reading a large buffer rather than lots of small reads because I'm sending files and worried that the computer freezing up could make me lose a piece of the data in the middle of the transfer

I know in the past the linux kernel had an internal buffer of 4096 bytes.
If this buffer is full and a new character arrives on the serial port,
the oldest character in the buffer will be overwritten and thus will be lost. I'm using RedHat7

Is this a problem that .NET can even fix if the kernel is limiting the buffer size? I'm not strong at Linux so I'm not sure. If this can't be fixed, should an exception be thrown?

**Comment by JeremyKuhne** [comment]
Triage: Closing, @ss4adam please reopen if you get a repro that shows that we're losing data.
