### ISSUE TITLE
EnumerableRewriter fails with unhandled NullReferenceException

### ISSUE THREAD

**Issue by fvolner** [dotnet/runtime#31473]
An unhandeled `NullReferenceException` is thrown by the method
`System.Linq.EnumerableRewriter.FindEnumerableMethod(string name, ReadOnlyCollection<Expression> args, params Type[] typeArgs)`

The method only asserts the resulting `MethodInfo` in debug mode.

https://github.com/dotnet/corefx/blob/21278249c6b417469737b20445a0dd045cd1b16e/src/System.Linq.Queryable/src/System/Linq/EnumerableRewriter.cs#L215-L226
On runtime, no check is performed and possible unhandled `NullReferenceException` will be thrown when returning either 

- the `return mi.MakeGenericMethod(typeArgs)` 
- or just the `MethodInfo` and it would be later used in the `VisitMethodCall` method without validating for null reference.

**Comment by jaredpar** [comment]
Closing as there is no response to the request for a repro. Would be happy to revisit this issue if a repro can be provided.
