### ISSUE TITLE
HttpClient .net core 3 don't read all response content

### ISSUE THREAD

**Issue by felipeOliveira** [dotnet/runtime#31480]
At first I thought it could be an encoding problem, but calling this endpoint by postman it`s works correctly. In postman and Fiddler the response have a content-length of 147bytes and these two clients can read a response content correctly, but with httpClient the response content have only 130 bytes .

![image](https://user-images.githubusercontent.com/2717505/68733080-5ebe3f80-05b4-11ea-8cf8-d96d4eabd0fd.png)

this is a printscreen of application request captured by the fiddler. On fiddler the request and response seems to be ok, but when the httpclient try read the response content the string of json is not readed as img above
![image](https://user-images.githubusercontent.com/2717505/68733199-a5ac3500-05b4-11ea-86d5-83a8951ef387.png)

**Comment by alnikola** [comment]
Could you please confirm that in the repro code above the ```token``` value happens to be an empty string whereas you expect it to be that JSON string ```"{"number_token":....."}"```? Is my understanding correct?

**Comment by karelz** [comment]
@felipeOliveira ping? (see @alnikola's question above)

**Comment by felipeOliveira** [comment]
@alnikola, no the value expected is `"{"number_token":....."}"`. But the client returns a a malformed string like t variable in the first image

**Comment by karelz** [comment]
I am not sure how we can make any progress without a repro here, or someone debugging it.
@felipeOliveira does it happen always? Or is it intermittent?
If it is 100%, are you in position to debug it?

**Comment by felipeOliveira** [comment]
It's always happened, but I can't post a part of code beacause it's a payment gateway and have sensive information. I will close this issue, because I changed a payment gateway and you cannot reproduce this without a code.
