### ISSUE TITLE
FromBody not working

### ISSUE THREAD

**Issue by kadirguloglu** [dotnet/runtime#31499]
Hello,
I get the error in the attached images in my project.

Visual studio recommends that I use FromBody ... as an error message. The application gives error even though I use it.

![Ekran Alıntısı](https://user-images.githubusercontent.com/28136387/68890222-7cfc7a80-072f-11ea-980e-e707cd289f82.PNG)
![Ekran Alıntısı1](https://user-images.githubusercontent.com/28136387/68890223-7d951100-072f-11ea-974d-c1a242b0b350.PNG)

**Comment by joperezr** [comment]
Question seems to be answered by reading the above, so closing this.
