### ISSUE TITLE
Infrastructure work required to service 5.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#31505]
We are making a lot of infra changes which will require changes in the servicing protocals. This issue is to track that work.

- [ ] We have a centralized place for package verison, we will have to find a place  of individuals packages to update that version in servicing
- [ ] We have a centeralized place for assembly Verision, we will have to find a way to increment the assembly version for specific assemblies in servicing.

cc @ericstj @ViktorHofer @wtgodbe @safern @danmosemsft

**Comment by ericstj** [comment]
@ViktorHofer that sounds right.  We then manually rev AssemblyVersions when we need to patch packages that require a change.  I wonder if we can codify that rule 🤔 .  Perhaps for any project that targets NETFramework it's assembly version bumps in servicing.  Then we go through and make sure every library that supports NETFramework has a NETFramework target?  @joperezr

**Comment by joperezr** [comment]
>Perhaps for any project that targets NETFramework it's assembly version bumps in servicing

I'm not sure I follow why we would do this every time. Is it because of the concern that the assembly could be GACed? If we are only bug fixing one small thing in an assembly, doing this will introduce the possiblity of requiring BindingRedirects on the app which a lot of people want to avoid.

**Comment by ViktorHofer** [comment]
@Anipik the title links to 5.0 servicing. Should we move the milestone back? Do you know what the remaining work here is?

**Comment by Anipik** [comment]
>  Should we move the milestone back? Do you know what the remaining work here is?

I moved it back to 5.0.

I want to see if we can automize the following
1. Package  Version rev ups 
2. Assembly Version rev ups and pinning of assembly version for ref assemblies
3. A check to verify we are actually building and shipping the package we are changing.

we have hit errors in the past where we have  missed some cases during the review. The error rate is low for last few releases but its still dependent on manual review. Most of the people are not aware of these servicing nitpicks.

**Comment by ViktorHofer** [comment]
Sounds good. I assigned you to the issue.

**Comment by ViktorHofer** [comment]
@Anipik pls prioritize this work item over pre6.0 work. We are showing up high on Jeff's table 🗡️

**Comment by Anipik** [comment]
>@Anipik pls prioritize this work item over pre6.0 work. We are showing up high on Jeff's table 🗡️

i moved it to 5.0.X (Talked with @danmosemsft about creating this new one)

**Comment by ericstj** [comment]
I chatted with Jeff about this on Monday so he's aware.  5.0.x seems reasonable, I'll make sure he knows about that so it stays out of the query.

**Comment by ViktorHofer** [comment]
@Anipik what's left to do here? I believe anything necessary to service 5.0 for next ~11 months should already be in place?

**Comment by Anipik** [comment]
yes we can close this one
