### ISSUE TITLE
Problems with SemaphoreSlim on OSX

### ISSUE THREAD

**Issue by johnnyasantoss** [dotnet/runtime#31502]
Hello,
I noticed that `SemaphoreSlim.WaitAsync(int)` is sometimes extremely slow on OSX.

I was trying to set up a test and build a R2R version of a console app on Azure Pipelines, and noticed that the MacOS tests were failing on a simple wait & release [test][test1] ([logs][logs1]).

So, I created a simplified version of that test and tried to run again using the same matrix.
Here's the [repro][r1], and here is the [pipeline][p1] with the failed jobs on OSX.

BTW I'm using Linux and I don't have a machine with OSX available to test this.

This issue might be related to dotnet/runtime#25790

 [test1]: https://github.com/johnnyasantoss/ExchangeSharp/blob/e9d3589b5fa08afffd70b0fc98756f7988cee0ea/tests/ExchangeSharpTests/CryptoUtilityTests.cs#L229-L255
 [logs1]: https://dev.azure.com/johnnyasantoss/ExchangeSharp/_build/results?buildId=13&view=logs&j=2da5cbf6-3d4c-554d-b450-f46789d0dcc6&t=d93bf2ca-2f6d-5bb9-d851-d18567965641&l=23
 [r1]: https://github.com/johnnyasantoss/semaphore-slim-osx-repro
 [p1]: https://dev.azure.com/johnnyasantoss/semaphore-slim-osx-repro/_build?definitionId=2&_a=summary

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/11226
