### ISSUE TITLE
SerialPort error on Virtual Serial Port for USB LINUX

### ISSUE THREAD

**Issue by JTrotta** [dotnet/runtime#31523]
The problem should be related to the DTR setting. It cannot be done on virtual ports.

This is the error opening a /dev/ttyUSB7 port:
`Hello World! Unhandled exception. System.IO.IOException: Broken pipe at System.IO.Ports.SerialStream.set_DtrEnable(Boolean value) at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace) at System.IO.Ports.SerialPort.Open() at RPTestcore3.Program.Start7() in D:\Visual Studio 2019\Projects\RPTestcore3\RPTestcore3\Program.cs:line 43 at RPTestcore3.Program.Main(String[] args) in D:\Visual Studio 2019\Projects\RPTestcore3\RPTestcore3\Program.cs:line 32 Aborted`

The problem should be here:
`        internal SerialStream(string portName, int baudRate, Parity parity, int dataBits, StopBits stopBits, int readTimeout, int writeTimeout, Handshake handshake,
            bool dtrEnable, bool rtsEnable, bool discardNull, byte parityReplace)`

at row568.
`DtrEnable = dtrEnable;`

which calls property:

```cs
internal bool DtrEnable
        {
            get
            {
                int status = Interop.Termios.TermiosGetSignal(_handle, Interop.Termios.Signals.SignalDtr);
                if (status < 0)
                {
                    throw GetLastIOError();
                }

                return status == 1;
            }

            set
            {
                if (Interop.Termios.TermiosGetSignal(_handle, Interop.Termios.Signals.SignalDtr, value ? 1 : 0) != 0)
                {
                    throw GetLastIOError();
                }
            }
        }`

We cannot set SignalDtr on Linux Virtual Ports.

**Comment by JeremyKuhne** [comment]
Triage: @JTrotta, we're all moved now, can you start on a proposed fix? If we change the API we'll need to go through the [API proposal process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

**Comment by JTrotta** [comment]
> Triage: @JTrotta, we're all moved now, can you start on a proposed fix? If we change the API we'll need to go through the [API proposal process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

I'm reading [API proposal process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).
And will try to propose

**Comment by JTrotta** [comment]
SerialPort error on Virtual Serial Port for USB LINUX.
The problem should be related to the DTR setting. It cannot be done on virtual ports. It means that we cannot call the Interop

**Interop.Termios.TermiosGetSignal(_handle, Interop.Termios.Signals.SignalDtr);**

I got the same problem in MONO, so I created a new serial port library, using the Windows one and adding ne API constructor. 

# Rationale and Usage
The idea is to allow users to activate a flag during port creation, adding a new API contructor.
This is my working API constructor in MONO:
```		
public SerialPort (string portName, int baudRate, Parity parity, int dataBits, StopBits stopBits, bool isVirtualPort) 
{
  port_name = portName;
  baud_rate = baudRate;
  data_bits = dataBits;
  stop_bits = stopBits;
  this.parity = parity;
  this.is_virtual_port = isVirtualPort;
}
```
is_virtual_port  should be a new private field.

# Proposed API
In dotnetcore SerialPort.cs we should add a new constructor or modify the last polymorphic:
```
// all the magic happens in the call to the instance's .Open() method.
// Internally, the SerialStream constructor opens the file handle, sets the device
// control block and associated Win32 structures, and begins the event-watching cycle.
public SerialPort(string portName, int baudRate, Parity parity, int dataBits, StopBits stopBits, bool IsVirtualPort) : this()
        {
            PortName = portName;
            BaudRate = baudRate;
            Parity = parity;
            DataBits = dataBits;
            StopBits = stopBits;
            IsVirtualPort = isVirtualPort;
        }
```
Add a filed and a  property:
```
bool is_virtual_port;
public bool IsVirtualPort
{
            get
            {
                return is_virtual_port;
            }
            set
            {
                is_virtual_port = value;
            }
}
```
Pass the property to the stream when open it:
```
public void Open()
{
   if (IsOpen)
      throw new InvalidOperationException(SR.Port_already_open);
_internalSerialStream = new SerialStream(_portName, _baudRate, _parity, _dataBits, _stopBits, _readTimeout, _writeTimeout, _handshake, _dtrEnable, _rtsEnable, _discardNull, _parityReplace, _is_virtual_port );
........
```
In SerialStream.Unix.cs, add a new ctrs or modify the current:
```
 // this method is used by SerialPort upon SerialStream's creation
internal SerialStream(string portName, int baudRate, Parity parity, int dataBits, StopBits stopBits, int readTimeout, int writeTimeout, Handshake handshake, bool dtrEnable, bool rtsEnable, bool discardNull, byte parityReplace, bool isVirtualPort)
            if (portName == null)
            {
                throw new ArgumentNullException(nameof(portName));
            }

            CheckBaudRate(baudRate);

            // Error checking done in SerialPort.

            SafeSerialDeviceHandle tempHandle = SafeSerialDeviceHandle.Open(portName);

            try
            {
                _handle = tempHandle;
                // set properties of the stream that exist as members in SerialStream
                _portName = portName;
                _handshake = handshake;
                _parity = parity;
                _readTimeout = readTimeout;
                _writeTimeout = writeTimeout;
                _baudRate = baudRate;
                _stopBits = stopBits;
                _dataBits = dataBits;

                if (Interop.Termios.TermiosReset(_handle, _baudRate, _dataBits, _stopBits, _parity, _handshake) != 0)
                {
                    throw new ArgumentException();
                }

                //DtrEnable = dtrEnable; //HERE IS THE PROBLEM If a port is Virtual Interop.Termios.TermiosGetSignal DTR cannot be used
            if (!isAVirtualPort)
                DtrEnable = dtrEnable;

                BaudRate = baudRate;
```
And change the current line [568](https://github.com/dotnet/runtime/blob/5eda36ed557d789d888647745782b261472b9fa3/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.Unix.cs#L568) like above.

# Details
Anyway, whatever will be the final API, the proble is that we cannot set DTR on Linux when port are virtual.

**Comment by willdean** [comment]
Personally I don't think "is a virtual port" is very well defined (I think I would say a 'virtual port' was one which emulated a port purely in software, not one which was physically implemented but via USB), and even if it was well-defined, "throws an exception if you try and set DTR" would not necessarily be exactly the same thing.   Lots of USB ports do support DTR operations, for example.

In reality there is no clear definition of what any serial port implementation is and isn't able to do, nor how reacts if asked to do something it can't actually physically carry out.

I think a more general approach of simply being more tolerant of these sort of errors might be better, at least within the constructor.  If we were to try and selectively enable or disable features, I think we would need a broader system of doing that than would be feasible to implement via bool args to a constructor.

It seems reasonable to me that the constructor/open call shouldn't throw for things like this, but if you actually called `DtrEnable` yourself, then it would throw.
