### ISSUE TITLE
Bug in DateTimeConverter when time has been specified

### ISSUE THREAD

**Issue by ulfemsoy** [dotnet/runtime#31527]
When converting DateTime, with a specified time, to string the wrong format is used.
Source: System.ComponentModel.TypeConverter/src/System/ComponentModel/DateTimeConverter.cs (line dotnet/corefx#120)

The following line (line number 120)
return dt.ToString(format, CultureInfo.CurrentCulture);

should be replaced with
return dt.ToString(format, culture);

**Comment by ericstj** [comment]
Seems like a reasonable request.  Bug has been around since desktop though and will be a breaking change.
https://referencesource.microsoft.com/#System/compmod/system/componentmodel/DateTimeConverter.cs,121

Too late in 5.0 to consider such breaks unless there is a compelling scenario that's blocked without workaround.

**Comment by ericstj** [comment]
Too late to take breaking changes in 6.0.0 at this point.

**Comment by Maximys** [comment]
@ericstj , it's really very funny, that line with problem was ported to other classes, linked with Date and Time. Simple search inside my favorite file manager (Far Manager), had display me next result:

1. [DateOnlyConverter](https://github.com/dotnet/runtime/blob/f107b4b53e831ac631ab91cc9cee0200d96a7eee/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/DateOnlyConverter.cs#L98);
2. [DateTimeConverter](https://github.com/dotnet/runtime/blob/f107b4b53e831ac631ab91cc9cee0200d96a7eee/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/DateTimeConverter.cs#L117);
3. [DateTimeOffsetConverter](https://github.com/dotnet/runtime/blob/f107b4b53e831ac631ab91cc9cee0200d96a7eee/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/DateTimeOffsetConverter.cs#L129);
4. [TimeOnlyConverter](https://github.com/dotnet/runtime/blob/f107b4b53e831ac631ab91cc9cee0200d96a7eee/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TimeOnlyConverter.cs#L91).

Can I try to fix it by single commit?

**Comment by ericstj** [comment]
@dotnet/area-system-componentmodel @dotnet/area-system-globalization @dotnet/dotnet-winforms can i get your take on the risk of the breaking change here vs value of fix?

**Comment by tarekgh** [comment]
I see this is something that needs to be fixed even if it is a breaking change. Currently `ConvertTo` is not consistent with `ConvertFrom`. In addition, it is very weird even in `ConvertTo` to get the date format pattern from the input `culture` and format with `CurrentCulture`. I see it can cause some issues. 
I am expecting most scenarios will be just passing either `null`, `Invriant`, or `CurrentCulture` which I think will reduce the breaking change risk. So I am supportive to the change.
