### ISSUE TITLE
API proposal: Modern Timer API

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#31525]
To solve of the common issues with timers:
1. The fact that it always captures the execution context is problematic for certain long lived operations (https://github.com/dotnet/corefx/issues/32866)
2. The fact that is has strange rooting behavior based on the constructor used
3. The fact timer callbacks can overlap (https://github.com/dotnet/corefx/issues/39313)
4. The fact that timer callbacks aren't asynchronous which leads to people writing sync over async code

I propose we create a modern timer API based that basically solves all of these problems 😄 .

- This API only makes sense for timers that fire repeatedly, timers that fire once could be Task based (we already have `Task.Delay` for this)
- The timer will be paused while user code is executing and will resume the next period once it ends.
- The timer can be stopped using a CancellationToken provided to stop the enumeration.
- The execution context isn't captured.

```diff
+namespace System.Threading
+{
+   public class AsyncTimer : IDisposable, IAsyncDisposable
+   {
+        public AsyncTimer(TimeSpan period);
+        public ValueTask<bool> WaitForNextTickAsync(CancellationToken cancellationToken);
+        public void Stop();
+   }
+}
```

Usage:

```C#
class Program
{
    static async Task Main(string[] args)
    {
        var second = TimeSpan.FromSeconds(1);
        using var timer = new AsyncTimer(second);

        while (await timer.WaitForNextTickAsync())
        {
            Console.WriteLine($"Tick {DateTime.Now}")
        }
    }
}
```

```C#
public class WatchDog
{
    private CanceallationTokenSource _cts = new();
    private Task _timerTask;

    public void Start()
    {
        async Task DoStart()
        {
            try
            {
                await using var timer = new AsyncTimer(TimeSpan.FromSeconds(5));

                while (await timer.WaitForNextTickAsync(_cts.Token))
                {
                    await CheckPingAsync();
                }
            }
            catch (OperationCancelledException)
            {
            }
        }

        _timerTask = DoStart();
    }

    public async Task StopAsync()
    {
        _cts.Cancel();

        await _timerTask;

        _cts.Dispose();
    }
}
```

## Risks

New Timer API, more choice, when to use over Task.Delay?

### Alternative 1: IAsyncEnumerable

The issue with IAsyncEnumerable is that we don't have a non-generic version. In this case we don't need to return anything per iteration (the object here is basically void). There were also concerns raised around the fact that `IAsyncEnumerable<T>` is used for returning data and not so much for an async stream of events that don't have data.

```diff
public class Timer
{
+     public IAsyncEnumerable<object> Periodic(TimeSpan period);
}
```

```C#
class Program
{
    static async Task Main(string[] args)
    {
        var second = TimeSpan.FromSeconds(1);

        await foreach(var _ in Timer.Periodic(second))
        {
            Console.WriteLine($"Tick {DateTime.Now}")
        }
    }
}
```

### Alternative 2: add methods to Timer

- Avoids a new type
- Confusing to think about what happens when WaitForNextTickAsync is called when a different constructor is called.

```diff
public class Timer
{
+     public Timer(TimeSpan period);
+     ValueTask<bool> WaitForNextTickAsync(CancellationToken cancellationToken);
}
```

cc @stephentoub

**Comment by plaisted** [comment]
@benaadams 
I like the generic factory, might be useful to have an overload something along the lines of the below in the case that you wanted to implement the Timer example with a fixed interval (eg. DateTime object exactly 30 seconds apart) rather than when the Func was called. The input for the factory could be a TimeSpan for total time since creation (periods*iterations) or just have an int representing iterations. Even some sort of context object with the time of first iteration and the timespan since then could be nice.

```csharp
public class Timer
{
    public static IAsyncEnumerable<T> Periodic(
        Func<TimeSpan, T> valueFactory,
        TimeSpan dueTime, 
        TimeSpan period, 
        CancellationToken cancellationToken = default);
}
```

**Comment by davidfowl** [comment]
@stephentoub  I'd like to push this back into 6.0.0, any concerns?

**Comment by stephentoub** [comment]
Nope

**Comment by 3dGrabber** [comment]
I like the idea.

However I'd propose a simpler, more modular API:


```C#
// CancellationToken omitted for brevity
public static async IAsyncEnumerable<long> Periodic(TimeSpan period)
{
    long i = 0; 
    while(true)
    {
        yield return i++;
        await Task.Delay(period);   
    }
}
```
There is no need for `dueTime`.  
If the consumer wants to wait before producing values, he can `Task.Delay` before starting the loop.  
Similarly, `valueFactory` can be moved outside.
  
So this:
```C#
var dueTime = TimeSpan.FromSeconds(3);
var period = TimeSpan.FromSeconds(1);
var rng = new Random();

foreach (var x in Timer.Periodic(dueTime, period, () => rng.Next())
{
    Console.WriteLine(x);
}
```
becomes this:
```C#

await Task.Delay(dueTime);

foreach (var _ in Timer.Periodic(period))
{
    var x = rng.Next();
    Console.WriteLine(x);
}
```

or with LINQ:

```C#
var stream = Timer
            .Periodic(period)
            .Delay(dueTime)           // Delay operator TBD (?)
            .Select(_ => rng.Next())  // Select available through System.Linq.Async (?)

foreach (var x in stream)
{
    Console.WriteLine(x);
}
```

As others have pointed out, this is similar to [Observable.Interval](http://introtorx.com/Content/v1.0.10621.0/04_CreatingObservableSequences.html#ObservableInterval).  
(It's a shame RX has no decent official doc)

RX has a nice modular/orthogonal API, I think it'd be worth it to look at it for inspiration.
Or maybe the RX team themselves make it part of `System.Linq.Async`?

**Comment by davidfowl** [comment]
I have a couple of goals with this API:
- Fix a set of timer misuses called out and linked above 
- remove callbacks from the API 

I like the timer.periodic without a callback. However the implementation is less efficient than using a timer with a period.

It needs to be in the box so we can replace a bunch of timers with this without taking a dependency on Rx or Ix.

**Comment by davidfowl** [comment]
I think this is ready for the first round of API review.

**Comment by stephentoub** [comment]
> I think this is ready for the first round of API review.

- What is the long that's yielded?
- Given your desire to reuse timer instances in the other issue, I'm a little surprised this proposal doesn't encompass that,  e.g. an overload that supports not starting the next period until MoveNextAsync is called.

**Comment by davidfowl** [comment]
> What is the long that's yielded?

I actually would prefer this to be Void but I didn't want to define that struct. We'll need to either figure out a good use for the generic parameter or make a new type to hide it (IAsyncEnumerable non generic).

> Given your desire to reuse timer instances in the other issue, I'm a little surprised this proposal doesn't encompass that, e.g. an overload that supports not starting the next period until MoveNextAsync is called.

I thought about adding the overload but wasn't sure what to call the bool, that can be brought up in API review. Open to ideas and I don't think it changes consumption, it's just an overload.

> Can you point to one or more places this will be used in ASP.NET, extensions, etc. in 6.0 to help validate the design?

ASP.NET Core has a type for this today https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/common/Shared/TimerAwaitable.cs

Used here https://github.com/dotnet/aspnetcore/blob/46359cd0a28f551d4021c9c9823752b049eaec79/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionManager.cs#L125

https://github.com/dotnet/aspnetcore/blob/46359cd0a28f551d4021c9c9823752b049eaec79/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1806

**Comment by davidfowl** [comment]
OK I updated the proposal and moved away from IAsyncEnumerable for reasons stated above and listed it as an alternative instead.

**Comment by willdean** [comment]
Does "The timer will be paused while user code is executing and will resume the next period once it ends." mean that the actual cycle period is the total of the code execution time plus the configured timer interval?   If so, is there any substantive difference between the proposed timer simply using `Task.Delay(period)`, like this:

```
class Program
{
    static async Task Main(string[] args)
    {
        var second = TimeSpan.FromSeconds(1);
 
        while (true)
        {
            await Task.Delay(second);
            Console.WriteLine($"Tick {DateTime.Now}")
        }
    }
}
```

But maybe that's not what "paused" implies?

**Comment by davidfowl** [comment]
I hope in API review we discuss the other option as well (where the next dueTime is interval - time to execute your code) as it could support both easily.

It's also more efficient than Task.Delay:
- There's no task allocation per delay
- There's no timer allocation per delay

The last thing is that the pattern that makes it nice is the `ValueTask<bool>` return type means you don't need to `While(true)`. If we figure out a way to make it IAsyncEnumerable work, then its possible we still end up with that as a pattern.

**Comment by willdean** [comment]
Thanks @davidfowl, that makes sense.  If either is feasible, then I would vote (as if I have a vote!) for the cycle time to be the configured interval (or best effort at) rather than (the interval + the execution time).   To me that that's what a 'timer' implies - something which keeps time independently of the code execution duration.

But this would require a definition of what happens about code execution which (occasionally, one presumes) overruns the configured interval, and there are several different ways of looking at this which are all right/wrong in different situations.  

I think there are three main possibilities:

1. It's just a delay, and the actual cycle period is configured interval + execution time.
2. The cycle period is the configured interval, and if the execution overruns you'll get re-scheduled immediately for the tick which you've missed.  Would there be a limit to how many of these late catch-up ticks you get immediately scheduled for?
3. The cycle period is effectively referenced to the original start time, so if you overrun a tick it's lost and nothing happens until the next tick is due.

(1) is like using `Task.Delay` and (2) & (3) are both things one can construct using `System.Threading.Timer` depending on how you handle re-entrant callbacks.

**Comment by omariom** [comment]
A TimeSpan parameter in WaitForNextTickAsync  would make the next scenario possible: 

```C#
    TimeSpan keepUp = TimeSpan.FromSeconds(1);
    TimeSpan next = keepUp;
    
    using var timer = new Ticker();
    
    while (await timer.WaitForNextTickAsync(next, default))
    {
        var sw = Stopwatch.StartNew();
        
        // ... some work
        
        next = (keepUp - sw.Elapsed);
        
        if (next < TimeSpan.Zero)
        {
            next = TimeSpan.Zero;
        }
    }
```

**Comment by terrajobst** [comment]
* We need to decide which model we want to use when you missed a period (1) should it complete immediately once (2) should it complete immediately for each period that was missed and (3) should it just skip to the next period. Supporting all would require an enum, but we may want to start simple, but we need to agree what "the simple" case is.
    - For ASP.NET's scenarios we only need mode (2).

```C#
namespace System.Threading
{
   public class PeriodicTimer : IDisposable
   {
        public PeriodicTimer(TimeSpan period);
        public ValueTask<bool> WaitForNextTickAsync(CancellationToken cancellationToken = default);
        public void Stop();
   }
}
```

**Comment by stephentoub** [comment]
@terrajobst, we didn't talk about assembly for this.  Where should it live?

**Comment by stephentoub** [comment]
System.Threading.Timer is implemented in corelib and exposed from System.Runtime.

**Comment by benaadams** [comment]
>  Any objections to that place? 

I thought Timers were a special type where each one needed to go in a different namespace? 😉

![image](https://user-images.githubusercontent.com/1142958/110552016-7cf76980-812e-11eb-9833-04334d69bfe4.png)


More seriously `System.Threading` sounds like a good place.

**Comment by danmoseley** [comment]
We maybe should improve that article to help people pick the right one., When looking for it, I actually found an article from 2004, when there were three, even back then it was apparently worth a magazine article to help explain ["The .NET Framework Class Library provides three different timer classes..."](https://docs.microsoft.com/en-us/archive/msdn-magazine/2004/february/comparing-the-timer-classes-in-the-net-framework-class-library)

**Comment by lloydjatkinson** [comment]
How do we write unit tests that use this? Has any thought been given to testability?

**Comment by weltkante** [comment]
> but if the delay is too big, it won't fit in the double

Any delay (in milliseconds) should fit into a double, you have 53 bits (or 15 decimal digits) precision, thats more than two hundred thousand years worth of waiting for your timeout if I didn't miscalculate. Thats longer than the machine is going to be running, considering the timers aren't persistent (will not survive restart of the process) double precision should be sufficient for any practical purpose.

**Comment by stephentoub** [comment]
Timer supports TimeSpans up to ~45 days, which means PeriodTimer would support such periods as well.  Larger values will fail.

**Comment by tebeco** [comment]
Hello,

regarding @benaadams's comment about the list of all existing timers here:
https://github.com/dotnet/runtime/issues/31525#issuecomment-794597247

Some of them should be concidered Obsolete to use when targeting .Net6 ?
The question about Timers is redundant on Community such as the CSharp Discord or Slack.
The confusion is especially affected by the two `System.Timers.Timer` vs `System.Threading.Timer`.
So my question is (naive on purpose), can something be done or are they both fully legitimate in modern code base ?

For example on the page of the `WebClient` we can see this:
![image](https://user-images.githubusercontent.com/2266487/114505222-572f1a00-9c30-11eb-932f-055d5beda7c3.png)

Even with that we see about 1 question every month using the `WebClient`, and not for upload, just for simple `GET` and deserialization.

If all class are legitimate, then my question would turn to the docs and wonder if there's like a "decision graph"
"do you use netfx ..." "do you use ....."

All of this of course assuming the `PeriodicTimer` being merged in .Net6, so also part of that big equation

**Comment by davidfowl** [comment]
Fun fact, node just stabilized their awaitable timer APIs: https://nodejs.org/api/timers.html#timers_timers_promises_api. They went with an async stream (async enumerable pattern):

```js
import {
  setInterval,
} from 'timers/promises';

const interval = 100;
for await (const startTime of setInterval(interval, Date.now())) {
  const now = Date.now();
  console.log(now);
  if ((now - startTime) > 1000)
    break;
}
console.log(Date.now());
```

**Comment by stephentoub** [comment]
Does that change your opinion on what shape you prefer here?

**Comment by davidfowl** [comment]
I'm not sure, I think it has similar problems to what we initially discussed in API review. Seems like you can pass a value that always gets returned when for the enumeration which I find bizzare:

```js
for await (const startTime of setInterval(1000,'1')) {
    console.log(startTime);
}
```

This just prints 1 over and over...

The only way to stop it from the outside is to use the equivalent of a cancellation token (the abort signal):

```js
var controller = new AbortController();

setTimeout(() => {
    controller.abort();
}, 
5000);

for await (const startTime of setInterval(1000,'1', { signal: controller.signal })) {
    console.log(startTime);
}
```

```
1
1
1
1
node:timers/promises:152
          callback(PromiseReject(new AbortError()));
                                 ^

AbortError: The operation was aborted
    at EventTarget.onCancel (node:timers/promises:152:34)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
    at EventTarget.dispatchEvent (node:internal/event_target:409:26)
    at abortSignal (node:internal/abort_controller:98:10)
    at AbortController.abort (node:internal/abort_controller:123:5)
    at Timeout._onTimeout (C:\dev\git\nodetest\app.js:11:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ABORT_ERR'
```

**Comment by omariom** [comment]
```C#
namespace System.Threading
{
   public class PeriodicTimer : IDisposable
   {
        public PeriodicTimer(TimeSpan period);
        public ValueTask<bool> WaitForNextTickAsync(CancellationToken cancellationToken = default);
        public void Stop();
   }
}
```

In such form the usage won't be very different from a while loop with a Task.Delay(..) within. It is not .. innovative.
Less allocations is not obvious, one would need to read about it in the remarks section of the docs. Also Task.Delays are easier to understand.

Instead, it could be 
```C#
   public class PeriodicTimer : IAsyncEnumerable<..>, IDisposable
   {
        public PeriodicTimer(TimeSpan period);
        public void Stop();
        ...
   }
```

**Comment by stephentoub** [comment]
> Instead, it could be

Every call to GetAsyncEnumerator should really produce its own isolated state... what would Stop here do?

**Comment by omariom** [comment]
> Every call to GetAsyncEnumerator should really produce its own isolated state.

Does it have to? 
Sometimes collections return `this` in `GetEnumerator`.

**Comment by stephentoub** [comment]
> Does it have to?

Yes

> Sometimes collections return this in GetEnumerator.

Do you have an example? That's typically only done as an optimization for the first enumeration.

**Comment by omariom** [comment]
> Do you have an example? 

Hmm.. haven't found a single one. That was probably in my collections :/

**Comment by stephentoub** [comment]
Maybe we take @omariom's suggestion of:
```C#
   public class PeriodicTimer : IAsyncEnumerable<..>, IDisposable
   {
        public PeriodicTimer(TimeSpan period);
        public void Stop();
        ...
   }
```
and say that any number of consumers can call GetAsyncEnumerator, each gets their own state (including their own underlying timer, etc.), the timer isn't started until GetAsyncEnumerator is called, and Stop stops all of them.  The type would no longer be IDisposable.

@davidfowl, thoughts?

**Comment by davidfowl** [comment]
OK this sounds interesting, lets try it.

**Comment by stephentoub** [comment]
@davidfowl and I spoke.  Two tweaks to the above:
- Functionally, we allow GetAsyncEnumerator to only ever be called once on the same instance.  Subsequent calls get an InvalidOperationException.  We can relax that in the future should we find a real need to enumerate the same instance multiple times.
- We remove the constructor and instead make this creatable from Timer, with a static CreatePeriodic method.  System.Threading.Timer remains the main place you go for this stuff.

```C#
namespace System.Threading
{
    public sealed class Timer
    {
        public static PeriodicTimer CreatePeriodic(TimeSpan period);
    }

    public sealed class PeriodicTimer : IAsyncEnumerable<TimeSpan>
    {
        public IAsyncEnumerator<TimeSpan> GetAsyncEnumerator(CancellationToken cancellationToken);
        public void Dispose();
    }
}
```

This means that if you just want to foreach, it's:
```C#
await foreach (TimeSpan ts in Timer.CreatePeriodic(period))
{
    ...
}
```

If you want to enumerate with cancellation, it's:
```C#
await foreach (TimeSpan ts in Timer.CreatePeriodic(period).WithCancellation(cancellationToken))
{
    ...
}
```

If you want to enumerate while also enabling another thread to stop you, it's:
```C#
private PeriodicTimer _timer = Timer.CreatePeriodic(period);
...
// Thread 1
await foreach (TimeSpan ts in _timer)
{
    ...
}
...
// Thread 2, at some point
_timer.Dispose();
```

And, of course, since this is an async enumerable, you can consume it with something like async LINQ, if desired.

**Comment by tebeco** [comment]
naive question on the last example:
```cs
private PeriodicTimer _timer = Timer.CreatePeriodic(period);
...
// Thread 1
await foreach (TimeSpan ts in _timer)
{
    await FooAsync(how do i get the cancellation here ?);

    // is there ?
    await FooAsync(_timer.CancellationToken);
}

// or is it with a tupple like PipeReader api
await foreach ( var (ts, ct) in timer))
{
  await FooAsync(ct);
}
...
// Thread 2, at some point
_timer.Dispose();
```

if the thread2 cancel or dispose the timer
how do i make the cancellation flow down ?

**Comment by stephentoub** [comment]
> if the thread2 cancel or dispose the timer how do i make the cancellation flow down ?

Disposing the timer will cause MoveNextAsync to start returning false. Canceling the cancellation token will cause MoveNextAsync to throw a cancellation exception.

**Comment by tebeco** [comment]
> Disposing the timer will cause MoveNextAsync to start returning false. Canceling the cancellation token will cause MoveNextAsync to throw a cancellation exception.

that works for the next tick, i'm wondering about the code inside the loop

```cs
private PeriodicTimer _timer = Timer.CreatePeriodic(period);
...
// Thread 1
await foreach (TimeSpan ts in _timer)
{
    // how do you cancel the line below "ASAP"
    // you don't always want to wait for MoveNextAsync
    await FooAsync(); // <== long operation
}
...
// Thread 2, at some point
_timer.Dispose();

if you want the outer+inner code to be cancellable at once you need to cancel both the loop and the code inside

i understand that there's way
* passing the cancellation-token into the thread state object
* sharing by closure
* etc ...

Since we're explicitly iteration on the timer i though we would have that token hold by the timer
