### ISSUE TITLE
Refactor core-setup host code for understandability, maintainability

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#3153]
- Split some of the source files up because they are too large. For example, fx_muxer.cpp is 1,500+ LOC.
- Remove some of the "old" naming including the "cli" directory at the root of the code.
- Organize the files properly. There are several "common" files that are not in the "common" folder for example.
- Some files would not needed by hostfxr.dll with a bit of #ifdef work. For example, deps_entry.cpp and deps_format.cpp

**Comment by elinor-fung** [comment]
A lot of refactoring, splitting, and renaming has been done since this was opened, largely covering examples called out here. I'm going to close this issue. If we have additional targeted improvements, we can create new issues.
