### ISSUE TITLE
Tasks.Dataflow - Aggregation Block and Rendezvous Block

### ISSUE THREAD

**Issue by abbotware** [dotnet/runtime#31531]
I have a few use cases where a pipeline chain depends on certain conditions before the pipeline can proceed.

**Aggregation** - C runs with a single input - an aggregation of B once B receives a complete notification.

`A-> B(sum) ->  C`

**Rendezvous** (barrier) - D runs only when B and C are set to complete
```
A->  B ->   D
     C -> 
```

In both cases, I can wire up the the behavior using the exposed Completion  Task.   However, this is outside the dataflow block functionality and seems to be mixing and matching different technologies (TPL and Dataflow).

I would prefer to create a Block which can inserted into the pipeline using the **LinkTo** methods so an entire chain can be represented as blocks.

The two block types I have listed above seem to be missing (by design possibly).  I have thought that perhaps a clever use of the join+ broadcast blocks could be used instead, but that seems to misrepresent the intent.

I am attempting to make an AggregationBlock<TInput, TOutput> (similar to a TransformBlock) - one that has an Action<Input> for all inputs..   Upon receiving a complete event, it will call Func<output> a single time to publish to the next block in in the pipeline.

The problem I am having is implementing my own ISourceBlock<TOutput> - if I use TransformBlock as an example. the block uses (SourceCore<TOutput>) which are only internal.  TransformBlock is also Sealed so i can't just extend it

**SourceCore** seems to be the one class I need to implement ISourceBlock<T> which has the **LinkTo** method I want.  (I know i can just implement the interface on my own, but I would prefer re-use existing code)

So a few questions:
Were these types of blocks intentionally left out?
Is there any reason why the existing blocks are sealed (Action / Transform)? 
Is there any reason why the high level objects such as SourceCore is not exposed?

**Comment by stephentoub** [comment]
Thanks for the suggestion.  This is sufficiently niche that we're unlikely to add them to the dataflow library itself.  It's great that you published your own implementation, such that others can find and use it if they also have a similar need.  I'm going to close this for now; we've not heard of others asking for similar things, but if we do in the future, we can always reopen this.

**Comment by abbotware** [comment]
@stephentoub - my 'ask' is/was to unseal / make non-internal the classes I mentioned (not necessarily add these to the library). That way the blocks I created would be able to behave more like existing blocks with regard to the LinkTo functionality.   Is there any reason why that can't be done?

**Comment by stephentoub** [comment]
Making internal types public is akin to designing / shipping brand new public surface area.  That's a significant design effort and isn't something we just do.  Same with unsealing: the blocks implement a bunch of interfaces and weren't designed / vetted with the possibility of other types changing the functionality of those methods.

**Comment by abbotware** [comment]
Well, if you plan to make this library easier to extend, I suggest exposing SourceCore at a minimum.   I can get to it now with reflection... but, I know that is asking for trouble  :-P
