### ISSUE TITLE
EventLog GetEventsLog is very very very poorly implemented

### ISSUE THREAD

**Issue by ocean2706** [dotnet/runtime#31543]
In real life, EventLog.GetEventsLog() is far away from being ready to use in order to acces local (or remote) computer events in a way similar to Event Viewer. If you try to use the provided sample code in current documentation (2019-06-12), it will fail with System.InvalidOperationException , {"Cannot open log Parameters on machine .. Windows has not provided an error code."}
 
This is because, according to reference page https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/EventLog.cs,4d9fa3c597ae17eb it use
private const string EventLogKey = "SYSTEM\\CurrentControlSet\\Services\\EventLog"; in order to list subkeys on corresponding HKLM registry, wich contain of course EventLog service parameters and of course the key does not conatain anything suitable for a log. At least in Windows 10.

As a workaround, you can try to use WMI (https://docs.microsoft.com/en-us/windows/desktop/wmisdk/wmi-tasks--event-logs) - not sure about the outcome,  or read logs from C:\Windows\System32\winevt\Logs where you can find them in .evtx fromat.

**Comment by Anipik** [comment]
>  it will fail with System.InvalidOperationException , {"Cannot open log Parameters on machine .. Windows has not provided an error code.

This has been fixed in master as well as in 3.1
