### ISSUE TITLE
API proposal: expose System.Text.Encoding.Latin1 getter publicly

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#31549]
The ISO-8859-1 encoding is used somewhat commonly in web scenarios since it's the encoding normally specified for headers. We should consider having a fast-access property for this encoding just like we have for `Encoding.UTF8`.

The workaround for now is to use `Encoding.GetEncoding("iso-8859-1", ...)`, which works but is not convenient or optimized.

### API Proposal

```cs
namespace System.Text
{
    public class Encoding
    {
        /* NEW static propery getter */
        public static Encoding Latin1 { get; }
    }
}
```

The return value of this would be equivalent to calling `Encoding.GetEncoding("iso-8859-1")`. The `byte` to `char` conversion is a naive widening operation. The `char` to `byte` conversion is a naive narrowing operation, with any `char` values above `0x007F` being best-fit mapped to an ASCII byte. If a best-fit mapping is unavailable then the character is converted to `(byte)'?'`.

If the developer wishes to change the fallback behavior or to enable best fit mapping, they can call `Encoding.GetEncoding("iso-8859-1", ...)` and pass custom fallback behaviors as needed for the newly-created instance.

This proposal __does not__ intend on making the existing internal `Latin1Encoding` class public.

/cc @davidfowl

**Comment by GrabYourPitchforks** [comment]
I updated the proposal to perform best-fit mapping during the narrowing conversion. This provides compatibility with the existing `Latin1Encoding` default behaviors.

**Comment by terrajobst** [comment]
* Looks good.
* We won't be exposing the `Latin1Encoding` type, because it's not necessary

```C#
namespace System.Text
{
    public partial class Encoding
    {
        public static Encoding Latin1 => Encoding.GetEncoding("iso-8859-1");
    }
}
```
