### ISSUE TITLE
Blazor - Add JsonSerializerOptions as parameter to HttpClient.GetJsonAsync<T>  

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/runtime#31551]
_From @GoranHalvarsson on Sunday, June 16, 2019 7:49:28 PM_

I suggest you add JsonSerializerOptions as a parameter(could be optional) to the HttpClient.GetJsonAsync<T> method. For the deserialization of json you are using `JsonSerializer.Parse<T>(await httpClient.GetStringAsync(requestUri), JsonSerializerOptionsProvider.Options)`. 

The  parameter `JsonSerializerOptionsProvider.Options`  should be accessible.

This should probably be added to all extension methods in `Microsoft.AspNetCore.Components.HttpClientJsonExtensions`

_Copied from original issue: aspnet/AspNetCore#11266_

**Comment by Jozkee** [comment]
Fixed on https://github.com/dotnet/runtime/pull/33459.

> The parameter JsonSerializerOptionsProvider.Options should be accessible.

This will be tracked on https://github.com/dotnet/runtime/issues/34626
