### ISSUE TITLE
X509Chain NotSignatureValid error on Linux with .NET Core 3.0+

### ISSUE THREAD

**Issue by mattw-db** [dotnet/runtime#31569]
Hello,

We're having issues with X509 cert chain validation after retargeting our Linux application to netcoreapp3.0.  The chain in three deep: we have a self-signed root CA, which has signed a domain level CA, which in turn has signed a server (non-CA) cert.

When validating the chain, we're met with a X509ChainStatusFlags.NotSignatureValid error carrying a "certificate signature failure" StatusInformation string.  The error appears to originate from openssl, but the native code responsible for bubbling this up to the managed world seems to be new (or at least heavily reworked) for .NET Core 3.0 and largely introduced by this pull request: https://github.com/dotnet/corefx/pull/35801

The issue occurs only on Linux (both x64 and ARM), not Windows.  It is seen with both .NET Core 3.0 and 3.1, but not with 2.2, 2.1, or 2.0.  I've also tested with both openssl 1.1.1 and 1.0.2 libs and it's seen with both.

I've validated the chain on the command line with both the openssl and GnuTLS certtool command (in the same Linux environments) and both show no errors.

The attached project (with a junk cert chain formed similarly to our own) should reproduce the issue easily.  On Windows (or Linux with .NET Core 2.x) it's output with be "Chain Valid".  On Linux with .NET Core 3.0/3.1, it'll print "Chain Invalid: NotSignatureValid: certificate signature failure"

[CertChainValidateTest.zip](https://github.com/dotnet/corefx/files/3899088/CertChainValidateTest.zip)

The following openssl command can be used to validate the chain:
```
$ openssl verify -CAfile root-ca.crt -untrusted domain-ca.crt server.crt 
server.crt: OK
```

Let me know if there's anything else I can provide or should check.

Thanks a lot!

Matt

Edit: updated zip with fixed example cert chain

**Comment by bartonjs** [comment]
I'm not sure that there's a good place to add documentation for this, and it requires a number of CA best practices to be violated (namely, it's reusing CNs and not using AKID).  If there seems to be a general usage problem then we can figure out where to document ... something :smile:.
