### ISSUE TITLE
Ubuntu .NET Core 3.1 runtime issue

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#31604]
I have successfully built .NET Core 3.1 from "https://github.com/dotnet/corefx/tree/release/3.1" on Ubuntu 18.04. I have also changed the System.Data.Odbc to make it work for Informix database. I have also changed Interop.Odbc.cs and Interop.Libraries.cs file appropriately for Linux to look for Informix ODBC shared object (.so). 

However, when I run simple .NET Core C# example to connect to Informix database it reports exception. Exception is very strange, as soon as it calls OdbcEnvironmentHandle() constructor ( ), which internally calls Interop.Odbc.SQLAllocHandle(<arguments>), it throws exception. It appears that it was unable to load the Informix ODBC shared object which is mentioned in the Interop.Libraries.cs file. LD_LIBRARY_PATH and other variables are set correctly, simple Informix ODBC application works in the same environment. I don't have unixODBC Driver Manager setup.

Is there any specific setup needed to load the dependent shared objects (which are natively written in C/C++ code) at runtime for .NET Core 3.1? Does unixODBC's "libodbc.so" is mandatory to be used?

Any help in this regard would be greatly appreciated.

**Comment by jkotas** [comment]
I believe that this was resolved in https://github.com/dotnet/runtime/issues/1215
