### ISSUE TITLE
System.CodeDom - Generic Method Adds 1 Blank Line per Type Parameter in Rendered Source

### ISSUE THREAD

**Issue by alistairjevans** [dotnet/runtime#31614]
**SDK Version**: 3.1.100

I believe I may have found a bug in either the CSharp ``CodeDomProvider``, or possibly the ``IndentedTextWriter``.

The bug is that when you define a generic method with type parameters in the CodeDom, and render to source code, the resulting source code has an extra blank line after the method start and before the opening brace of the method body, 1 for each type parameter that has been added.

I have a reproduction program, here:

```csharp
using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Linq;

class Program
{
    static void Main()
    {
        var codeCompileUnit = new CodeCompileUnit();

        var myNamespace = new CodeNamespace("MyNameSpace");
        codeCompileUnit.Namespaces.Add(myNamespace);

        var classDecl = new CodeTypeDeclaration("MyClass");
        classDecl.Attributes = MemberAttributes.Public;

        myNamespace.Types.Add(classDecl);

        var codeDom = CodeDomProvider.CreateProvider("CSharp");

        for(int numParams = 0; numParams < 6; numParams++)
        {
            var method = new CodeMemberMethod();
            method.Name = "MyMethod";
            method.TypeParameters.AddRange(Enumerable.Range(1, numParams)
                                            .Select(i => new CodeTypeParameter("T" + i))
                                            .ToArray());
            classDecl.Members.Add(method);
        }

        var tw = new IndentedTextWriter(Console.Out, "    ");
        // Generate source code using the code generator.
        codeDom.GenerateCodeFromCompileUnit(codeCompileUnit, tw, new CodeGeneratorOptions
        {
            BlankLinesBetweenMembers = true,
            BracingStyle = "C"
        });
    }
}
```

This yields the following output:
```
namespace MyNameSpace
{


    public class MyClass
    {

        private void MyMethod()
        {
        }

        private void MyMethod<T1>()

        {
        }

        private void MyMethod<T1, T2>()


        {
        }

        private void MyMethod<T1, T2, T3>()



        {
        }

        private void MyMethod<T1, T2, T3, T4>()




        {
        }

        private void MyMethod<T1, T2, T3, T4, T5>()





        {
        }
    }
}
```

It doesn't appear that the ``BracingStyle`` or ``BlankLinesBetweenMembers`` configuration settings have any effect on the behaviour.

**Comment by danmosemsft** [comment]
@alistairjevans thanks for reporting. This is fairly low impact so it might be a while before it gets looked at. Any interest in debugging or offering a PR?

**Comment by alistairjevans** [comment]
Yes, I can probably take a look; I'll post back here once I've got more info.

**Comment by alistairjevans** [comment]
Just to update; I've tracked down the problem. In the method ``CSharpCodeGenerator.OutputTypeParameterConstraints``, for every type parameter in the method, a line is added to contain the type constraint for that parameter, even if there are no type constraints. 

So the fix is to only write that line if a constraint actually needs to be rendered.

I'll get a PR together.
