### ISSUE TITLE
System.Text.Json: JsonStringEnumConverter ignores its JsonNamingPolicy during deserialization.

### ISSUE THREAD

**Issue by dbc2** [dotnet/runtime#31619]
In `System.Text.Json` in .Net Core 3.1, I can serialize an enum using a naming policy, however when I attempt to deserialize the same enum with a naming policy, the policy is ignored and an exception is thrown when the naming policy does anything beyond modifying the case of the enum value names.  

The issue can be reproduced as follows.  Define the following simple snake case naming policy:

```
public class SnakeCaseNamingPolicy : JsonNamingPolicy
{
    public override string ConvertName(string name)
    {
        return string.Concat(name.Select((x, i) => i > 0 && char.IsUpper(x) ? "_" + Char.ToLowerInvariant(x).ToString() : Char.ToLowerInvariant(x).ToString()));
    }
}
```

And the following enum:

```
public enum TestEnum
{
    ValueZero,
    ValueOne,
    ValueTwo,
    ValueThree
}
```

Then attempting to round-trip values of `TestEnum` will fail during deserialization:

```
var values = (TestEnum [])Enum.GetValues(typeof(TestEnum));

var options = new JsonSerializerOptions
{
    Converters = { new JsonStringEnumConverter(new SnakeCaseNamingPolicy()) },
    WriteIndented = true,
};

var json = JsonSerializer.Serialize(values, options);

Console.WriteLine("Serialized {0}:", values);
Console.WriteLine(json);

var valuesIn = JsonSerializer.Deserialize<TestEnum []>(json, options); // Exception thrown here!

Assert.IsTrue(valuesIn.SequenceEqual(values));
```			

The enum values are serialized with the naming policy successfully:

```
[
  "value_zero",
  "value_one",
  "value_two",
  "value_three"
]
```

But deserialization throws this exception:
```
Failed with unhandled exception: 
System.Text.Json.JsonException: The JSON value could not be converted to TestEnum[]. Path: $[0] | LineNumber: 1 | BytePositionInLine: 14.
   at System.Text.Json.ThrowHelper.ThrowJsonException()
   at System.Text.Json.Serialization.Converters.JsonConverterEnum`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

The problem seems to be that [`JsonConverterEnum<T>.Read()`](https://github.com/dotnet/runtime/blob/316a82fdcebb3bc025b3a5d056b751b29c1c3296/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterEnum.cs#L47) completely ignores the specified `_namingPolicy` and simply calls `Enum.TryParse()`:

                // Try parsing case sensitive first
                string? enumString = reader.GetString();
                if (!Enum.TryParse(enumString, out T value)
                    && !Enum.TryParse(enumString, ignoreCase: true, out value))
                {
                    ThrowHelper.ThrowJsonException();
                    return default;
                }
                return value;

A close reading of the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=netcore-3.1#remarks) seems to imply that this is an intended limitation:

 > Reading is case insensitive. Writing can be customized by using a JsonNamingPolicy.

However the inconsistency and inability to round-trip with the same settings is an odd and unexpected restriction.  Newtonsoft does not have this limitation -- it can round-trip enum values even when using `SnakeCaseNamingStrategy`.

Demo fiddle [here](https://dotnetfiddle.net/KDSSGb) showing that Json.NET can round-trip enums using `SnakeCaseNamingStrategy` while System.Text.Json cannot do so with `SnakeCaseNamingPolicy`.

**Comment by NoneGiven** [comment]
This is a bug. Since the doc and the implementation were both written before the snake case naming policy was invented, seems like the assumption was that regardless of naming policy, a case-insensitive `Enum.TryPase` would cover all possibilities.

#1197 is related in that it concerns sloppy assumption made about naming policy in these predefined converters. Hopefully 5.0 can take a pass at fixing all of these without getting bogged down in unnecessary fear of breaking changes...

**Comment by NoneGiven** [comment]
#1197 is related in that it concerns questionable assumptions about naming policy made by these predefined converters. Of note, if #782 (which is `api-approved`) is implemented, then this issue will become a bug when using a built-in naming policy rather than just a custom one.

**Comment by CodeBlanch** [comment]
Anyone looking for a workaround I have a JsonConverter named JsonStringEnumMemberConverter in [Macross.Json.Extensions](https://www.nuget.org/packages/Macross.Json.Extensions/) package which fixes this issue and then adds in support for EnumMemberAttribute & Nullable enums. A modified version of https://github.com/dotnet/corefx/pull/41648, basically.

**Comment by Bukran** [comment]
> JsonStringEnumMemberConverter

Thanks a lot! I was stumbling against deserialization.

**Comment by Macromullet** [comment]
I don't see how this can be addressed with the current API shape, as JsonNamingPolicy.ConvertName is potentially a one-way function. For instance, if you chose HashFunction(name) as the implementation, it's not possible to convert it back. The only way to support this would be to define something like WPF does with converters, where you have Convert and ConvertBack, but that seems to be functionality outside the scope of what System.Text.Json should do.

**Comment by layomia** [comment]
from @liul in https://github.com/dotnet/runtime/issues/41138:

> https://github.com/dotnet/runtime/blob/a5b491cb64475563597d837a6ec3a6b8b353175b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L317
> 
> Use the obtained string value directly here. But why not use _namingPolicy'?
> 
> like:
> 
> ```cs
>         internal override T ReadWithQuotes(ref Utf8JsonReader reader)
>         {
>             string? enumString = reader.GetString();
>             
>             var v =  _namingPolicy == null ? enumString : FormatEnumValueToString(enumString, encoder);
>              
>             // Try parsing case sensitive first
>             if (!Enum.TryParse(v, out T value)
>                 && !Enum.TryParse(v, ignoreCase: true, out value))
>             {
>                 ThrowHelper.ThrowJsonException();
>             }
> 
>             return value;
>         }
> ```

**Comment by 2m0nd** [comment]
Maybe add two parameters of type JsonNamingPolicy, first use when write json and second use when reading json?
JsonStringEnumConverter(writeNamePolicy: new SnakeCaseNamingPolicy(), readNamePolicy: new CamelCaseNamingPolicy())

**Comment by avonheimburg** [comment]
> I don't see how this can be addressed with the current API shape, as JsonNamingPolicy.ConvertName is potentially a one-way function. For instance, if you chose HashFunction(name) as the implementation, it's not possible to convert it back.

For enums, you could actually convert back even with a one-way function. You would need to convert all possible enum values to their serialized form using JsonNamingPolicy.ConvertName and could then simply look up the value you want to deserialize. The only limitation is that the naming policy actually assigns distinct names to all enum values.

**Comment by layomia** [comment]
Triage: per my comments in https://github.com/dotnet/runtime/pull/42302#pullrequestreview-674544699 I do not believe this feature is feasible. We'll close this issue.

As a workaround, users can write custom converters for enums that can support a close set of naming-policy-transformed enum names and honor them on deserialization. @tdykstra let's consider providing an example in the JSON docs.

**Comment by tdykstra** [comment]
> let's consider providing an example in the JSON docs

If you can point me to sample converter code, I'll add it to the Converters or Newtonsoft article.

**Comment by layomia** [comment]
@tdykstra @AlgorithmsAreCool here's some [sample](https://dotnetfiddle.net/GD9rBz) converter code to support this feature. Please let me know if you have any questions about it. It has the following behavior:

- Supports (de)serialization and serialization of arbitrary enum types using size-limited caches initialized with enum values transformed to their desired string representations (specified by naming policy & encoder).
- If the limit isn't exceeded, adds flag values to the caches on serialization which can be used during deserialization.
    - Provides a mechanism to specify known flag enum values that should be supported on deserialization, even when serialization of the values does not occur first.

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

public class Program
{
    public static void Main()
    {
        JsonSerializerOptions options = new() { Converters = { new CustomEnumConverterFactory() } };

        // If serialization happens first then we likely can support arbitrary values and flag combinations for this closed set of enums.
        SerializeThenDeserialize(DayOfWeek.Monday);
        SerializeThenDeserialize(BindingFlags.Instance | BindingFlags.Public);

        // Deserialize a "known" enum value without serializing first.
        BindingFlags value = JsonSerializer.Deserialize<BindingFlags>(@"""declaredOnly, createInstance""", options);
        Console.WriteLine(value);

        // Deserialize an "unknown" enum value without serializing first. Recall Enum.ToString() has specific and deterministic ordering for flags.
        try
        {
            JsonSerializer.Deserialize<BindingFlags>(@"""createInstance, declaredOnly""", options);
        }
        catch (JsonException) { }

        void SerializeThenDeserialize(object enumVal)
        {
            string json = JsonSerializer.Serialize(enumVal, options);
            Console.WriteLine(json);

            enumVal = JsonSerializer.Deserialize(json, enumVal.GetType(), options)!;
            Console.WriteLine(enumVal);
        }
    }

    private sealed class CustomEnumConverterFactory : JsonConverterFactory
    {
        public override bool CanConvert(Type typeToConvert) => typeToConvert.IsEnum;

        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        {
            object[]? knownValues = null;

            if (typeToConvert == typeof(BindingFlags))
            {
                knownValues = new object[] { BindingFlags.CreateInstance | BindingFlags.DeclaredOnly };
            }

            return (JsonConverter)Activator.CreateInstance(
                typeof(CustomEnumConverter<>).MakeGenericType(typeToConvert),
                BindingFlags.Instance | BindingFlags.Public,
                binder: null,
                args: new object?[] { JsonNamingPolicy.CamelCase, options, knownValues },
                culture: null)!;
        }
    }

    private sealed class CustomEnumConverter<T> : JsonConverter<T> where T : Enum
    {
        private readonly JsonNamingPolicy _namingPolicy;

        private readonly Dictionary<string, T> _readCache = new();
        private readonly Dictionary<T, JsonEncodedText> _writeCache = new();

        // This converter will only support up to 64 enum values (including flags) on serialization and deserialization
        private const int NameCacheLimit = 64;

        private const string ValueSeparator = ", ";

        public CustomEnumConverter(JsonNamingPolicy namingPolicy, JsonSerializerOptions options, object[]? knownValues)
        {
            _namingPolicy = namingPolicy;

            for (int i = 0; i < knownValues?.Length; i++)
            {
                if (!TryProcessValue((T)knownValues[i]))
                {
                    break;
                }
            }

            Array values = Enum.GetValues(typeof(T));

            for (int i = 0; i < values.Length; i++)
            {
                T value = (T)values.GetValue(i)!;

                if (!TryProcessValue(value))
                {
                    break;
                }
            }

            bool TryProcessValue(T value)
            {
                if (_readCache.Count == NameCacheLimit)
                {
                    Debug.Assert(_writeCache.Count == NameCacheLimit);
                    return false;
                }

                FormatAndAddToCaches(value, options.Encoder);
                return true;
            }
        }

        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? json;

            if (reader.TokenType != JsonTokenType.String || (json = reader.GetString()) == null || !_readCache.TryGetValue(json, out T value))
            {
                throw new JsonException();
            }

            return value;
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            if (!_writeCache.TryGetValue(value, out JsonEncodedText formatted))
            {
                if (_writeCache.Count == NameCacheLimit)
                {
                    Debug.Assert(_readCache.Count == NameCacheLimit);
                    throw new ArgumentOutOfRangeException();
                }

                formatted = FormatAndAddToCaches(value, options.Encoder);
            }

            writer.WriteStringValue(formatted);
        }

        private JsonEncodedText FormatAndAddToCaches(T value, JavaScriptEncoder? encoder)
        {
            (string valueFormattedToStr, JsonEncodedText valueEncoded) = FormatEnumValue(value.ToString(), _namingPolicy, encoder);
            _readCache[valueFormattedToStr] = value;
            _writeCache[value] = valueEncoded;
            return valueEncoded;
        }

        private ValueTuple<string, JsonEncodedText> FormatEnumValue(string value, JsonNamingPolicy namingPolicy, JavaScriptEncoder? encoder)
        {
            string converted;

            if (!value.Contains(ValueSeparator))
            {
                converted = namingPolicy.ConvertName(value);
            }
            else
            {
                // todo: optimize implementation here by leveraging https://github.com/dotnet/runtime/issues/934.
                string[] enumValues = value.Split(ValueSeparator);

                for (int i = 0; i < enumValues.Length; i++)
                {
                    enumValues[i] = namingPolicy.ConvertName(enumValues[i]);
                }

                converted = string.Join(ValueSeparator, enumValues);
            }

            return (converted, JsonEncodedText.Encode(converted, encoder));
        }
    }
}
```

**Comment by layomia** [comment]
From @AlgorithmsAreCool in https://github.com/dotnet/runtime/issues/56258:

> # Excessively Negative Foreword
> Hello folks,
> I wasn't going to bother filing this issue, but after seeing [this blog post](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/) showing significant investment in space age source-generator tech at the presumed expense of long standing and more (subjectively) fundamental issues such as #782 (which just fell off the .NET 6 release wagon) I am compelled to provide feedback on actual usability problems with STJ.
> 
> I intentionally held off on trying to adopt STJ for over 2 years because I kept reading about limitations, but it seems even now I can't use it for a pretty basic REST API integration without writing multiple custom converters to handle common patterns such as snake case along side string enum representations. Writing a custom naming policy isn't hard, but when it doesn't work with the other built-in components such as JsonStringEnumConverter, it has only created a 2nd problem for me to solve.
> 
> The worst part about this is I spent time debugging and reading docs and code trying to understand what I was doing wrong. I just wasn't expecting it to work fine for serialization but not for deserialization. I've run into other unexpected gaps that were less painful, but still disappointing. Admittedly part of this pain was caused because I am writing the code in F# which has it's own friction with the C# biased ecosystem, but **deserisalizing an enum from a string is not an F# specific problem.** [The docs are somewhere between misleading and flat-out incorrect](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-customize-properties#enums-as-strings). Note the last example that directly specifies the naming policy for deserialization when it will not be respected. That is setting the user up for confusion and disappointment.
> 
> # Actual Issue Description
> I am resubmitting this issue as a dupe of #31619 and #41138. Those were closed and locked so I cannot comment there.
> 
> The previous closure stems from [this comment](https://github.com/dotnet/runtime/pull/42302#pullrequestreview-674544699) partially copied below (emphasize mine).
> 
> > ... We are trying to map the result of a naming policy conversion back to enum property values. On the surface, this is no different from what we do when deserializing object properties using JsonSerializerOptions.PropertyNamingPolicy.
> > **The complication here is with flag combination values. We cannot cache all possible transformed enum property name values, of which there could be several, opening the door to security vulnerabilities (#36726 (comment)).** ...
> 
> ### My concrete ask here is either:
> A) Could we simply exclude [Flags] enums from the deserialization handling for now? My gut tells me the vast majority of enum deserializations in the wild will not use [Flags] and will simply be 1-1 enum mappings.
> 
> B) If [Flags] support MUST be included for consistency, could we use limit the cache size and allow a perf penalty for cache misses?
> 
> I hope it is not too late in the release cycle to get this into .NET 6.

**Comment by layomia** [comment]
> B) If [Flags] support MUST be included for consistency, could we use limit the cache size and allow a perf penalty for cache misses?

Yes we would need to include flags for consistency and to avoid confusion. I do not believe the perf penalty will be acceptable. However, I do not have perf numbers using a concrete implementation to quantify exactly how bad the penalty could be, and whether we could inadvertently facilitate denial of service attacks from bad actors who can generate several payloads with flag combinations that cannot be cached. I'll reopen this issue for the future in case any one wishes to do some perf measurements.

**Comment by layomia** [comment]
@tdykstra @AlgorithmsAreCool here's a workaround for this feature using custom converters. It has the following behavior:

- Supports serialization and deserialization of arbitrary enum types according to a specified naming policy and encoder, using size-limited caches to specify a range of supported enum values.
- Assuming cache-size limits haven't been met, dynamically adds transformed enum string representations to the caches on serialization which can also be used on deserialization (this is mostly useful for flags).
    - Also provides a mechanism to specify "known" enum flag values which can be used for deserialization even when serialization has not occurred.

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

public class Program
{
    public static void Main()
    {
        JsonSerializerOptions options = new() { Converters = { new CustomEnumConverterFactory() } };

        // If serialization happens first then we likely can support arbitrary values and flag combinations for this closed set of enums.
        SerializeThenDeserialize(DayOfWeek.Monday);
        SerializeThenDeserialize(BindingFlags.Instance | BindingFlags.Public);

        // Deserialize a "known" enum value without serializing first.
        BindingFlags value = JsonSerializer.Deserialize<BindingFlags>(@"""declaredOnly, createInstance""", options);
        Console.WriteLine(value);

        // Deserialize an "unknown" enum value without serializing first. Recall Enum.ToString() has specific and deterministic ordering for flags.
        try
        {
            JsonSerializer.Deserialize<BindingFlags>(@"""createInstance, declaredOnly""", options);
        }
        catch (JsonException) { }

        void SerializeThenDeserialize(object enumVal)
        {
            string json = JsonSerializer.Serialize(enumVal, options);
            Console.WriteLine(json);

            enumVal = JsonSerializer.Deserialize(json, enumVal.GetType(), options)!;
            Console.WriteLine(enumVal);
        }
    }

    private sealed class CustomEnumConverterFactory : JsonConverterFactory
    {
        public override bool CanConvert(Type typeToConvert) => typeToConvert.IsEnum;

        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        {
            object[]? knownValues = null;

            if (typeToConvert == typeof(BindingFlags))
            {
                knownValues = new object[] { BindingFlags.CreateInstance | BindingFlags.DeclaredOnly };
            }

            return (JsonConverter)Activator.CreateInstance(
                typeof(CustomEnumConverter<>).MakeGenericType(typeToConvert),
                BindingFlags.Instance | BindingFlags.Public,
                binder: null,
                args: new object?[] { JsonNamingPolicy.CamelCase, options, knownValues },
                culture: null)!;
        }
    }

    private sealed class CustomEnumConverter<T> : JsonConverter<T> where T : Enum
    {
        private readonly JsonNamingPolicy _namingPolicy;

        private readonly Dictionary<string, T> _readCache = new();
        private readonly Dictionary<T, JsonEncodedText> _writeCache = new();

        // This converter will only support up to 64 enum values (including flags) on serialization and deserialization
        private const int NameCacheLimit = 64;

        private const string ValueSeparator = ", ";

        public CustomEnumConverter(JsonNamingPolicy namingPolicy, JsonSerializerOptions options, object[]? knownValues)
        {
            _namingPolicy = namingPolicy;

            bool continueProcessing = true;
            for (int i = 0; i < knownValues?.Length; i++)
            {
                if (!TryProcessValue((T)knownValues[i]))
                {
                    continueProcessing = false;
                    break;
                }
            }

            if (continueProcessing)
            {
                Array values = Enum.GetValues(typeof(T));

                for (int i = 0; i < values.Length; i++)
                {
                    T value = (T)values.GetValue(i)!;

                    if (!TryProcessValue(value))
                    {
                        break;
                    }
                }
            }

            bool TryProcessValue(T value)
            {
                if (_readCache.Count == NameCacheLimit)
                {
                    Debug.Assert(_writeCache.Count == NameCacheLimit);
                    return false;
                }

                FormatAndAddToCaches(value, options.Encoder);
                return true;
            }
        }

        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? json;

            if (reader.TokenType != JsonTokenType.String || (json = reader.GetString()) == null || !_readCache.TryGetValue(json, out T value))
            {
                throw new JsonException();
            }

            return value;
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            if (!_writeCache.TryGetValue(value, out JsonEncodedText formatted))
            {
                if (_writeCache.Count == NameCacheLimit)
                {
                    Debug.Assert(_readCache.Count == NameCacheLimit);
                    throw new ArgumentOutOfRangeException();
                }

                formatted = FormatAndAddToCaches(value, options.Encoder);
            }

            writer.WriteStringValue(formatted);
        }

        private JsonEncodedText FormatAndAddToCaches(T value, JavaScriptEncoder? encoder)
        {
            (string valueFormattedToStr, JsonEncodedText valueEncoded) = FormatEnumValue(value.ToString(), _namingPolicy, encoder);
            _readCache[valueFormattedToStr] = value;
            _writeCache[value] = valueEncoded;
            return valueEncoded;
        }

        private ValueTuple<string, JsonEncodedText> FormatEnumValue(string value, JsonNamingPolicy namingPolicy, JavaScriptEncoder? encoder)
        {
            string converted;

            if (!value.Contains(ValueSeparator))
            {
                converted = namingPolicy.ConvertName(value);
            }
            else
            {
                // todo: optimize implementation here by leveraging https://github.com/dotnet/runtime/issues/934.
                string[] enumValues = value.Split(ValueSeparator);

                for (int i = 0; i < enumValues.Length; i++)
                {
                    enumValues[i] = namingPolicy.ConvertName(enumValues[i]);
                }

                converted = string.Join(ValueSeparator, enumValues);
            }

            return (converted, JsonEncodedText.Encode(converted, encoder));
        }
    }
}
```

**Comment by AlgorithmsAreCool** [comment]
@layomia Thank You! I'm going to study this a bit

**Comment by AlgorithmsAreCool** [comment]
> Yes we would need to include flags for consistency and to avoid confusion. I do not believe the perf penalty will be acceptable.


Although I realize there are no good answers, I personally think the current solution of ignoring the naming convention for deserialization is more harmful and confusing than poor/missing Flags support.
My rationale is that [Flags] usage is significantly less common than

Again without numbers to back me up, I would expect it is relatively rare for a web APIs to use Flags encoding. That being said, I realize people are using STJ to store and retrieve locally generated data that might need Flags more commonly. 

Perhaps a compromise, provide Flags support with the performance fallback, but hidden behind a experimental/preview environment variable until a better solution can be found?

**Comment by AlgorithmsAreCool** [comment]
> Yes we would need to include flags for consistency and to avoid confusion. I do not believe the perf penalty will be acceptable.

Although I realize there are no good answers, I personally think the current solution of ignoring the naming convention for deserialization is more harmful and confusing than poor/missing Flags support.

Again without numbers to back me up, I would expect it is relatively rare for a web APIs to use Flags encoding. That being said, I realize people are using STJ to store and retrieve locally generated data that might need Flags more commonly.

Perhaps a compromise, provide Flags support with the performance fallback, but hidden behind a experimental/preview environment variable until a better solution can be found?

Also, perhaps the limited space cache can be improved by switching to a simple LRU style cache that will avoid a performance "cliff" when the cache overflows. This might amortize the pain somewhat

**Comment by tdykstra** [comment]
If I run the Main method of the sample and instead of using the custom converter I use the  built-in JsonStringEnumConverter with JsonNamingPolicy.CamelCase, everything works correctly.  What am I missing that the custom converter is required for?

```
using System;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace EnumConverter
{
    public class Program
    {
        public static void Main()
        {
            JsonSerializerOptions options = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) } };

            // If serialization happens first then we likely can support arbitrary values and flag combinations.
            SerializeThenDeserialize(DayOfWeek.Monday);
            SerializeThenDeserialize(BindingFlags.Instance | BindingFlags.Public);

            // Deserialize a "known" enum value without serializing first.
            BindingFlags value = JsonSerializer.Deserialize<BindingFlags>(@"""declaredOnly, createInstance""", options);
            Console.WriteLine(value);

            // Deserialize an "unknown" enum value without serializing first. Recall Enum.ToString() has specific and deterministic ordering for flags.
            try
            {
                JsonSerializer.Deserialize<BindingFlags>(@"""createInstance, declaredOnly""", options);
            }
            catch (JsonException) { }

            void SerializeThenDeserialize(object enumVal)
            {
                string json = JsonSerializer.Serialize(enumVal, options);
                Console.WriteLine(json);

                enumVal = JsonSerializer.Deserialize(json, enumVal.GetType(), options)!;
                Console.WriteLine(enumVal);
            }
        }
    }
}
```

**Comment by layomia** [comment]
@tdykstra I think it's working because we have logic trying case-insensitive matching for enum string values, which works well with PascalCase -> camelCase transformations. Can you try your repro using a policy such as snake_case - https://github.com/dotnet/runtime/blob/66ca4741f543306f0b6138b17dc39baf05bfdd4c/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.cs#L1887-L1893?

**Comment by tdykstra** [comment]
That explains it, thanks! Snake case test cases work only with the custom converter. I'll update the docs.

**Comment by AlgorithmsAreCool** [comment]
@layomia I am assuming there is a 0% chance of a fix for this making it into .NET 6. Is that assumption correct?

**Comment by SabitKondakci** [comment]
> @layomia I am assuming there is a 0% chance of a fix for this making it into .NET 6. Is that assumption correct?

Will this feature be in .Net6 sooner or later?

**Comment by eiriktsarpalis** [comment]
> Will this feature be in .Net6 sooner or later?

We didn't get around to fixing this in time for .NET 6. It will be considered for .NET 7.

**Comment by brianlagunas** [comment]
I also need this functionality. Seems silly to me that a naming policy would only apply on serialization and not deserialization. Seems like a massive oversight.

Please fix this.
