### ISSUE TITLE
Receiving PlatformNotSupportedException when executing ProtectedData.Protect on Windows

### ISSUE THREAD

**Issue by bladelson** [dotnet/runtime#31617]
Hello, I am executing ProtectedData.Protect from a .Net Core 3.0 project on windows but I am receiving a `PlatformNotSupportedException`. I am consuming package System.Security.Cryptography.ProtectedData v4.7.

To my knowledge this should be supported - any insight would be greatly appreciated.

**Comment by vcsjones** [comment]
I am unable to reproduce this on netcoreapp3.0 using S.S.C.ProtectedData 4.7 on Windows 10 using the following:

```csharp
using System;
using System.Security.Cryptography;

class Program {
    static void Main(string[] args) {
        var data = new byte[10];
        var user = new byte[10];
        data.AsSpan().Fill(1);
        user.AsSpan().Fill(1);
        byte[] protect = ProtectedData.Protect(data, user, DataProtectionScope.CurrentUser);
        Console.WriteLine(BitConverter.ToString(protect));
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="4.7.0" />
  </ItemGroup>
</Project>
```

Can you perhaps share any additional steps to reproduce this, or information about your environment?

**Comment by bladelson** [comment]
Hello thank you for the response.

The encryption code is contained in a .net core 3.0 assembly that is ultimately turned into a NuGet package.

I'm able to directly consume the NuGet package from a console app and use DPAPI without error. However when this code is invoked from my business application it throws the `PlatformNotSupportedException`. This business app is in essence a SignalR hub built on .net core 3.0.

**Comment by Wraith2** [comment]
How is this app deployed/run? I'd guess you're using docker or another container which is running a non windows operating system on which data protection is not supported.

**Comment by bladelson** [comment]
I pulled down and compiled/ran the app locally and still receive the exception. The project targets .NET core 3.0 with an output type of Windows Application.

We're able to successfully consume some other windows only libraries (namely word interop dlls), it's just the DPAPI stuff that is failing when executed by this app.

**Comment by GrabYourPitchforks** [comment]
Can you provide please the full stack trace of the exception you're seeing? That could help us determine exactly what DLLs are being loaded into the application.

**Comment by bladelson** [comment]
```
   at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Hyland.WordManager.Core.CryptoProvider.Encrypt(Byte[] bytes)
   at Hyland.HostServices.ComposerService.Core.ComposerService.<EditDocument>d__12.MoveNext() in M:\git\ccm-hostservices-contentcomposer\src\Hyland.HostServices.ComposerService.Core\ComposerService.cs:line 123
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Hyland.DesktopHost.Execution.CommandExecutor.<Execute>d__3.MoveNext() in M:\git\desktop-host\Hyland.DesktopHost\Execution\CommandExecutor.cs:line 42
```

Here's how the method is invoked

```C#


In the Debug | Modules window I see System.Security.Cryptography.ProtectedData.dll v4.700.19.56404

**Comment by bladelson** [comment]
Ahh i did not mean to close this issue 😭

**Comment by GrabYourPitchforks** [comment]
@bartonjs Looks like this user may have pulled down the "platform not supported" assembly somehow instead of using the in-box DLL. Something wrong with the package reference that might be causing this?

**Comment by bartonjs** [comment]
Maybe... but @vcsjones having success suggests that the package isn't utterly broken.

@bladelson Does your application say it's running on netcoreapp3.0 (or something newer, since 3.0 is out of support), or netstandard2.0?  (i.e. in the csproj snippet at https://github.com/dotnet/runtime/issues/31617#issuecomment-581066481 the `<OutputType>Exe</OutputType>` project is targeting netcoreapp3.0).

Alternatively, are you using something other than `dotnet restore` to resolve package dependencies and extract the libraries? Perhaps it's a tool that doesn't understand multi-RID packages?

**Comment by bladelson** [comment]
It is targeting netcoreapp3.0

```
<TargetFramework>netcoreapp3.0</TargetFramework>
<OutputType>WinExe</OutputType>
```

Have this working now when I add a direct reference to System.Security.Cryptography.ProtectedData on the parent application. However without this direct reference (just leaving it as a dependency of the nuget package) the error occurs.

Seems like for some reason our app is not loading the right version of this dll unless we have the explicit reference. Going to do some digging on our end into how our assemblies get loaded, I should be good now.

Thank you all for your assistance.

**Comment by vcsjones** [comment]
> or something newer, since 3.0 is out of support

@bartonjs 3.0 is still supported until early March I thought, yes? Perhaps you were thinking of 2.2?

@bladelson 

I tried this as a transitive package and still wasn't able to reproduce it, albeit without going through a nuget package. I can try next.

Which SDK is your project using and nuget package using? Is it using `<Project Sdk="Microsoft.NET.Sdk">` or something different? Also in the code sample I saw some dynamic... I wonder if the library is getting loaded via reflection and the wrong one is getting picked up?

**Comment by bartonjs** [comment]
> @bartonjs 3.0 is still supported until early March I thought, yes? Perhaps you were thinking of 2.2?

Right.  It just became February, not just became March.  ::whistles innocently::

**Comment by vcsjones** [comment]
> I can try [sic] next.

Using `ProtectedData` as a transitive dependency from a nuget package seems to work as well.

I don't suppose you are perhaps using WSL, or restored the project using WSL or on a non-Windows system before running it?

**Comment by bladelson** [comment]
@vcsjones The nuget package which contains crypto code is using `<Project Sdk="Microsoft.NET.Sdk">
`. The app which throws the exception when executing is using `<Project Sdk="Microsoft.NET.Sdk.Web">`

The library which contains the crypto code is indeed being loaded via reflection. It does seem like the wrong version of System.Security.Cryptography.ProtectedData - I can resolve this locally by directly referencing this from the main app

**Comment by sankalan** [comment]
Any update on this?

**Comment by vcsjones** [comment]
@sankalan though I tried several things, I haven't been able to reproduce this. Are you having the same issue? Are you able to provide any additional information to reproduce the `PlatformNotSupportedException` on Windows for `Protect`?

**Comment by sankalan** [comment]
Ok I shall try to give you a sample project.

**Comment by paramitamandal** [comment]
I am having similar problem with 2 dlls (attached the source codes here). The ConsoleApp Dll is loading ServiceApp Dll by reflection. In ServiceApp dll, I am just having one method to call ProtectedData.Protect(data, user, DataProtectionScope.CurrentUser).

[SampleApp.zip](https://github.com/dotnet/runtime/files/4634179/SampleApp.zip)

Scenario 1:
=================
When ProtectedData.dll is referenced in only ServiceApp dll, then there is a targetInvocationException with innerException as 'FileNotFoundException'

Scenario 2:
=================
When the packageReferences are present in both the dlls, then there is no error occurred.

My question is why do I need to have reference to ProtectedData Dll in ConsoleApp Dll although the reference is present in ServiceApp Dll. Is there anything else I am missing here? Can anyone please help in this regard?

**Comment by paramitamandal** [comment]
@vcsjones  @GrabYourPitchforks @jkotas  Any thoughts/insight on this?

**Comment by vcsjones** [comment]
@paramitamandal this is a separate issue from the original question, which was dealing with a `PlatformNotSupportedException`.

Regarding your issue, when you use the reflection approach, the assembly containing `ProtectedData` isn't loaded because you have no reference to it - it's not in the deps.json file and its not in any of the places that the assembly loader will look for, it's a NuGet package.

When you add a PackageReference or ProjectReference to the actual service, `ProtectedData` is understood to be a transitive dependency so it is loaded correctly.

**Comment by paramitamandal** [comment]
thanks @vcsjones for commenting. Benjamin n me are using kind of same code but facing two different issues. He got PlatformNotSupportedException where as I got FileNotFoundException.

For the second part, I loaded the ServiceApp dll via reflection from ConsoleApp dll; so did not use any reference in ConsoleApp.csproj. I am not much experienced in dotnetcore. Actually in our project we dynamically load many dlls, and those dlls are also having references with other Microsoft dlls like cryptography.Pkcs but we are facing problem to handle only ProtectedData.

**Comment by paramitamandal** [comment]
@vcsjones can u plz let me know why we need to specify protectedData in ConsoleApp where there is already a reference of ProtectedData in ServiceApp.dll? Moreover for cryptography.Pkcs reference we do not need to specify it in ConsoleApp only reference in ServiceApp is sufficient. Any help is much appreciated!

**Comment by bartonjs** [comment]
This is getting more attention in the #37577 variant, so closing this one in favor of that one.
