### ISSUE TITLE
File.GetCreationTime returns last Modified date time  for non Windows platforms.

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#31621]
Code Fragment:

  DateTime fileCreateTime =  File.GetCreationTime("test.dat");
   Console.WriteLine("File Creation Time for test.dat is " + fileCreateTime);

If touch the file the program will return the Date time it was touched.... 

As I understand this might not be possible for non Windows platforms to get the file creation time  but documentation should be modified to reflect this issue. 

FYI: Issue also occurs in mono.

**Comment by stephentoub** [comment]
> As I understand this might not be possible for non Windows platforms

Right. We support it where the data is available, e.g. where stat exposes a "birthtime".

> but documentation should be modified to reflect this issue.

The docs are open source at https://github.com/dotnet/dotnet-api-docs. Please feel free to open an issue there with the suggestion, or even contribute a PR. Thanks!
