### ISSUE TITLE
[Tests]  Ensure JsonSerializer doesn't (de)serialize non-public properties

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#31633]
Follow up from https://github.com/dotnet/runtime/pull/2278.

We should add some tests ensuring that the serializer doesn't deserialize/serialize non-public properties under any circumstance including:

- when a derived type adds a non-public `new` property which collides with a public property defined on the parent
- when there are property name collisions between public/non-public properties due to `[JsonPropertyName]`
- when there are property name collisions between public/non-public properties due to `JsonNamingPolicy`

all such tests should have variants checking that public properties that are `[JsonIgnore]`'d are not accidentally (de)serialized due to mismatching `JsonPropertyInfo` with a colliding non-public member.

https://dotnetfiddle.net/2BD7bK goes over a few expecations.

**Comment by layomia** [comment]
Closed in https://github.com/dotnet/runtime/pull/32107 and related changes.

**Comment by Simonl9l** [comment]
Curious minds...is System.Test.Json suppose to be a plugin replacement to Json.Net ? cause if so this is going the wrong direction - probably for a very broad development community that does to to re-write all their code.
