### ISSUE TITLE
Consider porting Interlocked.SpeculationBarrier() from .NET 4.8

### ISSUE THREAD

**Issue by reflectronic** [dotnet/runtime#31639]
.NET 4.8 introduced a new [`Interlocked.SpeculationBarrier()`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.speculationbarrier?view=netframework-4.8) API. Presumably, it was introduced as part of the spectre/meltdown mitigations. Is there any reason why this was added to .NET 4.8 only? Few would understand how to use it, but if it met the high bar for .NET Framework...

**Comment by GrabYourPitchforks** [comment]
There's a more complex history behind this API than it appears at first. But in a nutshell - and with _significant_ handwaving - the reason the `SpeculationBarrier` API was added to .NET Framework is that it was the __least__ amount of work that could be done at the runtime level while still allowing applications to opt in to mitigations if developers deemed it appropriate for their code. The desire for .NET Core isn't to have a standalone intrinsic that developers must sprinkle throughout their code, but instead to have a global switch that could enable the speculative execution mitigations application-wide. That work isn't yet finished.

Another thing to keep in mind is that we don't have evidence that anybody actually uses the `SpeculationBarrier` intrinsic in practice. So it doesn't necessarily meet the bar for porting to .NET Core at the moment.

**Comment by jkotas** [comment]
As @GrabYourPitchforks said. This method was added to .NET Framework as future proofing when the wave of the speculative execution security issues started. Now that we know more about these issues, we do not believe that this method is useful.

cc @stephentoub @AndyAyersMS
