### ISSUE TITLE
Question about AzDO pipeline run and GitHub commits

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#31666]
Is there a way to see all the GitHub commits (e.g., a list of PRs to master) between two runs of an AzDO pipeline? E.g., what were all the PR's/commits between:

https://dev.azure.com/dnceng/public/_build/results?buildId=504461&view=results

and:

https://dev.azure.com/dnceng/public/_build/results?buildId=504509&view=results

?

@dotnet/runtime-infrastructure

**Comment by BruceForstall** [comment]
I believe Jenkins showed this directly in the UI for a run.

**Comment by ViktorHofer** [comment]
From your first link, at the end of the summary page:

![image](https://user-images.githubusercontent.com/7412651/73675133-2eb5a280-46b2-11ea-80f0-b290d036fefb.png)

**Comment by safern** [comment]
@BruceForstall does that help you and answer your question?

**Comment by dagood** [comment]
That's the old UI, in the new UI ("Multi-stage pipelines" preview) you have to click this text:

> ![image](https://user-images.githubusercontent.com/12819531/73680975-f6e33680-4682-11ea-995b-5703ce55f4fa.png)

**Comment by dagood** [comment]
If you want to directly diff two builds, you can type out a github URL directly fairly easily: `https://github.com/dotnet/runtime/compare/f954c6b...6c8a6290`. (Useful to compare official builds, things that AzDO doesn't detect as expected, and Maestro++ PR dependency source changes.)

**Comment by BruceForstall** [comment]
Thanks @dagood. Apparently I have the "new UI". I didn't see the "12 commits" text at first, and it wasn't obvious to me it was a clickable link, either (same for the other items in that list/display).
