### ISSUE TITLE
Reference type check branch does not get eliminated for Nullable<T> 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#31661]
Reference type check code and reference branch does not get eliminated for Nullable<T> 

https://sharplab.io/#v2:C4LghgzgtgPgAgBgAQGUAWYBOAHAMmAIwDoAlAVwDtgBLKAUwG4BYAKFbgGYk4AmJAYSSsA3qyTikAbQBS1YAHE6FOpmoBjABTAAntjoB7AGYbqVAPwBKCwBokshUpXqtug8dPArAXTETO3AEYANiQPJABZAB4AFQA+DQshFgkkUWSUiWpDJA0AEzpDMDIAG2ANaMSAXkqkChLixN8M1KbmvwB2JADmdOaAXyS2pDpiiDpBtrShlLhOnh6hvtallj6gA

```cs
using SharpLab.Runtime;

public class C 
{
    [JitGeneric(typeof(int?)), JitGeneric(typeof(int))]
    public static int M<T>() 
    {
        if (default(T) == null) 
        {
            return 1;
        } 
        else 
        {
            return 2;
        }
    }
}
```

asm:
```
; Core CLR v4.700.19.51502 (coreclr.dll) on x86.

C..ctor()
    L0000: ret

C.M[[System.Nullable`1[[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]]()
    L0000: sub esp, 0x8
    L0003: xor eax, eax
    L0005: mov [esp], eax
    L0008: mov [esp+0x4], eax
    L000c: xor eax, eax
    L000e: lea edx, [esp]
    L0011: mov [edx], eax
    L0013: mov [edx+0x4], eax
    L0016: cmp byte [esp], 0x0
    L001a: jnz L0025
    L001c: mov eax, 0x1
    L0021: add esp, 0x8
    L0024: ret
    L0025: mov eax, 0x2
    L002a: add esp, 0x8
    L002d: ret

C.M[[System.Int32, System.Private.CoreLib]]()
    L0000: mov eax, 0x2
    L0005: ret
```

**Comment by BruceForstall** [comment]
@AndyAyersMS

**Comment by AndyAyersMS** [comment]
We haven't put much effort into improving CQ for nullables, seems like we ought to invest here some.

**Comment by AndyAyersMS** [comment]
`fgMorphRecognizeBoxNullable` does part of the job here -- it simplifies the compare tree and removes the call to the box helper. But the struct remains address exposed and so we can't propagate the `hasValue` bit into the compare and finish the cleanup.

If we refactored so we could also have this transformation fire in `gtFoldExprSpecial` then we'd likely realize that the struct is no longer exposed; that would at least give us a chance to get rid of the rest.

**Comment by AndyAyersMS** [comment]
I've verified that if we move this optimization earlier then we get desired codegen. Let me work on a real fix.
