### ISSUE TITLE
Enable --debug mode in Mono by default

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#31662]
Historically Mono required passing the `--debug` flag to enable reading of .pdb files for getting line numbers in stack traces.

Since .NET Core does this by default we should look at enabling this on Mono too.

/cc @lambdageek @steveisok @marek-safar

**Comment by steveisok** [comment]
To me, that would mean removing swapping options.  Instead of offering `--debug`, we would add `--release`.

**Comment by akoeplinger** [comment]
that'd be misleading, I'd rather add something like `--debug=ignore`.

**Comment by steveisok** [comment]
I'm assuming we want this for netcore only?

**Comment by akoeplinger** [comment]
Yes.

**Comment by jaykrell** [comment]
How about -nodebug?
But nice change. Debugality is too important.

**Comment by am11** [comment]
https://github.com/dotnet/runtime/issues/839#issuecomment-571242564 suggested the opposite for dotnet/runtime repo; match `make` etc. and make Release as default configuration.

**Comment by lambdageek** [comment]
> [#839 (comment)](https://github.com/dotnet/runtime/issues/839#issuecomment-571242564) suggested the opposite for dotnet/runtime repo; match `make` etc. and make Release as default configuration.

This is an orthogonal issue. 839 is about how the assemblies and native code are _built_.

Mono's `--debug` option controls how the runtime behaves - whether the JIT will make provisions for debugging info to be available (by loading PDBs, etc).  This is most directly observable on stack traces on exceptions - without `--debug` even for assemblies compiled with Debug builds, mono will not have line numbers on stack traces.  With `--debug` (or now by default with this PR), we will always try to make use of the PDBs.
