### ISSUE TITLE
Should Switch.System.Net.DontEnableSchSendAuxRecord have any effect in .NET Core 3.1?

### ISSUE THREAD

**Issue by rayanalsubhi-feenics** [dotnet/runtime#31660]
I am migrating a .NET 4.6 application to .NET Core 3.1. The application makes a TLS 1.0 connection to a legacy device that is not going to receive any updates (it doesn't support TLS 1.1 or TLS 1.2)

The issue that I'm facing is related to a mitigation introduced in https://support.microsoft.com/en-ca/help/3155464/ms16-065-description-of-the-tls-ssl-protocol-information-disclosure-vu

The workaround that I had in .NET 4.6 was to set this AppContext switch to true:
```csharp
AppContext.SetSwitch("Switch.System.Net.DontEnableSchSendAuxRecord" , true);
```

This switch does not seem to be doing anything in .NET Core 3.1.The communication to the device breaks as it does not know how to handle the mitigation (Mitigation is to split the first application data to 1 byte then send the remaining data).

Would it be possible to disable the mitigation in .NET Core 3.1? I hate to be asking this question, but we are stuck with legacy devices and customers are probably not going to upgrade them.

Thanks

**Comment by davidsh** [comment]
>This switch does not seem to be doing anything in .NET Core 3.1.

The switch doesn't exist in .NET Core.

**Comment by rayanalsubhi-feenics** [comment]
> The switch doesn't exist in .NET Core.

@davidsh Thanks for the confirmation. Is there a workaround in .NET Core?

**Comment by davidsh** [comment]
>Is there a workaround in .NET Core?

There is not. In general, .NET Core doesn't have those AppContext or registry key switches to temporarily turn off security fixes (such as SCH_SEND_AUX_RECORD)  that .NET Framework did.

**Comment by rayanalsubhi-feenics** [comment]
Thank you.
