### ISSUE TITLE
Events contained unexpected event in AsyncTaskMethodBuilderTests.DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#31675]
*Example repro:*

https://dev.azure.com/dnceng/public/_build/results?buildId=505090&view=ms.vss-test-web.build-test-results-tab&runId=16033318&resultId=102213&paneView=debug

*Platform:* multiple including Alpine Linux x64 Release

*Error log:*

<pre>
Child exception:
  Xunit.Sdk.XunitException: Events contained unexpected event:
ActivityId: 00000000-0000-0000-0000-000000000000
Channel: None
EventId: 0
EventName: EventSourceMessage
EventSource: EventSource(System.Threading.Tasks.TplEventSource, 2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5)
Keywords: None
Level: LogAlways
Message: ERROR: Exception in Command Processing for EventSource System.Threading.Tasks.TplEventSource: Could not find the resource "System.Private.CoreLib.Resources.Strings.resources" among the resources "System.Private.CoreLib.Strings.resources", "System.Private.CoreLib.xml" embedded in the assembly "System.Private.CoreLib", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
Opcode: Info
OSThreadId: 48
Payload: ERROR: Exception in Command Processing for EventSource System.Threading.Tasks.TplEventSource: Could not find the resource "System.Private.CoreLib.Resources.Strings.resources" among the resources "System.Private.CoreLib.Strings.resources", "System.Private.CoreLib.xml" embedded in the assembly "System.Private.CoreLib", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
PayloadNames: message
RelatedActivityId: 00000000-0000-0000-0000-000000000000
Tags: None
Task: None
TimeStamp: 2/3/2020 11:58:40 AM
Version: 0

   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.<>c.<DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0() in /_/src/libraries/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs:line 625

Child process:
  System.Threading.Tasks.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<>c Void <DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0()
</pre>

**Comment by stephentoub** [comment]
@noahfalk, @tarekgh, this has started happening recently and sporadically.  A test of TplEventSource is getting an EventSource error event:
```
Message: ERROR: Exception in Command Processing for EventSource System.Threading.Tasks.TplEventSource: Could not find the resource "System.Private.CoreLib.Resources.Strings.resources" among the resources "System.Private.CoreLib.Strings.resources", "System.Private.CoreLib.xml" embedded in the assembly "System.Private.CoreLib", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
```
Ideas?  Seems like something regressed, maybe something around our corelib build?

**Comment by tarekgh** [comment]
@stephentoub this is for sure is build issue with corelib. it is expected to have the resources stream name in corelib as `System.Private.CoreLib.Strings.resources`, while it the exception message saying the name in corelib is `System.Private.CoreLib.Strings.resources`.  Maybe we are building Linux Alpine differently?

**Comment by tarekgh** [comment]
I checked 5.0 builds and I am seeing we are building using ` System.Private.CoreLib.Strings.resources` as the resource name. maybe there is someplace in the test somehow trying to access the resources with a hardcoded name.

**Comment by tarekgh** [comment]
I found it, I'll submit a PR soon.

**Comment by stephentoub** [comment]
Excellent.  Thanks, @tarekgh.
