### ISSUE TITLE
Received data when expecting null in SendAsync_GetWithValidHostHeader_Success

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#31676]
*Example repro:*

https://dev.azure.com/dnceng/public/_build/results?buildId=504646&view=ms.vss-test-web.build-test-results-tab&runId=16022470&resultId=103754&paneView=debug

*Error log:*

<pre>
Assert.Equal() Failure\r\nExpected: (null)\r\nActual: Byte[] [67, 91, 72, 199, 10, ...]

Stack trace
   at System.Net.Http.Functional.Tests.TestHelper.VerifyResponseBody(String responseContent, Byte[] expectedMD5Hash, Boolean chunkedUpload, String requestBody) in /_/src/libraries/Common/tests/System/Net/Http/TestHelper.cs:line 46
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_GetWithValidHostHeader_Success(Boolean withPort) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Headers.cs:line 264
--- End of stack trace from previous location ---
</pre>

I generally tend to ignore errors caused by transient network issues but it seems weird that we're receiving a response when we don't expect to.

**Comment by alnikola** [comment]
I checked the test and it doesn't expect null actually, instead it compares response's MD5 hash returned from the server to the hash calculated in the test. It means that Assert failed because the response somehow had hash=null which seems to be an intermittent network or server error since this is the only failure on this test's history.

**Comment by trylek** [comment]
Thanks @alnikola for double-checking. If it was a one-off failure, feel free to close this item as no repro. If it happens again, we'll be able to find this item in GitHub history and decide whether further action is needed.

**Comment by alnikola** [comment]
Closing as an one-off failure.

**Comment by stephentoub** [comment]
> Closing as an one-off failure

My concern here is that we have millions of tests.  If each sporadically has a one-off failure, we'll never get clean.  We need to find ways to get resilient against such things, retries, whatever.

cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
In code retries are already possible with the RetryHelper. We should clarify if that's enough or if we want an easier way like flagging tests as flaky so that they retry automatically. As most of such failures happen in System.Net.* I ask for opinions from @wfurt @davidsh @karelz and others.

**Comment by wfurt** [comment]
There are many tests failing in that batch. Mostly with

```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_ValidCertificate_SuccessAndExpectedPropertyBehavior [FAIL]
      Assert.Equal() Failure
      Expected: OK
      Actual:   ServiceUnavailable
      Stack Trace:
..
..
..
  Finished:    System.Net.Http.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Http.Functional.Tests  Total: 758, Errors: 0, Failed: 17, Skipped: 11, Time: 73.806s
```

I'm not convinced that immediate retry will work for  Azure outages. 
We may consider something like https://github.com/dotnet/runtime/pull/2369 and skip the content validation if we fail to get a successful response.

Long term, we may convert this to containerized tests similar to enterprise auth. 

cc: @davidsh

**Comment by davidsh** [comment]
>Long term, we may convert this to containerized tests similar to enterprise auth.

That is what I have been thinking about. In the old days, we would run tests in a physical lab where client and server machines are only separated by a network switch. That had higher reliability than having a remote server somewhere in the Internet separated by many layers of load balancers, proxies, etc.

In fact, the current code that runs as the remote Azure server (https://corefx-net-http11.azurewebsites.net/) can easily be containerized and we can change our test pipelines to launch the container prior to running the tests. This is similar to what I do for the enterprise tests pipeline, [runtime-libraries enterprise-linux](https://dev.azure.com/dnceng/public/_build?definitionId=690&_a=summary)
