### ISSUE TITLE
Arm64: Improve code generation for Vector<T> comparision

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#31685]
An example from ConsoleMandel:
Source:
```
while (increment != Vector<int>.Zero);
```
Generated code:
``` 
            dup     v20.4s, wzr
            cmeq    v21.4s, v19.4s, v20.4s
            uminv   v21.16b, v21.16b
            mov     w0, v21.b[0]
            eor     w0, w0, #1
            and     w0, w0, #1

            cbnz    w0, G_M3984_IG05
```
I believe that `umaxv` could be used for the != case. Also, if the result of the comparison is used in a branch, we shouldn't have to produce the precise `1` or `0`.

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
@CarolEidt @kunalspathak is this something we should put into .NET 5?

**Comment by tannergooding** [comment]
Some of this may naturally improve with the changes I did for https://github.com/dotnet/runtime/pull/35421 and the follow up PR I'll be submitting to handle cases like `op_Equality` and `op_Inequality`.

**Comment by AndyAyersMS** [comment]
Ok, will put in 5.0, we can revisit later if this is optimistic.

**Comment by BruceForstall** [comment]
@tannergooding @CarolEidt Is there any work left here? Should the issue remain in 5.0?

**Comment by kunalspathak** [comment]
In one of my previous PRs Tamar pointed out in https://github.com/dotnet/runtime/pull/37624#issuecomment-641451575 that `addp` or `uminp` is cheaper than `uminv`, so may be that's the minimum we should do. If @tannergooding  is busy, I can take some time to do it.

**Comment by BruceForstall** [comment]
I'm moving this to Future.

**Comment by kunalspathak** [comment]
@EgorBo  - can you double check if https://github.com/dotnet/runtime/pull/65632 handles this pattern?

**Comment by EgorBo** [comment]
Just checked - yes, it does
