### ISSUE TITLE
Merge multiple IBC data readings for the same MethodDesc

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#31687]
In my initial experiments with composite R2R build mode, I hit the exception throw at

https://github.com/dotnet/runtime/blob/be41d6275a6f4006c6d535da3308cb41b3846a59/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/IBC/IBCProfileData.cs#L19

According to @davidwrighton, this is likely due to the current inability to accumulate IBC data across multiple readings. The purpose of this work item is to fix this deficiency.

Thanks

Tomas

**Comment by mangod9** [comment]
should this be resolved @trylek ?

**Comment by davidwrighton** [comment]
Well, right now we just ignore any details beyond the first. This is "ok" as we don't actually use the ibc block data, but will need to be handled more correctly once we do. I think that means we should keep the workitem open.

**Comment by davidwrighton** [comment]
This sort of work on IBC and PGO will not happen in .NET 5.0. Moving to 6.0.

**Comment by davidwrighton** [comment]
Merging is supported in .NET 6.0
