### ISSUE TITLE
Arm64: Support containment of immediates for Vector<T>

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#31693]
An example from ConsoleMandel:
Source:
```
while (increment != Vector<int>.Zero);
```
Generated code:
``` 
            dup     v20.4s, wzr
            cmeq    v21.4s, v19.4s, v20.4s
            uminv   v21.16b, v21.16b
            mov     w0, v21.b[0]
            eor     w0, w0, #1
            and     w0, w0, #1

            cbnz    w0, G_M3984_IG05
```
This issue is about the fact that we shouldn't materialize zero into `v20.4s`. See also #31685 for the fact that the code generation for comparison is sub-optimal.

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by CarolEidt** [comment]
ConsoleMandel exists in the dotnet/performance repo here: https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/runtime/SIMD/ConsoleMandel asn well as in the dotnet/coreclr tests here: https://github.com/dotnet/runtime/tree/master/src/coreclr/tests/src/JIT/Performance/CodeQuality/SIMD/ConsoleMandel

**Comment by BruceForstall** [comment]
cc @echesakovMSFT

**Comment by AndyAyersMS** [comment]
@CarolEidt @kunalspathak marking this as future; let me know if you think otherwise.

**Comment by TIHan** [comment]
This has already been optimized via https://github.com/dotnet/runtime/pull/65632
