### ISSUE TITLE
[QUIC] Update MsQuic GCHandles

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#31695]
Some of the classes in MsQuic implementation are allocating a `GCHandle` for `this` and is depending on `Dispose` or finalizer to deallocate `this`. If a user forgets to call `Dispose`, the GC will never collect the object due to the `GCHandle`.

**Comment by scalablecory** [comment]
@geoffkizer feel free to unassign if you won't be able to get to this. We could reasonably bump this to 6.0 if we need to.

**Comment by ManickaP** [comment]
Close by https://github.com/dotnet/runtime/pull/49823
