### ISSUE TITLE
NullReferenceException on XNodeNavigator.MoveToNext(XPathNodeType)

### ISSUE THREAD

**Issue by mayorovp** [dotnet/runtime#31710]
```cs
// Create current element and it's parent
var current = new XElement("foo");
new XElement("parent", current);

// Try to find next sibling via xpath
var nav = current.CreateNavigator();
nav.MoveToNext(XPathNodeType.Element);
```

**expected**: MoveToNext returned false
**got**: NullReferenceException, probably in this line: https://github.com/dotnet/runtime/blob/9524bb599ea231fee1f9e233cb1a71850289ea57/src/libraries/System.Private.Xml.Linq/src/System/Xml/XPath/XNodeNavigator.cs#L552

**Comment by danmosemsft** [comment]
Thanks @mayorovp . Any interest in offering a PR and test?
