### ISSUE TITLE
[mono] Test failed with crash: System.Tests.Types.VoidTests.IsByRef_Get_ReturnsExpected

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#31713]
`System.Tests.Types.VoidTests.IsByRef_Get_ReturnsExpected` fails with crash in case of `void` type. It seems that the cause of the crash is somewhere in `Runtime.make_byref_type ()` method. 
This test will be skipped with ActiveIssue in #2087.

**Comment by GrabYourPitchforks** [comment]
Per Maxim's comment, looks like the relevant code is somewhere in the below.

https://github.com/dotnet/runtime/blob/aa6d1ac74e6291b3aaaa9da60249d8c327593698/src/mono/mono/metadata/icall.c#L7199-L7213

**Comment by lambdageek** [comment]
This seems to work in a standalone example now:

```
	    var t = typeof (void);
	    var b = t.IsByRef;
	    Console.WriteLine ("{0} {1}", b, t.FullName);
	    var u = t.MakeByRefType ();
	    Console.WriteLine ("{0}", u.IsByRef);
```

**Comment by SamMonoRT** [comment]
Assigning to CoffeeFlux for tracking.

**Comment by CoffeeFlux** [comment]
This can't be re-enabled yet, held up by https://github.com/dotnet/runtime/issues/37489

**Comment by SamMonoRT** [comment]
@imhameed - can this test be re-enabled and close this issue ?
