### ISSUE TITLE
Fix Testing of TargetFrameworks other than netcoreapp5.0 in Visual Studio

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#31757]
After the New configuration system has been deployed, we should be able to run the tests against the net472 or other targetFrameworks.

The issue is to track that work

cc @ericstj @ViktorHofer

**Comment by ViktorHofer** [comment]
That should only be a matter of setting the `DEVPATH` variable in the -vs path in the build.ps1 script. Assigning to myself to take care of this.

**Comment by Anipik** [comment]
@ViktorHofer is this fixed ?
