### ISSUE TITLE
Use live bits or recent shared framework for crossgen2 and other tools in coreclr subset

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#31755]
There are some self contained applications that we build in the coreclr subset https://github.com/dotnet/runtime/tree/master/src/coreclr/src/tools

They are using a very old(3-4 months) copy of the shared framework. We should start using the live bits are or should automatically update shared framework version.

cc @ericstj

**Comment by jkoritzinsky** [comment]
Crossgen2 will start running against live bits after https://github.com/dotnet/runtime/pull/31701

**Comment by jashook** [comment]
Addressed
