### ISSUE TITLE
Setting PropertyNamingPolicy to null results in JsonException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#31758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/859177/setting-propertynamingpolicy-to-null-results-in-js.html)._

---
In general, the JSON options configuration for the new System.Text.Json seems underdeveloped. Say, I cannot just extend JsonStringEnumConverter, if I want to write the possible enum values in the exception message; I'd have to replicate it.

The problem at hand is that the documentation states, that setting PropertyNamingPolicy to null preserves the property names. In fact, it throws an exception.

---
#### Visual Studio Feedback System on 12/18/2019, 00:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/22/2020, 06:27 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Mikhail on 1/22/2020, 11:59 PM: 

<p>Thank you for the info. I know it's not your call. But I'd say, if Microsoft wants to replace Newtonsoft, their JSON ought to be as good as Newtonsoft. At the moment there is a fairly large number of deficiencies in System.Text.Json, naming policies being one of them.</p>

---
#### Mikhail solved on 1/22/2020, 11:58 PM, 0 votes: 

<p>== Don't know how to delete a Solution. Posted by mistake instead of Comment.</p>

**Comment by ahsonkhan** [comment]
> The problem at hand is that the documentation states, that setting PropertyNamingPolicy to null preserves the property names. In fact, it throws an exception.

I am unable to repro the issue given the information provided. Can you please provide a simplified/isolated repro that showcases the error?

1) What is the exception you are seeing? Can you provide the whole message.
2) Is there something specific with your .NET object model that results in the error or does it always happen when `PropertyNamingPolicy` is set to null?
3) What target framework are you running on? Are you on .NET Core 3.0 or 3.1? If you are on .NET Framework, what version of the System.Text.Json package are you referencing?

This works as expected for me:
```C#
private static void TestNull()
{
    var options = new JsonSerializerOptions { PropertyNamingPolicy = null };

    var input = new Customer { Data = 5 };
    Console.WriteLine(JsonSerializer.Serialize(input, options)); // Outputs: {"Data":5}

    var result = JsonSerializer.Deserialize<Customer>(JsonSerializer.Serialize(input, options), options);
    Console.WriteLine(result.Data); // Returns 5
}

public class Customer
{
    public int Data { get; set; }
}
```

**Comment by layomia** [comment]
Closing - we can't repro this. This can be reopened if someone provides a repo.
