### ISSUE TITLE
GCStress=C failure in JIT/Regression/JitBlue/GitHub_13057/GitHub_13057/GitHub_13057.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#31769]
Failure in Linux x64 Checked stress runs with gcstress0xc_zapdisable_jitstress2, gcstress0xc_jitstress1, and gcstress0xc_jitstress2.

`
\nAssert failure(PID 24499 [0x00005fb3], Thread: 24499 [0x5fb3]): !CREATE_CHECK_STRING(pMT && pMT->Validate())\n File: /__w/10/s/src/coreclr/src/vm/object.cpp Line: 557\n Image: /home/helixbot/work/ACAB098C/p/corerun\n\n/home/helixbot/work/ACAB098C/w/9FE70916/e/JIT/Regression/JitBlue/GitHub_13057/GitHub_13057/GitHub_13057.sh: line 275: 24499 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"\n\nReturn code: 1\nRaw output file: /home/helixbot/work/ACAB098C/w/9FE70916/e/JIT/Regression/Reports/JIT.Regression/JitBlue/GitHub_13057/GitHub_13057/GitHub_13057.output.txt\nRaw output:\nBEGIN EXECUTION\n/home/helixbot/work/ACAB098C/p/corerun GitHub_13057.dll ''\nWriting minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.24499.dmp\nWritten 54415360 bytes (13285 pages) to core file\nExpected: 100\nActual: 134\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/ACAB098C/p\n> /home/helixbot/work/ACAB098C/w/9FE70916/e/JIT/Regression/JitBlue/GitHub_13057/GitHub_13057/GitHub_13057.sh\nExpected: True\nActual: False
`

https://dev.azure.com/dnceng/public/_build/results?buildId=507060&view=results

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
I'll take a look.
