### ISSUE TITLE
Update TextReader's default async method implementations to call ReadAsync() instead of Read()

### ISSUE THREAD

**Issue by halter73** [dotnet/runtime#31763]
Methods like TextReader.ReadToEndAsync()'s default implementation calls TextReader.Read() instead of TextReader.ReadAsync().

It would be nicer if a TextReader implementation could override `ReadAsync(char[] buffer, int index, int count)` and `ReadAsync(Memory<char> buffer, CancellationToken cancellationToken = default)` to get truly async versions of ReadToEndAsync(), ReadLineAsync() and ReadBlockAsync() automatically.

The alternative is to have types like HttpRequestStreamReader override 6 async methods just to avoid async-over-sync.

See https://github.com/dotnet/aspnetcore/issues/13834.

**Comment by JeremyKuhne** [comment]
We really can't do much here as it would be a breaking change as derived classes would no longer get potentially overriden `Read()` methods called. In derived classes we work around the derivation problem by checking our type to see if the class is derived or not (which gets optimized by the JIT). There is no efficient way to check if a given method is overriden. :/

We could potentially create some protected setting that derived classes could set to change the behavior. @stephentoub How tenable do you think that approach is?

**Comment by julealgon** [comment]
This should be kept open.

**Comment by halter73** [comment]
@JeremyKuhne makes a good point about my suggested change being breaking. While not a general solution, the better non-breaking proposal for `HttpRequestStreamReader` would be to add a constructor to `StreamReader` to make it compatible as a base type. I've proposed exactly this in #107490.

That's not a general solution, for something like that you might want something like a `DelegatingTextReader` similar to the `DelegatingStream` proposed by #43139 or a source generator similar to what's proposed for `Stream` by #79839. I don't think a breaking change is a good idea considering that this can be worked around, so I think any fix will have to come in the form of a new API. Unfortunately, I don't have an exact API proposal in mind, and I don't think addressing this, so I'm going to close this issue. I welcome anyone who wants to open a new issue to address this problem in a non-breaking way to do so.
