### ISSUE TITLE
ConfigurationManager.OpenExeConfiguration(string exPath) input not working in dotnetcore3

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#31764]
This issue ported from 
https://developercommunity.visualstudio.com/content/problem/850953/configurationmanageropenexeconfigurationstring-exp.html

[code reproing the issue](https://ibb.co/23T7vXZ)

**Comment by ericstj** [comment]
This works for me.  [OpenExeConfiguration.zip](https://github.com/dotnet/runtime/files/4887549/OpenExeConfiguration.zip)

Chances are the problem is with the config file that is being loaded.  We'd need more information to properly diagnose.

**Comment by danmosemsft** [comment]
Insufficient info.
