### ISSUE TITLE
Official builds in runtime failing with signing errors

### ISSUE THREAD

**Issue by riarenas** [dotnet/runtime#31760]
@jaredpar commented on [Tue Feb 04 2020](https://github.com/dotnet/core-eng/issues/8814)

Signing phase fails with errors like the following:

> error SIGN001: Signing 3rd party library '...bin\ref\microsoft.netcore.app\Release\System.Numerics.dll' with Microsoft certificate 'Microsoft400'. The library is considered 3rd party library due to its copyright: ''.

Example Build: 
- https://dev.azure.com/dnceng/internal/_build/results?buildId=506914&view=logs&j=03f0c49c-0e1a-5166-19f6-fc865fe47495&t=8ffb5fe8-216f-590f-db83-b0e95984e140&l=1082
- https://dev.azure.com/dnceng/internal/_build/results?buildId=506988

FR Thread: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1580845734961?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1580845734961&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1580845734961

---

@dagood commented on [Tue Feb 04 2020](https://github.com/dotnet/core-eng/issues/8814#issuecomment-582091285)

This is blocking dotnet/runtime official builds, as far as we can tell. Second failure: https://dev.azure.com/dnceng/internal/_build/results?buildId=506988&view=results

---

@safern commented on [Tue Feb 04 2020](https://github.com/dotnet/core-eng/issues/8814#issuecomment-582158431)

@dagood I believe we can transfer this issue into dotnet/runtime and assign to @marek-safar as it is actually ILLink which is trimming the required attributes and causing the failure? 

---

@dagood commented on [Tue Feb 04 2020](https://github.com/dotnet/core-eng/issues/8814#issuecomment-582159005)

It can't be transferred (private => public doesn't work) but I agree this is not an FR issue given recent convo in the teams thread.

---

@riarenas commented on [Tue Feb 04 2020](https://github.com/dotnet/core-eng/issues/8814#issuecomment-582160920)

I'm going to try to transfer the issue using ZenHub. It should close this and open a new one with a summary of all comments in dotnet/runtime.

**Comment by safern** [comment]
To summarize it here, basically this happened because of the ILLink update in: https://github.com/dotnet/runtime/commit/a05c599e0c9ba113902ba59746e041f1513cc339

After that update all of our full facades are getting the assembly attributes that define the company copyright and other information during trimming, hence, the official build is failing to validate it is a 1st party assembly.

**Comment by safern** [comment]
Closing as we reverted the break.
