### ISSUE TITLE
AsyncLocal<T> to let programmer clone the value in the old thread context

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/runtime#31783]
_This issue is recreated under dotnet/runtime from https://github.com/dotnet/docs/issues/9965 per suggestion in https://github.com/dotnet/coreclr/pull/28007._

In .NET Framework CallContext is the mechanism for applications to have ambient data that flow with the execution even if thread context changes. In certain slots of CallContext, if the data type implements IClonable, the object is cloned right before the thread context is switched. Such mechanism is necessary for applications that need the old and new thread contexts to use separate copies of the ambient data.

It seems hard for such applications to be ported to .NET Core since CallContext is not provided there.

AsyncLocal is a new type on both .NET Framework and NET Core platforms that replaces most of the functionality of CallContext. AsyncLocal represents ambient data that is local to a given asynchronous control flow.

AsyncLocal let the user handle the event that the value is changed, including value change due to thread context change. However the handler is invoked in the new thread context when async methods are called. In situations where the the old thread and the new thread cannot share the same copy of the ambient data, such mechanism would create race condition if cloning happens in the new thread context. It would be ideal to have an event that the application can handle to make the cloning decision in the old thread context right before the context switching happens.

**Comment by stephentoub** [comment]
cc: @kouvel
