### ISSUE TITLE
System.Text.Json serializes single quotes as \u0027

### ISSUE THREAD

**Issue by cmeeren** [dotnet/runtime#31788]
The following:

```f#
System.Text.Json.JsonSerializer.Serialize("'abc'")
```

outputs

```f#
"\u0027abc\u0027"
```

I would expect it to output

```f#
"'abc'"
```

**Comment by GrabYourPitchforks** [comment]
This is by design. See https://github.com/dotnet/runtime/issues/1564#issuecomment-504780719 and https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialize-all-characters for further information.

**Comment by cmeeren** [comment]
I see, thanks.

**Comment by eiriktsarpalis** [comment]
From @charles-lambert-kc in #72239

> The issue reported here #31788 has an invalid URL in the answer. The link should be updated to https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding .

Updated @GrabYourPitchforks's answer for posterity.
