### ISSUE TITLE
[mono] Wrong System.Data.SqlClient.dll loaded

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#31799]
Live-built System.Data.SqlClient is being deleted in #2275. The few tests that use System.Data.SqlClient are being switched to use NuGet package.

The Mono assembly seems to have a bug where it loads wrong System.Data.SqlClient.dll after the switch to use NuGet package that makes these tests to fail. I am disabling these tests against this issue.

**Comment by ViktorHofer** [comment]
cc @akoeplinger @steveisok

**Comment by lambdageek** [comment]
The disabled tests in question are in this commit: https://github.com/dotnet/runtime/pull/2275/commits/bb16909469e7435e02b6fe39921ddf257858906c

**Comment by steveisok** [comment]
From what I can tell, `System.Data.SqlClient.dll` is the same one loaded into both runtimes.  

Here's a snippet of the mono trace:

```
Mono: Assembly Loader probing location: '/Users/steve/dev/dotnet-runtime/artifacts/bin/System.Data.Common.Tests/netcoreapp5.0-Debug/System.Data.SqlClient.dll'.
  Mono: Image addref System.Data.SqlClient[0x7fa68f4b4660] (asmctx DEFAULT) -> /Users/steve/dev/dotnet-runtime/artifacts/bin/System.Data.Common.Tests/netcoreapp5.0-Debug/System.Data.SqlClient.dll[0x7fa68fa1a400]: 2
  Mono: Predicate: wanted = System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  Mono: Predicate: candidate = System.Data.SqlClient, Version=4.6.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Mono: Predicate: candidate and wanted names match, returning TRUE
  Mono: Prepared to set up assembly 'System.Data.SqlClient' (/Users/steve/dev/dotnet-runtime/artifacts/bin/System.Data.Common.Tests/netcoreapp5.0-Debug/System.Data.SqlClient.dll)
  Mono: Loading assembly System.Data.SqlClient (0x7fa68f4b4660) into domain xunit.console.dll (0x7fa69f443c80) and ALC 0x7fa69f4446f0
  Mono: Assembly System.Data.SqlClient[0x7fa68f4b4660] added to domain xunit.console.dll, ref_count=1
  Mono: Assembly System.Data.SqlClient[0x7fa68f4b4660] added to ALC (0x7fa69f4446f0), ref_count=2
  Mono: Assembly Loader loaded assembly from location: '/Users/steve/dev/dotnet-runtime/artifacts/bin/System.Data.Common.Tests/netcoreapp5.0-Debug/System.Data.SqlClient.dll'.
  Mono: Requesting loading reference 0 (of 7) of /Users/steve/dev/dotnet-runtime/artifacts/bin/System.Data.Common.Tests/netcoreapp5.0-Debug/System.Data.SqlClient.dll
  Mono: Loading reference 0 of /Users/steve/dev/dotnet-runtime/artifacts/bin/System.Data.Common.Tests/netcoreapp5.0-Debug/System.Data.SqlClient.dll asmctx DEFAULT, looking for System.Runtime, Version=4.2.1.0, Culture=neutral, 
```
I think this might be a reflection problem as the failure is actually happening here:

https://github.com/dotnet/runtime/blob/d491056751496d997dfaa693575190508a0c3cf6/src/libraries/System.Data.Common/src/System/Data/Common/DbProviderFactories.cs#L181-L185

**Comment by jkotas** [comment]
Sorry about the false alarm. This is a problem in how src/libraries restores NuGet packages and it is also affecting CoreCLR on Alpine. I am reverting the disabled tests in https://github.com/dotnet/runtime/pull/31850/
