### ISSUE TITLE
Fix up NETCoreApp closure validation when assembling runtime packages

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#31805]
In a recent official build binlog, it looks like `VerifyClosure` isn't running, and its dependency `GetClosureFiles` doesn't show up at all. This is an important check to ensure shared framework integrity.

**Comment by NikolaMilosavljevic** [comment]
@jkoritzinsky do you know if this is handled in the new shared FX infra?

**Comment by jkoritzinsky** [comment]
The is one of the areas I need to still look at. I dont know if this is required since ASP.NET doesn't do anything similar to this. I can look at adding this in the new infra if we still feel it is valuable.

**Comment by dagood** [comment]
> The is one of the areas I need to still look at. I dont know if this is required since ASP.NET doesn't do anything similar to this. I can look at adding this in the new infra if we still feel it is valuable.

@ericstj can help make this call. My understanding is it's pretty important. (I took some efforts to keep it working over time and run it in dotnet/windowsdesktop.)

**Comment by ericstj** [comment]
This validation helps ensure we're shipping a complete shared framework.  It guards against folks taking new dependencies without putting those in the shared framework.  It's important and something we should bring back.

**Comment by ericstj** [comment]
We need to do this for 5.0.  It was just exposed that we've introduced cycles into the shared framework because this was missing.  @NikolaMilosavljevic or @jkoritzinsky were you planning on fixing this?

**Comment by NikolaMilosavljevic** [comment]
> We need to do this for 5.0. It was just exposed that we've introduced cycles into the shared framework because this was missing. @NikolaMilosavljevic or @jkoritzinsky were you planning on fixing this?

Yes, this is planned. I will work on it soon.

**Comment by NikolaMilosavljevic** [comment]
Validation in progress - sending PR later today.
