### ISSUE TITLE
WritePropertyName in JsonConverter doesn't respect casing

### ISSUE THREAD

**Issue by CheloXL** [dotnet/runtime#31818]
I have a custom JsonConverter. In the write method, I have something like `writer.WritePropertyName(nameof(IOperationResult.Value))`.

The problem is that when using the `JsonSerializer.Serialize` method and passing in the options `PropertyNamingPolicy = JsonNamingPolicy.CamelCase`, the property name is written as **Value** instead of **value**.

I need a way to respect the user settings, either by having some method in the `JsonSerializerOptions` to convert casing, or by doing that automatically in the `WritePropertyName` method.

**Comment by CheloXL** [comment]
Found the method.

**Comment by ahsonkhan** [comment]
Your custom JsonConverter has the `option` argument. You should get the `JsonNamingPolicy` from it and call it's `ConvertName` method before passed the name to the `Utf8JsonWriter`.
