### ISSUE TITLE
List<T> RemoveAt  to return the removed value

### ISSUE THREAD

**Issue by rankeren** [dotnet/runtime#31827]
In the domain of system-modeling (e, systemVerilog, matlab, phyton), lists are obsoleting arrays, stacks (and usually also queues ) altogether. Other domains that use python, perl and ruby have that same mindset, as well.
c# seem so great ..but...

The **Remove&Return** approach is respected by :
C# Stack, C# Queue, Java ArrayList ,Python list, Perl, Ruby, 'e', systemverilog and others.

**A notable exception is ... C# List.**
c# List<T>.RemoveAt(idx) doesn't return a value.

Why is that important ? Say one wants to post this in a modeling web site (who aren't experts in c#):

```
while (!myCriticalProcessList.Length != 0 ) {
  sendMethod(   myCriticalProcessList.RemoveAt(0)    );  **//  NOT working !!** 
}
```
That seem to work for any modern language, but to post it in c#, one has to also post more lines, and/or  invent new names. Also one doesn't need to know the type of the list in other langs! And when the type is changed, he does not need to change his code at all. Also naturally System modeling folks care about advanced c#, as much as c# folks care about advanced system-modeling (i.e none).

Can there be any damage if a value is returned in that case? Is there a performance consideration here? Does Java-value-return in arraylist.remove, make it slower, or less safe? Is c#'s remove&return approach good for Stack, and Queue, yet not a good idea for List? Is there some difference in underline implementation, or philosophy ?

Side note:

C# Stack.Pop and c# Queue.Dequeue do return a value. (a remove&return approach, like Java remove, and unlike c# RemoveAt).

Python's list.pop([idx]), removes-element-by-position, and returns a value. Similar to remove in java ( yet with a cool  default, remove&return the last element).

C++ (stl) remove, is also void. Yet, decisions relevant for OLD languages without native-built-in-garbage-collection, are not always relevant for new  GC langs.

**Comment by danmosemsft** [comment]
This would be a binary breaking change because it is part of the implementation of `IList<T>`. You would have to add another method.

**Comment by Suchiman** [comment]
Not just because of `IList<T>`, since you could make it an explicit implementation to keep the void returning implementation for `IList<T>`, but changing the return type is a binary (signature) and source (e.g. delegate conversion) breaking change.

I see now way how this could be done.

 More chances would have #31828 with an overload that takes an index.

**Comment by danmosemsft** [comment]
#31828 is asking for Pop(), Pop() that takes an index is not something I've seen, and on List is unfamiliar as well.

I can close this issue unless @rankeren you want to propose another name to discuss. Not sure what it would be.

**Comment by Suchiman** [comment]
@danmosemsft i meant, `T Pop(int index)` as an extension to the proposal of #31828 since it's not too far of a stretch to be able to Pop at an index and have that also return the element at that index

**Comment by rankeren** [comment]
The important stuff  is List to support `Pop `O(1) and `Pop0` (  O(n), a.k.a Dequeue). ( that is supported by python,ruby, perl,e  and more ) .   But ...  
As Pop/Pop0  are *not* in  Java. While Java 'remove-by-pos' , **does** return a value, i was thinking, lets have c# at least as good as java, in that regard.   ( in other regards c#  is not only matching, but above java).  i.e.  `RemoveAt` to return a value.    Adding Pop/Pop0 would be another significant advantage  over Java.

**Comment by rankeren** [comment]
@danmosemsft : "Pop() of any kind on List is unfamiliar to me as well."
Well...    look at   **python, perl ,ruby and 'e' (specman).**
**`Python`** list `Pop `is O(1), and `Pop(0)` , is O(n) ,  just like in 'e'. 
'`e'  (specman)` by Cadence, is the one i know well, it's **strong typed**. `list  `there is implemented  just like `List<T>` in C#.  `Pop `O(1) and `Pop0 `(O(n))  are  common operations on list.

**Comment by rankeren** [comment]
@Suchiman "   `T Pop(int index)`  ..and it's not too far of a stretch to be able to Pop at an index and have that also return the element at that index:
**absolutely** ,   and if the parameter is _**optional**_ ( default, is _last_ item),  that 'd be exactly like in Python. Great!
