### ISSUE TITLE
Why the stackalloc need ret to release?

### ISSUE THREAD

**Issue by BenLampson** [dotnet/runtime#31840]
The localloc instruction allocates size (type natural unsigned int) bytes from the local dynamic memory pool and returns the address (a transient pointer, type *) of the first allocated byte. The block of memory returned is initialized to 0 only if the initialize flag on the method is true. When the current method executes a Ret, the local memory pool is made available for reuse.

But, if we have this code
{
var x=stackalloc byte[0x00100000];
}
This X must be haven't any usage out of this scope. Why not release this x?
Must to found the ret to release's mean is?

And there have other questions.

for (int i = 0; i < 1000; i++)
{
        var x = stackalloc byte[0x0100000];
}
This code can be used to Release mode.
So, the Release mode doesn't follow the documentation?

**Comment by GrabYourPitchforks** [comment]
In your sample code:

```cs
for (int i = 0; i < 1000; i++)
{
    var x = stackalloc byte[0x0100000];
}
```

The C# compiler sees that nobody ever references _x_, so it throws the `stackalloc` away at compile time in a Release mode build. If you instead change the code to this:

```cs
for (int i = 0; i < 1000; i++)
{
    var x = stackalloc byte[0x0100000];
    x[0] = 0; // use the 'x' pointer
}
```

Then you'll see the same behavior as the Debug build.

The `stackalloc` C# keyword corresponds to the IL instruction `localloc`. The instruction is documented as not releasing memory until the current method returns. See ECMA-335 (https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf), Sec. III.3.47 for more information.

**Comment by BenLampson** [comment]
Thanks for your reply. Thx.

**Comment by GrabYourPitchforks** [comment]
@jaredpar @agocke Just as a side question, why does Roslyn optimize this away in Release? I thought the compiler generally avoided optimizing away code that might have a side effect. (One possible side effect of the localloc instruction is process termination.)

**Comment by agocke** [comment]
The purpose of optimization is to reduce the use of real resources, while preserving the same semantic effect of a program. Under this definition, resource usage itself cannot be considered a side effect worth preserving.

But speaking more broadly, we don't have any rules per se, we just try to do what we think works best for most customers.

**Comment by jaredpar** [comment]
@GrabYourPitchforks 

> One possible side effect of the localloc instruction is process termination

Correct. Generally though customers are in the habit of complaining when we produce code that causes process termination. They're usually quite pleased when we change code that reduces process termination.
