### ISSUE TITLE
[System.Text.Json] DictionaryKeyPolicy for nested Dictionary does not work as expected when been set to JsonNamingPolicy.CamelCase

### ISSUE THREAD

**Issue by Balder1840** [dotnet/runtime#31849]
When I use System.Text.Json.JsonSerializer to serialize nested dictionary,
I found the key of the first level of the dictionary not set to camel case when I set DictionaryKeyPolicy to JsonNamingPolicy.CamelCase.

Any workaround?

System.Text.Json v4.7.0
.Net Core v3.1.1

Sample Code

```c#
var firstLevelDic = new Dictionary<string, Dictionary<string, string>>();
var secondLevelDic = new Dictionary<string, string> {
    { "FOO bar", "23" },
    { "FOObar", "23" },
    { "FooBar", "23" }
};

firstLevelDic.Add("FOO bar", secondLevelDic);
firstLevelDic.Add("FOObar", secondLevelDic);
firstLevelDic.Add("FooBar", secondLevelDic);

var options = new JsonSerializerOptions();
options.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
options.WriteIndented = true;
var json = JsonSerializer.Serialize(firstLevelDic, options);
```
generated json
```json
{
  "FOO bar": {
    "foo bar": "23",
    "foObar": "23",
    "fooBar": "23"
  },
  "FOObar": {
    "foo bar": "23",
    "foObar": "23",
    "fooBar": "23"
  },
  "FooBar": {
    "foo bar": "23",
    "foObar": "23",
    "fooBar": "23"
  }
}
```

I tried Newtonsoft.Json, which works as expected
Sample Code
```C#
var firstLevelDic = new Dictionary<string, Dictionary<string, string>>();
var secondLevelDic = new Dictionary<string, string> {
    { "FOO bar", "23" },
    { "FOObar", "23" },
    { "FooBar", "23" }
};

firstLevelDic.Add("FOO bar", secondLevelDic);
firstLevelDic.Add("FOObar", secondLevelDic);
firstLevelDic.Add("FooBar", secondLevelDic);

DefaultContractResolver contractResolver = new DefaultContractResolver
{
    NamingStrategy = new CamelCaseNamingStrategy()
    {
        ProcessDictionaryKeys = true
    }
};

var settings = new JsonSerializerSettings
{
    ContractResolver = contractResolver,
    Formatting = Formatting.Indented
};

var json = Newtonsoft.Json.JsonConvert.SerializeObject(firstLevelDic, settings);
```
Result
```json
{
  "foo bar": {
    "foo bar": "23",
    "foObar": "23",
    "fooBar": "23"
  },
  "foObar": {
    "foo bar": "23",
    "foObar": "23",
    "fooBar": "23"
  },
  "fooBar": {
    "foo bar": "23",
    "foObar": "23",
    "fooBar": "23"
  }
}
```

**Comment by eltiare** [comment]
I am experiencing this bug also and would like a work-around. Perhaps writing my own converter that overrides an existing one?

**Comment by IvanOliinychenko** [comment]
Same here. Had to use options.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase; and do a conversion manually later in the code.

**Comment by layomia** [comment]
This bug has been fixed for 5.0. The workaround is to implement custom dictionary converters as required. The policy can be obtained from `options.DicitonaryKeyPolicy`.

**Comment by mariusGundersen** [comment]
This also applies if the dictionary values are an array of strings, `Dictionary<string, string[]>`, which is the case for the [`ValidationProblemDetails.Errors`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.validationproblemdetails.errors?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_ValidationProblemDetails_Errors) dictionary in ASP.NET core. 

[Here](https://dotnetfiddle.net/pOAOlw) is an example that reproduces the problem.
```cs
var result = JsonSerializer.Serialize(new
{
    StringString = new Dictionary<string, string>
    {
        ["Key"] = "Value"
    },
    StringArray = new Dictionary<string, string[]>
    {
        ["Key"] = new []{ "Value" }
    }
}, options: new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
    WriteIndented = true
});

Console.WriteLine(result);
/*
{
  "stringString": {
    "key": "Value"
  },
  "stringArray": {
    "Key": [
      "Value"
    ]
  }
}
*/
```

What is the code for the workaround?

**Comment by tlentine** [comment]
> This also applies if the dictionary values are an array of strings, `Dictionary<string, string[]>`, which is the case for the [`ValidationProblemDetails.Errors`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.validationproblemdetails.errors?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_ValidationProblemDetails_Errors) dictionary in ASP.NET core.
> 
> [Here](https://dotnetfiddle.net/pOAOlw) is an example that reproduces the problem.
> 
> ```cs
> var result = JsonSerializer.Serialize(new
> {
>     StringString = new Dictionary<string, string>
>     {
>         ["Key"] = "Value"
>     },
>     StringArray = new Dictionary<string, string[]>
>     {
>         ["Key"] = new []{ "Value" }
>     }
> }, options: new JsonSerializerOptions
> {
>     PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
>     DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
>     WriteIndented = true
> });
> 
> Console.WriteLine(result);
> /*
> {
>   "stringString": {
>     "key": "Value"
>   },
>   "stringArray": {
>     "Key": [
>       "Value"
>     ]
>   }
> }
> */
> ```
> 
> What is the code for the workaround?

We have encountered this exact issue as well. Fortunately it was only a few areas of our code base that were impacted, but it would be nice if there was a solution to this.
