### ISSUE TITLE
CoreCLR Crossgen Build Failure: Error generating PDB for System.Private.CoreLib.dll - No Native Image

### ISSUE THREAD

**Issue by alistairjevans** [dotnet/runtime#31851]
I'm doing a first-time build of the dotnet runtime on Windows (to work on libraries only), and I cannot get the coreclr build to run successfully. 

During the CrossgenCoreLib phase, I am getting the following error in the log file:

```
BUILD: "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\crossgen.exe" /nologo  /Platform_Assemblies_Paths "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\IL" /out "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll" "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\IL\System.Private.CoreLib.dll" 
Native image D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll generated successfully.
BUILD: "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\crossgen.exe" /nologo /Platform_Assemblies_Paths "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release" /CreatePdb "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\PDB" "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll" 
Error generating PDB for 'D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll': Couldn't find a native image. (0x80131C64)
Error: compilation failed for "D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll" (0x80131c64)
Loaded image 'D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll' (for input file 'D:\GitHub\dotnet\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll') is not a native image.
```

Apologies for having to raise an issue, but I have tried a number of things, and hope this is an obvious thing that is known internally, but there is no github issue for it yet. I imagine it's just something I have missed.

The only issue I can find that has a possibly similar problem is https://github.com/dotnet/runtime/issues/9910, but that is an ARM issue, and I am not building for ARM. Is the crossgen attempting to build ARM and failing for some reason? 

**Pre-reqs**
Build OS: Windows_NT
Arch: x64
VS Version: 16.4.4
CMake Version: 3.15.7
Python Version: 3.8.1

I have installed all Visual Studio components using the .vsconfig file in the solution root.
This includes the ARM build tools, as specified in the pre-requisites list.

The command I'm running to build is:
```
.\build -subsetCategory coreclr -c Release
```

The CoreCLR build completes successfully, with the following warnings:
```
    19>PGOMGR : warning PG0188: No .PGC files matching 'C:\Users\Alistair\.nuget\packages\optimization.windows_nt-x64.pgo.coreclr\99.99.99-master-20190716.1\data\clrjit!*.pgc' were found. [D:\GitHub\dotnet\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\jit\standalone\clrjit.vcxproj]
    27>PGOMGR : warning PG0188: No .PGC files matching 'C:\Users\Alistair\.nuget\packages\optimization.windows_nt-x64.pgo.coreclr\99.99.99-master-20190716.1\data\coreclr!*.pgc' were found. [D:\GitHub\dotnet\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj]
```

The System.Private.CoreLib build completes with no warnings.

The build then fails with the above errors (which are written to the log).

**Comment by AaronRobinsonMSFT** [comment]
@alistairjevans Are you still hitting this issue? I apologize for no one responding for so long. The build scripts have recently been rewritten so perhaps this was a transient issue. Can you please try again from tip?

**Comment by alistairjevans** [comment]
Hey @AaronRobinsonMSFT, no worries on the delay; I didn't chase because I knew you were working on getting the builds more stable.

Everything works now from tip, so I'll close.

Thanks
