### ISSUE TITLE
Linux ARM self contained HelloWorld application consumes 117Mb of RAM

### ISSUE THREAD

**Issue by EffectiveLabs** [dotnet/runtime#31859]
Hi,

We have a very simple netcoreapp3.1 

     static void Main(string[] args)
       {
            while (true)
            {
                Console.Clear();
                Console.WriteLine($"{DateTime.Now} - Hello World!");
                Thread.Sleep(5000);
            }
        }

It is published with the following command 
`dotnet publish --configuration Release --framework netcoreapp3.1 --runtime linux-arm --self-contained=true -p:PublishTrimmed=true`

When executed on Raspian or Yocto targets the process takes cca. 117 MB of RAM.

Do you have any hints or solutions for this problem?

Thank you!

**Comment by janvorli** [comment]
@EffectiveLabs is the size you are referring to the virtual memory or the resident set? If you dump the /proc/PID/status and look for VmSize nad VmRSS, you'll get these values. When I launch a simple test app on my Odroid UX4, I get VmSize 144352 kB and VmRSS 32372 kB.
The VmRSS is the real memory consumption, the VmSize represents only the virtual address space reserved.

**Comment by EffectiveLabs** [comment]
@janvorli  Thank's for you reply, you helped me to understand that the busybox top command available on my targets calculates %MEM as VSZ/MemTotal instead of RSS/MemTotal.
The issue is documented here https://unix.stackexchange.com/questions/44948/what-do-tops-mem-and-vsz-mean

So it's not dotnet core runtime issue. I'll close this one.
