### ISSUE TITLE
System.Data.Common.DbProviderFactoriesTests failing in CI 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#31868]
A number of tests are failing, using `GetFactoryWithDataRowTest` as the marker test to follow. The first build to demonstrate this was 509362

### Console Log Summary

Appears to be a simple test failure

```
    System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeNameTest [FAIL]
      System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
      Stack Trace:
        /_/src/libraries/System.Data.Common/src/System/Data/Common/DbProviderFactories.cs(184,0): at System.Data.Common.DbProviderFactories.GetFactoryInstance(Type providerFactoryClass)
        /_/src/libraries/System.Data.Common/src/System/Data/Common/DbProviderFactories.cs(69,0): at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
        /_/src/libraries/System.Data.Common/tests/System/Data/Common/DbProviderFactoriesTests.cs(199,0): at System.Data.Common.DbProviderFactoriesTests.RegisterSqlClientAndTestRegistration(Action registrationFunc)
        /_/src/libraries/System.Data.Common/tests/System/Data/Common/DbProviderFactoriesTests.cs(72,0): at System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeNameTest()
      System.ArgumentNullException : Value cannot be null. (Parameter 'factory')
      Stack Trace:
```

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#508988](https://dev.azure.com/dnceng/public/_build/results?buildId=508988)|Rolling|1|
|[#509362](https://dev.azure.com/dnceng/public/_build/results?buildId=509362)|Rolling|1|
|[#509595](https://dev.azure.com/dnceng/public/_build/results?buildId=509595)|Rolling|1|
|[#509747](https://dev.azure.com/dnceng/public/_build/results?buildId=509747)|Rolling|1|
|[#509802](https://dev.azure.com/dnceng/public/_build/results?buildId=509802)|Rolling|1|
|[#509865](https://dev.azure.com/dnceng/public/_build/results?buildId=509865)|Rolling|1|
|[#509985](https://dev.azure.com/dnceng/public/_build/results?buildId=509985)|Rolling|1|
### Configurations
- netcoreapp5.0-Linux-Release-arm64-CoreCLR_release-(Alpine.38.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-a45aeeb-20190620184035
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|
| --- | --- | --- | --- | --- |
|[#508988](https://dev.azure.com/dnceng/public/_build/results?buildId=508988)|Rolling|[console.fc1893ef.log](https://helix.dot.net/api/2019-06-17/jobs/5cb0b92b-d38b-4bfc-b9f9-25e8d6ee6527/workitems/System.Data.Common.Tests/files/console.fc1893ef.log)|||
|[#509362](https://dev.azure.com/dnceng/public/_build/results?buildId=509362)|Rolling|[console.62f42be5.log](https://helix.dot.net/api/2019-06-17/jobs/cb568d05-e0c9-4b5d-a292-1ac6dd5847a9/workitems/System.Data.Common.Tests/files/console.62f42be5.log)|||
|[#509595](https://dev.azure.com/dnceng/public/_build/results?buildId=509595)|Rolling|[console.29bc91e3.log](https://helix.dot.net/api/2019-06-17/jobs/ed130407-35ad-40cc-a9ef-24b9767b2a77/workitems/System.Data.Common.Tests/files/console.29bc91e3.log)|||
|[#509747](https://dev.azure.com/dnceng/public/_build/results?buildId=509747)|Rolling|[console.c8ef635c.log](https://helix.dot.net/api/2019-06-17/jobs/a0a5f1cc-7287-4194-b7ee-f9e14a6106c4/workitems/System.Data.Common.Tests/files/console.c8ef635c.log)|||
|[#509802](https://dev.azure.com/dnceng/public/_build/results?buildId=509802)|Rolling|[console.c09790cc.log](https://helix.dot.net/api/2019-06-17/jobs/56285f4d-9fe0-48a2-b2f3-3c1dc3dc7d68/workitems/System.Data.Common.Tests/files/console.c09790cc.log)|||
|[#509865](https://dev.azure.com/dnceng/public/_build/results?buildId=509865)|Rolling|[console.33be4e10.log](https://helix.dot.net/api/2019-06-17/jobs/62ed550e-0ce8-4fb9-85c2-fb4045ac2627/workitems/System.Data.Common.Tests/files/console.33be4e10.log)|||
|[#509985](https://dev.azure.com/dnceng/public/_build/results?buildId=509985)|Rolling|[console.b1b2ed3b.log](https://helix.dot.net/api/2019-06-17/jobs/f640dce9-ca94-48a9-a3e4-b2e5261dca45/workitems/System.Data.Common.Tests/files/console.b1b2ed3b.log)|||

**Comment by jaredpar** [comment]
@danmosemsft who owns the `DbProviderFactoriesTests` suite? It's failing 100% on ARM64 right now.

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/runtime/commit/4b4d7416393ee7ec13f976c441dc21e0d3eb69b2.

**Comment by jaredpar** [comment]
#31850

**Comment by ViktorHofer** [comment]
A commits links to its PR :)

**Comment by jaredpar** [comment]
@ViktorHofer correct. But specifying the commit SHA won't cause the PR to link back to the issue. Linking to the PR means it will in turn link to the issue. That way when you look at the PR you can see the issues that are relevant to the changes.

**Comment by ViktorHofer** [comment]
That makes perfect sense, thanks for letting me know :)
