### ISSUE TITLE
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests is failing in CI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#31870]
This is blocking our ARM64 runs. Using the `RoundtripManyObjectsInOneStream` test as a marker to follow the failure.

### Console Log Summary

Appears to be a simple test failure

```
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs(581,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects()+MoveNext()
        /_/src/libraries/Common/src/System/Collections/Generic/LargeArrayBuilder.SpeedOpt.cs(117,0): at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
        /_/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.Linq.cs(111,0): at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
        /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(18,0): at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs(81,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects_MemberData()

```

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#508988](https://dev.azure.com/dnceng/public/_build/results?buildId=508988)|Rolling|1|
|[#509362](https://dev.azure.com/dnceng/public/_build/results?buildId=509362)|Rolling|1|
|[#509595](https://dev.azure.com/dnceng/public/_build/results?buildId=509595)|Rolling|1|
|[#509747](https://dev.azure.com/dnceng/public/_build/results?buildId=509747)|Rolling|1|
|[#509802](https://dev.azure.com/dnceng/public/_build/results?buildId=509802)|Rolling|1|
|[#509865](https://dev.azure.com/dnceng/public/_build/results?buildId=509865)|Rolling|1|
|[#509985](https://dev.azure.com/dnceng/public/_build/results?buildId=509985)|Rolling|1|
### Configurations
- netcoreapp5.0-Linux-Release-arm64-CoreCLR_release-(Alpine.38.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-a45aeeb-20190620184035
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|
| --- | --- | --- | --- | --- |
|[#508988](https://dev.azure.com/dnceng/public/_build/results?buildId=508988)|Rolling|[console.e86a0bb8.log](https://helix.dot.net/api/2019-06-17/jobs/5cb0b92b-d38b-4bfc-b9f9-25e8d6ee6527/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.e86a0bb8.log)|||
|[#509362](https://dev.azure.com/dnceng/public/_build/results?buildId=509362)|Rolling|[console.64a09699.log](https://helix.dot.net/api/2019-06-17/jobs/cb568d05-e0c9-4b5d-a292-1ac6dd5847a9/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.64a09699.log)|||
|[#509595](https://dev.azure.com/dnceng/public/_build/results?buildId=509595)|Rolling|[console.efc052e0.log](https://helix.dot.net/api/2019-06-17/jobs/ed130407-35ad-40cc-a9ef-24b9767b2a77/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.efc052e0.log)|||
|[#509747](https://dev.azure.com/dnceng/public/_build/results?buildId=509747)|Rolling|[console.4d951fab.log](https://helix.dot.net/api/2019-06-17/jobs/a0a5f1cc-7287-4194-b7ee-f9e14a6106c4/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.4d951fab.log)|||
|[#509802](https://dev.azure.com/dnceng/public/_build/results?buildId=509802)|Rolling|[console.d6fd071b.log](https://helix.dot.net/api/2019-06-17/jobs/56285f4d-9fe0-48a2-b2f3-3c1dc3dc7d68/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.d6fd071b.log)|||
|[#509865](https://dev.azure.com/dnceng/public/_build/results?buildId=509865)|Rolling|[console.6a67a89c.log](https://helix.dot.net/api/2019-06-17/jobs/62ed550e-0ce8-4fb9-85c2-fb4045ac2627/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.6a67a89c.log)|||
|[#509985](https://dev.azure.com/dnceng/public/_build/results?buildId=509985)|Rolling|[console.1c97ea7d.log](https://helix.dot.net/api/2019-06-17/jobs/f640dce9-ca94-48a9-a3e4-b2e5261dca45/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.1c97ea7d.log)|||

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/runtime/pull/31850
