### ISSUE TITLE
Consider renaming CoreFx.Private.TestUtilities

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#31876]
We are called .NET Libraries Team 🤙 

cc @danmosemsft @stephentoub

**Comment by danmosemsft** [comment]
"Runtime" or "Libraries" might be fine.

**Comment by ViktorHofer** [comment]
The old name was chosen because we had to package that library and uploaded it to our private feeds. We aren't doing that anymore which means we probably want something simpler like TestUtilities.dll?

**Comment by danmosemsft** [comment]
SGTM
