### ISSUE TITLE
AdditionalBuildTargetFrameworks should include .NET Framework TargetFrameworks

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#31872]
>  However, you can build for more TargetFrameworks by setting AdditionalBuildTargetFrameworks property.

(from https://github.com/dotnet/runtime/issues/31823)

Can we change the config system so that .NET Framework TFMs - if set in the project - are built as well, IF the tooling to build is already restored? I don't see a reason why we would filter them out if the vertical is already restored.

This would make it easier to build and run tests on .NET Framework configurations.

cc @anipik @ericstj @safern

**Comment by ericstj** [comment]
Downside of this is that we currently require refpaths for this to work.  To get those you need to build the netfx vertical or allconfigurations.  I'm more inclined to just fix https://github.com/dotnet/runtime/issues/31844, then make VS build behave same as SDK (all configurations).

**Comment by ViktorHofer** [comment]
> then make VS build behave same as SDK (all configurations).

What if we change the default not just for VS so that a `dotnet build` on an individual projects builds all configurations as well? That would be the expected behavior that you get from the sdk by default.
