### ISSUE TITLE
Cannot set PrincipalPolicy

### ISSUE THREAD

**Issue by gomathip02** [dotnet/runtime#31889]
@mgnsm commented on [Fri Jan 31 2020](https://github.com/dotnet/wpf/issues/2489)

.NET Core Version: 3.1.101
Windows version: 16299.1625
Reproducible in .NET Framework 4.8?: No.

Calling `AppDomain.CurrentDomain.SetPrincipalPolicy` to specify a principal policy of `PrincipalPolicy.UnauthenticatedPrincipal` doesn't seem to work.

If I create a new WPF application using the default `WPF App (.NET Core)` template in Visual Studio 2019 16.4.3 and implement the `App.xaml.cs` class like this:

    public partial class App : Application
    {
        public App()
        {
            AppDomain.CurrentDomain.SetPrincipalPolicy(PrincipalPolicy.UnauthenticatedPrincipal);
            Debug.Assert(Thread.CurrentPrincipal != null); //works
            Debug.Assert(Thread.CurrentPrincipal.GetType() == typeof(GenericPrincipal)); //works
        }
    }

...and the `MainWindow.xaml.cs` class like this:

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Debug.Assert(Thread.CurrentPrincipal != null); //fails
        }
    }

...the assert in the window unexpectedly fails. 

How do I properly specify a principal policy and set the `Thread.CurrentPrincipal` property in a WPF application running on .NET Core?

**Comment by bartonjs** [comment]
Closing in favor of #31717
