### ISSUE TITLE
Official build and CI builds failed with CMake Warning due to build agents updated VS

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#31888]
Official builds are currently hitting: https://github.com/dotnet/runtime/issues/30845 because the build agents got updated to VS2019 16.4 and CMake is 3.15.1, we need 3.15.5 or later. 

I will disable WarnAsError for Windows in the official builds shortly. We should revert that when this is fixed. 

cc: @dotnet/runtime-infrastructure @MattGal

**Comment by jkoritzinsky** [comment]
This is showing up now on the runtime-live-build pipeline.

**Comment by robertpi** [comment]
Hello,

I'm trying to build the latest master locally on windows 10, Visual Studio VS 2019, 16.4.1 and I'm getting this error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB8065: Custom build for item "C:\code\dotnet\runtime\artifacts\obj\native\netcoreapp5.0-Windows_NT-Debug-x64\CMakeFiles\a61efa86ec94e068b992e83ccf5bfaea\INSTALL_force.rule" succeeded, but specified output "c:\code\dotnet\runtime\artifacts\obj\native\netcoreapp5.0-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [C:\code\dotnet\runtime\artifacts\obj\native\netcoreapp5.0-Windows_NT-Debug-x64\install.vcxproj] [C:\code\dotnet\runtime\src\libraries\Native\build-native.proj]
```

This seems to be the same error as #30845, but I have the code from the PRs in this pull request disabling warning as errors.

I don't have CMake installed, it's unclear whether this is still necessary. The instructions about building under windows, which where once here, seem to have been removed: https://github.com/dotnet/corefx/commit/81c91fab23b26592334ac6ff4bef34f102e3c3ce#diff-4b7d5829731d454157a0e13d9d46da42

**Comment by trylek** [comment]
@robertpi - I believe the updated build instructionsfor the consolidated runtime repo are at

https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md

https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md

and related. I'm not sure what PR you are referring to. I fixed the issue for the runtime-live-build pipeline with

https://github.com/dotnet/runtime/pull/31999

Please however note that this fix is specific to lab testing - it only modifies the yml scripts to pass around an extra parameter so it doesn't affect local builds. AFAIK our standard developer guidance is that building the dotnet/runtime repo requires CMake 3.15.5 or newer.

**Comment by robertpi** [comment]
It was just that CMake was missing. It builds fine with the latest cmake installed. Might be nice to have a link from the building docs to the requirements page, that's what confused me. Should I open a PR for that.

**Comment by ViktorHofer** [comment]
@robertpi we already document that in the following way:

1. The Readme.md links to the workflow instructions:

![image](https://user-images.githubusercontent.com/7412651/74336263-381fc880-4d9e-11ea-9654-0efdb4216a1b.png)

2. The workflow instructions link to the build requirements:

![image](https://user-images.githubusercontent.com/7412651/74336337-5ab1e180-4d9e-11ea-81c3-a4b11a4f97d3.png)
