### ISSUE TITLE
Add variant for Validator.TryValidateObject which provides all validation errors

### ISSUE THREAD

**Issue by jbe2277** [dotnet/runtime#31882]
The [Validator](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator?view=netcore-3.1) implementation stops collecting validation errors when some error is found. I need the implementation to collect all validation errors.

Extract of the current [Validator](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs) implementation. See both comments _We only proceed to Step..._ which show the problematic code path:
``` C#
// Step 1: Validate the object properties' validation attributes
var errors = new List<ValidationError>();
errors.AddRange(GetObjectPropertyValidationErrors(instance, validationContext, validateAllProperties, breakOnFirstError));
 
// We only proceed to Step 2 if there are no errors
if (errors.Any())
{
    return errors;
}
 
// Step 2: Validate the object's validation attributes
var attributes = _store.GetTypeValidationAttributes(validationContext);
errors.AddRange(GetValidationErrors(instance, validationContext, attributes, breakOnFirstError));
 
// We only proceed to Step 3 if there are no errors
if (errors.Any())
{
    return errors;
}
 
// Step 3: Test for IValidatableObject implementation
if (instance is IValidatableObject validatable)
{
    var results = validatable.Validate(validationContext);
    ...
```

**Idea:** Provide a new method overload with the additional flag `continueValidationOnError`:
``` C#
public static bool TryValidateObject (object instance, ValidationContext validationContext, 
    ICollection<ValidationResult> validationResults, bool validateAllProperties, 
    bool continueValidationOnError)
```

And adapt the implementation shown above with:
``` C#
// We only proceed to Step n if there are no errors
if (!continueValidationOnError && errors.Any())
{
    return errors;
}
```

**Comment by ajcvickers** [comment]
We have no plans to add additional functionality to data annotations.

**Comment by jbe2277** [comment]
#31400
