### ISSUE TITLE
Assert in DAC running the diagnostics repo tests on Checked/Debug runtime build

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#31897]
This assert in the DAC happens with SOS runs the below command. It is benign but causes the diagnostics repo's SOS tests to fail.

(lldb) clrstack -i

```
Assert failure(PID 24691 [0x00006073], Thread: 24691 [0x6073]): DAC coding error: instance size cannot be 0
     File: /home/mikem/runtime/src/coreclr/src/debug/daccess/dacfn.cpp Line: 385
```

**Comment by tommcdon** [comment]
Closing since the issue is 6+ months older.  Feel free to reactive or open a new issue.
