### ISSUE TITLE
Regex malfunction

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#31891]
This issue is ported from https://developercommunity.visualstudio.com/content/problem/689056/regular-expression-mulfunction.html

```C#
static string expression = @"(\n((BLOCK\s+)?[1-9][0-9]?(.| |)|())((?😦?!\n((BLOCK\s+)?[1-9][0-9]?(.\D| |)|()).)*)";

static string text = @"\n" +
@“1.FLT AREA       :  BOUNDED BY FLW POINTS\n” +
@"                     353022N1401012E 353013N1401002E\n" +
@"                     352926N1401029E 353001N1401050E\n" +
@"                     (AROUND ICHIHARA-SHI IN CHIBA)\n" +
@“2.NUMBER         : 1\n” +
@“3.CHARACTERISTICS: LEN/MAX 0.29M WID/MAX 0.29M WT/MAX 1.5KG\n” +
@"                   COLOR/WHITE\n" +
@“4.FLT TIME       : HJ”;

static void Main(string[] args)
{
    Regex regex = new Regex(expression, RegexOptions.Compiled);
    Match match = regex.Match(text);
}
```

regex suppose to match but it is not.

**Comment by danmosemsft** [comment]
Unfortunately I don't think it is possible to figure this out without knowing what the emoji represents or if someone can infer it. Really, the original bug report should have been simplified down to a smaller repro case.

https://www.unicode.org/emoji/charts/emoji-list.html#1f626

**Comment by am11** [comment]
😦 U+1F626 - frowning face with open mouth; https://emojipedia.org/frowning-face-with-open-mouth/

**Comment by tarekgh** [comment]
@am11 we need to know what is the shortcut characters that can create this emoji. 

@danmosemsft  I have asked on the original report https://developercommunity.visualstudio.com/content/problem/689056/regular-expression-mulfunction.html to get the emoji replacement characters. We can activate this issue when we get more info,

**Comment by danmosemsft** [comment]
@GrabYourPitchforks you're our emoji encoding expert. Can you infer what the original characters were here? We know the emoji is U+1F626....

**Comment by GrabYourPitchforks** [comment]
Emoji expert, eh?
My best guess is a colon followed by an o, but would need to sit down and study the regex syntax to figure out what that means.

**Comment by tarekgh** [comment]
I believe the characters have to include `)` to make the open and close parenthesis to balance.

**Comment by danmosemsft** [comment]
This isn't worth further investigation I think :)
