### ISSUE TITLE
PGO Instrumentation Broken on CoreCLR Build

### ISSUE THREAD

**Issue by brianrob** [dotnet/runtime#31905]
In the process of bringing up PGO training for the dotnet/runtime CoreCLR build, I've noticed that PGO instrumentation is broken on Linux.

Running this command:
```
./build.sh x64 release skiprestoreoptdata nopgooptimize pgoinstrument
```

results in this error:
```
Failed to get PGO data package path.
```

Without this functionality, we're unable to ship an optimized runtime for Linux.

**Comment by brianrob** [comment]
@jeffschwMSFT can you help find someone to look at this?  Thanks.

**Comment by jkoritzinsky** [comment]
I’m currently refactoring the CoreCLR build scripts at the moment. I can take a look at this.

**Comment by brianrob** [comment]
Thanks @jkoritzinsky.  Very much appreciate it.
