### ISSUE TITLE
[Question] Does the intrinsics SSE4.2 _mm_cmpestri is exposed somewhere ?

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/runtime#31914]
I am looking for the _mm_cmpestri instruction, available on SSE4.2 processors.
Can't find it on the Sse42 object...
@tannergooding ?

**Comment by Gnbrkm41** [comment]
It does not appear to exist yet. https://github.com/dotnet/coreclr/pull/20887 suggests that the APIs were left behind due to lack of better design.

**Comment by Gnbrkm41** [comment]
Related: https://github.com/dotnet/runtime/issues/957
