### ISSUE TITLE
how can I get the CPU usage in percent of my app ?

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#31921]
I want to get the CPU and Memory usage of my app in .net core,  for .net framework , I can use `PerformanceCounter` class, I have read a few [docs](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md) about the `EventCounter` class ,  but it seems not able to get the info from it.

**Comment by hoyosjs** [comment]
Do you want to use them programatically? Or just see them?

- To see them we have the [dotnet-counters global tool](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-counters-instructions.md).
- You can see some sample usage of the [diagnostics client library](https://github.com/dotnet/diagnostics/blob/f5dc05d18aa7d32faf29511ee98c6958ab7b3958/documentation/design-docs/diagnostics-client-library.md#L73).
- Using `EventListener` on [the RuntimeEventSource](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/System.Private.CoreLib/src/System/Diagnostics/Eventing/RuntimeEventSource.cs) you can do it in-proc. You can get an idea maybe starting on the [Listener](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener.enableevents?view=netcore-3.1#System_Diagnostics_Tracing_EventListener_EnableEvents_System_Diagnostics_Tracing_EventSource_System_Diagnostics_Tracing_EventLevel_)

Or have you tried this and still get no information back? What version of the dotnet runtime are you using in this case?

@sywhang @josalem 
cc @dotnet/dotnet-diag

**Comment by noahfalk** [comment]
There are also programmatic options using properties on System.Diagnostics.Process. https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.totalprocessortime?view=netcore-3.1

**Comment by John0King** [comment]
@hoyosjs 
I'm using .net core 3.1, And I want to use it in-proc.

> Using EventListener on the RuntimeEventSource you can do it in-proc. You can get an idea maybe starting on the Listener

The `RuntimeEventSource` is internal how do I use that ? Is there a sample ?    and does the `PerformaceCounter` work on Linux ?

**Comment by sywhang** [comment]
@John0King  You can use ```EventListener``` to subscribe to `System.Runtime` EventSource. Here is a sample ```EventListener``` implementation on how to do that: https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/eventcounters.md#sample-code

`PerformanceCounter` only works on Windows. `EventCounter` is the recommended cross-platform API.
