### ISSUE TITLE
OS specific files are not being shown correctly in VS Solution Explorer

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#31935]
@Anipik @ericstj @safern @ViktorHofer 

Anirudh and I noticed this yesterday.

In my Windows machine, I rebased my enlistment to the latest changes and built everything successfully.

I have two repro examples:

### 1)

- Open this solution in VS: `runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.sln`.
- The `System.Private.CoreLib.Shared` project is not showing the Windows-specific files. For example, if you expand the `System\IO` folders in the Solution Explorer, I used to be able to see `Path.Windows.cs`, but it's not there anymore. I only see `Path.cs`.

### 2)

- Open this solution in VS: `runtime\src\libraries\System.IO.FileSystem\System.IO.FileSystem.sln`
- If you expand the `src\System\IO` folders in the Solution Explorer, I used to be able to see `FileSystem.Win32.cs` and `FileSystem.Windows.cs` (since I'm in my Windows machine). Now, I cannot see those files.
- Instead, I'm unexpectedly only seeing `FileSystem.Unix.cs`, which I couldn't see before in the Solution Explorer (unless I opened the solution in Visual Studio Code in my Ubuntu machine).

**Comment by Anipik** [comment]
VS is showing the files corresponding to the first targetFramework in TargetFrameworks list.

Related Issue https://github.com/dotnet/runtime/issues/31902

**Comment by carlossanlop** [comment]
Another case:

- Open this solution in VS: `runtime\src\libraries\System.IO.FileSystem.AccessControl\System.IO.FileSystem.AccessControl.sln`
- Even though the `src\System.IO.FileSystem.AccessControl.csproj` file is including a bunch of cs files (from Common, System.IO, System.Security.AccessControl, etc.), only the ones in `System.Diagnostics` are showing up.

**Comment by Anipik** [comment]
Thats expected, because our first target is netstandard and the missing files are windows assets. I will put up a pr to fix this

**Comment by carlossanlop** [comment]
Thanks @Anipik. Is there anything I can do in the meanwhile as a temporary workaround?

**Comment by Anipik** [comment]
yes the workaound is make the first targetFramework in targetFrameworks as $(NetCoreAppCurrent)-WindowsNT

**Comment by carlossanlop** [comment]
Nice! Thanks. Out of curiosity, why did that work?

**Comment by carlossanlop** [comment]
Thanks @Anipik for working on this!

**Comment by Anipik** [comment]
no worries. https://github.com/dotnet/runtime/pull/32312 would fix all the other troubles like showing all the files, and even give us  intellsenceand navigation for all the files
