### ISSUE TITLE
Add CLR GC heap fragmentation counter

### ISSUE THREAD

**Issue by preetamshetty1** [dotnet/runtime#31951]
Linking back from https://github.com/dotnet/runtime/issues/1099. 

It would be good to provide the fragmentation statistics per generation to go with the heap size to know true usage.

**Comment by davidfowl** [comment]
cc @Maoni0

**Comment by Maoni0** [comment]
if you could describe how you would use the per gen frag stats that'd be great. I'm not opposed to providing more diagnostics data, just want to make sure it's in a usable format.

**Comment by preetamshetty1** [comment]
We traditionally watch heap sizes to track process usage for managed components. Cases wherein processes have a misbehaved by pinning or fragmenting the LOH are not something we can triage without expansive GC traces and/or crash dumps. This gives us the ability to map these issues quickly. Lastly, we trend usage over long periods of time as enhancements/regressions occur, tracking how we actively work towards better health relies on a signal like a performance counter.

**Comment by Maoni0** [comment]
ahh I see; this is most for LOH. sounds reasonable. are you looking to add this as a dotnet-counter?

**Comment by davidfowl** [comment]
Should be exposed as an event counter (my 2c)

**Comment by preetamshetty1** [comment]
A performance counter would be great. I had another issue open to make sure we had performance counters vs. event counters. Are performance counters still on the table here?

**Comment by davidfowl** [comment]
We’ve moved away from them because they are windows specific and require admin privileges to install. Event counters are the new state of the art. They also flow as ETW events on windows so you can get that counters via anything collecting etw events

**Comment by tommcdon** [comment]
Dependent on https://github.com/dotnet/runtime/issues/34648

**Comment by sywhang** [comment]
Closed via #38851
