### ISSUE TITLE
JsonSerializer.Deserialize fails silently in default camelCasing

### ISSUE THREAD

**Issue by bigteejay** [dotnet/runtime#31969]
Reproduce...
```

using System;
using System.Text.Json;
				
public class Program
{
	public static void Main()
	{
		int id = 9;
		
		string brokenStr = "{\"id\": " + id + "}";
		var broken = JsonSerializer.Deserialize<User>(brokenStr);
		Console.WriteLine($"User ID: {broken.Id}, Correct: {id == broken.Id}");

		string workingStr = "{\"Id\": " + id + "}";  // Capital "I" in "id"
		var working = JsonSerializer.Deserialize<User>(workingStr);
		Console.WriteLine($"User ID: {working.Id}, Correct: {id == working.Id}");
	}
}


public class User {
	public int Id { get; set; }
}
```

I didn't not expect the (de)serializer to be case sensitive (especially to not assume the default camelCase format that seems to be the default otherwise).

**Comment by bigteejay** [comment]
[Related SO post.](https://stackoverflow.com/a/60123509/3246805)

These [existing](https://github.com/dotnet/runtime/issues/29577#issuecomment-504032913) [issues](https://github.com/dotnet/runtime/issues/29063), lead me to the [docs](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/docs/SerializerProgrammingModel.md#property-name-feature), which has a solution for the issue

Leaving all this up for search results fodder for others.

**Comment by ahsonkhan** [comment]
This official docs page provides the relevant details on what things are different and how to get the camel case behavior:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#table-of-differences-between-newtonsoftjson-and-systemtextjson
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#use-camel-case-for-all-json-property-names
