### ISSUE TITLE
GenerateReferenceSource instructions are outdated

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#31965]
Following https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/updating-ref-source.md fails with error:
```
  The assembly field is required.
  Specify --help for a list of available options and commands.
D:\runtime\src\libraries\Directory.Build.targets(143,5): error MSB3073: The command ""D:\runtime\.dotnet\dotnet.exe" "C:\Users\jkotas\.nuget\packages\microsoft.dotnet.genapi\5.0.0-beta.20105.2\build\\..\tools\netcoreapp2.1\Microsoft.DotNet.GenAPI.dll" "" --lib-path "D:\runtime\artifacts\bin\ref" --out "D:\runtime\src\libraries\System.Runtime\ref\System.Runtime.cs" --exclude-attributes-list "D:\runtime\eng\DefaultGenApiDocIds.txt" --header-file "D:\runtime\eng\LicenseHeader.txt" --lang-version "latest"" exited with code 1. [D:\runtime\src\libraries\System.Runtime\ref\System.Runtime.csproj]
```

@Anipik I believe that this fallout from #1787. Could you please take a look?

Among other things, I believe that these instructions should be updated to use Configuration instead of ConfigurationGroup.

**Comment by vcsjones** [comment]
Supposedly the original instructions will work again when the PR for https://github.com/dotnet/runtime/issues/31866#issuecomment-583108721 is merged?

**Comment by jkotas** [comment]
Also:
- coreclr/corefx should be replaced with dotnet/runtime in the instructions
- ConfigurationGroup should be replace with just Configuration

**Comment by ericstj** [comment]
@Anipik can you update the docs?

**Comment by Anipik** [comment]
Documentation is mostly up-todate with this PR.
- ConfigurationGroup has been removed 
- GenerateReferenceSource instructions are up to date.
- Build Instructions are upto date.

There are some instances of corefx and coreclr left, i can remove that as well.

 https://github.com/dotnet/runtime/pull/32062  updated the docs
