### ISSUE TITLE
coreclr_create_delegate cannot load internal class function

### ISSUE THREAD

**Issue by josephsmeng** [dotnet/runtime#31973]
From samples of [HostWithCoreClrHost ](https://github.com/dotnet/samples/tree/master/core/hosting/HostWithCoreClrHost/src)

if we add the ManagedWorker with an internal class which looks like this
```c#
namespace ManagedLibrary
{
    // Sample managed code for the host to call
    public class ManagedWorker
    {
        public class Internal
        {
           public static void Fun()
           {
              // this internal function should also 
              // can be loaded by coreclr_create_delegate 
           }
        }
    }
}
```
and load the `Internal.Fun` funtion in C++
```c++
   hr = createManagedDelegate(
            hostHandle,
            domainId,
            "ManagedLibrary, Version=1.0.0.0",
            "ManagedLibrary.ManagedWorker+Internal", //<-- the real&right C# class name
            "Fun",
            (void**)&anOtherDelegate);
```
or load this funtion in C++ like this 
```c++
   hr = createManagedDelegate(
            hostHandle,
            domainId,
            "ManagedLibrary, Version=1.0.0.0",
            "ManagedLibrary.ManagedWorker.Internal", //<-- the frustrated tried name
            "Fun",
            (void**)&anOtherDelegate);
```
both failed to working

**Comment by janvorli** [comment]
What is the `hr` that you are getting?

**Comment by josephsmeng** [comment]
`coreclr_create_delegate failed - status: 0x80131522`

**Comment by jeffschwMSFT** [comment]
@elinor-fung @vitek-karas

**Comment by vitek-karas** [comment]
While we're looking into the issue in this case...
Did you look at the other sample of hosting CoreCLR through the hostfxr? https://github.com/dotnet/samples/tree/master/core/hosting/HostWithHostFxr

This should be much easier to setup than direct hosting of coreclr and I verified that the nested type works in this case just fine.

**Comment by vitek-karas** [comment]
As far as I can tell nested types will simply not work via `coreclr_create_delegate`. The code eventually gets into `ClassLoader::GetClassValue` which calls `IsNested`:
https://github.com/dotnet/runtime/blob/084dd1a5aae0fbe6ed4f9164ac4ee1c5f0b2398f/src/coreclr/src/vm/clsload.cpp#L825

The important input is the `NameHandle` which in this case is initialized from namespace and type name and thus all other fields are left null/empty:
https://github.com/dotnet/runtime/blob/084dd1a5aae0fbe6ed4f9164ac4ee1c5f0b2398f/src/coreclr/src/vm/clsload.hpp#L154-L165

And so the `IsNested` will always return `FALSE`:
https://github.com/dotnet/runtime/blob/084dd1a5aae0fbe6ed4f9164ac4ee1c5f0b2398f/src/coreclr/src/vm/clsload.cpp#L773-L784

@elinor-fung can you please double check this?

**Comment by elinor-fung** [comment]
Yes, that is what I see as well - I came here to write up exactly the same findings. `coreclr_create_delegate` (and anything else going through `ClassLoader::LoadTypeByNameThrowing`) does not work with nested types due to what @vitek-karas mentioned above.

**Comment by vitek-karas** [comment]
Given that the new hosting APIs (hostfxr based) do support this scenario and that we want to in general steer users away from the direct coreclr hosting (calling into coreclr.dll directly) I don't think we should try to improve the behavior of `coreclr_create_delegate`.

**Comment by josephsmeng** [comment]
@vitek-karas yep, I did try to use hostfxr, but honestly speaking, I do not choose hostfxr API for reason, which right now hostfxr cannot be static linked, and must be placed with specified folder structure, therefore make the repacked embedded application looks odd.

**Comment by josephsmeng** [comment]
and if you did make your decision for not  improve the behavior of `coreclr_create_delegate`  I think it would be ok for me right now, thanks for your help.

**Comment by jkotas** [comment]
Related issue: https://github.com/dotnet/runtime/issues/12040

It is intentional that coreclr_create_delegate handles just the simple case of static methods.
