### ISSUE TITLE
[Api Proposal] Generic Convert.ChangeType

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#31987]
Rather than boxing back to object and then having to cast to type; it would be good to have a change type that returns the type:

#### Proposed API

```csharp
partial class Convert
{
    [return: NotNullIfNotNull("value")]
    public static T? ChangeType<T>(object? value);
    
    [return: NotNullIfNotNull("value")]
    public static T? ChangeType<T>(object? value, IFormatProvider? provider);
}
```

#### Questions

Not sure on nullable return type for structs?

**Comment by EgorBo** [comment]
If we make ` object? ChangeType(object? value, TypeCode typeCode)` inlineable Jit should be able to eliminate the intermediate boxing I guess. Isn't `typeCode` a constant in most use-cases?

**Comment by benaadams** [comment]
`public static object? ChangeType(object? value, Type conversionType)` is more likely the called overload, and [then it has to do a look up to get the typecode](https://github.com/dotnet/runtime/blob/3b72a4d7013abd36b0f2e145f44df85c43fc83aa/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L287-L352) falling through a bunch of `if` tests.

**Comment by benaadams** [comment]
Then when you use it in the generic as well as reboxing the output you then have to cast it to the type
e..g
```csharp
T value = (T)Convert.ChangeType(inputValue, typeof(T));
```

**Comment by EgorBo** [comment]
> `[then it has to do a look up to get the typecode](https://github.com/dotnet/runtime/blob/3b72a4d7013abd36b0f2e145f44df85c43fc83aa/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L287-L352) falling through a bunch of `if` tests.

yeah but if typecode is a const -- all those `ifs` will be easily eliminated 🙂

**Comment by EgorBo** [comment]
> Then when you use it in the generic as well as reboxing the output you then have to cast it to the type
> e..g
> 
> ```cs
> T value = (T)Convert.ChangeType(inputValue, typeof(T));
> ```
Jit eliminates boxing for `(T)(object)varOfT`, see https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4aNYgGYGZBgGEGAbxoMdDbboDaAKXEYA4jBEwo4sAAoMATw4wIAMzvixASjQMnLu6ePt4Auvo6igwAKgAiuBgMALIAPNFMUGB+cQkAfHbpmf7eEZqlusoA7AwF8RjedhDAAFYwYPUYstQVAL40PUA=

**Comment by benaadams** [comment]
As a developer/user would I prefer to write:
```csharp
T value = (T)Convert.ChangeType(inputValue, typeof(T));
```
Or
```csharp
T value = Convert.ChangeType<T>(inputValue);
```
An the implementation of the second done via generics could be more efficient than the first using type?

**Comment by nickwilsonr** [comment]
> As a developer/user would I prefer to write:
> 
> ```cs
> T value = (T)Convert.ChangeType(inputValue, typeof(T));
> ```
> 
> Or
> 
> ```cs
> T value = Convert.ChangeType<T>(inputValue);
> ```
> 
> An the implementation of the second done via generics could be more efficient than the first using type?

I second this request.. It would be much better/cleaner.

**Comment by redknightlois** [comment]
Is there any visibility on availability? As you know I usually abuse generic types with the purpose of code generation (performance) and the ability to convert numerical types from `TSource` to `TDestination` like `int` to `long` where they are hidden inside generic code would be very useful if the JIT picks up the idiom. 

This is one example where it actually simplify a lot since I know `TValueType` is a numeric type (just dont know why type yet).
![image](https://user-images.githubusercontent.com/1045411/169888359-69ac0178-9bb2-4113-9350-d038d41c94db.png)

So now I had to implement something like this:

```
long value = TypesHelper<TValueType, long>(currentType);
if ( !comparer.Compare(longValue, resultX))
     continue
```
with a quite nasty code for `TypesHelper`.

**Comment by dakersnar** [comment]
After discussion with @tannergooding, I don't think this is an API we are considering adding to the BCL at this time.
