### ISSUE TITLE
`Vector.tt` template does not seem to generate as part of `src/coreclr/build.cmd` script

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#31980]
Looking at `System.Private.CoreLib.Shared.Projitems` it suggests that the code generation is supposed to happen during build, however it does not appear to happen as part of `src/coreclr/build.cmd`. Do I need to pass in an extra flag / etc to make this happen?
https://github.com/dotnet/runtime/blob/850b4a23e513c9d133bad008fdf1058d77ff877c/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L1041-L1049

Additionally, I cannot seem to generate code by right-clicking the template file in VS, as there's no `Run custom tool` option which runs the generation tool:
![image](https://user-images.githubusercontent.com/42944058/74091158-f0781300-4af7-11ea-8a63-8043210fd04d.png)

Under normal circumstances it should be present under "Exclude from project".
![image](https://user-images.githubusercontent.com/42944058/74091167-084f9700-4af8-11ea-949b-1f1e4ce372f4.png)

I'm using VS2019 16.5 P2.

**Comment by Gnbrkm41** [comment]
As a workaround I copied the template to a new project, done the generation then copied the changes over.

**Comment by BruceForstall** [comment]
@tannergooding

**Comment by tannergooding** [comment]
As far as I know this is an issue with T4 templates and indirect inclusion (such as is done with shared projects). I don't think its something we can readily fix on our end.

**Comment by tannergooding** [comment]
Actually, looks like this is because the `T4 Service` guid was stripped at some point. We should have an entry such as the following somewhere which tells VS to load and enable that support:
```
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
```

**Comment by tannergooding** [comment]
@ViktorHofer, @safern. Do either of you know when/why those were stripped?

**Comment by tannergooding** [comment]
Looks like it was stripped sometime during the repo consolidation as it exists in the release/3.1.1 tag: https://github.com/dotnet/coreclr/blob/v3.1.1/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L452

**Comment by tannergooding** [comment]
Looks like it was stripped as part of https://github.com/dotnet/runtime/pull/244

**Comment by ViktorHofer** [comment]
That was a mistake from my side. Let me add that back.

**Comment by tannergooding** [comment]
Thanks @ViktorHofer
