### ISSUE TITLE
Exception.TargetSite confusion

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#31998]
The summary of `Exception.TargetSite` reads: `Gets the method that throws the current exception.`

However it's not updated when an exception that was originally thrown in A, is thrown again in B if the `TargetSite` was examined before throwing it again.

Example:
```cs
    static void A() => throw new InvalidOperationException();
    static void B() 
    {
        try 
        {
            
            try 
            {
                A();
            }
            catch(Exception ex)
            {
                // Remove this examination to read B() instead.
                Console.WriteLine(ex.TargetSite);
                throw ex;
            }
        }
        catch (Exception x) 
        {
            Console.WriteLine(x.TargetSite);
        }
    }
```

The exception from B shows both `TargetSite` reads to be `A()`.
Removing the examination before `throw ex` causes the remaining WriteLine to be correct. 
Shouldn't `TargetSite` follow the behavior of `StackTrace` and always update?

**Comment by danmosemsft** [comment]
For what its worth, I see the same behavior on .NET Framework 4.8.
