### ISSUE TITLE
Api proposal: BroadcastChannel<T>

### ISSUE THREAD

**Issue by aL3891** [dotnet/runtime#31992]
I've been really addicted to `Channel<T>` lately, it's just so gosh darn useful with its async enumerable support. One thing i've been missing though is the ability to have multiple listeners on a channel that each get all messages. In our system I’ve created a `BroadcastChannel<T>` that is comprised of one input channel and several subscription channels. 

My use case is very focused towards async enumerable and grpc streams, tapping into the automatic cancelation token management of those, witch is why it returns IAsyncEnumerables instead of channel readers, but perhaps there is a more elegant way to solve that. The subscription/unsubscription channels is meant to reduce the needs for locks/collection snapshots but maybe that's not needed in a more general case. We un/subscribe relatively unfrequently compared to how many items are passed though

Anyway i thought i'd check if there is any interest in something like this at all, or if there is a better way to do it.

    public class BroadcastChannel<T> : IDisposable
    {
        Channel<T> publishChannel;
        private ConcurrentQueue<Channel<T>> subscribtions;
        private ConcurrentQueue<Channel<T>> unsubscribtions;
        List<Channel<T>> listeners = new List<Channel<T>>();

        public BroadcastChannel()
        {
            publishChannel = Channel.CreateUnbounded<T>();
            subscribtions = new ConcurrentQueue<Channel<T>>();
            unsubscribtions = new ConcurrentQueue<Channel<T>>();
            _ = Run();
        }

        public void Publish( T item )
        {
            publishChannel.Writer.TryWrite( item );
        }

        async Task Run()
        {
            await foreach( var item in publishChannel.Reader.ReadAllAsync() )
            {
                while( subscribtions.TryDequeue( out var i ) )
                {
                    listeners.Add( i );
                }

                while( unsubscribtions.TryDequeue( out var i ) )
                {
                    listeners.Remove( i );
                }

                for( int i = 0; i < listeners.Count; i++ )
                {
                    listeners[i].Writer.TryWrite( item );
                }
            }
        }

        public async IAsyncEnumerable<T> Subscribe( [EnumeratorCancellation]CancellationToken cancellationToken = default )
        {
            var subscriber = Channel.CreateUnbounded<T>();
            subscribtions.Enqueue( subscriber );

            try
            {
                await foreach( var item in subscriber.Reader.ReadAllAsync( cancellationToken ) )
                {
                    yield return item;
                }
            }
            finally
            {
                subscriber.Writer.Complete();
                unsubscribtions.Enqueue( subscriber );
            }
        }

        public void Dispose()
        {
            publishChannel.Writer.Complete();
        }
    }

**Comment by aL3891** [comment]
Just to elaborate on the cancelation token/ grpc bit. Essentially i have a grpc request that returns a stream and what we want is to create a channel/subscription for that when the request comes in and them close the channel when the grpc stream stops. 

So in other words, my goal is to close the [subscription] channel when enumeration of the async enumerable is cancelled. 

Come to think about it, this concept on it's own might be useful, perhaps as an argument to ReadAllAsync or a similar method, just thinking out loud here

**Comment by aL3891** [comment]
Ok, another prototype, this time trying to separate the concepts above by having the Channel part and the AsyncEnumerable-that-closes-the-channel part as two separate things.

I'm still a little unhappy with exposing the entire channel when subscribing, not just the reader part, but i suppose it doesnt matter much.. likewise its a little unfortunate that there is no way to check if a channelwriter is closed (or is there?) so i have to check the reader, but again i suppose it doesnt matter much

    public class BroadcastChannel2<T>
    {
        private Channel<T> publishChannel = Channel.CreateUnbounded<T>();
        private ConcurrentQueue<Channel<T>> subscribtions = new ConcurrentQueue<Channel<T>>();
        private List<Channel<T>> listeners = new List<Channel<T>>();

        public BroadcastChannel2()
        {
            _ = Run();
        }

        public ChannelWriter<T> Writer()
        {
            return publishChannel.Writer;
        }

        async Task Run()
        {
            List<Channel<T>> unsubscribtions = null;
            await foreach( var item in publishChannel.Reader.ReadAllAsync() )
            {
                while( subscribtions.TryDequeue( out var i ) )
                {
                    listeners.Add( i );
                }

                for( int i = 0; i < listeners.Count; i++ )
                {
                    if( listeners[i].Reader.Completion.IsCompleted )
                    {
                        if( unsubscribtions == null )
                            unsubscribtions = new List<Channel<T>>();
                        unsubscribtions.Add( listeners[i] );
                    }
                    else
                        listeners[i].Writer.TryWrite( item );
                }

                if( unsubscribtions != null )
                {
                    for( int i = 0; i < unsubscribtions.Count; i++ )
                    {
                        listeners.Remove( unsubscribtions[i] );
                    }
                    unsubscribtions = null;
                }
            }
        }

        public Channel<T> Subscribe()
        {
            var subscriber = Channel.CreateUnbounded<T>();
            subscribtions.Enqueue( subscriber );
            return subscriber;
        }
    }

    public static class ChannelExtensions
    {
        public static  async IAsyncEnumerable<T> ReadAllAndCompleteAsync<T>( Channel<T> channel, [EnumeratorCancellation]CancellationToken cancellationToken = default )
        {
            try
            {
                await foreach( var item in channel.Reader.ReadAllAsync( cancellationToken ) )
                {
                    yield return item;
                }
            }
            finally
            {
                channel.Writer.Complete();
            }
        }
    }

**Comment by aL3891** [comment]
Actually perhaps its better to pass in the source/subscription channels to the constructor/subscribe method, that way the caller can configure them the way they like.

It would be nice to be able to pass in just the reader/writer and not a whole channel though

**Comment by stephentoub** [comment]
Thanks, @aL3891.  I can see why something like this could be useful in some scenarios, but I don't think it's going to be general-purpose enough to warrant us including it "in the box" (we shipped a `BroadcastBlock` with the dataflow library, and we didn't see it get a lot of use).  If you've come up with a design you like, I'd encourage you to publish it for others to use.  If it proves to be super useful, we could re-evaluate pulling it or something like it in.  Thanks!
