### ISSUE TITLE
Thread.GetCurrentProcessorId may return wrong value if HAVE_SCHED_GETCPU is not set

### ISSUE THREAD

**Issue by ayende** [dotnet/runtime#31995]
If `HAVE_SCHED_GETCPU` is not set, then `GetCurrentProcessorNumber` will return 0.

https://github.com/dotnet/runtime/blob/fcd862e06413a000f9cafa9d2f359226c60b9b42/src/coreclr/src/gc/unix/gcenv.unix.cpp#L481

However, the code here assume that we'll get -1, which we won't. See:

https://github.com/dotnet/runtime/blob/aedf8f52006619ef5d4eca65d79f42cc4b7bc402/src/coreclr/src/System.Private.CoreLib/src/System/Threading/ProcessorIdCache.cs#L35

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by VSadov** [comment]
This is the helper used by GC. Need to check what API we use here. 
I think I have seen ‘-1’ returned on OSX.

**Comment by danmosemsft** [comment]
This one? There are several functions with this name.

https://github.com/dotnet/runtime/blob/1c9af5ae859c03b36bfbb663d42bb166e880ce3b/src/coreclr/src/pal/src/misc/sysinfo.cpp#L489

**Comment by janvorli** [comment]
It should not matter what we return. The GCToOSInterface::GetCurrentProcessorNumber() should never be called if GCToOSInterface::CanGetCurrentProcessorNumber() returns false. If we don't honor that somewhere, it is a bug.

**Comment by jkotas** [comment]
Maybe add a comment and/or assert to make this clear?

**Comment by janvorli** [comment]
We actually have such an assert in the src/vm/gcenv.os.cpp and src/gc/windows/gcenv.windows.cpp versions of this function, only the standalone Unix version is missing it. It would be good to add it there too.

**Comment by jkotas** [comment]
#32033
