### ISSUE TITLE
`"src/coreclr/build.cmd" -checked` does not generate coreclr `nupkg`s

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#32001]
https://github.com/dotnet/runtime/blob/master/docs/workflow/using-dotnet-cli.md states that nupkg files should be present under `artifacts/bin/coreclr/[os].[arch].[flavour]` but no matter how many times I run it the nupkgs aren't generated. The folder does exist but it is completely empty. Same thing with different flavours. Am I supposed to provide extra arguments for this to happen, or is it an old document?

cc @EgorBo - Not sure if this is because disasmo uses a similar approach, but disasmo fails to build the project with error `NU1102`, saying something on the line of "cannot find package Microsoft.NETCore.App.Runtime.win-x64 of version = 5.0.0-alpha.1.20103.10" and another for WindowsDesktop... package. Do you have any comments on it?

**Comment by jkoritzinsky** [comment]
That documentation is out of date. You’ll find the packages under in artifacts/packages instead of artifacts/bin/coreclr.

I’m working on some workflow changes so I’ll update these docs.

**Comment by Gnbrkm41** [comment]
Has this been addressed? It appears that the documents seem to refer to existing paths / packages now.

**Comment by jkoritzinsky** [comment]
I believe so.
