### ISSUE TITLE
Access violation in [uwp] coreclr / x64

### ISSUE THREAD

**Issue by jtorjo** [dotnet/runtime#32004]
This was happening while I was testing my app, which using win2d/directx heavily. I can't reproduce it, but here are the events from Event viewer:

Event 1:

	Application: phoatawe.uwp.exe
	CoreCLR Version: 4.6.27902.3
	Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF9209F5AF3 (00007FF920850000) with exit code c0000005.

Event 2:

	Faulting application name: phoatawe.uwp.exe, version: 2.5.54.0, time stamp: 0x5d36223e
	Faulting module name: CoreCLR.dll, version: 4.6.27902.3, time stamp: 0x5d1bcbcd
	Exception code: 0xc0000005
	Fault offset: 0x00000000001a5af3
	Faulting process id: 0x4618
	Faulting application start time: 0x01d5df9bbc5c31aa
	Faulting application path: C:\Program Files\WindowsApps\CODEITRIGHTSRL.Phot-Awe_2.5.61.0_x64__y89h99n7awf44\phoatawe.uwp.exe
	Faulting module path: C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.2.2_2.2.27902.3_x64__8wekyb3d8bbwe\CoreCLR.dll
	Report Id: c84aee73-2ab5-476f-8f96-16be0a720f07
	Faulting package full name: CODEITRIGHTSRL.Phot-Awe_2.5.61.0_x64__y89h99n7awf44
	Faulting package-relative application ID: App

Event 3:

	Faulting application name: phoatawe.uwp.exe, version: 2.5.54.0, time stamp: 0x5d36223e
	Faulting module name: CoreCLR.dll, version: 4.6.27902.3, time stamp: 0x5d1bcbcd
	Exception code: 0xc0000005
	Fault offset: 0x00000000001a5af3
	Faulting process id: 0x4618
	Faulting application start time: 0x01d5df9bbc5c31aa
	Faulting application path: C:\Program Files\WindowsApps\CODEITRIGHTSRL.Phot-Awe_2.5.61.0_x64__y89h99n7awf44\phoatawe.uwp.exe
	Faulting module path: C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.2.2_2.2.27902.3_x64__8wekyb3d8bbwe\CoreCLR.dll
	Report Id: c84aee73-2ab5-476f-8f96-16be0a720f07
	Faulting package full name: CODEITRIGHTSRL.Phot-Awe_2.5.61.0_x64__y89h99n7awf44
	Faulting package-relative application ID: App

Event 4:

	Fault bucket 1278275398152184154, type 5
	Event Name: MoAppCrash
	Response: Not available
	Cab Id: 0

	Problem signature:
	P1: CODEITRIGHTSRL.Phot-Awe_2.5.61.0_x64__y89h99n7awf44
	P2: praid:App
	P3: 2.5.54.0
	P4: 5d36223e
	P5: CoreCLR.dll
	P6: 4.6.27902.3
	P7: 5d1bcbcd
	P8: c0000005
	P9: 00000000001a5af3
	P10:

**Comment by GrabYourPitchforks** [comment]
@jkotas Do you suppose this report is actionable by us? I don't see this crash report in Watson, so things like the stack trace are no longer available. It's possible the data was purged given how long it has been.

**Comment by jkotas** [comment]
@tommcdon How would you like to route this? Should we delete area-UWP since it is not actionable in this repo?

**Comment by tommcdon** [comment]
Moved this issue to internally tracked bug 1174100
