### ISSUE TITLE
SocketsHttpHandler: suppress follow redirect just for a single request 

### ISSUE THREAD

**Issue by Zetanova** [dotnet/runtime#32026]
If AllowAutoRedirect of `System.Net.Http.SocketsHttpHandler` is enabled,
it will add the handler `System.Net.Http.RedirectHandler` to the chain.
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L316

The `RedirectHandler` class could react on a WellKnownFlag in HttpRequestMessage.Properties 
to disable/suppress redirection for a single request.

**Comment by alnikola** [comment]
Could you please provide more context for this proposal? What is the scenario requiring such redirect suppression?

**Comment by Zetanova** [comment]
Currently there is no option for a TypedHttpClient to control the behaivor of the nested HttpClient for redirects. Sometimes the "location" header value is the result. An example would be an Auth-Redirect to an external SAO endpoint. 

The current workaround would be to disable auto redirect and implement the follow-redirect in user code and try to execute it after every request.

**Comment by karelz** [comment]
Triage:
We don't see this as common scenario. Given that there are workarounds -- either handle redirects manually all the time, or use 2 different HttpClient instances (one with redirects and one without), we think it is ok not to add such API.

**Comment by shravan2x** [comment]
Adding myself to this thread since I faced this issue too.
