### ISSUE TITLE
Installing through snap fails to create symlink

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/runtime#3203]
@tristan957 commented on [Wed Jun 06 2018](https://github.com/dotnet/core/issues/1667)

I tried to run the `dotnet` tool. Ended having to call it like this:

```
dotnet-sdk.dotnet help
ln: failed to create symbolic link '/var/snap/dotnet-sdk/18/Microsoft.NETCore.App/2.1.0': No such file or directory```

I installed it through snap using the commands in the README on Solus

**Comment by anirugu** [comment]
Same issue is happening in Ubuntu 20.04 for .net  core 5.

**Comment by tristan957** [comment]
@anirugu refer to previous comments for a workaround

**Comment by JackTiber** [comment]
Adding on that this is not working for Ubuntu 20.04 fresh install, using the stable channel to install the 3.1 SDK. Happy to alias the command, but would definitely be nice to see that during the install rather than having to search for this issue.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.

**Comment by YunusOzdemirr** [comment]
i have same issue i try the remove dotnet but i cant and i write the  ```which dotnet``` and go directory /var/lib/snapd/snap/bin/dotnet its my directory and remove dotnet and my problem is solved
