### ISSUE TITLE
Avoid using OSX for JIT stress jobs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#32041]
https://github.com/dotnet/runtime/pull/31750 reduced the number of platforms on which JIT stress pipelines are run. OSX is currently built/tested because that is the default pipeline configuration. Consider not using OSX at all based on trylek suggestion:

> If you want to avoid using OSX, you can use the parameter <code>ManagedOsxBuild: false</code> like we do here:

https://github.com/dotnet/runtime/blob/08a64b4cf72bebf0906f985e6521f499192fced8/eng/pipelines/coreclr/r2r.yml#L44

**Comment by jashook** [comment]
Seems like the better solution is to just not submit tests on osx, but still build them there.

**Comment by BruceForstall** [comment]
Why? Because the OSX test build is faster? OSX is still a limited hardware, isn't it?

**Comment by jashook** [comment]
The OSX build is significantly faster and the build machines are hosted vms.

**Comment by AndyAyersMS** [comment]
> The OSX build is significantly faster

That seems surprising, do we know why?

The coreclr test build seems super-slow overall. Given that it largely does the same thing over and over (both across most commits and across different build target OSs/ABIs), I wonder if we should be looking at other options.

**Comment by jashook** [comment]
The build machines that Azure devops provides on osx are very nice.

There has been a lot of work over the past ~8 months to improve the test build, there is still much more work to be done. Though, this is currently not as high priority as the 2 hour official build unfortunately.

**Comment by BruceForstall** [comment]
This is minor, maybe not even a good idea, so closing
