### ISSUE TITLE
"dotnet Service.dll" takes 8 seconds more on Windows Server 2019 container vs Windows Server 2016 container for first run

### ISSUE THREAD

**Issue by shreyagr** [dotnet/runtime#32058]
# General

We are running dotnet core 2.1 app on mcr.microsoft.com/dotnet/core/aspnet:2.1-nanoserver-1809 image for container. However, we are seeing that the command "dotnet service.dll" takes 8-9 seconds to start.

If I try to use Entrypoint to just get a cmd window and manually run "dotnet service.dll", the first attempt takes 8-9 seconds, but all following attempts within the same container instance are instantaneous. Does this mean there is some metadata that dotnet loads or tries to get for the first run?

**Comment by jeffschwMSFT** [comment]
Moved to https://github.com/dotnet/sdk/issues/10626
