### ISSUE TITLE
[QUIC] Don't leak QUIC session upon QuicListener disposal

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32073]
We have a hang in QuicListener.Dispose() and are currently working around it by just not disposing of the session.

https://github.com/dotnet/runtime/blob/5c6f5b14f0688b20ef339773854ff92e01807cde/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicListener.cs#L113-L115

**Comment by scalablecory** [comment]
Moving this to 6.0, @jkotalik does that sound okay given this will be experimental feature, and QuicListener is generally disposed at end of program in ASP.NET?

**Comment by ManickaP** [comment]
Has this been solved by: https://github.com/dotnet/runtime/pull/49823 ??? Seems to me like it has. We might close this.
@scalablecory

**Comment by ManickaP** [comment]
We're disposing the configuration properly:
https://github.com/dotnet/runtime/blob/11f1d82225500ae34eaae5ba3486f5b2a9506edb/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicListener.cs#L113

Closing, this was solved in #49823
