### ISSUE TITLE
[QUIC] Decide how concurrent sends are handled in QUIC

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32078]
Should sends "buffer" and complete sequentially? Should a send throw if another is already in progress?

https://github.com/dotnet/runtime/blob/65587ba7b402411b62ce877ee044aef2c2c71dfd/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L806-L810

**Comment by geoffkizer** [comment]
Do we need to support concurrent sends? This seems like something we should just disallow. Whether we reliably detect it and throw or not, I don't have a strong opinion.

**Comment by scalablecory** [comment]
This was a question because `Socket.Send` supports it. I am 100% fine not supporting it.

**Comment by geoffkizer** [comment]
Resolution: We will not support this.
