### ISSUE TITLE
[QUIC] Support synchronous QUIC APIs

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32076]
Current sync APIs use blocking async calls. We should use native MsQuic sync calls:

https://github.com/dotnet/runtime/blob/65587ba7b402411b62ce877ee044aef2c2c71dfd/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L393-L399

**Comment by GSPP** [comment]
Just some customer feedback:

Synchronous APIs are not an obsolete concept by any means. In many scenarios, the number of threads is not an issue. Synchronous calls still are easier to program, do not avoid certain classes of bugs and can impose less CPU overhead.

So it's a good thing if first-class synchronous support is available.

**Comment by karelz** [comment]
There is no msquic native API for sync access. Sync over async is the best we can do. Closing.
