### ISSUE TITLE
[QUIC] Use server TLS options in QUIC

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32071]
We need to support multiple ALPN protocols, certificates, and SNI callbacks in QuicListener:

https://github.com/dotnet/runtime/blob/5c6f5b14f0688b20ef339773854ff92e01807cde/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicSession.cs#L48-L56

**Comment by scalablecory** [comment]
@jkotalik moving to 6.0 -- did you find a way to use a server cert with Kestrel?

**Comment by ManickaP** [comment]
Triage: we're missing features in msquic to fully support that. We do have some support.

**Comment by ManickaP** [comment]
SslServerOptions properties we do not touch (not sure if they all make sense in QUIC context):
- AllowRenegotiation
- CipherSuitesPolicy PNSE
- EnabledSslProtocols.NoEncryption PNSE (should this rather be != RequireEncryption)

cc @wfurt could you help identify if anything from the three we should support and if not, we might add some more PNSE and close this.

**Comment by wfurt** [comment]
We should do `CipherSuitesPolicy` at some point. MsQuic has support now but at this point the list has only 3 items AFAIK.

**Comment by ManickaP** [comment]
CipherSuitePolicy covered in https://github.com/dotnet/runtime/issues/55378

**Comment by wfurt** [comment]
Looks complete to me. 
`CertificateRevocationCheckMode` is covered indirectly. 
For the `NoEncryption`: for SslStream we accept `AllowNoEncryption` even on systems that do not support NULL encryption. It will just never happen. We can be more strict for QUIC if we want to. 

I would be in favor of closing this and keeping specific issues instead.

**Comment by ManickaP** [comment]
I'll close this for now, since we have an issue for the policy.
