### ISSUE TITLE
JIT sometimes emits unnecessary movsxd instructions when performing logical operations against consts

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#32089]
Repro, courtesy sharplab:

```cs
public static bool CompareAgainstConstInt(int a) {
    return (a & 0x40) == 0;
}
    
public static bool CompareAgainstConstUInt(int a) {
    return (a & 0x40u) == 0;
}
```

```asm
; C.CompareAgainstConstInt(Int32)
    L0000: test cl, 0x40
    L0003: setz al
    L0006: movzx eax, al
    L0009: ret

; C.CompareAgainstConstUInt(Int32)
    L0000: movsxd rax, ecx   ; <-- this is unnecessary
    L0003: test al, 0x40
    L0005: setz al
    L0008: movzx eax, al
    L000b: ret
```

category:cq
theme:optimization
skill-level:intermediate
cost:medium

**Comment by 0xd4d** [comment]
The C# compiler converts the expression to a `long & long` expression. Would be nice to have some Roslyn analyzer catch this because it's usually not what the programmer intended.

**Comment by GrabYourPitchforks** [comment]
The Roslyn behavior makes sense to me, so I don't think an analyzer is needed. What this issue tracks is that I was hoping the JIT could recognize that the sign-extension was throwaway work (since the comparison is against a constant) and that it could avoid emitting the instruction.

You can also see this with other types like `byte` and `short`, not just `int`:

```cs
public static bool Foo(byte i) {
    return (i & 0x20) == 0;
}
```

```asm
; C.Foo(Byte)
    L0000: movzx eax, cl
    L0003: test al, 0x20
    L0005: setz al
    L0008: movzx eax, al
    L000b: ret
```

**Comment by AndyAyersMS** [comment]
This is fairly endemic; the jit does not do the analysis to determine when entire trees of computation can be safely and more profitably done on a smaller (or sometimes, larger) type.

**Comment by AndyAyersMS** [comment]
I can't find any overall issue talking about narrowing/widening -- @dotnet/jit-contrib anyone know of one?

**Comment by BruceForstall** [comment]
Going to close this in favor of #32504
