### ISSUE TITLE
Support Profiling API on macOS

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#32096]
Do you have any plans to officially support Profiling API on macOS?

I'm asking because right now it seems to be fully supported and I haven't seen anything except https://github.com/dotnet/runtime/issues/32093.

If you don't plan to update your infrastructure and officially support it in the near future, then what is your policy regarding troubleshooting macOS-specific issues in Profiling API (if any)? Just want to know how friendly you will be, and whether the community should report such problems. :)

cc @davmason

**Comment by davmason** [comment]
In general we are not commiting to fixing any issues found on macos, but if you report them we will do our best to provide advice on how to unblock yourself. We also would accept PRs from community members to fix any issues you run in to.
