### ISSUE TITLE
typeof(T).IsValueType isn't fully optimized for reference types T

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#32094]
Related: https://github.com/dotnet/runtime/pull/1157

It looks like there are still some cases where `typeof(T).IsValueType` isn't fully optimized by the JIT. Repro:

```cs
static void Main(string[] args)
{
    while (true)
    {
        ReturnIsValueType<bool>();
        ReturnIsValueType<bool?>();
        ReturnIsValueType<string>();
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static bool ReturnIsValueType<T>()
{
    return typeof(T).IsValueType;
}
```

For value types `bool` and `bool?` this is optimized as expected.

```asm
; for T = bool
00007ffd`51100bf0 b801000000      mov     eax,1
00007ffd`51100bf5 c3              ret

; for T = Nullable<bool>
00007ffd`51100c10 b801000000      mov     eax,1
00007ffd`51100c15 c3              ret
```

But for `string` there's still some throwaway work involving the passed type parameter and a stack spill before eventually returning the constant value _false_.

```asm
; for T = string
00007ffd`51100c30 50              push    rax
00007ffd`51100c31 48890c24        mov     qword ptr [rsp],rcx
00007ffd`51100c35 33c0            xor     eax,eax
00007ffd`51100c37 4883c408        add     rsp,8
00007ffd`51100c3b c3              ret
```

**Comment by EgorBo** [comment]
For `ReturnIsValueTypeForString`
```csharp
static bool ReturnIsValueTypeForString() => ReturnIsValueType<string>();

static bool ReturnIsValueType<T>() => typeof(T).IsValueType;
```
(when inlining is involved)
Emits
```
       xor      eax, eax
       ret      
```

**Comment by GrabYourPitchforks** [comment]
Yeah, things are inlined cleanly. The unexpected codegen only occurs when inlining is suppressed.

**Comment by AndyAyersMS** [comment]
The codegen for ref type `T` is by design -- for shared generic methods the jit has to make the generic context (passed in `rcx`, here) available to the runtime. You can see this in the gc info dump:
```
Set generic instantiation context stack slot to -16, type is MD.
```
I suppose one could argue this is unnecessary in a leaf method with no GC safe regions; I don't know the runtime well enough to say for sure.

**Comment by GrabYourPitchforks** [comment]
@AndyAyersMS I understand why the type information has to be passed in the _rcx_ register, but why in the method implementation is it being pushed onto the stack if it's never used?

**Comment by AndyAyersMS** [comment]
It is implicitly used by the runtime.

The location is conveyed from the jit to the runtime by the GC info, and the only supported reporting location is on the stack.
