### ISSUE TITLE
Profiler Attach/Detach support on macOS

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#32093]
_Originally posted by @k15tfu in https://github.com/dotnet/runtime/issues/9886#issuecomment-584305006_
> @davmason @noahfalk A bit confused that Profiler Attach/Detach feature (i.e. `FEATURE_PROFAPI_ATTACH_DETACH`) is not available on macOS: https://github.com/dotnet/coreclr/blob/5558d18aafc84ecac3630ca6a31f52699cde0b66/clrdefinitions.cmake#L184.
Is it a typo, or are there actually some unresolved issues to support this?

_Originally posted by @davmason in https://github.com/dotnet/runtime/issues/9886#issuecomment-584328760_
> @k15tfu profiling is not officially supported on macos. The fact that PROFILING_SUPPORTED is defined for anything besides linux or windows is an oversight. We only test the profiler on linux and windows, and only guarantee it will work as expected on those platforms.

Other Profiling API features are not prohibited and work on macOS, thus can we also allow profiler attach/detach on this platform? I'll check and say if everything is okay with it.

**Comment by k15tfu** [comment]
@davmason Hi again! Just have checked that Attach/Detach on macOS works on top of v3.1.1 with enabled `-DFEATURE_PROFAPI_ATTACH_DETACH` in clrdefinitions.cmake. The profiler's dylib also succesfully unloaded from the process after detach.

**Comment by davmason** [comment]
@k15tfu as mentioned in #32096, you can feel free to open a PR to enable it.

**Comment by k15tfu** [comment]
@davmason Cool. Gonna do it right now. And can we expect it to be available in 3.1 as well?

**Comment by k15tfu** [comment]
@davmason @jkotas What we can (should) do to port this to 3.1?

**Comment by davmason** [comment]
@k15tfu we can't just port any change to previous releases, we only port specific high impact or security fixes that are approved by my management. This is not the type of change that would be approved.

**Comment by k15tfu** [comment]
@davmason I know that it's not a normal practice to port new features to previous releases. But for this case I thought it might be possible because
1) 3.1 is LTS that will be used for almost 3 years
2) the fix is pretty simple (just update the configs). It doesn't rework other parts, and most likely will not break anything.

There will certainly be end users expecting attach to work on Mac, but I can't estimate their numbers. Of course formally it is still a new feature and managers may not approve this, but should we try?

**Comment by auduchinok** [comment]
I would really like to be able to attach to a process on a Mac.
Given that the fix consists of updating the configs is there a chance it could be added to a service release?

Thank you.

**Comment by davmason** [comment]
Hi @auduchinok @k15tfu,

Even though it may seem like a small request, we cannot port new features back in servicing. It is posted publicly in out (support policy)[https://dotnet.microsoft.com/platform/support/policy/dotnet-core] that LTS releases will only receive "critical and compatible fixes" and new features do not fall under that.

.net 5 preview 1 is already released and .net 5 should be officially released later this year, if profiling on mac is critical then the customers will have to move to .net 5.
