### ISSUE TITLE
Deadlock in SocketPal.Unix.cs

### ISSUE THREAD

**Issue by fehmianac** [dotnet/runtime#32103]
Hi,

We have some deadlock issue in Production stage.

Situation like that.
We are doing "fail over" our MSSQL database. Some time we had dead lock thread after fail over. When we analyze dump we are seeing some dead lock in "system.net.sockets.socketpal.receive" method.

Is there any work around about this case ?

OS: Ubuntu 18.04 also Docker
Runtime: 3.1.100
ORM: Dapper
Data Client: System.Data.SqlClient 4.80
RPM: About 10K

Dump Stacktrace

<img width="972" alt="threads" src="https://user-images.githubusercontent.com/9279620/74222729-32ef4a80-4cc6-11ea-868e-ee817cba95a1.png">
<img width="1675" alt="stacks" src="https://user-images.githubusercontent.com/9279620/74222736-34b90e00-4cc6-11ea-8523-a7eaa12a9f2c.png">

**Comment by karelz** [comment]
@fehmianac what are indicators that it is a deadlock?

**Comment by fehmianac** [comment]
Hi @karelz,

CPU of Machines are increasing. Then we got some dump on that machines. There was some locked threads in dump file.

After that when we listed proccess threads on linux machine. Some threads seams working 2 hours. It's fitting CPU usage grapics.

By the way it doesn't affect response time of services.

![CPU-Usage](https://user-images.githubusercontent.com/9279620/74403612-d95b5d00-4e38-11ea-8673-253915e9fffd.png)

It's happing more than 1 machine. We have over than 20 machine on production. It will increase because we are changing our from Monolithic WFC API to .NET Core 3.1 Web API.

In three months it happened that case 6 time and on over 10 
 diffrent machines.

**Comment by karelz** [comment]
@fehmianac it is still not clear that this is a real deadlock, and not just a busy loop in there.
Can you try to add some logging to confirm that it is deadlock vs. your code running same APIs in a loop.
Also, it might be good to check timeouts and verify that the threads are not just waiting for content from network.

Obviously, if you can isolate the problem into smaller repro, or at least something we can easily run in-house (even if it takes few hours to hit it), then we can make it actionable.

**Comment by Berreek** [comment]
@karelz We are hitting exactly same issue here. I wouldn't say it's a deadlock but rather some infinite loop according to traces we got.

Runtime: 3.1.9
OS: microsoft/aspnet:3.1-alpine hosted in AKS
SqlCient: Microsoft.Data.SqlClient 1.1.3
SqlServer: Azure Sql Server (General Purpose: Serverless, Gen5, 4 vCores)

I have full dumps and traces created by dotnet-monitor that might be needed to analyze that issue. 
In trace I can see that one of threads is running basically in the loop.

![image](https://user-images.githubusercontent.com/20483152/97445015-131fb580-192d-11eb-99ee-696f792c1426.png)

Our application is connecting to 3 different sql servers and the loop happens to only one that I mentioned - this connection is used for background worker to log http calls that failed and it's not used very often. I don't really have a way to reproduce easy but I believe with dumps and traces we can figure it out.
