### ISSUE TITLE
ODBC connection is not working with .NetCore 3.0 and 3.1

### ISSUE THREAD

**Issue by deepan-1984** [dotnet/runtime#32105]
Getting below error with >net core 3.0 and 3.1 version working with Net Core 2.0
ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

**Comment by wfurt** [comment]
not very much info for triage @deepan-1984
Repro code, steps, and platform info would be useful.

cc: @cheenamalhotra

**Comment by deepan-1984** [comment]
https://github.com/dotnet/runtime/issues/32152#issuecomment-585163644

**Comment by cheenamalhotra** [comment]
@saurabh500 for System.Data.Odbc namespace.

**Comment by saurabh500** [comment]
@deepan-1984 please provide a repro

**Comment by deepan-1984** [comment]
System.Data.Odbc
with NetCore 3.0
![image](https://user-images.githubusercontent.com/50020399/74331300-678ffe80-4db9-11ea-83cb-507f86554d88.png)

with .net core 2.0 its working
![image](https://user-images.githubusercontent.com/50020399/74331589-ff8de800-4db9-11ea-8272-133ca73be5d2.png)

tried using Microsoft.Windows.Compatibility Pack ,no luck

**Comment by saurabh500** [comment]
What does your connection string in failure cases look like? 

I see there is a difference in the way the connection string is being retrieved in the two scenarios. Can you retrieve the connection string from `_iconfigData.dbContext(connectionType)` and make sure it is valid ? 

The issue that you have pointed out, usually appears when you are pointing to a bad DSN which is not configured in the ODBC driver manager.

**Comment by deepan-1984** [comment]
> What does your connection string in failure cases look like?
> 
> I see there is a difference in the way the connection string is being retrieved in the two scenarios. Can you retrieve the connection string from `_iconfigData.dbContext(connectionType)` and make sure it is valid ?
> 
> The issue that you have pointed out, usually appears when you are pointing to a bad DSN which is not configured in the ODBC driver manager.

Thanks for the comments,
 the connection string is valid. Same string Connection is opened when targeting. Net Core 2.0,
Gets error with 3.0 no issue with connection string, and dsn are configured  for odbc driver and the connection succeed in dsn test. Getting error only when targeting. .Net Core 3.0. Please help

**Comment by saurabh500** [comment]
Can you do me a favor and upload a zipped version of good and bad projects with csproj files as well?

**Comment by deepan-1984** [comment]
attached zip with two asp.net core project with odbc connection in each controllers.
[OdbcConnection_Sample.zip](https://github.com/dotnet/runtime/files/4194371/OdbcConnection_Sample.zip)

note System.Data.Odbc nuget package has below dependency
![image](https://user-images.githubusercontent.com/50020399/74366699-7b0d8a80-4df6-11ea-979e-5203cd415293.png)

**Comment by saurabh500** [comment]
Can you share you connection string as well ?

**Comment by saurabh500** [comment]
Without any credentials (if it has any)

**Comment by saurabh500** [comment]
@deepan-1984  I am not very well versed with the web stack. Can you tell me to to invoke the WeatherForecastController HttpGet from the browser? For the 2.1 project I could get to it using /api/values, but that doesnt seem to be the case for 3.0

**Comment by deepan-1984** [comment]
https://localhost:44330/weatherforecast

                string connectionString = "Driver ={ Cisco Information Server 7.0}; DSN = ; user = ; password = ;encrypt=true;host=;port=9401;domain=composite;datasource=";

**Comment by saurabh500** [comment]
Thanks. I  tried this for both the projects after adding a reference to System.Data.Odbc 4.7.0 and used the connection string `DSN=customDsnPointingToSqlServer` and both the controllers can open the ODBC connections.

**Comment by saurabh500** [comment]
I tried the 3.0 project with 
`string connectionString = "Driver={ODBC Driver 17 for SQL Server};Server=(local);Trusted_Connection=Yes;Database=master;";`

I have the ODBC driver 17 installed for SQL Server and the connection goes through fine. 

Then I looked at your connection string and you have a space after `{`  while specifying the driver name. I think that is the problem. 

I changed the connection string to 
`                string connectionString = "Driver={ ODBC Driver 17 for SQL Server};Server=(local);Trusted_Connection=Yes;Database=master;";`
and I can repro the issue. So fixing the space before the driver name fixed the issue for me. Please check these aspects in your connection string.

**Comment by deepan-1984** [comment]
thanks, will check

**Comment by deepan-1984** [comment]
> I tried the 3.0 project with
> `string connectionString = "Driver={ODBC Driver 17 for SQL Server};Server=(local);Trusted_Connection=Yes;Database=master;";`
> 
> I have the ODBC driver 17 installed for SQL Server and the connection goes through fine.
> 
> Then I looked at your connection string and you have a space after `{` while specifying the driver name. I think that is the problem.
> 
> I changed my connection string to
> ` string connectionString = "Driver={ ODBC Driver 17 for SQL Server};Server=(local);Trusted_Connection=Yes;Database=master;";`
> and I can repro the issue. So fixing the space before the driver name fixed the issue for me. Please check these aspects in your connection string.

Thanks,
 checked with above scenario still getting same error.
will check with different driver .

**Comment by xiangzhai** [comment]
:gsvm-interest
