### ISSUE TITLE
FileInfo(path).Length works different on Mono than .NET Core on Linux

### ISSUE THREAD

**Issue by psantosl** [dotnet/runtime#32111]
I have this:

`lrwxrwxrwx 1 pablo users 14 Feb 11 10:16 blobs.idx -> blobs.orig.idx`

And this code:

Console.WriteLine("Size of {0} is {1}", path, new FileInfo(path).Length);

Mono prints: (no matter the version)
Size of ../wkplastic/01plastic/bin/server-netcore/jet/rep_1/blobs/blobs.idx is 65536

.NET Core 3.1 prints:
Size of ../wkplastic/01plastic/bin/server-netcore/jet/rep_1/blobs/blobs.idx is 14

Not sure which one is wrong, but it is certainly a pain :(

**Comment by EgorBo** [comment]
I suspect it's a https://github.com/mono/mono specific issue rather than mono-netcore runtime for .NET 5.

**Comment by psantosl** [comment]
It might be, but you're going to destroy app developers porting from Mono to .NET Core.

**Comment by JeremyKuhne** [comment]
Giving the data for the link itself is how the original .NET Framework implementation worked and we've matched that behavior for Unix. Note adding support for symbolic links is on our todo list (identifying them, following them, possibly creating them). https://github.com/dotnet/runtime/issues/24271

@marek-safar, @tarekgh This is a behavior difference in the libraries.

**Comment by marek-safar** [comment]
I agree with Egor that this about mono/mono not .NET5 MonoVM. You might consider reporting in at https://github.com/mono/mono as .NET5 behaviour is the same.
