### ISSUE TITLE
Infinite recursion while computing instance layout in crossgen2

### ISSUE THREAD

**Issue by y-yamshchikov** [dotnet/runtime#32120]
Crossgen2 falls into infinite recursion for some types on ARM.
Trace of recursion follows:
```
1. DefType::ComputeInstanceLayout
2. MetadataFieldLayoutAlgorithm::ComputeInstanceLayout
3. ReadyToRunMetadataFieldLayoutAlgorithm::ComputeInstanceFieldLayout
4. MetadataFieldLayoutAlgorithm::ComputeAutoFieldLayout
5. ReadyToRunMetadataFieldLayoutAlgorithm::AlignBaseOffsetIfNecessary
6. TypeExtensions::RequiresAlign8
7. DefType::InstanceByteAlignment
8. and (1) again and so on
```
`DefType::InstanceByteAlignment` expects that instance layout may be computed already, but in this case it obviously is not.
`TypeExtensions::RequiresAlign8` exits with `false` if target architecture is not ARM, so that case is not replicable on other machines.

Can you help us find a way to properly fix it?

@jkotas @alpencolt

**Comment by jkotas** [comment]
cc @dotnet/crossgen-contrib

**Comment by jkotas** [comment]
I believe that 
- Change the `AlignBaseOffsetIfNecessary` method to take an extra maximum required alignment argument. Use this argument instead of calling the RequiredAlign8.
- Keep track of maximum alignment in `// Iterate over all fields and do the following` loop in ComputeAutoFieldLayout
- Move the `AlignBaseOffsetIfNecessary` call down `ComputeAutoFieldLayout` to be after the loop

**Comment by y-yamshchikov** [comment]
Thank you! I will try it.

**Comment by y-yamshchikov** [comment]
I've tried to call RequiredAlign8 for types of all fields in the type and call AlignBaseOffsetIfNecessary with 8 in additional argument if any of fields' types requires. This solution shifted us from the point above, but caused infinite recursions of 2 kinds I've encountered:

1. type ``[S.P.CoreLib]System.Collections.Generic.Dictionary`2+KeyCollection<System.__Canon,System.__Canon>`` has field with name `_dictionary` and type ``[S.P.CoreLib]System.Collections.Generic.Dictionary`2<System.__Canon,System.__Canon>``
which in turn has field named `_keys` of type ``[S.P.CoreLib]System.Collections.Generic.Dictionary`2+KeyCollection<System.__Canon,System.__Canon>``, and so on.

and more simple case in another `.dll` (in `crossgen2.dll` itself):
2. type `[S.P.CoreLib]System.Exception` has field `_innerException` with type `[S.P.CoreLib]System.Exception`, and so on.

I guess that reference types have to follow common alignment rules, but i wonder how to properly test "referenceness", is it the only such mistake, and what the rule should be.

Can you help us?

**Comment by jkotas** [comment]
Yes, the alignment should propagate from value-type fields only. `TypeDesc.IsValueType` is the property to use to test for non-"referenceness". Thank you for your work on this!
