### ISSUE TITLE
Building in VS doesn't build the src project

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#32146]
When opening the `System.Configuration.ConfigurationManager` project in VS, I was noticing that the `src` project wasn't getting built.

![image](https://user-images.githubusercontent.com/8291187/74288869-377e2800-4cf3-11ea-8fde-c1c63991f015.png)

Digging into the design-time builds, it appears some of them are failing:

```
Project    Project    Dimensions    Targets    Type    Start    Elapsed    Status
System.Configuration.ConfigurationManager    .csproj    Debug|AnyCPU|net461    CollectUpToDateCheckBuiltDesignTime;CollectPackageDownloads;ResolveAssemblyReferencesDesignTime;CollectAnalyzersDesignTime;CollectSDKReferencesDesignTime;CollectUpToDateCheckInputDesignTime;CollectUpToDateCheckOutputDesignTime;ResolvePackageDependenciesDesignTime;CompileDesignTime;CollectResolvedCompilationReferencesDesignTime    DesignTimeBuild    2020-02-11T15:49:35        Failed
System.Configuration.ConfigurationManager    .csproj    Debug|AnyCPU|net472    CollectUpToDateCheckBuiltDesignTime;CollectPackageDownloads;ResolveAssemblyReferencesDesignTime;CollectAnalyzersDesignTime;CollectSDKReferencesDesignTime;CollectUpToDateCheckInputDesignTime;CollectUpToDateCheckOutputDesignTime;ResolvePackageDependenciesDesignTime;CompileDesignTime;CollectResolvedCompilationReferencesDesignTime    DesignTimeBuild    2020-02-11T15:49:35        Failed
```

The reason the design-time builds were failing is because it is trying to run `ApiCompat` checks on `net461` and `net472`, but I haven't built for those TFMs.

`C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20109.1\build\Microsoft.DotNet.ApiCompat.targets(51,5): ResolvedMatchingContract 'F:\git\runtime2\artifacts\bin\System.Configuration.ConfigurationManager\ref\net461-Debug\System.Configuration.ConfigurationManager.dll' did not exist. [F:\git\runtime2\src\libraries\System.Configuration.ConfigurationManager\src\System.Configuration.ConfigurationManager.csproj]`

I suspect that the VS project-system isn't expecting those design-time builds to fail. And when they do, there are cases where VS thinks that the project doesn't contain any output items. I turned on the "Up to date" logging, and noticed that:

```
1>FastUpToDate: No build outputs defined. (System.Configuration.ConfigurationManager)
1>FastUpToDate: Project is up to date. (System.Configuration.ConfigurationManager)
1>FastUpToDate: Up to date check completed in 0.5 ms (System.Configuration.ConfigurationManager)
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

@davkean - Does VS expect those design-time builds to fail? Would this be the reason why it thinks there are `No build outputs defined.`?

One option here is to not run ApiCompat during a design-time build. There may be other options to fixing this as well. But I wouldn't expect developers to have to build for all TFMs before they can use VS.

/cc @joperezr @Anipik @safern

**Comment by davkean** [comment]
Targets that run during design-time builds need to have correct dependencies. A target has a implicit assumption that the project is built before running, which is a bad assumption.

**Comment by joperezr** [comment]
I also believe that it doesn't really provide much value to try to run it on design-time builds, so it would be better to just skip it on design time builds

**Comment by davkean** [comment]
https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#designing-targets-for-use-in-design-time-builds

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/arcade/pull/4829
