### ISSUE TITLE
Code Guide questions: run time environment, C++ versions, using libraries, etc...

### ISSUE THREAD

**Issue by kfrolov** [dotnet/runtime#32144]
[CLR Code Guide](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/clr-code-guide.md) does not gives answers on some basic questions, and because of this I want to ask it here.

Suppose, we want to propose some addition to CoreCLR code, but before writing the code we should understood in which environment code may work and for which environment it should be written. We are understood, that basically the code (of the runtime itself) is written in C++, and that many things should be done in same way, as it done in existing code, but the devil is in the details.

**First of all, which version of C++ language standard should be used?** 

I have found, that currently build system doesn't enforces particular version (for example C++11 or C++14) and leaves this decision for the compiler. And different compilers, different compiler versions, in different build environments may give different results: for example, clang ver <= 5.0  and gcc <= 5.0 by default both use C++98, but gcc >= 6.0 and clang >= 6.0 use C++14. Microsoft's Visual C uses C++14 starting from MSVC 2015.

As I understood, really CoreCLR can't be compiled with C++98 compiler at all, and at least C++03 was required at initial stage of CoreCLR development. But currently C++11 features, such as `constexpr`, `decltype`, `std::move` is actively used, so C++11 is really minimal requirement to build CoreCLR.

But what about C++14 or C++17 features?

**Second, which C++ features can be used, which not, there is exists some limitations?**

For example, in some embedded projects using of C++ exceptions are prohibited, or using of dynamic_cast and RTTI may be prohibited, etc...  Does some limitations for CoreCLR code exists?

As I understood, the code at leas should be able to be built by MSVC 2017 (or other version?)  So, GCC or Clang-specific extensions shouldn't be used. But how about microsoft-specific extensions for clang?  It should be avoided too (because of GCC) ?

**Third, which C/C++ standard libraries can be used?**

I understood, that dependency on any external library is too serious question and typically this is not an option, but how about standard C++ and C libraries?  From one point of view, it we are using some version of C++ language standard, so we can use library functions defined by this standard.  But from other side I see, that in CoreCLR's code nor C library, neither C++ libraries almost not used. So I'm expecting, where should be some reasons for that.  I understood why POSIX functions shouldn't be used, but instead functions from PAL layer should be used (which is available in Windows and Unix). But I don't understand, why CoreCLR avoid using of C/C++ library. 

This is so for historic reasons, or using of C/C++ functions is undesirable by some reasons?   For example, I can imagine, what C++ library functions might be avoided to make sure, that CoreCLR's functions are exception safe (so, actually noexcept functions from C++ library can be safely used).

And I have some basic questions, for example:

1) How to perform memory allocations?  We should use functions from PAL (like malloc), use `new` (which might be not exception safe -- should we catch exceptions?), anything else?

2) Can we use smart pointers from C++ library, std::unique_ptr is especially handy. Doing manual memory management is more error prone.

3) Can we use containers from C++ library, for example, std::map, or we can prefer to use classes which already present in CoreCLR (but such classes are poorly documented, which might lead again to error prone code).

4) How we should process errors?  Which is strategy of error handling for CoreCLR?  In general, in which cases we should allow to an error to emerge/arise at upper API level, in which cases it's better to ignore error, and in which cases it's allowable to call `abort`?   Especially, how to handle shortage of the memory?  Should errors to be logged and in which way?

@alpencolt @jkotas @y-yamshchikov @gbalykov

**Comment by jkotas** [comment]
> Third, which C/C++ standard libraries can be used?

We are not able to use standard C/C++ libraries for most of the runtime, for two reasons:
- The runtime internals need to be DACized (
- !!!

> How to perform memory allocations?

`new` operator

> Can we use smart pointers from C++ library

CoreCLR codebases uses `NewHolder` for this.

> How we should process errors?

**Comment by am11** [comment]
@jkotas, thanks for the explanation. I was also looking for more info on this topic.

> We are not able to use standard C/C++ libraries for most of the runtime, for two reasons:

i was trying to cleanup some indirection from `palinternal.h` in an experimental branch and was monitoring how many components actually fall into the `#else` cases of, for example, these implementations: https://github.com/dotnet/runtime/blob/bd98efe6adf4638d699f92d4b24bc6cdd5e0ca47/src/coreclr/src/inc/clr_std/vector#L15-L17 In my preliminary findings, most components were taking the if branch (stl std. header) and the debug/diagnostics related components required the #else / non-STL branches. Thanks for the DACize reference.

In theory, is it possible to use STL everywhere and replace these components without compromising DAC functionality?

**Comment by jkotas** [comment]
The CoreCLR versions of STL vector and friends are not DACized today either, so DACization should not be a problem.

There is another problem with STL that I forgot to mention: exception handling. CoreCLR does not use C++ exceptions directly. Exceptions need to be thrown and caught via the `EX_...` macros to make blend with managed exception handling. The parts of STL that throw and catch exceptions would be prohibited unless something is done about this part.

**Comment by joperezr** [comment]
I believe that @jkotas answered most of the questions above, so I'll go ahead and close this, but @am11 and @kfrolov feel free to reopen if you think otherwise or have any follow up questions.

**Comment by am11** [comment]
> exception handling

Perhaps [`std::set_terminate`](http://www.cplusplus.com/reference/exception/set_terminate/) and [`std::set_unexpected`](http://www.cplusplus.com/reference/exception/set_unexpected/) could be investigated for this to intercept the STL exceptions, and switching to those might fix issues like https://github.com/dotnet/runtime/issues/35362.
