### ISSUE TITLE
ConcurrentBag<T>._locals is never disposed.

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#32154]
As I understand the code, it looks like `ThreadLocal<T>.Dispose()` is never called on `ConcurrentBag<T>._locals`. If someone create many `ConcurrentBag<T>` object instances and just drop it, the thread static slots would never be reclaimed?

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs#L36

**Comment by stephentoub** [comment]
> would never be reclaimed?

They'll be cleaned up by the ThreadLocal finalizer:
https://github.com/dotnet/runtime/blob/75d8683ff9557f107eac96d6a694883f42d74135/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadLocal.cs#L142-L146

**Comment by cshung** [comment]
Aha! I missed that.
It sounds right as long as the ThreadLocal<T> doesn't somehow store a reference that refers to itself?

**Comment by stephentoub** [comment]
Right, that's https://github.com/dotnet/runtime/issues/23103.

**Comment by cshung** [comment]
Got it
