### ISSUE TITLE
Build fails on windows systems where username has space

### ISSUE THREAD

**Issue by mariusGundersen** [dotnet/runtime#32165]
I've tried to clone this project and make it build on my windows 10 machine, but I'm having trouble. 

At first I cloned the project into my usual dev directory, which is at `C:\Users\Marius Gundersen\dev\dotnet-runtime`, but when I rat the build I got the error `MSBUILD : error MSB1008: Only one project can be specified.`. A bit of googling revealed that this happens when [there is a space in the path](https://stackoverflow.com/questions/3779701/msbuild-error-msb1008-only-one-project-can-be-specified). 

So I moved the project to `C:\dev\dotnet-runtime` and tried again. Now it fails when I run `build -subsetCategory coreclr -c Release` with the error `LINK : fatal error LNK1266: error reading instrumentation file 'C:\Users\Marius'; Unhandled PDB error [C:\dev\dotnet-runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj]`. Again the space in the path seems to be the issue. 

Specifically it seems to be a problem in pgosupport.cmake file, these lines:

```
set_property(TARGET ${TargetName} APPEND_STRING PROPERTY LINK_FLAGS_RELEASE        " /LTCG /USEPROFILE:PGD=${ProfilePath}")
set_property(TARGET ${TargetName} APPEND_STRING PROPERTY LINK_FLAGS_RELWITHDEBINFO " /LTCG /USEPROFILE:PGD=${ProfilePath}")
```

I wrapped the `${ProfilePath}` in these two lines with `\"` (escaped since it's inside a string already), and now it seems to work.

**Comment by jkotas** [comment]
> I wrapped the ${ProfilePath} in these two lines with \" (escaped since it's inside a string already), and now it seems to work.

Could you please submit a PR with this change now that you have tested it fixes part of the problem?
