### ISSUE TITLE
XmlWriterSettings.Encoding must be registered in static Encoding

### ISSUE THREAD

**Issue by jflepp** [dotnet/runtime#32164]
When specifying an encoding in `XmlWriterSettings`, an encoding with the exact same codepage must be registered in the static `Encoding` class.

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlEncodedRawTextWriter.cs#L175

When specifying an encoding which is not globally registered (E.g. from [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/)), an `System.NotSupportedException` is being thrown: 

```
System.NotSupportedException: No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
```

This scenario was supported in the [.NET Framework](https://github.com/microsoft/referencesource/blob/master/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs#L176).

**Comment by jkotas** [comment]
.NET Core does not have the full set of .NET Framework encodings registered by default. The data required by the full set of encodings have non-trivial size and it would be unfortunate for every .NET app depend on them even if it does not need them.

If your app needs complete set of encoding from .NET Framework, register them by running `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);` as the first thing in your Main method.

**Comment by jflepp** [comment]
Yes, I agree that it makes sense that not every .NET implementation contains all outdated encodings.

But one could also implement a custom encoding and use it to encode / decode. As the `XmlWriterSettings` provides an `Encoding` property, one assumes that it is possible to supply custom objects without registering them somewhere in a static instance.

So why does the `XmlEncodedRawTextWriter.cs` not use the supplied instance as it did in the .NET Framework implementation?

If it is intended to only allow encodings contained in the `Encodings`, the CodePage value would have been sufficient.

**Comment by jkotas** [comment]
Ok, I see your point. .NET Framework cloned the encoding type instead of re-creating it from CodePage that avoids the problem:

https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs#L177

@buyaa-n @krwq Could you please find out why this change was made in .NET Core? Should we change it back to what it used to be in .NET Framework?

**Comment by krwq** [comment]
I suspect this will need to be changed to what full framework did. I can't remember why this was changed in the first place.
