### ISSUE TITLE
System.Runtime.Serialization.Formatters.Tests.FormatterServicesTests.GetUninitializedObject_SharedGenericInstance_NetCore_ThrowsNotSupportedException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32183]
https://dev.azure.com/dnceng/public/_build/results?buildId=517643&view=ms.vss-test-web.build-test-results-tab&runId=16377280&paneView=attachments&resultId=169118

Configurations:
- netcoreapp5.0-Linux-Debug-x64-Mono_release-Centos.7.Amd64.Open
- netcoreapp5.0-Linux-Debug-x64-Mono_release-SLES.15.Amd64.Open
- netcoreapp5.0-Linux-Debug-x64-Mono_release-Ubuntu.1804.Amd64.Open
- netcoreapp5.0-Linux-Debug-x64-Mono_release-(Fedora.29.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-29-helix-a12566d-20191210224553

```
Assert.NotNull() Failure
at System.Runtime.Serialization.Formatters.Tests.FormatterServicesTests.GetUninitializedObject_SharedGenericInstance_NetCore_ThrowsNotSupportedException() in /_/src/libraries/System.Runtime.Serialization.Formatters/tests/FormatterServicesTests.cs:line 156
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
```

cc @stephentoub @GrabYourPitchforks @ViktorHofer

**Comment by ViktorHofer** [comment]
Ok that only breaks in https://github.com/dotnet/runtime/pull/32115 because of infra changes (removal of Mono TFM) cc @akoeplinger

**Comment by GrabYourPitchforks** [comment]
We could change the test such that it early-exits (with success) if `System.__Canon` is unavailable.

**Comment by akoeplinger** [comment]
@GrabYourPitchforks I don't think that would improve the test since we'd still pretty much skip it on Mono and CoreCLR could silently fail if for some reason `__Canon` returns there.

I think it's fine to keep the test disabled on Mono given the implementation difference so closing the issue.
