### ISSUE TITLE
Use new RPM/Deb/pkg build infra from shared framework tooling for runtime packages

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#32187]
Currently packages are built in two ways in dotnet/runtime:

* https://github.com/dotnet/runtime/tree/master/src/installer/pkg/packaging: Older style. Uses a single project file and procedural, copy-paste-heavy targets. Creates RPM packages, Deb packages, and macOS pkgs for host, hostfxr, runtime, and runtime deps.
* https://github.com/dotnet/runtime/tree/master/src/installer/pkg/projects: Uses shared framework tooling to assemble packages. Generally speaking, one project per artifact, making it easy to use ordinary MSBuild strategies to reuse code rather than copy. This is how targeting/apphost/runtime packs are created, as well as all the MSIs and the burn bundle installer.

I migrated the MSIs and burn bundle installers from the old infra to the new. I targeted these specifically because we were splitting dotnet/windowsdesktop from dotnet/core-setup, and if we didn't share code in Arcade there would be a *ton* of copying. dotnet/windowsdesktop doesn't produce RPM/Deb/macOS pkgs, so they weren't included in the prioritized effort.

This issue tracks moving the remaining installer types over to the new infra for maintainability and consistency.

**Comment by NikolaMilosavljevic** [comment]
It would be very nice to have this for long-term maintainability.

**Comment by NikolaMilosavljevic** [comment]
[Triage] @jkoritzinsky do you know if this was done as part of SharedFX refactoring?

**Comment by jkoritzinsky** [comment]
Yep
