### ISSUE TITLE
Requiring CMake versions that aren't in the default package repository

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#32199]
According to https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/linux-requirements.md#toolchain-setup

> Building the repo requires CMake 3.14.2 or newer on Linux. Add Kitware's APT feed to your configuration for a newer version of CMake.

This is going to cause problems if/when we want to ship .NET 5 in Ubuntu 18's default package feed. In order to submit our product to these feeds, we can't rely on versions of tools that are in external package feeds.

We should allow our product to be built by toolchains that are available by default in major Linux distros, and not require external feeds in order to build.

/cc @dseefeld @dleeapho

**Comment by jkotas** [comment]
cc @jkoritzinsky
