### ISSUE TITLE
System.Reflection.Emit.ILGenerator should allow emitting short branching opcodes automatically

### ISSUE THREAD

**Issue by lpereira** [dotnet/runtime#32204]
Since there's no way for a code generator using `ILGenerator` to know the distance to a particular label, users of this class often just emit the normal, long opcode for branches, conditional or not.  A welcome refinement would be defining an API that would, based on the distance to the target, automatically select which version of the opcode to emit.

Proposed change
---------------

Implement a new method in `ILGenerator`:

```csharp
public virtual void Emit(OpCode opcode, Label label, bool useShortFormIfPossible);
```

Then, if `useShortFormIfPossible` is `false`, this method would essentially tail call into `Emit(OpCode, Label)`.

Otherwise, it would check if the distance to `label` falls within the range for a short form of IL opcode.  If it does, it converts the opcode (e.g. `Br` -> `Br_S`) and tail calls into `Emit(OpCode, Label)`; otherwise, it passes its `opcode` argument to `Emit(OpCode, Label)` as is.

Use cases in the framework
--------------------------

The `System.Text.RegularExpression` compiler can be trivially modified to support this change.

Pull request
------------

I'll send a PR once this change is approved.

**Comment by stephentoub** [comment]
In the case of forward branching, how would Emit know the distance to the label that hasn't been marked yet?  Is the suggestion that the long form be used and then prior to baking the implementation the jump be backpatched to the short form if appropriate?  And if so, couldn't we do that without new API?

**Comment by lpereira** [comment]
My idea was to generate the long form for those branches, set a flag somewhere, and reconsider them whenever `ILGenerator.MarkLabel()` is called in that label.  [Here's the test modification](https://github.com/lpereira/runtime/commit/e109feb743a85b0bc8b8a99bbcee8cb3370d3c6c).

We could potentially do it without the new API, by exposing `GetLabelLoc()`, but then all users of the `ILGenerator` API would need the same logic everywhere; by making `Emit()` aware of this, it's just the matter of calling it with an additional boolean parameter.  [Here's the changes in RegexCompiler](https://github.com/lpereira/runtime/commit/2071b330f5a72c2095eead820c0ce6b2cce617d5) after introducing the new proposed API.

**Comment by stephentoub** [comment]
> Unless you're proposing getting rid of the boolean parameter altogether and always do this

Right.

**Comment by stephentoub** [comment]
> Right

Of course, that's if it even really matters. What are the negative ramifications of not using the shortest branch instruction... just a few bytes of IL, right? The generated asm end up being identical after the JIT is some with it? And with the current state of things where reflection emit doesn't support persisting to disk, such IL is only ever in-memory and jit'd once?

**Comment by jkotas** [comment]
There are other short-cuts that Reflection.Emit takes than make it produce IL that is not as tight as it can be. For example, the maxstack is not computed perfectly. As @stephentoub said, this is not worth fixing given that reflection emit is only used for JIT. The extra cycles spent producing smallest possible branches or maxstack would not pay for itself.
