### ISSUE TITLE
potentially leaked lock in System.ComponentModel.Composition.Hosting.ImportEngine

### ISSUE THREAD

**Issue by twmillett** [dotnet/runtime#32226]
PreviewImports has code like

```
           // This will take the lock, if necesary
            IDisposable? compositionLockHolder = _lock.IsThreadSafe ? _lock.LockComposition() : null;
            bool compositionLockTaken = (compositionLockHolder != null);
            try
            {
                // revert actions are processed in the reverse order, so we have to add the "release lock" action now
                if (compositionLockTaken && (atomicComposition != null))
                {
```

If an exception happens before entering the ```try``` block, the lock will leak.  We've run into problems like this when running in ASP.net, because ThreadAbortExceptions can (and do) happen whenever they feel like it.

We recently had a dump file indicating an orphaned lock held by this class and I'm wondering if that's what happened.  Would a ```using``` statement achieve the same purpose?

**Comment by stephentoub** [comment]
> We've run into problems like this when running in ASP.net, because ThreadAbortExceptions can (and do) happen whenever they feel like it.

On .NET Framework, yes.  But not on .NET Core.

**Comment by twmillett** [comment]
Good to know!  

We are running on .net framework -- my bad, I guess I need to raise the issue elsewhere.

**Comment by ericstj** [comment]
Here are the support details for .NETFramework :  https://dotnet.microsoft.com/platform/support/policy/dotnet-framework
