### ISSUE TITLE
Consider making Interlocked.And and friends into JIT intrinsics

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#32239]
From https://github.com/dotnet/runtime/pull/32216#discussion_r378817293

https://github.com/dotnet/runtime/pull/32216 adds new methods like Interlocked.And.  Some of these could be done as JIT intrinsics and replaced by better implementations/instructions in some cases, like `lock and` on platforms that have it.

cc: @tannergooding 

category:cq
theme:jit-intrinsics
skill-level:intermediate
cost:medium
impact:medium

**Comment by BruceForstall** [comment]
@AndyAyersMS

**Comment by GrabYourPitchforks** [comment]
For context, it turns out the JIT already optimizes this for the existing `Interlocked.Add` and similar APIs.

```cs
using System;
using System.Threading;

public class C {
    public static int M(ref int i) {
        return Interlocked.Add(ref i, 1);
    }
    
    public static void N(ref int i) {
        Interlocked.Add(ref i, 1);
    }
}
```

```asm
; C.M(Int32 ByRef)
    L0000: mov eax, 0x1
    L0005: lock xadd [rcx], eax
    L0009: inc eax
    L000b: ret

; C.N(Int32 ByRef)
    L0000: lock add dword [rcx], 0x1
    L0004: ret
```

**Comment by stephentoub** [comment]
Nice.  This can be closed then, right?

**Comment by stephentoub** [comment]
Oh.. you said Add, not And.

**Comment by AndyAyersMS** [comment]
These should be done via new-style intrinsics. We may also want to convert some of the existing intrinsified interlocked ops over to this mechanism as well.

**Comment by AndyAyersMS** [comment]
@stoub we're triaging proposed 5.0 codegen work -- any thoughts on the priority of this issue?

**Comment by stephentoub** [comment]
From my perspective, "nice to have", but I expect there's other higher priority JIT work that'll be more impactful.  These APIs are brand new.

**Comment by AndyAyersMS** [comment]
@GrabYourPitchforks can you make a case for addressing this in 5.0?

**Comment by GrabYourPitchforks** [comment]
I agree with Steve's assessment. Optimizing these APIs might save a few cycles in a handful of places, such as below.

https://github.com/dotnet/runtime/blob/ef2ea8a6a241431a209beab36236444de837dcbf/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L739-L740

https://github.com/dotnet/runtime/blob/ef2ea8a6a241431a209beab36236444de837dcbf/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L104-L105

These are hot code paths, but not _so_ hot that a few extra cycles are going to kill us. :) If you have other more pressing matters, so be it.

**Comment by AndyAyersMS** [comment]
Ok, I'm going to move this to future.

**Comment by JulieLeeMSFT** [comment]
@echesakovMSFT Possible candidate for .NET 6.

**Comment by EgorBo** [comment]
this is a bit tricky for the cases when return value of And/Or is used  🙂

**Comment by GrabYourPitchforks** [comment]
Wouldn't it be able to use the same logic `Interlocked.Add` and friends use? See my earlier comment at https://github.com/dotnet/runtime/issues/32239#issuecomment-586462094.

**Comment by EgorBo** [comment]
@GrabYourPitchforks here is what LLVM emits for us (mono-llvm): https://godbolt.org/z/WWxTKh

see `Interlocked.And (not-void)` codegen

**Comment by EgorBo** [comment]
better demo: https://godbolt.org/z/cMj5Tx

**Comment by echesakovMSFT** [comment]
When using Armv8.1 instructions the clang/llvm generated code seems much better than its Armv8.0 counterpart https://godbolt.org/z/Yvjcqb and there is no loops required.

**Armv8.0**
```asm
InterlockedAdd(int*, int):                  // @InterlockedAdd(int*, int)
.LBB0_1:                                // =>This Inner Loop Header: Depth=1
        ldaxr   w8, [x0]
        add     w8, w8, w1
        stlxr   w9, w8, [x0]
        cbnz    w9, .LBB0_1
        mov     w0, w8
        ret
InterlockedAnd(int*, int):                  // @InterlockedAnd(int*, int)
.LBB1_1:                                // =>This Inner Loop Header: Depth=1
        ldaxr   w8, [x0]
        and     w8, w8, w1
        stlxr   w9, w8, [x0]
        cbnz    w9, .LBB1_1
        mov     w0, w8
        ret
InterlockedOr(int*, int):                   // @InterlockedOr(int*, int)
.LBB2_1:                                // =>This Inner Loop Header: Depth=1
        ldaxr   w8, [x0]
        orr     w8, w8, w1
        stlxr   w9, w8, [x0]
        cbnz    w9, .LBB2_1
        mov     w0, w8
        ret
```

**Armv8.1**
```asm
InterlockedAdd(int*, int):                  // @InterlockedAdd(int*, int)
        ldaddal w1, w8, [x0]
        add     w0, w8, w1
        ret
InterlockedAnd(int*, int):                  // @InterlockedAnd(int*, int)
        mvn     w8, w1
        ldclral w8, w8, [x0]
        and     w0, w8, w1
        ret
InterlockedOr(int*, int):                   // @InterlockedOr(int*, int)
        ldsetal w1, w8, [x0]
        orr     w0, w8, w1
        ret
```

**Comment by EgorBo** [comment]
@echesakovMSFT Do you mind if I try to implement `Or` and `And` for arm ? (with the atomics)
In case if you haven't started it yet of course. I just want to do something for Arm back-end 🙂

**Comment by echesakovMSFT** [comment]
@EgorBo I haven't started working on this. If you want to work on this, feel free to do so and un-assign me.

**Comment by EgorBo** [comment]
Reopening since https://github.com/dotnet/runtime/pull/46253 only handled them for arm64

**Comment by EgorBo** [comment]
Moving to Future, it's not easy to optimize it for x86 unfortunately because we only can optimize cases where return value of these methods won't be used and we can't check that fact at the importer phase easily.

**Comment by tannergooding** [comment]
> Moving to Future, it's not easy to optimize it for x86 unfortunately because we only can optimize cases where return value of these methods won't be used and we can't check that fact at the importer phase easily.

This is actually a decently broad issue with intrinsics. There are many cases where we want to optimistically create a trea but where we won't know if it can actually be an intrinsic or call until much later.
With hardware intrinsics, this leads to codegen issues for things that are detected to be constants after importation, for example.

Some of the older intrinsics (`GT_INTRINSIC`) have support in rationalizer to be rewritting as user calls: https://github.com/dotnet/coreclr/blob/master/src/jit/rationalize.cpp#L208
I had taken a look at enabling this more broadly for cases like `GT_HWINTRINSIC` so we could fix cases like this but ran into issues due to the non-primitive inputs/returns (and these were out of my depth to resolve at the time): https://github.com/dotnet/runtime/issues/11062#issuecomment-549564950

Given that these interlocked methods only deal with primitives, its possible that it won't hit the same problems.

**Comment by EgorBo** [comment]
> Some of the older intrinsics (GT_INTRINSIC) have support in rationalizer to be rewritting as user calls: RewriteIntrinsicAsUserCall

@tannergooding the problem that if we re-write `GT_XAND` to a call like that - we'll regress the current case when we inline it as complex expression (contains a loop) as is. Perhaps, it's not a big deal ("call" overhead for the case where return value is used and super fast implementation for cases where it's not -- e.g. all BCL usages (there are just a few of them) of them don't care about return value.
