### ISSUE TITLE
ClientWebSocket on Linux uses wrong proxy if http and https proxies are different

### ISSUE THREAD

**Issue by daddyman** [dotnet/runtime#32230]
Using dotnet core 3.1.1. My program uses `ClientWebSocket` to connect to a server. The URL can be either secure (wss://server.example.com) or insecure (ws://server.example.com).

For testing I set the `http_proxy` and `https_proxy` environment variables to different values that go through a different proxy.

When I connect using insecure (ws://server.example.com) the HTTPS proxy is used which is not correct.

The problem seems to be in `src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs`. The `GetProxy` method looks like this

```c#
        /// <summary>
        /// Gets the proxy URI. (iWebProxy interface)
        /// </summary>
        public Uri GetProxy(Uri uri)
        {
            return uri.Scheme == Uri.UriSchemeHttp ? _httpProxyUri : _httpsProxyUri;
        }
```
In the websocket case the URI scheme is `ws` so it chooses the https proxy.

A potential fix is to change the code to:

```c#
        /// <summary>
        /// Gets the proxy URI. (iWebProxy interface)
        /// </summary>
        public Uri GetProxy(Uri uri)
        {
            return HttpUtilities.IsSupportedNonSecureScheme(uri.Scheme) ? _httpProxyUri : _httpsProxyUri;
        }
```
This would be similar to the logic in `HttpConnectionPoolManager.GetConnectionKey` where it decides if it should set the sslHostName so it can choose between using ProxyTunnel or SslProxyTunnel for the connection kind.

As a workaround I implemented an IWebProxy implementation that changes the URL (ws => http, wss => https) and then forwards the call (GetProxy or IsBypassed) to the default proxy implementation (HttpClient.DefaultWebProxy). With this change the correct proxy is used.

**Comment by stephentoub** [comment]
cc: @davidsh, @wfurt

**Comment by davidsh** [comment]
>When I connect using insecure (ws://server.example.com) the HTTPS proxy is used which is not correct.

This is happening because for all websocket connections (either WS or WSS) going thru a proxy, we always do CONNECT tunneling thru the proxy (either thru port 80 or 443). So, the logic for deciding between "http_proxy" vs. "https_proxy" is getting confused since it is assuming "HTTPS" connection since CONNECT tunneling is usually only used for HTTPS operations.

The fixed logic suggested above is probably the likely fix.

**Comment by karelz** [comment]
@daddyman thanks for the report and suggested fix! Are you interested in submitting a PR?
