### ISSUE TITLE
Non-ASCII chars shouldn't compare equal to ASCII chars under OrdinalIgnoreCase comparison

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#32247]
Under ICU, there are some non-ASCII code points that become ASCII code points after a simple case mapping transformation.

```txt
'K' (U+212A KELVIN SIGN) ~= 'k' (U+006B LATIN SMALL LETTER K) [simple lowercase mapping]
'ſ' (U+017F LATIN SMALL LETTER LONG S) ~= 'S' (U+0053 LATIN CAPITAL LETTER S) [simple uppercase mapping]
```

Since it's common for applications to use `StringComparison.OrdinalIgnoreCase` when comparing things like usernames, this could be a pit of failure for those applications, as it could lead to the following behavior at runtime.

```cs
string.Equals("administrator", "adminiſtrator", StringComparison.OrdinalIgnoreCase) // <-- FALSE on Windows, TRUE on Linux
```

A fairly straightfoward fix would be to prevent non-ASCII chars and ASCII characters from being equal under an `OrdinalIgnoreCase` comparison. It would mean that `OrdinalIgnoreCase` is no longer a direct wrapper around ICU's case mapping / case folding APIs, but it would bring the behavior more in line with what developers have come to expect over .NET's history.

With this proposal, `ToUpperInvariant` and `ToLowerInvariant` would be a direct wrapper around ICU's underlying simple case mapping APIs, and it wouldn't special-case any characters.

Related: https://github.com/dotnet/runtime/pull/27540

__The following APIs would be affected:__

 * `string.Equals`, `string.Compare`, `string.GetHashCode`, and any other APIs which might accept `StringComparison.OrdinalIgnoreCase` as a parameter
 * `StringComparer.OrdinalIgnoreCase.Equals` and `StringComparer.OrdinalIgnoreCase.GetHashCode`
 * `TextInfo.Compare` and similar APIs which might accept `CompareOptions.OrdinalIgnoreCase`

/cc @tarekgh

**Comment by tarekgh** [comment]
> prevent non-ASCII chars from becoming ASCII chars

I would recommend doing that in the case of the ordinal casing but not for invariant. The reason here is Invariant casing still treated as a cultural casing and not ordinal and it makes sense to do the right casing according to Unicode standard as most of the people using it in scenarios that not specific to compare 2 strings securely. instead, the ordinal comparison should be used at that time.

**Comment by GrabYourPitchforks** [comment]
Just to clarify, you're suggesting:

```cs
string.Equals("administrator", "adminiſtrator", StringComparison.OrdinalIgnoreCase) // <-- with this change, will return FALSE on all platforms
"administrator".ToUpperInvariant() == "adminiſtrator".ToUpperInvariant() // <-- will continue to return FALSE on Windows, TRUE on Linux
```

This means that `string.Equals(a, b, StringComparison.OrdinalIgnoreCase)` will no longer be equivalent to `string.Equals(a.ToUpperInvariant(), b.ToUpperInvariant(), StringComparison.Ordinal)`, which is a behavioral change from previous framework releases.

I'm ok with your suggestion here if you think we can swing the breaking change. :)

**Comment by tarekgh** [comment]
@GrabYourPitchforks yes you have articulated it accurately.

**Comment by GrabYourPitchforks** [comment]
@tarekgh I've updated the proposal text to match your suggestions. Thanks!

Do you suppose we'd need similar APIs `char.EqualsOrdinalIgnoreCase` or `Rune.EqualsOrdinalIgnoreCase` to accompany the string ordinal ignore case APIs? I can imagine some applications might be interested in doing the comparison on a character-by-character basis.

**Comment by tarekgh** [comment]
Char already has ToUpper/ToLower which should match the ordinal casing. Also, it has ToUpperInvariant/ToLowerInvariant for invariant case. I think the current APIs are enough for doing any needed operation.

**Comment by GrabYourPitchforks** [comment]
After this change, on Linux:

```cs
char.ToUpperInvariant('ſ') // <-- returns 'S'
"ſ".ToUpperInvariant() // <-- returns "ſ"
```

**Comment by tarekgh** [comment]
right. but I expect: 

```C#
string.Equals("ſ", "S", StringComparison.InvariantCultureIgnoreCase) // <-- returns true
```

Is that right?

**Comment by GrabYourPitchforks** [comment]
I guess my question is that in theory it should be possible to write the following code:

```cs
public static bool AreStringsEqualOrdinalCase(string a, string b)
{
    if (a.Length != b.Length) { return false; }
    for (int i = 0; i < a.Length; i++)
    {
        char charA = a[i];
        char charB = b[i];
        if (!CharsAreEqualOrdinalIgnoreCase(charA, charB)) { return false; }
    }
    return true;
}
```

And that it should behave identically to `string.Equals(a, b, StringComparison.OrdinalIgnoreCase)`, handwaving away that we should be checking for surrogates, etc.

What is the `CharsAreEqualOrdinalIgnoreCase` method in the example above? Since we don't expose such a method, a developer won't be able to write the sample method above reliably.

**Comment by tarekgh** [comment]
CharsAreEqualOrdinalIgnoreCase should be equivalent to Char.Toupper(ch1) == Char.Toupper(ch2). We want to ensure char.ToUpper is behaving as ordinal casing we are going to have.

**Comment by GrabYourPitchforks** [comment]
`char.ToUpper` is defined to be culture-aware, though.

https://github.com/dotnet/runtime/blob/0e0e852e83d5f30dfeeef7ac4999873ee10f9a4b/src/libraries/System.Private.CoreLib/src/System/Char.cs#L350-L353

We have no "ordinal" equivalent API. The closest we have is `ToUpperInvariant`.

**Comment by tarekgh** [comment]
ah, got it. I didn't know char is calling the current culture. That is sad as we already have methods on TextInfo do the cultural casing.

Thanks, for the clarification. I agree with the proposal `char.EqualsOrdinalIgnoreCase` and `Rune.EqualsOrdinalIgnoreCase`. The challenge now is how we clarify to the users which one to use :-)

**Comment by tarekgh** [comment]
@GrabYourPitchforks I marked this issue with the tag api-suggestion. do you think we need to finish this in 5.0? or can it be moved to the future?

**Comment by GrabYourPitchforks** [comment]
There's no API being proposed here. I think we should still tackle this in the 5.0 timeframe. It would dovetail nicely with the ICU work you're already doing.

**Comment by tarekgh** [comment]
@GrabYourPitchforks this comment https://github.com/dotnet/runtime/issues/32247#issuecomment-585977147 kind of suggesting a new APIs too.

**Comment by GrabYourPitchforks** [comment]
@tarekgh Ah, got it. I'll open a separate API proposal for those.

**Comment by tarekgh** [comment]
@GrabYourPitchforks if we are going to expose new APIs, shouldn't we break the current behavior? and we ask devs to use the new APIs for correct scenarios?

**Comment by GrabYourPitchforks** [comment]
@tarekgh, not quite sure I follow. You're suggesting that both the current APIs and the new APIs get the new behavior?

**Comment by tarekgh** [comment]
I am trying to say, don't change the current APIs behavior and have the new behavior in the new exposed APIs.

**Comment by GrabYourPitchforks** [comment]
So the current APIs would continue to have the behavior described below?

```cs
Console.WriteLine(string.Equals("administrator", "adminiſtrator", StringComparison.OrdinalIgnoreCase)); // prints True (on Linux)
```

**Comment by tarekgh** [comment]
Right. I think this can be acceptable. and the new proposed APIs can provide more control over the comparison as desired.

**Comment by GrabYourPitchforks** [comment]
I guess one of the things bugging me is that Unicode defines 4 ways to perform case-insensitive text comparison, and `OrdinalIgnoreCase` just kind of does its own thing that doesn't match any of them. 😊 See specifically https://www.unicode.org/versions/Unicode13.0.0/ch03.pdf, Sec. 3.13, definitions D144 - D147.

Our `OrdinalIgnoreCase` attempts to detect certain cases (see the comment in the opening description for https://github.com/dotnet/runtime/pull/27540), but it doesn't detect these special cases reliably. So I'd like to see us either fix the special-casing (which was the proposal for this issue) or to drop the special-casing entirely.

If we wanted to expose the 4 case-insensitive text comparison algorithms as their own separate APIs I can be sold on that idea.

**Comment by tarekgh** [comment]
I agree then fixing them as you described in the issue.

**Comment by GrabYourPitchforks** [comment]
@tarekgh One more quick question on `ToUpperInvariant` / `ToLowerInvariant`: should they allow for producing a result string whose length differs from the input?

On Windows, the behavior of these APIs is that they iterate through the string char-by-char, changing the case of each char in isolation. Each input char maps exactly to one output char (or to itself, if no case conversion exists). So the result string has the exact same length as the input string.

Today's behavior for `ToUpperInvariant` / `ToLowerInvariant` when under ICU is to do something similar. We manually iterate through the strings char-by-char, as shown below. So the result string will still have the same length as the input string.

https://github.com/dotnet/runtime/blob/75036ffec9473dd1d948c052c041fdedd7784ac9/src/libraries/Native/Unix/System.Globalization.Native/pal_casing.c#L40-L49

ICU's _normal_ case changing APIs (such as [`u_strToUpper`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ustring_8h.html#a14740e3b734ffa82205d4762fcacb5e1)) do not make this same guarantee. For example, the string `"ß"` will uppercase-convert to `"SS"` when run through ICU's normal uppercase conversion routine, even when specifying a null locale. This matches the recommended behavior in the Unicode Specification, Ch. 3, Sec. 3.13, Rule R1.

I think at the moment quite a bit of code relies on `ToUpperInvariant` / `ToLowerInvariant` not changing the length of the resulting string. So maybe a different API would be needed for these "pure ICU" cases so that we don't break the world. But wanted to get your opinion on this nonetheless.

**Comment by tarekgh** [comment]
I would expose new APIs to support different length for compact reason. I saw a usage before that consumer of the APIS always assumed the same input length.

**Comment by jkotas** [comment]
> I think at the moment quite a bit of code relies on ToUpperInvariant / ToLowerInvariant not changing the length of the resulting string

Do you have examples? We should look at how bad is this.

It is not pretty to have old broken and new correct versions of the same APIs. It has negative value in the long run. We had the same problem with floating point formatting changes, and we choose to fix the existing APIs.

**Comment by GrabYourPitchforks** [comment]
> Do you have examples? We should look at how bad is this.

Within the runtime and libraries:

https://github.com/dotnet/runtime/blob/1124c1ac95bf1b74b4a030fc21ef0b9f58e33b07/src/libraries/System.Private.CoreLib/src/System/MemoryExtensions.Globalization.cs#L317-L319

https://github.com/dotnet/runtime/blob/d5be85531a90aadd5e38e21e0d49bb145f39b737/src/libraries/System.Private.CoreLib/src/System/Marvin.OrdinalIgnoreCase.cs#L81-L82

https://github.com/dotnet/runtime/blob/d5be85531a90aadd5e38e21e0d49bb145f39b737/src/libraries/System.Private.CoreLib/src/System/Globalization/TextInfo.cs#L397

https://github.com/dotnet/machinelearning/blob/cdb1e4b38308d9256cbde9e740a14b3bc7d64c2f/src/Microsoft.ML.Transforms/Expression/BuiltinFunctions.cs#L716-L724

Within application code, I assume the biggest pit of failure would be people who call `MemoryExtensions.To{Upper|Lower}Invariant`. But I have no easy way of auditing those call sites.

**Comment by jkotas** [comment]
`MemoryExtensions.To{Upper|Lower}Invariant` - these are new APIs, they won't be used that much.

**Comment by tarekgh** [comment]
This is fixed by the PR https://github.com/dotnet/runtime/pull/40910.
