### ISSUE TITLE
Adjusting additionalProbingPaths for AssemblyDependencyResolver

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#32266]
I have a .NET Core global tool, https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool, that a user points to their build output folder and it loads their code and runs it within the process of the tool. In .NET Core 2.1 I had my hacky version of loading the user provided assembly and its dependencies using DependencyContext and other pieces of code from Microsoft.Extensions.DependencyModel which worked mostly okay.

For .NET Core 3.1 I wanted to switch to use the new AssemblyDependencyResolver. This works great when I'm debugging the tool but when I deploy the tool it fails to find the assemblies that are referenced and stored in the NuGet cache. It works when I debug the tool because my tool's runtimeconfig.dev.json file contains the entries for `additionalProbingPaths` that include the NuGet cache.

Is there a way to tell the process or AssemblyDependencyResolver to include the nuget cache folder for additionalProbingPaths. So far all of my investigation with adding additionalProbingPaths in the runtimeconfig.json has required a full directory path, including username, which isn't a portable solution.

**Comment by elinor-fung** [comment]
I don't think there is a way of doing this through `AssemblyDependencyResolver` right now.

The fact that the probing paths for the app (`.runtimeconfig[.dev].json`, `--additionalProbingPath`) is used by `AssemblyDependencyResolver` is not ideal. We have an open issue around separating the two and allowing customization of the probing paths used by `AssemblyDependencyResolver`. See #3835 for details and comments on options. I believe the first proposed option- supporting adding probing paths on `AssemblyDependencyResolver` - would be what you want.

Meanwhile, you could keep `PackageCompilationAssemblyResolver` from `Microsoft.Extensions.DependencyModel` as a fallback for if `AssemblyDependencyResolver` doesn't resolve the assembly.

**Comment by normj** [comment]
Alright I'll add the fallback using PackageCompilationAssemblyResolver back in. I'll close this issue in favor of tracking the feature request with https://github.com/dotnet/runtime/issues/3835
