### ISSUE TITLE
Feature Request: Enhance Stream with ability to read into unsafe pointer

### ISSUE THREAD

**Issue by rds1983** [dotnet/runtime#32282]
Right now, Stream.Read function accepts only byte[] argument as read destination.
However sometimes it is required to call it upon unsafe pointer.
For now the only solution is to create temporary buffer. 
Like:
```c#
  var temp = new byte[size];
  int read = stream.Read(temp, 0, size);
  Marshal.Copy(temp, 0, new IntPtr(ptr), read);
```
Such overhead could be easily avoided, since at least FileStream and MemoryStream can potentially read into unsafe pointer.

From the API perspective, this case could be solved by introducing new interface(and making capable Streams implement it):
```c#
  public unsafe interface IUnsafeStream
  {
    int Read (void *buffer, int offset, int count);
  }
```

Then code for reading into unsafe pointer would become:
```c#
  var asUnsafeStream = stream as IUnsafeStream;
  if (asUnsafeStream != null) 
  {
    asUnsafeStream.Read(ptr, 0, size);
  } 
  else 
  {
    // IUnsafeStream not supported, so do it old way
    var temp = new byte[size];
    int read = stream.Read(temp, 0, size);
    Marshal.Copy(temp, 0, new IntPtr(ptr), read);
  }
```

**Comment by vcsjones** [comment]
Starting in .NET Core 2.1 there is [`Read(Span<byte>)`][1].

Span has a [constructor][2] that allows passing a pointer. So you could do something like:

```csharp
void* ptr;
Span<byte> ptrSpan = new Span<byte>(ptr, size);
stream.Read(ptrSpan);
```

[2]: https://docs.microsoft.com/en-us/dotnet/api/system.span-1.-ctor?view=netcore-2.1#System_Span_1__ctor_System_Void__System_Int32_

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netcore-2.1#System_IO_Stream_Read_System_Span_System_Byte__

**Comment by rds1983** [comment]
Cool, thanks for the reply.
That would solve the case.
