### ISSUE TITLE
HashSet<T>.UnionWith() vs ctor(Enumerable<T>) performance.

### ISSUE THREAD

**Issue by idstam** [dotnet/runtime#32285]
On and empty HashSet<T> using UnionWith is slower than using the constructor that takes an Enumerable<T>. 
The larger the source set is the larger the performance difference get.

Would a viable change be to check for the special case that the set is empty in UnionWith and run "the same" code as the constructor if it is?

This is closely related to [HashSet constructor perf optimization concern #16001](https://github.com/dotnet/runtime/issues/16001).
and explicitly ignored in the fix for #16001:  [Improve memory use of HashSet constructed from HashSet. #5147](https://github.com/dotnet/corefx/pull/5147).

WIth one item in the source the code below takes 80 ms for UnionWith and 70 with the .ctor.
With five items UnionWith takes 180 ms and the .ctor still about 70 ms.

I ran the test on 3.1.100 in Ubuntu.

```
        static void Main(string[] args)
        {
            var sw = new Stopwatch();

            var src = new HashSet<string>();
            src.Add("Alice");
            // src.Add("Bob");
            // src.Add("Charlie");
            // src.Add("Damian");
            // src.Add("Elisabeth");

            sw.Start();
            for(int i = 0; i < 100000; i++){
                var hs = new HashSet<string>();
                hs.UnionWith(src);
            }

            sw.Stop();
            Console.WriteLine(sw.ElapsedMilliseconds);

            sw.Restart();
            for(int i = 0; i < 100000; i++){
                var hs = new HashSet<string>(src.AsEnumerable<string>());
            }

            sw.Stop();
            Console.WriteLine(sw.ElapsedMilliseconds);
        }

```

**Comment by scalablecory** [comment]
`UnionWith` is a more involved operation: it needs to compare the two sets. The constructor doesn't compare anything, it just inserts.

`UnionWith` could be optimized to special-case for an empty collection, but I don't know how much benefit that see in real-world code.

**Comment by idstam** [comment]
I stumbled on it trying to make Manatee.Json's schema validator faster. There it would have made a huge difference, but I can't even guess if that extra check would be worth the cost for all use cases that don't need it.
