### ISSUE TITLE
using Serialize fails but the Newtonsoft version works

### ISSUE THREAD

**Issue by Greypuma** [dotnet/runtime#32294]
I was trying to serialize an object into json. I get an empty string. below is the code i used.
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace test
{
    public class AdbEmulator
    {
        //needs to be public otherwise wont work
        public string name;
        internal string attached;

    }
    public class AndroidJson
    {
        public AndroidJson()
        {
            AddData();
        }
        public void AddData()
        {
            AdbEmulator adb1 = new AdbEmulator() { name = "emulator-5554", attached = "ll" };
            emulators.Add(adb1);
            string jsonAdb = System.Text.Json.JsonSerializer.Serialize<AdbEmulator>(adb1);
            string newtonjson = Newtonsoft.Json.JsonConvert.SerializeObject(adb1);
        }
    }

Program.cs
        static void Main(string[] args)
        {            AndroidJson aj = new AndroidJson();    }

Output
jsonAdb = {}
newtonjson ={"name":"emulator-5554"}

I'm not sure why newtonsoft works and the microsoft one does not.
i'v'e tried the code in an dotnet core 3.1 project and windows application ( including the nuget package for that project).

**Comment by GalaxiaGuy** [comment]
Serializing fields is not yet supported:
https://github.com/dotnet/runtime/issues/876

**Comment by ahsonkhan** [comment]
@Greypuma, if you turn your fields into properties it should work as expected. Please re-open if you still see issues.

Thanks.

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

namespace test
{
    public class AdbEmulator
    {
        //needs to be public otherwise wont work
        public string name {get; set;}
        internal string attached;
    }
}
```
