### ISSUE TITLE
BitOperations.RotateRight should emit rorx for constant offset

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#32290]
```csharp
public uint RotateRightBy1(uint x)
{
    return BitOperations.RotateRight(x, 1); // any constant
    // return (value >> c) | (value << (32 - c));
}
```
When `offset` is a const in `BitOperations.RotateRight` (same for `RotateLeft`) we can emit a slightly faster `rorx` instead of `rol`
### Current codegen:
```asm
       mov      eax, edx
       rol      eax, 31
       ret 
```
### Expected codegen (e.g. [LLVM](https://godbolt.org/z/MiUaZr))
```asm
       rorx     eax, edx, 1
       ret
```

**RORX**
> Rotates the bits of second operand right by the count value specified in imm8 without affecting arithmetic flags. The RORX instruction does not read or write the arithmetic flags.
It's part of `BMI2` set.

**Comment by EgorBo** [comment]
E.g. it's used in String's GetHashCode algorithm: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Marvin.cs#L232-L242

**Comment by EgorBo** [comment]
hm... looks like rorx and rol are the same in terms of latency and throughput on Skylake, Skylake-X and Zen for `r, i` (general purpose register and constant).
I guess the only advantage is `rorx` doesn't need that move and way faster for memory operand instead of gp register.

**Comment by GrabYourPitchforks** [comment]
Even with an equivalent latency, keeping the codegen small in tight loops like the `GetHashCode` example you mentioned earlier is goodness. :)

**Comment by tannergooding** [comment]
We don't seem to have exposed `rorx`, `sarx`, `shrx`, or `shlx` under `Bmi2`. I don't see any issue or previous discussion on this so I'm guessing it was purely just oversight.

**Comment by tannergooding** [comment]
This is a framework improvement that would require JIT changes to make happen. Do we want to track this as `area-codegen` or `area-System.Numerics`, or possibly both? @BruceForstall, @jkotas?

**Comment by BruceForstall** [comment]
@tannergooding Seems like it should be added via the usual intrinsics mechanism first, then we can optionally add a JIT optimization to use it in other situations (although I'm not sure we currently have ISA-specific opts, so that might be new and require some thinking). So I'd vote `area-System.Numerics`.

**Comment by tannergooding** [comment]
> although I'm not sure we currently have ISA-specific opts

We do in a few minimal places, but I think most of them are optimizations on already intrinsic methods. For example, `Math.FusedMultiplyAdd` will be accelerated if `Fma.IsSupported` and `Math.Round` will be if `Sse41.IsSupported`. It would likely be similar for `System.Numerics.BitOperations.RotateLeft`, but I think `x << y` and related would be a new thing (if we wanted to accelerate that to `shlx`).

**Comment by jkotas** [comment]
> Do we want to track this as `area-codegen` or `area-System.Numerics`

I think it should be tracked as area-codegen

> it should be added via the usual intrinsics mechanism first

I do not think we should be exposing intrisics for very standard operations like integer rotate. They should just be handled by the JIT without cluttering the public surface.
