### ISSUE TITLE
Undefined behavior in TimeZoneInfo.ConvertTime

### ISSUE THREAD

**Issue by reillymarkowitz** [dotnet/runtime#32317]
# Issue Title

Converting DateTime.MinValue from EST to UTC returns 0001-01-01 04:57:00 instead of 0001-01-01 05:00:00.

# General

* .NET Core version: discovered on 2.1, reproduced on 3.1
* OS: macOS 10.14.6

Contents of test method:
```csharp
var minDate = DateTime.MinValue;
var convertedDate = TimeZoneInfo.ConvertTime(minDate,
    TimeZoneInfo.FindSystemTimeZoneById("America/New_York"),
    TimeZoneInfo.FindSystemTimeZoneById("UTC")
);
            
Assert.AreEqual(minDate.AddHours(5), convertedDate);
```
Test result:
```
Expected: 0001-01-01 05:00:00
But was:  0001-01-01 04:57:00
```

**Comment by scalablecory** [comment]
@tarekgh

**Comment by Clockwork-Muse** [comment]
If I'm reading [this (surprisingly coincidental) example rule offset correctly](https://en.wikipedia.org/wiki/Tz_database#Example_zone_and_rule_lines), I think this is actually expected.  The offset [does change to the "expected" one after the date in the initial rule line](https://dotnetfiddle.net/iiJ2zi).

I'd heard about these strange offsets before, but in terms of various Asian countries in like the 1940s or something.  Essentially, countries aligned themselves to GMT (no UTC yet) from whatever they were using before (usually local solar noon), which means that there's a lot of these strange offsets for first entries.

**Comment by reillymarkowitz** [comment]
If this is expected behavior, shouldn't it be consistent across platforms? The test above passes on Windows.

**Comment by Clockwork-Muse** [comment]
No.

Like a number of globalization areas (notably string operations), we depend on the OS to provide certain raw data and behavior.  Timezone rules are one of those things.  Windows already has a slightly different set of timezones anyways (or did).

**Comment by tarekgh** [comment]
@Clockwork-Muse is correct in both answers. We are planning in the future to try to unify the behavior of the time zone when we start using ICU on Windows. But this may be in the future release (post 5.0 release) as in 5.0 release we are focusing on Globalization areas first and then we'll look at other areas like time zones. I am closing this issue per discussion but feel free to send any more questions if you have any.
