### ISSUE TITLE
[merp] Add mono-hang-watchdog binary for crash reporting

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#32325]
We had a [mono-hang-watchdog](https://github.com/mono/mono/tree/master/tools/mono-hang-watchdog) tool that was installed next to Mono that was responsible for killing crash reporting if it the process was too far gone to generate a crash report properly.

We need to bring it back (or something like it) - VS4M crash reporting experience depends on it.

/cc @alexischr

**Comment by karelz** [comment]
@lambdageek only 1 area label please.

**Comment by lambdageek** [comment]
Depends on outcome of https://github.com/dotnet/runtime/issues/32117

**Comment by lambdageek** [comment]
MERP has been removed from mono in dotnet/runtime
