### ISSUE TITLE
Investigate caching the underlying internal converters like KeyValuePairConverter

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#32352]
https://github.com/dotnet/runtime/blob/d4b06b1a9e3c56e343c42efad2211c04c196a0cf/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/KeyValuePairConverter.cs#L18-L20

cc @steveharter

**Comment by layomia** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/32148.
