### ISSUE TITLE
Consider using the converters and JsonClassInfo from s_defaultOptions by cloning

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#32357]
https://github.com/dotnet/runtime/blob/d4b06b1a9e3c56e343c42efad2211c04c196a0cf/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L332-L343

cc @steveharter

**Comment by steveharter** [comment]
The comment and a cloning approach is feasible, but moving to Future since it will tie together with memory conservation work planned for Future by https://github.com/dotnet/runtime/issues/1568
