### ISSUE TITLE
Figure out the best flush threshold for serializer based on performance and real-world use cases

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#32356]
It's currently set to flush when the buffer is 90% full.

https://github.com/dotnet/runtime/blob/d4b06b1a9e3c56e343c42efad2211c04c196a0cf/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs#L80

cc @steveharter

**Comment by layomia** [comment]
Triage: change the comment to say if we have a lot of customers with large objects and we are flushing too often, make the buffer bigger; and close the issue.
