### ISSUE TITLE
Test failure in Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#32379]
Failure in jitstress leg, including minopts, on Linux/x64 and OSX/x64.

https://dev.azure.com/dnceng/public/_build/results?buildId=522626&view=ms.vss-test-web.build-test-results-tab&runId=16559610&resultId=100041&paneView=debug

New test added by https://github.com/dotnet/runtime/pull/32034

`\nAssert failure(PID 11754 [0x00002dea], Thread: 11754 [0x2dea]): Assertion failed '!varTypeIsFloating(targetType) || (targetType == op1->TypeGet())' in 'ILStubClass:IL_STUB_PInvoke(float,float):System.Numerics.Vector2' during 'Linear scan register alloc' (IL size 42)\n\n File: /__w/10/s/src/coreclr/src/jit/codegenxarch.cpp Line: 4642\n Image: /home/helixbot/work/A6DE0912/p/corerun\n\n/home/helixbot/work/A6DE0912/w/B55D0992/e/Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh: line 275: 11754 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"\n\nReturn code: 1\nRaw output file: /home/helixbot/work/A6DE0912/w/B55D0992/e/Interop/PInvoke/Reports/Interop.PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.output.txt\nRaw output:\nBEGIN EXECUTION\n/home/helixbot/work/A6DE0912/p/corerun Vector2_3_4.dll ''\nWriting minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.11754.dmp\nWritten 51171328 bytes (12493 pages) to core file\nExpected: 100\nActual: 134\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/A6DE0912/p\n> /home/helixbot/work/A6DE0912/w/B55D0992/e/Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh\nExpected: True\nActual: False`

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by VincentBu** [comment]
This test failed again.
**Job:**
[runtime-coreclr gcstress-extra 20200221.2](https://dev.azure.com/dnceng/public/_build/results?buildId=532809&view=ms.vss-test-web.build-test-results-tab
)

**Related tests:**
Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh

**Error message:**
`
\nAssert failure(PID 318 [0x0000013e], Thread: 318 [0x013e]): Assertion failed '!varTypeIsFloating(targetType) || (targetType == op1->TypeGet())' in 'ILStubClass:IL_STUB_PInvoke(System.Numerics.Vector2,Vector2Callback):System.Numerics.Vector2' during 'Linear scan register alloc' (IL size 72)\n\n File: /__w/10/s/src/coreclr/src/jit/codegenxarch.cpp Line: 4642\n Image: /home/helixbot/work/B9D509BE/p/corerun\n\n/home/helixbot/work/B9D509BE/w/A6430928/e/Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh: line 275: 318 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"\n\nReturn code: 1\nRaw output file: /home/helixbot/work/B9D509BE/w/A6430928/e/Interop/PInvoke/Reports/Interop.PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.output.txt\nRaw output:\nBEGIN EXECUTION\n/home/helixbot/work/B9D509BE/p/corerun Vector2_3_4.dll ''\nWriting minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.318.dmp\nWritten 52482048 bytes (12813 pages) to core file\nExpected: 100\nActual: 134\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/B9D509BE/p\n> /home/helixbot/work/B9D509BE/w/A6430928/e/Interop/PInvoke/Vector2_3_4/Vector2_3_4/Vector2_3_4.sh\nExpected: True\nActual: False
`

**Comment by v-haren** [comment]
failed again in job:
[runtime-coreclr jitstress](https://dev.azure.com/dnceng/public/_build/results?buildId=533451&view=ms.vss-test-web.build-test-results-tab&runId=16935280&resultId=100032&paneView=debug)
[runtime-coreclr jitstress2-jitstressregs](https://dev.azure.com/dnceng/public/_build/results?buildId=533684&view=ms.vss-test-web.build-test-results-tab&runId=16939972&resultId=108033&paneView=debug)
