### ISSUE TITLE
Generic Append for StringBuilder

### ISSUE THREAD

**Issue by Entomy** [dotnet/runtime#32380]
Currently, [`StringBuilder`](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder) does not have a generic variant of [`.Append()`](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append), and relies on the `Object` overload to provide full coverage. The issue with this is, it's a boxing conversion for `struct` types that are not among the primitives already defined. While a minor thing, it would still reduce boxing by a bit, right? Or is this still occurring for some reason I'm not aware of.

**Comment by stephentoub** [comment]
If such boxing is an issue, wouldn't it be better for the call site to just do .ToString(), and avoid both the boxing and the generic instantiations? StringBuilder is otherwise just going to call that same ToString.

**Comment by Entomy** [comment]
I was just thinking some minor syntactic sugar, since it would make things orthogonal. But yes, this is how I've been doing it.

**Comment by fbrosseau** [comment]
Could it interface-check to leverage the ISpanFormattable interface? (Which has an ongoing suggestion of making public in #26374)

That would make it have more added value than just doing the ToString for you.

**Comment by Entomy** [comment]
I think so; it looks like it would. In that case, yeah, that's fine. The intent is just to cut back on boxing without requiring new syntax, since I've seen a lot of people forget that happens. As long as it accomplishes that, I'm happy.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/runtime/issues/27427, where we added `StringBuilder.Append(ROM<char>)` to avoid the intermediate boxing + allocation that the `StringBuilder.Append(object)` overload would have performed.

**Comment by Entomy** [comment]
Nevermind, I'll do it myself, again.
