### ISSUE TITLE
PreProcessor files for easy Progmatic PreProcessor Definitions

### ISSUE THREAD

**Issue by KoromaruKoruko** [dotnet/runtime#32412]
so, this is a feature request, that might as well be for MSBuild as a whole. but no clue where to post that so....

The Problem: You have a library that you want to make possible to disable or remove certain features that you wouldn't need in a safe and practical way And you do this via PreProcessor Directives but if you wish to take it up a notch and make large libraries with multiple disablable portions you quickly run into the issue of preprocessors taking up a large portion of every file and being mostly unreadable or you needing to define multiple PreProcessors combine this with open source and having the end-user define what they need and what they don't you have an almost impossible problem. Currently only remedied via custom or cumbersome PreCompilers or Pre-Compile Processors which just add to the complexity of a project.

The Suggestion: a new file type for MSBuild *.ppf (Pre Processor File) a file that just consists of preprocessor directives, that will get processed and the resulting state will then constitute the global preprocessing state, IE if you have something like this.

[MyPreprocessor.pff]
```
#if Custom_Disable_Directive1
    #define Disabled_Internal_Something_Directive 
    #if Conflicting_Directive
          #error X depends on Y, You must choose
    #endif
#endif
```

the code above would be run before processing all the other files and all defined processors added to the global store to act across all cs files.

**Comment by adamsitnik** [comment]
Hi @KoromaruKoruko 

This repo is for .NET Core Runtime and Base Class Libraries related issues. Your proposal seems like an MSBuild feature request. I can't transfer issues from dotnet/runtime to microsoft/msbuild repository (it's two different GH orgs) so I am going to close and ask you to open a new issue in https://github.com/microsoft/msbuild

Thank you and have a nice day!
