### ISSUE TITLE
README of referencesource links to old blog

### ISSUE THREAD

**Issue by binki** [dotnet/runtime#32424]
If I visit https://github.com/microsoft/referencesource/tree/17b97365645da62cf8a49444d979f94a59bbb155#readme , there is a link to http://blogs.msdn.com/b/dotnet/archive/2014/11/12/net-core-is-open-source.aspx . This links to a page saying that the blogs have moved.

Can this be fixed to point to the correct archived blog post?

I am filing this issue here because https://github.com/microsoft/referencesource/tree/17b97365645da62cf8a49444d979f94a59bbb155#readme says to file issues for the repo at https://github.com/dotnet/corefx which says issues should be filed at https://github.com/dotnet/runtime .

**Comment by vcsjones** [comment]
Thanks for pointing that out, a few links have been fixed.
