### ISSUE TITLE
.NET Core 3.1 publish as single-file can not run on CentOS 7.7 directly.

### ISSUE THREAD

**Issue by supershowwei** [dotnet/runtime#32428]
In Visual Studio 2019 v16.4.5, I create a ASP.NET Core MVC project from project template, and publish to single file, target is linux-x64, and .NET Core SDK is 3.1.101.

The binary file published can not run on CentOS 7.7 and .NET Core runtime is 3.1, message is "-bash: xxx: command not found", what steps did I miss ?

**Comment by swaroop-sridhar** [comment]
@supershowwei: To understand the scenario better, can you please answer the following questions: 
* Is this app published self-contained or framework dependent? 
* If you *publish* the app as a non-single file `linux-x64` are you able to run it on Centos? 
* Does the published single-file app have the correct execute permissions when copied to the Centos machine? 

Thanks.

**Comment by supershowwei** [comment]
thanks for your reply.

- Is this app published self-contained or framework dependent?

self-contained and framework dependent I tried.

- If you publish the app as a non-single file linux-x64 are you able to run it on Centos?

yes, it works fine. my project name is "LessDowntimeLab" and 'dotnet LessDowntimeLab.dll' command I executed. take look the picture as followed.

![](https://i.imgur.com/2Kkzfri.png)

I execute 'LessDowntimeLab' as owner directly when I published single-file, I got messages as followed picture.

![](https://i.imgur.com/SaQZPSc.png)

this is my CentOS version.

![](https://i.imgur.com/1IzIdfs.png)

this is my .NET Core Runtime version.

![](https://i.imgur.com/4qEASke.png)

this is my publishing settings, but in Chinese.

![](https://i.imgur.com/pbr5BMj.png)

- Does the published single-file app have the correct execute permissions when copied to the Centos machine?

yes, I checked it.

**Comment by vitek-karas** [comment]
Maybe I'm wrong, but when I run executables on Linux I must always specify a relative path, like `./LessDowntimeLab`. I think it's because the current directory is not part of `PATH` on Linux (at least by default).

**Comment by supershowwei** [comment]
my mistake, i miss `./`, thank you.
