### ISSUE TITLE
Test failure: System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32449]
https://dnceng.visualstudio.com/public/_build/results?buildId=524564&view=ms.vss-test-web.build-test-results-tab&runId=16605164&resultId=109051&paneView=debug

netcoreapp5.0-OSX-Release-x64-Mono_release-OSX.1014.Amd64.Open

Executed on **dci-macpro-03.local**

```
Assert.True() Failure\nExpected: True\nActual: False
  at System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6() in /_/src/libraries/System.Drawing.Common/tests/GdiplusTests.cs:line 17
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
```

@ilyas1974 @MattGal it looks like https://github.com/dotnet/core-eng/issues/8943 regressed again...

cc @safern

**Comment by ViktorHofer** [comment]
Happened again multiple times: https://dnceng.visualstudio.com/public/_build/results?buildId=525159&view=ms.vss-test-web.build-test-results-tab

**Comment by ilyas1974** [comment]
Let me follow up with DDFUN.

**Comment by MattGal** [comment]
@ViktorHofer we have not closed dotnet/core-eng#8943 yet so it can't have regressed until we think that's the case.  

Checking out the state this morning, dci-macpro-03 has been fixed up; here's four separate times it passed that test:
[Example](https://helixre107v0xdeko0k025g8.blob.core.windows.net/results-7def1c9f77434752a1/inspecting-gdi-state-14/console.c60ddc44.log?sv=2019-02-02&se=2020-02-28T16%3A55%3A26Z&sr=c&sp=rl&sig=Na0uuoAlSHKFAz%2BpbZ91r%2Fqk7ogUgcSYzBEnK0OZSlY%3D)
[Example](https://helixre107v0xdeko0k025g8.blob.core.windows.net/results-7def1c9f77434752a1/inspecting-gdi-state-63/console.9b7bf731.log?sv=2019-02-02&se=2020-02-28T16%3A55%3A26Z&sr=c&sp=rl&sig=Na0uuoAlSHKFAz%2BpbZ91r%2Fqk7ogUgcSYzBEnK0OZSlY%3D)
[Example](https://helixre107v0xdeko0k025g8.blob.core.windows.net/results-7def1c9f77434752a1/inspecting-gdi-state-122/console.5880ca93.log?sv=2019-02-02&se=2020-02-28T16%3A55%3A26Z&sr=c&sp=rl&sig=Na0uuoAlSHKFAz%2BpbZ91r%2Fqk7ogUgcSYzBEnK0OZSlY%3D)
[Example](https://helixre107v0xdeko0k025g8.blob.core.windows.net/results-7def1c9f77434752a1/inspecting-gdi-state-177/console.aa373570.log?sv=2019-02-02&se=2020-02-28T16%3A55%3A26Z&sr=c&sp=rl&sig=Na0uuoAlSHKFAz%2BpbZ91r%2Fqk7ogUgcSYzBEnK0OZSlY%3D)

Checking this mornign there's still three 10.13 machines (dci-mac-build-015, dci-mac-build-042, and dci-mac-build-013) that DDFUN hasn't gotten to yet, after that 10.13 and 10.14 should be ready; however until you see the state of the linked issue be closed please do not assume that things are fixed and subsequent failures are not "regressions";  it's just very slow to get manual changes applied to machines.

**Comment by safern** [comment]
@ViktorHofer I'll put up a PR to disable the test until the core-eng issue is closed.

**Comment by ViktorHofer** [comment]
@safern according to @MattGal, those machine were just taken offline. No need to disable the test.

**Comment by safern** [comment]
Yeah. I'm speaking with him offline. Thanks 😄

**Comment by carlossanlop** [comment]
I am seeing this failure happening again in release/6.0. This unrelated PR hit it:
https://github.com/dotnet/runtime/pull/81800/checks?check_run_id=11185960497

Queue: `Libraries Test Run release mono OSX x64 Debug failed`
Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=163717&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=5d5289b6-723b-5155-5d15-b590d280a14a&l=58
Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81800-merge-e5b0dff6d0bf494cab/System.Drawing.Common.Tests/1/console.d7c03e61.log?helixlogtype=result
Callstack:
```
    System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/GdiplusTests.cs(14,0): at System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(370,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by teo-tsirpanis** [comment]
Closing as libgdiplus is no longer supported.
