### ISSUE TITLE
Should UnobservedTaskExceptionEventArgs.Exception be nullable?

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#32454]
The only place the framework creates it, it never passes null:

https://github.com/dotnet/runtime/blob/76b4d64bd6510921fee46dbb7f2fd5613ab71e35/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskExceptionHolder.cs#L65-L69

I'm not sure how it could even be usefully consumed without providing an exception instance. This seems similar to https://github.com/dotnet/runtime/issues/30997. @stephentoub Would the same thing you said there potentially apply here?

> Seems fine. If we believe framework code is in reality the only producer of this EventArgs type, and that even it weren't it would never make sense to create one with a null name, then a non-nullable name is the intent, and regardless of whether it checks for null, we can annotate it as non-nullable.

Current definition:

https://github.com/dotnet/runtime/blob/76b4d64bd6510921fee46dbb7f2fd5613ab71e35/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskScheduler.cs#L621-L648

**Comment by stephentoub** [comment]
I think changing both the ctor parameter and the property is reasonable.
