### ISSUE TITLE
Update eng/illink.targets not duplicate configuration settings 

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#32453]
which are already available in https://github.com/mono/linker/blob/e5d6b69677dfc0da19c5b2c96b3466e8d5016327/src/ILLink.Tasks/ILLink.Tasks.targets#L8, in particular, `_LinkTaskTFM` and `_LinkTaskDirectoryRoot`

**Comment by ericstj** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/31359
