### ISSUE TITLE
Proposal: ChannelWriter<T>.DroppedWrites counter

### ISSUE THREAD

**Issue by declspec** [dotnet/runtime#32465]
As far as I'm aware, when operating a `BoundedChannel<T>` with a `BoundedChannelFullMode` of any of the `Drop*` variants there is no way to tell when and how many writes start being dropped. In all cases the call to `TryWrite` will succeed and the producer will be none the wiser.

It would be nice feature to have a `DroppedWrites` counter (or something that performs a similar function) that increments whenever a channel drops a pending write from the queue. Something like the following:

```cs
var channel = Channel.CreateBounded<object>(new BoundedChannelOptions(10) {
    FullMode = BoundedChannelFullMode.DropOldest
});

for (var i = 0; i < 20; ++i) {
    Debug.Assert(channel.Writer.TryWrite((object)i));
}

Debug.WriteLine(channel.Writer.DroppedWrites); // should output '10' at this point.
```

**Comment by matttrawicki** [comment]
👍 I find the Channels very intriguing but unusable as implemented. I need to know when the channel is full and writes are being blocked/dropped. Even a simple Count property would be a useful step.

**Comment by stephentoub** [comment]
> Even a simple Count property would be a useful step.

That now exists: https://github.com/dotnet/runtime/pull/312

**Comment by matttrawicki** [comment]
@stephentoub Thank you! I really did try to look before asking, but I missed it. 😥

**Comment by declspec** [comment]
As an alternative maybe an overload to `TryWrite` that adds an `out` parameter for communicating the action that was taken, something along the lines of:

```cs
bool TryWrite(T data, out BoundedChannelFullAction fullAction);

public enum BoundedChannelFullAction {
    None, // Channel isn't full yet
    Wait, // TryWrite == false
    DroppedOldest, // When BoundedChannelFullMode.DropOldest was specified
    DroppedNewest // When BoundedChannelFullModel.DropNewest was specified
}
```

But even just writing that out I'm not sure if it's a very nice API.

**Comment by springy76** [comment]
I don't see any counters on netcore 3.1.4

**Comment by stephentoub** [comment]
I'm going to close this as a dup of https://github.com/dotnet/runtime/issues/36522.  Such a callback can trivially be used to implement a counter if that's what's needed.  Thanks!

**Comment by declspec** [comment]
@stephentoub Yep that'll work perfectly, thanks.
