### ISSUE TITLE
Allow casting bool to int explicitly

### ISSUE THREAD

**Issue by MineCake147E** [dotnet/runtime#32469]
Sometimes I need to convert `bool` values into some kind of integral type(such as `uint`) like:
```csharp
public static int U(int y) => y > 0 ? 1 : 0;
```
which currently generates (on SharpLab x64 Release)
```asm
C.U(Int32)
    L0000: test ecx, ecx
    L0002: jg L0007
    L0004: xor eax, eax
    L0006: ret
    L0007: mov eax, 0x1
    L000c: ret
```
while
```csharp
public static bool G(int y) => y > 0;
```
becomes
```asm
C.G(Int32)
    L0000: test ecx, ecx
    L0002: setg al
    L0005: movzx eax, al
    L0008: ret
```

I need both codes compiles into same code as G(that uses `setg` instruction instead of `jg`).
## Proposal
By allowing conversion from `bool` to `int` like:
```csharp
public static int U(int y) => (int)(y > 0);
```
it can be compiled into
```asm
C.U(Int32)
    L0000: test ecx, ecx
    L0002: setg al
    L0005: movzx eax, al
    L0008: ret
```

**Comment by stephentoub** [comment]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYmpBkIYBvGgzNNdzJA148GAVQAUtjAwCeASlPmT1c/4ZgCAhJQIYAXncGAD4GOg0/ALNiAHYHLlxsADNBAEFcAB4gkLRAtwwYaMdYLMCPBP8AXxpGoA

**Comment by MineCake147E** [comment]
I'm glad to know that.
Thank you for teaching me.
Closing.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/coreclr/pull/16138, where we considered making this change in the existing method `Convert.ToInt32(bool)` but it was rejected in favor of waiting for the JIT to optimize the pattern.
