### ISSUE TITLE
Test failure in Interop Work Item

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32470]
Failure in jitstress leg, including minopts, on Linux/x64 and OSX/x64.
**Job:**
 [runtime-coreclr jitstress 20200216.1](https://dev.azure.com/dnceng/public/_build/results?buildId=524302&view=ms.vss-test-web.build-test-results-tab&runId=16597700&resultId=110165&paneView=debug)

**Comments**
{
"HelixJobId": "b326b542-30a9-4ae7-a794-c2a7cb03f5ea",
"HelixWorkItemName": "Interop"
}

**Error message**
The Work Item Failed

**Stack trace**

**Comment by VincentBu** [comment]
@v-haren , Ignore it this time. If it happen consistently, reopen it again
