### ISSUE TITLE
Proposal: ArgMax & ArgMin LINQ Extensions to IList<T>

### ISSUE THREAD

**Issue by strongrex2001** [dotnet/runtime#32471]
When calculating `min`, it is common that we need not only the value of the minimum but also the index of the element.
And when we map elements to a numerical value and get the minimum, we want to get the element more than the value.
Min LINQ extensions lack this functionality for the time being, overloads with a selector returns the numerical value after selection.

For the concept of a list index to exist, I think it should be `IList<T>.ArgMin`, not `IEnumerable<T>.ArgMin`.

Here is a simple implementation:
```csharp
/// <returns>Index of Minimum of collection. Throws exception if collection is empty.</returns>
public static int ArgMin<T> (this IList<T> collection, Comparison<T> comparison = null) {
    int cc = collection.Count;
    if (cc == 0)
        throw new InvalidOperationException ("ArgMin on Empty Collection");
    comparison = comparison ?? Comparer<T>.Default.Compare;
    T minx = collection[0];
    int mini = 0;
    for (int i = 1; i < cc; ++i) {
        if (comparison (collection[i], minx) < 0) {
            mini = i;
            minx = collection[i];
        }
    }
    return mini;
}
```

**Comment by Clockwork-Muse** [comment]
> And when we map elements to a numerical value and get the minimum, we want to get the element more than the value.

This has been proposed previously: #32471

>When calculating `min`, it is common that we need not only the value of the minimum but also the index of the element.

I'm less convinced of this; usually the index is only to retrieve the minimum element.  Returning the index usually ends up being used more in C++ code, where copy/move semantics are more a thing.

Note too that this can be done via the use of the generalist `Aggregate`.

**Comment by scalablecory** [comment]
@Clockwork-Muse you've linked to this issue; is there another you had in mind?

**Comment by strongrex2001** [comment]
Like when the index means strategies and it's an array of evaluations (there are patterns that may avoid the situation, but for efficiency or so), indexes are needed. You can get the value from the index with O(1) but you can't get the index from the value.
Or maybe, add both index and value versions.

**Comment by Clockwork-Muse** [comment]
@scalablecory - Don't know how that happened, thank you.  Corrected.

@strongrex2001 
> Like when the index means strategies and it's an array of evaluations (there are patterns that may avoid the situation, but for efficiency or so), indexes are needed. 

... Are you thinking of something like:
```csharp
var someListOfStrategies = GetList();
var listOfStrategyResults = someListOfStrategies.Select(s => s(someInput)).ToList();
```
... and then you're referencing back to the list of strategies based on the result?  I guess, but that's likely a minority use case compared to something like just including the strategy reference in the result object, especially now that we have tuples.

**Comment by strongrex2001** [comment]
Well, the index can refer to some real indexes (like row or column on a game tile map). It is surely equivalent to `Enumerator.Range (n).MinBy (x => evaluated[x])`, but I myself uses the argmin version.

**Comment by Clockwork-Muse** [comment]
... which assumes you do something to flatten any multi-dimensional arrays or quad/octrees into a single dimension; the method you've proposed can only return a single index.  If that's your real use case, LINQ is not going to be a good fit for this, since the general case is tuned mostly for single dimensional collections.

You **can** do things with lazy iterators (like [flattening a 2D array](https://stackoverflow.com/a/13823063/812837)), but you'd likely be better off either writing a custom method to return both coordinates at the same time (2D array), or modify your quad/octree implementation to perform the query (especially because dimensions are unlikely to be fixed).
