### ISSUE TITLE
Assert failure: !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#32475]
**Job:**
[runtime-coreclr gcstress-extra 20200216.1](https://dev.azure.com/dnceng/public/_build/results?buildId=524187&view=ms.vss-test-web.build-test-results-tab)

**Related tests:**
baseservices\\threading\\generics\\WaitCallback\\thread21\\thread21.cmd

**Stack trace:**
`
 at baseservices_threading._generics_WaitCallback_thread21_thread21_._generics_WaitCallback_thread21_thread21_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs:line 12653
`

**Error message:**
`
\r\nAssert failure(PID 3180 [0x00000c6c], Thread: 5664 [0x1620]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")\r\n\r\nCORECLR! Object::ValidateInner'::1'::catch$12 + 0x147 (0x00007ffa60911eb7)\r\nCORECLR! CallSettingFrame_LookupContinuationIndex + 0x20 (0x00007ffa607ae4a0)\r\nCORECLR! _FrameHandler4::CxxCallCatchBlock + 0x1DE (0x00007ffa607ac3de)\r\nNTDLL! RtlCaptureContext + 0x3C3 (0x00007ffa8ead9b03)\r\nCORECLR! Object::ValidateInner + 0x12F (0x00007ffa601f6aaf)\r\nCORECLR! Object::Validate + 0x131 (0x00007ffa601f6941)\r\nCORECLR! OBJECTREF::OBJECTREF + 0x97 (0x00007ffa601eed17)\r\nCORECLR! WKS::GCHeap::StressHeap + 0x254 (0x00007ffa60667714)\r\nCORECLR! DoGcStress + 0x340 (0x00007ffa6046f8c4)\r\nCORECLR! Thread::RedirectedHandledJITCase + 0x1E8 (0x00007ffa60038ef8)\r\n File: F:\workspace\_work\1\s\src\coreclr\src\vm\object.cpp Line: 634\r\n Image: C:\h\w\A65B093E\p\CoreRun.exe\r\n\r\n\r\nReturn code: 1\r\nRaw output file: C:\h\w\A65B093E\w\A291092A\e\baseservices\threading\Reports\baseservices.threading\generics\WaitCallback\thread21\thread21.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n "C:\h\w\A65B093E\p\corerun.exe" thread21.dll \r\nExpected: 100\r\nActual: -1073740286\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\A65B093E\p\r\n> C:\h\w\A65B093E\w\A291092A\e\baseservices\threading\generics\WaitCallback\thread21\thread21.cmd\r\nExpected: True\r\nActual: False
`

**Comment by jeffschwMSFT** [comment]
@kouvel

**Comment by briansull** [comment]
Ran this test in a loop overnight with all the different GCStress values: 1,2,4,C
It never hit any GC hole or other issue
