### ISSUE TITLE
Assert failure: SanityCheck()

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#32478]
**Job:**
[runtime-coreclr gcstress-extra 20200216.1](https://dev.azure.com/dnceng/public/_build/results?buildId=524187&view=ms.vss-test-web.build-test-results-tab)

**Related tests:**
JIT/HardwareIntrinsics/General/Vector256_1/Vector256_1_ro/Vector256_1_ro.sh

**Stack trace:**
`
at JIT_HardwareIntrinsics._General_Vector256_1_Vector256_1_ro_Vector256_1_ro_._General_Vector256_1_Vector256_1_ro_Vector256_1_ro_sh() in /__w/24/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs:line 2371
`

**Error message:**
`
\nAssert failure(PID 2968 [0x00000b98], Thread: 2968 [0x0b98]): SanityCheck()\n File: /__w/22/s/src/coreclr/src/vm/methodtable.cpp Line: 9842\n Image: /root/helix/work/correlation/corerun\n\n/root/helix/work/workitem/JIT/HardwareIntrinsics/General/Vector256_1/Vector256_1_ro/Vector256_1_ro.sh: line 275: 2968 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"\n\nReturn code: 1\nRaw output file: /root/helix/work/workitem/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/General/Vector256_1/Vector256_1_ro/Vector256_1_ro.output.txt\nRaw output:\nBEGIN EXECUTION\n/root/helix/work/correlation/corerun Vector256_1_ro.dll ''\nBeginning test case Zero.Byte at 2/16/2020 11:36:12 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:48 PM\nBeginning test case Zero.Double at 2/16/2020 11:36:48 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:49 PM\nBeginning test case Zero.Int16 at 2/16/2020 11:36:49 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:49 PM\nBeginning test case Zero.Int32 at 2/16/2020 11:36:49 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:49 PM\nBeginning test case Zero.Int64 at 2/16/2020 11:36:49 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:49 PM\nBeginning test case Zero.SByte at 2/16/2020 11:36:49 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:49 PM\nBeginning test case Zero.Single at 2/16/2020 11:36:49 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:50 PM\nBeginning test case Zero.UInt16 at 2/16/2020 11:36:50 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:50 PM\nBeginning test case Zero.UInt32 at 2/16/2020 11:36:50 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:50 PM\nBeginning test case Zero.UInt64 at 2/16/2020 11:36:50 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:50 PM\nBeginning test case As.Byte at 2/16/2020 11:36:50 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunGenericScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:36:56 PM\nBeginning test case As.Double at 2/16/2020 11:36:56 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\nBeginning scenario: RunBasicScenario\nBeginning scenario: RunGenericScenario\nBeginning scenario: RunReflectionScenario\n\nEnding test case at 2/16/2020 11:37:04 PM\nBeginni
`

category:correctness
theme:testing
skill-level:expert
cost:medium

**Comment by AndyAyersMS** [comment]
This passes with #32674, so closing as dup of #31770.
