### ISSUE TITLE
Many (100-500) Gen 2 Cycles During a Short Time Frame

### ISSUE THREAD

**Issue by liorss18** [dotnet/runtime#32487]
We have a service application running in IIS on Windows Server 2012, .NET 4.6.1, x64, 8 logical processors, 70GB RAM.
The process consumes ~60GB of RAM. Pagefile disabled.
We have a farm of >100 servers running that process.

We monitor the GC Gen2 cycles using ETW so we know exactly how long the pause times, both for foreground and background GCs.

On regular behavior, the process runs about 2 Gen2 GC cycles, where most of the cycles are background.

We observed an odd behavior on some of our servers, very sporadically, in which the process is continuously running GC gen 2, between 100 and 500 GC 2 cycles! Half of which are background.
This behavior can continue for several hours easily.
Inducing GC (forced, Blocking) doesn't help.

We have a memory dump taken while this scenario happened.
Analyzing the memory dump using windbg, I see that Gen2 heap is very fragmented, roughly 50%.
The amount of pinned handles is  118 so I don't think that is the root cause for the fragmentation.

What could cause the process to be doing so many GCs?
Is the fact that the heap is fragmented related to the frequency of the GCs?
How can I debug this further?

The following are some outputs of windbg analysis:
!Dumpgen 2
[SHOWING ONLY THE END]
  12,292,588    295,022,112   System.Char
   5,380,212    301,291,872   System.Collections.Generic.SortedSet`1+Node[[System.Collections.Generic.KeyValuePair`2[[System.String, mscorlib],[System.String, mscorlib]], mscorlib]]
   5,384,127    311,516,672   System.Int64[]
   5,953,068    360,136,472   System.Object[]
  12,306,093    383,227,784   System.String[]
  12,296,094    393,446,944   EeekSoft.Text.StringSearch+TreeNode[]
     291,722    455,813,264   System.Collections.Generic.HashSet`1+Slot[[System.String, mscorlib]][]
   3,529,196    480,075,540   System.Int32[]
  12,297,771    491,910,840   System.Collections.ArrayList
  18,072,666    722,906,640   DoubleVerify.Contracts.DataContracts.PlacementCacheItem
  12,296,095    885,318,840   EeekSoft.Text.StringSearch+TreeNode
  12,298,421    983,873,680   System.Collections.Hashtable
  12,298,422  1,248,775,728   System.Collections.Hashtable+bucket[]
     288,301  1,439,198,592   DoubleVerify.TP.Service.ImpressionRecord
  49,703,435  2,377,180,892   System.String
  10,472,242  9,515,231,972   **** FREE ****

---
!heapstat
Heap             Gen0         Gen1         Gen2          LOH
Heap0        32930032         3408   3853726640   4705433680
Heap1        74720520          160   3722360104   3761027864
Heap2        39349000         2080   3799923712   5013682768
Heap3      1778146464           24   1779635560   4738729936
Heap4       203758824           24   1701538480   4374659408
Heap5        38648160         1672   3717573368   4824707240
Heap6        36766608         1456   3861741896   5167467944
Heap7      2098208384           64   1907060224   3595937208
Total      4302527992         8888  24343559984  36181646048

Free space:                                                 Percentage
Heap0        11554952           72   2101271392    561414176SOH: 54% LOH: 11%
Heap1        48785944           24   1829592928    551596992SOH: 49% LOH: 14%
Heap2        10050400           48   1830229552    641896688SOH: 47% LOH: 12%
Heap3      1747896272            0     28240352    564286528SOH: 49% LOH: 11%
Heap4       170632424            0     29078448    640514032SOH: 10% LOH: 14%
Heap5           31544           48   1784876528    626256944SOH: 47% LOH: 12%
Heap6        26264168           48   1900437664    582754160SOH: 49% LOH: 11%
Heap7      2071542752           24     32449592    597280528SOH: 52% LOH: 16%
Total      4086758456          264   9536176456   4766000048

---
!gchandles
[ONLY THE END PART]
Handles:
    Strong Handles:       453
    Pinned Handles:       118
    Async Pinned Handles: 202
    Ref Count Handles:    2
    Weak Long Handles:    150966
    Weak Short Handles:   12681
    SizedRef Handles:     16
    Dependent Handles:    1

Thanks a lot

**Comment by danmosemsft** [comment]
Hello @liorss18 , this repo is for issues with .NET Core. To get support for .NET Framework, the best way is to either open a support issue if you have a support contract, or open an issue at https://developercommunity.visualstudio.com/spaces/61/index.html

**Comment by liorss18** [comment]
Thanks @danmosemsft  I'll open an issue there.

**Comment by Maoni0** [comment]
@liorss18 - sorry I didn't see this till now. are you running with high memory load? if so you could be hitting something i fixed in 4.7.x where it would continue to do gen2 GCs in high mem because there's a lot of pinning fragmentation in gen2. I dunno if you had any luck opening an issue on the VS website but wanted to check how it went with this. again, sorry I didn't see this.

**Comment by liorss18** [comment]
Hi @Maoni0,
Regarding memory load:
Allocated Bytes/sec is about 1GB.
Gen0 Promoted Bytes/sec is 1-4MB.
Gen1 Promoted Bytes/sec is 10-20MB.

According the numbers I gave in the initial issue show there are only 118 pinned handles and 202 async pinned handles. 
Is it considered as "a lot of pinning fragmentation" as you suggested?
Should upgrading to .Net 4.7.X fix this?

I just want to make sure we are on the same page here, we run on windows servers, .Net framework, and *not* on .Net Core.

As for opening an issue on VS website, I opened an issue but it didn't get any reply: https://developercommunity.visualstudio.com/content/problem/922736/excessive-gen-2-cycles.html
Which communication channel should I use for such issues in the future?
Thanks a lot for your help on this.

**Comment by Maoni0** [comment]
from the data you've shown you do have quite a bit of frag in gen2 but it's hard to tell whether that's a problem because I dunno when this is wrt a gen2 GC, meaning that if the data is from right after a BGC, that seems quite normal; but if it's after a compacting gen2 then certainly you could be hitting the problem I mentioned. 

in order to definitely diagnose this we'd need more data than the point in time you provided. would it be feasible to collect some ETW traces for this? you could collect a GCCollectOnly trace - 

`perfview /GCCollectOnly /AcceptEULA /nogui /MaxCollectSec:1800 collect`

1800 means 1800s; this is very low overhead so you could leave it on all the time.

ETW is described in https://devblogs.microsoft.com/dotnet/gc-etw-events-1/.

**Comment by Maoni0** [comment]
as far as what channel to use to report this kind of issues, it's unclear. the VS channel is clearly not effective. personally I don't mind if you just use the GH issue like this one (I didn't notice this just because I didn't realize at some point I stopped getting notification emails from GH) but I'm not sure what our general policy is. I'll try my best to respond but if there are too many obviously I wouldn't be able to respond to all of them in a timely manner.

**Comment by liorss18** [comment]
We have a service that collects ETW events of the production service that had the issue.
We don't collect all data as perfview, but we do have all Gen2 cycles and an indication of the duration, type and reason.

Since the issue had started we have done some memory optimizations and we haven't been seeing this issue again.
With that said, I'm attaching a file containing the info of Gen2 cycles.
Notice that since 07:00 am the GC cycles become very frequent and since 08:00 the frequency even increases.
There is noticeable pattern: the GC cycles alternate between BGC and BlockingGC.

[GcEventsLog.00000-TPS29-AtTimeOfGcFrequencyIssue.txt](https://github.com/dotnet/runtime/files/4438386/GcEventsLog.00000-TPS29-AtTimeOfGcFrequencyIssue.txt)

**Comment by Maoni0** [comment]
unfortunately just recording that you did such GCs doesn't help much. the reason you recorded is just trigger reason which tells us why the GC was triggered, not why it actually became a BGC or blocking full GC. 

unless we have the events it's difficult to make progress on this.

**Comment by Maoni0** [comment]
I'm closing this as there's not enough data to make progress. feel free to reopen with data that has enough GC events.
