### ISSUE TITLE
git clone; ./build.cmd fails

### ISSUE THREAD

**Issue by guylangston** [dotnet/runtime#32483]
@benaadams suggest that I raise this issue as he had numerous reports from the wild:
- https://twitter.com/ben_a_adams/status/1229750159095009280
- https://twitter.com/ben_a_adams/status/1228334444525891584

Steps to reproduce:
- `git clone https://github.com/dotnet/runtime.git`
- `./build.sh`

Results in error:
```
Build FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB8065: Custom build for item "E:\Projects\runtime\artifacts\obj\native\netcoreapp5.0-Windows_NT-Debug-x64\CMakeFiles\f69e234f9a3a26126514dd267f0ee80f\INSTALL_force.rule" succeeded, but specified output "e:\projects\runtime\artifacts\obj\native\netcoreapp5.0-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [E:\Projects\runtime\artifacts\obj\native\netcoreapp5.0-Windows_NT-Debug-x64\install.vcxproj] [E:\Projects\runtime\src\libraries\Native\build-native.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB8065: Custom build for item "E:\Projects\runtime\artifacts\obj\native\netcoreapp5.0-Windows_NT-Debug-x64\CMakeFiles\f69e234f9a3a26126514dd267f0ee80f\INSTALL_force.rule" succeeded, but specified output "e:\projects\runtime\artifacts\obj\native\netcoreapp5.0-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [E:\Projects\runtime\artifacts\obj\native\netcoreapp5.0-Windows_NT-Debug-x64\install.vcxproj] [E:\Projects\runtime\src\libraries\Native\build-native.proj]
    0 Warning(s)
    2 Error(s)
Time Elapsed 00:21:44.90
(NETCORE_ENGINEERING_TELEMETRY=Category) Build failed.
```

### Environment
- Windows10
- Visual Studio 16.4.5 
(Let me know what addition information you need)
- git source: `e7cd7bc1227a74d8e71226bf60a5969c8d57021f (HEAD -> master, origin/master, origin/HEAD) [master] Update dependencies from mono/linker dotnet/arcade (#32472)`

### Work-Around

```
$ echo "" > "e:\projects\runtime\artifacts\obj\native\netcoreapp5.0-windows_nt-debug-x64\cmakefiles\install_force"
$ ./build.sh

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

**Comment by vcsjones** [comment]
I ran in to this when my installed cmake version was below 3.15.5. Are you using a version of cmake that is older than that?

@jkoritzinsky

**Comment by guylangston** [comment]
> I ran in to this when my installed cmake version was below 3.15.5. Are you using a version of cmake that is older than that?
> 
> @jkoritzinsky

cmake version 3.15.19101501-MSVC_2

**Comment by vcsjones** [comment]
@guylangston 
@jkoritzinsky can probably confirm but the last I understood, the version of cmake that ships with Visual Studio is a little out of date. Can you try downloading the latest version, ensure it is on your PATH (make sure `cmake --version` output is the one you just installed), and seeing if that resolves the issue? 

https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md#cmake

**Comment by guylangston** [comment]
```
$ choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
=> cmake v3.16.2 [Approved]
```

Then:
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cmake --version
cmake version 3.16.2

E:\Projects\runtime>where cmake
C:\Program Files\CMake\bin\cmake.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe

E:\Projects>rmdir /s /q runtime
...

E:\Projects>git clone https://github.com/dotnet/runtime.git
...

E:\Projects> build.cmd
...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:20:24.86
```

@vcsjones Looks like you were correct.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md#cmake specifies 3.15.5 -- one would think that "3.15.19101501-MSVC_2" would meet that criterion but I'm guessing that 19101501 is not actually the 19 millionth revision of 3.15 and is just some unusual versioning scheme.

Closing since this seems resolved.
