### ISSUE TITLE
HttpClient not able to handle UTF8 Headers

### ISSUE THREAD

**Issue by tsproesser** [dotnet/runtime#32482]
I've noticed this issue when I first tried to request a service that just answered me with a cookie containing UTF8 strings (and obvisously got UTF8 encoded by the server; probably IIS). As soon as I send the next request I get the following exception:

> HttpRequestException: Request headers must contain only ASCII characters.

Sure headers need to be ASCII-encoded, but the real world already started to make an exception for cookies (e.g. FF, Chrome, Opera seam to do). As far as I can see I am not able to set a encoding for the headers so I am not able to communicate with this server.

**Comment by tsproesser** [comment]
Just found that in [https://github.com/dotnet/runtime/blob/3701909085632f3ad7b09b756bd32fd1a7f98017/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderDescriptor.cs#L140](url) already the `Location` is read as UTF8 - probably for redirect. Guess the same should be done for `set-cookie`?

**Comment by alnikola** [comment]
Could you please clarify whether you encountered the error on receiving first response or sending the second request?

**Comment by tsproesser** [comment]
The following code can fix the issue:

`Encoding.UTF8.GetString(Encoding.GetEncoding(28591).GetBytes((response as HttpWebResponse).Cookies[1].Value))`

If any request receives a UTF8 encoded Cookie the second will fail (because a non ASCII character is set in die cookies)

**Comment by alnikola** [comment]
Did I get it right that server responded with non-ASCII characters? It's prohibited [by the RFC](https://tools.ietf.org/html/rfc6265#section-6.1).
Additionally, could you please point me to some official documentation for Chrome saying that it can accept UTF-8 encoded cookies and sent them back to the server? I tried searching for something, but with no luck.

**Comment by tsproesser** [comment]
You can check this guy who has done several tests: [https://stackoverflow.com/questions/25665703/encoding-scheme-used-for-cookies](url). All I can tell you is that Chrome works for me with a page sending e.g. a German "Ü" in a cookie's content - the .NetCore WebClient gets an exception. And as I've already mentioned: the same fix was done for the `Location`, too.

**Comment by tsproesser** [comment]
Since the service I'm querying is an ASPX-service I'd guess that ASPX encodes the Cookies UTF8 in general.

**Comment by alnikola** [comment]
I read that post on SO, but it seems the author was talking about cookie storage **on the client inside browser** whereas the transfer encoding is [discussed in this comment](https://stackoverflow.com/a/25795420) where everything is properly encoded.
Anyways, thank you for your suggestion. We will consider it on triage.

**Comment by tsproesser** [comment]
Yes, that's correct ... But somehow the cookies must have come there.

Btw: can you maybe help me to get my current issue fixed? How to replace all the Cookies in a CookieContainer with the re-encoded ones? Right now I'm getting the private field `m_domainTable` and call the `GetCookie`-method but that doesn't seam to give me the correct instances, since changing it's value doesn't change it for the next call.

**Comment by tsproesser** [comment]
If anyone else faces this problem, I've written an extension method that fixes the cookies and Url-encodes them (since you fixed cookie can't be sent containing non-ASCII characters):

```
public static WebResponse FixResponseUTF8Cookies(this WebResponse paramHttpWebResponse)
{
	foreach (var c in (paramHttpWebResponse as HttpWebResponse)?.Cookies.OfType<Cookie>())
	{
		var newValue = Encoding.UTF8.GetString(Encoding.GetEncoding(28591).GetBytes(c.Value));
		Debug.Assert(newValue == c.Value);
		if (newValue != c.Value) { c.Value = HttpUtility.UrlEncode(newValue); }
	}

	return paramHttpWebResponse;
}
```

Sure the server needs to understand this, but guess the most do.

**Comment by tsproesser** [comment]
> I read that post on SO, but it seems the author was talking about cookie storage **on the client inside browser** whereas the transfer encoding is [discussed in this comment](https://stackoverflow.com/a/25795420) where everything is properly encoded.
> Anyways, thank you for your suggestion. We will consider it on triage.

That's the best SO I've found so far: [https://stackoverflow.com/questions/1969232/what-are-allowed-characters-in-cookies](url)

**Comment by davidsh** [comment]
>Did I get it right that server responded with non-ASCII characters? It's prohibited by the RFC.

>Just found that in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderDescriptor.cs#L140 already the Location is read as UTF8 - probably for redirect. Guess the same should be done for set-cookie?

In general, non-ASCII characters are disallowed by the RFC in header values. That doesn't stop browsers, however, from creating 'defacto' standards and accept UTF8 in certain headers.

While we generally try to adhere strictly to RFC standards, we also try to be flexible in accepting/receiving certain non-standard formats that are being used. The recent change to the 'Location' header to allow UTF8 is one such example.

We will have to a closer look at the use of UTF8 in cookie header values before making a decision about any change to .NET Core behavior.

**Comment by tsproesser** [comment]
> > Did I get it right that server responded with non-ASCII characters? It's prohibited by the RFC.
> 
> > Just found that in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderDescriptor.cs#L140 already the Location is read as UTF8 - probably for redirect. Guess the same should be done for set-cookie?
> 
> In general, non-ASCII characters are disallowed by the RFC in header values. That doesn't stop browsers, however, from creating 'defacto' standards and accept UTF8 in certain headers.
> 
> While we generally try to adhere strictly to RFC standards, we also try to be flexible in accepting/receiving certain non-standard formats that are being used. The recent change to the 'Location' header to allow UTF8 is one such example.
> 
> We will have to a closer look at the use of UTF8 in cookie header values before making a decision about any change to .NET Core behavior.

Sure, no problem! And thank you very much for your kind answer! For now I can go with the extension method I've posted - and I'd love to see the feature implemented in future. Since it's exactly the same "wrong or right" like the location is, I guess it should be implemented - or at least be optionally possible. But sure, that's your decision! Anyway, thanks in advance!
