### ISSUE TITLE
MulticastOption Group setter should not allow null

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#32490]
`MulticastOption`'s constructor doesn't allow the `IPAddress group` parameter to be `null`.

https://github.com/dotnet/runtime/blob/5ee7f889f722c0086c5bebdab5d854e0efbf0c79/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MulticastOption.cs#L14-L59

However, the public property for `Group` allows it to be set to `null`:

https://github.com/dotnet/runtime/blob/5ee7f889f722c0086c5bebdab5d854e0efbf0c79/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MulticastOption.cs#L61-L72

This is inconsistent. And when trying to add nullable annotations to this class, this setter forces the getter to allow returning `null`. Which means all consuming code will need to check for `null`, when it really isn't an acceptable state for this class to be in.

The IPv6 version of this class fixes this issue by throwing an `ArgumentNullException` in the setter:

https://github.com/dotnet/runtime/blob/5ee7f889f722c0086c5bebdab5d854e0efbf0c79/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MulticastOption.cs#L144-L160

We should consider a small breaking change here and throw an `ArgumentNullException` from `MulticastOption.Group`'s setter.

/cc @stephentoub @davidsh @dotnet/ncl 

NOTE: If we don't change the setter to reject `null`, we will need to decide what to do when it is `null`. Currently, we NRE:

![image](https://user-images.githubusercontent.com/8291187/74755233-7999f300-5238-11ea-8274-a8b261c57ee4.png)

**Comment by davidsh** [comment]
>We should consider a small breaking change here and throw an ArgumentNullException from MulticastOption.Group's setter.

I would be in a favor of making this breaking change for a major release like .NET 5 and documenting it accordingly.
