### ISSUE TITLE
JIT assertions are attributed to the wrong phase

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#32497]
JIT assertions, such as in https://github.com/dotnet/runtime/issues/32466:

`Assertion failed: '!emitComp->opts.compReloc || memBase->IsIconHandle() || memBase->IsIntegralConst(0)' in 'nullsdarr:f()' during 'Linear scan register alloc'`

are attributed to the last phase where `BeginPhase` or `EndPhase` was called. Unless using the `Phase` object, we don't use `BeginPhase` calls, so assertions are attributed to the previous phase, which is confusing. The above assertion is presumably during codegen, not LSRA.

@AndyAyersMS @dotnet/jit-contrib 

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

**Comment by AndyAyersMS** [comment]
Should be fixed by ongoing phasification...

**Comment by jaredpar** [comment]
These assertions are causing the coreclr outerloop builds to fail at the moment. Looks to be 100% failure rate. 

Failing tests are 

- `JIT\\Directed\\coverage\\importer\\Desktop\\nullsdarr_il_d\\nullsdarr_il_d.cmd`
- `JIT\\Directed\\coverage\\importer\\nullsdarr\\nullsdarr.cmd`

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#533208](https://dev.azure.com/dnceng/public/_build/results?buildId=533208)|Rolling|2|
|[#533291](https://dev.azure.com/dnceng/public/_build/results?buildId=533291)|Rolling|2|
|[#533388](https://dev.azure.com/dnceng/public/_build/results?buildId=533388)|Rolling|2|
|[#533425](https://dev.azure.com/dnceng/public/_build/results?buildId=533425)|Rolling|2|
|[#533595](https://dev.azure.com/dnceng/public/_build/results?buildId=533595)|Rolling|2|
|[#533653](https://dev.azure.com/dnceng/public/_build/results?buildId=533653)|Rolling|2|
|[#533733](https://dev.azure.com/dnceng/public/_build/results?buildId=533733)|Rolling|2|
|[#533816](https://dev.azure.com/dnceng/public/_build/results?buildId=533816)|Rolling|2|
|[#533874](https://dev.azure.com/dnceng/public/_build/results?buildId=533874)|Rolling|2|
|[#533988](https://dev.azure.com/dnceng/public/_build/results?buildId=533988)|Rolling|2|
### Configurations
- R2R Windows_NT x86 Checked @ Windows.10.Amd64.Open
- R2R Windows_NT x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|
| --- | --- | --- | --- | --- |
|[#533208](https://dev.azure.com/dnceng/public/_build/results?buildId=533208)|Rolling|[console.631fcabd.log](https://helix.dot.net/api/2019-06-17/jobs/0d38afa4-bbc9-453e-9ab5-cf6726db0c9b/workitems/JIT.Directed/files/console.631fcabd.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/0d38afa4-bbc9-453e-9ab5-cf6726db0c9b/workitems/JIT.Directed/files/testResults.xml)|
|[#533208](https://dev.azure.com/dnceng/public/_build/results?buildId=533208)|Rolling|[console.ec2ae37f.log](https://helix.dot.net/api/2019-06-17/jobs/66b18c18-e0c8-4581-90c6-2e18902dab36/workitems/JIT.Directed/files/console.ec2ae37f.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/66b18c18-e0c8-4581-90c6-2e18902dab36/workitems/JIT.Directed/files/testResults.xml)|
|[#533291](https://dev.azure.com/dnceng/public/_build/results?buildId=533291)|Rolling|[console.d78744e6.log](https://helix.dot.net/api/2019-06-17/jobs/b41f2ee4-393a-435c-a33b-3791bcbcdac8/workitems/JIT.Directed/files/console.d78744e6.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/b41f2ee4-393a-435c-a33b-3791bcbcdac8/workitems/JIT.Directed/files/testResults.xml)|
|[#533291](https://dev.azure.com/dnceng/public/_build/results?buildId=533291)|Rolling|[console.9e7bcd5e.log](https://helix.dot.net/api/2019-06-17/jobs/df99408a-0848-4bc5-8ed4-2edbd1915036/workitems/JIT.Directed/files/console.9e7bcd5e.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/df99408a-0848-4bc5-8ed4-2edbd1915036/workitems/JIT.Directed/files/testResults.xml)|
|[#533388](https://dev.azure.com/dnceng/public/_build/results?buildId=533388)|Rolling|[console.d63a346b.log](https://helix.dot.net/api/2019-06-17/jobs/a4ecdac9-3922-46b8-a28a-ce1c39b3872d/workitems/JIT.Directed/files/console.d63a346b.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/a4ecdac9-3922-46b8-a28a-ce1c39b3872d/workitems/JIT.Directed/files/testResults.xml)|
|[#533388](https://dev.azure.com/dnceng/public/_build/results?buildId=533388)|Rolling|[console.f5eced47.log](https://helix.dot.net/api/2019-06-17/jobs/4bbe85d9-5c4b-4a5f-bbb7-6ab9d80f2b44/workitems/JIT.Directed/files/console.f5eced47.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/4bbe85d9-5c4b-4a5f-bbb7-6ab9d80f2b44/workitems/JIT.Directed/files/testResults.xml)|
|[#533425](https://dev.azure.com/dnceng/public/_build/results?buildId=533425)|Rolling|[console.d7e2b330.log](https://helix.dot.net/api/2019-06-17/jobs/a84310cd-5859-425e-b67a-d6eedc99296f/workitems/JIT.Directed/files/console.d7e2b330.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/a84310cd-5859-425e-b67a-d6eedc99296f/workitems/JIT.Directed/files/testResults.xml)|
|[#533425](https://dev.azure.com/dnceng/public/_build/results?buildId=533425)|Rolling|[console.25399d3a.log](https://helix.dot.net/api/2019-06-17/jobs/fa66f3ce-78fd-4bc0-a529-8020c6addd7d/workitems/JIT.Directed/files/console.25399d3a.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/fa66f3ce-78fd-4bc0-a529-8020c6addd7d/workitems/JIT.Directed/files/testResults.xml)|
|[#533595](https://dev.azure.com/dnceng/public/_build/results?buildId=533595)|Rolling|[console.4784fa7d.log](https://helix.dot.net/api/2019-06-17/jobs/3cd3149f-ba4b-47d1-8d53-296ae636d0fd/workitems/JIT.Directed/files/console.4784fa7d.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/3cd3149f-ba4b-47d1-8d53-296ae636d0fd/workitems/JIT.Directed/files/testResults.xml)|
|[#533595](https://dev.azure.com/dnceng/public/_build/results?buildId=533595)|Rolling|[console.5ee21537.log](https://helix.dot.net/api/2019-06-17/jobs/6c66101a-5ed0-4178-8eef-dc4409f5fc52/workitems/JIT.Directed/files/console.5ee21537.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/6c66101a-5ed0-4178-8eef-dc4409f5fc52/workitems/JIT.Directed/files/testResults.xml)|
|[#533653](https://dev.azure.com/dnceng/public/_build/results?buildId=533653)|Rolling|[console.9fd14001.log](https://helix.dot.net/api/2019-06-17/jobs/b637a156-dd29-4dc6-8c55-a5894fa93afa/workitems/JIT.Directed/files/console.9fd14001.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/b637a156-dd29-4dc6-8c55-a5894fa93afa/workitems/JIT.Directed/files/testResults.xml)|
|[#533653](https://dev.azure.com/dnceng/public/_build/results?buildId=533653)|Rolling|[console.06e72e7f.log](https://helix.dot.net/api/2019-06-17/jobs/5f8c3965-f450-44de-96b7-8bd232da44ce/workitems/JIT.Directed/files/console.06e72e7f.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/5f8c3965-f450-44de-96b7-8bd232da44ce/workitems/JIT.Directed/files/testResults.xml)|
|[#533733](https://dev.azure.com/dnceng/public/_build/results?buildId=533733)|Rolling|[console.c01c7f97.log](https://helix.dot.net/api/2019-06-17/jobs/105e8f83-934d-45a9-ae72-c08878982fa1/workitems/JIT.Directed/files/console.c01c7f97.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/105e8f83-934d-45a9-ae72-c08878982fa1/workitems/JIT.Directed/files/testResults.xml)|
|[#533733](https://dev.azure.com/dnceng/public/_build/results?buildId=533733)|Rolling|[console.5418f9d6.log](https://helix.dot.net/api/2019-06-17/jobs/a51252d5-38b0-42a3-a228-23e2c1a6cc03/workitems/JIT.Directed/files/console.5418f9d6.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/a51252d5-38b0-42a3-a228-23e2c1a6cc03/workitems/JIT.Directed/files/testResults.xml)|
|[#533816](https://dev.azure.com/dnceng/public/_build/results?buildId=533816)|Rolling|[console.ed8549db.log](https://helix.dot.net/api/2019-06-17/jobs/e54d393e-5957-4864-a7c5-62f8742da02e/workitems/JIT.Directed/files/console.ed8549db.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/e54d393e-5957-4864-a7c5-62f8742da02e/workitems/JIT.Directed/files/testResults.xml)|
|[#533816](https://dev.azure.com/dnceng/public/_build/results?buildId=533816)|Rolling|[console.54eff531.log](https://helix.dot.net/api/2019-06-17/jobs/d6dc9cd6-8adf-49f4-8715-654afc4f9156/workitems/JIT.Directed/files/console.54eff531.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/d6dc9cd6-8adf-49f4-8715-654afc4f9156/workitems/JIT.Directed/files/testResults.xml)|
|[#533874](https://dev.azure.com/dnceng/public/_build/results?buildId=533874)|Rolling|[console.b1584d07.log](https://helix.dot.net/api/2019-06-17/jobs/902248e7-c68a-4099-8db8-a94473987bae/workitems/JIT.Directed/files/console.b1584d07.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/902248e7-c68a-4099-8db8-a94473987bae/workitems/JIT.Directed/files/testResults.xml)|
|[#533874](https://dev.azure.com/dnceng/public/_build/results?buildId=533874)|Rolling|[console.8e360259.log](https://helix.dot.net/api/2019-06-17/jobs/bb89de7a-eefb-4702-9ea4-7c1faa720f91/workitems/JIT.Directed/files/console.8e360259.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/bb89de7a-eefb-4702-9ea4-7c1faa720f91/workitems/JIT.Directed/files/testResults.xml)|
|[#533988](https://dev.azure.com/dnceng/public/_build/results?buildId=533988)|Rolling|[console.55f6f535.log](https://helix.dot.net/api/2019-06-17/jobs/72f74c4f-499b-4868-8466-eafab50037b6/workitems/JIT.Directed/files/console.55f6f535.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/72f74c4f-499b-4868-8466-eafab50037b6/workitems/JIT.Directed/files/testResults.xml)|
|[#533988](https://dev.azure.com/dnceng/public/_build/results?buildId=533988)|Rolling|[console.c27d3af3.log](https://helix.dot.net/api/2019-06-17/jobs/d06a8461-db7c-4d92-a360-48608d05b8c9/workitems/JIT.Directed/files/console.c27d3af3.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/d06a8461-db7c-4d92-a360-48608d05b8c9/workitems/JIT.Directed/files/testResults.xml)|

**Comment by jaredpar** [comment]
@BruceForstall FYI

**Comment by BruceForstall** [comment]
@jaredpar Your comment belongs in #32466 -- I copied it there.
