### ISSUE TITLE
 "true to continue on the capture context; otherwise, true."

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/runtime#325]
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs#L70

says "**true** to continue on the capture context; otherwise, **true**."
One of them should be **false**, right?

**Comment by stephentoub** [comment]
Fixed.
