### ISSUE TITLE
Comments in Microsoft.Extensions.DependencyModel

### ISSUE THREAD

**Issue by nguerrera** [dotnet/runtime#3250]
_From @psibernetic on July 16, 2018 1:37_

I, along with many others, have been diving into runtime assembly loading in .NET Core for various reasons. I absolutely love that the library was published on NuGet, so thanks for that, but no XML comments makes it hard to navigate the library.

_Copied from original issue: dotnet/cli#9668_

**Comment by eerhardt** [comment]
We should do this in `5.0` as we move DependencyModel to be more inline with the other libraries we own.

**Comment by carlossanlop** [comment]
Closing this issue in favor of https://github.com/dotnet/runtime/issues/43872, where all the undoc APIs are listed.
