### ISSUE TITLE
Migrate the x86 specific structures to AnyCPU for System.Data.OleDb

### ISSUE THREAD

**Issue by saurabh500** [dotnet/runtime#32509]
There are a few structs in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Data.OleDb/src/OleDbStruct.cs which were built with a Pack attribute value of 2 for x86 architecture. 

Problems with `tagDBPARAMBINDINFO` was fixed with https://github.com/dotnet/runtime/pull/32207 
However the usage of the other structs need to be fixed as well. 

Some user reported problems on x86 as copied from https://github.com/dotnet/runtime/issues/981

> In initial tests the reported problem was resolved.
> I noticed other problems in running x86 vs x64, the following commands do not work or return empty strings in x86 but work perfectly in x64:
> 
> * command.Connection.ChangeDatabase (dbName);
> * connection.Database
> * connection.ServerVersion

**Comment by FreddyD-GH** [comment]
OleDbConnectionStringBuilder exhibits the same behavior we saw in #981 (works on Framework x86/x64, works on Core x64, fails on Core x86).

I'm seeing it's throwing an exception at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)

So, I'm guessing this is likely the same issue.

**Comment by saurabh500** [comment]
@FreddyD-GH Can you provide a snippet that can be tested ? What API is failing exactly? i will add them to our tests as well.

**Comment by FreddyD-GH** [comment]
```csharp
        [TestMethod]
        public void ConnectionStringTest()
        {
            OleDbConnectionStringBuilder builder = new OleDbConnectionStringBuilder();
            builder.Provider = "Microsoft.ACE.OLEDB.12.0";
            builder.DataSource = "myDB.accdb";
            string connStr = builder.ConnectionString;

            Assert.AreEqual("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=myDB.accdb", connStr);
        }
```

**Comment by saurabh500** [comment]
@FreddyD-GH I cannot get the above test to fail on x86 with any of the builds 
Are you sure this test is correct, for spotting the issue? 

```C#
[TestMethod]
        public void ConnectionStringTest()
        {
            OleDbConnectionStringBuilder builder = new OleDbConnectionStringBuilder();
            builder.Provider = "Microsoft.Jet.OLEDB.4.0";
            builder.DataSource = "myDB.accdb";
            string connStr = builder.ConnectionString;

            Assert.AreEqual("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=myDB.accdb", connStr);
        }
```

If I change the test to use the provider "Microsoft.Jet.OLEDB.4.0" then I see exception 

```
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   at System.Data.OleDb.PropertyInfoSet.GetValues()
   at System.Data.OleDb.OleDbConnectionInternal.GetPropertyInfo(System.Guid[])
   at System.Data.OleDb.OleDbConnectionStringBuilder.GetProviderInfo(System.String)
   at System.Data.OleDb.OleDbConnectionStringBuilder.get_Keys()
   at System.Data.Common.DbConnectionStringBuilder.get_ConnectionString()
```


Can you confirm this so that I know I am trying to fix the correct issue?

**Comment by FreddyD-GH** [comment]
@saurabh500 Yes, the test with "Microsoft.ACE.OLEDB.12.0" does fail for me.  I have tested some more and the test will succeed if the provider is not installed.  I am guessing that if you give the OleDbConnectionStringBuilder a valid provider, it will try to communicate with it somehow, but if you give an invalid name, it just skips that communication code.

So, if you want to see the code fail, your test environment would have to install the Access Database Engine (x86 version): https://www.microsoft.com/en-us/download/details.aspx?id=54920

However, I feel that the test case that you provide should be sufficient, unless you want to add test cases that are specific for the MS Access OleDb driver.  I believe "Microsoft.Jet.OLEDB.4.0" is included with Windows itself, which probably makes it easier for you.

**Comment by saurabh500** [comment]
OK makes sense. I had uninstalled the Microsoft.ACE.OLEDB.12.0 provider and had been working with the Jet provider (x86). Thanks for digging.

**Comment by FreddyD-GH** [comment]
As a note, OleDbDataReader.cs has several `#if WIN32` preprocessor directives as well.  I'm assuming it would make sense to take a look at those as part of this issue.

**Comment by FreddyD-GH** [comment]
I took a look at this issue today and I came up with some code to fix the issues.  I certainly won't guarantee that my code is the simplest way to fix the issue, but it appears to get the job done in my test environment.  See https://github.com/dotnet/runtime/compare/master...FreddyD-GH:oledbx86

The only structs that I found to actually differ between the Pack of 2 and Pack of 8 (on x86) are the following:
tagDBPARAMBINDINFO (already fixed)
tagDBPROP
tagDBPROPINFO

@saurabh500 Would you be able to review/test my proposed changes to keep this issue moving?

**Comment by saurabh500** [comment]
Yes. Please start a PR.
