### ISSUE TITLE
Use deterministic ID provider to generate PE timestamps for composite R2R images

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#32507]
Initial implementation of composite R2R build mode in Crossgen2 doesn't include logic to calculate the PE header timestamp for output images (in contrast to single-assembly build mode where the timestamp is copied over from the input MSIL file). The purpose of this work item is to fix this deficiency - according to David Wrighton, 

*We should never force the PE timestamp to zero. That will cause problems with getting a pdb to work. Instead, we should either copy a timestamp, as we do already for the non-composite scenario, or use a deterministic id provider. (Basically, I'm arguing that this timestamp parameter should be passed as a nullable int, and this case should be null.*

*And not write a new timestamp.*

*Or, we should implement a deterministic id provider, and capture the timestamp out of that.*

*The general path for that is:*

<code>
Func<IEnumerable, BlobContentId> deterministicProvider = new new Func<IEnumerable, BlobContentId>(content => BlobContentId.FromHash(CryptographicHashProvider.ComputeHash(HashAlgorithmName.SHA1, content));
</code>

*then pass that provider to the PEBuilder constructor. See PeWriter.cs in the Roslyn codebase for details, or ask the Roslyn folks for advise on how to do that.*

**Comment by mangod9** [comment]
can this be closed @trylek ?

**Comment by trylek** [comment]
I filed this issue as @davidwrighton specifically pointed that out as a gap when reviewing my composite changes, my understanding is that this is something we should fix before shipping.

**Comment by davidwrighton** [comment]
We need to implement this, or ngen pdb's won't have correct semantics.
