### ISSUE TITLE
HttpClient now leaks NetworkChange.NetworkAddressChanged handlers

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#32526]
PR https://github.com/dotnet/runtime/pull/1294 modified HttpConnectionPoolManager with code that registers an event handler with NetworkChange.NetworkAddressChanged each time an HttpClient (SocketsHttpHandler) instance is used for the first time.  However, this event handler is only unregistered if the HttpClient is disposed... if the HttpClient instance is instead just dropped, the event handler gets leaked forever.  This results in a 120 byte leak of two objects (the event handler, and a WeakReference) for every HttpClient instance that's created and not explicitly Dispose'd.

Repro:
```C#
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        using var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
        listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
        listener.Listen(1);
        string uri = $"http://{((IPEndPoint)listener.LocalEndPoint).Address}:{((IPEndPoint)listener.LocalEndPoint).Port}";

        _ = Task.Run(delegate
        {
            while (true)
            {
                using Socket server = listener.Accept();
                using var reader = new StreamReader(new NetworkStream(server));
                while (!string.IsNullOrEmpty(reader.ReadLine())) ;
                server.Send(Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Length: 5\r\n\r\nhello"));
            }
        });

        for (int i = 0; i < 20_000; i++)
        {
            var c = new HttpClient();
            await c.GetStringAsync(uri);
        }

        for (int i = 0; i < 5; i++)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Thread.Sleep(1000);
        }

        Console.WriteLine("Waiting");
        Console.ReadLine();
    }
}
```

![image](https://user-images.githubusercontent.com/2642209/74798429-bb0fba00-529b-11ea-9dc7-37572ed32a76.png)

cc: @scalablecory

**Comment by scalablecory** [comment]
Hrm that is interesting; I remember looking at exactly this and thought I resolved it. Good catch.

**Comment by stephentoub** [comment]
I hadn't noticed this code was added in to SocketsHttpHandler. I think we need to revisit it more generally. In addition to this leak, it's going to cause every app that uses HttpClient to also pull in the NetworkInformation library (which I previously explicitly cut the dependcy on) and these types, increasing linked app size, plus the overhead this functionality incurs, e.g. a dedicated thread loop right now on Linux. That's all just in case the experimental HTTP/3 support is used.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/32524 is another regression related to this change.
