### ISSUE TITLE
TextInfo.ToTitleCase in System.Globalization does not work when target string is all Uppercase without space

### ISSUE THREAD

**Issue by bseng** [dotnet/runtime#32525]
When target string is all uppercase, toTitleCase does nothing.

toTitleCase should work even when target string is all uppercase.

Tried on .net 4.7.2 and .net core 3.1

I've a look at the test cases it seems like a word with all uppercase is ignored. I'm just wondering will it be better to treat a sentence without space and all uppercase to be excluded from this rule?

So ToTitleCase("AUSTRALIA") will become "Australia"

**Comment by GrabYourPitchforks** [comment]
This behavior is by design. From [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.textinfo.totitlecase):

> Converts the specified string to title case (except for words that are entirely in uppercase, which are considered to be acronyms).

**Comment by bseng** [comment]
Okay then.
