### ISSUE TITLE
[System.Text.Json] Utf8JsonReader/Writer should support Char

### ISSUE THREAD

**Issue by blankensteiner** [dotnet/runtime#32536]
As explained in the related issue #32429, I'm currently writing my own (de)serializer because I need to support creating the object without calling a constructor (using System.Runtime.Serialization.FormatterServices.GetUninitializedObject) and getting/setting private and read-only fields (using System.Reflection.FieldInfo.SetValue).

Just like [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=netcore-3.1) and [JsonDocument](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument?view=netcore-3.1), I am building on top of [Utf8JsonReader](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader?view=netcore-3.1) and [Utf8JsonWriter](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter?view=netcore-3.1).  
That decision was made because it's encouraged:

> [The Utf8JsonReader is a low-level type that can be used to build custom parsers and deserializers](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#utf8jsonreader-utf8jsonwriter-and-jsondocument)

and because I want to generate the exact same JSON and if possible also respect all options (JsonWriterOptions, JsonReaderOptions, JsonSerializerOptions).

However, I find that I'm not able to just focus on mapping from C# fields to JSON properties (and vise versa), because I have to duplicate functionality/behavior. I think these methods are missing from the current API:

```csharp
public ref partial struct Utf8JsonReader
{
    public char GetChar();
    public bool TryGetChar(out char value);
}
```

```csharp
public sealed partial class Utf8JsonWriter : System.IAsyncDisposable, System.IDisposable
{
    public void WriteString(string propertyName, char value);
}
```

```csharp
public readonly partial struct JsonElement
{
    public char GetChar();
    public bool TryGetChar(out char value);
}
```

In my opinion, it's the domain of Utf8JsonReader and Utf8JsonWriter to know how to (de)serialize the primitive types to whatever data types JSON happens to support. They already know how to do this for most types, but inconsistently Char is left out. By that logic (the arguments for not adding them), I don't see why DateTime and DateTimeOffset are handled in the reader and writer, but not Char? The challenge is the same: We have a C#-type and a JSON string, do some magic.

In .NET Core 3.1 you can deserialize a string to a char. The char will be the first character of the string. That is an implementation I have to duplicate in my serializer. When .NET 5 comes, this logic changes to throwing an exception and then I have to duplicate that behavior.
If that logic was instead pushed down into Utf8JsonReader, Utf8JsonWriter and JsonElement, all users (and people like me creating serializers) could be free'ed from dealing with that lower-level logic.
We should just pass through the wish to get a Char and not care what JSON data types the authors of Utf8JsonReader/Writer chose for it and what mapping logic there currently is.

**Comment by layomia** [comment]
I've split the request for `TimeSpan` into a new issue (https://github.com/dotnet/runtime/issues/32965), as `Char` and `TimeSpan` are separate work items for support.

@blankensteiner can you please update the description to reflect this and include the new API proposals in a format ready for [review](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md)? See https://github.com/dotnet/runtime/issues/29936 for an example specific to `Utf8JsonReader/Writer`.

**Comment by blankensteiner** [comment]
Hi @layomia 
Sure, will the above suffice?
