### ISSUE TITLE
Building -os Unix not work

### ISSUE THREAD

**Issue by MBurtsev** [dotnet/runtime#32546]
Hello, 
this command:
`build.cmd -subsetCategory coreclr -os Unix -c Release -arch x64`
Make Windows_NT.x64.Release  

```
    Microsoft.NETCore.TestHost -> E:\GitHub\dotnet-runtime\artifacts\packages\Debug\specs\runtime.win-x64.Microsoft.NETCore.TestHost.nuspec
    Microsoft.NETCore.ILAsm -> E:\GitHub\dotnet-runtime\artifacts\packages\Debug\specs\runtime.win-x64.Microsoft.NETCore.ILAsm.nuspec
    Microsoft.NETCore.ILDAsm -> E:\GitHub\dotnet-runtime\artifacts\packages\Debug\specs\runtime.win-x64.Microsoft.NETCore.ILDAsm.nuspec
    Microsoft.NETCore.ILDAsm -> E:\GitHub\dotnet-runtime\artifacts\packages\Debug\specs\Microsoft.NETCore.ILDAsm.nuspec
    Microsoft.NETCore.ILAsm -> E:\GitHub\dotnet-runtime\artifacts\packages\Debug\specs\Microsoft.NETCore.ILAsm.nuspec
    Microsoft.NETCore.TestHost -> E:\GitHub\dotnet-runtime\artifacts\packages\Debug\specs\Microsoft.NETCore.TestHost.nuspec
  BUILD: Build succeeded.  Finished at 20:44:40.05
  BUILD: Product binaries are available at E:\GitHub\dotnet-runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

What am I doing wrong?

OS: Windows 10

**Comment by vcsjones** [comment]
It's not clear to me what didn't work. The text output your included indicates the build succeeded.

**Comment by MBurtsev** [comment]
@vcsjones I Want build for Unix not for Windows

**Comment by Gnbrkm41** [comment]
Can you actually build Linux binaries on Windows? None of the documents mention it being possible, and the only case I know of building for a different OS/arch is building for Windows on ARM from Windows x86/64. (https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/cross-building.md).

**Comment by MBurtsev** [comment]
In [docs](https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries)
`-os identifies the OS for the build. It defaults to the OS you are running on but possible values include Windows_NT, Unix, Linux, or OSX. (msbuild property OSGroup)` 
default and not default )

**Comment by Gnbrkm41** [comment]
I agree with that. Either the docs / behaviour should be updated to do the right thing.

**Comment by jashook** [comment]
Related to https://github.com/dotnet/runtime/pull/35642

**Comment by jashook** [comment]
Addressed
