### ISSUE TITLE
ThreadPool and Xamarin platform integration

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#32543]
In Mono the `ThreadPool` code allowed [injecting custom code around user callbacks executed](https://github.com/mono/mono/blob/b4337dd4e83a8e89c278e5eaa3e3135a1dd672c9/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs#L1238-L1263) in the thread pool. This feature is notably used by Xamarin.iOS/Mac to implement code that [injects `NSAutoreleasePool`](https://github.com/xamarin/xamarin-macios/blob/35c04caa1b07881b26cf44d7a809465bada96a0c/src/ObjCRuntime/Runtime.cs#L273-L290) into the thread pool threads. This is vital part of the platform integration to ensure that Cocoa code executed on the thread pool threads releases all resources properly.

With the MonoVM [migrating to the managed thread pool](https://github.com/mono/mono/pull/17387) this feature was lost in the process. We should figure out how to proceed further on this, with either reintroducing the same private API, different private API, or public API to accomplish the same goal.

Related to https://github.com/xamarin/xamarin-macios/issues/7924.

**Comment by marek-safar** [comment]
@kouvel could you help us to design the right API?

/cc @jkotas

**Comment by lambdageek** [comment]
I wrote an API proposal in https://github.com/dotnet/runtime/issues/44213

**Comment by jkotas** [comment]
Closed in favor of  #44213
