### ISSUE TITLE
Unsound #endif - #if(n)def pairs in coreclr

### ISSUE THREAD

**Issue by speshuric** [dotnet/runtime#32559]
Recently while reading `gc.cpp` I've found some preprocessor directives, that I can't explain and they make harder to read code.
Example (gc.cpp lines 26462-26472): 
```c++
#ifdef MULTIPLE_HEAPS
    //restart
    if (gc_t_join.joined())
    {
#endif //MULTIPLE_HEAPS

#ifdef MULTIPLE_HEAPS
        dprintf(3, ("Restarting for compaction"));
        gc_t_join.restart();
    }
#endif //MULTIPLE_HEAPS
```
*Inline code snippets on github do not work for large files like gc.cpp, so all the code relates to current e4d7893a73 commit*

This code looks trashy and force me to recheck the `ifdef` logic in upper block (`#endif` can end `#else` branch or opposite condition branch). Sometimes `#endif` - `#if(n)def` are reasonable: 
- it could be logical blocks like gc.cpp lines 2098-2104:
```
#ifdef FEATURE_STRUCTALIGN
#define MAX_STRUCTALIGN OS_PAGE_SIZE
#else // FEATURE_STRUCTALIGN
#define MAX_STRUCTALIGN 0
#endif // FEATURE_STRUCTALIGN

#ifdef FEATURE_STRUCTALIGN
...
```
- it could be separated copy-pasted or autegenerated blocks (look at `CodeGen::genArm64EmitterUnitTests()` in `codegenarm64.cpp`) https://github.com/dotnet/runtime/blob/e4d7893a73dbdb6ffda263e04cef76448156065c/src/coreclr/src/jit/codegenarm64.cpp#L5122
- it could be `#else` or opposite condition branches

So I don't think they can be removed automatically without review.

BTW, striking that a lot of unsound `#endif` - `#if(n)def` pairs in `gc.cpp` that check `MULTIPLE_HEAPS` macro

I tried to find all code blocks of form
```
#endif // {token}
#ifdef {token}
```
I've found 9 occurencies in `gc.cpp`, but only 2 of them are quite reasonable. In all coreclr files there are more than 100 such blocks.

If one think that it's not a problem, try to check block at lines 11120-11122 in [gc.cpp](https://github.com/dotnet/runtime/blob/e4d7893a73dbdb6ffda263e04cef76448156065c/src/coreclr/src/gc/gc.cpp#L11120-L11122). Сorresponding `#ifdef` block is in more than 70 lines upper (in line 11045)

**Is it intentional usage of `#endif` - `#if(n)def` pairs or it just happened accidentally?**

Can it be fixed to make coreclr code cleaner?

**Comment by Maoni0** [comment]
this is perfectly intentional. I don't understand what the difficulty is to explain this. the code under MULTIPLE_HEAPS needs the join; otherwise it doesn't need to join. if you could help me understand what's confusing, perhaps I can suggest something.

**Comment by Maoni0** [comment]
and you should be able to just goto the matching brace to see where the upper block is. hopefully your editor can do that.

**Comment by speshuric** [comment]
> if you could help me understand what's confusing, perhaps I can suggest something

Why this code written as 
```cpp
#ifdef MULTIPLE_HEAPS
    //restart
    if (gc_t_join.joined())
    {
#endif //MULTIPLE_HEAPS

#ifdef MULTIPLE_HEAPS
        dprintf(3, ("Restarting for compaction"));
        gc_t_join.restart();
    }
#endif //MULTIPLE_HEAPS
```
instead of 
```cpp
#ifdef MULTIPLE_HEAPS
    //restart
    if (gc_t_join.joined())
    {
        dprintf(3, ("Restarting for compaction"));
        gc_t_join.restart();
    }
#endif //MULTIPLE_HEAPS
```

**Comment by Maoni0** [comment]
ahh, that's from people removing code that used to exist in the {} but didn't get rid of the extra #endif/#ifdef when they removed it.

I actually have a cleanup PR that I'm working on right now that includes all the extra #endif/#ifdef for things like this.

**Comment by Maoni0** [comment]
this is cleanup PR that fixes the unnecessary #endif/#ifdef: https://github.com/dotnet/runtime/issues/32559. closing. feel free to reopen if you find more places with these unnecessary #endif/#ifdef's.
