### ISSUE TITLE
IHow to verify that a Type can be passed to a generic method in C# also restore generic parameter types based on passed arguments

### ISSUE THREAD

**Issue by npolyak** [dotnet/runtime#32561]
**Version Used**: 
.net core 3.1

This is more of a question, rather than an issue. 

For example, if I have the following code:

    public static class MyClass
    {
         public static void DoSmthWithCollection<T>(IEnumerable<T> collection)
         {
          ...
         }
    }

Of course, compiler would allow to pass to it an object of List<int> type. Moreover, the compiler will figure out that the type T for the method is resolved to int type.

I need to do the same only dynamically, either by using System.Reflection or Roslyn. Say I get the `MethodInfo` for the method, I get the generic `ParameterInfo`. Is there any easy way to figure out that an object of type `typeof(List<int>)` actually fits to be an argument to the method and that when you pass it, the method resolves `T` to `int` type? And I am talking about some relatively easy solution without examining types and subtypes and the generic type constraints. I think at least Roslyn should have one, since this is what the C# compiler is doing.

Thanks for your help.

**Comment by jaredpar** [comment]
@jinujoseph  yes. At the point we're using reflection it becomes more of a CLR type system question vs. a C# type system one.

**Comment by npolyak** [comment]
I do not mind either solution - one using Reflection or one using Roslyn. I can obtain the Syntax and Semantic trees of the code.

**Comment by jeffschwMSFT** [comment]
@fadimounir

**Comment by fadimounir** [comment]
@npolyak Have you tried something like `Type.IsAssignableFrom(Type)`?

see: https://docs.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom?view=netframework-4.8

One thing to keep in mind when you say get the `MethodInfo`, then the `ParameterInfo` is that if you do that on the generic method, you will get info for the generic definitions, not a specific instantiation.

You could do something like:
``` c#
var instantiatedMethod = methodInfo.MakeGenericMethod(new[] { typeof(int) });
instantiatedMethod.GetParameters()[0].ParameterType.IsAssignableFrom(typeof(List<int>));
```

Hope this helps.

**Comment by janvorli** [comment]
@npolyak has @fadimounir's response answered your question?

**Comment by npolyak** [comment]
Sorry guys, I was not monitoring the replies. Thanks everyone for answering, but IsAssignableFrom is not a correct answer. Here is an (approximate) answer I gave myself on Stackoverflow: https://stackoverflow.com/a/60330159/1672563

**Comment by mangod9** [comment]
@npolyak closing this issue since it appears its been answered?
