### ISSUE TITLE
[QUIC] Improve MSQuic OS Version detection

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#32575]
https://github.com/dotnet/runtime/blob/3be5238a376cd4bca32db1acb732dc7c15091cdf/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicApi.cs#L144-L146

Environment.OSVersion is an unreliable API that reports old versions for compat purposes. It only reports the correct Win10 version if an app manifest is added. VS and the test runner have this manifest but sample apps and customer apps won't.
https://stackoverflow.com/questions/33328739/system-environment-osversion-returns-wrong-version

We're going to need a different way to check for this support. Worst case we look at the registry.

**Comment by am11** [comment]
fwiw, dotnet-cli uses this property for `dotnet --info`, which I think does not rely on the app manifest: https://github.com/dotnet/runtime/blob/cf43585e854f78bdec51323875369778055fc249/src/installer/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L16

**Comment by jkotas** [comment]
Microsoft.DotNet.PlatformAbstractions package is obsolete.

P/Invoking `Ntdll.RtlGetVersionEx` is your best bet.

**Comment by jkotas** [comment]
>  It only reports the correct Win10 version if an app manifest is added. VS and the test runner have this manifest but sample apps and customer apps won't.

This is considered to be a feature. It is not necessary something you want to "fix".

**Comment by am11** [comment]
> Microsoft.DotNet.PlatformAbstractions package is obsolete.

will its sources be removed and dotnet-cli switch to p/invoke?

**Comment by Tratcher** [comment]
> This is considered to be a feature. It is not necessary something you want to "fix".

This version check is to see if the OS has the right TLS 1.3 support. Http3 will have other opt-in guards to maintain compat. Once a developer opts in, false negatives from this version check are are an unnecessary hurdle and support burden.

**Comment by Tratcher** [comment]
#33643 fixed Environment.OSVersion so we can depend on that again.

**Comment by eerhardt** [comment]
@Tratcher - do you want me to update #36302 to add back the Environment.OSVersion check?

**Comment by Tratcher** [comment]
@jkotalik have you confirmed which version we need?

**Comment by jkotalik** [comment]
No, let's just merge what we have in that #36302 for now. I'll need to figure out if the Windows slow preview train has schannel support, which will take a while.

**Comment by scalablecory** [comment]
I'm thinking it's better to implement this in MsQuic -- https://github.com/microsoft/msquic/issues/92

**Comment by ManickaP** [comment]
This can be covered by analyzers with `SupportedOSPlatform`, first crude draft is already in https://github.com/dotnet/runtime/pull/49261, we just need a complete list of supported OS/versions/distros.
cc: @marek-safar
