### ISSUE TITLE
WebUtility.UrlDecode works differently compared to HttpUtility.UrlDecode

### ISSUE THREAD

**Issue by hanastasov** [dotnet/runtime#32594]
I expected [WebUtility.UrlDecode](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urldecode?view=netframework-4.8) and [HttpUtility.UrlDecode](https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility.urldecode?view=netframework-4.8) to work exactly the same, at least this is what the documentation says.

Seems like HttpUtility.UrlDecode will be able to decode both `"%uFF13"` and `"\uFF13"`, while WebUtility.Decode will only cope with  `"\uFF13"`. I am attaching screenshots below:

HttpUtility.UrlDecode("%uFF13")
![http%](https://user-images.githubusercontent.com/14248932/74936759-6b440680-53f3-11ea-981f-0e53abdb8e5e.PNG)

HttpUtility.UrlDecode("\uFF13")
![httpUtility](https://user-images.githubusercontent.com/14248932/74936777-71d27e00-53f3-11ea-82dd-945ae7dbaa4a.PNG)

WebUtility.UrlDecode("%uFF13")
![webutility%](https://user-images.githubusercontent.com/14248932/74936786-75fe9b80-53f3-11ea-92a6-299aeb1f8ebf.PNG)

WebUtility.UrlDecode("\uFF13")
![webutility](https://user-images.githubusercontent.com/14248932/74936798-79922280-53f3-11ea-9804-4ac7f9d6fde5.PNG)

**Comment by davidsh** [comment]
@GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Please don't use %u escaping. I actually tried to remove support for it from .NET 4.5 as a defense-in-depth measure but the change was rejected due to compatibility concerns. It's a legacy format that was never formally approved by any standards body. I don't see us enlightening further components to understand that syntax.

**Comment by davidsh** [comment]
@hanastasov Thanks for raising this issue. As you can, the current behavior is 'by design' and there are no plans to change it.

**Comment by hanastasov** [comment]
> Please don't use %u escaping. I actually tried to remove support for it from .NET 4.5 as a defense-in-depth measure but the change was rejected due to compatibility concerns. It's a legacy format that was never formally approved by any standards body. I don't see us enlightening further components to understand that syntax.

What is recommended when URl encoding actually uses %u ?

**Comment by hanastasov** [comment]
> > Please don't use %u escaping. I actually tried to remove support for it from .NET 4.5 as a defense-in-depth measure but the change was rejected due to compatibility concerns. It's a legacy format that was never formally approved by any standards body. I don't see us enlightening further components to understand that syntax.
> 
> What is recommended when URL encoding actually uses %u ?

URL encoding uses % if you use Javascript native `escpape`. Instead, use `encodeURIComponent`. Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape

**Comment by GrabYourPitchforks** [comment]
> What is recommended when URL encoding actually uses %u ?

If you absolutely must support decoding _%u_-escaped payloads then you should keep using `HttpUtility.UrlDecode`. But try to avoid generating such payloads if you can avoid it. They're non-standard and not well-supported across the broader web ecosystem.

**Comment by hanastasov** [comment]
> > What is recommended when URL encoding actually uses %u ?
> 
> If you absolutely must support decoding _%u_-escaped payloads then you should keep using `HttpUtility.UrlDecode`. But try to avoid generating such payloads if you can avoid it. They're non-standard and not well-supported across the broader web ecosystem.

Thanks ! actually I had trouble importing HttpUtility in .NetCore 3.1 project (not sure why), this is why I used WebUtility. But I will be able to migrate to escaping with \ instead of %.

**Comment by davidsh** [comment]
>Thanks ! actually I had trouble importing HttpUtility in .NetCore 3.1 project (not sure why

The 'HttpUtility' class is in the System.Web namespace. Most of that namespace is not part of .Net Core. That is the original reason why the 'System.Net.WebUtility' class was created. It was meant to replace and be similar to 'HttpUtility'.

**Comment by GrabYourPitchforks** [comment]
We have a _System.Web.HttpUtility_ package that contains a version of `HttpUtility` which works on .NET Core. See https://github.com/dotnet/runtime/tree/master/src/libraries/System.Web.HttpUtility.

For some reason it's not on nuget.org, but it might be available at one of the other package sources at https://github.com/dotnet/runtime/blob/master/NuGet.config.

@ericstj Do you know why this package was never made available on nuget.org?

**Comment by hanastasov** [comment]
> I spoke with @ericstj about this just now. :)
> 
> Turns out because `HttpUtility` is part of netstandard you don't need to add a package for it. You can simply put `using System.Web;` at the top of your source file and start using the type right away.
> 
> ```cs
> using System;
> using System.Web;
> 
> public class Program {
>     public static void Main() {
>         Console.WriteLine(HttpUtility.UrlDecode("%u1234"));
>     }
> }
> ```

Not able to do so in .Net Core 3.1, I guess because of the reason that @GrabYourPitchforks  explained - part of System.Web is not part of .NetCore. Anyway, I resolved my issue earlier in the pipeline and now I don't encode the URL with `%u`.
