### ISSUE TITLE
Dictionary serialization issue ASP.NET Core 3.1

### ISSUE THREAD

**Issue by menua-web** [dotnet/runtime#32590]
Asp.Net Core 3.1  throw  NotSupportedException exception then we call a API which returns Dictionary 
whose key type is enum. For example Dictionary<EntityTypeEnum, object>.

enum EntityTypeEnum {
    Item1 = 1
}
Isn't this feature supported by ASP.NET Core 3.1 or serialization's configuration issue?

**Comment by GrabYourPitchforks** [comment]
Can you provide the stack trace of the exception? That will help us route the issue appropriately.

**Comment by StephenBonikowsky** [comment]
@menua-web Feel free to re-open this issue if you can provide some additional info such as the call stack. FYI if you are using XmlSerializer it does not support Dictionary, in that case we would suggest you use DataContractSerializer instead.

**Comment by menua-web** [comment]
![image](https://user-images.githubusercontent.com/32366296/76387254-f162c580-637f-11ea-895d-3a910bb159f6.png)

**Comment by menua-web** [comment]
![image](https://user-images.githubusercontent.com/32366296/76387335-1b1bec80-6380-11ea-814b-6ec0ffb0dd8b.png)

**Comment by menua-web** [comment]
this is source code web Api Core 3.1 project

**Comment by GrabYourPitchforks** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/30524.
