### ISSUE TITLE
Cannot debug Coreclr on windows 0x00007FFE53E9A839 

### ISSUE THREAD

**Issue by symphony2014** [dotnet/runtime#32596]
When I follow the [debugging doc](https://github.com/dotnet/runtime/blob/master/docs/workflow/debugging/coreclr/debugging.md), and start debug from Visual Studio ,bellow error was threw:
`Unhandled exception at 0x00007FFE53E9A839 (KernelBase.dll) in CoreRun.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131018, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFDD2170000).`
![image](https://user-images.githubusercontent.com/6380601/74937535-394c9780-5427-11ea-881a-c3392ec1cfba.png)
this is stack error:
`Exception thrown at 0x00007FFE53E9A839 in CoreRun.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000004E8277AC38.
Exception thrown at 0x00007FFE53E9A839 in CoreRun.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE53E9A839 in CoreRun.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000004E8277AC38.
Loading D:\projects\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\ to load strings.
Loading D:\projects\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\ to load strings.
Loading D:\projects\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\ to load strings.
Exception thrown at 0x00007FFE53E9A839 (KernelBase.dll) in CoreRun.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131018, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFDD2170000).
Unhandled exception at 0x00007FFE53E9A839 (KernelBase.dll) in CoreRun.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131018, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFDD2170000).`

**Comment by symphony2014** [comment]
I just found this version coreclr.dll  cannot found sourceMap. 
![image](https://user-images.githubusercontent.com/6380601/74938392-e2e05880-5428-11ea-84db-9dc6ff01d207.png)
![image](https://user-images.githubusercontent.com/6380601/74938409-e96ed000-5428-11ea-9a67-3922726a2821.png)

**Comment by EgorBo** [comment]
@symphony2014 can you paste here what you use for `Command Arguments`
the doc says `(e.g. HelloWorld.exe)` but actually it needs `HelloWorld.dll`...

**Comment by symphony2014** [comment]
@EgorBo  This is my **Command Arguments**: **C:\Users\symph\source\repos\ConsoleApp1\bin\Debug\netcoreapp3.1\ConsoleApp1.dll**,
but I am also curosity where is correct path for **coreclr.dll**  to load the coreclr.pdb file.

**Comment by EgorBo** [comment]
@symphony2014 I usually do `dotnet publish -c Release -r win10-x64` for a console app I want to debug.

**Comment by jeffschwMSFT** [comment]
@josalem

**Comment by josalem** [comment]
@symphony2014 , could you post a screenshot of the Properties for the project (right-click on the project and select Properties)?  I want to make sure the working directory is set to the location of the product artifacts.  I'll try top repro this locally.  Also, what version of VS are you using?

For what it's worth, I typically will do what Egor suggested, i.e., `dotnet publish -r win-x64 --self-contained`, and the follow that up by copying the entire product artifact dir into the published directory.  Then I'll run `CoreRun` from there in VS/Windbg without opening the solution in the repo.

CC - @mikem8361 does this look familiar to you?

**Comment by mikem8361** [comment]
It isn't familiar.  Coreclr does throw some exceptions that are handled and can be continued, but this looks like it is unhandled/terminates the process.

**Comment by symphony2014** [comment]
@josalem , @EgorBo ,it was successful when I try with **dotnet publish -c Release -r win10-x64**, other than just use the **Consoleapp.dll** generated from Visual studio 2019 **Debug**.

failed case:
![image](https://user-images.githubusercontent.com/6380601/75123994-27991780-56e7-11ea-8091-73dbcb87a051.png)

success case:
![image](https://user-images.githubusercontent.com/6380601/75123955-d852e700-56e6-11ea-8b2e-602a62147276.png)
visual studio version:
![image](https://user-images.githubusercontent.com/6380601/75124007-3b447e00-56e7-11ea-88ca-8c6d1255ea44.png)

**Comment by sdmaclea** [comment]
Customer reported issue appears resolved.
