### ISSUE TITLE
Add Enumerable.Count(IEnumerable) (None Generic)

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/runtime#32614]
There is no need for [`Enumerable.Count(IEnumerable<T>)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count) to have the generic type. I would like to propose adding a `Enumerable.Count(IEnumerable)` method.

```csharp
namespace System.Linq
{
    public static int Count(this System.Collections.IEnumerable source);
}
```

(I'd even argue that this could replace the existing generic version but that would be a breaking change and not worth it)

**Comment by Tornhoof** [comment]
Many of linq functions special case known collection types to provide e.g. O(1) complexity, Count is one of them.
See https://github.com/dotnet/runtime/blob/a607cffe1243e633f9b5028560adc4e3505f48ac/src/libraries/System.Linq/src/System/Linq/Count.cs#L12-L25

Most of the non-generic collections have been replaced by generic ones for years, so if your code still relies on them you might want to think about replacing them

**Comment by SamuelEnglard** [comment]
True, but there are times where you don't know the type in the collection or are calling an API that only implements the non-generic versions.

**Comment by Suchiman** [comment]
I'd rather see non generic collections die rather than adding more infrastructure to support them.
Is there any benefit of non generic collections over generic collections?

**Comment by SamuelEnglard** [comment]
If you get a collection returned as an `object` and you don't know the type of items in the collection.

**Comment by Clockwork-Muse** [comment]
@SamuelEnglard - Except the type of such a collection can usually be expressed as the generic `IEnumerable<object>`, as opposed to the raw non-generic (assuming it's castable to either one in the first place - why is it coming as `object`?).

**Comment by Suchiman** [comment]
@Clockwork-Muse casting using covariance works only with reference types.

But in general, there are the two bridge methods, `OfType<T>()` and `Cast<T>()`, so you can use `IEnumerable.Cast<object>().Count()` which should work for every possible `IEnumerable`.

**Comment by SamuelEnglard** [comment]
@Clockwork-Muse API doesn't always return a collection. Can return a lot of things so LCD.

Yes @Suchiman I could just `IEnumerable.Cast<object>().Count()` but the cast is not needed so waste the time. Counting doesn't care about what type is there.

**Comment by Clockwork-Muse** [comment]
> API doesn't always return a collection. Can return a lot of things so LCD.

....huh?  `Count` isn't a standard method on "anything".

> I could just `IEnumerable.Cast<object>().Count()` but the cast is not needed so waste the time. Counting doesn't care about what type is there.

You (probably) don't need to cast each object.  [You only have to cast the collection](https://dotnetfiddle.net/9DlR68), which you have to do anyways to be able call `Count` in the first place:
```csharp
// As @Suchiman notes, though, only works with reference types
var count = ((IEnumerable<object>)SomeStrangeApiReturningObject()).Count();
```

.... _why_ does your API only return `object`?  If it's because it's some legacy API, the first thing I'd do is throw a wrapper around it to cast it for me during call.  Which has been doable for like 15 years or something.

**Comment by SamuelEnglard** [comment]
> .... why does your API only return object? If it's because it's some legacy API, the first thing I'd do is throw a wrapper around it to cast it for me during call. Which has been doable for like 15 years or something.

Not my API so I down own it 😄 

I guess I don't want to have to care about reference type or not. Admittedly seems I'm alone on this desire though.
