### ISSUE TITLE
ConditionalFact And ConditionalTheory attributes are not working in the VS

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#32628]
Helpers.NotElevatedAndSupportsEventLogs is false for eventlog tests but still following test is getting run in the vs test explorer

 [ConditionalFact(typeof(Helpers), nameof(Helpers.NotElevatedAndSupportsEventLogs))]
 public void SetProperties_SaveChanges_NotAdmin_Throws()

cc @ViktorHofer @ericstj @safern

**Comment by safern** [comment]
This is a duplicate of: https://github.com/dotnet/runtime/issues/1161
