### ISSUE TITLE
Branchless code generation for ternaries

### ISSUE THREAD

**Issue by lpereira** [dotnet/runtime#32632]
Might be an opportunity to improve codegen for ternaries where both the expr-if-true and expr-if-false are constants.

I played a little bit with Compiler Explorer today to get a feeling of how GCC and Clang generate the code for this.  Here's what I found from looking at the assembly output, with  the accompanying C code for reference.

Method 1: sete/setne
====

```C
int m1(int a) { return a == 5 ? 2 : 3; }
```   
Is generated as, by both Clang and GCC:

```asm
xor eax, eax
cmp edi, 5  
setne al    
add eax, 2
ret
```
   
Playing a bit with Compiler Explorer, it seems that if both expressions in the ternary are apart by 1, then it can reuse the result of "cmp" as part of the expression.  ("sete" is generated if the ternary is inverted, as expected: "a == 5 ? 3 : 2".)

Clang seems to go a bit further with this method before switching to use conditional moves as with "m3" below, by issuing an additional "add" instruction if values are apart by 2, for example.

I suspect a simplified version of this codegen could be used for things like `Convert.ToInt32(bool b)` too.  

Method 2: lea
===

```C
int m2(int a) { return a == 5 ? 10 : 1; }
```

Is generated as, by GCC:
   
```asm
xor eax, eax
cmp edi, 5
sete al
lea eax, [rax+1+rax*8]
ret
```

Clang generates similar code but changes the "+1" inside the LEA to an "add
eax, 1" before the "ret".

This is a more generic extension to the previous method, and seems to be preferred to the next method, when the operands would fit the constraints of the LEA instruction arguments.

Method 3: cmov
====

```C
int m3(int a) { return a == 5 ? 1 : 37; }
```

Is generated as, by both Clang and GCC (order varies a bit):
   
```asm
cmp edi, 5 
mov edx, 37
mov eax, 1
cmovne eax, edx
ret
```

Conditional moves seems to be generated when the above conditions do not hold.

category:cq
theme:optimization
skill-level:expert
cost:medium

**Comment by EgorBo** [comment]
`cmove` was discussed here: https://github.com/dotnet/runtime/issues/6749

Regarding `int m1(int a) { return a == 5 ? 2 : 3; }`
Turns out it depends on profile data (PGO) in clang/LLVM, see https://godbolt.org/z/88UpqV

**Comment by EgorBo** [comment]
But might be quite easy to implement:
IL:
```cil
.method public hidebysig static int32 MM (int32 a) cil managed 
{
    .maxstack 8
    ldarg.0
    ldc.i4.5
    ceq
    ldc.i4.2
    add
    ret
}
```
GenTree:
```
               [000007] ------------              *  ADD       int   
               [000005] ------------              +--*  EQ        int   
               [000000] ------------              |  +--*  LCL_VAR   int    V00 arg0         
               [000004] ------------              |  \--*  CNS_INT   int    5
               [000006] ------------              \--*  CNS_INT   int    2
```
Asm:
```asm
       cmp      ecx, 5
       sete     al
       movzx    rax, al
       add      eax, 2
       ret 
```

**Comment by scalablecory** [comment]
> Same for `condition ? x : x + 1` (for non cns x)

Hopefully this same optimization could be applied if this were written as:

```c#
if(condition) ++x;
```

**Comment by lpereira** [comment]
> > Same for `condition ? x : x + 1` (for non cns x)
> 
> Hopefully this same optimization could be applied if this were written as:
> 
> ```cs
> if(!condition) ++x;
> ```

These are different, right?  The latter statement has an expression with side effects on `x`, whereas the former only evaluates `x`. But if the JIT could match this pattern and generate the code as if it were written as (pseudo-code) `x += !condition`, though.

Do we have anything to query a source tree semantically, like [Coccigrep can do in C](https://home.regit.org/software/coccigrep/)?

**Comment by BruceForstall** [comment]
In the absence of a compelling real-world code example, I'm going to close this.
