### ISSUE TITLE
Socket.EndAccept(out byte[], IAsyncResult) doesn't work on Unix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#32633]
The following is a notebook that works on Windows, but fails on Unix:

```C#
using System.Net;
using System.Net.Sockets;
using System.Threading;

IPEndPoint localEndPoint = new IPEndPoint(IPAddress.Loopback, 11000);

// Create a TCP/IP socket.
Socket listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

// Bind the socket to the local endpoint, and listen for incoming connections.
listener.Bind(localEndPoint);
listener.Listen(100);

var allDone = new ManualResetEvent(false);

// Start an asynchronous socket to listen for connections and receive data from the client.
Console.WriteLine("Waiting for a connection...");

var state = Tuple.Create(listener, allDone);
// Accept the connection and receive the first 10 bytes of data.
int receivedDataSize = 10;
listener.BeginAccept(receivedDataSize, new AsyncCallback(AcceptReceiveCallback), state);

Socket sender = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
sender.Connect(localEndPoint);
byte[] bytes = new byte[3];
bytes[0] = 0x30;
bytes[1] = 0x31;
bytes[2] = 0x32;
sender.Send(bytes);
Console.WriteLine("writing to the socket...");
// Wait until a connection is made and processed before continuing.
allDone.WaitOne();

Console.WriteLine("Done");

public static void AcceptReceiveCallback(IAsyncResult ar) 
{
    // Get the socket that handles the client request.
    Tuple<Socket, ManualResetEvent> state = (Tuple<Socket, ManualResetEvent>) ar.AsyncState;
    Socket listener = state.Item1;
    
    // End the operation and display the received data on the console.
    try
    {
        byte[] buffer;
        Socket handler = listener.EndAccept(out buffer, ar);
        Console.WriteLine($"Got a buffer of length {buffer.Length}");
    }
    catch (Exception e)
    {
        Console.WriteLine(e.ToString());
    }

    state.Item2.Set();
}
```

On Windows, it prints:

```
Waiting for a connection...
writing to the socket...
Got a buffer of length 3
Done
```

On Linux the call to EndAccept fails:

```
Waiting for a connection...
writing to the socket...
System.ArgumentNullException: Value cannot be null. (Parameter 'src')
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, IAsyncResult asyncResult)
   at Submission#4.AcceptReceiveCallback(IAsyncResult ar)
Done
```

The reason it fails is because of the following:

https://github.com/dotnet/runtime/blob/ac941749537fc60c6ceb193462dfe145111a1ef7/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3546-L3548

On Unix, `innerBuffer` that is returned from the `EndAccept(out innerBuffer, ...` call is `null`. The `AcceptOverlappedAsyncResult._buffer` is explicitly set to `null` here:

https://github.com/dotnet/runtime/blob/ac941749537fc60c6ceb193462dfe145111a1ef7/src/libraries/System.Net.Sockets/src/System/Net/Sockets/AcceptOverlappedAsyncResult.Unix.cs#L29-L31

And then when we try to pass `null` into `Buffer.BlockCopy` it throws.

/cc @stephentoub @dotnet/ncl

**Comment by scalablecory** [comment]
Thanks. We should check to see if `SocketAsyncEventArgs` has the same issue.

**Comment by stephentoub** [comment]
IIRC, this method is supposed to not be supported.  It sounds like we end up null ref'ing rather than throwing a PlatformNotSupportedException or returning an empty buffer.

**Comment by scalablecory** [comment]
> IIRC, this method is supposed to not be supported.

We could actually implement it properly with uring, though I don't know if it is used commonly enough to be worth the effort.

**Comment by stephentoub** [comment]
Would we break any expectations if we set it to `Array.Empty<byte>()` instead of null? e.g. would anyone interpret that to mean EOF?

**Comment by eerhardt** [comment]
> We should check to see if SocketAsyncEventArgs has the same issue.

It looks like SocketAsyncEventArgs will throw PNSE:

https://github.com/dotnet/runtime/blob/404598b5e8f54281fc5f906856851e27204e50cf/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs#L69-L74

**Comment by stephentoub** [comment]
Thanks, yeah, so it looks like we just missed doing so in EndAccept.

**Comment by eerhardt** [comment]
We could do it in both `BeginAccept` when `receiveSize` isn't `0`, as well as `EndAccept`. We have a Debug.Assert that `receiveSize == 0` on Unix, but it comes from a public method and no one checks it:

https://github.com/dotnet/runtime/blob/404598b5e8f54281fc5f906856851e27204e50cf/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L1823-L1826

**Comment by eerhardt** [comment]
BTW - I'm trying to figure out if `EndAccept` should be annotated as `EndAccept(out byte[] buffer` or `EndAccept(out byte[]? buffer`. I'm going with the latter for now (since we do return `null` on Unix). But the resolution of this issue could change that annotation. If we decide it should never return `null`, we can change the annotation then.

**Comment by scalablecory** [comment]
> as noted I worry that could be construed to mean EOF

`AcceptEx` does not complete until data is available or EOF is reached, so I think your worry is probably realistic unless we're doing something special in our Windows implementation.

**Comment by antonfirsov** [comment]
I think the most consistent behavior would be to throw PNSE from all unsupported overloads on Unix, since users should not rely on this method in cross-platform code. If we return `null` or `Array.Empty<byte>()` that may lead to unexpected bugs IMO.

I also vote for changing the overloads to non-nullable, since the return buffer will be never null when the method is actually supported on the platform.

@scalablecory @geoffkizer do you agree? I wonder if this is an acceptable breaking change?

```diff
// All methods below should throw PNSE on Unix:

public IAsyncResult BeginAccept(int receiveSize, AsyncCallback? callback, object? state);
public IAsyncResult BeginAccept(Socket? acceptSocket, int receiveSize, AsyncCallback? callback, object? state);

-public Socket EndAccept(out byte[]? buffer, IAsyncResult asyncResult);
-public Socket EndAccept(out byte[]? buffer, out int bytesTransferred, IAsyncResult asyncResult);
+public Socket EndAccept(out byte[] buffer, IAsyncResult asyncResult);
+public Socket EndAccept(out byte[] buffer, out int bytesTransferred, IAsyncResult asyncResult);
```

**Comment by eerhardt** [comment]
>  I wonder if this is an acceptable breaking change?

Note that I added the `out byte[]?` annotation in .NET 5. So changing it to non-nullable in .NET 5 wouldn't be considered a breaking change. If this is the long-term change we want, it is totally acceptable from a "breaking change" aspect - since it isn't a breaking change.

**Comment by antonfirsov** [comment]
In that case, I would push for an API proposal ASAP, maybe it's not too late to get it in.

**Comment by scalablecory** [comment]
> I think the most consistent behavior would be to throw PNSE from all unsupported overloads on Unix, since users should not rely on these methods in cross-platform code. If we return `null` or `Array.Empty<byte>()` that may lead to unexpected bugs IMO that could be prevented by a "fail-fast" approach.

Since `SocketAsyncEventArgs` is throwing PNSE, it's fine to resolve this with the same exception.

However, I don't see any reason we couldn't emulate it on *nix at a later date.
