### ISSUE TITLE
.NET core self contained exe held open

### ISSUE THREAD

**Issue by IIFE** [dotnet/runtime#32634]
# Issue Title
.NET core self contained exe held open

# General

I have a .NET Core self contained application (Foo.exe), where the csproj file is configured in the following way:

```
  <PropertyGroup>
   <TargetFramework>netcoreapp3.0</TargetFramework>
   <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
   <OutputType>Exe</OutputType>
   <PublishTrimmed>true</PublishTrimmed>
   <PublishSingleFile>true</PublishSingleFile>
   <RuntimeIdentifier>win-x86</RuntimeIdentifier>
 </PropertyGroup>
```

I run the following command to publish the exe, which produces `Foo.exe`:
`dotnet publish -c release`

When I run the `Foo.exe` from the publish folder, I can see that everything is extracted and running from a temp folder as expected.

One thing I'm slightly confused about is that if I try to delete `Foo.exe` from the publish folder (**not** the temp folder), then I get an error saying the file is already open by `Foo.exe`. Using process explorer I can also see that the `Foo.exe` from the publish folder is held open by a file that itself is called `Foo.exe`.

I thought that given the application is self-contained, I can delete and change the executable from the publish folder freely, because the actual app is running from the temp folder. Any idea why the exe seems to be held open by a file that has the same name as the exe itself?

**EDIT**
The exe is configured to run as a windows service.

**Comment by swaroop-sridhar** [comment]
@IIFE is this specific to single-file apps, or all self-contained apps?

**Comment by IIFE** [comment]
@swaroop-sridhar same issue occurs if it's single-file self-contained (i.e. self-extracting), or just self-contained without the single file flag.

For my specific case I wish to have single-file self-contained, and be able to replace/delete the exe from the publish folder that was run and self-extracted everything to a temp folder.

**Comment by IIFE** [comment]
Just wanted to add that I can certainly **rename** the exe file from the publish folder while it's running (only during first run and not subsequent runs, just like #1260), however, the specific issue I have is that I cannot **delete** or **overwrite** the exe from the publish folder.

For the self update scenario I have, that can occur while the self-extracted app is running, I can achieve it by (as long as #1260 is resolved):
- Rename existing exe
- Copy new exe to location
- Ensure renamed exe is deleted when the app re-launches

However, it's much cleaner if I can just overwrite the existing exe without having to rename it.

**Comment by vitek-karas** [comment]
I think this is by design. The single-file bundle doesn't spawn a child process to run the app, it runs it "in-proc". This is necessary for multiple reasons:
* Some apps rely on getting the right PID from the outside and inside (basically tools talking to the app from the outside assume it's the process they launched and not a child)
* The single-file.exe contains native manifest on Windows - the child process would have to somehow duplicate that.
* Resource usage, spawning second process is both slower and requires more memory.
* Consistent behavior between single-file and non-single-file apps

I understand that it would be "nice", but that's how any typical executable behaves, so the fact that single-file apps are the same is good in my mind (consistent with everything else, not special if possible).

**Comment by vitek-karas** [comment]
Also of note - the improved single-exe planned for .NET 5 (Which will hopefully not extract to disk, or only very little) makes this a necessity - there's no second "app" to run in that case (the bundle contains all the code, runtime and everything runnable from memory without writing to disk).

**Comment by swaroop-sridhar** [comment]
Also, as @IIFE has confirmed, this is not specific to single-file apps. 
Its true for any .net app running through the apphost. 
The apphost remains loaded in the process and cannot be removed while it is running.

**Comment by IIFE** [comment]
> I think this is by design. The single-file bundle doesn't spawn a child process to run the app, it runs it "in-proc". This is necessary for multiple reasons:
> 
> * Some apps rely on getting the right PID from the outside and inside (basically tools talking to the app from the outside assume it's the process they launched and not a child)
> * The single-file.exe contains native manifest on Windows - the child process would have to somehow duplicate that.
> * Resource usage, spawning second process is both slower and requires more memory.
> * Consistent behavior between single-file and non-single-file apps
> 
> I understand that it would be "nice", but that's how any typical executable behaves, so the fact that single-file apps are the same is good in my mind (consistent with everything else, not special if possible).

Thanks for the clarification. I guess I had a misunderstanding on how the self extraction works as I thought the only purpose of the produced exe is to extract the app, not actually run it.

Happy to close issue. Will try to work with the rename approach.

Thanks.
