### ISSUE TITLE
Crossgen2 is missing support for ENCODE_CHECK_FIELD_OFFSET helper

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#32630]
During my work on composite R2R I noticed that in instance field access logic in EncodeFieldBaseOffset we're missing proper implementation of valuetypes with layout that is not fixed in version bubble. According to Crossgen1 this should be using the above helper so that needs adding another NodeCache and related vertical.

**Comment by MichalStrehovsky** [comment]
Fixed in #33729.
