### ISSUE TITLE
API proposal: Array.IsNullOrEmpty

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#32642]
### Justification

A helper method along the same lines of `string.IsNullOrEmpty`. We have several dozen places within _System.Private.CoreLib_ alone which perform array null or empty checks: see https://github.com/GrabYourPitchforks/runtime/commit/ef639cd4ecf4f39e540438709c723aee43bbd618 for a prototype of this change and a list of candidate call sites.

Furthermore, we can perform tricks within `Array.IsNullOrEmpty` similar to what we already do in `string.IsNullOrEmpty`. These take advantage of patterns the JIT already recognizes in order to optimize the codegen for code later in the method.

For example:

```cs
int[] theArray = GetArray();
if (!Array.IsNullOrEmpty(theArray))
{
    int element = theArray[0]; // JIT elides bounds check here
}
```

This API obviously isn't _required_ for apps to have correct behavior (devs have gone without it for 20+ years). But it is a convenience method that could add succinctness and clarity to call sites, and it could give a minor perf boost to some scenarios.

### API Proposal

```cs
namespace System
{
    public abstract partial class Array
    {
        public static bool IsNullOrEmpty([NotNullWhen(false)] Array? array) { throw null; }
    }
}
```

There's no need for this method to be generic on _T_; taking a standard `Array` would be sufficient to cover all use cases.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/16359

**Comment by GrabYourPitchforks** [comment]
You're dashing my hopes and dreams, man. :)

**Comment by stephentoub** [comment]
:smile:

**Comment by AaronRobinsonMSFT** [comment]
Within the link that @stephentoub mention above, there is a comment about `ICollection.IsNullOrEmpty()`. Perhaps that would have a bit more traction. I am personally convinced by the argument this isn't needed specifically for `Array`, but would be open to the debate for `ICollection`.

**Comment by GrabYourPitchforks** [comment]
`ICollection` would definitely be more generalizable. The primary arguments I can think of for a method which takes `Array` directly are: (a) no virtual dispatch is needed and it keeps the call site very tight, and (b) it allows the JIT to elide accesses to `theArray[0]` immediately after the check. See for instance https://github.com/GrabYourPitchforks/runtime/commit/ef639cd4ecf4f39e540438709c723aee43bbd618#diff-323079a1c1a8542b4d4c229b65fce067R2721.

**Comment by GrabYourPitchforks** [comment]
FWIW I did verify that the JIT does elide the bounds check on the pattern `if (!Array.IsNullOrEmpty(someArray)) { /* use someArray[0] */ }`. Still not quite sure if it's an important enough optimization for this.

**Comment by stephentoub** [comment]
Does it not elide it for:
```C#
if (someArray != null && someArray.Length != 0) { /* use someArray[0] */ }
```
or
```C#
if (someArray?.Length != 0) { /* use someArray[0] */ }
```
?

**Comment by GrabYourPitchforks** [comment]
Correct, those patterns aren't elided. There's a code comment in `string.IsNullOrEmpty` explaining it in more detail.

https://github.com/dotnet/runtime/blob/97b0b37aa1d6875a248751e75ad088961bfe9ff5/src/libraries/System.Private.CoreLib/src/System/String.cs#L458-L467

**Comment by jkotas** [comment]
> Correct, those patterns aren't elided. There's a code comment in `string.IsNullOrEmpty` explaining it in more detail.

That is a bug to fix in the JIT, not to workaround by adding new APIs.

**Comment by GrabYourPitchforks** [comment]
Yeah, I only found around 30-ish call sites within System.Private.CoreLib that would be candidates for using this helper method. (See https://github.com/GrabYourPitchforks/runtime/commit/ef639cd4ecf4f39e540438709c723aee43bbd618.) That might not be enough to justify the work. Even `string.IsNullOrEmpty` has around 5x that many call sites within CoreLib.

**Comment by juliusfriedman** [comment]
> ### Justification
> A helper method along the same lines of `string.IsNullOrEmpty`. We have several dozen places within _System.Private.CoreLib_ alone which perform array null or empty checks: see [GrabYourPitchforks@ef639cd](https://github.com/GrabYourPitchforks/runtime/commit/ef639cd4ecf4f39e540438709c723aee43bbd618) for a prototype of this change and a list of candidate call sites.
> 
> Furthermore, we can perform tricks within `Array.IsNullOrEmpty` similar to what we already do in `string.IsNullOrEmpty`. These take advantage of patterns the JIT already recognizes in order to optimize the codegen for code later in the method.
> 
> For example:
> 
> ```cs
> int[] theArray = GetArray();
> if (!Array.IsNullOrEmpty(theArray))
> {
>     int element = theArray[0]; // JIT elides bounds check here
> }
> ```
> 
> This API obviously isn't _required_ for apps to have correct behavior (devs have gone without it for 20+ years). But it is a convenience method that could add succinctness and clarity to call sites, and it could give a minor perf boost to some scenarios.
> 
> ### API Proposal
> ```cs
> namespace System
> {
>     public abstract partial class Array
>     {
>         public static bool IsNullOrEmpty([NotNullWhen(false)] Array? array) { throw null; }
>     }
> }
> ```
> 
> There's no need for this method to be generic on _T_; taking a standard `Array` would be sufficient to cover all use cases.

Having this method not return the length via out is dumb

**Comment by GrabYourPitchforks** [comment]
Previously considered and rejected. Closing.
