### ISSUE TITLE
Using both GenerateReferenceSource and Rebuild targets deletes ref dll in ref\netcoreapp5.0

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#32659]
I noticed using both GenerateReferenceSource and Rebuild targets on a src project removes the ref dll and we get error:

'runtime\artifacts\bin\ref\netcoreapp5.0\X.dll' is not found. 

To repro:

```
ref directory > dotnet msbuild X.csproj /t:rebuild
src directory > dotnet msbuild X.csproj /t:rebuild;GenerateReferenceSource
```

Eventhough we are not supposed to use both targets at the same time, I thought to share this observation. 

--- 

FYI, I personally tried all this in release configuration, so I added /p:Configuration=Release to all commands above.

cc: @Anipik

**Comment by maryamariyan** [comment]
Another observation I made was that, when both targets are specified and I also specify /p:BuildTargetFramework=netcoreapp5.0, then even if dll 

runtime\artifacts\bin\ref\netcoreapp5.0\X.dll'

was not available I think it gets copied over from 

runtime\artifacts\bin\X\ref\netstandard2.1-Release\X.dll

**Comment by Anipik** [comment]
no longer reproducible so closing this one
