### ISSUE TITLE
Discussion: Fallback CoreCLR build to OSX/x64 when building for iOS

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#32662]
I'm working on a branch that adds an iOS target OS to the build system.

This causes an issue for the CoreCLR build because it doesn't know how to build for that target and until https://github.com/dotnet/runtime/issues/32613 is fixed we need the CoreCLR build for the libraries build.

My current thinking was that the build can simply fallback to OSX.x64 in that case as it's the only platform where iOS can be built. I've implemented that in https://github.com/akoeplinger/runtime/commit/23cca6bfd3e0220c32bee8ada9f47569b237e6ae.

@ViktorHofer asked me to open a discussion issue so we can decide whether that is the correct approach and get some input from @jkotas.

**Comment by jkotas** [comment]
> fallback to OSX.x64 

That does not sound like the right approach to me. We should not building CoreCLR at all when building for iOS.

**Comment by akoeplinger** [comment]
@jkotas I agree but the libraries build requires CoreCLR at the moment.

**Comment by jkotas** [comment]
What does the libraries build require from CoreCLR?

**Comment by jkotas** [comment]
It should be just `System.Private.CoreLib` and it should be trivial to switch libraries to consume `System.Private.CoreLib` from Mono.

**Comment by akoeplinger** [comment]
I haven't looked into that but if it's trivial then yeah we should go that way instead.

@ViktorHofer can you take a look?

**Comment by steveisok** [comment]
From what I've seen it requires `System.Private.CoreLib`, its pdb and dwarf file.

**Comment by akoeplinger** [comment]
There's more logic that checks for CoreCLR artifacts like this one: https://github.com/dotnet/runtime/blob/58cf1468e1d9519c3752dfd40402eb4fda6fb9e9/eng/liveBuilds.targets#L91

I'm not sure if it's the only place.

**Comment by ViktorHofer** [comment]
We also need the [Microsoft.NET.Sdk.IL (ilasm, ildasm)](https://github.com/dotnet/runtime/tree/master/src/coreclr/src/.nuget/Microsoft.NET.Sdk.IL)

**Comment by steveisok** [comment]
Is it just ilasm / ildasm?  If so, can we use a fixed version for them?

**Comment by ViktorHofer** [comment]
I believe we aren't using a live version yet, so this shouldn't be an issue _at the moment_: https://github.com/dotnet/runtime/issues/1137.

**Comment by akoeplinger** [comment]
Ok, given that the fallback approach isn't desirable and we should instead fix the libraries build to no longer require CoreCLR let's continue the discussion in https://github.com/dotnet/runtime/issues/32613.
