### ISSUE TITLE
Crossgen2 is missing support for CORINFO_FIELD_STATIC_ADDRESS

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#32663]
We could achieve minor perf improvement when accessing statics by implementing the static address helper (ldsflda). Crossgen1 doesn't do this, it bails out at this point:

https://github.com/dotnet/runtime/blob/58cf1468e1d9519c3752dfd40402eb4fda6fb9e9/src/coreclr/src/zap/zapinfo.cpp#L3216

For now I'm about to add a similar clause with a reference to this issue to Crossgen2 as otherwise it causes failures with composite R2R at runtime due to <code>System.Console.get_Out</code> which uses <code>ldsflda</code> on <code>System.Console.s_out</code>.

**Comment by mangod9** [comment]
appears to be resolved?

**Comment by davidwrighton** [comment]
I don't believe this is resolved. We now bail out, which matches crossgen behavior, but when targeting the container compile scenario, it is clear that a large number cases of the bail out are being hit by async state machine code. So, this bail out is a significant negative towards achieving our goals of crossgen2 having better AOT compilation for containers.
