### ISSUE TITLE
Process.MainWindowHandle is not correctly refreshed

### ISSUE THREAD

**Issue by fernandreu** [dotnet/runtime#32690]
I have come across an [issue](https://github.com/FlaUI/FlaUI/issues/298) with a third-party UI test library which I have finally tracked down to their internal use of `Process.MainWindowHandle`. Consider the following example:

```csharp
bool TestProcess()
{
    var process = Process.Start("notepad");
    try
    {
        for (var attempt = 0; attempt < 20; ++attempt)
        {
            process?.Refresh();
            if (process?.MainWindowHandle != IntPtr.Zero)
            {
                return true;
            }

            Thread.Sleep(100);
        }

        return false;
    }
    finally
    {
        process?.Kill();
    }
}
```

This function will return `true` in .NET Framework after a few refreshes, but `false` in .NET Core.

The reason is: once the getter of `MainWindowHandle` is called once, it will never be evaluated again. See [Process.Win32.cs](https://github.com/dotnet/runtime/blob/d872a664488f773b98376365da93c2f3425e15bd/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L237):

```csharp
public IntPtr MainWindowHandle
{
    get
    {
        if (!_haveMainWindow)
        {
            EnsureState(State.IsLocal | State.HaveId);
            _mainWindowHandle = ProcessManager.GetMainWindowHandle(_processId);

            _haveMainWindow = true;
        }
        return _mainWindowHandle;
    }
}
```

There is no other `_haveMainWindow` assignment anywhere else that I can see. Therefore, if the handle was not ready yet (i.e. `_mainWindowHandle` gets assigned `IntPtr.Zero`), the class would assume it was ready anyway, set `_haveMainWindow` to true, and never re-evaluate this.

Due to this, I would propose two changes:

1. Change the line with the true assignment to: `_haveMainWindow = _mainWindowHandle != IntPtr.Zero;`
2. In [Process.Refresh()](https://github.com/dotnet/runtime/blob/d872a664488f773b98376365da93c2f3425e15bd/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L1117), add `_haveMainWindow = false;` (it seems to me this information should also be discarded together with the rest)

If you guys are happy with these changes, I would like to take care of making the pull request. I can also include a test demonstrating the issue as it stands, which would be very similar to the example I put above. I have already done these changes locally and can confirm it solves my issue without breaking any other test. Just be aware that it is unavoidable to launch a GUI to test this (I think). Microsoft-hosted agents in Azure Pipelines should not have any issues dealing with this, but perhaps you guys have other concerns.

**Comment by danmosemsft** [comment]
A PR would be great, thanks. For tests, we don't want to pop UI. It would need a more limited test. I think it is possible to mark a test so it's manual only and that could pop UI but I can't check right now.
