### ISSUE TITLE
System.Runtime.Loader.DetermineLibraryNameVariations on Windows doesn't match native

### ISSUE THREAD

**Issue by NextTurn** [dotnet/runtime#32708]
Reopened #12566

Related to dotnet/corert#5717

`System.Runtime.Loader.DetermineLibNameVariations` is used by:

- `System.Runtime.Loader.AssemblyDependencyResolver` in CoreCLR with `File.Exists` probing.
- P/Invoke in CoreRT with `LoadLibrary` probing.

The file names listed are **real names** in file system instead of parameters in `LoadLibrary` calls.

## Expected managed behaviors

- **The name does not contain dot: Try the name + `.dll` only.**
- **The name ends with a dot: Try the base name only.**
- The name ends with `.dll`/`.exe`: Try the name only.
- Otherwise: Try the name then the name + `.dll`.

## Actual managed behaviors in CoreCLR

- **The name does not contain dot: Try the name then the name + `.dll`.**
- **The name ends with a dot: Try the name then the name + `.dll`.**
- The name ends with `.dll`/`.exe`: Try the name only.
- Otherwise: Try the name then the name + `.dll`.

## Actual managed behaviors in CoreRT

- **The name does not contain dot: Try the name + `.dll` twice.**
- **The name ends with a dot: Try the base name then the name + `.dll`.**
- The name ends with `.dll`/`.exe`: Try the name only.
- Otherwise: Try the name then the name + `.dll`.

## Native behaviors of `LoadLibrary`

- **The name does not contain dot: Try the name + `.dll`.**
- **The name ends with a dot: Try the base name.**
- The name ends with `.dll`/`.exe`: Try the name.
- Otherwise: Try the name.

## Summary

||Expected|CoreCLR|CoreRT|Windows|
|-|-|-|-|-|
|**foo**|**foo.dll**|**foo + foo.dll**|**foo.dll * 2**|**foo.dll**|
|**foo.**|**foo**|**foo. + foo..dll**|**foo + foo..dll**|**foo**|
|foo.dll|foo.dll|foo.dll|foo.dll|foo.dll|
|foo.bar|foo.bar + foo.bar.dll|foo.bar + foo.bar.dll|foo.bar + foo.bar.dll|foo.bar|

**Comment by jkotas** [comment]
AssemblyDependencyResolver feeds the name into `FileExist`. P/Invoke resolver feeds the name into `LoadLibrary`. The logic for each two cases is different for a reason. `LoadLibrary` does its own appending of `.dll` suffix, etc.

Related comment: https://github.com/dotnet/coreclr/pull/24203#discussion_r277902414

Perhaps this should be fixed by having an extra bool argument that says what the result is going to be used for.

**Comment by jkotas** [comment]
We can use  dotnet/corert#5717 to track this. This is CoreRT specific issue. We track CoreRT specific issues in CoreRT repo.
