### ISSUE TITLE
Why is Microsoft.Extensions.Primitives.InplaceStringBuilder obsolete?

### ISSUE THREAD

**Issue by ygc369** [dotnet/runtime#32703]
I have not explored it in depth, but I have found that it is a `struct`, so it might have a bit performance advantage over `StringBuilder` which is a `class`. 
I wonder why it is marked as obsolete?

**Comment by davidfowl** [comment]
[string.Create](https://docs.microsoft.com/en-us/dotnet/api/system.string.create?view=netcore-3.1) is a better alternative.

**Comment by ygc369** [comment]
@davidfowl 
I have a question about `string.Create`, for it requires the string length as a parameter, then what if the initialized length (the length of the the initialized part) is less then the string length? if this happened, there would be an uninitialized part left in the string, if we show the string, what would happen?

**Comment by davidfowl** [comment]
You'll have null characters left in the string.

**Comment by ygc369** [comment]
@davidfowl 
I have tested string with null chars, and find that when I use `Console.WriteLine` to show such string, these null chars are just like "blank space" chars and printable chars after null chars can be shown too. Sometimes this is not my expected behavior. I hope the null char could be the terminated flag of a string, no matter what exist after it. 
So I propose to add the following properties to the string class:
1. bool string.IsNullTerminated { get; set; } ---- If it is set as true, then the string.Length will return the length before the first null char in the string (if no null char, return capacity), and when the string is shown, only chars before the first null char can be shown (just like C-style string, but if no null char, show the whole string). Chars after null char in a null-terminated string can't be accessed unless using unsafe code. To avoid breaking change, this property should be false by default, so if it is not set, the current string behavior will not change.
2. int string.Capacity { get; } ---- If string.IsNullTerminated is set as true, then string.Length can not represent the capacity of the string. So we need a new property to get the capacity.
3. bool string.ShrinkWhenGC { get; set; } ---- False by default to avoid breaking change. When it is set as true, if the string is alive when GC happens, the space after the first null char in the string (including the first null char itself) will be reclaimed by GC, and the string's capacity will shrink to be equal to its length. 

If we have these properties above, then when we use `string.Create`, we could just give a roughly estimated capacity, and don't have to calculate/predict the exact initialized length before actual initialization.

**Comment by DaZombieKiller** [comment]
> `bool string.IsNullTerminated { get; set; }`

This conflicts with the idea of strings being considered immutable in .NET, thus I personally am against it.

`string.Create` is intended for situations where you know the length of the string in advance, so you can avoid multiple allocations.

`InplaceStringBuilder` is a very similar API with roughly the same restrictions. The `capacity` parameter of `InplaceStringBuilder`'s constructor is actually more accurately described as `length`. ([Source](https://source.dot.net/#Microsoft.Extensions.Primitives/InplaceStringBuilder.cs))

If you are in a situation where you cannot calculate the length of the string in advance, then I don't believe there is a BCL solution other than `StringBuilder`.

**Comment by ygc369** [comment]
@DaZombieKiller 
Thank you for your example, but I think I can even do it like the following:
```C#
public static class StringExtension
    {
        unsafe public static void SetLength(this string s, int length)
        {
            fixed (char* p = s)
            {
                int* n = (int*)(p - 2);
                *n = length;
            }
        }        
    }
    class Program
    {
        static void Main(string[] args)
        {
            string s = new string('a', 100);
            s.SetLength(10);            
            Console.WriteLine("{0}:{1}\n", s.Length, s);
        }
    }
```

**Comment by DaZombieKiller** [comment]
@ygc369 That is indeed another way to do it, although I find the `Unsafe.As` approach to be much more readable (and clearer) than using pointer arithmetic.

**Comment by jkotas** [comment]
Both the suggestions above are corrupting GC heap. You are likely going to see a crash during next GC. Do not ever do that.

**Comment by DaZombieKiller** [comment]
@jkotas That's news to me, I had mainly advised against it due to memory wastage, but if there's potential GC heap corruption then I regret even mentioning it. Could you offer any additional details pertaining to how/why this corrupts the heap for curiosity's sake?

**Comment by jkotas** [comment]
>  I presume modifying Length causes the GC to be unaware of the full size of the object, leading to a myriad of problems when moving/freeing the memory.

Yes, that is the problem. 

The discussion in https://github.com/HelloKitty/Reinterpret.Net/issues/1 has a lot more details about this.
