### ISSUE TITLE
API Proposal: Linq Any and All should have versions with indexer

### ISSUE THREAD

**Issue by DevDrake** [dotnet/runtime#32712]
**Justification**

Where and Select functions are providing the way of selector/predicate with indexer. Any and All seems to embed Where filter, therefore it should also support predicate with indexer.
I sow plenty of code that code around this issue using **Where((x,i)=>...)** and then empty **.Any()** or **.All(...)**.

This API obviously isn't required for apps to have correct behavior. But it is a convenience method that could add succinctness and clarity to call sites.

**API Proposal**

```cs
namespace System.Linq
{
    public static partial class Enumerable
    {
        public static bool All<TSource>(this IEnumerable<TSource> source, Func<TSource, int, bool> predicate);
        public static bool Any<TSource>(this IEnumerable<TSource> source, Func<TSource, int, bool> predicate)
    }
}
```

**Considerations**

- We also should consider the change for other Linq functions like First, Last, Single, Contains, Aggregate.
- AsyncEnumerable
- Queryable

**Comment by artelk** [comment]
You can achieve that with Select returning the tuple
```cs
new[] { "7", "1" }.Select((v, i) => (v, i)).Any(p => p.v == p.i.ToString());
```

**Comment by DevDrake** [comment]
> 
> 
> You can achieve that with Select returning the tuple
> 
> ```cs
> new[] { "7", "1" }.Select((v, i) => (v, i)).Any(p => p.v == p.i.ToString());
> ```

Indeed. However it is much slower than native implementation:
```
|     AnyIt3 | 1000 |     87.19 ns |   1.379 ns |   1.222 ns |
|   AnyItOrg | 1000 |     82.42 ns |   0.395 ns |   0.350 ns |
| Workaround | 1000 |    223.65 ns |   3.222 ns |   3.014 ns |
```
        
```cs
        private IEnumerable<int> hash;

        [Params(10, 1000)]
        public int N;

        [GlobalSetup]
        public void Setup()
        {
            hash = new HashSet<int>(System.Linq.Enumerable.Range(10, N));
        }

        [Benchmark]
        public bool AnyIt3() => hash.Any2((x, i) => i == 5);

        [Benchmark]
        public bool AnyItOrg() => hash.Any(x => x == 15);
        
        [Benchmark]
        public bool Workaround() => hash.Select((v, i) => (v, i)).Any(p => p.i == 5);
```

**Comment by artelk** [comment]
I think Linq to Objects shouldn't be used for the code that require maximum-possible performance.
And I suspect the Any with indexer is too exotic for being added to the framework.
If the predicate only checks the index you probably could call Count() or Take(N).Count() to determine if the Any is true.
And I couldn't invent a real example when you would need a predicate by both value and index.

**Comment by mburbea** [comment]
I would wonder if `.Where((x,i)=> i==5).Any()` would be faster?

**Comment by DevDrake** [comment]
That's just example, obviously no one will use it just for that. The need for Any/All indexer are the same as for Where/Select indexer. No more no less in my opinion.
As for me, current API is inconsistent, as Where have indexer where All/Any have not.

**Comment by DevDrake** [comment]
>I would wonder if .Where((x,i)=> i==5).Any() would be faster?

```cs
        [Benchmark]
        public bool AnyIt3() => hash.Any2((x, i) => i == 5);

        [Benchmark]
        public bool Workaround() => hash.Select((v, i) => (v, i)).Any(p => p.i == 5);

        [Benchmark]
        public bool Workaround2() => hash.Select((v, i) => i).Any(p => p == 5);

        [Benchmark]
        public bool Workaround4() => hash.Where((x, i) => i == 5).Any();
```
and results

```
|      Method |    N |      Mean |    Error |   StdDev |
|------------ |----- |----------:|---------:|---------:|
|      AnyIt3 |   10 |  85.17 ns | 1.619 ns | 1.514 ns |
|  Workaround |   10 | 214.96 ns | 1.191 ns | 1.056 ns |
| Workaround2 |   10 | 174.33 ns | 0.905 ns | 0.802 ns |
| Workaround4 |   10 | 124.28 ns | 0.805 ns | 0.753 ns |
|      AnyIt3 | 1000 |  86.82 ns | 1.382 ns | 1.225 ns |
|  Workaround | 1000 | 221.89 ns | 2.915 ns | 2.584 ns |
| Workaround2 | 1000 | 176.77 ns | 2.196 ns | 2.054 ns |
| Workaround4 | 1000 | 124.30 ns | 0.939 ns | 0.784 ns |
```

**Comment by jkoritzinsky** [comment]
I believe that @artelk is correct and that the highest performance here for your test case would be the following:

```csharp
hash.Skip(5).Take(1).Any();
```

**Comment by DevDrake** [comment]
> 
> I believe that @artelk is correct and that the highest performance here for your test case would be the following:
> 
> ```cs
> hash.Skip(5).Any();
> ```

```cs
        [Benchmark]
        public bool Workaround5() => hash.Skip(5).Any();
```

`| Workaround5 |   10 |  97.32 ns | 0.267 ns | 0.237 ns |`

It is still slower than implementation of Any() with indexer :). 
Anyway that doesn't change the fact, it just a dummy test of something that needs indexer and object for predicate, as **Where** does. Using Skip is not universal for that purpose, as Select and Where are.

Also i disagree that Linq should not be used for performance. I think **Any()** is not slower than `count > 0 ` so it generally should be used instead.

The API Proposal was made for the API consistency mainly. Honestly I was surprised that I can write **Where** with indexer but not **Any/All**. 

I understand we may not want to extend API because all the things are already possible by using **Select + Any/All**, or **Where + Any/All**. 
If we do I will be happy to contribute.

**Comment by Clockwork-Muse** [comment]
... I think part of the issue here is that you're operating from the standpoint that the predicates are filters.  That's true for `Where`, but not for any of your other examples.  It's a specialized case of a _transformation_, like for `Select`, one that's restricted anyways (that is, the return type).

If you're trying to test something about an `N`th element, you should probably be using `ElementAt` (or `ElementAtOrDefault`), and then testing the returned item.  In certain cases this will be _even faster_, as it can be specialized if the underlying collection turns out to be an array or `List` (and a couple of other cases).

Note that your examples using `HashSet` are suspect, because sets have no inherent order to them: the index of any particular item is not guaranteed to be stable.

**Comment by adamsitnik** [comment]
Hi @DevDrake 

> I sow plenty of code that code around this issue using **Where((x,i)=>...)** and then empty **.Any()** or **.All(...)**.

Could you please provide one real-life example?

> hash.Skip(5).Any();

Using `.Skip` combined with `.Any|All` is exactly how I imagine that this problem should be solved.

> It is still slower than the implementation of Any() with indexer

Do I see correctly that it's slower by 10ns (`97.32 ns - 88.25 ns`)?

**Comment by DevDrake** [comment]
Hi @adamsitnik,

Thanks for looking into the proposal!

> Could you please provide one real-life example? <
I will try to find and extract it for you, as that example I had in mind was in proprietary code.

> Using .Skip combined with .Any|All is exactly how I imagine that this problem should be solved. < 
I agree that from performance reasons that's the obvious choice, however It's not intuitive as the any+predicate is easiest to be replaced with where+predicate+any, and so did I before I checking performance impact. And therefore the proposal.

> Do I see correctly that it's slower by 10ns (97.32 ns - 88.25 ns)? <
Yes.

**Comment by adamsitnik** [comment]
> I agree that from performance reasons that's the obvious choice, however It's not intuitive as the any+predicate is easiest to be replaced with where+predicate+any, and so did I before I checking performance impact. And therefore the proposal.

As you have noticed, it was not obvious which methods to use. Linq is already BIG and we should add only new methods and overloads that are hard or impossible to implement using the existing ones. Since here it's a matter of using `Skip` (or `Take`) I believe that it's not worth adding the proposed overloads.

10ns is also very little time and if this particular scenario ever becomes a perf bottleneck, you should rather optimize your code and use a loop instead of LINQ.  

Once again thank you for your proposal.
