### ISSUE TITLE
RSocket compared to System.IO.Pipelines

### ISSUE THREAD

**Issue by pisees** [dotnet/runtime#32715]
Can you compare these two technologies to each other? Any thoughts for ASP.NET Core support RSocket in addition to gRPC?

**Comment by davidfowl** [comment]
System.IO.Pipelines and Rsocket aren't comparable technologies, RSocket is more like SignalR than anything else. It's a messaging protocol that can sit on top of any streaming transport. 

We don't have any plans to support RSocket out of the box and there's already a .NET package https://github.com/rsocket/rsocket-net/ (though it looks mostly inactive, I tried sending a PR https://github.com/rsocket/rsocket-net/pull/8)
