### ISSUE TITLE
Test failure in JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32729]
failed in job: [runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16935746&paneView=debug&resultId=102249)

Error message:
`
\nReturn code: 1\nRaw output file: /private/tmp/helix/working/9D000951/w/BFB60A37/e/JIT/opt/Reports/JIT.opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.output.txt\nRaw output:\nBEGIN EXECUTION\nin takeLock\nWarning: No files matching /private/tmp/helix/working/9D000951/w/BFB60A37/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/*.dll\nEmitting R2R PE file: /private/tmp/helix/working/9D000951/w/BFB60A37/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.dll\n\nin ReleaseLock\n/tmp/helix/working/9D000951/p/corerun ObjectStackAllocationTests.dll ''\nFAILURE (AllocateSimpleClassAndAddFields): unexpected allocation of 24 bytes\nFAILURE (AllocateSimpleClassesAndEQCompareThem): unexpected allocation of 48 bytes\nFAILURE (AllocateSimpleClassesAndNECompareThem): unexpected allocation of 48 bytes\nFAILURE (AllocateSimpleClassAndGetField): unexpected allocation of 24 bytes\nFAILURE (AllocateClassWithNestedStructAndGetField): unexpected allocation of 32 bytes\nFAILURE (AllocateClassWithNestedStructAndAddFields): unexpected allocation of 32 bytes\nFAILURE (AllocateSimpleClassWithGCFieldAndAddFields): unexpected allocation of 32 bytes\nFAILURE (AllocateSimpleClassAndAssignRefToAField): unexpected allocation of 32 bytes\nFAILURE (TestMixOfReportingAndWriteBarriers): unexpected allocation of 32 bytes\nSUCCESS (AllocateSimpleClassAndCheckTypeNoHelper)\nSUCCESS (AllocateSimpleClassAndCheckTypeHelper)\nSUCCESS (AllocateSimpleClassAndCast)\nSUCCESS (BoxSimpleStructAndAddFields)\nExpected: 100\nActual: 255\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/tmp/helix/working/9D000951/p\n> /private/tmp/helix/working/9D000951/w/BFB60A37/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.sh\nExpected: True\nActual: False
`

**Comment by AriNuer** [comment]
Test `JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.sh` failed again.
**Job:**
[runtime-coreclr crossgen2 #20200303.1](https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=results)


**Error message**
`
\nReturn code: 1\nRaw output file: /home/helixbot/work/ACBB0982/w/A90508C8/e/JIT/opt/Reports/JIT.opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.output.txt\nRaw output:\nBEGIN EXECUTION\nin takeLock\nWarning: No files matching /home/helixbot/work/ACBB0982/w/A90508C8/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/*.dll\nEmitting R2R PE file: /home/helixbot/work/ACBB0982/w/A90508C8/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.dll\n\nin ReleaseLock\n/home/helixbot/work/ACBB0982/p/corerun ObjectStackAllocationTests.dll ''\nFAILURE (AllocateSimpleClassAndAddFields): unexpected allocation of 24 bytes\nFAILURE (AllocateSimpleClassesAndEQCompareThem): unexpected allocation of 48 bytes\nFAILURE (AllocateSimpleClassesAndNECompareThem): unexpected allocation of 48 bytes\nFAILURE (AllocateSimpleClassAndGetField): unexpected allocation of 24 bytes\nFAILURE (AllocateClassWithNestedStructAndGetField): unexpected allocation of 32 bytes\nFAILURE (AllocateClassWithNestedStructAndAddFields): unexpected allocation of 32 bytes\nFAILURE (AllocateSimpleClassWithGCFieldAndAddFields): unexpected allocation of 32 bytes\nFAILURE (AllocateSimpleClassAndAssignRefToAField): unexpected allocation of 32 bytes\nFAILURE (TestMixOfReportingAndWriteBarriers): unexpected allocation of 32 bytes\nSUCCESS (AllocateSimpleClassAndCheckTypeNoHelper)\nSUCCESS (AllocateSimpleClassAndCheckTypeHelper)\nSUCCESS (AllocateSimpleClassAndCast)\nSUCCESS (BoxSimpleStructAndAddFields)\nExpected: 100\nActual: 255\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/ACBB0982/p\n> /home/helixbot/work/ACBB0982/w/A90508C8/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.sh\nExpected: True\nActual: False
`

**Stack trace**
`
   at JIT_opt._ObjectStackAllocation_ObjectStackAllocationTests_ObjectStackAllocationTests_._ObjectStackAllocation_ObjectStackAllocationTests_ObjectStackAllocationTests_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.opt/JIT.opt.XUnitWrapper.cs:line 2759
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=ms.vss-test-web.build-test-results-tab&runId=17263490&resultId=101921&paneView=debug

**Comment by AriNuer** [comment]
Test `JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.sh` failed again.
**Job:**
[runtime-coreclr crossgen2:20200311.1](https://dev.azure.com/dnceng/public/_build/results?buildId=556709&view=results)
**Error message:**
```
Return code: 1
Raw output file: /home/helixbot/work/A17108C8/w/B61D0993/e/JIT/opt/Reports/JIT.opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/A17108C8/w/B61D0993/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/*.dll
Emitting R2R PE file: /home/helixbot/work/A17108C8/w/B61D0993/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.dll

in ReleaseLock
/home/helixbot/work/A17108C8/p/corerun ObjectStackAllocationTests.dll ''
FAILURE (AllocateSimpleClassAndAddFields): unexpected allocation of 24 bytes
FAILURE (AllocateSimpleClassesAndEQCompareThem): unexpected allocation of 48 bytes
FAILURE (AllocateSimpleClassesAndNECompareThem): unexpected allocation of 48 bytes
FAILURE (AllocateSimpleClassAndGetField): unexpected allocation of 24 bytes
FAILURE (AllocateClassWithNestedStructAndGetField): unexpected allocation of 32 bytes
FAILURE (AllocateClassWithNestedStructAndAddFields): unexpected allocation of 32 bytes
FAILURE (AllocateSimpleClassWithGCFieldAndAddFields): unexpected allocation of 32 bytes
FAILURE (AllocateSimpleClassAndAssignRefToAField): unexpected allocation of 32 bytes
FAILURE (TestMixOfReportingAndWriteBarriers): unexpected allocation of 32 bytes
SUCCESS (AllocateSimpleClassAndCheckTypeNoHelper)
SUCCESS (AllocateSimpleClassAndCheckTypeHelper)
SUCCESS (AllocateSimpleClassAndCast)
SUCCESS (BoxSimpleStructAndAddFields)
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/A17108C8/p
> /home/helixbot/work/A17108C8/w/B61D0993/e/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/ObjectStackAllocationTests.sh
Expected: True
Actual: False
```
**Stack trace:**
`
at JIT_opt._ObjectStackAllocation_ObjectStackAllocationTests_ObjectStackAllocationTests_._ObjectStackAllocation_ObjectStackAllocationTests_ObjectStackAllocationTests_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.opt/JIT.opt.XUnitWrapper.cs:line 2856
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=556709&view=ms.vss-test-web.build-test-results-tab&runId=17557570&resultId=102134&paneView=debug
