### ISSUE TITLE
Test failure in baseservices/threading/paramthreadstart/ThreadStartBool/ThreadStartBool.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32727]
Job: 
[runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16935746&paneView=debug&resultId=100009)

Error message:
`
Managed assembly not found: No such file or directory\n\nReturn code: 1\nRaw output file: /private/tmp/helix/working/9D000951/w/A420097F/e/baseservices/threading/Reports/baseservices.threading/paramthreadstart/ThreadStartBool/ThreadStartBool.output.txt\nRaw output:\nBEGIN EXECUTION\n/tmp/helix/working/9D000951/p/corerun ThreadStartBool.dll 'false'\nExpected: 100\nActual: 255\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/tmp/helix/working/9D000951/p\n> /private/tmp/helix/working/9D000951/w/A420097F/e/baseservices/threading/paramthreadstart/ThreadStartBool/ThreadStartBool.sh\nExpected: True\nActual: False
`

**Comment by v-haren** [comment]
also failed in [baseservices/threading/paramthreadstart/ThreadStartObject_1/ThreadStartObject_1.sh](https://dev.azure.com/dnceng/public/_build/results?buildId=535434&view=ms.vss-test-web.build-test-results-tab&runId=16999006&resultId=101273&paneView=debug)

**Comment by AriNuer** [comment]
Similar test `baseservices/threading/paramthreadstart/ThreadStartBool_1/ThreadStartBool_1.sh` failed with same error.
**Job:**
[runtime-coreclr crossgen2:20200308.1](https://dev.azure.com/dnceng/public/_build/results?buildId=551992&view=results)

**Error:**
```
Managed assembly not found: No such file or directory

Return code: 1
Raw output file: /home/helixbot/work/AE3B09C8/w/BBCD0A41/e/baseservices/threading/Reports/baseservices.threading/paramthreadstart/ThreadStartBool_1/ThreadStartBool_1.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/home/helixbot/work/AE3B09C8/w/BBCD0A41/e/baseservices/threading/paramthreadstart/ThreadStartBool_1
/usr/bin/env bash ../ThreadStartBool/ThreadStartBool.sh 'true'
BEGIN EXECUTION
/home/helixbot/work/AE3B09C8/p/corerun ThreadStartBool.dll 'true'
Expected: 100
Actual: 255
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/AE3B09C8/p
> /home/helixbot/work/AE3B09C8/w/BBCD0A41/e/baseservices/threading/paramthreadstart/ThreadStartBool_1/ThreadStartBool_1.sh
Expected: True
Actual: False
```
**Stack trace:**
`
at baseservices_threading._paramthreadstart_ThreadStartBool_1_ThreadStartBool_1_._paramthreadstart_ThreadStartBool_1_ThreadStartBool_1_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs:line 431
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=551992&view=ms.vss-test-web.build-test-results-tab&runId=17427408&resultId=100006&paneView=debug

**Comment by davidwrighton** [comment]
This was fixed by infra changes to find the set of dlls instead of using the project name as dll name.
