### ISSUE TITLE
Test failure in JIT\\opt\\ObjectStackAllocation\\ObjectStackAllocationTests\\ObjectStackAllocationTests.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32724]
job: 
[runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16936268&resultId=101940&paneView=debug)

Error message:
`
\r\nReturn code: 1\r\nRaw output file: C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\Reports\JIT.opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n 1 file(s) copied.\r\n" "C:\h\w\986B0834\p\crossgen2\crossgen2" C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.org -o:C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\986B0834\p\System..dll" -r:"C:\h\w\986B0834\p\Microsoft..dll" -r:"C:\h\w\986B0834\p\mscorlib.dll" -r:C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\.dll"\r\nWarning: No files matching C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\.dll\r\nEmitting R2R PE file: C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.dll\r\n "C:\h\w\986B0834\p\corerun.exe" ObjectStackAllocationTests.dll \r\nFAILURE (AllocateSimpleClassAndAddFields): unexpected allocation of 24 bytes\r\nFAILURE (AllocateSimpleClassesAndEQCompareThem): unexpected allocation of 48 bytes\r\nFAILURE (AllocateSimpleClassesAndNECompareThem): unexpected allocation of 48 bytes\r\nFAILURE (AllocateSimpleClassAndGetField): unexpected allocation of 24 bytes\r\nFAILURE (AllocateClassWithNestedStructAndGetField): unexpected allocation of 32 bytes\r\nFAILURE (AllocateClassWithNestedStructAndAddFields): unexpected allocation of 32 bytes\r\nFAILURE (AllocateSimpleClassWithGCFieldAndAddFields): unexpected allocation of 32 bytes\r\nFAILURE (AllocateSimpleClassAndAssignRefToAField): unexpected allocation of 32 bytes\r\nFAILURE (TestMixOfReportingAndWriteBarriers): unexpected allocation of 32 bytes\r\nSUCCESS (AllocateSimpleClassAndCheckTypeNoHelper)\r\nSUCCESS (AllocateSimpleClassAndCheckTypeHelper)\r\nSUCCESS (AllocateSimpleClassAndCast)\r\nSUCCESS (BoxSimpleStructAndAddFields)\r\nExpected: 100\r\nActual: -1\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\986B0834\p\r\n> C:\h\w\986B0834\w\AA5B0938\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.cmd\r\nExpected: True\r\nActual: False
`

**Comment by MichalStrehovsky** [comment]
Crossgen2 doesn't support the `COMPlus_JitObjectStackAllocation=1` environment variable. We just need a way to pass this as a `--codegenopt:JitObjectStackAllocation=1` argument to crossgen2 invocation.

We could also just add support for the environment variables, but environment variables are a pretty bad interface (they're the typical source of the "why can't I repro this on my box?" fun).

**Comment by AriNuer** [comment]
Test `JIT\\opt\\ObjectStackAllocation\\ObjectStackAllocationTests\\ObjectStackAllocationTests.cmd` failed again.

**Job:**
[runtime-coreclr crossgen2:#20200303.1](https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=results)

**Error message:**
`
\r\nReturn code: 1\r\nRaw output file: C:\h\w\AE250995\w\B53509E0\e\JIT\opt\Reports\JIT.opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n 1 file(s) copied.\r\n" "C:\h\w\AE250995\p\crossgen2\crossgen2" C:\h\w\AE250995\w\B53509E0\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.org -o:C:\h\w\AE250995\w\B53509E0\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\AE250995\p\System..dll" -r:"C:\h\w\AE250995\p\Microsoft..dll" -r:"C:\h\w\AE250995\p\mscorlib.dll" -r:C:\h\w\AE250995\w\B53509E0\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\.dll"\r\nWarning: No files matching C:\h\w\AE250995\w\B53509E0\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\.dll\r\nEmitting R2R PE file: C:\h\w\AE250995\w\B53509E0\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.dll\r\n "C:\h\w\AE250995\p\corerun.exe" ObjectStackAllocationTests.dll \r\nFAILURE (AllocateSimpleClassAndAddFields): unexpected allocation of 24 bytes\r\nFAILURE (AllocateSimpleClassesAndEQCompareThem): unexpected allocation of 48 bytes\r\nFAILURE (AllocateSimpleClassesAndNECompareThem): unexpected allocation of 48 bytes\r\nFAILURE (AllocateSimpleClassAndGetField): unexpected allocation of 24 bytes\r\nFAILURE (AllocateClassWithNestedStructAndGetField): unexpected allocation of 32 bytes\r\nFAILURE (AllocateClassWithNestedStructAndAddFields): unexpected allocation of 32 bytes\r\nFAILURE (AllocateSimpleClassWithGCFieldAndAddFields): unexpected allocation of 32 bytes\r\nFAILURE (AllocateSimpleClassAndAssignRefToAField): unexpected allocation of 32 bytes\r\nFAILURE (TestMixOfReportingAndWriteBarriers): unexpected allocation of 32 bytes\r\nSUCCESS (AllocateSimpleClassAndCheckTypeNoHelper)\r\nSUCCESS (AllocateSimpleClassAndCheckTypeHelper)\r\nSUCCESS (AllocateSimpleClassAndCast)\r\nSUCCESS (BoxSimpleStructAndAddFields)\r\nExpected: 100\r\nActual: -1\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\AE250995\p\r\n> C:\h\w\AE250995\w\B53509E0\e\JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.cmd\r\nExpected: True\r\nActual: False
`

**Stack trace:**
`
at JIT_opt._ObjectStackAllocation_ObjectStackAllocationTests_ObjectStackAllocationTests_._ObjectStackAllocation_ObjectStackAllocationTests_ObjectStackAllocationTests_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.opt\JIT.opt.XUnitWrapper.cs:line 2759
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=ms.vss-test-web.build-test-results-tab&runId=17264072&resultId=102190&paneView=debug

**Comment by janvorli** [comment]
@mangod9 this test is failing because it requires the object stack allocation feature to be enabled (COMPlus_JitObjectStackAllocation=1). For crossgen2, it would have to be passed to the JIT at crossgening time. The test passes it in at runtime, so the feature is off for jitted code and the test finds that objects are allocated from heap instead of stack.
This test should be marked as crossgen incompatible.

**Comment by mangod9** [comment]
ok thanks, moving it to 6 then. I assume this test is probably already disabled for cg2 runs?

**Comment by davidwrighton** [comment]
I added a means for passing parameters to the crossgen2 process using the CrossGen2TestExtraArguments property. We should do that and re-enable this test.

**Comment by davidwrighton** [comment]
This was fixed with #40096
