### ISSUE TITLE
Test failure in  JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32726]
Job: 
[runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16936268&resultId=102132&paneView=debug)

Error message:
`
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'C:\h\w\986B0834\w\AA5B0938\e\JIT\superpmi\superpmicollect\Bytemark\Bytemark.dll'. The system cannot find the file specified.\r\nFile name: 'C:\h\w\986B0834\w\AA5B0938\e\JIT\superpmi\superpmicollect\Bytemark\Bytemark.dll'\r\n\r\nReturn code: 1\r\nRaw output file: C:\h\w\986B0834\w\AA5B0938\e\JIT\superpmi\Reports\JIT.superpmi\superpmicollect\Bytemark\Bytemark.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n "C:\h\w\986B0834\p\corerun.exe" Bytemark.dll \r\nExpected: 100\r\nActual: -532462766\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\986B0834\p\r\n> C:\h\w\986B0834\w\AA5B0938\e\JIT\superpmi\superpmicollect\Bytemark\Bytemark.cmd\r\nExpected: True\r\nActual: False
`

**Comment by mangod9** [comment]
This test is now passing on latest builds.
