### ISSUE TITLE
LDAP over SSL (Port 636) and GetDomain not working

### ISSUE THREAD

**Issue by svkuhn** [dotnet/runtime#32734]
Problem:
I need to use ldap over ssl (LDAPS, Port 636) in order to use GetDomain. But currently as soon as i change my domain to  SSL only i can't establish a connection. 

As what i found the problem currently is:
Utils.AuthType is internal, so i can't change the value to AuthType.SecureSocketLayer | AuthType.Secure.

Using DirectoryEntry with the correct AuthenticationType successfully establishs a connection to my domain.

I guess i need to dynamically change following settings in order to change the AuthenticationType:

`internal const AuthenticationTypes DefaultAuthType = AuthenticationTypes.Secure | AuthenticationTypes.Signing | AuthenticationTypes.Sealing;`

[Utils.cs](https://github.com/dotnet/runtime/blob/c415fe33ac14ec47431a70e8936982295f67032a/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/Utils.cs#L50)

These settings are then used in:

`internal static DirectoryEntry Bind(string ldapPath, string username, string password, bool useServerBind)
        {
            DirectoryEntry de = null;
            AuthenticationTypes authType = Utils.DefaultAuthType;
            if (useServerBind)
            {
                authType |= AuthenticationTypes.ServerBind;
            }
            de = new DirectoryEntry(ldapPath, username, password, authType);
            return de;
        }`

[DirectoryEntryManager.Bind](https://github.com/dotnet/runtime/blob/c415fe33ac14ec47431a70e8936982295f67032a/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/DirectoryEntryManager.cs#L261)

**Comment by ericstj** [comment]
Can you share more about the public API you are calling?  It sounds like you're saying that if you use a particular API you are unable to specify `AuthenticationTypes`, but it's possible there is a different API that supports this.

For instance, the internal method you pointed at, just calls a [public constructor](https://github.com/dotnet/runtime/blob/c415fe33ac14ec47431a70e8936982295f67032a/src/libraries/System.DirectoryServices/src/System/DirectoryServices/DirectoryEntry.cs#L74) on `DirectoryEntry` which you could call yourself.

/cc @tquerec

**Comment by svkuhn** [comment]
Our approach was using the function [ActiveDirectory.GetDomain](https://github.com/dotnet/runtime/blob/c415fe33ac14ec47431a70e8936982295f67032a/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/Domain.cs#L61) in order to establish a basic connection to the current machine of the user. This was an easy and convenient way to connect to current active directory of the machine with the context of the current user. 

Later we used [ActiveDirectory.Domain.GetDirectoryEntry](https://github.com/dotnet/runtime/blob/c415fe33ac14ec47431a70e8936982295f67032a/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/Domain.cs#L500) for other actions. 

The ActiveDirectory.GetDomain API was just more convenient to build up a connection because it aquires the path and user settings directly. This way we didn't need to setup a ldap path or a specific user for the connection. 

That's why i think that currently the API for ActiveDirectory.GetDomain does not support LDAPS. The reason for that is that there is currently no way to specify the AuthenticationType for the GetDomain API.

Hope i could answer your question.

**Comment by ericstj** [comment]
Can you propose an API that would solve this?  Should there be an overload on GetDirectoryEntry to accept an AuthenticationTypes?  I'm not an owner of DirectoryServices here, that's @tquerec, just trying to turn this into a proposal

Could you workaround this by calling the DirectoryEntry constructor yourself or do you not have enough information?

**Comment by joperezr** [comment]
This is actually already supported, and was added by @iinuwa on PR https://github.com/dotnet/runtime/pull/52904 to 6.0. If you use the latest System.DirectoryServices.Protocols [preview package](https://www.nuget.org/packages/System.DirectoryServices.Protocols/6.0.0-preview.6.21352.12) so you should be able to do something like this:

```c#
LdapConnection connection = new LdapConnection(new LdapDirectoryIdentifier("yourLdapServer", 636), new NetworkCredential("myUser", "myPassword"));
connection.SessionOptions.ProtocolVersion = 3;
connection.SessionOptions.SecureSocketLayer = true; // -> This line instructs the connection to use ldaps:// instead of ldap:// which will make your credentials encrypted.
connection.Bind(); // -> This call to bind will be over SSL
```

**Comment by joperezr** [comment]
Given this is already supported, I'll go ahead and close this issue, but @svkuhn feel free to reopen if the snipped I shared doesn't work for you.
