### ISSUE TITLE
Official builds failing during signing validation

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32741]
Failing at 100% since at least 2020/2/21 with a single signing validation issue. 

https://dev.azure.com/dnceng/internal/_build?definitionId=679&_a=summary

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20117.3\tools\SdkTasks\SigningValidation.proj(57,5): error : Signing validation failed. Check D:\a\1\s\artifacts\log\Debug\\signcheck.errors.log for more information.
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20117.3\tools\SdkTasks\SigningValidation.proj(57,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Signing validation failed. Check D:\a\1\s\artifacts\log\Debug\\signcheck.errors.log for more information.
```

The signing log only had the following interesting info that I could find

```
    [File] WixDepCA, Signed: False, Excluded [Error] HRESULT: 800b0100 (No signature was present in the subject)
    [File] WixUIWixca, Signed: False, Excluded [Error] HRESULT: 800b0100 (No signature was present in the subject)
```

**Comment by jaredpar** [comment]
PR that caused the break https://github.com/dotnet/runtime/pull/32484

**Comment by ViktorHofer** [comment]
Signing validation is failing because of this file not being signed:

```
[File] fil5CEDBBA8A76E5217F437A0BE9B9E0203.dll, Signed: False, Full Name: dotnet\shared\Microsoft.NETCore.App\5.0.0-preview.2.20120.9\API-MS-Win-core-xstate-l2-1-0.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
```

**Comment by ViktorHofer** [comment]
Regressed with https://github.com/dotnet/runtime/commit/86a086377bd63cbe678b6cba5498e7ab4fd9b57d which removed ConfigurationGroup from the build scripts. Installer still uses it and we need to bring it back.

**Comment by dagood** [comment]
Specifically, here:

https://github.com/dotnet/runtime/blob/7edd9c927dfc1f7b909f2eebf9b00d6b9a7a20b0/eng/Signing.props#L53-L56
