### ISSUE TITLE
gcc compiles __declspec (uuid (x)) with errors

### ISSUE THREAD

**Issue by lbhnrg2021** [dotnet/runtime#32755]
ubuntu 18.04
gcc7.4
coreclr3.1.2
command:
./build.sh gcc
error:
src/pal/inc/rt/rpc.h:22:41: error: expected ‘)’ before ‘(’ token
#define DECLSPEC_UUID(x) __declspec(uuid(x))

gcc does not support uuid

**Comment by janvorli** [comment]
@lbhnrg2021 .NET Core 3.1 is not compilable with GCC, athough there were some changes in that direction. All the necessary changes are in the master  of the new runtime repo.
