### ISSUE TITLE
Vectorize codegen of switch statements

### ISSUE THREAD

**Issue by lpereira** [dotnet/runtime#32757]
It might be possible to use vector comparison instructions to improve codegen of switch statements.

This can probably be done for both strings and integers, although the details are different.  For instance, on strings:

```csharp
        switch (someString) {
            default: return 5;
            case "foo": return 130;
            case "bar": return 100;
            case "baz": return 200;    
        }
```

Will generate a series of:

```asm
   ldarg.0 // or something else to load someString
   ldstr "some string constant"
   call bool [System.Private.CoreLib]System.String::op_Equality(string, string)
   brtrue.s SomeLabel
```

Unfortunately, due to the strings being UTF-16 internally, comparing them with something like `pcmpeqd` or `vpcmpeqd` will be quite limited; however, a bunch of comparisons can be axed if the switch statement is performed in two steps: (1) compares the string prefixes and, if either of them matches, (2) generate the current code comparing with an offset.  Example:

```csharp
switch (someString) {
case "SomeLongString": return 5;
case "SomeStringWithSamePrefixAsPrev": return 4;
case "AnotherLongString": return 6;
case "YetAnotherString": return 7;
case "OneMoreForGoodMeasure": return 8;
default: return 0;
}
```

Would be generated as if this were written, in pseudo-code:

```csharp
vectored_switch (someString) {
case "Some":
   switch (someString[4..]) { 
      case "LongString": return  5,
      case "StringWithSamePrefixAsPrev": return 4
   }
   goto default_case;
case "Anot":
   switch(someString[4..]) { 
      case "herLongString": return 6
   }
   goto default_case;
case "YetA":
   switch (someString[4..]) { 
      case "notherString": return 7
   }
   goto default_case;
case "OneM":
   switch (someString[4..]) { 
      case "oreForGoodMeasure": return 8
   }
   goto default_case;
default:
   return 0;
}
```

Where `vectored_switch` would perform the comparison in parallel.  The inner switch statements would amortize the initial comparison.  If we take a look at the BCL to understand which kinds of strings are used in switch statements, we might learn that the common prefixes are much longer; if that's the case, then this particular solution won't help much; however, it is fixable by using some sort of longest subprefix match, such as a trie.

For integers, this could turn a bunch of:

```asm
ldarg.0 // or something else to push the expression in the stack
ldc.i4.???
beq.s SomeLabel
```

Into a jump table indexed by `CountTrailingZeros(parallelComparisonResult)` or something like that.  Indirect jumps are often less efficient than direct jumps, and integer comparison+conditional jumps are often macro-fused into one microop, but, depending on the size of the switch statement, this might be worth the trouble.  Would have to try (maybe by hand-writing the assembly first) and compare to what the JIT generates today.

category:cq
theme:optimization
skill-level:expert
cost:large

**Comment by benaadams** [comment]
When [String Deduplication](https://github.com/dotnet/runtime/blob/master/docs/design/features/StringDeduplication.md) is enabled (and perhaps even when not) it might be worth running through a set of `.ReferenceEquals` prior to falling back to `string` compares?

Gave some nice improvements for Kestrel https://github.com/dotnet/aspnetcore/pull/9341 which moves to the block matching length; then tests all as `.ReferenceEquals` and if non-pass then does `string.Equals`. 

However, in Kestrel this is more significant because the `string.Equals` used is `OrdinalIgnoreCase` whereas a regular switch statement is `Ordinal`.

**Comment by lpereira** [comment]
Ah, yes, good call.  Switching on longest subprefix length first with vector instructions, to then switch on the rest of the string themselves, might be actually a good idea.

**Comment by Suchiman** [comment]
It should be noted that once you reach 7 cases, roslyn will switch to a [hardcoded hash based lookup](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MGFUDeqmJ2WYAdsJgLIAUAysAE6UDmmAzgPYC2Apk1YU2ASmKkiKUjK4B3MMADGAC0x0eAoe3HTZJKfv1KAhp36YARAz78AMtxHaRlkNgDsmAKwBuCUdJTcysbLRZ2AHVFFQYTAQAFZn4AMzAADwBBTkT+ADdXD0wAFj89AJIgi0sMim5gFX5mBydwlzcYTwA2UvLAsyqATX5gGrqG5mc2Ao7Mdx7ezEqrAHkKfhpuJIAxTYBxbm4AExp+MwBXJOnPAA553qXrVrZOAEIrzABOO/KHh2BOZbJSavd4IAAM3wChxSJjOEFAhQh/lkAF9kWiUCigA===)

**Comment by benaadams** [comment]
>It should be noted that once you reach 7 cases, roslyn will switch to a hardcoded hash based lookup

There is now compiler detection of runtime support for features https://github.com/dotnet/runtime/issues/20623 as used by for example "default interface methods" https://github.com/dotnet/runtime/issues/21898; so roslyn can change what it does if the runtime supports something better.

**Comment by BruceForstall** [comment]
There are some cool ideas here, but in the absence of motivating real-world code examples, I'm going to close this. I believe the JIT doesn't see switch statements too often (it might be good if Roslyn passed through C# switch as IL switch more frequently), and there is probably a lot of room for general JIT switch implementation improvements.
