### ISSUE TITLE
`/azp run` can't start a pipeline if it is marked as `pr: none`

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#32777]
<samp>
Azure Pipelines could not run because the pipeline triggers exclude this branch/path.<br>

</samp>

_Originally posted by @azure-pipelines in https://github.com/dotnet/runtime/pull/32362#issuecomment-590618865_

with `/azp list` you can get the list of the available pipeline, but if you try to trigger them you will see:
`Azure Pipelines could not run because the pipeline triggers exclude this branch/path.
`
because they have that setting:
https://github.com/dotnet/runtime/blob/321632436c98365191d1b6175503553e82535f20/eng/pipelines/coreclr/ci.yml#L26

So if we want to be able to trigger something with `/azp run pipeline name` we need to do the workaround from https://github.com/MicrosoftDocs/vsts-docs/issues/4206

**Comment by karelz** [comment]
@sandreenko only 1 area label please - see [why](https://github.com/dotnet/runtime/blob/master/docs/project/issue-guide.md#motivation-for-triage-rules)

**Comment by ViktorHofer** [comment]
@trylek @safern do we know if this will change on the AzDO side? If not, I don't think this item is actionable and should be closed.

**Comment by trylek** [comment]
Well, so far I'm not aware of any indication that AzDO would be planning to roll out a fix / new functionality addressing this issue in the short term especially as this is kind of a feature request rather than a mere bugfix.

**Comment by ViktorHofer** [comment]
Can you remind me why some pipelines like the one mentioned in the top aren't triggerable? How is this pipeline different from the libraries outerloop which is triggerable?

**Comment by sandreenko** [comment]
> Can you please remind me why some pipelines like the one mentioned in the top aren't triggerable? How is this pipeline different from the libraries outerloop which is triggerable?

I think the task is:
1. trigger only a small amount of pipelines are when you run `/azp run`;
2.  make all optional heavy pipelines triggerable with `/azp run NAME`;

right now if we delete `pr: none` from all pipelines when you do `/azp run` it will run them all, that is undesirable for jit GCStress jobs etc. that are taking hours and many machines. But with `pr: none` you can't get the second.

**Comment by ViktorHofer** [comment]
Isn't /azp run already a no-op in dotnet/runtime as we set the pipeline limit to 10 and we have more than that?

**Comment by safern** [comment]
I think if we just remove the PR triggers and then set the options on the UI that the pipeline requires a comment to run, it would solve this issue.

> Isn't /azp run already a no-op in dotnet/runtime as we set the pipeline limit to 10 and we have more than that?

Yeah, this would happen and no pipelines would run, so I'm OK with removing the `PR` trigger section from the yml file.

**Comment by ViktorHofer** [comment]
@trylek can you help with that? I believe we just need to remove the `pr: none` entries and then mimic the pipelines UI settings with what we already have for libraries outerloop:

![image](https://user-images.githubusercontent.com/7412651/94665681-c08eb180-030c-11eb-8bfd-7ea79145d582.png)

**Comment by trylek** [comment]
If I'm right to understand that we still operate under the limitation that "/azp run" runs all the eligible pipelines, I guess we should only support a relatively small number of pipelines to avoid clogging the system by use of the parameterless command. I guess this rules out all the stress tests and mostly leaves in pipelines representing build variations - R2R, Crossgen2, maybe jit-experimental. Adding @BruceForstall who has the best knowledge of our pipeline portfolio and its usefulness to chime in.

**Comment by trylek** [comment]
OK, in such case I guess I'll just modify the UI settings for all pipelines as you described above and then we can arbitrarily start removing the <code>pr: none</code> specifiers.

**Comment by ViktorHofer** [comment]
Thanks Tomas

**Comment by sandreenko** [comment]
As I saw we now can trigger many pipelines with `/azp run`, it was fixed by #42933, @trylek should this issue be closed?

**Comment by ViktorHofer** [comment]
Yes, we can close the issue now. Thanks
