### ISSUE TITLE
MSBuild missing Multiply method 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32773]
Getting static method missing errors for `[MSBuild]::Multiply` when building dotnet/runtime now. 

```
F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.1.20112.7\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:F:\workspace\_work\1\s\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:__ToolsetLocationOutputFile=F:\workspace\_work\1\s\artifacts\toolset\5.0.0-beta.20121.6.txt /t:__WriteToolsetLocation /warnaserror F:\workspace\_work\1\s\artifacts\toolset\restore.proj
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20121.6\tools\Version.BeforeCommonTargets.targets(57,5): error MSB4186: Invalid static method invocation syntax: "[MSBuild]::Multiply($(_BuildNumberYY), 1000)". Method '[MSBuild]::Multiply' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. [F:\workspace\_work\1\s\eng\empty.csproj]
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20121.6\tools\Version.BeforeCommonTargets.targets(57,5): error MSB4186: Invalid static method invocation syntax: "[MSBuild]::Multiply($(_BuildNumberYY), 1000)". Method '[MSBuild]::Multiply' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order.
(NETCORE_ENGINEERING_TELEMETRY=Category) Build failed.
##[error]BUILD: Error: Failed to generate version headers.
BUILD:     -linuxdac x64 Release -skiptests -skipbuildpackages -officialbuildid -enforcepgo
##[error]Cmd.exe exited with code '1'.
```

Builds: 
- https://dev.azure.com/dnceng/internal/_build/results?buildId=534952
- https://dev.azure.com/dnceng/internal/_build/results?buildId=535050

**Comment by hoyosjs** [comment]
* https://dev.azure.com/dnceng/internal/_build/results?buildId=535218
* https://dev.azure.com/dnceng/internal/_build/results?buildId=535024

Seems to be consistently only on Windows x64 (even though x86, arm, and arm64 all use the same properties to generate versioning bits) and I expect all these to be building on x64 machines. I'd only expect this to be possible with an SDK change or an arcade update. However, these don't line up with the failures. Last place where this passed all legs is bc4fd91f9 and by 40d4b206 it was failing consistently.

**Comment by jaredpar** [comment]
@hoyosjs i verified it's not a result of the arcade merge. I did a revert and queued an official build and it failed with the same error. 

https://github.com/dotnet/runtime/pull/32780
https://dev.azure.com/dnceng/internal/_build/results?buildId=535279

**Comment by jaredpar** [comment]
Even stranger is the binary log for the failure doesn't actually have any errors.

**Comment by hoyosjs** [comment]
I think the suspect is the cross OS DAC build. Testing a revert right now.

**Comment by hoyosjs** [comment]
Actually, screw it, it is that. It doesn't set the officialbuildID correctly. sending the PR
