### ISSUE TITLE
TC_QuickJitForLoops support

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#32784]
`TC_QuickJitForLoops` is currently marked UNSUPPORTED. Do you have plans to make it EXTERNAL? We see 3% startup time improvement with this option enabled. 

cc @alpencolt @jkotas

**Comment by EgorBo** [comment]
It still works, `UNSUPPORTED` means `this value is available to partners/developers, but is not officially supported`

If you enable it - make sure you don't have cold methods with hot loops (e.g. some benchmarks). In this case you need to mark those with `[MethodImpl(MethodImplOptions.AggressiveOptimization)]`
see https://github.com/dotnet/runtime/issues/11006
