### ISSUE TITLE
Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by mikeTWC1984** [dotnet/runtime#32797]
Microsoft.Bcl.AsyncInterfaces has dependency on  System.Threading.Tasks.Extensions  >= 4.5.2, and it works fine with 4.5.2 version. However if upgraded to 4.5.3 app will throw below exception
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manif
est definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by ericstj** [comment]
When you upgrade a dependent nuget package you need to use bindingRedirects.  That's expected and same for any package when used on .NETFramework.  This happens automatically for most new projects.  See https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection for information about enabling autogeneration of bindingRedirects.

The following is what will be generated in the app.config in this case.
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

This is not required on .NETCore which has a more flexible binding policy.

/cc @joperezr
