### ISSUE TITLE
[System.Drawing.Common] Bug in printer-comment option resolution on PrintingServices.GetPrintDialogInfo()

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#32816]
Found in [PrintingServices.Unix.cs](https://github.com/dotnet/runtime/blob/e08396c7d291de20b1aedb260285b5955ec813de/src/libraries/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs#L669-L670) while annotating System.Drawing.Common in #31716. Seems like a clear-cut copy and paste bug.

cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
