### ISSUE TITLE
[System.Drawing.Common] Bitmap constructor thrown exception platform mismatch

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#32817]
It looks like the `public Bitmap(Type type, string resource)` constructor will throw different exception types for the same error condition on the [Windows](https://github.com/eiriktsarpalis/runtime/blob/e483b45468f2763e0d0f5b59366d9eb75804bcdb/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.Windows.cs#L18) and [Unix](https://github.com/dotnet/runtime/blob/e08396c7d291de20b1aedb260285b5955ec813de/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.Unix.cs#L80) implementations. Found while annotating for nullability #31716.

/cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
