### ISSUE TITLE
runtime-libraries stress-http pipeline is broken since 2/6

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32813]
https://dev.azure.com/dnceng/public/_build/results?buildId=535626

cc @eiriktsarpalis

**Comment by eiriktsarpalis** [comment]
I don't own that pipeline anymore, @dotnet/ncl  could you take a look?

**Comment by eiriktsarpalis** [comment]
Looks like adding multi-targeting broke the scripts.

**Comment by eiriktsarpalis** [comment]
This change seems to be the culprit https://github.com/dotnet/runtime/commit/725968c3c5562866c0a8a416b9a635fa54139f75.
