### ISSUE TITLE
Microsoft.NET.HostModel shouldn't be published to nuget.org

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#32825]
We are currently publishing `Microsoft.NET.HostModel` to https://www.nuget.org/packages/Microsoft.NET.HostModel. However, this package is not meant for public consumption, so we shouldn't be publishing it to nuget.org.

/cc @jkoritzinsky @swaroop-sridhar @dagood

**Comment by swaroop-sridhar** [comment]
The HostModel is only designed to be consumed by the SDK. 
It’s occasionally useful for external developers in order to extract or inspect the contents of a single-file app. However, the library is not vetted for a public release, and developers interested in it can build it from source.

**Comment by ViktorHofer** [comment]
Looks like this regressed 10-12 months ago, presumably with the move to Arcade.

**Comment by swaroop-sridhar** [comment]
The HostModel library has only been around since last April.

**Comment by dagood** [comment]
From offline:

> @dagood is there a change in runtime repo necessary to make this happen? Or is this done elsewhere? 

Yep, this is what the Shipping vs. NonShipping dirs are for, check out https://github.com/dotnet/arcade/blob/ff32e5111ec72af1b280186ae92c6090cb4585d4/Documentation/ArcadeSdk.md#isshipping-isshippingassembly-isshippingpackage-isshippingvsix-bool for the general idea. I think you want `<IsShipping>false</IsShipping>`. You can validate with a local build by looking at `artifacts/packages/...`.
