### ISSUE TITLE
WindowsDesktop installer doesn't install a distinct registry key (3.1)

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#32836]
The .NET Desktop 3.1.2 installer creates this registry key:

Key:`SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App`
Name: `3.1.2`
Value:`#1`

`Microsoft.NETCore.App` is the .NET Core Runtime, I would expect `Microsoft.WindowsDesktop.App` for the .NET Desktop Runtime.

I believe this is because we're missing `SharedFrameworkName` for the WindowsDesktop installer. That would be used here:

[src/pkg/packaging-tools/windows/wix.targets#L224 `      <RegKeyProductName Condition="'$(RegKeyProductName)' == '' and '$(SharedFrameworkName)' != ''">sharedfx\$(SharedFrameworkName)</RegKeyProductName>
`](https://github.com/dotnet/core-setup/blob/2d163b87b605fd23ceebfb04484e5ec5f2bffc32/src/pkg/packaging-tools/windows/wix.targets#L224)

which plugs into the reg key component here:

[src/pkg/packaging-tools/windows/product/registrykeys.wxs#L9 `        <RegistryKey Root="HKLM" Key="SOFTWARE\dotnet\Setup\InstalledVersions\$(var.Platform)\$(var.RegKeyProductName)">
`](https://github.com/dotnet/core-setup/blob/2d163b87b605fd23ceebfb04484e5ec5f2bffc32/src/pkg/packaging-tools/windows/product/registrykeys.wxs#L9)

The default value comes from the repo-wide props file:

[Directory.Build.props#L83 `    <SharedFrameworkName>Microsoft.NETCore.App</SharedFrameworkName>
`](https://github.com/dotnet/core-setup/blob/2d163b87b605fd23ceebfb04484e5ec5f2bffc32/Directory.Build.props#L83)

/cc @NikolaMilosavljevic

**Comment by danmosemsft** [comment]
@NikolaMilosavljevic nit, we don't use "servicing-xx" labels on issues.

**Comment by NikolaMilosavljevic** [comment]
[Triage] It would be too risky to change now; it could regress any customer workarounds.
