### ISSUE TITLE
Test failure in  Loader\\binding\\tracing\\BinderTracingTest.Basic\\BinderTracingTest.Basic.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32844]
**failed in job:** [runtime-coreclr crossgen2 20200225.2](https://dev.azure.com/dnceng/public/_build/results?buildId=536417&view=ms.vss-test-web.build-test-results-tab&runId=17025340&resultId=102666&paneView=debug)

**Error message**
`
\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\ncmdLine:C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd Timed Out\r\n\r\nReturn code: -100\r\nRaw output file: C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\Reports\Loader.binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n 1 file(s) copied.\r\n" "C:\h\w\ADEB091F\p\crossgen2\crossgen2" C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.org -o:C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\ADEB091F\p\System..dll" -r:"C:\h\w\ADEB091F\p\Microsoft..dll" -r:"C:\h\w\ADEB091F\p\mscorlib.dll" -r:C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\*.dll"\r\nEmitting R2R PE file: C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.dll\r\n "C:\h\w\ADEB091F\p\corerun.exe" BinderTracingTest.Basic.dll \r\nRunning LoadFile...\r\nRunning LoadBytes...\r\nRunning LoadFromStream...\r\nRunning LoadFromAssemblyPath...\r\nLaunching process for LoadFromAssemblyName...\r\nRunning LoadFromAssemblyName...\r\n\r\nLaunching process for LoadFrom...\r\nRunning LoadFrom...\r\n\r\nLaunching process for PlatformAssembly...\r\nRunning PlatformAssembly...\r\n\r\nLaunching process for PlatformAssembly_Cached...\r\nRunning PlatformAssembly_Cached...\r\n\r\nLaunching process for Reflection...\r\nRunning Reflection...\r\n\r\nLaunching process for Reflection_Cached...\r\nRunning Reflection_Cached...\r\n\r\nLaunching process for Reflection_CustomALC...\r\nRunning Reflection_CustomALC...\r\n\r\nLaunching process for ContextualReflection_DefaultToCustomALC...\r\nRunning ContextualReflection_DefaultToCustomALC...\r\n\r\nLaunching process for ContextualReflection_CustomToDefaultALC...\r\nRunning ContextualReflection_CustomToDefaultALC...\r\n\r\nLaunching process for JITLoad...\r\nRunning JITLoad...\r\n\r\nLaunching process for JITLoad_CustomALC...\r\nRunning JITLoad_CustomALC...\r\n\r\nRunning AssemblyInAppPath...\r\n\r\ncmdLine:C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\ADEB091F\p\r\n> C:\h\w\ADEB091F\w\AB580A1A\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd\r\nExpected: True\r\nActual: False
`

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr crossgen2 outerloop 20200411.1](https://dev.azure.com/dnceng/public/_build/results?buildId=597748&view=ms.vss-test-web.build-test-results-tab&runId=18829224&resultId=107184&paneView=debug)

failed in test: Loader\\binding\\tracing\\BinderTracingTest.Basic\\BinderTracingTest.Basic.cmd


Error message
~~~
Return code: 1
Raw output file: C:\h\w\B34B09C9\w\B79509F4\e\Loader\binding\Reports\Loader.binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.output.txt
Raw output:
BEGIN EXECUTION\
1 file(s) copied.
" "C:\h\w\B34B09C9\p\CoreRun.exe" "C:\h\w\B34B09C9\p\crossgen2\crossgen2.dll" C:\h\w\B34B09C9\w\B79509F4\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.org -o:C:\h\w\B34B09C9\w\B79509F4\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\B34B09C9\p\System..dll" -r:"C:\h\w\B34B09C9\p\Microsoft..dll" -r:"C:\h\w\B34B09C9\p\netstandard.dll" -r:"C:\h\w\B34B09C9\p\mscorlib.dll" -r:C:\h\w\B34B09C9\w\B79509F4\e\Loader\binding\tracing\BinderTracingTest.Basic\*.dll"
Emitting R2R PE file: C:\h\w\B34B09C9\w\B79509F4\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.dll
"C:\h\w\B34B09C9\p\corerun.exe" BinderTracingTest.Basic.dll 
Running LoadFile...
Running LoadBytes...
Running LoadFromStream...
Running LoadFromAssemblyPath...
Launching process for LoadFromAssemblyName...
Running LoadFromAssemblyName...
Launching process for LoadFrom...
Running LoadFrom...
Launching process for PlatformAssembly...
Running PlatformAssembly...
Launching process for PlatformAssembly_Cached...
Running PlatformAssembly_Cached...
Launching process for Reflection...
Running Reflection...
Launching process for Reflection_Cached...
Running Reflection_Cached...
Launching process for Reflection_CustomALC...
Running Reflection_CustomALC...
Launching process for ContextualReflection_DefaultToCustomALC...
Running ContextualReflection_DefaultToCustomALC...
Launching process for ContextualReflection_CustomToDefaultALC...
Running ContextualReflection_CustomToDefaultALC...
Launching process for JITLoad...
Running JITLoad...
Test JITLoad failed: TestLibrary.AssertTestException: Assert.AreEqual: Expected: [Default]. Actual: []. Unexpected value for RequestingAssemblyLoadContext on event
at TestLibrary.Assert.HandleFail(String assertionName, String message) in F:\workspace\_work\1\s\src\coreclr\tests\src\Common\CoreCLRTestLibrary\Assertion.cs:line 735
at TestLibrary.Assert.AreEqual[T](T expected, T actual, String message) in F:\workspace\_work\1\s\src\coreclr\tests\src\Common\CoreCLRTestLibrary\Assertion.cs:line 414
at BinderTracingTests.Helpers.ValidateBindOperation(BindOperation expected, BindOperation actual) in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\binding\tracing\Helpers.cs:line 24
at BinderTracingTests.BinderTracingTest.ValidateSingleBind(BinderEventListener listener, AssemblyName assemblyName, BindOperation expected) in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\binding\tracing\BinderTracingTest.cs:line 203
at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method) in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\binding\tracing\BinderTracingTest.cs:line 159
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B34B09C9\p
> C:\h\w\B34B09C9\w\B79509F4\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd
Expected: True
Actual: False


Stack trace
   at Loader_binding._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Loader.binding\Loader.binding.XUnitWrapper.cs:line 819
~~~

**Comment by mangod9** [comment]
This test passed on the latest build.
