### ISSUE TITLE
Build dotnet cli on qnx?

### ISSUE THREAD

**Issue by guesshe** [dotnet/runtime#32867]
I managed to build dotnet/coreclr on qnx but it can't run without the dotnet cli toolchain, does anyone know what is used to build dotnet cli and is it feasible to build it on qnx platform? QNX is POSIX compliant and supported x86_64 arch.

**Comment by ericstj** [comment]
I believe @wfurt has some steps that help in reusing binaries from other platforms on new OSes.
Also cc @dseefeld @MichaelSimons who drive source build that permits building the whole stack from source without build orchestration.

**Comment by wfurt** [comment]
That is certainly a bumpy road. Even if we have full cli for FreeBSD it is extremely difficult to use it for the build. Some c# parts are still platform dependent - Diagnostics.Process for example and without implementation build functions do no work.

My suggestion would be to start putting changes to recognize QNQ as a separate platform.    That would allow us to cross-target and build needed managed code on a supported platform. Source-build is useful but it needs a working SDK.

**Comment by guesshe** [comment]
Thank you very much! Tomas. I have another thread discussing on how to port dotnet/runtime to QNX, also facing some issues there, would you please take a look at that and see if anything is of interests? 
https://github.com/dotnet/runtime/issues/33374
