### ISSUE TITLE
Centos 7 HttpClient Post request Issue

### ISSUE THREAD

**Issue by lostmagicK** [dotnet/runtime#32880]
# HttpClient Timeout/Cancelled Exception

When i post data Timeout/Cancelled exception is thrown (in Cent Os 7, server nginx) but it perfectly fine when run on windows.
Is there a workaround for this?
Note: It works fine when i call within same application..
Here is my complete error
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at CardApp.Repository.Notifer.FCMSendNotification(NotificationRequest notification, String To) in C:\GitHub\CardApp\CardApp\Repository\Notifer.cs:line 59

**Comment by wfurt** [comment]
Do you have repro code @lostmagicK? There is not enough data to do any reasonable triage.  
I would also recommend doing packet capture with `tcpdump` or `wireshark` to see what is actually going on the wire. (or loopback)

**Comment by lostmagicK** [comment]
> Do you have repro code @lostmagicK? There is not enough data to do any reasonable triage.
> I would also recommend doing packet capture with `tcpdump` or `wireshark` to see what is actually going on the wire. (or loopback)

Due to restrictions i cannot share repo, but ill share the code. Its simple post request to call FCM

**Comment by lostmagicK** [comment]
`
public class Notifer : INotifier
{
        private readonly IConfiguration Configuration;
        private carddbContext _context;
        private IHttpClientFactory _clientFactory;

        public Notifer(IConfiguration _config, IHttpClientFactory clientFactory)
        {
            Configuration = _config;
            _clientFactory = clientFactory;
        }
	
	public async Task NotifyOnJoinRequest(List<NotificationRequest> requests)
        {
            using (_context = new carddbContext(Configuration.GetConnectionString("DefaultConnection")))
            {
                var userIDs = requests.Select(x => x.userID).ToList();
                var fcms = await _context.Audit.Where(x => x.deviceID != null && x.deviceID != "" && userIDs.Contains(x.userID)).Select(x => new { x.fcmID, x.userID }).ToListAsync();
                foreach (var item in requests)
                {
                    await FCMSendNotification(item, fcms.FirstOrDefault(x => x.userID == x.userID).fcmID);
                }
            }
        }

        private async Task FCMSendNotification(NotificationRequest notification, string To)
        {
            var client = _clientFactory.CreateClient();
            var payload = new
            {
                notification = new
                {
                    title = "Join Request",
                    body = notification.message,
                },
                to = To,
                priority = "high",
                content_available = true,
                data = notification
            };
            client.DefaultRequestHeaders.TryAddWithoutValidation("Authorization", $"key={Configuration.GetValue<string>("FCM:Key")}");
            client.DefaultRequestHeaders.TryAddWithoutValidation("Sender", $"id={Configuration.GetValue<string>("FCM:SenderID")}");
            try
            {
                var result = await client.PostAsJsonAsync("https://fcm.googleapis.com/fcm/send", payload);
                await File.WriteAllTextAsync(Path.Combine(Directory.GetCurrentDirectory(), "Response.txt"), result.ToString());
            }
            catch (Exception e)
            {
                await File.WriteAllTextAsync(Path.Combine(Directory.GetCurrentDirectory(), "Error.txt"), e.ToString());
            }
        }
}`

**Comment by wfurt** [comment]
Can you reproduce it with simple HttpClient? The fragment you post it still does not give me a way to run it. You should also verify that you do get data back from the server. (if not, the exception would be legitimate)

**Comment by lostmagicK** [comment]
Okay ill do that

**Comment by lostmagicK** [comment]
It seems problem is with https sites only.. posting to regular http works fine.. I think problem is with .net core only..

**Comment by lostmagicK** [comment]
> Can you reproduce it with simple HttpClient? The fragment you post it still does not give me a way to run it. You should also verify that you do get data back from the server. (if not, the exception would be legitimate)

You can try posting to any https enabled api it always fails..

**Comment by karelz** [comment]
Triage: @lostmagicK can you please post a repro we can try locally? (with Main method, ideally minimal)

**Comment by lostmagicK** [comment]
I got the issue solved.. Problem was not with httpClient it was with server.. Server was not able access the link to fcm url.. so i asked server people to fix it.. But Error thrown was misleading..
