### ISSUE TITLE
RuntimeFlavor is not consistently set to CoreCLR and Mono

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32884]
The MSBuild property `$(RuntimeFlavor)` is not consistently set to known values. When building Mono it is consistently set to `'Mono'`. When building CoreCLR though it will be set to `'CoreCLR`' when building via some of our YML files but not all. It's also not obviously set to `'CoreCLR'` when building locally.

This should be consistently set so our build files can be written consistently.

**Comment by ViktorHofer** [comment]
This is fixed: https://github.com/dotnet/runtime/blob/56b696403b3f8fe6dac4a83f4d0743490e0e9ad2/eng/Subsets.props#L51-L53
