### ISSUE TITLE
Directly appending buffer segments for a zero-copy PipeWriter

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32894]
This API would allow a user to insert their own buffer into a PipeWriter's stream.

This allows a PipeWriter to be truly zero-copy for such a scenario, while currently they must copy their buffer into the PipeWriter's internal buffer. An example might be a block of pre-serialized data that a user might reuse throughout a stream's lifetime. The transport implementation could then take the resulting sequence of the PipeWriter's own buffers and the user's buffers and perform a gathered write to the socket.

```c#
class PipeWriter
{
    // Allocate a reusable block that is guaranteed to be zero-copy if passed to AppendBuffer().
    public virtual IMemoryOwner<byte> GetReusableMemory(int length);

    // If the buffer is compatible with the pipe writer's needs, use the buffer directly. Otherwise, do an implicit GetSpan()+Copy()+Advance().
    // ValueTask completes once the buffer is no longer in use by the PipeWriter.
    // Unlike WriteAsync, does not flush.
    public virtual ValueTask AppendBufferAsync(ReadOnlyMemory<byte> buffer);
}
```

**Comment by davidfowl** [comment]
I'm not sure this can be implemented on the abstract class. What would it do by default? (I'm assuming these are virtual).

**Comment by scalablecory** [comment]
> I'm not sure this can be implemented on the abstract class. What would it do by default? (I'm assuming these are virtual).

Yes, they're virtual -- missed that. Default implementation can just call GetSpan()+Copy()+Advance().

**Comment by Drawaes** [comment]
This has been an oft requested feature (from all the way back when it worked in the corefxlab version)

#25848 is one request. @benaadams and I may have got some changes into owned memory that lets you tell the pool it came from as well so that you can ensure its the same pool as the pipeline you are trying to append to.

**Comment by scalablecory** [comment]
> @benaadams and I may have got some changes into owned memory that lets you tell the pool it came from as well so that you can ensure its the same pool as the pipeline you are trying to append to.

Yes, this is currently possible via `MemoryMarshal.TryGetMemoryManager()` and would be used to implement the "otherwise" path.

**Comment by BrennanConroy** [comment]
Closing to track with https://github.com/dotnet/runtime/issues/25848
