### ISSUE TITLE
Mono runtime missing several InteropServices.WindowsRuntime types

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32898]
The Mono version of System.Private.Corelib is missing a few types that are necessary to satisfy our GenFacades analysis:

- `System.Runtime.InteropServices.WindowsRuntime.DefaultInterfaceAttribute`
- `System.Runtime.InteropServices.WindowsRuntime.IActivationFactory`
- `System.Runtime.InteropServices.WindowsRuntime.InterfaceImplementedInVersionAttribute`
- `System.Runtime.InteropServices.WindowsRuntime.ReadOnlyArrayAttribute`
- `System.Runtime.InteropServices.WindowsRuntime.ReturnValueNameAttribute`
- `System.Runtime.InteropServices.WindowsRuntime.WriteOnlyArrayAttribute`

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT since this is about WinRT types in .NET

**Comment by jaredpar** [comment]
Note: this issue won't make sense until #32881 is merged as this is where the suppressions are added

**Comment by CoffeeFlux** [comment]
Looks like this was fixed by https://github.com/dotnet/runtime/pull/32905; closing.
