### ISSUE TITLE
dotnet-xtd exception at Regex Match

### ISSUE THREAD

**Issue by DotNetAppCompatFeiWang** [dotnet/runtime#32913]
Application Name: dotnet-xtd
OS: Windows 10 RS5
CPU: X64
.NET Build Number: 5.0.100-preview.1.20125.9
App Location:
App Source on GitHub link  : https://github.com/nil4/dotnet-transform-xdt

Verify Scenarios: 

1). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.1.20125.9: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build :  3.1.101   Pass

Repro Machine could be found at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1074633

Repo Machine Environment Info :

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20125.9
 Commit:    12e88ed2e5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20125.9\

Host (useful for support):
  Version: 5.0.0-preview.1.20120.5
  Commit:  3c523a6a7a

.NET Core SDKs installed:
  5.0.100-preview.1.20125.9 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.1.20122.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Repro steps:

On the repo machine 

1) On cmd, install app by : “dotnet tool install -g dotnet-xdt” (On repo machine, it is already installed ) 
2) On Cmd, go to this directory:   C:\Repro\dotnet-xtd
3) Run this command : 
dotnet-xdt --source AttributeFormatting_source.xml --transform AttributeFormatting_transform.xml --output AttributeFormatting_baseline.xml --verbose

Expected Result:

It should execute without error

Actual Result:

It gets exceptions

Findings :

After debugging the source code, we found out that in .net core5, regex expression Match method returns different values ,it causes app to fail 

Sample Code :

using System.Text.RegularExpressions;

string pattern = @"\A\s*(?<name>\w+)(\s*\((?<arguments>.*)\))?\s*\Z";
string input = "Match(Name)";
Regex myreg = new Regex(pattern, RegexOptions.Compiled | RegexOptions.Singleline);
System.Text.RegularExpressions.Match match = myreg.Match(input);
Console.WriteLine(match.Success); //return true in 3.1, false in 5.0, same code returns true in .net framework 4.7.2

@dotnet-actwx-bot  FYI

**Comment by danmosemsft** [comment]
@stephentoub

**Comment by stephentoub** [comment]
I'll take a look.

**Comment by stephentoub** [comment]
Is the repro code correct?  I copy/pasted it into an app:
```C#
using System;
using System.Text.RegularExpressions;

class Program
{
    static void Main(string[] args)
    {
        string pattern = @"\A\s*(?\w+)(\s*((?.)))?\s\Z";
        string input = "Match(Name)";
        Regex myreg = new Regex(pattern, RegexOptions.Compiled | RegexOptions.Singleline);
        Match match = myreg.Match(input);
        Console.WriteLine(match.Success); //return true in 3.1, false in 5.0, same code returns true in .net 
    }
}
```
On both .NET Core 3.1 and .NET 5, I get an exception:
```
Unhandled exception. System.Text.RegularExpressions.RegexParseException: Invalid pattern '\A\s*(?\w+)(\s*((?.)))?\s\Z' at offset 8. Unrecognized grouping construct.
   at System.Text.RegularExpressions.RegexParser.ScanGroupOpen()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
```
Similarly on .NET Core 2.1 and .NET Framework 4.8, just with a slightly different exception:
```
Unhandled Exception: System.ArgumentException: parsing '\A\s*(?\w+)(\s*((?.)))?\s\Z' - Unrecognized grouping construct.
   at System.Text.RegularExpressions.RegexParser.ScanGroupOpen()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
```

What is the correct repro?

**Comment by stephentoub** [comment]
I found the original expression used from the cited repo... it's a bit different than what's in the repro above:
```C#
@"\A\s*(?<name>\w+)(\s*\((?<arguments>.*)\))?\s*\Z"
```

**Comment by stephentoub** [comment]
This is caused by the "Optimize .* in Singleline mode" change in https://github.com/dotnet/runtime/commit/839dd69a25607070d530e785a74bc127999b38fb.

**Comment by stephentoub** [comment]
Simple fix in https://github.com/dotnet/runtime/pull/32930; we weren't initializing a value to 0.
