### ISSUE TITLE
Need argument to specify libraries runtime

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32918]
Once #32881 is merged it will be possible to build libraries against CoreCLR or Mono yet there is no build argument to specify which. Instead developers must specify MSBuild variables on the command line in order to pick Mono. 

```
.\build.cmd -subsetCategory libraries /p:RuntimeFlavor=Mono
```

Given this is a supported scenario we should have a supported argument here called `runtimeFlavor`. That should allow both Mono and CoreCLR arguments. 

Note: we should also consider supporting abbreviations for these arguments. Example:

```
.\build.cmd -subsetCategory libraries -runtimeFlavor Mono 
vs. 
.\build.cmd -sc libraries -rf mono
```

**Comment by ViktorHofer** [comment]
The RuntimeFlavor doesn't need to specified on mobile targets as its inferred. For desktop configuration the msbuild `RuntimeFlavor` should be sufficient. Hence I don't think we need a build argument mapping for that variable.

Closing. Feel free to reopen if you disagree.
