### ISSUE TITLE
GetAsyncStateMachineDescription may change behavior on app processed by ILLink

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#32921]
The code in [`AsyncMethodBuilderCore.GetAsyncStateMachineDescription`](https://github.com/dotnet/runtime/blob/5468699715d37d738f881da6050552c77a4caa82/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs#L95) enumerates all fields on the state machine type and prints out their values into the resulting string.

If a field is not accessed by anything in the application directly, the linker will remove it from the type (with exceptions to non-auto layout types and some special cases). So the enumeration of all fields on a type may return less fields when the app is processed with the linker.

Please review this and determine if the behavior is acceptable or if we should try to find a solution such that we would guarantee that all fields are preserved in this case.

**Comment by vitek-karas** [comment]
@eerhardt

**Comment by stephentoub** [comment]
> Please review this and determine if the behavior is acceptable or if we should try to find a solution such that we would guarantee that all fields are preserved in this case.

It's acceptable.  This is used to get a description of the state of the state machine when an async method doesn't complete / hangs and gets GC'd in that state; we output an EventSource event to help the dev track down their bug, and we include in it the state of the state machine as best we can gather it.  It's best effort, and if there's something on the state machine that's never touched such that the linker removes it, it's also not going to be meaningful in tracking down the actual problem.

**Comment by stephentoub** [comment]
As an aside, is the linker actually able to remove fields from async state machines?  That surprises me.  I would have expected anything the linker could possibly remove wouldn't have been promoted from locals to fields in the first place by Roslyn.

**Comment by vitek-karas** [comment]
You're probably right - I didn't actually try to see if there's a counter example.

I based the description above on analyzing the code looking for reflection calls which may provide different results on trimmed assemblies. Unless I'm pretty certain I'm trying to avoid definitive statements about the code's behavior as I don't understand the affected area that well.

**Comment by eerhardt** [comment]
I think we can close this issue, right? From @stephentoub's analysis above, the only usage of this method is:

https://github.com/dotnet/runtime/blob/84cf6a19356d7574664ce08251815ddd4e3d2964/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs#L262-L271

And the points that:
1. Fields on the async state machine shouldn't be able to be trimmed.
2. Even if they are trimmed, this won't affect the runtime of an application. Those fields just won't be written to the EventSource. If the fields were trimmed away, this seems totally reasonable.

**Comment by stephentoub** [comment]
Yup. The only question is if we need to attribute the method in some way to keep it off tooling radar in the future, and if so, how.

**Comment by vitek-karas** [comment]
Thanks a lot for the confirmation. Can we please keep this open a bit longer - we're currently figuring out the best way to tell the tooling that it should not warn about some code.

**Comment by stephentoub** [comment]
> we're currently figuring out the best way to tell the tooling that it should not warn about some code.

There are now multiple issues in the same state, right? This, the delegate one, etc. Seems like they should all be closed in favor of an issue specifically about annotating all such methods, rather than multiple issues tracking e same thing. Up to you, though.

**Comment by vitek-karas** [comment]
The delegate issue is somewhat different.
Is it a problem to have several issues opened as a way to track this work?
