### ISSUE TITLE
[System.Net.Security] Potential bug in SslStream.Implementation.cs

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#32920]
Discovered while annotating the library #32541.

It looks like the `lazyResult` value will never get initialized in this [snippet](https://github.com/dotnet/runtime/blob/d76ef042f8ead9d06a447ab2b1004ae626185ca2/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L429-L443). Similarly [here](https://github.com/dotnet/runtime/blob/d76ef042f8ead9d06a447ab2b1004ae626185ca2/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L510-L524).

**Comment by stephentoub** [comment]
I believe @wfurt is already aware of this and working in it.

**Comment by wfurt** [comment]
I'm running final benchmarks and stress on possible fix.  It should be ready today or tomorrow.
