### ISSUE TITLE
Environment.UserInteractive can be unexpectedly false

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#32929]
https://github.com/dotnet/wpf/issues/2663

This is preventing Winforms and WPF popping some dialogs.

Caused by https://github.com/dotnet/runtime/pull/1234   c6ec170197f42ce5ce21ceca27e89af6f1e6030

Since I copied the implementation from .NET Framework, it's surprising there's a problem. Needs investigation.

**Comment by DotNetAppCompatFeiWang** [comment]
@dotnet-actwx-bot  FYI since we will track the bug in this new issue in dotnet/runtime

**Comment by jkotas** [comment]
Fixed by #32947
