### ISSUE TITLE
System.GC.HeapCount not recognised when set via runtimeconfig.json

### ISSUE THREAD

**Issue by MendelMonteiro** [dotnet/runtime#32956]
I've written a very simple .net core 3.1 application and tried to set the GC heap count using either the environment variable or the `runtimeconfig.json` file and have found that it only works when it is set via the environment variable.  I checked that the heaps were created by verifying the number of GC Server threads created (inspecting a dump or using perfview).

Other settings such as `System.GC.Server` work correctly in both configuration modes.

The `runtimeconfig.json` used is as follows:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.GC.Server": true,
      "System.GC.HeapCount": 2
    }
  }
}
```

**Comment by Maoni0** [comment]
yeh, this should definitely be fixed. this doesn't work today due to [this bug](https://github.com/dotnet/runtime/issues/12948) which @cshung is looking at.
