### ISSUE TITLE
AzDO losing connection to build agents

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32964]
Build jobs are failing with the following message

> We stopped hearing from agent NetCorePublic-Pool 93. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

Impact over last 100 builds

|Build|Kind|Timeline Record|
|---|---|---|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Run  Windows_NT x64 checked|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Run  Linux x64 checked|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|Test crossgen-comparison Linux arm checked|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Build Linux x64 checked|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Run  Windows_NT x86 checked|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|Installer Build and Test Linux_arm64 Debug|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|Installer Build and Test Linux_musl_x64 Debug|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|Libraries Test Build Linux x64 Debug|
|[540296](https://dev.azure.com/dnceng/public/_build/results?buildId=540296)|PR https://github.com/dotnet/runtime/pull/32858|Installer Build and Test Linux_arm Debug|
|[540293](https://dev.azure.com/dnceng/public/_build/results?buildId=540293)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Build Linux x64 checked|
|[540293](https://dev.azure.com/dnceng/public/_build/results?buildId=540293)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Run  Windows_NT x64 checked|
|[540293](https://dev.azure.com/dnceng/public/_build/results?buildId=540293)|PR https://github.com/dotnet/runtime/pull/32858|CoreCLR Pri0 Test Run  Windows_NT x86 checked|
|[540293](https://dev.azure.com/dnceng/public/_build/results?buildId=540293)|PR https://github.com/dotnet/runtime/pull/32858|Libraries Test Build Linux x64 Debug|
|[540293](https://dev.azure.com/dnceng/public/_build/results?buildId=540293)|PR https://github.com/dotnet/runtime/pull/32858|Installer Build and Test Linux_arm Debug|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|CoreCLR Pri0 Test Run  Linux arm64 checked|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|Libraries Test Run release coreclr Linux x64 Release|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|Libraries Test Run release mono Linux x64 Release|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|Libraries Test Run release coreclr Linux arm Release|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|Libraries Test Run release coreclr Linux_musl x64 Release|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|CoreCLR Pri0 Test Run  Linux arm checked|
|[540233](https://dev.azure.com/dnceng/public/_build/results?buildId=540233)|Rolling|Installer Build and Test Linux_arm Release|

**Comment by jaredpar** [comment]
This is also blocking the outerloop builds. Here is the data from the coreclr loop

|Build|Kind|Timeline Record|
|---|---|---|
|[540410](https://dev.azure.com/dnceng/public/_build/results?buildId=540410)|Rolling|CoreCLR Product Build Linux_musl x64 checked|
|[540410](https://dev.azure.com/dnceng/public/_build/results?buildId=540410)|Rolling|Libraries Build Linux arm Release|
|[540410](https://dev.azure.com/dnceng/public/_build/results?buildId=540410)|Rolling|CoreCLR Pri1 Test Build Linux arm64 checked|

Evaluated 10 builds
Impacted 1 bulids
Impacted 3 jobs

**Comment by jkotas** [comment]
Service Bus outage causing the Helix client to fail renewing the lock on a work item
