### ISSUE TITLE
double with value 0 ToString() can return "-0"

### ISSUE THREAD

**Issue by tl-cristian-bordean** [dotnet/runtime#32975]
# Issue Title

double with the value 0 ToString() can return "-0"

# General

If you have a variable of type double with the value 0, multiply it by -1 and do a ToString on the result you will get "-0".

`var val = 0d
val *= -1;

var result = val.ToString()`

// result = "-0";

The issue only seems to occur with variables of type double and doesn't occurs on the latest version of .Net Framework.

**Comment by scalablecory** [comment]
Duplicate of #32237
