### ISSUE TITLE
dotnet-runtime-deps deb package needs updating for libicu version included in Focal

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#32971]
Ubuntu Focal which is in preview recently updated to a newer version of libicu - libicu65.  The dotnet-runtime-deps deb package needs to be updated appropriately so that the libicu dependency is correctly met/installed.

https://github.com/dotnet/runtime/blob/b2ad762793b9f74cb65f02687f0fa6b8c09c68e3/src/installer/pkg/packaging/deb/package.targets#L321

**Comment by dagood** [comment]
Related request from users: https://github.com/dotnet/core/issues/4360. We need to make this change in `master` and for all versions in support (3.1, 2.1).

/cc @NikolaMilosavljevic @nakarnam @leecow

**Comment by mthalman** [comment]
libicu65 is now obsolete.  The new version on the Focal feed is libicu66.

**Comment by NikolaMilosavljevic** [comment]
Should we wait for Focal Beta freeze (4/2) before making new change in libicu dependency? https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule

@mthalman is this a blocking issue?

**Comment by mthalman** [comment]
@NikolaMilosavljevic - It's not blocking Docker since we install the dependencies explicitly ourselves.

But it's a blocker in the sense that .NET Core won't be able to be installed on Focal until support is added for libicu66 because libicu65 is no longer available in the feed.

**Comment by NikolaMilosavljevic** [comment]
@leecow how do we want to manage this change in dependency for Ubuntu Focal? We have 2 pending PRs for updating the dependency to libicu65 (that is now missing) for 2.1 and 3.1 releases. We originally wanted to ship those in April. But, it seems that we need a new plan. It's also good that I held of on those PRs - I'm going to update them with libicu66 change.

**Comment by dagood** [comment]
We need the change in dotnet/runtime too, new PR since https://github.com/dotnet/runtime/pull/33455 was merged.

**Comment by NikolaMilosavljevic** [comment]
Yeah, working on 5.0 change now.

**Comment by leecow** [comment]
Get things queued up and we can get them in for 3.1.4/2.1.18. Should be open for check-in tomorrow.

**Comment by NikolaMilosavljevic** [comment]
> Get things queued up and we can get them in for 3.1.4/2.1.18. Should be open for check-in tomorrow.

3.1 PR was merged into release/3.1 branch yesterday by @Anipik , 2.1 PR is still pending - @leecow , are we good to merge that one now?

**Comment by NikolaMilosavljevic** [comment]
All PRs were merged, closing the issue.

**Comment by dagood** [comment]
We still need https://github.com/dotnet/runtime/pull/34079 though, right?
