### ISSUE TITLE
Disable targeting pack build during source-build: avoid incomplete platform manifest

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#32982]
See https://github.com/dotnet/runtime/issues/1622 for the reason why the targeting pack is incomplete, and a plan to make it complete.

If that's not addressed by 5.0, we should disable targeting pack generation during source-build. This allows source-build to decompile the targeting pack (as usual) and use it as the 5.0.0 targeting pack. If we don't disable it, we risk having dotnet/runtime building an incomplete 5.0.0 targeting pack that ends up in the source-built .NET Core SDK.

The overall effort to create targeting packs "properly" in the dotnet/runtime repo is tracked by https://github.com/dotnet/source-build/issues/1523.

**Comment by NikolaMilosavljevic** [comment]
There's a patch in source-build that could be incorporated in runtime repo.
