### ISSUE TITLE
Opening repo in VS Code reports modified files under Mono

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#32980]
Repro steps:

- Clone dotnet/runtime in Linux 
- Open VS Code on Windows
- Use Remote-SSH to open the dotnet/runtime enlistment on Linux

My expectation here would be that no files are different. Yet appears that several Mono files are listed as modified. The modification appears to be line entry issues and is visible both in VS Code and locally on the box. 

![image](https://user-images.githubusercontent.com/146967/75584411-8aaae700-5a24-11ea-9310-3ca1e692071b.png)

**Comment by BruceForstall** [comment]
Related? https://github.com/dotnet/runtime/issues/2222

**Comment by jaredpar** [comment]
@BruceForstall yes this is a dupe of #2222
