### ISSUE TITLE
Guidance around the dotnet-coreclr nuget feed

### ISSUE THREAD

**Issue by mletterle** [dotnet/runtime#32996]
What is the status of packages listed in https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json ? Are they ever going to be published to nuget.org? I'm specifically thinking of the IL Tools, but I'm sure there's others.

In the case of the IL Tools, nuget.org's versions stop at 2.0.8, whereas the dotnetfeed has many more versions.

Is this a feed that can be relied on? And if so, should it have a gallery? 

It doesn't help that static sleet feeds don't support search or pagination...

**Comment by jkotas** [comment]
https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json feed is for nightly builds and experimental packages. The packages have varying quality and are not officially supported.

@tannergooding Do you happen to remember why we are not publishing IL.SDK to nuget.org?

Duplicate / related to https://github.com/dotnet/runtime/issues/11411

**Comment by BruceForstall** [comment]
@tannergooding @jkotas any ideas here?

**Comment by tannergooding** [comment]
I don't think we ever made an official decision to productize it or not and believe there was some pending work items that would have been needed to make it more generally useable. I don't know if that ever happened or if it is still a goal to make them happen.

**Comment by BruceForstall** [comment]
AFAIK, the IL tools SDK is available on nuget.org for .NET 5.0 (e.g., https://www.nuget.org/packages/Microsoft.NET.Sdk.IL/), so this issue is resolved.
