### ISSUE TITLE
Exception.Data dictionary is not passed to catch block in dotnet core 3.1

### ISSUE THREAD

**Issue by einaradolfsen** [dotnet/runtime#32993]
# Issue Title
Exception.Data dictionary is not passed to catch block in dotnet core 3.1

# General
In my service layer I throw a HttpRequestException and set a origin key to a service name string.
IErrorOriginEnum origin = structure.OriginType;  //origin
ex.Data.Add("origin", origin);
trow ex;
Inspecting the ex instance at this point shows one Data dictionary entry key origin with its value

In the catch block on the controller however, the Dictionary is now empty
catch(Exception ex){... //ex.Data does not have any entries}

This used to work just fine in dotnet core 2.1

**Comment by karelz** [comment]
Not enough info, closing. Feel free to reopen if there is more information available. Thanks!
