### ISSUE TITLE
String literal escaping

### ISSUE THREAD

**Issue by cup** [dotnet/runtime#33007]
C# can print a string:

~~~cs
using System;
class Program {
   static void Main() {
      string s1 = "Sunday";
      Console.WriteLine(s1);
   }
}
~~~

but it seems to have no way to print a string representation, that is to say
`"Sunday"` instead of `Sunday`. Other languages can do this, like Rust:

~~~rust
fn main() {
   let s1 = "Sunday";
   println!("{:?}", s1);
}
~~~

C++:

~~~cpp
#include <iomanip>
#include <iostream>
main() {
   std::string s1 = "Sunday";
   std::cout << std::quoted(s1) << std::endl;
}
~~~

Go:

~~~go
package main
import "fmt"
func main() {
   s1 := "Sunday"
   fmt.Printf("%q\n", s1)
}
~~~

Ocaml:

~~~ml
open Printf;;
let s1 = "Sunday";;
printf "%S\n" s1;;
~~~

Nim:

~~~nim
import strutils
var s1 = "Sunday"
echo s1.escape
~~~

**Comment by benaadams** [comment]
Escape the quotes? `\n`
```csharp
string s1 = "\"Sunday\"";
Console.WriteLine(s1);
```
Interpolated string `$` with escaped quotes `\"`
```csharp
string s1 = "Sunday";
Console.WriteLine($"\"{s1}\"");
```
Verbatim interpolated string `@$` with escaped quotes `""`
```csharp
string s1 = "Sunday";
Console.WriteLine(@$"""{s1}""");
```

**Comment by cup** [comment]
@benaadams sorry I wasnt clear

the issue is not "how do I include a literal double quote in a string

the issue is, given an arbitrary string that might contain embedded quote
characters, or other pathological characters including but not limited to:

- Spaces
- Tabs
- Newlines

How can one print the representation of said string. All the examples I gave do
this. So given the input `string s1 = "Sunday"` or similar, the literal string
`"Sunday"` is printed rather than `Sunday`.

**Comment by davidfowl** [comment]
You're looking for the equivalent of https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.escape?view=netcore-3.1 but for strings yes? `String.Escape`

**Comment by cup** [comment]
@davidfowl thats correct, but it seems `String.Escape` is not a currently existing method

**Comment by davidfowl** [comment]
Sounds like an API suggestion 😄

**Comment by danmosemsft** [comment]
What is the value of this - why do these other platforms offer it?

**Comment by danmosemsft** [comment]
Oh, it seems intended for serializers.

https://en.cppreference.com/w/cpp/io/manip/quoted

**Comment by cup** [comment]
@danmosemsft as an example, say you have a program like this:

~~~cs
using System;
class Program {
   static void Main() {
      string s1 = "Sunday ";
      Console.WriteLine(s1);
   }
}
~~~

That final space wont be easily identifiable. You might counter with, "well
just do this":

~~~cs
Console.WriteLine("[" + s1 + "]");
~~~

but as I alluded to previously, this will fail as string can in general contain
any arbitrary character, including any character that you might choose to use
as a delimiter, making the above suggestion ambiguous should the delimiter
collide with a character in the source string. Other languages allow to print
a clear representation, regardless of any embedded characters. Here is an only
slighty pathalogical example with Go:

~~~go
package main
import "fmt"
func main() {
   s1 := "Sun \" Mon [ Tue ] Wed "
   fmt.Printf("%q\n", s1) // "Sun \" Mon [ Tue ] Wed "
}
~~~

**Comment by GrabYourPitchforks** [comment]
.NET doesn't expose a general-purpose "escape this string" API because it would be ambiguous as to what you mean. Are you looking for C#, C++, VB, F#, something else? (Remember: .NET isn't a specific language. It's a runtime.)

If you're looking for something that performs C#-style escaping specifically, check out the `CSharpCodeProvider` type and the `CodePrimitiveExpression` type. In fact, [a bug was recently fixed](https://github.com/dotnet/runtime/pull/1853) in this very code, and the unit test updates should provide a good sample for how to use the APIs.

**Comment by svick** [comment]
Another option would be to use the other C# compiler API: Roslyn.

For example, consider the following code:

```c#
using System;
using Microsoft.CodeAnalysis.CSharp;

class Program
{
    static void Main()
    {
        Console.WriteLine(SymbolDisplay.FormatLiteral(
            "Some special characters: \u0009\u000A\u0041\u0085", quote: true));
    }
}
```

It prints:

```
"Some special characters: \t\nA\u0085"
```

While Roslyn is more heavy-weight than CodeDOM (suggested by @GrabYourPitchforks above), I think it's more likely to be bug-free and up-to-date, since it's the actual code of the C# compiler.

**Comment by cup** [comment]
@svick thanks, that is exactly what I am looking for. Using this file:

~~~cs
using Microsoft.CodeAnalysis.CSharp;
using System;
class Program {
   static void Main() {
      string s1 = SymbolDisplay.FormatLiteral("Sunday", quote: true);
      Console.WriteLine(s1);      
   }
}
~~~

I can compile like this:

~~~
tools/csc /r:tools/Microsoft.CodeAnalysis.CSharp.dll \
/r:C:/Windows/Microsoft.NET/Framework64/v4.0.30319/netstandard.dll a.cs
~~~

whats interesting is the resultant file requires these to be in the same
directory:

~~~
Microsoft.CodeAnalysis.dll
Microsoft.CodeAnalysis.CSharp.dll
~~~

even just having them in the PATH doesnt seem to do it.
