### ISSUE TITLE
Is that any best way to call async function in a sync function

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/runtime#33023]
In asp.net core is that any best way to call async function in a sync function,and get the result
1. someasync.Result?
2.someasync.RunSynchronously()  someasync.Result?
3.someasync.GetAwaiter().GetResult()???
or other way?

**Comment by slang25** [comment]
A good resource on this topic is here:
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait

In short, there is no good way to do it. `.GetAwaiter().GetResult()` will give you the actual exception if there is one, whereas `.Result()` will wrap it in an AggregateException, so is slightly preferable, but is still bad.

**Comment by kugarliyifan** [comment]
> A good resource on this topic is here:
> https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait
> 
> In short, there is no good way to do it. `.GetAwaiter().GetResult()` will give you the actual exception if there is one, whereas `.Result` will wrap it in an `AggregateException`, so `.GetAwaiter().GetResult()` is ever so slightly preferable, but is still problematic and to be avoided if possible.



thk!!!
