### ISSUE TITLE
Question about the future of nullable types

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/runtime#33027]
In a future version - let’s say .NET 6, would you consider making a breaking change in the CLR to redo nullable types and to make it a first class runtime feature?

What would that take? I guess adding fields to the metadata and runtime checks. Simplified, of course.

Updating the compilers, obviously.

Could you even preserve backwards compatibility with .NET 5 somehow?

**Comment by jkotas** [comment]
We have pretty high bar for breaking changes. Incrementally updating the existing design in non-breaking way is fine, but large scale breaking changes would not be acceptable.

If we believed that the right way to do nullable types is by making them a first class runtime feature, we would do it that way in the first place. The chance of that happening now is close to zero.
