### ISSUE TITLE
README doesn't differ per release branch

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#3302]
I went to https://github.com/dotnet/core-setup/tree/release/2.1

I expected .NET Core 2.1 download links. I saw .NET Core 2.0 links.

I went to https://github.com/dotnet/core-setup/tree/release/2.2

I expected .NET Core 2.2 download links. I saw .NET Core 2.0 links.

The release pages used to differ by branch. Did I miss something?

**Comment by NikolaMilosavljevic** [comment]
Low benefit - closing.
