### ISSUE TITLE
[API Proposal]: Add extension method AsReadOnly() for IDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by Mrxx99** [dotnet/runtime#33033]
## Background and motivation

Like the `List<T>` has a method `AsReadOnly()` I would like to propose the same for the Dictionary.
This could lead to more clean and fluent code, when you can call AsReadOnly at the end of a call chain instead of creating a new instance of ReadOnlyDictionary manually.

I am aware that Dictionary already implements IReadOnlyDictionary but only using the ReadOnlyDictionary it is really immutable without the possibility to cast it back to (I)Dictionary.

## API Proposal
```diff
namespace System.Collections.Generic
{
    public static class CollectionExtensions
    {
+       public static ReadOnlyDictionary<TKey, TValue> AsReadOnly(this IDictionary<TKey, TValue> dictionary)
+            => new ReadOnlyDictionary<TKey, TValue>(dictionary);
    }
}
```

## API Usage
```C#
private Dictionary<string, string> _theDictionary = new Dictionary<string, string>();

public IReadOnlyDictionary<string, string> TheDictionary => _theDictionary.AsReadOnly();
```     

## Alternative Designs

The origianl proposal (as can be read in the comments, an extension method is preferred):
```diff
public class Dictionary<TKey, TValue> : IDictionary<TKey, TValue>, IDictionary...
{
+        public ReadOnlyDictionary<TKey, TValue> AsReadOnly()
+            => new ReadOnlyDictionary<TKey, TValue>(this);
}
```

## Risks

I don't see any it's just one extension method more calling a very common constructor.

**Comment by DevDrake** [comment]
I was scratching my head thinking about this proposal. 
If we need the functionality i would be more opt to extension function or default interface implementation for `IDictionary<,>`
`public ReadOnlyDictionary<TKey, TValue> AsReadOnly(this IDictionary<TKey, TValue> dictionary) => new ReadOnlyDictionary<TKey, TValue>(dictionary)`
as this will cover more than just Dictionary. 
also this is already used in  runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataServices.cs for example.
I'm not very convinced we need it at all.
IMHO we should go more in the #31573 direction

**Comment by eiriktsarpalis** [comment]
We'd probably want to express this as an extension method due to codegen size concerns. How about this?

```diff
namespace System.Collections.Generic
{
    public static class CollectionExtensions
    {
+       public static ReadOnlyDictionary<TKey, TValue> AsReadOnly(this IDictionary<TKey, TValue> dictionary)
+            => new ReadOnlyDictionary<TKey, TValue>(dictionary);
    }
}
```

cc @jkotas @GrabYourPitchforks

**Comment by Mrxx99** [comment]
I agree, I think it does make more sense as extension method.

**Comment by mattjohnsonpint** [comment]
Is this API still up for consideration?

**Comment by eiriktsarpalis** [comment]
It is, but we're not prioritizing it for .NET 6.

**Comment by terrajobst** [comment]
* This makes sense, but it seems we should be consistent and offer one for `ReadOnlyCollection<T>`, which today only exists as instance methods on `List<T>` and `Array`.

```C#
namespace System.Collections.Generic
{
    public static class CollectionExtensions
    {
        public static ReadOnlyCollection<T> AsReadOnly<T>(this IList<T> list);
        public static ReadOnlyDictionary<TKey, TValue> AsReadOnly<TKey, TValue>(this IDictionary<TKey, TValue> dictionary);
    }
}
```

**Comment by eiriktsarpalis** [comment]
@Mrxx99 would you be interested in providing an implementation?

**Comment by Mrxx99** [comment]
@eiriktsarpalis Yes, I would be interested. Also thanks for moving this issue forward. Should I also update the proposal to also include the extension method on IList<T>?

**Comment by eiriktsarpalis** [comment]
> Should I also update the proposal to also include the extension method on IList?

No that's fine, we use https://github.com/dotnet/runtime/issues/33033#issuecomment-958004623 as the source of truth.
