### ISSUE TITLE
After migration to .Net Core 3.1 for a given Cancellation Request test case ReadAsStringAsync() throws System.IO.IOException with message 'Error while copying content to a stream'

### ISSUE THREAD

**Issue by jelovacsoley** [dotnet/runtime#33038]
After migrating my solution from 2.2 to 3.1 I ended with a single test failing.

Test:
```C#
[Fact]
public async Task RequestCancellation_Test()
{
     // Setup  
     ...  

     var cancellationSource = new CancellationTokenSource();

     var requestTask = Client.PostItemAsync(uri, data, cancellationSource.Token)
                .EnsureSuccessStatusCodeWithMessage();

     await Task.Delay(TimeSpan.FromMilliseconds(10));
            cancellationSource.Cancel();

      var exception = await Assert.ThrowsAsync<HttpRequestException> (() => requestTask);
      Assert.Equal("StatusCode: BadRequest", exception.Message);
}
```
`EnsureSuccessStatusCodeWithMessage` is extension method where I use `ReadAsStringAsync`:

``` C#
public static async ValueTask<HttpResponseMessage> EnsureSuccessStatusCodeWithMessage(this HttpResponseMessage response)
{
     if (!response.IsSuccessStatusCode)
     {
          var errorMessage = response.Content == null ? null : await 
                          response.Content.ReadAsStringAsync();

          if (string.IsNullOrEmpty(errorMessage))
          {
                errorMessage = $"StatusCode: {response.StatusCode}";
          }

           // Make sure to actually dispose the response.T
           response.Dispose();

           throw new HttpRequestException(errorMessage);
      }

      return response;
}
```
the `response.Content.ReadAsStringAsync();` throws `System.IO.IOException` with message `Error while copying content to a stream`

Btw, if I leave the request to finish (remove the cancellation part), I don't have issues with `ReadAsStringAsync()`

In the test I expect the error message to be empty and end up with `"StatusCode: BadRequest"`,
`ReadAsStringAsync` was returning empty string while I was at .Net Core 2.2 
`ReadAsStringAsync`  was coming from:
`Assembly netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`
now on Net Core 3.1 it comes from:
`Assembly System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`

**Comment by karelz** [comment]
@jelovacsoley any chance to get a repro?

**Comment by jelovacsoley** [comment]
@karelz Unfortunately I was not able to create a simple repro for this issue. However I might try dissect a little bit more in the near future as this issue was not a show stopper. Once I have something I'll let you know. 
Thanks for the feedback and support

**Comment by karelz** [comment]
Looks like it is not actionable, closing for now.
Feel free to reopen once there is actionable info available. Thanks!
