### ISSUE TITLE
Can't resolve dependencies in published .net core applications

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/runtime#33040]
Recently I have a very weird behavior of the .net core runtime and I have absolutely no idea what I could do about it.
I publish an application:

> dotnet publish /p:Configuration=Debug  /p:PublishDir=%ShareToolsDirectory%\%CurDir%\

When I try to start it, it can't resolve any of the references that are published together with the appliciation

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Siemens.Collaboration.Net.Logging, Version=1.0.58291.446, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Siemens.Collaboration.Net.Logging, Version=1.0.58291.446, Culture=neutral, PublicKeyToken=null'
   at Siemens.Collaboration.Net.Tools.FileSystemLinkTool.Program.Main()

I checked with DotPeek whether the versions and public key tokens of the assemblies that are located in the app folder match with the requested one. But everything seems to be fine. Only workaround that I have at the moment is to setup a custom assembly resolution in the main before I do anything else. With that assembly resolution I simply force the app to load the assemblies that are located in its folder.

Does anybody have an idea how this behavior can appear?

**Comment by elinor-fung** [comment]
I assume the assemblies being loaded are dependencies that are intentionally not in your .deps.json? (e.g. set to not copy local / Private=false or not explicitly in project's chain of references)

.NET Core does not automatically load assemblies from the running application's directory. Aside from adding assembly resolution handling in your application, there is also the `Microsoft.NETCore.DotNetHostPolicy.SetAppPaths` property that can be set in the application's `.runtimeconfig.json`. When set to `true`, that will cause the runtime to look for assemblies in the application's directory (basically sets the `APP_PATHS` [probing property](https://docs.microsoft.com/dotnet/core/dependency-loading/default-probing#host-configured-probing-properties) to be the application's directory).

**Comment by vitek-karas** [comment]
What version of the .NET Core you're using? (Both the version of the SDK and the version the app is targeting is interesting).

Can you please look at the `.deps.json` generated in the output folder. Does it contain records for the failing assembly - it should have a property with the name of the .dll - so `Siemens.Collaboration.Net.Logging.dll`.

If that is missing, please check your project references as per @elinor-fung comment - maybe some of them are marked as Private=false and this may cause problems like this.

Do you have any custom build steps in your project? Something which copies files to the output manually or some special handling of references and so on?

Is the failing assembly directly referenced from the application or it's a dependency of something else which is then referenced from the application?

**Comment by TFTomSun** [comment]
@vitek-karas the proposed solution from @elinor-fung solved the issue. I added the runtime.config now to all of my applications.

**Comment by vitek-karas** [comment]
`.runtimeconfig.json` itself doesn't have direct impact on assembly resolution (it's used to perform framework resolution). SDK should generate it for all apps (but not classlibs) and I strongly suggest you keep those files and ship them with the app. There are certain cases where it might work without them, but it's hard to predict specifically what else might break.

Rewriting package to project references "on-the-fly" is something I can't comment on, I don't know enough about .NET Core SDK internals to tell if it can cause issues later on with generating `.deps.json`. @dsplaisted may know.
