### ISSUE TITLE
[Uri] UNC paths should consistently convert backslashes

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#33049]
Related https://github.com/dotnet/runtime/issues/22103 https://github.com/dotnet/runtime/issues/33029

UNC paths passed to the Uri constructor seem to receive the same platform dependent treatment as file schemes, yet UNC is firmly a Windows file path concept. I believe backslashes should always be replaced in UNC paths, also when running on Unix.

```cs
var path = "test\\foo/bar";
var x = new Uri("//example.com/" + path);
Console.WriteLine(x.GetComponents(UriComponents.AbsoluteUri, UriFormat.Unescaped));
```

This outputs `test\foo/bar` on Unix and `test/foo/bar` on Windows.

And as alluded to in https://github.com/dotnet/runtime/issues/33029 I really think there should be a way to roundtrip file scheme urls between Unix and Windows; without having to deal with (or know about) these platform specific shenanigans.

Appendix E.4 of the file scheme RFC states https://tools.ietf.org/html/rfc8089#appendix-E.4

>It may be possible to translate or update such an invalid file URI by
replacing all backslashes "\" with slashes "/" if it can be
determined with reasonable certainty that the backslashes are
intended as path separators.

Though what should reasonable certainty mean? I would say that converting backslashes to slashes for ANY host doesn't sound like you could be reasonably certain about that transformation being correct, a gigantic portion of the internet is Unix based. 

Reasonably certain to me sounds more like, this file url is local like `file:///file.txt`, `file://localhost/file.txt` or `file://resolvestothishost/file.txt` or you have specific knowledge (a host list) that it is a windows machine, and the RFC would back me up on that local definition.

https://tools.ietf.org/html/rfc8089#section-1.1

>The term "local file URI" is used to describe file URIs that have no
"authority" component or where the authority is the special string
"localhost" or a fully qualified domain name that resolves to the
machine from which the URI is being interpreted (Section 2).

Now I understand it would be a breaking change to change `file` semantics for Uri, but I implore you to look into allowing this to be configured.

**Comment by joshudson** [comment]
I don't get it at all. Try `ls -l //bin/sh`. The idea of it even being a UNC path appears to be Windows-specific.

**Comment by karelz** [comment]
Triage: It seems to be worth considering. We should be careful about backward compatibility.
It needs more investigation and decision what to do about it.
