### ISSUE TITLE
Running dotnet in Linux chroot with FreeBSD host fails

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#33051]
The helloworld app in Linux chroot of FreeBSD still failed when invoking the compiler (at `dotnet exec /path/csc.dll...`, during the build). Tested with 3.1.2, without the [workaround](https://github.com/dotnet/runtime/issues/13475#issuecomment-559854433). Here is the truss output: https://api.cirrus-ci.com/v1/task/6667788790005760/logs/emulate%20dotnet.log. With the `sched_getcpu` workaround, it continues to work.

_Originally posted by @am11 in https://github.com/dotnet/runtime/issues/13475#issuecomment-593388064_

**Comment by am11** [comment]
Script with the `sched_getcpu` workaround: https://github.com/am11/freebsd-bootstrap-cli/blob/043bb4a/.cirrus.yml

without the workaround: https://github.com/am11/freebsd-bootstrap-cli/blob/0e316bb/.cirrus.yml

**Comment by janvorli** [comment]
@am11 would you be able to check if this issue still occurs? It seems that it should be fixed now.

**Comment by am11** [comment]
@janvorli, sorry the above links are dead. I have tested with latest SDK and the build is failing with socket issue: https://cirrus-ci.com/task/6736777027256320. Underlying issue is: https://github.com/dotnet/runtime/issues/39279. I will keep an eye on it and close if it works after the socket issue isresolved.

**Comment by mangod9** [comment]
@am11 any updates on this? If not might make sense to close this out and reopen if the issue repros. Thx.

**Comment by am11** [comment]
The issue with `dotnet build` still persists, so this is waiting for fix. I am not sure `needs more info` is the right tag for this issue. I have already provided the public CI link where the build is breaking..

**Comment by mangod9** [comment]
Can you please clarify what version are you still seeing the issue on (the original comment mentions 3.1.2)? Are there more details on the failure details? Thx

**Comment by am11** [comment]
The issue is from March, at that time it was tested on 3.1. Last link I shared (https://github.com/dotnet/runtime/issues/33051#issuecomment-658911567) is using preview 8. At this point I cannot test whether it works without `sched_getcpu` workaround due to another issue with the SDK, which CI logs show

**Comment by janvorli** [comment]
@am11 are you sure the underlying issue with the socket is #39279? Looking at the call stack in the Cirrus CI logs you have provided link to, it seems that there is a problem with a relatively recent change that uses socketpair to implement Process.Start redirection: #34861

**Comment by am11** [comment]
@janvorli, you are right, it is a socketpair issue not the socket. There is another issue reported today for WSL https://github.com/dotnet/runtime/issues/40727, with similar callstack.

**Comment by adamsitnik** [comment]
@am11 is there any chance you could see if #40851 has fixed the problem for you?

**Comment by am11** [comment]
@adamsitnik, thanks for the reminder. Waiting for https://github.com/dotnet/sdk/pull/12935 to pick up that change.

**Comment by danmosemsft** [comment]
@am11 did you get a chance to check whether it's fixed?

**Comment by am11** [comment]
I am sorry that I forgot to follow-up here. With .NET 5.0 RTM, we can publish a simple .NET application for Linux, and run it in Linuxulator (FreeBSD Linux simulator), without the `sched_getcpu` workaround. 

Green CI showing a working HelloWorld app: https://cirrus-ci.com/task/4833901384302592 (the logs are not permanent and will be deleted by CI service once their retention period will elapse).

However, for more complex applications (such as, csc.dll, the C# compiler or `dotnet-build`), there are still some missing/unimplemented syscalls in Linuxlator environment, that causes crashes like https://github.com/dotnet/roslyn/issues/46772. Those missing calls are being implemented by the FreeBSD community members, as the time is passing by.

On the other hand, applications such as Firefox, go-lang's `go(1)` and others are known to be working in Linuxulator environment: https://wiki.freebsd.org/Linuxulator. I would love to see that .NET achieves the similar working status in Linuxulator (and similar limited / chroot-like / WSL-like subsystem) environments. 😎

It might require a few tweaks around syscalls (maybe `mprotect`, `mlock` etc.), which can be detected during the run-time (or build-time, if it affects the performance). The (strace equivalent) `truss -f dotnet build` tracer output, which shows what happens before exit code 139 (SIGSEGV), was captured from CirrusCI and saved at: https://gist.github.com/am11/ec04e27cc93884dbcadf94691340c3e4 ⬅️ this is very verbose.

**Comment by janvorli** [comment]
@am11 thank you for the details. What would be the tweaks around mprotect and mlock that you have mentioned?
As for the SIGSEGV, I assume we don't have any call stack available for that, do we?

**Comment by am11** [comment]
@janvorli, I was guessing from this part of of the trace that the unimplemented `membarrier` is causing the problem for mprotect/mlock:

```
 6618: munmap(0x801276000,13132)		 = 0 (0x0)
 6618: linux_sched_getaffinity(0x19da,0x80,0x7fffffffccf8) = 32 (0x20)
 6618: linux_membarrier(0x0,0x0)		 ERR#-38 'Function not implemented'
 6618: linux_mmap2(0x0,0x1000,0x3,0x22,0xffffffffffffffff,0x0) = 34379096064 (0x801276000)
 6618: mlock(0x801276000,4096)			 = 0 (0x0)
 6618: linux_mprotect(0x80396a000,0x1000,0x7)	 = 0 (0x0)
 6618: linux_madvise(0x80396a000,0x1000,0x11)	 = 0 (0x0)
```
Unfortunately, collecting callstack is tricky and it would probably require recompilation of gdb on FreeBSD with Linux coredump handler, as described in these notes: https://papers.freebsd.org/2018/bsdcan/tuffli-Running_Linux_applications_on_FreeBSD.files/tuffli-Running_Linux_applications_on_FreeBSD-notes.txt. The problems I was running into are:

Debugging
* FreeBSD's gdb only shows child forks and their exit codes.
* Linux gdb in linuxulator (distro: CentOS 7) fails with:
  ```sh
  Starting program: /home/newhdd/.dotnet/dotnet run
  warning: linux_test_for_tracefork: unexpected result from waitpid (3790, status 0x57f)
  Couldn't get CS register: Invalid argument.
  ```
CoreDump analysis
* the coredump which gets produced is in FreeBSD format, so while FreeBSD LLDB and GDB do understand the dump, they do not recognize the dotnet binary.
* Linux GDB does understand the binary format but not the FreeBSD coredump format.
* `dotnet dump analyze` also does not understand the FreeBSD coredump format.

SOS plugin
* fails in FreeBSD's lldb, as it is a linux shared object.

(I haven't yet tried installing lldb in linuxulator)

**Comment by janvorli** [comment]
The missing membarrier should not be a problem, the mprotect / mlock is a fallback that we use if the membarrier doesn't work. Only arm64 would have problems because the mprotect / mlock thing doesn't work on it.

**Comment by am11** [comment]
Opened https://github.com/microsoft/clrmd/issues/875 for `dump analyze` support.
