### ISSUE TITLE
[Uri] Localpath shouldn't be encoding ucschars

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#33053]
Passing Uri a UNC path that contains unicode special characters - which are valid directory and file names on Windows - get encoded to a percent encoded triplet anyway. This is correct when dealing with Uris, but `Uri.LocalPath` should not encode these characters.

```cs
var path = "\uFFF0";
var x = new Uri("//example/" + path);
Console.WriteLine(x.LocalPath);
```

Outputs `//example/%EF%BF%B0` yet it should output `//example/￰￰￰` (which is `//example/\uFFF0`)

**Comment by davidsh** [comment]
@MihaZupan

**Comment by NinoFloris** [comment]
Question would also be, should `uri.GetComponents(UriComponents.AbsoluteUri, UriFormat.Unescaped)` keep them encoded?

**Comment by karelz** [comment]
Triage: `Localpath` should do escaping which is appropriate for the platform.
