### ISSUE TITLE
System.Drawing.Font Name and Unit properties are missing TypeConverterAttributes

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/runtime#33061]
Both the `Font.Name` and `Font.Unit` properties are missing attributes for their respective type converters, `FontNameConverter` and `FontUnitConverter`. Both of these are included in `System.Windows.Extensions`. These missing type converters negatively affect how the font properties are displayed in the property grid control.

**Comment by ericstj** [comment]
We should fix this by adding attributes back and pointing to converters via string assembly qualified type name.

**Comment by ericstj** [comment]
@safern can you pick this up?

**Comment by safern** [comment]
@ericstj yeah.

**Comment by danmosemsft** [comment]
@DustinCampbell does this block any designer scenario, or is it just missing text in the property window? If the latter, we will likely move out at this point.

**Comment by safern** [comment]
@danmosemsft this shouldn't be a big change that I can get soon-ish, however I'm focusing on the designer attributes that we're missing.

**Comment by danmosemsft** [comment]
OK cool. I see there's several similar related issues. Great!
