### ISSUE TITLE
Decouple Coreclr Test and Product build

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#33066]
Currently our test build requires build.cmd/sh to complete. This is a bottleneck for our CI, without it our long poles are serialized on each other.

In order to accomplish this the test build will need to split apart the managed test build from the native test build. The native test build will happen as a separate step, that can be run right after the product build.

Note this is a larger issue tracking the end goal. The work items required to reach it are below.

Related to 

- https://github.com/dotnet/runtime/issues/31793
- https://github.com/dotnet/runtime/issues/33067

# Work items

1. ~~https://github.com/dotnet/runtime/pull/637~~
2. https://github.com/dotnet/runtime/issues/33072
3. ~~https://github.com/dotnet/runtime/issues/34507~~
4. ~~https://github.com/dotnet/runtime/issues/34508~~

**Comment by marek-safar** [comment]
Please also think about producing test artefacts which can be used by multiple runtimes instead of building it for each runtime

**Comment by sdmaclea** [comment]
This is complete at least in `dev\infra`
