### ISSUE TITLE
Move coreclr tests out of src/coreclr/tests

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#33071]
This will allow the tests to be more easily shared with mono.

**Comment by jkoritzinsky** [comment]
Looking at our directory structure, once we move `src/coreclr/tests` to something directly under `src` like `src/runtimetests`, it would be possible to remove the `src` directory under `src/coreclr` and move the contents one level up if we want to make the hierarchy a little cleaner and more consistent with mono, libraries, and installer.

**Comment by BruceForstall** [comment]
Is there a proposal for what the changed directory structure will be? IMO, "src/runtimetests" is verbose... And would there still be "src/runtimetests/src"? Why not "tests" at the root?

**Comment by jashook** [comment]
Addressed
