### ISSUE TITLE
A bug while the 'TypeBuilder' class processing the value type generic argument for generic definition.

### ISSUE THREAD

**Issue by 2300070** [dotnet/runtime#33075]
I define a class to inherit existen generic type definition, however, the base type has one generic argument, the type I processing has two generic argument, and I want the second generic as the generic argument of base type, so I write the code below, but the strange thing is: if the first generic argument is class type(though it is not used by any place), it works fine, but if I change it to a value type, an exception will thrown('Unable to read memory'), is there any problem while the 'TypeBuilder' class processing the generic arguments?

	[TestClass]
	public class GeneralTest
	{
		[TestMethod]
		public void TestDefineGenericType()
		{
			AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("GeneralTest"), AssemblyBuilderAccess.RunAndCollect);
			ModuleBuilder module = assembly.DefineDynamicModule("GeneralTest.dll");

			//define type
			TypeBuilder builder = module.DefineType("TestGenericClass");
			GenericTypeParameterBuilder[] arguments = builder.DefineGenericParameters("TValue1", "TValue2");
			
			builder.SetParent(typeof(TestClass<>).MakeGenericType(arguments[1]));

			//define constructor that invoke base constructor
			ConstructorBuilder constructor = builder.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, new Type[] {arguments[1] });
			ILGenerator generator = constructor.GetILGenerator();
			generator.Emit(OpCodes.Ldarg_0);
			generator.Emit(OpCodes.Ldarg_1);
			generator.Emit(OpCodes.Call, typeof(TestClass<>).GetConstructors(BindingFlags.Public | BindingFlags.Instance)[0]);
			generator.Emit(OpCodes.Ret);
			
			Type builtType = builder.CreateType();
			Type testType;
			TestClass<string> test;

			//this test is okay.
			testType = builtType.MakeGenericType(typeof(object), typeof(string));
			test = Activator.CreateInstance(testType, string.Empty) as TestClass<string>;
			Assert.AreEqual(typeof(string), test.ValueType);
			Assert.AreEqual(string.Empty, test.Value);//OK

			//change the first generic argument to value type, exception will be thrown.
			testType = builtType.MakeGenericType(typeof(int), typeof(string));
			test = Activator.CreateInstance(testType, string.Empty) as TestClass<string>;
			Assert.AreEqual(typeof(string), test.ValueType);
			//Assert.AreEqual(string.Empty, test.Value);//ERROR WHILE READ THE FIELD OF 'test'

			
			//change the first generic argument to class type back, exception disapear.
			testType = builtType.MakeGenericType(typeof(string), typeof(string));
			test = Activator.CreateInstance(testType, string.Empty) as TestClass<string>;
			Assert.AreEqual(typeof(string), test.ValueType);
			Assert.AreEqual(string.Empty, test.Value);//OK
		}

		public class TestClass<TValue>
		{
			public readonly TValue Value;

			public Type ValueType => typeof(TValue);

			public TestClass(TValue value)
			{
				this.Value = value;
			}
		}
	}

**Comment by GrabYourPitchforks** [comment]
The IL in the sample is incorrect. You need to close over the `TestClass<Something>` rather than have an open `TestClass<>` inside the _call_ instruction. Otherwise the base class ctor could be invoked with the wrong type argument, which could lead to data corruption since it's unverifiable IL and will violate type safety. That also explains the errors you saw while running the sample.

I ran the repro on .NET 4.8 as well and saw the same behavior. The method _appears_ to work, but it's still operating with the wrong type arguments under the covers. This could lead to data corruption e.g. if a GC kicks in while the constructor is running.

Closing this issue since the behavior was also undefined (due to incorrect IL) on Full Framework.
