### ISSUE TITLE
HttpClient error 'Could not create SSL/TLS secure channel' when not Administrator

### ISSUE THREAD

**Issue by replaysMike** [dotnet/runtime#33085]
I'm trying to use certificate based authentication using HttpClient in .Net Standard 2.0. However, I've noticed TLS negotiation doesn't succeed unless running the application in Administrator mode.

```c#
var requestMessage = new HttpRequestMessage() {
    RequestUri = new Uri(new Uri(_configuration.Endpoint), "someendpoint"),
    Method = HttpMethod.Get
};
var handler = new HttpClientHandler {
    ClientCertificateOptions = ClientCertificateOption.Manual,
    SslProtocols = SslProtocols.Tls12,
};          
handler.ClientCertificates.Add(certificate);
handler.CheckCertificateRevocationList = false;
// this is required to get around untrusted self-signed certs
handler.ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => true;
var client = new HttpClient(handler);
requestMessage.Headers.Add("X-ARR-ClientCert", certificate.GetRawCertDataString());
var response = await client.SendAsync(requestMessage);
```
The client certificate is valid and installed in the local computer `My` store.

Without Administrator privileges a generic error is thrown: `The request was aborted: Could not create SSL/TLS secure channel` when not Administrator.

Anyone have a clue as to why?

**Comment by danmosemsft** [comment]
I'm going to guess from the text above that this was resolved. Please reactivate if not

**Comment by danmosemsft** [comment]
I'll leave this open so that networking folks can see it.

**Comment by karelz** [comment]
Seems to be environment setup problem, not networking code problem, closing.
Please let us know if you have evidence it is not true. Thanks!
