### ISSUE TITLE
Move Libraries test host setup out of the Libraries product build

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#33128]
Today, the setup of the libraries test host is done during the product build. This creates a dependency on the full CoreCLR or Mono build having been completed. The product build should just depend on getting a copy of System.Private.CoreLib to build against (either an implementation assembly or a ref assembly).

If this is implemented, then we can move the Libraries product build in PR/CI/Official builds to depend only on a job that builds System.Private.CoreLib and not on the CoreCLR or Mono builds. This will enable us to further parallelize our builds and shorten our official build times by 15-20 minutes.

cc: @dotnet/runtime-infrastructure

**Comment by jkoritzinsky** [comment]
This is blocking most of the PR and CI time improvements possible from #33067 since the coreclr test build depends on the libraries build which (without this being fixed) depends on the coreclr product build.

**Comment by jaredpar** [comment]
> This will enable us to further parallelize our builds and shorten our official build times by 15-20 minutes.

Love it.

**Comment by ericstj** [comment]
> The product build should just depend on getting a copy of System.Private.CoreLib to build against (either an implementation assembly or a ref assembly).

Worst case here we can segment the set of src libs that need a core-lib reference and build those separately from those which can build against our reference assemblies.

**Comment by ericstj** [comment]
@jkoritzinsky is this something you're working on?  Do we understand the dependencies of CoreLib project to know if this is technically feasible?  /cc @safern @ViktorHofer

**Comment by mangod9** [comment]
I believe my PR #34166 should help with this, and pretest.proj can we removed from the libraries build.

**Comment by ViktorHofer** [comment]
@jkoritzinsky this should already be done with the introduced clr.corelib subset: `build clr.corelib+libs`. Should we close the issue?

**Comment by ViktorHofer** [comment]
Long term I would like to see us using a P2P to CoreLib instead of the manual reference.

**Comment by jkoritzinsky** [comment]
Yes we can close this.
