### ISSUE TITLE
API extension proposal for System.String: string.Format function for string template

### ISSUE THREAD

**Issue by radityoardi** [dotnet/runtime#33136]
- name: System.String API proposal
- about: Propose an additional extension function for System.String, so that it can be used for string template
- title: ''
- labels: api-suggestion
- assignees: ''

## Background and Motivation
I've been using this extension function for a number of years. It would be awesome if I can share it with the world through this dotnet runtime.
Previously, we used to go with the following method to format a string with template.
```C#
string.Format("{0}-{1}-{2}-{3}", 1, 4.5, "Nice Information", DateTime.Now.ToString("yyyyMMdd"));
```
//produces "1-4.5-Nice Information-20190501"`

The numbers, developers sometimes get upset when the argument changes but we forgot to change the string formatting or the number is out of sync with the argument provided. Just imagine if you have more than 50 arguments....

## Proposed API
I am proposing an extension to the following signature
```diff
namespace System
{
    public partial class String
    {
        public static string Format(string format, object? arg0) {
        public static string Format(string format, object? arg0, object? arg1) {
        public static string Format(string format, object? arg0, object? arg1, object? arg2) {
        public static string Format(string format, params object?[] args) {
+       public static string Format(string format, dynamic args) {
    }
}
```
**OR**
to add a static extension
```diff
namespace System
{
    public static class StringManipulationExtensions
    {
+       public static string Format(this string format, dynamic args) {
    }
}
```

## Usage Examples
Imagine if we go just like the sample below, wouldn't it be meaningful and easy?
```C#
"{IndexNumber}-{CustomValue}-{Description}-{CurrentTime:yyyyMMdd}".Format(
  new {
    IndexNumber = 1,
    CustomValue = 4.5,
    Description = "Nice Information",
    CurrentTime = DateTime.Now
  });
```
//which produces the same "1-4.5-Nice Information-20190501"`

It's useful and easy to comprehend just like a string templating pattern. Common usage:
- Email template
- Configuration (*.config) template
- String pattern message template

**Note**: I am aware of [string interpolation syntax](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated).

I have this piece of code to share, but please give your comment if this is just a nice idea for me to contribute.

## Alternative Designs
No idea what to fill here.

## Risks
No idea on the risks as of now.

**Comment by GrabYourPitchforks** [comment]
@radityoardi Have you taken a look at the C# [string interpolation syntax](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)? It's intended to solve largely the same problem you had called out here.

```cs
int indexNumber = ...;
double customValue = ...;
string description = ...;
DateTime currentTime = ...;

string formattedString = $"{indexNumber}-{customValue}-{description}-{currentTime:yyyyMMdd}";
Console.WriteLine(formattedString);
```

**Comment by radityoardi** [comment]
Oops... I guess I've missed that out. Shall I close this issue instead, since it's supported in C# 6.0?

**Comment by GrabYourPitchforks** [comment]
If you think it suits your needs, go ahead and close this out. Otherwise if you think it's missing functionality feel free to leave any feedback here and we'll route it appropriately. Thanks!

**Comment by radityoardi** [comment]
@GrabYourPitchforks My memory is very bad, I remembered that I have one scenario where the C# string interpolation syntax may not work. If the string template comes from a variable (which probably comes from a file or a configuration file), then string interpolation syntax may not be the answer.
The reason being is that string interpolation will be validated upon compile-time. If there's an error in the string, it will throw error directly in the VS. While using the Format function I've suggested above, any error will throw a runtime error.
As I said, one good scenario would be used for message templating (i.e. email template format, SMS format which reads from a configuration file).

How do I get this approved before I can start work on it?

**Comment by GrabYourPitchforks** [comment]
I'll re-mark it as untriaged so the wider area owners can look at it.

**Comment by radityoardi** [comment]
Hi, I just want to follow up on this topic. How do I get

**Comment by radityoardi** [comment]
I accidentally clicked on Close and comment. Just wanted to follow up on this. Any way I can get this approved, so I can start work on it?

**Comment by GrabYourPitchforks** [comment]
The product teams are triaging issues. This issue is labeled as untriaged, so they should see it when they get through the backlog.

**Comment by Bartizan** [comment]
I'd like to vote for the feature to add the message template support for String.Format. Such functionality has been added for Microsoft.Extensions.Logging.ILogger in .net core. It will be more naturally to make both places work alike without an extension or 3rd party libraries. 
C# string interpolation syntax is a cool thing, nevertheless it is not an option at all here as we need to work with _message template_ represented by a string. The string, the message template, can contain placeholders for each arguments, defined as names, not numbers. That makes easier to understand the data it requires. Plenty of such strings you could find working e.g. on application localization. Some samples below 

`_logger.LogWarning(MyLogEvents.GetItemNotFound, "Get({Id}) NOT FOUND", id);`
`"Get({Id}) NOT FOUND"` vs `"Get({userId}) NOT FOUND"` vs `"Get({bookId}) NOT FOUND"` Isn't it more meaningful?
And the old good one:  `"Get({0}) NOT FOUND"`
When you have few placeholders it becomes a mess
Thank you @radityoardi for bringing attention to this problem and dotnet team for scheduling for an improvement

**Comment by radityoardi** [comment]
Thanks @Bartizan. @joperezr is there any way I can contribute a piece of code for this?

**Comment by joperezr** [comment]
Hey @radityoardi, thanks for logging the API suggestion, usually before we take a PR that provides implementation for the API we need the API to be approved first. In order to get this ready for review (so it can be approved) do you mind modifying the initial comment on the issue to instead use the [template we use for API Proposals](https://github.com/dotnet/runtime/blob/master/.github/ISSUE_TEMPLATE/02_api_proposal.md)?

**Comment by radityoardi** [comment]
> In order to get this ready for review (so it can be approved) do you mind modifying the initial comment on the issue to instead use the [template we use for API Proposals](https://github.com/dotnet/runtime/blob/master/.github/ISSUE_TEMPLATE/02_api_proposal.md)?
@joperezr Thanks for the pointer. I have modified the initial comment.

**Comment by radityoardi** [comment]
I will start contributing in my forked repo first. Once it's done, I will create a PR according to this guide https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md.

**Comment by stephentoub** [comment]
> Once it's done, I will create a PR

If this is about adding new public API, the method needs to be reviewed and marked approved before we'll accept PRs. You're welcome and encouraged to share a prototype by linking to your commit from here,  of course.

**Comment by KalleOlaviNiemitalo** [comment]
C# won't let you define both `Format(string format, object? arg0)` and `Format(string format, dynamic args)` in the same class; it cannot distinguish `object` from `dynamic` in the signature. <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#the-dynamic-type>

Thus, the new method would have to be named differently, or there would have to be some other difference in the signature; for example, replace `string format` with a type defined for this purpose.

**Comment by radityoardi** [comment]
> If this is about adding new public API, the method needs to be reviewed and marked approved before we'll accept PRs. You're welcome and encouraged to share a prototype by linking to your commit from here, of course.
Thanks @stephentoub I'll work on it. It will be under \runtime\src\libraries\System.Private.CoreLib\src\System\String.Manipulation.cs.

**Comment by radityoardi** [comment]
> C# won't let you define both `Format(string format, object? arg0)` and `Format(string format, dynamic args)` in the same class; it cannot distinguish `object` from `dynamic` in the signature. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#the-dynamic-type
> 
> Thus, the new method would have to be named differently, or there would have to be some other difference in the signature; for example, replace `string format` with a type defined for this purpose.

damn, you've got the point, I missed this one. Any suggestion for the new name?

**Comment by radityoardi** [comment]
I will see if I can use regex inside this function to detect whether it's using a numeric format like {0} or named format {ThisIsMyString}.
![image](https://user-images.githubusercontent.com/12979499/110241414-91e7c780-7f8b-11eb-9bfd-f592ca6c26f6.png)

**Comment by danmoseley** [comment]
If this code is in system.Private.corelib then it will not have access to regex as it is too low level. It would need a hand written parser.

**Comment by KalleOlaviNiemitalo** [comment]
If String.Format(String format, Object arg0) can look at public properties of arg0, then will that require some attribute on the arg0 parameter, to prevent those properties from being trimmed out by IL Linker?

I thought [DynamicallyAccessedMembersAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-5.0) was it, but that is documented as applying only to Type or String, not Object.

**Comment by radityoardi** [comment]
Hi Team, just last straw. I just want to **contribute** this String.Format function to dotnet runtime.
Can you all suggest to me which code tree I should put this function in?

The idea of this function is the same as `String.Format("var1: {0} var2: {1}", var1, var2)` but instead of numbers, we do naming. This will be more suitable for devs who like to do string template such as `String.Format("var1: {var1} var2: {var2}", var1, var2)`.

Any suggestion where I should put this?

**Comment by stephentoub** [comment]
@radityoardi, I'm not clear on what you're proposing.  You can already do this:
```C#
string result = $"var1: {var1} var2: {var2}";
```

At this point, I don't see us adding anything further here, especially not something that's going to use reflection to find things to fill the holes in a string.Format call (I'm also not clear how reflection would help in your pseudo-code where the arguments could be locals).

I'm going to close out this suggestion.  If you have some helpers you believe would be useful to other developers, I'd encourage you to publish a nuget package, and anyone who wants to can then use the library you've produced.

Thanks.
