### ISSUE TITLE
System.IO.Ports should not depend on System.Native

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#33130]
We don't consider System.Native to be a stable public API, yet System.IO.Ports depends on it.  This can cause someone using an older System.IO.Ports to break when running on a newer shared framework where we update System.Native.

System.IO.Ports should remove this dependency, for example by including the same exports in its own native library, or eliminating the usage by moving functionality into the assembly.

We could potentially add validation to our packaging to catch this (we already analyze assemblies for DllImports here).

**Comment by krwq** [comment]
cc: @maloo that should fix the issue you have mentioned in https://github.com/dotnet/runtime/issues/35545

**Comment by maloo** [comment]
Great, do you know if anyone is working on this issue? Seems to been idle for a long time. And without this fixed there is no way of using SerialPort in net core 3.1 LTS.

**Comment by krwq** [comment]
Likely myself or one of the co-owners will pick this up soon. Note this fix won't be available for this preview anyway, I'm targeting preview5 (or whatever we name what comes after preview4).

I'm planning to pick this up possibly early next week. As a workaround for you in the meanwhile I recommend removing Flush and older version of the package (which we shipped in 3.1 timeframe).

**Comment by maloo** [comment]
Prefect, let me know when there is a nuget (nightly or others) and I will test it. Unfortunately I can't just remove the Flush, it is other .Net frameworks that is calling it. My example was just the result of tracking the issue down into a minimal repro for issue reporting. One framework that is calling Flush is this one (the one that got me into this issue): https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeWriter.cs#L308

**Comment by krwq** [comment]
@maloo 3.1 should work with System.IO.Ports:
5.0.0-preview.6.20272.2 from thus nuget feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

5.0 will only work with next preview (because of https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json which is causing that latest .so files is not restored because it's already part of the framework)

**Comment by maloo** [comment]
ok, so we fixed 3.1 and broke 5? :)

I will test 3.1 this weekend. Found another old issue that I will file, SerialStream is still messing with DtrEnable in constructor. This prevent usage of some devices in windows, Linux works but you have to hard code dtrenable to same value as kernel, so probably also need fixing.

**Comment by krwq** [comment]
@maloo yes/no, next preview will work correctly with latest preview package and old (3.1 timeframe) but will not work with the previous previews. Once we fix https://github.com/dotnet/runtime/issues/33932 then next 5.0 preview will start working correctly as native components will not fight for dominance 😄
