### ISSUE TITLE
System.IO.Tests.Enumeration.SpecialDirectoryTests_Enumerable.SkippingHiddenFiles test fails on Windows 10 2004

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#33148]
```
System.IO.Tests.Enumeration.SpecialDirectoryTests_Enumerable.SkippingHiddenFiles [FAIL]
        Assert.Contains() Failure
        Not found: .
        In value:  String[] [".."]
        Stack Trace:
          C:\git\runtime4\src\libraries\System.IO.FileSystem\tests\Enumeration\SpecialDirectoryTests.cs(64,0): at System.IO.Tests.Enumeration.SpecialDirectoryTests_Enumerable.SkippingHiddenFiles()
```

OS build: 19574.1000

cc @JeremyKuhne @carlossanlop @jozkee

**Comment by JeremyKuhne** [comment]
Interesting. @ViktorHofer does this fail consistently for you?

**Comment by ViktorHofer** [comment]
No, not consistently.

**Comment by ViktorHofer** [comment]
Just ran the tests again and it failed 2 out of 5 runs.

**Comment by ViktorHofer** [comment]
Still failing for me locally.

cc @carlossanlop @adamsitnik

**Comment by janvorli** [comment]
Failed again in a PR: https://dev.azure.com/dnceng/public/_build/results?buildId=1380764&view=ms.vss-test-web.build-test-results-tab&runId=40254434&resultId=140845&paneView=debug

**Comment by danmoseley** [comment]
With the addition of the Windows 11 test configuration, it's now failing fairly often and always on Windows 11. 

I looked at a number of the console outputs and its always the same as above. Maybe an OS bug that is now more common?

https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI2TQY%2faMBCF70j8h2lOIFED0qrqhUq7UFoqtbttkHqoKmSSgQw4tuWxRVPtj69JYAnqHjhFjt%2b8efNlskT2P5CD8tztPMPOkIY96XxCWqODn8btFx5LBqNfDov8NekXs65V8dkIDgU6hDlp4gJz%2bDABbQ69t%2bPRKO93O8PhWbGsLMJkAklacXQXM5JbbdhTxmIZ47F4ciZD5vqQXKyb3HXpXJJq3XwPGPBekeT69hBTmgOL8VjIMn93JzJFqL11KIxFnbTTPDipswLesJfO84F8AYnDDQ9tUOqk5FCW0tFfhMwE7Xt9WFfwFX1h8kGr9yXPfzMuHk%2bjfdShRCc9GS1SixlJNSOHmTeuqhWrk2KtMAGp81OfxmxP1pLefqY8Rz0nhXw1Sx3lmywR2tMY%2fjMcXulalp%2bcCfahWjVsU1R1lNU0sDfl1JRWxrDGJfBqn3HtEdYRShDj96M7IV0klRVnzs9gndlFT0iPifCK1wAAnsiiIh1hgY874OJ0vdiTcbVjo3txEyw6T8h9McNN3K0juWPr%2fqDbuZSvpkZvaBsasjeYZW39yauQfEOOX%2bdvWuuPUZLfjcFjGqtf2NSv7iOLG9IckZGPmILD%2bK90O%2f8AstMmmqcDAAA%3d&web=0
```
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-100d)
| where Result == "Fail"
| where QueueAlias == "windows.11.amd64.clientpre.open"
| where  Type == "System.IO.Tests.Enumeration.SpecialDirectoryTests_Enumerable" and Method == "SkippingHiddenFiles"
| project Started, QueueAlias,   Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  Phase = tostring(parse_json(Properties)["System.PhaseName"]),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture)
```


|Started|QueueAlias|Pipeline|Pipeline_Configuration|Phase|OS|Arch|
|---|---|---|---|---|---|---|
|2021-09-09 08:17:37.2270000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-09 20:30:06.3990000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-09 21:32:31.4430000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-10 09:49:41.8230000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-13 03:18:30.8830000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-13 15:06:41.6920000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-13 16:01:03.9450000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-16 12:08:03.2580000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-16 16:36:30.8400000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-16 18:47:51.6540000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-20 00:01:52.7740000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-20 20:05:32.2150000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-21 04:24:58.7370000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-21 14:50:39.7390000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-21 14:57:21.2680000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-21 20:12:14.4620000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-21 23:07:01.1850000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-22 04:55:27.5180000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-23 06:08:23.1540000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-23 07:52:49.5000000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-23 10:30:48.2340000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-23 14:28:08.2160000|windows.11.amd64.clientpre.open|runtime|Debug|libraries_test_run_release_coreclr_windows_x64_Debug|windows.11.amd64.clientpre.open|x64|
|2021-09-23 16:03:25.9120000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-23 16:03:28.2770000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-23 20:26:09.7920000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-24 04:35:26.8560000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-24 18:31:16.0280000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|
|2021-09-24 18:39:12.3940000|windows.11.amd64.clientpre.open|runtime-staging|Release|build_windows_x64_Release_AllSubsets_Mono|windows.11.amd64.clientpre.open|x64|

@dotnet/area-system-io might want to disable this line `Assert.Contains(".", paths);` just for windows 11.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/pull/59516

**Comment by jkotas** [comment]
Failure is https://github.com/dotnet/runtime/issues/33148

**Comment by danmoseley** [comment]
@dotnet/area-system-io  suggest disabling for Windows 11, or only verifying ".." there.

**Comment by danmoseley** [comment]
I'll do it

**Comment by mdh1418** [comment]
This was hit again on `Libraries Test Run release coreclr windows x64 Release` in an unrelated PR https://github.com/dotnet/runtime/pull/64952. Could this be one of the rare cases @danmoseley ?
>// Sometimes this is not returned - presumably an OS bug.
                // This occurs often on Windows 11, very rarely otherwise.
                
                
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1606293&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d&s=96ac2280-8cb4-5df5-99de-dd2da759617d
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64952-merge-007e44d80b3b48d59a/System.IO.FileSystem.Tests/1/console.8f75c14f.log?sv=2019-07-07&se=2022-03-03T01%3A55%3A33Z&sr=c&sp=rl&sig=YciFBQJ4sUU27D6l7nOTAuuviASVFJDCL43jVuPYetE%3D

**Comment by danmoseley** [comment]
@mdh1418 I'm guessing Windows Server 2022 and Windows 11 share the same "feature" and both need to be disabled the same way. Do you want to twiddle it?
https://github.com/dotnet/runtime/blob/96d72db9cbb748628ece37662dd252e49f3b9776/src/libraries/System.IO.FileSystem/tests/Enumeration/SpecialDirectoryTests.cs#L64

**Comment by mdh1418** [comment]
I can add to it, will put up a PR soon!
