### ISSUE TITLE
Crossgen2 build of framework assemblies is failing due to missing hostpolicy.dll / libhostfxr.so

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#33155]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=546025&view=logs&j=3cca9cb6-fa2f-5752-29bd-c1a454d766a9&t=23eb0527-6ff4-535f-2f76-7f76e2f1841d

On Windows it complains about missing hostpolicy.dll.
On Linux it complains about missing libhostfxr.so.
On OSX it claims that it cannot find the crossgen2 executable under Core_Root/crossgen2.

**Comment by jkoritzinsky** [comment]
This is due to my changes to the CoreCLR build. Crossgen2 needs to be run on CoreRun now. Looks like I missed a spot where we were running it via the apphost.

**Comment by trylek** [comment]
Fixed by

https://github.com/dotnet/runtime/commit/630a2185a87310b9d81ccfa4cfe82d5fd3563770
