### ISSUE TITLE
Reduce the run time of crossgen_comparison

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#33172]
Currently the crossgen comparison job takes anywhere between 30 minutes and 2 hours. Ideally the corssgen comparison runtime should be ~5 minutes.

The quicker the helix submission finishes the less contention there will be on the arm queue.

**Comment by am11** [comment]
+1 i waited for 2 hours in https://github.com/dotnet/runtime/pull/32800 to get some results, then it 404'd. 😁
