### ISSUE TITLE
Changes to Library Testing Workflow

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#33171]
The following targets were removed with https://github.com/dotnet/runtime/commit/33f2807fc64b938ee1584e515c746ddae1b03b56: **RebuildAndTest** and **BuildAndTest**.

The recommended command to test libraries is `dotnet build /t:Test` which incrementally calls restore and build. If you want to skip building the library, you can pass in the `/p:TestNoBuild=true` flag. We are working on enabling `dotnet test`, meanwhile this will hopefully simplify the existing workflow.

This is documented here: https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md.

**Comment by danmosemsft** [comment]
Not directly related, but useful examples from @ViktorHofer : 

Q1: How do I build coreclr in Release and libraries in Debug?
	.\build.cmd/sh -subsetcategory coreclr-libraries -runtimeconfiguration release

Q2: How do I build coreclr in Release and libraries in Release?
	.\build.cmd/sh -subsetcategory coreclr-libraries -runtimeconfiguration release -c Release

Q3: How do I test with VSTest Explorer against a release runtime?
	.\build.cmd -vs System.Text.RegularExpressions -runtimeconfiguration Release

Q4: How do I build mono in Release and libraries in Debug?
	.\build.cmd/sh -subsetcategory mono-libraries -runtimeconfiguration release

Q5: How do I invoke tests on a single csproj against a Release runtime?
	dotnet build /t:Test repo\...\...\System.Text.RegularExpressions.Tests.csproj /p:RuntimeConfiguration=Release
