### ISSUE TITLE
Move CoreCLR Helix tests to run XUnit on dotnet CLI instead of corerun

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#33185]
To enable to to get more fine-grained errors when running our test suite, we should move our Helix tests to pull down a dotnet CLI and run our tests against it with `dotnet xunit.console.dll` instead of `corerun xunit.console.dll`. This will allow us to get better diagnosability to test failures when the failure would cause xunit to not run our tests. It also moves us closer to running our tests with `dotnet test`.

See the [Helix SDK Readme](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix/Sdk) for docs on how to pull down a dotnet CLI as part of a Helix job.

**Comment by hoyosjs** [comment]
Will the inner test (the process that runs under the script) still be corerun and not run in-proc?

**Comment by nattress** [comment]
Yes - the inner-most process must be corerun since we need to use the runtime under test
