### ISSUE TITLE
When does AbsoluteExpiration Triggers?

### ISSUE THREAD

**Issue by vivekscripts** [dotnet/runtime#33188]
I am using "System.Runtime.Caching.MemoryCache" (https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime.Caching/src/System/Runtime/Caching/MemoryCache.cs) and wants to use "AbsoluteExpiration" for my cache entries to expire. However , looks like it's expiration triggers only if there is an activity on the cacheItem i.e. Get/Set/Remove etc.  
 
I see in extensions version of the library - https://github.com/dotnet/extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs
 
it does "StartScanForExpiredItems()" whenever any Get/Set/Remove happens on any cache item. 
 
However,  in general version of the library , it looks like only the specific items is evicted when accessed. 
 
...... lock (_entriesLock) {                if (_disposed == 0) {
                    existingEntry = _entries[key] as MemoryCacheEntry;
                    // has it expired?
                    if (existingEntry != null && existingEntry.UtcAbsExp <= DateTime.UtcNow) {
                        toBeReleasedEntry = existingEntry;
                        toBeReleasedEntry.State = EntryState.RemovingFromCache;
                        existingEntry = null;
                    }
                    // can we add entry to the cache?
                    if (existingEntry == null) {
                        entry.State = EntryState.AddingToCache;
                        added = true;
                        _entries[key] = entry;
                    }
                }
            }
            // release outside of lock
            RemoveFromCache(toBeReleasedEntry, CacheEntryRemovedReason.Expired, delayRelease:true);
            if (added) {
                // add outside of lock
                AddToCache(entry);
            }
            // update outside of lock
            UpdateExpAndUsage(existingEntry);
           
            // Dev10 861163: Call Release after the new entry has been completely added so
            // that the CacheItemRemovedCallback can take a dependency on the newly inserted item.
            if (toBeReleasedEntry != null) {
                toBeReleasedEntry.Release(_cache, CacheEntryRemovedReason.Expired);
            }
            return existingEntry;.......
 
https://github.com/microsoft/referencesource/blob/master/System.Runtime.Caching/System/Caching/MemoryCacheStore.cs
 
given multiple versions of the library and number of different articles - its causing lot of confusion around what's the expected behavior. 
 
appreciate your help on how to handle "absolute Expiration" gracefully in thread safe manner, so any cache item is evicted after the expiry.

**Comment by StephenMolloy** [comment]
Apologies for the super late reply to this. We had several issues fall off our tracking board for a long time without anyone noticing. We just recently discovered that and have moved to use different tracking methods as we catch up on issues that have gone unnoticed for a while. :/

The first thing I'd like to address here is that **System.Runtime.Caching.MemoryCache** and **Microsoft.Extensions.Caching.Memory.MemoryCache** are two completely separate cache implementations. Both originated from the ASP.Net team (several years apart), so you may see similarities... but they are independent. When ASP.Net Core was first getting off the ground, they wanted to redesign the caching paradigm there to be more inline with the goals of ASP.Net Core. [This short article](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0#systemruntimecachingmemorycache) briefly covers some of the different caches available in .Net and recommends using Microsoft.Extensions.Caching whenever possible. System.Runtime.Caching.MemoryCache was not originally planned for .Net Core. Eventually we did port it to help bridge .Net 4.x and .Net Core for customers trying to port existing code. SRC.MemoryCache is meant to be a bridge, it is not an actively developing project.

So, how does expiration work in SRC.Caching? There are two ways a cache item can be "expired" from MemoryCache. The first, as you noted, is if the expired item is accessed in some way and the cache sees that it has lived past its expiration time. The second way is simply via a timer. Each MemoryCache maintains a timer thread that periodically sweeps the cache with housekeeping tasks such as removing expired items.

What this means is that cache items are unlikely to be "evicted" immediately at the moment they expire. Once you pass their expiration time, MemoryCache will no longer let you access them. But they might still live in the cache until you do try to access them, or the timer thread sweeps them out. For a general purpose application cache, that's really all you need. And that's all that SRC.MemoryCache was designed to be. (It's actually a nearly-direct port of ASP.Net's original System.Web.Caching.Cache. When we found that many customers were trying to use that outside of ASP.Net applications, we decided to give them a similar cache that was unencumbered by System.Web baggage in .Net 4.0 - and it really is a fairly direct port of the System.Web cache, just in it's own more portable assembly.)

I don't know if there is any official documentation from Microsoft about how SRC.MemoryCache works - either in .Net 4.X or .Net Core. But wrt this particular question, I did find a pretty simple exploration in a [blog post](https://failingfast.io/erratic-behaviour-from-net-memorycache-expiration/) by Ben Hall.

Hope that helps!
