### ISSUE TITLE
Failed CoreCLR build outputs CI-only telemetry line

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#33181]
If I do an incremental CoreCLR build that fails, using:
```
build -subsetcategory coreclr -subset runtime -c Debug
```

the last line of the output is:
```
(NETCORE_ENGINEERING_TELEMETRY=Category) Build failed.
```

Isn't this only supposed to be output in a special `-ci` mode that is only used in the CI system? We don't need/want this on developer machine builds, do we?

**Comment by BruceForstall** [comment]
@dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
cc @chcosta
