### ISSUE TITLE
UrlAttribute IsValid not checking for empty URL

### ISSUE THREAD

**Issue by Bikonja** [dotnet/runtime#332]
The `System.ComponentModel.DataAnnotations.UrlAttribute` method `IsValid` does not check the passed in URL is not empty, i.e. `https://`, `https://` or `ftp://`.

The current code for this method (after checking for `null`) looks like this:
```
return value is string valueAsString &&
                (valueAsString.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
                || valueAsString.StartsWith("https://", StringComparison.OrdinalIgnoreCase)
                || valueAsString.StartsWith("ftp://", StringComparison.OrdinalIgnoreCase));
```

A possible solution could be to `&&` every `StartsWith` with `valueAsString.Length > startsWithString.Length` (hardcoded lengths to prevent calculating length every time?), however this would still leave cases like `http://\` "valid", even though that's not a valid URL.

I am going by Chrome's definition of a valid URL, specifically, if you put `window.location = 'http://'` into the JS console, it will give an error `Uncaught DOMException: Failed to set the 'href' property on 'Location': 'http://' is not a valid URL.`.
I haven't checked the code for `System.Uri`, however passing in those strings seem to give the same result as Chrome. As my code can take the overhead, I've currently added a custom URL attribute that `try`s to instantiate a `System.Uri` and, if there's a `UriFormatException` it returns `false`, otherwise it returns `true`, however I'm not sure of the performance implications for adding it to this attribute so I'll just leave all this info here for you to discuss :)

**Comment by ajcvickers** [comment]
We are not planning on changing behaviors of data annotations because preserving compatibility with existing applications is very important here. Experience has shown applications can break easily with very small, seemingly innocuous, changes to behavior. Instead, we recommend using your own validation rules where those supplied do not match your requirements.
