### ISSUE TITLE
linq.count()  too slow

### ISSUE THREAD

**Issue by bobobobo9** [dotnet/runtime#33216]
maybe use HashSet<object>.count  better？

**Comment by bobobobo9** [comment]
new Set<TSource>(source).count  maybe fast than foreach

**Comment by GrabYourPitchforks** [comment]
I'm not sure I understand your question. Can you clarify what you're looking for?

**Comment by stephentoub** [comment]
`Enumerable.Count()` by default just enumerates the source, walking each element, counting as it goes, so it's O(N) in the length of the input.  It has some special cases, e.g. checking to see if the source implements `ICollection` and using its `Count` property if it does, but if you know the type of the source and if it has a `Length` or `Count` property, you're better off just directly using that.  There's an analyzer for that exact thing as well, CA1829, that was added in https://github.com/dotnet/roslyn-analyzers/releases/tag/v2.9.5.  Thanks.
