### ISSUE TITLE
Almost impossible get the actual number of ReJitIds using ICorProfilerInfo4::GetReJITIDs

### ISSUE THREAD

**Issue by NitzanEgozy** [dotnet/runtime#33222]
Hey,
Unlike other API calls, this call is unable to receive 0 as the input and return the actual size:
```
HRESULT ProfToEEInterfaceImpl::GetReJITIDs(
                           FunctionID          functionId,  // in
                           ULONG               cReJitIds,   // in
                           ULONG *             pcReJitIds,  // out
                           ReJITID             reJitIds[])  // out
{
    ...
	...

    if (functionId == 0)
    {
        return E_INVALIDARG;
    }

    if ((cReJitIds == 0) || (pcReJitIds == NULL) || (reJitIds == NULL))
    {
        return E_INVALIDARG;
    }

    MethodDesc * pMD = FunctionIdToMethodDesc(functionId);

    return ReJitManager::GetReJITIDs(pMD, cReJitIds, pcReJitIds, reJitIds);
}
```
It seems that it is impossible to know how many ReJITIDs there are - Yes, I can allocate a buffer and recheck if it was filled, but that is just wasteful.
I can also listen to ReJITCompilation** callbacks and track it myself, but this just adds a lot of unnecessary bloat to the whole thing. Is it correct to assume that a ReJIT can only occur if the profiler requests it (excluding tiered compilation for the same ReJITId) ?

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
I haven't actually tested this, but from reviewing the code it looks like the call to ReJitManager::GetReJITIDs actually would do what you want, it's just that there is the explicit check and return of E_INVALIDARG.

Something like this should let you work around it:
```
    ReJITID dummyIDs[1];
    ULONG rejitIDsCount;
    pProfInfo->GetReJITIDs(funcID, 1, &rejitIDsCount, dummyIDs);

    ReJITID *realIDs = new ReJITID[rejitIDsCount];
    ULONG returnedCount;
    pProfInfo->GetReJITIDs(funcID, rejitIDsCount, &returnedCount, realIDs);
```

The only cost to your program would be one extra stack allocated variable which should effectively be no cost.

Or you could go a step further and get rid of any allocation for the common case. Assuming you do a small number of ReJITs per function this would require no allocation whatsoever unless you did more than 10 ReJITs, which is extremely rare in my experience but you would know better for your use case.
```
    constexpr ULONG expectedMaxReJITs = 10;
    ReJITID dummyIDs[expectedMaxReJITs];
    ULONG rejitIDsCount;
    HRESULT hr = pProfInfo->GetReJITIDs(funcID, expectedMaxReJITs, &rejitIDsCount, dummyIDs);

    if (hr == S_FALSE)
    {
        ReJITID* realIDs = new ReJITID[rejitIDsCount];
        ULONG returnedCount;
        pProfInfo->GetReJITIDs(funcID, rejitIDsCount, &returnedCount, realIDs);
    }
```

>  Is it correct to assume that a ReJIT can only occur if the profiler requests it (excluding tiered compilation for the same ReJITId) ?

A ReJIT can only happen if the profiler requests it. Tiered compilation won't affect this. You would see multiple JITCompilationStarted events, but only one ReJITCompilationStarted and only one ReJITID for each ReJIT (event with tiered compilation on).

**Comment by NitzanEgozy** [comment]
Hey David, thanks for the response. I managed to work around with it (used a constant of a bigger size, which is how we do a lot of the API with profiler-allocated buffers (we find it a lot more efficient for our cases). I didn't test what happens when we put in 1, but I'll try that soon.
However, it still looks like this specific method is different than the others. This is very confusing, as the API says "It follows the same usage pattern as other ICorProfilerInfo functions that accept caller-allocated buffers.", which it does not.

Thanks for providing the extra information regarding ReJIT/Tiered.

**Comment by noahfalk** [comment]
> You would see multiple JITCompilationStarted events, but only one ReJITCompilationStarted and only one ReJITID for each ReJIT (event with tiered compilation on).

Are you sure that is how it plays out David? With tiered compilation I would expect a sequence like this:
tier0 compilation - JitComplete
tier1 compilation - JitComplete
rejit happens
tier 0 compilation of new IL - RejitComplete
tier 1 compilation of the new IL - RejitComplete
https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/prestub.cpp#L812
