### ISSUE TITLE
.Net Core - Stuck on connection.open() in the Linux while connecting Sql Server

### ISSUE THREAD

**Issue by nayanishdamania** [dotnet/runtime#33220]
.Net Core 3.1 stuck on the **connection.open()** method call on Linux machine as well as Docker, it is working sometimes and stuck sometimes. Don't know where is the actual issue.

I am using **Microsoft.Data.SqlClient** library for the connection, I have tried **System.Data.SqlClient** too getting the same issue.
Even tried to downgrade the .Net core version from **3.1** to **2.2** and **2.1**

Tried with SQL Server **2008 R2 SP3**, **2012** and **2017**.

It is working fine on the Windows machine.

**Connection String:** Server={database.server},{database.port};Database={database.database};User Id={database.user};Password={dbPassword};MultipleActiveResultSets=True;Connection Timeout={database.connectionTimeout};Packet Size=32768;

Thanks in advance.

**Comment by Wraith2** [comment]
/cc @cheenamalhotra for a move to https://github.com/dotnet/SqlClient

Someone on gitter had something similar recently and on investigating he found that it was a security policy issue on the linux image, it was trying to force TLS 1.3 and not allowing TLS 1.2 which is what sql needs. Can you see if this might be the same thing?

If that doesn't work then we'll need some more information from you to diagnose the problem. There's not a lot we can do with just knowing it hangs. Can you try to get thread status'? stack traces? a memory dump?

**Comment by cheenamalhotra** [comment]
I see https://github.com/dotnet/SqlClient/issues/455 was created and closed later, perhaps this one was left out and can be closed too.

@nayanishdamania Just FYI, SqlClient repo is the right place to create respective issues.
