### ISSUE TITLE
Needs to provide ability for watching sources from github inside vs code

### ISSUE THREAD

**Issue by ndomanovskiy** [dotnet/runtime#33227]
I work with net core every day. Sometimes i really want to watch inside some classes, for example, i want to understand how i can use my own ```IGroupManager``` in Signalr Core, or maybe i want to understand possibility of catch ```NRE``` when i use ```MemoryCache.Get```. For investigate this thing i every time go to browser, go to github, and trying to find necessary sources there. 

It is possible to watch sources from github inside my visual studio code? Maybe you know about extensions which can decompile sources or redirect me to github page with source code.

**Comment by stephentoub** [comment]
@ndomanovskiy, https://github.com/microsoft/vscode would be a better repo for this issue.  Can you open one there instead?  There's nothing in this repo that would contribute into that kind of tooling in VS Code.  Thanks.

**Comment by ndomanovskiy** [comment]
@stephentoub okay, thx!
