### ISSUE TITLE
Marshal.AllocHGlobal alignment

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#33228]
Documentation doesn't specify the alignment of allocated memory returned by `Marshal.AllocHGlobal`. What is the expected alignment? Does it change based on machine bitness/OS?

Perhaps it's interesting to have an overload that accepts alignment as an argument (cfr [posix_memalign](http://man7.org/linux/man-pages/man3/posix_memalign.3.html))?

cc @adamsitnik

**Comment by tmds** [comment]
For Linux, the implementation calls malloc (LocalAlloc -> HeapAlloc -> PAL_malloc -> malloc).

This is documented to be aligned as

> functions return a pointer to the allocated memory that is suitably aligned for any kind of variable. 

So this property will also hold for `AllocHGlobal`: if you want to allocate to match a native struct with C types, you can assume `AllocHGlobal` returns something with proper alignment.

For Linux/x64, alignment is `16`, that is alignment of `long double`.
For Linux/x86, alignment is `8`. that is alignment of `long long` (`long double` is aligned at `4`).

**Comment by EgorBo** [comment]
I don't think it's possible to set desired alignment here and be able to free the memory correctly with given IntPtr.

**Comment by jkotas** [comment]
> Documentation doesn't specify the alignment of allocated memory

Could you please submit documentation edit to make this clear now that you have found the answer?

>  it's interesting to have an overload that accepts alignment as an argument

Could you please create a new API proposal issue on this? FWIW, I am not sure whether it is a good idea to make it overload. I think it would need to be a new pair of alloc/free methods to make it implementable cross-platform (e.g. see last post in https://stackoverflow.com/questions/33696092/whats-the-correct-replacement-for-posix-memalign-in-windows).

**Comment by tmds** [comment]
We know what it does on Linux now. We still need the answer for Windows. It may also be different on macOS (it uses something other than `malloc`).

**Comment by tmds** [comment]
Created https://github.com/dotnet/runtime/issues/33244 for API proposal.

**Comment by jkotas** [comment]
This needs to be a new pair of alloc / free APIs to make it cross-platform. There is no away to allocate aligned HGlobal memory on Windows. These APIs need to map to `_aligned_malloc` / `_aligned_free` on Windows. The names of the new APIs should not contain HGlobal.

**Comment by GrabYourPitchforks** [comment]
On Windows this function calls the Win32 API `LocalAlloc`. The MSDN docs for that function don't explicitly call out an alignment, but historically this has been at least 8-byte aligned. I'd be shocked if the OS team ever broke this assumption given the massive compatibility hit it'd incur. See also https://web.archive.org/web/20160204192037/https://support.microsoft.com/en-us/kb/286470.

**Comment by jkotas** [comment]
Superseded by #33244
