### ISSUE TITLE
ConcurrentDictionary.GetOrAdd is not always thread safe.

### ISSUE THREAD

**Issue by hikalkan** [dotnet/runtime#33221]
See the implementation:

https://github.com/dotnet/runtime/blob/e2881ae96bb4399864723aa46469c82379b03b32/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1033-L1037

Two problems here:

1. Multiple threads may check `TryGetValueInternal` then gets false and calls `TryAddInternal` which causes the factory method execuites multiple times. If the factory is doing a heavy work, this is a significiant problem.
2. If the factory method is using another shared object, then factory method will be concurrently executed and the shared object will be concurrently accessed, which can be a bug source ([we had this problem](https://github.com/abpframework/abp/issues/2736))

I think GetOrAdd should be completely thread safe since we trust in the ConcurrentDictionary, use it without checking its internal implementation.

**Comment by davidfowl** [comment]
GetOrAdd is thread safe.

> Multiple threads may check TryGetValueInternal then gets false and calls TryAddInternal which causes the factory method execuites multiple times. If the factory is doing a heavy work, this is a significiant problem.

> If the factory method is using another shared object, then factory method will be concurrently executed and the shared object will be concurrently accessed, which can be a bug source (we had this problem)


Those complaining about the same problem. The factory being executing concurrently is well documented in the remarks section of the API https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=netcore-3.1#System_Collections_Concurrent_ConcurrentDictionary_2_GetOrAdd__0_System_Func__0__1__.

If you want to avoid concurrent execution then use a Lazy<T> as the value in the dictionary.

**Comment by GrabYourPitchforks** [comment]
The API seems to be behaving [as documented](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd). Are you suggesting a new, separate mode of operation for a different API?

**Comment by hikalkan** [comment]
Sorry, you are right. It is explained in the documentation:

>Since a key/value can be inserted by another thread while valueFactory is generating a value, you cannot trust that just because valueFactory executed, its produced value will be inserted into the dictionary and returned. If you call GetOrAdd simultaneously on different threads, valueFactory may be called multiple times, but only one key/value pair will be added to the dictionary

So, we need to be careful about this.
