### ISSUE TITLE
Investigate why System.Memory.Span* dotnet microbenchmarks are very slow on mono-interpreter

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#33232]
[DotNet Microbenchmarks on MonoJit and Interpreter.xlsx](https://github.com/dotnet/runtime/files/4293302/DotNet.Microbenchmarks.on.MonoJit.and.Interpreter.xlsx)

From attached sheet, seems like the System.Memory.Span* benchmarks are very slow on Mono Interpreter compared to the Mono-Jit run.   Refer to second column in copy-paste below, or refer to attached excel sheet. I'll paste in exact repro steps to run the benchmarks locally.

**Benchmark | dotnet_core | mono_interpreter | mono_jit**

System.Memory.Span<Byte>.BinarySearch(Size: 512) | 1 | 93.55 | 3.22
System.Memory.Span<Byte>.Clear(Size: 512) | 1 | 552.02 | 6.28
System.Memory.Span<Byte>.EndsWith(Size: 512) | 1 | 324.71 | 6.09
System.Memory.Span<Byte>.Fill(Size: 512) | 1 | 569.07 | 6.61
System.Memory.Span<Byte>.IndexOfAnyFourValues(Size: 512) | 1 | 1219.37 | 3.7
System.Memory.Span<Byte>.IndexOfAnyThreeValues(Size: 512) | 1 | 1379.02 | 5.3
System.Memory.Span<Byte>.IndexOfAnyTwoValues(Size: 512) | 1 | 1262.11 | 4.47
System.Memory.Span<Byte>.IndexOfValue(Size: 512) | 1 | 1869.31 | 6.22
System.Memory.Span<Byte>.LastIndexOfAnyValues(Size: 512) | 1 | 1006.57 | 3.5
System.Memory.Span<Byte>.LastIndexOfValue(Size: 512) | 1 | 1021.84 | 3.4
System.Memory.Span<Byte>.Reverse(Size: 512) | 1 | 239.84 | 1.65
System.Memory.Span<Byte>.SequenceCompareTo(Size: 512) | 1 | 341.67 | 4.83
System.Memory.Span<Byte>.SequenceEqual(Size: 512) | 1 | 397.49 | 5.67
System.Memory.Span<Byte>.StartsWith(Size: 512) | 1 | 319.99 | 6.03
System.Memory.Span<Byte>.ToArray(Size: 512) | 1 | 48.42 | 6.23
System.Memory.Span<Char>.BinarySearch(Size: 512) | 1 | 88.89 | 3.14
System.Memory.Span<Char>.Clear(Size: 512) | 1 | 25.37 | 1.1
System.Memory.Span<Char>.EndsWith(Size: 512) | 1 | 406.34 | 6.36
System.Memory.Span<Char>.Fill(Size: 512) | 1 | 32.71 | 1.56
System.Memory.Span<Char>.IndexOfAnyFourValues(Size: 512) | 1 | 170.06 | 4
System.Memory.Span<Char>.IndexOfAnyThreeValues(Size: 512) | 1 | 150.99 | 4.15
System.Memory.Span<Char>.IndexOfAnyTwoValues(Size: 512) | 1 | 149.91 | 5.01
System.Memory.Span<Char>.IndexOfValue(Size: 512) | 1 | 2091.54 | 6.14
System.Memory.Span<Char>.LastIndexOfAnyValues(Size: 512) | 1 | 150.68 | 2.64
System.Memory.Span<Char>.LastIndexOfValue(Size: 512) | 1 | 99.27 | 5.5
System.Memory.Span<Char>.Reverse(Size: 512) | 1 | 241.43 | 2.43
System.Memory.Span<Char>.SequenceCompareTo(Size: 512) | 1 | 1061.93 | 4.39
System.Memory.Span<Char>.SequenceEqual(Size: 512) | 1 | 445.79 | 5.78
System.Memory.Span<Char>.StartsWith(Size: 512) | 1 | 421.96 | 6.5
System.Memory.Span<Char>.ToArray(Size: 512) | 1 | 43.4 | 6.87
System.Memory.Span<Int32>.BinarySearch(Size: 512) | 1 | 63.76 | 2.1
System.Memory.Span<Int32>.Clear(Size: 512) | 1 | 18.42 | 1.08
System.Memory.Span<Int32>.EndsWith(Size: 512) | 1 | 444.99 | 6.3
System.Memory.Span<Int32>.Fill(Size: 512) | 1 | 36.52 | 1.56
System.Memory.Span<Int32>.IndexOfAnyFourValues(Size: 512) | 1 | 484.17 | 3.71
System.Memory.Span<Int32>.IndexOfAnyThreeValues(Size: 512) | 1 | 151.98 | 3.39
System.Memory.Span<Int32>.IndexOfAnyTwoValues(Size: 512) | 1 | 200.02 | 3.54
System.Memory.Span<Int32>.IndexOfValue(Size: 512) | 1 | 494.03 | 3.82
System.Memory.Span<Int32>.LastIndexOfAnyValues(Size: 512) | 1 | 207.83 | 3.68
System.Memory.Span<Int32>.LastIndexOfValue(Size: 512) | 1 | 242.27 | 2.67
System.Memory.Span<Int32>.Reverse(Size: 512) | 1 | 242.14 | 2.43
System.Memory.Span<Int32>.SequenceCompareTo(Size: 512) | 1 | 183.55 | 2.45
System.Memory.Span<Int32>.SequenceEqual(Size: 512) | 1 | 489.8 | 6.04
System.Memory.Span<Int32>.StartsWith(Size: 512) | 1 | 454.72 | 6.22
System.Memory.Span<Int32>.ToArray(Size: 512) | 1 | 40.06 | 6.38

**Comment by SamMonoRT** [comment]
Based on recent set of PRs, is this ok to close @BrzVlad ?

**Comment by BrzVlad** [comment]
Much of the slowness here has been addressed. Closing this in detriment of more specific issues https://github.com/dotnet/runtime/issues/34750 and https://github.com/dotnet/runtime/issues/34751
