### ISSUE TITLE
Investigate why the Burgers.Test* dotnet benchmarks run slow on mono-interpreter

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#33234]
[DotNet Microbenchmarks on MonoJit and Interpreter.xlsx](https://github.com/dotnet/runtime/files/4293434/DotNet.Microbenchmarks.on.MonoJit.and.Interpreter.xlsx)

From attached sheet, seems like the Burgers.Test* benchmarks are very slow on Mono Interpreter compared to the Mono-Jit run. Refer to second column in copy-paste below, or refer to attached excel sheet. I'll paste in exact repro steps to run the benchmarks locally.

**Benchmark | dotnet_core | mono_interpreter | mono_jit**
Burgers.Test0 | 1 | 182.19 | 11.67
Burgers.Test1 | 1 | 240.41 | 13.8
Burgers.Test3 | 1 | 2550.7 | 4.8

**Comment by jkotas** [comment]
@SamMonoRT Could you please use only one area path? https://github.com/dotnet/runtime/blob/master/docs/issues-pr-management.md#scenarios-where-we-all-have-to-work-together

We may want to delete `area-Performance-mono` and use `tenet-performance` instead. It is how we mark performance-related issues in a specific area everywhere else. cc @marek-safar

**Comment by SamMonoRT** [comment]
thanks @jkotas - I updated the 3 issues I logged today to use the tenet-performance path.

**Comment by danmosemsft** [comment]
Sorry for confusion: what @jkotas meant is all issues and PR's should have exactly 1 label that has the "area-" prefix. (The bot attempts to apply these, usually correctly: if it gets it wrong or fails, folks fix it, and the bot learns.) 

The other labels like "tenet-" prefixed ones can be added as needed.

**Comment by SamMonoRT** [comment]
From slack conversation :  
Burgers Microbenchmark comparison after @vlad.brezae added more interpreter intrinsics (https://github.com/mono/mono/pull/19174) for math stuff. These are ratios to dotnet core in the first colum, and the end of feb column is before his change. It made a big difference!
Benchmark	dotnet_core	mono_end_of_feb	mono_interp_intrin_change
Burgers.Test0	1	        359.78	          28.27
Burgers.Test1	1	        495.58	          36.82
Burgers.Test2	1	         59.03	          18.89
Burgers.Test3	1	       8558.16	         2499.82
macOS Mojave 10.14.6 (18G103) [Darwin 18.7.0]			
Intel Core i7-7920HQ CPU 3.10GHz (Kaby Lake)			


Burgers.Test3 is still pretty slow and I will investigate a little more to see what can be done about that.

Egor Bogatov  4:26 AM
Burgers.Test3 uses SIMD (Vector<T>)
a small hack to improve Burgers in general -- is to optimize Math.Pow(x, 2) to x * x :slightly_smiling_face: (edited) 
Also burgers allocate arrays using the slow path allocators because of sizes (edited)

**Comment by SamMonoRT** [comment]
This issue : https://github.com/dotnet/runtime/issues/34751 should cover this one. Closing this one.
