### ISSUE TITLE
Remove A/W probing for PInvokes on non-Windows platforms

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#33246]
Currently both Mono and CoreCLR have logic to probe for functions ending in `W` (Unicode) or `A` (Ansi) when resolving P/Invoke targets.

This doesn't really make sense on non-Windows platforms where such a convention doesn't exist.

From discussion with @jkotas:

> CoreCLR does the W/A probing today even on non-Windows. I do not think it makes any sense. I would be ok with doing a breaking change for CoreCLR to remove this probing on non-Windows to make more sensible cross-plat behavior.

/cc @lambdageek @CoffeeFlux

**Comment by jkotas** [comment]
cc @jkoritzinsky @AaronRobinsonMSFT It would be nice to do this sooner rather than later so that we have enough time to react to feedback if it is problematic.

**Comment by CoffeeFlux** [comment]
Once this change goes in for CoreCLR, I'll PR the corresponding Mono change for *netcore only*.

**Comment by jkotas** [comment]
@CoffeeFlux  Could you please make matching change for Mono?

**Comment by CoffeeFlux** [comment]
Will PR today or tomorrow – things are a bit busy today since I'm in the process of transitioning to WFH.
