### ISSUE TITLE
Running CoreCLR tests on Mono : Investigate and hook up running the with PRs/CI, making sure any change in CoreCLR or Mono triggers these test run on Mono

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#33255]
Referring to comments in PR : https://github.com/dotnet/runtime/pull/33176
Investigate and hook up running the CoreCLR tests during PRs/CI, making sure any change in CoreCLR or Mono triggers these test run on Mono

**Comment by naricc** [comment]
@akoeplinger

**Comment by akoeplinger** [comment]
@directhex can you please take a look at this one when you have time?

**Comment by naricc** [comment]
My draft PR is here: https://github.com/dotnet/runtime/pull/34054

**Comment by SamMonoRT** [comment]
We can close this one. We are tracking this via the table in https://github.com/dotnet/runtime/issues/33381
