### ISSUE TITLE
About libraries cross-building on x64

### ISSUE THREAD

**Issue by NextTurn** [dotnet/runtime#33269]
https://github.com/dotnet/runtime/blob/fef9ca70f6e7268dfc9e0f600433f5293932f166/docs/workflow/building/libraries/cross-building.md#L78

This is incorrect. Managed assemblies on x64 platforms are **NOT** architecture-independent.

1. All assemblies except *mscorlib.dll* on x64 have 0x020B (PE32+) magic in PE header

Which means they cannot be loaded on 32-bit platforms. A bad image format exception (with path) will be thrown on 32-bit platforms, which is propagated simply as `E_FAIL`.

```
coreclr_initialize failed - status: 0x80004005
```

2. Framework assemblies except *mscorlib.dll* on Linux x64 have 0xFD1D (invalid) machine type in COFF header (dotnet/sdk#10772)

This leads to a bad image format exception (without path) later in CoreCLR x86. It's surprising that CoreCLR x64 isn't affected by this?

```
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B (COR_E_BADIMAGEFORMAT))
```

**Comment by ericstj** [comment]
> All assemblies except mscorlib.dll on x64 have 0x020B (PE32+) magic in PE header

I am not seeing this.  Perhaps you're looking at **cross-gened** binaries which have been JIT'ed and are architecture specific?  If you examine the output of the libraries build under artifacts\bin\runtime you should find the non-crossgen'ed IL.  The shipping runtime packages / shared framework has been cross-gened for the architecture noted in the package.
```
C:\src\dotnet\runtime\artifacts\bin\runtime\netcoreapp5.0-Windows_NT-Debug-x64>corflags System.Runtime.dll
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.8.3928.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x9
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 1

C:\src\dotnet\runtime\artifacts\bin\runtime\netcoreapp5.0-Windows_NT-Debug-x64>corflags System.Reflection.Metadata.dll
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.8.3928.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x9
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 1
```

System.Private.CoreLib on the other hand, is built with PE header for x64 since it's coupled to the CoreCLR for that architecture, but this document isn't discussing CoreLib (which is part of CoreCLR subset, not libraries)
```
C:\src\dotnet\runtime\artifacts\bin\coreclr\Windows_NT.x64.Release>corflags System.Private.CoreLib.dll
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.8.3928.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32+
CorFlags  : 0x4
ILONLY    : 0
32BITREQ  : 0
32BITPREF : 0
Signed    : 0

C:\src\dotnet\runtime\artifacts\bin\coreclr\Windows_NT.x64.Release>link /dump /headers System.Private.CoreLib.dll
Microsoft (R) COFF/PE Dumper Version 14.26.28619.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file System.Private.CoreLib.dll

PE signature found

File Type: DLL

FILE HEADER VALUES
            8664 machine (x64)
               3 number of sections
        B056B9EF time date stamp
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
            2022 characteristics
                   Executable
                   Application can handle large (>2GB) addresses
                   DLL
...
```

> Framework assemblies except mscorlib.dll on Linux x64 have 0xFD1D (invalid) machine type in COFF header (dotnet/sdk#10772)

Again, looks like crossgen.

You may be examining the wrong libraries.  During the installer build we cross-gen all the libraries.  The cross-gen'ed libraries become architecture (and OS platform) specific. 

Let me know what you're trying to do and we might be able to provide a better reccomendation.

/cc @jkotas @janvorli @sbomer

**Comment by NextTurn** [comment]
I simply built a self-contained Hello World app as described in dotnet/sdk#10772, copied the managed parts (no CoreLib or System.Native etc.) to x86 and saw these error messages. I didn't know whether the framework assemblies were cross-gened or not.

If I was seeing cross-gened assemblies, I'm curious in what the 0xFD1D machine type means. I believe the `IMAGE_FILE_MACHINE_*` values are sufficient to represent most existing machine types. Why not use `IMAGE_FILE_MACHINE_AMD64` for `linux-x64`, which is used for `win-x64`?

And what's the value of cross-gen'ing IL-only libraries like *HelloWorld.dll*?

**Comment by jkotas** [comment]
>  0xFD1D machine type

The Windows machine types are XORed with OS-specific masks in crossgened images
https://github.com/dotnet/runtime/blob/0c610c5de7db0b97099b9d3ea1a071a1027264bc/src/coreclr/src/inc/pedecoder.h#L91 . This is done to make ensure that Windows crossgened image does not get used on Unix, and vice versa - it would result into hard to diagnose crash.

**Comment by NextTurn** [comment]
Thanks for the great answers.
