### ISSUE TITLE
Variant interfaces do not need to be at the beginning of implementation lists

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#33260]
Types like `List<T>` carefully order implemented interfaces to have more common ones earlier in the list.

However, JIT does not call the casting helper that performs linear scan (`IsInstanceOfInterface`) for variant interfaces, so there is not much benefit from having, say, `IEnumerable<T>` 3rd in the implementation list of `List<T>`

We could either 
- move the variant interfaces to the end of the list or 
- teach JIT to use `IsInstanceOfInterface` with variant interfaces as well.
If most type checks do not involve variance conversion, there could be a slight win.

**Comment by jkotas** [comment]
If there is a benefit in reordering the interface list in the EE datastructures due to implementation details of the casting algorithms, we should do that transparently in the type builder. There is no point to send everybody onto a treadmill to tweak the code for this one.

**Comment by jkotas** [comment]
> If most type checks do not involve variance conversion

I do not think that it is safe to assume this. The Linq in particular tends to exercise the slow casting paths a lot.

**Comment by VSadov** [comment]
I think in some obscure cases order of interface implementation could be observable. I am not sure we can't reorder them.

I know that these interfaces were ordered by hand some time ago. I am just pointing that placing variant interfaces in front of the list is not helpful, unless JIT uses scanning casting for them.

This is not a new issue.

**Comment by jkotas** [comment]
The order is observable via reflection. We generally do not guarantee order in which reflection return things. If we really wanted, we can still make reflection to return the metadata order - but I do not think it is worth the trouble.

> I know that these interfaces were ordered by hand some time ago

The whole story is that the interfaces were reordered by accident as part of port from .NET Framework, somebody observed performance regression compared to .NET Framework that made us look at the order.

**Comment by VSadov** [comment]
It is not a huge issue either. Just an observation that interfaces on `List<T>` are roughly in the expected frequency order. Including the variant ones.

One thing that we can do is to use `IsInstanceOfInterface`  with interface instantiations over value types.

**Comment by VSadov** [comment]
Ideally, of course, the cache lookup would be so fast that we would not use scanning algorithm at all. This would be challenging. Scanning is very efficient on small interface lists, which is common case too.

I would be ok with closing this for now. It may need more thought.
