### ISSUE TITLE
Error downloading artifacts: could not find end of central directory record

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#33271]
Seeing a number of builds fail with the following AzDO error:

> Failed to extract package with error Error: Could not find the End of Central Directory Record

Impacting 6% of our builds

|Build|Kind|Timeline Record|
|---|---|---|
|[548493](https://dev.azure.com/dnceng/public/_build/results?buildId=548493)|PR https://github.com/dotnet/runtime/pull/33265|Download Build Assets|
|[548308](https://dev.azure.com/dnceng/public/_build/results?buildId=548308)|PR https://github.com/dotnet/runtime/pull/32669|Download Libraries artifacts|
|[548144](https://dev.azure.com/dnceng/public/_build/results?buildId=548144)|PR https://github.com/dotnet/runtime/pull/33252|Download live-built libraries|
|[548115](https://dev.azure.com/dnceng/public/_build/results?buildId=548115)|PR https://github.com/dotnet/runtime/pull/33251|Download native test artifacts|
|[547950](https://dev.azure.com/dnceng/public/_build/results?buildId=547950)|PR https://github.com/dotnet/runtime/pull/33062|Download CoreCLR build drop|
|[547772](https://dev.azure.com/dnceng/public/_build/results?buildId=547772)|PR https://github.com/dotnet/runtime/pull/32716|Download CoreCLR build drop|
|[547534](https://dev.azure.com/dnceng/public/_build/results?buildId=547534)|PR https://github.com/dotnet/runtime/pull/33153|Download live-built libraries|
|[547398](https://dev.azure.com/dnceng/public/_build/results?buildId=547398)|PR https://github.com/dotnet/runtime/pull/33212|Download CoreCLR build drop|
|[547026](https://dev.azure.com/dnceng/public/_build/results?buildId=547026)|PR https://github.com/dotnet/runtime/pull/33196|Download Test Assets|
|[546766](https://dev.azure.com/dnceng/public/_build/results?buildId=546766)|PR https://github.com/dotnet/runtime/pull/33170|Download CoreCLR artifacts|
|[546604](https://dev.azure.com/dnceng/public/_build/results?buildId=546604)|PR https://github.com/dotnet/runtime/pull/33024|Download product build|
|[546639](https://dev.azure.com/dnceng/public/_build/results?buildId=546639)|PR https://github.com/dotnet/runtime/pull/33168|Download managed test artifacts (built on Windows_NT)|

**Comment by ilyas1974** [comment]
Per Roman in teams channel - Created support request to AzDO: SR120030625000392 and emailed VSTS experts.

**Comment by ilyas1974** [comment]
ICM for this issue - https://portal.microsofticm.com/imp/v3/incidents/details/178680958

**Comment by ilyas1974** [comment]
ICM was just updated by AzDO - "We have disabled the partial artifact feature. The artifact download should now happen through agent code for build artifact. Can you please observe and let us know if you are continuing to see errors?"

**Comment by jaredpar** [comment]
Closing as the zip disable has fixed this.
