### ISSUE TITLE
DateTime no longer displays a readable time while debugging

### ISSUE THREAD

**Issue by timgabrhel** [dotnet/runtime#33287]
#### DateTime objects would display a formatted date as string while inspecting during debugging.

Here's what I'm used to seeing.
![image](https://user-images.githubusercontent.com/791022/75925031-97b54500-5e2d-11ea-85f8-2ecc77970b2c.png)

But what I'm now seeing.
![image](https://user-images.githubusercontent.com/791022/75925127-bf0c1200-5e2d-11ea-89e1-56c3bbc44d4c.png)

#### Details

The first screenshot is from .NET Framework 4.6.2. This behavior was observed as current as .NET Core 2.2. 

We recently upgraded to 3.1 1 week ago and I'm now seeing this issue.
Debugging in Visual Studio 2019 16.4.2

**Comment by scalablecory** [comment]
@tarekgh

**Comment by stephentoub** [comment]
This is more likely an issue with how settings are configured in Visual Studio. e.g. In Tools | Options | Debugging | General, what is your setting for:
![image](https://user-images.githubusercontent.com/2642209/76091358-6a7ea900-5f8b-11ea-9203-5b2cc37908e7.png)

**Comment by timgabrhel** [comment]
@stephentoub Thanks for the details! Never knew about that property. It's checked for me and I can't seem to reproduce it now, so it must have somehow changed.
