### ISSUE TITLE
Bad password on Rijndael does not throw exception in netcore 3.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#33283]
Hello,

While migrating our app to netcore 3, one of our test want red.
This unit test is availble [here](https://github.com/CK-Build/CKli/blob/5debb16e8f15eabd9344932da4fb85e1c8cfcaf9/Tests/CK.SimpleKeyVault.Tests/SimpleKeyVaultTests.cs#L25).
The test tried to decrypt with an invalid password.
In netcore 2.1 it throwed a with a CryptographicException with the message "Padding is invalid and cannot be removed".
In netcore3.1, it doensn't throw anymore but output gibberish.

I could not find any documentation on this breaking change, did I missed it?

**Comment by vcsjones** [comment]
This is going to depend on what the PKCS#7 padding is. As a general rule, you cannot rely on "Padding is invalid and cannot be removed" to detect if the wrong key / iv was used to decrypt something. This isn't specific to .NET, but AES-CBC as a whole.

More specifically, you need to authenticate your ciphertext using something like HMAC, first.

You can reproduce the behavior you are seeing in .NET Core 2.1 here:

```csharp
using System;
using System.Security.Cryptography;

public class Program {
    private static void Main(string[] args) {
        using var encryptor = Aes.Create();
        using var encryptTransform = encryptor.CreateEncryptor();
        using var decryptor = Aes.Create();
        byte[] content = System.Text.Encoding.ASCII.GetBytes("hi");
        byte[] ciphertext = encryptTransform.TransformFinalBlock(content, 0, content.Length);

        while (true) {
            decryptor.GenerateKey(); // Decryptor will have different key
            decryptor.IV = encryptor.IV; // Decryptor will have different key
            using var decryptTransform = decryptor.CreateDecryptor();

            try {
                byte[] plaintext = decryptTransform.TransformFinalBlock(ciphertext, 0, ciphertext.Length);
                string result = System.Text.Encoding.ASCII.GetString(plaintext);
                Console.Write($"Decrypt successfully: {result}");
                break;
            }
            catch (CryptographicException) {
                continue;
            }
        }
    }
}
```

This just tries decrypting something in a loop with the wrong key until it "succeeds". It will output the wrong plaintext however:

```
❯ dotnet run
Decrypt successfully: ???M??Jt?k????R
```

**Comment by GrabYourPitchforks** [comment]
What OS are you running? Did anything else in the environment change between 2.1 and 3.1? Even something as simple as your .cs files' line endings changing from CRLF to LF or vice versa?

**Comment by bartonjs** [comment]
It looks like you read a count value of `-1056021119` then exit the loop before ever reading the last block.

In prior versions of .NET, CryptoStream's Dispose with a decryptor in Read mode would frequently result in a bad padding exception if you exited before fully reading it (even when the key/IV/ciphertext were right), and it looks like you were depending on that.  It was reported as issue #16991 (though originally with a lower number, in a different repository) and fixed in https://github.com/dotnet/corefx/pull/36048.  Now we only process the padding when reading the final block.

It looks like this got missed when we did 3.0 breaking change documentation; so I'm going to call this a docs bug to add it now.

**Comment by Kuinox** [comment]
>  As a general rule, you cannot rely on "Padding is invalid and cannot be removed"

We fixed this issue, but i was curious as i didn't saw the changes in the docs, that all.

**Comment by krwq** [comment]
@bartonjs @Kuinox will my doc changes https://github.com/dotnet/docs/pull/20366 related to https://github.com/dotnet/runtime/issues/2042 also cover this? This seems similar if not the same. Should I perhaps add some more details there or would that be sufficient?

**Comment by bartonjs** [comment]
It's about the level I had in mind.

**Comment by Kuinox** [comment]
Maybe mention that it would break code that was using the exception to check if it's a bad key, which is something that you shouldn't do anyway.
Otherwise, it's fine, thanks!

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/docs/pull/20366
