### ISSUE TITLE
Add Mono LLVM debug nuget package for Windows.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#33282]
Mono LLVM netcore build on Windows can currently only be done in release configuration until we add a separate downloadable LLVM nuget containing the debug build version of LLVM, restored during debug build.

Background causing this issue is described here:

https://github.com/mono/mono/pull/19044

We should keep existing release package as is and add an additional package including "debug" in package naming. When running debug build of mono netcore using LLVM, the debug nuget package should be downloaded and restored instead of release.

**Comment by directhex** [comment]
I merged support for a Windows Debug LLVM package this morning.
