### ISSUE TITLE
Analyzers aren't running for vbprojs

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#33284]
During my work in https://github.com/dotnet/runtime/pull/33242 I noticed that analyzers aren't running for vbproj. My changes fixes that but I'll temporarily disable it again to fix the errors.

This issue tracks fixing the analyzer issues inside our vbprojs by flipping the condition in the "<EnableAnalyzers" property in src\libraries\Directory.Build.props

cc @stephentoub @ericstj

**Comment by stephentoub** [comment]
The only vbproj we have is Microsoft.VisualBasic.Core, right? That project is one we don't want to churn, and we have no intent on adding additional projects. I don't see a need to enable analyzers for VB in this repo, unless I'm missing something important.

**Comment by ViktorHofer** [comment]
> unless I'm missing something important.

I'm fine disabling the Analyzers for that project. I wanted to raise the issue that we aren't running analyzers on project on which we thought we would run them. I also noticed another not running on all projects but I don't have enough data yet to share.

**Comment by stephentoub** [comment]
> we aren't running analyzers on project on which we thought we would run them.

I never thought we were running them for VB :)

**Comment by stephentoub** [comment]
> we aren't running analyzers on project on which we thought we would run them.

I never thought we were running them for VB :) I thought we explicitly had a condition somewhere to only run them for C# projects.

**Comment by ViktorHofer** [comment]
> I thought we explicitly had a condition somewhere to only run them for C# projects.

I just checked again, can't find such a condition, maybe I'm missing some details here. @safern wrote that part when we switched to Arcade. Anyway, I'll disable the analyzers for VB.Core. Thanks.

**Comment by stephentoub** [comment]
Thanks.
