### ISSUE TITLE
Unable to build (timeout when restoring)

### ISSUE THREAD

**Issue by lpereira** [dotnet/runtime#33294]
I'm trying to build on a newly-installed Fedora 31 machine.  Dependencies have been installed according to the documentation, but I'm getting a timeout when `build.sh` tries to restore.

```
/home/leandro/runtime/.dotnet/sdk/5.0.100-preview.2.20155.14/NuGet.targets(124,5): error : Unable to load the service index for source https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet-tools/nuget/v3/index.j
son. [/home/leandro/runtime/tools-local/tasks/installer.tasks/installer.tasks.csproj]
/home/leandro/runtime/.dotnet/sdk/5.0.100-preview.2.20155.14/NuGet.targets(124,5): error :   The HTTP request to 'GET https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet-tools/nuget/v3/index.json' has timed out after 100000ms. [
/home/leandro/runtime/tools-local/tasks/installer.tasks/installer.tasks.csproj]
                     NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet-tools/nuget/v3/index.json.
```

(I've temporarily changed some shell scripts in `eng/` to execute with bash tracing, plus force msbuild to be called with `diag` verbosity. Can send the full log.)

It doesn't seem to be a network issue. Accessing that URL from the command line with something like Curl works just fine and returns me the expected JSON data.

This is unrelated to #2199.

`master` is at 2018c7931.

**Comment by lpereira** [comment]
Also happens in a Ubuntu 19.10 release, with same symptoms: NuGet times out while fetching that JSON, but it's fine if obtained with Curl.

**Comment by lpereira** [comment]
On Ubuntu 18.04 this seems to work just fine.  (Might be related to something else, as I've also switched from running things inside VirtualBox to Docker for Mac.)

**Comment by ViktorHofer** [comment]
Moving to NuGet.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/9785

**Comment by xiangzhai** [comment]
Hi @ViktorHofer 

But ArchLinux is still able to reproduce this issue.

Thanks,
Leslie Zhai
