### ISSUE TITLE
Tests are timing out in PRs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#33291]
There are a number of tests that are timing out:

- `System.Diagnostics.PerformanceCounter.Tests`
- `System.Text.Json`

Using ` System.Diagnostics.PerformanceCounter.Tests` as a marker to track this underlying isuse. 

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#549014](https://dev.azure.com/dnceng/public/_build/results?buildId=549014)|#33223|2|
|[#549037](https://dev.azure.com/dnceng/public/_build/results?buildId=549037)|#33278|2|
|[#549299](https://dev.azure.com/dnceng/public/_build/results?buildId=549299)|#33017|2|
|[#549304](https://dev.azure.com/dnceng/public/_build/results?buildId=549304)|#33261|1|
### Configurations
- netcoreapp5.0-Windows_NT-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|
| --- | --- | --- | --- | --- |
|[#549014](https://dev.azure.com/dnceng/public/_build/results?buildId=549014)|#33223|[console.d4b22e03.log](https://helix.dot.net/api/2019-06-17/jobs/35872f90-68d9-4675-8643-c766a9267787/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.d4b22e03.log)|||
|[#549014](https://dev.azure.com/dnceng/public/_build/results?buildId=549014)|#33223|[console.9970f35d.log](https://helix.dot.net/api/2019-06-17/jobs/ec9eac50-4315-49c3-8cdd-7ed5502c098a/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.9970f35d.log)|||
|[#549037](https://dev.azure.com/dnceng/public/_build/results?buildId=549037)|#33278|[console.31072bb4.log](https://helix.dot.net/api/2019-06-17/jobs/9ad856fb-5886-46b6-b96d-1ba7ac86c4a1/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.31072bb4.log)|||
|[#549037](https://dev.azure.com/dnceng/public/_build/results?buildId=549037)|#33278|[console.6476e110.log](https://helix.dot.net/api/2019-06-17/jobs/5e2f333b-8200-4d7d-a701-815a57d19dd2/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.6476e110.log)|||
|[#549299](https://dev.azure.com/dnceng/public/_build/results?buildId=549299)|#33017|[console.f54bc2e4.log](https://helix.dot.net/api/2019-06-17/jobs/0af835a5-0fa9-4163-8616-1c8137e13271/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.f54bc2e4.log)|||
|[#549299](https://dev.azure.com/dnceng/public/_build/results?buildId=549299)|#33017|[console.7dd0156a.log](https://helix.dot.net/api/2019-06-17/jobs/2374bc41-46b6-435d-aaae-9766b118abe6/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.7dd0156a.log)|||
|[#549304](https://dev.azure.com/dnceng/public/_build/results?buildId=549304)|#33261|[console.897427b0.log](https://helix.dot.net/api/2019-06-17/jobs/fc5c1f33-626c-4949-9b2c-6ead60768348/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.897427b0.log)|||

**Comment by danmosemsft** [comment]
All the console outputs above seem to be for perf counters tests. The last two have nice callstacks (as happily they timed out in RemoteExecutor) which show they are waiting for a pinvoke reading perf counters. The tests and product hasn't changed here. Are the machines overloaded?

**Comment by hoyosjs** [comment]
@sywhang any idea why this would happen?

**Comment by sywhang** [comment]
I don't own the System.Diagnostics.PerformanceCounter APIs. I believe that is @Anipik?

**Comment by danmosemsft** [comment]
@hoyosjs as noted above, there have been no changes to this code: it appears that the OS calls to read perf counters have been timing out. This could happen eg., if the machine is overloaded. Have there been any changes to the configuration of these machines? @jaredpar ?

**Comment by hoyosjs** [comment]
@danmosemsft The helix queue names for the timed out Windows jobs haven't changed in a while - 17 days - a month: https://github.com/dotnet/runtime/blame/master/eng/pipelines/libraries/helix-queues-setup.yml

However, there was a helix rollout on 2/26. I know these updated the base SKUs for Windows Server as described on https://github.com/dotnet/core-eng/issues/8973. I don't know if this could have this impact or if anything like this has been reported.

**Comment by tarekgh** [comment]
I have submitted the PR https://github.com/dotnet/runtime/pull/33410 which will avoid running one of the perf counters tests that consume a lot of time. Hopefully, this will help here.

**Comment by jaredpar** [comment]
@tarekgh thanks. This is hitting often enough we should be able to verify that fixes the issue pretty quickly.

**Comment by ericstj** [comment]
@jaredpar how does the data look on this?  I tried to look at failing instances of `System.Diagnostics.PerformanceCounter.Tests` work item in AzDo and didn't notice any timeouts, but there's a lot of noise in here from a couple busted draft PRs.

**Comment by jaredpar** [comment]
Closing as this hasn't come up in recent builds.
