### ISSUE TITLE
[Bug ?] Value tuple get an extra member when it has more then 8 members.

### ISSUE THREAD

**Issue by RevensofT** [dotnet/runtime#33299]
## Bug issue

I use pointer to read value of each member in value tuple but I found out it got an extra member on every 8th member.

Ex.
VTuple_input = (1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 8, 6, 5, 4, 3, 2, 1)
output = (1, 2, 3, 4, 5, 6, 7, 0, 8, 9, 9, 8, 7, 8, 6, 0, 5, 4, 3, 2, 1, 0)

Also size of VTuple_input is 88 byte instead 76 byte.

However, I'm not sure is this intention to leave zero for split every value tuple in merged value tuple ? I know value tuple limit at 8 member per tuple, if more then that compiler will split and merge it; so is this a bug or not ?

Here is my test code for prove an issue but you can re create issue by simple create an value tuple with more then 8 members and check size of it or create a pointer of first member and move it till last member.
![image](https://user-images.githubusercontent.com/7234852/76110818-c7bd3d80-6011-11ea-961f-f98c183821f6.png)

**Comment by stephentoub** [comment]
Closing as answered.

**Comment by RevensofT** [comment]
Thanks @bartonjs, very strange for value type to be auto layout,.

**Comment by stephentoub** [comment]
> very strange for value type to be auto layout

It's not that strange.
```C#
using System;
using System.Runtime.InteropServices;

class Program
{
    static void Main()
    {
        Console.WriteLine("Sequential: " + MeasureSize(() => new ClassWithSequentialLayoutTuple()));
        Console.WriteLine("Auto:       " + MeasureSize(() => new ClassWithAutoLayoutTuple()));
    }

    static long MeasureSize<T>(Func<T> func)
    {
        const int Count = 1000;
        long before = GC.GetAllocatedBytesForCurrentThread();
        for (int i = 0; i < Count; i++) func();
        return (GC.GetAllocatedBytesForCurrentThread() - before) / Count;
    }
}

class ClassWithAutoLayoutTuple
{
    public AutoLayoutTuple<long, bool, long, bool, long, bool, long> Value;
}

class ClassWithSequentialLayoutTuple
{
    public SequentialLayoutTuple<long, bool, long, bool, long, bool, long> Value;
}

[StructLayout(LayoutKind.Auto)]
internal struct AutoLayoutTuple<T1, T2, T3, T4, T5, T6, T7>
{
    public T1 Item1;
    public T2 Item2;
    public T3 Item3;
    public T4 Item4;
    public T5 Item5;
    public T6 Item6;
    public T7 Item7;
}

[StructLayout(LayoutKind.Sequential)]
internal struct SequentialLayoutTuple<T1, T2, T3, T4, T5, T6, T7>
{
    public T1 Item1;
    public T2 Item2;
    public T3 Item3;
    public T4 Item4;
    public T5 Item5;
    public T6 Item6;
    public T7 Item7;
}
```

**Comment by RevensofT** [comment]
Thanks @stephentoub, so value tuple use auto layout for optimize when use with class.
