### ISSUE TITLE
Can we ignore CLSCompliantAttribute in our APICompat comparisons

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#33316]
This attribute creates a ton of noise between ref/src differences and current/past differences.  Depending on what the assembly level / type settings are we see differences.

We rarely care about the differences and they generate noise in our baseline files.

So: should we ignore these or should we care more?  Follow up question: do we even care about using the attribute any more?

@terrajobst @stephentoub @jkotas @joperezr @danmosemsft

**Comment by danmosemsft** [comment]
I do not know why we use the attribute at all.

**Comment by joperezr** [comment]
I believe we probably don't but the compiler cares about it once someone is trying to use our APIs from a different language and trying to build a CLS compliant library.

**Comment by danmosemsft** [comment]
@jaredpar ?

**Comment by jkotas** [comment]
These attributes should be fine to ignore for API compat. They really only exist to make the compilers happy.

BTW: I am deleting number of redundant CLSCompliantAttributes in https://github.com/dotnet/runtime/pull/33326

**Comment by ericstj** [comment]
Ok. I’m planning to fork the attribute exclusions for genapi vs apicompat.  Since they are separate concerns. GenAPI will still need CLSCompliant so that we don’t have to manually maintain the attributes after regenerating ref cs.

**Comment by ericstj** [comment]
Fixed in #33300
