### ISSUE TITLE
CoreCLR product build on Linux fails in Initialize job due to access denied

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#33312]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=549999&view=logs&j=94ace3f6-c714-5cff-e8e5-0680920d3f7c&t=66ef0891-4e1f-542b-423c-e03b9751fda9

Diagnostic output:

<pre>

Initialize job

View raw log
Starting: Initialize job
Agent name: 'NetCorePublic-Pool 101'
Agent machine name: 'a00067I'
Current agent version: '2.165.0'
Agent running as: 'helixbot'
Prepare build directory.
##[error]One or more errors occurred. (One or more errors occurred. (Access to the path '/datadisks/disk1/workspace/_work/1/s/artifacts/bin/Microsoft.Extensions.DependencyModel.Tests/Debug/netcoreapp5.0/Microsoft.DotNet.InternalAbstractions.dll' is denied.)) (One or more errors occurred. (Access to the path '/datadisks/disk1/workspace/_work/1/s/artifacts/bin/Microsoft.Extensions.DependencyModel.Tests/Debug/netcoreapp5.0/xunit.execution.dotnet.dll' is denied.)) (One or more errors occurred. (Access to the path '/datadisks/disk1/workspace/_work/1/s/artifacts/bin/Microsoft.Extensions.DependencyModel.Tests/Debug/netcoreapp5.0/it/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll' is denied.)) (Access to the path '/datadisks/disk1/workspace/_work/1/s/artifacts/bin/Microsoft.Extensions.DependencyModel.Tests/Debug/netcoreapp5.0/Microsoft.DotNet.InternalAbstractions.dll' is denied.) (Access to the path '/datadisks/disk1/workspace/_work/1/s/artifacts/bin/Microsoft.Extensions.DependencyModel.Tests/Debug/netcoreapp5.0/xunit.execution.dotnet.dll' is denied.) (Access to the path '/datadisks/disk1/workspace/_work/1/s/artifacts/bin/Microsoft.Extensions.DependencyModel.Tests/Debug/netcoreapp5.0/it/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll' is denied.)
Finishing: Initialize job
</pre>

**Comment by trylek** [comment]
Looks like failure deleting locked test binaries from a previous run but that's just my Windows experience speaking, I don't know how exactly this works on Linux.

**Comment by trylek** [comment]
According to @jaredpar's statistics this seems to be hitting roughly 2% of our runs.

**Comment by MattGal** [comment]
Taking a look.   it's extra weird because if I don't have permissions to blow away that folder I generate totally new one.

**Comment by jaredpar** [comment]
Not seeing any recent occurences of this issue so closing out. 

The search I used is the following:

> runfo search-timeline -d runtime -c 300 -pr -v "Access to the path"
