### ISSUE TITLE
Static link the native libraries to the runtime

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#33311]
This issue intended to discuss if we need to static link the native libraries to the runtime to serve in one executable scenario. The discussion triggered by the comments https://github.com/dotnet/runtime/pull/33236#pullrequestreview-369991255. 

from @bartonjs 
This change, overall, makes me sad. We intentionally stripped off the lib prefix as part of "these aren't general purpose libraries, don't look here". But if we need to, we need to, I guess.

from @jkotas
The alternative may be to statically link these libraries into the runtime for Android where it is causing problems. We are going to have this option for single file flavor of CoreCLR anyway, so doing it for Android as well (or even everywhere) should not be a big deal.

from @tarekgh
CC @akoeplinger Alexander Köplinger FTE and @marek-safar Marek Safar FTE to be aware of the suggestion.

from @marek-safar
statically link these libraries into the runtime

Xamarin.Android does not support this mode. I think this would be nice but we won't be in a position to deliver this for .net5. This looks more like .net6 enhancement because we would need to do native linking during publish phase (this depends on Android NDK, etc).

/cc @jonpryor 

from @jkotas
For CoreCLR, the plan is to statically link the libraries as part of the dotnet/runtime build (see #32823). We are not planning to do native linking during publish phase.

from @marek-safar
That won't work for us. The thinking right now is to copy the dynamic libs which are used (during publish) and extend that to full static linking for Android as we plan to do for iOS (and wasm) during publish

from @jkotas
Just curious - why it does not work for you?

from @marek-safar
Primary because of size. If an app uses no crypto we should not link libSystem.Net.Security.Native and you can apply that to all native libs where System.IO.Compression.Native is probably the biggest one.

from @stephentoub
The moment someone brings in any managed HTTP implementation, client or server, it's going to end up requiring both of those. Presumably then the size concern would only be if they were using a platform-specific implementation (e.g. AndroidHttpHandler) where the platform provided all of that support?

**Comment by lpereira** [comment]
Considering that, at least on ELF systems, these static libraries would have to be linked with `-whole-archive` (as the native linker has no way of knowing that those symbols are going to be called by managed code), the only way to shake the tree and get a reasonable-sized binary would be to trace all calls made by the application down to the P/Invokes into these native libraries, and tell the native linker (maybe `--retain-symbols-file` for GNU ld/LLVM linker?) the name of all the symbols that need to be kept (or, at the very least, to determine which static libraries to link with- and without `-whole-archive` and let the linker shake the tree at its leisure). This would require the SDK user to have a native linker in their setup, though, and I don't know if this is a good idea.

**Comment by swaroop-sridhar** [comment]
I think this is a dup of  #32823

**Comment by agocke** [comment]
Dup of #37119
