### ISSUE TITLE
Provide a RID for WASM

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33327]
We need to provide a RID for WASM. My proposal is to call it `wasm`.

@ericstj I'm not sure if this node should be connected to anything in the RID graph, but my assumption is no. Also, is runtime the right repo or should this be moved elsewhere?

@rrelyea @marek-safar @mhutch @lewing @SteveSandersonMS @danroth27

**Comment by marek-safar** [comment]
Yes, this is right repo. We should clarify what RID will be the parent of wasm?

**Comment by ericstj** [comment]
So we currently have the RID `webassembly` with architecture `wasm` which derives from `unix`.

https://github.com/dotnet/runtime/blob/95b7248e9ba1a4552809c24cd571d5aa60d5af48/src/libraries/pkg/Microsoft.NETCore.Platforms.Future/runtimeGroups.props#L8-L11

If folks agree on this, we can promote it to the primary platforms package, it's currently in the *Future* package.

**Comment by marek-safar** [comment]
I don't think `unix` is right parent. What rid name do you suggest based on this, is it `webassembly1.0-wasm` ?

**Comment by ericstj** [comment]
The RIDs this generates are here: 
https://github.com/dotnet/runtime/blob/95b7248e9ba1a4552809c24cd571d5aa60d5af48/src/libraries/pkg/Microsoft.NETCore.Platforms.Future/runtime.json#L3-L16

What should be the parent?  Linux?  Nothing at all (peer of Unix/Win)?  Keep in mind that the RID parent here isn't likely to impact native assets since there won't be any with `wasm` architecutre.  It'll likely impact managed code.  Runtime libraries could be a case study, in the cases where we cross-compile which assets are most likely to work?  Does webassembly expose platform libs similar to Unix or Linux?

**Comment by marek-safar** [comment]
I think the parent should be either nothing at all (peer of Unix) or something WebAssembly specific (like wasm). It will depend on how the platform will evolve but I can imagine building managed libraries (under src/libraries) for two different RIDs where one is browser-based and one is WASI based where we have a dependency on system calls or we want to take advantage of the web environment.

The RID graph then could look like

```
		wasm
		/ 	\
wasm-wasi	wasm-browser
```

**Comment by ericstj** [comment]
Platform API availability / similarity is the thing to look at, also, where do we see our PAL.

For example the `Unix` lets us create a library PAL at this layer and implement it for each platform.  That way we have single IL and implement the differences in the system.native.* PAL.  Is a PAL at this layer feasible for `webassembly` or do you think it would need a totally different definition and therefor a parallel implementation for anything that cross-compiles between `win` and `unix` today?

**Comment by marek-safar** [comment]
> For example the Unix lets us create a library PAL at this layer and implement it for each platform. 

system.native.* PAL libraries won't be `unix` as they are compiled into native code which will be wasm byte code in our case. If there is a case where we have fully managed library which pinvokes into libc (and you consider libc to be unix) then both wasi and emscripten (wasm-browser) emulate it but the implementation is not 100% compatible. The same layer could emulate win32 API or other OS APIs.

We could start with Unix but I am worried that this will limit us in the future as we'll be forced to maintain unix compatibility for no good reason.

**Comment by ericstj** [comment]
> system.native.* PAL libraries won't be unix as they are compiled into native code

My point wasn’t the implementation of system.native PALs but the IL that uses them. Today this IL is “Unix” and we then implement the PAL on all concrete “Unix” compatible RIDs.  If you don’t derive from Unix and you want to use the IL that calls the system.native PALs then we will need to add `wasm` configuration.  Moreover we will need to do the same to every library that has a Unix or Linux configuration today. 

> I am worried that this will limit us in the future as we'll be forced to maintain unix compatibility

I’m not sure what “Unix” compatibility means.  These RIDs are really a limited way of conditional deployment, not really a concrete set of behaviors.  If a new platform comes along that’s a little different than past platforms that doesn’t mean it can’t be Unix. It just means Unix isn’t a sufficient way to target all platforms with a single implementation that notices this difference.  That library will need a specialized version for the new platform.  The outcome really isn’t any different than if that new platform was a peer to Unix: in either case the libraries that notice the difference need to cross compile for unix and the new platform.  Something you need to consider is how many characteristics of the platform are similar vs different than Unix. Will everyone still have to cross compile or will a large number of folks benefit from the similarities and use a single lib.  

You could throw data at this: analyze all nuget to find Unix-specific assets. Examine their pinvokes and determine if they are available on wasm.

I don’t really have a ton of opinion here but I want to make sure you understand the trade off and it’s implications.

**Comment by marek-safar** [comment]
I think I understand the tradeoff and that's why I think it's better to not have Unix as the base but use "any" or equivalent instead. We can revisit that later but if we choose the other way we won't. I don't have access to be able to analyze all nugets if they have managed assemblies under unix RID which could be valuable but even with that, we won't have time to make them work with wasm in this release.

**Comment by ericstj** [comment]
I see what you mean.  FYI to @stephentoub  on this.

So making wasm a peer of win/unix will mean that every library that cross-compiles by RID today must add a new configuration in order to support wasm.  It sounds like that's what you want.
