### ISSUE TITLE
JIT crash caused by late GetType() optimizations 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#33333]
Repro:

Compile and JIT w/ optimizations

```
using System;
using System.Runtime.CompilerServices;

sealed class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public object M()
    {
        return GetType2() == typeof(Program) ? base.ToString() : ToString();
    }

    Type GetType2() => GetType();

    static void Main(string[] args)
    {
        new Program().M();
    }
}
```

Result:

`Assert failure(PID 23416 [0x00005b78], Thread: 15036 [0x3abc]): Assertion failed 'OperIs(GT_NOP, GT_CALL, GT_COMMA) || OperIsCompare() || OperIsLong() || OperIsSIMD() || OperIsHWIntrinsic()' in 'Program:M():System.Object:this' during 'Lowering nodeinfo' (IL size 37)`

Release build hits AV later

More context: https://github.com/dotnet/corert/issues/6729#issuecomment-595956648

**Comment by jkotas** [comment]
The problem is that late `GetType()` optimizations produce IR that goes straight to lowering, but that lowering is not able to handle.

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib

**Comment by EgorBo** [comment]
Ah, I guess that was me in https://github.com/dotnet/runtime/pull/32790/ 🙁

**Comment by AndyAyersMS** [comment]
The problematic IR is a comma under a JTRUE:
```
Optimizing compare of obj.GetType() and type-from-handle to compare method table pointer
GenTreeNode creates assertion:
               [000041] ---X--------              *  NULLCHECK byte  
In BB01 New Local Constant Assertion: V00 != null index=#01, mask=0000000000000001

fgMorphTree BB01, STMT00001 (after)
[000007] ---XG+------              *  JTRUE     void  
[000042] ---X-+------              \--*  COMMA     int   
[000041] ---X-+------                 +--*  NULLCHECK byte  
[000000] -----+------                 |  \--*  LCL_VAR   ref    V00 this         
[000040] -----+------                 \--*  CNS_INT   int    1
```
You might imagine something would clean this up, but nothing does.

Related: see workarounds to avoid creating this kind of IR in `optVNConstantPropOnJTrue`.

**Comment by AndyAyersMS** [comment]
@EgorBo worked up some ideas on how to fix this in `fgFoldConditional` -- see [here](https://github.com/dotnet/runtime/compare/master...AndyAyersMS:PlausibleFixFor33333).

**Comment by EgorBo** [comment]
Ok, working on test cases

**Comment by briansull** [comment]
Looks very similar to #33091
