### ISSUE TITLE
Remove some WinRT code that was replaced by the new ComWrappers API.

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#33330]
The [ComWrappers API](https://github.com/dotnet/runtime/issues/1845) provides a different approach for WinRT support and therefore some code within the runtime can be removed.

See https://github.com/dotnet/runtime/pull/32091

/cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
We could also use the new "Better Obsoletion" (#33360) mechanism to mark the features as obsolete before removing them.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky In this case, the work item was really for some implementation code for the built-in RCW/CCW, but the .NET public API could definitely be updated as well. Good suggestion.
