### ISSUE TITLE
Utf8Formatter.TryFormat causes massive code bloat when used with a constant StandardFormat

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/runtime#33349]
The following function compiles to ~900 bytes of code when jitted on x64.

```cs
private static bool Format(Span<byte> span, int value)
{
    return Utf8Formatter.TryFormat(value, span, out _, new StandardFormat('D', 2));
}
```
Adding `AggressiveInlining` to `StandardFormat.ctor` allows the JIT to reduce the `TryFormat` call to a single call to `TryFormatUInt64D`, resulting in a code size of less than 100 bytes.

**Comment by EgorBo** [comment]
This change: https://github.com/EgorBo/runtime-1/commit/b7f15b74722ac1065e5c5d7ecac985b3347b4df3

makes `StandardFormat.ctor` inlineable 😄 
(And it seems it does make sense to make it so since it's mostly used with constant arguments)

**Comment by jkotas** [comment]
>  TryFormatUInt64D, resulting in a code size of less than 100 bytes

That is still very questionable. Some of the AggressiveInlining in the Utf8Formatter code should be deleted.

**Comment by GrabYourPitchforks** [comment]
I agree that some of the _AggressiveInlining_ attributes should disappear. The tricks I was playing around with over at https://github.com/dotnet/runtime/pull/32843 and Andy's WIP PR should also be generally applicable here, which could further reduce the codegen size around the switch statement.

**Comment by Thealexbarney** [comment]
Ideally all the dispatch code in TryFormatUInt64/TryFormatInt64  would disappear if the format was a constant. AggressiveInlining can't differentiate between the case of using a constant or not, so the entire TryFormatUInt64 function would always be inlined in non-constant cases.

I'd say that TryFormatUInt64Default should definitely not have AggressiveInlining if TryFormatUInt64 also has AggressiveInlining. TryFormatUInt64Default's child functions should keep AggressiveInlining since they would be inlined twice at most throughout the entire program.
