### ISSUE TITLE
pal::get_own_executable_path() does not work properly with hardlink on FreeBSD 

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#3335]
This popped out when trying to run corefx tests on FreeBSD.

```
[furt@toweinfu-d11 ~/git/wfurt-corefx]$ ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet --info
A fatal error occurred, the folder [/usr/home/furt/git/wfurt-corefx/artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/host/fxr] does not exist 
```

```
[furt@toweinfu-d11 ~/git/wfurt-corefx]$ find . -samefile ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet
./artifacts/bin/runtime/netcoreapp-FreeBSD-Debug-x64/dotnet
./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/dotnet
./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet
```
```
[furt@toweinfu-d11 ~/git/wfurt-corefx]$ find . -samefile ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet | xargs sha1
SHA1 (./artifacts/bin/runtime/netcoreapp-FreeBSD-Debug-x64/dotnet) = 5c9d06af2aabd85201acbc777a045de6f048037b
SHA1 (./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/dotnet) = 5c9d06af2aabd85201acbc777a045de6f048037b
SHA1 (./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet) = 5c9d06af2aabd85201acbc777a045de6f048037b
```
we have three identical versions with hardlinks.

Copying dotnet binary instead of using hardlink fixes the problem:
```
rm ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet
cp ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/dotnet ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet
[furt@toweinfu-d11 ~/git/wfurt-corefx]$ ./artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/dotnet --info
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

Host (useful for support):
  Version: 3.0.0-preview-27112-01
  Commit:  84f1c402cf

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 9.9.9 [/usr/home/furt/git/wfurt-corefx/artifacts/bin/testhost/netcoreapp-FreeBSD-Debug-x64/shared/Microsoft.NETCore.App]
```

At this point, this seems to cause troubles only with our test infrastructure. 
https://github.com/dotnet/corefx/blob/3ede762e6ed6bd9f27bdc37f85cfe8ee02cddceb/external/runtime/runtime.depproj#L107

Setting this to false for FreeBSD should workaround observed issue. 

cc: @bartonjs

**Comment by am11** [comment]
@wfurt, I realize that this is an old issue that was ported from (now-archived) dotnet/core-setup repository.

Does this issue reproduce with runtime's main branch or .NET 6? I'm asking because in .NET 6, we consolidated different implementations of "get self executable path" for various platforms across the runtime repo. The FreeBSD implementation looks like this:  https://github.com/dotnet/runtime/blob/24714ef76bad58d04e014f9a7496035a407ed800/src/native/minipal/getexepath.h#L48 if it is still missing hard link support (which I hope is not the case), fixing this issue will fix it for other use-cases as well (https://grep.app/search?q=getexepath&regexp=true&case=true&filter[repo][0]=dotnet/runtime), including `System.Environment.ProcessPath` public API which was introduced in .NET 6.

If it does not reproduce anymore, we can close this issue as fixed in 6.0 milestore.

cc @Thefrank

**Comment by Thefrank** [comment]
Not sure how the original runtime was generated but this was with:
`./build.sh -c Release -ci /p:OFFICIALBUILDID=20220508.99`
and
```diff
diff --git a/src/libraries/externals.csproj b/src/libraries/externals.csproj
index 969ed9603a2..040bf750136 100644
--- a/src/libraries/externals.csproj
+++ b/src/libraries/externals.csproj
@@ -29,8 +29,6 @@
           AfterTargets="AfterResolveReferences">
     <PropertyGroup>
       <UseHardlink>true</UseHardlink>
-      <!-- workaround core-setup problem for hardlinking dotnet executable to testhost: core-setup #4742 -->
-      <UseHardlink Condition="$(PackageRID.StartsWith('freebsd'))">false</UseHardlink>
     </PropertyGroup>
 
     <!-- We do not need apphost.exe.
```
It looks ok:
```
root@dotnet6:~/runtime # ./artifacts/bin/testhost/net6.0-FreeBSD-Release-x64/dotnet --info

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.3 [/root/runtime/artifacts/bin/testhost/net6.0-FreeBSD-Release-x64/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
```
root@dotnet6:~/runtime # find . -samefile ./artifacts/bin/testhost/net6.0-FreeBSD-Release-x64/dotnet | xargs sha1
SHA1 (./artifacts/bin/testhost/net6.0-FreeBSD-Release-x64/shared/Microsoft.NETCore.App/6.0.3/dotnet) = e51ba8bd5547d74336954e56b2cc29f02a47d212
SHA1 (./artifacts/bin/testhost/net6.0-FreeBSD-Release-x64/dotnet) = e51ba8bd5547d74336954e56b2cc29f02a47d212
SHA1 (./artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/dotnet) = e51ba8bd5547d74336954e56b2cc29f02a47d212
SHA1 (./.packages/runtime.freebsd-x64.microsoft.netcore.dotnethost/6.0.0/runtimes/freebsd-x64/native/dotnet) = e51ba8bd5547d74336954e56b2cc29f02a47d212

**Comment by am11** [comment]
@Thefrank, thanks for quickly testing it. Would you like to submit that as a PR to close this issue? :)

I believe the documented errors from link(2), which msbuild eventually uses [here](https://github.com/dotnet/msbuild/blob/72a07679401d1272d70ce482ea03c109ddd6e601/src/Tasks/NativeMethods.cs#L814) are acceptable.

https://www.freebsd.org/cgi/man.cgi?query=link&sektion=2
```
     [EXDEV]		The link named by name2	and the	file named by name1
			are on different file systems.
```

(EXDEV is also applicable to macOS and linux)

**Comment by wfurt** [comment]
I think it is ok to close if it does not manifest in any bad way. And yes, cross-device would fail on all Unixes.  
The System.Environment.ProcessPath would be interesting. Since hardline is essentially same file, I'm not sure if we would be able to distinguish. I guess on Linux we can get it vie /proc.

**Comment by Thefrank** [comment]
I did not get any new test failures from the above patch on top of net7 (main/HEAD@5ecaae992806a2d422157a095a63efb467365f54).

 I guess something, somewhere else, at a different point resolved the hardlink issue?

If nothing other than removing the FreeBSD exception for hardlinking is need then I will go ahead an make a PR to close this issue

**Comment by am11** [comment]
This issue was reported on Nov 12, 2018, so it is most likely produced on FreeBSD 11, whereas presumably your tests ran on FreeBSD 12 (released December 11 2018) or 13? Might have been fixed by the platform update?

The consolidation work was done in https://github.com/dotnet/runtime/commit/05cd29c81434aae62d0cb680768d0229c8da0d2d. Our mib arguments haven't changed since: https://github.com/dotnet/runtime/commit/05cd29c81434aae62d0cb680768d0229c8da0d2d#diff-7566e3c5f8e9197b0e37e6be66c937a909a14a650d0a049e298fe839b32b8786L814 vs. https://github.com/dotnet/runtime/blob/24714ef76bad58d04e014f9a7496035a407ed800/src/native/minipal/getexepath.h#L49

**Comment by wfurt** [comment]
Closing for now as it seems to work. We can reopen (or create new issue) if needed.

**Comment by am11** [comment]
https://github.com/dotnet/core-setup/issues/4742 is this issue which this comment is referring to https://github.com/dotnet/runtime/blob/24714ef76bad58d04e014f9a7496035a407ed800/src/libraries/externals.csproj#L43-L44 we should delete this workaround since issue is closed..
