### ISSUE TITLE
Add overload System.Text.Encoding.GetBytes(ReadOnlySpan<char> chars)

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#33352]
System.Text.Encoding.GetBytes is missing an overload to accept ReadOnlySpan<char> as input. It would be nice if this can be added.

```
void DoStuff(ReadOnlySpan<char> text) {
	var bytes = Encoding.UTF8.GetBytes(text);
	namedPipeClient.WriteBytes(bytes);
}
```
instead of
```
void DoStuff(ReadOnlySpan<char> text) {
	var bytes = Encoding.UTF8.GetBytes(text.ToString());
	namedPipeClient.WriteBytes(bytes);
}
```

**Comment by stephentoub** [comment]
It does have an overload that takes a span. It just takes two spans: the input and the space to write the output.
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getbytes?view=netcore-3.1#System_Text_Encoding_GetBytes_System_ReadOnlySpan_System_Char__System_Span_System_Byte__

**Comment by Symbai** [comment]
How do I know the size of the bytes of a particular encoding so I can allocate the bytes it uses? The first two overloads seems to be much easier to use like in my example above.

**Comment by stephentoub** [comment]
You can either get the exact amount with GetByteCount or a potential overestimate with GetMaxByteCount. The purpose of the span-based overloads is to avoid allocations, whereas the API you propose still needs to allocate a byte[].
