### ISSUE TITLE
Test Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh failed with Assert failure(PID 1006 [0x000003ee], Thread: 1006 [0x03ee]): (GetComponentSize() <= 2) || IsArray()

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#33366]
**Job:**
[runtime-coreclr gcstress0x3-gcstress0xc:20200308.1](https://dev.azure.com/dnceng/public/_build/results?buildId=551522&view=results)

**Error message:**
```
Assert failure(PID 1006 [0x000003ee], Thread: 1006 [0x03ee]): (GetComponentSize() <= 2) || IsArray()
File: /__w/18/s/src/coreclr/src/vm/methodtable.cpp Line: 7837
 Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh: line 275: 1006 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.output.txt
Raw output:
BEGIN EXECUTION\n/root/helix/work/correlation/corerun Base01b_seq_ser.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1006.dmp
Written 49307648 bytes (12038 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
Expected: True
Actual: False
```
**Stack trace:**
`
at Loader_classloader._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_sh() in /__w/17/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs:line 10713
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=551522&view=ms.vss-test-web.build-test-results-tab&runId=17415558&paneView=debug&resultId=102366

category:correctness
theme:testing
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment]
@janvorli Can you triage?

**Comment by janvorli** [comment]
Looks like a GC hole - my guess is that the MethodTable is corrupted.

**Comment by AriNuer** [comment]
Test `Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh` failed again here [runtime-coreclr gcstress0x3-gcstress0xc:20200329.1](https://dev.azure.com/dnceng/public/_build/results?buildId=578587&view=results)
**Error message:**
```
Assert failure(PID 215 [0x000000d7], Thread: 215 [0x00d7]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
File: /__w/1/s/src/coreclr/src/vm/object.cpp Line: 557
Image: /root/helix/work/correlation/corerun\n\n/root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh: line 275: 215 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.output.txt\nRaw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun Base01b_seq_ser.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.215.dmp\nWritten 49332224 bytes (12044 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
Expected: True
Actual: False
```
**Stack trace:**
```
at Loader_classloader._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs:line 10713
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=578587&view=ms.vss-test-web.build-test-results-tab&runId=18178846&resultId=100875&paneView=debug

**Comment by BruceForstall** [comment]
Failing in GCStress=C for Linux x64/arm64/arm32:
https://dev.azure.com/dnceng/public/_build/results?buildId=578587&view=ms.vss-test-web.build-test-results-tab

for these tests:
```
Loader/classloader/generics/Layout/General/Base01b_seq/Base01b_seq.sh
Loader/classloader/generics/Layout/General/Base01d_seq_ser/Base01d_seq_ser.sh
Loader/classloader/generics/Layout/General/Base01c_seq_ser/Base01c_seq_ser.sh
Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
```

**Comment by AndyAyersMS** [comment]
I can repro the failure in Base01b_seq_ser.sh (0xC gc stress, no other env settings) on Linux x64.
```
Assert failure(PID 22990 [0x000059ce], Thread: 22990 [0x59ce]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /home/andy/repos/runtime/src/coreclr/src/vm/object.cpp Line: 557
    Image: /home/andy/repos/runtime/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root/corerun
```
At first look this seems to go bad during a gc in `Test..cctor` when the stack walk looks to be incomplete. Logical stack at this point is
```
Test..cctor
Test.EvalBoolean
GenInt.VerifyLayout   ;; untracked "this" gc ref at rbp-8
Test.Main
```
From the stresslog, GC only seems to enumerate references in the topmost managed frame. There are some transition/helper frames below that so perhaps stackwalking gets thrown off there. 
Note without GC stress we would normally not gc from this cctor.

Assertion failure is a bit downstream from , when VerifyLayout virtually calls string equals on a field of its `this` and that reference fails validation in the prestub. Presumably failure to scan the refs in `VerifyLayout` is the proximate cause.

Will debug the stackwalk next.

**Comment by AndyAyersMS** [comment]
Also fails at the same spot with
```
COMPlus_JITMinOpts=1
COMPlus_GCStress=0x1
COMPlus_TieredCompilation=0
```
which might be a bit easier to debug.

**Comment by AndyAyersMS** [comment]
More detailed logging shows the stack walk is ok, and we're reporting the `this` reference in `GenInt.ValidateLayout` to the GC, but it looks almost as if the GC is not scanning the GC refs in the object, so they become invalid at some point.

Wondering if there's something amiss in the class loader for this case. From what I cant tell, `ContainsPointers` is not true for the `GenInt` class but is true for its parent class.

**Comment by AndyAyersMS** [comment]
For future reference, to dump the CDCDesc on Linux you can call a method in the debugger, but you need to have logging enabled first.
```
(lldb) exp -- (MethodTable*)  0x00007fff7cfb7300
(MethodTable *) $1 = 0x00007fff7cfb7300

(lldb) exp -- $1->DebugDumpGCDesc("GenInt", 0)
GC description for 'GenInt':

(lldb) exp -- (MethodTable*) 0x00007fff7cfb7140
(MethodTable *) $3 = 0x00007fff7cfb7140

(lldb) exp -- $3->DebugDumpGCDesc("GenBase`1[Int32]", 0)
TID 09c2: GC description for 'GenBase`1[Int32]':

TID 09c2: GCDesc:
TID 09c2:    offset     8 (0 w/o Object), size   -88 (   16 w/o BaseSize subtr)
TID 09c2:
```

If I remove the SequentialLayout attribute from `GenInt` and its base class, then the method table flags for `GenInt` show it has pointers: `0x1000200`. So it would seem something about that attribute is messing up propagation of gc descriptors during class loading.

This doesn't look like a codegen issue. @jkotas can you help route this to the right person?

**Comment by davidwrighton** [comment]
@AndyAyersMS  This bug is a basic typesystem bug. We should send it to @fadimounir

**Comment by AndyAyersMS** [comment]
Same underlying issue is there on windows but the test doesn't fail; guess we get lucky.

**Comment by fadimounir** [comment]
I guess the GC needs to relocate the object in question in order for the process to hit the AV. I've seen cases like this before.
To make sure I understand your analysis @AndyAyersMS, we're reporting some root object, but when GC traverses the fields, it misses one of them due to a bug somewhere (either gcinfo or field layout), correct?

**Comment by AndyAyersMS** [comment]
Right, the jit GC info seems correct, and GC scans the `GenInt` object, but apparently does not think that object contains GC refs -- while in actuality it has two string fields. So those fields eventually become bogus.

**Comment by davidwrighton** [comment]
In particular, @AndyAyersMS told me offline that the ContainsPointers bit wasn't set on the MethodTable, so possibly its just a bug around ContainsPointers inheritance, or a problem with that and GCDesc creation.

**Comment by fadimounir** [comment]
Ok thank you for the context and information you gathered so far. I will take a closer look at why the ContainsPointers bit wasn't set

**Comment by AndyAyersMS** [comment]
Same details above in the LLDB spew...
```
(lldb) exp -f hex -- *(MethodTable*)0x00007fff7cfa7300    // GenInt 
(MethodTable) $4 = {
  m_dwFlags = 0x00000200      // ContainsPointers not set

(lldb) exp -f hex -- *(MethodTable*)0x00007fff7cfa7140    // GenInt's parent class
(MethodTable) $5 = {
  m_dwFlags = 0x01000210      // ContainsPointers set
```
