### ISSUE TITLE
[Meta] List of APIs considered for "Better Obsoletion"

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/runtime#33360]
# Rationale

Immo Landwerth (@terrajobst) has proposed a mechanism to improve obsoleting APIs by extending `ObsoleteAttribute`, affectionally known as [Better Obsoletion](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/better-obsoletion.md). Recently, that proposed addition [was merged into the framework](https://github.com/dotnet/runtime/pull/33248) and the compilers honor the new properties as of dotnet/roslyn#42518. In light of this, it seems like a good idea to gather a list of APIs that should be considered for Better Obsoletion, so there's a central place to discuss/review/suggest these.

## Obsolete APIs

This list is by no means exhaustive, but it'll kickstart the discussion.

The three examples from the design doc:
* `SecureString` - #30612
* `HttpWebRequest` (and related) - #33125
* Non-generic collections - (no issue)

A quick search for 'obsolete' in dotnet/runtime revealed these:
* `Uri.EscapeUriString` - #31387
  * [This comment](https://github.com/dotnet/runtime/issues/32606#issuecomment-595333169) by @karelz mentions there's a few other bad APIs on `Uri`, but doesn't specify which.
* `Assembly.CodeBase` - #31127
* `RuntimeHelpers.OffsetToStringData` - #31406
* ~~`Thread.Abort` - #28664~~ (Handled in dotnet/designs#139)
* `IAsyncResult` - #27936
* `HandleProcessCorruptedStateExceptionsAttribute` - #31157
* `BinaryFormatter` - #29976
* `StringDictionary` - #889
* ~~UTF-7 Encoding - #32284~~ (Handled in #37535)
* ~~`PrincipalPermissionAttribute` (and related) - #31279~~ (Handled in dotnet/designs#139)

Other APIs to be considered:
* `implicit operator DateTimeOffset(DateTime)` - #32954
* `UnmanagedType.AnsiBStr` (and a few others) - #31006
  * These values are already marked obsolete, but it would be an improvement to give them a dedicated diagnostic ID.

**Comment by Kryptos-FR** [comment]
There was an issue I opened a while ago regarding `ArrayList` in .Net Standard (https://github.com/dotnet/standard/issues/296).

Which leads me to the question: would that obsoletion also be applied to the standard, or only to .NET5?

**Comment by Joe4evr** [comment]
@Kryptos-FR The idea of .NET Standard was to unify the API surface area across multiple implementations of the .NET runtime. With .NET 5 being the unification of those to a single runtime implementation, the purpose of .NET Standard loses its meaning in that new world.

As such, don't hold your breath on the Standard still evolving.

**Comment by jeffhandley** [comment]
We created https://github.com/dotnet/designs/pull/139, which includes a few APIs mentioned here.

**Comment by slavanap** [comment]
Can I obsolete specific objects from _another library (including .NET itself)_ in my project, if they aren't obsoleted in their source?

**Comment by chucker** [comment]
You can write an analyzer. Consider forking https://github.com/dotnet/platform-compat

**Comment by slavanap** [comment]
@chucker is it correct if I would ever want to restrict some API usages in my project, I would need to build custom analyzer for it which I would later use for code check?

**Comment by Joe4evr** [comment]
@slavanap For code that you own, you can simply apply `[Obsolete]` with your own value for the new `DiagnosticId` property.

**Comment by slavanap** [comment]
What about the case when I want to restrict usage of implicit operator, code of which I do not own?

**Comment by jeffhandley** [comment]
> You can write an analyzer. Consider forking https://github.com/dotnet/platform-compat

Note that we are working to fully productize the `platform-compat` analyzer, to get it integrated into the .NET SDK for .NET 5.  It will use the new [`DiagnosticId` and `UrlFormat` properties on `[Obsolete]`](https://github.com/dotnet/runtime/pull/33248) and respect the new [`IsOSPlatformOrLater` and `IsOSPlatformEarlierThan` methods](https://github.com/dotnet/runtime/pull/39005).

Here's the [draft PR from @buyaa-n](https://github.com/buyaa-n/roslyn-analyzers/pull/3) if you're curious; we expect the PR into dotnet/runtime will be created within the next couple weeks.

@slavanap Other than including an analyzer in your package as was suggested, there isn't a way to cast `[Obsolete]` attributes onto APIs exposed from one of your dependencies (or the .NET Libraries).

**Comment by jeffhandley** [comment]
Ha -- my goodness, I got my wires crossed on the previous comment, @slavanap, and I referenced the wrong attributes that the Platform Compat Analyzer will be using.  I've fixed the comment above to be accurate.

**Comment by jeffhandley** [comment]
With the bulk of these issues now addressed, I'm going to close this issue. #46767 captured the obsoletions completed in .NET 6 and I filed #57207 to capture the remaining items from that list and this one for carrying forward into .NET 7.

Thanks for originally filing this, @Joe4evr--this was a big help to steer our efforts and shape our obsoletion work.
