### ISSUE TITLE
WebClient / HttpClient seems to have a DNS issue?

### ISSUE THREAD

**Issue by BobbyCannon** [dotnet/runtime#33362]
# DNS issue?

I have been having issue with WebClient and HttpClient. The issue is no matter what I do the call takes a minimum of 2 sec per request.

This code is slow is .NET Core 2.2 and 3.1 but the same code take an initial 2 secs on the first request but then is uber fast. The code always take a minimum of 2 second per loop on .NET Core

# General

```c#
[TestClass]
public class UnitTest1
{
	[TestMethod]
	public void TestMethod1()
	{
		var address = "http://127.0.0.1:9222/json";
		// This address being "localhost" is uber slow
		//var address = "http://localhost:9222/json";

		for (var i = 0; i < 4; i++)
		{
			var c = new System.Net.WebClient();
			c.DownloadData(address);
			//c.DownloadString(address);
		}
	}
}
```

TestMethod1 in .NET Core takes 8 sec
TestMethod1 in .NET 4.8.2 takes 2 sec

If I replace "localhost" with "127.0.0.1" then everything is uber fast in all platforms.

**Comment by scalablecory** [comment]
This will be resolved as part of https://github.com/dotnet/runtime/issues/861

**Comment by BobbyCannon** [comment]
> This happens because it is attempting to connect via IPv6 before IPv4. You can speed things up a bit by hosting your server on a dual-mode (IPv4 and IPv6) socket.

I'm not the host, I'm the client. I cannot control the host.

Now I notice that .NET FX 4.8 handles this well, .NET Core 2.2 and 3.1 does not. This is my focus. Why does this work so well on full framework but so poorly on .NET Core? 

I feel that .NET FX is caching the DNS?

**Comment by BobbyCannon** [comment]
BTW, "http://127.0.0.1:9222/json" is the Chrome / Edge debugger port. You would easily test this locally by starting Chrome and / or Edge (chromium) in debug.

1. Launch with the arguments of "--remote-debugging-port=9222" 
1. Create the client 
    1. var c = new System.Net.WebClient();
1. Download the JSON 
    1. c.DownloadData(address);

**Comment by scalablecory** [comment]
You can make things a lot better by creating a single instance of `HttpClient` and reusing it across multiple requests. This will use a pooled connection rather than re-establish the connection (which is what is taking a long time) for every loop.

**Comment by BobbyCannon** [comment]
> You can make things a lot better by creating a single instance of `HttpClient` and reusing it across multiple requests. This will use a pooled connection rather than re-establish the connection (which is what is taking a long time) for every loop.

The sample code is just a sample. The performance is an issue when using it in the real world. Example is TestR my open source automation project will use a separate connection per automation incident. That connection could be re-used in that instance but the problem is all tests will spin up a new instance of the automation connection. This means each test is still going to run into the issue.

However, I repeat that the .NET FX does not have an issue with this design / implementation. Once HttpClient is accessed in the .NET FX the next instance will perform like a boss. This is not he case in .NET Core.

**Comment by karelz** [comment]
Triage recommendation:
1. Loopback server can listen also on IPv6, which will make the problem go away on dev machines
2. Use `HttpClient` cached instead of per-request as recommended above (general `HttpClient` guidance)
3. For IPv4-only servers we will eliminate the perf problem by Happy Eyeballs - #861

Closing as resolved [1] and [2] / duplicate [3]

**Comment by BobbyCannon** [comment]
@karelz Question on Triage 2. Is HttpClient threadsafe? If so then I could create a static instance and reuse it and I'll be fine. However if not then is this really a valid solution?

**Comment by stephentoub** [comment]
> Is HttpClient threadsafe? If so then I could create a static instance

Yes, and that is the recommended usage.
