### ISSUE TITLE
JsonSerializerOptions.IgnoreNullValues=true causes JsonConverter override to never be called

### ISSUE THREAD

**Issue by pasisavolainen** [dotnet/runtime#33369]
Tried to override null-ignore behavior on some individual cases where it makes sense, but no such luck.

My reasonable expectation is that if a property has converter specified (and converter gets the converter options), then the converter would be called on all and any values that the property is. However the `IgnoreNullValue = true` causes the converter to never be called and to be unable to make the decision in application.

example:
```csharp
    internal class KeepNullsConverterExample : JsonConverter<string>
    {
        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => throw new NotImplementedException();

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString());
    }
    class TestObject
    {
        [JsonConverter(typeof(KeepNullsConverterExample))]
        public string Foo { get; set; }
    }
    public class OptionItemTests
    {
        [Fact]
        public void NullValueSurvives()
        {
            var items = new TestObject[]
            {
                new TestObject{ Foo = "a" },
                new TestObject{ Foo = null},
            };

            var jsonOptions = new JsonSerializerOptions
            {
                IgnoreNullValues = true,
            };

            var json = JsonSerializer.Serialize(items, jsonOptions);

            var expected = "[{\"Foo\":\"a\"},{\"Foo\":null}]";

            Assert.Equal(expected, json);
        }
    }
```

**Comment by layomia** [comment]
We currently don't pass `null` to user converters, so even if `IgnoreNullValues` was `false` in your scenario, the converter's write method would still not be called. For 5.0, we are likely to add a `bool` property on `JsonConverter` (as part of work in https://github.com/dotnet/runtime/issues/1562), say `HandleNullValues` (defaults to `false`) for converter's to opt in to handle `null` tokens. cc @steveharter.

New semantics need to be added for a property not to be ignored when `IgnoreNullValues` is `true`. This seems like a good candidate for the `Never` condition on the new `JsonIgnoreCondition` property being proposed in https://github.com/dotnet/runtime/issues/30687. Your class definition could look like this:

```C#
class TestObject
{
    [JsonConverter(typeof(KeepNullsConverterExample))]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Foo { get; set; }
}
```

**Comment by layomia** [comment]
Closing as duplicate - https://github.com/dotnet/runtime/issues/34439 tracks providing an opt-in for converters to handle `null`, and properties can be excluded from being ignored using `JsonIgnoreCondition.Never` introduced in https://github.com/dotnet/runtime/issues/30687.
