### ISSUE TITLE
Issue: Multiple levels Json Deserialization with System.Text.Json.JsonSerializer API

### ISSUE THREAD

**Issue by Sandeep321** [dotnet/runtime#33376]
A couple of issues with the current implementation of Serialization/DeSerialization:
1.  We need to specify the JsonSerializerOptions everywhere we do the DeSerialization. It makes migration of existing projects to .Net core 3.1.0 very tricky and cumbersome. I really wonder if it's worth that much refactors. There is a workaround to fix it in one place but it would be nice if that comes from the .Net core team.
2. Next is even if I use the correct JsonSerializerOptions for DeSerialization, first-level properties get deserialized correctly but not the next level complex JSON objects. It works all fine with Newtonsoft JSON. This could be related to this [Issue](https://github.com/dotnet/runtime/issues/31015)

Are these known issues and do we have any workaround for these?

**Comment by layomia** [comment]
There's an issue to be able to specify the serializer's global options: https://github.com/dotnet/runtime/issues/31094. This will solve the issue of specifying the options everywhere.

Populating collections without setters is currently not supported. There's an issue tracking this: https://github.com/dotnet/runtime/issues/30258.

I'll close this as a duplicate. @Sandeep321 in the future, please create different issues for different concerns so we can properly track issues.
