### ISSUE TITLE
Create Debian/Ubuntu packages compatible with update-alternatives

### ISSUE THREAD

**Issue by ruimaciel** [dotnet/runtime#3338]
Currently, the official .net core installer for Debian/Ubuntu is designed to keep a single version installed.  This approach poses some problems to users who want or need to run multiple versions of the .net core platform in their system.  This will be particularly useful when v2.2 and v3.0 of the .net core platform are released.

Debian/Ubuntu supports installing and managing multiple versions of the same base package through [Debian's alternatives system](https://wiki.debian.org/DebianAlternatives).  With Debian's alternatives systems, users are able to select which alternative version of a package should be the system's default/preferred version, and thus run multiple versions of the same package concurrently and independently.  

With this in mind, it would be very helpful if future packages of the .net core platform for Debian/Ubuntu would integrate Debian's alternatives system to help end users try out and run multiple versions of the .net core platform.

**Comment by NikolaMilosavljevic** [comment]
This is already possible today, since package names include major.minor version. We don't support patch versions. @ruimaciel does that work for you?
