### ISSUE TITLE
Issue with regex in 5.0 preview1

### ISSUE THREAD

**Issue by javiercn** [dotnet/runtime#33399]
We got reports of dotnet dev-certs not working in 5.0-preview1. I've debugged through the code and determined that the issue was a regex that was failing.

I've investigated and this seems to be a regression in 5.0. Here is a minimal repro between 3.1 and 5.0 that showcases the issue.

```
/Users/jacalvar/work/repro/regexrepro> dotnet run --framework netcoreapp3.1
True
/Users/jacalvar/work/repro/regexrepro> dotnet run --framework netcoreapp5.0
False
/Users/jacalvar/work/repro/regexrepro> cat ./Program.cs
using System;
using System.Text.RegularExpressions;

namespace regexrepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var result = Regex.Match("CN=localhost", "CN=(.*[^,]+).*", RegexOptions.Singleline, TimeSpan.FromMinutes(1));
            Console.WriteLine(result.Success);
        }
    }
}
```

**Comment by danmosemsft** [comment]
I was going to suggest it was this, which @StephenToub already fixed for Preview2:
https://github.com/dotnet/runtime/pull/32930

However that issue relates to RegexOptions.Compiled, which I don’t see below. 

Can you retest with latest bits from master? Also try with and without the compiled option?

**Comment by danmosemsft** [comment]
#33409 #33407 #33405
