### ISSUE TITLE
VSDC Transfer: Why null value are not consider while apply RowFilter in DataTable

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/runtime#33392]
**Copied issue from Visual Studio Developer Community ([942886](https://developercommunity.visualstudio.com/content/problem/942886/why-null-value-are-not-consider-while-apply-rowfil.html))** 

I have applied the row filter condition in data table. After the filter is applied, the null values are not there in the table.

why not consider the null value, after filtering?

code example:
```cs
// Create a DataTable with one column
DataTable dt = new DataTable("MyTable");


System.Data.DataColumn column = new System.Data.DataColumn("Col", typeof(int));
dt.Columns.Add(column);


// Add 5 rows 
for (int i = 5; i < 10; i++)
{
    System.Data.DataRow row = dt.NewRow();
    row["Col"] = i == 5 ? DBNull.Value : row["Col"] = i;
    dt.Rows.Add(row);
    // Calling AcceptChanges will make the DataRowVersion change from Added to Unchanged in this case
    row.AcceptChanges();
}


// Create a DataView
DataView dataView = new DataView(dt);


// Changing the Sort order to descending
dataView.Sort = "Col DESC";


// Filter by an expression.
dataView.RowFilter = "NOT(Col = '6')";
```
Please refer the sample:
[122155-rowfilteringdatatable.zip](https://github.com/dotnet/runtime/files/4308340/122155-rowfilteringdatatable.zip)

Please refer the attached images:

1. Before Filtering
![image](https://user-images.githubusercontent.com/13396919/76245632-72438500-61f9-11ea-9837-7991424a6d0a.png)

2. After Filtering
![image](https://user-images.githubusercontent.com/13396919/76245701-930bda80-61f9-11ea-8147-8982f912e82c.png)

**Comment by Wraith2** [comment]
This is correct behaviour. Data table is emulating the semantics of sql database null by doing comparisons in such a way that DbNull values never return true when compared using value comparison operators. 

Consider this sql:

```sql
declare @data as table (col int NULL)
insert into @data(col) values (1),(2),(3),(4),(5),(6),(NULL)
select * from @data where not(col=6)

declare @null int = null
select 
	case when @null = 1 then 1 else 0 end as [null = 1],
	case when @null <> 1 then 1 else 0 end as [null <> 1],
	case when 1 = @null then 1 else 0 end as [1 = null],
	case when 1<> @null then 1 else 0 end as [1 <> null],
	case when @null = @null then 1 else 0 end as [null = null],
	case when @null <> @null then 1 else 0 end as [null <> null],
	case when @null is null then 1 else 0 end as [null IS null],
	@null
```

returns:

 _ | col 
--- | --- 
 | 1| 1 
 | 2| 2 
| 3| 3
| 4| 4
| 5|  5

null=1 |	null<>1 | 1=null | 1<>null | null=null | null<>null | null IS null | (No column name)
--- | --- | --- | --- | --- | --- | --- | ---
| 0	| 0	| 0	| 0	| 0	| 0	| 1	| NULL

The only way to deal with null is using the `IS` operator, any direct comparison will always return false without considering the type or value of the operand.

DataTable is preserving the behaviour of a typical SQL database provider with nulls. At the time it was written there was no NoSQL so this seems like sensible default behaviour. It allows you to work with data in memory or with a provider using the same logical rules whether you're constructing queries to send directly to the provider or backing them with memory in a data table.

**Comment by SaravananAyyanar** [comment]
Hi @cheenamalhotra 

thanks for your reply.

while applying row filter row  based on the condition (!6) in table, it will return all value include null value as we expected. Then why handle separate for null value?

**Comment by Wraith2** [comment]
`!6` is not a valid condition string. Every combination i've tried has acted correctly. I think you may need to read https://www.red-gate.com/simple-talk/sql/t-sql-programming/how-to-get-nulls-horribly-wrong-in-sql-server/

**Comment by roji** [comment]
@cheenamalhotra @Wraith2 happened to come across this, is there anything left to do here or can we close?

**Comment by Wraith2** [comment]
Unless someone has more to add I'd say it's ok to close.
