### ISSUE TITLE
Nullability inconsistency between GetIPv4Properties() and GetIPv6Properties()

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#33401]
The implementations of the methods are not look like return null ever and has very similar logic:
```csharp
public abstract IPv4InterfaceProperties GetIPv4Properties();
public abstract IPv6InterfaceProperties GetIPv6Properties();
```
But `GetIPv4Properties()` documented to return null https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipinterfaceproperties.getipv4properties?view=netframework-4.8#returns, but nothing mentioned for `GetIPv6Properties()`. 

By nullability annotations guidance we should follow documented behavior, some suggested we might need to update doc instead, but I don't think I should update doc, instead I would let area owners solve this as needed. 

For now I have made GetIPv4Properties() return nullable, but GetIPv6Properties() non null even they both seems return non null
```csharp
public abstract IPv4InterfaceProperties? GetIPv4Properties();
public abstract IPv6InterfaceProperties GetIPv6Properties();
```

Related to https://github.com/dotnet/runtime/pull/32990#discussion_r385942234

**Comment by karelz** [comment]
Triage: We just need to look through the code to find out what it does -- consistency would be ideal.
Idea: They should return empty collection, not null.
