### ISSUE TITLE
Mark Enumerable methods with the PureAttribute

### ISSUE THREAD

**Issue by Evangelink** [dotnet/runtime#33414]
Hello,

Looking at https://github.com/dotnet/roslyn-analyzers/issues/3363 I have realized that the `System.Linq.Enumerable` methods are not marked with the `PureAttribute` which seems odd to me. Is there an obvious reason I am missing?

**Comment by Evangelink** [comment]
Tagging @eiriktsarpalis @adamsitnik as requested by @Dotnet-GitSync-Bot

**Comment by stephentoub** [comment]
Mainly because [Pure] is part of the Contracts APIs, which we've stopped using in general across the core libraries. We've not gone through and purged existing usage of Pure, but we also haven't been adding it to new APIs in the last many years.

**Comment by Evangelink** [comment]
I see! I wasn't aware this was somehow "deprecated". Are you planning to have any kind of replacement? I see a lot of places where an attribute gives some metadata and helps building analyzers.

**Comment by stephentoub** [comment]
> Are you planning to have any kind of replacement?

Not currently.  Being able to reason about what kind of mutations code might or might not perform is certainly interesting, but it's also non-trivial; [Pure] only scraped the surface.  For example, see the whole "Permissions" section in the write-up here: http://joeduffyblog.com/2016/11/30/15-years-of-concurrency/.

**Comment by eiriktsarpalis** [comment]
Great article, thanks for sharing.
