### ISSUE TITLE
API Proposal: Thread.IsCurrent

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#33416]
## API
```cs
class Thread
{
   public bool IsCurrent { get; }
}
```
## Rationale

This property can be used to check whether that `Thread` is currently executing. That can then be used for example to not require synchronization to access state.

## Implementation
This can be implemented as:
```cs
object.ReferenceEquals(this, Thread.CurrentThread);
```
but a more efficient implementation may be possible.

**Comment by stephentoub** [comment]
I don't understand the proposal. A thread checking if it's currently executing is always going to return true, and a thread checking if another is executing could get an answer that's wrong immediately after checking. How would this be used to avoid any synchronization?

**Comment by tmds** [comment]
```cs
public bool IsCurrent => object.ReferenceEquals(this, Thread.CurrentThread);
```

`this` refers to a specific instance of `Thread`. So when code is not executing on that `Thread`, the property returns `false`.

I ran into this use-case while experimenting with the epoll/io_uring implementation. When Socket operations are allowed to continue on the epoll thread, then new operations are also likely to be started on that thread. When a new operation is started, the code checks if the current thread is still the epoll thread and can handle that case with less synchronization.

It is a niche use-case.

**Comment by stephentoub** [comment]
Ok, I thought from your description you were describing having the property return whether the target thread is currently executing, which isn't useful. What you're actually describing is that you've somehow got a Thread instance, and rather than writing `epollThread == Thread.CurrentThread`, you want to write `epollThread.IsCurrentThread`. Avoiding writing an `==` isn't a good reason to add a new API, especially for a niche scenario. You say the implementation could be more efficient. How so? The `==` version is showing up as a bottleneck that you could eliminate with a better implementation?

**Comment by stephentoub** [comment]
Also, the use case you describe is just as easily handled with a thread static bool that's set to true on the epoll thread and left as its default of false everywhere else.

**Comment by tmds** [comment]
> The == version is showing up as a bottleneck that you could eliminate with a better internal implementation?

It hasn't showed up as a bottleneck. It was awareness of introducing the ThreadStatic Thread.CurrentThread get that made me wonder.
There seemed to be a small regression in the code path that failed the check (not continuing on epoll thread). It wasn't benchmarked extensively.

This use-case occurs also in runtime sources. Often `Environment.CurrentManagedThreadId` is used instead of `Thread.CurrentThread`.

 > Also, the use case you describe is just as easily handled with a thread static bool that's set to true on the epoll thread and left as its default of false everywhere else.

That works for 1 epoll thread only.

I'm going to close this as pre-mature optimization.

Thank you for your feedback!
