### ISSUE TITLE
libraries net stress tests fail git checkout on Docker NanoServer

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#33428]
https://dev.azure.com/dnceng/public/_build/results?buildId=552319&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=1d3f18c3-4e0e-535e-19e9-0e4b922e42dd
https://dev.azure.com/dnceng/public/_build/results?buildId=552318&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=1d3f18c3-4e0e-535e-19e9-0e4b922e42dd

```
git checkout --progress --force 5aff3becf9d9e9f3bc77ee6e3442b3ec0e3d1605
fatal: reference is not a tree: 5aff3becf9d9e9f3bc77ee6e3442b3ec0e3d1605
##[warning]Git checkout failed on shallow repository, this might because of git fetch with depth '1' doesn't include the checkout commit '5aff3becf9d9e9f3bc77ee6e3442b3ec0e3d1605'. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=829603)
##[error]Git checkout failed with exit code: 128
Finishing: Checkout dotnet/runtime@master to s
```

**Comment by BruceForstall** [comment]
@ViktorHofer @danmosemsft

**Comment by ericstj** [comment]
Seems like the same issue as https://github.com/dotnet/runtime/issues/736.  I see from the logs that fetch depth is 1, so that seems likely that this would happen a lot more often.  This build definition seems to be maintained by networking team, please have a look @dotnet/ncl /cc @eiriktsarpalis @safern 

https://github.com/dotnet/runtime/blob/master/eng/pipelines/libraries/stress/http.yml

**Comment by davidsh** [comment]
>I see from the logs that fetch depth is 1, so that seems likely that this would happen a lot more often. 

I think specifying 'fetch depth' is troublesome. I don't do it for my 'runtime-libraries enterprise-linux' [pipeline](https://github.com/dotnet/runtime/blob/master/eng/pipelines/libraries/enterprise/linux.yml) and that pipeline runs all the time for every PR that touches System.Net touch. And the pipeline still runs fairly quickly.

@alnikola  I recommend we modify the stress tests [pipelines](https://github.com/dotnet/runtime/tree/master/eng/pipelines/libraries/stress) to remove 'fetch depth'.
