### ISSUE TITLE
SendPingAsync: Exception when using as root under macOS

### ISSUE THREAD

**Issue by pgrosslicht** [dotnet/runtime#33430]
Hello,

when using `SendPingAsync` as root on a macOS system, a SocketException is thrown (`System.Net.Sockets.SocketException (56): Socket is already connected`). If run as a regular user, it works. It also works for root if you use .NET 2.2. This leads me to believe that this behaviour was introduced in this commit c6efaf4ef89902f0f2180dba9d5d7be9065d80bb. I also tested this on different macOS machines and the outcome was the same, but on a Ubuntu machine it works with sudo as well.

Here is the program I used to reproduce this issue: https://gist.github.com/pgrosslicht/0acf36322247793925dd62692b9202cd.
Here are screenshots running said program with .NET 3.1 with and without sudo and with .NET 2.2 with and without sudo.

<img width="1205" alt="NET3 1" src="https://user-images.githubusercontent.com/1881000/76329955-21a95600-62e5-11ea-9ef9-94dde888470d.png">
<img width="1126" alt="NET2 2" src="https://user-images.githubusercontent.com/1881000/76329961-23731980-62e5-11ea-895d-2cd0d377cbb8.png">

Thanks in advance!

**Comment by vcsjones** [comment]
@wfurt

**Comment by karelz** [comment]
Triage: Regression from @wfurt's changes in Linux, they regressed Mac.

**Comment by wfurt** [comment]
I confirmed this is a regression caused by https://github.com/dotnet/corefx/pull/34084. It is not clear if #27996 was ever applicable to OSX. So far I was unable to reproduce it again either on Linux or OSX.
