### ISSUE TITLE
Make work item payload smaller for crossgen-comparison job

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#33434]
We currently put up the whole artifacts directory as the work item for our crossgen comparison jobs. This results in a massive work item which the ARM machines sometimes have trouble downloading according to https://github.com/dotnet/runtime/issues/33404#issuecomment-597180362. We should instead create a separate folder that has only the necessary files and send that as the work item directory to save space over the wire and speed up the download.

cc: @jashook

**Comment by jashook** [comment]
Looks like our core_root directory is pretty large in general. It is almost 1g

**Comment by jashook** [comment]
I will open a second issue to improve the size of the workitem for all helix submissions. I believe this should be looked at now that so much has changed over the last few months.
