### ISSUE TITLE
Remove the TS_UserSuspendPending enum value

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#33441]
Based on the following snippet in multiple places in the runtime, the `TS_UserSuspendPending` value should be removed.

https://github.com/dotnet/runtime/blob/308ab659f4098bc7df7ed3b1a87a90a209604349/src/coreclr/src/vm/threadsuspend.cpp#L1673-L1674

**Comment by eanova** [comment]
I'd like to take this.

**Comment by AaronRobinsonMSFT** [comment]
@eanova Thanks.
