### ISSUE TITLE
Do not run "Prepare testhost for publish" leg if build fails

### ISSUE THREAD

**Issue by adiaaida** [dotnet/runtime#33449]
Because of the conditional here:

https://github.com/dotnet/runtime/blob/a498bc5b97f2d0857049232375d96f10d64001d6/eng/pipelines/libraries/build-job.yml#L143

If the build fails, the "Prepare testhost for publish" step will still attempt to run, where as all of the other prepare for publish steps will not, since they do not have the conditional. The conditional should test for success && the current conditional so this leg will not be erroneously run, despite the testhost directory not existing because the build failed. See: https://dev.azure.com/dnceng/internal/_build/results?buildId=552445&view=logs&j=4ddd2606-8b9a-5e15-969e-e4774c1f9e64&t=0c1788d8-5459-5d42-d88a-212c8329597d&l=9

**Comment by adiaaida** [comment]
@jashook This popups up in our unknown failure triage frequently when build legs fail. It should be a quick fix. Can you guys have someone take a look?

**Comment by ViktorHofer** [comment]
cc @safern

**Comment by safern** [comment]
We should just change the condition to an `and(success(), ...` I will put up a PR in a sec.
