### ISSUE TITLE
Consider if there is a better term for non-SOH heaps than UOH

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#33445]
`UOH` means  `User's Old Heaps` or `User-allocated Other Heaps`.

The unifying property is that they are not SOH - i.e. they do not participate in generational behavior. Nothing will promote into or out of these.
That implies they are logically in the oldest generation. As long as card tables are one-directional, these will have to be marked together with Gen2.

It is mostly an internal term since the concept of "other than SOH" must have a name. We use it in many places - like comments, enums, function and type suffixes.

We do use these internal terms to explain how the GC works to our customers. So it is somewhat important that it is a good name.

It is hard to name such concept. If there are better ideas, we can rename.

**Comment by jkotas** [comment]
From https://github.com/dotnet/runtime/pull/33402#discussion_r390121014

User's Old Heaps or User-allocated Other Heaps. implies that there are non-user allocated heaps that makes it confusing.

> they are logically in the oldest generation

This would lead to a name like "Oldest Generation Heap", OGH.

**Comment by VSadov** [comment]
I think "User's" meant to point that all allocations in these heaps is done via some API, as opposed to most Gen0 allocations are done via bump-allocation and Gen1/Gen2 get objects in the course of promomotions.

That is a bit fuzzy distinction though, since `Alloc` API can allocate into Gen0 and we may allow alocating into Gen2 directly as well.

**Comment by VSadov** [comment]
Other possibility could be - `NGH` - Non-Generational-Heaps.

**Comment by Maoni0** [comment]
the history of this was: 
it stands for "User Old Heap" - I suggested UAOH - User Allocated Old Heap because it emphasizes that these are directly allocated by user code. but people said it was too long so it was shorted to UOH. I don't recall we never mentioned the word "Other".

I don't think we wanna name it "Oldest Generation Heap" because that does not emphasize the "user allocated" part. oldest would for sure include gen2. 

I believe it's not hard to explain to users what UOH means. we can work on the doc.

**Comment by Maoni0** [comment]
I already explained UOH [on twitter](https://twitter.com/maoni0/status/1230264146546941952), BTW. no one expressed any confusion so far.

**Comment by Maoni0** [comment]
> I think "User's" meant to point that all allocations in these heaps are done via some API, as opposed to most Gen0 allocations are done via bump-allocation and Gen1/Gen2 get objects in the course of promomotions.

it's almost the opposite - it's emphasizing that it's the same as gen0 in the sense that it's also allocated by user code, it just goes somewhere else (onto the UOH). and in contrast, user code cannot allocate in gen1 and gen2.

**Comment by Maoni0** [comment]
let's close this unless there's any objections; please do open a doc issue to add this to docs.

**Comment by ygc369** [comment]
@Maoni0 @VSadov 
Is there any API to allocate from UOH? What scenarios to use UOH?
I think that if C# programers can create UOH freely, the created UOH can be an "arena".

**Comment by VSadov** [comment]
I think at this point we can just close this.
