### ISSUE TITLE
net core2.1 datatable select Occasionally you don't get the right value

### ISSUE THREAD

**Issue by dengyantao** [dotnet/runtime#33466]

**Comment by dengyantao** [comment]
On the server, there is data but it cannot be queried



DataTable dttaxpayable = null;

 dttaxpayable = SerializeHelper.Deserialize<DataTable>(fitaxpayableall.Result.ToString());
  DataRow[] drs2 =dttaxpayable.Select("idnumber = '" + item.Idnumber + "' ");

**Comment by Wraith2** [comment]
Can you provide a working example project please? The description doesn't give enough information to start investigating.

**Comment by roji** [comment]
@dengyantao I'm going to close this for now as no code sample has been provided. However, if you post one we can reopen and investigate.
