### ISSUE TITLE
OSX CI builds fail to install python

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#33471]
https://dev.azure.com/dnceng/public/_build/results?buildId=555403&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=555050&view=results

```
Error: python 3.7.6_1 is already installed
To upgrade to 3.7.7, run `brew upgrade python`.
```

Seems to affect all OSX builds.

**Comment by directhex** [comment]
Do we want to add a `brew upgrade` call prior to the `brew install` calls, so any packages already installed get upgraded to $latest (calling install on a package which is already $latest is a warn, not an error)?
