### ISSUE TITLE
System.drawing.common on android

### ISSUE THREAD

**Issue by TheBricktop** [dotnet/runtime#33473]
Hello im trying to use Accord.net and it relies on system.drawing for bitmap operations,
im trying to use it in unity android so i need Mono.android binaries for that.
Current nupkg from nuget doesnt provide any of that so im asking here if there is any workaround.
![obraz](https://user-images.githubusercontent.com/3866030/76410052-9638cf00-638f-11ea-92eb-7f38dd928a7a.png)

**Comment by safern** [comment]
@marek-safar given the decision we made to make `System.Drawing.Common` windows specific I believe we should close this issue?

**Comment by TheBricktop** [comment]
However this is unfortunate accord net creator has dropped the support for his lib so this is not necessary now.
