### ISSUE TITLE
Span<T> is not Jump method? 

### ISSUE THREAD

**Issue by nczsl** [dotnet/runtime#33482]
I use one-dimensional array to simulate two-dimensional array, and then return row vector or column vector as required. When returning row, I can use slice function. However, the return column cannot be realized because there is no jump function. The return column vector needs to use multiple jumps in the simulated one-dimensional array to construct a span < T >

**Comment by nczsl** [comment]
If I don't use span < T > I think it's OK to have IEnumerable < ref T >

**Comment by stephentoub** [comment]
I'm having trouble understanding the question.  Can you share the signature of the API you're hoping for?

Leaving span out of it for a moment, what is it you'd do with a normal `T[]` here that you can't do with a `Span<T>`?  It sounds like you're wanting to loop through the elements in a given column in your 2D space, in which case with an array you'd do something like:
```C#
for (int i = column; i < arr.Length; i += rowSize)
    Use(arr[i]);
```
right?  Can't you do the same thing with a span?

You might instead be interested in https://devblogs.microsoft.com/dotnet/an-introduction-to-dataframe/.
