### ISSUE TITLE
[Arm64] Load one single-element structure and Replicate to all lanes of one register

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#33490]
```c#
class AdvSimd.Arm64
{
            /// <summary>
            /// float64x2_t vld1q_dup_f64 (float64_t const * ptr)
            ///   A64: LD1R { Vt.2D }, [Xn]
            /// </summary>
            public static unsafe Vector128<double> LoadAndReplicateToVector128(double* address) => LoadAndReplicateToVector128(address);

            /// <summary>
            /// int64x2_t vld1q_dup_s64 (int64_t const * ptr)
            ///   A64: LD1R { Vt.2D }, [Xn]
            /// </summary>
            public static unsafe Vector128<long> LoadAndReplicateToVector128(long* address) => LoadAndReplicateToVector128(address);

            /// <summary>
            /// uint64x2_t vld1q_dup_u64 (uint64_t const * ptr)
            ///   A64: LD1R { Vt.2D }, [Xn]
            /// </summary>
            public static unsafe Vector128<ulong> LoadAndReplicateToVector128(ulong* address) => LoadAndReplicateToVector128(address);
}
class AdvSimd
{
        /// <summary>
        /// uint8x8_t vld1_dup_u8 (uint8_t const * ptr)
        ///   A32: VLD1.8 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.8B }, [Xn]
        /// </summary>
        public static unsafe Vector64<byte> LoadAndReplicateToVector64(byte* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// int16x4_t vld1_dup_s16 (int16_t const * ptr)
        ///   A32: VLD1.16 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.4H }, [Xn]
        /// </summary>
        public static unsafe Vector64<short> LoadAndReplicateToVector64(short* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// int32x2_t vld1_dup_s32 (int32_t const * ptr)
        ///   A32: VLD1.32 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.2S }, [Xn]
        /// </summary>
        public static unsafe Vector64<int> LoadAndReplicateToVector64(int* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// int8x8_t vld1_dup_s8 (int8_t const * ptr)
        ///   A32: VLD1.8 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.8B }, [Xn]
        /// </summary>
        public static unsafe Vector64<sbyte> LoadAndReplicateToVector64(sbyte* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// float32x2_t vld1_dup_f32 (float32_t const * ptr)
        ///   A32: VLD1.32 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.2S }, [Xn]
        /// </summary>
        public static unsafe Vector64<float> LoadAndReplicateToVector64(float* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// uint16x4_t vld1_dup_u16 (uint16_t const * ptr)
        ///   A32: VLD1.16 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.4H }, [Xn]
        /// </summary>
        public static unsafe Vector64<ushort> LoadAndReplicateToVector64(ushort* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// uint32x2_t vld1_dup_u32 (uint32_t const * ptr)
        ///   A32: VLD1.32 { Dd[] }, [Rn]
        ///   A64: LD1R { Vt.2S }, [Xn]
        /// </summary>
        public static unsafe Vector64<uint> LoadAndReplicateToVector64(uint* address) => LoadAndReplicateToVector64(address);

        /// <summary>
        /// uint8x16_t vld1q_dup_u8 (uint8_t const * ptr)
        ///   A32: VLD1.8 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.16B }, [Xn]
        /// </summary>
        public static unsafe Vector128<byte> LoadAndReplicateToVector128(byte* address) => LoadAndReplicateToVector128(address);

        /// <summary>
        /// int16x8_t vld1q_dup_s16 (int16_t const * ptr)
        ///   A32: VLD1.16 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.8H }, [Xn]
        /// </summary>
        public static unsafe Vector128<short> LoadAndReplicateToVector128(short* address) => LoadAndReplicateToVector128(address);

        /// <summary>
        /// int32x4_t vld1q_dup_s32 (int32_t const * ptr)
        ///   A32: VLD1.32 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.4S }, [Xn]
        /// </summary>
        public static unsafe Vector128<int> LoadAndReplicateToVector128(int* address) => LoadAndReplicateToVector128(address);

        /// <summary>
        /// int8x16_t vld1q_dup_s8 (int8_t const * ptr)
        ///   A32: VLD1.8 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.16B }, [Xn]
        /// </summary>
        public static unsafe Vector128<sbyte> LoadAndReplicateToVector128(sbyte* address) => LoadAndReplicateToVector128(address);

        /// <summary>
        /// float32x4_t vld1q_dup_f32 (float32_t const * ptr)
        ///   A32: VLD1.32 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.4S }, [Xn]
        /// </summary>
        public static unsafe Vector128<float> LoadAndReplicateToVector128(float* address) => LoadAndReplicateToVector128(address);

        /// <summary>
        /// uint16x8_t vld1q_dup_u16 (uint16_t const * ptr)
        ///   A32: VLD1.16 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.8H }, [Xn]
        /// </summary>
        public static unsafe Vector128<ushort> LoadAndReplicateToVector128(ushort* address) => LoadAndReplicateToVector128(address);

        /// <summary>
        /// uint32x4_t vld1q_dup_u32 (uint32_t const * ptr)
        ///   A32: VLD1.32 { Dd[], Dd+1[] }, [Rn]
        ///   A64: LD1R { Vt.4S }, [Xn]
        /// </summary>
        public static unsafe Vector128<uint> LoadAndReplicateToVector128(uint* address) => LoadAndReplicateToVector128(address);
}
```

**Comment by echesakovMSFT** [comment]
@CarolEidt, @tannergooding , @TamarChristinaArm PTAL

**Comment by echesakovMSFT** [comment]
@TamarChristinaArm It looks that there is an error on https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics - the website said that `int64x2_t vld1q_dup_s64 (int64_t const * ptr)` and `uint64x2_t vld1q_dup_u64 (uint64_t const * ptr)` are supported on v7/A32/A64. However, `VLD1 (single element to all lanes)` instruction supports only .8 .16 and .32 data sizes.

**Comment by tannergooding** [comment]
@echesakovMSFT, Do you think this should be called `LoadScalar...` to clarify that the `T*` only loads a single `T` from memory?

**Comment by tannergooding** [comment]
For x86, we call this `BroadcastScalarToVector128`, so maybe `ReplicateScalarToVector128` would be an alternative name on the ARM side (dropping `LoadAnd`)...

**Comment by echesakovMSFT** [comment]
> @echesakovMSFT, Do you think this should be called LoadScalar... to clarify that the T* only loads a single T from memory?

There are LD2R, LD3R and LD4R that load 2, 3 and 4 Ts from the memory. Wouldn't we want to expose them via the same method name?

**Comment by echesakovMSFT** [comment]
> For x86, we call this BroadcastScalarToVector128, so maybe ReplicateScalarToVector128 would be an alternative name on the ARM side (dropping LoadAnd)...

Yep, `ReplicateScalarToVector128` was my first choice but then I switched to `LoadAndReplicateToVector128` for above-mentioned reasons

**Comment by tannergooding** [comment]
I don't think we can expose them with the same name due to overload resolution....

Do we have some idea for names/shape of the `LD2`, `LD3`, and `LD4` methods yet? Functionally, they are effectively:
```
(Vector128<T>) LD1R((T)* address);
(Vector128<T>, Vector128<T>) LD2R((T, T)* address);
(Vector128<T>, Vector128<T>, Vector128<T>) LD3R((T, T, T)* address);
(Vector128<T>, Vector128<T>, Vector128<T>, Vector128<T>) LD4R((T, T, T, T)* address);
```

As for shape, we would need to determine if we use `Vector128<T>*` for the results or if we use value tuples (so far, all HWIntrinsic APIs that have returned multiple values have used the former).
We would also need to determine how to encode the address; and while I'd be okay with returning a value tuple; I don't think taking a tuple as the address would be very good (for multiple reasons).
I don't think we'd want to take a value tuple in as the pointer however

**Comment by echesakovMSFT** [comment]
Can we have a separate structure that represents n consecutive SIMD registers? Something like `Vector64x2<T>`. Then these becomes easier

```c#
Vector64x2<uint> LoadAndReplicateToVector64x2(uint* address)
```

I don't think that we need a pointer to anything other than primitive types here.

**Comment by echesakovMSFT** [comment]
I think this is what you proposed here https://github.com/dotnet/runtime/issues/24790#issuecomment-540647378

**Comment by tannergooding** [comment]
We would need a separate proposal for those types, but I think that would be fine. They would have usages for a few other scenarios as well (as they basically represent matrices).

**Comment by tannergooding** [comment]
I think we need something that clarifies how many elements are being loaded from `address` however.

So far, all the APIs we expose only read `Scalar` or `Vector` sizes. I don't believe we have anything that reads `2xT` or `3xT` when that doesn't represent a full vector.

**Comment by TamarChristinaArm** [comment]
> @TamarChristinaArm It looks that there is an error on https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=ld1r - the website said that `int64x2_t vld1q_dup_s64 (int64_t const * ptr)` and `uint64x2_t vld1q_dup_u64 (uint64_t const * ptr)` are supported on v7/A32/A64. However, Arm Architecture Reference Manual says that `VLD1 (single element to all lanes)` instruction supports only .8 .16 and .32 element sizes.
> 

@echesakovMSFT It's not a mistake, for the 64-bit variant we just emit two instructions.

```
        vld1.64 {d0}, [r0:64]
        vmov.f64        d1, d0
```
Since the value is as big as the register we use the `VLD1 (multiple single elements)` variant of the instruction to load the element into the bottom lane of the `Q` register, and then just copy the bottom to the top. In this case the `ld1q_dup_[su]64` are convenience functions on AArch32.

**Comment by TamarChristinaArm** [comment]
> I don't think we can expose them with the same name due to overload resolution....
> 
> Do we have some idea for names/shape of the `LD2`, `LD3`, and `LD4` methods yet? Functionally, they are effectively:
> 
> ```
> (Vector128<T>) LD1R((T)* address);
> (Vector128<T>, Vector128<T>) LD2R((T, T)* address);
> (Vector128<T>, Vector128<T>, Vector128<T>) LD3R((T, T, T)* address);
> (Vector128<T>, Vector128<T>, Vector128<T>, Vector128<T>) LD4R((T, T, T, T)* address);
> ```

Hmm isn't this a bit complicated? they read from consecutive memory and always the same type, so wouldn't `(T)*` for each variant be simpler?

**Comment by tannergooding** [comment]
> Hmm isn't this a bit complicated? they read from consecutive memory and always the same type, so wouldn't (T)* for each variant be simpler?

I was giving an example of how the APIs work functionally, not suggesting an API shape here 😄 

I think @echesakovMSFT's proposed shape here https://github.com/dotnet/runtime/issues/33490#issuecomment-597876379 is much nicer and is something that would be more likely to be approved (or some close variant of it)

**Comment by CarolEidt** [comment]
I have to say that to me the `Vector64x2<t>` and similar look rather ugly, but I think they are probably the best choice. I haven't worked through the register allocation implications, other than thinking it through at a fairly high level. but I think that this is going to require that the register allocator treat these as fundamental types. I'm not sure whether it will be necessary to "leak" them out to the rest of the JIT.

**Comment by tannergooding** [comment]
> I have to say that to me the Vector64x2<t> and similar look rather ugly

I agree they aren't the prettiest, but it at least matches the `Matrix#x#` convention that may be similar to some people already.

>  haven't worked through the register allocation implications, other than thinking it through at a fairly high level. but I think that this is going to require that the register allocator treat these as fundamental types. I'm not sure whether it will be necessary to "leak" them out to the rest of the JIT.

If you have a suggestion for what would allow this to efficiently work in the register allocator, we can definitely take that into account during API review (whether it is a custom struct, value tuple, out/pointer parameters, etc).
This also isn't the only case where instructions return multiple results (`div` and `mul` variants are another), so it might be worthwhile deciding on something that is easily tenable long term.

**Comment by CarolEidt** [comment]
> If you have a suggestion for what would allow this to efficiently work in the register allocator, we can definitely take that into account during API review (whether it is a custom struct, value tuple, out/pointer parameters, etc).

I think that, from the register allocator's perspective, it only matters that we can recognize the "special types" (whether register-allocator-specific or not), and I think we can do that with any of those choices. I would reiterate that we probably want to do what's best from an API perspective, though I suspect that out or pointer parameters or returns will be the most difficult from a CQ perspective (mostly due to JIT front-end considerations due to things being address-taken, especially when inlining).

**Comment by terrajobst** [comment]
Looks good as proposed:

```C#
namespace System.Runtime.Intrinsics
{
    class AdvSimd
    {
        partial class Arm64
        {
            public static unsafe Vector128<double> LoadAndReplicateToVector128(double* address) => LoadAndReplicateToVector128(address);
            public static unsafe Vector128<long> LoadAndReplicateToVector128(long* address) => LoadAndReplicateToVector128(address);
            public static unsafe Vector128<ulong> LoadAndReplicateToVector128(ulong* address) => LoadAndReplicateToVector128(address);
        }
        public static unsafe Vector64<byte> LoadAndReplicateToVector64(byte* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector64<short> LoadAndReplicateToVector64(short* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector64<int> LoadAndReplicateToVector64(int* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector64<sbyte> LoadAndReplicateToVector64(sbyte* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector64<float> LoadAndReplicateToVector64(float* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector64<ushort> LoadAndReplicateToVector64(ushort* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector64<uint> LoadAndReplicateToVector64(uint* address) => LoadAndReplicateToVector64(address);
        public static unsafe Vector128<byte> LoadAndReplicateToVector128(byte* address) => LoadAndReplicateToVector128(address);
        public static unsafe Vector128<short> LoadAndReplicateToVector128(short* address) => LoadAndReplicateToVector128(address);
        public static unsafe Vector128<int> LoadAndReplicateToVector128(int* address) => LoadAndReplicateToVector128(address);
        public static unsafe Vector128<sbyte> LoadAndReplicateToVector128(sbyte* address) => LoadAndReplicateToVector128(address);
        public static unsafe Vector128<float> LoadAndReplicateToVector128(float* address) => LoadAndReplicateToVector128(address);
        public static unsafe Vector128<ushort> LoadAndReplicateToVector128(ushort* address) => LoadAndReplicateToVector128(address);
        public static unsafe Vector128<uint> LoadAndReplicateToVector128(uint* address) => LoadAndReplicateToVector128(address);
    }
}
```
