### ISSUE TITLE
Add AzDO pipelines to test coreclr with libraries test assets

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#33502]
Including JIT stress modes.

There are already
```
runtime-coreclr corefx-jitstress2-jitstressregs
runtime-coreclr corefx-jitstressregs
```
pipelines defined, but they don't work. There should also be a basic "runtime-coreclr corefx-outerloop"  or similar pipeline that does not run any JIT stress modes, and can be scheduled more frequently (just like "runtime-coreclr outerloop").

**Comment by jkoritzinsky** [comment]
I think today's `runtime` pipeline does a "release libraries on a checked CoreCLR" test run, so it looks like we only need to add the stress mode pipelines.

A recent rolling build for reference: https://dev.azure.com/dnceng/public/_build/results?buildId=557557&view=logs&j=96447df6-cb08-536e-96a6-2b28fb9fc6e6&t=df9553ca-be28-55ee-0cb8-d9f84c2659a4

**Comment by BruceForstall** [comment]
Fixed with https://github.com/dotnet/runtime/pull/36486
