### ISSUE TITLE
Package System.Reflection.Metadata 1.0.21 is not compatible with netcoreapp2.1

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/runtime#33520]
The dotnet core runtime snafus continue. It's been a little while since I've been deep in the stacks, but this just seems really broken to me. [Repro repository here](https://github.com/AlbertoMonteiro/CodeGenerationRoslynBugRepro). I'm just troubleshooting my CGR here, but I definitely did not expect this sort of snafu for what I want to accomplish.

**Comment by mwpowellhtx** [comment]
I have VS2017 installed against which I am trying to run this. I do not see any reason why this should not work, apart from dotnet package snafus.

I have the following run times installed, which should support the LTS `netcoreapp2.1`, should it not?

```
C:\Windows\system32>dotnet --list-sdks
1.0.0 [C:\Program Files\dotnet\sdk]
1.1.7 [C:\Program Files\dotnet\sdk]
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
2.1.401 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.509 [C:\Program Files\dotnet\sdk]
2.1.511 [C:\Program Files\dotnet\sdk]
2.1.512 [C:\Program Files\dotnet\sdk]
```

Has LTS expired? Because it seems like your support for it is weak, at best.

**Comment by steveharter** [comment]
The csproj is using netcore 2.1 and referencing `<PackageReference Include="Code.Generation.Roslyn" Version="1.2.0.20972" />` but I don't see any reference to "System.Reflection.Metadata 1.0.21" in the .csproj.

System.Reflection.Metadata 1.0.21 is a really old version that predated netcore 1.0 -- can you use a newer version?

**Comment by mwpowellhtx** [comment]
I did see that these are somewhat dated versions. However, to my knowledge, I have never had to reference these at all. Ever. And it's "just worked". Is there a way to "home" the CLI run time on an acceptable base version?

**Comment by yyjdelete** [comment]
@mwpowellhtx 
It's reference by `<DotNetCliToolReference Include="dotnet-cgr" Version="[1,2)" />`(1.0.0.30102), which maybe known something wrong and unlisted. Change the version to `1.0.1.5415`(seems nuget always install the lowest version) make it possible to restore.
https://www.nuget.org/packages/dotnet-cgr/1.0.0.30102

**Comment by mwpowellhtx** [comment]
@yyjdelete Yes, I am asking because I am the CGR author, and this runtime snafu issue has been a persistent, festering thing, especially since the advent of the new "LTS" runtime. Seems like that blew up the previous LTS altogether, and I have not been able to persuade a successful run from it ever since. At present it is depending on `netcoreapp2.1` if memory serves. Any thoughts on how to persuade the correct runtime for CGR?

**Comment by yyjdelete** [comment]
@mwpowellhtx
It should work for netcoreapp2.1 and 3.1 when you change version of `dotnet-cgr` to `1.*` or any version >= `1.0.1.5415`. In fact, `[1,2)` mean `1.0.0` since NuGet always choose the lowest version, even it's unlisted.
The only error I see is an `CS0101: The namespace "Alberto.TheApp" already contains the definition of "Bar"`, which is the same as https://github.com/mwpowellhtx/Code.Generation.Roslyn/issues/4

**Comment by mwpowellhtx** [comment]
@yyjdelete Appreciate the feedback. I will try that adjustment and see if it does not yield better results. Thanks!

**Comment by mwpowellhtx** [comment]
@yyjdelete And that's not an error. I believe the OP was concerned about an analysis/fixed `partial` keyword, which is not among the stated objectives of *CGR* itself. In terms of the generator, implementing the `IClonable` interface on behalf of its subscriber.

**Comment by ericstj** [comment]
I can reproduce:
```
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202: Package Microsoft.CodeAnalysis.CSharp 1.0.1 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.CodeAnalysis.CSharp 1.0.1 supports: [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5) [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202:   - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7) [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202: Package Microsoft.CodeAnalysis.Common 1.0.1 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.CodeAnalysis.Common 1.0.1 supports: [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5) [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202:   - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7) [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202: Package System.Collections.Immutable 1.1.36 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package System.Collections.Immutable 1.1.36 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : error NU1202: Package System.Reflection.Metadata 1.0.21 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package System.Reflection.Metadata 1.0.21 supports: portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7) [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
```

The error is saying a correct thing: those packages didn't support .NET Core.  They were built before .NET Core even existed.

This appears to be fallout of restoring the wrong version of the dotnet-cgr package, as @yyjdelete mentioned.

```
C:\scratch\CodeGenerationRoslynBugRepro\src\Alberto.TheApp\Alberto.TheApp.csproj : warning NU1603: dotnet-cgr-netcoreapp2.2-[1.0.0, 2.0.0) depends on dotnet-cgr (>= 1.0.0 && < 2.0.0) but dotnet-cgr 1.0.0 was not found. An approximate best match of dotnet-cgr 1.0.0.30102 was resolved. [C:\scratch\CodeGenerationRoslynBugRepro\Alberto.sln]
```

It looks like NuGet chose the lowest version that matched your constraint.  It seems like the issue here is around nuget resolution behavior of dependencies and ranges.  The correct place to file issues on nuget is https://github.com/nuget/home.  I believe best-practice for deterministic build is to list a specific version for a dependency: this way it requires an action by the developer to get a new dependency. 

I confirmed that referencing a newer version of dotnet-cgr as @yyjdelete mentioned avoids the issue reported.
