### ISSUE TITLE
Reenable linux unwinder on Cross OS DAC build

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#33524]
#31777 Disabled the unwinding of native frames in the Windows cross OS DAC build.  

The root cause of the compilation errors will need to be addressed and this code will need to be reenabled

**Comment by sdmaclea** [comment]
This is a bit harder than I initially had expected.  As I understand it to use this code on Windows will also require a Windows port of libunwind.

**Comment by sdmaclea** [comment]
Fixed by #37521

**Comment by tommcdon** [comment]
@sdmaclea can this issue be closed?
