### ISSUE TITLE
ConfigurationManager.AppSettings failing if app.config contains <system.net>…</system.net>

### ISSUE THREAD

**Issue by soyang2828** [dotnet/runtime#33523]
Want to know this is expected.

Our callstack:
Unhandled exception. System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.net. (C:\Program Files\Microsoft\Exchange Server\V15\PopNetCore\Microsoft.Exchange.Pop3.dll.config line 24)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at Microsoft.Exchange.Data.Internal.DefaultApplicationServices.GetTemporaryStoragePath()
   at Microsoft.Exchange.Data.Internal.BaseApplicationServices.GetConfigurationSubSections()

**Comment by safern** [comment]
@soyang2828 thanks. For diagnostics, could you please provide more info? 

What OS this is running on?
A sample code and input?
Version of .NET Core?

**Comment by soyang2828** [comment]
This is on Windows 2016,with .NET core 3.1 runtime.
Usage:
string appSettingsStr = ConfigurationManager.AppSettings["DependencyDirectories"];

It throws if my config has section:
  <system.net>
    <defaultProxy>
      <proxy usesystemdefault="true" bypassonlocal="true" />
      <bypasslist>
        <add address=".*" />
      </bypasslist>
    </defaultProxy>
  </system.net>

**Comment by safern** [comment]
cc: @JeremyKuhne do you have any clue from top of your mind, if no I can try debugging.

**Comment by JeremyKuhne** [comment]
@soyang2828 I presume under `<configuration>`? It would help if you shared a repro .config so that we can make sure we respond correctly.

This is by design, you can't have sections under `<configuration>` that don't have definitions. `system.net` is normally defined in `machine.config`, but there isn't a definition for .NET Core as the type (`System.Net.Configuration.NetSectionGroup`) doesn't exist in Core. We populate an [in-memory "machine" config](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L75) for types that come from `System.Configuration` so you can use `appSettings`, etc.

**Comment by soyang2828** [comment]
Here is short version of the example in app.config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy>
      <proxy usesystemdefault="true" bypassonlocal="true" />
      <bypasslist>
        <add address=".*" />
      </bypasslist>
    </defaultProxy>
  </system.net>
  <appSettings>
    <add key="MaxIoThreadsPerCPU" value="0" />
  </appSettings>
</configuration>

**Comment by soyang2828** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy>
      <proxy usesystemdefault="true" bypassonlocal="true" />
      <bypasslist>
        <add address=".*" />
      </bypasslist>
    </defaultProxy>
  </system.net>
  <appSettings>
    <add key="MaxIoThreadsPerCPU" value="0" />
  </appSettings>
</configuration>

**Comment by soyang2828** [comment]
[app.config.txt](https://github.com/dotnet/runtime/files/4588782/app.config.txt)

**Comment by ericstj** [comment]
This is expected.  Your app.config has `system.net` section which is not defined on .NETCore.

You can just delete the `system.net` section from your configuration file.  That won't be honored by System.Net types in .NETCore.  You can make similar settings in code directly, for example by setting up the [HttpClient.DefaultProxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1) or [WebRequest.DefaultWebProxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.defaultwebproxy?view=netcore-3.1).

If you need to have this section present in your config even though it does nothing on .NETCore let us know and we can provide a workaround or fix.

@soyang2828 let me know if this answers your question.

**Comment by soyang2828** [comment]
@ericstj , I sure can live with deleting it from config. This means I would have two different config files for .netfx and .netcore. And agree it's just something nice to have. So closing this.
