### ISSUE TITLE
CI - Sign and symbol upload Cross OS DAC 

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#33528]
We need to revise the official build process to

- Build the cross OS DAC configurations
- Sign them.
- Upload the builds to the symbol server
- Index the build by the corresponding elf-build-id (s)

We need to agree on the indexing scheme and update the symbol upload docs.

We will need add indices to support mapping from the following libcoreclr build-ids to the corresponding Windows DAC.

```
linux-arm
linux-arm64
linux-x64
musl/alpine-x64
musl/alpine-arm64
```

**Comment by sdmaclea** [comment]
Per @mikem8361 

> The libcoreclr.so index defined by symstore [spec](https://github.com/dotnet/symstore/blob/master/docs/specs/SSQP_Key_Conventions.md#elf-buildid)
> 
> libcoreclr.so/elf-buildid-4eb714123c1ed48a30101567209c40f302c0df18/libcoreclr.so
> 
> The regular Linux DAC index:
> 
> libmscordaccore.so/elf-buildid-coreclr-4eb714123c1ed48a30101567209c40f302c0df18/libmscordaccore.so

Per @leculver & @mikem8361 suggestions the new DAC should be indexed as:

```
mscordaccore.dll/elf-buildid-coreclr-4eb714123c1ed48a30101567209c40f302c0df18/mscordaccore.dll
```

**Comment by sdmaclea** [comment]
Per @dagood 

I believe @Jarret Shook is the right person to talk about implementation.

The artifact I think you need to end up with is a symbol package that contains the cross OS DAC + target platform libcoreclr, so the files are adjacent and hit the symbol uploader tool’s convention to pick up the desired build id. If those native bits can’t be built on the same platform as the libcoreclr, the way to get them together is a “join job” that depends on multiple earlier jobs to finish then downloads the artifacts to repackage.

Currently every Installer job joins all CoreCLR and Libraries jobs, because Installer has to read some data from every artifact on every platform to make the full platform manifest. (But we want to stop this: Create full platform manifest in local build (don't require job join) #1622.) That can maybe be used as an example to create a new job that makes cross OS DAC indexing symbol packages.

**Comment by jarret** [comment]
not me! probably meant to ping some other @

**Comment by dagood** [comment]
Sorry about that! It was pasted from an email (where that resolves to the right person). Edited.

**Comment by hoyosjs** [comment]
This was completed in #39574
