### ISSUE TITLE
CreateDelegate(Type, Type, string) ContainsGenericParameters check is too strict

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#33531]
Consider this example:
```csharp
using System;

class Base {
    public static void M () {
        Console.WriteLine ("Base.M");
    }
}

class Derived<T> : Base {
}

class App {
    public static void Main ()
    {
        var d = (Action) Delegate.CreateDelegate (typeof(Action), typeof(Derived<>), "M");
        d ();
    }
}
```

If I run the above, code on .NET Core 3.1 (or on .NET Framework 4.7.2) the runtime will error with:

```
Unhandled exception. System.ArgumentException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true. (Parameter 'target')
   at System.Delegate.CreateDelegate(Type type, Type target, String method, Boolean ignoreCase, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Type target, String method)
   at App.Main() in /private/tmp/g/Program.cs:line 15
```

This is done by this code in CoreCLR

https://github.com/dotnet/runtime/blob/2beb5527ea3be3d2e9f30fdbb9ece090adc0a889/src/coreclr/src/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs#L265-L266

and by this code in MonoVM

https://github.com/dotnet/runtime/blob/2beb5527ea3be3d2e9f30fdbb9ece090adc0a889/src/mono/netcore/System.Private.CoreLib/src/System/Delegate.Mono.cs#L181-L182

But note that in this case the method definition is not in a generic class, so at runtime it cannot depend on generic parameters.

The ContainsGenericParameters check should be done on the type where the method is actually defined, not on the type that is passed to `CreateDelegate`.

**Comment by lambdageek** [comment]
/cc @jonpryor

The opposite issue (to add the missing ContainsGenericParameters check) for mono/mono is https://github.com/mono/mono/issues/19207

**Comment by akoeplinger** [comment]
We hit this case while bringing up Xamarin.Forms on top of .NET5-enabled Xamarin.Android.

/cc @jkotas

**Comment by jkotas** [comment]
@akoeplinger What would you expect the behavior to be for ambiguous matches, e.g.?

```csharp
using System;

class Base {
    public static void M () {
        Console.WriteLine ("Base.M");
    }
}

class Derived<T> : Base {
    public static new void M () {
        Console.WriteLine ("Base.M");
    }
}

class App {
    public static void Main ()
    {
        var d = (Action) Delegate.CreateDelegate (typeof(Action), typeof(Derived<>), "M");
        d ();
    }
}
```

You are right that the reflection APIs can do more guesses about what you meant in many cases, but I do not think it is a good idea. It is hard to tell where to stop. I believe that the current CoreCLR behavior is the more appropriate one.

Other factors to consider:
- C# does not allow you to call the method via open types either, e.g. `Derived<>.M()` does not compile.
- This behavior is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.delegate.createdelegate?view=netcore-3.1) and the method worked like this in .NET Framework and .NET Core since forever.

**Comment by grendello** [comment]
@jkotas in your example, as stated by the OP, the error should be thrown. There's no ambiguity. The OP says:

```
The ContainsGenericParameters check should be done on the type where the method is actually defined, not on the type that is passed to CreateDelegate.
```

In the OP code the method is actually defined in the non-generic type, in your case it is defined in the generic type.

**Comment by jkotas** [comment]
How do you know that the user meant the method on non-generic type, and not the method on the generic type - that is closer in the inheritance hierarchy?

**Comment by grendello** [comment]
In the OP case there's just one method - in the base type. There's no ambiguity as to which method the user meant. In your case it's more complicated, but the `new` keyword causes the method to shadow the original one - and since there's no cast to the base type, the ambiguity doesn't exist.

**Comment by jkotas** [comment]
I agree with you that there are cases that this API can handle. I just do not think it is a good idea for this API to allow them, for the same reason that it does not make sense for C# to allow calling static methods via open generic types (e.g. `Derived<>.M()` does not compile). I will leave it for reflection area owners to chime in with their opinions.

**Comment by grendello** [comment]
@jkotas this thing has a concrete and real impact on existing Xamarin.Android code and apps, though. Which is why it was brought up - it's not a theoretical case.

**Comment by jkotas** [comment]
Was the code where this was hit in the app itself, or in the Xamarin part?

**Comment by steveharter** [comment]
>>  I just do not think it is a good idea for this API to allow them, for the same reason that it does not make sense for C# to allow calling static methods via open generic types

I agree. I don't know of any other cases where delegates have different behavior\rules than C#.

Closing the generic works of course:
```cs
var d = (Action)Delegate.CreateDelegate(typeof(Action), typeof(Derived<int>), "M");
```
as well as calling the base:
```cs
var d = (Action)Delegate.CreateDelegate(typeof(Action), typeof(Base), "M");
```

**Comment by grendello** [comment]
@jkotas it's in Xamarin.Forms, exposed by Xamarin.Android, but it can/will be part of any XF app

**Comment by jkotas** [comment]
Can we fix it Xamarin.Forms/Android? 

I assume that the apps will be required to upgrade to latest Xamarin.Forms/Android for .NET 5. We have similar policy with ASP.NET - e.g. ASP.NET 2.1 is not supported/tested on top .NET Core 3.

If we get data that this API usage is very common in the Xamarin apps, we can decide that to do about it then.

**Comment by jonpryor** [comment]
> Was the code where this was hit in the app itself, or in the Xamarin part?

It was hit within the Xamarin part.

> Can we fix it Xamarin.Forms/Android?

We have a Fix in Xamarin.Android: xamarin/xamarin.android#4394.
