### ISSUE TITLE
[mono] Don't compile and export unused icalls

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#33533]
In https://github.com/dotnet/runtime/blob/master/src/mono/mono/metadata/icall-decl.h we have declarations for icalls that may not be used in https://github.com/dotnet/runtime/blob/master/src/mono/mono/metadata/icall-def-netcore.h that aren't under an '#ifndef ENABLE_NETCORE` guard.

The two files should be audited and the icall declarations should be ifdefed out in `icall-decl.h` (along with their corresponding implementations which are likely in `icall.c` but maybe elsewhere)

**Comment by jaykrell** [comment]
Compiling them is useful.
Are they actually exported? I think not. Agreed they should not be.

**Comment by lambdageek** [comment]
We don't have icall-def.h in dotnet/runtime anymore, and all the `#ifndef ENABLE_NETCORE` code has been removed.  I don't expect that any unused icalls remain.
