### ISSUE TITLE
For .NET Core 2.1, the CoreCLR symbols are missing for IL symbols.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/runtime#33550]
Affected Build: Val build D15.9/28307.1072(15.9.22) with SDK 2.1.513(runtime-2.1.17)

### Steps to reproduce
Testing on Windows with VS -
1.	Goto Tools -> options -> Debugging
Under General
a. Uncheck 'Enable Just My Code'
b. Check 'Suppress JIT optimization on module load (Managed only)'
Under Symbols
a. Check 'Microsoft Symbol Servers'
2.	Create a new ASP.NET Razor project by doing
mkdir razor
cd razor
dotnet new razor
3.	Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code.
4.	Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file). When using VS, you can add this line of code on Program.cs file
Console.WriteLine("x " + 3);
5.	Place a breakpoint on that line (F9).
6.	Run the application until it hit that breakpoint (F5). It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint. You should see 20-30 lines of ‘Loaded XXX Symbols loaded’.
7.	Step into the concatination method (F11). Select 'Download Source and Continue Debugging' from the popup
This tests CoreCLR symbols AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR Concat().

### Expected result:
CoreCLR symbols are displayed in step7.

### Actual result:
CoreCLR symbols are missing in step7.
![image](https://user-images.githubusercontent.com/57380211/76613839-e2376f80-6559-11ea-9a9e-de3347f950bb.png)
**Dotnet –info:**
.NET Core SDK (reflecting any global.json):
 Version:   2.1.513
 Commit:    537cfb9a5c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.513\

Host (useful for support):
  Version: 2.1.17
  Commit:  7b9e4ef7c1

.NET Core SDKs installed:
  2.1.513 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jashook** [comment]
This looks like it should be opened in dotnet/coreclr. /cc @hoyosjs

**Comment by jashook** [comment]
Right dotnet/coreclr does not have issues now. I will add this to our backlog for now.

**Comment by vdanche** [comment]
Repro on Version 16.7.3 [30425.237.d16.7] with inserted 3.1.402 SDK when test september update
![image](https://user-images.githubusercontent.com/65637796/91426418-12b46100-e88f-11ea-9e6a-3334b4fa2b72.png)

**Comment by vdanche** [comment]
Also repro on VS 16.10.4 and 16.11

**Comment by jkoritzinsky** [comment]
I believe this has since been resolved. Please open a new issue if it hasn't.
