### ISSUE TITLE
[Arm64] Vectorize System.Numerics.Matrix4x4 using hardware intrinsics

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#33565]
System.Numerics.Matrix4x4.Transpose()
System.Numerics.Matrix4x4.Lerp()
System.Numerics.Matrix4x4.operator-()
System.Numerics.Matrix4x4.operator+()
System.Numerics.Matrix4x4.operator*()
System.Numerics.Matrix4x4.operator==()
System.Numerics.Matrix4x4.operator!=()

**Comment by BruceForstall** [comment]
Related: #33308

**Comment by BruceForstall** [comment]
I'm moving this to Future, as there is no current plan to do the work for .NET 5.

**Comment by jeffhandley** [comment]
This work is being picked up by the .NET Libraries team; assigned to @tannergooding now.

**Comment by eanova** [comment]
@tannergooding Hi,  I've been unavailable for the past month.  I'd like to finish these Matrix4x4 tasks plus Inversion if you haven't assigned it to someone else already.

**Comment by tannergooding** [comment]
This is something I've actually already finished locally and will be getting up a PR for either later tonight or early Monday. Thanks however!

**Comment by BruceForstall** [comment]
@tannergooding Is this still in progress?

**Comment by tannergooding** [comment]
Yes, just trying to work through some ARM64 specific failures: <https://github.com/dotnet/runtime/pull/40054>
