### ISSUE TITLE
net core2.1 datatable select Occasionally you don't get the right value

### ISSUE THREAD

**Issue by dengyantao** [dotnet/runtime#33572]
net core2.1 datatable select Occasionally you don't get the right value
example：
DataTable dttaxpayable =new DataTable ();
dttaxpayable .Select("idnumber = '" + item.Idnumber + "' ")

**Comment by Wraith2** [comment]
duplicate of https://github.com/dotnet/runtime/issues/33466

**Comment by danmosemsft** [comment]
Duplicate
