### ISSUE TITLE
Dotnet build is stuck

### ISSUE THREAD

**Issue by urbanecm** [dotnet/runtime#33571]
Hello, I've encouraged a weird issue - dotnet build is just stuck forever. I've disucssed the idea at dotnet/cli gitter channel, see https://gitter.im/dotnet/cli?at=5e3db126f3718e705deb7c3f and following.

It behaves like this:

    urbanecm@titanium  ~/tmp
    $ ps ux | grep dotnet
    urbanecm 1010806  0.0  0.0  13056   804 pts/5    S+   11:22   0:00 grep --color=auto dotnet
    urbanecm@titanium  ~/tmp
    $ mkdir foo
    urbanecm@titanium  ~/tmp
    $ cd foo
    urbanecm@titanium  ~/tmp/foo
    $ dotnet new console
    The template "Console Application" was created successfully.

    Processing post-creation actions...
    Running 'dotnet restore' on /home/urbanecm/tmp/foo/foo.csproj...
    [is stuck]
    ^C
    urbanecm@titanium  ~/tmp/foo
    $ ps ux | grep dotnet
    urbanecm 1010875  0.0  1.4 3691804 61088 pts/5   SLl  11:22   0:01 dotnet exec /usr/share/dotnet/sdk/2.2.402/MSBuild.dll -maxcpucount -verbosity:m -nologo -target:Restore /home/urbanecm/tmp/foo/foo.csproj -distr
    ibutedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/2.2.402/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/2.2.402/dotnet.dll
    urbanecm 1010940  0.0  0.0  13056   832 pts/5    S+   11:23   0:00 grep --color=auto dotnet
    urbanecm@titanium  ~/tmp/foo
    $ kill -9 1010875
    urbanecm@titanium  ~/tmp/foo
    $ dotnet build
    Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

    [stuck as well]
    ^CAttempting to cancel the build...

    urbanecm@titanium  ~/tmp/foo
    $ ps ux | grep dotnet
    urbanecm 1010985  0.0  1.3 3494904 58296 pts/5   SLl  11:23   0:01 dotnet exec /usr/share/dotnet/sdk/2.2.402/MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary -target:Build -distrib
    utedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/2.2.402/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/2.2.402/dotnet.dll
    urbanecm 1011039  0.0  0.0  13056   780 pts/5    S+   11:23   0:00 grep --color=auto dotnet
    urbanecm@titanium  ~/tmp/foo
    $ kill -9 1010985
    urbanecm@titanium  ~/tmp/foo
    $

This was dotnet 2.2, but dotnet 3.1 behaves the same. Interesting is that self-contained apps behaves the same. 

    urbanecm@titanium  /home/s3w3n/linux-x64
    $ ./blazor-self-contained
    Failed to create CoreCLR, HRESULT: 0x8013200A

Any idea how this could be fixed?

**Comment by Pilchie** [comment]
@jeffschwMSFT - can you help label and triage this?  It appears to be a failure to initialize the runtime?

**Comment by jeffschwMSFT** [comment]
@mangod9

**Comment by mangod9** [comment]
@urbanecm based on the comments in the issue, does the hang occur while running on https://vpsadminos.org/ ? Have you been able to capture a dump when the hang occurs? Thanks!

**Comment by mangod9** [comment]
@urbanecm closing this issue for now since it hasnt had much activity for a few weeks. Please reopen if the issue still persists. Hoping you can capture a dump at that time.

**Comment by gaviriar** [comment]
Hi There, I seem to be having a very similar issue to this. However the slight difference is that on one project on my environment dontet build. Whereas on the other project my build gets stuck. 

**My Enviromennt**
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Output when calling `dotnet build /b`:**
```
~\projects\failing_build_project> dotnet build /bl
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.1.302\MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.1.302\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.1.302\dotnet.dll -maxcpucount -restore -verbosity:m /bl .\ChromeleonConsole.csproj
```

I also have the dump file, but it seems to be too big to share on this thread. But please let me know and I will happily share it with you.

Thanks in advance for reading this.

**Comment by ksemkav** [comment]
Hello. We have also similar issue on build agent with several CPUs, on buildagents with one it works fine. 
The one with 2 CPUs:
`.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
`
And it is also stucked at these lines 
`
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
13:57:09
      Copyright (C) Microsoft Corporation. All rights reserved.
`

Thanks in advance for your time and any help.

**Comment by mangod9** [comment]
A dump would be very useful to investigate further. Could you please upload to a share and send a link over email? Thx

**Comment by ksemkav** [comment]
@mangod9 Sorry, I'm not sure that I fully understand what I should do. How can I prepare such dump and what do you expect to see there?

**Comment by mangod9** [comment]
My comment was for @gaviriar who mentioned that they have been able to capture a dump when the build hangs. So sharing that would be helpful to continue the investigation. Thx.

**Comment by gaviriar** [comment]
Hi @mangod9 ,

I have sent you the dump via private email. I hope it is somewhat helpful. For future reference here are the instructions on how to create a dump (FYI @ksemkav): 

1. Install `dotnet-dump` by following [these steps](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump#installing-dotnet-dump)

2. Run the build that is stuck `dotnet build --project <problematic-project>.csproj`

3. Open another shell and find the process ID of process running the build in step 2. I use `dotnet-dump ps`

4. Collect the dump of the process into `~/projects/<problematic-project>_dump.dmp`

```
dontet-dump collect -p <PID> -o ~/projects/<problematic-project>_dump.dmp
```

**Comment by andrii-litvinov** [comment]
Seems like I am hitting the same issue. Builds get stuck once in a while on our build server and I have to ssh to the agent and kill the hanging process. Any workaround is available so far? Or should I try to collect the dump? If so, whom should I send it to?

**Comment by mangod9** [comment]
Hi @andrii-litvinov, yeah a dump should be helpful. Please send it over to me. We have a theory so additional dumps would help confirm. Thx

**Comment by andrii-litvinov** [comment]
@mangod9 I tried to collect the dump for a process
```
ps -aux | grep dotnet
root     24307  0.1  1.0 3102804 84668 ?       SLl  00:58   0:00 dotnet run --project Build.Project -- Clean Test --configuration Release
root     24348  0.8  1.8 22855188 148580 ?     SLl  00:58   0:02 /usr/share/dotnet/dotnet exec /usr/share/dotnet/sdk/3.1.401/Roslyn/bincore/VBCSCompiler.dll -pipename:CDZAR5edX3y23v7o2Ux503noB+tJ5+Lx0ltF_IxXplk
root     24487  0.0  0.7 2829680 58152 ?       SLl  00:58   0:00 /usr/bin/dotnet build /home/administrator/BuildAgent/work/9777e0758252645c/.output/compile --configuration Release --verbosity Minimal /property:Version=2020.09.17.0
root     24500  0.2  1.0 3747364 88692 ?       SLl  00:58   0:00 dotnet exec /usr/share/dotnet/sdk/3.1.401/MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary -property:Configuration=Release -verbosity:Minimal /home/administrator/BuildAgent/work/9777e0758252645c/.output/compile /property:Version=2020.09.17.0
adminis+ 24593  0.0  0.0  14220  1016 pts/2    S+   01:04   0:00 grep --color=auto dotnet
root     26457  0.0  0.0 3919316 1136 ?        SLl  Sep16   0:02 /usr/share/dotnet/dotnet /usr/share/dotnet/sdk/3.1.401/MSBuild.dll /usr/share/dotnet/sdk/3.1.401/MSBuild.dll /nologo /nodemode:1 /nodeReuse:true /low:false
```
And got following error 
```
dotnet-dump collect -p 26457 -o hanging-msbuild.dmp

Writing full to /home/administrator/hanging-msbuild.dmp
Process 26457 not running compatible .NET runtime.
```

Cannot get dump for any other MSBuild processes. I suppose the one that is hanging is 26457, because when the build being cancelled by timeout it's the only process that remains. And when I kill it all build successfully proceed.

**Comment by mangod9** [comment]
hey @andrii-litvinov did dotnet-dump fail just for the dotnet build process? Assume this is with .net core 3.1? Adding @tommcdon as well.

**Comment by tommcdon** [comment]
Adding @mikem8361

**Comment by mikem8361** [comment]
@andrii-litvinov, what does `dotnet-dump ps` display? The problem may be that the msbuild process user is "root".

**Comment by andrii-litvinov** [comment]
@mangod9 `dotnet-dump` fails for all the dotnet process, yes it's .net core 3.1.
```
dotnet-dump --version
3.1.141901+3f460984c62efa118b6bd87fa4c5f07b11074b34
```

@mikem8361 I tried to collect dump both with and without `sudo`, same result. Both `dotnet-dump ps` and `sudo dotnet-dump ps` don't list any processes.

**Comment by mikem8361** [comment]
Can you ls your /tmp/ directory and look for pipe files like dotnet-diagnostic-31853-493163662-socket= where "31853" is the dotnet app process id?  Does the msbuild.dll process and the shell you are using to execute dotnet-dump collect have the same /tmp/ directory? 

/cc: @dotnet/dotnet-diag

**Comment by andrii-litvinov** [comment]
@mikem8361 In `/tmp/` directory I don't see any files with pattern that you described, only ones like `MSBuild59253` where 59253 is the id of the process.

>Does the msbuild.dll process and the shell you are using to execute dotnet-dump collect have the same /tmp/ directory?

I am not sure how to tell that. I ssh to the server, I tried switching to the root user as well. The processed are started by TeamCity agent and subsequent build steps are implemented with Nuke. I don't think any of those do something weird with `/tmp/` folder.

**Comment by mikem8361** [comment]
Is there anyway to see if/what the TMPDIR environment variable is set for the msbuild process? Also if the COMPlus_EnableDiagnostics env var is set to 0 explicitly, it would disable the diagnostics server pipe (and managed debugging in general) and would explain why dotnet-dump collect isn't working. 

I don't know anything about TeamCity or Nuke and how they launch msbuild.

/cc: @josalem

**Comment by andrii-litvinov** [comment]
`COMPlus_EnableDiagnostics` isn't set to anything, I mean `echo $COMPlus_EnableDiagnostics` returns empty result.

```
sudo cat /proc/5389/environ | tr '\0' '\n' | grep TMPDIR
TMPDIR=/home/administrator/BuildAgent/temp/buildTmp
```
So it seems that the temp dir is different.

I tried to set temp dir in the shell to the same value and got same result

```
TMPDIR=/home/administrator/BuildAgent/temp/buildTmp
dotnet-dump collect -p 4262 -o hanging-msbuild.dmp

Writing full to /home/administrator/hanging-msbuild.dmp
Process 4262 not running compatible .NET runtime.
```

If there is something that I can try let me know. I have no idea what else to look for.

**Comment by mikem8361** [comment]
I don't think dotnet-dump collect (or any other of our global tools) looks at TMPDIR to find the diagnostic server connection. Hopefully, @josalem can answer this.

**Comment by hoyosjs** [comment]
We definitely respect TEMPDIR on Linux because of the API we use: https://source.dot.net/#System.Private.CoreLib/Path.Unix.cs,71

**Comment by josalem** [comment]
The tools should be looking in whatever the `TMPDIR` variable points at (https://github.com/dotnet/diagnostics/blob/894ade7a80d46e8870a718f8ac9df6959cc4a61c/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs#L105).

What do you see when `ls -lah $TMPDIR` while the target process is running?  What does `dotnet-dump ps` show?

**Comment by andrii-litvinov** [comment]
@josalem `dotnet-dump ps` doesn't return anything. The output from `ls -lah $TMPDIR` is below. I set `TMPDIR` manually in the shell during this investigation.

```bash
total 72K
drwxr-xr-x 4 root root  12K Sep 21 11:24 .
drwxr-xr-x 6 root root 4.0K Sep 21 11:24 ..
-rw-r--r-- 1 root root 2.3K Sep 21 11:24 changedFiles4718313358388767628.txt
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-19811-168815419-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-19811-168815419-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-19870-168815816-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-19870-168815816-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-19982-168816223-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-19982-168816223-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20000-168816238-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20000-168816238-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20019-168816252-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20019-168816252-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20041-168816266-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20041-168816266-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20062-168816280-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20062-168816280-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20082-168816294-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20082-168816294-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20431-168818407-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20431-168818407-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20444-168818421-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20444-168818421-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20468-168818459-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20468-168818459-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20486-168818473-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20486-168818473-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20504-168818488-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20504-168818488-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20525-168818502-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20525-168818502-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20546-168818515-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20546-168818515-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20568-168818529-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20568-168818529-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20591-168818542-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20591-168818542-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20626-168818565-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20626-168818565-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20655-168818609-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20655-168818609-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20656-168818612-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20656-168818612-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20657-168818612-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20657-168818612-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20683-168818621-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20683-168818621-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20684-168818623-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20684-168818623-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20719-168818645-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20719-168818645-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20756-168818677-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20756-168818677-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20790-168818689-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20790-168818689-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20794-168818693-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20794-168818693-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20798-168818694-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20798-168818694-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20808-168818696-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20808-168818696-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20922-168818732-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20922-168818732-out
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20941-168818813-in
prwx------ 1 root root    0 Sep 21 11:24 clr-debug-pipe-20941-168818813-out
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-19811-168815419-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-19870-168815816-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-19982-168816223-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20000-168816238-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20019-168816252-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20041-168816266-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20062-168816280-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20082-168816294-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20431-168818407-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20444-168818421-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20468-168818459-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20486-168818473-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20504-168818488-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20525-168818502-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20546-168818515-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20568-168818529-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20591-168818542-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20626-168818565-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20655-168818609-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20656-168818612-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20657-168818612-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20683-168818621-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20684-168818623-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20719-168818645-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20756-168818677-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20790-168818689-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20794-168818693-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20798-168818694-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20808-168818696-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20922-168818732-socket
srw------- 1 root root    0 Sep 21 11:24 dotnet-diagnostic-20941-168818813-socket
drwxrwxrwx 3 root root 4.0K Sep 21 11:24 NuGetScratch
-rw-r--r-- 1 root root 2.1K Sep 21 11:24 teamcity.build7680489535867057158.properties
-rw-r--r-- 1 root root 2.9K Sep 21 11:24 teamcity.build7680489535867057158.properties.xml
-rw-r--r-- 1 root root 9.1K Sep 21 11:24 teamcity.config1529141588846845257.properties
-rw-r--r-- 1 root root  13K Sep 21 11:24 teamcity.config1529141588846845257.properties.xml
-rw-r--r-- 1 root root  702 Sep 21 11:24 teamcity.runner6345272519070156754.properties
-rw-r--r-- 1 root root 1.1K Sep 21 11:24 teamcity.runner6345272519070156754.properties.xml
drwxr-xr-x 3 root root 4.0K Sep 21 11:24 VBCSCompiler
```

**Comment by josalem** [comment]
Just to be thorough, did you `export TMPDIR=...` before running `dotnet-dump ps`?

Specifically:
```
export TMPDIR=/home/administrator/BuildAgent/temp/buildTmp
dotnet-dump ps
```

**Comment by andrii-litvinov** [comment]
I tried
```
export TMPDIR=/home/administrator/BuildAgent/temp/buildTmp
dotnet-dump ps
```
And received following response
```
Failed to initialize CoreCLR, HRESULT: 0x80004005
```
Googled a bit without digging much into the error and found out that it can work with `sudo`. For some reason `sudo dotnet-dump ps` returns `sudo: dotnet-dump: command not found`, so after some more trial following command listed all .NET processes and I was able to collect the dump:
```
sudo -E env "TMPDIR=/home/administrator/BuildAgent/temp/buildTmp" /home/administrator/.dotnet/tools/dotnet-dump ps
sudo -E env "TMPDIR=/home/administrator/BuildAgent/temp/buildTmp" /home/administrator/.dotnet/tools/dotnet-dump collect -p 30512 -o hanging-msbuild.dmp
```

Interestingly, after the build finished, the same command to collect the dump returned same `Process 30555 not running compatible .NET runtime.` response.

I will wait for the next time when MSBuild hangs and will send the dump. Thanks everyone for guiding me through the process!

**Comment by andrii-litvinov** [comment]
I've sent a dump to @mangod9. For some reason I wasn't able to get a dump two other MSBuild processes, but when I killed those next scheduled builds succeeded.

```csharp
$ ps -aux | grep dotnet
root     27354  0.0  0.1 3853784 8588 ?        SLl  Sep24   0:01 /usr/share/dotnet/dotnet /usr/share/dotnet/sdk/3.1.401/MSBuild.dll /usr/share/dotnet/sdk/3.1.401/MSBuild.dll /nologo /nodemode:1 /nodeReuse:true /low:false
root     46070  0.0  0.0 3788244 7140 ?        SLl  Sep23   0:01 /usr/share/dotnet/dotnet /usr/share/dotnet/sdk/3.1.401/MSBuild.dll /usr/share/dotnet/sdk/3.1.401/MSBuild.dll /nologo /nodemode:1 /nodeReuse:true /low:false

$ sudo -E env "TMPDIR=/home/administrator/BuildAgent/temp/buildTmp" /home/administrator/.dotnet/tools/dotnet-dump collect -p 27354 -o hanging-msbuild-2.dmp

Writing full to /home/administrator/hanging-msbuild-2.dmp
Process 27354 not running compatible .NET runtime.
```

**Comment by ffMathy** [comment]
I am also experiencing this issue randomly. Very frustrating. Also happens on my machine.

**Comment by sdmaclea** [comment]
@josalem @sywhang Do we cover the `tmpdir` and `sudo` dotnet-dump nuances in our docs?  Should we?

**Comment by josalem** [comment]
For the `TMPDIR` usage, I don't believe we document the requirement that the target process and the dotnet tool need to share a `TMPDIR` value.  I think https://github.com/dotnet/diagnostics/issues/1737 is appropriate for that.

**Comment by sdmaclea** [comment]
@josalem Thanks.  I added a separate item for same user for access to the diagnostic pipes.  Feel free to edit.

**Comment by andrii-litvinov** [comment]
Eventually I solve the hanging build issue in CI by running 
```
dotnet build-server shutdown
```
after each build. So far so good. Nuke.build provides attribute `[ShutdownDotNetAfterServerBuild]` for the matter.
