### ISSUE TITLE
Official buids failing at testing published symbols

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#33577]
The error is 

>  runtimes/win/native/coreclr.dll has no version resource

This is impacting all our official builds at the moment. 

|Build|Kind|Timeline Record|
|---|---|---|
|[558488](https://dev.azure.com/dnceng/internal/_build/results?buildId=558488)|Rolling|Publish|
|[558213](https://dev.azure.com/dnceng/internal/_build/results?buildId=558213)|Rolling|Publish|
|[558052](https://dev.azure.com/dnceng/internal/_build/results?buildId=558052)|Rolling|Publish|
|[557647](https://dev.azure.com/dnceng/internal/_build/results?buildId=557647)|Rolling|Publish|
|[557570](https://dev.azure.com/dnceng/internal/_build/results?buildId=557570)|Rolling|Publish|
|[557254](https://dev.azure.com/dnceng/internal/_build/results?buildId=557254)|Rolling|Publish|
|[556993](https://dev.azure.com/dnceng/internal/_build/results?buildId=556993)|Rolling|Publish|
|[556704](https://dev.azure.com/dnceng/internal/_build/results?buildId=556704)|Rolling|Publish|
|[556531](https://dev.azure.com/dnceng/internal/_build/results?buildId=556531)|Rolling|Publish|
|[556563](https://dev.azure.com/dnceng/internal/_build/results?buildId=556563)|Rolling|Publish|
|[556246](https://dev.azure.com/dnceng/internal/_build/results?buildId=556246)|Rolling|Publish|
|[555804](https://dev.azure.com/dnceng/internal/_build/results?buildId=555804)|Rolling|Publish|
|[554673](https://dev.azure.com/dnceng/internal/_build/results?buildId=554673)|Rolling|Publish|
|[554422](https://dev.azure.com/dnceng/internal/_build/results?buildId=554422)|Rolling|Publish|
|[554279](https://dev.azure.com/dnceng/internal/_build/results?buildId=554279)|Rolling|Publish|
|[553695](https://dev.azure.com/dnceng/internal/_build/results?buildId=553695)|Rolling|Publish|
|[553529](https://dev.azure.com/dnceng/internal/_build/results?buildId=553529)|Rolling|Publish|
|[553214](https://dev.azure.com/dnceng/internal/_build/results?buildId=553214)|Rolling|Publish|
|[547855](https://dev.azure.com/dnceng/internal/_build/results?buildId=547855)|Rolling|Publish|
|[547593](https://dev.azure.com/dnceng/internal/_build/results?buildId=547593)|Rolling|Publish|
|[547487](https://dev.azure.com/dnceng/internal/_build/results?buildId=547487)|Rolling|Publish|
|[547367](https://dev.azure.com/dnceng/internal/_build/results?buildId=547367)|Rolling|Publish|
|[546929](https://dev.azure.com/dnceng/internal/_build/results?buildId=546929)|Rolling|Publish|
|[546292](https://dev.azure.com/dnceng/internal/_build/results?buildId=546292)|Rolling|Publish|
|[546068](https://dev.azure.com/dnceng/internal/_build/results?buildId=546068)|Rolling|Publish|
|[545969](https://dev.azure.com/dnceng/internal/_build/results?buildId=545969)|Rolling|Publish|
|[545844](https://dev.azure.com/dnceng/internal/_build/results?buildId=545844)|Rolling|Publish|

> runfo search-timeline -d runtime-official -c 100 -v "has no version resource" -m

**Comment by directhex** [comment]
This seems resolved
