### ISSUE TITLE
Take advantage of nint and nuint in Utf8String code

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#33575]
When we get a compiler with the new [`nint`/`nuint` feature](https://github.com/dotnet/csharplang/issues/435) we should change our current ifdef pattern in the Utf8String code:

https://github.com/dotnet/runtime/blob/490f09e1751d03d3ca9ea87ae3a8ea49b72739a3/src/libraries/System.Private.CoreLib/src/System/Text/Unicode/Utf8Utility.Transcoding.cs#L14-L20

And just use the new feature.

For the OOB Utf8String package, we chose to use `Int64` and `UInt64` for `nint` and `nuint`, because we can't compile twice for each bitness.

**Comment by jkotas** [comment]
This is in no way specific to Utf8String.

**Comment by eerhardt** [comment]
I can make it more general to cover the whole CoreLib. I was just logging this in order to put in a tracking issue for [this comment on my PR](https://github.com/dotnet/runtime/pull/33357#discussion_r392077362).

It directly affects Utf8String because we can only build 1 IL assembly, and so we had to pick what `nint` means in that build.

**Comment by jkotas** [comment]
Fixed by #36159. One remaining place is left that would need https://github.com/dotnet/runtime/issues/36160.
