### ISSUE TITLE
Remove UMThunkStub for all non-x86 scenarios

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#33581]
With the completion of support for NativeCallableAttribute being public - https://github.com/dotnet/runtime/pull/33005, there is some additional cleanup that can now occur. The `UMThunkStub()` calls written in assembly can now be replaced by the newly added JIT helpers for Reverse P/Invoke Enter/Exit.

https://github.com/dotnet/runtime/blob/a1af0f2ad6cf51107a636dbe280cf939abd46b34/src/coreclr/src/vm/jithelpers.cpp#L5064-L5095

The x86 case must still use the `UMThunkStub()`, but all other can now be removed.

/cc @jkoritzinsky @jkotas @janvorli

**Comment by safern** [comment]
This was reverted in: https://github.com/dotnet/runtime/pull/34306
