### ISSUE TITLE
Debug.Assert causing unit test failures in System.Runtime and System.Memory

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#33596]
Some unit tests are failing due to `Debug.Assert` statements being tripped. See for instance:

 * https://helix.dot.net/api/2019-06-17/jobs/945daa52-1ccd-42e5-a59a-02cc4a26fa76/workitems/System.Memory.Tests/console
 * https://helix.dot.net/api/2019-06-17/jobs/945daa52-1ccd-42e5-a59a-02cc4a26fa76/workitems/System.Runtime.Tests/console

The culprit is likely https://github.com/dotnet/runtime/pull/32385. However, that PR was green across all of CI.

Assigning myself to investigate.

**Comment by jkotas** [comment]
Unless you have a fix ready, could you please revert the change?

**Comment by GrabYourPitchforks** [comment]
I should have a fix ready soon.
