### ISSUE TITLE
Implement IAsyncDisposable for XmlWriter and XmlReader

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#33618]
There is some issues filed for XmlWriter about async write operation using  sync write/flush on dispose: https://github.com/dotnet/runtime/issues/29464, https://github.com/dotnet/runtime/issues/31104. From the issues apparently In ASP.NET Core 3.x for HTTP Response/Request streams now sync operation is disabled by default and throwing `InvalidOperation` when XmlWriter `Dispose()` eventually calls sync Write(...)/Flush() for the Http stream.

Kind of similar issue happening for XmlReader too https://github.com/dotnet/runtime/issues/31737. 

Proper solution for these issues would be implement IAsyncDisposable for XmlWriter and XmlReader
```csharp
public abstract class XmlWriter : IDisposable, IAsyncDisposable
{
    …
    // Existing
    public void Dispose() { } 
    public virtual void Close() { }
    // New
    public ValueTask DisposeAsync() { throw null; } 
    public virtual ValueTask CloseAsync() { throw null; }
}
...
public abstract class XmlReader : IDisposable, IAsyncDisposable
{
    …
    // Existing
    public void Dispose() { } 
    public virtual void Close() { }
    // New
    public ValueTask DisposeAsync() { throw null; }
    public virtual ValueTask CloseAsync() { throw null; }
}
```

**Comment by scalablecory** [comment]
If `CloseAsync` is going to call `Stream.FlushAsync`, can we make it take a defaulted `CancellationToken`?

**Comment by buyaa-n** [comment]
We are only using  overloads without `CancellationToken`

**Comment by terrajobst** [comment]
# Notes

* We should not make the reader `IAsyncDisposable`
* We should not have a `CloseAsync`
* We don't want a cancelable `DisposeAsync`, for scenarios that need that we add an overload to `FlushAsync` that accepts a cancellation token. We generally want to dispose resources even when you're cancelled.

```C#
namespace System.Xml
{
    public partial class XmlWriter : IAsyncDisposable
    {
        public ValueTask DisposeAsync();
        protected virtual ValueTask DisposeAsyncCore();
    }
}
```

**Comment by buyaa-n** [comment]
The API added with #35233 for Writer, as we don't need to implement IAsyncDisposable for Reader and Reader async disposal bug is tracked by other issue closing this one.

**Comment by John0King** [comment]
> [Video](https://www.youtube.com/watch?v=POdrqNOlY5g&t=0h38m26s)
> 
> * We should not make `XmlReader` implement `IAsyncDisposable`
> * We should not have a `CloseAsync`
 
@terrajobst I can not access youtube , could you  explain more on here ?

I see `XmlReader` is implement the `IDisposeable`  so  why it should not implement `IAsyncDisposeable`,

and which version of .net   I can use the `IAsyncDisposable` on `XmlWriter`

**Comment by buyaa-n** [comment]
> I see XmlReader is implement the IDisposeable so why it should not implement IAsyncDisposeable,

@John0King `XmlWriter` could have something need to write or flush before closing the stream, but for `XmlReader` no need any final operation except just close the stream, so just using `Dispose()` suffices for async sync streams both 

> and which version of .net I can use the IAsyncDisposable on XmlWriter

You can use it from Net 5.0 version, you can download 5.0 preview versions from [here](https://github.com/dotnet/installer#installers-and-binaries)

**Comment by John0King** [comment]
@terrajobst  @buyaa-n  I still recommand  `XmlReader` to implement the `IAsyncDisposeable`  because it access `Stream` and `Stream` has implement `IAsyncDisposeable`  ,  the `XmlReader` will crash too if some stream  throw on `Dispose` .
because 

reference souce  .net framework 4.8  `Stream` class
```C#
        // Stream used to require that all cleanup logic went into Close(),
        // which was thought up before we invented IDisposable.  However, we
        // need to follow the IDisposable pattern so that users can write 
        // sensible subclasses without needing to inspect all their base 
        // classes, and without worrying about version brittleness, from a
        // base class switching to the Dispose pattern.  We're moving
        // Stream to the Dispose(bool) pattern - that's where all subclasses 
        // should put their cleanup starting in V2.
        public virtual void Close()
        {
            /* These are correct, but we'd have to fix PipeStream & NetworkStream very carefully.
            Contract.Ensures(CanRead == false);
            Contract.Ensures(CanWrite == false);
            Contract.Ensures(CanSeek == false);
            */
 
            Dispose(true);
            GC.SuppressFinalize(this);
        }
```
