### ISSUE TITLE
Ignore invalid header line instead of throw exception

### ISSUE THREAD

**Issue by caihongxu** [dotnet/runtime#33610]
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L885

The logic here throws exception if an invalid header line is encountered, which caused issue when I talk to a web server that is not well designed. As a generic http client library, should the code logic be more robust so that invalid header lines are ignored instead of causing failure of the entire request?

**Comment by karelz** [comment]
Triage: @caihongxu do you have repro / example of the invalid header? We would need that to decide if / how we want to relax our validations.

**Comment by caihongxu** [comment]
Thanks for investigation. I no longer have this issue for my specific case. Closing for now and will re-file it if it becomes a problem again.
