### ISSUE TITLE
add DataTable.WriteCSV & DataTable.ReadCSV methods

### ISSUE THREAD

**Issue by bayesfactor** [dotnet/runtime#33628]
There is a [DataTable.WriteXML](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.writexml?view=netframework-4.8) and [DataTable.ReadXML](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.readxml?view=netframework-4.8) method, but no native functionality for CSVs. Since CSVs are pretty much a standard of data science, and users of [R](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) and python/[pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) are very used to passing data around as CSVs, it would be much more convenient to have a DataTable.WriteCSV() method than XML.

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to implement.
