### ISSUE TITLE
CoreCLR test run failure: missing System.Runtime.dll

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#33638]
I built using:
```
call build.cmd -subsetcategory libraries -c Release -arch x64
call build.cmd -subsetcategory coreclr -subset runtime-corelib-nativecorelib-tools -c Checked -arch x64
call src\coreclr\build-test.cmd x64 checked
```
then tests fail with missing System.Runtime.dll:
```
C:\gh\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\JIT\CodeGenBringUpTests\div2_d>C:\gh\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe div2_d.dll
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
And in fact `C:\gh\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.Runtime.dll` does not exist.

This is the System.Runtime.dll found in my build:
```
C:\gh\runtime\artifacts>dir /s /b System.Runtime.dll
C:\gh\runtime\artifacts\bin\netcoreapp\netcoreapp3.1-Release\System.Runtime.dll
C:\gh\runtime\artifacts\bin\netfx\netcoreapp5.0-Release\System.Runtime.dll
C:\gh\runtime\artifacts\bin\netstandard\netstandard2.0-Release\System.Runtime.dll
C:\gh\runtime\artifacts\bin\ref\microsoft.netcore.app\Release\System.Runtime.dll
C:\gh\runtime\artifacts\bin\ref\net472\System.Runtime.dll
C:\gh\runtime\artifacts\bin\ref\netcoreapp3.1\System.Runtime.dll
C:\gh\runtime\artifacts\bin\ref\netcoreapp5.0\System.Runtime.dll
C:\gh\runtime\artifacts\bin\ref\netstandard2.0\System.Runtime.dll
C:\gh\runtime\artifacts\bin\ref\netstandard2.1\System.Runtime.dll
C:\gh\runtime\artifacts\bin\System.Runtime\ref\netcoreapp5.0-Release\System.Runtime.dll
C:\gh\runtime\artifacts\obj\System.Runtime\ref\netcoreapp5.0-Release\System.Runtime.dll
```

What is missing?

**Comment by BruceForstall** [comment]
@jkoritzinsky @dotnet/runtime-infrastructure Any suggestions?

**Comment by BruceForstall** [comment]
If I follow those build steps with:
```
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-tools-all -c Release -runtimeconfiguration Checked -arch x64
call src\coreclr\build-test.cmd x64 checked generatelayoutonly
```
then System.Runtime.dll is there, and running the test works.

So what is the salient difference here? Why do the first steps (above) fail, but these steps succeed?

**Comment by jkoritzinsky** [comment]
In your first command when you’re just building libraries, that command tries to build libraries against a Release CoreCLR. From what it looks like, that command failed because you didn’t have a release build of S.P.CL. That’s why there’s only ref-assembly outputs one your output list.

In your second set of commands, you’re telling the libraries build to build against a checked CoreCLR. As a result, it finds the Checked Corelib build and can build the libraries.

Add the `-runtimeconfiguration Checked` flag to your first command in your first post and it should work.

**Comment by BruceForstall** [comment]
@jkoritzinsky ok, the issue is I didn't build the "whole" thing release first.

In https://github.com/dotnet/runtime/issues/32991, you say to do this:
```
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -runtimeconfiguration Debug
```

what if I want to build coreclr Checked and Release also? What is the minimal set of commands, to avoid unnecessary builds/rebuilds? Does the `libraries` subsetcategory need to be built more than once?

I.e., can I do this (1):
```
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -runtimeconfiguration Debug
call build.cmd -subsetcategory coreclr -subset runtime-corelib-nativecorelib -c Checked,Release
```
or (2):
```
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -runtimeconfiguration Debug
call src\coreclr\build-runtime.cmd all x64 Checked Release
```

or do I need to do something like this (that would appear to build libraries for each configuration) (3):
```
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -runtimeconfiguration Debug
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -runtimeconfiguration Checked
call build.cmd -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -runtimeconfiguration Release
```

?

**Comment by jkoritzinsky** [comment]
There's also a `-librariesconfiguration` flag like the `-runtimeconfiguration` flag. Also, libraries only needs to be built once. So you could do one of the two following:

```
./build -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -c Debug -c Checked -librariesconfiguration Release
```

or  (this one only builds libraries once so it will be faster):

```
./build -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib -c Release -c Debug -c Checked
./build -subsetcategory libraries -c Release
```

**Comment by BruceForstall** [comment]
@jkoritzinsky In your second example:
```
./build -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib -c Release -c Debug -c Checked
./build -subsetcategory libraries -c Release
```
The first command specified `-subsetcategory coreclr-libraries` but the `-subset` arg doesn't include any subset applicable to libraries (of which the only defined subset appears to be `all`). So does it build libraries at all, if a `-subset` is defined that doesn't include a libraries subset? If so, what is the difference between these two:
```
./build -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib -c Release -c Debug -c Checked
./build -subsetcategory coreclr-libraries -subset runtime-corelib-nativecorelib-all -c Release -c Debug -c Checked
```
?

You obviously can't build libraries first, then coreclr. Can you build coreclr first, then libraries? (In both cases, it appears coreclr tests need to be built last.)

**Comment by jkoritzinsky** [comment]
Shoot, that first command had a typo with the subsets as you noticed. It should have the `all` subset as well.

**Comment by BruceForstall** [comment]
Well, I'm still confused about the proper use of `-subsetcategory` and `-subset`, but there's no point keeping this issue open.

**Comment by jkoritzinsky** [comment]
I'm really sorry for the confusion.
