### ISSUE TITLE
Please remove SOS_README.md from every app's OutDir

### ISSUE THREAD

**Issue by wjk** [dotnet/runtime#33648]
This file is trite and pointless, but if I fail to install it alongside my app, it won't launch because this file is written into the deps.json file, and is therefore treated as vital. It comes from the `Microsoft.NETCore.App.Runtime.win-x64` runtime pack, and I am not entirely certain how to stop it from being included. Nor am I successful with removing it at build time using injected MSBuild targets. Could someone please point me to the correct way to do this (or submit a PR to remove that file from the runtime packs, which would be even better)? Thanks!

**Comment by tommcdon** [comment]
@mikem8361

**Comment by mikem8361** [comment]
PR https://github.com/dotnet/runtime/pull/33878
