### ISSUE TITLE
Change Environment.OSVersion to return actual OS version on Windows

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#33643]
`Environment.OSVersion` returns quirked OS version from app manifest on Windows. Consider changing it to return the actual OS version. It's not the recommended solution, but so many times I've seen folks say that Environment.OSVersion is buggy and then go and just do the P/Invoke themselves (or parse some other string-based representation that's doing it).

Related:
- https://github.com/dotnet/designs/pull/97#discussion_r393169688
- https://github.com/dotnet/runtime/issues/32575

**Comment by GrabYourPitchforks** [comment]
How do we intend on getting this information? The _HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion_ reg keys?

This needs to be coordinated with the Windows team. I don't know about the other keys, but they've said in crystal clear terms that _BuildLab_ and _BuildLabEx_ keys are intended to be human-readable strings used for debugging, and applications should under no circumstance attempt to parse these strings as they're not guaranteed stable across versions.

**Comment by jkotas** [comment]
`RtlGetVersion`. We are using this API in `System.Runtime.InteropServices.RuntimeInformation` already.

**Comment by dougbu** [comment]
With the property be quirked to avoid breaking applications expecting the old behaviour? Probably something of a corner case but&hellip?

**Comment by stephentoub** [comment]
> Will the property be quirked to avoid breaking applications expecting the old behaviour? Probably something of a corner case but…?

Wasn't planning on it.

**Comment by davidsh** [comment]
>Wasn't planning on it.

It should, though, be documented as a 'breaking-change' for .NET 5.
