### ISSUE TITLE
Does CipherSuitesPolicy require tls1.3 / openssl 1.1.1?

### ISSUE THREAD

**Issue by LarsAndreasEk** [dotnet/runtime#33649]
Hi,

I'm trying to specify allowed ciphers in a dotnet core 3.0 api, hosted on linux, in order to be compliant with PCI DSS.

Incoming connections/Kestrel: Setting SslServerAuthenticationOptions.CipherSuitesPolicy through the HttpsConnectionAdapterOptions.OnAuthenticate hook.

Outgoing connections: Setting SocketsHttpHandler.SslClientAuthenticationOptions.CipherSuitesPolicy

However, the CipherSuitesPolicy constructor throws System.PlatformNotSupportedException: CipherSuitesPolicy is not supported on this platform.

I read the code and it seems to [require tls1.3:](https://github.com/dotnet/runtime/blob/74124d4eafaf0ba64c42c214be33f7f2940a0259/src/libraries/System.Net.Security/src/System/Net/Security/CipherSuitesPolicyPal.Linux.cs#L35).

In my simple mind, it should be possible to specify cipher suites for tls1.2 also when the openssl version does not support tls1.3.

I'd appreciate any input you might have!

Some keywords:
- dotnet core 3.0
- linux
- openshift 3.11
- openssl 1.0.2

**Comment by vcsjones** [comment]
Yes, OpenSSL 1.1.1 or macOS has been mentioned previously as a requirement. https://github.com/dotnet/runtime/issues/28048#issuecomment-482764569

/cc @krwq

**Comment by LarsAndreasEk** [comment]
Thanks for bringing this to my attention. Missed that comment.

Br

**Comment by davidsh** [comment]
@wfurt

**Comment by davidsh** [comment]
@bartonjs

**Comment by wfurt** [comment]
@vcsjones  was right. It it documented 
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.ciphersuitespolicy.allowedciphersuites?view=netcore-3.1

I'm not sure if there is anything left to answer.

**Comment by bartonjs** [comment]
At this point, OpenSSL 1.0.2 is out of support (from the OpenSSL project).  We needed API from OpenSSL 1.1.1 to make it work nicely, and it wasn't worth the cost of doing it not-nicely given that 1.0.2 was almost out of support.

**Comment by vcsjones** [comment]
> I'm not sure if there is anything left to answer.

I think one thing to clarify, correct me if I am wrong, is that TLS1.3 is not a requirement. Checking for TLS1.3 is just the easiest xplat way to determine if `CipherSuitesPolicy` will work on the given platform (i.e. all non-Windows platforms that support TLS1.3 can also support `CipherSuitesPolicy`)

**Comment by bartonjs** [comment]
> I think one thing to clarify, correct me if I am wrong, is that TLS1.3 is not a requirement

Correct, it can modify SSL2-TLS1.2 ciphersuites as well as TLS 1.3 ciphersuites; but "system has TLS 1.3" and "system supports this feature" currently have the same truth table.

**Comment by wfurt** [comment]
OS X does not have TLS13 (yet), right? So the overlap is true for Linux.

**Comment by bartonjs** [comment]
Yeah, that does sound right.  What @wfurt said.

**Comment by bartonjs** [comment]
Just to restate:

macOS: The feature works.
Linux: The feature works with OpenSSL 1.1.1 (internally the code uses "has TLS 1.3" as a proxy for this test), does not work with OpenSSL 1.0.2.
Windows: The feature is unavailable.
