### ISSUE TITLE
Build icu for iOS/tvOS/Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#33654]
In order to support globalization on mobile, we would like a custom build version so that we know / can control the binary size and have more flexibility.  

- [x] Build/Package for iOS
- [x] Build/Package for tvOS
- [x] Build/Package for Android

**Comment by danmosemsft** [comment]
Per the plan in https://github.com/dotnet/runtime/issues/33652, it sounds like @akoeplinger will make this build, then @safern will handle consuming it and making tests pass.

Design in https://github.com/dotnet/designs/pull/102

**Comment by tarekgh** [comment]
CC @ jefgen

**Comment by tarekgh** [comment]
@akoeplinger, when you work on building ICU packages, it will be good to get in contact with @jefgen who has a connection with Apple guys and also he is the one building Windows ICU packages for us.

**Comment by steveisok** [comment]
This might be helpful as zoltan got ICU to build for wasm:

https://github.com/vargaz/runtime/commit/17affa3ac0137145240d25ea13aa3aad8a5fe388

**Comment by akoeplinger** [comment]
iOS ICU build was done with https://github.com/dotnet/icu/pull/33

**Comment by akoeplinger** [comment]
CI/packaging work for iOS was done with: https://github.com/dotnet/icu/pull/77

**Comment by akoeplinger** [comment]
tvOS build/packaging added in https://github.com/dotnet/icu/pull/78. Looks like we're done here :)
