### ISSUE TITLE
ISourceBlock<TOutput>/IReceivableSourceBlock<TOutput> should be marked for nullability

### ISSUE THREAD

**Issue by davkean** [dotnet/runtime#33666]
These interfaces should be marked as follows:

``` C#
interface ISourceBlock<TOutput> : IDataflowBlock
{
    …

    [return: MaybeNull]
    TOutput ConsumeMessage(DataflowMessageHeader messageHeader, ITargetBlock<TOutput>, out bool messageConsumed);
}
```

``` C#
interface IReceivableSourceBlock<TOutput> : ISourceBlock<TOutput>
{
    …

    bool TryReceive(Predicate<TOutput>? filter, [MaybeNullWhen(returnValue: false)] out TOutput item);
    bool TryReceiveAll([NotNullWhen(returnValue: true)] out IList<TOutput>? items);
}
```

This is not an exhaustive list of nullability annotations changes for dataflow, but ones I've encountered and had to suppress warnings for not matching the source interface after we annotated our blocks.

**Comment by stephentoub** [comment]
This library hasn't been annotated yet. The issue  https://github.com/dotnet/runtime/issues/2339 is tracking annotating all libraries in this repo, and  https://github.com/dotnet/runtime/pull/33644 is a PR I put up yesterday for dataflow.

**Comment by davkean** [comment]
Thanks!
