### ISSUE TITLE
Test failure:baseservices/threading/interlocked/compareexchange/CompareExchangeTClass/CompareExchangeTClass.sh

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#33660]
**Job:**
[runtime-coreclr crossgen2 outerloop:20200315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=560510&view=results)
**Error message:**
```
Managed assembly not found: No such file or directory

Return code: 1
Raw output file: /home/helixbot/work/AB4809D2/w/BA140A41/e/baseservices/threading/Reports/baseservices.threading/interlocked/compareexchange/CompareExchangeTClass/CompareExchangeTClass.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/AB4809D2/p/corerun CompareExchangeTClass.dll ''
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/AB4809D2/p
> /home/helixbot/work/AB4809D2/w/BA140A41/e/baseservices/threading/interlocked/compareexchange/CompareExchangeTClass/CompareExchangeTClass.sh
Expected: True
Actual: False
```
**Stack trace:**
`
at baseservices_threading._interlocked_compareexchange_CompareExchangeTClass_CompareExchangeTClass_._interlocked_compareexchange_CompareExchangeTClass_CompareExchangeTClass_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs:line 19540
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=560510&view=ms.vss-test-web.build-test-results-tab&runId=17650772&resultId=102400&paneView=debug

**Comment by davidwrighton** [comment]
This is no longer failing in outerloop, and looks like it was something wrong with the infrastructure in any case. Closing.
