### ISSUE TITLE
DateTime should accept 0 as a valid year input

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#33662]
Repro:
```csharp
var date = new DateTime(0, 1, 1);
```

Exception:
```
Unhandled exception. System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
```

**Comment by GrabYourPitchforks** [comment]
Per [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.datetime), the smallest possible value for `DateTime` is January 1, 0001 CE. This is also reflected via the [`DateTime.MinValue`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.minvalue) static member.

**Comment by Clockwork-Muse** [comment]
Note too that formally there isn't a year 0000 CE - the next previous year would be 0001 BCE

(unless we're talking proleptic years, which is handy for astronomers, but isn't how anybody else uses it)
In general, if you need better date/time support, use NodaTime.
