### ISSUE TITLE
System.Runtime.WindowsRuntime.sln refuses to open

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#33671]
It just hangs here forever:
![image](https://user-images.githubusercontent.com/2642209/76861410-f5389100-6832-11ea-9595-e943600ce47a.png)

cc: @Anipik, @ViktorHofer, @safern

**Comment by ViktorHofer** [comment]
@anipik @ercistj is this the same as https://github.com/dotnet/runtime/issues/33427?

**Comment by Anipik** [comment]
No its the problem with sln file. i will take a look and fix it
