### ISSUE TITLE
Enable android builds on CI

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#33689]

**Comment by am11** [comment]
@jkotas, would it make sense to add pipeline for CoreCLR+libraries Android builds in rootfs as well? If infra load becomes a problem for this additional matrix, perhaps we can add it as [scheduled job](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers) which runs over the weekend or bi-monthly bases. An additional advantage is that it would also exercise some code paths (e.g. `FEATURE_EVENT_TRACE=OFF`), which are currently not covered by any other pipeline runs.

**Comment by jkotas** [comment]
We should first enable the Mono/Xamarin configurations that are shipping for .NET 5. Once those are enabled, we can look at CoreCLR.

**Comment by steveisok** [comment]
Linking these together -> https://github.com/dotnet/core-eng/issues/9431

**Comment by steveisok** [comment]
PR merged -> https://github.com/dotnet/runtime/pull/34125
