### ISSUE TITLE
Optimize System.SpanHelpers using arm64 intrinsics

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#33707]
This item tracks the conversion of the System.SpanHelpers class to use arm64 intrinsics.

Related: #33308

**Comment by GrabYourPitchforks** [comment]
A nit about these functions that might not be immediately obvious:

`SpanHelpers.IndexOf(ref byte, ...)` and `SpanHelpers.IndexOf(ref char, ...)` are used as the workhorses for the `strlen` and `wcslen` implementations. The caller lies about the _length_ parameter and assumes that if the null character first occurs at page _n_, the `IndexOf` method will never attempt to dereference page _n + 1_. We have some limited unit tests for this scenario as shown below, but I wanted to make whoever attempts to intrinsicify this method aware of this behavior.

https://github.com/dotnet/runtime/blob/c0ddd1c5d1636de873398c8d9544e02289f95fec/src/libraries/System.Runtime/tests/System/StringTests.cs#L48-L68

**Comment by kunalspathak** [comment]
`IndexOf(char)`, `IndexOf(byte)` , `IndexOfAny(byte)` are now optimized with ARM64 intrinsics. We didn't optimize `SequenceCompareTo(byte)` and `SequenceEqual(byte)` because the existing SIMD vector implementation is fast enough and comparable with ARM64 intrinsics.
