### ISSUE TITLE
Dead store when accessing ref T property over a field

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#33741]
From [this `Box<T>` type](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3128/files#diff-5c63a3a37beacda1a8405c01553670df), when replacing the field with a property:

```csharp
[StructLayout(LayoutKind.Sequential)]
public sealed class Box<T>
    where T : struct
{
    private T Data;
        
    public ref T Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => ref Data;
    }
        
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Box<T> DangerousGetFrom(object obj)
    {
        return Unsafe.As<Box<T>>(obj);
    }
}
```

When used like so:

```csharp
public static int UnboxInt(object obj)
{
    return Box<int>.DangerousGetFrom(obj).Value;
}
```

The JIT produces the following asm x64:

```asm
; Core CLR v4.700.19.57202 (coreclr.dll) on amd64.
C.UnboxInt(System.Object)
    L0000: mov eax, [rcx]
    L0002: mov eax, [rcx+0x8]
    L0005: ret
```

Similarly, with a generic method returning `ref T`:

```csharp
[JitGeneric(typeof(int))]
public static ref T Unbox<T>(object obj)
    where T : struct
{
    return ref Box<T>.DangerousGetFrom(obj).Value;
}
```

The JIT produces another dead store:

```asm
; Core CLR v4.700.19.57202 (coreclr.dll) on amd64.
C.Unbox[[System.Int32, System.Private.CoreLib]](System.Object)
    L0000: mov eax, [rcx]
    L0002: lea rax, [rcx+0x8]
    L0006: ret
```

cc. @benaadams

**Comment by EgorBo** [comment]
I guess you use `sharplab` with some old coreclr runtime to inspect the asm code. I don't see that first mov in master.

**Comment by Sergio0694** [comment]
Yup, I was using sharplab.io - it's weird though, I tried both the usual x64 branch, as well as with the Roslyn branch from the 10th of March 2020 ([see here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMAdAEoCuAdjAJZhzEDCA9mAA40A2iAyogG40AxnCgBuALAAoXARIVqdBgElqiZmz4JBI8dOlYAzAQBMeRtIDe0vLYLGiANjw1qeAKqVgzAB6qYABTMwABWcEIweMEhAJQ2dtZSdskEAOx4AEK+ADyuMAB8xAAiEJQA5urkUADicDAAYgisQaExxABqEJzkcJJJdgC+0kNS0gDaPDAI5BEAMhAAnszkgfNLKwDSrgAmxHwAjj2KXTEAugbGUHBdcNummTkAKvnxtgDuABaIcHiPeCB4WDTCJWV54NgIGj8CDwX54EowCB9FJ2MFGPAIOAAMzhnW6cDBiRRtjGAFk6h9mNtlOxOAFyTBKdTaQB5Ni0ZiUKDEACCZTKmKgUChcFUnFcrjKZzByQqkQAvPkMdj4TCkWCRsS8GCyRSqTS2HSGUyDZw2Ryubz+YLhfxRZRxZRJdL+rZ0U4Hj5ss9VeVKjU6o1mtFwpFonFXXgicSsOlPFAIFiGDyoNksl7nvkWrFkYNhkA)) and I see the same result.
I wonder why that is 🤔

Anyway, if you can confirm that that's fixed in your current master than that's great to hear!
In that case, sorry for opening a bogus issue 😄

**Comment by EgorBo** [comment]
> I tried both the usual x64 branch, as well as with the Roslyn branch from the 10th of March 2020 ([see here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMAdAEoCuAdjAJZhzEDCA9mAA40A2iAyogG40AxnCgBuALAAoXARIVqdBgElqiZmz4JBI8dOlYAzAQBMeRtIDe0vLYLGiANjw1qeAKqVgzAB6qYABTMwABWcEIweMEhAJQ2dtZSdskEAOx4AEK+ADyuMAB8xAAiEJQA5urkUADicDAAYgisQaExxABqEJzkcJJJdgC+0kNS0gDaPDAI5BEAMhAAnszkgfNLKwDSrgAmxHwAjj2KXTEAugbGUHBdcNummTkAKvnxtgDuABaIcHiPeCB4WDTCJWV54NgIGj8CDwX54EowCB9FJ2MFGPAIOAAMzhnW6cDBiRRtjGAFk6h9mNtlOxOAFyTBKdTaQB5Ni0ZiUKDEACCZTKmKgUChcFUnFcrjKZzByQqkQAvPkMdj4TCkWCRsS8GCyRSqTS2HSGUyDZw2Ryubz+YLhfxRZRxZRJdL+rZ0U4Hj5ss9VeVKjU6o1mtFwpFonFXXgicSsOlPFAIFiGDyoNksl7nvkWrFkYNhkA))

That combobox is for Roslyn, the runtime is the same (don't know how to convert "Core CLR v4.700.19.46205" into a commit)

**Comment by Sergio0694** [comment]
Ah, you're right, I just assumed it'd also always grab a recent version of CoreCLR as well when doing so (since some new features also need runtime support). I guess that's not always the case though.

Well glad to hear this is actually already fixed then, thank you for your time! 😊
Have a nice day!
