### ISSUE TITLE
RegularExpressionAttribute should allow setting RegexOptions

### ISSUE THREAD

**Issue by Ziriax** [dotnet/runtime#33755]
We often see pricing decimal places validation like:

```[RegularExpression(@"\d+(\.\d{2})?", ErrorMessage = "Please enter an amount with two decimal places")]```

However, this isn't culture invariant.

Therefore, it would be very handy if the `RegularExpressionAttribute` allows setting the `RegexOptions`, so we can make the validation culture invariant.

**Comment by danmosemsft** [comment]
@Ziriax could you please update your proposal per the example in https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md?

**Comment by ajcvickers** [comment]
We have no plans to add additional functionality to data annotations.
