### ISSUE TITLE
R2R test failure: failed to crossgen Microsoft.Extensions.Options.ConfigurationExtensions.dll

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#33760]
The R2R test legs are failing with failure to crossgen:
```
Microsoft.Extensions.Options.ConfigurationExtensions.dll
Microsoft.Extensions.Options.DataAnnotations.dll
```

https://dev.azure.com/dnceng/public/_build/results?buildId=563316&view=logs&j=0589f720-bbe2-587b-3b91-78c5f6628f2f&t=b0177560-80d1-5f10-4d58-529397c9d415
https://dev.azure.com/dnceng/public/_build/results?buildId=564341&view=logs&j=a98fdc64-2e92-55c8-b9d3-0db752ccb04d&t=09d63f54-2c8a-56fd-655f-a1cda215a841

**Comment by BruceForstall** [comment]
@sandreenko You saw this yesterday

@dotnet/runtime-infrastructure

**Comment by safern** [comment]
These are new assemblies. I wonder if they're missing something, or if they are somehow special. cc: @ericstj @maryamariyan

**Comment by ericstj** [comment]
Why are these even being crossgen'ed they aren't part of the base shared framework.

Here's the error:
```
Precompiling /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/Tests/Core_Root/Microsoft.Extensions.Options.DataAnnotations.dll
Unable to precompile /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/Tests/Core_Root/Microsoft.Extensions.Options.DataAnnotations.dll, exit code is 33.
Command-line: /__w/1/s/artifacts/bin/coreclr/Linux.arm.Checked/x64/crossgen /Platform_Assemblies_Paths /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/Tests/Core_Root /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/Tests/Core_Root/Microsoft.Extensions.Options.DataAnnotations.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: Could not load file or assembly 'Microsoft.Extensions.Options, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
 (0x80070002 (COR_E_FILENOTFOUND))
```

Looks to me like CrossGen isn't being passed the path for all dependencies.

**Comment by ericstj** [comment]
Ok, the reason for this failure is because Options isn't being built:
https://github.com/dotnet/runtime/blob/f80a5147ef7662c3238275568c9dad7655a9684f/src/libraries/Directory.Build.props#L19

I think that `Options.*` will not find `Options\`

**Comment by maryamariyan** [comment]
Please refer to #33563 description.

```
test (reason for later: #33563 (comment))

Microsoft.Extensions.DependencyInjection
Microsoft.Extensions.Options (Options tests needs ref to DI)
```

Enabling DI.tests enables DI and in turn that enabled Options, and that should unblock this issue.

**Comment by ericstj** [comment]
Thanks for catching this @maryamariyan .

@BruceForstall do you really want to be crossgen'ing these things that aren't part of the base product?  Is it just to get some test coverage of additional NuGet packages?

**Comment by BruceForstall** [comment]
Looks like `build-test.cmd` and `build-test.sh` blindly crossgen all the assemblies in `CORE_ROOT` with the pattern `System.*.dll` or `Microsoft.*.dll`, with a few hard-coded exceptions. This is part of test legs that also crossgen each individual test before running it.

There are two goals: (1) make sure crossgen is successful (no asserts/crashes) across many assets, (2) make sure tests run successfully with everything crossgen'ed.

**Comment by janvorli** [comment]
I've added the requirement of the crossgening of the assemblies in CORE_ROOT to succeed few months ago since we were silently failing to crossgen some of them when running coreclr crossgen tests due to bugs in crossgen / crossgen2 and we have never realized that.

**Comment by ericstj** [comment]
I guess this will get better when we stop putting packages in the test shared framework.

**Comment by BruceForstall** [comment]
We need a solution so this job succeeds. Do we need to add some assemblies to an exclusion list?

**Comment by trylek** [comment]
I believe that today the easiest way forward is to add manual exclusions for those assemblies that are known to crash compilation. I can prepare a PR fixing that.

**Comment by ericstj** [comment]
We're already fixing this, no need to disable.

**Comment by maryamariyan** [comment]
This issue should now be fixed as of https://github.com/dotnet/runtime/pull/33816

**Comment by ericstj** [comment]
Last night's build passed.
