### ISSUE TITLE
Use HashCode instead of manual hashcode combining

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33762]
Find `GetHashCode` implementations doing manual hash code combination and recommend switching to `HashCode.Combine`.

**Category**: Reliability

**Comment by stephentoub** [comment]
Related, note that Visual Studio will now generate GetHashCode overrides using Hashcode.Combine if it's available:

![image](https://user-images.githubusercontent.com/2642209/77183604-f8d34e80-6aa4-11ea-9a40-910d73ce6b44.png)

![image](https://user-images.githubusercontent.com/2642209/77183634-04bf1080-6aa5-11ea-8131-c26e946206d0.png)

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Not Applicable

**Comment by stephentoub** [comment]
> Fixer: Not Applicable

I think it is.  Maybe it couldn't be offered in all cases, but I suspect the analyzer would be looking for specific patterns, and given those patterns, the fixer could fix them. e.g. transforming `x.GetHashCode() ^ y.GetHashCode()` into `Hashcode.Combine(x, y)`.

**Comment by terrajobst** [comment]
The heuristics we can look for is (1) two calls to `field.GetHashCode()` and zero references to `HashCode`.

Instead of making this an analyzer/fixer, we could make this a refactoring suggestion on overrides of `GetHashCode()`, associated with the identifier of the method.

**Comment by stephentoub** [comment]
This is already implemented as IDE0070:
https://github.com/dotnet/roslyn/tree/79cad10b3ee06b382f634094da0d0d99c68d93c0/src/Features/Core/Portable/UseSystemHashCode
though it looks for only very specific patterns.

**Comment by stephentoub** [comment]
I'm going to close this.  I expect any further work we'd want to do here would be augmenting IDE0070 based on feedback, and with IDE0070 designed/implemented in dotnet/roslyn, that's something better left in that repo,
