### ISSUE TITLE
Do not pass value types to Object.ReferenceEquals

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33766]
Calls to `ReferenceEquals` where we can detect a value type is being passed in are invariably wrong, as the value type will be boxed, and regardless of its value, `ReferenceEquals` will always return `false`.

**Category**: Reliability

**Comment by bartonjs** [comment]
Fixed in https://github.com/dotnet/roslyn-analyzers/pull/3368.

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Not Applicable
