### ISSUE TITLE
Pass constants to parameters marked as [ConstantExpected]

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33771]
Consider adding an `[ConstantExpected]` attribute that could be put on parameters to indicate that arguments should be constants rather than variables.  See https://github.com/dotnet/runtime/issues/30740#issuecomment-594111037 for details.
### The attribute proposal
```cs
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class ConstantExpectedAttribute : Attribute
    {
        public object? Min { get; set; }
        public object? Max { get; set; }
    }
}
```
### Usage and Diagnostic examples
```cs
public static class C
{
    public static void MyBool1([ConstantExpected] bool b) { }
    public static void MyLong1([ConstantExpected] long b) { }
    public static void MyLong2([ConstantExpected(Min = -5, Max = 10)] long b) { }
    public static void MyFloat1([ConstantExpected] float b) { }
    public static void MyFloat2([ConstantExpected(Min = -5.3f, Max = 10.1f)] float b) { }

    // Might want to warn for the negative values and out of range values
    public static void MyInvalidUshort([ConstantExpected(Min = -5, Max = -1)] ushort b) { }
    public static void MyInvalidRange([ConstantExpected(Min = 5, Max = -5)] int b) { }
    // flag any ref type usage as not applicable
    public static void MyString([ConstantExpected] string b) { }

    // Diagnostics examples
    public static void Test(long b, ushort u)
    {
        // OK
        const long a = 10;
        MyLong1(a);
        MyLong2(a);
        MyLong1(1L);
        MyLong2(2L);
        MyInvalidUshort(1);
        const ushort us = 0;
        MyInvalidUshort(us); // Flag

        MyLong1(b); // Flag
        MyLong2(b); // Flag

                
        MyLong2(20); // Flag, out of range
        MyInvalidUshort(u); // Flag
        MyInvalidUshort(10); // Flag, out of the range
    }
}
```
**Category**: Reliability
**Severity**: Info

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Not Applicable

**Comment by jeffhandley** [comment]
This issue should capture:

1. The attribute itself (getting that through the API review)
2. Creation of the analyzer
3. Identification of some instances where the attribute should be applied

The work to apply the attribute (especially through intrinsics) could be a separate issue/PR.

**Comment by jeffhandley** [comment]
@tannergooding Do you think this is a must-have attribute & analyzer for .NET 5 to round out the intrinsics work we've done, or do you think this could be added in .NET 6?

**Comment by tannergooding** [comment]
It is not. The hardware intrinsics don't even require constant inputs, they just benefit from them and you will get very poor codegen if you don't.
We shipped .NET Core 3.0 without such an attribute and I'm sure we'll be fine if we do the same for .NET 5.

**Comment by jeffhandley** [comment]
Thank you, @tannergooding. I'm going to move this to Future so that we can consider it for .NET 6 then.

**Comment by Mrnikbobjeff** [comment]
How would we catch expressions which are evaluated at compile time? I.e. `2*2*2` would be folded to 8 and I guess emit the same code as if we would manually fold it, but manually incorporating folding rules to detect if the expression may become a constant would be difficult or am I missing something?

**Comment by carlossanlop** [comment]
@GrabYourPitchforks @tannergooding  should we have a separate API proposal for the attribute itself? Or in other words, should we reopen https://github.com/dotnet/runtime/issues/33814 for that purpose specifically? I don't mind if we can get both the attribute and the analyzer approved in one single issue.

### Attribute questions

- The name `ConstantExpected` makes more sense. Levi proposed `Immediate` in the other issue.

- Here is an example of an API Levi shared in the other issue, which could benefit from having both the new proposed attribute.
```cs
namespace System.Runtime.Intrinsics.X86
{
    public abstract class Sse2 : Sse
    {
        public static Vector128<short> ShiftLeftLogical(Vector128<short> value, [ConstantExpected(/* Min = 0, Max = 15 */)] byte count);
    }
}
```
A proposal of the attribute could be:
```cs
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class ConstantExpectedAttribute : Attribute
    {​​​​
        public int? Min {​​​​ get; set; }​​​​
        public int? Max {​​​​ get; set; }​​​​
    }​​​​
```
- @GrabYourPitchforks Do we want the attribute to receive limits as arguments, like you added in your example as a comment (Min/Max)? Is the type only expected to be an integer? Is this even possible if we don't know the specific parameter type? If we have constant number types, we could find the default minimum and maximum values, but for other types like string, which could also be constant, it wouldn't make sense to try to find a min/max.

- In which assembly/namespace would the attribute live?

### Analyzer questions

- The analyzer should have an `Info` severity, since it's allowed to pass a non-constant even if the parameter has the attribute. Agreed?

- Could we make the analyzer mandatory for Intrinsics APIs only? And if we could, would be interested in doing that?

**Comment by GrabYourPitchforks** [comment]
If we wanted min / max, they could be typed as _object?_. This would allow `byte`, `sbyte`, `int`, `double`, etc. parameters. This isn't being checked at runtime - only compile-time - and it's straightforward enough for the compiler to handle attribute properties typed as object. For string literals, min / max would stay null.

**Comment by tannergooding** [comment]
I think that this issue is fine for tracking the API, and I believe that was @terrajobst intent when he tagged it `api-needs-work`.

**Comment by carlossanlop** [comment]
Ping @tannergooding @GrabYourPitchforks . Would you mind answering[ these questions](https://github.com/dotnet/runtime/issues/33771#issuecomment-736088234)? Does the proposed attribute make sense? Can you please share some usage examples where this could be useful?

**Comment by tannergooding** [comment]
I'd like to better see some use-cases and the expectations of the attribute.

At least in the case of the hardware intrinsics, a constant is not required, it is only beneficial/recommended and so passing a constant is basically a performance feature.
If that is always the expected usage (passing a constant is recommended for perf), then I think it is fine as is. However. if we ever expect it to mean passing a constant is required for correctness, I think that might be a different API altogether.

I think the Min/Max values make sense as there are some hardware intrinsics that support the entire input range and others that may fail if the range isn't correct.

**Comment by carlossanlop** [comment]
@tannergooding @GrabYourPitchforks

- What if we made the attribute generic? Seems that generic attributes are a preview feature.
- Min and Max could be made nullable to cover the case of string.
- For value types, the user can specify the limit and they will get warned if they go beyond the data type limit.
- Should we warn if the attribute is used for other reference types that are not string?

```cs
namespace N
{
    // Applies to all the value type primitives and also strings
    // https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public  class ConstantExpectedAttribute<T> : Attribute
    {
        public T? Min { get; set; }
        public T? Max { get; set; }
    }

    public static class C
    {
      public static void MyBool1([ConstantExpected<bool>] bool b){}
      // Do Min and Max make sense for bool?
      public static void MyBool2([ConstantExpected<bool>(Min = false, Max = false)] bool b){}

      public static void MyLong1([ConstantExpected<long>] long b){}
      public static void MyLong2([ConstantExpected<long>(Min = -5, Max = 10)] long b){}
      public static void MyFloat1([ConstantExpected<float>] float b){}
      public static void MyFloat2([ConstantExpected<float>(Min = -5.3f, Max = 10.1f)] float b){}

      // Invalid: CS0182 flags the -1
      // public static void MyInvalidUshort([ConstantExpected<ushort>(Min = -1, Max = 2)] ushort b);

      public static void MyString([ConstantExpected<string>] string b){}

        public static void Main(string[] args)
        {
          // OK
          const long a = 10;
          MyLong1(a);
          MyLong2(a);
          MyLong1(1L);
          MyLong2(2L);

          long b = 4;
          MyLong1(b); // Flag
          MyLong2(b); // Flag

          MyLong2(20); // Flag, out of range
        }
    }
}
```

**Comment by terrajobst** [comment]
I'm not sure I like the generic because it seems a bit over engineered and would now require specifying the type even if no `min`/`max` values are necessary.

Also, we would never be able to use the attribute (even if defined internally) on .NET Standard 2.0.

```C#
namespace System.Diagnostics.CodeAnalysis;

[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
public sealed class ConstantExpectedAttribute : Attribute
{
    public object? Min { get; set; }
    public object? Max { get; set; }
}
```

**Comment by buyaa-n** [comment]
A new proposal added to the description

**Comment by bartonjs** [comment]
The attribute looks good as proposed (except we changed the namespace)

```C#
namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class ConstantExpectedAttribute : Attribute
    {
        public object? Min { get; set; }
        public object? Max { get; set; }
    }
}
```

For the analyzer:
* Category: Performance
* The default diagnostic for passing a non-constant value: Warning
* The default diagnostic for a constant that's out of range: Warning
* The default diagnostic for a constant that's out of range by composition with another ConstantExpected attribute: Warning
* The default diagnostic for passing min/max that make no sense (wrong type, inverted, is a reference type, etc): Error
* So far we've identified two distinct diagnostic IDs needed, one for "you used the attribute wrong" (the error) and one for "you're calling this method wrong" (all of the others).  They can, of course, be subsetted as needs demonstrate.

**Comment by zvrba** [comment]
I'm late to the discussion, but in relation to use with intrinsics, I'd prefer something like `void DoSomething(int runtimeValue, const byte imm)`. Passing in anything than a compile-time constant for `imm` would generate a compile error.

It could possibly be extended to have a generic constraint `where T : const int` and subsequently one could write "metacode" that unrolls loops at compile-time like one does with templates in C++. But I guess there are source generators for that now.

**Comment by tannergooding** [comment]
That would be a breaking change and go against the goals of hardware intrinsics in .NET. It also has several issues, including that you couldn't write code that works with values that become constant after inlining.

**Comment by wzchua** [comment]
I would like to be assigned this.

Does the work start with getting the attribute merged into runtime repo, then writing the analyzer? Are there other steps for the attribute?

**Comment by buyaa-n** [comment]
> Does the work start with getting the attribute merged into runtime repo, then writing the analyzer?

Yes start with the attribute getting merged to the runtime repo, for the analyzer you can use a mock attribute for testing until you were able to consume it in the analyzers repo

**Comment by buyaa-n** [comment]
Also, there could be a step "applying the attribute" to the APIs in the runtime repo but that is not needed to be covered by this issue

**Comment by wzchua** [comment]
Do we allow composition of different types? Like what should the analyzer do with something like below:
```cs
public static void TestMethod([ConstantExpected(Min=0, Max=5)] uint constant)
{
    TestMethod2(constant);
}
public static void TestMethod2([ConstantExpected(Min=0, Max=10)] int val)
{
}
```

**Comment by wzchua** [comment]
Also, does casting influence the analyzer?
```cs
TestMethod((uint)100);
```

**Comment by buyaa-n** [comment]
> Do we allow composition of different types? Like what should the analyzer do with something like below:

Not sure I follow the question, though I believe the analyzer should warn on `TestMethod2(constant);` invocation because it is not passing a constant
```cs 
public static void TestMethod([ConstantExpected(Min=0, Max=5)] uint constant)
{
    TestMethod2(constant); // should warn here as constant expected for 'val' parameter
}
public static void TestMethod2([ConstantExpected(Min=0, Max=10)] int val)
{
}
```

> Also, does casting influence the analyzer?
> ```cs
> TestMethod((uint)100);
> ```

Not sure what issue you are having here, but `TestMethod((uint)100);` and `TestMethod(100);` in your example should behave the same

**Comment by wzchua** [comment]
It seems we want to be able to compose the ConstantExpectedAttribute using another ConstantExpectedAttribute. I'm clarifying what should be done if the types don't match.

I guess I'm asking does casting make it not a constant?
It might be more relevant for the composition case. 
I guess it is not an issue for the literal scenario.

**Comment by buyaa-n** [comment]
Good question, tagging @tannergooding for anwser

**Comment by wzchua** [comment]
Given,
```cs

using System;
using System.Diagnostics.CodeAnalysis;
#nullable enable

public class Test
{
    public interface ITest<T>
    {
        T Add(T operand1, [ConstantExpected] T operand2);
    }
    public abstract class AbstractTest<T>
    {
        public abstract T Add2(T operand1, [ConstantExpected] T operand2);
    }
    public class GenericInt : AbstractTest<int>, ITest<int>
    {
        public int Add(int operand1, int operand2)
        {
            return 0;
        }
        public override int Add2(int operand1, int operand2)
        {
            return 0;
        }
    }
}
```
I assume the analyzer should warn for not having `[ConstantExpected]` in the more concrete type parameter?

**Comment by tannergooding** [comment]
> I assume the analyzer should warn for not having [ConstantExpected] in the more concrete type parameter?

I'd expect so, yes. There is some "wonkiness" here though, in that `[ConstantExpected]` is "impossible" to fulfill for non-primitive types. So if `T` were a `Guid`, for example, we'd need to decide what happens.

**Comment by wzchua** [comment]
Ok, i have written the tests for many of the cases.
For cases where the attribute is applied to T, setting Min Max is an error, and warning at callsite only appears if concrete type for T can be constant

**Comment by deeprobin** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/5766#issuecomment-1049290656
@bartonjs Do we need a VB analyzer?

/cc @wzchua

**Comment by bartonjs** [comment]
@deeprobin The general stance is "most analyzers should Just Work for both C# and VB, so you should add VB tests and enjoy that it Just Worked... but if your analyzer requires special VB code it's probably not worth it"
