### ISSUE TITLE
Avoid incorrect use of ValueTask/ValueTask<T>

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33776]
The rule should detect cases where there's a strong likelihood a `ValueTask{<T>}` is being used incorrectly, e.g. where a single instance may be awaited multiple times, where an instance may be awaited and then also returned out of a method, where an instance may have `.GetAwaiter().GetResult()` called on it when it's not obviously already completed, when one is stored into a static field or a dictionary or some other publishing mechanism, etc.

**Category**: Reliability

**Comment by stephentoub** [comment]
This has already been done: https://github.com/dotnet/roslyn-analyzers/pull/3001
