### ISSUE TITLE
Do not use OfType<T>() with impossible types

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33770]
Warn if use of `OfType<T>()` would provably result in an empty sequence, because we can see that the input type in the sequence will never be the specified type.

**Category**: Reliability
**Suggested severity**: Warning 

UPDATE FROM [roslyn-analyzer issue](https://github.com/dotnet/roslyn-analyzers/issues/3608) :

The following will always throw an InvalidCastException at runtime:

```csharp
new int[] { 1 }.Cast<string>().ToList();
new float[] { 1f }.Cast<double>().ToList();
new int[] { 1 }.Cast<long>().ToList();
```
Perhaps worse, this will return an enumerable that fully enumerates the source and then returns no items silently:
```cs
enumerableOfApple.OfType<Orange>()
```
Both of these situations are likely to be a mistake.

Ther is a [PR](https://github.com/dotnet/roslyn-analyzers/pull/4328) out for review

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Not Applicable

**Comment by drewnoakes** [comment]
Possibly at the same time, though via a different diagnostic ID: calling `OfType<T>()` on an `IEnumerable<T>` where the `T` is identical or assignable is redundant.

```c#
Enumerable.Range(1, 100).OfType<int>();

myString.Split(",").OfType<object>();
```

**Comment by fowl2** [comment]
I did a little prototype for fun over at https://github.com/dotnet/roslyn-analyzers/issues/3608

**Comment by jnyrup** [comment]
@drewnoakes Note that for reference types this *can* be used as a less clear way of writing`Where(e => e != null)`.

**Comment by bartonjs** [comment]
Approved as proposed

Category: Reliability
Suggested severity: Warning
