### ISSUE TITLE
Pass TaskContinuationOptions to the correct constructor

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33775]
`TaskCompletionSource` has a constructor that takes a `TaskCreationOptions options` and another constructor that takes an `object state`.  There's a similar enum to `TaskCreationOptions` that's only meant to be used with `ContinueWith`: `TaskContinuationsOptions`.  It's easy to accidentally pass a `TaskContinuationOptions` to the TCS ctor, in which case it binds to the overload accepting an `object` and isn't treating as options at all (and, adding insult to "your options aren't respected" injury, it also boxes).

**Category**: Reliability

**Comment by stephentoub** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/3059

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Medium

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/roslyn-analyzers/pull/3059.
