### ISSUE TITLE
Avoid unnecessary string concatenation

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33783]
Various patterns of string concatenation generate unnecessary intermediate strings, e.g. `string result = s1 + s2; return result + s3;` will create an unnecessary string allocation, as will `string result = s1 + s2; if (condition) result+= s3; return result;` which could be rewritten as `string result = condition ? s1 + s2 + s3 : s1 + s2;`.  The rule would find and offer fixes for such patterns.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Large
* Fixer: Large

**Comment by carlossanlop** [comment]
[TODO] Define more positive and negative cases. For now, we only have the ones suggested in the description. cc @buyaa-n 

- Suggested category: Performance
- Suggested severity: Info

Examples:
```cs

// A) String definition and immediate return (no other update to the string in between)
// Before
string result1 = s1 + s2;
return result1 + s3;

// After
return s1 + s2 + s3;


// B) String definition and immediate edit guarded by condition (no other update to the string in between)
// Before
string result2 = s1 + s2;
if (condition)
{
    result2 += s3;
}

// After
string result2 = condition ? s1 + s2 + s3 : s1 + s2;
```

**Comment by bartonjs** [comment]
It's not clear that the resulting code is "better", especially if it inlines a concatenation across conditional statements (duplicated code costs vs performance benefits).  There may be room for "StringBuilder would be better here", but they're hard to describe.

Separating out the unconditional (unobserved) concatenation into a distinct analyzer/diagnostic would be less controversial; but the conditional cases are definitely more complicated.

**Comment by carlossanlop** [comment]
This analyzer covers too many scenarios, and as mentioned in the video discussion, a user concatenating strings might not be very interested in improving performance. So unless we come up with a better delimited scenario, we don't think there's much value coming from this.
