### ISSUE TITLE
Prefer string.AsSpan() over string.Substring() when parsing

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33784]
The rule should flag instances of a pattern like `int.Parse(str.Substring(...))` and instead switch to using the span-based `int.Parse(str.AsSpan(...))`.  This would apply to all of the primitive types, and more generally potentially anything that has an overload taking a `ReadOnlySpan<char>` instead of a `string`.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Small

**Comment by GrabYourPitchforks** [comment]
Seems reasonable. We should figure out how much we want our analyzers (especially our on-by-default analyzers) to push people into using span. Using `ROS<char>` increases the concept count for scenarios which are currently very simple.

**Comment by bartonjs** [comment]
* Find argument expressions that are str.Substring(...) and there's an overload (or the same overload) that accepts ReadOnlySpan&lt;char> in that position
* Suggest changing Substring to AsSpan for the call

Category: Performance
Suggested severity: Info

**Comment by carlossanlop** [comment]
@Mrnikbobjeff also approved in case you already started working on this. Let us know if you'd like to get this issue assigned to you.

**Comment by Mrnikbobjeff** [comment]
> @Mrnikbobjeff also approved in case you already started working on this. Let us know if you'd like to get this issue assigned to you.

I am currently working on porting my analyzers to be IOperation analyzers to be inline with the pattern already established. While I have a working implementation for a c# analyzer and fixer I still need to port the analyzer at least for this to be viable.

**Comment by carlossanlop** [comment]
Would you like me to assign this to you @Mrnikbobjeff or should i mark it up-for-grabs instead?

**Comment by carlossanlop** [comment]
I closed https://github.com/dotnet/runtime/issues/33778 in favor of this one (it was an identical approved proposal).

Note to whoever decides to work on this: Please take a look at [this comment in the dup issue](https://github.com/dotnet/runtime/issues/33778#issuecomment-761167449), since it contains a list of cases this analyzer should be able to address.

**Comment by NewellClark** [comment]
I would like to be assigned to this. I'll start work on it immediately.

**Comment by AraHaan** [comment]
How does one enable this ``AsSpan`` diagnostics for netstandard2.0+ for using it over ``Substring``?
