### ISSUE TITLE
Don't guard Dictionary<K, V>.Remove(key) by ContainsKey(key)

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33797]
The pair can be combined into just the `Remove` call.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Medium

**Comment by carlossanlop** [comment]
Suggested severity: Info

#### Example

```cs
// Before
        public void RemoveValue(Dictionary<string, int> data, string key)
        {​​
            if (data.ContainsKey(key))
                data.Remove(key);
            // or
            if (data.ContainsKey(key))
                data.Remove(key, out var value);
        }​​

// After
        public void RemoveValue(Dictionary<string, int> data, string key)
        {​​
            data.Remove(key);
            // or
            data.Remove(key, out var value1);
        }​​

```

Avoid triggering the analyzer if there's additional code inside the if statement:

```cs
        public void DontTrigger(Dictionary<string, int> data, string key, Dictionary<string, int> otherData)
        {​​
            if (data.ContainsKey(key))
            {
                otherData[key] = data[key]; // Unrelated code
                data.Remove(key);
            }
        }​​
```

**Comment by terrajobst** [comment]
* Makes sense.

We could further improve the fixer to handle this as well:

```C#
// Before
if (data.ContainsKey(key))
{
    data.Remove(key);
    SomeUnrelatedCode();
}
// After
if (data.Remove(key))
{
    SomeUnrelatedCode();
}
```

But it's not necessary -- we can start simple and take it from there.

**Comment by chucker** [comment]
I have the analyzer mostly ready to go for both C# and VB. No fixer yet, though.

Do you want a PR, or should I first write a fixer?

**Comment by carlossanlop** [comment]
Thanks for your help, @chucker! I'm assigning the issue to you. Feel free to submit a PR whenever you get a chance, and we can take a look.

**Comment by chucker** [comment]
(The PR linked above does now include the fixer, too.)

**Comment by paulomorgado** [comment]
is there an issue like this for `HashSet<T>`?

* Don't guard `HashSet<T>.Remove(item)` by `HashSet<T>.Contains(item)`?
* Don't guard `HashSet<T>.Add(item)` by  `HashSet<T>.Contains(item)`?

**Comment by carlossanlop** [comment]
@paulomorgado if you can't find any issue, please create an API proposal.

**Comment by paulomorgado** [comment]
An API proposal????
