### ISSUE TITLE
Extract array of const to static readonly field

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33794]
Arrays of `const` passed to known methods on types like `System.String` (e.g. `IndexOfAny(new[] { ',', '.' })`) can be lifted out to `static readonly` fields.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Large

**Comment by jeffhandley** [comment]
Moving this one out of .NET 5, but this would be a good warmup analyzer for someone, and it would be a high-value analyzer in .NET 6 because it applies to some recently added APIs.

**Comment by jeffhandley** [comment]
The hardest part of this one will be coming up with the list of APIs we want this to target--using a heuristic is the recommended approach. Beyond that, we think the analyzer will be pretty easy; the fixer will have some edge cases to consider for how to rewrite the code to reflect the definition/usage of the const--simply extracting the const won't necessarily be straightforward, and there will need to be an ordered list of approaches to apply.

**Comment by jakub-klima** [comment]
Cannot optimization like this be done by the compiler?

**Comment by teo-tsirpanis** [comment]
Such optimization could be automatically done by the compiler for methods that accept a `ReadOnlySpan`.

**Comment by steveberdy** [comment]
@buyaa-n I would like this assigned to me. Thanks.
