### ISSUE TITLE
Prefer Memory<T> overloads for Stream.Read/WriteAsync

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33790]
Find places where `await stream.Read/WriteAsync(array, offset, length, ...)` are used and recommend they be replaced by calls to the overloads that take `{ReadOnly}Memory<byte>`, to benefit from the return type being `ValueTask<int>`.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Medium

**Comment by carlossanlop** [comment]
Merged the analyzer and the fixer. Reopening because there are still two things pending:
- Documentation
- Executing within dotnet/runtime.
