### ISSUE TITLE
Cache result of virtual property

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33795]
Virtual properties are rarely inlined by the JIT and result into expensive virtual calls. Detect cases where the call can be hoisted and the return value reused.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Medium

**Comment by buyaa-n** [comment]
@terrajobst @elinor-fung could you help with examples or how we detect `cases where the call can be hoisted and the return value reused.`?
