### ISSUE TITLE
Remove redundant configuration from [DllImport] declaration

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33808]
**Immo** proposal here: https://github.com/dotnet/runtime/issues/33808#issuecomment-988300574

Flag places where an attribute is set on a DllImport that's already the default value.

**Category**: Style

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Small

**Comment by carlossanlop** [comment]
@terrajobst can you please clarify what you meant in the description? What does it mean "an attribute is set on a DllImport"?

cc @AaronRobinsonMSFT since you linked https://github.com/dotnet/runtime/issues/34831 and maybe you understand what the description means.

**Comment by alexrp** [comment]
E.g. `[DllImport(..., SetLastError = false)]` or `[DllImport(..., CharSet = CharSet.Ansi)]` (etc) are pointless because those are already the default values.

**Comment by AaronRobinsonMSFT** [comment]
@carlossanlop the response from @alexrp is what I interpreted as the intent of this issue.

**Comment by carlossanlop** [comment]
Ok thanks. Then these are the default values set for the public fields of the `DllImportAttribute` class: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#dllimport-attribute-settings

I'm curious about `PreserveSig`: it's a boolean, but the document says `true` is its default. Where is it set? I don't see any logic setting it to `true` in the [ref](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/DllImportAttribute.cs#L7) file or in the [src](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L361-L370) file.

**Comment by alexrp** [comment]
Note that `DllImportAttribute` is one of a number of pseudo-attributes. It's actually understood by the compiler and emitted as special metadata. So Roslyn is really where you should be looking for the defaults.

Example: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAGAAkIEYA6AJQFcA7DbAWxioEkmYoIAHAMo8AbtjAwAzgG4AsAChCAZnIAmUgGFSAb3mk9pANoARXLg4s+0DAAoARLmzAAZhAi20pAAqwJImAOwAc1IAXlIMKDoYAEoAXV19JXIKJFIYBAweBnIUUhcIa2jZOQBfIA

**Comment by AaronRobinsonMSFT** [comment]
@carlossanlop The `PreserveSig` is a pseudo-attribute and is encoded directly in metadata. See section II.23.1.11 of ECMA-335.

**Comment by carlossanlop** [comment]
Thanks.

Should this analyzer also apply to the new `GeneratedDllImportAttribute`? Unlike `DllImportAttribute`, this new class [uses properties](https://github.com/dotnet/runtime/blob/9dc08dd7d054594eb415b9ec093a5a4b0ee746eb/src/libraries/Common/src/System/Runtime/InteropServices/GeneratedDllImportAttribute.cs#L20), but they are similarly named.

**Comment by carlossanlop** [comment]
Suggested severity: Info
Suggested category: [Style](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/categories)

These are all the public fields in the `DllImportAttribute` class, and their documented default value, which the analyzer should flag:

```cs
public sealed partial class DllImportAttribute : System.Attribute
{
    // true by default
    // https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.bestfitmapping?view=net-6.0#remarks
    public bool BestFitMapping;

    // The default value is Winapi on Windows, and Cdecl on all other platforms.
    // https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.callingconvention?view=net-6.0#remarks
    public System.Runtime.InteropServices.CallingConvention CallingConvention;

    // If DefaultCharSetAttribute is applied on the module in C# or Visual Basic code,
    // then the C# or Visual Basic compiler will emit the provided CharSet by default instead of using CharSet.None.
    // F# does not support the DefaultCharSetAttribute, and always emits CharSet.None by default.
    // https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset
    public System.Runtime.InteropServices.CharSet CharSet;

    // Optional API name, the analyzer should ignore this field
    public string? EntryPoint;

    // false by default
    // https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#dllimport-attribute-settings
    public bool ExactSpelling;

    // true by default
    // https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#dllimport-attribute-settings
    public bool PreserveSig;

    // false by default
    // https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#dllimport-attribute-settings
    public bool SetLastError;

    // false by default
    // https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.throwonunmappablechar?view=net-6.0#remarks
    public bool ThrowOnUnmappableChar;

    // This is mandatory, the analyzer should ignore this field
    public string Value { get; }
}
```

If we want to do the same with `GenerateDllImport`, then these are the properties exposed by this attribute:

```cs
#if DLLIMPORT_GENERATOR_TEST
    public
#else
    internal
#endif
sealed class GeneratedDllImportAttribute : Attribute
{
    public CharSet CharSet { get; set; }
    public string? EntryPoint { get; set; }
    public bool ExactSpelling { get; set; }
    public bool PreserveSig { get; set; }
    public bool SetLastError { get; set; }

    public string Value { get; private set; }
}
```

**Comment by terrajobst** [comment]
* We're not convinced that over-specification is a bad practice; these are expert-level APIs and many experts like being explicit instead of relying on defaults.
* However, there is value in P/Invoke analyzers, which, could flag when people are calling Unicode APIs (*W) but specify ANSI encoding, for instance.
* Let's close this one for now. If there are other suggestions, we can open new issues.
