### ISSUE TITLE
Prefer slim synchronization primitives

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33803]
Find places where a `ManualResetEvent` is created without a name, where its never passed to `WaitHandle.WaitAll`/`Any`, etc., and replace usage with `ManualResetEventSlim`.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Medium

**Comment by carlossanlop** [comment]
@terrajobst Some questions:

- Can you please explain what you meant by "created without a name"? `ManualResetEvent` inherits from `EventWaitHandle` but does not offer a constructor that takes a name. Unless you construct an `EventWaitHandle` and then cast it to `ManualResetEvent`? Which seems weird to do.
- The `WaitAll`/`WaitAny` methods are defined in the parent abstract class `WaitHandle` from which `EventWaitHandle` inherits, but they are not available in `ManualResetEvent`. So the question is how would you call `WaitAll` from a `ManualResetEvent`?
- Can you please offer a usage example of what this analyzer should flag and how it should fix it?
