### ISSUE TITLE
Prefer IsEmpty over Count

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#33801]
Find places where a concurrent collection's `Count` is accessed and compared to `0`, then replace with `IsEmpty`. We should probably not special case concurrent collections but rather say if a type defines both `Count` and `IsEmpty`, callers should prefer `IsEmpty` when comparing count to `0`.

**Category**: Performance

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Small
* Fixer: Small

**Comment by jeffhandley** [comment]
There's already a rule that checks for `Count` vs. `Any`. We should look at that rule for reference and design and implementation details. We don't know if a new diagnostic ID would be needed.

**Comment by jeffhandley** [comment]
For the existing rule that checks `Count()` vs. `Any()`, it's going against very specific types that have `Count()` and similar methods, along with `Any()` being available on that type.

Looking at concurrent collections, I see a commonality of the classes implementing `IReadOnlyCollection<T>`, which is where `Count` is provided as a property. But as far as I can tell, `IsEmpty` does not belong to any interface definitions.  `IsEmpty` exists on a lot of classes, some of which this rule would make sense for and others it would not.  But as far as I can tell, every class that has both a `Count` property and an `IsEmpty` property, it would make sense to recommend `IsEmpty`.

Without an interface to check against, it seems the logic for this analyzer would be:

- Find all places where a comparison is performed
- And one side of the comparison is `0`
- And we're verifying either that the other value is equal to, not equal to, or greater than 0
- And the other side of the comparison is checking a property named "Count", the method `Count()`, or the method `LongCount()`
- And the object that `Count`/`Count()`/`LongCount()` was accessed from also contains a member named `IsEmpty` (anywhere in its hierarchy)

This would match `Count`, `Count()`, or `LongCount()` for:

1. `foo.Count == 0` or `0 == foo.Count`
1. `foo.Count != 0` or `0 != foo.Count`
1. `foo.Count > 0` or `0 < foo.Count`

Replacing with:

1. `foo.IsEmpty`
1. `!foo.IsEmpty`
1. `foo.IsEmpty`

This seems a little heavy-handed though, having to check every single comparison against 0 and then check for the property/method and then the object having an `IsEmpty`.  Is there another approach that could have type constraints, or is this OK?

/cc @stephentoub @terrajobst @bartonjs

**Comment by bartonjs** [comment]
`foo.Count >= 1` would also be `!IsEmpty` (and `foo.Count < 1` would be `IsEmpty`).

Possibly a way to start up is to learn about all types that have an IsEmpty property, then if they're the this (or this-arg) to a "counting" method comparing against zero or one, warn.

It sounds fine to me.

**Comment by jeffhandley** [comment]
> foo.Count >= 1 would also be !IsEmpty (and foo.Count < 1 would be IsEmpty).
Ooh, good catch!

>Possibly a way to start up is to learn about all types that have an IsEmpty property
Do you think that could be done during startup? Somehow enumerating all types' members available and defining a collection of types with `IsEmpty`?

**Comment by stephentoub** [comment]
https://source.dot.net/#q=Isempty

**Comment by jeffhandley** [comment]
Would we want to just hard-code the list, or have the analyzer "learn" the list?  Would we want this to identify collection implementations beyond our libraries?

**Comment by stephentoub** [comment]
The C# language enables its collection initializers feature based on whether a type implements `IEnumerable<T>` and has an `Add` method; I think it'd be reasonable here to look for `IEnumerable<T>` types that have an `int Count` property and a `bool IsEmpty` property.  Would that result in any known-problematic false positives?

**Comment by jeffhandley** [comment]
@Jozkee Can you discover all of the types that meet the following criteria and add a comment here with that list of types please?

1. Implement `IEnumerable<T>`
2. Have an `int Count` property
3. Have a `bool IsEmpty` property

We will want to review that list, look at the implementations of `Count` and `IsEmpty` and verify that across the whole list, `IsEmpty` is a cheaper getter than `Count`.

**Comment by Jozkee** [comment]
First, using a regex, I searched for matches of `public bool IsEmpty` within all the .cs files in our ref projects.
Then I analyzed each file that matched the criteria with a `SyntaxTree`.

I verified that the member `IsEmpty` was indeed a property (it could be a method).
Then searched within the type for the property `Count`.

Note: I didn't filter by `IEnumerable<T>` just to make sure that we weren't missing any potential candidate.

So here are the results:

```
Total of 12 files found.

C:\repos\runtime\src\libraries\System.Collections.Concurrent\ref\System.Collections.Concurrent.cs
  [CANDIDATE] System.Collections.Concurrent.ConcurrentBag - IsEmpty ln 62, Count ln 60
  [CANDIDATE] System.Collections.Concurrent.ConcurrentDictionary - IsEmpty ln 86, Count ln 84
  [CANDIDATE] System.Collections.Concurrent.ConcurrentQueue - IsEmpty ln 133, Count ln 131
  [CANDIDATE] System.Collections.Concurrent.ConcurrentStack - IsEmpty ln 153, Count ln 151

C:\repos\runtime\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable.cs
  [CANDIDATE] System.Collections.Immutable.ImmutableArray - IsEmpty ln 105, Count ln 112
  [CANDIDATE] System.Collections.Immutable.ImmutableDictionary - IsEmpty ln 290, Count ln 288
  [CANDIDATE] System.Collections.Immutable.ImmutableHashSet - IsEmpty ln 426, Count ln 424
  [CANDIDATE] System.Collections.Immutable.ImmutableList - IsEmpty ln 555, Count ln 553
  [NOT CANDIDATE] System.Collections.Immutable.ImmutableQueue - IsEmpty ln 738, Count ln 0
  The Type does not contain a Count property.
  [CANDIDATE] System.Collections.Immutable.ImmutableSortedDictionary - IsEmpty ln 786, Count ln 784
  [CANDIDATE] System.Collections.Immutable.ImmutableSortedSet - IsEmpty ln 929, Count ln 927
  [NOT CANDIDATE] System.Collections.Immutable.ImmutableStack - IsEmpty ln 1058, Count ln 0
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.ComponentModel.TypeConverter\ref\System.ComponentModel.TypeConverter.cs
  [NOT CANDIDATE] System.ComponentModel.Design.Serialization.MemberRelationship - IsEmpty ln 2142, Count ln 0
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Drawing.Common\ref\System.Drawing.Common.cs
  [NOT CANDIDATE] System.Drawing.Region - IsEmpty ln 956, Count ln 0
  Member IsEmpty was a method, not a property.
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Drawing.Primitives\ref\System.Drawing.Primitives.cs
  [NOT CANDIDATE] System.Drawing.Color - IsEmpty ln 76, Count ln 0
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Memory\ref\System.Memory.cs
  [NOT CANDIDATE] System.Buffers.ReadOnlySequence - IsEmpty ln 217, Count ln 0
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Runtime\ref\System.Runtime.cs
  [NOT CANDIDATE] System.Memory - IsEmpty ln 2692, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] System.ReadOnlyMemory - IsEmpty ln 3015, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] System.ReadOnlySpan - IsEmpty ln 3042, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] System.Span - IsEmpty ln 3239, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] System.Security.PermissionSet - IsEmpty ln 9671, Count ln 9647
  Member IsEmpty was a method, not a property.

C:\repos\runtime\src\libraries\System.Runtime.WindowsRuntime\ref\System.Runtime.WindowsRuntime.cs
  [NOT CANDIDATE] Windows.Foundation.Rect - IsEmpty ln 157, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] Windows.Foundation.Size - IsEmpty ln 182, Count ln 0
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Security.Permissions\ref\System.Security.Permissions.cs
  [NOT CANDIDATE] System.Security.PermissionSet - IsEmpty ln 622, Count ln 598
  Member IsEmpty was a method, not a property.

C:\repos\runtime\src\libraries\System.Utf8String.Experimental\ref\System.Utf8String.Experimental.cs
  [NOT CANDIDATE] System.Text.Utf8Span - IsEmpty ln 294, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] System.Text.Utf8Span - IsEmpty ln 323, Count ln 0
  Member IsEmpty was a method, not a property.
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Xml.ReaderWriter\ref\System.Xml.ReaderWriter.cs
  [NOT CANDIDATE] System.Xml.XmlElement - IsEmpty ln 396, Count ln 0
  The Type does not contain a Count property.
  [NOT CANDIDATE] System.Xml.XmlQualifiedName - IsEmpty ln 742, Count ln 0
  The Type does not contain a Count property.

C:\repos\runtime\src\libraries\System.Xml.XDocument\ref\System.Xml.XDocument.cs
  [NOT CANDIDATE] System.Xml.Linq.XElement - IsEmpty ln 224, Count ln 0
  The Type does not contain a Count property.
```

**Comment by Jozkee** [comment]
I am a bit confused by previous comments. 
Does this rule apply to any type that defines a `bool IsEmpty` and an `int Count` method or property, or the type should also implement `IEnumerable<T>`  for this rule to kick in?

Also, I think `Count` does not necessarily needs to be defined by the type; it can be an extension method.

**Comment by jeffhandley** [comment]
> Does this rule apply to any type that defines a `bool IsEmpty` and an `int Count` method or property, or the type should also implement `IEnumerable<T>` for this rule to kick in?

That is still an open decision; the data you provided above is very helpful to inform that decision.  Thanks for finding a way to extract the candidates/non-candidates from our own assemblies!

From this report, I'm inclined to limit this analyzer to specific types, and namely the ones you've marked here as candidates:

* System.Collections.Concurrent.ConcurrentBag
* System.Collections.Concurrent.ConcurrentDictionary
* System.Collections.Concurrent.ConcurrentQueue
* System.Collections.Concurrent.ConcurrentStack
* System.Collections.Immutable.ImmutableArray
* System.Collections.Immutable.ImmutableDictionary
* System.Collections.Immutable.ImmutableHashSet
* System.Collections.Immutable.ImmutableList
* System.Collections.Immutable.ImmutableSortedDictionary
* System.Collections.Immutable.ImmutableSortedSet

Without any underlying interfaces that define `IsEmpty`, and otherwise needing to fall back to naive identification of those two props and making assumptions about the implementations of `IsEmpty` vs. `Count`, I'm not confident a generalized solution would be worthwhile.  Additionally the classes like `Region` and `Rect` showing up in that report make me wary of what types across a user's entire codebase the analyzer would end up considering.

@stephentoub & @terrajobst - what do you think about hard-coding this analyzer to a small list of types within our control?

@Jozkee - can you look at the implementations of `IsEmpty` and `Count` on that list of candidates and confirm that `IsEmpty` indeed is more optimized for all of them?

Thanks!

**Comment by Jozkee** [comment]
> @Jozkee - can you look at the implementations of IsEmpty and Count on that list of candidates and confirm that IsEmpty indeed is more optimized for all of them?

They do, specially for the concurrent ones, since in most of them, the collections need to freeze/lock from other threads in order to get the Count. 

The IsEmpty property in concurrent collections first takes a fast path looking at the local collection without locks in order to get the result and falls back to the lock path when the local snapshot is empty (This reason is from just looking at the code; I am not completely certain of how this works).

cc @safern 

For the immutable ones, the Count seems to me that has already been computed when getting the property so I don't think there is a significant performance difference when choosing between IsEmpty and Count here. There is also cases (`ImmutableHashSet<T>`) where the IsEmpty property looks to Count to compute its return value.
```cs
public sealed partial class ImmutableHashSet<T>{
    public bool IsEmpty
    {
        get { return this.Count == 0; }
    }
}
```

Due to the fast paths of concurrent collections, I assume that's why the issue description originally was calling those out explicitly.

**Comment by jeffhandley** [comment]
Awesome, @Jozkee -- from that, I think we can restrict all the way back down to the concurrent collections then, and name the analyzer and word the message accordingly.

@terrajobst & @stephentoub -- are you comfortable with the scope for this analyzer being restricted to concurrent collections?

**Comment by bartonjs** [comment]
I don't see why we'd restrict it if we haven't found evidence that the capabilities-based variant doesn't work.

* Has an IsEmpty property
* Has a Count property (not a method, or extension method)  (we could also include Length, if we wanted)
* Optionally, implements (directly or via inheritance) IEnumerable (or, if we wanted to be fancy, "adheres to the enumerable pattern").

In some cases (e.g. concurrent collections) there's likely a perf benefit from changing from Count to IsEmpty (for simple boolean expressions). In others, it just reads better (e.g. `string.IsNullOrEmpty(str)` vs `str?.Length > 0`).  So, unless the cost to analyze all of the types is horrendous, why would we box ourselves into an analyzer that doesn't extend to 3rd party types?

Personally, unless we see that using heuristics is provably bad, we should do it with heuristics.

**Comment by Jozkee** [comment]
Ok, in that case this would be a rule for `Microsoft.CodeQuality.Analyzers` since its not specific to a .NET API.

I just want to confirm the conditions needed for the rule to trigger.

* It will only apply on operators (`==`, `!=`, `>`, `>=`, `<`, `<=`). 
  * Should also apply for `obj.Count.Equals(0)`?
* IsEmpty needs to be a non-static visible boolean property with a visible getter.
  * Should a field named IsEmpty be recognized by the rule as well?

**Comment by jeffhandley** [comment]
OK -- color me convinced. :-)  Let's move forward with those heuristics that @bartonjs laid out.  Thanks, Jeremy!

> Should also apply for obj.Count.Equals(0)?

Yeah, that sounds good.

> Should a field named IsEmpty be recognized by the rule as well?

Yeah, that sounds good too.

**Comment by bartonjs** [comment]
> Should a field named IsEmpty be recognized by the rule as well?

If it's easier to include fields than exclude them, sure.  But since our design guidelines say to not have public fields, there's no reason to write extra code to handle this case.  (Same for a public "Count" or "Length" field)

**Comment by Jozkee** [comment]
> > Should also apply for obj.Count.Equals(0)?
> 
> Yeah, that sounds good.

I will keep this aside for now and add it on top in order to get/focus on feedback related to the initial rule creation.
