### ISSUE TITLE
Add [Immediate] attribute for parameters which should be constants

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#33814]
(Copied from https://github.com/dotnet/runtime/issues/30740#issuecomment-594111037.)

We have scenarios (particularly in the _Intrinsics_ namespace) where certain APIs expect constant values as parameters. For instance, [`Sse2.ShiftLeftLogical(Vector, byte)`](https://apisof.net/catalog/System.Runtime.Intrinsics.X86.Sse2.ShiftLeftLogical(Vector128%3CInt16%3E,Byte)) expects a constant value for its last argument, as the constant value needs to be encoded as part of the instruction. You can pass a non-constant, but if you do this you'll get redirected to a jump table, which could kill your performance. And presumably you were using intrinsics because you wanted bare-metal performance. :)

As a strawman for an analyzer that could detect this, we could consider an `[Immediate]` attribute that could be placed on parameters and an analyzer that would flag call sites where a non-const is passed in for these parameters. Bruce had further suggested we could extend it with min and max properties if needed.

So, using the SSE2 example mentioned earlier, the annotation would appear as follows.

```cs
namespace System.Runtime.Intrinsics.X86
{
    public abstract class Sse2 : Sse
    {
        public static Vector128<short> ShiftLeftLogical(Vector128<short> value, [Immediate( /* Min = 0, Max = 15 */)] byte count);
    }
}
```

__Category__: Performance (possibly also correctness?)

**Comment by tannergooding** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/33771 ?

**Comment by GrabYourPitchforks** [comment]
Derp. I somehow missed that he added that.
