### ISSUE TITLE
Prefer Span<T>.Clear() over Span<T>.Fill(default)

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#33813]
(Copied from https://github.com/dotnet/runtime/issues/30740#issuecomment-595436029.)

Consider replacing this:

```cs
Span<T> theSpan = GetSpan();
theSpan.Fill(default(T));
```

With this:

```cs
Span<T> theSpan = GetSpan();
theSpan.Clear();
```

I see a handful of uses of `Fill(0)` or `Fill(default)` throughout the codebase (see [callers](https://source.dot.net/System.Private.CoreLib/R/ae132b20c11a88a5.html)). The `Clear()` method is potentially much more optimized than the `Fill` method depending on the _T_ in use.

__Category__: Performance

**Comment by gfoidl** [comment]
Aside from the analyzer I can submit a PR changing `Fill(default)` to `Clear`.

**Comment by Joe4evr** [comment]
Is there a rule-of-thumb on when `Clear()` could be more optimized than `Fill(default)`?

**Comment by GrabYourPitchforks** [comment]
@Joe4evr currently `Clear` is always more optimized than `Fill(default)` for all _T_. Maybe there's an exception when the span contains only 1 or 2 elements, but those are rarities.

**Comment by jeffhandley** [comment]
I'm going to remove this from the [Roslyn Analyzers](https://github.com/dotnet/runtime/projects/46) project for the time-being; we will add it back to the project once we get our triage process in place for prioritizing newly filed code-analyzer issues.

**Comment by GrabYourPitchforks** [comment]
@jeffhandley Any issues with me marking this _ready for review_? Seems straightforward enough.

**Comment by davidfowl** [comment]
I feel like `Span<T>.Fill(default)` would only be written by someone coming from C\C++, `memset(0, sizeof(...))`.

**Comment by GrabYourPitchforks** [comment]
I count [9 references](https://source.dot.net/System.Private.CoreLib/R/ae132b20c11a88a5.html) to `Span<T>.Fill(default)` tracked by source.dot.net.

**Comment by jeffhandley** [comment]
> Any issues with me marking this _ready for review_?

No objections from me; thanks!

**Comment by bartonjs** [comment]
Level: Info
Category: Performance

Looks good as proposed.

**Comment by carlossanlop** [comment]
@huoyaoyuan Consider this issue assigned to you.

**Comment by huoyaoyuan** [comment]
@carlossanlop You can assign me now, and you can tell the owners to review the PR.

**Comment by NN---** [comment]
@GrabYourPitchforks Probably also `Fill` could be optimized internally when default value is passed.

**Comment by huoyaoyuan** [comment]
> For VB, please confirm on the dotnet/runtime issue whether VB support is desired or not? If desired, and you wish to postpone it to a separate PR, please file a tracking issue in this repo for VB part.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/5181#pullrequestreview-867553249_

@bartonjs 
I think support for VB shouldn't be desired, since using span in VB will cause error anyway.

**Comment by stephentoub** [comment]
We don't need VB support for analyzers about the use of span until such a time that VB has more than minimal support for spans.
