### ISSUE TITLE
UTF8 encoder returns different results if Convert is called only once or multiple times with the same source data

### ISSUE THREAD

**Issue by eberzosa** [dotnet/runtime#33817]
Calling Convert with a given char[], i.e.:  { '1', '2', '\uD804', '3', '4' } in a unique call gives different results than when calling Convert for each independent character in a loop. This only happens with some .NET versions.

Tested with .Net Framework 4.6.1 and .Net Core 2.0.3 with correct results
.Net Core 3.1.2 returned different results

```csharp
using System;
using System.IO;
using System.Text;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Encoder encoder = Encoding.UTF8.GetEncoder();
            encoder.Fallback = EncoderFallback.ReplacementFallback;

            var data = new[] { '1', '2', '\uD804', '3', '4' };

            var bytes = new byte[10];

            encoder.Convert(data, 0, data.Length, bytes, 0, bytes.Length, false, out _, out var byteCount, out _);

            for (var i = 0; i < byteCount; i++) 
                Console.Write(bytes[i].ToString("x") + " "); // Returns 31 32 3f 33 34 in netcore and framework

            Console.WriteLine();

            encoder = Encoding.UTF8.GetEncoder();
            encoder.Fallback = EncoderFallback.ReplacementFallback;

            foreach (var c in data)
            {
                encoder.Convert(new[] { c }, 0, 1, bytes, 0, bytes.Length, false, out var charCount, out byteCount, out _);

                if (charCount >= 1)
                    for (int i = 0; i < byteCount; i++)
                        Console.Write(bytes[i].ToString("x") + " ");

                        // Returns 31 32 3f 33 34    in framework 4.6.1
                        // Returns 31 32 3f 33 3f 34 in netcore 3.1.2
            }
        }
    }
}
```

**Comment by eberzosa** [comment]
@layomia @krwq @tarekgh

**Comment by tarekgh** [comment]
@GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Need to look at it a bit closer. OP originally reported at https://github.com/dotnet/runtime/issues/415#issuecomment-601267431 but the repro code there was truncated so I wasn't able to test it locally.

**Comment by GrabYourPitchforks** [comment]
Bug is at the following location in _EncoderNLS.cs_:

https://github.com/dotnet/runtime/blob/cd09cd3999b862360f4f9811f243a2baabb330f9/src/libraries/System.Private.CoreLib/src/System/Text/EncoderNLS.cs#L397-L400

This block of code should set `_charLeftOver = default;` upon execution, just like all the other cases in the switch statement which precedes it.

**Comment by tarekgh** [comment]
@GrabYourPitchforks I am not sure this will meet the servicing bar.

**Comment by GrabYourPitchforks** [comment]
I'm not sure either, but I wanted to at least have the discussion. This could possibly lead to data corruption of the output, but _only if_ the original input was also corrupted through the presence of a standalone unpaired surrogate. Given the "garbage-in/garbage-out" behavior it's certainly less severe than the other UTF-8 issues we've backported.
