### ISSUE TITLE
Detect when copying Range-based indexers are being used with a Span or Memory target.

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#33829]
The decision for Range based indexers is they return the type they're declared on:

```C#
var val = str[x..y];
```

Produces a string, the same as `str.Substring(x, y-x)`.  Due to implicit conversions, this simple-looking statement is actually a copy:

```C#
ReadOnlySpan<char> val = str[x..y];
```

Since strings are immutable, this pattern should almost always be an error, and replaced with a call to AsSpan:

```C#
ReadOnlySpan<char> val = str.AsSpan(x, y-x);
```

For arrays, and any other sources, it's possible that a copy was actually desired... but it's probably not the majority case.  Since it's less slam-dunk it might warrant a different diagnostic ID so it can be suppressed differently than the string variant.

Fixer: Replace range indexer use with calls to AsSpan or AsMemory.  (If actual `Index` types were used the fix is more complicated, since it requires calling GetOffsetAndLength and using temporary variables, while maintaining order of evaluation).

**Category:** Performance

**Comment by GrabYourPitchforks** [comment]
> If actual Index types were used the fix is more complicated, since it requires calling GetOffsetAndLength and using temporary variables, while maintaining order of evaluation

It's also more complex if _x_ and _y_ in your sample have side effects. For instance, if they were method calls instead of consts or local variables. Then we'd need to make sure each expression is evaluated only once.

The pattern `foo.AsSpan()[x..y]` - while more verbose - would probably be preferred here from a cleanliness and reliability perspective. Or even an overload `MemoryExtensions.AsSpan(Range)` so that we could write `foo.AsSpan(x..y)`.

**Comment by bartonjs** [comment]
Yeah, `foo.AsSpan()[x..y]` probably works as a general substitution; but I think that I'll try making the fixer be more elegant when it can (x and y are literals, variables, or fields, and not of type Index).

(The "acceptance" criteria could certainly be raised to include "provably pure" operations, like math expressions, and I guess "y" can even have side effects safely in a rewrite to AsSpan, just "x" can't.)

**Comment by jeffhandley** [comment]
Estimates:
* Analyzer: Medium
* Fixer: Medium
