### ISSUE TITLE
asn.xslt - use ReadOnlySpan<byte> for defaultDerInit

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#33823]
When generating the .xml.cs files for the ASN types, the defaultDerInit will emit something like:

```csharp
private static readonly byte[] s_defaultHashAlgorithm = { 0x30, /* blah blah */ 0x01 };
```

These are only ever used in `AsnValueReader` which is a ref struct and accepts a Span in the constructor, and in `SequenceEqual` which can already take a `Span`.

I would propose the fields instead be properties as:

```csharp
private static ReadOnlySpan<byte> DefaultHashAlgorithm => new byte[] { 0x30, /* blah blah */ 0x01 };
```

The benefit being to get rid of the array allocation during type initialization.

@bartonjs does this make sense to implement or am I missing something?

**Comment by bartonjs** [comment]
Yeah, it's probably something reasonable to do.  AFAIK, the xslt msbuild step is still only supported by netfx-msbuild; so if you want to change the generator you have to use msbuild (vs dotnet msbuild) on each of the affected projects (possibly repeating the compile with `/p:OSGroup=Linux` and /p:OSGroup=OSX`)

**Comment by vcsjones** [comment]
@bartonjs Mono's MSBuild has the XSLT transform, but thanks for saving me 15 minutes today. I seem to recall that if you do it with core it succeeds without doing anything.

**Comment by bartonjs** [comment]
> I seem to recall that if you do it with core it succeeds without doing anything.

Yeah, since core-msbuild doesn't have the XSLT task the asn.target has a condition to just skip everything when running under core-msbuild.
