### ISSUE TITLE
System.Drawing.Common is missing a netcoreapp rid-less asset

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#33838]
I'm not sure how we aren't catching this in package testing but I noticed this today.

We have a netcoreapp3.0 ref, but no rid-less netcoreapp3.0 lib.  We have rid-specific libs, but if someone were to use this package on a platform that didn't map to unix|win they'd get the netstandard2.0 lib.  Moreover this lib has a lower version than the netcoreapp3.0 ref, so they would see a file load exception.  We should fix this by adding a netcoreapp config to match the ref.

Maybe we should see why package testing missed it too /cc @joperezr @safern

**Comment by safern** [comment]
The `netstandard2.0` lib asset just throws. Since S.D.Common is very rid specific, should we make the same for `netcoreapp3.0`?

**Comment by ericstj** [comment]
Yeah, a not supported assembly is fine.  It just needs to have an assembly version that matches the ref.

**Comment by joperezr** [comment]
I'll take a look later today into why this wasn't catched in our package testing, as I agree that this should have been caught.

**Comment by joperezr** [comment]
> We have a netcoreapp3.0 ref, but no rid-less netcoreapp3.0 lib. We have rid-specific libs, but if someone were to use this package on a platform that didn't map to unix|win they'd get the netstandard2.0 lib. 

I took a look, the reason why we are not hitting any issues in package testing is because we don't test any framework|RID configuration where the above is true.

Netcoreapp 3.0 tests the following RIDS:
```
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=ubuntu.14.04-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=linuxmint.17-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=centos.7-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=rhel.7.2-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=debian.8-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=win7-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=win7-x86
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=ubuntu.16.04-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=fedora.24-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=osx.10.12-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=rhel.7-x64
    Testing System.Drawing.Common TFM=netcoreapp3.0 RID=opensuse.42.1-x64
```

All of which get either the win-rid specific asset or the unix-rid specific asset and so the AssemblyVersions match as expected.

**Comment by ericstj** [comment]
We don't test with no RID?  We used to.  We should fix that.

**Comment by ericstj** [comment]
I was also expecting package validation to catch this, not just package testing.   The package report should show the mismatch.

**Comment by joperezr** [comment]
We do test with no RID, but in that case I believe we don't consider runtime files, same goes for the package report, the report doesn't emit runtimeAssets when there is no RID:

```json
    ".NETCoreApp,Version=v3.0": {
      "Framework": ".NETCoreApp,Version=v3.0",
      "CompileAssets": [
        {
          "LocalPath": "F:\\git\\runtime\\artifacts\\bin\\System.Drawing.Common\\ref\\netcoreapp3.0-Debug\\System.Drawing.Common.dll",
          "PackagePath": "ref/netcoreapp3.0/System.Drawing.Common.dll",
          "SourceProject": {
            "Project": "F:\\git\\runtime\\src\\libraries\\System.Drawing.Common\\ref\\System.Drawing.Common.csproj",
            "AdditionalProperties": "TargetFramework=netcoreapp3.0;"
          },
          "TargetFramework": ".NETCoreApp,Version=v3.0",
          "Version": "5.0.0.0"
        }
      ]
    },
```

**Comment by ericstj** [comment]
I see, that likely predates our pattern of shipping not-supported assemblies.  I could have sworn we had validation that forced this :(

**Comment by joperezr** [comment]
For reference, here is the piece if code that is in question:

https://github.com/dotnet/runtime/blob/a43d6c4dc313bcd5106130231f5085e1f4bbc9a8/src/libraries/pkg/test/packageTest.targets#L63-L77

If you see, VerifyRuntimeClosure will only run if RuntimeIdentifier is set, so on the one that doesn't have a RID doesn't show.

**Comment by danmosemsft** [comment]
@ericstj do we need to add validation here and run it for 5.0 do you think?

**Comment by safern** [comment]
FWIW, we added this asset on: https://github.com/dotnet/runtime/pull/40814

**Comment by ericstj** [comment]
Yes, @anipik just fixed it.  The validation for this case is coming with https://github.com/dotnet/runtime/pull/41041.

I've been rethinking how we do package validation and have a better idea that would catch this case.

**Comment by Anipik** [comment]
fixed with https://github.com/dotnet/runtime/pull/41001
