### ISSUE TITLE
Evaluate build definition step to copy sharedfx to build machine staging directory

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/runtime#3383]
Linux x64 leg for glibc produces portable binaries . Same binaries are consumed by all native installers ( rpm and deb ) . As of today, it is achieved by copying the sharedframework published folder to Build machine staging directory and then volume mapped during docker run for each native installer build process. Copying to Build machine staging directory is a separate step in build definition. It will be a good idea to evaluate and then implement the copy step in build script for official build scenario.

**Comment by NikolaMilosavljevic** [comment]
This hasn't come up since 2018 - closing.
