### ISSUE TITLE
Roslyn analyzers sometimes interfere with running libraries tests within VS

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#33842]
It seems like the code analyzers are running over the test projects, causing build errors when we try to use VS to run the unit tests. See attached screenshot below showing errors that occur while trying to run `Int32` unit tests from the Test Explorer.

![image](https://user-images.githubusercontent.com/1746272/77129991-59b24680-6a13-11ea-90b2-e9ff22cbb916.png)

**Comment by Gnbrkm41** [comment]
I opened `System.Runtime.sln` project on the latest HEAD and it does not seem to be happening for me. AFAIK most of the analyzers are disabled for test projects?

**Comment by ViktorHofer** [comment]
@GrabYourPitchforks does this still happen, i.e. when opening the solution with the -vs switch (which does a CLI restore of the test project which is currently necessary because of a NuGet issue).

**Comment by GrabYourPitchforks** [comment]
Problem appears to be resolved.
