### ISSUE TITLE
Using ToDictionary fails build on linux

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/runtime#33843]
We are using .Net SDK 3.1.100 and building against netstandard2.0. Looks like adding in a ToDicitonary throws the following error:

_Utilities/FakesUtilities.cs(92,36): error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [/home/vsts/work/1/s/src/Microsoft.TestPlatform.Common/Microsoft.TestPlatform.Common.csproj]_

[Here's](https://dev.azure.com/vstestplatform/TestPlatform/_build/results?buildId=1171&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5494183b-801e-5084-3b4b-5451c6a14ee1) a PR build where this first reproed. Notice in that link that the same dotnet tooling on windows works.
Change in question is [here](https://github.com/microsoft/vstest/blob/482797b83261cf2582a19b58ad69cb33ae1acb57/src/Microsoft.TestPlatform.Common/Utilities/FakesUtilities.cs#L92).

To repro: 
1. git clone https://github.com/microsoft/vstest
2. git checkout 482797b83261cf2582a19b58ad69cb33ae1acb57
3. Run `<Repo root>\build.sh`

**Comment by danmosemsft** [comment]
Not sure where to direct this one. @safern in case he has an idea.

**Comment by safern** [comment]
I'll have a to take a look at the repro, the references that are passed to the compiler and all the detailed info. I'll try it later.

**Comment by safern** [comment]
@AbhitejJohn I was able to take a look at this and repro it. It seems like the error you're getting is not for `netstandard2.0`. Your project is cross targeting for `netstandard2.0;net451`. So I looked at it by producing a binlog of the build and looking at the targetframework and it is failing when building for `net451`. 

![image](https://user-images.githubusercontent.com/22899328/77705672-891a0380-6f7d-11ea-83a0-15b13e8f8780.png)

I added: `<Reference Include="System.Collections" />` here: https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Common/Microsoft.TestPlatform.Common.csproj#L16-L24

That fixes the issue. However, I wonder, do you need to build for net451 in non Windows at all?

**Comment by AbhitejJohn** [comment]
@safern : Interesting. And this was only failing on the linux build because it was auto resolved from GAC in a windows environment? 
We've only recently started making changes to this repo, so I'm not really sure why we are building net451 on a linux environment. There is a net451 only runtime scenario where we need to load this assembly in a net451 host so we do need to build against the two TFMs. Is this supported even? Building against netfx on a linux host cause it looks like its working? If it is should the build pick up framework assemblies from the GAC on a windows environment?

**Comment by joshudson** [comment]
I know why you would want to build like this. He has a single build server for a multi-platform build. This makes perfect sense for many reasons, and one of which that would be particularly hard to work around is it's calling `dotnet pack`.

**Comment by safern** [comment]
> Is this supported even? Building against netfx on a linux host cause it looks like its working?

It is working because you guys are referencing the netfx targeting pack nuget package. https://github.com/microsoft/vstest/blob/bbf72dd8026effaa9dfd2fd5e9aafc67e5f6536f/src/package/external/external.csproj#L91
And then you point the build system to it through an environment variable: https://github.com/microsoft/vstest/blob/2f026a9b449d4fa8ef08d3cb1137b9473bbd9b35/scripts/build.sh#L241

Sorry for the late response I missed this through my notifications.

So are you good to go with this, can we close this issue?

**Comment by AbhitejJohn** [comment]
@safern : Ah that makes sense. Its been a while since I've made changes to this repo - not familiar with the infra. Yes, this should be good to be closed. Thanks for all the pointers.
