### ISSUE TITLE
Accessing the property information changes the order of System.Text.Json serialization.

### ISSUE THREAD

**Issue by neelabo** [dotnet/runtime#33854]
If you access the property information before serialization, the property will be output at the top.

I hope the same serialized result is output from the same object regardless of the property access.

### Sample code

```
public class OrderSample
{
    public int A { get; set; }
    public int B { get; set; }
    public int C { get; set; }

    public void Test()
    {
        var propertyInfo = this.GetType().GetProperty(nameof(C));

        for (int turn = 1; turn <= 3; turn++)
        {
            Console.WriteLine(JsonSerializer.Serialize(this, new JsonSerializerOptions()));
        }
    }
}
```

### Result: .NET Core 3.1

The accessed property "C" is placed at the top.

```
{"C":0,"A":0,"B":0}
{"C":0,"A":0,"B":0}
{"C":0,"A":0,"B":0}
```

### Result: .NET Framework 4.8 + System.Text.Json 4.7.1

In the .NET Framework, the order changes from the second time.

```
{"A":0,"B":0,"C":0}
{"C":0,"A":0,"B":0}
{"C":0,"A":0,"B":0}
```

**Comment by layomia** [comment]
Reflection order is not guaranteed on serialization. The serialized content will always be the same.

**Comment by neelabo** [comment]
It will be used to save application settings, but there is a problem if the order is not guaranteed.

- Diff cannot be obtained, making it difficult to find differences in settings.
- Not suitable for version control.

Is JsonSerializer.Serialize not suitable for this purpose?

**Comment by neelabo** [comment]
To fix the order, we propose the following enhancements:

-  Extend so that alphabetical sort flag or sort function (IComparer&lt;strng&gt;) can be set in JsonSerializerOptions. This option only affects the output.

**Comment by layomia** [comment]
@neelabo this is a valid scenario - we have a tracking issue for being able to control the serialization order https://github.com/dotnet/runtime/issues/728.

**Comment by neelabo** [comment]
I will look closely at that issue.
Thank.
