### ISSUE TITLE
Missing "Host Configuration Knobs" doc file

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#33856]
Has https://github.com/dotnet/coreclr/blob/release/3.1/Documentation/project-docs/clr-configuration-knobs.md been deleted on purpose or by accident?

I find this doc very useful.

**Comment by EgorBo** [comment]
@adamsitnik as far as I remember it was deleted because it was constantly in "outdated" state

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/coreclr/pull/27612 is the PR that deleted the file.

**Comment by mangod9** [comment]
@adamsitnik is there any action required for this issue?

**Comment by adamsitnik** [comment]
@mangod9 After reading what @jkotas wrote in https://github.com/dotnet/coreclr/pull/27612 I am closing this issue as it looks like the doc was removed on purpose and there are no intentions to bring it back
