### ISSUE TITLE
Deadlock in System.Threading.Channels.BoundChannelWriter.TryWrite

### ISSUE THREAD

**Issue by AqlaSolutions** [dotnet/runtime#33858]
Using the latest stable nuget release I encountered this:
![deadlock in channels](https://user-images.githubusercontent.com/3465565/77165782-a81b2000-6abb-11ea-98aa-a367fcc342a3.png)

1. Lock of `synsObj` in `TryWrite` is taken
2. In different thread `CancellationToken` is canceled so callback `SignalCompletion` is called
3. `TryWrite` tries to unregister this callback but it needs to wait until `SignalCompletion` is completed.
4. Which is never completed because it calls synchronously a continuation which calls to `ReadAsync` which blocks trying to lock the same `syncObj`.

**Comment by stephentoub** [comment]
@AqlaSolutions, can I assume you're setting BoundedChannelOptions.AllowSynchronousContinuations = true when constructing the BoundedChannel?  Assuming yes, a workaround is "don't do that" :smile:

**Comment by AqlaSolutions** [comment]
@stephentoub , yes, it's true. But why is it there if it can't be used?

**Comment by stephentoub** [comment]
This interaction with cancellation on BoundedChannel is a bug.  I'm saying you can avoid the bug by not opting-in to the optimization.  It's off by default for a reason.

**Comment by AqlaSolutions** [comment]
You're right, I checked `AllowSynchronousContinuations = false` and it is a workaround.
