### ISSUE TITLE
Question: Duplicated definitions of Oids in System.Security.Cryptography.Pkcs/tests and Common files

### ISSUE THREAD

**Issue by tolyanich** [dotnet/runtime#33859]
There is a very small difference between ./src/libraries/System.Security.Cryptography.Pkcs/tests/Oids.cs and src/libraries/Common/src/System/Security/Cryptography/Oids.cs. It's mainly naming like Rc2 and Rc2Cbs.  Should the first one be removed and test are fixed to use Oids.cs from src/Common...?

**Comment by bartonjs** [comment]
It could be updated to use a common one, but there's not a compelling need.
