### ISSUE TITLE
Remove the PInvoke analyzer from runtime repo build

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#33867]
The brief discussion about that is here https://github.com/dotnet/runtime/pull/33834#pullrequestreview-378179698

**Comment by danmosemsft** [comment]
may be just roughly reverting https://github.com/dotnet/corefx/pull/16704

**Comment by danmosemsft** [comment]
should also delete https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/pinvoke-checker.md
