### ISSUE TITLE
System.Net.Http GetResponseStream(),different results in .NET Framework vs .NET Standard

### ISSUE THREAD

**Issue by Jmales** [dotnet/runtime#33866]
Hey huys!

I have a project in .NET Standard 2.0 which is used in two solutions: a .NET Framework 4.7.2 and a .NET Core App 3.1.

I'm seeing different results in a call to _System.Net.Http_'s GetResponseStream().

**Project 1**- In the .NET Framework 4.7.2 solution, that method returns a **ConnectedStream** and everything goes well;

**Project 2**- In the .Net Core solution, that method returns a **ChunkedEncodingReadStream** and causes a lot of problems which I think are related. Namely, it tries to call an event infinitely (I guess it has to do with the timeouts). Note in the image below that Read and Write Timeouts are said not to be supported

![image](https://user-images.githubusercontent.com/22914881/77178285-c59db900-6abe-11ea-806d-6b83d935c8a2.png)

I looked at the System.Net.Http that each solution uses and noticed that:
**Project 1**- Looks into **C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\**  where I can see that the version of _System.Net.Http_ dll is**4.2.0**
**Project 2**-  Looks into **C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\ref\** where I can see that the version of _System.Net.Http_ dll is **4.1.2**

So, why does it seem that .Net Standard is using an older version of _System.Net.Http_? How do I solve that?
Will that solve my **ConnectedStream** vs **ChunkedEncodingReadStream** problem?

Read a lot of things, tried a lot of things (such as activating **AutoGenerateBindingRedirects** or adding a BindingRedirect file in a app.config, etc) and

**Comment by stephentoub** [comment]
> I'm seeing different results in a call to System.Net.Http's GetResponseStream().

What is the actual problem you're experiencing?  The implementation of HttpClient is entirely different between .NET Framework and .NET Core, which is why you're seeing different concrete types for the actual Stream being returned.  Such a difference isn't itself a problem, so what are the symptoms that are causing you grief?  Please share a small repro.  Thanks.

**Comment by Jmales** [comment]
@stephentoub thanks for the answer.

Like I said, " Namely, it tries to call an event infinitely (I guess it has to do with the timeouts). Note in the image below that Read and Write Timeouts are said not to be supported".

**Comment by stephentoub** [comment]
> it tries to call an event infinitely

What is "it" here?  What "event" is being called?

**Comment by stephentoub** [comment]
> I traced it down to GetResponseStream()'s from .NET Core not supporting Timeouts

Yes, in .NET Core, a response stream's CanTimeout is false.

It also looks like you're using HttpWebRequest/Response rather than HttpClient?  The former is considered legacy and will have many behavioral differences between .NET Framework and .NET Core.

**Comment by Jmales** [comment]
Yes I am using HttpWebRequest... Didn't knew that, thanks for the info.

So, if I need Read/Write Timeout in .NET Core, what is my option?





> > it tries to call an event infinitely
> 
> What is "it" here? What "event" is being called?

Great question. Sorry for not being clear.
The event is a custom event and the "it" is a while cycle which keeps doing `str = responseStreamReader.ReadLine()` until the thread is aborted.

**Comment by Jmales** [comment]
I ended up using a wrapper around stream to allow timeouts:
https://stigvoss.dk/2017/11/04/timeoutstream-and-net-standard-20/
