### ISSUE TITLE
CI is failing in Mono stack __icall_wrapper_mono_gc_alloc_string when running System.Composition.TypedParts.Tests

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#33875]
https://helix.dot.net/api/2019-06-17/jobs/2c80a078-051c-42ef-90aa-f2254bbdc2cb/workitems/System.Composition.TypedParts.Tests/console

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Object:__icall_wrapper_mono_gc_alloc_string <0x0007d>
	  at System.Object:AllocString <0x00113>
	  at System.String:Concat <0x0011f>
	  at Xunit.Sdk.DefaultTestCaseOrderer:Compare <0x0009f>
	  at System.Collections.Generic.ArraySortHelper`1:InsertionSort <0x0013f>
	  at System.Collections.Generic.ArraySortHelper`1:IntroSort <0x002f3>
	  at System.Collections.Generic.ArraySortHelper`1:IntrospectiveSort <0x000d3>
	  at System.Collections.Generic.ArraySortHelper`1:Sort <0x00063>
	  at System.Collections.Generic.List`1:Sort <0x000f3>
	  at Xunit.Sdk.DefaultTestCaseOrderer:OrderTestCases <0x0014f>
	  at <RunTestMethodsAsync>d__38:MoveNext <0x00178>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000ff>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestClassRunner`1:RunTestMethodsAsync <0x000ff>
	  at <RunAsync>d__37:MoveNext <0x003aa>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestClassRunner`1:RunAsync <0x000f3>
	  at Xunit.Sdk.XunitTestCollectionRunner:RunTestClassAsync <0x000f7>
	  at <RunTestClassesAsync>d__28:MoveNext <0x0041c>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000f3>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestCollectionRunner`1:RunTestClassesAsync <0x000f7>
	  at <RunAsync>d__27:MoveNext <0x003a7>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestCollectionRunner`1:RunAsync <0x000f3>
	  at Xunit.Sdk.XunitTestAssemblyRunner:RunTestCollectionAsync <0x000c7>
	  at <>c__DisplayClass14_2:<RunTestCollectionsAsync>b__2 <0x00060>
	  at System.Threading.Tasks.Task`1:InnerInvoke <0x00078>
	  at <>c:<.cctor>b__274_0 <0x0002f>
	  at System.Threading.ExecutionContext:RunInternal <0x00101>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00287>
	  at System.Threading.Tasks.Task:ExecuteEntry <0x000c3>
	  at <>c:<.cctor>b__8_0 <0x00057>
	  at Xunit.Sdk.MaxConcurrencySyncContext:RunOnSyncContext <0x0004f>
	  at <>c__DisplayClass11_0:<WorkerThreadProc>b__0 <0x0004b>
	  at System.Threading.ExecutionContext:RunInternal <0x00101>
	  at System.Threading.ExecutionContext:Run <0x0004b>
	  at System.Object:lambda_method2 <0x0008a>
	  at Xunit.Sdk.ExecutionContextHelper:Run <0x0005e>
	  at Xunit.Sdk.MaxConcurrencySyncContext:WorkerThreadProc <0x001f7>
	  at <>c:<QueueUserWorkItem>b__5_0 <0x0006b>
	  at System.Threading.Tasks.Task:InnerInvoke <0x000a2>
	  at <>c:<.cctor>b__274_0 <0x0002f>
	  at System.Threading.ExecutionContext:RunInternal <0x00101>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00287>
	  at System.Threading.Tasks.Task:ExecuteEntryUnsafe <0x00097>
	  at <>c:<.cctor>b__10_0 <0x0005b>
	  at System.Threading.Thread:StartCallback <0x00109>
	  at System.Object:runtime_invoke_void__this__ <0x00091>

**Comment by ericstj** [comment]
Dup of https://github.com/dotnet/runtime/issues/32377
