### ISSUE TITLE
System.Runtime.WindowsRuntime fails building with Crossgen

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#33885]
This is most likely just a side symptom of the broader problem that Crossgen currently doesn't support WinMD and WinRT. Build of the assembly is currently blocked out in the scripts <code>src/coreclr/build-test.cmd/sh</code>.

<pre>
Error: Could not load type 'Windows.Foundation.AsyncStatus' from assembly ''.
Error compiling D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.Runtime.WindowsRuntime.dll: Could not find or load a specific file. (0x80131621 (COR_E_FILELOAD))
Error: compilation failed for "D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.Runtime.WindowsRuntime.dll" (0x80131621)
</pre>

**Comment by nattress** [comment]
Closing - WinRT got removed from the runtime (https://github.com/dotnet/runtime/pull/36715).
