### ISSUE TITLE
IOptionsSnapshot is not getting the updated values  from app settings

### ISSUE THREAD

**Issue by mabusaa** [dotnet/runtime#33891]
I am using .net core 3.1

I am trying the IOptionsSnapshot with strongly typed settings. I am injecting it in a controller as below

1. The program class looks like below 

 ```
 public static void Main(string[] args)
        {
            Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));

            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((ctx, config) =>
            {
                config.SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("Config/appsettings.json", optional: false)
                .AddJsonFile($"Config/appsettings.{ctx.HostingEnvironment.EnvironmentName}.json", optional: true);

            })
            .UseStartup<Startup>()
            .Build();
```

2. the appettings is configured in startup as below :

`            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));
`

3. the controller look like below, injected the IOptionSnapshot in constructor  :

```
 private AppSettings _appKeys;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IOptionsSnapshot<AppSettings> appSettings)
        {
            _logger = logger;
            _appKeys = appSettings.Value;

        }
```

4. I am using it a method like below for testing , but the output is always the same even after editing the values after running the application 

```
        [HttpGet("GetConfigs")]
        public List<string> GetConfigs()
        {
            List<string> configs = new List<string>();

            configs.Add(_appKeys.Config1);

            configs.Add(_appKeys.Sql.ConnectionString);

            return configs;
        }
```

is there anything am missing , or is this a bug ?

**Comment by Tratcher** [comment]
IOptionsSnapshot has moved to runtime, transferring this issue.

**Comment by davidfowl** [comment]
cc @HaoK This should work right?

**Comment by HaoK** [comment]
I think it’s just missing reloadOnChange true in the config setup which is what triggers the updates. Otherwise the config would never get updated

**Comment by mabusaa** [comment]
> I think it’s just missing reloadOnChange true in the config setup which is what triggers the updates. Otherwise the config would never get updated
> […](#)
> On Mar 20, 2020, at 1:56 PM, David Fowler ***@***.***> wrote: ﻿ cc @HaoK This should work right? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I tried it with reloadOnChange  = true , but still not working

**Comment by HaoK** [comment]
There's two pieces of plumbing that are key.
1. reloadOnChange for the config to get Configuration to detect changes
2. a Configure that registers an IOptionsChangeTokenSource, this is done underneath the covers whenever you call `options.Configure(IConfiguration config)`, but if you aren't calling an overload variant of that, you will need to hook it up yourself for options to detect configuration changes: https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Options.ConfigurationExtensions/src/OptionsConfigurationServiceCollectionExtensions.cs#L72

**Comment by mabusaa** [comment]
If i got correctly , I tried it as below , but still not working

1. Added reloadOnChange = true

2. Updated the ConfigureServices as below 

` public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();

            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));

            services.AddSingleton<IOptionsChangeTokenSource<AppSettings>>(new ConfigurationChangeTokenSource<AppSettings>("AppSettings", Configuration));

            services.AddControllers();
        }`

**Comment by HaoK** [comment]
You shouldn't need more than reloadOnChange and `services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));`

And when you say its not working, what are you trying to do/expecting to work?

IOptionsSnapshot would only detect changes between requests.
You can try using IOptionsMonitor to see if that behaves any differently as that always checks the cache.  You can further debug by getting the cache `IOptionsMonitorCache<AppSettings>` and calling `Clear()` after you modify config to force options to reconfigure.  If that doesn't work, reload on change isn't working correctly for your app (which is a possibility)
https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Options/src/IOptionsMonitorCache.cs

**Comment by HaoK** [comment]
You can try printing out the config values in your app as well, to see if that's what's broken

**Comment by mabusaa** [comment]
what am doing is

1. hitting F5 and see the values. "I have a method that return the app settings values."
2. then i go to app setting json and update the values.
3. then i go to browser and refresh the page.
4. the same values are returned.

**Comment by HaoK** [comment]
Sure, so on that page, can you also get the Configuration directly and print out the values from that ( the thing that the AppSettings are binding to, because if those values don't change, the options won't ever change either)

**Comment by HaoK** [comment]
Also what environment is your app running on/ OS/hosting etc

**Comment by mabusaa** [comment]
windows 10 , IIS express , VS 2019

i will try and inform you

**Comment by mabusaa** [comment]
I tired it to add the value as below , also getting the old value

` configs.Add(_confiugration["AppSettings:Config1"]);`

**Comment by mabusaa** [comment]
I read the docs about IOptionsSnapshot , I need to the updated value  

> IOptionsSnapshot<TOptions> is useful in scenarios where options should be recomputed on every request.

**Comment by HaoK** [comment]
how are you accessing config?  try explicitly reloading the configuration via Reload on the ConfigurationRoot, you might need to cast the IConfiguration you get from DI to this.

https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/IConfigurationRoot.cs#L17

**Comment by HaoK** [comment]
But it looks like the issue is your config isn't reloading, that's why options isn't changing

**Comment by mabusaa** [comment]
I am accessing the config by constructor injection,

how can I reload it ?

```
public WeatherForecastController(ILogger<WeatherForecastController> logger, IConfiguration confiugration,  IOptionsSnapshot<AppSettings> appSettings)
        {
            _logger = logger;
            _appKeys = appSettings.Value;
            _confiugration = confiugration;

        }
```

**Comment by HaoK** [comment]
Looks like you just cast it to the root, see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1

```
    private IConfigurationRoot ConfigRoot;

    public Index2Model(IConfiguration configRoot)
    {
        ConfigRoot = (IConfigurationRoot)configRoot;
    }
```

**Comment by mabusaa** [comment]
i tried the below , no changes , still the old values are returned

```
  private IConfigurationRoot _configuration
            ;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IConfiguration configuration,  IOptionsSnapshot<AppSettings> appSettings)
        {
            _logger = logger;
            _appKeys = appSettings.Value;
            _configuration = configuration as IConfigurationRoot;
            _configuration.Reload();
        }
```

**Comment by HaoK** [comment]
What does your config registration look like?

**Comment by HaoK** [comment]
Oh I would try reloading on the request, not in the controller too.

**Comment by HaoK** [comment]
So reload the config in the method you are displaying so every time basically

**Comment by mabusaa** [comment]
the registration in Configure services

        `    services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));
`

I updated the method , still old values are returned

```
[HttpGet("GetConfigs")]
        public List<string> GetConfigs()
        {
            _configuration.Reload();

            List<string> configs = new List<string>();

            configs.Add(_appKeys.Config1);

            configs.Add(_appKeys.Sql.ConnectionString);

            configs.Add(_configuration["AppSettings:Config1"]);

            return configs;
        }
```

**Comment by HaoK** [comment]
I meant how is your IConfiguration being setup specifically, the AddJson calls, and all of the relevant methods there

**Comment by HaoK** [comment]
But I guess there's fundamentally your problem, if you call Reload on the configuration after updating your file on disk, and its not updating, this will never work.  I'm assuming if you stop your server and restart it updates the values?

**Comment by mabusaa** [comment]
this is the program class

 ```
public static void Main(string[] args)
        {
            Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));

            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((ctx, config) =>
            {
                config.SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("Config/appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"Config/appsettings.{ctx.HostingEnvironment.EnvironmentName}.json", optional: true, reloadOnChange: true);

            })
            .UseStartup<Startup>()
            .Build();
    }
```

**Comment by mabusaa** [comment]
> But I guess there's fundamentally your problem, if you call Reload on the configuration after updating your file on disk, and its not updating, this will never work. I'm assuming if you stop your server and restart it updates the values?

of course , if i restart the application , I will get the new values,

the idea is I want to get the new values without restarting the application ?

**Comment by HaoK** [comment]
So, seems like you are basically doing exactly the same thing as this blog post, https://edi.wang/post/2019/1/5/auto-refresh-settings-changes-in-aspnet-core-runtime

can you just walk through his steps and see if you are doing anything slightly different?

**Comment by HaoK** [comment]
There's also a similar example in the official docs as well: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1

**Comment by mabusaa** [comment]
that whats am doing , using the IOptionsSnapshot , but its not returning the new values when you refresh .

**Comment by mabusaa** [comment]
I figure out the problem , its my mistake 

in the program class , I removed this line and the new values started appearing
            `Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));
`
