### ISSUE TITLE
Consider documenting the initial contents of the Span<char> passed into SpanAction of string.Create method

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#33907]
[Looking at the documents](https://docs.microsoft.com/en-gb/dotnet/api/system.string.create?view=netcore-3.1#System_String_Create__1_System_Int32___0_System_Buffers_SpanAction_System_Char___0__) It is currently unclear on whether the contents are zeroed or contain random data. I believe currently the contents are zeroed (returned from FastAllocateString) but it would be nice to specify whether it is something people can rely on or not.

**Comment by bartonjs** [comment]
I believe the answer is "it's completely not guaranteed, you're responsible for assigning every position"

**Comment by Gnbrkm41** [comment]
I did guess so. However couldn't it be a breaking change if we were to change its implementation to give non-zeroed string? It has not been documented so far and currently it zeroes.

**Comment by danmosemsft** [comment]
@jkotas would it be reasonable to document this?

**Comment by jkotas** [comment]
> It's completely not guaranteed, you're responsible for assigning every position

Yes, it would be a good idea to mention this in the documentation.

> could it be a breaking change if we were to change its implementation to give non-zeroed string

We would not change this in servicing where we try to maintain bug-for-bug compatibility. I believe that we would be comfortable to change it for major version where we try to be compatible, but not bug-for-bug compatible.

**Comment by Gnbrkm41** [comment]
Great! I can put up a PR on the docs repo in the morning (local time).

Though, do I need to make two separate PRs (one in the docs repo, one in the runtime repo), or do the changes made in XML comments propagate down to the dotnet-api-docs repo?

**Comment by jkotas** [comment]
The XML comments and the docs repo are not kept in sync automatically. It has to be done manually.

**Comment by bartonjs** [comment]
I'd just do it in Remarks on the docs site, I wouldn't do anything here.

@jkotas So zero-init memory is guaranteed here for 2.1-5.0?

**Comment by jkotas** [comment]
It always happens to zero-init in 2.1 - 3.1. We have not shipped 5.0 yet...

**Comment by stephentoub** [comment]
We should document that it's not guaranteed. I believe that's what Jan is saying as well. Correct, Jan?

**Comment by jkotas** [comment]
Right. The docs should not mention that it happens to zero-init in 2.1 - 3.1

**Comment by bartonjs** [comment]
Somehow I decided Jan had quoted the "it's zero" instead of my "it's not guaranteed".  Good clarification.
