### ISSUE TITLE
Marshaling Delegate field behavioral change from .NET Framework

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#33919]
The following code runs as expected on .NET Framework, but fails on .NET5. The issue appears to be the generated IL Marshalers calling [`Marshal.GetDelegateFromFunctionPointer()`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.getdelegateforfunctionpointer) on .NET Core but do not on .NET Framework. The behavior and implementation of `Marshal.GetDelegateFromFunctionPointer()` between .NET5 and and .NET Framework are semantically identical. 

/cc @jkoritzinsky 

``` CSharp
public class Program
{
    public delegate IntPtr WndProc(IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam);
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    struct WNDCLASS
    {
        public uint style;
        public Delegate lpfnWndProc;
        // public WndProc lpfnWndProc;
        public int cbClsExtra;
        public int cbWndExtra;
        public IntPtr hInstance;
        public IntPtr hIcon;
        public IntPtr hCursor;
        public IntPtr hbrBackground;
        [MarshalAs(UnmanagedType.LPWStr)]
        public string lpszMenuName;
        [MarshalAs(UnmanagedType.LPWStr)]
        public string lpszClassName;
    }

    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    extern static IntPtr DefWindowProc(IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam);

    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    static extern ushort RegisterClass(ref WNDCLASS lpWndClass);

    private static Program.WndProc _sharedWndProc;
    private static ushort _sharedWindowClassAtom;

    static void Main(string[] args)
    {
        WNDCLASS wndclass = new WNDCLASS();
        wndclass.cbClsExtra = 0;
        wndclass.cbWndExtra = 0;
        wndclass.hbrBackground = IntPtr.Zero;
        wndclass.hCursor = IntPtr.Zero;
        wndclass.hIcon = IntPtr.Zero;
        wndclass.lpfnWndProc = _sharedWndProc = Program.DefWindowProc;
        wndclass.lpszClassName = "ThisClass";
        wndclass.lpszMenuName = null;
        wndclass.style = 0;

        _sharedWindowClassAtom = Program.RegisterClass(ref wndclass);
    }
}
```

**Comment by jkoritzinsky** [comment]
So the problem is that .NET Framework and .NET Core call `COMDelegate::ConvertToDelegate(LPVOID, MethodTable*)` directly, but .NET 5 calls `Marshal.GetDelegateForFunctionPointer`. `Marshal.GetDelegateForFunctionPointer` does some additional type validation.

The implementation that calls `COMDelegate::ConvertToDelegate` directly actually has a pretty serious bug if the type is `System.Delegate` or `System.MulticastDelegate`. If the function pointer passed in isn't an "unmanaged thunk to a managed delegate", the runtime will do an invalid cast of the EEClass for the method table to `DelegateEEClass*`, even though the EEClass isn't a DelegateEEClass.
https://github.com/dotnet/runtime/blob/f79afdbc3145285bb38113913bf9ca185cb8c699/src/coreclr/src/vm/comdelegate.cpp#L1370

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky So what are your thoughts on how to address this? Asserting? Or do you consider this a bug in marshaling design and should be avoided when possible?

>If the function pointer passed in isn't an "unmanaged thunk to a managed delegate"

Is this possible to do in practice? For example could a user cause this to occur in .NET Framework or .NET Core when only writing C#/VB?

**Comment by jkoritzinsky** [comment]
I think the behavior in .NET 5 is the correct behavior. I think that allowing marshalling a `System.Delegate`-typed field as a function pointer from native back to managed was a bug in .NET Framework and .NET Core 3.1 and lower and should be avoided when possible on those runtimes.

I would say that this is possible to do this in practice on .NET Framework or .NET Core. For example, if someone were to call `GetClassInfoW` with the following P/Invoke signature for a pre-defined Win32 window class with the above defined struct then they could attempt to marshal back a pointer to a native function in the WNDCLASS struct.

```
[DllImport("user32.dll", CharSet = CharSet.Unicode)]
static extern bool GetClassInfoW(IntPtr hinstance, string lpClassName, out WNDCLASS lpWndClass);
```

**Comment by AaronRobinsonMSFT** [comment]
>I think the behavior in .NET 5 is the correct behavior. I think that allowing marshalling a System.Delegate-typed field as a function pointer from native back to managed was a bug in .NET Framework and .NET Core 3.1 and lower and should be avoided when possible on those runtimes.

Okay. I am slightly concerned with the impact of this change will be. I think the fact that the workaround is straightforward does lend itself to being an okay change. Let's update our documentation for this. Perhaps https://docs.microsoft.com/dotnet/standard/native-interop/best-practices or https://docs.microsoft.com/dotnet/standard/native-interop/type-marshaling?

/cc @jeffschwMSFT

**Comment by jkoritzinsky** [comment]
I'll go add it to the best-practices document.

**Comment by vatsan-madhavan** [comment]
I'm assuming this is only a problem for `System.Delegate` (or `System.MultiCastDelegate`) typed fields, and had `WNDCLASS.lpfnWndProc` been declared as `WndProc`, all would have been well and .NET 5 would have continued behaving the same way as netfx & netcoreapp3.1 ?

**Comment by AaronRobinsonMSFT** [comment]
@vatsan-madhavan Yes. The issue here is in/out. Passing a `Delegate`/`MultiCastDelegate` in isn't much of an issue because the native side needs to cast it appropriately anyways. However, when it comes back out the type isn't known because `Delegate`/`MultiCastDelegate` are abstract and so can't be instantiated. Explicitly typing the delegate to a concrete class for in/out structs is the correct way to define the field and will work on both .NET Framework and .NET Core/.NET 5.
