### ISSUE TITLE
StringBuilder performance drops dramatically after frequent mutations

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#33912]
## StringBuilder performance drops dramatically after frequent mutations

Test code (using LinqPad for `Dump()`):
```csharp
const int docLength = 10000;

void Main()
{
    (from power in Enumerable.Range (1, 16)
    let mutations = (int) Math.Pow (2, power)
    select new
    {
        mutations,
        PerformanceRatio = Math.Round (GetPerformanceRatio (docLength, mutations), 1)
    }).Dump();
}

// Calculate performance ratio
float GetPerformanceRatio (int docLength, int mutations)
{
    var sb = new StringBuilder ("".PadRight (docLength));
    var before = GetPerformance (sb);
    FragmentStringBuilder (sb, mutations);
    var after = GetPerformance (sb);
    return (float) after.Ticks / before.Ticks;
}

// Insert an x and then remove it
void FragmentStringBuilder (StringBuilder sb, int mutations)
{
    var r = new Random(42);
    for (int i = 0; i < mutations; i++)
    {
        sb.Insert (r.Next (sb.Length), 'x');
        sb.Remove (r.Next (sb.Length), 1);
    }
}

// Get time cost for reading a StringBuilder sequentially
TimeSpan GetPerformance (StringBuilder sb)
{
    var sw = Stopwatch.StartNew();
    long tot = 0;
    for (int i = 0; i < sb.Length; i++)
    {
        char c = sb[i];
        tot += (int) c;
    }
    sw.Stop();
    return sw.Elapsed;
}
```

Result:

Mutations Count | Performance Ratio
-- | --
2 | 1
4 | 1
8 | 1
16 | 1
32 | 1
64 | 1.1
128 | 1.2
256 | 1.8
512 | 5.2
1024 | 19.9
2048 | 81.3
4096 | 274.5
8192 | 745.8
16384 | 1578.8
32768 | 1630.4
65536 | 930.8

Frequent mutations to a StringBuilder will cause lots of memory fragments, and it will make StringBuilder sequence reading performance really low. You can see that after 32768 times of mutations, performance of StringBuilder even drops to original's 1/1630. It's very terrible when you use `StringBuilder` as a text buffer for code generation.

Visual Studio Code used [`PieceTable`](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation) to implement its text buffer to resolve the problem, and I think current implementation of StringBuilder should be optimized too.

Thanks.

> This is a translation of a blog written in Chinese, link: https://www.cnblogs.com/sdflysha/p/20200317-memory-fragment-performance-impact-to-stringbuilder.html
> May related to #25464

**Comment by stephentoub** [comment]
StringBuilder is optimized for its most common use case by far: appends. The memory issues you're seeing come from the inserts. In that way, this is a dup of https://github.com/dotnet/runtime/issues/25464
