### ISSUE TITLE
System.Text.Json.Serialization.Tests.ConstructorTests_StringTValue.OtherPropertiesAreSet fails with nullref

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#33928]
<b>Build job:</b> Libraries Test Run release mono Linux x64 Release

<b>Example pipeline:</b> https://dev.azure.com/dnceng/public/_build/results?buildId=568935&view=logs&j=3b5945b0-87a7-52cf-843a-406c21a8e27e&t=7eb56c92-15af-5ace-3e2c-14c3e65847f5

<b>Failure log:</b>

<pre>
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 2)
    System.Text.Json.Serialization.Tests.ConstructorTests_StringTValue.OtherPropertiesAreSet [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectWithParameterizedConstructorConverter.Small.cs(25,0): at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[System.Text.Json.Serialization.Tests.Point_2D_With_ExtData_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateObject(ReadStackFrame& frame)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectWithParameterizedConstructorConverter.cs(35,0): at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1[[System.Text.Json.Serialization.Tests.Point_2D_With_ExtData_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Point_2D_With_ExtData_Class& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs(159,0): at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.Point_2D_With_ExtData_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Point_2D_With_ExtData_Class& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfTTypeToConvert.cs(164,0): at System.Text.Json.JsonPropertyInfo`1[[System.Text.Json.Serialization.Tests.Point_2D_With_ExtData_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectDefaultConverter.cs(379,0): at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[System.Text.Json.Serialization.Tests.Person_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadPropertyValue(Object obj, ReadStack& state, Utf8JsonReader& reader, JsonPropertyInfo jsonPropertyInfo, Boolean useExtensionProperty)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectWithParameterizedConstructorConverter.cs(67,0): at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1[[System.Text.Json.Serialization.Tests.Person_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Person_Class& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs(159,0): at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.Person_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Person_Class& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs(61,0): at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.Person_Class, System.Text.Json.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(26,0): at System.Text.Json.JsonSerializer.ReadCore[Person_Class](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(18,0): at System.Text.Json.JsonSerializer.ReadCore[Person_Class](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(116,0): at System.Text.Json.JsonSerializer.Deserialize[Person_Class](String json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(47,0): at System.Text.Json.JsonSerializer.Deserialize[Person_Class](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(26,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.StringTValueSerializerWrapper.Deserialize[Person_Class](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests.ParameterMatching.cs(307,0): at System.Text.Json.Serialization.Tests.ConstructorTests.OtherPropertiesAreSet()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Text.Json.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.Json.Tests  Total: 11731, Errors: 0, Failed: 1, Skipped: 0, Time: 37.764s
</pre>

**Comment by jkotas** [comment]
Hit again in #33933

**Comment by ericstj** [comment]
Here's the data from the last 100 builds:
|Build|Kind|Console Log|
|---|---|---|
|[568452](https://dev.azure.com/dnceng/public/_build/results?buildId=568452)|PR https://github.com/dotnet/runtime/pull/33852|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4cf7fd72-ff0b-42e1-aa97-212167e1ab1e/workitems/System.Text.Json.Tests/files/console.2b0cfe73.log)|
|[568335](https://dev.azure.com/dnceng/public/_build/results?buildId=568335)|PR https://github.com/dotnet/runtime/pull/33674|[console.log](https://helix.dot.net/api/2019-06-17/jobs/9488892c-bd77-422d-850e-a0e57e52d485/workitems/System.Text.Json.Tests/files/console.22e9cd4c.log)|
|[568266](https://dev.azure.com/dnceng/public/_build/results?buildId=568266)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/1f59258e-c758-4de4-ae05-c7f393b455c6/workitems/System.Text.Json.Tests/files/console.dad37371.log)|
|[567761](https://dev.azure.com/dnceng/public/_build/results?buildId=567761)|PR https://github.com/dotnet/runtime/pull/33892|[console.log](https://helix.dot.net/api/2019-06-17/jobs/e321bd3a-475c-478d-bd08-8f2edf25cc4a/workitems/System.Text.Json.Tests/files/console.1c6c2226.log)|
|[568935](https://dev.azure.com/dnceng/public/_build/results?buildId=568935)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4719076b-c549-4ff9-a23f-28778f49c97f/workitems/System.Text.Json.Tests/files/console.d99a574b.log)|
|[568318](https://dev.azure.com/dnceng/public/_build/results?buildId=568318)|PR https://github.com/dotnet/runtime/pull/33911|[console.log](https://helix.dot.net/api/2019-06-17/jobs/6561aadb-46bf-4c88-994a-881b821dc680/workitems/System.Text.Json.Tests/files/console.bad68226.log)|
|[568678](https://dev.azure.com/dnceng/public/_build/results?buildId=568678)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/03115a33-5194-4d7b-9033-9dcc16feeb8c/workitems/System.Text.Json.Tests/files/console.0ff3acaf.log)|
|[569159](https://dev.azure.com/dnceng/public/_build/results?buildId=569159)|PR https://github.com/dotnet/runtime/pull/33933|[console.log](https://helix.dot.net/api/2019-06-17/jobs/82f1620b-5f6b-4ad3-80fa-98d9a4033f9c/workitems/System.Text.Json.Tests/files/console.a06f4292.log)|
|[568167](https://dev.azure.com/dnceng/public/_build/results?buildId=568167)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/5fcd7a52-223f-4117-98d0-c5361a335948/workitems/System.Text.Json.Tests/files/console.c8d111f2.log)|
