### ISSUE TITLE
System.Runtime.Loader Nuget out of date AssemblyLoadContext constructors

### ISSUE THREAD

**Issue by luhis** [dotnet/runtime#33935]
I am making use of the collectable assemblies functionality in AssemblyLoadContext released with Core3.1.  It works fine within a Core3.1 project, but if i try to move it out to a Standard2.1 library for reuse, the System.Runtime.Loader Nuget is out of date and does not have the new collectable constructor.

Does the Nuget need updating, or is there another reason for this?

**Comment by jkotas** [comment]
.NET Standard 2.1 does not include collectible assemblies feature. You have to target netcoreapp3.0+ to use collectible assemblies.

System.Runtime.Loader is left over from .NET Core 1.0 where the platform was composed from many small NuGet packages. We are not planning to update these NuGet packages.

**Comment by luhis** [comment]
ah, that explains it.  thanks
