### ISSUE TITLE
How can I use TlsCipherSuite.TLS_RSA_WITH_DES_CBC_SHA in Sslsteam

### ISSUE THREAD

**Issue by Jackcu** [dotnet/runtime#33947]
# Scenario
There are old  server that use TLS for data transmission and work with weak TlsCipherSuite:TLS_RSA_WITH_DES_CBC_SHA and accept TLS_RSA_WITH_DES_CBC_SHA only. I have to send TLS_RSA_WITH_DES_CBC_SHA on "Hello client"

![image](https://user-images.githubusercontent.com/6947638/77286717-d0e72380-6d0e-11ea-95a2-9efc18d05148.png)

OS: macOS, windows

# What I want
![image](https://user-images.githubusercontent.com/6947638/77285525-279f2e00-6d0c-11ea-9ada-b1ad7360dbfa.png)

# My code
I have tried following code with reflect,it's not work and throw a exception
```
_ssls = new SslStream(_ns, false, ValidateServerCertificate, null);

var method_AuthenticateAsClient = typeof(SslStream).GetMethods(BindingFlags.NonPublic | BindingFlags.Instance)
                                                   .ToList()
                                                   .Where(v => v.Name == "AuthenticateAsClient")
                                                   .First();
var tlsCipherSuites = new List<TlsCipherSuite>() {TlsCipherSuite.TLS_RSA_WITH_DES_CBC_SHA};
var policy          = new CipherSuitesPolicy(tlsCipherSuites);
var opt = new SslClientAuthenticationOptions() {
    TargetHost                     = "test1"
  , ClientCertificates             = null
  , EnabledSslProtocols            = SslProtocols.Tls
  , CertificateRevocationCheckMode = X509RevocationMode.NoCheck
  , EncryptionPolicy               = EncryptionPolicy.RequireEncryption
  , CipherSuitesPolicy             = policy
};

method_AuthenticateAsClient.Invoke(_ssls, new[] {opt});

```
![image](https://user-images.githubusercontent.com/6947638/77286493-51595480-6d0e-11ea-9266-b44b89eea63a.png)

```
Exception has been thrown by the target of an invocation. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+AppleCrypto+SslException: One or more parameters passed to a function were not valid.
  at at System.Net.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
  at at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
```

**Comment by davidsh** [comment]
What OS are you using? Windows, Linux, Mac?

The cipher suites policy feature, for example, doesn't work in Windows due to OS limitations.

**Comment by Jackcu** [comment]
it throw a Exception with message that is "windows not support CipherSuitesPolicy" in windows.
in mac,it throw Interop+AppleCrypto+SslException: One or more parameters passed to a function were not valid

**Comment by wfurt** [comment]
The Windows behavior is documented and as @davidsh mentioned the ism because of underplaying OS limitations. What version of macOS and .NET do you use? I've seen something similar when testing TLS1.3. It is possible that OS does not like the particular cipher. 
Can you craft runnable repo @Jackcu? And any reason for the reflection?

**Comment by Jackcu** [comment]
Thank you all for your time.
My dev-environment: Mac 10.15.3 and Windows10 1909. dotnet core 3.1.2,TLSv1.
Yes,the CipherSuites for "Client Hello" are OS dependant. eg.Schannel in Windows controls CipherSuites sent to server for negotiation. Accroding to the [list](https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-10--version-1507) TLS_RSA_WITH_DES_CBC_SHA (what I need) can be allowed by switch SCH_USE_STRONG_CRYPTO. Unfortunately,the switch has been used with SystemDefaults [#27382](https://github.com/dotnet/corefx/commit/ac46f56). 

Is there someway I can set SCH_USE_STRONG_CRYPTO in dotnet core.

**Comment by Monorihan** [comment]
you can try this method:
Win7 SP1 system, in PC Registry
HKEY_LOCAL_MACHINE \ SYSTEM \ CurrentControlSet \ Control \ Cryptography \ Configuration \ Local \ SSL \ 0001002 \ Functions
TLS_RSA_WITH_DES_CBC_SHA added and TLS_RSA_WITH_NULL_XXX deleted.
Update Windows6.1-KB2533623-x64 Patch

**Comment by Jackcu** [comment]
Yes,It works fine in Win7.  
OS layer modification will affect cipher suites policy of the other application.
I'm trying use detour to hook AcquireCredentialsHandle, the argument pAuthData can control which cipher suites will be filter.

**Comment by wfurt** [comment]
Did you get this solved somehow @jackcu? There is API to allow impacting ciphers but it 1. is not available on Windows 7 and 2. .NET does not use it. I'm not sure about your comment about SCH_USE_STRONG_CRYPTO. That would be normally set unless you request weak parameters. 

I don't think this issue is not actionable at the moment.

**Comment by karelz** [comment]
Closing as not actionable. Feel free to reopen if/when there is more info. Thanks!
