### ISSUE TITLE
Mismatched XML documentation for ValidationAttribute?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/runtime#33957]
https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/ValidationAttribute.cs

XML documentation for the constructor with  a string argument reads the following:
```
        //
        // Summary:
        //     Initializes a new instance of the System.ComponentModel.DataAnnotations.ValidationAttribute
        //     class by using the error message to associate with a validation control.
        //
        // Parameters:
        //   errorMessage:
        //     The error message to associate with a validation control.
```

Where as inside ValidationAttribute.cs, its 
```
        /// <summary>
        ///     Constructor that accepts a fixed validation error message.
        /// </summary>
        /// <param name="errorMessage">A non-localized error message to use in <see cref="ErrorMessageString" />.</param>
```

I'm guessing this is intentional? Is there a way to switch between the two? As the latter is much more clearer, especially for the following:

```
        /// <summary>
        ///     Default constructor for any validation attribute.
        /// </summary>
        /// <remarks>
        ///     This constructor chooses a very generic validation error message.
        ///     Developers subclassing ValidationAttribute should use other constructors
        ///     or supply a better message.
        /// </remarks>
```

**Comment by scalablecory** [comment]
The XML comments within source files is only used for documentation once. From then on, docs are updated in the [dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/ValidationAttribute.xml#L129) repo -- we do not make an effort to keep these in sync with source.

We can accept changes to the docs repo, though, if you feel something can be clarified.

**Comment by SpiritBob** [comment]
@scalablecory Sorry for the late reply. A good suggestion in my eyes would be to replace what we now have in the dotnet-api-docs repo for `ValidationAttribute.ValidationAttribute()` constructor to the one used in the source

```
        /// <summary>
        ///     Default constructor for any validation attribute.
        /// </summary>
        /// <remarks>
        ///     This constructor chooses a very generic validation error message.
        ///     Developers subclassing ValidationAttribute should use other constructors
        ///     or supply a better message.
        /// </remarks>
```

**Comment by ericstj** [comment]
@SpiritBob it looks to me like it already has this?
https://github.com/dotnet/dotnet-api-docs/blob/469d167b84246c5e3ecad1a36e942c7f5c5a22a5/xml/System.ComponentModel.DataAnnotations/ValidationAttribute.xml#L77-L85

Feel free to submit a PR over there with your exact recommended changes.
