### ISSUE TITLE
Proposal: allow "stackalloc" class references' array when using span

### ISSUE THREAD

**Issue by ygc369** [dotnet/runtime#33960]
Currently the following code is disallowed:
```C#
span<object> arr = stackalloc object[10];
```
But I think that this should be allowed, stackalloc object[10] should not mean to allocate 10 objects on the stack, it should mean to allocate 10 object references on the stack (all initialized to null).
I have posted this proposal in csharplang repo(https://github.com/dotnet/csharplang/issues/3294), but someone told me this is a runtime issue, because the corresponding IL instruction only supports struct now. So I think this proposal need CLR support.

**Comment by jkotas** [comment]
Related / duplicate: https://github.com/dotnet/runtime/issues/25423

**Comment by ygc369** [comment]
@jkotas 

> Related / duplicate: #25423

I think they are different. That proposal focus on "safety", but my proposal focus on "freedom".

**Comment by jkotas** [comment]
Both of the proposals are solving the same problem. #25423 has the nice property that it also solves problems with `stackalloc` in general.

**Comment by GSPP** [comment]
If the runtime becomes capable of stack allocating references, this should just work with the normal `stackalloc` keyword. https://github.com/dotnet/runtime/issues/25423 would not include that work.
