### ISSUE TITLE
Use cmeq, cmge, cmgt (zero) when one of the operands is Vector64/128<T>.Zero

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#33972]
For example,

The code as in https://github.com/dotnet/runtime/pull/33749#issuecomment-601447809 **BitArray:.ctor**
```asm
dup     v17.16b, wzr
cmeq    v16.16b, v16.16b, v17.16b
```
should be optimized down to
```asm
cmeq    v16.16b, v16.16b, #0
```

This applies to all the intrinsics that are mapped to cmeq, cmge, cmgt, cmle, cmlt, fcmeq, fcmge, fcmgt, fcmle and fcmlt instructions

category:cq
theme:hardware-intrinsics
skill-level:intermediate
cost:small

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/runtime/blob/c74407fcaff466a17b6e98f1dcc969248de506fe/src/libraries/System.Collections/src/System/Collections/BitArray.cs#L183-L195

**Comment by echesakovMSFT** [comment]
I believe this item was addressed fully.
@TIHan can you please confirm and close the issue?

**Comment by TIHan** [comment]
Yes, I believe it was. There is more opportunity with other instructions like 'cmle' and 'cmlt', but based on the title of this issue, we got them covered.
