### ISSUE TITLE
Shift-JIS Encoding throws 'System.NotSupportedException' in BodyName

### ISSUE THREAD

**Issue by imxike** [dotnet/runtime#33979]
Net Core 3.1 (netcoreapp3.1)
Visual Studio Community 2019 (16.5.0)
OS: Windows 10 (1903)

When i'm trying to use JsonConvert.SerializeObject my Object which have japan-character. It raise the following exception

> Newtonsoft.Json.JsonSerializationException: 'Error getting value from 'BodyName' on 'System.Text.DBCSCodePageEncoding'.'
NotSupportedException: No data is available for encoding 932. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

Trying to find whats problem here, i found that the encoding i'm using throw exception in the property. I have registered the  `EncodingProvider.Instance` before i'm using it
![image](https://user-images.githubusercontent.com/8916625/77277396-64106100-6cef-11ea-9322-5364adc2dcfa.png)

Is it unable to use SerializeObject which have shift-jis encoding in .net core 3. Or is it a bug from the encoding. Please help. Thank you.

**Comment by nechvatalp** [comment]
I experience the same issue.

**Comment by tarekgh** [comment]
We don't support serializing the encoding objects in .NET Core. You may need to look at your object and try to have it to serialize the encoding name as a string instead of the actual encoding object. if you have more details we can try to look at and try to help providing the workaround.
