### ISSUE TITLE
Add RID for 32bit ios

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#33982]
This would be straight forward if Apple didn't drop the support for 32bits in the recent versions. The last supported 32bit version is ios 10.

RIDs for other ios architectures already exist and only 32 bit needs to be added up to `ios-10-arm`.

@ericstj please advice on the correct logic.

**Comment by ericstj** [comment]
You should be able to define separate groups.  Any overlapping RIDs will be dedup-ed so long as they have the same imports.  I submitted a PR based on what I think you want.  Please review.
