### ISSUE TITLE
LoggingBuilderExtensions: Duplicate type in M.E.Logging and M.E.Logging.Configuration

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#33998]
The type LoggingBuilderExtensions is in both Microsoft.Extensions.Logging and Microsoft.Extensions.Logging.Configuration
This is a pre-existing issue and, as a side effect, it makes it impossible to use LoggingBuilderExtensions when referencing both assemblies.

A part of PR https://github.com/dotnet/runtime/pull/33984/files makes a change to suppress the duplicate error for now.

**Comment by ericstj** [comment]
Not completely impossible.  I bet the compiler will still resolve an extension method in either type (though we could test it).  It's likely only a real issues if the same methods exist, or if someone was trying to refer to the static method (rather than as an extension method).

**Comment by ericstj** [comment]
Moved this to future since the duplication has existed for past releases and we aren't going to make a breaking change to resolve it.

The common scenario works:
```c#
builder.SetMinimumLevel(LogLevel.Trace);
builder.AddProvider(provider);
builder.ClearProviders();
builder.AddConfiguration(configuration);
```

It's only the following that fail:
```c#
LoggingBuilderExtensions.SetMinimumLevel(builder, LogLevel.Trace);
LoggingBuilderExtensions.AddProvider(builder, provider);
LoggingBuilderExtensions.ClearProviders(builder);
LoggingBuilderExtensions.AddConfiguration(builder, configuration);
var type = typeof(LoggingBuilderExtensions);
```

**Comment by maryamariyan** [comment]
To fix this we have to have a breaking change and as @ericstj mentioned the common scenario works fine. Therefore, closing it, if someone hits this issue we can reopen and plan for a fix.
