### ISSUE TITLE
Test failures: Microsoft.Extensions.Caching.Memory flakiness

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#33993]
```
Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.GetAndSet_AreThreadSafe_AndUpdatesNeverLeavesNullValues [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/MemoryCacheSetAndRemoveTests.cs(488,0): at Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.GetAndSet_AreThreadSafe_AndUpdatesNeverLeavesNullValues()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

https://helix.dot.net/api/2019-06-17/jobs/e7ed99d0-5a25-4792-8b58-04c5a0009c69/workitems/Microsoft.Extensions.Caching.Memory.Tests/console

---
UPDATE:
Failures not just on Mono. The flakiness reported in https://github.com/dotnet/runtime/issues/34128 and disabled in PR https://github.com/dotnet/runtime/pull/34142

**Comment by ericstj** [comment]
Duping this to https://github.com/dotnet/runtime/issues/34128 since it has more data.

**Comment by ericstj** [comment]
Reopen since tests are disabled against this

**Comment by ericstj** [comment]
There may be more tests failing than just these.  I sampled some of the logs listed in #34128 and see a couple other tests failing:

```
Microsoft.Extensions.Caching.Memory.CapacityTests.CompactsToLessThanLowWatermarkUsingLRUWhenHighWatermarkExceeded [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/CapacityTests.cs(378,0): at Microsoft.Extensions.Caching.Memory.CapacityTests.CompactsToLessThanLowWatermarkUsingLRUWhenHighWatermarkExceeded()
```

```
    Microsoft.Extensions.Caching.Memory.CapacityTests.ExpiringEntryDecreasesCacheSize [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/CapacityTests.cs(338,0): at Microsoft.Extensions.Caching.Memory.CapacityTests.ExpiringEntryDecreasesCacheSize()
```

I wonder if there is something broken with how we're testing these in dotnet/runtime?  Maybe concurrency differences and shared state?

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstress 20200726.1](https://dev.azure.com/dnceng/public/_build/results?buildId=746053&view=ms.vss-test-web.build-test-results-tab&runId=23124036&resultId=102773&paneView=debug)

failed test: Microsoft.Extensions.Caching.Memory.CapacityTests.DoNotAddIfSizeOverflows


Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.Caching.Memory.CapacityTests.DoNotAddIfSizeOverflows() in /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/CapacityTests.cs:line 137
--- End of stack trace from previous location ---
~~~

**Comment by danmoseley** [comment]
Duping arbitrarily https://github.com/dotnet/runtime/issues/50270

**Comment by jkotas** [comment]
We still have 7 tests disabled against this issue.

**Comment by danmoseley** [comment]
More commentary in https://github.com/dotnet/runtime/issues/50270

**Comment by jakobbotsch** [comment]
Failed again in https://dev.azure.com/dnceng/public/_build/results?buildId=1903569&view=ms.vss-test-web.build-test-results-tab&runId=49497968&resultId=111528&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab after the reenabling

**Comment by danmoseley** [comment]
I'll disable that asap and create a new issue, for clarity, as this has covered other symptoms...

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/72879
