### ISSUE TITLE
Change Environment.GetFolderPath to be compatible with tvOS

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#34007]
As part of the mobile workloads migration, we need to ensure the apps are behaving consistently when calling into `Environment.GetFolderPath`. There is already some implementation for iOS but it looks like it's not fully compatible with existing Mono code

The second part is to ensure there is full code coverage for all `SpecialFolder` values.

**Comment by akoeplinger** [comment]
We still have an important TODO that needs to be fixed for tvOS: https://github.com/dotnet/runtime/blob/f48c8d581b584495079fa5f2b2789ef48546edd9/src/mono/netcore/System.Private.CoreLib/src/System/Environment.iOS.cs#L39-L41

Reopening to track that.

**Comment by marek-safar** [comment]
@steveisok please assign

**Comment by directhex** [comment]
It looks like NSCachesDirectory is the preferred alternative for tvOS.

Ref: https://github.com/firebase/firebase-ios-sdk/pull/2777
Ref: https://developer.apple.com/forums/thread/19002

**Comment by akoeplinger** [comment]
@directhex on the mono/mono version we've been using a subdirectory in `NSLibraryDirectory`: https://github.com/mono/mono/blob/main/mcs/class/corlib/System/Environment.iOS.cs#L21-L30
