### ISSUE TITLE
how to use dotnet command to get the newest release??

### ISSUE THREAD

**Issue by larryw3i** [dotnet/runtime#34004]
I'll thank dotnet for it improves my patience and teachs me how to unzip/update it's newest release instead of using terminal after the first installing
![Screenshot from 2020-03-24 14-57-11](https://user-images.githubusercontent.com/24457116/77397082-ef691f80-6ddf-11ea-9e7c-28483d694f8e.png)

**Comment by am11** [comment]
Related https://github.com/dotnet/sdk/issues/10848.

**Comment by joperezr** [comment]
I don't believe there is a way to do it from the dotnet command, but you should be able to do it by using the dotnet install scripts. You can get all the info on how to run them here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

**Comment by joperezr** [comment]
Closing for now since this seems like it was a question which has been answered. Feel free to reopen otherwise.
