### ISSUE TITLE
Add MetaDataGetDispenser export as public API for profilers

### ISSUE THREAD

**Issue by georgschausberger** [dotnet/runtime#34014]
Since ilasm didn't need the export for MetaDataGetDispenser any more it was removed in
https://github.com/dotnet/runtime/commit/a6cbdae05eaa017e8e11eb1954c9525c62e5dfe0#diff-9246b6a12f41551eeb91940bd9905151L30 .

MetaDataGetDispenser is needed for profilers to access interfaces like IMetaDataEmit.

Already talked to @jkotas about this.

**Comment by jkotas** [comment]
The profilers are meant to get IMetaDataEmit interface using  `ICorProfilerInfo2::GetModuleMetadata` . Here is an example that shows how to do it: https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/profiling/davbr-blog-archive/samples/Add%20local%20to%20LocalVarSig.cpp

Could you please describe how you are using the MetaDataGetDispenser interface?

**Comment by georgschausberger** [comment]
Yes it is used that way (ICorProfilerInfo2::GetModuleMetadata()).
We are using MetDataDispenser::OpenScopeOnMemory() to get these interfaces for various use cases (e.g. accessing meta data on ModuleLoadStarted where the above metadata is not complete yet).

Is there any other way to access memory/file mapped assemblies including the emit interface?

**Comment by jkotas** [comment]
@dotnet/dotnet-diag Adding this back is a trivial one line change. Are you ok with supporting this API for profilers? If yes, we should add some tests for it.

**Comment by tommcdon** [comment]
I think it is reasonable to add the export back. @davmason can you look at adding test coverage for this scenario?

**Comment by georgschausberger** [comment]
I'm ok with it.

**Comment by davmason** [comment]
@georgschausberger Can you be more specific with your scenario? Typically if you want to access something like IMetadataEmit you would do so in ModuleLoadFinished where the metadata is already populated.

**Comment by georgschausberger** [comment]
@davmason We are changing metadata (adding new types, adding references, etc.) which has to be done on ModuleLoadStarted. This lead to problems on Linux.
Second use case are tests which load assemblies without a runtime.

The dispenser is used to query the IMetaDataTables via OpenScopeOnMemory(), which is then used to query interfaces for IMetaDataImport, IMetaDataAssemblyEmit, IMetaDataEmit, and IMetaDataAssemblyImport.

**Comment by davmason** [comment]
@georgschausberger Adding new types, references, etc should all work in ModuleLoadFinished without issue. You shouldn't have to call MetaDataGetDispenser for those operations.

I don't think there is another way to get the metadata readers for reading files off disk without loading them though.

Doing some additional investigating we found that VS has a dependency on MetaDataGetDispenser, so it should be added back.

**Comment by georgschausberger** [comment]
@davmason Thanks for adding it back. We've tried to change this some time ago but unfortunately the tests proved this to be not working.

**Comment by tommcdon** [comment]
Closing since #34113 was merged
