### ISSUE TITLE
Build on FreeBSD without workarounds: use proper SDK tooling

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3401]
Collection of comments from https://github.com/dotnet/core-setup/pull/4936:

> [@wfurt] BTW we will need to pass in override variables like we did before or update DotnetCLIVersion.txt There is no 2.x version for FreeBSD. core-sdk used 3.,0 preview 1 build.

> [@dagood] Back when we did have the FreeBSD pool, the leg reports it succeeded: https://dnceng.visualstudio.com/public/_build/results?buildId=68484. It does say `Unsupported OS 'FreeBSD' detected. Downloading linux-x64 tools` though. What symptoms would you expect?

> [@wfurt] that is because old build used environmental variables to point at locally installed SDK. If core-setup uses arcade now, we should either use updated version or use same values as corefx. (may be fastest to talk on IM)

> [@wfurt] We can do little bit more and we can remove all special handling.
> 
> ```
> [toweinfu@toweinfu-fbsd /mnt/resource/core-setup]$ git diff
> diff --git a/DotnetCLIVersion.txt b/DotnetCLIVersion.txt
> index 6f1c03c6..2b1526a3 100644
> --- a/DotnetCLIVersion.txt
> +++ b/DotnetCLIVersion.txt
> @@ -1 +1 @@
> -2.1.401
> \ No newline at end of file
> +3.0.100-preview-009812
> diff --git a/init-tools.sh b/init-tools.sh
> index 5e6abb3c..281c2cdd 100755
> --- a/init-tools.sh
> +++ b/init-tools.sh
> @@ -86,7 +86,10 @@ if [ ! -e "$__DOTNET_PATH" ]; then
>                      exit 1
>                  fi
>                  ;;
> -
> +            FreeBSD)
> +                OS=FreeBSD
> +                __PKG_RID=freebsd
> +                ;;
>              Linux)
>                  __PKG_RID=linux
>                  OS=Linux
> ```
> > Total tests: 109. Passed: 109. Failed: 0. Skipped: 0.
> > Test Run Successful.
> > Test execution time: 5.5528 Seconds
> > Build succeeded.
> 
> With this we would
> 
> * not need variable override or local SDK.
> * can do crossgen
> * can run all tests
> 
> The CLI update is needed as there is no 2.1x version.
> I choose version used by core-sdk to decrease variations but we can also use any newer available version.

That SDK version looks good to me. `3.0.100-preview-009812` is the 3.0.0-preview1 version source-build produces, so using it will let source-build build preview2's SDK with the N-1 (preview1) SDK build.

**Comment by NikolaMilosavljevic** [comment]
@wfurt does this still repro in dotnet/runtime? Is this needed?

**Comment by wfurt** [comment]
This is probably not relevant as we don't use init-tools.sh any more (replaced with Arcade) and we don't publish FreeBSD builds any more. The battle shifted to source-build now.
