### ISSUE TITLE
Microsoft.Extensions.Http test failure on mono

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#34023]
This issue tracks Http test failing on Mono:
```
Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler
```

https://helix.dot.net/api/2019-06-17/jobs/c6ed46b1-0512-4f5d-b721-ecaaaa01dc59/workitems/Microsoft.Extensions.Http.Tests/console

```
Discovering: Microsoft.Extensions.Http.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Http.Tests (found 70 test cases)
  Starting:    Microsoft.Extensions.Http.Tests (parallel test collections = on, max threads = 2)
    Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler [FAIL]
      Cleanup entry disposable
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Http/tests/DefaultHttpClientFactoryTest.cs(449,0): at Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler()
        --- End of stack trace from previous location ---
  Finished:    Microsoft.Extensions.Http.Tests
```

**Comment by safern** [comment]
Added console output to description since the file links might expire.

**Comment by danmosemsft** [comment]
@maryamariyan there is a label `runtime-mono` that is handy for mono specific issues

**Comment by danmosemsft** [comment]
Likely relates to different GC behavior on Mono. Test says "depends on the GC and timing."

**Comment by jkotas** [comment]
Failed in #39717

**Comment by danmosemsft** [comment]
@maryamariyan please fix or disable

**Comment by akoeplinger** [comment]
@maryamariyan I think this is the result of different GC on Mono, we disabled some similar tests with the `PlatformDetection.IsPreciseGcSupported` which returns false on Mono. The same should be done with this test.

**Comment by directhex** [comment]
Closing the issue, since the test in question is now annotated with IsPreciseGcSupported. If Mono ever supports that, we can revisit related issues.
