### ISSUE TITLE
IReadOnlyList<T> should implement IndexOf(T item);

### ISSUE THREAD

**Issue by gregmac** [dotnet/runtime#34020]
Currently `int IndexOf(T item);` is implemented in `IList<T>`, but not `IReadOnlyList<T>`. There's several cases where this would be useful to have, and there doesn't seem to be any clear reason it's not implemented in `IReadOnlyList<T>`. 

Many (if not all?) of the built-in usages of `IReadOnlyList<T>` also implement `IList<T>`, so at least within the .NET codebase it seems this would have very little impact.

**Comment by bartonjs** [comment]
.NET Standard is a description of API shapes that have already shipped. Modifying API has to start with an implementation project, so I've transferred the issue to dotnet/runtime.

**Comment by huoyaoyuan** [comment]
**This can't be done** because `IReadOnlyList<T>` is *covariance*, while `IList<T>` is not.
