### ISSUE TITLE
RyuJIT: Is `*(&X) -> X` optimization safe?

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#34026]
Just a minor issue (is it?), morph seems to optimize `*(&X)` to `X` (see https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/morph.cpp#L3747)
```csharp
int  a =  (*((int*)0)); // throws NRE
int* b = &(*((int*)0)); // optimized to `(int*)0`, no NRE
```
Is it correct?

(from twitter: https://twitter.com/konradkokosa/status/1242491683557773314)

I know It's pretty normal for C/C++ compilers to do such UB optimizations but is it for C#? 

category:correctness
theme:question
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
From what I can see, Roslyn is the one doing this optimization.

**Comment by EgorBo** [comment]
hm... but doesn't JIT also do it in morph (link ^)?

**Comment by AndyAyersMS** [comment]
> hm... but doesn't JIT also does it in morph too (link ^)?

Hard to say if that amounts to the same thing -- we'd need to start with IL and then see if what the jit does violates IL semantics.

**Comment by am11** [comment]
Interesting that both decompile to [same thing](https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UgrgHYDOAhgGYCmyALIgLIQAUAlNrljLt4gJaEAXHKUQBeHEwBUTJvwGSWABhYsA3OxwBfDXkREyVWgzCtMO7nMmIARmMQAyKTMtKV6rjxxzEAYzuTrd25tGE0gA==).

**Comment by sandreenko** [comment]
> Just a minor issue (is it?), morph seems to optimize *(&X) to X (see

I think it is correct, in your test it is `&(*(X))` that we don't fold (or I am not aware that we do).

**Comment by BruceForstall** [comment]
@EgorBo Do you have any outstanding question here?

**Comment by sandreenko** [comment]
I have checked that again and found one case:
https://github.com/dotnet/runtime/blob/247b657d314bf612d74e1c9eda3d3b8911f3769f/src/coreclr/src/jit/morph.cpp#L13279, but we do it pretty inconsistently, for example in another case we do it only for IND(ADDR(IND())) case that is more conservative:
https://github.com/dotnet/runtime/blob/247b657d314bf612d74e1c9eda3d3b8911f3769f/src/coreclr/src/jit/compiler.hpp#L969
