### ISSUE TITLE
Single-File: dotnet don't check if the temp files are corrupted

### ISSUE THREAD

**Issue by yehia2amer** [dotnet/runtime#34035]
**Problem**
I got a weird issue from one of my customers, that each time he is trying to run the application. he got this error:
```
Error:
  An assembly specified in the application dependencies manifest (appname.deps.json) was not found:
    package: 'Microsoft.DotNet.PlatformAbstractions', version: '2.0.4'
    path: 'lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll'
```

After debugging for a couple of hours it turns out that the files in the temp folder : %TEMP%\.net are somehow corrupted or not complete. and the issue was fixed by deleting the folder and running again.

**Suggested Solution**
dotnet save a hash of this temp folder and if it don't match it regenerate this folder.

**Environment**
Windows 10 - 1809
dotnet core 3.1

**Comment by swaroop-sridhar** [comment]
Thanks for reporting this @yehia2amer.
A fix for this problem is approved for .net core 3.1 servicing: https://github.com/dotnet/core-setup/pull/9013. It is expected to be in the May release.

**Comment by swaroop-sridhar** [comment]
Dup of https://github.com/dotnet/runtime/issues/3778
