### ISSUE TITLE
Setting up  CoreFX on Ubuntu 18.04 for 32 bit 

### ISSUE THREAD

**Issue by sumitdua** [dotnet/runtime#34066]
hi guys , I am trying to build the dotnet core for Ubuntu18.04 -x86 .I am able to build coreclr .But while building the corefx 3.1 version .I am getting errors. System.Threading.Tasks.Dataflow -> /home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/artifacts/bin/System.Threading.Tasks.Dataflow/netstandard-Release/System.Threading.Tasks.Dataflow.dll
Microsoft.Win32.Primitives -> /home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/artifacts/bin/Microsoft.Win32.Primitives/netcoreapp-Unix-Release/Microsoft.Win32.Primitives.dll
Microsoft.Win32.Registry -> /home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/artifacts/bin/Microsoft.Win32.Registry/netcoreapp-Unix-Release/Microsoft.Win32.Registry.dll
Restore completed in 32.84 ms for /home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/external/runtime/runtime.depproj.
runtime.depproj: No assets were resolved from NuGet packages.
/home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/eng/referenceFromRuntime.targets(73,5): error : Could not resolve ReferenceFromRuntime item(s) 'System.Private.CoreLib' from '/home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/external/runtime/runtime.depproj'. [/home/dotnetvb/Downloads/dotnetcore-build-x86-Linux-master/corefx/src/System.AppContext/src/System.AppContext.csproj]
Can someone please help me on this issue? I am using below command to build corefx sudo ./build.sh --arch x86 --configuration Release

**Comment by danmosemsft** [comment]
Is x64 an option for you?

**Comment by sumitdua** [comment]
No, As hardware supports 32 bit only.

**Comment by ericstj** [comment]
The build isn't resolving the CoreCLR runtime that you built.  You would need to make sure that the corefx build is using your CoreCLR output as the source for CoreLib.  If you don't want to use the packages, there is a hook you can use to just resolve from the path you built: https://github.com/dotnet/corefx/blob/release/3.1/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits

**Comment by ViktorHofer** [comment]
Triage: we don't believe this is an issue anymore since we changed how CoreLib is referenced during the build. If you still facing trouble, please open a new issue with a repro. Thanks.
