### ISSUE TITLE
Add nopgooptimization build flag for coreclr

### ISSUE THREAD

**Issue by dseefeld** [dotnet/runtime#34069]
The root build script when building coreclr should have the option for nopgooptimize.  This option is being used when building from source, but can no longer be specified.

/cc: @jkoritzinsky

**Comment by jashook** [comment]
@dseefeld is this referring the `runtime/build.sh/cmd`? These options are still available in `src/coreclr/build-runtime.cmd/sh`. If we want to expose them in the root build script I suggest a more generic approach which would be adding something like `--coreclrExtraArguments`. /cc @dotnet/runtime-infrastructure

**Comment by dseefeld** [comment]
> is this referring the `runtime/build.sh/cmd`?

Yes.  This is from the root build script.  

> If we want to expose them in the root build script I suggest a more generic approach which would be adding something like `--coreclrExtraArguments`.

I think this would work.  I'm looking for an option to use from source-build.

**Comment by safern** [comment]
> If we want to expose them in the root build script I suggest a more generic approach which would be adding something like --coreclrExtraArguments.

The approach that we use in root build scripts is passing it down as MSBuild properties. So if `NoPgoOptimization` is set to true in MSBuild, then when calling down to `build-runtime` we can add the args here:
https://github.com/dotnet/runtime/blob/b5d044dcbac94790809a1b69a5f161c639c7dc11/src/coreclr/runtime.proj#L6-L18

We process these automatically in the build.ps1 script as Powershell lets us do it: 
https://github.com/dotnet/runtime/blob/b5d044dcbac94790809a1b69a5f161c639c7dc11/eng/build.ps1#L155

For `build.sh` we need to add the argument processing, i.e: 
https://github.com/dotnet/runtime/blob/b5d044dcbac94790809a1b69a5f161c639c7dc11/eng/build.sh#L149-L152

**Comment by noahfalk** [comment]
I've been looking into this. Wanted to share what I have so far and get some feedback on a few questions...

### Design
On the command-line you can do:
````
runtime_repo_root> build.cmd -subset clr -c Release /p:NoPgoOptimize=true
````
And this will eventually cause src\coreclr\src\build-runtime.cmd/sh to be invoked with the -nopgooptimize argument. I want to confirm this is the desired behavior?

### Questions
1. The current runtime.proj automatically adds -enforcepgo argument to build-runtime.cmd when any windows x86/x64 release build occurs. Do we want the NoPgoOptimize property to remove the -enforcepgo argument?
2. There is a separate src\coreclr\src\tools\dotnet-pgo\dotnet-pgo.csproj project. Should the NoPgoOptimize parameter have some impact on this project as well?
3. Aside from using the build log to confirm that -nopgooptimize was passed to build-runtime.cmd, is there any other verification I should do to ensure the new behavior is working as desired?

I still need to handle the Linux case, working on that now...

**Comment by jkoritzinsky** [comment]
I'll answer the questions:

1. I'm pretty sure you have to remove the enforcepgo argument or the build will fail.
2. I believe dotnet-pgo is something to do with @davidwrighton's work for an IBC replacement.
3. I think validating that it is passed to the build is all you need. (Having the enforcepgo script fail is another good indicator of it working)

**Comment by noahfalk** [comment]
> I'm pretty sure you have to remove the enforcepgo argument or the build will fail.

That is what I would have expected, but it succeeds regardless:
````
>build-runtime.cmd x64 release -nopgooptimize -enforcepgo
...
F:\GitHub\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\coreclr.dll: NOT compiled with PGO (LTCG)
F:\GitHub\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release\clrjit.dll: NOT compiled with PGO (LTCG)
ERROR: The files listed above must be compiled with PGO
BUILD: Build succeeded.  Finished at 18:24:24.04
BUILD: Product binaries are available at F:\GitHub\runtime\src\coreclr\..\..\artifacts\bin\coreclr\Windows_NT.x64.Release
````

**Comment by jkoritzinsky** [comment]
Well thats a bug in the handling of the enforcepgo script. I'll file a bug for that. In the mean time, it looks like your proposed change is working.
