### ISSUE TITLE
Microsoft.Extensions.FileProviders.Abstractions failing on  packaging-Windows.10.Amd64.Server19H1.Open possibly due to some python script issue

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#34087]
See https://helix.dot.net/api/2019-06-17/jobs/aff9e87d-45df-425f-9632-c1beb56f934a/workitems/Microsoft.Extensions.FileProviders.Abstractions/console from unrelated PR: https://github.com/dotnet/runtime/pull/32587

```text
C:\h\w\BBBE09EA\w\BE050A20\e>C:\Users\runner\.azdo-env\Scripts\python.exe -c "import azure.devops"   || C:\Users\runner\.azdo-env\Scripts\python.exe -m pip install azure-devops==5.0.0b9 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'azure'
...
```

```text
...
C:\h\w\BBBE09EA\w\BE050A20\e>C:\Users\runner\.azdo-env\Scripts\python.exe -c "import future"   || C:\Users\runner\.azdo-env\Scripts\python.exe -m pip install future==0.17.1 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'future'
```

Failing on the `Libraries Build Windows_NT allConfigurations x64 Debug` CI leg
https://dev.azure.com/dnceng/public/_build/results?buildId=573075&view=logs&j=423ae147-26a3-5a4d-a4d3-4b3fc1dd598e&t=22b271c0-bf2a-51c0-ee9c-4349f9238990

`packaging-Windows.10.Amd64.Server19H1.Open`
https://dev.azure.com/dnceng/public/_build/results?buildId=573075&view=ms.vss-test-web.build-test-results-tab&runId=17970228&paneView=debug

I don't know if the logs are incomplete or if there was an intermittent helix issue.

cc @maryamariyan

**Comment by maryamariyan** [comment]
This seems like a packaging build failure, having seen it reproduced. We can reopen if it gets hit again.
