### ISSUE TITLE
Framework-dependent app appears to not be compatible with 32-bit OS

### ISSUE THREAD

**Issue by Tyrrrz** [dotnet/runtime#34083]
Hi there. Sorry if this issue is potentially misplaced.

Users of my WPF .NET Core 3.1 application report that they can't run it on 32-bit version of Windows. The app is framework-dependent and they have installed .NET Core 3.1 runtime for 32-bit systems.

![image](https://user-images.githubusercontent.com/1935960/77576627-2e7d9a80-6ede-11ea-899e-97b17f4c941f.png)

I'm not even sure where to begin looking into this. What could potentially cause this error? I'd assume that a framework-dependent assembly should be able to run regardless of OS bitness, as long as correct runtime is installed.

Original issue: https://github.com/Tyrrrz/DiscordChatExporter/issues/243

Project file:

https://github.com/Tyrrrz/DiscordChatExporter/blob/9f4277ae848fc97907b3aaa7cf8b843af267c898/DiscordChatExporter.Gui/DiscordChatExporter.Gui.csproj#L1-L38

The app is published with this command:

https://github.com/Tyrrrz/DiscordChatExporter/blob/9f4277ae848fc97907b3aaa7cf8b843af267c898/.github/workflows/CD.yml#L24-L25

**Comment by jkotas** [comment]
> What could potentially cause this error?

.NET Core does not have integration with Windows OS like .NET Framework. The .exe that is published as part of the app is regular OS-specific native .exe. It matches the OS of the dotnet SDK that you are publishing on by default.

You can publish your app for x86 (e.g. `-r win-x86`) and then it is going to run as 32-bit app and it will work on both 32-bit and 64-bit Windows.

**Comment by Tyrrrz** [comment]
Thanks a lot @jkotas, I will use that.

I didn't know that published apps are OS-specific even if runtime identifier is not specified. I'm guessing `AnyCPU` or something doesn't exist for .NET Core?

**Comment by Tyrrrz** [comment]
@jkotas it appears that `-r win-x86` produces a full self-contained distribution. Is there any way to publish an app as 32-bit while still remaining framework-dependent? My users will have the runtime installed.

**Comment by jkotas** [comment]
>  I'm guessing AnyCPU or something doesn't exist for .NET Core?

You can publish the app without the .exe, and launch it using `dotnet app.dll`. It will give you equivalent of AnyCPU from .NET Framework. Of course, platform-specific `dotnet` has to be present on the machine for this to work.

> is there any way to publish an app as 32-bit while still remaining framework-dependent? 

`--self-contained false`

These options are documented at https://docs.microsoft.com/en-us/dotnet/core/deploying/

**Comment by Tyrrrz** [comment]
That did the trick, thank you. Didn't know about the link, couldn't find it myself when searching. With the help provided here, my issue is now resolved. ❤️
