### ISSUE TITLE
App crashes now crash differently

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#34093]
Apps when they throw from main now terminate in ucrtbase.dll instead of kernelbase.dll.
The problem is that the urctbase exception can't be handled by `__try {} __except(...){}` when manually invoking `hostfxr_run_app` in native code. Which causes problems with InProcess IIS now crashing instead of handling the app failure.

We've narrowed the change to https://github.com/dotnet/runtime/compare/97d1f9698cfa20054a2909ad2e4e9c4ee20a7520..b0351370ccd132d95c97b75312fc36adaacc2664

And the most likely commit to affect anything relevant is dotnet/runtime@b035137

Simple repro with newer hostpolicy.dll vs old hostpolicy.dll:

* `dotnet new console`
* `throw new Exception();` in Main
* Observe event viewer showing fault in ucrtbase instead of kernelbase

Before:
```
Faulting application name: tmp.exe, version: 1.0.0.0, time stamp: 0x5e71cf46
Faulting module name: KERNELBASE.dll, version: 10.0.18362.719, time stamp: 0xb31987d3
Exception code: 0xe0434352
```

After:
```
Faulting application name: tmp.exe, version: 1.0.0.0, time stamp: 0xdb637d68
Faulting module name: ucrtbase.dll, version: 10.0.18362.387, time stamp: 0x4361b720
Exception code: 0xc0000409
```

**Comment by Pilchie** [comment]
@jeffschwMSFT - can you help get this triaged?  We're going to have to skip a bunch of tests do to this change for now.

**Comment by jeffschwMSFT** [comment]
@vitek-karas @elinor-fung @jkoritzinsky

**Comment by elinor-fung** [comment]
It looks like this is from `/EHsc` no longer being specified for the host projects - it used to be in the deleted [settings.cmake](https://github.com/dotnet/runtime/commit/b035137#diff-ffcfc895c580dfc4e2784a3b9f77c41a). (I had thought that was one of the default flags that cmake uses for MSVC, but I guess not.)

**Comment by elinor-fung** [comment]
Oh, I see. `configurecompiler.cmake` (which the host projects were switched to using) explicitly [specifies](https://github.com/dotnet/runtime/blob/master/eng/native/configurecompiler.cmake#L425) `/EHa`.

**Comment by BrennanConroy** [comment]
So does that mean someone is going to fix this?

**Comment by elinor-fung** [comment]
Yes.
