### ISSUE TITLE
Breakpoint changes the test output on MSTest

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/runtime#34109]
This seems very similar to #12875. The output of a test suite is affected if you add a breakpoint on a specified line.

**Repro steps:**
```csharp
[TestMethod]
public void TestMethod1()
{
    const double value = 0.84551240822557006;
    Assert.AreEqual(value, value); // breakpoint here
}
```
Code from: https://developercommunity.visualstudio.com/content/problem/933087/floating-point-precision-issues-when-stepping-in-t.html

1. Add a breakpoint at specified line;
2. Target .NET Core 3.0 or 3.1;
3. Start debugging;
4. Hit breakpoint and continue execution.

**Expected output**
Test succeeds.

**Actual output**
`Assert.AreEqual failed. Expected:<0.8455124082255452>. Actual:<0.8455124082255701>. `

**Remarks**
- The issue does not reproduce on .NET Core 2.2 or earlier versions.

**Comment by tommcdon** [comment]
@sdmaclea

**Comment by hoyosjs** [comment]
@sdmaclea 

Confirmed the behavior, but 3.1 doesn't contain the fix for the issue. Couldn't get to run the test on 5.0 under the debugger (VSCode or VS). I'll try again after I restart the machine.

**Comment by sdmaclea** [comment]
This is #12875.  It has not yet been backported to 3.x, because we were lacking direct feedback from customers.  I will open the PR to backport to 3.1.

**Comment by hoyosjs** [comment]
Confirmed 5.0 solves this scenario.

**Comment by hoyosjs** [comment]
This has been ported to 3.1 and 5.0;
