### ISSUE TITLE
build.cmd contains dead documentation link

### ISSUE THREAD

**Issue by michha** [dotnet/runtime#34116]
Link _https://github.com/dotnet/runtime/tree/master/docs/installer/building/windows-instructions.md_ doesnt exist anymore.

I could not figure out where the referenced file went, otherwise I would have made a pull request.

https://github.com/dotnet/runtime/blob/c6d463c7eac1d03a77a16276d7eb3ae2646612a3/src/installer/corehost/build.cmd#L69

**Comment by AaronRobinsonMSFT** [comment]
Looks like this file was removed with a71a3249a95be90d7ff7a03d9cf311e8f0d75188.

@ViktorHofer was the above file replaced by some other documentation or was it accidentally removed and not relocated?

**Comment by danmosemsft** [comment]
@dagood are there instructions for building installer? If the instructions are just 'build.cmd/sh' then we can delete this line.

**Comment by dagood** [comment]
The file describes some prereqs and a build command with `/p:Subset=CoreHost`.

(Archive link for easy access: https://github.com/dotnet/core-setup/blob/master-archive/Documentation/building/windows-instructions.md.)

I'd say it's up to the area-Host folks where this link should point now, or if it should be removed. It's part of the host build script. area-Infra-installer has triage today, so if there's consensus on that, I think the issue will more to area-Host.
