### ISSUE TITLE
Proposal: interface to look up keys, but not enumerate, as base interface of IReadOnlyDictionary

### ISSUE THREAD

**Issue by epa** [dotnet/runtime#34118]
I suggest making a new interface `IReadOnlyKeyLookup<TKey,TValue>` which extracts out some of the methods currently provided by `IReadOnlyDictionary<TKey,TValue>`:

- `Item[TKey]`
- `ContainsKey(TKey)`
- `TryGetValue(TKey, TValue)`

In other words an interface to look up particular keys, but not to list all keys.  Then `IReadOnlyDictionary<TKey,TValue>` would inherit from `IReadOnlyKeyLookup<TKey,TValue>`.

Sometimes you want to expose a key-value lookup to client code but you'd like to satisfy yourself that nothing depends on the exact count of things in the lookup.  The client code can look up particular keys but not enumerate over all of them.  That way, you can be reasonably sure that adding new keys to the lookup won't affect any existing code.  (Not 100% sure since callers could always try looking up random keys and catching errors, but close enough.)

Also, by providing the more restrictive interface you have more freedom to change the implementation.  The lookup can be implemented by a function that takes a `TKey` and returns a `TValue`.  Or it could be implemented by a dictionary, or even an array if `TKey` is `int`.  You don't have to expose the implementation, and you don't have to worry about providing an enumeration of all possible keys (all possible input values to the function).

**Comment by Wraith2** [comment]
Is this nor covered by [`ILookup<TKey,TElement>`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.ilookup-2?view=netcore-3.1)?

**Comment by epa** [comment]
Thanks for pointing out `ILookup<TKey,TElement>` but that does contain `Count` and `GetEnumerator` while I am thinking of a more restrictive interface that only lets you look up by key, but not list all keys.

**Comment by Wraith2** [comment]
This sounds like a very restricted use case that can be handled through encapsulation. Adding new interfaces to the BCL collections and to dictionary specifically are high maintenance and high risk actions.

**Comment by stephentoub** [comment]
> Then IReadOnlyDictionary<TKey,TValue> would inherit from IReadOnlyKeyLookup<TKey,TValue>

Note that such a change is breaking.

**Comment by epa** [comment]
Thanks, I hadn't realized that adding a new base interface was a breaking change.

**Comment by eiriktsarpalis** [comment]
It seems like this issue can probably be closed.
