### ISSUE TITLE
API Proposal: Stream.ReadBlock / Stream.ReadBlockAsync

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#34129]
I use the following 2 methods more than I use the normal `Read`/`ReadAsync` methods (I have them implemented as extension methods) so I think it would be rather useful to have them in the runtime:

```c#
public abstract class Stream
{
    /// <summary>
    /// Reads until all the requested bytes have been loaded into the buffer.
    /// </summary>
    public int ReadBlock(Span<byte> buffer)
    {
        int totalBytes = 0;

        while (buffer.Length > 0) {
            int bytesRead = Read(buffer);

            if (bytesRead == 0)
                break;

            totalBytes += bytesRead;
            buffer = buffer.Slice(bytesRead);
        }

        return totalBytes;
    }

    /// <summary>
    /// Reads until all the requested bytes have been loaded into the buffer.
    /// </summary>
    public async ValueTask<int> ReadBlockAsync(Memory<byte> buffer)
    {
        int totalBytes = 0;

        while (buffer.Length > 0) {
            int bytesRead = await ReadAsync(buffer);

            if (bytesRead == 0)
                break;

            totalBytes += bytesRead;
            buffer = buffer.Slice(bytesRead);
        }

        return totalBytes;
    }
}
```

Thanks @jnm2 for suggesting the method names as they are analogous in behavior to `TextReader.ReadBlock` and `TextReader.ReadBlockAsync`.

**Comment by jnm2** [comment]
Should they potentially be virtual and/or ValueTask?

Nice proposal. It would keep me from having to carry around extension methods like this.

**Comment by mikernet** [comment]
Definitely yes to `ValueTask` - updated accordingly. Not sure if there is value in making them virtual. Is there a particular situation you can see that would benefit from being able to override them?

**Comment by jnm2** [comment]
No, I don't have a use case for specializing the implementations.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/16598 (albeit with span/memory-based overloads)

**Comment by stephentoub** [comment]
Closing as dup. Thanks.
