### ISSUE TITLE
Caching.Memory tests are impacting CI reliability

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#34128]
Several tests in this group are failing. Looks like some inherent flakiness here that needs to be addressed:

- `Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.GetAndSet_AreThreadSafe_AndUpdatesNeverLeavesNullValues`
- `Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.GetAndSet_AreThreadSafe_AndUpdatesNeverLeavesNullValues`
- `Microsoft.Extensions.Caching.Memory.CapacityTests.ExpiringEntryDecreasesCacheSize`

### Console Log Summary
```
Assert.False() Failure\nExpected: False\nActual: True

Stack trace
   at Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.GetAndSet_AreThreadSafe_AndUpdatesNeverLeavesNullValues() in /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/MemoryCacheSetAndRemoveTests.cs:line 489
```

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#573475](https://dev.azure.com/dnceng/public/_build/results?buildId=573475)|#33984|1|
|[#574007](https://dev.azure.com/dnceng/public/_build/results?buildId=574007)|#34107|1|
|[#574039](https://dev.azure.com/dnceng/public/_build/results?buildId=574039)|Rolling|1|
|[#574145](https://dev.azure.com/dnceng/public/_build/results?buildId=574145)|#34113|1|
|[#574187](https://dev.azure.com/dnceng/public/_build/results?buildId=574187)|Rolling|2|
|[#574195](https://dev.azure.com/dnceng/public/_build/results?buildId=574195)|#32592|3|
|[#574272](https://dev.azure.com/dnceng/public/_build/results?buildId=574272)|#32107|1|
|[#574310](https://dev.azure.com/dnceng/public/_build/results?buildId=574310)|Rolling|3|
|[#574321](https://dev.azure.com/dnceng/public/_build/results?buildId=574321)|#32592|1|
|[#574382](https://dev.azure.com/dnceng/public/_build/results?buildId=574382)|#34061|1|
### Configurations
- netcoreapp5.0-Linux-Debug-x64-CoreCLR_release-Debian.9.Amd64.Open
- netcoreapp5.0-Linux-Debug-x64-Mono_release-SLES.15.Amd64.Open
- netcoreapp5.0-Linux-Release-arm64-CoreCLR_release-(Alpine.38.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-a45aeeb-20190620184035
- netcoreapp5.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-bfcd90a-20200127194925
- netcoreapp5.0-Linux-Release-x64-CoreCLR_release-Debian.9.Amd64.Open
- netcoreapp5.0-Windows_NT-Debug-x64-Mono_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
- netcoreapp5.0-Windows_NT-Debug-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|
| --- | --- | --- | --- | --- |
|[#573475](https://dev.azure.com/dnceng/public/_build/results?buildId=573475)|#33984|[console.d2783e41.log](https://helix.dot.net/api/2019-06-17/jobs/f57311d9-194b-4e00-a790-240bb4943d18/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.d2783e41.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/f57311d9-194b-4e00-a790-240bb4943d18/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574007](https://dev.azure.com/dnceng/public/_build/results?buildId=574007)|#34107|[console.dfed949a.log](https://helix.dot.net/api/2019-06-17/jobs/9c487095-e039-4b94-be4f-79ea1542aac6/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.dfed949a.log)|||
|[#574039](https://dev.azure.com/dnceng/public/_build/results?buildId=574039)|Rolling|[console.5888d78a.log](https://helix.dot.net/api/2019-06-17/jobs/a17c3f0b-8f8f-403f-82a3-7aee0176491a/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.5888d78a.log)|||
|[#574145](https://dev.azure.com/dnceng/public/_build/results?buildId=574145)|#34113|[console.ed98370f.log](https://helix.dot.net/api/2019-06-17/jobs/69862130-a475-4556-96d7-896801bfcfec/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.ed98370f.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/69862130-a475-4556-96d7-896801bfcfec/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574187](https://dev.azure.com/dnceng/public/_build/results?buildId=574187)|Rolling|[console.18e09cc6.log](https://helix.dot.net/api/2019-06-17/jobs/d0219916-41f9-46d4-96ef-63bb638b8ed8/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.18e09cc6.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/d0219916-41f9-46d4-96ef-63bb638b8ed8/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574187](https://dev.azure.com/dnceng/public/_build/results?buildId=574187)|Rolling|[console.c15c1d96.log](https://helix.dot.net/api/2019-06-17/jobs/69d4161a-bd62-431a-8fa3-dadca8654886/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.c15c1d96.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/69d4161a-bd62-431a-8fa3-dadca8654886/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574195](https://dev.azure.com/dnceng/public/_build/results?buildId=574195)|#32592|[console.8de44599.log](https://helix.dot.net/api/2019-06-17/jobs/fd8df08a-817c-412a-ae02-aaa8187c54d4/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.8de44599.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/fd8df08a-817c-412a-ae02-aaa8187c54d4/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574195](https://dev.azure.com/dnceng/public/_build/results?buildId=574195)|#32592|[console.6bef8943.log](https://helix.dot.net/api/2019-06-17/jobs/394f9f6d-5a3c-4ce0-ad86-6a15a38b15f1/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.6bef8943.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/394f9f6d-5a3c-4ce0-ad86-6a15a38b15f1/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574195](https://dev.azure.com/dnceng/public/_build/results?buildId=574195)|#32592|[console.b749e716.log](https://helix.dot.net/api/2019-06-17/jobs/6b1d8f4f-e770-42bd-ae72-83bcffd20d7c/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.b749e716.log)|||
|[#574272](https://dev.azure.com/dnceng/public/_build/results?buildId=574272)|#32107|[console.ad9f0b28.log](https://helix.dot.net/api/2019-06-17/jobs/f2acd41c-6ac4-4e26-a3f8-615d2ed29de8/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.ad9f0b28.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/f2acd41c-6ac4-4e26-a3f8-615d2ed29de8/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574310](https://dev.azure.com/dnceng/public/_build/results?buildId=574310)|Rolling|[console.d7ef0d51.log](https://helix.dot.net/api/2019-06-17/jobs/a99c1ae5-cf01-4b6e-beb1-242d873d9db0/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.d7ef0d51.log)|||
|[#574310](https://dev.azure.com/dnceng/public/_build/results?buildId=574310)|Rolling|[console.b7698877.log](https://helix.dot.net/api/2019-06-17/jobs/7df59f03-64bf-479e-a50e-680591bfadde/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.b7698877.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/7df59f03-64bf-479e-a50e-680591bfadde/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/testResults.xml)|
|[#574310](https://dev.azure.com/dnceng/public/_build/results?buildId=574310)|Rolling|[console.685207a6.log](https://helix.dot.net/api/2019-06-17/jobs/e281d7bb-f81f-45cb-bb56-eae91da6d60b/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.685207a6.log)|||
|[#574321](https://dev.azure.com/dnceng/public/_build/results?buildId=574321)|#32592|[console.1b681dda.log](https://helix.dot.net/api/2019-06-17/jobs/58f93d26-f489-4fc6-8b75-800288bdef3a/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.1b681dda.log)|||
|[#574382](https://dev.azure.com/dnceng/public/_build/results?buildId=574382)|#34061|[console.a5a81439.log](https://helix.dot.net/api/2019-06-17/jobs/b0e167e9-a616-400c-928d-40a99b82d5a8/workitems/Microsoft.Extensions.Caching.Memory.Tests/files/console.a5a81439.log)|||

**Comment by ericstj** [comment]
@maryamariyan can we disable these tests and file an issue?

**Comment by maryamariyan** [comment]
I spotted one of them yesterday on the CI PR that were failing on Mono so I created this issue for it:
https://github.com/dotnet/runtime/issues/33993.

Thanks seems like it is not necessarily a Mono flakiness. I'll update that issue and push a PR

**Comment by ericstj** [comment]
Dup of #33993
