### ISSUE TITLE
XmlWrite.Close unconditionally synchronously writes on asynchronous writers

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#34130]
When invoking `Close` or `Dispose`, even if the writer has been flushed, it will try to flush the writer which will result in synchronously writing 0 bytes which will fault on asynchronous streams.

It's not just an issue of sync over async ([this](/dotnet/runtime/issues/33618) will handle it). It's also a performance issue. If the buffer is empty, there's no need to write 0 bytes.

**Comment by stephentoub** [comment]
cc: @buyaa-n

**Comment by buyaa-n** [comment]
I have added check if there is any bytes need be written with https://github.com/dotnet/runtime/pull/35233, so closing this issue
