### ISSUE TITLE
Build failing on OS X 10.15.3

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#34148]
Here are the steps I followed to try to build the runtime:
```
$ git clone https://github.com dotnet/runtime
$ cd runtime
$ ./build.sh -subsetCategory coreclr -c Checked
$ ./build.sh -subsetCategory coreclr-libraries -c Checked
```
This was the last part of the output from this step:

>   -- Detecting C compile features - done
>   CMake Error at CMakeLists.txt:133 (message):
>     Unknown build type.  Set CMAKE_BUILD_TYPE to DEBUG or RELEASE.
>   
>   
>   -- Configuring incomplete, errors occurred!
>   See also "/Users/mj/Documents/develop/runtime/artifacts/obj/native/netcoreapp5.0-OSX-Checked-x64/CMakeFiles/CMakeOutput.log".
>   Failed to generate "native libraries component" build project!
> /Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.proj(36,5): error MSB3073: The command ""/Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.sh" x64 Checked outconfig netcoreapp5.0-OSX-Checked-x64 -os OSX " exited with code 1. 
> 
> Build FAILED.
> 
> /Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.proj(36,5): error MSB3073: The command ""/Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.sh" x64 Checked outconfig netcoreapp5.0-OSX-Checked-x64 -os OSX " exited with code 1.
>     0 Warning(s)
>     1 Error(s)
> 

There are 1500 instances of the file CMakeLists.txt.  Which one to check?

Next, I tried this:

```
$  export CMAKE_BUILD_TYPE=DEBUG
$ ./build.sh -subsetCategory coreclr-libraries -c Checked
```

This ended with a similar failure:

>   Invoking "/Users/mj/Documents/develop/runtime/eng/native/gen-buildsys.sh" "/Users/mj/Documents/develop/runtime/src/libraries/Native/Unix" "/Users/mj/Documents/develop/runtime/src/libraries/Native/Unix" "/Users/mj/Documents/develop/runtime/artifacts/obj/native/netcoreapp5.0-OSX-Checked-x64" x64 clang "" "" Checked ""  -DCLR_ENG_NATIVE_DIR="/Users/mj/Documents/develop/runtime/eng/native" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_STATIC_LIB_LINK=0 -DFEATURE_DISTRO_AGNOSTIC_SSL=1 
>   CMake Error at CMakeLists.txt:133 (message):
>     Unknown build type.  Set CMAKE_BUILD_TYPE to DEBUG or RELEASE.
>   
>   -- Configuring incomplete, errors occurred!
>   See also "/Users/mj/Documents/develop/runtime/artifacts/obj/native/netcoreapp5.0-OSX-Checked-x64/CMakeFiles/CMakeOutput.log".
>   Failed to generate "native libraries component" build project!
>   
> /Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.proj(36,5): error MSB3073: The command ""/Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.sh" x64 Checked outconfig netcoreapp5.0-OSX-Checked-x64 -os OSX " exited with code 1.
> 
> Build FAILED.
> 
> /Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.proj(36,5): error MSB3073: The command ""/Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.sh" x64 Checked outconfig netcoreapp5.0-OSX-Checked-x64 -os OSX " exited with code 1.
>     0 Warning(s)
>     1 Error(s)
> 

My CMake version is 3.17.0 (installed today from brew).

**Comment by mrj001** [comment]
As I've updated my OS X to 10.15.4, and the build.sh parameters have been updated, I decided to recheck this.
The new build command lines I used:
```
$xxx
$ ./build.sh -subset Libs+Libs.Tests -runtimeConfiguration Checked
```

The first succeeds.  The second fails.  Scrolling (way) back through the output, the first problem I found was:

>   -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
>   CMake Error at System.Security.Cryptography.Native/CMakeLists.txt:17 (message):
>     !!! Cannot find libssl and System.Security.Cryptography.Native cannot build
>     without it.  Try installing libssl-dev (or the appropriate package for your
>     platform) !!!.  See the requirements document for your specific operating
>     system:
>     https://github.com/dotnet/runtime/tree/master/docs/workflow/requirements.
>   
>   
>   -- Configuring incomplete, errors occurred!
>   See also "/Users/mj/Documents/develop/runtime/artifacts/obj/native/netcoreapp5.0-OSX-Debug-x64/CMakeFiles/CMakeOutput.log".
>   See also "/Users/mj/Documents/develop/runtime/artifacts/obj/native/netcoreapp5.0-OSX-Debug-x64/CMakeFiles/CMakeError.log".
>   Failed to generate "native libraries component" build project!
> /Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.proj(36,5): error MSB3073: The command ""/Users/mj/Documents/develop/runtime/src/libraries/Native/build-native.sh" x64 Debug outconfig netcoreapp5.0-OSX-Debug-x64 -os OSX " exited with code 1.
> 

Issue 1: Since configuring failed, why did the build appear to proceed?  Isn't it known that this will eventually fail?

Issue 2: file: ```docs/workflow/building/coreclr/osx-instructions.md``` does not mention that openssl is required.  This file also indicates it was validated on 10.12, which is three revisions ago.  File ```docs/workflow/requirements/macos-requirements.md``` does indicate that OpenSsl is required.  So these two files are out of sync.

Question: How does .NET avoid a runtime dependency on the presence of OpenSSL, which is not present by default on OSX?

**Comment by wfurt** [comment]
I think #1 is caused by parallelism in the build. When something fails, it is not east to stop everything at once. 

to answer #2: coreclr does not requite openssl. But libraries and runtime repo  does. OpenSSL is loaded via shim  and dlopen. But we need headers to build the shim.

I'm building on 10.15.3 without any problems so you most likely have problem with prerequisites. 
When you add missing stuff, rebuild does not usually work. `git -dfx` or `rm -rf artifacs` is usually needed.

**Comment by ViktorHofer** [comment]
Closing as we haven't heard back. @mrj001 feel free to reopen.
