### ISSUE TITLE
Use hosted AzDO pools for CI

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3416]
Hosted pool agents are recycled, which would make the build significantly more reliable because builds wouldn't accumulate or affect each other.

There are reasons to use the persistent agents in some cases (needed to sign, VS version issues, hosted agents don't have a lot of disk space) but I want to at least track the reasons we can't use hosted pools in the legs we don't.

---

* Public CI win arm/arm64 uses dotnet-external-temp because Hosted VS2017 is missing dependencies (as of writing). https://github.com/dotnet/core-setup/issues/5052

**Comment by NikolaMilosavljevic** [comment]
We're not aware of any related issues in dotnet/runtime repo - closing.
