### ISSUE TITLE
Assertion failed 'offsetFitsInVectorMem(emitGetInsSC(id))'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#34170]
Windows arm32 with:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=1
```

From attempt to re-enable "runtime-coreclr jitstress" testing:
https://dev.azure.com/dnceng/public/_build/results?buildId=574937&view=results

```
    JIT\Methodical\explicit\coverage\expl_float_1_d\expl_float_1_d.cmd [FAIL]
      
      Assert failure(PID 7700 [0x00001e14], Thread: 10360 [0x2878]): Assertion failed 'offsetFitsInVectorMem(emitGetInsSC(id))' in 'TestApp:Main():int' during 'Generate code' (IL size 4230)
      
          File: F:\workspace\_work\1\s\src\coreclr\src\jit\emitarm.cpp Line: 465
          Image: D:\h\w\B77C09AB\p\CoreRun.exe
```

Tests:
```
JIT\Methodical\explicit\coverage\expl_float_1_d\expl_float_1_d.cmd
JIT\Methodical\explicit\coverage\expl_float_1_r\expl_float_1_r.cmd
```

category:correctness
theme:alignment
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Repros without JitStress, and with altjit, when generating:
```
                                                               /--*  t1970  float
Generating: N023 (  5,  8) [001972] UA-----------             *  STORE_LCL_FLD float  V53 tmp1         ud:3->0[+47] Fseq[tmp2] NA REG NA
```

This is a test of struct explicit layout
```
[StructLayout(LayoutKind.Explicit)]
internal struct AA
{
    [FieldOffset(3)]
    public byte tmp1;

    [FieldOffset(8)]
    public float q;

    [FieldOffset(47)]
    public float tmp2;

    public AA(float qq)
    {
        tmp1 = 0;
        tmp2 = 0;
        q = qq;
    }
```

and we're trying to generate `vstr s8, [fp-117]`, but assert that vstr offsets must be 4-byte aligned.

Note that when repro'ing with altjit, first you get:
```
NO_WAY("JIT must expand the intrinsic!");
```
in `System.Runtime.Intrinsics.X86.Sse41:get_IsSupported():bool` before getting to the failure in `TestApp:Main():int`

**Comment by BruceForstall** [comment]
@sandreenko Might any of your recent struct work have affected this?

**Comment by sandreenko** [comment]
I will check.

**Comment by jashook** [comment]
This does not seem to need jit stress

**Comment by BruceForstall** [comment]
My guess is this is due to `MorphLocalIndir` introduced in https://github.com/dotnet/runtime/pull/991. For arm32, if a field is a float/double at a not-aligned address, we should leave it to be processed by fgMorphField which will treat it as an IND, and the arm32 codegen knows how to deal with unaligned IND (see `emitInsLoadStoreOp`). Or, perhaps we need to teach the emitter about unaligned floating point field loads/stores using similar logic to `emitInsLoadStoreOp`.

**Comment by BruceForstall** [comment]
As @jashook pointed out in https://github.com/dotnet/runtime/issues/34178, we should understand why this didn't fail in Linux arm runs. Was the test run there?

**Comment by BruceForstall** [comment]
Looks like this is also failing in the rolling "runtime-coreclr outerloop" Windows arm test run job, starting after Windows arm testing was re-enabled with https://github.com/dotnet/runtime/pull/32819

e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=567481&view=logs&j=08fa9cb9-5528-5234-de15-5bfafb946da9&t=8fff87e1-0d46-5658-1051-6234077c6b03

**Comment by BruceForstall** [comment]
@sandreenko Since this failure is affecting the regular outerloop job, I'm inclined to immediately disable the failing test for Windows arm32, since I don't think we have an easy fix here.

**Comment by jashook** [comment]
Have a pr out to do that

**Comment by jashook** [comment]
https://github.com/dotnet/runtime/pull/34179

**Comment by sandreenko** [comment]
We do not run this test outside Windows:
https://github.com/dotnet/runtime/blob/14a2f7897c744357566e678e59b3e725b50e5a52/src/coreclr/tests/src/JIT/Methodical/explicit/coverage/expl_float_1_r.csproj#L7

Note: We have ~300 tests with that condition, probably we should check them and see if it is still applicable.

**Comment by BruceForstall** [comment]
I agree that we should double-check those tests. It's not helpful that there is no comment as to _why_ it is unsupported.

**Comment by sandreenko** [comment]
Opened https://github.com/dotnet/runtime/issues/34233

**Comment by jashook** [comment]
For a long time we did not support explicit layout on unix

**Comment by BruceForstall** [comment]
Do you know why? Or if that's still true?

**Comment by BruceForstall** [comment]
I opened https://github.com/dotnet/runtime/pull/34250 to re-enable the explicit layout tests. Some are failing on Linux arm due to unaligned access. On Windows, unaligned accesses are fixed up by the OS.

**Comment by sandreenko** [comment]
I don't have a solution yet, because it appeared that for code like
```
[StructLayout(LayoutKind.Explicit)]
internal struct AA {
    [FieldOffset(47)]
    public float tmp2;
    public AA() {
      tmp2 = 0;
    }
```
IL doesn't have `CEE_UNALIGNED` prefix, so we can't catch `GTF_IND_UNALIGNED` because it is not yet set, it will be set later here:
https://github.com/dotnet/runtime/blob/38bef8c60e9483eeb16d85850ad6109c4bc47f5d/src/coreclr/src/jit/morph.cpp#L13075-L13086

@BruceForstall @jashook do you know if IL should have [the unaligned prefix](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.unaligned?view=netframework-4.8) in this case or not?

It doesn't affect ARM64, because there we need both unaligned and volatile to change instruction and all volatile operations are not transformed by lclmorph.

It is possible to teach `genCodeForStoreLclFld` to work with unaligned fields, but not clear which phase should set this flag on the node.

**Comment by sandreenko** [comment]
@dotnet/jit-contrib the previous comment is the question that I mention at the meeting.
