### ISSUE TITLE
IntPtr should implement IFormattable

### ISSUE THREAD

**Issue by hex64dbg** [dotnet/runtime#34194]
Consider this program :

```
var ptr = new IntPtr(0xff);
Console.WriteLine($"0x{ptr.ToString("x")}"); // Output 0xff
```

Visual studio suggests a simplification ([recently introduced](https://docs.microsoft.com/en-us/visualstudio/ide/reference/simplify-string-interpolation?view=vs-2019))
![image](https://user-images.githubusercontent.com/3956685/77756637-dfe01580-702f-11ea-80a5-413e63d0fe07.png)
`
Console.WriteLine($"0x{ptr:x}"); // Output 0x255`

After simplification the output is not the same anymore, it's not formatted as hexadecimal.
This feature assumes that the object implements IFormattable, but IntPtr doesn't, instead it has a custom `.ToString(String format)`

I think it would be cleaner if IntPtr implements IFormattable.

**Comment by Joe4evr** [comment]
Seems to me there's a slightly deeper issue here, that the code fix is suggested for types that *don't* implement `IFormattable`. I know that code fixes are made without the guarantee that it remains semantically identical, but this looks like one of those cases where you'd never want the semantics unexpectedly changed for what looks like a really tiny fix.

**Comment by stephentoub** [comment]
I agree with @Joe4evr.  Separate from this request, we should open an issue in dotnet/roslyn to address that, if it's not already covered somewhere.

**Comment by Gnbrkm41** [comment]
Related: https://github.com/dotnet/runtime/issues/21943

**Comment by Joe4evr** [comment]
I took a quick look at what is declared on [IntPtr](https://apisof.net/catalog/System.IntPtr) and [UIntPtr](https://apisof.net/catalog/System.UIntPtr), and the latter seems to be missing `ToString(string)`. Is it desirable to add that overload for symmetry purposes?

**Comment by stephentoub** [comment]
So for {U}IntPtr, this is a dup of https://github.com/dotnet/runtime/issues/21943, and I've opened https://github.com/dotnet/roslyn/issues/42887 for the refactoring issue.  Thanks.
