### ISSUE TITLE
How to handle Runtime Pack naming when targeting > 1 VM 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#34193]
I'm moving the [question](https://github.com/dotnet/designs/pull/50#issuecomment-605038362) I had in dotnet/designs here as this might be a better place.

With the introduction of the mono vm in .net 5, there is a need to uniquely differentiate the runtime packs. To be clear, this would apply to scenarios where there are > 1 vm's being used (Xamarin.Mac targeting OSX).

To me, it would make sense to just add the vm to the name of the runtime pack. Something like Microsoft.NETCore.App.Runtime.{vm}.{rid}.{version}.nukpg.  I'm sure the vm name clash will apply to other scenarios as well.  

What's the best way to proceed?

**Comment by ericstj** [comment]
@terrajobst @mhutch @dsplaisted @ViktorHofer @jkotas 

So the name of the runtime packages is an implementation detail.  We should first think about the customer experience.

Do we want to allow independent selection of `{vm}` or is it something that is just implicit based on the TFM + RID?  If the latter, maybe we can just bring TFM into the naming convention, or have the SDK choose a different FrameworkReference based on the TFM.  We need not make all TFMs use/build on top of the Microsoft.NETCore.App shared framework.  The only place we *need* the Microsoft.NETCore.App shared framework to be represented is for apps which use hosts that actually leverage that shared framework.

**Comment by jkotas** [comment]
We have similar problem for CoreCLR single-file: The current plan for single-file CoreCLR runtime pack is to include it in the default CoreCLR runtime pack, but it is wasteful. It results into downloading 10+ MBs of stuff with the runtime pack that you do not need.

Also, we are exploring  CoreCLR+framework build optimized for containers where we want to apply different AOT policies that work better for containers. Again, it would be nice to have a option to pack it into a separate runtime pack.

I would make the name `Microsoft.NETCore.App.Runtime{.custom}.{rid}.{version}.nukpg` where `custom` can be any identifier that identifies non-default runtime for the given TFM.

User experience: 
- The workload-specific SDKs (e.g. Xamarin.Mac SDK) can override default to something else.
- The user .csproj file and the command line can override the default to something else.

**Comment by jkotas** [comment]
Also, filled https://github.com/dotnet/runtime/issues/34202 that is somewhat related to this.

**Comment by jzabroski** [comment]
@ericstj said:

> We should first think about the customer experience.

@jkotas  said:

> I would make the name Microsoft.NETCore.App.Runtime{.custom}.{rid}.{version}.nukpg where custom can be any identifier that identifies non-default runtime for the given TFM.

So, as an open source author, if I want to support users who want to use the Mono runtime, what XML am I going to stick in my .NET SDK csproj?  How will my downstream tools like xUnit.net run tests?  Or is customer experience here optimizing for the default case and letting people build complex csproj's to support complex requirements?

**Comment by terrajobst** [comment]
It's not clear to me that customers need to chose a specific runtime pack in their project file yet. As @ericstj said, I would generally expect this to be driven by the TFM. Maybe there are other factors that control that (DEBUG vs RELEASE, AOT vs JIT) but I would generally expect these to be either exposed as settings in the project file/the build and not result in the user having to pick the runtime pack.

The container scenario is an interesting one. For example, let's say we support three different policies A, B, and C. I would expect the project file to look something like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AotPolicy>A</AotPolicy>A
  </PropertyGroup>

</Project>
```

The reason is that we generally want to avoid customers having to pick the full thing with version number because it becomes hard when they upgrade to a later TFM. We learned this with ASP.NET Core where folks used weird combinations of the .NET platform with lower/higher versions of ASP.NET Core packages. That's why invented things like `FrameworkReference` which doesn't include a version in the project file.

**Comment by jzabroski** [comment]
Yes, that's what I want to hear. All set.

**Comment by dsplaisted** [comment]
Folks,

I've got a PR out which adds the mechanism we can use to allow projects to opt into Mono runtime packs.  Take a look and let me know what you think.

Once it's merged, we'll need to:

- Add `KnownRuntimePack` items to describe the available Mono runtime packs
- Add support for a user-facing property to opt into Mono runtime packs, such as `UseMonoRuntime`

**Comment by rolfbjarne** [comment]
So from what I understand what's left before the SDK can consume this, is for Mono to add `KnownRuntimePack` items to describe the available Mono runtime packs?

**Comment by dsplaisted** [comment]
> So from what I understand what's left before the SDK can consume this, is for Mono to add `KnownRuntimePack` items to describe the available Mono runtime packs?

@rolfbjarne Yes, the `KnownRuntimePack` items need to be declared somewhere.  Additionally, there needs to be a way to opt in to them.  You can do this by setting the `RuntimePackLabels` metadata on the appropriate `FrameworkReference` item, but we probably want something like a `UseMonoRuntime` property that's more user-friendly.

Also, here's an explicit link to the PR that added the capability: https://github.com/dotnet/sdk/pull/11824

**Comment by akoeplinger** [comment]
This is done now. The Mono-based runtime packs use `.Mono` in the package ID (e.g. `Microsoft.NETCore.App.Runtime.Mono.osx-x64`) and there's a `UseMonoRuntime` property you can set in the .csproj that will opt into them by using the `RuntimePackLabels` metadata.
