### ISSUE TITLE
Hoist access to volatile variables out of loop in ConcurrentDictionary

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#34198]
There are few places in [ConcurrentDictionary](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs) where we call `AcquireAllLocks` but still access the volatile variables like `_tables._countPerLock`, `_tables._buckets` and `_tables._locks` inside loop.

E.g. [CopyTo](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L642), [GetCountInternal](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1005), [CopyTo](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1674), [GetKeys](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1990) and [GetValues](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L2022). 

Is there a reason for doing it or can we cache those variables outside the loop and use it inside? Currently, for ARM64, JIT generates expensive memory barrier instructions for accessing volatile variables. With volatile variables getting accessed inside the loop, we are executing these instructions inside the loop. Caching them would optimize the performance of these APIs on ARM64. 

Below is an example of machine code we generate before/after caching the volatile variable outside loop for `GetCountInternal` method.
Before:
![before](https://user-images.githubusercontent.com/12488060/77773751-47ce3600-7007-11ea-81aa-660ff42aef70.PNG)

After: I made following change and see this generated code. This gave approx. 30% win in [Dictionary.Count](https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Collections/Concurrent/Count.cs#L37) benchmark.
```c#
private int GetCountInternal()
{
    int count = 0;
    int[] countPerLocks = _tables._countPerLock;

    // Compute the count, we allow overflow
    for (int i = 0; i < countPerLocks.Length; i++)
    {
        count += countPerLocks[i];
    }

    return count;
}
```

![after](https://user-images.githubusercontent.com/12488060/77773761-4a309000-7007-11ea-8b26-24807fd6d41f.PNG)

**Comment by kunalspathak** [comment]
// @danmosemsft , @BruceForstall

**Comment by danmosemsft** [comment]
@stephentoub

**Comment by stephentoub** [comment]
I'd need to look in more depth to be sure, but if memory serves, as long as all the locks are held, it should be fine to do the reads once (even as non-volatile).

**Comment by kunalspathak** [comment]
Thanks @stephentoub . I will send out the PR to address this. Let me know if your findings don't allow it.
