### ISSUE TITLE
Connecting a System.Threading.Tasks.Task object to a native "Fence"

### ISSUE THREAD

**Issue by sunkin351** [dotnet/runtime#34205]
Is there a method by which I can create a Task object around a native Fence synchronization primitive? And if not, can we make one?
I'm developing an application utilizing the Vulkan Graphics API and it would be advantageous if we could connect a VkFence to a Task object.

**Comment by tannergooding** [comment]
CC. @stephentoub ?

For reference a `VkFence` is an opaque handle which you operate on using `VkResetFences` and `VkWaitForFences` (among a few other APIs).
It's similar in concept to `CreateEventW` and using `WaitForSingleObject` and related APIs on Windows (or `ID3D12Fence` in DirectX land).

**Comment by stephentoub** [comment]
The TaskCompletionSource type let's you create a Task object and have manual control over its completion; this is generally what's used when wrapping a Task around an arbitrary API, managed or native.  So, for example, let's say we didn't have Task.Run and I wanted to use ThreadPool.QueueUserWorkItem to invoke a `Func<T>` and have a `Task<T>` that represented it... I'd do something along the lines of:
```C#
public static Task<T> Run(Func<T> func)
{
    var tcs = new TaskCompletionSource<T>();
    ThreadPool.QueueUserWorkItem(_ =>
    {
        try { tcs.SetResult(func()); }
        catch (Exception e) { tcs.SetException(e); }
    });
    return tcs.Task;
}
```
You should be able to use that to create a Task for these VkFence things.

**Comment by sunkin351** [comment]
That's really nice. Is there one that isn't generic too?

**Comment by stephentoub** [comment]
`Task<T>` derives from `Task`, so for non-generic we generally just use `TaskCompletionSource<bool>` with a dummy value, e.g.
```C#
public static Task Run(Action action)
{
    var tcs = new TaskCompletionSource<bool>();
    ThreadPool.QueueUserWorkItem(_ =>
    {
        try
        {
            action();
            tcs.SetResult(true);
        }
        catch (Exception e) { tcs.SetException(e); }
    });
    return tcs.Task;
}
```
There's an open issue about adding a non-generic one, just for simplicity / symmetry:
https://github.com/dotnet/runtime/issues/17393

**Comment by sunkin351** [comment]
Sweet, thanks. I'll look forward to it.

**Comment by sunkin351** [comment]
Could I get a more threadless way of waiting for these through tasks?
Just because there really isn't any "work" being done, so there's no need for it to be waited on a different thread. And I'd hate to block too many pool threads like this...

**Comment by stephentoub** [comment]
I don't understand the question. Nothing here is blocking a thread unless you yourself do that. You get to complete the task with whatever callback based mechanism you have. My QueueUserWorkIem example was just an example.

**Comment by sunkin351** [comment]
Checking a Fence within Vulkan requires that I call `VkWaitForFences()`, which can block depending on the arguments given. I wish for it to be called by the thread awaiting the returned task.

**Comment by tannergooding** [comment]
@sunkin351, are you asking if there is a way to effectively `await` a `VkWaitForFences()` call?

**Comment by davidfowl** [comment]
There is no thread, it’s up to the person calling SetResult on the task completion source to call it from the “right place”. If your API requires blocking then there’s no avoiding that. TaskCompletionSouce doesn’t make threads, it just gives you way to expose a Task where you don’t already have one.

**Comment by sunkin351** [comment]
Its just that VkWaitForFences() allows the option for simply querrying whether a fence was signaled, so I wanted to optimize based on that if possible.

**Comment by davidfowl** [comment]
When the consumer of your task is waiting for the task to complete, there's no thread executing. You have to have a thread somewhere, polling VkWaitForFences and completing the TaskCompletionSource when each fence completes. When you complete the completion source, the caller will execute on the thread that was waiting on wait for fences. You *can* dispatch execution of the continuation to the thread pool, but it's not the default. To do that you pass a flag to the constructor of the TaskCompletionSource called `TaskCreationOptions.RunContinuationsAsynchronously`.
