### ISSUE TITLE
Fix testing of libraries projects in the vscode

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#34210]
https://github.com/dotnet/runtime/pull/34025 fixes the intellisense and gives the option to user to run the an individual test or group of tests 
<img width="981" alt="Screen Shot 2020-03-27 at 1 46 21 PM" src="https://user-images.githubusercontent.com/10516582/77799179-75c87000-7031-11ea-9716-cde49208613e.png">

Currently on running the test it just hangs, It could be that coreclr is build in debug mode. It would be nice to have this thing working in vscode. It may also make the debugging easier on linux machine.
<img width="999" alt="Screen Shot 2020-03-27 at 1 46 36 PM" src="https://user-images.githubusercontent.com/10516582/77799268-a6a8a500-7031-11ea-971e-9bfaee84f10d.png">

cc @ViktorHofer @ericstj @danmosemsft @safern

**Comment by ViktorHofer** [comment]
Running tests in VS is not yet possible. This isn't related to a runtime configuration mismatch but due to how VSTest invokes the testhost.

**Comment by safern** [comment]
> This isn't related to a runtime configuration mismatch but due to how VSTest invokes the testhost.

I guess we would need to open vscode with some environment variables just like we do for VS? I'm just wondering, I think the best is to just wait for this to land when we move to VSTest with the new features you worked with them.

**Comment by ViktorHofer** [comment]
@ManickaP do you know if testing dotnet/runtime libraries inside VSCode does already work? I never tried it out myself.

**Comment by ViktorHofer** [comment]
Thanks @ManickaP. Unfortunately I don't know what this issue was originally tracking. VSCode doesn't have an in-built test explorer and `dotnet test` from the integrated terminal works just fine.
