### ISSUE TITLE
CI net472 leg failure: 'Target frameworks need to be updated'

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#34216]
```
src\libraries\Common\tests\Extensions\TestingUtils\Microsoft.AspNetCore.Testing\src\xunit\FrameworkSkipConditionAttribute.cs(53,8): error CS1029: (NETCORE_ENGINEERING_TELEMETRY=Build) #error: 'Target frameworks need to be updated.'
```

https://github.com/dotnet/runtime/pull/34207/checks?check_run_id=540330536

**Comment by danmosemsft** [comment]
Thanks. In future, if you know the build is broken, and it is sometimes the best move to validate locally and direct-commit as soon as you throw up the PR (so the PR can complete validation, but you've already almost surely fixed it)
