### ISSUE TITLE
Return interned strings in ReadOnlySpan<char>.ToString() if possible

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#34256]
Before allocating a new String object in `ReadOnlySpan<char>.ToString()` we can check if the given string is interned and return it instead of allocations, a **simplified** repro:
```csharp
string str1 = "hello";
string str2 = str1.AsSpan().ToString(); // currently returns a new object
bool sameObj = object.ReferenceEquals(str1, str2); // should be true
```
Working prototype: https://github.com/EgorBo/runtime-1/commit/df06317c054969bd277aa1783d1ea436fa4c7e14

The pool of interned string should contain all the most popular string such as "0", "1" constant formats we use in number formatting/parsing, etc.

/cc @controlflow (his idea), @jkotas

**Comment by jkotas** [comment]
You are trading allocations for throughput. It does not sound like a good idea to do by default. If it was a good idea to do it here, it would be a good idea to do for all string allocations.

If somebody wants to do string interning for Span.ToString, they can do it themselves with the policy that is fine tuned for the given case.
