### ISSUE TITLE
Should M.E.DependencyModel only target netstandard2.0+ going forward?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#3425]
M.E.DependencyModel currently supports several TFMs which means we have to maintain the use of two JSON APIs (System.Text.Json for netstandard2.0+ and Newtonsoft.Json for < netstandard2.0).

https://github.com/dotnet/core-setup/blob/63a01b08e5d1d1a6b8544f598b3d3bda76e6e424/src/managed/Microsoft.Extensions.DependencyModel/Microsoft.Extensions.DependencyModel.csproj#L6

We should consider only targeting netstandard2.0 for the upcoming major release and simplify our dependencies.

VS requires 4.7.2 which is compatible with netstandard2.0.

This effort goes in conjunction with https://github.com/dotnet/announcements/issues/90 and helps remove the dependency on Json.NET more cleanly: https://github.com/dotnet/core-setup/issues/3311

Related PRs:
- https://github.com/dotnet/core-setup/pull/5009
- https://github.com/dotnet/core-setup/pull/5010

cc @joshfree, @glennc, @eerhardt, @terrajobst, @jaredpar, @ericstj, @davidfowl, @livarcocc

**Comment by eerhardt** [comment]
I plan on doing this as part of moving `Microsoft.Extensions.DependencyModel` from `src\installer` to `src\libraries`.

We can add back the `netstandard1.x` targets in the future, if deemed necessary. But please speak up early if you know that only supporting `netstandard2.0` is going to be a problem.
