### ISSUE TITLE
Broken build on Linux ARM64 host

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#34254]
Looks like there are at least two issues with building on Linux ARM64 hosts:

1) Incorrect System.Private.CoreLib.dll variant is built. According to the logs and the artifact directory the output is for "Linux.x64". The CoreCLR native part is correctly built as "Linux.arm64".
2) cmake detection seems inconsistent. Early in the build it executes cmake just fine but later on it complains about the version being too old. The machine has cmake 3.17 installed from source to `/usr/local/bin/` and symlinked to `/usr/bin/`.

Full log attached: 
[10.txt](https://github.com/dotnet/runtime/files/4398858/10.txt)

**Comment by BruceForstall** [comment]
Building on a Linux arm64 is not a supported scenario, though it doesn't hurt to keep it working. cc @janvorli who I believe has done this in the past.

**Comment by filipnavara** [comment]
I'd gladly switch to consuming binary packages but right now Mono+LLVM runtime NuGets are not available. This will also affect any distribution that is going to try building from source.

**Comment by am11** [comment]
Fixed a similar issue for Android build <kbd>on</kbd> the device: https://github.com/dotnet/runtime/pull/34236.
Current approach for arm64 is to use rootfs script on Ubuntu x64:

```sh
cd runtime
./eng/common/cross/build-rootfs.sh arm64  # takes few minutes (add `alpine` if you want musl-libc based artifacts that take < 10 seconds to setup the whole thing, as its apk(1) uses HTTP instead of HTTPS, with super fast extraction and exempts multiple hash checks that aptitude uses..)

./build.sh -subsetcategory coreclr -cross -arch arm64 -configuration release
```

**Comment by filipnavara** [comment]
@am11 Thanks. I am aware of the approach for the official builds. It's unfortunately not applicable to my situation. I'd have to run additional machine and transfer the builds between the test machines.

**Comment by janvorli** [comment]
The build on arm64 device used to work, but I haven't tried that after the migration to the runtime repo. There seem to be even more issues than @filipnavara has reported. The Mono build is failing with "ERROR: No usable version of clang found.". 
@filipnavara as for the mis-detection of cmake, this sounds strange. I don't see cmake being executed in your log, I can see just a failure to detect that at multiple places. Is it possible that your symlink is somehow not correct? Can you please run `/usr/bin/cmake --version` to verify it?
As for the runtime package (including System.Private.CoreLib) coming from x64 version of the package at the build, I actually wonder why do we restore them from packages at all. The build should start by building the coreclr. I'll try to run it on my local RPI3 to see.

**Comment by filipnavara** [comment]
> The build on arm64 device used to work, but I haven't tried that after the migration to the runtime repo. There seem to be even more issues than @filipnavara has reported. The Mono build is failing with "ERROR: No usable version of clang found.".

I have clang installed on the machine:
```
ubuntu@ip-172-31-17-240:~$ clang-9 --version
clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

> @filipnavara as for the mis-detection of cmake, this sounds strange. I don't see cmake being executed in your log, I can see just a failure to detect that at multiple places. Is it possible that your symlink is somehow not correct? Can you please run `/usr/bin/cmake --version` to verify it?

My bad, I must have pasted wrong log from the Azure pipelines. Here's a more recent one: [24.txt](https://github.com/dotnet/runtime/files/4402630/24.txt)

The cmake is executed successfully here:
```
2020-03-30T01:50:23.4187882Z   Checking prerequisites...
2020-03-30T01:50:23.4207757Z   /usr/local/bin/cmake
...
2020-03-30T01:50:33.2727385Z   -- The C compiler identification is Clang 9.0.0
2020-03-30T01:50:33.4858512Z   -- The CXX compiler identification is Clang 9.0.0
```

Apparently this log seems to have CMake working fine. The one that was working in some cases and not working in others had `/usr/local/bin/cmake` on the places where it worked and `/usr/bin/cmake` on those where it didn't work.

Here's the version information:
```
ubuntu@ip-172-31-17-240:~$ /usr/local/bin/cmake --version
cmake version 3.17.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
ubuntu@ip-172-31-17-240:~$ /usr/bin/cmake --version
cmake version 3.17.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

> As for the runtime package (including System.Private.CoreLib) coming from x64 version of the package at the build, I actually wonder why do we restore them from packages at all. The build should start by building the coreclr. I'll try to run it on my local RPI3 to see.

Thanks! I can give you access to the AWS test machine I use. Let me know if it would be of any help.

**Comment by filipnavara** [comment]
Looks like #34300 may address the System.Private.CoreLib.dll part.

**Comment by janvorli** [comment]
@filipnavara ah, great, the build on my RPI3 is so slow that it is just finishing the coreclr build after several hours of busy work of compiling cmake and building coreclr. So it is a perfect time to apply that change and see if it fixes the problem with S.P.C.

**Comment by filipnavara** [comment]
I can confirm the fix in #34300 works. Still waiting for the full build to finish to see if there is any other problem.

**Comment by janvorli** [comment]
OK, great, so I can stop torturing my poor RPi3. So we just have the cmake detection issue  left, right? I'll switch to looking into that.

**Comment by filipnavara** [comment]
Yeah, let's see if I can still reproduce the CMake issue. The full build should take around 1,5 hours on the AWS machine so it will take a bit of time for me to get new logs.

**Comment by janvorli** [comment]
Looking at the logs you've shared again, I can see that one was failing consistently at all attempts to locate the correct cmake (it found it in /usr/bin/cmake and the version was not right) and the other was succeeding consistently (it found it in /usr/local/bin/cmake). So I haven't seen the case you were referring to (failing early in the build and succeeding later).
Looking at the detection code here:
https://github.com/dotnet/runtime/blob/335ffb05fbe97187452046bc6791405ea33f210c/eng/native/build-commons.sh#L51-L60
It is not clear to me how it could have executed a different cmake than the one it printed a path to or mis-detected the version.

**Comment by filipnavara** [comment]
Unfortunately I don't have logs from that one failed run. I cannot completely rule out that it was error in my setup caused by uninstalling the old APT-distributed cmake and reinstalling the new cmake from source when the Azure Pipelines agent was running on the machine. The APT-distributed cmake was version 3.10 located in `/usr/bin/cmake`. I am sure I didn't do the steps when any build was running on the agent. However, there could still have been something that I overlooked.

I don't think it's worth wasting time on it until I get results from the next build. It already passed through several places where cmake was required and the error didn't happen so it's likely that it was a configuration error with the specific machine.

**Comment by filipnavara** [comment]
Looks like I underestimated the build times. However, it got past all the native components (Mono, CoreCLR, Native libraries) so it looks quite promising that this time it will get to the end.

**Comment by filipnavara** [comment]
It was incremental build from the last failure point, not a clean one, but it eventually finished:
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 01:22:41.19
```

Let's close this once #34300 is merged.

**Comment by safern** [comment]
> Let's close this once #34300 is merged.

It feels nice to get lucky and fix an issue while intending to fix another one 😄
