### ISSUE TITLE
Consider harvesting S.CM.Composition and S.R.DispatchProxy for netstandard2.x

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#34253]
We still live build S.CM.Composition and S.R.DispatchProxy for netstandard2.x even though those are part of the netstandard closure. We should consider harvesting them for netstandard2.x and add a netcoreapp configuration.

This is controversial so I'm not saying we should do it but considering it.

@ericstj thoughts?

**Comment by ericstj** [comment]
When you say "part of netstandard closure" do you mean that all the types were absorbed into netstandard.dll?  If the latter then we should just stop building the package.

I do see that System.Reflection.DispatchProxy is part of netstandard.dll with https://github.com/dotnet/standard/commit/ce9240526720810d1565032ed6674ec57c70074b

I didn't see any of System.ComponentModel.Composition in netstandard.dll.

**Comment by ericstj** [comment]
@ViktorHofer can you clarify what you meant by being part of the netstandard closure?

**Comment by ViktorHofer** [comment]
In my PR I had to disable the default references for both assemblies which come via netstandard 2.0 and/or 2.1 to avoid cycles during the restore: https://github.com/dotnet/runtime/pull/34893/files#diff-e2009cfe1f129dd4d69891e2c457a0f9R47-R52.

> When you say "part of netstandard closure" do you mean that all the types were absorbed into netstandard.dll?

I meant that those assemblies are part of the default references:

![image](https://user-images.githubusercontent.com/7412651/79580465-4f926f00-80c9-11ea-8b82-d03f4e068fb1.png)

**Comment by ericstj** [comment]
System.ComponentModel.Composition.dll is very small in `netstandard2.1` it's a single type:
```
[assembly: TypeForwardedTo(typeof(Lazy<, >))]
```
For that one we cannot remove the package.  It is correct to allow the libraries version to win.

DispatchProxy on the other hand appears to completely overlap.  For that one we can stop building the package and remove the netstandard ref.
