### ISSUE TITLE
RegEx, please add Pre-Defined Subroutines.

### ISSUE THREAD

**Issue by Layarion** [dotnet/runtime#34269]
I have found myself wishing that .Net Regex supported Pre-Defined subroutines in this situation: https://i.imgur.com/fvN7tka.png

definition here: https://www.rexegg.com/regex-disambiguation.html#define
at the "Pre-Defined Subroutines" section.

If I want modular, and maybe even more readable regex, I think a Pre-Defined subroutine here would a) still allow me to use regex syntax highlighting since I wouldn't need `$""` anymore. b) I would still be able to use the entire expression in tools like this: http://regexstorm.net/tester

regexstorm won't know what `{commands}` is and thus I won't be able to use it like this.

**Comment by pgovind** [comment]
This would be a substantial addition to the regex engine itself. I'd be very interested to get a sense of how popular this request is.

**Comment by sunkin351** [comment]
I have an interest in having this implemented, or implementing it myself.

**Comment by pgovind** [comment]
@sunkin351: Please feel free to prototype/implement this. I highly recommend putting up your plan/prototype first so everyone can review it. An option to consider might be prototyping your work in dotnet/runtimelab.

**Comment by sunkin351** [comment]
I'll be honest, I'm not familiar at all with the code in this area, so assistance would be beneficial in knowing where and how to modify/add to the implementation.

**Comment by VBAndCs** [comment]
I asked for this 2.5 years ago (with an ole account), and asked also to allow us to call a validation function from a regex expression. One thing to solve with this, is to validate IP parts are lee than 256, which is a complex thing to do by regex syntax.
\b(?:1?\d{1,2}|2(?:[0-4]\d|5[0-5]))(?:\.(?:1?\d{1,2}|2(?:[0-4]\d|5[0-5]))){3}\b
But if we can use a validation function it would be:
\b(?Validate(\d{1,3}))(?:.(?Validate(\d{1,3}))){3}\b
I remembered this while writing a tiny regex with `Ring lang` (it supports Regex but I don't want to use it).
It wasn't difficult to allow this pattern:
```
ex.Replace(
    sourceStr, 
    "xy$myFunc(2,1)", 
    "#If(1)x#1z#1|xyz"
)
```

`$myFunc(2,1)` calls myFunc, passing it 2 chars in the match pos. the 1 param in the pattern means continue evaluating expression when validation fails,
So, in the replacement pattern, I can check if the validation function succeeded by its group number `#If(1)` and supply two patterns, one for valid match, and another of invalid match.
This yields simpler yet more powerful regex patterns.
I hope you support something like this in .NET Regex.

**Comment by VBAndCs** [comment]
The old proposal: https://github.com/dotnet/runtime/issues/26160

**Comment by sunkin351** [comment]
I have no idea what syntax you're going for... I'm just trying to close a gap with .NET missing regex capabilities. Recursion in this case.

**Comment by VBAndCs** [comment]
By the way, it is easier to use [Verex](https://github.com/VBAndCs/Verex) to define and reuse regex patterns. Ex:
```
var ValidFirstChar = EnglishLetterOrHyphen;
var ValidChars = EnglishLetterOrHyphenOrDigit & '.' & '-';

var email = WordEdge
        + ValidFirstChar
        + ValidChars[0, 19]
        + "@"
        + ValidFirstChar
        + ValidChars[2, 14]
        + "."
        + ValidFirstChar
        + ValidChars[1, 9]
        + WordEdge;

textBox1.Text = email.ToString();

var vrx = new Verex(email);
var txt = "My email is msvbnet@hotmail.com .";
var m = vrx.Match(txt);
if (m.Success)
    MessageBox.Show(m.Value);
```

It generates:
`\b[_a-zA-Z][_.\-a-zA-Z0-9]{0,19}@[_a-zA-Z][_.\-a-zA-Z0-9]{2,14}\.[_a-zA-Z][_.\-a-zA-Z0-9]{1,9}\b`

**Comment by sunkin351** [comment]
Do we want to support the `\g` meta sequence? Being that its part of the Regex Recursion surface area...
