### ISSUE TITLE
In 2.1/2.2, upgrade runtime-deps OpenSSL dependency to 1.1

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3426]
See https://github.com/dotnet/core-setup/issues/4731.

OpenSSL 1.1 support in the .NET Core Runtime is being ported to 2.1/2.2: https://github.com/dotnet/corefx/pull/34443. Once that's done, we can upgrade runtime-deps dependencies here in core-setup.

I think we would need to upgrade to support new distro versions as OpenSSL 1.0 support is dropped from repositories. (I don't know how broadly support will be dropping.)

However, we might not want to upgrade OpenSSL on distro versions we already have runtime-deps packages for, simply to avoid unnecessary changes. I don't know the benefits of OpenSSL 1.1 vs. 1.0 in itself, maybe there's a compelling reason. Or, using 1.1 throughout all of 2.1, 2.2, and 3.0 might be enough reason to do so.

/cc @leecow

**Comment by NikolaMilosavljevic** [comment]
No customer asks for this potentially breaking change.
