### ISSUE TITLE
Add an abstract base class to the Utf8JsonWriter, please!

### ISSUE THREAD

**Issue by xljiulang** [dotnet/runtime#34277]
In my scenario, I need to use JsonSerializer to use the same configuration and Atribute to serialize an object as Json, bson,  and key-value list(for x-www-form-urlencoded). Now the Utf8JsonWriter is sealed and cannot be overridden any method, and there is no an abstract base class. Please design an abstract base class for Utf8JsonWriter

**Comment by xljiulang** [comment]
We can abstract out a JsonWriter class and subclass the existing Utf8JsonWriter. Developers can implement other subclasses, such as TextJsonWriter, BsonWriter, KeyValueWriter, etc., so that other serialization requirements with similar serialization can implement their own serialization format at very low cost.

**Comment by layomia** [comment]
To better understand your scenario, can you put together an API proposal and code examples of what you would like to achieve? Here are some examples for the JSON space: https://github.com/dotnet/runtime/tree/master/src/libraries/System.Text.Json/docs.

Building an abstraction for the `Utf8JsonWriter` requires a fully fleshed out design and the various trade-offs carefully evaluated.

**Comment by joshudson** [comment]
Correct me if I'm wrong, but I think you want a Utf8StringWriter.

**Comment by xljiulang** [comment]
@joshudson 

I want to use the custom JsonWriter and combine the JsonSerializer to serialize  an object to the format of ini, YML or key-value set

**Comment by GrabYourPitchforks** [comment]
Why would you want to use a JSON-specific class to create output that is unrelated to JSON? It seems that you'd be best served by having a generic serialization base class which isn't tied to JSON, BSON, YML, INI, or any other specific format. Then within each format's concrete implementation you could wrap the real serializer.

**Comment by joshudson** [comment]
Oh; maybe he wants to rip the base out of JsonSerializer not Utf8JSONWriter.
