### ISSUE TITLE
Fix assembly loading order on mono

### ISSUE THREAD

**Issue by BrzVlad** [dotnet/runtime#34273]
## Steps to reproduce
1. Build a mono runtime (`./mono.sh`, `make patch-mono-dotnet`)
2. Clone https://github.com/dotnet/performance
3. Build `src/benchmarks/micro/MicroBenchmarks.csproj` (`./dotnet-mono build -c Release -f netcoreapp5.0 MicroBenchmarks.csproj`)
4. Go to binaries folder in `artifacts/bin/MicroBenchmarks/Release/netcoreapp5.0` and run `MicroBenchmarks.dll`
5. Observer a libgdiplus error which seems to be caused by loading of `System.Drawing.Common.dll` from the current folder, rather than from the `runtimes` folder

**Comment by CoffeeFlux** [comment]
For documentation, the reason this is happening is the netcore hook (which checks the TPAs) and the hook checking ApplicationBase are both preload hooks, but the netcore hook is installed first. When both hooks are prepended, this means the netcore hook is run last, so we were loading from ApplicationBase first. We want the netcore hook to be the first preload hook we run.
