### ISSUE TITLE
Question: Do you need to call Process.WaitForExit() after Process.WaitForExitAsync(CancellationToken)

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#34294]
In .NET you should call `Process.WaitForExit()` to ensures that all processing has been completed, including the handling of asynchronous events for redirected standard output.

````c#
Process p = Process.Start(...);
while (!p.WaitForExit(1000)) {}

// call WaitForExit() here to ensures that all processing has been completed
p.WaitForExit();
````

In .NET 5 there is a new method `Process.WaitForExitAsync(CancellationToken)`. Should we call `WaitForExit` after `Process.WaitForExitAsync`?

````c#
Process p = Process.Start(...);
await p.WaitForExitAsync(cancellationToken);

// Is it necessary to ensures that all processing has been completed?
p.WaitForExit();
````

**Comment by scalablecory** [comment]
`WaitForExitAsync` is all you need. It is semantically equivalent, just async rather than blocking.
