### ISSUE TITLE
System.Net.HttpWebRequest fails with error 502 Bad Gateway

### ISSUE THREAD

**Issue by darkdragon-001** [dotnet/runtime#34290]
`HttpWebRequest` with `PreAuthenticate=true` and `NetworkCredential("anonymous", string.Empty)` returns error _(502) Bad Gateway_ for some websites.

Example code:
```
using System;
using System.IO;
using System.Net;

namespace monotest2
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri uri = new Uri("https://www.duolingo.com/");

            HttpWebRequest req = WebRequest.CreateHttp(uri);
            req.Credentials = new NetworkCredential("anonymous", string.Empty);
            req.PreAuthenticate = true;

            using (Stream s = req.GetResponse().GetResponseStream())
            {
                using (StreamReader sr = new StreamReader(s))
                {
                    Console.WriteLine(sr.ReadToEnd());
                }
            }
        }
    }
}
```

This happens for
- .Net Core 2.2
- Mono 6.8.0.105

A friend tested this on Windows with .Net Framework where it works without problems.

**Comment by stephentoub** [comment]
I just tried this on Windows on .NET Core 2.2 and 3.1, and .NET 5 Preview 1, and it succeeded for me in all cases.

Can you elaborate on your configuration?  You wrote "Mono 6.8.0.105"... were you saying you tried this on both .NET Core 2.2 and Mono, or were saying this was only failing on Mono?

**Comment by darkdragon-001** [comment]
I was selecting .NET Core App as target in MonoDevelop and thought it is using .Net Core then. But the important part is running the result. Running it via `dotnet monotest2.dll` works while running the same file with `mono monotest2.dll` throws the stated error. So it obviously is a problem with mono. Sorry to bother you and thanks for your help and testing!

**Comment by stephentoub** [comment]
Thanks for confirming.
