### ISSUE TITLE
Review `MONO_CPU_X86_SSSE3_COMBINED`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#34304]
`MONO_CPU_X86_SSSE3_COMBINED` is currently defined as `MONO_CPU_X86_SSE3_COMBINED  | MONO_CPU_X86_PCLMUL | MONO_CPU_X86_AES | MONO_CPU_X86_SSSE3,` (https://github.com/dotnet/runtime/blob/335ffb05fbe97187452046bc6791405ea33f210c/src/mono/mono/mini/mini.h#L2832).

However, this doesn't match the hierarchy exposed by `System.Runtime.Intrinsics` nor does it match the CPUID checks specified by the Intel or AMD architecture manuals:

From `Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 1: Basic Architecture, October 2019`
![image](https://user-images.githubusercontent.com/10487869/77967198-811dd480-7299-11ea-8046-54dc199b356e.png)
![image](https://user-images.githubusercontent.com/10487869/77967149-621f4280-7299-11ea-99f2-0be005f0bdfe.png)

**Comment by tannergooding** [comment]
CC. @EgorBo, @davidwrighton

**Comment by davidwrighton** [comment]
I'm not convinced that the relationship that is implemented here in Mono is right, but it is interesting. In all practical cases, these may be equivalent, and by combining instruction sets like this, the test matrix is technically reduced. However, we should be sure that the checks in the runtime are equivalent between both Mono and CoreCLR and their associated AOT compilers. One convincing argument that this approach is correct would be if the llvm model also matches mono here. But if it doesn't we should probably change mono to match the Intel/AMD manuals.
