### ISSUE TITLE
DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs failed in CI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#34317]
# Console Log Summary

```
    System.Net.NameResolution.Tests.GetHostEntryTest.DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs(mode: 0) [FAIL]
      Assert.All() Failure: 2 out of 4 items in the collection did not pass.
      [3]: Item: fe80::20d:3aff:fe5b:2be9%2
           Xunit.Sdk.TrueException: Not a loopback address: fe80::20d:3aff:fe5b:2be9%2
           Expected: True
           Actual:   False
              at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 95
              at Xunit.Assert.True(Boolean condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 83
              at System.Net.NameResolution.Tests.GetHostEntryTest.<>c.<DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs>b__13_0(IPAddress addr) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 205
              at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
      [2]: Item: 10.0.0.22
           Xunit.Sdk.TrueException: Not a loopback address: 10.0.0.22
           Expected: True
           Actual:   False
              at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 95
              at Xunit.Assert.True(Boolean condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 83
              at System.Net.NameResolution.Tests.GetHostEntryTest.<>c.<DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs>b__13_0(IPAddress addr) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 205
              at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
      Stack Trace:
        /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(205,0): at System.Net.NameResolution.Tests.GetHostEntryTest.DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs(Int32 mode)
        --- End of stack trace from previous location ---
```

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#580674](https://dev.azure.com/dnceng/public/_build/results?buildId=580674)|Rolling|1|
### Configurations
- netcoreapp5.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#580674](https://dev.azure.com/dnceng/public/_build/results?buildId=580674)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4a569c32-cd00-416f-9855-d4a61f9cf52d/workitems/System.Net.NameResolution.Functional.Tests/files/console.223f1868.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/4a569c32-cd00-416f-9855-d4a61f9cf52d/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-4a569c32cd00416f98/System.Net.NameResolution.Functional.Tests/5636a998-54be-4c48-8e78-105109f111bf.log?sv=2019-02-02&se=2020-04-10T02%3A20%3A40Z&sr=c&sp=rl&sig=vhYnjH8qvLcfq2dCUhptNpKLzGRRt%2FXUEvvRHkKFdv4%3D)|

Only seen one failure so far but also suspicious that this showed up in CI

**Comment by jaredpar** [comment]
This is now regularly blocking CI @karelz 

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#584646](https://dev.azure.com/dnceng/public/_build/results?buildId=584646)|Rolling|1|
|[#584991](https://dev.azure.com/dnceng/public/_build/results?buildId=584991)|Rolling|1|
|[#585184](https://dev.azure.com/dnceng/public/_build/results?buildId=585184)|Rolling|2|
### Configurations
- netcoreapp5.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open
- netcoreapp5.0-Linux-Release-x64-Mono_release-SLES.12.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#584646](https://dev.azure.com/dnceng/public/_build/results?buildId=584646)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/2f47daac-71f1-49c2-87d3-4dec9ad248b5/workitems/System.Net.NameResolution.Functional.Tests/files/console.6ec34737.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/2f47daac-71f1-49c2-87d3-4dec9ad248b5/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-2f47daac71f149c287/System.Net.NameResolution.Functional.Tests/888d4a0e-bdae-4c2b-baca-6e5e833826d6.log?sv=2019-02-02&se=2020-04-12T01%3A53%3A19Z&sr=c&sp=rl&sig=jZ%2FWVEiROWpKLtmmKt8Znkk9NLzuYSHkI1YYR83uzQI%3D)|
|[#584991](https://dev.azure.com/dnceng/public/_build/results?buildId=584991)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4c8de3c5-46b3-40b1-ac4a-15278a9b9eb1/workitems/System.Net.NameResolution.Functional.Tests/files/console.40aaf356.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/4c8de3c5-46b3-40b1-ac4a-15278a9b9eb1/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-4c8de3c546b340b1ac/System.Net.NameResolution.Functional.Tests/52aba14b-9702-4fa1-be1d-dd45f94aed36.log?sv=2019-02-02&se=2020-04-12T06%3A53%3A05Z&sr=c&sp=rl&sig=J3k%2F1oR1nEMPHBCbrngiXG7EJowxJKvKODManlB9Y3Q%3D)|
|[#585184](https://dev.azure.com/dnceng/public/_build/results?buildId=585184)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/0fc4bedb-d8b2-4960-aaf6-90332af4b089/workitems/System.Net.NameResolution.Functional.Tests/files/console.e79420e7.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/0fc4bedb-d8b2-4960-aaf6-90332af4b089/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-0fc4bedbd8b24960aa/System.Net.NameResolution.Functional.Tests/b83afd74-66dc-4938-85e0-fd1609e2f718.log?sv=2019-02-02&se=2020-04-12T12%3A23%3A22Z&sr=c&sp=rl&sig=R6uJsn0HbcaqVJsYfypUI1sdhwxzzQOhA7lHboWuX7Q%3D)|
|[#585184](https://dev.azure.com/dnceng/public/_build/results?buildId=585184)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/eea23c91-0f38-41a2-a648-1c45d2ac2aaa/workitems/System.Net.NameResolution.Functional.Tests/files/console.4fc2a1e3.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/eea23c91-0f38-41a2-a648-1c45d2ac2aaa/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-eea23c910f3841a2a6/System.Net.NameResolution.Functional.Tests/6a502360-c8c0-4d1d-9a20-2908a80cec4b.log?sv=2019-02-02&se=2020-04-12T12%3A25%3A38Z&sr=c&sp=rl&sig=4QYp4v%2B9yCRAUMKqKmiRl7hBuHxlMpwVJsX8etIega8%3D)|

**Comment by karelz** [comment]
@MihaZupan can you please take a look at this new failure?
Kusto database mining shows first and only failure 2 days ago (3/31). Disabling the test to unblock CI may be best first response.
cc @alnikola

**Comment by jaredpar** [comment]
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#585813](https://dev.azure.com/dnceng/public/_build/results?buildId=585813)|Rolling|1|
|[#586664](https://dev.azure.com/dnceng/public/_build/results?buildId=586664)|Rolling|1|
|[#587083](https://dev.azure.com/dnceng/public/_build/results?buildId=587083)|Rolling|1|
### Configurations
- netcoreapp5.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open
- netcoreapp5.0-Linux-Release-x64-Mono_release-SLES.12.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#585813](https://dev.azure.com/dnceng/public/_build/results?buildId=585813)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/a3687818-7958-4109-954e-6688c606f7d4/workitems/System.Net.NameResolution.Functional.Tests/files/console.f81dec1d.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/a3687818-7958-4109-954e-6688c606f7d4/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a36878187958410995/System.Net.NameResolution.Functional.Tests/4248e379-7485-4b7b-9ea0-d333e1287881.log?sv=2019-02-02&se=2020-04-12T20%3A32%3A38Z&sr=c&sp=rl&sig=WIsHNtmbY15IHXssmMesIqxB6V8MA7lOZhcjf8%2FTsME%3D)|
|[#586664](https://dev.azure.com/dnceng/public/_build/results?buildId=586664)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/f89d3bb3-4d3e-4d11-b365-0b95b338e68c/workitems/System.Net.NameResolution.Functional.Tests/files/console.abd54c5e.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/f89d3bb3-4d3e-4d11-b365-0b95b338e68c/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-f89d3bb34d3e4d11b3/System.Net.NameResolution.Functional.Tests/e3efc99e-0b40-4044-9c47-545bab8b4d35.log?sv=2019-02-02&se=2020-04-13T01%3A18%3A26Z&sr=c&sp=rl&sig=zaogk71sDzErRyaMTHEMi5inHUv4V2Ye6A2laQtwNHU%3D)|
|[#587083](https://dev.azure.com/dnceng/public/_build/results?buildId=587083)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/ad69a534-e461-4014-8497-0dbd5d2f0d4c/workitems/System.Net.NameResolution.Functional.Tests/files/console.5b2c8831.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/ad69a534-e461-4014-8497-0dbd5d2f0d4c/workitems/System.Net.NameResolution.Functional.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-ad69a534e461401484/System.Net.NameResolution.Functional.Tests/9bef35ce-34dd-4175-9553-c982fe536dea.log?sv=2019-02-02&se=2020-04-13T06%3A56%3A44Z&sr=c&sp=rl&sig=kkwfw77MjJS8lGmEOj6mjjhJ7arFOWw6gG%2B99HLm2qk%3D)|

**Comment by jaredpar** [comment]
This is causing roughly a 3% failure rate at this point. Do we have an ETA for when this will be disabled?

**Comment by karelz** [comment]
Sorry for that, I thought @MihaZupan had chance to do it over night.
PR is up - see #34527

**Comment by MihaZupan** [comment]
From console logs here I am seeing the following tests failing
```text
DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs
DnsObsoleteGetHostByName_EmptyString_ReturnsHostName
DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName
Dns_GetHostEntry_HostString_Ok
Dns_GetHostEntryAsync_HostString_Ok
```
Which looks like the 4 mentioned in https://github.com/dotnet/runtime/issues/1488 + now `DnsGetHostEntry_LocalHost_ReturnsFqdnAndLoopbackIPs`

**Comment by wfurt** [comment]
This may be misconfigured machine. Also SLES12 uses systemd and that resolver can synthesize response. I think we should collect more system info on failure. If we have helper diag functions, that may be helpful for other DNS test failures.

**Comment by alnikola** [comment]
@wfurt I think you are right because the test always fails when it's run on an sles.12.amd64.open agent with machine name 'localhost' which looks weird.

**Comment by alnikola** [comment]
The failures were caused by a Helix infra issue which was resolved yesterday.

**Comment by karelz** [comment]
@alnikola did we re-enable the tests?
Was it the misconfiguration with `localhost`?

**Comment by karelz** [comment]
Reopening to re-enable the tests ...
https://github.com/dotnet/runtime/blob/d818d33294288fce07ec7b89b1a16922cd24e451/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs#L189

**Comment by jaredpar** [comment]
@alnikola 

> The failures were caused by a Helix infra issue which was resolved yesterday.

What Helix issue was this? I'm looking for an issue in core-eng or arcade to link to. If they didn't create on for this problem we should push them to do so. 

Issues are the primary way we track reliability between our services. If there is a bug in Helix, Azure, etc ... that impacted our reliability we should push to make sure that there is an issue tracking that. Always feel free to include me in the convo to help with this if needed.

**Comment by alnikola** [comment]
The issue was closed without enabling the affected test by mistake. Will do it shortly.

**Comment by jaredpar** [comment]
@alnikola 

Where is the Helix issue that describes the bug that they fixed? That is what I'm interested in. If they're not filing bugs then it's issues we're not tracking. That means we can't track improvements.

**Comment by alnikola** [comment]
@jaredpar Helix issue was reported by the engineering services team. I don't have a link. Will ping offline for the details.
