### ISSUE TITLE
Linux .NET Core : Encoding 1252 issue

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#34320]
Hi,
On Linux .NET Core version 3.1, the below core reports the following exception. The same code works on Windows. Any pointers in terms of common codepage (culInfo.TextInfo.ANSICodePage) usage would be helpful on Windows and Linux. The below code snippet is in OdbcParameter.cs file.

                        if (!Convert.IsDBNull(value) && value is string)
                        {
                            int lcid = System.Globalization.CultureInfo.CurrentCulture.LCID;
                            CultureInfo culInfo = new CultureInfo(lcid);
                            Encoding cpe = System.Text.Encoding.GetEncoding(culInfo.TextInfo.ANSICodePage);
                            value = cpe.GetBytes(value.ToString());
                            size = ((byte[])value).Length;
                        }

Exception on Linux:
--------------------
Unhandled exception. System.NotSupportedException: No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at Informix.Net.Core.IfxParameter.PrepareForBind(IfxCommand command, Int16 ordinal, Int32& parameterBufferSize)
   at Informix.Net.Core.IfxParameterCollection.CalcParameterBufferSize(IfxCommand command)
   at Informix.Net.Core.IfxCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at Informix.Net.Core.IfxCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at Informix.Net.Core.IfxCommand.ExecuteNonQuery()
   at Bigint_test1.Main(String[] args) in /home/pratishtha/Desktop/NetCore/dotnetcore/devtests/Bigint/Bigint_Test1/testcase.cs:line 95

**Comment by EgorBo** [comment]
The exception text contains useful information that answers your question: 
```
No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
```
so you need to register `CodePagesEncodingProvider.Instance` as encoding provider.

**Comment by deokershesh** [comment]
It should be under label "area-System.Data" (ODBC)

**Comment by deokershesh** [comment]
Thanks @EgorBo, I compiled (and tested one basic test) on Windows after adding the line you suggested, I yet to try on Linux. Hope the below code is fine?

int lcid = System.Globalization.CultureInfo.CurrentCulture.LCID;
                            CultureInfo culInfo = new CultureInfo(lcid);
                            System.Text.Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                            Encoding cpe = System.Text.Encoding.GetEncoding(culInfo.TextInfo.ANSICodePage);
                            Value = cpe.GetString((byte[])Value);

**Comment by EgorBo** [comment]
@deokershesh should be fine, the idea is to link fat `System.Text.Encoding.CodePages` with rarely used encodings (tables).

**Comment by rstm-sf** [comment]
```c#
System.Text.Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
System.Text.Encoding.GetEncoding(name);
```

Can replace it with the following, without registering a provider (.net core >= 3.0)

```c#
CodePagesEncodingProvider.Instance.GetEncoding(name);
```

I think we can do something like this https://github.com/dotnet/runtime/issues/31244#issuecomment-597739520. Please correct me if I'm wrong

**Comment by tarekgh** [comment]
Registering the provider should take care with this issue. The link https://docs.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=netcore-3.1#remarks is providing more info if you want to consult it. I am closing the issue but feel free to respond back with any question which we can help with.
