### ISSUE TITLE
[Linux/x64/Debug] System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests failures in CI

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#34326]
An example of the error:
```
Assert.Equal() Failure\nExpected: 74785590\nActual: 74786910
```

The failing run: https://dev.azure.com/dnceng/public/_build/results?buildId=580328&view=ms.vss-test-web.build-test-results-tab

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/28553
