### ISSUE TITLE
In 2.1 and 2.2 branches, set authors/owners of PlatformAbstractions and DependencyModel packages

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3433]
See https://github.com/dotnet/core-setup/issues/5051 (`master`)

> Currently (e.g. `release/2.1`, but also `master`) these packages don't have author and owner set:
> 
> ```
>     <id>Microsoft.Extensions.DependencyModel</id>
>     <version>2.1.0</version>
>     <authors>Microsoft.Extensions.DependencyModel</authors>
>     <owners>Microsoft.Extensions.DependencyModel</owners>
> ```
> 
> ```
>     <id>Microsoft.DotNet.PlatformAbstractions</id>
>     <version>2.1.0</version>
>     <authors>Microsoft.DotNet.PlatformAbstractions</authors>
>     <owners>Microsoft.DotNet.PlatformAbstractions</owners>
> ```
> 
> These packages are built by `dotnet pack` so they are likely just missing properties.

Port https://github.com/dotnet/core-setup/pull/5060 to 2.1/2.2.

PR: https://github.com/dotnet/core-setup/pull/5065

**Comment by eerhardt** [comment]
@dagood - is this still necessary? I'm going to close it, but if you feel it is still necessary please re-open.

**Comment by dagood** [comment]
It's necessary if we need to push a new version of these packages in 2.1, due to new requirements: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/972/NuGet?anchor=attribute-requirements

/cc @NikolaMilosavljevic

**Comment by eerhardt** [comment]
Since we haven't had to service DependencyModel in 2.1 yet, I'd say we can set these attributes if/when we need to service 2.1. I don't think there is a reason to keep this issue open.

**Comment by dagood** [comment]
Problem is, if it's forgotten, it only shows up as an error close to release day since we don't have validation baked into the build. (I think we are still unable to validate with "standard" tooling. I'm only aware of some custom-written validation bits, https://www.nuget.org/packages/Jver.VerifyMicrosoftPackage/0.0.1-beta.)

Whether an open issue means it'll be forgotten or not, I don't know.
