### ISSUE TITLE
Change in FileSystem.Unix.File.Move possibly introduced bug

### ISSUE THREAD

**Issue by alexischr** [dotnet/runtime#34330]
While porting https://github.com/dotnet/corefx/pull/40611 to Mono, @baulig noticed a deleted line 
checking the `Dev` fields of the `struct FileStatus` outputs of `LStat` for the source and destination files. No discussion was made about that change, which seems incorrect, and the comment on the next line even alludes to the removed check.

The line:
https://github.com/dotnet/corefx/pull/40611/files#r401020707

The Mono discussion:
https://github.com/mono/corefx/pull/395/files#r400813984

//cc original reviewers @stephentoub @carlossanlop @JeremyKuhne

**Comment by alexischr** [comment]
cc @mdh1418

**Comment by danmosemsft** [comment]
We still have the `sourceStat.Ino == destStat.Ino` check -- am I right in guessing that inodes of two files on different devices could theoretically be the same, but it's very unlikely (hence we didn't see any issue)?

**Comment by mdh1418** [comment]
Right, the inode check is still there. Wouldn't adding the device check back in ensure that the code is functioning as we intend it to, rather than introduce an undesired case where inodes happen to be the same on different devices?

**Comment by baulig** [comment]
When I reviewed the Mono PR and saw this, my thinking was that we're introducing a bug that will be extremely rare and thus a total nightmare to track down when it does happen.  Even more so because when it does happen, the scenario will only exist on the customer's system and be unreproducible by any of us.

**Comment by danmosemsft** [comment]
Yup. fully agree, we should add it back. Was just thinking aloud why we had not seen a problem yet.

**Comment by danmosemsft** [comment]
One of you want to throw up the PR? If not then area owner can but I  think this is a one line PR with perhaps no reasonable test possible for it.
