### ISSUE TITLE
Formatting job is causing flaky failures

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#34336]
The formatting job is now failing on 4% of our jobs and doing so on PRs that don't actually change any native sources. The content of the patch file seems to always be the same even though the PRs are not touching these files:

```
diff --git a/src/coreclr/src/jit/alloc.cpp b/src/coreclr/src/jit/alloc.cpp
index ca205e1..62fa0e8 100644
--- a/src/coreclr/src/jit/alloc.cpp
+++ b/src/coreclr/src/jit/alloc.cpp
@@ -139,41 +139,43 @@ void ArenaAllocator::destroy()
 
 //------------------------------------------------------------------------
 // ArenaAllocator::allocateHostMemory:
 //    Allocates memory from the host (or the OS if `bypassHostAllocator()`
 //    returns `true`).
 //
 // Arguments:
 //    size - The number of bytes to allocate.
 //    pActualSize - The number of byte actually allocated.
 //
 // Return Value:
 //    A pointer to the allocated memory.
 void* ArenaAllocator::allocateHostMemory(size_t size, size_t* pActualSize)
 {
 #if defined(DEBUG)
     if (bypassHostAllocator())
     {
         *pActualSize = size;
         void* p      = malloc(size);
         if (p == nullptr)
+        {
             NOMEM();
+        }
         return p;
     }
 #endif // !defined(DEBUG)
 
     return g_jitHost->allocateSlab(size, pActualSize);
 }
 
 //------------------------------------------------------------------------
 // ArenaAllocator::freeHostMemory:
 //    Frees memory allocated by a previous call to `allocateHostMemory`.
 //
 // Arguments:
 //    block - A pointer to the memory to free.
 void ArenaAllocator::freeHostMemory(void* block, size_t size)
 {
 #if defined(DEBUG)
     if (bypassHostAllocator())
     {
         free(block);
         return;

```

|Build|Kind|Timeline Record|
|---|---|---|
|[581427](https://dev.azure.com/dnceng/public/_build/results?buildId=581427)|PR https://github.com/dotnet/runtime/pull/33701|Run tests/scripts/format.py|
|[581230](https://dev.azure.com/dnceng/public/_build/results?buildId=581230)|PR https://github.com/dotnet/runtime/pull/32592|Run tests/scripts/format.py|
|[581302](https://dev.azure.com/dnceng/public/_build/results?buildId=581302)|PR https://github.com/dotnet/runtime/pull/34275|Run tests/scripts/format.py|
|[581140](https://dev.azure.com/dnceng/public/_build/results?buildId=581140)|Rolling|Run tests/scripts/format.py|

Evaluated 100 builds
Impacted 4 bulids
Impacted 4 jobs

> runfo search-timeline -d runtime -c 100 -pr -v "Format job found errors" -m

**Comment by BruceForstall** [comment]
@erozenfeld Can you please take a look?

**Comment by safern** [comment]
@jkotas was this PR intending to fix this issue? https://github.com/dotnet/runtime/pull/34333

**Comment by jkotas** [comment]
Right

**Comment by ViktorHofer** [comment]
Reopening. We should still investigate why this didn't fail in the PR.

**Comment by jkotas** [comment]
The log from the PR is at https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/580855/logs/132 . It does not have any obvious failures.

**Comment by erozenfeld** [comment]
I think there is a bug in the logic that tries to ensure that a particular version of clang-format and clang-tidy is used and we end up using the version that's installed on the machine. I'll get it fixed.
