### ISSUE TITLE
shell scripts for arm/armel on Tizen

### ISSUE THREAD

**Issue by y-yamshchikov** [dotnet/runtime#34345]
We need more flexible testing shell scripts to allow running tests precompiled with crossgen2 on armel/Tizen.

Now there is hardcoded invocation of crossgen2:
https://github.com/dotnet/runtime/blob/852080ede1527a6c67450b7d7e65823128c700de/src/coreclr/tests/src/CLRTest.CrossGen.targets#L74-L76
so we re-hardcode it locally, which is inconvenient and breaks a sync with the upstream.

We need at least to alter
1) `targetarch` which is `armel` in our case (we build `arm` test artifacts and use `armel` `targetarch` with them)
2) location of `crossgen2.dll` which is in the `CORE_ROOT` in our case
3) `targetos` which is `linux` as we guess for Tizen
4) pass `libclrjit.so` with `jitpath` key
5) maybe pass different set of references denoted with `-r`

How could we properly contribute to considered testing framework?
One of the propositions sounded in our team is to test some of special environment variables and switch to them if any. Is it acceptable way to consider?

@jkotas @alpencolt @gbalykov @kfrolov

**Comment by kfrolov** [comment]
I think jitpath not needed: actually it is needed only in ours setup, but we can put library (or symlink) at right place.

**Comment by kfrolov** [comment]
Also I think `-targetarch=x64` should be just deleted. Architecture should be determined by crossgen itself. I have checked -- it works.

**Comment by y-yamshchikov** [comment]
> I think jitpath not needed: actually it is needed only in ours setup, but we can put library (or symlink) at right place.

Does your proposition about jitpath actually work?

**Comment by kfrolov** [comment]
```
sysop@debian:~/clr$ ./corerun crossgen2/crossgen2.dll "-r:*.dll" -o:fibsharp.ni.dll fibsharp.dll
Emitting R2R PE file: /home/sysop/clr/fibsharp.ni.dll

sysop@debian:~/clr$ ./corerun fibsharp.ni.dll 10
55

sysop@debian:~/clr$ uname -m
armv7l
```

**Comment by davidwrighton** [comment]
Contributions to the testing framework are just like contributions to the rest of the product. Please submit PRs, and we will review. It is possible for some PRs to get missed, so if there is a PR of importance to you, please remind us.

With regards to this particular ask, tweaking the generated scripts to consume environment variables is reasonable. The general pattern of check for the presence of environment variable, and if they exist, do something special fits with our current infrastructure.
