### ISSUE TITLE
Prolog code don't initialize all 16 bytes of struct in multi-reg scenario

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#34359]
We don't completely initialize the memory location used to store result struct that is later returned through multi-reg.

 Running [ArrayAsSpanStartLength](https://github.com/dotnet/performance/blob/8aed638c9ee65c034fe0cca4ea2bdc3a68d2a6b5/src/benchmarks/micro/libraries/System.Memory/Constructors.cs#L83) generates following code. Here `[V02 tmp1]` is a 16-byte struct. We are just initializing first 8 bytes of the memory location in prolog and saves 12 bytes later-on, leaving upper 4 bytes unchanged. The prolog should be `stp xzr, xzr, [fp, #16]`.

```asm

;  V02 tmp1         [V02    ] (  2,  4   )  struct (16) [fp+0x10]   do-not-enreg[XSBR] multireg-ret must-init addr-exposed "Return value temp for multireg return."
...
...

G_M43267_IG01:
        A9BE7BFD          stp     fp, lr, [sp,#-32]!
        910003FD          mov     fp, sp
        F9000BBF          str     xzr, [fp,#16] // [V02 tmp1]    # <== Zero out 8 bytes starting offset 16.
                                                ;; bbWeight=1    PerfScore 2.50
G_M43267_IG02:
        F9400400          ldr     x0, [x0,#8]
        B40001C0          cbz     x0, G_M43267_IG06
                                                ;; bbWeight=1    PerfScore 4.00
G_M43267_IG03:
        B9400801          ldr     w1, [x0,#8]
        2A0103E1          mov     w1, w1
        F100283F          cmp     x1, #10
        54000143          blo     G_M43267_IG06
                                                ;; bbWeight=0.50 PerfScore 2.50
G_M43267_IG04:
        91004000          add     x0, x0, #16
        52800141          mov     w1, #10
        910043A2          add     x2, fp, #16   // [V02 tmp1]
        F9000040          str     x0, [x2]           # <===== Write bytes 16...23
        B9000841          str     w1, [x2,#8]        # <===== Write bytes 24...27
        F9400BA0          ldr     x0, [fp,#16]  // [V02 tmp1]
        F9400FA1          ldr     x1, [fp,#24]  // [V02 tmp1+0x08]
                                                ;; bbWeight=1    PerfScore 7.50
G_M43267_IG05:
        A8C27BFD          ldp     fp, lr, [sp],#32
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
G_M43267_IG06:
        97E65C22          bl      System.ThrowHelper:ThrowArgumentOutOfRangeException()
        D43E0000          bkpt
                                                ;; bbWeight=0    PerfScore 0.00

```

category:correctness
theme:prolog-epilog
skill-level:intermediate
cost:medium

**Comment by jkotas** [comment]
Why is this a problem? It looks by design. We do not guarantee that padding is zero-initialized.

**Comment by kunalspathak** [comment]
I see. But then how do we guarantee to return correct result? What if there is garbage value in upper 4 bytes? Is it even possible to have garbage value?

**Comment by jkotas** [comment]
The padding in the return value can be garbage. The calling code should not depend on the padding to be zero-initialized.

**Comment by EgorBo** [comment]
Wonder if can use a SIMD here to clear all 16 bytes including padding (I understand we don't have to) at once.

**Comment by BruceForstall** [comment]
In this code:
```
add     x2, fp, #16   // [V02 tmp1]
str     x0, [x2]           # <===== Write bytes 16...23
str     w1, [x2,#8]        # <===== Write bytes 24...27
ldr     x0, [fp,#16]  // [V02 tmp1]
ldr     x1, [fp,#24]  // [V02 tmp1+0x08]
```
we should be able to forward-substitute the `add` into the addressing mode (since `x2` is subsequently unused), giving:
```
str     x0, [fp,#16]           # <===== Write bytes 16...23
str     w1, [fp,#24]        # <===== Write bytes 24...27
ldr     x0, [fp,#16]  // [V02 tmp1]
ldr     x1, [fp,#24]  // [V02 tmp1+0x08]
```
then the question is whether we can omit the store/load entirely. given we store `w1` and load `x1`, does that mismatch block us? Can we know that nobody else wrote to the upper 4 bytes of the struct in memory and we don't need to load it? The zero init question might not be relevant to answering this.

**Comment by kunalspathak** [comment]
sounds good to me.
