### ISSUE TITLE
Building corefx 3.1 on Windows and Linux

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#34369]
Is it possible and absolutely safe to build even "Linux" flavor of corefx (https://github.com/dotnet/corefx/tree/release/3.1) from Windows machine? As it says its cross platform. I could build independently on both platforms and use it without any issue. But was wondering if its possible to build Linux also from Windows only. May be "build" command has option to build for Linux also from Windows??

**Comment by stephentoub** [comment]
You can use WSL on Windows.

**Comment by deokershesh** [comment]
Thanks @stephentoub for quick response. While WSL could be an option, is there any way directly from corefx command to provide option to build Linux? I guess not! For example: After creating clone of "corefx", I simply execute "build" to do the build, may be "build <some options>" exist to build for Linux (cross platform also!).

**Comment by stephentoub** [comment]
You could build the managed components, but you won't be successful in building the native components, which would be needed.

**Comment by safern** [comment]
You can also use a docker container to build it, so long it has al the prereqs in place.

**Comment by danmosemsft** [comment]
This seems answered.

**Comment by deokershesh** [comment]
@stephentoub, Yes, I plan to build only the managed components , to be precise only "corefx" repository from https://github.com/dotnet/corefx/tree/release/3.1 (to be more precise corefx/src/System.Data.Odbc/src folder ) which is all managed code. How do I achieve the same for Linux from Windows machine? What command options do I use along with "build" command?

**Comment by deokershesh** [comment]
By the way, I am already using Ubuntu VM image to do exclusive Linux build, but since .NET Core says "Cross Platforms", I was wondering if there is way to build from single platform (let say from Windows) across all support platforms for .NET Core.

**Comment by stephentoub** [comment]
> since .NET Core says "Cross Platforms", I was wondering if there is way to build from single platform (let say from Windows) across all supported platforms for .NET Core.

The cross-platform nature is about apps that run on the platform, not about building the platform.

> to be more precise corefx/src/System.Data.Odbc/src folder

After you've built from root once, inside that src folder, do `dotnet msbuild /p:OSGroup=Linux`.

**Comment by deokershesh** [comment]
Thanks stephentoub, 
Tried following and works pretty well, I can do Windows build from Linux and vice versa. This is only for component builds, still for some reason "build" doesn't provide option to do at the top level (for all components).

   dotnet msbuild  /t:rebuild -v:n /P:Configuration=netcoreapp-Linux-Release
   dotnet msbuild  /t:rebuild -v:n /P:Configuration=netcoreapp-Windows_NT-Release
   dotnet msbuild  /t:rebuild -v:n /P:Configuration=netcoreapp-Linux-Debug
   dotnet msbuild  /t:rebuild -v:n /P:Configuration=netcoreapp-Windows_NT-Debug
