### ISSUE TITLE
Explicit marshalling indication of return types doesn't work with delegates

### ISSUE THREAD

**Issue by nxrighthere** [dotnet/runtime#34367]
.NET Core 3.1.200 (x64), Windows 10.

`[return:MarshalAs(UnmanagedType.I1)]` attribute has no effect on return types of delegates converted from function pointers with `GetDelegateForFunctionPointer()` or using a custom IL generator with `calli` opcode. In my case, a boolean from native side is always `true` on the managed side.

`[MarshalAs(UnmanagedType.I1)]` attribute on parameters seems to work fine.

Example:
```cpp
// Native code
bool Test(bool value) {
  return value;
}
```

```csharp
// Managed code
[return:MarshalAs(UnmanagedType.I1)]
delegate bool Test([MarshalAs(UnmanagedType.I1)] bool value);
```

**Comment by nxrighthere** [comment]
CC @AaronRobinsonMSFT @jkoritzinsky

**Comment by nxrighthere** [comment]
Using `byte` instead of `bool` as a return type on the managed side without marshalling works fine.

**Comment by nxrighthere** [comment]
### Area Owners

@AaronRobinsonMSFT @jkoritzinsky

**Comment by jeffschwMSFT** [comment]
@jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
@nxrighthere I've been unable to reproduce this. I confirmed in the IL Stub generator logic that `delegate` types adorned with `[return: MarshalAs(...)]` are respected in main branch.

Please let us know if there is some confusion here.
