### ISSUE TITLE
CoreCLR tests on Mono runtime : crash running Interop/ICustomMarshaler/ConflictingNames/SameNameDifferentAssembly/SameNameDifferentAssembly.sh

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#34372]
Crash seen when running the following CoreCLR test on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/ConflictingNames/SameNameDifferentAssembly/SameNameDifferentAssembly.sh”

Crash report :

 =================================================================
          External Debugger Dump:
          =================================================================
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/ConflictingNames/SameNameDifferentAssembly/SameNameDifferentAssembly.sh: line 282: 77278 Abort trap: 6           $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/Reports/Interop.ICustomMarshaler/ConflictingNames/SameNameDifferentAssembly/SameNameDifferentAssembly.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun SameNameDifferentAssembly.dll ''
          * Assertion at /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/mono/metadata/marshal-ilgen.c:93, condition `method' not met, function:get_method_nofail, Could not lookup method GetCustomMarshalerInstance in Marshal
          
          
          =================================================================
          Native Crash Reporting
          =================================================================
          Got a abrt while executing native code. This usually indicates
          a fatal error in the mono runtime or one of the native libraries 
          used by your application.
          =================================================================
          
          =================================================================
          Native stacktrace:
          =================================================================
          0x10fa5f4b2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_dump_native_crash_info
          0x10fa01105 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_handle_native_crash
          0x10fa5eabf - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : sigabrt_signal_handler
          0x7fff728f342d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
          0x0 - Unknown
          0x7fff727c8a1c - /usr/lib/system/libsystem_c.dylib : abort
          0x10fc1c117 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_assert_abort
          0x10fbfc117 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_log_write_logfile
          0x10fc1c5a5 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_g_logv_nofree
          0x10fc1c72f - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_assertion_message
          0x10fb9b340 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_mb_emit_auto_layout_exception
          0x10fb91d98 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : emit_marshal_custom_ilgen
          0x10fb1177b - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_emit_marshal
          0x10fb96a96 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : emit_native_wrapper_ilgen
          0x10fb1285c - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_marshal_get_native_wrapper
          0x10f9830f8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_method_to_ir
          0x10f969507 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : inline_method
          0x10f98e631 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_method_to_ir
          0x10f95a6b9 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mini_method_compile
          0x10f95cbbc - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_inner
          0x10f9609f2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_with_opt
          0x10f964993 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_runtime_invoke
          0x10fb3a2c8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_invoke_checked
          0x10fb40645 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_exec_main_checked
          0x10f9bf02c - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_exec
          0x10f9c2126 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_main
          0x10fa3b589 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monovm_execute_assembly
          0x10f919896 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun : _Z22ExecuteManagedAssemblyPKcS0_S0_iPS0_
          0x10f91818d - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun : main
          0x7fff726fa7fd - /usr/lib/system/libdyld.dylib : start
          0x2 - Unknown
          
          =================================================================
          Telemetry Dumper:
          =================================================================
          Pkilling 0x123145325555712x from 0x4755545536x
          Entering thread summarizer pause from 0x4755545536x
          Finished thread summarizer pause from 0x4755545536x.
          
          Waiting for dumping threads to resume
          
          =================================================================
          Basic Fault Address Reporting
          =================================================================
          Memory around native instruction pointer (0x7fff728417fa):0x7fff728417ea  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
          0x7fff728417fa  73 08 48 89 c7 e9 85 a2 ff ff c3 90 90 90 b8 53  s.H............S
          0x7fff7284180a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 6d a2  ...I....s.H...m.
          0x7fff7284181a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....
          
          =================================================================
          Managed Stacktrace:
          =================================================================
          =================================================================
          Expected: 100
          Actual: 134
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/ConflictingNames/SameNameDifferentAssembly/SameNameDifferentAssembly.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.ICustomMarshaler/Interop.ICustomMarshaler.XUnitWrapper.cs(237,0): at Interop_ICustomMarshaler._ConflictingNames_SameNameDifferentAssembly_SameNameDifferentAssembly_._ConflictingNames_SameNameDifferentAssembly_SameNameDifferentAssembly_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by CoffeeFlux** [comment]
Same failure: https://github.com/dotnet/runtime/issues/34374

**Comment by CoffeeFlux** [comment]
CoreCLR [PR](https://github.com/dotnet/coreclr/pull/21606) and [issue](https://github.com/dotnet/runtime/issues/10965) prompting this test, though they aren't what's directly causing the crash here.

The problematic line is this, as that method does not exist in our netcore implementation of Marshal:
```
		get_instance = get_method_nofail (Marshal, "GetCustomMarshalerInstance", 2, 0);
```

I assume the Marshal managed implementation changed to use more shared code but the native side wasn't updated to reflect that. I'm not sure what all the changes were or how much the native side needs adjustment.
