### ISSUE TITLE
Publish blob checksums to BAR

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3438]
In 2.1/2.2, ProdCon infra generated these checksums. For 3.0, Core-Setup should generate and publish them to BAR so they show up as shipping files when Darc assembles a release.

@leecow, @dleeapho, it's possible I didn't understand the conclusion in the build drop thread, but I think this is the followup work for those checksums.

**Comment by NikolaMilosavljevic** [comment]
@mmitche do you know if this is still necessary? Feel free to close if not needed anymore.

**Comment by mmitche** [comment]
This has been resolved. I see checksums in the outputs.
