### ISSUE TITLE
Should we still run Microsoft.DotNet.CodeAnalysis for libraries?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#34407]
from @ericstj in https://github.com/dotnet/runtime/pull/33553#discussion_r401210927:

> Do we even care about this analyzer any more? It was particularly helpful when porting code that was designed for desktop and making it work for AppX, but I wonder if its even relevant (especially since we just baseline all the failures).

cc @safern @anipik @joperezr

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/33867

**Comment by ViktorHofer** [comment]
Thanks, closing as duplicate.
