### ISSUE TITLE
JsonSerializer reports the wrong max depth in exception message

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/runtime#34406]
The default value for `JsonSerializationOptions.MaxDepth` is 0, which is a special value meaning "use the default" (which is 64)

But when a cycle is detected, the error message reports that the max depth is 0, which is quite confusing. Since I didn't think I had a cycle in my object graph, I initially thought I had accidentally set the MaxDepth to 0.

> System.Text.Json.JsonException : A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.

It should probably report the *effective* max depth.

**Comment by danmosemsft** [comment]
Do you want to offer a PR?

**Comment by thomaslevesque** [comment]
@danmosemsft sure
