### ISSUE TITLE
Nullability issues with latest arcade update which updates the compiler

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#34417]
I don't have the errors anymore but it's easy to repro by upgrading the Arcade SDK.

cc @safern

**Comment by GrabYourPitchforks** [comment]
The nullability problems that were affecting us previously should be resolved. But we can't remove this line just yet, as it seems to trip an assert within Roslyn itself, resulting in a build failure. See https://github.com/dotnet/roslyn/issues/44000 for more information.

**Comment by jcouv** [comment]
https://github.com/dotnet/roslyn/issues/44000 was fixed. New build should be forthcoming.

**Comment by safern** [comment]
@GrabYourPitchforks thanks for working on this, ok to assign to you instead?

**Comment by GrabYourPitchforks** [comment]
Sure, assign me. Per a comment on the other PR I'll pin our toolset to the latest Roslyn nightlies. Will leave this tracking issue open so that once the fixed build makes its way through to Arcade, we can remove our override entirely.

**Comment by safern** [comment]
Makes sense to me, thanks for working on this 😄

**Comment by ViktorHofer** [comment]
@GrabYourPitchforks FYI I think an arcade update is in with a new compiler.

**Comment by GrabYourPitchforks** [comment]
Great! I'm heads-down on other work right now, but if anybody wants please feel free to reassign this issue to yourself. Otherwise I'll get to it when I get some cycles again.
