### ISSUE TITLE
Enable FreeBSD Core-Setup builds

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3443]
Due to https://github.com/dotnet/core-setup/issues/4949, the FreeBSD leg was disabled. The infra issues should be fixed now.

CoreFX needs to start building FreeBSD again so Core-Setup can pull in the packages: https://github.com/dotnet/corefx/pull/34869.

PRs related to disabling:
* https://github.com/dotnet/core-setup/pull/5035 (removes build leg)
* https://github.com/dotnet/core-setup/pull/5036 (fixup for build leg removal)
* https://github.com/dotnet/core-setup/pull/5055 (removes FreeBSD RID)

Related (not a prereq): Enabling FreeBSD in Core-SDK is tracked by https://github.com/dotnet/core-sdk/issues/248.

---

When we have time to implement this on the core-setup side, the plan is to ping @safern to turn it on in corefx. (This may involve downgrading the version of core-setup that corefx uses to one that included the FreeBSD leg.) Then we turn on the core-setup FreeBSD leg, then corefx uptakes the new core-setup build.

**Comment by NikolaMilosavljevic** [comment]
Stale issue - closing.
