### ISSUE TITLE
Dotnet tools not found when using xargs

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#3444]
@jonathann92 commented on [Tue Feb 05 2019](https://github.com/dotnet/cli/issues/10714)

Hi my use case is that I have multiple test projects in one folder and I would like to run all the unit tests. I am using coverlet dotnet tool to run the unit tests and gather code coverage information.

## Steps to reproduce
```
dotnet tool install -g dotnetsay --version 2.0.0 # install dotnetsay
dotnetsay # should output something
echo hi | xargs dotnetsay # this will output "xargs: dotnetsay: No such file or directory"
which dotnetsay # this outputs nothing. But it should output the dotnet tools path
```

## Expected  behavior
"echo hi | xargs dotnetsay" should run the dotnetsay tool
"which dotnetsay" should print out the dotnet tools path

## Actual behavior
"echo hi | xargs dotnetsay"  will output "xargs: dotnetsay: No such file or directory"
"which dotnetsay" prints out nothing
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.503 [/usr/local/share/dotnet/sdk]
  2.2.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---

@livarcocc commented on [Wed Feb 06 2019](https://github.com/dotnet/cli/issues/10714#issuecomment-461099791)

@wli3

**Comment by elinor-fung** [comment]
I think this should be covered by https://github.com/dotnet/sdk/issues/23165 and https://github.com/dotnet/sdk/issues/22214, which are about the issues that come with the installer putting the non-expanded `~/.dotnet/tools` in the path.
