### ISSUE TITLE
System.Text.Json.Serialization.JsonStringEnumConverter isn't linker-safe

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#34449]
Most other converters in S.T.J. (as far as I know) are safe because their default constructors are referenced statically. However, if you use `JsonStringEnumConverter` like this:

```cs
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MyEnum { A, B, C }
```

then there is no static reference to `JsonStringEnumConverter`'s default constructor, so the linker will strip it out. Then at runtime it will fail when `JsonSerializerOptions.GetConverterFromAttribute` tries to call `Activator.CreateInstance(converterType)` (where `converterType = typeof(JsonStringEnumConverter)`). This was originally reported at https://github.com/dotnet/aspnetcore/issues/19086

For Blazor 3.2.0, we'll put in a workaround into Blazor's built-in linker config. However it would make sense to fix the underlying issue in S.T.J. in the longer term.

### Suggested fix

Either `System.Text.Json.dll` should embed its own linker config file preserving the constructors for all converter types, or consider extending the set of types listed in `JsonSerializerOptions.DefaultSimpleConverters` to include an instantiation of `JsonStringEnumConverter` (or have any other static reference to its constructor).

This applies to all converter types that may be used at runtime. The only one I know of that's causing a problem is `JsonStringEnumConverter`, but I didn't exhaustively check that all the others are linker-safe too.

**Comment by stephentoub** [comment]
cc: @eerhardt

**Comment by eerhardt** [comment]
Another potential way to fix this is to add the correct dataflow analysis annotations (https://github.com/mono/linker/pull/988) to JsonConverter. Using the current names in that proposal, all we would need to add `[DynamicallyAccessedMembers(MemberKinds.DefaultConstructor)]` to `JsonConverterAttribute`, which would tell the linker to keep the default constructor on any type passed into `JsonConverter`.

/cc @vitek-karas @MichalStrehovsky @sbomer

**Comment by MichalStrehovsky** [comment]
Yes, we'll want to solve this through annotations - the fact that the other converters have their constructor rooted from elsewhere is hardly a contract one could rely on: they just _happen to work right now_. We are working on a linking solution that would let us guarantee things work after linking by construction (as opposed to "working thanks to luck").

**Comment by stephentoub** [comment]
For reference:
https://github.com/dotnet/runtime/blob/d59f143221bfa500fe2b974827dcb47eb4ce327c/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactory.cs#L28-L46
https://github.com/dotnet/runtime/blob/4a804959512a76556add344d998f3fc9ca9513e8/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectConverterFactory.cs#L25-L27
https://github.com/dotnet/runtime/blob/0e0e852e83d5f30dfeeef7ac4999873ee10f9a4b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverterFactory.cs#L21-L23
https://github.com/dotnet/runtime/blob/0e0e852e83d5f30dfeeef7ac4999873ee10f9a4b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/KeyValuePairConverterFactory.cs#L22
https://github.com/dotnet/runtime/blob/0e0e852e83d5f30dfeeef7ac4999873ee10f9a4b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonStringEnumConverter.cs#L57-L59
