### ISSUE TITLE
Missing Socket.UseOnlyOverlappedIO functionality?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#34458]
This comment in the UseOnlyOverlappedIO setter suggests it's a nop because we don't support DuplicateAndClose:
https://github.com/dotnet/runtime/blob/15ec69e47b4dc56098e6058a11ccb6ae4d5d4fa1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L325-L329

But DuplicateAndClose was implemented here:
https://github.com/dotnet/runtime/pull/1858

Either the setter needs to be implemented, or the comment needs to be updated.

**Comment by karelz** [comment]
Triage: Update comment.

**Comment by stephentoub** [comment]
@karelz, you noted that the comment needs to be updated and added an "easy" label, but there's no indication of what the comment should be changed to.

**Comment by antonfirsov** [comment]
This property was used in Framework to prevent the assigning completion ports, to allow sockets being duplicatable after performing (async) operations. The .NET core windows async PAL is based on IOCP all the way, and it's unlikely we want to change this.

We should replace outdated statements in the comment with the explanation above.
