### ISSUE TITLE
System.DirectoryServices.AccountManagement Intermittent COMException 0x800401E4

### ISSUE THREAD

**Issue by los93sol** [dotnet/runtime#34466]
I'm really not sure where to go with this one.  We have an aspnetcore app that has a login page with some that authenticates the user against AD and builds a ClaimsPrincipal to sign them in.  We have the site hosted on Windows Server 2016 in IIS using a domain account on the app pool.  Things generally work fine, but every once in awhile we see users become unable to log in.  We get the following in our logs....
```
System.DirectoryServices.AccountManagement.PrincipalOperationException: Creating an instance of the COM component with CLSID {080D0D78-F421-11D0-A36E-00C04FB950DC} from the IClassFactory failed due to the following error: 800401e4 Invalid syntax (0x800401E4 (MK_E_SYNTAX)).
 ---> System.Runtime.InteropServices.COMException (0x800401E4): Creating an instance of the COM component with CLSID {080D0D78-F421-11D0-A36E-00C04FB950DC} from the IClassFactory failed due to the following error: 800401e4 Invalid syntax (0x800401E4 (MK_E_SYNTAX)).
   at System.DirectoryServices.AccountManagement.ADStoreCtx.LoadDomainInfo()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.get_DnsForestName()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOf(Principal p)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOf(Principal p)
   at System.DirectoryServices.AccountManagement.Principal.GetGroupsHelper()
   at System.DirectoryServices.AccountManagement.Principal.GetGroups()
```
We have also witnessed that once this occurs even once the only way to get things working again is to cycle the app pool.  If users are still logged in then things continue to work as expected.

Even more interesting is that our code validating the username/password against AD does work, but as soon as we go to get the users groups to build their claims out we receive the above error.

Unfortunately, the error is quite cryptic and we have been unable to track down the root cause as we are unable to repro the issue reliably, sometimes it happens once ever few days, sometimes it's once every few weeks.

Searching for the exact error yields quite a few results and lots of users suggesting to enable LoadUserProfile in IIS, we have tried that and the issue persisted.  We have also pointed the code directly at a specific DC and the issue still persisted.  Additionally, it seems this is somewhat of a known issue among users as various articles say it's something that just happens from time to time with AD/LDAP and you just go bounce the app pool to get things rolling again, which is hardly a reasonable solution.

Not sure where to go to further debug this, any help/pointers would be greatly appreciated.

**Comment by los93sol** [comment]
I was able to get a little closer to figuring this out.  In our case we have the same domain account setup on multiple app pools.  If I am logged onto two sites and publish one of them I get errors in event viewer about the registry leaking a user file and then logging out and back into the other app fails, but the one just published works without issue.  I did find two places that weren’t properly disposing from DirectoryServices so I’m testing that now to see if that was causing things to be held when they shouldn’t.

**Comment by los93sol** [comment]
The missing using a did not resolve it, however setting Load User Profile to true on all the app pools with the shared identity did resolve the issue...I guess this can be closed but I’d like to understand the underlying issue and any implications of making this change.

**Comment by danmosemsft** [comment]
@los93sol unfortunately we do not have recent expertise in this code. It is unlikely we can help you in the near term. Since you have gotten unblocked, I am going to close this and perhaps it will help others.
