### ISSUE TITLE
Windows installers need accessibility testing

### ISSUE THREAD

**Issue by dleeapho** [dotnet/runtime#3446]
Cribbing from @merriemcgaw
-	Narrator and NVDA (there may be more issues that we are aware of here)
-	High Contrast – this one is pretty big. We have to change colors to particular system defined ones when we get the message from Windows. I don’t know how hard that will be to do in the chainer.
-	Tab Order must be logical
-	I know HDPI is out of the question realistically, but confirm that the magnifier app works. 
-	UIA Hierarchy must be correct and make sense.

**Comment by NikolaMilosavljevic** [comment]
Closing - this was for 3.0 and 3.1. @NikolaMilosavljevic please open a new issue after discussing with Fundamentals owners.
