### ISSUE TITLE
Build System.IO.Packaging against netstandard2.1

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/runtime#34476]
Related: https://github.com/dotnet/wpf/issues/2022

- `DirectWriteForwarder.dll` calls into `[System.IO.Packaging]System.IO.FileFormatException([netstandard2.0]System.Uri))`
- `System.Printing.dll` calls into `System.IO.Packaging.Package::Open(string, [netstandard2.0]System.IO.FileMode)`
 
In turn, this results in each of the above assemblies having references to both netstandard2.1 (reference from `Microsoft.NetCore.App`) and netstandard2.0. 

I don't see any harm in the current state - is there a reason why we should try to eliminate one of these references ? 

Also, can we consider building `System.IO.Packaging` against `netstandard2.1` ? 

/cc @dotnet/wpf-developers

**Comment by danmosemsft** [comment]
@carlossanlop (I had bot typo..)

**Comment by joperezr** [comment]
> I don't see any harm in the current state - is there a reason why we should try to eliminate one of these references ?

No, netstandard.dll facade in Netcoreapp should be compatible to both netstandard2.0 and netstandard2.1 (at least the facade we have in NCA 3.0 and onward) so this is totally a supported scenario and something we don't really should have to worry about.

> Also, can we consider building System.IO.Packaging against netstandard2.1 ?

In runtime we usually try not to cross-compile when it is not necessary as that would just increase package size and NuGet cache footprint so we only do it whenever we are either exposing new API on a newer TFM, or using/depending on implementation or API surface that is only available on newer TFMs. For System.IO.Packaging that is not the case, as we don't really can benefit of anything present in netstandard2.1 (and not in netstandard2.0) for the implementation nor do we want to add additional API surface and of course we wouldn't be able to move from netstandrd2.0 to netstandard2.1 as this would just drop support for a lot of frameworks, so there is really no point of just increasing package sizes as netsandard2.1 fully supports netstandard2.0 assemblies.

**Comment by joperezr** [comment]
I'm closing this issue for now given the above response, but @vatsan-madhavan feel free to reopen if you have any follow-up questions or comments.
