### ISSUE TITLE
Variable is no longer available after Edit and Continue on .NET Framework x86

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/runtime#34487]
**Repro steps:**
1. Start debugging the following app on **.NET Framework x86**:
```csharp
static void Main()
{
   int a = 0; // breakpoint here
   List<int> list = MyList;
   return; // breakpoint here
}

static List<int> MyList => new List<int>(new int[]{ 1, 2, 3 });
```
2. Stop at breakpoint and add a new line somewhere in `Main()`;
3. Press F5 and stop at second breakpoint.

**Expected**
Locals window will show up value of `a` and `list`.

**Actual**
`list` will show up with an error message:
_The runtime is unable to evaluate this expression._

* When getting the local variable through [ICorDebugILFrame.GetLocalVariable()](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugilframe-getlocalvariable-method) with index **1**, the CLR returns a `CORDBG_E_CLASS_NOT_LOADED` error.

**Remarks**
- I was able to reproduce this regardless of the .NET Framework version targeting **x86**;
- The issue **does not repro** if we modify the method for something like this:
```csharp
static void Main()
{
   int a = 0; // breakpoint here
   List<int> list = MyList;
   a = list.Count;
   return; // breakpoint here
}
```

**Comment by isadorasophia** [comment]
@tmat Could this issue have anything to do with Roslyn? It looks like the variable is being optimized away, it doesn't repro on .NET Core or .NET Framework x64.

**Comment by tommcdon** [comment]
Since this issue is for .NET Framework and does not reproduce on .NET Core, I've moved this issue to internal Bug# 1092771

**Comment by tmat** [comment]
@isadorasophia If it doesn't repro on any other .NET then it's unlikely Roslyn issue since we don't emit platform specific IL/metadata/PDB.
