### ISSUE TITLE
Enable xUnit1024 analyzer rule

### ISSUE THREAD

**Issue by alexvy86** [dotnet/runtime#34503]
Rule 1024 in the xUnit analyzers looks for test methods that have overloads and flags them as compilation errors. Right now it is [explicitly disabled](https://github.com/dotnet/runtime/blob/221f869e9bac3cafcfe6bd35d062e2fbfe8accba/eng/CodeAnalysis.ruleset#L339), even though [it is important because different test runners can behave differently when they encounter overloads for a test method](https://github.com/xunit/xunit/issues/1361#issuecomment-314886134). E.g., xUnit's console runner doesn't seem to mind, but the VS runner gets confused and tests end up failing:

![image](https://user-images.githubusercontent.com/716334/78376863-837f7780-7594-11ea-8e1a-635c40000828.png)

![image](https://user-images.githubusercontent.com/716334/78376876-89755880-7594-11ea-83e2-1f979df94d99.png)

Per the discussion [here](https://github.com/dotnet/runtime/issues/31823) I'm creating this issue to track the renaming of test methods across all projects in this repo, so the rule can be enabled.

**Comment by ViktorHofer** [comment]
cc @stephentoub
