### ISSUE TITLE
Eliminate the use of properties defined in targetframework.props

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#34525]
We moved all the properties depending on targetFramework to targetframework.props.
We should now work on removing these properties from all .props file and csprojs as tfm derived properties should only be in .targets file.

cc @ericstj @ViktorHofer

**Comment by ericstj** [comment]
Please focus on doing this now.  We're seeing too many related issues due to this problem.

**Comment by Anipik** [comment]
Sure i can move this up the priority list
