### ISSUE TITLE
Validation of COM Host library scenarios

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#3452]
The current COM Host has no testing associated with it due to the lack of SDK support. That support (https://github.com/dotnet/sdk/pull/2814) is slated to be inserted once this work is committed. When SDK support is finally added we need some tests for COM Host.

- [x] Update the core-setup authoring to deploy the new comhost library with the apphost binary
- [x] Isolation of COM assemblies
- [x] Validation of respect for `.clsidmap`
    - [x] Activation via [`CLSID`](https://docs.microsoft.com/windows/win32/com/clsid-key-hklm) - [`CoCreateInstance()`](https://docs.microsoft.com/windows/win32/api/combaseapi/nf-combaseapi-cocreateinstance)
    - [x] Activation via [ProgID](https://docs.microsoft.com/windows/win32/com/-progid--key) - [`CLSIDFromProgID()`](https://docs.microsoft.com/windows/win32/api/combaseapi/nf-combaseapi-clsidfromprogid)
- [ ] Validation of coordination between existing CLR instance and new
    - [x] Multiple COM servers activation 
    - [ ] Managed application activating managed COM server
        - [ ] Framework dependent app
        - [ ] Self-contained app
- [x] Validate the transmission of error details in an `IErrorInfo` instance on failure of COM server activation

**Comment by agocke** [comment]
@AaronRobinsonMSFT Do you think we're done here for 5.0

**Comment by AaronRobinsonMSFT** [comment]
@agocke I think so. The outstanding checkbox are are for additional testing. We still don't have this coverage but it shouldn't be blocking in .NET 5. I think we should make some more effort in .NET 6 to fill the gaps though. I would move to .NET 6 for now.

**Comment by petarpetrovt** [comment]
Scenario `Managed application activating managed COM server` dosen't work when COM library is a project reference in a executable project. Currently the [AddDepsJsonAndRuntimeConfigToCopyItemsForReferencingProjects](https://github.com/dotnet/sdk/blob/22c4860dcb2cf6b123dd641cc4a87a50380759d5/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L308) target copies the *runtimeconfig.json and *deps.json only if the project generates executable and the runtime thinks its a self-contained but its not. Running the test executable fails with error:
> Retrieving the COM class factory for component with CLSID {GUID} failed due to the following error: 80008093 0x80008093.

Example project structure:
* MyComLibrary (net6.0-windows - EnableComHosting=true, EnableRegFreeCom=true)
* MyComLibraryTester (net6.0-windows - windows forms)

Temporary fix: 
```xml
<Target
    Name="_AddDepsJsonAndRuntimeConfigToCopyItemsForReferencingProjects"
    BeforeTargets="GetCopyToOutputDirectoryItems;_GetCopyToOutputDirectoryItemsFromThisProject">
<ItemGroup Condition="'$(GenerateDependencyFile)' == 'true'">
	<AllItemsFullPathWithTargetPath Include="$(ProjectDepsFilePath)"
		TargetPath="$([System.IO.Path]::GetFileName($(ProjectDepsFilePath)))"
		CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>

<ItemGroup Condition=" '$(GenerateRuntimeConfigurationFiles)' == 'true'">
	<AllItemsFullPathWithTargetPath Include="$(ProjectRuntimeConfigFilePath)"
		TargetPath="$([System.IO.Path]::GetFileName($(ProjectRuntimeConfigFilePath)))"
		CopyToOutputDirectory="PreserveNewest" />
	<AllItemsFullPathWithTargetPath Include="$(ProjectRuntimeConfigDevFilePath)"
		TargetPath="$([System.IO.Path]::GetFileName($(ProjectRuntimeConfigDevFilePath)))"
		CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
</Target>
```

Maybe we should update the condition in `AddDepsJsonAndRuntimeConfigToCopyItemsForReferencingProjects` target to something like `Condition="'$(HasRuntimeOutput)' == 'true' OR '$(EnableComHosting)' == 'true'"`? @agocke @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
> dosen't work when COM library is a project reference in a executable project

@petarpetrovt Yep. This particular scenario is something we haven't invested a lot of effort in. The primary reason is that if one is referencing a managed assembly, then the preferred activation path would be via the typical managed object creation mechanism&mdash;`new Class()`. This of course is also how the classic `CoClass` mechanism worked but under the covers it was/is far more complicated. One of the base assumptions is that if one is activating a managed class via COM then there wouldn't be a reference to the implementation assembly but rather to a PIA. The goal is to keep COM activation independent of managed class activation since it simplifies application composition.

All that aside, is there a specific scenario where it is advantageous to activate a managed COM server via COM activation as opposed to normal managed class creation?
