### ISSUE TITLE
DependencyContextLoaderTests.LoadCanLoadANonEntryAssembly test fails in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#34541]
https://dev.azure.com/dnceng/public/_build/results?buildId=588699&view=logs

Configuration: `net472-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`

```
Microsoft.Extensions.DependencyModel.Tests.DependencyContextLoaderTests.LoadCanLoadANonEntryAssembly [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.DependencyModel/tests/DependencyContextLoaderTests.cs(83,0): at Microsoft.Extensions.DependencyModel.Tests.DependencyContextLoaderTests.LoadCanLoadANonEntryAssembly()
```

cc @eerhardt

**Comment by eerhardt** [comment]
The test is failing in your PR because the proposed change broke it.

https://github.com/dotnet/runtime/pull/33553/files#diff-ac51945fb79648e38d3b69df8dd8bfe7L6

```
    <GenerateDependencyFile>true</GenerateDependencyFile>
```

You are removing that line, which the test needs. The test needs a `deps.json` file generated for it, even when it is running on netfx because it tries loading it.

**Comment by ViktorHofer** [comment]
Thanks. What is the use-case for a deps.json on .NET Framework?

**Comment by eerhardt** [comment]
> What is the use-case for a deps.json on .NET Framework

To be able to get the dependency graph of your application. ASPNET used it to find all the assemblies that referenced the MVC assembly to find all the controller classes. It didn’t need to search assemblies that didn’t reference MVC.

**Comment by ViktorHofer** [comment]
Got it, thanks for the explanation. I assumed generating and using it on .NET Framework isn't common.

**Comment by eerhardt** [comment]
It isn’t common anymore now that aspnet doesn’t support .NET Framework. But it is supported.
