### ISSUE TITLE
Restore internal tools dotnet install binds us to only released versions

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#34546]
The [UseDotnet@2 task](https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/eng/pipelines/common/restore-internal-tools.yml#L6) can only resolve publicly released dotnet SDK versions from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json. This means that we can't update the [sdk attribute in our global.json](https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/global.json#L3) to a non-officially released version:

```
##[section]Starting: Install dotnet 
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.165.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
No matching sdk version could be found for specified version: 5.0.100-preview.3.20170.6 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 5.0.100-preview.3.20170.6 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 5.0
##[error]sdk version matching: 5.0.100-preview.3.20170.6 could not be found
##[section]Finishing: Install dotnet 
```

We should find another way to aquire the dotnet SDK for internal tools restore. Meanwhile I'm hardcoding the version to the latest officially released version.

cc @dotnet/runtime-infrastructure @safern

**Comment by safern** [comment]
@ViktorHofer this was to workaround an issue that NuGet had with the credential manager when doing multiple restores. If we update to the latest SDK, we should be able to remove this step and use the bootstrapped SDK.

**Comment by ViktorHofer** [comment]
Cool. What would the change look like? Do we still need the other two `NuGetAuthenticate@0` and `DotNetCoreCLI@2` tasks?

**Comment by safern** [comment]
Yes. You just need to change the UseDotNet@2 task to use the global.json instead of a specific version. That way if it is already installed it will be a no-op but if it is not, it will install it and add it to the path.


`useGlobalJson: true`

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops

**Comment by ViktorHofer** [comment]
Hmm are we talking about the same thing? It already uses global.json: https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/eng/pipelines/common/restore-internal-tools.yml#L10.

What I'm saying is that this task only accept public released versions, ie 5.0-preview2.

**Comment by safern** [comment]
Yeah, I realized that after I hit submit on the comment, look at my last edit.

> Edit: I just saw it doesn’t support prerelease versions. Then we just need to make sure dotnet is installed and in the path before calling restore internal tools.
If you want we can disable restoring internal tools and I can take a look later in the week.

**Comment by safern** [comment]
Also we can change the UseDotNet task to invoke the arcade script to install dotnet right? I believe there is a way, no?

**Comment by ViktorHofer** [comment]
I downgraded the SDK for now to the latest preview2 release and will try out your suggestion ~tomorrow. Thanks :)

**Comment by ViktorHofer** [comment]
Santiago volunteered to take a look 👍
