### ISSUE TITLE
Allow GT_CNS_DBL to be a CSE candidate

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#34557]
We are currently preventing `GT_CNS_DBL` from being a CSE candidate here: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/optcse.cpp#L3232-L3237. However, we do track the underlying type of a `GT_CNS_DBL` and should be able to use that to differentiate a `TYP_FLOAT` constant from a `TYP_DOUBLE` constant. This is also safe given that `TYP_FLOAT` can be roundtripped through `TYP_DOUBLE`. Likewise, we are blocking `TYP_FLOAT` on x86 directly above that, even though (AFAIK) ryuJIT no longer uses the x87 FPU stack (aside from returns) and does support enregistering both floats and doubles directly.

It may be beneficial to begin allowing these values to be CSE'd and to define IEEE compliant semantics here for things like +/-0, +/-Inf, and NaN handling. `IEEE 754:2019, 10.4 Literal meaning and value-changing optimizations 10.4.0` (and the equivalent section in `IEEE 754:2008`) define the optimizations that are allowed and which still preserve the literal meaning of the source code. Many of these rules are also more flexible given that we don't support `signaling NaN`.

category:cq
theme:cse
skill-level:expert
cost:large

**Comment by BruceForstall** [comment]
cc @briansull

**Comment by briansull** [comment]
I will look into this

**Comment by briansull** [comment]
Fix in progress with #43453

**Comment by briansull** [comment]
Fix in progress with #44419
