### ISSUE TITLE
x86 emitxarch assert '((int)offs < 0) || emitComp->opts.IsOSR()'

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#34576]
When I run this test on x86 checked (latest master)
```

using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Numerics;

class TestStructReturns {
    struct smallStruct {
        public bool a;
        public bool b;
    }

    struct largeStruct {
        public int a;
        public long b;
        public double c;
        public bool d;
        public float e;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static public unsafe void StructFromSStruct2() {
        smallStruct smallS;
        smallS.a = true;
        smallS.b = false;
        largeStruct largeS = Unsafe.As<smallStruct, largeStruct>(ref smallS);
        Debug.Assert((uint)(largeS.a % (UInt32.MaxValue + 1L)) == 1);
    } 
}

class TestStructs {
    public static int Main() {
        TestStructReturns.StructFromSStruct2();        
        return 100;
    }
}
```
I get:
```
Assert failure(PID 23796 [0x00005cf4], Thread: 20260 [0x4f24]): Assertion failed '((int)offs < 0) || emitComp->opts.IsOSR()' in 'TestStructReturns:StructFromSStruct2()' during 'Generate code' (IL size 56)

    File: F:\git\runtime\src\coreclr\src\jit\emitxarch.cpp Line: 1988
    Image: F:\git\runtime\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe
```
Doesn't repro with minopts, tiering is disabled.
The jitdump is attached.
[x86failure.txt](https://github.com/dotnet/runtime/files/4436233/x86failure.txt)

**Comment by sandreenko** [comment]
@AndyAyersMS could you please take a look? Is the test invalid? Should Roslyn reject to compile it maybe?
The assert mentions OSR, so you probably touched that place recently.

cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
> where did this test case come from? We've had similar issues in the past with invalid tests, but I don't think we've seen one of those cases in a while.

I wrote it to test my struct changes ([test](https://github.com/dotnet/runtime/blob/2e00f954a2ce51f3263b430caffad7fa30f8831d/src/coreclr/tests/src/JIT/Directed/StructABI/structreturn.cs)).

> how unsafe something is - i.e. when does it cross the line from unsafe to invalid?
Yes, looks like I do not see that border, for example, can we reinterpreter int as long? Should ECMA state that or how can we determine that?

> I don't think this test is valid; you can't safely reinterpret a small struct as a larger one -- in this case, the "reinterpreted" larger struct's upper fields reach off the end of the stack frame.

I have other cases of such casts, should jit behavior be consistent across platforms/tests for these cases or is it undefined behavior?
Looks like we do local reordering, otherwise `largeStruct ` would be put last on the stack.

**Comment by CarolEidt** [comment]
I don't think the Ecma spec specifically addresses the question of reinterpreting one type as another. But it is fundamentally incorrect to assume that you can load or store a given type from a location of a smaller type. In the past we've had some old tests that accessed an int as a long and although we had people trying to argue that if the test had ever passed it must continue to pass, there's just no way that can be done without unnecessarily padding everything. And, further, no reasonable way to require that the JIT must always lay out the stack in the same order that a previous JIT had done.

**Comment by sandreenko** [comment]
Got it, thanks @CarolEidt, I will delete these cases.

**Comment by sandreenko** [comment]
Note: in System.Text.Json.dll we have such code:
https://github.com/dotnet/runtime/blob/f511ec456f18f5ffa10aca88b29f4d8d644ba1b5/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L74
https://github.com/dotnet/runtime/blob/f511ec456f18f5ffa10aca88b29f4d8d644ba1b5/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L107-L113
that in crossgen we compile like `System.Text.Json.Serialization.Converters.EnumConverter1[__Canon][System.__Canon]:Read(byref,System.Type,System.Text.Json.JsonSerializerOptions):System.__Canon:this`, so `T = Canon = ref = 8 byte type`, so when we do this cast we are retyping int (4 byte) as ref(8 byte):
```
               [000151] *-CXG-------              *  IND       ref   
               [000363] ------------              \--*  ADDR      byref 
               [000364] -------N----                 \--*  LCL_VAR   int   (AX) V08 loc4  
```
It is compiling without warnings/errors nowadays.
