### ISSUE TITLE
How change DOTNET_BUNDLE_EXTRACT_BASE_DIR

### ISSUE THREAD

**Issue by denispasternak** [dotnet/runtime#34572]
Please tell me how I can change the DOTNET_BUNDLE_EXTRACT_BASE_DIR variable, instead of "% temp%.net\application\id", set to "% LOCALAPPDATA%.net\application\id" (system variable), will use app only on Windows OS. So that the directory is not cleared by the system or system cleaning applications.

Thanks!

**Comment by swaroop-sridhar** [comment]
@denispasternak  you can set the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable on the machine where the app is run.

**Comment by denispasternak** [comment]
> @denispasternak you can set the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable on the machine where the app is run.

this means that I have to change the system variable% temp%

**Comment by denispasternak** [comment]
Found how to, thank you.
Mast create net environment variabl
