### ISSUE TITLE
[mono] Portable threadpool does not support async IO eg ThreadPoolBoundHandle on Windows

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34582]
A lot of `System.IO.Pipes.Tests` fail with `System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.` on windows.
The example of the output:
```
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerInOutRead_ClientInOutWrite.OperationsOnDisconnectedClient [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\PipeStream.Windows.cs(46,0): at System.IO.Pipes.PipeStream.InitializeAsyncHandle(SafePipeHandle handle)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\PipeStream.cs(101,0): at System.IO.Pipes.PipeStream.InitializeHandle(SafePipeHandle handle, Boolean isExposed, Boolean isAsync)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.Windows.cs(122,0): at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.Windows.cs(49,0): at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.cs(85,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.cs(41,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
    _\src\libraries\System.IO.Pipes\tests\NamedPipeTests\NamedPipeTest.Simple.cs(761,0): at System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerInOutRead_ClientInOutWrite.CreateNamedPipePair(PipeOptions serverOptions, PipeOptions clientOptions)
    _\src\libraries\System.IO.Pipes\tests\NamedPipeTests\NamedPipeTestBase.cs(42,0): at System.IO.Pipes.Tests.NamedPipeTestBase.CreateNamedPipePair()
    _\src\libraries\System.IO.Pipes\tests\NamedPipeTests\NamedPipeTest.Simple.cs(310,0): at System.IO.Pipes.Tests.NamedPipeTest_Simple.OperationsOnDisconnectedClient()
```

The whole namespace will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592

**Comment by danmosemsft** [comment]
@MaximLipnin this is because Mono corelib is not built with `<FeaturePortableThreadPool>true</FeaturePortableThreadPool>`. Should it be? 
cc @kouvel

**Comment by MaximLipnin** [comment]
@danmosemsft Thanks for clarification, but please correct me if I'm wrong - a quick search shows that this flag is [activated](https://github.com/dotnet/runtime/blob/42183b1b86656a348e0b6af7fa7c75072865f759/src/mono/netcore/System.Private.CoreLib/System.Private.CoreLib.csproj#L130) in Mono's SPC

**Comment by kouvel** [comment]
The portable thread pool implementation currently doesn't support `BindHandle`. I guess that Mono would inherit the PNSE implementation here:
https://github.com/dotnet/runtime/blob/893882f27ec509182e32d7bfd31a06f9440a66bf/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L1807-L1810

I guess IO completion stuff may need to be added to the portable implementation on Windows to make `BindHandle` work there, I don't know if Mono has an alternative implementation it can fork to easily at the moment for those. Probably would be best to add that to the portable implementation.

**Comment by marek-safar** [comment]
> <FeaturePortableThreadPool>true</FeaturePortableThreadPool>

This is correct.

Could the tests be guarded with IsBindHandleSupported instead of Windows only or is the BindHandle support something your team can fix? 

I know @jkotas would like to use portable TP for CoreCLR too and this could be a blocker.

**Comment by jkotas** [comment]
> @jkotas would like to use portable TP for CoreCLR too and this could be a blocker.

Adding implementation for IO completion stuff (ie `BindHandle` and friends) is one of the things that will need to be fixed to fully switch to portable TP for CoreCLR on Windows.

To understand the priority: Is Mono going to ship as officially supported on Windows for .NET 5?

**Comment by marek-safar** [comment]
It's not high on our priority list to support IO completion stuff anywhere (including Windows)

**Comment by danmosemsft** [comment]
> To understand the priority: Is Mono going to ship as officially supported on Windows for .NET 5?

I am interested in this too as it helps us understand what to do about these mono-on-Windows bugs. My assumption is that there is value in getting this test pass clean, regardless.

cc @steveisok

**Comment by ericstj** [comment]
Libraries rely on this API in order to create an IO completion ports.  This is necessary for any of our async IO implementations to work on Windows.  I agree with @jkotas here: if you care about running mono on Windows I wouldn't leave this as throwing.

**Comment by jkotas** [comment]
One option to consider is to use Windows OS build-in threadpool that comes with IO completion port support. It is what CoreRT does: https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Threading/ThreadPool.Windows.cs . It comes with trade-offs, e.g. Windows OS build-in threadpool has different heuristics.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by lateralusX** [comment]
> I guess IO completion stuff may need to be added to the portable implementation on Windows to make `BindHandle` work there, I don't know if Mono has an alternative implementation it can fork to easily at the moment for those. Probably would be best to add that to the portable implementation.

@kouvel, any plans to actually implement support in portable thread pool so we can get this working on Mono?

**Comment by kouvel** [comment]
> any plans to actually implement support in portable thread pool so we can get this working on Mono?

Yes I'm planning on adding support for BindHandle in the portable thread pool soon.
