### ISSUE TITLE
coreclr.cmd does not support building CoreCLR tests or generating the CoreRoot layout

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#34603]
As per the title, `.\coreclr.cmd` does not currently support building the coreclr tests (which are built by default by `.\src\coreclr\build.cmd`. Likewise, it does not look to currently support regenerating the `CoreRoot` test layout.

However, using `.\src\coreclr\build.cmd` currently prints the following:
> BUILD: WARNING: This build script is deprecated and will be deleted soon. Use the root build script to build CoreCLR. If you want to build the CoreCLR runtime without using MSBuild, use the build-native.cmd script.

Ideally this would be updated so that native tests can be easily built and so that the test layout can be trivially regenerated without having to rebuild all the tests. My current process for setting up a new branch is frequently:
* `cd runtime`
* `git checkout -b fix-#####`
* `git fetch --all`
* `git reset --hard dotnet/master`
* `.\coreclr.cmd -configuration Release`
* `.\coreclr.cmd -configuration Checked`
* `.\libraries.cmd -configuration Release`
* `.\src\coreclr\build-test.cmd Release`
* `.\src\coreclr\build-test.cmd Checked`

My inner loop is then:
* Make changes
* `.\src\coreclr\build.cmd skiptests generatelayout checked`
* `.\src\coreclr\build.cmd skiptests generatelayout release`
* Run relevant tests
* Get diffs using `dotnet/jitutils`

I build both `checked` and `release` because `dotnet/jitutils` requires it
I use `skiptests` because the coreclr tests take a long time to build and if I've not made changes, rebuilding them is unnecessary
* When I do make changes, I generally just build that one project with the right properties, as I don't want to waste time doing all the up-to-date checks
I use `generatelayout` so that the `CoreRoot` folder is properly laid out with the updated JIT changes

**Comment by jkoritzinsky** [comment]
@tannergooding you can use the build-test.cmd script to just regenerate Core_Root with the `generatelayoutonly` parameter from an updated build, so that should unblock you to move off the old build.cmd script. (full command from the root being `src/coreclr/build-test generatelayoutonly`)

**Comment by tannergooding** [comment]
>  you can use the build-test.cmd script to just regenerate Core_Root with the generatelayoutonly parameter from an updated build, so that should unblock you to move off the old build.cmd script

That doesn't simultaneously rebuild the JIT side though, does it? Ideally I'd also be able to do all this from the repo root without needing to dot off into `.\src\coreclr`...

**Comment by jkoritzinsky** [comment]
It does not do a product build, no. #33183 would give a way to do that.

**Comment by jashook** [comment]
Script has been removed
