### ISSUE TITLE
[Uri] Consider caching PathAndQuery

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#34618]
Uri caches several results that are likely to be accessed again.  It doesn't do so for Uri.PathAndQuery, but this property is used on every request made by SocketsHttpHandler.  We should _consider_ caching it, for scenarios where the same Url is used repeatedly with an HttpClient.  As with any caching, though, we'd want to make sure it was actually worthwhile and didn't negatively impact other important cases.

cc: @scalablecory, @MihaZupan

**Comment by karelz** [comment]
Triage: Helps gRPC scenarios perf.
