### ISSUE TITLE
x64 libraries build error

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#34610]
If I try to build with subsets specified for libraries, lots of different errors show up:
```
./build.sh --clang9 --arch x64 --configuration Release --subsetcategory libraries --subset native-src
```
```
error MSB3245: Could not resolve this reference. Could not locate the assembly "System.Collections". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/z/Dev/runtime/src/libraries/Microsoft.CSharp/src/Microsoft.CSharp.csproj]

error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/z/Dev/runtime/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj]

IDistributedCache.cs(74,72): error CS0246: The type or namespace name 'CancellationToken' could not be found (are you missing a using directive or an assembly reference?) [/home/z/Dev/runtime/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj]

etc.
```

Build without subsets is fine:
```
./build.sh --clang9 --arch x64 --configuration Release --subsetcategory libraries
```

Seems that this is related to `depprojs` and #33553:
https://github.com/dotnet/runtime/blob/986518e2ad9ac431d08ff7effb21fbe1f3aeb3ed/eng/Subsets.props#L61

cc @alpencolt @jkotas

**Comment by ViktorHofer** [comment]
Make sure that you ran -restore once. Currently deprojs only run for the full subsetCategory. We are planning to remove the depprojs so that the upfront restore isn't necessary anymore.

**Comment by safern** [comment]
Also, the error is because you're missing to build the ref assemblies which we use to build the src. So after running `-restore` once you would need to build `native-ref-src` if you haven't built the ref subset yet.

**Comment by gbalykov** [comment]
Thank you, that helped. So, the current working solution is:
```sh
./build.sh --clang9 --arch x64 --configuration Release --subsetcategory libraries --restore
./build.sh --clang9 --arch x64 --configuration Release --subsetcategory libraries --subset native-ref-src --build
```

**Comment by ViktorHofer** [comment]
You could also just do `./build.sh --clang9 --arch x64 --configuration Release --subsetcategory libraries`.

**Comment by gbalykov** [comment]
@ViktorHofer I want to build only specific subsets, e.g. I don't need `packages` and `native` in some cases

**Comment by ViktorHofer** [comment]
Then you are good to go with this: `./build.sh --clang9 --arch x64 --configuration Release --subsetcategory libraries --subset depprojs-native-ref-src` Restore and build is incremental here.

**Comment by gbalykov** [comment]
`depprojs` is not available from the command line and is not listed in the list from `--subset --help`

**Comment by ViktorHofer** [comment]
Oh right. We plan to remove them anyway soon. I'll fix this in the meantime.

**Comment by ViktorHofer** [comment]
They are available now on latest master. Closing as I believe this issue is now fixed.

**Comment by gbalykov** [comment]
Thank you
