### ISSUE TITLE
Dynamic libraries in the microsoft.netcore.app.runtime.ios-x64 package has incorrect identity

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#34637]
Repro:

```shell
otool -l ~/.nuget/packages/microsoft.netcore.app.runtime.ios-x64/5.0.0-*/runtimes/ios-x64/native/*dylib | grep LC_ID_DYLIB -A 2
          cmd LC_ID_DYLIB
      cmdsize 184
         name /Users/runner/runners/2.165.2/work/1/s/artifacts/obj/native/netcoreapp5.0-iOS-Release-x64/System.IO.Compression.Native/libSystem.IO.Compression.Native.dylib (offset 24)
```

This should be something like `@executable_path/libSystem.IO.Compression.Native.dylib`.

CC @akoeplinger

**Comment by filipnavara** [comment]
Not sure what changed but at least on macOS I see the binaries now have identity like `@rpath/libSystem.IO.Compression.Native.dylib` which seems reasonable. Is this still relevant? Or specific to iOS?
