### ISSUE TITLE
Event Logging is incomplete in System.Net.Security.SecureChannel.Decrypt

### ISSUE THREAD

**Issue by frankracis-work** [dotnet/runtime#34635]
System.Net.Security.SecureChannel.Decrypt logs an "Enter" trace event, but does not log the corresponding "Exit" trace event.   

More importantly, this method does not execute NetEventSource.DumpBuffer on the decrypted content.    Using HttpWebRequest on 4.x, this functionality was present as part of System.Net tracing.   I don't see any way of doing this type of tracing with HttpClient.

The pattern is implemented correctly, 30 lines higher in the same file, in Encrypt.    NetEventSource.DumpBuffer is called with the cleartext, and NetEventSource.Exit is called with the result of the encryption. 

If there aren't any philosophical objections to adding this, I could take a shot at submitting the PR.

**Comment by alnikola** [comment]
Triage:
It's a diagnostics code bug, but not a priority now.
We would welcome a PR for this, thank you.

**Comment by wfurt** [comment]
closed by #40998
