### ISSUE TITLE
Can not use Microsoft.Windows.Compatibility 5.0.0-preview.2.20160.6

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#34639]
Microsoft.Windows.Compatibility 5.0.0-preview.2.20160.6 depends on 
```
System.Reflection.Emit (>= 5.0.0-preview.2.20160.6)
System.Reflection.Emit.ILGeneration (>= 5.0.0-preview.2.20160.6)
System.Reflection.Emit.Lightweight (>= 5.0.0-preview.2.20160.6)
```
but these packages do not published on Nuget.org and `dotnet restore` fail.

**Comment by ViktorHofer** [comment]
I believe that was fixed by @mmitche ?

**Comment by iSazonov** [comment]
I downloaded 5.0 Preview2 and tried to move PowerShell Core to the version some minutes ago with the error.

**Comment by ViktorHofer** [comment]
I believe the fix was made in 5.0-preview3.

**Comment by mmitche** [comment]
Yes, fixed i p3 (not released)

**Comment by iSazonov** [comment]
Ok, thanks. It is not critical so close the issue.
