### ISSUE TITLE
[mono] Test failed on windows: System.DirectoryServices.Protocols.Tests.SortRequestControlTests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34679]
`System.DirectoryServices.Protocols.Tests.SortRequestControlTests` fails on windows with `exit code -1073740940`. It happens somewhere in `SortRequestControl.GetValue` method.

The test will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by ericstj** [comment]
This is C0000374‬ STATUS_HEAP_CORRUPTION.
