### ISSUE TITLE
The Build QuickStart for dotnet/runtime has a broken link for running tests from VS

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/runtime#34688]
This README document: https://github.com/dotnet/runtime/blob/master/docs/workflow/building/libraries/README.md, which contains instructions on how to build the runtime.

At the bottom, under "Running tests", it has a link to `https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing-vs.md`, but this link returns a 404. What is the proper location and could the readme be updated?

**Comment by safern** [comment]
Thanks @abelbraaksma -- it seems like the link should point to: https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md#running-tests-from-visual-studio 

Seems like a fallout of merging the docs. Fix: https://github.com/dotnet/runtime/pull/34704

**Comment by abelbraaksma** [comment]
@safern thanks for the quick update!
