### ISSUE TITLE
what's the difference between Windows and Linux?

### ISSUE THREAD

**Issue by egmkang** [dotnet/runtime#34684]
my application is a MMOG GameServer, it runs on linux, but i use Windows to profile and optimize.

on Windows Server 2012 R2, it works well, I don't even need to warm up the program.

but on linux (centos 7.6 64bit), i must run application for a long time, then it works well, Otherwise, the program cannot handle so much requests. 

this link is the application start up within 10 minutes: [https://github.com/dotnet/runtime/issues/34678](https://github.com/dotnet/runtime/issues/34678)

this is a problem, what the difference between Windows and Linux strategy? how can i solve this problem?

.net core 3.1.201
hardware: Intel Xeon Cascade Lake 8255C(2.5 GHz) 32 Core 64G Cloud VM

**Comment by charlesroddie** [comment]
Why don't you aot it with corert?

**Comment by egmkang** [comment]
@charlesroddie it sames like not the JIT problem. running a long time, __pv_queued_spin_lock_slowpath  still cost almost half time .

**Comment by BruceForstall** [comment]
@egmkang Isn't this the same as #34678?

@janvorli This looks like a PAL/Linux kernel issue.

**Comment by egmkang** [comment]
@BruceForstall yes. it's the same problem.

**Comment by BruceForstall** [comment]
I'm going to close this one and let #34678 track the issue.
