### ISSUE TITLE
Optimizing generic math 

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#34681]
Hello,

I have created a simple example in trying to get rid of my IL code to apply generic math routines.
For example I want to simply add two values but with generic behavior.

`public static T AddGeneric<T>(T a, T b);`

Additionally I have added the simple method

`public static float AddScalar(float a, float b) => a+b;`

Interestingly I do not get the same jitted code for 

AddGeneric<float>(10,10) and AddScalar(10,10);

see here: https://gist.github.com/1b4ac5eab741121bb4bceeedbd5841a6

Also my benchmarks differ a bit.

**Comment by EgorBo** [comment]
@msedi sharplab is quite confusing here, when you select "master" it actually uses .NET Framework.
Here is you code for .NET Core: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9BrIAW2KGIAy2YO258BG6poDMTUgyEMA3jQbuGbj94DaAKV4MAHEYLhllAAoMAE8xGAgAMwiEyQhsDABKDIBdL293HwBZGAwdCAATAElxSQji0orqsUkAeTE+CC5cFgBBAHM+2FxcXgUYSq5JXi5pvoZCBnqyqpq2jq7egaGRsbX+XgAvdN5OnLz84jtmJAYAFQYe8vKAHluAPgj77DQ7hmAM87eVzUfKghi8BIMKKxeJJW4ZBgAXkRDBicUSEVwZSgmQBILBBOIAHYofCIhBgAArGBgTIRTHYukU6m0jLYBgAaihWOgTKpNMy/ysgLBEKhaNhnwRyNRMIxHB5OKyIoJ7mJpIy5P5rPpCsZmuZArZnKhet5Bu1goywvxqvBkOh6Lh0pREox01xKtV6qlWpZdIiHot/uNXMDPGDRqFNC93jFjsl8KRrrlSQ4QbxdtBPrJhp1EXTEb9RvZYcLfJD0esttV8bdzuTsqdEVSXD6yprWaYJN9eYDrfbxdZpahA8jrKrsY8ddTUsb9YLY8zXY8OfHAY4Y6HmRHi86g77GUnndFDoXSZlC5SaU9J7ta+3muSqXS69DUOvr8fx67M+bF5TZtyggDhgGkDsV1XHtc0tJ9gNA8DH13eCwJgN8fyzUooAgAB3BgwjwgBRBAVHaE4uAia0vQAX3OL0ihKZYmlqJZGlWMjOm6fpBlUHZxkmaZZnmRZGLY5o9k4zYeOGUYYD2fBDmOU5cjvJgrnIG5PwwB4nmfG8Hh+LSGAAIWXUFgS7dUeg5YyrAJWjqGooA

**Comment by msedi** [comment]
@EgorBo: Thx for the correction. Now it looks much better. The question is if the benchmark result only show a hickup or do you think there is a real problem?
```

|    Method |     Mean |   Error |  StdDev |
|---------- |---------:|--------:|--------:|
| RunCsharp | 365.8 ms | 4.81 ms | 4.01 ms |
|     RunIL | 356.3 ms | 3.70 ms | 3.09 ms |
```

**Comment by EgorBo** [comment]
@msedi can you add `[DisassemblyDiagnoser]` to your benchmark and compare asm for both benchmarks?

**Comment by msedi** [comment]
@EgorBo: The generated code seems to be identical. Here's the code.
Again with some benchmarks

```
|    Method |     Mean |   Error |   StdDev | Code Size |
|---------- |---------:|--------:|---------:|----------:|
| RunCsharp | 362.5 ms | 7.21 ms | 10.10 ms |     126 B |
|     RunIL | 353.6 ms | 3.26 ms |  3.05 ms |     126 B |
```

## .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
```assembly
; ConsoleApp10.ILBenchmark.RunCsharp()
       push      rsi
       sub       rsp,20
       vzeroupper
       mov       esi,[rcx+8]
       movsxd    rdx,esi
       mov       rcx,offset MT_System.Single[]
       call      CORINFO_HELP_NEWARR_1_VC
       xor       edx,edx
       test      esi,esi
       jle       short M00_L01
       mov       ecx,[rax+8]
M00_L00:
       mov       r8,2A714A17390
       mov       r8,[r8]
       cmp       edx,[r8+8]
       jae       short M00_L02
       movsxd    r9,edx
       vmovss    xmm0,dword ptr [r8+r9*4+10]
       mov       r8,2A714A17398
       mov       r8,[r8]
       cmp       edx,[r8+8]
       jae       short M00_L02
       vmovss    xmm1,dword ptr [r8+r9*4+10]
       vaddss    xmm0,xmm0,xmm1
       cmp       edx,ecx
       jae       short M00_L02
       vmovss    dword ptr [rax+r9*4+10],xmm0
       inc       edx
       cmp       edx,esi
       jl        short M00_L00
M00_L01:
       add       rsp,20
       pop       rsi
       ret
M00_L02:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 126
```

## .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
```assembly
; ConsoleApp10.ILBenchmark.RunIL()
       push      rsi
       sub       rsp,20
       vzeroupper
       mov       esi,[rcx+8]
       movsxd    rdx,esi
       mov       rcx,offset MT_System.Single[]
       call      CORINFO_HELP_NEWARR_1_VC
       xor       edx,edx
       test      esi,esi
       jle       short M00_L01
       mov       ecx,[rax+8]
M00_L00:
       mov       r8,204B1757390
       mov       r8,[r8]
       cmp       edx,[r8+8]
       jae       short M00_L02
       movsxd    r9,edx
       vmovss    xmm0,dword ptr [r8+r9*4+10]
       mov       r8,204B1757398
       mov       r8,[r8]
       cmp       edx,[r8+8]
       jae       short M00_L02
       vmovss    xmm1,dword ptr [r8+r9*4+10]
       vaddss    xmm0,xmm0,xmm1
       cmp       edx,ecx
       jae       short M00_L02
       vmovss    dword ptr [rax+r9*4+10],xmm0
       inc       edx
       cmp       edx,esi
       jl        short M00_L00
M00_L01:
       add       rsp,20
       pop       rsi
       ret
M00_L02:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 126
```

**Comment by DaZombieKiller** [comment]
Something interesting is that using pointer casts or `Unsafe.As` seems to produce less desirable results, which isn't what I had expected: https://sharplab.io/#gist:9016c51ae533ea83d0f43a71e68015b5

**Comment by joperezr** [comment]
cc: @tannergooding

**Comment by tannergooding** [comment]
This is related to some of the stuff @migueldeicaza has been thinking about.

Also CC. @jaredpar as what we do here is likely impacted by any decisions on a language timeframe for https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-29.md
