### ISSUE TITLE
System.Drawing.Printing.PrintDocument is missing DefaultEvent and DefaultProperty attributes

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/runtime#34696]
On .NET Framework, [`PrintDocument`](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Printing/PrintDocument.cs,275c61df12f04804) is defined with `DefaultEvent` and `DefaultProperty` attributes, which control the behavior at design-time when this component is being modified via the property grid control. These are missing in .NET Core, which negatively affects the designer experience.

**Comment by safern** [comment]
Thanks @DustinCampbell -- I added this to the 5.0 backlog.

**Comment by eriawan** [comment]
@safern 

I'd like to take this one. Could you please assign this to me? Thanks in advance 🙂

**Comment by safern** [comment]
@eriawan done 😄

**Comment by eriawan** [comment]
@safern 
Thanks!
I've submitted PR on #35162 and I got some build errors. Let's continue to discuss there on the PR. 🙂

**Comment by eriawan** [comment]
@safern 
I think I've found the cause of the build error. I have updated my PR.

**Comment by danmosemsft** [comment]
@DustinCampbell I see that we don't have them on BackgroundWorker or Process (and .NET Framework does), do you care about those?

**Comment by DustinCampbell** [comment]
We likely do, but we haven't gotten to those components in the WinForms designer yet, so I hadn't noticed them.

**Comment by danmosemsft** [comment]
@eriawan do you want to look at those two as well?

**Comment by eriawan** [comment]
@danmosemsft 
Sure. 🙂 
I will add those attributes into BackgroundWorker and Process in separate PR, because current PR #35162 is still being reviewed.

cc @safern

**Comment by danmosemsft** [comment]
BTW, that's assuming it's appropriate to add these attributes, it wouldn't add a problematic dependency, etc -- that would be for @safern to say as he's the area owner.
