### ISSUE TITLE
[mono] Tests failed on windows: System.Net.*.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34690]
There a lot of failures in `System.Net.*.Tests` namespaces on windows. Mostly it's `System.PlatformNotSupportedException: This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.`
The related tests/assemblies will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by danmosemsft** [comment]
The tests failing with the message above is a dupe of https://github.com/dotnet/runtime/issues/34591.

What are the other failures -- @MaximLipnin could you please break them out or share the testresults.xml? I am guessing they are not interesting but perhaps there is another distinct category.

Networking folks - I don't think there is any suggestion there is a networking bug here. Either Mono runtime differences, or tests could use more fine grained disabling.

**Comment by am11** [comment]
> `This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.`

Is it right to get this message on Windows?
