### ISSUE TITLE
Proposal: Add support for int keyed dictionaries to configuration binder

### ISSUE THREAD

**Issue by beppemarazzi** [dotnet/runtime#34691]
Up to now, only string or enum keys are supported for dictionaries in ConfigurationBinder.
This simple proposal adds support for integer keys:

int
uint
short
ushort

See also dotnet/extensions#3052

I've done a very simple PR implementing this feature dotnet/extensions#3063 but it was closed because that component was migrated to this repo.

**Comment by beppemarazzi** [comment]
@Dotnet-GitSync-Bot the area label is area-System.Configuration

**Comment by safern** [comment]
This seems more like a `Microsoft.Extensions` area. @maryamariyan could you please take a look?

**Comment by ericstj** [comment]
This appears to be a duplicate of https://github.com/dotnet/runtime/issues/36044
