### ISSUE TITLE
Enable LLVM + AOT for the release build for devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#34693]
The default release build for devices is going to be LLVM + AOT.  We need to modify the build to make this happen:

- [ ] Modify the android & iOS store publish to enable LLVM + AOT for devices.
- [x] Ensure the right files sit next to `mono-aot-cross` https://github.com/dotnet/runtime/pull/35306
- [ ] Validate a simple sample works

**Comment by ViktorHofer** [comment]
Not relevant anymore, closing.
