### ISSUE TITLE
replace "corefx" with "libraries" as appropriate

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#347]
There are 507 remaining uses of 'corefx' in this repo.

https://github.com/dotnet/runtime/search?q=corefx&unscoped_q=corefx

Where it's not expensive or breaking, it would be good to replace many of these with 'libraries' to reduce confusion for future contributors: the term 'corefx' will have no meaning going forward.

**Comment by eanova** [comment]
This looks like something I could do.  If you have no objections, I'd like to take on this assignment.

**Comment by scalablecory** [comment]
@eanova it's yours

**Comment by stephentoub** [comment]
Many of these references are in ActiveIssue links. Those should remain; we could manually update them to the corresponding issue in runtime once the issues are bulk moved, but that's also a lot of work (the issue numbers will be different) for little gain.

**Comment by eanova** [comment]
I'll try to avoid any conflicts for now.  I'll go through them and find the single file changes that don't conflict first.

**Comment by danmosemsft** [comment]
@eanova yes I'd just do a PR with high confidence ones first. There are some eg package names, environment variables where it is not clear whether there should be a change. And as @stephentoub says, the URL's have to stay.

**Comment by eanova** [comment]
Got it.  I noticed there were 296 results for ActiveIssue.  I'll skip those source and test files.

**Comment by eerhardt** [comment]
One place I just discovered is in the `PersistedFiles.Names.Unix.cs` location.  If you install dotnet on a Linux machine and inspect the folders under `$HOME/.dotnet` you'll see a `corefx` directory. Currently mine looks like:

![image](https://user-images.githubusercontent.com/8291187/71747853-6a9ce400-2e36-11ea-95dd-4367003801a2.png)

This comes from https://github.com/dotnet/runtime/blob/662817d60a82cbffb4331817f1e8e3a082e9bd29/src/libraries/System.Private.CoreLib/src/System/IO/PersistedFiles.Names.Unix.cs#L9-L15

Should I open a separate issue for this one location? It might be considered a breaking change if we rename this directory.

/cc @bartonjs

**Comment by bartonjs** [comment]
@eerhardt That's pretty breaking.  It can't change.

**Comment by danmosemsft** [comment]
Probably we should add a comment in the code indicating it's a historical artefact that cannot change now.

**Comment by danmosemsft** [comment]
@eanova are you planning to do more here? I wonder whether this can now be closed?

**Comment by danmosemsft** [comment]
Looks like this is mostly cleaned up (ignoring the many new ones added by making active issue ID's into full URLs)

**Comment by eanova** [comment]
@danmosemsft Sorry Dan just got this message.  It's pretty clean as it is.  I'm going to make another pass through but I think it's less than two PRs(10 each) worth left.

**Comment by danmosemsft** [comment]
Cool! https://github.com/dotnet/runtime/pull/1941

**Comment by jkotas** [comment]
@eanova Thank you for all your work on this!

**Comment by eanova** [comment]
No problem!  Everyone updated the references during the transition which made it interesting. Thank you for all your suggestions and help.
