### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007001F on Catalina

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#34708]
I bump to this when trying to build runtime repo after sync. It is trying to use 5.0 preview build and the build fails every time. 

```
Shining:wfurt-runtime2 furt$ /Users/furt/github/wfurt-runtime2/.dotnet/dotnet --info
Failed to create CoreCLR, HRESULT: 0x8007001F

Host (useful for support):
  Version: 5.0.0-preview.3.20169.1
  Commit:  bc28cbef85

.NET Core SDKs installed:
  5.0.100-preview.4.20202.8 [/Users/furt/github/wfurt-runtime2/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.3.20170.2 [/Users/furt/github/wfurt-runtime2/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20169.1 [/Users/furt/github/wfurt-runtime2/.dotnet/shared/Microsoft.NETCore.App]
```

I tried to run wit with `COREHOST_TRACE=1` but that did not show any useful.
I'm not sure what would be best next step to debug this. 

cc: @janvorli as PAL may be suspect.

**Comment by wfurt** [comment]
failing block may be clue (when running under dtruss)
```
27723/0xbb9196:     40857       8      5 bsdthread_create(0x1051F4680, 0x7F9F3C805600, 0x70000F53E000)|\|\\\ = 257155072 0
27723/0xbb91aa:         5       4      0 thread_selfid(0x0, 0x0, 0x0)|\\|\\\ = 12292522 0
27723/0xbb91aa:        36       6      2 psynch_cvsignal(0x7F9F3C805748, 0x100, 0x0)|\\\|\\\ = 257 0
27723/0xbb9196:     40867      42      3 psynch_cvwait(0x7F9F3C805748, 0x100000100, 0x0)|\\\|\\\ = 0 0
27723/0xbb9196:     40879       3      0 sigaction(0xF, 0x7FFEEAB4CF78, 0x1056C3550)|\\\|\\\ = 0 0
27723/0xbb9196:     40883       3      0 fcntl(0x0, 0x43, 0x0)|\|\\\ = 6 0
27723/0xbb9196:     40885       2      0 fcntl(0x1, 0x43, 0x0)|\|\\\ = 7 0
27723/0xbb9196:     40886       2      0 fcntl(0x2, 0x43, 0x0)|\|\\\ = 8 0
27723/0xbb9196:     41094       4      1 mmap(0x0, 0x1000, 0x3, 0x1002, 0xFFFFFFFFFFFFFFFF, 0x0)|\\\|\\\ = 0x105854000 0
27723/0xbb9196:     41102       3      0 mlock(0x105854000, 0x1000, 0x0)|\\\|\\\ = -1 35
```
35 is EAGAIN and that seems weird. attaching whole trace. 
[trace.txt](https://github.com/dotnet/runtime/files/4452620/trace.txt)

**Comment by wfurt** [comment]
Disabling SIP (System Integrity Protection) fixed it. But is enabled by default and requires reboot to recovery mode to disable it.

```
Shining:coreclr furt$ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: enabled
	Debugging Restrictions: enabled
	DTrace Restrictions: disabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

We may not see this in CI as we may have disabled SIP to get crash dumps.

**Comment by janvorli** [comment]
The problem is that there are not enough resources for locking a memory page. There is a system wide limit on the number of pages that can be locked and once it is depleted, all mlock attempts fail until some process frees that memory. I've looked into it few weeks ago, let me add the issue number.

**Comment by wfurt** [comment]
If so, why SIP would matter? I have system with 32G of RAM.

**Comment by janvorli** [comment]
I don't think it mattered, I think it was just a coincidence that some process has released its wired memory. See #10870 for details.

**Comment by wfurt** [comment]
It does seem like dup of #34793. It happened to me again with SIP disabled and stopping few Parallels VM brought it back to life. So it is memory constrain as @janvorli suspected.

**Comment by Ornias1993** [comment]
@wfurt I want to add to this:
Had the same issue on FreeBSD where ZFS was exeeding the max wired memory and thus preventing mlock from running. This is actually a bug with ZFS and FreeBSD (in contrast with this problem).

But I would like to ask the question: Do we really need to mlock this? If even Databases can run without mlock on multiplatform and thus don't hit these issues, why does DotNet need mlock?

**Comment by janvorli** [comment]
@Ornias1993 the mlock is essential for correct .NET behavior. We create just a single locked page to be able to trigger flushing write buffers of all processors in the process (perform a process wide memory barrier). Without the locked page, GC and some other stuff in the runtime would not work reliably as we need to ensure that the state of all processors is synchronized. 
On Linux, we use membarrier syscall with MEMBARRIER_CMD_PRIVATE_EXPEDITED option as a primary mean to achieve that goal, but that's not available on FreeBSD. If there is some other way to achieve that on FreeBSD, it would be great to add that.

**Comment by Ornias1993** [comment]
@janvorli I understand.
I've thrown an email to @AllanJude (he doesn't respond well to github tags, he gets too many), asking if he might know a way, as he has some experience with FreeBSD memory management afaik.

**Comment by allanjude** [comment]
I am not really familiar with the DotNet stuff, but @rootwyrm helps to maintain that on FreeBSD, he might be of help here.

**Comment by Ornias1993** [comment]
@allanjude I was more refering to general advice what options/alternatives there are to mloc on bsd ;)

**Comment by Ornias1993** [comment]
Note:
The error I had seems specific to FreeNAS, it is actually solved in FreeBSD itself here:
https://docs.freebsd.org/cgi/getmsg.cgi?fetch=145846+0+archive/2019/svn-src-head/20190519.svn-src-head

Sorry to bother :)
