### ISSUE TITLE
Should AllowReversePInvokeCallsAttribute be marked Obsolete?

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#34701]
Should [AllowReversePInvokeCallsAttribute ](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.allowreversepinvokecallsattribute) be marked `Obsolete` and point to [`NativeCallableAttribute`](https://github.com/dotnet/runtime/issues/32462)? This appears to be a legacy attribute with no real application anymore.

/cc @jkotas @stephentoub

**Comment by jkotas** [comment]
This attribute is part of code access security (CAS) family of attributes. It should be on the same plan as the rest of them.

We should mark all CAS attributes as obsolete once we have the fine grained controls for obsoleting in place (https://github.com/dotnet/runtime/issues/31279#issuecomment-586545318).

**Comment by jkoritzinsky** [comment]
I believe the fine grained obsoletion support is merged in and supported in Roslyn.

**Comment by AaronRobinsonMSFT** [comment]
This can be addressed by following the pattern in https://github.com/dotnet/runtime/pull/37536.
