### ISSUE TITLE
System.IO.Ports references non-existent runtime.native.System.IO.Ports in preview2

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#34715]
In preview2, https://www.nuget.org/packages/System.IO.Ports/5.0.0-preview.2.20160.6 has non-existent dependency runtime.native.System.IO.Ports at a 5.0.0-... version.

**Comment by ericstj** [comment]
We used to build this but something broke that in October: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=runtime.native.System.IO.Ports&protocolType=NuGet&version=5.0.0-alpha1.19523.8

**Comment by ericstj** [comment]
I put up a couple PRs to fix this.  Oddly we were still building all the RID-specific versions of this package, but not the meta-package which references them.
