### ISSUE TITLE
Problem like common error NETSDK1099:

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#34712]
_From @SourceSkyBoxer on Thursday, March 19, 2020 12:08:23 AM_

Hello everyone, 

I am very disappointed because I have to use DotNet 3.1 but it shows always crazy like not support for single executable. That is really dreadfully.
![image](https://user-images.githubusercontent.com/57066679/77018467-e3173980-697d-11ea-9a5c-460e722db7f1.png)
Why do i should understand hard?

I have tried to type like simple:
"dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true

// EDIT:
For csproj file
like this:
add 2 lines 
And save it than try:
dotnet publish -c Release -r linux-x64
result: Nor errors. Successfully! But I don't understand why do they not use "-p:PublishSingleFile -p:PublishTrimmed" than it throws error like I have shown about common error.

I can't expect that. I have yesterday successfully. Now it happens.
I am using Ubuntu 18.04.4, dotnet 3.1.2x and dotnet 5 preview 1.... 

Thanks!

_Copied from original issue: dotnet/sdk#10909_

**Comment by swaroop-sridhar** [comment]
@SourceSkyBoxer are you trying to publish a library as a single file? 
That's not supported. 

`PublishSingleFile=true` requires 
* `targetframework=` `netcoreapp3.0` or `netcoreapp3.1`, 
* `OutputType=Exe`
* `UseApppHost=true`

**Comment by swaroop-sridhar** [comment]
@wli3  I think this issue should have remained in SDK, since this is a publish time concern.

**Comment by wli3** [comment]
Did you add all the flags? If not, we will make our decision for these flags

**Comment by swaroop-sridhar** [comment]
> Did you add all these flags? If not, we will make our decision for these flags

@wli3  I'm not sure if you're asking me or @SourceSkyBoxer about the flags.
I did add checks for these properties (and the associated errors) in the SDK for PublishSingleFile.

**Comment by wli3** [comment]
@swaroop-sridhar I believe runtime own the logic around PublishSingleFile and PublishTrimmed in SDK.

**Comment by swaroop-sridhar** [comment]
> @swaroop-sridhar I believe runtime own the logic around PublishSingleFile and PublishTrimmed in SDK.

@wli3 Yes I completely agree about this  -- the issue should be assigned to me.
What I meant is that the issue should be in the SDK repo assigned to me (the permission problem that prevented this is now resolved).

**Comment by wli3** [comment]
I see. OK, I can close this and reopen and assign to you
