### ISSUE TITLE
Unnecessary PGO work in CoreCLR build

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#34728]
If you build with `build-runtime.cmd` and don’t pass `nopgooptimize`, it restores the optimization data package, then does some parsing of it.

In a Debug/Checked build, isn’t this completely unused or wasted? It looks like `pgosupport.cmake` will set `LINK_FLAGS_RELEASE` and `LINK_FLAGS_RELWITHDEBINFO` based on this info, but those aren’t used except for Release builds.

So, shouldn’t we force the `__PgoOptimize` variable in the `build-runtime.cmd` script to 0 for non-Release builds? It doesn’t even seem interesting to allow forcing it to 1 in these cases, as it wouldn’t be used.

@jkoritzinsky

**Comment by jkoritzinsky** [comment]
This has been fixed by the improvements in the incremental inner-loop.
