### ISSUE TITLE
[mono] Tests failed on windows: System.ComponentModel.TypeConverterTests.ImageConverterTest

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34755]
`System.ComponentModel.TypeConverterTests.ImageConverterTest` tests fail on windows with `exit code -1073740791`. 
They will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by danmosemsft** [comment]
0xC0000005 -1073741819 STATUS_ACCESS_VIOLATION

**Comment by ericstj** [comment]
ImageConverterTest : Likely the same as https://github.com/dotnet/runtime/issues/34591

**Comment by JeremyKuhne** [comment]
System.Drawing.Common has moved to WinForms.
