### ISSUE TITLE
Add support for removing dead branches in mono interpreter

### ISSUE THREAD

**Issue by BrzVlad** [dotnet/runtime#34750]
The mono interpreter currently does constant folding, but conditional branches are never optimized away. Optimizing them is particularly useful in various bcl places, like Span, where there are many checks with results known at jit compile time. (ex `Sizeof<T> == ct`, `typeof(T) == ct`, `feature.IsSupported` etc)

**Comment by SamMonoRT** [comment]
Moving this to 6.0 milestone.

**Comment by BrzVlad** [comment]
Done in https://github.com/dotnet/runtime/pull/41574, https://github.com/dotnet/runtime/pull/41628, https://github.com/dotnet/runtime/pull/41913 and https://github.com/dotnet/runtime/pull/42531
