### ISSUE TITLE
Dictionary ToArray throws System.ArgumentException in Mono

### ISSUE THREAD

**Issue by banditoth** [dotnet/runtime#34765]
Exception message:
` 
[DB_LOGGER][EXCEPTION][2020. 04. 09. 15:36:20]: PollFactory at MainExecute: Main executing failed, exception occured | System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].CopyTo (System.Collections.Generic.KeyValuePair`2[TKey,TValue][] array, System.Int32 index) [0x00021] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:337
  at System.Collections.Generic.Dictionary`2[TKey,TValue].System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo (System.Collections.Generic.KeyValuePair`2[TKey,TValue][] array, System.Int32 index) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:904
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/Common/src/System/Collections/Generic/EnumerableHelpers.cs:79
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:18
  at <SENSITIVEPROJECTINFORMATIONS>.Factory.PollFactory.MainExecute () [0x00022] in /Users/viking/<SENSITIVEPROJECTINFORMATIONS>/Factory/PollFactory.cs:140
`

Full logic:

`
namespace SENSITIVEPROJECTNAME.Factory
{
	public static class PollFactory
	{
		public static bool Initalized { get; private set; }
		private static Task _mainExecuteTask = null;
		private static Dictionary<Guid, PollFactoryTask> _pollTaskList = null;
		private static bool _executionEnabled = false;

		public static void Initalize()
		{
			try
			{

				if (Initalized)
				{
					throw new InvalidOperationException($"Already initalized");
				}

				MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(Initalize)}: Initalization started");

				_pollTaskList = new Dictionary<Guid, PollFactoryTask>();

				SubscribeToControlEvents();

				StartMainExecute();

				Initalized = true;

				MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(Initalize)}: Initalization sucessed");

			}
			catch (Exception ex)
			{
				MobileLogger.Instance.LogException(ex, $"{nameof(PollFactory)} at {nameof(Initalize)}: Initalization failed, exception occured");
			}
		}

		private static void SubscribeToControlEvents()
		{
			ApplicationLifeCycleManager.ApplicationResumed += ApplicationLifeCycleManager_ApplicationResumed;
			ApplicationLifeCycleManager.ApplicationSentToBackground += ApplicationLifeCycleManager_ApplicationSentToBackground;
			var connectionMgr = Resolver.Resolve<ConnectionManager>();
			connectionMgr.InternetAccessEnabled += ConnectionMgr_InternetAccessEnabled;
			connectionMgr.InternetAccessDisabled += ConnectionMgr_InternetAccessDisabled;
		}

		#region EventHandling

		private static void ConnectionMgr_InternetAccessDisabled()
		{
			StopMainExecute();
		}

		private static void ConnectionMgr_InternetAccessEnabled()
		{
			StartMainExecute();
		}

		private static void ApplicationLifeCycleManager_ApplicationSentToBackground()
		{
			StopMainExecute();
		}

		private static void ApplicationLifeCycleManager_ApplicationResumed()
		{
			StartMainExecute();
		}

		private static void StopMainExecute()
		{
			_executionEnabled = false;
		}

		#endregion EventHandling

		private static void StartMainExecute()
		{
			try
			{
				if (_mainExecuteTask == null || _mainExecuteTask?.IsCompleted == true)
				{
					_executionEnabled = true;
					_mainExecuteTask = Task.Factory.StartNew(MainExecute);
				}
			}
			catch (Exception ex)
			{
				MobileLogger.Instance.LogException(ex, $"{nameof(PollFactory)} at {nameof(StartMainExecute)}: Initalization failed, exception occured");
			}
		}

		private static async void MainExecute()
		{
			try
			{
				while (true)
				{
					foreach (var currentPollTask in _pollTaskList.ToArray()) // This line is where the exception occurs
					{
						if (false == _executionEnabled)
						{
							MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(MainExecute)}: Polling factory {nameof(MainExecute)} stop requested");
							return;
						}

						PollFactoryTask input = currentPollTask.Value;

						if (input == null)
						{
							MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(MainExecute)}: Task with id: '{currentPollTask.Key}''s {nameof(PollFactoryTask)} was null, removing it from tasks");
							RemovePollTask(currentPollTask.Key);
						}

						if (input.CallBackAction == null)
						{
							MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(MainExecute)}: Task with id: '{currentPollTask.Key}''s {nameof(input.CallBackAction)} was null, removing it from tasks");
							RemovePollTask(currentPollTask.Key);
						}

						if (input.ExecutingAction == null)
						{
							MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(MainExecute)}: Task with id: '{currentPollTask.Key}''s {nameof(input.ExecutingAction)} was null, removing it from tasks");
							RemovePollTask(currentPollTask.Key);
						}

						if (input.PollingThresholdInMilisec < 1)
						{
							MobileLogger.Instance.LogInfo($"{nameof(PollFactory)} at {nameof(MainExecute)}: Task with id: '{currentPollTask.Key}''s {nameof(input.PollingThresholdInMilisec)} was smaller than 1, removing it from tasks");
							RemovePollTask(currentPollTask.Key);
						}

						if (input.IsRunning == false)
						{
							if (DateTime.Now > input.LastInvoked.AddMilliseconds(input.PollingThresholdInMilisec))
							{
								input.IsRunning = true;
								_ = Task.Factory.StartNew(() => ExecuteCustomLogic(input.ExecutingAction, input.CallBackAction, input.ExceptionCallbackAction, input.ExecutingActionParameters));
								input.LastInvoked = DateTime.Now;
								input.IsRunning = false;
							}
						}
						else
						{
							MobileLogger.Instance.LogDebug(nameof(PollFactory), $"{nameof(PollFactory)} at {nameof(MainExecute)}: Oh,no! This polling task has not completed it's polling execution yet, ignoring new thread starting for the same logic.");
						}

					}

					await Task.Delay(200);

				}
			}
			catch (Exception ex)
			{
				MobileLogger.Instance.LogException(ex, $"{nameof(PollFactory)} at {nameof(MainExecute)}: Main executing failed, exception occured");
			}
		}

		private static async Task ExecuteCustomLogic(ExecutingActionDelegate<IPollFactoryResult> executionAction, CallBackActionDelegate callBackAction, Action onExceptionCallbackAction, object[] parameters)
		{
			try
			{
				IPollFactoryResult result = null;
				result = await executionAction.Invoke(parameters);
				callBackAction.Invoke(result);
			}
			catch (Exception ex)
			{
				MobileLogger.Instance.LogException(ex, $"{nameof(PollFactory)} at {nameof(ExecuteCustomLogic)}: Exception occured on executing polling logic. Invoking exception callback action");

				try
				{
					onExceptionCallbackAction?.Invoke();
				}
				catch (Exception exceptionCallbackException)
				{
					MobileLogger.Instance.LogException(exceptionCallbackException, $"{nameof(PollFactory)} at {nameof(ExecuteCustomLogic)}: Could not invoke exception callback action");
				}
			}
		}

		public static PollFactoryTask CreatePollFactoryTask(int pollingThresholdInMilisec, ExecutingActionDelegate<IPollFactoryResult> executionAction, CallBackActionDelegate callBackAction, Action onExceptionCallbackAction, params object[] parameters)
		{
			if (executionAction == null)
			{
				throw new ArgumentNullException(nameof(executionAction), "Must contain value");
			}

			if (callBackAction == null)
			{
				throw new ArgumentNullException(nameof(executionAction), "Must contain value");
			}

			if (pollingThresholdInMilisec < 100)
			{
				throw new ArgumentException("Must be higher than 1", nameof(pollingThresholdInMilisec));
			}

			return new PollFactoryTask()
			{
				CallBackAction = callBackAction,
				ExceptionCallbackAction = onExceptionCallbackAction,
				ExecutingAction = executionAction,
				LastInvoked = DateTime.MinValue,
				PollingThresholdInMilisec = pollingThresholdInMilisec,
				ExecutingActionParameters = parameters
			};
		}

		public static Guid AddPollTask(PollFactoryTask input)
		{
			Guid identifier = Guid.NewGuid();

			if (input == null)
			{
				throw new ArgumentNullException(nameof(input));
			}

			_pollTaskList.Add(identifier, input);

			return identifier;
		}

		public static void RemovePollTask(Guid identifier)
		{
			try
			{
				_pollTaskList.Remove(identifier);
			}
			catch (Exception ex)
			{
				MobileLogger.Instance.LogException(ex, $"{nameof(PollFactory)} at {nameof(RemovePollTask)}: Could not remove polling task with identifier: {identifier}");
			}
		}
	}
}
`

**Comment by vcsjones** [comment]
I suspect you are reading (`ToArray`) and writing (`AddPollTask`, `RemovePollTask`) to the dictionary from another thread. The `Dictionary` class is not thread safe - when you are adding things to the dictionary and the underlying array needs to grow, and that happens at the same time you are reading with `ToArray`, the internal state will be inconsistent.

A more minimal example might be something like:

```csharp
using System.Collections.Generic;
using System.Linq;
using System.Threading;

public static class Program {
    static void Main() {
        Dictionary<int, int> r = new Dictionary<int, int>();
        var t = new Thread(_ => {
            for (var i = 0;; i++)
            {
                r[i] = i;
            }
        });
        t.Start();
        while (true)
        {
            _ = r.ToArray();
        }
    }
}
```

Which when run should quickly produce an exception like "Destination array is not long enough to copy all the items in the collection. Check array index and length."

The solution is to either synchronize access to your dictionary, or use a thread collection like [`ConcurrentDictionary`][1] 

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=netcore-3.1

**Comment by banditoth** [comment]
> 
> 
> I suspect you are reading (`ToArray`) and writing (`AddPollTask`, `RemovePollTask`) to the dictionary from another thread. The `Dictionary` class is not thread safe - when you are adding things to the dictionary and the underlying array needs to grow, and that happens at the same time you are reading with `ToArray`, the internal state will be inconsistent.
> 
> A more minimal example might be something like:
> 
> ```cs
> using System.Collections.Generic;
> using System.Linq;
> using System.Threading;
> 
> public static class Program {
>     static void Main() {
>         Dictionary<int, int> r = new Dictionary<int, int>();
>         var t = new Thread(_ => {
>             for (var i = 0;; i++)
>             {
>                 r[i] = i;
>             }
>         });
>         t.Start();
>         while (true)
>         {
>             _ = r.ToArray();
>         }
>     }
> }
> ```
> 
> The example above will have one thread adding things to the dictionary while the main thread just calls `ToArray` in a loop.
> 
> Which when run should quickly produce an exception like "Destination array is not long enough to copy all the items in the collection. Check array index and length."
> 
> The solution is to either synchronize access to your dictionary, or use a thread-safe collection like [`ConcurrentDictionary`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=netcore-3.1)

Your scenario can be valid for the usage of my PollFactory.
Thank you for your fast reply, and exact solution for the problem.
Also sorry for the interrupt.
I'm closing this ticket, MSDN has the documentation for thread safety for Dictionaries (https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netframework-4.8#thread-safety)

Have a great day, and be safe in the days of pandemic.

Regards,
András
