### ISSUE TITLE
Examine JsonSerializer behavior for ref structs & pointers

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#34779]
Related - https://github.com/dotnet/runtime/pull/34777.

We should detect these types and fail gracefully rather than leaking exceptions from lower level APIs like `Type.MakeGenericType`.

**Comment by loligans** [comment]
Any workaround in the meantime? @layomia

**Comment by layomia** [comment]
@loligans unfortunately there's no workaround AFAIK. We'd need reflection support for ref structs to be able to support this. Ref structs can't be boxed or be generic parameters, so they are not friendly with `System.Reflection` APIs.

> Nevermind, I found that I could write my own JsonConverter for the Type.

How were you able to do this? A ref struct can't be the `T` type used in a `JsonConverter<T>` instance.

**Comment by loligans** [comment]
> 
> 
> @loligans unfortunately there's no workaround AFAIK. We'd need reflection support for ref structs to be able to support this. Ref structs can't be boxed or be generic parameters, so they are not friendly with `System.Reflection` APIs.
> 
> > Nevermind, I found that I could write my own JsonConverter for the Type.
> 
> How were you able to do this? A ref struct can't be the `T` type used in a `JsonConverter<T>` instance.

@layomia I was able to do this by using `ReadOnlyMemory` instead

```c#
public class MemoryJsonConverter : JsonConverter<ReadOnlyMemory<byte>>
{
    public override ReadOnlyMemory<byte> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return reader.GetBytesFromBase64().AsMemory();
    }

    public override void Write(Utf8JsonWriter writer, ReadOnlyMemory<byte> value, JsonSerializerOptions options)
    {
        if (writer is null) { throw new ArgumentNullException(nameof(writer)); }
        writer.WriteBase64StringValue(value.Span);
    }
}
```

**Comment by krwq** [comment]
I've added a fix for issue which sounds similar to this one in contract customization PR, can we verify it works as expected now? See test I added here: https://github.com/dotnet/runtime/commit/5be70920626207098ffc56ee7e13bf14c9b4c483#diff-c0f5d77b22f8bd7e41958095b0e9fc829a00de0104bf283035d81e6bb3d7b30eR599

**Comment by krwq** [comment]
I'm closing this for now please create new issue with repro if you feel like we've missed anything in there

**Comment by eiriktsarpalis** [comment]
@krwq the tests you cite are specific to contract customization. We should add a test that specifically validates the scenario described in, say, https://github.com/dotnet/runtime/issues/34779#issuecomment-940242154. I would recommend reopening the issue until that is addressed.

**Comment by eiriktsarpalis** [comment]
The test in question is related to the issue better described in #46088. I think we should close this one since it's less concrete and address any issues related to unsupported types as they come up.
