### ISSUE TITLE
src/libraries/tests.proj contains incorrect condition

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#34788]
The test run complains:
`F:\git\runtime4\src\libraries\tests.proj(24,11): error MSB4092: An unexpected token "==" was found at character position 25 in condition "'$(Coverage)' == 'true' == 'true' and '$(SkipCoverageReport)' != 'true'".`

**Comment by danmosemsft** [comment]
@safern this was broken by  #33553

**Comment by safern** [comment]
I'll take a look and put up a PR in a few mins.
