### ISSUE TITLE
Support reading calling convention from modreq or modopt on the return type

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#34805]
Runtime-side tracking of the extensible calling convention proposal. Compiler-side issue: https://github.com/dotnet/roslyn/issues/39865. Will update with a final description of the actual spec when we've settled it.

**Comment by jeffschwMSFT** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Based on plans in .NET 5, there are no current reasons to read any `modopt` values. This would change if/when we add `CallConvSuppressGCTransition`. Instead the goal here would be to ignore/block cases when we do discover an existing `modopt` that is attempting to change behavior. The goal here would be preventative for when we do add support in a future runtime.

**Comment by AaronRobinsonMSFT** [comment]
Related https://github.com/dotnet/runtime/issues/38133
