### ISSUE TITLE
Changing binary file properties

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#34811]
Hi,
I need to change the " Product name, Product version and Copyright details" in the similar file (example below). Could someone help me to locate the right resource/property file to make the changes?

![File-Property](https://user-images.githubusercontent.com/38784601/78977937-9961df00-7b36-11ea-9ddd-dee66c294386.png)

**Comment by gfoidl** [comment]
Have a look at [AssemblyInfo properties](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#assemblyinfo-properties).

**Comment by deokershesh** [comment]
Thanks gfoidl,

I could locate the assembly file which has all these details. Below is the content, it says "auto-generated" and changing directly any value may have unwanted run time issues. How do I change these values? Which file/configuration do I need to modify to make sure this "auto-generated" file contents is changed for the values I want to put?
===================

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
<Assembly: System.Reflection.AssemblyDefaultAliasAttribute("Microsoft.VisualBasic.Core"),  _
 Assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", ""),  _
 Assembly: System.Reflection.AssemblyMetadata("Serviceable", "True"),  _
 Assembly: System.Reflection.AssemblyMetadata("PreferInbox", "True"),  _
 Assembly: System.Reflection.AssemblyCompanyAttribute("Microsoft Corporation"),  _
 Assembly: System.Reflection.AssemblyCopyrightAttribute("© Microsoft Corporation. All rights reserved."),  _
 Assembly: System.Reflection.AssemblyDescriptionAttribute("Microsoft.VisualBasic.Core"),  _
 Assembly: System.Reflection.AssemblyFileVersionAttribute("4.700.20.21001"),  _
 Assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.1.1"),  _
 Assembly: System.Reflection.AssemblyProductAttribute("Microsoft® .NET Core"),  _
 Assembly: System.Reflection.AssemblyTitleAttribute("Microsoft.VisualBasic.Core"),  _
 Assembly: System.Reflection.AssemblyVersionAttribute("10.0.5.0")> 

'Generated by the MSBuild WriteCodeFragment class.

**Comment by deokershesh** [comment]
Just to add, the above contents come from D:\corefx-release-3.1\artifacts\obj\Microsoft.VisualBasic.Core\netcoreapp-Windows_NT-Debug\Microsoft.VisualBasic.Core.AssemblyInfo.vb

**Comment by deokershesh** [comment]
And D:\corefx-release-3.1\artifacts folder gets generated during the build process.

**Comment by gfoidl** [comment]
Why do you want to change this information for a Microsoft-Assembly? You are not the owner of this library and I don't think this conforms with the license.

For your own projects see the link above.

**Comment by deokershesh** [comment]
@gfoidl, You are right, I had given only example, not the same DLL at all.
Anyway, I figured out, by adding "<GenerateAssemblyInfo>false</GenerateAssemblyInfo>" in the project file and adding our own customized Assembly file in the the project, would solve the purpose.

Thanks for everyone's help and pointers.

**Comment by deokershesh** [comment]
...False for " <GenerateAssemblyInfo>false</GenerateAssemblyInfo> " in the project file.... looks like tool chops off the special symbols!

**Comment by deokershesh** [comment]
...False for " <  GenerateAssemblyInfo  > false < / GenerateAssemblyInfo > " in the project file..

**Comment by gfoidl** [comment]
... or you use the values in `<PropertyGroup>` and omit the `AssemblyInfo.cs` (as this file will be generated by the tooling when the value is `true`). Either way will result in the same information in the assembly.

On benefit (amongst others) of using the csproj-Items is that they can be easily automated, e.g. via environment variables (use info from build-system, git-Tags, etc.).
