### ISSUE TITLE
CompareInfo.IndexOf / LastIndexOf early-exit code paths do not account for zero-weight characters

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#34828]
Repro code:

```cs
Console.WriteLine(CultureInfo.InvariantCulture.CompareInfo.IndexOf(string.Empty, "\u200c"));
```

This should print `0` on all platforms unless we're running under the invariant globalization mode, in which case it should return `-1`. The reason for this is an incorrect early-exit in `CompareInfo.IndexOf`, as shown below.

https://github.com/dotnet/runtime/blob/1ae617bc8f3644cd51faf124e399fb01c952be45/src/libraries/System.Private.CoreLib/src/System/Globalization/CompareInfo.cs#L940-L947

This early exit does not account for the fact that empty strings and non-empty strings may compare as equal under certain collations if the non-empty strings consist only of zero-weight code points.

**Comment by tarekgh** [comment]
@GrabYourPitchforks thanks for filing it. just wondering if you'll get the fix? or expect someone else to do it?

**Comment by GrabYourPitchforks** [comment]
The fix is included in https://github.com/dotnet/runtime/pull/1514. I'm hoping to get a new iteration of that out by the end of today.

**Comment by GrabYourPitchforks** [comment]
A quick note: there is a difference between NLS and ICU here.

Consider a call to `"hello".LastIndexOf("\u200d")` (using a linguistic comparer). NLS's `FindNLSStringEx` will return an index of _4_. ICU's `usearch_last` will return an index of _5_. As far as I can tell this only happens with weightless code points. I'm not going to try to work around this in the .NET Core layer, but I'll update the unit tests to account for the target environment and to change the expectation.

**Comment by tarekgh** [comment]
@GrabYourPitchforks 

>  I'm not going to try to work around this in the .NET Core layer

Any reason why we cannot do that?

**Comment by GrabYourPitchforks** [comment]
> Any reason why we cannot do that?

We're not doing it in other places. For example, on NLS `"\u200dhello".IndexOf("hello")` returns _1_, but logically it should really return _0_ (since `"\u200dhello".StartsWith("hello")` returns _true_). I think the risk of trying to capture all of these edge cases makes it more likely that we'll introduce bugs in our own code. It'll definitely slow down the common path.

**Comment by tarekgh** [comment]
ok. thanks!
