### ISSUE TITLE
FilterNamedIntrinsicMethodAttribs checks className for unsupported isas not classname

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#34826]
As noted by @saucecontrol in https://github.com/dotnet/runtime/pull/34550#issuecomment-611850762_ crossgen doesn't correctly check for isaName instead of className which checking for the use of the crossgen2 corelib unsupported isas like Avx, Avx2, etc. We should fix this as it might cause very odd behavior for code in corelib which uses such logic.

**Comment by tannergooding** [comment]
This looks like an oversight on my part when I changed the logic in https://github.com/dotnet/coreclr/pull/25365
