### ISSUE TITLE
Enabling EventPipe via the managed EventPipe class isn't thread-safe

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#34839]
Reported by @xiaomi7732:

```cs
using System;
namespace System.Diagnostics.Tracing
{
    internal static class EventPipe
    {
        private static ulong s_sessionID;
        internal static void Enable(EventPipeConfiguration configuration)
        {
            if (configuration == null)
            {
                throw new System.ArgumentNullException("configuration");
            }
            if (configuration.Providers == null)
            {
                throw new System.ArgumentNullException("Providers");
            }
            EventPipeProviderConfiguration[] providers = configuration.Providers;
            EventPipe.s_sessionID = EventPipeInternal.Enable(configuration.OutputFile, configuration.Format, configuration.CircularBufferSizeInMB, providers, (uint)providers.Length);
        }
        internal static void Disable()
        {
            EventPipeInternal.Disable(EventPipe.s_sessionID);
        }
    }
}
```

This code may leak an EventPipe session when EventPipe.Enable() is called concurrently where two session may be enabled from different codepaths and both of them will be enabled, but only one of them will be tracked via s_sessionID meaning whichever session isn't tracked will be leaked when Disable() is called.

On top of that, even without involving concurrency, it's also possible for us to never call Disable() on a session that was overwritten by calling Enable() twice before the first one was disabled.

**Comment by josalem** [comment]
@sywhang says I can close this so I'm closing it.  Thanks, @sywhang. 😁
