### ISSUE TITLE
Please stop asking whether I want to cancel when clicking "Close"

### ISSUE THREAD

**Issue by UweKeim** [dotnet/runtime#3484]
Back in the 1990s and 2000s, when I click cancel in a setup executable, it asked me whether I want to cancel.

Luckily, this annoying behavior is mostly gone.

Unfortunately, not in the Microsoft .NET Core 2.2.2 Windows Server Hosting setup.

### Steps

1. [Download the setup from here](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.2-windows-hosting-bundle-installer).

1. Start the setup, let it run completely until finished.

1. Optionally, reboot.

1. Start the setup again, to see this screen:
    ![image](https://user-images.githubusercontent.com/415439/53698114-bb881a00-3dd8-11e9-8df4-c21ff2b1c661.png)

1. Click the <kbd>Close</kbd> button.

1. See this message box:
    ![image](https://user-images.githubusercontent.com/415439/53698125-d5296180-3dd8-11e9-9be8-575bdf9c3e29.png)

### Expected behavior

The setup should simply close, without asking. I. e. Step 6 should not occur.

Beside the message box when closing, in my opinion it also should be removed everywhere else, i. e. when the button reads <kbd>Cancel</kbd>, too.

**Comment by NikolaMilosavljevic** [comment]
Cost prohibitive - closing.
