### ISSUE TITLE
BAR reporting is incorrect

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#3486]
Because core-setup pushes to the dotnetcli storage account, the assets that are pushed there (zips, installers, etc.) should be reported to BAR as from those locations, instead of the dotnet-core feed.  They do exist in the dotnet-core feed, but but that's not the final intended location.

**Comment by NikolaMilosavljevic** [comment]
@mmitche does this still apply?

**Comment by mmitche** [comment]
yep fixed.
