### ISSUE TITLE
Test failure: Interop/MarshalAPI/FunctionPointer/FunctionPtrTest/FunctionPtrTest.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34883]
failed in job: [runtime-coreclr gcstress-extra 20200412.1](https://dev.azure.com/dnceng/public/_build/results?buildId=598025&view=ms.vss-test-web.build-test-results-tab&runId=18835866&resultId=100671&paneView=debug)

Error message
~~~
Process terminated. A callback was made on a garbage collected delegate of type 'FunctionPtrTest!FunctionPtr+DelegateWithLong::Invoke'.
Repeat 2 times:
--------------------------------
at FunctionPtr+FunctionPointerNative.CheckFcnPtr(IntPtr)
--------------------------------
at FunctionPtr.RunGetFcnPtrSingleMulticastTest()
at FunctionPtr.Main()
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa6647040)
/root/helix/work/workitem/Interop/MarshalAPI/FunctionPointer/FunctionPtrTest/FunctionPtrTest.sh: line 275: 246 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/Interop/MarshalAPI/Reports/Interop.MarshalAPI/FunctionPointer/FunctionPtrTest/FunctionPtrTest.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun FunctionPtrTest.dll ''
Running RunGetDelForFcnPtrTest...
Running RunGetFcnPtrSingleMulticastTest...
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.246.dmp
Written 58204160 bytes (14210 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Interop/MarshalAPI/FunctionPointer/FunctionPtrTest/FunctionPtrTest.sh
Expected: True
Actual: False


Stack trace
   at Interop_MarshalAPI._FunctionPointer_FunctionPtrTest_FunctionPtrTest_._FunctionPointer_FunctionPtrTest_FunctionPtrTest_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/Interop.MarshalAPI/Interop.MarshalAPI.XUnitWrapper.cs:line 140
~~~

**Comment by AaronRobinsonMSFT** [comment]
This test was recently updated to permit throwing an exception instead of catching it and reporting a failure via `Console.WriteLine()`. See below for the previous version of the test: https://github.com/dotnet/runtime/blob/9ddbf5f63c8375aaabec83c3054af9bbf8107170/src/coreclr/tests/src/Interop/MarshalAPI/FunctionPointer/GetFcnPtrForDel_Negative_Security.cs#L28-L59

This would appear to be something other than an interop issue.

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/jit-contrib Any known issues with exception handling and GC Info on ARM64? The test update was to remove the enclosing `try`/`catch` instead of using it to handle reporting failures.

**Comment by jkotas** [comment]
This is a looks like a bug in: 

https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/src/Interop/MarshalAPI/FunctionPointer/SingleMulticastTest.cs#L22

The delegate has to be kept alive for as long as the function pointer created from it can be used.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Yeah. I thought that too, but this code didn’t really change here between the current version and past and is now failing. I guess there is the scope but I thought that was the same as the try/catch block. How was the previous okay if the current is not?

**Comment by jkotas** [comment]
The previous code was caching the delegate in static variable. It kept the unmanaged marshaled delegate alive.

The current code is caching it in a local. The local scope does not guarantee that object reference stays alive. The JIT is free to stop reporting the reference to the GC after its last use (ie much earlier than end of the variable scope).

This is very common gotcha with delegate marshaling, and one of the reasons we should be recommending function pointers for interop once we have them available (function pointers do not have this gotcha).

**Comment by jkotas** [comment]
Also, bugs like this can come and go due to very subtle changes. The exact place where the JIT stops reporting the reference to the GC depends on how optimizations kick in.

**Comment by AaronRobinsonMSFT** [comment]
> The previous code was caching the delegate in static variable. It kept the unmanaged marshaled delegate alive.

Doh. I completely missed I converted the stored variable to a local from a static. Yes I see the issue now. Will fix.
