### ISSUE TITLE
.\coreclr.cmd -skiptests does not work

### ISSUE THREAD

**Issue by poizan42** [dotnet/runtime#349]
But it is documented at https://github.com/dotnet/runtime/tree/master/docs/workflow/building/coreclr

```
PS C:\Users\poizan\Documents\dev\dotnet-runtime> .\coreclr.cmd -skiptests
##vso[task.setvariable isSecret=False;variable=Artifacts;isOutput=True]C:\Users\poizan\Documents\dev\dotnet-runtime\artifacts
##vso[task.setvariable isSecret=False;variable=Artifacts.Toolset;isOutput=True]C:\Users\poizan\Documents\dev\dotnet-runtime\artifacts\toolset
##vso[task.setvariable isSecret=False;variable=Artifacts.Log;isOutput=True]C:\Users\poizan\Documents\dev\dotnet-runtime\artifacts\log\Debug
##vso[task.setvariable isSecret=False;variable=TEMP;isOutput=True]C:\Users\poizan\Documents\dev\dotnet-runtime\artifacts\tmp\Debug
##vso[task.setvariable isSecret=False;variable=TMP;isOutput=True]C:\Users\poizan\Documents\dev\dotnet-runtime\artifacts\tmp\Debug
##vso[task.prependpath]C:\Program Files\dotnet
##vso[task.setvariable isSecret=False;variable=DOTNET_MULTILEVEL_LOOKUP;isOutput=True]0
##vso[task.setvariable isSecret=False;variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE;isOutput=True]1
MSBUILD : error MSB1001: Unknown switch.
Switch: -skiptests

For switch syntax, type "MSBuild -help"
(NETCORE_ENGINEERING_TELEMETRY=Category) Build failed.
```

**Comment by maryamariyan** [comment]
@poizan42 thanks for raising this. We just moved to dotnet/runtime repository and need to get updated as a result.
Related to: https://github.com/dotnet/runtime/issues/304

**Comment by poizan42** [comment]
It seems that the default was changed so now -buildtests is needed to built them, otherwise they won't be built. So it's just the documentation that needs to be updated.

**Comment by poizan42** [comment]
`-release` doesn't work either, it seems to be `-configuration Release` now.

**Comment by ViktorHofer** [comment]
The root coreclr.cmd/sh script is just a small wrapper which isn't yet on feature parity with its siblings: libraries.cmd/sh and installer.cmd/sh. We have a tracking issue for migrating most of the old script to msbuild files: https://github.com/dotnet/runtime/issues/97

**Comment by jkoritzinsky** [comment]
We've migrated the coreclr build scripts to the new system. Closing this as out of date.
