### ISSUE TITLE
Pass proxy to handler IHttpClientFactory

### ISSUE THREAD

**Issue by patrickiscoding** [dotnet/runtime#34904]
I would like to somehow pass a proxy when creating an instance of IHttpClientFactory. I know you can configure a HttpClientMessageHandler in Startup.cs but then I can't change the proxy afterwards. Normally I would just create a HttpClient each time I need it and pass a proxy to the handler i'm using for it. How would I do this when using IHttpClientFactory?

**Comment by karelz** [comment]
In general, you need to create your `HttpClientHandler` with the setting - see https://stackoverflow.com/a/52526366
cc @rynowak

**Comment by rynowak** [comment]
The request that we hear over and over from users re: `IHttpClientFactory` is not **How do I configure XYZ for HttpClient once?** - it's closer to **How do I configure XYZ for a request?**. (I know that's not how HttpClient works).

Here's the points that stand out to me:

>but then I can't change the proxy afterwards. 

> Normally I would just create a HttpClient each time I need it and pass a proxy to the handler i'm using for it. 

These usage patterns don't reflect how HttpClient wants to be used for best performance (long-lived) - but users want answers.

**Comment by karelz** [comment]
What are the scenarios to use proxy per request?
Or is it different proxy per endpoint / set of endpoints?

@patrickiscoding can you help us understand what exactly you're trying to achieve (regardless of APIs used)?

**Comment by patrickiscoding** [comment]
Yes sure @karelz , I want to use a different proxy in each controller. I make requests using HttpClient in a asp.net core api controller and the user passes the proxy he wants to use to the controller. Now I do not want to use HttpClient with using() statements since this could result into DNS issues and problems with too many open sockets. My question is, how would I achieve the same thing (as in obtaining a HttpClient instance from the HttpClientFactory) but set a proxy for the handler of the HttpClient that I am getting.

**Comment by karelz** [comment]
@patrickiscoding who is the user? Developer using your library? Or is it configuration of your app? Or is it the real user of the web app?
Does the app know the list of proxies upfront? Or is it dynamic information, potentially even changing?
What is the real-world scenario? (the setup) ... I can't quite wrap my head around it.

Each proxy requires its own connection / connection pool. The `HttpClient` model has a single proxy per instance. That is burned into its API design (as there is usually just 1 proxy in 99.99% of user cases), so not something that can be easily changed / enhanced in `HttpClient` IMO.
As such, one needs mapping of proxy -> `HttpClient` instance with the right proxy setup. I wonder if we could flex existing `HttpClientFactory` model to help with that in your scenario (e.g. if the list of proxies is known upfront, or incrementally change config if it is possible).

**Comment by rynowak** [comment]
@patrickiscoding - did you mean to close this?

**Comment by ransagy** [comment]
I've also come across this and was left confused; I want to leverage the `IHttpClientFactory` model/pattern, But some specific usage point needs a proxy (also another case with cookies, but thats a different topic).

Instantiating my own handler seems counter-productive - I want to avoid either having a singular instance not in the pool (or not refreshed in the pool to avoid DNS issues) but i don't want to add the proxy to a handler that might be reused by something later on when its back in the pool.

Clarification on these scenarios would be greatly appreciated. The documentation on `IHttpClientFactory` and the usages around it, including typed `HttpClient` use sites etc is very lacking to anything but the straight-and-narrow simple `HttpClient` usage, IMO.
