### ISSUE TITLE
JIT: "default(T) == null" does not emit a constant when T is Nullable<>

### ISSUE THREAD

**Issue by michkot** [dotnet/runtime#34906]
After toying with efficient detection of reference types / value types / nullable types I triggered a  discovery of generic context issue https://github.com/dotnet/runtime/issues/34641.

I now also find out that `default(T) == null` for T being  `Nullable<XXX>` in the following snippet does not produce a constant in ASM but rather builds what seems to be a composed "struct + HasValue bool" on stack and then `cmp`s to `0x0`.
[sharplab.io link with longer example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4aNXBihCwGBggYBvGg3FiG2WdR17gh46rBndqgCaGAvnOoB6ZwwCCXJgHkGAYQAJdwA5AHEAUQYAFQCASSZo32sGDAgGXBgYBggMFhgoBjA8GFwaAG0AKXEMUJgRfPEwAAoMAE8OGAgAMybgoQAbft5+mAAeBAA+AEopgF0aYgBmBmJyJBXSf1GogDVsfomGTW0jo+1XBgB3LKEMlLyGLuwVe+xVLugGPf6hLKj2kpobLAABWDAAvOCGCIBv0GDAEBxYLhcOIICIGOc3OwsrAOEMwDAbFdqiwGAByJ79DLk/SqJQiOASKQMJoVWJRFKSGBTE4nJYrNYMYAQCBwqIlDBNXb7BgAN32vKMx2Vp3EXVZNhgTwGUpl/SmEKhMMGStORy0qvNKwA7CklDITqdHFbbY99hkzAwXWdlRcJQoGFJchAbPzlqt1iKxQxYrgACLa7C676/f4dXDS77yxUnS3m4h2hX9PjhACOQg9TS1Ov6eu+My9PsxfrcACE8I1CqGYOHBVHRXC431Bu4s7Li2aVdbC6zi0bobCpk2ThcO6iwN2tX3I8LB7HcCP+m3x3DJ3mnUdo3DxLh9QJtfk6oT0zBvFAj8MYJyoYpfl61Q1Jpb3vR9YBEF8AXfT9gBGKIp1OfNrSOWcmnnSFF1NACjmbU4YGpXtXSQ5C3T/R1XWbZtVzcbwAGtHk+EVcjUAAOdYmkTWsMENbARGJZAUB3IVrwPTjkzrAB1UkogdAAxaBUxKU8cwNC9XREkDvgfLonwg78oI/WEvx/Bga3E+tFQXE1+mwnQgM0/ZtN0yCOmgozYO/BCLUvAs7TQ2UMOs5cfNwo58IyHziOQ2cyNsyihIHGM4zE3VgmgfB9hPfUVKnKK7M1JNdVPQ1AqXSKfNOWd0ONWE4p82dksKutFNfTNJxXZUBV3ETGq4vx9n6ZTz2VPKGoTJqMBagE2sVDr7CAA=)

```cs
public static class C<TVal>  {
  public static bool Test(TVal val)
  {
     if (default(TVal) == null)
     {
        return true;
     }
     return false;
  }
}
```

The produced assembly is (I guess) valid, although quite inefficient. (And I did not find other good way to determine whether type is reference of a non-nullable valuetype.)

**Comment by EgorBo** [comment]
> I now also find out that default(T) == null for T being Nullable<XXX> in the following snippet does not produce a constant in ASM

why should it produce a constant? a variable of a Nullable type can be null (or not)

**Comment by khellang** [comment]
@michkot Have you seen https://github.com/dotnet/runtime/pull/1157 and https://github.com/dotnet/runtime/pull/32098?

**Comment by benaadams** [comment]
> why should it produce a constant? a variable of a Nullable type can be null (or not)

`default` of a nullable is always null so its constant?

e.g. `default(int?)` is always `null`

**Comment by EgorBo** [comment]
> > why should it produce a constant? a variable of a Nullable type can be null (or not)
> 
> `default` of a nullable is always null so its constant?
> 
> e.g. `default(int?)` is always `null`

Ah, oops.

**Comment by EgorBo** [comment]
@benaadams @michkot anyway I can't repro it on my master, probably is already fixed (e.g. here? https://github.com/dotnet/runtime/pull/32269/files)

**Comment by michkot** [comment]
> @benaadams @michkot anyway I can't repro it on my master, probably is already fixed (e.g. here? #32269)
> 
> It's not the first time people use sharplab with .NET Core 3.0 to file issues against RyuJIT-master 😐

Thanks for looking into it. I will close the issue now then 👍 . Can you point me at some resources/docs so I can try it myself at current master @EgorBo ? (I had luck the last time with sharplab, so I tried it again).

**Comment by michkot** [comment]
> @michkot Have you seen #1157 and #32098?

I did not explicitly, but I noticted that work being done in other issue. That feature/opt. is also nice when you need reference/value type distinction. I trully care about null being a default here though :)

**Comment by EgorBo** [comment]
@michkot 
my workflow is this:
```
git clone git@github.com:dotnet/runtime.git
cd runtime/src/coreclr
./build.sh -checked
```
once it finishes:
```
cd myConsoleApp
dotnet publish -c Release -r osx-x64
cp ~/runtime/artifacts/bin/coreclr/OSX.x64.Checked/* ~/myConsoleApp/bin/netcoreapp3.1/osx-x64/publish
cd ~/myConsoleApp/bin/netcoreapp3.1/osx-x64/publish
COMPlus_JitDisasm=MyNamespace.MyProgram:MyMethod ./myConsoleApp
```
Also, let me promote my add-in for that: https://github.com/EgorBo/Disasmo (it still needs a pre-built runtime in Checked config)
