### ISSUE TITLE
Delete task code that has been moved to the shared framework SDK in Arcade

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#34907]
This copy of `CreateFrameworkListFile` is unused and should be deleted:

https://github.com/dotnet/runtime/blob/59a24e5/tools-local/tasks/installer.tasks/CreateFrameworkListFile.cs

True source:

https://github.com/dotnet/arcade/blob/8935804/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/src/CreateFrameworkListFile.cs

Any other leftover copies of tasks from the sharedfx SDK should be removed too.

**Comment by NikolaMilosavljevic** [comment]
@v-chayan can you validate that this is fixed and close?

**Comment by v-chayan** [comment]
Verified and close this issue.
