### ISSUE TITLE
Create a MacOS version of createdump

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#34916]
This is going to be quite of bit of work even with Noah’s idea of using the existing ELF core dump writing from the Linux createdump. The work is changing the read memory API and gathering the crash info state (memory, threads, modules) and it is completely different on MacOS. The biggest difficulty is that the MacOS vm_read_overwrite/task_for_pid APIs used to read memory requires the app (createdump) to be signed with a special cert. We need to investigate the cert details (all I found was a way to do it locally which only works locally) and if our build system can sign MacOS binaries.

**Comment by noahfalk** [comment]
I'd suggest we at least explore mechanisms we could use in-proc to collect memory/thread/module lists, then expose that data via diagnostic server RPC APIs. This may not make the work any cheaper, but if we can do it we have avoided the signing requirements on Mac as an ongoing concern. The work probably also gets us closer to being able to do CreateDump on Linux without using ptrace.

**Comment by mikem8361** [comment]
- [ ] Build MacOS version of createdump that generates ELF core dumps.
- [ ] Sign the MacOS createdump with the “task_for_pid-allow” entitlement.
- [ ] Implement PAL_VirtualUnwindOutOfProc for MacOS, otherwise the DAC can't unwind HelperMethodFrames.
- [ ] Add abort/crash trigger to the runtime to launch createdump on MacOS.
- [ ] Update createdump [doc](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/xplat-minidump-generation.md) for MacOS and Windows createdump.
- [ ] Enable testing in the diagnostics repo dotnet-dump tests

**Comment by mikem8361** [comment]
PR #https://github.com/dotnet/runtime/pull/39982 added the guard env var and updated the docs.
