### ISSUE TITLE
Enable knownValues for custom KnownHeaders in HttpClient

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#34923]
We currently prohibit "knownValues" in KnownHeader in HttpClient:
https://github.com/dotnet/runtime/blob/f380910ce9dd4f38e68efec6feb7b80c8019f397/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeader.cs#L24
But for headers where we expect only a few predictable header values, adding them can help save string allocations.  We should remove this constraint, and update KnownHeaders to include known values where applicable for "custom" headers:
https://github.com/dotnet/runtime/blob/f380910ce9dd4f38e68efec6feb7b80c8019f397/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs#L11-L102

cc: @scalablecory

**Comment by scalablecory** [comment]
I'd also love to revamp the knownvalues concept to function for HTTP/2 static table headers.
