### ISSUE TITLE
Not Building Referenced projects while BuildingInsideVisualStudio

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#34925]
After doing a pass of a vertical build if i build an individual project for a /p:BuildTargetFramework=netcoreapp5.0-unix config from the command line as ResolveProjectReferences builds all the projectReferences for this tfm.

This is not the case while building the project from building inside the VS eg 
```
stem.Utf8String.Experimental.dll

Build FAILED.

C:\Users\anagniho\.nuget\packages\microsoft.dotnet.genfacades\5.0.0-beta.20201.2\build\Microsoft.DotNet.GenPartialFacadeSource.targets(30,5): error : Could not find a part of the path 'C:\git\runtime\artifacts\bin\System.Runtime\netcoreapp5.0-Unix-Debug\System.Runtime.dll'. [C:\git\runtime\src\libraries\System.Utf8String.Experimental\src\System.Utf8String.Experimental.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.31
``` 
This is bcoz sdk assumes the project references are already build by the IDE and doesnt run the msbuild task during project references https://github.com/microsoft/msbuild/blob/64c8e4a18e7cf7f064fbad304ea7ed877cdaa0a1/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1812

By default we are building for all netcoreapp5.0-{TargetOS} inside the VS, we should either fix the msbuild or remove edit the default VS behavior

cc @ericstj @ViktorHofer @safern

**Comment by danmosemsft** [comment]
I don't have full context here, but my general assumption as a user is that a build in VS will build only projects that appear in VS. IOW, if I work on library X, I expect to build all other libraries (using the command line) then open X and have build just build X. This makes the inner loop fastest. If I want to build more, I should be able to add it to my solution and it build build too. If I want to build everything in VS, ideally I can open everything in VS - that we're working on separately of course.

**Comment by ericstj** [comment]
@Anipik can you elaborate on why you think this is a problem?  Perhaps describe the end to end experience you are aiming for?

**Comment by ericstj** [comment]
I chatted with @Anipik and he mentioned this was causing a problem for the scenario where you do:
1. Build vertical from the root.
2. Open a project that uses `ProjectReference`s to projects that cross-target by runtime.  Related https://github.com/dotnet/runtime/issues/34653

Because the vertical will only build assemblies for the TargetOS, the ProjectReferences for other OS's aren't built, and building in VS will fail.

**Comment by ViktorHofer** [comment]
I thought we filter other inapplicable OSs out when we dispatch to inner builds?

**Comment by ericstj** [comment]
In VS we build for all OS's https://github.com/dotnet/runtime/blob/34685241a256db73769ed595f2a132ee4535235a/src/libraries/Directory.Build.props#L24.

This is what was done to allow folks to cross-target from VS.  It's a middle ground between building *everything* as the SDK does and building just the single TargetOS as we do in the vertical build.

@Anipik and I had discussed that one fix here would be to just update the SLNs to have their project reference closure for src.

**Comment by ViktorHofer** [comment]
> @Anipik and I had discussed that one fix here would be to just update the SLNs to have their project reference closure for src.

+1 as it will also help with switching to P2Ps, away from named references (if we want to do this in the future). Can we please do that consistently for all slns?
