### ISSUE TITLE
Add test support for additional platforms

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#3492]
At the moment, this repo doesn't run tests on platforms that were cross compiled for (i.e. ARM32). This repo should support testing for all supported platforms.

**Comment by NikolaMilosavljevic** [comment]
@AaronRobinsonMSFT is this something that can be handled in the host test infra? Is this required for 5.0?

**Comment by AaronRobinsonMSFT** [comment]
@NikolaMilosavljevic I don't know if this is still an issue now that we have consolidated the dotnet/setup repo into the dotnet/runtime repo. This was a specific issue with the dotnet/setup repo.

**Comment by AaronRobinsonMSFT** [comment]
I am going to close this since we do run tests in dotnet/runtime on the ARM platform.
