### ISSUE TITLE
Make build configurable to ensure RPM/Debian packages are built

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3493]
## Steps to reproduce
I build Core-Setup on a machine that I *think* is set up to build RPM packages, but when the build completes, I don't see packages in the output directory. (Same scenario for Debian packages.)

## Expected  behavior
I can run the build in a way that indicates I want to create RPM packages, and the build tells me in what way my machine isn't set up correctly. ("Error: Can't find `fpm` command!")

## Actual behavior
The build succeeds. Somewhere in build output it tells me that it didn't find `fpm` and skipped the package build, but it isn't easy to see.

This is much worse in official builds: if the machines are updated and aren't set up correctly, we might silently stop producing RPM/Debian packages. (There might be some other part of the build that eventually consumes them and raises it as a build failure--I'm not sure. This problem hasn't actually occurred so far.)

**Comment by NikolaMilosavljevic** [comment]
Obsolete - closing.
