### ISSUE TITLE
Compiled regex can lead to infinite matching

### ISSUE THREAD

**Issue by bahusoid** [dotnet/runtime#34947]
See below examples of regex and values that lead to infinite matching:

```C#
[Test]
public void RegexIssue_InfiniteMatchingExamples()
{
	//The following combinations of regex and values lead to infinite matching
	var regex = new Regex(@"^([^a-wA-WyzYZ]*\d+[^a-wA-WyzYZ]*)+$", RegexOptions.Compiled);
	var isMatch = regex.IsMatch("666-837-7777/444-327-8888 ext");

	var regex2 = new Regex(@"^(([xX]|\W)*\d+([xX]|\W)*)+$", RegexOptions.Compiled);
	bool isMatch2 = regex2.IsMatch("123456789012345678901234567890q");
}
```
Regexs are not really used anywhere so no need to suggest how it can be improved.

Tested on .NET Core 2.0/3.1 and Full .NET Framework 4.7

Maybe it's related to https://github.com/dotnet/runtime/issues/27282.
Though I'm not sure why it's targeted as 3.0 - I checked it on .NET Core 3.1 and it's still can't be evaluated.

**Comment by stephentoub** [comment]
This isn't related to RegexOptions.Compiled.  It's entirely about the expression you've input, which has what's referred to as "catastrophic backtracking".  For a backtracking-based regex engine, it can lead to an exponential amount of processing.  You can see the same thing with the PCRE engine if you go to http://regex101.com and enter `^([^a-wA-WyzYZ]*\d+[^a-wA-WyzYZ]*)+$` as the expression and `666-837-7777/444-327-8888 ext` as the test string.  It's for such expressions that Regex has a Timeout.

**Comment by bahusoid** [comment]
Well it works well with GoLang engine...

**Comment by stephentoub** [comment]
Yes, RE2 uses a non-backtracking engine.  It has deterministic performance, but can't support all of the syntax that the .NET regex engine supports, e.g. back references.
