### ISSUE TITLE
GCStress failures in _il_*jumps4, _il_*valftn_t

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#34957]
Failures in Linux arm GCStress=C

There are multiple failure modes. E.g.:
`
/root/helix/work/workitem/JIT/Methodical/VT/callconv/_il_dbgjumps4/_il_dbgjumps4.sh: line 275: 2491 Segmentation fault $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"\n\nReturn code: 1\nRaw output file: /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/VT/callconv/_il_dbgjumps4/_il_dbgjumps4.output.txt\nRaw output:\nBEGIN EXECUTION\n/root/helix/work/correlation/corerun _il_dbgjumps4.dll ''\n--VT-- : ->ToStringHelper\nWriting minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.2491.dmp\nWritten 51798016 bytes (12646 pages) to core file\nExpected: 100\nActual: 139\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/root/helix/work/correlation\n> /root/helix/work/workitem/JIT/Methodical/VT/callconv/_il_dbgjumps4/_il_dbgjumps4.sh\nExpected: True\nActual: False
`

https://dev.azure.com/dnceng/public/_build/results?buildId=599203&view=ms.vss-test-web.build-test-results-tab&runId=18874720&resultId=107939&paneView=debug

Tests:
```
JIT/Methodical/VT/callconv/_il_dbgjumps4/_il_dbgjumps4.sh
JIT/Methodical/VT/callconv/_il_reljumps4/_il_reljumps4.sh
JIT/Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.sh
JIT/Methodical/Invoke/fptr/_il_relvalftn_t/_il_relvalftn_t.sh
```

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/34002

**Comment by AndyAyersMS** [comment]
Wasn't this a test run vs a PR (#341)?

**Comment by BruceForstall** [comment]
Good point; I didn't notice that when I was looking at the adjacent reported issues.

@erozenfeld This is from your manual run. I'm going to close it.
