### ISSUE TITLE
"CreateAppHost" task failed unexpectedly fix release date

### ISSUE THREAD

**Issue by ehelin** [dotnet/runtime#34950]
Hi:

We are using .net core 3.1 and get this error most of the time running local host (see 'Error').  I found issue 3831 (see 'Fix Issue') and it says a fix should be part of this April's release.  Has this been released?  I installed 3.1.3 and the issue is still present.

Thank you!

Eric

**Error**
Error MSB4018 - The "CreateAppHost" task failed unexpectedly AND HResultException: 8007006E

Fix Issue
https://github.com/dotnet/runtime/issues/3831

**Comment by ehelin** [comment]
area-SDK

**Comment by hoyosjs** [comment]
This is set for release 3.1.4 (April release) of the runtime. Currently it hasn't been released, usually this happens in the later portion of the month.

**Comment by swaroop-sridhar** [comment]
I've made a note about the expected release date in #3831

**Comment by madhusameena** [comment]
When can we expect the release
This is causing lot of problems  
Any workaround to eliminate this (in build agents) ?

**Comment by jeanpoelie** [comment]
Running into problems as well, blank (default) 3.1.2 .net core project when deploying via azure devops. Running it in visual studio 2019 is giving me zero issues.

**Comment by e8matrix** [comment]
I turn this off and it worked. I guess it doesn't like .net sdk :)

![image](https://user-images.githubusercontent.com/55712992/81303961-684bd000-904a-11ea-8705-c9e7715c2052.png)

**Comment by jeanpoelie** [comment]
> I turn this off and it worked. I guess it doesn't like .net sdk :)
> 
> ![image](https://user-images.githubusercontent.com/55712992/81303961-684bd000-904a-11ea-8705-c9e7715c2052.png)

I unfortunatly cannot do this on azure devops

**Comment by e8matrix** [comment]
@jeanpoelie for now on my local machine I need to do this until they figure out a fix. For me it works on DevOps though.

**Comment by darrylluther** [comment]
All of these issues (this one and the linked issues) are closed like this has been fixed, but I'm still experiencing this on pretty much every other build. Is there a release date for the fix? There's a note that references a release date was added to [#3831](https://github.com/dotnet/runtime/issues/3831), but that note just has a link back to this issue and says it will be released later this month (which was April).

**Comment by swaroop-sridhar** [comment]
@darrylluther  I heard that  .net core 3.1.4 is expected to be released this week.
