### ISSUE TITLE
System.Drawing: Image.Save() changes color of image

### ISSUE THREAD

**Issue by pweissenbacher** [dotnet/runtime#34954]
# Issue Title

When saving a BMP image file as JPEG, using System.Drawing.Image.Save() changes colors of resulting image.
Specifically: Cyan colors (#2ce7b2) become magenta (#b22be7).

# General

Bug can be reproduced using following code (test image can be found in attached ZIP archive):

[test_small.zip](https://github.com/dotnet/core/files/4473260/test_small.zip)

```csharp
using System;
using System.Drawing;
using System.Drawing.Imaging;

namespace ConvertBmpToJpg
{
    class Program
    {
        static void Main(string[] args)
        {
            var imageFile = "test_small.bmp";
            var image = Image.FromFile(imageFile);

            var imageToSave = new Bitmap(image);

            SaveJpegWithQualityFactor(imageToSave, "testBMPConverted.jpeg", 75L);
        }

        private static void SaveJpegWithQualityFactor(Bitmap imageToSave, string imagePath, long qualityFactor)
        {
            // Define JPEG compression level
            var jpgEncoder = GetEncoder(ImageFormat.Jpeg);

            // Create an Encoder object based on the GUID  
            // for the Quality parameter category.  
            var qualityEncoder = Encoder.Quality;

            // Create an EncoderParameters object. 
            var encoderParameters = new EncoderParameters(1);

            var qualityFactorParam = new EncoderParameter(qualityEncoder, qualityFactor);
            encoderParameters.Param[0] = qualityFactorParam;
            imageToSave.Save(imagePath, jpgEncoder, encoderParameters);
        }

        private static ImageCodecInfo GetEncoder(ImageFormat format)
        {
            var codecs = ImageCodecInfo.GetImageDecoders();
            foreach (var codec in codecs)
            {
                if (codec.FormatID == format.Guid)
                {
                    return codec;
                }
            }
            return null;
        }
    }
}
```

# Environment

We tried the above code in different environments and found following results.

![grafik](https://user-images.githubusercontent.com/57172030/79193132-4c2d8800-7e2a-11ea-9268-aae3df492731.png)

Additionally, we tried:

- OS: Windows 10 Pro - 1809, 17763.1098, SDK: dotnet core 3.1.201
Here, the results are as expected (same color in both images jpeg & bmp)

**Comment by safern** [comment]
Related to: #34959

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
