### ISSUE TITLE
JPEG image re-save is not working in Linux OS

### ISSUE THREAD

**Issue by Deepak211** [dotnet/runtime#34959]
# Issue Title

JPEG image re-save is not working in Linux OS

# General

When tried to re save a **JPEG image** using **System.Drawing**, it provides an output JPEG image with different color in Linux Operating System. It works fine in Windows operating system. I have used **.Net Core console project** to implement the same using the following **C# code snippet**.

`using System;`
`using System.IO;`
`using System.Drawing;`

`namespace ImageExtracter`
`{`
    `class Program`
   `{`
        `static void Main(string[] args)`
        `{`
            `Image image = Image.FromFile("Input_Image.jpeg");`
            `Stream stream = new MemoryStream();`
            `image.Save(stream, image.RawFormat);`
            `stream.Position=0;`
            `Image img = Image.FromStream(stream);`
            `img.Save("Output_Image.jpeg", img.RawFormat);`
        `}`
    `}`
`}`

Please find the images below.

**Input_Image.jpeg** - The image loaded as input 

![Input_Image](https://user-images.githubusercontent.com/52351496/72043993-aa514900-32d8-11ea-9290-2d48e87249f4.jpeg)

**Output_Image.jpeg** - The image obtained

![Output_Image](https://user-images.githubusercontent.com/52351496/72043983-a1607780-32d8-11ea-8f1f-d55f98f006ae.jpeg)

Kindly check this and let me know your suggestion to resolve this issue. Also, please let me know if you need any further details.

**Comment by safern** [comment]
Thanks @Deepak211 I will have to debug this to see what's going on. Thanks for opening the issue.

**Comment by uthandaraja** [comment]
Any update on the solution for this issue?

**Comment by uthandaraja** [comment]
Please provide update or solution on this issue.

**Comment by safern** [comment]
Hello @uthandaraja sorry for the delay on responding. I just assigned the milestone to 5.0 so that it is taken care on our 5.0 release.

**Comment by jeffhandley** [comment]
I'm sorry we weren't able to get to this issue during 5.0.0; we're going to have to move it to 6.0.0.

**Comment by safern** [comment]
@Deepak211 we are not going to fix this because we have decided to no longer support `System.Drawing.Common` for non-Windows platforms.

Please look at this document for the motivation behind it: https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

Also as an alternative I suggest looking at `SkiaSharp` or `ImageSharp` to achieve this scenario.
