### ISSUE TITLE
CLS-Compliant issue spotted during intellisense for ref in System.DirectoryServices

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#34953]
System.Runtime references are not getting resolved in during the design time build for netstandard2.0 

cc @ericstj @ViktorHofer @safern

**Comment by ericstj** [comment]
Is this for reference assembly or implementation?  Did you look into how the reference is satisfied during actual build to see what was going wrong in design time?

**Comment by ViktorHofer** [comment]
@Anipik do you have more data on this to follow-up?

**Comment by Anipik** [comment]
No, i will take another look

**Comment by safern** [comment]
Is the `System.Runtime` reference correct, should it be excluded from `netstandard2.0` configuration, there we should be building against `netstandard.dll` not `System.Runtime`, right?

**Comment by Anipik** [comment]
The inellisense for the sources is working , ref intellisense throws some cls compliant errors. Moving it to 6.0.0

**Comment by ViktorHofer** [comment]
> System.Runtime references are not getting resolved in during the design time build for netstandard2.0

System.Runtime's contract compiles against `$(NetCoreAppCurrent)` only. I'm not sure how netstandard2.0 comes into play here.
Closing as I didn't observe any CLS-Compliant design time build issues when I just recently tested the System.Runtime VS experience.
