### ISSUE TITLE
DCS_MyPersonSurrogate_Stress test failed

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#34962]
The assert indicates that there are distinct NonSerializablePersonForStress objects, with the same field values.

This comment suggests that the test is intended to verify referential identity:
```
               // We put the same object at two different slots. Because the DataContract type
                // is marked with [DataContract(IsReference = true)], after serialization-deserialization,
                // the objects at this two places should be the same object to each other.
```
```
Error message
Assert.Equal() Failure\nExpected: Person[Name=name,Age=30]\nActual: Person[Name=name,Age=30]


Stack trace
   at DataContractSerializerTests.DCS_MyPersonSurrogate_Stress() in /_/src/libraries/System.Runtime.Serialization.Xml/tests/DataContractSerializerStressTests.cs:line 62
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 360
```
https://dev.azure.com/dnceng/public/_build/results?buildId=598762&view=ms.vss-test-web.build-test-results-tab&runId=18856272&resultId=101137&paneView=debug

netcoreapp5.0-Linux-Debug-arm64-Mono_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-h

**Comment by safern** [comment]
This failed in rolling build as well in master. Updated the title, to remove "preview3".

**Comment by safern** [comment]
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#628369](https://dev.azure.com/dnceng/public/_build/results?buildId=628369)|Rolling|1|
|[#628656](https://dev.azure.com/dnceng/public/_build/results?buildId=628656)|Rolling|1|
### Configurations
- netcoreapp5.0-OSX-Release-x64-Mono_release-OSX.1013.Amd64.Open
- netcoreapp5.0-Windows_NT-Release-x64-Mono_release-Windows.10.Amd64.Server19H1.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#628369](https://dev.azure.com/dnceng/public/_build/results?buildId=628369)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/29e740e1-ba9f-4865-90bf-9f2a76875c58/workitems/System.Runtime.Serialization.Xml.Tests/files/console.eb6e50ec.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/29e740e1-ba9f-4865-90bf-9f2a76875c58/workitems/System.Runtime.Serialization.Xml.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-helixqueuesupdate-29e740e1ba9f486590/System.Runtime.Serialization.Xml.Tests/fe136a14-d18f-4f45-977f-a273a7563f54.log?sv=2019-02-02&se=2020-05-12T20%3A43%3A56Z&sr=c&sp=rl&sig=AAflWYySYm7cOmyeczcDAwuojw1TFH8KJMsPuTUa2u0%3D)|
|[#628656](https://dev.azure.com/dnceng/public/_build/results?buildId=628656)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/7b184630-d730-41ec-a734-c91c446932d5/workitems/System.Runtime.Serialization.Xml.Tests/files/console.844b65a5.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/7b184630-d730-41ec-a734-c91c446932d5/workitems/System.Runtime.Serialization.Xml.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7b184630d73041eca7/System.Runtime.Serialization.Xml.Tests/eb836df8-1a72-45c8-a046-de927beeb539.log?sv=2019-02-02&se=2020-05-13T02%3A56%3A42Z&sr=c&sp=rl&sig=FY0f44EAWONDjO3dpb%2BbYhYnmabm1izRaiXiZozwsws%3D)|

**Comment by HongGit** [comment]
Duplicate #35066
