### ISSUE TITLE
Read plain Rsa keys

### ISSUE THREAD

**Issue by daviatorstorm** [dotnet/runtime#34960]
Using dotnet core 3.1

Have generated private and public and need to do extra actions to transform from plain to xml style key. Is there any official way to transform? If not - I have a suggestion to use [this](https://github.com/stulzq/DotnetCore.RSA/blob/master/DotnetCore.RSA/RSAHelper.cs) code to read the keys.

**Comment by daviatorstorm** [comment]
Its okey to use this practice https://vcsjones.dev/2019/10/07/key-formats-dotnet-3/ ?

**Comment by vcsjones** [comment]
> Have generated private and public and need to do extra actions to transform from plain to xml style key. Is there any official way to transform? 

I'm not clear what a "plain" RSA key is, can you give an example?

I assume for "xml-style" you mean the output of `RSA.ToXmlString`?

**Comment by daviatorstorm** [comment]
I meant that plain

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxzYuc22QSst/dS7geYYK
5l5kLxU0tayNdixkEQ17ix+CUcUbKIsnyftZxaCYT46rQtXgCaYRdJcbB3hmyrOa
vkhTpX79xJZnQmfuamMbZBqitvscxW9zRR9tBUL6vdi/0rpoUwPMEh8+Bw7CgYR0
FK0DhWYBNDfe9HKcyZEv3max8Cdq18htxjEsdYO0iwzhtKRXomBWTdhD5ykd/fAC
VTr4+KEY+IeLvubHVmLUhbE5NgWXxrRpGasDqzKhCTmsa2Ysf712rl57SlH0Wz/M
r3F7aM9YpErzeYLrl0GhQr9BVJxOvXcVd4kmY+XkiCcrkyS1cnghnllh+LCwQu1s
YwIDAQAB
-----END PUBLIC KEY-----
```

**Comment by vcsjones** [comment]
In .NET Core 3 you can get close to doing this using something like this:

```csharp
using RSA rsa = RSA.Create();
rsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(@"
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxzYuc22QSst/dS7geYYK
5l5kLxU0tayNdixkEQ17ix+CUcUbKIsnyftZxaCYT46rQtXgCaYRdJcbB3hmyrOa
vkhTpX79xJZnQmfuamMbZBqitvscxW9zRR9tBUL6vdi/0rpoUwPMEh8+Bw7CgYR0
FK0DhWYBNDfe9HKcyZEv3max8Cdq18htxjEsdYO0iwzhtKRXomBWTdhD5ykd/fAC
VTr4+KEY+IeLvubHVmLUhbE5NgWXxrRpGasDqzKhCTmsa2Ysf712rl57SlH0Wz/M
r3F7aM9YpErzeYLrl0GhQr9BVJxOvXcVd4kmY+XkiCcrkyS1cnghnllh+LCwQu1s
YwIDAQAB"), out _);
string xml = rsa.ToXmlString(false);
```

What .NET Core 3 cannot do for you is extract the base64 contents between the PEM boundaries. You will need some mechanism or parsing to get the base64 contents between the PEM boundaries.

In .NET 5 (currently in preview) this will be possible in-the-box using:

```csharp
using RSA rsa = RSA.Create();
rsa.ImportFromPem(@"
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxzYuc22QSst/dS7geYYK
5l5kLxU0tayNdixkEQ17ix+CUcUbKIsnyftZxaCYT46rQtXgCaYRdJcbB3hmyrOa
vkhTpX79xJZnQmfuamMbZBqitvscxW9zRR9tBUL6vdi/0rpoUwPMEh8+Bw7CgYR0
FK0DhWYBNDfe9HKcyZEv3max8Cdq18htxjEsdYO0iwzhtKRXomBWTdhD5ykd/fAC
VTr4+KEY+IeLvubHVmLUhbE5NgWXxrRpGasDqzKhCTmsa2Ysf712rl57SlH0Wz/M
r3F7aM9YpErzeYLrl0GhQr9BVJxOvXcVd4kmY+XkiCcrkyS1cnghnllh+LCwQu1s
YwIDAQAB
-----END PUBLIC KEY-----");
string xml = rsa.ToXmlString(false);
```

**Comment by bartonjs** [comment]
It seems as though the question has been answered, so closing the issue.  If there's still an outstanding question feel free to re-open or just comment.
