### ISSUE TITLE
InvalidEnumArgumentException quality-of-life API improvements

### ISSUE THREAD

**Issue by chwarr** [dotnet/runtime#34983]
There it too much repetitive ceremony when using
[`InvalidEnumArgumentException`][ieae] on invalid enum values. This proposal
outlines two potential ways of eliminating said ceremony.

If an API change is accepted here, I can likely contribute it.

# Background

The `System.ComponentModel.InvalidEnumArgumentException` type exists to
indicate that an enum value is invalid for some reason. It has a constructor
[overload] `(string argumentName, int invalidValue, Type enumClass)` that

> \[creates\] a localized message saying that the `argumentName` parameter
> was invalid because the value passed in was invalid, and that the value
> should be one of the values in the enumeration class.

An example message when invoke as `new InvalidEnumArgumentException("color",
100, typeof(System.Drawing.KnownColor))` is:

> The value of argument 'color' (100) is invalid for Enum type 'KnownColor'.
> (Parameter 'color')

This is often used as the default in switch statements/expressions.

# Option 1: `Create` helper method

Option 1 adds a static factory method, `Create<TEnum>(string argumentName,
TEnum invalidValue)`.

```csharp
class InvalidEnumArgumentException
{
    // ...

    public static InvalidEnumArgumentException Create<TEnum>(
        string argumentName,
        TEnum invalidValue)
        where TEnum : Enum
    {
        return new InvalidEnumArgumentException(
            argumentName,
            Convert.ToInt32(invalidValue),
            typeof(TEnum));
    }
}
```

Here's a code diff showing how this new method would be used in
representative code:

```diff
--- before.cs
+++ proposal-create.cs
@@ -14,7 +14,7 @@
             Color.Blue => "like the ocean",
             Color.Green => "like the leaves of a tree",
             Color.Purple => "like an eggplant",
-            _ => throw new InvalidEnumArgumentException(nameof(c), (int)c, c.GetType()),
+            _ => throw InvalidEnumArgumentException.Create(nameof(c), c);
         };
     }
 }
```

Some alternative names:

* `For()` (I find `InvalidEnumArgumentException.For(nameof(c), c)` quite
  readable, but it may be "too cute". ☺)
* `Make()`
* `New()` (Though, would this be problematic in PowerShell?)

Pros:

* Type deduction kicks in most of the time, and the enum type need not be mentioned.
* No existing `catch (InvalidEnumArgumentException)` will break.

Cons:

* It's a little odd to throw the result of a method. Perhaps doubly so for a
  factory method hanging off an exception class.
    * But, I don't know another way to avoid needing to mention the enum type.
    Such type deduction factories do exist already, like
    [`Tuple.Create()`][tuple-create].

# Option 2: `InvalidEnumArgumentException<TEnum>`

Option 2 is to introduce `InvalidEnumArgumentException<TEnum>` with a single
constructor<sup>1</sup> that takes the argument name and the invalid enum
value.

```csharp
class InvalidEnumArgumentException<TEnum> : InvalidEnumArgumentException
    where TEnum : Enum
{
    public InvalidEnumArgumentException(string argumentName, TEnum invalidValue)
        : base(argumentName, Convert.ToInt32(invalidValue), typeof(TEnum))
    {
    }
}
```

<sup>1</sup> Serialization is elided here. It's assumed to be needed.

Here's a code diff showing how this new type would be used in representative
code:

```diff
--- before.cs
+++ proposal-type.cs
@@ -14,7 +14,7 @@
             Color.Blue => "like the ocean",
             Color.Green => "like the leaves of a tree",
             Color.Purple => "like an eggplant",
-            _ => throw new InvalidEnumArgumentException(nameof(c), (int)c, c.GetType()),
+            _ => throw new InvalidEnumArgumentException<Color>(nameof(c), c);
         };
     }
 }
```

Pros:

* No existing `catch (InvalidEnumArgumentException)` will break.
  `InvalidEnumArgumentException<TEnum>` is a `InvalidEnumArgumentException`.
  (I think.)
* Fits into the existing `throw new SomeExceptionType...` pattern.

Marginal:

* `InvalidEnumArgumentException<Color>` is different from
  `InvalidEnumArgumentException<HttpStatusCode>` is different from
  `InvalidEnumArgumentException`.

Cons:

* Adds a new type.
* One still has to repeat the enum type when `new`ing the exception.
* Potential serialization compability concerns when trying to deserialize
  `InvalidEnumArgumentException<Color>` by older runtimes. Slicing to the
  base would probably be fine here.

[ieae]: https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.invalidenumargumentexception.-ctor?view=net-5.0
[overload]: https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.invalidenumargumentexception.-ctor?view=net-5.0#System_ComponentModel_InvalidEnumArgumentException__ctor_System_String_System_Int32_System_Type_
[tuple-create]: https://docs.microsoft.com/en-us/dotnet/api/system.tuple.create?view=net-5.0

**Comment by charlesroddie** [comment]
This is a C# limitation: lack of exhaustiveness checking. If C# had exhaustiveness checking then all this would happen automatically without a need for a default case and manual creation of an exception. So this should be addressed in C# rather than in the runtime.

**Comment by chwarr** [comment]
@safern, it looks like you're [the owner of `System.ComponentModel`](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md). Can you help get this API proposal moved along? It looks to me like it's waiting for an [owner to be assigned](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md#steps).

**Comment by chwarr** [comment]
@charlesroddie, while exhaustiveness checking in C# would be helpful, I see this proposal complementing it. Even with exhaustiveness checking there will still be cases when one needs to handle invalid enum members at runtime. Examples I can think of:

* Deserialization.
* Assemblies that were coded/built against different definitions of the enum. (E.g., different versions of the enum were available at compile time, binary assembly compat)
* As an escape hatch when an exhaustiveness checking is too conservative and manual code still needs to be written.
* Languages and versions of languages without exhaustiveness checking.

(Also, I can contribute this improvement. I don't have enough C# compiler skills to contribute exhaustiveness checking. 😀).

**Comment by safern** [comment]
Thanks, @chwarr for your suggestion. 

I clearly understand that this would reduce the dance of having to call `object.GetType` or `typeof(type)` when creating the new exception type. 

However, I don't think we follow this pattern anywhere in the framework, at least from what I remember. While it is nice to remove an extra parameter, I don't think it is worth the overhead of adding a `Create` method just to get type resolution kick in here. I rather have the exception been created with `new` when throwing it rather than calling a factory method. In my honest opinion I don't think this would meet the bar for API Review and would most likely not be approved.

**Comment by chwarr** [comment]
Thank you for taking a look and getting this to closure.

**Comment by safern** [comment]
Thanks @chwarr for the proposal and hope to see more proposals from you to make .NET better 😄
