### ISSUE TITLE
behavior of List.GetRange is wrong 

### ISSUE THREAD

**Issue by fallshuang** [dotnet/runtime#34989]
List<int> ms = new List<int>();            
            ms.Add(0);
            var ns = ms.GetRange(1, 0);

The start index '1'  is not a valid index .  but this code  doesn't throw exception

**Comment by stephentoub** [comment]
> The start index '1' is not a valid index . but this code doesn't throw exception

This is by design. Most .NET collections consider the position just after the last element to be a valid index as long as it doesn't actually try to dereference an element at that position, which this won't, because the length is 0.  For example, this will work fine, returning -1:
```C#
Array.IndexOf(new string[1], "hello", 1)
```

Thanks.
