### ISSUE TITLE
Wrong FileVersion for Mono's version of System.Private.CoreLib

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#34993]
Currently, it has the generic dev FileVersion=42.42.42.42424 even in the official build.

**Comment by directhex** [comment]
The good news is this appears to be a minor Yaml issue in runtime-official. Mono respects the OfficialBuildId property, we just aren't setting it in CI.

**Comment by directhex** [comment]
https://github.com/dotnet/runtime/pull/35002
