### ISSUE TITLE
.NET Core No OID value matches this name

### ISSUE THREAD

**Issue by pantonis** [dotnet/runtime#34995]
I migrated from .NET 4.7.2 to .NET Core 3.1 and trying to verify signed data and I get the following error ```No OID value matches this name.```

My code is the following:

```
using (var rsa = new RSACryptoServiceProvider())
{
    byte[] bytesToVerify = Encoding.UTF8.GetBytes(orData);

    byte[] signedBytes = Convert.FromBase64String(signedData);

    rsa.FromXmlString(ConvertPemToXML(publicKeyPath));

    return success = rsa.VerifyData(bytesToVerify, CryptoConfig.MapNameToOID("SHA512"), signedBytes);
}
```

**Comment by vcsjones** [comment]
Can you share the full stack trace of the exception or a runnable example to reproduce this? Which operating system are you able to reproduce this on?

I'm unable to reproduce this on Linux or Windows with something like:

```csharp
using RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
byte[] bytesToVerify = new byte[] { 1 };
byte[] signedBytes = rsa.SignData(bytesToVerify, CryptoConfig.MapNameToOID("SHA512"));
bool result = rsa.VerifyData(bytesToVerify, CryptoConfig.MapNameToOID("SHA512"), signedBytes);
Console.WriteLine(result);
```

**Comment by pantonis** [comment]
This is the full stacktrace that I am getting (1st chance exception)

```
   at System.Security.Cryptography.Oid.FromFriendlyName(String friendlyName, OidGroup group)
```

OS:
![image](https://user-images.githubusercontent.com/3295086/79344463-8c7b2c00-7f38-11ea-8133-d1ad4a290b7e.png)

I have the same issue on Windows Server 2016

**Comment by vcsjones** [comment]
`MapNameToOID` may throw this exception since it will [call `Oid.FromFriendlyName`][1]. However, it handles the exception.

> (1st chance exception)

Are you running this with a debugger attached and the debugger is reporting this exception as a first-chance exception? If so, does the issue still occur if you run it without a debugger attached?

[1]: https://github.com/dotnet/corefx/blob/60ffc71647ceb932c437313ab7907b89f544add7/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CryptoConfig.cs#L506

**Comment by pantonis** [comment]
I get this when in production as well (Release build)

**Comment by vcsjones** [comment]
> I get this when in production as well (Release build)

Thanks. I'm still not clear on steps on how to reproduce this. Your sample code includes a few unknown things like the complete implementation of `ConvertPemToXML`. It's also not clear what is calling `Oid.FromFriendlyName` and with what values the exception is occurring.

Does my [sample code above][1] run or fail for you? 

Anything additional you can share that would help reproduce this would be greatly appreciated.

[1]: #issuecomment-614048125

**Comment by pantonis** [comment]
I just tried the sample code you posted. Still the same error.

This is the assembly of the RSACrypto  

``` C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Security.Cryptography.Csp.dll```

**Comment by pantonis** [comment]
I slightly modified your sample to 

```
var OId = CryptoConfig.MapNameToOID("SHA512");

            using RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
            byte[] bytesToVerify = new byte[] { 1 };
            byte[] signedBytes = rsa.SignData(bytesToVerify, CryptoConfig.MapNameToOID("SHA512"));
            bool result = rsa.VerifyData(bytesToVerify, CryptoConfig.MapNameToOID("SHA512"), signedBytes);
            Console.WriteLine(result);
```

The exception occurs when the breakpoint reaches SignData

**Comment by pantonis** [comment]
I have a sample console app that reproduces this. I can send it to you if you wish.

**Comment by vcsjones** [comment]
> The exception occurs when the breakpoint reaches SignData

Can you post the complete, full stack trace?

Before we go too much further, is there anything that is tying you in to using `RSACryptoServiceProvider`? The preferred mechanism on .NET Core is to use `RSA.Create()`. So your code would become

```csharp
using RSA rsa = RSA.Create();
byte[] bytesToVerify = new byte[] { 1 };
byte[] signedBytes = rsa.SignData(bytesToVerify, HashAlgorithmName.SHA512, RSASignaturePadding.Pkcs1);
bool result = rsa.VerifyData(bytesToVerify, signedBytes, HashAlgorithmName.SHA512, RSASignaturePadding.Pkcs1);
Console.WriteLine(result);
```

I'd still like to know why you are getting an exception using `RSACryptoServiceProvider`, but, to unblock you moving to .NET Core, the above is the recommended approach now.

**Comment by pantonis** [comment]
@vcsjones No I am totally fine. I changed to the recommended approach. If you still want to investigate let me know your email and I will drop the sample app.

**Comment by vcsjones** [comment]
> If you still want to investigate the initial code let me know your email and I will drop the sample app.

If it doesn't contain anything sensitive then I would just post the files on https://gist.github.com/ and I'll take a look. If it does contain anything sensitive then I wouldn't send it to me or post it since you have a working solution for now.

**Comment by pantonis** [comment]
Take a look at this [gist ](https://gist.github.com/pantonis/d06b75a6511a7a1513193d63c5dc3d26)

**Comment by bartonjs** [comment]
So you're only seeing the error as a first chance exception? We don't make any guarantees about those.

But @vcsjones is right, the preferred way of doing things is to use `RSA.Create()` and the newer sign/verify methods (that take an RSASignaturePadding value).

**Comment by bartonjs** [comment]
Since this is about a first chance exception, not an unhandled exception, and the repro case requires using something other than the recommended approach, there's no further action.
