### ISSUE TITLE
Avoid Type.MakeGenericType when (de)serializing objects

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#35028]
As part of researching approaches to https://github.com/dotnet/runtime/issues/1568 it was found that avoiding `Type.MakeGenericType` for our object converter (non-collections and non-valuetypes) will help "reach" scenarios (AOT platforms that may not support it) as well as improve CPU performance and reduce memory consumption.

This means that the `T` in `JsonConverter<T>` will be of type `System.Object`; some changes are necessary in the object factory and JsonConverter base classes for this to work.

**Comment by MichalStrehovsky** [comment]
> non-valuetypes

MakeGenericType over valuetypes is the thing that contributes to most of JITtting though - MakeGenericType over a reference type usually ends up using shared code and JIT doesn't have to be spun up.

I wrote a quick summary of generics in .NET in a twitter thread recently: https://threadreaderapp.com/thread/1244602445461950470.html

**Comment by steveharter** [comment]
> MakeGenericType over valuetypes is the thing that contributes to most of JITtting though - 

The two main benefits:
- Helps for "reach" scenarios where Type.MakeGenericType is not supported. This is one of several issues that will be created to address "reach".
- Helps first-time startup perf since no reflection Emit needs to occur for these types.

**Comment by jmaine** [comment]
@MichalStrehovsky, Could we remove/reduce the need to JITing in the case of value types on generics by having the Jit transform the valuetype to a pointer to a valuetype?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky, Could we remove/reduce the need to JITing in the case of value types on generics by having the Jit transform the valuetype to a pointer to a valuetype?

Yes, that's kind of how Universal Shared Code looks like. It can be used for any `T`, but it's a lot less efficient than code specialized for a given `T`. RyuJIT/CoreCLR currently doesn't have support for that. (See sample of how Universal Shared Code looks like in the above mentioned Twitter thread).

**Comment by jmaine** [comment]
@MichalStrehovsky, I believe that is what I was referring to when I wrote this issue: #37143.

**Comment by steveharter** [comment]
Closing this for the following reasons:
- `Type.MakeGenericType` is supported on platforms including Xamarin; the serialization usage was made drastically simpler in 5.0 and no reported issues have been reported.
- We have a [code-gen initiative](https://github.com/dotnet/runtime/issues/1568) `Type.MakeGenericType` will not be used for AOT scenarios. This will help scenarios that want faster startup time and less memory usage.
- Using `System.Object` as the `T` will make writing custom converters a bit less intuitive since a cast will be necessary.

A prototype of the original idea is located at https://github.com/steveharter/runtime/tree/UseObjectAsT.
