### ISSUE TITLE
Optimize System.Text.Encodings.Web using arm64 intrinsics

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#35036]
This item tracks the conversion of the System.Text.Encodings.Web class to use arm64 intrinsics.

Related: #33308

**Comment by tarekgh** [comment]
CC @GrabYourPitchforks

**Comment by BruceForstall** [comment]
I'm moving this to Future, as there is no current plan to do the work for .NET 5.

**Comment by eiriktsarpalis** [comment]
Addressed by #38707.
