### ISSUE TITLE
Running libraries tests in VS using launchSettings.json fails

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#35031]
When using .NET Core xUnit Console profile I get the following error:

```
The application to execute does not exist: 'xunit.console.dll'

D:\repos\dotnet_runtime_2\artifacts\bin\testhost\netcoreapp5.0-Windows_NT-Debug-x64\dotnet.exe (process 45676) exited with code -2147450751.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
```
 
Chatted with @safern and it seems to be an issue with the `RunWorkingDirectory` having the wrong value in Design Time Build. If I manually change the workingDirectory in launchSettings.json from "$(RunWorkingDirectory)" to the hardcoded path to the test run working directory, I can run tests fine.

**Comment by safern** [comment]
cc: @Anipik

**Comment by ViktorHofer** [comment]
RunWorkingDirectory is derived from OutputPath. @ericstj @anipik I strongly believe we should fix the actual issue which is getting rid of TargetFramework reads from msbuild files which are imported before the project is evaluated,  instead of working around the various fallouts. Does that sound reasonable?

**Comment by ericstj** [comment]
> @ericstj @Anipik I strongly believe we should fix the actual issue which is getting rid of TargetFramework reads from msbuild files which are imported before the project is evaluated, instead of working around the various fallouts.

Agreed.  @Anipik has been driving towards this.  @Anipik can we go ahead and do so completely?

This would mean looking at all Directory.Build.props and all the props from our Arcade packages and project files ensuring they don't read TargetFramework in PropertyGroup.

**Comment by ericstj** [comment]
Effectively a dup of https://github.com/dotnet/runtime/issues/34525 but leaving this open to track the scenario.

**Comment by Anipik** [comment]
> @Anipik can we go ahead and do so completely?

Sure i can move this up the priority list
