### ISSUE TITLE
Optimize System.Text.Unicode using arm64 intrinsics

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#35035]
This item tracks the conversion of the System.Text.Unicode class to use arm64 intrinsics.

Related: #33308

**Comment by BruceForstall** [comment]
I'm moving this to Future, as there is no current plan to do the work for .NET 5.

**Comment by carlossanlop** [comment]
@BruceForstall @tannergooding below are the 3 APIs to fix for this area, but I realized that only the first API can be found in `Utf16Utility`. The other two exist in `Utf8Utility` instead:

- `System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar()` -> [Utf16Utility.Validation.cs#L45](https://github.com/dotnet/runtime/blob/6b5850fa7cf476b66be9d01a3ed05f4484b01d3a/src/libraries/System.Private.CoreLib/src/System/Text/Unicode/Utf16Utility.Validation.cs#L45)
- `System.Text.Unicode.Utf16Utility.TranscodeToUtf8()` -> [Utf8Utility.Transcoding.cs#L842](https://github.com/dotnet/runtime/blob/6b5850fa7cf476b66be9d01a3ed05f4484b01d3a/src/libraries/System.Private.CoreLib/src/System/Text/Unicode/Utf8Utility.Transcoding.cs#L842)
- `System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidByte()` -> [Utf8Utility.Validation.cs#L26](https://github.com/dotnet/runtime/blob/ba728d9fa0ad756bf39e2ed9e5411f871ccec16d/src/libraries/System.Private.CoreLib/src/System/Text/Unicode/Utf8Utility.Validation.cs#L26)

Was that a typo? Should I work on the Utf8 ones instead?

**Comment by danmosemsft** [comment]
cc @GrabYourPitchforks

**Comment by BruceForstall** [comment]
It's certainly likely to be a typo. I created the initial list using, essentially, findstr/grep with a little bit of intelligence thrown in. I easily could have made a mistake.

Bottom-line: anything in `System.Text.Unicode` that has been intrinsics optimized for Intel should be considered tracked by this issue for optimizing for arm64. Feel free to update the list of APIs listed in #33308 to be more correct.

**Comment by carlossanlop** [comment]
Thanks Bruce. I'll adjust the signatures in the original issue.
