### ISSUE TITLE
Optimize System.Text.ASCIIUtility using arm64 intrinsics

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#35034]
This item tracks the conversion of the System.Text.ASCIIUtility class to use arm64 intrinsics.

Related: #33308

**Comment by BruceForstall** [comment]
I'm moving this to Future, as there is no current plan to do the work for .NET 5.

**Comment by jeffhandley** [comment]
The remaining two methods will be finished in 6.0.0 with #41292.
