### ISSUE TITLE
Multi-level cache

### ISSUE THREAD

**Issue by bladepan** [dotnet/runtime#35044]
It is common for applications to have two level cache with a in memory cache as level 1 cache and a remote cache server as level 2 cache (such as redis). 
We can have a implementation of multi-levle cache in Extensions Cache package. 

```cs
public class MultiLevelCache: IDistributedCache {
  private readonly IMemoryCache _l1Cache;
  private readonly IDistributedCache _l2Cache;
}
```

**Comment by davidfowl** [comment]
What does usage look like? IDistributedCache has  takes byte[] and IMemoryCache uses objects. Are you trying to store the retrieved bytes in memory to save a network hop but paying the cost to deserialization every time? 

Or are you trying to wrap a memory cache around a distributed cache ?

**Comment by bladepan** [comment]
There is no de-serialization cost as we can store byte[] in MemoryCache. The new class implements IDistributedCache interface, so it only takes byte[].

Yes, essentially it is wrapping a memory cache around a distributed cache.

**Comment by davidfowl** [comment]
> There is no de-serialization cost as we can store byte[] in MemoryCache. The new class implements IDistributedCache interface, so it only takes byte[].

Sorry I don't understand. The sample you show will result in the code caching a `byte[]` in the memory cache, then something has to turn the `byte[]` into an object of some form. That works but you're paying the cost of turning that `byte[]` into an object even if you avoid the network hop.

> Yes, essentially it is wrapping a memory cache around a distributed cache.

Well what you propose is the opposite. You're wrapping an IDistributedCache around a memory cache.

**Comment by bladepan** [comment]
A byte[] is also a object. There is no serialization involved, only type casting, right? See also the Set method in MemoryDistributedCache.cs.

```cs
public class MultiLevelCache: IDistributedCache {
    private readonly IMemoryCache _l1Cache;
    private readonly IDistributedCache _l2Cache;
    public byte[] Get(string key)
    {
        byte[] l1Result = _l1Cache.Get(key) as byte[];
        if(l1Result != null) {
              return l1Result;
        }
        return _l2Cache.Get(key);
    }
}
```

**Comment by davidfowl** [comment]
I see, so you are storing `byte[]` itself, sure. I'm not sure this is the super common case. It seems like it would be more common to cache the object created as a result of de-serializing the byte[] (if the goal is to store serialized data)

**Comment by bladepan** [comment]
The goal is to saving calls to a distributed cache (redis). I have seen classes doing similar thing in various code bases and have written some myself. It is somewhat common use case i would say.

**Comment by jodydonetti** [comment]
Hi @bladepan if you still need an (optionally) multi-level cache with some other advanced features may I suggest taking a look at [FusionCache ⚡🦥](https://github.com/jodydonetti/ZiggyCreatures.FusionCache) ?

I just released it and, if you find it helpful, that would be great to know.

Also, any comment on it would be greatly appreciated.

**Comment by adamsitnik** [comment]
> It is somewhat common use case i would say.

There was only one upvote over three years. I am sorry, but we are not going to implement it in the near future. Thanks!
