### ISSUE TITLE
UDP Socket is broken on Linux if remote endpoint is localhost

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#35048]
UDP socket (`ProtocolType.Udp`, `SocketType.Dgram`) has strange behavior on Linux if loopback address is used as a remote endpoint. The first attempt to send the data over the socket breaks it.
```csharp
var localhost = IPAddress.Loopback;
using var socket = new Socket(localhost.AddressFamily, SocketType.Dgram, ProtocolType.Udp);
socket.Connect(new IPEndPoint(localhost, 3262));
            
await socket.SendAsync(new byte[10], SocketFlags.None);
var args = new SocketAsyncEventArgs();
args.RemoteEndPoint = new IPEndPoint(localhost, 3262);
False(socket.ReceiveFromAsync(args));
Equal(SocketError.ConnectionRefused, args.SocketError);
```
`Connect` method call is successful. After that, I'm trying to send packet. This call turns socket into disconnected state and attempts to listen response will fail with `ConnectionRefused` error.

However, on Windows this code behaves correctly and WinSock just drops the packet because there is no listener on this port and UDP is connectionless protocol.

Such inconsistent behavior makes me burn :fire: with unit tests for my code depending on UDP socket. Generally, it's not possible to guarantee instantiation and binding server-side UDP socket strongly before client code.

IDK, probably this is happening due to differences in native socket API on Windows and Linux. In Linux, kernel decides to inform the caller that there is no active listeners that was bound to localhost event if it's UDP. This is possible because localhost connection is actually IPC.

Also, this bug is strongly related to #34473, #34474 and probably to #30782.

**Comment by wfurt** [comment]
You can do packet capture and you will probably see ICMP back. 
I'm wondering if we could ignore it for UDP. It is unusual to ignore socket errors but that would make it more consistent. I think the behavior is same on all platform e.g. socket would get to disconnected state when it get ICMP unreachable but Windows stack does not generate it. 

Could you try SendTo() as well @sakno ? e.g. avoid calling Connect? 

cc: @tmds

**Comment by sakno** [comment]
@wfurt , I tried `SendToAsync` without `Connect` and my problem is now solved! Thanks a lot! However, I'm confused by `Connect` behavior. What is it for (in case of connectionless protocol)? Why it affects UDP socket in such (inconsistent) way? It would be nice to update official documentation.

**Comment by wfurt** [comment]
@tmds may have better explanation about Linux behavior but here is what I observed while back. When you sendto() you are not committed to any particular peer. The socket is just a handle to send packets anywhere. When you call "connect" you are bound to the particular endpoint and you establish special relation - even if there is no real handshake like TCP. So when that endpoint goes away (or never existed) you may get ICMP notification. At the low-level socket API, it would be up to you ignore it or react to it. This is not specific to loopback. I've seen it with firewalls and routers - they may send ICMP unreachable when traffic is prohibited by policy or if the network is unreachable. 


There is some reading here http://man7.org/linux/man-pages/man2/send.2.html but it does not talk about the icmp behavior.
