### ISSUE TITLE
System.Net.Sockets.TcpClient how to wait the bytes available?

### ISSUE THREAD

**Issue by yukozh** [dotnet/runtime#35052]
Now use the NetworkStream.ReadAsync, even 0 byte received it will exit await. Is there a way to wait for at least a number of bytes?

**Comment by tmds** [comment]
> even 0 byte received it will exit await

`ReadAsync` will complete when there is data available, or when the peer has closed the connection (0-byte receive).
Otherwise it waits.

> Is there a way to wait for at least a number of bytes?

There is no API to wait for a minimal nr of bytes. You need to keep track yourself on how many bytes of expected were already received.
