### ISSUE TITLE
Version mismatch between System.Security.Principal.Windows ref & lib

### ISSUE THREAD

**Issue by dedale** [dotnet/runtime#35055]
Hello,

When I use version 4.7.0 of System.Security.Principal.Windows Nuget package, assembly references do not match the version of assembly in output folder.

Actual repo is ~200 projects. I do not want to add App.config for almost all projects to fix this mismatch.

## Repro
[code](https://github.com/dedale/dotnet_runtime_issue)

I have a repo with projects in:
- .NET Standard 2.0
- .NET Framework 4.8
- .NET Core 3.1

## Expected results
No version mismatch between assembly in output folder and assembly references.

### .NET Core (unit tests)

>   Message: 
>       Expected: <4.1.1.0>
>       But was:  <4.1.3.0>

### .NET Core App (Console)

> ref: 4.1.1.0 bin: 4.1.3.0

### .NET Framework 4.8

> ref: 4.1.1.0 bin: 4.0.0.0

**Comment by vcsjones** [comment]
This looks like a duplicate of https://github.com/dotnet/runtime/issues/30988.

**Comment by bartonjs** [comment]
Agreed, closing as dupe.
