### ISSUE TITLE
IPGlobalProperties.GetActiveUdpListeners() hangs in .NET 5 preview 2

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#35051]
Using .NET 5.0.100-preview.2.20176.6, calls to `IPGlobalProperties.GetActiveUdpListeners()` seem to hang indefinitely.

I can repro this with the following, where the Console output never occurs with .NET 5 preview 2 (the method does not block with .NET Core 3.1).

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>GetActiveUdpListenersHangRepro</RootNamespace>
  </PropertyGroup>
</Project>
```

```csharp
using System;
using System.Net.NetworkInformation;

namespace GetActiveUdpListenersHangRepro
{
    internal static class Program
    {
        internal static void Main()
        {
            var properties = IPGlobalProperties.GetIPGlobalProperties();
            properties.GetActiveUdpListeners();

            Console.Write("Press any key to exit...");
            Console.Read();
        }
    }
}
```

Partial output from `dotnet --info`:

```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.2.20176.6
 Commit:    d752c3e07b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.2.20176.6\

Host (useful for support):
  Version: 5.0.0-preview.2.20160.6
  Commit:  d12f79a4d1
```

**Comment by martincostello** [comment]
Here's a summary of the repro while it's running from Process Explorer:

![image](https://user-images.githubusercontent.com/1439341/79451691-d6b6e880-7fde-11ea-9867-11e22e894657.png)

**Comment by martincostello** [comment]
Looks like the test for this method isn't run on Windows at all:

https://github.com/dotnet/runtime/blob/110282c71b3f7e1f91ea339953f4a0eba362a62c/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs#L30-L38

**Comment by wfurt** [comment]
I could not reproduce it with 5.0 alpha1 but I do see it with preview4 build. So it looks like very recent regression. It is curious as I did not see any recent change in the windows code.
