### ISSUE TITLE
Generate api diffs as a part of an official build CI

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#35059]
After moving Asmdiff to the ci, we can automate the generation of api-diffs as part official ci build.
This will involve 2 steps

- Adding md writer to asmdiff. The code will be similar to api reviewer code base but currently asmdiff doesnot support writing markdown files.
- running the tool as the part of the ci

cc @ericstj @danmosemsft @ViktorHofer

**Comment by Anipik** [comment]
We can run this as a part of our release process in a separate pipeline
The asmdiff tool requires the input and output set of assemblies.
The workflow will look something like this.

- Run darc gather drop to get the packages using the bar id and repo names.
- extract the Nuget packages into a temp folder which will act as the new set of dependencies. We can add functionality to provide separate configurations for shared framework and oob packages.
- Run gather drop using preview release bar id. we can store this previous bar id.
- Run the asmdiff tool to generate the markdown files.
- we can use darc/ github api to open the pr in the core repo with these new files


@ericstj @safern @ViktorHofer  any suggestions for the above workflow ?

**Comment by safern** [comment]
@Anipik maybe we can use: https://github.com/dotnet/api-catalog-infra -- or do you think that this should be part of the runtime repo?

**Comment by Anipik** [comment]
I dont think this need to be a  part of runtime, we will be using this for runtime for aspnetcore as well.
I can go through the readme in this repo and take a look how we can inject this into the repo.

**Comment by safern** [comment]
That repo already uses darc to get the runtime repo OOB packages and shared framework and also gets ASP.NET Core and WindowsDesktop frameworks, so it might make sense to put all this there since we already have the info needed.

**Comment by Anipik** [comment]
We decided to move away from this as the dev cost of generating api diffs was really low.
