### ISSUE TITLE
 Bundle_can_be_renamed_while_running failed in CI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#35068]
##

### Console Log Summary

```
System.ComponentModel.Win32Exception : Text file busy


Stack trace
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/test/TestUtils/Command.cs:line 200
   at AppHost.Bundle.Tests.BundleRename.Bundle_can_be_renamed_while_running(Boolean renameFirstRun) in /_/src/installer/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleRename.cs:line 36

```

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#601707](https://dev.azure.com/dnceng/public/_build/results?buildId=601707)|Rolling|1|
### Configurations
- Installer-Linux_x64-Release

**Comment by safern** [comment]
@swaroop-sridhar I saw this fail yesterday again, is there any update on this issue?

**Comment by swaroop-sridhar** [comment]
@safern  can you please point me at the recent failure? Was it the same test that failed? 
This kind of failure is very intermittent, and occurs on different test. 
(ex: https://github.com/dotnet/runtime/issues/33675).

**Comment by safern** [comment]
It was this exact same failure.

## Bundle_can_be_renamed_while_running

### Console Log Summary

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#662596](https://dev.azure.com/dnceng/public/_build/results?buildId=662596)|#37128|1|
|[#663426](https://dev.azure.com/dnceng/public/_build/results?buildId=663426)|Rolling|1|
|[#664004](https://dev.azure.com/dnceng/public/_build/results?buildId=664004)|#37166|8|
### Configurations
- Installer-coreclr-Linux_musl_x64-Release
- Installer-coreclr-Linux_x64-Release
- Installer-coreclr-OSX_x64-Release
- Installer-coreclr-Windows_NT_x64-Release
- Installer-coreclr-Windows_NT_x86-Debug

**Comment by xtqqczze** [comment]
Failure in build [#670388](https://dev.azure.com/dnceng/public/_build/results?buildId=670388&view=ms.vss-test-web.build-test-results-tab&runId=20766046&resultId=100002&paneView=debug), PR #37367

**Comment by ManickaP** [comment]
PR #37441 as well

**Comment by swaroop-sridhar** [comment]
@janvorli any ideas on how to debug this failure on Linux? 

[This test](https://github.com/dotnet/runtime/blob/master/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleRename.cs)  is failing non-deterministically once in a while with the `Text File Busy` exception on Linux. The test is failing on startup -- and looks like a sharing violation error.  Even though the failures are mostly on this test, #33675 shows a similar failure on another test.

Thanks.

**Comment by ViktorHofer** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=684945&view=ms.vss-test-web.build-test-results-tab&runId=21253244&resultId=100002&paneView=debug

**Comment by ViktorHofer** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=670388&view=ms.vss-test-web.build-test-results-tab&runId=20766046&paneView=debug&resultId=100002

Tending towards disabling the test until someone has time to investigate.

ping @swaroop-sridhar @janvorli

**Comment by swaroop-sridhar** [comment]
OK I can disable the bundle_can_be_renamed test for now. 
But on Linux, the "text file busy" needs investigation because a few other tests failed on it.

**Comment by ViktorHofer** [comment]
Yes please do that. We usually create a tracking issue for such issues to investigate and link to it from the failing test.

**Comment by safern** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=690964&view=ms.vss-test-web.build-test-results-tab&runId=21450494&resultId=100008&paneView=debug

@swaroop-sridhar did you get a chance to look at disabling the test?

**Comment by swaroop-sridhar** [comment]
@safern  @ViktorHofer  here's the PR to disable the test: https://github.com/dotnet/runtime/pull/38014

**Comment by ManickaP** [comment]
It failed again for me in this run: https://dev.azure.com/dnceng/public/_build/results?buildId=700110&view=ms.vss-test-web.build-test-results-tab&runId=21707460&resultId=100008&paneView=debug

**Comment by jaredpar** [comment]
Looks like this test is flaky again. We should disable 


### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#699878](https://dev.azure.com/dnceng/public/_build/results?buildId=699878)|Rolling|1|
|[#700110](https://dev.azure.com/dnceng/public/_build/results?buildId=700110)|#34948|1|
### Configurations
- Installer-coreclr-OSX_x64-Release

**Comment by safern** [comment]
The test was just re-enabled in: https://github.com/dotnet/runtime/pull/38143

**Comment by swaroop-sridhar** [comment]
The test now failed in a different mode. 
Previously, the test failed to start, but now it runs to completion but output wasn't captured properly.
Also, the failures so far are Osx release only.

I'll disable the test again and investigate.
