### ISSUE TITLE
System.Net.Sockets.Tests failing as a group in CI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#35065]
This failure group occurred in the following build:
- https://dev.azure.com/dnceng/public/_build/results?buildId=602040
- netcoreapp5.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open

Failure text is pretty much the same for all the tests.

```
    System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_CreateUnixDomainSocket_Throws_OnWindows [SKIP]
      Condition(s) not met: "IsSubWindows10"
    System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds [FAIL]
      System.Net.Sockets.SocketException : Network is unreachable
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(5171,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1420,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1450,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(303,0): at System.Net.Sockets.Tests.SocketOptionNameTest.CreateBoundUdpSocket(Int32& localPort)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(90,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_Helper(Int32 interfaceIndex)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(72,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds()
        --- End of stack trace from previous location ---
```

All the following tests failed in that build

System.Net.Sockets.Tests Work Item 1
System.Net.Sockets.Tests.SendTo+Async+Apm.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Async+Apm.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Async+Eap.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Async+Eap.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Async+Task.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Async+Task.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Sync+ArrayForceNonBlocking.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Sync+ArrayForceNonBlocking.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Sync+MemoryArrayTask.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Sync+MemoryArrayTask.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Sync+MemoryNativeTask.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Sync+MemoryNativeTask.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Sync+Span.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Sync+Span.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SendTo+Sync+SpanForceNonBlocking.Datagram_UDP_AccessDenied_Throws_DoesNotBind 1
System.Net.Sockets.Tests.SendTo+Sync+SpanForceNonBlocking.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint 1
System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds 1
System.Net.Sockets.Tests.SocketOptionNameTest.MulticastOption_CreateSocketSetGetOption_GroupAndInterfaceIndex_SetSucceeds_GetThrows 1

**Comment by antonfirsov** [comment]
@scalablecory @wfurt getting `ENETUNREACH` from `sendto` seems really weird in case of UDP sockets. Do you have any explanation or idea? (A fake endpoint, `10.20.30.40:12345` is being used.)

**Comment by wfurt** [comment]
do we know what subnet the system is connected to (and how the the routing table looks like)? For the MulticastInterface_Set_AnyInterface_Succeeds, it always fails for me in my local VM. 
I assumed this is part of the VM magic so I did not bothered to investigare.

**Comment by davidsh** [comment]
Multicast tests are tricky because they can easily be restricted due to firewall and other network config settings. In general, it is something difficult to test multicast unless the network is completely isolated.

**Comment by karelz** [comment]
Triage: There were larger hiccups on SLES in April -- we should check if it was part of that before investing too much time.
