### ISSUE TITLE
Restore in visual Studio is not removing the placeholder configurations

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#35061]
![restoreFailure](https://user-images.githubusercontent.com/10516582/79486119-17a50200-7fcb-11ea-8a55-115fa618978f.JPG)

It seems like our static regex removal is not removing placeholder configs while running in the vs
This is not reproducable from command line.

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
I'm looking into this already. Thanks for opening an issue.
