### ISSUE TITLE
System.ComponentModel.IListSource is missing TypeConverter and Editor attributes

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/runtime#35076]
.NET Framework defines `IListSource` with `TypeConverter` and `Editor` attributes, which control the designer experience in the Property Browser. In .NET Core those are missing, which makes it impossible for the Property Browser to show the right editor and provide the correct designer experience.

More context: 
`IListSource`'s Designer related attributes are used when editing the `DataSource` property of the `DataGridView` or the `BindingSource` component, for example. Those properties are of type `object` all right, but they are forwarded to `IListSource` with the `AttributeProviderAttribute`.

**Comment by ericstj** [comment]
Looks like @safern added back Editor in https://github.com/dotnet/runtime/commit/3130ac980c97c0664eddb04411f8f765a9f908d8

We are missing `TypeConverterAttribute` which on .NETFramework has the following value:
https://referencesource.microsoft.com/#System/compmod/system/componentmodel/IListSource.cs,17
```
    TypeConverterAttribute("System.Windows.Forms.Design.DataSourceConverter, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
```

@safern did you want to pick this up as it is very similar to the other work you've recently done?

**Comment by safern** [comment]
Sure, why not.
