### ISSUE TITLE
Meaning of negative index in System.Numerics.Tensors 

### ISSUE THREAD

**Issue by abgoswam** [dotnet/runtime#35075]
I am curious whats a negative index in System.Numerics.Tensors represents ?

```
            var arrayA = new[, ,]
            {
                {
                    {0, 1, 2},
                    {3, 4, 5}
                },
                {
                    {6, 7 ,8 },
                    {9, 10 ,11 },
                },
                {
                    {12, 13 ,14 },
                    {15, 16 ,17 },
                },
                {
                    {18, 19 ,20 },
                    {21, 22 ,23 },
                }
            };

            var tensorA = arrayA.ToTensor<int>(); // tensorA shape (4, 2, 3)
            var y = tensorA[2, -1, -2]; // **7**
            var z = tensorA[0, -1, -2]; // **throws error**
```

I was trying to draw parallels with numpy. Numpy results made sense. 

```
a = np.array([ [[0,1,2], [3,4,5]],  [[6,7,8], [9,10,11]],  [[12,13,14],[15,16,17]]])
y = a[2,-1,-2]  # 16,  looks ok
z = a[0,-1,-2]  # 4, looks ok
```

@eerhardt

**Comment by eerhardt** [comment]
What you want here is a `System.Index` with a `^` which means "from the end".

https://docs.microsoft.com/en-us/dotnet/api/system.index?view=netcore-3.1

```
int[] someArray = new int[5] { 1, 2, 3, 4, 5 };
int lastElement = someArray[^1]; // lastElement = 5
```

However, the issue is that `System.Numerics.Tensors` targets `netstandard1.1`, but `System.Index` is only available on `netcoreapp3.0`+.

@terrajobst @tarekgh @GrabYourPitchforks - maybe since `Range` and `Index` are now stable - we could consider making a `Microsoft.Bcl` package for them?

**Comment by tarekgh** [comment]
> maybe since Range and Index are now stable - we could consider making a Microsoft.Bcl package for them?

I believe it was decided before we are not going to create a package for Index/Range. 

CC @jaredpar

**Comment by abgoswam** [comment]
thanks for the discussion.

@eerhardt . what really worries me is this:
> `var y = tensorA[2, -1, -2]; // **7**`

the library silently returned me an answer (7)

I would have expected this to throw a 'System.IndexOutOfRangeException' similar to what multi-dimensional arrays in .NET does for negative indices

**Comment by eerhardt** [comment]
> what really worries me is this:
the library silently returned me an answer (7)

Yeah, that looks like a bug. It doesn't do any argument checking:

https://github.com/dotnet/runtime/blob/103fa2c16dc138fedf431dbaebcb02567c176cd3/src/libraries/System.Numerics.Tensors/src/System/Numerics/Tensors/Tensor.cs#L668-L673

> I believe it was decided before we are not going to create a package for Index/Range.

The discussion keeps coming up though. It recently came up for making the `Utf8String` package support `netstandard2.0`: #33357.

**Comment by jaredpar** [comment]
> I believe it was decided before we are not going to create a package for Index/Range.

@terrajobst drives this process

**Comment by pgovind** [comment]
> Yeah, that looks like a bug. It doesn't do any argument checking:

I randomly ran into this issue today and spent a little bit of time debugging it. In the example, `tensorA` is a `DenseTensor`. When I look at its `strides` property, it returns `[6, 3, 1]`. I'm not sure that is correct, I expected `Strides` to return `[4, 2, 3]`. However I'm not familiar at all with the Tensors codebase, so I'm going to double check that. At first glance, it looks like lines 88 and 89 should be swapped here: https://github.com/dotnet/runtime/blob/103fa2c16dc138fedf431dbaebcb02567c176cd3/src/libraries/System.Numerics.Tensors/src/System/Numerics/Tensors/ArrayUtilities.cs#L89

Also, AFAICT, there doesn't exist a single unit test checking negative indices to the indexer!
