### ISSUE TITLE
Prototype ICU size reduction tooling 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#35092]
Because the data file for ICU is quite large (~16MB), we need to prototype trying to reduce the size for iOS & tvOS.  

Using https://github.com/unicode-org/icu/blob/master/docs/userguide/icu_data/buildtool.md and http://www.icu-project.org/docs/demo/datacustom_help.html as guides, we should determine the following:

- [ ] How much friction is involved? Can we easily integrate into our build? 
- [ ] What is the smallest possible size configuration?  Can we get down to 2MB?
- [ ] Are there any drawbacks / implications to using?

**Comment by ViktorHofer** [comment]
cc @safern

**Comment by filipnavara** [comment]
Is this still relevant? dotnet/icu already uses filtering and the artifacts are consumed on iOS.

**Comment by steveisok** [comment]
No, it's an old issue
