### ISSUE TITLE
About the ConcurrentQueue<T> space question

### ISSUE THREAD

**Issue by hey-hoho** [dotnet/runtime#35094]
Follow this test code:
```c#
 ConcurrentQueue<int> queue = new ConcurrentQueue<int>();
for (int i = 0; i < 35; i++)
{
     queue.Enqueue(i);
}
int[] ary = queue.ToArray();
queue.Enqueue(100);
```
When I done the `ToArray()`, the queue's tail has been frozened. Then enqueue item by next step that will create a new segment(3th) with size 32, but only 3 items filled in the 2th segment with size 64! 

Will there be a lot of wasted space here?

How about unfrozen  the queue's tail when  `ToArray()` completed, Will it cause other problems?

**Comment by stephentoub** [comment]
> How about unfrozen the queue's tail when ToArray() completed, Will it cause other problems?

Yes, it could cause problems.  With the segment frozen, any concurrent enqueues at that point will start going into a new segment.  If we then unfroze the previous segment, ordering would be lost.  Plus it would make various aspects of the synchronization more complicated.

**Comment by hey-hoho** [comment]
@stephentoub Thanks for your answer. 
Are there any plans to optimize the space waste problem?

**Comment by stephentoub** [comment]
No. There's no evidence that there's an actual problem in real code that's using the type as it was designed for.

**Comment by MaximGurschi** [comment]
On a slightly related note, i was wondering if there is interest in making the maximum segment size be programmable. So that it can be more than ~10^6?
