### ISSUE TITLE
Follow up task for named runtime pack functionality

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#35107]
In https://github.com/dotnet/runtime/pull/34980, we are overriding the name of `Microsoft.NETCore.App.Runtime.{RID}.{version}.nupkg` with `Microsoft.NETCore.App.Runtime.Mono.{RID}.{version}.nupkg`.  This issue is follow up work to simplify what is being renamed.

- [x] Change [RidSpecificPackProperties](https://github.com/dotnet/arcade/blob/be7971c98d4ad60cdf8c3d1aa41f950f42bd466a/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/framework.packaging.targets#L224) to be `<RidSpecificPackProperties>BaseId=$(MSBuildProjectName)$(RuntimeSpecificFrameworkSuffix).$(PackageBuildRID);IdPrefix=</RidSpecificPackProperties>` https://github.com/dotnet/arcade/pull/5287
- [ ] Remove `MobileGetBuildRidSpecificPackageProps` target and create a property group `RuntimeSpecificFrameworkSuffix` with .Mono inside. #35124 

The end result should be the same.  A `Microsoft.NETCore.App.Runtime.Mono.{RID}.{version}.nupkg` produced for desktop mono builds.

**Comment by dagood** [comment]
> * Alter the `MobileGetBuildRidSpecificPackageProps` target to override `RuntimeSpecificFrameworkSuffix` with .Mono

Shouldn't need a target. Copying my suggestion from https://github.com/dotnet/runtime/pull/34980#discussion_r408532336 to make it easy to reach:

> this should be done with a small tweak over here (but without the redundant `.Mono`):
> 
> https://github.com/dotnet/arcade/blob/be7971c98d4ad60cdf8c3d1aa41f950f42bd466a/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/framework.packaging.targets#L224
> 
> ```xml
> <RidSpecificPackProperties>BaseId=$(MSBuildProjectName)$(RuntimeSpecificFrameworkSuffix).$(PackageBuildRID);IdPrefix=</RidSpecificPackProperties>
> ```
> 
> And you'd use that API here in dotnet/runtime by specifying the property:
> 
> ```xml
> <PropertyGroup Condition="'$(RuntimeFlavor)' == 'Mono' and '$(TargetsMobile)' != 'true'">
>   <RuntimeSpecificFrameworkSuffix>.Mono</RuntimeSpecificFrameworkSuffix>
> </PropertyGroup>
> ```

**Comment by dagood** [comment]
> we are overriding the name of `Microsoft.NETCore.App.Runtime` with `Microsoft.NETCore.App.Mono.Runtime`.

Not quite: `Microsoft.NETCore.App.Runtime.Mono.{RID}.{version}.nupkg`

This corresponds to `BaseId=$(MSBuildProjectName)$(RuntimeSpecificFrameworkSuffix).$(PackageBuildRID)`
