### ISSUE TITLE
Proposal: store JIT result in persistent storage (e.g. hard disk)

### ISSUE THREAD

**Issue by ygc369** [dotnet/runtime#35103]
When running a .Net program, CLR must do JIT and cache the JIT result in memory. But once the program is closed, the JIT result gets lost. When running it next time, CLR has to do JIT again. I think this is a waste of time. Why not store the JIT result in persistent storage? Thus next time running the program, just load the stored JIT result and not need do JIT again. The startup time would be reduced. 
About where to place the JIT result, I think that CLR could create a new file in the same directory with the executable file of the .Net program. Of course, if the exe file is in a readonly storage, then JIT result can't be stored, but it is a rare scenario that does not matter.

**Comment by EgorBo** [comment]
This is already supported via R2R (AOT), see
https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/

E.g. you can precompile the whole application via:
```
dotnet publish -r win-x64 /p:PublishReadyToRun=true
```
and it should start as quick as possible with minimal JIT actions.

**Comment by jkotas** [comment]
>  But once the program is closed, the JIT result gets lost. When running it next time, CLR has to do JIT again. I think this is a waste of time. Why not store the JIT result in persistent storage?

The very first implementation of NGen in .NET Framework 1.0 worked like this. It had number of reliability and security problems, and it was quickly abandoned (even before .NET Framework 1.0 shipped). I do not think we would want to ever rebuild it again.

**Comment by jkotas** [comment]
Thanks for the suggestion
