### ISSUE TITLE
System.IO.FileSystem.Tests crashed in CI

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#35117]
It seems like this has only happened once in the last 100 builds, when retrying the job, the test passed.

|Build|Kind|Console Log| Dump
|---|---|---|---|
|[604570](https://dev.azure.com/dnceng/public/_build/results?buildId=604570)|PR https://github.com/dotnet/runtime/pull/34998|[console.log](https://helix.dot.net/api/2019-06-17/jobs/ae88097e-5466-4bb7-ac0f-43135b782f70/workitems/System.IO.FileSystem.Tests/files/console.4a967642.log)|[dotnet.exe.6024.dmp](https://helix.dot.net/api/2019-06-17/jobs/ae88097e-5466-4bb7-ac0f-43135b782f70/workitems/System.IO.FileSystem.Tests/files/dotnet.exe.6024.dmp)|

cc: @jaredpar

**Comment by jkotas** [comment]
Duplicate of #34279

**Comment by safern** [comment]
Thanks @jkotas
