### ISSUE TITLE
ARM64: Optimize pair of "str reg, [fp]" to stp 

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#35134]
```asm
str     x2, [fp,#16]
str     x3, [fp,#24]
```
can be combined into `stp` if the stores are happening in subsequent memory.
```asm
stp x2, x3, [fp, #16]
```

I collected no. of such `str` pairs in framework libraries and found approx. 33K pairs in 16K methods.

Details:

[str_str_fp_to_stp.txt](https://github.com/dotnet/runtime/files/4495189/str_str_fp_to_stp.txt)

category:cq
theme:optimization
skill-level:intermediate
cost:small
impact:medium

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/35133
