### ISSUE TITLE
ARM64: Optimize pair of "str wzr, [reg]" to "str xzr"

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#35136]
```asm
str     wzr, [x1,#8]
str     wzr, [x1,#12]
```
can be combined into `str xzr` if the stores are happening in subsequent memory.
```asm
str     xzr, [x1,#8]
```

I collected no. of such `str` pairs in framework libraries and found approx. 450 pairs in 353 methods.

Details:

[str_str_wzr_to_str_xzr.txt](https://github.com/dotnet/runtime/files/4495199/str_str_wzr_to_str_xzr.txt)

category:cq
theme:optimization
skill-level:intermediate
cost:small
impact:medium

**Comment by BruceForstall** [comment]
In addition, a sequence of 4 `str wzr` could be collapsed down to a single `stp xzr, xzr` by further optimizing using https://github.com/dotnet/runtime/issues/35134.

**Comment by BruceForstall** [comment]
In the attached file, there are some interesting example that are more complicated than simple adjacency peephole optimization. E.g.,
```
; Assembly listing for method System.Data.ExpressionParser:StartScan():this
[0024]        B9003C1F          str     wzr, [x0,#60]
[0025]        B900301F          str     wzr, [x0,#48]
[0026]        B900341F          str     wzr, [x0,#52]
[0027]        B900401F          str     wzr, [x0,#64]
```
Could be:
```
str     xzr, [x0,#48]
str     xzr, [x0,#60]
```
but it require recognizing that the non-contiguous offsets 60 and 64 can be combined.
