### ISSUE TITLE
ARM64: Optimize pair of "ldr reg, [fp]" to ldp

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#35130]
```asm
ldr     x2, [fp,#24]
ldr     x3, [fp,#32]
```
can be combined into `ldp` if the loads are happening from subsequent memory.
```asm
ldp x2, x3, [fp, #24]
```

I collected no. of such `ldr` pairs in framework libraries and found approx. 28K pairs in 13K methods.

Details:

[ldr_ldr_fp_to_ldp.txt](https://github.com/dotnet/runtime/files/4495139/ldr_ldr_fp_to_ldp.txt)

category:cq
theme:optimization
skill-level:intermediate
cost:small
impact:medium

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/35132

**Comment by BruceForstall** [comment]
I noticed a few things from the attached file:

- Sometimes the low offset comes first, sometimes it comes second in the instruction stream. A peep would need to handle both cases.
- There are a few cases in the attached examples of non-contiguous loads that wouldn't be mergeable (e.g., `[fp,#72]` / `[fp,#32]`)
- Were there any cases of consecutive loads of the `w` sub-registers? Or the floating-point registers?

**Comment by BruceForstall** [comment]
Extending this to arm32, we could use `STM` with a register mask to collapse multiple store (if the consecutive stores were using increasing register numbers, and possibly other conditions were met).

**Comment by kunalspathak** [comment]
Fixed in various peepholes, latest being https://github.com/dotnet/runtime/pull/85032.
