### ISSUE TITLE
Set up telemetry for runtime installer success

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3513]
This exists in the SDK bundle installer, copy it over into the runtime bundle installer.

https://github.com/dotnet/core-sdk/blob/7464d9bca4a2f25d1f832f9ef51ed288d4b0201e/src/redist/targets/packaging/windows/clisdk/dotnet.wxs#L38-L52

/cc @leecow

**Comment by NikolaMilosavljevic** [comment]
@wli3 has SDK installer telemetry proven valuable?
