### ISSUE TITLE
Move test_fx_ver under the cli/test folder

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#3515]
Once dotnet/core-setup#5522 is merged we will have the "test exe" infrastructure in place. So it would make sense to move the `test_fx_ver` under the `test` folder and cleanup the cmake file to use the shared bits.

@sdmaclea @elinor-fung

**Comment by elinor-fung** [comment]
This was done in https://github.com/dotnet/runtime/pull/49313.
