### ISSUE TITLE
Severe performance issues in code generation by the JIT

### ISSUE THREAD

**Issue by ameisen** [dotnet/runtime#35159]
[As per this SharpLab example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIAYACASQDsMYBzGKAFQE8ADjEYBeRsXIA6AEL8OAbhoB6ZQxbsuPAcLETpbDAGZSS2tQCWmqK2wAbfUgmlGAYQitcGbO1yMA3jSMwYxWHDb2jJCeGBoc3HxCIgBaPBB6ABSGWonCAJT0ZiGh1rYO0V5xOToiAPKsIuJZmgk1eeRmAL40dEaOzowAgrgAqhgWdhYY/AFBIcoAVHPBy4wA6gAWMxgbIrtgANaM2LCMOzC4IgBmeOFnGz6MACYQVpyhsQDuUxtW9yIQc5QRj4GA7CBPXAAflWzFik3C9jsM24DSg2A4fmAYLukCeIgsVxYUSRx0YAFdxgiZqDwU97hjnhALqsAPrnRi4bCg+5vVlSVarBbKQXUYrEPqSJzkzzYK4iYAQCAOYYyJV2DI7Cx+bKtJKMK5KvKzMXFELEADsjAWGUVyoWeQAZIaIEUQt1TStPRJJeRpbL5VU9bphrqeJrflj1QajSazearTbgPIYA7nUq3cEPR7ev0yIwAGJQCD4NXKuPzZRuW5vUJ+Dk3LwXDBoRjASlM2tTRgANws2DJlImUxpYI2EIZGCk09WqiZF3+jFZXNBrN5rE406kdYNtx4Au9Ev6YdyIlctzGw+mtujLuNgW94qtLqkoZa4bymcYHuKqyPUqDbR9XPLwb3LO8K3jGUuUDB943jS1rVtFM0xdL9ih/d1RXFX0nBPGpGF4HhbCgfgwIcCC4PgxCXUYKE3A8LwfAwXApHqEQQAYmJmNY1Jiy/TCvRw4931PFgrl4XZWHImMIHvVZikJRgMjvBTqKtdxuN8NiGnQhMuKY7S+NdVZBMYP9cMAsSAGVvgwMANhkyi1OCXA7Ic5TnMfeCwDwa57EuEAXPg4JEM0wyWKkYy9PjfEbnJOwsGCkKwsY7xtPYmLv1M7DK2JK4rHpLU/A8ERYCRGYvHRDcYAPYo5zYJtsHpCAiVRHgMVrAcAANYAwbrjliAAZJBWymWcq3a9FMTJbqACt8EEAaMHSIanlbT5fg87Ut1mvrurq81LPw/VbKmByAFEEEEKAnNjKiEOfJVOXcjZIJC3c7EuMQAD4DPSyLjLQZKQjXUQ/vCgHWPY4LOgEmgc2of8/QGXgIDLBwHsYOcQPGDcdwbPcvFbdtYheLtYj7AcByHakQTHCcdgxLcJvnetdiXFcYDXLUN127VdybKBDtCyy7QcXHL2pZp4iA3QvJSp6IFfXAMYyT8cu9Cz+nF6tQJO+X7uC6C5RELHFaQ8XUIzWHNd/b0GoAcnwUJFtgXBLiKh5Yg5AApZheCiEtBAmHgdxgK55TAcYexgZEKVsYA7BEFbGAgQRxnwCwAC8U8jEXsarOFGCmjEF0+aBvrxPPHg5QRyVgZE4GiJ4pgsDxIh7E5+18Vt8VwEOOEYA5WAgb4N1ZpmfY592EtiAXOFefHU9b2Bo/jxuy7OdIOS7uxyVq7WAN1oiIlIgsApgGXqn1BX1M857RHESGeKitJjXom4vo4s4oAP+GtaHjFtGU+JF+C8D/lfA21wjbeVClaFSz0ACEz80qv2Mh/X+B9GCcS/pcAB9thLH2jJpVu4wO52Avt/a+wYYFyXek+WSYhUFaUBmkAhIQj4o11qQtuFCIEHxoXLOh8k4ESCVowFB/10HsLtpwoBOtoxnXso5aBslREW1om5c6b1zbwSYODT6lxgZiOKGDP6GBIGwwAVwpwutmASSkkIsSd94xKUQekKRL8jLvxBvArBMAso0UvgAzoQA==).

For a variety of test cases related to converting between a `byte`/`int` and a `bool`, the JIT (as of `Core CLR v4.700.20.6603`, which is what SharpLab is using), generates pretty poor code unless I perform a pointer-dereference cast between `bool` and `byte`.

What is more interesting and concerning is that I get better results by calling a utility method that *does the same thing* than doing it in that function. Observe:

`
public static unsafe int AsInteger(this bool foo) {
	return *(byte*)&foo;
}
`
`
public static unsafe int Cast(bool foo) {
	return *(byte*)&foo;
}
`
`
public static int CastUtility(bool foo) {
	return foo.AsInteger();
}
`

`Cast`'s JIT output:
`	mov [rsp+0x8], ecx`
`	movzx eax, byte [rsp+0x8]`
`	ret`

`CastUtility`'s JIT output:
`	movzx eax, cl`
`	ret`

The codegen is actually substantially worse if I specify that I want to use Roslyn `master`, as well. 

category:cq
theme:optimization
skill-level:intermediate
cost:medium

**Comment by EgorBo** [comment]
> What is more interesting and concerning is that I get better results by calling a utility method that does the same thing than doing it in that function. Observe:

Hm.. interesting here is the IR diff (in morph phase):

The one with inlining (`CastUtility`):
```
[000003] --C---------              *  RETURN    int   
[000007] ---XG-------              \--*  CAST      int <- int
[000006] *--XG-------                 \--*  IND       ubyte 
[000005] ------------                    \--*  ADDR      long  
[000004] -------N----                       \--*  LCL_VAR   int    V02 tmp1         
```

without inlining (`Cast`)
```
[000003] ---XG-------              *  RETURN    int   
[000002] *--XG-------              \--*  IND       ubyte 
[000001] ------------                 \--*  ADDR      long  
[000000] -------N----                    \--*  LCL_VAR   int    V00 arg0   
```
So the difference is the GT_CAST node 🙂 

2) From your sharplab:

> // I'm impressed that the JIT compiler is effectively unable to optimize this.

That should be fixed via https://github.com/dotnet/runtime/pull/32716

**Comment by SingleAccretion** [comment]
It appears that better codegen for `CastUtility` [may not be better after all](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIAYACASQDsMYBzGKAFQE8ADjEYBeRsXIA6AEL8OAbhoB6ZQxbsuPAcLETpbDAGZSS2tWJH9SCaUYyIEADYxsrAMoBXfLhoBvGkYgiStJGwBLdkYAYWwnME8nbA4vfAB5ADMHZ1wAdXCMAAsAVQxwpwLwmFwACmBHJ0ZsNEZ651aWtsawAEpA4IDqYOGJAHZGADEoCHxspylY3AxS8oL+GuwexgBqSenZhoW8ZbKKjHXgLd2pmbmjpZWz9d6zYYBffpHGT5DrRkiMDE4gkkilvJk5nkCoVFhhal0mp0Gh1Wsjej9Bl8gsRxjcDs57hgNlc9rdDrC6iS8XcKS8fh9qAy6KFyDYyKT8Y1McFVEClpFOP9cIwiiIMsdqhhOp5AQATCAC/6AgBu4WwTUYMtW50Y+BgRQgspFhWSUjNP158uqxpEAH1cNg9bbjQKzVIhYxxUseFIfpY/oYtHwhCJYY81nVkRlHFtuV8cZ7HFIAIK4QPcKA1HqvYIM4Z+lk2dPaEN8okI6MQWM/YaeVgOjIiONY7HjABUdXkMDbPQAZJWc1887mWzQmRZC7ZGKnwzq/MEC386w2RMXg7pU2uakVwsKKzHGM3hgmO8Auz3+45B4wGW8gA).

**Comment by ameisen** [comment]
So, just *getting* the value via a utility method produces better code, but *using* it does not.

I would, regardless, consider this sequence to be a codegen issue as well:

`movzx eax, cl`
`movzx eax, al`
`movzx edx, dl`
`movzx edx, dl`

It's... very odd. It writes to `eax`, then immediately writes to it again. It then moves `dl` to `edx`... and then immediately does it again.

**Comment by ameisen** [comment]
[Another pathological case](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIAYACY8gOgCUBXAOwwEt8MVgGEI+AA58ANjCgBlWQDc+YGLgDcNOgGZmpRsJoBvGozPNdLJIz69GAWQAUtjIwQBKU+ZPVzf5gDsjAB+oWHhEZFR0THBCJq+5gC+NElAA=)

`not eax`
`not eax`
...
`not eax`
`not eax`

**Comment by SingleAccretion** [comment]
> return ~ ... ~x;
My understanding is that the JIT today doesn't do many of what could be considered "peephole optimizations".

**Comment by EgorBo** [comment]
> > return ~ ... ~x;
> 
> My understanding is that today the JIT doesn't do many of what could be considered "peephole optimizations".

**Comment by EgorBo** [comment]
_oops, closed accidentally_ 

> return ~ ... ~x;

This one can be handled as part of https://github.com/dotnet/runtime/pull/32000

> // I'm impressed that the JIT compiler is effectively unable to optimize this.

This one is fixed in https://github.com/dotnet/runtime/pull/32716

`Cast` vs `CastUtility` looks interesting, the only difference in jit IR between them is a `GT_CAST` node in `CastUtility`

**Comment by ameisen** [comment]
The NOT(NOT(x)) case also applies to NEG(NEG(x)). Or `~-~-~-~-~-~-~-~-~-x`.

**Comment by BruceForstall** [comment]
There are multiple issues here.

For the case of BooleanSums:CalculateSumOfBoolsWithUtilities(bool,bool,bool):int :
```
movzx    rax, cl
movzx    rax, al
movzx    rdx, dl
movzx    rdx, dl
add      eax, edx
movzx    rdx, r8b
movzx    rdx, dl
add      eax, edx
```
The JIT doesn't have any kind of late bitwise value propagation optimization to notice the extra zero extensions.

They come into play because we set up arguments for the inline call, e.g.:
```
***** BB01
STMT00007 (IL 0x000...  ???)
               [000026] -A----------              *  ASG       bool
               [000025] D------N----              +--*  LCL_VAR   bool   V06 tmp3
               [000000] ------------              \--*  LCL_VAR   bool   V00 arg0

***** BB01
STMT00002 (IL   ???...  ???)
               [000006] -AC---------              *  ASG       int
               [000005] D------N----              +--*  LCL_VAR   int    V04 tmp1
               [000020] --C---------              \--*  CAST      int <- ubyte <- int
               [000024] *--XG-------                 \--*  IND       ubyte
               [000023] ------------                    \--*  ADDR      long
               [000022] -------N----                       \--*  LCL_VAR   int    V06 tmp3
```

After morph, the argument setup inserts a cast, and the inline function still has a cast:
```
***** BB01
STMT00007 (IL 0x000...  ???)
               [000026] -A---+------              *  ASG       bool
               [000025] D----+-N----              +--*  LCL_VAR   int    V06 tmp3
               [000048] -----+------              \--*  CAST      int <- bool <- int
               [000000] -----+------                 \--*  LCL_VAR   int    V00 arg0

***** BB01
STMT00002 (IL   ???...  ???)
               [000006] -A---+------              *  ASG       int
               [000005] D----+-N----              +--*  LCL_VAR   int    V04 tmp1
               [000020] -----+------              \--*  CAST      int <- ubyte <- int
               [000022] -----+------                 \--*  LCL_VAR   int    V06 tmp3
```

Presumably this could be addressed by forward substituting tmp3 into the use, Without the cast, presumably value numbering would clean it up.

Comments, @AndyAyersMS ?

**Comment by AndyAyersMS** [comment]
What is it that is blocking direct sub by the inliner (`impInlineFetchArg`)? Is it that the arg does not look simple (say a cast of a lcl var) and has multiple uses?

**Comment by jakobbotsch** [comment]
All the cases from this issue look to be fixed in .NET 8 when I refresh the codegen results on the SharpLab links.
