### ISSUE TITLE
Re-evaluate the nullabilty of eventName parameters in EventSourceActivity

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#35157]
The public methods on this internal type have xmldoc that says that eventName can be null.

https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/EventSourceActivity.cs#L167-L180

But one of the two ArgumentNullException sources in this class is for when eventName is null:

https://github.com/dotnet/runtime/blob/363b7add1906547eeba681b3f3ec3f686a603dee/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/EventSourceActivity.cs#L260-L268

maybe there's something I'm missing, though.  Spotted in a code review for updating parameter names for ArgumentException types.

**Comment by tarekgh** [comment]
@tommcdon @noahfalk I believe you own this one. could you please triage it?

**Comment by tommcdon** [comment]
@sywhang @josalem

**Comment by josalem** [comment]
If I recall, the nullability was added with dotnet/coreclr#24070 which looks like it may have been done in an automated fashion.  Is the expectation that a `nullable` parameter can be `null` on invocation and not incur a `ArgumentNullException`?  If so, then the parameter shouldn't be `nullable`.  I can do an audit of EventSource*.cs later this week.

**Comment by bartonjs** [comment]
>  Is the expectation that a nullable parameter can be null on invocation and not incur a ArgumentNullException?

Yes, that's what it means to be marked as nullable.  Nullability has no runtime impact, so declaring something to be not-null just means "this is going to throw an ArgumentNullException, or some less nice failure, if you pass null"

**Comment by noahfalk** [comment]
This was dead code and has been removed from the product entirely: https://github.com/dotnet/runtime/pull/55575
