### ISSUE TITLE
System.Text.Json JsonStringEnumConverter per enum naming policy 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#35163]
System.Text.Json JsonStringEnumConverter per enum naming policy 

```cs
public JsonStringEnumConverter(JsonNamingPolicy namingPolicy = null, bool allowIntegerValues = true)
```

The constructor exists, but how would you apply a camelCase naming policy on a specific enum type without creating new attributes or derived converters?

```cs
[JsonConverter(typeof(JsonStringEnumConverter))] // how to camel case?
public enum Foo
{
    Bar = 1 
    Baz = 2
}
```

**Comment by layomia** [comment]
Derive a new custom attribute from `JsonConverterAttribute` & override the `CreateConverter` method:

```csharp
public class JsonStringWithCamelCaseEnumConverterAttribute : JsonConverterAttribute
{
    public override JsonConverter CreateConverter(Type typeToConvert) =>
        new JsonStringEnumConverter(namingPolicy: JsonNamingPolicy.CamelCase);
}

[JsonStringWithCamelCaseEnumConverter]
public enum Foo
{
    Bar = 1,
    Baz = 2
}

Console.WriteLine(JsonSerializer.Serialize(Foo.Bar)); // "bar"
```

**Comment by layomia** [comment]
> without creating new attributes

Is there a limitation with creating a new attribute? This is currently the most feasible solution here, AFAIK.

**Comment by layomia** [comment]
> without creating new attributes or derived converters?

Can you explain more about your scenario? Is there a limitation with creating a new attribute or deriving from `JsonStringEnumConverter`? These are the most feasible solutions here, AFAIK.

**Comment by layomia** [comment]
The recommended way to do this is to derive from `JsonConverterAttribute`, override the `CreateConverter` method, and return an instance of the `JsonStringEnumConverter` factory constructed with the desired naming policy (or get the `JsonConverter<TEnum>` instance from the factory).
