### ISSUE TITLE
Did we need the union class type?

### ISSUE THREAD

**Issue by BenLampson** [dotnet/runtime#35172]
Currently, the Blazor published preview 4.
But in my project(base on React's ANTD component to create the Blazor Component library) we found the "Demand UnionType".
There's React operation like this:
[Union Type in React](https://ant.design/components/grid/#API)
The same property can get different types used to do a different operation.
Even I realization the sample union type, like this:
```C#
UnionType<int, string, TestClass> _testInstance = 1;
var x=_testInstance.Value;
_testInstance = "";
var y=_testInstance.Value;
_testInstance = new TestClass();
var z=_testInstance.Value;
```
You can find the all test case in[Test Case](https://github.com/luanniao/Core/tree/master/src/Z.LuanNiao.Core.Test)
But, I think this type is the global case in Blazor, doesn't it?
And if I want to realization all case maybe I need to copy paste so many times to join as most type as we can ***write*** ..

And, there are so many bugs in my realization( It sample right now). But If we can add this type to a standard that so cool, cause you guys so strong than me in MS right, Maybe you can do super things than my demo(I'm sure about this, that's why I'm here)

In my realization, I create the instance every time, I try to use the BCL's operation(like the value type case I try to use get hashcode to compare) to fix the performance, but if this class in the BCL, it can do more things than me.

So, can we add the union class in the .NET standard?

**Comment by AaronRobinsonMSFT** [comment]
@BenLampson This is a similar idea to COM [Variant](https://docs.microsoft.com/windows/win32/api/oaidl/ns-oaidl-variant). Exposing a way to do this in C# has been discussed before and can be found over in the language repo: https://github.com/dotnet/csharplang/issues/687.

**Comment by jkotas** [comment]
Another variant is https://github.com/dotnet/csharplang/issues/113 . It is not do this well.

Let's use the csharplang repo to discuss this. This is primarily a C# language feature.
