### ISSUE TITLE
[Uri] Add UriScheme Properties: SSH, FTPS, SFTP, WS, WSS

### ISSUE THREAD

**Issue by ArthurHNL** [dotnet/runtime#35180]
Currently, the `System.Uri` class has static fields for the Scheme part of a URI  of common protocols:

- `UriSchemeFile`
- `UriSchemeFtp`
- `UriSchemeGopher`
- `UriSchemeHttp`
- `UriSchemeHttps`
- `UriSchemeMailto`
- `UriSchemeNetPipe`
- `UriSchemeNetTcp`
- `UriSchemeNews`
- `UriSchemeNntp`

I, however, think that this list is out of date and that the following URI Schemes would be a good addition for the .NET 5 era:

- `UriSchemeSsh = "ssh"` for [secure shell access](https://en.wikipedia.org/wiki/Secure_Shell).
- `UriSchemeFtps = "ftps"` and `UriSchemeSftp = "sftp"` for [secure](https://en.wikipedia.org/wiki/FTPS) [filetransfer](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol).
- `UriSchemeWs = "ws"` and `UriSchemeWss = "wss"` for [(secure) websockets](https://en.wikipedia.org/wiki/WebSocket).

`UriSchemeTelnet = "telnet"` might be considered for interaction with legacy systems.

# Proposal

Extend the list of well-known Uri schemes with more commonly used schemes.

```c#
namespace System
{
    public class Uri
    {
        // Existing
        public static readonly string UriSchemeFile;
        public static readonly string UriSchemeFtp;
        public static readonly string UriSchemeGopher;
        public static readonly string UriSchemeHttp;
        public static readonly string UriSchemeHttps;
        public static readonly string UriSchemeMailto;
        public static readonly string UriSchemeNews;
        public static readonly string UriSchemeNntp;
        public static readonly string UriSchemeNetTcp;
        public static readonly string UriSchemeNetPipe;

        // Proposed
        public static readonly string UriSchemeWs;
        public static readonly string UriSchemeWss;
        public static readonly string UriSchemeSsh;
        public static readonly string UriSchemeTelnet;
        public static readonly string UriSchemeSftp; // SSH File Transfer Protocol
        public static readonly string UriSchemeFtps; // FTP over SSL
    }
}
```

**Comment by scalablecory** [comment]
I'm okay with adding these APIs. We should look to see if any other common schemes could be added at the same time. @mihazupan what do you think?

**Comment by MihaZupan** [comment]
I think it makes sense adding them. 

Ws, Wss and Telnet already exist, just aren't publicly exposed.

The idea of this list of schemes is that Uri has built-in knowledge of them to provide validation and avoid an allocation of the scheme string when parsing.
Adding more validation to new schemes now would be a breaking change (likely acceptable), but we can at the very least avoid the scheme string allocation.

```c#
namespace System
{
    public class Uri
    {
        // Existing
        public static readonly string UriSchemeFile;
        public static readonly string UriSchemeFtp;
        public static readonly string UriSchemeGopher;
        public static readonly string UriSchemeHttp;
        public static readonly string UriSchemeHttps;
        public static readonly string UriSchemeMailto;
        public static readonly string UriSchemeNews;
        public static readonly string UriSchemeNntp;
        public static readonly string UriSchemeNetTcp;
        public static readonly string UriSchemeNetPipe;

        // Proposed
        public static readonly string UriSchemeWs;
        public static readonly string UriSchemeWss;
        public static readonly string UriSchemeSsh;
        public static readonly string UriSchemeTelnet;
        public static readonly string UriSchemeFtps;
        public static readonly string UriSchemeSftp;
    }
}
```

Should any other schemes be considered? `data` comes to mind.

**Comment by ArthurHNL** [comment]
IANA maintains [a list of all official URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml). Surprisingly, `ftps` is not on the list, yet `spotify` and `steam` are.

**Comment by karelz** [comment]
So what is the value of these APIs? Just to save 1 memory allocation? Is it really worth it?

**Comment by MihaZupan** [comment]
> So what is the value of these APIs? Just to save 1 memory allocation?

No, this is to provide a list of _common_ well-known Uri schemes (akin to MediaTypeNames #1489).

Whether to use the optimization of saving the scheme allocation is completely up to Uri - an implementation detail that currently holds true for schemes in this list (and ws, wss, telnet).

**Comment by MihaZupan** [comment]
@ArthurHNL I've edited your post with the proposal template and the API has been added to the [review](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) backlog.

**Comment by terrajobst** [comment]
* The names and API shape makes sense.
* The only concern that we have is whether supporting those schemes has any implications on other parts of URI, such as in `UriParser` and populating defaults, such as ports. Is there any extra work we'd be signing up to support those? If so, we may want to be more selective what we support. @dotnet/ncl, could you double check?

```C#
namespace System
{
    public partial class Uri
    {
        public static readonly string UriSchemeWs;
        public static readonly string UriSchemeWss;
        public static readonly string UriSchemeSsh;
        public static readonly string UriSchemeTelnet;
        public static readonly string UriSchemeSftp;
        public static readonly string UriSchemeFtps;
    }
}
```

**Comment by poke** [comment]
Hey, I just wanted to let you know that I began working on this in #43375. I’m still struggling a bit with the build system but will add tests later. I would be happy about some early feedback though!

**Comment by scalablecory** [comment]
Thanks @poke, let me assign the issue to you. Please ask questions if you have any!

**Comment by poke** [comment]
The PR was merged so this issue can be closed :blush:

**Comment by MihaZupan** [comment]
Thanks!
