### ISSUE TITLE
Create implicit logging scopes from Activity.Tags

### ISSUE THREAD

**Issue by shirhatti** [dotnet/runtime#35209]
Builds upon the work in https://github.com/dotnet/runtime/issues/34305

This is a proposal to implicitly flow Activity.Tags to ILogger scopes by creating implicit logging scopes from Activity.Tags. Based on our offline discussion, we'll need to add an option to turn this on/off.

There is currently no consensus on whether this should be on by default.

In we decided not to do this, we'll at least need to provide guidance on the idiomatic way to do this.

**Comment by shirhatti** [comment]
In the 5.0 timeframe, we'll provide guidance via docs on how to do this. We may reconsider in the future.

**Comment by maryamariyan** [comment]
We are not going to provide this feature for now until we see a demand on it. 

> In we decided not to do this, we'll at least need to provide guidance on the idiomatic way to do this.

So therefore the next step for this issue is to provide documentation on adding Activity.Tags to logging.

**Comment by ericstj** [comment]
@shirhatti @tarekgh @noahfalk do you have any update on this?  Should it be considered for 6.0?

**Comment by tarekgh** [comment]
@ericstj we already have https://github.com/dotnet/runtime/issues/46571 which is the feature requested currently marked for 6.0. I believe if we implemented the requested feature will address the question in this issue. basically it will be opt-in choice to include the Tags (and the Baggage). We still discussing the feature though.

**Comment by tarekgh** [comment]
This is taken care of by the https://github.com/dotnet/runtime/pull/48722
