### ISSUE TITLE
Infrastructure - Rollout (May 2020)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#35202]
# Overview

We'll use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`.

| Change |  Impact | Assignee |
| --- | --- | --- | 
| https://github.com/dotnet/runtime/pull/35115 | The `src/coreclr/build.[cmd/sh]` script will be removed in favor of the root build script and the `src/coreclr/build-runtime.[cmd/sh]` script. | @jkoritzinsky |
| https://github.com/dotnet/runtime/pull/35176 | The netcoreapp5.0 Target Framework Moniker will be replaced with net5.0 | @ViktorHofer |
| https://github.com/dotnet/runtime/pull/35285 | Support for dotnet test in libraries will be added, and with that the command to measure code coverage changes to `dotnet test -f net5.0 /p:Coverage=true`. The existing test target won't be removed. | @ViktorHofer |
| https://github.com/dotnet/runtime/pull/35589 | The `TargetsNetFx`, `TargetsNetCoreApp` and `TargetsNetStandard` libraries helper properties will be removed. This is necessary to fix Intellisense issues in libraries projects. The recommended pattern is to condition on `TargetFramework` inside the project file (e.g. `TargetFramework.StartsWith('netstandard'))`) and on `TargetFrameworkIdentifier` outside of the project file (e.g. in Directory.Build.targets `'$(TargetFrameworkIdentifier)' == '.NETStandard'`). | @Anipik |

:warning: SDK will be updated to >= `5.0.100-preview.5.20228.8` (https://github.com/dotnet/installer#installers-and-binaries)

## Archive
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by marek-safar** [comment]
Will net5 TFM switch come together with msbuild/nuget updates?

**Comment by ViktorHofer** [comment]
The current sdk in dotnet/runtime already supports net5.0, there's no need to update the sdk again.

**Comment by ViktorHofer** [comment]
Closing as done.
