### ISSUE TITLE
CoreCLR tests on Mono runtime : Failures in Interop/NativeLibrary* tests

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#35219]
Several failures seen when running the Interop/NativeLibrary* tests. These are CoreCLR tests  run on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/Regressions/coreclr/Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh"

1. Interop/NativeLibraryResolveCallback/CallbackTests/CallbackTests.sh
2. Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh
3. Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh

Full stacks below : 

Interop/NativeLibraryResolveCallback/CallbackTests/CallbackTests.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/Reports/Interop.NativeLibraryResolveCallback/CallbackTests/CallbackTests.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun CallbackTests.dll ''
          Expected: 100
          Actual: 106
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/CallbackTests/CallbackTests.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.NativeLibraryResolveCallback/Interop.NativeLibraryResolveCallback.XUnitWrapper.cs(237,0): at Interop_NativeLibraryResolveCallback._CallbackTests_CallbackTests_._CallbackTests_CallbackTests_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         

***************************************        Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh [FAIL]
          
          Unhandled Exception:
          System.DllNotFoundException: NativeLib assembly:<unknown assembly> type:<unknown type> member:(null)
             at CallbackStressTest.Main() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/Interop/NativeLibraryResolveCallback/CallbackStressTest.cs:line 152
          [ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: NativeLib assembly:<unknown assembly> type:<unknown type> member:(null)
             at CallbackStressTest.Main() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/Interop/NativeLibraryResolveCallback/CallbackStressTest.cs:line 152
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/Reports/Interop.NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun CallbackStressTest.dll ''
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.NativeLibraryResolveCallback/Interop.NativeLibraryResolveCallback.XUnitWrapper.cs(140,0): at Interop_NativeLibraryResolveCallback._CallbackStressTest_CallbackStressTest_._CallbackStressTest_CallbackStressTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          

***************************************        Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveEvent/Reports/Interop.NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun ResolveEventTests.dll ''
          Expected: 100
          Actual: 105
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.NativeLibraryResolveEvent/Interop.NativeLibraryResolveEvent.XUnitWrapper.cs(140,0): at Interop_NativeLibraryResolveEvent._ResolveEventTests_ResolveEventTests_._ResolveEventTests_ResolveEventTests_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by CoffeeFlux** [comment]
Not-so-quick update:

After the NativeLibrary test refactoring, these names and our exclusions are no longer all accurate or useful. Regardless, the test content is the same, and the failure here is interesting. A minimal repro:

NativeLibrary.c: (compiled with `clang -c -fPIC NativeLibrary.c -o NativeLibrary.o` and `clang -shared -o libNativeLibrary.dylib NativeLibrary.o` and placed in the assembly directory)
```
int NativeSum(int a, int b) {
	return a + b;
}
```

HelloWorld.cs:
```
#define USE_DLLIMPORT

using System;
using System.Runtime.InteropServices;
using System.Reflection;

namespace HelloWorld
{
    class Program
    {
        const string bad_lib_name = "Test";
        const string good_lib_name = "NativeLibrary";

        static IntPtr ResolveDllImport(string libraryName, Assembly asm, DllImportSearchPath? dllImportSearchPath)
        {
            if (string.Equals(libraryName, bad_lib_name))
                return NativeLibrary.Load(good_lib_name, asm, DllImportSearchPath.AssemblyDirectory);
            return IntPtr.Zero;
        }

        static void Main(string[] args)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            DllImportResolver resolver = ResolveDllImport;
            NativeLibrary.SetDllImportResolver(assembly, resolver);
            int result = NativeSum(1, 2);
            Console.WriteLine(result);
        }

#if (USE_DLLIMPORT)
        [DllImport(bad_lib_name)]
        static extern int NativeSum(int arg1, int arg2);
#else
        [DllImport(good_lib_name)]
        [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory)]
        static extern int NativeSum(int arg1, int arg2);
#endif
    }
}
```

With the define commented out, this works fine. When uncommented, the fun begins: `NativeLibrary.Load` succeeds, the library appears to successfully be propagated through the `DllImportResolver` delegate, the pinvoke lookup succeeds and `piinfo->addr` is set correctly, but then... we throw a DllNotFoundException anyway. We appear to call `mono_lookup_pinvoke_call_internal` twice for the same `NativeSum` method, with the first lookup failing. This seems normal since I think we intentionally attempt to resolve the `addr` when generating the IR for the pinvoke, and at that point the `DllImportResolver` probably isn't set up, but I've put the two stack traces below just in case:
```
	0x10aa3948e - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_lookup_pinvoke_call_internal
	0x10a9cd878 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_marshal_get_native_wrapper
	0x10a8393bc - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_method_to_ir
	0x10a810279 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mini_method_compile
	0x10a81276c - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_compile_method_inner
	0x10a816672 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_compile_method_with_opt
	0x10a81a693 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_runtime_invoke
	0x10a9f6748 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_runtime_invoke_checked
	0x10a9fcaa5 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_runtime_exec_main_checked
	0x10a875eac - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_exec
	0x10a878fa6 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_main
	0x10a8f2259 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : monovm_execute_assembly
```
```
	0x10f03d483 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_lookup_pinvoke_call_internal
	0x10ee19f5c - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_compile_method_with_opt
	0x10eebebff - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : common_call_trampoline
	0x10eebe670 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_magic_trampoline
	0x10f2b3396 - Unknown
	0x10f337c83 - Unknown
	0x10ee1ec8e - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_runtime_invoke
	0x10effa738 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_runtime_invoke_checked
	0x10f000a95 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_runtime_exec_main_checked
	0x10ee79e9c - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_jit_exec
	0x10ee7cf96 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : mono_main
	0x10eef6249 - /Users/ryan/git/runtime/.dotnet-mono/shared/Microsoft.NETCore.App/5.0.0-preview.8.20361.2/libcoreclr.dylib : monovm_execute_assembly
```

I believe you need the work in https://github.com/dotnet/runtime/pull/38975 to test this, but that should be merged soon.

**Comment by CoffeeFlux** [comment]
Figured out the exact issue here: the current version of `mono_marshal_get_native_wrapper` assumes that if the pinvoke address can't be resolved at IL generation on non-AOT, it will never be resolved and instead emits IL that just throws an exception. We need to lift those assumptions and fill in the address when the method is jitted if we're unable to resolve it previously, since on netcore we have runtime callbacks that can resolve it.

**Comment by CoffeeFlux** [comment]
This is actually nastier than I thought. You can have the PInvoke fail to resolve, set the callback, and _then_ have it resolve correctly... Updated sample:

```
using System;
using System.Runtime.InteropServices;
using System.Reflection;
namespace HelloWorld
{
    class Program
    {
        const string bad_lib_name = "Test";
        const string good_lib_name = "NativeLibrary";
        static IntPtr ResolveDllImport(string libraryName, Assembly asm, DllImportSearchPath? dllImportSearchPath)
        {
            if (string.Equals(libraryName, bad_lib_name))
                return NativeLibrary.Load(good_lib_name, asm, DllImportSearchPath.AssemblyDirectory);
            return IntPtr.Zero;
        }
        static void Main(string[] args)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            DllImportResolver resolver = ResolveDllImport;
            try
            {
                NativeSum(10, 10);
            }
            catch (DllNotFoundException)
            {
                Console.WriteLine("Exception thrown correctly");
            }
            NativeLibrary.SetDllImportResolver(assembly, resolver);
            int result = NativeSum(1, 2);
            Console.WriteLine(result);
        }
        [DllImport(bad_lib_name)]
        static extern int NativeSum(int arg1, int arg2);
    }
}
```

**Comment by CoffeeFlux** [comment]
Keeping open until the issues.targets is updated.
