### ISSUE TITLE
Runtime build.cmd lets random values through

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#35222]
Follow up to #34782 

`Build.cmd` in the root of the `runtime` repo lets random values on several parameters pass and actually start the building process, only to fail much later with unrelated, and therefore misguiding errors. It is worth highlighting this happens both, on Windows and Linux. Running various cases, the flags that allow these "garbage" parameters are:
- Configuration
- OS
- Architecture

I've started working on this, but there are other things that remain unclear, which are preventing me of making further progress.

- Does `build.cmd` support any platform other than Windows? The `-help` says the possible options are `Windows_NT` and `Unix`, but the latter fails. This help documentation might need to be updated.
- On the other hand, `build.sh` lists a whole different (and bigger) list of supported platforms: Windows, Linux, FreeBSD, OSX, tvOS, iOS, Android, WebAssembly. Can I assume Windows is wrong here as `build.cmd` does that?

A funny story that added to my motivation on working on this fix, is that I spent so much time one day trying to build `runtime` only to fail over and over again. It turns out I had a typo in one of those flags.

**Comment by ivdiazsa** [comment]
cc @dotnet/runtime-infrastructure

**Comment by hypeartist** [comment]
> Follow up to #34782 
> * Does `build.cmd` support any platform other than Windows? The `-help` says the possible options are `Windows_NT` and `Unix`, but the latter fails. 

Just finished my first (Windows) build with the new build system with the following args:

```
call build.cmd -subset Clr -os Windows_NT -arch x64 -cofiguration Debug -runtimeConfiguration Debug
```
Build succeeded. And completed quite fast.

**Comment by ViktorHofer** [comment]
You have a typo in configuration. Also you don't need to specify os and arch as they default to the appropriate values.
