### ISSUE TITLE
System.Text.Json.JsonSerializer.DeserializeAsync<T> may throw JsonException when deserialize large json stream.

### ISSUE THREAD

**Issue by lhrbu** [dotnet/runtime#35239]
Try to Deserialize a json file larger > 200kB, DeserializeAsync<T> will throw JsonException that said "The JSON value could not be converted to...". And if I change the default buffer size by setting JsonSerializerOptions to 200kB, then the method works normally.

**Comment by lhrbu** [comment]
I uploaded the json file and JsonSerializerOptions settings here:
https://github.com/lhrbu/ReproduceJsonFile

**Comment by layomia** [comment]
Thanks for the repro. Can you also provide the definition for the type you are deserializing into (& every type in its type graph)? 

This may be related to https://github.com/dotnet/runtime/issues/34564.

**Comment by lhrbu** [comment]
I uploaded a demo csproj:
https://github.com/lhrbu/ReproduceJsonFile

And it will throw exception below if not set defaultBufferSize:
System.Text.Json.JsonException:“The JSON value could not be converted to JsonBench.EquipmentInfo. Path: $.$values[77].CalibrationInfo.EquipmentInfo | LineNumber: 2261 | BytePositionInLine: 33.”

**Comment by lhrbu** [comment]
And dotnet SDK is: 5.0.100-preview.2

**Comment by layomia** [comment]
Thanks @lhrbu, I'll take a look.

**Comment by layomia** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/35046 (See the bullet on "Issue when combining ReferenceHandling.Preserve and DeserializeAsync" in the issue description). Please let us know if you still face issues with this.
