### ISSUE TITLE
.NET 5 How to receive UDP packet by using System.Net.Sockets.Socket and get the sender endpoint?

### ISSUE THREAD

**Issue by yukozh** [dotnet/runtime#35230]
.NET 5 How to receive UDP packet by using System.Net.Sockets.Socket and **get the sender endpoint**?

**Comment by tmds** [comment]
Use `ReceiveFrom*` methods? https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=net-5.0#methods

**Comment by scalablecory** [comment]
Looks like @tmds answered this one already, so I'm closing this out. Thanks for the question.
