### ISSUE TITLE
CoreCLR tests on Mono runtime : Failures in GC/API/* tests

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#35250]
Several failures seen when running the GC/API/* tests. These are CoreCLR tests run on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/Regressions/coreclr/Interop/PInvoke/AsAny/AsAnyTest/AsAnyTest.sh"

Failing tests ::

1. GC/API/GC/AddThresholdTest/AddThresholdTest.sh
2. GC/API/WeakReference/Finalize2/Finalize2.sh
3. GC/API/GC/CollectionCountTest/CollectionCountTest.sh
4. GC/API/GC/AddMemoryPressureTest/AddMemoryPressureTest.sh
5. GC/API/GC/GetGeneration/GetGeneration.sh
6. GC/API/GC/MaxGeneration/MaxGeneration.sh
7. GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh
8. GC/API/GC/Collect1/Collect1.sh
9. GC/API/GC/AddUsageTest/AddUsageTest.sh
10. GC/API/GC/AllocateUninitializedArray/AllocateUninitializedArray.sh
11. GC/API/GC/GetGenerationWR/GetGenerationWR.sh
12. GC/API/GC/RemoveUsageTest/RemoveUsageTest.sh
13. GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh

Full stacks for individual tests below :

******************    GC/API/GC/AddThresholdTest/AddThresholdTest.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/AddThresholdTest/AddThresholdTest.output.txt
          Raw output:
          
\r\n          
BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun AddThresholdTest.dll ''
          0 0
          ThresholdTest Failed
          
          Test Failed
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/AddThresholdTest/AddThresholdTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(237,0): at GC_API._GC_AddThreoldTest_AddThreoldTest_._GC_AddThresholdTest_AddThresholdTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   

******************        GC/API/WeakReference/Finalize2/Finalize2.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/WeakReference/Finalize2/Finalize2.output.txt
          Raw output:
               
BEGIN EXECUTION    
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun Finalize2.dll ''
          Running ~SetTargetTest
          setTarget failed
          
          Running ~GetTargetTest
          getTarget passed
          
          
          Short WR Test Failed!
          
          
          Running ~IsAliveTest
          IsAlive failed
          
          Running ~GetTargetTest
          getTarget failed
          
          Running ~SetTargetTest
          Caught expected InvalidOperationException
          setTarget passed
          
          Running ~IsAliveTest
          IsAliveTest passed
          
          
          Long WR Test Passed!
          
          
          Test Failed!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/WeakReference/Finalize2/Finalize2.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(3341,0): at GC_API._WeakReference_Finalize2_Finalize2_._WeakReference_Finalize2_Finalize2_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

******************        GC/API/GC/CollectionCountTest/CollectionCountTest.sh [FAIL]
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/CollectionCountTest/CollectionCountTest.output.txt
          Raw output:
          BEGIN EXECUTION

          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun CollectionCountTest.dll ''
          NegativeTest passed
          LargeValueTest passed
          Failure at CollectionTest(0)
          Test Failed
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/CollectionCountTest/CollectionCountTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(722,0): at GC_API._GC_CollectionCountTest_CollectionCountTest_._GC_CollectionCountTest_CollectionCountTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

******************     GC/API/GC/AddMemoryPressureTest/AddMemoryPressureTest.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/AddMemoryPressureTest/AddMemoryPressureTest.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun AddMemoryPressureTest.dll ''
          TooSmallTest Passed
          TooLargeTest Passed
          StressTest Started...
          0 0
          StressTest Failed
          
          Test Failed
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/AddMemoryPressureTest/AddMemoryPressureTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(140,0): at GC_API._GC_AddMemoryPressureTest_AddMemoryPressureTest_._GC_AddMemoryPressureTest_AddMemoryPressureTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         

******************        GC/API/GC/GetGeneration/GetGeneration.sh [FAIL]
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/GetGeneration/GetGeneration.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun GetGeneration.dll ''
          0 0
          ObjectTest Failed!
          0 0
          arrayTest Failed!
          failTest Failed!
          
          Test for GetGeneration() FAILED!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/GetGeneration/GetGeneration.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(1304,0): at GC_API._GC_GetGeneration_GetGeneration_._GC_GetGeneration_GetGeneration_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

 
********************        GC/API/GC/MaxGeneration/MaxGeneration.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/MaxGeneration/MaxGeneration.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun MaxGeneration.dll ''
          Max Generations: 1
          Test for GC.MaxGeneration failed!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/MaxGeneration/MaxGeneration.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(1692,0): at GC_API._GC_MaxGeneration_MaxGeneration_._GC_MaxGeneration_MaxGeneration_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  

       

********************         GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh [FAIL]
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/GetGeneration_fail/GetGeneration_fail.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun GetGeneration_fail.dll ''
          This test should throw an exception!
          Generation: 0
          Generation: 1
          Test for GetGeneration() failed!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(1498,0): at GC_API._GC_GetGeneration_fail_GetGeneration_fail_._GC_GetGeneration_fail_GetGeneration_fail_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         

********************         GC/API/GC/Collect1/Collect1.sh [FAIL]

          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/Collect1/Collect1.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun Collect1.dll ''
          Array is in generation: 0
          Object is in generation: 0
          Collect(1)
          Array is in generation: 0
          Object is in generation: 0
          Test for GC.Collect(1) failed!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/Collect1/Collect1.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(625,0): at GC_API._GC_Collect1_Collect1_._GC_Collect1_Collect1_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

********************         GC/API/GC/AddUsageTest/AddUsageTest.sh [FAIL]

          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/AddUsageTest/AddUsageTest.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun AddUsageTest.dll ''
          0 0
          AddTest Failed
          
          Test Failed
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/AddUsageTest/AddUsageTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(334,0): at GC_API._GC_AddUsageTest_AddUsageTest_._GC_AddUsageTest_AddUsageTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**********************************************        GC/API/GC/AllocateUninitializedArray/AllocateUninitializedArray.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/AllocateUninitializedArray/AllocateUninitializedArray.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun AllocateUninitializedArray.dll ''
          Scenario 6 Expected exception!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/AllocateUninitializedArray/AllocateUninitializedArray.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(431,0): at GC_API._GC_AllocateUninitializedArray_AllocateUninitializedArray_._GC_AllocateUninitializedArray_AllocateUninitializedArray_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**********************************        GC/API/GC/GetGenerationWR/GetGenerationWR.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/GetGenerationWR/GetGenerationWR.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun GetGenerationWR.dll ''
          Expected exception not thrown!
          Test failed!
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/GetGenerationWR/GetGenerationWR.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(1401,0): at GC_API._GC_GetGenerationWR_GetGenerationWR_._GC_GetGenerationWR_GetGenerationWR_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**********************************        GC/API/GC/RemoveUsageTest/RemoveUsageTest.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/RemoveUsageTest/RemoveUsageTest.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun RemoveUsageTest.dll ''
          0 0
          RemoveTest Failed
          
          Test Failed
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/RemoveUsageTest/RemoveUsageTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(1886,0): at GC_API._GC_RemoveUsageTest_RemoveUsageTest_._GC_RemoveUsageTest_RemoveUsageTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**********************************        GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh [FAIL]
          
          Unhandled Exception:
          System.Exception: Expected more memory to be allocated. previous.precise = 126665504, precise = 126664264, difference = 1240
             at Test.CallGetTotalAllocatedBytes(Counts previous, Int64& differenceBetweenPreciseAndImprecise) in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 72
             at Test.CallGetTotalAllocatedBytes(Counts previous) in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 79
             at Test.TestAnotherThread() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 132
             at Test.Main() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 179
          [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Expected more memory to be allocated. previous.precise = 126665504, precise = 126664264, difference = 1240
             at Test.CallGetTotalAllocatedBytes(Counts previous, Int64& differenceBetweenPreciseAndImprecise) in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 72
             at Test.CallGetTotalAllocatedBytes(Counts previous) in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 79
             at Test.TestAnotherThread() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 132
             at Test.Main() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/GC/API/GC/GetTotalAllocatedBytes.cs:line 179
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/Reports/GC.API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun GetTotalAllocatedBytes.dll ''
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(1595,0): at GC_API._GC_GetTotalAllocatedBytes_GetTotalAllocatedBytes_._GC_GetTotalAllocatedBytes_GetTotalAllocatedBytes_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by SamMonoRT** [comment]
@naricc - please investigate each individual failure and add comments on reason.

**Comment by naricc** [comment]
This doesn't seem to be a customer issue, so I am moving it to 8.

**Comment by SamMonoRT** [comment]
There are other individual issues opened for GC APIS needed for Mono and these tests excluded correctly. Closing this test failure issue
