### ISSUE TITLE
Pinned object heap impact on profilers

### ISSUE THREAD

**Issue by davmason** [dotnet/runtime#35258]
Overview issue in https://github.com/dotnet/runtime/issues/35561

After #32283 we have another GC heap for pinned objects. This will require at least the addition of a new entry to `COR_PRF_GC_GENERATION` and might require more work. This issue is tracking the investigation of any impact on profilers.

**Comment by davmason** [comment]
The enum value was already added, still need to investigate any remaining impact though

**Comment by davmason** [comment]
After doing some investigation, there is no work needed for the profiler. It will have impact on profilers since they may not expect the new generation, but there is no runtime work necessary.

**Comment by noahfalk** [comment]
David, re-opening this issue to make sure we've also considered if testing needs to be added and if the enum has been documented?

**Comment by davmason** [comment]
I don't believe there is any testing that needs added at this point, and the documentation is done. Closing this issue
