### ISSUE TITLE
Different output in Unix between Path.GetPathRoot overloads for redundant segments

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#35260]
While working on this [issue](https://github.com/dotnet/runtime/issues/2162) ([PR](https://github.com/dotnet/runtime/pull/2187)), I found a bug in the string overload for `Path.GetPathRoot` (Unix):

```cs
using System;
using System.IO;
namespace ConsoleAppCore
{
    class Program
    {
        static void Main()
        {
            string original = "/home/../folder/../..";
            string expected = "/";
            ReadOnlySpan<char> actualSpan = Path.GetPathRoot(original.AsSpan());
            string actualString = Path.GetPathRoot(original);
            Console.WriteLine($"Expected:      '{expected}'");
            Console.WriteLine($"Actual string: '{actualString}'");          // This returns '/'
            Console.WriteLine($"Actual span:   '{actualSpan.ToString()}'"); // This returns ''
        }
    }
}
```

I also found that running the same code in Windows will yield the behavior below, which is why I originally opened this issue, but @jkotas kindly pointed out it's expected behavior - the string method overload normalizes, while the span overload does not:

```cs
            Console.WriteLine($"Actual span:   '{actualSpan.ToString()}'"); // This returns '/'
            Console.WriteLine($"Actual string: '{actualString}'");          // This returns '\'
```

**Comment by carlossanlop** [comment]
Assigning to myself to investigate and fix since it's blocking my redundant segments PR.

**Comment by jkotas** [comment]
FWIW, this is by design. From https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getpathroot?view=netcore-3.1#System_IO_Path_GetPathRoot_System_ReadOnlySpan_System_Char__ :

Unlike the string overload, this method doesn't normalize directory separators.

**Comment by carlossanlop** [comment]
Thanks @jkotas. I assume the string overload was never modified to keep backwards compatibility, and the new behavior was only introduced in the span overload. Is this a correct assumption?

So is this something we would like to change in 5.0 and register as a breaking change?

**Comment by carlossanlop** [comment]
Thanks, @jankotas. I assume the behavior is different because we wanted to prevent introducing a breaking change in the old string overload method, and the new method had the behavior corrected to prevent normalization. I found a couple of places in our own code where the string overload of GetPathRoot is being used to normalize a path.

**Comment by carlossanlop** [comment]
I'm reopening this issue because I reviewed my notes more closely and realized the actual bug is in Unix.

**Comment by carlossanlop** [comment]
Found the root cause/ The `IsEffectivelyEmpty` check is wrong:
https://github.com/dotnet/runtime/blob/0a2f0e6da98a784601b37d19417b930a33b2c478/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L130-L133

It should be inverted to match the same way we check for empty in the string overload:
https://github.com/dotnet/runtime/blob/0a2f0e6da98a784601b37d19417b930a33b2c478/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L123-L128

I also noticed we do not have unit tests verifying this method. I'll include this fix in my PR for removing redundant segments, which also adds unit tests for the case that helped me find this problem.

**Comment by jkotas** [comment]
I would be better to submit the fix for the bug and the associated test coverage in separate PR.
