### ISSUE TITLE
Remove usage of non-generic collections from Mono's SPC

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#35282]
There are still few usages of non-generic collections in Mono's SPC (for example ArrayList) which should be replaced with generics implementation as their usage has been reduced in CoreFX and could help with size reduction effort.

**Comment by Marusyk** [comment]
I would prepare a PR for this. Please assign it to me

**Comment by Marusyk** [comment]
Should I replace this `Hashtable` to `Dictionary<string, string>` as well?

https://github.com/dotnet/runtime/blob/c9b6a7c70a5706c5db0bc2d015cff906a2ec834f/src/mono/netcore/System.Private.CoreLib/src/System/Environment.Unix.Mono.cs#L63-L77

**Comment by Marusyk** [comment]
Can we use `Dictionary<ConstructorInfo, ConstructorOnTypeBuilderInst>` here instead of `Hashtable`

https://github.com/dotnet/runtime/blob/c9b6a7c70a5706c5db0bc2d015cff906a2ec834f/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilderInstantiation.cs#L167-L173

**Comment by marek-safar** [comment]
> Can we use Dictionary<ConstructorInfo, ConstructorOnTypeBuilderInst> here instead of Hashtable

Yes, that should work

**Comment by vargaz** [comment]
There is a synchronized hash table in EncodingTable, tried removing it in:
https://github.com/dotnet/corefx/pull/41581
didn't work out.

**Comment by Marusyk** [comment]
@vargaz Are you sure this related to Mono?

**Comment by marek-safar** [comment]
We could have another stab on that (in the worst case we could if-def for size sensitive RIDs)
