### ISSUE TITLE
[arm64] sxtb, sxth, sxtw instructions disassembly incorrect

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#35303]
The JIT disassembly for the `sxtw` instruction is:
```
sxtw    x0, x21
```
It should instead use the `w` register form in the second position:
```
sxtw    x0, w21
```

**Comment by BruceForstall** [comment]
cc @kunalspathak (since you are looking at arm64 disassembly issues)

**Comment by echesakovMSFT** [comment]
`sxtb` and `sxth` as well

```asm
IN0291: 000A48  93401D47          sxtb    x7, x10
IN0292: 000A4C  93403D65          sxth    x5, x11
```

**Comment by echesakovMSFT** [comment]
I am going to fix since I am working nearby
