### ISSUE TITLE
Snap Installer Does not install on ARM64 Device - Nvidia Jetson Nano

### ISSUE THREAD

**Issue by gizmohd** [dotnet/runtime#3530]
# Issue Title

Unable to install SDK 3.0 on an ARM64 device using snap.

# General
Ran the command:

sudo snap install dotnet-sdk --beta --classic

got response:

error: snap "dotnet-sdk" is not available on beta for this architecture (arm64)
       but exists on other architectures (amd64).

Hardware:   Nvidia Jetson Nano

**Comment by ardacetinkaya** [comment]
I know that it would not be prioritized issue, but any plans to update snap store with latest previews. 

When I check no preiew-5 in 5.0/edge or 5.0/beta channels.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
