### ISSUE TITLE
Consider reworking how the x86 emitter handles the 'w' bit

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#35305]
As investigated on https://github.com/dotnet/runtime/pull/34550#issuecomment-613069007, the emitter currently has some odd support for detecting whether a given instruction uses the 'w' and 's' encoding bits.

It would likely benefit from having this be an `INS_FLAGS` entry that can be trivially checked to statically determine the appropriate encoding that is required.

category:implementation
theme:emitter
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
I'm going to move this to Future.

**Comment by anthonycanino** [comment]
@tannergooding I was re-reading your first comment, 

> - There's probably a bit of wonkiness in a few places since REX.W is part of the REX byte and we also have AddRex*PrefixIfNeeded
> - We already have a few helper functions like TakesRexWPrefix (I believe we also have a similar for Rex.B, not sure about Rex.X`)

and I wanted to clarify one point. These functions determine whether to emit the REX.W bit, and as part of a larger refactoring, we'll have to consider how that interplays with parts of the code that determine whether to emit the 'w' bit, but we are only talking about tracking the 'w' and 's' bits in the INS_FLAGS entry, not an additional 'REX.W' bit, correct?

**Comment by tannergooding** [comment]
Right, that was me conflating two different `w` bits in the original message. `REX.W` is different from the `w` bit actually being discussed here.

**Comment by anthonycanino** [comment]
@tanner I think we should close this out per the merged PR?
