### ISSUE TITLE
Prefix protected fields with underscore for the internal XmlRawWriter and its descendant classes

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#35320]
Related to code review comment https://github.com/dotnet/runtime/pull/35233#discussion_r412258966: `It's confusing to me to see fields without the underscore prefix.  It'd be nice to clean that up in the future.`

There is many fields could be updated accordingly, so creating separate issue

Note: XmlEncodedRawTextWriter is generated class don't forget to update templates

**Comment by krwq** [comment]
please don't pick up this issue until nullable work is done.

**Comment by Marusyk** [comment]
I would prepare a PR for this. Please assign it to me. 
@krwq do you mean #35233?

**Comment by krwq** [comment]
Yes and also please make sure you don't create any merge conflicts with https://github.com/dotnet/runtime/pull/35319

**Comment by siriak** [comment]
Should this be closed already? It seems that #35759 fixed it.

**Comment by Marusyk** [comment]
Yeah, it should be closed. @buyaa-n, please close

**Comment by buyaa-n** [comment]
Yes its done, thanks
