### ISSUE TITLE
Assemblies cannot be modified after loading AssemblyLoadContext is garbage collected

### ISSUE THREAD

**Issue by ccifra** [dotnet/runtime#35342]
# Assemblies cannot be modified after loading AssemblyLoadContext is garbage collected

# General

I would like to load assemblies in a custom AssemblyLoadContext to reflect on the types in the assembly.  It is important that after reflection I can unload the assembly so that it can be modified.  My expectation is that after an AssemblyLoadContext is garbage collected the loaded assembly should be able to be deleted / modified on disk.  This does not seem to work.

Here is a simple test app:

``` csharp
using System;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;

namespace TestALC
{
    class Program
    {
        static string AssemblyToLoad = @"A SIMPLE ASSEMBLY FULL PATH";
        static WeakReference<TestLoadContext> _testContextRef;

        static void Main(string[] args)
        {
            Console.WriteLine("Starting");
            DoLoadTest(AssemblyToLoad);
            while (_testContextRef.TryGetTarget(out _))
            {
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
                GC.WaitForPendingFinalizers();
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
            }
            Console.WriteLine("Unloaded ALC!");
            foreach (var item in AssemblyLoadContext.Default.Assemblies)
            {
                Console.WriteLine($"Default Assembly: {item.Location}");
            }
            Console.WriteLine("ALC Has Been GCed!");
            Console.WriteLine("Try to delete assembly now. Press Enter to Exit");
            Console.ReadLine();
        }

        static void DoLoadTest(string assemblyName)
        {
            var context = new TestLoadContext();
            _testContextRef = new WeakReference<TestLoadContext>(context);
            context.LoadTestAssembly(assemblyName);
            Console.WriteLine("Loaded");
            Console.WriteLine($"Context loaded: {context.Assemblies.Count()}");
            foreach (var item in context.Assemblies)
            {
                Console.WriteLine($"Assembly: {item.Location}");
            }
        }
    }
}

public class TestLoadContext : AssemblyLoadContext
{
    private Assembly _loadedAssembly;

    public TestLoadContext()
        : base(true)
    {
    }

    public void LoadTestAssembly(string path)
    {
        _loadedAssembly = LoadFromAssemblyPath(path);
    }
}
```

After the assembly is loaded and the ALC is garbage collected I try to delete the assembly on disk from Explorer.   Explorer cannot delete the file on disk and informs me that my test app still has the assembly loaded.

### **NOTE**:
I also noticed that the ALC is never garbage collected in a debug build (which is also a problem) so to test you need to do a release build.

**Comment by vitek-karas** [comment]
/cc @janvorli 

If you're only using this to reflect over assemblies I would suggest to use [`MetadataLoadContext`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext?view=dotnet-plat-ext-3.1) instead. You get a fully functional reflection API back (same `Type`, `MethodInfo`, ...), with the only limitation being that it can't run the code. It does not actually load the assemblies into the runtime in any way - it's a purely managed implementation (parses the IL byte-by-byte in managed code). That way there should be no issued with file locking - dispose the context and it should release everything.

I'll let @janvorli  answer the problem that the files seems to be locked.

**Comment by janvorli** [comment]
The sample has a couple of problems. 
* The `DoLoadTest` can get inlined into `Main` and the `Assembly` or `AssemblyLoadContext` can be still alive during the loop checking for unload completion. To fix that, you can add `[MethodImpl(MethodImplOptions.NoInlining)]` attribute to the `DoLoadTest` method.
* The `_testContextRef.TryGetTarget` pulls in the `AssemblyLoadContext` into the current frame. Depending on what JIT does, it can be stored in a register or a stack local variable that outlives the testing loop, preventing the unload. This could be the reason why unload doesn't work in debug build for you. I would recommend using non-generic `WeakReference` and use its `IsAlive` method as a check.
* The fact that the instance of `AssemblyLoadContext` is gone doesn't necessarily mean that the reference to the Assembly is already gone too. To make sure you can delete it, you'll need to also keep a weak reference to it and do the same check loop as you do for the `AssemblyLoadContext` (with the fix I've mentioned) Once that `WeakReference` is not alive anymore, you should be able to delete the assembly from disk.

**Comment by janvorli** [comment]
Btw, some of the stuff I've suggested is described here: https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability

**Comment by ccifra** [comment]
I think I have updated my example to match all of the recommendations and I still can't get the assembly to unload.  My new version below tries to wait for the Assembly to be garbage collected, which never happens.  So it makes sense that I can't delete the file on disk.  

I also tried calling Unload explicitly on the ALC, but that seems to make things worse.  If I call Unload then the ALC does not get garbage collected either.

Eventually we want to be able to execute code and then unload so the MetadataLoadContext is not going to completely solve our issue.  It looks like a really interesting way to do reflection.

Here is the updated version of my test app
``` csharp
using System;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;

namespace TestALC
{
    class Program
    {
        static string AssemblyToLoad = @"A SIMPLE ASSEMBLY FULL PATH";
        static WeakReference _testContextRef;
        static WeakReference _testAssemblyRef;

        static void Main(string[] args)
        {
            Console.WriteLine("Starting");
            DoLoadTest(AssemblyToLoad, out _testContextRef, out _testAssemblyRef);
            Console.WriteLine("Completed load test");
            while (_testContextRef.IsAlive)
            {
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
                GC.WaitForPendingFinalizers();
            }
            Console.WriteLine("ALC Has Been GCed!");
            foreach (var item in AssemblyLoadContext.Default.Assemblies)
            {
                Console.WriteLine($"Default Assembly: {item.Location}");
            }
            while (_testAssemblyRef.IsAlive)
            {
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
                GC.WaitForPendingFinalizers();
            }
            Console.WriteLine("Assembly Has Been GCed!");
            Console.WriteLine("Try to delete assembly now. Press Enter to Exit");
            Console.ReadLine();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void DoLoadTest(string assemblyName, out WeakReference alcReference, out WeakReference assemblyRef)
        {
            var context = new TestLoadContext();
            context.LoadTestAssembly(assemblyName);

            alcReference = new WeakReference(context);
            assemblyRef = new WeakReference(context.LoadedAssembly);

            Console.WriteLine($"Context loaded: {context.Assemblies.Count()}");
            foreach (var item in context.Assemblies)
            {
                Console.WriteLine($"Assembly: {item.Location}");
            }
            // Calling unload prevents the ALC from being GCed
            //context.Unload();
        }
    }

    public class TestLoadContext : AssemblyLoadContext
    {
        public TestLoadContext()
            : base(true)
        {
        }

        public Assembly LoadedAssembly { get; private set; }

        public void LoadTestAssembly(string path)
        {
            LoadedAssembly = LoadFromAssemblyPath(path);
            if (LoadedAssembly == null)
            {
                Console.WriteLine("Failed to load assembly");
            }
        }
    }
}
```

**Comment by janvorli** [comment]
Ok, let me try to repro this locally. @ccifra which version of .NET Core are you trying it with?

**Comment by ccifra** [comment]
I built against 3.1.201

**Comment by janvorli** [comment]
I've found the problem. It is the fact that you store the assembly in the TestLoadContext. That creates a circular dependency during shutdown and blocks the unload from completing. I'll need to add this case into the https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability.
If you remove that property and just return the Assembly from the LoadTestAssembly instead, your example works fine. Even with the content.Unload call.

Here is your sample modified that way for your convenience:
```c#
using System;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;

namespace TestALC
{
    class Program
    {
        static string AssemblyToLoad = @"F:\issues\35342\testassembly\bin\Debug\netcoreapp3.1\testassembly.dll";
        static WeakReference _testContextRef;
        static WeakReference _testAssemblyRef;

        static void Main(string[] args)
        {
            Console.WriteLine("Starting");
            DoLoadTest(AssemblyToLoad, out _testContextRef, out _testAssemblyRef);
            Console.WriteLine("Completed load test");
            while (_testContextRef.IsAlive)
            {
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
                GC.WaitForPendingFinalizers();
            }
            Console.WriteLine("ALC Has Been GCed!");
            foreach (var item in AssemblyLoadContext.Default.Assemblies)
            {
                Console.WriteLine($"Default Assembly: {item.Location}");
            }
            while (_testAssemblyRef.IsAlive)
            {
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
                GC.WaitForPendingFinalizers();
            }
            Console.WriteLine("Assembly Has Been GCed!");
            Console.WriteLine("Try to delete assembly now. Press Enter to Exit");
            Console.ReadLine();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void DoLoadTest(string assemblyName, out WeakReference alcReference, out WeakReference assemblyRef)
        {
            var context = new TestLoadContext();
            Assembly assembly = context.LoadTestAssembly(assemblyName);

            alcReference = new WeakReference(context);
            assemblyRef = new WeakReference(assembly);

            Console.WriteLine($"Context loaded: {context.Assemblies.Count()}");
            foreach (var item in context.Assemblies)
            {
                Console.WriteLine($"Assembly: {item.Location}");
            }
            // Calling unload prevents the ALC from being GCed
            //context.Unload();
        }
    }

    public class TestLoadContext : AssemblyLoadContext
    {
        public TestLoadContext()
            : base(true)
        {
        }

        public Assembly LoadTestAssembly(string path)
        {
            Assembly loadedAssembly = LoadFromAssemblyPath(path);
            if (loadedAssembly == null)
            {
                Console.WriteLine("Failed to load assembly");
            }

            return loadedAssembly;
        }
    }
}
```

Here are some internal details on what exactly happens.
When GC doesn't find any references to the TestLoadContext, the unload is initialized. The native runtime keeps a long weak GC handle to the TestLoadContext and now it adds a strong GC handle to extend the lifetime of the TestLoadContext until the latest stages of the unload. That final stage is triggered by LoaderAllocator associated with the TestLoadContext being GC collected. But the presence of the Assembly instance in the TestLoadContext prevents that, because each collectible Assembly has an internal reference to the LoaderAllocator. To summarize it, we have a chain of strong GC handle->TestLoadContext->Assembly->LoaderAllocator.

**Comment by ccifra** [comment]
I have verified that not storing the assembly or setting it to null before unload fixes the issue.
Thanks for the help.

**Comment by vitek-karas** [comment]
This seems to be resolved - if there's still an issue, feel free to reopen or open a new one.
