### ISSUE TITLE
Some Azure DevOps pipelines broken

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#35367]
Starting some pipelines is failing with `/eng/pipelines/common/templates/runtimes/build-test-job.yml: Could not find /eng/pipelines/templates/xplat-pipeline-job.yml in repository self hosted on https://github.com/ using commit 19d26fc6c30c70c476e0a37b75e8d7180e9bcd4b. GitHub reported the error, "Not Found"`

This appears to be due to https://github.com/dotnet/runtime/pull/34054

Pipelines include (but may not be limited to):

- runtime-coreclr jitstress2-jitstressregs
- runtime-coreclr jitstressregs
- runtime-coreclr jitstress

**Comment by BruceForstall** [comment]
@naricc @safern @jashook 
cc @dotnet/jit-contrib

**Comment by naricc** [comment]
Looking into it now. I had to reorganize some of these yml files and my guess is I missed updating some path.

**Comment by safern** [comment]
@BruceForstall I think this is fixed by: https://github.com/dotnet/runtime/pull/35311

**Comment by BruceForstall** [comment]
@safern that's related, but it won't fix these problems

**Comment by naricc** [comment]
It looks like runtimeFlavor is not set on some path, and expands to nothing, resulting in a invalid path when trying to find the appropriate xplat-pipeline-job.

**Comment by naricc** [comment]
I'm not sure how that is happening since everything seem to go through platform-matrix, which defines coreclr as the default...

**Comment by safern** [comment]
Oh you're correct I overlooked the issue. Following offline with @naricc who already reached out.

**Comment by BruceForstall** [comment]
Fixed with https://github.com/dotnet/runtime/pull/35377
