### ISSUE TITLE
Where can I find WindowsImpersonationContext in .net core 3.x?

### ISSUE THREAD

**Issue by wstaelens** [dotnet/runtime#35389]
I'm working on a project and I need to use WindowsImpersonationContext.
I have .net core 3.1 using Windows Desktop (WPF + GDI) features

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
```

so I'm bound to windows, but can't find this WindowsImpersonationContext. Which nuget should I add?

**Comment by Symbai** [comment]
https://github.com/dotnet/runtime/issues/30258

**Comment by jkotas** [comment]
`WindowsImpersonationContext` is not in .NET Core. It was an intentional decision since it has number of security problems. The discussion about this is at  https://github.com/dotnet/runtime/issues/20647#issuecomment-454860914

**Comment by jkotas** [comment]
The recommendation is to change the code to use `WindowsIdentity.RunImpersonated` method.
