### ISSUE TITLE
Do not use dotnetcli as intermediate storage for 2.1/2.2 builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#3538]
2.1 and 2.2 prodcon builds should not use dotnetcli* as intermediate storage.

* It's too easy to mess it up by doing multiple stabilized builds.
* Staging to dotnetcli and dotnetclichecksums are done by the final publish steps, so it's not needed.

**Comment by NikolaMilosavljevic** [comment]
Closing - not sure if this is still needed.
