### ISSUE TITLE
System.Text.Json doesn't deserialize IDictionary<string, string> if get only property

### ISSUE THREAD

**Issue by componentspace** [dotnet/runtime#35388]
In the following code Newtonsoft.Json correctly deserializes but System.Text.Json doesn't with the dictionary being empty. If the IDictionary<string, string> property has a setter, the deserialization works. However, I don't control the class that requires serialization/deserialization and it includes IDictionary<string, string> properties with getters only.

`
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Text.Json;

namespace TestConsoleApp
{
    class Test
    {
        public IDictionary<string, string> Items { get; } = new Dictionary<string, string>();
    }

    class Program
    {
        static void Main(string[] args)
        {
            var test = new Test();
            test.Items["a"] = "1";
            test.Items["b"] = "2";

            var json = System.Text.Json.JsonSerializer.Serialize(test);

            // Dictionary is empty.
            var test2 = System.Text.Json.JsonSerializer.Deserialize<Test>(json);

            // Correctly deserialized.
            var test3 = JsonConvert.DeserializeObject<Test>(json);
        }
    }
}

`

**Comment by Symbai** [comment]
https://github.com/dotnet/runtime/issues/30258
https://github.com/dotnet/runtime/issues/30688

**Comment by layomia** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/30258
