### ISSUE TITLE
.net framework 4+ and core are not working with some ntlm proxy servers

### ISSUE THREAD

**Issue by oguzkurumlu** [dotnet/runtime#35398]
Hi,

We are using HttpWebRequest on .net framework 4.7.2. We have a ntlm authentication on the proxy server and we are trying to connect it like bellow.
```
var httpWebRequest = (HttpWebRequest)HttpWebRequest.Create("https://www.microsoft.com");
var proxyCre = new NetworkCredential("XXX", "XXX");
var proxy = new WebProxy("*proxyaddress*", 8080);
proxy.Credentials = proxyCre;
httpWebRequest.Proxy = proxy;
httpWebRequest.GetResponse();
```
And versions of dotnet frameworks and results are different for proxy servers. There is no problem with digest and basic authentication but we are not able to connect some of them with ntlm authentication. 

Framework --- Mcaffee ------ FreeProxy --- CCProxy
3,5 ------------ OK ------------ OK ----------- OK
4 -------------- X -------------- X -------------	OK
4.7.2 ---------- X -------------- X -------------	OK
Core 3.1 ------ X -------------- X -------------	OK

linux curl and browsers(ie, chrome etc) can connect all of them.
I trace them with network monitor and i can see the difference on negotiation flags like bellow.

![image](https://user-images.githubusercontent.com/6850015/80205567-83bee000-8633-11ea-8425-d4db759e9d6f.png)

**Comment by davidsh** [comment]
Since you mention .NET Framework in addition to .NET Core, I'm assuming this is all using Windows OS? What version of Windows OS is being used?

**Comment by davidsh** [comment]
The other thing to keep in mind is that for many years, NTLM was a Microsoft proprietary protocol. Over time, more vendors wanted to interop with it. There were attempts by enthusiasts to reverse engineer the protocol. Some of those efforts resulted in third-party products (like these proxies) implementing a version of NTLM support.

Within the last several years, Microsoft officially began documenting these protocols as part of the Microsoft Open Specification program.  NTLM is officially documented now.

See: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/b38c36ed-2804-4868-a9ff-8dd3182128e4

Over time NTLM went through several protocol revisions. It is possible that the Mcaffee and FreeProxy products are not supporting all the official versions of the NTLM protocol.

>I trace them with network monitor and i can see the difference on negotiation flags like bellow.

These differences support my theory that perhaps NTLM v2 is not being supported properly.

**Comment by davidsh** [comment]
>linux curl and browsers(ie, chrome etc) can connect all of them.

I have a theory also why curl and some browsers work against these proxies. Many of the linux tools currently only support NTLM v1 and so they would work against these proxies. But newer Windows OS will attempt to connect with NTLM v2 first. And so some of these proxies won't work because of that.

**Comment by oguzkurumlu** [comment]
> Since you mention .NET Framework in addition to .NET Core, I'm assuming this is all using Windows OS? What version of Windows OS is being used?

Hi,

Thank you for your reply. 
Yes client and server are both windows. The client is windows 10 and the server is server 2019.

I tried it with powershell and the result is same.

Are you saying that the reason working on framework 3.5 and FreeProxy that's because they both created with older specification of NTLM?

**Comment by davidsh** [comment]
>Are you saying that the reason working on framework 3.5 and FreeProxy that's because they both created with older specification of NTLM?

@oguzkurumlu 

That is very likely.

There doesn't appear to be anything actionable in .NET Framework or .NET Core to help with this problem. I would recommend you follow up with the vendors for McAfee and FreeProxy to see if there are updated versions that support the newer NTLM protocols.
