### ISSUE TITLE
Flaky missing files in single FDD exe temp dir

### ISSUE THREAD

**Issue by dedale** [dotnet/runtime#35392]
Hello,

We have a .NET Core App 3.1 console application (AKA ysh) deployed as a single framework dependent executable. Based on our ELK metrics, this application is used hundreds of times a day.
But everyday, we have a few users facing failures like:

> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '<C:\Program Files\dotnet>'.
 
> -- Invoked apphost [version: 3.1.2, commit hash: ... main = { %AppData%\Local\Temp\ysh.exe compile debug }
> Redirecting errors to custom writer:
> The managed DLL bound to this executable is: 'Ard.Ying.Shell.dll'
> [...] --- Resolving hostpolicy.dll version from deps json

> An assemby specified in the application dependencies manifest (Ard.Ying.Shell.deps.json) was not found:
> Package: 'JetBrains.Annotations', version: '2019.1.3'
> path: 'lib/netstandard2.0/JetBrains.Annotations.dll'

We currently advise these users to remove all %TEMP%/.net/ysh directories.

Unfortunately, even if I am the top user of this application, I am unable to reproduce the problem under normal conditions (of course, removing files in temp folder would trigger the failures).

Thanks in advance for your help.
Vianney

**Comment by janvorli** [comment]
cc: @vitek-karas

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/3778

The bug will be fixed in this month's servicing release.
In the meantime, as a workaround, you can set the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable to a non-temp directory when running the app, so that the extracted files are not cleaned up.
