### ISSUE TITLE
ICorDebug work for pinned object heap

### ISSUE THREAD

**Issue by davmason** [dotnet/runtime#35396]
Overview of all pinned object heap diagnostics [here](#35561)

I did a quick pass over the ICorDebug code to see what needs some updates to be aware of the new pinned object heap.

CorDebugGenerationTypes needs another entry in the enum

These apis use dac methods that are not aware of the new heap:
- HRESULT EnumerateHeap([out] ICorDebugHeapEnum **ppObjects);
- HRESULT EnumerateHeapRegions([out] ICorDebugHeapSegmentEnum **ppRegions);

Additionally,  gcinterface.dac.h and g_gcDacGlobals need updating to reflect the new heap as well.

**Comment by noahfalk** [comment]
> CorDebugGenerationTypes needs another entry in the enum

As long as VS gives us the green light it sounds good to me.

**Comment by davmason** [comment]
@gregg-miskelly @caslan do you have any thoughts on updating ICorDebug so that EnumerateHeap and EnumerateHeapRegions return objects off the new pinned object heap? Are there any compatibility concerns there?

**Comment by gregg-miskelly** [comment]
From what I can tell, I don't see any problems with adding a new enum entry. I only see one spot in our code that uses that enum value, and it will be fine with a new value.

**Comment by davmason** [comment]
Fixed with #39139  and #38146
