### ISSUE TITLE
Make legacy pre-generic collection types implement IEnumerable<T>

### ISSUE THREAD

**Issue by ekolis** [dotnet/runtime#35417]
There are certain collection types in the framework that were added prior to the addition of generic types in C# 2.0, such as `System.Data.DataRowCollection`. It would be very helpful to convert these to implement the appropriate `IEnumerable<T>` type, e.g. `IEnumerable<DataRow>` for the preceding class. Right now in order to treat these collections as `IEnumerable<T>` you have to call the `Cast<T>` extension method on them.

**Comment by danmosemsft** [comment]
@ekolis which collections specifically are you asking for? Is it just `DataRowCollection`? I doubt we would make a pass through adding it to every strongly typed custom collection. But if there is a type or types that are still heavily used and their entries have a well defined type it seems potentially reasonable

**Comment by ekolis** [comment]
@danmosemsft No, not just `DataRowCollection`. I don't have a particular list of collection types in mind, however; this just occurred to me as I was casting elements of a `DataRowCollection`.

**Comment by danmosemsft** [comment]
Fair enough. Can you please reformat your top post per https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md ?

**Comment by hughbe** [comment]
Linking https://github.com/dotnet/winforms/issues/2644 - there may be some breaking changes associated, see that PR

**Comment by Joe4evr** [comment]
@ekolis If you're still going to rewrite your first post, you should probably change your title as well to single out `DataRowCollection`. I really don't see the other non-generic collections getting updated when they're on the shortlist of Better Obsoletion targets.

**Comment by weltkante** [comment]
As far as WinForms is concerned we won't be able to make pre-generic collection types `IEnumerable<T>`. I made a prototype and you quickly run into issues with the base class design that are impossible to solve in a binary compatible way. The desire is that you can run .NET Core 3.0 builds on .NET Core 5.0 so you need binary compatibility.

Lessons learned from WinForms why it doesn't work adding the generic interface:
- If the class was designed for extensibility then subclasses will only be extending the non-generic API, adding the generic interface requires different `Add` and `GetEnumerator` APIs which need to be implemented by subclasses.
- If the nongeneric class hierarchy already has base classes then its usually impossible to make those generic in a sensible way, the way virtual methods are used is incompatible with implementing the generic interface sensibly.
- Adding the interfaces will conflict with the `GetEnumerator` API if it was already public, so you have to make the generic one an explicit interface implementation, but that means roslyn won't pick up the type in `foreach` loops.

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to implement.
