### ISSUE TITLE
Assertion failed 'rhs != UninitVal()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#35413]
Linux arm JitStress=1 or 2, tiered and non-tiered

https://dev.azure.com/dnceng/public/_build/results?buildId=614765&view=ms.vss-test-web.build-test-results-tab&runId=19293616&resultId=109469&paneView=debug

`
\nAssert failure(PID 3001 [0x00000bb9], Thread: 3001 [0x0bb9]): Assertion failed 'rhs != UninitVal()' in 'BB:Method1(byref,byref,byref,AA6[SByte,Byte,UInt32,UInt32,Int64,Boolean],byref,int):this' during 'Update flow graph opt pass' (IL size 510)\n\n File: /__w/1/s/src/coreclr/src/jit/bitsetasshortlong.h Line: 91\n Image: /root/helix/work/correlation/corerun\n\n/root/helix/work/workitem/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh: line 312: 3001 Aborted $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"\n\nReturn code: 1\nRaw output file: /root/helix/work/workitem/JIT/Regression/Reports/JIT.Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.output.txt\nRaw output:\nBEGIN EXECUTION\n/root/helix/work/correlation/corerun b539509.dll ''\nTesting AA::Method1\nException handled: System.InvalidCastException: Unable to cast object of type 'BB' to type 'AA6[System.SByte,System.Byte,System.UInt32,System.UInt32,System.Int64,System.Boolean]'.\n at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 595\nTesting AA::Static1\nException handled: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.\n at AA6.Static1(TF param1) in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 135\n at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 606\nTesting AA::Static2\nTesting AA::Static3\nException handled: System.NullReferenceException: Object reference not set to an instance of an object.\n at AA6.Static3(TestEnum param1, Int16 param2) in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 349\n at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 628\nTesting AA::Static4\nTesting AA::Static5\nException handled: System.NullReferenceException: Object reference not set to an instance of an object.\n at AA`6.Static5(TE& param1, Char[,,,][]& param2, Array param3, UInt64[,,,,]& param4, Int64[,][][][][,,,]& param5) in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 443\n at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 648\nTesting BB::Method1\nWriting minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3001.dmp\nWritten 188223488 bytes (45953 pages) to core file\nExpected: 100\nActual: 134\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/root/helix/work/correlation\n> /root/helix/work/workitem/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh\nExpected: True\nActual: False
`

Test:
```
JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
```

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Linux arm regression

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr jitstress 20200424.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=616927&view=ms.vss-test-web.build-test-results-tab&runId=19336334&resultId=107091&paneView=debug)

failed test: JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh


Error message
~~~
Assert failure(PID 8179 [0x00001ff3], Thread: 8179 [0x1ff3]): Assertion failed 'rhs != UninitVal()' in 'BB:Method1(byref,byref,byref,AA6[SByte,Byte,UInt32,UInt32,Int64,Boolean],byref,int):this' during 'Update flow graph opt pass' (IL size 510)

 File: /__w/1/s/src/coreclr/src/jit/bitsetasshortlong.h Line: 91
 Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh: line 312: 8179 Aborted $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"

Return code: 1
Raw output file: /root/helix/work/workitem/JIT/Regression/Reports/JIT.Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun b539509.dll ''
Testing AA::Method1
Exception handled: System.InvalidCastException: Unable to cast object of type 'BB' to type 'AA6[System.SByte,System.Byte,System.UInt32,System.UInt32,System.Int64,System.Boolean]'.
 at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 595
Testing AA::Static1
Exception handled: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at AA6.Static1(TF param1) in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 135
 at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 606
Testing AA::Static2
Testing AA::Static3
Exception handled: System.NullReferenceException: Object reference not set to an instance of an object.
 at AA6.Static3(TestEnum param1, Int16 param2) in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 349
 at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 628
Testing AA::Static4
Testing AA::Static5
Exception handled: System.NullReferenceException: Object reference not set to an instance of an object.
 at AA`6.Static5(TE& param1, Char[,,,][]& param2, Array param3, UInt64[,,,,]& param4, Int64[,][][][][,,,]& param5) in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 443
 at App.Main() in /__w/1/s/src/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509.cs:line 648
Testing BB::Method1
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.8179.dmp
Written 188116992 bytes (45927 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
Expected: True
Actual: False


Stack trace
   at JIT_Regression._VS_ia64_JIT_V2_0_RTM_b539509_b539509_b539509_._VS_ia64_JIT_V2_0_RTM_b539509_b539509_b539509_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs:line 138559
~~~

**Comment by sandreenko** [comment]
I have arm32 Linux machine setup after my previous fix, I can take a look.

**Comment by sandreenko** [comment]
The regression was introduced by https://github.com/dotnet/runtime/pull/34837, it could be reproduced on x64 windows with altjit.
PTAL @briansull.

**Comment by briansull** [comment]
Investigating this issue
