### ISSUE TITLE
ArgumentNullException in Json serialization

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#35422]
In [PowerShell repo](https://github.com/PowerShell/PowerShell/pull/11198) we get an exception for null parameter:
```
PS > $null | ConvertTo-Json -Compress
ConvertTo-Json: Value cannot be null. (Parameter 'type')
PS > Get-Error

Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'type')
    ParamName  : type
    TargetSite :
        Name          : VerifyValueAndType
        DeclaringType : System.Text.Json.JsonSerializer
        MemberType    : Method
        Module        : System.Text.Json.dll
    StackTrace :
   at System.Text.Json.JsonSerializer.VerifyValueAndType(Object value, Type type)
   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertToJson2(Object objectToProcess, ConvertToJsonContext& context) in
 C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\Microsoft.PowerShell.Commands.Utility\commands\utility\WebCmdlet\J
sonObject.cs:line 538
   at Microsoft.PowerShell.Commands.ConvertToJsonCommand2.EndProcessing() in C:\Users\1\Documents\GitHub\iSazonov\Power
Shell\src\Microsoft.PowerShell.Commands.Utility\commands\utility\WebCmdlet\ConvertToJsonCommand.cs:line 252
   at System.Management.Automation.Cmdlet.DoEndProcessing() in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\Syst
em.Management.Automation\engine\cmdlet.cs:line 187
   at System.Management.Automation.CommandProcessorBase.Complete() in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\s
rc\System.Management.Automation\engine\CommandProcessorBase.cs:line 590
    Source     : System.Text.Json
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [ConvertTo-Json], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShell.Commands.ConvertToJsonCommand2
InvocationInfo        :
    MyCommand        : ConvertTo-Json
    ScriptLineNumber : 1
    OffsetInLine     : 9
    HistoryId        : 1
    Line             : $null | ConvertTo-Json -Compress
    PositionMessage  : At line:1 char:9
                       + $null | ConvertTo-Json -Compress
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : ConvertTo-Json
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```
I tried to directly reference System.Text.Json 5.0.0-preview.2.20160.6 but get the same exception.
I wonder to see  JsonSerializer.VerifyValueAndType() because it was removed it in https://github.com/dotnet/runtime/pull/2259

Now we moved to 5.0 Preview3 with the same error.

**Comment by layomia** [comment]
@iSazonov it is indeed odd that you are seeing `VerifyValueAndType` in the stacktrace using a preview 3 build. Can you share a simple repro of the issue? Is any caller of the serializer passing in `null` as an argument for the `inputType` to any of the `Serialize` method overloads?

**Comment by iSazonov** [comment]
Today we moved to 5.0 Preview4 in PowerShell repo and I will re-check.

>  Is any caller of the serializer passing in null as an argument for the inputType to any of the Serialize method overloads?

Yes, we are trying to serialize null. It worked before but not in 5.0.

**Comment by iSazonov** [comment]
@layomia After we update to latest .Net 5.0 preview I don't see `VerifyValueAndType` but exception present.
```powershell
Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'inputType')
    ParamName  : inputType
    TargetSite :
        Name          : Serialize
        DeclaringType : System.Text.Json.JsonSerializer
        MemberType    : Method
        Module        : System.Text.Json.dll
    StackTrace :
   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerOptions options)
```
PowerShell 6.0 and 7.0 use NewtonSoft Json.Net and follow works:
```powershell
> $null | ConvertTo-Json -Compress
null
```
But after we move to .Net 5.0 Json API we get the exception.
It is _single_ regression we see currently (.Net team great work!).

`JsonSerializer.Serialize()` processes null-s well in general but does not allow null-s in its signature (it explicitly check and throw on inputType == null).

Expectation is that follow works:
```c#
JsonSerializer.Serialize(null, null, null)    // returns "null"
JsonSerializer.Serialize(null, typeof(string), null)    // returns "null"
```

**Comment by layomia** [comment]
> It is single regression we see currently (.Net team great work!).

Glad to hear! Thanks.

> Expectation is that follow works:
> 
> ```cs
> JsonSerializer.Serialize(null, null, null)    // returns "null"
> JsonSerializer.Serialize(null, typeof(string), null)    // returns "null"
> ```

So the expectation is that when the instance to serialize is `null`, passing `null` as the input type doesn't cause the `ArgumentNullException` to be thrown.

Why pass a `null` `inputType` in the first place? Which scenarios require this?

**Comment by iSazonov** [comment]
> So the expectation is that when the instance to serialize is null, passing null as the input type doesn't cause the ArgumentNullException to be thrown.

Yes. 
I look only from PowerShell side and I do not know if there are problems for other scenarios/applications.
I could do a check for null before calling this method, but my fear is that there may also be such limitations inside the method.

> Why pass a null inputType in the first place? Which scenarios require this?

PowerShell scenario `$variable | ConvertTo-Json -Compress` that is "get an input object and convert to JSON" - so we should get the target type at runtime. This is implemented as:
```c#
JsonSerializer.Serialize(objectToProcess, objectToProcess?.GetType(), options);
```
Again, my request comes from only the scenario and I could create a workaround (use `typeof(string)` if null or address the scenario before the call as mentioned above) if MSFT team confirm that the API design is ideal.

**Comment by layomia** [comment]
> if MSFT team confirm that the API design is ideal.

Yes, we consider passing a `null` input type invalid, and the [API docs](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer.serialize?view=netcore-3.1) call this out.

> I could do a check for null before calling this method

Doing a null check here is probably the best option, as the serializer will simply write `"null"` if the root object is `null` anyway. Looks like you're using a string-returning overload, so you could just write the null by hand.

I'll go ahead and close this issue, since it is not actionable as is. Please feel free to re-open if you still face issues.

**Comment by iSazonov** [comment]
@layomia Thanks! I will implement the way. I hope it will be in next PowerShell Preview and we will get more feedback.

**Comment by steveharter** [comment]
@layomia I believe we should we call the out the "null input type semantics" as a breaking change in 5.0. We didn't throw previously, now we throw.

**Comment by danmosemsft** [comment]
@layomia since ASP.NET had to react to that, do you think it is worth a [breaking change note](https://github.com/dotnet/docs/issues/new?assignees=&labels=&template=dotnet-breaking-change.md&title=)? so it appears in https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#core-net-libraries

**Comment by layomia** [comment]
@danmosemsft - yes, it is a breaking change and has been shown to be significant. The change was made in https://github.com/dotnet/runtime/pull/32669/files. Will file a breaking change note.

**Comment by danmosemsft** [comment]
thanks!

**Comment by layomia** [comment]
Update: a breaking change doc was already filed for this: dotnet/docs#21376, https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#jsonserializerserialize-throws-argumentnullexception-when-type-parameter-is-null.
