### ISSUE TITLE
Linux CryptographicException on ImportEncryptedPkcs8PrivateKey for RSA and ECDsa

### ISSUE THREAD

**Issue by whyvra** [dotnet/runtime#35428]
While working with asymmetric keys, I found an issue on Linux calling `ImportEncryptedPkcs8PrivateKey` on RSA and ECDsa for encrypted keys with an iteration count over 600000.

```
System.Security.Cryptography.CryptographicException: The EncryptedPrivateKeyInfo structure was decoded but was not successfully interpreted, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: Value was invalid.
   at System.Security.Cryptography.PasswordBasedEncryption.NormalizeIterationCount(Int32 iterationCount)
   at System.Security.Cryptography.PasswordBasedEncryption.OpenPbkdf2(ReadOnlySpan`1 password, Nullable`1 parameters, Nullable`1& requestedKeyLength)
...
```

The issue seems related to the internal `PasswordBasedEncryption` class in `System.Security.Cryptography` where you can clearly see: 

```
namespace System.Security.Cryptography
{
    internal static class PasswordBasedEncryption
    {
        internal const int IterationLimit = 600000;
```

This issue only occurs on Linux. I have no issues importing an encrypted key with an iteration count of a million on Windows.

Could the limit be increased/removed for Linux so that the behavior is similar to what happens in Windows?

#### Steps to reproduce

1. `dotnet new console -n Crypto.Test`
2. Replace `Program.cs` with the following:
```
using System.Security.Cryptography;

namespace Crypto.Test
{
    public class Program
    {
        public static void Main()
        {
            var password = "Password1".ToCharArray();
            var pbe = new PbeParameters(PbeEncryptionAlgorithm.Aes256Cbc, HashAlgorithmName.SHA256, 1000000);

            var ec = ECDsa.Create();
            var encrypted = ec.ExportEncryptedPkcs8PrivateKey(password, pbe);

            var decrypted = ECDsa.Create();
            decrypted.ImportEncryptedPkcs8PrivateKey(password, encrypted, out _); // Crash on Linux
        }
    }
}
```
3. Run the code. Works on Windows and crashes on Linux.

#### dotnet ---info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.103
 Commit:    6f74c4a1dd

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.103/

Host (useful for support):
  Version: 3.1.3
  Commit:  ed88943d24

.NET Core SDKs installed:
  3.1.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by bartonjs** [comment]
I feel like I picked that number because it matched Windows.  How far are you seeing that you can go with Windows before it fails?  Maybe I picked a value from an older OS.

**Comment by whyvra** [comment]
I tried with 10 millions on a Windows 10 Desktop and it worked.  It's definitely not fast, but no crashes. I just started it with `int.MaxValue` and it's working away. That would probably take forever to complete and it's probably not that realistic. Not sure if an older Windows environment would have more restrictions.

I can definitely do a million with OpenSSL too. I was trying to find out if they had a limit, but didn't find anything.

Seems like NIST and OWASP recommend at least 100,000 rounds for high-security environments so maybe the limit you have in place isn't that bad. I'd still like to see a million rounds for Linux, that should be nothing for a server.

**Comment by whyvra** [comment]
Would like to point out that generating a key and exporting it with `ExportEncryptedPkcs8PrivateKey` and a million rounds works on Linux. The decryption really seems to be the issue.

**Comment by vcsjones** [comment]
Windows has a limit of 600,000 when the algorithm is 3DES. This will fail:

```csharp
var pbe = new PbeParameters(
    PbeEncryptionAlgorithm.TripleDes3KeyPkcs12,
    HashAlgorithmName.SHA1,
    600_001);
using RSA rsa = RSA.Create();
rsa.ExportEncryptedPkcs8PrivateKey("password", pbe);
```

So that's likely where the 600,000 limit is coming from. With AES, Windows doesn't seem to impose a meaningful limit. It ran fine with 100 million.

@bartonjs perhaps we remove the limit for AES PBE algorithms?

**Comment by vcsjones** [comment]
> perhaps we remove the limit for AES PBE algorithms?

Maybe not, there is a little more nuance with 600,000 iterations. If you use greater than 600,000 iterations with `Pkcs12Builder`, Windows will refuse to import the resulting PFX, regardless of the algorithm.

So if you are using `PbeParameters` with `AddShroudedKey`, 600,001 iterations is not going to create a usable PFX on Windows.

**Comment by vcsjones** [comment]
Hm, > 600,000 iterations works with `Pkcs12Builder.AddShroudedKey` but only if, the algorithm AES, and `SealWithMac` is <= 600,000 iterations.

How confusing.

It still seems reasonable to lift the iteration limit on `PbeParameters` with AES - it's probably too late to add one to `SealWithMac`.
