### ISSUE TITLE
Some reference assemblies do not contain the [ReferenceAssembly] attribute

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#35449]
`C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1` is a directory containing reference assemblies and their documentation. Reference assemblies just contain type forwards and are marked with the `System.Runtime.CompilerServices.ReferenceAssemblyAttribute`, however, not all in the directory are marked. Specifically, the following assemblies do not:

```
Microsoft.VisualBasic.dll
mscorlib.dll
netstandard.dll
System.ComponentModel.DataAnnotations.dll
System.Configuration.dll
System.Core.dll
System.Data.dll
System.dll
System.Drawing.dll
System.IO.Compression.FileSystem.dll
System.Net.dll
System.Numerics.dll
System.Runtime.Serialization.dll
System.Security.dll
System.ServiceModel.Web.dll
System.ServiceProcess.dll
System.Transactions.dll
System.Web.dll
System.Windows.dll
System.Xml.dll
System.Xml.Linq.dll
System.Xml.Serialization.dll
WindowsBase.dll
```

Is that intentional? All these assemblies just have one type declared (`<Module>`), which makes me believe it is not.

**Comment by jkotas** [comment]
cc @ericstj

**Comment by ericstj** [comment]
Yes, it is intentional.  For assemblies which are full facades we don't set ReferenceAssembly.  See https://github.com/dotnet/buildtools/pull/1663
Since there is no harm in these being loaded for execution we don't block it.  Not blocking helps in cases where some old design-time tooling still loads references for execution.

**Comment by teo-tsirpanis** [comment]
I see. So, only the assemblies with that particular attribute are prohibited to be loaded for execution?

**Comment by ericstj** [comment]
ReferenceAssemblies are identified by both the ReferenceAssemblyAttribute and AssemblyFlags of 0x70.  https://github.com/dotnet/runtime/blob/6d64040a3a577e097e8d06ef72c10f700a17bf9c/eng/referenceAssemblies.props#L19-L22

The purpose of these is to prevent them from being loaded for execution.  IIRC CLR used AssemblyFlags and CoreCLR honors the ReferenceAssemblyAttribute .  This, of course, isn't the only thing that prevents an assembly from being loaded for execution (arch mismatch, bad metadata, etc).
