### ISSUE TITLE
System.Text.Json and Xamarin

### ISSUE THREAD

**Issue by vgdh** [dotnet/runtime#35450]
When i add System.Text.Json to a new clean xamarin forms project.
Visual studio show in designer mode MockView.

i use latest new clean install version of VisualStudio.
<img width="98" alt="devenv_4lDGGGpwXD" src="https://user-images.githubusercontent.com/15322782/80279750-f5bd2500-8718-11ea-8551-e62c36d0d6d8.png">
<img width="347" alt="devenv_6PEv2JRUBC" src="https://user-images.githubusercontent.com/15322782/80279755-f6ee5200-8718-11ea-9d41-87c5acb817c8.png">

**Comment by layomia** [comment]
We have known issues with running in Xamarin projects. Please see https://github.com/dotnet/runtime/issues/31326 which tracks this, and add more details about the specific error you are seeing. cc @steveharter
