### ISSUE TITLE
build.cmd command not working for dotnet runtime repo

### ISSUE THREAD

**Issue by himanshu8088** [dotnet/runtime#35458]
Hi,

I just cloned the repo runtime (git@github.com:dotnet/runtime.git) and imported .vsconfig file in VisualStudioInstaller and downloaded all pre-requisite like Python, CMake, and Git. But getting below error on executing build.cmd in the prompt window. 

![image](https://user-images.githubusercontent.com/29939910/80284973-89095100-873f-11ea-8565-262329b4de87.png)

But runtime/eng/build.ps1 is working fine when opened directly, this is failing with build.cmd script only

**Comment by stephentoub** [comment]
Can you try cloning to a path that doesn't include spaces? I'm guessing there's a quoting issue in the build script.

**Comment by himanshu8088** [comment]
> Can you try cloning to a path that doesn't include spaces? I'm guessing there's a quoting issue in the build script.

@stephentoub this worked for me. Thanks for responding so fast. ;)

**Comment by ViktorHofer** [comment]
Probably happening because of the path in the command not being surrounded by quotes: https://github.com/dotnet/runtime/blob/master/build.cmd#L7. @himanshu8088 interested in submitting a PR to fix this?

**Comment by himanshu8088** [comment]
> Probably happening because of the path in the command not being surrounded by quotes: https://github.com/dotnet/runtime/blob/master/build.cmd#L7. @himanshu8088 interested in submitting a PR to fix this?

@ViktorHofer Yes, I can work in it, please give a invite of collaborator to me. Thanks🙂

**Comment by himanshu8088** [comment]
> > Probably happening because of the path in the command not being surrounded by quotes: https://github.com/dotnet/runtime/blob/master/build.cmd#L7. @himanshu8088 interested in submitting a PR to fix this?
> 
> @ViktorHofer Yes, I can work in it, please give an invite of collaborator to me. Thanks🙂

I have opened a [PR](https://github.com/dotnet/runtime/pull/35554) for the issue fix.

**Comment by himanshu8088** [comment]
> > > Probably happening because of the path in the command not being surrounded by quotes: https://github.com/dotnet/runtime/blob/master/build.cmd#L7. @himanshu8088 interested in submitting a PR to fix this?
> > 
> > 
> > @ViktorHofer Yes, I can work in it, please give an invite of collaborator to me. Thanks🙂
> 
> I have opened a [PR](https://github.com/dotnet/runtime/pull/35554) for the issue fix.

Two CI checks failed(unit test failed because it is unable to restore NuGet package from the host NuGet package manager) when I did a quick check, it seems there is already a blocking issue with `System.Net.Http` library, as per the last commit master branch conversation - [Issue PR #35498](https://github.com/dotnet/runtime/pull/35498).
