### ISSUE TITLE
TFM should be dotnet5.0 instead of net5.0

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#35469]
We see TFM for .NET 5.0 projects has been updated from `netcoreapp5.0` to `.net5.0` in preview 3 release but we think TFM `dotnet5.0` would be more readable and meaningful which is neither too long nor too short.

.NET Team can consider it.

Thank you.

**Comment by huoyaoyuan** [comment]
This may be ambiguous with deprecated `dotnet50` TFM, which is used by the early development of ASP.NET Core. See https://docs.microsoft.com/en-us/dotnet/standard/frameworks#deprecated-target-frameworks

**Comment by jkotas** [comment]
This was considered and rejected:

https://github.com/dotnet/designs/pull/92#issuecomment-591217044
https://github.com/dotnet/designs/pull/92#discussion_r379854694

cc @terrajobst

**Comment by TanvirArjel** [comment]
@jkotas and @huoyaoyuan  Thank you so much for the provided links. But I am still not convinced as I have checked the whole list of deprecated TFMs and I found none of them is conflicting `dotnet5.0` and so on.

**Comment by jpactor** [comment]
> @jkotas and @huoyaoyuan Thank you so much for the provided links. But I am still not convinced as I have checked the whole list of deprecated TFMs and I found none of them is conflicting `dotnet5.0` and so on.

"dotnet5.0" doesn't directly conflict, but there was a TFM, now deprecated, which was "dotnet50". This could lead to confusion as people may leave off the "."
