### ISSUE TITLE
Generate compressed archives (zip/tar.gz) for framework packs

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3546]
Efforts have been focused on nupkg and installers, but zip/tar.gz files are used in some situations. These should be included in the new packaging infrastructure for framework packs.

https://github.com/dotnet/core-setup/pull/5816 adds a zip for the WindowsDesktop shared framework, but it is specific to that scenario and needs to be cleaned up and more generic.

**Comment by NikolaMilosavljevic** [comment]
Obsolete - implemented with SharedFX infra refactoring.
