### ISSUE TITLE
Question: .net core and wifi direct?

### ISSUE THREAD

**Issue by psantosl** [dotnet/runtime#35479]
Is it possible to use wifidirect from a .net core console application? Any hints on how to make it?

**Comment by wfurt** [comment]
That is generally function of your os e.g. drivers & routing. There is nothing AFAIK in .NET preventing the use, as long as you get IP configured.  There is no API to configure interfaces - wirelesss or wired or to manipulate wireless setting.

**Comment by psantosl** [comment]
I mean something like this: https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifidirect.wifidirectdevice

It was a pain to use it from a .net console application :
https://github.com/psantosl/PeerFinderConsole

So I wanted to know if it is any better in .net core

See what I mean? It was meant to be used by UWP apps, not console

**Comment by davidsh** [comment]
>See what I mean? It was meant to be used by UWP apps, not console

.NET 5 will have improvements to interop with WinRT APIs. Many of the Windows WinRT API (Windows.* namespaces) can be used by both UWP apps as well as console apps. The documentation for the WinRT API will say whether or not it can be used in Windows console apps as well as Windows UWP apps.

The current tooling in Visual Studio sometimes make that difficult to interop currently. But improvements are forthcoming.

**Comment by psantosl** [comment]
Awesome! Thank you!

Anything I can read? Or should I just wait?

**Comment by karelz** [comment]
Closing as answered.
@AaronRobinsonMSFT can you comment on more WinRT interop capabilities in .NET 5? Do we have more insights what are the plans.

**Comment by AaronRobinsonMSFT** [comment]
@psantosl The announcement and future plans are documented at https://github.com/dotnet/runtime/issues/35318.
