### ISSUE TITLE
Is there a reason ChannelReader.ReadAllAsync is not available in netstandard2.1 yet?

### ISSUE THREAD

**Issue by iskandersierra** [dotnet/runtime#35481]
area-System.Threading.Channels
@tarekgh @stephentoub 
I noticed that ReadAllAsync is only available in netcoreapp3.* but not in netstandard2.1. 
I don't know if there is a reason for this to be still an issue.

**Comment by iskandersierra** [comment]
area-System.Threading.Channels

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/817. Thanks.
