### ISSUE TITLE
EventLog access is not supported on this platform (Windows)

### ISSUE THREAD

**Issue by andv15** [dotnet/runtime#35496]
Exception: 'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.PlatformNotSupportedException: EventLog access is not supported on this platform.
   at System.Diagnostics.EventLog.SourceExists(String source)

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="3.1.3" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="4.7.0" />
  </ItemGroup>

**Comment by jaymin93** [comment]
You need to install windows compatibility pack first to make it work with .net core it’s available on NuGet , I checked it working fine able to write to event log

**Comment by andv15** [comment]
System.Diagnostics.EventLog.SourceExists is called from a .net standard 2.0 library referenced by a .net framework 4.7.2 project.

**Comment by jaymin93** [comment]
Then you might need to install this from the where it is being called

**Comment by tommcdon** [comment]
@sywhang is this ours?

**Comment by Anipik** [comment]
@andv15 system.Diagnostics.EventLog is not supported on netstandard2.0 https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj#L11
