### ISSUE TITLE
Regex fails on zero-or-more match of character from outside the BMP

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/runtime#35499]
BMP = Unicode Basic Multilingual Plane

**Repro:**
`Regex.IsMatch("", "🐲*")`

**Expected:**
true - there are 0 or more matches of the specified character

**Actual:**
false

When given a matching input, the evaluation is correct:
`Regex.IsMatch("🐲", "🐲*") == true`

Side note: for this to work in ECMAScript, the Regexp object must use the u flag (for Unicode) to handle the pattern as a sequence of code points ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp)).  I can't find an equivalent in .NET.

**Comment by stephentoub** [comment]
Regex doesn't support surrogates today. It sees the pattern you provided as a single character to match followed by a star loop around a second character. It then doesn't match an empty string because an empty string doesn't match the first character.
