### ISSUE TITLE
ConstructorInfo ought to have a CreateDelegate method, just as MethodInfo has.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#355]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/368713/constructorinfo-ought-to-have-a-createdelegate-met.html)._

---
<p>Given ConstructorInfo has an Invoke method, why not have a CreateDelegate method, so I can invoke it in a type-safe manner, without boxing and object[] allocation?</p>

---
#### Fiona Niu[MSFT] on 10/28/2018, 11:03 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by GrabYourPitchforks** [comment]
A constructor on a type is really a void-returning instance method, but presumably if you want to wrap a constructor within a delegate you actually wanted to _instantiate_ the object, returning the new object instance. This isn't something that can be accomplished with a single method invocation. See https://github.com/dotnet/runtime/pull/32520 for an alternative proposal which attempts to provide a usable API for this scenario.

See also: https://github.com/dotnet/runtime/issues/23716, https://github.com/dotnet/runtime/issues/31895
