### ISSUE TITLE
Expose way to calculate heap memory usage of an object

### ISSUE THREAD

**Issue by wanton7** [dotnet/runtime#35511]
Currently there is no way to calculate how much memory object has allocated. 

I noticed that there is internal method here https://github.com/dotnet/runtime/blob/b41296a37f4bfead66db234e9d14b81fff302567/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs#L196

that comes quite close but it's not recursive and subtracting those IntPtrs makes its calculations little bit off. It would really helpful for setting memory limits for things like IMemoryCache and it's size support if there was a method that would allow you to calculate object memory usage that would have optional support to calculate memory usage recursively.

**Comment by stephentoub** [comment]
Thanks.  Dup of https://github.com/dotnet/runtime/issues/24200.
