### ISSUE TITLE
Make unboxing MethodDescs local to CorInfoImpl

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#35531]
https://github.com/dotnet/runtime/pull/34842#issuecomment-620151488

We should make it so that the unboxing MethodDesc don't enter the `NodeFactory` system. `CorInfoImpl` needs to unwrap the unboxing thunk into the normal MethodDesc and a bool specifying whether this is an unboxing stub. Leaking this into NodeFactory could be a source of annoying bugs since the system is not prepared to see these.

One fix fix that:
* We can undo a part of #35504 where I unshared the factory so that this doesn't leak anywhere else (it can be moved back to Common)
* We should make the unboxing MethodDesc a private nested class of CorInfoImpl to prevent this happening in the future.

**Comment by mangod9** [comment]
Hey @MichalStrehovsky,  is this issue specific to cg2?

**Comment by MichalStrehovsky** [comment]
Yep, specific to crossgen2. See https://github.com/dotnet/runtime/pull/34842#issuecomment-620151488.
