### ISSUE TITLE
API suggestion: RuntimeFeature.IsComActivationSupported

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#35539]
Related: https://github.com/dotnet/runtime/issues/34328

```cs
namespace System.Runtime.CompilerServices
{
    public static partial class RuntimeFeature
    {
        public static bool IsComActivationSupported { get; }
    }
}
```

This API answers the question "Does the current environment support [`Type.GetTypeFromCLSID`](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettypefromclsid) (or `CoCreateInstance` in general)?" This API returning _true_ doesn't guarantee that a particular COM instantiation will succeed. The API returning _false_ means that COM activation APIs will throw PNSE so the caller shouldn't bother.

**Comment by jkotas** [comment]
Note that there many other parts of COM not implemented by Mono. COM activation is just a small part of it.

https://github.com/dotnet/runtime/issues/35079 is about adding test project property (e.g. `PlatformDetection.IsComSupported`) to disable tests that use COM against.

I do not see the value of public API(s) for this. Catching the PlatformNotSupported exception should be sufficient for the few situations that need it.

**Comment by GrabYourPitchforks** [comment]
I have in mind applications that might attempt to instantiate plugins via registered COM interfaces. The idea is that they could perform feature detection to avoid using a COM based plugin model at all if they know all the calls will fail.

Your suggestion instead is that these apps should attempt COM instantiation anyway, treating the exception as "feature unavailable" rather than as a configuration error that requires user attention?

**Comment by jkotas** [comment]
Yes, I think catching `PlatformNotSupportedException` should work just fine for this case.

**Comment by AaronRobinsonMSFT** [comment]
Suggestion for catching `PlatformNotSupportedException` is the recommendation here. There is a thought about adding something higher level [`RuntimeFeature.IsComSupported`](https://github.com/dotnet/runtime/issues/36659#issuecomment-630605468). Will close this specific issue in lieu of that link-ability issue.
