### ISSUE TITLE
Jit: move runtime lookup expansion to lower

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#35551]
This is a follow-up to #341.

The jit currently expands runtime lookups in the importer (`impRuntimeLookupToTree`). The optimal expansion requires introducing control flow either via `GT_QMARK` or via `IndirectCallTransformer`.

The tail call via helpers mechanism introduced in #341 also needs to insert runtime lookups. The expansion of tail calls via helpers happens in morph and it's impossible to change control flow there the way it's done in the importer. Because of that the runtime lookups introduced in morph use the slower helper call expansion:
https://github.com/dotnet/runtime/blob/e1ffadd6521b29db350e701b11d78a286ecd783a/src/coreclr/src/jit/morph.cpp#L8032-L8040

The suggested solution is to move the expansion of runtime lookups to lower so that both the importer and morph can just create and insert a new node representing a runtime lookup and have lower expand it in an optimal way. This will involve teaching optimization phases (e.g., value numbering) about the new runtime lookup node.

category:cq
theme:helpers
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
@erozenfeld marking this as future; let me know if you think we should try to implement this in 5.0.
