### ISSUE TITLE
about runtime support Windows Server 2008 

### ISSUE THREAD

**Issue by sgf** [dotnet/runtime#35553]
Windows 2008+ OS (including: server 2012 server 2016 server 2019) are relatively poor in design. The system occupies a very large amount of resources, which leads to the fact that the system's own resource consumption is very ridiculous.

In fact, the market of server 2008 is mainly SMEs, they have no much resorce (money). The higher version of the system means wasting more resources resorce (money). Unless Microsoft has plans to improve in the future new server OS Efficiency of system resource utilization.

Therefore, in fact, the utilization rate of windows server 2008 is actually very high, although Microsoft has stopped the mainstream update service. 
But .net core runtime as a language runtime, especially asp.net. The current new version (3.1), or future version does not plan to support windows server 2008 OS.

The benefits of windows server 2008 include: low resource usage (memory and CPU), fast ui response (classic ui), stability (much system services including remote desktop), and easy operation (compared to the server core system command line ).

If .net core does not support this system, I think its lost a very big promotion opportunity.
For example: many customers' systems can be migrated from .net 4.0 to the new .net core, but now, due to core 3.1 and other subsequent versions are not supported. 

This stoped these systems from migrating to .net core and enjoying the new .net core ecosystem.

its not hard to support it,right?so why not?

**Comment by sgf** [comment]
@Dotnet-GitSync-Bot tag: os-windows area-Host

**Comment by GrabYourPitchforks** [comment]
What is your specific question?

**Comment by sgf** [comment]
> What is your specific question?
could be .net core runtime new version(5.0 or newer) support Windows Server 2008

**Comment by xtqqczze** [comment]
@sgf Windows Server 2008 and Windows Server 2008 R2 reached end of Extended Support
on 2020-01-14. This means Microsoft no longer provide *free security updates*.
https://support.microsoft.com/en-gb/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2

**Comment by leecow** [comment]
@xtqqczze is correct, .NET 5 will not be supported on Server 2008 as that product has reached the end of support from the owning team. This is the standard .NET Core support policy for all supported OS platforms as detailed in the supported os documentation ([2.1](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md), [3.1](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md), [5.0](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md))

**Comment by sgf** [comment]
Maybe I should choose go-lang to avoid these .net core deployment problems.
