### ISSUE TITLE
Use '/r' rather than '-platform_assemblies_paths' for crossgen calls

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3556]
`/r` is a new parameter that accepts individual files, rather than entire directories.

In WindowsDesktop, we have two directories that provide the same `WindowsBase.dll`. Using `/r` allows us to specifically point to the DLL we want to use, rather than relying on an implementation detail by ordering `platform_assemblies_paths` in a specific way.

**Comment by NikolaMilosavljevic** [comment]
No clear reason to implement, stale.
