### ISSUE TITLE
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto returns only 1 symbol is length attribute is not specified

### ISSUE THREAD

**Issue by y0rik** [dotnet/runtime#35588]
The following behavior is observed when .Net core Marshal.PtrToStringAuto is used

![Screenshot_20200429_005525](https://user-images.githubusercontent.com/58331951/80545735-5ae07700-89b4-11ea-91dd-851a33993b17.png)

**Comment by jkotas** [comment]
`PtrToStringAuto` uses UTF8 encoding on non-Windows platforms. BSTRs are always UTF16. It means that the second byte of the BSTR is zero and `PtrToStringAuto` will interpret it as end of string.

Try to use `PtrToStringUnicode` instead.

**Comment by y0rik** [comment]
Thank you, Jan. This works.
