### ISSUE TITLE
Environment.ExitCode not respected when void Main throws exception

### ISSUE THREAD

**Issue by Davidsv** [dotnet/runtime#35599]
**Version Used:**
Microsoft Visual Studio Professional 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Net core 3.1 Console application on Windows 10

**Steps to Reproduce:**
Run this
```
class Program
{
   public static void Main()
   {
      Environment.ExitCode = 1;
      throw new Exception("boom");
   }
}
```

**Expected Behavior:**
I would have expected it to print the exception and have an exit code `1`. 

**Actual Behavior:**
The exception is printed but the Exit code is `0`:

> Unhandled exception. System.Exception: boom
>    at ExitCodeTest.Program.Main() in C:\repos\private\ExitCodeTest\ExitCodeTest\Program.cs:line 11
> 
> C:\repos\private\ExitCodeTest\ExitCodeTest\bin\Debug\netcoreapp3.1\ExitCodeTest.exe (process 10548) **exited with code 0.**
> To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
> Press any key to close this window . . .

**Remarks**
The documentation for `Environment.ExitCode` says "Gets or sets the exit code of the process.". Furthermore, "If the Main method returns void, you can use this property to set the exit code that will be returned to the calling environment."

Is it not the intention of `Environment.ExitCode` to set an exit code that will be used unless something else is used?

**Comment by tmds** [comment]
fyi, on Linux:
```
$ bin/Debug/netcoreapp3.1/console 
Unhandled exception. System.Exception: boom
   at console.Program.Main() in /tmp/console/Program.cs:line 10
Aborted (core dumped)
$ echo $?
134
```
This is ok. Unhandles exceptions cause `abort`. 128 + SIGABRT (6) = 134

**Comment by jkotas** [comment]
Exceptions and other abnormal situations take precedence in this case. It is the expected behavior.

If you would like to override the exit code for unhandled exceptions, you should be able to do that by providing your own `UnhandledException` handler, e.g.:

```
using System;

class Program
{
    static void Main(string[] args)
    {
        AppDomain.CurrentDomain.UnhandledException += UnhandledException;
        throw new Exception("boom");
    }

    private static void UnhandledException(object sender, UnhandledExceptionEventArgs e)
    {
        Environment.Exit(1);
    }
}
```

**Comment by Davidsv** [comment]
If `Environment.Exit(1)` is used, the exception is no longer printed. Maybe it is normally printed to stderr so it can be used later? I'm not sure of the terminology, but how could I output the exception in an equivalent way if I also need to use `Environment.Exit(1)`?

In any case, looks like there is a large difference between linux and windows here. Is it an undesirable difference?

**Comment by jkotas** [comment]
You can print the exception in your unhandled exception handler in any format you would like:
```
    private static void UnhandledException(object sender, UnhandledExceptionEventArgs e)
    {
        Console.Error.WriteLine(e.ExceptionObject);
        Environment.Exit(1);
    }
```

We delegate the unhandled exception to the OS specific handler for fatal crashes (Windows Error Reporting on Windows, and `abort` on Unix systems). It allows the OS specific mechanisms to log the fatal crash or to create crash dump to kick in, but also results into differences between OSes.

**Comment by tmds** [comment]
On Linux exit code `0` is used to indicate the program finished successful.
It is unfortunate that the default exit code of a program that terminates due to an unhanded exception is `0`. That may lead to false assumptions a program finished successful.

**Comment by jkotas** [comment]
The default exit code of a program that terminates due to an unhanded exception is not 0. 

The Visual Studio debugger has a quirk that it reports exit code of programs that terminate due to unhandled exceptions as 0 on Windows, but that only happens when you run the program from VS debugger. It does not happen when you run the program from the command line. @noahfalk

**Comment by janvorli** [comment]
Running the repro at the beginning of this issue from command line using "dotnet run" gets exit code -532462766 (E0434352), which represents unhandled managed exception. Both in 3.1 and 5.0. So maybe it is VS issue?

**Comment by janvorli** [comment]
Ah, so VS shows zero exit code if you debug the application. If you just run it, it shows the -532462766.

**Comment by Davidsv** [comment]
Thanks for the comments, looks it works like intended, and as you point out is not really an issue in prod
