### ISSUE TITLE
Developers need FTP client support!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#356]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/392809/developers-need-ftp-client-support.html)._

---
<p>At https://docs.microsoft.com/en-us/dotnet/api/system.net.ftpwebrequest?view=netframework-4.7.2 I'm reading &quot;We don't recommend that you use the FtpWebRequest class for new development. For more information and alternatives to FtpWebRequest, see WebRequest shouldn't be used on GitHub.&quot;, and at that GitHub page, it says to use 3rd party FTP client.  Really???  Why is Microsoft <u>removing</u> support?  FTP is still very popular, especially for interfacing between systems (such as accounting, purchasing, invoicing, etc.).  PLEASE KEEP SUPPORTING FtpWebRequest.  Thanks.</p>

---
#### Dylan Cottell on 11/28/2018, 05:33 AM: 

<p>Doing some research, it looks like the WebClient libraries have been depreciated. Whilst I cannot find any official post from Microsoft regarding this, following the trail of development leads us to <a target='_blank' href="https://github.com/robinrodricks/FluentFTP" target="_blank">FluentFTP</a> (https://github.com/robinrodricks/FluentFTP) which should be used as a replacement.</p><p>System.Net.FtpWebRequest was superseded by System.Net.FtpClient, as all WebRequest libraries were superseded by the Client Libraries. After some time, FtpClient became FluentFTP. As I can't find a direct source announcing this, this is what I've been able to gather from some research.</p><p>tl;dr - Don't use FtpWebRequest as it's depreciated. Use FluentFTP. </p>

**Comment by wfurt** [comment]
FTP may not get much active development but it is not going away. While it may be in used for legacy reasons, one should consider security aspects.  
It is also open for contributions from community if there is enough interest.
This does not seems actionable. cc: @karelz

**Comment by karelz** [comment]
Agreed, FtpWebRequest is supported in its current form. It does not mean we have to recommend the API going forward though.
