### ISSUE TITLE
KeyValuePair<TKey, TValue> should implement IEquatable<T>

### ISSUE THREAD

**Issue by znakeeye** [dotnet/runtime#35602]
The [KeyValuePair](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/KeyValuePair.cs) class should implement [IEquatable&lt;T&gt;](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netcore-3.1).

Consider the sample below. It doesn't compile due to the constraint.

```c#
class Program
{
    class Foo : IEquatable<Foo>
    {
        public bool Equals(Foo other) => false;
    }

    static void Bar<T>(IEnumerable<T> items) where T : IEquatable<T>
    {
        // Code that relies on IEquatable<T>
    }

    static void Main(string[] args)
    {
        var dic = new Dictionary<string, Foo>();
        
        Bar(dic);        // CS0315
        Bar(dic.Values); // ok, but produces more garbage
    }
}
```

In our performance critical application, reading the `Values` property is not an option. Now we faced the above problem, where our `IEquatable<T>` aware APIs cannot be used in this context.

**Current declaration:**
```c#
public readonly struct KeyValuePair<TKey, TValue>
```

**Should be:**
```c#
public readonly struct KeyValuePair<TKey, TValue> : IEquatable<KeyValuePair<TKey, TValue>>
```

Current **workaround** involves **allocating** an intermediate enumerator:

```c#
private static IEnumerable<TValue> GetItems<TKey, TValue>(Dictionary<TKey, TValue> dic)
    where TValue : IEquatable<TValue>
{
    foreach (var kvp in dic)
    {
        yield return kvp.Value;
    }
}
```

**Comment by scalablecory** [comment]
What are you imagining the implementation being? `EqualityComparer.Default` on each of the members?

**Comment by john-h-k** [comment]
I could see it implementing all 3 - `IEquatable<KeyValuePair<TKey, TValue>>, IEquatable<TKey>, and IEquatable<TValue>`

**Comment by znakeeye** [comment]
Well, this is an error that should have been caught by your unit tests. All value types should implement `IEquatable<T>` as stated on [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netcore-3.1).

You effectively have a well-used *public* type that a developer can unintentionally misuse, ending up with unnecessary boxing.

> If you're only interested in enumerating values in the dictionary, you can already use `Dictionary<TKey,TValue>.Values` to get an `IEnumerable<TValue>`.

No. That's exactly what I'm trying to avoid here. Reading the `Values` property is very costly (at least as of .NET 4.7.2). Put it on a hot path and you are in GC trouble. So my workaround is highly relevant. Memory profiling a hot path in our code pointed at the `Values` collection, and using a regular `foreach` loop fixes that.

I agree with @john-h-k. For the strongly typed `KeyValuePair<..>` why not enforce strongly typed equability? As of 2020, it makes no sense to write a class without implementing this interface. Even more so for **struct**.

**Comment by eiriktsarpalis** [comment]
Given KVP is a readonly struct, I think this would be a reasonable addition. There is precedent in the [ValueType implementations](https://github.com/dotnet/runtime/blob/8a6693a33ddc67d9e8c343a21e631840d68f830f/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L481-L485). Note that `Object.Equals()` and `Object.GetHashCode()` would need to be overridden explicitly as well.

**Comment by jkotas** [comment]
This is non pay-for-play API. It will make static footprint of all existing Dictionary instantiations more expensive. I do not think that this is a good API to add.

**Comment by znakeeye** [comment]
Interesting. Care to elaborate? Which static footprint are you referring to?

**Comment by jkotas** [comment]
The memory occupied by the runtime data structures that are backing the type.

**Comment by terrajobst** [comment]
* We believe @jkotas concerns outweighs the (minor) benefit of adding this API.
