### ISSUE TITLE
libnethost.lib in shared directory

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#35616]
The static library version of `nethost.dll` is located in the `shared/` directory with `coreclr.dll`. This was discovered in the nightly build and shouldn't be there. For example:

`shared\Microsoft.NETCore.App\5.0.0-preview.5.20228.12\libnethost.lib`

The macOS and linux archives weren't checked.

/cc @vitek-karas @swaroop-sridhar @elinor-fung

**Comment by vitek-karas** [comment]
@swaroop-sridhar @VSadov could one of you please take this and get it fixed?

**Comment by AaronRobinsonMSFT** [comment]
@VSadov @vitek-karas This seems to no longer be shipped in `shared\Microsoft.NETCore.App` - yay, but is now no longer shipped at all - boo. This is breaking tools like https://github.com/AaronRobinsonMSFT/DNNE that rely on the static lib of nethost - `libnethost.lib`.

I verified this on the [nightly build](https://github.com/dotnet/installer#installers-and-binaries) - `5.0.0-preview.7.20313.3`.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky This is an issue I hope some of your work on setup will address.

**Comment by VSadov** [comment]
I have checked   `shared\Microsoft.NETCore.App\5.0.0-rc.1.20404.16`  and `libnethost.lib` is there. As I understand this is undesirable.

Where exactly it should be though?

**Comment by AaronRobinsonMSFT** [comment]
It is simply superfluous in this location - it is never used. The `libnethost.lib` libraries are deployed in the apphost package and have no purpose in the actual `Microsoft.NETCore.App` location.

**Comment by VSadov** [comment]
Fixed in: https://github.com/dotnet/runtime/pull/40754
