### ISSUE TITLE
Remove redundant load that is immediately after the store in same src/dst

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#35613]
I have seen below pattern in generated code for framework libraries. We can eliminate the `ldr` if it is loading the value into same register that was used to store in previous instruction in same memory location.

Example of ARM64 code:
```asm
B90023A0          str     w0, [fp,#32]	// [V04 loc1]
B94023A0          ldr     w0, [fp,#32]	// [V04 loc1]
```

Example of x64 code:
```asm
48894C2430           mov      gword ptr [rsp+30H], rcx
488B4C2430           mov      rcx, gword ptr [rsp+30H]
```

There are approx. 2500 such patterns in 1500 methods. Details in [str-ldr.txt](https://github.com/dotnet/runtime/files/4553462/str-ldr.txt).

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/35614

**Comment by kunalspathak** [comment]
It turns out that we shouldn't do this optimization for 4-byte registers. Consider for below example, the 2nd instruction zero-extends the upper bits of `x0` by doing `ldr`. If 2nd instruction is eliminated, that won't be true and hence would cause functional bug.

```asm
B90023A0          str     w0, [fp,#32]	// [V04 loc1]
B94023A0          ldr     w0, [fp,#32]	// [V04 loc1]
```

With that, I re-calculated the patterns in framework libraries and looks like there are 1442 patterns in 830 methods.

Details:
[str-ldr-x.txt](https://github.com/dotnet/runtime/files/4921159/str-ldr-x.txt)
