### ISSUE TITLE
[System.Drawing.Icon.Unix] Icon file with single PNG icon should be marked as valid as well

### ISSUE THREAD

**Issue by darkdragon-001** [dotnet/runtime#35610]
https://github.com/dotnet/runtime/blob/ee3ee42fb2df77300ed6bf2c490ba8d4fccef025/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs#L805-L816

On Linux, PNG icons are processed, but the overall file is not marked as valid and throws an exception as a result.

On Windows this seems to be supported:
https://github.com/dotnet/runtime/blob/0fa0b905f65e57f5eb64dd556a07ead522930c8a/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs#L707-L719

**Comment by safern** [comment]
Thanks @darkdragon-001 this definitely seems like a bug in the Unix parsing logic. We will take a look at this, however I don't think this is critical for 5.0 at the given timeframe, so will move it to next release.

**Comment by darkdragon-001** [comment]
Sad to hear it won't be part of the 5.0.0 release. Really looking forward to see this fixed (it bothers me every couple days)!

**Comment by safern** [comment]
@darkdragon-001 I'm sorry to hear that, I'll change the milestone to 5.0.0 to see if we can put up a fix at the right timeframe to make it on time since the fix seems simple enough.

**Comment by jeffhandley** [comment]
I'm sorry we weren't able to get to this issue during 5.0.0; we're going to have to move it to 6.0.0.

**Comment by safern** [comment]
@darkdragon-001 I'm sorry we missed this issue. We were evaluating what was going to be the story for `System.Drawing.Common` on Unix going forward and we decided that it is not worth to keep investing on that path for various different reasons. You can read more about that decision here: https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

Please let us know if you have any questions.
