### ISSUE TITLE
Fix Windows build to /W3 or /W4 and enable warnings as errors

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#3561]
We are building with `/W1`. We should probably build with `/W3` at least, as the runtime does. We should also add `/WX`.

https://github.com/dotnet/core-setup/blob/master/src/settings.cmake#L160

cc @eerhardt who pointed it out.

**Comment by am11** [comment]
This was fixed with unification of configs (#33716). W3 and WX are used by installer and coreclr alike: https://github.com/dotnet/runtime/blob/c985bdcec2a9190e733bcada413a193d5ff60c0d/eng/native/configurecompiler.cmake#L455-L456

**Comment by danmosemsft** [comment]
Thank you, @am11.
