### ISSUE TITLE
Is there a sscli for .net 3.5?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/runtime#35617]
This repo is the lastest .net source, and there's a sscli20 for .net 2.0.
So, is there a sscli for .net 3.5? I want to learn more about JIT, but there's some differences between 3.5 and 2.0

**Comment by jkotas** [comment]
Shared Source CLI 2.0 was the last one.

If you would like to learn more about the JIT, look at JIT in this repo. The JIT in sscli20 did not have any optimizations - it was not the JIT shipping in .NET Framework.

**Comment by CreateAndInject** [comment]
@jkotas 
```
    virtual void __stdcall embedGenericHandle(
                        CORINFO_MODULE_HANDLE   module,
                        unsigned                metaTOK,
                        CORINFO_CONTEXT_HANDLE  context,
                        CorInfoTokenKind        tokenKind,
                        CORINFO_GENERICHANDLE_RESULT *pResult) = 0;
```

I find this in sscli20, but the .pdb of mscorwks.dll (from 3.5) tell me: There must be something between `metaTOK` and `context`

```
    virtual void __stdcall embedGenericHandle(
                        CORINFO_MODULE_HANDLE   module,
                        unsigned                metaTOK,
                        //There must be one more field, what???
                        CORINFO_CONTEXT_HANDLE  context,
                        CorInfoTokenKind        tokenKind,
                        CORINFO_GENERICHANDLE_RESULT *pResult) = 0;
```
Could you tell me what's it and what's meaning?

**Comment by jkotas** [comment]
Sorry, this is undocumented interface in .NET Framework. I am not able to provide the details about it.
