### ISSUE TITLE
CreateAppHost fails on file systems that cannot mmap with MAP_SHARED

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/runtime#35628]
I created a new console application in VS 2017 using .NET Core 2.1. Published it as a self-contained linux-x64 app without any changes and tried to run it on an Ubuntu 18.04 VM. Got this error:

```
 ./LinuxTest 
This executable is not bound to a managed DLL to execute. The binding value is: 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2'
A fatal error was encountered. This executable was not bound to load a managed DLL.
```

c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2 is apparently the SHA256 hash of "foobar", so whatever the real problem is, this is a very weird error message, too!

LinuxTest.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

</Project>
```

Program.cs:
```
using System;

namespace LinuxTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

Resulting self-contained binary: [LinuxTest.zip](https://github.com/dotnet/sdk/files/2900841/LinuxTest.zip)

If I install dotnet-runtime-2.1 on the Linux VM and run `dotnet LinuxTest.dll` it works.

**Comment by dsplaisted** [comment]
@swaroop-sridhar @jeffschwMSFT We think this would be a fix to the CreateAppHost code which lives in the runtime repo.  So I've moved it to dotnet/runtime.  Please triage.  Thanks!

**Comment by swaroop-sridhar** [comment]
Sure @dsplaisted. 
This issue depends on implementing https://github.com/dotnet/runtime/issues/3829, which would be a good thing to implement in .net 5.  Thanks.

**Comment by loop-evgeny** [comment]
Why does it depend on that (providing the offset)? Can't the search and replace still be done using normal file read/write APIs (instead of a memory-mapped file)?

**Comment by swaroop-sridhar** [comment]
@loop-evgeny  "depends" was probably too strong a constraint. 
Fixing #3829 would eliminate the need to search the pattern, and is a better fix than using search/replace via read/write. Please see Nick's comments [above](https://github.com/dotnet/runtime/issues/35628#issuecomment-551202981).

,

**Comment by agocke** [comment]
This should be fixed as we no longer use MAP_SHARED to write the apphost
