### ISSUE TITLE
Double System.Drawing.PointConverter

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#35651]
Discovered in PowerShell repo (based on .Net 5.0 Preview3)
(for reference https://github.com/PowerShell/PowerShell/pull/10869)
I guess the first dll reference is outdated.
```powershell
 [System.Drawing.Point].GetCustomAttributes($false)

ConverterTypeName
-----------------
System.Drawing.PointConverter, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a


[System.Drawing.PointConverter].AssemblyQualifiedName
System.Drawing.PointConverter, System.ComponentModel.TypeConverter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```
I guess the issue here:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Drawing.Primitives/src/System/Drawing/Point.cs#L14-L15

As result it break PowerShell Core:
```powershell
[System.Drawing.Point]'10,20'
InvalidArgument: Cannot convert the "10,20" value of type "System.String" to type "System.Drawing.Point".
```

**Comment by tannergooding** [comment]
@safern, do you think this should be fixed with a type forward or by updating the assembly in the `TypeConverter` declaration?

**Comment by iSazonov** [comment]
In https://github.com/PowerShell/PowerShell/issues/12513 mentioned other affected types.

**Comment by safern** [comment]
I believe the reason why the `TypeConverter` declaration is like that, is because Point is serializable and we needed to match whatever `Desktop` had to be able to serialize and deserialize from Desktop to Core and the other way around. However, I would expect `System.Drawing, 4.0.0.0` to be a facade in .NET Core, which typeforwards `PointConverter` to `System.Drawing.Common`. @iSazonov do you have a full stack trace on the error?

**Comment by safern** [comment]
cc: @ericstj

**Comment by iSazonov** [comment]
> do you have a full stack trace on the error?

No exception. PowerShell collects type references to assemblies at design time in a type catalog (right). At run time it call GetCustomAttributes() and get another (wrong) assembly reference then from the type catalog. As result PowerShell doesn't know that assembly to use to create the type instance.
So expectation is that GetCustomAttributes() returns a reference to real assembly, not fake 4.0.0.0.

**Comment by ericstj** [comment]
System.Drawing 4.0.0.0 is a real assembly and exists in the shared framework with typeforward to System.ComponentModel.TypeConverter, from IL:
```
.class extern forwarder System.Drawing.PointConverter
{
	.assembly extern System.ComponentModel.TypeConverter
}
```
Simply calling GetType on `System.Drawing.PointConverter, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` succeeds, as well as getting this through TypeDescriptor.

You shouldn't be attempting to resolve types and assemblies yourself, if that's what you're doing.  Let the runtime do that for you.

See https://gist.github.com/ericstj/fc115cc3102555efd3dbd6a3461e17f9.

**Comment by iSazonov** [comment]
> Let the runtime do that for you.

So  GetCustomAttributes() should do this and returns reference to real assembly, not fake.

**Comment by ericstj** [comment]
GetCustomAttributes doesn't return an assembly reference, it returns an atttribute with a string value pointing to a fully qualified type name.  If you ask the runtime to resolve that type it will work.  PowerShell is implementing some form of type resolution itself which is what's failing because it isn't following type-forwards nor loader policy for assembly versions.  

What does Powershell do with the type name it reads?  If you point us to this code we could probably make a recommendation.  /cc @jkotsas

**Comment by iSazonov** [comment]
The code https://github.com/PowerShell/PowerShell/blob/8de0ddc6d16474ec895bf3559fd15683656589fc/src/System.Management.Automation/engine/LanguagePrimitives.cs#L1491-L1500

I tied using Type.GeType() for the attr.ConverterTypeName and this works. 
```c#
            var typeConverters = type.GetCustomAttributes(typeof(TypeConverterAttribute), false);
            foreach (var typeConverter in typeConverters)
            {
                var attr = (TypeConverterAttribute)typeConverter;
                string assemblyQualifiedtypeName = attr.ConverterTypeName;
                typeConversion.WriteLine("{0}'s TypeConverterAttribute points to {1}.", type, assemblyQualifiedtypeName);
                var converterType = Type.GetType(attr.ConverterTypeName);    // Key here!!!

                // The return statement makes sure we only process the first TypeConverterAttribute
                return Activator.CreateInstance(converterType);
```
But now it passes PowerShell type catalog assembly resolver and I'm not sure if this is permissible
/cc @TylerLeonhardt @daxian-dbw @SteveL-MSFT @rjmholt

**Comment by ericstj** [comment]
This [NewConverterInstance](https://github.com/PowerShell/PowerShell/blob/8de0ddc6d16474ec895bf3559fd15683656589fc/src/System.Management.Automation/engine/LanguagePrimitives.cs#L1505-L1544) method seems to be making assumptions about exact match on AssemblyName which is not resilient to new versions (whereas the default AssemblyLoader is).  I can't tell for certain but this also looks to be scoping the set of assemblies examined based on type, which may miss assemblies that contain typeforwards.

An algorithm closer to Type.GetType would be splitting the assembly portion out of the fully-qualified type name.  Loading that assembly while applying policy, like version roll forward, or whatever might be done by a load context.  Then asking that assembly for the type, which might in turn resolve a different assembly in the case of a type forward.  I added a hacky sample to the gist to demonstrate with Assembly.Load but you could do that with your own loader.  /cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@vitek-karas

**Comment by iSazonov** [comment]
> which may miss assemblies that contain typeforwards.

We use a script and tool to generate a type catalog https://github.com/PowerShell/PowerShell/blob/6d1d62f2f83b526997d23e0606be9d5708246e9f/build.psm1#L1969-L2016
As result we get Dictionary like:
```
                {"System.Drawing.ColorConverter", "System.ComponentModel.TypeConverter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"},
                {"System.Drawing.PointConverter", "System.ComponentModel.TypeConverter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"},
                {"System.Drawing.RectangleConverter", "System.ComponentModel.TypeConverter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"},
```
Even if we enhanced this catalog, PowerShell still clearly verifies TPA - that exactly requested assembly is loaded https://github.com/PowerShell/PowerShell/blob/6d1d62f2f83b526997d23e0606be9d5708246e9f/src/System.Management.Automation/engine/LanguagePrimitives.cs#L1519

**Comment by ericstj** [comment]
The part that didn't honor TPA was the exact string match check of Assembly name below.  The part that doesn't honor type forwards is the fact that your type->assembly catalog is only listing TypeDefs and doesn't include entries for assemblies that export types but forward to another assembly.

**Comment by iSazonov** [comment]
One my thought how resolve this in PowerShell without any fix in .Net is that if PowerShell already load a type PowerShell already trust to the type and could trust an attribute it get for the type and bypass TPA check with `Type.GetType(attr.ConverterTypeName)`.

**Comment by daxian-dbw** [comment]
I think this is something that should be fixed in PowerShell.
Since the full assembly name is given, PowerShell should call `Assembly.Load` to load that assembly, and then run `Assembly.GetType` to get the type back.

**Comment by safern** [comment]
Yeah I agree this should be fixed in PS. There is not anything wrong from the runtime side of things as we have the right typeforwards and point to a real, existing assembly in the shared framework. @iSazonov are you OK with closing this issue? Discussion can of course keep going.

**Comment by iSazonov** [comment]
Yes, my goal was to inform .Net team that this could cause some compatibility issues.
It also worries me that it was first discovered at .Net 3.0 milestone, fixed in .Net 5.0 Preview1 and has reappeared now. I hope .Net team found right solution and this area will now be stable.
