### ISSUE TITLE
Error running all library tests

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#35664]
Built as follows:
```
$ ./build.cmd -subset clr -c Checked
$ ./build.cmd -subset Libs+Libs.Tests -runtimeConfiguration Checked
```
Then I tried to run all tests from root as follows (per a comment by @ViktorHofer in Issue #34152):
```
$ ./build.cmd libs.tests -test -coverage -runtimeConfiguration Checked
```

This ended quickly in the following error:

> Build FAILED.
> 
> C:\Users\mrj00\source\repos\runtime\eng\testing\coverage.targets(42,7): error MSB4184: The expression ""C:\Users\mrj00\source\repos\runtime\src\libraries".SubString(50)" cannot be evaluated. startIndex cannot be larger than length of string. (Parameter 'startIndex') [C:\Users\mrj00\source\repos\runtime\Build.proj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:23.25
> Build failed.
> Some builds failed:
>         Configuration: Debug, Architecture: x64
>

**Comment by ViktorHofer** [comment]
This will be fixed with https://github.com/dotnet/runtime/pull/35285

**Comment by danmosemsft** [comment]
What command should @mrj001 use meantime?

**Comment by ViktorHofer** [comment]
A workaround meanwhile would be to change this line: https://github.com/dotnet/runtime/blob/master/eng/testing/coverage.targets#L21 to
`<Target Name="SetupCoverageFilter" Condition="'$(MSBuildProjectFile)' != 'tests.proj'">

**Comment by mrj001** [comment]
@ViktorHofer 
I got 256 errors all similar to this:

> C:\Users\mrj00\source\repos\runtime\eng\testing\tests.targets(102,24): error MSB4113: Specified condition "'$(TargetsMobile)'" evaluates to "" instead of a boolean. [C:\Users\mrj00\source\repos\runtime\src\libraries\Common\tests\Common.Tests.csproj]

Is there an expected date for that PR to be applied?

**Comment by ViktorHofer** [comment]
cc @steveisok for the broken TargetsMobile condition.

Yes, the change will be merged next Monday.

**Comment by steveisok** [comment]
We'll have a PR up for that `$(TargetsMobile)` check shortly

**Comment by steveisok** [comment]
PR is up https://github.com/dotnet/runtime/pull/35709
