### ISSUE TITLE
Close and Send with timeout CancellationToken is not timing out

### ISSUE THREAD

**Issue by nosalan** [dotnet/runtime#35666]
### Describe the bug
When closing websocket using `CloseAsync` method with timeout based `CancellationToken` the Close method hangs indefinitely and the timeout of 10 seconds is disregarded.
This happens when the remote site is not processing messages timely. For example when you put a long thread sleep in the remote receiving loop. Link to reproduction example repo is below. In this code I send several messages to remote and then invoke `CloseAsync`. The closing hangs despite passing the `CancellationToken`.
This is how I do the closing:
```c#
using (var ctsc = new CancellationTokenSource(TimeSpan.FromSeconds(10)))
{
    var token = ctsc.Token;
    try
    {
        Console.Out.WriteLine("Closing");
        //Bug - hangs here when remote is not processing messages timely
        await socket.CloseAsync(WebSocketCloseStatus.NormalClosure, "", token);
        //Never got here, CancellationToken is not working
        Console.Out.WriteLine("Closed");
    }
    catch (OperationCanceledException e)
    {
        Console.WriteLine(
            "Exc on close: " + e.Message + ". Is our canc?: " + (e.CancellationToken == token));
    }
    catch (Exception e)
    {
        Console.WriteLine(
            "Another Exc on close: " + e.Message);
    }
}
```

What's more painful is that I have similar problem with `SendAsync` method even if `CancellationToken` with timeout is provided. I could not create a reproducible example for sending case because it only happens sometimes on our docker (Debian based, 3.1.3 dotnet runtime). Sending just hangs for long minutes, whereas I would like to timeout.

### To Reproduce

The code to reproduce the `CloseAsync` method cancel issue is here:
https://github.com/nosalan/dotnet-core-websocket-cancelling-issue

### Further technical details (Close issue reproduction)
- ASP.NET Core version
- Include the output of `dotnet --info`:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:
Rider

**Comment by stephentoub** [comment]
I've not yet looked at the code, but from your description and repro, I'm betting it's the following.  We can only have at most one receive pending at a time, and a close needs to receive.  In your repro, you have a receive pending at the time you try to close.  Close sees the pending receive, and thus relies on it to read the close message sent in response, but because the receive is already pending, it doesn't have a chance to supply its own cancellation token, and thus close's token ends up being ignored.  To address this, when we detect in close that there's already a receive pending, we probably need to just register to Abort similar to how we do elsewhere.

**Comment by stephentoub** [comment]
I put up a fix for the CloseAsync cancellation issue at https://github.com/dotnet/runtime/pull/35715.  I can't repro the send case you alluded to; if you're able to create a repro for that, please open a separate issue with it and we'll happily take a look.  Thanks!

**Comment by nosalan** [comment]
Thanks for fixing that immediately!

Regarding the situation when the sending hangs. In noticed in the code of `ManagedWebSocket` that not all calls to `_stream.WriteAsync` are made with the cancellation token. One of the situations, that theoretically could happen is when `SendFrameLockAcquiredNonCancelableAsync` is invoked with `MessageOpcode.Ping`. This invocation does not supply cancellation token and it cannot be passed as the caller is an internal timer. Perhaps a network buffer goes full because, again, the remote is lagging or hanged and the ping invocation is holding the `_sendFrameAsyncLock` indefinitely.

**Comment by stephentoub** [comment]
> the remote is lagging or hanged and the ping invocation is holding the _sendFrameAsyncLock indefinitely.

That shouldn't be a problem.  The code that then tries to send passes its CancellationToken to WaitAsync on _SendFrameAsyncLock:
https://github.com/dotnet/runtime/blob/6d40a8ff5139c59815304487f1dc9dd4ead752ae/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L448

**Comment by nosalan** [comment]
Ah ok, I was looking at 3.1 code where there was no token at that place :)
That's a great news, there's a big chance the problem with sending goes away when we switch to dotnet core 5. Thanks!

**Comment by stephentoub** [comment]
Great. Thanks.
