### ISSUE TITLE
Fix libunwind CMake typo.

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#35669]
https://github.com/dotnet/runtime/blob/aa81328f4e3e53e9dabb7839bcd0533fe6e485ed/src/coreclr/src/pal/src/libunwind/CMakeLists.txt#L9

Typo `elseif(CLR_CMAKE_PLATFROM_ARCH_ARM)`

This was also an issue with 3.1. https://github.com/dotnet/coreclr/blob/05e3582c126663120b82a2eec8fd12dcb6929064/src/pal/src/libunwind/CMakeLists.txt#L9

Mostly raising an issue to see whether this matters enough to backport to 3.1.
I don't really know whether this matters much as we seem to be able to build...

/cc @janvorli  @mikem8361

**Comment by janvorli** [comment]
The good news is that this arch variable is not used anywhere.

**Comment by janvorli** [comment]
Hmm, I take it back, it is. I've overlooked it.

**Comment by janvorli** [comment]
But it is used only when UNW_REMOTE_ONLY is defined, which we never define.

**Comment by sdmaclea** [comment]
This looks like it was fixed in the tip already.  Closing.
