### ISSUE TITLE
[System.Text.Json] NRE thrown when applying JsonExtensionData attribute to a property whose type inherits from Dictionary instead of being a Dictionary

### ISSUE THREAD

**Issue by YetAnotherCodeMaker** [dotnet/runtime#35677]
When deserializing a JSON string containing unknown properties into a class which contains such a property, the UnknownProperties property receives the unknown properties, as expected
```
class TheClass
{
    [JsonExtensionData]
    public Dictionary<string, object> UnknownProperties { get; set; } =
        new Dictionary<string, object>();
}
```
When the property is defined like below, a null reference exception is raised while deserializing
```
class TheClass
{
    [JsonExtensionData]
    public CustomDictionary<string, object> UnknownProperties { get; set; } =
        new CustomDictionary<string, object>();
}

public class CustomDictionary<TKey, TValue> : Dictionary<TKey, TValue> { }
```
version 4.7.1

**Comment by layomia** [comment]
We've made improvements to the JsonExtensionData feature for version 5.0.0/.NET 5, and this issue doesn't repro.

For version 4.7.x and .NET Core 3.x, the serializer has limited support for custom dictionaries as extension data properties. It is recommended to use a built in dictionary like `Dictionary<string, JsonElement/object>`. 

Closing as this issue doesn't meet the bar for a servicing fix to these prior versions.
