### ISSUE TITLE
[Uri] Uri caches DnsSafeHost rather than IdnHost

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#35676]
Uri currently caches DnsSafeHost but not IdnHost.  However, accordingly to docs:

> IdnHost is provided as the preferred alternative to using DnsSafeHost, because IdnHost is guaranteed to always be DNS safe, no matter what the current app.config settings might be.

Would it make sense to cache IdnHost instead, if that's what we recommend developers use?

**Comment by davidsh** [comment]
>Would it make sense to cache IdnHost instead, if that's what we recommend developers use?

Yes we should cache IdnHost instead. The docs were written before we added the 'IdnHost' property, which is a recently new property for System.Uri.

**Comment by MihaZupan** [comment]
Related: #34618

I think it makes sense for us to cache both IdnHost and PathAndQuery.

**Comment by karelz** [comment]
Triage: Useful for Uri when they are reused. It is used by `SocketsHttpHandler`.
It will help gRPC perf scenarios.

Optional: Consider replacing `DnsSafeHost` usage with `IdnHost` in our code. We could then stop caching `DnsSafeHost`.
