### ISSUE TITLE
Bring back Win7 and Win8 queues to PRs once we have enough machines

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#35689]
Currently these queues were intentionally reduced. Once we have more cores we should bring them back to PR. Probably we could balance them out anyway as we do many runs on them. 

cc: @dotnet/runtime-infrastructure

**Comment by safern** [comment]
PR moving them to CI is: https://github.com/dotnet/runtime/pull/35690

**Comment by ViktorHofer** [comment]
@safern which queues are still disabled?

**Comment by safern** [comment]
We still have: https://github.com/dotnet/runtime/blob/master/eng/pipelines/libraries/helix-queues-setup.yml#L93 but I think we can remove those as I think the current balancing gives us good coverage without stressing the queues. I'll put up a PR to clean that up and close this issue.

**Comment by ViktorHofer** [comment]
Thanks :)
