### ISSUE TITLE
Simplify console output when runtime is missing

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#35697]
The text could be simplified to make copy/paste easier.

Current text:

```consoleC:\git\testapps\versioninfo>bin\Debug\net5.0\versioninfo.exe
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\git\testapps\versioninfo\bin\Debug\net5.0\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=win10-arm64&apphost_version=5.0.0-preview.4.20227.9
```

Here is the requested change (with only a subset of the text shown, for brevity):

```console
The .NET runtime can be found at:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=win10-arm64&apphost_version=5.0.0-preview.4.20227.9
```

In short remove "  - " before the URL.

**Comment by gfoidl** [comment]
Did you just mean this particular message or all similar messages:

The one mentioned in the isssue:
https://github.com/dotnet/runtime/blob/479067315a31a2a2285b62674ede2b5dbe44aff4/src/installer/corehost/cli/fxr_resolver.cpp#L122

The other ones:
https://github.com/dotnet/runtime/blob/78b303df8fbb242985d049a277d0d199cafd51b5/src/installer/corehost/corehost.cpp#L91
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/corehost/cli/fxr/fx_resolver.messages.cpp#L141

**Comment by richlander** [comment]
Any message that is similar.

**Comment by elinor-fung** [comment]
This should have been addressed with:
- https://github.com/dotnet/runtime/pull/67022
- https://github.com/dotnet/runtime/pull/67564
