### ISSUE TITLE
Do not use [Out] string for P/Invokes

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#35692]
Add a rule to flag P/Invoke declarations passing `string` parameters by value with the `[Out]` attribute, which can destabilize the runtime if the string is an interned string.
```C#
 // Flag [Out] string
[DllImport("MyLibrary")]
private static extern void Foo([Out] string s);

// OK
[DllImport("MyLibrary")]
private static extern void Bar(out string s1, [Out] ref string s2);
```

**Category:** Interoperability
**Default:** Enabled

cc @terrajobst @stephentoub @AaronRobinsonMSFT @jkoritzinsky

**Comment by stephentoub** [comment]
Is there any situation in which this is considered valid?  It's akin to pinning a string and then writing into it, right? I'm wondering if in addition to an analyzer (which I agree is warranted; I didn't realize we allowed this), .NET 5 should simply throw an exception at runtime if you try to do this.

**Comment by AaronRobinsonMSFT** [comment]
> .NET 5 should simply throw an exception at runtime if you try to do this?

I believe @jkoritzinsky added this.

**Comment by elinor-fung** [comment]
@terrajobst @stephentoub Any concerns with us going ahead with this? Is there a specific/official approval we should ask for?

**Comment by terrajobst** [comment]
> @terrajobst @stephentoub Any concerns with us going ahead with this? Is there a specific/official approval we should ask for?

Approval for which part? Throwing the exception, the analyzer or both? I thinking doing both seems great to me.

**Comment by elinor-fung** [comment]
@terrajobst Approval for the analyzer. We were told we would need to go through an official API review process via marking this issue as `api-ready-for-review`. Is that still the case - should we be marking it differently or are we no longer expecting an API review for analyzers?

**Comment by terrajobst** [comment]
The analyzer makes sense.

**Comment by elinor-fung** [comment]
Analyzer was added with dotnet/roslyn-analyzers#3879
Doc has also been added now: https://github.com/MicrosoftDocs/visualstudio-docs/commit/df17e88f5cd466580bb32ed9907a38cc3a1dbb67
