### ISSUE TITLE
Consider extending the functionality of the PEReader class 

### ISSUE THREAD

**Issue by Dewera** [dotnet/runtime#35691]
The `PEReader` class is very useful when working with portable executables (both managed and native) but currently only really supports the reading of the headers and debug directory information. I think it would be cool to extend the current class to read the information from the rest of the directories.

Some examples of what could be done 

- Import directory could be read to produce a collection of imported libraries + functions
- BaseRelocation directory could be read to produce a collection of base relocations
- Export directory could be read to produce a collection of exported functions

As both managed and native assemblies follow a similar PE format (in terms of the data directories) this information would be read in the same way regardless of the assembly. 

The offset + size of each directory is already read and present in the class so all that would really need to be implemented would be the reading of said directories themselves.

**Comment by ericstj** [comment]
Do you have a scenario for this?  Those directories don't typically contain useful information in managed (non C++/IJW) assemblies and S.R.M is largely focused on enabling the scenarios needed by managed tools (compilers and other design-time tools).   It doesn't aim to satisfy the scenarios of native toolchains.

**Comment by Dewera** [comment]
I would need to think more about specific examples of the above mentioned examples (for general usage,) however, one directory that I can see being relatively useful in a general managed context would be the resource directory (i.e embedded manifests.)
