### ISSUE TITLE
[System.DateTime] OLE Automation Date Inconsistencies

### ISSUE THREAD

**Issue by stageosu** [dotnet/runtime#35698]
There is a noticeable inconsistency with the OLE Automation Date parsing that is used in Dotnet Core 3.1. The issue lies within the minimum DateTime values for both the regular DateTime as well as the OLE Automation conversion.

```
Console.WriteLine(DateTime.MinValue); // prints 1/1/0001 12:00:00 AM
Console.WriteLine(DateTime.MinValue.ToOADate()); // prints 0
Console.WriteLine(DateTime.FromOADate(0)); // prints 12/30/1899 12:00:00 AM
```

Why is it that `DateTime.MinValue.ToOADate();` prints 0, while parsing a DateTime from an OADate of 0 returns a completely different date?

**Comment by vcsjones** [comment]
Well, this seems in line with its [documented behavior].

> The base OLE Automation Date is midnight, 30 December 1899.

That explains why "0" is 1899/12/30. So -1, would be 1899/12/29, etc.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tooadate?view=netcore-3.1

> The `ToOADate` method throws an `OverflowException` if the current instance represents a date that is later than `MaxValue` and earlier than midnight on January 1, 0100. However, if the value of the current instance is `DateTime.MinValue`, the method returns 0.

So 0100-01-01 gives "-657434".

So `MinValue` gets some special treatment. As to why, we can refer to this comment from comdatetime.cpp:

https://github.com/dotnet/runtime/blob/d119c051399136ddb7767115e56b3d55fa46b1a4/src/coreclr/src/vm/comdatetime.cpp#L100-L103

**Comment by joperezr** [comment]
According to the response abvoe this does seem to be by design, is that correct @tarekgh ?

**Comment by tarekgh** [comment]
Yes this is by design we special case the DateTime.MinValue when converting it to OA date.
