### ISSUE TITLE
In console.Beep feature can frequency include decimals too instead of integer alone?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#357]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/461285/in-consolebeep-feature-can-frequency-include-decim.html)._

---
<p>Console.Beep(int frequency, int duration) ------&gt; can this feature be made to include decimals too in the frequency feature? Sorry for the nuisance caused.Thanks for the opportunity given.</p>

---
#### Jane Wu [MSFT] on 2/18/2019, 11:59 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by danmosemsft** [comment]
What is the scenario where you require resolution of less than 1 Hz?

Anyway, I do not think this is possible. The Windows function [takes an integer](https://docs.microsoft.com/en-us/windows/win32/api/utilapiset/nf-utilapiset-beep). We do not have an implementation for Unix.
