### ISSUE TITLE
Docs about System.Environment.SpecialFolder.ProgramFiles might be wrong

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#35705]
https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=netcore-3.1#System_Environment_SpecialFolder_ProgramFiles

> On a non-x86 **system**, passing ProgramFiles to the GetFolderPath(Environment+SpecialFolder) method returns the path for non-x86 programs. To get the x86 program files directory on a non-x86 system, use the ProgramFilesX86 member.

However, it appears that using this member with `GetFolderPath` on x86 apps running on x64 systems (and presumably ARM) actually return the x86 program files folder, which does make sense. So perhaps the docs should be fixed to "On a non-x86 process/program"?

**Comment by sos-dll** [comment]
According to Win32 docs, this specific case is described as not supported.
In case anyone wants the "fix" for `Environment.GetFolderPath`; to still retrieve x64 program files with non-X86 flag in x86 process for x64 OS:
[Gist](https://gist.github.com/sos-dll/729faa104eadb94a2b21118261a4cc85).

**Comment by jkotas** [comment]
Anybody interested in submitting a PR for https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Environment+SpecialFolder.xml ?

**Comment by Gnbrkm41** [comment]
Closing as the PR fixing this issue has been merged.
