### ISSUE TITLE
build.cmd -vs System.Private.CoreLib fails to find the sln file

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#35738]
The `System.Private.CoreLib` project files are located inside `src\libraries\System.Private.CoreLib` just like the code of all the other Libraries projects, but the *.sln file is located in:

`src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.sln`

Please consider adding a special case to handle this solution whe executing this command, which currently fails to find the *.sln file:

```
D:\runtime> .\build.cmd -vs System.Private.CoreLib

D:\runtime\eng\build.ps1 : The term 'D:\runtime\eng\..\src\libraries\System.Private.CoreLib\System.Private.CoreLib.sln' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1
+ & 'D:\runtime\eng\build.ps1' -vs System.Private.CoreLib
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\runtime\eng\...ate.CoreLib.sln:String) [build.ps1], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,build.ps1
```

Low priority, since there is a workaround, but it would be nice not to have such a long command:

```
D:\runtime> .\build.cmd -vs src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.sln
```

**Comment by ViktorHofer** [comment]
Why do you need the -vs switch here? As it doesn't contain any tests that need to run on the live built shared framework, you can just open the solution directly.

Also if you really want to open it that way, you can pass in the full path.

**Comment by carlossanlop** [comment]
Oh right, it has no tests. I've been working with tests located somewhere else but didn't pay attention to that small but inportant requirement in this sln. Thanks, I think we can close this.
