### ISSUE TITLE
"./build.sh --subset" throw unbound variable error

### ISSUE THREAD

**Issue by hughbe** [dotnet/runtime#35769]
I wanted to list all the subsets, so I triedSteps to repro.
```
./build.sh --subset`
```

But I got an error:
```
/Users/hugh/Documents/GitHub/runtime/eng/build.sh: line 111: $2: unbound variable
```

Would be good to fix this

**Comment by hughbe** [comment]
Note I can repro this with a bunch of stuff, e.g.
```
./build.sh -arch
/Users/hugh/Documents/GitHub/runtime/eng/build.sh: line 115: $2: unbound variable
```

Not sure how to fix this as I'm not a very pro bash user :))

**Comment by ViktorHofer** [comment]
Thanks for reporting. https://github.com/dotnet/runtime/pull/35774 should fix it.
