### ISSUE TITLE
Cannot find AssemblyDependencyResolver

### ISSUE THREAD

**Issue by MeikelLP** [dotnet/runtime#35775]
I'm developing a library (netstandard 2.1) for my ASP.NET Core (netcore 3.1) app.

I can install the `System.Runtime.Loader` (4.3) nuget package but I am unable to use the `AssemblyDependencyResolver` but can use `AssemblyLoadContext`.

Am I doing something wrong?

SDK: 3.1.201

**Comment by jkotas** [comment]
AssemblyDependencyResolver is in netcore 3.1 only. It is not available in netstandard 2.1
