### ISSUE TITLE
System::ReadOnlySpan deprecated warning using C++/CLI

### ISSUE THREAD

**Issue by alberts2** [dotnet/runtime#35797]
Using System::ReadOnlySpan in a  C++/CLI library targeting .Net Core 3.1.201
`	bool XmlReader::LoadXml(const wchar_t* path)
	{
		return Reader->LoadXml(System::ReadOnlySpan<System::Char>((void*)path, wcslen(path)));
	}`
gives the following compilation warnings:
`1>------ Build started: Project: LibCave.Wrapper, Configuration: Debug Win32 ------
1>XmlReader.cpp
1>F:\source\repos\LibCave\LibCave.Wrapper\src\XmlReader.cpp(14,34): warning C4996: 'System::ReadOnlySpan<wchar_t>': was declared deprecated
1>F:\source\repos\LibCave\LibCave.Wrapper\src\XmlReader.cpp(14): message : see declaration of 'System::ReadOnlySpan'
1>F:\source\repos\LibCave\LibCave.Wrapper\src\XmlReader.cpp(14,60): warning C4996: 'System::ReadOnlySpan<wchar_t>::ReadOnlySpan': was declared deprecated`

I am using Visual Studio 2019 version 16.5.4.

**Comment by jkotas** [comment]
Managed C++ does not support ref structs. 

Could you please reopen this issue at https://developercommunity.visualstudio.com/ ? It is the right place to provide feedback for managed C++.

**Comment by alberts2** [comment]
> Managed C++ does not support ref structs.
> Could you please reopen this issue at https://developercommunity.visualstudio.com/ ? It is the right place to provide feedback for managed C++.

Thanks! I wasn't aware that C++ does not support C# ref structs and opened a issue at https://developercommunity.visualstudio.com/content/problem/1017965/systemreadonlyspan-deprecated-warning-using-ccli.html
