### ISSUE TITLE
Use AMP from .NET (or equivalent)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#358]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/472864/use-amp-from-net-or-equivalent.html)._

---
<p>Beeing able to write code to do GPGPU from c# using c# syntax without doing explicit marshalling and calling C++/CLI dlls </p>

---
#### Jane Wu [MSFT] on 3/1/2019, 01:06 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jkotas** [comment]
Multiple solutions for this exist in the .NET ecosystem:

http://www.ilgpu.net/
http://www.quantalea.com/

**Comment by joperezr** [comment]
Closing this per @jkotas comment above and the lack of activity.
