### ISSUE TITLE
Move host customization logic into Microsoft.NET.HostModel

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#3580]
Currently, all of the code to customize the AppHost and COM Host are in the dotnet/sdk repo. As as result, we currently don't have an easy dev-loop for testing the customization code in this repo where we build the hosts.

As part of the bundler work, we created the `Microsoft.NET.HostModel` package, which we flow through over to the dotnet/sdk repo for them to consume. This allows the bundler work to live in the same repo as the apphost that the bundler works with.

We should move the AppHost and COM Host customization logic into the `Microsoft.NET.HostModel` package living in this repo and change the tasks in the SDK to consume them.

cc: @nguerrera @AaronRobinsonMSFT @vitek-karas

**Comment by elinor-fung** [comment]
@jkoritzinsky you did this for [comhost](https://github.com/dotnet/core-setup/pull/8293) and @swaroop-sridhar did this for [apphost](https://github.com/dotnet/core-setup/pull/6831), right? Is there any remaining work being tracked here?

**Comment by jkoritzinsky** [comment]
This work has all been completed.

**Comment by jkoritzinsky** [comment]
I guess we can add a feature request for https://github.com/dotnet/runtime/issues/3580#issuecomment-490251603

I'll open an issue in dotnet/runtime for it if I can find the place in `dotnet tool install` that would use it.

**Comment by jkoritzinsky** [comment]
Looks like the API in that comment was also completed, so this issue is 100% complete.
