### ISSUE TITLE
Running tests - outdated instructions.

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#35801]
@ViktorHofer 

The file "https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md" did not get updated instructions for running tests.

**Comment by ViktorHofer** [comment]
@mrj001 what updates are you missing?

**Comment by mrj001** [comment]
@ViktorHofer 
Shouldn't it be updated to show how to test the libraries with ```dotnet test``` instead of build.cmd/sh?

**Comment by ViktorHofer** [comment]
I haven't upgraded the docs for that yet as the existing test target can still be used. I would say that even though `dotnet test` is working now in master it's still an experimental feature. I plan to update the docs after I made sure that everything works correctly with `dotnet test` (probably in a week).

**Comment by ViktorHofer** [comment]
Closing as the current docs are working fine. We will update the docs when we remove xunit.console support: https://github.com/dotnet/runtime/issues/37953
