### ISSUE TITLE
Timeouts on HttpClient Factory on Linux

### ISSUE THREAD

**Issue by Nonary** [dotnet/runtime#35809]
This issue that was closed 18 days ago I believe is the same problem: https://github.com/dotnet/runtime/issues/33280

I am currently using the HttpClientFactory via dependency injection as outlined in this article:
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

It appears to have no issues when running locally on my machine, but as soon as I put this under the .net core 3.1 runtime docker image provided by Microsoft, I get several "System.Threading.Tasks.TaskCanceledException" in my log because the client terminated its connection to the server (after 30 seconds, which is the default for most clients).

When enabling trace logs, I see that sometimes when the HttpClient is sending a request, it never finishes. After 100 seconds it will then throw the exception (typically the TaskCancelled, because the client terminated it).

After some suggestions on other issues, I configured the SocketHttpHandler to false, it immediately fixed the problem.
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.1

I believe there is some underlying bug with the new handler that is causing requests to timeout, since the problem goes away when I change the setting to false.

**Comment by scalablecory** [comment]
This points to a possible network/docker config issue, be need more info to be sure. 

Can you please provide some stack traces, code to reproduce, and anything additional? You might also try running [dotnet trace](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md) to listen to the various [System.Net providers](https://github.com/dotnet/runtime/blob/master/docs/workflow/debugging/libraries/windows-instructions.md#systemnet-namespaces).

**Comment by Nonary** [comment]
Hi @scalablecory, after running some testing on a different network I would agree that this is a network issue of some type.

Is there any technical details I can suggest to my network team to why it works with that switch turned off vs on? I am not sure how I can describe the issue to them on the technicalities of the default handler.

**Comment by karelz** [comment]
As we do not have actionable repro or something for us to investigate, I am closing it.
It would be ideal to have docs on troubleshooting network issues, etc. -- we will try it in 5.0.

**Comment by vproxy666** [comment]
I am encountering the same issue.  Same code works fine on Windows, but encounter error when accessing same server from linux docker container (the microsoft image)
