### ISSUE TITLE
Make corerun easier to debug in case of initialization failure

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#35814]
In my PR https://github.com/dotnet/runtime/pull/35684, a couple of things are identified that we could do to make `corerun` easier to work with in case the runtime fails to initialize.

We can consider them in the future.

**Comment by vitek-karas** [comment]
@cshung Could you please write the proposed improvements into the issue? It's hard to track down what you mean by looking at a PR (and it's easier for everybody else to see what this is about).

**Comment by cshung** [comment]
The proposed improvements are:

If the runtime initialization failed:
- Use initialization failure HR as the exit code for the unix corerun, and
- Output something meaningful to the console
