### ISSUE TITLE
GetAllNetworkInterfaces fails on Android

### ISSUE THREAD

**Issue by pjcollins** [dotnet/runtime#35836]
`System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces ()`
is crashing on Android when using our very early Xamarin SDK preview bits:

```
05-05 10:49:44.065 31222 31222 E AndroidRuntime: Process: UnnamedProject.UnnamedProject, PID: 31222
05-05 10:49:44.065 31222 31222 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Net.NetworkInformation.NetworkInformationException (2): No such file or directory
05-05 10:49:44.065 31222 31222 E AndroidRuntime:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
05-05 10:49:44.065 31222 31222 E AndroidRuntime:    at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces()
05-05 10:49:44.065 31222 31222 E AndroidRuntime:    at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
05-05 10:49:44.065 31222 31222 E AndroidRuntime:    at UnnamedProject.MainActivity.<>c.<OnCreate>b__1_0(Object <p0>, EventArgs <p1>)
```

### Steps to Reproduce

1. Ensure you have a recent .NET 5 preview build installed.
2. Download the repro here: [BuildXASdkProjectFalse.zip](https://github.com/dotnet/runtime/files/4581507/BuildXASdkProjectFalse.zip)
3. Run the sample and click the button.
```
dotnet build /t:Run ~/Downloads/BuildXASdkProjectFalse/UnnamedProject.csproj /v:n
```

This project is configured to run on an `x86` emulator by default. If you want to test on a physical device the `RuntimeIdentifier` element in the .csproj file will need to be updated.

**Comment by EgorBo** [comment]
@pjcollins can this happen because networking capabilities are not specified in the AndroidManifest?

**Comment by wfurt** [comment]
Is the /proc available like normal Linux? The NetworkInfo code heavily depends on it and we have seen similar cases on the past with WSL when some entries are missing or incomplete. 

Also this looks like unhandled exception more than crash.

**Comment by steveisok** [comment]
This looks like something we'll need to resolve similar to our HttpHandler integration.  In mono, we were reaching into Xamarin libraries we won't have access to.

**Comment by pjcollins** [comment]
@steveisok To provide a quick update here, this issue is still present in 6.0.0-preview.4.21177.4.

**Comment by steveisok** [comment]
Related to https://github.com/dotnet/runtime/issues/51303

**Comment by wfurt** [comment]
can you check @steveisok what file it is trying to access  and if we are hitting the "getifaddrs" path or the legacy /proc implementation? 
I'm wondering if we are hitting the second because some header or detection issue during configuration.

**Comment by wfurt** [comment]
https://github.com/morristech/android-ifaddrs is 8 years old and I'm wondering if anything changed since then. Netlink now works (somehow) with .NET so we _could_ do something similar if needed. That would possibly allow some other NetworkInfo functions as well if needed.

**Comment by wfurt** [comment]
https://android.googlesource.com/platform/bionic/+/master/libc/include/ifaddrs.h
makes comment about API level 24. Can we use it and throw PNSP on older versions?

**Comment by marek-safar** [comment]
Closing this in favour of #51303
