### ISSUE TITLE
unable to generate code coverage report for libraries

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#35843]
Built as follows:
```
$ git clean -xdf
$ git pull upstream master
$ ./build.cmd -subset clr -c Checked
$ ./build.cmd -subset Libs+Libs.Tests -runtimeConfiguration Checked
$ ./build.cmd Libs.Tests -test -coverage -runtimeConfiguration Checked
```
This is the final part of the output:

>   2020-05-05T08:09:25: Executable: C:\Users\mrj00\.nuget\packages\dotnet-reportgenerator-globaltool\4.5.2\tools\netcoreapp3.0\any\ReportGenerator.Core.dll
>   2020-05-05T08:09:25: Working directory: C:\Users\mrj00\source\repos\runtime\src\libraries
>   2020-05-05T08:09:25: The report file pattern 'C:\Users\mrj00\source\repos\runtime\artifacts\bin\*.Tests\*\coverage.opencover.xml' is invalid. No matching files found.
>   2020-05-05T08:09:25: No report files specified.
> C:\Users\mrj00\source\repos\runtime\eng\testing\coverage.targets(51,5): error MSB3073: The command ""C:\Users\mrj00\source\repos\runtime\.dotnet\dotnet.exe" tool run reportgenerator "-reports:C:\Users\mrj00\source\repos\runtime\artifacts\bin\*.Tests\*\coverage.opencover.xml" "-targetdir:C:\Users\mrj00\source\repos\runtime\artifacts\coverage" "-reporttypes:Html" "-verbosity:Info"" exited with code 1. [C:\Users\mrj00\source\repos\runtime\src\libraries\tests.proj]
> 
> Build FAILED.
> 
> C:\Users\mrj00\source\repos\runtime\eng\testing\tests.targets(96,5): error : One or more tests failed while running tests from 'System.Runtime.InteropServices.Tests'. [C:\Users\mrj00\source\repos\runtime\src\libraries\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
> C:\Users\mrj00\source\repos\runtime\eng\testing\coverage.targets(51,5): error MSB3073: The command ""C:\Users\mrj00\source\repos\runtime\.dotnet\dotnet.exe" tool run reportgenerator "-reports:C:\Users\mrj00\source\repos\runtime\artifacts\bin\*.Tests\*\coverage.opencover.xml" "-targetdir:C:\Users\mrj00\source\repos\runtime\artifacts\coverage" "-reporttypes:Html" "-verbosity:Info"" exited with code 1. [C:\Users\mrj00\source\repos\runtime\src\libraries\tests.proj]
>     0 Warning(s)
>     2 Error(s)
> 
> Time Elapsed 01:36:38.46
> Build failed.
> Some builds failed:
>         Configuration: Debug, Architecture: x64
> 
>
As there are 251 files named "testResults.xml", and no files named "coverage.opencover.xml", it looks like this last step is the problem.

HEAD is at 7ddda11a7ab.

**Comment by safern** [comment]
> C:\Users\mrj00\source\repos\runtime\artifacts\bin*.Tests*\coverage.opencover.xml

It seems like we're missing a `\` after `artifacts\bin`. 

We use `ArtifactsBinDir` property for that, I thought that one had a trailing backslash:
https://github.com/dotnet/runtime/blob/b9467c8823cea979dcd735bcb402da96a1b654c1/src/libraries/tests.proj#L8

**Comment by ViktorHofer** [comment]
I'll look into this. Just a minor nit, you can simplify your command:

```
$ git clean -xdf
$ git pull upstream master
$ ./build.cmd clr+libs -rc Checked
$ ./build.cmd libs.tests -rc Checked -test -coverage
```

**Comment by ViktorHofer** [comment]
I don't understand why `$(ArtifactsBinDir)` doesn't contain the final backslash but I found the other issues. I will submit a fix and an update for the docs tomorrow after the net5.0 change is in and will update this thread.

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/runtime/commit/85bfbfcf5451463d285fd1ccd0b3ac0d8be7b949
