### ISSUE TITLE
X509Certificate2.Import hangs on some .der files

### ISSUE THREAD

**Issue by gfs** [dotnet/runtime#35856]
# Issue Title

Calling `X509Certificate2.Import(string Filename)` or `X509Certificate2.Import(byte[] FileContents)` with certain .der files hangs and never returns.

# General

.Net Core 3.1.201
Mac OS 10.15.4

Here's the line of code that it is hanging on: https://github.com/microsoft/AttackSurfaceAnalyzer/blob/7e77e4d81a344f26ee474155bedcd57330046441/Lib/Collectors/FileSystemCollector.cs#L109

You can also reproduce on ASA 2.2.18: 
`dotnet tool install -g Microsoft.CST.AttackSurfaceAnalyzer.CLI --version 2.2.18-beta-g24764cf0b8`
`asa collect -f --directories /path/to/the/attached/certificate --verbose`

Here's the example file it is hanging on: [publicKey.der.zip](https://github.com/dotnet/core/files/4583349/publicKey.der.zip)

It is a public key certificate installed by XCode at `/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RTCReporting.framework/publicKey.der`

**Comment by bartonjs** [comment]
This can't be .NET Core 3.1, because X509Certificate.Import isn't available on .NET Core:

https://github.com/dotnet/corefx/blob/c07c7917ec0e6ecc734131a39a43e44c0142f59d/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs#L532-L562

Is this perhaps Mono?

FWIW, that file is an RSA public key, not a certificate.

**Comment by gfs** [comment]
Sorry. I see the confusion. I'm actually doing. 

```csharp
using var certificate = new X509Certificate2();
certificate.Import(Path);
```

**Comment by vcsjones** [comment]
> Here's the example file it is hanging on: publicKey.der.zip

The attached file is not an X509 certificate, it is an RSA PKCS1 key. You would import this as an `RSA` object using [`ImportRSAPublicKey`][1].

I wasn't able to reproduce a hang on macOS 10.15.4 with that file. This code:

```csharp
var key = File.ReadAllBytes("/Users/kjones/Downloads/publicKey.der");
var cert = new X509Certificate2();
cert.Import(key);
```

Results in the Exception (both for the `string` and `byte[]` overloads of `Import`):

> Unhandled exception. System.PlatformNotSupportedException: X509Certificate is immutable on this platform. Use the equivalent constructor instead.
   at System.Security.Cryptography.X509Certificates.X509Certificate.Import(Byte[] rawData)

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.importrsapublickey?view=netcore-3.1

**Comment by gfs** [comment]
> FWIW, that file is an RSA public key, not a certificate.

I'm trying to scan the whole system for certificates so I am passing in every .der file.

**Comment by vcsjones** [comment]
Sorry; didn't realize @bartonjs beat me to it.

> I'm actually doing `certificate.Import(Path);`

That should still be throwing an `System.PlatformNotSupportedException` on macOS. A new `X509Certificate2` using the appropriate constructor should be used instead.

> I'm trying to scan the whole system for certificates so I am passing in every .der file.

It shouldn't hang, but a `.der` extension does not necessarily mean it is a certificate. Just some "DER-encoded" thing like an RSA key, X509 certificate, etc.

**Comment by gfs** [comment]
> That should still be throwing an System.PlatformNotSupportedException on macOS. A new X509Certificate2 using the appropriate constructor should be used instead.

Thanks. This is what was happening. I was not catching PlatformNotSupportedException.

**Comment by gfs** [comment]
As an aside. The documentation does not indicate this can throw PlatformNotSupported. https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.import?view=netcore-3.1#System_Security_Cryptography_X509Certificates_X509Certificate2_Import_System_Byte___
