### ISSUE TITLE
Add diagnostic for Dictionary.ContainsKey when used in an ? statement.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#35854]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID
None yet that I know of. I would like one added that lets users know that ``Dictionary.ContainsKey(key) ? Dictionary[key] : null`` is a double lookup and can be simplified to ``Dictionary.TryGetKey(key, out var value) ? value : null``. Because of the lack of a diagnostic for this I did not know about it according to my usage on it.

#### Repro steps

1. Well it is as simple as writing a dictionary that checks for if keys are added and wanting to get the value, and if it has no value return null on the method / statement like I wrote above.
2. Notice that currently no diagnostic is reported to the user so they could reduce the amount of lookups and increase performance hits.

#### Expected behavior
A diagnostic for this that alerts the user of the possible performance hits from this example above.

#### Actual behavior
No diagnostic explaining all of this is reported. Probably because there is none yet that exists?

**Comment by AraHaan** [comment]
Any updates on this one?

**Comment by jeffhandley** [comment]
Hi @AraHaan. Thanks for filing this suggestion. This has been tagged to be considered as a possible future analyzer that we could implement. We've already selected the analyzers we're investing in for .NET 5 though, so this is marked as Future. We will need to further review this analyzer concept before we can mark it as approved though, and I don't yet have a timeline for when we'll be reviewing the backlog for planning beyond .NET 5.

If you would be interested in thinking through possible call site samples, showing those possible scenarios and edge cases, and illustrating with code snippets, that would help us though, and we then might even be able to mark this as up-for-grabs.

Thanks!

**Comment by stephentoub** [comment]
Isn't this a dup of https://github.com/dotnet/runtime/issues/33798?

**Comment by AraHaan** [comment]
oh shoot ye you are right it is possible a duplicate.

**Comment by layomia** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/33798.
