### ISSUE TITLE
LinqToObjects "Single" throws Sequence contains more than one matching element - even though it does not

### ISSUE THREAD

**Issue by kvinther** [dotnet/runtime#35861]
## Background
*Hi. I am a bit anxious to report this, as Linq to me always has been the definition of rock solid!*

I have a simple class with some static data in an array and a public GetById method. Each item in the array is a simple POCO with an interger Id and some other int/enum properties. The Ids run from 1..48, with no duplicates.

```csharp
public static class GameData
{
    private static readonly Domino[] Dominos;

    public static Domino[] GetDominos() => Dominos;

    static GameData()
    {
        Dominos = new[]
        {
            new Domino(1, /*other params*/),
            new Domino(2, /*other params*/),
            new Domino(3, /*other params*/),
            new Domino(4, /*other params*/),
            new Domino(5, /*other params*/),
            new Domino(6, /*other params*/),
            // and so on...
        };
    }

    public static Domino GetDominoById(int dominoId) => Dominos.Single(x => x.Id == dominoId);
}
```

## Issue
After my program has run for a while, I run into an exception stating that *"Sequence contains more then one matching element."* However, looking in the Immediate window, I perform the exact same operation ```sequence.Single(x => x.Id == id)``` - and here I get the expected result...

The image below is taken from Visual Studio 2019 at the time of the exception.

![image](https://user-images.githubusercontent.com/4615024/81118402-0e9fb480-8f29-11ea-8cc0-0ed262898a11.png)

## How to reproduce
I have not been able to reproduce this error by any other means, than running my applicaiton. That there should be a "bug" in ```.Single``` seems quite far fetched to me, but I am at a loss as how to explain the above.

## Framework
Microsoft.NETCore.App 2.2.0
NETStandard.Library 2.0.3
Visual Studio Professional 2019 v16.5.2

**Comment by stephentoub** [comment]
Sounds like you have a race condition, where whatever `sequence` is has changed by the time you examine it in Visual Studio.

**Comment by kvinther** [comment]
> Sounds like you have a race condition, where whatever `sequence` is has changed by the time you examine it in Visual Studio.

In my case the sequence is a readonly array initialized once in a static constructor. So you may be right, but the change would then need to come from "outside" my code, I guess.

**Comment by stephentoub** [comment]
It could also be one of the closed-over values in the delegate, or the objects in the array, or some such thing. The chance that this is a bug in LINQ is very small.

**Comment by kvinther** [comment]
Yeah. My thoughts exactly. I am experimenting further.

**Comment by kvinther** [comment]
@stephentoub I think you are right about the race condition thing. I will close this issue.
