### ISSUE TITLE
ComWrappers do not respect interface IID when used for marshalling 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#35883]
See https://github.com/dotnet/corert/issues/4219#issuecomment-624461282 for details

**Comment by AaronRobinsonMSFT** [comment]
As mentioned in the above bug there is an issue at:

https://github.com/dotnet/runtime/blob/a4c050ebf45a9745e2941863a8d7ae9c70ee88b2/src/coreclr/src/vm/interopconverter.cpp#L465-L473

There is also another instance of the same issue lurking higher in the file:

https://github.com/dotnet/runtime/blob/a4c050ebf45a9745e2941863a8d7ae9c70ee88b2/src/coreclr/src/vm/interopconverter.cpp#L176-L198
