### ISSUE TITLE
SOS_README.md NOT FOUND

### ISSUE THREAD

**Issue by evan-choi** [dotnet/runtime#35888]
### How to get rid of file SOS_README.md?
Can't find any info on how to achieve that.

### General
Every time we compile project based on core 3.1, this file appears.
If i delete file, application don't work.
Maybe it tells that we are missing something important?

![image](https://user-images.githubusercontent.com/9690415/81163346-92a97900-8fc9-11ea-8ba8-b359b4300f99.png)

**Comment by hoyosjs** [comment]
@mikem8361 we might need to port to 3.1...

**Comment by joperezr** [comment]
Can you give exact repro steps (includding how you publish) so that we can evaluate what is going on? My hunch is that there must be an entry for this file in the runtimeconfig file but it would be good to repro it so that we can fully understand.

**Comment by hoyosjs** [comment]
@joperezr there is an entry in the dependency list. It gets shipped in the 3.1 shared framework and results in the asset manifests, so it gets published and added, even though it was only meant as an informational readme. Excluding it in 3.1 got rejected by ship room

**Comment by joperezr** [comment]
I see, has this been addressed for 5.0?

**Comment by hoyosjs** [comment]
Yes, this is no longer an issue in 5.0

**Comment by joperezr** [comment]
Ok, given that and the fact we won't fix this for 3.1 I'll go ahead and close this for now.
