### ISSUE TITLE
Infrastructure - Rollout (June 2020)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#35895]
# Overview

We'll use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. The change will merged on the first Monday of the month.

| Change |  Impact | Assignee |
| --- | --- | --- | 
|https://github.com/dotnet/runtime/pull/34757|The minimum cmake version for building is bumped to 3.14.5 from 3.14.2 for Linux|@akoeplinger|

## Archive
- [May 2020](https://github.com/dotnet/runtime/issues/35202)
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/pull/34757 was merged.
