### ISSUE TITLE
typeof(T).IsValueType isn't resolved to a constant

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#35897]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHuGueBtAMoALbFAAOAGWzAAdACUArgDsMAS3wxZAKTUYA4jGUwoasAAoMAT3EwIAM3NrVAShcBdPt3oNgECAA2DACSuABq2AEAKjYwADxRAHzmLgwAvIkM1rYO5lEusqERAYowMbYA3DQAvkA===

It can always be resolved to a constant as of course in reference type shared generics, is it always false. Would be useful for optimising `Span<T>(T[])` and `Memory<T>(T[])` in particular

**Comment by samsosa** [comment]
Like this: https://github.com/dotnet/runtime/pull/1157 ?

:-D

**Comment by john-h-k** [comment]
.......not sure how i missed that, oops
