### ISSUE TITLE
dotnet test doesn't filter projects

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#35891]
Invoking `dotnet test -f net5.0` on `src\libraries\tests.proj` doesn't filter out projects which aren't applicable like `Microsoft.Diagnostics.Tracing.EventSource.Redist.Tests.csproj` (which doesn't have a configuration for `net5.0`). It tries to restore and build the project for `net5.0`.

cc @Anipik @ericstj

**Comment by Anipik** [comment]
It might be a side effect of this https://github.com/dotnet/sdk/issues/11305

**Comment by ViktorHofer** [comment]
I don't think this is related as there is no explicit target in the above command.

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/runtime/commit/809a06f45161ae686a06b9e9ccc2f45097b91657
