### ISSUE TITLE
Build should set PRERELEASE=0 in release/* branches

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#35903]
Related: https://github.com/dotnet/coreclr/pull/23436

The _release/*_ branches (even for previews) should set `PRERELEASE=0` so that we're not building anything in there that we don't intend to ship. There are still some features in _master_ that aren't yet ready for prime time and are conditioned on the flag `PRERELEASE=1` being set.

https://github.com/dotnet/runtime/blob/4d3b5e556ea51a5ba108e95d6fdfeb8471569f9e/eng/native/configureplatform.cmake#L4-L6

https://github.com/dotnet/runtime/blob/a1af15d229c44f72d639c686a66a621196fd4172/Directory.Build.props#L63-L65

**Comment by ericstj** [comment]
@GrabYourPitchforks this means those features would never be in packages shipped to nuget.org.  Is that your intent?

@Anipik let's clarify what to do here and see if we can make it happen in Preview5.

**Comment by jkotas** [comment]
> this means those features would never be in packages shipped to nuget.org

Yes, that's the intent.
