### ISSUE TITLE
Cannot Deserialize into Nested Class

### ISSUE THREAD

**Issue by tlbaxter** [dotnet/runtime#35921]
I have a class structure like this:

public class A {
   // some stuff....
   public class B {
      // some more stuff...
   }
}

If I have a json string I should, I think, be able to do this:

A.B ab = JsonSerializer.Deserialize<A.B>(someJsonString);

The ab variable is not populated. If I move B outside of A. It works. Why is this?

**Comment by layomia** [comment]
It seems like you want an API to deserialize into an existing object. Can you see if https://github.com/dotnet/runtime/issues/29538 expresses your ask? Please feel free to re-open if not.

**Comment by tlbaxter** [comment]
> It seems like you want an API to deserialize into an existing object. Can you see if #29538 expresses your ask? Please feel free to re-open if not.


Please re-open. Issue [#29538 ](https://github.com/dotnet/runtime/issues/29538)has nothing to do with what i am talking about.

**Comment by layomia** [comment]
My mistake. I see you opened https://github.com/dotnet/runtime/issues/35957. Thanks.
