### ISSUE TITLE
Can't find compatible framework message should specify x86/x64 on Windows

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#3592]
See dotnet/runtime#3589 for details.
On Windows there are two sets of frameworks: 32bit and 64bit. The "can't find framework" message doesn't include anything which would specify which of the two were used to try to find the framework.

It might be also worth it to include all the paths which were probed in order to find the framework in question.

**Comment by elinor-fung** [comment]
https://github.com/dotnet/runtime/pull/57150 added architecture information.
https://github.com/dotnet/runtime/pull/67022 added the .NET location where the host looked for the framework.
