### ISSUE TITLE
UnmanagedCallersOnlyAttribute returning non-primitive value types do not work

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#35928]
```
[UnmanagedCallersOnly]
static Vector2 MyCallback() { ... }
```

Expected: works fine
Actual: fails

More context: https://github.com/dotnet/runtime/pull/35926#discussion_r421165727

**Comment by jkoritzinsky** [comment]
Since this depends on a fix for https://github.com/dotnet/runtime/issues/12375 and #39294 isn't going to make .NET 5, I'm going to move this to .NET 6.

**Comment by vargaz** [comment]
How is this going to work without marshal attributes ?

**Comment by jkoritzinsky** [comment]
The returned value type must be a blittable value type. As a result, it doesn’t require marshalling and the marshal attributes aren’t needed.
