### ISSUE TITLE
Add ICU App-Local tests

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#35930]
We need to add tests by building a NuGet package in runtime-assets containing ICU and validating that everything works fine.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/pull/35383
#826

**Comment by mjsabby** [comment]
Any updates here?

Also it would be good to ensure that `vcpkg` built ICU libraries can be consumed by this functionality.

**Comment by safern** [comment]
Not yet @mjsabby — it is the next item on my priority list. Will be working on this next week.

**Comment by safern** [comment]
@tarekgh ill try to get this in the next days if I can't get it on Friday I'll re-adjust to 6.0.0

**Comment by tarekgh** [comment]
@safern I moved this to 7.0. let me know if you think otherwise.
