### ISSUE TITLE
WildCard doesn't work when transform XSLT in .net core 

### ISSUE THREAD

**Issue by yuqi0207** [dotnet/runtime#35932]
Recently we are working on .net core migration from .net framework. We use XSLT to generate the final HTML file. During migration, we found there’s some behavior changed between .net framework and .net core 3.1.
 
In .net framework, we can select a xpath with wildcard * starting with a parameter navigator, below $Locale is param added dynamically. But in .net core, it throw exception when doing transform with exception ("Object reference not set to an instance of an object"), Only If I give full path, it works. looks it don’t think the * is wildcard character. I search answer online but don’t find any clue. 
 
XSLT file

`  <xsl:template match="/">
    <HTML>
      <HEAD>
        <TITLE>
          <xsl:apply-templates select="$Locale/root/Localizations/*/Config/Subject">
            <xsl:with-param name="curNodeIndex" select="$Locale/root/Localizations/*/Config/Subject" />
          </xsl:apply-templates>
        </TITLE>
      </HEAD>
      <Body>
        test test
      </Body>
    </HTML>
  </xsl:template >
`
`<xsl:for-each select="$Locale/root/Localizations/GlobalHeader/SideBar/*">`
C# code

`           
            // Load the style sheet.

            XslCompiledTransform xslt = new XslCompiledTransform();
            XDocument transform = XDocument.Load("Transform.xslt");
 
            XName param = transNs + "param";
 
            transform.Root.Add(
                new XElement(param,
                    new XAttribute("name", "Locale")));
 
            xslt.Load(transform.CreateReader());
            var argList = new XsltArgumentList();
 
            XDocument payload  = XDocument.Parse(@"");
 
            XDocument template = XDocument.Load("PasswordChange_Content_en.xml");
            argList.AddParam("Locale", string.Empty, template.CreateNavigator());
 
            // Execute the transform and output the results to a file.
            using (var stringWriter = new StringWriter(System.Globalization.CultureInfo.CurrentCulture))
            {
                using (XmlWriter xmlWriter = new XmlTextWriter(stringWriter))
                {
                    try
                    {
                        xslt.Transform(payload.CreateNavigator(), argList, xmlWriter);
                       var res = stringWriter.ToString();
                    }
                    catch (Exception e)
                    {
                        throw;
                    }
                }
            }
`
Exception:
 
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Private.Xml.Linq
  StackTrace:
   at System.Xml.XPath.XNodeNavigator.MoveToNext(XPathNodeType type)
   at System.Xml.Xsl.Runtime.XmlNavTypeFilter.MoveToNextContent(XPathNavigator navigator)
   at System.Xml.Xsl.Runtime.ContentMergeIterator.MoveNext(XPathNavigator input, Boolean isContent)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlSequenceWriter results)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer)
   at System.Xml.Xsl.XslCompiledTransform.Transform(IXPathNavigable input, XsltArgumentList arguments, XmlWriter results, XmlResolver documentResolver)
   at System.Xml.Xsl.XslCompiledTransform.Transform(IXPathNavigable input, XsltArgumentList arguments, XmlWriter results)
   at XSLTTestCore.Program.Main(String[] args) in D:\[D]Project\TestCSharp\XSLTTestCore\XSLTTestCore\Program.cs:line 61

**Comment by buyaa-n** [comment]
It doesn't seem we will be able to fix this within 5.0, so moving to 6.0, @krwq if you have the fix ready feel free to move back to 5.0

**Comment by MOZGUI** [comment]
Every second stylesheet contains "*".
This means half of the stylesheets will not work in .net core
Looks like Microsoft won't see xslt

**Comment by krwq** [comment]
@yuqi0207 or @MOZGUI can you provide full project with repro? I think the XSLT in the repro is a bit broken, also there is no corresponding XML file to transform.

**Comment by MOZGUI** [comment]
Good news,
It really works on .NET 5. I'm happy!

            XDocument xDoc = XDocument.Parse("<root><element>1</element><element>2</element></root>");
            var elements = xDoc.XPathSelectElements("//*").ToList();
            foreach (var element in elements)
            {
                //worked
            }

            XslCompiledTransform xsltCompiledTransformation = new XslCompiledTransform();

            XDocument xslt = XDocument.Parse(@"<?xml version='1.0' encoding='UTF-8'?>"+
            "<xsl:stylesheet version='2.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:fn='http://www.w3.org/2005/xpath-functions'>"+
	            "<xsl:output method='xml' version='1.0' encoding='UTF-8' indent='yes'/>"+
	            "<xsl:template match='*'>"+
		            "<xsl:copy>"+
			            "<xsl:apply-templates select='.//*'></xsl:apply-templates>"+
		            "</xsl:copy>"+
	            "</xsl:template>"+
            "</xsl:stylesheet>");
            
            xsltCompiledTransformation.Load(xslt.CreateReader());

            XDocument resultDoc = new XDocument();
            using (XmlWriter newDocumentWriter = resultDoc.CreateWriter())
            {
                xsltCompiledTransformation.Transform(xDoc.CreateNavigator(), new XsltArgumentList(), newDocumentWriter);
            }
           //worked

**Comment by krwq** [comment]
@yuqi0207 @MOZGUI given this is fixed in 5.0 I'll close the bug, please re-open if you feel there is anything left
