### ISSUE TITLE
JSON Deserialization (using System.Text.Json) in Nested Class Fails

### ISSUE THREAD

**Issue by tlbaxter** [dotnet/runtime#35957]
I'm new here so forgive me if I am not doing something right.

We're using Core v3.1 and trying to deserialize a small bit of JSON. I have this simple class structure, where we are trying to deserialize into `A.B`.

```
public class A {
   public class B {
      // some public properties
   }
}
```

When I try to deserialize into `A.B` I get an empty object with only default values. Neither of these work:

```
A.B ab_1 = JsonSerializer.Deserialize(someJson, typeof(A.B));
A.B ab_2 = JsonSerializer.Deserialize<A.B>(someJson);
```

If I remove the `B` class from its nesting and make it "stand-alone" I can deserialize into it just fine. Should I not be able to deserialize into `A.B`?

**Comment by Symbai** [comment]
#30083

**Comment by tlbaxter** [comment]
@Jozkee : PLEASE CLOSE THIS ISSUE. MY MISTAKE.

**Comment by layomia** [comment]
I couldn't repro this: https://dotnetfiddle.net/49ylUD. @tlbaxter is this why you want the issue closed?

**Comment by tlbaxter** [comment]
@layomia -- Yes, I made a mistake. So sorry to have wasted your time.

**Comment by layomia** [comment]
@tlbaxter, no worries.
