### ISSUE TITLE
URI ctor decodes URI-encoded URL string

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#35971]
Comes from PowerShell repo https://github.com/PowerShell/PowerShell/issues/10871

```powershell
[System.Uri]"https://localhost/ingest/jg1798/07%2F1798-07-25.xml"

AbsolutePath   : /ingest/jg1798/07%2F1798-07-25.xml
AbsoluteUri    : https://localhost/ingest/jg1798/07%2F1798-07-25.xml
LocalPath      : /ingest/jg1798/07/1798-07-25.xml
Authority      : localhost
HostNameType   : Dns
IsDefaultPort  : True
IsFile         : False
IsLoopback     : True
PathAndQuery   : /ingest/jg1798/07%2F1798-07-25.xml
Segments       : {/, ingest/, jg1798/, 07%2F1798-07-25.xml}
IsUnc          : False
Host           : localhost
Port           : 443
Query          :
Fragment       :
Scheme         : https
OriginalString : https://localhost/ingest/jg1798/07%2F1798-07-25.xml
DnsSafeHost    : localhost
IdnHost        : localhost
IsAbsoluteUri  : True
UserEscaped    : False
UserInfo       :
```

As you see `LocalPath` is broken. As result ToString() returns the broken string too.

**Comment by wfurt** [comment]
cc: @MihaZupan

**Comment by MihaZupan** [comment]
> As you see LocalPath is broken

Uri unescapes percent-encoded sequences for LocalPath. Why shouldn't it do so in this case?

Related: #23738

**Comment by iSazonov** [comment]
> Why shouldn't it do so in this case?

From LocalPath docs https://docs.microsoft.com/en-us/dotnet/api/system.uri.localpath?view=netcore-3.1
> Gets a local operating-system representation of a file name.

In the example a file name is `07%2F1798-07-25.xml`, not `1798-07-25.xml`.

**Comment by iSazonov** [comment]
PowerShell uses the Uri in `HttpRequestMessage` so maybe the issue is there.

**Comment by MihaZupan** [comment]
It also states that `The value returned by this property is unescaped.` If `%2F` were meant as a literal, it's arguable that the percent sign should have been encoded as `%25`.

```c#
new Uri("https://a/foo%2Fbar").LocalPath
/foo/bar

new Uri("https://a/foo%252Fbar").LocalPath
/foo%2Fbar
```

**Comment by MihaZupan** [comment]
The linked issue is making a web request. I would assume PathAndQuery is accessed there, not LocalPath.

I don't know if PowerShell does any more processing on the uri string, but Uri itself keeps the uri escaped for PathAndQuery and AbsoluteUri.

```c#
Uri uri = new Uri("https://localhost/ingest/jg1798/07%2F1798-07-25.xml");

uri.PathAndQuery;
// /ingest/jg1798/07%2F1798-07-25.xml

uri.AbsoluteUri;
// https://localhost/ingest/jg1798/07%2F1798-07-25.xml
```

**Comment by iSazonov** [comment]
PowerShell code https://github.com/PowerShell/PowerShell/blob/f4382202ae4622bf26795e29a7b39b9d7cdfb3fb/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1054
and 
https://github.com/PowerShell/PowerShell/blob/f4382202ae4622bf26795e29a7b39b9d7cdfb3fb/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L722

I don't that PowerShell changes the Uri - it send the Uri as-is in HttpRequestMessage

**Comment by MihaZupan** [comment]
As far as I can see, HttpClient is used to make the request. HttpClient will access PathAndQuery, not LocalPath.

HttpClient will send `/ingest/jg1798/07%2F1798-07-25.xml` over the wire.

It is possible that the formatting of the error message (which I assume comes from the reason phrase from the server) `The requested URL /exist/restxq/edoc/admin/ingest/jg1798/07/1798-07-25.xml was not found on this server.` led the OP to believe the request was made to that Uri.

**Comment by iSazonov** [comment]
Thanks for your thoughts! I see you guess that it is the server error. I close the issue untill @dariok add more info.
