### ISSUE TITLE
Support DeleteByPattern in IDistributedCache

### ISSUE THREAD

**Issue by AleAntonellis** [dotnet/runtime#35982]
I need a smart way to evict cache keys based on a regex or pattern. In order to evict application areas based on some criteria.
Example. I need to evict all the keys for a particular country in a particular application area

### Describe the solution you'd like
Create a method in IDistributedCache (es. DeleteByPattern) that accepts a pattern and evict all keys that match the pattern

### Describe alternatives you've considered
Implement it by my self and call directly the distributed cache server. In my application is Redis and it supports this feature. But I want to maintain my application agnostics about the infrastructure

**Comment by eerhardt** [comment]
Duplicate of #36127.
