### ISSUE TITLE
BackgroundService TaskStatus

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/runtime#35991]
### Is your feature request related to a problem? Please describe. 
As a developer I'm unable able to determine if a registered BackgroundService is running and/or has ran to competition or faulted.

### Describe the solution you'd like
The based abstract class should have a TaskStatus property added which shows the status of the ExecuteAsync task.

## Proposed API

```diff
namespace Microsoft.Extensions.Hosting
{
    /// <summary>
    /// Base class for implementing a long running <see cref="IHostedService"/>.
    /// </summary>
    public abstract class BackgroundService
    {
+        /// <summary>
+        /// Gets the Task that is executing the background operation.
+        /// </summary>
+        public Task ExecutingTask;
    }
}
```

## Usage example

```C#
BackgroundService s = ...;
s.ExecutingTask.ContinueWith(t =>
{
    if (t.IsFaulted)
    {
        Console.WriteLine(t.Exception.ToString());
    }
});
```

**Comment by eerhardt** [comment]
Updating the top-post to make an official API proposal, and marking it ready-for-review.

Exposing this Task is generally useful to a few different scenarios - ex. it is blocking #36017.

**Comment by terrajobst** [comment]
* Should be a property ;-)
* Let's rename it to `ExecuteTask` to make it clear that's the task returned by `ExecuteAsync` rather than being some transient task.

```C#
namespace Microsoft.Extensions.Hosting
{
    public abstract class BackgroundService
    {
        public virtual Task ExecuteTask { get; }
    }
}
```
