### ISSUE TITLE
TraceSourceLoggerProvider does not like TextWriterTraceListener

### ISSUE THREAD

**Issue by zijianhuang** [dotnet/runtime#36004]
### Describe the bug
TraceSourceLoggerProvider is for ILogger to write messages to a TraceListener object attached to a TraceSource object created internally,

The provider works well with ConsoleTraceListener, however, does nothing with TextWriterTraceListener.

Also, the same TextWriterTraceListener attached to the other TraceSource objects created in the application codes is not working either, while it is working when the listener is not associated with TraceSourceLoggerProvider.

### To Reproduce

I had created a few demo projects at https://github.com/zijianhuang/TraceSourceNetCore

And please focus on ConsoleApptraceSourceLogger.csproj.

### Expected behavior

1. TraceSourceLoggerProvider  should be working with TextWriterTraceListener .
2. TraceSourceLoggerProvider  should be working with TextWriterTraceListener shared with other TraceSource objects in the application codes.

**Comment by tarekgh** [comment]
CC @maryamariyan

**Comment by maryamariyan** [comment]
I believe the way you are setting up your project is not right.

```c#
static void Main(string[] args)
        {
            using var loggerFactory = LoggerFactory.Create(builder =>
            {
                var testSwitch = new SourceSwitch("sourceSwitch", "Logging Sample");
                testSwitch.Level = SourceLevels.Warning;
                builder
                    .AddSystemdConsole()
                    .AddTraceSource(testSwitch,
                        new TextWriterTraceListener(@"C:\logs\trace.log"));// writer: Console.Out));
            });
            var logger = loggerFactory.CreateLogger("sourceSwitch");
            logger.Log(LogLevel.Warning, new NotImplementedException("NIE exception message"), "message for warning");
        }
```

Here's a sample code showing usage with TextWriterTraceListener. 

HTH.

**Comment by zijianhuang** [comment]
@maryamariyan
Thanks for the example which provides an alternative way of initialize TextWriterTraceListener and SourceSwitch.

My business intent was to use System.Diagnostics.TraceSource to emit trace. Apparently TraceSourceLoggerProvider instantiated by AddTraceSource is not to serve TraceSource at all, but for ILogger. However, if TraceSourceLoggerProvider is instantiated , then TraceSource won't be working.

Is such understanding true?

While your example codes, you do not use TraceSource at all.

**Comment by maryamariyan** [comment]
How about something like this: (slight update to previous code snippet and using TraceSource)

```c#

        static void Main(string[] args)
        {
            using (var textWriterTraceListener = new TextWriterTraceListener(@"C:\CodeHub\logs\trace.log"))
            using (var consoleTraceListener = new ConsoleTraceListener())
            {
                using var loggerFactory = LoggerFactory.Create(builder =>
                {
                    builder
                        .AddTraceSource(new SourceSwitch("Something") { Level = SourceLevels.All }, consoleTraceListener)
                        .AddTraceSource(new SourceSwitch("HouseKeeping") { Level = SourceLevels.All }, textWriterTraceListener);
                    // writer: Console.Out));
                });
                var logger = loggerFactory.CreateLogger<Program>();
                logger.LogInformation("LogInformation information");
                logger.LogWarning("LogWarning warning");

                var ts = new TraceSource("HouseKeeping", SourceLevels.All);
                ts.Listeners.Add(consoleTraceListener);
                ts.Listeners.Add(textWriterTraceListener);
                ts.TraceEvent(TraceEventType.Error, 0, "trace error");
            }
        }
```

What won't work in this case?

**Comment by zijianhuang** [comment]
Thanks. All working.
