### ISSUE TITLE
API Proposal: Expose Host.ConfigureDefaults

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#36003]
This would allow callers to provide the IHostBuilder instance without having to copy all the logic to setup defaults.

**Comment by maryamariyan** [comment]
API Proposal Summary:

The ask is to move the IHostBuilder instantiation below out of the new API, so other callers can provide their own IHostBuilder to CreateDefaultBuilder
https://github.com/dotnet/runtime/blob/f7e0069ef27afa83c38d97c1650bc87e152d98a2/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L58



```diff
    public static partial class Host
    {
        public static Microsoft.Extensions.Hosting.IHostBuilder CreateDefaultBuilder() { throw null; }
        public static Microsoft.Extensions.Hosting.IHostBuilder CreateDefaultBuilder(string[] args) { throw null; }
+       public static Microsoft.Extensions.Hosting.IHostBuilder CreateDefaultBuilder(IHostBuilder builder, string[] args) { throw null; }
    }
```

**Comment by terrajobst** [comment]
* Let's not name it `CreateDefaultBuilder()` because it doesn't actually create a new builder, it just applies the defaults.

```C#
namespace Microsoft.Extensions.Hosting
{
    public static partial class Host
    {
        // Existing:
        // public static IHostBuilder CreateDefaultBuilder();
        // public static IHostBuilder CreateDefaultBuilder(string[] args);
        public static IHostBuilder ConfigureDefaults(IHostBuilder builder, string[] args);
    }
}
```

**Comment by davidfowl** [comment]
Nice!

**Comment by IEvangelist** [comment]
If you're okay with it @maryamariyan and @davidfowl, I'd love to work on this?

**Comment by davidfowl** [comment]
Do it!
