### ISSUE TITLE
IsNullOrEmpty/Whitespace fails on many empty/whitespace StringValues values.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/runtime#36005]
### Describe the bug
Having the following `StringValues` value:
```c#
var a = new StringValues("", "");
var b = new StringValues(" ", " ");
var c = new StringValues("", " ");
```
When calling `string.IsNullOrWhitespace(x)` or `StringValues.IsNullOrEmpty(x)` or `string.IsNullOrEmpty(x)` I'm seeing inconsistent (unexpected) results.

### To Reproduce
```c#
var a = new StringValues(new string[] { "", "" });
var b = new StringValues(new string[] { " ", " " });
var c = new StringValues(new string[] { "", " " });

Console.WriteLine("--------------------------------------------------");
Console.WriteLine($"A {{\"\", \"\"}} Expected True: {StringValues.IsNullOrEmpty(a)}");
Console.WriteLine($"A {{\"\", \"\"}} Expected True: {string.IsNullOrEmpty(a)}");
Console.WriteLine($"A {{\"\", \"\"}} Expected True: {string.IsNullOrWhiteSpace(a)}");
Console.WriteLine("--------------------------------------------------");
Console.WriteLine($"B {{\" \", \" \"}} Expected False: {StringValues.IsNullOrEmpty(b)}");
Console.WriteLine($"B {{\" \", \" \"}} Expected False: {string.IsNullOrEmpty(b)}");
Console.WriteLine($"B {{\" \", \" \"}} Expected True: {string.IsNullOrWhiteSpace(b)}");
Console.WriteLine("--------------------------------------------------");
Console.WriteLine($"C {{\"\", \" \"}} Expected False: {StringValues.IsNullOrEmpty(c)}");
Console.WriteLine($"C {{\"\", \" \"}} Expected False: {string.IsNullOrEmpty(c)}");
Console.WriteLine($"C {{\"\", \" \"}} Expected True: {string.IsNullOrWhiteSpace(c)}");
```
### Expected behavior
```c#
--------------------------------------------------
StringValues.IsNullOrEmpty A {"", ""}     Expected True:  False
string.IsNullOrEmpty       A {"", ""}     Expected True:  True
string.IsNullOrWhiteSpace  A {"", ""}     Expected True:  True
--------------------------------------------------
StringValues.IsNullOrEmpty B {" ", " "}   Expected False: False
string.IsNullOrEmpty       B {" ", " "}   Expected False: False
string.IsNullOrWhiteSpace  B {" ", " "}   Expected True:  False
--------------------------------------------------
StringValues.IsNullOrEmpty C {"", " "}    Expected False: False
string.IsNullOrEmpty       C {"", " "}    Expected False: False
string.IsNullOrWhiteSpace  C {"", " "}    Expected True:  True
```

### Additional context
One of the offending lines that makes the `StringValues` inconsistency:
https://github.com/dotnet/extensions/blob/master/src/Primitives/src/StringValues.cs#L436

**Comment by iSazonov** [comment]
The behavior is explicitly documented https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.stringvalues.isnullorempty?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Primitives_StringValues_IsNullOrEmpty_Microsoft_Extensions_Primitives_StringValues_

I wonder if MSFT team agreed to change the design.

**Comment by jaymin93** [comment]
yes as per the above comment as well and checking from code L438 is returning false as it's default case and it's expected output based on documentation i think no change will be required or it's change at api level to check entire array for null

**Comment by danmosemsft** [comment]
@maryamariyan since this is documented, should we close this?

**Comment by eerhardt** [comment]
> since this is documented, should we close this?

Yes. Closing as this is documented behavior. The API is if the `StringValues` (a collection) is null or empty. Not if the strings inside of it are null or empty.
