### ISSUE TITLE
Include filename in load exception

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#36007]
We spent a few minutes today trying to debug a file load error only to find out that we were trying to fix the wrong file because the exception doesn't say what file failed to load.

https://github.com/aspnet/Extensions/blob/06dcb43bfb372585d3801cfc333a2d9ee9c189ea/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L90

cc @jkotalik

**Comment by anurse** [comment]
This could be a nice and low-cost 5.0 fix-up, so I'll leave it untriaged for now.

**Comment by KimKiHyuk** [comment]
umm.. is it good? like
```
...
 using (var stream = file.CreateReadStream())
                {
                    try
                    {
                        Load(stream);
                    }
                    catch (FileNotFoundException e)
                    {
                        var error = new StringBuilder($"The configuration file '{Source.Path}' was not found and is not optional.");
                        HandleException(ExceptionDispatchInfo.Capture(error));
                    }
                    catch (Exception e)
                    {
                        HandleException(ExceptionDispatchInfo.Capture(e));
                    }
                }

**Comment by BrennanConroy** [comment]
Not quite, the original issue wasn't about a file missing, it was about the file load failing because of bad config, in the case of a json file there was invalid json in the file.

**Comment by KimKiHyuk** [comment]
> Not quite, the original issue wasn't about a file missing, it was about the file load failing because of bad config, in the case of a json file there was invalid json in the file.

what about checking json file's syntax? 
like 
```
private void Load(bool reload)
{
            var file = Source.FileProvider?.GetFileInfo(Source.Path);
            if (file == null || !file.Exists)
            {
                if (Source.Optional || reload) // Always optional on reload
                {
                    Data = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }
                else
                {
                    var error = new StringBuilder($"The configuration file '{Source.Path}' was not found and is not optional.");
                    if (!string.IsNullOrEmpty(file?.PhysicalPath))
                    {
                        error.Append($" The physical path is '{file.PhysicalPath}'.");
                    }
                    HandleException(ExceptionDispatchInfo.Capture(new FileNotFoundException(error.ToString())));
             } //  pseudo code
             else if (IsInvalidFileFormat()) 
             {
                  ....
             }
 
}

**Comment by heesunlee9** [comment]
@BrennanConroy, did you solve the problem? It seems like you already solve it.

**Comment by danmosemsft** [comment]
@maryamariyan still 5.0?

**Comment by maryamariyan** [comment]
no it's not a show stopper for 5.0. moving the milestone.

**Comment by ericstj** [comment]
Ensure that the fix for this covers the suggestion from #42337 

> It looks like it would be very simple to pass the Source.Path to the FileNotFoundException's constructor.

> The line in question is this:
https://github.com/dotnet/runtime/blob/8933510b35aab8bb49f999586d4169a2cd6d920a/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs#L74

**Comment by IEvangelist** [comment]
Hey, @maryamariyan and @eerhardt - do you mind if I take this one?

**Comment by eerhardt** [comment]
@IEvangelist - it's all yours!

**Comment by ericstj** [comment]
Make sure to consider the constraints that came up in the last PR: https://github.com/dotnet/runtime/pull/35183

**Comment by IEvangelist** [comment]
> Make sure to consider the constraints that came up in the last PR: #35183

Thanks, will do.
