### ISSUE TITLE
Single-file: Generate bundles with deterministic IDs

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#3601]
The Bundler generates bundled apps with randomly generated bundle-IDs for each build.
Instead, this should be changed to use an ID based on the contents of the bundle.
This way, two builds on the same input generate identical output.

**Comment by wjch-krl** [comment]
Is this something that is planned for fixing in nearest future? If not, will you accept contribution for this?

**Comment by jakrivan** [comment]
Btw. here is the exact location of the rootcause of the issue: https://github.com/dotnet/runtime/blob/main/src/installer/managed/Microsoft.NET.HostModel/Bundle/Manifest.cs#L82

**Comment by vitek-karas** [comment]
Fixed by https://github.com/dotnet/runtime/pull/52930.

**Comment by nioncode** [comment]
@vitek-karas Thanks for merging the fix. Is there a roadmap for when a version with the fix will be released?

**Comment by vitek-karas** [comment]
This should go into the Preview 6 of .NET 6. It will take a couple of days to get to https://github.com/dotnet/installer where you can download a nightly build before the Preview 6 is released.

**Comment by vitek-karas** [comment]
Note that this only affects the SDK, not the runtime. So you can use the latest .NET 6 SDK, but still target 3.1 or 5.0 for the app itself.
