### ISSUE TITLE
Cannot bind configuration to a value type

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/runtime#36023]
### Describe the bug
Not sure if this is actually a bug or if it's intentional, but it's apparently not possible to bind configuration to a value type.

### To Reproduce
1. Using version `3.0.0` of package `Microsoft.Extension.Configuration.Binder`
2. Run this code

```csharp
static void Main()
{
    var configuration = new ConfigurationBuilder()
        .AddInMemoryCollection(new Dictionary<string, string>
        {
            ["X"] = "hello",
            ["Y"] = "world"
        })
        .Build();
        
    var foo = configuration.Get<Foo>();
}

public struct Foo
{
    public string X { get; set; }
    public string Y { get; set; }
}
```
3. The following exception is thrown: **InvalidOperationException**: Cannot create instance of type 'ConsoleApplication1.Program+Foo' because it is missing a public parameterless constructor.

### Expected behavior
The binding should succeed. It works fine if `Foo` is a class. And `Foo` is a value type, so it doesn't *need* a public parameterless constructor.

### Screenshots
N/A

### Additional context
N/A

**Comment by ericstj** [comment]
Looks like ConfigurationBinder.CreateInstance is missing a special case for structs:
https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L370-L374

It may be that this only requires special handling for the struct case, just checking its public.

@thomaslevesque would you be interested in making a PR to fix this?

**Comment by thomaslevesque** [comment]
@ericstj sure, I'll take a look at it.
