### ISSUE TITLE
Getting all cache keys Microsoft.Extensions.Caching.Memory

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/runtime#36026]
Is there anything available at this time for getting list of keys?

**Comment by specialforest** [comment]
+1, .net has two(!) implementations of MemoryCache and both are terrible!

**Comment by maryamariyan** [comment]
Thanks @KamranShahid for your issue. The next step for this would be to add API proposal, and example usage. Refer to https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md for more detail.

**Comment by KamranShahid** [comment]
> If you really, _really_, **really** have to do something like this, at least move the `var methodInfo = item.GetType().GetProperty("Key");` part out of the foreach loop to avoid a double reflection lookup per each item.
> 
> Btw maybe [this](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.memorycache.getenumerator?view=dotnet-plat-ext-3.1#System_Runtime_Caching_MemoryCache_GetEnumerator) is what you are looking for.

Can you suggest how?

**Comment by sigmarsson** [comment]
I too display interest in dealing somehow with the keys. 
My is like `$"{object}+{DateTime}-{DateTime}"`

Therefore my cache legitim could furnish the cached value for the following key request :

`$"{object}+{DateTime + 1 Day}-{DateTime - 1 Day}"` because this period is contained by the previous one. 

I am not sure anymore this class is the right one here. What is your take on ?

**Comment by adamsitnik** [comment]
@KamranShahid As @maryamariyan has pointed (https://github.com/dotnet/runtime/issues/36026#issuecomment-705025634), you need to provide the API proposal using the official [template](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md). Once you do that and we have a better understanding of what problem the API would try to solve, we can continue the process of adding new API.

**Comment by KamranShahid** [comment]
> @KamranShahid As @maryamariyan has pointed ([#36026 (comment)](https://github.com/dotnet/runtime/issues/36026#issuecomment-705025634)), you need to provide the API proposal using the official [template](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md). Once you do that and we have a better understanding of what problem the API would try to solve, we can continue the process of adding new API.

requirement is quite clear and i have put a solution as well which i am using

**Comment by maryamariyan** [comment]
I don't see us working on this feature item anytime soon, closing since it does not seem like a blocking item either.
