### ISSUE TITLE
How to download all NuGet packages at once?

### ISSUE THREAD

**Issue by lg2de** [dotnet/runtime#36033]
### Is your feature request related to a problem? Please describe.
As a software vendor we have to ensure that all packages included in our software have a license according to our rules.
Therefore we started approval process for NuGet packages.

So far this is working fine for individual packages based on .NET Framework (4.X).
Starting with .NET Core we are facing a huge list of packages required to be approved.

### Describe the solution you'd like
I would like to have a download package containing all NuGet packages of a feature set, e.g. all from `Microsoft.Extensions` in version 3.1.0.
Within the (ZIP) package all packages should be grouped by the license.
If all have the same license: Fine, no grouping required.

### Describe alternatives you've considered
Currently every package needs to be downloaded manually from nuget.org or copied to the local nuget cache.
Further every package needs to be check for the license.

### Additional context
In this context the following question may be relevant:
Why all packages are released with new version even the package has not changed since last version?
Especially the abstractions packages (e.g. microsoft.extensions.logging.abstractions) are released as 3.1.0, 3.1.1, 3.1.2 and 3.1.3 even there **must** be no change on the abstractions (according SemVer), isn't it?

**Comment by NikolaMilosavljevic** [comment]
@dagood

**Comment by dagood** [comment]
I think this scenario would be best addressed by an SDK or NuGet feature. It sounds like you're looking for something like a "bill of materials" that describes what's needed to build/publish/etc. a particular project or set of projects, along with the contents of each package for manual inspection/audit. Does that description seem reasonable, @lg2de?

(License is a property in the xml file `*.nuspec` in each package, so putting that in the SDK feature might not be necessary, but it seems like a small detail. Depending on how you audit, you may end up having different requirements or objections to what the feature would tell you, anyway.)

About the direct request:

> I would like to have a download package containing all NuGet packages of a feature set, e.g. all from `Microsoft.Extensions` in version 3.1.0.

I don't think we're fit to assemble something like this--I'm not sure what the granularity of a "feature set" would be, for example. We'd need a set of categories that makes sense to us, but more importantly, is obvious to anyone trying to download the right set of archives to get the package set they're looking for. Seems like a significant challenge we should try to avoid.

On the technical side: the packages that may be referenced by projects accumulates over time. (You use packages from the 3.1.0, 3.1.1, and 3.1.2 releases all at once in some cases.) This means we can't simply produce these artifacts when we build .NET Core. We'd need to harvest old releases to assemble these artifacts. On a similar note... these archives would grow forever.

An SDK or NuGet feature would be able to get the packages you actually reference without needing you to manually match up categories, wouldn't grow uncontrollably, and would be easily repeatable for audit tooling.

I think this should be transferred to dotnet/sdk if that all sounds reasonable.

---

> Why all packages are released with new version even the package has not changed since last version?
> Especially the abstractions packages (e.g. microsoft.extensions.logging.abstractions) are released as 3.1.0, 3.1.1, 3.1.2 and 3.1.3 even there **must** be no change on the abstractions (according SemVer), isn't it?

I don't think this affects it, but we do *generally* avoid releasing new versions of packages to NuGet.org when they don't change. This is especially true for dotnet/runtime's libraries. Maybe there's a different reason for that particular package--if it affects your audit I think a new issue is right. Note that `Microsoft.Extensions.Logging` somewhat recently migrated from dotnet/extensions to dotnet/runtime, so this behavior might be in flux.

**Comment by NikolaMilosavljevic** [comment]
@lg2de , does the proposal above suits your needs?

**Comment by lg2de** [comment]
> dagood wrote:
> I think this scenario would be best addressed by an SDK or NuGet feature.

Do you think, this is the wrong repo for my question?
May be. I was not sure who is responsible to create "all these packages" and who decided on the scope of each package.

> It sounds like you're looking for something like a "bill of materials" that describes what's needed to build/publish/etc. a particular project or set of projects, along with the contents of each package for manual inspection/audit. Does that description seem reasonable, @lg2de?

No, I do not want to download each NuGet package manually. Instead I would like download "all" at once. Because the number of packages in the "dotnet world" is very huge I asked for download packages according to "feature sets".

> I don't think we're fit to assemble something like this

This repository seams to manage sources for many [libraries](https://github.com/dotnet/runtime/tree/master/src/libraries). All these are build at once, I guess. All created NuGet packages could be provided in one ZIP asset, isn't it?

**Comment by dagood** [comment]
> > I think this scenario would be best addressed by an SDK or NuGet feature.
> 
> Do you think, this is the wrong repo for my question?

I think it's fine, it got where it needed to be. However, I doubt we would be able to produce the exact zip you're asking for. So instead, I'm proposing something that I'm hoping can accomplish the same goal in a better way. If it sounds reasonable to you, the alternative would be filed in a different repo.

> No, I do not want to download each NuGet package manually.

This isn't what I meant. The "along with the contents of each package for manual inspection/audit" part was supposed to mean the proposed feature would download everything for you. (Just like a package restore.)

> Because the number of packages in the "dotnet world" is very huge I asked for download packages according to "feature sets".

> All created NuGet packages could be provided in one ZIP asset, isn't it?

In case it didn't stand out, the paragraphs starting with "I don't think we're fit to assemble something like this" are reasons I don't think "feature sets" will work, or a single zip file.

---

I realized I missed this:

> Currently every package needs to be downloaded manually from nuget.org or copied from local nuget cache.

@lg2de Why not copy from the nuget cache?

**Comment by lg2de** [comment]
> Why not copy from the nuget cache?

Just now I fixed my initial comment from "from cache" to "to cache"...

Maybe this clarifies some confusion.

**Comment by lg2de** [comment]
Maybe another information needs to be clarified: WHY do I want to download multiple packages?

Together with the approval process we have setup a NuGet package mirror (Azure DevOps Server). Internal development (build process) must use only the this internal feed.

When new version of ".net core libraries" is available I would like to download all and approve all at once.

**Comment by dagood** [comment]
> Together with the approval process we have setup a NuGet package mirror (Azure DevOps Server). Internal development (build process) must use only the this internal feed.
> 
> When new version of ".net core libraries" is available I would like to download all and approve all at once.

This is much more useful, thanks. The original request sounded like you want to grab all package dependencies an **existing** project has, and evaluate them. The dependencies are downloaded to the package cache when you build an app, so that's when it would make sense to look at the package cache and copy them out as necessary to do extra stuff.

But what you're really trying to do is grab every .NET package that apps in your build environment will be permitted to use **in the future**, and build up an approved mirror over time. It makes a lot more sense why you would want to download a zip of packages to get this going. :smile: The most reasonable form it would take is a zip file for each GitHub repository containing all nupkgs built by that repo. (We used to do something very similar to distribute the symbol files that each repo built.)

So... now that the scenario is clear, I do think you're requesting a worthwhile artifact that is possible for us to produce. It would be something that's created during the release pipeline, and the download link would be posted to the release download doc (like https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.4.md). This means the production of the zip would probably best be tracked in dotnet/arcade. I've filed this, for further discussion and triage: https://github.com/dotnet/arcade/issues/5681.

Does that all sound right, @lg2de?

---

It's not too hard to work around this, though: we do publish lists of packages released in each servicing event:
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.4.md#packages-updated-in-this-release
Taking one of these tables and downloading every package is a pretty trivial script. (PowerShell below.) This also lets you filter a "feature set" if you want.

```powershell
$copyPasteFromGitHub="
Microsoft.Extensions.FileProviders.Physical	3.1.4
Microsoft.Extensions.FileProviders.Embedded	3.1.4
Microsoft.Extensions.FileProviders.Composite	3.1.4
Microsoft.Extensions.FileProviders.Abstractions	3.1.4
"
foreach ($line in $copyPasteFromGitHub.Split("`r`n")) {
	$id, $version = $line.Split("`t")
	if ($id -and $version) {
		Invoke-WebRequest `
			-Uri "https://www.nuget.org/api/v2/package/$id/$version" `
			-OutFile "$id.$version.nupkg" `
			-UseBasicParsing
	}
}
```

**Comment by lg2de** [comment]
> This is much more useful, thanks.

I'm very sorry for the confusion before!

> I've filed this, for further discussion and triage: [dotnet/arcade#5681](https://github.com/dotnet/arcade/issues/5681). Does that all sound right, @lg2de?

Yes, that is fine.

> It's not too hard to work around this [...]

I did not notice before this list.
Yes, this is a work-around. But I guess it is very easy to create such a ZIP file while build process... ;)

BTW: There is a small type in this list for System.Reflection.Metadata.1.8.1

**Comment by dagood** [comment]
> But I guess it is very easy to create such a ZIP file while build process... ;)

An interesting guess. Not the same as my guess. 😄 But we'll see what the people who would actually implement it think in https://github.com/dotnet/arcade/issues/5681.

> BTW: There is a small type in this list for System.Reflection.Metadata.1.8.1

Mind filing an issue or submitting a PR in dotnet/core for this?

> Yes, that is fine.

Great, closing this issue then, and followup will be at https://github.com/dotnet/arcade/issues/5681. Thanks for the discussion.
