### ISSUE TITLE
Introduce ISecretStore

### ISSUE THREAD

**Issue by tomkerkhove** [dotnet/runtime#36035]
### Is your feature request related to a problem? Please describe.
As of today; `IConfiguration` provides integration with Azure Key Vault which is by nature a secret store, not configuration information.

### Describe the solution you'd like
I'd love to have an `ISecretStore` or `ISecretProvider` to provide a clear distinction between configuration & secret information so that it can be treated how they should be.

Too often I've seen when people get access to secrets while they are not aware of them or they do not correctly handle them by logging them, not providing transient handling of expired secrets and more.

By providing a seperation in interfaces this can be improved.

**Comment by tomkerkhove** [comment]
For those interested, you can now use [Arcus Secret Store](https://security.arcus-azure.net/features/secret-store/) (read more in [our blog post](https://www.codit.eu/blog/introducing-secret-store-net-core/)).

Get started with:
```
PM > Install-Package Arcus.Security.Core
```

_This is obviously a first version and we are open for feedback_

**Comment by maryamariyan** [comment]
Based on the discussions that @rynowak and @davidfowl raised closing this issue. Please feel free to reopen if you think we should reconsider this or have a further discussion
