### ISSUE TITLE
Single-File: Servicing locations should take precedence over bundle contents

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#36031]
As described in the single-file app [dependency resolution logic](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md#dependency-resolution), if a bundled assemblies can be overridden by those found in a servicing location.

The Host adds servicing assemblies into the TPA list. But the Runtime probes the bundled contents before the TPA list.

Therefore, if a matching servicing assembly is discovered, remove the corresponding bundled assembly from the bundle-manifest maintained by the host.

**Comment by davidfowl** [comment]
Hammer servicing?

**Comment by swaroop-sridhar** [comment]
> Hammer servicing?

Yes @davidfowl  this is to support hammer servicing.
