### ISSUE TITLE
Support reading a byte array from a base64 string in JSON configuration

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/runtime#36034]
### Is your feature request related to a problem? Please describe.

Currently, the configuration binder can't read a byte array from a base64 string. 

For instance, if I have this:
```csharp
    public class MyOptions
    {
        public byte[] Key { get; set; }
    }
    ...
    services.Configure<MyOptions>(Configuration.GetSection("My"));
```

and my appsettings.json file specifies the value for `Key` as a base64 string, it silently fails to bind my property, which remains null.

### Describe the solution you'd like

I'd like to be able to use base64 to specify byte array values in my configuration file. Instead, I have to declare the property as string, and parse it myself, which isn't very convenient.
(or write the values as a JSON array, which is even worse)

### Describe alternatives you've considered

As mentioned above, declaring the property as a string and parsing it manually works, but isn't convenient.

### Additional context

N/A

**Comment by safern** [comment]
Thanks for the proposal @thomaslevesque.

The problem that I see with this is, how would we identify you have a base64 string to decode in the config file?

Would we have to look at the property that we're binding and if it's type is `byte[]` then try and decode the base64 string as a `byte[]`?

**Comment by thomaslevesque** [comment]
> Would we have to look at the property that we're binding and if it's type is `byte[]` then try and decode the base64 string as a `byte[]`?

Yes, at least that's what I had in mind.

Actually, I probably shouldn't have mentioned JSON in the issue description, since it's not actually specific to JSON configuration. It should apply to any configuration source, since AFAIK the configuration binder doesn't care where the values come from, it just sees key/value pairs.

**Comment by thomaslevesque** [comment]
Looks like [`TryConvertValue`](https://github.com/dotnet/runtime/blob/30e643e2f2433055d6ed433af38a925ee657d4ad/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L490) uses the `TypeConverter` for the property type to parse the value, but there isn't a specific `TypeConverter` for `byte[]`.
It could easily be solved by adding a special case to `TryConvertValue`. Something like this:
```csharp
if (type == typeof(byte[]))
{
    if (value is null)
        return null;
    return Convert.FromBase64String(value);
}
```
(with appropriate error handling, of course)

I can submit a PR if this approach is acceptable.

**Comment by safern** [comment]
I don't have an objection to doing that.

cc: @maryamariyan @davidfowl ?

**Comment by thomaslevesque** [comment]
@safern I sent a PR for this: #43150

**Comment by davidfowl** [comment]
This seems reasonable.
