### ISSUE TITLE
Feature request: Getting the WatcherChangeTypes from IFileProvider.Watch

### ISSUE THREAD

**Issue by Sina-Soltani** [dotnet/runtime#36038]
The `System.IO.FileSystemWatcher` already gives us the `WatcherChangeTypes` enum when a files is created, modified, deleted or renamed. This feature does not exist in `IFileProvider.Watch` method. So if we inject the `IFileProvider` somewhere for tracking the changes of a folder, then we have no possibility to know what exactly to a file happened.

### Describe the solution you'd like
Maybe something like this can solve the problem:

```c#
private readonly IFileProvider _fileProvider;

public SomeClass(IFileProvider fileProvider)
{
   _fileProvider = fileProvider;
}

public void StartTracking()
{
   var changeToken = _fileProvider.Watch("<PATH>");

   switch (changeToken.ChangeType)
   {
   }
}
```

OR
```csharp
_fileProvider.Watch("<PATH>", onFileChanged => 
{
   switch (onFileChanged.ChangeType)
   {
   }
})
```

**Comment by maryamariyan** [comment]
The next step for this is to create an API proposal with sample usage as shown in guideline [here](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

@Sina-Soltani would you like to provide an API proposal for this request?

**Comment by Sina-Soltani** [comment]
Hi @maryamariyan,
Unfortunately I'm not sure if I have time for this.
