### ISSUE TITLE
Teach the DAC how to unwrap ComWrappers-based CCWs

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#36048]
To ensure that we get an accurate diagnostics experience for RCWs and CCWs that use the new ComWrappers APIs, we should enlighten the DAC to how to discover them and dump them.

Additionally, this work should include updating the DAC's support for dumping a stowed exception to be able to unwrap ComWrappers-based CCW stowed exceptions.

Related: https://github.com/microsoft/CsWinRT/issues/201, #35318

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT @tommcdon

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Thanks for filing this. Can you elaborate on what information would be helpful? The details that are in the `ComWrappers` RCW/CCW are vastly different than the built in ones.

**Comment by jkoritzinsky** [comment]
For the stowed exception scenario in particular, the DAC needs to be able to identity an interface pointer as a ComWrappers CCW interface pointer, retrieve the managed object, and dump the managed object.

The implementations of https://github.com/dotnet/runtime/blob/b48900f3b37e6d68b5d84a3e48f0c5beb602a128/src/coreclr/src/inc/sospriv.idl#L299-L304 are what we need to enlighten.

In particular, `GetCCWData` at https://github.com/dotnet/runtime/blob/b48900f3b37e6d68b5d84a3e48f0c5beb602a128/src/coreclr/src/debug/daccess/request.cpp#L4069 is the function that the "dump stowed exception" path uses to unwrap the stowed exception object and get the information for the user.

**Comment by jkoritzinsky** [comment]
If we implement all of the mentioned functions for the DAC, I think that will enable all of the CCW/RCW related SOS commands for ComWrappers CCWs and RCW s as well.

**Comment by AaronRobinsonMSFT** [comment]
This is going to be unfortunate. I was hoping to avoid having a DAC build of the interoplib. We might want to redesign some of the data structures so the header contains everything. Don't know if that has already been done.

**Comment by tommcdon** [comment]
@noahfalk
