### ISSUE TITLE
ASP.net Core 3.1 Could not parse the JSON file

### ISSUE THREAD

**Issue by mjthompson2107** [dotnet/runtime#36040]
I have started the upgrade of my project from ASP.net core 2.1 to 3.1, but having an issue with reading the appsettings.json file. This file has not changed and I am getting the following error:

'Could not parse the JSON file.'
JsonReaderException: '0x10' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 8 | BytePositionInLine: 21.

This is not an issue in other ASP.net core 3.1 projects that I have created and the following is format of my appsettings.json:

{
  "DataProtection": {
    "ApplicationName": "test",
    "BlobName": "test",
    "SasToken": "test",
    "ContainerName": "test",
    "StorageUrl": "https://test.windows.net"
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Warning",
      "System": "Warning"
    },
    "AllowedHosts": "*"
  }
}

Please could you help with this issue

**Comment by ericstj** [comment]
Can you please update your exact appsettings.json file?  I want to make sure we don't lose something with encoding in the copy/paste to comments.

**Comment by uchagani** [comment]
I have a similar problem.  here is my full appsettings.json

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "ABCD_TEST": "Data Source=ab-cdefgh-12.1234567x1abc.database.windows.net;Initial Catalog=ABCD-TEST;Persist Security Info=True;User ID=abc_user;Password=A5X_ab#r%^"
  }
}
```

**Comment by uchagani** [comment]
So in my case, I had at one point used the `Manage User Secrets` option in Visual Studio which created an empty `secrets.json` file.  That file is the one that was giving me problems as it was empty and that is not valid json.  I added `{}` into that file and the JSON parse error disappears.

**Comment by Shiva-netmasons** [comment]
> So in my case, I had at one point used the `Manage User Secrets` option in Visual Studio which created an empty `secrets.json` file. That file is the one that was giving me problems as it was empty and that is not valid json. I added `{}` into that file and the JSON parse error disappears.

This resolved my issues.  Solution > Right click to Manage User Secrets and Open the file in explore if the file is empty.

**Comment by ericstj** [comment]
@uchagani and @Shiva-netmasons It sounds like this was caused by feeding an empty secrets.json in both cases.  I don't think we should make AddJsonFile tolerate an empty file as it's an indication that something is wrong with the input.

I think these are both different issues than what @mjthompson2107 is seeing, since his error is clearly calling out line/position number.  

@mjthompson2107 we really need the actual file (or a similar file that reproduces the issue but doesn't contain sensitive information) to help you.  Please do not copy-paste content of the file, but drag/drop into the issue (as a .zip if GitHub doesn't like the extension).

**Comment by maryamariyan** [comment]
> @mjthompson2107 we really need the actual file (or a similar file that reproduces the issue but doesn't contain sensitive information) to help you. Please do not copy-paste content of the file, but drag/drop into the issue (as a .zip if GitHub doesn't like the extension).

@mjthompson2107 could you please provide more info to repro this issue?

**Comment by mjthompson2107** [comment]
my issue has been resolved now. same solution as @uchagani
