### ISSUE TITLE
Bug: AddCommandLine(args, switchMappings) System.FormatException: The short switch '-k1=value1' is not defined in the switch mappings.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/runtime#36041]
Code from [CommandLineConfigurationExtensions.AddCommandLine Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.commandlineconfigurationextensions.addcommandline?view=dotnet-plat-ext-3.1)

```
dotnet --version
3.1.101
```

To repo:

```
dotnet new web -o swithMap
cd swithMap
// Replace main with the following code from the doc page
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            var switchMappings = new Dictionary<string, string>()
             {
                 { "-k1", "key1" },
                 { "-k2", "key2" },
                 { "--alt3", "key3" },
                 { "--alt4", "key4" },
                 { "--alt5", "key5" },
                 { "--alt6", "key6" },
             };

            return Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddCommandLine(args, switchMappings);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
        }
    }
```

Per the doc page, run the following command
`dotnet run -k1=value1 -k2 value2 --alt3=value2 /alt4=value3 --alt5 value5 /alt6 value6`

Unhandled exception. System.FormatException: The short switch '-k1=value1' is not defined in the switch mappings.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildHostConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at swithMap.Program.Main(String[] args) in C:\tmp\swithMap\Program.cs:line 16

The following command works
`dotnet run -k1 value1 -k2 value2 --alt3=value2 /alt4=value3 --alt5 value5 /alt6 value6`

As you can see from the preceding command, `=` works with `--` and `/`, it's just the single `-` that fails.

**Comment by Rick-Anderson** [comment]
Customer complaints this is not working. Perhaps remove? 
https://github.com/dotnet/AspNetCore.Docs/issues/19236

**Comment by maryamariyan** [comment]
@Rick-Anderson should this be transferred to dotnet/AspNetCore.Docs repo?

**Comment by Rick-Anderson** [comment]
@maryamariyan  only if the team says this is no longer supported. It's trivial to test and it worked in 1.x for sure and probably 2.x

**Comment by maryamariyan** [comment]
Below shows where we are getting the FormatException:

https://github.com/dotnet/runtime/blob/53976d38b1bd6917b8fa4d1dd4f009728ece3adb/src/libraries/Microsoft.Extensions.Configuration.CommandLine/src/CommandLineConfigurationProvider.cs#L113-L117

The sample in the description which fails uses the workflow of
```C#
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddCommandLine(args, switchMappings);
                })
```

Whereas the doc sample just simply does:
```C#
             var builder = new ConfigurationBuilder();
             builder.AddCommandLine(args, switchMappings);
  
             var config = builder.Build();
```
