### ISSUE TITLE
PhysicalFileProvider leaks memory

### ISSUE THREAD

**Issue by AndreasLudviksen** [dotnet/runtime#36051]
### Describe the bug
We have a component that monitors a file-share continously, and kick off work based on the raised events.
In the process of running .NET Core 3.1 projects as Linux-containers, we encountered issues with the FileSystemWatcher beeing unreliable when monitoring changes on a file-share.
We wanted to move to PhysicalFileProvider, and use the polling-strategy for detecting changes to the file-share we monitor.

The problem is - memory consumed by the process constantly increases when changes happen and events are raised.

We also tried wrapping it in the 'FinalizingPhysicalFileProvider' class mentioned in this bug:
https://github.com/dotnet/extensions/issues/844
But the result is the same.

Can you shed some light on if our approach to this is wrong - is the PhysicalFileProvider not supposed to be used like this ?

### To Reproduce
Test-code that reproduces the issue when changes are made to the monitored file-share:
```
static void Main()
{
	/* OPTION 1 - PhysicalFileProvider - Mem Leak */
	_provider = new PhysicalFileProvider(_path);
	var token = _provider.Watch("*.*");
	_changeToken = token.RegisterChangeCallback(WriteToConsole, null);

	/* OPTION 2 - FileSystemWatcher - No Mem leak */
	//var _watcher = new FileSystemWatcher(_path)
	//{
	//    Filter = "*.*",
	//    NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.FileName
	//};

	//_watcher.Changed += (sender, args) => WriteToConsole(null);
	//_watcher.Deleted += (sender, args) => WriteToConsole(null);
	//_watcher.Renamed += (sender, args) => WriteToConsole(null);
	//_watcher.EnableRaisingEvents = true;

	Console.ReadLine();
}

private static void WriteToConsole(object state) 
{

	Console.WriteLine("WriteToConsole raised");
	
	_changeToken.Dispose();
	var token = _provider.Watch("*.*");
	Console.WriteLine("Registering for token {0}", token.GetHashCode());
	_changeToken = token.RegisterChangeCallback(WriteToConsole, null);
}
```

**Comment by maryamariyan** [comment]
Would you please provider a repo project. Is DOTNET_USE_POLLING_FILE_WATCHER set for polling in your case?

**Comment by carlossanlop** [comment]
Triage:
There are 3 things in the code snippet that should be fixed:
1. The `PhysicalFileProvider` instance is disposable but it is not getting disposed.
2. Same with the `FileSystemWatcher` instance, needs to be disposed.
3. The `WriteToConsole` method keeps disposing the token, then replacing it, but when the process finishes, the last token created will not get disposed.

Does that solve your question @AndreasLudviksen ?

**Comment by AndreasLudviksen** [comment]
@maryamariyan - Yes, we are.

@carlossanlop - Valid points, but it would not explain the memory-buildup while the service is running continously, right?

Background and update:
The service using the FileSystemWatcher is running in a Linux-container in a Kubernetes-environment.
This test was conducted a while back because we had problems with the FileSystemWatcher not picking up on changes made to a container-mounted file-share.
We tried to switch to the PhysicalFileProvider as it had support for polling, and should be more reliable.
However, there was a memory build-up and it eventually ran out of memory.
The scenario was reproduced with the simple code in this issue.
We reverted the change, and worked around the limitations of the FileSystemWatcher.

Now I tested the scenario again, and have two updates.
1. The FileSystemWatcher now seems to receive events, and the service works as before.
2. The PhysicalFileProvider does not seem to leak memory anymore. I ran the same test again, even running GC.Collect in the WriteToConsole method, and there is no build-up.

There has been updates both on the platform (Kubernetes) and .NET runtine (Patch-version) that could affect this.

Thanks for the follow-up. You can close this item.
