### ISSUE TITLE
Feature request: facilitate testing

### ISSUE THREAD

**Issue by fluffynuts** [dotnet/runtime#36057]
## The problem
I'd like to prove that logging has (or has not) happened from within a test. I'm attempting to use an injected NSubtitute for ILogger<T>. Asserting calls is difficult because methods like `LogInformation` are extension methods -- but that's ok, if we can get down to the lowest `Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);` method. The issue here is performing assertions - at this level, `TState` is an instance of `FormattedLogValues`, which is an internal struct. So trying to do assertions has to be done by hackery and trickery, since I can't use. eg `Arg.Is<FormattedLogValues>(...)`

### Describe the solution you'd like
Please publicise `FormattedLogValues` and anything else which would facilitate testing logging

### Describe alternatives you've considered
Hackery -- I can get a list of received calls and work through the arguments manually using reflection

**Comment by maryamariyan** [comment]
@fluffynuts closing as per @anurse 's comment.
Please reopen if you feel like you are still stuck.
