### ISSUE TITLE
DOTNET_SHUTDOWNTIMEOUTSECONDS not respected

### ISSUE THREAD

**Issue by LarsAndreasEk** [dotnet/runtime#36059]
### Setting ShutdownTimeout via environment variable does not affect host shutdown timeout
According to the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#shutdowntimeout), setting the DOTNET_SHUTDOWNTIMEOUTSECONDS as an environment variable should affect graceful shutdown time. Configuring it through code work fine.

### To Reproduce
1. Create new api project from VS template
2. Set the environment variable in debug settings (or otherwise), to a value other than the 5 seconds default.
3. Add an IOptions< HostOptions > dependency to the default created controller and return the ShutdownTimeout.
4. Start in debug.
5. In the browser, see that the value is still 5 seconds.

### Expected behavior
The HostOptions.ShutdownTimeout value should be set to whatever value passed to it by DOTNET_SHUTDOWNTIMEOUTSECONDS.

Tested both with 3.1 and 3.0.1.

Please see attached repro.
[ReproduceShutdownTimeout.zip](https://github.com/dotnet/extensions/files/4164843/ReproduceShutdownTimeout.zip)

**Comment by maryamariyan** [comment]
- [ ] Will need to honour the value on the HostOptions value which comes from configuration.
- [ ] Revisit docs (also for ApplicationName, ContentRoot)

**Comment by ericstj** [comment]
In ASP.NET this was handled by WebHostOptions accepting an IConfiguration and consulting that for values of options.  https://github.com/dotnet/aspnetcore/blob/6afd6f40c043f96c8fb1ee06cbebbc1d229efddc/src/Hosting/Hosting/src/Internal/WebHostOptions.cs#L19-L46

In generic host, the HostOptions doesn't accept an IConfiguration.
https://github.com/dotnet/runtime/blob/e3ffd343ad5bd3a999cb9515f59e6e7a777b2c34/src/libraries/Microsoft.Extensions.Hosting/src/HostOptions.cs#L12

**Comment by galakt** [comment]
@eerhardt @maryamariyan Can you please specify intended way to fix it?
