### ISSUE TITLE
usersecrets are not accessible inside container for worker service project

### ISSUE THREAD

**Issue by pratiksanglikar** [dotnet/runtime#36062]
### Describe the bug
The user secrets for a worker service are not accessible inside docker container.

### To Reproduce
1. Create a new .NET Core 3.0/3.1 WorkerService project using Visual Studio. (Or just clone [this](https://github.com/pratiksanglikar/WorkerService3) repo and jump to step 5)
2. Right click on the project, click "Add Docker Support" select "Linux".
3. Edit the project file and add -
        a. Package reference to `Microsoft.Extensions.Configuration.UserSecrets` as following `<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.1" /> `
Because of this issue [#2743](https://github.com/dotnet/extensions/issues/2743)
        b. A volume mapping of the user secrets directory inside the container by adding following line to the property group - 
`<DockerfileRunArguments>-v "$(AppData)/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"</DockerfileRunArguments>`
4. Modify the file `Worker.cs` to access the user secrets - 
```
 public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly IConfiguration configuration;

        public Worker(ILogger<Worker> logger, IConfiguration configuration)
        {
            _logger = logger;
            this.configuration = configuration;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("The secret - {}", this.configuration["secretKey"]);
                await Task.Delay(1000, stoppingToken);
            }
        }
    }
```
5. On powershell or command prompt, navigate to the project directory and add user secrets using the command -
`dotnet user-secrets set "secretKey" "secretValue"`

6. hit F5 with the Docker debug profile and monitor the output window. Notice that the value of the user secret is null.

**Note:** You can open the Containers window in the VS to check the file contents of the container. 
If you check the path - `/root/.microsoft/usersecrets` you will notice the user-secrets directory with `secrets.json` inside it.

### Expected behavior
The output should print the value of the user-secret.

### Screenshots
![Filesystem and output of the program](https://user-images.githubusercontent.com/1625492/72640926-c0d15300-391d-11ea-842e-085c9095a162.jpg)

![UserSecretIDAttribute in the assembly](https://user-images.githubusercontent.com/1625492/72640973-de062180-391d-11ea-8de9-a4f5a9000ee8.jpg)

### Additional context
Same program with WorkerService debug profile works well.

**Comment by guibranco** [comment]
Any news ?

**Comment by Lesthad** [comment]
I am running into the same issue for a console app running in docker. Any news on this?

**Comment by wzchua** [comment]
There's no issue with the mount. The docker image default `DOTNET_ENVIRONMENT` value is `Production`. If you set it to Development in the `launchSettings.json`, it will work.
```json
    "Docker": {
      "commandName": "Docker",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
```

**Comment by pratiksanglikar** [comment]
@wzchua,
Why worker service's behavior is different than that of ASP.NET application?

**Comment by wzchua** [comment]
when you run the default aspnetcore project with docker. `-e "ASPNETCORE_ENVIRONMENT=Development"` is added to the commandline argument

**Comment by angusmillar** [comment]
Having the same issue here. I can see the problem as explained by @wzchua is that my `DOTNET_ENVIRONMENT` value is not being set. However, I have added the `launchSettings.json` as follows. It just does not pick it up. How else can I set that environment variable?

```json
{
  "profiles": {
    "Iata.Verity.Service": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": "true"
    },
    "Docker": {
      "commandName": "Docker",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/13332180/124085973-eca1b380-da93-11eb-9ec4-cd21c2db4a62.png)

**Comment by jcotton42** [comment]
> ```json
> DOTNET_ENVIRONMENT
> ```

Not that it's a proper fix, but telling Docker directly about it seems to work. For example I have this in my `docker-compose.override.yml` under the node for the relevant service.

```yaml
environment:                      
  - DOTNET_ENVIRONMENT=Development
volumes:                                                               
  - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets/:ro"
```

I also needed the volume definition as it wasn't being mapped by default.

**Comment by maryamariyan** [comment]
> @angusmillar Not that it's a proper fix, but telling Docker directly about it seems to work. For example I have this in my docker-compose.override.yml under the node for the relevant service.

Closing since there seems to be a workaround

**Comment by jcotton42** [comment]
> > @angusmillar Not that it's a proper fix, but telling Docker directly about it seems to work. For example I have this in my docker-compose.override.yml under the node for the relevant service.
> 
> Closing since there seems to be a workaround

Closing this issue is not proper. The Docker tooling should do the setup for user secrets automatically. Please reopen this.

**Comment by maryamariyan** [comment]
> Closing this issue is not proper. The Docker tooling should do the setup for user secrets automatically. Please reopen this.

@MichaelSimons what are your thoughts here?

**Comment by eerhardt** [comment]
cc @mthalman as well.

**Comment by MichaelSimons** [comment]
This seems like a VS Docker Tools issue vs a runtime issue.  I suggested opening an issue at https://github.com/microsoft/dockertools/issues.

**Comment by eerhardt** [comment]
Closing as this is not a dotnet/runtime issue. If someone is blocked on the VS Docker Tools, please open an issue at https://github.com/microsoft/dockertools/issues.
