### ISSUE TITLE
API Proposal: Assembly.GetAssemblyCount()

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#36068]
Returns the number of assemblies loaded in the current process. 

```csharp
public abstract class Assembly
{
    public static int GetAssemblyCount();
}
```

This is already implemented on CoreCLR side and is being used as part of the runtime performance counters. Adding this API as a public API will let customers monitor their current assembly count in-proc without having to write EventListener to consume the counters.

cc @tommcdon @noahfalk @mjsabby

**Comment by MichalStrehovsky** [comment]
`AppDomain.CurrentDomain.GetAssemblies().Length`?

**Comment by ericstj** [comment]
Moving to 6.0 as it's too late for this in 5.0.  Is @MichalStrehovsky's suggestion sufficient or does it have [too much overhead](https://github.com/dotnet/runtime/blob/29e9b5b7fd95231d9cd9d3ae351404e63cbb6d5a/src/coreclr/src/vm/appdomainnative.cpp#L67-L120) for your scenario?

**Comment by sywhang** [comment]
Thanks @ericstj - I think @MichalStrehovsky's suggestion is good for now unless we hear feedback regarding its perf overhead. I can bring back this discussion if I do hear such feedback. I'll close this issue for now.
