### ISSUE TITLE
API Proposal: System.Diagnostics.Process.GetCpuUsage()

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#36069]
Returns the current CPU usage of the process as a percentage.

```csharp
public class Process
{
    public static int GetCpuUsage();
}
```

This is already implemented on CoreCLR side and is being used as part of the runtime performance counters. Adding this API as a public API will let customers monitor their current CPU usage in-proc without having to write EventListener to consume the counters.

cc @tommcdon @noahfalk @mjsabby

**Comment by jkoritzinsky** [comment]
I believe the managed thread pool could use this instead of its current implementation of getting CPU utilization.

**Comment by jkotas** [comment]
What is this API going to return exactly and how it is going to be computed?

> This is already implemented on CoreCLR side and is being used as part of the runtime performance counters.

Note that the implementation for performance counters returns the CPU utilization since the last time the API was called. I do not think that is a good contract for a public API.

**Comment by noahfalk** [comment]
@mjsabby - I think you would already have the public APIs you need for this one and the BCL doesn't need to add anything? The factoring inside the runtime is slightly different but conceptually CpuUsage counter is:

````
System.Diagnostics.Process p = Process.GetCurrentProcess();
StopWatch s = new Stopwatch();
TimeSpan cpuA = p.TotalProcessorTime;
s.Start();
// wait some time interval you want to measure
TimeSpan cpuB = p.TotalProcessorTime;
s.Stop();
return (cpuB - cpuA) * 100.0F / s.Elapsed;
````

Also agreed with Jan, if we had an API here, I don't think we could model it as a an instantaneous calculation. The cpu-usage calculation is only well defined over a time interval.

**Comment by mjsabby** [comment]
Correct, this one is implementable with current APIs.

**Comment by noahfalk** [comment]
Thanks @mjsabby - I'm taking to that mean no objections to closing the issue and directing users interested in this scenario to use the pre-existing APIs via the snippet I suggested above. If I misinterpreted let me know.
