### ISSUE TITLE
API Proposal: System.Exception.GetTotalExceptionCount()

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#36071]
Get the total exception count of the process.

```csharp
public class Exception
{
    public static int GetTotalExceptionCount();
}
```

This is already implemented on CoreCLR side and is being used as part of the runtime performance counters. Adding this API as a public API will let customers monitor the process' exception count in-proc without having to write EventListener to consume the counters.

cc @tommcdon @noahfalk @mjsabby

**Comment by MichalStrehovsky** [comment]
It a new API really necessary? This can already be achieved using .NET Standard 2.0 APIs.

```csharp
class Program
{
    static int s_counter;

    static void Main()
    {
        AppDomain.CurrentDomain.FirstChanceException += new EventHandler<FirstChanceExceptionEventArgs>((o, a) =>
        {
            Interlocked.Add(ref s_counter, 1);
        });

        try
        {
            throw new Exception();
        }
        catch
        {
        }

        Console.WriteLine(s_counter);
    }
}
```
