### ISSUE TITLE
TCPKeepAlive on Linux not working

### ISSUE THREAD

**Issue by AV25242** [dotnet/runtime#36075]
I am reaching out as a followup to this [issue](https://github.com/dotnet/runtime/issues/24041) as already closed but with some open questions. This issue was fixed for .NET Core 3.0 but  it doesn't look like it was fixed for .netstandard which our application uses and we cannot move off it at this moment.

Can someone please advice when this would be made available for .netstandard ? or what is the roadmap for it to be available.

Below is the test that we had performed on AWS EC2 Instance and on Linux CentOs Instance both showed the same results
**Setup**
       In the Client Configuration for Couchbase in the .NET application
       Enabled TCPKeepAlive with a
       Probe-Interval of 1 Second and
       Keep Alive time of 10 minutes.

Attached is the TCP dump from the server that clearly says that there were no tcp-keep-alive requests made.

<img width="1780" alt="Linux EC2" src="https://user-images.githubusercontent.com/5351738/81355826-47f53300-9095-11ea-8391-ba96d7e84f12.png">

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/standard/issues/1474
