### ISSUE TITLE
[Extensions.Options] ValidateDataAnnotation doesn't work when classes have properties that also have DataAnnotations on their members

### ISSUE THREAD

**Issue by ardove** [dotnet/runtime#36093]
### Describe the bug
When using ValidateDataAnnotations to validate a configuration hierarchy, you can only validate top level members of the class. Any properties that are types which also include validation are NOT validated. 

Perhaps this was viewed as a design decision, but I think it'd be a lot more consistent if automatic data annotation validation worked in the same fashion as mvc model validation.

### To Reproduce
1. Design the classes which represent the nested configuration
```c#
public class AnnotatedOptions
{
    [Required]
    public string Required { get; set; }

    [StringLength(5, ErrorMessage = "Too long.")]
    public string StringLength { get; set; }

    [Range(-5, 5, ErrorMessage = "Out of range.")]
    public int IntRange { get; set; }

    public AnnotatedOptionsSubsection AnnotatedOptionSubsection { get; set; }
}

public class AnnotatedOptionsSubsection
{
    [Range(-5, 5, ErrorMessage = "Really out of range.")]
    public int IntRange2 { get; set; }
}
```
2. Register the options
```c#
var services= new ServiceCollection();
services
     .AddOptions<AnnotatedOptions>()
     .Configure(o =>
                {
                    o.StringLength = "111111";
                    o.IntRange = 10;
                    o.AnnotatedOptionSubsection = new AnnotatedOptionsSubsection
                    {
                        IntRange2 = 10000
                    };
                })
       .ValidateDataAnnotations();
```
3. Set up a controller which retrieves the options
```c#
[Route("api/[controller]")]
[ApiController]
public class ConfigController : ControllerBase
{
    private readonly AnnotatedOptions _configuration;

    public ConfigController(IOptionsMonitor<AnnotatedOptions> configuration)
    {
        try
        {
            _configuration = configuration.CurrentValue;
        }
        catch (OptionsValidationException ex)
        {
            throw new Exception(string.Join(@"\r\n", ex.Failures), ex);
        }
    }

    // GET api/config/
    [HttpGet("{configKey}")]
    public ActionResult<AnnotatedOptions> Get()
    {
        return _configuration;
    }
}
```

4. Invoke the controller method and observe the error results
````
System.Exception: DataAnnotation validation failed for members Required with the error 'The Required field is required.'.
DataAnnotation validation failed for members StringLength with the error 'Too long.'.
DataAnnotation validation failed for members IntRange with the error 'Out of range.'. ---> Microsoft.Extensions.Options.OptionsValidationException: Exception of type 'Microsoft.Extensions.Options.OptionsValidationException' was thrown.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.get_CurrentValue()
   at PF.ClinicalEndpoint.Host.Controllers.ConfigController..ctor(IOptionsMonitor`1 configuration) in C:\dev\test\ClinicalEndpoint\src\Host\Controllers\ConfigController.cs:line 19
   --- End of inner exception stack trace ---
   at PF.ClinicalEndpoint.Host.Controllers.ConfigController..ctor(IOptionsMonitor`1 configuration) in C:\dev\test\ClinicalEndpoint\src\Host\Controllers\ConfigController.cs:line 23
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at PF.Core.WebApi.Middleware.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext)
   at PF.Core.WebApi.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Expected behavior
Another error in the list of failures for the `IntRange2` field which reads as follows
`DataAnnotation validation failed for members IntRange2 with the error 'Really out of range.'`

**Comment by mronnblom-cint** [comment]
Somewhat related to https://github.com/dotnet/runtime/issues/36391.

**Comment by jcotton42** [comment]
I am also having this issue.

**Comment by alexb5dh** [comment]
Found a workaround for nested objects based on similar [StackOveflow question](https://stackoverflow.com/questions/7663501/dataannotations-recursively-validating-an-entire-object-graph) and corresponding [Nuget package](https://www.nuget.org/packages/DataAnnotationsValidator/). It works for nested objects, arrays and dictionaries but requires some preparation:
- Installing the package: `Install-Package DataAnnotationsValidator` or copying the code from the [repository](https://github.com/reustmd/DataAnnotationsValidatorRecursive)
- Creating custom options validator: 
```
public class RecursiveDataAnnotationValidateOptions<TOptions>: IValidateOptions<TOptions> where TOptions: class
{
    private readonly DataAnnotationsValidator.DataAnnotationsValidator _validator = new();

    public RecursiveDataAnnotationValidateOptions(string name) => Name = name;

    public string Name { get; }

    public ValidateOptionsResult Validate(string name, TOptions options)
    {
        if (name != Name)
            return ValidateOptionsResult.Skip;

        var results = new List<ValidationResult>();
        if (_validator.TryValidateObjectRecursive(options, results))
            return ValidateOptionsResult.Success;

        var stringResult = results
            .Select(validationResult =>
                $"DataAnnotation validation failed for members: '{string.Join(",", validationResult.MemberNames)}' with the error: '{validationResult.ErrorMessage}'."
            ).ToList();

        return ValidateOptionsResult.Fail(stringResult);
    }
}
```
- Creating extension method for it:
```
public static OptionsBuilder<T> ValidateDataAnnotationsRecursively<T>(this OptionsBuilder<T> builder) where T: class
{
    builder.Services.AddSingleton<IValidateOptions<T>>(new RecursiveDataAnnotationValidateOptions<T>(builder.Name));
    return builder;
}
```

Usage should be simple - just replace calls of `ValidateDataAnnotations` to `ValidateDataAnnotationsRecursively`.

**Comment by ardove** [comment]
I know that it's possible to fix, but this should be part of the .NET runtime. Not an extension method I need to copy to every application I ever work on.

**Comment by bgillet** [comment]
> I know that it's possible to fix, but this should be part of the .NET runtime. Not an extension method I need to copy to every application I ever work on.

Options is part of every applications. Some may have lots of. Nesting options is obvious in this case as it helps sorting them. It is even the purpose of the Option pattern. And adding lots of options in the DI to avoid nesting them is not a good idea because you may have a service using many of them and this will result in a method declaration with lots of parameters for each options you need instead having only one option "registry" you can navigate into.

**Comment by maryamariyan** [comment]
It would be good to address this in 7.0.

**Comment by mronnblom-cint** [comment]
@maryamariyan It feels very weird to me to include https://github.com/dotnet/runtime/issues/36391 in release 6 but not this issue. I guess it's too late now though. An idea is to at least add to the [documentation for Options Validation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#options-validation) that it (currently) only validates fields on the top Options class, not fields in nested Options classes.

**Comment by rurounijones** [comment]
Just came across this issue and am quite flabberghasted and annoyed that recursive validation does not take place nor is there an option to set it. It has cost me a decent chunk of time trying to figure out why my tests were failing.

I echo the request to _at least_ document this to save others frustration time.

Another request would be why this was removed from the 6.0.0 milestone. Are inclusions in these milestones not commitments but "best effort" ?

**Comment by LionelVallet** [comment]
For Options validation, you can use [this NuGet package](https://www.nuget.org/packages/ReHackt.Extensions.Options.Validation) ([source and docs (GitHub)](https://github.com/LionelVallet/ReHackt.Extensions.Options.Validation)) until the release of .NET 7 (or 8, 9...).

It is compatible with .NET Standard 2.0, .NET Core 3.1, .NET 5 and .NET 6.

It provides two `OptionBuilder` extension methods:
- `ValidateDataAnnotationsRecursively`: based on Microsoft.Extensions.Options.DataAnnotations, but it can even validate nested properties
- `ValidateOnStart`: call Microsoft.Extensions.Hosting method in version 6, but custom code in previous .NET version


And a `ServiceCollection` extension method:

``` csharp
services.ConfigureAndValidate<TOptions>(configureOptions)
```
  
which is syntactic sugar for

``` csharp
services
    .AddOptions<TOptions>()
        .Configure(configureOptions) // Microsoft
        .ValidateDataAnnotationsRecursively() // based on Microsoft's ValidateDataAnnotations, but supports nested properties
        .ValidateOnStart() // Microsoft (.NET 6) or ValidateEagerly() in previous versions
        .Services
```

**Comment by rdewaele** [comment]
I also came across this issue and would like to have seen at least a large disclaimer that this does not work as one would reasonably expect from a released (finished?) product. I agree with https://github.com/dotnet/runtime/issues/36093#issuecomment-755586930

I came up with my own workaround, where the only requirement is that all option types are defined in the same namespace.
It's tuned to my specific needs, but maybe it is useful to someone. :slightly_smiling_face: 

(The namespace requirement  is just one way to prioritize specificity over sensitivity - matching e.g. a string is evidently wrong and will even result in a runtime exception. Finer tuned approaches could check for the presence of annotations on the members, for example.)

```
public static class ServiceConfiguration
{
  private static readonly MethodInfo HelperMethod =
    typeof(ServiceConfiguration).GetMethod(nameof(AddValidatedOptions), BindingFlags.Static | BindingFlags.NonPublic)
    ?? throw new InvalidOperationException("famously, this should not happen");

  public static IServiceCollection AddValidatedOptions<TOptions>(this IServiceCollection services, string sectionPath)
    where TOptions : class
  {
    var @namespace = typeof(TOptions).Namespace
                     ?? throw new ArgumentException("could not get namespace of type", nameof(TOptions));
    AddValidatedOptions<TOptions>(services, sectionPath, @namespace);
    return services;
  }

  private static void AddValidatedOptions<TOptions>(IServiceCollection services, string sectionPath, string @namespace)
    where TOptions : class
  {
    services
      .AddOptions<TOptions>()
      .BindConfiguration(sectionPath)
      .ValidateDataAnnotations()
      .ValidateOnStart();

    foreach (var pi in typeof(TOptions).GetProperties(BindingFlags.Instance | BindingFlags.Public))
    {
      bool skip = !pi.PropertyType.IsClass
                  || string.CompareOrdinal(pi.PropertyType.Namespace, @namespace) != 0;
      if (skip)
      {
        continue;
      }

      string currentPath = string.Join(':', sectionPath, pi.Name);
      HelperMethod.MakeGenericMethod(pi.PropertyType)
        .Invoke(null, new object[] { services, currentPath, @namespace });
    }
  }
}
```

Use as follows:
```
services.AddValidatedOptions<ComplexOption>("path:to:complex:option:that:is:probably:way:shorter:than:this:example");
```

If you decide to keep the `ValidateOnStart` call, make sure to call this before adding any hosted services. (`ValidateOnStart` adds a hosted service of its own to implement this functionality, and you likely want to run that one first.)

Lastly, this is a recursive implementation, so don't go and use this with configuration files that nest ... _a lot_ of objects. (What kind of monster would do that?)

**Comment by CodeBlanch** [comment]
I could be mistaken, but I think the `ValidateDataAnnotations` behavior is in sync with how `System.ComponentModel.DataAnnotations.Validator` itself works. I'm not arguing the behavior is _good_, but I think creating inconsistency might be surprising.

Example...

```csharp
	public class MyModel
	{
		[Required]
		public string? Id { get; set; }

		public MySubmodel? PrimarySubmodel { get; set; }

		public IEnumerable<MySubmodel>? ExtraSubmodels { get; set; }
	}

	public class MySubmodel
	{
		[Required]
		public string? Name { get; set; }
	}

	MyModel invalidModel = new()
	{
		PrimarySubmodel = new(),
		ExtraSubmodels = new[] { new MySubmodel(), new MySubmodel() }
	};

	List<ValidationResult> results = new();

	bool isValid = Validator.TryValidateObject(invalidModel, new ValidationContext(invalidModel), results);

	// isValid is false (expected) but results only contains a single error, that Id was missing.
```

Maybe a better solution is to add something in `System.ComponentModel.DataAnnotations` which could be used universally?

```csharp
	public class MyModel
	{
		[Required]
		public string? Id { get; set; }

		[ValidateComplexObject] // System.ComponentModel.DataAnnotations.ValidateComplexObjectAttribute
		public MySubmodel? PrimarySubmodel { get; set; }

		[ValidateEnumerable] // System.ComponentModel.DataAnnotations.ValidateEnumerableAttribute
		public IEnumerable<MySubmodel>? ExtraSubmodels { get; set; }
	}
```

**Comment by SteveDunn** [comment]
@maryamariyan I'm happy to look at this one

**Comment by SteveDunn** [comment]
The default behaviour after this PR is to validate recursively. Would this be classed as a breaking change? If so, and we add an overload to force recursion, would this require an API Proposal?

**Comment by SteveDunn** [comment]
The linked PR addresses this issue but has been dormant for a while. It also seems that fixing this _might be_ a 'breaking change'...

**Comment by jchannon** [comment]
Just hit this!!

**Comment by tzachihakmon** [comment]
Hey, any news with solution for that issue?

**Comment by SteveDunn** [comment]
I'm still keen to work on this. I don't know if a decision has yet been made on which form this validation should take, and where it should live.

**Comment by eerhardt** [comment]
https://github.com/dotnet/runtime/issues/85475 is adding a `ValidateTransitivelyAttribute` which would handle this case. There is a [question](https://github.com/dotnet/runtime/issues/85475#issuecomment-1531930293) about whether that attribute should live in `System.ComponentModel.DataAnnotations` or in `Microsoft.Extensions.Options`.

cc @jeffhandley @DamianEdwards @tarekgh

**Comment by cremor** [comment]
I agree, it would be even more confusing in .NET 8 if `ValidateObjectMembersAttribute` exists but only works for the new source generator way of validation.

**Comment by cremor** [comment]
It seems like this will be fixed in .NET 8 with the new attribute `ValidateObjectMembersAttribute`, see #90275

**Comment by tarekgh** [comment]
Closing this as completed by https://github.com/dotnet/runtime/pull/90275. Thanks @cremor for noticing that.
