### ISSUE TITLE
IDistributedCache Support for  `Collection` 

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#36095]
Both SqlServer and Redis can implement for `Collection` cache ,  and even union support.
Please consinder for  add follow api
```
interface IDistributeCache
{
  ...
  IEnumerable<byte[]> GetCollection(string key)
  RemoveCollection(string key);
  void LPushCollection(string key, byte[] item, Opitons option)
  void RPushCollection(string key, byte[] item, Opitons option)
  byte[] LPopCollection(string key)
  byte[] RPopCollection(string key)
}

```

**Comment by John0King** [comment]
@anurse  
> Adding a new API to IDistributedCache would be extremely breaking

theoretically ：  yes, 
fact : no

when people upgrade to a new .net core  /asp.net core,  there are always breaking changes,
for example : EF Core  update,   but  when EF update ,   the EFCore.SqlServer,  EFCore.Sqlite , EFCore.InMemory,  and third party like  'EFCore.Npgsql'  also update.
This is not some kind of  remove features,   for example :  MVC to MVC core ,  signalR  to signalR Core (it's bad example, they are 2 frameworks ),  there are manage feature and api not exists in the new api, and I believe people actually need this collection support in caching and they goes to native Redis client library for this feature.

**Comment by adamsitnik** [comment]
> Adding a new API to `IDistributedCache` would be extremely breaking so I don't think it's likely, but I'll transfer it over for tracking on the backlog in the dotnet/runtime repo.

Yes, it would be a breaking change. Since there were not upvotes or any other feedback from other users for over three years I am going to close the issue. I am sorry, but we are not going to implement it in the near future. Thanks!
