### ISSUE TITLE
Modify System.Timers.Timer ctor to accept TimeSpan parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#361]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/632496/modify-systemtimerstimer-ctor-to-accept-timespan-p.html)._

---
Too frequently I write code like this:

```
s_enableTimer = new System.Timers.Timer(TimeSpan.FromSeconds(50). TotalMilliseconds);
```

Would be cleaner if I could just write:

```
s_enableTimer = new System.Timers.Timer(TimeSpan.FromSeconds(50));
```

Similar to:

```
Thread.Sleep(TimeSpan.FromSeconds(5));
```

---
#### Jane Wu [MSFT] on 7/4/2019, 02:54 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by Gnbrkm41** [comment]
Related: https://github.com/dotnet/corefx/issues/1118. It's one of the long-standing issues that could be worth considering.

**Comment by Gnbrkm41** [comment]
Perhaps the `Interval` property could be exposed as TimeSpan as well, just for completeness' sake? Obviously it wouldn't be possible to expose it as an overload (since it's a property), so that's one problem.

**Comment by stephentoub** [comment]
This now exists
