### ISSUE TITLE
nethost backward compatibility

### ISSUE THREAD

**Issue by MxGrv** [dotnet/runtime#36109]
Since nethost provides get_hostfxr_path(), which returns path to the hostfxr.dll only for the recent version of .NET Core, is there any option to tell it to target older versions?

`hostfxr_initialize_for_runtime_config_fn` does actually only work if the current version of dotnet is the same as the one stated in the provided *.runtimeconfig.json, as when we later successfully obtain the pointer to the `load_assembly_and_get_function_pointer_fn` function (using `hostfxr_get_runtime_delegate_fn`), it does work properly. Whereas if we provide *.runtimeconfig.json, generated with the assembly of the older version, it is actually swallowed with success return value == 0, but when we later try to get a delegate for that assemblie's method, the 0x80070002 error code is returned.

To be more clear and specific, [the way](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#create-a-host-using-nethosth-and-hostfxrh) adviced:
1. Windows 10, 64-bit, dotnet installed in "C:\Program Files\dotnet", versions 3.0 (3.0.0 actually, via 3.0.100 SDK) and 3.1 (3.1.3 actually, via 3.1.201 SDK)
2. `get_hostfxr_path()` naturally returns "C:\Program Files\dotnet\host\fxr\3.1.3\hostfxr.dll"
3. Using the `LoadLibrary()` and `GetProcAddress()` we successfully obtain `hostfxr_initialize_for_runtime_config_fn`, `hostfxr_get_runtime_delegate_fn`, and `hostfxr_close_fn` pointers
4. `hostfxr_initialize_for_runtime_config_fn` receives either ***.runtimeconfig.json of version 3.1 (latest)**, or **of version 3.0 (older)**; in both cases, passing `hdt_load_assembly_and_get_function_pointer` to the delegate getter, we successfully obtain the `load_assembly_and_get_function_pointer_fn` function pointer
5. When trying to obtain a delegate for a custom assembly:
5.1. If the assembly is **of version 3.1**, we succeed.
5.2. If the assembly is **of version 3.0**, we fail with return code 0x80070002. Well, despite the config file for **version 3.0** has been **successfully** accepted by the **3.1.3 hostfxr**, not a single delegate could be obtained.

By the way, 0x80070002, which stands for "File not found", appears to be unclear, in contrast to 0x80131509, which stands for actual "Assembly not found" (that is really quite entangling). And in case of cdb debugger, 0x80070002 begets a bunch of exceptions, like these:
```
Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!GetCLRRuntimeHost

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!coreclr_shutdown_2

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in ntdll!RtlCaptureContext

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!coreclr_shutdown_2

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in ntdll!RtlCaptureContext

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!coreclr_shutdown_2

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in ntdll!RtlCaptureContext

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!coreclr_shutdown_2

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in ntdll!RtlCaptureContext

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!coreclr_shutdown_2

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in ntdll!RtlCaptureContext

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in coreclr!coreclr_shutdown_2

Exception at 0x7ffd6d71a799, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in ntdll!RtlCaptureContext
```

So:
1. Is there any possibility to redirect `get_hostfxr_path()` to the older versions, besides the "brutal" manual path providing? For example, using the get_hostfxr_parameters struct? (anyway it's description is far for clear)
2. How come that 3.0 runtime config is successfully eaten by the 3.1.3 hostfxr, but no delegate can actually be retrieved and such a weird error is returned? I mean, is it supposed to be supported at this step? It seems to me that the 3.1.3 hostfxr.dll cannot redirect 3.0 environment deployment to the 3.0.0 hostfxr.dll, can it?

**Comment by vitek-karas** [comment]
The hosting APIs should work on 3.0 as well, but there were some fixes specifically around self-contained applications in 3.1. If the host application is self-contained for example there might be problems when running on 3.0 (in some specific cases).

You can get a detailed trace of what's going on by setting `COREHOST_TRACE=1` and `COREHOST_TRACE=host_trace.txt`. Run the failing scenario and the `host_trace.txt` should contained detailed information how far the system got in the hosting world. If the failure is coming from the managed code, you should be able to attach a managed debugger and stop on managed exceptions (as pretty much all failures should show up as managed exception first).

Also of note: .NET Core 3.0 is out of support, why do you need to support it still?

**Comment by MxGrv** [comment]
Setting COREHOST_TRACE=1 and COREHOST_TRACEFILE=report.txt for my C++ helped me understand that I was misusing the nethost API. Everyone who receives 0x80070002, in case they see this thread, check if you are supplying consistent configuration (in my case it all went visa-versa - using Mono.Cecil for assemblies modification, I supplied runtime config json file for the assembly to be modified while config for my assembly, which actually performs modification, was needed 🤦‍♂️🤦‍♂️🤦‍♂️ never neglect having a break). Thank you, @vitek-karas !
