### ISSUE TITLE
VS insertion federation: insert Runtime into VS separately for SDK simplification

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3610]
To simplify SDK delivery, the Runtime needs to be able to service and insert into VS independently.

As of writing, the plan for 3.0 is for VS insertion tooling to be developed in Arcade with Core-SDK using it first, and then used in Core-Setup.

More info at https://github.com/dotnet/core-sdk/issues/2166.

**Comment by NikolaMilosavljevic** [comment]
Closing - obviated by a planned optional components workloads work.
