### ISSUE TITLE
Specify SizeConst when marshalling field as ByValArray

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#36134]
When marshalling using `UnmanagedType.ByValArray`, the `SizeConst` field should be specified.

```C#
struct MyStruct
{
    [MarshalAs(UnmanagedType.ByValArray)]
    int[] Foo;
}
```

**Category:** Interoperability
**Default:** Enabled

cc @terrajobst @stephentoub @AaronRobinsonMSFT @jkoritzinsky

**Comment by elinor-fung** [comment]
Also `UnmanagedType.ByValTStr`

**Comment by AaronRobinsonMSFT** [comment]
I think any of these type of requirements should be in some analyzer.

**Comment by terrajobst** [comment]
* The analyzer should probably also handle `UnmanagedType.ByValTStr`
    - Should be the same diagnostic ID with a slightly different message
* Assuming code like this wouldn't work at runtime, turning the rule on by default seems fine
    - If code like this works today, then on by default might be noisy

**Comment by jkoritzinsky** [comment]
Roslyn already requires `SizeConst` for `ByValTStr`. Should we instead extend Roslyn to also require `SizeConst` for `ByValArray` instead of writing a separate analyzer?
