### ISSUE TITLE
Regex is incorrectly handling casing of some ranges

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#36149]
```C#
using System;
using System.Text.RegularExpressions;

class Program
{
    static void Main()
    {
        Console.WriteLine(Regex.IsMatch("\xF7", @"^(?i:[\xD7\xD8])$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant));
        Console.WriteLine(Regex.IsMatch("\xF7", @"^(?i:[\xD7-\xD8])$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant));
    }
}
```

The above two patterns should be identical, with on character set containing \xD7 and \xD8 and the other containing the range from \xD7 through \xD8 (which is just \xD7 and \xD8, since there's nothing in between them).

However, the first correctly prints `false` whereas the second incorrectly prints `true`.

The implementation handles casing by creating a character class that's the lowercased version of the original.  That means that for individual characters, it just adds the lowercase character:
https://github.com/dotnet/runtime/blob/fd82afe3826d7778a46bda33db4b6e92de679a05/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexCharClass.cs#L554-L555
and for ranges it needs to add the lowercase character for each character in the range:
https://github.com/dotnet/runtime/blob/fd82afe3826d7778a46bda33db4b6e92de679a05/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexCharClass.cs#L559

In the first case above, it follows the first path, adding in the ToLower(\xD7) (which is just \xD7) and the ToLower(\xD8) (which is \xF8).

In the second case, however, it follows the second path, and ends up incorrectly adding a range from \xF7 through \xF8.

As a result, the second case ends up incorrectly matching \xF7.

cc: @eerhardt, @pgovind

**Comment by pgovind** [comment]
Just adding some notes here: The range `/xD7 - /xD8` is `215 - 216` in terms of `int`s. `char.ToLower(/xD7)` is `/xD7` i.e. `215`. `char.ToLower(/xD8)` is however `248`. So, we end up adding the range `215-248` in the 2nd case, which is why we can match `/xF7` (which has the int value `247`)

**Comment by GrabYourPitchforks** [comment]
`U+00D7` is a symbol (see https://www.fileformat.info/info/unicode/char/00d7/index.htm), so it doesn't have an associated case.

You'll occasionally see symbols and other non-alpha characters sitting in the middle of character blocks. You'll also see some ranges where the uppercase and lowercase variants aren't separated by 32. For example, **Ģ** (`U+0122`) is the uppercase form of **ģ** (`U+0123`). That's a separation of only 1 code point, not 32 code points.

Best thing to do might be to case-map each code point independently, then see if you can generate any ranges from those maps. For example, consider that you're given the regex "allow 100 - 109, case-insensitive." And the lowercase mappings are as follows:

```txt
; examples only
100 -> 132
101 -> 133
102 -> 134
103 -> 103 ; symbol, not an alpha character
104 -> 135
105 -> 136
106 -> 137
107 -> 138
108 -> 139
109 -> 140
```

Then ideally we'd add the ranges `[100 - 109]`, `[132 - 134]`, and `[135 - 140]` (all inclusive) to the match list. With some additional logic we could compact overlapping or adjacent ranges.

Also worth pointing out: `string.Contains(a, b, StringComparison.OrdinalIgnoreCase)` normalizes to _uppercase_ before performing the check. Has `Regex.IsMatch(..., IgnoreCase)` always normalized to _lowercase_? This could result in `string.Contains` and `Regex.IsMatch` returning different results for the same inputs. It might be worth investigating getting these two implementations in sync so as not to surprise callers.

**Comment by GrabYourPitchforks** [comment]
BTW, here are the two resources I use for getting information on Unicode code points.

https://unicode.org/cldr/utility/character.jsp is the authoritative source. It also has click-through navigation, so you can ask for things like "show me all code points which, when uppercased, convert to the code point I'm looking at right now." To use it, either paste the character itself into the text box at the top of the page, or write it as a hex-formatted number (padded to at least 4 digits, no 0x prefix). Example: __`00D7`__ or __`12345`__.

https://www.fileformat.info/info/unicode/char/0000/index.htm is also a useful resource. It will show you the UTF-8 or UTF-16 encodings of the scalar value, and it will also show you the best attempt at rendering the glyph, even if you don't have an appropriate font pack installed locally. To use it, replace the "0000" in the URL above with the hex-formatted number for your code point (padded to at least 4 digits, no 0x prefix). Example: __/00D7/index.htm__ or __/12345/index.htm__.

**Comment by stephentoub** [comment]
> Has Regex.IsMatch(..., IgnoreCase) always normalized to lowercase?

Yup

**Comment by pgovind** [comment]
#42282 is being reverted in https://github.com/dotnet/runtime/pull/59425. Re-opening this issue.

**Comment by joperezr** [comment]
I have validated that https://github.com/dotnet/runtime/pull/67184 fixes this
