### ISSUE TITLE
DataContractSerialization is not linker friendly

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#36154]
See this comment:

https://github.com/dotnet/runtime/blob/890fab0a640503201eed977f8710f23ce78987b6/src/libraries/System.Private.DataContractSerialization/src/System.Private.DataContractSerialization.csproj#L10-L11

This setting only applies to running the linker during the `dotnet/runtime` build. It doesn't affect when a user's application uses this library and is trimmed.

If there is too much private reflection for this assembly to be trimmed, it isn't going to work well when an application using it is trimmed. We should ensure DataContractSerialization can be used safely by linked applications.

**Comment by HongGit** [comment]
The code is too intricate to be trimmed safely.

**Comment by eerhardt** [comment]
We should annotate the API with `[RequiresUnreferencedCode]` attributes then, so someone who is trimming their app gets warnings when they call this code.

**Comment by HongGit** [comment]
@eerhardt are you going to do this work?  Can you please assign a milestone to this issue?

**Comment by eerhardt** [comment]
> @eerhardt are you going to do this work?  Can you please assign a milestone to this issue?

I'm not sure who will actually do the work. But there will be an effort to get the libraries annotated in 6.0, so I moved it to there.

**Comment by eerhardt** [comment]
This has been addressed with #50619 and #51200. Closing.
