### ISSUE TITLE
Link on the Core Setup links to fx not setup

### ISSUE THREAD

**Issue by jdm7dv** [dotnet/runtime#36171]
On the .NET Core 2.03 release the setup links to fx @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@leecow

**Comment by leecow** [comment]
@jdm7dv - 2.0 is out of support and we generally do not maintain resources in such a case. That said, where is the link you are referring to?

**Comment by NikolaMilosavljevic** [comment]
@jdm7dv, can you clarify which links are pointing to the wrong location?

**Comment by NikolaMilosavljevic** [comment]
Closing - not actionable.

**Comment by NikolaMilosavljevic** [comment]
Closing for now. Please open a new issue with more information.
