### ISSUE TITLE
.NET Core 1.0.4

### ISSUE THREAD

**Issue by jdm7dv** [dotnet/runtime#36173]
CoreCLR for 1.0.4 tag is 1.0.6 needs to be 1.0.4

**Comment by joperezr** [comment]
cc @leecow do you mind taking a look? seems like they are referring to this tag: https://github.com/dotnet/coreclr/releases/tag/v1.0.6

**Comment by leecow** [comment]
I recall instances where CoreCLR had to be built and the versioned bumped between releases leading to this state though I don't recall the reasons. @wtgodbe, I know this was before your time but, any thoughts?

**Comment by wtgodbe** [comment]
I don't remember what the reason was, but the version of CoreClr was definitely out of sync with the version of .Net Core in the 1.0 era - I think it was always off by 2 (e.g. v1.0.6 of CoreClr was part of .Net Core 1.0.4). Maybe @janvorli or @jkotas might remember the historical reason for that?

**Comment by jkotas** [comment]
I do not remember the details.

Closing this issue. .NET Core 1.0 is out of support and we are not going to touch anything related to it.
