### ISSUE TITLE
FormatterServices.GetUninitializedObject allows creating boxed Nullable<T> instances

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#36187]
On https://try.dot.net/:

```cs
using System;
using System.Runtime.Serialization;

class Program
{
    static void Main(string[] args)
    {
        var o = FormatterServices.GetUninitializedObject(typeof(int?));
        Console.WriteLine(o.GetType()); // prints "System.Nullable`1[System.Int32]"
    }
}
```

It turns out it's creating a `Nullable<T>` (with `HasValue = true`, `Value = default(T)`), then boxing that `Nullable<T>` instance.

I can't repro this on a normal coreclr build. Perhaps the behavior is unique to Mono or CoreRT? I don't quite know how to investigate this.

---

*Edit*

Expected output is
```
System.Int32
```

**Comment by jkotas** [comment]
try.dot.net runs on Mono

**Comment by MichalStrehovsky** [comment]
> Perhaps the behavior is unique to Mono or CoreRT?

FWIW CoreRT doesn't have the bug either:

https://github.com/dotnet/corert/blob/7c80d180073674d495ae88b6bfc6b8a9f9ff51fb/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreRT.cs#L302-L305

**Comment by lambdageek** [comment]
There's a check for `Nullable<T>` in mono's `GetUninitializedObjectInternal` icall 

https://github.com/dotnet/runtime/blob/master/src/mono/mono/metadata/icall.c#L1395

Not yet clear why it's not doing the right thing

**Comment by GrabYourPitchforks** [comment]
Can no longer repro on my local box. Possibly fixed by https://github.com/mono/mono/pull/13391?

**Comment by SamMonoRT** [comment]
Can't repro. Closing the issue.
