### ISSUE TITLE
Review and update THIRD-PARTY-NOTICES.TXT

### ISSUE THREAD

**Issue by leecow** [dotnet/runtime#3619]
Review and update repo THIRD-PARTY-NOTICES.TXT as appropriate. Work should be completed for Preview 7.

**Comment by Anipik** [comment]
@NikolaMilosavljevic any update on this one ?

**Comment by Anipik** [comment]
Can close this after we merge https://github.com/dotnet/runtime/pull/42989

**Comment by jeffschwMSFT** [comment]
Closing via https://github.com/dotnet/runtime/pull/42989
