### ISSUE TITLE
How can I packaging the SCD exe project use setup project

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/runtime#36193]
I use the setup project to build the msi file,but I want to publish the SCD type,,,I use the setup project's "PublishItemsOutputGroup" type,it only package the normal file,not contain the .net core framework files, How can I do this??

**Comment by NikolaMilosavljevic** [comment]
@kugarliyifan , can you provide more detailed steps to reproduce this issue? Is this a Visual Studio scenario?

**Comment by NikolaMilosavljevic** [comment]
Closing for now. Please open a new issue or reply with more information.
