### ISSUE TITLE
High Efficiency Image File Format format in .NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#362]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/666347/high-efficiency-image-file-format-format-in-net.html)._

---
<p>Provide System.Drawing image conversion for HEIF/HEIC files to jpeg, etc.</p>

---
#### Jane Wu [MSFT] on 7/30/2019, 11:46 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by wjk** [comment]
I don't know how practical this is going to be. IIRC the HEIF/HEIC file formats are patented and require royalty payments to legally support.

**Comment by danmosemsft** [comment]
Is there a reason this has to be in System.Drawing?

**Comment by jpapp05** [comment]
It would be nice if System.Drawing started to move away (at least on Windows) from the antiquated GDI+ APIs.   This problem could be solved by using more modern APIs.   For example, in Windows, for loading images the Windows Imaging Component (WIC) supports these formats and more.

https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nn-wincodec-iwicbitmapdecoder

See CLSID_WICHeifDecoder

We used these APIs to solve a similar issue; once decoded it is not to difficult to move the bits into a GDI+ bitmap...

**Comment by rebeccapowell** [comment]
Any news on this? Currently we have a nasty hack to try/catch the images our users upload and reject HEIC / HEIF images. But it is far from ideal.

**Comment by danmoseley** [comment]
@antonfirsov do you have a recommendation for such a transcoder?

**Comment by JeremyKuhne** [comment]
As System.Drawing.Common is a GDI/GDI+ wrapper and only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now, this feature is out of scope. Please see our [recommendations](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) for other libraries to consider.
