### ISSUE TITLE
Investigate and schedule creation of .NET Core 3.0 runtime bootstrap package

### ISSUE THREAD

**Issue by leecow** [dotnet/runtime#3620]
The Installer Projects extension the most widely used deployment technology Visual Studio offers to customers. VS telemetry indicates 50-60k monthly users and nearly 4.5 million downloads.

Scenario example using the Installer Projects Extensions and MSIs

1. Install the Installer Projects Extension
2. Copy both folders from \\ddfiles\team\XAML\User\lukewest\Nc3BootstrapperPackages\preview5-27626-15 into “Program Files (x86)\Microsoft SDKs\ClickOnce Bootstrapper\Packages”
3. Create a “Setup Project” in VS, right-click it in SE and select “Properties”, then click “Prerequisites” to bring up a dialog with a list of potential prereqs
4. You should see two new entries here, “.Net Core 3 Runtime Libraries Preview 5 (x64)” and an “(x86)” version.  Select one or both of these and click OK
5. Build the setup project, which will create a folder with an msi and a setup.exe
 
Now if you run this setup.exe it will detect if the .Net Core 3 runtime is installed and then offer to install it for you if necessary.  Note that though I’m concentrating on installer projects this bootstrapper package also enables the similar ClickOnce scenario, we both look for bootstrapper packages at the same location.

**Comment by dagood** [comment]
I've copied the files to https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2Fdev%2FMSLukeWest%2FNc3BootstrapperPackages for future reference.

**Comment by MSLukeWest** [comment]
Packages for the x86/x64 Core and Desktop 3.1 runtimes have been created and will appear in the upcoming VS 2019.7 update.
