### ISSUE TITLE
upgrade from 2.0 to 3.1,we got the overrided "dotnet",will it compatible with 2.0?

### ISSUE THREAD

**Issue by xyz0822** [dotnet/runtime#36216]
Hi,
By now,we use dotnet runtime 2.0 on the server ,but recently we want upgrade to runtime 3.1,and for the convenience,we just downloaded NET Core 3.1 SDK (v3.1.201),and extract to the same folder on linux `/usr/local/dotnet`,and found in `/usr/local/dotnet`  we got the same **dotnet**,is seems the **dotnet** from NET Core 3.1 SDK override the **dotnet** from NET Core 2.0 SDK ,does it compatible with "dotnet *.dll" that  from old application which develop on version 2.0 sdk?

**Comment by xyz0822** [comment]
> I couldn't figure out the best area label to add to this issue. Please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

it should belongs to **area-SDK**

**Comment by jkotas** [comment]
> does it compatible with "dotnet *.dll" that from old application which develop on version 2.0 sdk?

Yes, we are very careful about making `dotnet` backward compatible. Note that the rest of the runtime (e.g. `libcoreclr.so`) have side-by-side copies for each version, so this concern is just for the `dotnet` (we often call it "muxer").
