### ISSUE TITLE
ClaimsPrincipal.Current lacks Thead.CurrentPrincipal fallback

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/runtime#36211]
Under the .NET Framework `ClaimsPrincipal.Current` defaults to using `Thread.CurrentPrincipal` as its value. This can be overridden with the `ClaimsPrincipalSelector`, with the default behavior coded as a fallback when that value has not been set.

While `ClaimsPrincipalSelector` exists, the fallback to `Thread.CurrentPrincipal` is not present under .NET Core. The class is currently documented as using `Thread.CurrentPrincipal` by default even in .NET Core. See dotnet/dotnet-api-docs#4213. Having just filed that documentation bug, I thought it worth questioning if this difference from the .NET Framework is desirable.

Obviously there is an easy workaround for people who need this functionality. (Just copy the default implementation of .NET Framework from the ReferenceSource repo, and set that as the `ClaimsPrincipalSelector` delegate.)

I'm personally indifferent on implementing the fallback or having it remain as a deliberate difference. In the latter case, let this issue serve as an indication that implementing the fallback was considered and rejected.

**Comment by bartonjs** [comment]
Looks like it's all due to ClaimsPrincipal.Current having been added in .NET Core 1, but Thread.CurrentPrincipal wasn't brought back until .NET Core 2, and this was the first anyone reported anything being wrong.

Seems simple enough to fix.
