### ISSUE TITLE
ParamName in an ArgumentException has a space

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#36212]
That seems a bit strange:

![image](https://user-images.githubusercontent.com/31348972/81566921-da4e4d00-939b-11ea-9b81-99570addd2da.png)

---

https://github.com/dotnet/runtime/blob/8527a991b91cabc9bec6f6abe57a52b5bb5e154d/src/coreclr/src/vm/comutilnative.cpp#L920

**Comment by weitzhandler** [comment]
I'm taking this. Please stop me if you're already on it.

**Comment by weitzhandler** [comment]
Is `WeakReference(null)` something ever needed?
