### ISSUE TITLE
Annotate reflection APIs for linkability

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#36229]
The linker hardcodes some of the reflection APIs as "intrinsic" calls and will warn if it can't recognize the exact usage, but lot of reflection APIs are not recognized by the linker. Usage of such APIs can still be problematic and can cause the linker to break the app. The task is to annotate all such APIs with the necessary attributes:
* DynamicallyAccessedMembersAttribute where this is possible as this provides the best chance of making the code work
* RequiresUnreferencedCodeAttribute in cases where there's no good solution

An example of annotations like these would be:
```C#
class Type // System.Type
{
    // Annotate the "this" parameter with PublicFields since GetFields returns all public fields on the type.
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberType.PublicFields)]
    FieldInfo GetFields();
}
```

```C#
class Assembly // System.Reflection.Assembly
{
    [RequiresUnreferencedCode("Dynamically loading assemblies doesn't work with application trimming.")]
    static Assembly LoadFrom(string);
}
```

Additionally the outcome of this work should not only be the annotations, but also identifying problematic areas (for example `Type.IsAssignableFrom` or `Type.GetCustomAttributes`) and starting a discussion about potential solutions.

We can start this work by using the XML files (https://github.com/mono/linker/pull/1176) to annotate the code from the outside. Eventually these annotations should be added to the actual source code of reflection in dotnet/runtime repo.

Note: While the linker does recognize some of the reflection calls as intrinsics and will handle them even without annotations, we should still put annotation on all such methods. This will not only act as a documentation, but should also help with analyzing the reflection code itself.

**Comment by vitek-karas** [comment]
To fully annotate `System.Type` APIs a proposed API change is needed: https://github.com/dotnet/runtime/issues/36708

**Comment by eerhardt** [comment]
@MichalStrehovsky - you've been working on this correct? Is this work complete? Or is there more work for this issue?

**Comment by MichalStrehovsky** [comment]
As far as I'm aware, core reflection APIs are annotated.

There are some APIs left that are "reflection with extra steps", but they're not reflection per se.
