### ISSUE TITLE
[JsonSerializer] Provide option to specify a custom default value for a type, property, or field

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#36236]
https://github.com/dotnet/runtime/issues/779 discusses options to ignore CLR default values during serialization (API approved).

Rather than using the CLR default, users may want to specify a custom default to be ignored. This issue is a placeholder for an API proposal to make this achievable.

**Comment by layomia** [comment]
From @steveoh in https://github.com/dotnet/runtime/issues/41630

> ### Description
> ```cs
> // startup
> .AddJsonOptions(options => {
>   options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
>   options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull & JsonIgnoreCondition.WhenWritingDefault;
>   options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
> });
> 
> // ...
> 
> [DefaultValue(typeof(decimal), "-1")]
> [DefaultValue(-1.0)]
> [DefaultValue(-1D)]
> public double Prop { 
> 	get => _prop;
>     set => _prop = Math.Round(value, 2);
> }
> ```
> 
> When the prop is set to -1, which is the default value, the property is serialized when `JsonIgnoreCondition.WhenWritingDefault` is set. I would expect that property to not be serialized.
> 
> ### Configuration
> osx catalina x64
> 5.0.100-preview.8.20417.9

**Comment by walterpg** [comment]
#### Raising the flag

FYI, I am considering returning to a [tried-and-true third party](https://www.newtonsoft.com/json) to get [this functionality](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DefaultValueHandling.htm).  Custom `JsonConverter`s are not sustainable workarounds for my scenarios.

**Comment by eiriktsarpalis** [comment]
I believe that most of that functionality can now be achieved using a combination of the `JsonPropertyInfo.ShouldSerialize`/`Get`/`Set` delegates in the contract customization layer. There a limits to what values can be specified in the attribute layer, so I'd be inclined to close this in favor of the API surface exposed in #63686.
