### ISSUE TITLE
Not able to get client device name

### ISSUE THREAD

**Issue by nareshkathi** [dotnet/runtime#36240]
I am not able to get the client device name either from Request/HttpContext. Below is the sample code i am using,

 IPAddress ClientIP = IPAddress.Parse(IHttpContextAccessor.HttpContext.Connection.RemoteIpAddress.ToString());
IPHostEntry GetIPHost = Dns.GetHostEntry(ClientIP);
var clientDeviceName = GetIPHost?.HostName?.ToString()?.Split('.')?.ToList()?.FirstOrDefault();

I was able to get client machine IP but not the machine name.

Please let me know how to get client machine name of any device type.

I am using .NET core 3.1 and ASP.Net core environment.

Thanks

**Comment by wfurt** [comment]
This really depends on your DNS configuration @nareshkathi and reverse lookups may or may not work. e.h 'foo' -> 1.1.1.1 but 1.1.1.1 may not resolve to 'foo'

Are you trying to get https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipglobalproperties.hostname?view=netcore-3.1#System_Net_NetworkInformation_IPGlobalProperties_HostName ???

That also may or may not resolve back and forth - at least not on Linux.

**Comment by nareshkathi** [comment]
I tried with both IHttpContextAccessor and IPGlobalProperties, but still couldn't able to get the  client device name of the request.

**Comment by wfurt** [comment]
If you talking about remote client connecting to HTTP server, there is no general reliable way. You can try DNS lookup[ but that may or may not work and you need to deal with failures. That is not limitation of .NET but rather general networking behavior. You can use nslookup to see what OS can get about given IP.

**Comment by karelz** [comment]
Triage: As mentioned above, DNS reverse lookup is OS/config dependent, not something we can affect.
If we misunderstood, please provide a repro to demonstrate the problem you're hitting. Thanks!
