### ISSUE TITLE
Add FrameworkName property to RuntimeLibrary

### ISSUE THREAD

**Issue by rseanhall** [dotnet/runtime#36259]
Needed to implement https://github.com/dotnet/sdk/issues/3339. Usage is in https://github.com/dotnet/sdk/pull/11545.

### Proposed Api

```C#
// In assembly Microosft.Extensions.DependencyModel
namespace Microsoft.Extensions.DependencyModel
{
    public partial class RuntimeLibrary : Library
    {
        // Existing constructors
        public RuntimeLibrary(
            string type, string name, string version, string hash,
            IReadOnlyList<RuntimeAssetGroup> runtimeAssemblyGroups,
            IReadOnlyList<RuntimeAssetGroup> nativeLibraryGroups,
            IEnumerable<ResourceAssembly> resourceAssemblies, 
            IEnumerable<Dependency> dependencies,
            bool serviceable);
        public RuntimeLibrary(
            string type, string name, string version, string hash,
            IReadOnlyList<RuntimeAssetGroup> runtimeAssemblyGroups,
            IReadOnlyList<RuntimeAssetGroup> nativeLibraryGroups,
            IEnumerable<ResourceAssembly> resourceAssemblies,
            IEnumerable<Dependency> dependencies,
            bool serviceable,
            string path,
            string hashPath);
        public RuntimeLibrary(
            string type, string name, string version, string hash,
            IReadOnlyList<RuntimeAssetGroup> runtimeAssemblyGroups,
            IReadOnlyList<RuntimeAssetGroup> nativeLibraryGroups,
            IEnumerable<ResourceAssembly> resourceAssemblies,
            IEnumerable<Dependency> dependencies,
            bool serviceable,
            string path,
            string hashPath,
            string runtimeStoreManifestName);

        // New apis
        public RuntimeLibrary(
            string type, string name, string version, string hash,
            IReadOnlyList<RuntimeAssetGroup> runtimeAssemblyGroups,
            IReadOnlyList<RuntimeAssetGroup> nativeLibraryGroups,
            IEnumerable<ResourceAssembly> resourceAssemblies,
            IEnumerable<Dependency> dependencies,
            bool serviceable,
            string path,
            string hashPath,
            string runtimeStoreManifestName,
            string frameworkName); // This is the added parameter

        public string FrameworkName { get; }

        // Some of the existing apis on the class
        public string Name { get; }
        public string Path { get; }
        public IReadOnlyList<RuntimeAssetGroup> NativeLibraryGroups { get; }
        public IReadOnlyList<ResourceAssembly> ResourceAssemblies { get; }
        public IReadOnlyList<RuntimeAssetGroup> RuntimeAssemblyGroups { get; }
        // More ...
    }
}
```

`FrameworkName` already exists in the SDK in its `RuntimePack` class, this is simply storing that in DependencyModel's `RuntimeLibrary` class.

With this change we're also adding the property `frameworkName` into the `.deps.json` format into the "library" object, like this:
```JSON
  "libraries": {
    "runtimepack.Microsoft.NETCore.App.Runtime.win-x64/3.1.2": {
      "type": "runtimepack",
      "serviceable": false,
      "sha512": "",
      "frameworkName": "Microsoft.NETCore.App"
    }
  }
```

The main purpose is for the app to be able to determine which assemblies belong to a framework as this has implications on version resolution in scenarios around `AssemblyDependencyResolver`.

cc @vitek-karas

**Comment by vitek-karas** [comment]
Discussed this with @eerhardt and we need input from SDK on this. Basically for .NET 5 it would be enough to look at the type of the library. If it's "runtimepack" then it's a framework. That alone would solve the problem this is trying to solve.

The question is if going forward we can guarantee that all frameworks and only frameworks will be marked as type="runtimepack". I don't know the answer to that.

@dsplaisted - would you know the answer to that?

**Comment by dsplaisted** [comment]
Checking for type runtimepack seems like it would work well.

I don't expect we would mark anything which isn't a "framework" as a runtimepack.  I tried to think of how it might change in the future, and the most I could come up with would be that maybe we would support partially self-contained apps, for example an app that used an installed shared framework for Microsoft.NETCore.App, but shipped the implementation for Microsoft.AspNetCore.App.  But I think that would still work with the check for type=runtimepack.

**Comment by rseanhall** [comment]
Are you suggesting that this could be denied because there's no current scenario that requires this information? It would also be useful for https://github.com/dotnet/runtime/issues/33472.

**Comment by vitek-karas** [comment]
@rseanhall yes - that's basically the concern. The main issue (plugins loaded into a self-contained app) doesn't seem to need the framework name (it only needs to know if an assembly is from a framework or not). #33472 doesn't need this either - the host has access to runtime config which has full information about frameworks (even for self-contained apps), and that API doesn't need to map assemblies to frameworks.

**Comment by rseanhall** [comment]
@vitek-karas So is this `api-ready-for-review`? Or is this declined?

**Comment by vitek-karas** [comment]
I think we should close this - we don't have a use for it - it would be rather hard to make the case for this without a use case...

**Comment by rseanhall** [comment]
I'm not going to close this since I think it's silly to throw this information away. But if you're not going to take it, you should close it.

**Comment by vitek-karas** [comment]
It's not just the API - I don't think we should add the JSON property either and we should not make the necessary SDK changes.
Basically this is about adding more information into `.deps.json`. Currently we don't have a use for it. And since every .NET Core application would get that information in there, every app would pay the (very small but still) price to parse that piece of JSON every time it starts. Without any usage.

I know that the .deps.json is already way too large for what it needs to be, but this is basically just making it worse without a solid reason to do so.
