### ISSUE TITLE
Restore failing intermittently on build

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#36255]
Restore is failing intermittently 

```
F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20251.2\NuGet.targets(128,5): error : Cannot create a file when that file already exists. [F:\workspace\_work\1\s\src\libraries\restore\binplacePackages\binplacePackages.depproj] 
##[error].dotnet\sdk\5.0.100-preview.5.20251.2\NuGet.targets(128,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Cannot create a file when that file already exists. 
```

Looks like a race that is hitting the "Libraries Build Windows_NT allConfigurations x64 Debug" the most often.

Note: if you are looking into this bug make sure to look at all attempts of this leg. About 1/2 of the PRs here retried this failure and it succeeded on retry. Hence looking at the final state of the build will not display this error. 

|Build|Kind|Job Name|
|---|---|---|
|[640103](https://dev.azure.com/dnceng/public/_build/results?buildId=640103)|[PR 36242](https://github.com/dotnet/runtime/pull/36242)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[637444](https://dev.azure.com/dnceng/public/_build/results?buildId=637444)|[PR 36150](https://github.com/dotnet/runtime/pull/36150)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[637444](https://dev.azure.com/dnceng/public/_build/results?buildId=637444)|[PR 36150](https://github.com/dotnet/runtime/pull/36150)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[637444](https://dev.azure.com/dnceng/public/_build/results?buildId=637444)|[PR 36150](https://github.com/dotnet/runtime/pull/36150)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[638863](https://dev.azure.com/dnceng/public/_build/results?buildId=638863)|[PR 36098](https://github.com/dotnet/runtime/pull/36098)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[638863](https://dev.azure.com/dnceng/public/_build/results?buildId=638863)|[PR 36098](https://github.com/dotnet/runtime/pull/36098)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[638849](https://dev.azure.com/dnceng/public/_build/results?buildId=638849)|[PR 36175](https://github.com/dotnet/runtime/pull/36175)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[638786](https://dev.azure.com/dnceng/public/_build/results?buildId=638786)|Rolling|Libraries Build Windows_NT net472 x64 Release|
|[638313](https://dev.azure.com/dnceng/public/_build/results?buildId=638313)|[PR 36098](https://github.com/dotnet/runtime/pull/36098)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[638357](https://dev.azure.com/dnceng/public/_build/results?buildId=638357)|[PR 35366](https://github.com/dotnet/runtime/pull/35366)|Libraries Build Windows_NT allConfigurations x64 Debug|
|[638198](https://dev.azure.com/dnceng/public/_build/results?buildId=638198)|Rolling|Libraries Build Windows_NT allConfigurations x64 Release|

**Comment by safern** [comment]
@ViktorHofer it seems like we have a race condition in allConfigurations. Since you're the "restore"  expert and work on a bunch of NuGet features recently, could you take a look at this?

**Comment by ViktorHofer** [comment]
The binlog shows that the project.assets.json file for one of the depproj's isn't TargetFramwork specific which it should be, hence the race:
![image](https://user-images.githubusercontent.com/7412651/81943415-a40f0880-95fb-11ea-80b2-fff9f85ead2c.png)

cc @ericstj

**Comment by ViktorHofer** [comment]
OK, this regressed with https://github.com/dotnet/runtime/commit/43f948bccbc383a9be52e3be3ad20a1b06c847b7.

https://github.com/dotnet/runtime/blob/f53c15657a99e6c72cd360e9795e03cf7c9421b1/src/libraries/restore/Directory.Build.props#L6 depends on `IntermediateOutputPath` being set in a props file. Even though it isn't recommended that the TargetFramework property is read before the project is load, we currently encode the TargetFramework in the `IntermediateOutputPath` for depproj files.

I will submit a hot-fix by bringing that property back for depproj files. The long-term fix is to get rid of per configuration restores by getting rid of our depproj files.

**Comment by ViktorHofer** [comment]
cc @Anipik

**Comment by ericstj** [comment]
> depproj's isn't TargetFramwork specific which it should be, hence the race
>  The long-term fix is to get rid of per configuration restores by getting rid of our depproj files.

@ViktorHofer / @Anipik I thought we removed that?  Depproj's shouldn't need per-configuration restore.  That was really only needed when we were conditioning PackageReferences by Runtime.  If we only condition on TargetFramework and then they can have single pass restore just like everything else.

**Comment by ericstj** [comment]
I'm also supportive of just deleting them :)

**Comment by ViktorHofer** [comment]
We are still condition on runtime in [runtime.depproj](https://github.com/dotnet/runtime/blob/master/src/libraries/restore/runtime/runtime.depproj#L9).
