### ISSUE TITLE
BigInteger is not IConvertible 

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#36264]
All numeric types is IConvertible.
Why couldn't BigInteger be too?

**Comment by danmosemsft** [comment]
Can you show some example code that would use it?

**Comment by iSazonov** [comment]
@danmosemsft You could look Powershell PR https://github.com/PowerShell/PowerShell/pull/12629
We are trying to get better BigInteger support in PowerShell and now have to use some workarounds.

**Comment by danmosemsft** [comment]
Right, but if you're making a formal API proposal here in this repo, it would be best to include proposed API, useage samples, rationale etc here.

**Comment by tannergooding** [comment]
There are a lot of numerics types and `IConvertible` is really only implemented by a limited subset defined by [System.TypeCode](https://source.dot.net/#System.Private.CoreLib/TypeCode.cs,c5d283ec0427bcdb)
Additionally, the types it supports converting to is even more limited and the majority of cases will actually throw (either outright or due to overflow).

I'm not sure it is worthwhile exposing the interface on `BigInteger` or other numeric types (like `Complex`) due to this.

**Comment by iSazonov** [comment]
I open the issue only for consulting - it is not critical for PowerShell.
If .Net team does not see a need for this today, it can close the issue.
But if .Net team will enhance `IConvertible` support in numeric types I'd expect to see BigInteger in the list too.

**Comment by tannergooding** [comment]
My (possibly incorrect) understanding is that isn't an intended or supported use-case for `IConvertible`.

Maybe @stephentoub or @jkotas would know better?

**Comment by stephentoub** [comment]
> My (possibly incorrect) understanding is that isn't an intended or supported use-case for IConvertible.

What is the use-case we're even discussing here? :-)  @iSazonov, what code are you hoping a developer would actually write to take advantage of BigInteger implementing the interface?  A few C# examples would be helpful.

**Comment by iSazonov** [comment]
@stephentoub We have started to enhance BigInteger support in PowerShell to get a consistency with all numerics. The PR is referenced above. We have to add new code paths because all numerics excluding BigInteger implement `IConvertable`. It is not critical but wonder. So I asked - why not? Now I see that .Net team did not consider this and my request is - if .Net team will consider `IConvertable` enhancement support please include BigInteger in the consideration too.

**Comment by danmosemsft** [comment]
@iSazonov we hear you but we need  concrete motivation - real use cases ideally with sample code. Consistency alone is unlikely to be enough motivation to do this rather than invest resources elsewhere...

**Comment by iSazonov** [comment]
Example from referenced PR
https://github.com/PowerShell/PowerShell/blob/fc6184b367cf488946ff85ce94d1690c55193ab8/src/System.Management.Automation/engine/LanguagePrimitives.cs#L2925-L2937

**Comment by stephentoub** [comment]
Thanks, but I'm not seeing the motivation here.  That's just showing using Convert.ChangeType, which just begs the question of why/when you'd need to use that with BigInteger?  On top of that, there are significant practical limitations here.  Implementing this in the same way as the primitive types would end up requiring those primitives (e.g. Int32) to have a dependency on BigInteger.  I don't think this is worth pursuing.

**Comment by iSazonov** [comment]
Another more generic sample from the same file https://github.com/PowerShell/PowerShell/blob/fc6184b367cf488946ff85ce94d1690c55193ab8/src/System.Management.Automation/engine/LanguagePrimitives.cs#L5694-L5706

As you can see PowerShell has many workarounds for type conversions and as I said it is not critical for PowerShell to have IConvertible with BigInteger. 
If the IConvertible complicates the Runtime, then this means that these workarounds will be in PowerShell.

**Comment by stephentoub** [comment]
I'm going to close this. Thanks for the suggestion. I'm just got seeing significant enough benefits here.
