### ISSUE TITLE
The type initializer for 'System.Net.ServicePointManager' threw an exception

### ISSUE THREAD

**Issue by fanyhawu** [dotnet/runtime#36270]
I randomly got this exception and It seems this exception was thrown by this simple code:
`ServicePointManager.DefaultConnectionLimit = 100;`

the full stack trace is below:

> New exception: 5/9/2020 11:09:53 AM
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
> 
> Stack trace:
> 
> at System.Net.ComNetOS.GetWindowsInstallType()
> 
> at System.Net.ComNetOS..cctor()
> 
> Outer exception:
> 
> System.TypeInitializationException: The type initializer for 'System.Net.ComNetOS' threw an exception.
> 
> Stack trace:
> 
> at System.Net.ServicePointManager..cctor()
> 
> Outer exception:
> 
> System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception.
> 
> Stack trace:
> 
> at System.Net.ServicePointManager.set_InternalConnectionLimit(Int32 value) at System.Net.ServicePointManager.set_DefaultConnectionLimit(Int32 value) at Company.Product.CloudDB.AppServer.AppServerCalls.GetTheportNumberInternal(IConnectMediator mediator, Boolean& tryagain)

note: this issue happens randomly. 

I opened .NET NETWORK trace, here's my findings: 
**when issue happens**:  I can see all http request seems created failed, there's only Entering for WebRequest::Create, no Exiting trace. it seems some exception happens in WebRequest::Create, but not recorded by network trance log. 

> System.Net Verbose: 0 : [2304] Entering WebRequest::Create(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:47.5920394Z
> System.Net Verbose: 0 : [2304] Entering HttpWebRequest#11328498::HttpWebRequest(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx#271711259)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:47.5920394Z
> System.Net Verbose: 0 : [0900] Entering WebRequest::Create(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:47.6180390Z
> System.Net Verbose: 0 : [0900] Entering HttpWebRequest#52077944::HttpWebRequest(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx#271711259)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:47.6180390Z
> System.Net Verbose: 0 : [6320] Entering WebRequest::Create(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx?ID=availablemodules&APPEND=)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:47.6220386Z
> System.Net Verbose: 0 : [6320] Entering HttpWebRequest#62125865::HttpWebRequest(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx?ID=availablemodules&APPEND=#1182706709)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:47.6220386Z
> System.Net Verbose: 0 : [3364] Entering WebRequest::Create(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:48.3852463Z
> System.Net Verbose: 0 : [3364] Entering HttpWebRequest#17555010::HttpWebRequest(http://dev.mycompany.com/mycompanyservices/toadlinks.aspx#271711259)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:48.3852463Z
> System.Net.Sockets Verbose: 0 : [5328] Entering Socket#34609487::Socket(AddressFamily#2)
>     ProcessId=4684
>     DateTime=2020-05-10T08:40:55.6168445Z
> System.Net.Sockets Verbose: 0 : [5328] Exiting Socket#34609487::Socket() 

I have spent a week on this issue, but still no progress, can you help me with that?

**Comment by fanyhawu** [comment]
by the way, when the issue happens, I don't see this line " Current OS installation type is 'Server'." in network trace log, when It works fine, such line will be printed. 
and I found this line is printed by HttpWebRequest(), and from the log, it seems something wrong happen when calling HttpWebRequest().

**Comment by Youssef1313** [comment]
Are you using .NET Framework or .NET Core?
I tried to search this repo for "`GetWindowsInstallType`", no results.
However, it exists in .NET Framework (https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System/net/System/Net/Internal.cs#L723)

**Comment by fanyhawu** [comment]
Hi Youssef, 
    I am using .NET Framework. Shall I post this issue here or other place?

**Comment by davidsh** [comment]
>I am using .NET Framework. Shall I post this issue here or other place?

Please open a .NET Framework issues here:
https://developercommunity.visualstudio.com/spaces/61/index.html
