### ISSUE TITLE
`build -test` won't actually run tests as said in the docs?

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#36284]
https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md says:
> The following builds and runs all tests in release configuration:
`build.cmd/sh -subset libs -test -c Release`

However when I do `build -subset libs -runtimeConfiguration Release -test` it doesn't appear to build tests neither run the tests; From what I see it seems to build the libraries part, and ends.

In addition, when I specify `-testnobuild` it doesn't seem to respect it as it does actually build the libs component.

**Comment by ViktorHofer** [comment]
The subset is wrong in the docs. It should be libs.tests.

**Comment by safern** [comment]
PR: https://github.com/dotnet/runtime/pull/36286

**Comment by EgorBo** [comment]
@ViktorHofer btw, is it possible to build everything from scratch and run tests at once?, e.g.
```bash
build -subset Mono+Libs+Libs.Tests -test
```
or it should be
```bash
build -subset Mono+Libs
build -subset Libs.Tests -test
```
?

**Comment by ViktorHofer** [comment]
> @ViktorHofer btw, is it possible to build everything from scratch and run tests at once?, e.g.

I think `build.cmd mono+libs+libs.tests -test` should work fine as long as mono doesn't have a test subset.

**Comment by safern** [comment]
> I think build.cmd mono+libs+libs.tests -test should work fine as long as mono doesn't have a test subset.

Also, do we need to pass `/p:RuntimeFlavor=mono` for that?

**Comment by ViktorHofer** [comment]
No, that's auto-detected: https://github.com/dotnet/runtime/blob/master/eng/Subsets.props#L52.

**Comment by safern** [comment]
Good to know 😄 thanks!
