### ISSUE TITLE
Application not closing socket stuck in CLOSE_WAIT state

### ISSUE THREAD

**Issue by jogoertzen-stantec** [dotnet/runtime#36293]
Our ASP.NET Core application (RHEL 7; ASP.NET Core 2.2.7 runtime) frequently stops responding immediately after restarting a remote SQL Server database hosted on Windows Server.

![htop](https://user-images.githubusercontent.com/41205049/81730837-62d7f680-944b-11ea-9a28-617702c49ff1.png)

The application has a thread that is repeatedly calling recvmsg on a socket in CLOSE_WAIT state.

![strace](https://user-images.githubusercontent.com/41205049/81730918-7c793e00-944b-11ea-8082-6479d43f6604.png)

The socket was originally ESTABLISHED with the database and transitioned to CLOSE_WAIT as soon as the database host was restarted. The socket remains in CLOSE_WAIT indefinitely until the application is restarted.

![lsof](https://user-images.githubusercontent.com/41205049/81730963-8733d300-944b-11ea-93d2-725a5b48d175.png)
![netstat](https://user-images.githubusercontent.com/41205049/81730998-9286fe80-944b-11ea-8b0d-b8a8accc52d9.png)

Attaching a debugger reveals the following stack trace.

[stack.txt](https://github.com/dotnet/runtime/files/4617717/stack.txt)

I'm not exactly sure, but [this is my best guess](https://github.com/dotnet/corefx/blob/v2.2.7/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L86) as to the line of code that produces the recvmsg calls.

If the TCP state transition diagram below is to be believed, then the socket correctly transitioned to CLOSE_WAIT when the database went down, but the application seems to think it is still ESTABLISHED or something.

![tcp](https://user-images.githubusercontent.com/41205049/81731190-d417a980-944b-11ea-97d9-71c9e8a76705.png)

Given the information above, does this look like a dotnet bug?

Thanks for reading!

**Comment by karelz** [comment]
@jogoertzen-stantec does it use high CPU for calling `recvmsg` in a loop?
Given that 2.2 is not supported anymore, would you be able to upgrade to 3.1 and test it out there if it is still a problem?

**Comment by jogoertzen-stantec** [comment]
> @jogoertzen-stantec does it use high CPU for calling `recvmsg` in a loop?
> Given that 2.2 is not supported anymore, would you be able to upgrade to 3.1 and test it out there if it is still a problem?

@karelz It sure does! 😅 Is this a known issue?

We unfortunately cannot upgrade to 3.1 at this time as [odata is not supported](https://github.com/OData/WebApi/issues/1748#issuecomment-553109029).

**Comment by scalablecory** [comment]
Do you have small code to repro this? I don't think we have enough here to diagnose the problem -- at first glance it appears someone is calling `Socket.Receive` in a loop and not handling an exception, but that can be in many places.

**Comment by wfurt** [comment]
I think it is essentially dup of https://github.com/dotnet/runtime/issues/29327
fixed by 
https://github.com/dotnet/corefx/pull/38499 in 3.0.

**Comment by wfurt** [comment]
BTW some background, we could leave OS descriptor open if it is not disposed explicitly. 
Doing explicit `Dispose()` should avoid the issues. That can still be hidden inside of SqlClient.

**Comment by Wraith2** [comment]
Given the presence of `SslOverTdsStream.ReadInternal()` in the stack trace it looks like it could be a known possible issue in [`SslOverTdsStream`](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SslOverTdsStream.cs#L105-L110) in SqlClient

```csharp
                    while (readBytes < TdsEnums.HEADER_LEN)
                    {
                        readBytes += async ?
                            await _stream.ReadAsync(packetData, readBytes, TdsEnums.HEADER_LEN - readBytes, token).ConfigureAwait(false) :
                            _stream.Read(packetData, readBytes, TdsEnums.HEADER_LEN - readBytes);
                    }
```

Note that the readBytes value is not checked for 0 so you can sit in a non-iterating infinite loop if the connection is somehow closed but not throwing on access. In Microsoft.Data.SqlClient I've got an open PR that changes that behaviour, https://github.com/dotnet/SqlClient/pull/541

**Comment by karelz** [comment]
So, we have a few suspicion. Is there any easy way to confirm which one it is?
Is there anything actionable left on this issue?

**Comment by Wraith2** [comment]
If the runtime fix for later versions makes it impossible to return 0 on a closed socket that'll fix it for most people. In this particular case my upcoming change in Microsoft.Data.SqlClient will fix it on the older runtime. 

So I don't think there's anything that needs to be done here. My suggestion would be that @jogoertzen-stantec probably needs to track the PR I linked and once it gets merged try the Microsoft.Data.SqlClient preview that contains it to see if the issue goes away.

**Comment by jogoertzen-stantec** [comment]
@Wraith2 Unless I am missing something, the potential change to `Microsoft.Data.SqlClient` will not make a difference in this particular situation as the application currently uses `System.Data.SqlClient`. Are you also suggesting the applicationon should switch to `Microsoft.Data.SqlCient`?

**Comment by Wraith2** [comment]
Yes.

**Comment by jogoertzen-stantec** [comment]
Great! I am subscribed to dotnet/SqlClient#541 as @Wraith2 suggested. We are planning to upgrade the application to ASP.NET Core 3.1 anyways in the coming weeks, but in case that plan falls through this is a nice alternative.

Also, thank you all very much for jumping on this issue so **deliciously** fast. 😄 Honestly, I wasn't even sure I was in the right place to begin with, so all this attention is greatly appreciated!

**Comment by jogoertzen-stantec** [comment]
Actually, should I close this issue at this point, or should it remain open until I can confirm the proposed approaches actually solve the issue?

**Comment by karelz** [comment]
Given that it is not actionable now (https://github.com/dotnet/runtime/issues/36293#issuecomment-628084999), we can close it.
If you find out it is not addressed with upcoming changes, we can reopen and then dig deeper to make it actionable.
