### ISSUE TITLE
Functional extensions for ValueTask

### ISSUE THREAD

**Issue by Frank0101** [dotnet/runtime#36325]
Hi all,
I find both Task and ValueTask a bit verbose, at times. Even though I'm not against using multiple `async` rows, I think that a functional approach, when available, is more elegant and concise.

My impression is that C# is moving to that direction, so would like to see if there's interest in adding more of that, similarly to how other languages do.

For instance here is an example of how a potential FlatMap method would look like:

```
public static class ValueTaskExtensions
    {
        public static async ValueTask<T2> FlatMap<T1, T2>(this ValueTask<T1> valueTask, Func<T1, ValueTask<T2>> function)
        {
            var result = await valueTask;
            return await function(result);
        }

        public static async ValueTask FlatMap<T>(this ValueTask<T> valueTask, Func<T, ValueTask> function)
        {
            var result = await valueTask;
            await function(result);
        }
    }
```

And of course there's more to add to simplify the language

**Comment by YairHalberstadt** [comment]
Perhaps a better solution would be a pipeline operator https://github.com/dotnet/csharplang/issues/74 so you could do :

```csharp
    return await ... |> await func |> await func;
```

**Comment by Frank0101** [comment]
@YairHalberstadt

Ok, I think I've been mixing up the discussion about `for-comprehension` with the discussion about the `FlatMap`. Sorry for that, Going to focus on the FlatMap and to better explain: I'm talking about case where we have to chain multiple calls.

In the sync case I can do:
```
var result = func1().func2().func3()
```

In the async case I have to do:
```
var v1 = await func1();
var v2 = await v1.func2();
var result = await v2.func3();
```

async/await in the case above is less functional than having something like:
```
var result = await func1()
   .FlatMap(v => v.func2())
   .FlatMap(v => v.func3());
```

**Comment by Frank0101** [comment]
Your pipeline operator wouldn't be bad, but I think we would still lose the opportunity to have a consistent Map/FlatMap operator that can be used across different things (Collections, Options etc..) instead of defining different syntaxes to achieve the same logical action

**Comment by YairHalberstadt** [comment]
Note that rust solves this by making await a postfix operator:

```csharp
func1().await.func2().await.func3();
```

Unfortunately that ship has sailed with C#, although if a new operator is introduced as per https://github.com/dotnet/csharplang/issues/3403 that would give us a chance to revisit it.

I still think that adding a pipelining operator is a more natural solution than adding methods which lead to more nested delegates, and are much less performant.

**Comment by Frank0101** [comment]
> Note that rust solves this by making await a postfix operator:

This looks similar to what you can have with the `.Result` or with the `await` in Scala, but it would block the thread isn't it?

**Comment by YairHalberstadt** [comment]
It's exactly the same as `(await (await (await func1()).func2()).func3())`

**Comment by Frank0101** [comment]
> It's exactly the same as `(await (await (await func1()).func2()).func3())`

ok, this is definitely not readable :)

In general I think that making functions a first class citizen in terms of accepting it as parameter it's key to even start any functional programming in C#. This is more and more used across the language and don't see much performance issues. Nobody prevent people to opt out the functional extensions (as they can alreay do for Linq and everywhere else delegates are strongly used) if performances as a great concern.

But that being said nothing prevent having multiple ways, no I'm not against your pipe operator :)

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
This looks like a monadic bind for ValueTask. I appreciate that everyone has their own perspective for what makes for easily-read and maintained code, but from my perspective, this would be a net negative.  It adds another way to achieve the same thing that's already possible with just as little code (less even) and it does so in a more expensive way, one that not only requires additional delegate invocations but that will also lead to more heap allocation.

If you believe it's important, I'd encourage you to create a library with such extensions and put it up on nuget for others to use when they desire this form of consumption.

**Comment by tarekgh** [comment]
@Frank0101 per the discussion here, I am closing this issue as it looks like it is not preferred to add these methods for the reasons mentioned by @stephentoub and @YairHalberstadt. It would be nice to start with the suggestion of creating a NuGet package with such methods. Thanks for your suggestions and thoughts and feel free to respond back with any questions or comments.

**Comment by Frank0101** [comment]
Thank you all for your time. My view is that the same that was said here could also be said to Linq or others widely used and much appreciated language features, that are maybe not as performing as other ways to achieve the same, but are much more elegant and readable. And for enterprise applications there's more value in that than in counting the microseconds, at least in 99% of cases. If performances are the only thing that matters we should all go back programming in C, or in Assembly. Besides, something being less functional that something else is a fact, not an opinion, and being forced to write multiple lines (or being forced to write some unreadable horror to avoid it) fits the case of a non-functional (or non functional-friendly) approach.

I know that C# is a language designed almost 20 years ago, but I see the effort in covering gaps with more modern languages and patters, so I'm a bit surprised that functional programming is still seen a something that "you should do yourself". I've seen good improvements on this side, like the functional switch recently introduced, so I'm a bit surprised.

Thanks anyway
