### ISSUE TITLE
Safer and performant EventSource calling patterns

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#36326]
Implementing EventSource methods generally involves calling one of many Write or WriteEvent overloads. For 4 and fewer parameters there are specific typesafe overloads, but after that you either need to call an overload that uses params keyword or call WriteEventCore. The params keyword implies allocations and WriteEventCore implies unsafe pointer usage. We could make an alternate version of WriteEventCore that is spanified for better safety. Some example code I stole from @davidfowl 
````C#
protected unsafe void WriteMyEvent(int eventId, int arg1, int arg2)
        {
            Span<EventData> descrs = stackalloc EventData[2];
            descrs[0].DataPointer = (IntPtr)(&arg1);
            descrs[0].Size = 4;
            descrs[0].Reserved = 0;
            descrs[1].DataPointer = (IntPtr)(&arg2);
            descrs[1].Size = 4;
            descrs[1].Reserved = 0;
            WriteEventCore(eventId, descrs);
        }


protected struct EventData
        {
            public IntPtr DataPointer { get; set; }
            public int Size { get; set; }
            internal int Reserved { get; set; }
            public unsafe void SetValue<T>(in T item) where T : unmanaged
            {
                DataPointer = (IntPtr)Unsafe.AsPointer(ref Unsafe.AsRef(item));
                Size = Unsafe.SizeOf<T>();
                Reserved = 0;
            }
            public unsafe void Set(ReadOnlySpan<char> value)
            {
                DataPointer = (IntPtr)Unsafe.AsPointer(ref Unsafe.AsRef(value.GetPinnableReference()));
                Size = value.Length;
                Reserved = 0;
            }
        }
````

**Comment by stephentoub** [comment]
> (IntPtr)Unsafe.AsPointer(ref Unsafe.AsRef(item))
> (IntPtr)Unsafe.AsPointer(ref Unsafe.AsRef(value.GetPinnableReference()))

That looks really dangerous. There's no indication to the caller that they need to pin in order to use this, and if they don't bad things could ensue.

**Comment by davidfowl** [comment]
I wouldn’t take those as the gospel I was experimenting with codez to see if I could make it less cumbersome. I know the Span\<char\> version needs to pin for sure but not sure if the T overload needs to (though I guess it would be if it was referring to a public field of a reference type?)

Then there’s the realization that this is really conceptually a Span\<Span\<?>\> but there’s no way to represent that. You really want EventData to also be a ref struct. I was also playing around with __arglist and TypedReference but didn’t get very far as yet

**Comment by stephentoub** [comment]
> I know the Span<char> version needs to pin for sure

Yes.  More specifically it needs to be pinned around the grabbing of the pointer and all use of that pointer.

> but not sure if the T overload needs to (though I guess it would be if it was referring to a public field of a reference type?)

It does, in case it's referring to something on the heap, e.g. a field (public or not) of a reference type, either directly or indirectly.  That includes array elements.  For example:
```C#
protected unsafe void WriteMyEvent(int[] array, int index)
{
    Span<EventData> descrs = stackalloc EventData[1];
    descrs[0].SetValue(array[index]); // BAD!!!
    WriteEventCore(eventId, descrs);
}
```

**Comment by davidfowl** [comment]
Sure like I said, don’t treat it like the answer. I was hacking and that was like 5 mins of work. I just want to make it simpler since we’re gong to be adding a bunch of these calls all over 😬
