### ISSUE TITLE
[API Proposal] Class for retrieving JIT metrics

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#36324]
This is for https://github.com/dotnet/runtime/issues/1098.

We had customer asks to create runtime EventCounters and corresponding managed APIs that users can track JIT-related metrics with - specifically total # of IL bytes jitted and # of methods jitted. 

```csharp
namespace System.Runtime.CompilerServices
{
    public struct JitCompiledMethodsMetrics
    {
        public int GetJitCompiledILBytes;
        public int GetJitCompiledMethodCount;
        public double GetTimeSpentOnJitCompilation;
    }

   public static JitCompiledMethodsMetrics GetJitCompiledMethodsMetrics();

   public static JitCompiledMethodsMetrics GetJitCompiledMethodMetricsForCurrentThread();

}

```

**Comment by john-h-k** [comment]
Could data about inlining success/failure also possibly be included in this API? That seems like it would be super useful

**Comment by john-h-k** [comment]
Could data about inlining success/failure also possibly be included in this API? That seems like it would be super useful

**Comment by mjsabby** [comment]
Can this proposal be modified to refer to just methods as opposed to JIT metrics?

It would be really useful to expose the following:

* Number or precompiled methods restored
* Machine code size total for precompiled methods
* Current Dynamic method count
* Total Dynamic Method count
* Current/Total IL bytes for dynamic methods
* Machine code size for jitted methods

**Comment by BruceForstall** [comment]
nit: Instead of "jitted", it seems like "JIT compiled" would be a better phrase. So, e.g., `GetJitCompiledMethodCount`

**Comment by sywhang** [comment]
Changed the proposal a little bit to make it align with what we did for GC metrics. 

@BruceForstall I modified the proposal to reflect your suggestions. Thanks!

@john-h-k @mjsabby Thanks for the suggestions - I think @BruceForstall can comment on whether those APIs would be useful to expose? From a diagnostics standpoint, I believe having managed APIs be exposed for computing these metrics can be very valuable, but I would love to hear Bruce's opinion on this as the domain area expert.

**Comment by BruceForstall** [comment]
@john-h-k I believe everything related to inlining is already available in ETW events. I think the goal and design point of these counters is different from ETW events, but @sywhang can better comment on that. E.g., I'm not sure how useful it would be to have a managed code API to get the ETW info that's already exposed. Unless perhaps there is a general managed API for consuming VM produced ETW event info.

@mjsabby I'm sure you have a better idea of why you, as a consumer, would like those data compared to me. I would expect that adding the machine code size is similar to the `GetJitCompiledILBytes` proposed API -- the VM already knows how much generated native code the JIT creates for each method. You might want to further understand or break out how much GC info, EH/unwind info, and debug info the JIT generates for a function, the hot/cold native code sizes, and more. So the amount of data to expose might be too detailed, and perhaps subject to change over time. E.g., what about info on Tier-0 versus Tier-1 compilations? In the future, OSR compilations or interpreted Tier-0.

**Comment by AndyAyersMS** [comment]
All or almost all of the above already appears as part of the method load / unload events. We should create a sample that shows how to process all this.

One crude attempt can be found [here](https://github.com/AndyAyersMS/InstructionsRetiredExplorer/blob/master/src/instretired.cs). It also tries to attribute samples back to jitted code types.

**Comment by mjsabby** [comment]
This is not about eventing, it is about statistics that the runtime already has and exposing it through managed APIs makes it easy to consume without using event data to recreate the statistic. A large part of the code in my profiler is just rebuilding these statistics and so I figured it'd be useful if the work involved in exposing it as a managed API is easy.

**Comment by sywhang** [comment]
@BruceForstall @AndyAyersMS 

My take on the effort to add managed APIs for retrieving metrics across various spaces in the runtime (i.e. GC, JIT, loader, etc.) is to provide a "richer" in-proc diagnostics info for the users without them having to start a tracing session. It is possible for them to get these events by subscribing to the ETW events using EventListener, but EventListener spawns up a whole new thread for flushing and is quite expensive to set up.

Moreover, being able to query these metrics using public APIs allow users to create EventCounters to track them for less-intrusive performance monitoring, since tracing via ETW/EventPipe isn't cheap enough for most users to deploy on performance-sensitive production workloads. 

I think the [GCMemoryInfo API](https://github.com/dotnet/runtime/issues/34648) that was added recently is a work from a similar motivation in the GC space to one we're discussing here for the JIT space.

**Comment by jkotas** [comment]
> Number or precompiled methods restored
> Machine code size total for precompiled methods

We should not be exposing these. If we expose them, it would prevent us from doing AOT optimizations. Also, keeping track of machine code size total for precompiled method is expensive.

**Comment by sywhang** [comment]
@BruceForstall do you have any other suggestions or modifications you'd like to make on this API? Otherwise I'd like to start moving this forward and get them submitted for API design review.  Thanks!

**Comment by josalem** [comment]
duping to #54444
