### ISSUE TITLE
Remove PreserveDependency from SR class

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#36330]
The `PreserveDependencyAttribute` should be no longer needed as the illinker can now recognize RunClassConstructor method call.

**Comment by Youssef1313** [comment]
Is it just about removing the following line?

https://github.com/dotnet/runtime/blob/fe3bf71f40436eebd36db9c1a7c782f3822ecf89/src/libraries/System.Private.CoreLib/src/System/SR.cs#L27

**Comment by marek-safar** [comment]
Yes
