### ISSUE TITLE
ThreadPool unexpected behavior in combination with foreground threads

### ISSUE THREAD

**Issue by kkokosa** [dotnet/runtime#36334]
I've noticed some `ThreadPool` behavior and I/m not sure whether it is a feature or a bug. I'm calling `ThreadPool.QueueUserWorkItem(DoWork)` 20 times with `ThreadPool.SetMaxThreads(Environment.ProcessorCount, 1000)` so in my case max worker threads are 8. If `DoWork` runs on a background thread (default), I observe correct behavior: 8 items are running for some time and 12 are queued. If the main thread ends, the app immediately closes, as all those threads are background. Obviously, those queued items are also discarded.

But if I change DoWork to something like:
```
private static void DoWork(object? state)
{
   Thread.CurrentThread.IsBackground = false;
```
then the behavior is strange: when the main thread ends, 8 active items are processed to the end and this is expected. But I observe that **also remaining 12 items are eventually dequeued, started and executed before an app closes**. It looks like `ThreadPool` is somehow aware that the remaining queued items will be executed as foreground threads but I do not understand how it may happen. 

Documentation (and source code) says that worker threads are reset when the works is done (including background flag and priority). But this behavior suggests that somehow the thread 'steals' work item from the queue without being reset. Is that correct? I cannot find any guarantees in documentation about that but at least it behaves counter-intuitive. 

Minimal repro:

```
class SimplifiedProgram
{
    public static void Main(string[] args)
    {
        // To make queueing much easier
        ThreadPool.SetMinThreads(8, 8);
        ThreadPool.SetMaxThreads(Environment.ProcessorCount, 1000);

        // Assuming 8 cores, it will immediately start 8 items and 12 will be queued
        for (int i = 0; i < 20; ++i)
            ThreadPool.QueueUserWorkItem(DoWork, i);

        Thread.Sleep(1_000);
        Console.WriteLine(ThreadPool.PendingWorkItemCount);

        // If you terminate earlier, while the first 8 items are executed, an app will wait for them, that's obvious.
        // But why it waits for the 12 being dequeued & executed?
        Console.ReadKey(); 
    }

    private static void DoWork(object? state)
    {
        Thread.CurrentThread.IsBackground = false;
        int id = (int)state!;
        for (int i = 0; i < 5; ++i)
        {
            Console.Write($"({id}:{i})");
            Thread.Sleep(1000);
        }
        Thread.CurrentThread.IsBackground = true; // not necessary, just to check
    }
}
```

Note: I know playing with foregrounds threads in a thread pool may be tricky but this is an example to understand thread pool AND to validate whether it may be used in "I want to have all work items processed in thread pool"-scenario.

**Comment by svick** [comment]
Is it possible that what happens is the following?

1. When the main thread ends, nothing changes: `ThreadPool` continues as before and the app doesn't exit, since there are still foreground threads running.
2. Whenever a work item completes, its thread is reset to background, so the number of foreground threads decreases by one. But other threads are still executing their work items, so it doesn't decrease to zero, which means the app continues running.
3. There is now a free `ThreadPool` thread and work items in the queue, so another work items starts executing, increasing the number of foreground threads.

So, since the work items complete one by one (and not all at once), they keep being replaced by new work items, which means there is never a moment when the number of foreground threads is zero. That's why the app continues running until all work items are completed.

**Comment by kevingosse** [comment]
I think you're right. If I add a Barrier to synchronize the threads then the app exits as expected:

```
private static void DoWork(object state)
{
    _barrier.SignalAndWait();

    Thread.CurrentThread.IsBackground = false;
    int id = (int)state;
    for (int i = 0; i < 5; ++i)
    {
        Console.WriteLine($"({id}:{i})");
        Thread.Sleep(1000);
    }

    _barrier.SignalAndWait();
    Thread.CurrentThread.IsBackground = true; // not necessary, just to check
}

private static Barrier _barrier = new Barrier(8);
```

I see 2-3 threads printing (id:0) right before the process exits, but I think it's a race condition between the moment when we set `Thread.CurrentThread.IsBackground = false;` and the moment the runtime decides to teardown the process.

**Comment by kkokosa** [comment]
Right, good point! I was fooled by the fact that they end at (almost) the same time but in fact it is enough that they overlap a little and such behavior can be observer. I believe I can close it.
