### ISSUE TITLE
master branch and profdata desynchronization

### ISSUE THREAD

**Issue by serge-sans-paille** [dotnet/runtime#36344]
While investigating [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1827282), where a PGO build of coreclr with clang leads to an assert, I tracked down the bug to profile data referencing non-existing statements.

That's just an assumption though, so I'd like to know if the profile data downloaded online have any guarantee of synchronicity with a given branch? The HEAD I was using is 19a0db47c8796d4e689d4fe8a698d74066cb7d05 and the profdata end up in `~/.nuget/packages/optimization.linux-x64.pgo.coreclr/99.99.99-master-20200228.3`

**Comment by serge-sans-paille** [comment]
cc @tmds

**Comment by jkotas** [comment]
The profile data do not have guaranteed synchronicity.

**Comment by serge-sans-paille** [comment]
Thanks, then that's probably up to clang to cope with slightly different information; Which compiler version is used to generate the profdata?

**Comment by jkotas** [comment]
It should be the same version that we are using for regular build (clang 9).

cc @brianrob

**Comment by serge-sans-paille** [comment]
This turned to be a relatively serious bug in clang, fix proposed in https://reviews.llvm.org/D79961. basically clang should correctly handle out-of-sync data, and in that case it was computing the same hash for two different body, due to an error in the way it feeds the hashing algorithm.

**Comment by brianrob** [comment]
@billwert, FYI
