### ISSUE TITLE
Publishing single file worker service does not bundle appsettings.json

### ISSUE THREAD

**Issue by LeonidasFettikus** [dotnet/runtime#36356]
.Net Core 3.1
VS 2019 Community 16.4.4

I am trying to publish a worker service.

Added a setting `"Test": "Hello World"` to appsettings.json and accessing it in `ExecuteAsync `method of worker class.

Using VS to publish as a single file with the following profile:

Target Location: C:\Users\<user>\Desktop\Test
Configuration: Release
Deployment Mode: Self-contained
Target Framework: netcoreapp3.1
Target Runtime: win-x64
Produce single file: checked

Expected behavior

Configuration setting available in `ExecuteAsync` method with value `"Hello World"`.

Actual behavior

Configuration setting in `ExecuteAsync` method is `null`. I also see that there is no `appsettings.json` inside the worker's publish folder inside `%TEMP%`.

Repo can be found [here](https://github.com/LeonidasFettikus/WorkerServiceSingleFilePub).

I haven't changed anything in the standard worker template that VS gives me except adding/accessing the setting and creating a publishing profile. What am I doing wrong?

**Comment by swaroop-sridhar** [comment]
@LeonidasFettikus  I tried out the example in your repo.
In this case I see that the `appsettings.json` (and `appsettings.development.json`) files are included in the bundle, and extracted out to `%temp%\.net\WorkerService2\<hash>\` directory.

This is the default behavior of the single-file bundler -- it bundles all files to be published, unless files are explicitly excluded. Therefore, in this case you should exclude the `appsettings.json` config files from the bundle using the  `<ExcludeFromSingleFile>true</ExcludeFromSingleFile>` meta-data. This will leave the files unbundled, beside the single-file app `WorkerService2.exe`.

`Microsoft.NET.Sdk.web` already has excludes for `appsettings.json` looks like `Microsoft.NET.Sdk.Worker` is missing these excludes.

**Comment by swaroop-sridhar** [comment]
I've filed https://github.com/dotnet/websdk/issues/1462 about adding excludes for these `json` files in the Worker SDK.

**Comment by LeonidasFettikus** [comment]
Hi Swaroop,

I tried what you suggested but I still get the same behavior. I can update the json files in 2 scenarios:

1. Debugging inside VS
2. Launching the worker service from it's exe directly

However, it doesn't work when I create a service using `sc` utility. Somehow, my service still has the json files inside the exe somewhere because I need to publish my service again so it can pick up any changes I made to my json files. 

Very weird behavior.

**Comment by LeonidasFettikus** [comment]
Updated the repo to reflect my current code.

**Comment by LeonidasFettikus** [comment]
Ok I have found a workaround for this. It included a little more code than I would write for something like this, but it gets the job done. I do not know whether the single file publish or the worker service is the source of the problem, but writing a custom configuration source and provider that always reads the json file from `Environment.CurrentDirectory` works. It seems that the appsettings files are somehow still included in the single file published or maybe they are cached somewhere by using the worker template, I have no idea. Anyway, I put all my configuration in a new file `settings.json` and `settings.Development.json`, then I decompiled and copied `JsonConfigurationFileParser.cs` from the `Microsoft.Extensions.Configuration.Json` package. 

The contents of my configuration source and provider are as follows:

```
public class JsonFileConfigurationProvider : ConfigurationProvider
{         
    public override void Load()
    {
        var path = Environment.CurrentDirectory;

        if (Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT") == Environments.Development)
            path = Path.Combine(path, "settings.Development.json");
        else
            path = Path.Combine(path, "settings.json");

        using (var stream = File.Open(path, FileMode.Open)) 
        {
            Data = JsonConfigurationFileParser.Parse(stream);
        }
    }
}

public class JsonFileConfigurationSource : IConfigurationSource
{
    public IConfigurationProvider Build(IConfigurationBuilder builder)
    {
        return new JsonFileConfigurationProvider();
    }
}
```

I also needed to set Environment.CurrentDirectory to the .exe's path before loading my custom configuration:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .SetCurrentDirectory(args)
        .UseWindowsService()
        .ConfigureAppConfiguration()
        .ConfigureLogging()
        .ConfigureServices();

public static IHostBuilder SetCurrentDirectory(this IHostBuilder builder, string[] args)
{
    var isService = !(Debugger.IsAttached || args.Contains("--console"));
    if (isService)
    {
        var processModule = Process.GetCurrentProcess().MainModule;
        if (processModule != null)
        {
            var pathToExe = processModule.FileName;
            var pathToContentRoot = Path.GetDirectoryName(pathToExe);
            Directory.SetCurrentDirectory(pathToContentRoot);
        }
    }

    return builder;
}

public static IHostBuilder ConfigureAppConfiguration(this IHostBuilder builder)
{            
    builder.ConfigureAppConfiguration(config =>
    {
        config.Add(new JsonFileConfigurationSource());
    });

    return builder;
}
```
And that's pretty much it. This way, the configuration is always read from the two configuration files which are in the .exe's directory. I have updated my repo in case anyone wants to have a look at it.
