### ISSUE TITLE
System.Uri and System.UriBuilder seems to fail with accented characters

### ISSUE THREAD

**Issue by MathieuGirard** [dotnet/runtime#36365]
new UriBuilder {Host="", Path="/é", Scheme="file"}.Uri

In .Net frame work:
You obtain : [file:///é]

In .Net core:
You obtain : [file://%2fé/é]

Escaping the text does not work either: new Uri("file://" + Uri.EscapeUriString("/é")) also fails in .NetCore but not in framework...

**Comment by davidsh** [comment]
@MihaZupan

**Comment by MihaZupan** [comment]
Thanks for the report. This is a known bug that will be fixed for .NET 5.

**Comment by MihaZupan** [comment]
Duplicate of #1061
