### ISSUE TITLE
Add back metadata specs files

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#36361]
https://github.com/dotnet/runtime/pull/35095 removed files from src/System.Reflection.Metadata/specs. This change broke links to the specs used in other repos.
It'd be better to add the files back with a link to the new location.

**Comment by ericstj** [comment]
You shouldn't have links which rely on the position of a file in source control.  We don't maintain that as a public contract.  Can you update the external references, ideally to use fwlinks/aka.ms so that they're resilient to any changes in the future?

cc @jkotas @jnm2
