### ISSUE TITLE
Add async application initialization before RunAsync

### ISSUE THREAD

**Issue by daniel-white** [dotnet/runtime#36377]
I am trying to run various steps before `RunAsync`. EF core migrations, setting up scheduled tasks, validating configuration, etc.

### Describe the solution you'd like
 It would be nice if there was an `InitializeAsync` that happened inside of there and a common `IAsyncApplicationInitalizationStep` interface or the like to be run when `RunAsync` is called. I've used [this package](https://github.com/thomaslevesque/AspNetCore.AsyncInitialization), but it would be great if there was something built into the libraries such as `Microsoft.Extensions.Hosting` or `Microsoft.Extensions.Hosting.Abstractions`

**Comment by maryamariyan** [comment]
Closing as per recommendations provided in comments https://github.com/dotnet/runtime/issues/36377#issuecomment-535987535 and https://github.com/dotnet/runtime/issues/36377#issuecomment-536013785
