### ISSUE TITLE
More flexible Host Environment name

### ISSUE THREAD

**Issue by iron9light** [dotnet/runtime#36376]
### Is your feature request related to a problem? Please describe.
Our service has more environments than just Development, Staging and Production. For example, we have 2 Production environments for serving different region.
Let's call them "Production1" and "Production2"

### Describe the solution you'd like
There are some extension methods like "IsDevelopment", "IsStaging" and "IsProduction" (https://github.com/dotnet/extensions/blob/master/src/Hosting/Abstractions/src/HostEnvironmentEnvExtensions.cs)
They will check if the environment is Development, Staging and Production (ignoring case).
I just wondering if it's possible that we just check the prefix of environment?
Then "Production1" and "Production2" will be treated as Production.

### Describe alternatives you've considered
I can add my own extension methods like "IsMyProduction" which do whatever I want.
But it seems IsDevelopment/IsStaging/IsProduction methods has been used in different places in asp.net.

**Comment by eerhardt** [comment]
Just to summarize what work needs to be done for this issue:

This issue is tracking adding XML documentation to the `IsDevelopment`, `IsStaging` and `IsProduction` methods that they are intended to be used by applications, and aren't intended for library authors.

**Comment by maryamariyan** [comment]
Closing as this issue is covered already by PR https://github.com/dotnet/dotnet-api-docs/pull/4204.
