### ISSUE TITLE
ASP.NET Core Dependency Injection container uses excessive amount of memory and CPU when large dependency graph is created

### ISSUE THREAD

**Issue by sergey-kolodiy** [dotnet/runtime#36374]
### Description
ASP.NET Core Dependency Injection container uses excessive amount of memory and CPU when large dependency graph is created.

### How To Reproduce
I created a [repository](https://github.com/sergey-kolodiy/AspNetCore.DI) with a small project that reproduces the issue. It targets .NET Framework 4.7.2, but the issue is also reproducible for .NET Core 2.2.

1. Build the solution and run `AspNetCore.DI.Default` project.
2. Using Fiddler or some other tool of your choice, send multiple simultaneous HTTP requests to `http://localhost:5000/api/values` API endpoint. The issue is not always reproduced if you send a single HTTP request and then just wait for the response.
3. Observe resources consumption. You should see significant increase in both CPU and memory consumption:
![image](https://user-images.githubusercontent.com/741576/64855546-cabe0f00-d628-11e9-8523-01e74f913e48.png)
4. For comparison, run `AspNetCore.DI.Autofac` project that uses Autofac DI container instead of the default one and send multiple HTTP API requests again. You won't see those CPU and memory peaks this time.

### Expected behavior
Obviously the default DI container shouldn't use that much CPU and memory resources.

### So, what's going on?
Web API from the example above uses MVC middleware only, but, in addition to MVC services, it also registers a bunch of services with `Scoped` lifetime that are organized in a large graph (without any circular dependencies), and it seems like the default ASP.NET Core DI container is having some issues handling it.

In the request processing thread, the dependency graph is created and injected into the `ValuesController` just fine, and the API returns HTTP 200. But, it looks like for every dependency graph encountered, default DI container (or ASP.NET Core runtime) also spawns a separate background thread that performs some sort of initial processing and/or caching of that dependency graph. So, in theory this operation shouldn't affect request processing threads (at least when the dependency graph is relatively small).

However, it seems like this graph processing algorithm complexity grows exponentially, so the bigger dependency graph is, the more time and memory is consumed by this background operation. On my machine I had peaks up to 100% CPU (completely freezed) and more that 11GB memory consumption, which is not acceptable for production.

After this background process is done, resource consumption slowly decreases back to normal, and it doesn't start again when I invoke API methods on that controller, but for other controllers with different dependency graphs it starts again.

This issue is not reproducible when using Autofac DI container.

**Comment by maryamariyan** [comment]
> @davidfowl you mentioned the original issue was fixed, however there is a separate PR by @brandondahler that is now closed. What does this issue track? Is there concensus on what needs to be done or should some new issue be created.

Also found this possible action item:

> 100% agree @pakrym on removing ILEmitCallSiteAnalyzer. I think defaulting to 1024 or 2048 would be sufficient to cover normal cases without grossly over-allocating. If I can get alignment on this direction, I'll update my PR accordingly.

@brandondahler were you thinking of reopening your PR this time on runtime repo? https://github.com/dotnet/extensions/pull/2375

**Comment by benjiro** [comment]
> From what I can tell, ILEmitCallSiteAnalyzer's only purpose is to make a good estimate for ILEmitResolverBuilder's `dynamicMethod.GetILGenerator(info.Size);` call; however, it looks like we updated the way that we're generating the IL in ILEmitResolverBuilder at [dotnet/extensions@1424884](https://github.com/dotnet/extensions/commit/1424884389d95c89687229431f79d280bac61495); however, we didn't subsequently update the logic in ILEmitCallSiteAnalyzer.
> 
> In particular, it appears that we are generating significantly smaller amounts of IL by calling the ResolveService dynamic methods per-service (technically per-service-slot) instead of presumably nesting these resolution. Long story short, I believe that something like [dotnet/extensions#2375](https://github.com/dotnet/extensions/pull/2375) might be the correct fix for it, but clarity and/or validation from @pakrym or other aspnet members would be needed to proceed further.

We're noticing the same issue after migrating our FF app over to .net core 3.1 and it is causing us nightmares trying to run our api inside of a container on kubenetes. I've made an example app that is able to reproduce the problem. https://github.com/benjiro/ExcessiveMemoryUsageWhenLargeDI

Would be greatly appricated if this could be resolved with a similar approach that @brandondahler outlined above.

CC @davidfowl

**Comment by davidfowl** [comment]
We should fix this and consider it for servicing in 3.x 

cc @Pilchie (yes I will make the change in 3.1 as well 😄)
