### ISSUE TITLE
Add tests for Setup artifacts

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3637]
In many cases, the tooling that generates Setup artifacts (framework pack nupkgs, installers, etc.) can enforce requirements to catch issues as early as the info is available. However, the infra can be easy to break (e.g. the tools may not even run). We need checks that take a more holistic view of the artifacts, especially as we refactor and share more tooling.

**Comment by NikolaMilosavljevic** [comment]
Closing - not a high impact.
