### ISSUE TITLE
`bool` return from `PInvoke` misinterpreted on Alipine

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#36372]
On linux-musl-release-x64 builds, the return value from a native function returning `false` is sometimes incorrectly interpreted as `true` because of the mismatch between the number of bytes expected for `bool` on native and managed sides.

Repro:
The host defines a native function [bundle_probe](https://github.com/dotnet/runtime/blob/master/src/installer/corehost/cli/hostpolicy/hostpolicy_context.cpp#L38) with type
```c++
bool STDMETHODCALLTYPE bundle_probe(const char16_t* path, int64_t* offset, int64_t* size)
```

If this function is called from [managed code](https://github.com/dotnet/runtime/blob/master/src/installer/test/Assets/TestProjects/BundleProbeTester/Program.cs#L13) using the following delegate:

```c#
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]	        
 public delegate bool BundleProbeDelegate([MarshalAs(UnmanagedType.LPWStr)] string path, IntPtr size, IntPtr offset);
```

The invocations where `bundle_probe` return `false`, are interpreted as `true`. Gor example:
```c#
Probe(bundleProbeDelegate, "", isExpected: false);
```

Once this issue is fixed, [this test asset](https://github.com/dotnet/runtime/blob/master/src/installer/test/Assets/TestProjects/BundleProbeTester/Program.c) should be updated to use the `bool` return type in the PInvoke delegate.

**Comment by stephentoub** [comment]
> bool STDMETHODCALLTYPE bundle_probe(const char16_t* path, int64_t* offset, int64_t* size)

Isn't the issue here that this signature uses `bool` rather than, say, `int32_t`?  By default, a `bool` in C# is marshaled as a 4-byte value.

**Comment by jkotas** [comment]
This behavior is by design. The test has mismatched signatures between managed and unmanaged sides that is causing the bug.

`bool` in C# does not match `bool` in C++. The default marshaling for C# `bool` is 4-byte `BOOL`. 

It is best to avoid `bool` in the interop signatures, on both managed and unmanaged sides.

**Comment by swaroop-sridhar** [comment]
Thanks for the clarification @jkotas and @stephentoub.

The `bundle_probe` function is an internal API intended to be used from native code. It was used via PInvoke only for unit-testing, and I have fixed the test code now (https://github.com/dotnet/runtime/pull/36327).
