### ISSUE TITLE
BackgroundService appears to create tasks that will never complete

### ISSUE THREAD

**Issue by Zenexer** [dotnet/runtime#36380]
This line appears to create a task that will most likely never complete:
 https://github.com/aspnet/Extensions/blob/aa7fa91cfc8f6ff078b020a428bcad71ae7a32ab/src/Hosting/Abstractions/src/BackgroundService.cs#L65

Based on my own understanding of BackgroundService and the description of its use of cancellation in dotnet/extensions#1245, I don't expect the CancellationToken to StartAsync or StopAsync to be marked as cancelled under normal operation.  (This is why BackgroundService exists: it provides a more useful CancellationToken to ExecuteAsync than the one provided to StartAsync, which is helpful for tasks that run indefinitely.)  That means the task created with this expression is likely to never complete:

``` csharp
Task.Delay(Timeout.Infinite, cancellationToken)
```

To resolve this, a new CancellationTokenSource could be created for the current scope:

``` csharp
using var stopCts = new CancellationTokenSource();
using var _ = cancellationToken.Register(stopCts.Cancel);

await Task.WhenAny(_executingTask, Task.Delay(Timeout.Infinite, stopCts.Token));
```

I can submit a PR if this fix makes sense.

**Comment by moonrockfamily** [comment]
> > It might be possible to mitigate this with a more descriptive name for the methods.
> 
> [I use `WaitAsync(CancellationToken)`](https://github.com/StephenCleary/AsyncEx/blob/5ede2ebad24bb3696fd730de2d7e11cda92bf8dc/src/Nito.AsyncEx.Tasks/TaskExtensions.cs#L20), in an attempt to make it clear that it is the _wait_ that is cancelled and not the _task_.

Your API designs are very 'clear'. 👍   Looking forward to using https://github.com/StephenCleary/AsyncEx to solve my HostedService BackgroundService recoverability.  Currently, critical exceptions are vaporized, leaving the Host running, but useless!  I don't want to build sophisticated recovery scenarios in my 'worker', it already has a reasonable implementation of 'starting up', why build another; let the host reinstantiate it!  Simple, leverages DI without work-around re-init methods etc.

**Comment by StephenCleary** [comment]
@moonrockfamily I [blogged about that](https://blog.stephencleary.com/2020/05/backgroundservice-gotcha-silent-failure.html) recently - part of a 3-part blog series. I use all three techniques to create a "critical `BackgroundService`" base type that avoids startup delay (`Task.Run`), catches `ExecuteAsync` exceptions, and logs and then exits the host if a critical background service fails.

**Comment by maryamariyan** [comment]
> Can I go ahead and make a PR for this, or should I wait?

@Zenexer the source code has moved to dotnet/runtime since. Are you interested in creating a PR for this?

**Comment by nminaya** [comment]
Not sure if this issue is related but I just realized that the CancellationToken passed to BackgroundService.StartAsync is not the same as the one received in ExecuteAsync method. So when the CancellationToken is cancelled, ExecuteAsync is not getting notified through the CancellationToken and keeps running.

**Comment by Nick-Stanton** [comment]
@Zenexer thanks for the catch. A fix has been merged to resolve this behavior
