### ISSUE TITLE
Developers can get immediate feedback on validation problems

### ISSUE THREAD

**Issue by HaoK** [dotnet/runtime#36391]
_Updated by @maryamariyan:_

### Goal

When an application starts, we want to get immediate feedback on validation problems. e.g. we would like to get exceptions thrown on app startup rather than later.

*Benefits of eager validation*:
* Enabling this feature forces the program to crash fast when an invalid configuration is passed, as opposed to the default lazy validation only when `IOptions<T>` is requested

### API Proposal

`ValidateOnStart` feature is implemented as extension to[ `OptionsBuilder<TOptions>`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#optionsbuilder-api)
To allow for eager validation, an API suggestion is to add an extension method on OptionsBuilder, (not IHost).

#### Usage:

```csharp
services.AddOptions<MyOptions>()
    .ValidateDataAnnotations()
    .ValidateOnStart();                 // Support eager validation
```

#### APIs:

According to usage, we'd need the APIs below:

```C#
namespace Microsoft.Extensions.DependencyInjection
{
    public static class OptionsBuilderExtensions
    {
        public static OptionsBuilder<TOptions> ValidateOnStart<TOptions>(this OptionsBuilder<TOptions> optionsBuilder) where TOptions : class;
    }
}
```
#### Focus of this issue:

The focus here is on eager validation at application startup, and these APIs don't trigger for IOptionsSnapshot and IOptionsMonitor, where values may get recomputed on every request or upon configuration reload after the startup has completed.

* It would support named options too.
 
##### `IOptions<TOptions>`: 
 - Reads configuration data only after the app has started.
 - Does not support [named options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#named)

##### `IOptionsSnapshot<TOptions>`: 
May be recomputed on every request, and supports [named options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#named)

##### `IOptionsMonitor<TOptions>`: 
Is registered as a singleton, supports [named options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#named), change notifications, configuration reloads, and can be injected to any service lifetime.

<details>
 <summary> Original Description (click to view)</summary>

[AB#1244419](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1244419)
From exp review with @ajcvickers @DamianEdwards @Eilon @davidfowl 

We should support some mechanism for eager (fail fast on startup) validation of options.  

Needs to also work for generic host as well as webhost, must be configurable on a per options instance, since this will never work for request based options.

</details>

**Comment by ngbrown** [comment]
For a background worker (console and/or service), I am already using `ConfigureAppConfiguration` and would like to eagerly validate options from command-line, environment settings, and `appsettings.json`.

Adapting the above, I did the following:

```cs
public class Program
{
    public static int Main(string[] args)
    {
        try
        {
            CreateHostBuilder(args).Build()
                .ValidateOptions<LoggingOptions>()       // new line per option to validate.
                .ValidateOptions<CredentialsOptions>()
                .Run();
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Host terminated unexpectedly");
            return 1;
        }
    }

    // etc.
}
```

```cs
public static class OptionsBuilderValidationExtensions
{
    public static IHost ValidateOptions<T>(this IHost host)
    {
        object options = host.Services.GetService(typeof(IOptions<>).MakeGenericType(typeof(T)));
        if (options != null)
        {
            // Retrieve the value to trigger validation
            var optionsValue = ((IOptions<object>)options).Value;
        }
        return host;
    }
}
```

**Comment by scottbarnesbass** [comment]
Has anyone written any tests for these solutions? @michaelgregson I've implemented somehting very similar to your solution...

**Comment by maryamariyan** [comment]
Added api-suggesion label to this issue. The best next step on this would be to prepare the API proposal, usage, etc. in the issue page here (following https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

**Comment by davidfowl** [comment]
I'm not a fan of this proposal (I don't think there should be an extension method on the host). Also that implementation is more complex than it needs to be.

**Comment by danmosemsft** [comment]
@maryamariyan as this is work generated by the team (as opposed to necessary for the high level .NET 6 themes) please label it "bottom up"
Also you will want to list it in the Epic https://github.com/dotnet/runtime/issues/44314 so that it is parented when you go to https://themesof.net/?q=is:open%20kinds:teub as opposed to floating at the bottom.

**Comment by danmosemsft** [comment]
you may also want to add a cost and/or priority labels according to your judgement

**Comment by danmosemsft** [comment]
@maryamariyan can you please ensure User stories have a title in the form "XXX can YY" indicating what user experience changes. Take a look at other titles: https://themesof.net/?q=is:open%20kinds:ub%20team:Libraries  Same for #44517.

**Comment by terrajobst** [comment]
* Looks good as proposed
* Only question is: is `Eagerly` the right term here? Any opinions @davidfowl?

```C#
namespace Microsoft.Extensions.DependencyInjection
{
    public static class OptionsBuilderDataAnnotationsExtensions
    {
    //  Already exists:
    //  public static OptionsBuilder<TOptions> ValidateDataAnnotations<TOptions>(this OptionsBuilder<TOptions> optionsBuilder) where TOptions : class;
        public static OptionsBuilder<TOptions> ValidateAnnotationsEagerly<TOptions>(this OptionsBuilder<TOptions> optionsBuilder) where TOptions : class;
        public static OptionsBuilder<TOptions> ValidateEagerly<TOptions>(this OptionsBuilder<TOptions> optionsBuilder) where TOptions : class;
    }
}
```

**Comment by davidfowl** [comment]
> Is Eagerly the right term here? I think we'd prefer OnStartup Any opinions @davidfowl?

I prefer ValidateOnStartup, though people may think it has something to do with the Startup class. What about `ValidateOnStart`?

**Comment by maryamariyan** [comment]
> Why do we need both ValidateEagerly and ValidateDataAnnotationsEagerly

The ValidateDataAnnotationsOnStartup would also validate data annotations, would be same as calling

```c#
services.AddOptions<MyOptions>()
   .Configure(o => o.Boolean = false)
   .Validate(o => o.Boolean)
   .ValidateOnStartup();
```

 but it is also possible for us to configure validating options that are specified inline, e.g.

```c#
services.AddOptions<MyOptions>()
   .Configure(o => o.Boolean = false)
   .ValidateDataAnnotationsOnStartup();
```

**Comment by HaoK** [comment]
I like ValidateOnStart too, eagerly isn't clear exactly what that means

**Comment by terrajobst** [comment]
* Let's drop the `new()` constraint? The existing `OptionsBuilderDataAnnotationsExtensions.ValidateDataAnnotations()` method doesn't have it.
* We considered existing types in that namespace but we don't think there is an appropriate home for this.

```C#
namespace Microsoft.Extensions.DependencyInjection
{
    public static class OptionsBuilderValidationExtensions
    {
        public static OptionsBuilder<TOptions> ValidateOnStart<TOptions>(this OptionsBuilder<TOptions> optionsBuilder) where TOptions : class;
    }
}
```

**Comment by davidfowl** [comment]
> Let's drop the new() constraint? The existing OptionsBuilderDataAnnotationsExtensions.ValidateDataAnnotations() method doesn't have it.

👍🏾
