### ISSUE TITLE
ConfigurationSource load async resource

### ISSUE THREAD

**Issue by Meir017** [dotnet/runtime#36395]
### Problem:

I'm am trying to create a `ConfigurationProvider` that loads data from an http endpoint but there isn't a `LoadAsync` method to use.

### Describe the solution you'd like
1. maybe add a virtual `LoadAsync` method to the `ConfigurationProvider` abstract class
2. add another type `AsyncConfigurationProvider` that only has a `LoadAsync` method and not the `Load` method
### Describe alternatives you've considered
using `.GetAwaiter().GetResult()` on the task

**Comment by maryamariyan** [comment]
Next step for this is to prepare API suggestion and sample usage as per guideline in https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

**Comment by maryamariyan** [comment]
closing as dupe of https://github.com/dotnet/runtime/issues/36018
