### ISSUE TITLE
Remove IDisposable from ICacheEntry

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#36392]
https://github.com/aspnet/Caching/blob/65228be1d9aba6f2c360553868010f18706ee302/src/Microsoft.Extensions.Caching.Abstractions/ICacheEntry.cs#L13

IDisposable recommends a `using` pattern as follows, where Dispose commits the entry to the cache:
```
using (var entry = MemoryCache.CreateEntry(cacheKey))
{
  // The result is processed inside an entry
  // such that the tokens are inherited.
  entry.Value = CreateValue(params);
  entry.SetOptions(options); 
}
```

However, if CreateValue throws then the entry is still committed to the cache as null. Thus the `using` pattern should not be used with ICacheEntry, and we should remove IDisposable to prevent it. Replace it with a Commit method.

https://github.com/aspnet/Mvc/issues/6522

**Comment by maryamariyan** [comment]
The major issues with Dispose on ICacheEntry were addressed in PR https://github.com/dotnet/runtime/pull/42355 in 5.0.

At this point the cost of doing this breaking change outweighs any benefit we get.
