### ISSUE TITLE
Add support for IHostingStartup/IHostStartup  in generic host

### ISSUE THREAD

**Issue by chuanboz** [dotnet/runtime#36394]
In WebHost, there is IHostingStartup interface, see https://github.com/aspnet/Hosting/issues/1000.

Can we do something similar for [generic host](https://github.com/aspnet/Hosting/issues/1163), something like below

```C#
/// <summary>
    /// Represents platform specific configuration that will be applied to a <see cref="IHostBuilder"/> when building an <see cref="IHost"/>.
    /// </summary>
    public interface IHostStartup
    {
        /// <summary>
        /// Configure the <see cref="IHostBuilder"/>.
        /// </summary>
        /// <remarks>
        /// Configure is intended to be called before user code, allowing a user to overwrite any changes made.
        /// </remarks>
        /// <param name="builder"></param>
        void Configure(IHostBuilder builder);
    }
```

I will need this to execute some platform specific logic for integration testing with Service Fabric; I could define my own interface and get it work, but it would be useful if such concept could be generic in the generic host.

**Comment by ElanHasson** [comment]
Any updates on this item?

**Comment by ElanHasson** [comment]
cc: @davidfowl @Tratcher 

I made an implementation that mirrors that in `WebHostBuilder`, complete with `HostingStartupAssemblies` and
`HostingStartupExcludeAssemblies` support. Here is a repo: https://github.com/ElanHasson/GenericHostHostingStartup

After further inspection I don't think it is a straightforward as just adding those methods. IMO the better implementation would be to support it in `Host` versus `WebHost`.

Also, moving `HostingStartupAttribute` and friends over to Microsoft.Extensions.Hosting.Abstractions would be a breaking change. 

I'm happy to make changes and send a PR once design consensus is achieved.

**Comment by 3GDXC** [comment]
@davidfowl @Tratcher any updates on this? it's something that I'd like to use; but not sure if it's work implementing myself or if a extension from the team is coming/available or on backlog?

**Comment by eerhardt** [comment]
I'm closing this issue as this isn't an approach we are going to take.

Instead, in `7.0` the plan is to implement https://github.com/dotnet/runtime/issues/61634, which eliminates the need for `Startup` methods. And instead, the startup logic will look more like the [ASP.NET Minimal APIs](https://docs.microsoft.com/aspnet/core/fundamentals/minimal-apis) (which don't have Startup methods anymore either).
