### ISSUE TITLE
UsePollingWatcher getter throws Exception

### ISSUE THREAD

**Issue by chadgrant** [dotnet/runtime#36397]
```
 Error getting value from 'UsePollingFileWatcher' on 'Microsoft.Extensions.FileProviders.PhysicalFileProvider'. ---> System.InvalidOperationException: Cannot modify UsePollingFileWatcher once file watcher has been initialized.
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.get_UsePollingFileWatcher()

```
Trying to dump/serialize the current config and can't. Getters on properties shouldn't throw exceptions.

**Comment by anurse** [comment]
This should have been fixed in https://github.com/dotnet/extensions/pull/2099 which should have been released in the 5.0 previews. Let us know if you're still seeing this on 5.0 previews.
