### ISSUE TITLE
timeout for synchronous socket connect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#364]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/712952/timeout-for-synchronous-socket-connect.html)._

---
Timeout works for receive, but not for accept.  Documenting this bug did not turn it into a feature.  Please fix.  While I understand Asynch is the One True Path, and someone apparently passionately wants to promote it, it seems excessively complicated for the task at hand, and timeout on connect seems like a basic, 101-level, standard normal boring vanilla thing that should be there on the synchronous connect in any sockets library.

---
#### Jane Wu [MSFT] on 8/27/2019, 01:37 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by scalablecory** [comment]
The standard way to accomplish this is with `Select`, something like:

```c#
static Socket ConnectWithTimeout(EndPoint ep, SocketType socketType, ProtocolType protocolType, TimeSpan timeout)
{
    Socket socket = new Socket(ep.AddressFamily, socketType, protocolType);

    try
    {
        socket.Blocking = false;

        try
        {
            socket.Connect(ep);
        }
        catch (SocketException ex) when (ex.SocketErrorCode == SocketError.WouldBlock)
        {
            // expected, do nothing.
        }

        var writeSet = new List<Socket> { socket };
        var errorSet = new List<Socket> { socket };
        Socket.Select(null, writeSet, errorSet, checked((int)(timeout.TotalSeconds * 1_000_000)));

        if (writeSet.Count != 0)
        {
            socket.Blocking = false;
            return socket;
        }

        if (errorSet.Count != 0)
        {
            var err = (SocketError)socket.GetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Error);
            throw new SocketException((int)err);
        }

        throw new SocketException((int)SocketError.TimedOut);
    }
    catch
    {
        socket.Dispose();
        throw;
    }
}
```

**Comment by karelz** [comment]
Triage: There is workaround. Over last decade this is the only ask we've seen for this (despite the "101" claim).
Implementation-wise it is complicated as not all connect timeouts are exposed in all OSs.
Closing until we get more people asking for it. We can then reconsider.
