### ISSUE TITLE
LoggerT and CreateLogger(...Type) don't include resolved type parameter name

### ISSUE THREAD

**Issue by zarenner** [dotnet/runtime#36401]
When using CreateLogger<SomeService\<TKind>> logs don't include the resolved type of TKind.
That is, they just show up just as 'SomeNamespace.SomeService'.

From a quick look, it seems that TypeNameHelper.GetTypeDisplayName in Shared supports this. Is there a reason CreateLogger/LoggerT aren't using it?

edit: Sorry for the confusion - Markdown killed the "TKind" above.

**Comment by maryamariyan** [comment]
@zarenner closing as per @pranavkm 's comment and since the behavior seems to have been originally intentional and has a risk of breaking existing logging setups. 
If you still believe this is highly blocking please let us know and go ahead and reopen @zarenner .
