### ISSUE TITLE
What are the scenarios Main method getting called in Worker Service after installing it

### ISSUE THREAD

**Issue by arvindrajachourasiya** [dotnet/runtime#36417]
# Issue Title

What are the scenarios Main method getting called in Worker Service after installing it in Windows/Linux machine

# General
I am working on .NET Core "Worker Service" project to implement service for Windows & Linux machine.

Service reading data from external config.xml file like credentials/urls. I want to add interval time too in config file so that in future if I want change schedule time I will just modify config file, I not need to modify my code and recompile.

I am using [Coraval](https://docs.coravel.net/) library for scheduler. I am setting interval time in Main method. My doubt is when I will change interval time in config file(which is being read in Main method). 

How often Main method getting called so that it will read new scheduling time from config file?

This is my code

```
public static void Main(string[] args)
{
	var schedulingConfig = GlobalSettings.ReadIntervals(out List<intervalValue> intervalvalues);
	string intrvaltype = string.Empty;
	foreach (var item in schedulingConfig)
	{
		if (item.Name == "true")
		{
			intrvaltype = item.Execution;
			break;
		}
	}
	IHost host = CreateHostBuilder(args).Build();
	host.Services.UseScheduler(scheduler =>
	{
	   //Remind schedular to repeat the same job  
		switch (intrvaltype)
		{
			case "isSignleHourInADay":
				scheduler
			   .Schedule<ReprocessInvocable>()
			   .Hourly();
				break;
			case "isMinutes":
				scheduler
			   .Schedule<ReprocessInvocable>()
			   .EveryFiveMinutes();
				break;

			case "isOnceInADay":
				scheduler
			   .Schedule<ReprocessInvocable>()
			   .Daily();
				break;

			case "isSecond":
				scheduler
			   .Schedule<ReprocessInvocable>()
			   .EveryThirtySeconds();
				break;
		}  
	});
	host.Run();
}
```
Please help me how my code going to work?

**Comment by arvindrajachourasiya** [comment]
@Dotnet-GitSync-Bot - The area label not doing justice with issue. The clearly falls under ".NET Core Worker Service", You should have provided a proper documentation of flow service life.

**Comment by arvindrajachourasiya** [comment]
@scalablecory - Could you please provide me solution?

**Comment by scalablecory** [comment]
@arvindrajachourasiya Main will only ever be called once here, so it looks like your config will only be read once on startup. @Pilchie do we have a generalized way to handle config  updates here?

**Comment by Pilchie** [comment]
Using `IOptionsMonitor<T>` as described in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1

**Comment by arvindrajachourasiya** [comment]
@pi1024e  - Such a worst article I have never seen in my life.

**Comment by davidfowl** [comment]
I would look for something more native as part of Coraval and file the issue on that repository. Maybe they support binding to configuration natively. IOptions\<T\> is more for implementing this yourself. You might be able to do that but it would also require being able to change the underlying scheduler (which I'm not sure you can do).

**Comment by arvindrajachourasiya** [comment]
@davidfowl - Thank you. In Coraval there is something called `When`. I am checking with it. If I can fix this issue.

**Comment by maryamariyan** [comment]
@arvindrajachourasiya closing issue as it seems to be answered please reopened if you need more information.
