### ISSUE TITLE
Can't launch a .net core 3.0 WPF app from another .net core 3.0 app

### ISSUE THREAD

**Issue by AnthonyM** [dotnet/runtime#3642]
I have a .net core 3.0 WPF application, called client.exe.

I have a second .net core 3.0 application. 

I'm trying to launch client.exe from the other application. I get the error, 
```
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.
```

The code is
```c#
var filename = @$"bin\Debug\netcoreapp3.0\Client.exe";
var child = Process.Start(new ProcessStartInfo()
{
  WorkingDirectory = Path.GetDirectoryName(filename),
  FileName = filename,
});
```

**Comment by elinor-fung** [comment]
@AnthonyM I am closing this for now since we have not been able to repro this. If you are still seeing this in latest versions of .NET and have more information, feel free to reactivate.
