### ISSUE TITLE
Regex . does not match UTF-16 surrogate pairs "😃"

### ISSUE THREAD

**Issue by GeneThomas** [dotnet/runtime#36425]
. in a regular expression should match one code point, presently .net’s Regex "." does not match UTF-16 surrogate pair "😃".

Iʙᴍ’s Iᴄᴜ C++ project does regexes . vs UTF-16 correctly: http://userguide.icu-project.org/strings/regexp it uses UTF-16 for it’s UnicodeString.

The attached project exercises the fault in .net:

[RegexUnicodeFaultTest.zip](https://github.com/dotnet/runtime/files/4625508/RegexUnicodeFaultTest.zip)

**Comment by stephentoub** [comment]
Regex doesn't support surrogates today. All comparisons are performed on individual chars.

**Comment by danmosemsft** [comment]
I guess we do not need an issue tracking this. Thanks for the report @GeneThomas !

**Comment by GrabYourPitchforks** [comment]
Steve / Dan, wasn't there discussion earlier of improving Regex all-up? I know you've been making perf improvements lately, but I thought there was some talk about overhauling the engine in its entirety. This seems like something we might address if / when we do that.

**Comment by danmosemsft** [comment]
@GrabYourPitchforks so far as I recall that talk was motivated solely by its uncompetitive perf. @stephentoub has managed to make the existing engine competitive and identify more perf opportunities. I don't think we have other major plans. This is the first request I can recall for surrogate support. How commonly doea such text exist? Why would one run a regex on emojis?

**Comment by GrabYourPitchforks** [comment]
There's more to the surrogate range than just emoji. See https://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt, everything from `10000..1007F` and after. But the odds of coming across such text in the wild is by design fairly low.

I'd be more concerned with how we handle things like diacritics (see https://en.wikipedia.org/wiki/Combining_character and https://en.wikipedia.org/wiki/Arabic_diacritics for some examples). They're not surrogates, but in the context of this issue we can draw parallels because diacritics take multiple `char` elements to form what we perceive as a single display character. If we have problems with surrogates then we probably also have problems with this category of characters. @tarekgh is the subject matter expert on how common / uncommon it is to come across such text in the wild.

**Comment by tarekgh** [comment]
> @tarekgh is the subject matter expert on how common / uncommon it is to come across such text in the wild.

The part of the Surrogate range that can be interesting is the CJK extensions which I expect will be widely used by people speaking CJK languages and these ranges which include a list of characters which support casing. The reset of Surrogate is not that interesting especially if it came to regex. I would say, declaring current regex work for a single character only would be ok till we get more demands on supporting multiple characters (Surrogates, ligatures, diacritics...etc.).

**Comment by danmosemsft** [comment]
As far as I know, none of our first class API on `string` support this, right? Would we ever support such sequences in `string` (it being originally UCS-2 - hopefully that's the correct term). Should I instead think of this as Regex adding support for Utf8String?

**Comment by tarekgh** [comment]
> As far as I know, none of our first class API on string support this, right?

Not true. we already support Surrogates. e.g. string casing and comparison and other functionality like StringInfo and encoding.

**Comment by danmosemsft** [comment]
Interesting. I would like to learn more about that eg my assumption was indexing was naive and just moved 2 bytes along at a time. Perhaps I can learn more offline.

**Comment by GrabYourPitchforks** [comment]
Good news! We recently posted a doc that should explain some of these concepts in a bit more detail. :)
https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction

**Comment by danmosemsft** [comment]
That is an awesome article. Thank you @tdykstra

**Comment by tdykstra** [comment]
Thanks to @GrabYourPitchforks for writing the original text that I edited. 😄

**Comment by stephentoub** [comment]
It's a great write-up.  FYI, some things don't display well with a dark theme in the browser.
![image](https://user-images.githubusercontent.com/2642209/82056551-1df0d180-9690-11ea-97ac-445397fa5c83.png)

**Comment by tdykstra** [comment]
@stephentoub Thanks for letting me know.  I'll get that fixed.
