### ISSUE TITLE
Don't run the CI if only .md files were changed

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#36457]
While reviewing #36431 where only `.md` were edited, I've noticed that the CI was triggered and all tests executed:

![obraz](https://user-images.githubusercontent.com/6011991/81960515-5b624a00-9611-11ea-94bb-2fda85298513.png)

We had a similar problem in the performance repo in the past which was solved by: https://github.com/dotnet/performance/pull/355

I am an AzDO n00b and I could not find `azure-pipelines.yml` in this repo, so this is why I create an issue instead of sending a PR.

/cc @ViktorHofer

**Comment by ViktorHofer** [comment]
@adamsitnik seems like we can't easily ignore all .MD files. I think there's a uservoice ticket somewhere against AzDO to support that. Closing.

**Comment by ViktorHofer** [comment]
Moving to future, let's see if Github actions will allow this.

**Comment by ViktorHofer** [comment]
Closing as not actionable (AzDO limitation). Feel free to reopen when we moved off AzDO.
