### ISSUE TITLE
Why read values from object when binding object to configuration-section

### ISSUE THREAD

**Issue by PeterLarsen-CPH** [dotnet/runtime#36459]
I am trying to understand why it is necessary to call all getters on object when binding object to configuration, e.g the following code:

- Configuration.GetSection("AppSettings").Bind(new MySettings())

...cause all getters to be called on MySettings.
I would expect it to go the other way around, like:

1. First read the configuration
2. Then search for properties with the same name
3. and set values if matching names are found

As it is today, all getters are called on MySettings - also on properties only exists in MySettings.
I guess the reason is that we don't want to overwrite existing values in MySettings with values from the configuration, but the code should not test properties not existing in the configuration.

Why is this a problem?
It is a problem because some properties in the object may fail if e.g. not all properties are loaded from configuration.

What could be the solution?
Add a property to BindingOptions saying whether to always overwrite if value exists in configuration, or not. This could remove the need of calling the getters. It's not important how it is solved, it should just involve a switch to prevent the getters from being called.

Thanks.

**Comment by maryamariyan** [comment]
> Add a property to BindingOptions saying whether to always overwrite if value exists in configuration, or not. This could remove the need of calling the getters. It's not important how it is solved, it should just involve a switch to prevent the getters from being called.

Thanks @PeterLarsen-CPH for your issue. The next step for this would be to prepare API proposal and sample usage for this

**Comment by madelson** [comment]
I believe that the `BindingPoint` class now provides this functionality: we only call property getters when we actually need the value (e.g. for binding nested objects).

**Comment by PeterLarsen-CPH** [comment]
> I believe that the `BindingPoint` class now provides this functionality: we only call property getters when we actually need the value (e.g. for binding nested objects).

Not bad @madelson - many thanks.
