### ISSUE TITLE
[System.Text.Json] The JsonSerializer should Have "Try" method variants

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/runtime#36452]
Simply put: The Serializer should have build-in Try -methods, to simplify handling of bad data. This should work just like Guid.TryParse();

So something like:
```C#
bool success = JsonSerializer.TryDeserializeObject<User>(jsonString, out var user);
```

Searched for issues using "System.Text.Json JsonSerializer try is:open " and found nothing, so this should not be a duplicate

**Comment by layomia** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/29902.
