### ISSUE TITLE
Consider adding SingleToUInt32Bits(float value) to BitConverter

### ISSUE THREAD

**Issue by pgovind** [dotnet/runtime#36469]
BitConverter has APIs to convert float -> int, but not `uint`. Sometimes it's useful to get the `uint` bits underlying a float too (for ex: I'd find it useful for https://github.com/dotnet/runtime/issues/936).

API:
``` csharp
public static unsafe ulong DoubleToUInt64Bits(double value);
public static unsafe double UInt64BitsToDouble(ulong value)

public static unsafe ushort HalfToUInt16Bits(Half value);
public static unsafe Half UInt16BitsToHalf(ushort value)

public static unsafe uint SingleToUInt32Bits(float value);
public static unsafe float UInt32BitsToSingle(uint value)
```

Note: `uint` is not CLS compliant

cc @tannergooding

**Comment by pgovind** [comment]
Tagging @joperezr and @bartonjs as area owners

**Comment by jkotas** [comment]
Is it really that hard to cast to `uint` as needed in this case? 

There are many APIs in .NET that return `int` and where `uint` is sometime more convenient for micro-optimizations. I do not think it makes sense to add `uint` variants to all these APIs.

**Comment by tannergooding** [comment]
In many cases for `float`/`double` it also isn't about micro-optimization, but instead correctness as you internally manipulate the parts using shifts and you don't want the sign being carried.
In order to implement `Half` for example, we will have to provide software fallbacks that manipulate the raw bits of each and that will in turn require a number of additional casts to be inserted hindering readability of already complex code.
S.P.Corelib itself wouldn't be blocked as we can just define an internal helper but if we are already defining it, and its a trivial function that would provide convenience to 3rd party users as well, then I don't see why we shouldn't also propose it as a more general API.

It's also worth noting it isn't always just casting to uint, if you are using any kind of literal then C# will require you to insert an `unchecked()` as well (due to the sign bit being set):
```csharp
uint bits = (uint)BitConverter.SingleToInt32Bits(value);
float value = BitConverter.Int32BitsToSingle(unchecked((int)0x80000000));
// vs
uint bits = BitConverter.SingleToUInt32Bits(value);
float value = BitConverter.UInt32BitsToSingle(0x80000000);
```

**Comment by DaZombieKiller** [comment]
Would it also make sense to add the equivalents for `double`?
```cs
public static unsafe ulong DoubleToUInt64Bits(double value);
public static unsafe double UInt64BitsToDouble(ulong value);
```

**Comment by tannergooding** [comment]
I'm going to mark this as `ready-for-review` and we can have further discussion on whether or not this is warranted in API review. We already have these methods internally.

**Comment by jkotas** [comment]
> We already have these methods internally.

Pointers? I do not think we have them in any shipping binaries.

**Comment by tannergooding** [comment]
> Pointers? I do not think we have them in any shipping binaries.

Ah, you're right, I was misremembering.

We just have many of the internally usages in product code explicitly converting to the unsigned variant:
* https://source.dot.net/#System.Private.CoreLib/BitConverter.cs,27a5a69559e7663e,references
* https://source.dot.net/#System.Private.CoreLib/BitConverter.cs,db20ea77a561c0ac,references
* https://source.dot.net/#System.Private.CoreLib/BitConverter.cs,bd24ba94db019618,references

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System
{
    public static class BitConverter
    {
        public static unsafe ulong DoubleToUInt64Bits(double value);
        public static unsafe double UInt64BitsToDouble(ulong value);

        public static unsafe ushort HalfToUInt16Bits(Half value);
        public static unsafe Half UInt16BitsToHalf(ushort value);

        public static unsafe uint SingleToUInt32Bits(float value);
        public static unsafe float UInt32BitsToSingle(uint value);
    }
}
```

**Comment by MichalPetryka** [comment]
I'd like to try and do this, if I understand correctly `src\libraries\System.Private.CoreLib\src\System\BitConverter.cs` is the place for API implementation and `src\libraries\System.Runtime.Extensions\tests\System\BitConverter.cs` for the unit tests, is there any other place that needs changing?

**Comment by tannergooding** [comment]
> is there any other place that needs changing?

The APIs would need to be expose, tests added, and ideally all the existing usages would be updated to use the new APIs as appropriate: https://source.dot.net/#System.Private.CoreLib/BitConverter.cs,27a5a69559e7663e,references.
This would include places that are directly doing `(uint)BitConverter.SingleToInt32Bits(value);` (such as https://source.dot.net/#System.Private.CoreLib/BinaryWriter.cs,309)
As well as places that are correctly using things like `unchecked((int)(0x80000000))` after getting the signed bits (such as https://source.dot.net/#System.Private.CoreLib/MathF.cs,73)

**Comment by MichalPetryka** [comment]
Okay, I've implemented the APIs itself and unit tests for them locally, should I open a draft before I go over all the existing usages  or do that and then open a PR?

**Comment by tannergooding** [comment]
> should I open a draft before I go over all the existing usages or do that and then open a PR

I don't have a preference myself. That being said, we prefer to not keep draft PRs open for too long so it would likely be good to wait if you don' think you'll be able to get the remaining changes up within a few days of creating the draft.

**Comment by tannergooding** [comment]
@MichalPetryka, are you still working on this?

If so, it would be great to get a PR up so we can get this into .NET 6. And if not, please let me know and I can pick it up and finish it out (even using your existing changes/commits if that's alright with you)

**Comment by MichalPetryka** [comment]
Sorry, I've had some trouble running the tests (wasn't able to start them at all, even without any changes) and then I got sick and forgot about this. I'll get back to this tommorow.
