### ISSUE TITLE
ReferenceFromRuntime aren't resolvable inside VS if the default runtime configuration hasn't been built

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#36464]
Following up on the discussion here: https://github.com/dotnet/runtime/pull/36126#issuecomment-628363503.

My recommendation is to get rid of `ReferenceFromRuntime` items that point to CoreLib and replace them with P2Ps. The P2P would either point to coreclr's or mono's CoreLib.

cc @safern @ericstj @GrabYourPitchforks

**Comment by ericstj** [comment]
To make P2P work CoreLib would have to state all its TargetFrameworks and cross-compile by those and not rely on any global properties from a vertical build to determine its content.  Is that what you had in mind @ViktorHofer?

**Comment by safern** [comment]
Related issue: https://github.com/dotnet/runtime/issues/34653
