### ISSUE TITLE
Allow direct access to ICacheEntry and make it thread safe 

### ISSUE THREAD

**Issue by ohadschn** [dotnet/runtime#36498]
Currently all methods that return a value from the cache (most importantly `TryGetValue`) directly return the underlying `object`. This is convenient but does not allow for a scenario of updating an entry's expiration after it has been added. Even if I retain a reference to the original `ICacheEntry` returned from `CreateEntry` it won't be good enough as no memory barriers are raised when accessing its properties (so I might change the expiration time in my thread, but your `StartScanForExpiredItems` thread won't observe them).

**Comment by adamsitnik** [comment]
This feature request has received 0 new comments or upvotes from other users for more than 6 years. I am sorry, but we are not going to implement it. Thank you!
