### ISSUE TITLE
Transient Disposal

### ISSUE THREAD

**Issue by dazinator** [dotnet/runtime#36491]
UPDATE: Quicker to read this comment first: 
 https://github.com/dotnet/extensions/issues/3252#issuecomment-628489160

Background: 
https://github.com/dotnet/extensions/issues/1785

It's currently a known (accepted?) behavior that:

- You can register a transient service that implements `IDisposable` for DI.
- The container / scope takes ownership of any transient instances it then creates. Those instances won't be disposed until the container or scope is itself disposed. 

Now consider you are resolving many transient instances from a root container *or* just a scope that happens to live a long time before disposal - for example:
- a background process of an app such as a windows forms app etc
- a long running integration or system test

I list those examples because a http request having a scope is not the only game in town for scopes.

All of the transient `IDisposable` instances whilst that scope is alive will accrue and you get a form of memory leak where services are kept alive way past their need.

I appreciate the design philosophy behind this feature may have originally been around:

1. If we inject an IDisposable and don't track it.. what if the developer forgets to dispose of it?
2. If we inject an IDisposable instance into some service, how does that service know whether it needs to dispose of that or not? For example if the IDisposable was registered as scoped or singleton then it should NOT be disposed.

Both 1 & 2 can be answered:

1. Don't inject transient IDisposable's. Inject some other factory function instead.
2. As above, if an IDisposable is directly injected then it is owned elsewhere and the service does not dispose it. If a transient IDisposable is created as a result of a call to an injected factory, then as its a new instance, we own it, and we dispose of it.

So.. the harsh line and better long term solution for the framework on this would be to disallow the registration of transient types that implement IDisposable:

```
services.AddTransient<FooDisposable>();
```

The above would error. Ideally if the c# language was a touch more expressive with generic type constraints and had support for [not constraints] as someone raised here: (https://github.com/dotnet/csharplang/issues/707) this would ideally cause a compile error (type constraint indicating the type must *not* implement IDisposable) rather than wait for a runtime exception.

This would be a breaking change (alternative non breaking suggestion below) I know. A compile error with a suggestion (analyzer) could really help mitigate that, along with some docs covering how to amend such service registrations and why. I think it would be better to address this issue rather than continue to allow developes to be caught by surprise memory issues. The fact that the container keeps alive transients *is not intuitive* given that once the instance goes out of scope it's done with. This is not the case with Scoped or Singleton services where this makes perfect sense.

The change in user code could be that the consumer needs to change the registration (and constructor args) to something like this instead:

``` 
// register your own factory for disposable transients.
services.AddTransient<Func<FooDisposable>>(sp=>new FooDisposable());
```

This could even ship as an extension method of sorts:

```
services.AddTransientFunc<FooDisposable>();
```
E.g the above would set up a `Func<FooDisposable>` slightly more tersely, in a way that `FooDisposable` will be new'ed up by DI when the Func was invoked. 

Note: if you wanted to keep the old behaviour so as not to cause any breaking changes) then this new behavior could be entirely opted into by just providing the new extension method, and guidance that transient disposables should now be registered using it. This means transients registered the old way will behave as before. Transient dispsables registerd the new way would need to be resolved and disposed using the new way. This could be achieved by having the new style registration wire up the Func that it creates, to internally remove the transient instance that it resolved, from the container / scope tracking list when it is invoked.

It would then be down to the consumer to dispose of that instance once they were done with it. 

```
public class FooController
{
   public FooController(Func<DbConnection> factory)
   {
       using var factory(); // you get the idea...
    }
}
```

**Comment by sjb-sjb** [comment]
People have been struggling with this for at least 5 years now (see date of aspnet/DependencyInjection#456). The desired feature is the ability for the caller to avoid having transient services held in memory until the closing of a scope. I encountered this problem as part of a design in which scope beginning / ending corresponds to opening / closing a database file. 

One of the constraints discussed in https://github.com/dotnet/extensions/issues/1785 is the desirability of getting a solution that works or can be adapted to many different DI containers, at least some of which do not offer any built-in flexibility to release IDisposables from their management. I agree with the view that creating new scopes simply in order to be able to dispose the transients created in that scope is not a very good solution; it is too complex especially if there are multiple types of transients with differing desired lifetimes, which then require multiple scopes active at the same time. 

The approach I took was to provide the user of the transient service with the ability to transfer responsibility for Dispose from the DI container to the caller. To achieve this, I created a Transferable<T> wrapper with a OwnershipTransferring event. The wrapper holds a strong reference to the service until such time as ownership responsibility is transferred to the caller. After responsibility is transferred the wrapper continues to hold a weak reference, however this is not essential to the design. The transferable service is created by an IDisposable factory that keeps a list of the created instances and subscribes to their OwnershipTransferring events. When ownership is transferred, the factory drops the reference to the wrapper. If ownership is never transferred, then when the factory is disposed by the DI container the factory will dispose the wrapper, which will dispose the service.

It can be used in a variety of ways, one example would be along the lines of "using (T service = serviceProvider.GetTransferableService<T>().TakeOwnerhip()) {...}

Sample code is below. Caveats: (a) some parts of this are somewhat tested but other parts are not, (b) this sample code does not deal with concurrency in GetTransferableService and in Service_OwnershipTransferring, which a finished version should, (c) this code does not show the fact that you must register a (scoped) instance of the TransferableTrackingFactory.

    static public class ServiceProviderExtensions
    {
        static public ITransferable<T> GetTransferableService<T>(this IServiceProvider serviceProvider) where T: class, new()
        {
            TransferableTrackingFactory factory = serviceProvider.GetService<TransferableTrackingFactory>();
            return factory.CreateTransferableService<T>();
        }
    }

    public class TransferableTrackingFactory: IDisposable, IAsyncDisposable
    {
        public ITransferable<T> CreateTransferableService<T>() where T: class, new()
        {
            ITransferable<T> transferableService = new Transferable<T>();
            transferableService.OwnershipTransferring += this.Service_OwnershipTransferring;
            this._ownedTransferables.Add(transferableService);
            return transferableService;
        }
        private void Service_OwnershipTransferring(ITransferable transferableService, object args)
        {
            transferableService.OwnershipTransferring -= this.Service_OwnershipTransferring;
            this._ownedTransferables.TryRemove(transferableService);
        }
        public void Dispose()
        {
            foreach (ITransferable transferableService in this._ownedTransferables) {
                if (transferableService is IDisposable disposableService) {
                    disposableService.Dispose();
                }
                this._ownedTransferables.Remove(transferableService);
            }
        }
        public async ValueTask DisposeAsync()
        {
            foreach (ITransferable transferableService in this._ownedTransferables) {
                if (transferableService is IAsyncDisposable asyncDisposableService) {
                    await asyncDisposableService.DisposeAsync();
                }
                this._ownedTransferables.Remove(transferableService);
            }
        }
        private HashSet<ITransferable> _ownedTransferables = new HashSet<ITransferable>();
    }

    public interface ITransferable: IServiceLifetimeConstraints, IDisposable, IAsyncDisposable
    {
        event TypedEventHandler<ITransferable, object> OwnershipTransferring;
    }
    public interface ITransferable<out T> : ITransferable where T: class
    {
        T TakeOwnership();
        bool HasBeenTransferred { get; }
        T Service { get; } // use this to access the service before taking ownership
    }

    // When you take ownership of a service, you are taking over 
    // responsibility for Dispose and DisposeAsync.
    // Before you take ownership, the service provider is responsible for disposal.
    // This is useful for transient services, which would otherwise not be disposed 
    // until the service scope is exited. 
    // The purpose is to allow the transient service to be garbage collected long
    // before the service provider scope exits. 
    public class Transferable<T>: ITransferable<T> where T: class, new()
    {
        public Transferable() => this.StrongReference = new T();

        ServiceLifetime IServiceLifetimeConstraints.MaximumLifetime => ServiceLifetime.Transient; 
        ServiceLifetime IServiceLifetimeConstraints.MinimumLifetime => ServiceLifetime.Transient; 

        private T? StrongReference { get; set; }
        private WeakReference<T>? WeakReference { get; set; }

        public bool HasBeenTransferred => (this.StrongReference == null && this.WeakReference != null);
        public bool OwnedByServiceLocator => !this.HasBeenTransferred;

        public T Service => this.StrongReference ?? throw new InvalidOperationException("Ownership has already been transferred.");

        public static implicit operator T( Transferable<T> transferable) => transferable.Service;

        // Use this to access the service after taking ownerhip; but null if reference has been dropped 
        public T? TryTransferredService {
            get {
                Debug.Assert((this.StrongReference != null) == (this.WeakReference == null));
                if (!this.HasBeenTransferred) { throw new InvalidOperationException("Ownership has not been transferred yet."); }
                T target;
                if (this.WeakReference!.TryGetTarget(out target)) { return target; }
                return null;
            }
        }

        public event TypedEventHandler<ITransferable, object>? OwnershipTransferring;

        // Release the T from the ownership of this, so that this will no longer keep the T in memory.
        // And raise an event so that others can release their reference to this.
        // Return the released T. 
        public T TakeOwnership()
        {
            Debug.Assert((this.StrongReference != null) == (this.WeakReference == null));
            if (this.HasBeenTransferred) { throw new InvalidOperationException("Already transferred ownership!"); }
            T strongReference = this.StrongReference ?? throw new NullabilityLogicException();
            this.OwnershipTransferring?.Invoke(this, strongReference);
            this.WeakReference = new WeakReference<T>(strongReference);
            this.StrongReference = null;
            return strongReference;
        }

        // Dispose the T, if it has not been transferred already. 
        public void Dispose()
        {
            if (this.HasBeenTransferred) { return; }

            if (this.StrongReference is IDisposable disposable) {
                disposable.Dispose();
            }
        }
        public async ValueTask DisposeAsync()
        {
            if (this.HasBeenTransferred) { return; }

            if (this.StrongReference is IAsyncDisposable asyncDisposable) {
                await asyncDisposable.DisposeAsync();
            }
        }

    }

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/36461
