### ISSUE TITLE
ConfigurePrimaryHttpMessageHandler is not loading the specified HttpClientHandler in Azure Functions V3 Runtime

### ISSUE THREAD

**Issue by kontacthimanshu** [dotnet/runtime#36493]
### Describe the bug
ConfigurePrimaryHttpMessageHandler is not loading the specified HttpClientHandler in Azure Functions V3 Runtime. 

I am creating an Azure Function and hosting in Azure. The function makes HTTP POST call to TIBCO endpoint. The TIBCO endpoint has self-signed certificate. So I am setting the ServerCertificateCustomValidationCallback of HttpClientHandler to return true always.

### To Reproduce
1. Create an Azure Function using Azure Functions V3
2. Create a Startup.cs file to add IHttpClientFactory and other services to the service collection.
3. While calling AddHttpClient method configure the primary message handler by using ConfigurePrimaryHttpMessageHandler.
4) In the lambda method of ConfigurePrimaryHttpMessageHandler instantiate HttpClientHandler and set the ServerCertificateCustomValidationCallback to a lambda method returning 'true'. 

### Expected behavior
Inject IHttpClientFactory in your functions constructor and try and use the HttpClient objects. The HttpClient object should not complain about self-signed certificate. Currently I am getting an error message saying 'The remote certificate is invalid according to validation procedure'.

### Code
```c#
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;
using Microsoft.Extensions.DependencyInjection;
using RabbitMQ2Tibco;

[assembly: WebJobsStartup(typeof(Startup))]
namespace RabbitMQ2Tibco
{
    public class Startup : IWebJobsStartup
    {
        string serverCertificateValidationSwitch = Environment.GetEnvironmentVariable("ServerCertificateValidationSwitch");
        public void Configure(IWebJobsBuilder builder)
        {
            builder.Services.AddHttpClient("BasicClient", c =>
            {
                
            }).
            ConfigurePrimaryHttpMessageHandler(() =>
            {
                var handler = new HttpClientHandler();
                if (string.Compare(serverCertificateValidationSwitch, "ON", true) == 0)
                {
                    handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };
                }

                return handler;
            });
        }
    }
}
```

### Other approaches already tried are as below:

```c#
.ConfigureHttpMessageHandlerBuilder(builder => 
            {
                builder.PrimaryHandler = new HttpClientHandler() { ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; } }; 
                builder.Build();
            });
```

```c#
builder.Services.AddTransient<ServerCertificateHandler>();
            builder.Services.AddHttpClient("BasicClient", c =>
            {
                
            }).
            ConfigurePrimaryHttpMessageHandler(s => s.GetRequiredService<ServerCertificateHandler>());
			
			public class ServerCertificateHandler : HttpClientHandler
    {
        public ServerCertificateHandler() : base()
        {
            ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };
        }
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            return base.SendAsync(request, cancellationToken);
        }
    }
```

**Comment by kontacthimanshu** [comment]
Here is the full exception:

Error: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at RabbitMQ2Tibco.RabbitMQ2Tibco.Post2Tibco(String json) in C:\Users\<HidingUserName>\Desktop\RabbitMQ2TibcoNew\RabbitMQ2Tibco-CustomMQ\RabbitMQ2Tibco.cs:line 75

**Comment by kontacthimanshu** [comment]
I have tried both types of Azure Functions startup namely FunctionsStartup and WebJobsStartup. Both are showing the lambda expression to validate certificate as loaded. But eventually it is not getting executed.

![HttpClientHandlerLoaded](https://user-images.githubusercontent.com/4209244/82046317-45668f00-96ce-11ea-9379-90faf898b02b.PNG)

**Comment by kontacthimanshu** [comment]
It worked fine locally. I tested it by hosting a WebAPI in local IIS with a self-signed certificate.

**Comment by ericstj** [comment]
@dotnet/ncl any idea why ServerCertificateCustomValidationCallback would not be invoked in Azure Function?

@kontacthimanshu did you try in the same environment without involving ConfigurePrimaryHttpMessageHandler?  For example trying a console app using HttpClient directly and setting ServerCertificateCustomValidationCallback while interacting with the same endpoint.  When you debugged did you find more than one active handler?  Did you look at the instance you got in your `Post2Tibco` method to confirm it has the callback set?

**Comment by wfurt** [comment]
If TLS resume is used, ServerCertificateCustomValidationCallback would not be called (as there is no certificate exchange) 
I don't know about any other cases. I think using HttpClient could provide some useful insight. Is the V3 function backed by Linux or Windows?
