### ISSUE TITLE
Make bundled targets transitive

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/runtime#36495]
Packages like .UserSecrets and .FileProviders.Embedded bundle some MSBuild targets which are essential to make some API function correctly. A repeated problem customers have with this is detailing with transitive references across ProjectReferences. Today, users must add a direct PackageReference to each and every project that uses these.

As of https://github.com/NuGet/NuGet.Client/pull/2667, we have a way to solve this. See https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior. By opting into this new behavior, we should be able to ensure targets in packages are imported correctly in to _all_ projects, not just ones with a direct PackageRef.

**Comment by maryamariyan** [comment]
Seems like an infra issue.

cc: @ericstj @safern

**Comment by ViktorHofer** [comment]
This is about attributing the ProjectReference or the PackageReference items with the right metadata so that they flow transitively. I don't think this is per se an infra issue.

**Comment by ViktorHofer** [comment]
@ericstj do you think this would require work in the pkgproj infra?

**Comment by ericstj** [comment]
No work needed in infra to support this.  The fix is to simply move the props/targets from `build` to `buildTransitive` folder.  https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior

Seems like a good one to do at the start of 6.0.

**Comment by ericstj** [comment]
Looks like this would only apply to `Microsoft.Extensions.Configuration.UserSecrets` in dotnet/runtime.  `Microsoft.Extensions.FileProviders.Embedded` is in [aspnetcore](https://github.com/dotnet/aspnetcore/tree/9f1b61e2fa71d4197c01d83ea870475eebeba7d7/src/FileProviders/Embedded/src/build/netstandard2.0).

**Comment by ericstj** [comment]
Given the usage in UserSecrets requires the project to add a property to actually use it I don't think it makes sense to apply those targets transitively.  If folks want to use that functionality they can directly reference the package as they do today.  Closing this as won't fix.
