### ISSUE TITLE
Question: Does AddHttpClient honor FIPS OS setting?

### ISSUE THREAD

**Issue by amccool** [dotnet/runtime#36490]
When a windows OS has been set using the computer security policy "Use FIPS", does the the HttpClient honor FIPS by only using FIPS compliant ciphers?

nuget in question
https://www.nuget.org/packages/Microsoft.Extensions.Http/3.1.4

Method for getting HttpClient
`.AddHttpClient()`

### Additional context
OS in question is Windows Server 2016 standard
Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> "System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing" to "Enabled".

**Comment by wfurt** [comment]
Yes, it should. The handshake and cipher selection is not done by .NET but by underlying OS functions. It is up to `lsass` to choose.

**Comment by amccool** [comment]
any thoughts on a magical way to test this?   Seems like I cant write a unit test because its dependent on system running it.

**Comment by karelz** [comment]
@amccool you have to run on the FIPS enabled system to get FIPS limitations from OS / OpenSSL. .NET is not doing anything about it, we rely on crypto from OS / OpenSSL.

Closing as answered.

**Comment by wfurt** [comment]
The FIPS setting is probably registry key. You would have to make the test conditional on that.
