### ISSUE TITLE
Ill defined Enums file silently in Configuration Binding

### ISSUE THREAD

**Issue by afcruzs** [dotnet/runtime#36502]
When binding a configuration which contains an Enum type it fails silently if the enum is not well defined. In general, if the binding fails it will just fail silently and that part of the configuration is not binded and proceed. I want to catch this errors to prevent runtime errors due to misconfigurations. 

Is it possible to catch that error or add validation logic somewhere?, or, is it possible to allow control of whether to fail silently or not?

The silent pass happens [here](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Binder/src/ConfigurationBinder.cs#L446) and in other places (depending on the collection type you're binding).

Lets say I have the following json configuration file:

```
{
   "Config": [
        {
          "Color": "Red"
        },
        {
          "Color": "Dog"
        }
    ]
}
```

And I'm trying to bind it to the following class:

```
public class MyConfiguration
{
  public IList<Color> Config { get; set }
}
```

Where Color is an *enum* defined somewhere:

```
public Enum
{
  Red,
  Green,
  Blue,
}
```
If I set "Dog" the enum parse will fail and thus that section of the config will be ignored. I would rather catch that error and let know the user his/her configuration is not well defined.

**Comment by maryamariyan** [comment]
Closing as dupe of https://github.com/dotnet/runtime/issues/36502
