### ISSUE TITLE
ConfigurationReloadToken does not suppress ExecutionContext capture

### ISSUE THREAD

**Issue by smbecker** [dotnet/runtime#36507]
### Describe the bug
Comparing the implementation of `ConfigurationReloadToken` and `CancellationChangeToken`, you can see that `ConfigurationReloadToken` does not suppress the flow of `ExecutionContext` the way that `CancellationChangeToken` does. This can lead to inadvertently capturing an `ExecutionContext`.

I would expect the implementation to be similar to the following...

```c#
public class ConfigurationReloadToken : CancellationChangeToken
{
	private readonly CancellationTokenSource _cts;

	public ConfigurationReloadToken() : this(new CancellationTokenSource())
	{
	}

	private ConfigurationReloadToken(CancellationTokenSource cts) : base(cts.Token)
	{
		_cts = cts;
	}

	public void OnReload() => _cts.Cancel();
}
```

Per the [comment](https://github.com/aspnet/Extensions/issues/558#issuecomment-441420162) on dotnet/extensions#558, I am opening this bug to discuss if this should in fact be changed. If so, I can push a PR with this change.

**Comment by maryamariyan** [comment]
> Per the comment on dotnet/extensions#558, I am opening this bug to discuss if this should in fact be changed. If so, I can push a PR with this change.

This looks like an improvement. Would you like to add a PR for this?

cc: @HaoK @safern

**Comment by safern** [comment]
It makes sense to me.

**Comment by Nick-Stanton** [comment]
Thanks for the catch @smbecker, `ConfigurationReloadToken`'s RegisterChangeCallback method has been changed to avoid this case
