### ISSUE TITLE
[FeatureRequest] add option to ignore invalid configuration files

### ISSUE THREAD

**Issue by JanEggers** [dotnet/runtime#36503]
### Is your feature request related to a problem? Please describe.
We write from our app to a configfile. (through a tempfile and rename that after serialization was successfull). but even with this precautions we sometimes (once in a year) end up with an empty file while the app is starting.
this empty file prevents the app from starting as the jsonconfigfileprovider has no option to swallow errors.

### Describe the solution you'd like
the file is marked as optional. My opinion is that if an optional file is invalid it should be ignored. If it is not possible to implement this behavior with the optional flag there should be another flag that allows to configure this behavior.

### Describe alternatives you've considered
currently I use this methods to determine if I should call addjson:

```csharp
        public static bool ContainsValidJson(this string path)
        {
            if (!File.Exists(path))
            {
                return false;
            }

            using (var fs = new FileStream(path, FileMode.Open))
            using (var sreader = new StreamReader(fs))
            {
                return sreader.IsValidJson();
            }
        }

        public static bool IsValidJson(this TextReader text)
        {
            try
            {
                using (var jreader = new JsonTextReader(text))
                {
                    JObject.Load(jreader);

                    return true;
                }
            }
            catch (Exception)
            {
                return false;
            }
        }

in program.cs
            var app = new WebHostBuilder()
                .ConfigureAppConfiguration( ( host, config ) =>
                {                   
                    if (path.ContainsValidJson())
                    {
                        config.AddJsonFile(path, optional: true);
                    }
                } )
```

**Comment by maryamariyan** [comment]
Thanks for the issue @JanEggers. Could you please add a formal API proposal using guidelines in https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md for this issue?

**Comment by JanEggers** [comment]
## Background and Motivation

improve the visibility of OnLoadException by adding it as a new overload to the configurationbuilder.

## Proposed API

```diff
namespace Microsoft.Extensions.Configuration
{
public static class JsonConfigurationExtensions {
+    public static IConfigurationBuilder AddJsonFile(this IConfigurationBuilder builder, IFileProvider provider, string path, bool optional, bool reloadOnChange, Action<FileLoadExceptionContext> onLoadException)> {
}
```

## Usage Examples

the api should enable the user to catch loading file issues.

## Alternative Designs

the issue can be solved with the current api. but it is required to call some method (ResolveFileProvider) that might not be obvious and leads to errors

## Risks

its just another overload so the only risk is the increased complexity of maintaining another overlaod.


@maryamariyan  is this what you meant by following the guidelines?

**Comment by maryamariyan** [comment]
@JanEggers I must have missed the notification on this. Thanks for filling in the details. Yes, for API proposals, we'd need that detail.

Looking back at the comment thread on this issue now. The sample code recommended by @HaoK lives here today: (code migrated from dotnet/extensions to dotnet/runtime)

https://github.com/dotnet/runtime/blob/6cf1b8ec012d52880d46fa4773f60ed52ddc9f3d/src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs#L450-L459


https://github.com/dotnet/runtime/blob/6cf1b8ec012d52880d46fa4773f60ed52ddc9f3d/src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs#L460-L470

As shown in the test, Given that the existing overloads already allow for ignoring invalid configuration files, there's not much value add to having another overload. I'd lean towards not adding a new API, therefore closing the issue.
