### ISSUE TITLE
[Feature request] Add FileContent Configuration

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/runtime#36501]
Is this a good feature to have a configuration source like KeyPerFile which reads content of a file but it's only for one file and the key can be set via code?

This is what I have in mind

`public static IConfigurationBuilder AddFileContent(this IConfigurationBuilder builder, string filePath, string key, bool optional, bool reloadOnChange)
`
I know the implementation is simple, but is this something that could be added in Microsoft.Extensions?

**Comment by maryamariyan** [comment]
Closing as of https://github.com/dotnet/runtime/issues/36501#issuecomment-597263705
