### ISSUE TITLE
Why don't installer projects import the root Directory.Build files and the Arcade SDK?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#36518]
Currently [installer test projects](https://github.com/dotnet/runtime/tree/master/src/installer/test/Assets/TestProjects) don't import any of the repositories centrally defined properties or targets files. There is a TestProjects.props file which imports eng/Versions.props instead. Going back in history I found the commit that created this file: https://github.com/dotnet/core-setup/pull/3350/commits/3aa233dbd06b542aa62453d1de341dfcc25e15a8#diff-fc1aafae5f3f3352e26bce20b8640132 which was in the 2.x timeframe.

I'm wondering if we can let the TestProjects import the Arcade SDK and our centrally defined properties and targets file as any other projects do. We are doing the same for our libraries test projects.

cc @NikolaMilosavljevic @dagood @ericstj @safern

**Comment by jkoritzinsky** [comment]
The installer test projects are testing various aspects of the host. I think the reason they don’t import the root files and Arcade is to ensure that they are correctly isolated. I know that they need to have their custom global.json to correctly test the host behavior.

These projects built as part of the test runs, not as part of the build.

**Comment by ViktorHofer** [comment]
Thanks for explaining. Closing.
