### ISSUE TITLE
API Proposal:System.IO.Pipelines.Pipe<T>

### ISSUE THREAD

**Issue by RamType-0** [dotnet/runtime#36516]
## Background and Motivation
I'm now trying on audio streaming processing with `System.IO.Pipelines.Pipe`.
When I streaming IEEEFloat audio,type of streaming elements is `float`,and when I streaming 16bitPCM,and also if I streaming stereo,each frames are provided as vector.
type of streaming elements is  `short` or `ushort`.
But `System.IO.Pipelines.Pipe` supports only `byte`.
`SequenceMarshal.TryRead` and `MemoryMarshal.Cast<TFrom,TTo>` help me very much,but it is still hard.(Because there is no function such as `SequenceMarshal.Cast<TFrom,TTo>`. Yes,I know, It is impossible.)

## Proposed API
```C#

public class Pipe<T>
{
   PipeWriter<T> Writer{get;}
   PipeReader<T> Reader{get;}
}
public abstract class PipeWriter<T> : IBufferWriter<T>{}
public abstract class PipeReader<T>{}

public class Pipe : Pipe<byte>{}
public abstract class PipeWriter : PipeWriter<byte>{}
public abstract class PipeReader : PipeReader<byte>{}

```

## Issues
`byte` is `unmanaged`,`IEquatable<byte>` type.What constrain are needed for `T`?
Or create variants such as `UnmanagedPipe<T>`?

**Comment by RamType-0** [comment]
Oh, it is a duplicate of #28556

**Comment by BrennanConroy** [comment]
Closing as dupe
