### ISSUE TITLE
Merge artifacts and CTS leak

### ISSUE THREAD

**Issue by berdon** [dotnet/runtime#36511]
### Describe the bug
- Merge artifacts in solution
- Possible CTS leak in ConfigurationReloadToken / ConfigurationRoot

### To Reproduce
- Compile
- Wait a while for memory accrual?

### Expected behavior
- Compile
- Dispose of the CTS in the rolling change tokens

### Screenshots
n/a

### Additional context
PR to follow

**Comment by maryamariyan** [comment]
Closing as per conversation in https://github.com/dotnet/extensions/pull/1462. We could revisit if still blocking.
