### ISSUE TITLE
"The 'libs' subset must be built before building this project" when subset has been built

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#36528]
### Description

Attempting to build+run tests on Debian on a git checkout by following documentation but the libs subset is not being picked up after building.

I've run the following successfully:
```
PATH=~/cmake/bin:$PATH ./build.sh -subset clr+libs -runtimeconfiguration Debug
PATH=~/cmake/bin:$PATH ./build.sh -subset clr+libs -runtimeconfiguration Release
```

But any time I do ```PATH=~/cmake/bin:$PATH ./src/coreclr/build-test.sh``` I get errors about the libs subset:

```
Starting the Managed Tests Build...
Building step 'Managed tests build (build tests)' testGroupToBuild=1 via "/home/kate/Projects/runtime/eng/common/msbuild.sh"  --warnAsError false /home/kate/Projects/runtime/src/coreclr/tests/build.proj /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount "/flp:Verbosity=normal;LogFile=/home/kate/Projects/runtime/artifacts/log/Tests_Managed.Linux.x64.Debug.log;Append=false" "/flp1:WarningsOnly;LogFile=/home/kate/Projects/runtime/artifacts/log/Tests_Managed.Linux.x64.Debug.wrn;Append=false" "/flp2:ErrorsOnly;LogFile=/home/kate/Projects/runtime/artifacts/log/Tests_Managed.Linux.x64.Debug.err;Append=false"  /p:TargetArchitecture=x64 /p:Configuration=Debug /p:TargetOS=Linux /nodeReuse:false     "/p:CopyNativeProjectBinaries=true" /p:__SkipPackageRestore=true
  Building Targeting Pack
  external -> 
/home/kate/Projects/runtime/eng/liveBuilds.targets(148,5): error : The 'libs' subset must be built before building this project. Missing artifacts: /home/kate/Projects/runtime/artifacts/bin/ref/microsoft.netcore.app/Release/ [/home/kate/Projects/runtime/src/coreclr/tests/src/Common/CoreCLRTestLibrary/CoreCLRTestLibrary.csproj]
/home/kate/Projects/runtime/eng/liveBuilds.targets(148,5): error : The 'libs' subset must be built before building this project. Missing artifacts: /home/kate/Projects/runtime/artifacts/bin/ref/microsoft.netcore.app/Release/ [/home/kate/Projects/runtime/src/coreclr/tests/src/CoreMangLib/system/environment/environment_version.csproj]
Attempting to cancel the build...

Build FAILED.
```

After messing around for a bit it seems like the solution is:

```
PATH=~/cmake/bin:$PATH ./build.sh -subset clr+libs -runtimeconfiguration Release -c Release
```

Because that got me past the 'subset must be built' error. But I didn't find this anywhere in the documentation on how to build so it seems like it shouldn't necessarily be required (or the docs are just outdated).

### Configuration

Debian Buster (10), Intel x64
git commit 7debfe4b605a743b61eced52970563b59a4967ea

**Comment by ViktorHofer** [comment]
Based on the path in the error message I would say you need to build the libs subset in Release. We should probably refine the error message to include the required configuration.

```
PATH=~/cmake/bin:$PATH ./build.sh -subset clr+libs -runtimeconfiguration Debug -c Release
```

or if you want to build everything in Release:

```
PATH=~/cmake/bin:$PATH ./build.sh -subset clr+libs -c Release
```

**Comment by kg** [comment]
OK, that was the answer I arrived at. The docs should probably specify this since as-is none of the instructions for how to build the tests actually work - i.e. https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/linux-instructions.md which doesn't ever mention needing to explicitly build in release configuration. Some of the other docs I looked at didn't mention this either.

**Comment by ViktorHofer** [comment]
cc @jashook @trylek
