### ISSUE TITLE
Managed API for Editing EnhancedKeyUsage on X509Certificate

### ISSUE THREAD

**Issue by colathro** [dotnet/runtime#36535]
## Background and Motivation

Our team has run into an issue where we need to adjust the Enhanced Key Usages programmatically after the cert has been added to a root store. Upon adding the certificate to the root store it's key usages are reset and we need to enable Server Authentication. Right now we'll doing this directly calling unmanaged Wincrypt CertSetCertificateContextProperty.

## Proposed API

I'm unsure of exactly how the public interface will look; but it seems like it would fit in the existing retrieval; but on an edit open of the certificate store here:

[https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509enhancedkeyusageextension?view=netcore-3.1](url)

So a setter on: [https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509enhancedkeyusageextension.enhancedkeyusages?view=netcore-3.1](url)

## Usage Examples

Ideally, with edit access to the store, we'd be able to replace the existing EnhancedKeyUsages with a new System.Security.Cryptography.OidCollection containing the desired usages.

I'm unsure if editing KeyUsages can be supported in the Unix and OSX PALs, or where the stance is on a windows only setter if that's the case.

## Risks

I'm unsure exactly why this wasn't already implemented; but I thought there may be something risky with editing these properties that I'm unaware of.

**Comment by colathro** [comment]
I should note, I'd be looking at doing the implementation here.

**Comment by vcsjones** [comment]
What would be the behavior of this API on other platforms, macOS and Linux?

* As far as I know, Linux / OpenSSL has no concept of having EKUs outside of what the certificate specify it for.
* macOS has Trust Policies for certificates, but I don't think that is a 1:1 for the functionality that Windows offers.

**Comment by zentavious** [comment]
Can we limit this behavior only to Windows?

**Comment by bartonjs** [comment]
This isn't about manipulating certificates, it's about manipulating property data within the Windows Certificate Store (exporting the cert and re-importing it won't show the modifications, and (IIRC) the property overrides don't affect the data that gets reported via cert.Extensions).

I don't think this makes sense to add to the platform.

**Comment by vcsjones** [comment]
> property overrides don't affect the data that gets reported via cert.Extensions

Right; extensions / EKU are part of a cert's TBS... you couldn't change them without invalidating the signature.

**Comment by colathro** [comment]
I think due to this being property data within the store (thus adjustments not reflected on reimport), it becomes more useful to have a programmatic way to adjust these.

Windows itself allows these to be adjusted via UI, and in our specific use-case the adjusted certificate information works as expected.

I believe the adjustments to the certificate context is different from adjusting the actual cert:
[https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certsetenhancedkeyusage](url)

VERSUS

[https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certsetcertificatecontextproperty](url)

**Comment by bartonjs** [comment]
>I think due to this being property data within the store (thus adjustments not reflected on reimport), it becomes more useful to have a programmatic way to adjust these.

I'm not disagreeing with the value of programmatic access, but I don't think it fits in cleanly with anything provided in the box... it's better as a NuGet package (only applies to Windows, only applies to certificates that are registered to a store, ...).

> Can we limit this behavior only to Windows?

We are very hesitant to add anything in the box that doesn't make sense on all platforms these days.  The fact that this was even suggested is why I think it's best left to a NuGet package.

**Comment by bartonjs** [comment]
(I didn't actually mean to hit close, but I don't think there's going to be a convincing argument to add it, so I'll just let the close stand)
