### ISSUE TITLE
Will there be GetEnumerator() for MemoryCache ?

### ISSUE THREAD

**Issue by ardpx** [dotnet/runtime#36554]
**LINK to the proposal**: https://github.com/dotnet/runtime/issues/36554#issuecomment-1818437941

Just wonder if there would be GetEnumerator() for MemoryCache, as supported in System.Runtime.Caching.Memorycache?

**Comment by Naidile-P-N** [comment]
I want to monitor the memory usage, space consumed by each key in the cache created within the application.
Is there any other way to evaluate this?

**Comment by patchu** [comment]
I want to echo similar comments above. I'm migrating from the old HTTPContext cache which did have an enumerator in it. I have sets of keys that all start with a specific string that I want to delete. Yes, I COULD keep a list of keys in my own array, but then I'd be writing additional code to maintain information that already exists in the cache. For Javascript objects, this is simply cache.keys(). Why not something simple like that?

**Comment by kwacks** [comment]
Not sure why this basic scenario isn't supported - most modern cache providers support enumerating keys - one core scenario like many others pointed out is the ability to delete keys with a certain prefix. Necessary if you're maintaining IMemoryCache as a singleton and want to avoid deleting all items in the cache at once. 
Is there any plan to support this?

**Comment by udlose** [comment]
Tracking cache keys myself is at best a hacky and dangerous solution.  If the `StackExchange.Redis` implementation can do this for a **Distributed Cache** (which it does quite well), there is no reason you couldn't take a read-only snapshot and return that to the caller.  Of course, the caveat is known that the list could change after the snapshot is taken.

**Comment by adamsitnik** [comment]
I was performing an audit of `Microsoft.Extensions.Caching.Memory` today and realized that this is one of the most up-voted feature requests.

First of all, same as for `Clear` we can't extend `IMemoryCache` as it would be a breaking change (https://github.com/dotnet/runtime/issues/45593#issuecomment-900541842). So our focus should be on the concrete implementation: `MemoryCache`.

`MemoryCache` is more or less a wrapper around `ConcurrentDictionary`, so:
- implementing the enumeration should be simple (https://github.com/dotnet/runtime/commit/fad4c91a4f770952d74a554504582d226fb182a6).
- implementing a performant and thread-safe bulk remove based on a condition is not possible as `ConcurrentDictionary` itself does not support it. I would prefer not to expose a non-performant version, as it would be performance pit of failure the the end users.

When it comes to the enumeration, we have two options: make `MemoryCache` implement `IEnumerable` or implement `GetEnumerator` that returns `struct` that implements the pattern (this is a duck typing recognized by C# compiler).

The disadvantage of the first approach is the clutter IDE gives me for everything that implements `IEnumerable`:

![image](https://github.com/dotnet/runtime/assets/6011991/2e98cfbd-b174-438c-8c4d-add73a55b07d)


The disadvantage of the latter approach is lack of good discoverability.

@bartonjs @stephentoub Which approach would you recommend?

**Comment by stephentoub** [comment]
> The disadvantage of the first approach is the clutter IDE gives me for everything that implements IEnumerable

Those glyphs at the bottom of the IntelliSense popup allow you to filter out extension methods if you don't want to see them.

> The disadvantage of the latter approach is lack of good discoverability.

The bigger disadvantage is it means you can't use LINQ (or, at least, to use LINQ you need to play tricks like writing your own iterator and then using LINQ over that).  I assume that's something folks would like to be able to do.

> Which approach would you recommend?

If we want to address this issue, I'd want to see it implement the interface.  It could do so explicitly rather than implicitly and then you could also have a GetEnumerator that returns a struct if there were allocation concerns; then foreach'ing over it directly wouldn't allocate but you'd still be able to use extension methods on IEnumerable, and they'd use whatever explicit GetEnumerator implementation was provided with whatever object it wants to return.

**Comment by bartonjs** [comment]
I can't think of any places where we've done (2) without also doing (1), off the top of my head.

One way to get fairly close is to add something like `public IEnumerable<???> EnumerateItems()`.  So it'll enable `cache.EnumerateItems().Where(entry.Key.StartsWith(somePrefix)).[...]` without "polluting" the object itself.  Typing more words might also convey "this isn't necessarily the best of approaches", vs collection types where enumeration is more expected.

**Comment by adamsitnik** [comment]
## Background and Motivation

`MemoryCache` gives the possibility to add and remove values for given keys, but it does not expose a possibility to read keys added to the cache.

Many (more than twenty by looking at the number of reactions) of our customers have expressed the need of this API in #36554.

So far most of them were forced to use ugly workarounds like creating a wrapper around `MemoryCache` that would be also storing their own collection of keys added to the cache.

## Proposed API

Expose a collection of `ICollection<object> Keys`, with the same behavior as `ConcurrentDictionary.Keys`: a snapshot.

```diff
namespace Microsoft.Extensions.Caching.Memory
{
    public class MemoryCache
    {
+       public ICollection<object> Keys { get; } // Gets a snapshot containing all the keys in the cache.
    }
```

## Usage Examples

```cs
MemoryCache cache = new(new MemoryCacheOptions());

cache.Set("key1", "value1");
cache.Set("key2", "value2");

foreach (object key in cache.Keys)
{
    if (key is string text && text.StartsWith("key"))
    {
        cache.Remove(key);
    }
}
```

### Alternative Designs

Extending `MemoryCache` with `IEnumerable<KeyValuePair<object, ICacheEntry>>` implementation was considered, but:
- it would expose more information that the users have asked for (not just keys, but also values). It would be a first API that would allow to mutate cache entries (values) after adding them to the cache, which is not supported and can lead into issues like #88733.
- it would clutter the IDE with all LINQ extensions

![image](https://github.com/dotnet/runtime/assets/6011991/930576f4-8028-4a3e-a019-3a66488a0145)

## Risks

This proposal avoids a risk of breaking change, by not extending the `IMemoryCache` interface.

However, our users may not understand the concept of a snapshot and:
- assume that the content of `Keys` read once from `MemoryCache` is always in sync with the cache.
- assume that no copy is being made until the `Keys` are enumerated for the first time.

But this has not stopped us from adding this API to `ConcurrentDictionary` and I hope it's also not going to stop us this time.

**Comment by stephentoub** [comment]
> But this has not stopped us from adding this API to ConcurrentDictionary and I hope it's also not going to stop us this time.

ConcurrentDictionary implements IDictionary, so it had to have Keys (at least explicitly).

And from my perspective we made a mistake giving it the semantics we did. Didn't you storms a bunch of time reducing overheads in MemoryCache? And now we'd be implementing a property with O(N) allocation on every property read?

**Comment by adamsitnik** [comment]
@stephentoub What other options do we have considering that:
- users want to iterate over it to find keys that they want to remove (having a copy helps here)
- `MemoryCache` is a wrapper around `ConcurrentDictionary` and it can use only `public` method/properties

**Comment by stephentoub** [comment]
> What other options do we have

```C#
public IEnumerable<object> GetKeys()
{
    foreach (KeyValuePair<object, CacheEntry> pairs in _dictionary)
    {
        yield return pairs.Key;
    }
}
```
?

**Comment by adamsitnik** [comment]
@stephentoub I've given it a try in https://github.com/dotnet/runtime/pull/94992/commits/42751808d8a9b63a0485bd2eb05730b24daf46ac and updated the proposal (I was unaware of the fact it's possible to enumerate over concurrent dictionary and modify it at the same time). Thanks, it was great idea!

**Comment by bartonjs** [comment]
* During review there was a question of whether it should be `IEnumerable<object>` or should use a custom struct-based enumerator-pattern type; but the answer to that depends on usage data we don't have, so it's a question for the area owners.

```C#
namespace Microsoft.Extensions.Caching.Memory
{
    public partial class MemoryCache
    {
       public IEnumerable<object> Keys { get; }
    }
}
```

**Comment by thompson-tomo** [comment]
@adamsitnik I am attempting to implement an actuator to provide info about the cache/clear it as per how spring boot does it (https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#caches) and i would propose we make a change to the data model being returned to provide additional metadata and this is the best time to do it before it is released. I have created a proposal #98251 to cover this for the memory cache option could you take a look.

Note we should be able to address the breaking change aspect by providing a default implementation.
