### ISSUE TITLE
Refine the memory pressure expiration algorithm

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#36558]
When the cache is removing items due to memory pressure it currently considers:
1. Expired
2. Priority
3. LRU

Also consider:
- TTL - How long does this item have to live before time based expiration? Sliding vs Absolute.
- Estimated object (graph) size
- Others?

**Comment by maryamariyan** [comment]
Closing as it's been 6 years since the issue opened with no discussion.
