### ISSUE TITLE
Add a TryGetOrCreate or other mechanism for safely indicating value isn't ready yet

### ISSUE THREAD

**Issue by mungojam** [dotnet/runtime#36553]
I'm using IMemoryCache in asp.net core.

I would like to be able to retrieve a value via the cache, but allow for the possibility that the value isn't able to be retrieved yet so should not be added to the cache at this point. 

If it doesn't exist yet then it could be either because it just hasn't been requested yet (i.e. Create is fine), or because it isn't ready yet in which case I want to abort the GetOrCreate without risking other consumers picking up a null or dummy value.

What I've ended up doing so far is throwing a custom exception from the Create method and then catching that when calling GetOrCreate. It works, but doesn't feel good.

What I am currently doing:
```C#
try
{
    return await Cache.GetOrCreateAsync(id, GetResultToReturn);
}
catch (NoResultException)
{
    //let consumer know that it's not ready yet, try again later
    return await Task.FromResult((NicelyFormatted)null);
}

async Task<NicelyFormatted> GetResultToReturn(ICacheEntry entry)
{
    var dbResult = await DbService.GetResultAsync(id);

    if (dbResult == null)
    {
        //result isn't ready yet but it might be next time
	throw new NoResultException();
    }

    return await Task.Run(() =>DoSomethingLongWithResult(dbResult);
}
```

What I'd like to be able to do, something like this:
```C#

if (!await Cache.TryGetOrCreateAsync(id, GetResultToReturn, out var result)){
    return null;
}

return result;

async Task<NicelyFormatted> GetResultToReturn(ICacheEntry entry, out bool hasValue)
{
    var dbResult = await DbService.GetResultAsync(id);

    if (dbResult == null)
    {
        //result isn't ready yet but it might be next time
        hasValue = false;
	return null;
    }

    hasValue = true;
    var result = await Task.Run(() =>DoSomethingLongWithResult(dbResult);
    return result;
}
```

**Comment by adamsitnik** [comment]
From my understanding, both `IMemoryCache` and `MemoryCache` already provide a method for that: `bool TryGetValue(object key, out object? value)`. The method simply returns false if given key has no value present in the cache.

https://learn.microsoft.com/dotnet/api/microsoft.extensions.caching.memory.memorycache.trygetvalue

**Comment by mungojam** [comment]
What I was asking for is more like TryAddValue, not TryGetValue, a safe way to abort adding something to the cache

**Comment by adamsitnik** [comment]
Please excuse me, but I still don't understand.

Currently we have following methods:
- `TryGetValue` - returns `true` and the value when it's found, `false` otherwise
- `GetOrCreate` - returns value when it's found, if it's not then it creates the entry, adds it to the cache and returns value
- `Remove` - tries to remove item for given key, does nothing when it's not found

@mungojam What would be the behavior of the new method?

**Comment by mungojam** [comment]
TryGetOrCreate would be like getorcreate but would provide an escape hatch if a value couldn't be created yet, perhaps if it takes a long time to create and that is being processed already. It might be if the cache consumer just wants to return a 202.

So by invoking the escape hatch it's saying I can't give you a value at the moment but try again whenever you want, i.e. don't cache this failure result

**Comment by adamsitnik** [comment]
@mungojam So in case the factory method returns `null`, the value should not be added to the cache?

```cs
static async Task<TValue?> TryGetOrAddWhenNotNullAsync<TValue>(this MemoryCache cache, object key, Func<Task<TValue>> factory)
{
    if (cache.TryGetValue(key, out var cachedValue) && cachedValue is not null)
    {
        return (TValue)cachedValue;
    }

    TValue? value = await factory();
    if (value is not null)
    {
        cache.Set(key, value);
    }
    return value;
}
```

**Comment by mungojam** [comment]
> @mungojam So in case the factory method returns `null`, the value should not be added to the cache?
> 
> ```cs
> static async Task<TValue?> TryGetOrAddWhenNotNullAsync<TValue>(this MemoryCache cache, object key, Func<Task<TValue>> factory)
> {
>     if (cache.TryGetValue(key, out var cachedValue) && cachedValue is not null)
>     {
>         return (TValue)cachedValue;
>     }
> 
>     TValue? value = await factory();
>     if (value is not null)
>     {
>         cache.Set(key, value);
>     }
>     return value;
> }
> ```

I'm not sure that using `null` would be enough as a general approach since you might want to have `null` as a valid cached value
