### ISSUE TITLE
Need more Get function in the Cache class

### ISSUE THREAD

**Issue by PrimeObjects** [dotnet/runtime#36559]
Hi,

In session class, we have Get, GetInt32, GetString functions.
Can I suggest we also do it to Cache Class to make the design consistent?

Thanks
Gary

**Comment by adamsitnik** [comment]
We are not planning to add any `Get$TypeName` methods to existing `MemoryCache`, but we may add a new generic `MemoryCache<TKey, TValue>`. Please follow https://github.com/dotnet/runtime/issues/48567 for updates.
