### ISSUE TITLE
Revisit MemoryCache design

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/runtime#36556]
The current design of MemoryCache is awkward due to the IMemoryCache interface where `ICacheEntry CreateEntry(object key)` exists instead of a more intuitive `Set(object key, object value)`. The expected usage pattern is to call `Dispose()` on the `ICacheEntry` to "commit" the entry to the cache but this is unintuitive as well. This proved to be an issue when attempting to implement a strategy based eviction trigger and strategy in https://github.com/aspnet/Caching/pull/280. We should revisit this design and see if there are possible improvements.

cc @davidfowl @DamianEdwards

**Comment by anurse** [comment]
The fact that you have to `CreateEntry` and then `Dispose` the returned value to add it to the cache has been very non-intuitive to users. It'd be nice to take a look at a better API here.

**Comment by maryamariyan** [comment]
@JunTaoLuo is this still needed? (Referring to https://github.com/aspnet/Caching/pull/280#issuecomment-288829165)

Also since we have a Set extension method here:

https://github.com/dotnet/runtime/blob/855e2961ba70d3ed8b094d230aaf655adac2b76e/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/MemoryCacheExtensions.cs#L44-L50

**Comment by JunTaoLuo** [comment]
The point of the issue is that the pattern of using `CreateEntry` and then calling `Dispose` to add the entry to the cache is unintuitive. We do have more convenient helpers like `Set` so that most people don't need to directly use that pattern when interacting with a cache. However, the underlying issue of the unintuitive API remains. That said, given that there hasn't been much traffic on this issue, maybe it's not a problem for most users, in which case we can either backlog or close this issue.

**Comment by adamsitnik** [comment]
The current design is far from perfect. I agree that we need a re-design. Pplease follow #48567 which includes your proposal and some other good ideas. Thank you!
