### ISSUE TITLE
Can't use Environment.GetCommandLineArgs() for ConfigurationBuilder.AddCommandLine(...)

### ISSUE THREAD

**Issue by ChadJessup** [dotnet/runtime#36566]
Can't use the results from Environment.GetCommandLineArgs() as a parameter to the ConfigurationBuilder's .AddCommandLine extension method.

```
An exception of type 'System.FormatException' occurred in Microsoft.Extensions.Configuration.CommandLine.dll but was not handled in user code

Additional information: Unrecognized argument format: 'C:\<path to running code>.dll'.
```

The first command line element in the string array provided by `Environment.GetCommandLineArgs()` is the path to the executable, which cannot be parsed.
`Environment.GetCommandLineArgs().Skip(1).ToArray()` is a messy work around.

I feel that this is something that should _just work_ since Microsoft owns both of these pieces. The underlying problem is that the `.AddCommandLine()` method can't parse anything outside of a very particular format, that is `--howdy` also throws an exception.

The expected functionality is that unknown arguments are either ignored, or these exceptions can be disabled, since the command line arguments aren't controllable to the program, and often used for configuration of multiple aspects of a program.

**Comment by maryamariyan** [comment]
Closing this issue since a workaround is provided. We could reopen if there is more asks on this in the future.
