### ISSUE TITLE
LoggerMessage.Define throws error when no template string 

### ISSUE THREAD

**Issue by chassq** [dotnet/runtime#36565]
Calling AppLogException, in the code below, throws a null ref exception when the define string template is set to null. Maybe consider giving Define an overload where no template string could be provided or use the name of the LogLevel Enum by default?

**Repro code:**
```c#
    class Program
    {
        static void Main(string[] args)
        {
            using var loggerFactory = LoggerFactory.Create(builder =>
            {
                builder.AddConsole();
            });
            var logger = loggerFactory.CreateLogger("logger");
            var exceptionToLog = new NotImplementedException("NIE");
            logger.Log(LogLevel.Warning, exceptionToLog, "message for warning");
            AppLoggerExtensions.AppLogException(logger, exceptionToLog);
        }
    }

    public static class AppLoggerExtensions
    {
        private static readonly Action<ILogger, Exception> _appLogException = LoggerMessage.Define(
            LogLevel.Error,
            new EventId(1, nameof(AppLogException)),
            formatString: null); // causing NRE

        public static void AppLogException(this ILogger logger, Exception ex)
        {
            _appLogException(logger, ex);
        }
    }
```

**Comment by maryamariyan** [comment]
Rather than a `NullReferenceException`, [LoggerMessage.Define](https://apisof.net/catalog/Microsoft.Extensions.Logging.LoggerMessage.Define%3CT1%3E(LogLevel,EventId,String)) or  [LoggerMessage.Define](https://apisof.net/catalog/Microsoft.Extensions.Logging.LoggerMessage.DefineScope%3CT1%3E(String)) and their overloads, should throw with an `ArgumentNullException` given a null formatString.

**Comment by danmosemsft** [comment]
'first time contributor' is meant to indicate the PR/issue was the community member's first one in this repo. (The fabricbot is supposed to set it.) maybe it needs a better name..

**Comment by eugene-shcherbo** [comment]
Hi, can I take this as my first time contribution?

**Comment by maryamariyan** [comment]
> Hi, can I take this as my first time contribution?

@eugene-shcherbo sure thing. Go ahead and in fact you can pick from any of the open up-for-grabs issues.
