### ISSUE TITLE
Support GetFileInfo for directories

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/runtime#36575]
_From @stilettk on Friday, November 3, 2017 2:56:28 AM_

Currently `GetFileInfo` supports only files: when called on a path that points to a directory it returns `PhysicalFileInfo` which has `IsDirectory == false`. 

So, when given a path, how to decide what to do: to call `GetFileInfo` (if it's a file) or call `GetDirectoryContents` (if it's a folder)? Currently the only way I found isn't very intuitive:
`bool isDirectory = fileProvider.GetDirectoryContents(myPath).Exists`

My suggestion:
`new PhysicalFileProvider(myPath).GetFileInfo("data")` 
Expected:
`PhysicalDirectoryInfo`
Actual:
`PhysicalFileInfo`

_Copied from original issue: aspnet/FileSystem#298_

**Comment by tillig** [comment]
Related: #36496
This was definitely a confusing situation when trying to figure out if a directory exists.

**Comment by amcasey** [comment]
Just ran into this again.  However, I'm already off the paved path because I'm trying to `ResolveLinkTarget` which isn't exposed anyway.  In a way, I'm more confused that `FileInfo` will let you construct an instance for a directory and then just report that it doesn't exist.
