### ISSUE TITLE
Setting key must match property exactly, preventing use of some json styles

### ISSUE THREAD

**Issue by dodexahedron** [dotnet/runtime#36573]
### Functional impact
Due to the fact that, on [line 172 of ConfigurationBinder.cs](https://github.com/aspnet/Configuration/blob/2d68e24422f8bf5e9d23be8178cd66f8cea62094/src/Config.Binder/ConfigurationBinder.cs#L172), the reflected property name is used for matching properties to JSON dictionary keys, it is not possible to consume many legal JSON properties in a configuration file.

This is a problem when attempting to load files that follow a style that includes dashes or other characters that are illegal in identifiers, in C#, VB.Net, and other languages.

For example, a JSON property such as "multi-word-key": "some value" cannot be assigned to any object value and must be accessed via the configuration object's indexer, which is cumbersome and not compile-time type safe (thus static analysis is impossible).

### Minimal repro steps
The following C# code and JSON file will demonstrate the problem.

C# Code:
```C#
namespace ExampleCase
{
    using System;
    using System.Runtime.Serialization;
    using Microsoft.Extensions.Configuration;

    [DataContract]
    public class MySettings
    {
        [DataMember( Name = "multi-word-setting" )]
        public string MultiWordSetting { get; set; }
    }

    public class ExampleCase
    {
        public static void Main( string[ ] args )
        {
            IConfigurationBuilder configBuilder = new ConfigurationBuilder( ).AddJsonFile( "settings.json" );
            IConfigurationRoot configRoot = configBuilder.Build( );
            MySettings config = new MySettings(  );
            configRoot.Bind( config );

            Console.WriteLine( configRoot[ "multi-word-setting" ] ); //This will output the expected value
            Console.WriteLine( config.MultiWordSetting ); //However, this will be null
        }
    }
}
```

JSON File `settings.json`:
```JSON
{
    "multi-word-setting": "some string"
}
```

### Expected result
The `config.MultiWordSetting` property should have the value specified by its associated JSON, as specified by the DataMemberAttribute.
Ideally, there would be a specific attribute created for exactly this case (e.g. `ConfigurationElementAttribute`), as well as support for respecting other common attributes, such as DataMemberAttribute.

### Actual result
The property is not set, because the mentioned line of code in the binder relies on the explicit matching of the property's name to the json key.

**Comment by safern** [comment]
Thanks @dodexahedron for the proposal. I'm closing this as a dupe of: https://github.com/dotnet/runtime/issues/36010 which has a formal proposal for this.
