### ISSUE TITLE
ILAsm/ILDasm roundtrip tests not running

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#36599]
While working with framework ILAsm and ILDasm we noticed that an assembly didn't roundtrip. There was an assembly that ildasm disassembled as having a `ldc.r4 -nan(inf)` instruction. As this is not valid IL, ILAsm failed to roundtrip the assembly.

I can't say if this happens right now with the Core ILDasm, but talking to @jashook it seems that we might have lost the assembly roundtrip tests in the migration to azure devops.

**Comment by AaronRobinsonMSFT** [comment]
See the customer reported issue in https://github.com/dotnet/runtime/issues/37210.

**Comment by BruceForstall** [comment]
@hoyosjs Do you have a repro case that could be tried on Core?

**Comment by BruceForstall** [comment]
@briansull The customer case was a regression from .NET Framework 4.6.1 => .NET Framework 4.8. Do you know of any ildasm changes in that time frame that might be relevant?

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall The repo is simple actually. Create any C# assembly that uses `float.NaN` or `double.NaN`, build, and disassemble with ILDAsm. Observe the `ldc.r4 -nan(inf)` for `float` or `ldc.r8 -nan(inf)` for `double`. When using the ILAsm tool to reassemble the tool will fail on `-nan(inf)`.

**Comment by AaronRobinsonMSFT** [comment]
The following should be enough.

```CSharp
public class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine($"{float.NaN}");
    }
}
```

**Comment by jkotas** [comment]
.NET Core version of ilasm/ildasm roundtrips NaNs just fine. We should use this issue to add back the roundtrip testing.

Note that we are not really shipping ilasm/ildasm in .NET Core today (#13823 and #32996), so  ilasm/ildasm roundtrip testing is nice-to-have in the current situation. It would become must-have if we started shipping these tools.

**Comment by BruceForstall** [comment]
ilasm round-trip testing added with https://github.com/dotnet/runtime/pull/38490
