### ISSUE TITLE
Inefficient codegen when trying to abstract endianness differences with StructLayout.Explicit.

### ISSUE THREAD

**Issue by GoldenCrystal** [dotnet/runtime#36592]
### Description

I'm investigating how to map a structure with explicit field layout and overlapping fields, while supporting both little endian & big endian hosts.
Basically, I'd like to somehow have two definitions of the structure, chosen dynamically at runtime, without any performance overhead.
 
I'm hitting what I think are (x64) JIT codegen issues, some of them you are probably already aware of.

### Configuration

Using SharpLab to inspect generated x64 assembly on .NET Core:
`; Core CLR v4.700.20.6603 (coreclr.dll) on amd64.`

### Regression?

I don't think so / don't know

### How to reproduce the problem

For this repro case, assume I want to create a structure that represents the registers of a very simple CPU. This CPU has a single 16 bit register  `HL` composed of two 8 bit registers `H` & `L` such that `HL = H << 8 | L`. (NB: Endianness of this CPU doesn't matter here.)

There are various ways to write endianness independant code, but I'd like to find one that is straightforward, the safest possible, and produces "efficient" assembly. (At least as efficient than code assuming only little endian)

#### The reference "good" codegen

My reference layout for registers will be as follows:
````csharp
[StructLayout(LayoutKind.Explicit)]
public struct RegistersLittleEndian
{
    [FieldOffset(0)]
    public ushort HL;
    
    [FieldOffset(1)]
    public byte H;
    [FieldOffset(0)]
    public byte L;
}
````

I'll be using the following code to compare different codegens:
````csharp
public class CpuLe
{
    private RegistersLittleEndian _registers;
    
    public int DoSomething()
        => _registers.H < 16 ? _registers.HL : _registers.L == 0 ? _registers.H + _registers.L : _registers.H;
}
````

If I look at the assembly generated using SharpLab, I get the following:
````assembly
CpuLe.DoSomething()
    L0000: movzx eax, byte [rcx+0x9]
    L0004: cmp eax, 0x10
    L0007: jl L0015
    L0009: movzx ecx, byte [rcx+0x8]
    L000d: test ecx, ecx
    L000f: jz L0012
    L0011: ret
    L0012: add eax, ecx
    L0014: ret
    L0015: movzx eax, word [rcx+0x8]
    L0019: ret
````

This seems quite good to me, but that was generated with a structure that is only ever valid for Little Endian machines.

Now, I can easily make a similar structure for BigEndian architectures and have things work there too:
````csharp
[StructLayout(LayoutKind.Explicit)]
public struct RegistersBigEndian
{
    [FieldOffset(0)]
    public ushort HL;
    
    [FieldOffset(0)]
    public byte H;
    [FieldOffset(1)]
    public byte L;
}
````

However, I need a mechanism to switch between implementations at runtime, which would hopefully be optimized by the JIT. Seems like a job for `BitConverter.IsLittleEndian`.

#### The bad codegen when trying to implement a conditional layout

I tried the following structure:
````csharp
[StructLayout(LayoutKind.Explicit)]
public struct RegistersTernary
{
    [FieldOffset(0)]
    public ushort HL;
    
    [FieldOffset(0)]
    private RegistersLittleEndian _littleEndian;
    [FieldOffset(0)]
    private RegistersBigEndian _bigEndian;
    
    public byte H => BitConverter.IsLittleEndian ? _littleEndian.H : _bigEndian.H;
    public byte L => BitConverter.IsLittleEndian ? _littleEndian.L : _bigEndian.L;
}
````
(NB: For the sake of keeping this already long issue the smallest possible, I'm omitting the setters, but assume I'd want them in the real world)

This however, generates inefficient assembly, compared to the optimal case above:
````assembly
CpuTernary.DoSomething()
    L0000: cmp [rcx], ecx
    L0002: lea rdx, [rcx+0x8]
    L0006: mov rax, rdx
    L0009: movzx eax, byte [rax+0x1]
    L000d: cmp eax, 0x10
    L0010: jl L0031
    L0012: mov rax, rdx
    L0015: movzx eax, byte [rax]
    L0018: test eax, eax
    L001a: jz L0021
    L001c: movzx eax, byte [rdx+0x1]
    L0020: ret
    L0021: mov rax, rdx
    L0024: movzx eax, byte [rax+0x1]
    L0028: mov rcx, rdx
    L002b: movzx edx, byte [rcx]
    L002e: add eax, edx
    L0030: ret
    L0031: movzx eax, word [rcx+0x8]
    L0035: ret
````
 
The other variant i've tried uses a helper to choose between endianness and interestingly produces slightly smaller assembly code:

````csharp
static class Helper
{
    // Pick "le" or "be" depending on platform endianness.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ref byte Pick(ref byte le, ref byte be)
        => ref BitConverter.IsLittleEndian ? ref le : ref be;
}
````

````assembly
CpuPick.DoSomething()
    L0000: lea rdx, [rcx+0x8]
    L0004: mov rax, rdx
    L0007: cmp [rax], eax
    L0009: inc rax
    L000c: mov r8, rax
    L000f: cmp byte [r8], 0x10
    L0013: jb L002a
    L0015: mov rcx, rdx
    L0018: cmp byte [rcx], 0x0
    L001b: jz L0021
    L001d: movzx eax, byte [rax]
    L0020: ret
    L0021: movzx eax, byte [rax]
    L0024: movzx edx, byte [rdx]
    L0027: add eax, edx
    L0029: ret
    L002a: movzx eax, word [rcx+0x8]
    L002e: ret
````

I've tried various other implementations without success (see the link to SharpLab at the end). As it seems, the more "clever" the code, the larger the generated assembly… 🙁

#### Naive analysis

From what I see, the assembly generated in the simple case of ternary operator with `BitConverter.IsLittleEndian`, the assembly generated for the property getters is optimal:
````assembly
RegistersTernary.get_H()
    L0000: movzx eax, byte [rcx+0x1]
    L0004: ret

RegistersTernary.get_L()
    L0000: movzx eax, byte [rcx]
    L0003: ret
````
As such, I'm guessing the problems arise when they are inlined in the `DoSomething` method.

In the case of the `Pick` helper, the assembly emitted for the property getters include useless instructions, instead of being simplified to the same assembly code as in the ternary case:
````assembly
RegistersPick.get_H()
    L0000: cmp [rcx], ecx ; Useless comparison ?
    L0002: inc rcx ; Could be moved into the following instruction as [rcx + 0x1]
    L0005: movzx eax, byte [rcx]
    L0008: ret

RegistersPick.get_L()
    L0000: mov rax, rcx ; Useless mov, the following instruction could use ecx directly.
    L0003: cmp [rax], eax ; Useless comparison ?
    L0005: movzx eax, byte [rcx]
    L0008: ret
````
Despite this, it still produces slightly smaller assembly than the ternary case when inlined.

#### Conclusion

Could the codegen be improved in some way that would make at least one implementation produce the optimal assembly code?
Or do you know of an alternative way to solve this problem, that I could have missed?

### Other information

[SharpLab with all the repro cases](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6mpvJImpBgAkYksTJoBvGg18MA9P4MAArKANYMAETSkQzQUcAwsQAmMO5cybxcAOZxXAxiktgYAGbQ+AwwGbzYXFyquCw+fgDaALIwGAAWEMkG4pIAFB3dvf2FAPJifBBcjQCC2dmwuLi8CjBGkllZ2QCUALrNvsQAzNr2sCUMwACeGDAh4YNXN/eP0mgMr3cPNzB7Y5+XwAXgAfN8YNcAEK8DAiLgbKAPKAsAy4AAycIw0gAotVagwAPyQ67SBggUn/DTUAC+NmogQYABUoLddgwMBAbhwpMkGNgGLgMFAOGAMBxYAxIDxsDscpyuo9YNleMKZLg4tdBUJggBVBhlKCVfAcIozfKzAVcW6c7BQbKdBj4bBgLpZQQMlqyEVijAY7C3CAcDCDANBkMAaSyyRYuIQhWUcMOmnOwtF4oYbBgqvVUEx2LxBK4XiBLQAYrxXMkJiUSrhOoM6CnqMCzgwOLgesjnBiacCy5Xq7X643yC22+dfo8nP3WkPJDW6w3Q82jq2/O3pww+zR6dQaN7feLw8HQ6eozG4wntmBk+v2+m/Vmc2qUbhYdl8ZlaqWN74KyrRcRxXJsJ03c5O27DBeznXxByApdR1XcCTind5nDghhAOHZcx1Qph0L+Xc6S9H0M39QMzzDKjLwya9EzvDAW0fY8YOzXN32ZGQuHtW4/2BHDgLwlD10nDsu2gGCnBIgd/2whckNAtcgTEKB1mKR4OLfDUsQwHEYG/Gp8gAfW2fSix/LgsKEpTGxU+S1I0v5tLzD9eC/YsGBM4APKM2osKBLcMKcBhwQYWF4VmJEUTRAsLMMrySTMwtEqslhQspHy/OLDKsOC4iwohSKERimQ4r0gz/PyZLzKq3KMQpbzfM89KSP3Q9yL9C9z1ojBo3o+NGPvVMhTYl9OI1UIwDCAT50QkD7II9soKk2CgQQ3DkLAsS/CchRNImnT80qyzjO8uqzoCzbhO2hzgX2w7XPfT9quanKrMC+SCpnIrnFcdxUWmsIXihC7UuqjKvlebLWuMjK9nyojHka8KXDccrgdB64UoSyGMWhsHYfxxG9zItiepoiN+qvIbbxG2g03G56NXLc0HnqZJuKgXi2TmgDFMW0SgsgySexkr7BMFkSdtU9SDr+bcTLoGzpe28ddt8R7FYwkzyEliC3j+ULwpK6KZFi9FTrS87kvIJrlaRo2Ub+s3EQt8qrYhpLvMYLL9bJg9qCPCjKZ6gbYzppNmIfJmKKOty2eKDmYGSYH+YUhaZfuw3VvF2S/Buuzhcc+XDqVlWi6FwYNbl5zHiVgP5JF53nD+9HAZYLGYfIQmcebJ3t1RiEO8x54YboPvvPHGkOsZIJmXdTVZkeSSzX5D0lAwbBgEkW1EhubB+SNHdUoYarOopvqqbPCOWHkABHDgqj4bBJBYuPnxZ/NH+fvQ36mHwfAvAABeMBoTvAzj9TCLch4GzQhJaCvY/qDDzsxQYoUAA8mCGAAA4GCEB3KTUiQcmQGAAOQVBgAmGA4oOTdDVHkR4AAqSA69mH/DiNMfgoDU5fGACGBgcJyGai4BAGCIp1g1EkJfUO19w5Xl/i/aRH8xrx2/rgJR/9JCAJ4WAvURgMB2CgaLJBEsNrfWRm3cKgxpx7AwY1MEEJcHEPEkPFBdjzEkJoEyRejCHhui4MoN+e9IRqVUC/TUAB3LoxQGAUP5NQ9wmZuiPAAFIGGZJybkyQICyO6vIvqd8tGv3frHNRX9XxuT1HMbAJQYAZ21g3XWldS711bnreBhFEFrRkn9GpuA6mCHmLgTB04vhoLBNjX2rjDbbhNhCAZQyWDzGSMkaZysvhuzKqiL2eMfb20pAPWBGFh4MCWfUlZayNmTwinCUqHtdnxXqlZYkDA/YMBnoHUaZAGBCDEBwDEDTqDeDaQrLSVT3zWzeiZFUx1rDN3kkyNgtRckVEkBAVUYAGAACtOwSO5JAcQ9pHiQFSI6EslihE8AYAAEQgLIUQnR3Q5EGICeSwJwqwshRqDKDAcF2Dedyya+YMqNSynCtyLBUYgneUKyV74+UAGpvIKt5eK1VPLRWzm+fPBgExgBKGDLgUJ3AsgolUHwBUVpkAoB+Y4f5HBoTAtBQ9MuLktXuThoSYV8KunItRaIBgGKsW4vxdk6UogxAksjeSqoLdzV0oZUyhhrL2XAk5RCX1UqsGfPsMlNV2qNXZsVTKuVBbPXKs1SKxoxbC2NB1d4xmDg/kAu5rzfiIK67goTlxHifFq1+oscCANGQg0huUGG4UEaiXRqlGSnM8aqWJvpYygQqbshsqBJmwdOb+V5vlZWvpErK1lsYBWmtVaS3qodvWvKur2y/MdenLtYKnqeuBru98/qggorHeizFk68XTq5JG4l87eiLspeJFdyb10ss3emjNoIs13tzYKi98KxW3tPWFWV56v28tCiq69oq61HtngyR9DqAVJ30lUVO7a+KNPdRCmtdGU5c37WyQj+Yf1ZkDQB0NwGCVgbnaSyDFKE00tXSmhDW6OV+C5Wh/dGHeMNvI5es9h7L3EfU9KnDunKNB2o62jgHGGNp3CCx9pGiLOc0/aRhFckR2/sE8GwD2KRMzqjTGhdUnl0ybg8y3YCnkMof0+h/NkXNNYe05hvdJG72xZzcZ+1ZmSnSN0cAsBECHg2Z7RozLADuE5fAbret/G/1oo88J8NoHZ1+ck0umDQW10hbTdupTqGj2qei057DJ6tN4fLZFhgSXcNDaw42uepnHXFZ0aV3hBieDGNfW62znqFvZeW4YwVTmqvuYnV5+rhLfMQbjdBw2sH2sbrC+F5TvWBX9bQyl0tI2CMDb0wNt7RG0vNqfQCi5Lru3vprcD9Th3/21aA6dsTTXLvSZgrJ+DoWkPIce7pvrOnpu/bIx9nHiX9N44bbPIAA)

category:cq
theme:optimization
skill-level:intermediate
cost:medium

**Comment by EgorBo** [comment]
`BitConverter.IsLittleEndian` is not a constant so branch elimination doesn't work. However, it's a readonly field which is converted to a constant if Jit promotes method to Tier1 from Tier0. and then one of the branches is eliminated - it's just not easy to see asm for it (definitely not via sharplab).

**Comment by GoldenCrystal** [comment]
Thankfully, I remembered correctly, and `IsLittleEndian` should already be an intrinsic, as the work was done back in the .NET Core 2.0 days: https://github.com/dotnet/coreclr/pull/9789 (See the associated issue: https://github.com/dotnet/runtime/issues/7480)
I guess that's why branch elimination is working properly in all the assembly listings I posted above ? 😜

However, my question was more about why the assembly generated was not as efficient as the one from the "plain" case, given that the inlining *and* branch eliminations were at work as expected.

FWIW I did a bit more investigation after posting this issue, trying to see how things would work out with generics. (Not an ideal solution, and… Spoiler: It was better but still not very good)

````csharp
[StructLayout(LayoutKind.Explicit)]
public struct RegistersPropertiesLe : IRegisters
{
    [FieldOffset(0)]
    private ushort _hl;
    
    [FieldOffset(1)]
    private byte _h;
    [FieldOffset(0)]
    private byte _l;
    
    public ushort HL => _hl;
    public byte H => _h;
    public byte L => _l;
}

[StructLayout(LayoutKind.Explicit)]
public struct RegistersPropertiesBe : IRegisters
{
    [FieldOffset(0)]
    private ushort _hl;
    
    [FieldOffset(0)]
    private byte _h;
    [FieldOffset(1)]
    private byte _l;
    
    public ushort HL => _hl;
    public byte H => _h;
    public byte L => _l;
}

public class CpuPropertyLe
{
    private RegistersPropertiesLe _registers;
    
    public int DoSomething()
        => _registers.H < 16 ? _registers.HL : _registers.L == 0 ? _registers.H + _registers.L : _registers.H;
}

[JitGeneric(typeof(RegistersPropertiesLe))]
[JitGeneric(typeof(RegistersPropertiesBe))]
public class CpuProperty<TRegisters>
    where TRegisters : struct, IRegisters
{
    private TRegisters _registers;
    
    public int DoSomething()
        => _registers.H < 16 ? _registers.HL : _registers.L == 0 ? _registers.H + _registers.L : _registers.H;
}
````

````assembly
CpuPropertyLe.DoSomething()
    L0000: cmp [rcx], ecx
    L0002: add rcx, 8
    L0006: mov rax, rcx
    L0009: movzx eax, byte ptr [rax+1]
    L000d: cmp eax, 0x10
    L0010: jl short L001d
    L0012: movzx edx, byte ptr [rcx]
    L0015: test edx, edx
    L0017: je short L001a
    L0019: ret
    L001a: add eax, edx
    L001c: ret
    L001d: mov rax, rcx
    L0020: movzx eax, word ptr [rax]
    L0023: ret

CpuProperty`1[[RegistersPropertiesLe, _]].DoSomething()
    L0000: cmp [rcx], ecx
    L0002: add rcx, 8
    L0006: mov rax, rcx
    L0009: movzx eax, byte ptr [rax+1]
    L000d: cmp eax, 0x10
    L0010: jl short L001d
    L0012: movzx edx, byte ptr [rcx]
    L0015: test edx, edx
    L0017: je short L001a
    L0019: ret
    L001a: add eax, edx
    L001c: ret
    L001d: mov rax, rcx
    L0020: movzx eax, word ptr [rax]
    L0023: ret
````

I did not realize at the time, but as it turns out, it seems that the simple fact of hiding field accesses behind properties, is already making the assembly worse, despite property getters being inlined.

Is it really just a tiered JIT issue ?
I tried adding `[MethodImpl(MethodImplOptions.AggressiveOptimization)]` on the methods (see here: https://github.com/dotnet/runtime/issues/1711#issuecomment-601477171), but it didn't change anything.
This leads me to believe it is not a tiered JIT issue ^^

See [this link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgylWoxbtOASRYiIfcVCkz5y1aIAW2KHwAy2YPWZsOipcoDaojFAZgMBwBPCAYMAApg0IwAaVYmABMaAFEEPkFpVgwASgBdcwBmclxffwxyOhgAc1YSkVwAMVYYQQTcOxhlAG9lcj7yTyaWhIB5ADMx3BgI0jze/uIihlxLaHKACTt3fvJ5vsHm1vHJ6fCqOaUdxfJgIIwYcnXt/oPh46mZi6ui2/vyLeUAF9lIVyPF7lAxtgZORtJUanUoLhuntKEsVmtHnZyF1yFVpnJyMDLgsfncHuscXiCUTUddfg9sbj8RhCcTiV4fH4AlEwpFsCEwnFEik0hkwFkLtcStzyvDahDcAAFKAGERsWQdcggWHyxHIpQ9En7IZHCYfcKzfLG8h8KCsCTYP7LVZQcoAfUsgmefVRrzNJwi52tOztDqdDwZ5E9PoGptG5tOVtRYcdfyj7u9qLp6NdG2xAF4AHzRr2x+nkx7kYul8tkv6FkuZ9wcpTeUo8gXRfmC2LxJKpdKZHLW6UduXVBX1FVqt3NXAAIQeOrhk/1KJt/oTgctX36qYj5BdmM9WZtfvj7yTe76B/TlZjF8O24twZT9rTkYfZ52OaPGLdLFqybMs/yjSka0fG0KwbYDozPVtrmIAAmcguD4Bh43aTpDXfcM/j1RUsK1d1YARRVY1RAB6KjPAAWWmVYEm0fhBHCBiMCYlj0hGPg2AgJhcBoABBKoqlgXBcAdGBeNcVgAC8nVYASbzRMEWHIAARCBRF4Rj4iqcJslRHZILIqckRoSkAB5yCoJByAAfmjcz9Ss7EdVItdFRoQsC3IChnK88j6is8gAGoXO80KPKikLLKeIEQRUIoULQjCZz4dUgg6DdQw/Q9COnVUsrnTUHmCiyzHPG0aPoxiIGY1j2IapqeL45TBJEsSJKkiQZI6/AFKUlSQ1JdTym03SOE4gyjJM/ozOihLyFs+ynLiqr3O1Ta3L8gKNsqtzKUio6fNis7QsSpRW08AApLIAHEYCYERpHCDAgiyiAxnCIqkUy9V5w6bILnup6XresAPq+mAfr+5blRKoHZCXUHR1S1D0IYQG3SCayABV/twItUQAd0sEQHiJxGdplMo0F1RG8v3Aq/hp+LcF2ijs1q2iOK45qBca7jBFkzqhNE8TZD6ga5MU/imFU65wS0nS9NmphDOMm1TKbVyfJsuyHKCg2rous3LP2wLuauiLbatnbLoSlsgA) for the code

PS: I don't have the luxury of having a computer that can checkout and build the dotnet runtime simply to get disassembly listings (maybe in the coming months), so I always been using shaplab to prototype my code in these cases. It usually worked well enough… 😕

**Comment by BruceForstall** [comment]
Since this looks like an optimization issue, not a correctness bug, I've renamed this issue. We always interpret "bad codegen" as a correctness problem.

I haven't investigated this case, but the JIT often bails out on optimizations for overlapping and/or explicit layout structures.

**Comment by GoldenCrystal** [comment]
> We always interpret "bad codegen" as a correctness problem.

My bad, this seems quite logical indeed; sorry for that title


I did a bit more investigation on this issue, and it seems that part of what I observed simply a consequence of wrapping fields into properties and unrelated to `LayoutKind.Explicit`:

As seen [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgylWoxbtOASRYiIfcVCkz5y1aIAW2KHwAy2YPWZsOipcoDaojFAZgMBwBPCAYMAApg0IwAaVYmABMaAFEEPkFpVgwASgBdcwBmclxffwxyOhgAc1YSkVwAMVYYQQTcVPTMjGUAb2VyAfJPJpaEgHkAMwncGAjSPP7B4iKGXEtocoAJO3dB8kWB4ebWyenZ8KoFpT3l8mAgjBhyTd3Bo9HTmbmrm6L7x/IO2UAF9lGClN5SgEomFItgQmE4okaOIAI4MGCabCCK63Ep+AIVaq1R5QRrHNpojFYwS9A6UFZrDbPIHXQb027/J4vDl/B5PVmgjwqIrxUkTbAycjaSo1Opkulsga3VbrKBbOzkHrkKqzOTkIW/O7855anV6g2840AzXa3UYfVCoVeHwEwLw6JwhGxeJJDoZMBZXFFfFlIly0m4AAKUAMIjYsn9XXIIGlspJ9UVe3eJymX3C83ySvIfCgrAk2ABquZAH1LIJXgN6Tnxnnzpci3tS+XK08ueQ642hiNc2dvp3Bt2KwD+zWG/SrdX1SzyABeAB8A/rQ85Js2a83g6t/c1G4H86UzohrrKMIid6RSSpmLY2ODxSh5XT8ujsb48eaXBnxpFM02JH8syWRk1Q1M17UdY89zgi1DSg60BWQh1LUvcFbmIAAmcguD4BgRzaJNA26JQ+mLKde3DDMyTI9o0gDLIB1gCN6iHK0xXIAARCBRF4WZLHiKpwmyek9jPGtOMY3AaH3AAecgqCQcgAH4OPAyMlM1VM5N0+oaFPVdyAobSjK4sklPIABqHSbMUgynIUpT3CvPDCOI0iKSAmB0RfVhsUggY6IBb9I2Y4DX0ENyfx44tbj4wThI4DAxKYCSpOLGTD3kn87NU9StISvTtlA6z3LMiyyuqor90chq9NclqTJ5HDhW8oiSJjON1UAiisjCksy2nJ4ovqfr/0GxNWOTdqySSo1UqEkTMvEyTpMGWTCoq8gSo0qz9o6trTts2rLPKjqHJuy6qouxTOq8ooCN6hgZoA2RYpC2lqPpCLJuMskvrmgKgpApazGLXiWAE9aMqynKdoGPaQeew61OO+7nvOjHTLXczruhuzmqewnDIpl7wU8AApLIAHFMREaRwgwIJ/wgCZwim0G/2+ljOko7IrnppmWbLMB2c5mBud5jGwYTCHqTi0Wix63ylaCZSABU+dwdd6QAd0sEQnn1jHQNDAI0DA5zRqB8hLec3GVrQtb0tErbcr2fLceK7H6up/HnMJ1dieDgmmoD0P3JeoA==), a structure with `LayoutKind.Sequential` will exhibit the same inefficient codegen as the one with `LayoutKind.Explicit` as soon as fields are encapsulated in properties.

Compare

````assembly
CpuFieldsSequential.DoSomething()
    L0000: movzx eax, byte ptr [rcx+0xa]
    L0004: cmp eax, 0x10
    L0007: jl short L0015
    L0009: movzx ecx, byte ptr [rcx+0xb]
    L000d: test ecx, ecx
    L000f: je short L0012
    L0011: ret
    L0012: add eax, ecx
    L0014: ret
    L0015: movzx eax, word ptr [rcx+8]
    L0019: ret
````
to
````assembly
CpuPropertiesSequential.DoSomething()
    L0000: cmp [rcx], ecx
    L0002: add rcx, 8
    L0006: mov rax, rcx
    L0009: movzx eax, byte ptr [rax+2]
    L000d: cmp eax, 0x10
    L0010: jl short L001e
    L0012: movzx edx, byte ptr [rcx+3]
    L0016: test edx, edx
    L0018: je short L001b
    L001a: ret
    L001b: add eax, edx
    L001d: ret
    L001e: mov rax, rcx
    L0021: movzx eax, word ptr [rax]
    L0024: ret
````

Wrapping fields in properties seems to introduce this preamble to the codegen, which could be entirely avoided like in the fields-only case:
````assembly
    L0000: cmp [rcx], ecx ; Is this a null pointer check? This seems to be the side-effect of calling a method on a struct, but why is it needed there and not for field accesses?
    L0002: add rcx, 8 ; Seems this one can be inlined in all the movzx instructions elsewhere… But it could end up being worth it if there was at least one more access to the struct data.
    L0006: mov rax, rcx ; Isn't rcx enough by itself?
````


Then, I guess that when I add the ternary operator in the mix, the JIT becomes unable to unify multiple accesses to the same field, which further increases the size of the generated assembly: [see on SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8YUCAAcAymIBuvMDFwBuGjQDaUjFA5gMAGWwBPCBwwAKQybMBpXlwAmLGQEcOMHr2wAbAJQBdGmIAZgZcbV0MBjYYAHNecLFcfRgaAG8aBiymUI5cAAtoKIAJfVVqbIZM7JCGYCMMGAZi8sra+saGMpoAXzVqTQi9K1MLEdt7J1d3Tx8AoNDwnT1ouITGqFwAIVTqDIqa3IKi5u6DrOqs9oamlsucupuu8r7qDS1lg2NRy2+Jx2cMDcHj4c0CtEWQyiMXiiU26XuEigvFk2E6MPWSRSDAA+t4YK1skiUWimhi4dsmjjgAT7vdanlClASvoGABeAB8DC2vAwAGEIFxZGINsJkryMPiAKKOLxcBgAflx+JYpQYIFxNNVZzaoQ6t3ZXJ5/MFwuZYjF+gl0tl2HlSrxgmK6s1TsJVz1T1ZnO5vIFQpFFqE4owkpgMoccsVysErI11NjL36tTIDD5Eg4CPODGJqPRawpuNgsI2Kjp2dq9iiABEIFIIAIMPl7LFzL57pUfTji5jNqqGAAeBjkJDR7sF0val3jktJFjetkMRgOnsU/sAaiLE7nca3s77d2oryAA)
And again, this might be unrelated to `LayoutKind.Explicit`… 😶


So, the two main issues seem to be for now:
- Wrapping fields of structs into properties seems to generate extra assembly instructions despite properties being inlined.
- An ternary operator optimized to a field acces, itself inside an inlined property, confuses the JIT in not recognizing the same field to be accessed multiple times.

I think I begin to have some vague ideas as to how the property getters could get inlined to produce these results, but I'll not start wildly guessing here, as I've never seriously looked at the JIT source code. 😄

At least, I hope that this further investigation can be of any help to you.

**Comment by AndyAyersMS** [comment]
Because `_registers` is a field of a class the jit must assume that it might be null

The "ternary" construct branches from testing `BitConverter.IsLittleEndian` are not removed in a timely fashion so the jit does not CSE the field references as one might hope. And that seems to happen because we import this static field (which is a special "intrinsic field") as a `bool` and not an `int`:
```
Importing BB10 (PC=000) of 'Registers:get_L():ubyte:this'
    [ 0]   0 (0x000) ldsfld 0A000004
    [ 1]   5 (0x005) brtrue.s

               [000066] ------------              *  JTRUE     void  
               [000065] ------------              \--*  NE        int   
               [000063] ------------                 +--*  CNS_INT   bool   1
               [000064] ------------                 \--*  CNS_INT   int    0
```
This looks like something we can and should fix. I have a prototype in the works and here's the code it produces from your sharplab example above:
```asm
; Assembly listing for method Cpu:DoSomething():int:this

G_M4145_IG01:

G_M4145_IG02:
       add      rcx, 8
       mov      rax, rcx
       movzx    rax, byte  ptr [rax+2]
       mov      edx, eax
       cmp      edx, 16
       jl       SHORT G_M4145_IG07

G_M4145_IG03:
       movzx    rdx, byte  ptr [rcx+3]
       mov      ecx, edx
       test     ecx, ecx
       je       SHORT G_M4145_IG05

G_M4145_IG04:
       ret      

G_M4145_IG05:
       add      eax, edx

G_M4145_IG06:
       ret      

G_M4145_IG07:
       mov      rax, rcx
       movzx    rax, word  ptr [rax]

G_M4145_IG08:
       ret   
```
Loads are CSEd now, null check is folded into the first field access. Still room for improvement, but better.

**Comment by AndyAyersMS** [comment]
> Wonder if it makes sense to convert IsLittleEndian into an intrinsic

It is an "intrinsic field" (see `getFieldIntrinsic` in the jit interface) and the jit produces a constant for it; however that constant was type `bool` and so wasn't getting optimized early, which sometimes inhibited other opts.

**Comment by GoldenCrystal** [comment]
> Loads are CSEd now, null check is folded into the first field access. Still room for improvement, but better.

Indeed, this already looks quite nicer 
Thanks for this quick fix 🙂

**Comment by AndyAyersMS** [comment]
I didn't look at what this does for your various attempts to get the jit to behave better. 

If you get a chance, pick up a nightly build in a day or two, or Preview 5 (next month), and see if you see anything else that concerns you.

**Comment by BruceForstall** [comment]
@AndyAyersMS You wrote one fix related to this issue. Is there any other reason we need to keep this issue open?

**Comment by jakobbotsch** [comment]
Codegen on main for the ternary case today is:
```asm
; Method Program+CpuLe:DoSomething():int:this
G_M53511_IG01:
						;; size=0 bbWeight=1    PerfScore 0.00

G_M53511_IG02:
       movzx    rax, byte  ptr [rcx+09H]
       cmp      eax, 16
       jl       SHORT G_M53511_IG07
						;; size=9 bbWeight=1    PerfScore 3.25

G_M53511_IG03:
       movzx    rcx, byte  ptr [rcx+08H]
       test     ecx, ecx
       je       SHORT G_M53511_IG05
						;; size=8 bbWeight=0.50 PerfScore 1.62

G_M53511_IG04:
       ret      
						;; size=1 bbWeight=0.50 PerfScore 0.50

G_M53511_IG05:
       add      eax, ecx
						;; size=2 bbWeight=0.50 PerfScore 0.12

G_M53511_IG06:
       ret      
						;; size=1 bbWeight=0.50 PerfScore 0.50

G_M53511_IG07:
       movzx    rax, word  ptr [rcx+08H]
						;; size=4 bbWeight=0.50 PerfScore 1.00

G_M53511_IG08:
       ret      
						;; size=1 bbWeight=0.50 PerfScore 0.50
; Total bytes of code: 26

```

Looks identical to the little-endian version now. Will close this as fixed.
