### ISSUE TITLE
[System.Text.Json] Utf8JsonReader from Stream?

### ISSUE THREAD

**Issue by Int32Overflow** [dotnet/runtime#36609]
Until now I have used the library Json.NET from Newtsoft. There was a possibility to create a reader directly from a stream. Can the Utf8JsonReader read directly from the stream?

**Comment by AraHaan** [comment]
I see on the net 5 preview packages where you can pass a stream in, however since I am using some internet based requests from an api which returns response json as a string, I pass that string directly into the System.Text.Json Deserializer.

**Comment by Int32Overflow** [comment]
@AraHaan  Thank you very much for the answer. If I have understood you correctly, the next version will include this function? 
But I want to read JSON fragments from a stream repeatedly. Therefore reading directly from a stream is easier and more performant.

**Comment by layomia** [comment]
@Int32Overflow please see https://github.com/dotnet/runtime/issues/30328. Closing as dup.
