### ISSUE TITLE
Guard against invalid TypeToConvert args to read methods of object and collection converter

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#36605]
Depending on the scenario, we could fail with a NRE:

```cs
[Fact]
public static void ConverterRead_VerifyInvalidTypeToConvertFails()
{
    var options = new JsonSerializerOptions();
    Type typeToConvert = typeof(KeyValuePair<int, int>);
    byte[] bytes = Encoding.UTF8.GetBytes(@"{""Key"":1,""Value"":2}");

    JsonConverter<KeyValuePair<int, int>> converter =
        (JsonConverter<KeyValuePair<int, int>>)options.GetConverter(typeToConvert);

    // Baseline
    var reader = new Utf8JsonReader(bytes);
    reader.Read();
    KeyValuePair<int, int> kvp = converter.Read(ref reader, typeToConvert, options);
    Assert.Equal(1, kvp.Key);
    Assert.Equal(2, kvp.Value);

    // Test
    reader = new Utf8JsonReader(bytes);
    reader.Read();
    try
    {
        converter.Read(ref reader, typeof(Dictionary<string, int>), options);
    }
    catch (Exception ex)
    {
        if (!(ex is InvalidOperationException))
        {
            throw ex; // NullReferenceException thrown.
        }
    }
}
```

~~Validation should take place in this method:~~

~~https://github.com/dotnet/runtime/blob/ce1123f166944422b3d1171fed86a402149c17e8/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonResumableConverterOfT.cs#L17~~

~~The ReadStack `Initialize` method [called downstream](https://github.com/dotnet/runtime/blob/ce1123f166944422b3d1171fed86a402149c17e8/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonResumableConverterOfT.cs#L26) may also need some validation logic.~~

EDIT: the validation may need to take place in the individual object/collection converters.

**Comment by layomia** [comment]
Moving this to 6.0 since this is not a regression and will not be experienced if a compatible `typeToConvert` is passed to the converter.

**Comment by MCCshreyas** [comment]
Hi, @layomia So, in this should we throw an exception like stating that type mismatched or just return `null`? 
In case of throwing an exception, what would be appropriate exception type should be thrown (`InvalidOperationException`?) and with which message?

**Comment by layomia** [comment]
@MCCshreyas I believe an `InvalidOperationException` with a message along the lines of `"Type 'NameOfType' is not compatible with converter 'ConverterName'."` is appropriate.

**Comment by MCCshreyas** [comment]
OK @layomia, thanks for clarification! I will get that implemented!

**Comment by eiriktsarpalis** [comment]
Moving to Future, as we won't have time to work on this in the .NET 7 timeframe.
