### ISSUE TITLE
[System.Text.Json] Map null on json when type for it is enum to default enum value.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#36611]
I would like if the Enum converter would check if the data is null.

Basically on the converter, map the ``TokenType.Null`` to that enum's default value.

And then on writing map that default value back to ``null``.

**Comment by layomia** [comment]
Enums are value types, so they cannot be `null`. The serializer emphasizes correctness (wrt. to honoring both CLR type information and the JSON spec). Other users may depend on the default behavior of throwing `JsonException` when deserializing `JsonTokenType.Null` here for input validation or other reasons.

Any flexibility/custom behavior here can be achieved by using a custom converter.
