### ISSUE TITLE
corerun failed to initialize coreclr on Ubuntu 18.04

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#36623]
commit: bacef403fbfce0d9e3d49368bfd36dec6dea01fc

Repro:

```sh
#!/usr/bin/env bash

# fast debug build of coreclr
src/coreclr/build-runtime.sh  -skipgenerateversion -nopgooptimize

# corerun some assembly
artifacts/bin/coreclr/Linux.x64.Debug/corerun \
    ./src/libraries/Common/tests/Data/TinyAssembly.dll
```

failed with:
> coreclr_initialize failed - status: 0x80004005

`strace -f` result: http://sprunge.us/ahFgEb.

**Comment by am11** [comment]
cc @janvorli, i was investigating sigsegv failure during coreclr_initialize on SmartOS and trying to establish a reference point on Ubuntu, when this issue was encountered. The failure on Illumos side is reported in #36632.

**Comment by janvorli** [comment]
@am11 the build-runtime.sh doesn't build System.Private.CoreLib.dll (it is supposed to build native stuff only).  So it seems like a likely reason for the failure. These 0x80004005 general errors are one more thing that I would like to fix to provide more details on what exactly failed. Eg by providing more fine-grained error codes that would enable easy indentification of where the issue stems from.

**Comment by am11** [comment]
Thank you, I forgot about corelib. After build `clr.corelib` subset and it worked as expected (entry point error is clear, as TinyAssembly is not runnable):

```sh
$ ./build.sh clr.corelib
$ artifacts/bin/coreclr/Linux.x64.Debug/corerun     ./src/libraries/Common/tests/Data/TinyAssembly.dll
coreclr_initialize failed - status: 0x80004005
$ cp artifacts/bin/coreclr/Linux.x64.Debug/IL/System.Private.CoreLib.dll artifacts/bin/coreclr/Linux.x64.Debug/
$ artifacts/bin/coreclr/Linux.x64.Debug/corerun     ./src/libraries/Common/tests/Data/TinyAssembly.dll
Unhandled exception. System.MissingMethodException: Entry point not found in assembly 'TinyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Aborted (core dumped)
```

> These 0x80004005 general errors are one more thing that I would like to fix to provide more details on what exactly failed. Eg by providing more fine-grained error codes that would enable easy indentification of where the issue stems from.

I agree. Is there an issue tracking that or should we keep this one opened?

A general suggestion; i am using `certutil` on Windows to decode hex error codes to the numbers. IMO, if we add these error code as comments next to their definitions, it will improve the tractability when searching in code: https://github.com/dotnet/runtime/blob/54e08b663fd4343e194d9162d7792566b23d380d/src/coreclr/src/pal/inc/pal_error.h#L133-L154

**Comment by janvorli** [comment]
Do you mean adding e.g. 0x8007FF00 as a comment to the  #define ERROR_PALINIT_INITIALIZE_MACH_EXCEPTION line?

**Comment by am11** [comment]
Yes, that's correct.

**Comment by janvorli** [comment]
> Is there an issue tracking that or should we keep this one opened?

No, there is no issue for it opened yet. But it would be better to create a separate one for it. However, I am not sure yet if it is feasible. There are over 600 places in the runtime that return this error code (E_FAIL).

**Comment by am11** [comment]
Ah, 600+ is too many indeed. Maybe some failure cases which are essential to initialization (such as presence of compatible corelib) would be more interesting for the starters. I will close this issue for now and focus on the coreclr initialization on Illumos story.
