### ISSUE TITLE
CompareInfoIsSuffixTests.IsSuffix fails on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36631]
This test fails on every arch with:

```
Assert.Equal() Failure
Expected: False
Actual:   True
```

StackTrace:
```
at System.Globalization.Tests.CompareInfoIsSuffixTests.IsSuffix(CompareInfo compareInfo, String source, String value, CompareOptions options, Boolean expected) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.IsSuffix.cs:line 103
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/steve/dev/net5/droid-runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359
```

**Comment by safern** [comment]
Thanks @steveisok for opening these issues. Given the number of tests and test suites we have would it make sense to open a meta issue per test assembly for each platform listing the individual tests and then we can close the issue once the test suite is green with no ActiveIssue against that issue?

**Comment by GrabYourPitchforks** [comment]
Echoing Santi, I'd also prefer a single issue per assembly. Otherwise we run the risk of drowning out other issues in the repo.

Is there a particular CI output where we can see the failures? I pulled a random recent PR (https://github.com/dotnet/runtime/pull/36633) and it seems like the Android CI legs are passing. Seeing the exact CI failures will help pinpoint what inputs were fed into these test theories at the time they failed.

**Comment by safern** [comment]
> it seems like the Android CI legs are passing. Seeing the exact CI failures will help pinpoint what inputs were fed into these test theories at the time they failed.

We’re not yet running tests on CI. We’re on the process on enabling that and we’ve been running them locally and gathering numbers in order to disable against issues and add a leg.

**Comment by tarekgh** [comment]
@steveisok if you don't mind, we'll consolidate the issues to be one issue per test suite. that is even will be easier for tracking and ensuring the whole suite is fixed. 

@safern could you please go ahead and consolidate those?

**Comment by tarekgh** [comment]
by the way, do we now use ICU on Android? or this work still in progress?

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/36630
https://github.com/dotnet/runtime/issues/36629
https://github.com/dotnet/runtime/issues/36628
https://github.com/dotnet/runtime/issues/36627
https://github.com/dotnet/runtime/issues/36626
https://github.com/dotnet/runtime/issues/36625
https://github.com/dotnet/runtime/issues/36624

**Comment by safern** [comment]
> @safern could you please go ahead and consolidate those?

Yeah I’ll take care of it.

**Comment by safern** [comment]
Closing in favor of: https://github.com/dotnet/runtime/issues/36672

**Comment by safern** [comment]
> by the way, do we now use ICU on Android? 

I believe we use the one that ships as part of Android but I might be miss remembering, @akoeplinger should know better.

**Comment by akoeplinger** [comment]
Yes we use the ICU that is part of the Android system right now.
