### ISSUE TITLE
[browser][wasm] Request Streaming upload via http handler

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#36634]
During the initial review of the browser wasm code integration it was brought to the attention that the request content may not be sufficient in its current state.  

There needs to be more investigation into whether there is a way to stream the request content.  The issue being that not being able to handle this scenario may result in the buffering of huge amounts of data is some scenarios.

These scenarios need to be identified and solution coded if there is a way to achieve this using the browser API.

Initial investigation leads to some sort of wrapping the javascript [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) and exposing it in some way via .NET stream.

- [Using ReadableStreams](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams)

- [WritableStream](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream) 

Model being:

```
fetch('/', {
  method: 'POST', 
  body: new ReadableStream({
    pull: function(controller) {
      console.log('pull called!');
      controller.enqueue('Some data...');
    }
  })
});

```

Right now this does not seem to work as per the discussion here:  https://github.com/whatwg/fetch/pull/425#issuecomment-614452337

As well as multiple issues outstanding.

Also to keep in mind the streaming API is still marked experimental in the documentation.

**Comment by campersau** [comment]
Here is working prototype using `ReadableStream` request bodies. It currently requires the `Experimental Web Platform features` feature to be turned on in chrome://flags.
- https://github.com/campersau/BrowserHttpHandlerRequestStreaming
- https://github.com/campersau/BrowserHttpHandlerRequestStreaming/blob/d847437f47f9efacc00fa60a98f4baca477ad9f6/Client/BrowserHttpHandler.cs#L194-L213
- https://github.com/campersau/BrowserHttpHandlerRequestStreaming/blob/d847437f47f9efacc00fa60a98f4baca477ad9f6/Client/BrowserHttpHandler.cs#L377-L406

**Comment by guardrex** [comment]
@pavelsavara ... I'm in the process of adding remarks to the Blazor WASM *File uploads* topic to alert readers to the limitation of the current `BrowserHttpHandler` implementation for large file uploads. This issue is marked "Future," so it seems like it hasn't reached a critical threshold to be worked for .NET 8. Is it of any benefit for the article to let readers know that they can add an upvote (👍) to help you understand how much interest there is in this potential update? If not, I'll just cross-link this issue. If that would be helpful, I'll tell readers to add a 👍 to the opening comment if they support this suggestion.

**Comment by pavelsavara** [comment]
@guardrex streaming HTTP is still not supported by browsers as far as I could tell.

See https://chromestatus.com/feature/5274139738767360

**Comment by campersau** [comment]
It is supported by Chrome / Edge (https://developer.chrome.com/articles/fetch-streaming-requests/) but not by Firefox (https://github.com/mozilla/standards-positions/issues/663) or Safari (https://github.com/WebKit/standards-positions/issues/24)

**Comment by pavelsavara** [comment]
> It is supported by Chrome / Edge (https://developer.chrome.com/articles/fetch-streaming-requests/) but not by Firefox ([mozilla/standards-positions#663](https://github.com/mozilla/standards-positions/issues/663)) or Safari ([WebKit/standards-positions#24](https://github.com/WebKit/standards-positions/issues/24))

Thanks @campersau!

We could possibly implement it and hide it behind option similar to `WebAssemblyEnableStreamingResponse` we already have. 
@lewing Do you see this is as Net8 priority ?
