### ISSUE TITLE
Add the ability to remove COM support using ILLinker

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#36659]
As discussed in:

* https://github.com/dotnet/runtime/issues/35199#issuecomment-616559764
* https://github.com/dotnet/runtime/issues/31712#issuecomment-620911891

We are currently "rooting" types in the libraries specifically for COM:

https://github.com/dotnet/runtime/blob/0955d7f38597ea80856bd5f6b0cdb915ad90a1a8/src/libraries/Microsoft.CSharp/src/ILLinkTrim.xml#L7-L8

https://github.com/dotnet/runtime/blob/0955d7f38597ea80856bd5f6b0cdb915ad90a1a8/src/libraries/System.Runtime.InteropServices/src/ILLinkTrim.xml#L3-L4

A lot of scenarios in .NET don't have COM support, as such we should be able to trim out any COM specific code when we are linking for a scenario that won't ever need COM (Blazor, Xamarin, Linux, etc).

One way of doing this would be to add a new [feature switch](https://github.com/dotnet/designs/blob/master/accepted/2020/feature-switch.md) to the product that would enable/disable COM. We can then add the switch in code to remove any COM specific code. In order to remove the COM types from being rooted by the `ILLinkTrim.xml` "descriptor XML files" above, we would need the ILLinker to allow "feature switches" to be present in the descriptor XML files, and to include/exclude that root based on the feature switch.

Note that Blazor today is already using something similar when it uses `monolinker.exe` - `--exclude-feature com`. See the [Blazor build code](https://github.com/dotnet/aspnetcore/blob/2d0c49d0fca0aaf37672e0aec1c011cfe6a2d6f2/src/Components/Blazor/Build/src/targets/Blazor.MonoRuntime.props#L9). However, `--exclude-feature` is not supported by the ILLinker, only by `monolinker.exe`.

cc @vitek-karas @MichalStrehovsky @sbomer @marek-safar

**Comment by marek-safar** [comment]
In this case, I'd prefer to see a new public property for COM. Something like `RuntimeFeatures.IsCOMSupported` and use that for all COM related code inside libraries including ComEventsSink or IMarshal dependencies.

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas and @MichalStrehovsky I would be grateful if one of you could provide some suggestions on the best way to solve this issue.

**Comment by jkotas** [comment]
Both `IMarshal` and `ComEventsSink` roots above are instances of https://github.com/mono/linker/issues/936 . What are the plans for ComImport support in the linker?

**Comment by marek-safar** [comment]
Linker has all the required features needed to make COM support feature-based. The ball is on the libraries side to decide what level of granularity is needed and add the API (static bool property/properties).

**Comment by eerhardt** [comment]
> Does it need to be public API, or can it just be internal (for now at least)?

I think it can be internal for now, we can make it public later if we see a need.

____

We would also need a [feature switch](https://github.com/dotnet/designs/blob/master/accepted/2020/feature-switch.md) to allow for trimming `System.Runtime.InteropServices.ComEventsSink` from Microsoft.CSharp, if we want to make this complete. The route I've been going is to name the feature switch the same as the API, so this would be named `System.Runtime.InteropServices.Marshal.IsComSupported`

**Comment by jkotas** [comment]
Ideally, `System.Runtime.InteropServices.Marshal.IsComSupported` would control treatment of types marked with `[ComImport]`. When COM support is on, the linker should keep all methods on interfaces marked with `[ComImport]`. Both `ComEventsSink` and `IMarshal` would be covered by this logic.

Or do you believe that we should rather ask everybody out there (both in libraries and apps) to mark their `[ComImport]` interfaces with an extra linker attribute to tie it with `IsComSupported`?

**Comment by eerhardt** [comment]
> Or do you believe that we should rather ask everybody out there (both in libraries and apps) to mark their [ComImport] interfaces with an extra linker attribute to tie it with IsComSupported?

I guess it depends on how much we want the ILLinker to know about COM. My understanding was that @marek-safar and @vitek-karas were moving away from ILLinker having hard-coded knowledge of features. But since COM is so low in the stack, it may be fine for the ILLinker to know about it.

**Comment by vitek-karas** [comment]
I think we're discussing two related but separate issues here:
1. How to remove anything COM related from apps which don't need/want it - like all of Blazor apps
1. How to make sure that trimmed apps which do use COM actually work

The former is something we're trying to solve for .NET 5. The latter is something we should probably punt to later releases. I also don't think the solutions will be that related, so we should feel free to do what's necessary to make the .NET 5 goals work.

**Comment by eerhardt** [comment]
If we aren't trying to fully solve this issue in .NET 5, I believe the only thing necessary to strip it from Blazor would be to remove these lines from the System.Private.CoreLib's Shared ILLink.Descriptors file:

https://github.com/dotnet/runtime/blob/643f5e1be543ef6582cf9b90c91e804f07e2bea4/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Descriptors.Shared.xml#L50-L55

And move them into the CoreCLR specific `System.Private.CoreLib`'s ILLink.Descriptors file. Then the Mono S.P.C. won't ever have these types - since my assumption is Mono doesn't support COM at all (but I could be wrong there).

For `Microsoft.CSharp` and `System.Runtime.InteropServices`, I don't believe these assemblies will typically be used in Blazor, at least not for the majority of Blazor apps. So we can just leave them as-is. They will get trimmed away since they aren't used.

**Comment by vitek-karas** [comment]
That might work... although it would be safer to introduce the feature switch and make sure that Blazor runs it off - just so that we don't run into surprises in the future.

**Comment by marek-safar** [comment]
> Does it need to be public API, or can it just be internal (for now at least)?

I suspect we'll need it public at least in scope for our libraries. I guess there will be some code outside of SPC which could be conditionally excluded based on this property.

It'd also be helpful for libraries authors so they don' have to rely on 
exceptions handling.

> Ideally, System.Runtime.InteropServices.Marshal.IsComSupported would control treatment of types marked with [ComImport]. When COM support is on, the linker should keep all methods on interfaces marked with [ComImport]. Both ComEventsSink and IMarshal would be covered by this logic.

The COM types are already recognized by the linker and handled differently. I don't think we have should bound that logic directly with `System.Runtime.InteropServices.Marshal.IsComSupported` but it'd be helpful to control this linker behaviour via the same feature-switch which we'll use to set `System.Runtime.InteropServices.Marshal.IsComSupported`

**Comment by jkotas** [comment]
> The COM types are already recognized by the linker and handled differently.

What does linker do for them? If it did the right thing (tm) for them, we would need the manual entries for IMarshal and ComEventsSink?

**Comment by marek-safar** [comment]
> What does linker do for them? 

I think it marks the default constructor and all fields on the type

**Comment by jkotas** [comment]
Fields do not matter for COM interop. Did you meant to say methods?

**Comment by marek-safar** [comment]
I couldn't find the code which is handling this so it looks like it was removed when we stopped caring about COM. We could add it back to linker though.

**Comment by jkotas** [comment]
> remove these lines from the System.Private.CoreLib's Shared ILLink.Descriptors file
> and move them into the CoreCLR specific System.Private.CoreLib

That's sounds like the first thing to do here. These types do not even exist in the shared CoreLib...

**Comment by eerhardt** [comment]
I've opened https://github.com/dotnet/runtime/pull/38172 for that first change.

**Comment by AaronRobinsonMSFT** [comment]
> Ok, my proposal would be `bool Marshal.IsComSupported`, returns true by default on Windows and false by default on Unix. Does it need to be public API, or can it just be internal (for now at least)?

@marek-safar @jkotas @eerhardt Thoughts on putting this under `RuntimeFeatures.IsComSupported` for the public version? This would be how I would add the public API and I can put out an API review and PR shortly. For an internal version creating an `internal static bool Marshal.IsComSupported` seems the most appropriate. If we need this public I would prefer to put this in the "canonical" place for feature support instead of hiding it on the `Marshal` class.

**Comment by eerhardt** [comment]
> and I can put out an API review and PR shortly

I'm not convinced this is a "must have" for 5.0. The target scenario for 5.0 is to enable Blazor WASM applications, which use the Mono runtime. In those apps, the COM support is completely stripped (except for the Microsoft.CSharp case, which Blazor apps don't use by default). So either way I don't think this is something we need to address in 5.0.

As for the question "Should this bool be public or not?" - I think my initial opinion would be to make it internal, until we found a need for it to be public. Is there something external consumers could do with this boolean? If they need to use COM, and it isn't supported, what would they alternatively do?

**Comment by jkotas** [comment]
>  I would prefer to put this in the "canonical" place for feature support

The "canonical" place for feature support properties is the "main" type for the feature, so `Marshal.IsSupported` sounds appropriate.  `System.Runtime.CompilerServices.RuntimeFeature` is only for core runtime features that are not exposed as public APIs.

**Comment by AaronRobinsonMSFT** [comment]
>If they need to use COM, and it isn't supported, what would they alternatively do?

Great question. For pre-.NET 5.0 they could fallback to some user generated approach (e.g. [SharpGenTools](https://github.com/SharpGenTools/SharpGenTools)). For .NET 5.0, [with some work on our side](https://github.com/dotnet/runtime/issues/36582), they could leverage the ComWrappers approach again with some external tooling  (e.g. [SharpGenTools](https://github.com/SharpGenTools/SharpGenTools)). The question that could be asked is "can I use the built-in system or do I need to supply the interop?". I don't know of another decision that could be made other than throw `NotSupportedException`.

>The "canonical" place for feature support properties is the "main" type for the feature, so Marshal.IsSupported sounds appropriate.

Okay.

>System.Runtime.CompilerServices.RuntimeFeature is only for core runtime features that are not exposed as public APIs.

So checking for feature support is spread across various locations? That seems really hard to find and determine support in fact I don't know of another API surface area that defers checking for support to disparate areas. Even the class name seems to imply that "RuntimeFeatures".

**Comment by AaronRobinsonMSFT** [comment]
>I'm not convinced this is a "must have" for 5.0. 

Okay. I will move this to .NET 6.0. Feel free to remark if this becomes a need for .NET 5.0.

**Comment by jkotas** [comment]
> So checking for feature support is spread across various locations? 

Yes, each feature exposed as API is responsible to expose its own local `bool IsSupported` properties as necessary. IIRC, it was discussed during API reviews of this problem space and the local `bool IsSupported` properties were agreed upon as the right pattern to follow. This pattern scales well to 3rd party libraries among other things.

**Comment by vitek-karas** [comment]
I creates https://github.com/dotnet/runtime/issues/43604 to track the work around breaking hard coded dependencies in `ComActivator`.

**Comment by eerhardt** [comment]
@LakshanF - is this work completed? Or is there still more to do?

**Comment by LakshanF** [comment]
There are still some cleanup work around test coverage and rooting native types. I'm planning to spend some time this week to review and will re-visit this after that

**Comment by SamMonoRT** [comment]
@LakshanF @eerhardt -  are we on track to get this in by Preview 7 ?

**Comment by LakshanF** [comment]
yes

**Comment by LakshanF** [comment]
Closing this now
