### ISSUE TITLE
Process terminated due to error in .NET Runtime with exit code c0000006

### ISSUE THREAD

**Issue by fernandreu** [dotnet/runtime#36660]
### Description

I have a C#/WPF application with a handler for the `Application.Dispatcher.UnhandledException` event. Despite that, some users are experiencing intermittent crashes where this event does not seem to get fired. When I look at Windows's event log, I can see an error coming from the .NET Runtime with the following message:

```
Application: NameOfMyApp.exe
CoreCLR Version: 4.700.19.60701
.NET Core Version: 3.1.1
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFF06600F8B (00007FFF06470000) with exit code c0000006.
```

That is unfortunately all I can find for now in terms of error messages / stack traces.

The issue seems to occur when reading / writing data via the SQLite provider for EFCore (more details below). However, before I go and post a similar issue somewhere else, I was wondering if there could be an underlying issue in the runtime as well, or if you know any other information I could check to debug this / catch the error at run time. Would `AppDomain.UnhandledException` or any other similar event get fired for this type of error for example?

### Configuration

- Runtime: .NET Core 3.1.1
- OS: Windows 10 (not sure of the specific versions right now, but I can check if needed)
- Architecture: x64

### Regression?

I am not sure if this would occur on earlier versions or in .NET Framework (quite difficult to isolate / reproduce as well).

### Other information

The .NET Core runtime is self-contained within the app folder, which is stored in %TEMP% (it gets initially copied there by a second process, but this should be irrelevant for the crash in hand). Other than the files in that temp folder, the app should just be accessing a few things from a network drive (in Windows Server I believe):

- An SQLite database which gets used via `Microsoft.EntityFrameworkCore.Sqlite`
- A folder containing some crash reports automatically generated in the `Application.Dispatcher.UnhandledException` event handler
- A folder with dummy lock to check who has the tool open in a simple manner. Each app instance has exclusive write access to one of those

Most (if not all) users experiencing crashes access this network drive via a VPN connection. The crashes usually occur when the database is being read / written.

This leads me to think that the VPN connection is causing some temporary disconnects in the middle of the database operations, in turn causing some issue with the unmanaged SQLite driver, garbage collection, or something similar.

Another possibility is that the SQLite driver throws an exception which is getting caught by the `Application.Dispatcher.UnhandledException` event handler as expected, but the latter is triggering the runtime error instead (e.g. when generating the automated crash report, or when trying to show a window to the user to inform them about the error).

**Comment by jkotas** [comment]
This error means that the runtime hit unrecoverable error and that we are unable continue to run managed code.

The best way to diagnose crashes like this is using a crash dump. https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps has details on how to enable crash dump collection on Windows.

**Comment by AraHaan** [comment]
I mean it is possible to have it on Windows for when this type of thing hits the runtime could call ``MiniDump_WriteDump`` and save it to the current directory (assuming windows) with the exception pointers passed in and it being a full dump. That is what I do when my managed code itself causes the ``UnhandledException`` event to file (I normally swallow a lot of minor exceptions, but do not have it swallow the major ones). So in theory the runtime could be changed to do dumps (and if possible log the stack trace of the managed / runtime as well).

**Comment by jkotas** [comment]
> it is possible to have it on Windows for when this type of thing hits the runtime could call MiniDump_WriteDump

We cannot do this by default. Doing this by default would create more problems than it would solve, e.g. the dumps can take a while to write and they can occupy non-trivial amount of diskspace.

We defer to the OS crash dump collection policy by default (on both Windows and Unix). 

For .NET 5, we have added configuration options to allow configuring the crash dump collection. Details in https://github.com/dotnet/runtime/pull/35381/

cc @mikem8361

**Comment by fernandreu** [comment]
Thanks a lot for the replies. I think this confirms my suspicions about the SQLite library. I will see if I can get more info about the crash the way you mentioned and post the details somewhere more appropriate depending on what I find (possibly in either the [efcore](https://github.com/dotnet/efcore) or the [SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw) projects). It is also nice that there will be some configuration options directly on .NET 5.

Just to confirm, [this article](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) mentions the following:

> Applications that do their own custom crash reporting, including .NET applications, are not supported by this feature.

I guess this refers to standard .NET exception handling and not crashes of the runtime itself like in this case?

**Comment by jkotas** [comment]
> I guess this refers to standard .NET exception handling and not crashes of the runtime itself like in this case?

Correct.
