### ISSUE TITLE
System.Globalization.Tests fail on Android

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#36672]
Various tests from System.Globalization.Tests fail on Android:
- [ ] CompareInfoCompareTests.Compare
- [ ] TextInfoMiscTests.ToUpper
- [ ] TextInfoMiscTests.ToLower
- [ ] CompareInfoIsSuffixTests.IsSuffix
- [ ] CompareInfoIsPrefixTests.IsPrefix
- [ ] CompareInfoLastIndexOfTests.LastIndexOf_String
- [ ] CompareInfoIndexOfTests.IndexOf_String
- [ ] CompareInfoTests.SortKeyTest
- [ ] CultureInfoEnglishName.EnglishName
- [ ] RegionInfoPropertyTests.MiscTest
- [ ] RegionInfoPropertyTests.NativeName
- [ ] RegionInfoPropertyTests.EnglishName
- [ ] CultureInfoNativeName.NativeName

Note that more tests might be shown as failed (in testResults.xml) now because of `SkipTestException` thrown in `RemoteExecutor`, we need support from the runner to treat those tests as skipped: https://github.com/dotnet/xharness/issues/205

Stack traces
[System.Globalization.Methods_and_Stack_traces.txt](https://github.com/dotnet/runtime/files/4734148/System.Globalization.Methods_and_Stack_traces.txt)

Edit: Updated based on https://github.com/dotnet/runtime/pull/50095

[System.Globalization.Tests.log](https://github.com/dotnet/runtime/files/6259942/System.Globalization.Tests.log)

**Comment by GrabYourPitchforks** [comment]
We'd need to know what inputs are causing the failures, along with how we can get the CI logs from the failures. Current PR legs are not failing, so this issue is at the moment not actionable by the team.

**Comment by safern** [comment]
@GrabYourPitchforks we don’t have them running on CI yet. This issue is to track progress of adding these legs to CI and to be able to disable the tests agains the issue. There is no action required by anyone but the crew working on the mobile effort.
