### ISSUE TITLE
Httpclient,Please support UTF8-encoding for ContentDisposition.FileName 

### ISSUE THREAD

**Issue by softboy99** [dotnet/runtime#36683]
In the [https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderDescriptor.cs#L140](url) ,you commented:"Normally Location should be in ISO-8859-1 but occasionally some servers respond with UTF-8.", For ContentDisposition.FileName, it is the same. Please support UTF8-encoding. Thanks a lot for your great help.

**Comment by karelz** [comment]
@softboy99 can you give us examples? Is it truly UTF-8 or just Latin-1 (something we already got report for and are considering).

**Comment by GrabYourPitchforks** [comment]
[`ContentDispositionHeaderValue.FileName`](https://apisof.net/catalog/System.Net.Http.Headers.ContentDispositionHeaderValue.FileName) (from namespace _System.Net.Http.Headers_) supports RFC 5987 and UTF-8 encoded filenames natively.

[`ContentDisposition.FileName`](https://apisof.net/catalog/System.Net.Mime.ContentDisposition.FileName) (from namespace _System.Net.Mime_) does not support this.

Which type are you discussing?

**Comment by softboy99** [comment]
System.Net.Http.Headers, do you mean it has been supported? in which verson? I'm using  .net framework 4.7.2,which depends on System.Net.Http 4.2.0.0.

**Comment by softboy99** [comment]
Hi,
After update to .net framework 4.8, it also depends on System.Net.Http 4.2.0.0

**Comment by softboy99** [comment]
@GrabYourPitchforks Do you mean it has been supported? in which verson?System.Net.Http 4.2.0.0 or latest 4.3.4?

**Comment by scalablecory** [comment]
@softboy99 HttpClient on .NET Core supports UTF-8 via `ContentDispositionHeaderValue.FileNameStar` property.

Note that this repo is for .NET Core, not .NET Framework. HttpClient's implementation is very different between the two, and there may not be feature parity.

**Comment by karelz** [comment]
Seems to be addressed, closing.
