### ISSUE TITLE
How to cross compile mscorlib?

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#36684]
PR https://github.com/dotnet/runtime/pull/35115 removed src/coreclr/build.cmd script, which was previously used during the freebsd bringup; to build feebsdmscorlib: https://github.com/dotnet/runtime/blob/4f9ae42/docs/workflow/building/coreclr/freebsd-instructions.md

Now that the script is removed, what is the new approach to build mscorlib for new platforms?

**Comment by stephentoub** [comment]
cc: @ViktorHofer

**Comment by jkoritzinsky** [comment]
You can pass the `-os` flag with the `TargetOS` value that you want when building `System.Private.CoreLib` to cross-compile it.

**Comment by am11** [comment]
Thanks. Forgot to close this issue. Yes, I am using `-cross -os illumos` in the CI script to cross-compile the whole set of artifacts: https://github.com/am11/runtime/blob/cc00c2c828d1/.github/workflows/main.yml#L26.
