### ISSUE TITLE
Incorrectly named function arguments in TryGetPlatformSocketOption

### ISSUE THREAD

**Issue by usr-sse2** [dotnet/runtime#36686]
https://github.com/dotnet/runtime/blob/49f59a3cb935523c07187ce26bb03c7fa7fd66bd/src/libraries/Native/Unix/System.Native/pal_networking.c#L1951

https://github.com/dotnet/runtime/blob/49f59a3cb935523c07187ce26bb03c7fa7fd66bd/src/libraries/Native/Unix/System.Native/pal_networking.c#L2084

Here `socketOptionLevel` and `socketOptionName` seem to be swapped, according to the definition: https://github.com/dotnet/runtime/blob/49f59a3cb935523c07187ce26bb03c7fa7fd66bd/src/libraries/Native/Unix/System.Native/pal_networking.c#L1595

The issue has been found with Svace static analyer: https://www.ispras.ru/en/technologies/svace/

**Comment by ManickaP** [comment]
The names of arguments are swapped in definition: https://github.com/dotnet/runtime/blob/49f59a3cb935523c07187ce26bb03c7fa7fd66bd/src/libraries/Native/Unix/System.Native/pal_networking.c#L1595 The call sites are OK, at least according to code. The `socketOptionName` is compared with `SocketOptionLevel_` values and vice versa, see: https://github.com/dotnet/runtime/blob/49f59a3cb935523c07187ce26bb03c7fa7fd66bd/src/libraries/Native/Unix/System.Native/pal_networking.c#L1597-L1599

**Comment by stephentoub** [comment]
Yup. It looks like there's no actual functional bug here, just poorly named function arguments.

**Comment by AraHaan** [comment]
This this only in unix?

**Comment by stephentoub** [comment]
Yes

**Comment by AraHaan** [comment]
*grabs pitchfork*
