### ISSUE TITLE
Mono: ConstructorInfo.ToString () returns unexpected format

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#36688]
Example:

```csharp
public class Application
{
	static void Main (string[] args)
	{
		Console.WriteLine (typeof (Application).GetConstructors ()[0]);
	}
}
```

Actual result:

```
.ctorVoid ()
```

Expected result (output when using mono or a dotnet console app):

```
Void .ctor()
```

**Comment by alexischr** [comment]
@rolfbjarne I am actually getting `Void .ctor()` (on stable, X.I version 13.18.2.1)

**Comment by rolfbjarne** [comment]
@alexischr Sorry I wasn't clear in the description, but the problem occurs with .NET 5, not current stable XI.

**Comment by alexischr** [comment]
I did something wrong the first time I checked this under a default desktop build and must have run CoreCLR on my sample - The behavior is actually reproducible on the desktop when using a Mono build. So this is a more general bug.
