### ISSUE TITLE
Add "static class Lazy" with Lazy::Create<T>(…) methods

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/runtime#36709]
## Background and Motivation

Currently for creating `Lazy<>` value user must explicitly specify a type of the value (generic type parameter):
```cs
var lazyValue1 = new Lazy<MyObject>();
var lazyValue2 = new Lazy<MyObject>(isThreadSafe: false);
var lazyValue3 = new Lazy<MyObject>(LazyThreadSafetyMode.PublicationOnly);
var lazyValue4 = new Lazy<MyObject>(() => new MyObject(param1));
var lazyValue5 = new Lazy<MyObject>(() => GetMyObject(param1), isThreadSafe: true);
var lazyValue6 = new Lazy<MyObject>(GetMyObject, mode: LazyThreadSafetyMode.PublicationOnly);
var lazyValue7 = new Lazy<MyObject>(new MyObject(param2));
```
In many cases user must repeat yourself and specify type of the lazy value twice.
The purpose of the new API is to simplify the creation of `Lazy<>` values by using type inference where possible.

## Proposed API

```diff
namespace System
{
+  public static class Lazy
+  {
+    public static Lazy<T> Create<T>(Func<T> valueFactory) => new Lazy<T>(valueFactory);
+    public static Lazy<T> Create<T>(Func<T> valueFactory, bool isThreadSafe) => new Lazy<T>(valueFactory, isThreadSafe);
+    public static Lazy<T> Create<T>(Func<T> valueFactory, LazyThreadSafetyMode mode) => new Lazy<T>(valueFactory, mode);
+    public static Lazy<T> Create<T>(T value) => new Lazy<T>(value);
+  }
}
```
This pattern already used in some types: [Tuple](https://github.com/dotnet/runtime/blob/714fbbc71c271244ca469c5b6af0839cf374ef99/src/libraries/System.Private.CoreLib/src/System/Tuple.cs#L22), [KeyValuePair](https://github.com/dotnet/runtime/blob/77b1d6410497c1d8b298c6cfeaeaaba8232ad4d2/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/KeyValuePair.cs#L12), [Partitioner](https://github.com/dotnet/runtime/blob/d734c7ee32add0fbdd9fedcacc3cadd03b369de2/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/PartitionerStatic.cs#L69) etc.

## Usage Examples

With proposed API calling of four of seven constructors of `Lazy<>` can be simplified:
``` C#
var lazyValue4a = new Lazy<MyObject>(() => new MyObject(param1));
var lazyValue4b = Lazy.Create(() => new MyObject(param1));

var lazyValue5a = new Lazy<MyObject>(() => GetMyObject(param1), isThreadSafe: true);
var lazyValue5b = Lazy.Create(() => GetMyObject(param1), isThreadSafe: true);

var lazyValue6a = new Lazy<MyObject>(GetMyObject, mode: LazyThreadSafetyMode.PublicationOnly);
var lazyValue6b = Lazy.Create(GetMyObject, mode: LazyThreadSafetyMode.PublicationOnly);

var lazyValue7a = new Lazy<MyObject>(new MyObject(param2));
var lazyValue7b = Lazy.Create(new MyObject(param2));
```

## Alternative Designs

As alternative, users can add a proposed class to own projects / libraries, if needed.

## Risks

May conflict with a types already defined in user libraries in `System` namespace.

**Comment by FiniteReality** [comment]
Wouldn't [target typed new](https://github.com/dotnet/csharplang/blob/64da1dcf0085eea2d70a737e5f39d48b9bff8d5d/proposals/target-typed-new.md) also solve this (for C#), without the need for a new type?

**Comment by GrabYourPitchforks** [comment]
@FiniteReality yes:

```cs
var x = new Lazy<object>(() => new object());
var y = new Lazy<Object>(() => new()); // using target typed new; tersest syntax
var z = Lazy.Create(() => new object()); // proposal here
```

**Comment by ViIvanov** [comment]
Forgot about "target typed new". It will not help in cases, where no object creation expressions under `Lazy<>` factory:
```cs
var x1 = new Lazy<object>(() => GetMyObject());
var x2 = Lazy.Create(() => GetMyObject());

var y1 = new Lazy<object>(instance);
var y2 = Lazy.Create(instance);
```

**Comment by GrabYourPitchforks** [comment]
But it's still only saving 4 - 5 characters of typing. Is there a code pattern that was previously difficult that this proposal makes easier?

**Comment by mburbea** [comment]
Personally, I still feel that what's missing for `Lazy<T>` or `LazyInitializer<T>`, is a variant that takes a state object. e.g.
```cs
T EnsureInitialized<T,TState>(ref T target, Func<TState, T> valueFactory, TState state)
T EnsureInitialized<T,TState>(ref T target, ref bool initialized, ref object syncLock, Func<TState, T> valueFactory, TState state);
```
That way you can avoid potentially creating a delegate every single time the lazy is invoked.

**Comment by ViIvanov** [comment]
@GrabYourPitchforks 
1. Number of saved characters depends on length of the type, for example:
```cs
var x = new Lazy<Dictionary<string, ISomeFeatureProvider>>(() => BuildProvedersCache());
var y = LazyCreate(() => BuildProvedersCache());
```
2. It will help not add `using` directive for not-imported types
3. In a general, it allows not thinking about a concrete type of the expression at all. If I make some changes in an expression and need a lazy value of it expression, I need just change an expression and not an initialization

**Comment by GrabYourPitchforks** [comment]
> Number of saved characters depends on length of the type, for example:

It has already been established that using target typed new offers even more savings.

> It will help not add using directive for not-imported types ... it allows not thinking about a concrete type of the expression at all

I don't believe this will be the case in practice. The overwhelming use case for `Lazy<T>` is to use them as fields in a class, as shown below.

```cs
public class SomeClass
{
    private readonly Lazy<Foo> _lazy = new Lazy<Foo>(/* ... */); // field set as part of SomeClass's ctor
}
```

In this scenario the field type must be written out explicilty - you can't use _var_ or otherwise infer it. So you need both the using directive and the concrete _T_.

**Comment by ViIvanov** [comment]
Generally agree, the proposed API will be limited to local variables after "target typed new" released.
```cs
Lazy<Dictionary<string, ISomeFeatureProvider>> lazyDictionary = new (() => new ());
Lazy<MyObject> lazyObject = new (() => new ());
Lazy<MyObject> lazyInstance = new (new ());
Lazy<MyObject> lazyItem = useLazy ? new (() => new ()) : new (new ());
```
:thinking:
Will try to understand how often local `Lazy<>` variables used in other projects and how it will look with target typed new. Thank you for pointing out.

**Comment by ViIvanov** [comment]
Thanks to all, looks like that with "[target-typed new](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-new.md)" feature (already available in MSVS 2019 Preview) proposed methods will have a narrow scope, limited to local `Lazy<>` variables. Such variables are very rarely used. I think, anybody can add proposed class to own assembly, if needed.

Therefore, this issue should be closed.
