### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.DnsEndPointTest.Socket_ConnectAsyncDnsEndPoint_Success(type: Async)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36737]
failed in job: [runtime-libraries outerloop 20200519.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=651228&view=ms.vss-test-web.build-test-results-tab&runId=20205164&resultId=103418&paneView=debug)

Error message
~~~
Timed out while waiting for connection
Expected: True
Actual: False


Stack trace
   at System.Net.Sockets.Tests.DnsEndPointTest.Socket_ConnectAsyncDnsEndPoint_Success(SocketImplementationType type) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 209
~~~

**Comment by karelz** [comment]
Failures during 3/12-5/11 (incl. PRs):

Date | Build / PR | OS
-- | -- | --
4/30 | Official run | Windows.10.Amd64.Server19H1.Open

**Comment by wfurt** [comment]
triage: DNS and  outerloop is not 100% reliable. No recent failures -> closing.
