### ISSUE TITLE
System.Net.Mail.MailAddress.ToString() issue with embedded double quotes in DisplayName

### ISSUE THREAD

**Issue by J0nKn1ght** [dotnet/runtime#36752]
### Description

If a MailAddress instance is created with a DisplayName that includes embedded double quote characters, the ToString method doesn't properly escape the embedded double quotes.

The ToString method in the repository is currently:

```c#
        /// <summary>
        /// this returns the full address with quoted display name.
        /// i.e. "some email address display name" &lt;user@host&gt;
        /// if displayname is not provided then this returns only user@host (no angle brackets)
        /// </summary>
        public override string ToString()
        {
            if (string.IsNullOrEmpty(DisplayName))
            {
                return Address;
            }
            else
            {
                return "\"" + DisplayName + "\" " + SmtpAddress;
            }
        }
```
[link to above source](https://github.com/dotnet/runtime/blob/1c048bdfc7b7e4dc9b6d8170b63052695b1d8459/src/libraries/System.Net.Mail/src/System/Net/Mail/MailAddress.cs)

If the DisplayName property includes double quotes, then these are not escaped properly before surrounding the string with additional double quotes.  
For example, if the display name is 'Henry "The Fonz" Winkler', when the ToString method is called, the resulting string would be:
`\"Henry \"The Fonz\" Winkler\" <someemail@somedomain.com>`
but should be:
`\"Henry \\\"The Fonz\\\" Winkler\" <someemail@somedomain.com>`

### Configuration

Tested on .Net Core v2.2, but the source in this repository looks like it is still an issue in the latest version.

### Regression?

Not known if this worked correctly on previous versions of .Net Framework / .Net Core

**Comment by scalablecory** [comment]
`ToString()` is not intended to return a serialized string, merely one that is human-readable. I don't know that I would want to escape the inner quotes here, as it would sacrifice readability.

**Comment by J0nKn1ght** [comment]
OK, thanks. So is there no built in way to produce a full mail address string which can be re-parsed?  I've added an extension method to build the elements up and escape double quotes in the DisplayName property, but it seemed like there should be a method in the framework to produce a string which can be re-parsed using the MailAddress constructor (or anything else that accepts an RFC 2822 format email address).
Happy to carry on using my extension method if you don't think it would be useful.

**Comment by karelz** [comment]
Triage: We already allow proper parsing (added in #907). Adding proper serialization as mirroring functionality makes sense. Using `ToString` is probably best.
Looks like fairly straightforward change -- any interest to contribute a PR @J0nKn1ght?
cc @MarcoRossignoli

**Comment by J0nKn1ght** [comment]
Hi @karelz - Sorry, I've been busy with project deadlines.  As you say, it's a simple change, so I could look at doing a PR. Do you think that it's acceptable to always return a MailAddress from ToString with escaped embedded double quotes? Can you envisage any circumstances where that could break existing code that uses ToString?

**Comment by jaymin93** [comment]
I was also checking for the issue you opened but when I add  double quotes string the values I am getting back the same way so can you explain. Why you need this actually I seen your expected output but it's escaping the already escaped string not the original one so what display name currently returns that seems perfect for me

**Comment by jaymin93** [comment]
And in your extension method are you replacing only double quotes or any other special char can you show extension method ?

**Comment by J0nKn1ght** [comment]
@jaymin93 So, if you have a variable (say 'displayName') that contains:

`Henry "The Fonz" Winkler`

and you instantiate a new MailAddress with:

`var mailAddress = new MailAddress("hw@yopmail.com", displayName);`

if you call the ToString() method and view the result it contains this:

`"Henry "The Fonz" Winkler" <hw@yopmail.com>`

i.e. there are four double quote characters, and the ones around 'The Fonz' are not escaped (to a higher level than the surrounding ones).  Therefore, anything trying to parse the mail address will match the first double quote with the one before 'The...', not the one after 'Winkler'.  To correctly parse the mail address, the double quotes around 'The Fonz' must be escaped.

We're actually getting the error when passing the value from ToString to the constructor of MailAddress, which should parse it correctly, but I suspect that anything trying to parse an [RFC 2822](https://tools.ietf.org/html/rfc2822) mail address will have the same problem.  There's information on page 9 about quoted pairs, and an example on page 41 of a mail address containing double quote characters, showing that they have to be escaped.

The extension method that I'm using is this:
```
        public static string ToSafeString(this MailAddress mailAddress)
        {
            if (!string.IsNullOrEmpty(mailAddress.DisplayName))
                return $"\"{mailAddress.DisplayName.Replace("\"", "\\\"")}\" <{mailAddress.Address}>";
            else
                return mailAddress.Address;
        }
```
As the C# string contains double quote characters that are already escaped, the extension method replaces any embedded double quotes with two additional escape characters, so that the escape character is itself escaped.

Does that make sense?

**Comment by jaymin93** [comment]
ok now i got what your concern is all about , and i will be happy to add pr for same if you do not mind . so should i go ahead and add pr ?

@karelz i am interested adding pr for same , should i create overload of tostring( bool escape) or should i add replace logic in the existing to string  ?

**Comment by wfurt** [comment]
I think we should just fix ToString() @jaymin93 . Adding any new API surface would require API review and it would defeat the intention to use ToString() for serialization as well as for debug.

**Comment by jaymin93** [comment]
OK so I will go ahead with fixing with replacement logic and send pr will it work?

**Comment by karelz** [comment]
That's the best bet - let's hope no surprises / other consideration come into your PR's way ;)

**Comment by jaymin93** [comment]
I have added logic for replacement and ran the test,(it's my first pr on  gihutb and I am new here) what should I do not to add pr I try to commit the code from vs, obviously I should be not Able to commit in master and it shown me the same error. Then in which branch Should I commit this code? Please guide me in case I am doing any wrong steps for committing code thanks.

**Comment by wfurt** [comment]
Take a look at https://github.com/dotnet/runtime/blob/master/docs/pr-guide.md
In essence:
- make fork in your workspace
- create brach (name does not matter but I like them descriptive)
- build and run tests current tests
- add tests
- make fix
- run tests
- repeat previous 3 stems as needed

when ready, create PR, reference this issue in description.

**Comment by jaymin93** [comment]
i have certain issues with unit test as below , any advice  ?

i have all pre requisite for building libs , i ran build.cmd but vs shows various error   

![image](https://user-images.githubusercontent.com/10508429/84594148-d9627c80-ae6d-11ea-8a6c-3b7aaef1c530.png)

**Comment by wfurt** [comment]
try to build the whole project from command line with tests - at least once. 
@ViktorHofer may have more insight to what exact VS version you need. 
There were some recent changes and I think it may needs particular version to make tests working right.

**Comment by ViktorHofer** [comment]
The minimum required VS version is 16.6  Preview 2, see the windows-requirements.md file for more infos.

**Comment by ViktorHofer** [comment]
Can you please try to restore the solution from CLI first?

**Comment by jaymin93** [comment]
yes using your suggestion to restore from cli worked and errors for tests are gone now and it's building the both source and test , but while running the test i am getting below output in both vs stable and latest preview 


![image](https://user-images.githubusercontent.com/10508429/84865810-743d9f80-b096-11ea-884a-ac2e899f3eb9.png)


any help or suggestion would be appreciated thanks.

**Comment by ViktorHofer** [comment]
Sure, happy to help. How did you build the repository first? Did you invoke "build.cmd clr+libs -rc Release"?

**Comment by jaymin93** [comment]
i used this steps 

https://github.com/dotnet/runtime/blob/master/docs/workflow/building/libraries/README.md

and  executed below steps for building lib
https://github.com/dotnet/runtime/blob/master/docs/workflow/building/libraries/README.md


git clean -xdf
git pull upstream master & git push origin master
:: Build Debug libraries on top of Release runtime:
build -subset clr+libs -runtimeConfiguration Release
:: The above you may only perform once in a day, or when you pull down significant new changes.

:: If you use Visual Studio, you might open System.Text.RegularExpressions.sln here.
build -vs System.Net.Mail

:: Switch to working on a given library (RegularExpressions in this case)
cd src\libraries\System.Net.Mail

:: Change to test directory
cd tests

:: Then inner loop build / test
:: (If using Visual Studio, you might run tests inside it instead)
pushd ..\src & dotnet build & popd & dotnet build /t:test

**Comment by ViktorHofer** [comment]
Oh I see what happened here. When you open VS can you also pass in the runtimeconfiguration which you built before:

build.cmd -vs System.Net.Mail -rc Release

**Comment by jaymin93** [comment]
i used command you shared 


build.cmd -vs System.Net.Mail -rc Release

![image](https://user-images.githubusercontent.com/10508429/84884968-043c1300-b0b0-11ea-86c3-3d82e9ce2901.png)


still shows the same issue 

---------- Starting test discovery for requested test run ----------
Using automatically detected runsettings file(s). To learn more visit https://aka.ms/vs-runsettings.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
========== Test discovery aborted: 0 Tests found in 638.1 ms ==========
No tests found to run.

**Comment by ViktorHofer** [comment]
OK sorry for the issue that you are hitting here. I will look into it later today and will get back to you by tomorrow.

**Comment by jaymin93** [comment]
@ViktorHofer its strange my two machines 1 dell 2 surface go shows issues running test while my other PC which is not accessible most of time runs test well ( very slow 3 minutes to run single but runs ) where as all of them are on same vs and source code and windows required components installed
