### ISSUE TITLE
Split AOT cross compilers from iOS/Android runtime packs

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#36758]
Right now we package the Mono AOT compiler inside the Microsoft.NETCore.App runtime pack.

However we don't always need the AOT compiler e.g. for iOS simulator builds where JIT is available and on Android we only use AOT as an optimization.

We should figure out a way to split the AOT compiler off into a separate package.

**Comment by lambdageek** [comment]
I think this is done now, right @directhex ?

**Comment by steveisok** [comment]
Yes, we package the aot compilers separate and they were removed from being in the runtime packs via https://github.com/dotnet/runtime/pull/51782
