### ISSUE TITLE
Net5 should support something like Windows.Foundation.Metadata.GCPressure

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/runtime#36762]
This attribute, when attached to lightweight RCWs, provides the GC with a t-shirt size description of native payload backing the RCW.  This prevents pathological heap freeing of heavy objects.  With the removal of WinRT from the runtime and adoption of C#/WinRT, the WinUI effort still requires this capability.  The name of the attribute and supporting types can certainly be changed.

**Comment by AaronRobinsonMSFT** [comment]
We can build this in or alternatively CsWinRT can implement this manually using [`GC.AddMemoryPressure()`](https://docs.microsoft.com/dotnet/api/system.gc.addmemorypressure).

Internally that is how the built-in WinRT support worked. Below are the relevant values to match the built-in semantics.

Pressure options:
https://github.com/dotnet/runtime/blob/9d9008ee5ec979543c997616f33de5283b73bad5/src/coreclr/src/vm/runtimecallablewrapper.h#L396-L411

Values:
https://github.com/dotnet/runtime/blob/9d9008ee5ec979543c997616f33de5283b73bad5/src/coreclr/src/vm/runtimecallablewrapper.h#L81-L91

Usage:
https://github.com/dotnet/runtime/blob/9d9008ee5ec979543c997616f33de5283b73bad5/src/coreclr/src/vm/runtimecallablewrapper.cpp#L2050-L2060

https://github.com/dotnet/runtime/blob/9d9008ee5ec979543c997616f33de5283b73bad5/src/coreclr/src/vm/runtimecallablewrapper.cpp#L2424-L2449

**Comment by AaronRobinsonMSFT** [comment]
Spoke offline. CsWinRT has all the needed APIs to implement this themselves and has decided to do that. See https://github.com/microsoft/CsWinRT/issues/282.
