### ISSUE TITLE
[Mono JIT] Extend Linux perf jitdump functionality

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#36774]
mono/mono#17024 A similar improvement as coreclr is needed. The following is copied from https://github.com/dotnet/runtime/issues/13540

Added basic support for generating the Linux perf jitdump format. The initial implementation did not include support for adding:

- [x] Debug info - JIT_CODE_DEBUG_INFO. Provide assembly the line number info to improve annotation.

- [ ] Unwinding info - JIT_CODE_UNWINDING_INFO. Adds dwarf unwind info. This allows/improves recording with the --callgraph dwarf option.

Consider adding these records to improve value of perf jitdump support.

Implementation Notes:

JIT_CODE_DEBUG_INFO & JIT_CODE_UNWINDING_INFO each apply to the next JIT_CODE_LOAD record. This means to properly support multithreading, the information needs to be provide when generating the JIT_CODE_LOAD record

The FEATURE_GDBJIT probably already needs similar info to construct the elf files it passes to gdb. src/vm/gdbjit.cpp may be instructive.

**Comment by SamMonoRT** [comment]
Low priority - Moving to 7.0.0

**Comment by SamMonoRT** [comment]
We'll not get to fixing this. Closing this issue for now.

**Comment by fanyang-mono** [comment]
`JIT_CODE_DEBUG_INFO` was added by #85107. But `JIT_CODE_UNWINDING_INFO` hasn't been added yet.

**Comment by steveisok** [comment]
It's highly unlikely we will be able to get to this. Closing.
