### ISSUE TITLE
Feature Request: Json Schema Validation

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/runtime#36790]
Please consider adding support for JSON Schema Validation as presently we are unable to move away from Newtonsoft JSON and make use of memory/performance improvements of the System.Text.Json as these features are missing.

**Comment by danmosemsft** [comment]
Thanks, this is a duplicate: https://github.com/dotnet/runtime/issues/29887

**Comment by danmosemsft** [comment]
cc @layomia
