### ISSUE TITLE
Add immutable replacements for IPEndPoint, IPAddress and such

### ISSUE THREAD

**Issue by MarcusWichelmann** [dotnet/runtime#36809]
## Background and Motivation

Classes like `IPEndPoint` and `IPAddress` are very useful classes to represent address and endpoint information in applications. But these classes are mutable which makes it very hard to use them inside of immutable classes.

Example for such an immutable class (which is in fact mutable because `IPAddress` is mutable):
```C#
public class ServerNode
{
    public string Name { get; }

    public IPAddress Address { get; }

    public ServerNode(string name, IPAddress address)
    {
        Name = name ?? throw new ArgumentNullException(nameof(name));
        Address = address ?? throw new ArgumentNullException(nameof(address));
    }
}
```
Or imagine a `ConnectParameters` object which stores parameters for creating a TCP connection and should not be modified after having been passed to a `Connect(parameters)` method.
And in future, the problem will become even more visible when trying to use these types together with the new record types coming with C# 9.

## Proposed API

So how do you think about adding `ImmutableIPEndPoint` or `ImmutableIPAddress` classes to the framework, just as you did with `ImmutableList`, `ImmutableDictionary` and so on?

IMO this would be a good addition to C#'s immutability features and could greatly help with designing clean and thread-safe library APIs.

Also, these types are not the only ones which cannot be correctly used in immutable classes. See `Point` as just one example of probably many more.

**Comment by karelz** [comment]
@terrajobst what is our position on adding immutable variants of existing types. This could easily explode. Is that something we want to pursue?
cc @stephentoub

**Comment by scalablecory** [comment]
Can you expand on a scenario where the current types are very hard to use in an immutable context? We have discussed making immutable address types in the past, but this aspect never came up.

**Comment by MarcusWichelmann** [comment]
@scalablecory Here is one piece of code where I tried to build an immutable `ConnectParameters` class where the API consumer will once define all wished parameters for how the connection should later be established: https://github.com/MarcusWichelmann/MarcusW.VncClient/blob/master/src/MarcusW.VncClient/ConnectParameters.cs#L65

Because my code is also handling reconnects and will access this parameters object again and again over time, I do not want that it's properties can be changed later on. To ensure this, I had to add a method to do a deep copy of the `Endpoint` value.

Starting with C# 9, I'm going to refactor this class to be a record instead. But I will still have to create a deep copy, because I cannot make this class fully immutable (because of `IPEndPoint`).

**Comment by MarcusWichelmann** [comment]
One will even have this issue when coding an asynchronous `ConnectAsync(IPEndPoint endpoint)` method that accesses the endpoint multiple times. Because the caller of this method could still have a reference to the `IPEndPoint`, the method implementation can never be sure, that the object hasn't changed. This leads to bad API design where things are possible, which were never intended by the library author and could break some things.

IMHO, the `IPEndPoint` and `IPAddress` classes are also way more often used like a `string` parameter, thats passed to some method, rather than actually used as some object which is intended to be mutated.

Of course, you cannot change the existing classes to be immutable. But immutable types for that would enable programmers to define more clear APIs without having to implement these types themselves (and again, for every library).

**Comment by karelz** [comment]
Triage: We agree that if we were designing it again, making it immutable would be great. However, given where we are -- adding these APIs would be lots of changes, adding new overloads ... overall the cost and complexity does not seem to be worth it.
Unless new scenarios and higher demand emerge, we recommend to close this as Won't Fix ... it is something we will likely have to live with.
