### ISSUE TITLE
when an assembly referenced in .NET Core project won't be loaded?

### ISSUE THREAD

**Issue by Tahatoun** [dotnet/runtime#36801]
I know for example if any type in a referenced assembly is used by the project this assembly won't be loaded. But in some cases we can't eliminate this reference because this reference is used in the build time(for example using a constant in that assembly).Can you please enumerate the different scenarios when we use a referenced assembly and it is not loaded by the project like the example of the constant that I gave. and what we call this type of dependencies please. Is there a way to get this assemblies for a given project. Using reflection for example and specifically Assembly.GetReferencedAssemblies() return assemblies loaded at runtime by the project but don't return this assemblies.

**Comment by jkotas** [comment]
The assembly loader is trying to be as lazy as possible to optimize startup performance. It is not a good idea to depend on whether or when the assembly loader loads the given assembly at runtime. 

Other common cases where you may not see the assembly loaded at runtime are type forwarders or when the calling assembly is AOT compiled.

**Comment by vitek-karas** [comment]
There's one other optimization at play. If you have a program which has a project reference to a class lib and the only thing it uses from it is a static const value, then the compiler (C#) will actually inline the constant value into the program. In that case the program assembly doesn't have an assembly reference to your class lib (as there are no symbols to resolve from it).

In that case, there's no way at runtime to enumerate such dependency - it simply doesn't exist.

On top of that there are other reasons as listed by @jkotas - runtime works hard to avoid loading things unless absolutely necessary.

What is the scenario for this? Why do you need to know the "potentially referenced" assemblies?

**Comment by Tahatoun** [comment]
First, I would like to thank you @vitek-karas and @jkotas for your answers. @vitek-karas  actually I'm developing an application that detect and eliminate all useless references for a given project whether it was a class lib reference or a project reference or a package reference. For example if we have a project A that reference project B which in turn depends on package C and  our project actually only use package C, in this case I will eliminate the reference to package B and replace it with a reference to package C. And before doing this and traverse the graph of dependencies to detect the references to eliminate and the new one to establish, I need to detect those assemblies concretely used by the project and of course I can't take only loaded assemblies at runtime into consideration so I need to know as you said all "potentially referenced" assemblies used either at build or at runtime. for example if we take the case you gave me in your comment if the project use only a static const value of a referenced class lib and my app take only assemblies loaded at runtime into consideration(that we can collect names thanks to the Assembly.GetReferencedAssemblie()method) this reference will be marked as useless and it will be eliminated which is not true and this will cause an error in the next build of the project.

**Comment by vitek-karas** [comment]
I don't know - I think that runtime is "too late" for this, in fact IL (the compiled assemblies) is probably too late as well (due to the above example). This would have to operate at the compiler level. I don't know if the compiler has some way to report this already. Maybe it would be possible to do this with Roslyn analyzer as that should see the world from the compiler's point of view.

**Comment by Tahatoun** [comment]
Thank you @vitek-karas for your feedback.

**Comment by vitek-karas** [comment]
The original question seems to be answered. If you have any other issues around this, please open a new one.
