### ISSUE TITLE
Implement a modern way to invoke Native Libraries

### ISSUE THREAD

**Issue by steskalja** [dotnet/runtime#36812]
Are there any plans to add a way to invoke Native Libraries that is not tied to pInvoke using the structure of declaring the interface, activating it, and then using it. Such as the example below from AdvancedDLSupport:

1. Declare the Interface:
public interface IMyNativeLibrary
{
	long MyNativeGlobal { get; set; }
	int MyNativeMultiply(int a, int b);
	void MyOtherNativeFunction(MyStruct strct, ref MyStruct? maybeStruct);
}

2. Activate it:
const string MyLibraryName = "MyLibrary";

var activator = new NativeLibraryBuilder();
var library = activator.ActivateInterface<IMyNativeLibrary>(MyLibraryName);

3. Use it:
library.MyNativeGlobal = 10;

var result = library.MyNativeMultiply(5, 5);

var myStruct = new MyStruct();
MyStruct? myOtherStruct = null;

library.MyOtherNativeFunction(myStruct, ref myOtherStruct);

This is referenced from: https://github.com/Firwood-Software/AdvancedDLSupport

**Comment by steskalja** [comment]
label:api-suggestion

**Comment by GrabYourPitchforks** [comment]
Have you looked at [`NativeLibrary`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary)?
See also https://github.com/dotnet/runtime/issues/27267.

**Comment by steskalja** [comment]
I have not, I'll attempt that, and if that works I'll close this request
