### ISSUE TITLE
aes encryption low-level interface

### ISSUE THREAD

**Issue by HeMinzhang** [dotnet/runtime#36819]
## Proposed API
About aes encryption low-level interface:

By calling the encryption APIs of different systems (windows, unix) to build a common c # aes encryption API, or more c # encryption APIs, users can use it more flexibly or difficultly.Compatible with more application scenarios.

Source of ideas:
https://github.com/dotnet/runtime/issues/36730#event-3354207135

Because openssl (version openssl-OpenSSL_1_1_1d) uses aes gcm encryption, different iv will generate different ciphertexts that cannot be decrypted.

## Usage Examples

AES_Method
(
byte[] plaintext,
byte[] ciphertext,
byte[] key,
byte[] iv,
.... ...
);
c # aes encryption API, or more c # encryption APIs,

**Comment by bartonjs** [comment]
I'm not clear what your proposal is for.  We already have AES-ECB, AES-CBC, and AES-GCM (all as-provided by the underlying system) in .NET Core.

AES-ECB and AES-CBC are available via

```C#
using (Aes aes = Aes.Create())
{
    // the object is currently in CBC mode, ECB can be utilized via
    //aes.Mode = CipherMode.ECB;
    using (ICryptoTransform encryptor = aes.CreateEncryptor(key, iv))
    {
        ciphertext = encryptor.TransformFinalBlock(plaintext, 0, plaintext.Length);
    }
}
```

AES-GCM requires using a specialized type, since it has more pieces.

```C#
byte[] tag = new byte[16];

using (AesGcm aes = new AesGcm(key))
{
    ciphertext = new byte[plaintext.Length];
    Encrypt(nonce, plaintext, ciphertext, tag);

    // Now ciphertext and tag are both filled in.
}
```

**Comment by vcsjones** [comment]
Perhaps a source of confusion, OpenSSL calls the GCM nonce an "IV" (`EVP_CTRL_GCM_SET_IVLEN`). So, if you have an IV and using AES-GCM, it should be used in the `nonce` parameter of `AesGcm`.

**Comment by HeMinzhang** [comment]
@bartonjs @vcsjones 

Thanks, I continue to test the C # and C ++ sharing aes gcm encryption API.

If the test passes, I will open source, hoping to help those in need.

Currently, I am developing a web api based on aes gcm encryption.

**Comment by HeMinzhang** [comment]
`Input Any Key to run!
Message:This is Test Message 01
, size: 24
key
31-38-45-42-33-38-39-38-34-44-38-32-34-37-37-42-39-39-32-46-33-46-36-42-46-32-37-45-38-42-36-37-

nonceBytes
31-38-45-42-33-38-39-38-34-44-38-32-

DateTime Binary:5248951190946842551
timeBytes
B7-7-C0-4B-4C-5-D8-48-

EncryptData
F-8-6A-1B-EB-F5-49-6B-E6-7C-9A-20-F6-6F-29-85-E3-FB-C4-A7-F7-C-78-33-

tagData
1A-F7-78-91-CB-2A-CF-7A-3D-BE-90-6-58-27-64-6D-

DecryptData
54-68-69-73-20-69-73-20-54-65-73-74-20-4D-65-73-73-61-67-65-20-30-31-A-

DecMessage: This is Test Message 01
;size: 24
请按任意键继续. . .`

`Please input key
31-38-45-42-33-38-39-38-34-44-38-32-34-37-37-42-39-39-32-46-33-46-36-42-46-32-37-45-38-42-36-37-
31-38-45-42-33-38-39-38-34-44-38-32-34-37-37-42-39-39-32-46-33-46-36-42-46-32-37-45-38-42-36-37-
31-38-45-42-33-38-39-38-34-44-38-32-34-37-37-42-39-39-32-46-33-46-36-42-46-32-37-45-38-42-36-37-
Please input nonceBytes
31-38-45-42-33-38-39-38-34-44-38-32-
31-38-45-42-33-38-39-38-34-44-38-32-
31-38-45-42-33-38-39-38-34-44-38-32-
Please input timeBytes
B7-7-C0-4B-4C-5-D8-48-
b7-7-c0-4b-4c-5-d8-48-
b7-7-c0-4b-4c-5-d8-48-
f-8-6a-1b-eb-f5-49-6b-e6-7c-9a-20-f6-6f-29-85-e3-fb-c4-a7-f7-c-78-33-
54-68-69-73-20-69-73-20-54-65-73-74-20-4d-65-73-73-61-67-65-20-30-31-a-
This is Test Message 01


C:\Dev Repos\Site.Safe\AES_GCM_Demo\x64\Debug\CPP_GCM.exe (process 1252) exited with code 0.
Press any key to close this window . . .
`

Thanks a lot, I got the correct result

@bartonjs 
@vcsjones

**Comment by HeMinzhang** [comment]
[CsharpAndCplusplusGCMencryptDemo](https://github.com/HeMinzhang/CsharpAndCplusplusGCMencryptDemo)
