### ISSUE TITLE
runtime-coreclr outerloop pipeline is broken

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#36825]
Since https://github.com/dotnet/runtime/pull/35426, the runtime-coreclr outerloop pipeline has been failing since it hasn't been able to find a `dotnet` to execute with.

cc: @jashook @trylek @nattress

**Comment by nattress** [comment]
This is failing on the `Linux_musl` test legs. We're requesting this runtime on those legs:
```
DotNetCliVersion: 5.0.0-preview.5.20230.9
DotNetCliPackageType: runtime
HelixRuntimeRid: linux-arm64
```

Should that be `linux-musl-arm64` instead?

Sample Helix worker failure. It added dotnet correlation payload to the path but it seems there's not actually a dotnet in there:
```
+ export 'PATH=/root/helix/work/correlation/dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ dotnet /root/helix/work/correlation/xunit.console.dll JIT/HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait 'TestGroup=JIT.HardwareIntrinsics'
/root/helix/work/correlation/scripts/e6cf474c39824aa89ddc96fed596e57d/execute.sh: line 12: dotnet: not found
```

**Comment by jkoritzinsky** [comment]
Yes, it should be `linux-musl-x64`. The "dotnet not found" issue is likely because it can't load the libc it's linked against (glibc instead of musl),
