### ISSUE TITLE
System.Text.RegularExpressions failures on android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36848]
## Various tests fail for android:

- [ ] RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 2)
- [ ] RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 256)
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;az-Latn-AZ\&quot;, pattern: \&quot;ı\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;tr-TR\&quot;, pattern: \&quot;ı\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])

[System.Text.RegularExpressions.log](https://github.com/dotnet/runtime/files/6260416/System.Text.RegularExpressions.log)

## The following tests are skipped with `Condition(s) not met: "IsSupported"`
- [ ] RegexMatchTests.Match_DefaultTimeout_Throws(options: None)
- [ ] RegularExpressions.Tests.RegexMatchTests.Match_DefaultTimeout_Throws(options: Debug)
- [ ] RegularExpressions.Tests.RegexMatchTests.Match_DefaultTimeout_Throws(options: Compiled | Debug)
- [ ] RegexMatchTests.Match_DefaultTimeout_Throws(options: Compiled)
- [ ] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries
- [ ] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Second_drops_first
- [ ] RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw
- [ ] RegexCacheTests.Ctor_Cache_Uses_culture_and_options
- [ ] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Shrink_cache
- [ ] RegexConstructorTests.StaticCtor_InvalidTimeoutObject_ExceptionThrown
- [ ] System.Text.RegularExpressions.Tests.RegexConstructorTests.Ctor_PatternInName
- [ ] RegexConstructorTests.StaticCtor_InvalidTimeoutRange_ExceptionThrown

**Comment by steveisok** [comment]
re: the Android failures, the `tr-TR` does not return the results we expect as it pertains to case and a few other scenarios.  

@mdh1418 can you re-run the `IsSupported` tests as I suspect this may be feature flag related.

**Comment by mdh1418** [comment]
@steveisok The tests skipped with `IsSupported` are still being skipped with `IsSupported`

**Comment by steveisok** [comment]
Ok, that's expected.  I think we can close this issue.

**Comment by mdh1418** [comment]
@steveisok Though those are not supported, there are still 2 actual failures here
`RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture`
`System.Text.RegularExpressions.Tests.RegexGroupTests.Groups`

Stil fail for 
```
Test collection for System.Text.RegularExpressions.Tests.RegexGroupTests
System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \"tr-TR\", pattern: \"ı\", input: \"I\", options: IgnoreCase, expectedGroups: [\"I\"])
    Assert.True() Failure\nExpected: True\nActual:   False
System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \"az-Latn-AZ\", pattern: \"ı\", input: \"I\", options: IgnoreCase, expectedGroups: [\"I\"])
    Assert.True() Failure\nExpected: True\nActual:   False

Test collection for System.Text.RegularExpressions.Tests.RegexCultureTests
System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 2)
    Assert.All() Failure: 2 out of 2 items in the collection did not pass.\n[1]: Item: Iıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in xunit.assert.dll:token 0x600000d+0x19\n        at Xunit.Assert.False(Boolean condition) in xunit.assert.dll:token 0x600000a+0x6\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime_droid/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 90\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in xunit.assert.dll:token 0x6000012+0x28\n[0]: Item: Iıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in xunit.assert.dll:token 0x600000d+0x19\n        at Xunit.Assert.False(Boolean condition) in xunit.assert.dll:token 0x600000a+0x6\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime_droid/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 90\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in xunit.assert.dll:token 0x6000012+0x28
System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 256)
    Assert.All() Failure: 2 out of 2 items in the collection did not pass.\n[1]: Item: IıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in xunit.assert.dll:token 0x600000d+0x19\n        at Xunit.Assert.False(Boolean condition) in xunit.assert.dll:token 0x600000a+0x6\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime_droid/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 90\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in xunit.assert.dll:token 0x6000012+0x28\n[0]: Item: IıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in xunit.assert.dll:token 0x600000d+0x19\n        at Xunit.Assert.False(Boolean condition) in xunit.assert.dll:token 0x600000a+0x6\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime_droid/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 90\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in xunit.assert.dll:token 0x6000012+0x28

```

**Comment by steveisok** [comment]
Yeah, I don't believe there is anything we can do to make them pass on Android.

**Comment by mdh1418** [comment]
Currently they're marked with ActiveIssues linked to this issue. I'm curious what is inherent from these tests that prevent them from passing on Android, and when we find out, should some PlatformNotSupportedException error then be generated for this case. That way, we can use `SkipOnPlatform` and provide the inherent reason. In any case, it seems like it can be investigated more in 7.0
