### ISSUE TITLE
Add a string overload for HMAC* constructors

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#36844]
## Background and Motivation

Make it easier, more expressive and more straight forward for a developer to initialize a HMAC* class by passing in a string directly without first having transform the string into a byte array.

## Proposed API
A constructor overload for the HMAC* classes that takes a `string` as the input parameter for the key.

```diff
namespace System.Security.Cryptography
{
    public class HMACSHA256 : HMAC
        public HMACSHA256(byte[] key);
+        public HMACSHA256(string key);
     }
```

## Usage Examples

``` C#
var hmac = new HMACSHA256("my secret key");
```

**Comment by GrabYourPitchforks** [comment]
That's not really how HMACs are intended to be used. [RFC 2104](https://tools.ietf.org/html/rfc2104), which defines the HMAC mechanism, explicitly states that keys are provided as bytes.

Adding a string constructor harms us in two ways. First, it adds a .NET Framework-specific opinion on top of the official RFC. (How do we convert chars to bytes in a standards-compliant fashion?) Second, it could actually harm the cryptographic security of the HMAC construction. A sequence of bytes used as an HMAC key is expected to have high entropy. Strings, however, tend to represent human-readable text and often have very low entropy. Encouraging use of low-entropy keys in HMAC routines ultimately will lead to reduced security throughout the .NET ecosystem.

If you need to produce a one-way digest of a password, consider using a type like [`Rfc2898DeriveBytes`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes). The RFC 2898 construction is more secure than a simple HMAC for this scenario.

**Comment by vanillajonathan** [comment]
I am not interested in using the HMAC-* classes for password hashing. I want to use it for signing a message with a pre-shared secret so that I can send the message along with the hash to the recipient who will be able to prove that the message have not been tampered with by computing the received message with the pre-shared secret and compare the hashes.

The pre-shared secret would probably be shared as a string. Since its not meant for a user to authenticate with it by physically entering the secret as a password, it would be fairly long (32 characters or more) and have fairly good entropy (mixed cased letters, numbers, possibly other characters).

**Comment by bartonjs** [comment]
String-based keys provide too much confusion.  Is it hex parsing, or a text encoding?

While the discussion for hashing strings can continue in #36843, accepting a string as a key to an HMAC or an encryption algorithm isn't something that would provide enough value to offset the cost of ambiguity.
