### ISSUE TITLE
System.Data.Common.Tests fail on android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36841]
These tests fail on android:

- [ ] System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeNameTest
- [ ] System.Data.Common.DbProviderFactoriesTests.TryGetFactoryTest
- [ ] DbProviderFactoriesTests.RegisterFactoryWithAssemblyQualifiedNameTest
- [ ] System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithInstanceTest
- [ ] System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithBadInvariantNameTest
- [ ] System.Data.Common.DbProviderFactoriesTests.GetProviderInvariantNamesTest
- [ ] System.Data.Common.DbProviderFactoriesTests.GetFactoryWithDbConnectionTest
- [ ] DbProviderFactoriesTests.ReplaceFactoryWithRegisterFactoryWithTypeTest
- [ ] System.Data.Common.DbProviderFactoriesTests.UnregisterFactoryTest
- [ ] System.Data.Common.DbProviderFactoriesTests.GetFactoryWithInvariantNameTest
- [ ] System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeTest
- [ ] DbProviderFactoriesTests.RegisterFactoryWithWrongAssemblyQualifiedNameTest
- [ ] System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithWrongTypeTest
- [ ] System.Data.Common.DbProviderFactoriesTests.GetFactoryWithDataRowTest
- [ ] System.Data.Tests.FacadeTest.TestSystemData(typeName: \&quot;Microsoft.SqlServer.Server.SqlMetaData\&quot;)

All fail with:
```
System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

or 

```
System.TypeLoadException : Could not load type 'Microsoft.SqlServer.Server.SqlMetaData' from assembly 'System.Data, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by ajcvickers** [comment]
Moving to the SqlClient area since the tests are attempting to load SQL-specific assemblies.

**Comment by mdh1418** [comment]
These are no longer failing on x64, x86, or arm64 based on https://github.com/dotnet/runtime/pull/50095
