### ISSUE TITLE
GC/API/GC/AddThresholdTest / Linux ARM64 fails with "newly-allocated dummy ended up in gen 1"

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#36850]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=655916&view=ms.vss-test-web.build-test-results-tab&runId=20359696&resultId=102255&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Configuration: *Linux arm64*

Diagnostics:

<pre>
  Starting:    GC.API.XUnitWrapper
    GC/API/GC/AddThresholdTest/AddThresholdTest.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/GC/API/Reports/GC.API/GC/AddThresholdTest/AddThresholdTest.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun AddThresholdTest.dll ''
      Warning: newly-allocated dummy ended up in gen 1
      Warning: newly-allocated dummy ended up in gen 1
      Warning: newly-allocated dummy ended up in gen 1
      Warning: newly-allocated dummy ended up in gen 1
      2 2
      ThresholdTest Failed
      
      Test Failed
      Expected: 100
      Actual: 1
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/GC/API/GC/AddThresholdTest/AddThresholdTest.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(140,0): at GC_API._GC_AddThreoldTest_AddThreoldTest_._GC_AddThresholdTest_AddThresholdTest_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/GC/API/Reports/GC.API/GC/AddThresholdTest/AddThresholdTest.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun AddThresholdTest.dll ''
        Warning: newly-allocated dummy ended up in gen 1
        Warning: newly-allocated dummy ended up in gen 1
        Warning: newly-allocated dummy ended up in gen 1
        Warning: newly-allocated dummy ended up in gen 1
        2 2
        ThresholdTest Failed
        
        Test Failed
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/GC/API/GC/AddThresholdTest/AddThresholdTest.sh
  Finished:    GC.API.XUnitWrapper
</pre>

**Comment by Maoni0** [comment]
yeah, this is because the impl of AMP/RMP changed with [36767](https://github.com/dotnet/runtime/pull/36767). tests like this are of very low value...I'll just delete it.

**Comment by jkotas** [comment]
The test is still disabled in https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/issues.targets#L119 against this issue. Delete the test before closing this?

**Comment by Maoni0** [comment]
tests deleted, closing
