### ISSUE TITLE
Port Patches from the sourceBuild to Runtime

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#36858]
This is to track all the patches that we need to port to runtime
patch list https://github.com/dotnet/source-build/tree/release/3.1/patches

coreclr
- [ ] Allow-separate-tool-and-SDK-directories.patch
- [ ] Conditionally-override-PackageVersion-properties.patch
- [x] Exclude-optdata-from-source-build.patch https://github.com/dotnet/runtime/pull/36861
- [x] Remove-Helix-Dependency.patch // not using in the build

corefx
- [x] Enable-sourcelink-in-source-build.patch  // will always be present during build
- [ ] Enable-tests-for-CoreFX-in-s-b.patch  // not building or running tests for sourcebuild
- [ ] don-t-call-dotnet-without-path.patch
- [x] Conditionally-restore-runtime-native-SystemDataSqlCl.patch // no longer using this dependency
- [x] Enable-build-on-hosted-arm64.patch // already done in master
- [x] add-entries-for-new-FreeBSD-releases-41794.patch // already in master
- [ ] do-not-fail-on-test-chmod.patch // not building or running tests for sourcebuild
- [x] remove-unneeded-feeds.patch // already deleted from master

Core-setup
- [ ] Pin-NuGetProjectModel-to-a-specific-version.patch
- [x] Try-ExcludeFromSourceBuild-in-windowsdesktop.patch // no longer present
- [ ] Don-t-call-dotnet-without-a-path.patch
- [ ] Use-pinned-version-of-MSBuild-reference-assemblies.patch
- [x] Enable-building-for-arm64-on-arm64.patch // already in master
- [x] add-freebsd-support.patch // already in master 
- [x] Fix-OSGroup-on-FreeBSD.patch https://github.com/dotnet/runtime/pull/36861
- [x] Remove-fallback-folder-to-pick-up-correct-libhostpol.patch // already not doing it
- [x] remove-unneeded-feeds.patch // not present in master

cc @ericstj @ViktorHofer @safern

**Comment by Anipik** [comment]
@dseefeld can you take a look if any of the unmarked patches need to be ported to runtime ?

**Comment by dseefeld** [comment]
> @dseefeld Dan Seefeldt FTE can you take a look if any of the unmarked patches need to be ported to runtime ?

@Anipik I am in progress on getting preview4 runtime building with source-build.  Of the unmarked patches above, the only one I'm still using is do-not-fail-on-test-chmod.patch

**Comment by ViktorHofer** [comment]
What is the `do-not-fail-on-test-chmod` patch for? Just curious as I might have already fixed a chmod error which sounds related.

**Comment by dseefeld** [comment]
> What is the `do-not-fail-on-test-chmod` patch for? Just curious as I might have already fixed a chmod error which sounds related.

Here's a link to the patch: https://github.com/dotnet/source-build/blob/master/patches/runtime/0004-do-not-fail-on-test-chmod.patch

**Comment by ViktorHofer** [comment]
Yes, that one is already fixed in P4. I added the condition if the current OS is not Windows: https://github.com/dotnet/runtime/blob/release/5.0-preview4/src/libraries/restore/runtime/runtime.depproj#L68.

**Comment by ViktorHofer** [comment]
@Anipik what's the status on this?

**Comment by Anipik** [comment]
We can close this one
