### ISSUE TITLE
FreeBSD build legs sometime crashes when running msbuild

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#36860]
```
uilding step 'Restore product binaries (build tests)' via "/__w/1/s/eng/common/msbuild.sh"  --warnAsError false /__w/1/s/src/coreclr/tests/build.proj /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount "/flp:Verbosity=normal;LogFile=/__w/1/s/artifacts/log/Restore_Product.FreeBSD.x64.Release.log" "/flp1:WarningsOnly;LogFile=/__w/1/s/artifacts/log/Restore_Product.FreeBSD.x64.Release.wrn" "/flp2:ErrorsOnly;LogFile=/__w/1/s/artifacts/log/Restore_Product.FreeBSD.x64.Release.err" /t:BatchRestorePackages /p:TargetArchitecture=x64 /p:Configuration=Release /p:TargetOS=FreeBSD /nodeReuse:false    
  [01:17:00.84] Restoring all packages...
  Segmentation fault (core dumped)
/__w/1/s/src/coreclr/tests/build.proj(52,5): error MSB3073: The command ""/__w/1/s/.dotnet/dotnet" restore -r freebsd-x64 /__w/1/s/src/coreclr/tests/scripts/scripts.csproj  /p:SetTFMForRestore=true /p:TargetOS=FreeBSD /p:TargetArchitecture=x64 /p:Configuration=Release " exited with code 139.

Build FAILED.

/__w/1/s/src/coreclr/tests/build.proj(52,5): error MSB3073: The command ""/__w/1/s/.dotnet/dotnet" restore -r freebsd-x64 /__w/1/s/src/coreclr/tests/scripts/scripts.csproj  /p:SetTFMForRestore=true /p:TargetOS=FreeBSD /p:TargetArchitecture=x64 /p:Configuration=Release " exited with code 139.
    0 Warning(s)
    1 Error(s)
```

I've seen this a couple times only. I tried using `runfo search-buildlog` because in the timeline the error is shown as: `Bash exited with code 1`

Happened in: https://github.com/dotnet/runtime/pull/36855
https://dev.azure.com/dnceng/public/_build/results?buildId=656450&view=results

cc: @wfurt @dotnet/runtime-infrastructure

**Comment by wfurt** [comment]
It would be nice to get the core file. I'm not sure if have that enabled for build. (I know we do for tests)

**Comment by ViktorHofer** [comment]
@MattGal do you know if we capture dumps during the build?

**Comment by MattGal** [comment]
> @MattGal do you know if we capture dumps during the build?

Actually yes... it requires Kusto access to find them, but they're normal helix machines so if the core got written to the right spot, we'll have it. Checking that build now.

**Comment by MattGal** [comment]
@ViktorHofer unfortunately the build listed above is deleted, so I can't get its orchestration id back. 

If it happens again, if you go to https://dev.azure.com/dnceng/public/_apis/build/builds/{build id} , copy off the orchestration plan id, and note that down we'll have a durable GUID that lets us find cores if they were uploaded.  Otherwise someone pushes a commit and the build and its metadata disappears.

**Comment by ViktorHofer** [comment]
Thanks Matt. FYI @dotnet/runtime-infrastructure in case you encounter a FreeBSD crash during building.

**Comment by jaredpar** [comment]
Closing as can't find any recent occurrences.
