### ISSUE TITLE
System.Console tests failing on iOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36878]
### System.Console.Tests:
- [ ] TermInfo.TermInfoVerification
- [ ] TermInfo.VerifyInstalledTermInfosParse
- [ ] TermInfo.TryingToLoadTermThatDoesNotExistDoesNotThrow
- [ ] TermInfo.VerifyTermInfoSupportsNewAndLegacyNcurses

[XML of failing tests](https://github.com/dotnet/runtime/files/4771719/xunit-test-ios-simulator-64-20200611_185459.txt)

## PlatformNotSupportedException
CancelKeyPressTests.CanAddAndRemoveHandler
ReadAndWrite.OutputEncodingPreamble
ReadAndWrite.ReadAndReadLine
ReadAndWrite.OutputEncoding
SetIn.SetInReadLine
SetIn.SetInThrowsOnNull
Color.RoundtrippingColor
Color.RedirectedOutputDoesNotUseAnsiSequences
Color.InvalidColors
ConsoleEncoding.TestEncoding
ConsoleEncoding.TestValidEncodings
SyncTextReader.ReadAsync
SyncTextReader.ReadBlockAsync
SyncTextReader.ReadLineAsync
SyncTextReader.Read
SyncTextReader.ReadToEnd
SyncTextReader.ReadBlock
SyncTextReader.Peek
SyncTextReader.ReadToEndAsync
TimeOut.OpenStandardXXX_ReadTimeOut
TimeOut.OpenStandardXXX_WriteTimeOut
TimeOut.OpenStandardXXX_CanTimeOut
ThreadSafety.SetStandardXXXCanBeCalledConcurrently
ThreadSafety.ReadMayBeCalledConcurrently
ThreadSafety.OpenStandardXXXCanBeCalledConcurrently
WindowAndCursorProps.GetCursorPosition_Invoke_ReturnsExpected
WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop
WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException
WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException
WindowAndCursorProps.LargestWindowHeight_UnixGet_ReturnsExpected
WindowAndCursorProps.WindowHeight_GetUnix_Success
WindowAndCursorProps.WindowWidth_GetUnix_Success
WindowAndCursorProps.BufferWidth_GetUnix_ReturnsWindowWidth
WindowAndCursorProps.SetCursorPosition_Invoke_Success
WindowAndCursorProps.CursorSize_GetUnix_ReturnsExpected
WindowAndCursorProps.LargestWindowWidth_UnixGet_ReturnsExpected
WindowAndCursorProps.BufferHeight_GetUnix_ReturnsWindowHeight
WindowAndCursorProps.CursorTop_Set_GetReturnsExpected
WindowAndCursorProps.CursorLeft_Set_GetReturnsExpected

**Comment by danmosemsft** [comment]
Every single failure is `PlatformNotSupportedException Operation is not supported on this platform`.

**Comment by mdh1418** [comment]
Reran the tests on iOS and ignored PlatformNotSupportedExceptions this time. Updated this issue again, but the failures are `System.ArgumentNullException : Value cannot be null. (Parameter 'type')` which don't seem iOS specific.

**Comment by danmosemsft** [comment]
```
System.ArgumentNullException : Value cannot be null. (Parameter 'type')]]></message>
          <stack-trace><![CDATA[   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at TermInfo.ReadTermInfoDatabase(String term)
   at TermInfo.TermInfoVerification(String termToTest, String expectedForeground, String expectedBackground, Int32 colorValue)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
```c#
    private const string TerminfoType = "System.TermInfo";
    private const string TerminfoDatabaseType = TerminfoType + "+Database";
... ...
MethodInfo readDbMethod = typeof(Console).GetTypeInfo().Assembly.GetType(TerminfoDatabaseType).GetTypeInfo().GetDeclaredMethods(ReadDatabaseMethod).Where(m => m.GetParameters().Count() == 1).Single();
```
I guess `GetType` failed on `System.TermInfo+Database`

**Comment by danmoseley** [comment]
@mdh1418 is this still actually an issue?
