### ISSUE TITLE
Single file bundle extraction misses feedback

### ISSUE THREAD

**Issue by Lakritzator** [dotnet/runtime#3687]
I have provided a Greenshot preview version to a couple of users, to detect any issues with the direction we are going. I was especially interested in the single file bundle functionality, as this could provide a very quick feedback.

When watching two of the users to see if they like the UX. My first observation was that they, seconds after clicking the Greenshot.exe icon stored in their download order, click again. The users said that as nothing is happening, they assumed the double-click was somehow ignored / lost and they wanted to make sure Greenshot started.

What I got back from this:

- The dotnet core published single bundle exe takes a **long** time extracting, which is not really visible -> can't do anything myself here, so that is where this issue comes into play.
- When after many seconds Greenshot finally starts, it's visible in the system tray but only if the user doesn't collapse the icon -> Greenshot should "tell" that it's started (with an option to turn it off) to make sure the user knows.

My hope is that you might be able to provide some kind of feedback, that the system is doing something. My first **suggestion** is a small window just telling the user to wait with an icon (sand-hour), this would prevent the need for translations.

## Steps to reproduce
Publish a single-exe Windows WPF application, it should be >140MB
double-click the icon to start the application
now wait... and notice that you don't know what happens

## Expected  behavior
Somehow see that the system is starting the application

## Actual behavior
Nothing until the application is started, and only if the application shows something.

## Environment data
dotnet core 3.0.100-preview8-013289

Additional hints:
In https://github.com/dotnet/core-setup/issues/7070 there was an issue with McAfee (which actuall I was facing too) where the solution is in https://github.com/dotnet/core-setup/pull/7135 it's visible that in some cases the extraction process takes > 45 seconds. Now this is not the main issue, it takes as long as it needs, but the fact that this is not visible it why I created this issue.

P.S.
There are other issues with the whole life-cycle for Single-Exes, one is the cleanup process when the user downloads multiple versions. But this is something for other issues...

**Comment by elinor-fung** [comment]
In .NET 5+, single-file applications no longer need to extract all the files to a directory. I going to close this against https://github.com/dotnet/runtime/issues/50081, which is the same kind of request around feedback / a splash screen but with the newer single-file experience.
