### ISSUE TITLE
MultipartFormDataContent in System.Net.Http 4.3.* package does not allow to read entire content from the stream

### ISSUE THREAD

**Issue by vhorodnii** [dotnet/runtime#36873]
### Description

Hi, I want to read MultipartFormDataContent to string and use it to generate a request signature. My code looks like the following snippet of code:

var data = new MultipartFormDataContent()
{
    { new StringContent(JsonConvert.SerializeObject(new { Name = "name" }), Encoding.UTF8, "application/json"), "Properties" },
};

var stream = await data.ReadAsStreamAsync();

var bufferSize = (int)stream.Length;

byte[] buffer = new byte[bufferSize];
await stream.ReadAsync(buffer, 0, bufferSize);

var str = Encoding.UTF8.GetString(buffer);

However, 'str' variable does not contain entire content. It returns only the first line of content like: `--48d5a28a-7a51-4c4b-a7f6-c3825b000774` . I found a workaround to read stream content in a while loop but I guess it has to work without looping.

### Configuration

To replicate the issue I used .NET Framework 4.7 console application. I installed System.Net.Http 4.3.4 only and all required dependencies.

### Regression?

I've tried to use System.Net.Http 4.1.4 and it works as expected (reads entire content).

**Comment by scalablecory** [comment]
> I found a workaround to read stream content in a while loop but I guess it has to work without looping.

`Stream.ReadAsync()` makes no guarantee to maximally fill the buffer supplied to it. Looping is the correct usage here.

You might consider using `HttpContent.ReadAsByteArrayAsync()` or `HttpContent.ReadAsStringAsync()` here to shortcut having to work with the `Stream` directly.
