### ISSUE TITLE
System.Globalization.CalendarsWithConfigSwitch.Tests fails on iOS and Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36883]
### System.Globalization.CalendarsWithConfigSwitch.Tests:
- [ ] System.Globalization.Tests.CalendarTests.TestJapaneseCalendarDateParsing

The reason why this test fails is that we do not yet support runtimeconfig.json.  If we did, then we could add an entry that passes the test `"System.Globalization.EnforceJapaneseEraYearRanges": true`

**Comment by safern** [comment]
Thanks @mdh1418 for opening the issue. Let’s make sure that the issues we open for the iOS/Android effort are part of the project to “Getting libraries passing on Mono/devices”

**Comment by mdh1418** [comment]
@safern Oh awesome! I didn't know there was that project. Was going to make a parent issue that would track all of these after I finished making the issues. Will be adding my issues to that project from now on.

**Comment by steveisok** [comment]
@mdh1418 Since we have runtimecfg support, this should now work.  Can you see that the "System.Globalization.EnforceJapaneseEraYearRanges": true switch is set and retest?

**Comment by mdh1418** [comment]
No longer fails on iOSSimulator (x64) or Android (x64) as of ec3f9fa03f7
