### ISSUE TITLE
System.Diagnostics.Debug.Tests fail on iOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36882]
### System.Diagnostics.Debug.Tests
System.Diagnostics.Tests.DebugTestsUsingListeners.Debug_WriteLineNull_IndentsEmptyStringProperly
System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected
System.Diagnostics.Tests.DebugTestsUsingListeners.Trace_ClearTraceListeners_StopsWritingToDebugger
System.Diagnostics.Tests.DebugTestsUsingListeners.TraceWriteLineIf

```
System.Diagnostics.Debug.Tests.dll   Failed: 6

System.Diagnostics.Debug
System.Diagnostics.Tests.DebugTestsUsingListeners.Debug_WriteLineNull_IndentsEmptyStringProperly
    Assert.Equal() Failure\n             ↓ (pos 3)\nExpected:    \\n\nActual:       \\n\n             ↑ (pos 3)
System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected(indentLevel: 0, expectedIndentLevel: 0)
    Assert.Equal() Failure\n             ↓ (pos 3)\nExpected:    pizza\\n\nActual:       pizza\\n\n             ↑ (pos 3)
System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected(indentLevel: 1, expectedIndentLevel: 1)
    Assert.Equal() Failure\n             ↓ (pos 3)\nExpected:    pizza\\n\nActual:       pizza\\n\n             ↑ (pos 3)
System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected(indentLevel: -1, expectedIndentLevel: 0)
    Assert.Equal() Failure\n             ↓ (pos 3)\nExpected:    pizza\\n\nActual:       pizza\\n\n             ↑ (pos 3)
System.Diagnostics.Tests.DebugTestsUsingListeners.Trace_ClearTraceListeners_StopsWritingToDebugger
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: pizza\nActual:      pizza\n          ↑ (pos 0)
System.Diagnostics.Tests.DebugTestsUsingListeners.TraceWriteLineIf
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: category: 5\\n\nActual:      category: 5\\n\n          ↑ (pos 0)

**Comment by tommcdon** [comment]
@steveisok would you mind adding a milestone to this issue?

**Comment by noahfalk** [comment]
@marek-safar - I notice this issue has been unaddressed for ~7 months. Is it tracking work you plan to do or can it be closed?

I ask because Tom's team has triage queries that include anything tagged System.Diagnostics but I don't think we have any actionable work here. We can update our queries with exclusions if needed. Thanks!

**Comment by steveisok** [comment]
Yes, we are planning iOS diagnostics work for .net 6.

**Comment by lateralusX** [comment]
@mdh1418 I have run this test suite on iOSSimulator, Full AOT LLVM, and it passed, did you only repro this on physical iOS device?

**Comment by lateralusX** [comment]
@mdh1418 Looks like failures on MacCatalyst and tvOS are not related to re-enabled tests, https://dev.azure.com/dnceng/public/_build/results?buildId=1906721&view=ms.vss-test-web.build-test-results-tab, so looks like this issue has been resolved and we could re-enable the tests and close this issue.
