### ISSUE TITLE
System.Memory.Tests Crashes on tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36885]
Crashes/Hangs on GetArrayDataReference_NullInput_ThrowsNullRef

**Comment by GrabYourPitchforks** [comment]
All of the failing tests involve globalization-related code paths. I suspect whatever is causing https://github.com/dotnet/runtime/issues/36883 is also causing this.

**Comment by mdh1418** [comment]
System.Memory.Tests no longer fails on iOS, but the suite crashes consistently on tvOS as of #49917

**Comment by adamsitnik** [comment]
> I suspect whatever is causing #36883 is also causing this.

#36883  has been recently closed as it does not repro anymore: https://github.com/dotnet/runtime/issues/36883#issuecomment-882910858

I've sent #56724 to see if it passes now
