### ISSUE TITLE
System.ServiceModel.Syndication.Tests fail on iOS, tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36898]
### System.ServiceModel.Syndication.Tests
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.DiffAtomNsTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Rss
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.DiffRssNsTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Atom_DateTimeParser
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Write_RSS_Feed_
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.AtomEntryPositiveTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.DiffRssVersionTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.RssEntryPositiveTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Write_RSS_Feed
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.AtomEntryPositiveTest_write
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Write_Atom_Feed
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Write_RSS_Use_Optional_Element_Properties
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.RssFeedPositiveTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.NoRssVersionTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.AtomFeedPositiveTest
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Rss_DateTimeParser
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Rss_WrongDateFormat
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_RSS_Optional_Elements
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Rss_TestDisjointItems
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Write_RSS_With_Optional_Elements
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Rss_UriParser
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Write_Atom_Feed_
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Atom_UriParser
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Load_Atom
- [ ] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Atom_TestDisjointItems
[XML of test failures](https://github.com/dotnet/runtime/files/4669937/test_failures.txt)

**Comment by danmosemsft** [comment]
`System.IO.DirectoryNotFoundException : Could not find a part of the path '/Users/mdhwang/Library/Developer/CoreSimulator/Devices/AB8A2904-AD12-4CCD-9072-445DC2401264/data/Containers/Bundle/Application/CE9907CF-5259-4D0E-A076-51556A027E06/System.ServiceModel.Syndication.Tests.app/TestFeeds/FailureFeeds/diff_atom_ns.xml`

**Comment by mdh1418** [comment]
No longer fails
