### ISSUE TITLE
Cannot export certificate data even with X509KeyStorageFlags.Exportable

### ISSUE THREAD

**Issue by SCLDGit** [dotnet/runtime#36899]
If I export an X509Certificate2 using

`var myCert = p_certificate.Export(X509ContentType.Pkcs12, SomeSecureString);`

then save that to a file using

`File.WriteAllBytes(filePath, myCert);`

if I then create a new X509Certificate2 object

`var newCert = new X509Certificate2(p_keyFilePath, p_keyFilePassword, X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);`

and try to export the private key

`var loadedRsa = newCert.GetRSAPrivateKey();`
`var loadedPrivate = loadedRsa.ExportRSAPrivateKey();`

I get

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The requested operation is not supported.

Any ideas or workarounds would be much appreciated.

**Comment by SCLDGit** [comment]
Update: The same code runs without any issues on Linux

**Comment by vcsjones** [comment]
I'm unable to reproduce this using the code below. Also, some questions:

1. Where does `p_certificate` come from in the first place? Another PFX that is loaded from disk, or the certificate store? 
2. What is the complete stack trace, can you perhaps create a sample program that reproduces the issue?
3. Does it reproduce if you use `EphemeralKeySet` instead of persistent?

```csharp
using System;
using System.IO;
using System.Security.Cryptography.X509Certificates;

namespace scratch {
    class EntryPoint {
        static void Main() {
            // Assume "foo.pfx" is a PFX that is already on disk.
            X509Certificate2 first = new X509Certificate2("foo.pfx", "test", X509KeyStorageFlags.Exportable);
            var export = first.Export(X509ContentType.Pkcs12, "yagni");
            File.WriteAllBytes("exported.pfx", export);
            X509Certificate2 second = new X509Certificate2("exported.pfx", "yagni", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);
            second.Export(X509ContentType.Pkcs12, "yagni");
            var loadedRsa = second.GetRSAPrivateKey();
            var loadedPrivate = loadedRsa.ExportRSAPrivateKey();
            Console.WriteLine(Convert.ToBase64String(loadedPrivate));
        }
    }
}
```

**Comment by SCLDGit** [comment]
The pasted code fails here in the same way on ExportRSAPrivateKey();

Full stacktrace is:

   at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
   at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSA.WritePkcs1PrivateKey()
   at System.Security.Cryptography.RSA.ExportRSAPrivateKey()
   at CryptoPlayground.Program.Main(String[] args) in C:\Users\UserName\Documents\Development\Test Projects\CryptoPlayground\CryptoPlayground\Program.cs:line 24

They original cert in question is generated by OpenSSL via the DidiSoft.OpenSsl library.

The issue persists even with Ephemeral set.

I can attach a .pfx where this fails if that's of any use.

**Comment by vcsjones** [comment]
> I can attach a .pfx where this fails if that's of any use.

Assuming it's a key you don't care about, I think that would be helpful.

**Comment by SCLDGit** [comment]
The key is just the one generated by our test, not being used for any kind of security. It's attached here. Had to put it in a zip to make GitHub happy.
[myKey.zip](https://github.com/dotnet/runtime/files/4670210/myKey.zip)

**Comment by vcsjones** [comment]
@SCLDGit that key appears to have a password on it, and it isn't null/empty string. Can you share it?

Another Q: Are you using .NET Core 3.1?

**Comment by SCLDGit** [comment]
Ah yes, sorry, it's just "P@ssw0rd" for testing. Yes, this is on .NET Core 3.1

**Comment by vcsjones** [comment]
Now I can reproduce it, thanks. There is something about the contents of the PFX that are important to reproducing the problem. Now to find out what. 😄

**Comment by SCLDGit** [comment]
I'm all ears! Happy to do some more testing on my side if you need anything else. Seemed odd to me that Linux is perfectly happy with it but Windows barfs on it.

**Comment by bartonjs** [comment]
Just said it at https://github.com/dotnet/runtime/issues/26031#issuecomment-632912957, but here it is again in a different context:

Exportable ends up meaning two different things depending on if the key got loaded into Windows CAPI or Windows CNG.  For CAPI it means ... exportable -- ExportParameters will work, and exporting as a PFX will work.  For CNG it ends up meaning "exportable if encrypted", so PFX export works, and ExportEncryptedPkcs8PrivateKey works... but ExportParameters and ExportPkcs8PrivateKey do not.

One work-around is to do something like

```C#
using (RSA tmp = RSA.Create())
using (RSA key = cert.GetRSAPrivateKey())
{
    PbeParameters pbeParameters = ...;
    tmp.ImportPkcs8PrivateKey(key.ExportPkcs8PrivateKey(pwd, pbeParameters), pwd);
    return tmp.ExportRSAPrivateKey();
}
```

We -could- do something like that in the platform when we get an error, but we've thus far resisted doing it.

**Comment by vcsjones** [comment]
@SCLDGit 

I can reproduce this with my own PFX now, and I don't think there is anything particular about the PFX that is the problem. Rather, it's that when Windows exports a PFX, it includes CSP key ID. So when you re-import the certificate, it gets that key handle.

I wonder then, if this works for you?

```csharp
var exported = loadedRsa.ExportEncryptedPkcs8PrivateKey("temp", new PbeParameters(PbeEncryptionAlgorithm.TripleDes3KeyPkcs12, HashAlgorithmName.SHA1, 1));
RSA temp = RSA.Create();
temp.ImportEncryptedPkcs8PrivateKey("temp", exported, out _);
var loadedPrivate = temp.ExportRSAPrivateKey();
```

Basically, do an indirect export through an encrypted export, first. What I think has happened is that your RSA key in CNG is marked as `Exportable` but not `PlaintextExportable`.

**Comment by vcsjones** [comment]
Aw, lost by 6 seconds.

**Comment by bartonjs** [comment]
@vcsjones Yours has the advantage of compiling, though.  6 seconds well spent :wink:

**Comment by SCLDGit** [comment]
I'll give the workaround a try, thanks! Alternately, is there any way to set the key to be plain text exportable?

**Comment by vcsjones** [comment]
@SCLDGit 
>is there any way to set the key to be plain text exportable?

Actually yes. You should be able to do something like this:

```csharp
var loadedRsa = cert.GetRSAPrivateKey();

if (loadedRsa is RSACng cng)
{
    byte[] exportValue = new byte[] { 0x02, 0x00, 0x00, 0x00 }; // 0x02 DWORD in little endian
    cng.Key.SetProperty(new CngProperty("Export Policy", exportValue, CngPropertyOptions.None));
}

var loadedPrivate = loadedRsa.ExportRSAPrivateKey();
```

**Comment by bartonjs** [comment]
While this is another nudge in the direction of working around the underlying difference in exportability notions, I don't think we're ready to do anything about it yet. So I'm going to go ahead and close the issue.
