### ISSUE TITLE
Cannot work with same root for many classes - Microsoft.XmlSerializer.Generator 2.2.0

### ISSUE THREAD

**Issue by NUnitTester** [dotnet/runtime#36922]
The problems ocure while transforming a project from .NET Framework to .NET Core 3.1 with
Microsoft.XmlSerializer.Generator 2.2.0.

In .NET Framework there is the possibility to get such a code work:
```
    [XmlRoot("root")]
    public class Base
    {
	[XmlAttribute("Type")]
        public string TypeName;
    }

    [XmlRoot("root")]
    public class A : Base
    {
        [XmlElement("value1")] 
        public string V;
    }

    [XmlRoot("root")]
    public class B : Base
    {
        [XmlElement("value2")] 
        public string V;
    }
```

Error Message:
The top XML element 'root' from namespace '' references distinct types DbGenerator.Base and DbGenerator.A. Use XML attributes to specify another XML name or namespace for the element or types.

This works in .NET Framework. My code analyzes the file and found the roor 'root'. Then it looks for the type and if it is known it creates the serializer with the correct type. The serializer can than deserialize it and everything is fine. The real code works only with the base class because every member can be overloaded if needed. Serialization is no problem at all in .NET Framework.

The very nive solution would be to define a delegate for solving ambiguity if needed.
The main idea is like that:
```
        public class XmlRootAmbigiousEventArgs : EventArgs
        {
            public string RootName { get; }
            public IReadOnlyCollection<Type> AmbigiousTypes { get; }
            public Type TypeToUse { get; set; }

        }
                
       public delegate void XmlRootAmbigiousEventHandler(object sender, XmlRootAmbigiousEventArgs e);

```

**Comment by HongGit** [comment]
duplicate #36921 same workaround.
