### ISSUE TITLE
[profiler] Get generic type arguments

### ISSUE THREAD

**Issue by ABaboshin** [dotnet/runtime#36927]
I'm using ICorProfilerCallback8::JITCompilationStarted to intercept the calls and to instrument some methods. 

To retrieve the method information I'm using `GetMemberRefProps/GetMemberProps/GetMethodSpecProps`:

```
...
        switch (TypeFromToken(token)) {
        case mdtMemberRef:
            hr = metadataImport->GetMemberRefProps(
                token, &parentToken, &functionName[0], MAX_CLASS_NAME, &functionNameLength,
                &rawSignature, &rawSignatureLength);
            break;
        case mdtMethodDef:
            hr = metadataImport->GetMemberProps(
                token, &parentToken, &functionName[0], MAX_CLASS_NAME, &functionNameLength,
                nullptr, &rawSignature, &rawSignatureLength, nullptr, nullptr,
                nullptr, nullptr, nullptr);
            break;
        case mdtMethodSpec: {
            isGeneric = true;
            hr = metadataImport->GetMethodSpecProps(
                token, &parentToken, &rawSignature, &rawSignatureLength);
            if (FAILED(hr)) {
                ...
            }
            auto genericInfo = GetFunctionInfo(metadataImport, parentToken);
...
        } break;

```

To get the type information I'm using `parentToken` and `GetTypeDefProps/GetTypeRefProps/GetTypeSpecFromToken`:

```
        switch (TypeFromToken(parentToken)) {
        case mdtTypeDef:
            hr = metadataImport->GetTypeDefProps(parentToken, &typeName[0], MAX_CLASS_NAME,
                &typeNameLength, nullptr, nullptr);
            break;
        case mdtTypeRef:
            hr = metadataImport->GetTypeRefProps(parentToken, nullptr, &typeName[0],
                MAX_CLASS_NAME, &typeNameLength);
            break;
        case mdtTypeSpec:
        {
            PCCOR_SIGNATURE signature{};
            ULONG signature_length{};

            hr = metadataImport->GetTypeSpecFromToken(token, &signature,
                &signature_length);

            if (FAILED(hr) || signature_length < 3) {
                return {};
            }

            if (signature[0] & ELEMENT_TYPE_GENERICINST) {
                mdToken typeToken;
                auto length = CorSigUncompressToken(&signature[2], &typeToken);
                auto ti = GetTypeInfo(metadataImport, typeToken);
...
            }
        }
        break;

```

I've faced a problem when parsing the type signature to the method like `Interface<Class<T>>::Method` (i.e. MassTransit.IConsumer<T>::Consume(ConsumeContext<T> contenxt) ). I'm getting the folllowing type signature:

```
0x15 -> ELEMENT_TYPE_GENERICINST
0x12 -> ELEMENT_TYPE_CLASS
0x83
0x2c -> type token
0x1 -> number of generic arguments
0x13 -> ELEMENT_TYPE_VAR
0x1 -> 
```

What is the right way to resolve generic type arguments?

P.S. I have the same behavior with .net core 2.1 and .net core 3.1.

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
Hi @ABaboshin 

For what you have above, `ELEMENT_TYPE_VAR` means that the following unsigned integer will be an index to the generic parameters. So in the example you pasted, the type has 1 generic parameter and then first parameter is `ELEMENT_TYPE_VAR`, and the 1 that follows means that the parameter is the first generic parameter to the class.

I.e. if you had the class `class Foo<T, U>`, then for `ELEMENT_TYPE_VAR` 1 would refer to `T` and 2 would refer to `U`. `ELEMENT_TYPE_MVAR` functions the same way, except it indicates that the following integer refers to the generic method types instead of the generic class types.

It might be helpful to read the CLI spec here: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf. The signature format is described in `II.23.2` and there are some examples of metadata in `VI.B.4.3`

**Comment by ABaboshin** [comment]
Hi @davmason 

Thank you for your reply.

I found the following:

When I write in my code something like `new MyGenericType<T1>().Execute()` or `IMyGenericType<T1> obj = new MyGenericType<T1>(); obj.Execute();` then I'm able to get the full information about the generic argument.

But when I'm trying to intercept the calls done by MassTransit + Greenpipes (https://github.com/MassTransit/MassTransit) where the call is looking like 

```
if (context.Consumer is IConsumer<TMessage> messageConsumer)
                return messageConsumer.Consume(context); (1)
```
 then I'm getting the following type signature for the (1) call
```
0x15 -> ELEMENT_TYPE_GENERICINST
0x12 -> ELEMENT_TYPE_CLASS
0x83
0x2c -> type def  token mdtTypeDef which is going to be resolved as MassTransit.IConsumer'1
0x1 -> number of generic arguments
0x13 -> ELEMENT_TYPE_VAR
0x1 -> 
```

I'm getting information that it's a generic class which has 1 generic type argument. And when I'm moving to the generic arguments part I see only that it's the first argument (ELEMENT_TYPE_VAR 1).

And now I'm stuck to resolve this generic argument and get the type token for it.

**Comment by davmason** [comment]
From searching through MassTransit it looks like this is the code you're trying to instrument https://github.com/MassTransit/MassTransit/blob/3b98c2819fdddc519d4ad88e3873255013aa137d/src/MassTransit/Pipeline/Filters/MethodConsumerMessageFilter.cs#L27-L49

The issue that you're looking at the IL for a generic method, so there is no instantiated type to find. When you make a call like `IMyGenericType<T1> obj = new MyGenericType<T1>(); obj.Execute(); ` You are creating an instantiated generic type with a specific type argument, so at the callsite you know what the types are for that particular call.

When you are looking at the IL for a method like `Task IFilter<ConsumerConsumeContext<TConsumer, TMessage>>.Send(ConsumerConsumeContext<TConsumer, TMessage> context,
            IPipe<ConsumerConsumeContext<TConsumer, TMessage>> next)`, the method IL does not have a particular type. It is generic, so the caller will determine what type it is calling with. The `ELEMENT_TYPE_VAR` with the 1 as the next token means that this method is generic and it will take whatever the first generic argument of the class is. For `public class MethodConsumerMessageFilter<TConsumer, TMessage>` `ELEMENT_TYPE_VAR=1` refers to `TConsumer`. But, `TConsumer` can be any type specified by a caller that satisfies the generic constraints.

If you were looking at the IL in a method that calls the `Send` above, you would be able to get the generic type.

**Comment by ABaboshin** [comment]
@davmason Thank you, now I got it!
