### ISSUE TITLE
[System.Test.Json] JsonStringEnumConverter should support enum values marked with EnumMember and use the value from that when serializing/deserializing.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#36931]
I personally think that EnumMember should be supported, many users try to use it with the JsonStringEnumConverter that comes shipped with System.Text.Json itself. Because of this they can run into an System.Text.Json.JsonException from doing such which sucks.

Take a look at the draft pr that is on hold because this is 1 of the issues they face when trying to eradicate newtonsoft.json: https://github.com/RehanSaeed/Schema.NET/pull/100

Also take a look at a version of my code which did that, then I have to now struggle trying to get my stuff to compile because now I got to create a string extension method that could allow null strings somehow and then filter it to the enum values accordingly manually which also sucks.
https://paste.mod.gg/giwezarimo.cs
https://paste.mod.gg/nuqofuwamu.cs
https://paste.mod.gg/gunoqemufu.cs

You can literally use this code as a minimal example and as you can tell my code will not compile as this stuff is lacking. Note: I only made this change because of that pull request above I seen that it used ``EnumMember`` and that it used a converter I did not really know about so I thought "Wait a second so my manual converters is not needed at all?"

**Comment by jmaine** [comment]
This looks like an easy issue to fix. The only question is which version do we want to put the fix in?

**Comment by jmaine** [comment]
I am working on a pull request for this.

**Comment by AraHaan** [comment]
Most likely the master branch.

**Comment by layomia** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/31081.
