### ISSUE TITLE
System.DirectoryServices.Protocols - Night build preview 6 - LDAP Linux Search Error

### ISSUE THREAD

**Issue by brunohbrito** [dotnet/runtime#36948]
### Description

I was trying to search a user specific metadata by following code snippet:

```c#
var searchFilter = $"(|(mail=joao.silva@brunobrito.net)(sAMAccountName={username}))";
var searchRequest = new SearchRequest("DC=brunobrito,DC=net", searchFilter, SearchScope.Subtree, "displayName", "cn", "mail" );

var response = (SearchResponse)connection.SendRequest(searchRequest);
```
The code runs fine at Windows Environment, but doesn't work under Linux. Doesn't matter the changes at filter / parameters I do the error is always the same: `An unspecified operation error occurred.`

### Configuration

* Which version of .NET is the code running on?
.NET 5.0
* What OS and version, and what distro if applicable?
Linux Debian 10 - Container image runtime:5.0-buster-slim

**Comment by ericstj** [comment]
This looks like it is the same issue reported in https://github.com/dotnet/runtime/issues/38608.
