### ISSUE TITLE
# Socket.ReadMessageFromAsync fails with SocketError.MessageSize reading from raw IP socket using IPv6

### ISSUE THREAD

**Issue by mikebromwich** [dotnet/runtime#36959]
# Socket.ReadMessageFromAsync fails with SocketError.MessageSize reading from raw IP socket using IPv6

When attempting to read a raw IPv6 packet from a Socket using ReadMessageFromAsync, the SocketAsyncEventArgs.SocketError is always MessageSize and the IPPacketInformation is unpopulated. I have ensured that the buffer size is sufficient (e.g. 2000) and the size of the packet (seen in Wireshark) is <100 bytes.

Changing from ReadMessageFromAsync to ReadMessageAsync resolves the issue - but as expected does not populate IPPacketInformation.

Tested under .NET Core 3.1.

Socket created using:

```
var RawSocket = new Socket(AddressFamily.InterNetworkV6, SocketType.Raw, ...)

RawSocket.Bind(new IPEndPoint(IPAddress.IPv6Any, 0));

RawSocket.ReceiveFromAsync(NextArgs)...

internal void ReceivedSocketEvent(object _, SocketAsyncEventArgs currentArgs)
{
}

```

**Comment by wfurt** [comment]
Can you post complete runnable app @mikebromwich? What OS do you use?

**Comment by mikebromwich** [comment]
Hi @wfurt 

In preparing a self-contained runnable app, I believe that I have spotted the (my) error. I was initializing SocketAsyncEventArgs.RemoteEndpoint to IPAddress.Any as opposed to IPAddress.IPV6Any - so the issue was probably being caused by the size of the address buffer not the size of the message.

I'll close this issue - and apologies for (probably) wasting your time.

Regards,

Mike
