### ISSUE TITLE
DI - Minor additional test coverage PR

### ISSUE THREAD

**Issue by dazinator** [dotnet/runtime#36977]
I have submitted a PR that just adds an additional test to DI [CallsiteTests](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.DependencyInjection/tests/CallSiteTests.cs)

Notes are provided on the PR.

**Comment by ViktorHofer** [comment]
Closing as the additional issue isn't needed. Thanks.
