### ISSUE TITLE
Different Task Status for ThrowIfCancellationRequested vs Throwing OperationCanceledException

### ISSUE THREAD

**Issue by wsugarman** [dotnet/runtime#36996]
### Description

I was writing some unit tests when I discovered that the `Task` object returned by `Task.Run` behaves differently depending on the expression used to throw an `OperationCanceledException` as illustrated in the below example:

```csharp
public static async Task Main(string[] args)
{
    using CancellationTokenSource source = new CancellationTokenSource();
    source.Cancel();

    var tasks = new Task[]
    {
        Task.Run(() => throw new OperationCanceledException(source.Token)),
        Task.Run(() => source.Token.ThrowIfCancellationRequested()),
    };

    for (int i = 0; i < tasks.Length; i++)
    {
        var t = tasks[i];
        try
        {
            await t.ConfigureAwait(false);
        }
        catch (OperationCanceledException e)
        {
            Console.WriteLine("[{0}] - Status: {1}, Exception: {2}, IsCancellationRequested: {3}", i, t.Status, e.GetType().Name, e.CancellationToken.IsCancellationRequested);
        }
    }
}
```
Output:
```
[0] - Status: Canceled, Exception: OperationCanceledException, IsCancellationRequested: True
[1] - Status: Faulted, Exception: OperationCanceledException, IsCancellationRequested: True
```

Strangely, at least to me, while the first `Task` becomes "Canceled", the second `Task` becomes "Faulted." Is this behavior intended? Either way, why does this happen?

### Configuration

I first tried this in `netcoreapp3.1`.

### Regression?

It doesn't appear to be a regression, as I also tried this in `netcoreapp2.2` and `net472`.

**Comment by stephentoub** [comment]
This is by-design and is more to do with the C# compiler.  There are a variety of Task.Run overloads that take different delegate types, and the C# compiler's overload resolution is mapping your two calls to two different overloads.  It sees with the second call that it's effectively a void-returning lambda, so it uses the `Task.Run(Action)` overload.  For the first call, however, it can't determine what the return type is, as all paths throw, and it ends up picking the `Task.Run(Func<Task>)` overload.  The difference you see behaviorally is then the difference between behaviors of those two overloads. The Action-based overload doesn't special-case anything.  The `Func<Task>`-based overload is intended to be used with async methods, which special-case `OperationCanceledException` such that if an async method throws an `OperationCanceledException`, the Task returned from the async method ends in a Canceled state.  To avoid a discrepancy between the delegate synchronously throwing an OperationCanceledException and the delegate asynchronously "throwing" an OperationCanceledException, it special-cases the first to have the same behavior as the second.

**Comment by tarekgh** [comment]
@wsugarman closing this issue here per @stephentoub comment. feel free to respond back if you have any questions or comments.
