### ISSUE TITLE
[browser][wasm] Move messages into the project .resx.

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#36999]
Static text messages need to be moved into a project .resx.

**Comment by BruceForstall** [comment]
@kjpou1 what 'area' should this issue have?

**Comment by Nikolay-parhimovich** [comment]
It looks like the issue is solved in https://github.com/dotnet/runtime/pull/37235

**Comment by kjpou1** [comment]
Hello Nikolay

I do not think it is solved completely.  I think it was only started.  Will take a look at it to see where the progress is.

Thank you for the interest in the project and hopefully contributing.

**Comment by Nikolay-parhimovich** [comment]
@kjpou1 Hi!
Could you please give more details on this issue?

**Comment by kjpou1** [comment]
Sorry for the delay Nikolay.  

There are still some that did not get caught in [BrowserHttpHandler](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/BrowserHttpHandler/BrowserHttpHandler.cs)

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/BrowserHttpHandler/BrowserHttpHandler.cs#L250

and 

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/BrowserHttpHandler/BrowserHttpHandler.cs#L565

Not sure I see anymore though.  Most have been caught now it seems.

We can follow how the the message for [blobs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/Resources/Strings.resx#L207) were handled by using the string resource instead of literal:  SR.net_http_client_http_browser_baseaddress_required;

**Comment by Nikolay-parhimovich** [comment]
@kjpou1 Hi. I created related changes in https://github.com/dotnet/runtime/pull/43723 . Could you please check it?

**Comment by kjpou1** [comment]
closed by https://github.com/dotnet/runtime/pull/43723
