### ISSUE TITLE
Mono Delegate contains code which ILLink can't analyze

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#37008]
I'm not clear on when this code is in use and what it's trying to reflect on:

https://github.com/dotnet/runtime/blob/92760b595598373279709353e7f36f9a1d1ab0c6/src/mono/netcore/System.Private.CoreLib/src/System/Delegate.Mono.cs#L428-L434

This implies we have scenarios when a delegate instance hasn't decided what method it's pointing to and it's going to make the decision based on the parameters passed to `Delegate.DynamicInvoke`. Besides the `FIXME` bug around null parameters, this has obvious problems with `Type.Missing` values, passing types that are subject to implicit widening, variance, etc.

**Comment by lambdageek** [comment]
The corresponding code in CoreCLR calls `GetInvokeMethod` which is an internal call and is also opaque to the linker (AFAIK)

https://github.com/dotnet/runtime/blob/e899d1106f7154fe4c7a6dfadf0e4f521711f5ef/src/coreclr/src/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs#L86-L92

**Comment by MichalStrehovsky** [comment]
CoreCLR doesn't have the concept of Heisendelegates. Once you have a delegate instance the method it's pointing to is fixed (forgetting about open virtual delegates for a moment).

With the Mono Heisendelegates, one can do:

```csharp
class Program
{
    public static void Do(int a) { Console.WriteLine("Int"); }
    public static void Do(byte a) { Console.WriteLine("Byte"); }

    static void Main()
    {
        {
            var a = MakeMonoHeisendelegate();

            // Binds the delegate to the Int overload
            a.DynamicInvoke(123);

            // Byte can be widened to int
            a.DynamicInvoke((byte)1234);
        }
        {
            var a = MakeMonoHeisendelegate();

            // Binds the delegate to the Byte overload
            a.DynamicInvoke((byte)123);

            // DynamicInvoke doesn't narrow so this would throw
            a.DynamicInvoke(1234);
        }
    }
}
```

I want to find out what `MakeMonoHeisendelegate` is so that we can mark it as trimming unfriendly.

**Comment by lambdageek** [comment]
Ah, thanks for the explanation, Michal, I get what you're asking now.

It's really old code, (coming from mono/mono@a37e583ddb9f93385991579a72f3c232a2ece6bd from 18 years ago), I wonder if it's dead.

**Comment by lambdageek** [comment]
Nothing got tripped in either dotnet/runtime or mono/mono testing that's attributable to those lines in Mono's delegate implementation.

I'm going to assume that Heisendelegates don't exist and will remove that branch.  `Method` should always be non-null in `DynamicInvokeImpl`

**Comment by MichalStrehovsky** [comment]
Awesome, thanks! One less warning to worry about.
