### ISSUE TITLE
Missing RID for Ubuntu 20.04

### ISSUE THREAD

**Issue by bradwilson** [dotnet/runtime#37000]
### Description

Ubuntu 20.04 was released last month, and the [RID list](https://github.com/dotnet/runtime/blob/064c5f15242b8ffe402cd50633b79bac76cd0134/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json#L5336) does not yet include Ubuntu 20.04; as a result, the RID on Ubuntu 20.04 (and derivatives) is returned as the generic `linux-x64`. This causes compatibility issues with native libraries, since some dependencies in generic Linux and Ubuntu are different (for example, libssl 1.0 vs. 1.1).

### Configuration

`dotnet --info` from Ubuntu 19.10:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/
```

`dotnet --info` from Ubuntu 20.04:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/
```

**Comment by ViktorHofer** [comment]
cc @danmosemsft @ericstj

**Comment by danmosemsft** [comment]
@wfur use you adding these?

Cc @dleeapho

**Comment by bartonjs** [comment]
FYI @wfurt

**Comment by ViktorHofer** [comment]
Impelmented with https://github.com/dotnet/corefx/pull/42934. Closing.
