### ISSUE TITLE
a little fault about instructions in the  struct "Char"`s functions

### ISSUE THREAD

**Issue by BillWagner** [dotnet/runtime#37012]
@wybgsn commented on [Thu May 21 2020](https://github.com/dotnet/docs/issues/18564)

**Visual Studio Version**:
16.5.5
**Summary**:
There`s a little fault in System.Char, a lot of functions` instructions written by Chinese in that file  
discribe the name of parameter as "true“, actually it should be "c" or "s".

**Steps to Reproduce**:

1. 

2. 

3. 

**Expected Behavior**:
如果 c 是一个字母，则为 true；否则为 false。(Others all like this)
**Actual Behavior**:
![1](https://user-images.githubusercontent.com/57448396/82557918-3042a200-9b9f-11ea-85da-bf6a79825d24.png)
**User Impact**:
uhhh... just a little misunderstand or .. funny?

---

@drewnoakes commented on [Thu May 21 2020](https://github.com/dotnet/docs/issues/18564#issuecomment-632090158)

Thanks for the issue.

Looks like this should be transferred to runtime. That repo doesn't come up in the list for me. Can anyone on this repo do that?

---

@wybgsn commented on [Fri May 22 2020](https://github.com/dotnet/docs/issues/18564#issuecomment-632483477)

> Thanks for the issue.
> 
> Looks like this should be transferred to runtime. That repo doesn't come up in the list for me. Can anyone on this repo do that?

https://docs.microsoft.com/zh-cn/dotnet/api/system.char.isletter?view=netframework-4.8
I'm sorry, but I'm just a beginner. I saw this only occasionally, and I didn't know how to get in touch with the people who managed it. I would appreciate it very much if you could help me to tell them about it.

**Comment by GrabYourPitchforks** [comment]
@BillWagner sounds like a docs localization issue? In English, that line reads "_true_ if _c_ is a letter; else _false_." Sounds like the Chinese translation of the doc got morphed to "if _true_ is a letter, returns _c_; else _false_."

**Comment by BillWagner** [comment]
Thanks @GrabYourPitchforks 

Adding @JasonCard   Should this move back to the loc doc repos?

**Comment by JasonCard** [comment]
@BillWagner Yes, this looks like Simplified Chinese (zh-cn) translation issue, so it should be moved to [zh-cn repo](https://github.com/dotnet/dotnet-api-docs.zh-cn).

**Comment by BillWagner** [comment]
Issue moved to [dotnet/dotnet-api-docs.zh-cn #60](https://github.com/dotnet/dotnet-api-docs.zh-cn/issues/60) via [**ZenHub**](https://www.zenhub.com/)

**Comment by GrabYourPitchforks** [comment]
Thanks! :D
