### ISSUE TITLE
Not all contention is are reported via Lock contention

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#37023]
`lock` aka `Monitor` records contention prior to beginning its spin->wait cycle; however if contention happens in `SpinLock` and it has to spin, that isn't surfaced via this counter.

Related but different, I think contention handled via a `SpinWait` isn't surfaced this way (e.g. `ConcurrentQueue`), though it's not a `lock` perse; but the contention figure gives an incomplete picture.

So they be added?

/cc @kouvel @stephentoub

**Comment by jkotas** [comment]
> Monitor records contention prior to beginning its spin->wait cycle

I believe that it reports it after spinning, before calling into OS to wait: https://github.com/dotnet/runtime/blob/58ee1305580774e6791ad1b31d01f7f7effb5780/src/coreclr/src/vm/syncblk.cpp#L2555

**Comment by benaadams** [comment]
Was thinking more the counter; which is much lower cost being only an Interlocked increment

https://github.com/dotnet/runtime/blob/58ee1305580774e6791ad1b31d01f7f7effb5780/src/coreclr/src/vm/syncblk.cpp#L2567

However, I may be wrong as to when it happens as can't find an pre-spinning now; can only find the spinning after it has been awoken and is trying to reacquire the lock.

Rephrasing then, should in Interlocked increment be moved prior to any spinning and also more wide spread to give a better view on contention; then the more detail provided by ETW etc which is more expensive remain with the Wait?

**Comment by benaadams** [comment]
Ah; before calling `EnterObjMonitorHelperSpin`

**Comment by benaadams** [comment]
Ah...

Should it call `Thread::IncrementMonitorLockContentionCount` before calling `EnterObjMonitorHelperSpin`, because at that point there definitely is contention, even if its not yet going to sleep

**Comment by jkotas** [comment]
It would change what this number means and how to interpret it. The current counter should be very flat in a well-written app. If the counter is steadily increasing, it means the app has scalability problem that it is worth looking into.

If we were to change it to count spinning, the number will be more noisy, less reliable indicator of a real scalability problem that it is worth looking into.

**Comment by benaadams** [comment]
Ok
