### ISSUE TITLE
Add method "hasText" to String class

### ISSUE THREAD

**Issue by athinboy** [dotnet/runtime#37040]
## Background and Motivation

public bool hasText([NotNullWhen(false)] string? value){

return    !IsNullOrWhiteSpace(value) ;

}

**Comment by SingleAccretion** [comment]
I suppose it is meant to be an extension method (since otherwise it would throw NRE when `value is null`)? In that case it would introduce an inconsistency: generally, extension methods are meant to throw on `null` inputs.

**Comment by vcsjones** [comment]
A similar proposal was already made in https://github.com/dotnet/runtime/issues/26677.

Personally I don't see much value in introducing a new public API just avoid a logical negation.

**Comment by athinboy** [comment]
@vcsjones  
you are right! 
But, I think "hasText" is more concise and more  logical  than "IsNullOrWhiteSpace"  .
