### ISSUE TITLE
single file publish: AppContext.BaseDirectory doesn't point to apphost directory

### ISSUE THREAD

**Issue by dasMulli** [dotnet/runtime#3704]
## Steps to reproduce
1. Create a hello world program:
```c#
static void Main(string[] args)
{
    Console.WriteLine("Hello World!");
    Console.WriteLine($"Base Directory: {AppContext.BaseDirectory}");
    Console.WriteLine($"Assembly Location: {typeof(Program).Assembly.Location}");
}
```
2. Publish self contained - `dotnet publish -c Release -r win-x64 -p:PublishSingleFile=True --self-contained false` (or self-contained)

3. Run the resulting exe file.

## Expected  behavior

According to the [design document](https://github.com/dotnet/designs/blob/686205657ace53b3e6d568cb098be302f6974956/accepted/single-file/design.md), `AppContext.BaseDirectory` is the API that developers should use to access the path where the app host resides.

The app context base directory should therefore not be in `AppData\Local\Temp\.net\`.

Background: I want to use this directory to load override config files.

## Actual behavior

```
C:\demos\testcons\bin\Release\netcoreapp3.0\win-x64\publish>testcons.exe
Hello World!
Base Directory: C:\Users\ullrimar\AppData\Local\Temp\.net\testcons\53kpwgv0.3mq\
Assembly Location: C:\Users\ullrimar\AppData\Local\Temp\.net\testcons\53kpwgv0.3mq\testcons.dll
```

## Environment data

```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450
```

cc @vitek-karas

**Comment by theimowski** [comment]
FYI seems like starting with .NET SDK 3.1.201, the `Diagnostics.Process.GetCurrentProcess().MainModule.FileName` changed behaviour with regards to non-single file publish.

with .NET SDK 3.1.101:
I could use `Diagnostics.Process.GetCurrentProcess().MainModule.FileName` for both single-file publish, and debug development (dotnet watch run) and it returned the base directory in both cases, but 

in .NET SDK 3.1.201:
In debug development mode (dotnet watch run),  `Diagnostics.Process.GetCurrentProcess().MainModule.FileName` returns the dotnet executable (e.g. `/usr/local/share/dotnet/dotnet`) so I had to amend my code to following:

```fsharp
  let baseDir =
#if DEBUG
    AppContext.BaseDirectory
#else
    Diagnostics.Process.GetCurrentProcess().MainModule.FileName
    |> IO.Path.GetDirectoryName
#endif
```

**Comment by dasMulli** [comment]
@theimowski are you running this on macOS?

In order to comply with notarization requirements, the signed binary (`/usr/local/share/dotnet/dotnet`) is used so users don't get too many errors.

You can get the old behavior again by specifying this in your project file:
```xml
<PropertyGroup>
  <UseAppHost>true</UseAppHost>
</PropertyGroup>
```

See https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues for more details

**Comment by theimowski** [comment]
Thanks @dasMulli  yup I'm running on macOS and missed the notarization update. The `UseAppHost` property did the job for me 👍

**Comment by swaroop-sridhar** [comment]
This issue is fixed in .net5
