### ISSUE TITLE
System.MissingMethodException : Constructor on type 'System.Text.Json.Serialization.NullableConverter[...]' not found

### ISSUE THREAD

**Issue by dlyz** [dotnet/runtime#37047]
Related to .NET 5 only.

Consider we have a class:

```cs
class MyClass
{
    [JsonConverter(typeof(MyValueTupleConverterFactory))]
    public (int, int)? Val { get; set; }
}
```

where `MyValueTupleConverterFactory` is a `JsonConverterFactory`, that can convert `ValueTuple<int, int>`, but can not convert `Nullable<ValueTuple<int, int>>`.

In this case `System.Text.Json.Serialization.NullableConverter<ValueTuple<int, int>>` will be constructed with an instance of `MyValueTupleConverterFactory` which is `JsonConverterFactory`, but the constructor expects `JsonConverter<ValueTuple<int, int>>`. As a result we got MissingMethodException thrown.

Probably, in order to fix this, factory converter should be replaced with the exact converter [here](https://github.com/dotnet/runtime/blob/32fdcaf5eeb890c00f2a5310cc36b24cc1025884/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L249).

**Comment by layomia** [comment]
@dlyz thanks for the clear explanation of the issue. Fix in https://github.com/dotnet/runtime/pull/40879.
