### ISSUE TITLE
Feature Request: Add various extension methods from Microsoft.AspNet.WebApi.Client

### ISSUE THREAD

**Issue by IanKemp** [dotnet/runtime#37055]
References:

https://github.com/aspnet/Mvc/issues/1639
https://github.com/dotnet/runtime/issues/16538

There is a NuGet package [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/microsoft.aspnet.webapi.client/) that provides a whole bunch of useful extension methods to allow you to perform various useful operations on `HttpClient` and `HttpContent` instances ([`HttpContent.ReadAsAsync<T>()`](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpContentExtensions.cs#L137) and [`HttpClient.PostAsJsonAsync(string)`](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpClientExtensions.cs#L33) were my personal favourites). However that package is targeted at ye olde ASP.NET Web API 2, so I don't know how optimal it is for ASP.NET Core (e.g. it has no knowledge of `Span<T>`) and/or how long it will continue to work with Core (especially since it was last updated over a year ago).

Would it be desirable to add these extensions to ASP.NET Core? If not, is the `Microsoft.AspNet.WebApi.Client` package the correct and supported way to get those extensions going forward?

**Comment by IanKemp** [comment]
@pranavkm I don't think this should be transferred here, the functionality I'm looking for is mostly around very web-specific stuff regarding JSON.

**Comment by pranavkm** [comment]
@IanKemp the runtime repo is the appropriate place to discuss `HttpClient` extensibility. Some of your asks might have already been covered by System.Net.Http.Json that was introduced very recently: https://github.com/dotnet/runtime/issues/32937 (/cc @Jozkee)

**Comment by IanKemp** [comment]
@pranavkm thanks, did not know that. The new APIs you linked to seem like they will cover a lot of my "wants" but I feel like it would be useful to cross-check them against what was/is available in `Microsoft.AspNet.WebApi.Client`.

**Comment by karelz** [comment]
@IanKemp can you please help with the cross check? Are there specific APIs which you think are missing?

**Comment by karelz** [comment]
Triage: Does not seem to be critical for 5.0 -> Future.
Unclear if anything is needed at all.

**Comment by karelz** [comment]
Unclear what is needed, closing.
