### ISSUE TITLE
Warning CS8602: Dereference of a possibly null reference warning after Asserting not null

### ISSUE THREAD

**Issue by markmarsella** [dotnet/runtime#37060]
After asserting not null on an object I still get  the warning about dereferencing a null reference

Code example:

```
using NUnit.Framework;
....
 Assert.IsNotNull(obj);  //Assert is from Nunit
 Assert.IsNotNull(obj.TheObject); //Warning is here

```

```
<TargetFramework>netcoreapp3.1</TargetFramework>
 <Nullable>enable</Nullable>
```

**Comment by stephentoub** [comment]
The argument to `Assert.IsNotNull` would need to be attributed as `[NotNullWhen(true)]` for the compiler to be able to infer anything about the object's null state. This is an issue for NUnit.
