### ISSUE TITLE
System.Diagnostics.DiagnosticSource.Switches.Tests tests fail on Android/iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37073]
Based on Android x64, x86, arm64 runs on https://github.com/dotnet/runtime/pull/50095

### System.Diagnostics.DiagnosticSource.Switches.Tests

- [ ] System.Diagnostics.Tests.ActivityTests.ActivityIdNonHierarchicalOverflow
    `Assert.InRange() Failure\r\nRange:  (55 - 56)\r\nActual: 27`
- [ ] System.Diagnostics.Tests.ActivityTests.IdFormat_ZeroTraceIdAndSpanIdWithHierarchicalFormat
    `Assert.Equal() Failure\nExpected: Hierarchical\nActual:   W3C`
- [ ] System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalIsDefault
    `Assert.Equal() Failure\nExpected: Hierarchical\nActual:   W3C`
- [ ] System.Diagnostics.Tests.ActivityTests.IdGenerationInternalParent
    `Expected: |3bb0aa728f97f001b74c999028c145ff.child1-1. || |3bb0aa728f97f001b74c999028c145ff.1.\nActual: 00-3bb0aa728f97f001b74c999028c145ff-005236cd8f819f69-00`

```
System.Diagnostics.DiagnosticSource.Switches.Tests.dll   Failed: 4

Test collection for System.Diagnostics.Tests.ActivityTests
System.Diagnostics.Tests.ActivityTests.ActivityIdNonHierarchicalOverflow
    Assert.InRange() Failure\r\nRange:  (55 - 56)\r\nActual: 27
System.Diagnostics.Tests.ActivityTests.IdFormat_ZeroTraceIdAndSpanIdWithHierarchicalFormat
    Assert.Equal() Failure\nExpected: Hierarchical\nActual:   W3C
System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalIsDefault
    Assert.Equal() Failure\nExpected: Hierarchical\nActual:   W3C
System.Diagnostics.Tests.ActivityTests.IdGenerationInternalParent
    Expected: |f7975b073fab84cb7f79edd32172a912.child1-1. || |f7975b073fab84cb7f79edd32172a912.1.\nActual: 00-f7975b073fab84cb7f79edd32172a912-97b1c565a0ff71e3-00
```

Update: Folded in https://github.com/dotnet/runtime/issues/51376 as it also fails on iOS and tvOS with similar failures.

**Comment by noahfalk** [comment]
@marek-safar - I notice this issue has been unaddressed for ~7 months. Is it tracking work you plan to do or can it be closed?

I ask because Tom's team has triage queries that include anything tagged System.Diagnostics but I don't think we have any actionable work here. We can update our queries with exclusions if needed. Thanks!

**Comment by marek-safar** [comment]
I think it's worth updating your queries to exclude issues diagnostics team does not own. Essentially range of os-XXX architectures
