### ISSUE TITLE
BitConverter.ToSByte(byte data)

### ISSUE THREAD

**Issue by tthiery** [dotnet/runtime#37099]
## Background and Motivation

When interpreting raw communication protocols, we need to convert a single byte (from a byte array) into a signed byte (e.g. Bluetooth GATT message with byte in position 23 is the current RSSI value (-127 - 0).

SByte seems an omission, considering a pretty wide mapping of [signed and unsigned elementary data types](https://docs.microsoft.com/de-de/dotnet/api/system.bitconverter?view=netcore-3.1). The [common workaround](https://bytes.com/topic/c-sharp/answers/231516-convert-byte-sbyte-no-easy-way) seems to be a code using a unchecked cast. Not very UX friendly.

## Proposed API

```diff
namespace System
{
     public static class BitConverter {
+        public static sbyte ToSByte(byte input) {}
     }
}
```

## Usage Examples

``` C#
byte[] gattPayload = FromBluetooth();

sbyte rssi = BitConverter.ToSByte(gattPayload[23]);

Console.WriteLine(rssi);

```

## Alternative Designs

- BitConverter seems pretty Array/Span oriented ... maybe instead of parameter `byte` doing a `ReadOnlySpan<byte>` is more appropriate.
## Risks

- sbyte is not CLS compatible (whatever that means nowadays)

**Comment by mburbea** [comment]
Why do you need to these unsafe casts?
```cs
ReadOnlySpan<byte> bytes = new byte[]{ 0xDE,0xAD,0xBE,0xEF};
foreach(byte b in bytes)
{
       Console.WriteLine((sbyte)b);
} 
```
This works without unchecked casts. You only need the unchecked for constant values.

**Comment by tthiery** [comment]
@mburbea Thanks for the hint with the constant. That threw the exception I stepped over. Strict reading sometimes helps.

Mmh ... the api still makes a bit (oh the word play) sense but I expect a quick close from the fx team as it is otherwise easy to solve.

**Comment by joperezr** [comment]
I'll close this for now given the above solution but @tthiery feel free to reopen if you think that we should still consider the proposal you stated.
