### ISSUE TITLE
Add libldap package to the snaps

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#37091]
In 5.0 a new native dependency was added on libldap.  As a result, it should be added as a package that is included in the .NET snaps.

Related:
https://github.com/dotnet/runtime/pull/36405
https://github.com/dotnet/runtime/issues/36888
https://github.com/dotnet/dotnet-docker/issues/1946
https://github.com/dotnet/runtime/issues/37090

**Comment by NikolaMilosavljevic** [comment]
[Triage] It was decided not to do this work.
