### ISSUE TITLE
System.Buffers contains untracked sources

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/runtime#37109]
Seems like there are some generated files that aren't being embedded in the pdb.

![image](https://user-images.githubusercontent.com/1427284/83086652-59f73f80-a05d-11ea-9474-1e87742cebb1.png)

@ericstj

**Comment by clairernovotny** [comment]
It's also not deterministic, needs `ContinuousIntegrationBuild` set to true.

**Comment by tannergooding** [comment]
CC. @ViktorHofer, @ericstj  this seems like a more general issue that should be handled by arcade

**Comment by danmosemsft** [comment]
@markwilkie should "validation rings" have flagged this?

**Comment by markwilkie** [comment]
Yes, but not yet I think @danmosemsft.  Source link is (almost) hooked up.  @adiaaida probably has more input....

**Comment by adamsitnik** [comment]
> @adiaaida probably has more input

@adiaaida ping

**Comment by adiaaida** [comment]
I would have expected the validation ring to have flagged this, but I am not finding System.Buffers.dll in the sourcelink validation logs at all, in either the Validation pipeline for dotnet/runtime, or the release pipeline.

**Comment by adiaaida** [comment]
I looked at the drop that we are validating against, and System.Buffers does not have a symbols package file in the drop, so we do not check it for 5.0. However, the short answer is yes: if there was a System.Buffers.<version>.symbols.nupkg file in the drop, and it had broken source links, we would have caught this in the validation pipeline. As you can see here, though, the source link job is green for the latest runtime drop, with no broken source links: https://dev.azure.com/dnceng/internal/_build/results?buildId=718633&view=results

**Comment by jeffhandley** [comment]
I'm unsure what action is needed on this based on @adiaaida's findings.
@ericstj - can you advise me on this please?

**Comment by ericstj** [comment]
You are looking at a package produced by the 2.1 branch.  This predates source linking infrastructure.

**Comment by jeffhandley** [comment]
OK, thanks @ericstj. Does that mean this should be closed as won't fix?

**Comment by ericstj** [comment]
I believe so.  Just one small thing to clear up.

> It's also not deterministic, needs ContinuousIntegrationBuild set to true.

What did you mean by this, @clairernovotny?  I wouldn't expect a 4.5.1 package to be produced by any current builds.

**Comment by ericstj** [comment]
I think it's fine to close for now, @clairernovotny can reactivate if there are any concerns.  I can say definitively we don't have this issue in 5.0.0 since we don't even produce that package.
