### ISSUE TITLE
Microsoft.Extensions.Logging is missing a dependency on Microsoft.Extensions.Configuration.Binder in 5.0

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#37104]
### 3.1
![image](https://user-images.githubusercontent.com/174281/83083648-869a5f80-a03b-11ea-85d5-1d1e21753a77.png)

### 5.0
![image](https://user-images.githubusercontent.com/174281/83083684-9d40b680-a03b-11ea-8797-980ec411c122.png)

**Comment by pranavkm** [comment]
Noticed this when I was updating one of our templates targeting ns2.1 to use the 5.0 package.

**Comment by joperezr** [comment]
cc: @ericstj

**Comment by ericstj** [comment]
cc @JunTaoLuo The library wasn't using that dependency and thus it was removed.  This happened across the board for any extensions with had "dead" references to packages they didn't need.
