### ISSUE TITLE
.NET Core 3.1 - RijndaelManaged - Initialization vector 256 bits not supported

### ISSUE THREAD

**Issue by dericferreira** [dotnet/runtime#37127]
Hey,

If .NET Core 3.1 still does not support 256 initialization vector why documentation does not reflect that?

Look at this:

//RijndaelManaged
// Legal min key size = 128
// Legal max key size = 256
// Legal min block size = 128
// Legal max block size = 256

Anybody can't get the same result! Why does the documentation is not refleting the truth?

https://docs.microsoft.com/pt-br/dotnet/api/system.security.cryptography.symmetricalgorithm.legalkeysizes?view=netcore-3.1

**Comment by vcsjones** [comment]
>  .NET Core 3.1 still does not support 256 initialization vector

Correct, it does not support a block size other than 128-bits. This was covered in some detail in this issue: https://github.com/dotnet/runtime/issues/895#issuecomment-577329652

> Why does the documentation is not refleting the truth?

Thanks for pointing that out. [The documentation specifically for `RijndaelManaged`][1] notes of this in .NET Core:

>In .NET Framework, this algorithm supports block sizes of 128, 192, or 256 bits; defaulting to 128 bits (Aes-compatible). In .NET Core, it is the same as AES and supports only a 128-bit block size.

It seems there was just a small oversight in that snippet of code in `SymmetricAlgorithm`.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndaelmanaged?view=netcore-3.1#remarks
