### ISSUE TITLE
Dataflow TransformBlock cannot accept messages while Link predicates goes well.

### ISSUE THREAD

**Issue by shiwk** [dotnet/runtime#37125]
Hi guys! 

I think something weird happened when I use `System.Threading.Tasks.Dataflow`. The `DataflowBlock`s were linked as below code. 

```c#
private TransformBlock<QueuedTransaction, QueuedTransaction> CreateQueuedTransactionBufferBlock()
        {
            var executionDataFlowBlockOptions = new ExecutionDataflowBlockOptions
            {
                BoundedCapacity = _transactionOptions.PoolLimit,
                MaxDegreeOfParallelism = _transactionOptions.PoolParallelismDegree
            };
            var linkOptions = new DataflowLinkOptions { PropagateCompletion = true };

            var updateBucketIndexTransformBlock =
                new TransformBlock<QueuedTransaction, QueuedTransaction>(UpdateBucketIndex,
                    executionDataFlowBlockOptions);
            var updateRefBlockStatusActionBlock = new ActionBlock<QueuedTransaction>(
                async queuedTransaction =>
                    await ProcessQueuedTransactionAsync(queuedTransaction, UpdateQueuedTransactionRefBlockStatusAsync),
                executionDataFlowBlockOptions);
            int i = 0;
            while (i < _transactionOptions.PoolParallelismDegree)
            {
                var validationTransformBlock = new TransformBlock<QueuedTransaction, QueuedTransaction>(
                    async queuedTransaction =>
                        await ProcessQueuedTransactionAsync(queuedTransaction, AcceptTransactionAsync),
                    new ExecutionDataflowBlockOptions
                    {
                        BoundedCapacity = _transactionOptions.PoolLimit,
                        EnsureOrdered = false
                    });
                _validationTransformBlockList.Add(validationTransformBlock);
                var index = i;
                updateBucketIndexTransformBlock.LinkTo(validationTransformBlock, linkOptions,
                    queuedTransaction =>
                    {
                        var bucketHit = queuedTransaction.BucketIndex == index ||
                                        queuedTransaction.BucketIndex == -index;
                        if (bucketHit)
                            Logger.LogDebug(
                                $"Transaction {queuedTransaction.TransactionId}, enqueue time {queuedTransaction.EnqueueTime} hits the bucket {index}." +
                                $"validation transform block input count {validationTransformBlock.InputCount}, output count {validationTransformBlock.OutputCount}");
                                
                        return bucketHit;
                    });

                validationTransformBlock.LinkTo(updateRefBlockStatusActionBlock, linkOptions,
                    queuedTransaction => queuedTransaction != null);
                validationTransformBlock.LinkTo(DataflowBlock.NullTarget<QueuedTransaction>());
                i++;
            }

            updateBucketIndexTransformBlock.LinkTo(DataflowBlock.NullTarget<QueuedTransaction>());
            return updateBucketIndexTransformBlock;
        }

```

And the pipeline is 
- Calculate transaction **BucketIndex** in **updateBucketIndexTransformBlock**
- Map(by Link predicates) and transform the transaction to one of **validationTransformBlock** with **BucketIndex**
- Transform the transaction from **validationTransformBlock** to **updateRefBlockStatusActionBlock**

Everything was ok at the beginning, but  the **validationTransformBlock** cannot accept transaction any more after thousands of transactions went through. 

I traced it with debug log and I found no transaction went into the delegate method **AcceptTransactionAsync**,  while the Link predicates for the **BucketIndex** still worked well.

**Comment by svick** [comment]
I can't spot an issue in your code, but it's hard to diagnose one part of a system in isolation like this. Can you create [a small self-contained application that demonstrates the issue](http://sscce.org/) and post it here?

**Comment by shiwk** [comment]
> Can you create [a small self-contained application that demonstrates the issue](http://sscce.org/) and post it here?

I tried to launch a simple program with the same blocks linking, but it didn't reproduce.

Thanks anyway.

I hope I can propose the issue clearly for you. I am confused that a `TransformBlock` , with `InputCount` zero and Link predicate hit, cannot receive that message, even without any exception before. Maybe I am far from the kernel theory of `DataFlowBlock`.

Btw, for clear, this is the source code which contains all the above pipeline. I hope it helps.
https://github.com/AElfProject/AElf/blob/txhub-accept-tx-test/src/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs

**Comment by svick** [comment]
> with `InputCount` zero

The `InputCount` on its own doesn't matter. What matters is whether the total number of items in the block (roughly `InputCount` + items currently being processed + `OutputCount`) is less than `BoundedCapacity`.

**Comment by shiwk** [comment]
> roughly `InputCount` + items currently being processed + `OutputCount`

`InputCount` and `OutputCount` are all both 0 when the problem happened. And for me **items currently being processed** won't be too many, right? In this case, I set `BoundedCapacity` more than 5000. 

I can show you some logs and no more message accepted after these logs.

```
...
validation transform block input count 7, output count 0 
validation transform block input count 6, output count 0
validation transform block input count 5, output count 0
validation transform block input count 4, output count 0
validation transform block input count 3, output count 1
validation transform block input count 2, output count 1
validation transform block input count 1, output count 0
validation transform block input count 0, output count 0
```

It seems the number of pending message is decreasing to zero already.

**Comment by svick** [comment]
Ok, I have found an issue with your code: because you're using `PropagateCompletion = true`, as soon as one `validationTransformBlock` completes, completion propagates to `updateRefBlockStatusActionBlock`, which means that items from the other `validationTransformBlock`s might not reach the `updateRefBlockStatusActionBlock`. Can you check the `Completion` of all the relevant blocks to see if this is what's causing the problem?

**Comment by shiwk** [comment]
> Can you check the `Completion` of all the relevant blocks to see if this is what's causing the problem?

I did and the status of `Completion` is `WaitingForActivation`.



> which means that items from the other `validationTransformBlock`s might not reach the `updateRefBlockStatusActionBlock`

In my case,  the blocks linking structure of  multi To one ,  it will be the cause of blocking message entered?

**Comment by shiwk** [comment]
And I found this happened very soon with the server CPU overloaded. I am still unclear about the root cause.

**Comment by stephentoub** [comment]
Thanks for the issue, but there's not enough information here to determine whether there's a real bug in dataflow.  If you're able to create a small repro as requested, we'd be happy to take a look.  In the meantime, I'm going to close this. Thanks.
