### ISSUE TITLE
Struct Return not optimized

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#37134]
I have created a GIST [Here](https://gist.github.com/juliusfriedman/95e7eef7a4f247781c3ec6f2dc100c3d)

The difference boils down to returning the struct vs assigning it to a variable and returning it.

```
public TimeSpan M() {
        TimeSpan x = TimeSpan.Zero;
        return x;  
    }
    
    public TimeSpan N() {
        return TimeSpan.Zero;          
    }
```

I would expect optimized code to be the same for both of these methods however this is not the case...

Is my assumption wrong?

Environment:
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by juliusfriedman** [comment]
Sorry @Dotnet-GitSync-Bot, I only see `Performance-mono` which would not be appropriate here I don't think.

Perhaps a new tag for `Performance` is also needed.

**Comment by vcsjones** [comment]
That gist looks like it was debug output, the included JSON file seems to indicate as such. [In release I see identical JIT output][1]. 

[1]: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgJgIwCwAUFgMwAEu5AwuQN7FnkAqAlmHAMoAOEAduQCyACgCU9YuSnSpbDj37kAHuQC8Ldl158AdAC1EAewDckmdKwB2ZcalmpAX3vlnTOVsUA5MRKLmL1u4KugYIJv4yzk5EDkA===

**Comment by juliusfriedman** [comment]
The thing is I have seen similar results from Production code which prompted this issue creation.

It's odd we see different things...

Is your Framework version the same as mine?

**Comment by scalablecory** [comment]
Your gist says you're in a debug build:

```
{
    "version": 1,
    "target": "JIT ASM",
    "mode": "Debug"
}
```

**Comment by huoyaoyuan** [comment]
The two versions of code creates [exactly same IL](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MGFMDeqGmAKmALYCmAygA4CGAdpgLIAUAlIapn/33LV6zTAA9MAXjKVajJgDoAWlQBOAewDcvAfxgB2cZr46+AX1OZLJIXNEA5LjxS69h2yMUqNx1/0sWKGZAA).

You can use ILSpy to check your production IL code first. If you find difference of IL patterns, you can put them here, which is useful for the JIT team.

**Comment by juliusfriedman** [comment]
I will close this issue as we have already profiled (using the Visual Studio Profiler) and worked around the issue by changing to a direct return where it showed the hot spot.

Additionally it seems the code produces the same IL and ASM on the master branch so if and when we notice this again we will create a new issue with the IL from the Release code and hopefully it will be easier to triage.
