### ISSUE TITLE
Terminating GenericHost without Control-C

### ISSUE THREAD

**Issue by JasonDWilson** [dotnet/runtime#37131]
I've looked had no luck in finding an answer, but is there a way to use the generic host in a console app and have it run and terminate automatically.  RunConsoleAsync waits for Control-C to terminate.

**Comment by davidfowl** [comment]
> I tried injecting IHostLifetime in my hosted service and calling StopApplication() in the StopAsync(), but still didnt work:

You don't need to call StopApplication from StopAsync, that's backwards. StopAsync should be called as a result of the host shutting down.

**Comment by danmosemsft** [comment]
Please exactly one area label.
