### ISSUE TITLE
Update master branch NETStandard.Library.Ref to produce 2.2 (for 5.0)

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3713]
@nguerrera pointed out in https://github.com/dotnet/core-sdk/pull/3741#discussion_r310339695 that core-setup `master` still produces 2.1 `NETStandard.Library.Ref`. dotnet/standard now produces 2.2 from its `master` branch (https://github.com/dotnet/standard/pull/1344), which core-setup should probably match.

A consideration is that we should move this package to dotnet/standard, https://github.com/dotnet/standard/issues/1209, but we don't have the prereqs to do so right now. It might be useful to just do this small amount of work to get it flowing.

/cc @wtgodbe

**Comment by NikolaMilosavljevic** [comment]
[Triage] Obsolete.
