### ISSUE TITLE
ECCurve.NamedCurves.nistP*.IsPrime returns false

### ISSUE THREAD

**Issue by tolginator** [dotnet/runtime#37144]
# Issue Title

NIST prime curves as defined in the ECCurve.NamedCurves have the *IsPrime* property returning false.

# General

These are NIST prime curves of prime order, and the property must be set to true.

**Sample Code**. 
1. Go to debugger in MSVS
2. In the watch window, type ECCurve.NamedCurves.nistP256, and expand it to see the following.

Code: deb-dotnet-corefx/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECCurve.NamedCurves.cs

Here is a screen shot.
![image](https://user-images.githubusercontent.com/3058754/83202447-772f1b00-a0fc-11ea-8332-70f42e169ff4.png)

**Comment by bartonjs** [comment]
The `IsPrime` property is always `false` for named curves, it only has meaning for explicit parameter curves.  This is better spelled out in the documentation than the property name:

> Gets a value that indicates whether the curve type indicates an explicit prime curve.

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.eccurve.isprime?view=netcore-3.1

**Comment by bartonjs** [comment]
Since this is a documented behavior of the API, closing the issue ("by design").
