### ISSUE TITLE
Socket.BeginReceive never awakes in RedHat 7 under certain conditions

### ISSUE THREAD

**Issue by psantosl** [dotnet/runtime#37149]
Hi there,

We have an issue with `Socket.BeginReceive`, that sometimes never awakes, causing trouble in a server in production.

Our customer runs .NET Core 3.1.100 in a ReadHat 7 machine.

It doesn't always happen, it doesn't happen on our load tests with 100 times more load, we don't really know why it happens.

This is our code:

```c#
mSocket.BeginReceive(buffer, 0, 0, SocketFlags.None, OnMessageReceived, null);
```

What we achieve with this code is:

- We just want to decouple the threads in our threadpool from the socket, so we don't have a 1-1 connection to socket. We can have thousands of open connections and just a few threads in the thread pool.
- If I'm not mistaken, this helps us take advantage of the underlying IOCP/epoll.
- Once the `OnMessageReceived` is triggered, we enqueue the request in a queue, and a thread in our threadpool attends it. It reads synchronously, do its thing, and writes the response back.
- Then we do a `BeginReceive` again on the socket and the thread continues for another request.
- All the `BeginReceive` are done from a single thread (not the thread pool thread). A single "network thread" that never dies that does all the BeginReceives, so we ensure this thread never leaves (in .net framework the docu says if the beginreceive dies, bad things can happen).

This code has been around for +10 years already, running on .net framework, mono, and now net core. We suspect we saw this issue in mono before.

As I said above: what happens is that _sometimes_ the callback in `BeginReceive` is never invoked, leaving the client side unattended.

When that happens, we see the async thread doing the few callbacks that really happen, is always the same (same thread id), while many different threads show up in the callback code under normal operation.

Finally, we suspect a different piece of code is causing trouble: we have a `ThreadPool.QueueUserWorkItem` call that launches an activity that never dies, so we are hijacking a thread from the system threadpool. We suspect this might cause the issue, but we don't have a small repro case yet, and we don't know if it makes any sense.

Thanks!

**Comment by karelz** [comment]
@tmds @wfurt @stephentoub does it ring a bell?
I've seen some troubles around zero reads, but couldn't find bug tracking this specific one ...

**Comment by stephentoub** [comment]
> does it ring a bell?

I'm not aware of any issues related to this.

> What we achieve with this code is

You generally wouldn't do a 0-byte async receive with a buffer.  You generally would either:
- Do the actual async receive you want, using the buffer and as much space from it as you have to spare
- Do a 0-byte async receive with an empty buffer.  The benefit of the 0-byte receive is that you can avoid renting or allocating a buffer until you know data is ready, so calling it with anything other than an empty buffer is strange.

> BeginReceive

In general I'd recommend switching to using the corresponding XxAsync methods and awaiting them, e.g. `int bytesRead = await socket.ReceiveAsync(buffer, cancellationToken);`.  It'll be faster, simpler, and less error prone.

**Comment by psantosl** [comment]
`Do a 0-byte async receive with an empty buffer. The benefit of the 0-byte receive is that you can avoid renting or allocating a buffer until you know data is ready, so calling it with anything other than an empty buffer is strange.`

This is mostly what we do because we don’t use the buffer at all and it is allocated only once. We could pass null.

Regarding the full async: yes, we will eventually do this, but it means making our entire deserialization code async. Now we simply read synchronously once we know there is data available in the socket. We has a very bad experience years ago converting everything to begin/end receive that was actually much slower than the sync code. So, yes; we will move to async but we need to put together some benchmarks first. We heavily use custom binary readers to deserialize, on top of a bunch of streams (buffered, ssl, one to control the traffic and then the network).


Anyway: that doesn’t help us fix our problem. Problem is sometimes the BeginReceive callback is not invoked. It happens rarely but when it does it has a huge negative impact on production. Any hints ?

**Comment by scalablecory** [comment]
If you can supply a small repro that would be very helpful. Your usage appears correct, but you only gave us one line -- I don't think we have enough to help yet.

**Comment by psantosl** [comment]
Yeah, I wish I had a small repro case :-) I have a big production server instead...

I know how few clues I'm giving you. My point is: can you highlight any interactions that could prevent the BeginReceive callback to be invoked? Like if we're doing something wrong in a different place? That would help us find out the wrong spot.

We implement our own threadpool, there are few pieces actually running on the .net threadpool, and the beginreceive is one of them. This dates back from the early days of Mono when you better didn't mess with the threadpool and that's why Remoting had its own and so on.

**Comment by wfurt** [comment]
since this is backed by epoll on Linux, I was wondering if notifications could be lost under load. But I did not find any hints about it.  It seems like the BeginReceive would try to read and return immediately if data is available. If not, we would subscribe and wait for epoll notification. 
Is there any chance you still have IO pending while this is happening @psantosl ? 
It seems like this read on separate thread is the biggest difference from typical use and perhaps repro should focus on that aspect. 
Also strace may give you clues if you can reproduce it with it. 
You should see recv(), most likely returning EAGAION or EWOULDBLOCK, and then epoll subscription. Than you can check for the notification or any other suspicious activity on given socket.

**Comment by psantosl** [comment]
Thanks @wfurt for taking the time to answer, any help is more than welcome.

At this point we suspect we might be killing the ThreadPool in some other place, the system ThreadPool, I mean, and that might be delaying the creation of new threads if all of them are busy. I'm not sure if it makes at all, since I thought the IO threads attending the callback wouldn't be locked by the presence of other threads. Anyway, we're looking for an extreme number of threads in use or something.

**Comment by tmds** [comment]
If this were an issue in Sockets, I think we'd get more reports about it.

> I'm not sure if it makes at all, since I thought the IO threads attending the callback wouldn't be locked by the presence of other threads.

On Unix there are no dedicated IO threads. Completions are queued to the ThreadPool. So if the ThreadPool is exhausted, then Socket completions may be stuck in the queue.

This is different on Windows, where these callbacks run on dedicated IO threads.

**Comment by psantosl** [comment]
That was the issue @tmds : on Linux the ThreadPool was exhausted and this prevented the callback to wakeup timely.
