### ISSUE TITLE
[browser][wasm] Implement JavaScript managed object reference counting 

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#37151]
The current implementation of the InteropServices.JavaScript framework creates a handle to each managed JavaScript object using the GCHandle.Alloc method, which prevents the managed object from being collected. This leads to the developers code being sprinkled with calling Dispose directly or the 'using' construct so that the JavaScript manage objects can be disposed.

The InteropServices.JavaScript should be modified to implement reference counting to facilitate the correct object collection.

**Comment by AaronRobinsonMSFT** [comment]
@kjpou1 Are you referring to the [`Microsoft.JSInterop`](https://docs.microsoft.com/dotnet/api/microsoft.jsinterop) assembly? I am unfamiliar with this "InteropServices.JavaScript"; can you provide a reference to source or package?

**Comment by kjpou1** [comment]
closed by https://github.com/dotnet/runtime/pull/37417
