### ISSUE TITLE
[browser][wasm] The target "GetCopyToPublishDirectoryItems" does not exist in the project

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#37152]
When running tests using the solution file the following error is returned.

command

```bash
./build.sh --arch wasm --os Browser --configuration release --projects src/libraries/System.Net.Http/System.Net.Http.sln
```

Error:

```
runtime/src/libraries/System.Net.Http/src/System.Net.Http.csproj : error MSB4057: The target "GetCopyToPublishDirectoryItems" does not exist in the project.

```

when run via the .cproj file the tests run correctly without the error above.

After talking with Alexander this is probably due to the mobile platform issuing a Publish on the solution.

**Comment by marek-safar** [comment]
@kjpou1 is this issue still relevant?

**Comment by MaximLipnin** [comment]
It's still relevant - I get it when I've built the entire repo and want to re-build some particular solution.

**Comment by kjpou1** [comment]
When I executed the following:

```
./build.sh --arch wasm --os Browser --configuration debug --projects /Users/Jimmy/websharp/projects/runtime/src/libraries/System.Net.Http/System.Net.Http.sln
```

I do not get that error anymore

**Comment by MaximLipnin** [comment]
Kenneth, could you try it for `Release` configuration?
