### ISSUE TITLE
Directory not found exception when using PhysicalFileProvider with non-existant folder

### ISSUE THREAD

**Issue by brgrz** [dotnet/runtime#37155]
### Describe the bug
This might also be how you wanted to design the behaviour of UseStaticFiles() but to me is counterintuitive and dangerous.

The issue lies with using UseStaticFiles() and setting the exclusion to directory that might not exist.

### To Reproduce

Use this is your Startup.cs

			app.UseStaticFiles(new StaticFileOptions
			{
				FileProvider = new PhysicalFileProvider(
					Path.Combine(Directory.GetCurrentDirectory(), "upload")),
				RequestPath = "/upload"
			});

The app will fail to start if ~/upload directory doesn't exist. If you create the ~/upload directory the app will start fine (although a site restart is required at least with IIS).

In my opinion the app (or in this case the PhysicalFileProvider class) should disregard if directory does not exist and just proceed running on (maybe silently logging a warning or not even that).

### Exception

An error occurred while starting the application.
DirectoryNotFoundException: F:\sites\...\upload\
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)

DirectoryNotFoundException: F:\sites\...\upload\
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root)

### Further technical details
- ASP.NET Core 3.1.4

**Comment by maryamariyan** [comment]
This seems like the application behavior is intentional, even for the scenario that you are mentioning. 
Treating a missing file as non-exceptional is a policy decision that your application is free to make. 
You can check for existence and avoid creating the PFP.  The contract of the PFP is to fail on non-existent paths, and as @Tratcher mentioned this is intentional.
