### ISSUE TITLE
System.IO.Pipeline issue : 'The examined position cannot be less than the previously examined position.'`

### ISSUE THREAD

**Issue by Mathew-Kochekkan** [dotnet/runtime#37176]
The following code 

            var pipe = new Pipe(); 
            await pipe.Writer.WriteAsync(new byte[] { 1, 2, 3, 4, 5 }).ConfigureAwait(false);

            var pipeReader = pipe.Reader;
            var r = await pipeReader.ReadAsync().ConfigureAwait(false);
            pipeReader.AdvanceTo(r.Buffer.Start, r.Buffer.End);

            await pipe.Writer.WriteAsync(new byte[] { 1, 2, 3, 4, 5 }).ConfigureAwait(false);

            r = await pipeReader.ReadAsync().ConfigureAwait(false);
            pipeReader.AdvanceTo(r.Buffer.GetPosition(1));

 Throws the following exception
`System.InvalidOperationException: 'The examined position cannot be less than the previously examined position.'`

Is this expected behavior?

If I read from the pipe and get a buffer and decide that I need more data, I will call AdvanceTo(buffer.Start, buffer.End) on the PipeReader and issue another read.

Once I get more data and then decide that I should consume only to a position before the previous Buffer.End, this behavior makes it impossible.

In the above scenario, I will have to call AdvanceT(buffer.Start) and issue Reads till I get the required amount of data. If no more data arrives for some time, this will lead to unnecessary looping.

If the above behavior is as designed, is there anyway to optimize the above scenario?

**Comment by Mathew-Kochekkan** [comment]
Area label would be area-System.IO.Pipelines

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FiniteReality** [comment]
When you call AdvanceTo without a second parameter, it infers the first parameter to be the "end" value. The idea is that you read as much as you can from the ReadOnlySequence in `readResult.Buffer`, and then `AdvanceTo(readPosition, buffer.End)` after you have read as much as you can.

For example, this is how I do most of my reading:
```cs
try
{
    ReadResult result = default;
    while (!result.IsCompleted || !result.Buffer.IsEmpty)
    {
        result = pipeReader.ReadAsync(cancellationToken);
        var buffer = result.Buffer;
        while (TryProcessPayload(ref buffer, out var payload))
        {
            // do something with payload (e.g. if it's a JSON object you need to process)
            // TryProcessPayload should advance the buffer as it reads a valid payload (e.g. an entire JSON object) to the next payload location
        }
        // If TryProcessPayload returned false, we did not have enough data to read a full payload
        // so we tell the PipeReader we at least examined everything, but do not want to advance.
        pipeReader.AdvanceTo(buffer.Start, buffer.End);
    }
}
finally
{
    await pipeReader.CompleteAsync();
}
```

**Comment by halter73** [comment]
https://github.com/dotnet/runtime/blob/fec84ae0b81edd71f6f9f5a20c2e484bc3de3253/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L53

> But if I try to advance to a position before the previous examined position, the exception is thrown

You can advance `consumed` to a position before the previous `examined` position, but `examined` still needs to be >= what `examined` was before. The logic is that if you've examined the data before, it doesn't make much sense to "unexamine" it.

https://github.com/dotnet/runtime/blob/fec84ae0b81edd71f6f9f5a20c2e484bc3de3253/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L41

In the single-parameter version of PipeReader.AdvanceTo(SequencePosition), the parameter represents both `consumed` and `examined`. Generally speaking, if you use the two-parameter version of AdvanceTo once, you should continue using the two-parameter version of AdvanceTo to avoid issues like this.

A non-throwing version of your code could look like the following:

```C#
var pipe = new Pipe(); 
await pipe.Writer.WriteAsync(new byte[] { 1, 2, 3, 4, 5 }).ConfigureAwait(false);

var pipeReader = pipe.Reader;
var r = await pipeReader.ReadAsync().ConfigureAwait(false);
pipeReader.AdvanceTo(r.Buffer.Start, , r.Buffer.End);

await pipe.Writer.WriteAsync(new byte[] { 1, 2, 3, 4, 5 }).ConfigureAwait(false);

r = await pipeReader.ReadAsync().ConfigureAwait(false);

// Note that r.Buffer.End is being used for the examined parameter.
// This will always be >= to the last r.Buffer.End.
pipeReader.AdvanceTo(r.Buffer.GetPosition(1), r.Buffer.End);
```

**Comment by Mathew-Kochekkan** [comment]
> You can advance `consumed` to a position before the previous `examined` position, but `examined` still needs to be >= what `examined` was before. The logic is that if you've examined the data before, it doesn't make much sense to "unexamine" it.
> 
> https://github.com/dotnet/runtime/blob/fec84ae0b81edd71f6f9f5a20c2e484bc3de3253/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L41
> 
> In the single-parameter version of PipeReader.AdvanceTo(SequencePosition), the parameter represents both `consumed` and `examined`. Generally speaking, if you use the two-parameter version of AdvanceTo once, you should continue using the two-parameter version of AdvanceTo to avoid issues like this.

@halter73 Thank you very much for clearing this up. I was under the impression that once a new read is issued, the examined position will be cleared. But as you said, it doesn't make much sense to "unexamine" an examined position.

I have some logic which relies on the assumption of the examined position getting "unexamined" behavior and it was throwing the exception randomly because when sufficient data is available to make a decision on each read, this situation is not going to arise.

It would be helpful if this behavior was mentioned in the documentation for AdvanceTo. I should have checked the source of AdvanceTo on GitHub before making assumptions. Sorry for the trouble and thank you once again.

**Comment by danmosemsft** [comment]
@Mathew-KochekkMatin perhaps you'd offer a PR to clarify docs.microsoft.com? Just click the pencil button in the top right of the doc.

**Comment by Mathew-Kochekkan** [comment]
Created a PR  #4311 (Update PipeReader.xml to add info to AdvanceTo). 

Took a long time being my first PR. Thanks @danmosemsft for guiding me to this opportunity

**Comment by Ninds** [comment]
Hi,

I have hit this problem also.

### Context

_The setup is described at davidfowl/BedrockFramework#65
To summarize :
The service is setup to handle multiple protocols of which one is HTTP. The service is also setup with a (main) Controller AssemblyLoadContext and some worker AssemblyLoadContexts. The controller ALC encapsulates an instance of Kestrel wired up to a socket. The worker ALCs each encapsulate an instant of Kestrel listening on a MemoryTransport.
Upon receiving requests, the Controller Kestrel dispatches (most but not all) requests internally to one of the worker Kestrels hosted in their own isolated ALCs. The main purpose/motivation for this choice of design is that the code servicing the requests cannot be guaranteed to be thread-safe and hence this particular implementation of isolation/sandboxing has been chosen._

The Controller needs to examine (peek)  the data coming in on the PipeReader and dispatch accordingly. However when the PipeReader is handed off to  one of the workers it needs to appear untouched, hence the need for the data in the PipeReader to be “unexamined”. I think this feature, being able to regress the examined position to an earlier location, would be very useful.

Another use case is when wanting to handle https and http on the same port, it’s conceivable that one might want to peek at the first handful of bytes to detect TLS.


Thanks
