### ISSUE TITLE
CollectionExtensions.GetValueOrDefault annotated badly

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#37189]
## Background and Motivation

The API is defined this way.

```cs
namespace System.Collections.Generic
{
    public static class CollectionExtensions
    {
        [return: MaybeNull]
        public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, [AllowNull] TValue defaultValue) where TKey : notnull
```

Since it is defined as returning `MaybeNull`, it has false negative warning when you specify non null `defaultValue`

## Proposed API

I would expect it is defined in a way when non null is specified in `defaultValue` the method is not returning null:

Something like
```cs
        [return: MaybeNull]
        public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, [AllowNull][ReturnNullWhenValueIsNull] TValue defaultValue) where TKey : notnull
```

or:
```cs
        [return: NullWhenArgumentIsNull("defaultValue")]
        public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, [AllowNull][ReturnNullWhenValueIsNull] TValue defaultValue) where TKey : notnull
```

## Usage Examples

```cs
Dictionary<int, Func<int, int>> d;

var f = d.GetValueOrDefault(1, x => x + 1);

// Obviously f is not null here, but it is hard to say that without some annotations help.
f();
```

## Risks

It is not a breaking change, if one used to check the return value, it won't affect the code.

**Comment by stephentoub** [comment]
Neither of those cited attributes exist or are recognized by the C# language/compiler. Any such improvements here would need to start with C# language enhancements. I suggest you open an issue with your proposal in the csharplang repo. Thanks.

**Comment by NN---** [comment]
What about annotating NotNullIfNotNull as mentioned in #3518 ?

```cs
    [return: MaybeNull]
    [return: NotNullIfNotNull("defaultValue")]
    public static TValue GetValueOrDefault<TKey, TValue>(
        this IReadOnlyDictionary<TKey, TValue> dictionary,
        TKey key,
        [AllowNull] TValue defaultValue)
        where TKey : notnull
    {
        return dictionary.TryGetValue(key, out var value) ? value : defaultValue;   
    }
}
```

**Comment by stephentoub** [comment]
> What about annotating NotNullIfNotNull as mentioned in #3518 ?

That wouldn't be accurate. The default value could be non-null, but it could still return null if the dictionary's value for that key was null.

**Comment by NN---** [comment]
Right. Thanks for catching this.
It must be the opposite if there was an attribute: [NullIfNull("defaultValue")]
