### ISSUE TITLE
Q: LoadLibrary fails to load core3.1 (ijwhost) mixed assembly.

### ISSUE THREAD

**Issue by obiwanjacobi** [dotnet/runtime#37194]
[I've edited the question to provide more precise wording- I made some errors in my testing.]

I am trying to load a renamed mixed cpp/cli assembly into a 3rd party unmanaged host - which uses `::LoadLibrary`.  It's is basically the same as #32769 other than the extension of the mixed assembly we're trying to load is renamed from `.dll` to something else (`.vst3` - if that's important).
`::GetLastError` returns 126 (`ERROR_MOD_NOT_FOUND`).

If I feed the 3rd party host a managed `.dll` it loads fine (then errors out at a later stage - but that is expected). If I feed it the mixed assembly with the .dll extension it also does not load (126). The non-dll extension is part of the convention of the 3rd party host app.

I do not understand what is different to [this project](https://github.com/obiwanjacobi/vst.net/tree/netcore3/Source.Core/Code3/Jacobi.Vst3.Interop) with respect to [the project I used in Issue 32769](https://github.com/obiwanjacobi/vst.net/tree/netcore3/Source.Core/Code/Jacobi.Vst.Interop) - which works fine. I all files in one folder, which include the runtimeconfig.json and ijwhost.dll.

Even the setting `COREHOST_TRACE` and `COREHOST_TRACEFILE` env vars do not yield results (no text file created)

Q: Can anyone see what I am missing, any suggestions?
Edit: Q2: Can anybody shed some light on how (nuget) dependencies are loaded? Do I have to traverse the complete dependency tree (is there an object that can do that?) and have all these files in the same folder? The mixed cpp/cli project does not publish its dependencies...?

An alternative solution might be to get `DllExport` working in netCore. I haven't found a library that can do that.

**Comment by vitek-karas** [comment]
@jkoritzinsky @elinor-fung

**Comment by obiwanjacobi** [comment]
Not sure what I did wrong, but loading now works.
Sorry to bother you.

**Comment by obiwanjacobi** [comment]
Okay, I still have something weird (to my eyes).
I can load a mixed assembly into my native test process. But when I rename the mixed assembly it crashes on the first call from native to (mixed) managed.

Is there a dependency on this name staying the same?

**Comment by elinor-fung** [comment]
You should be able to rename the mixed assembly after building.

- Are you renaming both the mixed assembly and the .runtimeconfig.json? Those need to match (the .runtimeconfig.json name is computed based on the assembly name).
- If you set the environment variable `COREHOST_TRACE=1` (and `COREHOST_TRACEFILE=<pathToFile>` to redirect to a file - otherwise it just prints to the console), do you get any errors logged before the crash?

**Comment by obiwanjacobi** [comment]
Doh! it was the runtimeconfig.json.
Thanx!
