### ISSUE TITLE
COM reference: exception is thrown when iterating over Excel cells

### ISSUE THREAD

**Issue by JohnyL** [dotnet/runtime#37191]
### Description
I am trying to iterarate over Excel cells with `foreach`. This is what I have:

### Project file:

```
<ItemGroup>
	<COMReference Include="Microsoft.Office.Excel">
		<Guid>00020813-0000-0000-c000-000000000046</Guid>
		<VersionMajor>1</VersionMajor>
		<VersionMinor>9</VersionMinor>
		<WrapperTool>primary</WrapperTool>
		<Lcid>0</Lcid>
		<Isolated>false</Isolated>
		<EmbedInteropTypes>true</EmbedInteropTypes>
	</COMReference>
</ItemGroup>
```

### C# code:
```
var file_path = @"C:\test_file.xlsx";
var excel = new Excel.Application { Visible = true };
var book = excel.Workbooks.Open(file_path);
var sheet = book.Worksheets[1] as Excel.Worksheet;
var rng = sheet.Range["A1:B3"];

foreach (Excel.Range cell in rng) //or rng.Cells
{
	listBox.Items.Add(cell.Value);
}
```
However, when execution reaches iteration, I get the following error on `foreach` line (`rng` is highlighted):
> System.TypeLoadException: 'Could not load type 'System.Runtime.InteropServices.ComTypes.IEnumerator' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'

![image](https://user-images.githubusercontent.com/7391680/83321900-e8d1ab00-a25b-11ea-9540-f74bb39f8ecd.png)

### Configuration
**Visual Studio**: Community 2019 16.7.0 Preview 1.0
**.NET**: .NET 5.0 Preview 4, .NET Core 3.1, .NET Core 3.0
**OS**: Windows 10 Pro x64 1909 Build 18363.836

### Regression?
The same code works on .NET Framework 4.8.

**Comment by elinor-fung** [comment]
Related: #21690
