### ISSUE TITLE
Make RegexParseException public

### ISSUE THREAD

**Issue by OskarKlintrot** [dotnet/runtime#372]
I'm trying to validate a regex pattern but I can't catch `System.Text.RegularExpressions.RegexParseException` since it's `internal`.

I can solve it by using pattern matching but it feels like a bodge:
```csharp
private static bool IsValidRegex(string pattern)
{
    if (string.IsNullOrEmpty(pattern))
    {
        return false;
    }

    try
    {
        Regex.Match(string.Empty, pattern);
    }
    catch (Exception ex)
        when (ex is ArgumentException)
    {
        return false;
    }

    return true;
}
```

**Comment by OskarKlintrot** [comment]
I have no clue what I'm doing. I could not get it to work yesterday. Today I noticed I had `Common Language Runtime Exceptions` set to `all` so I restored it to default and tried again and then it works just fine! When I select `all` again it still works! Looks like a PEBKAC or a glitch somewhere yesterday :)

**Comment by danmosemsft** [comment]
I see. It’s still probably worth an issue to discuss exposing the offset. If we don’t, we can probably do some cleanup to remove the type.
