### ISSUE TITLE
PublishSingleFile=true causes extraction issues in regards to folders when running inside a Linux docker container

### ISSUE THREAD

**Issue by JustArchi** [dotnet/runtime#37208]
### Description

Hello.

I'm deploying a single-file `netcoreapp3.1` project built with `-p:PublishSingleFile=true`. The output of the build includes several folders, mainly culture-specific resources (such as `pl/Humanizer.resources.dll`) as well as my own custom files that are included as part of `<Content Include="...">`.

When the project is run on Windows or Linux host, everything works as expected and the resulting directory is extracted properly. Here is a sample output of `ls -l` inside the extracted directory of my project (`/var/tmp/.net/root/ArchiSteamFarm/*`) on barebones Linux machine:

![image](https://user-images.githubusercontent.com/1069029/83340773-866cbf00-a2dc-11ea-96c7-43a60a5a5647.png)

However, when the same project is run inside a Linux docker container, the files inside extracted folders are incorrect, as if the dotnet runtime detected a Windows machine by a mistake and used a wrong path separator:

![image](https://user-images.githubusercontent.com/1069029/83340788-aa300500-a2dc-11ea-8bf0-e4580517d836.png)

As you can see, the dotnet host decided to create files named `<folder>\<file>` instead of `<file>` in given `<folder>`. Since `\` is allowed in filename on Linux, this didn't result in any error, apart from weird-looking filenames.

This causes various issues in the running app that come from the missing files - in my case this is incorrectly working localization of the program as well as other issues.

### Configuration

.NET Core on linux, x86 and arm64 docker containers tested with both Windows and Linux docker host.

### Regression?

Can't say, this is the first time I observed this issue.

### Other information

~~In order to reproduce this, I'm pretty sure that it should be easy with any single-file-published project that includes some files inside any folder in the resulting binary (e.g. installing `Humanizer` nuget library will do the trick) and running it inside a Linux docker container.~~ I've just noticed that this actually won't work - see my comment. You need to include the folders with files yourself, e.g. through custom localized resources or `<Content Include="...">`.

Of course you can also use docker container that I noticed the problem with:

```sh
docker run -d --name asf --rm justarchi/archisteamfarm:dotnet-37208
docker exec -it asf /bin/bash
cd /var/tmp/.net/root/ArchiSteamFarm/*
ls -l
```

Building the above docker container yourself is also possible:

```sh
git clone https://github.com/JustArchiNET/ArchiSteamFarm -b 4.2.1.8
cd ArchiSteamFarm
docker build -f Dockerfile.Service.x64 .
```

Thank you in advance for taking a look into this issue. I'd appreciate any workarounds that come to your mind.

**Comment by JustArchi** [comment]
Interesting thing is the fact that structures created by other libraries (such as libs added by `Humanizer`) are actually extracted properly, only ones included directly in the project (such as my own project strings or custom folders) are extracted wrong.

This is getting really weird...

**Comment by JustArchi** [comment]
And yet another anomaly: files 2+ levels deep are actually extracted... properly?

I have example `www/scripts/0.a5ea5a9.chunk.js` file, in the affected docker container it's extracted as `www\scripts/0.a5ea5a9.chunk.js` - that is, a `0.a5ea5a9.chunk.js` in a folder named `www\scripts`.

Now I need headache pills.

**Comment by swaroop-sridhar** [comment]
@JustArchi  thanks for reporting this issue. Can you please provide a small repro for the problem? I'll fix it. Thanks.

**Comment by JustArchi** [comment]
@swaroop-sridhar I've prepared the most minimal repro I could come up with. Please see attached file:

[37208.zip](https://github.com/dotnet/runtime/files/4791801/37208.zip)

Instructions for reproduction (after unpacking the zip file and changing directory to extracted structure, requires docker to be installed, will reproduce properly on both Windows and Linux):

```
docker build -f Dockerfile -t "dotnet:37208" .
docker run -it --rm --name 37208 dotnet:37208

# Another window
docker exec -it 37208 /bin/bash
cd /var/tmp/.net/root/test/*
ls -l
```

Output:

![image](https://user-images.githubusercontent.com/1069029/84885875-ec569600-b093-11ea-8e84-f79c448a9a81.png)

Notice pl-PL\test.resources.dll` file.

Thank you in advance for your help!

**Comment by JustArchi** [comment]
Like I said I'm not sure how this possibly could be reproduced without docker, as it works properly if you run it in native `linux-x64` environment (I had no luck reproducing it on barebones linux), which is why this is a docker repro. This could be a good lead to find out the culprit of this issue.

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/runtime/pull/40699
