### ISSUE TITLE
Tests in CI failing with "Precondition failure: FAILED: IpcStreamFactory::HasActiveConnections"

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#37203]
```
    System.Tests.EnvironmentTests.UserInteractive_WindowsNano [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"

Assert failure(PID 10544 [0x00002930], Thread: 11824 [0x2e30]): Precondition failure: FAILED: IpcStreamFactory::HasActiveConnections()

CORECLR! coreclr_shutdown_2 + 0xA913 (0x71f78183)
CORECLR! GetCLRRuntimeHost + 0x1E1504 (0x7218a874)
KERNEL32! BaseThreadInitThunk + 0x24 (0x774962c4)
NTDLL! RtlSubscribeWnfStateChangeNotification + 0x439 (0x77691e39)
NTDLL! RtlSubscribeWnfStateChangeNotification + 0x404 (0x77691e04)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\diagnosticserver.cpp Line: 32
    Image: C:\h\w\AED50980\p\dotnet.exe

    System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: -45) [FAIL]
      Exit code was -1073740286 but it should have been -45
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(232,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Runtime.Extensions/tests/System/Environment.Exit.cs(28,0): at System.Tests.Environment_Exit.CheckExitCode(Int32 expectedExitCode)
  Finished:    System.Runtime.Extensions.Tests
```

**Comment by jkotas** [comment]
Hit in https://github.com/dotnet/runtime/pull/37201 : https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-37201-merge-bf63b451e84a4684a7/System.Runtime.Extensions.Tests/console.d255b335.log?sv=2019-02-02&se=2020-06-19T14%3A57%3A15Z&sr=c&sp=rl&sig=xhTyelM6RoR0%2BAMTCg9rTviUXl4He2f74D5ZP147JPU%3D

**Comment by tommcdon** [comment]
@josalem

**Comment by josalem** [comment]
Taking a look!

**Comment by josalem** [comment]
After a quick read, it looks like what _might_ be happening is the Diagnostics Server thread is somehow starting _after_ the process has entered the shutdown phase.  The IPC connections have all been closed already as part of shutdown and the precondition fails.  I'll see if I can reproduce this issue locally, but it seems like it would be racy.  How often is this getting hit?  Hopefully it will be sufficient to modify the precondition and check if we started after shutdown began.

**Comment by jkotas** [comment]
>  the Diagnostics Server thread is somehow starting after the process has entered the shutdown phase

This likely means that the diagnostic server thread can be starting at the same time we are entering shutdown phase. Make sure that this behaves correctly.
