### ISSUE TITLE
ArraySegment<T>.Array is never null

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#37215]
ArraySegement constructor never accepts null, however it defines `Array` property as nullable.

https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1.array?view=netcore-3.1

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L41

```cs
        public T[]? Array => _array;
```

**Comment by stephentoub** [comment]
It's a struct, and it's not uncommon to use `default(ArraySegment)`, in which case Array is null.
