### ISSUE TITLE
Remove transport package for extensions

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#37219]
As https://github.com/dotnet/runtime/pull/33515 doesn't contain a description or commit message I can only guess why the transport package was added. My assumption is that this package was used during the migration which should already be completed. Can we remove that package and its infra now?

https://github.com/dotnet/runtime/tree/master/src/libraries/pkg/Microsoft.Extensions.Internal.Transport

cc @ericstj @maryamariyan

**Comment by ericstj** [comment]
No, we need it.  You can see it's purpose in the package description: https://github.com/dotnet/runtime/blob/0bf441b7c837334b61ed96fd988c5c2a1e68917d/src/libraries/pkg/descriptions.json#L210-L211
