### ISSUE TITLE
IdnMapping is now lower-casing inputs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#37229]
In .NET Core 3.1 (and .NET Framework), this repro would print out "ABCDEFG":
```C#
using System;
using System.Globalization;

class Program
{
    static void Main() => Console.WriteLine(new IdnMapping().GetAscii("ABCDEFG"));
}
```
In other words, IdnMapping.GetAscii wouldn't modify the input and would end up returning the original string.

Now in .NET 5, (presumably due to the NLS to ICU change?), it will now output "abcdefg", having forcibly lowercased the input.  This then also defeats the optimization in the GetAscii implementation that tries to return the original string if the input hasn't changed at all.

cc: @tarekgh, @safern, @krwq

**Comment by tarekgh** [comment]
@stephentoub we'll take a look. I assume you are comparing 3.1 to 5.0 on Windows only, right? you didn't try it on Linux.

**Comment by stephentoub** [comment]
Correct. It's possible Linux and/or mac were already lowercasing.

I noticed this due to some some allocation-profiling showing string creations I wasn't expecting, due to calling this with my machine name, which has uppercase letters in it.

**Comment by safern** [comment]
Thanks @stephentoub -- I've self assigned and will take a look.

**Comment by tarekgh** [comment]
I confirmed this is the ICU behavior. I tried the repo on Ubuntu with 3.1 and I can see it lowercase the result.

@safern do we have any doc capturing the behavior differences we are noticing? if not, we can start creating one and capturing that as breaking changes after we switched to ICU.

**Comment by safern** [comment]
@tarekgh should we be concerned about this? 

>  This then also defeats the optimization in the GetAscii implementation that tries to return the original string if the input hasn't changed at all.

> @safern do we have any doc capturing the behavior differences we are noticing? if not, we can start creating one and capturing that as breaking changes after we switched to ICU.

We added these docs, maybe we can capture them there: https://github.com/dotnet/docs/pull/18492

**Comment by stephentoub** [comment]
Can we change https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/System.Private.CoreLib/src/System/Globalization/IdnMapping.cs#L156 to use OrdinalIgnoreCase?

**Comment by tarekgh** [comment]
Actually, looking at the [IDN specs](https://tools.ietf.org/html/rfc3490#section-4.1), it looks to me the ICU behavior is wrong. I am not sure why they are lowercasing it. The spec says:

```
ToASCII never alters a sequence of code points that are all in the 
ASCII range to begin with (although it could fail).  Applying the
ToASCII operation multiple times has exactly the same effect as
applying it just once.
```

so to answer @stephentoub question, I believe yes we can use ordinal ignore case.
