### ISSUE TITLE
Duplicate .props files in packages directories

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#37241]
For each platform, we are adding copy of these files with no visible difference:

```
src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/runtime.$(PlatformName).Microsoft.NETCore.ILAsm.props
src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/runtime.$(PlatformName).Microsoft.NETCore.ILDAsm.props
src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/runtime.$(PlatformName).Microsoft.NETCore.TestHost.props
src/installer/pkg/projects/Microsoft.NETCore.DotNetAppHost/runtime.$(PlatformName).Microsoft.NETCore.DotNetAppHost.props
src/installer/pkg/projects/Microsoft.NETCore.DotNetHost/runtime.$(PlatformName).Microsoft.NETCore.DotNetHost.props
src/installer/pkg/projects/Microsoft.NETCore.DotNetHostPolicy/runtime.$(PlatformName).Microsoft.NETCore.DotNetHostPolicy.props
src/installer/pkg/projects/Microsoft.NETCore.DotNetHostResolver/runtime.$(PlatformName).Microsoft.NETCore.DotNetHostResolver.props
```

@jkotas, @ericstj, is it possible to deduplicate these files? until someday when we may need to do platform-specific specialization (in which case we can probably just override the properties using `Condition=..` attribute without a new file).

**Comment by am11** [comment]
Noticed this when working on enabling cross-compilation on illumos and Solaris. After completing the task, i realized that majority of `lines added` are due to these props files, which is apparently just a noise for each (existing/upcoming) platform.

**Comment by jkotas** [comment]
Delete the .props file and inline their content with the right conditions to the place they are included from?

**Comment by am11** [comment]
Yes, I was thinking something like that, just wasn't sure if something else in the (post-)packaging process is relying on the presence `runtime.$(PlatformName).$(ProjectName).props` files.
