### ISSUE TITLE
[HttpListener] Failure in HttpListener.Start causes HttpListener get disposed automatically

### ISSUE THREAD

**Issue by chenxinyanc** [dotnet/runtime#37242]
### Description
If there is any `Exception` getting thrown from `HttpListener.Start`, `HttpListener._state` will be set to `Closed`.
https://github.com/dotnet/runtime/blob/0ba81ca1bfa1af6288b1717307f21ca4d2037cac/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs#L50-L55

This will make the whole class enter disposed state.

https://github.com/dotnet/runtime/blob/0ba81ca1bfa1af6288b1717307f21ca4d2037cac/src/libraries/System.Net.HttpListener/src/System/Net/HttpListener.cs#L320-L326

This auto-disposing behavior is somewhat surprising, as there is no documentation about this:
https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.start?view=netcore-3.1

Perhaps we should set `_state` to `Stopped` instead of `Closed` for this situation.

### Configuration

.NET Core 3.1

### Regression?

No

### Other information

Sample code
```c#
try
{
    port = ...;
    this.localHttpListener.Prefixes.Add($"http://127.0.0.1:{port}/");
    this.localHttpListener.Start();
}
catch (HttpListenerException)
{
    // e.g. port conflict; let user retry at a later time.
    this.localHttpListener.Prefixes.Clear();    // This will throw ObjectDisposedException.
    throw new Exception("Failed to set up local http listener, please try it again.");
}
```

**Comment by karelz** [comment]
@chenxinyanc did it happen on Linux, Mac or Windows?
Do you know if it is the same behavior on .NET Framework?

**Comment by karelz** [comment]
Triage: Does not seem to be critical for 5.0 -> moving to Future.

**Comment by chenxinyanc** [comment]
It happens on Windows. But they share the same codebase so I suppose the behavior should be the same on other platforms.

A check on referencesource shows that .NET Framework 4.8 has the same behavior: https://referencesource.microsoft.com/#System/net/System/Net/HttpListener.cs,874
```cs
                } catch (Exception exception) {
                    // Make sure the HttpListener instance can't be used if Start() failed.
                    m_State = State.Closed;
                    CloseRequestQueueHandle();
                    CleanupV2Config();
                    if (Logging.On) Logging.Exception(Logging.HttpListener, this, "Start", exception);
                    throw;
                } finally {
```

I'm not sure about the reason why it's necessary to
> Make sure the HttpListener instance can't be used if Start() failed.

but at least the documentation should observe such behavior, which is unfortunately not. Actually such undocumented behavior seems to have led to a bit of surprise: https://stackoverflow.com/questions/11164919/why-httplistener-start-method-dispose-stuff-on-exception
