### ISSUE TITLE
[Question]Does jitter cut empty methods?

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/runtime#37244]
Suppose to have something like 
```cs
public interface ITestabilitySupport
{
    void Step(string stepName);
}
...
public class NopTestabilitySupport : ITestabilitySupport
{
     public void Step(string stepName) { }
}
```

Does jitter elide completely the method invocation?I think so.
I need to inject code only for testing purpose for complex overlapped/race friendly algorithm.

cc: @jkotas @AndyAyersMS

**Comment by hypeartist** [comment]
@MarcoRossignoli just add some `throw` as a method body.

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli just add some throw as a method body.

Mmm not sure...throw will be compiled in production I want a no-op

**Comment by benaadams** [comment]
Put the call in another method (as indirect calls won't be removed e.g. via interface or virtual); and use a conditional attribute on that method https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=netcore-3.1

Then it will only be included if that is defined at compile time; so that could be `[Conditional("DEBUG")]` or something else if you want to include it in release code.

**Comment by MarcoRossignoli** [comment]
> Then it will only be included if that is defined at compile time; so that could be [Conditional("DEBUG")] or something else if you want to include it in release code.

I thought about that...I didn't like the idea to update all CI/local test run and pass a `define` to correctly run(cannot use debug/release because tests run in all configuration but production released). Pay only for ctor DI it's ok, it's not hot code.
It would have been a good feature for code generators with the possibility to modify code.
Another way could be IL post processing, dunno if there is something around.

**Comment by jkotas** [comment]
> Does jitter elide completely the method invocation?I think so.

You can test it using e.g. https://sharplab.io/

The JIT does not see well through abstraction boundaries like interface or virtual methods. If you use any of those, the call is unlikely to be eliminated.

**Comment by MarcoRossignoli** [comment]
Understood, thanks to all.
