### ISSUE TITLE
[mono] Propagate hosting properties through AppContext

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#37240]
See: https://github.com/dotnet/runtime/blob/master/src/mono/mono/mini/monovm.c#L184-L192

While setting the environmental variable works for now, it would be nice to handle this properly, especially since we may want to set other AppContext properties in this fashion. There should be two main components to this work: 
1. Creating helper functions for calling into AppContext from the native side
2. Storing the relevant properties set at host initialization (`monovm_initialize`) until they can be set after runtime startup (`mono_jit_init`)

**Comment by fanyang-mono** [comment]
This functionality has already been supported. The code lives at https://github.com/dotnet/runtime/blob/main/src/mono/mono/metadata/appdomain.c#L1256
