### ISSUE TITLE
Share portions of CoreCLR and Mono CoreLib's ILLinkTrim.xml file

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#37255]
We have duplicate entries between CoreCLR and Mono CoreLib's linker descriptor files.

https://github.com/dotnet/runtime/blob/7493302c99cc258ef8a636398b66fbdb54934245/src/mono/netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml#L746-L814

https://github.com/dotnet/runtime/blob/7493302c99cc258ef8a636398b66fbdb54934245/src/coreclr/src/System.Private.CoreLib/ILLinkTrim.xml#L12-L73

What's worse is that they are now getting out of sync. #36715 and #37083 have modified the CoreCLR version, but didn't modify the Mono version.

We should find a way to have this list in one place (probably under `src/libraries/System.Private.CoreLib`) and use it in both projects.

cc @joperezr

**Comment by marek-safar** [comment]
I think the best goal would be to have no linker descriptor for the shared part and use attributes only.
