### ISSUE TITLE
Reflection heavy CryptoConfig implementation is not illink friendly

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#37250]
The current implementation of [CryptoConfig](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CryptoConfig.cs) is not linker friendly and its flexibility is hurting size constrained workload as there is no simple way to limit supported crypto algorithms.

**Comment by stephentoub** [comment]
In general we discourage the use of it. If memory serves, it was only brought back for compatibility, and against the well-founded objections of @bartonjs. The right answer here may just be to continue to encourage devs to move off of it. Jeremy can correct me if I'm misremembering.

**Comment by bartonjs** [comment]
> If memory serves, it was only brought back for compatibility,

That's correct.  If it's showing up in primary workloads then we should figure out how to restructure the callsites to not need it; but a quick check suggests to me that it should already be dropped out of most applications.  (e.g. in .NET Core `Aes.Create()` doesn't use CryptoConfig, and while `Aes.Create(string)` does, it's not expected that anyone would use it)

**Comment by marek-safar** [comment]
I don't see any warning on API or documentation that we discourage the use of it. Should we make any effort to make this API work with illinker or just change it to PNSE on workloads where we always run linker?

**Comment by jkotas** [comment]
>  Should we make any effort to make this API work with illinker or just change it to PNSE on workloads where we always run illinker?

I think we should mark this API with `RequiresUnreferencedCodeAttribute` to declare that it is not compatible with IL linking.
