### ISSUE TITLE
.NET 5.0 Runtime Epics

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#37269]
# .NET 5.0 Runtime Epics

The .NET 5.0 release is composed of many improvements and features. This issue lists the "epics" that are part of the release (for dotnet/runtime). Beyond these epics are many "features" in this release that are not listed here, because they are not truly epics. An epic is a collection of features that together form a step-function level improvement in .NET, and typically requires the epic owner (a single developer or a small team) to go on a [journey to satisfy the epic goals](https://en.wikipedia.org/wiki/Epic_poetry). Such a journey can require taking great personal risk or fighting dragons, but it's all worth it to make .NET better.

This list will be filled out over the course of the release. Team members working on epics are encouraged to edit this issue directly to add their epic. The order of the epics is arbitrary (like epics should be grouped together). A small set of these 5.0 epics may be enabling early (but partial) support for .NET 6.0 scenarios.

## Libraries

* [Optimize library code using arm64 intrinsics](https://github.com/dotnet/runtime/issues/33308)
* [Enable `net5.0` TFM](https://github.com/dotnet/runtime/issues/34173)
* [Enabling libraries support for iOS, Android, and Xamarin.Mac](https://github.com/dotnet/runtime/issues/35410) (6.0)
* [Improving JsonSerializer functionality and performance](https://github.com/dotnet/runtime/issues/41313)

## Runtime

* [Improving P95+ latency](https://github.com/dotnet/runtime/issues/37534)
* [Improving ARM64 Performance in .NET 5.0 – Closing the gap with x64](https://github.com/dotnet/runtime/issues/35853)
* [Support Windows ARM64](https://github.com/dotnet/runtime/issues/36699)
* [Support Single-File Apps](https://github.com/dotnet/runtime/issues/36590)
* [Support WinRT APIs in .NET 5](https://github.com/dotnet/runtime/issues/35318)
* [Support WebAssembly (Mono Runtime)](https://github.com/dotnet/runtime/issues/38367)

## Tools

* [Roslyn code analyzers for interop](https://github.com/dotnet/runtime/issues/37039)

## Experiments

* [Implement simple version of On Stack Replacement (OSR)](https://github.com/dotnet/runtime/pull/32969)

## Other

* [New Roslyn analyzers for library authors](https://github.com/dotnet/runtime/projects/46)
* [Detect platform-specific API using analyzers](https://github.com/dotnet/runtime/issues/37359)

**Comment by srxqds** [comment]
as this (https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5) show, there are many improvements in .net5, but how about the improvements on mono runtime. because we are embeded .net using mono runtime.

**Comment by richlander** [comment]
In short, no. The longer version is that there are two variants of Mono now, the one in dotnet/runtime that is the future of Mono (and currently only used for web assembly) and the the one in mono/mono that is used for everything else. Xamarin use cases will move to using the Mono in dotnet/runtime in 6.0. For the most part, Mono investments are focused on functional parity with CoreCLR and to improve the specific workloads that the Mono runtime is used for.

**Comment by richlander** [comment]
Closing this issue, with the 5.0 release coming to a close. Thanks for all the reactions to this issue. The reactions and the excitement are very much appreciated, more than you might expect.

A 6.0 epic tracking issue will be created soon.
