### ISSUE TITLE
Fixes to the covariant returns support

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#37265]
This issue tracks changes we will likely want to make to the covariant returns support after the #35308 merge.

- [x] Visit the pointers, byrefs, function pointer returns scenarios and determine if they should be supported, and add test coverage.
- [ ] Add a chapter on the covariant returns to https://github.com/dotnet/runtime/blob/master/docs/design/specs/Ecma-335-Augments.md ? Try to match the style and language used by ECMA-335 (e.g. in the ideal case - we would just copy&paste it over once we figure out how to make edits to ECMA-335).
- [x] Crossgen2 - for performance reasons, we will likely need to burn a MethodFlags bit for RequiresSlotUnification (in the AttributeMetadataCache category) and make this a proper member on MethodDesc.

**Comment by mangod9** [comment]
I believe this work is actually complete. Will wait for @janvorli to confirm though.

**Comment by janvorli** [comment]
@mangod9 the first bullet is completed (I've just marked it as such), but the second and third are not.

**Comment by mangod9** [comment]
ok, moved to 6.0. Guess we can do the documentation update as part of quality week?

**Comment by janvorli** [comment]
It sounds reasonable, thanks!
