### ISSUE TITLE
NullReferenceException in HttpConnectionPoolManager's RemoveStalePools

### ISSUE THREAD

**Issue by cjberg** [dotnet/runtime#37306]
### Description

I have an ASP.NET Core 3.1.3 application running on Azure App Service (Windows/IIS). It has recently crashed randomly on a few occasions since May 15, bringing down the entire worker process. The stack trace found in `eventlog.xml` suggests a possible runtime bug in `HttpConnectionPoolManager.RemoveStalePools()`, a `NullReferenceException`:

```XML
<Event>
  <System>
    <Provider Name=".NET Runtime"/>
    <EventID>1026</EventID>
    <Level>1</Level>
    <Task>0</Task>
    <Keywords>Keywords</Keywords>
    <TimeCreated SystemTime="2020-05-25T09:29:06Z"/>
    <EventRecordID>1006972375</EventRecordID>
    <Channel>Application</Channel>
    <Computer>RD501AC57AB654</Computer>
    <Security/>
  </System>
  <EventData>
    <Data>Application: w3wp.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
 at System.Net.Http.HttpConnectionPoolManager.RemoveStalePools()
 at System.Net.Http.HttpConnectionPoolManager.<>c.<.ctor>b__10_0(Object s)
 at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
 at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
 at System.Threading.TimerQueue.FireNextTimers()
 at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
</Data>
  </EventData>
</Event>
```

The above error has been logged six times. On one occasion, however, another stack trace was logged, also a `NullReferenceException`:

```XML
<Event>
  <System>
    <Provider Name=".NET Runtime"/>
    <EventID>1026</EventID>
    <Level>1</Level>
    <Task>0</Task>
    <Keywords>Keywords</Keywords>
    <TimeCreated SystemTime="2020-05-19T06:19:14Z"/>
    <EventRecordID>477198171</EventRecordID>
    <Channel>Application</Channel>
    <Computer>RD501AC57AB654</Computer>
    <Security/>
  </System>
  <EventData>
    <Data>Application: w3wp.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
 at System.Threading.Overlapped.Free(NativeOverlapped* nativeOverlappedPtr)
 at System.Threading.PreAllocatedOverlapped.System.Threading.IDeferredDisposable.OnFinalRelease(Boolean disposed)
 at System.Threading.DeferredDisposableLifetime`1.Dispose(T obj)
 at System.Threading.PreAllocatedOverlapped.Finalize()
</Data>
  </EventData>
</Event>
```

### Configuration

* Azure App Service, Windows/IIS
* CoreCLR Version: 4.700.20.11803
* .NET Core Version: 3.1.3
* File Version: 13.1.20074.3. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: e81033e094d4663ffd227bb4aed30b76b0631e6d

Kudu reports:
* OS version: Microsoft Windows NT 10.0.14393.0
* 64 bit system: True
* 64 bit process: False
* Processor count: 2

### Regression?

Not neccessarily. It might be code in the application that makes this error more likely to occur. The current code was deployed on May 11.

### Other information

I wish I had more information. I have tried to increase logging and enabled snapshot debugging, so _maybe_ I can get a memory dump the next time it occurs, but it can go days between crashes.

**Comment by stephentoub** [comment]
> so maybe I can get a memory dump the next time it occurs

Thanks, @cjberg.  That would be very helpful.  From a quick glance at the RemoveStalePools method, it's not clear to me where a null ref could be coming from (I've not examined all the methods it calls, other than to see they shouldn't be inlineable and thus should appear in the exception call stack if the null ref was coming from one of them).

**Comment by karelz** [comment]
@cjberg any luck with providing a dump? It does not seem to be actionable at this point for us :(

**Comment by cjberg** [comment]
@karelz Unfortunately, my attempt at using [ProcDumpHelper](https://techcommunity.microsoft.com/t5/azure-app-service/capturing-dumps-on-multiple-instances-automatically-using/ba-p/392394) to capture a memory dump hasn't been successful, so I need to reconfigure it somehow. However, a recent crash produced an improved stacktrace:

```
Application: w3wp.exe
CoreCLR Version: 4.700.20.20201
.NET Core Version: 3.1.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetEnumerator()+MoveNext()
   at System.Net.Http.HttpConnectionPoolManager.RemoveStalePools()
   at System.Net.Http.HttpConnectionPoolManager.<>c.<.ctor>b__10_0(Object s)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

So it occurs during the foreach enumeration of `ConcurrentDictionary<HttpConnectionKey, HttpConnectionPool> _pools` apparently. It sure looks strange, as it's supposed to be thread-safe.

**Comment by stephentoub** [comment]
> Could it be a compiler or JIT error?

In theory, sure.  I think more likely though would be something in the process causing corruption, e.g. something overwriting memory using unsafe code it shouldn't be.  Simply because there have now been three different call stacks failing due to null reference issues.

**Comment by karelz** [comment]
Closing as not actionable -- per discussion above, it seems to be memory corruption induced likely by higher level code.
