### ISSUE TITLE
[Android] Mono runtime should always ask Xamarin.Android to load native shared libraries

### ISSUE THREAD

**Issue by grendello** [dotnet/runtime#37303]
When an application performs a p/invoke, the runtime is tasked with finding the shared library on the filesystem. Mono implements it by taking the name passed to it from the application

```csharp
[DllImport("Foo")]
```

and then performs a number of transformations on the name (`Foo` above) in order to find a native library with system-specific name (e.g. `libFoo.so` on Linux `libFoo.dylib` on macOS and `Foo.dll` on Windows). 
For each library name, Mono probes a number of filesystem locations. On Android, when running as part of `Xamarin.Android`, Mono behaves in the same way but with additional step where it calls to the
`Xamarin.Android` runtime in order to find the shared library. The reason for this is that the native shared libraries shipped in the APK are not installed in any pre-determined location on the filesystem (they are
placed in the application's data directory which has a unique and unpredictable name) or they are not extracted from the APK at all. `Xamarin.Android` runtime knows how to find the libraries and so Mono must
rely on it to do the lookup. However, the version of Mono in `dotnet/runtime` fails to call `Xamarin.Android` for every permutation, instead calling it only for the first one:

```
06-02 12:48:18.645 30770 30770 I monodroid-assembly: Trying to load shared library '/data/app/com.microsoft.net5.helloandroid-z1ONKNMf_Z_s-e7TAU00hw==/lib/arm64/libSystem.Native'
06-02 12:48:18.645 30770 30770 I monodroid-assembly: Shared library '/data/app/com.microsoft.net5.helloandroid-z1ONKNMf_Z_s-e7TAU00hw==/lib/arm64/libSystem.Native' not found
06-02 12:48:18.646 30770 30770 V Mono    : DllImport error loading library 'libSystem.Native': 'dlopen failed: library "libSystem.Native" not found'.
06-02 12:48:18.646 30770 30770 V Mono    : DllImport searching in: 'libSystem.Native' ('libSystem.Native.so').
06-02 12:48:18.646 30770 30770 V Mono    : Searching for 'SystemNative_Stat'.
06-02 12:48:18.646 30770 30770 V Mono    : DllImport attempting to load: 'libSystem.Native'.
06-02 12:48:18.646 30770 30770 V Mono    : DllImport searching in: 'libSystem.Native' ('libSystem.Native.so').
06-02 12:48:18.646 30770 30770 V Mono    : Searching for 'SystemNative_LStat'.
06-02 12:48:18.655 30770 30770 V Mono    : DllImport attempting to load: '__Internal'.
06-02 12:48:18.655 30770 30770 V Mono    : DllImport searching in: '__Internal' ('(null)').
06-02 12:48:18.655 30770 30770 V Mono    : Searching for 'GlobalizationNative_CompareString'.
06-02 12:48:18.677 30770 30770 V Mono    : Request to load System.Private.CoreLib.resources in (domain 0x79530a9100, alc 0x79e8a02a00)
```
Since `libSystem.Native` does not indeed exist, the whole process fails and the application crashes (the `monodroid-assembly` lines are logged by XA runtime, the `Mono` lines by the Mono runtime). In this 
case, the 2nd attempt would have succeeded had the `Xamarin.Android` runtime been called.

Mono in `dotnet/runtime` must be fixed to perform the lookup in the same way as the "traditional" Mono.

/cc @CoffeeFlux

**Comment by akoeplinger** [comment]
I wonder why/how this works in the Android test app we're building in this repo since we should hit the same problem there and I don't see any hooks for that in https://github.com/dotnet/runtime/blob/93b6c449d4f31ddd7d573d1d3769e681d5ebceb9/tools-local/tasks/mobile.tasks/AndroidAppBuilder/Templates/monodroid.c.

**Comment by SamMonoRT** [comment]
Assigning to @akoeplinger and moving to 7.0.0 - not sure why it doesn't repro with sample/functional apps ?

**Comment by akoeplinger** [comment]
@grendello do you know if this is still an issue?

**Comment by grendello** [comment]
From what I see, the current net6 builds no longer show this behavior. Closing then :)
