### ISSUE TITLE
FileSystemEntry.Attributes property is not correct on Unix

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#37301]
### Description

Comes from https://github.com/PowerShell/PowerShell/pull/12834 where custom file enumerator is replaced with .Net FileSystemEnumerator.

_Expectation is that:_
1. FileSystemEntry.Attributes property works the same as FileSystemInfo.Attributes property for Hidden (and perhaps ReadOnly) flags.
2. For Extended Unix flags and Windows Reparse points we need new property FileSystemInfo.ExtendedAttributes.

It turns out the first has a simplified implementation 
https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEntry.Unix.cs#L69-L84

than the second 
https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs#L76-L91

Also CHFLAGS works only on BSD-like systems (MacOS, FreeBSD) but not on Linux. So expectation is that assigning Hidden flag on Linux throws PlatformNotSupportedException - it was very amazing to discover that some PowerShell tests are passed on Linux but really Hidden flag does not work.

**Comment by danmosemsft** [comment]
Was this just an oversight in https://github.com/dotnet/corefx/pull/34560

**Comment by iSazonov** [comment]
@davidkaya @danmosemsft @JeremyKuhne Could you please look the issue? I'd be happy to get the fix for PowerShell.

**Comment by JeremyKuhne** [comment]
@danmosemsft Yes, this looks like an oversight. We should add a comment in both places pointing out the connection if we can't share the code.

@iSazonov I'm no longer on the libraries team, but this should clearly be consistent between the two. @carlossanlop will have to decide the best course of action on throwing. If we can be confident on checking that it isn't supported than throwing seems reasonable to me at first glance.

**Comment by iSazonov** [comment]
If the fix is "to throw" the issue should be fixed in 5.0 milestone - later it will be a breaking change.

**Comment by carlossanlop** [comment]
@iSazonov I marked it for 5.0. Would you have a chance to work on this in the next few days? If not, @Jozkee or I can take over when we get some bandwidth.

**Comment by iSazonov** [comment]
@carlossanlop I have not possibility to develop on Unix :-(

**Comment by danmosemsft** [comment]
@iSazonov even with WSL 2 ? 😃

**Comment by iSazonov** [comment]
@danmosemsft I would like, but my laptop is against  😃

**Comment by carlossanlop** [comment]
@iSazonov can you take a look at [the PR](https://github.com/dotnet/runtime/pull/40641), please?

**Comment by iSazonov** [comment]
@carlossanlop Can we re-open the issue?

**Comment by billwert** [comment]
@daxian-dbw hit this when trying to move Powershell to RC1. Here's the test we should ensure works well when we address this for 6.0:
```
Measure-Command { TabExpansion2 -inputScript "Invoke-Web" -cursorColumn "Invoke-Web".Length }
```

In WSL2 if that takes more than a couple hundred milliseconds, there's a problem. (In .NET 5 RC1 it is ~2.5 seconds due to all the stating.)

**Comment by iSazonov** [comment]
> Priority:3

I wonder how you weight this:
1. There is two code paths which contradict each other
2. There is a clear performance issue
3. Finally, it's just bad design, even wrong

**Comment by jeffhandley** [comment]
@iSazonov Thanks for the comment and feedback. The priority is based on our overall themes and the relative priority of fixing this issue compared to completing other items that the team is committing to for 6.0.0. Even with `Priority:3`, our project plan includes time to work on this issue during the 6.0.0 release cycle.

**Comment by iSazonov** [comment]
@jeffhandley Thanks for clarify! I am trying to speed up PowerShell Core file operation and I hope we get this in the PowerShell milestone. So I have many concerns about .Net file API design and performance. Feel free to ping me when will your team start this work.

**Comment by jeffhandley** [comment]
@iSazonov What timing would enable you to utilize this fix in the PowerShell milestone you're targeting?

**Comment by iSazonov** [comment]
@jeffhandley MSFT PowerShell team said they want to stop big changes before summer and then work only on bugs and stability.

**Comment by iSazonov** [comment]
I added in the OP that is right design should be - "For Extended Unix flags and Windows Reparse points we need new property FileSystemInfo.ExtendedAttributes."
