### ISSUE TITLE
HashSet<T>.EnsureCapacity throws exception after calling Remove

### ISSUE THREAD

**Issue by sglienke** [dotnet/runtime#37314]
### Description

Following code throws an exception on the second call to EnsureCapacity - only happens when Remove was called:

```
var s = new HashSet<int>(new int[] { 1, 2, 3, 4, 5});

Console.WriteLine(s.EnsureCapacity(10));
Console.WriteLine(s.Remove(1));
Console.WriteLine(s.EnsureCapacity(20));
```

### Configuration

Seems to be broken since the introduction of EnsureCapacity in .NET Core 2.1

**Comment by stephentoub** [comment]
Thanks.  Dup of https://github.com/dotnet/runtime/issues/30698 which was fixed for .NET 5 in https://github.com/dotnet/corefx/pull/40638.
