### ISSUE TITLE
JIT: poor codegen for simple ref-to-pointer method

### ISSUE THREAD

**Issue by vvuk** [dotnet/runtime#37313]
[This SharpLab sample](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANmgExAGoAfAAQCYBGAWAChyAGAAnOoDoAlAVwDsM2ALYwOAYQhCADnhhQAynIBu2MDADOAbgYNyAZhb91AQwBmMFtgFzTxtSwASx9QCEAnhg0MA3gxb+WYA8YACoWAFU+E3N3T3UWbxYAcxgMTRYAXwYs+l0DIzMLdQwoHjAMFgAxbAQYAliLEEdnBvUfPwCrTyg+Y1xDdQALaAqhAH0AGRg+JIxB7XoAy2sevsDglnHWhY7/fXXPMMjomFaE3aWWAG0AWVThggBJaVwACju5iCeXgHkpQQgUQ4AEEkklYOp1NglDBHnxcFYrEkAJQAXQuSxSFUS5AA7CxXkFDsiIlFCiD1AAFCBdOSvWCmTZjVrI9I5JbsgIXfbkFAsRQYBqvKxVGp1BosCBzOTIi6+RaXfxbYLxAC8kulUA4yriCw52R0jAM7CQbEoLAAoggMB8Hm16PKlld5INjFApBNjMBuPxBCIOAApbAYADi0zkqleGDcUhgEFMr2qtXqwWRaBY0dj8cTYpTnmRaO5xuopoK5jYfIkUjcDQAPAAVajp+uUAB89JgjLm2HijYzTeWLBbGcosoVioA7oM5BY+01+EJjL0UgR005XCqMQEpzOh+b53xF8u6muWpvx+cL0sMJxjoVWlcmKiWOq7+YKVxO8K+CPkRw36cKqPqieoBDkOR5GaLBiJeSw8nyNyvCSjqKqKyYSsA1AviwBCdsYPC4GkW7+Em4obMA5rqrhtgEURV4BJh4gQNWQoUayFzgUAA==) shows the issue.  This getter:

```c#
public unsafe struct FixedByte
{
    internal ushort m_Length;
    internal byte m_Bytes;

    public byte* UnsafeBytes {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get { return (byte*) Unsafe.AsPointer(ref m_Bytes); }
    }
...
}
```

ends up with poor IL (which I guess is Roslyn's fault):

```
    .method public final hidebysig specialname newslot virtual instance uint8* get_UnsafeBytes () cil managed aggressiveinlining 
    {
        .maxstack 1
        .locals init (
            [0] uint8*
        )

        IL_0000: nop
        IL_0001: ldarg.0
        IL_0002: ldflda uint8 FixedByte::m_Bytes
        IL_0007: call void* [System.Runtime.CompilerServices.Unsafe]System.Runtime.CompilerServices.Unsafe::AsPointer<uint8>(!!0&)
        IL_000c: stloc.0
        IL_000d: br.s IL_000f

        IL_000f: ldloc.0
        IL_0010: ret
    } // end of method FixedByte::get_UnsafeBytes
```

and then ends up with even poorer JIT (that looks entirely unoptimized, e.g. the short jump at L0043 -- is release mode on sharplab maybe not working properly?):

```
FixedByte.get_UnsafeBytes()
    L0000: push rbp
    L0001: sub rsp, 0x30
    L0005: lea rbp, [rsp+0x30]
    L000a: xor eax, eax
    L000c: mov [rbp-8], rax
    L0010: mov [rbp+0x10], rcx
    L0014: cmp dword ptr [0x7ff8587bc320], 0
    L001b: je short L0022
    L001d: call 0x00007ff8b0add1a0
    L0022: nop
    L0023: mov rcx, [rbp+0x10]
    L0027: cmp [rcx], ecx
    L0029: mov rcx, [rbp+0x10]
    L002d: add rcx, 2
    L0031: call System.Runtime.CompilerServices.Unsafe.AsPointer[[System.Byte, System.Private.CoreLib]](Byte ByRef)
    L0036: mov [rbp-0x10], rax
    L003a: mov rax, [rbp-0x10]
    L003e: mov [rbp-8], rax
    L0042: nop
    L0043: jmp short L0045
    L0045: mov rax, [rbp-8]
    L0049: lea rsp, [rbp]
    L004d: pop rbp
    L004e: ret
```

Is this expected?  It seems like this should end up as just a direct address load -- I'm surprised that `AsPointer` isn't understood by the JIT either; is it supposed to be?

**Comment by EgorBo** [comment]
@vvuk looks like sharplab is experiencing some issues - the Debug/Release switch doesn't work.
so the code you see is Debug.

**Comment by tannergooding** [comment]
Here is the updated URL for `Release`: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYG3XNgBmMBrx4zD2FQwASeAEIBPDKpoBvGgy8NgzmACoGAFUuA2MnF1wGNwYAcxgMNQYAXxpU6i1dfSMTXAwoDjAMBgAxXgQYABMIkxBbBz9cd09vMxcoLmxJPVwAC2hi/AB9ABkYLliMXo1qb1NzDq6fPwZhmvVNWe8dZZdAkLCYdeiWua8AbQBZBP7KgElxSQAKa6mIe8eAeTE+CFCWACCsVisFwuF4Chgdy4kjMZliAEoALqnM7xYoxYgAdgYT18ewRwVCOUBuAAChA2jInrBDKshusEUl0nMWd5UTtiCgGPIMDUnmZSuUqjUGBApjIEaiPFszvTjgBeMUSqAsNaNGastKbTnkJBMUgMACiCAwr1uTWoMrm51kvWwUDEI2wwHY3D4AhYACleBgAOLjGTKJ4YRxiGAQQxPMoVap+BFoBih8OR6PCuMuBHIjm6Zj67LGJjckRiRw1AA8ABVyInK6QAHw0mB0qa8KLVpM1+YMOtJ0hS2VnADuvRkJg7dW4+GwnXilUTdlw61RcxHY57hsnXGns6qC4akWlK+8GFYBxy63OdCRDCV5+MpLYzYFXD7CJY96OjSvSM13nS6SZAaDBCCcg6ctylxPIS1pykKsaisA5C3gwlTNtgHCSIkx5eDGIorMAhpKmhliYdhg5zEhwgQKW/KEUyqIAUAA==

**Comment by vvuk** [comment]
Ah ha!  That makes a lot more sense.  Thanks, and sorry for the spam :)
