### ISSUE TITLE
Unable to build downloaded Release 5.0 runtime preview 5 on Ubuntu 16.04

### ISSUE THREAD

**Issue by ppb2020** [dotnet/runtime#37325]
### Description

Downloaded runtime fails to build. A git clone of the same load builds fine.

Steps to reproduce:
1. Download runtime-release-5.0-preview5.zip.
2. unzip runtime-release-5.0-preview5.zip
3. cd runtime-release-5.0-preview5
4. ./build.sh -c debug

First error message:

> /home/ppb2020/.nuget/packages/microsoft.build.tasks.git/1.1.0-beta-20206-02/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory '/home/ppb2020/Downloads/runtime-release-5.0-preview5/tools-local/tasks/installer.tasks'. [/home/ppb2020/Downloads/runtime-release-5.0-preview5/tools-local/tasks/installer.tasks/installer.tasks.csproj] 

Final result:

    0 Warning(s)                                                                                                                            
    1012 Error(s)

### Configuration

.Net Release 5.0-preview5 (same issue with preview4)
Ubuntu 16.04 Linux x64

$ uname -a
Linux <hostname> 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Regression?

Unknown

### Other information

The following sequence builds fine:

1. git clone -b release/5.0-preview5 https://github.com/dotnet/runtime.git
2. cd runtime
3. ./build.sh -c debug

From the error message, there seems to be a dependency on git:

> /home/ppb2020/.nuget/packages/microsoft.build.tasks.git/1.1.0-beta-20206-02/build/Microsoft.Build.Tasks.Git.targets

It should be possible to build .Net without being in a git environment. As well, it should be possible to import the .Net code into a different git directory so that we can manage our (local) changes to the source code.

**Comment by safern** [comment]
Thanks @ppb2020. So basically we use SourceLink for debug symbols and also to get information about the current commit the repo is being built on to embed this data into the file versions, etc. So we unfortunately have a strong dependency to that. However, I think we could workaround this. 

For example, that is just a warning that SourceLink emits, but we build with warnaserror, so I wonder what happens if you try:

`./build.sh --warnaserror false /p:SourceRevisionId=dsfsdf`

cc: @tmat, do you know of a better way to disable source link in the repo?

**Comment by hoyosjs** [comment]
From https://github.com/dotnet/runtime/issues/13846#issuecomment-576429012:

> /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false

**Comment by safern** [comment]
Thanks @hoyosjs 

Also, setting `/p:SourceRevisionId=foo` to a random value would help in order to workaround the native version headers generation.

so something like:

`./build.sh /p:SourceRevisionId=dsfsdf /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false`

**Comment by ppb2020** [comment]
Hello Santiago,

Using the command you proposed, I get 1003 warnings and 29 errors.

I still get the original error "Unable to locate repository [...]".

I will read and reply to the next message in this thread.

Pierre Pierre
--
Pierre Pierre Blais
Principal Software Architect - BlackBerry Advanced Technology Development Labs
Office: +1 (613) 595.3039
Mobile: +1 (613) 608.4035
ppblais@blackberry.com<mailto:ppblais@blackberry.com>

"Real programmers can write assembly code in any language." — Larry Wall
[signature_932933711]

**Comment by ppb2020** [comment]
Hi again,

Using these options, the build is down to 8 warnings and 29 errors. The first error remains the same (as per my initial report).

For reference, here is the exact command I entered:

                ./build.sh --warnaserror false /p:SourceRevision=dsfdsf /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false -c debug | tee /tmp/log.txt

Regards,
Pierre Pierre
--
Pierre Pierre Blais
Principal Software Architect - BlackBerry Advanced Technology Development Labs
Office: +1 (613) 595.3039
Mobile: +1 (613) 608.4035
ppblais@blackberry.com<mailto:ppblais@blackberry.com>

"Real programmers can write assembly code in any language." — Larry Wall
[signature_492812119]

**Comment by ViktorHofer** [comment]
@tmat do you know about this issue? Should we move it sourcelink?

**Comment by tmat** [comment]
I don't see a specific Source Link issue here yet. Seems like it should be first investigated in dotnet/runtime repo and only when a specific issue is found file it in sourcelink repo.

**Comment by ViktorHofer** [comment]
If I understood correctly, this about sourcelink complaining that it can't find GIT information on an clone that doesn't have GIT enabled.

**Comment by hoyosjs** [comment]
@ViktorHofer it feels like it should be disabled in arcade for zip downloads (aka, there's no `.git` folder). We'd need to do that too for native source versioning files in runtime too I believe.

**Comment by ViktorHofer** [comment]
yeah, shouldn't the sourcelink package detect that there's no .git folder? Naively asking as I don't know how this all works...

**Comment by hoyosjs** [comment]
The thing is is you reference sourcelink and you set repository type to be git, an error saying like this is honestly what you want for sanity check. In arcade if you don't disable SCM queries, it's assumed to be a git repo automatically: https://github.com/dotnet/arcade/blob/22d6355c4f3c9ac00b0e3abf9d85f2fb07e4787b/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L32

**Comment by tmat** [comment]
Exactly. If you ask for Source Link (the default for .NET repos) and you can't get it we shouldn't just silently ignore it.

**Comment by tmat** [comment]
The above error is reported as warning by SourceLink: https://github.com/dotnet/sourcelink/blob/f61f34798be0641e4bbfa3a50174c8ee1f4f7ee5/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs#L99

So perhaps what we can do in Arcade SDK is to not treat this specific warning as an error, unless `ContinuousIntegrationBuild` is `true`. CI should definitely fail if Source Link doesn't work.
