### ISSUE TITLE
UDP Multicast not receiving data

### ISSUE THREAD

**Issue by furch23** [dotnet/runtime#37336]
https://stackoverflow.com/questions/55104386/udp-multicast-not-receiving-data

any idea why IPEndPoint localEP = new IPEndPoint(localIPAddr, mcastPort) doesn't work and changing it to IPAddress.Any fixes the issue?

**Comment by karelz** [comment]
Triage: Not critical for 5.0.
@furch23 can you please post here HelloWorld-style repro that we can run locally? (maybe just copy paste from SO?) ... that will simplify investigation.
