### ISSUE TITLE
More Unicode character information (such as script)

### ISSUE THREAD

**Issue by Serentty** [dotnet/runtime#37366]
Right now, it's possible to find the block of a Unicode character using the ``UnicodeRange`` class. However, based on my search of the APIs, it is not possible to find properties such as the script of a character. Since most scripts are divided between many different blocks, with new blocks likely to be added in the future, and many blocks contain a mix of different scripts, the correspondence between ranges and scripts is fairly shaky. Since it seems that .NET already ships with many different Unicode tables, it would be nice to be able to ask the standard library the script of a character instead of using hacky solutions based on ranges.

**Comment by GrabYourPitchforks** [comment]
For context to area owners, the `UnicodeRange` class is intended for use within the `HtmlEncoder` and related classes. It specifies a range of Unicode code points which should be marked as "these don't need to be encoded before going out on the wire." By contrast, the API request here would be for getting Unicode character properties from an arbitrary code point, perhaps via additions to `CharUnicodeInfo`.

**Comment by Serentty** [comment]
Thanks for that context. I didn't realize when I posted this that ``UnicodeRange`` wasn't meant for general use to represent Unicode ranges and blocks, but was specifically part of ``HtmlEncoder``'s API. Yes, I did mean a general API that .NET software could use to get information about code points.

**Comment by Serentty** [comment]
As an example of what this API could look like, I found this NuGet package which provides information using Unicode property tables. However, I think it would make sense for a standard version to work with ``Rune`` instead of ``int`` like this library does. Of course overloads for ``int`` would also be useful for stuff like checking if a code point is an unpaired surrogate.

https://www.nuget.org/packages/UnicodeInformation/

**Comment by GrabYourPitchforks** [comment]
We can't carry full Unicode information within the runtime. It would bloat the size of the runtime by several megabytes. But since we're defaulted to running on top of ICU now, I wonder if we could expose some of those APIs as first-class members from `CharUnicodeInfo`. Would need to let the area owners chime in.

**Comment by tarekgh** [comment]
I think CharUnicodeInfo is the right place for such functionality. I believe we can get get the need information from ICU/NLS. ICU should be supporting that but I am not sure yet of NLS. so we don't have to carry the data. I understand the drawback of that is maybe the Unicode version supported by ICU may be different than the version we support in CharUnicodeInfo but I think it could be acceptable.

**Comment by GrabYourPitchforks** [comment]
In theory if we knew the ICU APIs were available to us we could have `CharUnicodeInfo` ignore its own backing data and call directly into ICU. Then there wouldn't be a discrepancy. I expect this would result in a perf hit, but perhaps that's acceptable?

**Comment by Serentty** [comment]
Hm... I was about to comment that I didn't think that would be a problem, since I couldn't see myself checking character properties in a tight loop. But then I thought about it some more, and I realized that doing something like iterating through a string looking for characters belonging to a certain script is actually a fairly realistic use case. Would the performance hit mostly just be from marshalling?

**Comment by tarekgh** [comment]
> I expect this would result in a perf hit, but perhaps that's acceptable?

If the perf can be a concern, we can cache the script ranges from ICU. I didn't look at the ICU APIs but I guess there could be some way to help optimize it.

**Comment by Serentty** [comment]
I checked the UCD, and the file containing script properties was defined entirely in terms of ranges, not individual code points. So the file itself is quite small, unlike the files for most other properties.

**Comment by tarekgh** [comment]
Cool. I still prefer to try to get the info from ICU as long term we should be fully avoiding carrying any Unicode data. But in the short term, I don't mind carrying some if the size is small. Thanks, @Serentty for the info.
