### ISSUE TITLE
Not able to execute at Linux-arm running at i.MX28 env

### ISSUE THREAD

**Issue by Thraka** [dotnet/runtime#37368]
### Issue moved from docs repo to here

----

_From @heautio on Monday, April 20, 2020 2:38:36 PM_

I'm facing segmentation fault when executing .Net (linux-arm) at openwrt running at imx28 env.

My development env is Ubuntu 18.04.3 LTS and I'm able to cross compile other applications to the same target but not the Hello Word example from .Net. So I think my dev env is ok. I tried also the runtime binaries but the same issue is faced. 

Here is the issue at target board:

root@openwrt:/usr/bin/dotnet/publish# echo $PATH
/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/dotnet/publish
root@openwrt:/usr/bin/dotnet/publish# echo $DOTNET_ROOT
/usr/bin/dotnet/publish
root@openwrt:/usr/bin/dotnet/publish# ./dotnet --info
Segmentation fault
root@openwrt:/usr/bin/dotnet/publish# LD_TRACE_LOADED_OBJECTS=1 /lib/ld-linux.so.3
./dotnet
        libpthread.so.0 =&gt; /lib/libpthread.so.0 (0xb6ed0000)
        libdl.so.2 =&gt; /lib/libdl.so.2 (0xb6ebd000)
        libstdc++.so.6 =&gt; /usr/lib/libstdc++.so.6 (0xb6daa000)
        libm.so.6 =&gt; /lib/libm.so.6 (0xb6ce6000)
        libgcc_s.so.1 =&gt; /lib/libgcc_s.so.1 (0xb6cc9000)
        libc.so.6 =&gt; /lib/libc.so.6 (0xb6b84000)
        ld-linux-armhf.so.3 =&gt; /lib/ld-linux-armhf.so.3 (0xb6b52000)
        /lib/ld-linux-armhf.so.3 =&gt; /lib/ld-linux.so.3 (0xb6efb000)
root@openwrt:/usr/bin/dotnet/publish#

_Copied from original issue: dotnet/docs#17959_

**Comment by janvorli** [comment]
The i.mx28 processor is not compatible with .NET Core. .NET Core requires ARMv7 or ARMv8 instruction architectures while i.mx28 uses very old ARMv5TE one. We don't even support a newer ARMv6. The largest issue here is the JIT that would have to be modified to generate code for that instruction architecture, which is a non-trivial task.

**Comment by janvorli** [comment]
However, with Mono integration happening in .NET 5, it seems that you might be able to use the mono runtime to run .NET stuff on that processor.

**Comment by ViktorHofer** [comment]
Closing as not actionable. The plan is to support Mono on mobile platforms initially and on Desktop later.
