### ISSUE TITLE
Non-BMP Unicode ranges

### ISSUE THREAD

**Issue by Serentty** [dotnet/runtime#37364]
Currently, ``System.Text.Unicode.UnicodeRange`` only supports the BMP. This has the unfortunate consequence that the list of blocks provided ``UnicodeRanges`` leaves out many blocks such as “Transport and Map Symbols” which contain very commonly-used characters such as emoji. It seems that the public interface for this class is already based around ``int32``, so I don't think breaking changes would be necessary for this.

**Comment by GrabYourPitchforks** [comment]
There are no plans at this time to allow `HtmlEncoder` and related types to support supplementary code points in their "never needs escaping" list.

**Comment by Serentty** [comment]
Hm...? What does this have to do with ``HtmlEncoder`` specifically? I thought this was just the general type for Unicode ranges in .NET.

**Comment by Serentty** [comment]
Oh, I just read your response on the issue about character script information. I didn't realize that this class was specifically related to HTML encoding. Its position in the namespace hierarchy didn't make that clear to me.

**Comment by GrabYourPitchforks** [comment]
`UnicodeRange` is intended for use by `HtmlEncoder` and friends. That's why it's in the _System.Text.Encodings.Web_ package.

Check out the `CharUnicodeInfo` class if you're looking for general Unicode character properties. I relabeled the other issue you opened re: exposing more information via these APIs so that the area owners would see it.

**Comment by Serentty** [comment]
Yeah, I guess I was confused about what it was for since it shows up to me as ``System.Text.Unicode.UnicodeRange`` with nothing web-related. Anyway, thanks for figuring out what I was asking.
