### ISSUE TITLE
SslStream.AuthenticateAsClientAsync fails to flush when writing to underlying stream

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#37380]
As originally reported in https://github.com/AArnott/Nerdbank.Streams/issues/186, it seems that when `SslStream` is constructed with an underlying stream that buffers written bytes (thus requiring `FlushAsync` to be called to actually send them out), that `AuthenticateAsClientAsync` and `AuthenticateAsServerAsync` may hang as they wait for a response to bytes they never actually flushed.

It seems at least part of the fault may lie here: 

https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/System.Net.Security/src/System/Net/Security/ReadWriteAdapter.cs#L58-L59

This method is relied on by its caller to transmit bytes, but no `FlushAsync` is ever called.

**Comment by stephentoub** [comment]
cc: @wfurt

**Comment by wfurt** [comment]
I've seen cases when it seems to take long time to get the data out. However I did not expected flush to be mandatory if data are written to underlying stream @stephentoub.
If anything, we should maybe do it in ForceAuthenticationAsync() after we sent out whole frame(s) and before waiting for response.

**Comment by AArnott** [comment]
@wfurt if it helps, [here is the justification](https://github.com/AArnott/Nerdbank.Streams/issues/186#issuecomment-638856475) I gave the original filer as to why it's important to always flush if you depend on the bytes being transmitted.

**Comment by karelz** [comment]
Triage: `Write` should not flush, but higher level operation like `AuthenticationAsClientAsync` (which writes and then reads - i.e. expects stuff to be sent over the wire) should call `FlushAsync`.
We should always assume that the underlying stream can be buffering.
