### ISSUE TITLE
Investigate why IdnMapping with ICU lowercases ASCII inputs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#37385]
From https://github.com/dotnet/runtime/pull/37348#pullrequestreview-423947478

> I think it might be worth looking at why ICU is changing the casing, since as @tarekgh mentioned in: #37229 (comment) since according to the IDN specs it should not change the sequence, so it would be good to understand why it is returns as lowercase.

cc: @safern

**Comment by safern** [comment]
Thanks @stephentoub -- self assigned.

**Comment by tarekgh** [comment]
I took a look and I am seeing ICU forcing lowercasing the ASCII string although is not really required by any spec. 

Looking at ICU code https://github.com/unicode-org/icu/blob/cd56519859e23683f5b9001a1ffb6155dfa0375d/icu4c/source/common/uts46.cpp#L279 it is stating `The normalizer (using uts46.nrm) maps uppercase ASCII letters to lowercase` and the defined table used to lowercase the characters in the line: https://github.com/unicode-org/icu/blob/cd56519859e23683f5b9001a1ffb6155dfa0375d/icu4c/source/common/uts46.cpp#L357.
But the comment claims this done according to `UTS #46` while looking at it https://unicode.org/reports/tr46/#Processing I am seeing it says `2. Normalize. Normalize the domain_name string to Unicode Normalization Form C.`  while normalization C shouldn't lowercase the ASCII characters according to the comment in https://unicode.org/reports/tr15/ which clearly says `Note: Text exclusively containing ASCII characters (U+0000..U+007F) is left unaffected by all of the Normalization Forms.`

I think ICU is not correct but I don't think it will cause any problem. For .NET, I don't think need to lowercase and we should be ok keeping the original string casing.

**Comment by safern** [comment]
Thanks, @tarekgh -- you beat me to look into it. Then I think we can close the issue as it is ICU doing that.
