### ISSUE TITLE
Document a way to use ILVerify to diagnose issues in IL Rewriting with CLR Profiling API

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/runtime#37389]
I find that one of the biggest challenges in working with the CLR Profiling API is attempting to mitigate the risk that a bug in my IL-rewriting logic may produce invalid IL, which would in turn produce catastrophic results at runtime (ExecutionEngineException, InvalidProgramException, etc). 

I think it could be extremely helpful if profiler vendors had a documented way to run ILVerify/PEVerify on assemblies after preforming IL-rewriting / ReJIT. This method could be used as part of integration testing, and also as a very useful debugging aid.

[Someone asked on stackoverflow](https://stackoverflow.com/questions/55793865/creating-a-pe-file-using-imetadataemitsave-tomemory-tostream) if this could be accomplished using `IMetadataEmit::SaveToStream`, but unfortunately that method would only write out the .NET module, not a complete PE that can then be fed to ILVerify/PEVerify.

If anyone has an idea how this could be accomplished, I’d be more than happy to attempt it, and then once I succeed, to open-source/document the approach.

/cc  @noahfalk @davmason @jkotas

**Comment by davmason** [comment]
Closing this - the steps are outlined in this issue, it is unlikely that we will write official documentation on how to achieve this
