### ISSUE TITLE
Delete special casing around non-virtual calls to abstract interface methods

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#37400]
Port dotnet/coreclr#23032 to crossgen2.

The comment `// Backwards compat: calls to abstract interface methods are treated as callvirt` is still present in crossgen2's JitInterface implementation.

Noticed because #37370 was touching nearby lines.

Weird that the test is not failing (?).

**Comment by mangod9** [comment]
is this fixed after @nattress recent change?

**Comment by MichalStrehovsky** [comment]
No, that line is about a dozen lines above Simon's change. I just didn't want to pester him with one more unrelated thing.
