### ISSUE TITLE
`Browser` configuration for libraries is inconsistent with RID graph

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#37439]
https://github.com/dotnet/runtime/pull/34940 added `Browser` RID and made it derive from `any`

https://github.com/dotnet/runtime/pull/35323 made `Browser` configuration in libraries derive from `Linux`

This inconsistency will cause the build of dotnet/runtime to use `linux` and `unix` configurations of libraries for `Browser` during build and test, but those assets will not be used in a customer project that consumes a Nuget package that happens to use `linux` or `unix` RIDs.  In other words, our test results will be wrong and not actually represent the shipping product.  Anything in the runtime pack will work (since it's built with the inconistency, but packaged as `browser`) but we shouldn't rely on this.

We need to make these consistent.  If the runtime graph is the correct thing to use (deriving from `any`), then we need to update `OSGroups.json` to remove any imports from `Browser`.  We also need to go and add `$(NetCoreAppCurrent)-Browser` to projects that that were defining some behavior for Unix or Linux that is desirable for `Browser` configuration.

This is what I was calling out [here](https://github.com/dotnet/runtime/pull/34940#issuecomment-615415135) but it looks like that wasn't clear enough.

**Comment by ericstj** [comment]
The following are the libs that use these configurations today.

<details><summary>Unix (81 libraries)</summary>
<p>

- Microsoft.Win32.Primitives
- Microsoft.Win32.Registry
- System.AppContext
- System.Buffers
- System.Collections
- System.Collections.Concurrent
- System.Console
- System.Diagnostics.Contracts
- System.Diagnostics.Debug
- System.Diagnostics.FileVersionInfo
- System.Diagnostics.StackTrace
- System.Diagnostics.TextWriterTraceListener
- System.Diagnostics.Tools
- System.Diagnostics.Tracing
- System.Drawing.Common
- System.Drawing.Primitives
- System.Globalization
- System.Globalization.Calendars
- System.Globalization.Extensions
- System.IO.Compression
- System.IO.Compression.Brotli
- System.IO.FileSystem
- System.IO.FileSystem.DriveInfo
- System.IO.IsolatedStorage
- System.IO.MemoryMappedFiles
- System.IO.Pipes
- System.IO.Pipes.AccessControl
- System.IO.UnmanagedMemoryStream
- System.Linq.Expressions
- System.Memory
- System.Net.HttpListener
- System.Net.Mail
- System.Net.NameResolution
- System.Net.Ping
- System.Net.Primitives
- System.Net.Requests
- System.Net.Security
- System.Net.Sockets
- System.Net.WebSockets.Client
- System.Numerics.Vectors
- System.Private.Uri
- System.Private.Xml
- System.Private.Xml.Linq
- System.Reflection
- System.Reflection.Emit
- System.Reflection.Emit.ILGeneration
- System.Reflection.Emit.Lightweight
- System.Reflection.Primitives
- System.Reflection.TypeExtensions
- System.Resources.ResourceManager
- System.Runtime
- System.Runtime.Extensions
- System.Runtime.InteropServices
- System.Runtime.InteropServices.RuntimeInformation
- System.Runtime.Intrinsics
- System.Runtime.Intrinsics.Experimental
- System.Runtime.Loader
- System.Runtime.Serialization.Formatters
- System.Security.Cryptography.Algorithms
- System.Security.Cryptography.Csp
- System.Security.Cryptography.Encoding
- System.Security.Cryptography.OpenSsl
- System.Security.Cryptography.X509Certificates
- System.Security.Principal
- System.Security.Principal.Windows
- System.Text.Encoding
- System.Text.Encoding.Extensions
- System.Threading
- System.Threading.Overlapped
- System.Threading.Tasks
- System.Threading.Tasks.Extensions
- System.Threading.Thread
- System.Threading.ThreadPool
- System.Threading.Timer
- System.Utf8String.Experimental
- System.Xml.ReaderWriter
- System.Xml.XDocument
- System.Xml.XmlDocument
- System.Xml.XmlSerializer
- System.Xml.XPath
- System.Xml.XPath.XDocument
</p>
</details>
<details><summary>Linux (8 libraries)</summary>
<p>

- System.Data.Odbc
- System.Diagnostics.Process
- System.Diagnostics.TraceSource
- System.DirectoryServices.Protocols
- System.IO.FileSystem.Watcher
- System.IO.Ports
- System.Net.Http
- System.Net.NetworkInformation

</p>
</details>

**Comment by marek-safar** [comment]
@akoeplinger could you please clean this up. I think the RID graph is correct and we need to update `OSGroups.json` config. It's already causing pain in files like https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System.Net.Http.csproj#L354 and it should also help us with pinvoke(s) cleanup.

**Comment by Anipik** [comment]
Fixed by #37944 browser no longer derives from unix or linux
