### ISSUE TITLE
Compiler error in native coreclr code build on Windows is not printed to console

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#37431]
When I run build locally (e.g. using `build.cmd Clr+Libs` from the root of the repo) and the compilation of coreclr fails due to a bug in the native source code, the compiler error message is not printed to console anymore. It is only recorded in the build log files. 
This is painful and we should fix it so that the error message is printed to console too, as it used to be in the recent past.

**Comment by ivdiazsa** [comment]
I was able to repro by adding some nonsense lines in `gc.cpp`. The message shown in console is like the following:

```powershell
\runtime\src\coreclr\runtime.proj(32,5): error MSB3073: The command ""\runtime\src\coreclr\build-runtime.cmd" -x64 -release -enforcepgo" exited with code 1.
```

As expected, I could see the error when viewing the _Binary Log_. I agree it would make a much better experience to see the errors directly in console. I'm willing to try to fix this, but I'd like to ask for some guidance in this subsystem. Where is the error handler in the build system? It must be somewhere there that the messages are being suppressed.

**Comment by ivdiazsa** [comment]
@trylek @janvorli

**Comment by janvorli** [comment]
@ivdiazsa I don't know how the build filters the messages. But I have at least some hints
* E.g. after trying to build windows x64 debug, the errors end up logged in F:\git\runtime3\artifacts\log\Debug\CoreCLR_Windows_NT__x64__Debug.err text file.
* The build-runtime.cmd script is invoked from src\coreclr\runtime.proj
* Looking at the binlog might reveal what made it swallow the errors in the console output. My guess is that there will be configuration of loggers that would omit errors in the console output.
