### ISSUE TITLE
System.Console.Tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37465]
## System.Console.Tests
- [ ] TermInfo.TermInfoVerification(termToTest: \"screen\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
- [ ] TermInfo.TermInfoVerification(termToTest: \"mach-color\", expectedForeground: \"\\x1b[312m\", expectedBackground: \"\\x1b[412m\", colorValue: 12)
- [ ] TermInfo.TermInfoVerification(termToTest: \"screen\", expectedForeground: \"\\x1b[39m\", expectedBackground: \"\\x1b[49m\", colorValue: 9)
- [ ] TermInfo.TermInfoVerification(termToTest: \"Eterm\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
- [ ] TermInfo.TermInfoVerification(termToTest: \"xterm-256color\", expectedForeground: \"\\x1b[90m\", expectedBackground: \"\\x1b[100m\", colorValue: 8)
- [ ] TermInfo.TermInfoVerification(termToTest: \"wsvt25\", expectedForeground: \"\\x1b[34m\", expectedBackground: \"\\x1b[44m\", colorValue: 4)
- [ ] TermInfo.TermInfoVerification(termToTest: \"xterm-256color\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
- [ ] TermInfo.TermInfoVerification(termToTest: \"mach-color\", expectedForeground: \"\\x1b[35m\", expectedBackground: \"\\x1b[45m\", colorValue: 5)
- [ ] TermInfo.TermInfoVerification(termToTest: \"Eterm\", expectedForeground: \"\\x1b[33m\", expectedBackground: \"\\x1b[43m\", colorValue: 3)
- [ ] TermInfo.TermInfoVerification(termToTest: \"screen\", expectedForeground: \"\\x1b[32m\", expectedBackground: \"\\x1b[42m\", colorValue: 2)
- [ ] TermInfo.TermInfoVerification(termToTest: \"xterm-256color\", expectedForeground: \"\\x1b[31m\", expectedBackground: \"\\x1b[41m\", colorValue: 1)
- [ ] TermInfo.TermInfoVerification(termToTest: \"Eterm\", expectedForeground: \"\\x1b[310m\", expectedBackground: \"\\x1b[410m\", colorValue: 10)
- [ ] TermInfo.TermInfoVerification(termToTest: \"wsvt25\", expectedForeground: \"\\x1b[311m\", expectedBackground: \"\\x1b[411m\", colorValue: 11)
- [ ] TermInfo.TermInfoVerification(termToTest: \"mach-color\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
- [ ] TermInfo.TermInfoVerification(termToTest: \"wsvt25\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
- [ ] TermInfo.VerifyInstalledTermInfosParse
- [ ] TermInfo.TryingToLoadTermThatDoesNotExistDoesNotThrow
- [ ] TermInfo.VerifyTermInfoSupportsNewAndLegacyNcurses

```
TermInfo.TermInfoVerification(termToTest: \"screen\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"mach-color\", expectedForeground: \"\\x1b[312m\", expectedBackground: \"\\x1b[412m\", colorValue: 12)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"screen\", expectedForeground: \"\\x1b[39m\", expectedBackground: \"\\x1b[49m\", colorValue: 9)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"Eterm\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"xterm-256color\", expectedForeground: \"\\x1b[90m\", expectedBackground: \"\\x1b[100m\", colorValue: 8)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"wsvt25\", expectedForeground: \"\\x1b[34m\", expectedBackground: \"\\x1b[44m\", colorValue: 4)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"xterm-256color\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"mach-color\", expectedForeground: \"\\x1b[35m\", expectedBackground: \"\\x1b[45m\", colorValue: 5)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"Eterm\", expectedForeground: \"\\x1b[33m\", expectedBackground: \"\\x1b[43m\", colorValue: 3)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"screen\", expectedForeground: \"\\x1b[32m\", expectedBackground: \"\\x1b[42m\", colorValue: 2)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"xterm-256color\", expectedForeground: \"\\x1b[31m\", expectedBackground: \"\\x1b[41m\", colorValue: 1)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"Eterm\", expectedForeground: \"\\x1b[310m\", expectedBackground: \"\\x1b[410m\", colorValue: 10)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"wsvt25\", expectedForeground: \"\\x1b[311m\", expectedBackground: \"\\x1b[411m\", colorValue: 11)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"mach-color\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TermInfoVerification(termToTest: \"wsvt25\", expectedForeground: \"\\x1b[30m\", expectedBackground: \"\\x1b[40m\", colorValue: 0)
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.VerifyInstalledTermInfosParse
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.TryingToLoadTermThatDoesNotExistDoesNotThrow
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
TermInfo.VerifyTermInfoSupportsNewAndLegacyNcurses
    System.ArgumentNullException : Value cannot be null. (Parameter 'type')
```

## PlatformNotSupportedException
- [ ] CancelKeyPressTests.CanAddAndRemoveHandler
- [ ] ReadAndWrite.OutputEncodingPreamble
- [ ] ReadAndWrite.ReadAndReadLine
- [ ] ReadAndWrite.OutputEncoding
- [ ] SetIn.SetInReadLine
- [ ] SetIn.SetInThrowsOnNull
- [ ] Color.RoundtrippingColor
- [ ] Color.RedirectedOutputDoesNotUseAnsiSequences
- [ ] Color.InvalidColors
- [ ] ConsoleEncoding.TestEncoding(inputString: \"This string has non ascii characters αßΓπΣσµ\")
- [ ] ConsoleEncoding.TestEncoding(inputString: \"\\xd800\")
- [ ] ConsoleEncoding.TestEncoding(inputString: \"This is Ascii string\")
- [ ] ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...)
- [ ] ConsoleEncoding.TestEncoding(inputString: \"This is string have surrogates 𐀀\")
- [ ] ConsoleEncoding.TestValidEncodings
- [ ] SyncTextReader.ReadAsync
- [ ] SyncTextReader.ReadBlockAsync
- [ ] SyncTextReader.ReadLineAsync
- [ ] SyncTextReader.Read
- [ ] SyncTextReader.ReadToEnd
- [ ] SyncTextReader.ReadBlock
- [ ] SyncTextReader.Peek
- [ ] SyncTextReader.ReadToEndAsync
- [ ] TimeOut.OpenStandardXXX_ReadTimeOut
- [ ] TimeOut.OpenStandardXXX_WriteTimeOut
- [ ] TimeOut.OpenStandardXXX_CanTimeOut
- [ ] ThreadSafety.SetStandardXXXCanBeCalledConcurrently
- [ ] ThreadSafety.ReadMayBeCalledConcurrently
- [ ] ThreadSafety.OpenStandardXXXCanBeCalledConcurrently
- [ ] WindowAndCursorProps.GetCursorPosition_Invoke_ReturnsExpected
- [ ] WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop(value: False)
- [ ] WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop(value: True)
- [ ] WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException(value: -1)
- [ ] WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException(value: 32768)
- [ ] WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException(value: 32768)
- [ ] WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException(value: -1)
- [ ] WindowAndCursorProps.LargestWindowHeight_UnixGet_ReturnsExpected
- [ ] WindowAndCursorProps.WindowHeight_GetUnix_Success
- [ ] WindowAndCursorProps.WindowWidth_GetUnix_Success
- [ ] WindowAndCursorProps.BufferWidth_GetUnix_ReturnsWindowWidth
- [ ] WindowAndCursorProps.SetCursorPosition_Invoke_Success
- [ ] WindowAndCursorProps.CursorSize_GetUnix_ReturnsExpected
- [ ] WindowAndCursorProps.LargestWindowWidth_UnixGet_ReturnsExpected
- [ ] WindowAndCursorProps.BufferHeight_GetUnix_ReturnsWindowHeight
- [ ] WindowAndCursorProps.CursorTop_Set_GetReturnsExpected
- [ ] WindowAndCursorProps.CursorLeft_Set_GetReturnsExpected

**Comment by adamsitnik** [comment]
Hi @mdh1418 

I am the new owner of `System.Console` area. This issue had no milestone set in an explicit way so I've set it to `6.0.0` and removed the `untriaged` label as it's something that we clearly need and the label was jut added by the bot.

Thanks,
Adam
