### ISSUE TITLE
Failures in "CoreCLR Common Pri1 Test Build AnyOS AnyCPU" pipeline. 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#37466]
I have rebased my changes on the top of the current master and triggered jitstress and jitstressregs, both have failed with:
```
/Users/runner/runners/2.169.1/work/1/s/eng/liveBuilds.targets(147,5): error : The 'libs' subset must be built before building this project. Missing artifacts: /Users/runner/runners/2.169.1/work/1/s/artifacts/bin/ref/microsoft.netcore.app/Release/ [/Users/runner/runners/2.169.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/CoreCLRTestLibrary.csproj]
##[error]eng/liveBuilds.targets(147,5): error : The 'libs' subset must be built before building this project. Missing artifacts: /Users/runner/runners/2.169.1/work/1/s/artifacts/bin/ref/microsoft.netcore.app/Release/

```
in `CoreCLR Common Pri1 Test Build AnyOS AnyCPU checked` that I have not seen before.
[example](https://dev.azure.com/dnceng/public/_build/results?buildId=672645&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a&t=ea573249-0a9e-59d9-0a41-40ec8869f91f)

I think it could be caused by #37373, @safern could you take a look?

We need stress testing to be green to push two PRs that have been blocked on testing for a few days due to infrastructure issues. It would be very helpful to get this fixed/reverted before new potential disrupting infra changes.

cc @jashook @dotnet/runtime-infrastructure @CarolEidt

**Comment by safern** [comment]
> I think it could be caused by #37373, @safern could you take a look?

I don't see how it could be caused by that, I'm inclined more towards: https://github.com/dotnet/runtime/pull/37274

The warnings where the logs were not found are definitely my fault, but the Common Test Build failure, I don't see how it would be caused by my change.

**Comment by safern** [comment]
The bug is that those ymls don't pass down `liveLibrariesBuildConfig:` parameter when building the test job:
https://github.com/dotnet/runtime/blob/e34ac42289d21a4a7e71d623f574ae1bf16f83b0/eng/pipelines/coreclr/jitstressregs.yml#L43
https://github.com/dotnet/runtime/blob/e34ac42289d21a4a7e71d623f574ae1bf16f83b0/eng/pipelines/common/templates/runtimes/build-test-job.yml#L95-L102

**Comment by safern** [comment]
https://github.com/dotnet/runtime/pull/37468
