### ISSUE TITLE
Microsoft.Extensions.Http.Tests fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37463]
### Microsoft.Extensions.Http.DefaultHttpClientFactoryTest
- [ ] Factory_CleanupCycle_DisposesEligibleHandler

Stack Trace
```
   at Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesEligibleHandler() in /_/src/libraries/Microsoft.Extensions.Http/tests/DefaultHttpClientFactoryTest.cs:line 379
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Hit in #37441 though it's not on andriod but `net5.0-Linux-Debug-x64-Mono_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open`: https://dev.azure.com/dnceng/public/_build/results?buildId=672936&view=ms.vss-test-web.build-test-results-tab&runId=20847372&resultId=101229&paneView=debug

**Comment by v-haren** [comment]
failed again in job: [runtime 20200630.96 ](https://dev.azure.com/dnceng/public/_build/results?buildId=712294&view=ms.vss-test-web.build-test-results-tab&runId=22086060&resultId=101450&paneView=debug)

failed test: Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesEligibleHandler


Error message
~~~
Cleanup entry disposable
Expected: True
Actual: False


Stack trace
   at Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesEligibleHandler() in /_/src/libraries/Microsoft.Extensions.Http/tests/DefaultHttpClientFactoryTest.cs:line 379
--- End of stack trace from previous location ---
~~~

**Comment by mdh1418** [comment]
This test no longer fails on Android, and it is skipped now with attribute `IsPreciseGcSupported`
