### ISSUE TITLE
Add out-of-proc eventing for Activities that don't use DiagnosticListener

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#37467]
### Background
Historically the prescribed way to do distributed tracing was to create a new Activity, then call DiagnosticListener.StartActivity()/StopActivity() to notify other in-proc software components about it.  Today most distributed tracing tools require the application developer to make an a-priori reference to a NuGet library or to do some form of in-proc library injection at runtime but these techniques can be onerous or brittle compared to deploying a stand-alone tool. To resolve these issues I am trying to shift more tools, both 1st and 3rd party, to consider tracing from out-of-process. 

When Activities are emitting notifications using DiagnosticListener we already have a solution to convert the in-proc notifications to out-of-proc notification using DiagnosticSourceEventSource. My concern is that our new Activity API changes encourage people to stop using the DiagnosticListener pattern, and when they do that DiagnosticSourceEventSource will no longer provide a solution to generate out-of-proc events. 

### Request
Augment the functionality in DiagnosticSourceEventSource so that an out-of-proc tool can receive EventSource notifications for Activity start/stop when the Activity uses the new ActivitySource.StartActivity() API. The goal is to keep the design simple and cheap to implement. If further study shows it would take more than a few days of effort I've been deliberating and I don't think this is must-have for .NET 5.

### Rough design
The tool would provide the ActivitySource name and Activity operation name via filter arguments, similar to how tools can provide DiagnosticListener name + activity name now. DiagnosticSourceEventSource would then create an ActivityListener to receive the relevant callbacks. When the callbacks occur we invoke corresponding EventSource methods to emit the events.

**Comment by tarekgh** [comment]
@ericstj This is the issue we talked about and tracking it for 5.0 release. Thanks @noahfalk for logging it.
