### ISSUE TITLE
Add support for MissingMemberHandling to System.Text.Json

### ISSUE THREAD

**Issue by SiggyBar** [dotnet/runtime#37483]
We would love to migrate our ASP.NET Core 3 application from using `Newtonsoft.Json` to `System.Text.Json`.  However, the lack of [support/workaround](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#missingmemberhandling) for `MissingMemberHandling` is a showstopper, because we need a robust way to detect and report deficient `[FromBody]` model binding.  Without this feature, mistakes in the input JSON document can go undetected, and that is not acceptable.

Is adding `MissingMemberHandling` something that is planned for `System.Text.Json`?

EDIT @eiriktsarpalis: API proposal & usage examples added

## API Proposal

```C#
namespace System.Text.Json;

public enum JsonMissingMemberHandling { Ignore = 0, Error = 1 }

public partial class JsonSerializerOptions
{
     // Global configuration
     public JsonMissingMemberHandling MissingMemberHandling { get; set; } = JsonMissingMemberHandling.Ignore;
}
```
```C#
namespace System.Text.Json.Serialization;

// Per-type attribute-level configuration
[AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Interface | AttributeTargets.Struct, AllowMultiple=false, Inherited=false)]
public class JsonMissingMemberHandlingAttribute : JsonAttribute
{
       public JsonMissingMemberHandlingAttribute(JsonMissingMemberHandling missingMemberHandling);
       public JsonMissingMemberHandlingAttribute MissingMemberHandling { get; }
}

namespace System.Text.Json.Serialization.Metadata;

public partial class JsonTypeInfo
{
      // Per-type configuration via contract customization.
      public JsonMissingMemberHandling MissingMemberHandling { get; set; } = JsonMissingMemberHandling.Ignore;
}
```

## API Usage

```C#
JsonSerializer.Deserialize<MyPoco>("""{ "jsonPropertyNotBindingToPocoProperty" : null}"""); // JsonException: member not found

[JsonMissingMemberHandling(JsonMissingMember.Error)]
public class MyPoco { }
```

**Comment by layomia** [comment]
Triage: this can be considered.

Removing `api-suggestion` as there's no [API proposal](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) here.

**Comment by LetMeSleepAlready** [comment]
@ShadyNagy Interesting extension, but I don't see any code that handles the 'MissingMemberHandling.Error' case. So that means it is the default functionality, which is not the intent of this raised ticket.

case:
```

POCO: class { public string member {get;set;} }
JSON: {"membah","some value"}

```
The above will not throw an exception, and there is no way to somehow trap this and act on it.

**Comment by ShadyNagy** [comment]
@LetMeSleepAlready and @SiggyBar 
The Devebetter Team Package updated so you can find cover for your problem here 
https://github.com/DevBetterCom/DevBetter.JsonExtensions/blob/main/tests/DevBetter.JsonExtensions.Tests/SetMissingMemberErrorHandlingTests.cs
Nuget: [DevBetter.JsonExtensions](https://www.nuget.org/packages/DevBetter.JsonExtensions)
Source Code: [DevBetter.JsonExtensions](https://github.com/DevBetterCom/DevBetter.JsonExtensions)


> 
> 
> @ShadyNagy Interesting extension, but I don't see any code that handles the 'MissingMemberHandling.Error' case. So that means it is the default functionality, which is not the intent of this raised ticket.
> 
> case:
> 
> ```
> 
> POCO: class { public string member {get;set;} }
> JSON: {"membah","some value"}
> ```
> 
> The above will not throw an exception, and there is no way to somehow trap this and act on it.

**Comment by SiggyBar** [comment]
@ShadyNagy, have you looked at [Dahomey.Json](https://github.com/dahomey-technologies/Dahomey.Json)?  Maybe these efforts could be joined.

**Comment by shadow-cs** [comment]
I recently stumbled upon this problem and I come to the same conclusion as @LetMeSleepAlready. @eiriktsarpalis could you provide some more insight, whether this feature has any chance of landing and if required is there something the community can do (so maybe pinpoint more areas that might need changing), this would be very helpful to start a PR, thanks 😉

**Comment by eiriktsarpalis** [comment]
@shadow-cs the feature is not in our immediate sights for .NET 7. Hopefully once https://github.com/dotnet/runtime/issues/63686 has been released it should be possible to convert the workaround as described in https://github.com/dotnet/runtime/issues/37483#issuecomment-950774100 into a general-purpose contract resolver.

**Comment by reinux** [comment]
This is a pretty important feature for robust versioning of APIs. Could this be expedited in any way?

**Comment by reinux** [comment]
> @ShadyNagy, have you looked at [Dahomey.Json](https://github.com/dahomey-technologies/Dahomey.Json)? Maybe these efforts could be joined.

This won't handle the opposite case, i.e. throwing an exception if the json is missing a field that's expected by the CLR type. Maybe this is another/solved problem?

Pardon my F#rench:
```
[<CLIMutable>]
type Person = {
  FirstName: string
  LastName: string
  age: int
}

let options = JsonSerializerOptions().SetupExtensions()
options.SetMissingMemberHandling(MissingMemberHandling.Error)

let x = JsonSerializer.Deserialize<Person>("""{"FirstName": "yarr"}""", options)
```

Result:
```
val x: Person = { FirstName = "yarr"
                  LastName = null
                  age = 0 }
```

**Comment by rvanmaanen** [comment]
Any update on this?

**Comment by LetMeSleepAlready** [comment]
@reinux isn't what you are looking for something like json schema?

This is what I use now to solve my original problem (unfortunately in an add-on as .net doesn't have this out of the box).

**Comment by reinux** [comment]
> @reinux isn't what you are looking for something like json schema?
> 
> This is what I use now to solve my original problem (unfortunately in an add-on as .net doesn't have this out of the box).

With some validation, yeah. Are you using the json schema piece that comes with Swashbuckle or something?

**Comment by eiriktsarpalis** [comment]
A sketch of such an API might look as follows:
```C#
namespace System.Text.Json;

public enum JsonMissingMemberHandling { Ignore, Error }

public partial class JsonSerializerOptions
{
     // Global configuration
     public JsonMissingMemberHandling MissingMemberHandling { get; set; } = JsonMissingMemberHandling.Ignore;
}

namespace System.Text.Json.Serialization;

// Per-type attribute-level configuration
[AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple=false, Inherited=false)]
public class JsonMissingMemberHandlingAttribute : JsonAttribute
{
       public JsonMissingMemberHandlingAttribute(JsonMissingMemberHandling missingMemberHandling);
       public JsonMissingMemberHandlingAttribute MissingMemberHandlinger { get; }
}

namespace System.Text.Json.Serialization.Metadata;

public partial class JsonTypeInfo
{
      // Per-type configuration via contract customization.
      public JsonMissingMemberHandling MissingMemberHandling { get; set; } = JsonMissingMemberHandling.Ignore;
}
```

Any implementation would need to validate interoperability of the feature with `JsonExtensionDataAttribute` (possibly failing if both that and `JsonMissingMemberHandling.Error` are specified). 

@krwq thoughts?

**Comment by LetMeSleepAlready** [comment]
How would this work with the 2 separate cases?
1) class member not present in json
2) json member not present in class

**Comment by eiriktsarpalis** [comment]
> class member not present in json

This case is different and has been implemented in #29861. `MissingMemberHandling` only concerns the second case.

**Comment by krwq** [comment]
Theoretically we could also extend JsonTypeInfo (maybe also in the options) and add something along the lines of:

```csharp
Action<object, object, string>? SetMissingProperty { get; set; }, // declaring object, value, property name
```

then such behavior could be controlled per type.

That obviously couldn't be used with conjunction of extension data properties.

**Comment by eiriktsarpalis** [comment]
I like the idea of using a per-type handler, but how would the JSON of the missing property be deserialized into an `object` if we're missing metadata on how to do it?

**Comment by layomia** [comment]
> Action<object, object, string>? SetMissingProperty { get; set; }, // declaring object, value, property name

Is this supposed to be implemented and set by users only (and not the serializer)?

> // different name ideas: SetUnhandledProperty, MissingPropertyHandler

`HandleMissingProperty` seems nice.

**Comment by krwq** [comment]
> Is this supposed to be implemented and set by users only (and not the serializer)?

yes, by default we'd do nothing or use extension data property


@eiriktsarpalis good point, I guess it would need to be Utf8JsonReader (which would require delegate since it would need to be `ref`) or JsonElement/JsonNode instead.

**Comment by eiriktsarpalis** [comment]
> which would require delegate

Given the added complexity, we might want to hold off on adding this unless there is a proven use case. Perhaps focus on exposing enum support for now.

**Comment by eiriktsarpalis** [comment]
Starting with .NET 7, it is possible enable missing member handling for every type [without the added boilerplate](https://github.com/dotnet/runtime/issues/37483#issuecomment-950774100) using a custom resolver:
```C#
var options = new JsonSerializerOptions
{
    TypeInfoResolver = new DefaultJsonTypeInfoResolver
    {
        Modifiers = { AddMissingMemberHandling }
    }
};

string json = """{"Name" : "John", "Surname" : "Doe", "Age" : 99 }""";
// Fails with Unhandled exception. System.Text.Json.JsonException: JSON properties Surname, Age could not bind to any members of type MyPoco
JsonSerializer.Deserialize<MyPoco>(json, options);

static void AddMissingMemberHandling(JsonTypeInfo typeInfo)
{
    if (typeInfo.Kind == JsonTypeInfoKind.Object && 
        typeInfo.Properties.All(prop => !prop.IsExtensionData) &&
        typeInfo.OnDeserialized is null)
    {
        var cwt = new ConditionalWeakTable<object, Dictionary<string, object>>(); // Dynamically attach dictionaries to deserialized objects

        JsonPropertyInfo propertyInfo = typeInfo.CreateJsonPropertyInfo(typeof(Dictionary<string, object>), "__extensionDataAttribute");
        propertyInfo.Get = obj => cwt.TryGetValue(obj, out Dictionary<string, object>? value) ? value : null;
        propertyInfo.Set = (obj, value) => cwt.Add(obj, (Dictionary<string, object>)value!);
        propertyInfo.IsExtensionData = true;
        typeInfo.Properties.Add(propertyInfo);
        typeInfo.OnDeserialized = obj =>
        {
            if (cwt.TryGetValue(obj, out Dictionary<string, object>? dict))
            {
                cwt.Remove(obj);
                throw new JsonException($"JSON properties {String.Join(", ", dict.Keys)} could not bind to any members of type {typeInfo.Type}");
            }
        };
    }
}

public class MyPoco
{
    public string Name { get; set; }
}
```

**Comment by bartonjs** [comment]
* Since the proposal involved a two-enum we asked if a boolean would be better, and the conclusion was yes.  And then it was no.
* While Newtonsoft.Json calls it MissingMemberHandling, that's actually a debatable/confusing name.  The property was specified, but it didn't map to a property/field on the target type (so reflection's MissingMember).
  * So we renamed "MissingMember" to "UnmappedMember".  Sorry, future us.

```C#
namespace System.Text.Json
{
    public enum JsonUnmappedMemberHandling { Skip, Disallow }

    public partial class JsonSerializerOptions
    {
        // Global configuration
        public JsonUnmappedMemberHandling UnmappedMemberHandling { get; set; } = JsonUnmappedMemberHandling.Skip;
    }
}

namespace System.Text.Json.Serialization
{
    // Per-type attribute-level configuration
    [AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Interface | AttributeTargets.Struct, AllowMultiple=false, Inherited=false)]
    public class JsonUnmappedMemberHandlingAttribute : JsonAttribute
    {
        public JsonUnmappedMemberHandlingAttribute(JsonUnmappedMemberHandling unmappedMemberHandling);
        public JsonUnmappedMemberHandling UnmappedMemberHandling { get; }
    }
}

namespace System.Text.Json.Serialization.Metadata
{
    public partial class JsonTypeInfo
    {
        // Per-type configuration via contract customization.
        public JsonUnmappedMemberHandling UnmappedMemberHandling { get; set; }; // defaults to the JsonSerializerOptions value
    }
}
```

**Comment by jeancallisti** [comment]
I don't understand. It's 2022. And we're still devising custom solutions in lengthy conversations, in order to be able to deserialize with the _absolutely basic_ option "IF JSON NO MATCH CLASS, DESERIALIZE NO HAPPY" ?

For the last three years I read that Newtonsoft's Json is dying. and I keep trying to adopt System.Text.Json. And yet I'll _yet again_ go back to Newtonsoft because I'm baffled by the absolutely wacky solutions proposed to address basic scenarios.

**Comment by dbc2** [comment]
FYI, there's a workaround for this in .NET 7.  You can use use [DefaultJsonTypeInfoResolver modifier](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts#modifiers) that adds a synthetic extension data property that throws an error on an unknown property.  

It is, however, a little bit complicated to customize the error message so it shows both the unexpected JSON property name and the file location.

Taken from [this answer](https://stackoverflow.com/a/74996510/3744182) to [ASP.NET Core - System.Text.Json: how to reject unknown properties in payload?](https://stackoverflow.com/questions/74995241/asp-net-core-system-text-json-how-to-reject-unknown-properties-in-payload), first define the following modifier:

```
// A JsonException subclass that allows for a custom message that includes the path, line number and byte position.
public class JsonMissingMemberException : JsonException
{
    readonly string? innerMessage;
    public JsonMissingMemberException() : this(null) { }
    public JsonMissingMemberException(string? innerMessage) : base(innerMessage) => this.innerMessage = innerMessage;
    public JsonMissingMemberException(string? innerMessage, Exception? innerException) : base(innerMessage, innerException) => this.innerMessage = innerMessage;
    protected JsonMissingMemberException(SerializationInfo info, StreamingContext context) : base(info, context) => this.innerMessage = (string?)info.GetValue("innerMessage", typeof(string));
    public override string Message =>
        innerMessage == null
            ? base.Message
            : String.Format("{0} Path: {1} | LineNumber: {2} | BytePositionInLine: {3}.", innerMessage, Path, LineNumber, BytePositionInLine);
    public override void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        base.GetObjectData(info, context);
        info.AddValue("innerMessage", innerMessage);
    }
}

public static class JsonExtensions
{
    class UnknownPropertyDictionary<TModel> : IDictionary<string, JsonElement>
    {       
        static JsonException CreateException(string key, JsonElement value) =>
            new JsonMissingMemberException(String.Format("Unexpected property \"{0}\" encountered while deserializing type {1}.", key, typeof(TModel).FullName));
        
        public void Add(string key, JsonElement value) => throw CreateException(key, value);
        public bool ContainsKey(string key) => false;
        public ICollection<string> Keys => Array.Empty<string>();
        public bool Remove(string key) => false; 
                                    
        public bool TryGetValue(string key, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out JsonElement value) { value = default; return false; }
        public ICollection<JsonElement> Values => Array.Empty<JsonElement>();
        public JsonElement this[string key]
        {
            get => throw new KeyNotFoundException(key);
            set =>  throw CreateException(key, value);
        }
        public void Add(KeyValuePair<string, JsonElement> item) =>  throw CreateException(item.Key, item.Value);
        public void Clear() => throw new NotImplementedException();
        public bool Contains(KeyValuePair<string, JsonElement> item) => false;
        public void CopyTo(KeyValuePair<string, JsonElement>[] array, int arrayIndex) { }
        public int Count => 0;
        public bool IsReadOnly => false;
        public bool Remove(KeyValuePair<string, JsonElement> item) => false;
        public IEnumerator<KeyValuePair<string, JsonElement>> GetEnumerator() => Enumerable.Empty<KeyValuePair<string, JsonElement>>().GetEnumerator();
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { return GetEnumerator(); }
    }

    public static DefaultJsonTypeInfoResolver AddMissingMemberHandlingError(this DefaultJsonTypeInfoResolver resolver)
    {
        resolver.Modifiers.Add(typeInfo => 
                               {
                                   if (typeInfo.Kind != JsonTypeInfoKind.Object)
                                       return;
                                   if (typeInfo.Properties.Any(p => p.IsExtensionData))
                                       return;
                                   var dictionaryType = typeof(UnknownPropertyDictionary<>).MakeGenericType(typeInfo.Type);
                                   JsonPropertyInfo property = typeInfo.CreateJsonPropertyInfo(dictionaryType, "<>ExtensionData");
                                   property.IsExtensionData = true;
                                   property.Get = (obj) => Activator.CreateInstance(dictionaryType);
                                   property.Set = static (obj, val) => { };
                                   typeInfo.Properties.Add(property);
                               });
        return resolver;
    }
}
```
And now configure your options as follows:

```
var options = new JsonSerializerOptions
{
    TypeInfoResolver = new DefaultJsonTypeInfoResolver()
        .AddMissingMemberHandlingError(),
};
``` 
And you will get an exception on a missing member like the following:

```
sonMissingMemberException: Unexpected property "Unknown" encountered while deserializing type Model. Path: $.Unknown | LineNumber: 6 | BytePositionInLine: 16.
   at JsonExtensions.UnknownPropertyDictionary`1.set_Item(String key, JsonElement value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.ReadJsonAndAddExtensionProperty(Object obj, ReadStack& state, Utf8JsonReader& reader)
```

Demo [here](https://dotnetfiddle.net/DbmJfT).
