### ISSUE TITLE
Microsoft.Bcl.AsyncInterfaces and Microsoft.Bcl.HashCode expose reference assemblies

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#37496]
Both of these packages are exposing reference assemblies to desktop projects.  This makes them break when used in a project that uses the workflow compiler, as well as others.  See https://github.com/dotnet/sdk/issues/1522.

We should service 3.1 to fix this by removing the reference assemblies from the package and look for any other new instances of this that may have been introduced in 3.1.

cc @joperezr

**Comment by StephenBonikowsky** [comment]
@andreyns thanks for finding these. Could you provide us with the name of the current package which references this in its closure so we can find any other packages that are also exposing ref assemblies to desktop projects?

**Comment by andreyns** [comment]
@StephenBonikowsky , I believe it was "Microsoft.Extensions.Hosting" for .netstandard 2.0

**Comment by ericstj** [comment]
@andreyns we'd need to see all dependencies you have to be certain that its worth fixing.  We wouldn't want to fix just a couple packages to find out it doesn't unblock the scenario.

**Comment by andreyns** [comment]
I have one more case: `System.BadImageFormatException: 'Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)'`

**Comment by joperezr** [comment]
Yup, we actually took a look couple of weeks ago and found that there were many others in this bucket, in fact just direct dependencies from the Hosting package  you pointed out above has many of these:
```
Microsoft.Bcl.AsyncInterfaces
System.Buffers
System.ComponentModel.Annotations
System.Diagnostics.EventLog
System.Memory
System.Runtime.CompilerServices.Unsafe
System.Security.Principal.Windows
System.Threading.Tasks.Extensions
```

**Comment by ericstj** [comment]
Closing as we found that it's not feasible to eliminate all reference assemblies across all past packages we've shipped.  For folks hitting problems related to reference assemblies the first thing to do is pursue a fix to the component which is attempting to load the reference assembly,  If blocked you can consider a workaround such as https://github.com/dotnet/sdk/issues/1522#issuecomment-324141767.
