### ISSUE TITLE
error: Not found PathtoPublish: /__w/1/s/artifacts/log/Checked

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#37500]
All the Libraries builds in

https://dev.azure.com/dnceng/public/_build/results?buildId=672754&view=results

failed with:

`##[error]Publishing build artifacts failed with an error: Not found PathtoPublish: /__w/1/s/artifacts/log/Checked`

@dotnet/runtime-infrastructure

**Comment by BruceForstall** [comment]
Same for:

https://dev.azure.com/dnceng/public/_build/results?buildId=672785&view=results

**Comment by jashook** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/37466

**Comment by safern** [comment]
Will be fixed by #37468 

as a side note, this is not really failing the build (it is a warning, represented as an error in the timeline, but in the build is just a warning) -- I know azdo is confusing.
