### ISSUE TITLE
Support PInvoke exports via regular LoadLibrary/etc. without setting up runtime first

### ISSUE THREAD

**Issue by MeikTranel** [dotnet/runtime#3750]
As i understand, as of .NET Core 3.0 calling .NET library functions from something like a native wrapper is supported only via the new external host model, where a slew of APIs have to be called before actually being able to hit the .NET Core dll C API endpoint (but this time without the need for rewriting the assembly post-build).

I have been working on a modern replacement for the `UnmanagedExports` NuGet package, which reweaves attributed methods for VTFixUp entries and thus i am naturally interested. See 
https://github.com/MeikTranel/NXPorts for more info.

Can we clarify whether it is a goal to support this feature in parallel to how it worked in .NET Framework.

**Comment by AaronRobinsonMSFT** [comment]
@MeikTranel I have create a project that might help with some of this. It requires the latest .NET 5.0 though.

It uses the `nethost` API and contains a native binary with the desired exports. It doesn't embed the managed assembly nor the JSON files, but does give you an example of how the system could work. You could imagine that using the [Single File](https://github.com/dotnet/runtime/issues/11201) approach that this project could eventually produce a single native binary to deploy.

The project is at https://github.com/AaronRobinsonMSFT/DNNE and is also published https://github.com/AaronRobinsonMSFT/DNNE.

**Comment by MeikTranel** [comment]
I like C99 touch although I don't like installed dependencies, but that's something we can work around. What drives the sweat out of me is the idea of having to supply the marshalling, but I guess that was kind of bound to happen.
Maybe I can work on flowing my integration test suite into your in project, to help get the ball rolling - because tbh writing tests was about 99% of the effort I did on nxports so far.

One last question: have you considered the deployment scenarios yet? Single file standalone, single file framework dependent, regular multi dll output etc?  Are there any theoretical barriers off the top of your head?

**Comment by AaronRobinsonMSFT** [comment]
>I like C99 touch although I don't like installed dependencies, but that's something we can work around.

I assume you mean the requirements for VS or clang on the path? 

If so, you can use the `dnne-gen` tool manually to generate the desired code and I could update it to copy over all the required source, libs, etc into the output dir so you can compile however desired. Feel free to file any suggestions/issues. These kind of scenarios are simple to support.

>What drives the sweat out of me is the idea of having to supply the marshalling, but I guess that was kind of bound to happen.

As in you want the runtime supply that? If so, going the `DNNE.ExportAttribute` approach instead of the `UnmanagedCallersOnlyAttribute` should handle most of that. But then you need to supply a `Delegate` type.

>One last question: have you considered the deployment scenarios yet? Single file standalone, single file framework dependent, regular multi dll output etc? Are there any theoretical barriers off the top of your head?

That is apart of the larger hosting issues. The self contained runtime et al is a hard problem and I am unsure where we are there for components - @vitek-karas could comment more. What would be nice is having the single file solution for libraries, not just applications. If that was done, then we could embed everything for the FDD scenario and have a single native binary.

**Comment by vitek-karas** [comment]
Single file framework dependent is definitely doable. .NET 5 should have support for creating applications like that, currently we don't have any plans to support components. That said I don't see any special problems with it. Especially when combined with the native exports per @AaronRobinsonMSFT 's project this could work very well.

Single file self-contained is very problematic. The plans are for .NET 5 to really only have a true single file for applications on Linux/Mac. Windows will for now still need the runtime to live in a separate .dll (limitations of the diagnostics stack if I remember correctly) but eventually we think it's also doable - for applications. Components are a different story though. The main issue is that we don't support loading multiple .NET Core runtimes into one process. Generic solution for self-contained components would have to allow that somehow. There are also problems with diagnostics (similar to the above) and couple of other cases.

Multi file should work just fine in all cases except self-contained components - same problems as mentioned above.

There's a discussion around a special case of a self-contained component: Basically the host only ever wants to load one managed component - in that case the issues with self-contained and multiple runtimes goes away. There's an interesting discussion on this topic here: https://github.com/dotnet/runtime/issues/35465.
