### ISSUE TITLE
ODBC Connection ISSUE | ERROR [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'MS\LHTU1353438462S$'.

### ISSUE THREAD

**Issue by ImAbhishekTomar** [dotnet/runtime#37519]
### Description
I am facing issue with odbc connection after hosting site on IIS with core 2.2.0
### Configuration

IIS Settings 

Anonymous Auth with  Application Pool Identity
Platform x64
DSN  On 64

### Other information
**CODE**
 ```
try
            {

                string connectionString = "DSN=COBRA;";
                var con = new OdbcConnection(connectionString);
                con.Open();
                var adp = new OdbcDataAdapter("select top 10 name from sys.tables", con);
                var dt = new DataTable();
                adp.Fill(dt);

                string text = "";
                foreach (DataRow row in dt.Rows)
                {
                    text += row["name"].ToString();
                }
                con.Close();
                return Content(text);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
```

**Error On IIS**
ERROR [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'MS\LHTU05CG8520Y2S$'.
ERROR [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'MS\LHTU05CG8520Y2S$'.

_Same code is working on local system_

**Other Settings Picture**

![Capture1](https://user-images.githubusercontent.com/6933841/83923781-8e2ad880-a7a0-11ea-8a68-4e02e0da5569.JPG)
![Capture2](https://user-images.githubusercontent.com/6933841/83923792-91be5f80-a7a0-11ea-9d56-c413d878a78d.JPG)
![Capture3](https://user-images.githubusercontent.com/6933841/83923794-93882300-a7a0-11ea-9acf-5f126930b473.JPG)
![Capture4](https://user-images.githubusercontent.com/6933841/83923795-94b95000-a7a0-11ea-9c1a-a27d5bf273ad.JPG)

**Comment by SteveSyfuhs** [comment]
This is most likely off topic for this repo. This is a SQL Server error. Your computer account `MS\LHTU1353438462S$` doesn't have permission to access the database or server. You need to grant login rights to SQL for this account.
