### ISSUE TITLE
No tests for GlobalizationMode.Invariant

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#37526]
There appear to be 0 tests for managed libraries behaviour with runtime setting of GlobalizationMode.Invariant.

**Comment by safern** [comment]
Actually there is: https://github.com/dotnet/runtime/tree/master/src/libraries/System.Globalization/tests/Invariant

Why did you think there were 0 tests for invariant mode?

**Comment by marek-safar** [comment]
Great! I just had hard time to find them.

**Comment by safern** [comment]
Awesome 😄
