### ISSUE TITLE
Add ability to perform zero byte reads in StreamPipeReader

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#37539]
## Background and Motivation

Bufferless reads are a technique used in a couple of places in ASP.NET Core to avoid renting memory from the memory pool if there's no data available on the socket; this helps when trying to reduce the memory usage for idle connections for applications that are trying to handle a large number of concurrent connections (like websocket based applications).

We'd like to use this for websocket applications to remove the need to allocate any memory (see https://github.com/dotnet/runtime/issues/37122 for an example)

## Proposed API

```diff
namespace System.Collections.Generic
{
    public class StreamPipeReaderOptions 
    {
+      public bool WaitForData { get; set; }
    }
```

WaitForData tells the PipeReader implementation that it should wait for data from the underlying stream before allocating memory. It relies on the stream supporting zero byte reads (which networking and SSL do)

## Usage Examples

``` C#
var reader = PipeReader.Create(stream, new StreamPipeReaderOptions { WaitForData = true })
```

## Numbers in SSLStream

- During TLS Handshakes we allocate an 8K buffer while waiting for the handshake
- During pending TLS reads we allocate a 16K buffer per read
    - The caller then allocates a 4K buffer on top of this so we burn 20K per connection in pooled buffers (that shouldn't be pooled, see https://github.com/dotnet/runtime/issues/49001)

**Comment by terrajobst** [comment]
* Zero byte reads are technically a violation of the `Stream.Read()` contract, but granted many streams probably support it by accident.
* We should have an API on `Stream` instead
* We should validate the `SslStream`, `SocketListenerStream`, `NetworkStream`, and other compression streams
* This should be investigated and the API proposal should be updated

```C#
namespace System.IO.Pipelines
{
    public class StreamPipeReaderOptions
    {
        public bool WaitForData { get; set; }
    }
}
namespace System.IO
{
    public partial class Stream
    {
        public virtual Task WaitForDataAsync() => return Task.CompletedTask;
    }
}
```

**Comment by GrabYourPitchforks** [comment]
For reference, here's the snippet [from MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read):

> Read returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file).

The contrapositive to this statement is "if there might be more data in the stream, `Read` returns a non-zero value." Combined with that `Read` cannot return a negative value and that it cannot return a value greater than the number of bytes requested, the only logical conclusion is that it's a contract violation (per the docs) to pass a zero-length buffer in to the `Read` method. However, since implementations may or may not be checking for zero-length inputs, what this really means is that the behavior is undefined / implementation-dependent.

**Comment by davidfowl** [comment]
Please don't couple the 2 APIs together. If the wrapping Stream doesn't support zero byte reads then it should throw (or return 0 I guess?). When it does though, like SSLStream and NetworkStream, this passthrough should just work.

**Comment by scalablecory** [comment]
> Please don't couple the 2 APIs together. If the wrapping Stream doesn't support zero byte reads then it should throw (or return 0 I guess?). When it does though, like SSLStream and NetworkStream, this passthrough should just work (they are verified and have tests)

What we heard was that it was not critical for Kestrel in 5.0, so a foolproof end-to-end usage is better. If critical, we can accept the API separately and demand good documentation that it expects non-standard Stream behavior.

**Comment by davidfowl** [comment]
It's not critical for Kestrel in 5.0 but that's not the point of this API. I don't mind adding the API to stream either but the purity argument being made doesn't change the API on StreamPipeReader, nor does it change what happens if the underlying Stream doesn't support it. This API is .NET Standard 2.0 so it runs in all the places (where there won't be a new WaitForDataAsync API). 

For all you know, the StreamPipeReader could implement this by doing a big switch statement on the stream type and determine which ones support zero byte reads and throw if that isn't the case.

I'd like the 2 APIs decoupled in general because they don't need overlap.

**Comment by davidfowl** [comment]
I've updated the proposal to add the Stream addition as well.

**Comment by davidfowl** [comment]
@stephentoub I want to take this back to API review as is, without the Stream API.

**Comment by davidfowl** [comment]
Fixed the comment @terrajobst. I updated the API to match the fact that `StreamPipeReaderOptions` is immutable.
