### ISSUE TITLE
[mono] po is not available

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#37537]
Hi,

When build mono:

```
cd src/mono
./autogen.sh --with-llvm=/usr
make
```

[po](https://github.com/mono/mono/tree/master/po) is not availlable:

```
make  all-recursive
make[1]: Entering directory '/home/loongson/zhaixiang/runtime-mips64-dev/src/mono'
Making all in po
/bin/sh: line 20: cd: po: No such file or directory
Makefile:584: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/loongson/zhaixiang/runtime-mips64-dev/src/mono'
Makefile:515: recipe for target 'all' failed
make: *** [all] Error 2

```

Workaround:

```
diff --git a/src/mono/configure.ac b/src/mono/configure.ac
index 6eb961f..3b2c290 100644
--- a/src/mono/configure.ac
+++ b/src/mono/configure.ac
@@ -6360,7 +6360,7 @@ else
                mono_subdirs_ikvm_native=ikvm-native
        fi
 
-       MONO_SUBDIRS="po $mono_subdirs_libgc llvm mono $mono_subdirs_ikvm_native $mono_subdirs_support data runtime scripts man samples $mono_subdirs_tools $mono_subdirs_docs msvc acceptance-tests"
+       MONO_SUBDIRS="$mono_subdirs_libgc llvm mono $mono_subdirs_ikvm_native $mono_subdirs_support data runtime scripts man samples $mono_subdirs_tools $mono_subdirs_docs msvc acceptance-tests"
        MONO_NOINST_SUBDIRS="$mono_subdirs_libgc"
 fi
 
```

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
@Dotnet-GitSync-Bot  

area-Build-mono
area-Infrastructure-mono

**Comment by lambdageek** [comment]
@xiangzhai The recommended way to build mono from this repository is by [following the workflow in docs/](https://github.com/dotnet/runtime/tree/master/docs/workflow/building/mono)

Note that mono in this repo does not produce a standalone mono framework, but simply the MonoVM as part of (not yet released) .NET 5.

If you are interested in using Mono as a cross-platform .NET Framework replacement, please build it from the https://github.com/mono/mono repository, or [download a package for your operating system from mono-project.com](https://www.mono-project.com/download/stable/).

Finally if you're building from source, you can pass the `--disable-nls` option to `configure` to disable using the translations from `po/`.

**Comment by xiangzhai** [comment]
@lambdageek  Thanks!

**Comment by xiangzhai** [comment]
Hi @lambdageek 

I met some issue:  https://github.com/xiangzhai/mono/issues/2  Please give me some hint about porting mono to MIPS64.

Thanks,
Leslie Zhai
