### ISSUE TITLE
IServiceProvider Disposal and Scopes with singletons

### ISSUE THREAD

**Issue by dazinator** [dotnet/runtime#37545]
I think it would be great if IServiceProviders could be Disposed of safely.

At the moment, suppose you build a new service provider having registered a disposable singleton service.

Later you are referencing that IServiceProvider to create various new scopes, perhaps to satisfy incoming requests as asp.net core does, or background jobs.

How can you now safely Dispose of the service provider, and replace it with a new one? If you dispose of it, it will dispose of any singletons, and those singletons may still currently be in use in those other scopes no? This problem only seems to come for singletons, scoped and transient services shouldn't have this problem (but I know there is a transient tracking list, perhaps someone could confirm my assumptions are actually valid here)

I am aware that there are lots of third party implementations of IServiceProvider. But it seems to me that if they are to have the ability to safely dispose of their services, then it may be better for Dispose to be made DisposeAsync(canceltoken) so that they have the folloowing options:

1. Can wait for existing scopes created with CreateScope to become disposed before they dispose of this underlying IServiceProvider, without blocking the thread. A rudimentary scheme would be incrmeent a counter when CreateScope is called and decrement it via a callback when scopes are disposed, and only proceed with dispose when counter hits 0

2. Depending on the strategy for how active scopes are drained down (or not) by the provider, DisposeAsync  may eventually succeed (i.e if the provider refused to create more scopes whilst disposal is in progress) or it may fail for some reason, or the caller could get sick of waiting and signal cancellation of the dispose. Perhaps the site is too busy etc.

**Comment by davidfowl** [comment]
Seems reasonable to implement (except for the overload that takes the cancellation token). It’s not something you’ll be able to rely on though, as it’s not something other containers are required to implement nor would we require at this point as it’s something that can be implemented on top on the container abstraction today.

**Comment by davidfowl** [comment]
This isn’t usually problem in practice when using hosting because shutdown is triggered and gives a grace period before disposal.

**Comment by dazinator** [comment]
@davidfowl guessing doing a shut down at the host level would stop all requests in a web application until the host or a new host was started up again. Im really thinking of restarting individual tenants without stopping or interrupting other tenants traffic by stopping the entire site. The disposeasync just means I wouldn't have to tie up a thread waiting for scopes to be disposed. I can do it without that but it would be blocking so not as efficient. Restarts won't happen often so potentially not a massive deal.

I could do this approach instead I guess:

1. Create my own interface ISuperDuperServiceProvider deriving from IServiceProvider.  It would just add DisposeAsync(cancelToken).
2. It can wrap any existing IServiceProvider implementation today.
3. When handing out a new scope it would increment a counter, return its own wrapper around the underlying providers scope that just calls a callback on dispose to decrement the counter.
4. Additionally it can have a strategy not to hand out new scopes when disposeasync is in progress etc.

I can take this approach. I could even release this as a general purpose nuget package. I think it should work with any underlying IServiceProvider.

Couple of ares though:

Guidance to users would be:

1. Cast HttpContext.ApplicationServices to ISuperDuperServiceProvider and call DisposeAsync().
2. Replace existing asp.net core middleware that creates scope for request with one that does the above cast and calls CreateScopeAsync(csncelToken). The purpose of that would be that if a disposal was in place, that task could run until disposal was complete so the middleare could await it. Once its complete the middleare could try again to see if there was a new ApplicationServices in place (potentially put in some retry logic etc).

I believe this would be a viable approach, its a shame If have to derive my own interface and do casting, rather than just implement a new IServiceProvider that can directly wrap others and give this behavior completely transparently!

**Comment by dazinator** [comment]
One other idea that occurrs is.. having t
IServiceProvider.DisposeAsync passively wait for scopes to dispose before disposing itself is one strategy. It could be combined with actively trying to singal cancellation of those scopes. For example if when CreateScope() was called, if the scope that was returned had a cancellation token, the caller creating the scope (I.e presumably to do something like run a background job etc) could now chose to listen for signal of that scopes cancellation token, and throw (or exit gracefully) when cancellation is signalled, disposing the scope early.

**Comment by dazinator** [comment]
just to state specific use cases i thought would be awesome to enable:

1. Could update the app with no downtime (plugins could be deployed and services reloaded without any requests being dropped.)
2. In a service provider per tenant scenario, a tenant can be "restarted" i.e their service provider disposed and substituted for a new one and other tenants would not be impacted. The bit I'm thinking could be a frameworl objective here is to just facilitate the safe disposal aspect, given scopes are in existence using singletons. Not expecting it to manage any multitenancy aspects of this use case, but I suspect this one common case where it would be desirable to dispose of a service provider.

**Comment by davidfowl** [comment]
> Would you entertain the notion of DI scopes having a cancellation token, and IServiceProvider having a DisposeAsync() to facilitate this kind of active scope cancellation wiring for service provider implementations that want to enabke it do you think?

Seems obscure TBH. I get it but this adds new API and not enough people have had this complaint to make it a priority. Also it wouldn't work in any of the other containers. Those things combined mean it won't get looked at in the short term. 

It is an interesting scenario but I would encourage you to get something working so you can get a better handle on all of the problems and come up with something more comprehensive.  Multitenant applications are important and lots of people are building them today but I haven't seen this request come up yet (mostly because if you care enough it can be layered on top).

**Comment by davidfowl** [comment]
You need to keep track of outstanding requests tied to specific tenants, when you decide to unload the tenant then drain those requests before disposing the tenant's container. I don't think this has anything to do with DI the more I think about it, that's why I think it's important to write a sample. I think most of the logic has to do with coordinating the things that are being shutdown (requests, and background tasks) per tenant and the DI container disposal just happens to be a part of that process.

**Comment by dazinator** [comment]
@davidfowl OK thanks. I'll close this for now then and perhaps reopen once I've got something more concrete to share.

**Comment by dazinator** [comment]
>  You need to keep track of outstanding requests tied to specific tenants, when you decide to unload the tenant then drain those requests before disposing the tenant's container. I don't think this has anything to do with DI the more I think about it

The need to drain requests before disposing the tenants container is the DI issue here. Because the disposal of the IServiceProvider is not safe when scopes are in play. If you solve that issue in DI then the need to track requests to work around it goes away and it also solves it anywhere else a scope may be created like background jobs etc.

But I'll take your advice - this would be easier to examine with a concrete example, I'll give that a go!



Thats the approach I started with too, and do today in one of my apps. But I realised that

**Comment by davidfowl** [comment]
> Solving it there in DI means request draining isn't necessary, and also solves it anywhere else a scope comes into play like background jobs.

I think that's the wrong layering though. It seems wrong to me to rely on DI scopes as the center of the universe. Any object created outside of the container (like things activated using the container as input but not tracked by the container) are broken.

**Comment by dazinator** [comment]
> Any object created outside of the container (like things activated using the container as input but not tracked by the container) are broken.

Thats a good point. I beleive these kind of "extraneous objects" that have been activated (but not tracked), would only be broken if something IDisposable was injected into them where that IDisposable was being tracked. I think if you are injecting an IDisposable that has a lifetime managed by the container, into a service that you are managing outside the container, then you'd design things in such a way that your extraneous service would be disposed when you also dispose of the container. In essence they live and die together. I dont think this is a problem specific to my case, I think you can hit this with DI today, just activate a new class that has an idisposable tracked by the container injected and then dispose of the container and keep hold of the service..

**Comment by dazinator** [comment]
Here is an xunit test that just highlights the issue i'm attemptign to solve:

```
  public class ServiceProvider_Dispose_Tests
    {
        [Fact]
        public void Dispose_Breaks_SingletonIDisposables_In_OtherScopes ()
        {
            var services = new ServiceCollection();
            services.AddSingleton<DisposableService>();
            var rootServiceProvider = services.BuildServiceProvider();

            using var scope = rootServiceProvider.CreateScope();
            var singleton = scope.ServiceProvider.GetRequiredService<DisposableService>();
            singleton.DoSomething(); // all good.

            rootServiceProvider.Dispose(); // now all bad.
            Assert.Throws<ObjectDisposedException>(() => singleton.DoSomething());
        }
    }    


    [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "Simplified for test purposes")]
    public class DisposableService : IDisposable
    {
        public bool WasDisposed { get; set; } = false;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "Simplified for test purposes")]
        public void Dispose()
        {
            WasDisposed = true;
        }

        public void DoSomething()
        {
            if (WasDisposed)
            {
                throw new ObjectDisposedException(nameof(DisposableService));
            }
        }
    }

```

My next step is to look at whether I can make a general purpose wrapper / decorator for any `IServiceProvider` that implements `IDisposable`. My implementation will wrap the inner providers `IServiceScopeFactory` with one that does reference counting of the created scopes. It will also implement IAsyncDisposable and will only call the inner providers dispose method, after waiting fdor that reference count to be 0.  If I can do this, I'll push the above test showing the failure, and the fixed test using the wrapper / decorator in action.

**Comment by davidfowl** [comment]
Yes I understand the problem but that unit test is contrived and doesn't show the problem. If you made the root scope wait on all all scopes for disposal it would turn into a deadlock. The fact is that you have an application that is running things concurrently and you have some logic for determining when to "unload" a tenant. You want to dispose a tenant concurrently when it may be in use and you want to have that work without disturbing any inflight scopes. 

What do you want to happen when new requests come in for that tenant during dispose? I assume you will have logic to safely spin up a new container while the old one is being spun down etc.

**Comment by dazinator** [comment]
> What do you want to happen when new requests come in for that tenant during dispose?

One strategy would be to overlap the new service provider with the old, 
 I.e before disposing the old service provider, build and swap the new service provider into place so that all new requests start creating scopes from the new provider rather than the old provider. The code that does this swap would then await the old provider to be disposed whilst its scopes drain down repreeenting in flight requests at the time and any background job scopes.

> If you made the root scope wait on all all scopes for disposal it would turn into a deadlock.

Yeah if I await disposal of the service provider from within a scope, I can see that being true, but I think this is solvable. I'll try to get a working implmentation and work through the issues including bringing a background job into the equation to see what it ends up looking like.

**Comment by dazinator** [comment]
Well, so far so good. [Here is an implementation](https://github.com/dazinator/serviceprovider-experiment/blob/master/src/DisposableServiceProvider.Tests/DisposableServiceProvider.cs) of an IServiceProvider that can wrap any other, but implements IAsyncDisposable and allows scopes to drain down, before disposing. I added some basic tests:

1. Test shows the deadlock issue does happen (as expected) if you try to `await` the `AsyncDispose()` of the service provider, whilst simultaneously holding onto a scope.
2. Calling AsyncDispose() whilst not holding onto any scope, allows all current scopes to finish before disposing the wrapped serivice provider.

The deadlock issue doesn't worry me too much - given that the code that will want to asyncdispose the service provider will also want to build a new one and swap it into play - I expect that logic to naturally sit outside of holding on to any particular scope created from said service provider anyway. 

However it does get tricky if you wanted to - for example, trigger a restart from an MVC action method and have the response come back confimring the restart completed. The action method is operating within a scope so awaiting any kind of result there would be keeping that scope open. In my case though I am happy just confirming the "restart was initiated" so I can allow the request to complete and the scope to close. Perhaps I will implement a solution for this at the middleware level if I need to - by having a middleware execute prior to scope creation, and orchestrate things there to allow the mvc request to finish and scope to be closed, but keep hold of the request and wait for the service provider async dispose to complete, and only then return the response - something along those lines. Bit overkill for my purposes at present.

**Comment by dazinator** [comment]
The last thing I wanted to show is what scopes would look like if they had a cancellationtoken property that could be signalled when the service provider wants to dispose and is waiting for them to drain down. Knowing that IServiceScope isn't likely to change, I can make this so that anyone wanting to leverage this, can cast IServiceScope to ICancellableScope to get access to that token. This would mean background services can do this and use this token to cancel long running jobs and allow the scopes to drain down more quickly  when the service provider wants to async dispose. I'll add a test showing this.

Just mentioning this for completeness at this point. It looks like with these workarounds in place I should be able to release a general purpose nuget package for this without any framework changes anywhere

**Comment by dazinator** [comment]
@davidfowl - it looks like decorating an IServiceProvider / IServiceScopeFactory is not really possible anyway, so I cannot use this approach to keep track of scopes as they are created even if I wanted to.

So now I am looking at addressing this further up the stack using a combination of:

1. IServiceProvidersFeature (Responsible for creating the scope at the start and disposing of it at the end of a request)
2. Some sort of custom `ITrackedScopeCreator` service that things like background jobs will have to just to CreateScope() instead to ensure that the created scope is tracked.

The problems with this is that:

1. If anything does a CreateScope() directly using the underlying IServiceProvider, the scope will not be tracked. Therefore I can not know whether its safe to dispose of the underlying service provider that contains singletons. For all I know there could be classes hidden in nuget packages that do this - for example does azure service bus create scopes? what about server side blazor? How do I track those?
