### ISSUE TITLE
Request Runtime-bootstrap

### ISSUE THREAD

**Issue by sgf** [dotnet/runtime#37553]
why .net runtime use C++ in the underlying infrastructure.like jit or vm.
Do we(.net) have the ability to remove all C++ code from runtime.

Is it because the description ability of the .net platform language is not enough?
Otherwise, why should the runtime carry code that is not in the language of the .net platform itself?

If it is a question of all .net platform languages, does it prove that any of our languages are not good enough? Can we further improve the description ability of the languages on the .net platform to replace the underlying C++ code.

**Comment by jkotas** [comment]
This is certainly possible. It is just too expensive and it is hard to see how it would make the .NET platform better for .NET users. 

See discussion in https://github.com/dotnet/runtime/issues/10158 for more details. Resolving as duplicate.
