### ISSUE TITLE
The platform manifest should be sorted: order stability is useful for testing

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/runtime#3756]
## Steps to reproduce

1. Installing the .NET Core SDK 3.0.100-rc2-014188 (x86) (Use release/3.0.1XX branch from https://github.com/dotnet/core-sdk)
2. Downloading and extracting the x86 zip archive of the .NET Core SDK
3. Running a folder diff on the extracted SDK and the install folder
Tool WinDiff : [\\bvtsrv2\Team\v-yunwei\Docshare\windiff](\\bvtsrv2\Team\v-yunwei\Docshare\windiff)

## Expected  behavior
Make sure that everything matches

## Actual behavior
The x86 installers have different contents as the x86 zip archives.
**_`.\packs\microsoft.netcore.app.ref\3.0.0-rc1-19455-02\data\platformmanifest.txt   different (C:\Users\e2euser\Downloads\dotnet-sdk-latest-win-x86 is more recent)`_**
![image](https://user-images.githubusercontent.com/33921754/64419923-8d113180-d0d0-11e9-9a3c-47c2dc1e8fe7.png)

Note: The x64 installers include identical contents as the  x64 zip archives.
![image](https://user-images.githubusercontent.com/33921754/64420103-0ad53d00-d0d1-11e9-8ca9-7073e37a3763.png)

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc2-014188
 Commit:    a553bba776

 

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.0.100-rc2-014188\

 

Host (useful for support):
  Version: 3.0.0-rc1-19455-02
  Commit:  caa8d3b1ed

 

.NET Core SDKs installed:
  3.0.100-rc2-014188 [C:\Program Files (x86)\dotnet\sdk]

 

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19453.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19455-02 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19455-02 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

 

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by NikolaMilosavljevic** [comment]
@jkoritzinsky is this tracked by your work in shared FX?

**Comment by jkoritzinsky** [comment]
This is implemented in the templated platform manifest.

**Comment by NicoleWang001** [comment]
With SDK 3.1.107 and 3.1.401, ref files (files on .\packs\Microsoft.AspNetCore.App.Ref\3.1.3\ref\netcoreapp3.1\) on .exe installer is more recent than .zip installer.
![image](https://user-images.githubusercontent.com/1578239/88782816-9ad81580-d1c0-11ea-9991-3d1039096a5c.png)

**Comment by jkoritzinsky** [comment]
Fixed by #38457

**Comment by vdanche** [comment]
@jkoritzinsky Still repro on SDK 3.1.111, ref files (files on .\packs\microsoft.aspnetcore.app.ref\3.1.10\ref\netcoreapp3.1) on .exe installer is more recent than .zip installer.
![image](https://user-images.githubusercontent.com/65637796/100207518-a3f4ab80-2f42-11eb-9054-221099c8e894.png)

**Comment by dagood** [comment]
This issue wasn't tracking a timestamp issue, just sorting the list of files in PlatformManifest.txt. This repo (dotnet/runtime) is also not involved in those files in the SDK. I've filed a new issue for that diff at https://github.com/dotnet/installer/issues/9153.
