### ISSUE TITLE
Test failure: JIT/SIMD/VectorAbs_r/VectorAbs_r.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#37581]
failed in job: [runtime-coreclr jitstress-isas-x86 20200606.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=674945&view=ms.vss-test-web.build-test-results-tab&runId=20920208&resultId=108928&paneView=debug)

Error message
~~~
Return code: 1
Raw output file: /private/tmp/helix/working/B5CB09CF/w/9BD708B8/e/JIT/SIMD/Reports/JIT.SIMD/VectorAbs_r/VectorAbs_r.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B5CB09CF/p/corerun VectorAbs_r.dll ''
Method System.Numerics.Vector1[Single][System.Single]:Abs was compiled but should not have been
Method System.Numerics.Vector1[Double][System.Double]:Abs was compiled but should not have been
Method System.Numerics.Vector1[Int64][System.Int64]:Abs was compiled but should not have been
Method System.Numerics.Vector1[Int32][System.Int32]:Abs was compiled but should not have been
Method System.Numerics.Vector1[Int16][System.Int16]:Abs was compiled but should not have been
Method System.Numerics.Vector1[SByte][System.SByte]:Abs was compiled but should not have been
Method System.Numerics.Vector1[UInt16][System.UInt16]:Abs was compiled but should not have been
Method System.Numerics.Vector1[Byte][System.Byte]:Abs was compiled but should not have been
Method System.Numerics.Vector1[UInt32][System.UInt32]:Abs was compiled but should not have been
Method System.Numerics.Vector1[UInt64][System.UInt64]:Abs was compiled but should not have been
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B5CB09CF/p
> /private/tmp/helix/working/B5CB09CF/w/9BD708B8/e/JIT/SIMD/VectorAbs_r/VectorAbs_r.sh
Expected: True
Actual: False


Stack trace
   at JIT_SIMD._VectorAbs_r_VectorAbs_r_._VectorAbs_r_VectorAbs_r_sh() in /Users/runner/runners/2.169.1/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.SIMD/JIT.SIMD.XUnitWrapper.cs:line 5281
~~~

**Comment by BruceForstall** [comment]
`CoreCLR OSX x64 Checked jitstress_isas_x86_nohwintrinsic @ OSX.1013.Amd64.Open`

```
export COMPlus_EnableBMI1=0
export COMPlus_EnableBMI2=0
export COMPlus_EnableLZCNT=0
export COMPlus_EnableSSE=0
```

The example above in the bug description is just one of many similar failures.

Should this test even be run under these modes, since it appears to be requiring intrinsics are used?

@tannergooding @CarolEidt

**Comment by CarolEidt** [comment]
These tests are problematic, now that we are using HW intrinsics to implement SIMD intrinsics, as I believe @tannergooding has pointed out elsewhere. I think the testing strategy for these probably needs to be reworked, but I'm not certain what would be the best approach.

**Comment by tannergooding** [comment]
The fix for this is already up and just pending review: https://github.com/dotnet/runtime/pull/37459

These tests are failing because `SSE` is disabled and since they are now implemented using `SimdAsHWIntrinsic` that means that they will use the software fallback as well.
A potentially better fix than the one I put up is to also have `IsHardwareAccelerated` return `false` and for the remaining `GT_SIMD` nodes that haven't been ported to also return `nullptr` if `SSE2` or `AdvSimd` aren't supported.

**Comment by BruceForstall** [comment]
Fixed by https://github.com/dotnet/runtime/pull/37459
