### ISSUE TITLE
System.Text.Json: JsonSerializerOptions.IgnoreReadOnlyProperties being ignored

### ISSUE THREAD

**Issue by nathan-alden-sr** [dotnet/runtime#37599]
### Description

`JsonSerializerOptions.IgnoreReadOnlyProperties` seems to be ignored for my specific DTO. I'm not sure why this is happening, but my property is definitely read-only and is definitely being serialized for some reason. Are there exceptions for specific types where read-only properties of those types will be serialized?

### Configuration
```ps
PS > dotnet --version
5.0.100-preview.4.20258.7
```
VS Community 2019 Preview 16.7.0 Preview 2.0
### Example
```cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.ComponentModel;
using System.Text.Json.Serialization;

internal static class Program
{
    private static void Main()
    {
        string json = JsonSerializer.Serialize(
            new JsonBug(),
            new JsonSerializerOptions { WriteIndented = true, IgnoreReadOnlyProperties = true });

        Console.WriteLine(json);
    }
}

public class JsonBug
{
    public JsonBug()
    {
        ListWrapper = new ListWrapper<string>(() => List, a => List = a);
    }

    public IList<string>? List { get; set; }
    // Why is this serialized? It's clearly read-only
    // Adding [JsonIgnore] does avoid serialization
    public ListWrapper<string> ListWrapper { get; }
}

public class ListWrapper<T> : IList<T>
{
    private readonly Func<IList<T>?> _getPropertyDelegate;
    private readonly Action<IList<T>?> _setPropertyDelegate;

    public ListWrapper(Func<IList<T>?> getPropertyDelegate, Action<IList<T>?> setPropertyDelegate)
    {
        _getPropertyDelegate = getPropertyDelegate;
        _setPropertyDelegate = setPropertyDelegate;
    }

    private IList<T> MutableSourceList
    {
        get
        {
            IList<T>? sourceList = _getPropertyDelegate();

            if (sourceList is null)
            {
                _setPropertyDelegate(sourceList = new List<T>());
            }

            return sourceList;
        }
    }

    private IList<T> ReadOnlySourceList => _getPropertyDelegate() ?? ImmutableList<T>.Empty;

    public T this[int index]
    {
        get => ReadOnlySourceList[index];
        set => MutableSourceList[index] = value;
    }

    public int Count => ReadOnlySourceList.Count;
    public bool IsReadOnly => ReadOnlySourceList.IsReadOnly;

    public IEnumerator<T> GetEnumerator() => ReadOnlySourceList.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    public void Add(T item) => MutableSourceList.Add(item);

    public void Clear()
    {
        _setPropertyDelegate(null);
    }

    public bool Contains(T item) => ReadOnlySourceList.Contains(item);
    public void CopyTo(T[] array, int arrayIndex) => ReadOnlySourceList.CopyTo(array, arrayIndex);

    public bool Remove(T item)
    {
        bool result = MutableSourceList.Remove(item);

        if (Count == 0)
        {
            _setPropertyDelegate(null);
        }

        return result;
    }

    public int IndexOf(T item) => ReadOnlySourceList.IndexOf(item);
    public void Insert(int index, T item) => MutableSourceList.Insert(index, item);

    public void RemoveAt(int index)
    {
        MutableSourceList.RemoveAt(index);

        if (Count == 0)
        {
            _setPropertyDelegate(null);
        }
    }
}
```
Output:
```json
{
  "List": null,
  "ListWrapper": []
}
```

**Comment by layomia** [comment]
`JsonSerializerOptions.IgnoreReadOnlyProperties/Fields` does not apply to collections, as .NET design [guidelines](https://docs.microsoft.com/visualstudio/code-quality/ca2227?view=vs-2019) state that collection properties should be read-only. Read-only collection properties could be populated on deserialization following https://github.com/dotnet/runtime/issues/30258.

If read-only collections need to be ignored during serialization, we can consider adding a new `WhenWriting` enum value to [`JsonIgnoreCondition`](https://github.com/dotnet/runtime/blob/0f7370baa68c5809f93095cbce9bf614f44cc731/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonIgnoreCondition.cs#L13) which can be applied per-property via [`JsonIgnoreAttribute`](https://github.com/dotnet/runtime/blob/0f7370baa68c5809f93095cbce9bf614f44cc731/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Attributes/JsonIgnoreAttribute.cs#L16).

**Comment by raffaeler** [comment]
I don't see the value in serializing something that is backed from a `IEnumerable<something>` data type.
The typical example is a projection property like:
```
public IEnumerable<string> CandidateNames => TermToItems.Select(c => c.Item.Name);
```
where the `TermToItems` is a property where serialization is expected

It would be nice supporting this scenario avoiding [JsonIgnore] which brings the undesired dependency of `System.Text.Json`.
Doing it in a custom converter is quite complex, given the current custom converters architecture which doesn't help much.
