### ISSUE TITLE
Handle failures from printf when tracing errors

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#3760]
We've seen failures which indicate that the call to `pal::str_vprintf` can fail (return -1) - currently no idea what causes the failure though. When this happens `trace::error` will end up calling `fputs` with `NULL` which is a hard failure (parameter validation error in CRT).

The code should be changed to handle the failure `printf` and probably try to print out the message in some other way - maybe without formatting, or print out a generic error message instead. It should definitely not cause a crash of the process.

**Comment by adarshamrit** [comment]
Can you please provide steps on how to reproduce this issue?

**Comment by vitek-karas** [comment]
Thanks for the interest. Unfortunately, I didn't have a repro even back when I filed the issue. I also haven't seen it reported in several years now, so I don't think it's worth keeping the issue open for a hypothetical scenario. Going to close it. If it happens again we can create a new one.
