### ISSUE TITLE
ParallellEnumerable.MinimumParallelThreshold<T>

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#37602]
## Background and Motivation
Preface:
When using the `ParallellEnumerable` class one has the options of specifying the `WithDegreeOfParallelism`

Impetus:
How does one easily determine for a given `T` what the acceptable `Count` would be in relation to running `ParallelEnumerable` vs running in a single `foreach` construct?

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```diff
namespace System.Linq.ParallelEnumerable
{
+    ///Indicates the `Count` at which users should be able to use Parallel without causing unnecessary overhead
+    public int MinimumParallelThreshold<T>() {
       /*Logic based on ProcessorCount and CacheSize of Processor to determine if the context switch overhead for using ParallelEnumerable would be acceptable*/
     }
```

## Usage Examples

```C#
/// <summary>
        /// Calulcates the <see href="https://en.wikipedia.org/wiki/Standard_deviation">Standard Deviation</see>, 
        /// </summary>
        /// <param name="values">The values of <see cref="IEnumerable{double}"/></param>
        /// <param name="sample">Indicates if the result should be the sample or the whole population, defaults to <see langword="false"/></param>
        /// <returns>The <see cref="double"/> value which is the <see href="https://en.wikipedia.org/wiki/Standard_deviation">Standard Deviation</see></returns>
        public static double StandardDeviation(this IEnumerable<double> values, bool sample = false)
        {
            if (null == values) return 0.0d;
            var count = Enumerable.Count(values);
            if (count <= 1) return 0.0d;

            //Small amount of samples use 1 thread
            if(count <= MinimumParallelThreshold<double>())
            {
                var avg = Enumerable.Average(values);
                var sum = Enumerable.Sum(values, d =>
                {
                    var dAvg = d - avg;
                    return dAvg * dAvg;
                });
                return Math.Sqrt(sum / count - (sample ? 1 : 0));
            }

            //Get the ParallelQuery
            var parallelValues = values.AsParallel();

            // Standard deviation calculation requires that we first
            // calculate the mean average. Average is a predefined
            // aggregation operator, along with Max, Min and Count.
            double mean = parallelValues.Average();

            return parallelValues.Aggregate(
                // initialize subtotal. Use decimal point to tell
                // the compiler this is a type double. Can also use: 0d.
                0.0,

                 // do this on each thread
                 (subtotal, item) => subtotal + Math.Pow(item - mean, 2),

                 // aggregate results after all threads are done.
                 (total, thisThread) => total + thisThread,

                // perform standard deviation calc on the aggregated result.
                (finalSum) => Math.Sqrt(finalSum / count - (sample ? 1 : 0))
            );
        }
```

## Alternative Designs

Expose CPU Cache Size and a reasonable way to convert from `sizeof(T)` to this threshold.

## Risks
None

##Benefits

Users will know explicitly if they should or not use `AsParallel`

##Further Improvements
`ParallelEnumerable` could use this information under the hood without exposing it and set the `WithDegreeOfParallelism` to `1` when the `MinimumThreshold` is not met.

**Comment by juliusfriedman** [comment]
@Dotnet-GitSync-Bot, You can add the label `area-System.Linq.Parallel` I can't.

**Comment by stephentoub** [comment]
> How does one easily determine for a given T what the acceptable Count would be in relation to running ParallelEnumerable vs running in a single foreach construct?

PLINQ doesn't know how much work is being performed in the user-supplied delegates, and that's one of if not the most important factor in whether parallelizing is beneficial.

I'm not really clear on what this proposal is or how it would actually work.

**Comment by juliusfriedman** [comment]
It's a method given given a type?

```ParallellEnumerable.MinimumParallelThreshold<T>()```

Inside this function I would know the `sizeof(T)`, I would then compute the cacheSize of the processor to determine how many of this element can fit in the cache.

Once I know that number I can say if I have an `IEnumerable` with a `Count` >= `ParallellEnumerable.MinimumParallelThreshold<T>()`

That I can then call `AsParalell` without worrying that I am spinning up more threads than I needed to when i might have been able to just use a single `foreach` loop.

As I then stated, the implementation of `PLINQ` could further be optimized to perform this check when `WithDegreeOfParallelism` is called and override the value setting it to `1` where any other value would technically be a DOS attempt at the worst or a overhead waster at the least.

**Comment by stephentoub** [comment]
Even if sizeof(T) correctly indicated how many Ts could fit in a cache line (and it wouldn't for non-blittable types), that's only a minor concern in the parallelizability of a query.  A much more impactful aspect is the actual work being performed per element, which in the general case is not something PLINQ can know.  You could fit 64 Ts per cache line and it wouldn't be worth parallelizing, and a T could be larger than a cache line and it would still be worth parallelizing.

**Comment by juliusfriedman** [comment]
Well for any other type it would always be `IntPtr.Size` right?

I realize the amount of operations being performed in the cache is highly relevant but before one can even calculate that they need a basis don't you agree?

What about the aspect of an unbounded `ParallelEnumerable` i.e. without calling `WithDegreeOfParallelism` is that always best to use all cores? I would say no.

I would say there needs to be an optimal way to at least have a basis and furthermore that `WithDegreeOfParallelism` should not only enforce it but potentially provide a new method `WithOptomialDegreeOfParallelism` that sets the users up at least to know if they should even attempt to use parallel.

**Comment by stephentoub** [comment]
My point is that such a basis is largely meaningless.  PLINQ already falls back to serialized execution if it doesn't see a path to getting good speedups, which is largely based on what operators are used in the query and its knowledge of its implementation of those operators.  Beyond that, it'd be a research project for it to figure out a better "basis", and the most impactful piece to such a basis (the amount of work that'll be done per operation) is not something it's generally privvy to, because it's opaque operations supplied by the caller.  This doesn't look tractable to me.

**Comment by juliusfriedman** [comment]
Hence why the simpler ```public int MinimumParallelThreshold<T>``` is semi useful, it tells me this is likely or not, not definitely. At that point at least I made my own decision...

**Comment by stephentoub** [comment]
The method would need to always return 2.  Any other value would yield both false positives and false negatives.  And a method which always returns 2 is not useful.

**Comment by juliusfriedman** [comment]
Obviously you would also agree that this is naive:

```
someCount <= Environment.ProcessorCount
```

So what other way would you determine that, I would say if the amount of elements can fit in the cache then say yes otherwise say probably no.

**Comment by stephentoub** [comment]
> Obviously you would also agree that this is naive

It depends entirely on what query I'm running, which only I as the developer of the query know.

> I would say if the amount of elements can fit in the cache then say yes otherwise say probably no

It is trivial to come up with many queries where that will produce bad results.

**Comment by juliusfriedman** [comment]
`that` being the sizof(T) ? I cannot see how since the cache size but be able to hold those elements, if they can I should not be parallel. In that specific case you can produce a bad result?

**Comment by stephentoub** [comment]
I have a collection of a 10 million integers.  I want to factor each with `integers.AsParallel().Select(i => Factor(i))`.  You're saying I shouldn't run that in parallel because 10 million integers doesn't fit in my cache?  Or I have a collection of 4 strings, each of which is a url from which I want to download some data... you're saying I shouldn't run that in parallel because 4 is less than the number of cores in my machine?

> how would 2 always be the magic number?

It would never make sense to parallelize the processing of a single item.  The minimum number of items at which parallelization makes sense is when there's actually data to be processed in parallel, aka 2.

**Comment by juliusfriedman** [comment]
Your taking this a bit further, I see where you mind is going but not sure why...

This is not about HOW I should use Parallel, it's about WHEN I should use it.

Its also about not totally about using `WithDegressOfParallism` [which uses ALL cores].

It's about telling a developer hey, if you have `10 million integers` and they fit in your cache you should not run this as parallel because the context switching will outweigh the serial processing on a single core in that case.

When you bring Downloading into the picture it confuses me because ONLY I WOULD KNOW what I am doing with that data and therefore is WAY outside the scope of what I am asking.

I am simply saying given a <string> I would return IntPtr.Size * Count() >= CacheSize and say it's possible that since this fits in cache you might not want to run this as parallel... but since I am using the strings to then download something I would not care about the cache size.....

Hopefully we can agree to agree I would care more if 10 strings can fit in cache I might be better off using a Task with a for loop to download my files rather than ParallelEnumerable.ForAll

**Comment by stephentoub** [comment]
> It's about telling a developer hey, if you have 10 million integers and they fit in your cache you should not run this as parallel because the context switching will outweigh the serial processing on a single core in that case.

I do not want to tell them that.  That's my point.  It doesn't take a lot of work per Int32 for it to absolutely make sense to parallelize that.

> When you bring Downloading into the picture it confuses me because ONLY I WOULD KNOW what I am doing with that data and therefore is WAY outside the scope of what I am asking.

Exactly.  So how could the system possibly give you a meaningful value back from `MinimumParallelThreshold`, other than `2`.  It has no way of knowing what the minimum number of elements is at which parallelization is useful, other than knowing that if you have fewer than 2 it won't be useful.

> I am simply saying given a I would return IntPtr.Size * Count() >= CacheSize and say it's possible that since this fits in cache you might not want to run this as parallel

Anyone can do that computation on their own if it's relevant to their domain.  In a very large number of cases (I'd argue the majority of cases, based on seeing what folks do with PLINQ), such a computation is going to be irrelevant.

**Comment by juliusfriedman** [comment]
Can you point me to a place where one can easily determine the cache size of the processors on the machine so one can trivially implement this themselves?

My point was you guys have the cache size and know based on the sizeof(T) how many can fit in cache...

perhaps a better place for this would be outside of `Linq` and inside the `Intrinsics` namespace.

**Comment by stephentoub** [comment]
> Can you point me to a place where one can easily determine the cache size of the processors on the machine so one can trivially implement this themselves?

If what you're asking for is a .NET API to return machine configuration / cache sizes, that's got nothing to do with PLINQ, and doesn't belong as an API on ParallelEnumerable.  There are already various issues open discussing APIs for querying for such data in a platform-agnostic manner, e.g. https://github.com/dotnet/runtime/issues/22948; if those don't fit your needs, please feel free to propose a separate one.

In the meantime, I'm going to close this one.  Thanks.

**Comment by juliusfriedman** [comment]
Thank you, I will assume that someone will notice the mention form this thread and no further comment there is required.

Thank you for your time.

**Comment by stephentoub** [comment]
You're of course welcome to add a comment to that issue if you believe this discussion is relevant. :)
