### ISSUE TITLE
Wrapping a TextWriter with TextWriter.Synchronized causes ToString to return unexpected results

### ISSUE THREAD

**Issue by AdamRuark** [dotnet/runtime#37611]
### Description

Wrapping a TextWriter with TextWriter.Synchronized causes ToString() to return unexpected results

```
using System;
using System.IO;
					
public class Program
{
	public static void Main()
	{
		TextWriter normalWriter = new StringWriter();
		TextWriter synchronizedWriter = TextWriter.Synchronized(normalWriter);
		
		synchronizedWriter.WriteLine("Test string");
		
		Console.WriteLine(normalWriter.ToString()); // Result: "Test string"
		Console.WriteLine(synchronizedWriter.ToString()); // Result: "System.IO.TextWriter+SyncTextWriter"
	}
}
```

I would expect ToString to return "Test string" in both cases.

### Configuration

.NET version: 3.1.300
OS: Windows 10 Version 1803
Architecture: x64

### Regression?

Unknown

### Other information

None

**Comment by Jozkee** [comment]
Closing this, we may re-open if we consider that `ToString` method should be overriden by `TextWriter` maybe on a similar fashion to `StringWriter`.
