### ISSUE TITLE
System.Net.Http.Json.HttpClientJsonExtensions Custom Exceptions on Error Status Codes

### ISSUE THREAD

**Issue by MichaelPeter** [dotnet/runtime#37633]
My webservice returnes detailed error information but methods like System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsync() return just an gerneric error if a 500 Code is returned and not an exception with the error message.

I would suggest something along the lines that HttpClient has a Property EnsureSuccessDelegate to set a custom handler which then allows to throw a custom exception.

HttpResponseMessage.EnsureSuccessStatusCode() then calls the delegate if it is not null instead of checking the status itself.

My scenario is blazor, so there must also be a possiblity to set this property for the injected HttpClient globaly

```c#
System.Net.Http.HttpClient {

public EnsureSuccessDelegate CustomEnsureSuccessHandler {get; set; }

}


/// <summary>
        /// Checks if the response is an error and allows to throw a custom exception.
        /// </summary>
        /// <param name="response">The response http message.</param>
        public delegate void EnsureSuccessDelegate(HttpResponseMessage response);
```

As an alternative all methods could be extended for an paramameter EnsureSuccess but this would be too much effort for the developer to set this property on every call, also there would be too many additional methods.
`public static Task<TValue> CustomGetFromJsonAsync<TValue>(this HttpClient client, string? requestUri, CancellationToken cancellationToken = default,  EnsureSuccessDelegate customEnsureSuccess = null)`

**Comment by MichaelPeter** [comment]
Yea ended up writing an extension method simular to that but I felt it would be a very common scenario and wouldn't want to implement it on each project again, so I thought this addition would be nice

**Comment by karelz** [comment]
Triage: We do not think it makes sense to add these overloads - it would have to be likely also on `HttpClient` and would create quite a lot of clutter.
If there are more upvotes or evidence this is needed in future, we can reconsider. Closing for now.

FYI @Jozkee
