### ISSUE TITLE
[wasm] Issue with loading files from the file system during the library tests run

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#37648]
Wasm does not support loading files from the file system by default.  
There seem to be at least 3 options:
- Embed the files as resources in an assembly and pull them out during the test run (wasm supports writing / creating files)
- Wasm supports configuring a filesystem ahead of time.  This would be the entire set of files being used in the tests.
- Disable the tests

cc @steveisok

**Comment by akoeplinger** [comment]
Note: Option 1 is what we did in mono/mono and iOS/Android are running into the same issue too (though it's a little bit easier to bundle the test files into the app bundle there).

**Comment by marek-safar** [comment]
@danmosemsft is this something @safern can help with to decide and implement?

**Comment by stephentoub** [comment]
Option (3) (disabling tests) is a reasonable place to start if it would help us get to a clean state.  But we shouldn't end there.

Are all of the files in question the ones that come from the testdata repo?  Option (2) (pre-configure file system) seems like it'd make the most sense / result in the fewest changes if we could effectively just say that all of that data we're pulling in is a file system made available to the tests.

**Comment by ericstj** [comment]
> We essentially need to list each file in the .js that we generate in WasmAppBuilder and add it to the virtual filesystem we create (this is similar to how the managed assemblies get loaded). From there on the normal File APIs should work as expected.

Shouldn't something in the build system map CopyLocal Content to this automatically?  If we do it ourselves here does that mean customers that depend on CopyLocal content (EG: from a nuget package) need to do the same?

**Comment by kjpou1** [comment]
Here is an example of populating the file system that can be read from wasm

https://github.com/mono/mono/blob/master/sdks/wasm/runtime-tests.js#L161

**Comment by steveisok** [comment]
I'm leaning towards the first option (embedding in the assemblies) because we can spread the same functionality out between wasm, iOS, and android.  

Any objections to that?

**Comment by ViktorHofer** [comment]
I'm fine with any solution that is app-local. I would like to avoid sharing test data if not strictly necessary.

**Comment by safern** [comment]
Re-opening to track the remaining failures with DirectoryNotFound and FileNotFoundException which are not related to mapping files to the VFS.
