### ISSUE TITLE
Should static constructor of an interface be invoked if a DIM method is not called?

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#37647]
Are static constructors on interfaces expected to run in this situation?

### Description

`dotnet new console` and run the following code:

```csharp
using System;
using System.Runtime.CompilerServices;


#if false
/* X is a class, X cctor prints */

public class X {
	static X () {
		Console.WriteLine ("X cctor");
	}

	public virtual void Foo () {
		Console.WriteLine ("X.Foo");
	}
}

public class C : X {
	public void Bar () {
		Console.WriteLine ("C.Bar");
	}

	public override void Foo () {
		Console.WriteLine ("C.Foo");
	}
}
#else
/* X is an interface, X cctor doesn't print */
public interface X {
	static X () {
		Console.WriteLine ("X cctor");
	}

	void Foo () {
		Console.WriteLine ("X.Foo");
	}
}

public class C : X {
	public void Bar () {
		Console.WriteLine ("C.Bar");
	}

	void X.Foo () {
		Console.WriteLine ("C.Foo");
	}
}
#endif

public class M {
	public static void Main () {
		var c = new C();
		CCaller (c);
	}

	[MethodImpl (MethodImplOptions.NoInlining)]
	public static void CCaller (C c) {
		c.Bar ();
		XCaller (c);
	}


	[MethodImpl (MethodImplOptions.NoInlining)]
	public static void XCaller (X x) {
		x.Foo ();
	}
}
```

Actual output:
```
C.Bar
C.Foo
```

Expected(?) output:
```
X cctor
C.Bar
C.Foo
```

### Configuration

.NET Core 3.1 on macOS

### Regression?

No
### Other information

Mono 6.10 and 6.12 also behave the same way.

**Comment by jkotas** [comment]
I believe that the current behavior is by design. Static constructors of interfaces are triggered only by execution of the default interface method body. They are not triggered by implementing the interface on a type.

cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
The spec is here: https://github.com/dotnet/runtime/blob/master/docs/design/features/default-interface-methods.md and this is the specified behavior. They initialize same as value types since they don't have an instance constructor that normally protects instance methods on classes.
