### ISSUE TITLE
Reliable No GC Region

### ISSUE THREAD

**Issue by WenceyWang** [dotnet/runtime#37667]
## Background and Motivation

Sometimes, GC pause is unbearable in a game or a critical app.

There are `GC.TryStartNoGCRegion` can be used but with a lot limit and provide no guarantee to pause GC. GC can still be invoked by WinUI or something else in no GC region without any notification, which makes games unplayable.

I know that Unity has API to disable GC and open it back manually: https://docs.unity3d.com/ScriptReference/Scripting.GarbageCollector.GCMode.html

## Proposed API

```diff
namespace System
{
    public static class GC
    {
+        public static void StartNoGCRegion();
    }
}
```

## Usage Examples

``` C#
void StartGame()
{
    GC.StartNoGCRegion(); //Return until GC paused and only resume by EndNoGCRegion()
}

void EndGame()
{
    GC.EndNoGCRegion(); //Resume GC
}
```

## Alternative Designs

Allow set `GCSettings.LatencyMode` to `NoGCRegion`?

## Risks

We might get OOM.

**Comment by Maoni0** [comment]
how would you handle OOM?

**Comment by lindexi** [comment]
Useful in game.

**Comment by huoyaoyuan** [comment]
For games, `SustainedLowLatency` is getting pretty well performance.
Using No-GC means you should control you code under no-alloc, which is extremely hard.

**Comment by WenceyWang** [comment]
> 
> 
> how would you handle OOM?

The idea of No GC Region is that let the game running smoothly, which means I will try to allocate anything before stopping GC. And we don't think we will handle OOM in gameplay. If OOM does happen, I think I'll just let the game crash or try to let the game fail.

> 
> 
> For games, `SustainedLowLatency` is getting pretty well performance.
> Using No-GC means you should control your code under no-alloc, which is extremely hard.

`SustainedLowLatency` runs well on some gaming PC but not Xbox and some PC with lower performance.

**Comment by Maoni0** [comment]
>  And we don't think we will handle OOM in gameplay. If OOM does happen, I think I'll just let the game crash or try to let the game fail.

that sounds like a bad user experience.

> There are GC.TryStartNoGCRegion can be used but with a lot limit and provide no guarantee to pause GC. 

you can specify a much larger segment size via a GC config (COMPlus_GCSegmentSize). I'm also open to just making this part handled by the GC instead of having the users specify a larger segment size. I would think that'd be useful to a lot more scenarios...

**Comment by WenceyWang** [comment]
> 
> 
> > And we don't think we will handle OOM in gameplay. If OOM does happen, I think I'll just let the game crash or try to let the game fail.
> 
> that sounds like a bad user experience.

As a result, I have used No GC in Unity while game being played and it works just fine because most of the memory usage is not managed.

> > There are GC.TryStartNoGCRegion can be used but with a lot limit and provide no guarantee to pause GC.
> 
> you can specify a much larger segment size via a GC config (COMPlus_GCSegmentSize). I'm also open to just making this part handled by the GC instead of having the users specify a larger segment size. I would think that'd be useful to a lot more scenarios...

The problem of `GC.TryStartNoGCRegion` is that the GC free region will end without any indication. What I got is a GC pause and `GCSettings.LatencyMode` change to the previous value, and actually make the game unplayable.
Meantime I have no idea how to change GC config in a UWP environment.

**Comment by Maoni0** [comment]
> As a result, I have used https://docs.unity3d.com/ScriptReference/Scripting.GarbageCollector.GCMode.html to stop GC in Unity while game being played and it works just fine because most of the memory usage is not managed.

so what's the difference? in .net core a lot more memory is managed?

> The problem of GC.TryStartNoGCRegion is that the GC free region will end without any indication.

if all you want is a way to be notified, that seems like an easy problem to solve - we could throw an exception if a GC is triggered when in NoGC region, if that's what the user wants.

> Meantime I have no idea how to change GC config in a UWP environment.

I don't remember but I'm sure someone on our team knows - @tommcdon?

**Comment by WenceyWang** [comment]
> 
> 
> > As a result, I have used https://docs.unity3d.com/ScriptReference/Scripting.GarbageCollector.GCMode.html to stop GC in Unity while game being played and it works just fine because most of the memory usage is not managed.
> 
> so what's the difference? in .net core a lot more memory is managed?

I mean that in a game, most of the memory usage is unmanaged, both Unity and currently I am calling graph API from .net core. OOM is not a real problem that we will face.

> > The problem of GC.TryStartNoGCRegion is that the GC free region will end without any indication.
> 
> if all you want is a way to be notified, that seems like an easy problem to solve - we could throw an exception if a GC is triggered when in NoGC region, if that's what the user wants.

What I really need is GC make no pause in the NoGC region, we prefer OOM than GC pause.

**Comment by mangod9** [comment]
@cshung given your recent work for this, can this be closed?
