### ISSUE TITLE
[Breaking change] Removal of built-in WinRT support in .NET 5.0

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#37672]
# [Breaking change] Removal of built-in WinRT support in .NET 5.0

With the work to provide sustainable and long term [support for WinRT consumption in .NET](https://github.com/dotnet/runtime/issues/35318), the built-in support has been removed. This is a high impact change to all existing libraries and application that rely on the built-in WinRT support.

The replacement for built-in WinRT support is the [C#/WinRT](https://aka.ms/cswinrt) tool chain.

For complete details see the official doc issue at https://github.com/dotnet/docs/issues/18875.

**Comment by Nukepayload2** [comment]
How can I upgrade my .NET Framework 4.x, .NET Core 3.1 VB apps to .NET 5 after this breaking change? Many of them are using WinRT APIs to send toast notifications, share files or save settings.

**Comment by svick** [comment]
@Nukepayload2 You're supposed to use [C#/WinRT](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/) for that. Have you tried it?

**Comment by AaronRobinsonMSFT** [comment]
@Nukepayload2 there are recommended next steps linked about in https://github.com/dotnet/docs/issues/18875.
