### ISSUE TITLE
ARM64: Left over dead code for special throw blocks

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#37675]
While debugging something on ARM64, I noticed that we end up leaving some of the dead code in place. 
```csharp
private static uint DivTest(uint xr)
{
    return xr  / 4;
}
```
Generates the following where `IG04` block is dead:
```asm
G_M26531_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
                                                ;; bbWeight=1    PerfScore 1.50
G_M26531_IG02:
        53027C00          lsr     w0, w0, #2
                                                ;; bbWeight=1    PerfScore 1.00
G_M26531_IG03:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
G_M26531_IG04:
        97FF67A9          bl      CORINFO_HELP_THROWDIVZERO
        D43E0000          bkpt
```

For `int` parameter, we have 2 blocks that are dead:
```asm
G_M26531_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
                                                ;; bbWeight=1    PerfScore 1.50
G_M26531_IG02:
        131F7C01          asr     w1, w0, #31
        12000421          and     w1, w1, #3
        0B000020          add     w0, w1, w0
        13027C00          asr     w0, w0, #2
                                                ;; bbWeight=1    PerfScore 3.00
G_M26531_IG03:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
G_M26531_IG04:
        97FF67A2          bl      CORINFO_HELP_OVERFLOW
                                                ;; bbWeight=0    PerfScore 0.00
G_M26531_IG05:
        97FF67A5          bl      CORINFO_HELP_THROWDIVZERO
        D43E0000          bkpt
```

We don't produce dead BB if I change from division to bit-shift like `xr >> 2`. I was assuming there be some dead code elimination phase, but looking at dumps I didn't see anything like that happening.

category:cq
theme:dead-code
skill-level:intermediate
cost:medium

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Looks like we add those `throwBlocks` [inside morph](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/morph.cpp#L13087) for ARM64 and then don't remove it [inside flowgraph](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/flowgraph.cpp#L2065) because we don't remove internal throw blocks. We can perhaps eliminate 1 or both those checks in certain situation where e.g. divisor is a constant power of 2 (no need of overflow check) or if it is non-zero constant (no need of divide by zero check).

**Comment by AndyAyersMS** [comment]
Marking as future.

**Comment by TIHan** [comment]
https://github.com/dotnet/runtime/pull/82924 and https://github.com/dotnet/runtime/pull/68945 covered a majority of these cases. There are still cases as it is possible that one of these blocks can be added and then an optimization happens that proves we don't need the blocks.

**Comment by EgorBo** [comment]
Let's close it then and re-open/re-create if we find a pattern that is not optimized today. Current asm for the Kunal's snippet:
```asm
; Method C:DivTest(uint):uint (FullOpts)
G_M2997_IG01:  ;; offset=0x0000
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
						;; size=8 bbWeight=1 PerfScore 1.50

G_M2997_IG02:  ;; offset=0x0008
            lsr     w0, w0, #2
						;; size=4 bbWeight=1 PerfScore 1.00

G_M2997_IG03:  ;; offset=0x000C
            ldp     fp, lr, [sp], #0x10
            ret     lr
						;; size=8 bbWeight=1 PerfScore 2.00
; Total bytes of code: 20


```

**Comment by AndyAyersMS** [comment]
I would expect #95379 to catch most cases of this.
