### ISSUE TITLE
Expose a ValueRef property on LinkedListNode<T>

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#37681]
## Rationale

`LinkedList<T>` currently exposes all nodes in the list as `LinkedListNode<T>`. That node itself then exposes the underlying value via `public T Value { get; set; }`.
This works sufficiently for classes but it will incur a copy for any `T` that is a struct. For large `T` this can incur measurable overhead in some scenarios.

I propose a new property `ValueRef` be exposed that gives a reference to the underlying `T` field. This should be safe as the `LinkedListNode` is already a class and can exist independently of the `LinkedList`.
Additionally, the `LinkedListNode` doesn't use any complicated logic relating to the backing field and so modifying it indirectly is already safe.

## Proposed API

```csharp
namespace System.Collections.Generic
{
    public partial class LinkedListNode<T>
    {
        public ref T ValueRef => ref item;
    }
}
```

**Comment by svick** [comment]
Bikeshedding: should it be `ValueRef` or `RefValue`? I think "ref" behaves as an adjective and so should be before the noun.

**Comment by reflectronic** [comment]
Well, the ship has sailed on that one.
https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablesorteddictionary-2.valueref
https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.itemref

**Comment by terrajobst** [comment]
Looks good as proposed

```C#
namespace System.Collections.Generic
{
    public partial class LinkedListNode<T>
    {
        public ref T ValueRef => ref item;
    }
}
```
