### ISSUE TITLE
HttpClient: Add switch support special targetHost that used to verify the ssl certificate

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#37694]
curl support allow different host in ssl certificate and http request

``` bash
curl https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp -H 'HOST: image.tuhu.cn' --head
```

Convert to C# code, I think is that:
``` C#
using var client = new HttpClient(/*using var client = new HttpClient(new SocketsHttpHandler { SslOptions = { TargetHost = "iovip.qbox.me" } }*/);

using var request = new HttpRequestMessage(HttpMethod.Get, "https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp");

request.Headers.Host = "image.tuhu.cn";

using var response = await client.SendAsync(request);

Console.WriteLine(response.StatusCode);
```
But, your will get a certificate error, I found the reason in [here](https://github.com/dotnet/runtime/blob/4b03513e20e0caf9ee34817eb74356903f1bb33e/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L249), preferred to use `HttpRequestMessage.Headers.Host`.    
I don't want to use `DangerousAcceptAnyServerCertificateValidator`, and `HttpClient` is not a browser.     
So, could provide a switch(may be from `HttpRequestMessage.Properties`) to take the code work like `curl`? The special targetHost can from `HttpRequestMessage.RequestUri.Host` or `SocketsHttpHandler.SslOptions.TargetHost `.

**Comment by pengweiqhca** [comment]
> For cases like this, you should use [ServerCertificateCustomValidationCallback](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.servercertificatecustomvalidationcallback?view=netcore-3.1#System_Net_Http_HttpClientHandler_ServerCertificateCustomValidationCallback) and apply your logic there @pengweiqhca. You will get X509Chain and errors and then you can verify expected name and fail if there are any other issues.
> From the example it is not clear what is relation between iovip.qbox.me and image.tuhu.cn.

The Dns of `iovip.qbox.me` and `image.tuhu.cn` resolve to same ip, I want verification certificate by `iovip.qbox.me`, the actual request is `image.tuhu.cn`. If use `ServerCertificateCustomValidationCallback`, how to coding?

**Comment by pengweiqhca** [comment]
This is `SocketsHttpHandler` 'bug', if don't use `SocketsHttpHandler`, no problem.
``` C#
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

**Comment by scalablecory** [comment]
"iovip.qbox.me" is using a wildcard cert of "*.qbox.me".
"image.tuhu.cn" is using a cert for "www.baishancloud.com".
They do not resolve to the same IPs, either, at least from my DNS server.

I agree `ServerCertificateCustomValidationCallback` is correct path here.

**Comment by pengweiqhca** [comment]
Whether is the same IP is not important, verify the connection security using known host, using other host fetch a actual resource. `SocketsHttpHandler` vdoes not support at present, `WinHttpHandler`/`CurlHandler` is suppoort.

**Comment by wfurt** [comment]
The IP differences are probably caused by CDN and geolocation. The interesting part is that this is trying to fetch data from host neither site is willing to vouch for.

Anyway, here is what I had in mind:

```c#
using System;
using System.Net.Http;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;


namespace httpsValidation
{
    class Program
    {
        const string subject = "*.qbox.me";
        const string host = "image.tuhu.cn";

        static async Task  Main(string[] args)
        {
            using (HttpClientHandler handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback =
                (request, cert, chain, errors) =>
                {
                    if (errors == SslPolicyErrors.None)
                    {
                        return true;

                    }
                    else if (errors == SslPolicyErrors.RemoteCertificateNameMismatch)
                    {
                        // errors is bitmask so we will end up here only if name is only one problem.
                        // e.g. trust, expiration, revocation etc. is OK and chain is trusted.
                        if (cert.GetNameInfo(X509NameType.DnsName, false) == subject)
                        {
                            return true;
                        }

                        Console.WriteLine("Certificate has unexpected issuer {0}", cert);
                    }

                    // Any other validation issues.
                    return false;
                };

                using var client = new HttpClient(handler);
                using var request = new HttpRequestMessage(HttpMethod.Get, "https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp");

                request.Headers.Host = host;

                using var response = await client.SendAsync(request);

                Console.WriteLine(response.StatusCode);
            }
        }
    }
}
``` 

gives `OS` to me. I think the current behavior is there for a reason and we would need to dig through corefx history. It is unlikely to change IMHO given the unusual scenario and possible workaround. 
Also note that curl handler is no longer available in .NET 5 so any solution based on that will stop working after upgrade.

**Comment by pengweiqhca** [comment]
I've been using `Lib.Harmony` patched `GetConnectionKey`.

**Comment by karelz** [comment]
Triage: The above workaround should be sufficient. No need to have it as first-class feature based on limited demand at this moment.
