### ISSUE TITLE
Bitmap FlipRotate issue with 1bpp images

### ISSUE THREAD

**Issue by tslater2006** [dotnet/runtime#37703]
### Description
There seems to be an issue with the FlipRotate method of the Bitmap class in System.Drawing. When loading a 128px wide by 52px tall image (1bpp bitmap format) and performing a horizontal flip the right side of the resulting image is not correct. an 8 pixel column on the right side is set to all black instead of the expected white value.

I have a minimal repro gist here: https://gist.github.com/tslater2006/3fdeb97b5741b1ff39a1d82b8752bbe4

Here is the resulting flipped image:
![image](https://user-images.githubusercontent.com/1731714/84269841-6795d600-aaef-11ea-9ba5-c9ca54eb788c.png)

This result occurs when doing either a vertical or horizontal flip.

### Configuration

I've tested this on .NET Framework 4.7.2 and also .NET Core 3.0 

In my .NET Core 3.0 test the System.Drawing.Common library reports version 4.70

### Regression?

Unknown

### Other information

My workaround was to create a new Bitmap image and then read from the old image and draw to the new one with a Graphics object to do the horizontal flip myself

**Comment by JeremyKuhne** [comment]
This appears to be a GDI+ issue and as such there isn't much we can do here.
