### ISSUE TITLE
Infrastructure - Rollout (July 2020)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#37706]
# Overview

We'll use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. Changes will be merged on the first Monday of the month (7/6).

| Change |  Impact | Assignee |
| --- | --- | --- |
| https://github.com/dotnet/runtime/issues/37440 | Runtime tests will be moved from `src/coreclr/tests/src/` to `src/tests/` as they are now shared with Mono | Tomas Rylek | 

## Archive
- [June 2020](https://github.com/dotnet/runtime/issues/35895)
- [May 2020](https://github.com/dotnet/runtime/issues/35202)
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by ViktorHofer** [comment]
@trylek based on our offline conversation, can you please add your change for the runtime tests to the list?

**Comment by marek-safar** [comment]
I don't see the change in, what is the plan with this rollout?

**Comment by trylek** [comment]
I rebased the change to the latest master yesterday but I hit infra issues in testing and later a conflict. I'm now re-testing the change and hoping it comes out fine, I'll ping the reviewers to approve the merge ASAP as the change is a pain to keep in sync.

**Comment by ViktorHofer** [comment]
The change is now merged. Closing the issue. Will send out a monthly status mail later this week.
