### ISSUE TITLE
ReadOnlySpan<T>.Split() does not share splitting semantics with string.Split()

### ISSUE THREAD

**Issue by bbartels** [dotnet/runtime#37746]
The parameter-less overload of `ReadOnlySpan<T>.Split` will use a single white space token `' '` to split on the input buffer. The original `string.Split()` implementation however splits on any character that returns `true` when calling `char.IsWhiteSpace(char)`.

**Comment by bbartels** [comment]
The issues I see with implementing ReadOnlySpan<T>.Split() to share the behavior of string.Split is, that there doesn't seem to be way to do this with the current generic enumerator. We would have to pass a `ReadOnlySpan<char>` of separators to  `ReadOnlySpan<T>.IndexOfAny(ROS<T>)`, which at least to my limited knowledge doesn't seem to be possible, as we would have to either cast the ROS<char> to ROS<T> or vice versa.

/cc @stephentoub 
/cc @layomia 
/cc @GrabYourPitchforks

**Comment by stephentoub** [comment]
You can just pass a bool to the ctor indicating the mode, and then iterate calling IsWhitespace.

**Comment by bbartels** [comment]
But such an implementation would then not be vectorised.

**Comment by stephentoub** [comment]
Correct.

**Comment by bbartels** [comment]
For clarification, is it not vectorised for both the parameter-less case, as well as the one with parameters? (re str.Split)

**Comment by stephentoub** [comment]
> What exactly is stopping us from using ROS.IndexOf() or ROS.IndexOfAny() in at least the first couple cases here.

Someone taking the time to measure the impact on a wide array of commonly-expected inputs to see whether it helps or potentially even hurts.

**Comment by GrabYourPitchforks** [comment]
From an algorithmic complexity perspective, the only real requirements are this:

```txt
let str := input string to search within
let n := length of str
let S := set of chars to search for
let |S| := size of set S
let f := index in str where any char in S first appears
```

Then, for any realistic inputs _str_ and _S_:

`str.Split(S)` must have algorithmic complexity no worse than _O(n * |S|)_.
(this is already the case)

`str.IndexOfAny(S)` must have algorithmic complexity no worse than _O(f * |S|)_.
(this is already the case)

`MemoryExtensions.IndexOfAny(str, S)` must have algorithmic complexity no worse than _O(f * |S|)_.
(this is already the case)

`foreach (var range in MemoryExtensions.Split(str, S)) { /* no-op */ }` must have algorithmic complexity no worse than _O(n * |S|)_.

From my perspective any implementation of `MemoryExtensions.Split` which fulfills that requirement is fine. I leave it to the perf-oriented folks to weigh in on how much of a constant factor is acceptable. :)

**Comment by stephentoub** [comment]
> I leave it to the perf-oriented folks to weigh in on how much of a constant factor is acceptable. :)

I'm amused, as this would seem to be you leaving it to you :)

**Comment by GrabYourPitchforks** [comment]
When I start talking algorithmic complexity I'm wearing a security hat, not a perf hat. :)

We can't be in a world where `"attacker-controlled-input".Split()` has _O(n^2)_ complexity. But `"attacker-controlled-input".Split(new char[] { /* attacker-controller search chars */ })` isn't anywhere near as much of a concern.

**Comment by bbartels** [comment]
> From my perspective any implementation of MemoryExtensions.Split which fulfills that requirement is fine. I leave it to the perf-oriented folks to weigh in on how much of a constant factor is acceptable. :)

Glad that you aren't opposed to my idea of adding `Thread.Sleep()` somewhere in `MoveNext()` ;)

**Comment by bbartels** [comment]
Closing for now as per https://github.com/dotnet/runtime/pull/37742#issuecomment-642788210
