### ISSUE TITLE
Incorrect Swiss-French CultureInfo NumberFormat

### ISSUE THREAD

**Issue by YZahringer** [dotnet/runtime#37743]
### Description
In Switzerland there are 4 official languages:
- German `de-CH`
- French `fr-CH`
- Italian `it-CH`
- Romansh `rm-CH`

Officially, the number format use an apostrophe as a thousands separator with a dot `.` as the decimal separator (for example: 1'234'567.89).

The `CultureInfo.NumberFormat` is correct with `de-CH` and `it-CH`, but not with `fr-CH` and `rm-CH`:
`new CultureInfo("de-CH", false).NumberFormat;`
![de-CH](https://user-images.githubusercontent.com/4254116/84376601-ab690800-abe1-11ea-9d2d-08d451f2dacf.png)

`new CultureInfo("it-CH", false).NumberFormat;`
![it-CH](https://user-images.githubusercontent.com/4254116/84376605-adcb6200-abe1-11ea-862c-45ce7461856a.png)

`new CultureInfo("fr-CH", false).NumberFormat;`
![fr-CH](https://user-images.githubusercontent.com/4254116/84376604-ad32cb80-abe1-11ea-9861-361412e33322.png)

`new CultureInfo("rm-CH", false).NumberFormat;`
![rm-CH](https://user-images.githubusercontent.com/4254116/84376607-ae63f880-abe1-11ea-906b-38a32ddef0b9.png)

### Configuration
- .NET Standard 2.1
- Windows 10 build 1909 x64

### Related
- https://developercommunity.visualstudio.com/content/problem/239285/wrong-decimal-separator-for-culture-fr-ch.html

**Comment by tarekgh** [comment]
.NET doesn't carry the globalization data. we just use whatever the OS or native globalization libraries give us. Please file this issue to the Windows team through Windows 10 Feedback Hub. I'll try to send it internally to them too.

**Comment by jefgen** [comment]
Thanks for reporting this issue!

I wanted to add a comment here to give some more info:

Much of the globalization data for "regional formats", or cultures/locales, in Windows 10 comes from the [Unicode CLDR](http://cldr.unicode.org/) project. In this case all 4 of the locales derive their data from CLDR.

A ticket/issue has been filed with the CLDR project here: [13877](https://unicode-org.atlassian.net/browse/CLDR-13877) 

Regarding this comment:
> Officially, the number format use an apostrophe as a thousands separator with a dot . as the decimal separator (for example: 1'234'567.89).

Do you know of any "Official" sources for this info? If so that could help with the CLDR ticket. If you do, please let me know and I can add it to the ticket.

Thank you!

**Comment by YZahringer** [comment]
@jefgen thanks for the answer. I see a lot of issues in CLDR project about "Swiss cultures":
- https://unicode-org.atlassian.net/browse/CLDR-13877
- https://unicode-org.atlassian.net/browse/CLDR-13323
- https://unicode-org.atlassian.net/browse/CLDR-11530
- https://unicode-org.atlassian.net/browse/CLDR-10755
- https://unicode-org.atlassian.net/browse/CLDR-10633
- https://unicode-org.atlassian.net/browse/CLDR-9370
- https://unicode-org.atlassian.net/browse/CLDR-7238
- https://unicode-org.atlassian.net/browse/CLDR-563
- https://unicode-org.atlassian.net/browse/CLDR-63

It's not clear, each person gives their opinion, which gives an inconsistent result between the different regions of the country, it doesn't make sense.

Unfortunately I haven't found any official document that defines the Swiss rules for the moment. I continue the search.
