### ISSUE TITLE
R2R Linux x64 outerloop test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#37759]
https://dev.azure.com/dnceng/public/_build/results?buildId=681518&view=logs&j=14edd310-98f2-5f17-21e6-c93c30b8ed1a&t=261c55f5-8586-5d1b-aab5-fc629ccad30b

Hundreds of Loader/classloader/TypeGeneratorTests tests failed with timeout for both tiered and non-tiered runs, on Alpine x64. 

Also, a number of tests failed with:
```
Unhandled exception. System.TypeLoadException: Could not load type 'System.Collections.Generic.HashSet`1' from assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Are there known problems with the Alpine queue?

@dotnet/runtime-infrastructure

**Comment by safern** [comment]
The latest Libraries test run on Alpine x64 is green: https://dev.azure.com/dnceng/public/_build/results?buildId=682815&view=logs&j=5c657fa2-65d2-55e4-f9c9-8fbd97185e37

So I guess this has to do something with the R2R test mode?

**Comment by BruceForstall** [comment]
Well, the latest outerloop run was green, so closing.

https://dev.azure.com/dnceng/public/_build/results?buildId=685414&view=results
