### ISSUE TITLE
[Snap] .NET Core 3.0 RC1 console app (and webapp) does not work under Linux

### ISSUE THREAD

**Issue by petermcclymont** [dotnet/runtime#3775]
I am using .NET Core from a snap package on KUbuntu. I switched to the beta and edge channels to upgrade from .NET Core 2.2 to .NET Core 3.0.

When on beta or edge my console app doesn't work, whereas it was working perfectly under .NET Core 2.2.

I decided to go back to basics. Create a new console app to see what would happen,

mkdir testdotnet
cd testdotnet
dotnet new console
dotnet build
dotnet run

It runs for a second, and gives nothing. No output, whereas I would normally expect,

Hello World!

My actual app does the same thing. Running the app doesn't actually run any code. When I change back to the stable channel, everything works.

Please let me know what additional information you need. I ran this,

dotnet run -v diag

But the output was no different (as far as I could see) between .NET Core 2.2 and .NET Core 3.0, it just shows the build process that was run first. However if that is useful or something similar then let me know.

Something else, I also tried this,

dotnet new webapp
dotnet build
dotnet run

And it does the same. If you want me to run this against a different version of Linux, or a clean version of Linux I can do do.

**Comment by petermcclymont** [comment]
I wanted to try the latest preview, and it has the same problem,

sudo snap install dotnet-sdk --channel=5.0/beta --classic
sudo snap alias dotnet-sdk.dotnet dotnet
mkdir dotnet
cd dotnet
dotnet new console
dotnet run

Gives nothing. However this works fine,

dotnet bin/Debug/net5.0/dotnet.dll

**Comment by ForNeVeR** [comment]
FYI, folks, this is still an issue with the latest stable .NET 5 SDK from Snap.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
