### ISSUE TITLE
Wasm Microbenchmark Runs

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#37762]
This issue is the master work item to track all the work related to getting Microbenchmark runs.

There are basically two big parts to this:

1. Changes to Benchmark Dotnet so it can run benchmarks in through wasm. Issue here: https://github.com/dotnet/BenchmarkDotNet/issues/1472
2. All the stuff to get reporting and regular runs going; @DrewScoggins will be working on this part.

**Comment by SamMonoRT** [comment]
@marek-safar @lewing - fyi - issue to track enabling .NET Microbenchmark runs on WASM.

**Comment by DrewScoggins** [comment]
Do we have some initial command lines that we will need to make this stuff work? If we do I can pre-flight all of the work on the yaml file updates so that when this change is in BDN we can turn it on much faster.

**Comment by SamMonoRT** [comment]
@naricc @DrewScoggins - I believe we have the runs going in Drew's lab now, but still waiting on reporting. I'm not sure where the reporting scripts live (which repo) and if we need to publish/merge those prior to the RC1 snap on Monday ? If no code change needed for the snap, we can close this issue.

**Comment by naricc** [comment]
There is some fine tuning to do on the exact set of benchmarks to run (changes will be in dotnet/performance).
