### ISSUE TITLE
Create source package for HostFactoryResolver.cs

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#37767]
When moving extensions to runtime we didn't create the source package for this since we agreed we'd avoid source packages in favor of just letting each repo duplicate sources.

This particular package needs to stay in sync between ASP.NET and EF and EF doesn't really control the conventions that this code knows about and shouldn't be expected to keep it in sync.  We could put it in ASP.NET but that creates an unnecessary backwards flow in the dependency graph.

Instead we'll keep the source single-instance in dotnet/runtime and ASP.NET and EF will consume it from here.

**Comment by JunTaoLuo** [comment]
👀
