### ISSUE TITLE
System.Runtime.InteropServices.JavaScript.Runtime is not linker-safe

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#37775]
We recently introduced a JavaScript.Runtime class with methods like the following:

https://github.com/dotnet/runtime/blob/9ce5e481ca143e5af7e2bfba59300820bdcf35bc/src/libraries/System.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/Runtime.cs#L61-L64

These methods are invoked through JS code here:

https://github.com/dotnet/runtime/blob/2c3cd0d3c7aafb01c766823b0c4ed0573757080a/src/mono/wasm/runtime/binding_support.js#L60-L61

https://github.com/dotnet/runtime/blob/2c3cd0d3c7aafb01c766823b0c4ed0573757080a/src/mono/wasm/runtime/binding_support.js#L79-L82

However, the linker doesn't know that these methods need to be preserved, so it is trimming them out. Thus, a trimmed Blazor app doesn't load successfully.

We should enable it so these methods are preserved by the linker.

cc @marek-safar @lewing

**Comment by marek-safar** [comment]
I think the master version should have that fixed already
