### ISSUE TITLE
IDynamicInterfaceCastable and reflection

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#37787]
Some reflection problems are unsolvable for `IDynamicInterfaceCastable` (e.g. having `GetInterfaces` return the dynamic list of interfaces), but reflection APIs that deal with castability should be solvable:

```csharp
using System;
using System.Runtime.InteropServices;

interface IFoo
{
    void Frob();
}

[DynamicInterfaceCastableImplementation]
interface IFooImpl : IFoo
{
    void IFoo.Frob() => Internal.Console.WriteLine("Hello");
}

class Program :  IDynamicInterfaceCastable
{
    public bool IsInterfaceImplemented(RuntimeTypeHandle interfaceType, bool throwIfNotImplemented)
    {
        return true;
    }

    public RuntimeTypeHandle GetInterfaceImplementation(RuntimeTypeHandle interfaceType)
    {
        return typeof(IFooImpl).TypeHandle;
    }

    public static void Greet(IFoo f) => f.Frob();

    static void Main()
    {
        // Returns false
        Internal.Console.WriteLine(typeof(IFoo).IsAssignableFrom(typeof(Program)).ToString());

        // Throws that the interface is not implemented
        var m = typeof(Program).GetInterfaceMap(typeof(IFoo));
        for (int i = 0; i <= m.InterfaceMethods.Length; i++)
            Internal.Console.WriteLine($"{m.InterfaceMethods[i]}: {m.TargetMethods[i]}");
    }
}

```

**Comment by MichalStrehovsky** [comment]
I suspect the `dynamic` keyword is not going to work at all with `IDynamicInterfaceCastable` (since Microsoft.CSharp builds its own symbol table for binding and it does that by calling `GetInterfaces`), but I don't particularly mind that we're punching yet another hole in it.

**Comment by MichalStrehovsky** [comment]
Cc @elinor-fung

**Comment by jkotas** [comment]
> reflection APIs that deal with castability should be solvable

I do not see how this can be solved. `IDynamicInterfaceCastable` requires object instance. Reflection APIs do not have object instance.

**Comment by MichalStrehovsky** [comment]
> IDynamicInterfaceCastable requires object instance

Good point. Do we want to repurpose this to track the `dynamic` keyword, or just close this out? I just remembered that COM and `dynamic` actually is a thing (#33060).

**Comment by jkotas** [comment]
I have opened a new issue to discuss the `dynamic` thing specifically.
