### ISSUE TITLE
Single file: Guard against partial cleanup of extracted files

### ISSUE THREAD

**Issue by theimowski** [dotnet/runtime#3778]
## Steps to reproduce

Unfortunately no deterministic steps to reproduce here, but we've experienced multiple cases of files getting removed from %TEMP%\.net on windows.
The files that were locked by main executable were still there, but "casual" dlls and other files got removed either by AntiVirus or other software.
As a result when our long-running process tried to load files from the temp directory it failed to do so, and we even observed high memory consumption when that was the case.

As a workaround we now set the DOTNET_BUNDLE_EXTRACT_BASE_DIR variable to custom directory.
That said I think the %TEMP% directory is not a good default.

## Expected  behavior

The default extraction directory for Single File Publish should be "safe", meaning there's low risk other programs might try to remove stuff from there

## Actual behavior

Antivirus and other software might remove files from the extraction directory

## Environment data

Various flavours of Windows OS

**Comment by blakepell** [comment]
Has there been any discussion about a switch the developer could use that would tell the extraction to replace the previous extraction (e.g. remove the previous version(s) if they exist and use the new one/current one that's being executed).  In cases where this is appropriate the developer could toggle this setting on publish and it would alleviate the issue of having 10 old version stored when only the newest one is wanted/needed.  It wouldn't stop a user from using old versions but switching versions back and forth (rare case when people are typically using the most updated bundle) would take the extraction hit.

**Comment by swaroop-sridhar** [comment]
Currently, there is no plan to support explicit removal of extraction directories. Removing extractions is tricky, because another process may be using them. It is very unlikely that the feature will be added to .net core 3.1 in servicing releases. So, the only cleanup currently is via tmp-directory cleanup by the OS.

In .net 5,  the amount of extracted files will be minimal (or none, depending on the app). So, there we can consider the design where every execution extracts to a temp-directory, and attempts to cleanup after its completion. However, due to various failure-modes in the app, the runtime may not always get a chance to cleanup the extraction.

**Comment by speed2048** [comment]
A couple of things:

- To confirm, If someone overrides the  DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable, the directories and files will never be pruned.
- Time Frame for fix?
- In some threads there has been discussion that Dotnet 5.0 will handle it differently, can anyone share what will change?

Thanks.

**Comment by swaroop-sridhar** [comment]
@speed2048 
> To confirm, If someone overrides the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable, the directories and files will never be pruned.

Dotnet doesn't delete any extracted files. The default extraction directory is within the `TEMP` directory, from which the OS removes files from time to time. So this fix aims to recover those files.
If `DOTNET_BUNDLE_EXTRACT_BASE_DIR` is set to a non-temp directory, the files are not expected to be lost.  The extracted files are verified/recovered regardless of whether `DOTNET_BUNDLE_EXTRACT_BASE_DIR` is set or not. 

> Time Frame for fix?
This fix is checked in to 5.0 branch; I'll port it to CoreCLR 3.1 branch, and the fix will likely make it into the April servicing release.

> In some threads there has been discussion that Dotnet 5.0 will handle it differently, can anyone share what will change?

In .net 5, the assemblies bundled in single file apps will be loaded directly from the bundle. The design for this feature is explained in this [document](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md).

**Comment by theimowski** [comment]
Thanks @swaroop-sridhar for adding the fix - do I understand correctly that the validation mechanism is run only upon start of the application? I.e. for long running processes, if some of the extracted files are deleted, one needs to restart the app to restore those files right?

**Comment by swaroop-sridhar** [comment]
Yes, @theimowski, the extraction is only validated at startup. This is a potential risk for long running processes, but the files extracted in the temp directory are typically not lost for several months. 
.net 5 will reduce/eliminate the dependency on extraction to help resolve this problem.

**Comment by hillin** [comment]
Just to make sure, this is not fixed in .net core 3.1 right? Some of our clients are running into this problem, it seems Windows or some other software clears their Temp folder in a weekly routine.

**Comment by swaroop-sridhar** [comment]
@hillin  This bug is fixed in last week's [3.1.4](https://dotnet.microsoft.com/download/dotnet-core/3.1) release.  For the fix to work, apps targetting netcoreapp3.1 need to be published using the SDK in this release and re-deployed.

**Comment by yhnbgfd** [comment]
3.1.4 has been updated, but there seems to be a new problem. If <PublishReadyToRun> is set to true, the program will report errors. When <PublishReadyToRun> is set to false, the program can run normally

Err1:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.Sqlite, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. 
File name: 'Microsoft.Data.Sqlite, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Err2: 
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.JwtBearer, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. 
File name: 'Microsoft.AspNetCore.Authentication.JwtBearer, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at MIQS.WebApiServer.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MIQS.WebApiServer.Program.Main(String[] args)

**Comment by danmosemsft** [comment]
This issue is closed. Can you please open new issues?

**Comment by swaroop-sridhar** [comment]
@yhnbgfd  I think the failure you report is not related to this issue. Please file a different issue with more details about how to repro the problem. Thanks.
