### ISSUE TITLE
Lengthy RuntimeIdentifierGraph update roundtrip with SDK

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#37790]
A change to `src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json` requires a full update cycle, which includes:

1. a PR updating `runtime.json` merged in runtime repo
2. SDK repo picks up runtime change
3. runtime picks up the updated SDK

This blocks building CLR tests on a new platform, until all of the above has happened (or we patch  SDK after the restore). For example, my current workaround is:

```sh
# workaround: overwrite file containing updated RIDs from libraries
/runtime $ cp src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json \
    .dotnet/sdk/5.0.100-preview.6.20310.4/RuntimeIdentifierGraph.json

# then cross-compile CLR tests without getting restore errors
/runtime $ ROOTFS_DIR=$(pwd)/.tools/rootfs/x64 ./src/coreclr/build-test.sh \
    -x64 -cross -os illumos -gcc
```

In the age of live-live builds, is it possible to ensure `LiveRuntimeIdentifierGraphPath` from `eng/liveBuilds.targets` is properly picked up during the SDK resolution for test build? Currently it seem to have no effect (despite being imported in `src/coreclr/tests/src/Common/test_dependencies/test_dependencies.csproj`) and SDK  ends up using `.dotnet/sdk/<version>/RuntimeIdentifierGraph.json`, instead of the `runtime.json` file pointed by `LiveRuntimeIdentifierGraphPath`.

cc @jashook, @jkotas

**Comment by am11** [comment]
I think the previous tag was correct; this was only encountered during the build of CLR tests.

**Comment by jkotas** [comment]
The fundamental problem is the process required to add new RIDs that falls under libraries though.

**Comment by ViktorHofer** [comment]
> In the age of live-live builds, is it possible to ensure LiveRuntimeIdentifierGraphPath from eng/liveBuilds.targets is properly picked up during the SDK resolution for test build?

I don't know how flowing of the RID graph into the SDK currently works. I assumed this is handled by the `Microsoft.NetCore.Platforms` OOB package so I'm wondering how the SDK comes into play here. @ericstj might know.

**Comment by jkoritzinsky** [comment]
To my knowledge dotnet/installer pulls down the Microsoft.NETCore.Platforms package during build and embeds the file in the final product.

**Comment by ericstj** [comment]
Seems like the SDK just needs a place to define this.  Let's see if they have it.  /cc @dsplaisted

**Comment by dsplaisted** [comment]
You can set the `BundledRuntimeIdentifierGraphFile` property to the path to the updated runtime identifier graph json file.  Is that what you're looking for?

**Comment by am11** [comment]
I think `RuntimeIdentifierGraphPath` is the way to define custom path, which SDK checks [here](https://github.com/dotnet/sdk/blob/062d9a036ea335833e472d3b3c17174ba62c5c19/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L23), and liveBuilds.targets defines at: https://github.com/dotnet/runtime/blob/c19ce52bb6aeb56fb255d7e989eb8471a0aad29a/eng/liveBuilds.targets#L202
For some reason it is not taking effect when this targets is imported by Directory.Build.targets at repo root. (it is already too late by then?)

Before the `cp` workaround mentioned above, I was getting:

```
/runtime/.dotnet/sdk/5.0.100-preview.6.20310.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): error NETSDK1083: The specified RuntimeIdentifier 'illumos-x64' is not recognized. [/runtime/src/coreclr/tests/src/Common/test_dependencies/test_dependencies.csproj] [/runtime/src/coreclr/tests/build.proj]
/runtime/src/coreclr/tests/build.proj(52,5): error MSB3073: The command ""/runtime/.dotnet/dotnet" restore -r illumos-x64 /runtime/src/coreclr/tests/src/Common/test_dependencies/test_dependencies.csproj  /p:SetTFMForRestore=true /p:TargetOS=illumos /p:TargetArchitecture=x64 /p:Configuration=Debug " exited with code 1.
```

**Comment by ericstj** [comment]
@am11 it looks like you need to set the property @dsplaisted mentions (`BundledRuntimeIdentifierGraphFile`)  it seems to get used in a few more places than `RuntimeIdentifierGraphPath`: https://github.com/dotnet/sdk/search?q=BundledRuntimeIdentifierGraphFile&unscoped_q=BundledRuntimeIdentifierGraphFile

**Comment by am11** [comment]
Replacing `RuntimeIdentifierGraphPath` with `BundledRuntimeIdentifierGraphFile` in `liveBuilds.targets` fixed the issue. I also had to import this targets in `external.csproj` and `ilasm.ilproj`. Will prepare a PR shortly. Thank you!
