### ISSUE TITLE
Arm64 legs are timing out in CI.

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#37823]
Looks like this is contributing to 9% failure rate.
https://dev.azure.com/dnceng/public/_build/results?buildId=684566
https://dev.azure.com/dnceng/public/_build/results?buildId=684308
https://dev.azure.com/dnceng/public/_build/results?buildId=684000
https://dev.azure.com/dnceng/public/_build/results?buildId=678126
https://dev.azure.com/dnceng/public/_build/results?buildId=675652
https://dev.azure.com/dnceng/public/_build/results?buildId=674382
https://dev.azure.com/dnceng/public/_build/results?buildId=673646
https://dev.azure.com/dnceng/public/_build/results?buildId=672860
https://dev.azure.com/dnceng/public/_build/results?buildId=672622

Evaluated 100 builds
Impacted 9 bulids
Impacted 44 jobs

@Safern mentioned this is happening due to overloading arm64 queues.

**Comment by safern** [comment]
@jashook and @ilya-bin -- since they're helping with the investigation.

**Comment by jashook** [comment]
We expect the impact to go up as our current queue depth is high.

**Comment by ilyas1974** [comment]
All machines in the queue are healthy and are running processing jobs as quickly as they can. At this point, as Jarret mentioned, it is a issue of the number of jobs within the queue.

**Comment by jashook** [comment]
Closing, average queue time today was 5 min
