### ISSUE TITLE
Remove MemoryExtensions.Slice (for now)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#37826]
https://github.com/dotnet/runtime/pull/37742#issuecomment-642788210
cc: @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
@stephentoub I assume this tracks https://github.com/dotnet/runtime/pull/37757, or was there a different API we should temporarily back out?

**Comment by stephentoub** [comment]
Oh, that PR passed by without me even noticing :)
