### ISSUE TITLE
Reflection does not work in the first attempt

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/runtime#37858]
### Description

I wrote the following code in a class library project

```cs
    public interface IRepository<T> {}

    public class Student {}
    public class Person  {}

    public interface IStudentRepository : IRepository<Student> {}
    public interface IPersonRepository : IRepository<Person> {}

    public class StudentRepo : IStudentRepository {}
    public class PersonRepo : IPersonRepository {}
```

And wrote this block of code in another console project

```cs
var types1 = AppDomain.CurrentDomain.GetAssemblies()
    .SelectMany(s => s.GetTypes())
    .Where(x => !x.IsInterface && x.GetInterfaces()
    .Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IRepository<>)))
    .ToList();
```

Something odd happened in the first call the code returns nothing but in the second attempts it works!!!

![41435bdb-5025-4929-a3c9-957263c8cec7](https://user-images.githubusercontent.com/8418700/84570220-317f7d00-ada1-11ea-89e4-5a33456d92ad.jpg)

The two blocks of code are the same !!!

![637d39c9-f3d0-491e-a402-08d2544af58c](https://user-images.githubusercontent.com/8418700/84570237-6390df00-ada1-11ea-8765-1880ba605752.jpg)

### Configuration

.NET Core 3.1.300 - Win 10 x64

**Comment by jkotas** [comment]
`AppDomain.CurrentDomain.GetAssemblies()`  returns the currently loaded assemblies. It can grow and shrink over time.

The likely explanation of the behavior you are seeing is that the assemblies with your types were not loaded for the first call, but they got loaded for the second call.

`AppDomain.CurrentDomain.GetAssemblies()` should be really only used for diagnostics. Searching through it like you have done is anti-pattern that leads to reliability and performance problems.
