### ISSUE TITLE
Custom ILogger does not receive exception passed to LogError extension method

### ISSUE THREAD

**Issue by superstator** [dotnet/runtime#37862]
### Describe the bug
The exception object passed to ILogger.LogError() is not passed to a custom ILogger implementation.

### To Reproduce

Create a trivial ILogger implementation:

```
public class ConsoleLogger : ILogger
{
    public IDisposable BeginScope<TState>(TState state) => null;

    public bool IsEnabled(LogLevel logLevel) => true;

    public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
    {
        Console.WriteLine(formatter(state, exception));

        if (exception != null)
        {
            Console.WriteLine(exception.Message);
        }
    }
}

public class ConsoleLoggerProvider : ILoggerProvider
{
    public ILogger CreateLogger(string categoryName) => new ConsoleLogger();
    public void Dispose() { }
}
```

Then log an exception from a simple console application:

```
static void Main(string[] args)
{
    var loggerFactory = LoggerFactory.Create(builder => builder.AddProvider(new ConsoleLoggerProvider()));

    ILogger logger = loggerFactory.CreateLogger<Program>();

    logger.LogError("Hello", new Exception("Ruh-roh"));
}
```

### Expected behavior

Expected output:

```
Hello
Ruh-roh
```

Actual output:
```
Hello
```

### Additional context
If I debug the Log<TState> method, the `exception` parameter is always null. The `state` object does contain the original exception, but only in a private `_values` collection. The [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger.log?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Logging_ILogger_Log__1_Microsoft_Extensions_Logging_LogLevel_Microsoft_Extensions_Logging_EventId___0_System_Exception_System_Func___0_System_Exception_System_String__) seems fairly clear that the `exception` argument should contain the logged exception.

I am using Microsoft.Extensions.Logging 3.1.5 via nuget.org, VS 16.6.1, and .NET Core 3.1.300.

**Comment by davidfowl** [comment]
You're calling the wrong overload of LogError:

![image](https://user-images.githubusercontent.com/95136/84577040-d6806280-ad6d-11ea-99b4-7b47bae55a7e.png)

The exception comes first:

![image](https://user-images.githubusercontent.com/95136/84577061-f31c9a80-ad6d-11ea-884d-ef3952b48a8e.png)

**Comment by superstator** [comment]
D'oh.

But then why doesn't the formatter do something with it? The metadata for that overload says "   An object array that contains zero or more objects to format.", but it seems to just ignore the extra object?

**Comment by davidfowl** [comment]
It's like passing a format string argument when there's no format string to `Console.WriteLine` or `string.Format`:

```C#
Console.WriteLine("Hello", new Exception(...));
```

VS

```C#
Console.WriteLine("Hello {0}", new Exception(...));
```

If you did this:

```C#
logger.LogError("Hello {Exception}", new Exception("Ruh-roh"));
```

It would show up, but that's not what you want anyways.

**Comment by superstator** [comment]
Fair enough. I'm just trying to think of a way to make that less of a trap - it's not exactly obvious you've switched them unless you dig into the overloads, and the `LogError(message, exception)` semantic feels pretty natural. log4net, for example, uses that format which is probably why I did it reflexively. Not that one is better than the other, I'd just like some kind of warning that I'm doing it the wrong way.

**Comment by superstator** [comment]
I added this extension to my project and found half a dozen more places I'd made the same mistake:

```
[Obsolete("Reversed arguments")]
public static void LogError(this ILogger logger, string message, Exception ex)
    => Microsoft.Extensions.Logging.LoggerExtensions.LogError(logger, ex, message);
```

So maybe this is a feature request now?

**Comment by davidfowl** [comment]
I mean, we wouldn't add a new API as obsolete, but maybe the logging analyzers can detect this.

**Comment by maryamariyan** [comment]
as per @davidfowl comment closing issue. @superstator if you have further questions please let us know and we can consider reopening it.
