### ISSUE TITLE
[Mono] FieldInfo.SetValue does not do an init check for readonly static fields

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#37903]
Related to https://github.com/dotnet/runtime/issues/37796 for Mono.

Given a program like this:

```csharp
using System;
using System.Runtime.CompilerServices;

internal class Program
{
    private static void Main(string[] args)
    {
        typeof(InlineReadOnly).GetField(nameof(InlineReadOnly.InlineMagicNumber)).SetValue(null, 0x123456789);

        InlineReadOnly.Test();

	typeof(InlineReadOnly).GetField(nameof(InlineReadOnly.InlineMagicNumber)).SetValue(null, 42);

        InlineReadOnly.Test2();

    }
}

public static class InlineReadOnly
{
	public static readonly long InlineMagicNumber = 0; //InlineReadOnly.GetInlineMagicNumber();

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Test() => Console.WriteLine(InlineReadOnly.InlineMagicNumber);

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Test2() => Console.WriteLine(InlineReadOnly.InlineMagicNumber);

    public static long GetInlineMagicNumber() => 0;
}
```

Mono prints:

```
4886718345
42
```

The expected behavior is to throw a FieldAccessException (See https://github.com/dotnet/runtime/pull/37849)

Note that Mono behavior here is different from CoreCLR - we can reset the field value multiple times.

(The two NoInlining methods are because we inline the value 0x123456789 when we JIT `Test`, so it's hard to observe that the second `SetValue` had an effect)

**Comment by lambdageek** [comment]
Note we will have to do the work twice: once for mini and once for the interpreter.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by lambdageek** [comment]
#97829 has better notes of what is going on with `SetValue` and a hint for how to fix it (using a check of the type initialization hash).

It looks like in this issue I thought there's work to be done in the JIT, too. But that needs to be verified (see the comment on 97829 about the `stsfld` outside a cctor

**Comment by lambdageek** [comment]
Closing in favor of #97829 which has better notes
