### ISSUE TITLE
foreach on non-generic should not issue nullable warnings

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#37918]
Consider:
```C#
#nullable enable
using System.Collections;
using System.Collections.Generic;

public class C {
    public void M()
    {
        var c = new BarCollection();
        foreach (Bar b in c) { } // warning CS8606: Possible null reference assignment to iteration variable
        foreach (Zoo? z in c) { } // ok
    }
}

public class BarCollection : IEnumerable, IEnumerable<Bar>
{
    public IEnumerator GetEnumerator() => null!;
    IEnumerator<Bar> IEnumerable<Bar>.GetEnumerator() => null!;
}

public class Bar{}
public class Zoo{}
```
The `foreach (Bar b in c)` will incur a nullable warning, because `IEnumerator.Current` is typed to return `object?`.  However, `foreach` over a non-generic `IEnumerable` allows the iteration variable to be of _any_ type, without warning, as highlighted by the `foreach (Zoo? z in c)` which has no warnings, even though it'll blow up at run time due to a failed cast.

We should change the nullable heuristics to simply not warn for the iteration variable when foreach binds to the non-generic `IEnumerable`.

Updated proposal: could we special-case for nullability the case where the type being enumerated implements `IEnumerable<T>`, and if the dev specifies `T` as the iteration variable or anything in its inheritance hierarchy, and if `T` is defined as non-nullable, treating it as non-null?

cc: @agocke, @jcouv

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/pull/37969

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/runtime/pull/37969
