### ISSUE TITLE
Profiling API Not Built Correctly

### ISSUE THREAD

**Issue by nealall123** [dotnet/runtime#37929]
Hi,

I'm following the instructions [here](https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI/ReJITEnterLeaveHooks) to write and build my own profiler and it worked fine at the existence of visual studio. However, when we tried to run this profiler in another computer without VS installed, it's not working any more and gave us this error.

`.NET Runtime version 4.0.30319.0 - Loading profiler failed during CoCreateInstance.  Profiler CLSID: '{cf0d821e-299b-5307-a3d8-b283c03916dd}'.  HRESULT: 0x8007007e.  Process ID (decimal): 2544.  Message ID: [0x2504].`

When we installed VS on, the profiler's working again. I'm new to Profiling API and not sure if we built it correctly against CoreClr repo and can someone please tell me if this is case or there is something wrong with our profiler? Does VS introduce some SDK or runtime that we're missing?

Thank you

**Comment by nealall123** [comment]
@sywhang Can you provide some suggestions? Thanks!

**Comment by sywhang** [comment]
@nealall123 I no longer work on the ICorProfiler APIs but @davmason should be able to help you out : )

**Comment by davmason** [comment]
Hi @nealall123 

0x8007007e is the HR for file not found (which can also mean that the dependency of a file is not found. Assuming you have already checked that the profiler exists and paths are set correctly, the most likely issue is that the particular Visual C++ redist you built against is not installed.

You can find the redists at https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.

If that doesn't fix it, the easiest way to diagnose is to either use something like depends.exe (third party tool) or turn on loader snaps via gflags (shipped with the windows SDK), and then run the program under windbg (also installed via windows sdk) to see the output of loader snaps.

**Comment by davmason** [comment]
I am assuming at this point that you figured out the issue. Feel free to get in touch if you haven't, for now I'm closing this issue.
