### ISSUE TITLE
SDK 3.0 does not find 2.2 and 2.1 runtimes (snap)

### ISSUE THREAD

**Issue by paaland** [dotnet/runtime#3793]
## Steps to reproduce
Install sdk 3.0 and runtimes 2.2 and 2.1 as snaps

```
$ snap list
Name               Version          Rev   Tracking   Publisher    Notes
core               16-2.41          7713  stable     canonical✓   core
core18             20191001         1192  stable     canonical✓   base
dotnet-runtime-21  2.1.13           18    stable     dotnetcore✓  -
dotnet-runtime-22  2.2.7            8     stable     dotnetcore✓  -
dotnet-runtime-30  3.0.0            1     stable     dotnetcore✓  -
dotnet-sdk         3.0.100          49    stable     dotnetcore✓  classic
```

Running dotnet info shows the 3.0 SDK does not find/know about the 2.1 and 2.2 runtimes:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/49/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/snap/dotnet-sdk/49/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/snap/dotnet-sdk/49/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/snap/dotnet-sdk/49/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

This makes it impossible to run anything but 3.0 projects using snap installed SDK

## Expected  behavior

The 3.0 SDK should find and use the runtime versions installed as separate snaps enabling me to run 2.2 and 2.1 apps from the 3.0 SDK. You really should offer the 2.2 and 2.1 SDKs as channels on your snap. That way I can decide which to install. Or the 3.0 SDK should include the 2.2 and 2.1 runtimes.

## Actual behavior

The 3.0 SDK and the 2.x runtimes does not find each other.

## Environment data

Linux Ubuntu 18.04 x64

**Comment by jmp75** [comment]
I am trying to test targeting .NET5 for [dynamic-interop-dll](https://github.com/rdotnet/dynamic-interop-dll) and [R.NET](https://github.com/rdotnet/rdotnet) but need to work with .net core 3.1 for current releases. Not being able to register several versions of the SDK is a nuisance.

`snap list`
```text
Name               Version                Rev   Tracking       Publisher    Notes
core               16-2.46.1              9993  latest/stable  canonical✓   core
core18             20200724               1885  latest/stable  canonical✓   base
dotnet-runtime-31  3.1.8                  9     latest/stable  dotnetcore✓  -
dotnet-sdk         5.0.100-rc.1.20452.10  100   5.0/beta       dotnetcore✓  classic
```

Trying `sudo snap install dotnet-sdk --classic --channel=3.1`  leads to:

snap "dotnet-sdk" is already installed, see 'snap help refresh'

I don't understand what "parallel install feature" can or cannot do, from reading the thread above.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
