### ISSUE TITLE
Test failure: Segmentation fault $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#37943]
failed in job: [runtime 20200615.71 ](https://dev.azure.com/dnceng/public/_build/results?buildId=688348&view=ms.vss-test-web.build-test-results-tab&runId=21367444&resultId=102233&paneView=debug)

failed tests:
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part2_r/AdvSimd_Part2_r.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part0_ro/AdvSimd_Part0_ro.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part1_r/AdvSimd_Part1_r.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part3_ro/AdvSimd_Part3_ro.sh
JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part0_r/AdvSimd.Arm64_Part0_r.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part3_r/AdvSimd_Part3_r.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part4_r/AdvSimd_Part4_r.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part1_ro/AdvSimd_Part1_ro.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part2_ro/AdvSimd_Part2_ro.sh
JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part1_r/AdvSimd.Arm64_Part1_r.sh
JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part1_ro/AdvSimd.Arm64_Part1_ro.sh

Error message
~~~
/root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part0_r/AdvSimd_Part0_r.sh: line 317: 871 Segmentation fault $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part0_r/AdvSimd_Part0_r.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun AdvSimd_Part0_r.dll ''
Supported ISAs:
 AdvSimd: False
 Aes: False
 ArmBase: False
 Crc32: False
 Sha1: False
 Sha256: False

Beginning test case Abs.Vector64.Int16 at 6/15/2020 8:24:24 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part0_r/AdvSimd_Part0_r.sh
Expected: True
Actual: False


Stack trace
   at JIT_HardwareIntrinsics._Arm_AdvSimd_AdvSimd_Part0_r_AdvSimd_Part0_r_._Arm_AdvSimd_AdvSimd_Part0_r_AdvSimd_Part0_r_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Release/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs:line 528
~~~

**Comment by BruceForstall** [comment]
@tannergooding PTAL
cc @echesakovMSFT
