### ISSUE TITLE
Mono Pri0 Runtime Tests Run Linux arm64 release leg failing

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#37946]
Looks like **Mono Pri0 Runtime Tests Run Linux arm64 release** leg started failing recently in `JIT.HardwareIntrinsics` test. See [these errors](https://helix.dot.net/api/2019-06-17/jobs/29ee0d94-e5e3-4cdd-acd7-c32156c3deca/workitems/JIT.HardwareIntrinsics/console). I noticed this failure in at least 4 PRs. https://github.com/dotnet/runtime/pull/37942, https://github.com/dotnet/runtime/pull/37912, https://github.com/dotnet/runtime/pull/37941 and https://github.com/dotnet/runtime/pull/37934. 

@tannergooding  made a change today to split the tests under ARM HWIntrinsic in https://github.com/dotnet/runtime/pull/37859. Is that related? I don't see this leg ran as part of this PR, so may be that's why it was not caught earlier.

**Comment by kunalspathak** [comment]
@tannergooding , @BruceForstall , @danmosemsft

**Comment by tannergooding** [comment]
I'd be very surprised if splitting the project into 5 suddenly started causing Mono to fail...

**Comment by benaadams** [comment]
Mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)

/root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part0_ro/AdvSimd_Part0_ro.sh: line 317: 650 
```
/root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part4_ro/AdvSimd_Part4_ro.sh: line 317: 1031 Segmentation fault $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part4_ro/AdvSimd_Part4_ro.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun AdvSimd_Part4_ro.dll ''
Supported ISAs:
 AdvSimd: False
 Aes: False
 ArmBase: False
 Crc32: False
 Sha1: False
 Sha256: False

Beginning test case ShiftRightLogicalNarrowingLower.Vector64.UInt32.1 at 6/16/2020 4:21:48 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part4_ro/AdvSimd_Part4_ro.sh
Expected: True
Actual: False
```
```
at JIT_HardwareIntrinsics._Arm_AdvSimd_AdvSimd_Part4_ro_AdvSimd_Part4_ro_._Arm_AdvSimd_AdvSimd_Part4_ro_AdvSimd_Part4_ro_sh()
 in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Release/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs:line 1401
```

**Comment by tannergooding** [comment]
Ah, they are timing out: https://helix.dot.net/api/2019-06-17/jobs/5ce10ff8-b722-4533-8535-485f9336e94a/workitems/JIT.HardwareIntrinsics/files/console.b6522eeb.log

`cmdLine:/root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part2_ro/AdvSimd_Part2_ro.sh Timed Out`

I wonder why splitting them is causing a timeout now... Maybe Mono was special casing the previous test?

**Comment by tannergooding** [comment]
Yes. They were excluded here: https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/issues.targets#L2575

This just needs to be updated to handle the new names, will have an update shortly.

**Comment by safern** [comment]
> I don't see this leg ran as part of this PR, so may be that's why it was not caught earlier.

I put up a PR to fix this, the condition for that leg was wrong: https://github.com/dotnet/runtime/pull/37985
