### ISSUE TITLE
Trimmability of token based reflection APIs

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#37958]
We have several APIs that deal with IL metadata tokens in the reflection API surface. It's not very clear to me what the use cases for these are, but trimming will definitely open us up to behavior changes (the tokens are going to shift around as linker removes things).

I would just mark them all as `RequiresUnreferencedCode`, but wanted to open this for discussion.

E.g. this is one of the APIs:
https://apisof.net/catalog/System.Reflection.Module.ResolveMember(Int32)

@vitek-karas @eerhardt Thoughts?

**Comment by vitek-karas** [comment]
Agreed - we should simply mark these with `RequiresUnreferencedCode`.
