### ISSUE TITLE
Performance regression in string.Compare(Ordinal)

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#37951]
### Benchmark code

```csharp
    [SimpleJob(RuntimeMoniker.NetCoreApp50, baseline: true)]
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    public class Program
    {

        static void Main(string[] args)
        {
            BenchmarkRunner.Run<Program>();
        }

        [Benchmark]
        public int CompareConstant() => string.Compare("abc", "def", StringComparison.Ordinal);

        [Benchmark]
        public int CompareOrdinalConstant() => string.CompareOrdinal("abc", "def");

        private string A
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get => "abc";
        }

        private string B
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get => "def";
        }

        [Benchmark(Baseline = true)]
        public int Compare() => string.Compare(A, B, StringComparison.Ordinal);

        [Benchmark]
        public int CompareOrdinal() => string.CompareOrdinal(A, B);
    }
```
### Environment

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.329 (2004/?/20H1)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-preview.5.20279.10
  [Host]        : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  .NET 4.8      : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT
  .NET Core 3.1 : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.0 (CoreCLR 5.0.20.27801, CoreFX 5.0.20.27801), X64 RyuJIT
```

### Regression?

.NET Core 3.1 already regressed from .NET Framework 4.8, and .NET 5 is even a more regression from .NET Core 3.1

### Data

|                 Method |           Job |       Runtime |     Mean |     Error |    StdDev | Ratio | RatioSD |
|----------------------- |-------------- |-------------- |---------:|----------:|----------:|------:|--------:|
|        CompareConstant |      .NET 4.8 |      .NET 4.8 | 1.955 ns | 0.0207 ns | 0.0184 ns |  0.43 |    0.01 |
| CompareOrdinalConstant |      .NET 4.8 |      .NET 4.8 | 1.121 ns | 0.0025 ns | 0.0019 ns |  0.25 |    0.00 |
|                Compare |      .NET 4.8 |      .NET 4.8 | 3.627 ns | 0.0227 ns | 0.0212 ns |  0.80 |    0.01 |
|         CompareOrdinal |      .NET 4.8 |      .NET 4.8 | 3.028 ns | 0.0105 ns | 0.0093 ns |  0.67 |    0.00 |
|        CompareConstant | .NET Core 3.1 | .NET Core 3.1 | 2.438 ns | 0.0231 ns | 0.0216 ns |  0.54 |    0.01 |
| CompareOrdinalConstant | .NET Core 3.1 | .NET Core 3.1 | 2.047 ns | 0.0045 ns | 0.0040 ns |  0.45 |    0.00 |
|                Compare | .NET Core 3.1 | .NET Core 3.1 | 4.533 ns | 0.0301 ns | 0.0267 ns |  1.00 |    0.00 |
|         CompareOrdinal | .NET Core 3.1 | .NET Core 3.1 | 3.589 ns | 0.0084 ns | 0.0079 ns |  0.79 |    0.01 |
|        CompareConstant | .NET Core 5.0 | .NET Core 5.0 | 2.488 ns | 0.0269 ns | 0.0210 ns |  0.55 |    0.00 |
| CompareOrdinalConstant | .NET Core 5.0 | .NET Core 5.0 | 2.497 ns | 0.0596 ns | 0.0528 ns |  0.55 |    0.01 |
|                Compare | .NET Core 5.0 | .NET Core 5.0 | 5.266 ns | 0.0872 ns | 0.0815 ns |  1.16 |    0.02 |
|         CompareOrdinal | .NET Core 5.0 | .NET Core 5.0 | 4.035 ns | 0.0408 ns | 0.0340 ns |  0.89 |    0.01 |

### Additional considerations

Do we need an analyzer to suggest `CompareOrdinal` over `Compare(StringComparison.Ordinal)`? The former is simpler and easier to optimize.

**Comment by stephentoub** [comment]
cc: @GrabYourPitchforks

**Comment by stephentoub** [comment]
@huoyaoyuan, have you tried strings longer than 3 characters?

**Comment by GrabYourPitchforks** [comment]
Re: the analyzer question, I don't think it's worth having an analyzer for this. You should use whatever calling pattern you find easiest to reason about. Most of our analyzers are for correctness or to steer you away from methods that have unexpectedly high algorithmic complexity.

Re: the perceived perf regression, per these results it's a half nanosecond per invocation. Probably explained by stack spilling or register reshuffling somewhere in the method. It appears to be fixed overhead per call, but I'd be concerned if it translates to a measurable difference given larger inputs.

**Comment by huoyaoyuan** [comment]
Rerun using larger strings:
```csharp
        const string str1 = "qwertyuiopasdfghjkl1";
        const string str2 = "qwertyuiopasdfghjkl2";
```
And the result:

|                 Method |           Job |       Runtime |     Mean |     Error |    StdDev | Ratio |
|----------------------- |-------------- |-------------- |---------:|----------:|----------:|------:|
|        CompareConstant |      .NET 4.8 |      .NET 4.8 | 5.676 ns | 0.0209 ns | 0.0196 ns |  0.66 |
| CompareOrdinalConstant |      .NET 4.8 |      .NET 4.8 | 4.398 ns | 0.0133 ns | 0.0118 ns |  0.51 |
|                Compare |      .NET 4.8 |      .NET 4.8 | 6.598 ns | 0.0121 ns | 0.0107 ns |  0.77 |
|         CompareOrdinal |      .NET 4.8 |      .NET 4.8 | 6.075 ns | 0.0280 ns | 0.0261 ns |  0.71 |
|        CompareConstant | .NET Core 3.1 | .NET Core 3.1 | 5.660 ns | 0.0347 ns | 0.0325 ns |  0.66 |
| CompareOrdinalConstant | .NET Core 3.1 | .NET Core 3.1 | 6.150 ns | 0.0279 ns | 0.0261 ns |  0.72 |
|                Compare | .NET Core 3.1 | .NET Core 3.1 | 8.541 ns | 0.0311 ns | 0.0275 ns |  1.00 |
|         CompareOrdinal | .NET Core 3.1 | .NET Core 3.1 | 7.438 ns | 0.0185 ns | 0.0155 ns |  0.87 |
|        CompareConstant | .NET Core 5.0 | .NET Core 5.0 | 6.051 ns | 0.0175 ns | 0.0163 ns |  0.71 |
| CompareOrdinalConstant | .NET Core 5.0 | .NET Core 5.0 | 5.446 ns | 0.0076 ns | 0.0067 ns |  0.64 |
|                Compare | .NET Core 5.0 | .NET Core 5.0 | 8.678 ns | 0.0646 ns | 0.0572 ns |  1.02 |
|         CompareOrdinal | .NET Core 5.0 | .NET Core 5.0 | 7.090 ns | 0.0135 ns | 0.0120 ns |  0.83 |

It's still a regression from .NET Framework, but .NET Core 3.1 and 5.0 are now very close.

**Comment by GrabYourPitchforks** [comment]
I quickly glanced at the compare routine. While it probably doesn't make sense to vectorize this code (since differences in the string tend to manifest very early), there's definitely some low-hanging fruit that can be addressed. I'll run some experiments once the current work winds down.

**Comment by kamronbatman** [comment]
One thing I noted in a .NET 5 upgrade PR for my project is that `CompareOrdinal` and `Compare` using Ordinal use different code paths. The former uses `CompareOrdinalHelper` which does some tricks, while the latter uses
`SpanHelpers.SequenceCompareTo`.

I think this code should be tightened so they both take the same code path, whichever achieves better performance, especially since I assume they both achieve the same results.

**Comment by stephentoub** [comment]
> The former uses CompareOrdinalHelper which does some tricks, while the latter uses SpanHelpers.SequenceCompareTo.

CompareOrdinalHelper just calls SpanHelpers.SequenceCompareTo.

Can you elaborate on the difference you're seeing?

**Comment by kamronbatman** [comment]
@stephentoub, maybe I am reading this wrong, but this is what I see:
```cs
        public static int CompareOrdinal(string? strA, string? strB)
        {
            if (object.ReferenceEquals(strA, strB))
            {
                return 0;
            }

            // They can't both be null at this point.
            if (strA == null)
            {
                return -1;
            }
            if (strB == null)
            {
                return 1;
            }

            // Most common case, first character is different.
            // This will return false for empty strings.
            if (strA._firstChar != strB._firstChar)
            {
                return strA._firstChar - strB._firstChar;
            }

            return CompareOrdinalHelper(strA, strB);
        }
```

```cs
        private static unsafe int CompareOrdinalHelper(string strA, string strB)
        {
            Debug.Assert(strA != null);
            Debug.Assert(strB != null);

            // NOTE: This may be subject to change if eliminating the check
            // in the callers makes them small enough to be inlined
            Debug.Assert(strA._firstChar == strB._firstChar,
                "For performance reasons, callers of this method should " +
                "check/short-circuit beforehand if the first char is the same.");

            int length = Math.Min(strA.Length, strB.Length);

            fixed (char* ap = &strA._firstChar) fixed (char* bp = &strB._firstChar)
            {
                char* a = ap;
                char* b = bp;

                // Check if the second chars are different here
                // The reason we check if _firstChar is different is because
                // it's the most common case and allows us to avoid a method call
                // to here.
                // The reason we check if the second char is different is because
                // if the first two chars the same we can increment by 4 bytes,
                // leaving us word-aligned on both 32-bit (12 bytes into the string)
                // and 64-bit (16 bytes) platforms.

                // For empty strings, the second char will be null due to padding.
                // The start of the string is the type pointer + string length, which
                // takes up 8 bytes on 32-bit, 12 on x64. For empty strings the null
                // terminator immediately follows, leaving us with an object
                // 10/14 bytes in size. Since everything needs to be a multiple
                // of 4/8, this will get padded and zeroed out.

                // For one-char strings the second char will be the null terminator.

                // NOTE: If in the future there is a way to read the second char
                // without pinning the string (e.g. System.Runtime.CompilerServices.Unsafe
                // is exposed to mscorlib, or a future version of C# allows inline IL),
                // then do that and short-circuit before the fixed.

                if (*(a + 1) != *(b + 1)) goto DiffOffset1;

                // Since we know that the first two chars are the same,
                // we can increment by 2 here and skip 4 bytes.
                // This leaves us 8-byte aligned, which results
                // on better perf for 64-bit platforms.
                length -= 2; a += 2; b += 2;

                // unroll the loop
#if TARGET_64BIT
                while (length >= 12)
                {
                    if (*(long*)a != *(long*)b) goto DiffOffset0;
                    if (*(long*)(a + 4) != *(long*)(b + 4)) goto DiffOffset4;
                    if (*(long*)(a + 8) != *(long*)(b + 8)) goto DiffOffset8;
                    length -= 12; a += 12; b += 12;
                }
#else // TARGET_64BIT
                while (length >= 10)
                {
                    if (*(int*)a != *(int*)b) goto DiffOffset0;
                    if (*(int*)(a + 2) != *(int*)(b + 2)) goto DiffOffset2;
                    if (*(int*)(a + 4) != *(int*)(b + 4)) goto DiffOffset4;
                    if (*(int*)(a + 6) != *(int*)(b + 6)) goto DiffOffset6;
                    if (*(int*)(a + 8) != *(int*)(b + 8)) goto DiffOffset8;
                    length -= 10; a += 10; b += 10;
                }
#endif // TARGET_64BIT

                // Fallback loop:
                // go back to slower code path and do comparison on 4 bytes at a time.
                // This depends on the fact that the String objects are
                // always zero terminated and that the terminating zero is not included
                // in the length. For odd string sizes, the last compare will include
                // the zero terminator.
                while (length > 0)
                {
                    if (*(int*)a != *(int*)b) goto DiffNextInt;
                    length -= 2;
                    a += 2;
                    b += 2;
                }

                // At this point, we have compared all the characters in at least one string.
                // The longer string will be larger.
                return strA.Length - strB.Length;

#if TARGET_64BIT
            DiffOffset8: a += 4; b += 4;
            DiffOffset4: a += 4; b += 4;
#else // TARGET_64BIT
                // Use jumps instead of falling through, since
                // otherwise going to DiffOffset8 will involve
                // 8 add instructions before getting to DiffNextInt
                DiffOffset8: a += 8; b += 8; goto DiffOffset0;
                DiffOffset6: a += 6; b += 6; goto DiffOffset0;
                DiffOffset4: a += 2; b += 2;
                DiffOffset2: a += 2; b += 2;
#endif // TARGET_64BIT

            DiffOffset0:
                // If we reached here, we already see a difference in the unrolled loop above
#if TARGET_64BIT
                if (*(int*)a == *(int*)b)
                {
                    a += 2; b += 2;
                }
#endif // TARGET_64BIT

            DiffNextInt:
                if (*a != *b) return *a - *b;

                DiffOffset1:
                Debug.Assert(*(a + 1) != *(b + 1), "This char must be different if we reach here!");
                return *(a + 1) - *(b + 1);
            }
        }
```
🤔

**Comment by huoyaoyuan** [comment]
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19043.1081 (21H1/May2021Update)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100-preview.5.21302.13
  [Host]             : .NET 6.0.0 (6.0.21.30105), X64 RyuJIT
  .NET 5.0           : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT
  .NET 6.0           : .NET 6.0.0 (6.0.21.30105), X64 RyuJIT
  .NET Framework 4.8 : .NET Framework 4.8 (4.8.4360.0), X64 RyuJIT


|                 Method |                Job |            Runtime |     Mean |     Error |    StdDev | Ratio |
|----------------------- |------------------- |------------------- |---------:|----------:|----------:|------:|
|        CompareConstant |           .NET 5.0 |           .NET 5.0 | 6.754 ns | 0.0198 ns | 0.0185 ns |  1.14 |
|        CompareConstant |           .NET 6.0 |           .NET 6.0 | 6.268 ns | 0.0340 ns | 0.0318 ns |  1.06 |
|        CompareConstant | .NET Framework 4.8 | .NET Framework 4.8 | 5.924 ns | 0.0250 ns | 0.0234 ns |  1.00 |
|                        |                    |                    |          |           |           |       |
| CompareOrdinalConstant |           .NET 5.0 |           .NET 5.0 | 5.768 ns | 0.0660 ns | 0.0618 ns |  1.09 |
| CompareOrdinalConstant |           .NET 6.0 |           .NET 6.0 | 4.875 ns | 0.0633 ns | 0.0592 ns |  0.92 |
| CompareOrdinalConstant | .NET Framework 4.8 | .NET Framework 4.8 | 5.283 ns | 0.0264 ns | 0.0234 ns |  1.00 |
|                        |                    |                    |          |           |           |       |
|                Compare |           .NET 5.0 |           .NET 5.0 | 9.269 ns | 0.0411 ns | 0.0384 ns |  1.09 |
|                Compare |           .NET 6.0 |           .NET 6.0 | 8.615 ns | 0.0296 ns | 0.0277 ns |  1.02 |
|                Compare | .NET Framework 4.8 | .NET Framework 4.8 | 8.478 ns | 0.0231 ns | 0.0193 ns |  1.00 |
|                        |                    |                    |          |           |           |       |
|         CompareOrdinal |           .NET 5.0 |           .NET 5.0 | 8.285 ns | 0.0551 ns | 0.0515 ns |  1.07 |
|         CompareOrdinal |           .NET 6.0 |           .NET 6.0 | 6.794 ns | 0.0692 ns | 0.0647 ns |  0.88 |
|         CompareOrdinal | .NET Framework 4.8 | .NET Framework 4.8 | 7.738 ns | 0.0300 ns | 0.0281 ns |  1.00 |

We are now faster with ordinal and slower with culture-aware. Encountering the NLS vs ICU change, performance change with culture-aware comparison is expected. I'm considering this resolved and closing.
