### ISSUE TITLE
Initial HTTPS request with client certificate fails on Linux, subsequent requests succeeds

### ISSUE THREAD

**Issue by pardahlman** [dotnet/runtime#37952]
### Description

We are migrating a .NET Framework application to a .NET Core 3.1 application running on Linux in kubernetes. The application uses an `HttpClient` with client certificates to send request to an HTTP server. This works as expected when running on .NET Framework as well as .NET Core 3.1 on Windows. However, we get an unexpected behavior when running on Linux:

The first HTTP request fails with the following stack trace:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
```

All subsequent requests to the HTTP server are successful. When monitoring the network traffic from the container, it becomes clear that the first request to the server only contains the leaf client certificate, whereas the following requests also contains the intermediate certificates.

This behavior can not be reproduced by using curl from within a newly created container. With curl, the request always succeeds and the observed network traffic shows that all requests contain the leaf client certificate as well as the intermediate ones.

Our application code is very much inspired by @bartonjs's answer to [this StackOverflow question]( https://stackoverflow.com/questions/61677247/can-a-p12-file-with-ca-certificates-be-used-in-c-sharp-without-importing-them-t) (_Can a .p12 file with CA certificates be used in C# without importing them to certificate store_). That is: we put intermediate certificates in the current user's `CertificateAuthority` store and only add the certificate to which we have the private key in the `HttpClient.ClientCertificates` property.

Is this behavior expected, or can we make modifications to our code to prevent this from happening?

### Configuration

The Docker image is built on `mcr.microsoft.com/dotnet/core/aspnet:3.1`,  `dotnet --info` outputs

```
Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

`DEFAULT@SECLEVEL` has been lowered from 2 to 1 the container (OpenSSL configuration)

**Comment by wfurt** [comment]
Do you se attempt to fetch the intermediate certificates on the first request? I would expect that if everything is in the store, there would be no need. Also if you have simple app to demonstrate it, I can take a look if we can reproduce it.

**Comment by pardahlman** [comment]
My apologizes for not getting back earlier. Creating a repro app proved to be more challenging than I first expected. It seems to me that in order to reproduce this I had to do one of the following:

* Perform an outgoing HTTPS call without client certificate.
* Open an SQL connection to database server

This may sound odd, but performing one of those operations prior to the HTTPS call ensure deterministic failure.

Here is sample code that can be run to verify this:  https://github.com/pardahlman/issue-client-cert

It does the following:

1. Make HTTPS call to google.com
2. Make HTTPS call with client certificate to third party integration, this call fails with _sslv3 alert handshake failure_
3. Wait for two seconds before making next call, a direct call will fail again
4. Make an identical call as in 2., this time it succeeds.

Hope this helps!

**Comment by wfurt** [comment]
I'm not able to reproduce it. I checkout the repo and I get 
```
docker run --rm issue-client-cert
Making an HTTPS call to Google without client certificate.
Loading certificate from /app/swish_client_certificate_test.p12.
Certificate chain consists of 3 entries.
The first HTTP request succeeded.
Waiting for 2 seconds, a direct call will fail again.
The second HTTP request succeeded.
```

so the first client authentication works just fine. Could you do packet capture of all traffic from that container? 
It seems like this can be some environmental issue. 

cc: @bartonjs since he commented on the StackOverflow post.

**Comment by pardahlman** [comment]
That is very strange. I have reproduced this on my Windows laptop, my Macbook Pro, in the GCP cloud as well as on my colleagues Windows laptop. There are at three different networks used. I'll get back to you once I've captured the network traffic.

**Comment by akselsson** [comment]
I was able to reproduce this, but only on the second time i ran the container:

```
PS E:\Projects\temp\issue-client-cert> docker run --rm  issue-client-cert
Making an HTTPS call to Google without client certificate.
Loading certificate from /app/swish_client_certificate_test.p12.
Certificate chain consists of 3 entries.
The first HTTP request succeeded.
Waiting for 2 seconds, a direct call will fail again.
The second HTTP request succeeded.
PS E:\Projects\temp\issue-client-cert> docker run --rm  issue-client-cert
Making an HTTPS call to Google without client certificate.
Loading certificate from /app/swish_client_certificate_test.p12.
Certificate chain consists of 3 entries.
The first HTTP request failed with 'sslv3 alert handshake failure'.
Waiting for 2 seconds, a direct call will fail again.
The second HTTP request succeeded.
PS E:\Projects\temp\issue-client-cert>
```

**Comment by wfurt** [comment]
can you do packet captures @akselsson ?

**Comment by oskar** [comment]
I was able to reproduce this in a Docker container on Windows. Attached is [a pcap file](https://github.com/dotnet/runtime/files/4869314/issue-client-cert.zip) created with tcpdump.

Inspecting the tcpdump in Wireshark, it's possible to see that on the first (failing) request, only the leaf certficate is included in the request. On the second (succeding) request, the leaf certificate along with its intermediate certificates are included.

**Comment by oskar** [comment]
Use this `docker-compose.yml` file:

```docker-compose.yml
version: '3'
services:
  issue-client-cert:
    image: pardahlman/issue-client-cert:latest
    entrypoint: ["sleep", "infinity"]
  sidecar:
    image: "corfr/tcpdump"
    volumes:
      - ./tcpdump-data:/data
    network_mode: "service:issue-client-cert"
```

and run this to reproduce and capture the network traffic:
```
docker-compose up -d
docker-compose exec issue-client-cert dotnet /app/issue-client-cert.dll
docker-compose down

wireshark.exe .\tcpdump\dump00
```

Complete command line log:

```
C:\dev> docker-compose up -d
Creating network "dev_default" with the default driver
Creating dev_issue-client-cert_1 ... done
Creating dev_sidecar_1           ... done
C:\dev> docker-compose exec issue-client-cert dotnet /app/issue-client-cert.dll
Making an HTTPS call to Google without client certificate.
Loading certificate from /app/swish_client_certificate_test.p12.
Certificate chain consists of 3 entries.
The first HTTP request failed with 'sslv3 alert handshake failure'.
Waiting for 2 seconds, a direct call will fail again.
The second HTTP request succeeded.
C:\dev> docker-compose down
Stopping dev_sidecar_1           ... done
Stopping dev_issue-client-cert_1 ... done
Removing dev_sidecar_1           ... done
Removing dev_issue-client-cert_1 ... done
Removing network dev_default
C:\dev> wireshark.exe .\tcpdump-data\dump00
```

**Comment by wfurt** [comment]
cc: @bartonjs. The intermediate certificates would normally be downloaded and that would be subject to external failures. But if they come from pfx file, I would expect it to work. It seems like the results are inconsistent. I'll give it another try to see if I can reproduce it.

**Comment by bartonjs** [comment]
This is probably related to the store caching that we added, to avoid warm-reading the filesystem every chain build.  Basically, it'll repro unless the GetLeafCertAndAddIntermediateToStore call happens after the second current has rolled over from the first call (because the last modified time is only to the second, so sub-second operations can get lost).

I can try to force local operations to blow the cache, but I thought I already had that (there shouldn't be any race conditions here, so clearly not).

If you load the p12 intermediates first, everything should just work.

**Comment by wfurt** [comment]
this is all in sequence @bartonjs and the --rm nukes the container every time. You can look at the code from linked repro https://github.com/pardahlman/issue-client-cert/blob/master/Program.cs
I was wondering if X509Chain.Build(clientCertificate) would fix it but I don't understand why this is not predictable.

**Comment by bartonjs** [comment]
The certificate doesn't have an AIA record, so when the CA (intermediates) store (or, at least, the outdated cache) can't find it, the chain build fails.

If it did have an AIA record, it would, of course, fix itself, but with an unnecessary download.

**Comment by bartonjs** [comment]
We improved the cache flush logic in #48149, which should address the scenario here.
