### ISSUE TITLE
Updating reference sources for System.Runtime don't work

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#37966]
https://github.com/dotnet/runtime/blob/1692e34e4161fa8ee9d3f92ba0abb2aae93a8b1a/docs/coding-guidelines/updating-ref-source.md

After following these instructions I would expect the generated ref assembly to have the extra attributes added in #37704 but it doesn't.

It doesn't look too surprising since GenApi is invoked with a single input: the single input is the ref assembly that I want to update in the first place. It's not clear to me how this is supposed to work (replacing the ref with the impl assembly and specifying a libpath produces and empty file instead).

```
"C:\git\runtime\.dotnet\dotnet.exe" "C:\Users\michals\.nuget\packages\microsoft.dotnet.genapi\5.0.0-beta.20309.1\build\\..\tools\netcoreapp2.1\Microsoft.DotNet.GenAPI.dll" "C:\git\runtime\artifacts\obj\System.Runtime\ref\net5.0-Release\System.Runtime.dll" --lib-path "" --out "C:\git\runtime\src\libraries\System.Runtime\ref\System.Runtime.cs"  --exclude-attributes-list "C:\git\runtime\eng\DefaultGenApiDocIds.txt" --header-file "C:\git\runtime\eng\LicenseHeader.txt" --lang-version "preview" (TaskId:17)
```

**Comment by MichalStrehovsky** [comment]
@eerhardt Could you help me route this?

**Comment by stephentoub** [comment]
cc: @safern

**Comment by safern** [comment]
The docs are wrong here. Before we didn’t support following TypeForwards in GenApi and that’s why we needed to run it from the ref folder but now we have that support. @MichalStrehovsky can you try running `dotnet build --no-incremental /t:GenerateReferenceSource` from the src directory instead?

**Comment by MichalStrehovsky** [comment]
Yep, running that command from src works, thanks! I'll submit a pull request to update the doc and resolve this issue.

**Comment by ViktorHofer** [comment]
> @MichalStrehovsky can you try running dotnet build --no-incremental /t:GenerateReferenceSource from the src directory instead?

@safern just curious, why did you add the `--no-incremental` flag to the command?

**Comment by safern** [comment]
From what I remember there was an issue that if people built with their changes and then try to generate reference source again with dotnet build, the `GenerateReferenceSource` target is skipped and is a no-op because of the inputs and outputs because they're up to date.

**Comment by ViktorHofer** [comment]
That makes sense, thanks for clarifying 👍
