### ISSUE TITLE
Change Microsoft.XmlSerializer.Generator to not use private reflection on XElement constructor

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#37970]
See the discussion in #35725, specifically this comment: https://github.com/dotnet/runtime/issues/35725#issuecomment-622600338.

We should change the C# generation to special case XElement (just like we did for the IL generation case), and have it generate new XElement("default") instead of calling `Activator.CreateInstance`. Using private reflection can easily be broken in the future, so we shouldn't rely on it.

**Comment by danmosemsft** [comment]
Per https://github.com/dotnet/runtime/blob/master/docs/area-owners.md this is owned by @HongGit @StephenMolloy
