### ISSUE TITLE
ARM64 manual install: dotnet-dump libhostfxr.so could not be found

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#37988]
```bash
stmaclea@rpi:~$ uname -a
Linux rpi 5.4.0-1012-raspi #12-Ubuntu SMP Wed May 27 04:08:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

APT packages for the arm64 SDK are not available. 
Installed SDK using dotnet-install script.
Installed dotnet-dump using `dotnet tool install dotnet-dump --global`

Set environment as...
```bash
stmaclea@rpi:~$cat ~/.bash_profile 
# Add .NET Core
export PATH="$PATH:/home/stmaclea/.dotnet"
# Add .NET Core SDK tools
export PATH="$PATH:/home/stmaclea/.dotnet/tools"
stmaclea@rpi:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/stmaclea/.dotnet:/home/stmaclea/.dotnet/tools
```

When running `dotnet-dump ps` libhostfxr.so is not found. 
When running `dotnet dump ps` libhostfxr.so is not found. 

Set `DOTNET_ROOT` as recommended by the failure.  No success.

```bash
stmaclea@rpi:~$ dotnet dump ps
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/stmaclea/.dotnet/tools/.store/dotnet-dump/3.1.122203/dotnet-dump/3.1.122203/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=ubuntu.20.04-arm64
stmaclea@rpi:~$ echo $DOTNET_ROOT
/home/stmaclea/.dotnet
stmaclea@rpi:~$ find $DOTNET_ROOT -name libhostfxr.so
/home/stmaclea/.dotnet/host/fxr/3.1.5/libhostfxr.so
```

Setting /etc/dotnet/install_location worked.

```bash
stmaclea@rpi:~$ cat << EOF >> install_location
/home/stmaclea/.dotnet
EOF
stmaclea@rpi:~$ sudo mkdir /etc/dotnet
stmaclea@rpi:~$ sudo mv install_location /etc/dotnet/install_location
stmaclea@rpi:~$ dotnet dump ps
      4841 dotnet     /home/stmaclea/.dotnet/dotnet
```

/cc @vitek-karas @mikem8361

**Comment by vitek-karas** [comment]
This is basically the same problem as discussed in https://github.com/dotnet/install-scripts/issues/43#issuecomment-644143526 (and mainly the linked issue https://github.com/dotnet/docs/issues/18715). The `dotnet-install` script is not an installer, and will not setup the environment for you in any way really.

Setting the `DOTNET_ROOT` should work with the `dotnet-dump` approach.
I'm surprised the `dotnet dump` didn't work on its own - can you please double check that it ran `dotnet` from the right location in that case?

Setting the `etc/dotnet/install_location` is definitely the best way if you want the install to be "machine wide".

**Comment by sdmaclea** [comment]
OK.  The `DOTNET_ROOT` was at least partially user error.  I set the variable, but didn't export it.  Perhaps `use the DOTNET_ROOT environment variable` should change to `export the DOTNET_ROOT environment variable` as a reminder to the user.

The `dotnet dump ps` doesn't work.  Probably because it is implicitly calling `dotnet-dump`.  IF I pass the the explicit path, it does work. i.e. `dotnet /home/stmaclea/.dotnet/tools/.store/dotnet-dump/3.1.122203/dotnet-dump/3.1.122203/tools/netcoreapp2.1/any/dotnet-dump.dll ps`

**Comment by sdmaclea** [comment]
I happy to just close this as a duplicate.
