### ISSUE TITLE
Consider adding issue / PR templates

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#380]
I often see issues / pull requests asking for new APIs to be exposed, which can't be done immediately because it has to go through API review process. I also see a lot of issues related with bugs without any reproducible code / runtime version which is crucial for approaching problems.

It would be great if we have templates for issues and PR templates to list out some important details perhaps?

**Comment by danmosemsft** [comment]
@karelz have other folks expressed opinions about templates? On repos with these I always seem to end up deleting all the text -- but this isn't about me 😃 I don't mind adding them.

**Comment by karelz** [comment]
I am in favor of not having them (status quo) - we considered them and didn't find them super useful.
