### ISSUE TITLE
API Proposal: ExecutionContext.Restore(ExecutionContext? executionContext)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#38011]
## Background and Motivation

Alternative to the approved api https://github.com/dotnet/runtime/issues/30867 "ExecutionContext.Run<TContext> ref overloads"

`await`ing a `Task` returning method that is itself not `async` does not guarantee undoing `AsyncLocal`/`ExecutionContext` changes (as it is the responsibility of the callee)

`ExecutionContext` does provide an callback based method that acts as a stack:

```csharp
public sealed class ExecutionContext
{
    ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object? state)
}
```

However using it to just undo changes is clunky (involves rearranging code into a callback); as well as applying the current context to run on, when its already on the current context.

It also doesn't provide a return value; and if it was guarding multiple `await`s arranging to return a single `Task` (via using state as a reference) becomes complicated.

Rather than using it in a stack based "apply=>undo" manner; it would be useful if it could be restored directly inline.

Related ASP.NET issues dotnet/aspnetcore#15384, dotnet/aspnetcore#13991

## Proposed API

```csharp
namespace System.Threading
{
    public sealed class ExecutionContext
    {
        public static void Restore(ExecutionContext? executionContext);
    }
}
```

## Usage Examples

``` C#
var ec = ExecutionContext.Capture();
while (!cancelled)
{
    await NextRequest();

    await OnStartAsync();

    await ProcessRequestAsync();

    await OnCompleteAsync();

    ExecutionContext.Restore(ec);
}
```

## Alternative Designs
https://github.com/dotnet/runtime/issues/30867 "ExecutionContext.Run<TContext> ref overloads"; this again requires contorting the code to the callback based pattern and is problematic for multiple awaits as regular `.Run` as well as introducing a large method that has generic code expansion.

Also guard the multiple `await`s behind an explicitly `async` method:
``` C#
while (!cancelled)
{
    await NextRequest();

    await ProcessUserCode();
}

async ValueTask ProcessUserCode()
{
    await OnStartAsync();

    await ProcessRequestAsync();

    await OnCompleteAsync();
}
```
However this introduces an extra statemachine per request and an additional allocation per request; as well as causing the ExecutionContext to be captured and restored per request; when really we just want to capture it at the start of request processing and only restore/reset it per request.

/cc @davidfowl @stephentoub

**Comment by benaadams** [comment]
Related change in ASP.NET that would make use of this api https://github.com/dotnet/aspnetcore/pull/23175

**Comment by benaadams** [comment]
@stephentoub are you happy for this to be for review?

**Comment by stephentoub** [comment]
@kouvel, any concerns with this being exposed?

**Comment by benaadams** [comment]
Was a naming question raised https://github.com/dotnet/runtime/pull/37942#discussion_r445120759
 
> Would it make sense to call this method `Apply` or something similar instead of `Restore` given how it's used?

**Comment by stephentoub** [comment]
Either seems fine to me.

**Comment by kouvel** [comment]
Looks fine to me. I was also wondering if it should be prefixed with `Unsafe` since it would allow changing the EC arbitrarily which may not have been possible to do before, but can determine in the review.

**Comment by terrajobst** [comment]
@stephentoub @kouvel This is marked as 6.0. If we were to approve this this week, would it still make sense for 5.0?

**Comment by benaadams** [comment]
>  This is marked as 6.0. If we were to approve this this week, would it still make sense for 5.0?

Would mean the upstream change in aspnet core could be merged for 5.0 https://github.com/dotnet/aspnetcore/pull/23175

/cc @davidfowl

**Comment by stephentoub** [comment]
> If we were to approve this this week, would it still make sense for 5.0?

Yes

**Comment by terrajobst** [comment]
Looks good as proposed.

```C#
namespace System.Threading
{
    public sealed class ExecutionContext
    {
        public static void Restore(ExecutionContext? executionContext);
    }
}
```
