### ISSUE TITLE
Allow test projects to build against reference assemblies but consume the implementation assembly (app-local)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#38037]
Test projects use P2Ps to reference dependencies which sit on top of the targeting packs (.NETStandard, .NETFramework, .NETCoreApp), also called OOB projects. In most cases such P2Ps point to a library's reference assembly. None of these P2Ps are copying assets into the test app's output folder today.

To guarantee that we test the product the way customers use it, we should turn our OOB assemblies app-local instead of part of the shared framework. This means not binplacing the OOB implementation assemblies into the `runtime` and `testhost` folder anymore and adding infrastructure to build against a reference assembly but copy the implementation assembly into the test output folder.

Roslyn's [RefOut](https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md) feature is similar in the way that a P2P against a project that uses the RefOut feature builds against the generated ref assembly but copies the implementation assembly into the output directory. There might be a way to leverage that functionality without using the RefOut feature.

There are two benefits out of this:
1. Construct the shared framework and OOB assemblies the same way that a customer uses them. Test what a customer uses.
2. Improve developer productivity by building the implementation assembly along with the test assembly (initially only for OOBs).

cc @ericstj @safern @joperezr @jaredpar

**Comment by ericstj** [comment]
P2P's call GetTargetPath which now returns `@(TargetPathWithTargetPlatformMoniker)`

See https://github.com/microsoft/msbuild/blob/9eb5d09e6cd262375e37a15a779d56ab274167c8/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1917-L1924

Perhaps all we need to do is insert a target and add `ReferenceAssembly` metadata, to point to the reference assembly we built separately?  (and optionally trigger a build of that reference assembly if we wish).

**Comment by ViktorHofer** [comment]
This was fixed with https://github.com/dotnet/runtime/commit/809a06f45161ae686a06b9e9ccc2f45097b91657.
