### ISSUE TITLE
System.Threading.Thread.Tests PNSE on iOS, tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#38032]
System.Threading.Thread.Tests

## PlatformNotSupportedException
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent

**Comment by SamMonoRT** [comment]
@mdh1418 - assigning to you for further action, not sure who is actually implementing it.

**Comment by steveisok** [comment]
The test has been marked correctly on ios/tvos/catalyst
