### ISSUE TITLE
Enable linker analysis and add baselines for warnings

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#38033]
https://github.com/mono/linker/issues/1030 will change the ILLinker that it will start adding warnings by default when it detects unsafe use of reflection. This will cause our libraries build to start emitting a lot of warnings (in the hundreds).

To keep our build clean, we should add a "baseline" of linker warnings to the repo, which will suppress the warnings. In the future, as we annotate the usages of reflection to make them linker-safe, we can remove the suppressions.

To suppress individual warnings, we can create a `LinkerSuppressions.cs` file in each project that will contain `UnconditionalSuppressMessage` attributes. @mateoatr is working on a mechanism that can generate these suppress message attributes that we can use to bootstrap the baselines.

cc @vitek-karas

**Comment by joperezr** [comment]
@eerhardt @layomia isn't this done already?

**Comment by layomia** [comment]
@joperezr not yet - I need to update https://github.com/dotnet/runtime/pull/40691 following the new linker warning codes brought in with https://github.com/dotnet/runtime/pull/40865.

**Comment by layomia** [comment]
Moving to 6.0 as this isn't needed for 5.0.

**Comment by eerhardt** [comment]
Resolved by https://github.com/dotnet/runtime/pull/40691. Closing.
