### ISSUE TITLE
Fixup nullable on ObjectFactory

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#38043]
Should be able to pass null as the arguments for the ObjectFactory.

>There's more things in the ObjectFactory that should be nullable that I missed.

https://github.com/dotnet/aspnetcore/pull/23040#discussion_r441717592

cc @pranavkm

**Comment by Marusyk** [comment]
Hi @BrennanConroy,
do you mean to add one more delagate without `arguments` parameter?

**Comment by BrennanConroy** [comment]
> do you mean to add one more delagate without `arguments` parameter?

No, just making the arguments parameter nullable.

**Comment by Marusyk** [comment]
Oh, I see, thanks. I'll try to do that

**Comment by iSazonov** [comment]
@stephentoub Since #38384 was merged the issue can be closed.

**Comment by stephentoub** [comment]
Thanks
