### ISSUE TITLE
DateTime.ToLocalTime offset calculation performance 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#38047]
Today I looked at some Npgsql traces in our app, which uses [timestamptz](https://www.postgresql.org/docs/9.1/datatype-datetime.html) (timestamp with timezone) columns for storing datetime instants. To stay close to PG behavior of automatic local timezone conversion npgsql receives these values as UTC from PG and internally maps them to the local timezone of the application.

Looking at traces of some common requests (this was a fairly beefy request) in our app I see `Npgsql.TypeHandlers.DateTimeHandlers.TimestampTzHandler` -- which has the least amount of invocations overall -- take the most time of all type handlers. 

In absolute time almost hitting 1ms for just 36 conversions  -- note this was a tracing, not sampling, profiling run -- this is a significant contributor for simpler requests.

The culprit as can be seen from traces below is almost entirely the offset calculation triggered by `DateTime.ToLocalTime`.

<img width="1177" alt="Screenshot 2020-06-17 at 19 16 32" src="https://user-images.githubusercontent.com/4218809/84933036-8a1e8500-b0d5-11ea-848e-37d4a801f0cb.png">

Looking at the implementation, one main thing that could be easily improved is a fast path for `ToLocalTime` calls which resolve a local timezone that equals Utc (which in most cases is expected to be the default on servers).

For other timezones I'm less sure, considering freshness for DST calculations, is there anything that can be improved regardless?

This is on macOS 10.14, sdk 3.1.300

/cc @roji

**Comment by Clockwork-Muse** [comment]
.... I know it would probably be a breaking change for them, but personally I'd want to complain to npgsql about converting to "local" time, at least globally.  "Local" time on a server, even if not set to UTC, is almost always irrelevant - it's going to be the timezone from an entity from some other table.  Local time might be relevant on a user-hosted client, but I would wish to convert that myself.

Note that postgresql doesn't really handle timezones, or even offsets, at anywhere close to the necessary level (not even an equivalent to SQL Server's `DateTimeOffset`).  Pretty much all RDBMSs are terrible at it, so this isn't really a mark against them.  As usual, you're far better off pulling all the data from the database and doing it application-side, preferably with the aid of NodaTime.

> For other timezones I'm less sure, considering freshness for DST calculations, is there anything that can be improved regardless?

DST calculation freshness due to rule _changes_ (as opposed to just DST occurring due to rules long in place) is a game you've already lost; the record is Haiti, who announced DST changes ~24 hours before it was to occur.  It took Windows multiple months to distribute a patch.  Assume that every time you read a future scheduled date from the database the scheduled local time+timezone id may no longer match the estimated UTC instant+offset.

**Comment by roji** [comment]
FWIW Npgsql is only doing what PostgreSQL itself is doing when you select a `timestamp with time zone`: it converts to your local time, based on the session timezone.

But this issue really isn't about that - if you'd like to discuss this further please open an issue on https://github.com/npgsql/npgsql/issues, let's keep this about the performance of DateTime.ToLocalTime.

**Comment by Clockwork-Muse** [comment]
@roji - Yes, I'm aware of that (although I don't really agree with the database doing it either, since that can cause strange effects for reporting).

Looking at the [relevant method](https://github.com/dotnet/runtime/blob/0a2f0e6da98a784601b37d19417b930a33b2c478/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs#L1688-L1732), nothing immediately jumps out as problematic.  Can you give us the full performance dump for everything below `ToLocalTime` (you didn't expand `GetUtcOffsetFromUtc` - you should be able to get some sort of text output, I think?).

**Comment by NinoFloris** [comment]
Full trace the type handler

<img width="1450" alt="Screenshot 2020-06-18 at 18 06 53" src="https://user-images.githubusercontent.com/4218809/85044896-8c90e580-b18e-11ea-8e8c-b6ef60b61c59.png">


<details>
<summary>and as text</summary>

```
  100%   Read  •  0.9 ms • 36 calls  •  Npgsql.TypeHandlers.DateTimeHandlers.TimestampTzHandler.Read(NpgsqlReadBuffer, Int32, FieldDescription)
    87.3%   ToLocalTime  •  0.8 ms • 36 calls  •  System.DateTime.ToLocalTime(Boolean)
      83.5%   GetUtcOffsetFromUtc  •  0.8 ms • 36 calls  •  System.TimeZoneInfo.GetUtcOffsetFromUtc(DateTime, TimeZoneInfo, out Boolean, out Boolean)
        50.9%   GetIsDaylightSavingsFromUtc  •  0.5 ms • 36 calls  •  System.TimeZoneInfo.GetIsDaylightSavingsFromUtc(DateTime, Int32, TimeSpan, AdjustmentRule, Nullable, out Boolean, TimeZoneInfo)
          29.5%   GetDaylightSavingsStartOffsetFromUtc  •  0.3 ms • 36 calls  •  System.TimeZoneInfo.GetDaylightSavingsStartOffsetFromUtc(TimeSpan, AdjustmentRule, Nullable)
            1.33%   GetPreviousAdjustmentRule  •  0.01 ms • 36 calls  •  System.TimeZoneInfo.GetPreviousAdjustmentRule(AdjustmentRule, Nullable)
            0.67%   Add  •  0.006 ms • 72 calls  •  System.TimeSpan.Add(TimeSpan)
          8.43%   GetDaylightTime  •  0.08 ms • 36 calls  •  System.TimeZoneInfo.GetDaylightTime(Int32, AdjustmentRule, Nullable)
            5.99%   ConvertToFromUtc  •  0.05 ms • 72 calls  •  System.TimeZoneInfo.ConvertToFromUtc(DateTime, TimeSpan, TimeSpan, Boolean)
              1.77%   Add  •  0.02 ms • 144 calls  •  System.TimeSpan.Add(TimeSpan)
              0.89%   DateTime..ctor  •  0.008 ms • 72 calls  •  System.DateTime..ctor(Int64)
            0.33%   GetPreviousAdjustmentRule  •  0.003 ms • 36 calls  •  System.TimeZoneInfo.GetPreviousAdjustmentRule(AdjustmentRule, Nullable)
          2.00%   GetDaylightSavingsEndOffsetFromUtc  •  0.02 ms • 36 calls  •  System.TimeZoneInfo.GetDaylightSavingsEndOffsetFromUtc(TimeSpan, AdjustmentRule)
            0.78%   Add  •  0.007 ms • 72 calls  •  System.TimeSpan.Add(TimeSpan)
          1.55%   op_Subtraction  •  0.01 ms • 108 calls  •  System.DateTime.op_Subtraction(DateTime, TimeSpan)
          1.11%   GetDatePart  •  0.01 ms • 72 calls  •  System.DateTime.GetDatePart(Int32)
          0.67%   IsStartDateMarkerForBeginningOfYear  •  0.006 ms • 36 calls  •  System.TimeZoneInfo+AdjustmentRule.IsStartDateMarkerForBeginningOfYear()
          0.44%   CheckIsDst  •  0.004 ms • 36 calls  •  System.TimeZoneInfo.CheckIsDst(DateTime, DateTime, DateTime, Boolean, AdjustmentRule)
          0.33%   IsEndDateMarkerForEndOfYear  •  0.003 ms • 36 calls  •  System.TimeZoneInfo+AdjustmentRule.IsEndDateMarkerForEndOfYear()
        22.7%   GetAdjustmentRuleForTime  •  0.2 ms • 36 calls  •  System.TimeZoneInfo.GetAdjustmentRuleForTime(DateTime, Boolean, out Nullable)
          17.0%   CompareAdjustmentRuleToDateTime  •  0.2 ms • 288 calls  •  System.TimeZoneInfo.CompareAdjustmentRuleToDateTime(AdjustmentRule, AdjustmentRule, DateTime, DateTime, Boolean)
            5.54%   get_Kind  •  0.05 ms • 504 calls  •  System.DateTime.get_Kind()
          1.11%   op_Addition  •  0.01 ms • 36 calls  •  System.DateTime.op_Addition(DateTime, TimeSpan)
          0.22%   get_Date  •  0.002 ms • 36 calls  •  System.DateTime.get_Date()
        1.55%   get_HasDaylightSaving  •  0.01 ms • 36 calls  •  System.TimeZoneInfo+AdjustmentRule.get_HasDaylightSaving()
        1.22%   Add  •  0.01 ms • 72 calls  •  System.TimeSpan.Add(TimeSpan)
        0.44%   op_Addition  •  0.004 ms • 36 calls  •  System.DateTime.op_Addition(DateTime, TimeSpan)
        0.33%   GetDatePart  •  0.003 ms • 36 calls  •  System.DateTime.GetDatePart(Int32)
      0.33%   DateTime..ctor  •  0.003 ms • 36 calls  •  System.DateTime..ctor(Int64, DateTimeKind, Boolean)
      0.33%   get_Kind  •  0.003 ms • 36 calls  •  System.DateTime.get_Kind()
    5.43%   ToDateTime  •  0.05 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime.ToDateTime()
      1.22%   get_Kind  •  0.01 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime.get_Kind()
      0.78%   DateTime..ctor  •  0.007 ms • 36 calls  •  System.DateTime..ctor(Int64, DateTimeKind)
      0.33%   get_Ticks  •  0.003 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime.get_Ticks()
      0.22%   get_IsFinite  •  0.002 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime.get_IsFinite()
    4.10%   ReadTimeStamp  •  0.04 ms • 36 calls  •  Npgsql.TypeHandlers.DateTimeHandlers.TimestampHandler.ReadTimeStamp(NpgsqlReadBuffer, Int32, FieldDescription)
      2.33%   NpgsqlDateTime..ctor  •  0.02 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime..ctor(InternalType, NpgsqlDate, TimeSpan)
        0.89%   get_IsFinite  •  0.008 ms • 36 calls  •  NpgsqlTypes.NpgsqlDate.get_IsFinite()
      0.44%   KindToInternalType  •  0.004 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime.KindToInternalType(DateTimeKind)
    0.44%   get_IsFinite  •  0.004 ms • 36 calls  •  NpgsqlTypes.NpgsqlDateTime.get_IsFinite()
```

</details>

**Comment by Clockwork-Muse** [comment]
... The fact that trace is calling `GetIsDaylightSavingsFromUtc` means it's picked up adjustment rules, which, if I'm reading the class correctly, means that you're not using UTC.

**Comment by NinoFloris** [comment]
I'll be closing this, can't repro it (at least not anymore)

**Comment by roji** [comment]
Also FYI for anyone stumbling upon this, Npgsql will be changing its default behavior in the upcoming 6.0 release to longer return convert to local timestamps (the idea is to never perform timezone conversions in the driver), see https://github.com/npgsql/npgsql/issues/3947.
