### ISSUE TITLE
Run mono perf interpreter tests on every PR?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#38041]
We had to disable the mono perf interpreter tests today: https://github.com/dotnet/runtime/commit/a5a97757e7c91b82c007858e6a32fcb86c5b307e. Do we actually need to run the mono perf interpreter tests on every PR? Should we instead only run them per  rolling build or scheduled?

cc @jashook @DrewScoggins @MattGal @akoeplinger @safern @naricc

**Comment by safern** [comment]
cc: @SamMonoRT

**Comment by SamMonoRT** [comment]
The Mono Interpreter is powering our WebAssembly scenario and we are trying to improve the performance here. We have changes being made in that code base and we want to be monitoring the results for any regressions (and improvements !). If we don't do it on every PR, we need a way to run the interpreter runs atleast once daily (as we had initially discussed with @Lxiamail team.

**Comment by DrewScoggins** [comment]
The performance runs that are triggered as part of a PR are purely for functional correctness. We do not gather any results from there as they are run on VMs and only ran for a single iteration. These exists to ensure that our tests are not broken by a check-in. The actual runs that we collect for the performance lab are done on an internal queue, backed by actual hardware. As of right now we have the CI jobs turned off for the interpreter as they take a very long time and it is unlikely that we will ever hit an issue that causes our perf tests to only fail on the interpreter, but we are still running the interpreter performance tests on the internal physical hardware backed queue as of today.

**Comment by ViktorHofer** [comment]
@DrewScoggins what's the status on this? Are we still running mono perf interpreter tests on PRs? Should we close this issue?

**Comment by SamMonoRT** [comment]
No, we aren't running it on all PRs. We can close this issues.
