### ISSUE TITLE
BitArray(Int32, bool) constructor can leave dirty bits causing RightShift() to later fail

### ISSUE THREAD

**Issue by scottdsanders** [dotnet/runtime#38059]
### Description

The BitArray(Int32, bool) constructor appears to leave dirty bits in the internal storage array. This breaks an assumption by (at least) RightShift(Int32) such that it can fail.

For Example:

BitArray ba = new BitArray(500, true);

will completely fill the internal array of 16 ints with 0xFFFFFFFF from the call m_array.AsSpan().Fill(-1). 

This causes RightShift() to fail:

BitArray ba = new BitArray(1000, true);
ba.RightShift(500);
for (int i = 0; i < 500; i++)
    Assert.IsTrue(ba[i] == (i < 500)); // will fail at 500 (500 is true)

### Configuration

.NET Core 3.0
Windows 10 1909
x64

(should not be specific to this configuration)

### Regression?

No

### Other information

By modifying the constructor as follows, the issue is resolved. It is also probably bad that RightShift() has this dependency. 

```
            if (defaultValue)
            {
                m_array.AsSpan().Fill(-1);

                Div64Rem(m_length, out int extraBits);
                if (extraBits > 0)
                {
                    m_array[^1] &= (long)((1UL << extraBits) - 1);
                }
            }
```

**Comment by scottdsanders** [comment]
@jeffhandley @eiriktsarpalis @layomia

**Comment by eiriktsarpalis** [comment]
I can reproduce this, it's clearly a product bug. It's also probably not a regression, this constructor seems to have always behaved that way and `RightShift` is a relatively recent addition to the type.
