### ISSUE TITLE
Why does DependencyModel fallback to .Net Framework desktop assemblies

### ISSUE THREAD

**Issue by smbecker** [dotnet/runtime#3806]
I was investigating an issue that was caused by how an internal project was resolving reference paths. It turned out to be an issue with when a developer has .Net Framework 3.5 installed locally and the fact that those [locations are considered as fallback](https://github.com/dotnet/core-setup/blob/18780678da576d8c629066f50af30159a8859b2f/src/managed/Microsoft.Extensions.DependencyModel/Resolution/ReferenceAssemblyPathResolver.cs#L94). This only caused issues with a project that targets .netcoreapp3.0. I am curious why those locations would be considered for fallback in a .Net Core application?

**Comment by eerhardt** [comment]
The reason it looks in .NET Framework 3.5 reference assemblies is mostly legacy reasons. ASP.NET was previously supported on .NET Framework. There is a big difference in our reference assemblies are installed between .NET Framework 3.5 and 4.0, so we needed to implement this "fallback" path to support both 3.5 and 4.0+.

Going forward, it probably makes less sense to keep supporting .NET Framework reference assemblies - especially by default. But removing it could be considered a breaking change, so unless we have a good reason to remove it, I think we should keep it.

However, this code path will only ever be used for assemblies that are marked `"referenceassembly"`. Can you show how you got `"referenceassembly"` libraries in your .deps.json file?

In `2.0`, we added the ability to be able to specify which resolvers you want to use. You can use this API to remove the `ReferenceAssemblyPathResolver` completely, if you don't want its functionality. See 

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/managed/Microsoft.Extensions.DependencyModel/CompilationLibrary.cs#L60-L66

You should be able to pass whichever resolvers you require. By default, the list used is:

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/managed/Microsoft.Extensions.DependencyModel/CompilationLibrary.cs#L46-L51

I'm going to close this out, as I believe the question is answered. But feel free to re-open if things aren't clear or you have more questions in this area.
