### ISSUE TITLE
Improve runtime uninstall behavior on Windows: avoid unprompted shutdown of apps

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3808]
## Steps to reproduce

Install 3.0-rc using the bundle installer (EXE). Run an FDE app that stays active. (`Console.ReadLine()`.) Upgrade to 3.0.

## Expected behavior

When the upgrade tries to uninstall the 3.0-rc runtime due to product band in-place upgrade behavior, it prompts whether you would like to attempt to shut down and restart the app, or if you'd like to wait until a reboot to complete the uninstall.

## Actual behavior

When the installer tries to uninstall the 3.0-rc runtime, the FDE app is shut down without a prompt.

(This behavior repros with FDD apps, however the upgrade *does* prompt for `dotnet.exe` in particular, which makes the shutdown more confusing.)

---

There may be a way to configure Restart Manager to handle this better. ([MSIRMSHUTDOWN](https://docs.microsoft.com/en-us/windows/win32/msi/msirmshutdown)?)

Workaround: install the MSIs or zips to avoid the old version uninstall.

If this repros for the ASP.NET Core and WindowsDesktop runtime installers, this may need to be fixed in all of them to make sure the overall scenario is sound.

**Comment by dleeapho** [comment]
Moving back to 5.0 because of customer feedback on urgency. /cc @preethikurup @nakarnam @StephenBonikowsky

**Comment by NikolaMilosavljevic** [comment]
We are not fixing .NET installers - proposed solutions for applications/services are being tracked in a separate document.
