### ISSUE TITLE
Runtime dependency resolution

### ISSUE THREAD

**Issue by andrius-lokotas** [dotnet/runtime#38080]
Hello.

We have a bit of "non standard" windows 10 environment. 
We use both DOTNET_ROOT and DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variables in global context that point to custom location on hard drive. 

There is self contained custom installation and update windows service that has blazor (self hosted server side) UI that manages both net core sdk (binary version) and client software versions update and installation. This service is also responsible setting the above mentioned environment variables via command Environment.SetEnvironmentVariable and EnvironmentVariableTarget.Machine context.

None of the custom folders are hinted under PATH.

All installation files are zip formatted and we use microsoft own System.io.Compression zip code to unpack them. All works fine if runtime / sdk is installed via official installation and is placed into dotnet default locations, however if there is no sdk/runtime installation and our custom update service will try to extract dotnet sdk zip file we will get exception

CoreCLR Version: 4.700.19.60701
.NET Core Version: 3.1.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException:
File name: 'System.IO.Compression.ZipFile, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Ironically the dll is present in the temporary folder that self contained service created once runtime unpacks executable, however resolution seems to fail. What is even more strange is that the rest of the blazor application is working just fine, however as soon as ZIP code is executed it breaks.

Any suggestions why is this happening ?

**Comment by swaroop-sridhar** [comment]
@andrius-lokotas are you running a single-file app or a normal (multi-file) self-contained app? 
`DOTNET_BUNDLE_EXTRACT_BASE_DIR` only applies to single-file apps.

I think you mean a single-file app. Are you sure it is self-contained single-file app? Can you please share how the app is published? What properties are set? 

By temporary directory, do you mean the directory where files are extracted from a single-file app? 
What is `DOTNET_BUNDLE_EXTRACT_BASE_DIR`  set to? Is it set within %TEMP%? 

Does this problem persist when using 3.1.4 SDK/runtime?

**Comment by andrius-lokotas** [comment]
In project file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <NeutralLanguage>et</NeutralLanguage>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>
```

CI build command

> "C:\Program Files\dotnet\dotnet.exe" publish ${bamboo.module.name}.sln -c Release /p:Version=1.0.1.${bamboo.buildNumber} --self-contained true

One more note, we also embedd wwwroot directory files, to do that in project file:
```
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>
```
and in startup configure:
```
            // This code is needed to embedd all static files into dll
            // we filter only files including a wwwroot name part
            var filePaths = new List<string>() { "wwwroot" };
            var allProviders = new List<IFileProvider>
            {
                // Keep the existing provider
                env.WebRootFileProvider,
                new ManifestEmbeddedFileProvider(typeof(Program).Assembly, "wwwroot")
            };

            // Replacing the previous WebRootFileProvider by our new composite one
            env.WebRootFileProvider = new CompositeFileProvider(allProviders);
```

**Comment by vitek-karas** [comment]
What is the callstack of the exception (not really interested in app's code so feel free to redact that, just curious what is triggering the assembly load - if it's a static dependency or a dynamic call like `Assembly.Load`)?

Can you try to run the app with environment variables `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=host_trace.txt`? This should produce `host_trace.txt` in the current directory. The file will contain information about the machine like local paths, names and so on, so only share it if that's OK. The bit I would look for in it is any mention of the failing `System.IO.Compression.ZipFile`, most notably if it ends up in `TRUSTED_PLATFORM_ASSEMBLY` list and what is the path of the file there (and if that is the expected path you think it should be loaded from).
