### ISSUE TITLE
Include needed runtime version and arch in error message when no runtime is installed

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#3811]
When the running a console app where the runtime is not installed, the host fails to find hostfxr and shows something like:
```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [D:\helloWorld\bin\Debug\netcoreapp3.0\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].
```
This contains a lot of information / potential fixes, but is not that readable or user-friendly.

When running a console app where a framework is missing, the host shows something like:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [D:\dotnet-test\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

With dotnet/core-setup#8509, a more user-friendly error message will be shown for GUI applications on Windows. We can look at doing the same for console apps tracing to stderr.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/runtime/pull/57150 and https://github.com/dotnet/runtime/pull/57089
