### ISSUE TITLE
[may be a bug] serilize Task object will let cpu 100%

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/runtime#38111]
# Issue Title

serilize Task object will let cpu 100%

# General

IDE: VS2019 Community
Version: .net core 3.1
System: both Win10 and Centos 7.5
Framework: ASP.Net Core

```csharp
public IActionResult test () {
    var content = Task.Run (...);// Task object
    return new OkObjectResult (new { result = true, reason = "", content });
}
```

if I use Newtonsoft.Json to serilize the object, it will throw a exception, but if I use the code, It will always lock with there and let CPU 100%

**Comment by scalablecory** [comment]
Not sure if it should go to JSON or ASP.NET. CC @Pilchie

**Comment by Pilchie** [comment]
Pretty sure it's just JSON, but maybe @pranavkm can confirm that it's not something ASP.NET is doing.

**Comment by pranavkm** [comment]
We don't do anything interesting during serialization that would cause this. That said, you're attempting to serialize a `Task` that returns a value i.e. a `Task<T>`, the serializer is going to synchronously block evaluating the `Result` property. I can't think of any good reason you would want to serialize a `Task` \ `ValueTask` instance, it most likely indicates a programming error. Perhaps the serializer could add a custom converter that throws anytime it encounters one of these? That way it throws by default and you get a useful error and users have a way to opt out if they relied on the serialized format.

**Comment by fawdlstty** [comment]
This is a logical bug, so I think it's better to throw an exception rather than get the CPU to 100%

**Comment by fawdlstty** [comment]
The serializer does not wait for Result, because the asynchronous method completes quickly, but the serializer stays blocked

**Comment by layomia** [comment]
We can add a converter factory to throw when one of these types is encountered, similar to the work done in https://github.com/dotnet/runtime/pull/34249.
