### ISSUE TITLE
Linq Sum<TimeSpan>()

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#38120]
Please add a Sum() that works with TimeSpan.

**Comment by nickorlow** [comment]
I'll see what I can do

**Comment by capra314cabra** [comment]
It should be easy to implement `Sum(IEnumerable<Nullable<TimeSpan>>)` soon.
However, we have to consider first whether we are going to create `Sum` overrides for anything which can be added and which also have no `Sum` overrides such as `System.Drawing.Point` or not.

**Comment by huoyaoyuan** [comment]
`TimeSpan` isn't common enough to have a specialized overload for it. It should be solved when type classese/shapes is a thing, and then `Sum` can support any types with `operator +`.

**Comment by eiriktsarpalis** [comment]
I would tend to agree, summation of TimeSpan is not common enough to justify such an addition. Ideally this should be solved at the language level, so we can expose methods that are generic w.r.t. types with monoidal structure. Given it is fairly trivial to implement this as an extension method, I am going to close this issue. /cc @adamsitnik

**Comment by AlgorithmsAreCool** [comment]
@TonyValenti 
You can also use the `Aggregate<T>(Func<T,T,T>)` linq method.

It is less clean, but more flexible.

```csharp
using System;
using System.Linq;

public class C {
    public static void Main(string[] args) {
        var items = new [] {
            1,
            2,
            3,
        };
        
        var times = new [] {
            TimeSpan.FromSeconds(1),
            TimeSpan.FromSeconds(2),
            TimeSpan.FromSeconds(3),
        };
        
        
        Console.WriteLine($"ItemSum = {items.Sum()}");
        Console.WriteLine($"ItemAgg = {items.Aggregate((a, b) => a + b)}");
        Console.WriteLine($"TimeAgg = {times.Aggregate((a, b) => a + b)}");
    }
}
```


[SharpLab Example](https://sharplab.io/#v2:EYLgJgpgtg9gzgWmAVwJYBswIEwAY8A0ALiAE7IB2APgALYCMAsAFA24AEN9AdADKoUAjgG4WLGgGZO2dgGF2AbxbsVnKVwBsnACzsAsgEMBACi64A2gF12B0gHM4ASkXLVbgG632qItDjsAXnYKCAB3disXZjcY1XoCV1i3bATopLcJVPSAX1E02MSYz1J2IlQoCH8gkPDIpXz09gAVcogAZQAHAwpuADFSGCg2iABjGAowOGN6RyzGlRaKzu6+gaHR8cnjbFnC9MX2rp7+weGxiamJXYa3XL3Ve5VHznoATmMAEgAiAElfIeQUECih8fm4bUBxkc2S+jjy6S472+f2gAEE7HZgQpQVA4Nx0XZSBA7AZfMZjAYCOxgM4AgA+GzsADU1OhsPhSURny+BwJWLKFTxBKJJLJFKpNMCDIMzNZMLhhWyLGyQA===)
