### ISSUE TITLE
[Wasm] CultureInfo isn't correctly constructed

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#38124]
```C#
var culture = new CultureInfo("fr-FR");
while (true)
{
    Console.WriteLine($"{culture.Name}: {culture.DisplayName}");
    if (culture == CultureInfo.InvariantCulture)
    {
        break;
    }
    culture = culture.Parent;
}
```

Output in .NET Core:

```
fr-FR: French (France)
fr: French
: Invariant Language (Invariant Country)
```

Output in WASM:

```
fr-FR: Invariant Language (Invariant Country)
 : Invariant Language (Invariant Country)
```
The important bit here is that the parent culture (`fr`) is missing. This affects resx file lookups.

**Comment by safern** [comment]
I think this is still using wasm globalization implementation in mono right? Not using ICU or Invariant implementation.

**Comment by pranavkm** [comment]
I'm not a 100% certain. Feel free to untag System.Globalization until they've had a chance to triage this.

**Comment by tarekgh** [comment]
This looks to me wasm is using the invariant globalization mode which forcing Invariant culture data for all created cultures.

**Comment by safern** [comment]
Right, so if we ran the same code with Invariant enabled on .NET5.0 we would get the same behavior as on WASM.

**Comment by marek-safar** [comment]
That's expected and was discussed on the syncs. We are forcing Invariant Mode for now.

**Comment by Berrysoft** [comment]
Is there any plan or roadmap to add localization back to WASM?

**Comment by safern** [comment]
@Berrysoft you can try installing the latest .NET daily build that enables ICU usage by default on wasm at the moment. Which brings it closer to a regular console app. Note that we only carry data for the locales listed here: https://developer.chrome.com/webstore/i18n?csw=1#localeTable

You can find the latest daily preview here
https://github.com/dotnet/installer/blob/master/README.md#installers-and-binaries

**Comment by steveisok** [comment]
@mdh1418 Can you see what wasm w/ ICU enabled produces?

**Comment by lewing** [comment]
The current output is
`
fr-FR: fr (FR)
fr: fr
: und
`

**Comment by pranavkm** [comment]
I think that's fine. The runtime resolves culture specific resources correctly which is pretty much all we care about. Closing.

**Comment by mdh1418** [comment]
Now building the wasm sample results in

Output:
```
fr-FR: fr (FR)
fr: fr
: und
```
