### ISSUE TITLE
[WASM] Invariant culture doesn't work

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#38126]
Blazor added a test to verify that `CultureInfo.InvariantCulture` works in WASM. This is failing since upgrading to .NET 5. 

```C#
// This test verifies that invariant cultue works correctly in WebAssembly environments. The test case is based on the discussions here: https://stackoverflow.com/a/20085219
var string1 = "Strasse";
var string2 = "Straße";

var ordinalComparison = string1.Equals(string2, StringComparison.Ordinal);
var invariantComparison = string1.Equals(string2, StringComparison.InvariantCulture);

Console.WriteLine(ordinalComparison + " " invariantComparison);
```

Expected: `False True`
Actual: `False False`

**Comment by tarekgh** [comment]
@pranavkm I would hold logging more issues till figuring out if the wasm enabling the invariant globalization mode or not. with this mode, you lose almost all globalization support.

**Comment by safern** [comment]
I set the milestone to 5.0 since it is related to WASM.

**Comment by steveisok** [comment]
Since ICU is going to be enabled for blazor, is this still an issue?

**Comment by safern** [comment]
I think we can close this now... also now in .NET 5.0, InvariantMode is the same for WASM and non-WASM, before it was the Mono Globalization implementation which differed.
