### ISSUE TITLE
Add a new `unmanaged` calling convention bit for use with function pointers

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#38133]
We need a new `unmanaged` calling convention bit for use with function pointers in .NET 5.

This bit will represent the "platform" default calling convention (essentially equivalent to `Winapi` for P/Invoke).

Based on the conversations, this would be `bit 9` in the calling kind encoding.

```CSharp
namespace System.Reflection.Metadata
{
    public enum SignatureCallingConvention : byte
    {
        // existing
        Default = 0x0,
        CDecl = 0x1,
        StdCall = 0x2,
        ThisCall = 0x3,
        FastCall = 0x4,

        // 0x5 - 0x8 are taken by other types of signatures (fields, properties, etc.)

        // new
        Unmanaged = 0x9,
    }
}
```

**Comment by tannergooding** [comment]
CC. @333fred, @davidwrighton, @AaronRobinsonMSFT, @jkotas

**Comment by AaronRobinsonMSFT** [comment]
Related https://github.com/dotnet/runtime/issues/34805

**Comment by jkotas** [comment]
This should include the new API proposal for `System.Reflection.Metadata`. I have edited the top post.

**Comment by AaronRobinsonMSFT** [comment]
Seems like we are going to also have to update [`System.Runtime.InteropServices.CallingConvention`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.callingconvention) to support the [`ILGenerator.EmitCalli()`](https://docs.microsoft.com/dotnet/api/system.reflection.emit.ilgenerator.emitcalli#System_Reflection_Emit_ILGenerator_EmitCalli_System_Reflection_Emit_OpCode_System_Runtime_InteropServices_CallingConvention_System_Type_System_Type___) scenario.

**Comment by AaronRobinsonMSFT** [comment]
I have updated the above proposal. We could also not support it since the API doesn't seem to have a place to add `modopt`s?

/cc @davidwrighton

**Comment by jkotas** [comment]
`enum CallingConvention` is used in other more common contexts like `DllImport` where this new value would be confusing.

The use of `enum CallingConvention` in the Reflection.Emit APIs is broken, e.g. `CallingConvention.WinApi` is mapped to StdCall [here](https://github.com/dotnet/runtime/blob/5c667210d0f41b8e0ba94eeee2c29eb3d07bb0f0/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/Emit/SignatureHelper.cs#L96). I think we should leave the use of this enum in Reflection.Emit alone and not try to fix it or improve it.

If we wanted to make this work with existing reflection APIs, I think it may be better to add a new `Unmanaged` value to `enum CallingConventions`. This enum can be  used in combination with `SignatureHelper` to produce signature with modopts and then emitted using `Emit(OpCode opcode, SignatureHelper signature)`.

**Comment by AaronRobinsonMSFT** [comment]
>The use of enum CallingConvention in the Reflection.Emit APIs is broken

That is what I was thinking as well. Perhaps it would be worth marking that API as `Obsolete`?

**Comment by davidwrighton** [comment]
I think we should hold off on adding new support to reflection emit for this in this release. We're very close to ship, and I'm not aware of any scenarios where we need calli support for this in the .NET 5 timeframe. Support in System.Reflection.Metadata is different though, as that is the api surface used by the compilers to generate code, we should fix that so that the Roslyn team doesn't need to maintain their own definition of the enum value.

**Comment by terrajobst** [comment]
* Technically, the actual calling convention is expressed as modopt on the return type.

```C#
namespace System.Reflection.Metadata
{
    public enum SignatureCallingConvention : byte
    {
        Unmanaged = 0x9
    }
}
```
