### ISSUE TITLE
Need help related to controlling TLS fragmentation of SslStream.

### ISSUE THREAD

**Issue by huiren-jiang** [dotnet/runtime#38141]
Hi,

I hope to know whether it is possible to control the TLS fragmentation behavior of SslStream.

I am aware of it should be transparent to upper layer. The reason why I ask here is because the implementation we talk to does not handle TLS fragmentation perfectly. SslStream will always fragment the leading bytes of our request and cut the header struct so the server will fail our request.

Thanks!

**Comment by davidsh** [comment]
>SslStream will always fragment the leading bytes of our request 

That is because SslStream has implemented mitigations for [BEAST](https://www.acunetix.com/blog/web-security-zone/what-is-beast-attack/) vulnerability.

>so the server will fail our request.

It's possible that your server is not updated or compliant with TLS RFC's.

**Comment by huiren-jiang** [comment]
> > SslStream will always fragment the leading bytes of our request
> 
> That is because SslStream has implemented mitigations for [BEAST](https://www.acunetix.com/blog/web-security-zone/what-is-beast-attack/) vulnerability.
> 
> > so the server will fail our request.
> 
> It's possible that your server is not updated or compliant with TLS RFC's.

Thanks for the information! Since the server is not ours and we cannot update, is there any workaround for SslStream?

**Comment by wfurt** [comment]
what platform are you running on and what version of .NET do you use?

**Comment by huiren-jiang** [comment]
Latest Windows 10 and dotnet framework 4.7.x/dotnet core 3.x.

**Comment by wfurt** [comment]
I think @davidsh is right. That is controlled by OS layers and I I'm not aware of anything you could at SslStream level. 
You can try to search through articles to see if there is any way how to control the behavior through registry keys.

**Comment by scalablecory** [comment]
Triage: Framework had some opt-outs relating to this; we might consider adding these to .NET Core.

**Comment by wfurt** [comment]
I don't think we have sufficient underlying API to support this. Closing for now as not actionable.
