### ISSUE TITLE
[WASM] PublishTrimmed causes TypeLoadException in HttpClientHandler

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#38154]
```
Could not load type of field 'System.Net.Http.HttpClientHandler:s_dangerousAcceptAnyServerCertificateValidator' due to: 
Could not resolve type with token 01000072 from typeref (expected class 'System.Security.Cryptography.X509Certificates.X509Certificate2' in assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
assembly:System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Security.Cryptography.X509Certificates.X509Certificate2 member:(null)
System.TypeLoadException: Could not load type of field 'System.Net.Http.HttpClientHandler:s_dangerousAcceptAnyServerCertificateValidator' 
due to: Could not resolve type with token 01000072 from typeref (expected class 'System.Security.Cryptography.X509Certificates.X509Certificate2' in assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') 
assembly:System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Security.Cryptography.X509Certificates.X509Certificate2 member:(null)
```

**Comment by lewing** [comment]
Probably related to https://github.com/dotnet/runtime/pull/37909

**Comment by pranavkm** [comment]
Looks like it. We're on 5.0.0-preview.7.20317.2 of the runtime which might have just missed picking up changes from this PR.

**Comment by marek-safar** [comment]
This is a quite weird error and we'll need to investigate. The commit Larry mentioned should be able to hide it but could you share verbose log before you bump to that version?

**Comment by pranavkm** [comment]
ILLink logs: https://gist.github.com/pranavkm/9a19669bcdc9baf5933e8f1d540099da

There isn't any additional information in the runtime stack trace.

**Comment by marek-safar** [comment]
Could you please include full verbose log and share the output folder

**Comment by lewing** [comment]
@pranavkm can you verify this is still failing with the latest runtime build and include the verbose log if so?

**Comment by pranavkm** [comment]
The linker issue is still open: https://github.com/mono/linker/issues/1298. We could close this as a dupe of the other. As noted in https://github.com/mono/linker/issues/1298#issuecomment-665176123, this only affects if the linker uses `copyused`. Blazor uses trimmode=link.

**Comment by lewing** [comment]
closing as a duplicate of https://github.com/mono/linker/issues/1298
