### ISSUE TITLE
System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedAfterConnect_ThrowsOperationCanceledException failures in OSX

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#38159]
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#694781](https://dev.azure.com/dnceng/public/_build/results?buildId=694781)|#38089|1|
|[#695034](https://dev.azure.com/dnceng/public/_build/results?buildId=695034)|#38109|1|
|[#695665](https://dev.azure.com/dnceng/public/_build/results?buildId=695665)|Rolling|1|
### Configurations
- net5.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open
- net5.0-OSX-Debug-x64-CoreCLR_release-OSX.1013.Amd64.Open
- net5.0-OSX-Release-x64-CoreCLR_release-OSX.1013.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#694781](https://dev.azure.com/dnceng/public/_build/results?buildId=694781)|#38089|[console.log](https://helix.dot.net/api/2019-06-17/jobs/5adbe18f-7339-44fa-8df3-66c96dc69baf/workitems/System.Net.WebSockets.Client.Tests/files/console.0ccba110.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/5adbe18f-7339-44fa-8df3-66c96dc69baf/workitems/System.Net.WebSockets.Client.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-38089-merge-5adbe18f733944fa8d/System.Net.WebSockets.Client.Tests/f62b60ad-f8c9-4aad-9c46-c4f718c604ea.log?sv=2019-02-02&se=2020-07-08T21%3A24%3A50Z&sr=c&sp=rl&sig=yox0O%2FIgrzRsvxBhG0WZ4BiYUm21kYH10J1E28LcAG8%3D)|
|[#695034](https://dev.azure.com/dnceng/public/_build/results?buildId=695034)|#38109|[console.log](https://helix.dot.net/api/2019-06-17/jobs/87ecaf01-689b-4c96-a6ef-b154fbc36391/workitems/System.Net.WebSockets.Client.Tests/files/console.8da442ab.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/87ecaf01-689b-4c96-a6ef-b154fbc36391/workitems/System.Net.WebSockets.Client.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-38109-merge-87ecaf01689b4c96a6/System.Net.WebSockets.Client.Tests/c520d4de-0e4b-4504-9009-e988b9e45d60.log?sv=2019-02-02&se=2020-07-08T23%3A27%3A15Z&sr=c&sp=rl&sig=qdzC7WNnNHN%2Bx0AgOoKn3RTml91N%2F3M6MRGEfq3C%2Fxs%3D)|
|[#695665](https://dev.azure.com/dnceng/public/_build/results?buildId=695665)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/873b6e83-2bf3-466b-925c-ce3ad8451318/workitems/System.Net.WebSockets.Client.Tests/files/console.b1b553d3.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/873b6e83-2bf3-466b-925c-ce3ad8451318/workitems/System.Net.WebSockets.Client.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-873b6e832bf3466b92/System.Net.WebSockets.Client.Tests/387cd77f-47b4-4d80-842b-8c60300d138f.log?sv=2019-02-02&se=2020-07-09T06%3A57%3A47Z&sr=c&sp=rl&sig=wlxQhE0a5PfWFenbnd9ih5QlHCk8mcK7l73pHLluOZM%3D)|

This is over the past 100 builds. 

```
System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedAfterConnect_ThrowsOperationCanceledException [FAIL]
      System.Net.Sockets.SocketException : Invalid argument
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(5173,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(4694,0): at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1871,0): at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(631,0): at System.Net.Sockets.Socket.set_NoDelay(Boolean value)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(97,0): at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(130,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(83,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(67,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.WebSockets.Client/tests/ConnectTest.cs(264,0): at System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedAfterConnect_ThrowsOperationCanceledException()
        --- End of stack trace from previous location ---
```

cc: @dotnet/ncl @stephentoub

**Comment by wfurt** [comment]
interesting
```
 System.Net.Sockets.SocketException : Invalid argument
```
https://github.com/envoyproxy/envoy/issues/1446 suggests that we can get that if peer shutdown their side. We have seen something similar with getpeername() in Socket from  fd code. Maybe loopback should just eat that exception. Perhaps NoDelay should be best effort.

**Comment by ericstj** [comment]
Same test just failed for me: 
https://dev.azure.com/dnceng/public/_build/results?buildId=725147&view=ms.vss-test-web.build-test-results-tab&runId=22479114&resultId=126814&paneView=debug

```
    System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedAfterConnect_ThrowsOperationCanceledException [FAIL]
      System.IO.IOException : The operation is not allowed on non-connected sockets.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs(57,0): at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs(32,0): at System.Net.Sockets.NetworkStream..ctor(Socket socket, Boolean ownsSocket)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(103,0): at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(134,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(82,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(110,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(82,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.WebSockets.Client/tests/ConnectTest.cs(263,0): at System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedAfterConnect_ThrowsOperationCanceledException()
        --- End of stack trace from previous location ---
```

**Comment by wfurt** [comment]
This is interesting. The socket should be in connected state once Accept is finished. Unless explicit Disconnect or Dispose() is called. 
Duration 0:00:00.497. Since the test really tests aborting connection, perhaps we can wrap the server in try/catch and ignore all errors.

**Comment by jkotas** [comment]
Hit in #41234
