### ISSUE TITLE
Vector.IsHardwareAccelerated result differs when called directly and called via reflection

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#38162]
```C#
using System;
using System.Reflection;
using System.Numerics;

class X
{
    public static int Main()
    {
        bool hw1 = Vector.IsHardwareAccelerated;

        Assembly spc = typeof(object).Assembly;
        Type vecType = spc.GetType("System.Numerics.Vector");
        MethodInfo method = vecType.GetMethod("get_IsHardwareAccelerated");
        bool hw2 = (bool) method.Invoke(null, null);

        Console.WriteLine($"Direct call to Vector.IsHardwareAccelerated returns {hw1}");
        Console.WriteLine($"Reflection call to Vector.IsHardwareAccelerated returns {hw2}");

        return (hw1 == hw2 ? 100 : -1);
    }
}
```
results in
```
Direct call to Vector.IsHardwareAccelerated returns True
Reflection call to Vector.IsHardwareAccelerated returns False
```
Seems like we're not recognizing this as an intrinsic when it is jitted on its own.

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib @tannergooding

**Comment by AndyAyersMS** [comment]
Saw this when looking at PMI results, where we force this method to be jitted.

**Comment by tannergooding** [comment]
CC. @CarolEidt 

This has always been like this as the methods aren't recursive (and we didn't actually add the `mustExpand` recursion support until HWIntrinsics in 3.0).

It shouldn't be particularly hard to fix, however.

**Comment by tannergooding** [comment]
I have the fix for this done locally however since `IsHardwareAccelerated` lives in `Vector` (rather than `Vector<T>`), it is included in R2R.

I though this just needed to be `fTreatAsRegularMethodCall = TRUE` in zapinfo, but then it isn't recognized as intrinsic at runtime and so it fails if R2R is enabled (the call ends up being recursive and not recognized as an intrinsic).

**Comment by tannergooding** [comment]
Moving this to future for the time being as the existing behavior goes back to .NET Framework and so I don't think it is particularly critical that we get it fixed for .NET 5.

I think I would need input from @davidwrighton or @jkotas as to what is missing for R2R to start working correctly with `IsHardwareAccelerated` being recursive.
As best as I can tell, there isn't any difference between it and the `IsSupported` checks in terms of attribution or handling, but I'm likely missing a check somewhere.

**Comment by tannergooding** [comment]
The changes I had prepped are here, for reference: https://github.com/tannergooding/runtime/commit/b6b555faf46b9860887edb6631eee7d52d1e2e0d

**Comment by jkotas** [comment]
One problem that I can see in your delta is that the mustExpand expansion will kick in only for `FEATURE_HW_INTRINSICS` and so it will not work on ARM. I think it needs to be unconditional outside `FEATURE_HW_INTRINSICS` ifdef like the `NI_IsSupported_True` / `NI_IsSupported_False` for regular hardware intrinsics.

Also, you may need a matching change in Mono.

The zapper side of your delta looks fine.

**Comment by tannergooding** [comment]
Moving to 8.0.0. This is in PR but not high priority and is dependent on someone from @dotnet/crossgen-contrib following up on the potential issue with the ISA flags
