### ISSUE TITLE
Build should check up front for Python and CMake

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#38169]
I ran 'build.cmd' on Windows without Python and CMake. It ran for several minutes (mostly restoring projects it looked like) before a command failed because 'py' could not be found, then it continued anyway and noted 'cmake' was not installed, then again continued anyway. 

To make it easier for new contributors to get started successfully, 'build.cmd' should immediately check for prerequisites (long paths, Python, CMake at least), and fail if they are not present, providing a link to the prerequisites doc. It should do this before building anything.

```
... lots of text ...
  Restored C:\git\runtime\src\coreclr\src\tools\dotnet-pgo\dotnet-pgo.csproj (in 1.07 min).
C:\git\runtime\eng\python.targets(8,5): error MSB3073: The command "py -3 -c "import sys; sys.stdout.write(sys.executable)" 2> nul || python3 -c "import sys; sys.stdout.write(sys.executable)" 2> nul || python -c "import sys; sys.stdout.write(sys.executable)" 2> nul" exited with code 9009. [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
  BUILD: Starting Build at 13:27:51.32
  BUILD: Detected Visual Studio 16.0 developer command prompt environment
          1 file(s) copied.
          1 file(s) copied.
  BUILD: Commencing CoreCLR product build
  BUILD: Checking prerequisites
  CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from https://cmake.org/download/ and ensure it is on your path.
  CROSSGEN-CORELIB: Starting Build at 13:28:02.29
  CROSSGEN-CORELIB: Detected Visual Studio 16.0 developer command prompt environment
```

**Comment by trylek** [comment]
The documentation issue https://github.com/dotnet/runtime/issues/38203 refers to the same underlying problem - missing prerequisites identified in the middle of build.

**Comment by jashook** [comment]
This has been fixed by https://github.com/dotnet/runtime/pull/39481
