### ISSUE TITLE
Fix official build race condition: managed library test projects vs. managed library signing

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3817]
In the official build, the Microsoft.NET.HostModel test project tries to use Microsoft.NET.HostModel.dll, but the build is also trying to sign it. If signing tries to replace the file with the signed file at the same time as tests try to use it, the build breaks. Same for the other managed libs built in Core-Setup.

To fix this, managed lib test projects should wait for binary signing to complete before going forward.

This causes build flakiness, however I've only seen it twice and the code has been this way for months.
* https://github.com/dotnet/core-setup/pull/8621#issuecomment-544700915
* https://dev.azure.com/dnceng/internal/_build/results?buildId=392170&view=results (first iteration, I accidentally retried it.)

Consider performance implications of this extra wait.

**Comment by NikolaMilosavljevic** [comment]
No known fixes merged in this area. Potentially obviated by upcoming signing work in Arcade.
