### ISSUE TITLE
Error unable to build console application when inside Live Share session (I'm not the host)

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/runtime#38170]
### Description

I'm getting an error explained below when the target first creates a build of the project. After that any future builds do not prompt any error, nor any application. (Console application)

### Configuration

Running on .NET Core 3.1, Windows 10, x64.

The error message I received:

```
One or more errors occurred.
Services not available:
DebugSessionHostService-2953e364-bb5b-4718-b517-f06d6c4f3751
```

Latest VS 2019 Enterprise Preview

**Comment by tommcdon** [comment]
Thank you for reporting the Visual Studio Live Share issue.  This looks like an issue Visual Studio and not in .NET core.  Please open a Visual Studio feedback ticket to [report ](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) the problem, and thank you for providing feedback for Visual Studio preview builds!
