### ISSUE TITLE
dumps are no longer debuggable

### ISSUE THREAD

**Issue by weltkante** [dotnet/runtime#38174]
### Description

Since about a week dumps taken on dotnet.exe from nightly builds are no longer debuggable in current VS preview. You get an error "`mscordbi.dll` contains a missing or invalid digital signature" when you try managed or mixed mode debugging.

This causes problems investigating WinForms memory corruption issues because we can no longer inspect dumps taken on CI machines.

### Configuration

observed in
- `5.0.20.31102` (dump from WinForms CI, about a week ago)
- `5.0.20.31702` (dump from WinForms CI)
- `5.0.20.31802` (dump taken from task manager locally today, shared [here](https://1drv.ms/u/s!AuW3VU_s-jxTgeZzDZtqE-g0fCDDdw?e=1E1jky) if you need to take a look)

### Regression

yes (investigating earlier dumps works fine, for example from `5.0.20.30808`)

### Other information

both dumps taken by the OS on crashes, and dumps taken from task manager seem to be affected

**Comment by hypeartist** [comment]
Could [https://github.com/dotnet/runtime/issues/38105](https://github.com/dotnet/runtime/issues/38105) also be related?

**Comment by weltkante** [comment]
Probably unrelated - building, execution and live debugging works - only debugging crash dumps is broken.

**Comment by hoyosjs** [comment]
Let me take a look at the dump. But no, signing issues would not affect things outside Watson collection scenarios. There was a recent regression around bugs in the DAC around the `AppDomain` that Mike fixed. I'm looking at the shared dump.

**Comment by hoyosjs** [comment]
The problem is this is not signed at all... and the VS debugger doesn't trust unsigned downloaded PEs from the server it looks like. there was an MSBuild bug last week that caused signing issues. However, this raises some concerns with OOB signing. I'll investigate both.

**Comment by hoyosjs** [comment]
@weltkante looks like the latest update to WinForms is properly signed. Those dumps should open correctly in VS.

**Comment by RussKie** [comment]
Thank you. Now all we need is wait for another test crash...

**Comment by weltkante** [comment]
Can confirm local dumps are already working again, would expect any CI dumps taken today work as well.
