### ISSUE TITLE
Cross platform inconsistency

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/runtime#3818]
_From @a20081860 on Monday, October 28, 2019 3:48:59 PM_

Hellow
"Microsoft.Extensions.DependencyModel.dll" Cross platform issues exist.

int num = DependencyContext.Default.CompileLibraries.Count     ;
num  in   Windows                   value is not 0  .
num  in   Linux（centos7）      value is 0
Microsoft.Extensions.DependencyModel.dll  version  2.1.0   and  3.0.0

What's the reason

_Copied from original issue: aspnet/AspNetCore#16603_

**Comment by eerhardt** [comment]
Closing as I believe the question has been answered.
