### ISSUE TITLE
Find a way to enable GS cookie on OSX in a singlefile deployment scenario.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#38184]
The current way of changing protection levels on a section seems to not work as expected in a singlefile (superhost) scenario, so it was disabled.

We need to find a way around this and enable GS cookine as a separate change. There must be a way.

Search for:
`#if defined(TARGET_OSX) && defined(CORECLR_EMBEDDED)`

**Comment by VSadov** [comment]
Releated: https://github.com/dotnet/runtime/pull/36847

**Comment by am11** [comment]
This was fixed by #39143. (github keyword parser apparently fails when there is no space between `Fixes:` and issue number)
