### ISSUE TITLE
dotnet implementation of AES decryption is slower than native call to bcrypt

### ISSUE THREAD

**Issue by vsevolodp** [dotnet/runtime#38183]
### Description

I've compared 3 different implementations of AES 128 decrypt as a simple benchmark project.

| Method | Time | Ratio |
|-|-|-|
| DecryptAesDotNetTransform | 5.76 µs | 1.00 baseline |
| DecryptAesBCrypt | 4.35 µs | 0.76 |
| DecryptAesDotNetStream | 9.32 µs | 1.62 |

You can find implementation in https://github.com/vsevolodp/dotnet-aes-benchmark/blob/master/benchmark_simple/Program.cs

To me this looks like significant performance issue.

In other project in my repository I've compared dotnet core 3.1 to 5.0 preview and this perf issue is same on .net 5.0.

Also it is much slower than OpenSSL implementation.

## Numbers from detailed benchmark project https://github.com/vsevolodp/dotnet-aes-benchmark/tree/master/benchmark
AesDecryptDotNet128 is same implementation as DecryptAesDotNetStream  above.

AesDecryptDotNet128Type2 is same implementation as DecryptAesDotNetTransform above.

### Windows Host
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.329 (2004/?/20H1)
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.4.20258.7
  [Host]        : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  .NET Core 3.1 : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.0 (CoreCLR 5.0.20.25106, CoreFX 5.0.20.25106), X64 RyuJIT
```
|                   Method |       Runtime |     Mean |     Error |    StdDev | Ratio |
|------------------------- |-------------- |---------:|----------:|----------:|------:|
|      AesDecryptDotNet128 | .NET Core 3.1 | 9.925 us | 0.1985 us | 0.4906 us |  1.82 |
| AesDecryptDotNet128Type2 | .NET Core 3.1 | 6.014 us | 0.1185 us | 0.1541 us |  1.03 |
|   AesDecryptBCryptWin128 | .NET Core 3.1 | 4.499 us | 0.0521 us | 0.0462 us |  0.78 |
|     AesDecryptOpenSsl128 | .NET Core 3.1 | 4.463 us | 0.0708 us | 0.0591 us |  0.77 |
|      AesDecryptDotNet128 | .NET Core 5.0 | 9.467 us | 0.0692 us | 0.0613 us |  1.63 |
| AesDecryptDotNet128Type2 | .NET Core 5.0 | 5.804 us | 0.0465 us | 0.0412 us |  1.00 baseline |
|   AesDecryptBCryptWin128 | .NET Core 5.0 | 4.442 us | 0.0352 us | 0.0329 us |  0.77 |
|     AesDecryptOpenSsl128 | .NET Core 5.0 | 4.138 us | 0.0324 us | 0.0271 us |  0.71 |

### WSL2 (Ubuntu 18.04) on Windows Host
```
BenchmarkDotNet=v0.12.1, OS=ubuntu 18.04
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.5.20279.10
  [Host]        : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
  .NET Core 3.1 : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.0 (CoreCLR 5.0.20.27801, CoreFX 5.0.20.27801), X64 RyuJIT
```

|                   Method |       Runtime |     Mean |     Error |    StdDev | Ratio |
|------------------------- |-------------- |---------:|----------:|----------:|------:|
|      AesDecryptDotNet128 | .NET Core 3.1 | 9.572 us | 0.1426 us | 0.1585 us | 1.699 |
| AesDecryptDotNet128Type2 | .NET Core 3.1 | 5.336 us | 0.1040 us | 0.1239 us | 0.946 |
|     AesDecryptOpenSsl128 | .NET Core 3.1 | 3.746 us | 0.0644 us | 0.0602 us | 0.669 |
|      AesDecryptDotNet128 | .NET Core 5.0 | 9.922 us | 0.1156 us | 0.1025 us | 1.771 |
| AesDecryptDotNet128Type2 | .NET Core 5.0 | 5.577 us | 0.1040 us | 0.1900 us | 1.000 baseline |
|     AesDecryptOpenSsl128 | .NET Core 5.0 | 3.690 us | 0.0441 us | 0.0368 us | 0.655 |

### Regression?
No

**Comment by vcsjones** [comment]
This will likely improve with some work that I am doing in #2406, how much is hard to say. I'll post some benchmark numbers as soon as I am able to.

I don't think the existing APIs can be as fast as straight calls to CNG, but they should improve. My hope is the new APIs in the linked issue can be closer, though that remains to be proven.

**Comment by vsevolodp** [comment]
> This will likely improve with some work that I am doing in #2406, how much is hard to say. I'll post some benchmark numbers as soon as I am able to.
> 
> I don't think the existing APIs can be as fast as straight calls to CNG, but they should improve. My hope is the new APIs in the linked issue can be closer, though that remains to be proven.

I remeasured implementation with your change. It is almost as fast as BCrypt PInvokes or OpenSSL on Windows.

I'm closing this issue.

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.388 (2004/?/20H1)
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-rc.1.20407.13
  [Host]        : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
  .NET Core 3.1 : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.0 (CoreCLR **5.0.20.40416**, CoreFX 5.0.20.40416), X64 RyuJIT


|                   Method |           Job |       Runtime |      Mean |     Error |    StdDev | Ratio |
|------------------------- |-------------- |-------------- |----------:|----------:|----------:|------:|
|      AesDecryptDotNet128 | .NET Core 3.1 | .NET Core 3.1 | 11.656 us | 0.4262 us | 1.2229 us |  2.42 |
| AesDecryptDotNet128Type2 | .NET Core 3.1 | .NET Core 3.1 |  7.425 us | 0.2878 us | 0.8487 us |  1.85 |
|   AesDecryptBCryptWin128 | .NET Core 3.1 | .NET Core 3.1 |  4.825 us | 0.0940 us | 0.1464 us |  1.01 |
|     AesDecryptOpenSsl128 | .NET Core 3.1 | .NET Core 3.1 |  4.472 us | 0.0884 us | 0.1525 us |  0.95 |
|      AesDecryptDotNet128 | .NET Core 5.0 | .NET Core 5.0 | 10.107 us | 0.2008 us | 0.3300 us |  2.11 |
| AesDecryptDotNet128Type2 | .NET Core 5.0 | .NET Core 5.0 |  4.746 us | 0.0929 us | 0.0776 us |  1.00 baseline |
|   AesDecryptBCryptWin128 | .NET Core 5.0 | .NET Core 5.0 |  4.856 us | 0.0959 us | 0.1848 us |  **1.05** |
|     AesDecryptOpenSsl128 | .NET Core 5.0 | .NET Core 5.0 |  4.466 us | 0.0886 us | 0.1183 us |  **0.94** |
