### ISSUE TITLE
Add Valve Encoding Rules to System.Formats.Asn1

### ISSUE THREAD

**Issue by bitcynth** [dotnet/runtime#38193]
## Background and Motivation

The CA/Meme Forum has requested dotnet to implement Valve Encoding Rules for System.Formats.Asn1.

## Alternative Designs

No, it is perfect

## Risks

It might make @vcsjones cry.

Also blame @ghuntley for suggesting that I file this issue.

**Comment by ghuntley** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by tarekgh** [comment]
@bitcynth this doesn't look a runtime issue to be opened here. I am closing it. feel free with more clarification if you think otherwise.
