### ISSUE TITLE
Guard against partial cleanup of extracted files issue is happening again.

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#38194]
### Description

Issue 3778 happening in .NET Core 3.1.4 (https://github.com/dotnet/runtime/issues/3778)

C:\BoincSpy\bin>BoincSpy.MQRabbit.Receiver.exe
Error:
  An assembly specified in the application dependencies manifest (BoincSpy.MQRabbit.Receiver.deps.json) was not found:
    package: 'BoincSpy.BoincRPC', version: '1.0.0.0'
    path: 'BoincSpy.BoincRPC.dll'

I have checked %Temp%\.net\BoincSpy.MQRabbitReceiver\randomdirectoryName\ and BoincSPY.BoincRPC.dll along with 4 other files that are supposed to be there are not there.

### Configuration
dotnet --info

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Window version.
Microsoft Windows [Version 10.0.19041.329]

**Comment by swaroop-sridhar** [comment]
@speed2048  was the `BoincSpy.MQRabbit.Receiver` app published using .net core 3.1.4 SDK? 
Installing the 3.1.4 SDK is not sufficient, the app needs to be built with the SDK. 
Can you please confirm this? Thanks.

**Comment by speed2048** [comment]
Hi Swaroop,

That was the case, I did not update that application and publish using the .net core 3.1.4 SDK. My assumption was wrong about runtime vs sdk. From now on I will not rely on just having the runtime installed I have to rebuild the app against the .sdk.

Thank you,
Bob

**Comment by swaroop-sridhar** [comment]
Thanks for the clarification @speed2048
