### ISSUE TITLE
Failed to determine location for extracting embedded files

### ISSUE THREAD

**Issue by genifycom** [dotnet/runtime#3821]
Using single publish file with DotNet 3.0.100 under Windows 10.

Installed machines sometime run under regular command prompt but sometimes we get:

Failure processing application bundle.
Failed to determine location for extracting embedded files
A fatal error was encountered. Could not extract contents of the bundle

In this case, we have to run an Administrative command prompt.

Is this expected behavior or something else? How to debug this?

**Comment by agocke** [comment]
Closing this out until we can get a log or repro
