### ISSUE TITLE
Stale version badges in README.md

### ISSUE THREAD

**Issue by rokonec** [dotnet/runtime#3822]
Improper cache-control in generated badges caused browsers caching svg badges for a year.

It is, therefore, recommend to modify related README.md content by simple find & replace from: _version_badge.svg to _version_badge.svg?no-cache

This will trigger github to compute and use different/new Camo proxy URL as explained [here](https://github.com/dotnet/arcade/issues/3948).

**Comment by afroze9** [comment]
I can take care of this.
