### ISSUE TITLE
Fix framework pack NuGet package licenseUrl

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3823]
For example these packages link to the license via a "floating" Core-Setup GitHub repo URL:
[Microsoft.NETCore.App 2.1.13](https://www.nuget.org/packages/Microsoft.NETCore.App/2.1.13)
[Microsoft.NETCore.App.Ref 3.0.0](https://www.nuget.org/packages/Microsoft.NETCore.App.Ref/3.0.0)
[Microsoft.NETCore.App.Ref 3.1.0-preview1.19506.1](https://www.nuget.org/packages/Microsoft.NETCore.App.Ref/3.1.0-preview1.19506.1)
They link to https://github.com/dotnet/core-setup/blob/master/LICENSE.TXT based on `licenseUrl` in the nuspec.

This is awkward for repo consolidation (we have to create a probably confusing `master` tag to avoid breaking the link, rather than only having the `master-archive` tag). It's also very bad practice. NuGet packages should contain their license.

Mitigation: the NuGet packages *do* contain `LICENSE.TXT`, but the NuGet Gallery (and probably Visual Studio?) show `licenseUrl`, so the user would have to dig in their NuGet cache or extract the nupkg to find `LICENSE.TXT`.

Note that the managed library packages like [Microsoft.DotNet.PlatformAbstractions 3.0.0](https://www.nuget.org/packages/Microsoft.DotNet.PlatformAbstractions/3.0.0) aren't affected because they are packed using different packaging tooling.

The `pkgproj` packaging tooling should support what we need to do here, but something in Core-Setup is not right or interferes. (https://github.com/dotnet/arcade/pull/2313)

I believe we should definitely fix this for 3.1, and consider porting to 3.0.

/cc @MichaelSimons @dleeapho @leecow @ericstj

**Comment by KalleOlaviNiemitalo** [comment]
At [System.Memory 4.5.4](https://www.nuget.org/packages/System.Memory/4.5.4) (the latest version) in NuGet Gallery, the [License Info](https://github.com/dotnet/corefx/blob/master/LICENSE.TXT) link is dead because of repository consolidation. Is that covered by this issue or should I file a separate one? I'm not sure because the link points to the corefx repository rather than core-setup.

**Comment by dagood** [comment]
We fixed the old license link just now. This works as of writing: https://github.com/dotnet/corefx/blob/master/LICENSE.TXT. Thanks again for pointing it out!

(Note for future viewers: the main core-setup issue tracked by this thread is still open--we should switch away from the old URLs where we can.)

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic can you check if this still repros?

**Comment by NikolaMilosavljevic** [comment]
Checked the latest Microsoft.NETCore.App.Ref package. License info is correct:

`    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>`

Closing.
