### ISSUE TITLE
CG2: m_alignpad == 0 in readytorun/crossboundarylayout/crossboundarytest (Ubuntu x64)

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#38239]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=698082&view=ms.vss-test-web.build-test-results-tab&runId=21631922&resultId=108010&paneView=attachments

Platform:

Linux x64 (Ubuntu 18.04)

Item log:

<pre>
irm: cannot remove '/home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.dll.rsp': No such file or directory

Assert failure(PID 7669 [0x00001df5], Thread: 7669 [0x1df5]): m_alignpad == 0
    File: /__w/1/s/src/coreclr/src/vm/syncblk.cpp Line: 2967
    Image: /home/helixbot/work/C40809FE/p/corerun

/home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.sh: line 317:  7669 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/Reports/readytorun.crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Response file: /home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.dll.rsp
--inputbubble
/home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/IL/crossboundarytest.dll
-r:/home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/IL/*.dll
-o:/home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.dll
-r:/home/helixbot/work/C40809FE/p/System.*.dll
-r:/home/helixbot/work/C40809FE/p/Microsoft.*.dll
-r:/home/helixbot/work/C40809FE/p/mscorlib.dll
--targetarch:x64
-O
Running CrossGen2:  dotnet /home/helixbot/work/C40809FE/p/crossgen2/crossgen2.dll @/home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.dll.rsp 
Emitting R2R PE file: /home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.dll
in ReleaseLock
/home/helixbot/work/C40809FE/p/corerun crossboundarytest.dll ''
Writing minidump to file /home/helixbot/dotnetbuild/dumps/coredump.7669.dmp
Written 52629504 bytes (12849 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/C40809FE/p
> /home/helixbot/work/C40809FE/w/A0C208F8/e/readytorun/crossboundarylayout/crossboundarytest/crossboundarytest/crossboundarytest.sh
</pre>

**Comment by janvorli** [comment]
I remember hitting this issue with crossgen2 when I was fixing the initial bugs last year. The cases I've seen were caused by object layout disagreement between crossgen2 and runtime. CG2 generated code was writing behind the end of an object (from the runtime point of view) and overwriting the m_alignpad field in the syncblk of the next object on the heap.

**Comment by janvorli** [comment]
Or maybe it was with the large version bubble work in CG1, I'm not sure.

**Comment by davidwrighton** [comment]
Sigh. Well, this is exactly the sort of thing that this test is supposed to find. This is some sort of field layout disagreement between the runtime and compiler. I keep meaning to write some sort of stress mode that allows the runtime to flag disagreements in an easier fashion, but fortunately this test is generally simple enough that simple inspection of code near the failure point will find the fault. If this was found in our automated testing, it probably indicates that there are more significant problems, and effort should be made to take that horrible script I wrote up for running these tests on Windows and run them on Linux (as well as consider writing a proper stress mode to chase down issues.)

**Comment by davidwrighton** [comment]
The issue here is that we were compiling the wrong set of binaries with the wrong set of switches. I've prepared a PR which addresses these issues, and the test passes on Linux for me now. (The reason the test passed on Windows was an issue in the crossgen2 scripting which didn't copy all of the appropriate dlls to the right location.)
