### ISSUE TITLE
[DI] Is there a way to override IServiceScopeFactory in the native ServiceProvider?

### ISSUE THREAD

**Issue by dazinator** [dotnet/runtime#38240]
I'd like to be able to intercept whenever a DI scope is created so I can keep track of them.
I saw that `IServiceScopeFactory` is resolved from the container in order to create a new scope, so I thought brilliant, if I can decorate the scope factory by overriding that registration, I can wrap any new scopes that are returned (irrespective of underlying container used) with some additional functionality - also counting / keeping track of them in the process.

However is seems that registering an `IServiceScopeFactory` does nothing - as this registration seems hard baked into the container itself as some `Callsite` stuff that I find hard to understand on first glances.

``` csharp
            Host.CreateDefaultBuilder(args)
            .ConfigureServices((a) =>
            {
                a.AddSingleton<IHost, TestingHost>();
                a.AddSingleton<IApplicationBuilderFactory, TestApplicationBuilderFactory>();
                a.AddSingleton<IServiceScopeFactory>(sp =>
                {
                     // not invoked
                    var factory = new TestScopeFactory();
                    return factory;
                });
            })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.ConfigureServices((a) =>
                    {
                        a.AddSingleton<IServiceScopeFactory>(sp =>
                        {
                              // not invoked
                            var factory = new TestScopeFactory();
                            return factory;
                        });
                    });           
                })
            .UseServiceProviderFactory(new TestServiceProviderFactory());

```

I have tried all of the extension points above with no joy.

Is there a way I can achieve this with the native service provider?

**Comment by akovac35** [comment]
I have the same issue - registering a custom IServiceProviderFactory has no effect in a Blazor application.

**Comment by davidfowl** [comment]
Closing this as it isn't possible or desireable.

**Comment by dazinator** [comment]
The underlying use case that led to this is: I'd like to not dispose of an IServiceProvider if has DI scopes in use as doing so would break code running elsewhere with those DI scopes, through disposing of its singletons. I know this is not currently supported or considered to be valuable to most simple applications. I've adopted a tweaked version of MS DI to enable me to achieve this so I do have a workaround. I just thought if a Disposable object is able to break other threads indirectly, by disposing of it, it seems valuable to me to have some method of disposing of it in a "safe" manner - perhaps baked into the api - even if most simple apps won't dispose (or create) any seperate IServiceProvider's, some more complex ones do see this as a desirable thing to do - I.e rather than one big container that is built on startup and never rebuilt, having additional purpose built containers for different parts of the system, that can be disposed of and rebuilt in isolation to the root container,  can help to split a large modular system up and allow different parts of the system to be reconfigured at runtime without stopping and starting the whole application.

**Comment by davidfowl** [comment]
Forking the container (which I think you already do for other reasons) is a better idea. This isn't extensibility that we want to provide for what i would deem not a common scenario
