### ISSUE TITLE
.net core, can't set this legacyUnhandledExceptionPolicy?

### ISSUE THREAD

**Issue by ourplan9000** [dotnet/runtime#38257]
.net core 2.1
To avoid program crash, I use AppDomain.CurrentDomain.UnhandledException to catch the unhandledexception，but the program still crashes and exits

Where to set this property of UnhandledExceptionEventArgs.IsTerminating ?

.net, can set this legacyUnhandledExceptionPolicy
<runtime> <legacyUnhandledExceptionPolicy enabled="true" /> </runtime>

but in .net core, hot to do?

Copied from original issue: dotnet/corefx#33689

**Comment by srisuk2519** [comment]
5c125edb32d388eea765334d465b3b312fe55f5e0ad53174e6f643fb0e461eb147ca28e66b093f85ae26fab658f23f88af5253684c4bf170aa4fa663902449d8

เมื่อ อ. 23 มิ.ย. 2563 เวลา 11:07 ourplan9000 <notifications@github.com>
เขียนว่า:

**Comment by jkotas** [comment]
Ignoring unhandled exceptions is not supported in .NET Core. https://github.com/dotnet/runtime/issues/11546 has more discussion on this.

**Comment by srisuk2519** [comment]
เมื่อ อ. 23 มิ.ย. 2563 เวลา 20:49 Jan Kotas <notifications@github.com>
เขียนว่า:

**Comment by stephentoub** [comment]
This issue is a word-for-word copy of https://github.com/dotnet/runtime/issues/11546#issue-557925198.
