### ISSUE TITLE
Performance improvements on collections

### ISSUE THREAD

**Issue by CalinBunea** [dotnet/runtime#38263]
### Description
Hello,
My name is Calin Bunea and I work as a .NET developer in BigData area. We use .NET for most of our data processing and performance + memory usage is something we must always have in mind. So I will get straight to the proposal.
A LIst<T> in .NET is great because it can dynamically grow without any headache from developers (same applies for other collection structures like HashSet). However, in BigData most of the time, you don't know exactly the amount of data to be stored in a collection and therefore the collection has to grow dynamically. One "problem" with .NET collection when they grow is the fact that they always double the memory size allocated. This strategy works great with relative small collections, but when you have a collection of 50 million items, and you need to add one more item and the memory allocated would double...is quite a lot of wasted memory in my opinion.
I would suggest here to provide an option for the collection so the developer can specify the grown amount (percentage) and a maximum threshold (i.e. grow by 100% every time but not more than 2000 items). 
Another thing which could be dramatically improve is the memory allocation. In C++ there is an option to realoc a chunk of memory, and in case that the adjacent memory is available, the current allocated memory would simply expand and there won't be double memory allocated for a small amount of time plus there won't be any need to move items from original memory (array) to the new bigger one. If realoc cannot expand current memory, the private reference to the memory can be updated, and even GC can actually update all objects which reference that memory (internal array). 
Also this improvement can be done for Array.Resize because you can implement in GC the logic to update references of that memory in case that realoc will allocate a different memory. GC is already doing this while compacting (aka defragmentation) memory, so I'm sure is possible to be implemented. 
Then, I also believe that copying the items (memory copy) can be done faster (probably using 256 and 512 bit registers). Buffer.MemoryCopy is already much faster than managed Buffer.BlockCopy or Array.Copy. Again, is a matter of GC to update the references (if even needed) after the copy procedure.
Then I had a look at List<T>.Insert method. I honestly would expect from a core functionality to be implemented in the most efficient way not in a way where the code looks better. During the Insert there is an EnsureCapacity called which can potential move all the items to a newly expanded Array, and only after that the Insert will actually perform another move of items inside the Array. So if you call Insert on position 0, you potentially move all the items twice. Once between the original array into the bigger array, then another move inside the big array.

### Configuration

all platforms

### Regression?

This was always like that.

### Analysis

I made some tests with Buffer.MemoryCopy VS Buffer.BlockCopy or Array.Copy. Then I made tests of Marshal.AllocHGlobal and Marshal.ReAllocHGlobal

**Comment by SingleAccretion** [comment]
> In C++ there is an option to realoc a chunk of memory, and in case that the adjacent memory is available, the current allocated memory would simply expand and there won't be double memory allocated for a small amount of time plus there won't be any need to move items from original memory (array) to the new bigger one.

Note that if I understand you correctly, this will essentially make `array.Length` a mutable property which does not seem desirable.

**Comment by CalinBunea** [comment]
> > In C++ there is an option to realoc a chunk of memory, and in case that the adjacent memory is available, the current allocated memory would simply expand and there won't be double memory allocated for a small amount of time plus there won't be any need to move items from original memory (array) to the new bigger one.
> 
> Note that if I understand you correctly, this will essentially make `array.Length` a mutable property which does not seem desirable.

Ok, you are right, but then there can be another method exposed by the Array class which will return the newly created Array (if is created). Currently, Array.Resize will generate a new object of type Array eitherway and that new type will have a new Length and the original Array will be actually floating in memory and available for garbage collection, so in any case I don't see your point with Length property... Length is value type, so is not like you can store somewhere a "reference" to the array Length and that reference will no longer be valid...

**Comment by SingleAccretion** [comment]
> so is not like you can store somewhere a "reference" to the array

Well, yes, but you can store reference to the array itself which is arguably equivalent.
In any case, a lot of code throughout the whole stack right now relies on `array.Length` being immutable, so changing that would be quite a break. For example, right now, if you store the array field in a local, JIT can safely assume that its length is not going to change and optimize based on that. If the array is allowed to grow, JIT would be forced to drop this optimization since it would potentially disallow some valid code (Thread 1 is processing the first part of the array while Thread 2 is adding items to the tail).

**Comment by CalinBunea** [comment]
Well, I think there are 2 different things here. I didn't said that array should be allowed to "grow" but rather to provide tools to developer to allow to "expand" the current array in a more efficient way. Thread safety should be a concern for developer as it is today if you try to add items in a List<T> from multiple threads because behind the scenes List<T> has a field T[] _items which actually the "real" storage of data. 

https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs

even if you have

**Comment by jkotas** [comment]
Thank you for taking a time to write a long list of suggestions.

> Buffer.MemoryCopy is already much faster than managed Buffer.BlockCopy or Array.Copy

All these APIs use the same memcpy method from C++ runtime for buffers that are [larger than 2kB - on x64](https://github.com/dotnet/runtime/blob/6b5850fa7cf476b66be9d01a3ed05f4484b01d3a/src/libraries/System.Private.CoreLib/src/System/Buffer.Unix.cs#L17). They will have identical performance for collections of 50 million items that you are concerned about. 

Could you please share your tests that demonstrate that `Buffer.MemoryCopy` is much faster?

> In C++ there is an option to realoc a chunk of memory, and in case that the adjacent memory is available

This situation would be rare in .NET. GC is able to pack the memory blocks next to each other, and so chance that there is a free adjacent memory block available is very low.

> I honestly would expect from a core functionality to be implemented in the most efficient way not in a way where the code looks better

We pay attention to code size of common collections like `List<T>`. Typical application has many copies of the `List<T>` instantiated over different `T`s. The code size of the collections like `List<T>` matters more than optimizations of corner cases that increase code size.

----

Have you considered implementing your own collections that are optimized for your specific scenario? The built-in .NET collections are implemented with many trade-offs that make them a good fix for vast majority of use cases. There are always going to more extreme use cases that require different trade-offs where the built-in collections will be suboptimal.
