### ISSUE TITLE
When will the PrepForRemoting method be available?

### ISSUE THREAD

**Issue by buzzers** [dotnet/runtime#38262]
I'm using the Orleans framework. 
I want to propagate exceptions across processes in this framework and retain the original stacktrace. 
Which has been done in the past, but when upgraded to .net core, because the `Exception.PrepForRemoting` method is no longer supported, we can only get the stack that is truncated. 
This is a huge problem for debugging. When do you plan to re-offer this approach, or if there are other solutions?

**Comment by jkotas** [comment]
`ExceptionDispatchInfo.Throw(Exception source)` allows rethrowing an exception while preserving the original stack track. Unlike `PrepForRemoting`, this method is a proper fully supported public API.

Can Orleans use this API?

**Comment by buzzers** [comment]
@jkotas But ExceptionDispatchInfo can't be serialized, how does this deal with cross-process exceptions?

**Comment by jkotas** [comment]
You are right. `ExceptionDispatchInfo` does not work for binary serialization.

**Comment by buzzers** [comment]
So if I need to propagate an exception across processes, is there a solution at the moment?

**Comment by jkotas** [comment]
`Exception.PrepForRemoting` was an internal implementation detail that Orleans called via private reflection. There is probably a way to replicate the behavior of `Exception.PrepForRemoting` by using private reflection on the current internal implementation details.

All such solutions that depend on private reflection are unreliable and can break at any point.

The only reliable solution for this would be to introduce a public API that does this.

**Comment by buzzers** [comment]
But `Exception.PrepForRemoting` is a feature of dotnet fw and does not exist in the core. Do we have any plans in .NET5 offers a similar API?

**Comment by jkotas** [comment]
`Exception.PrepForRemoting` is internal implementation of .NET Framework. It was never a supported feature. 

We have no plans to work on this work .NET 5.

The process for adding new APIs is here: https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

**Comment by buzzers** [comment]
So now we can only consider using `ExceptionDispatchInfo` to try to solve the problem.
So here's a question: After the exception of the CLR is serialized-deserialized, does stacktrace continue to retain the pre-serialization value or will it be reset empty? Because I found the exception before it wasn't throw, stacktrace was empty.Is the "before throw" here included after de-serialization?

**Comment by jkotas** [comment]
Orleans preserves the exception stacktraces across machines now. See https://github.com/dotnet/orleans/pull/7513 and related issues.
