### ISSUE TITLE
Remove Hardcoding wasm pinvoke  paths

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#38278]
Currently We are hardcoding the pinvokes paths https://github.com/dotnet/runtime/blob/master/src/mono/wasm/wasm.targets#L12

The  list is error pone and we should move away from it.

One was possible solutions suggested by @safern is adding p2ps and getting output assemblies.

cc @safern @ViktorHofer @ericstj

**Comment by ericstj** [comment]
I would expect that this table should consider every assembly which is part of the runtimepack, is that right @akoeplinger?

This seems similar to some other things that @ViktorHofer has been working on.

**Comment by akoeplinger** [comment]
Yes it should consider every assembly.

**Comment by safern** [comment]
Yeah I agree we should consider every assembly instead of hard coding a list of assets.
