### ISSUE TITLE
Use cross-platform code to update apphost win32 resources, open apphost only once for writing

### ISSUE THREAD

**Issue by nguerrera** [dotnet/runtime#3828]
On https://github.com/dotnet/core-setup/pull/6831, it was noted that there now exists some portable code somewhere to update win32 resources, but we are still updating using Win32 API.

The downsides of using the win32 API are:

1. Prevents cross-compilation of apphost. You have to be on a windows build machine to build a windows apphost executable. Even a Windows Nano server is not up to the task.

2. Prevents something like Anti-Virus, sneaking in between different opens of the apphost. We currently open it once to patch in the app name over the placeholder, and again to patch the win32 resources. This should be done with a single open.

Various attempts have been made to get around the anti-virus (or anti-virus-like) issues with retries, but we are seeing that is insufficient with multiple users still running into issues regularly.

See https://github.com/dotnet/cli/issues/11650#issuecomment-549478350

cc @swaroop-sridhar @jeffschwMSFT @peterhuene @davidwrighton

**Comment by KoalaBear84** [comment]
Hmm.. Any idea when this will be fixed? Now forced to build everything on Windows in a GitHub Action because of this.

**Comment by agc93** [comment]
This specific issue has been open for more than 18 months at this point and this behaviour has been (if I'm reading the various issues right) in place since the Core 3.x days. Is there _any_ indication of if this is going to be resolved at all, let alone when?

**Comment by chylex** [comment]
Is this why windows executables built on linux don't have an icon, and open the console window even though they're GUI applications?

**Comment by KalleOlaviNiemitalo** [comment]
@chylex the console window thing seems unrelated to me, as it's controlled by the PE header and not by resources. <https://github.com/dotnet/runtime/blob/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs#L65> <https://github.com/dotnet/runtime/blob/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/src/installer/managed/Microsoft.NET.HostModel/AppHost/PEUtils.cs#L86>

**Comment by rgwood** [comment]
@chylex To answer your other question: yes, this is why Windows exes built on Linux don’t have an icon.

**Comment by mikkeljohnsen** [comment]
Why is this not resolved yet ?

The "csc" command from "mono" was able to target:winexe and set an icon. So this should be simpel to port.

**Comment by LordMike** [comment]
Chiming in as disappointed this won't work on Linux, yet. We'd really like to embed a manifest in our linux build chain - but no luck. :/

**Comment by sps-nathan-alden-sr** [comment]
This was very surprising behavior to me. There does not seem to be any indication in the build logs that PE information will be skipped because of building on Linux. I spent all day yesterday performing extensive debugging on my self-hosted Linux Azure Pipelines build agent to track down what the heck was going on.

I really don't want to build on Windows because of the licensing requirement. My self-hosted build agent is Ubuntu 20.04 LTS and I'd like to keep it that way.

Is there any workaround to this issue? Is there a third-party library out there that can add the PE information?

**Comment by LordMike** [comment]
Hi @sps-nathan-alden-sr we just reiterated this within my team, just a few hours ago, so you're very convenient in reviving this :)

The only workaround I have is to add the manifests _after_ the build, either:

* On Windows (maybe as part of a code signing process), use `mt.exe` to add the manifest
* On any OS, use the Mono development tools to do the same. I'm not aware of the commandline here.

**Comment by Apostolique** [comment]
@sps-nathan-alden-sr when I build my app on Ubuntu 20.04 LTS I get this warning:

> Warning: /home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(550,5): warning NETSDK1074: The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server).

Do you not see this warning in your own builds?

**Comment by smbecker** [comment]
@sps-nathan-alden-sr, I use `rcedit` on Windows and `wine rcedit` on linux. If you have `npm` installed on your build agent, this can be pulled in pretty easily through [npm](https://www.npmjs.com/package/rcedit).

**Comment by sps-nathan-alden-sr** [comment]
> Do you not see this warning in your own builds?

No, I don't. I searched the logs for `NETSDK1074` and don't see any warnings.

**Comment by KalleOlaviNiemitalo** [comment]
[CreateAppHost.ExecuteCore()](https://github.com/dotnet/sdk/blob/714082d0e96cef8c3a5f5d04a08d18baaf036f21/src/Tasks/Microsoft.NET.Build.Tasks/CreateAppHost.cs#L59-L68) outputs the NETSDK1074 warning only for Windows GUI apps, not console apps.

**Comment by LordMike** [comment]
I can additionally report that we tried the workaround of using `mt.exe` to embed the manifest in our single-file published application. I was not able to make it work - as in the manifest was embedded, but what seems to be the .NET application dissappeared. Its like `mt.exe` didn't understand whatever was after the apphost exe, and just removed it.

So for us, using `mt.exe` as a workaround is not an option.

**Comment by trampster** [comment]
I just came accross this issue trying to build an avalonia app for windows from a linux docker container.

**Comment by trampster** [comment]
I just came accross this issue trying to build an avalonia app for windows from a linux docker container.

**Comment by agocke** [comment]
Yeah, I'm seeing if we can fit this in for .NET 7

**Comment by martijnvanschie** [comment]
+1
Took me too long to figure out this was related to `runs-on: ubuntu-latest` ;)

**Comment by RobThree** [comment]
> Yeah, I'm seeing if we can fit this in for .NET 7

@agocke Any news on this?

**Comment by vitek-karas** [comment]
It unfortunately didn't happen in .NET 7.

**Comment by RobThree** [comment]
So we're gonna have to wait until .Net 8? 😳🤪
I'm sure we disagree, and that's ok, but I kinda think a little bit that having a versionnumber in an executable is pretty much a very basic thing to ask for? We're using GitLab with runners to do our builds and, yes, we can use workarounds with `rcedit` and whatnot but I can't say it's ideal. But apparently it's hard to implement; I wouldn't know, so I'll just have to believe that. I hope this gets fixed _soon_. Good luck on whoever is implementing this feature!

**Comment by vitek-karas** [comment]
Thanks a lot for the kind words!
I definitely understand that there are cases where this matters a lot. But unfortunately you're right, this is a relatively complex thing to implement (and test).

**Comment by alexrp** [comment]
Not to beat a dead horse, but I think it's worth noting that this restriction is not just a minor inconvenience, it comes with real cost to private projects that don't enjoy free and unlimited GitHub Actions minutes:

* [Windows runners have a 2x minute multiplier](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers)
* [Windows runners have a 2x per-minute rate](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates)
* Windows runners are generally about 1.8-2x as slow as Linux runners, consuming more minutes on top of the above

I think these facts should probably be factored in when prioritizing this issue.

**Comment by dsplaisted** [comment]
@agocke @vitek-karas Ping on this, any chance we can fix this for .NET 8?  Now that we support [`EnableWindowsTargeting`](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enablewindowstargeting) to allow apps targeting Windows to build successfully on Linux / Mac OS, people are hitting this more.

Here's a recent discussion of this: https://github.com/dotnet/docs/issues/34197

**Comment by rubo** [comment]
Same here. We're hitting this issue on GitHub Actions Ubuntu runners as all our workflows are tailored to Linux. This is not a minor inconvenience, indeed.

**Comment by agocke** [comment]
Unfortunately, this is approaching the cut line for .NET 8. We may not have the resources to complete it in this release. But I will try to triage and see if we can get it in.

**Comment by r-work** [comment]
It would really be a shame if this misses 8.0, we've been waiting for so long for this, this issue itself about 4 years old.

**Comment by mikkeljohnsen** [comment]
We have been waiting for this more than 3 years now, ever since we changed from Mono to dotnet.

Mono had the functionality.

**Comment by agocke** [comment]
@mikkeljohnsen This is news to me -- if the code is easily available in Mono then it might be as simple as porting it over. We would certainly take a PR.

**Comment by elinor-fung** [comment]
Thanks a lot to @anatawa12 for taking this on - https://github.com/dotnet/runtime/pull/89303 has been merged and will be in .NET 8.

**Comment by NCLnclNCL** [comment]
> Thanks a lot to @anatawa12 for taking this on - #89303 has been merged and will be in .NET 8.

can you explain me what it does, i think the apphost is a c++ exe file copied and renamed and the dll is shared, why can't for win32

**Comment by anatawa12** [comment]
My understanding is this.

AppHost for Windows GUI should have resources for app icon and else. So, .NET SDK copies resources from dll to AppHost exe.
However, copying resources was performed with Win32 API so copying resources was not performed on non-windows.
So cross-built Windows GUI app will not have (correct) icon and exe will be executed as console app.

My pull-request adds cross-platform (managed only) code to add resources to AppHost exe instead of Win32 API invocation.
This will fix the problem that cross-built Windows GUI app will not have (correct) icon.
