### ISSUE TITLE
Setting 5.0 milestone in this repo

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#38286]
As you know we’re working hard to release .NET 5 in November. 

## Milestones

We expect to use much the same process we used last year to ship .NET Core 3.0. Over the next 3 weeks in this repo we’re working to clear the 5.0 milestone of everything except those issues we must fix for that release. You’ll see us set the 5.0 milestone on some issues and remove it from others. That doesn’t mean we won’t take community fixes – generally we’ll remain open to other changes from our community as we usually are. We are setting the milestone mainly so that our team can focus on what must be fixed to complete feature work and make a high quality release. As always your comments are welcome in the issues. You will also see there is a 6.0 milestone. This is mainly for some teams working on [Xamarin unification work](https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/). We're not currently using it to scope all 6.0 work. If an issue is marked Future that does not mean it will not happen in the 6.0 product. It simply means, it is not a must have for 5.0 release.

## Codeflow

At the moment code in master in this repo contains changes destined for 5.0. We plan to branch this repo off master for 5.0 for the last time likely in August. From that point on any further changes for 5.0 will be selectively ported from master. Other .NET repos that are higher in the stack, such as dotnet/sdk and dotnet/aspnetcore, may go through this process a little later, but we will all ship together in November.

@danmosemsft @jeffschwMSFT @marek-safar

**Comment by charlesroddie** [comment]
.Net 5 is very ambitious so it's not unexpected that some things slip.

The difficult, ambitious, and impactful part of the original plan was the unification of mono and netcore into "one dotnet". This allows .net 5 to run mono workloads, of which the main ones are Xamarin and Webassembly.

If Xamarin is not included this is missing and the name ".Net 5" isn't appropriate. Webassembly is in but isn't really usable if it doesn't include the aot/linker work.

This strategy does not unify .Net so would be better called ".Net Core 4" with ".Net 5" to come later.

It would be better to .Net Core 3.2 in Nov and push back the .Net 5 release until it can cover the main .Net workloads.

**Comment by danmosemsft** [comment]
@charlesroddie .NET 5 we will be adding support for WebAssembly. That didn't move to .NET 6. See  https://github.com/dotnet/runtime/issues/38367

**Comment by vcsjones** [comment]
@danmosemsft The timeline for 5.0 seems similar to 3.0, so far. Given that, I would expect the `release/5.0` branch is going to be taken soon. Can you share any additional info on when that will happen?

Apologies if this spelled out somewhere and I missed it.

**Comment by danmosemsft** [comment]
@vcsjones right now we're thinking mid-August. Work before that in master will end up in 5.0, work after that would be ported selectively.

**Comment by danmosemsft** [comment]
Issue has fulfilled its purpose.
