### ISSUE TITLE
Blazor debug proxy and Mono proxy should generate ETL events

### ISSUE THREAD

**Issue by digeff** [dotnet/runtime#38285]
For investigating performance issues it'd be great if Blazor debug proxy and Mono proxy generates ETL events for the main things that are happening (loading things, getting requests to set breakpoints, and the breakpoint can now be hit, etc...) so then we can use the ETL trace gathered by the VS Report a Problem tool to easily analyze performance issues

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by lewing** [comment]
The proxy is running on the host runtime so much of this is about logging the events there.

/cc ankit

**Comment by lewing** [comment]
@lateralusX @lambdageek is there a better issue tracking this now?

**Comment by mdh1418** [comment]
Hi @digeff, just to clarify, are the events you'd like to see in the ETL trace file specifically events related to the debugger proxy and not the application? Are you looking to see if there are performance issues stemming from the debugger proxy?
