### ISSUE TITLE
Allow deletion of custom attributes with the linker

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#38301]
## Background and Motivation

The proposal is to create an attribute for specifying "always" removed attributes. The main purpose is to reduce size on final applications by deleting the attributes we know are not necessary. The proposed name for this attribute is `LinkerRemovableAttribute` and is used to annotate other custom attribute types. Adding the `LinkerRemovableAttribute` attribute on a custom attribute type means that the linker will remove all attributes usages of the custom attribute type but not the attribute definition. The `LinkerRemovableAttribute` has been discussed in https://github.com/mono/linker/issues/1162 and https://github.com/mono/linker/issues/1163. This is an internal-only API.

## Proposed API

Allow the `LinkerRemovableAttribute` to be applied to class types. Tools would warn in case a custom attribute is referenced (reflection) after custom attribute removal
```
[AttributeUsage (
AttributeTargets.Class, Inherited = false)]
public sealed class LinkerRemovableAttribute : Attribute
{
}
```
Implementation is simple enough since the attribute doesn't need any particular parameters just needs to be referenced in the type

## Usage Examples

One usage mode would be injecting the attribute using the --link-attributes flag and passing an XML file stating the custom attributes to be removed. For example: 
```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="*">
    <type fullname="System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute">
      <attribute fullname="System.Diagnostics.CodeAnalysis.LinkerRemovableAttribute"></attribute>
    </type>
  </assembly>
</linker>
```
This for example will remove the System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute from all assemblies (since its making use of an * in assembly). 

The other usage mode would be annotating the class directly with the attribute. 
```diff
	[AttributeUsage (
		AttributeTargets.Field | AttributeTargets.ReturnValue | AttributeTargets.GenericParameter |
		AttributeTargets.Parameter | AttributeTargets.Property |
		AttributeTargets.Method, // This is used only to mark the "this" parameter - it should not appear in public API for this attribute (and we don't support it on anything but System.Type)
		Inherited = false)]
+	[LinkerRemovable]
	public sealed class DynamicallyAccessedMembersAttribute : Attribute
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DynamicallyAccessedMembersAttribute"/> class
		/// with the specified member types.
		/// </summary>
		/// <param name="memberTypes">The types of members dynamically accessed.</param>
		public DynamicallyAccessedMembersAttribute (DynamicallyAccessedMemberTypes memberTypes)
		{
			MemberTypes = memberTypes;
		}

		/// <summary>
		/// Gets the <see cref="DynamicallyAccessedMemberTypes"/> which specifies the type
		/// of members dynamically accessed.
		/// </summary>
		public DynamicallyAccessedMemberTypes MemberTypes { get; }
	}
```
Alternatively, you could use feature switches to remove the custom attributes only under certain circumstances
```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="Assembly">
    <type fullname="Assembly.A" feature="EnableOptionalFeature" featurevalue="false">
      <attribute fullname="System.Diagnostics.CodeAnalysis.LinkerRemovableAttribute"></attribute>
    </type>
  </assembly>
</linker>
```

## Alternative Designs

The name of the attribute is still open to discussion, we could also include parameters for notes in case we believe they are necessary.

## Risks

As all removals, this could lead to problematic behaviors. This will be partially mitigated by the tools (IL Linker) warnings about some cases but there would be other cases like mark unconditional GetCustomAttributes as a problematic API.

**Comment by tlakollo** [comment]
cc @stephentoub @terrajobst @marek-safar @vitek-karas @jkotas

**Comment by stephentoub** [comment]
I'm not understanding why this requires a new attribute.  If the primary use case is just naming it in the XML file, why can't specifying the removal of an attribute just be a feature of the XML file?

**Comment by vitek-karas** [comment]
Couple of notes from our thinking about this:
* We don't plan (want) to make this attribute public for .NET 5 - we don't have a need for a public one, only internal one right now. We wanted to go through at least some API discussion to reduce the burden of renaming it (and other changes) in the future once we do make it public.
* Currently we plan to have most of it in XML because it's the fastest way to do that for Blazor, but we think that long term the right place for these would be in the actual code (where it's possible) - mostly "code locality" arguments
* Removal of some attributes will be conditioned by feature switches - currently we only have the ability to "feature switch" in the XML, but we plan to have then in the code in the future as well

**Comment by stephentoub** [comment]
> We don't plan (want) to make this attribute public for .NET 5

There's multiple aspects of public, though.  If developers will be able to name it in an XML file they pass to the linker, referring to some internal attribute in corelib, then if we delete/rename/etc. that attribute, we'd break them.  So while it's not public from the perspective of C# code using it, it is public from the perspective of these XML files using it.

Or am I misunderstanding the intent for .NET 5?

**Comment by marek-safar** [comment]
@tlakollo it would be helpful for the review to include example how this attribute will be used in c# only (no XML)

**Comment by vitek-karas** [comment]
> Or am I misunderstanding the intent for .NET 5?

You're right (no misunderstanding) - I think we should not advertise this capability too widely - we'll use it for Blazor (and even that is not 100% yet - depends on actual size wins).
The alternative to an "internal" API is to have a feature in the linker (something similar to what you suggest) - but that would also be "temporary" and would fall into the same "we'd have to support this going forward" category.

I thought that defining an internal attribute would be a slightly cleaner solution (since it would allow us to use it on at least some of the attributes in code already for .NET 5) - but if we come to a conclusion that this is not desirable from FX's point of view, we can go the linker-only route for now.

**Comment by tlakollo** [comment]
> @tlakollo it would be helpful for the review to include example how this attribute will be used in c# only (no XML)

I update the usage section with the attribute usage directly on the class and an example with the feature switch on the xml

**Comment by stephentoub** [comment]
> I update the usage section with the attribute usage directly on the class and an example with the feature switch on the xml

Thanks, but wouldn't such a removal be problematic for, e.g., our usage in dotnet/runtime? What would prevent the linker from trimming out these attributes when doing the assembly build (rather than the subsequent app build)?

**Comment by vitek-karas** [comment]
There will have to be a way in the linker to disable attribute removal all up anyway, so I assume the libraries build would set that option.

**Comment by MichalStrehovsky** [comment]
Whether an attribute is removable really depends on what you as an end user are trying to do. It's not a property of the attribute itself. It feels weird to have this as a custom attribute placed on the attribute.

I understand the use case for this when it's in an XML file under a feature switch (e.g. "remove "feature" nullable annotations"). But for that we don't need an actual attribute type. It can be a pseudoattribute (a unique text string we put in the XML file). We could also just have dedicated XML syntax.

Is `CLSCompliantAttribute` a removable attribute? Well that really depends on whether one uses it for something at runtime. If you have some sort of [scripting engine](https://github.com/blancosj/dodonet/blob/0613dd61e2e2fb652aaf74508ce18383965a8617/DodoNet/JScript/engine/typeexpression.cs#L175) you wouldn't appreciate linker stripping it without questions.
Should the C# nullable annotations just be garbage collected as soon as possible? Yes, if you ask me. But [others](https://github.com/dotnet/runtime/issues/29723) might disagree.

It doesn't feel like the attribute's removability is something for the attribute itself to decide.

**Comment by stephentoub** [comment]
> But for that we don't need an actual attribute type. It can be a pseudoattribute (a unique text string we put in the XML file). We could also just have dedicated XML syntax.

I agree.  The whole purpose of the XML file is to exert fine-grained control over what's kept and what's not.  Up until now it's been a way to say "even if you would have gotten rid of this, keep it".  It makes sense to me that the mechanism would be expanded to also allow you to say "even if you would have kept this, get rid of it".  I don't think an actual attribute in corelib is the right way to do that.

**Comment by marek-safar** [comment]
Let me offer a bit different perspective on this. The XML syntax is here to stay and it's actually required in some scenarios. What I think is worth discussing is if we should have an attribute which allows us to connect an attribute with feature-switches in the source code. If we find that valuable should the name/syntax be the same in XML or not.

I think having clearly visible annotation for feature-switch controllable attributes is more maintainable over a set of XML files each grouped per feature switch or something similar. My main concern is that the list of attributes maintained this way will be long and growing. For illustration, we can pick two feature switches (the same list can be built for serialization, ETW, globalization, etc)

1. Debugger.IsDebuggingSupported
- DebuggableAttribute
- DebuggerBrowsableAttribute
- DebuggerDisplayAttribute
- DebuggerHiddenAttribute
- DebuggerNonUserCodeAttribute
- DebuggerStepThroughAttribute
- DebuggerStepperBoundaryAttribute
- DebuggerTypeProxyAttribute
- DebuggerVisualizerAttribute
- StackTraceHiddenAttribute

2. IsComSupported
- ClassInterfaceAttribute
- CoClassAttribute
- ComDefaultInterfaceAttribute
- ComEventInterfaceAttribute
- ComImportAttribute
- ComSourceInterfacesAttribute
- ComVisibleAttribute
- DispIdAttribute
- GuidAttribute
- InAttribute
- InterfaceTypeAttribute
- LCIDConversionAttribute
- OptionalAttribute
- ProgIdAttribute
- TypeIdentifierAttribute

_Note: Both lists are probably incomplete_

**Comment by MichalStrehovsky** [comment]
Feels like what we need is a way to tag the attribute (or attribute constructor?) as a "feature".

Can we meld that with the mechanism for feature switches that we have in the linker?

**Comment by MichalStrehovsky** [comment]
In the [original link-time framework feature removal model](https://github.com/dotnet/designs/pull/42) (that was largely inspired by how `ConditionalAttribute` works during source compilation), the extension would be straightforward because it would work the same as when `ConditionalAttribute` is placed on a custom attribute. I don't have a good mental model for the current removable feature design to offer suggestions.

**Comment by joperezr** [comment]
@eerhardt not sure if this one has to be done by 5.0 so I added it to the Linker project and set the 5.0 milestone for now.  Feel free to push to future and remove from the project if you think it is appropriate.

**Comment by tlakollo** [comment]
For 5.0 the agreement is to only use an internal attribute instead of creating one in the runtime as described in comment https://github.com/mono/linker/issues/1162#issuecomment-652441773

**Comment by eerhardt** [comment]
Instead of pushing this to future, I'm going to close this issue. I'm not sure we will do this work in the future. We can re-open this issue, or open a new one, when we want to do this work.
