### ISSUE TITLE
No way to null-annotate a validation method that throws if null

### ISSUE THREAD

**Issue by dotMorten** [dotnet/runtime#38319]
### Description

Often you write little reusable validations methods to validate the state of an object, including it not being null.
So you might write something like this:
```cs
private void ValidateString(string? value)
{
    if(value is null) throw new ArgumentNullException(nameof(value));
    if(value.Length != 8) throw new ArgumentException(nameof(value));
}
```
So in a public method you could imagine having something like this (of course overly simplified):
```cs
public void MyMethod(string? value)
{
    ValidateString(value);
    // At this point value is guaranteed to not be null but there's no way to annotate this
}
```
It seems like a bit of an oversight, because there are annotations to specify a method will never return, or if a return value is something specific (true/false) then the value is not null either.
I realize I could use the `NotNullWhen` attribute here, but that means I now have to duplicate throwing the correct argument exceptions everywhere false is returned.

FXCop actually has a way to do the same thing, so obviously there is a need:
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019#null-check-validation-methods

### Configuration
.NET Core 3.1

### Regression?
No

**Comment by meziantou** [comment]
I think you can just use `[NotNull]` here

````
private void ValidateString([NotNull] string? value)
{
    if(value is null) throw new ArgumentNullException(nameof(value));
    if(value.Length != 8) throw new ArgumentException(nameof(value));
}
````

**Comment by dotMorten** [comment]
@meziantou Oh good call! Didn't notice that can go on a parameter as well. I should have read the second part of that sentence closer:
> Specifies that an output is not null even if the corresponding type allows it. Specifies that an input argument was not null when the call returns.

Thanks!
