### ISSUE TITLE
Constructor decorated with the JsonConstructor attribute should be able to be non-public

### ISSUE THREAD

**Issue by swtrse** [dotnet/runtime#38327]
In general, a constructor decorated with the [JsonConstructor] attribute should be able to be a non-public constructor.

This would address cases where there is a special internal constructor that is solely used for json deserializing and that should not be called from user code.

Category: Design

**Comment by danmosemsft** [comment]
Removing label as this is not proposing new API surface.

**Comment by layomia** [comment]
We want to hold off on doing this until the ramifications to the ongoing [JSON code generation](https://github.com/dotnet/runtime/issues/1568) efforts are well understood - https://github.com/dotnet/runtimelab/tree/JsonCodeGen.

**Comment by c0g1t8** [comment]
> We want to hold off on doing this until the ramifications to the ongoing [JSON code generation](https://github.com/dotnet/runtime/issues/1568) efforts are well understood - https://github.com/dotnet/runtimelab/tree/JsonCodeGen.

The last link does not exist.  I believe it should be https://github.com/dotnet/runtimelab/tree/feature/JsonCodeGen.

**Comment by layomia** [comment]
Merging this into https://github.com/dotnet/runtime/issues/31511 which considers support for non-public members in general, not just ctors.
