### ISSUE TITLE
Generate a version metadata file which can be used by dotnet-install

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#3833]
When the runtime or other components generates a stabilized build, it publishes to a non-stable directory, with an identical set of stable and suffixed asset names inside. This is so that dotnet-install, which makes an assumption that the version to install will match the asset name, will work properly.  Example:

```
3.0.100-preview3-123545\sdk-3.0.100-preview3-123545.zip (contents are 3.0.100 branded) 
3.0.100-preview3-123545\sdk-3.0.100.zip (contents are 3.0.100 branded) 
```

We publish both so that we can push the final branded artifacts on release day, and the suffixed assets will work with dotnet-install. dotnet-install, however, will install the sdk, then look for the installed version (3.0.100-12345) rather than 3.0.100 because it knows nothing about the contents of the zip. It will fail.

We want to solve two problems

- dotnet-install doesn't know what version to check for when it expands an archive
- We have to double publish everything so that we still have the desired suffix-less assets for release day.

To solve this, the runtime, sdk, and aspnetcore repos should produce a file called productVersion.txt, which inside, identifies the actual product version.  Example:

```
productVersion.txt-> contains 3.0.100
```

Thus, the dotnet-install script can find the blob directory of the files based on the passed in version, then look up the file containing the version number and use this to identify what the names of the runtime/sdk archives it should download as well as what it should verify it installed after it completes,.

**Comment by NikolaMilosavljevic** [comment]
@donJoseLuis are you looking at this for 5.0?

**Comment by mmitche** [comment]
I think we will need this for 5.0. Because right now stable builds do not work.

**Comment by MattGal** [comment]
Taking this issue to work on as part of the DncEng dependency flow / servicing readiness work, please let me know if you're already working on it!

**Comment by MattGal** [comment]
This is done, via https://github.com/dotnet/runtime/pull/41719 (master) and
https://github.com/dotnet/runtime/pull/41721 (release/5.0-rc2) branches.
