### ISSUE TITLE
Standalone GC for Unix arm doesn't have FEATURE_64BIT_ALIGNMENT defined

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#38358]
When debugging a GC issue on arm Linux, I've tried to use the standalone GC. I've found that in debug build we assert `assert ((flags & GC_ALLOC_ALIGN8) == 0)`, because the FEATURE_64BIT_ALIGNMENT is not defined for the standalone GC build. It is defined for the built-in GC.
In release build, I've hit an alignment fault in jitted code instead.
I've found that just defining the FEATURE_64BIT_ALIGNMENT is not sufficient, as the simplified copy of MethodTable class that the standalone GC uses doesn't have definition for `RequiresAlign8` method. But it should be easy to fix too.

**Comment by Maoni0** [comment]
fixed with [PR#38970](https://github.com/dotnet/runtime/pull/38970)
