### ISSUE TITLE
.NET Core 2.X does not resolve valid certificate chain path when there is an intermediate cross-signed certificate (Linux only)

### ISSUE THREAD

**Issue by kevinpayne** [dotnet/runtime#38350]
@bartonjs @GrabYourPitchforks @krwq

It appears that certificate chains where there’s a choice of cross-signed intermediate certificates, is “resolved” differently between 2.x and 3.x.

On May 30th, a security certificate from Sectigo (formerly Comodo Certificate Authority) expired. In preparation for this event, we had added a new cross-signed intermediate certificate to our servers. 

When the certificate expired, all of our .NET Core 2.X (Linux) docker containers started failing in production, whereas the .NET Core 3.1 containers were ok.  It appears that 2.x was not smart enough to figure out the valid path to the new root in the local trust store. 

Is this a known short-coming in the 2.x Linux X509 library or perhaps a bug that was fixed in 3.X?

Here is the chain from the server. 1 is the new intermediate. 2 and 3 are expired.

 0 s:/C=US/postalCode=99999/ST=CA/L=Vista/street=9999 Street Dr./O=My Company, Inc./OU=IT/OU=PremiumSSL Wildcard/CN=*.blahblahblah.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Organization Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Organization Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   
   
I've been asked to determine root cause. Any insight from your team is very much appreciated.

**Comment by bartonjs** [comment]
The chain resolution was overhauled between 2.1 and 3.1 to make scenarios like this work better.

**Comment by bartonjs** [comment]
Essentially: In 2.1 the chain walker is greedy (the first cert is used that has the right match characteristics), but in 3.1 it considers more potential chains before picking the "best" one (where "trusted root" beats "untrusted root" and "not expired" beats "expired")

**Comment by kevinpayne** [comment]
Got it. Makes sense and gives us yet another reason to migrate over to 3.1 sooner rather than later. Thanks for the help!
