### ISSUE TITLE
API Proposal: Add Environment.ProcessId property

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#38388]
## Background and Motivation

A non-trivial amount of code uses:
```C#
Process.GetCurrentProcess().Id
```
to get the ID of the current process.  Some examples:

https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/Process.cs,e7bdad2b99a54a87,references

While that works:
a) from a throughput perspective it's much more expensive than it needs to be
b) it allocates a Process just to get the Id
c) it's easy to forget to Dispose of the Process instance, making it that much more expensive
d) if nothing else is using Process, it increases linked size by increasing the graph of types referenced
e) it's not as discoverable as it otherwise could be

It'd be nice to have a cheap, simple, available-without-using-Process way to get at the current process' ID, for logging or any other reason.

Various places avoid going through `Process` by P/Invoking directly; such usage could be switched to this new API.

## Proposed API

```C#
public static class Environment
{
    public static int ProcessId { get; } // new property
    ...
}
```

## Usage Examples

```C#
Log($"{Environment.ProcessId}: {message}");
```

**Comment by hypeartist** [comment]
What about exposing a process handle same way?

**Comment by AaronRobinsonMSFT** [comment]
This approach also has the opportunity of caching that value for all future callers as well - since I would assume we expect it to be unchanged for the lifetime of the current process.

**Comment by terrajobst** [comment]
Looks fine to me as proposed. Ideally, we'd combine this with an analyzer/fixer that recommends replacing with `Process.GetCurrentProcess().Id` with `Environment.ProcessId`.

@dotnet/fxdc?

**Comment by terrajobst** [comment]
* Looks good as proposed.
* We verified that `int` is appropriate data type across all operating systems
* We'll avoid throwing in WASM and instead return a value, such as `42`

namespace System
{
    public static class Environment
    {
        public static int ProcessId { get; } // new property
    }
}
