### ISSUE TITLE
Mark System.Diagnostics.DiagnosticsEventSource.TransformSpec.PropertySpec.PropertyFetch.FetcherForProperty as unsafe for linker-trimming

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#38404]
See discussion here: https://github.com/dotnet/runtime/pull/38216#discussion_r445435926

https://github.com/dotnet/runtime/blob/afc9f65bd63f911d9f709fae2bd95021dab65411/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs#L898

**Comment by eerhardt** [comment]
This isn't necessary for 5.0, there are a lot of APIs that are unsafe that aren't being marked. Moving to 6.0.

**Comment by eerhardt** [comment]
This was addressed in #50265.
