### ISSUE TITLE
Improve Activity API usability and OpenTelemetry integration (Part 2)

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#38419]
The whole design of the proposed APIs is in the issue https://github.com/dotnet/designs/pull/134

**Comment by terrajobst** [comment]
[Spec](https://github.com/dotnet/designs/pull/134)

* `ActivityContext.IsRemote` sounds like the instance is remoted, which isn't the case, but we can't think of a better name.
* Making `Activity.Kind` settable seems very unfortunate. Given we do this backward compat only, we should find another way of doing this without making one of the key properties mutable. One option is to disallow changing after it was observed (whatever that means). The preferred option would be to find a way that doesn't require mutation (constructor parameter, factory method etc).
* `Activity.Attributes` seems unfortunate b/c it adds more concepts.
    - Add `SetTag(string, object)`
    - Add `AddTag(string, object)`
    - Add `TagObjects`
    - The existing `Tags` property should probably be marked as obsolete and return all convert all objects to string.
* `ActivityAttributesCollection` should be renamed to something `ActivityTagsCollection`
* `ActivityListener.PregenerateNewRootId` has complex policy so be it

```C#
namespace System.Diagnostics
{
    public readonly partial struct ActivityContext
    {
        // This constructor already exist but we are adding extra defaulted parameter for isRemote.
        public ActivityContext(ActivityTraceId traceId, ActivitySpanId spanId, ActivityTraceFlags traceFlags, string? traceState = null, isRemote = false);

        // This is the new property
        public bool IsRemote { get; }
    }
    public partial class Activity
    {
        public void AddTag(string key, object value);
        public void SetTag(string key, object value);
        public IEnumerator<KeyValuePair<string, object>> TagObjects { get; }
    }
    public readonly struct ActivityEvent
    {
        public ActivityEvent(string name)
        public ActivityEvent(string name, DateTimeOffset? timestamp = null, ActivityTagsCollection? tags = null);
    }
    public readonly partial struct ActivityLink  : IEquatable<ActivityLink>
    {
        public ActivityLink(ActivityContext context, ActivityTagsCollection? tags = null)
    }
    public class ActivityTagsCollection : IDictionary<string, object>
    {
        // Implements this[key] = value as deleting the key
        // Add(key, null) should throw if key already exists, otherwise no-op
        // Should meant that this[key] returns null for-non existing keys too
    }
    public sealed class ActivityListener
    {
        public bool AutoGenerateRootContextTraceId { get; set; }
    }
}
```

**Comment by tarekgh** [comment]
> The existing Tags property should probably be marked as obsolete and return all convert all objects to string.

Just to comment on that, we are not going to obsolete it in this release as it will be a big breaking for libraries using the old way of activity (e.g. asp.net, http client,...etc.). Also, we'll not change the Tags behavior and we'll return only the items which has string values. that is for less confusion and also for the sake of the performance.
