### ISSUE TITLE
[Analyzer Suggestion] (Performance) Usage of ConvertAll vs LINQ Select

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#38418]
I haven't done the benchmarks yet, but based on [this](https://stackoverflow.com/a/55624925/5108631) stackoverflow answer:

> The first answer should not be the accepted one. I am a former 2007 C# Microsoft MVP.
>
> In contrast to the accepted response, ConvertAll is much more efficient than the combination of Select and ToList().
>
> First of all, ConvertAll is strictly faster and it uses the minimum amount of memory to do so. Same as Array.ConvertAll vs Select and ToArray. This would be a much more evident with a larger length array or many calls within a loop.
>
> 1) ConvertAll knows the size of the final list and avoids reallocating the base array. ToList() will keep resizing the array multiple times.
>
> 2) ToList will make slower interface IEnumerable<> calls, while ConvertAll will loop through the underlying array without extra calls or range checks.
>
> 3) Select will create an extra IEnumerable<T> object.

If `ConvertAll` is more performant than LINQ's `Select`, I think it's worth having an analyzer (I believe this analyzer will get flagged in many projects and will be useful, there is even an [example](https://github.com/dotnet/roslyn-analyzers/blob/7bc7660d8f01dbc06fd8d1ac672e44c1d033f5dc/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ReleaseTrackingHelper.cs#L167) in this repo!).

I think same could apply to `Array.ConvertAll` vs `.Select` chained by `.ToArray()` call.

**Comment by eiriktsarpalis** [comment]
Presumably such an analyzer would only apply to `arrayOrList.Select(_ => _).ToArray()` expressions right? It is not necessarily guaranteed to be faster in the general case and it might also result in subtle breaks when the lambdas are stateful.

**Comment by Youssef1313** [comment]
@eiriktsarpalis 

> Presumably such an analyzer would only apply to `arrayOrList.Select(_ => _).ToArray()` expressions right?

I think either `array.Select(_ => _).ToArray()` (which can be converted to `Array.ConvertAll(...)`), or `list.Select(_ => _).ToList()` which can be converted to `list.ConvertAll(...)`.

>  It is not necessarily guaranteed to be faster in the general case and it might also result in subtle breaks when the lambdas are stateful.

But it won't degrade performance right? Either same performance or higher?
Would it be easy for the analyzer to determine if the change will break something?

**Comment by eiriktsarpalis** [comment]
Consider the following snippet:
```csharp
int[] input = Enumerable.Range(1, 1_000_000).ToArray();

int state = 0;
_ = input
    .Select(x => ++state)
    .Take(5)
    .Count();

Assert.Equal(5, state);
```

Replacing that particular `Select` with `ConvertAll` will result in
1. a second large array allocation,
2. breaking the assertion (`state` will now equal `1_000_000`).

**Comment by eiriktsarpalis** [comment]
Here are the benchmark results from my machine:
```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19041
Intel Core i7-8665U CPU 1.90GHz (Coffee Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.6.20323.1
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  DefaultJob : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
```

|     Method |           Mean |        Error |        StdDev |     Ratio |  RatioSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|----------- |---------------:|-------------:|--------------:|----------:|---------:|---------:|---------:|---------:|----------:|
|     Select |       106.8 ns |      2.07 ns |       2.55 ns |      1.00 |     0.00 |   0.0459 |        - |        - |     192 B |
| ConvertAll | 2,703,668.9 ns | 53,791.41 ns | 114,633.88 ns | 25,007.64 | 1,290.70 | 203.1250 | 203.1250 | 203.1250 | 4000155 B |

**Comment by Youssef1313** [comment]
@eiriktsarpalis  I don't thinl the analyzer should report any diagnostic in that case for two reasons:

1. `.Select(x => ++state)`: it should only be reported if `.Select(x => some_thing_that_doesnt_change_state)`. (Not sure how hard to determine if it changes the state or not) (*Perhaps* operations the involves only `x`?)

2. The existence of `.Take(5)` call.

So, I believe it should be reported in a case like the following (**if** there is a perf improvement):

```
int[] input = Enumerable.Range(1, 1_000_000).ToArray();

int[] inputPlusOne = input
    .Select(x => x + 1)
    .ToArray();
```

**Comment by stephentoub** [comment]
The justification shared in the initial post is no longer accurate (the only one of the points that is still correct is that the Select call will allocate a small enumerable object).  If you have `array.Select(...).ToArray()`, the optimizations in LINQ are going to cause this specialized method to be used:
https://github.com/dotnet/runtime/blob/4486164506a56200e66cf4cd750fde6b54ab5abd/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs#L74-L87

You'll notice that is almost identical to the implementation of `Array.ConvertAll`.  I don't think there's a need for such an analyzer at this point.

**Comment by Youssef1313** [comment]
@stephentoub, Thanks. I added a link to your comment on the stackoverflow answer as it might help others. Closing.
