### ISSUE TITLE
[Feature Request] Support GraalVM like use-cases

### ISSUE THREAD

**Issue by redradist** [dotnet/runtime#38426]
Hi all,

What if `.NET` will support `GraalVM` like use-cases with multiple-language interaction ?

It is possible today, but `GraalVM` goes further with adding support for `LLVM` and `WebAssembly` byte codes as well as other languages as `Python` ( `IronPython 3` died without even being born :( ), `JavaScript` and other languages ...

`.NET` has better infrastructure than `GraalVM`, because it supports `The Dynamic Language Runtime DLR`

`LLVM` and `WebAssembly` could be translated to `IL` code and set of translator could be called `The Native Language Runtime NLR` or something like this ...

In such way `.NET` really become `The Common Language Runtime CLR`

**Comment by jeffschwMSFT** [comment]
Adding @marek-safar for comment on our webassembly support.

**Comment by marek-safar** [comment]
I agree it would be nice to run popular intermediate languages (byte codes) on .NET but it's not on our roadmap right now.
