### ISSUE TITLE
aspnet core using Json.Text instead of Newtonsoft bug

### ISSUE THREAD

**Issue by foxjazz** [dotnet/runtime#38435]
### Describe the bug
when NOT using newtonsoft serializer for returning objects from get requests can result non valid json responses when using base64 strings.

### To Reproduce
Unfortunately I don't have a good way to reproduce this. I would try base64 of a few pictures and add to a parmeter. 64k in length. And test. I have a string that fails, but can't produce it here.

### Further technical details
- ASP.NET version 3.1.4
-

**Comment by layomia** [comment]
Can you please provide a small project that highlights the issue, or some more information about what type specifically you are serializing and what the input to the serializer looks like?

**Comment by layomia** [comment]
Will close - this issue isn't actionable as is. Please let us know if you still face issues here.
