### ISSUE TITLE
WebAssembly should support handling runtimeconfig.json

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#38433]
See https://github.com/dotnet/runtime/pull/37535#issuecomment-649890269

**Comment by marek-safar** [comment]
Could you clarify why? We'd need to copy the files to the temp file system and add all the baggage for handling the json logic which is not necessary for self-contained setup.

I think a better approach is to add the configProperties section which is probably the only relevant part for self-contained configs to csproj PropertyGroup and handle it during build.

**Comment by akoeplinger** [comment]
Yeah I was imprecise when creating the title, I don't think we need to necessarily read the file as part of the WASM process but we need to handle it _somehow_ rather than just ignoring it.

**Comment by radical** [comment]
> I think a better approach is to add the configProperties section which is probably the only relevant part for self-contained configs to csproj PropertyGroup and handle it during build.

Do you mean - read the `configProperties` section of the `runtimeConfig.json`, and add it to the build, so that we don't have to support reading `runtimeConfig.json` itself in the wasm app?

**Comment by marek-safar** [comment]
We should just leverage the runtimeConfig.json task we have for mobile AOT for WASM AOT

**Comment by lambdageek** [comment]
Yea, this is exactly what the runtimeConfig.json task is meant to do.  The WasmApp target needs to be updated to use it, and then driver.c needs to be updated to call the runtime API that consumes the binary blob of the parsed json file.

**Comment by SamMonoRT** [comment]
cc @lewing @radical - Fan will give this a shot.

**Comment by eerhardt** [comment]
Is this going to be completed for .NET 6? Using AppContext switches is becoming more and more important in order to support feature switches. For example, the plan in https://github.com/dotnet/runtime/pull/55102 is relying on the fact that an AppContext switch will be set in applications that will be trimmed during `F5/dotnet run`.

**Comment by SamMonoRT** [comment]
> Is this going to be completed for .NET 6? Using AppContext switches is becoming more and more important in order to support feature switches. For example, the plan in #55102 is relying on the fact that an AppContext switch will be set in applications that will be trimmed during `F5/dotnet run`.

Yes, a PR should be up soon
