### ISSUE TITLE
Add linker trimming test for reflection usage in System.Net.CookieExtensions.IsRfc2965Variant

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#38447]
i.e add a test following this change https://github.com/dotnet/runtime/pull/38216/files#diff-8dd8b975ead2339ec56247c4dcbcfeccL45

**Comment by karelz** [comment]
@layomia @eerhardt is this still on your radar for 6.0? I see it is in "Uncommitted" column in the project, so I wonder ...

**Comment by eerhardt** [comment]
I don't think this is still on the radar for 6.

Looking again, since the linker isn't warning in this location, we can assume it works correctly with trimming. There isn't a strong need to add a test. Closing.
