### ISSUE TITLE
Test failed: Loader/binding/assemblies/assemblybugs/37910/Ii/Ii.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#38452]
Fails on Linux x64, starting with:

https://dev.azure.com/dnceng/public/_build/results?buildId=705015&view=ms.vss-test-web.build-test-results-tab

This test was introduced with: https://github.com/dotnet/runtime/pull/38016

@jkotas @vitek-karas @viewizard

**Comment by viewizard** [comment]
Error message:
```
\nReturn code: 1\nRaw output file: /home/helixbot/work/B3F80981/w/ABEF0912/e/Loader/binding/Reports/Loader.binding/assemblies/assemblybugs/37910/Ii/Ii.output.txt\nRaw output:\nBEGIN EXECUTION\nin takeLock\nMicrosoft (R) CoreCLR Native Image Generator - Version 5.0.0-ci\nCopyright (c) Microsoft Corporation. All rights reserved.\n\nNative image Ii.dll generated successfully.\n\nin ReleaseLock\nin takeLock\n/home/helixbot/work/B3F80981/p/corerun Ii.dll ''\nFailed! tr_TR.UTF-8 locale was not found in system!\nin ReleaseLock\nExpected: 100\nActual: 255\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/B3F80981/p\n> /home/helixbot/work/B3F80981/w/ABEF0912/e/Loader/binding/assemblies/assemblybugs/37910/Ii/Ii.sh\nExpected: True\nActual: False
```
Wait, I mentioned, that tr_TR.UTF-8 locale must be installed/generated in system.

**Comment by BruceForstall** [comment]
Apparently our CI systems are not configured that way. This test needs to be disabled until they are.

**Comment by jkotas** [comment]
> Wait, I mentioned, that tr_TR.UTF-8 locale must be installed/generated in system.

It is not reasonable to expect that this will be installed on all systems that we want to run the tests on. I have submitted change #38468 to skip the test when this specific locale is not installed. It is the pattern we are using in number of other places.

**Comment by viewizard** [comment]
@jkotas  Yeah, I see now. BTW arm32/arm64 don't have any issues with this test, that mean TR locale installed in that systems, is the any chance install this locale at x64? I mean, could CI with Linux x64 be configured for this locale too in future?

**Comment by jkotas** [comment]
We have variety of setups for the CI runs. I expect that we are always going to have some setups where this locale is not installed.
