### ISSUE TITLE
Consider adding Half support to the BinaryPrimitives class

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#38456]
## Background and Motivation

This came up while working to add `Half` support to the CBOR components. While not blocking to my work, these methods would be nice to have for the sake of completeness.

## Proposed API

```csharp
public static class BinaryPrimitives
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Half ReadHalfLittleEndian(ReadOnlySpan<byte> source);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Half ReadHalfBigEndian(ReadOnlySpan<byte> source);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryReadHalfLittleEndian(ReadOnlySpan<byte> source, out Half);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryReadHalfBigEndian(ReadOnlySpan<byte> source, out Half);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void WriteHalfLittleEndian(Span<byte> destination, Half value);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void WriteHalfBigEndian(Span<byte> destination, Half value);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryWriteHalfLittleEndian(Span<byte> destination, Half value);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryWriteHalfBigEndian(Span<byte> destination, Half value);
}
```

**Comment by GrabYourPitchforks** [comment]
Saw that you also mentioned this in https://github.com/dotnet/runtime/issues/38288. Definitely should do both at the same time. :)

**Comment by GrabYourPitchforks** [comment]
Can we add these to `BinaryReader` and `BinaryWriter` as well? They're useful for throwing data across the wire.

**Comment by terrajobst** [comment]
Looks good

```C#
namespace System.Buffers.Binary
{
    public static class BinaryPrimitives
    {
        public static Half ReadHalfLittleEndian(ReadOnlySpan<byte> source);
        public static Half ReadHalfBigEndian(ReadOnlySpan<byte> source);
        public static bool TryReadHalfLittleEndian(ReadOnlySpan<byte> source, out Half);
        public static bool TryReadHalfBigEndian(ReadOnlySpan<byte> source, out Half);

        public static void WriteHalfLittleEndian(Span<byte> destination, Half value);
        public static void WriteHalfBigEndian(Span<byte> destination, Half value);
        public static bool TryWriteHalfLittleEndian(Span<byte> destination, Half value);
        public static bool TryWriteHalfBigEndian(Span<byte> destination, Half value);
    }
}
```

**Comment by akoeplinger** [comment]
Curious why we need separate *LittleEndian and *BigEndian methods? Is it because I might want to read something in big-endian encoding even though I'm on a little-endian machine so using `BitConverter.IsLittleEndian` internally wouldn't make sense?

**Comment by tannergooding** [comment]
Right, many file formats (for example) explicitly call out themselves as being big or little endian. These methods allow you to do the right thing regardless of what machine you are on.

**Comment by jeffhandley** [comment]
Moved to 6.0.0 per [discussion](https://github.com/dotnet/runtime/pull/40882#issuecomment-680615860) on #40882. Thanks, @huoyaoyuan.

**Comment by xPaw** [comment]
Would you reconsider putting this into 5.0 release? Putting this into 6.0 release makes this new type harder to use imo.

I wanted to switch to using native half type, but the missing methods on BinaryReader make this a bit harder.

**Comment by jkotas** [comment]
.NET 5 API surface is done. We are not able to add this to 5.0 release. If you need the method on BinaryReader for your project, you can add it as internal extension method for now. It should be like ~20 lines.
