### ISSUE TITLE
Struct layout difference with crossgen2

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#38450]
Compile and run the following with crossgen2:

```csharp
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential, Size = 0x14)]
public struct Struct
{
    private long A;
    private long B;
    public int C;
}

class My
{
    unsafe static void Main() {
        Console.WriteLine(sizeof(Struct).ToString());
    }
}
```

Expected result: 20
Actual result  when compiled with crossgen2: 24

**Comment by jkotas** [comment]
Reported by @Thealexbarney https://gitter.im/dotnet/corert?at=5ef56ab654d7862dc4ac20a2

**Comment by tannergooding** [comment]
Is this with 32-bit? I'd expect 24 is correct for 64-bit.

**Comment by jkotas** [comment]
This is on 64-bit.

**Comment by tannergooding** [comment]
I'm confused as why `20` is expected then, the natural packing of `long` is 8, which means the struct needs to be padded to a multiple of 8 so it is correctly laid out for an array.

Does undersizing the type impact packing?

**Comment by tannergooding** [comment]
Hmmm, yeah, it looks like here: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/classlayoutinfo.cpp#L194

The `StructLayout` size must be at least the size of the struct, minus any trailing padding. If a size is given at all, it causes the trailing padding to be removed.

**Comment by jkotas** [comment]
Right, the `StructLayout.Size` says: I want to size of the struct to be exactly this, ignore everything else.
