### ISSUE TITLE
System.Formats.Cbor: Add Reader and Writer methods for System.Half.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#38467]
## Background and Motivation

The CBOR spec requires support for IEEE 754 half-precision floats. Given that we just added System.Half, we should expose reader and writer methods that handle that particular type.

## Proposed API

```csharp
public class CborReader
{
    public void WriteHalf(Half value);
}

public class CborWriter
{
    public Half ReadHalf();
}
```

Relevant implementation PR: https://github.com/dotnet/runtime/pull/38946

**Comment by bartonjs** [comment]
Approved as proposed.

```csharp
public class CborReader
{
    public void WriteHalf(Half value);
}

public class CborWriter
{
    public Half ReadHalf();
}
```
