### ISSUE TITLE
Multiple single exe apps not working under IIS on the same machine

### ISSUE THREAD

**Issue by RomanHubyak** [dotnet/runtime#38472]
I have published a single exe app to IIS and it works as expected.

When I publish another single exe app to the same IIS on the same machine it doesn't work at all. Here are errors:

![image](https://user-images.githubusercontent.com/46841287/77617153-150b3b80-6f3c-11ea-847a-5608a27116a3.png)

![image](https://user-images.githubusercontent.com/46841287/77617187-29e7cf00-6f3c-11ea-822b-1dda8713bf0c.png)

I checked the directory [C:\WINDOWS\TEMP\.net\] and it already exists and contains unpacked first app.

**Comment by romanryasne2** [comment]
@swaroop-sridhar I use Windows 10, .Net Core 3.1. App is exctracted into system-temp directory (C:\Windows\temp\.net).

**Comment by agocke** [comment]
Single-file apps are no longer extracted by-default, so this should be fixed.
