### ISSUE TITLE
Missing runtime prompt does not redirect to the actual runtime

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#3848]
Please excuse me if this is only because .NET Core 3.1 is still in preview but

### Issue
I've tried the new [runtime missing prompt added on .NET Core 3.1](https://github.com/dotnet/core-setup/issues/8368) . A preview 3 compiled WPF app opens this URL:

https://dotnet.microsoft.com/download?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=3.1.0-preview3.19553.2

but instead of landing on the download page with just a single button as I as a developer would expect my end users to land, I visually land on the default download page: https://dotnet.microsoft.com/download

This is a problem for multiple reasons:
1. It shows 3.0 for download but the user needs 3.1. Fixed when 3.1 releases but what if 3.2 or 5.0 releases then it wouldn't match again
2. It shows SDK and Runtime, an end user wouldn't know which to choose
3. Even if he hits runtime, he might downloads the x86 instead but he needs x64.

### Expected:
What I would expect is that it the command prompt opens this URL instead: `https://dotnet.microsoft.com/download/dotnet-core/3.1/runtime/desktop/x64` which points the end user to the only runtime he needs with a single download button, no chance for misunderstandings.

ping @dagood since you were involved in the original issue. Hope thats okay.

**Comment by richlander** [comment]
I implemented this in maybe February. Can folks re-check? It should be working now.

**Comment by NikolaMilosavljevic** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/36765
