### ISSUE TITLE
`System.IO.FileInfo` doesn't throw for invalid paths

### ISSUE THREAD

**Issue by RussKie** [dotnet/runtime#38487]
### Description

I'm porting https://github.com/gitextensions/gitextensions/pull/7162 from .NET Framework 4.6.1 to .NET Core 3.1 and observing a number of tests fail. In particular [tests for functionality that checks validity of user supplied paths](https://github.com/gitextensions/gitextensions/blob/0b00208914c1e126de69fdbf162bc2252113b344/UnitTests/GitCommands.Tests/EnvironmentPathsProviderTests.cs#L30-L38).

The code:
https://github.com/gitextensions/gitextensions/blob/b210331fb67b2362cc1c666ad49911d4666d85e0/GitCommands/EnvironmentPathsProvider.cs#L73-L90

.NET Framework version of `FileInfo` ctor used to throw if `fileName` contains invalid an invalid path, e.g.:
![image](https://user-images.githubusercontent.com/4403806/85924510-2adf2280-b8d6-11ea-9829-baeee25c3bb1.png)

However .NET Core (3.1.200) doesn't throw, despite the docs state it would:
![image](https://user-images.githubusercontent.com/4403806/85924624-cb354700-b8d6-11ea-8eca-1894e510435d.png)

https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=netcore-3.1#exceptions
![image](https://user-images.githubusercontent.com/4403806/85924557-801b3400-b8d6-11ea-8703-58983622a1a9.png)
![image](https://user-images.githubusercontent.com/4403806/85924564-89a49c00-b8d6-11ea-8503-6fee91c8614e.png)

### Configuration

.NET Core 3.1.5 (latest official)
W10 1909 x64

### Regression?

It looks like a regression/breaking change but I couldn't find any docs pertaining to the change (looked [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx) and [here](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo?view=netcore-3.1))

.NET Framework version of the API throws, if an invalid path is passed into ctor
![image](https://user-images.githubusercontent.com/4403806/85924510-2adf2280-b8d6-11ea-9829-baeee25c3bb1.png)

**Comment by RussKie** [comment]
Looks like the same applies to `DirectoryInfo` class too, no more exceptions for invalid paths.

**Comment by Youssef1313** [comment]
@RussKie The resource for that exception message was removed in https://github.com/dotnet/corefx/pull/23851/files, but can't find when this resource became unused.

In .NET Framework, the ctor was making a call to [Init](https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/mscorlib/system/io/fileinfo.cs#L102) which calls `GetFullPathInternal`, which then [calls NormalizePath](https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/mscorlib/system/io/path.cs#L366) that will delegate at some point to [NewNormalizePath](https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/mscorlib/system/io/path.cs#L486), the exception is thrown there.

That's just a quick tracing. Just in case it's useful.

**Comment by Youssef1313** [comment]
I'm wondering if even the behavior you get on .NET Framework is correct? Shouldn't it be NotSupportedException based on docs?

**Comment by vcsjones** [comment]
I believe this is a known breaking change that was introduced in .NET Core 2.1. It was blogged about in the post [System.IO in .NET Core 2.1 sneak peek][1]. Under "Key behavior changes", one of the items is:

> Exceptions for "bad" paths are thrown when _used_, not when normalizing (as we can't know what is "valid" without using them)

In your case, constructing a `FileInfo` doesn't do anything to access the file on disk. However if you attempt to get information about the file, like accessing the `Length` property, it is then it will throw for ill-formed paths.

For example, if I do:

```c#
static void Main() {
    _ = new FileInfo("c::\\word\\").Length;
}
```

That causes an exception:

> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\:\word\'

[1]: https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek

**Comment by RussKie** [comment]
Thank you for your help 👍

**Comment by RussKie** [comment]
The question still remains - who does one definitely check for a given path to be a valid path?
Invoking a property on `FileInfo` instance can get us so far. Some paths are user supplied, some paths are concatenated from bits sourced from various sources, and not all paths necessarily physically present on a hard drive (those may be fed to git). 

E.g. `c:\Programs\Get"\` isn't valid, yet the new `FileInfo` happily creates an object for it.
* .NET 4.6.1
    ![image](https://user-images.githubusercontent.com/4403806/85961477-10986800-b9ee-11ea-9c0f-8152a9dcd47d.png)
* .NET Core 3.1
    ![image](https://user-images.githubusercontent.com/4403806/85961509-37ef3500-b9ee-11ea-882b-58a711a1f388.png)

**Comment by JeremyKuhne** [comment]
The only way to know a path is valid is to actually try to use it. Trying to check for "invalid characters" falls apart in a number of scenarios, notably when using file systems that aren't "normal" for the host OS (and in many other corner cases).  If you really want to check invalid characters you can do that yourself with `Path.InvalidPathChars`, but I wouldn't recommend it outside of recommending not to use a specific filename. That said, it isn't a great filter. I've created some API suggestions for "better" pick-a-good-name helpers, such as #25010, but they never bubbled up to the top of the stack.

The only thing we check for now is embedded nulls as most OS APIs work off of null terminated strings and understanding the results in this case would be difficult. There is also likely some creative security holes with embedded nulls but I haven't spent a great deal of time thinking that angle through (would make it difficult to compare paths for containment).

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/docs/issues/20004
