### ISSUE TITLE
Test failure: JIT\\SIMD\\MinMax_ro\\MinMax_ro.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#38496]
failed in job: [ runtime-coreclr jitstress-isas-x86 20200627.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=707975&view=ms.vss-test-web.build-test-results-tab&runId=21935156&resultId=108131&paneView=debug)

Error message
~~~
Assert failure(PID 8652 [0x000021cc], Thread: 7612 [0x1dbc]): Assertion failed 'kind == Overwrite' in 'VectorMathTests.Program:Main(System.String[]):int' during 'Per block local var liveness' (IL size 112)

 File: F:\workspace\_work\1\s\src\coreclr\src\jit\jithashtable.h Line: 270
 Image: C:\h\w\BAFD09F6\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\BAFD09F6\w\A0EA0904\e\JIT\SIMD\Reports\JIT.SIMD\MinMax_ro\MinMax_ro.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\BAFD09F6\p\corerun.exe" MinMax_ro.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\BAFD09F6\p
> C:\h\w\BAFD09F6\w\A0EA0904\e\JIT\SIMD\MinMax_ro\MinMax_ro.cmd
Expected: True
Actual: False


Stack trace
   at JIT_SIMD._MinMax_ro_MinMax_ro_._MinMax_ro_MinMax_ro_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\JIT.SIMD\JIT.SIMD.XUnitWrapper.cs:line 3438
~~~

**Comment by BruceForstall** [comment]
In `CoreCLR Windows_NT x86 Checked jitstress_isas_x86_nohwintrinsic @ Windows.10.Amd64.Open`

@tannergooding @CarolEidt

**Comment by tannergooding** [comment]
Looks like this may have been introduced in the last week as it wasn't failing in [20200620.1](https://dev.azure.com/dnceng/public/_build/results?buildId=697391&view=ms.vss-test-web.build-test-results-tab)

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib looks like a liveness change affected SIMD test. @erozenfeld maybe your recent liveness-related changes?

**Comment by erozenfeld** [comment]
Could be. Will take a look tomorrow.
