### ISSUE TITLE
System.IO.DirectoryInfo.MoveTo() does not support cross-device moves, but System.IO.FileInfo.MoveTo() does

### ISSUE THREAD

**Issue by rjmholt** [dotnet/runtime#38504]
### Description

From https://github.com/PowerShell/PowerShell/issues/13039.

When moving a directory, .NET simply uses the [`rename` syscall](https://man7.org/linux/man-pages/man2/rename.2.html), which fails with error `EXDEV` when applied across mount boundaries:

https://github.com/dotnet/runtime/blob/4965d3463cd3e65d59cb2ce59e5ce4a4cf2b4b94/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L385-L393

You can find the native implementation here:

https://github.com/dotnet/runtime/blob/a547d4178cd2d71d9b6a7a99600e20a3211d4436/src/libraries/Native/Unix/System.Native/pal_io.c#L994-L999

This could make sense if the `MoveTo` is intended to be a more primitive operation that does not handle copy+delete functionality, but in System.IO.FileInfo, that's not the case:

https://github.com/dotnet/runtime/blob/4965d3463cd3e65d59cb2ce59e5ce4a4cf2b4b94/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L190-L194

Handling this at the caller level is made trickier because while the error thrown on Unix contains the `EXDEV` HResult and so can be handled, the error thrown on Windows is too generic, meaning a different test needs to be used for copy+delete.

The error on Linux:

```
TargetSite     : Void MoveDirectory(System.String, System.String)
StackTrace     :    at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
                    at System.IO.DirectoryInfo.MoveTo(String destDirName)
                    at CallSite.Target(Closure , CallSite , Object , String )
Message        : Invalid cross-device link
Data           : {}
InnerException :
HelpLink       :
Source         : System.IO.FileSystem
HResult        : 18
```

And on Windows:

```
Type           : System.IO.IOException
TargetSite     : Void MoveTo(System.String)
StackTrace     :    at System.IO.DirectoryInfo.MoveTo(String destDirName)
                    at CallSite.Target(Closure , CallSite , Object , String )
Message        : Source and destination path must have identical roots. Move will not work across
                 volumes.
Data           : {}
InnerException :
HelpLink       :
Source         : System.IO.FileSystem
HResult        : -2146232800
```

Given that .NET has more information about the implementation details and that `FileInfo.MoveTo()` already handles cross-device moves, it feels like this is something best handled by .NET rather than by callers.

### Configuration

- .NET Core 3.1
- Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

### Regression?

Not as far as I know.

**Comment by vcsjones** [comment]
I believe #31149 is caused by the same issue. There's some more background and discussion that I think is useful.

**Comment by rjmholt** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/31149
