### ISSUE TITLE
It is not possible to change Proxy to an HttpClient that has already started

### ISSUE THREAD

**Issue by M-Boukhlouf** [dotnet/runtime#38526]
I keep hearing that HttpClient object has some high startup costs and that it is recommended to create only one instance and keep using throughout the program. Yet, it is not possible to change the Proxy of the HttpClient by changing the Proxy property of the HttpClientHandler object with which it was instantiated. There is a method that checks if the HttpClient has already started or sent a request, and if it did, it throws an InvalidOperationException.
If I have to change the proxy while keeping the session and any other properties, I would have to save the cookie container and properties like timeout, and use them when recreating a new HttpClient.  
Like this:
```csharp
        public IWebProxy Proxy
        {
            get
            {
                return httpClientHandler.Proxy;
            }
            set
            {
                if (Proxy != value)
                {
                    try
                    {

                        httpClientHandler.Proxy = value;
                    }
                    catch (InvalidOperationException)
                    {
                        var cookieContainer = httpClientHandler.CookieContainer;
                        var timeout = httpClient.Timeout;

                        httpClient.Dispose();
                        httpClientHandler.Dispose();

                        httpClientHandler = new HttpClientHandler()
                        {
                            UseCookies = true,
                            AllowAutoRedirect = false,
                            Proxy = value,
                            CookieContainer = cookieContainer
                        };

                        httpClient = new HttpClient(httpClientHandler)
                        {
                            Timeout = timeout
                        };
                        httpClient.Timeout = timeout;
                    }
                }
            }
        }
```

Why can't it be just like this:
```csharp
        public IWebProxy Proxy
        {
            get
            {
                return httpClientHandler.Proxy;
            }
            set
            {
                if (Proxy != value)
                {
                    httpClientHandler.Proxy = value;
                }
            }
        }
```

**Comment by stephentoub** [comment]
What are you changing it to?

Keep in mind that am IWebProxy is handed the Uri and gets to give back the proxy to use for that Uri, so the IWebProxy itself can change its behavior at will, and can be mutated however you want your implementation to be mutated.

And if you actually do want different IWebProxy instances, you can just have multiple HttpClients... just keep one around for each IWebProxy.

**Comment by M-Boukhlouf** [comment]
> What are you changing it to?
> 
> Keep in mind that an IWebProxy is handed the Uri and gets to give back the proxy address to use for that Uri, so the IWebProxy itself can change its behavior at will, and can be mutated however you want your implementation to be mutated.
> 
> And if you actually do want different IWebProxy instances, you can just have multiple HttpClients... just keep one around for each IWebProxy.
> 
> And finally, if you really do want the behavior of changing the proxy because you don't want to reuse connections for future requests, well, that's the overhead folks refer to when talking about reusing an HttpClient instance.
Thank you for your reply. I remember I read your article about ConfigureAwait, very informative.
I'm changing it to a WebProxy. 
You mean that I can create a class that implements IWebProxy, and wrap a proxy inside, so if I want to change the proxy, I just change inside this new class?

**Comment by stephentoub** [comment]
Yup, that should work :)

**Comment by geoffkizer** [comment]
Just to provide some additional guidance:

> I keep hearing that HttpClient object has some high startup costs and that it is recommended to create only one instance and keep using throughout the program. 

There's no need to limit yourself to only 1 HttpClient. If you have different configuration needs (as in this case, with multiple proxies in use), it's fine to create a handful of HttpClient instances for these different configurations and use the appropriate HttpClient instance as necessary.

What you should avoid doing is creating a new HttpClient instance for every request. 

HttpClient by itself has minimal startup costs. The issue is that connections are not shared across different instances of HttpClient. But if you're using different proxies, then you are not sharing connections anyway.

**Comment by M-Boukhlouf** [comment]
> Yup, that should work :)

Thank you

**Comment by M-Boukhlouf** [comment]
> Just to provide some additional guidance:
> 
> > I keep hearing that HttpClient object has some high startup costs and that it is recommended to create only one instance and keep using throughout the program.
> 
> There's no need to limit yourself to only 1 HttpClient. If you have different configuration needs (as in this case, with multiple proxies in use), it's fine to create a handful of HttpClient instances for these different configurations and use the appropriate HttpClient instance as necessary.
> 
> What you should avoid doing is creating a new HttpClient instance for every request.
> 
> HttpClient by itself has minimal startup costs. The issue is that connections are not shared across different instances of HttpClient. But if you're using different proxies, then you are not sharing connections anyway.

Thank you
