### ISSUE TITLE
Inconsistency of the 'CanRead' property after disposing of an HTTP content stream

### ISSUE THREAD

**Issue by angelobreuer** [dotnet/runtime#38527]
### Description

There is an inconsistency of the [`CanRead`](https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs#L21) property after disposing of an HTTP client content stream that inherits from [HttpContentReadStream](https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs).

I think the [`CanRead`](https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs#L21) property should return `false` after the HTTP client content stream has been disposed.

### Configuration
Reproduced in netcoreapp3.1, SDK version 3.1.400-preview-015178

### Regression

For example the following test passes:
```csharp
using var httpClient = new HttpClient();
using var response = await httpClient.GetAsync("https://github.com/dotnet/runtime");
var responseStream = await response.Content.ReadAsStreamAsync(); // --> System.IO.MemoryStream

Assert.True(responseStream.CanRead); // Passes
responseStream.Dispose();
Assert.False(responseStream.CanRead); // Passes
```

The same test with specifying [`HttpCompletionOption.ResponseHeadersRead`](https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/HttpCompletionOption.cs#L14) fails:

```csharp
using var httpClient = new HttpClient();
using var response = await httpClient.GetAsync("https://github.com/dotnet/runtime", HttpCompletionOption.ResponseHeadersRead);
var responseStream = await response.Content.ReadAsStreamAsync(); // --> System.Net.Http.HttpConnection.ChunkedEncodingReadStream or System.Net.Http.HttpConnection.ContentLengthReadStream

Assert.True(responseStream.CanRead); // Passes
responseStream.Dispose();
Assert.False(responseStream.CanRead); // FAILS!
```

Or with using [`HttpClient#GetStreamAsync()`](https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L257) directly, also fails:

```csharp
using var httpClient = new HttpClient();
var responseStream = await httpClient.GetStreamAsync("https://github.com/dotnet/runtime"); // --> System.Net.Http.HttpConnection.ChunkedEncodingReadStream or System.Net.Http.HttpConnection.ContentLengthReadStream

Assert.True(responseStream.CanRead); // Passes
responseStream.Dispose();
Assert.False(responseStream.CanRead); // FAILS!
```

The [`CanRead`](https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs#L21) property is defined as:

https://github.com/dotnet/runtime/blob/4ef07c29d0d339a60ebf90de479d1f90fa2e6ae7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs#L21

**Comment by stephentoub** [comment]
> I think the CanRead property should return false after the HTTP client content stream has been disposed.

In what situation are you using the object after it's been Disposed?  In general in .NET, most contracts are no longer considered valid on a disposed object.

**Comment by angelobreuer** [comment]
Hello @stephentoub,
thanks for your response!

> In what situation are you using the object after it's been Disposed? 

I have no specific issue in my code this issue is related to. I just came across this issue while debugging.

> In general in .NET, most contracts are no longer considered valid on a disposed object.

I just thought that streams should return false for [`CanRead`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canread?view=netcore-3.1), [`CanSeek`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=netcore-3.1), and [`CanWrite`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canwrite?view=netcore-3.1) after disposal as stated in the official MSDN documentation for the Stream class in the [Remarks section](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canread?view=netcore-3.1#remarks):
> Remarks
> If a class derived from Stream does not support reading, calls to the Read, ReadByte, and BeginRead methods throw a NotSupportedException.
> __If the stream is closed, this property returns false.__ 

Note: I think that the [`CanTimeout`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.cantimeout) property does not follow this behavior because it is not explicitly mentioned like the other properties in the official MSDN [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.cantimeout?view=netcore-3.1#remarks).

Also, most of the stream implementations in .NET return `false` after they were disposed: [MemoryStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream?view=netcore-3.1), [DeflateStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream?view=netcore-3.1), [GZipStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.gzipstream?view=netcore-3.1), [BufferedStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.bufferedstream?view=netcore-3.1), [FileStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream?view=netcore-3.1), [BrotliStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.brotlistream?view=netcore-3.1), [CryptoStream](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptostream?view=netcore-3.1), and so on.

Other stream types redirect the [`CanRead`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canread?view=netcore-3.1) to the inner base stream, for example, [NegotiateStream](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.negotiatestream?view=netcore-3.1) (see [here](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Security/src/System/Net/Security/NegotiateStream.cs#L266)).

**Comment by angelobreuer** [comment]
Resolved via https://github.com/dotnet/runtime/pull/43766
