### ISSUE TITLE
Linux arm/arm64/x64 GCStress=3 time out failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#38523]
I see the following tests fail with timeout under GCStress=3 for Linux arm/arm64/x64:

```
profiler/eventpipe/eventpipe_readevents/eventpipe_readevents.sh
profiler/eventpipe/eventpipe/eventpipe.sh
profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.sh
profiler/unittest/metadatagetdispenser/metadatagetdispenser.sh
profiler/rejit/rejit/rejit.sh
profiler/gc/gc/gc.sh
JIT/Generics/Exceptions/general_class_instance01/general_class_instance01.sh
JIT/Generics/Exceptions/general_struct_instance01/general_struct_instance01.sh
JIT/Generics/Exceptions/general_class_static01/general_class_static01.sh
JIT/Generics/Exceptions/general_struct_static01/general_struct_static01.sh
Interop/DllImportAttribute/DllImportPath/DllImportPathTest/DllImportPathTest.sh
```

https://dev.azure.com/dnceng/public/_build/results?buildId=708505&view=ms.vss-test-web.build-test-results-tab&runId=21947356&resultId=109001&paneView=debug

Related: https://github.com/dotnet/runtime/issues/38522

Should the timeout be raised? (by how much)

Are there real bugs here?

Should they be disabled under GCStress? (seems like a last resort)

**Comment by BruceForstall** [comment]
@janvorli

**Comment by josalem** [comment]
CC @davmason for profiler tests

**Comment by davmason** [comment]
The profiler tests often cause a lot of GCs to happen, and don't do anything particularly interesting in managed code. I think the best avenue is to opt out of GCStress for the ones that time out.

**Comment by mangod9** [comment]
Given the comment above, ok to move to 6?

**Comment by davmason** [comment]
As far as the profiler tests are concerned the issue can be closed, I can't speak for the jit or interop tests though. Turning off GCStress is a permanent thing for these tests.

**Comment by mangod9** [comment]
Since the related issue is closed around the Finalizer thread running in a loop, closing this assuming that should fix this too.
