### ISSUE TITLE
What does EE means in string.cs file?

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/runtime#38545]
What does `EE` means in [String](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/String.cs) comment?

```c#
public sealed partial class String : IComparable, IEnumerable, IConvertible, IEnumerable<char>, IComparable<string?>, IEquatable<string?>, ICloneable
{
    //
    // These fields map directly onto the fields in an EE StringObject.  See object.h for the layout.
    //
    [NonSerialized]
    private readonly int _stringLength;
}
```

---

![String.Empty](https://user-images.githubusercontent.com/11468733/85995252-a523ba00-ba30-11ea-8a96-26ed059b82c6.png)

> The definition of **String.Empty** was not found in this repository. The screenshot is from https://referencesource.microsoft.com/#mscorlib/system/string.cs

Thanks.

**Comment by gintsk** [comment]
Execution Engine
https://stackoverflow.com/a/25917242

**Comment by Youssef1313** [comment]
Check [this SO question](https://stackoverflow.com/questions/25917189/).

**Comment by omajid** [comment]
CoreCLR also has several documents that help define what an EE is: https://github.com/dotnet/runtime/search?l=Markdown&q=Execution+Engine

**Comment by danmosemsft** [comment]
```
The runtime itself is
--
23 | variously called the EE (execution engine), the VM (virtual machine), or simply the CLR (common language runtime).
```
Probably https://github.com/dotnet/runtime/blob/a21da8f6d945002bbb7cdb426c148867f60be528/docs/project/glossary.md should make clear that "Virtual Machine" is not being used in the normal sense (which I think was not commonly used when the term likely arose in ~2000)

**Comment by danmosemsft** [comment]
I think this is answered, unless @jkotas you believe there is value in trying to settle on a single term (that perhaps covers Mono also)

**Comment by jkotas** [comment]
Both "execution engine" and "virtual machine" are used interchangeably, for both CoreCLR and Mono. I do not see the value in unification.

**Comment by danmosemsft** [comment]
@CwjXFH if you like, feel free to offer a PR to improve glossary.md.
