### ISSUE TITLE
Markdown: unused definitions found

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#38549]
```command
> remark --quiet --use lint-no-unused-definitions .
docs\coding-guidelines\clr-code-guide.md
    108:1-108:91  warning  Found unused definition  no-unused-definitions  remark-lint
    241:1-241:98  warning  Found unused definition  no-unused-definitions  remark-lint
    242:1-242:96  warning  Found unused definition  no-unused-definitions  remark-lint
    554:1-554:87  warning  Found unused definition  no-unused-definitions  remark-lint
    719:1-719:89  warning  Found unused definition  no-unused-definitions  remark-lint
    825:1-825:82  warning  Found unused definition  no-unused-definitions  remark-lint
  1146:1-1146:91  warning  Found unused definition  no-unused-definitions  remark-lint

docs\design\coreclr\botr\corelib.md
    290:1-290:90  warning  Found unused definition  no-unused-definitions  remark-lint
    352:1-352:86  warning  Found unused definition  no-unused-definitions  remark-lint

docs\design\features\source-generator-pinvokes.md
    217:1-217:67  warning  Found unused definition  no-unused-definitions  remark-lint

docs\project\glossary.md
    353:1-353:39  warning  Found unused definition  no-unused-definitions  remark-lint
    354:1-354:62  warning  Found unused definition  no-unused-definitions  remark-lint

‼ 12 warnings
```

**Comment by danmosemsft** [comment]
@xtqqczze do you want to offer a PR? I thought I got the markdown clean, but maybe it's regressed or you have a different linter.

**Comment by xtqqczze** [comment]
@danmosemsft I used [remark-lint-no-unused-definitions](https://www.npmjs.com/package/remark-lint-no-unused-definitions). Does the repo currently run any linters on CI?

**Comment by danmosemsft** [comment]
Not for markdown. But we could, if it was easy and reliable (and flagged impactful issues eg broken links)
Maybe https://github.com/github/super-linter could help?

**Comment by xtqqczze** [comment]
@danmosemsft I have two PRs to resolve these linter warnings. #38618 removes unused definitions and #38619 resolves false positives.

**Comment by xtqqczze** [comment]
@danmosemsft [super-linter](https://github.com/github/super-linter) looks like it has [a lot of dependencies](https://github.com/github/super-linter/blob/master/Dockerfile), we could just use an action based on [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) (this is what super-linter does).

**Comment by danmosemsft** [comment]
@xtqqczze as mentioned above, to add a linter it would at a minimum have to be totally reliable, and it would have to flag issues we care about (some markdown lint issues are things like inconsistent indent of headings which make no visual difference). If you think we should consider markdownlint-cli perhaps you could open a new issue to discuss.

**Comment by xtqqczze** [comment]
We would first need to replace invalid inline HTML like `<a name="register" />` (see #38619). Otherwise, we cannot be sure to avoid false positives.
