### ISSUE TITLE
Browser Implementation For various assemblies

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#38559]
I will be filling the implementation details as the work goes on
@marek-safar @akoeplinger , i tried to summarize the implementation for each of the proj, can you guys take a look at the list and check if we need to make any changes ?

cc @ericstj 

Validated | ProjectName  | Implementation Detail  | Comments   |
|---|---|---|---|
|:heavy_check_mark:|Microsoft.CSharp|ridless||
|:heavy_check_mark:|Microsoft.Diagnostics.Tracing.EventSource.Redist|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Caching.Abstractions|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Caching.Memory|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.Abstractions|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.Binder|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.CommandLine|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.EnvironmentVariables|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.FileExtensions|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.Ini|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.Json|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.UserSecrets|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Configuration.Xml|ridless||
|:heavy_check_mark:|Microsoft.Extensions.DependencyInjection|ridless||
|:heavy_check_mark:|Microsoft.Extensions.DependencyInjection.Abstractions|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.DependencyModel|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.FileProviders.Abstractions|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.FileProviders.Composite|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.FileProviders.Physical|netstandard| Effectively PNSE b/c of FSW |
|:heavy_check_mark:|Microsoft.Extensions.FileSystemGlobbing|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Hosting|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Hosting.Abstractions|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Http|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Logging|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Logging.Abstractions|netstandard||
|:heavy_check_mark:|Microsoft.Extensions.Logging.Configuration|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Logging.Console|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Logging.Debug|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Logging.EventLog|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Logging.EventSource|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Logging.TraceSource|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Options|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Options.ConfigurationExtensions|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Options.DataAnnotations|ridless||
|:heavy_check_mark:|Microsoft.Extensions.Primitives|ridless||
|:heavy_check_mark:|Microsoft.IO.Redist|netstandard||
|:heavy_check_mark:|Microsoft.Win32.Primitives|PNSE||
|:heavy_check_mark:|Microsoft.Win32.Registry|Unix Implementation||
|:heavy_check_mark:|Microsoft.Win32.Registry.AccessControl|netstandard||
|:heavy_check_mark:|Microsoft.Win32.SystemEvents|netstandard||
|:heavy_check_mark:|Microsoft.XmlSerializer.Generator|netstandard||
|:heavy_check_mark:|Microsoft.VisualBasic|netstandard||
|:heavy_check_mark:|mscorlib|netstandard||
|:heavy_check_mark:|netstandard|netstandard||
|:heavy_check_mark:|System.ComponentModel.DataAnnotations|netstandard||
|:heavy_check_mark:|System.Configuration|netstandard||
|:heavy_check_mark:|System.Core|netstandard||
|:heavy_check_mark:|System|netstandard||
|:heavy_check_mark:|System.Data|netstandard||
|:heavy_check_mark:|System.Drawing|netstandard||
|:heavy_check_mark:|System.IO.Compression.FileSystem|netstandard||
|:heavy_check_mark:|System.Net|netstandard||
|:heavy_check_mark:|System.Numerics|netstandard||
|:heavy_check_mark:|System.Runtime.Serialization|netstandard||
|:heavy_check_mark:|System.Security|netstandard||
|:heavy_check_mark:|System.ServiceModel.Web|netstandard||
|:heavy_check_mark:|System.ServiceProcess|netstandard||
|:heavy_check_mark:|System.Transactions|netstandard||
|:heavy_check_mark:|System.Web|netstandard||
|:heavy_check_mark:|System.Windows|netstandard||
|:heavy_check_mark:|System.Xml|netstandard||
|:heavy_check_mark:|System.Xml.Linq|netstandard||
|:heavy_check_mark:|System.Xml.Serialization|netstandard||
|:heavy_check_mark:|WindowsBase|netstandard||
|:heavy_check_mark:|mscorlib|netstandard||
|:heavy_check_mark:|System|netstandard||
|:heavy_check_mark:|System.Data|netstandard||
|:heavy_check_mark:|System.Xml|netstandard||
|:heavy_check_mark:|System.AppContext|ridless||
|:heavy_check_mark:|System.Buffers|ridless||
|:heavy_check_mark:|System.CodeDom|netstandard||
|:heavy_check_mark:|System.Collections|ridless||
|:heavy_check_mark:|System.Collections.Concurrent|ridless||
|:heavy_check_mark:|System.Collections.Immutable|ridless||
|:heavy_check_mark:|System.Collections.NonGeneric|ridless||
|:heavy_check_mark:|System.Collections.Specialized|ridless||
|:heavy_check_mark:|System.ComponentModel|ridless||
|:heavy_check_mark:|System.ComponentModel.Annotations|netstandard||
|:heavy_check_mark:|System.ComponentModel.Composition|ridless||
|:heavy_check_mark:|System.ComponentModel.Composition.Registration|netstandard||
|:heavy_check_mark:|System.ComponentModel.EventBasedAsync|ridless||
|:heavy_check_mark:|System.ComponentModel.Primitives|ridless||
|:heavy_check_mark:|System.ComponentModel.TypeConverter|ridless||
|:heavy_check_mark:|System.Composition.AttributedModel|netstandard||
|:heavy_check_mark:|System.Composition.Convention|netstandard||
|:heavy_check_mark:|System.Composition.Hosting|netstandard||
|:heavy_check_mark:|System.Composition.Runtime|netstandard||
|:heavy_check_mark:|System.Composition.TypedParts|netstandard||
|:heavy_check_mark:|System.Configuration.ConfigurationManager|netstandard||
|:heavy_check_mark:|System.Console|Browser specific||
|:heavy_check_mark:|System.Data.Common|ridless||
|:heavy_check_mark:|System.Data.DataSetExtensions|ridless||
|:heavy_check_mark:|System.Data.Odbc|netstandard (PNSE)||
|:heavy_check_mark:|System.Data.OleDb|netstandard|netstandard (PNSE)|
|:heavy_check_mark:|System.Diagnostics.Contracts|ridless||
|:heavy_check_mark:|System.Diagnostics.Debug|ridless||
|:heavy_check_mark:|System.Diagnostics.DiagnosticSource|ridless||
|:heavy_check_mark:|System.Diagnostics.EventLog|netstandard||
|:heavy_check_mark:|System.Diagnostics.FileVersionInfo|PNSE||
|:heavy_check_mark:|System.Diagnostics.PerformanceCounter|netstandard||
|:heavy_check_mark:|System.Diagnostics.Process|PNSE||
|:heavy_check_mark:|System.Diagnostics.StackTrace|ridless||
|:heavy_check_mark:|System.Diagnostics.TextWriterTraceListener|ridless||
|:heavy_check_mark:|System.Diagnostics.Tools|ridless||
|:heavy_check_mark:|System.Diagnostics.TraceSource|Unix specific||
|:heavy_check_mark:|System.Diagnostics.Tracing|ridless||
|:heavy_check_mark:|System.DirectoryServices|netstandard||
|:heavy_check_mark:|System.DirectoryServices.AccountManagement|netstandard||
|:heavy_check_mark:|System.DirectoryServices.Protocols|Unix Implemenation|netstandard/PNSE|
|:heavy_check_mark:|System.Drawing.Common|Unix Implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Drawing.Primitives|ridless||
|:heavy_check_mark:|System.Dynamic.Runtime|ridless||
|:heavy_check_mark:|System.Formats.Asn1|netstandard||
|:heavy_check_mark:|System.Formats.Cbor|ridless||
|:heavy_check_mark:|System.Globalization|ridless||
|:heavy_check_mark:|System.Globalization.Calendars|ridless||
|:heavy_check_mark:|System.Globalization.Extensions|ridless||
|:heavy_check_mark:|System.IO|ridless||
|:heavy_check_mark:|System.IO.Compression|Unix Implementation||
|:heavy_check_mark:|System.IO.Compression.Brotli|PNSE||
|:heavy_check_mark:|System.IO.Compression.ZipFile|ridless||
|:heavy_check_mark:|System.IO.FileSystem|Unix implemenation|PAL may need tweaks|
|:heavy_check_mark:|System.IO.FileSystem.AccessControl|netstandard||
|:heavy_check_mark:|System.IO.FileSystem.DriveInfo|Browser Specific||
|:heavy_check_mark:|System.IO.FileSystem.Primitives|ridless||
|:heavy_check_mark:|System.IO.FileSystem.Watcher|PNSE||
|:heavy_check_mark:|System.IO.IsolatedStorage|PNSE||
|:heavy_check_mark:|System.IO.MemoryMappedFiles|Unix Implementation|Some browser tweaks needed.|
|:heavy_check_mark:|System.IO.Packaging|netstandard||
|:heavy_check_mark:|System.IO.Pipelines|ridless||
|:heavy_check_mark:|System.IO.Pipes|Unix Implementation|netstandard/PNSE|
|:heavy_check_mark:|System.IO.Pipes.AccessControl|ridless||
|:heavy_check_mark:|System.IO.Ports|netstandard||
|:heavy_check_mark:|System.IO.UnmanagedMemoryStream|ridless||
|:heavy_check_mark:|System.Linq|ridless||
|:heavy_check_mark:|System.Linq.Expressions|ridless||
|:heavy_check_mark:|System.Linq.Parallel|ridless||
|:heavy_check_mark:|System.Linq.Queryable|ridless||
|:heavy_check_mark:|System.Management|netstandard||
|:heavy_check_mark:|System.Memory|ridless||
|:heavy_check_mark:|System.Net.Http|Linux specific|Browser|
|:heavy_check_mark:|System.Net.Http.Json|ridless||
|:heavy_check_mark:|System.Net.Http.WinHttpHandler|netstandard||
|:heavy_check_mark:|System.Net.HttpListener|unix implementation |netstandard/PNSE|
|:heavy_check_mark:|System.Net.Mail|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.NameResolution|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.NetworkInformation|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.Ping|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.Primitives|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.Requests|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.Security|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.ServicePoint|ridless||
|:heavy_check_mark:|System.Net.Sockets|unix implementation|netstandard/PNSE|
|:heavy_check_mark:|System.Net.WebClient|ridless|PNSE|
|:heavy_check_mark:|System.Net.WebHeaderCollection|ridless||
|:heavy_check_mark:|System.Net.WebProxy|ridless||
|:heavy_check_mark:|System.Net.WebSockets|ridless||
|:heavy_check_mark:|System.Net.WebSockets.Client|ridless||
|:heavy_check_mark:|System.Net.WebSockets.WebSocketProtocol|ridless||
|:heavy_check_mark:|System.Numerics.Tensors|netstandard||
|:heavy_check_mark:|System.Numerics.Vectors|ridless||
|:heavy_check_mark:|System.ObjectModel|ridless||
|:heavy_check_mark:|System.Private.DataContractSerialization|ridless||
|:heavy_check_mark:|System.Private.Uri|ridless||
|:heavy_check_mark:|System.Private.Xml|ridless||
|:heavy_check_mark:|System.Private.Xml.Linq|ridless||
|:heavy_check_mark:|System.Reflection|ridless||
|:heavy_check_mark:|System.Reflection.Context|netstandard||
|:heavy_check_mark:|System.Reflection.DispatchProxy|ridless||
|:heavy_check_mark:|System.Reflection.Emit|ridless||
|:heavy_check_mark:|System.Reflection.Emit.ILGeneration|ridless||
|:heavy_check_mark:|System.Reflection.Emit.Lightweight|ridless||
|:heavy_check_mark:|System.Reflection.Extensions|ridless||
|:heavy_check_mark:|System.Reflection.Metadata|ridless||
|:heavy_check_mark:|System.Reflection.MetadataLoadContext|ridless||
|:heavy_check_mark:|System.Reflection.Primitives|ridless||
|:heavy_check_mark:|System.Reflection.TypeExtensions|ridless||
|:heavy_check_mark:|System.Resources.Extensions|netstandard||
|:heavy_check_mark:|System.Resources.Reader|ridless||
|:heavy_check_mark:|System.Resources.ResourceManager|ridless||
|:heavy_check_mark:|System.Resources.Writer|ridless||
|:heavy_check_mark:|System.Runtime|ridless||
|:heavy_check_mark:|System.Runtime.Caching|netstandard||
|:heavy_check_mark:|System.Runtime.CompilerServices.VisualC|ridless||
|:heavy_check_mark:|System.Runtime.Extensions|ridless||
|:heavy_check_mark:|System.Runtime.Handles|ridless||
|:heavy_check_mark:|System.Runtime.InteropServices|ridless||
|:heavy_check_mark:|System.Runtime.InteropServices.JavaScript|netstandard||
|:heavy_check_mark:|System.Runtime.InteropServices.RuntimeInformation|netstandard||
|:heavy_check_mark:|System.Runtime.Intrinsics|ridless||
|:heavy_check_mark:|System.Runtime.Loader|ridless||
|:heavy_check_mark:|System.Runtime.Numerics|ridless||
|:heavy_check_mark:|System.Runtime.Serialization.Formatters|ridless||
|:heavy_check_mark:|System.Runtime.Serialization.Json|ridless||
|:heavy_check_mark:|System.Runtime.Serialization.Primitives|ridless||
|:heavy_check_mark:|System.Runtime.Serialization.Xml|ridless||
|:heavy_check_mark:|System.Security.AccessControl|netstandard||
|:heavy_check_mark:|System.Security.Claims|ridless||
|:heavy_check_mark:|System.Security.Cryptography.Algorithms|netstandard||
|:heavy_check_mark:|System.Security.Cryptography.Cng|ridless||
|:heavy_check_mark:|System.Security.Cryptography.Csp|PNSE||
|:heavy_check_mark:|System.Security.Cryptography.Encoding|PNSE||
|:heavy_check_mark:|System.Security.Cryptography.OpenSsl|PNSE||
|:heavy_check_mark:|System.Security.Cryptography.Pkcs|ridless||
|:heavy_check_mark:|System.Security.Cryptography.Primitives|ridless||
|:heavy_check_mark:|System.Security.Cryptography.ProtectedData|netstandard||
|:heavy_check_mark:|System.Security.Cryptography.X509Certificates|PNSE||
|:heavy_check_mark:|System.Security.Cryptography.Xml|netstandard||
|:heavy_check_mark:|System.Security.Permissions|ridless||
|:heavy_check_mark:|System.Security.Principal|ridless||
|:heavy_check_mark:|System.Security.Principal.Windows|netstandard||
|:heavy_check_mark:|System.Security.SecureString|ridless||
|:heavy_check_mark:|System.ServiceModel.Syndication|netstandard||
|:heavy_check_mark:|System.ServiceProcess.ServiceController|netstandard||
|:heavy_check_mark:|System.Text.Encoding|ridless||
|:heavy_check_mark:|System.Text.Encoding.CodePages|ridless||
|:heavy_check_mark:|System.Text.Encoding.Extensions|ridless||
|:heavy_check_mark:|System.Text.Encodings.Web|ridless||
|:heavy_check_mark:|System.Text.Json|ridless||
|:heavy_check_mark:|System.Text.RegularExpressions|ridless||
|:heavy_check_mark:|System.Threading|ridless||
|:heavy_check_mark:|System.Threading.AccessControl|netstandard||
|:heavy_check_mark:|System.Threading.Channels|ridless||
|:heavy_check_mark:|System.Threading.Overlapped|ridless||
|:heavy_check_mark:|System.Threading.Tasks|ridless||
|:heavy_check_mark:|System.Threading.Tasks.Dataflow|netstandard||
|:heavy_check_mark:|System.Threading.Tasks.Extensions|ridless||
|:heavy_check_mark:|System.Threading.Tasks.Parallel|ridless||
|:heavy_check_mark:|System.Threading.Thread|ridless||
|:heavy_check_mark:|System.Threading.ThreadPool|ridless||
|:heavy_check_mark:|System.Threading.Timer|ridless||
|:heavy_check_mark:|System.Transactions.Local|ridless||
|:heavy_check_mark:|System.Utf8String.Experimental|ridless||
|:heavy_check_mark:|System.ValueTuple|ridless||
|:heavy_check_mark:|System.Web.HttpUtility|ridless||
|:heavy_check_mark:|System.Windows.Extensions|ridless||
|:heavy_check_mark:|System.Xml.ReaderWriter|ridless||
|:heavy_check_mark:|System.Xml.XDocument|ridless||
|:heavy_check_mark:|System.Xml.XmlDocument|ridless||
|:heavy_check_mark:|System.Xml.XmlSerializer|ridless||
|:heavy_check_mark:|System.Xml.XPath|ridless||
|:heavy_check_mark:|System.Xml.XPath.XDocument|ridless||
|:heavy_check_mark:|GenDefinedCharList|netstandard||
|:heavy_check_mark:|GenUnicodeRanges|netstandard||

**Comment by ericstj** [comment]
Maybe we can omit everything that isn't changing.  Only list the things we aim to change, so it should be a list that's 20-40 items.

**Comment by marek-safar** [comment]
I did first pass and added comments on what will most likely need to change. I don't think we should hold original PR as there are/will be PRs addressing this on per assembly basis as we enable more tests.

/cc @steveisok @MaximLipnin @mdh1418

**Comment by ViktorHofer** [comment]
Triage: @steveisok will update the table. We might want to add a column to track completeness.

**Comment by VSadov** [comment]
I pushed a rebased branch and github did autoclose. Probably because there is a commit that claims to be resolving this.

**Comment by steveisok** [comment]
I think we're in good shape here

**Comment by marek-safar** [comment]
Closing as we are in good shape and any follow up will be handled on per assembly level
