### ISSUE TITLE
Limit arm32 windows testing

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#38570]
Limit windows arm32 testing. The PR loop will continue to build windows arm32. We can remove all stress testing and testing in the runtime pipeline. We can still continue to test windows arm32 in coreclr-outerloop.

@BruceForstall let me know if this meshes with the conversation we had. If not we can change the plan as we see fit to enable the quality bar the team needs for arm32 investigations.

**Comment by BruceForstall** [comment]
This matches my understanding of our plan.

**Comment by Gnbrkm41** [comment]
Does this apply to ARM64 as well?

**Comment by BruceForstall** [comment]
> Does this apply to ARM64 as well?

No, arm64 is fully supported. At this point I don't think arm64 is missing from any CI testing.
