### ISSUE TITLE
Framework information may be dropped on .NET 4.7.2

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#38588]
### Description

On .NET 4.7.2, `PopulateDefaultValues` is sometimes executed before ComputeTargetFrameworkName, which can lead Long Paths not being supported in certain scenarios.

### Configuration

Information from https://github.com/microsoft/msbuild/pull/3960

Root cause:

>  bin\amd64\MSBuild.exe.config tries to force itself to use our (IL-only) core libraries from the bin\ folder using codeBase entries that point to ..\whatever.dll.
> 
> That causes a call to RuntimeCheckLocationAccess that chains into a call to PopulateDefaultValues:
> 
> 0:000> !clrstack
> OS Thread Id: 0xeb50 (0)
>         Child SP               IP Call Site
> 0000002dcabfb640 00007ffd4b568baa System.AppContextDefaultValues.TryParseFrameworkName(System.String, System.String ByRef, Int32 ByRef, System.String ByRef) [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextDefaultValues.cs @ 78]
> 0000002dcabfb6a0 00007ffd4b568b54 System.AppContextDefaultValues.ParseTargetFrameworkName(System.String ByRef, System.String ByRef, Int32 ByRef) [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextDefaultValues.cs @ 42]
> 0000002dcabfb6e0 00007ffd4b568af8 System.AppContextDefaultValues.PopulateDefaultValues() [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextDefaultValues.cs @ 30]
> 0000002dcabfb730 00007ffd4b568a81 System.AppContext.InitializeDefaultSwitchValues() [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContext.cs @ 84]
> 0000002dcabfb780 00007ffd4b568845 System.AppContext.TryGetSwitch(System.String, Boolean ByRef) [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContext.cs @ 104]
> 0000002dcabfb820 00007ffd4b568651 System.AppContextSwitches..cctor() [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextSwitches.cs @ 205]
> 0000002dcabfbcb0 00007ffd4e7c6913 [GCFrame: 0000002dcabfbcb0] 
> 0000002dcabfc648 00007ffd4e7c6913 [HelperMethodFrame: 0000002dcabfc648] 
> 0000002dcabfc750 00007ffd4b5aa01e System.Security.Util.URLString.CheckPathTooLong(System.Text.StringBuilder) [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 461]
> 0000002dcabfc790 00007ffd4b618b69 System.Security.Util.URLString.PreProcessForExtendedPathRemoval(Boolean, System.String, Boolean, Boolean ByRef) [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 455]
> 0000002dcabfc810 00007ffd4b5a9ff5 System.Security.Util.URLString.PreProcessURL(System.String, Boolean) [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 477]
> 0000002dcabfc840 00007ffd4b5a9ed8 System.Security.Util.URLString.ParseString(System.String, Boolean) [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 653]
> 0000002dcabfc880 00007ffd4b5a9d92 System.Security.Util.URLString.GetFileName() [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 767]
> 0000002dcabfc8c0 00007ffd4bd86afe System.Reflection.RuntimeAssembly.DemandPermission(System.String, Boolean, Int32) [f:\dd\ndp\clr\src\BCL\system\reflection\assembly.cs @ 2798]
> 0000002dcabfcad0 00007ffd4e7c6913 [GCFrame: 0000002dcabfcad0] 
> 0000002dcabff508 00007ffd4e7c6913 [DebuggerClassInitMarkFrame: 0000002dcabff508] 
> 0:000> k
> # Child-SP          RetAddr               Call Site
> 00 0000002d`cabfb640 00007ffd`4b568b54     mscorlib_ni+0x588baa [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextDefaultValues.cs @ 78] 
> 01 0000002d`cabfb6a0 00007ffd`4b568af8     mscorlib_ni+0x588b54 [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextDefaultValues.cs @ 42] 
> 02 0000002d`cabfb6e0 00007ffd`4b568a81     mscorlib_ni+0x588af8 [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextDefaultValues.cs @ 30] 
> 03 0000002d`cabfb730 00007ffd`4b568845     mscorlib_ni+0x588a81 [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContext.cs @ 84] 
> 04 0000002d`cabfb780 00007ffd`4b568651     mscorlib_ni+0x588845 [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContext.cs @ 104] 
> 05 0000002d`cabfb820 00007ffd`4e7c6913     mscorlib_ni+0x588651 [f:\dd\ndp\clr\src\BCL\system\AppContext\AppContextSwitches.cs @ 205] 
> 06 0000002d`cabfb860 00007ffd`4e7c6818     clr!CallDescrWorkerInternal+0x83 [f:\dd\ndp\clr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 97] 
> 07 0000002d`cabfb8a0 00007ffd`4e9951e7     clr!CallDescrWorkerWithHandler+0x4e [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 89] 
> 08 0000002d`cabfb8e0 00007ffd`4e9951b5     clr!DispatchCallDebuggerWrapper+0x1f [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 183] 
> 09 0000002d`cabfb940 00007ffd`4e994be5     clr!DispatchCallSimple+0x93 [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 238] 
> 0a 0000002d`cabfb9e0 00007ffd`4e994ddc     clr!MethodTable::RunClassInitEx+0x111 [f:\dd\ndp\clr\src\vm\methodtable.cpp @ 3269] 
> 0b 0000002d`cabfbb10 00007ffd`4e994c5c     clr!MethodTable::DoRunClassInitThrowing+0x3b9 [f:\dd\ndp\clr\src\vm\methodtable.cpp @ 3501] 
> 0c 0000002d`cabfc5a0 00007ffd`4e99540d     clr!MethodTable::CheckRunClassInitThrowing+0xea [f:\dd\ndp\clr\src\vm\methodtable.cpp @ 3659] 
> 0d 0000002d`cabfc5d0 00007ffd`4b5aa01e     clr!JIT_GetSharedNonGCStaticBase_Helper+0xcd [f:\dd\ndp\clr\src\vm\jithelpers.cpp @ 1551] 
> 0e 0000002d`cabfc750 00007ffd`4b618b69     mscorlib_ni+0x5ca01e [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 461] 
> 0f 0000002d`cabfc790 00007ffd`4b5a9ff5     mscorlib_ni+0x638b69 [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 455] 
> 10 0000002d`cabfc810 00007ffd`4b5a9ed8     mscorlib_ni+0x5c9ff5 [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 477] 
> 11 0000002d`cabfc840 00007ffd`4b5a9d92     mscorlib_ni+0x5c9ed8 [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 653] 
> 12 0000002d`cabfc880 00007ffd`4bd86afe     mscorlib_ni+0x5c9d92 [f:\dd\ndp\clr\src\BCL\system\security\util\urlstring.cs @ 767] 
> 13 0000002d`cabfc8c0 00007ffd`4e7c6913     mscorlib_ni+0xda6afe [f:\dd\ndp\clr\src\BCL\system\reflection\assembly.cs @ 2798] 
> 14 0000002d`cabfc910 00007ffd`4e7c6818     clr!CallDescrWorkerInternal+0x83 [f:\dd\ndp\clr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 97] 
> 15 0000002d`cabfc950 00007ffd`4e7c70d8     clr!CallDescrWorkerWithHandler+0x4e [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 89] 
> 16 0000002d`cabfc990 00007ffd`4ed3a292     clr!MethodDescCallSite::CallTargetWorker+0x102 [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 655] 
> 17 (Inline Function) --------`--------     clr!Thread::SetFrame [f:\dd\ndp\clr\src\vm\threads.h @ 2156] 
> 18 (Inline Function) --------`--------     clr!Frame::Pop [f:\dd\ndp\clr\src\vm\frames.cpp @ 481] 
> 19 (Inline Function) --------`--------     clr!GCFrame::Pop [f:\dd\ndp\clr\src\vm\frames.cpp @ 1031] 
> 1a (Inline Function) --------`--------     clr!FrameWithCookie<GCFrame>::Pop [f:\dd\ndp\clr\src\vm\frames.h @ 3573] 
> 1b 0000002d`cabfca90 00007ffd`4ed3b545     clr!AssemblySpec::DemandFileIOPermission+0xcd [f:\dd\ndp\clr\src\vm\assemblyspec.cpp @ 961] 
> 1c 0000002d`cabfcc10 00007ffd`4ebce6df     clr!RuntimeCheckLocationAccess+0x14b [f:\dd\ndp\clr\src\vm\assemblyspec.cpp @ 922] 
> 1d 0000002d`cabfcce0 00007ffd`4e89c5f3     clr!CAssemblyDownload::GetNextCodebase+0x33452f [f:\dd\ndp\clr\src\fusion\download\adl.cpp @ 674] 
> 1e 0000002d`cabfcda0 00007ffd`4e89c48c     clr!CAssemblyDownload::KickOffDownload+0x144 [f:\dd\ndp\clr\src\fusion\download\adl.cpp @ 400] 
> 1f 0000002d`cabfd070 00007ffd`4e901317     clr!CAssemblyName::BindToObject+0x6a4 [f:\dd\ndp\clr\src\fusion\binder\naming.cpp @ 1779] 
> 20 0000002d`cabfd1f0 00007ffd`4e901165     clr!BindHelper+0x11d [f:\dd\ndp\clr\src\fusion\binder\bindhelpers.cpp @ 272] 
> 21 0000002d`cabfd2a0 00007ffd`4e9010f3     clr!BindContext::PreBindFullLocal+0x51 [f:\dd\ndp\clr\src\fusion\interface\bindcontext.cpp @ 344] 
> 22 0000002d`cabfd300 00007ffd`4e86de7b     clr!BindContext::PreBind+0x19c [f:\dd\ndp\clr\src\fusion\interface\bindcontext.cpp @ 179] 
> 23 0000002d`cabfd3b0 00007ffd`4e86e3e8     clr!NATIVE_BINDER_SPACE::VerifyNativeCandidate+0x4e9 [f:\dd\ndp\clr\src\nativebinder\binder.cpp @ 637] 
> 24 0000002d`cabfda70 00007ffd`4e85f874     clr!NATIVE_BINDER_SPACE::CreateVerifiedNICandidate+0x116 [f:\dd\ndp\clr\src\nativebinder\binder.cpp @ 401] 
> 25 0000002d`cabfdd90 00007ffd`4e85b93d     clr!NATIVE_BINDER_SPACE::BindToNativeDependency+0x367 [f:\dd\ndp\clr\src\nativebinder\binder.cpp @ 315] 
> 26 0000002d`cabfe410 00007ffd`4e85b6b8     clr!BindToNativeAssembly+0x10d [f:\dd\ndp\clr\src\nativebinder\binder.cpp @ 86] 
> 27 (Inline Function) --------`--------     clr!BaseHolder<IBindResult *,FunctionBase<IBindResult *,&DoNothing<IBindResult *>,&DoTheRelease<IBindResult>,2>,0,&CompareDefault<IBindResult *>,2>::Assign+0xffffffff`fffffff6 [f:\dd\ndp\clr\src\inc\holder.h @ 302] 
> 28 (Inline Function) --------`--------     clr!BaseHolder<IBindResult *,FunctionBase<IBindResult *,&DoNothing<IBindResult *>,&DoTheRelease<IBindResult>,2>,0,&CompareDefault<IBindResult *>,2>::Assign+0xffffffff`fffffff6 [f:\dd\ndp\clr\src\inc\holder.h @ 296] 
> 29 (Inline Function) --------`--------     clr!BaseWrapper<IBindResult *,FunctionBase<IBindResult *,&DoNothing<IBindResult *>,&DoTheRelease<IBindResult>,2>,0,&CompareDefault<IBindResult *>,2>::operator=+0xffffffff`fffffff6 [f:\dd\ndp\clr\src\inc\holder.h @ 641] 
> 2a (Inline Function) --------`--------     clr!Wrapper<IBindResult *,&DoNothing<IBindResult *>,&DoTheRelease<IBindResult>,0,&CompareDefault<IBindResult *>,2,1>::operator=+0xffffffff`fffffff6 [f:\dd\ndp\clr\src\inc\holder.h @ 877] 
> 2b (Inline Function) --------`--------     clr!ReleaseHolder<IBindResult>::operator=+0xffffffff`fffffff6 [f:\dd\ndp\clr\src\inc\holder.h @ 1001] 
> 2c 0000002d`cabfe540 00007ffd`4e8fcc2c     clr!BindToNativeImage+0x1fa [f:\dd\ndp\clr\src\fusion\binder\bindhelpers.cpp @ 170] 
> 2d 0000002d`cabfe880 00007ffd`4e8fde6d     clr!ExplicitBind+0x3cd [f:\dd\ndp\clr\src\fusion\binder\bindhelpers.cpp @ 920] 
> 2e 0000002d`cabff0a0 00007ffd`4e8fc163     clr!AppDomain::BindExplicitAssembly+0xf3 [f:\dd\ndp\clr\src\vm\appdomain.cpp @ 9556] 
> 2f 0000002d`cabff3a0 00007ffd`4e8fbe64     clr!SystemDomain::ExecuteMainMethod+0x2c1 [f:\dd\ndp\clr\src\vm\appdomain.cpp @ 3698] 
> 30 0000002d`cabff9a0 00007ffd`4e8fbbbd     clr!ExecuteEXE+0x3f [f:\dd\ndp\clr\src\vm\ceemain.cpp @ 3053] 
> 31 0000002d`cabffa10 00007ffd`4e8fcda4     clr!_CorExeMainInternal+0xb2 [f:\dd\ndp\clr\src\vm\ceemain.cpp @ 2887] 
> 32 0000002d`cabffaa0 00007ffd`4f3f8c01     clr!_CorExeMain+0x14 [f:\dd\ndp\clr\src\vm\ceemain.cpp @ 2814] 
> 33 0000002d`cabffae0 00007ffd`4f7dac42     mscoreei!_CorExeMain+0x112 [f:\dd\ndp\clr\src\dlls\shim\shim.cpp @ 6425] 
> 34 0000002d`cabffb40 00007ffd`679b6fd4     MSCOREE!_CorExeMain_Exported+0x72 [onecore\com\netfx\windowsbuilt\shell_shim\v2api.cpp @ 1223] 
> 35 0000002d`cabffb70 00007ffd`67fdcec1     KERNEL32!BaseThreadInitThunk+0x14 [clientcore\base\win32\client\thread.c @ 64] 
> 36 0000002d`cabffba0 00000000`00000000     ntdll!RtlUserThreadStart+0x21 [minkernel\ntdll\rtlstrt.c @ 1153]
> 
> But that happens before the call to pDomain->ComputeTargetFrameworkName() that happens a few lines later in clr!SystemDomain::ExecuteMainMethod.

**Comment by agocke** [comment]
We'll need to verify if this problem is also present in Core, or just in framework

**Comment by swaroop-sridhar** [comment]
This codepath doesn't exist in .net core.
