### ISSUE TITLE
ComponentModel IntrinsicTypeConverters are not linker safe

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#38582]
Calling `TypeDescriptor.GetConverter(typeof(Guid))`, or passing other low-level system types, in a trimmed app can cause failures because we are using reflection to create the object.

Underneath, we have a map of `Type` => `Converter Type`:

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L103-L136

And then we use that `Converter Type` and create an instance of it using reflection:

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs#L220-L222

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L1322-L1336

However, the linker cannot tell that it is supposed to preserve the constructor on these converters because it can't see through adding types to a collection.

Blazor is currently working around this issue here: https://github.com/dotnet/aspnetcore/blob/e906c2067be5552bf15f0bd2a9c793a6ad4d3dc6/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/LinkerWorkaround.xml#L11-L13

See related https://github.com/dotnet/aspnetcore/issues/23262

**Comment by MichalStrehovsky** [comment]
I've been thinking about these kinds of patterns in the past. I think the safest way to approach this is through a wrapper class. Something like:

```csharp
struct ReflectableHashtable
{
    private Hashtable _table;

    public void Add(Type x, [DynamicallyAccessed(X)] Type y) => _table.Add(x, y);

    [UnconditionalSuppressMessage(blah)]
    [DynamicallyAccessed(X)]
    public this[Type k] => _table[k];
}
```

Linker cannot fully see through this, so it needs a suppression, but it's a small struct and it's easy to audit that it is in fact safe.

**Comment by eerhardt** [comment]
That's a good idea, I'll see if I can get that to work.

In mono, it looks like it was annotated using `PreserveDependency` to preserve the constructors:

https://github.com/mono/mono/blob/be6f43c80e88ec0613c35714bac9c110d4012acb/mcs/class/referencesource/System/compmod/system/componentmodel/ReflectTypeDescriptionProvider.cs#L109-L136

Which can easily get out of sync.

One other option I was playing around with was to use a `Func<T>`, or similar, to create the objects, so that way the code just uses the constructors directly without reflection.

**Comment by ericstj** [comment]
@safern is contributing https://github.com/dotnet/runtime/pull/39854 which will need to be included as well.
