### ISSUE TITLE
Deserializing System.Collections.Immutable types with JsonSerializer is not linker safe

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#38593]
A `NullReferenceException` is thrown when deserialization of any of these collection types is attempted, due to the various `CreateRange` methods being trimmed out e.g. https://docs.microsoft.com/dotnet/api/system.collections.immutable.immutablelist.createrange.

**Comment by eerhardt** [comment]
@layomia - did we fix this? Can it be closed now?

**Comment by layomia** [comment]
@eerhardt  yes - this was fixed in https://github.com/dotnet/runtime/pull/38595.
