### ISSUE TITLE
Failed to detect .NET Core runtime in single file bundle

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#38601]
### Description

Failed to detect .NET Core runtime in single file bundle.

I cloned this project: https://github.com/ppy/osu
And I changed its TFM to `net5.0` and upgrade all existing old packages to 5.0.0-preview* as possible as I can. (There's a breaking change in EFCore, so that after upgrade EF packages there're some compile errors, it's ok to remove the line that caused compile error)

After publish project `osu.Desktop` as **self-contained** single file bundle, it prompted me that "Need to install .NET" when I tried to run it.

```bash
> dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true

.NET 向け Microsoft (R) Build Engine バージョン 16.7.0-preview-20310-07+ee1c9fd0c
Copyright (C) Microsoft Corporation.All rights reserved.

  復元対象のプロジェクトを決定しています...
  復元対象のすべてのプロジェクトは最新です。
  プレビュー版の .NET Core を使用しています。https://aka.ms/dotnet-core-preview をご覧ください
  プレビュー版の .NET Core を使用しています。https://aka.ms/dotnet-core-preview をご覧ください
  プレビュー版の .NET Core を使用しています。https://aka.ms/dotnet-core-preview をご覧ください
  プレビュー版の .NET Core を使用しています。https://aka.ms/dotnet-core-preview をご覧ください
  osu.Game -> C:\Users\hez20\source\repos\osu\osu.Game\bin\Release\netstandard2.1\osu.Game.dll
  osu.Game.Rulesets.Catch -> C:\Users\hez20\source\repos\osu\osu.Game.Rulesets.Catch\bin\Release\netstandard2.1\osu.Game.Rulesets.Catch.dll
  osu.Game.Rulesets.Osu -> C:\Users\hez20\source\repos\osu\osu.Game.Rulesets.Osu\bin\Release\netstandard2.1\osu.Game.Rulesets.Osu.dll
  osu.Game.Tournament -> C:\Users\hez20\source\repos\osu\osu.Game.Tournament\bin\Release\netstandard2.1\osu.Game.Tournament.dll
  osu.Game.Rulesets.Taiko -> C:\Users\hez20\source\repos\osu\osu.Game.Rulesets.Taiko\bin\Release\netstandard2.1\osu.Game.Rulesets.Taiko.dll
  osu.Game.Rulesets.Mania -> C:\Users\hez20\source\repos\osu\osu.Game.Rulesets.Mania\bin\Release\netstandard2.1\osu.Game.Rulesets.Mania.dll
  osu.Desktop -> C:\Users\hez20\source\repos\osu\osu.Desktop\bin\Release\net5.0\win-x64\osu!.dll
  osu.Desktop -> C:\Users\hez20\source\repos\osu\osu.Desktop\bin\Release\net5.0\win-x64\publish\
```

![image](https://user-images.githubusercontent.com/14960345/86078086-e3b48580-babf-11ea-8341-673fecc8af38.png)

![image](https://user-images.githubusercontent.com/14960345/86078099-eadb9380-babf-11ea-8d09-48cfb0510827.png)

Also found that this error message was not language localized.

### Configuration

.NET SDK: .NET 5 Preview 6

**Comment by swaroop-sridhar** [comment]
Hi @hez2010, can you please share a branch with your changes to `ppy/osu` so that I can try to repro the problem? Thanks.
Also, did you perform a clean build with the preview 6 SDK? Does the problem repro with preview 7? Thanks.

**Comment by hez2010** [comment]
Thanks!
The problem was gone with a clean build with preview 6 SDK.

**Comment by swaroop-sridhar** [comment]
Thanks for confirming this. Incremental build across sdk versions doesn't work correctly yet.
