### ISSUE TITLE
System.Threading.Tasks.Dataflow gets stuck using 100% cpu waiting for block completion

### ISSUE THREAD

**Issue by blushingpenguin** [dotnet/runtime#38629]
### Description

I have created a minimal reproduction sample here:

https://github.com/blushingpenguin/DataflowHang

within a few seconds of running this (linux) or few minutes (Windows) then the dataflow will get stuck on "waiting for dataflow to complete" and spin the cpu (up to 4 cores worth, presumably matching the configured degree of parallelism for the blocks involved).

### Configuration

dotnet core 3.1.5
either ubuntu 18.04 x64 or Windows 10 x64

### Regression?

unknown

**Comment by stephentoub** [comment]
Thanks for the repro.  I took a quick look, and I *think* the problem is that BatchBlock.BatchesNeedProcessing isn't factoring in _decliningPermanently.  _decliningPermanently is true, but BatchesNeedProcessing returns true rather than false; as a result, ProcessAsyncIfNecessary launches another task (which won't find anything to do) and then when it tries to complete the block, it finds there's a pending task (the one spawned by ProcessAsyncIfNecessary) and thus doesn't complete.  We just end up in this loop indefinitely.

**Comment by blushingpenguin** [comment]
I attached to a hung process, and it's definitely looping around spawning tasks in BatchBlockTargetCore.ProcessAsyncIfNecessary with _decliningPermanently = true.  In _nonGreedyState.PostPonedMessages, there is 1 message -- since the source has completed shouldn't this last message get forwarded though?  (I don't have a good handle on exactly what the code is doing so this could be totally off target though).

Thanks for looking at it so quickly!

**Comment by stephentoub** [comment]
> In _nonGreedyState.PostPonedMessages, there is 1 message -- since the source has completed shouldn't this last message get forwarded though?

No.  The repro has this code:
```
                fetchBlock.LinkTo(batchBlock, linkOptions, a => a != null);
                fetchBlock.LinkTo(DataflowBlock.NullTarget<JobThing>(), linkOptions);
```
That means that fetchBlock first offers the message to the batch block, assuming the message passes the filter.  If the message either doesn't pass the filter or if the batch block is full and postpones the message it was offered, the message will instead be offered to the next linked block, which in this case is a "null" target that will happily accept (and drop) everything.

> Thanks for looking at it so quickly!

👍

**Comment by Jetski5822** [comment]
I think I am seeing this in .netcore 3.1.5, is there any chance of getting this fix backported?
