### ISSUE TITLE
Defect in ReaderWriterLock when using it in recursive scenarios and multiple instances on the same thread

### ISSUE THREAD

**Issue by baxnie** [dotnet/runtime#38638]
### Description

When creating 2 instances of the ReaderWriterLock they can influence eachother via the threadlocal static behind it holding the read locks. An AcquireReaderLock can clear all earlier AcquireReaderLock calls rendering in an incorrect ReaderWriterLockApplicationException.

The code sample below is not working while it should

            var lock1 = new ReaderWriterLock();
            var lock2 = new ReaderWriterLock();

            lock1.AcquireReaderLock(0);

            lock2.AcquireReaderLock(0);
            lock2.ReleaseReaderLock();

            lock1.AcquireReaderLock(0);
            lock1.ReleaseReaderLock();
            lock1.ReleaseReaderLock(); // Throws ReaderWriterLockApplicationException Attempt to release a lock that is not owned by the calling thread

While the code below with 1 instance of ReaderWriterLock is working fine:

            var lock1 = new ReaderWriterLock();

            lock1.AcquireReaderLock(0);
            lock1.AcquireReaderLock(0);
            lock1.ReleaseReaderLock();
            lock1.ReleaseReaderLock();

After some investigation, I found that the ReaderWriterLock.ThreadLocalLockEntry.GetOrCreateCurrent(long lockID) can reuse a free ThreadLocalLockEntry while the entry is already present in the linked list.

### Configuration
.NET 2.1.16, but also happens in latest version
Windows 10 x64
This was correctly working on the .NET Framework version of ReaderWriterLock 

label: area-System.Threading

**Comment by baxnie** [comment]
[proposed Label] area-System.Threading

**Comment by baxnie** [comment]
labels: area-System.Threading

**Comment by Clockwork-Muse** [comment]
.... outside of any potential debug/fixing of this, recursive locks should usually be avoided.  If you're doing new development, the recommendation is to use `ReaderWriterLockSlim` and disable recursive locks.

For an example, there's this in the documentation for `ReaderWriterLock.AcquireReaderLock()`: 
> If the current thread already has the writer lock, no reader lock is acquired. Instead, the lock count on the writer lock is incremented. This prevents a thread from blocking on its own writer lock. The result is exactly the same as calling `AcquireWriterLock`, and an additional call to `ReleaseWriterLock` is required when releasing the writer lock.

.... which means that if you don't know what the lock state of any particular part of your program is going to be, unlocks should be vastly more complicated.
