### ISSUE TITLE
Linux/arm build warning with unw_getcontext

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#38652]
```
In file included from /__w/1/s/src/coreclr/src/pal/src/exception/seh.cpp:407:
/__w/1/s/src/coreclr/src/pal/src/exception/seh-unwind.cpp:321:10: warning: use of SP or PC in the list is deprecated [-Winline-asm]
    st = unw_getcontext(&unwContext);
         ^
/__w/1/s/artifacts/obj/coreclr/Linux.arm.Debug/src/pal/src/libunwind/include/libunwind-common.h:127:29: note: expanded from macro 'unw_getcontext'
#define unw_getcontext(uc)              unw_tdep_getcontext(uc)
                                        ^
/__w/1/s/src/coreclr/src/pal/src/libunwind/include/libunwind-arm.h:288:6: note: expanded from macro 'unw_tdep_getcontext'
    "stmia %[base], {r0-r15}\n"                                         \
     ^
<inline asm>:5:1: note: instantiated into assembly here
stmia r0, {r0-r15}
^
1 warning generated.
```

This came up before, in https://github.com/dotnet/runtime/issues/5595, where it was stated that the behavior is acceptable/required for libunwind. The fix before was to suppress the warning by avoiding inlining (apparently). Somehow, that fix isn't good enough anymore.

Example: https://dev.azure.com/dnceng/public/_build/results?buildId=712094&view=logs&j=7c52437f-2051-5ead-95de-b55e3296cb61&t=8db66bc6-175f-59c5-6a1e-742f332c2bdf

@janvorli

**Comment by janvorli** [comment]
@BruceForstall the change in #5595 changed that warning to not to be reported as an error and cause a build failure. Based on what I can see in the log from the build you have referenced, it is still not causing the build to fail.

**Comment by BruceForstall** [comment]
@janvorli Correct, it is not causing a build failure. I thought (assumed) the previous "fix" suppressed even this warning, so as not to confuse people (like me) who were searching for an actual failure. If the warning must remain, it's unfortunate, because it's confusing to see warnings like this.

**Comment by janvorli** [comment]
I think it should be possible to disable that warning. I don't remember why it was not done before.
