### ISSUE TITLE
Sporadic AccessViolationException creating a thread using `CreateThread`

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/runtime#38654]
### Description

<< More likely just a question and not a bug report >>

**Is there a known problem that could cause memory corruptions when calling `CreateThread` directly to create a thread (and passing a manaaged method as its ThreadProc) in a managed process?**

--

When attempting to add P/Invoke sigs for `CreateThread` and allied functions (https://github.com/dotnet/pinvoke/pull/463), I observed that my tests failed in the PR builds with `AccessViolationException`. 

Initially I couldn't reproduce the problem locally, but with effort (i.e., with some modifications to the tests etc.) I was able to repro the problem locally as well in my own separate CI builds. 

- dotnet/pinvoke PR builds - repros always. 
- my personal PR builds  - ~2/3 incidence
- local/dev builds - highly variable; sometimes no repro and sometimes repros consistently. 

I've only ever seen the problem repro under netfx TFM's. I've never been able to reproduce it under netstandard or netcoreapp TFM's. Another point of interest - if the threads are created suspended and never resumed, then all is well (no AV's, ever). 

### Configuration

- The tests in question are [here](https://github.com/dotnet/pinvoke/blob/a8e0d2a371db49219f73f863c7a35d6c1cffab23/src/Kernel32.Tests/storebanned/Kernel32Facts.cs#L947-L1123). . 
- Usually observed in net472 x86 runs only, and only sporadically. The repro is not consistent.

**Comment by AaronRobinsonMSFT** [comment]
@vatsan-madhavan I've never observed this. One important note is that the `CreateRemoteThread()` API is identical to `CreateThread` when the current process is passed as the handle. I don't think that matters in this case but want to call it out. It would be helpful to see a DMP if possible. Do you know where the A/V is occurring? From the cursory look at the code it seems correct - albeit with a bit too much usage of recent C# sugar for my taste.

**Comment by jkotas** [comment]
This is very likely caused by https://github.com/dotnet/pinvoke/pull/463/files#r448117142

**Comment by vatsan-madhavan** [comment]
@jkotas thanks for the quick help!
