### ISSUE TITLE
Feature Request: IEnumerable<T> for XmlNodeList

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/runtime#38657]
The current design of `System.Xml.XmlNodeList` in all versions of .Net Framework and .Net Core is:
`public abstract class XmlNodeList : IDisposable, System.Collections.IEnumerable`
https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlnodelist?view=netcore-3.1

It would make work with this class much easier (e.g. Linq could be used directly), if `XmlNodeList` also implemented `System.Collections.IEnumerable<T>`.
Please add this.

Note: Maybe this issue does not apply to C# itself yet, because the functionality likely needs to be added in the CLR first.

```diff
- public abstract class XmlNodeList : IDisposable, System.Collections.IEnumerable
+ public abstract class XmlNodeList : IDisposable, System.Collections.IEnumerable, System.Collections.IEnumerable<XmlNode>
```

EDIT (@krwq): extracted API proposal

**Comment by eiriktsarpalis** [comment]
@TobiasKnauss FWIW it should be possible to work around that limitation by using `xmlNodeList.Cast<XmlNode>()`.

**Comment by TobiasKnauss** [comment]
@eiriktsarpalis Yes, this is possible, but I'd like to avoid it.
@Joe4evr I was unsure whether dotnet/runtime was the correct repository. I searched for CLI and CLR, but couldn't find them. Thanks for clarifying.

**Comment by eiriktsarpalis** [comment]
> Yes, this is possible, but I'd like to avoid it.

Why is that? Performance considerations presumably?

**Comment by TobiasKnauss** [comment]
Performance, simplicity, it would be the'correct' way.
It could even implement ICollection, IList, IList<T>. I don't see a reason why this should not be possible.

**Comment by krwq** [comment]
I'm fine with this API. @TobiasKnauss assuming it gets approved are you interested in sending a PR?

**Comment by TobiasKnauss** [comment]
> I'm fine with this API. @TobiasKnauss assuming it gets approved are you interested in sending a PR?

I would, If I knew, how to do. I have never built the .Net Framework myself and I also don't have time to figure it out at the moment. I can provide the code that I would add, and If someone told me about all classes that derive from XmlNodeList, I could provide the code for these classes, too.
They only thing we need to consider: Adding more abstract methods to the abstract class XmlNodeList will break all derived classes, so they need to be adapted. I the previous paragraph, I wrote that I could provide code for all these classes in the .Net framework, but I everybody who created own derived classes needs to do the same. Otherwise their code will not compile anymore. I don't know whether this is acceptable, but If it was not, then enhancements of existing classes would never be possible.

**Comment by krwq** [comment]
@TobiasKnauss the instructions for all OS-es are here https://github.com/dotnet/runtime/tree/master/docs/workflow
basicallly you need to install VS with few checkboxes selected, install git, cmake and python and just run `build` command from the root repo, after that you just use regular msbuild from any directory in this project

**Comment by terrajobst** [comment]
* This wouldn't help the general `foreach` case due to the pattern-matched `GetEnumerator()` method
* This would only help the Linq case
* It general, it feels like a losing battle to trying to enrich technologies built on non-generic collections implement generic collection interfaces
