### ISSUE TITLE
Gateway Timeout -504 issue with API request - .net 4.7.2 framework but works with .net core

### ISSUE THREAD

**Issue by tsk238** [dotnet/runtime#38668]
I have issue sending a request to API using .net 4.7.2 framework but works with .net core. If I use .net 4.7.2, it is giving me Gateway Timeout -504 but same code works for .net core request. What would be the fix here for the .net 4.7.2 framework with this kind of issue ?

**Comment by wfurt** [comment]
I think you should do packet captures and look for differences. Since .NET Core works, this is wring place to file an issue. 
You should follow https://dotnet.microsoft.com/platform/support to file .NET Framework bug.

**Comment by scalablecory** [comment]
Triage: if you think this is a Framework bug, please file a bug in the community site. This Github repo is for .NET Core issues only.

**Comment by tsk238** [comment]
> Triage: if you think this is a Framework bug, please file a bug in the community site. This Github repo is for .NET Core issues only.

Thanks for the Suggestion. Why Core is working but not .Net Framework? What could be the difference between here in the request?

**Comment by wfurt** [comment]
The description does not have any clues. There can be differences in default headers, timeouts or ssl handshake if this is HTTPS request. I recommend to use Wireshark and look for any differences.
