### ISSUE TITLE
Add NativeIntegerAttribute

### ISSUE THREAD

**Issue by cston** [dotnet/runtime#38683]
## Background and Motivation

Allow annotating references to `System.IntPtr` and `System.UIntPtr` as native integers in metadata.
See [spec](https://github.com/dotnet/csharplang/blob/master/proposals/native-integers.md).

## Proposed API

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(
        AttributeTargets.Class |
        AttributeTargets.Event |
        AttributeTargets.Field |
        AttributeTargets.GenericParameter |
        AttributeTargets.Parameter |
        AttributeTargets.Property |
        AttributeTargets.ReturnValue,
        AllowMultiple = false,
        Inherited = false)]
    public sealed class NativeIntegerAttribute : Attribute
    {
        public NativeIntegerAttribute()
        {
            TransformFlags = new[] { true };
        }
        public NativeIntegerAttribute(bool[] flags)
        {
            TransformFlags = flags;
        }
        public IList<bool> TransformFlags { get; }
    }
}
```

Used by the C# compiler to represent type references to `nint` and `nuint` in metadata.

The C# compiler reserves the attribute for compiler use only.

If the attribute is not available in the compilation, the C# compiler will emit an `internal` attribute type with the same shape.

## Usage Examples

Consider the following signature in C#:
```C#
static nint Sum(nint[] array)
{
}
```

In metadata:
```C#
[NativeInteger]
static System.IntPtr Sum(
    [NativeInteger(new[] { false, true })] System.IntPtr[] array)
{
}
```

**Comment by tannergooding** [comment]
CC. @terrajobst as an FYI

**Comment by terrajobst** [comment]
* We didn't add `NullableAttribute`. We only added attributes that we expect users to reference explicitly by manually adding custom attributes. It seems this attribute would only be emitted and read by the compiler, so unless there is a reason, we'd not add it.

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(
        AttributeTargets.Class |
        AttributeTargets.Event |
        AttributeTargets.Field |
        AttributeTargets.GenericParameter |
        AttributeTargets.Parameter |
        AttributeTargets.Property |
        AttributeTargets.ReturnValue,
        AllowMultiple = false,
        Inherited = false)]
    public sealed class NativeIntegerAttribute : Attribute
    {
        public NativeIntegerAttribute()
        {
            TransformFlags = new[] { true };
        }
        public NativeIntegerAttribute(bool[] flags)
        {
            TransformFlags = flags;
        }
        public IList<bool> TransformFlags { get; }
    }
}
```

**Comment by jaredpar** [comment]
> It seems this attribute would only be emitted and read by the compiler, so unless there is a reason, we'd not add it.

This logic seems to apply to `DynamicAttribute` and `TupleElementNamesAttribute` yet those are in the BCL.

**Comment by eerhardt** [comment]
Just an FYI - these kinds of decisions impact other tools in the ecosystem as well. For example, the ILLinker has the ability to strip attributes if someone asks it to. However, when an attribute can be generated into a bunch of different assemblies, it makes it slower for the linker to strip these attributes.

See https://github.com/dotnet/runtime/pull/39000#discussion_r452411120 for the discussion. I've copied the relevant parts here:

> Can we limit the assembly "*" to only the cases where it's necessary? it's relatively expensive for the linker (as it has to search all assemblies in the closure and find all occurrences of the type).

cc @marek-safar @vitek-karas
