### ISSUE TITLE
Task.Run failing with broken exceptions and internal CLR errors

### ISSUE THREAD

**Issue by Perksey** [dotnet/runtime#38709]
### Description
I have an action delegate which launches a new task using Task.Run when dequeued from a concurrent queue and executed. The enqueue and dequeue, while it can be on different threads, in this case both enqueue and dequeue are happening on the same thread along with everything else. I get a number of obscure exceptions when doing this and I can't reproduce them on my machine (this information was collected from a tester's machine).

The code is protected so here's a minimal example that captures the essence of what the program is doing:

```cs
public class Class1
{
    private ConcurrentQueue<Action> _viewableChanges = new ConcurrentQueue<Action>();
    public void SetViewable(IViewable viewable, bool arg1 = false)
    {
        _viewableChanges.Enqueue(() =>
        {
            viewable.Bind(); 
        });
    }

    public void DrawFrame(double arg0)
    {
        if (_viewableChanges.TryDequeue(out var changeViewable))
        {
            changeViewable();
        }
    }
}
public class LoadingScreen : IViewable
{
    private Task _loadTask = null;
    public void Bind()
    {
        _loadTask ??= Task.Run(LoadAsync);
    }
    public async Task LoadAsync() { /* ... */ }
}

public interface IViewable {void Bind();}
public class Program
{
    public static void Main(string[] args)
    { try { ActualMain(); } catch (Exception ex) { /* ... */ }

    public static void ActualMain()
    {
        Class1.SetViewable(new LoadingScreen());
        /* ... */
        var window = Silk.NET.Windowing.Window.Create(Silk.NET.Windowing.WindowOptions.Default);
        window.Render += Class1.DrawFrame;
        /* ... */
        window.DoRender();
    }
}
```

### Configuration

- .NET Core 3.1
- Self-contained deployment
- Windows x64
- Multiple configurations

### Debug configuration
![image](https://user-images.githubusercontent.com/11160611/86363596-fde09600-bc6e-11ea-99f3-5d4cee2ab22d.png)

### Release configuration
![image](https://user-images.githubusercontent.com/11160611/86363782-3b452380-bc6f-11ea-8e49-9b7a00f3aaf0.png)

The first partially cut-off line reads:
```
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib. This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: Arg_AccessViolationException
```

### Regression?

Unknown.

### Other information

So it seems that on debug configuration perhaps the CLR is attempting to pass along a garbage collected delegate as a function pointer (as I have got similar CLR errors when working with manual interop and forgot to pin the delegate) but that's just a hunch and it may not be the actual reason. In any case it does look like an advapi32 interop issue.

On release configuration I don't even know what's going on. It looks like an AccessViolationException is being thrown somewhere, but another localization failure occurs (presumably because of the corrupt state) while throwing the exception such that it fails in the way that it does.

In both cases, these are both obscure errors that I don't even know where to begin to nail-down. Any help would be appreciated.

**Comment by jkotas** [comment]
These symptoms are most likely caused by some other component in your program corrupting the unmanaged heap.

The best way to diagnose them is via the pageheap utility: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-and-pageheap

**Comment by Perksey** [comment]
Closing as I gave up with fixing this issue to be quite frank :P
