### ISSUE TITLE
ilasm (and ildasm) crashing on Linux

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#38701]
### Description
Calling ilasm (and ildasm) directly by their name (without path) on Linux crashes with:
`Segmentation fault (core dumped)`

### Configuration
OS: Ubuntu 18.04 x64
dotnet: 3.1.301
ilasm (ildasm) package: 2.0.8

### How to reproduce
In a new terminal execute the following sequence:
1. dotnet new console -n test
2. cd test
3. dotnet add package Microsoft.NETCore.ILAsm (ILDAsm)
4. dotnet publish -c Release --self-contained --runtime linux-x64
5. export PATH=$(pwd)/bin/Release/netcoreapp3.1/linux-x64/publish:$PATH
6. ilasm (ildasm)

### Other information
Calling ilasm (or ildasm) by specifying the full path works correctly.
After some investigation it seems that the problem might be in PAL library which expects '/' to be found in argv[0]

**Comment by BruceForstall** [comment]
Thanks for the report. This is a dup of https://github.com/dotnet/runtime/issues/12690
