### ISSUE TITLE
Question: How to pass object arrays from .NET CoreCLR Host Application to C# Application and vice versa?

### ISSUE THREAD

**Issue by DasDarki** [dotnet/runtime#38708]
Currently I'm trying to write a CoreCLR host application in C++ that runs C# plugins and does certain things with those loaded plugins.
Hosting the CoreCLR host, loading and executing and interacting with the plugins works without any problems. The previously integrated P/Invoke also works fine, but now I have encountered a problem where I don't know if this is possible and if so, how.

I'm trying to execute a method from the CoreCLR host, which has as parameter an Object Array (of unknown length; the length is determined from the host side). The objects of the array can be one of 3 types: String, Double or Boolean. I've been trying around for a few days and saw through the internet how to implement this and the only thing I managed to do was to pass a simple int array via Marshal.
The second problem, same scenario: How can I call a C++ function via P/Invoke that also takes an array of "objects" of the 3 types?

Some examples for the method signatures:
```c++
EXPORTED void DoSomething(void** objects)
{
    //Does something
}
```

```csharp
public static void DoSomething(object[] objects)
{
     //Does something
}
```

I would be very grateful if someone could help me with these problems and thank you very much in advance. If there is any information missing, I will add it on request and wish you a nice day.

**Comment by AaronRobinsonMSFT** [comment]
@DasDarki This is possible, but it may require utilizing some non-recommended practices in some cases.

**Calling a C native function**

The below uses the COM-Automation type [`VARIANT`](https://docs.microsoft.com/windows/win32/api/oaidl/ns-oaidl-variant) to marshal the object types. This approach is Windows only and not recommended.
```C
void PassObjArray(VARIANT* arr, int arrLen);
```
```CSharp
[DllImport("...")]
extern static void PassObjArray([MarshalAs(UnmanagedType.LPArray)] object[] arr, int arrLen);
```

The recommended, but more complicated way, is to manually marshal the data. This approach works on Windows and non-Windows platforms. Manually marshalling involves [allocating native memory](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.alloccotaskmem) and passing a value or pointer into the array. Arrays with heterogeneous value will need some kind of discriminated union (e.g. `VARIANT` or [`std::variant`](https://en.cppreference.com/w/cpp/utility/variant)) or to utilize some bespoke solution.

```C
void PassObjArray(void* arr, int arrLen);
```
```CSharp
[DllImport("...")]
extern static void PassObjArray(void* arr, int arrLen);
```

**Calling a C# managed function**

This approach is largely the same but in reverse order. The below example is Windows only and requires the same `VARIANT` in C code.

```CSharp
delegate void TestDel([MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] object[] arr, int c);
static void TestM(object[] arr, int c)
{
    ...
}

...
var d = new TestDel(TestM);
IntPtr fptr = Marshal.GetFunctionPointerForDelegate(d);
//
// Pass fptr to native and call.
//
GC.KeepAlive(d); // Keep delegate alive during call or it may be collected during a GC.
...
```

The manual way is similar but allocated on the native side.

Additional references:
* [Interop Marshalling](https://docs.microsoft.com/dotnet/framework/interop/interop-marshaling)
* [Type marshalling](https://docs.microsoft.com/dotnet/standard/native-interop/type-marshaling)
* [Marshalling Classes, Structures, and Unions](https://docs.microsoft.com/dotnet/framework/interop/marshaling-classes-structures-and-unions)
