### ISSUE TITLE
X509Chain.Build leads to crash of the dotnet core runtime on linux

### ISSUE THREAD

**Issue by farodin91** [dotnet/runtime#38704]
### Description

The call of X509Chain.Build method leads to crash of the dotnet core runtime with the exit code 139.

### Configuration
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.103
 Commit:    6f74c4a1dd

Runtime Environment:
 OS Name:     fedora
 OS Version:  32
 OS Platform: Linux
 RID:         fedora.32-x64
 Base Path:   /usr/lib64/dotnet/sdk/3.1.103/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.103 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```

In our production environment, we also see this issue. In this environment, we use the docker image `mcr.microsoft.com/dotnet/core/aspnet:3.1`.

### Regression?

We create a regression test to check the behaviour on different platforms. We see this issue on Linux but not on Windows.

[regression.cert.txt](https://github.com/dotnet/runtime/files/4863213/regression.cert.txt)

```
[Fact]
public void RegressionTest()
{
     var certPath = Path.Combine(Directory.GetCurrentDirectory(), "regression.cert.txt");
     var certContent = Convert.FromBase64String(File.ReadAllText(certPath));
     var cert = new X509Certificate2(certContent);

     var ch = new X509Chain();
     ch.Build(cert);

     Assert.NotNull(cert);
}
```

**Comment by bartonjs** [comment]
Hm.  The first time we call X509_verify_cert it doesn't crash, then we're ready to move in to chain building phase 2 and the second call (via CryptoNative_X509StoreCtxRebuildChain) ends up asking if NULL was the issuer of some cert.  Not sure how a NULL got in the mix.

**Comment by vcsjones** [comment]
Here is what I think is going on - the AIA URL on the leaf certificate points to `http://ca.playtechgaming.com/`. That URL returns a zero byte result when downloaded in `CertificateAssetDownloader`

https://github.com/dotnet/runtime/blob/cfd0172f89d237f79c47de51b64d5778c440bbc6/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CertificateAssetDownloader.cs#L24-L38 

Passing `byte[0]` to `X509Certificate2.ctor` doesn't throw, you just get a "default" certificate. We never actually touch the certificate to make sure it's "real", we just try chain building again with this default cert and a null PAL.

Changing the cert downloader to throw if the certificate is in an invalid state fixes it.

```c#
try
{
    X509Certificate2 cert = new X509Certificate2(data);
    cert.ThrowIfInvalid();
    return cert;
}
catch (CryptographicException)
{
    return null;
}
```

**Comment by vcsjones** [comment]
I will address this with a PR shortly.
