### ISSUE TITLE
Single-file: Test debugging on Linux/Mac

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#38726]
Test to ensure that debugging behavior matches the expectation in https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md#host-builds

Results on testing with 5.0.100-preview.6.20318.15 (4356580024):

- [X] Mac
 - VS Code
      - ❌ Without copying mscordbi.dll, fails with: `Failed to attach to process: Unknown Error: 0x80131c3c`
      - ✔️After copying mscordbi.dll, attach succeeds
 - ✔️ LLDB + SOS: Works, I think. Having trouble hitting breakpoints in any configuration, not just single file. I think it's an unrelated problem. 
- [x] Linux
  - ✔️ LLDB + SOS: Works fine. Symbols are present and breakpoints work.
- [X] Windows
  -  VS Code
      - ❌ Without copying mscordbi.dll, fails with: `Failed to attach to process: Unknown Error: 0x80131c3c`
      - ✔️ After copying mscordbi.dll, attach succeeds
      - ❌ Without copying mscordbi.dll, fails with:  `msvsmon` crashes, `unable to attach to the process`
      - ✔️After copying mscordbi.dll, attach succeeds
  - ✔️ WinDBG + SOS: SOS is not loaded automatically, although the coreclr module is loaded. When sos.dll is loaded manually using `dotnet install`, debugging seems to work OK. Symbols are present and breakpoints work.

**Comment by agocke** [comment]
I can test on Mac, as I have a Mac laptop

**Comment by swaroop-sridhar** [comment]
Thanks @agocke. I'll add more details about the test scenarios.

**Comment by agocke** [comment]
Debugging work has been completed for .NET 5 -- once mscordbi and mscordaccore are copied next to the single-file app, debugging works fine.
