### ISSUE TITLE
Remove #ifDefs on constants like TARGET_UNIX

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#38741]
There are a couple of places where we are still using os based if defs.
We should instead have separate files for them and should not be using them

cc @ericstj

**Comment by safern** [comment]
I guess this is referring to framework libraries and not System.Provate.CoreLib, right?

**Comment by jkotas** [comment]
We want to optimize for source readability here. We end up using ifdefs in some cases because of it makes the sources more readable, understandable or efficient compared to split files.

**Comment by ViktorHofer** [comment]
Closing based on above's discussion and because this issue isn't actionable.
