### ISSUE TITLE
System.Diagnostics.PerformanceCounter.Tests failure

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#38756]
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInit_ProcessorCounter

net472-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open

```
    System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInit_ProcessorCounter [FAIL]
      System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
      Stack Trace:
           at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
           at System.Diagnostics.PerformanceCounterLib.get_NameTable()
           at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
           at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
           at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
           at System.Diagnostics.PerformanceCounter.InitializeImpl()
           at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, String machineName)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs(163,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInit_ProcessorCounter()
```

https://dev.azure.com/dnceng/public/_build/results?buildId=715815&view=ms.vss-test-web.build-test-results-tab&runId=22181210&resultId=109727&paneView=debug

[Console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-38453-merge-590b60ac358b44d786/System.Diagnostics.PerformanceCounter.Tests/console.031b7281.log?sv=2019-02-02&se=2020-07-23T10%3A37%3A00Z&sr=c&sp=rl&sig=Gy%2B454kVLg3ygIm48uWBW4ZqJImEhy1b08H3McoXmLM%3D)
[TestResults.xml](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-38453-merge-590b60ac358b44d786/System.Diagnostics.PerformanceCounter.Tests/testResults.xml?sv=2019-02-02&se=2020-07-23T10%3A37%3A00Z&sr=c&sp=rl&sig=Gy%2B454kVLg3ygIm48uWBW4ZqJImEhy1b08H3McoXmLM%3D)

**Comment by tarekgh** [comment]
This is usually happens when the perf counters are corrupted on this machine. you can consult the link https://support.microsoft.com/en-us/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6 on how you can manually fix it.

**Comment by ManickaP** [comment]
It's a CI, I cannot fix anything on that machine :disappointed: 
But if what you say is true, than this might be an infra issue.

**Comment by danmosemsft** [comment]
In the last 6 months, this is always on the same machine (actually always in Dec)

https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2QTUsDMRCG74L%2fYeilLfRj7UkK68FWYQUVbcXzdDNtpt1NlkzWdsUfb7ItVkEITGaSeeZ9Z0niX0nqwgtcXnzBXpMjWDYVgXh0XvbsNXQWjXgqR3PGjbHiOZfRMnRKJ%2fZsLRvYsVEpG0MO3q3bZeG7gDU%2fSaZ%2b8e%2fZsGhScJOCQk%2beS%2bpNkkkyTK6HyRUk0ySe%2fn%2f0B7tqwSFm6oy8dWhyDWkKHUdrGWtCJeMSg27Xqqyc3VLuYWaN2ILeHA9gES2SGsC8dujZmgE8ktc2VF5qqukJS4olEdzEC%2baaTVs9Dz69tpNPa8rMBxasnis6Uu8OOVXxAlOYoTHWQ2FRBSm1CfIgAuMeEFaUYy0EaICPkBAVHaDbhT0KuOAK1s6W4DWFbMPiXTNqDUpdluj4kyCP3F4fVs0fG2f139BSEjr2AQAA&web=0

TestResults 
| where Type startswith "System.Diagnostics.Tests"
| join kind=inner WorkItems on WorkItemId 
| where Finished >= datetime(2020-08-01 0:00:00)
| join kind=inner Jobs on JobId
| where Branch == "refs/heads/master"
| project ConsoleUri, Started, Duration, Method, QueueName, Message, MachineName
| where Message == "System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry."
| summarize count() by QueueName, MachineName


QueueName | MachineName | count_
-- | -- | --
windows.10.arm64v8.open | DDARM64-160 | 42

**Comment by danmosemsft** [comment]
@dotnet/dnceng could we please rebuild DDARM64-160? Seems the perf counters are corrupted.

**Comment by danmosemsft** [comment]
If this fixes it we should improve the message to give the machine name and suggest the perf counters are corrupted.

**Comment by MattGal** [comment]
> @dotnet/dnceng could we please rebuild DDARM64-160? Seems the perf counters are corrupted.

I put it offline and am double checking it's the only one with this symptom;  I'm unfamiliar with "corrupted" perf counters, is there something we should investigate on the machine itself?

**Comment by MattGal** [comment]
Doing some quick reading it seems rebuilding perf counters isn't hard but given there could be other problems with the agent I created https://github.com/dotnet/core-eng/issues/11788 to reimage it.

**Comment by danmosemsft** [comment]
Seems indeed to be fixed by the repaving.

**Comment by VincentBu** [comment]
Failed again in [runtime 20210616.88](https://dev.azure.com/dnceng/public/_build/results?buildId=1190871&view=ms.vss-test-web.build-test-results-tab&runId=35752412&resultId=107868&paneView=debug)

Failed test:
```
net48-windows-Release-x86-Windows.10.Amd64.Client19H1.Open

- System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

```
**Error message:**
```
System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.


Stack trace
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)
   at System.Diagnostics.Tests.Helpers.DeleteCategory(String name) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 46
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131
```
