### ISSUE TITLE
JIT generates redundant vmovaps

### ISSUE THREAD

**Issue by TYoung86** [dotnet/runtime#38750]
### Description

JIT generates redundant vmovaps.

### Configuration

SharpLab's Release x64 (Core CLR v4.700.20.26901 on amd64)

### Regression?

No.

### Data

[sharplab.io output](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ovLrmXrNjZu258BLIxhNmLLABoAOJBuqaAzEykDEIIDADeNAzRDFExANoAsjAYABYQACYG4pIAFMlpmdlikgDyYnwQZiwAggDmdbC45gowRpKmpnUAlAC6cdFiJgrYGDDaSAwZEBzA0iEwUl2yuDAo5LnTs/MK3QMxALwAfAwra6xCix1cdbJg2JLYULkAajBgGNDkpJ7CsKMwO4PJ4AVTM2AAZjBcrtuiwACoQIGPZ7dXz7JIpdJZHL5LFFHLlSrVeqNVQtNpca5dPr7Ia8EZjCZTGZzcbwqDce5jM7rTasnZ7agxQ4nXk6GZcDKIgBaMiR9xRr3enyg31+Qn+PMVoPBUJh3ThiORT1yaP2+xFkDMGBZ23ZNRBDAODESo1SLAACgYAFSkXwijEFbHFPLBgklIm8Kq4WoNJoUqP4XgAL1G0a4tOFMXpjPGzEmWzZDDYMAyHBUGyL8zSKWw3QilpiIygDAgzoYtYw2ADIoYLbbwRdbrSLAAYhxVhlEhxJHwSgBPGoZDK5S5LG7i3K5eGOhg+hjBOBthsH3LkBgAegYu5BhrQN8dD4g5uzIoHEECw/d48nZZnc68Iuy6rnAHJcgCW4QMEZ4Xtet73o+ILPqQr59kwADsbb+L20QAL40EG+I4iUeKFCRZQVBmsakgmDIwEmqbplUWYirmALMtW4yluWKikPy9qdqkdYNpEb4xF22AdiOHoTlOAHzpIS4rmuVzLKsfI7nuB5HkJIn7gw55XkhiG3g+kloX2knST+cn/rOinKaB4FcNygIaRs1mwcZCHdA+Zl6d2lkisQWGSbhDAEX41B4UAA===)
```

Cx.Reduce1(Double)
    L0000: vzeroupper
    L0003: vmovsd xmm1, [Cx.Reduce1(Double)]
    L000b: vsubsd xmm1, xmm1, xmm0
    L000f: vmulsd xmm1, xmm1, [Cx.Reduce1(Double)]
    L0017: vroundsd xmm1, xmm1, xmm1, 0xa
    L001d: vmovsd xmm2, [Cx.Reduce1(Double)]
    L0025: vfmadd213sd xmm1, xmm2, xmm0
    L002a: vmovaps xmm0, xmm1
    L002e: vmulsd xmm0, xmm0, [Cx.Reduce1(Double)]
    L0036: vroundsd xmm0, xmm0, xmm0, 0xb
    L003c: vmovsd xmm2, [Cx.Reduce1(Double)]
    L0044: vxorps xmm0, xmm0, xmm2
    L0048: vmovsd xmm2, [Cx.Reduce1(Double)]
    L0050: vfmadd213sd xmm0, xmm2, xmm1
    L0055: ret

Cx.Reduce2(Double)
    L0000: vzeroupper
    L0003: vmovsd xmm1, [Cx.Reduce2(Double)]
    L000b: vsubsd xmm1, xmm1, xmm0
    L000f: vmulsd xmm1, xmm1, [Cx.Reduce2(Double)]
    L0017: vroundsd xmm1, xmm1, xmm1, 0xa
    L001d: vmovsd xmm2, [Cx.Reduce2(Double)]
    L0025: vfmadd213sd xmm1, xmm2, xmm0
    L002a: vmovaps xmm0, xmm1
→   L002e: vmovaps xmm1, xmm0
    L0032: vmulsd xmm1, xmm1, [Cx.Reduce2(Double)]
    L003a: vroundsd xmm1, xmm1, xmm1, 0xb
    L0040: vmovsd xmm2, [Cx.Reduce2(Double)]
    L0048: vxorps xmm1, xmm1, xmm2
    L004c: vmovsd xmm2, [Cx.Reduce2(Double)]
    L0054: vfmadd213sd xmm1, xmm2, xmm0
→   L0059: vmovaps xmm0, xmm1
    L005d: ret
```

### Analysis

Something's not right, I think?
```
    L002a: vmovaps xmm0, xmm1
    L002e: vmovaps xmm1, xmm0
```
Reduce1 and Reduce2 should preferably be identical.

**Comment by EgorBo** [comment]
```asm
; Assembly listing for method Cx:Reduce2(double):double
; Emitting BLENDED_CODE for X64 CPU with AVX - Unix
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  9,  9   )  double  ->  mm0
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;* V02 tmp1         [V02    ] (  0,  0   )  double  ->  zero-ref    "Inlining Arg"
;* V03 tmp2         [V03    ] (  0,  0   )  double  ->  zero-ref    "Inlining Arg"
;  V04 cse0         [V04,T01] (  3,  3   )  simd16  ->  mm2         "CSE - aggressive"
;
; Lcl frame size = 0

G_M37874_IG01:
       C5F877               vzeroupper
						;; bbWeight=1    PerfScore 1.00
G_M37874_IG02:
       C5FB100D5D000000     vmovsd   xmm1, qword ptr [reloc @RWD08]
       C5F35CC8             vsubsd   xmm1, xmm1, xmm0
       C5F3590D61000000     vmulsd   xmm1, xmm1, qword ptr [reloc @RWD24]
       C4E3710BC902         vroundsd xmm1, xmm1, xmm1, 2
       C5FB101563000000     vmovsd   xmm2, qword ptr [reloc @RWD40]
       C4E2E9A9C8           vfmadd213sd xmm1, xmm2, xmm0
       C5F828C1             vmovaps  xmm0, xmm1
       C5FB590D62000000     vmulsd   xmm1, xmm0, qword ptr [reloc @RWD56]
       C4E3710BC903         vroundsd xmm1, xmm1, xmm1, 3
       C5FB101D64000000     vmovsd   xmm3, qword ptr [reloc @RWD72]
       C5F057CB             vxorps   xmm1, xmm3
       C4E2E9A9C8           vfmadd213sd xmm1, xmm2, xmm0
       C5F828C1             vmovaps  xmm0, xmm1
						;; bbWeight=1    PerfScore 39.83
G_M37874_IG03:
       C3                   ret
						;; bbWeight=1    PerfScore 1.00
RWD00  dq	0000000000000000h
RWD08  dq	402921FB54442D18h
RWD16  dq	0000000000000000h
RWD24  dq	3FC45F306DC9C883h
RWD32  dq	0000000000000000h
RWD40  dq	401921FB54442D18h
RWD48  dq	0000000000000000h
RWD56  dq	3FC45F306DC9C883h
RWD64  dq	0000000000000000h
RWD72  dq	8000000000000000h


; Total bytes of code 82, prolog size 3, PerfScore 50.93, (MethodHash=127f6c0d) for method Cx:Reduce2(double):double
; ============================================================
```

**Comment by tannergooding** [comment]
SharpLab is generally on the last release (3.1) rather than the latest nightlies, so the disassembly it shows can be quite out of sync with what is actually being produced.
In this case, various fixes have gone in that improve the codegen for these scenarios and the redundant `movaps` no longer exist.

**Comment by BruceForstall** [comment]
According to @tannergooding and the output shown by @EgorBo this has already been addressed. I'll go ahead and close this, but feel free to re-open if this is incorrect.

**Comment by TYoung86** [comment]
Just to confirm, switching sharplab.io to the June 9th build of roslyn master that still exhibits the redundant `movaps` is out of sync?

**Comment by tannergooding** [comment]
Roslyn and .NET Runtime are different. Roslyn is the C# and VB compilers and language service, while dotnet/runtime is the actual JIT and framework assemblies.

Sharplab does not currently support running code against the latest dotnet/runtime builds.
