### ISSUE TITLE
Boxing ref struct using MethodInfo.Invoke

### ISSUE THREAD

**Issue by MaximGurschi** [dotnet/runtime#38769]
Hi team,

Accidentally i've discovered the ability to box a ref struct by using reflection.

The scenario is the invocation via reflection of a method that has, say, an in ref struct parameter. Upon the exit of the call the parameter array passed to MethodInfo.Invoke will contain a boxed ref struct.

Small reproduction (call Repro.Test()):
```C#
     static class Repro
    {
        ref struct RefStruct
            {
                private long L;
                private int I;
            }

        private static void MethodStr(in RefStruct rs) { }

        private static void ReflectionInvoke(string method)
        {
            var parameters = new object[1];

            var message = parameters[0] == null ? "null" : parameters[0].GetType().Name;
            Console.WriteLine(message); // Displays null.
            typeof(Repro)
                .GetMethod(method, BindingFlags.Static | BindingFlags.NonPublic)
                .Invoke(null, parameters);
            message = parameters[0] == null ? "null" : parameters[0].GetType().Name;
            Console.WriteLine(message); //Displays RefStruct.
        }

       public static void Test() => ReflectionInvoke(nameof(MethodStr));
    }
```
 
Can someone please confirm if the outcome of the second Console.WriteLine is by design?

**Comment by GrabYourPitchforks** [comment]
Probably something we should address, as boxing ref structs could destabilize the runtime. It's possible that the only reason this worked rather than resulting in an internal VM error is that the ref struct defined in the repro doesn't contain any reference-type fields.

**Comment by MaximGurschi** [comment]
Thanks, I've edited the post to include some fields in the struct. Even with fields it works. Yes i was thinking that this should not be allowed by the runtime as it can lead to passed stack frame reads.
