### ISSUE TITLE
Regex Capture Trees

### ISSUE THREAD

**Issue by osamakawish** [dotnet/runtime#38776]
This is to simplify regex captures a little. Although this can be done on the side, it would be more efficiently done in the code behind. 

Basically, each regex `Capture` should be treated as a type of a `Match`, with it's own captures which are in the form of an ordered list or a `CaptureCollection`. 

This is mainly for captures containing captures, like `"Email" : "((\w+)@(\w+).com)"`.

For `"Email": "address@gmail.com"`, you'd have:
1. address@gmail.com
  1.1. address
   1.2. gmail

**Edit.** It's worth clarifying that captures not containing captures would simply have an empty `CaptureCollection`.

**Comment by pgovind** [comment]
@osamakawish , would you able to come up with a more detailed API proposal with use cases and justifications? Some examples of recent API proposals are: https://github.com/dotnet/runtime/issues/50902, https://github.com/dotnet/runtime/issues/50389

**Comment by osamakawish** [comment]
I think I'm over thinking this. It would be relatively easy to implement on your own and probably just as efficient performance-wise than I originally thought.
