### ISSUE TITLE
System.Security.Cryptography.X509Certificates.Tests outerloop failing

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#38781]
Fails since 2.7.2020.
These 4 tests are failing:
|Type|Method|Arguments|
| ---|------|---------|
|System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests|RevokeEndEntity_PolicyErrors_NotTimeValid|policyErrors: True, notTimeValid: False|
|System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests|RevokeEndEntity_PolicyErrors_NotTimeValid|policyErrors: True, notTimeValid: True|
|System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests|RevokeIntermediate_PolicyErrors_NotTimeValid|policyErrors: True, notTimeValid: False|
|System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests|RevokeIntermediate_PolicyErrors_NotTimeValid|policyErrors: True, notTimeValid: True|

Reproduces locally.
AzDO fail, e.g.: https://dev.azure.com/dnceng/public/_build/results?buildId=715844&view=ms.vss-test-web.build-test-results-tab&runId=22182572&resultId=104464&paneView=debug

When reverted https://github.com/dotnet/runtime/pull/38182, the tests pass locally.
cc: @wfurt

**Comment by vcsjones** [comment]
This appears to be a duplicate of #38744

**Comment by ManickaP** [comment]
Duplicate of #38744
