### ISSUE TITLE
Possible de-reference of null pointer in `debugger.h`

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#38792]
https://github.com/dotnet/runtime/blob/312c758edc524ef941bce5cebd289a628f0182cf/src/coreclr/src/debug/ee/debugger.h#L741-L755

dereferencing a possible null pointer `dipce` in `dipce->next = NULL` before the null check nullifies (heh) the null check. `dipce->next = NULL` probably should be moved into `if (dipce != NULL)`.

**Comment by mikem8361** [comment]
It doesn't look used to me either.  Have you tried to removing it and building?
