### ISSUE TITLE
Many test failures in "nohwintrinsics" jobs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#38841]
In both the `runtime-coreclr jitstress-isas-x86` and `runtime-coreclr jitstress-isas-arm` pipelines, the "nohwintrinsics" (and for arm, the "nosimd") jobs are failing about 40 tests (about 20 for arm).

https://dev.azure.com/dnceng/public/_build/results?buildId=716582&view=ms.vss-test-web.build-test-results-tab&runId=22206304&resultId=108832&paneView=debug
https://dev.azure.com/dnceng/public/_build/results?buildId=716578&view=ms.vss-test-web.build-test-results-tab&runId=22205912&paneView=debug&resultId=105800

@tannergooding @CarolEidt @echesakovMSFT

**Comment by tannergooding** [comment]
Will take a look

**Comment by tannergooding** [comment]
This is essentially https://github.com/dotnet/runtime/issues/35605. Basically, `EnableHWIntrinsic=0` no longer disables `SSE+`. This means that the JIT is setting `Vector<T>` to be 32-bytes but the software fallback is getting executed, which assumes 16-bytes.

The fix should be relatively small and I am testing it out locally.

**Comment by BruceForstall** [comment]
@tannergooding The proposed PR is https://github.com/dotnet/runtime/pull/38879? How is this coming along? (Of course, the weekend test runs failed again.)

**Comment by tannergooding** [comment]
@BruceForstall, https://github.com/dotnet/runtime/pull/38879 fixes (I believe) all the x86 issues.

There is still an ARM64 issue tthat I haven't finished investigating that is causing some remaining failures

**Comment by tannergooding** [comment]
Closing. The last -arm job fully passed (https://dev.azure.com/dnceng/public/_build?definitionId=665) and the last x86 job only had eventpipe failures which are unrelated: https://dev.azure.com/dnceng/public/_build?definitionId=664
