### ISSUE TITLE
src\libraries\Common\src\Interop\Windows\Kernel32\Interop.DeviceIoControl.cs appears to be a dead file

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/runtime#38861]
`src\libraries\Common\src\Interop\Windows\Kernel32\Interop.DeviceIoControl.cs` (and all other files related to `DeviceIoControl`) appear to be unused in dotnet/runtime.

It looks like they were introduced to support System.Data.SqlClient (dotnet/corefx#29879), but no longer used as Microsoft.Data.SqlClient is maintained in dotnet/SqlClient.

**Comment by stephentoub** [comment]
Thanks.  If they're unused, let's delete 'em.  CI will help confirm they're not used anywhere.
