### ISSUE TITLE
Play and Capture Audio

### ISSUE THREAD

**Issue by sipsorcery** [dotnet/runtime#38886]
## Background and Motivation

There should be a way to play and capture audio with .Net Core. For some reason it's always been missing and to rub salt in the wounds even newer SDK's, much younger than .Net, such as Go and Rust, have this capability.

On top of that there are numerous Azure API's that take and return PCM 8K and 16K audio samples but to actually use those samples on anything other than Windows requires jumping through some big hoops.

## Proposed API

[NAudio](https://github.com/naudio/NAudio) would be a good basis for an API. NAudio's weakness is it only supports Windows.

## Usage Examples

An example of initialising and using an audio output device with NAudio:

````C#
public override async Task Start()
{
	if (!IsStarted)
	{
		await base.Start();

		// Render device.
		_waveOutEvent = new WaveOutEvent();
		_waveOutEvent.DeviceNumber = AUDIO_OUTPUTDEVICE_INDEX;
		_waveProvider = new BufferedWaveProvider(_waveFormat);
		_waveProvider.DiscardOnBufferOverflow = true;
		_waveOutEvent.Init(_waveProvider);
		_waveOutEvent.Play();

		// Audio source.
		if (WaveInEvent.DeviceCount > 0)
		{
			_waveInEvent = new WaveInEvent();
			_waveInEvent.BufferMilliseconds = AUDIO_SAMPLE_PERIOD_MILLISECONDS;
			_waveInEvent.NumberOfBuffers = 1;
			_waveInEvent.DeviceNumber = AUDIO_INPUTDEVICE_INDEX;
			_waveInEvent.WaveFormat = _waveFormat;
			_waveInEvent.DataAvailable += LocalAudioSampleAvailable;

			_waveInEvent.StartRecording();
		}
		else
		{
			Log.LogWarning("No audio capture devices are available. No audio stream will be sent.");
		}

		base.OnRemoteAudioSampleReady += RemoteAudioSampleAvailable;
	}
}

private void RemoteAudioSampleAvailable(byte[] pcmSample)
{
	_waveProvider?.AddSamples(pcmSample, 0, pcmSample.Length);
}
`````

**Comment by SingleAccretion** [comment]
> NAudio's weakness is it only supports Windows.

There is a wrapper for VLC which should be cross-plat. I do not think it supports capture though.

In general, what are the scenarios? It seems like it would be a lot of work to make this work on Windows, and Linux, and MacOS, and Android, and iOS, and Browser.

**Comment by sipsorcery** [comment]
> In general, what are the scenarios?

In my case the scenarios I have needed this capability for in the recent past are;
 
 - Play and capture audio/video for VoIP calls.
 - Play and capture audio/video for WebRTC sessions,
 - Playback audio from the Azure text-to-speech service,
 - Capture audio for the Azure speech-to-text service,
 - Play and capture audio with the Skype Bot API for a call to Microsoft Teams.

> It seems like it would be a lot of effort to make this work on Windows, and Linux, and MacOS, and Android, and iOS, and Browser.

It would definitely be a big job. At the moment and for the last 18 years we've had to use different tricks or bits and pieces from other Microsoft SDK's. One way to perhaps short circuit the work would be to rely on ffmpeg as some other Microsoft projects have started to do. It has very good cross platform support and has basic audio/video capture/render features. I think it still uses DirectShow so it wouldn't be able to provide access to all the latest and greatest webcam features but I suspect basic audio and video would be more in demand than pan-tilt-zoom.

**Comment by danmosemsft** [comment]
As you know this repo is for the base libraries. API at this level needs to be stable for a long time, and is commensurately slow to change. We tend to have a single implementation, that is likely to be uncontroversial and suitable for everyone. We think of tech like audio and video as a better fit for higher in the stack, where libraries can move quickly, break API if needed, and be opinionated - different API/SDK for different needs, OS, hardware - and owned by teams with real expertise in it.

**Comment by sipsorcery** [comment]
Fair enough although imho playback of PCM 8k/16k audio is as basic as it gets and will not change. I got my hopes up that once Azure ($$) .Net SDK's started requiring audio IO then the next step would for it to get supported in the base class library. I haven't seen anywhere higher up the stack very interested; there are some rudimentary XAML (UWP only) controls with very very rudimentary audio/video capabilities but that seems to be about it.

> API at this level needs to be stable for a long time

I've lived through .Net Remoting, Silverlight etc. The current PCM audio encoding format standard was created in the 70's, is pretty much universally  supported by lower level OS API's, such as Windows Media Foundation, and is unlikely to change in the next 50 years.

But apologies for the whinge. It's only because the .Net Core cross platform support works as well as it does that we want more and more from it. I doubt I've got the energy to do the cross platform .Net Core interop with ffmpeg for audio/video support but fingers crossed that eventually someone will.

**Comment by danmosemsft** [comment]
To be clear -- I'm not suggesting such a library would be a good idea, cross platform or not. Just that it's probably not a good fit for this repo, which is the most core of the .NET libraries. We have some great community graphics libraries - it seems like there could be a great community audio library if there isn't one already. I'd be happy to refer folks to it.
