### ISSUE TITLE
 Change DAC to use MachOReader to lookup "g_dacTable" symbol instead of the rva header file hack

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#38901]
This is a cleanup work item to remove the RVA header file scripts and logic the DAC uses to get the g_dacTable from the runtime on MacOS, FreeBSD, NetBSD and SunOS.  MacOS can use the new MachOReader but the rest can use the ElfReader to lookup the symbol.

[12/9/2020] This is work that needs to be done for MacOS Single File

**Comment by tommcdon** [comment]
Not needed for single file, so closing

**Comment by mikem8361** [comment]
This is needed for MacOS single-file because the RVA of the global DAC table in the single-file exe isn't consistent. The DAC needs to use the global symbol to find the table.
