### ISSUE TITLE
Timer Docs incorrect for TimeSpan overload

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#38911]
[See](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer.-ctor?view=netcore-3.1#System_Threading_Timer__ctor_System_Threading_TimerCallback_System_Object_System_TimeSpan_System_TimeSpan_)

> dueTime
TimeSpan
The amount of time to delay before the callback parameter invokes its methods. Specify negative one (-1) milliseconds to prevent the timer from starting. Specify zero (0) to start the timer immediately.

> period
TimeSpan
The time interval between invocations of the methods referenced by callback. Specify negative one (-1) milliseconds to disable periodic signaling.

However it should read `Specify System.Threading.Timeout.Infine to prevent the timer from starting.` on both parameters.

**Comment by juliusfriedman** [comment]
cc @danmosemsft, @jkotas

**Comment by stephentoub** [comment]
> incorrect

Timeout.Infinite is -1.  And Timeout.InfiniteTimeSpan is TimeSpan.FromMilliseconds(-1).  So the docs aren't incorrect, but there's always room for improvement.

**Comment by danmosemsft** [comment]
@juliusfriedman if you like you can submit a PR to clarify the doc (click the pencil button on the doc)

**Comment by juliusfriedman** [comment]
But passing TimeSpan.InfiniteTimeout also seems to work, perhaps there is a whole there?

**Comment by stephentoub** [comment]
> But passing TimeSpan.InfiniteTimeout also seems to work, perhaps there is a whole there?

There is no TimeSpan.InfiniteTimeout.

If you mean Timeout.InfiniteTimeSpan, as I stated that's the same as -1 milliseconds. It's named that and defined as such to be usable in this manner.

**Comment by juliusfriedman** [comment]
Correct, `Timeout.InfiniteTimeSpan` my apolagies.
So the question remains if I was to fix this would you rather people use `Timeout.InfiniteTimeSpan` per the docs or should this stay the way it is? I feel the current read is confusing and I feel like we should point people to `Timeout.InfiniteTimeSpan` but that is my own opinion.

**Comment by stephentoub** [comment]
I'm fine if the docs highlight Timeout.InfiniteTimeSpan.

**Comment by juliusfriedman** [comment]
https://github.com/dotnet/dotnet-api-docs/pull/4496
