### ISSUE TITLE
Some transport packages are pushed to nuget.org

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#38924]
Discussed this with @ViktorHofer, we think this shouldn't be happening:

- https://www.nuget.org/packages/transport.Microsoft.NET.SDK.IL
- https://www.nuget.org/packages/transport.Microsoft.NETCore.ILasm
- https://www.nuget.org/packages/transport.Microsoft.NETCore.ILDAsm
- https://www.nuget.org/packages/transport.Microsoft.NETCore.TestHost

**Comment by ViktorHofer** [comment]
cc @jashook @trylek @jkotas

**Comment by BruceForstall** [comment]
Maybe @jkoritzinsky knows about this?

**Comment by jkoritzinsky** [comment]
I did not know about this. We definitely shouldn't be shipping these

**Comment by BruceForstall** [comment]
Is there someone on this issue who would be the best equipped (most knowledgeable) to fix the problem? (and be assigned the issue)

**Comment by jkoritzinsky** [comment]
I think @hoyosjs or @ericstj might know about how to fix this since they've both recently touched the CoreCLR pkgproj files.

**Comment by ericstj** [comment]
I believe these need to be treated as Non-shipping.  I believe if the set the appropriate property then the right thing happens.  Arcade has docs on it.  I know we set it by convention in libraries.

**Comment by hoyosjs** [comment]
There's a bunch of things that should be non-shipping but are not:

```xml
  <Package Id="transport.dotnet-ilverify" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.Microsoft.ILVerification" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.Microsoft.NET.Sdk.IL" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.Microsoft.NETCore.ILAsm" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.Microsoft.NETCore.ILDAsm" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.Microsoft.NETCore.TestHost" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.runtime.win-x64.Microsoft.NETCore.ILAsm" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.runtime.win-x64.Microsoft.NETCore.ILDAsm" Version="5.0.0-rc.1.20374.5" />
  <Package Id="transport.runtime.win-x64.Microsoft.NETCore.TestHost" Version="5.0.0-rc.1.20374.5" />
```

That's controlled by the `IsShipping` property. I'll take a look given that the transport package is non-shipping, but the runtime packages are meant to be.

**Comment by hoyosjs** [comment]
Looks like they are all produced by the same target from the packaging task in Arcade:

![image](https://user-images.githubusercontent.com/19413848/88441244-5ebe4280-cdc5-11ea-8fb1-3250fcdd6d7f.png)

Do we need both symbol and transport packages? Runtime and transport packages are identical except for symbols in the package, but I'm not sure if the consumers of transport packages need the symbols (removing the transport packages could also break repos downstream, but removing them is as simple as `CreatePackedPackage` set to false). @jkoritzinsky, do you know if any of the SDK logic needs them? Now we do all the crossgen here, so I'm not sure. The problem is both packages get dropped in `PackageOutputPath` and there's no way I see to split that. I'd have to modify arcade, and that feels heavy-handed.

**Comment by jkoritzinsky** [comment]
I don't know of any part of the stack that uses the transport packages.

**Comment by ericstj** [comment]
The purpose of transport packages in the past was to share bits between repositories for the purpose of repackaging (eg: between coreclr and core-setup, or SDK).  It's possible these are non longer needed with the repo merge.  Not sure, you could probably search for consumers.

**Comment by hoyosjs** [comment]
I took a look. A few things:

- Symbol packages already have all the necessary binaries + symbols. This will ensure symbol indexing.
- For runtime packs for IL tools, the only RID that has a transport package getting published is win-x64. This makes me think it's unlikely we have direct consumers. I couldn't find any references in dnceng or devdiv.
- The other weird bug here is the Lineup packages for ILasm and ILDasm have runtime bits, while they should only have runtime.json manifests.
