### ISSUE TITLE
TimeSpan more singleton options

### ISSUE THREAD

**Issue by BratulescuMihai** [dotnet/runtime#38934]
I would like some more singleton options for TimeSpan: Hour, Day, Week

Maybe even Month (30 days) and Year (365), I understand these two would be up for debate.

**Comment by Joe4evr** [comment]
There's no point in any of these since `TimeSpan` is a struct, so there's no advantage to any "singleton" instances because you always copy them by-value. You can just as easily already use `TimeSpan.FromHours(1)`, `TimeSpan.FromDays(1)`, and `TimeSpan.FromDays(7)`, respectively.

**Comment by joperezr** [comment]
Given the above comment that @Joe4evr provided, we agree that this wouldn't really be beneficial so I'll go ahead and close this issue for now and would encourage to instead use the alternatives provided on that same comment. @BratulescuMihai feel free to reopen if you still think that there is a proposal that we should consider here.
