### ISSUE TITLE
System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited hangs in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#38943]
Configuration: `net5.0-OSX-Release-x64-Mono_release-OSX.1014.Amd64.Open`

https://helix.dot.net/api/2019-06-17/jobs/6fafb787-3aa8-4715-a1f4-2573e59b0da3/workitems/System.Diagnostics.Process.Tests/files/console.af56a1ee.log

https://dnceng.visualstudio.com/public/_build/results?buildId=720820&view=ms.vss-test-web.build-test-results-tab&runId=22326810&paneView=debug

```
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 220 of 290 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 12)
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Darwin
    System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"
    System.Diagnostics.Tests.ProcessTests.CanBeFinalized [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:02:10
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:04:11
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:06:12
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:08:13
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:10:14
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:12:15
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_WaitAfterExited', Elapsed: 00:14:15
```

**Comment by adamsitnik** [comment]
I've sent a PR to disable this test for Mono to unblock the CI https://github.com/dotnet/runtime/pull/40837 and moving this to 6.0

@jeffhandley @marek-safar how area owners should handle Mono-specific issues?

**Comment by jeffhandley** [comment]
> I've sent a PR to disable this test for Mono to unblock the CI #40837 and moving this to 6.0
> 
> @jeffhandley @marek-safar how area owners should handle Mono-specific issues?

Thanks, Adam! We'll want to put a little more time into this later to try to narrow it down to see if we can find the appropriate mono area that we would move it into. But since we've already punted this out to 6.0.0 and disabled the test for now, there's no urgency on it as far as I'm concerned.

/cc @lewing @steveisok

**Comment by CoffeeFlux** [comment]
Interesting that this doesn't happen with `SingleProcess_WaitAsyncAfterExited`.

**Comment by jkotas** [comment]
Failed in #42112

**Comment by steveisok** [comment]
Interesting that there are only 7 records in Kusto that have passed and taken longer than 3 seconds.  And 28 records taking longer than 1 second.  

Also interesting that there's a 2 min run for each iteration in both the original and what @jkotas just indicated.

**Comment by jaredpar** [comment]
@ViktorHofer no failures in last 14 days. Do u want to keep this open and make a live issue or close?

https://runfo.azurewebsites.net/search/tests/?bq=definition%3Aruntime+started%3A%7E14&tq=SingleProcess_WaitAfterExited

**Comment by ViktorHofer** [comment]
14 days without a hit should be enough to justify closing the issue. I expect us to reopen when we hit it again in CI.
