### ISSUE TITLE
Saving/restoring of extended context during thread suspension

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#38974]
Thread suspension does not save/restore full extended context on Windows, `CONTEXT_XSTATE` e.g. AVX registers.

If some code in the thread suspension handler happens to use these register, it will show up as intermittent data coruption.

**Comment by jkotas** [comment]
Found via codereview

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/runtime/pull/47212

**Comment by mangod9** [comment]
Opening so that #47212 can be ported to 5.0 if required.

**Comment by VSadov** [comment]
Fixed in:
6.0 - https://github.com/dotnet/runtime/pull/47212
5.0 - https://github.com/dotnet/runtime/pull/47447
3.1 - https://github.com/dotnet/coreclr/pull/28131
