### ISSUE TITLE
Setting the calendar to use for the current culture to UmAlQuraCalendar on Linux-x64 isn't working

### ISSUE THREAD

**Issue by legrandb** [dotnet/runtime#38986]
### Description

When I'm trying to set the culture to UmAlQuraCalendar on Linux-x64 I get the error:
`System.ArgumentOutOfRangeException: Not a valid calendar for the given culture. (Parameter 'value') Actual value was System.Globalization.UmAlQuraCalendar.`

Here is the code I use to do It:
`CultureInfo arEG = CultureInfo.CreateSpecificCulture("ar-EG");
 arEG.DateTimeFormat.Calendar = new UmAlQuraCalendar();`
 

### Configuration

The issue happen on Linux-x64, with .Net Core 3.1.
On windows no bug occurs.
With the same configuration the ThaiBuddhistCalendar is well setted

**Comment by tarekgh** [comment]
It is not allowed to set any calendar to any culture. Every culture support specific list of calendars and not all calendars. you can call [CultureInfo.OptionalCalendars](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.optionalcalendars?view=netcore-3.1) to know which calendars are supported for any specific culture. UmAlQura calendar is not one of the optional calendars for ar-EG. you need to use a culture like ar-SA to use UmAlQura calendar.

something like:

```C#

	CultureInfo ci = new CultureInfo("ar-SA");
	ci.DateTimeFormat.Calendar = new UmAlQuraCalendar();
```

**Comment by tarekgh** [comment]
By the way, you should get the same behavior on Windows if you have the `CultureInfo.CurrentCulture` set to `ar-EG` too.

**Comment by legrandb** [comment]
Thank you for your answer 
Unfortunately the error is also happening for :

```
CultureInfo ci = new CultureInfo("ar-SA");
 ci.DateTimeFormat.Calendar = new UmAlQuraCalendar();
```

On linux UmAlQuraCalendar is not supported by the ar-SA culture:
The ar-SA culture supports the following calendars: 
```
System.Globalization.GregorianCalendar (Localized)
 System.Globalization.HijriCalendar
```

On windows UmAlQuraCalendar is supported by the ar-SA culture:
```
The ar-SA culture supports the following calendars:
   System.Globalization.UmAlQuraCalendar
   System.Globalization.HijriCalendar
   System.Globalization.GregorianCalendar (USEnglish)
   System.Globalization.GregorianCalendar (MiddleEastFrench)
   System.Globalization.GregorianCalendar (Arabic)
   System.Globalization.GregorianCalendar (Localized)
   System.Globalization.GregorianCalendar (TransliteratedFrench)
```

By the way the ar-EG support the `UmAlQuraCalendar` on windows.

**Comment by tarekgh** [comment]
I just ran the following code on Linux Ubuntu 18.04:
```C#
    foreach (Calendar cal in CultureInfo.GetCultureInfo("ar-SA").OptionalCalendars)
    {
        Console.WriteLine(cal);
    }
```

and I am seeing the following result which containing UmAlQura:

```
System.Globalization.UmAlQuraCalendar
System.Globalization.GregorianCalendar
System.Globalization.HijriCalendar
```

To explain more, when running on Linux, we use the ICU library for the globalization support. ICU gives us the supported list of the calendars for each locale/culture. it is possible your system is using old version of the ICU library. could you check that and let's know? on my system I have the following ICU version:

```
❯ uconv -V
uconv v2.1  ICU 60.2
```

> By the way the ar-EG support the UmAlQuraCalendar on windows.

You are right. first, ICU doesn't set UmAlQura as optional calendar for Egypt so if you run on Linux you'll not see UmAlQura listed i. Second, I was running using .NET Core 5.0 which is using ICU when running on Windows too. That is why I didn't see UmAlQura as optional calendar for Egypt.
