### ISSUE TITLE
API Proposal: Add PlatformID.Unknown value

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#38984]
## Background and Motivation

With the addition of more platforms to dotnet/runtime the existing .NET Framework APIs are missing way to express them. Instead of duplicating logic between `System.Runtime.InteropServices.RuntimeInformation` API and old .NET Framework APIs we introduce generic undefined value for old APIs.

## Proposed API

```diff
namespace System
{
    public enum PlatformID
    {
        MacOSX = 6,
+       Unknown = 7,
    }
```

**Comment by bartonjs** [comment]
API review suggests that "Other" is a better name, since it is "known" to not be one of the other values.

```diff
namespace System
{
    public enum PlatformID
    {
        MacOSX = 6,
+       Other = 7,
    }
```

Additionally, if we haven't already done obsoletion plans for this enum and the things related to it, it's probably a good idea.

**Comment by marek-safar** [comment]
> Additionally, if we haven't already done obsoletion plans for this enum and the things related to it, it's probably a good idea.

I agree is that work is tracked elsewhere?
