### ISSUE TITLE
[wasm] Calling Interop.Sys.* results in EntryPointNotFoundException

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#38987]
Trying to run the assembly tests on WASM, I faced some failures related to Interop.Sys.* methods invocation. In particular, I'm observing it for System.Net.NetworkInformation:
```
<failure exception-type="System.EntryPointNotFoundException">
    <message><![CDATA[System.EntryPointNotFoundException : SystemNative_EnumerateInterfaceAddresses assembly:<unknown assembly> type:<unknown type> member:(null)]]></message>
    <stack-trace><![CDATA[   at System.Net.NetworkInformation.UnixIPGlobalProperties.GetUnicastAddresses()
     at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.GetUnicastAddresses_NotEmpty()
--- End of stack trace from previous location ---]]></stack-trace>
</failure>
```
Even though, this particular case doesn't make much sense on browser (the entire System.Net.NetworkInformation will be PNSE), 
Interop.Sys.* can be used in some other places.

**Comment by lewing** [comment]
@MaximLipnin I think this should all be throwing PNSE now, is the reproduction just running the the System.Net tests?

@kjpou1 please follow and verify they are throwing
