### ISSUE TITLE
GenerateReferenceAssemblySource generates old license header

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#38992]
It should now generate only the new 2-line version introduces in: https://github.com/dotnet/runtime/pull/38793
It still generates the old 3-line version.

![image](https://user-images.githubusercontent.com/11718369/87037449-8372c180-c1ec-11ea-8a4d-342e08318f4a.png)

**Comment by stephentoub** [comment]
Being fixed by https://github.com/dotnet/runtime/pull/38973
