### ISSUE TITLE
Rename "tools-local" folder to "tools"

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#39007]
We have some local MSBuild tasks that don't come from arcade and are part of the `tools-local` folder. 

This naming convention came from the repo consolidation as this was how `core-setup` named it. The reason for that name, is because back in the days when we used buildtools, buildtools would restore the tools and would put them in a folder called "tools" in the root of the repo, so to avoid that clash, we named it "tools-local". 

Nowadays everything that comes from arcade is under `eng/common` so I think to avoid confusion, we should rename it to `tools` since it is implicitly "local"

cc: @jkotas @stephentoub @danmosemsft @dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
Please see https://github.com/dotnet/runtime/issues/36519 which talks about removing the tools-local folder entirely.

**Comment by safern** [comment]
Dang it, I should've searched for that 😄. Closing as a dupe then.
