### ISSUE TITLE
authentication proxy required

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/runtime#39014]
Hello,

I have problem when i call API using Default proxy on .NET Core 3.1

```c#
protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                VSMP_Settings = new XmlDocument();

                if (OperatingSysteme.IsLinux())
                {
                    VSMP_Settings.Load(Xml_Settings_PathLin);
                }
                else
                {
                    VSMP_Settings.Load(Xml_Settings_PathWin);

                }

                var _proxyswitch = Convert.ToBoolean(VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Proxy_SettingsAtos//ProxySwitch").InnerText);
                var _proxyurl = VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Proxy_SettingsAtos//ProxyUrl").InnerText;
                var _proxyport = Convert.ToInt32(VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Proxy_SettingsAtos//ProxyPort").InnerText);
                if (_proxyswitch)
                {
                    var proxy = new WebProxy(_proxyurl, _proxyport);
                    proxy.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;

                    HttpClient.DefaultProxy = proxy;

                    LogHelper.Writer("Bypass proxy utilisé : " + proxy.Address);
                }

                HttpResponseMessage response = null;

                _applicationId = VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Contracts_Settings//HmacID").InnerText;
                _secretKey = VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Contracts_Settings//HmacSecret").InnerText;

                var _secretKeyUTF8 = UTF8Encoding.UTF8.GetBytes(_secretKey);
                string nonce = Guid.NewGuid().ToString("N");

                var gbCulture = new CultureInfo("en-GB");
                // Get current UTC time.   
                var utcDate = DateTime.UtcNow;

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss UTC", gbCulture);

                //string Date = "date:" + UpperCaseUrlEncode(str);
                string Date = "date: " + utcFormattedDate;
                //Date = "date:Thu%2C+21+Apr+2016+13%3A32%3A18+UTC";
                using (HMACSHA1 hmac = new HMACSHA1(_secretKeyUTF8))
                {
                    byte[] Datebytes = Encoding.UTF8.GetBytes(Date);
                    byte[] hashedValue = hmac.ComputeHash(Datebytes);
                    string Signature = Convert.ToBase64String(hashedValue);
                    string Url_Encoded_Signature = UpperCaseUrlEncode(Signature);
                    request.Content = new StringContent(string.Empty, Encoding.UTF8, "application/json");

                    request.Headers.Add("Authorization", string.Format("Signature keyId=\"{0}\",algorithm=\"{1}\",signature=\"{2}\"", _applicationId, "hmac-sha1", Url_Encoded_Signature));

                    var field = typeof(HttpRequestHeaders).GetField("invalidHeaders",BindingFlags.NonPublic | BindingFlags.Static)?? typeof(HttpRequestHeaders).GetField("s_invalidHeaders", BindingFlags.NonPublic | BindingFlags.Static);
                    if (field != null)
                    {
                        var invalidFields = (HashSet<string>)field.GetValue(null);
                        invalidFields.Remove("Content-Type");
                    }
                    request.Content.Headers.Remove("Content-Type");
                    //request.Headers.Add("Accept-Encoding", "gzip");
                    request.Content.Headers.Add("Content-Type", "application/json;charset=UTF-8");
                    request.Content.Headers.TryAddWithoutValidation("Date", utcFormattedDate);
                }
              
                response = await base.SendAsync(request, cancellationToken).ContinueWith<HttpResponseMessage>(task =>
                {
                    return task.Result;
                });
                LogHelper.Writer("La réponse : " + response.StatusCode);

                return response;
            }
```

I get error message : 9/07/2020 21:50:59   |   Bypass proxy used: http://193.56.47.8:8080/
09/07/2020 21:51:00   |   response : ProxyAuthenticationRequired
09/07/2020 21:51:00   |   Error when importing contracts from the web service, error message: 0
System.Exception: Exception of type 'System.Exception' was thrown.

area-System.Net.Http | @karelz | @dotnet/ncl |  
area-System.Net.Security | @karelz | @dotnet/ncl |  
area-System.Net.Sockets | @karelz | @dotnet/ncl

**Comment by wfurt** [comment]
What is your OS version @HASSEN-MEDDEB-ATOS? Can you get packet captures?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @wfurt, thnaks for your answer, my os version redhat 7 and i used .NET Core 3.1, i used 2 proxy, one proxy to connect to dynamics crm used clientSecret and the second to connect to WS
before i used 
````````
var proxy = new WebProxy(_proxyurl, _proxyport);
                    proxy.Credentials = new NetworkCredential(_proxylogin, _proxypass);
                    WebRequest.DefaultWebProxy = proxy;

````````
but @davidsh  suggest us to use HttpClient

````````
  var proxy = new WebProxy(_proxyurl, _proxyport);
                    HttpClient.DefaultProxy.Credentials = CredentialCache.DefaultCredentials;
                    HttpClient.DefaultProxy = proxy;
                    LogHelper.Writer("Bypass proxy utilisé : " + proxy.Address);
````````

Cordially

**Comment by wfurt** [comment]
I'm yet to understand your setup @HASSEN-MEDDEB-ATOS. On Linux, the proxy is configured vie environment variables. So I'm not sure how you distingues two different proxies. Also, DefaultCredentials are somewhat tricky on Linux.  Unlike Windows, there is no real binding to actually user (since there is no Kerberos under the cover)
Providing complete simple app would be useful.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
You are right
actually when i enter the commands
export http_proxy = myproxy1: port;
export https_proxy = myproxy1: port;
i can  access to my web services and I recover the different registrations
But I can't no longer authenticate with my secret client; and when I use the second proxy
export http_proxy = myproxy2: port;
export https_proxy = myproxy2: port;

I can authentificate on azure using secret client but  I lose the connection with my webservices

I'm looking for a trick to just be able to call proxy1 just when calling WebServices .

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @davidsh @karelz  any suggestion please

**Comment by wfurt** [comment]
You should be able to set proxy explicitly. The environment is just default. The part I don't understand is why you use DefaultCredentials and how do you manage CredentialCache. Do both proxies use same authentication?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hi @wfurt ,

I have used  DefaultCredentials  to Gets the system credentials of the application.  the proxies don't use the same authentification :/

**Comment by wfurt** [comment]
`proxy.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;` ?
From the example it is not clear to me how do you populate the CredentialCache and how you do you manage the proxy duality. Also I just noticed that you assign `DefaultProxy.Credentials` but the you replace DefaultProxy with different object effectively wiping out the line above. 
Why don't you post complete runable minimal repro with your logic? (it is ok if the proxies are not reachable)

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Ok, you are right, i have putted 
export http_proxy=http://.................. 
export http_proxy=http://..................
For my Web Services 

and for my CRM : i have putted 
````````
   var proxy = new WebProxy(_proxyurl, _proxyport);
                    HttpClient.DefaultProxy.Credentials = new NetworkCredential(_proxylogin, _proxypass);
                    HttpClient.DefaultProxy = proxy;
                    LogHelper.Writer("Proxy used to connect to CRM : " + proxy.Address + " " + "Port : " + proxy.Address.Port);
````````
Now i can connect to my CRM but i get error when connect to WEB API : ProxyAuthentificationRequired

however I have putted my proxy which opens the flow to my API in the environment variables

Cordially

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hi @mconnew any suggestion please :)

**Comment by wfurt** [comment]
The point I was trying to make is that  `HttpClient.DefaultProxy = proxy;` sets `HttpClient.DefaultProxy.Credentials` to `null`. You either need to flip the order or set credentials like  `proxy.Credentials = new NetworkCredential();`
It is hard to help you with small fragments you showing. If you want to move forward, please provide full runnable repro.

**Comment by karelz** [comment]
Closing for now as it is not actionable. We need a minimal repro we can run locally without code that is not needed to provide any further advice or help.
Feel free to reopen when you have standalone minimal repro available. Thanks!
