### ISSUE TITLE
Support for macOS running on Apple Silicon

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#39010]
Hi!

Is there a plan to build & distribute dotnet sdk/runtime for Apple Silicon based macOS in the near future?

Linked issues: https://github.com/mono/mono/issues/20007, https://github.com/dotnet/runtime/issues/10036.

**Comment by jkotas** [comment]
Yes, we are actively looking into this and we will be sharing the plan soon. cc @tommcdon @richlander

**Comment by k15tfu** [comment]
@jkotas Awesome. Yes please keep me in touch!

**Comment by joperezr** [comment]
Closing as the question has been answered, and we won't be using this issue once we have more info to share.

**Comment by k15tfu** [comment]
@joperezr Could you post a new link to follow up on?

**Comment by danmosemsft** [comment]
@k15tfu I don't think there's another link, probably best to watch the .NET blog https://devblogs.microsoft.com/dotnet/

**Comment by k15tfu** [comment]
I would rather take it as a meta issue of lack of support, with clarification that you plan to work on this. It was strange to close the issue for developers/contributors and ask to follow the blog.

**Comment by danmosemsft** [comment]
Fair enough..@richlander do you plan an Epic issue in this repo for Apple Silicon?

**Comment by richlander** [comment]
@danmosemsft ... good question. Yes.

In short:

- 3.1.7+ and 5.0 will be "preview supported" running as x64 under Rosetta 2.
- .NET 6.0 will support Apple Silicon (AKA ARM64).

**Comment by k15tfu** [comment]
Found these ones:
* Epic: Support Apple Silicon https://github.com/dotnet/runtime/issues/43313
* Enable .NET Core on Apple Silicon https://github.com/orgs/dotnet/projects/18#card-44036333
* Enable ASP.NET Core on Apple Silicon https://github.com/dotnet/aspnetcore/issues/26821
* Build .NET SDK for Apple Silicon https://github.com/dotnet/installer/issues/8840
