### ISSUE TITLE
[Perf -5%] System.Tests.Perf_Decimal.TryParse

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39027]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Tests.Perf_Decimal

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
TryParse | 88.63 ns | 102.01 ns | 1.15 |  | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Tests.Perf_Decimal_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Tests.Perf_Decimal.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Decimal*';
```
<details>

#### System.Tests.Perf_Decimal.TryParse(value: "123456.789")

```log
[ 84.869 ;  87.053) | @@@
[ 87.053 ;  90.324) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 90.324 ;  93.222) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 93.222 ;  96.700) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 96.700 ; 100.073) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[100.073 ; 104.362) | @@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
This regression is much closer to 5% then the 15% shown by the tool, we just happened to pick a low baseline. Looking at the rolling average we see a 5% regression, that looks pretty stable.

**Comment by joperezr** [comment]
@DrewScoggins is there an easy way on this issues to tell if this is a regression from 3.1? Marking as 5.0 for now in case it is a regression and will move to future if that is not the case.

**Comment by DrewScoggins** [comment]
So if you click into the link that goes to the historical results you can look at the seven build moving average of the master branch. In that you can see that the master branch was in line with the results of 3.1 until around late February, when we saw the regression updward. 
![image](https://user-images.githubusercontent.com/9439069/87464587-36b23080-c5c8-11ea-9424-7093a524d628.png)

**Comment by danmosemsft** [comment]
This one seems pretty marginal to me. Depending on which point I pick in both lines, they can be quite close or overlap. @DrewScoggins is there a way for me to generate a fuller (newer) report?

**Comment by DrewScoggins** [comment]
Looking at this one here, https://pvscmdupload.blob.core.windows.net/reports/07_29_2020/report_Daily_ca%3Dx64_cb%3Dmaster_co%3DWindows1018362_cr%3Ddotnetcoresdk_cc%3DCompliationMode%3Dtiered-RunKind%3Dmicro_Baseline_bb%3Drelease-3.1.1xx_2020-07-29.html, I don't see it showing as regression. This is not too surprising to me as this one was also pretty close when we filed it. It was done more out of an abundance of caution. Given that we don't seem to be seeing the regression anymore, I am fine closing this until we see data that is a stronger indicator.

**Comment by danmosemsft** [comment]
Thanks @DrewScoggins . How can I find updated reports like that in future by myself?

**Comment by DrewScoggins** [comment]
You can find the perf reports at aka.ms/dotnetperfstatus
