### ISSUE TITLE
[Perf -492%] System.Linq.Tests.Perf_Enumerable.FirstWithPredicate_LastElementMatches

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39032]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Linq.Tests.Perf_Enumerable

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
TakeLastHalf | 468.70 ns | 514.79 ns | 1.10 |  | False
FirstWithPredicate_LastElementMatches | 663.99 ns | 3.94 μs | 5.94 | Bimodal | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Linq.Tests.Perf_Enumerable_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Linq.Tests.Perf_Enumerable_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Linq.Tests.Perf_Enumerable.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Linq.Tests.Perf_Enumerable*';
```
<details>

#### System.Linq.Tests.Perf_Enumerable.TakeLastHalf(input: List)

```log
[456.467 ; 475.142) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[475.142 ; 490.020) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[490.020 ; 504.707) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[504.707 ; 518.671) | @@@@@@@@@@@@@
```
#### System.Linq.Tests.Perf_Enumerable.FirstWithPredicate_LastElementMatches(input: IOrderedEnumerable)

```log
[ 588.698 ;  804.631) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 804.631 ; 1020.564) | 
[1020.564 ; 1236.497) | 
[1236.497 ; 1452.431) | 
[1452.431 ; 1668.364) | 
[1668.364 ; 1884.297) | 
[1884.297 ; 2100.231) | 
[2100.231 ; 2316.164) | 
[2316.164 ; 2532.097) | 
[2532.097 ; 2748.030) | 
[2748.030 ; 2963.964) | 
[2963.964 ; 3179.897) | 
[3179.897 ; 3395.830) | 
[3395.830 ; 3611.764) | 
[3611.764 ; 3840.029) | 
[3840.029 ; 4087.029) | @@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by stephentoub** [comment]
This is by design: https://github.com/dotnet/runtime/pull/36643.
