### ISSUE TITLE
CMake WIN32 usage

### ISSUE THREAD

**Issue by mathstuf** [dotnet/runtime#3904]
As stated in dotnet/coreclr#69, `WIN32` is currently used all over the place to mean a couple things:
- the generator is multi-configuration;
- the host platform is Windows;
- the generator is Visual Studio; and
- the compiler is MSVC.

Counter examples: Xcode is also multi-config, Ninja works on Windows, cross-compiling exists, and Clang works on Windows. The proper way to do these are:
- check `CMAKE_CONFIGURATION_TYPES`; if it exists, the generator is multi-config;
- `CMAKE_GENERATOR MATCHES "Visual Studio"`
- check `MSVC` to set MSVC-specific flags.

This is a larger task since all uses of `WIN32` are suspect right now. About the only place it should be used is when checking things that are related to Windows being the _target_ platform of the current build.

**Comment by AaronRobinsonMSFT** [comment]
We now build using Ninja. Seems like this issue can be closed.

**Comment by Arunprakash142** [comment]
Hi, this is Arunprakash. I like the way the article is explained. The content is very good. If any of the engineering students who are looking for a Artificial Neural Network Projects I found this site and they are providing  the best service to the engineering students regarding the projects [Artificial Neural Network Projects](https://takeoffprojects.com/Artificial-Neural-Network-Projects)
