### ISSUE TITLE
load/store memory unaligned for type LONG and type long

### ISSUE THREAD

**Issue by shushanhf** [dotnet/runtime#39054]
### Description

runtime/src/coreclr/src/pal/inc/pal_mstypes.h        Line:241
<pre>
typedef int LONG;       // NOTE: diff from windows.h, for LP64 compat 
typedef unsigned int ULONG; // NOTE: diff from windows.h, for LP64 compat
</pre>
Why defining LONG as int ?

runtime/src/coreclr/src/vm/vars.cpp     Line:31
<pre>
Volatile < LONG >       g_TrapReturningThreads;               <-------------here is int
</pre>

runtime/src/coreclr/src/vm/arm64/asmhelpers.S
<pre>
 777     PREPARE_EXTERNAL_VAR g_TrapReturningThreads, x2
 778     ldr x3, [x2]                                <---------------------here loading is long, the addr is not aligned
</pre>

runtime/src/coreclr/src/vm/amd64/pinvokestubs.S
<pre>
200         // Check return trap
201         PREPARE_EXTERNAL_VAR g_TrapReturningThreads, rax
202         cmp             dword ptr [rax], 0                               <---------------------here loading is long, the addr is not aligned
</pre>

while in the JIT comiler loading the g_TrapReturningThreads is also unaligned.
The JIT see it as long type.

for example, mips64-CoreCLR
<pre>
   0xff7c8df5a8:    lui a0,0xff
   0xff7c8df5ac:    ori a0,a0,0xf7a0
   0xff7c8df5b0:    dsll    a0,a0,0x10
   0xff7c8df5b4:    ori a0,a0,0xeb7c           <-------this is not 8-byte aligned.
=> 0xff7c8df5b8:    ld  a0,0(a0)
</pre>

**Comment by jkotas** [comment]
> ldr x3, [x2]  

This is a bug. It should be loading it as 32-bit int.

**Comment by jkotas** [comment]
> Why defining LONG as int ?

The PAL definitions match Windows. LONG is defined as 32-bit on Windows.

**Comment by jkotas** [comment]
> cmp             dword ptr [rax], 0

This is loading it as 32-bit int. Not a bug.

**Comment by shushanhf** [comment]
> should

That means  the "Volatile < LONG >       g_TrapReturningThreads;  " is int type.
while on 64bit-processor liking arm64, amd64 and mips64, we should also define LONG as int ?

**Comment by jkotas** [comment]
> while on 64bit-processor liking arm64, amd64 and mips64, we should also define LONG as int ?

Correct.

**Comment by shushanhf** [comment]
> > cmp             dword ptr [rax], 0
> 
> This is loading it as 32-bit int. Not a bug.

Thanks ~

**Comment by jkotas** [comment]
Keeping this open to fix the bug in src/coreclr/src/vm/arm64/asmhelpers.S

**Comment by shushanhf** [comment]
> > while on 64bit-processor liking arm64, amd64 and mips64, we should also define LONG as int ?
> 
> Correct.

I'm sorry for closing.

**Comment by shushanhf** [comment]
> Keeping this open to fix the bug in src/coreclr/src/vm/arm64/asmhelpers.S

clicking for misktake.

**Comment by shushanhf** [comment]
> > while on 64bit-processor liking arm64, amd64 and mips64, we should also define LONG as int ?
> 
> Correct.

How to processe it during the JIT compiler,
<pre>
$8 = {_vptr$GenTree = 0xff57783920 <vtable for GenTreeIntCon+16>, gtOper = GT_CNS_INT, gtType = TYP_LONG, gtOperSave = GT_NONE, gtCSEnum = 0 '\000',
  gtLIRFlags = 0 '\000', gtAssertionInfo = {m_isNextEdgeAssertion = 0, m_assertionIndex = 0}, gtCostsInitialized = true, _gtCostEx = 1 '\001', _gtCostSz = 1 '\001',
  gtRegTag = GenTree::GT_REGTAG_REG, _gtRegNum = 4 '\004', gtFlags = 3489660928, gtDebugFlags = 26, gtVNPair = {m_liberal = 4294967295, m_conservative = 4294967295},
  gtRsvdRegs = 0, gtNext = 0x1200c4188, gtPrev = 0x1200c4098, gtTreeID = 129, gtSeqNum = 138, gtUseNum = 27,
  static gtOperKindTable = 0xff5763af90 <GenTree::gtOperKindTable>,
  static s_gtNodeSizes = 0xff577a9c04 <GenTree::s_gtNodeSizes> "xxxxxxxxx\310\310xxxxxxxxxx\310xxx\310x\310xxxxxxx\310\310\310xx\310\310\310\310", 'x' <repeats 30 times>, "\310x\310\310x\310xxxxxxx\310\310\310\310\310\310", 'x' <repeats 20 times>, "\310\310xxxx", static MAX_CHILDREN = 6, static s_vtablesForOpers = {0x0, 0x0,
    0xff57784430 <vtable for GenTreeLclFld+16>, 0xff577843d0 <vtable for GenTreeLclVar+16>, 0x0, 0xff577843d0 <vtable for GenTreeLclVar+16>,
    0xff57784430 <vtable for GenTreeLclFld+16>, 0x0 <repeats 26 times>, 0xff57783a50 <vtable for GenTreeIndir+16>, 0x0 <repeats 32 times>,
    0xff57783ab0 <vtable for GenTreeOp+16>, 0x0, 0x0, 0x0, 0xff57783ab0 <vtable for GenTreeOp+16>, 0x0 <repeats 20 times>, 0xff577844c0 <vtable for GenTreeCall+16>,
    0x0 <repeats 25 times>, 0xff577840c0 <vtable for GenTreeStmt+16>}, static s_vtableForOp = 0xff57783ab0 <vtable for GenTreeOp+16>}
</pre>
The  "gtType = TYP_LONG" is not TYP_INT.

**Comment by shushanhf** [comment]
Here is the place getting addr of g_TrapReturningThreads , is it right ?
<pre>
 3968         GenTree* value; // The value of g_TrapReturningThreads
 3969         if (pAddrOfCaptureThreadGlobal != nullptr)
 3970         {
 3971             // Use a double indirection
 3972             GenTree* addr =
 3973                 gtNewIndOfIconHandleNode(TYP_I_IMPL, (size_t)pAddrOfCaptureThreadGlobal, GTF_ICON_PTR_HDL, true);
 3974 
 3975             value = gtNewOperNode(GT_IND, TYP_INT, addr);
 3976             // This indirection won't cause an exception.
 3977             value->gtFlags |= GTF_IND_NONFAULTING;
 3978         }
 3979         else
 3980         {
 3981             // Use a single indirection
 3982             value = gtNewIndOfIconHandleNode(TYP_INT, (size_t)addrTrap, GTF_ICON_PTR_HDL, false);
 3983         }
</pre>
Here is setting it as TYP_INT.

I will conform it on mips64.

**Comment by jkotas** [comment]
Right. `TYP_INT` in the JIT is 32-bit. `TYP_LONG` in the JIT is 64-bit.

**Comment by shushanhf** [comment]
> Right. `TYP_INT` in the JIT is 32-bit. `TYP_LONG` in the JIT is 64-bit.

Thanks, I will backport to mips64.
