### ISSUE TITLE
Type.IsInterface returns different values between .NET and Mono for byref types

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#39068]
### Description

Test case:

```csharp
interface I {}

Console.WriteLine (typeof (I).MakeByRefType ().IsInterface);
```

shows True with Mono and False with .NET (on macOS using .NET Core using MonoVM).

Complete test case: [consoleapp-fbd84e3.zip](https://github.com/dotnet/runtime/files/4902973/consoleapp-fbd84e3.zip)

Download, unzip, and run `make both`:

```shell
 $ make both
Mono output:
    I& IsInterface: True
.NET output:
    I& IsInterface: False
```

### Configuration

```shell
$ dotnet --version
5.0.100-preview.7.20317.11
```

* What OS and version, and what distro if applicable?

macOS 10.15

**Comment by marek-safar** [comment]
@lambdageek could you investigate what broke?

**Comment by lambdageek** [comment]
There's no bug in the netcore version of Mono.  Its output matches CoreCLR (and also .NET Framework, FWIW).

The outlier is Mono 6.* from https://github.com/mono/mono which prints `True` while all the rest print `False`.

If we want to fix this in mono/mono, I'll move the bug there.

**Comment by lambdageek** [comment]
The issue btw, is this code.  Non-netcore Mono would need to do the `byref` check, too.

https://github.com/dotnet/runtime/blob/ce51448da23e12b27c6193efeaf7f1e69e43b0fd/src/mono/mono/metadata/icall.c#L2178-L2189

**Comment by marek-safar** [comment]
Closing as by-design
