### ISSUE TITLE
override methode cant call base.methode

### ISSUE THREAD

**Issue by HossienMehdikhah** [dotnet/runtime#39071]
### Description

`public class UserManagement<TUser> : UserManager<TUser>`
`{`
  `public async override Task<IdentityResult> CreateAsync(TUser user, string password)`
    `{`
      `user.ConcurrencyStamp = Guid.NewGuid().ToString();`
      `var temp = await base.CreateAsync(user, password).ConfigureAwait(false);`
      `await AddToRoleAsync(user, typeof(TUser).Name.Replace("Set", string.Empty)).ConfigureAwait(false);`
      `await SendRegisterConfirmationEmailAsync(user, true).ConfigureAwait(false);`
      `return IdentityResult.Success;`
    `}`
`}`

**Comment by HossienMehdikhah** [comment]
@jaredpar

**Comment by mangod9** [comment]
Hey @HossienMehdikhah, could you please provide a simple repro + error its generating. Assume you are checking whether base.CreateAsync should be allowed from within the overridden CreateAsync ?

**Comment by HossienMehdikhah** [comment]
hi @mangod9. sorry for incomplete question. i fix it so can  you delete it ?

**Comment by mangod9** [comment]
thanks for the update.
