### ISSUE TITLE
PreserializedResourceWriter embeds stale System.Resources.Extensions version, failing at runtime on desktop Framework

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/runtime#39078]
This issue was reported in comments at https://github.com/microsoft/msbuild/issues/4704#issuecomment-645145418.

### Description

Here's a project that references System.Resources.Extensions 4.7.1. It fails to extract resources at runtime with

```
System.IO.FileLoadException: Could not load file or assembly 'System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)

=== Pre-bind state information ===
LOG: DisplayName = System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///S:/repro/microsoft/msbuild/issues/4704/ResourceError/bin/Debug/net48/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: S:\repro\microsoft\msbuild\issues\4704\ResourceError\bin\Debug\net48\ResourceError.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: Attempting download of new URL file:///S:/repro/microsoft/msbuild/issues/4704/ResourceError/bin/Debug/net48/System.Resources.Extensions.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

The copied assembly is the updated `4.0.1.0`.

[ResourceError.zip](https://github.com/microsoft/msbuild/files/4903827/ResourceError.zip) from https://github.com/microsoft/msbuild/issues/4704#issuecomment-645145418 (thanks, @EamonHetherton!)

### Regression?

Sort of? It works with `System.Resources.Extensions` 4.6.0.

### Other information

I think this is happening because of this hardcoding

https://github.com/dotnet/runtime/blob/4dccf9a5e1127f8be192b6b9b2f102138d620f6d/src/libraries/System.Resources.Extensions/src/System/Resources/Extensions/PreserializedResourceWriter.cs#L20-L22

Which works fine on .NET Core's assembly loader (located assembly newer than referenced) but fails on Framework.

**Comment by rainersigwald** [comment]
cc @ericstj

**Comment by ericstj** [comment]
Cc @Anipik 

Binding Redirect will workaround.  It’s not necessarily caused by hard coding. It’s caused by version used by MSBuild gets out of sync with version references by app.  I wonder if we need MSBuild to know the version when writing.  🤔

**Comment by tarekgh** [comment]
@ericstj did we decide what we'll do here? or the workaround will be enough by doing binding redirect?

**Comment by ericstj** [comment]
I think @rainersigwald would need to weigh in on thoughts of plumbing a version to the code which is writing the resources.

One thing we could do here is include targets in the package to always suggest the bindingRedirect.  We did this with the WinRT contracts last release.

**Comment by rainersigwald** [comment]
We already grovel through the references of the currently-being-built project to find _whether_ it references `System.Resources.Extensions`; it wouldn't be hard to extract and use that version. But we'd need an API change to support passing that in, right?

Always suggesting a binding redirect via package logic makes sense to me and is pretty low-cost.

**Comment by ericstj** [comment]
Given RAR will never see the version that is burned into resources, even if we did have GenerateResource write a higher version we'd still miss cases like the following.

App uses S.R.E 5.0.0.0
Lib uses S.R.E 4.0.0.0 (no reference to S.R.E types except in resource stream).

To handle this I think bindingRedirect is actually a better solution than GenerateResource.  Let's fix this in 5.0 by adding net4x specific targets (taking care not to apply those targets to net5 :))

**Comment by EamonHetherton** [comment]
Can someone elaborate on the correct way to do this binding redirect workaround?

I've tried this in my reproduction project as attached in the top of this post but no joy.

`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Resources.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0-4.0.0.0" newVersion="4.0.1.0" />
      </dependentAssembly>      
    </assemblyBinding>
  </runtime>
</configuration>`

**Comment by ericstj** [comment]
Here's what worked for me.

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Resources.Extensions" culture="neutral" publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Double check your setting is making into the final config and that is what is being used (previously shared log message with fusion log will show this).

**Comment by EamonHetherton** [comment]
👍 
I'd added it to the app.config file for the library, all good once I add it to the executable's app.config

**Comment by stonstad** [comment]
I don't believe this made it into .NET 4.8.  I'm still seeing this behavior.

**Comment by Anipik** [comment]
@ericstj do we have plans to ship the fix for .NET 4.8 ?
