### ISSUE TITLE
NullReferenceException when parsing regular expression

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/runtime#39077]
### Description

The following code raises an NRE:

```c#
Regex("(?(?x)yesno)")
// System.NullReferenceException: Object reference not set to an instance of an object.
```

Expected: a normal `ArgumentException` as any invalid regex raises that. The error in this regex is that the conditional part missing an alternation character `|`. Correct would be: `?(?x)yes|no)`

Note that `(?(x)yesno)` compiles fine, so there's an argument to be made for the above to compile fine too, as technically they should be equivalent (a conditional alternation with only a true-part).

_(found while working on https://github.com/dotnet/runtime/issues/38872, but not related to that issue per se)_

**Comment by stephentoub** [comment]
This was fixed in .NET Core several versions ago.  It now produces:
"Unhandled exception. System.Text.RegularExpressions.RegexParseException: Invalid pattern '(?(?x)yesno)' at offset 5. Unrecognized grouping construct."

**Comment by abelbraaksma** [comment]
My bad, I accidentally tested 4.8 only,which clearly didn't get that fix. Glad it's solved!
