### ISSUE TITLE
RuntimeInformation.RuntimeIdentifier unknown on Browser wasm

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#39074]
When running tests for `System.Runtime.InteropServices.RuntimeInformation.Tests`, this failure is encountered because `AppContext.GetData("RUNTIME_IDENTIFIER")` does not yet work for wasm, leading to `RuntimeInformation.RuntimeIdentifier` being unknown. It is typically set by the hosting app.
```
[FAIL] System.Runtime.InteropServices.RuntimeInformationTests.RuntimeIdentifierTests.VerifyOSRid
Assert.EndsWith() Failure:
Expected:    Wasm
Actual:   ···nown
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by marek-safar** [comment]
That's odd we hardcode it as a constant value

**Comment by marek-safar** [comment]
@steveisok please assign

**Comment by steveisok** [comment]
Ah!  I'll add it to https://github.com/dotnet/runtime/pull/39446
