### ISSUE TITLE
Move System.Runtime.Serialization.Formatters.Binary.BinaryFormatter to CoreLib

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#39090]
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter type is always required by System.Private.CoreLib because it's used for resources serialization/deserialization. The required code after trimming in size sensitive scenarios ends up quite small (about 6kB) which indicates there is not a large chunk of code to be moved.

Moving the implementation would help reduce the number of file transfers for browser and get rid of extra reflection call in  https://github.com/dotnet/runtime/blob/9907151841e30ab11e9dcc4e818c25735b7026c3/src/libraries/System.Private.CoreLib/src/System/Resources/ResourceReader.Core.cs#L68-L86

@eerhardt

**Comment by GrabYourPitchforks** [comment]
`BinaryFormatter` doesn't work at all in browser after the changes in https://github.com/dotnet/runtime/pull/38963 come online. Why not ifdef this code away in wasm? Or condition this check on the internal API `SerializationInfo.IsBinaryFormatterEnabled` (also part of that PR), which will always evaluate to _false_ on wasm and other scenarios where BF is intended to be trimmed away?

**Comment by jkotas** [comment]
I agree with @GrabYourPitchforks . System.Runtime.Serialization.Formatters.Binary.BinaryFormatter has problematic security characteristics. It is better for it to be in separate binary.

**Comment by eerhardt** [comment]
> The required code after trimming in size sensitive scenarios ends up quite small (about 6kB) which indicates there is not a large chunk of code to be moved.

Note that it is that small because the linker is removing all the methods from the type. This is because it can't automatically detect the above reflection usage and produces a warning (which we are currently ignoring all warnings).

See the conversation here: https://github.com/dotnet/runtime/pull/38432#discussion_r446268741

**Comment by GrabYourPitchforks** [comment]
If there aren't any objections, I'll experiment with sending a new iteration of https://github.com/dotnet/runtime/pull/38963 that addresses this code path as well.

**Comment by GrabYourPitchforks** [comment]
@marek-safar These code paths should no longer be called in wasm applications, so there should be no remaining references to the Formatters package. Anything else we need to do here?

**Comment by eerhardt** [comment]
I don't believe there is anything else we need to do here. After linking a Blazor WASM app with the latest runtime, I am not seeing `System.Runtime.Serialization.Formatters.dll` in the output at all.
Closing.
