### ISSUE TITLE
[mono][Browser] Interpreter doesn't fully support UnmanagedCallersOnly

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#39100]
Currently, the only way to pass a managed callback to a pinvoke in Mono-Wasm-Interp is to use `IntPtr` + `Marshal.GetFunctionPointerForDelegate` + `MonoPinvokeCallbackAttribute`.

/cc @vargaz 

I will use link to this issue for workarounds.

**Comment by EgorBo** [comment]
Once fixed, `MonoPInvokeCallbackAttribute` should be removed from `System.Private.CoreLib`

**Comment by jkotas** [comment]
I have extended this workaround to apply to all Mono targets in https://github.com/dotnet/runtime/pull/39082
