### ISSUE TITLE
Remove GetICUVersion from being preserved unconditionally by the ILLinker

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#39102]
We have one entry in CoreLib's ILLink.Descriptors.xml that is only used for testing:

https://github.com/dotnet/runtime/blob/b779870a391ed4e6021a40b317508a1fab817820/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Descriptors.Shared.xml#L3-L6

We should remove this entry so the method is trimmed when linking an app. See @marek-safar's comment here: https://github.com/dotnet/runtime/issues/35199#issuecomment-656734139

> Marking it all the time will cause problems for us in InvariantMode when the native part won't be available and we need to statically link it.

One option would be to make a "_LibraryBuild.xml" file for CoreLib and only preserve this method when doing the "library build". The descriptor entry won't be embedded into the assembly, so it won't be picked up when linking the user's application.

@safern @joperezr @layomia

**Comment by tarekgh** [comment]
I am wondering how much we'll gain when trimming this method? is it really worth it?

**Comment by eerhardt** [comment]
It isn't so much about the size gain. The size gain is super minimal.

The bigger issue is the static linking with InvariantMode, as mentioned above.

**Comment by jkotas** [comment]
So can we make it conditional on InvariantMode?

**Comment by marek-safar** [comment]
What is the motivation to have this pinvoke compiled into SPC at all? My understanding is that this is used for some test checks only, why the pinvoke cannot be defined in test assembly directly?

**Comment by tarekgh** [comment]
> why the pinvoke cannot be defined in test assembly directly?

This was discussed when we introduced using ICU on Windows. The reason we preferred having it there is because the test assembly not aware if the ICU is loaded at all in the process or not or we are in NLS mode or ICU mode. Or if we are in NLS mode and somehow someone loaded ICU in the process for any other reason. having it in the SPC make it just straight forward if we are really in ICU mode without any heuristics.

**Comment by safern** [comment]
> why the pinvoke cannot be defined in test assembly directly?

Also, the reason why this PInvoke wasn't added into the test assembly directly is because the PInvoke is a QCall, which is internal and only allowed from `System.Private.CoreLib` since `System.Globalization.Native` shim is linked into mono and coreclr.

**Comment by marek-safar** [comment]
I see. I agree with @eerhardt that the simplest solution then is to move the rule to "_LibraryBuild.xml" file for SPC.

**Comment by eerhardt** [comment]
This work isn't necessary to ship 5.0, so moving to 6.0.

**Comment by eerhardt** [comment]
Resolved by #48120.
