### ISSUE TITLE
[Perf -25%] System.Memory.Constructors<String> (2)

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39113]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Memory.Constructors<String>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
ReadOnlyMemoryFromArray | 3.78 ns | 4.60 ns | 1.22 |  | False
ReadOnlyMemoryFromArrayStartLength | 3.79 ns | 4.84 ns | 1.28 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Memory.Constructors(String)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Memory.Constructors(String)_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Memory.Constructors(String).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Memory.Constructors<String>*';
```
<details>

#### System.Memory.Constructors<String>.ReadOnlyMemoryFromArray

```log
[3.751 ; 3.862) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3.862 ; 3.998) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3.998 ; 4.116) | 
[4.116 ; 4.233) | 
[4.233 ; 4.351) | 
[4.351 ; 4.468) | 
[4.468 ; 4.632) | @@@@@@
```
#### System.Memory.Constructors<String>.ReadOnlyMemoryFromArrayStartLength

```log
[3.638 ; 3.735) | @
[3.735 ; 3.847) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3.847 ; 3.932) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3.932 ; 4.088) | @@@@@@@@
[4.088 ; 4.241) | 
[4.241 ; 4.393) | 
[4.393 ; 4.545) | 
[4.545 ; 4.698) | 
[4.698 ; 4.779) | 
[4.779 ; 4.952) | @@@@@
[4.952 ; 5.077) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by GrabYourPitchforks** [comment]
Was this regression seen only on linux? Trying to narrow down what may have been the culprit.

**Comment by DrewScoggins** [comment]
Yes, we are only seeing it there.

**Comment by adamsitnik** [comment]
Overall 5.0 is on par with 3.1 and producing smaller native code, so I am closing. Full details below.

<details>

``` ini

BenchmarkDotNet=v0.12.1.1405-nightly, OS=ubuntu 18.04
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-rc.1.20413.9
  [Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
  Job-SYKXBJ : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 3.1  Arguments=/p:DebugType=portable  
Toolchain=netcoreapp3.1  IterationTime=250.0000 ms  MaxIterationCount=20  
MinIterationCount=15  WarmupCount=1  

```
|                             Method |     Mean |     Error |    StdDev |   Median |      Min |      Max | Code Size | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------- |---------:|----------:|----------:|---------:|---------:|---------:|----------:|------:|------:|------:|----------:|
|            ReadOnlyMemoryFromArray | 4.453 ns | 0.0169 ns | 0.0150 ns | 4.453 ns | 4.433 ns | 4.481 ns |      83 B |     - |     - |     - |         - |
| ReadOnlyMemoryFromArrayStartLength | 4.457 ns | 0.0177 ns | 0.0165 ns | 4.455 ns | 4.432 ns | 4.489 ns |      91 B |     - |     - |     - |         - |

## .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
```assembly
; System.Memory.Constructors`1[[System.__Canon, System.Private.CoreLib]].ReadOnlyMemoryFromArray()
       push      rbp
       sub       rsp,10
       vzeroupper
       lea       rbp,[rsp+10]
       xor       eax,eax
       mov       [rbp-10],rax
       lea       rax,[rbp-10]
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [rax],xmm0
       mov       rax,[rdi+8]
       test      rax,rax
       jne       short M00_L00
       lea       rax,[rbp-10]
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [rax],xmm0
       jmp       short M00_L01
M00_L00:
       mov       [rbp-10],rax
       xor       edi,edi
       mov       [rbp-8],edi
       mov       eax,[rax+8]
       mov       [rbp-4],eax
M00_L01:
       mov       rax,[rbp-10]
       mov       rdx,[rbp-8]
       lea       rsp,[rbp]
       pop       rbp
       ret
; Total bytes of code 83
```

## .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
```assembly
; System.Memory.Constructors`1[[System.__Canon, System.Private.CoreLib]].ReadOnlyMemoryFromArrayStartLength()
       push      rbp
       sub       rsp,10
       vzeroupper
       lea       rbp,[rsp+10]
       xor       eax,eax
       mov       [rbp-10],rax
       lea       rax,[rbp-10]
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [rax],xmm0
       mov       rax,[rdi+8]
       test      rax,rax
       je        short M00_L00
       mov       edi,[rax+8]
       cmp       rdi,0A
       jb        short M00_L01
       mov       [rbp-10],rax
       xor       eax,eax
       mov       [rbp-8],eax
       mov       dword ptr [rbp-4],0A
       mov       rax,[rbp-10]
       mov       rdx,[rbp-8]
       lea       rsp,[rbp]
       pop       rbp
       ret
M00_L00:
       call      System.ThrowHelper.ThrowArgumentOutOfRangeException()
       int       3
M00_L01:
       call      System.ThrowHelper.ThrowArgumentOutOfRangeException()
       int       3
; Total bytes of code 91
```
**Method was not JITted yet.**
System.ThrowHelper.ThrowArgumentOutOfRangeException()

``` ini

BenchmarkDotNet=v0.12.1.1405-nightly, OS=ubuntu 18.04
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-rc.1.20413.9
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
  Job-QTZUVH : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 5.0  Arguments=/p:DebugType=portable  
Toolchain=netcoreapp5.0  IterationTime=250.0000 ms  MaxIterationCount=20  
MinIterationCount=15  WarmupCount=1  

```
|                             Method |     Mean |     Error |    StdDev |   Median |      Min |      Max | Code Size | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------- |---------:|----------:|----------:|---------:|---------:|---------:|----------:|------:|------:|------:|----------:|
|            ReadOnlyMemoryFromArray | 4.465 ns | 0.0091 ns | 0.0076 ns | 4.465 ns | 4.455 ns | 4.477 ns |      71 B |     - |     - |     - |         - |
| ReadOnlyMemoryFromArrayStartLength | 4.244 ns | 0.0098 ns | 0.0087 ns | 4.245 ns | 4.228 ns | 4.257 ns |      81 B |     - |     - |     - |         - |

## .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
```assembly
; System.Memory.Constructors`1[[System.__Canon, System.Private.CoreLib]].ReadOnlyMemoryFromArray()
       push      rbp
       sub       rsp,10
       vzeroupper
       lea       rbp,[rsp+10]
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [rbp-10],xmm0
       mov       rax,[rdi+8]
       test      rax,rax
       jne       short M00_L00
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [rbp-10],xmm0
       jmp       short M00_L01
M00_L00:
       mov       [rbp-10],rax
       xor       esi,esi
       mov       [rbp-8],esi
       mov       eax,[rax+8]
       mov       [rbp-4],eax
M00_L01:
       mov       rax,[rbp-10]
       mov       rdx,[rbp-8]
       lea       rsp,[rbp]
       pop       rbp
       ret
; Total bytes of code 71
```

## .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
```assembly
; System.Memory.Constructors`1[[System.__Canon, System.Private.CoreLib]].ReadOnlyMemoryFromArrayStartLength()
       push      rbp
       push      rbx
       sub       rsp,18
       vzeroupper
       lea       rbp,[rsp+20]
       mov       rbx,rdi
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [rbp-18],xmm0
       mov       rax,[rbx+8]
       test      rax,rax
       je        short M00_L00
       mov       edi,[rax+8]
       cmp       rdi,0A
       jb        short M00_L00
       mov       [rbp-18],rax
       xor       eax,eax
       mov       [rbp-10],eax
       mov       dword ptr [rbp-0C],0A
       mov       rax,[rbp-18]
       mov       rdx,[rbp-10]
       lea       rsp,[rbp-8]
       pop       rbx
       pop       rbp
       ret
M00_L00:
       call      System.ThrowHelper.ThrowArgumentOutOfRangeException()
       int       3
; Total bytes of code 81
```
**Method was not JITted yet.**
System.ThrowHelper.ThrowArgumentOutOfRangeException()


</details>
