### ISSUE TITLE
TypeConverterAttribute needs to be annotated so the ILLinker preserves the ctor on the converter

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#39125]
If you link the following app:

```C#
using System;
using System.ComponentModel;
using System.Globalization;

/// <summary>
/// Tests that System.ComponentModel.TypeConverter.ConvertFromInvariantString
/// is not trimmed out when needed by DefaultValueAttribute in a trimmed application.
/// </summary>
class Program
{
    static int Main(string[] args)
    {
        TypeDescriptor.AddAttributes(typeof(string), new TypeConverterAttribute(typeof(MyStringConverter)));

        var attribute = new DefaultValueAttribute(typeof(string), "Hello, world!");
        return (string)attribute.Value == "Hello, world!trivia" ? 100 : -1;
    }

    private class MyStringConverter : StringConverter
    {
        /// <summary>
        /// Converts the specified value object to a string object.
        /// </summary>
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            if (value is string)
            {
                return (string)value + "trivia";
            }

            throw new NotSupportedException();
        }
    }
}
```

It fails because `MyStringConverter` is not getting its ctor preserved. This is because `TypeConverterAttribute` needs to have a `[DynamicallyAccessedMembers(PublicParameterlessConstructor)]` annotations on it:

https://github.com/dotnet/runtime/blob/a9944fa8a721af673999d074caf1dd74617f6ba6/src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs#L33-L41

`ConverterTypeName` is used elsewhere to create the object:

https://github.com/dotnet/runtime/blob/a9944fa8a721af673999d074caf1dd74617f6ba6/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs#L192-L196

@joperezr @layomia

**Comment by MichalStrehovsky** [comment]
That's odd. Linker has some special casing for this attribute:

https://github.com/mono/linker/blob/2b0d31c1bf91d8259fa99f0619fe4e91adb86fe4/src/linker/Linker.Steps/MarkStep.cs#L1559-L1568

Either way, it's preferable to use the dataflow annotations. We should delete the linker handling.

Note the attribute also has a `string` version that should be annotated the same:

https://github.com/dotnet/runtime/blob/a9944fa8a721af673999d074caf1dd74617f6ba6/src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs#L48-L56

**Comment by marek-safar** [comment]
IIRC `PublicParameterlessConstructor` is not the only ctor which needs to be kept so we might need to keep part of the linker logic

**Comment by eerhardt** [comment]
> IIRC PublicParameterlessConstructor is not the only ctor which needs to be kept

TypeConverter supports 2 kinds of constructors:

* A PublicParameterlessConstructor or
* A public constructor that takes a `Type` to support things like `NullableConverter` and `EnumConverter`.

Here is the underlying code in `ReflectTypeDescriptionProvider.CreateInstance`:

https://github.com/dotnet/runtime/blob/7b2364312f2145ffa3bad6e153459b412e1bf264/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L222-L226

So we will probably want `PublicConstructors` in the annotation.
