### ISSUE TITLE
[Perf -81%] System.Threading.Tests.Perf_Thread.GetCurrentProcessorId

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39120]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Threading.Tests.Perf_Thread

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
GetCurrentProcessorId | 4.00 ns | 6.97 ns | 1.74 |  | False

### Related Issue on x86 Windows
[[Perf -42%] System.Threading.Tests.Perf_Thread.GetCurrentProcessorId](https://github.com/DrewScoggins/performance-2/issues/978)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Threading.Tests.Perf_Thread_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Threading.Tests.Perf_Thread.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Threading.Tests.Perf_Thread*';
```
<details>

#### System.Threading.Tests.Perf_Thread.GetCurrentProcessorId

```log
[3.820 ; 4.466) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[4.466 ; 4.738) | 
[4.738 ; 5.385) | @@
[5.385 ; 5.769) | 
[5.769 ; 6.415) | @@@@@@@@@
[6.415 ; 6.928) | @@@@
[6.928 ; 7.575) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7.575 ; 8.434) | @@@@@@@@
[8.434 ; 8.911) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment]
@DrewScoggins  again this diff link is bad.

**Comment by DrewScoggins** [comment]
This should help you track down the diff link.

https://github.com/dotnet/runtime/issues/39122#issuecomment-656941297

**Comment by stephentoub** [comment]
Isn't this the same as https://github.com/dotnet/runtime/issues/37804?

**Comment by DrewScoggins** [comment]
Yes, given that we got that to a point we understand I can close both of these issues.
