### ISSUE TITLE
StringBuilder overload AppendJoin or new RemoveLast

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#39134]
## Background and Motivation

We often remove the last character from a string when building an array in `foreach` notation to remove the trailing comma.

## Example code

```c#
void Main()
{
	var sb = new System.Text.StringBuilder();
	
	 sb.Append('[');
	 
	 foreach (var Int in System.Linq.Enumerable.Range(0, 10)){
	  sb.Append(Int);
	  sb.Append(',');
	 }
	 sb.Remove(sb.Length - 1, 1);
	 sb.Append(']');
	 
	 Console.WriteLine(sb.ToString());
}
```

## Proposed API

```diff
namespace System.Text
{
    public class StringBuilder{
+    public StringBuilder RemoveLast(int count = 1) => m_ChunkOffset + m_ChunkLength > 0 ? Remove(m_ChunkOffset + m_ChunkLength - count) : this;
     }
```

## Usage Examples

```c#
void Main()
{
	var sb = new System.Text.StringBuilder();
	
	 sb.Append('[');
	 
	 foreach (var Int in System.Linq.Enumerable.Range(0, 10)){
	  sb.Append(Int);
	  sb.Append(',');
	 }
	 sb.RemoveLast()
	 sb.Append(']');
	 
	 Console.WriteLine(sb.ToString());
}
```

## Alternative Designs

Warrant a bigger discussion around `foreach` and how one should be allowed to specify the start and end using `Range` syntax etc. (would not solve problems of truly enumerable things unless you stored the enumerator first)

# Proposed API

```diff
namespace System.Text
{
    public class StringBuilder{
+    public StringBuilder AppendJoin(IEnumerable<string> strings, int offset, int count = 1){
   foreach(var str in stings.Skip(offset).Take(count)) AppendJoin(string);
return this;
}
     }
```

## Risks

None, chars are always UTF16 so there is no ambiguity in `count` or the return which is consistent with other methods on that type (useful for chaining).

**Comment by juliusfriedman** [comment]
cc @danmosemsft @jkotas

**Comment by vcsjones** [comment]
Seems like your use-case works well with `AppendJoin`, for what it's worth.

```c#
static void Main() {
    var sb = new StringBuilder();

    sb.Append('[');
    sb.AppendJoin(',', Enumerable.Range(0, 10));
    sb.Append(']');

    Console.WriteLine(sb.ToString());
}
```

I've used `Length--` when I've need to "remove last", or `Length -= n` when needing to remove last `n` number of characters. Is this lacking in some way?

**Comment by juliusfriedman** [comment]
@vcsjones  Perhaps a delegated version of `AppendJoin` is more what I am after:

```c#
long counter = 0;
                    sb.Append('[');
 foreach (Object someObject in someOtherObject.Collection)
                {
                    long objectId = someObject .ID== 0 ? counter++ : someObject .ID;

                    sb.Append('{');

                    sb.Append(FormattableString.Invariant($@"""id"":{ objectId},"));

//...
                    sb.Append('}');

                    sb.Append(',');
                }

                sb.Remove(sb.Length - 1, 1);

                sb.Append(']');
```

**Comment by Clockwork-Muse** [comment]
... I don't know that I'd have reason to use the alternative design, as opposed to just doing the `Skip()`/`Take()` myself.  Especially since _usually_ the thing to do is dump the whole list.  Anything more unusual - like printing start/end of long lists for quick debug, or the differences in the list like XUnit - is going to have to be set up externally anyways,

**Comment by juliusfriedman** [comment]
I am good with the `Length -=` and other proposed alternatives feel free to close this issue for now as there are bigger fish to fry and the library I am using will eventually be updated to System.Text.Json anyway.

**Comment by danmosemsft** [comment]
Ok, closing. Thanks
