### ISSUE TITLE
GC.Resurrect & Better Disposable support around ref struct

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#39146]
## Background and Motivation
Sometimes you finalize an object and you change you mind, perhaps you should be using pools but that is a different issue.

## Proposed API

Ideally also a base disposable class with full async support but is not required.

[A newer this](https://github.com/juliusfriedman/net7mma_core/blob/master/Common/Classes/Disposables/CommonDisposable.cs)

[See the interface](https://github.com/juliusfriedman/net7mma_core/blob/master/Common/Interfaces/IDisposed.cs)

As well as the following methods.

```diff
public static class GC {
+bool Resurrect<T>(ref something) where T : unmanaged;
+bool Resurrect<T>(something) where T : class;
}
```

## Usage Examples

```c#
Wait:
///....
var scope = new CommonDisposable()
Operation:
using(new CommonDisposable()){

}
Done:
GC.Resurrect(scope);
goto Operation;
```

``` C#
GC.Resurrect<T>(ref something) where T : unmanaged;
```

and

``` C#
GC.Resurrect<T>(something) where T : class;
```

## Alternative Designs

```ReRegisterForFinalize<T>``` same overloads

Pooling.

## Risks

Low, better than people getting it wrong.

**Comment by juliusfriedman** [comment]
cc @danmosemsft @jkotas

**Comment by jkotas** [comment]
I do not understand what would `Object.Resurrect` do. For example, how is it different from `GC.ReRegisterForFinalize` ?

**Comment by juliusfriedman** [comment]
It basically doesn't differ at all from `GC.ReRegisterForFinalize` I was just proposing an API which would do that work for the user with respect to the disposable instance (hence where the `CommonDispoable` comes in).

I also think that having the mechanism already in place for users of ref structs is important and that `GC.ReRegisterForFinalize` is not generic.

**Comment by danmosemsft** [comment]
@juliusfriedman an API proposal should explicitly list the proposed API diff please.

**Comment by juliusfriedman** [comment]
Sorry wasn't totally sure where to plop them at first.

**Comment by stephentoub** [comment]
I don't understand. A ref struct can't be finalizable, isn't subject to GC, etc; what does it have to do with resurrection? What does something that meets the unmanaged constraint have to do with resurrection?

**Comment by juliusfriedman** [comment]
> I don't understand. A ref struct can't be finalizable, isn't subject to GC, etc; what does it have to do with resurrection? What does something that meets the unmanaged constraint have to do with resurrection?
> 
> And what benefit is there to ReRegisterForFinalize being generic?

It also can't implement Equals right?

When I treat a ref struct as a disposable tis Dispose method is called without boxing it and that call will be made from the finalizer queue so I treat that at a place where this would be beneficial although one can already work around that by implementing an interface on the ref struct with release semantics right? Not on a ref struct though...

**Comment by GrabYourPitchforks** [comment]
> For the most common cases the benefit is simply not boxing.

Ref structs can never end up on the heap (and as a result can never end up in the finalizer queue), and they can't be used as the _T_ inside a generic method. For example:

```cs
public ref struct MyRefStruct { }

public void DoSomething<T>() { /* no-op */ }

public void Main()
{
    DoSomething<MyRefStruct>(); // compiler error; can't use MyRefStruct as 'T'
}
```

**Comment by stephentoub** [comment]
> I believe in some cases that call will be made from the finalizer queue

No. A ref struct can't live on the heap, it can't be boxed, it can't have a finalizer, it won't ever be in the finalizer queue.

**Comment by juliusfriedman** [comment]
> > For the most common cases the benefit is simply not boxing.
> 
> Ref structs can never end up on the heap (and as a result can never end up in the finalizer queue), and they can't be used as the _T_ inside a generic method. For example:
> 
> ```cs
> public ref struct MyRefStruct { }
> 
> public void DoSomething<T>() { /* no-op */ }
> 
> public void Main()
> {
>     DoSomething<MyRefStruct>(); // compiler error; can't use MyRefStruct as 'T'
> }
> ```

Well then I suppose my proposed API won't be needed or even beneficial for ref structs 👍 

ATP the only benefit of the proposed API (for the class type) would be the non boxing of the object which I myself don't believe is needed in this scenario.

Also thank you for the clarification on the ref struct finalizer, not sure where I got that from...

**Comment by juliusfriedman** [comment]
> > I believe in some cases that call will be made from the finalizer queue
> 
> No. A ref struct can't live on the heap, it can't be boxed, it can't have a finalizer, it won't ever be in the finalizer queue.

noted

**Comment by juliusfriedman** [comment]
You guys are free to close this one, sorry for any detritus. (Still feel like the CommonDisposable and the IDisposed are important pieces here, especially when sharing resources within the ref structs) [Disposable Ref Structs Article](https://tooslowexception.com/disposable-ref-structs-in-c-8-0/)

> In summary
We can treat disposable ref structs as lightweight types that have A REAL destructor, known from C++. It will be executed as soon as the corresponding instance goes out of the scope of the underlying using statement (or enclosing scope in case of using declaration).
For sure it is not a feature that will suddenly become extremely popular in writing regular, business-driven code. But few layers below, when writing high-performant low-level code, it is worth to know about such possibility!

The important distinction here is that a ref struct is never on the finalizer queue and therefor won't benefit from the API I proposed. ( I guess `struct` in general can't really get on the finalizer queue, please correct me if I am wrong as when it's boxed only the box would end up on the finalier queue and then noop if anything. )

Unfortunately that still doesn't solve the sharing of resources issue, e.g. I can only implement `Dispose` for `IDisposable`, not my own interface e.g `IDisposed` or any other variation.

Structs can't inherit either so that means I have to own a lot of repeated code (violation of DRY) or I can opt to use a generic struct to which I can still use `ref` to pass it around like a `ref` struct as well as have the ability to implement interfaces. (talk about splitting hairs) [IStruct](https://github.com/juliusfriedman/net7mma_core/blob/fd895adbce2f4776eee5695431c7b35eb9c1be78/Common/Structures/Struct.cs#L42)

Do with this issue as you will, close it / break it down into other issues etc.

I just had these thoughts while I was writing / reviewing some code and wanted to share my thoughts.

**Comment by GrabYourPitchforks** [comment]
> I guess struct in general can't really get on the finalizer queue

Good question. It's not the `Dispose` method that adds something to the finalizer queue, but rather the existence of a `Finalize` method. I don't know if it's legal in .NET Core for a struct to have a finalizer. But assuming for a minute that it were legal, IMO it'd be truly bizarre if anybody were ever to do this.

**Comment by juliusfriedman** [comment]
> > I guess struct in general can't really get on the finalizer queue
> 
> Good question. It's not the `Dispose` method that adds something to the finalizer queue, but rather the existence of a `Finalize` method. I don't know if it's legal in .NET Core for a struct to have a finalizer. But assuming for a minute that it were legal, IMO it'd be truly bizarre if anybody were ever to do this.

Thank you.

I do not believe a struct can ever have a finalizer yet an object does which is where I got confused I guess. (ValueType)

I am also not sure if this is a C# limitation e.g. if in IL you can definite a struct with a finalizer... but I am fairly certain that no type of struct can have a finalizer as written from the C# compiler.

**Comment by jkotas** [comment]
Thank you for sharing the idea. I think it is best to close this one.

**Comment by Joe4evr** [comment]
> I don't know if it's legal in .NET Core for a struct to have a finalizer.

@GrabYourPitchforks For the record, [it isn't](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0575). I want to say this limitation exists since C#/.NET 1.0, but it would be great if I could find a reference to back that up.

**Comment by juliusfriedman** [comment]
> > I don't know if it's legal in .NET Core for a struct to have a finalizer.
> 
> @GrabYourPitchforks For the record, [it isn't](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0575). I want to say this limitation exists since C#/.NET 1.0, but it would be great if I could find a reference to back that up.

Let me know if you ever find that reference.
