### ISSUE TITLE
StringSegment.EndsWith inconsistent (buggy?) behavior

### ISSUE THREAD

**Issue by adams85** [dotnet/runtime#39140]
### Description

```csharp
Console.WriteLine("/".StartsWith("/", StringComparison.Ordinal));
// prints True

Console.WriteLine(new StringSegment("/").StartsWith("/", StringComparison.Ordinal));
// prints True

Console.WriteLine("/".EndsWith("/", StringComparison.Ordinal));
// prints True

Console.WriteLine(new StringSegment("/").EndsWith("/", StringComparison.Ordinal));
// prints False !!!
```

Is this by design or simply a bug?

### Configuration

.NET Core 3.1.5, Windows 10 x64

**Comment by GrabYourPitchforks** [comment]
FYI to whoever addresses this bug: using `string.Compare` may give incorrect results, especially when dealing with linguistic comparisons (e.g., `StringComparison.InvariantCulture`). Use `CompareInfo.IsPrefix` and `CompareInfo.IsSuffix` instead within the implementation, as it will always give the correct results.

**Comment by maryamariyan** [comment]
Here's the EndsWith logic on StringSegment:

https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L333-L352

The problem is on the comparisonLength.

@adams85 would you like to push up a PR to fix this?

**Comment by adams85** [comment]
@maryamariyan No, I'd pass on this. I guess it's not too much work to fix the method itself but then - if one wants to be thorough - the full codebase needs to be scrutinized to make sure the fix doesn't break anything. Unfortunately, I won't have the time for this in the near future.

**Comment by GrabYourPitchforks** [comment]
Reiterating my previous comment:

The index needs to be fixed, sure. But this code __should not__ use `string.Compare`. It should instead use `CompareInfo.IsPrefix` or `CompareInfo.IsSuffix`, as mentioned earlier.

**Comment by DKittenz** [comment]
I can take this, assign me please.
