### ISSUE TITLE
Support nethost environment undeployment

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#39165]
@MxGrv commented on [Mon Jun 29 2020](https://github.com/dotnet/sdk/issues/12261)

Using the nethost library, one can deploy the .NET Core environment via nethost, using the load_assembly_and_get_function_pointer() routine, but cannot undeploy (unload or terminate) the assemblies and functions in any way, except native process termination. One may want to use the other version of .NET Core, or another [sub-]framework (like, switch from pure .NET Core to .NET Core with Windows extensions support or ASP.NET Core); moreover, correct termination with no memory leakage is desired. Neither nethost.h, nor coreclr_delegates.h do not support this, as seen [here](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#create-a-host-using-nethosth-and-hostfxrh). So, the question is, are there any plans to make a new C to C# library, or to refactor the nethost fundamentally to support proper .NET Core undeployment when needed? Is there any fundamental restriction which would never allow one to implement it (i.e., the whole concept of calling .NET code from native code)?
P.S. Thanks in advance!

**Comment by vitek-karas** [comment]
AFAIK the runtime itself doesn't really support clean unload. So until it does, there's no point in having APIs to do it. I don't know how hard it would be to make the runtime unloadable correctly - maybe @jkotas would know.

**Comment by jkotas** [comment]
The runtime and the core libraries are not designed to be unloadable.

**Comment by vitek-karas** [comment]
This is not in our plans right now (either the runtime or hosting side).
