### ISSUE TITLE
Microsoft.Extensions.Configuration.Binder should only depend on Microsoft.Extensions.Configuration.Abstractions

### ISSUE THREAD

**Issue by lukoerfer** [dotnet/runtime#39168]
According to [its project file](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Configuration.Binder/src/Microsoft.Extensions.Configuration.Binder.csproj) the package `Microsoft.Extensions.Configuration.Binder` depends on both `Microsoft.Extensions.Configuration.Abstractions` and `Microsoft.Extensions.Configuration`. For its functionality, a dependency on the `Abstractions` package should be sufficient. 

Even if this change may be considered negligible, since it only causes minimal overhead, in my opinion it may still be worth to look at it in its its entirety: I noticed this issue when I was working on a project with several sub-projects that only depend on `Abstraction` packages (`DependencyInjection`, `Logging`, `Configuration`). To register a settings class to the dependency container, I used the following module approach:

``` csharp
public class FooModule : IModule
{
    public void Configure(IServiceCollection services)
    {
        services.AddTransient<IService, FooService>();
        services.AddTransient(provider => {
            var configuration = provider.GetRequiredService<IConfiguration>();
            return configuration.GetSection("foo").Get<FooSettings>();
        });
    }
}
```

To use this approach, a dependency on the `Binder` package is required, but this automatically comes with the full `Microsoft.Extensions.Configuration` package.

In my opinion, if it is reasonable to have a separate `Abstractions` package to prevent a dependency on the implementation, this change is reasonable, too. I know that there was a [similar discussion](https://github.com/aspnet/Options/issues/120) on whether a `Microsoft.Extensions.Options.Abstractions` package would be reasonable, which was rejected.

I did not find any information on package dependencies in [Breaking Changes](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/breaking-changes.md) or [Breaking Change Rules](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/breaking-change-rules.md#assemblies), but I guess this change could be categorized as *breaking*, because projects that solely depend on the `Binder` package may stop working.

**Comment by ericstj** [comment]
All unused references will not appear in package-references for all extensions packages that moved to 5.0 as we calculate package dependencies based on assembly references in the final DLL, not those that were in the project file.  Still this is good cleanup.
