### ISSUE TITLE
Unexptected result with EUC-JP encoding

### ISSUE THREAD

**Issue by tomthebearded** [dotnet/runtime#39161]
The following issue has been found in .NET Core 3.0, but can be replicated also in .NET Frameworl 4.7.2.

I'm trying to read a file called kradfile2 (downloadable from [http://nihongo.monash.edu/kradinf.html](http://nihongo.monash.edu/kradinf.html), it's inside the kradzip.zip)

When i open the file in Visual Studio Code with the EUC-JP encoding there isn't any problem, this is for example the firts line
`丂 : 一 勹`
but when i try to read file in my .NET Core project 
`var lines = File.ReadAllLines(path, Encoding.GetEncoding(20932));`
and inspect the first line, which should be identical to the one above, this is the result
`\u008f亜 : 一 勹`

**Comment by ShawnSteele** [comment]
Workaround would be to open it in VS Code then and save as Unicode.

There's a general problem with character encodings in computing in that all OS's/Frameworks/Applications don't necessarily use the same mappings for the data.  Changing behavior, particularly in frameworks consumed by multiple applications, can disrupt data that had been saved in those formats previously.

The general recommendation to avoid the problems introduced by multiple behaviors of character encodings is to use Unicode.

**Comment by tarekgh** [comment]
Also, we support extending the encoding by using [EncodingProvider](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=netcore-3.1) and you can provide your own mapping with the desired behavior.
