### ISSUE TITLE
Disposing of Activity updates Activity.Current before the end event, which different to DiagnosticSource.EndActivity

### ISSUE THREAD

**Issue by cg110** [dotnet/runtime#39179]
### Description
While looking at updating some code to use ActivitySource rather than DiagnosticSource, I noticed that the behavior has changed around ending an activity.

With DiagnosticSource.EndActivity:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceActivity.cs#L44

Activity.Current is updated after the event is fired.

With the new ActivitySource based Activity, when Activity is disposed Current is updated before the end event occurs, as dispose calls Stop:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L579

Is this an expected change in behavior, as it seems inconsistent as Starting an activity sets current and then fires the start event.

I'd expect symmetry between start/stop, and matching the previous DiagnosticSource behavior.

### Configuration

.net framework 4.8
System.Diagnostics.DiagnosticSource nuget: 5.0.0-preview.6.20305.6

### Regression?
No, new functionality in 5.0

### Other information
I believe this is an api issue, I'd like clarity on when Activity.Current is set, as we have logging code decorator that looks at ambient state using Activity.Current.  This picks up Activity info for the Start Event, however, for the End Event it ends up looking at the parent/null, which means the decorator may override properties with Activity.Current (which is the parent), rather than the activity ending.

**Comment by tarekgh** [comment]
@cg110 thanks for reporting the issue. Usually Activity.Current will have the same instance of the Activity object we'll stop which will be sent as the event parameter.So, I guess the current behavior looks better as when you receive the event, you'll have the activity object we are stopping and also you'll have the updated Activity.Current too. But, if this can cause any behavior confusion, I wouldn't mind to change it.

@noahfalk what you think?

**Comment by tarekgh** [comment]
@cijothomas does OT assume anything about the order of the operations here?

**Comment by cg110** [comment]
The problem is more that in our logging framework, we've decorators that add properties to messages, but they don't have access to the activity, they just see a Trace/Log message go through, and attach properties, we currently have an AsyncLocal with a transaction Id, and want to move to trace context.

**Comment by cg110** [comment]
Perhaps this example better explains, the tracing pre-fixes messages with the Trace context:

**Comment by noahfalk** [comment]
Thanks for the report @cg110 👍 

I'd suggest that we match the ordering used by DiagnosticSource - stop event comes before Activity.Current changes. In addition to @cg110's scenario there is probably another one where someone using an ActivityListener wants to emulate the DiagnosticSource events for back-compat. If an ActivityListener.Stop() call was implemented to send DiagnosticSource.Write(activityName + ".Stop") it would be very nice if DiagnosticListeners got that event before Activity.Current was updated, matching previous behavior.

For any code running during the callback that wants to know what the new Activity.Current will be after the callback, it can always evaluate Activity.Parent to find out.

**Comment by tarekgh** [comment]
Sounds good. I'll track fixing this soon then.

**Comment by cijothomas** [comment]
Agree.

**Comment by tarekgh** [comment]
Fixed through the linked PR
