### ISSUE TITLE
How to use System.Text.Decoder parameters

### ISSUE THREAD

**Issue by dhhoang** [dotnet/runtime#39185]
I have a use case where I need to read a stream of UTF8 bytes character by character, while keeping track of the position within the stream. I'm trying to find a way to decode UTF8 bytes into a `char` buffer of size 2 (which is enough to hold any UTF-8 character):
```csharp
void Read(ReadonlySpan<byte> bytes){
  Span<char> chars = stackalloc char[2];
  var decoder = Encoding.UTF8.GetDecoder();
  decoder.Convert(bytes, chars, true, out var bytesUsed, out var charsUsed, out var complete);
}
```
I might misunderstand the usage, but right now I assume `bytesUsed` returns the number of bytes consumed by `decoder`, `charsUsed` returns the number of decoded Unicode `char`. 
However I find the behavior of `Decoder` to be strange. So in order to accommodate for all UTF8 code points, my `bytes` buffer is always 4-byte. The problem is that when decoding a 3-byte code point ("件"), `bytesUsed` returns 4 (instead of the expected 3).
```csharp
var bytes = new byte[4];
Encoding.UTF8.GetBytes("件", bytes);
```
What's even more strange is that when I make `bytes` to contain exactly 3-byte, the `Convert` methods returns `bytesUsed` to be 3 (as expected).
```csharp
var bytes = Encoding.UTF8.GetBytes("件");
```
I tried looking but did not find many useful examples of `System.Text.Decoder` being used. Am I making any mistakes here? Is there an example of how `System.Text.Decoder` is supposed to be used anywhere?

**Comment by tarekgh** [comment]
@dhhoang thanks for reporting the issue. we'll take a look to know what is wrong there. meanwhile, you may try to use the API https://github.com/dotnet/runtime/blob/7b2e585285884d80a4be5389d6a87f59195b7337/src/libraries/System.Private.CoreLib/src/System/Text/Rune.cs#L384 which should help in your scenario.

CC @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
@dhhoang I'm not seeing any of the APIs return _4_ for your scenario. Here's the sample application I have, which demonstrates that the behavior is as expected.

```cs
static void Main(string[] args)
{
    void Read(ReadOnlySpan<byte> bytes)
    {
        Span<char> chars = stackalloc char[2];
        var decoder = Encoding.UTF8.GetDecoder();
        decoder.Convert(bytes, chars, true, out var bytesUsed, out var charsUsed, out var complete);

        Console.WriteLine(bytesUsed); // prints '3'
        Console.WriteLine(charsUsed); // prints '1'
        Console.WriteLine(complete); // prints 'True'
    }

    var bytes = new byte[4];
    int bytesWritten = Encoding.UTF8.GetBytes("件", bytes);
    Console.WriteLine(bytesWritten); // prints '3'
    Read(bytes[0..bytesWritten]);
}
```

Can you provide a standalone repro which demonstrates the API returning _4_?

**Comment by dhhoang** [comment]
@GrabYourPitchforks  In your code snippet, I got `bytesUsed=3` when calling `Read(bytes.AsSpan())` instead of `Read(bytes[0..bytesWritten])` (i.e. convert the whole buffer).
My guess is that `decoder` maintains an internal buffer for incomplete UTF8 sequence?

**Comment by GrabYourPitchforks** [comment]
@dhhoang Yes, it maintains an internal buffer. But in your particular sample, the contents of `bytes[3]` (the byte that wasn't overwritten) was `0x00`, which is a standalone well-formed UTF-8 sequence which converts to the UTF-16 character `\u0000`.

So, for your scenario:

```txt
bytes = [ 00 00 00 00 ] ; freshly allocated
bytes = [ E4 BB B6 00 ] ; first three bytes overwritten by Encoding.UTF8.GetBytes
          |        `-- converts to \u0000
          `----------- converts to \u4ef6

[ E4 BB B6 00 ] as UTF-8 converted to chars -> [ 4EF6 0000 ]
```

If you don't want the extra data (in your case, the trailing null) consumed by the encoder / decoder, you need to slice the input buffer appropriately.

**Comment by dhhoang** [comment]
@GrabYourPitchforks Sorry for providing a bad example, this is another one that fits my use case more:
```csharp
    static async Task Main(string[] args)
    {
        void Read(ReadOnlySpan<byte> bytes)
        {
            Span<char> chars = stackalloc char[2];
            var decoder = Encoding.UTF8.GetDecoder();
            decoder.Convert(bytes, chars, true, out var bytesUsed, out var charsUsed, out var completed);

            Console.WriteLine(bytesUsed); // prints '4'
            Console.WriteLine(charsUsed); // prints '2'
            Console.WriteLine(complete); // prints 'True'
        }

        var bytes = Encoding.UTF8.GetBytes("件る");
        Console.WriteLine(bytes.Length); // prints '6'
        Read(bytes.AsSpan().Slice(0, 4));
    }
```
In this case bytes[3] is the first byte of a new sequence ('る') and `Decoder.Convert` returns `bytesUsed=4` (which is now clear to me since it maintains an internal buffer). 
In this case, should I not expect `completed` to be `false` because not all bytes in `bytes` have been decoded?

**Comment by GrabYourPitchforks** [comment]
The `Convert` method is unfortunately a bit complicated. We tried changing the behavior in 3.0 to return _false_ in the scenario you describe, but it caused [huge compatibility problems](https://github.com/dotnet/runtime/issues/594) and we ended up backing out the change. There's a detailed comment in the code [starting here](https://github.com/dotnet/runtime/blob/7b2364312f2145ffa3bad6e153459b412e1bf264/src/libraries/System.Private.CoreLib/src/System/Text/EncoderNLS.cs#L196) that describes exactly what the _completed_ parameter means.

If you could describe your scenario a bit (what are you trying to do?) we can make recommendations for the right API to call.

**Comment by dhhoang** [comment]
I need to go over a UTF8 byte buffer and process one character at a time (for things like parsing escape sequences etc). I'd like to have a nice way to parse one single UTF8 codepoint at a time in a loop. `System.Text.Rune` seems to be the correct API for that, unfortunately I need to support .NET standard 1.3 which does not have this API.
My current workaround is to find out the number of bytes in a UTF8 sequence from the first byte, so that I can slice the buffer correctly before passing it to `Decoder.Convert`. Seems to work well so far.

**Comment by tarekgh** [comment]
> My current workaround is to find out the number of bytes in a UTF8 sequence from the first byte, so that I can slice the buffer correctly before passing it to Decoder.Convert. Seems to work well so far.

I think this is reasonable workaround till you migrate to .NET 5.0 and then use Rune. I am closing the issue here but feel free to respond back with nay more questions.

**Comment by GrabYourPitchforks** [comment]
> My current workaround is to find out the number of bytes in a UTF8 sequence from the first byte, so that I can slice the buffer correctly before passing it to Decoder.Convert. Seems to work well so far.

This should work fine as long as you can ensure that your input is a well-formed UTF-8 sequence. If your input is not guaranteed well-formed UTF-8, your slice routine could end up operating on the incorrect number of bytes, which might make your `Convert` routine return garbage.

If you do this I would recommend:

```cs
// use this
var encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
var decoder = encoding.GetDecoder();

// not this
var decoder = Encoding.UTF8.GetDecoder();
```

That will prevent the `Convert` routing from giving you garbage due to incorrect slicing of input data.
