### ISSUE TITLE
System.Runtime.Loader.Tests.AssemblyLoadContextTest.Finalizer_CollectibleWithNoAssemblyLoaded failure on Interpreter

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#39190]
### Description

This test is a reproducible failure with the Mono interpreter.

https://helix.dot.net/api/2019-06-17/jobs/dd0eca30-d0a8-4d70-8c3f-3d51253dbd18/workitems/System.Runtime.Loader.Tests/console

```
    System.Runtime.Loader.Tests.AssemblyLoadContextTest.Finalizer_CollectibleWithNoAssemblyLoaded [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Runtime.Loader/tests/CollectibleAssemblyLoadContextTest.cs(489,0): at System.Runtime.Loader.Tests.AssemblyLoadContextTest.CollectibleChecker.GcAndCheck(Int32 overrideExpect)
        /_/src/libraries/System.Runtime.Loader/tests/CollectibleAssemblyLoadContextTest.cs(51,0): at System.Runtime.Loader.Tests.AssemblyLoadContextTest.Finalizer_CollectibleWithNoAssemblyLoaded()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(362,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

### Configuration

Git master, Mono interpreter

### Regression?

Hard to be sure. We broke interpreter CI about 3 weeks ago

**Comment by BrzVlad** [comment]
I remember mentioning this is extremely likely to be a false pinning issue, that we should disable with PreciseGCSupported. Was there an investigation suggesting otherwise ?

**Comment by directhex** [comment]
I’ve marked the relevant test with a ConditionalFact instead of ActiveIssue, let’s see if that lets it pass. If so, we can close this issue
