### ISSUE TITLE
Is HttpConnectionResponseContent.Content.ReadAsStringAsync() guaranteed to be re-runnable?

### ISSUE THREAD

**Issue by brphelps** [dotnet/runtime#39218]
This is a pretty specific question, and I don't really see an answer in docs. I'm trying to figure out if there's a guarantee that ReadAsStringAsync() will be reading from buffered content after the first read for the lifetime of the HttpConnectionResponseContent return from a .GetAsync call. 

From what I can tell, it's an implicit guarantee today because the data will get buffered and replayed, but I'm wondering if we're potentially opening ourselves up to a future break where it is readable only once (e.g. if the framework doesn't fully buffer or hold a response in memory for the lifetime of the response content). Either way, can it be doc'ed somewhere what the expected lifetime / reusability is for the content object? 

Thanks!
Brandyn

**Comment by MihaZupan** [comment]
As long as you are passing `HttpCompletionOption.ResponseContentRead` to `HttpClient` (the implicit default), you can call `ReadAsStringAsync` on the content multiple times.

For an arbitrary `HttpResponseMessage` that you don't have control over, you can't make this assumption.
