### ISSUE TITLE
Investigate why NETStandard.Library package dependency is being added to net461 dependency groups for some of our packages

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#39225]
I hit this when doing my changes for https://github.com/dotnet/runtime/pull/39099 by adding configurations and noticed that some of our Microsoft.Extensions packages had this dependency added for the net461 group. We'll have to investigate why that is  happening and fix whatever is causing it.

cc: @ericstj

**Comment by ViktorHofer** [comment]
dup of https://github.com/dotnet/runtime/issues/39641
