### ISSUE TITLE
Test failure: Microsoft.Extensions.Caching.Memory.CapacityTests.DoNotAddIfSizeOverflows

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39241]
Windows, x86, `COMPlus_JitStressRegs=8`

https://dev.azure.com/dnceng/public/_build/results?buildId=726304&view=ms.vss-test-web.build-test-results-tab&runId=22490824&resultId=102068&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

I don't think this is related to JitStressRegs; I can't repro it locally like that. I think the test simply fails sometimes on loaded systems due to this code:

```
            // Wait for compaction to complete
            Assert.True(await sem.WaitAsync(TimeSpan.FromSeconds(10)));
```

Kusto shows 6 such failures in the last 30 days (all Windows x86, JitStress).

Could this timeout number be made much, much higher?

**Comment by danmosemsft** [comment]
Increasing the timeout would not affect tests that pass today, right? I think it would be fine if you want to increase those numbers.

**Comment by BruceForstall** [comment]
> Increasing the timeout would not affect tests that pass today, right? 

No idea. That would be up to the test owner to determine.

> I think it would be fine if you want to increase those numbers.

I would prefer the test/area owner make that change, to contribute to a better, more stable CI.

**Comment by BruceForstall** [comment]
Failed again:
https://dev.azure.com/dnceng/public/_build/results?buildId=736732&view=ms.vss-test-web.build-test-results-tab&runId=22818708&resultId=102444&paneView=debug

**Comment by BruceForstall** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=746053&view=ms.vss-test-web.build-test-results-tab&runId=23124036&resultId=102773&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by BruceForstall** [comment]
Dup'ing to https://github.com/dotnet/runtime/issues/33993
