### ISSUE TITLE
Switch IL bug in .NET Core 3.1

### ISSUE THREAD

**Issue by Dogwei** [dotnet/runtime#39256]
### Description

At X86 runtime, switch(long) will make an error, as shown in the picture.
this is normal on .Net Framework 471.

![微信截图_20200714132436](https://user-images.githubusercontent.com/14845492/87387476-6451a680-c5d5-11ea-96b4-48b16047e737.png)

### Configuration

.NET Core 3.1 on X86

##### This is an equivalent IL code:

```IL
.method public virtual instance int32  GetOrdinal(string name) cil managed
{
  .maxstack  8
  ldarg.1
  call       instance int32 [mscorlib]System.String::get_Length()
  ldc.i4.2
  sub
  conv.i8 // If remove this sentence, it won't go wrong
  switch     (IL_001d, IL_0032)
  br         IL_0047

  IL_001d:  ldarg.1
  ldstr      "Id"
  call       bool [Swifter.Core]Swifter.Tools.StringHelper::EqualsWithIgnoreCase(string, string) // You can change to: string.Equals(string, string)
  brtrue     IL_0049
  br         IL_0047

  IL_0032:  ldarg.1
  ldstr      "Id2"
  call       bool [Swifter.Core]Swifter.Tools.StringHelper::EqualsWithIgnoreCase(string, string) // You can change to: string.Equals(string, string)
  brtrue     IL_004b
  br         IL_0047

  IL_0047:  ldc.i4.m1
  ret
  IL_0049:  ldc.i4.0
  ret
  IL_004b:  ldc.i4.1
  ret
}
```

category:correctness
theme:invalid-il
skill-level:intermediate
cost:small

**Comment by xiangzhai** [comment]
:mips-interest

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

We can either reject this IL or try and tolerate it. Seems odd that this apparently works in full framework

**Comment by AndyAyersMS** [comment]
Going to mark this as 5.0.

**Comment by AndyAyersMS** [comment]
Moving to future.

**Comment by JulieLeeMSFT** [comment]
Not commonly seen. Unlikely to happen in .NET 6. Moving to future.

**Comment by AndyAyersMS** [comment]
Related: https://github.com/dotnet/runtime/pull/69986
