### ISSUE TITLE
Socket.ConnectAsync result get the socket error "InvalidArgument" for UDP

### ISSUE THREAD

**Issue by iozcelik** [dotnet/runtime#39268]
I use .net core 3.1 and creating a worker service.

I try to implement Socket.ConnectAsync both TCP and UDP. However UDP is not working as expected.

From [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.connectasync?view=netcore-3.1), it will be possibble. However, I am not successed.
> If you are using a connection-oriented protocol, the ConnectAsync method starts an asynchronous request for a connection to the remote host. If you are using a connectionless protocol, ConnectAsync establishes a default remote host.

My code is simple:

```
var socket = new Socket(Endpoint.AddressFamily, SocketType.Dgram, ProtocolType.Udp);

var _connectEventArg = new SocketAsyncEventArgs();
_connectEventArg.RemoteEndPoint = Endpoint;
_connectEventArg.Completed += OnAsyncCompleted;

socket.ConnectAsync(_connectEventArg);
```

**Comment by antonfirsov** [comment]
> However UDP is not working as expected.

Can you elaborate on this? Your code looks fine. What is the value of `Endpoint`, where does it come from?

**Comment by iozcelik** [comment]
I add some screenshoot. And try to what I expect. First of all, I expect ConnectAsync must return true but it return false. Why?
From [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.connectasync?view=netcore-3.1):

> true if the I/O operation is pending. The Completed event on the e parameter will be raised upon completion of the operation.
> 
> false if the I/O operation completed synchronously. In this case, The Completed event on the e parameter will not be raised and the e object passed as a parameter may be examined immediately after the method call returns to retrieve  the result of the operation.

Secondly, _connectEventArg.SocketError give InvalidArgument error. Which given argument is invalid? I have only one endpoint argument.

![image](https://user-images.githubusercontent.com/10682780/87470578-9f7bc600-c625-11ea-89ab-4d44924afdff.png)

Example code is here:

```
static void Main(string[] args) { 
       string address = "172.21.48.1";
       int port = 5858;
       var endpoint = new IPEndPoint(IPAddress.Parse(address), port);

       var socket = new Socket(endpoint.AddressFamily, SocketType.Dgram, ProtocolType.Udp);

       var _connectEventArg = new SocketAsyncEventArgs();
       _connectEventArg.RemoteEndPoint = endpoint;
       _connectEventArg.Completed += OnAsyncCompleted;

       var status = socket.ConnectAsync(_connectEventArg);
}

private static void OnAsyncCompleted(object sender, SocketAsyncEventArgs e) {
       Console.WriteLine(e.SocketError);
}
```

**Comment by wfurt** [comment]
This should be fixed by https://github.com/dotnet/runtime/pull/33674. 
Use 5.0 preview if you can @iozcelik 
(You did not specify but I assume you are on Windows, right?)

**Comment by iozcelik** [comment]
Yes, working on Windows. I cant use .net 5 but thanks.

**Comment by wfurt** [comment]
You should be able to use `socket.ConnectAsync(endpoint);`
