### ISSUE TITLE
[mono] Browser's ICU limitations

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#39285]
We use a stripped version of ICU data file. The default size is ~30Mb (or ~5mb after compression) - we reduced it down to 1.39Mb (or ~302kb compressed) by removing some features we don't need to can give up on. The main filter file is located here: https://github.com/dotnet/icu/blob/maint/maint-67/icu-filters/optimal.json

Here is a list of known limitations:

- `CultureInfo.EnglishName` returns "locale" as a name, e.g. "en (US)" instead of "English (United States)"
- `CultureInfo.NativeName` returns "locale" as a name, e.g. "ru (RU)" instead of "русский (Россия)"
- List of supported locales is limited (see list [here](https://github.com/dotnet/icu/blob/0f49268ddfd3331ca090f1c51d2baa2f75f6c6c0/icu-filters/optimal.json#L6-L54)).
- `DateTimeFormatInfo.NativeCalendarName` is not supported.
- `RegionInfo.NativeName` returns a short name e.g. "US" instead of "United States" etc.
- `String.Normalize` and `String.IsNormalized` don't support rarely used `NormalizationForm.FormKC` and `NormalizationForm.FormKD` forms.
- `RegionInfo.CurrencyNativeName` is not supported, it returns `CurrencyEnglishName` instead, e.g. `new RegionInfo("ru-RU").CurrencyNativeName`: "Russian Ruble" instead of "рубль".

**Comment by steveisok** [comment]
@EgorBo Since we hit a good spot w/ ICU, please update.

**Comment by EgorBo** [comment]
@steveisok updated the description.

**Comment by safern** [comment]
@EgorBo might be worth adding these browser limitations into this doc? https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu

**Comment by safern** [comment]
@EgorBo @steveisok should we add the list of limitations to the docs I shared above and close this?

**Comment by steveisok** [comment]
Yeah, I think that’s fine

**Comment by steveisok** [comment]
@EgorBo Since this is for .NET 5, please update the docs so that we can close the issue.

**Comment by safern** [comment]
This was fixed by: https://github.com/dotnet/docs/pull/20830.

Thanks, @EgorBo
