### ISSUE TITLE
Disabled trimming test for windows configuration

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#39288]
For the Windows configuration, there is an expectation of debug symbols to be available in the output but it looks like there is some misconfiguration about it. I had to disable the test run in #39158 to unblock other work but ideally, this should be addressed and re-enabled. All tests failed with the same error because the project.deps.json is generated with the required System.Private.CoreLib.pdb dependencies.

```
  [Trimming Tests] Running test: F:\workspace\_work\1\s\src\libraries\System.Linq.Expressions\tests\TrimmingTests\GetHelperTypeTests.cs...
EXEC : error :  [F:\workspace\_work\1\s\src\libraries\System.Diagnostics.Tracing\tests\TrimmingTests\System.Diagnostics.Tracing.TrimmingTests.proj]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) 
    An assembly specified in the application dependencies manifest (project.deps.json) was not found:
      package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '5.0.0-preview.8.20361.2'
      path: 'System.Private.CoreLib.pdb'
```

@joperezr

**Comment by joperezr** [comment]
I'm taking a look at this now...
