### ISSUE TITLE
X509Chain Validation with my own self signed CA

### ISSUE THREAD

**Issue by martinm1000** [dotnet/runtime#39283]
# Issue Title

Linux, netcoreapp3.1

# General

## Code
https://gist.github.com/martinm1000/a9cd19204fa463ca4ae57a309f3d7131

I'm trying to have code that can validate a certificate chain where the CA cert is self signed. I want to do this all
in memory (without the official certificates on the OS).

I already have working code that do this in Java, but my first tests in C# seems to indicate I can't have this working.

To validate my CA Cert (X509BasicConstraintsExtension with CA = true, KeyFlags = KeyCertSign),
I need the X509Chain to have the flag AllowUnknownCertificateAuthority.

This works.

But this also work, and shouldn't ? :

'Authority' and 'otherCA' are Self Signed CA certificates.
'SignedBy' was signed by 'Authority'

```cs
Console.WriteLine("Signed + Authority = " + Validate(signedBy, new X509ChainPolicy() {
                RevocationMode = X509RevocationMode.NoCheck,
                VerificationTime = DateTime.Now,
                VerificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority,
                //ExtraStore = { authority }
                ExtraStore = { otherCA } // DID NOT SIGN signedBY !!!
            }));
```

It looks like AllowUnknownCertificateAuthority will let the Chain Validate, even if the CA cert in it isn't related to the other certificate being checked.

I would expect a broken chain element (signedBy issued by a certificate unknown here).

Unless I'm missing how this should work...

**Comment by bartonjs** [comment]
> Is X509VerificationFlags.AllowUnknownCertificateAuthority means that we accept a CA that isn't in the chain at all ?

AllowUnknownCertificateAuthority means the validation state ignores an incomplete chain (X509ChainStatusFlags.PartialChain) or a chain that completed with an untrusted root (X509ChainStatusFlags.UntrustedRoot).

> I'm trying to have code that can validate a certificate chain where the CA cert is self signed

We've added a feature for this in .NET 5.

```C#
Console.WriteLine("Signed + Authority = " + Validate(signedBy, new X509ChainPolicy() {
                RevocationMode = X509RevocationMode.NoCheck,
                VerificationTime = DateTime.Now,
                CustomTrustStore = { authority },
                TrustMode = X509ChainTrustMode.CustomRootTrust,
            }));
```

**Comment by martinm1000** [comment]
@bartonjs Thank you, this explain what I've seen. I think it would be a good idea to specify this somewhere in the documentation; I find it kind of dangerous that X509ChainStatusFlags.PartialChain would be allowed. 

If I only tested with 'authority' and not with the 'other ca' I wouldn't have known that the chain could validate with basically anything !

> We've added a feature for this in .NET 5.

Perfect. I'll use BouncyCastle in the mean time (same feature they already have, I think they call it the trust anchor when validating). But knowing this could work with standard code is great.

**Comment by martinm1000** [comment]
@bartonjs 

Do you know if the extension for AuthorityKeyIdentifier was also added in .NET 5 ?

**Comment by bartonjs** [comment]
I do!  It was not 😦.  The new System.Formats.Asn1 package makes it reasonably easy, though; like we do in our tests.

https://github.com/dotnet/runtime/blob/83a15e3b95642e11918dd3e9ba37dd6245e15597/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs#L753-L800

**Comment by martinm1000** [comment]
Interessting !

Thank you.
