### ISSUE TITLE
Path.Join may return an invalid path given (perhaps) invalid input

### ISSUE THREAD

**Issue by ericwj** [dotnet/runtime#39297]
### Description

Is this proper?
```C#
[Theory]
[InlineData(@"D:\", @"C:\", @"D:\")]
public void Join(string expected, params string[] paths) {
    var actual = Path.Join(paths);
    Assert.Equal(expected, actual);
}
```
```
Message: 
    Assert.Equal() Failure
              ↓ (pos 0)
    Expected: D:\
    Actual:   C:\D:\
              ↑ (pos 0)
```

### Configuration

Same on `netcoreapp3.1` as on `net5.0`

```
> dotnet --list-sdks
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
5.0.100-preview.5.20279.10 [C:\Program Files\dotnet\sdk]
```

### Regression?

Don't think so.

### Opinion

It might do the 'reverse' of `GetRelativePath(@"C:\", @"D:\")` which returns `D:\` and return `D:\` - as I expected writing that test.

**Comment by pinkfloydx33** [comment]
Wasn't the motivation behind `Path.Join` to side step all the logic of `Path.Combine` wrt things like rooting and (at the time) path validation? `Join` simply combines two or more values with the directory seperator for the current environment. The assumption made when calling it seems to be that you have already validated your inputs. 

> Unlike the Combine method, the Join method does not attempt to root the returned path. (That is, if path2 or path2 or path3 is an absolute path, the Join method does not discard the previous paths as the Combine method does. 

[From the docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.join?view=netcore-3.1#:~:text=on%20Windows%20systems.-,Unlike%20the%20Combine%20method%2C%20the%20Join%20method%20does%20not%20attempt,as%20the%20Combine%20method%20does.)

**Comment by ericwj** [comment]
Thanks for that. I am quite content in fact that you can quote the docs and point out the error is mine. That speaks to the quality of .NET as well as the docs, for which I gladly thank Microsoft and the community.

Seeing the last line I wrote, I should have given `Combine` these arguments and find that it does what I wrote to expect. I might use this API sometimes now that I know the difference with `Combine`. Apologies for having you hunt that quote down though.

I guess I was slightly put off guard by finding errors in `C# interactive` which have so far proven not to reproduce on latest, while this result remained.
