### ISSUE TITLE
Test failure: System.Net.Tests.HttpListenerResponseHeadersTests.KeepAlive_SetDisposed_ThrowsObjectDisposedException

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39309]
With:
```
COMPlus_TailcallStress=1
COMPlus_TieredCompilation=0
```

This test hangs. Fails on Windows x86, x64 and arm64 (at least).

https://dev.azure.com/dnceng/public/_build/results?buildId=728248&view=ms.vss-test-web.build-test-results-tab&runId=22547532&resultId=178566&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

This is release libraries, checked coreclr.

category:correctness
theme:testing
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment]
This is just the tip of the iceberg. There are many other hangs and failures in this assembly if you get past this one (e.g., by disabling just this one test).

**Comment by erozenfeld** [comment]
The bad tail call for `System.Net.Tests.HttpListenerResponseHeadersTests.KeepAlive_SetDisposed_ThrowsObjectDisposedException` is the same as in https://github.com/dotnet/runtime/issues/38887#issuecomment-670178544

https://github.com/dotnet/runtime/blob/b39c698c628079b464650cda2540653533a84342/src/libraries/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs#L307-L321

We are passing a pointer to a local `infoptr` (points to `info`) to the call to `SetUrlGroupProperty`. So it's a tailcallstress issue.
