### ISSUE TITLE
System.Net.Mime ContentType(string) constructor throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by avanigupta** [dotnet/runtime#39337]
### Description

While initializing a new instance of the System.Net.Mime.ContentType class using a string, I got IndexOutOfRangeException instead of FormatException.

```c#
ContentType ct = new ContentType("application/");
```

According to the documentation, we should only get these 3 exceptions:
https://docs.microsoft.com/en-us/dotnet/api/system.net.mime.contenttype.-ctor?view=netcore-3.1#System_Net_Mime_ContentType__ctor_System_String_ 

### Other information

Stack Trace:
 ```
 Message: 
    System.IndexOutOfRangeException : Index was outside the bounds of the array.
  Stack Trace: 
    MailBnfHelper.ReadToken(String data, Int32& offset, StringBuilder builder)
    ContentType.ParseValue()
    ContentType.ctor(String contentType)
```

**Comment by wfurt** [comment]
we should probably fix it and throw ArgumentException or FormatException.

**Comment by danmosemsft** [comment]
@avanigupta thanks for reporting this. Do you want to offer a PR?

**Comment by avanigupta** [comment]
@danmosemsft , sure. I can create a PR for this.
