### ISSUE TITLE
OSX leg is not being running in the core-setup servicing for 2.1

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#39332]
The OSX leg has not been running for quite some time in  2.1 
This is due to the OSX image not being present
eg https://github.com/dotnet/core-setup/pull/9044

cc @ericstj @dagood @dleeapho

**Comment by dagood** [comment]
Core-Setup 2.1 => @mmitche may have some input.

Core-Setup 3.1 => I'm confused, it looks like it ran fine in https://github.com/dotnet/core-setup/pull/9043?

/cc @NikolaMilosavljevic

**Comment by Anipik** [comment]
correcting its just for 2.1

**Comment by mmitche** [comment]
The machine name is no longer available. 3.1 uses the following:

https://github.com/dotnet/core-setup/blob/release/3.1/eng/jobs/osx-build.yml#L7-L10

**Comment by Anipik** [comment]
should we make efforts to fix this ?

**Comment by mmitche** [comment]
https://github.com/dotnet/core-setup/pull/9046
