### ISSUE TITLE
Case-insensitive dictionaries do not work in Blazor WASM

### ISSUE THREAD

**Issue by DougSchmidt-AI** [dotnet/runtime#39352]
### Describe the bug
Neither `StringComparer.InvariantCultureIgnoreCase` nor `StringComparer.CurrentCultureIgnoreCase` perform case-insensitive lookups in dictionaries as expected in Blazor.WASM. Only `StringComparer.OrdinalIgnoreCase` works as expected.

Case-mismatched strings throw a `KeyNotFoundException` when they should work fine as keys.

### To reproduce

The example code works in .NET Framework, .NET Core, but not in Blazor WASM.

```C#
var text = "";

var comparers = new (StringComparer Comparer, string Name)[]
{
	(StringComparer.CurrentCultureIgnoreCase, nameof(StringComparer.CurrentCultureIgnoreCase)),
	(StringComparer.InvariantCultureIgnoreCase, nameof(StringComparer.InvariantCultureIgnoreCase)),
	(StringComparer.OrdinalIgnoreCase, nameof(StringComparer.OrdinalIgnoreCase))
};

foreach (var comparer in comparers)
{
	var leftHandedBeatles = new Dictionary<string, bool>(comparer.Comparer)
	{
		{"Paul", true},
		{"Ringo", true},
		{"John", false},
		{"George", false}
	};

	try
	{
		var name = "paul";
		var isLeftHanded = leftHandedBeatles[name];

		text = $"{text}\n{comparer.Name}:{comparer.Comparer}: {name} isLeftHanded={isLeftHanded}";
	}
	catch (KeyNotFoundException exception)
	{
		text = $"{text}\n{comparer.Name}:{comparer.Comparer}: ERROR {exception.Message}";
	}
}
```

The above code yields this result in the `text` string variable:
```
CurrentCultureIgnoreCase:System.CultureAwareComparer: ERROR The given key 'paul' was not present in the dictionary.
InvariantCultureIgnoreCase:System.CultureAwareComparer: ERROR The given key 'paul' was not present in the dictionary.
OrdinalIgnoreCase:System.OrdinalIgnoreCaseComparer: paul isLeftHanded=True
```

### Exceptions (if any)

The `KeyNotFoundException` should not be thrown. This is the case in regular .NET Framework or .NET Core projects. The exceptions only get thrown when run in a Blazor WebAssembly project.

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
```
$ dotnet --version
3.1.301
```
- Visual Studio 2019 v16.6.3

**Comment by safern** [comment]
I believe this could be related that `Blazor` uses Invariant globalization on 3.1. 

cc: @kg @EgorBo @tarekgh

**Comment by tarekgh** [comment]
@safern Invariant mode should handle the ASCII character casing fine. so, I guess it is different issue or it can be other invariant part affecting this scenario.

**Comment by DougSchmidt-AI** [comment]
If it helps, my Blazor project where I first discovered this issue has its [source here](https://github.com/AquaticInformatics/tabular-field-data-plugin/tree/master/src/BlazorTestDrive) is [hosted here](https://aquaticinformatics.github.io/tabular-field-data-plugin/test-drive/).

The project is currently using [Western European localizations](https://github.com/AquaticInformatics/tabular-field-data-plugin/blob/master/src/BlazorTestDrive/BlazorTestDrive.csproj#L9) via the `<BlazorWebAssemblyI18NAssemblies>west</BlazorWebAssemblyI18NAssemblies>` property, and is otherwise able to parse English, [French](https://aquaticinformatics.github.io/tabular-field-data-plugin/test-drive/?example=french) and [Spanish](https://aquaticinformatics.github.io/tabular-field-data-plugin/test-drive/?example=spanish) dates, times, and numbers.

No matter what locale is used (and it [defaults to InvariantCulture](https://github.com/AquaticInformatics/tabular-field-data-plugin/blob/master/src/TabularCsv/LocaleScope.cs#L12) when no explicit LocaleName is specified), the same case-insensitive failures are observed.

Perhaps it is a side effect of using those localization assemblies?

**Comment by lewing** [comment]
This works in master I believe any issues are related to old mono bcl.

**Comment by DougSchmidt-AI** [comment]
I commented out the `<BlazorWebAssemblyI18NAssemblies>west</BlazorWebAssemblyI18NAssemblies>` project setting, to disable the localization assemblies, but the problem persists.

```xml
  <ItemGroup>
    <PackageReference Include="Aquarius.FieldDataFramework" Version="20.2.0" />
    <PackageReference Include="BlazorInputFile" Version="0.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview9.19424.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview9.19424.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
  </ItemGroup>
```

What is the magic version of Blazor where this might work? I tried manually updating the 4 references to `Version="3.2.0"` as suggested in the [May 19th release announcment](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-now-available/), but those versions are not resolveable from NuGet.

**Comment by DougSchmidt-AI** [comment]
Ah, looks like my original project template was based on an older prerelease version of Blazor, and there have been some breaking changes. I will need to work through those before trying this on 3.2.0 (or greater)

**Comment by lewing** [comment]
I'm going to close this, if you can reproduce it in 3.2 please open an issue in mono/mono and reference this one.

**Comment by DougSchmidt-AI** [comment]
Yup. Confirmed that the bug is gone once I updated to 3.2. Thanks for the help along the ride.
