### ISSUE TITLE
Add missing Designer support attributes to the BackgroundWorker component

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/runtime#39366]
### Description

Several Attributes providing Designer support for the BackgroundWorker component are missing for the class itself but also for some of its properties and events which results in missing Designer support.

### Configuration

* These affects all .NET Core versions on all OS.

### Regression?

This is a regression from NetFx.

### Other information

* The `DescriptionAttribute` is missing for the class definition.
* The `DefaultEventAttribute` (`"DoWork"`) is missing for the class definition.
* The `BrowsableAttribute` (`false`) is missing for the `CancellationPending` property.
* The `DescriptionAttribute` is missing for the for the `CancellationPending` property.
* The `CategoryAttribute` is missing for `DoWork` event.
* The `DescriptionAttribute` is missing for the `DoWork` event.
* The `BrowsableAttribute` (`false`) is missing for the `IsBusy` property.
* The `DescriptionAttribute` is missing for the for the `IsBusy` property.
* The `CategoryAttribute` is missing for `ProgressChanged` event.
* The `DescriptionAttribute` is missing for the `ProgressChanged` event.
* The `CategoryAttribute` is missing for `RunWorkerCompleted` event.
* The `DescriptionAttribute` is missing for the `RunWorkerCompleted` event.
* The `CategoryProperty` is missing for the `WorkerReportsProgress` property.
* The `DescriptionAttribute` is missing for the for the `WorkerReportsProgress` property.
* The `DefaultValue` is missing for the for the `WorkerReportsProgress` property.
* The `CategoryProperty` is missing for the `WorkerSupportsCancellation` property.
* The `DescriptionAttribute` is missing for the for the `WorkerSupportsCancellation` property.
* The `DefaultValue` is missing for the for the `WorkerSupportsCancellation` property.

**Comment by ericstj** [comment]
Thanks for the report.  I'm going to combine this with https://github.com/dotnet/runtime/issues/39375
