### ISSUE TITLE
arm64 Helix reporter script error

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39371]
On `net5.0-Windows_NT-Release-arm64-CoreCLR_checked-tailcallstress-Windows.10.Arm64.Open` failure in `System.Collections.Concurrent.Tests Work Item` of this pipeline:

https://dev.azure.com/dnceng/public/_build/results?buildId=730506&view=ms.vss-test-web.build-test-results-tab&runId=22603680&resultId=148545&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

This log file:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-d32317c5455049499b/System.Collections.Concurrent.Tests/console.af5cc3b8.log?sv=2019-02-02&se=2020-08-04T11%3A44%3A51Z&sr=c&sp=rl&sig=t1K49s9fAEZTijJHE6KY92Mh%2Fy6pZF%2FTK7Tn01fggSo%3D

```
  File "C:\dotnetbuild\work\d32317c5-4550-4949-9b46-eeebdd0fda86\Payload\reporter\run.py", line 48
    def process_args() -> Tuple[str, str, str, Optional[str]]:
                       ^
SyntaxError: invalid syntax
 Wed 07/15/2020- 6:45:30.39
Traceback (most recent call last):
  File "C:\dotnetbuild\work\d32317c5-4550-4949-9b46-eeebdd0fda86\Payload\xunit-reporter.py", line 124, in <module>
    sys.exit(main())
  File "C:\dotnetbuild\work\d32317c5-4550-4949-9b46-eeebdd0fda86\Payload\xunit-reporter.py", line 79, in main
    upload_dir = settings.workitem_upload_dir
AttributeError: WorkItemSettings instance has no attribute 'workitem_upload_dir'
```

Related to https://github.com/dotnet/runtime/issues/39244?

@MattGal PTAL

**Comment by ericstj** [comment]
@MattGal does this look like an old python version on arm64 helix client?  Seems python isn't understanding [function annotations](https://www.python.org/dev/peps/pep-3107/).

**Comment by MattGal** [comment]
@ericstj yes I've been raising this issue with folks on my team but you're the first customer caring about it.  It's not understanding function annotations because it's one of the 10 boxes that is still running python 2.x.  We should take those machines offline; let me chat with @ilyas1974 .

**Comment by MattGal** [comment]
All 10 "Seattle" Arm64 boxes are offline now; per @ilyas1974 there seems to be some overly helpful lab engineer putting them back online when he takes them off.  Since I offlined them from the Helix API, they shouldn't take work now even if they are on, heartbeating, and wasting electricity.

**Comment by ericstj** [comment]
> you're the first customer caring about it.

Just triaging.  :)

Thanks for the update, if possible it'd be good to get a new python on them and have them online.  Aren't our ARM64 devices a scarce resource?

Closing this for now as it is understood and mitigated.
