### ISSUE TITLE
Unused resources in System.Threading.Overlapped

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#39385]
### Description

These resources seem to be unused: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Threading.Overlapped/src/Resources/Strings.resx.

This causes a linker warning because we are generating substitutions for `System.SR`, but that type doesn't exist (presumably it is removed by the linker):

```
resource ILLink.Substitutions.xml in System.Threading.Overlapped, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: warning IL2008: Could not resolve type 'System.SR' specified in resource ILLink.Substitutions.xml in System.Threading.Overlapped, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```
(I hit this running on blazor bits).

@eerhardt mentioned that perhaps it should be a full facade assembly.
/cc @ericstj

**Comment by eerhardt** [comment]
@joperezr - do you think you have time to look at this?

**Comment by eerhardt** [comment]
@safern also pointed out that we could add more assemblies to this test to make sure certain assemblies are empty:

https://github.com/dotnet/runtime/blob/69b0d160953f5c920e52f021366743623693c158/src/libraries/System.Runtime/tests/System/NullableMetadataTests.cs#L134

**Comment by safern** [comment]
Note that the `.resx` on that assembly seem to be a leftover from when moving all the types down to System.Private.CoreLib. The resources are defined in `System.Private.CoreLib` and only used there: https://github.com/dotnet/runtime/search?q=Argument_PreAllocatedAlreadyAllocated&unscoped_q=Argument_PreAllocatedAlreadyAllocated

So the fix would be to just delete that folder and add a a test if we will.

**Comment by joperezr** [comment]
Yup I'll take care of this.
