### ISSUE TITLE
Assert failure: (size (xl) > 0)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39393]
Job:

https://dev.azure.com/dnceng/public/_build/results?buildId=730394&view=ms.vss-test-web.build-test-results-tab&runId=22596042&resultId=171798&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Test log:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-45e329275d614728b6/System.Memory.Tests/console.b69cee47.log?sv=2019-02-02&se=2020-08-04T07%3A52%3A25Z&sr=c&sp=rl&sig=7fNu5uYZZnFEivtJjcrOZlrXcvuOc79Eu0kOc6CrSJg%3D

This was a test run on Linux/arm32 with:
```
COMPlus_TieredCompilation=0
COMPlus_JitStress=2
COMPlus_JitStressRegs=0x1000
```

Failure is in libraries System.Memory.Tests, with release libraries and checked coreclr.

It seems unlikely the stress modes matter to this assert.

Failure:
```
----- start Wed Jul 15 09:16:15 UTC 2020 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem /root/helix/work/workitem
  Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Memory.Tests (found 2533 of 2552 test cases)
  Starting:    System.Memory.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 26 [0x0000001a], Thread: 38 [0x0026]): (size (xl) > 0)
    File: /__w/1/s/src/coreclr/src/gc/gc.cpp Line: 22766
    Image: /root/helix/work/correlation/dotnet

./RunTests.sh: line 161:    26 Aborted                 "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem
----- end Wed Jul 15 09:16:43 UTC 2020 ----- exit code 134 ----------------------------------------------------------
```

**Comment by mangod9** [comment]
> It seems unlikely the stress modes matter to this assert.

Does this imply this is a recent regression?

**Comment by BruceForstall** [comment]
> Does this imply this is a recent regression?

No.

I haven't seen this failure before, but it could just be rare.

One thing to note is that due to all the new stress mode jobs, we are running all the libraries tests, including with stress modes, much more frequently than before, and that can cause rare bugs to show up in "stress mode jobs" that have nothing to do with the stress mode itself.

**Comment by AndyAyersMS** [comment]
Missing an area label, so will presume codegen.

**Comment by mangod9** [comment]
@AndyAyersMS are you able to repro this? I know you were working on reproing other issue on arm32.

**Comment by AndyAyersMS** [comment]
Am just about to try reproing... same test dll as in #40061 which I already have running, but slightly different stress config.

**Comment by AndyAyersMS** [comment]
No repros yet using 6ed1e41e590c4, 100 tries (each ~4 mins). Will queue up another set.

**Comment by AndyAyersMS** [comment]
No runs after 600 local attempts. Has not failed in CI in the past month. Closing as no repro.
