### ISSUE TITLE
Single-file apps are not debuggable by VS/VS Code

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#39414]
I believe the root of the problem is that the debugger is getting the wrong value for `fInMemory` https://github.com/dotnet/runtime/blob/1bdcd669e70d687bb0c56fe20aafa7c104b6aa0e/src/coreclr/src/debug/daccess/dacdbiimpl.cpp#L4477

Single-file apps seem to be loaded like they are file loads, not like in-memory loads. This means that the offsets in the module are file offsets, not RVAs.

Unfortunately https://github.com/dotnet/runtime/pull/39275 doesn't seem to fix the problem, but I haven't traced down exactly why. It may be that the path alone is not the only thing that the debugger uses to interpret the format.

**Comment by agocke** [comment]
Good news -- I don't think this is entirely true. It looks like https://github.com/dotnet/runtime/pull/39275 *did* fix debugging for the source assembly. It just broke it for the framework assemblies. 😄 In this case it looks like the framework assemblies are actually loaded in the expanded format, which is the opposite of the source assembly.

**Comment by hoyosjs** [comment]
#39865 fixes this throughout. Missing VS integration to see the results..
