### ISSUE TITLE
Potentially unused ES_BUILD_PCL build constant in EventSource

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#39412]
As was [discovered](https://github.com/dotnet/runtime/pull/39269#discussion_r455015252) during #39269, there's an `ES_BUILD_PCL` build constant in the EventSource code. It was first identified in `TraceLoggingEventSource`. I couldn't find any place where the constant is defined, so I think the `#if (!ES_BUILD_PCL)` blocks will always be applied.

For #39269, I'm augmenting the condition to be `#if (!ES_BUILD_PCL && !NETCOREAPP)` so that the existing check is in place along with the new condition. I'm assuming this issue will be resolved after #39269 is merged.

**Comment by tommcdon** [comment]
@jeffhandley I assume #39269 resolved this issue, if so is it OK to close this issue?

**Comment by jeffhandley** [comment]
#39269 didn't resolve it; I worked around it there. The potentially unused constant is still in place. I was tempted to remove it from the code I was touching but filed this issue instead since it's referred to elsewhere too.

If the constant is truly unused in all builds, it would help to remove references to it.

**Comment by eerhardt** [comment]
Resolved with #40204
