### ISSUE TITLE
Change ilasm command line arguments for PDB generation to match csc convention

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#39436]
Based on discussion from #5051 thread (which can be seen bellow) I am opening a new issue which can be referenced when the fix is available.

---
>So the question is not about whether -pdbfmt and -debug options can be merged but whether it will be clear enough for ilasm users.

@ivanpovazan I would agree that taking inspiration from the `csc` options is appropriate here.

```
-debug[+|-]                   Emit debugging information
-debug:{full|pdbonly|portable|embedded}
                              Specify debugging type ('full' is default,
                              'portable' is a cross-platform format,
                              'embedded' is a cross-platform format embedded into
                              the target .dll or .exe)
```

Since the `debug` flag appears to have a predefined set of options for `ilasm` and I personally wouldn't want to deal with the matrix of multiple argument, I propose slightly modifying your suggestion to align with existing `ilasm` syntax and acknowledge `csc` convention.

`-debugfmt={full|portable}`

At this point we can support `full` and `portable`. In the future we can add `embedded` as the need arises.

_Originally posted by @AaronRobinsonMSFT in https://github.com/dotnet/runtime/issues/5051#issuecomment-658316718_

**Comment by ivanpovazan** [comment]
I will fix this asap.

**Comment by AaronRobinsonMSFT** [comment]
>The only problem I can see with changing the -pdbfmt flag into -debugfmt is for the case when someone uses -pdb flag:

@ivanpovazan I think that is a reasonable argument. I am fine with the flag itself, but the flag argument should really match `csc` at the very least. That seems to change `-pdbfmt=CLASSIC` to `-pdbfmt=FULL`?

**Comment by ivanpovazan** [comment]
@AaronRobinsonMSFT yes, I am down to change the CLASSIC into FULL, but would like to check two things.

1. If I am not mistaken, I believe Roslyn compiler would in case of `-debug:full` produce the old "classic" PDB on Windows, while on other systems, this would actually mean producing PDBs in portable format.
So, if we are trying to follow the convention, the same should apply to ilasm as well. Am I right?

2. The second thing I wanted to check is, whether it would be wise to set portable PDB as default for .net core ilasm, since it does not support the original "full" PDB format. This way there would be no need for potential changes in scripts/tools for people who use ilasm on daily basis.

**Comment by AaronRobinsonMSFT** [comment]
> 1. If I am not mistaken, I believe Roslyn compiler would in case of `-debug:full` produce the old "classic" PDB on Windows, while on other systems, this would actually mean producing PDBs in portable format.
>    So, if we are trying to follow the convention, the same should apply to ilasm as well. Am I right?

Yes, the old PDB format is what 'full' means.

> 2. The second thing I wanted to check is, whether it would be wise to set portable PDB as default for .net core ilasm, since currently it does not support the original "full" PDB format. This way there would be no need for potential changes in scripts/tools for people who use ilasm on daily basis.

Yes. The default should remain. I was just implying the terminology should be the same, not suggesting we change the default values.

Thanks for confirming!

**Comment by ivanpovazan** [comment]
Based on https://github.com/dotnet/runtime/pull/45979 I believe this isn't an issue anymore.
Now ILAsm generates only portable PDBs and there are no more issues with -pdbfmt command line argument.

@jkotas I think you can close this issue.
