### ISSUE TITLE
Badrequest .NET Core RedHat

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/runtime#39442]
Hi,

i get `bad request when i call API :/ 

```c#
public static class CTR_WS_Connection
    {
        public async static Task<List<Contract>> GetContracts(string URL, string startDate, string EndDate, string lastVersion)
        {
            AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", true);


            List<Contract> ListContrats = new List<Contract>();                                 //liste allant contenir des pages de contrats (ou des objets "Contract")           
            int startIndex = 0;
            int NbContracts = 0;
            string urlAppelWS;
            try
            {

                         
                CustomDelegatingHandler customDelegatingHandler = new CustomDelegatingHandler();
                HttpClient client = HttpClientFactory.Create(customDelegatingHandler);
                var watch = System.Diagnostics.Stopwatch.StartNew();

                if (lastVersion != null)
                {
                    urlAppelWS = URL + "&startDate=" + startDate + "&endDate=" + EndDate + "&count=100" + "&lastVersion=" + lastVersion;
                }
                else
                {
                    urlAppelWS = URL + "&startDate=" + startDate + "&endDate=" + EndDate + "&count=100";

                }
                while (!string.IsNullOrEmpty(urlAppelWS)) //appel du web service en boucle (pour le parcours de la pagination) jusqu'à ce que l'on ait plus de page suivante
                {

                    HttpResponseMessage response = await client.GetAsync(urlAppelWS);

                    if (response.StatusCode != HttpStatusCode.OK)
                        throw new Exception();

                    string responsedata = await response.Content.ReadAsStringAsync();

                    Contract Contrats = JsonConvert.DeserializeObject<Contract>(responsedata);
                    if (Contrats.results.Length == 0)
                    {
                        break;
                    }
                    ListContrats.Add(Contrats);        //ajout de la réponse en page de contrats dans la liste
                    urlAppelWS = string.IsNullOrEmpty(Contrats.nextResults) ? string.Empty : URL + Contrats.nextResults.Split('?')[1];
                    Console.WriteLine("Nouvelle page de contrats : {0} contrats", Contrats.results.Length);
                    NbContracts += Contrats.results.Length;
                }
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;
                LogHelper.Writer(string.Format("Temps d'extraction des contrats depuis le web service : {0} ms soit {1} s", elapsedMs, elapsedMs / 1000));

                if (NbContracts != 0)
                    LogHelper.Writer(string.Format("{0} contrats extrais répartis sur {1} pages", NbContracts, startIndex));
            }
            catch (NullReferenceException ex)
            {
                LogHelper.Writer("Erreur (référence nulle) lors de l'import des contrats depuis le web service, message de l'erreur : " + Environment.NewLine + ex.ToString());
                throw ex;
            }
            catch (Exception ex)
            {
                LogHelper.Writer("Erreur lors de l'import des contrats depuis le web service, message de l'erreur : " + ListContrats.Count + Environment.NewLine + ex.ToString());
                throw ex;
            }
            return ListContrats;
        }

        public class CustomDelegatingHandler : DelegatingHandler
        {
            //Obtained from the server earlier, APIKey MUST be stored securely and in App.Config
            private string _applicationId;
            private string _secretKey;
            private string _proxyurl;
            private int _proxyport;
            private bool _proxyswitch;
            /// <summary>
            /// FILE XML pour environnement intégration
            /// </summary>
            //private static string Xml_Settings_PathWin = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName + @"\PRB_SECURE_SETTINGS_INTEG.xml";
            //private static string Xml_Settings_PathLin = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.FullName + @"/PRB_SECURE_SETTINGS_INTEG.xml";
            /// <summary>
            /// File XML pour environnement production
            /// </summary>
            private static string Xml_Settings_PathWin = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName + @"\PRB_SECURE_SETTINGS_PROD.xml";
            private static string Xml_Settings_PathLin = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.FullName + @"/PRB_SECURE_SETTINGS_PROD.xml";


            private static XmlDocument PRB_Settings;
            public static string UpperCaseUrlEncode(string s)
            {
                char[] temp = HttpUtility.UrlEncode(s).ToCharArray();
                for (int i = 0; i < temp.Length - 2; i++)
                {
                    if (temp[i] == '%')
                    {
                        temp[i + 1] = char.ToUpper(temp[i + 1]);
                        temp[i + 2] = char.ToUpper(temp[i + 2]);
                    }
                }
                return new string(temp);
            }


            protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                PRB_Settings = new XmlDocument();


                if (OperatingSysteme.IsLinux())
                {
                    PRB_Settings.Load(Xml_Settings_PathLin);
                }
                else
                {
                    PRB_Settings.Load(Xml_Settings_PathWin);

                }



                 _proxyurl = PRB_Settings.DocumentElement.SelectSingleNode("//PRB_Proxy_SettingsWSPROD//ProxyUrl").InnerText;
                 _proxyport = Convert.ToInt32(PRB_Settings.DocumentElement.SelectSingleNode("//PRB_Proxy_SettingsWSPROD//ProxyPort").InnerText);
                 _proxyswitch = Convert.ToBoolean(PRB_Settings.DocumentElement.SelectSingleNode("//PRB_Proxy_SettingsWSPROD//ProxySwitch").InnerText);

                //proxy bypass connection settings
                if (_proxyswitch)
                {
                    var proxy = new WebProxy(_proxyurl, _proxyport);
                    HttpClient.DefaultProxy.Credentials = CredentialCache.DefaultCredentials;
                    HttpClient.DefaultProxy = proxy;
                    LogHelper.Writer("Proxy used to connect to HUB : " + proxy.Address + " " + "Port : " + proxy.Address.Port  );

                }


                HttpResponseMessage response = null;

                _applicationId = PRB_Settings.DocumentElement.SelectSingleNode("//PRB_Contracts_Settings//HmacID").InnerText;
                _secretKey = PRB_Settings.DocumentElement.SelectSingleNode("//PRB_Contracts_Settings//HmacSecret").InnerText;

                var _secretKeyUTF8 = UTF8Encoding.UTF8.GetBytes(_secretKey);
                string nonce = Guid.NewGuid().ToString("N");

                var gbCulture = new CultureInfo("en-GB");
                // Get current UTC time.   
                var utcDate = DateTime.UtcNow;

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss UTC", gbCulture);

                //string Date = "date:" + UpperCaseUrlEncode(str);
                string Date = "date: " + utcFormattedDate;
                //Date = "date:Thu%2C+21+Apr+2016+13%3A32%3A18+UTC";
                using (HMACSHA1 hmac = new HMACSHA1(_secretKeyUTF8))
                {
                    byte[] Datebytes = Encoding.UTF8.GetBytes(Date);
                    byte[] hashedValue = hmac.ComputeHash(Datebytes);
                    string Signature = Convert.ToBase64String(hashedValue);
                    string Url_Encoded_Signature = UpperCaseUrlEncode(Signature);
                    request.Content = new StringContent(string.Empty, Encoding.UTF8, "application/json");

                    request.Headers.Add("Authorization", string.Format("Signature keyId=\"{0}\",algorithm=\"{1}\",signature=\"{2}\"", _applicationId, "hmac-sha1", Url_Encoded_Signature));

                    var field = typeof(HttpRequestHeaders).GetField("invalidHeaders", BindingFlags.NonPublic | BindingFlags.Static) ?? typeof(HttpRequestHeaders).GetField("s_invalidHeaders", BindingFlags.NonPublic | BindingFlags.Static);
                    if (field != null)
                    {
                        var invalidFields = (HashSet<string>)field.GetValue(null);
                        invalidFields.Remove("Content-Type");
                    }
                    request.Content.Headers.Remove("Content-Type");
                    //request.Headers.Add("Accept-Encoding", "gzip");
                    request.Content.Headers.Add("Content-Type", "application/json;charset=UTF-8");
                    request.Content.Headers.TryAddWithoutValidation("Date", utcFormattedDate);
                 
                }

                response = await base.SendAsync(request, cancellationToken).ContinueWith<HttpResponseMessage>(task =>
                {
                    return task.Result;
                });
                LogHelper.Writer("La requete : " + request);
                LogHelper.Writer("La réponse : " + response.StatusCode);

                return response;
            }
        }
    }
```

**Comment by HASSEN-MEDDEB-ATOS** [comment]
`
i have called the same API with script bash, it work perfectly 

`````````````
#!/bin/bash

key="*******************************"
secret="xxxxxxxxxxxx"
urlHUB="********************"

function urlencode() {
  #echo -n "$1" | perl -MURI::Escape -ne 'print uri_escape($_)' | sed "s/%20/+/g"
  #echo -n "$1" | sed "s/=/%3D/g" | sed "s/%20/+/g"
  python -c "import urllib; print urllib.quote_plus('$1')"
}

date="$(LC_ALL=C date -u +"%a, %d %b %Y %X %Z")"

signature=`echo -n "date: ${date}" | openssl sha1 -binary -hmac "${secret}" |base64`
url_encoded_signature=`urlencode "${signature}"`

echo "Date: ${date}"
echo "Signature: ${url_encoded_signature}"
echo "Authorization: Signature keyId=\"${key}\",algorithm=\"hmac-sha1\",signature=\"${url_encoded_signature}\""

url="https://${urlHUB}/mediation/v1/hmac/prb/contracts/?startDate=2020-05-02T11:55:05Z&endDate=2020-05-03T09:55:00Z&count=1"

echo "Call $url"

curl -v\
     --request GET \
     --header "Date: ${date}" \
     --header "Authorization: Signature keyId=\"${key}\",algorithm=\"hmac-sha1\",signature=\"${url_encoded_signature}\"" \
$url
echo ""
`````````````
@stephentoub  @davidsh @karelz  can you investigate please 💯  ?

**Comment by karelz** [comment]
@HASSEN-MEDDEB-ATOS which version do you run on? Why do you use `UseSocketsHttpHandler` context switch? That should be default.
By API you mean a GET request to specific URL?
Did you try to use vanilla `HttpClient` API? That way you will avoid bugs in your code.
The repro above is sadly not actionable for us -- I recommend to create a minimal repro, using hardcoded value and minimal amount of code that anyone can run locally.

**Comment by wfurt** [comment]
I would suggest to use something like `sproxy` as man-in-the-middle and do packet capture. 
The reflection use and TryAddWithoutValidation looks suspicious. 
Without repro, this really is not actionable @HASSEN-MEDDEB-ATOS.
Note that curl add some extra headers and it matters to some servers.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @karelz  @wfurt 

First, i want to thank you for your answer, I will answer all your questions :
 which version do you run on? I use .NET Core 3.1 
why do use UseSocketsHttpHandler ?  just for test
Did you try to use vanilla HttpClient API?  no i don't know vanilla :(
the client doesen't want to install software like wireshark in production environment:/
the last sentence of @wfurt, when he talked about TryAddWithoutValidation, disturbs me because when i have called the team who manage API, they told me  that my request had a problem with the date :/, but i have test my request with another API, it work perfectly :o 

Cordially

**Comment by wfurt** [comment]
Do you have link to any previous discussions @HASSEN-MEDDEB-ATOS? 
I did not say it os wrong but it looks suspicious to me personally.
If packet capture is not an option, could you enable and collect .NET tracing? At this point, I think HTTP alone  (without verbose) would be sufficient. 
Alternatively, could you run your code in your environment? You may not see the 500 but at least you should be able to analyze the difference between both requests.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
@wfurt  yes : https://github.com/dotnet/runtime/issues/39014, but now  when i tested my request with my script bash, i get all record, i can't find any difference between my request in C# and Bash.

**Comment by wfurt** [comment]
Can you share both traces publicly or privately @HASSEN-MEDDEB-ATOS ? There probably is _some_ difference unless the server have strong intuition and hates .NET :)

**Comment by HASSEN-MEDDEB-ATOS** [comment]
7/17/2020 2:01:05 PM   |  quest : Method: GET, RequestUri: 'https://**************/mediation/v1/hmac/vsmp/contracts/?&startDate=2020-05-02T11:55:05Z&endDate=2020-07-17T12:01:02Z&count=100', Version: 1.1, Content: System.Net.Http.StringContent, Headers:^M
{^M
  Authorization: Signature keyId="fcfb8f286a4d4f098afc05f5c8712c27",algorithm="hmac-sha1",signature="Qxs5Z9lA8KEdwbc6wHvia%2B%2FBWbQ%3D"^M
  Date: Fri, 17 Jul 2020 12:01:05 GMT^M
  Content-Type: application/json; charset=UTF-8^M
  Content-Length: 0^M
}
7/17/2020 2:01:05 PM   |   response: BadRequest
7/17/2020 2:01:05 PM   |   Format Date : Fri, 17 Jul 2020 12:01:05 UTC
7/17/2020 2:01:05 PM   |   Erreur lors de l'import des contrats depuis le web service, message de l'erreur : 0
System.Exception: Exception of type 'System.Exception' was thrown.
   at VSMP_Contracts.CTR_WS_Connection.GetContracts(String URL, String startDate, String EndDate, String lastVersion) in /crm/VSMP_Data_Integration/VSMP_Contracts_Import/CTR_WS_Connection.cs:line 49
7/17/2020 2:01:05 PM   |   Erreur inattendue ! :
System.AggregateException: One or more errors occurred. (Exception of type 'System.Exception' was thrown.)
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at VSMP_Contracts.CTR_WS_Connection.GetContracts(String URL, String startDate, String EndDate, String lastVersion) in /crm/VSMP_Data_Integration/VSMP_Contracts_Import/CTR_WS_Connection.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Future.cs:line 491
   at System.Threading.Tasks.Task`1.get_Result() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Future.cs:line 461
   at VSMP_Contracts.CTR_Traitement.ContractsImport() in /crm/VSMP_Data_Integration/VSMP_Contracts_Import/CTR_Traitement.cs:line 133
   at VSMP_Contracts.CTR_Traitement.BatchExecute(String[] args) in /crm/VSMP_Data_Integration/VSMP_Contracts_Import/CTR_Traitement.cs:line 112
7/17/2020 2:01:05 PM   |   ------------------------------Fin de l'import des contratn nombre d'erreurs : 1------------------

**Comment by HASSEN-MEDDEB-ATOS** [comment]
I thought that i had a problem with the date but no :/
``````````````````````````````
protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                VSMP_Settings = new XmlDocument();


                if (OperatingSysteme.IsLinux())
                {
                    VSMP_Settings.Load(Xml_Settings_PathLin);
                }
                else
                {
                    VSMP_Settings.Load(Xml_Settings_PathWin);

                }



                 _proxyurl = VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Proxy_SettingsWSPROD//ProxyUrl").InnerText;
                 _proxyport = Convert.ToInt32(VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Proxy_SettingsWSPROD//ProxyPort").InnerText);
                 _proxyswitch = Convert.ToBoolean(VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Proxy_SettingsWSPROD//ProxySwitch").InnerText);

                //proxy bypass connection settings
                if (_proxyswitch)
                {
                    var proxy = new WebProxy(_proxyurl, _proxyport);
                    HttpClient.DefaultProxy.Credentials = CredentialCache.DefaultCredentials;
                    HttpClient.DefaultProxy = proxy;
                    LogHelper.Writer("Proxy used to connect to HUB : " + proxy.Address + " " + "Port : " + proxy.Address.Port  );

                }


                HttpResponseMessage response = null;

                _applicationId = VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Contracts_Settings//HmacID").InnerText;
                _secretKey = VSMP_Settings.DocumentElement.SelectSingleNode("//VSMP_Contracts_Settings//HmacSecret").InnerText;

                var _secretKeyUTF8 = UTF8Encoding.UTF8.GetBytes(_secretKey);
                string nonce = Guid.NewGuid().ToString("N");

                var gbCulture = new CultureInfo("en-GB");
                // Get current UTC time.   
                var utcDate = DateTime.UtcNow;

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss UTC", gbCulture);

                //string Date = "date:" + UpperCaseUrlEncode(str);
                string Date = "date: " + utcFormattedDate;
                //Date = "date:Thu%2C+21+Apr+2016+13%3A32%3A18+UTC";
                using (HMACSHA1 hmac = new HMACSHA1(_secretKeyUTF8))
                {
                    byte[] Datebytes = Encoding.UTF8.GetBytes(Date);
                    byte[] hashedValue = hmac.ComputeHash(Datebytes);
                    string Signature = Convert.ToBase64String(hashedValue);
                    string Url_Encoded_Signature = UpperCaseUrlEncode(Signature);

                    request.Headers.Add("Authorization", string.Format("Signature keyId=\"{0}\",algorithm=\"{1}\",signature=\"{2}\"", _applicationId, "hmac-sha1", Url_Encoded_Signature));
                    request.Headers.TryAddWithoutValidation("Date", utcFormattedDate);


                }
                LogHelper.Writer("La requete : " + request.Headers);
                LogHelper.Writer("La requete : " + utcFormattedDate);

                response = await base.SendAsync(request, cancellationToken).ContinueWith<HttpResponseMessage>(task =>
                {
                    return task.Result;
                });

                LogHelper.Writer("La requete : " + request);
                LogHelper.Writer("La réponse : " + response.StatusCode);



                return response;
            }
``````````````````````````````

**Comment by HASSEN-MEDDEB-ATOS** [comment]
I didn't understand something I send a UTC Date 
```````
    var utcDate = DateTime.UtcNow;

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss UTC", gbCulture);
```````

 it returns a GMT in response Header, it is problem ?
![Probléme](https://user-images.githubusercontent.com/58071802/87805981-7aba6500-c856-11ea-81c8-60cfb0b4897f.png)

**Comment by karelz** [comment]
That is response header, isn't it?
How is it relevant to the problem?
Did you capture traffic of C# vs. bash? What is the difference there?
Can you please create MINIMAL HelloWorld style app sending just 1 request to a URL? (remove all unnecessary code that still reproduces the problem)

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hi @karelz ,

I have 2 APIs, one for the prod and one for the dev, the when i test with the dev the request works because the date is not mandatory in the Header, but when I use the URL of the prod there it returns BadRequest. I can't undestand, i have tested the same script in bash script, the request works with no problem.

I called the service that manages the API they told me that I have a problem with the date.

The only track I have is : I send a date in UTC it returns GMT I don't know why

with Bash Script the request retruns : Fri, 17 Jul 2020 15:29:23 UTC

 Headers:
{
  Authorization: Signature keyId="0f13c4a92e574c8071345a4321864dc2",algorithm="hmac-sha1",signature="EkHJnGtzDG1PGpQnkPPc%2Ff%2FqcKA%3D"
  Date: Fri, 17 Jul 2020 15:29:23 GMT
}

**Comment by karelz** [comment]
What problem with date did they tell you that you have?
Who sets the date format? Your code? Or 'HttpClient'?
If you use EXACTLY same date format in bash, does that work? Or is the format of the request different?
Did you compare the outgoing requests between failing and working client? What is the difference?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
they told me that the date ils missed when I call the API.

The only differce between my bash script and my C # code in the response

in bash script it returns :
Date: Fri, 17 Jul 2020 15:29:23 UTC
In NET it returns :
Date: Fri, 17 Jul 2020 15:29:23 GMT

In m'y code C# i send a UTC format date, why in response i get GMT. Maybe thé problem comes from this 😕.

**Comment by karelz** [comment]
So what you're saying is that the request on the wire is EXACTLY the same, yet C# gets bad request from server?
That doesn't make much sense, right?
Did you use packet capture tool to confirm? Eg Wireshark?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Exactly i get Bad request in C#, i can't install whireshark in production environenment, but do you have an explanation why in response it returns GMT instead of UTC ?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
``

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss UTC", gbCulture);

                //string Date = "date:" + UpperCaseUrlEncode(str);
                string Date = "date: " + utcFormattedDate;
                //Date = "date:Thu%2C+21+Apr+2016+13%3A32%3A18+UTC";
                using (HMACSHA1 hmac = new HMACSHA1(_secretKeyUTF8))
                {
                    byte[] Datebytes = Encoding.UTF8.GetBytes(Date);
                    byte[] hashedValue = hmac.ComputeHash(Datebytes);
                    string Signature = Convert.ToBase64String(hashedValue);
                    string Url_Encoded_Signature = UpperCaseUrlEncode(Signature);

                    request.Headers.Add("Authorization", string.Format("Signature keyId=\"{0}\",algorithm=\"{1}\",signature=\"{2}\"", _applicationId, "hmac-sha1", Url_Encoded_Signature));
                    request.Headers.TryAddWithoutValidation("Date", utcFormattedDate);
                }
``

**Comment by wfurt** [comment]
It does make sense. https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1
```
All HTTP date/time stamps MUST be represented in Greenwich Mean Time (GMT), without exception.
```

**Comment by yyjdelete** [comment]
@HASSEN-MEDDEB-ATOS 
Maybe an mistake and not sure if it's related, the url contains an addition `&` in C#: `.../contracts/?&startDate=...` in C# but `.../contracts/?startDate=...` in bash.

**Comment by karelz** [comment]
@HASSEN-MEDDEB-ATOS I am a bit concerned how you compare the requests between bash and C# -- the above comment https://github.com/dotnet/runtime/issues/39442#issuecomment-660584325 demonstrates they are not exactly the same.

Given that it does not make sense for the server to tell the difference between client when the requests are EXACTLY (byte by byte) same, it is most likely some problem in your code.
I would recommend to find out as much as you can either in your test environment, staging environment or in production -- whichever is easier. At this point we are just guessing what are the differences in your code. It is not actionable.
