### ISSUE TITLE
Show Blazor Wasm Singleton Services Class Data in VS Community 2019 Debugger 

### ISSUE THREAD

**Issue by CincySteve** [dotnet/runtime#39449]
I have setup some Services Singleton data classes to share data across Blazor Wasm components.  I can't see any of the data in the debugger, either via mouse-over in the code or by entering statements in the VS Immediate Window when stopped at a break point.  If I assign the Services data to local variables in my code, I am able to see it in those variables using the debugger, so I know it is in the Services Singleton.

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by lewing** [comment]
cc @radical

**Comment by radical** [comment]
@CincySteve Could you please elaborate on the problem?

- What are you hovering your mouse over? Could you share a screenshot of what it shows? A screencast would be even better, if possible.

- The Immediate window case is a known bug.

**Comment by CincySteve** [comment]
@radical I haven't been able to create a screencast, so here's a screenshot as the best alternative.  I put the variables I would like to see in the Watch list to reflect what mouseover is showing me.  When I mouseover frcst.ForecastHeader or D_.ForecastHeader, nothing shows.  But when I mouseover just frcst and D_, you can see what displays.  I am not showing the data that's in the frcst.ForecastHeader object for privacy reasons and to show D_ in the same screenshot.

D_.ForecastHeader is a static instance of the ForecastHeader class.  It is declared in the D_ Singleton Services class.  ForecastHeader is a class of String and  Int32 properties that are declared in a different Singleton Services class.  

I hope this makes the situation clear.  

![Blazor Services Data Visibility](https://user-images.githubusercontent.com/18602722/87857320-e272bd80-c8f3-11ea-86c0-be6d3d7a4315.png)

**Comment by radical** [comment]
@CincySteve Thanks, that helps. This is a known issue, and being fixed. The issue being that member references like `a.b`, `a.b.c`, don't work. So, just `a` would work, or `this.a`.
As for all those property getters, there is a PR up for that already - https://github.com/mono/mono/pull/20045 .

**Comment by CincySteve** [comment]
@radical Any ETA on the fix?  This is a really, really big productivity problem.  Thanks.

**Comment by CincySteve** [comment]
@radical As I have continued work on my app, I have noticed that my inability to see data values in the debugger includes not only the "a.b" and "a.b.c" references you mention above, but also just "a" references in which "a" is a static property within a public class within the app's namespace.  I think that's what you meant by "a".  

In any case, I'd like to reiterate how important it is to get this debugger data visibility issue fixed.  It is a **giant** productivity drain which requires lots of local var assignments throughout my code with app restarts in order to see my app's data while debugging.  I have come across 8-10 Blazor bugs or feature shortcomings since starting to use Blazor in June, but this one is far and away the most important.

Finally, I am subscribed to this issue (at least that's what I'm seeing) and my email address is in my profile, but I have received no email notices when comments are added.  Can you tell me if there is something I'm not understanding or doing right?  I am, unfortunately, a novice GitHub user and don't see what I am doing wrong based on the documentation I have found.  Thanks.

**Comment by radical** [comment]
Part 1 of a fix for this - https://github.com/dotnet/runtime/pull/40836 .
Part 2 would be showing inherited members.

**Comment by radical** [comment]
> Part 1 of a fix for this - #40836 .

Merged.

> Part 2 would be showing inherited members.

This is filed as a specific issue - https://github.com/dotnet/runtime/issues/40245 . Therefore, closing this in favor of that issue.
