### ISSUE TITLE
System.Runtime.Intrinsics.Arm.AdvSimd build failure in preview 8

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/runtime#39440]
there is System.Runtime.Intrinsics.Arm.AdvSimd failure in release/5.0-preview8
The problem is visible here:
https://github.com/dotnet/runtime/pull/39434/checks?check_run_id=877743259

error:
```
TypesMustExist : Type 'System.Runtime.Intrinsics.Arm.AdvSimd' does not exist in the reference but it does exist in the implementation. 

TypesMustExist : Type 'System.Runtime.Intrinsics.Arm.ArmBase' does not exist in the reference but it does exist in the implementation.
```

It can be caused by #39416

cc @Anipik @jeffhandley

**Comment by ericstj** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/39444
