### ISSUE TITLE
System.Text.Encodings.Web.dll ref api compat issue in preview 8

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/runtime#39444]
There is System.Text.Encodings.Web.dll failure in release/5.0-preview8
The problem is visible here:
https://github.com/dotnet/runtime/pull/39434/checks?check_run_id=877743259

Error message:
```
MatchingRefApiCompat failed - The reference assembly doesn't match all the APIs in the implementation for 'artifacts\bin\System.Text.Encodings.Web\netcoreapp3.0-Debug\System.Text.Encodings.Web.dll'. To address either fix errors in the reference assembly (referenced as implementation in compat errors for this reverse compat check), add the issues to the baseline file 'src\libraries\System.Text.Encodings.Web\src\MatchingRefApiCompatBaseline.txt' or disable this check by setting RunMatchingRefApiCompat=false in this project.
```

cc: @Anipik @ericstj  @GrabYourPitchforks @layomia @tarekgh

**Comment by ericstj** [comment]
Here's the error messages from https://dev.azure.com/dnceng/public/_build/results?buildId=733219&view=logs&j=423ae147-26a3-5a4d-a4d3-4b3fc1dd598e&t=98a4dd5a-baea-5dc4-484b-ccbd315f07c8&l=4551
```
error : TypesMustExist : Type 'System.Runtime.Intrinsics.Arm.AdvSimd' does not exist in the reference but it does exist in the implementation. 
error : TypesMustExist : Type 'System.Runtime.Intrinsics.Arm.ArmBase' does not exist in the reference but it does exist in the implementation. 
```


I believe regression was caused by https://github.com/dotnet/runtime/pull/38707.  @eiriktsarpalis

**Comment by aik-jahoda** [comment]
For the `System.Runtime.Intrinsics.Arm.AdvSimd` I created an issue there: #39440.

**Comment by eiriktsarpalis** [comment]
I think this might be caused by the shimmed AdvSimd APIs [used for netcoreapp3.0 builds](https://github.com/dotnet/runtime/commit/7fab504a54e97b20d08946c2ed621b48cca4fbc6#diff-41fd4c3dcafff7e9e07b5eed514a9e22). Something is causing the `USE_INTERNAL_ACCESSIBILITY` constant not being defined. I'll take a look.

**Comment by aik-jahoda** [comment]
I expect the fix can be as simple as in: https://github.com/dotnet/runtime/commit/6be3ce77c4fc6cf451c9ef87f760365c943cceae

The IsPrerelease has changed in this branch: https://github.com/dotnet/runtime/commit/bf35bfd11f74fb1efe1c3a1e749636113270eccd

**Comment by eiriktsarpalis** [comment]
Tagging @pgovind

**Comment by ericstj** [comment]
@eiriktsarpalis can this be closed now?
