### ISSUE TITLE
Error in culture fr-BE on macOS Catalina

### ISSUE THREAD

**Issue by Ablim** [dotnet/runtime#39467]
# Error in culture fr-BE on macOS Catalina

Hi. I have an issue that the CurrencyGroupSeparator and NumberGroupSeparator for the culture fr-BE returns " " instead of expected "." on my mac. The same binary returns "." in Windows. I am aware that both " " and "." are used in Belgium, but why does it differ between Core runtimes?

Thanks for any help!

The code in particular:
`CultureInfo.CreateSpecificCulture("fr-BE").NumberFormat.CurrencyGroupSeparator`
`CultureInfo.CreateSpecificCulture("fr-BE").NumberFormat.NumberGroupSeparator`

.NET Core version 3.1.201
macOS Catalina 10.15.5

**Comment by safern** [comment]
Hello @Ablim the reason why it differs in between runtimes it is because in .NET Core 3.1 for Windows we used NLS as the underlying locale data source and ICU for Unix.

Starting on .NET 5 we're using ICU on Windows as well when running on Windows Creators Update 2019 or later. I expect this to return the same result in .NET 5 for both runtimes. Let me try it out.

**Comment by tarekgh** [comment]
@Ablim I am closing the issue but feel free to respond with any question and we'll be happy to help with.

**Comment by Ablim** [comment]
Ok, thanks. So is there anything I can do as a workaround, like configuring my runtime or OS? 
Or are my only options to either switch to Windows or wait for .NET 5 and hope we upgrade the project?

**Comment by safern** [comment]
I think the only workaround I can see is to either override it on Windows:
![image](https://user-images.githubusercontent.com/22899328/87761666-b6a5e980-c7c6-11ea-9c77-d4680ab65ff4.png)

Or set it in MacOS to match `Windows`

```cs
CultureInfo.CreateSpecificCulture("fr-BE").NumberFormat.CurrencyGroupSeparator = "."
```
https://source.dot.net/#System.Private.CoreLib/NumberFormatInfo.cs,334

**Comment by tarekgh** [comment]
Note that, changing user overrides on Windows settings will work only if you have the culture is set as the default user locale in the user profile. I would say it is better to control that by setting the Culture.NumberFormat properties in your app.
