### ISSUE TITLE
[MIPS64] Port Unwinder

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#395]
Hi,

As @janvorli [suggested](https://github.com/dotnet/coreclr/issues/27831#issuecomment-552945501),  we need to port unwinder for MIPS64.

> Design your own unwind info format. It seems that modelling it similar to the ARM64 unwind info might be the easiest. Looking at the src/jit/unwindarm64.cpp and src/unwinder/unwinder_arm64.cpp it looks like they are the simplest we have and register-wise, the architectures look similar. Maybe you could even reuse most of the code in both files.

We are not sure about the **Bits** for the **Unwind code**, for example, `alloc_l`:

```
11100000'xxxxxxxx'xxxxxxxx'xxxxxxxx: allocate large stack with size < 256M (2^24 *16)
```

What is the `11100000` or `0xE0` meaning?  Is it some **opcode** of AArch64 instruction?  Or is it just like **ID** to distinguish from others?

Please give us some hint!

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
\cc @janvorli 

\cc @QiaoVanke

**Comment by janvorli** [comment]
@xiangzhai The codes are binary codes of unwinder "instructions". It has nothing to do with aarch64 instruction codes. The example in your comment means that there will be an 0xE0 byte followed by three bytes that form the size of the stack allocation that this unwind instruction represents.
As you can see, some codes are only one byte long, some are two bytes, and some four bytes.
For example the alloc_s instruction has format 000xxxxx. That means that it is a single byte starting with three zero bits and the remaining five bits represents the size to allocate (the value is multiplied by 16, as the stack allocs are always using 16 bytes granularity). So e.g. 00000010 would represent allocation of 32 bytes of stack.

**Comment by xiangzhai** [comment]
Hi @janvorli 

Thanks for your teaching!

> The codes are binary codes of unwinder "instructions". It has nothing to do with aarch64 instruction codes. 

Yes, I am using the same Unwind code when porting Unwinder for MIPS64 this afternoon :)

Thanks,
Leslie Zhai
