### ISSUE TITLE
TestParserDouble_SpecificValues failing on browser

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#39503]
System.Tests.RealParserTests.TestParserDouble_SpecificValues failed on https://github.com/dotnet/runtime/pull/39498

log https://helix.dot.net/api/2019-06-17/jobs/875a70b3-492a-42d9-ad1e-d87cb37c2bf3/workitems/System.Runtime.Tests/console

cc @akoeplinger @marek-safar @safern @ericstj

**Comment by safern** [comment]
Dupe of: https://github.com/dotnet/runtime/issues/39473
