### ISSUE TITLE
Test failure: System.Linq.Parallel.Tests.ZipTests.Zip_Unordered(leftCount: 1, rightCount: 1)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39512]
failed in job: [runtime-coreclr libraries-jitstress2-jitstressregs 20200711.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=725908&view=ms.vss-test-web.build-test-results-tab&runId=22477892&resultId=144374&paneView=debug)

Error message
Assert.Equal() Failure
Expected: 1
Actual:   0

Stack trace
   at System.Linq.Parallel.Tests.ZipTests.Zip_Unordered(Int32 leftCount, Int32 rightCount) in /_/src/libraries/System.Linq.Parallel/tests/QueryOperators/ZipTests.cs:line 60

**Comment by Clockwork-Muse** [comment]
[Comment is correct](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq.Parallel/tests/QueryOperators/ZipTests.cs#L62-L63):

>// For unordered collections the pairing isn't actually guaranteed, but an effect of the implementation.
// If this test starts failing it should be updated, and possibly mentioned in release notes.

I guess I'm a bit surprised it's lasted this long.  
I'll get a PR later today.

**Comment by tarekgh** [comment]
Thanks @Clockwork-Muse please tag me on the PR when you have it.
