### ISSUE TITLE
Improve file locking of files contained in a self-contained executable or change extraction logic

### ISSUE THREAD

**Issue by lothrop** [dotnet/runtime#39515]
I'm not sure how widespread this issue is, but I just saw the following phenomenon:

Our .NET Core 3.1 Windows service is packaged as a self-contained executable. When Service Control Manager first launches the executable it gets extracted to somewhere under C:\Windows\Temp and executed from there.

On a test machine, we now saw messages in the log that DLLs could not be loaded because they could not be found. It turns out that about 190 files that were contained in the executable were no longer in the temporary folder, leaving about 70 behind. Someone or some process must have cleaned up the temp folder and deleted all the DLLs that were not currently loaded by our running Windows service (those couldn't be deleted as they were locked). Restarting the service did not help because the unpacking logic figured out that the executable had already been unpacked and executed it from the temp folder. It ran, but could not answer HTTP requests anymore because of missing DLLs that were to be loaded at runtime.

I could see two ways of improving this:

1. Not only the files that are currently loaded into the process memory are locked but all files in the temporary folder are explicitly locked while the process is running.
2. When a self-contained executable is launched, it not only checks if it has been extracted and the folder it has been extracted to is still there but also checks if all the files contained in the self-contained package are in that folder.

Now I'm not sure if cleaning up the temp directory is something that a user should not do. I have found many sources on the internet encouraging this, though. https://social.technet.microsoft.com/Forums/ie/en-US/4a8eeaa3-0322-4bff-9561-673dbd3731cf/is-it-safe-to-delete-cwindowstemp-files?forum=w7itprogeneral

**Comment by agocke** [comment]
@lothrop We changed the extraction logic a couple months ago to verify all binaries and re-extract them if necessary. However, this does require you to rebuild/redeploy your app. Could you provide info on which version of the SDK/runtime you saw this issue with?

**Comment by lothrop** [comment]
We’re still on version 3.1.0.

**Comment by agocke** [comment]
This should be fixed in the latest patch version, 3.1.6. I'll close for now, but let me know if this repros after rebuilding with the latest and we can investigate
