### ISSUE TITLE
System.Text.RegularExpressions test fails on Browser wasm

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#39528]
When running library tests on Browser wasm, `Groups` in `Regex.Groups.Tests.cs` fails on one test case https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs#L859

### Repro
```
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;

public class Test
{
    public static void Main (String[] args) {
        var pattern = "\u0131";
        var input = "\u0049";
        var options = RegexOptions.IgnoreCase;
        Regex regex = new Regex(pattern, options);
        Match match = regex.Match(input);
        Console.WriteLine(match.Success);
    }
}
```
Result: False
Expected: True

**Comment by safern** [comment]
I think this is just a limitation of the ICU data, since we don't support the `az-Latn-AZ` culture/locale. This is the table of locales we support in WASM: https://developer.chrome.com/webstore/i18n?csw=1#localeTable

cc: @EgorBo is my assumption correct?

**Comment by safern** [comment]
Closing as this locale is not supported in wasm ICU.
