### ISSUE TITLE
`System.Globalization.Nls.Tests.ToUpper/ToLower_netcore` test failures in local environment

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#39522]
### Description

Run tests in `System.Globalization.Nls.Tests` test project. The characters after the ToLower/ToUpper call do not change even though we expect it to change.
```
Test	Duration	Traits	Error Message
System.Globalization.Tests.TextInfoMiscTests.ToLower_Netcore Failed	24 ms		Assert.Equal() Failure            ↓ (pos 1) Expected: 𐐨 Actual:   𐐀            ↑ (pos 1)
System.Globalization.Tests.TextInfoMiscTests.ToUpper_netcore Failed	< 1 ms		Assert.Equal() Failure            ↓ (pos 1) Expected: 𐐀 Actual:   𐐨            ↑ (pos 1)

```

Please note that this only seems to happen when no culture name is specified (`new CultureInfo("")`); the exact same test but with the culture name `en-US` / `fr` / `fr-FR` passes fine.

https://github.com/dotnet/runtime/blob/f4e9146d1d2ba7cf48ab59022658619fc9dbaec3/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs#L174-L184

### Configuration

* Windows 10 Pro Insider Preview, Build 20170 (Also noticed in a couple previous flights), x64
* Locale ko-KR
* Ran with VS2019 16.7 P4, with `./build.cmd -vs System.Globalization -runtimeConfiguration Release -librariesConfiguration Debug`

### Other information

Possibly a Windows NLS issue, rather than the libraries implementation being wrong? Using builds from the dev channel probably doesn't help a lot 😅

**Comment by tarekgh** [comment]
@Gnbrkm41 I am running on Windows 10 v19577 and I am not seeing this behavior. So this most likely a new change coming from Windows. I am trying to confirm that now. Thanks for reporting that.

**Comment by Gnbrkm41** [comment]
`System.Text.Tests.RuneTests.Casing_Invariant` under `System.Runtime.Nls.Tests` appears to be failing with the same test data.

**Comment by tarekgh** [comment]
do you see any other failures than with this data "\U00010400"?

**Comment by Gnbrkm41** [comment]
No, that is the only failure I'm noticing with existing test data.

**Comment by MattGal** [comment]
Also observed on ARM64 Windows 10.0.19619

**Comment by GrabYourPitchforks** [comment]
@tarekgh Do you know if Windows ever _removes_ case conversion mappings between versions? Win7 didn't support case conversion between characters from the Deseret alphabet, Win8 did, and now it looks like recent versions of Win10 may have backed it out?

**Comment by tarekgh** [comment]
@GrabYourPitchforks 

> Do you know if Windows ever removes case conversion mappings between versions? Win7 didn't support case conversion between characters from the Deseret alphabet, Win8 did, and now it looks like recent versions of Win10 may have backed it out?

I am trying to investigate the issue. I doubt Windows removed it intentionally but any way I am accessing some machine with same reported version and seeing the casing not changed here. I'll dig more to understand what could be the problem. I'll report back when having more info.

**Comment by tarekgh** [comment]
@Gnbrkm41 I am not able to repro it so far. I have tried on 2 machines with different architecture. could you please create a stand alone dotnet app and run the following code:

```C#
using System;
using System.Runtime.InteropServices;
using System.Reflection;
using System.Globalization;

namespace apps
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(RuntimeInformation.OSDescription);
            Console.WriteLine(RuntimeInformation.FrameworkDescription);
            Console.WriteLine($"UseNls: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("UseNls", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null)}");
            Console.WriteLine($"Invariant: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("Invariant", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null)}");

            CultureInfo ci = new CultureInfo("ko-KR");
            foreach (char c in ci.TextInfo.ToLower("\U00010400"))
            {
                Console.Write($"\\u{(int)c:x4}, ");
            }
            Console.WriteLine();
        }
    }
}
```

and the project:

```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
  </ItemGroup>
</Project>
```

on my machine I am getting the output:

```
Microsoft Windows 10.0.20170
.NET 5.0.0-preview.8.20361.2
UseNls: True
Invariant: False
\ud801, \udc28,
```

**Comment by Gnbrkm41** [comment]
I get the following output with the code:
```
Microsoft Windows 10.0.20170
.NET 5.0.0-preview.8.20361.2
UseNls: True
Invariant: False
\ud801, \udc28,
```

However, I did miss out something when writing the initial issue, that this only seems to happen for the test case when nothing is specified for the culture name (I figured that copying the rows from the test explorer would also copy the details about the data, turns out it doesn't):
![image](https://user-images.githubusercontent.com/42944058/87906456-9e232100-ca9d-11ea-8ffa-6bbe2b18ea48.png)

If I change the value of the string passed into `CultureInfo` to `""`, like this:
```cs
CultureInfo ci = new CultureInfo("");
foreach (char c in ci.TextInfo.ToLower("\U00010400"))
{
    Console.Write($"\\u{(int)c:x4}, ");
}
```
then the code now outputs the following:
```
Microsoft Windows 10.0.20170
.NET 5.0.0-preview.8.20361.2
UseNls: True
Invariant: False
\ud801, \udc00,
```

**Comment by tarekgh** [comment]
Thanks, I'll take a deeper look. this is very helpful.

**Comment by tarekgh** [comment]
I discovered this is repro in any WIn 10 machine and not specific to the reported version. Also, the test make sense to fail with the Invariant culture. The question I am trying to find answer for is why this failure didn't show up before?

**Comment by tarekgh** [comment]
It is a change in Windows with the Invariant culture. I have reported it to the Windows team. Meanwhile, I'll try to submit a fix from our side to have us immuned against such a change.
