### ISSUE TITLE
Unable to build on Windows in Visual Studio 2019

### ISSUE THREAD

**Issue by alexcovington** [dotnet/runtime#39568]
I've been having difficulty building in Visual Studio 2019. I believe the issue is related to CMake and could use some help figuring out what I'm doing wrong. Here is the error:

```
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/acovingt/source/repos/runtime/src/libraries/Native/Windows/out/build/x64-Debug (default)/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_83150 && [1/2] Building C object CMakeFiles\cmTC_83150.dir\testCCompiler.c.obj
    cl : Command line warning D9025 : overriding '/W0' with '/W3'
    [2/2] Linking C executable cmTC_83150.exe
    FAILED: cmTC_83150.exe 
    cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_83150.dir --rc=rc --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_83150.dir\testCCompiler.c.obj  /out:cmTC_83150.exe /implib:cmTC_83150.lib /pdb:cmTC_83150.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_83150.dir\testCCompiler.c.obj /out:cmTC_83150.exe /implib:cmTC_83150.lib /pdb:cmTC_83150.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_83150.dir/intermediate.manifest CMakeFiles\cmTC_83150.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake	60	
```

I have all of the .NET and C++ workloads installed, Python 3.7, CMake 3.18.0, and Git 2.26.2 installed, so I don't think I'm missing any dependencies. Any help would be appreciated!

**Comment by AntonLapounov** [comment]
> LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

`kernel32.lib` is a part of Windows 10 SDK.  Please make sure it is properly installed.  For instance, on my machine this file resides at `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64\kernel32.Lib`.

**Comment by alexcovington** [comment]
The Windows 10 SDK is installed, is there an environment variable that needs to be set for Visual Studio to find the SDK?

**Comment by alexcovington** [comment]
I uninstalled/reinstalled the Windows 10 SDK, now I am receiving this error when I try to build:

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/acovingt/source/repos/runtime/src/coreclr/out/build/x64-Debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_8b981 && [1/2] Building C object CMakeFiles\cmTC_8b981.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_8b981.exe
    FAILED: cmTC_8b981.exe 
    cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_8b981.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_8b981.dir\testCCompiler.c.obj  /out:cmTC_8b981.exe /implib:cmTC_8b981.lib /pdb:cmTC_8b981.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\Users\acovingt\source\repos\runtime\src\coreclr\out\build\x64-Debug\CMakeFiles\CMakeTmp && powershell -noprofile -executionpolicy Bypass -file C:/Users/acovingt/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/acovingt/source/repos/runtime/src/coreclr/out/build/x64-Debug/CMakeFiles/CMakeTmp/cmTC_8b981.exe -installedDir C:/Users/acovingt/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_8b981.dir\testCCompiler.c.obj /out:cmTC_8b981.exe /implib:cmTC_8b981.lib /pdb:cmTC_8b981.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_8b981.dir/intermediate.manifest CMakeFiles\cmTC_8b981.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake	60

**Comment by safern** [comment]
@alexcovington could you share which project are you trying to build, what process are you following, etc? That would be helpful for the diagnostics of this.

**Comment by alexcovington** [comment]
I uninstalled/reinstalled Visual Studio and the workload dependencies, the missing library issue above seems to be resolved.

Now when I try to build using either Visual Studio or the command line I get the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at configure.cmake:42 (message):
  Unknown platform.  Cannot define PAL_UNIX_NAME, used by RuntimeInformation.		C:\Users\acovingt\source\repos\runtime\src\libraries\Native\Unix\configure.cmake	42	
```

and 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\acovingt\source\repos\runtime\src\libraries\Native\Unix\CMakeLists.txt:6 (include):
  include could not find load file:

    /configuretools.cmake	CoreFX	C:\Users\acovingt\source\repos\runtime\src\libraries\Native\Unix\CMakeLists.txt	6	
```

I am currently trying to build using the command:

```
.\build.cmd -c debug -a x64
```

But I get the same errors when I build with Visual Studio as well.

**Comment by AntonLapounov** [comment]
@alexcovington Are you doing a clean build?  If not, I would suggest running `git clean -xdf` to remove old artifacts and trying again.  You might want to run `git clean -xdn` first to see what files would be removed.

**Comment by alexcovington** [comment]
I tried this as well as recloning the repository, same error.

**Comment by AntonLapounov** [comment]
I noticed you are using Ninja build system instead of MSBuild ("ninja: build stopped").  Not sure whether it is supported for Windows.

**Comment by alexcovington** [comment]
How do I change this? I'm still a little new to Visual Studio and can't find a reference to it in the documentation.

**Comment by alexcovington** [comment]
I've uninstalled/reinstalled the Windows 10 SDK again, now some pieces are building, but not the CoreCLR. I'm going to close this issue and open a new one with more specifics on those issues.
