### ISSUE TITLE
Crossgen2 does not work with PublishReadyToRunEmitSymbols

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#39573]
Specifying both `PublishReadyToRunEmitSymbols` and `PublishReadyToRunUseCrossgen2` properties leads to PDB generation failures during the `_CreateR2RSymbols` target (composite mode only).

Repro steps:
```
dotnet new console
dotnet publish -r win-x64 /p:PublishReadyToRunEmitSymbols=true /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true
```
Output:
```
error : Error generating PDB for 'obj\Debug\net5.0\win-x64\R2R\foo.dll': Index not found. (0x80131124)
error : Error: compilation failed for "obj\Debug\net5.0\win-x64\R2R\foo.dll" (0x80131124)
error : Error generating PDB for 'obj\Debug\net5.0\win-x64\R2R\Microsoft.CSharp.dll': Index not found. (0x80131124)
error : Error: compilation failed for "obj\Debug\net5.0\win-x64\R2R\Microsoft.CSharp.dll" (0x80131124)
error : Error generating PDB for 'obj\Debug\net5.0\win-x64\R2R\Microsoft.VisualBasic.Core.dll': Index not found. (0x80131124)
error : Error: compilation failed for "obj\Debug\net5.0\win-x64\R2R\Microsoft.VisualBasic.Core.dll" (0x80131124)
...
```
@davidwrighton @mangod9

**Comment by davidwrighton** [comment]
We won't be fixing this in .NET 5.

**Comment by trylek** [comment]
@davidwrighton - is this a deficiency of the PDB generator so that we should track fixing it for the .NET 6 release?

**Comment by trylek** [comment]
@AntonLapounov - I believe this should be now fixed with SDK Preview 2 including my change

https://github.com/dotnet/sdk/pull/15529

where we newly use Crossgen2 to emit PDB directly during compilation, not during the separate <code>_CreateR2RSymbols</code> target. Do you think we can close this issue?

**Comment by AntonLapounov** [comment]
Verified as fixed in .NET 6 SDK.  When targeting .NET 6, the PDB is successfully generated.  When targeting .NET 5, the following error is reported:
```
error NETSDK1163: Cannot emit symbols when publishing for .NET 5 with Crossgen2 using composite mode.
```
