### ISSUE TITLE
Crossgen2 does not work with PublishTrimmed

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#39572]
Specifying both `PublishTrimmed` and `PublishReadyToRunUseCrossgen2` properties leads to incorrectly skipping the `_CreateR2RImages` target and a failure during the `_CopyResolvedFilesToPublishPreserveNewest` target.

Repro steps:
```
dotnet new console
dotnet publish -r win-x64 /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true
```
Output:
```
error MSB3030: Could not copy the file "obj\Debug\net5.0\win-x64\R2R\System.Console.dll" because it was not found.
error MSB3030: Could not copy the file "obj\Debug\net5.0\win-x64\R2R\System.Collections.Concurrent.dll" because it was not found.
error MSB3030: Could not copy the file "obj\Debug\net5.0\win-x64\R2R\System.Collections.dll" because it was not found.
...
```
@davidwrighton @mangod9

**Comment by mangod9** [comment]
I think its ok to move this to 6.0. There was a discussion about publishTrimmed + R2R, and there are some unknowns there too.

**Comment by mangod9** [comment]
Closing this since @VSadov has recently fixed this.
