### ISSUE TITLE
Assert failure: xl <= end

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39577]
```
Assert failure(PID 15498 [0x00003c8a], Thread: 15498 [0x3c8a]): xl <= end
    File: /home/bruce/gh/runtime/src/coreclr/src/gc/gc.cpp Line: 23036
    Image: /home/bruce/gh/runtime/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root/corerun
```

Frequently, when trying to run:

```
~/gh/runtime/artifacts/tests/coreclr/Linux.x64.Release/JIT/HardwareIntrinsics/General$ COMPlus_JitStress=1 COMPlus_TieredCompilation=0 COMPlus_GCStress=C  ./Vector64_1/Vector64_1_r/Vector64_1_r.sh -coreroot=/home/bruce/gh/runtime/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root
```

on Linux/x64, I see the above assertion.

Related? These tests fail in this same scenario with apparently bad GC info: https://github.com/dotnet/runtime/issues/39576

**Comment by mangod9** [comment]
@BruceForstall assume this is not affected by the arcade issue?

**Comment by BruceForstall** [comment]
The arcade issue only affects issue logging and reporting, not the actual test case runs.

But correct, this is Linux x64, so the reporting here would be fine.

Unfortunately, I didn't link this to a CI run.

**Comment by mangod9** [comment]
Ok to close for now assuming most of the GC stress issues were related to a couple of fixes recently?

**Comment by BruceForstall** [comment]
Sure. Looks like it failed with this assert five times in the last few months but hasn't failed in the CI since mid-July.

**Comment by mangod9** [comment]
great, Thanks
