### ISSUE TITLE
Test failure: Interop\COM\Dynamic\Dynamic is very slow under GCStress

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39584]
On Windows x64/x86, I measure about 2 minutes to run Interop\COM\Dynamic\Dynamic\Dynamic.cmd with:
```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
```

However, adding:
```
set COMPlus_HeapVerify=1
```
(which some of the scenarios in the `gcstress-extra` pipeline do) makes the test run a very long time (I gave up waiting for it to finish).

**Comment by BruceForstall** [comment]
e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=726589&view=ms.vss-test-web.build-test-results-tab&runId=22500980&resultId=109452&paneView=debug

**Comment by AaronRobinsonMSFT** [comment]
I don't think there is much in the way of making this faster in GCStress. Uses of the COM are slow under GCStress and uses of `dynamic` are also slow. The combination is simply an immense impact on the GCStress methodology. I am going to close for now.
