### ISSUE TITLE
Can't run System.Net.Http tests via VS test explorer due to build failure "Metadata file ... System.Runtime.InteropServices.JavaScript.dll could not be found"

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#39593]
I built the runtime several times using different configurations (`build.cmd`, `build.cmd Clr+Libs+Libs.Tests -rc Release -lc Debug` etc) and then launched VS using `build.cmd -vs System.Net.Http -rc Release -lc Debug`. When I attempt to run the test, I get an error `Metadata file 'C:\Users\gotos\source\repos\runtime\artifacts\bin\System.Runtime.InteropServices.JavaScript\net5.0-Browser-Debug\System.Runtime.InteropServices.JavaScript.dll' could not be found`	for the project `System.Net.Http (net5.0-Windows_NT)` during the build phase before the test is able to run, results in the tests not running.

Am I missing something? Do I need to build the runtime/library for wasm/browser? I tried to build the runtime for wasm/browser via `build -arch wasm -os browser` but this resulted in some weird failures. Assistances would be appreciated 🙂

**Comment by danmosemsft** [comment]
@lewing ?

**Comment by lewing** [comment]
The current test runner is likely failing against http because we're testing against v8 (js shell) which is not the same a (headless) browser. @kjpou1 and @radical what is the current state of our networking tests on dotnet/runtime?

**Comment by Gnbrkm41** [comment]
Just in case it wasn't clear: This happens before the test is run. It looks like the test runner likely attempts to build the library/tests when I ask for it to run the tests, and the error happens during the build phase. This results in a build failure and thus the tests are not run.

**Comment by akoeplinger** [comment]
@Gnbrkm41 You can't build the Browser/WebAssembly runtime pieces on Windows right now, you'd need to do that on Linux or Mac. That also means running the System.Runtime.InteropServices.JavaScript assembly tests from inside VS on Windows won't work.

There seems to be something wrong with the project reference, I'll take a look

**Comment by akoeplinger** [comment]
@Gnbrkm41 would you mind checking whether this change fixes it:

```diff
diff --git a/src/libraries/System.Net.Http/src/System.Net.Http.csproj b/src/libraries/System.Net.Http/src/System.Net.Http.csproj
index 65d63c045bb..4d1cc31bf9b 100644
--- a/src/libraries/System.Net.Http/src/System.Net.Http.csproj
+++ b/src/libraries/System.Net.Http/src/System.Net.Http.csproj
@@ -721,7 +721,7 @@
   <ItemGroup>
     <None Include="Resources\SR.resx" />
   </ItemGroup>
-  <ItemGroup Condition=" '$(TargetsBrowser)' == 'true'">
+  <ItemGroup Condition=" '$(TargetOS)' == 'Browser'">
     <ProjectReference Include="..\..\System.Runtime.InteropServices.JavaScript/src/System.Runtime.InteropServices.JavaScript.csproj" />
   </ItemGroup>
 </Project>
```

**Comment by Gnbrkm41** [comment]
That results in a different kind of compilation failure, where it fails to find the `System.Runtime.InteropServices.JavaScript` namespace while trying to build `src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs`.

**Comment by akoeplinger** [comment]
This should fix the issue: https://github.com/dotnet/runtime/pull/39629
