### ISSUE TITLE
coreclr.dll size regressed ~200kB due to constexpr changes

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#39599]
https://github.com/dotnet/runtime/pull/39532 introduce unexpected ~200kB size regression in coreclr.dll size on Windows x64:

commit a9b0bebdbb3b7fc50f295bb26acaa39b045634ae

5,028,352 coreclr.dll

commit 902645707215bcd0c22900d0a9ba4d01ca1a2fbe

5,209,600 coreclr.dll

**Comment by jkotas** [comment]
It may be best to just move to the constant data to .cpp where possible. It seems to be the only full portable and reliable way to avoid the constant duplication.

https://github.com/dotnet/runtime/pull/39532#issuecomment-660296905

**Comment by mangod9** [comment]
Assume this means we have to conditionally compile using constexpr only on Linux?

**Comment by jkotas** [comment]
Or move the static data to the .cpp files and stop depending on these fancy features that do not work...
