### ISSUE TITLE
Improve perf of Activity Get/SetCustomProperty API for auto-instrumentation (codeless attach) APM scenarios.

### ISSUE THREAD

**Issue by macrogreg** [dotnet/runtime#39591]
[edited by @tarekgh adding this line] We are optimizing the case here without exposing any new APIs. If we see any need in the future to improve more, we can revisit that.

## Background and Motivation

Hi!

I propose to state enrichment API to the `System.Diagnostics.`**`Activity`** class.
The purpose of the API is to cater for specific high-performance scenarios typical for auto-instrumentation scenarios.

### Background

We are currently working on the Open Telemetry Tracer (aka In-Proc Instrumentation Agent). The Tracer aims to collect information from an application that uses a wealth of libraries. Some such libraries may be already instrumented "out-of-the-box" and emit Activities. Other libraries are not, and then the Tracer uses profiling APIs to modify their byte code to emit Activities as required. The Tracer collects all activities, performs some basic processing, serializes them, and sends them to a remote endpoint for further processing. 

On contrary to libraries (such as Open Telemetry), Tracers often are deployed on an application that is readily in production and may already run with high resource utilization relative to what is available. As such, the constraints on the resource utilization added by Tracer are even more aggressive compared to SDK-based tracing.

The Open Telemetry Tracer is a basis technology shared between multiple APM vendors. We need to be flexible in how we process Activities, and we need to enrich activities with additional state. These are not only semantic properties to be logged, but also “processing state” required for performance optimizations (e.g. some scenarios require memory references to other data structures, pre-computed hashes and IDs not covered by OTel standards, etc...).

### Alternatives

Today custom state can be stored in an Activity object by using the following APIs:

* `public IEnumerable<KeyValuePair<string, object?>> TagObjects` and `public Activity AddTag(string key, object? value)`
This is meant for information intended for logging. It is stored in a linked list. A fast lookup is not possible.

* `public void SetCustomProperty(string propertyName, object? propertyValue)` and `public object? GetCustomProperty(string propertyName)`
This allows enriching activity state. However, the information is stored in a ConcurrentDictionary. R/W access in constant, amortized, but relatively slow. The dictionary-based architecture allows different actors/libraries to attach state to the Activity without conflicting with each other, by using well-chosen property names.

However, an In-Proc Instrumentation Agent has a special scenario:

* There is typically only one In-Proc Instrumentation Agent / Tracer attached to the application at any one time. Conflicts are unlikely.
* Performance overhead is particularly critical, as the Tracer is usually attached to an existing application in-prod, where resource utilization may be already high.

Because to address such scenario I propose an additional state-related API intended specifically for APM vendors, 

## Proposed API

```csharp
namespace System.Diagnostics
{
    public class Activity
    {
        // . . . 

        /// <summary>
        /// The state associated with this <c>Activity</c> instance.
        /// </summary>
        /// <remarks>
        /// This property is intended to production and application monitoring tools and should not be used by
        /// application code.
        /// </remarks>
        public object State { get; }

        /// <summary>
        /// Sets the <see cref="State" /> of this <c>Activity</c> instance, if the cuttent state in <c>null</c>.
        /// </summary>
        /// <remarks>
        /// This property is intended to production and application monitoring tools and should not be used
        /// by application code.
        /// </remarks>
        /// <param name="newState"><c>true</c> if the activity state was <c>null</c> and has been set
        /// to the specified <c>newState</c>. <c>false</c> otherwise.</param>
        /// <returns></returns>
        public bool TrySetState(object newState);


        /// <summary>
        /// Sets the <see cref="State" /> of this <c>Activity</c> instance, if the current state in <c>null</c> or
        /// if <c>forceIfStateExists</c> is <c>true</c>.
        /// This property is intended to production and application monitoring tools and should not be used by
        /// application code.
        /// </summary>
        /// <param name="newState">The state object to be set as the new state.</param>
        /// <param name="forceIfStateExists">If <c>forceIfStateExists</c> is <c>true</c>, then
        /// <c>newState</c> is always set as the new state.
        /// If <c>forceIfStateExists</c> is <c>false</c>, then <c>newState</c> is only set as the new state
        /// if the previous state is <c>null</c>.</param>
        /// <param name="prevState">If this method returns <c>true</c>, the <c>prevState</c> is set to
        /// the previous state, that was current before <c>newState</c> was set.
        /// If this method returns <c>false</c>, <c>prevState</c> is set to refer to the object that is both,
        /// the previous and the current state.
        /// The state change from <c>prevState</c> to <c>newState</c> occurs atomically in respect to concurrent
        /// operations.</param>
        /// <returns><c>true</c> if the <see cref="State" /> of this <c>Activity</c> instance was set
        /// to <c>newState</c>, because the state was null previously
        /// or becasue <c>forceIfStateExists</c> was <c>true</c>. <c>false</c> otherwise</returns>
        public bool TrySetState(object newState, bool forceIfStateExists, out object prevState);
    }
}
```

## Usage

This will allow Tracer vendors to create highly optimized access to Activity state, while backing off to name-spaces properties if required:

```csharp
namespace OpenTelemetry.Trace.AutoInstrumentation
{
    public class ActivityTracingState { }

    public static class ActivityExtensions
    {
        private const string StateObjectKey = "OpenTelemetry.Trace.AutoInstrumentation.State";

        public void SetState(this Activity activity, ActivityTracingState state)
        {
            // Try the the high per path. Fall back to Properties, if State is already used:
            if (! activity.TrySetState(state))  // 
            {
                activity.SetCustomProperty(StateObjectKey, state);
            }
        }

        public ActivityTracingState GetState(this Activity activity)
        {
            // Try fetching from high-perf accessor:
            object state = activity.State;

            // We typically set a state. If we did not find it in the high-perf accessor, we likely had
            // a conflict setting it and it is in the Properties. Look there, but still be defensive:
            if (state != null)
            {
                var activityTracingState = state as ActivityTracingState;
                if (activityTracingState != null)
                {
                    return activityTracingState;
                }
            }

            state = activity.GetCustomProperty(StateObjectKey);
            if (state == null)
            {
                return null;
            }

            return state as ActivityTracingState;
        }
    }
}
```

The other `TrySetState` overload is useful to reliably keep track of the previous state in concurrent scenarios. This is important when state needs to be processed when removed (e.g. disposed).

## Risks

The API is aimed at performance-critical scenarios in production monitoring. If customers or libraries use this functionality for other purposes, if will force Tracer implementations the slower path, defeating the purpose of the API.
We could partially mitigate by hiding the API from Intelligence.

I am not sure if this is in-time for .Net 5.
I will create a PR on the weekend. I hope, this API can be considered, and if approved – merged in-time.

Thank you!

**Comment by macrogreg** [comment]
Hey @noahfalk , @davmason  thanks for chatting to us about the TRacer the other week. After the main chat we chatted about prototyping the OTel tracer to use "new style" activities. This proposal is that result of that investigation.

Another outcome was a question / request for clarification on when is it OK or not OK to mutate Activities. Especially doing it in ActivityStopped handlers can lead to unexpected consequences. I posted about is in the OTel SG Gitter Chat: https://gitter.im/open-telemetry/opentelemetry-dotnet?at=5f127ddef8b05b39f951caee

I suggest that the Activity and ActivityListener docs include guidance about that.

Thank you!

**Comment by macrogreg** [comment]
@kevingosse @zacharycmontoya @lucaspimentel @tonyredondo @colin-higgins FYI

**Comment by noahfalk** [comment]
Hey @macrogreg, thanks for filing the issue! I'm sympathetic to your goal and a little skeptical of this particular approach. First some issues I am wary of and then some alternate suggestions on how we might accomplish a similar outcome.

Activity tends to be a type that people want to attach state to and we already have quite a few (Tags, Baggage, CustomProperties, Events, Links). At the same time we also have requests that the type uses too much memory which is a performance issue + the type has too many concepts which makes using it confusing and complicated. So each time we help out the folks wanting state we are making the situation worse for people that want low memory/low concept count. The other worry is that even if there is typically only on ActivityListener today its hard to say if that convention will remain true 5-10 years from now. Building perf features that only work if there is a single tracer isn't off the table, but its a point in favor of alternatives that don't have this limitation.

Alternative solutions:
1. CustomProperties currently use a ConcurrentDictionary, but it isn't a requirement. I suspect typical use cases wouldn't store more than a few properties which could make it very reasonable to use a small linked list or an array of KeyValuePair. This switches to O(n) insert/query but much smaller constants. If we later discovered that some important scenario used a large number of custom properties the implementation could toggle back to the ConcurrentDictionary above some size threshold.
2. As a byte-code instrumentating Tracer you've got special powers, you could modify the metadata for the Activity type to add the field directly. 

In terms of timing we just passed feature complete. If there was a blocking issue or an API choice we'd regret for a long time then there is probably still a little wiggle room, but adding new APIs solely to improve performance wouldn't meet the bar for 5.0. I'm happy to chat more about this and get your thoughts. Also do you have perf data from experiments you could share? I'm a little surprised that this API would stand out as the top opportunity for optimization relative to other areas in the Activity implementation.

**Comment by tarekgh** [comment]
I want to add for the current release we should look at the Set/GetCustomProperty perf and try to enhance it in term of speed and allocation which should help in the requested scenario. 

@@macrogreg if you agree, I'll go ahead and close this issue for now.

**Comment by macrogreg** [comment]
Hi @noahfalk ,

Thank you for your feedback.
I actually submitted a PR before I noticed your response:
https://github.com/dotnet/runtime/pull/39679

However I follow your argument.
There are a few small points to consider, as we continue your line of thought.

> As a byte-code instrumentating Tracer you've got special powers, you could modify the metadata for the Activity type to add the field directly.

True. However, it feel wrong to have auto-instrumentation rewrite Framework code for improving performance (rather than adding tracing-specific functionality).

> CustomProperties currently use a ConcurrentDictionary, but it isn't a requirement. I suspect typical use cases wouldn't store more than a few properties which could make it very reasonable to use a small linked list or an array of KeyValuePair. This switches to O(n) insert/query but much smaller constants. If we later discovered that some important scenario used a large number of custom properties the implementation could toggle back to the ConcurrentDictionary above some size threshold.

Good point. Perhaps we should make a small change now to have CustomProperties use a normal (non-concurrent) dictionary. If we use ConcurrentDictionary today, we essentially build concurrency resilience into the contract. However, if we just use a normal Dictionary<string, object>, we leave additional flexibility for future perf optimizations.
If we did this tweak now, I'd be happy to prepare an optimizing PR targeting a future release that uses a combo or linked list and dictionary depending on the size of the property bag.

>  Also do you have perf data from experiments you could share?

I did not focus on all Activity perf opportunities. Instead, I prototyped using Activities in the Tracer (instead of proprietary Spans) and focused on what seemed to be missing.

Thank you!

**Comment by macrogreg** [comment]
@tarekgh re your question above: I am OK with either decision, but if we decide to close this issue, I just would encourage you to explicitly consider this for a moment:  

> Perhaps we should make a small change now to have CustomProperties use a normal (non-concurrent) dictionary. If we use ConcurrentDictionary today, we essentially build concurrency resilience into the contract. However, if we just use a normal Dictionary<string, object>, we leave additional flexibility for future perf optimizations.

As long as the decision on this is explicit (rather than just not focusing on this aspect) I am fine with the direction of the runtime team. If we decide to consider perf-optimizing that API (not change its shape), I'd be happy to prepare a PR for current or future release, as appropriate.

Thanks!

**Comment by tarekgh** [comment]
@macrogreg sure. we can keep this issue opened to track the perf work. please change the issue title to reflect that. 

If you want to help in this perf optimization, that will be great. let's know if need any help in that. Are you familiar with dotnet benchmark https://github.com/dotnet/BenchmarkDotNet to use for measuring the perf before and after the changes to know the gain? 

Thanks for willing to help here.

**Comment by macrogreg** [comment]
Hi @tarekgh ,

I changed the title as requested.

I am not familiar with https://github.com/dotnet/BenchmarkDotNet, however, it looks like a useful thing to learn about. :)
Can you please indicate the following:

* What release would such perf improvements target? (If current, how much time do I have?)
* Is being thread-safe a requirement? Why? (or why not?)

Thanks!

**Comment by tarekgh** [comment]
@macrogreg 

> What release would such perf improvements target? (If current, how much time do I have?)

Is the current release 5.0. you should have enough time (at least 6 weeks from now). but if you can get it earlier that will be better.

> Is being thread-safe a requirement? Why? (or why not?)

Yes, this is why we used concurrent dictionary in the implementation. And if you look at the rest of the Activity code, you'll find it handle the threading safety. I think the original design of Activity is to have it thread safe but I don't know if there is more history behind that. @noahfalk may know the history here. 

Thanks again for the help.

**Comment by macrogreg** [comment]
Thanks, @tarekgh . I have no opposition to thread safety, just looking to learn the background. :)
If we stick to being thread-safe: In my opinion we can optimize for the Get-scenario (i.e. a slight perf decrease in SetXxx is OK, if if yields a significant improvement in GetXxx). Would you (and @noahfalk ) agree with such an approach?

**Comment by tarekgh** [comment]
> In my opinion we can optimize for the Get-scenario (i.e. a slight perf decrease in SetXxx is OK, if it yields a significant improvement in GetXxx). Would you (and @noahfalk ) agree with such an approach?

I would start by having some goals for a scenario like yours and try to address it. Optimizing for reading over writing looks reasonable to me but I am expecting writing perf should still be reasonable. @noahfalk suggested before to have like a linked list (which we use inside Activity for other purposes). The list can be reasonable for this release but in the future, I expect we'll change it if proven users storing many values to the custom property. I want to emphasize that we don't have to over-engineering this. In the main scenarios I am not expecting to have more than one thread trying to write/read on the same activity so taking a local lock on our data structure can be reasonable. Of course, the lock will be local for this activity object only. If you want to try some lock-free mechanisms (using CAS), that is ok to try it too.

**Comment by macrogreg** [comment]
What I had in mind was:

The first 5 elements are stored in an array of KeyValue pairs. Modifications use optimistic concurrency: copy the array and interlocked-replace the array if it has not changed, otherwise, try again. On look-ups, first search the array using reference equality, and if not found. search again using string comparison.

If the number of properties grows beyond 5. the rest goes into a normal dictionary. Use a local lock to control RW access to it (since you agree - contention is unlikely).

**Comment by tarekgh** [comment]
Give it a shot and we can review the details and look at the benchmarks. Please note the SetCustomProperty has a behavior when setting null value it delete the entry which has same input key.

**Comment by macrogreg** [comment]
I'll create a draft and if the approach looks fine to all involved, I'll follow up with perf measurements and additional unit tests.

**Comment by macrogreg** [comment]
I created a draft here: https://github.com/dotnet/runtime/pull/39690

It is slightly different from what I described above to keep things shorter and simpler. But the high-level idea is the same.
Please let me know if this looks good in general.
If we all agree on the approach, I can follow up with perf data and tests later.

Thanks!

**Comment by noahfalk** [comment]
> In my opinion we can optimize for the Get-scenario

My expectation is that a high performance scenario would either use 1-3 get operations per set operation, and/or the exporter would issue a series of get operations for the keys the Activity creating code never populated on a particular Activity. Beyond a few Get operations it probably gets faster to have an enumeration API for custom properties, but I'd suggest we constrain this to optimizing the existing API in .Net 5 and let performance oriented additional APIs wait for .Net 6 (assuming ongoing usage demonstrates they would be valuable).

> If the number of properties grows beyond 5. the rest goes into a normal dictionary. Use a local lock to control RW access to it (since you agree - contention is unlikely)

That sounds good to me with a small variation, above 5 get rid of the array and put everything in the dictionary. I want to avoid growing the memory footprint of Activity when no custom properties are in use. This lets us reuse the same the field as a reference to either the array or the dictionary and use a type check to determine which case we are in.
FWIW you might also find simpler designs perform even better, or well enough that it doesn't merit the additional complexity in the code. For example:
a) Just a Dictionary with a lock, no array (dictionary operations should be faster than concurrent dictionary operations)
b) Swap between Dictionary/array, but allocate the array initially to size 5 and use a lock to control insertions/removals rather than doing re-allocation + interlocked exchange each time. The cost of the extra allocations are probably higher than cost of an uncontended lock acquisition.

> I think the original design of Activity is to have it thread safe but I don't know if there is more history behind that. @noahfalk may know the history here.

I don't know the particular history. I can make an educated guess that Activity was designed to flow into potentially multiple threads via async-local storage and Vance thought that would make thread-safety a valuable characteristic. It doesn't seem mandatory to me, but it does make typical usage easier. Given that the initial Activity properties were thread-safe I think it would be reasonable for us to keep the design consistent and ensure newly added properties behave the same way.

> Another outcome was a question / request for clarification on when is it OK or not OK to mutate Activities

 I forgot before... the design intent is that the code which creates the Activity does all the writing and the code which receives Activities via ActivityListener or DiagnosticListener does only reading. In practice in some spots we've ventured into grey areas where the OpenTelemetry listener will write the Activity.Kind property where it has specific knowledge about the limitations of some legacy instrumentation code that predated the property being available.

**Comment by macrogreg** [comment]
Thank you. I'll measure different options mentioned, but it will be several days until I can get to it. :)

> > Another outcome was a question / request for clarification on when is it OK or not OK to mutate Activities
> 
> I forgot before... the design intent is that the code which creates the Activity does all the writing and the code which receives Activities via ActivityListener or DiagnosticListener does only reading. In practice in some spots we've ventured into grey areas where the OpenTelemetry listener will write the Activity.Kind property where it has specific knowledge about the limitations of some legacy instrumentation code that predated the property being available.

I see at least 2 scenarios where mutating an Activity may be necessary. I am curious about a recommendation:

1. Enriching an Activity with some environment Information. This may be service name, instance name, or some environment info that is APM-vendor specific and was configured by the user for this specific service or instance.
This could be set after the activity has been serialized or during serialization. However, an attempt to split serialization from processing seems architecturally natural, so people will tend to do this by adding into to an Activity.
In additional, such logic is likely to apply to all or most activities, so people will try to do this in ActivityListener or DiagnosticListener rather than in the code that creates Activities.

2. Grouping activities. Some scenarios require Activity groups. The one that I am actively aware of is that some exporters require a trace (aka all local activities that belong to the same service invocation) to be exported in a single data structure. While putting all activities in a look-up bucket is possible, it may be more performant to cross-link them directly. E.g. in the trace example, a root activity may point to all its children and their transient children, and all children may point to the root. This requires mutating Activity properties at central processing points (ActivityListener or DiagnosticListener appear natural).

All in all I feel that the guidance to not mutate activities once they are started will not hold up. Can we improve on it? Would it be reasonable to say that Start Events (in either ActivityListener or DiagnosticListener) should be considered for modifying Activities, and Stop Events should not?

**Comment by tarekgh** [comment]
@noahfalk @tommcdon @ericstj I have marked this for 5.0 and blocking release too. it is needed as it is requested from a couple of teams so far. I already have the PR ready https://github.com/dotnet/runtime/pull/41840 and will follow the process getting this to rc2 branch after the PR get merged.
