### ISSUE TITLE
AF: GetOptimizationTier() == NativeCodeVersion::OptimizationTier0

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#39604]
Repro:

1. Build checked coreclr
2. Unzip 
[repro.zip](https://github.com/dotnet/runtime/files/4943309/repro.zip) to `artifacts\bin\coreclr\Windows_NT.x64.Checked`
3. Run `runme.bat`

Result:
```
ssert failure(PID 23464 [0x00005ba8], Thread: 11528 [0x2d08]): pConfig->GetCodeVersion().GetOptimizationTier() == NativeCodeVersion::OptimizationTier0

CORECLR! MethodDesc::JitCompileCodeLocked + 0x3E7 (0x00007ffb`58d7a8bf)
CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x318 (0x00007ffb`58d7ad74)
CORECLR! MethodDesc::JitCompileCode + 0x4F4 (0x00007ffb`58d7a3f8)
CORECLR! MethodDesc::PrepareILBasedCode + 0x24D (0x00007ffb`58d7c519)
CORECLR! MethodDesc::PrepareCode + 0xE9 (0x00007ffb`58d7c27d)
CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x359 (0x00007ffb`58c0b00d)
CORECLR! MethodDesc::DoPrestub + 0x926 (0x00007ffb`58d762f6)
CORECLR! PreStubWorker + 0x532 (0x00007ffb`58d7f0e2)
CORECLR! ThePreStub + 0x55 (0x00007ffb`5924aa45)
<no module>! <no symbol> + 0x0 (0x00007ffa`f9678a08)
    File: C:\runtime\src\coreclr\src\vm\prestub.cpp Line: 1066
```

**Comment by jkotas** [comment]
The problem is that JIT lock does not guarantee that the method is JITed exactly once. The method can be JITed multiple times in some situations to break deadlocks. My repro is single threaded, there are also multithreaded versions of the same problem possible. I believe https://github.com/dotnet/runtime/pull/39082 is blocked on the multithreaded version of this problem.

**Comment by jkotas** [comment]
@kouvel Could you please take a look?

**Comment by kouvel** [comment]
Will take a look

**Comment by kouvel** [comment]
Thanks for the repro, worked great
