### ISSUE TITLE
Questions about kasiabulat writable jsondom

### ISSUE THREAD

**Issue by BreyerW** [dotnet/runtime#39610]
I was scanning kasiabulat effort [writable jsondom](https://github.com/kasiabulat/corefx/tree/kasiabulat/writable-json-dom-refactor/src/System.Text.Json/src/System/Text/Json/Node)

And it seems almost done except it doesnt support latest features like preserve reference but thats a given considering they are very recent additions and maybe some bits are slighty incomplete

What prevented shipping it (aside from kasiabulat no longer working for Net Core team)? Or in other words was is missing because im thinking on grabbing it up and finishing

Is this link most up to date design/code? I saw several branches related  to this effort and as such im not 100% sure what was accepted and what is merely an experimentation

And assuming i would pick it up how would you feel if i merged `JsonBoolean`, `JsonNumber`, `JsonString` and  `JsonNull` into `JsonValue` backed by byte array? Byte array would be created using `MemoryMarshal.CreateSpan` of length=1 then `AsBytes`+`ToArray` except string where marshal would be replaced by `AsSpan` (creates `char` span). And i would either add IsNull property or rely on `JsonValueKind` for `null` values. Alternatively `Unsafe.As` could be used instead of marshal?

cc @ahsonkhan  & @Jozkee   since if im not mistaken they put quite some effort on `System.Text.Json`

**Comment by BreyerW** [comment]
@333fred  oh right sorry i had opened runtime and csharplang in browser side by side and didnt notice this slip up xD

**Comment by Jozkee** [comment]
@layomia

**Comment by ahsonkhan** [comment]
Here's the issue and post which captures the state of the writable dom and what work items are left:
https://github.com/dotnet/runtime/issues/30436#issuecomment-535301281

The primary blocker is making sure folks are happy with the API design and customers are successful with it. From the linked issue:
> Investigate alternative design (making the JsonNode type hierarchy internal to JsonElement and unify the types) and conduct A/B usability study

There are benefits and drawbacks of having the `JsonNode` types being a public hierarchy on the side, separate from `JsonElement`, but it is important that the option to unify the types within `JsonElement`, hiding the hierarchy from the end user, is explored to understand that aspect of an alternative design, first.

The latest code can be found in this PR, where it was removed until someone goes through the above mentioned exercise: https://github.com/dotnet/runtime/pull/34099

**Comment by BreyerW** [comment]
@ahsonkhan  how do you envision unifying hierarchy with `JsonElement` considering it is `struct`? Could you provide some rough sketch (eg `JsonBoolean`<->`JsonElement`)? Or did you mean `JsonDocument`? Unless ur ok to change to `class` which i m highly doubtful about? I must say being `class` is crucial for writable version. lm using `JSON.NET` version of writable dom and being able to use reference is highly convenient and if im not mistaken you want for writable to be more convenient even if it means losing a bit of performance (btw Unity game engine is also using writable dom and is also based on `class` for modifying objects its just that they use their own format rather than json)

That being said i considered copying `jsonelement` hierarchy AND behaviour, changing to class and renaming and adding write logic but this approach has a problem of being huge PITA when updating with mismatching length of byte data (while being trivial in case of same length) and being potentially slow (because u have to resize byte array then perform a lot of magic to ensure that is packed then u have to update  all offsets after changed data. Of course u can be clever and avoid some of that work but only in very specific situations)

**Comment by layomia** [comment]
As @ahsonkhan mentioned, https://github.com/dotnet/runtime/issues/30436#issuecomment-535301281 highlights what the next steps for the writable JSON DOM are, and that is the tracking issue.

Closing this issue as a duplicate - I'll copy your comments over there and we'll be sure to consider them as we continue the effort for the feature. @BreyerW
