### ISSUE TITLE
.NET 5.0 Preview 6.20318.15 (X64) Not Handling CultureInfo/RegionInfo Correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#39613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1093484/net-50-preview-62031815-x64-not-handling-culturein.html)._

---
I have the following code in a static 'gazeteer' function that loads country names, time zone id's, etc:

```
			/*  create the country name list  */

CultureInfo[] CultureInfos = CultureInfo.GetCultures(CultureTypes.SpecificCultures);
			foreach (CultureInfo CultureInfo in CultureInfos)
			{
				RegionInfo Ri = new RegionInfo(CultureInfo.LCID);
				CountryNames[Ri.EnglishName] = Ri.TwoLetterISORegionName;
			}

```
It worked fine until just now when I installed the SDK 5.0 preview noted in the title.
Now the GetCultures function delivers some CultureInfos that causes the RegionInfo constructor to throw an unknown culture exception.
In particular, this happens for those CultureInfos beginning with 'aa_'.

---
#### Feedback Bot on 6/28/2020, 03:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/8/2020, 02:51 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by tarekgh** [comment]
It is not right to use `CultureInfo.LCID` property. It is kind of deprecated property. It is recommended to use `CultureInfo.Name` instead. OS's introduced a lot of cultures which not having a valid LCID and get assigned LCID 0x1000. You'll find many cultures has same LCID. this LCID cannot be used to create RegionInfo or CultureInfo.

**Comment by planogramsinc** [comment]
This property should be marked as deprecated in the online docs.  Currently it is not.

**Comment by tarekgh** [comment]
Fully agree @planogramsinc. We were trying to not exposing it in the .NET Core at all but there was some migration blocking scenario which made us to expose it. anyway, I am pasting a couple of links which can be useful too.

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.lcid?view=netcore-3.1#remarks
https://docs.microsoft.com/en-us/globalization/locale/locale-names

**Comment by planogramsinc** [comment]
Got it.  Thx.
