### ISSUE TITLE
Linq Expression.TypeIs produces an InvalidProgramException when using open generics

### ISSUE THREAD

**Issue by sidney-pauly** [dotnet/runtime#39614]
### Description
If the type provided in Expression.TypeIs is an open generic, compiling a lambda with that expression produces an InvalidProgramException  ("Common Language Runtime detected an invalid program").

### Minimal example
```
        public static Func<object, bool> CompileIsDictionary()
        {
            // Input param of the function
            var INPUT_PARAM_object = Expression.Parameter(typeof(object));

            // Function that creates issues because it is translated into
            // 'type is IDictionary<,>' which produces a compiler error.
            var isDictionary = Expression.TypeIs(INPUT_PARAM_object, typeof(IDictionary<,>));

            var lambda = Expression.Lambda<Func<object, bool>>(isDictionary, new[] { INPUT_PARAM_object });

            var compiled = lambda.Compile();
            return compiled;
        }
```
### Explenation
As mentioned in the code, the open generic gets directly used as the right side for the "is" operator, which produces a compiler error. In the case of the Lamda compilation pipeline an error occurs here:
```
Stack Trace: 
    DynamicMethod.CreateDelegate(Type delegateType, Object target)
    LambdaCompiler.CreateDelegate()
    LambdaCompiler.Compile(LambdaExpression lambda)
    Expression`1.Compile(Boolean preferInterpretation)
    Expression`1.Compile()
    OpenGenericIssueCompiler.CompileIsDictionary() line 22
    Tests.RunIsDictonary() line 14
```

### Possible solutions

1. Throw an exception if a Expression.TypeIs is created with an open generic
2. Transport errors from the CreateDelegate method: This would be very useful regardless of 1. because it would potentially also solve some other cases where compile errors occur. (See #39485 )

**Comment by cston** [comment]
@sidney-pauly, thanks for reporting this issue. As you suggested, `Expression.TypeIs()` should probably throw an exception if the type argument is an open generic type.

However, we are limiting the changes accepted in System.Linq.Expressions (see [README.md](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/README.md)).
