### ISSUE TITLE
HashCode.GetHashCode and HashCode.Equals lack ObsoleteAttribute in Microsoft.Bcl.HashCode reference assembly

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/runtime#39624]
### Description

In System.HashCode, the GetHashCode() and Equals(object) methods always throw NotSupportedException, and they have ObsoleteAttribute and EditorBrowsableAttribute to discourage their use. However, in the Microsoft.Bcl.HashCode 1.1.0 NuGet package, the methods in the reference assembly do not have these attributes, so the compiler does not warn if they are used.

### To reproduce

HashCodeDemo.csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.0" />
  </ItemGroup>

</Project>
```

Class1.cs:

```C#
namespace HashCodeDemo
{
    public class Class1
    {
        public void Demo()
        {
            var hashCode = new System.HashCode();
            hashCode.GetHashCode();
            hashCode.Equals(hashCode);
        }
    }
}
```

Then run `dotnet build`.

### Expected result

Compilation fails with an error saying those methods should not be used.

### Actual result

Compilation succeeds with no warnings.

### Configuration

.NET Core SDK 3.1.301 on Windows 10 version 2004 x64, but I don't think it is specific to that configuration.

### Regression?

No, the System.HashCode type does not exist in .NET Framework, and the NuGet package has been like this ever since it was added in <https://github.com/dotnet/corefx/pull/37273>.

### Other information

Removing the reference assembly as requested in <https://github.com/dotnet/runtime/issues/37496> would also fix this.

**Comment by ericstj** [comment]
Thank you for the report.  We no longer build these compat packages and are unlikely to make this type of breaking change in servicing.

**Comment by KalleOlaviNiemitalo** [comment]
That is unfortunate. I'll use [Microsoft.CodeAnalysis.BannedApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.BannedApiAnalyzers), then.

```
M:System.HashCode.GetHashCode;Always throws NotSupportedException.
M:System.HashCode.Equals(System.Object);Always throws NotSupportedException.
```
