### ISSUE TITLE
Strange logic in System.Data.ProviderBase.DbMetaDataFactory.FindMetaDataCollectionRow()

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/runtime#39620]
### Description
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Common/src/System/Data/ProviderBase/DbMetaDataFactory.cs#L225-L314

Seems the code here want to do an case-sensitive match first, and fallback to an case-insensitive match, and throw if get more than one matches(in case-sensitive or case-insensitive).
But if it first hit an case-sensitive match, and then some case-insensitive match, var `requestedCollectionRow` will be overwrite by the last case-insensitive match, but won't throw `AmbigousCollectionName` since `haveExactMatch` is true, and finally return the case-insensitive result instead of the extra match one.

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Common/src/System/Data/ProviderBase/DbMetaDataFactory.cs#L280
Is it the expected logic? Maybe it should be `else if (!haveExactMatch)` here instead?

### Regression?
No. And didn't hit any problem with this, just found this when do some research for the behavior of `DbConnection.GetScmema()`.

### Other information
***Note: There is also some copy of this file in OleDb and MD.SqlClient, which have the same problem.***
https://github.com/dotnet/runtime/search?q=FindMetaDataCollectionRow&unscoped_q=FindMetaDataCollectionRow
https://github.com/dotnet/sqlclient/search?q=FindMetaDataCollectionRow&unscoped_q=FindMetaDataCollectionRow

**Comment by roji** [comment]
I agree this seems like a bug... @ajcvickers?

**Comment by roji** [comment]
@yyjdelete are you interested in submitting a PR to fix this?
