### ISSUE TITLE
Support AggressiveInlining in mono interpreter?

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#39632]
The mono interpreter does not support `[MethodImpl(MethodImplOptions.AggressiveInlining)]` and appears to only inline leaf methods that do not have conditionals. This was determined by logging the interpreter calls and discussion with @BrzVlad.

Some data and examples are shown below.

However, supporting inlining is not expected to significantly affect performance for the System.Text.Json scenario shown below (pending additional measurements), but would likely help more in other JSON scenarios (such as serializing a long string) and other scenarios where a tight loop is assumed and that would otherwise be inlined outside of the interpreter.

## JSON Deserialization usages
When deserializing a very simple 2-property POCO, these JSON methods are called by the interpreter but are normally inlined with the JIT:
```
calls 7	 Method System.Text.Json.Utf8JsonReader:HasMoreData ()
calls 2	 Method System.Text.Json.JsonClassInfo:GetKey (System.ReadOnlySpan`1<byte>)
calls 3	 Method System.Text.Json.JsonReaderHelper:IndexOfQuoteOrAnyControlOrBackSlash (System.ReadOnlySpan`1<byte>)
calls 5	 Method System.Text.Json.JsonHelpers:ReadWithVerify (System.Text.Json.Utf8JsonReader&)
calls 2	 Method System.Text.Json.Utf8JsonReader:HasMoreData (System.Text.Json.ExceptionResource)
calls 2	 Method System.Text.Json.ReadStack:SetConstrutorArgumentState ()
calls 2	 Method System.Text.Json.JsonClassInfo:IsPropertyRefEqual (System.Text.Json.PropertyRef&
calls 1	 Method System.Text.Json.JsonSerializerOptions:GetReaderOptions ()
calls 1	 Method System.Text.Json.Utf8JsonReader:UpdateBitStackOnEndToken ()
calls 1	 Method System.Text.Json.Utf8JsonReader:get_IsLastSpan ()
calls 1	 Method System.Text.Json.BitStack:SetFirstBit ()
calls 1	 Method System.Text.Json.JsonPropertyInfo`1<SimpleMonoBenchmarks.SimpleStructWithProperties>:get_ConverterBase ()
```
These represent ~31 calls out of 184 or about 17% of the total method calls.

The System.Text.Json project has 85 explicit usages of `[MethodImpl(MethodImplOptions.AggressiveInlining)]` in addition to many more assumed (small methods with conditional statements). STJ makes use of System.Text.Encoding.Web which also assumes inlining mostly during serialization (not deserialization).

In addition, here some other non-STJ that may or may not be possible to inline:
```
calls 13 Method intptr:op_Addition (intptr
calls 3	 Method intptr:op_Subtraction (intptr
calls 1	 Method System.Span`1<byte>:op_Implicit (System.Span`1<byte>)
calls 3	 Method intptr:op_Subtraction (intptr
calls 1	 Method System.Span`1<byte>:op_Implicit (byte[])
calls 4	 Method System.Math:Min (int
calls 1	 Method System.MemoryExtensions:AsSpan (string)
calls 1	 Method System.Span`1<byte>:Clear ()
```

## Simple perf test
Consider this simple test:
```cs
        public static bool s_bool = false;

        public static void Inline_Method_Test()
        {
            const long Iterations = 100_000_000;
            bool b=false;

            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();

            for (long l = 0; l < Iterations; l++)
            {
                b = Method_Test(s_bool);
            }

            stopWatch.Stop();

            Console.WriteLine($"{stopWatch.ElapsedMilliseconds} ms");
            Console.WriteLine(b.ToString()); // ensure no optimizations short-circuit test code
        }

        private static bool Method_Test(bool b)
        {
            if (b)
            {
                return true;
            }
            return false;
        }
```

This is not inlined because it has conditionals. Adding `[MethodImpl(MethodImplOptions.AggressiveInlining)]` does not help with the interpreter.

This runs in 2219ms locally. Substract 914ms for the `for` loop overhead results in 1305ms for calling the method, running the method and returning from the method.

If we lift the implementation up, emulating `inlining`:
```cs
            for (long l = 0; l < Iterations; l++)
            {
                if (b)
                {
                    b = true;
                }
                else
                {
                    b = false;
                }
            }
```
then it runs in 1309-914=395ms.

Thus for this simple case calling a method makes it ~3x as expensive versus if it was inlined.

Since the loop factor here is 100_000_000, the actual time for a single call is very small and since there are not a huge number of calls like this in STJ, it is not expected to increase performance significantly for STJ. However consider that the mono and core JIT can run the same method (when `[AggressiveInlining]` is used) in ~20ms or ~65x faster (1305/20) which for other scenarios with many more method calls and\or more arguments that would need to be marshalled then this becomes more significant especially when comparing against JIT.

Note that under WASM, this test runs about 1.7x slower but the ~3x factor remains.

## No good alternatives
Consider this wrapper method that the serializer calls for almost every "Read()" call to the `Utf8JsonReader`:
```cs
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void ReadWithVerify(this ref Utf8JsonReader reader)
        {
            bool result = reader.Read();
            Debug.Assert(result);
        }
```

This assumes no overhead and is just a debug check to ensure the reader didn't run out of buffer space.

Without support for aggressive inlining, it is not possible to author code like this without affecting performance. An attempt at a work-around to remove this method code and manually "lifting up" the code to each call site decreases the maintainability and understandability of the code.

**Comment by BrzVlad** [comment]
This has since been fixed.
