### ISSUE TITLE
Blazor WebAssembly error from GZipStream

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#39635]
### Describe the bug
Blazor WebAssembly throws an error when `GZipStream` is used.

> ZLibException: The underlying compression routine could not be loaded correctly. DllNotFoundException: libSystem.IO.Compression.Native assembly:<unknown assembly> type:<unknown type> member:(null)", DebugException="System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly. ---> System.DllNotFoundException: libSystem.IO.Compression.Native assembly:<unknown assembly> type:<unknown type> member:(null) at System.IO.Compression.ZLibNative.ZLibStreamHandle.InflateInit2_(Int32 windowBits) at System.IO.Compression.ZLibNative.CreateZLibStreamForInflate(ZLibStreamHandle& zLibStreamHandle, Int32 windowBits) at System.IO.Compression.Inflater.InflateInit(Int32 windowBits) --- End of inner exception stack trace --- at System.IO.Compression.Inflater.InflateInit(Int32 windowBits) at System.IO.Compression.Inflater..ctor(Int32 windowBits, Int64 uncompressedSize) at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize) at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen) at Grpc.Net.Compression.GzipCompressionProvider.CreateDecompressionStream(Stream stream) at Grpc.Net.Client.StreamExtensions.TryDecompressMessage(ILogger logger, String compressionEncoding, Dictionary`2 compressionProviders, Byte[] messageData, Int32 length, Nullable`1& result) at Grpc.Net.Client.StreamExtensions.<ReadMessageAsync>d__5`1[[Grpc.Testing.SimpleResponse, InteropTestsGrpcWebClient, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].MoveNext() at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__71[[Grpc.Testing.SimpleRequest, InteropTestsGrpcWebClient, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad],[Grpc.Testing.SimpleResponse, InteropTestsGrpcWebClient, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].MoveNext()

GZipStream use to work. The error started after moving Blazor app from netstandard2.1 to net5.0.

Seen when building app in `mcr.microsoft.com/dotnet/nightly/sdk:5.0` container. Current SDK version is `5.0.100-preview.7.20364.3`

### To Reproduce
1. git clone https://github.com/JamesNK/grpc-dotnet.git
2. git checkout jamesnk/multitarget-net5
3. docker-compose -f docker-compose.yml build grpcweb-server
docker-compose -f docker-compose.yml build grpcweb-client
docker-compose -f docker-compose.yml up -d grpcweb-server
docker-compose -f docker-compose.yml up -d grpcweb-client
4. Browse to http://localhost:8081/
5. Click run all
6. See red failure messages

![image](https://user-images.githubusercontent.com/303201/87846585-013d7800-c925-11ea-898c-b2b6950842ed.png)

**Comment by mkArtakMSFT** [comment]
Thanks @JamesNK.
@marek-safar this is important for the gRPC scenario.

**Comment by ericstj** [comment]
Could use the managed implementation of DEFLATE, which will likely be very slow.  Seems like something better should be available.

**Comment by JamesNK** [comment]
FYI I mentioned that this error started after moving Blazor app from netstandard2.1 to net5.0. It is a regression from Blazor WebAssembly on .NET Core 3.1.

**Comment by ericstj** [comment]
I think Mono was using a managed implementation.  So I guess that could mean the bar is low for perf.

**Comment by JamesNK** [comment]
No one has complained about performance of this in 3.1. If performance is equal in 5.0 then that is fine.

**Comment by akoeplinger** [comment]
This should work but it was only enabled recently. @JamesNK could you please try out a later preview8 build?

**Comment by StevenGranados** [comment]
This does work in the nightly build.

**Comment by akoeplinger** [comment]
Closing as this is fixed in later builds.
