### ISSUE TITLE
Add PR templates (default and servicing)

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#39646]
As we approach .NET 5, we are nearing branching off .NET 5 and moving to a servicing model after release. For the servicing model, we have an ad-hoc PR template that we require, but we don't have it saved anywhere. We end up pointing people to previous servicing PRs as examples.

We should add a servicing PR template to simplify this process and make it easier to set up servicing PRs right the first time.

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by ericstj** [comment]
Agree that it would be nice to have PR templates in the system for various ask-modes.

**Comment by Anipik** [comment]
> Agree that it would be nice to have PR templates in the system for various ask-modes.

@ericstj what do u mean by various ask modes ? wont the template be always the same specifying the risk, impact, description, regression ?

**Comment by ericstj** [comment]
If servicing and release are the same that’s fine.  If different they can have different templates.
