### ISSUE TITLE
Add source-build "smoke-test" product build

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#39647]
This would do the following build:

>./build.sh -s clr+libs -c release

With the following dependencies:

- `cmake 3.6.2`
- `llvm-3.9`

**Comment by ViktorHofer** [comment]
Closing as we already have protection in place for this: https://github.com/dotnet/runtime/blob/d058930b2bf416635710b8b4022839a1ee1b8e6e/eng/pipelines/global-build.yml#L125-L137. We also protect a non portable build with this.
