### ISSUE TITLE
Some OOB packages are getting NETStandard.Library package dependency on .NET 461 which shouldn't happen now that we always have net461 configurations

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#39641]
One concrete example for this is Microsoft.Extensions.Logging.Console, if you build this package today you will get a package that looks like this:

![image](https://user-images.githubusercontent.com/13854455/87974806-791fb580-ca7f-11ea-9d1f-8fdd2d8261e5.png)

I haven't done much digging on this yet but we should investigate this as this will have an impact on package restore size. My hunch here is that what is causing this is having dependencies on netstandard1.x (where x is 0-5). I have validated is that in the end this will not cause the shims to get added and the package is still working as expected, but the issue here is that this is causing package restore to require restoring a significantly higher number of packages than desired so we should find the issue and fix it.

cc: @ericstj

**Comment by joperezr** [comment]
Just adding more info here, I think the Task adding this dependency is ApplyMetaPackages Task but knowing exactly what might be going on will probably require debugging the Task. My hunch for this particular package is that it depends on System.Runtime.InteropServices.RuntimeInformation which is a netstandard1.1 assembly and it is part of .NETStandard.Library package so that is most likely what is triggering this. To fix this, we may need to add a special condition on .NET Framework where we exclude the .NET STandard library metapackage reference always, and then just have the packaging infrastructure to emit the package reference directly to System.Runtime.InteropServices.RuntimeInformation instead.

**Comment by ericstj** [comment]
Maybe we should just universally suppress NETStandard.Library meta-package on .NETFramework.

**Comment by joperezr** [comment]
yup that is what I meant with what I said above 😆

**Comment by ViktorHofer** [comment]
@ericstj as @joperezr is current OOF, would you be the best person to fix this?

**Comment by ericstj** [comment]
Lets keep it on the backlog for the moment.  It should be a simple fix, I may be able to get to it or I can assign someone when the time window gets closer to ZBB.

**Comment by joperezr** [comment]
Reopening to track the ingestion of this on dotnet/runtime which will actually fix the issue.
