### ISSUE TITLE
Introduce QuaranTime: a relatable modern-day relative time

### ISSUE THREAD

**Issue by kzu** [dotnet/runtime#39665]
## Background and Motivation

Just like [Unix time](https://en.wikipedia.org/wiki/Unix_time) is a system for describing a point in time relative to the Unix epoch, **QuaranTime** (from *quarantine time*) is also a way to represent time relative to the beginning of a [specific quarantine lockdown](https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Argentina#Mandatory_lockdown).

The Unix epoch, being 1 January 1970, happened a "long" time ago and therefore seconds (and even moreso milliseconds) from it are already fairly large numbers (currently, 10 and 13 digits respectively). By comparison, in Quarantine epoch they are 3 digits shorter currently. 

But moreover, since the COVID-19 epoch will likely be remembered far more vividly by current and future generations, it seems like a great opportunity to adopt a more easily relatable epoch.

I propose the date 3 March 2020 (2020-03-20) GMT-0300 for the **QuaranTime** epoch, for the following reasons: 
* It's very easy to remember (20/03/20)
* Even the timezone is easy to remember since it's the same as the month (-03hrs)
* I'm from Argentina ¯\_(ツ)_/¯

## Proposed API

```diff
namespace System
{
  public class DateTimeOffset
  {
+    public static DateTimeOffset FromQuaranTimeMilliseconds (long milliseconds);
+    public static DateTimeOffset FromQuaranTimeSeconds (long seconds);
+    public long ToQuaranTimeMilliseconds ();
+    public long ToQuaranTimeSeconds ();
```

Optionally, the actual epoch value could also be exposed:

```diff
namespace System
{
  public class DateTimeOffset
  {
+    public static DateTimeOffset QuaranTimeEpoch { get; }
```

The proposed API follows the design of the existing Unix-related members (see [ToUnixTimeMilliseconds](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.tounixtimemilliseconds?view=netcore-3.1), [ToUnixTimeSeconds](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.tounixtimeseconds?view=netcore-3.1), [FromUnixTimeMilliseconds](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.fromunixtimemilliseconds?view=netcore-3.1) and [FromUnixTimeSeconds](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.fromunixtimeseconds?view=netcore-3.1)).

## Usage Examples

``` C#
var ms = DateTimeOffset.Now.ToQuaranTimeMilliseconds();
// Save it somewhere, then retrieve the date with:
var date = DateTimeOffset.FromQuaranTimeMilliseconds(ms);
```
-->

## Alternative Designs

An alternative design would be to introduce `ToQuaranTimeMilliseconds` and `ToQuaranTimeSeconds ` as extension methods to `DateTimeOffset`, but that leaves the other two members (`FromQuaranTime*`) in need of a place. This could be a new type, `QuaranTime`, like in [my project](https://www.cazzulino.com/QuaranTime). 

## Risks

There is a real risk that nobody will use UnixTime-related values anymore and we could even cause people to not even know what Unix ever was 😇. Not to mention what the Unix epoch date itself is, which might already be at risk even without implementing the proposed API.

I don't think there are any risks of regressions though, since prior to this year, nobody knew what living in quarantine even was like.

## Workarounds

You can use [QuaranTime](https://www.cazzulino.com/QuaranTime) in the meantime, source available in [GitHub](https://github.com/kzu/QuaranTime).

**Comment by jeffhandley** [comment]
Should methods that compare two `QuaranTime` values just return random `TimeSpan` values since perception of time is disrupted during quarantine?

**Comment by kzu** [comment]
Might not be such a good idea in the end. Closing. Maybe the start of the new millennium (01-01-2000) might be better and more neutral.
