### ISSUE TITLE
CAA Record Capabilities with .NET

### ISSUE THREAD

**Issue by yuiichiiros** [dotnet/runtime#39666]
I'm working on a program where one of the features is that, given a domain name, it will query for that domain's CAA records and return the CAA records in a string format. I first tried finding a way to do this using .NET, but it seems that this capability doesn't exist. I mostly looked in the DNS class, so maybe I'm missing something, but can someone confirm/deny if this capability already exists? If it doesn't, would it be possible to add this to .NET in the future?

**Comment by KalleOlaviNiemitalo** [comment]
There is a third-party DNS client library that claims to support CAA records. <https://dnsclient.michaco.net/docs/DnsClient.Protocol.CaaRecord.html>

Its author filed <https://github.com/dotnet/runtime/issues/19443> to request adding such features to .NET.

**Comment by ericstj** [comment]
Also cc @bartonjs since this is System.Security related.

**Comment by wfurt** [comment]
since there is already issue opened, what do you expect here @yuiichiiros?
It seems like duplicate.

**Comment by karelz** [comment]
Duplicate of #19443
