### ISSUE TITLE
out-of-proc COM feature in Core 3.x missing

### ISSUE THREAD

**Issue by dougie1970** [dotnet/runtime#39693]
@DoCode I am a big fan of out-of-proc COM, has some performance concerns but addresses many issues. As far as setting up an activatable COM server in a .NET Core application, that is probably possible but will require working with the [hosting API](https://github.com/dotnet/runtime/blob/master/docs/design/features/native-hosting.md) and having a good understanding of authoring a [COM server](https://docs.microsoft.com/windows/win32/com/com-clients-and-servers) in general. It may also require some additional work if the interfaces aren't defined in MIDL because `TlbExp` doesn't exist for .NET Core.  In order to consume the interfaces in a non-managed environment, headers or a TLB and [proxy/stubs](https://docs.microsoft.com/windows/win32/com/building-and-registering-a-proxy-dll) would need to be created and registered.

There is also the slightly cheaper way to get to an out-of-proc COM scenario using the [Running Object Table](https://docs.microsoft.com/windows/win32/api/objidl/nn-objidl-irunningobjecttable). A managed example using .NET Framework is [here](https://github.com/AaronRobinsonMSFT/COMInterop/tree/master/OutOfProcDemo).

The above aside, the build issue being faced in this scenario involves building a COM server class library, not a standalone application. A .NET Core application - not library - exposing a COM server should build in a self-contained manner, however that scenario hasn't been tested in .NET Core - see the [COM-activation](https://github.com/dotnet/runtime/blob/master/docs/design/features/COM-activation.md) design documentation for .NET Core.

_Originally posted by @AaronRobinsonMSFT in https://github.com/dotnet/runtime/issues/870#issuecomment-573499617_

**Comment by dougie1970** [comment]
@AaronRobinsonMSFT - how does this feature for out-of-proc COM get completed and into a Core 3.x version?  It would be really nice to have this same feature as it works in Framework, where regasm.exe (or similar/new command), would register a .NET Core 3.x executable.  Without this capability, it would be essentially losing a nice to have feature in existing software to port it to .NET Core.  I assume @DoCode would need this also.

**Comment by AaronRobinsonMSFT** [comment]
>how does this feature for out-of-proc COM get completed and into a Core 3.x version?

@dougie1970 It comes down to priorities and customer demand. Right now we have some interest but not enough compared to other feature request in interop. Adding first class support would be a non-trivial amount of work and there would be some very sharp edges to fix up. Adding this for Core 3.x isn't something that is going to happen to be honest. The amount of feature work to enable this would not make it past our servicing bar.

It is possible for future runtime versions and that is tracked by https://github.com/dotnet/runtime/issues/38814. Adding your scenario to that issue would help us to keep track of customer need and goals. Let's continue the conversation there.
