### ISSUE TITLE
CollectionBase implements IList.Remove to throw, contrary to docs

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#39703]
https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist.remove?view=netcore-3.1#notes-to-implementers:

> If `value` is not in the list, the `Remove(Object)` method should do nothing. In particular, it should not throw an exception.

```cs
using System.Collections;

public static class Program
{
    class C : CollectionBase { }

    public static void Main()
    {
        IList list = new C();

        // (Picture an arbitrary amount of distance across classes here)

        // System.ArgumentException:
        // 'Cannot remove the specified item because it was not found in the specified Collection.'
        list.Remove(new object());
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by eiriktsarpalis** [comment]
I feel that we should probably just update the docs to reflect the current behaviour. Changing the behaviour could break users.

**Comment by eiriktsarpalis** [comment]
Changing interface implementations to match the contract now has precedent with #36926. We should consider doing the same thing here /cc @stephentoub

**Comment by eiriktsarpalis** [comment]
As illustrated in https://github.com/dotnet/runtime/pull/46166#issuecomment-754168515 many classes inheriting from `CollectionBase` depend on the current throwing behaviour. So in the interest of maintaining compatibility, we will preserve the current behaviour even though it is inconsistent with `IList` specification.
