### ISSUE TITLE
DevCert install is invalid on Windows

### ISSUE THREAD

**Issue by ststeiger** [dotnet/runtime#39713]
The .NET DevCert seems to yield invalid certificate for NodeJS (Microsoft.AspNetCore.NodeServices). 
Operating system is Windows 10. 
Domain is localhost, .NET Core 3.1. 

Sample:
https://github.com/ststeiger/MyBlog/blob/master/MyBlogCore/Startup.cs

Here, parsoid downloads a configuration file from "https://localhost:PORT/w/api.php". 
On https, this fails, because NodeJS complains about "invalid certificate". 

Anyone attempting to reproduce must override https://en.wikipedia.org with https://localhost:PORT in
node_modules/parsoid/lib/config/wmf.sitematrix.json

**Comment by vcsjones** [comment]
Node, to my knowledge, does not use the OS trust store. My understanding then is that you need to export the developer certificate as a X509 certificate, then specify [`NODE_EXTRA_CA_CERTS`][1].

I don't know the best way to get a DER or PEM encoded version of the developer certificate, but since you are on Windows you should be able to find it in the certificate store, and export it from there. 

[1]: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

**Comment by davidfowl** [comment]
We've added support for exporting the cert to pem in .net 5 fwiw

**Comment by ststeiger** [comment]
@davidfowl: I have written my own utility to manage/read/convert SSL certificates years ago.

**Comment by davidfowl** [comment]
It supports pem in 5.0, so that will improve

**Comment by ststeiger** [comment]
Good, that's good to hear.

**Comment by ststeiger** [comment]
One more thing: 
The .NET integrated cryptography does not support to create an RSA provider from just exponent and modulus. 
Though certificates with only modulus and exponent are perfectly valid. 
JetBrains license server, for example, used to use such a certificate. 
I had to go to great lengths to get it to work with BouncyCastle. 
Turns out, unlike BouncyCastle, Python can read out these certificate files fine, and give you the corresponding bigintegers.

**Comment by vcsjones** [comment]
> The .NET integrated cryptography does not support to create an RSA provider from just exponent and modulus.

If there is something that is missing to making working with RSA keys easier, please feel free to open another issue.

> Though a PEM-file with only modulus and exponent is perfectly valid.

.NET Core 3 has `RSA.ImportRSAPublicKey` to import a DER encoded PKCS1 key, and `RSA.ImportSubjectPublicKeyInfo` to import a DER encoded PKCS8 public key.

> Though a PEM-file with only modulus and exponent is perfectly valid.

.NET 5 will have [`RSA.ImportFromPem`][1] which will support PEM encoded RSA public keys in either PKCS1 ("BEGIN RSA PUBLIC KEY") or SPKI ("BEGIN PUBLIC KEY") form.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.importfrompem?view=net-5.0
