### ISSUE TITLE
[Perf -19%] System.Net.NetworkInformation.Tests.PhysicalAddressTests.PAShort

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39720]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/cf774155778050ad93a9158caf389e26d49f1411...bf0076c80b9b2f1d2080016c7c7edb66ed61fa73)

### Regressions in System.Net.NetworkInformation.Tests.PhysicalAddressTests

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
PAShort | 14.44 ns | 17.14 ns | 1.19 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Net.NetworkInformation.Tests.PhysicalAddressTests_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Net.NetworkInformation.Tests.PhysicalAddressTests.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter "System.Net.NetworkInformation.Tests.PhysicalAddressTests*"
```
<details>

#### System.Net.NetworkInformation.Tests.PhysicalAddressTests.PAShort

```log
[14.317 ; 14.884) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[14.884 ; 15.542) | @@@@@@@@@
[15.542 ; 16.023) | @@@
[16.023 ; 16.671) | @
[16.671 ; 17.238) | @@@@@@@@@@@@@@@@@@@@@@@
[17.238 ; 17.945) | @@@
[17.945 ; 18.526) | @@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by karelz** [comment]
Triage: Not important for 5.0, still might be nice to see what caused it, but there haven't been any changes in the space ...
Fine to just close it as "OK" in future.

**Comment by DrewScoggins** [comment]
@tannergooding who mentioned that he thought there was some change in this space.

**Comment by wfurt** [comment]
hmm That lines up with #37546 on Jul 17. That change did not go through ncl.

**Comment by danmosemsft** [comment]
It does seem very likely #37546. It's the only plausible commit in this interval . cc @tkp1n in case he is interested.

**Comment by tkp1n** [comment]
The additional ~3ns can easily be explained by the added overhead of using the new public hex encoding API instead of an internal method without as many input checks.

The easy fix would be to revert [this line](https://github.com/tkp1n/runtime/blob/8c8919805247e9cfbb362b48bbd41c179b50c44e/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/PhysicalAddress.cs#L93) from: 
`return Convert.ToHexString(_address.AsSpan());` 
back to 
`return HexConverter.ToString(_address.AsSpan(), HexConverter.Casing.Upper);`

I've opened #39702 (some time ago) to vectorize hex encoding/decoding. This would provide a or a more sustainable solution that'll also help other places in the framework. Until now, no one from the team seemed to care.

**Comment by danmosemsft** [comment]
@tkp1n thanks for the offer - I've assigned this to you. We would welcome a PR if it would reverse this small regression. We ARE interested in https://github.com/dotnet/runtime/pull/39702 😊- we've just been pretty occupied on bugs, so it may miss the 5.0 cutoff.

**Comment by danmosemsft** [comment]
Per discussion in the PR, closing this as acceptable for improved code reuse.

**Comment by adamsitnik** [comment]
Thre regression is between 30-50%, are we sure that this method is never on hot path?

## System.Net.NetworkInformation.Tests.PhysicalAddressTests.PAShort

| Conclusion |  Base |  Diff | Base/Diff | Modality | Operating System        | Bit | Processor Name                              | Base Runtime    | Diff Runtime         |
| ---------- | -----:| -----:| ---------:| -------- | ----------------------- | --- | ------------------------------------------- | --------------- | --------------------- |
| Slower     | 19.96 | 37.67 |      0.53 |          | Windows 10.0.18363.1016 | Arm | Microsoft SQ1 3.0 GHz                       | .NET Core 3.1.6 | 5.0.100-rc.1.20413.9 |
| Slower     | 10.44 | 15.50 |      0.67 |          | Windows 10.0.18363.959  | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20404.3 |
| Slower     | 10.94 | 15.55 |      0.70 |          | Windows 10.0.18363.959  | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3 |
| Slower     | 12.92 | 17.58 |      0.73 |          | Windows 10.0.19041.450  | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20413.9 |
| Slower     |  9.39 | 13.49 |      0.70 | bimodal  | Windows 10.0.19042      | X64 | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3 |
| Slower     | 13.36 | 29.57 |      0.45 | bimodal  | Windows 10.0.19041.450  | X86 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20419.5 |
| Slower     | 16.15 | 23.93 |      0.67 |          | ubuntu 18.04            | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20403.23|
| Slower     | 17.98 | 26.68 |      0.67 |          | macOS Mojave 10.14.5    | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20404.2 |
| Slower     | 17.38 | 27.83 |      0.62 |          | ubuntu 18.04            | X64 | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3 |
