### ISSUE TITLE
More robust searching for clang and llvm

### ISSUE THREAD

**Issue by poizan42** [dotnet/runtime#3972]
Currently we can only find clang if it's on the path with the name "clang", and we only attempt to locate the llvm-3.5 tools (even if the version of clang is based on a newer llvm version).

It seems that the only way to locate clang is to look for a clang-\d+.\d+ somewhere on the path. Given a clang we also need to figure out which llvm it is based on to get the correct version of the llvm tools. We can ask it with --version, but that output isn't very consistent. E.g. on a debian system:

```
Debian clang version 3.5.0-9 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

and on Mac OS X:

```
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
10.10.2
```

**Comment by jkoritzinsky** [comment]
I think with the work that @am11 did a few months ago to improve and unify our compiler discovery we can close this.
