### ISSUE TITLE
System.Half backport to .Net Standard

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#39734]
Half is an amazing type, and I'm sure many Math-related projects would like to integrate it, but currently can't / have to multi-target to .Net 5
A behaviour like with `Span`/`Memory` on .Net Standard would be great, with a NuGet package bringing the functionality on older platforms, while not doing anything on .Net 5+

**Comment by Perksey** [comment]
+1 Something akin to Microsoft.Bcl.HashCode (but for Half obviously) would be great.

**Comment by jkotas** [comment]
cc @terrajobst @ericstj 

Related: https://github.com/dotnet/runtime/issues/28285

**Comment by ericstj** [comment]
cc @pgovind @jeffhandley

**Comment by jeffhandley** [comment]
Hi @HurricanKai. Thanks for suggesting this, but we have no plans to backport `Half` to ship it against previous versions.

**Comment by Perksey** [comment]
Note: We've released the [Ultz.Bcl.Half](https://nuget.org/packages/Ultz.Bcl.Half) to do this.
