### ISSUE TITLE
Annotate DependencyInjection to make it linker friendly

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#39745]
The DependencyInjection library uses IL Emit and Reflection in order to create service implementations. However, this isn't linker friendly because the ILLinker will trim the constructors from these types, since it doesn't know anyone is using them.

We should annotate the DependencyInjection library with `DynamicallyAccessedMembers` attributes, so the ILLinker knows to preserve the constructors correctly. This should allow us to remove the `Microsoft.Extensions.*` assemblies from [Blazor's "type granularity" list](https://github.com/dotnet/aspnetcore/blob/fb28ce3ec2531327d6f98bfb7d44ad160393a925/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Components.Wasm.targets#L372-L374), and instead fully trim these assemblies, just like the `System.*` assemblies.

I have a prototype of this [here](https://github.com/dotnet/runtime/compare/master...eerhardt:AnnotateDependencyInjection), where the size reduction is decent:

**Uncompressed IL file sizes:**
    - Before 2,425,856 bytes
    - After    2,360,320 bytes

**Compressed (.br) all file sizes in wwwroot\_framework:**
    - Before 1,464,786 bytes
    - After    1,443,696 bytes

We can see a ~20 KB size reduction in the Brotli compressed file sizes with this change.

cc @pranavkm @SteveSandersonMS @joperezr @layomia @davidfowl

**Comment by eerhardt** [comment]
Moving to 6.0, as the size savings here is not critical for 5.0.

**Comment by davidfowl** [comment]
Any chance we can do this in 5.0? Is there any harm?
