### ISSUE TITLE
Blazor WebAssembly Client cant create WebSockets in Preview 7

### ISSUE THREAD

**Issue by Stryxus** [dotnet/runtime#39757]
After upgrading my Blazor WebAssembly Client project to .NET 5 Preview 7, ClientWebSocket doesnt seem to connect at all via .ConnectAsync()

No websocket appears in the browsers dev tools network list and yes, the servers socket is live, iv connecting to it manually.

How to reproduce?
Simply create a ClientWebSocket and connect it to a websocket receiver (In my case was ws://localhost:5000/state).

**Comment by lewing** [comment]
wasm WebSocket support isn't in in preview7, it will be in preview8

**Comment by Stryxus** [comment]
@lewing Thanks for confirming. This really hit my app but, thankfully, in the meantime i can use old school javascript for websockets.

**Comment by lewing** [comment]
@Stryxus sorry for the trouble, they should be working in p8/master builds already so it is just a matter of time
