### ISSUE TITLE
Host and Application Lifetime Notifications (order) Bug/Question

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/runtime#39764]
# Description
Namespace: Microsoft.Extensions.Hosting.Internal 
Class: Host
I'm using current (3.1.xxx) Hosting Environment for a Winforms demo, and i have lot of problems with the Host and Application shutdown.

I found one one place in the source code that may the reason:

Source code file: [src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs)

Inside the "StartAsync" method everything looks fine: host is started as first and the applicationLifeTime is created and notifications for start are sent (Line 58)

For me, the "StopAsync" method looks wrong regarding the notifications about hosting-lifetime and application-lifetime:

Line 92 stops the hostingLifetime
Line 95 stops the applicationlifetime

That may be the wrong order, assuming that host owns app, then we should assume/expect that applicationLifetime ends BEFORE the hostLiftime!

### Configuration
dotnetcore 3.1.1xx with current packages

**Comment by maryamariyan** [comment]
Closed via https://github.com/dotnet/runtime/pull/39832
