### ISSUE TITLE
Misbehaving RegionInfo.Name in net core vs net framework

### ISSUE THREAD

**Issue by genyx** [dotnet/runtime#39769]
### Description

The string property RegionInfo.Name has different output on dotnet framework vs dotnet core. This seems to be a bug.

When using the string-parameter constructor like `new RegionInfo("de-CH").Name` in an dotnet core (3.1) app vs a framework app (4.8) the output is different.

According to the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.regioninfo.name?view=netcore-3.1) (see "Remarks" section) the behaviour of passing a full culture name such as "de-CH" should be that the `Name` Property equals to that string. This is correct in dotnet framework but not in net core.

#### Reproduce: 

Write a minimal program like following and compile for framework and core

```c#
static void Main(string[] args) {
    Console.WriteLine(new RegionInfo("de-CH").Name);
    // output should be "de-CH"
    // output in fx 4.8 is "de-CH"
    // output in core 3.1 is "CH"
}
```

### Configuration

Tested builded with 4.7.2, 4.8 (correct behavior) and net core 2.2 and 3.1 (both wrong behaviour).

Running Windows 10 Pro 2004 with net core sdk 3.1.301 and net framework 4.8 dev pack installed.

### Regression

Correct behaviour in Framework (4.7.2, 4.8), not in core (2.2 and 3.1).

### Other information

* Maybe related to but not the same as [17362](https://github.com/dotnet/runtime/issues/17362)

**Comment by tarekgh** [comment]
@genyx this is intentional change we did since the .NET Core 1.0. returning the region name and not the culture name is the right behavior. could you explain more why this is a problem for you?

**Comment by tarekgh** [comment]
We need to fix the documentation though.

**Comment by tarekgh** [comment]
I have created the doc PR https://github.com/dotnet/dotnet-api-docs/pull/4560 to fix the doc. @genyx I am closing this issue but feel free to respond back with any question. Thanks for your report.

**Comment by genyx** [comment]
I was creating a dropdown menu for country selection and implementing it in our software and webpage when i encountered this behaviour. I needed to create a CultureInfo object out of this (the GUI got RegionInfo objects), which is no longer possible in net core since "CH" can not be parsed to the CultureInfo "de-CH"... I switched to store a CultureInfo internally and got rid of RegionInfo completly.

I'm wondering however, what the plan with NET 5.0 and different behaviour of framework api is... but i think that story is not for this issue.

**Comment by tarekgh** [comment]
> I'm wondering however, what the plan with NET 5.0 and different behaviour of framework api is... but i think that story is not for this issue.

I am not fully understand the question. Usually when we change the behavior of any API we publish a breaking change doc and explain the change. 

For this RegionInfo issue, the .NET Core behavior existed very long ago in .NET Core 1.0 and even existed before that on the framework supported phones platforms. 

>  I needed to create a CultureInfo object out of this (the GUI got RegionInfo objects), which is no longer possible in net core since "CH" can not be parsed to the CultureInfo "de-CH"... I switched to store a CultureInfo internally and got rid of RegionInfo completly.

It is not possible to guarantee you can create CultureInfo from RegionInfo the way you described even in the Full Framework except if you guaranteed the RegionInfo is created from culture info. If this is your case, then keeping the culture info list make sense if you need to use them later. 
We had this change for a good reason. For example, if you create 2 RegionInfo objects from "en-US" and "US", these 2 objects should be equal and that what we are doing in .NET Core. 

anyway, please let's us know if you have any blocking issue we may help telling how you can workaround it.
