### ISSUE TITLE
`System.Half` doesn't generate correct ordered comparison results when both sides are negative

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#39770]
### Description
The comparison methods / operators do not return the correct comparison result when both numbers are negative. For example, `-1 <= NegativeInfinity` returns `true`, when it is obvious that -1 is greater than `NegativeInfinity`.

### Configuration

The code likely isn't specific to a certain H/W or OS. There's only software implementations of those comparison methods.

### Regression?

This bug existed from the initial prototype code in dotnet/corefxlab.

### Other information

The current implementation, `return (short)(left._value) <= (short)(right._value); ` is incorrect when both sides are negative.

Consider the following:
|Actual value|Raw bits            | Signed raw bit comparison | Unsigned raw bit comparison|Half comparison|
|------------|--------------------|---------------------------|-------------------------|---------------|
|          -1|`1 01111 0000000000`| Smaller (-17408)          | Smaller (48128)         | Larger        |
|          -∞|`1 11111 0000000000`| Larger (-1024)            | Larger  (64512)         | Smaller       |
|------------|--------------------|---------------------------|-------------------------|---------------|
|           1|`0 01111 0000000000`| Smaller (15360)           | Smaller (15360)         | Smaller       |
|           ∞|`0 11111 0000000000`| Larger  (31744)           | Larger  (31744)         | Larger        |

This implementation is correct for cases where both sides are positive, but when both sides are negative we get an inverted result. This likely is the same in all 4 ordered comparison operators and `CompareTo` method.

The solution would be to invert the result when `leftIsNegative` is true. (XOR with `leftIsNegative`?)

https://github.com/dotnet/runtime/blob/0e23ef47ff8a2de6a5b5898a849ba00303aba8df/src/libraries/System.Private.CoreLib/src/System/Half.cs#L127-L145

P.S. Apparently we don't have any test that compares two negative values....

**Comment by Gnbrkm41** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
CC. @jeffhandley, @pgovind
