### ISSUE TITLE
Cannot build CoreCLR on Windows

### ISSUE THREAD

**Issue by alexcovington** [dotnet/runtime#39787]
I'm having trouble building the CoreCLR on Windows both in and outside of Visual Studio using the building workflow in the documentation.

Currently, whenever I run the command:

```
.\build.cmd -a x64 -c debug
```

I get the error message:

```
 BUILD: Error: native component build failed. Refer to the build log files for details.
      C:\Users\acovingt\runtime\src\coreclr\..\..\artifacts\log\Debug\CoreCLR_Windows_NT__x64__Debug.log
      C:\Users\acovingt\runtime\src\coreclr\..\..\artifacts\log\Debug\CoreCLR_Windows_NT__x64__Debug.wrn
      C:\Users\acovingt\runtime\src\coreclr\..\..\artifacts\log\Debug\CoreCLR_Windows_NT__x64__Debug.err
C:\Users\acovingt\runtime\src\coreclr\runtime.proj(32,5): error MSB3073: The command ""C:\Users\acovingt\runtime\src\coreclr\build-runtime.cmd" -x64 -debug" exited with code 1.

Build FAILED.

C:\Users\acovingt\runtime\src\coreclr\runtime.proj(32,5): error MSB3073: The command ""C:\Users\acovingt\runtime\src\coreclr\build-runtime.cmd" -x64 -debug" exited with code 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:04:10.35
Build failed.
Some builds failed:
        Configuration: Debug, Architecture: x64
```

The content of the error log file is:

```
    38>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 9009. [C:\Users\acovingt\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\ToolBox\SOS\DacTableGen\gen_dialib.vcxproj]
```

I am able to build using the equivalent scripts in WSL, just not Windows. Any help would be appreciated.

**Comment by hypeartist** [comment]
@alexcovington Try this:

`build.cmd -subset Clr -os Windows_NT -arch x64 -configuration Debug -runtimeConfiguration Debug`

**Comment by alexcovington** [comment]
@hypeartist Same error.

**Comment by hypeartist** [comment]
> Same error.

Yeah. My bad. Sorry. Just pulled the current tree and got build error too. Strange. Worked for me before.

**Comment by alexcovington** [comment]
@hypeartist No worries! I'll wait for a fix and pull then.

**Comment by alexcovington** [comment]
I'm still unable to build using the instructions [here](https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/README.md). I'm still getting the same error message as above. I've successfully been able to build CoreCLR on Ubuntu 20.04.

Any word on a fix?

**Comment by alexcovington** [comment]
I'm still unable to build, receiving the same error message. Are there other log files I should be looking at?

**Comment by hoyosjs** [comment]
Hmm can only think of a couple things. What version of CMake are you using, do you have this path: `Microsoft Visual Studio\2019\Community\DIA SDK`, and what version of the Windows SDK . This should still repro if you do `src/coreclr/build-runtime.cmd`

As for the VS opening folder, we don't have the CMakeLists configured such that you can open the directory and let it build. We define some things in the build scripts as we detect some parameters.

**Comment by alexcovington** [comment]
@hoyosjs Thanks for the tip on the CMakeLists, I'll focus on just getting this to build outside of Visual Studio first.

CMake version is 3.18.0.

I did not have `Microsoft Visual Studio\2019\Community\DIA SDK` on my path, I added that.

I had many versions of the Windows SDK installed, so I uninstalled them all and reinstalled just Windows SDK 10.0.19041.1.

I tried running the `build-runtime.cmd` with defaults from inside `src\coreclr`, build still failed. Here's the last few lines of `artifacts\log\Debug\CoreCLR_Windows_NT__x64__Debug.log`:

```
Build FAILED.

       "C:\Users\acovingt\source\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\install.vcxproj" (default target) (1) ->
       "C:\Users\acovingt\source\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\Users\acovingt\source\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\inject_debug_resources.vcxproj" (default target) (20) ->
       "C:\Users\acovingt\source\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\ToolBox\SOS\DacTableGen\dactablegen.csproj" (default target) (33) ->
       "C:\Users\acovingt\source\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\ToolBox\SOS\DacTableGen\gen_dialib.vcxproj" (default target) (39) ->
       (CustomBuild target) -> 
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 9009. [C:\Users\acovingt\source\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\ToolBox\SOS\DacTableGen\gen_dialib.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:02:13.31
```

**Comment by janvorli** [comment]
@alexcovington it seems that something from the dia library is missing or midl or tlbimpl were not found. Would you mind trying to instrument the src/coreclr/src/ToolBox/SOS/DacTableGen/CMakeLists.txt a bit to pinpoint the culprit?

The instrumentation would be simple. Right after the `FIND_PROGRAM(MIDL midl.exe)` line, you'd add a couple of new lines:
```cmake
message("MIDL found at: ${MIDL}")
message("TLBIMPL found at: ${TLBIMPL}")
message("Attempted to copy ${DIASDK_DIR}/bin/msdia140.dll to CMAKE_CURRENT_BINARY_DIR")
message("DIASDK_DIR: ${DIASDK_DIR}")
```

Then run the `build-runtime.cmd` and after it fails, look up the added messages output in the console.

**Comment by hoyosjs** [comment]
Oh sorry, didn't mean to say that needs to be in the path, but rather if that path exists on your machine.

**Comment by alexcovington** [comment]
@janvorli Seems like it can't find `tlbimp.exe`. I added the lines in your post (changed `TLBIMPL` to `TLBIMP` to match the existing variables) and the output I get when running `build-runtime.cmd` gave me:

```
MIDL found at: C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/midl.exe
TLBIMP found at: TLBIMP-NOTFOUND
Attempted to copy C:/Program Files (x86)/Microsoft Visual Studio/2019/Community//DIA SDK/bin/msdia140.dll to C:/Users/acovingt/source/repos/runtime/artifacts/obj/coreclr/Windows_NT.x64.Debug/src/ToolBox/SOS/DacTableGen
DIASDK_DIR: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community//DIA SDK
```

Am I missing a dependency? What should I install/reinstall to get the executable?

**Comment by janvorli** [comment]
I have tlbimp that is executed during the build at `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\TlbImp.exe`.
It seems you might missing the .NET Framework 4.8 SDK installation in the Visual Studio.

**Comment by alexcovington** [comment]
.NET Framework 4.8 SDK is installed in Visual Studio, but it wasn't anywhere on my PATH. I added it to my PATH and got further in the build, however now I get the error:

```
BUILD: Error: Please install the Redistributable Universal C Runtime.
```

I've confirmed that the Windows Universal C Runtime is installed in VS 2019.

![wucrt](https://user-images.githubusercontent.com/68252706/89344880-74e8c000-d65b-11ea-89d2-56ab3d88b6d0.PNG)

**Comment by alexcovington** [comment]
I've confirmed that Universal CRT is installed on my system at `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64` and is in my LIB environment variable. Some environment variables to help troubleshoot:

```
C:\Users\acovingt\source\repos\runtime [master ≡]> echo $env:LIB
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64;
C:\Users\acovingt\source\repos\runtime [master ≡]> echo $env:PATH
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;C:\Users\acovingt\vcpkg;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\CMake\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Mono\bin;C:\Program Files\Git\cmd;C:\Users\acovingt\AppData\Local\Microsoft\WindowsApps;C:\Users\acovingt\.dotnet\tools;C:\Users\acovingt\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\CMake\bin;C:\Program Files (x86)\Python*;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Users\acovingt\.dotnet\tools;C:\Users\acovingt\AppData\Roaming\npm;C:\Users\acovingt\AppData\Roaming\Python\Python38\Scripts
```

**Comment by hoyosjs** [comment]
That path that you show is the `lib` version or the CRT. You need the redist version. The path is `C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64` or `C:\Program Files (x86)\Windows Kits\10\Redist\<VERSION>\ucrt\DLLs\x64`. Do you have such paths?

**Comment by alexcovington** [comment]
The path exists on my machine, but wasn't in my LIB environment variable. I added it, still getting:

```
  BUILD: Error: Please install the Redistributable Universal C Runtime.
```

Here's PATH and LIB again after adding the Redist path:

```
C:\Users\acovingt\source\repos\runtime [master ≡ +5 ~0 -0 !]> echo $env:LIB
C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64;
C:\Users\acovingt\source\repos\runtime [master ≡ +5 ~0 -0 !]> echo $env:PATH
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;C:\Users\acovingt\vcpkg;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\CMake\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Mono\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64;C:\Users\acovingt\AppData\Local\Microsoft\WindowsApps;C:\Users\acovingt\.dotnet\tools;C:\Users\acovingt\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\CMake\bin;C:\Program Files (x86)\Python*;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Users\acovingt\.dotnet\tools;C:\Users\acovingt\AppData\Roaming\npm;C:\Users\acovingt\AppData\Roaming\Python\Python38\Scripts
```

**Comment by hoyosjs** [comment]
Those don't need to be in your path and lib. Can you save this to a cmd file and run this from a "Developer Command Prompt for VS 2019" and paste the output back here?
```cmd
@if not defined _echo @echo off
setlocal EnableDelayedExpansion EnableExtensions
set "__BuildArch=x64"
set "__UCRTDir=%UniversalCRTSDKDIR%Redist\ucrt\DLLs\%__BuildArch%\"
echo %__UCRTDir%
if not exist "!__UCRTDir!" (echo does not exist)
set "__UCRTDir=%UniversalCRTSDKDIR%Redist\%UCRTVersion%\ucrt\DLLs\%__BuildArch%\"
echo %__UCRTDir%
if not exist "!__UCRTDir!" (echo does not exist)
```

**Comment by alexcovington** [comment]
Here's the output:

```
Redist\ucrt\DLLs\x64\
does not exist
Redist\\ucrt\DLLs\x64\

```

**Comment by alexcovington** [comment]
Oh, my bad, I thought I had run this from the VS Developer Command Prompt, but it was just my normal one. Here is the output from the VS Developer Command Prompt:

```
C:\Program Files (x86)\Windows Kits\10\
C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\
C:\Program Files (x86)\Windows Kits\10\Redist\\ucrt\DLLs\x64\
```

**Comment by hoyosjs** [comment]
Ok, that's some progress. Usually there's a non-versioned installation. Looks like you don't have it. And after that, we would try to fall back to the versioned one: we use `UCRTVersion` to look at it, but seems it's not defined. I'll take a look as to why later (need to update some things, but I can't do that right now). However, if you need to unblock yourself for local testing and checking stuff out, you can add this line to the beginning of `src\coreclr\build-runtime.cmd` for development in your machine:

```
set "UCRTVersion=10.0.19041.0"
``` 

Also, to help investigations later: what folders do you have under `C:\Program Files (x86)\Windows Kits\10\Redist\`. Yours is the only one that I don't have installed:

![image](https://user-images.githubusercontent.com/19413848/89577921-3e8b7c00-d7e6-11ea-9899-4b803c4f1947.png)

**Comment by alexcovington** [comment]
I see, I'll try modifying the `build-runtime.cmd` and see if I can't get it running that way. I'm also going to try rolling back to an older version of the SDK in case maybe that's the problem.

Contents of `C:\Program Files (x86)\Windows kits\10\Redist\`:

```
Directory of C:\Program Files (x86)\Windows Kits\10\Redist

08/04/2020  11:56 AM    <DIR>          .
08/04/2020  11:56 AM    <DIR>          ..
08/04/2020  11:56 AM    <DIR>          10.0.18362.0
08/04/2020  09:27 AM    <DIR>          10.0.19041.0
08/04/2020  09:26 AM    <DIR>          D3D
08/04/2020  09:26 AM    <DIR>          MBN
08/04/2020  11:53 AM    <DIR>          ucrt
               0 File(s)              0 bytes
               7 Dir(s)  207,128,473,600 bytes free
```

**Comment by alexcovington** [comment]
@hoyosjs Ended up getting it to build by modifying `build-runtime.cmd` and hard-coding `__UCRTDir` to point to `C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\`, which is a good enough work around for now and unblocks me. I guess VS2019 just isn't setting the `UniversalCRTSDKDIR` environment variable properly in my case.

Here's the change I made in `build-runtime.cmd`:

```cmd
:: set "__UCRTDir=%UniversalCRTSDKDIR%Redist\ucrxxxt\DLLs\%__BuildArch%\"
set "__UCRTDir=C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\"
    if not exist "!__UCRTDir!" set "__UCRTDir=%UniversalCRTSDKDIR%Redist\%UCRTVersion%\ucrt\DLLs\%__BuildArch%\"
    if not exist "!__UCRTDir!" (
        echo %__ErrMsgPrefix%%__MsgPrefix%Error: Please install the Redistributable Universal C Runtime.
        goto ExitWithError
    )
```

I also spoke with my local IT about my development machine and there may be a Windows licensing issue with it, so I'm starting to wonder if maybe I just have a bad Windows install too...

Thanks for everyone's help! Feel free to close.

**Comment by hoyosjs** [comment]
Good to hear you are unblocked @alexcovington. Those variables get set by Visual Studio when setting up a developer command prompt. I'm not sure why that failed for you, but I'll keep that in mind in case someone reports the same error again.
