### ISSUE TITLE
Infrastructure - Rollout (September 2020)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#39788]
# Overview

We'll use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. Changes will be merged on the first Monday of the month (9/7). The target branch is master.

| Change |  Impact | Assignee |
| --- | --- | --- |
| https://github.com/dotnet/runtime/issues/38919 | Test build script path changes | @trylek |
| https://github.com/dotnet/runtime/pull/41947 | Update SDK baseline version to P8 final | @ViktorHofer |

**Note: The August rollout didn't happen because changes weren't ready. I recycled its issue for September.**

## Archive
- [July 2020](https://github.com/dotnet/runtime/issues/37706)
- [June 2020](https://github.com/dotnet/runtime/issues/35895)
- [May 2020](https://github.com/dotnet/runtime/issues/35202)
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by ViktorHofer** [comment]
Status: We are halfway through with the rollout. The SDK update seems to take a bit more time than expected.

**Comment by jkoritzinsky** [comment]
@ViktorHofer since we've completed the rollout, can we close this issue?

**Comment by ViktorHofer** [comment]
Sure, thanks for the reminder.

**Comment by naricc** [comment]
Is there one of these for October, or is there no roll out that month?

**Comment by ViktorHofer** [comment]
Nothing planned for October :)
