### ISSUE TITLE
System.Text.Json.JsonSerializer.Serialize ignores JsonPropertyName on abstract properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#39790]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1118138/systemtextjsonjsonserializerserialize-ignores-json.html)._

---
<p>Consider the following code:</p><pre>abstract class A
{
    [JsonPropertyName(&quot;id&quot;)]
    public abstract string Id { get; }
}

class B : A
{
    public override string Id =&gt; &quot;Value&quot;;
}

</pre><p>When serializing an instance of type B:</p><p>Expected: JsonPropertyName to affect inheriting class</p><p>{&quot;id&quot;:&quot;Value&quot;}</p><p>Actual: JsonPropertyName has no effect</p><p>{&quot;Id&quot;:&quot;Value&quot;}</p><p>Note: This behavior differs from the one in Newtonsoft.Json and in my opinion is more error prone.</p>

---
#### Feedback Bot on 7/20/2020, 03:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by layomia** [comment]
This is known/by design. Properties cannot inherit System.Text.Json attributes. The attributes need to be placed on each (de)serializable override.
