### ISSUE TITLE
ImmutableArray.CastUp and Cast should be annotated with `class?`

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#39799]
### Description

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L327
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L347

Both of these methods are annotated as `where TOther : class`. However, it's perfectly reasonable to substitute a nullable type for `TOther` there, and they should be annotated as `class?` because of it.

**Comment by eiriktsarpalis** [comment]
Tagging @stephentoub, @buyaa-n, @krwq.

I think this is a reasonable change. Should we prioritize this ahead of the .NET 5.0 release?

**Comment by stephentoub** [comment]
> Should we prioritize this ahead of the .NET 5.0 release?

Yes
