### ISSUE TITLE
.NET BCL error: System.Runtime.DateTime debug in win7 and win10 have a different.

### ISSUE THREAD

**Issue by fSharpMinor** [dotnet/runtime#39805]
# Issue Title

# General
IDE: vs 2019 preview 16.7.0 preview 4，SDK: .NET 5.0 preview 7 x86，if use win7 os to debug，Datetime DebugDisplay is : 2020/7/21 15:00:00, if use win10 os, DebugDisplay is : 2020/7/21 下午3:00:00，these two different text influenced some APIs(ToLongDateString \ ToShortTimeString...)

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@fSharpMinor this is looks right. VS grab the date format from the user profile settings. It is possible the date format on Windows 7 machine is different than Windows 10 machine. You may try run `intl.cpl` on the 2 machines and then compare the date settings there. You can also customize the dates there the way you like to get what the formatted date as you desired.

I am closing the issue but feel free to respond back with any question we can help with.
