### ISSUE TITLE
Broken parsing of c# file (static delegate?)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#39843]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1120503/broken-parsing-of-c-file-static-delegate.html)._

---
[severity:My work is severely impacted or blocked (internal MSFT only)]
Repro steps
###
1) Open dotnet runtime System.Net.Http solution: https://github.com/dotnet/runtime/tree/master/src/libraries/System.Net.Http
2) Open src\libraries\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs

Symptoms
### 
The file failed to parse and show lot or errors. I'm able to build the solution from command line, so the file should be valid.

VS info
###
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.7.0 Preview 4.0
VisualStudio.16.Preview/16.7.0-pre.4.0+30310.162
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA488
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.523.48425
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.523.48425
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.523.48425
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.523.48425
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-4.20359.1+b90347a69117be7181e2f03a991790634981eddb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.7.20181.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.7.20181.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.7.20181.2
Conda support for Python projects.

Python - Django support   16.7.20181.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.7.20181.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.7.20181.2
Profiling support for Python projects.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.04220
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-4.20359.1+b90347a69117be7181e2f03a991790634981eddb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30309.115
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20329.1+19c9e2f1b21a66ec90fefae79988b33fc16744fc
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

---
#### Feedback Bot on 7/22/2020, 00:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Tarek Mahmoud Sayed [MSFT] solved on 7/22/2020, 09:44 AM, 0 votes: 

<p>Thanks for reporting the issue. We couldn’t report the issue but this may happen if there are some packages not stored when you loaded the solution. Could you please try to build the repo once and then reopen the solution and look if you still seeing this issue? Thanks.</p>

#### mapichov [MSFT] on 7/23/2020, 08:32 AM: 

<p>I'm hitting the same issue, updated VS preview, freshly build repo.</p>

#### Tarek Mahmoud Sayed [MSFT] on 7/23/2020, 09:33 AM: 

<p>did you try to build the repo before loading the solution? and if you compile the solution do you see errors? or it is just the editor showing this issue?</p>

**Comment by tarekgh** [comment]
dup of #39844
