### ISSUE TITLE
[Wasm] Build options to enable AOT in monovm

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#39855]
### Description
The build options to build for WebAssembly AOT are not yet available in the runtime, like they are in mono/mono.

The only option I can find is here:
https://github.com/dotnet/runtime/blob/b613cbe051234c4e55e32d0dcd198fb3e7974567/src/mono/mono.proj#L628

Is this the only option to ensure the interpreter+AOT is enabled?

**Comment by steveisok** [comment]
The AOT parts are pretty well integrated, so closing this issue.
