### ISSUE TITLE
Default activity name to caller member name if not provided

### ISSUE THREAD

**Issue by kzu** [dotnet/runtime#39857]
The improvements up to [part 2](accepted/2020/diagnostics/activity-improvements-2.md) have made things substantially more usable for the Activity API. This is a small proposed improvement to introduce a sensible default activity name.

## ActivitySource.StartActivity

We currently require an activity `name` to be provided as the only required argument in `ActivitySource.StartActivity` overloads. For scenarios where the caller wants to match the activity with the calling method name, providing that as a default value would make calling code less repetitive.

## ***API  Proposal***

```c#
    public Activity? StartActivity([CallerMemberName] string name = "", ActivityKind kind = ActivityKind.Internal)
            => StartActivity(name, kind, default, null, null, null, default);
```

In addition, when the only thing the caller wants to customize is the `ActivityKind`, a new overload would also be useful:

## ***API  Proposal***

```c#
    public Activity? StartActivity(ActivityKind kind, [CallerMemberName] string name = "")
            => StartActivity(name, kind, default, null, null, null, default);
```

Ongoing draft PR in place at https://github.com/dotnet/runtime/pull/39761

**Comment by tarekgh** [comment]
I am seeing this is kind nice to have but wouldn't add much value especially I am not seeing this is main scenario. Providing such overload can cause confusing for the API users too as it switch the parameters with other existing overload. 
Whoever want the proposed scenario can easily create a small wrapper which would be simple and enough. 

```C#
public static Activity? StartActivity(ActivityKind kind, [CallerMemberName] string name = "") => ActivtySource.StartActivity(name, kind);
```

CC @noahfalk

**Comment by kzu** [comment]
Yeah, I'm "solved" this by having an extension method on `ActivitySource` instead, so, closing.
