### ISSUE TITLE
JsonConsoleFormatter: should include formatted string for scopes

### ISSUE THREAD

**Issue by alefranz** [dotnet/runtime#39867]
### Description

From https://github.com/dotnet/runtime/issues/39664#issuecomment-662315321

Currently the new JsonConsoleFormatter does not includes the formatter message for the scopes.
As the formatted message is available for the log entry itself and it is generally available in others structured logging providers.

#### Sample code
```csharp
using (logger.BeginScope("This is a scope message with a {ScopeNumber}", 2))
{
    logger.LogInformation("This is a message with a {Number}", 1);
}
```
#### Current result
```json
{
  "Timestamp": "2020-07-23T21:47:33.7369359\u002B01:00",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "JsonLogging.Program",
  "Message": "This is a message with a 1",
  "Number": "1",
  "{OriginalFormat}": "This is a message with a {Number}",
  "Scopes": {
    "ScopeNumber": "2",
    "{OriginalFormat}": "This is a scope message with a {ScopeNumber}"
  }
}
```
#### Expected result

```json
{
  "Timestamp": "2020-07-23T21:47:33.7369359\u002B01:00",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "JsonLogging.Program",
  "Message": "This is a message with a 1",
  "Number": "1",
  "{OriginalFormat}": "This is a message with a {Number}",
  "Scopes": {
    "ScopeNumber": "2",
    "{OriginalFormat}": "This is a scope message with a {ScopeNumber}",
    "Message": "This is a scope message with a 2"
  }
}
```

Essentially including a property in `Scopes`, maybe called `Message`, with the rendered message.

### Configuration
```<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0-rc.1.20368.6" />```

### Regression?

No, part of a new feature

### Other information

The exact structure would depends on https://github.com/dotnet/runtime/issues/39664 and https://github.com/dotnet/runtime/pull/39860

/cc @maryamariyan

**Comment by maryamariyan** [comment]
Added a commit for this issue in PR: https://github.com/dotnet/runtime/pull/39860/commits/17abe4c9ece50dddaa24a730ec6a8e74186294ca

**Comment by maryamariyan** [comment]
closing, already fixed through https://github.com/dotnet/runtime/pull/39860
