### ISSUE TITLE
JsonConsoleFormatter: number and boolean properties should not be converted to string

### ISSUE THREAD

**Issue by alefranz** [dotnet/runtime#39870]
### Description

Currently the new JsonConsoleFormatter converts all the values of the key/value pairs in both the state and scopes to string.
As json supports numbers and booleans, I think the _built-in value types_ should not be converted to `string`.
Using number would allow to write range queries once ingested on a log analysis system.

/cc @maryamariyan 

#### Sample code
```csharp
logger.LogInformation("This is a message with a {Number}", 1);
```
#### Current result
```json
{
  "Timestamp": "2020-07-23T21:47:33.7369359\u002B01:00",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "JsonLogging.Program",
  "Message": "This is a message with a 1",
  "Number": "1",
  "{OriginalFormat}": "This is a message with a {Number}",
}
```
#### Expected result

```json
{
  "Timestamp": "2020-07-23T21:47:33.7369359\u002B01:00",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "JsonLogging.Program",
  "Message": "This is a message with a 1",
  "Number": 1,
  "{OriginalFormat}": "This is a message with a {Number}",
}
```

### Regression?

No, part of a new feature

**Comment by alefranz** [comment]
@maryamariyan if this change is agreed, I could work on a PR if it helps.

**Comment by maryamariyan** [comment]
> @maryamariyan if this change is agreed, I could work on a PR if it helps.
Sure. @alefranz go for it :)
