### ISSUE TITLE
Rollout T? on unconstrained type parameters

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#39877]
C# 9 just added support for `T?` on unconstrained generic parameters in https://github.com/dotnet/roslyn/pull/45993.  We can use this in dotnet/runtime in two ways:
1. To express better annotations than we currently are due to previously lacking the expressability.
2. To replace some use of [MaybeNull].

We need to do (1) for .NET 5 in order to ensure our annotations are correct, and we should strive to do (2) as well (though I believe we can do (2) later and still have it be compatible; @cston, please correct me if I'm wrong).

I don't expect there to be many places we actually need to change to address (1).  Basically, we should do some searches looking for things like `IEnumerable<SomeGeneric>`, `Task<SomeGeneric>`, `SomeGeneric[]`, etc., where the generic parameter is nested, and annotate cases where the implementation may effectively override what the developer specified such that a null value may be returned even if the developer specified a non-nullable type. An example of (1) is:
https://github.com/dotnet/runtime/blob/90619d5d3577f2aaddf670ee6bf431f393afccaf/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Get.cs#L37
Just as we return `Task<object?>` from the non-generic overload (because the implementation may return null), we need to return `Task<TValue?>` from the generic (because the implementation may return null).

For (2), it should be fairly straightforward: search for places we use `[MaybeNull]` on return values, or `[MaybeNull, AllowNull]` (and all the various permutations of that) on anything, and replace it with `T?`.

cc: @jeffhandley, @buyaa-n

**Comment by danmosemsft** [comment]
We'd need to ingest Roslyn.

**Comment by stephentoub** [comment]
> We'd need to ingest Roslyn

Then we need to ingest Roslyn.

**Comment by danmosemsft** [comment]
Right, I'm just pointing out that it hasn't reached us yet. 😛

**Comment by stephentoub** [comment]
Ah, cool, I thought you were saying that was prohibitive for the release.
