### ISSUE TITLE
jit: check-release diff in some pinvoke call prologs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#39908]
After #39888 there are still around 8 methods in the "test SPMI" collection still show check-release diffs. In release the return address saved in the pinvoke frame has a value that is sometimes too large:

```asm
;; check

164e3ccdd39: 4c 8d 1d 15 00 00 00 	lea	r11, [rip + 21]
164e3ccdd40: 4c 89 9d 10 fc ff ff 	mov	qword ptr [rbp - 1008], r11
164e3ccdd47: 48 89 85 f8 fd ff ff 	mov	qword ptr [rbp - 520], rax
164e3ccdd4e: c6 40 0c 00          	mov	byte ptr [rax + 12], 0
164e3ccdd52: 41 ff d2             	call	r10
164e3ccdd55: 48 8b b5 f8 fd ff ff 	mov	rsi, qword ptr [rbp - 520]

;; release

164e3d095a9: 4c 8d 1d 19 00 00 00 	lea	r11, [rip + 25]                   // should be rip + 21
164e3d095b0: 4c 89 9d 10 fc ff ff 	mov	qword ptr [rbp - 1008], r11
164e3d095b7: 48 89 85 f8 fd ff ff 	mov	qword ptr [rbp - 520], rax
164e3d095be: c6 40 0c 00          	mov	byte ptr [rax + 12], 0
164e3d095c2: 41 ff d2             	call	r10
164e3d095c5: 48 8b b5 f8 fd ff ff 	mov	rsi, qword ptr [rbp - 520]
```
Not sure yet if this impacts correctness.

Likely caused by incorrect accounting of instruction and IG length changes. This has happened before in the pinvoke call prolog; see #8747.

Would be nice to address #9129 so we can avoid introducing these.

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib. If you've never tracked one of these down it is a fun exercise.

**Comment by AndyAyersMS** [comment]
From what I can tell the exact value of the `m_pCallerReturnAddress` field in an `InlinedCallFrame` is not critical, so long as it's within the current method; the only non-logging use I can find in the runtime is to determine if we're in R2R or jitted code. So this issue may not lead to any observable bugs.

@jkotas let me know if I'm off base here.

**Comment by jkotas** [comment]
The exact value is not critical as long as the unwind sequence is the same. The exact value tends to be critical on x86 where the stack frame size (and thus the unwind sequence) varies throughout the method.
