### ISSUE TITLE
Allow JsonConsoleFormatter to write in compact format

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#39917]
## Background and Motivation

For the newly introduced JsonConsole formatter, the logged output for a given log:
```c#
using (logger.BeginScope("{Number}", 2))
using (logger.BeginScope("{AnotherNumber}", 3))
{
    logger.LogInformation("{LogEntryNumber}", 1);
}
```
could look like this:
```
{
  "Timestamp": "15:57:40 ",
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "ConsoleApp46.Program",
  "Message": "1",
  "State": {
    "Message": "1",
    "LogEntryNumber": "1",
    "{OriginalFormat}": "{LogEntryNumber}"
  },
  "Scopes": [
    {
      "Message": "2",
      "Number": "2",
      "{OriginalFormat}": "{Number}"
    },
    {
      "Message": "3",
      "AnotherNumber": "3",
      "{OriginalFormat}": "{AnotherNumber}"
    }
  ]
}
```
For more the formatter to perform more efficiently, it would be good to add a property to JsonConsoleFormatterOptions with a flag called IsCompact, so that once true the above log could look more compact to something like this:

```
{
  "@t": "15:57:40 ",
  "@i": 0,
  "@l": "Information",
  "@c": "ConsoleApp46.Program",
  "@m": "1",
  "@st": {
    "@m": "1",
    "LogEntryNumber": "1",
    "{OriginalFormat}": "{LogEntryNumber}"
  },
  "@sc": [
    {
      "@m": "2",
      "Number": "2",
      "{OriginalFormat}": "{Number}"
    },
    {
      "@m": "3",
      "AnotherNumber": "3",
      "{OriginalFormat}": "{AnotherNumber}"
    }
  ]
}
```

Where:
```
@t: Timestamp
@i: EventId
@l: LogLevel
@c: Category
@m: Message
@st: State
@sc: Scopes
``` 

## Proposed API

```diff
namespace Microsoft.Extensions.Logging.Console
{
     public class JsonConsoleFormatterOptions {
+    public bool IsCompact { get; set; }
      public JsonWriterOptions JsonWriterOptions { get; set; }
     }
```

This could greatly improve the performance and is in line with other third party logging libraries like serilog (inspired by https://github.com/serilog/serilog-formatting-compact).

FYI: conversation initiated here: https://github.com/dotnet/runtime/issues/39664#issuecomment-662770003

**Comment by maryamariyan** [comment]
cc: @shirhatti @davidfowl

**Comment by tarekgh** [comment]
Do we need to have API for that? can't this supported by a config switch? We'll have the desired behavior as default and then any app want to switch back to older format can decide to enable it through the switch.

**Comment by maryamariyan** [comment]
For the config switch there also needs to be a property available in JsonConsoleFormatterOptions. to allow us to flip back and forth, unless we decided that the existing Json formatter should only write compact logs, which in that case we wouldn't need to flip back and forth and this API would not be necessary either.

Note `IsCompact` in the sample appsettings.json file below:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "None",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },

    "Console": {
      "LogLevel": {
        "Default": "Information"
      },
      "FormatterName": "json",
      "FormatterOptions": {
        "JsonWriterOptions": {
          "Indented": true
        },
        "IsCompact": "true",
        "IncludeScopes": true,
        "TimestampFormat": "HH:mm:ss",
        "UseUtcTimestamp": true
      }
    }
  },
  "AllowedHosts": "*"
}
```

I think that is what you meant by config switch right @tarekgh ?

**Comment by tarekgh** [comment]
ignore my comment. I was looking at something else which confused with this one. 

my question now is, does anyone asked for this compact formatting? why we think to get it in 5.0?

**Comment by maryamariyan** [comment]
It would greatly improve the performance.

**Comment by maryamariyan** [comment]
Also in a case like below:

```
using (logger.BeginScope("{Number}", 2))
using (logger.BeginScope("message contains {Message}", 3))
{
    logger.LogInformation("{LogEntryNumber}", 1);
}
```

we would no longer get Json key collision with Message:

IsCompact gives: 

```
{
  "@t": "15:57:40 ",
  "@i": 0,
  "@l": "Information",
  "@c": "ConsoleApp46.Program",
  "@m": "1",
  "@st": {
    "@m": "1",
    "LogEntryNumber": "1",
    "{OriginalFormat}": "{LogEntryNumber}"
  },
  "@sc": [
    {
      "@m": "2",
      "Number": "2",
      "{OriginalFormat}": "{Number}"
    },
    {
      "@m": "message contains 3",
      "Message": "3",
      "{OriginalFormat}": "message contains {Message}"
    }
  ]
}
```

whereas the second scope in the default Json formatter gives:

```
    {
      "Message": "message contains 3",
      "Message": "3",
      "{OriginalFormat}": "message contains {Message}"
    }
  ]
}
```

**Comment by tarekgh** [comment]
Any more details about the perf? I mean, do you think non-compact formatting would be very slow? do we have any goal for the perf in general for the formatters? did we look in optimizing the non-compact formatting?  

It is good in general to consider the perf, but I am afraid jump adding some features for that while users may still need the non-compact and still complaining about perf. let's see what others think about that. personally I am not preferring producing the logs in 2 different way just for the performance. log consumers now need to understand both. in addition the compact logs is not readable to me either. When I see `"@i": 0,` I have no idea what this means.

**Comment by alefranz** [comment]
I second @tarekgh on the importance of the loss of readability.
In my experience the human overheads due to the of the loss of readability outweigh the performance gains, in terms of software maintenance costs. It feels also quite disorientating for new comers, but for that what matters is that we don't make this the default.

The Serilog compact json format is an opinionated take on the performance problem of logging, in my opinion the performance advantage of this approach are fairly minimal while hindering the readability cost and making queries more complex (on top of hard to understand field names you have to deal with escaping the `@` symbol).
When performance matter, I had achieved better success with a good use of log levels to reduce the amount of logging and filtering out the scopes content, cherry picking only some specific properties our of it.

If the goal here is to solve https://github.com/dotnet/runtime/issues/39664 , this solution will only mitigate it as it would still cause a collision in the unlikely event that you use that name as a property e.g. `logger.BeginScope("{@m}", 3)`
I have a couple of alternatives in mind I've proposed in https://github.com/dotnet/runtime/issues/39664#issuecomment-663834064

**Comment by layomia** [comment]
It's been a couple years since we got engagement here + there aren't customer asks. Closing.
