### ISSUE TITLE
"Cannot print exception string because Exception.ToString() failed." should include type

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#39910]
In [this PR](https://github.com/dotnet/runtime/pull/39871#issuecomment-663707844) a missing FSharp.Core.dll produced

```
Unhandled exception.
   Cannot print exception string because Exception.ToString() failed.
```

This can be trivially reproduced by throwing an unhandled exception object whose ToString() returns null (eg) but historically there have been more subtle cases

Although the actual cause may be a bit more complicated. It has come up before when FSharp.Core.dll was missing ([here](https://github.com/dotnet/runtime/issues/6299)) but that was supposed to be fixed by https://github.com/dotnet/coreclr/pull/3858.

As with any exception, an easy repro may not be available. If callstack is impossible, it would still be helpful if the runtime attempted to log the exception type (with appropriate catch block around that too)

https://github.com/dotnet/runtime/blob/c87e75e8ef260ccc6e979f9df1cc012536ee036f/src/coreclr/src/vm/excep.cpp#L5378

**Comment by danmosemsft** [comment]
Here's a repro, it's clearly not particularly interesting to replace FSharp.Core.dll with garbage, but perhaps more realistic repros go via the same path:
```
C:\proj\fs2>dotnet new console -lang f#
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\proj\fs2\fs2.fsproj...
  Determining projects to restore...
  Restored C:\proj\fs2\fs2.fsproj (in 152 ms).
Restore succeeded.


C:\proj\fs2>dotnet publish --self-contained -r win-x64
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\proj\fs2\fs2.fsproj (in 186 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  fs2 -> C:\proj\fs2\bin\Debug\net5.0\win-x64\fs2.dll
  fs2 -> C:\proj\fs2\bin\Debug\net5.0\win-x64\publish\

C:\proj\fs2>echo foo > C:\proj\fs\bin\Debug\net5.0\win-x64\publish\FSharp.Core.dll

C:\proj\fs2>C:\proj\fs\bin\Debug\net5.0\win-x64\publish\ConsoleApp3.exe
Unhandled exception.
   Cannot print exception string because Exception.ToString() failed.

```
In this case I would expect a stack, but even an exception type would be nice.

**Comment by am11** [comment]
I tried the repro steps on Windows and macOS with net5. I think `ConsoleApp3.exe` is actually `fs2.exe`?
Nonetheless, on Windows I receive the same error as yours, but on macOS, it gives a proper error:

```sh
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Abort trap: 6
```

On Windows, I used `5.0.0-preview.7.20366.15` (from dotnet/installer's readme list); and on macOS `5.0.0-preview.8.20361.2` (which dotnet/runtime repo is currently using).

**Comment by danmosemsft** [comment]
Cc @janvoJan who made earlier fix above.

There may be two fixes here ideally : in this case maybe it shoukd simply work as normal, and a "backup plan" that adds the type even if ToString() fails for some other reason.

**Comment by danmosemsft** [comment]
BTW, I didn't intend to suggest this was required for 5.0.

**Comment by davidwrighton** [comment]
This no longer reproduces.
