### ISSUE TITLE
.NET 5 Preview 7 Queue can not add value when debug step by step

### ISSUE THREAD

**Issue by SinxHe** [dotnet/runtime#39918]
### description

i have a simple code with xunit, when i just run the test or when i debug test without step by step breakpoint. it passed.
but when i make a breakpoint before `_buffer.Enqueue(node?.val);` and after. i can see `_buffer` not add any element(must view the value, if not, the test will past). by the way, `_queue` can always add element sucessful.

![image](https://user-images.githubusercontent.com/9050899/88446938-d1303080-ce60-11ea-8448-5e89c9b9f22b.png)

### environment

1. linqpad v6.10.1 and .net sdk 5 preview 5 `step by step debug not pass`
2. linqpad v6.10.1 and .net sdk 5 preview 7 `step by step debug not pass`
3. rider 2020.1.4 and .net sdk 5 preview 5 `step by step debug not pass`
4. rider 2020.1.4 and .net sdk 5 preview 7 `step by step debug not pass`
5. visual studio 16.7.0 preview 3.1 and .net sdk 5 preview 7 `step by step debug not pass`

### code

[project code is here](https://github.com/SinxHe/leet-code/blob/master/editor/data-struct/TreeNode.cs)
![image](https://user-images.githubusercontent.com/9050899/88447013-98448b80-ce61-11ea-9729-afa75f25573b.png)
![image](https://user-images.githubusercontent.com/9050899/88447037-c0cc8580-ce61-11ea-94ba-824045789728.png)

```csharp
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Xunit;

// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global

public class TreeNode : IEnumerable<int?>
{
	public int val { get; }
	public TreeNode left { get; set; }
	public TreeNode right { get; set; }

	public TreeNode(int val)
	{
		this.val = val;
	}

	private TreeNode(IEnumerable<int?> nums)
	{
		throw new System.NotImplementedException();
	}

	public IEnumerator<int?> GetEnumerator()
	{
		return new TreeNodeEnumerator(this);
	}

	IEnumerator IEnumerable.GetEnumerator()
	{
		return GetEnumerator();
	}

	private class TreeNodeEnumerator : IEnumerator<int?>
	{
		private readonly Queue<TreeNode> _queue = new Queue<TreeNode>();
		private readonly Queue<int?> _buffer = new Queue<int?>();
		public int? Current => _buffer.Dequeue();

		object IEnumerator.Current => Current;

		public TreeNodeEnumerator(TreeNode node)
		{
			_queue.Enqueue(node);
		}

		public bool MoveNext()
		{
			if (_buffer.Any())
			{
				return true;
			}
			if (_queue.Any())
			{
				while (_queue.Any() && (!_buffer.Any() || _buffer.Any() && _buffer.Last() == null))
				{
					var node = _queue.Dequeue();
					_buffer.Enqueue(node?.val);
					if (node != null)
					{
						_queue.Enqueue(node.left);
						_queue.Enqueue(node.right);						
					}
				}
				if (_buffer.LastOrDefault() != null)
				{
					return true;
				}
			}
			return false;
		}

		public void Dispose()
		{
		}

		public void Reset()
		{
			throw new System.NotImplementedException();
		}
	}

	public class TreeNodeTests
	{
		[Fact]
		public void GetEnumerator()
		{
			var node = new TreeNode(1);
			Assert.Equal(new int?[] {1}, node);
			node = new TreeNode(0)
			{
				right = new TreeNode(2)
			};
			Assert.Equal(new int?[] {0, null, 2}, node);
		}
	}
}
```

**Comment by hoyosjs** [comment]
Will try to take a look today

**Comment by hoyosjs** [comment]
@SinxHe this is expected behavior. See the last line of [IEnumerator.Current's remarks](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current?view=netcore-3.1#remarks). You implementation of `Current` dequeues the item. The local view in the debuggers see a property and run the `get` accessor to display a value to you. This ends up having you queuing the item when you step through the code, and then the property view tries to refresh once it pauses after the step/breakpoint and dequeues the item (potentially twice, once for the property on the class and once for `IEnumerator.Current`).
