### ISSUE TITLE
Support for Argon2, BCrypt

### ISSUE THREAD

**Issue by MythreyaK** [dotnet/runtime#39922]
ASP.Net core supports  PBKDF2. Support for Argon2, BCrypt as first-party implementations would be nice. 

There are nuget packages, but not sure if they're '_cryptographically verified_' for production scenarios. The common suggestion seems to be "[don't use 3-rd party packages, unless they're verified to be secure](https://stackoverflow.com/a/6228051)".

**Comment by vcsjones** [comment]
Argon2 request is a dupe of #19933, bcrypt request could probably dupe under #15936.

**Comment by bartonjs** [comment]
I agree with the duplicate assessments, these requests are already tracked.

**Comment by MythreyaK** [comment]
Yikes sorry, should've used better keywords for dupe-search. 
CoreFX seems to redirect back to this repo.
