### ISSUE TITLE
Memory leak by System.Net.NetworkInformation.Ping

### ISSUE THREAD

**Issue by iDreamCXK** [dotnet/runtime#39926]
.Net core version : 3.1.201
OS : Linux

codes :
```c#
using System.Net.NetworkInformation;
private Ping ping = new Ping();
private bool Ping()
{
            PingReply pingReply = ping.Send(ipAddr.ToString(), 1000);
            return pingReply.Status == IPStatus.Success;
}
```
------------------------------------------------------------------------
The codes above running well on Windows , but memory leak on Linux . 
And I have found an article that said it was solved in .Net framework 4 ,but occure now
https://docs.microsoft.com/zh-cn/troubleshoot/dotnet/framework/access-violation-call-ping-send-repeatedly

**Comment by danmosemsft** [comment]
@iDreamCXK can you please try [.NET 5.0 Preview 7? ](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-7/)

Does it repro there?

**Comment by karelz** [comment]
@iDreamCXK how do you measure / recognize memory leak? Does it eventually throw OutOfMemoryException?
Are you sure it isn't just GC not releasing memory as there is no need?

How many iterations do you have to do before the symptoms manifest themselves?

**Comment by iDreamCXK** [comment]
Well，the memory grows slowly and never decreased.When I comment out the codes , the memory no longer grows.

**Comment by iDreamCXK** [comment]
> @iDreamCXK can you please try [.NET 5.0 Preview 7? ](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-7/)
> 
> Does it repro there?

I only test it on .net core 3.1.   My parter said that's ok on Windows,  but the memory grows slowly on Linux，It may take one day or two to see it more obviously.

**Comment by danmosemsft** [comment]
It might help narrow down the problem if you can try on 5.0 for us.

**Comment by karelz** [comment]
Also, "memory grows" does not yet mean a memory leak - it could be just GC not triggering finalized or not collecting memory.
I would try to force GC, or even better, use memory profiler analysis to identify, if there is a leak and where - eg PerfView can do nice snapshots of memory on Windows and I bet it will have similar capabilities on Linux ...

**Comment by iDreamCXK** [comment]
I verify this problem by writing a demo. The result shows  that it works fine on .Net 5 Preview 7 ,while the memory grows slowly on .Net 3.1 , although I force garbage collection.

![Ping内存泄漏](https://user-images.githubusercontent.com/46046441/88509526-d7b2d980-d013-11ea-8d43-f4bb566d9a5c.png)

The code is below :

`using System;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using System.Threading;
using System.Threading.Tasks;

namespace PingMemoryLeakTest
{
    class Program
    {
        static void Main(string[] args)
        {
            List<Task> tasks = new List<Task>();
            for(int i = 0; i < 50; i++)
            {
               Task t = Task.Factory.StartNew(() => { PingTest(); }, TaskCreationOptions.LongRunning);
               tasks.Add(t);
            }

            new Thread(() =>
            {
                GC.Collect();
                Thread.Sleep(5000);
            });

            Task.WaitAll(tasks.ToArray());
        }

        private static bool PingTest()
        {
            Ping ping = new Ping();
            while (true)
            {

                PingReply pingReply = ping.Send(**"IP Address"**, 1000);
                bool result =pingReply.Status == IPStatus.Success;
                GC.Collect();
                Thread.Sleep(100);
            }

        }
    }
}`

**Comment by karelz** [comment]
Thanks for confirmation @iDreamCXK. As it seems to be addressed in .NET 5, is it an option for you to migrate to .NET 5?

**Comment by karelz** [comment]
Closing as addressed in .NET 5.
We can keep discussing how to unblock the situation on 3.1 -- e.g. by migration to 5.0.
