### ISSUE TITLE
Publish valid NETStandard.xml for NetStandard.Library 2.0.3

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/runtime#39938]
The latest NuGet package for https://www.nuget.org/packages/NETStandard.Library/2.0.3 contains NetStandard.xml which is invalid XML:
https://github.com/dotnet/runtime/issues/24631
https://github.com/dotnet/standard/issues/666

The issue that caused invalid XML to be generated has since been fixed, but we haven't published an updated NetStandard 2.0 XML file anywhere that I can find. Starting with 2.1 this no longer seems to be a problem, but if you're using NETStandard 2.0 the XML file is still broken.

I've found that this 2.1.0 package for example has the valid XML: https://dotnet.myget.org/feed/dotnet-core/package/nuget/NETStandard.Library/2.1.0-prerelease.18572.1
However the concern is that it doesn't exactly match the API set that is in 2.0.3.

I'm not sure what's the best way to do this, but we should either publish 2.0.4 with the fixed XML or at least publish the XML file separately somewhere that matches https://www.nuget.org/packages/NETStandard.Library/2.0.3

**Comment by KirillOsenkov** [comment]
It appears that we already have an issue for this: https://github.com/dotnet/standard/issues/1527

**Comment by KirillOsenkov** [comment]
@Anipik

**Comment by ViktorHofer** [comment]
Closing as dup of https://github.com/dotnet/standard/issues/1527.
