### ISSUE TITLE
Interop with C++: Is it possible?

### ISSUE THREAD

**Issue by fsinisi90** [dotnet/runtime#39945]
I want to embed .NET Core in my C++ application (host) and be able to P/Invoke methods from C# directly like Mono allows doing.

For example, with Mono I can write this:

```
[DllImport("__Internal", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN9CSharpAPI11SetVariableEPKcS1_")]
```

And because I'm using `"__Internal"` it will find the symbol in the main assembly.

Is there a way to accomplish that with .NET Core?

**Comment by am11** [comment]
Related https://github.com/dotnet/runtime/issues/7267

**Comment by AaronRobinsonMSFT** [comment]
@fsinisi90 Specifying the actual process binary isn't supported using any of the current APIs (e.g. `NativeLibrary` or `DllImport`) in CoreCLR. Neither accept `__Internal` nor do they allow passing `null` to the underlying `LoadLibrary`/`dlopen` function being used.

Alternatively one could P/Invoke to `LoadLibrary`/`dlopen`, pass the `null`, and then use `GetProcAddress`/`dlsym` to access the desired export. I realize this is a rather poor experience. In this case the solution is for CoreCLR is to support something similar to `__Internal`. What that means exactly is something we should discuss at #7267.

For consuming a C++ export from the non-process binary this will work like any other `DllImport` scenario so I am going to close this issue. Let's continue the conversation about support for `__Internal` in #7267.

**Comment by fsinisi90** [comment]
@AaronRobinsonMSFT Thanks for the workaround. I've been able to make it work on macOS in the way you've proposed but I'm having problems on Windows. When trying to P/Invoke to `LoadLibrary(null)` I'm getting a null pointer and the error code 87.

Here's the code:

```
[DllImport("kernel32.dll", SetLastError=true)]
public static extern IntPtr LoadLibrary(string fileName);

public static IntPtr OnResolveDllImport(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
{
    if (libraryName == "__Internal")
    {
        IntPtr dllHandle = LoadLibrary(null);

        if (dllHandle == IntPtr.Zero)
        {
            Console.WriteLine(Marshal.GetLastWin32Error()); // prints 87
        }
        else
        {
            return dllHandle;
        }
    }

    return IntPtr.Zero;
}

static Lib()
{
    NativeLibrary.SetDllImportResolver(Assembly.GetAssembly(typeof(Hy.TestAPI)), OnResolveDllImport);
}
```

**Comment by AaronRobinsonMSFT** [comment]
@fsinisi90 Sorry about that. I always mess this up when not actually in the process of writing code. On Windows, the function to get the process handle is `GetModuleHandle()` - that is what should be passed `NULL`.

I am also updating the original workaround.

**Comment by fsinisi90** [comment]
That was fast! Thank you. It seems to work, now I'm getting `System.EntryPointNotFoundException` (even after checking the symbols with dumpbin) but I guess that's a completely different story...

**Comment by tritao** [comment]
On .NET Core, the symbol lookup call eventually ends up in https://github.com/dotnet/runtime/blob/b2c7585ba82a2248e7d0afb956c3f17cfbb6d6e7/src/coreclr/src/vm/dllimport.cpp#L5939.

```
    INT_PTR address = reinterpret_cast<INT_PTR>(GetProcAddress((HMODULE)handle, lpstr));
```

You could try to put a breakpoint here and check it out. Or just try to create a native sample that does the same and confirm the issue.

**Comment by fsinisi90** [comment]
The problem was that I had to add the attribute `__declspec(dllexport)` to expose the methods on Windows.
