### ISSUE TITLE
API proposal: IsEmpty property for System.Guid

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#39956]
## Background and Motivation

Add `IsEmpty` property to `System.Guid` for convenience.

<https://stackoverflow.com/questions/9837602/why-isnt-there-a-guid-isnullorempty-method/9837628>

## Proposed API

```diff
namespace System
{
    public struct Guid : IComparable, IComparable<Guid>, IEquatable<Guid>, IFormattable
+        public bool IsEmpty => this == Guid.Empty;
```

## Usage Examples

``` C#
Assert(!guid.IsEmpty);
```

**Comment by GrabYourPitchforks** [comment]
@xtqqczze Can you expand on the motivation for this? The StackOverflow question doesn't really give much context so it's difficult to tease out what problem this is intended to solve.

**Comment by xtqqczze** [comment]
@GrabYourPitchforks This proposal is purely for developer convenience, `guid.IsEmpty` is less code then `guid == Guid.Empty`. `IsEmpty` would also be listed in IntelliSense. This will reduce the chance of a developer writing something bad like `guid == null` (for example see https://github.com/PowerShell/PowerShell/pull/13285/files).

**Comment by stephentoub** [comment]
Thanks. I'm not sure why Guid is special here. I don't want us adding IsEmpty properties to every value type, and I don't see why Guid deserves special treatment here over other value types. `== default` works fine.

**Comment by xtqqczze** [comment]
@stephentoub I agree there is no reason for this to be `Guid` specific. Is there a case for `IsEmpty` property on types with `public static T Empty` field (this is likely a high number)?

**Comment by stephentoub** [comment]
> Is there a case for IsEmpty property on types with public static T Empty field (this is likely a high number)?

Personally I don't think it's worth it.

**Comment by xtqqczze** [comment]
@stephentoub OK in that case I shall close this issue.
