### ISSUE TITLE
Test failure: DataContractSerializerTests.DCS_DecimalAsRoot

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39951]
failed in job: [runtime-coreclr libraries-jitstress2-jitstressregs 20200725.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=745730&view=ms.vss-test-web.build-test-results-tab&runId=23109872&resultId=127010&paneView=debug)

Error message
~~~
Assert.Equal() Failure
Expected: 0
Actual:   79228162514264337593543950335


Stack trace
   at DataContractSerializerTests.DCS_DecimalAsRoot() in /_/src/libraries/System.Runtime.Serialization.Xml/tests/DataContractSerializer.cs:line 117
~~~

**Comment by BruceForstall** [comment]
This was `net5.0-Linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs1`

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS, please look into this issue.

cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
This passed in the most recent run:

https://dev.azure.com/dnceng/public/_build/results?buildId=793494&view=results
