### ISSUE TITLE
Configuration.Save() does write changes to appsettings

### ISSUE THREAD

**Issue by Ahoerstemeier** [dotnet/runtime#39967]
### Description

The following little code sniplet writes an empty app.config 
`            var config = ConfigurationManager.OpenMappedExeConfiguration(configMap, ConfigurationUserLevel.None);
            config.AppSettings.Settings.Add("YourKey", "YourValue");
            config.Save(ConfigurationSaveMode.Full);
`
In 4.7.2 it did write the old app.config plus the new key. 

### Configuration

x64, Windows, .NET3.1

### Regression?

Worked on 4.7.2.

### Other information

It seems like the change in the appsettings is no longer recorded in the configuration anymore, as the save does exactly what it should when there really were no changes.

**Comment by ericstj** [comment]
Confirmed this.  Here's a full repro: 
[Program.zip](https://github.com/dotnet/runtime/files/4991047/Program.zip)

On .NETFramework it writes 
```xml
<configuration>
    <appSettings file="">
        <clear />
        <add key="A" value="1" />
        <add key="B" value="2" />
        <add key="C" value="3" />
    </appSettings>
</configuration>
```

On .NETCore it writes
```
<configuration>
    <appSettings file="">
        <clear />
        <add key="" value="" />
    </appSettings>
</configuration>
```

This doesn't appear to be a regression as it's been present since past releases.
