### ISSUE TITLE
Introduce Math/F.ReciprocalEstimate and Math/F.ReciprocalSqrtEstimate

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#39971]
## Background and Motivation

This would expose methods in `Math`/`MathF` which provide a method to calculate estimations for the reciprocal (`1 / x`), reciprocal square root (`1 / sqrt(x)`) and square root of a method. These are estimations, and are faster than their equivalent "exact" IEEE counterparts but are not necessarily deterministic on all systems.

These methods prove very useful in 3D graphics where you need to do these operations a lot and very fast, but exact accuracy is not key. On x64, they would map to `rcp` for `Reciprocal` and `rsqrt` for `ReciprocalSquareRoot`

## Proposed API

```diff
namespace System
{
    public static class Math
    {
+        public double ReciprocalEstimate(double x);
+        public double SqrtEstimate(double x);
+        public double ReciprocalSqrtEstimate(double x);
    }

    public static class MathF
    {
+        public float ReciprocalEstimate(float x);
+        public float SqrtEstimate(float x);
+        public float ReciprocalSqrtEstimate(float x);
    }
}
```
## Alternative Designs

`Approx` could be used instead of `Estimate`

## Outstanding Questions

Should similar methods be exposed on the various vector types?

**Comment by tannergooding** [comment]
@john-h-k, could you elaborate on the behavior on hardware that doesn't support a reciprocal estimate or what the allowed error would be?

**Comment by terrajobst** [comment]
* Makes sense

```C#
namespace System
{
    public static class Math
    {
        public double ReciprocalEstimate(double x);
        public double SqrtEstimate(double x);
        public double ReciprocalSqrtEstimate(double x);
    }

    public static class MathF
    {
        public float ReciprocalEstimate(float x);
        public float SqrtEstimate(float x);
        public float ReciprocalSqrtEstimate(float x);
    }
}
```

**Comment by Joe4evr** [comment]
@terrajobst The signatures should probably be marked as `static` for the sake of consistency/correctness.

**Comment by tannergooding** [comment]
They will be in the implementation and are required to due to Math/MathF being `static` themselves.
