### ISSUE TITLE
Use HTTP/2 by default when version is 2.0 and not using TLS

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#39980]
In .NET Core 3.1 a request with `HttpRequestMessage.Version` set to 2.0 will use HTTP/1.1 if TLS is not used. An AppContext switch is required to opt-in to use HTTP/2+cleartext

This situation is improving in .NET 5 with version selection - https://github.com/dotnet/runtime/issues/987

Has allowing HTTP/2+H2C by default been considered? Browsers require TLS with HTTP/2, but for apps making API calls I think there are valid use cases for HTTP/2+H2C. For example, TLS was terminated by a proxy, you're an app inside a cluster, and you want to use HTTP/2.

Happy for this to be closed if there are good reasons to fallback to HTTP/1.1 by default.

**Comment by scalablecory** [comment]
It's reasonable to explore if we can implement reliable version detection (i.e. look for an HTTP/1 response to the connection prefix) and allow it to (based on the user's version policy) fall back to HTTP/1.

Technically we should be using H2C upgrade if we get a http:// URI and aren't sure if the remote server supports HTTP/2. I'm not sure how many servers support this though.

**Comment by JamesNK** [comment]
I don't think anyone uses the H2C upgrade header. Kestrel doesn't, and I don't know of other servers that do. Everyone either uses ALPN, or prenegotiates H2C.

With `http` + `RequestMessage.Version = 2.0` + `HttpVersionPolicy.RequestVersionOrHigher` then HttpClient will use prenegotiated h2c, but I was wondering why it makes sense for `HttpVersionPolicy.RequestVersionOrLower` (the default value) to fallback to HTTP/1.1.

**Comment by stephentoub** [comment]
It would be a very visible breaking change. Someone previously could set the default version to 2.0 and 2.0 would be used if available; it wouldn't be available if http were used, falling back to 1.1. This change would instead result in failures rather than fallback when the server didn't speak prenegotiated h2c.

**Comment by JamesNK** [comment]
I thought that might be the case.

Since HttpVersionPolicy solves my scenario well I'll close this.
