### ISSUE TITLE
mscorlib.dll is outdated in the comment.

### ISSUE THREAD

**Issue by symphony2014** [dotnet/runtime#39986]
### Description
The keyword **"mscorlib.dll"** is outdated, should be replaced by **"System.Private.CoreLib.dll"**.
https://github.com/dotnet/runtime/blob/2ad46cdeca74a2c3f451cfe31c19ee9ada0edd41/src/coreclr/src/vm/binder.cpp#L62

**Comment by danmosemsft** [comment]
Well, "Mscorlib" is all over this file.
