### ISSUE TITLE
Use FileOptions.SequentialScan in File.ReadAllBytes

### ISSUE THREAD

**Issue by mcpiroman** [dotnet/runtime#40001]
`System.IO.File.ReadAllBytesAsync` already uses `FileOptions.SequentialScan` flag when opening a file,  but `System.IO.File.Read` does not:
https://github.com/dotnet/runtime/blob/52d4d8c057d24a77b2cf6708d495cf549a8bee9a/src/libraries/System.IO.FileSystem/src/System/IO/File.cs#L331

Furthermore, this could be added in `ReadAllText` and alike, but it would need to be routed through `StreamReader` and that would probably require public API changes.

**Comment by QueenCitySmitty** [comment]
@jkotas Hey is it cool if I pick this up, it doesn't sound like it would be too much work. Pretty new to the .NET Runtime repo though, does this seem like an 'Easy' labeled item, or is the work more substantial than I'm thinking.

**Comment by jkotas** [comment]
Yep, this one should be pretty easy
