### ISSUE TITLE
JIT poor codegen for calculating field offsets of structs

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#40021]
### Description

The JIT doesn't generate good assembly when calculating (what should be) constant fields offsets.
[Example sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgJgIwCwAUFgAwAEWeAdAEoCuAdjAJZhzUDCA9mAA4sANogDKiAG4sAxnCgBuYsQDaYbgBN6wkOREBrFnwAy3KREFQAkoxYwAuopIBmckygQAZnEo5yncgG9icmDyIJCsZ1gEeikYcgBRAA8IfmEw4MCiEOzKZ2AAT3hyAC1EbgUsnOD0nL4EFnEIIoKigH08JHJWnE7Wxwqq6sqqiPIWrwAxbnoEAZCAXxqa0ZZmcgB5d3coOBgAQSgAOU1BAAoAShrMwYTk1LgAKnI+cgBeckYTuZGAdnJT1Ywc6nABkfAAtAA+KYzcjg8hgqGlBDcc7fciLYahLErNYAVUYbk8m22uwOx0EZ0uWOugwQcHctxSfGEzze5HpjIJRI4B1oDIAPElmcJIadPpS0TVslg/gDmOduR4OAAhQpwEk7GCnTnPajI7idXV8agwhBSrGY7JLHHOQEbLZa8ncGAUwQAdRsAAtjKYqVdpSFhfdyIITGZ0dlgyzHmz3iCw37I+E5YDgYjodMEHCERDIQaLdkrSEbdbbeR7ZqyUcXW7TtHhE8+NTsrTfv806C82acxmC+ji0MZXb8YTlVX9jXXScdQymSHmwGsTLUwqlZ5qGr4BPZ4yTQajXOTWbCwtiJjiIwUrI+BAZJQaAxmGwODx+EJRBJpLJiG3yAB6QDyAFKB6DASAEHySEakA/9yDxHY1HIGBuArRg1GkJovBQ5CvS8KReAEYRsxgL0mlwrwBSkSFqETMwoDQmwBX/aiYKA9xBAgABzcgoC9aZBCQxgXTGLwtTQ8h2FI9RyDwiA1EQKBqDYuDmNA8CIEg6CsVg4D6Qg3QoG07JdIAFS9FgGKaGB6mAegikslwx08UTTHoHYKziSB8g5OBxDgMwnNWGwWDMFgAC84CQ9hVEg5DuBUijyAgPgWUw1huEYCSZAQGAIFWNDYAgRgZAY04OC46hD3k1YePcFEwCC6xWDCyK1ESoqpF0MxEwAcmiuBYvyc5qHICxGRStKovi5LJN2fikIw+lYkEfJOlIrxrNs+y4ESybBBYWQZtI8ipIW5L0OSykPlkeAkPcJhYhYTKys4sBgDUaBOjowREoekqMsJc5RLDAB3TzRvG5LUoO6acIgZD8j4LxuGzVQNGETobGhqaGPhylErO9QGMYW7ptWKAWAU0bzMcraWDshyGMBOBn0ynqfOEuJkYQMAbDu8hMr2qAdne2GlPgjzyI2yT1E0LxhH8wRCvgeSZv2nycLATRWBjRHkcShSpE4hAmmewllJ0oDmP0zTDOMkIlD2GAbIZnaEO4uBTmd13GbgUzNK43YlIAWTltJlxCDByB97b4ADhAg5gJTOE4kXA2CaPY7d+PA+D6gRBsmIYAz8gs5duP/bz5PqCseAEHcO9dsjzOY4rnOq8T/OeEJIvYlR0vy99naE6T0P5vUQe2+H3Ou5rgAFFEeZgfIp+zv3R/z+J/OYTorDw+oBfeRvzDgc57HLHYzGm3AdH0Ixw3MKwbHXnbyG0V/4CXG5Rj0AxfXos/fY7c/YXFLn+IsNRMTzCAA=)

### Configuration

.NET 5, master branch on sharplab and I repro'd it locally with what i believe is a reasonably up to date copy of the runtime (i don't think it is more than a week old)

### Analysis

I'm aware the JIT has to throw for null in the first null case, but they show it has the ability to resolve it to a constant (it emits it as a constant load of `4` there, although right after throwing an NRE). It doesn't seem to succeed doing this with either a local (even when `SkipLocalsInit` is enabled) or just with a pointer (where I would expect identical codegen to the null case, except comparing the pointer for `null` rather than immediately NREing). 

```cs
[module: SkipLocalsInit]

public struct Example
{
    public byte Zero;

    private byte _1, _2, _3;

    public byte Four;
}

// good codegen :)! ... but instant null ref ex
public int OffsetAsNull()
{
    Example* p = null;
    return (int)(&p->Four - &p->Zero);
}

// bad codegen
public int OffsetAsNotNullWithLocal()
{
    Example local;
    Example* p = &local;
    return (int)(&p->Four - &p->Zero);
}

// bad codegen
public int OffsetAsNotNullWithParam(Example* p)
{
    return (int)(&p->Four - &p->Zero);
}
```

generates

```asm
C.OffsetAsNull()
    L0000: xor eax, eax
    L0002: cmp [eax], eax ; NRE
    L0004: mov eax, 4 ; constant offset load
    L0009: ret

C.OffsetAsNotNullWithLocal()
    L0000: sub esp, 8
    L0003: lea eax, [esp]
    L0006: cmp [eax], eax
    L0008: lea edx, [eax+4]
    L000b: sub edx, eax
    L000d: mov eax, edx
    L000f: add esp, 8
    L0012: ret

C.OffsetAsNotNullWithParam(Example*)
    L0000: cmp [edx], edx
    L0002: lea eax, [edx+4]  
    L0005: sub eax, edx ; it sets eax to edx + 4, then subs, but doesn't fold that to a constant?
    L0007: ret
```

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium
impact:small

**Comment by EgorBo** [comment]
> .NET 5, master branch on sharplab

Yeah it's quite confusing, but "master" on sharplab means "master version of Roslyn + .NET Core 3.1 x86 JIT"
It confuses so many people so many times so we should ask sharplab authors to make it clearer 🙂 

I'd recommend to either use BenchmarkDotNet's disasm + .NET 5 or use `COMPlus_JitDisasm=method` (preferable)

**Comment by john-h-k** [comment]
> I repro'd it locally with what i believe is a reasonably up to date copy of the runtime (i don't think it is more than a week old)

I did check it with my local copy of the runtime too 😄 , just can't do it on a freshly pulled copy right now because I am having some issues building it

**Comment by AndyAyersMS** [comment]
@john-h-k thanks. Is this representative of something you've run into somewhere, or just something you happened to notice?

Marking this as future as we're battening down the hatches for 5.0.

**Comment by john-h-k** [comment]
no problem :smile:. Ran into it in a marshalling scenario where I have to relatively frequently offset some pointers based off of a field offset

**Comment by AndyAyersMS** [comment]
Actually marking as future.

**Comment by MichalStrehovsky** [comment]
I ran into pretty much the same thing in #9791 - we can probably merge these issues because they look similar.

The workaround with null is nice. I'll probably use that.

**Comment by john-h-k** [comment]
While implementing the `no. nullcheck` prefix for `ldfld`, i realised if it supported `ldflda` then this would allow this to work. ECMA doesn't say `no. nullcheck ldflda` is valid for some reason (i really am not sure why), but when i allowed it, I got the perfect constant folded codegen 🎉 

```asm
G_M11044_IG01:
                                                ;; bbWeight=1    PerfScore 0.00
G_M11044_IG02:
       B804000000           mov      eax, 4
                                                ;; bbWeight=1    PerfScore 0.25
G_M11044_IG03:
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.00```

**Comment by BruceForstall** [comment]
`C.OffsetAsNotNullWithLocal()` could lose the extra `mov` with slightly better register allocation.

Both `C.OffsetAsNotNullWithLocal()` and `C.OffsetAsNotNullWithParam()` look the same to the JIT after morph:
```
*  RETURN    int
\--*  CAST      int <- long
   \--*  SUB       long
      +--*  COMMA     long
      |  +--*  NULLCHECK byte
      |  |  \--*  LCL_VAR   long   V01 arg1
      |  \--*  ADD       long
      |     +--*  LCL_VAR   long   V01 arg1
      |     \--*  CNS_INT   long   4 field offset Fseq[Four]
      \--*  LCL_VAR   long   V01 arg1          Zero Fseq[Zero]
```
Presumably this pattern could be recognized and folded if it's common enough to warrant. The `NULLCHECK` node slightly complicates it. The JIT assumes that if you're creating a byref (or native pointer) that it will be dereferenced, so it conservatively creates the null check. Here, presumably we don't need the null checks.
