### ISSUE TITLE
UserSecrets should reload on changed

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#40020]
Today the host will reload appsettings.json if it changes.
https://github.com/dotnet/runtime/blob/4b8c5fe2b4757f77f5699d49a072fcb123d2e33b/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L74-L77

However, it does not reload the user secrets file.
https://github.com/dotnet/runtime/blob/4b8c5fe2b4757f77f5699d49a072fcb123d2e33b/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L84
See
https://github.com/dotnet/runtime/blob/4b8c5fe2b4757f77f5699d49a072fcb123d2e33b/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L119

These are similar resources and should have similar functionality.

**Comment by Marusyk** [comment]
I'll try to prepare PR for this. Please assign it to me

**Comment by eerhardt** [comment]
Unassigning since the linked PR was closed. @Marusyk - let us know if you are still interested in working on this.
