### ISSUE TITLE
Add concurrency data structures for TPL

### ISSUE THREAD

**Issue by chriskuech** [dotnet/runtime#40029]
### Is your feature request related to a problem? Please describe.
A reoccurring problem I see with ASP.NET Core web services is caching data from an API.  Currently this manifests in two primary scenarios:
1. Lazily caching a single request on a field.
2. Lazily caching many requests by a key in a ConcurrentDictionary.

Both of these scenarios have suboptimal solutions.  `System.Lazy` does not support async value factory functions and `async`/`await` does not work in a `lock`, so mitigation requires mixing semaphores boilerplate with TPL.  `System.Concurrency` classes don't support async value factory methods, which results in caching `Task`s and messy error handling and cache management code around the stored `Task`s.

### Describe the solution you'd like
Support async value factory function parameters in `System.Concurrency` and `System.Lazy`, so that API calls can be made in factory functions and only the result is cached, rather than caching the whole `Task`.

**Comment by chriskuech** [comment]
@javiercn , thanks for the quick triage.  We do currently store Tasks as you describe, but this leads to some messy error handling code to avoid caching errors and to avoid the appearance of multiple erroring requests instead of one.  I will see if memcache can solve the second scenario.

**Comment by stephentoub** [comment]
Is there a concrete proposal here for new APIs?  Seems like the scenarios are already achievable via other means.  If that's the case, we can just close this.  Thanks.
