### ISSUE TITLE
Unable to build library test project in Visual Studio

### ISSUE THREAD

**Issue by alefranz** [dotnet/runtime#40039]
### Description

Hello 👋! 

I'm trying to work on `Microsoft.Extensions.Logging.Console` in Visual Studio _Preview_.

I can build and run the tests successfully from the command line, but when I open the library project in VS with
```.\build.cmd -vs  Microsoft.Extensions.Logging.Console```
I am unable to build the test projects due to the following error:
```
2>------ Build started: Project: Microsoft.Extensions.Logging.Console.Tests, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4469,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "_GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences".
2>Done building project "TestUtilities.csproj" -- FAILED.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4469,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "_GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences".
2>Done building project "TestUtilities.csproj" -- FAILED.
```
Any idea of what I could be doing wrong? Thank you!

### Configuration

Visual Studio: Version 16.7.0 Preview 6.0
Windows Pro x64 Version 10.0.19041 Build 19041

master @ 065bf96e5c2

### Regression?

build problem

**Comment by safern** [comment]
Thanks @alefranz for reporting. Something to note, you shouldn't longer need to use the `-vs` switch to run tests from VS as we now use a `.settings` file that the test explorer uses to run the tests.

We will take a look at the issue you're hitting.

**Comment by alefranz** [comment]
> we now use a `.settings` file that the test explorer uses to run the tests.

I don't seem to have a .settings file.

So what is the recommended workflow?
Should I simply set the path for the dotnet sdk, cd into the library folder and launch the sln in VS?

**Comment by ViktorHofer** [comment]
The runsettings file is created automatically during the test libraries build. As that is failing for you, you won't have it. We will look into the test build's failure. Probably a fallout from a recent change that I did.
