### ISSUE TITLE
Windows_NT Formatting jobs failing 

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#40034]
Windows formatting failure seems to be a configuration issue while configuring Cmake

/cc @jkoritzinsky @dotnet/jit-contrib 

```

  $<TARGET_PROPERTY:prop> may only be used with binary targets.  It may not
  be used with add_custom_command or add_custom_target.  Specify the target
  to read a property from using the $<TARGET_PROPERTY:tgt,prop> signature
  instead.
CMake Error:
  Error evaluating generator expression:
    $<TARGET_PROPERTY:NAME>
  $<TARGET_PROPERTY:prop> may only be used with binary targets.  It may not
  be used with add_custom_command or add_custom_target.  Specify the target
  to read a property from using the $<TARGET_PROPERTY:tgt,prop> signature
  instead.
CMake Error:
  Error evaluating generator expression:
    $<TARGET_PROPERTY:NAME>
  $<TARGET_PROPERTY:prop> may only be used with binary targets.  It may not
  be used with add_custom_command or add_custom_target.  Specify the target
  to read a property from using the $<TARGET_PROPERTY:tgt,prop> signature
  instead.
CMake Error:
  Error evaluating generator expression:
    $<TARGET_PROPERTY:NAME>
  $<TARGET_PROPERTY:prop> may only be used with binary targets.  It may not
  be used with add_custom_command or add_custom_target.  Specify the target
  to read a property from using the $<TARGET_PROPERTY:tgt,prop> signature
  instead.
CMake Error:
  Error evaluating generator expression:
    $<TARGET_PROPERTY:NAME>
```

**Comment by jashook** [comment]
Based on conversations with @safern I will disable the job is it will fail consistently.

**Comment by BruceForstall** [comment]
Did the cmake version change on the build machines? What version is it? (btw, we should add `cmake --version` output in the logfiles). I can't repro this locally with `cmake version 3.15.5`

**Comment by am11** [comment]
Normally on Windows machine, cmake version should be same as https://github.com/dotnet/runtime/blob/ad939422e1db604a0ff85af01d6cdf636c07fffc/global.json#L11 (this cmake.exe gets downloaded locally from blob storage during the execution of build.cmd)

**Comment by sandreenko** [comment]
@jashook I am not sure why but it looks like the job was not disabled with your change, I see that all outerloop jobs are failing with Windows formatiing job:
https://dev.azure.com/dnceng/public/_build?definitionId=655&_a=summary
![image](https://user-images.githubusercontent.com/22642771/89630931-e8a1ed00-d854-11ea-8611-b96625045cd2.png)
![image](https://user-images.githubusercontent.com/22642771/89630954-f2c3eb80-d854-11ea-8fb1-92334c735020.png)

**Comment by BruceForstall** [comment]
Fixed by https://github.com/dotnet/runtime/pull/49025
