### ISSUE TITLE
Code Incorrectly Optimized Away

### ISSUE THREAD

**Issue by luckerby** [dotnet/runtime#40043]
Consider the following simple code:
```
    class Program
    {
        static void Main(string[] args)
        {
            var w = new Worker();
            while (!w.IsDone);
            Console.WriteLine("Done");
        }
    }

    class Worker
    {
        public volatile bool IsDone;
        public Worker() => new Thread(Job).Start();

        private void Job()
        {
            Thread.Sleep(3000);
            IsDone = true;
        }
    }
```

Building to `Debug` will get the application running as expected, but targeting `Release` will end up in a never-ending run.

Looking at the resulting assembly, it appears that some code is optimized away, leaving the equivalent of a `while(true) {}` infinite loop. Using Visual Studio, this can actually be seen in the Disassembly View:
![image](https://user-images.githubusercontent.com/31319583/88716390-aa575000-d127-11ea-9d9e-9fe5b7e75724.png)

Note that the whole loop comes down to 2 assembly instructions. The first one (test) simply sets the ZF (zero flag)to 1, as ECX is 0. The next one (je) will always jump as ZF has just been set (one can double check by looking at the 7th bit of the EFLAGS register, whose value is 246). ECX will never get its value changed from outside, as each thread keeps its context, including the register contents. Hence the infinite loop. 

The question would be who makes the error - the compiler or the JITter ? Using dnSpy, we can clearly see below that the IL is referencing the `IsDone` field, so that pretty much leaves the JITter as the culprit.
![image](https://user-images.githubusercontent.com/31319583/88716489-d07cf000-d127-11ea-92d9-cb3e096d8d25.png)

Tried switching to 32-bit output instead of the default 64-bit, but got the same outcome, so the issue is probably affecting both platforms.

Once volatile is applied to the `IsDone` field, the loop's assembly instructions change drastically, and we can see the `IsDone` field referenced directly when comparing, ensuring a "correct" loop:
![image](https://user-images.githubusercontent.com/31319583/88716541-e1c5fc80-d127-11ea-8259-fcb26e7e2801.png)

My guess is that applying volatile simply changes something in the JITter's state just enough so that it compiles correctly. If it would have been a memory barrier issue, then the code seen in the first picture above shouldn't have been that of an infinite loop to begin with.

This came up in a Dotnetos [Async Expert course](https://asyncexpert.com/), raised first by Thiago Borba.

Tested on .NET Core 3.1 x64 and x86 on Windows 10 v1909, with the same result.

**Comment by jkotas** [comment]
This is the expected behavior. `volatile` have to be used to make a lock-free multi-threaded code like this work correctly.

For reference, the documentation is at: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile#example
