### ISSUE TITLE
Consider making Visual Studio's CMake integration work with CMake projects within the repo

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#40049]
When I open the `src/coreclr` folder with VS, I get the following errors during CMake cache generation (with the CMake related components instslled):
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at src/libraries-native/CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source
  "/src/libraries/Native/Unix/System.Globalization.Native" which is not an
  existing directory.		C:\Users\gotos\source\repos\runtime\src\coreclr\src/libraries-native/CMakeLists.txt	10	
Error		CMake Error at src/pal/prebuilt/inc/CMakeLists.txt:3 (_install):
  Unknown CMake command "_install".	COREPAL	C:\Users\gotos\source\repos\runtime\src\coreclr\src/pal/prebuilt/inc/CMakeLists.txt	3	
Error		CMake Error at C:\Users\gotos\source\repos\runtime\src\coreclr\CMakeLists.txt:8 (include):
  include could not find load file:

    /configurecompiler.cmake	CoreCLR	C:\Users\gotos\source\repos\runtime\src\coreclr\CMakeLists.txt	8	
```
I looked briefly into it, and it looks like some variables aren't defined. Manually defining those variables in `CMakeSettings.json` file does somewhat fix this issue by letting it successfully generate the cache:
```json
"variables": [
    {
        "name": "CLR_REPO_ROOT_DIR",
        "value": "C:/Users/gotos/source/repos/runtime",
        "type": "PATH"
    },
    {
        "name": "CLR_ENG_NATIVE_DIR",
        "value": "C:/Users/gotos/source/repos/runtime/eng/native",
        "type": "PATH"
    },
    {
        "name": "CLR_CMAKE_HOST_ARCH",
        "value": "x64",
        "type": "STRING"
    }
]
```
(Without the last variable, `eng/native/configureplatform.cmake` end up calling `clr_unknown_arch` which results in hilarious error message like "Only AMD64, ... are supported. Found: AMD64")

This ends up generating 100+ new files in `out/build` folder, which looks like it's artifacts from CMake judging by the fact that `out/build` is specified in default `CMakeSettings.json` file. Perhaps this should be `gitignore`d?

I'm not really familiar with how CMake and VS integration with it works in general, so I might have guessed certain things the wrong way - is `CMakeSettings.json` file something we want to have / need in the repo to get this working correctly? are those variables supposed to be set automatically?

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/runtime/issues/272 looks like part of this bigger issue.

**Comment by tannergooding** [comment]
CC. @ViktorHofer, @safern

**Comment by safern** [comment]
cc: @jashook @jkoritzinsky

**Comment by Gnbrkm41** [comment]
I looked into this a bit more, and it looks like the `out/build` issue is just the matter of setting `buildRoot` as something else in the CMakeSettings.json.

Currently what I have is this:
src/coreclr/CMakeSettings.json
```json
{
    "configurations": [
        {
            "name": "Windows_NT.x64.Debug",
            "generator": "Ninja",
            "configurationType": "Debug",
            "inheritEnvironments": [ "msvc_x64_x64" ],
            "buildRoot": "${projectDir}\\..\\..\\artifacts\\obj\\coreclr\\${name}",
            "installRoot": "${projectDir}\\..\\..\\artifacts\\bin\\coreclr\\${name}",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "",
            "ctestCommandArgs": "",
            "variables": [
                {
                    "name": "CLR_REPO_ROOT_DIR",
                    "value": "${projectDir}\\..\\..",
                    "type": "PATH"
                },
                {
                    "name": "CLR_ENG_NATIVE_DIR",
                    "value": "${projectDir}\\..\\..\\eng\\native",
                    "type": "PATH"
                },
                {
                    "name": "CLR_CMAKE_HOST_ARCH",
                    "value": "x64",
                    "type": "STRING"
                }
            ]
        }
    ]
}
```

Again, I'm not really 100% sure about what I'm doing, so I'm not confident about certain things. One is whether we could / should use Ninja for the generator instead of `Visual Studio 16 2019`; However, I believe there is a bug with VS that prevents us from using VS2019 as the generator for the time being. I filed https://developercommunity.visualstudio.com/content/problem/1129864/cmake-integration-environments-specified-in-cmakes.html in the developer community for the time being.

**Comment by Gnbrkm41** [comment]
Continuing to tinker with this, it also appears to support other targets like

**Comment by Gnbrkm41** [comment]
It'd be interesting if this also means we could edit sources for Linux/ARM with support of IntelliSense, using the VS integration's WSL / remote building support...

I tried adding a configuration like this:
```
{
    "name": "Linux.x64.Debug",
    "generator": "Ninja",
    "configurationType": "Debug",
    "buildRoot": "${clr.repoRootDir}\\artifacts\\obj\\coreclr\\${name}",
    "cmakeExecutable": "cmake",
    "inheritEnvironments": [ "linux_clang_x64" ],
    "wslPath": "${defaultWSLPath}",
    "variables": [
        {
            "name": "CLR_REPO_ROOT_DIR",
            "value": "${clr.repoRootDir}",
            "type": "PATH"
        },
        {
            "name": "CLR_ENG_NATIVE_DIR",
            "value": "${clr.engNativeDir}",
            "type": "PATH"
        },
        {
            "name": "CLR_CMAKE_HOST_ARCH",
            "value": "x64",
            "type": "STRING"
        }
    ]
}
```
In hopes that it could also generate cache for Linux as well, but unfortunately it seems to be complaining about missing `version.c` files under `artifacts/obj/coreclr/Linux.x64.Debug`. Not entirely sure what those files are about - it seems to be automatically generated as part of the build process, but I can't figure out how they are generated.

**Comment by janvorli** [comment]
> Not entirely sure what those files are about - it seems to be automatically generated as part of the build process, but I can't figure out how they are generated.

The version.c is generated by a msbuild script invoked here:
https://github.com/dotnet/runtime/blob/65c9be6388a99739bd72dc2136f4a0a59b00db72/eng/native/build-commons.sh#L104-L108
 It is used to embed the version / git commit hash into the binary so that it can be found using the following command (example for libcoreclr.so, the version is embedded into all of the binaries we generate).
```sh
strings libcoreclr.so | grep "@(#)"
```

**Comment by Gnbrkm41** [comment]
Ah, I see. Perhaps I can use `remotePrebuildCommand` in the CMakeSettings.json to run the script prior to invoking Cmake...

**Comment by itodirel** [comment]
@Gnbrkm41 you could also try the open cache feature, where you generate the cache externally with the existing scripts, and configure it to open with Visual Studio; we don't currently have a pregenerate command that would work in local non-remote scenarios

**Comment by trylek** [comment]
We should tackle this in context of Jeremy's PR

https://github.com/dotnet/runtime/pull/41897

which already contains special provisions regarding continued support for using VS for the runtime native projects.
