### ISSUE TITLE
Bug with MeasureCharacterRanges on Linux, if text contains LF/CR

### ISSUE THREAD

**Issue by IshmaZX82** [dotnet/runtime#40066]
### Description

Main problem: there is a difference in how method MeasureCharacterRanges work on Windows and on Linux.
On Windows this code works correctly: each char -> rectangle, CR/LF -> empty rectangle.
On Linux: CR symbols disappear, the first symbols of each line after LF also disappear.

Code:
```
                    var g = Graphics.FromImage(new Bitmap(1, 1));
                    var font = new Font("Arial", 11f);
                    var rect = new RectangleF(0, 0, 99999, 99999);
                    var sf = new StringFormat();
                    string text = "12\r\n34\r\n56";
                    var count = text.Length;

                    CharacterRange[] cr = new CharacterRange[count];
                    for (int index = 0; index < count; index++)
                    {
                        cr[index].First = index;
                        cr[index].Length = 1;
                    }
                    sf.SetMeasurableCharacterRanges(cr);
                    Region[] ranges = g.MeasureCharacterRanges(text, font, rect, sf);

                    RectangleF?[] rects = new RectangleF?[count];
                    for (int index = 0; index < count; index++)
                    {
                        rects[index] = ranges[index].GetBounds(g);
                    }
```

Results on Windows:

![on win](https://user-images.githubusercontent.com/52139455/88775605-947c7600-d18d-11ea-8ca0-09b32c60f072.png)

Results on Linux:

![on linux](https://user-images.githubusercontent.com/52139455/88775629-9b0aed80-d18d-11ea-92bd-766c480a53d1.png)

I highlighted the symbols and their rectangles in yellow.

### Configuration

We have tested on NetCore3.0,   
Windows - IIS,
Linux - standard Docker container.

**Comment by IshmaZX82** [comment]
I make some investigations and have an idea that the problem might be in libgdiplus

https://github.com/mono/libgdiplus/issues/663

**Comment by safern** [comment]
@IshmaZX82 this definitely seems like a `libgdiplus` issue. However, it would be helpful to see the difference in the `ranges` array as well.  It seems like you need to update to a later `libgdiplus`. 

Should we close this issue and follow up on `libgdiplus` side?

**Comment by IshmaZX82** [comment]
> Should we close this issue and follow up on `libgdiplus` side?

Yes. Thank you.
