### ISSUE TITLE
Different System.Drawing.Common.dll on different OSes

### ISSUE THREAD

**Issue by Nemirtingas** [dotnet/runtime#40064]
### Description

The runtime library System.Drawing.Common.dll is different on Linux and Windows for example if you build an app that uses it with the .NET Core docker image.

### Configuration

I've build a cross-platform GUI project with the Avalonia Framework and triied to deploy it on Windows/Linux/MacOS with the same code and unfortunatly, using System.Drawing.Image make it impossible to do so. I've switched to SkiaSharp to load/save images.

### Analysis

Windows version of the library uses Gdip and Linux don't ?

**Comment by gfoidl** [comment]
> Windows version of the library uses Gdip and Linux don't ?

Non-windows versions use Mono's [libgdiplus](https://github.com/mono/libgdiplus).
So libgdiplus is a pre-requisite on the linux-target, then at runtime your project should use the correct code-paths to work.

> triied to deploy

Please provide some steps on how you tried this, so this can be reproduced.

**Comment by Nemirtingas** [comment]
Hi,
libgdiplus is already installed on my linux vm, I'll try to provide you an easy reproducable project.

**Comment by Nemirtingas** [comment]
Here's a step-by-step that can reproduce the error, on linux, you also need libc6-dev for System.Drawing to work.

Test project: [test_image.zip](https://github.com/dotnet/runtime/files/4995204/test_image.zip)

```
docker run -it --name test_image -v $(pwd)/test_image:/test_image mcr.microsoft.com/dotnet/core/sdk bash
apt update
apt install libc6-dev libgdiplus -y
cd test_image
dotnet publish -c Release -r linux-x64 --self-contained=false
dotnet publish -c Release -r osx-x64 --self-contained=false
dotnet publish -c Release -r win-x64 --self-contained=false
cd  bin/Release/netcoreapp3.1/win-x64/publish/
dotnet test_image.dll
# Hello World!
# Error: The type initializer for 'Gdip' threw an exception.
cp ../../linux-x64/publish/test_image .
./test_image
# Hello World!
# Error: The type initializer for 'Gdip' threw an exception.
cd ../../linux-x64/publish/
./test_image
# Hello World!
```

**Comment by jkotas** [comment]
You need to publish the app as platform neutral by running ``dotnet publish -c Release` to get a deployment that works everywhere. The app published this way will contain multiple copies of `System.Drawing.Common.dll` under `runtimes` directory.

**Comment by Nemirtingas** [comment]
Yes but then I miss the test_image.exe and test_image for macos:
```
file bin/Release/netcoreapp3.1/test_image
bin/Release/netcoreapp3.1/test_image: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=6644aee648567ad2d7c248a017cbc94d6f5dda3c, stripped
```

Is there a way to generate a neutral platform but with all start executables ?

**Comment by jkotas** [comment]
I do not think we have a single command to do that. You can try copying over the launchers from the platform-specific publish into the platform neutral one.

**Comment by Nemirtingas** [comment]
Ok, I'll try and report back.

**Comment by Nemirtingas** [comment]
Seems to work, I'll use this workaround.
Do you (.NET Team) intend to work on a way to build the startup exes alongside the project ? If so should I open a new issue somewhere else ?
If not then I'll close this.

**Comment by jkotas** [comment]
> Do you (.NET Team) intend to work on a way to build the startup exes alongside the project ? If so should I open a new issue somewhere else ?

You can open issue on this in https://github.com/dotnet/sdk repo.

**Comment by safern** [comment]
Thanks, @jkotas for helping @Nemirtingas here... Given the discussion above I'm going to close this and please @Nemirtingas feel free to open an issue in the SDK to discuss the startups hosts issue.

**Comment by Nemirtingas** [comment]
Thanks for your time and the help.
