### ISSUE TITLE
Remove SocketsHttpConnectionFactory

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#40075]
`SocketsHttpConnectionFactory` was proposed as part of https://github.com/dotnet/runtime/issues/1793.

Its original intent was to provide a number of callbacks for users to customize things without understanding all of the `ConnectionFactory` stuff. However, API review removed all of these callbacks, making this class largely redundant with `SocketsConnectionFactory`.

The only remaining features it has are:
- it pulls the `HttpRequestMessage` out of the property bag for the user.
- it turns Nagle off.

We should consider reducing our API surface by doing the following:
- Remove `SocketsHttpConnectionFactory`.
- Update `SocketsConnectionFactory` to default its sockets with Nagle off.
    - This may cause some confusion to people expecting the default `Socket` behavior. But, it may be okay to be opinionated here, and most experts end up turning it off anyway.
- Update the `DnsEndPointWithProperties` type to expose an `HttpRequestMessage` property.

Old usage example:

```c#
class MyCustomFactory : SocketsHttpConnectionFactory
{
    public override ValueTask<Connection> EstablishConnectionAsync(HttpRequestMessage message, EndPoint endPoint, IConnectionProperties properties, CancellationToken cancellationToken)
    {
       // ...
    }
}
```

New usage example:

```c#
class MyCustomFactory : SocketsConnectionFactory
{
    public override ValueTask<Connection> ConnectAsync(EndPoint endPoint, IConnectionProperties properties, CancellationToken cancellationToken)
    {
        if(!properties.TryGet(out HttpRequestMessage message)) throw new Exception("Expected HttpRequestMessage property");
        // ...
    }
}
```

CC @geoffkizer @karelz this came about from a discussion with @stephentoub. I feel we can treat this as low priority, but it is a low-effort way to improve API surface.

**Comment by geoffkizer** [comment]
This seems like a good thing.

But I don't understand this part:

> Update the DnsEndPointWithProperties type to expose an HttpRequestMessage property.

**Comment by scalablecory** [comment]
> This seems like a good thing.
> 
> But I don't understand this part:
> 
> > Update the DnsEndPointWithProperties type to expose an HttpRequestMessage property.

We currently have this code:

https://github.com/dotnet/runtime/blob/7acaf166f43380ba76616b24a93f1429995ff1d8/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DnsEndPointWithProperties.cs#L19-L29

It exposes a property using an internal type that `SocketsHttpConnectionFactory` understands. We just need to update this to expose the `HttpRequestMessage` as a property instead of this internal type.

**Comment by geoffkizer** [comment]
Yeah, that makes sense, thanks. That seems like it ends up in a better place anyway.

**Comment by geoffkizer** [comment]
@antonfirsov I believe you're already working on this
