### ISSUE TITLE
Microsoft.Diagnostics.Tracing.EventSource.Redist.xml file name does not match Microsoft.Diagnostics.Tracing.EventSource.dll

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/runtime#40093]
### Description

The Microsoft.Diagnostics.Tracing.EventSource.Redist NuGet package contains `Microsoft.Diagnostics.Tracing.EventSource.dll` but `Microsoft.Diagnostics.Tracing.EventSource.Redist.xml`. Because the name of the XML documentation file contains `.Redist` and the name of the DLL file doesn't, Visual Studio cannot find the documentation and show it in Intellisense or in _Go To Definition_.

### Configuration

Visual Studio 2017 version 15.9.25.  
C# project targeting .NET Framework 4.6.1.  
Microsoft.Diagnostics.Tracing.EventSource.Redist version 2.2.0 or 5.0.0-preview.7.20364.11.

### Regression?

It is a regression from Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28, which contains `Microsoft.Diagnostics.Tracing.EventSource.dll` and `Microsoft.Diagnostics.Tracing.EventSource.XML`. However, 2.2.0 and 5.0.0-preview.7.20364.11 are not binary compatible with 1.1.28 (publickeytoken `cc7b13ffcd2ddd51` vs. `b03f5f7f11d50a3a`), so developers shouldn't automatically upgrade from that version and hit the regression.

### Other information

I guess the incorrect `DocumentationFile` is set here (originally from <https://github.com/dotnet/corefx/pull/32934>): <https://github.com/dotnet/runtime/blob/53976d38b1bd6917b8fa4d1dd4f009728ece3adb/src/libraries/Directory.Build.targets#L14-L15>

which uses the `MSBuildProjectName` property, rather than the `AssemblyName` property that was set here: <https://github.com/dotnet/runtime/blob/53976d38b1bd6917b8fa4d1dd4f009728ece3adb/src/libraries/Microsoft.Diagnostics.Tracing.EventSource.Redist/src/Microsoft.Diagnostics.Tracing.EventSource.Redist.csproj#L3>

Found while checking for <https://github.com/dotnet/runtime/issues/31389> in 5.0.0-preview.7.20364.11.

**Comment by KalleOlaviNiemitalo** [comment]
I believe Microsoft.Diagnostics.Tracing.EventSource.Redist.csproj is the only source project that sets `AssemblyName` as something other than the project name.

**Comment by KalleOlaviNiemitalo** [comment]
@Dotnet-GitSync-Bot, aren't you going to add any labels? 🤔

**Comment by tommcdon** [comment]
@davmason can you take a look, this looks like a quick fix and valuable for dev inner loop scenarios
