### ISSUE TITLE
Support for `init` properties in dynamic binder

### ISSUE THREAD

**Issue by HaloFour** [dotnet/runtime#40118]
See: https://github.com/dotnet/csharplang/issues/39#issuecomment-666012974

Seems that the C# runtime binder ignores `modreq` metadata on members.  This enables `init` properties to be trivially mutated by casting to `dynamic`:

```cs
public class Foo {
    public string Value { get; init; }
}

static class Program {
    static void Main() {
        var foo = new Foo { Value = "Hello" };
        ((dynamic)foo).Value = "World";
        Console.WriteLine(foo.Value); // prints World
    }
}
```

**Comment by mangod9** [comment]
@HaloFour I assume you expect this to not compile in c#, additionally the runtime to also throw?

**Comment by HaloFour** [comment]
@mangod9 

I'd expect it to compile in C# (since it's being cast to `dynamic`) but to throw at runtime.  It probably should be doing this already since the member would have a `modreq` applied to it and shouldn't be invoked without the binder understanding what that modifier entails.

If you take `dynamic` out of the equation and attempt to mutate the property it will fail to compile: [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUgOwjDigAcIBjOAAhwIDoAlAV3JjWrsAwgHswtTIgDKiAG5omUZgG9SzdawDMrAgDZWeZgEkoAUQAe8BJQxHyaGCuYBfUq7Iec2/MwBiIkRU1DS8dAAZmADUIDG4WZWYAczgYAG5mNHs0lzdSUjZ9HzYAdiCSDR1CgBZmAFkITIAKAEoyiorZCARmADMA5gBeZnI4AHc/foTo2JYhgCIACTgMDBE5l1Tg9t6A9mm4weY5gHURBAwAEznN8u2dAE5GvpE9mLjmm4r3ZyA===)

**Comment by YairHalberstadt** [comment]
In the discussion about this the C# team seemed to feel it would be better not to throw:

See the discussion in https://github.com/dotnet/csharplang/issues/3376

Specifically see https://github.com/dotnet/csharplang/issues/3376#issuecomment-617899163

**Comment by HaloFour** [comment]
Also see: https://github.com/dotnet/csharplang/issues/3376#issuecomment-617925716

@jaredpar
