### ISSUE TITLE
System.Runtime.InteropServices.JavaScript.Tests.MarshalTests.TestFunctionApply failed on CI (wasm mono subset)

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#40112]
Some wasm test failures on the PR https://github.com/dotnet/runtime/pull/39825: 
https://dev.azure.com/dnceng/public/_build/results?buildId=749999&view=ms.vss-test-web.build-test-results-tab

```
System.Linq.Expressions.Tests
System.Runtime.InteropServices.JavaScript.Tests
```

e.g.: `System.Runtime.InteropServices.JavaScript.Tests.MarshalTests.TestFunctionApply`
```
Error message
System.Runtime.InteropServices.JavaScript.JSException : Error: System.NullReferenceException: Object reference not set to an instance of an object.\n   at System.Runtime.InteropServices.JavaScript.Tests.HelperMarshal.CreateFunctionApply()

Stack trace
   at Interop.Runtime.InvokeJS(String str)
   at System.Runtime.InteropServices.JavaScript.Runtime.InvokeJS(String str)
   at System.Runtime.InteropServices.JavaScript.Tests.MarshalTests.TestFunctionApply()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by MaximLipnin** [comment]
It seems to be flaky - I got the failure 4 times out of 10 locally.

**Comment by MaximLipnin** [comment]
Besides that, there can be something like:
```
  dbug: test[0]
        [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTests.FunctionMath
  dbug: test[0]
        Assert.NotNull() Failure
  dbug: test[0]
           at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTests.FunctionMath()
  dbug: test[0]
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by MaximLipnin** [comment]
The failing tests will be disabled in https://github.com/dotnet/runtime/pull/40139

**Comment by lewing** [comment]
This failure seems to go away if you pass `--disable-on-demand-gc` so it is likely related to the on-demand GC, either a bug there or ref counting/pinning issues in the bindings.

**Comment by lewing** [comment]
cc @vargaz

**Comment by marek-safar** [comment]
@kg @lewing where are we on this one?

**Comment by kg** [comment]
We're disabling on demand GC in the release, and I've been working on binding fixes that should fix this for .NET 6. I don't know if the current set of fixes is sufficient yet

**Comment by lewing** [comment]
@kg is this still failing for net5.0?

**Comment by kg** [comment]
I never successfully reproduced this bug locally to begin with, so I don't know.

**Comment by lewing** [comment]
Ok, I'll take a look. I was able to reproduce it in the past.

**Comment by MaximLipnin** [comment]
`System.Runtime.InteropServices.JavaScript.Tests.MarshalTests.MarshalTypedArrayByte` also fails with NRE - it has the most stable local repro.

**Comment by lewing** [comment]
@kg was able to reproduce locally
