### ISSUE TITLE
How to install vc_redist in nanoserver

### ISSUE THREAD

**Issue by imaramos** [dotnet/runtime#40131]
AFAIK  it is not possible to install vc_redist in nanoserver at least in the traditional way because nanoserver is not able to install msi packages.
I have tried to copy dlls such as `vcruntime140.dll` and `vccorlib140.dll` from windows server core to `C:/Windows/System32/`, but I am still getting  `System.BadImageFormatException` when running my app (which has mixed mode assemblies).
Can someone help me with this?

**Comment by AaronRobinsonMSFT** [comment]
@imaramos Can you verify the needed dependencies are those versions? It is possible, for Debug builds, the debug versions of those binaries are needed (i.e. `vcruntime140d.dll`). This can be determined by running the following at a Developer command prompt: `dumpbin /imports <assembly>.dll`

/cc @tgani-msft @jkoritzinsky

**Comment by imaramos** [comment]
This is the output of that command:

```
File Type: DLL

  Section contains the following imports:

    KERNEL32.dll
             18000C000 Import Address Table
             18003B220 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         450 QueryPerformanceCounter
                         21E GetCurrentProcessId
                         222 GetCurrentThreadId
                         2F0 GetSystemTimeAsFileTime
                         122 DisableThreadLibraryCalls
                         36C InitializeSListHead
                         4D3 RtlCaptureContext
                         4DA RtlLookupFunctionEntry
                         4E1 RtlVirtualUnwind
                         382 IsDebuggerPresent
                         5BC UnhandledExceptionFilter
                         57B SetUnhandledExceptionFilter
                         2D7 GetStartupInfoW
                         389 IsProcessorFeaturePresent
                         27E GetModuleHandleW
                         3C4 LoadLibraryA
                         2B5 GetProcAddress
                         524 SetEvent
                          BF CreateEventW
                         1B1 FreeLibrary
                         5E6 WaitForSingleObject
                          86 CloseHandle
                         58B Sleep

    VCRUNTIME140.dll
             18000C0E0 Import Address Table
             18003B300 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          1C __current_exception_context
                          3D memmove
                          13 __FrameUnwindFilter
                          1B __current_exception
                          25 __std_type_info_destroy_list
                           1 _CxxThrowException
                          22 __std_exception_destroy
                          21 __std_exception_copy
                          3E memset
                           8 __C_specific_handler

    api-ms-win-crt-runtime-l1-1-0.dll
             18000C180 Import Address Table
             18003B3A0 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          67 terminate
                          16 _cexit
                          1D _crt_at_quick_exit
                          1E _crt_atexit
                          22 _execute_onexit_table
                          3C _register_onexit_function
                          33 _initialize_narrow_environment
                          18 _configure_narrow_argv
                          3F _seh_filter_dll
                          37 _initterm_e
                          36 _initterm
                          39 _invalid_parameter_noinfo_noreturn
                          34 _initialize_onexit_table
                          54 abort

    api-ms-win-crt-heap-l1-1-0.dll
             18000C150 Import Address Table
             18003B370 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           8 _callnewh
                          19 malloc
                          18 free

    MSVCP140.dll
             18000C0C0 Import Address Table
             18003B2E0 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         299 ?__ExceptionPtrDestroy@@YAXPEAX@Z
                         28E ?_Xlength_error@std@@YAXPEBD@Z
                         295 ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z

    WS2_32.dll
             18000C138 Import Address Table
             18003B358 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                             Ordinal   115
                             Ordinal   116

    api-ms-win-crt-string-l1-1-0.dll
             18000C1F8 Import Address Table
             18003B418 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          90 strncpy_s
                          89 strcpy_s

    api-ms-win-crt-math-l1-1-0.dll
             18000C170 Import Address Table
             18003B390 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          7D ceilf

    ijwhost.dll
             18000C210 Import Address Table
             18003B430 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           1 _CorDllMain

  Summary

        2000 .data
        2000 .nep
        1000 .pdata
       30000 .rdata
        1000 .reloc
        1000 .rsrc
        9000 .text

```
`ijwhost.dll` is placed in the bin folder, and I have tried to copy `VCRUNTIME140.dll`  `MSVCP140.dll` to c:/Windows/System32 with no luck

**Comment by AaronRobinsonMSFT** [comment]
@imaramos Thanks for confirming this. The `System.BadImageFormatException` is typically related to bitness mismatch so I would verify that next. Is everything 64-bit or 32-bit? This can be verified using the `dumpbin` command with the `/headers` flag. Verifying all the deployed and generated binaries is key here. I assume the target platform is amd64-bit nanoserver?

**Comment by imaramos** [comment]
> @imaramos Thanks for confirming this. The `System.BadImageFormatException` is typically related to bitness mismatch so I would verify that next. Is everything 64-bit or 32-bit? This can be verified using the `dumpbin` command with the `/headers` flag. Verifying all the deployed and generated binaries is key here. I assume the target platform is amd64-bit nanoserver?

Thank you for the help!  Yes everything is running on 64-bit
```
FILE HEADER VALUES
            8664 machine (x64)
               7 number of sections
        5F229ED4 time date stamp Thu Jul 30 11:20:04 2020
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
            2022 characteristics
                   Executable
                   Application can handle large (>2GB) addresses
                   DLL
```
Yes I am targeting amd64-bit, I have tested the same code in windowserver core and it worked, the only difference was that in windowservercore I was able to install https://aka.ms/vs/16/release/vc_redist.x64.exe.
I am actually using docker with this image mcr.microsoft.com/dotnet/core/aspnet:3.1.6-nanoserver-2004 which is amd64.
On the other hand I have tried with this image mcr.microsoft.com/windows/servercore:2004 but I had to install the vc_redist (https://aka.ms/vs/16/release/vc_redist.x64.exe) and the dotnet runtime using this command `dotnet-install.ps1 -Runtime aspnetcore -Channel 3.1 -Version latest`

**Comment by AaronRobinsonMSFT** [comment]
@imaramos Thanks. At this point I agree with the assumption this is some install issue. Seems we need to get the VC team involved as they should be able to help guide the investigation if the nanoserver is the issue since servercore works as expected. Let me reach out to them offline and bring them in.

**Comment by imaramos** [comment]
@AaronRobinsonMSFT thank you so much for helping me with this issue. From my perspective this is an important issue because C++/CLI only works on windows and I don't see intentions to support it on linux.

Just for you and the team to analyze:

**This is what I am trying with nanoserver (and failing)**
```
FROM mcr.microsoft.com/windows/servercore:2004 as installer
ADD https://aka.ms/vs/16/release/vc_redist.x64.exe C:/setup/vc_redist.x64.exe
RUN C:/setup/vc_redist.x64.exe /install /quiet /norestart

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.6-nanoserver-2004 as runtime
COPY --from=installer C:/Windows/System32/vcruntime140.dll C:/Windows/System32/vcruntime140.dll
COPY --from=installer C:/Windows/System32/msvcp140.dll C:/Windows/System32/msvcp140.dll
COPY C:/bin C:/bin
ENTRYPOINT ["C:/bin/MyApp.dll"]
```
 **This is what I have tried before with windowsserver core that worked**
```
FROM mcr.microsoft.com/windows/servercore:2004 as runtime
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
ADD https://dot.net/v1/dotnet-install.ps1 C:/setup/dotnet-install.ps1
RUN C:/setup/dotnet-install.ps1 -Runtime aspnetcore -Channel 3.1 -Version latest -InstallDir c:\dotnet
ENV DOTNET_ROOT=c:/dotnet
ADD https://aka.ms/vs/16/release/vc_redist.x64.exe C:/setup/vc_redist.x64.exe
RUN C:/setup/vc_redist.x64.exe /install /quiet /norestart
COPY  C:/bin C:/bin
ENTRYPOINT ["C:/bin/MyApp" ]
```

**Comment by AaronRobinsonMSFT** [comment]
@imaramos Any chance you can try a pre-2004 version? Just for the sake of sanity it might help to understand if this is a new OS asset issue or something that been an issue for a while.

**Comment by imaramos** [comment]
> @imaramos Any chance you can try a pre-2004 version? Just for the sake of sanity it might help to understand if this is a new OS asset issue or something that been an issue for a while.

Yes, tried wit  mcr.microsoft.com/windows/servercore:1909 + mcr.microsoft.com/dotnet/core/aspnet:3.1.6-nanoserver-1909 and got the same issue

**Comment by tgani-msft** [comment]
BadImageFormatException is also possible when vcruntime*dll isn't found. Did you try to copy the vcruntime140.dll app-locally?

**Comment by imaramos** [comment]
> BadImageFormatException is also possible when vcruntime*dll isn't found. Did you try to copy the vcruntime140.dll app-locally?

I am running it in docker, and there it fails when you `COPY` a file that doesn't exist.

**Comment by MahmoudGSaleh** [comment]
> /cc @MahmoudGSaleh for help with vclibs.

vc_redist.x64.exe Desktop only and won't run on Nano Server (or any other non-Desktop OS). You will need to copy the binaries manually. Please use the OneCore version; e.g. c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Redist\MSVC\**14.27.29009**\onecore\x64\Microsoft.VC142.CRT . You will need to copy everything under that folder. You can put the files in windows\system32 or app local.

**Comment by imaramos** [comment]
> > /cc @MahmoudGSaleh for help with vclibs.
> 
> vc_redist.x64.exe Desktop only and won't run on Nano Server (or any other non-Desktop OS). You will need to copy the binaries manually. Please use the OneCore version; e.g. c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Redist\MSVC*_14.27.29009_*\onecore\x64\Microsoft.VC142.CRT . You will need to copy everything under that folder. You can put the files in windows\system32 or app local.

Thank you so much for the help, could you point me the path for these onecore dlls when installing vc_redist through this installer vc_redist.x64.exe? I am not finding those.

**Comment by MahmoudGSaleh** [comment]
>Thank you so much for the help, could you please point me out the path for these onecore dlls when installing vc_redist through this installer vc_redist.x64.exe? I am not finding those.

Unfortunately, these are not installed by the vc_redist. To get these files, you will need to [install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019), making sure to select the option "Desktop development with C++".

You can download Visual Studio from [here](https://visualstudio.microsoft.com/downloads/). And, for more information about the redistributables of Visual C++ Runtime files, please see [this page](https://docs.microsoft.com/en-us/visualstudio/releases/2019/redistribution#visual-c-runtime-files).

**Comment by imaramos** [comment]
> > Thank you so much for the help, could you please point me out the path for these onecore dlls when installing vc_redist through this installer vc_redist.x64.exe? I am not finding those.
> 
> Unfortunately, these are not installed by the vc_redist. To get these files, you will need to [install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019), making sure to select the option "Desktop development with C++".
> 
> You can download Visual Studio from [here](https://visualstudio.microsoft.com/downloads/). And, for more information about the redistributables of Visual C++ Runtime files, please see [this page](https://docs.microsoft.com/en-us/visualstudio/releases/2019/redistribution#visual-c-runtime-files).

Got it, ideally we should be able to do it with vc_redist because we are using docker.
I have copied the dlls from my OS and I got another error that does not seem related with vc_redist so I guess it worked, thank you very much!
Do you have any plan to support such installation without having the need to install the whole visual studio? I guess it would be helpful for scenarios like this.

**Comment by AaronRobinsonMSFT** [comment]
@imaramos I am going to close this issue since this appears to be an issue with vc_redist. For continuing that conversation, I would recommend filing an issue through [Developer Community Portal](https://developercommunity.visualstudio.com/spaces/8/index.html) for the vc_redist questions/issues.
