### ISSUE TITLE
Add Pattern Matching to Linq.Expressions

### ISSUE THREAD

**Issue by sidney-pauly** [dotnet/runtime#40143]
## Background and Motivation

I'm currently building code generating code with Linq.Expressions, that needs to produce a function which switches on the type of an object and performs a specific action specific to the matched class. One option is to use `myObject.GetType().FullName` and make the switch on it. As this is a switch string it should be significantly slower than directly switching on the types. Additionally, an extra cast is needed if the cast object is needed. In any case, it would produce a switch case like such:
```
        void MyCompiledFunc(object myObject)
        {
            switch (myObject.GetType().FullName)
            {
                case ("SomeNamespace.SomeType"):
                    var asSomeType = (SomeType)myObject;
                    asSomeType.DoSomething();
                    break;
            }
        }
```
A better way to write this function is using [Pattern Matching](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching):

```
        void MyBetterCompiledFunc(object myObject)
        {
            switch (myObject)
            {
                case SomeType asSomeType:
                    asSomeType.DoSomething();
                    break;
            }
        }
```

## Proposed API

Adding Pattern Matching to Linq.Expressions could be done like this.   
Note: The following code only describes the API, not how it could get implemented. 

```diff
namespace System.Linq.Expressions
{
    public abstract class Expression
    {
        // ...

+       /// <summary>
+       /// Produces a pattern matching expression.
+       /// </summary>
+       /// <param name="toMatch">
+       /// The <see cref="ParameterExpression"/> representing the Parameter that should get matched
+       /// </param>
+       /// <param name="type">
+       /// The type <paramref name="toMatch"/> the Parameter should get matched to
+       /// </param>
+       /// <param name="matched">
+       /// The <see cref="ParameterExpression"/> the matched object is assigned to if the match was successful
+       /// </param>
+       /// <returns></returns>
+       public static TypeBinaryExpression TypeMatchPattern(ParameterExpression toMatch, Type type, ParameterExpression matched)
+       {
+         // ..
+       }
        
        // ...
    }

+   public class TypeBinaryExpression : Expression
+    {
+        // ..
+    }
}
```

## Usage Examples

Example of a function that generates the second switch shown in "Background and Information":
```
public Action<object> CompileMyFunc()
        {
            var RESULT_FUNC_PARAMETER_myObject = Expression.Parameter(typeof(object));

            var matchedType = Expression.Variable(typeof(SomeType));
            var callDoSomething = Expression.Call(matchedType, typeof(SomeType).GetMethod(nameof(caseSomeType.DoSomething)));
            var caseSomeType = Expression.SwitchCase(callDoSomething, new[] { Expression.TypeMatchPattern(RESULT_FUNC_PARAMETER_myObject, typeof(SomeType), matchedType) });

            var mySwitch = Expression.Switch(RESULT_FUNC_PARAMETER_myObject, new[] { caseSomeType });

            return Expression.Lambda<Action<object>>(mySwitch, new[] { RESULT_FUNC_PARAMETER_myObject }).Compile();
        }

```
Using the Expression.TypeMatchPattern with if-conditions would work in the same way.

## Implementation
I have no knowledge of how Linq.Expressions work under the hood, but I believe it should be possible to implement this, as this merely replicates the already existing pattern matching functionality.

**Comment by Wraith2** [comment]
> As this is a switch string it should be significantly slower than directly switching on the types.

Why would this be the case?

**Comment by sidney-pauly** [comment]
@Wraith2 Switching on strings should be slower because two reasons:
- Strings are made up of multiple chars and therefore a comparison has to be done on each individual char.
- The casting/typehierachie is handled by the runtime, comparing them is therefore very fast.

In addition you get rid of one cast and the code is cleaner overall. Also pattern matching not only matches the type itself, but all derived types.

**Comment by pinkfloydx33** [comment]
There's plenty of language features that expressions don't support, several that I'd much rather see than this. I'm not arguing against pattern matching support, but things like null-propogation are probably more useful. I'm pretty sure however, that the team has decided in the past that the Expression API was not going to be updated going forward... which is quite unfortunate

**Comment by svick** [comment]
@sidney-pauly 

I don't understand how is the proposed `TypeMatchPattern` supposed to work. If you evaluate it on its own, what value does it return? And how can you use this value in both `Switch` and `If`?

Also, if I was trying to write a type switch using Expression Trees today, I would probably use a sequence of `IfThenElse` expressions and `TypeIs` (or `TypeAs`), instead of trying to fit it into a `Switch`.

@pinkfloydx33 

I agree that wholesale updating of the Expressions API with new language features (https://github.com/dotnet/csharplang/issues/158) is a much better option than trying to do it one by one. As I understand it, that has not been rejected, but it also has not received much attention recently. ([The latest update I know of is from 2018.](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-06-06.md))

**Comment by danmosemsft** [comment]
Hello, thanks for the suggestions. We are not accepting new features into S.L.E - please see https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/README.md

**Comment by cston** [comment]
Closing since we are not accepting new features in System.Linq.Expressions.

Thanks @sidney-pauly for the suggestion.
