### ISSUE TITLE
Trim OSPlatformAttributes from WASM apps

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#40163]
The new attributes that inherit from `OSPlatformAttribute` that were introduced with #33331 are only needed for build-time analysis. They are not necessary at runtime. We should add these attributes to the list of attributes we remove for linked WASM apps:

https://github.com/dotnet/runtime/blob/a5e2249753147038bc9f317bb556c32e2bc91f29/src/mono/netcore/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.wasm.xml#L2-L7

cc @marek-safar @layomia

**Comment by jeffhandley** [comment]
@marek-safar I'm assuming your team will field this but please let me know if you need anything from my team. Thanks.
