### ISSUE TITLE
build mono sdks

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#40179]
Can this repo use to build mono sdks(macos, windows, ios and android) now? Is there any tutorial for build it?
Another quesion is can we include source code directly build with other project(like Unreal Engine)?

**Comment by marek-safar** [comment]
There is documentation on how to build for different OSes and different configurations. You can start for example here https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries#building-all-for-other-oses

The output will be always NuGet package which is what .NET Core uses as a distribution unit. If you would like to build for a new OS or platform please submit PR and the details will be discussed there.
