### ISSUE TITLE
DateTimeFormatInfo.GetEra(string) does not work in a scenario

### ISSUE THREAD

**Issue by alexeysmorkalov** [dotnet/runtime#40194]
### Steps to reproduce

```
            var ci = new CultureInfo("ja-JP") { DateTimeFormat = { Calendar = new JapaneseCalendar() }};
            var jpFormatInfo = ci.DateTimeFormat;

            // it returns -1 but expected 4
              var result = jpFormatInfo.GetEra("H");
```

### Configuration

**Fails** on  **5.0.100-preview.7.20366.6**
**Works correctly** on any .NET Framework, .Net Core 3.0, .Net Core 3.1, .Net 5 lower than **5.0.100-preview.4.20258.7**
x64

### Regression
.Net Framework, Core 3.0, Core 3.1 and .Net5 until 5.0.100-preview.4.20258.7

### Other information

The reason is System.Globalization.DateTimeFormatInfo.AbbreviatedEnglishEraNames contains not abbreviated but full era names

**Comment by tarekgh** [comment]
Thanks @alexeysmorkalov for reporting the issue. we'll take a look to see what is going on.
