### ISSUE TITLE
Value of COMPlus_PInvokeInline knob

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#40192]
The `PInvokeInline` knob is defined by: https://github.com/dotnet/runtime/blob/b262f0bd2e57c528241609aa47bc4eb99a865336/src/coreclr/src/inc/clrconfigvalues.h#L695

but I could not figure out what should be the (string) value? (and what output to expect from it)

I am investigating an issue with P/Invoke methods, which are also marked with intrinsic attribute (and correctly recognized as intrinsic by the JIT), fail to get inlined. I am thinking `COMPlus_PInvokeInline` will help in this investigation, in addition to:

```sh
COMPlus_JitDump=*
COMPlus_JitPrintInlinedMethods=1
```

**Comment by jkotas** [comment]
This is dead code. Removing in #40199
