### ISSUE TITLE
JIT assertion failure when running tests in OSX

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#40195]
I'm seeing the following assertion failure when running a new set of tests in Coreclr OSX x64 Debug:

```
Assert failure(PID 82341 [0x000141a5], Thread: 933639 [0xe3f07]): Assertion failed 'tree->AsField()->gtFldObj == nullptr' in 'elems@20:Close():this' during 'Update flow graph early pass' (IL size 133)

    File: /Users/runner/work/1/s/src/coreclr/src/jit/flowgraph.cpp Line: 19214
    Image: /private/tmp/helix/working/A9D5098C/p/dotnet
```

The issue seems to reproduce consistently (I triggered CI twice) and only happens in OSX. I don't currently have access to an OSX device, so wasn't able to further drill down into the problem.

Relevant PR: https://github.com/dotnet/runtime/pull/40135#issuecomment-666343524 cc @kunalspathak

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib , @erozenfeld

**Comment by AndyAyersMS** [comment]
Marking as 5.0.

**Comment by erozenfeld** [comment]
This assert also fires when running pmi on FSharp.Core.dll:

```
F:\runtime3\artifacts\tests\coreclr\Windows_NT.x64.checked\Tests\Core_Root\CoreRun.exe C:\jitutils\bin\pmi.dll PREPALL-QUIET F:\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Release\Tests\Core_Root\FSharp.Core.dll

Assert failure(PID 48636 [0x0000bdfc], Thread: 57452 [0xe06c]): Assertion failed 'tree->AsField()->gtFldObj == nullptr' in 'System-Collections-Generic-IReadOnlyDictionary-2-get_Keys@676[__Canon,Int64][System.__Canon,System.Int64]:Close():this' during 'Update flow graph early pass' (IL size 135)

    File: F:\runtime3\src\coreclr\src\jit\flowgraph.cpp Line: 19214
    Image: F:\runtime3\artifacts\tests\coreclr\Windows_NT.x64.checked\Tests\Core_Root\CoreRun.exe
```

**Comment by AndyAyersMS** [comment]
I'll take a look.

**Comment by AndyAyersMS** [comment]
Think the repro is an object field feeding a degenerate switch. Haven't tracked down the source yet; based on IL, trying to come up with some simple C# for this. Roslyn is surprisingly aggressive at turning switches into if then trees. Seems like perhaps way too aggressive.

**Comment by AndyAyersMS** [comment]
The method being jitted in CI also comes from FSharp.Core.dll, issue looks similar... we are not properly handling a switch flow opt that happens before statement lists are threaded. Fix seems simple.

**Comment by eiriktsarpalis** [comment]
I'm curious though why CI only surfaced this issue in OSX builds?
