### ISSUE TITLE
Configuration binder not using the expected default value for nullable members?

### ISSUE THREAD

**Issue by FMauroy** [dotnet/runtime#40193]
### Description

I use Microsoft.Extensions.Configuration.GetSection() and then Bind() to fill a list of objects. The class contains nullable fields, like bool? and enum?. When the JSON config contains an explicit value for any of these, binding works fine, but when it doesn't, I'd expect the value to be set to null, which is not the case. The bool? is set to false, and the enum? is set to the first item (0). Am I doing something wrong? I tried setting several attributes to those fields (like DefaultValue(null) among others), to no avail...
I need them to be null when not specified in config, so I can coallesce the missing ones with default values.
Thanks beforehand!

### Configuration

DotNet Core 2.2

### Regression?

Well, if I test with Newtonsoft Json.Net, the defaults are null as expected.

### Other information

Only workaround I found was to explicitely set the values to null in the JSON file, which defeats their optional nature.

### Code excerpt
```

    public class OpcEndpoint
    {
        public string Alias { get; set; }
        public string Endpoint { get; set; }

        public MessageSecurityMode? SecurityMode { get; set; } = null;
        public bool? UseSecurity { get; set; } = null;
    }

    var endpoints = new List<OpcEndpoint>();
    configuration.GetSection("OPC:Endpoints").Bind(endpoints);

```

**Comment by FMauroy** [comment]
Probable label: area-Extensions-Configuration

**Comment by maryamariyan** [comment]
So the issue here is having a missing check for nullable value type and it sets to default rather than null.

The fix would be a breaking change. Perhaps it might be better to keep existing behavior as default and then introduce an API in BinderOptions to allow for setting nullable attributes to null.

cc: @HaoK @safern @davidfowl

**Comment by HaoK** [comment]
Is this indeed only an issue in the new json provider and not an issue with the old newtonsoft one?

**Comment by Nick-Stanton** [comment]
Hi @FMauroy, I attempted to recreate this using .NET 6 and could only get the intended behavior. Are you still experiencing this issue?

I created a repo for my recreation [here](https://github.com/Nick-Stanton/BinderNotNull---40193) in case you were curious. I used an ArrayList for my SecurityMode field for simplicity, but I don't expect that to cause a change in behavior.
