### ISSUE TITLE
[wasm] Full GC ends up in loop in get_next_size

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#40214]
### Description

Blazor benchmarks seem to be triggering an infinite loop in  mono\metadata\mempool.c:

``` 
static guint
get_next_size (MonoMemPool *pool, int size)
{
       int target = pool->next? pool->next->size: pool->size;
       size += SIZEOF_MEM_POOL;
       /* increase the size */
       target += target / 2;
       while (target < size) {
              target += target / 2;
       }
       if (target > MONO_MEMPOOL_PAGESIZE && size <= MONO_MEMPOOL_PAGESIZE)
              target = MONO_MEMPOOL_PAGESIZE;
       return target;
}
```
The problem is that for some reason, the value of ‘target’ has become zero.  Disabling the full gc seems to avoid the issue.

cc @pranavkm @paolosevMSFT

**Comment by SamMonoRT** [comment]
We'll ship with full GC disabled just like the prior release. The tests will have GC enabled to flush out such issues. Moving to 6.0.0 Milestone.

**Comment by SamMonoRT** [comment]
@lewing - is this still an issue with GC enabled now ?

**Comment by lewing** [comment]
gc is enabled. closing
