### ISSUE TITLE
Improve error message when attempting prior-knowledge H2C and server returns a HTTP/1.1 response

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#40219]
Copied from PR - https://github.com/dotnet/runtime/pull/39201

Related to this issue - https://github.com/dotnet/runtime/issues/31132

> * If HTTP/2 and no TLS, use HTTP/2 cleartext (H2C)
>   
>   * if the server doesn't support H2 (only recognizes H1) we get protocol error (observed with loopback server)
>   * it's expected behavior as-is now; discussion: [#31132 (comment)](https://github.com/dotnet/runtime/issues/31132#issuecomment-541078587), code: https://github.com/dotnet/runtime/blob/1e23a0629617ab18e259872f8fbb11d3f49efc2d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L199-L211

It would be great if we could improve the error message in this situation. "if the server doesn't support H2" is one situation this error will occur. There is another common, and more confusing reason to get it:

You will see this error if a port on the server has been configured as [Http1AndHttp2](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#listenoptionsprotocols). When a server is configured to support both, but it is not using TLS, then actually it only supports HTTP/1.1. That is because TLS+ALPN is required to negotate which protocol is used, and if TLS is not being used then the server defaults to HTTP/1.1.

It would be great if we could have an error message like "Client attempted to make a prior-knowledge HTTP/2 request to the server, but received an HTTP/1.1 error response. The server may not be configured to use HTTP/2, or require TLS to negotiate a HTTP/2 connection".

This situation is common cause of confusion. A descriptive error message would be a lot more useful than "The response ended prematurely, with at least 9 additional bytes expected."

**Comment by geoffkizer** [comment]
I have a pending change here that will at least give a better error message: "An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake."

Suggestions welcome.

**Comment by geoffkizer** [comment]
BTW, I really hesitate to specifically try to detect an HTTP1.1 response here, as per @stephentoub's comment here: https://github.com/dotnet/runtime/issues/31132#issuecomment-541078587

Hopefully the error message above is enough to point people in the right direction (i.e., the server isn't doing HTTP2).

**Comment by geoffkizer** [comment]
I posted the change with the improved error message, please take a look

**Comment by JamesNK** [comment]
> BTW, I really hesitate to specifically try to detect an HTTP1.1 response here

Ok. What I asked for was the ideal, but I understand why interpreting unexpected bytes is educated guessing and you don't want to do it.

A more user friendly error message that describes what failed is good enough. It is something that can be searched for and docs/StackOverflow can go into more detail.

**Comment by scalablecory** [comment]
I think the improved exception message is a good start, but I feel like this should be cheap and reliable enough to detect.

If we get back a response like `HTTP/1.1 ...\r\n` -- `HTT` decodes to a frame length that is invalid, and `P` is not a valid frame type when we would be expecting a SETTINGS frame. If we detect this we could throw an exception with language like "the server may be HTTP/1.1".

**Comment by geoffkizer** [comment]
@scalablecory Sure, that seems worth looking in to. Regardless, I think this is a worthwhile change.
