### ISSUE TITLE
HttpClient with different configurations and the TIME_WAIT problem

### ISSUE THREAD

**Issue by Hulkstance** [dotnet/runtime#40217]
I have a .NET Core 3.1 application which performs multiple requests with different proxy configurations known at runtime. Let's say the proxies are around 10000.

I would need multiple instances of HttpClient for each proxy and each proxy is basically an additional socket. I can definitely take an advantage of HttpClient's pooling because I'm able to use one proxy for like 5 requests, before it gets blocked by API limitations.

HttpClient is known with its socket exhaustion and not being able to handle DNS recycling as singleton. That causes serious performance issues. There are multiple articles into that. Of course there are ways to solve the socket exhaustion: a singleton of HttpClient (not a solution in my case, because I need to set a different proxy for each request/per 5 requests); keep-alive to false (`client.DefaultRequestHeaders.ConnectionClose = true`), which kinda solves the socket exhaustion but not the DNS recycling; `ServicePoint's ConnectionLeaseTimeout` would've worked before, but not anymore, because HttpClient is not affected by it. The DNS recycling could've been solved by `ServicePointManager.DnsRefreshTimeout` before, but not anymore.

I'm aware of two options:
- SocketsHttpHandler - I will have to create multiple instances of it, because of the different proxies, but I can still take advantage of the pooling, because I can execute 5 requests with same proxy (until it gets limited by the API).

```csharp
var socketsHandler = new SocketsHttpHandler
{
    PooledConnectionLifetime = TimeSpan.FromMinutes(10),
    PooledConnectionIdleTimeout = TimeSpan.FromMinutes(5),
    MaxConnectionsPerServer = 10
};

var client = new HttpClient(socketsHandler);
```

- IHttpClientFactory with named clients - it solves the socket exhastion and DNS recycling but it's useless, simply because I don't know the proxies at compile-time. I have them at runtime. 

What is the worthiest solution in this case? 

My sample code:
```csharp
private async Task TestAsync(string proxy = null)
{
    using var handler = new HttpClientHandler();

    if (proxy != null)
    {
        handler.Proxy = new WebProxy(proxy, true);
    }

    using var client = new HttpClient(handler);
    client.DefaultRequestHeaders.ConnectionClose = true;

    using (var request = new HttpRequestMessage(HttpMethod.Get, "http://aspnetmonsters.com"))
    {
        using var response = await client.SendAsync(request).ConfigureAwait(false);

        if (response.IsSuccessStatusCode)
        {
            string content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
        }
    }
}

async Task ExecuteAsync()
{
    string randomProxy = string.Empty;

    for (int i = 0; i < 10; i++)
    {
        await TestAsync(randomProxy).ConfigureAwait(false);
    }
}
```

**Comment by scalablecory** [comment]
It looks like you could implement a custom `IWebProxy` that hands out a random proxy for each URL queried.

`SocketsHttpHandler`, the default implementation of `HttpClient`, will pool connections based on proxy anyway. So, creating one `HttpClient` per proxy will be no different in terms of socket resource usage than a single `HttpClient` with multiple proxies.

**Comment by Hulkstance** [comment]
@scalablecory, thanks for your answer! That's what I did:

```csharp
/// <summary>
/// A wrapper for <see cref="FlurlClient"/>, which solves socket exhaustion and DNS recycling.
/// </summary>
public class FlurlClientManager : IFluentClientManager
{
    /// <summary>
    /// Static collection, which stores the clients that are going to be reused.
    /// </summary>
    private static readonly ConcurrentDictionary<string, IFlurlClient> _clients = new ConcurrentDictionary<string, IFlurlClient>();

    /// <summary>
    /// Gets all clients.
    /// </summary>
    /// <returns>The clients.</returns>
    public ConcurrentDictionary<string, IFlurlClient> GetClients()
        => _clients;

    /// <summary>
    /// Gets a client by client name.
    /// </summary>
    /// <param name="clientName">The client name.</param>
    /// <returns>The <see cref="FlurlClient"/>.</returns>
    public IFlurlClient GetClient(string clientName)
        => _clients[clientName];

    /// <summary>
    /// Creates a new client.
    /// </summary>
    /// <param name="clientName">The client name.</param>
    /// <param name="proxy">The proxy URL.</param>
    /// <returns>The <see cref="FlurlClient"/>.</returns>
    public IFlurlClient CreateClient(string clientName, string proxy = null)
    {
        return _clients.AddOrUpdate(clientName, CreateClient(proxy), (_, client) =>
        {
            return client.IsDisposed ? CreateClient(proxy) : client;
        });
    }

    /// <summary>
    /// Disposes a client. This leaves a socket in TIME_WAIT state for 240 seconds but it's necessary in case a client has to be removed from the list.
    /// </summary>
    /// <param name="clientName">The client name.</param>
    /// <returns>Returns true if the operation is successful.</returns>
    public bool DeleteClient(string clientName)
    {
        var client = _clients[clientName];
        client.Dispose();
        return _clients.TryRemove(clientName, out _);
    }

    private IFlurlClient CreateClient(string proxy = null)
    {
        // PooledConnectionLifetime default is infinity.
        // PooledConnectionIdleTimeout default is 2.
        // MaxConnectionsPerServer default is int.MaxValue.
        var handler = new SocketsHttpHandler()
        {
            Proxy = proxy != null ? new WebProxy(proxy, true) : null,
            AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
        };

        var client = new HttpClient(handler);

        return new FlurlClient(client);
    }
}
```

**Comment by stephentoub** [comment]
Closing as addressed / answered. Thanks.
