### ISSUE TITLE
CoreRun and hostpolicy are not in bin/testhost

### ISSUE THREAD

**Issue by pgovind** [dotnet/runtime#40215]
I think this is related to recent changes in the infrastructure to make testhost more closely aligned to the shipping product. 

1. Running the performance benchmarks needs CoreRun to be in the `testhost` (though this can be fixed in the perf repo I'm guessing) folder. 

2. Sometimes I also run into `A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\repos\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\5.0.0'` though I'm not certain if this is something messed up in my environment. 

For both these issues, copying the dlls from elsewhere into testhost works, so this is not a pressing issue.

cc @ViktorHofer @safern

**Comment by danmosemsft** [comment]
#1 breaks the documented workflow in the perf repo, as per linked issue.

**Comment by ViktorHofer** [comment]
Submitted a fix: https://github.com/dotnet/runtime/pull/40341. Sorry the inconvenience this caused.

**Comment by adamsitnik** [comment]
I verified that it works again, thanks!

![obraz](https://user-images.githubusercontent.com/6011991/89389934-5b508280-d706-11ea-8fe7-59658c81c686.png)
