### ISSUE TITLE
The inner array in ArraySegment should not be nullable

### ISSUE THREAD

**Issue by aalmada** [dotnet/runtime#40233]
### Description

Both the [field `_array`](https://github.com/dotnet/runtime/blob/5de3b209853637b63546460e4a67cc82c4ac75fd/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L36) and the [property `Array`](https://github.com/dotnet/runtime/blob/5de3b209853637b63546460e4a67cc82c4ac75fd/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L63) in `ArraySegment` are declared as `T[]?`. 

The field is only assigned in the constructors and [both throw if the value is `null`](https://github.com/dotnet/runtime/blob/5de3b209853637b63546460e4a67cc82c4ac75fd/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L40).

This makes the implementation of `ArraySegment` more complex, its uses much more cumbersome and reduces significantly its performance. So much so that its own implementation assumes the field is never `null` at the following places: 
* [Line 78](https://github.com/dotnet/runtime/blob/5de3b209853637b63546460e4a67cc82c4ac75fd/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L78)
* [Line 87](https://github.com/dotnet/runtime/blob/5de3b209853637b63546460e4a67cc82c4ac75fd/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L87)

There's really no need to be nullable.

 

### Configuration

* Which version of .NET is the code running on?
.NET 5.0

**Comment by aalmada** [comment]
@jeffhandley

**Comment by benaadams** [comment]
Can create it with `default` or by not initializing in a class field when it would be null?

**Comment by mburbea** [comment]
Since it's a struct it defaults to null. In those cases, the range check would prevent you from getting to it as any value would be greater than the default count of 0.

**Comment by jkotas** [comment]
> reduces significantly its performance.

Why do you think this reduces ArraySegment performance?

**Comment by aalmada** [comment]
Ok, I missed the default struct constructor issue. It's true is can be `null`. 😔

I mentioned performance because of all the required validations. In the struct implementation and when using it. There's no other solution so please forget about it. 

IMHO the two missing validations should still be fixed.

**Comment by aalmada** [comment]
Sorry, `index > count`...

**Comment by GrabYourPitchforks** [comment]
> IMHO the two missing validations should still be fixed.

The validations are correct. If the struct is initialized with `default`, then the fields will be:

*_array* = null
*_offset* = 0
*_count* = 0

The only way for the `if ((uint)index >= (uint)_count)` check to pass at all would be for the struct to have been created from a non-empty array, at which point we can assume that ctor validation succeeded and the *_array* backing field is non-null.

(I'm ignoring torn structs for the sake of this argument, as they bring their own problems.)
