### ISSUE TITLE
The options subsystem needs linker attributes to preserve constructors on options types

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#40236]
### Description

Looking into what it means to takes to make ASP.NET Core more linkable once we get this (https://github.com/dotnet/runtime/pull/40227) and (https://github.com/dotnet/aspnetcore/pull/24458), options is the next big hurdle to cross. The issue is the very similar to DI in that the option system creates instances but the linker doesn't understand that and removes constructors from the poco objects.

```C#
public class MyOptions
{
    public int Value { get; set; };
}
```

```C#
var services = new ServiceCollection();
services.AddOptions();
services.Configure<MyOptions>(o =>
{
     o.Value = 100;
});
var service= services.GetService<IOptions<MyOptions>>();
var value = service.Value;
```

Linking this should preserve `MyOptions` constructors.

This matters for:
- `IOptions<T>`
- `IOptionsMonitor<T>`
- `IOptionsSnapshot<T>`

cc @eerhardt

**Comment by davidfowl** [comment]
Just realized this is the exact same problem as `Lazy<T>` and I checked and it has been annotated appropriately 😄 https://github.com/dotnet/runtime/blob/de1f8d847ee3ac635affa5296b163691ef8612f6/src/libraries/System.Private.CoreLib/src/System/Lazy.cs#L186

**Comment by davidfowl** [comment]
@eerhardt who do I need to bribe to get this into 5? My boss? 😄

**Comment by marek-safar** [comment]
You can submit PR yourself. Doing quick check it could be enough to annotate OptionsFactory::Create method

**Comment by eerhardt** [comment]
I'm working on it. I'll probably have a PR out today.

>  it could be enough to annotate OptionsFactory::Create method

Unfortunately this isn't enough.
