### ISSUE TITLE
X509Certificate2 authorityKeyIdentifier extension has different format value for Windows and Linux

### ISSUE THREAD

**Issue by dhhoang** [dotnet/runtime#40240]
### Description
I have a use case where I need to filter multiple X509 certificates by the value of the `authorityKeyIdentifier` extension.  When I try to get extension value using the `X509Certificate2` class, the return value is different between Windows and Linux (for the same certificate file).
* Take the repro code at: https://github.com/dhhoang/x509-authKid-repro
* The `me.crt` file is a certificate generated using Openssl on Linux.
* When running it, the return values are:
    * On Windows: `KeyID=09fcb692f80ab3c03367221ccc68aa66fced2e8f, Certificate Issuer: Directory Address:E=org1@compA.com, CN=org1, OU=Org1, O=CompA, L=SEA, S=WA, C=US, Certificate SerialNumber=00ffa226d6b1c399a8`
    * On Linux: `keyid:09:FC:B6:92:F8:0A:B3:C0:33:67:22:1C:CC:68:AA:66:FC:ED:2E:8F`. 

Other than the issue that the value on Linux does not have the issuer's info, the format of the `KeyID` is also different. Is there any reason for this difference?
### Configuration
* .NET Core 3.1
* Windows 10 1909, Linux 4.14.186-146.268.amzn2.x86_64
* Arch: x86
* Do you know whether it is specific to that configuration: Unlikely.

### Other information
Output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     amzn
 OS Version:  2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by bartonjs** [comment]
We let the OS pretty-print the extensions, and Windows and OpenSSL have decided to print them differently.

This is tracked at a higher level as #15445.  If you want to interpret the data out of the extension, don't use the string form, use the new System.Formats.Asn1 package and the AsnReader class to interpret the data.
