### ISSUE TITLE
Some tests are timing out under GCStress

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#40250]
failed in job: [runtime-coreclr gcstress-extra 20200802.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=754417&view=ms.vss-test-web.build-test-results-tab&runId=23408646&resultId=110537&paneView=debug)

failed tests:
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest1234\\Generated1234\\Generated1234.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest927\\Generated927\\Generated927.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest560\\Generated560\\Generated560.cmd
JIT\\CodeGenBringUpTests\\DblAdd_r\\DblAdd_r.cmd

Error message
~~~
cmdLine:D:\h\w\A40E0951\w\B0F10980\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1234\Generated1234\Generated1234.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 8/2/2020 4:22:33 PM, end: 8/2/2020 5:52:33 PM)

Return code:      -100
Raw output file:      D:\h\w\A40E0951\w\B0F10980\e\Loader\classloader\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest1234\Generated1234\Generated1234.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A40E0951\p\corerun.exe" Generated1234.dll 

cmdLine:D:\h\w\A40E0951\w\B0F10980\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1234\Generated1234\Generated1234.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 8/2/2020 4:22:33 PM, end: 8/2/2020 5:52:33 PM)
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=D:\h\w\A40E0951\p
> D:\h\w\A40E0951\w\B0F10980\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1234\Generated1234\Generated1234.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1234_Generated1234_Generated1234_._TypeGeneratorTests_TypeGeneratorTest1234_Generated1234_Generated1234_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Loader.classloader\Loader.classloader.XUnitWrapper.cs:line 138850
~~~

**Comment by BruceForstall** [comment]
The set of timeout failures is not consistent. Following your manual trigger run were to scheduled runs:

https://dev.azure.com/dnceng/public/_build/results?buildId=783747&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=784328&view=ms.vss-test-web.build-test-results-tab

There was one non-timeout failure:

Interop\COM\NETClients\Primitives\NETClientPrimitives\NETClientPrimitives.cmd

Given that the timeout is 1.5 hours per test, if these are actually that slow, perhaps they should just be disabled. The scenarios where they time out are very slow scenarios: HeapVerify=1 + ZapDisable or JITMinOpts or sometimes JitStress.

**Comment by mangod9** [comment]
should we just ignore timeouts as part of these runs and not open issues? Have any of such timeout failures been actionable?

**Comment by mangod9** [comment]
assume this is not a frequent occurrence anymore? Do we need to keep this issue?

**Comment by BruceForstall** [comment]
I'll close and we can see if it comes back.

**Comment by mangod9** [comment]
thanks!
