### ISSUE TITLE
3.0.100 Segmentation Fault on Ubuntu virtual server 16.04.6 LTS

### ISSUE THREAD

**Issue by choXberg** [dotnet/runtime#40272]
Problem occurs on two virtual server with ubuntu 16.04, followed the installation guide for 16.04  at
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
 
all dependencies installed via package manager.

sometimes i got a segmentation fault (seems to happen randomly) for dotnet --info
i am connected to both servers with ssh as normal user, not as root

```
cho@XXX:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
Segmentation fault

```
and i cannot build on both machines for a new project (dotnet new mvc):
```
cho@XXX:~/tmp/mvc$ dotnet build
Segmentation fault
```

second time the build freezes the remote shell:

```
cho@XXX:~/tmp/mvc$ dotnet build
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

and both cpu threads are running dotnet tasks, but only at max 3% and they are never stopping.

```
top - 07:27:29 up 15:30,  0 users,  load average: 0,03, 0,08, 0,03
Tasks:  34 total,   1 running,  33 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,8 us,  1,0 sy,  0,0 ni, 98,2 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem :  4194304 total,  2097420 free,   831720 used,  1265164 buff/cache
KiB Swap:  4194304 total,  4186664 free,     7640 used.  3200732 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                   
 6830 cho       20   0 14,835g  58904  26308 S   3,0  1,4   0:07.89 dotnet                                                                                                                                                                    
 6811 cho       20   0 14,849g  46404  24776 S   1,7  1,1   0:03.88 dotnet   

```
i installed 3.0.100 on 4 machines: 
2x dedicated (3.0.100 runs fine) development and production
2x virtual server (segmentation fault) jenkins, and qa server
so i guess it has something to do with the virtual server setup?

virtual server with broken dotnet 3.0.100:

```
cho@XXX:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

```

```
cho@XXX:~$ uname -a
Linux XXX 4.4.0-042stab139.1 dotnet/core#1 SMP Tue Jun 18 12:51:14 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux
```

dotnet 3.0.100 runs fine at:
```
cho@YYY:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic


```
dotnet 2.2 is fine for all 4 systems 
any help is welcome :)

**Comment by jeffschwMSFT** [comment]
@JerryJoyce we would need a core dump or some additional information to help diagnose what is happening.  We have made a number of reliability fixes in .NET Core 3.1.*.  Can you try the latest?

**Comment by mangod9** [comment]
@choXberg @JerryJoyce please let us know if this repros on 3.1.7, which has had a few reliability fixes, else we can close this issue. Thanks!

**Comment by choXberg** [comment]
@mangod9 - I do not have any segmentation faults issues anymore with dotnet core on linux host and linux virtual machine 

ubuntu linux 3.1.403

I would say we can close this ticket.

Thank you

**Comment by mangod9** [comment]
great thanks for your response. Closing this for now.
