### ISSUE TITLE
Add option to JsonStringEnumConverter for parsing strings but export numbers

### ISSUE THREAD

**Issue by YehudahA** [dotnet/runtime#40284]
[Sorry for my bad English]

## Background and Motivation

I migrated an existing api project to aspnet3.1, and I prefere to use the new ```System.Text.Json``` serialization.

Fore compatiblity, I have to support submitting enums string.
If I configure the project with ```JsonStringEnumConverter```, it parsed strings as well, but it also configure the project to serial enums as string.

## Minimal sample

``` C#
    public sealed class TestJsonController : Controller
    {
        [HttpPost]
        public ActionResult TestEnum([FromBody] MyModel model)
        {
            if (model is null)
            {
                return BadRequest();
            }

            return Json(model);
        }
    }

    public sealed class MyModel
    {
        public DayOfWeek Day { get; set; }
    }
```

If I send this body:

``` JSON
{
    "day": "Sunday"
}
```

I get 400.

If i register ```JsonStringEnumConverter``` like this:

``` C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers()
        .AddJsonOptions(opts => opts.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter())
    );
}
```
I get this response:

``` json
{
    "day": "Thursday"
}
```

## Proposed API

Please add this public contructor to ```JsonStringEnumConverter```

``` C#
public JsonStringEnumConverter(JsonNamingPolicy namingPolicy = null, bool allowIntegerValues = true, exportAsNumbers = false);
```
If ```exportAsNumbers == true```, then the converter can parsing strings, but it doesn't change the serialization.

## Usage Examples

``` C#
 services.AddControllers()
        .AddJsonOptions(opts => opts.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(exportAsNumbers : true))
    );
```

**Comment by YehudahA** [comment]
> regardless of the merits of your idea, I would normally prefer string enums, rather than an integer code. Especially, is there a reason why you want to return a different type of value than you receive? It means that callers cannot just give you what they have received.

Integer values are the default behavior of  aspnetcore, and I don't want to change it.
However, i have to support some legacy client, which uses string values.

**Comment by YehudahA** [comment]
Meanwhile, I wrote for me this converter:

``` C#
public sealed class EnumParsingConverter : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert) => typeToConvert.IsEnum;

    public override JsonConverter CreateConverter(Type type, JsonSerializerOptions options)
    {
        JsonConverter converter = (JsonConverter)Activator.CreateInstance(
            typeof(DictionaryValueConverterInner<>).MakeGenericType(
                new Type[] { type }));

        return converter;
    }

    private sealed class DictionaryValueConverterInner<TValue> : JsonConverter<TValue> where TValue : struct, Enum
    {
        public override TValue Read(
            ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Number)
            {
                var numberValue = reader.GetInt32();
                return (TValue)(object)numberValue;
            }

            if (reader.TokenType == JsonTokenType.String)
            {
                var valueString = reader.GetString();

                if (Enum.TryParse(valueString, ignoreCase: false, out TValue value)
                    || Enum.TryParse(valueString, ignoreCase: true, out value))
                {
                    return value;
                }

                throw new JsonException(
                    $"Unable to convert \"{valueString}\" to Enum \"{typeof(TValue)}\".");

            }

            throw new JsonException();
        }

        public override void Write(
            Utf8JsonWriter writer,
            TValue value,
            JsonSerializerOptions options) => writer.WriteNumberValue((int)(object)value);
    }
}
```

**Comment by Clockwork-Muse** [comment]
>Integer values are the default behavior of aspnetcore, and I don't want to change it.
>
>However, I have to support some legacy client, which post string values.
>These legacy project, uses newthonsoft.json, and can parse enum interger values as well.
>
>So, the best solution is using integer values by default, and suppoort string parsing.

... my _guess_ would be that the default behavior is due to the fact that enums are backed by an integer field of sorts.  Do note that  using an integer code will render your messages less readable (will require a documentation check).
