### ISSUE TITLE
Consider reference counter as alternative garbage collector

### ISSUE THREAD

**Issue by mirhagk** [dotnet/runtime#4029]
Tracing garbage collection is great for throughput and C# has a pretty well tuned garbage collector (even if it's a little out of date w.r.t. academic papers). But there are scenarios where throughput does not matter as much as consistent predictable performance, or scenarios that use a lot of memory and can't afford to pay the price of a tracing collector in either pausing or memory consumption.

Video games are a very common situation where tracing collection can be disastrous, and a lot of programmers have to work around this with object pools and the like, essentially managing memory themselves.

It'd be nice if it was possible to swap out the garbage collector in .NET (like it is possible with many java implementations), and a reference counter would be a useful one to swap out for. Of course it should not change any guarantees that the language has (so there'll have to be a backup cycle collector) but merely change throughput, pausing, performance and memory consumption.

This would obviously be a very big change, as the GC is very tuned, and quite a lot of code, and the new reference GC would need to be able to hook in to assignments and variable scope, but it has the potential to make C# that much more attractive to certain scenarios (such as game programming).

Alternatively this could be a consideration for .NET native only, as .NET native already seeks to reduce memory consumption on constrained devices, and reference counting has many similar goals. This is basically a request to consider reference counting as an alternative garbage collector somewhere in the .NET ecosystem

**Comment by lostmsu** [comment]
I think ARC can transparently be used for any classes, that provably do not have cycles. ARC classes can only contain fields of:
- unmanaged types
- types that previously were determined to be ARC-compatible
- maybe also arrays of types previously determined to be ARC-compatible

They also must be sealed or carry a special attribute, that would prevent adding any non-ARC fields when the type is inherited from.

This outright would apply to `System.String`, and any handle classes.

As long as it does not contradict current behavior, I would simply call their finalizer the second their reference count drops to zero (I realize there might be a problem with resurrection, which may need another bit for finalization).

**Comment by richlander** [comment]
There is no plan to adopt ARC. I'm going to close this issue as a result.
