### ISSUE TITLE
Don't throw OperationCanceledException in Host.StopAsync

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#40290]
We shouldn't be throwing in `Host.StopAsync` when the token is canceled and instead let the hosted services and host lifetime run.

We should remove
https://github.com/dotnet/runtime/blob/df7f985f44712efd46b8b3bc5e4d83fe3d83ed4b/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L79
and
https://github.com/dotnet/runtime/blob/df7f985f44712efd46b8b3bc5e4d83fe3d83ed4b/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L91
and add a try catch around
https://github.com/dotnet/runtime/blob/df7f985f44712efd46b8b3bc5e4d83fe3d83ed4b/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L92
and add it to the `AggregateException`

Discussion about this at https://github.com/dotnet/aspnetcore/pull/24279#issuecomment-668208979

cc @Tratcher @halter73

**Comment by huoyaoyuan** [comment]
Related: #39085

**Comment by Marusyk** [comment]
I will try to prepare PR for this
