### ISSUE TITLE
TimeSpan.Parse of 24 hours instead of 1 day gives 24 days

### ISSUE THREAD

**Issue by adambajguz** [dotnet/runtime#40316]
I come up with an issues with TimeSpan.Parse(string)

`System.TimeSpan.Parse("24:00:00")` results in `[24.00:00:00]` instead of an overflow error or just 1 day.
(This was tested on .NET Core 3.1)

`System.TimeSpan.Parse("00:60:00")` results in `System.OverflowException` and I think the same should happen in the case of `System.TimeSpan.Parse("24:00:00")`

**Comment by adambajguz** [comment]
Generalizing: ` System.TimeSpan.Parse("N:00:00")` for N >= 24 is treated as  `System.TimeSpan.Parse("N.00:00")`

**Comment by GrabYourPitchforks** [comment]
Repros in .NET 5.0 RC1 and .NET Framework 4.8.

**Comment by danmosemsft** [comment]
Documented behavior.
