### ISSUE TITLE
System.Threading.Channels - Stack-like Behavior

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#40311]
Currently System.Threading.Channels operates much like a queue: FIFO.
I essentially need a LIFO channel.
Can another parameter be added to the constructor args that determine whether it is FIFO or LIFO?

**Comment by benaadams** [comment]
`ConcurrentStack<T>`?

**Comment by TonyValenti** [comment]
@benaadams A ConcurrentStack doesn't operate the same way a channel does.  Just as a ConcurrentQueue isn't the same as a channel.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  I'm going to close this as a dup of https://github.com/dotnet/runtime/issues/32700, as if we were going to add such support, that's how we'd do it.  It'd be helpful if you could add your scenario to that issue, and in particular why you need LIFO behavior here.
