### ISSUE TITLE
How to query signed in user's security groups

### ISSUE THREAD

**Issue by youn123** [dotnet/runtime#40317]
@joperezr 

Is there a way to query the list of Active Directory security groups that the currently signed in user is a member of using the `System.DirectoryServices` or `System.DirectoryServices.AccountManagement` API?
By currently signed in, I mean the user signed in to the machine (as shown in the screenshot).

<img width="399" alt="ad" src="https://user-images.githubusercontent.com/19635090/89316786-638abe00-d631-11ea-919d-65028c6c0082.PNG">

Thank you.

**Comment by SteveSyfuhs** [comment]
You're asking to query the user's group membership from AD, but show that you're connected to Azure AD. Which one are you actually trying to query here?

**Comment by youn123** [comment]
I think I had a misunderstanding of how AD and Azure AD work and now realize my question doesn't apply here. Thanks for replying. I'm closing the issue.
