### ISSUE TITLE
HttpClient set headers error

### ISSUE THREAD

**Issue by OverQuartzer** [dotnet/runtime#40320]
var client = new HttpClient {Timeout = new TimeSpan(0, 0, 30)};
 client.DefaultRequestHeaders.From = "ENSURE";

errorinfo:The specified value is not a valid 'From' header string.

i want set From  =  "ENSURE",but It reported a mistake

**Comment by mkArtakMSFT** [comment]
@ericstj is HttpClient something your team owns?

**Comment by geoffkizer** [comment]
This behavior is by design. As mentioned above, the right way to do this is to use TryAddWithoutValidation.

**Comment by OverQuartzer** [comment]
> I have a solution:
> 
> ```cs
> client.DefaultRequestHeaders.TryAddWithoutValidation("From", "ENSURE");
> ```
> 
> The error _The specified value is not a valid 'From' header string_ was thrown because value of 'From' should be a email string.
> See [RFC 2616](https://tools.ietf.org/html/rfc2616#page-128)
> 
> > The From request-header field, if given, SHOULD contain an Internet
> > e-mail address for the human user who controls the requesting user
> > agent.
> 
> The best practice is to add an 'x-from' header
> 
> ```cs
> client.DefaultRequestHeaders.Add("x-from", "ENSURE");
> ```

thank you ,TryAddWithoutValidation is ok!
