### ISSUE TITLE
Potentially unnecessary check in DelayPromise constructor (Task.Delay)

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#40335]
https://github.com/dotnet/runtime/blob/1e961bab56f33b7b5179b9a70ca0724428d1b8af/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5385-L5391

I don't see how this race condition is possible. This is in the DelayPromise constructor. DelayPromiseWithCancellation derives from DelayPromise and calls DelayPromise's constructor via : base(millisecondsDelay). This means DelayPromise's constructor will complete before DelayPromiseWithCancellation's constructor (which registers the cancellation) even starts.

**Comment by tarekgh** [comment]
CC @benaadams who originally introduced this code. 

CC @stephentoub

**Comment by stephentoub** [comment]
The line before this starts the timer, which may cancel this instance. This code is valid. What is the concern?

**Comment by WizardBrony** [comment]
@stephentoub Ah, I see now. I thought the comment was referring to the CancellationToken cancelling, not the Timer executing. Thank you for the clarification.

**Comment by WizardBrony** [comment]
@stephentoub Actually, then shouldn't it be IsCompleted instead of IsCanceled? CompleteTimedOut calls TrySetResult not TrySetCanceled

**Comment by stephentoub** [comment]
> then shouldn't it be IsCompleted instead of IsCanceled?

Probably.

**Comment by benaadams** [comment]
It should be moved down to the the `DelayPromiseWithCancellation` class

**Comment by benaadams** [comment]
No this is correct. It's the race with the `DelayPromiseWithCancellation` subtype which may cancel the Task via `CompleteCanceled()` before the timer is created

**Comment by benaadams** [comment]
However the base .ctor will run before the `CompleteCanceled` can be called in the subclass so it unnessary?

**Comment by WizardBrony** [comment]
@benaadams My initial comment was incorrect: It is necessary. The following line comes directly before the logic in question:

https://github.com/dotnet/runtime/blob/1e961bab56f33b7b5179b9a70ca0724428d1b8af/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5384

As @stephentoub mentioned, it is possible that the timer may fire and call CompleteTimedOut before _timer is assigned:

https://github.com/dotnet/runtime/blob/1e961bab56f33b7b5179b9a70ca0724428d1b8af/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5395-L5409

If that occurs, _timer may still be null when Cleanup is called, so _timer?.Close() may not get called. The logic in the constructor makes sure that it does. However, I believe the statement should be `if (IsCompleted)` instead of IsCanceled because CompleteTimedOut calls TrySetResult, not TrySetCanceled.

**Comment by benaadams** [comment]
Added fix https://github.com/dotnet/runtime/pull/40356
