### ISSUE TITLE
.NET 5 SDK acquisition should mention WSL issues with snap

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#40331]
https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.7-install-instructions.md

The preferred method of installing .NET 5 SDK previews is using `snap`. That tool has issues with WSL2 though (and doesn't work at all with WSL1). Given the number of people using WSL2 to develop on Linux seems like we should be using our install instructions to point people to the work arounds for WSL2 vs. having them spend time googling for it. 

This is the best answer I could find but given the steps involved I gave up and went back to the second preferred method

https://forum.snapcraft.io/t/running-snaps-on-wsl2-insiders-only-for-now/13033

**Comment by NikolaMilosavljevic** [comment]
@leecow we should document this as a known issue and anywhere we're pointing to Snap support, including Previews.

**Comment by jongio** [comment]
I agree.  Just wasted a bunch of time trying to get this to work.  Let's get the doc updated to state Snap method doesn't work with WSL2.  Want a PR?

azsdke2e

**Comment by NikolaMilosavljevic** [comment]
[Triage] @adegeo can this be added to our Snap documentation?

**Comment by adegeo** [comment]
Sure. I have a PR that is moving snap to its own article and I can add a note there.

**Comment by adegeo** [comment]
This warning has been published.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
