### ISSUE TITLE
Mono runtime allows running module ctor and class ctors multiple times through reflection

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#40351]
As part of fixing bug #1748 it was discovered that reflection can execute module and class constructors multilple times. As this violates a number of the assumptions that the JIT is taking around behavior of readonly static fields, it was decided to disable that behavior.

The Mono runtime currently allows the class/module constructors to execute multiple times. This bug exists to track that difference and make it simple to disable the new test that checks to verify that such constructors do not run repeatedly.

**Comment by jkotas** [comment]
Fixed by #73955
