### ISSUE TITLE
Suggestions on the encoding function of System.IO.Ports

### ISSUE THREAD

**Issue by dsyx** [dotnet/runtime#40364]
Currently, users need to provide an Encoding value (ASCII by default) when using the serial port. However, for IoT applications, the data obtained from the serial port is often unencoded (ie, HEX). For example, when I want to read an 8-bit data (such as 0xAA), I need `sp.Encoding = Encoding.GetEncoding(1252);`. Linux users probably don't know what the code page `1252` means.

I suggest to provide a "no encoding" option (default if possible). Use the original byte data when reading/writing.

**Comment by krwq** [comment]
@dsyx can you show how do you read/write data where you encounter problems? When reading bytes encoding should not matter

**Comment by dsyx** [comment]
![image](https://user-images.githubusercontent.com/34703581/89388366-7f2bbc80-d736-11ea-9387-0b6b63b2d9c7.png)
Under the default encoding, AA becomes 3F. @krwq

**Comment by krwq** [comment]
@dsyx using `char` implies some encoding of characters (in order to convert them to bytes). Bytes are what is being transferred over the wire. Try using:

```csharp
_sp.Write (new byte[] { 0xAA, 0x3F, 0x3F }, 0, 3);
```

**Comment by dsyx** [comment]
@krwq  Thanks.
