### ISSUE TITLE
Invalid use of Unsafe.As in System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#40366]
https://github.com/dotnet/runtime/blob/a4f15bff674160b592e66865247cc73419835805/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L258 is invalid use of `Unsafe.As`.

`Unsafe.As` cannot be used to cast object to a type that it is not assignable to and then hand the reference of invalid type out.

Please do not use `Unsafe.As` unless it is really required. Having an extra static field of the right type is both more correct and also likely cheaper than `Unsafe.As`.

**Comment by tarekgh** [comment]
Thanks @jkotas. it is me who introduced this code. I was trying to avoid introducing extra static field. but I understand your point. wil fix that.

**Comment by tarekgh** [comment]
This is will be addressed as part of https://github.com/dotnet/runtime/pull/40362

**Comment by tarekgh** [comment]
This is fixed by the linked PR
