### ISSUE TITLE
Memory leak in HttpClient in combination with WebProxy

### ISSUE THREAD

**Issue by loadinganimation** [dotnet/runtime#40369]
We are experiencing a memory leak using HttpClient in combination with a WebProxy. The memory leak is only present, if .NET Framework 4.8 is installed (System.Net.Http.dll 4.8.4084.0). Our application runs fine with .NET Framework 4.7.2 (System.Net.Http.dll 4.7.3056.0).

Without the use of a proxy, the memory leak could not be reproduced.

We made serveral memory dumps and analysed them using dotMemory. It seems like the HTTP connections are not correctly garbage collected. 

[
![memoryleak](https://user-images.githubusercontent.com/58587944/89389651-f72dbe80-d705-11ea-9b94-c7ba5fadf07d.png)
](url)

In code we use a single HttpClient object for multiple requests as well as the current version of the SignalR client for .NET.

The problem also was reproduced by other users in the following closed issue: https://github.com/dotnet/runtime/issues/25197#issuecomment-385540888

**Comment by scalablecory** [comment]
This repo is for .NET Core / .NET 5 only -- as this issue is in Framework, please head over to the VS Community site and file an issue there. Thanks.
