### ISSUE TITLE
StreamReader.EndOfStream throws ObjectDisposedException after Dispose() when leaveOpen is set to true

### ISSUE THREAD

**Issue by kevinrjt** [dotnet/runtime#40372]
I create a StreamReader and set leaveOpen to true, it calls Dispose() and EndOfStream, then it throws `System.ObjectDisposedException: Cannot read from a closed TextReader.` Simple repro code:
```
string path = @"D:\Program.cs";
MemoryStream memoryStream = new MemoryStream(File.ReadAllBytes(path));

StreamReader reader = new StreamReader(memoryStream, Encoding.UTF8, true, 4 * 1024, true);
reader.Dispose();
Console.WriteLine(reader.EndOfStream);
```

The same code works in .NET Core 2.1 and .NET Framework, but not .NET Core 3.1. I believe it's related with this change: https://github.com/dotnet/runtime/commit/0c43b98e0e95d863d963f4ff2844d1491b0cd9f5

Given the leaveOpen option, is this an expected behavior?

**Comment by svick** [comment]
@kevinrjt 

> Given the leaveOpen option, is this an expected behavior?

The `leaveOpen` parameter is about leaving the underlying `Stream` open, it doesn't say anything about accessing members of the `StreamReader` after `Dispose`. Based just on that, I think it's an expected behavior.

Though it could still be worth fixing this, considering that it used to work on previous versions of .Net.

**Comment by danmosemsft** [comment]
Looks like it's from https://github.com/dotnet/coreclr/pull/23725 which has some commentary that alludes to this. In .NET Framework, Dispose() does nothing at all if you have leaveOpen ([src](https://referencesource.microsoft.com/#mscorlib/system/io/streamreader.cs,273)). As a general rule, after you've disposed an object you should not attempt to use it in any way. So the current state is more "correct" and I doubt we would want to loosen it unless there was evidence of widespread breaks.

@kevinrjt is it possible to change your code?

**Comment by kevinrjt** [comment]
Thanks @svick @danmosemsft . I agree that we should not use a disposed object, and leaveOpen is just for the underlying stream instead of the object itself. I'll change our code.

**Comment by danmosemsft** [comment]
Thanks @kevinrjt
