### ISSUE TITLE
system.text.json support for polymorphic serialization.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/runtime#40370]
There has been questions before about polymorphic (de)serialization of json. There is an argument to not support this because it opens a security vulnerability where completely unrelated classes could be instantiated and allow execute of arbitrary code. But why not allow for custom interfaces or types to be used. Just ` Deserialize<IMyInterface>` shouldn't be causing problems?

**Comment by Symbai** [comment]
Dupe of #29937 and #30083, please vote on both and comment on them if you support the same request.

**Comment by layomia** [comment]
Closing as dup of issues @Symbai linked above.
