### ISSUE TITLE
[Mono] Scan the stack for collectible ALC roots 

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#40394]
As part of fixing #13348 I discovered that Mono also has the same bug. Also, I discovered that our test suite is lacking in collectible assembly lifetime tests for the following cases which are known to be handled by the coreclr runtime. I do not know if those cases are handled by Mono.

- Methods on the stack (where there are no heap objects keeping a collectible assembly alive, except for a method on the stack)
- Type parameters for shared generic methods on the stack (For the case of instantiation of generic types not in the collectible assembly which are instantiated over types in the collectible assembly.)
- Delegates to methods in the collectible assembly
- RuntimeMethodHandle, RuntimeFieldHandle, RuntimeTypeHandle, ModuleHandle are also each capable of keeping an the assembly alive

**Comment by MichalStrehovsky** [comment]
Mono's RuntimeHandles (RuntimeTypeHandle/RuntimeFieldHandle/RuntimeMethodHandle) are also IntPtr-based, so I assume they wouldn't keep the underlying assembly alive either.

**Comment by davidwrighton** [comment]
@MichalStrehovsky Good point. I've added that the the list of missing tests in the issue.

**Comment by KevinCathcart** [comment]
@CoffeeFlux

This bug gives a list of circumstances that must keep an assembly uncollected, that are not yet covered by the test suite, and therefore must be tracked separately unless we get tests suite cases added for them. Given that you own the tracking issue for the tests (#34072), I think you might want to have this one too.

Hope this helps.

**Comment by lambdageek** [comment]
I think I've convinced myself that it's at least _possible_ to be safe here with conservative stack scanning, though.  If we have a `MonoMethod*` on the stack (or some other data structure for a class from the ALC), it will be allocated out of the memory manager of the ALC (or in the case of generics, from the memory manager owned by the union of ALCs of the gtd and the params) - so as long as we scan the stack for pointers into the collectible ALCs' memory, we can probably capture all of the above cases.  for constant data and IL bodies, we'd also have to look for pointers into the memmaped MonoImages of the ALC.

It's probably costly to do on every collection. I wonder if we can do this scan of the stack only when we haven't seen any other roots keeping the ALC alive.

**Comment by steveisok** [comment]
I think it's highly unlikely we'll be able to prioritize this work.
