### ISSUE TITLE
Support the Specified convention for serializing and deserializing in System.Text.Json

### ISSUE THREAD

**Issue by pierslawson** [dotnet/runtime#40395]
## Background and Motivation

Both the XmlSerializer and @JamesNK 's  JSON.Net support the convention that whether a property on a class (say property XYZ) should be serialized or has been deserialized can be controlled/reported through a second property on the class (which is named by convention as XYZSpecified). 

See https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.Xml/src/System/Xml/Serialization/ReflectionXmlSerializationWriter.cs#L606

https://github.com/JamesNK/Newtonsoft.Json/blob/6b9f467e817854532ea31e6c08abe47c53ac8b5c/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L533

https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json.Tests/Serialization/ShouldSerializeTests.cs#L217

This allows any code working with the deserialized data to tell the difference between a property that has a default value because the source document didn't have a value, and a document that did have a value but it happened to equal the default value. It also allows any code working with the serializer to optionally decide whether a particular property should be serialized or not (at run time).

This is extremely useful when trying to make an API backwards compatible. Say you add a property "NumberOfChildren" to a"Person" class. New client applications will send in values for how many children the person has, but old client applications won't. However, if your code cannot tell the difference between a new client application setting the property to zero and an old client just not sending the data at all, you could mistakenly overwrite the NumberOfChildren value stored in your database.

## Proposed API

Please have System.Text.Json allow the calling code to optionally (at runtime) decide whether a particular property should be serialized or not on an object by object basis. Also allow the calling code to be able to tell if a property's value is set because it was deserialised or because it is the default value for the property.

## Usage Examples
During serialization:
```
SpecifiedTestClass` c = new SpecifiedTestClass();
c.Name = "James";
c.Age = 27;
c.NameSpecified = false;
var json = JsonSerializer.Serialize(c);
StringAssert.AreEqual(@"{
  ""Age"": 27
}", json);

```
During deserialization:
```
string mikeFullDisclosureString = "{\"Name\": \"Mike Person\", \"NumberOfChildren\": \"0\"}";
var mike = JsonSerializer.Deserialize<FamilyDetails>(mikeFullDisclosureString);
Assert.AreEqual(true, mike.NumberOfChildrenSpecified);
```

## Alternative Designs

Maybe tere is already a way to achieve this that I have missed.

## Risks

Performance overhead of looking for "Specified" properties. Also, most "Specified" properties need to be ignored either by using the JsonIgnore or a convention to ignore them.

**Comment by eiriktsarpalis** [comment]
I believe this could be easily implemented as a third-party extension once #63686 has been completed.

**Comment by KillerBoogie** [comment]
Another generic option would be to have a special value _undefined_ besides the special value _null_. This of course requires a major change for .Net CLI and is probably not a practical option.

**Comment by KillerBoogie** [comment]
Since .Net 5 there is a solution to the problem that this issue tries to solve using Optional\<T\> and a Custom Converter. See https://stackoverflow.com/questions/63418549/custom-json-serializer-for-optional-property-with-system-text-json and https://stackoverflow.com/questions/71024060/distinguish-between-null-and-not-present-using-json-merge-patch-with-netcore-web/71074603#71074603

It took me a few weeks to find this solution and effort to adopt it when <Nullable>enable</Nullable> and <WarningsAsErrors>nullable</WarningsAsErrors> is set. 

Two steps from the .Net team would make it easy to handle this common requirement:

1) Add Optional\<T\> from Microsoft.CodeAnalysis to System and extend it to Optional\<T?\>
2) Add a standard converter for Optional\<T?\>

optional: Add a JsonIgnoreCondition 'WhenOptionalIsUndefined' or 'WhenOptionalHasNoValue'

**Comment by KillerBoogie** [comment]
My proposal hasn't received any feedback. Is this feature already planned for version 7?

**Comment by eiriktsarpalis** [comment]
Per my comment in https://github.com/dotnet/runtime/issues/40395#issuecomment-1012428989, we believe that the feature can be implemented using customized contract resolvers (under proposal https://github.com/dotnet/runtime/issues/63686). We have listed this particular issue as part of the acceptance criteria.

**Comment by KillerBoogie** [comment]
Thanks for your answer. Since Optionals are required for any serious project with access permissions or PATCH Merge commands Optionals should be supported out of the box, without having to write any customized contract resolver.

**Comment by eiriktsarpalis** [comment]
The release of the [contract customization feature](https://github.com/dotnet/runtime/issues/63686) in .NET 7 Preview 6 should make it possible to add support for the `Specified` convention via a custom contract resolver. Here is a functional test demonstrating how it could be implemented:

https://github.com/dotnet/runtime/blob/19588127b93f056eb26616d9d31936df94a9e6d8/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/TypeInfoResolverFunctionalTests.cs#L728-L774

**Comment by eiriktsarpalis** [comment]
Per my earlier comment, adding support for the "Specified" convention should be achievable via contract customization starting in .NET 7. We're not planning on adding out-of-the-box support for this, but it should still be possible for third-party extension libraries to ship contract resolvers offering this functionality.
