### ISSUE TITLE
Add JsonElement.ToObject<T>()

### ISSUE THREAD

**Issue by MikeStall** [dotnet/runtime#40393]
[AB#1166325](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1166325)
## Background and Motivation

We want to fluidly convert between a JsonElement and an object.  

Json.Net supports this (https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_ToObject__1.htm) 

## Proposed API

Add JsonElement.ToObject<T>()  for converting a jsonelement to an object. 

Current workaround is to double deserialize, like  https://stackoverflow.com/a/61047681

```
    public static T ToObject<T>(this JsonElement element, JsonSerializerOptions options = null)
    {
        var bufferWriter = new ArrayBufferWriter();
        using (var writer = new Utf8JsonWriter(bufferWriter))
        {
            element.WriteTo(writer);
        }

        return JsonSerializer.Deserialize<T>(bufferWriter.WrittenSpan, options);
    }
```

see also: https://github.com/dotnet/runtime/issues/31274
## Risks

Risk should be low.  

- This is an additive API, so it shouldn't break anything.  
- Json.Net does this, so the pattern is well understood and used with existing audiences. 
-

**Comment by layomia** [comment]
cc @StephenBonikowsky

**Comment by layomia** [comment]
Related to https://github.com/dotnet/runtime/issues/31274, cc @steveharter.

**Comment by danmoseley** [comment]
@layomia is this still committed for .NET 6?

**Comment by ericstj** [comment]
I think this will be covered by @steveharter's proposal https://github.com/dotnet/runtime/issues/31274.  It permits serialization/deserialization from the new writable DOM.  I believe there are also ways to go from JsonElement to new DOM.

**Comment by steveharter** [comment]
Yes this is covered by  #31274 and is currently under development for 6.0.
