### ISSUE TITLE
Add ForEach() extension method for IEnumerable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#40409]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/990384/add-foreach-extension-method-for-ienumerable.html)._

---
<p>ForEach is an useful method for all sorts of collections but strangely is only present as a direct method of List&lt;T&gt; when it would be useful in all sorts of collections or IEnumerable types. I noticed this when trying to find the method on ObservableCollection&lt;T&gt; (and found it was missing).</p>

---
#### Feedback Bot on 4/14/2020, 11:58 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by ygra** [comment]
I'm not sure much has changed since [Eric Lippert's (IMHO) rather convincing explanation](https://docs.microsoft.com/en-us/archive/blogs/ericlippert/foreach-vs-foreach).

**Comment by eiriktsarpalis** [comment]
The `foreach` keyword provides a much better way to achieve the same effect. I'd be inclined to close this cc @adamsitnik

**Comment by pinkfloydx33** [comment]
My biggest pet peeve is seeing code that does the following:

```csharp
IEnumerable<T> enumerable = GetSomeEnumerable();
enumerable.ToList().ForEach(c => { /* do something */ });
```
I think this is one of the worst antipatterns I come across regularly. There's at best a single array allocation (though likely more) plus the delegate, closure, two method calls and the enumerators. 

At my previous job I wrote an analyzer that designated this pattern  as a compiler error. Adding an extension method on `IEnumerable` smells of the same thing. Please don't do this, let people use `foreach`.

**Comment by eiriktsarpalis** [comment]
Closing since the prefered approach is to use the `foreach` keyword.
