### ISSUE TITLE
APICompat failures on Linux

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#40416]
APICompat is causing failures in PRs that don't change library code on Linux.

```
/__w/1/s/src/libraries/shims/ApiCompat.proj(116,5): error : CannotRemoveAttribute : Attribute 'System.ComponentModel.TypeConverterAttribute' exists on 'System.ComponentModel.MarshalByValueComponent' in the contract but not the implementation.
```

Example: https://github.com/dotnet/runtime/pull/40404

**Comment by safern** [comment]
Finally I was able to get a repro on my private branch that is publishing the artifacts in question, now to investigate: 🎉 

https://dnceng.visualstudio.com/_apis/resources/Containers/4784658/libraries_bin_Linux_arm64_Release?itemPath=libraries_bin_Linux_arm64_Release%2Flibraries_bin_Linux_arm64_Release.tar.gz

**Comment by jkotas** [comment]
@safern @ericstj @danmosemsft This is taking down a large number of PRs. Can we prioritize getting it fixed?

**Comment by am11** [comment]
Made a similar fix for `SuppressGCTransitionAttribute`, by listing it in `eng/DefaultGenApiDocIds.txt`. Not sure if it is applicable to `TypeConverterAttribute`.

**Comment by safern** [comment]
> @safern @ericstj @danmosemsft This is taking down a large number of PRs. Can we prioritize getting it fixed?

This is my top priority, I added logging to APICompat and ran multiple builds from a branch using APICompat... now looking at the logs and trying to find the reason behind it. It seems like a race condition... if I can't fix this today I can baseline the errors temporarily until I found the fix. 

> Made a similar fix for SuppressGCTransitionAttribute, by listing it in eng/DefaultGenApiDocIds.txt. Not sure if it is applicable to TypeConverterAttribute.

We don't want to do this as that means that we don't check those attributes in between ref and implementation, so we would loose coverage for individual libraries.

**Comment by danmosemsft** [comment]
> . if I can't fix this today I can baseline the errors temporarily until I found the fix.

@safern what do you tihnk about putting up a PR to do this while you work on it? I think you could reasonabledirect-submit it if it's just an edit to the baseline and you build locally to check, since the risk is outweighed by the cost of these breaks.

**Comment by danmosemsft** [comment]
As a general rule if something hits CI it's good to immediately suppress the problem if we can, while we work on it. (?)

**Comment by safern** [comment]
Yeah I guess that makes sense.

**Comment by ViktorHofer** [comment]
@safern what's the status on this?

**Comment by Anipik** [comment]
I didnt see this one reproing any more on official builds.

**Comment by ViktorHofer** [comment]
Ok so let's close this for now. Thanks.

**Comment by safern** [comment]
This is not reproing because I baselined the errors. We should still fix this. Will re-open, but I will mvoe to 6.0.0 and remove blocking-clean-ci.

**Comment by safern** [comment]
The errors are no longer baselined since we moved APICompat to run against 5.0.0 and we haven't gotten a repro (really weird). Closing.
