### ISSUE TITLE
Make GraphQL a part of .NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#40413]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1132825/make-graphql-a-part-of-net.html)._

---
<p>I'd suggest to make GraphQL functionalities a part of .NET (System.Net.Http.GraphQL).</p> <p>There are community projects for it, like you can see here https://graphql.org/code/#c-net, but the demand for GraphQL is increasing. Having buil-it GraphQL classes and methods would provide a covenient way to build an API with a GraphQL endpoint. For instance there could be a template for a WebApi with GraphQL.</p>

---
#### Feedback Bot on 8/3/2020, 03:17 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by danmosemsft** [comment]
@JeremyLikness is doing some investigation about the maturity of GraphQL libraries on .NET. As a general rule, we want to strengthen the general .NET Library ecosystem so that there are great, trustworthy libraries to fulfil all needs. Only in certain cases is the best answer to put an implementation in the base .NET libraries.

**Comment by scalablecory** [comment]
Also, we would need an actual API proposal as well :)

**Comment by danmosemsft** [comment]
I wouldn't suggest to put in the work to make an API proposal without consensus here that we would be open to it. As I suggested above we would rather support our ecosystem and that's what @JeremyLikness is looking into.

**Comment by JeremyLikness** [comment]
Looping in @jamesmontemagno who is doing focused work here as well. As @danmosemsft mentioned, right now we aren't looking to build `System.GraphQL`. We are in the process of evaluating existing libraries and speaking with customers to understand what their end-to-end scenarios are and where the pain points in .NET exist. That will drive our next steps to determine how we can help deliver the best experience for .NET developers.

**Comment by danmosemsft** [comment]
@ajcvickers where do you plan to track issues relating to GraphQL work (if any)?

**Comment by ajcvickers** [comment]
@danmosemsft Not decided yet.

**Comment by myermian** [comment]
At one point in time, `System.Text.Json` did not exist, which was fine because `Newtonsoft.Json` worked very well (and still does). But, Microsoft still created and supported a NuGet package for Json support. I don't see why GraphQL can't also have a Microsoft package for support.

When you create a new ASP.NET Core project, it defaults to using REST. Having a package available like `Microsoft.AspNet.GraphQL` (just an example) would be nice.

**Comment by ajcvickers** [comment]
@myermian Have you tried [Hot Chocolate from ChilliCream](https://chillicream.com/docs/hotchocolate)? Don't be put off by the name; it's a really well done, professional GraphQL platform.

We are currently in the process of deciding how to best support GraphQL in .NET. Feedback on the advantages of a Microsoft solution verses leveraging third-party packages would be much appreciated.

/cc @JeremyLikness

**Comment by myermian** [comment]
> @myermian Have you tried [Hot Chocolate from ChilliCream](https://chillicream.com/docs/hotchocolate)? Don't be put off by the name; it's a really well done, professional GraphQL platform.
> 
> We are currently in the process of deciding how to best support GraphQL in .NET. Feedback on the advantages of a Microsoft solution verses leveraging third-party packages would be much appreciated.
> 
> /cc @JeremyLikness

I have tried both `HotChocolate` and `graphql-dotnet` -- I even have a contribution towards the `graphql-dotnet` project. Both are really good. I'm not sure what the decision to create `System.Text.Json` was when even ASP.NET was using `Newtonsoft.Json`, but it happened. I imagine the same will probably happen with the GraphQL protocol.

**Comment by JeremyLikness** [comment]
@myermian `System.Text.Json` addresses a much lower level in the stack than GraphQL. For example, ASP.NET Core relies on JSON serialization as part of its  engine and functionality, so the choice of a library impacts the entire framework. GraphQL is an extension to the core capabilities and therefore is more flexible and doesn't require us to commit to a specific library for it to work. 

Having said that, there are probably features that make sense for developers independent of the GraphQL library they use. For example, `.graphql` and `.gql` schemas are well-defined and work the same for any library, so one consideration is providing support for these (validation, IntelliSense).

Can you share the benefits you would gain from a Microsoft GraphQL implementation over using a community solution like HotChocolate? A big part of this work item is understanding what developers like you need and are missing so we can help fill that gap. Your feedback will be very valuable to help us craft the best solution to address your requirements.

**Comment by JeremyLikness** [comment]
Adding this cross-reference for further discussion:

[Issue #5852: .NET Developers have a first class experience working with GraphQL](https://github.com/dotnet/core/issues/5852)

**Comment by stephentoub** [comment]
Closing this in favor of https://github.com/dotnet/core/issues/5852.
