### ISSUE TITLE
Allow skip chain validation in ClientCertificate authentication

### ISSUE THREAD

**Issue by espenrl** [dotnet/runtime#40423]
## Background and Motivation

We use `Microsoft.AspNetCore.Authentication.Certificate` and for our use case chain validation gets in the way. We have the `client certficate` explicitly registered server side and validate that aspect in `CertificateAuthenticationOptions.Events.OnCertificateValidated`. Chain validation is really not needed as the client certificate is validated against a server side copy of the same certificate. If the chain validation fails we never get to doing our validation logic in `OnCertificateValidated` as the event is never raised.

NOTE: The ideal solution is to use either self signed certificates or certificates with valid chains. That is easier said than done when the same certificates are used across multiple environments.

## Proposed API

``` CSharp
public enum X509ChainTrustMode
{
    NoCheck
}
```

## Usage Examples

``` CSharp
void ConfigureCertificateAuthentication(CertificateAuthenticationOptions options)
{
    options.ChainTrustValidationMode = X509ChainTrustMode.NoCheck;
}
```

## Risks

Additive API with opt in use. Should not result in any regression.

**Comment by espenrl** [comment]
I have to add that the inspiration for this design is long term usage of RavenDB.

### From RavenDB documentation

https://ravendb.net/docs/article-page/5.0/csharp/server/security/overview

RavenDB does not use PKI infrastructure to trust certificates and uses a more strict approach. It will allow access to client certificates which are explicitly registered in the RavenDB server or certificates which have the same issuer and Public Key Pinning Hash as a certificate which is already trusted.

**Comment by espenrl** [comment]
I am working on a library `Extended client certificate authentication with management UI for ASP.NET Core`, please see https://github.com/espenrl/erl.AspNetCore.Authentication.ClientCertificate. We're in the process of doing the final touches before a first release. This will give you an idea of the use case, as well as ready to run examples.

**Comment by espenrl** [comment]
I've got another idea. What about allowing a callback for configuring the `X509Chain.ChainPolicy` to our liking.

https://github.com/dotnet/aspnetcore/blob/91776832e08d5ddf8abc2824ee7ac24f42f953e7/src/Security/Authentication/Certificate/src/CertificateAuthenticationHandler.cs#L125-L131

**Comment by bartonjs** [comment]
This seems to be either for SslStream or HttpClient (or both), changing area.

**Comment by karelz** [comment]
Triage: We believe this should be part of larger issue around certificate chains and their options -- there is already existing tracking issue - @wfurt will link it and close this one.

**Comment by wfurt** [comment]
may be in similar to https://github.com/dotnet/runtime/issues/35839. We may want to expose some better control over validation in general.

**Comment by espenrl** [comment]
As I have understood it the client certificate goes through validation on SSL handshake as well as in `CertificateAuthenticationHandler`. I guess the public API will have to expose ways to relax validation of both.

**Comment by wfurt** [comment]
Client and server now have option to pass in `X509ChainPolicy` via `CertificateChainPolicy` in ssl options. If present, chain constructed inside `SslStream` will respect the setting. You can customize it anyway you want (including disabling AIA) but as far as I can tel there is no way to disable the validation completely. I don't know how the options would surface in Kestrel but @Tratcher can probably point you in right direction.
