### ISSUE TITLE
[wasm] Blazor apps started from Visual Studio have optimizations disabled, even in Release

### ISSUE THREAD

**Issue by BrzVlad** [dotnet/runtime#40428]
Steps to reproduce:
- Create blazor wasm template
- Add some code that requires optimizations. For example, on counter page
```
@page "/counter"
@using System.Diagnostics

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;
    private int result;

    private int Add (int a, int b)
    {
        return a + b;
    }

    private void TestMethod ()
    {
        for (int i = 0; i < 100000; i++) {
            int a = 10;
            int b = 20;
            result += Add (a, b);
        }

    }

    private void IncrementCount ()
    {
        Stopwatch sw = new Stopwatch ();
        sw.Start ();
        TestMethod ();
        sw.Stop ();
        Console.WriteLine ("TestMethod took {0} ms", sw.ElapsedMilliseconds);

        currentCount++;
    }
}
```
- Notice that, when running from visual studio the release configuration with `Start without debugging`, the computation time when doing a click is around 4-5 times slower than the same operation with the web app published and deployed to an IIS instance

When initializing the runtime, `mono_wasm_load_runtime` always receives `enable_debugging` as -1 when started from visual studio, while the published version has it set to 0.

**Comment by BrzVlad** [comment]
cc @lewing @marek-safar

**Comment by lewing** [comment]
I see the issue, fix incoming.

**Comment by lewing** [comment]
@brzvlad when you are running the release build are you choosing "run-without-debugging"?

**Comment by BrzVlad** [comment]
As mentioned in the description, I go to `Debug` menu and click `Start without debugging`

**Comment by lewing** [comment]
closed in favor of https://github.com/dotnet/aspnetcore/issues/24623

**Comment by captainsafia** [comment]
@BrzVlad Thanks for reporting this issue.

> Notice that, when running from visual studio the release configuration with Start without debugging, the computation time when doing a click is around 4-5 times slower than the same operation with the web app published and deployed to an IIS instance

This is particular interesting. Debugging is disabled by default when running in a release configuration. In Blazor, we verify this by checking if PDBs are generated in the build. This doesn't happen in a release configuration.

I ran some tests with our perf benchmarking tool to verify the behavior here.

Here's a screenshot of perf stats on a Blazor app built with a Debug configuration.

![localhost_5001_ (2)](https://user-images.githubusercontent.com/1857993/91205283-26f33500-e6ba-11ea-8b7e-7136c782b719.png)

And here's a screenshot of perf stats when running in a Release configuration.

![localhost_5001_](https://user-images.githubusercontent.com/1857993/91205379-5013c580-e6ba-11ea-9721-6a138a2fda1c.png)

There's not a major perf distinction between the two for the scenarios measured.

> When initializing the runtime, mono_wasm_load_runtime always receives enable_debugging as -1 when started from visual studio, while the published version has it set to 0.

It might be the case that PDBs are generated in VS even when the Release configuration is used. Do you see PDBs in the build output when building with a Release config?
