### ISSUE TITLE
ApiCompat failing in CI due to System.ComponentModel.MarshalByValueComponent ref + src diffs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#40439]
See:

https://github.com/dotnet/runtime/pull/40425/checks?check_run_id=951460794
https://github.com/dotnet/runtime/pull/36252/checks?check_run_id=951596391

```txt
src/libraries/shims/ApiCompat.proj(116,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) CannotRemoveAttribute : Attribute 'System.ComponentModel.TypeConverterAttribute' exists on 'System.ComponentModel.MarshalByValueComponent' in the contract but not the implementation.
```

These PRs are not touching the ref assembly for `MarshalByValueComponent`.

**Comment by safern** [comment]
Thanks @GrabYourPitchforks. I'm already investigating this, with no luck yet to repro. Here's the original issue: https://github.com/dotnet/runtime/issues/40416 closing as a dupe.
