### ISSUE TITLE
`Console.CursorLeft` doesn't loop back to 0 when it hits a new line.

### ISSUE THREAD

**Issue by BrainSlugs83** [dotnet/runtime#40438]
# Issue Title
`Console.CursorLeft` doesn't loop back to 0 when the console line wraps.

If you watch it, it will go from BufferWidth - 1, to BufferWidth - 1 (same value twice), to 1 -- never hitting 0.

So it never reports BufferWidth, or 0 as the CursorLeft position. -- It seems like a bug that you can print a character to the console, and the cursor position is not updated.

# General

You can see from the below code that the left most cursor position SHOULD be position 0, and that printing a period character over and over, eventually does loop back around and fill that position. -- But the API will never report it.

Instead (assuming `Console.BufferWidth` == 120), you will see that it goes in this sequence: `118`, `119`, `119`, `1`.

It reports 119 twice, instead of 0. -- The second 119 is obviously wrong though, and should be 0 (I have visually verified that it is at the far left, blinking at the very first position when it reads 119 the second time, and that 1 is the second position).

```
Console.WriteLine(Console.CursorLeft); // prints 0

Console.Write('.');
while (Console.CursorLeft != 0) // infinite loop, but shouldn't be.
{
    Console.Write('.');
}
```

**Comment by danmosemsft** [comment]
@BrainSlugs83 thanks for the report. do you want to investigate a little to find where the bug is?

**Comment by BrainSlugs83** [comment]
Sure... @danmosemsft.

I did some further digging in the .NET Core source and found the following two classes:
 - https://github.com/dotnet/runtime/blob/master/src/libraries/System.Console/src/System/Console.cs
 - https://github.com/dotnet/runtime/blob/master/src/libraries/System.Console/src/System/ConsolePal.Windows.cs

Looks like the implementation is platform specific, and that makes total sense of course.
FWIW, I am on Windows 10 Pro (Version 1903, Build 18362.959).

Anyway, it looks like the Windows implementation is just shelling out to `GetConsoleScreenBufferInfo`, and sure enough, it does the same thing when called from C++ (see code below; same issue with `GetConsoleCursorPositionEx`, btw...)

But I did notice a fix (literally stumbled into it) when I was screwing around with some other settings to gather more information -- a fix which is at odds with the [documentation ](https://docs.microsoft.com/en-us/windows/console/setconsolemode) for the function -- and it's kind of a terrible compromise IMO.

According to the documentation, you could see this behavior if the console mode has the `DISABLE_NEWLINE_AUTO_RETURN` flag set -- and in my case that flag is NOT set.

Instead I'm seeing this behavior when the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag is set. -- which does not make any mention of this weird newline behavior; and honestly, still seems like a bug.

@danmosemsf: **Can we push this up to the Windows API team? (or whatever team owns this API?)**

Here's the C++ I used to reproduce the issue (it calls the same method as .NET Core on Windows):
```
#include <stdio.h>
#include <iostream>
#include <Windows.h>
#include <conio.h>
#include <io.h>

COORD GetConsoleCursorPosition(HANDLE hConsoleOutput)
{
    CONSOLE_SCREEN_BUFFER_INFO cbsi;
    if (GetConsoleScreenBufferInfo(hConsoleOutput, &cbsi))
    {
        if (cbsi.dwCursorPosition.X == (cbsi.dwSize.X - 1))
        {
            __asm nop // compile in debug mode and put your breakpoint here.
        }

        return cbsi.dwCursorPosition;
    }
    else
    {
        // The function failed. Call GetLastError() for details.
        COORD invalid = { 0, 0 };
        return invalid;
    }
}

int main()
{
    std::cout << "Hello World!";

    HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);

    // Insert force or fix code here

    COORD pos = GetConsoleCursorPosition(h);
    while (pos.X != 0)
    {
        std::cout << ".";
        pos = GetConsoleCursorPosition(h);
    }
}
```

The force code forcibly enables the Virtualization if it's not on by default for you:
```
// FORCE BUG
if (GetConsoleMode(h, &mode))
{
    SetConsoleMode(h, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
}
```

The fix (again, kind of a lame compromise to not allow an accurate read of the cursor position when terminal emulation is turned on):
```
DWORD mode;
if (GetConsoleMode(h, &mode) && (mode & ENABLE_VIRTUAL_TERMINAL_PROCESSING))
{
    SetConsoleMode(h, mode & ~ENABLE_VIRTUAL_TERMINAL_PROCESSING);
}
```

**Comment by danmosemsft** [comment]
@BrainSlugs83 thanks for investigating. Could you please open an issue at https://github.com/Microsoft/Terminal (if you want to ask about behavior) or https://github.com/MicrosoftDocs/Console-Docs  (if you want the docs to be better)?

Then I think you can close this one based on your investigation.

**Comment by danmosemsft** [comment]
I'm going to close this per above.
