### ISSUE TITLE
System.Collections.Generic.SortedList<TKey, TValue> should have GetByIndex(Int32)

### ISSUE THREAD

**Issue by quangaming2929** [dotnet/runtime#40450]
## Background and Motivation

The missing method between Generic and non-generic version of SortedList
## Proposed API

The signature should be similar to [SortedList.GetByIndex(Int32) Method](https://docs.microsoft.com/en-us/dotnet/api/system.collections.sortedlist.getbyindex?view=netcore-3.1#System_Collections_SortedList_GetByIndex_System_Int32_)  but with Generic.
## Usage Examples

```cs
void SampleMethod() 
{
   System.Collections.Generic.SortedList<string, string> sortedList = new  System.Collections.Generic.SortedList<string, string>();
   sortedList.Add("One, cat");
   sortedList.Add("Two, dog");
   sortedList.Add("Three, bat");
   for ( int i = 0; i < sortedList.Count; i++ )  
   {
         Console.WriteLine( "\t{0}:\t{1}", sortedList.GetKey(i), sortedList.GetByIndex(i) );
   }
}
```

**Comment by svick** [comment]
You can already do this by accessing [the `Values` collection](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedlist-2.values):

```c#
Console.WriteLine("\t{0}:\t{1}", sortedList.Keys[i], sortedList.Values[i]);
```

**Comment by quangaming2929** [comment]
Oh I didn't know that, but I still find it unintuitive due to the inconsistency between versions

**Comment by eiriktsarpalis** [comment]
I don't think we could add this on the basis of API consistency with the non-generic version. Since a workaround exists, I'm going to close this issue.
