### ISSUE TITLE
Add macOS BigSur to RID graph

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#40479]
This time the insertion can be a bit more interesting.

- The version number `11` or `11.0` should be added
- New arm64 architecture was added

**Comment by danmosemsft** [comment]
cc @ericstj was telling me we probably should do this now and not wait.

**Comment by danmosemsft** [comment]
This will also need 2.1 and 3.1 ports right?

**Comment by danmosemsft** [comment]
@marek-safar , @wfurt told me last week that current builds are 10.16. Are you sure it will be 11?

**Comment by wfurt** [comment]
It seems like that will be 11 in final release. I'll get it ready.

**Comment by safern** [comment]
> This will also need 2.1 and 3.1 ports right?

Right. 

I will be sending helix jobs to a testing helix queue we have to see what comes out as well.

**Comment by marek-safar** [comment]
@danmosemsft that has changed in beta3. The system version is reported as '11.0' now everywhere

**Comment by danmosemsft** [comment]
Keeping open for port.

**Comment by danmosemsft** [comment]
these were done https://github.com/dotnet/corefx/pulls?q=is%3Apr+is%3Aclosed+author%3Awfurt

**Comment by wfurt** [comment]
there is still  #41044 and port to 5.0 branch to be done. (3.1 and 2.1 should be OK)
