### ISSUE TITLE
How to request for backport runtime to coreclr?

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#40509]
Hi,

OpenJDK is able to request for backport to jdk8u, for example, [JDK-8238380](https://bugs.openjdk.java.net/browse/JDK-8238380) backport jdk-15 to jdk8u-dev by adding label: jdk8u-fix-request.

But how to request for backport runtime to coreclr?  Is there some guidelines for working on coreclr or best practices for coreclr backports just like [jdk8u](https://wiki.openjdk.java.net/display/jdk8u/Main)?

Thanks,
Leslie Zhai

**Comment by GrabYourPitchforks** [comment]
There's no formal mechanism. The common way of doing this is to find the original tracking issue and leave a comment describing how it's impacting you and why the patch should be backported. We don't tend to backport entire features, but we do occasionally backport reliability fixes depending on how impactful they are.

What did you have in mind?

**Comment by xiangzhai** [comment]
Hi @GrabYourPitchforks 

Thanks for your kind response!

> The common way of doing this is to find the original tracking issue and leave a comment describing how it's impacting you and why the patch should be backported.

Thanks for your teaching!

> We don't tend to backport entire features

I agree+1

We will not backport, for example, [Compile with gcc 4.8](https://github.com/dotnet/coreclr/pull/27625) to coreclr.

Thanks,
Leslie Zhai
