### ISSUE TITLE
[Perf -125%] PerfLabTests.CastingPerf.CheckArrayIsNonvariantGenericInterface

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#40503]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/1d05f27bf92586e8b7e0d312194b83de6a35ba67...4c18fb2cea5a7e0123fee52e61139836be3362b4)

### Regressions in PerfLabTests.CastingPerf

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
CheckArrayIsNonvariantGenericInterface | 7.04 ns | 15.84 ns | 2.25 |  | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_04_2020/refs/heads/master_x64_Windows%2010.0.18362/PerfLabTests.CastingPerf_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_04_2020/refs/heads/master_x64_Windows%2010.0.18362/PerfLabTests.CastingPerf.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'PerfLabTests.CastingPerf*';
```
<details>

#### PerfLabTests.CastingPerf.CheckArrayIsNonvariantGenericInterface

```log
[ 6.643 ;  7.572) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 7.572 ;  8.018) | 
[ 8.018 ;  8.947) | @@@@
[ 8.947 ;  9.481) | 
[ 9.481 ; 10.411) | @@@@@@@
[10.411 ; 11.248) | 
[11.248 ; 12.178) | @@@@@@@@@@@
[12.178 ; 12.999) | @
[12.999 ; 14.031) | 
[14.031 ; 14.960) | @
[14.960 ; 15.371) | 
[15.371 ; 16.301) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
We are also seeing a high degree of erratic behavior in most of the CheckArrayIsNonvariant* tests as can be seen in this [report](https://pvscmdupload.blob.core.windows.net/reports/08_03_2020/Perflab/report_Weekly_ca=x64_cb=refs-heads-master_co=Windows1018362_cr=dotnetruntime_cf=Perflab_cc=CompliationMode=tiered-RunKind=micro_2020-08-03.html), starting on July 31st 2:17PM.

**Comment by davidwrighton** [comment]
Noise appears to have increased for this test, but not typical performance. While noise isn't great, its not particularly bad either. Closing.
