### ISSUE TITLE
Microsoft XML Serializer Generator

### ISSUE THREAD

**Issue by ssommerf** [dotnet/runtime#40511]
Execution of the Xml Serializer Generator from within a NET Standard 2.0 project works and a XML assembly is generated. The generated assembly is missing the assembly version of the targeted (analyzed) assembly. 
XML serialization assembly always defaults to [assembly: AssemblyVersion("0.0.0.0")].

This is an major issues in scenarios where you''ll have setups/installers that calculate delta updates of assemblies based on the version number.

**Comment by HongGit** [comment]
This should have been resolved with the linked PR.
