### ISSUE TITLE
Asserts not working in WinForms .net Core apps

### ISSUE THREAD

**Issue by kirsan31** [dotnet/runtime#40512]
* .NET Core Version: **3.1.6.**

* Have you experienced this same bug with .NET Framework?:  **No**.

**Problem description:**

`System.Diagnostics.Trace.Assert` and `System.Diagnostics.Debug.Assert` are not working in WInForms .net core apps. Programs are silently crash.

**Expected behavior:**
No crash, and assertion dialog must appear after assert.

**Minimal repro:**
Create new WinForm core project. Put `System.Diagnostics.Debug.Assert(false, "test");` anywhere in the code, for example:
```cs
protected override void OnShown(EventArgs e)
{
    base.OnShown(e);
    System.Diagnostics.Debug.Assert(false, "test");
}
```
run project (Debug conf.) with ctrl+f5.
P.s. if run with f5 - no crash, but and no assertion dilaog (only message in output).

**Comment by danmosemsft** [comment]
We couldn’t pop a msg box at this level any more due to layering. So we treat as a regular failing assert. But I think we added a hook for UI stacks to wire in a dialog. If so then rich is actually in winforms

**Comment by jkotas** [comment]
Related / duplicate: #15386 ,  #11461

**Comment by kirsan31** [comment]
@jkotas 
So, if I understand right, [this](https://github.com/dotnet/runtime/issues/15386#issuecomment-438005841):

> what work remains here? Is it only for Winforms/WPF to hook it up to a dialog? If so I think we can close this, **and ensure they have issues in their repos to do that**.

did not happen (until now)? And this issue must be transferred back to WinForms repo?

**Comment by tommcdon** [comment]
dotnet/coreclr#20764 changed winforms assert behavior.  We have a [hook](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.cs#L112) which is currently used by debug.assert tests.  @danmosemsft is this the hook that winforms should use took hook debug.assert? Adding @merriemcgaw

**Comment by jkotas** [comment]
> [hook](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.cs#L112) 

This hook is internal API. It is not something that WinForms or WPF should be using in the current shape.

`System.Diagnostics.Trace.Listeners` is the public API for customization of assertion failures.

**Comment by jkotas** [comment]
In case `System.Diagnostics.Trace.Listeners` does not work for WinForms for some reason, we should add a proper public API using standard public API process that does work.

**Comment by kirsan31** [comment]
> In case `System.Diagnostics.Trace.Listeners` does not work for WinForms for some reason

@RussKie @merriemcgaw I think guys here not 100% sure what going on with this in WinForms.
This is nasty regression from .net Framework - not to able using asserts :(

**Comment by maryamariyan** [comment]
> dotnet/coreclr#20764 changed winforms assert behavior. We have a hook which is currently used by debug.assert tests. @danmosemsft is this the hook that winforms should use took hook debug.assert? Adding @merriemcgaw

I think as explained in https://github.com/dotnet/runtime/issues/11461, the [Trace_AssertUiEnabledFalse_SkipsFail](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Debug/tests/DebugTestsUsingListeners.cs#L248-L303) test illustrates how to use custom Trace Listeners to allow for showing dialogs.

**Comment by kirsan31** [comment]
Something must be really done with this, because in many cases assert info even not written to sys. log - simple app crash. I have used memory dump just to identify that crash was cause by assert :raised_eyebrow:

**Comment by danmosemsft** [comment]
@RussKie do you have a 5.0 issue where you're investigating TraceListener fix?

**Comment by RussKie** [comment]
Yes, https://github.com/dotnet/winforms/issues/3739

**Comment by danmosemsft** [comment]
Perhaps you could open a similar issue for WPF and we can close this one?

**Comment by RussKie** [comment]
Aye, will do.

**Comment by RussKie** [comment]
https://github.com/dotnet/wpf/issues/3346

**Comment by josalem** [comment]
Issue was "moved" to dotnet/wpf; closing
