### ISSUE TITLE
WASM: new blazor wasm template fails to load on Windows

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#40527]
I created a new blazor wam app with `dotnet new blazorwasm` using latest Preview 8 and latest RC1 SDK. Then run `dotnet run`

Open any browser (Chrome, Microsoft Edge) and the page fails to load. Looking at the console logs there is an error when trying to load ICU:

```
ICU call ulocdata_getCLDRVersion failed with error #2 'U_MISSING_RESOURCE_ERROR'.
```

Tested this on macOS and it works fine there.

cc: @EgorBo @kg @lewing @steveisok

**Comment by lewing** [comment]
This is because the icu data isn't being loaded and invariant mode isn't being enabled.  I'm not sure what mix of packages causes it to be in this state.

cc @pranavkm @kg

**Comment by safern** [comment]
The weird thing is that icudt.dat is in the output directory so I wonder why it is not being loaded.

**Comment by tarekgh** [comment]
are we sure the ICU data is not loaded? or could it be loaded and missing some stuff that returned this error code?

**Comment by lewing** [comment]
@tarekgh yeah that error may be the loading failing.  cc @EgorBo

**Comment by safern** [comment]
I used a local build and it seems like https://github.com/dotnet/runtime/blob/2b93f831736a44998b9b58a249dfd57d08ef319f/src/libraries/Native/Unix/System.Globalization.Native/pal_icushim_static.c#L34-L49

is not being called at all at startup, so that seems to be part of the problem as @tarekgh suggests the ICU data is not being loaded.

**Comment by pranavkm** [comment]
@safern there were changes in the preview8 Blazor SDK required to load the icu data that haven't flown to master (RC1) SDK as yet. Can you try using a p8 SDK instead?

**Comment by safern** [comment]
I used a P8 SDK... the latest build from yesterday to be precise. It worked on macOS so I expect it to work on Windows as well with that SDK and it didn't.

**Comment by kg** [comment]
I'm not sure how I can fix this unless it's a bug in the runtime.

**Comment by lewing** [comment]
@kg it is just the issue where the .dat isn't being loaded and the load_runtime is being called directly problem again.

**Comment by safern** [comment]
@kg @EgorBo any update on this?

**Comment by kg** [comment]
As far as I know nothing has changed in terms of me not being able to fix this. Blazor's template needs to do the right thing.

**Comment by safern** [comment]
cc: @pranavkm

**Comment by tarekgh** [comment]
Any news about this one? I am just triaging the globalization issues and trying to figure out if issues marked with 5.0 are on track. Thanks!

**Comment by EgorBo** [comment]
@safern @tarekgh I think it can be closed, the failure was fixed in https://github.com/dotnet/runtime/pull/40765
so now an app from the template should not crash and use Invariant mode always. Blazor guys are working on integrating `icudt.dat` into the template but I believe it's a separate issue

**Comment by safern** [comment]
Do we have a tracking issue for that? Falling back into Invariant is fine but I would like to avoid us falling back always because we forgot or didn't realize this was falling back to invariant on Windows only, because on Unix it loads ICU correctly and that is a difference of behavior in between OSs.

**Comment by ericstj** [comment]
I couldn't find an issue for adding `icudt.dat` into the template.  It sounds like @safern is saying this is important for 5.0 and related to this issue he has opened.  @EgorBo can you provide an update on that?

**Comment by pranavkm** [comment]
@safern could you try this again with the the RC1 SDK that's out? We have tests and CTI verification for trying this out on different operating systems, and we haven't seen this issue reported recently.

**Comment by safern** [comment]
@pranavkm trying this out and I'll update this.

**Comment by safern** [comment]
@pranavkm I can confirm this is fixed in RC1 and it didn't fall back to Invariant, I can see in the requests and files that it loaded `icudt.dat`
