### ISSUE TITLE
Add InstructionEncoder.Switch to enable emitting switch instructions with LabelHandles

### ISSUE THREAD

**Issue by SeeminglyScience** [dotnet/runtime#40546]
## Background and Motivation

It doesn't look like there's a way to use `InstructionEncoder.DefineLabel`'s `LabelHandle`s with a `switch` instruction.  I'm mainly asking if there is a way to do it that I'm missing, but if not here's a basic API proposal to enable it.

## Proposed API

```diff
namespace System.Reflection.Metadata.Ecma335
{
    public readonly struct InstructionEncoder
    {
+       public void Switch(params LabelHandle[] label);
    }
}
```

## Usage Examples

```csharp
var ie = new InstructionEncoder(new BlobBuilder(), new ControlFlowBuilder());
var case0 = ie.DefineLabel();
var case1 = ie.DefineLabel();
var case2 = ie.DefineLabel();
var afterCases = ie.DefineLabel();

ie.OpCode(ILOpCode.Ldc_i4_0);
ie.Switch(case0, case1, case2);
ie.Branch(ILOpCode.Br_s, afterCases);

ie.MarkLabel(case0);
ie.OpCode(ILOpCode.Ldc_i4_0);
ie.OpCode(ILOpCode.Ret);

ie.MarkLabel(case1);
ie.OpCode(ILOpCode.Ldc_i4_1);
ie.OpCode(ILOpCode.Ret);

ie.MarkLabel(case2);
ie.OpCode(ILOpCode.Ldc_i4_2);
ie.OpCode(ILOpCode.Ret);

ie.MarkLabel(afterCases);
ie.OpCode(ILOpCode.Ldc_i4_s);
ie.CodeBuilder.WriteCompressedSignedInteger(10);
ie.OpCode(ILOpCode.Ret);

new MethodBodyStreamEncoder(new BlobBuilder())
    .AddMethodBody(ie, maxStack: 8, localVariablesSignature: default, MethodBodyAttributes.None);
```

## Alternative Designs

Originally this proposal was based on emitting the label by itself:

```diff
namespace System.Reflection.Metadata.Ecma335
{
    public readonly struct InstructionEncoder
    {
+       public void Label(LabelHandle label);
    }
}
```

This won't work because the target offset is based on the end of the `switch` instruction, not the offset of the label.

Also for it to work with switch like intended, it would need to only emit int32 offsets.  That's not super clear from the name and would generate bad IL if someone were to do `OpCode(ILOpCode.Br_s); Label(label);`, even if it were based on the label's offset.

**Comment by teo-tsirpanis** [comment]
I think it should also have an overload for `IReadOnlyCollection<LabelHandle>`, to allow high-performance apps to reuse a `List<LabelHandle>`.

**Comment by teo-tsirpanis** [comment]
[I have refactored](https://github.com/teo-tsirpanis/dotnet-runtime/tree/srm-controlflowbuilder-refactor) the relevant SRM code to easily support emitting `switch`. Is there anything that prevents the proposal from going forward?

**Comment by buyaa-n** [comment]
@tmat what do you think about this proposal?

**Comment by SeeminglyScience** [comment]
> Any updates? I would really like to see this proposal implemented! (I'd be very thankful if someone could provide a temporary workaround.)

This is probably not the temporary workaround you're hoping for, but what I did was basically rip out and modify their flow control builder code. Here's the PR where I did that if you want some ideas SeeminglyScience/ILAssembler#19

**Comment by teo-tsirpanis** [comment]
@buyaa-n, @tmat can this move forward? And @SeeminglyScience can you also propose an overload that takes an `IReadOnlyCollection<LabelHandle>`?

**Comment by SeeminglyScience** [comment]
> And @SeeminglyScience can you also propose an overload that takes an `IReadOnlyCollection<LabelHandle>`?

I tried to keep the proposal as close to other APIs in the library as possible. If we were adding overloads for performance, I'd rather see `ReadOnlySpan<LabelHandle>` added (but that also is not present in the API surface today). For now, I'm going to keep the proposal as is.

**Comment by teo-tsirpanis** [comment]
Yeah, spans would not fit because they are nowhere else used in this library. `IReadOnlyCollection` would be the next most memory-efficient solution (in a library where memory efficiency is a theme), but let's wait for the API owners' opinion.

**Comment by tmat** [comment]
We could add the proposed API that takes `LabelHandle[]` but a non-allocating version like following would be more aligned with the spirit of the encoder APIs.

```C#
public readonly struct SwitchInstructionEncoder
{
   private readonly InstructionEncoder _instructionEncoder;
   private readonly int _instructionEndOffset;

   internal SwitchInstructionEncoder(InstructionEncoder instructionEncoder, int switchInstructionSize) { ... }

   public void Branch(Label label)
     => _instructionEncoder.GetBranchBuilder().AddBranch(_instructionEndOffset, label, _instructionEncoder.CodeBuilder);
}

public readonly struct InstructionEncoder
{
   public SwitchInstructionEncoder Switch(int branchCount)
   {
      OpCode(ILOpCodes.Switch);      
      CodeBuilder.WriteInt32(branchCount);
      return new SwitchInstructionEncoder(this, Offset + branchCount * sizeof(uint));
   }
}
```

**Comment by bartonjs** [comment]
* We went with the alternative proposal with `SwitchInstructionEncoder` instead of the params array, since it felt more consistent with existing paradigms.

```C#
namespace System.Reflection.Metadata.Ecma335
{
    public readonly struct SwitchInstructionEncoder
    {
        public void Branch(LabelHandle label);
    }

    public partial struct InstructionEncoder
    {
        public SwitchInstructionEncoder Switch(int branchCount);
    }
}
```

**Comment by teo-tsirpanis** [comment]
I will do it in a couple of months in time for 8.0.0, if someone else wants to do it, feel free to.

**Comment by August-Alm** [comment]
The original proposal had a clear usage example but the approved API leaves the intended functionality implicit. Am I correct in understanding the approved proposal as supposed to work in such a way that the originally suggested method is equivalent to the following ``InstructionEncoder`` method?
```cs
public void SwitchOfLabelHandles(params LabelHandle[] labels)
{
    var switchEncoder = Switch(labels.Length);
    foreach (var label in labels)
    {
        switchEncoder.Branch(label);
    }
}
```

**Comment by teo-tsirpanis** [comment]
@August-Alm yes.
