### ISSUE TITLE
Can't use IServiceProvider to instantiate new services in Dispose(Async) during scope disposing 

### ISSUE THREAD

**Issue by andriysavin** [dotnet/runtime#40545]
First, some intro. While `IDisposable` and `IAsyncDisposable` interfaces' main goal is to "cleanup resources", they are widely used to also reset some state, finalize some work or as a notification mechanism of some scope ending. With addition of `IAsyncDisposable` the purpose of disposing has become much wider, as it allows much more complex interactions. 

In context of dependency injection `I(Async)Disposable` is not only a convenient way of being notified that a DI scope is ending, but is practically the only one (as far I'm aware). This makes it a great mechanism to implement something like Unit Of Work, when you inject a repository as a scoped service at HTTP request beginning, do your work, and on request(scope) end the repository gets notified via `Dispose(Async)` that its lifetime is close to end, and the repository saves changes to a DB. At this point you can also dispatch domain events which were collected during the request handling (you want to notify other (micro)services about things happened only after the state is persisted, right?). 

Since we can do rather complex things in cases described, it's totally possible that there can be attempts to create new dependencies during disposing. And here we get the problem: once DI scope disposing is started, it's immediately marked disposed, so any attempt to create new scoped or transient dependencies will fail with `ObjectDisposedException`. In my case it was in MediatR library, which was trying to (lazily) instantiate a notification handler while sending notifications in `DisposeAsync` of my repository. In other words, the DI scope doesn't support iterating over and over through instantiated dependencies until they stop growing. It instead doesn't allow any more once disposing is started.

I can guess some reasons which led to this limitation. E.g. no particular order in which objects are disposed is guaranteed anyway, so calling to EF `DBContext.SaveChanges` may fail because the context was already disposed. But are there any workarounds for this? Is there any way to get called back just before scope disposal start? Or maybe some other interface should be introduced to allow such scenarios?

**Comment by davidfowl** [comment]
No this isn't something we support or plan to support, or something that you should rely on in your services that are part of the DI container.
