### ISSUE TITLE
Outgoing HTTP request never completes

### ISSUE THREAD

**Issue by Ne4to** [dotnet/runtime#40541]
### Description

We have several independent applications faced with the similar issue. The application periodically makes HTTP request to other service and process data. According to logs and metrics the application sometimes stops this activity at some point of time (low CPU and network consumption, no '_finish_'-ish message in logs). It could be hours or days. Using CancellationToken does not help.

### Configuration

* .Net Core version: 2.2.5, 2.2.7 and 2.2.8
* Architecture: x64
* The application is running in a linux container based on `mcr.microsoft.com/dotnet/core/aspnet:2.2.7-stretch-slim` image
* The container is running in a Kubernetes cluster: `version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}`

### Other information

I was trying to use [dotnet-dump](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md) tool. All dumps have similar picture.

`dumpasync -stacks` output:

```
00007f6148482288 00007f6161eb3ed0      128          0 System.Net.Http.HttpConnection+<FillAsync>d__91
Async "stack":
.00007f6148482308 (1) System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<CopyToAsyncCore>d__8
..00007f61484823b8 (0) System.Net.Http.HttpConnection+HttpConnectionResponseContent+<SerializeToStreamAsync>d__7
...00007f6148482450 (0) System.Net.Http.HttpContent+<LoadIntoBufferAsyncCore>d__52
....00007f6147f5a640 (0) <error>
.....00007f6147f5a708 (0) <error>
......00007f6147f5a7b8 (0) <error>
.......00007f6147f5a940 (0) <error>
........00007f6147f5aa28 (0) <error>
.........00007f6147f5aaf0 System.Threading.Tasks.Task+WhenAllPromise
```

or

```
00007fce64b76c68 00007fce85820f48      128          0 System.Net.Http.HttpConnection+<FillAsync>d__91
Async "stack":
.00007fce64b76ce8 (1) System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<CopyToAsyncCore>d__8
..00007fce64b76d98 (0) System.Net.Http.HttpConnection+HttpConnectionResponseContent+<SerializeToStreamAsync>d__7
...00007fce64b76e30 (0) System.Net.Http.HttpContent+<LoadIntoBufferAsyncCore>d__52
....00007fce64b75c58 (0) <error>
.....00007fce64b75d20 (0) <error>
......00007fce64b75dd0 (0) <error>
.......00007fce64b75f10 (0) <error>
........00007fce64b75fb8 (0) <error>
.........00007fce64b76048 (0) <error>
..........00007fce64b73730 (0) <error>
...........00007fce64b737b8 (0) <error>
............00007fce64b73850 (0) <error>
.............00007fce64b738f8 (0) <error>
..............00007fce64b707c8 System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]]
```

`clrstack` output:

```
        Child SP               IP Call Site
00007F61C3EB4838 00007f61da34e303 [InlinedCallFrame: 00007f61c3eb4838] Interop+Sys.WaitForSocketEvents(IntPtr, SocketEvent*, Int32*)
00007F61C3EB4838 00007f61616bd9c8 [InlinedCallFrame: 00007f61c3eb4838] Interop+Sys.WaitForSocketEvents(IntPtr, SocketEvent*, Int32*)
00007F61C3EB4830 00007F61616BD9C8 DomainBoundILStubClass.IL_STUB_PInvoke(IntPtr, SocketEvent*, Int32*)
00007F61C3EB48B0 00007F6161CD6AE4 System.Net.Sockets.SocketAsyncEngine.EventLoop() [/root/corefx-3120937/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs @ 321]
00007F61C3EB48F0 00007F6161CD6F09 System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__24_0(System.Object)
00007F61C3EB4900 00007F6160097D2A System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 2416]
00007F61C3EB4C90 00007f61d974817f [GCFrame: 00007f61c3eb4c90]
00007F61C3EB4D50 00007f61d974817f [DebuggerU2MCatchHandlerFrame: 00007f61c3eb4d50]
OS Thread Id: 0x16
```

I've downloaded `System.Net.Sockets.dll` from a container and ILSpy shows following source code:

```csharp
// System.Net.Sockets.SocketAsyncEngine
private unsafe void EventLoop()
{
	try
	{
		bool flag = false;
		while (!flag)
		{
			int num = 1024;
			if (Interop.Sys.WaitForSocketEvents(_port, _buffer, &num) != 0)
			{
				throw new InternalException();
			}
			for (int i = 0; i < num; i++)
			{
				IntPtr data = _buffer[i].Data;
				if (data == ShutdownHandle)
				{
					flag = true;
				}
				else
				{
					GetContextFromHandle(data)?.HandleEvents(_buffer[i].Events);
				}
			}
		}
		FreeNativeResources();
	}
	catch (Exception ex)
	{
		Environment.FailFast("Exception thrown from SocketAsyncEngine event loop: " + ex.ToString(), ex);
	}
}
```

**Comment by scalablecory** [comment]
.NET Core 2.2 reached end of life last December. This may have been resolved in subsequent verssions -- can you please see if your problem still occurs in .NET Core 3.1 or with the recent .NET 5 previews?

**Comment by Ne4to** [comment]
> .NET Core 2.2 reached end of life last December. This may have been resolved in subsequent verssions -- can you please see if your problem still occurs in .NET Core 3.1 or with the recent .NET 5 previews?

Unfortunately right now we are referencing additional packages and they are not compatible with newer version of .Net Core. I was looking for similar issues, but it looks like all of them was in pre-2.2 era. I'd like to know is it some known issue in the runtime or we should search issue in the application code.

**Comment by scalablecory** [comment]
> I'd like to know is it some known issue in the runtime or we should search issue in the application code.

It's not a known issue, but the code there has been updated quite a bit since 2.2 so if it is a bug it may be fixed.

**Comment by geoffkizer** [comment]
The HttpClient code is expecting more data on the chunked-encoded response stream. It could be a bug, but it seems more likely that the server is sending an invalid response, e.g. not properly terminating the chunked encoding.

I'd suggest looking at what your server is actually sending and see if it looks correct or not.

**Comment by Ne4to** [comment]
Some of our services were migrated to .NET Core 3.1 and .NET 5 and they do not have the issue now.
