### ISSUE TITLE
Provide ability to supply hostname, time in the COMPlus_DbgMiniDumpName template

### ISSUE THREAD

**Issue by kichalla** [dotnet/runtime#40558]
Currently only process id is supported: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy

For example, having hostname and time can be useful when an app is running in multiple containers.

cc @mikem8361 as discussed in our email thread.

**Comment by mikem8361** [comment]
The vstest/helix integration effort, Watson and anybody else generating coredumps in docker containers need to uniquely name the coredumps based on these coredump pattern features.

**Comment by danmosemsft** [comment]
@nohwnd do you have an issue to update the dump name pattern here ? https://github.com/microsoft/vstest/blob/9394924dba5c3b6b84edb771ae8bc0e5ca405f93/src/Microsoft.TestPlatform.Extensions.BlameDataCollector/BlameCollector.cs#L14*

**Comment by nohwnd** [comment]
@danmosemsft I have a task for it in this issue https://github.com/microsoft/vstest/issues/2498, did not get to do it yet. I am 90% sure it is just that line of code.
