### ISSUE TITLE
FORMATEC should define cfFormat as a ushort

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/runtime#40555]
# Proposed API update

The COM type FORMATETC does not match the native implementation.  It should be defined as a ushort.

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Runtime.InteropServices/src/System/Runtime/InteropServices/ComTypes/FORMATETC.cs

https://docs.microsoft.com/en-us/windows/win32/api/objidl/ns-objidl-formatetc

Referred from: https://developercommunity.visualstudio.com/content/problem/1136346/formatetccfformat-is-the-wrong-type.html

```diff
namespace System.Runtime.InteropServices.ComTypes
{
    public struct FORMATETC
    {
        [MarshalAs(UnmanagedType.U2)]
-       public short cfFormat;
+       public ushort cfFormat;
        public IntPtr ptd;
        [MarshalAs(UnmanagedType.U4)]
        public DVASPECT dwAspect;
        public int lindex;
        [MarshalAs(UnmanagedType.U4)]
        public TYMED tymed;
    }
}
```

**Comment by AaronRobinsonMSFT** [comment]
This is one of those issues that we can talk about but makes things complicated for VB.NET. Making the field `ushort` would make the type [non-CLS compliant](https://docs.microsoft.com/dotnet/standard/language-independence-and-language-independent-components#Types) and thus break VB.NET usage.

A Github search [here](https://github.com/search?q=FORMATETC+language%3A%22Visual+Basic+.NET%22&type=Code&ref=advsearch&l=Visual+Basic+.NET&l=) seems to indicate there is a fair bit of use of the name `FORMATETC` which means it is used in VB.NET. However, it is hard to know how many repos define their own version vs using this one.

**Comment by AaronRobinsonMSFT** [comment]
Let's consider this for 6.0. If this doesn't have value in changing we should close it.

**Comment by terrajobst** [comment]
It's a breaking change and it seems this isn't the only place where we don't match the signedness of the native implementation. Considering this type was shipped in 2005 it seems the downsides of the breaking change outweigh the potential benefits.
