### ISSUE TITLE
Slow summing of int[], IEnumerable<int>(from List<int>) & IList<int>(from int[]) compared to .Net Fw 4.8

### ISSUE THREAD

**Issue by karakasa** [dotnet/runtime#40575]
### Description

The code sums 100,000 integers stored in
- `int[]`
- `List<int>`

by

- `for` on `int[]`
- `for` on `List<int>`
- `for` on `IList<int>`
- `foreach` on `IEnumerable<int>`

Compared to .Net Fw, Core sums:

- `int[]` 75% slower
- `IEnumerable<int>` from `List<int>` 36% slower
- `IList<int>` from `int[]` 16% slower

Other results are similar.

I can also observe that:
- Emitted assembly codes are similar when I checked **on SharpLab**.
- The issue is unlikely due to overflow check because I tried `unchecked` and the performance gap is similar.

Code is as follows:

```
using BenchmarkDotNet.Attributes;
using System.Collections.Generic;

namespace Benchmark
{
    public class ListBenchmark
    {
        private readonly int[] intArray;
        private readonly List<int> intList;
        public ListBenchmark()
        {
            intArray = new int[100000];
            var start = 1234;
            var sum = 0;
            for (var i = 0; i < intArray.Length; i++)
            {
                sum = unchecked(sum + i);
                start = unchecked(sum ^ 0x1234567 + start << 2);

                intArray[i] = start;
            }
            intList = new List<int>(intArray);
        }
        public int SumIEnumerable(IEnumerable<int> test2)
        {
            var sum = 0;
            foreach (var it in test2)
            {
                sum += it;
            }
            return sum;
        }
        public int SumIList(IList<int> test2)
        {
            var sum = 0;
            var cnt = test2.Count;
            for (var i = 0; i < cnt; i++)
            {
                sum += test2[i];
            }
            return sum;
        }

        public int SumList(List<int> test2)
        {
            var sum = 0;
            var cnt = test2.Count;
            for (var i = 0; i < cnt; i++)
            {
                sum += test2[i];
            }
            return sum;
        }

        public int SumArray(int[] test2)
        {
            var sum = 0;
            for (var i = 0; i < test2.Length; i++)
            {
                sum += test2[i];
            }
            return sum;
        }

        [Benchmark]
        public int BenchmarkIEnumerableWithArray() => SumIEnumerable(intArray);
        [Benchmark]
        public int BenchmarkIEnumerableWithList() => SumIEnumerable(intList);
        [Benchmark]
        public int BenchmarkIListWithArray() => SumIList(intArray);
        [Benchmark]
        public int BenchmarkIListWithList() => SumIList(intList);
        [Benchmark]
        public int BenchmarkArray() => SumArray(intArray);
        [Benchmark]
        public int BenchmarkList() => SumList(intList);
    }
}

```

### Configuration

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.17763.1217 (1809/October2018Update/Redstone5)
Intel Core i7-5820K CPU 3.30GHz (Broadwell), 1 CPU, 12 logical and 6 physical cores
```

For CLR, they are .Net Core 3.1.2 and .Net Framework 4.8, while Core 2.0.7 is used as the baseline.

with a x64 system.

### Regression?

It is a regression from .Net Framework, while it seems the performance has been improved through the iterations of .Net Core.

### Data

Core 3.1.2

```
.NET Core SDK=3.1.300-preview-015135
  [Host]     : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
  DefaultJob : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT


|                        Method |      Mean |     Error |    StdDev |    Median |
|------------------------------ |----------:|----------:|----------:|----------:|
| BenchmarkIEnumerableWithArray | 455.98 us |  8.936 us | 13.375 us | 447.16 us |
|  BenchmarkIEnumerableWithList | 688.01 us | 13.573 us | 21.132 us | 678.09 us |
|       BenchmarkIListWithArray | 291.96 us |  5.831 us | 12.171 us | 291.65 us |
|        BenchmarkIListWithList | 252.48 us |  4.363 us |  3.643 us | 251.01 us |
|                BenchmarkArray |  65.95 us |  1.306 us |  2.947 us |  65.67 us |
|                 BenchmarkList |  64.40 us |  0.253 us |  0.197 us |  64.40 us |
```

Fw 4.8

```
  [Host]     : .NET Framework 4.8 (4.8.4180.0), X86 LegacyJIT
  DefaultJob : .NET Framework 4.8 (4.8.4180.0), X86 LegacyJIT


|                        Method |      Mean |    Error |    StdDev |    Median |
|------------------------------ |----------:|---------:|----------:|----------:|
| BenchmarkIEnumerableWithArray | 453.55 us | 7.733 us |  6.855 us | 452.85 us |
|  BenchmarkIEnumerableWithList | 504.19 us | 8.591 us |  6.707 us | 501.60 us |
|       BenchmarkIListWithArray | 250.92 us | 0.444 us |  0.347 us | 250.79 us |
|        BenchmarkIListWithList | 261.23 us | 5.177 us | 10.219 us | 259.70 us |
|                BenchmarkArray |  37.03 us | 0.739 us |  1.526 us |  36.64 us |
|                 BenchmarkList |  74.32 us | 1.445 us |  2.207 us |  72.89 us |
```

Core 2.0.7 (for reference)
```
.NET Core SDK=3.1.300-preview-015135
  [Host]     : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), X64 RyuJIT
  DefaultJob : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), X64 RyuJIT


|                        Method |      Mean |     Error |    StdDev |    Median |
|------------------------------ |----------:|----------:|----------:|----------:|
| BenchmarkIEnumerableWithArray | 613.55 us | 12.081 us | 22.985 us | 611.17 us |
|  BenchmarkIEnumerableWithList | 698.36 us |  4.131 us |  3.225 us | 697.30 us |
|       BenchmarkIListWithArray | 281.86 us |  5.598 us |  6.222 us | 279.01 us |
|        BenchmarkIListWithList | 293.34 us |  5.825 us | 13.500 us | 291.18 us |
|                BenchmarkArray |  64.54 us |  1.268 us |  2.648 us |  62.85 us |
|                 BenchmarkList |  65.61 us |  1.172 us |  1.825 us |  64.85 us |
```

**Comment by AndyAyersMS** [comment]
Odd, I don't see this locally. Generally things have stayed the same or improved with each release.

`BenchmarkIListWithList `  and `BenchmarkIEnumerableWithList` might have regressed from 3.1 to 5.0.

## Intel Core i7-8650U CPU 1.90GHz
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.959 (1909/November2018Update/19H2)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.8.20359.6
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.35809, CoreFX 5.0.20.35809), X64 RyuJIT
  Job-UVBDKF : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT
  Job-MLRJUL : .NET Core 2.1.16 (CoreCLR 4.6.28516.03, CoreFX 4.6.28516.10), X64 RyuJIT
  Job-TSYZVI : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.21406), X64 RyuJIT
  Job-PMCWQH : .NET Core 5.0.0 (CoreCLR 5.0.20.35809, CoreFX 5.0.20.35809), X64 RyuJIT
```
|                        Method |       Runtime |      Mean |     Error |    StdDev | Ratio | RatioSD |
|------------------------------ |-------------- |----------:|----------:|----------:|------:|--------:|
| BenchmarkIEnumerableWithArray |      .NET 4.8 | 561.50 us | 11.102 us | 11.879 us |  1.00 |    0.00 |
| BenchmarkIEnumerableWithArray | .NET Core 2.1 | 574.41 us |  5.018 us |  4.190 us |  1.03 |    0.02 |
| BenchmarkIEnumerableWithArray | .NET Core 3.1 | 510.82 us |  9.753 us |  9.578 us |  0.91 |    0.02 |
| BenchmarkIEnumerableWithArray | .NET Core 5.0 | 477.08 us |  7.008 us |  6.556 us |  0.85 |    0.02 |
|                               |               |           |           |           |       |         |
|  BenchmarkIEnumerableWithList |      .NET 4.8 | 720.87 us | 14.380 us | 30.017 us |  1.00 |    0.00 |
|  BenchmarkIEnumerableWithList | .NET Core 2.1 | 731.19 us |  9.537 us |  8.920 us |  0.99 |    0.06 |
|  BenchmarkIEnumerableWithList | .NET Core 3.1 | 699.52 us |  6.542 us |  6.120 us |  0.95 |    0.05 |
|  BenchmarkIEnumerableWithList | .NET Core 5.0 | 721.65 us |  9.204 us |  8.159 us |  0.98 |    0.05 |
|                               |               |           |           |           |       |         |
|       BenchmarkIListWithArray |      .NET 4.8 | 380.18 us |  7.579 us | 13.859 us |  1.00 |    0.00 |
|       BenchmarkIListWithArray | .NET Core 2.1 | 285.95 us |  4.130 us |  3.661 us |  0.74 |    0.03 |
|       BenchmarkIListWithArray | .NET Core 3.1 | 254.40 us |  2.148 us |  2.009 us |  0.66 |    0.03 |
|       BenchmarkIListWithArray | .NET Core 5.0 | 284.27 us |  1.927 us |  1.609 us |  0.73 |    0.03 |
|                               |               |           |           |           |       |         |
|        BenchmarkIListWithList |      .NET 4.8 | 345.72 us |  6.153 us |  5.756 us |  1.00 |    0.00 |
|        BenchmarkIListWithList | .NET Core 2.1 | 285.13 us |  4.329 us |  4.049 us |  0.82 |    0.02 |
|        BenchmarkIListWithList | .NET Core 3.1 | 285.95 us |  3.459 us |  3.236 us |  0.83 |    0.01 |
|        BenchmarkIListWithList | .NET Core 5.0 | 226.10 us |  4.218 us |  4.331 us |  0.66 |    0.02 |
|                               |               |           |           |           |       |         |
|                BenchmarkArray |      .NET 4.8 |  64.25 us |  1.211 us |  1.133 us |  1.00 |    0.00 |
|                BenchmarkArray | .NET Core 2.1 |  63.85 us |  1.205 us |  1.127 us |  0.99 |    0.03 |
|                BenchmarkArray | .NET Core 3.1 |  64.30 us |  1.201 us |  1.234 us |  1.00 |    0.03 |
|                BenchmarkArray | .NET Core 5.0 |  64.70 us |  0.118 us |  0.099 us |  1.01 |    0.01 |
|                               |               |           |           |           |       |         |
|                 BenchmarkList |      .NET 4.8 |  73.50 us |  1.398 us |  1.554 us |  1.00 |    0.00 |
|                 BenchmarkList | .NET Core 2.1 |  74.48 us |  1.438 us |  1.345 us |  1.01 |    0.02 |
|                 BenchmarkList | .NET Core 3.1 |  73.74 us |  1.448 us |  1.354 us |  1.00 |    0.02 |
|                 BenchmarkList | .NET Core 5.0 |  75.55 us |  0.565 us |  0.501 us |  1.03 |    0.02 |

I used `BenchmarkSwitcher` to allow BDN to compare perf across runtimes, eg via this `Main`
```C#
    public static void Main(string[] args)
    {
        var sw = BenchmarkSwitcher.FromAssembly(typeof(ListBenchmark).Assembly);
        var summary = sw.Run(args);
    }
```
and then run via
```
dotnet run -c Release -f net5.0 -- -f * --runtimes net48 netcoreapp2.1 netcoreapp3.1 netcoreapp5.0
```

Also tried this on a few other machines with similar results

## Intel Core i9-9900T CPU 2.10GHz

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.959 (1909/November2018Update/19H2)
Intel Core i9-9900T CPU 2.10GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.100-preview.4.20258.7
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.25106, CoreFX 5.0.20.25106), X64 RyuJIT
  Job-ZRVIVH : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT
  Job-SLKYRB : .NET Core 2.1.18 (CoreCLR 4.6.28801.04, CoreFX 4.6.28802.05), X64 RyuJIT
  Job-AFODOD : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT
  Job-DRVJYN : .NET Core 5.0.0 (CoreCLR 5.0.20.25106, CoreFX 5.0.20.25106), X64 RyuJIT
```

|                        Method |       Runtime |      Mean |     Error |    StdDev | Ratio | RatioSD |
|------------------------------ |-------------- |----------:|----------:|----------:|------:|--------:|
| BenchmarkIEnumerableWithArray |      .NET 4.8 | 504.52 µs |  8.411 µs |  7.868 µs |  1.00 |    0.00 |
| BenchmarkIEnumerableWithArray | .NET Core 2.1 | 505.87 µs |  8.134 µs |  7.609 µs |  1.00 |    0.02 |
| BenchmarkIEnumerableWithArray | .NET Core 3.1 | 396.46 µs |  4.819 µs |  4.508 µs |  0.79 |    0.02 |
| BenchmarkIEnumerableWithArray | .NET Core 5.0 | 401.82 µs |  1.832 µs |  1.714 µs |  0.80 |    0.01 |
|                               |               |           |           |           |       |         |
|  BenchmarkIEnumerableWithList |      .NET 4.8 | 672.72 µs |  6.498 µs |  6.079 µs |  1.00 |    0.00 |
|  BenchmarkIEnumerableWithList | .NET Core 2.1 | 707.34 µs | 11.347 µs | 10.614 µs |  1.05 |    0.02 |
|  BenchmarkIEnumerableWithList | .NET Core 3.1 | 700.70 µs |  9.040 µs |  8.456 µs |  1.04 |    0.02 |
|  BenchmarkIEnumerableWithList | .NET Core 5.0 | 646.45 µs |  4.149 µs |  3.881 µs |  0.96 |    0.01 |
|                               |               |           |           |           |       |         |
|       BenchmarkIListWithArray |      .NET 4.8 | 348.98 µs |  3.301 µs |  3.088 µs |  1.00 |    0.00 |
|       BenchmarkIListWithArray | .NET Core 2.1 | 241.81 µs |  0.829 µs |  0.648 µs |  0.69 |    0.01 |
|       BenchmarkIListWithArray | .NET Core 3.1 | 241.31 µs |  1.738 µs |  1.540 µs |  0.69 |    0.01 |
|       BenchmarkIListWithArray | .NET Core 5.0 | 241.92 µs |  0.922 µs |  0.770 µs |  0.69 |    0.01 |
|                               |               |           |           |           |       |         |
|        BenchmarkIListWithList |      .NET 4.8 | 346.49 µs |  4.010 µs |  3.751 µs |  1.00 |    0.00 |
|        BenchmarkIListWithList | .NET Core 2.1 | 242.58 µs |  1.846 µs |  1.727 µs |  0.70 |    0.01 |
|        BenchmarkIListWithList | .NET Core 3.1 | 241.16 µs |  1.637 µs |  1.452 µs |  0.70 |    0.01 |
|        BenchmarkIListWithList | .NET Core 5.0 | 215.35 µs |  1.855 µs |  1.735 µs |  0.62 |    0.01 |
|                               |               |           |           |           |       |         |
|                BenchmarkArray |      .NET 4.8 |  56.25 µs |  0.622 µs |  0.552 µs |  1.00 |    0.00 |
|                BenchmarkArray | .NET Core 2.1 |  56.25 µs |  0.380 µs |  0.337 µs |  1.00 |    0.01 |
|                BenchmarkArray | .NET Core 3.1 |  56.08 µs |  0.338 µs |  0.299 µs |  1.00 |    0.01 |
|                BenchmarkArray | .NET Core 5.0 |  56.19 µs |  0.415 µs |  0.368 µs |  1.00 |    0.01 |
|                               |               |           |           |           |       |         |
|                 BenchmarkList |      .NET 4.8 | 106.49 µs |  1.238 µs |  1.158 µs |  1.00 |    0.00 |
|                 BenchmarkList | .NET Core 2.1 | 107.65 µs |  0.851 µs |  0.711 µs |  1.01 |    0.01 |
|                 BenchmarkList | .NET Core 3.1 | 106.90 µs |  0.857 µs |  0.715 µs |  1.00 |    0.01 |
|                 BenchmarkList | .NET Core 5.0 | 107.19 µs |  0.736 µs |  0.689 µs |  1.01 |    0.02 |

## Intel Core i7-6700 CPU 3.40GHz

``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.959 (1909/November2018Update/19H2)
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.7.20366.6
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.36411, CoreFX 5.0.20.36411), X64 RyuJIT
  Job-HARFKH : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT
  Job-WHOLWB : .NET Core 2.1.15 (CoreCLR 4.6.28325.01, CoreFX 4.6.28327.02), X64 RyuJIT
  Job-EJJIXI : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  Job-ARBJIE : .NET Core 5.0.0 (CoreCLR 5.0.20.36411, CoreFX 5.0.20.36411), X64 RyuJIT
```

|                        Method |       Runtime |      Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------------ |-------------- |----------:|---------:|---------:|------:|--------:|
| BenchmarkIEnumerableWithArray |      .NET 4.8 | 497.24 us | 8.287 us | 7.346 us |  1.00 |    0.00 |
| BenchmarkIEnumerableWithArray | .NET Core 2.1 | 475.01 us | 4.501 us | 4.211 us |  0.96 |    0.02 |
| BenchmarkIEnumerableWithArray | .NET Core 3.1 | 370.81 us | 6.157 us | 5.142 us |  0.74 |    0.01 |
| BenchmarkIEnumerableWithArray | .NET Core 5.0 | 398.51 us | 2.779 us | 2.321 us |  0.80 |    0.01 |
|                               |               |           |          |          |       |         |
|  BenchmarkIEnumerableWithList |      .NET 4.8 | 600.68 us | 5.359 us | 4.751 us |  1.00 |    0.00 |
|  BenchmarkIEnumerableWithList | .NET Core 2.1 | 604.23 us | 5.969 us | 5.583 us |  1.01 |    0.01 |
|  BenchmarkIEnumerableWithList | .NET Core 3.1 | 622.42 us | 4.266 us | 3.991 us |  1.04 |    0.01 |
|  BenchmarkIEnumerableWithList | .NET Core 5.0 | 584.16 us | 5.450 us | 5.098 us |  0.97 |    0.01 |
|                               |               |           |          |          |       |         |
|       BenchmarkIListWithArray |      .NET 4.8 | 319.18 us | 3.713 us | 3.473 us |  1.00 |    0.00 |
|       BenchmarkIListWithArray | .NET Core 2.1 | 239.81 us | 2.318 us | 1.936 us |  0.75 |    0.01 |
|       BenchmarkIListWithArray | .NET Core 3.1 | 239.64 us | 2.111 us | 1.871 us |  0.75 |    0.01 |
|       BenchmarkIListWithArray | .NET Core 5.0 | 239.39 us | 1.899 us | 1.684 us |  0.75 |    0.01 |
|                               |               |           |          |          |       |         |
|        BenchmarkIListWithList |      .NET 4.8 | 291.36 us | 3.474 us | 3.250 us |  1.00 |    0.00 |
|        BenchmarkIListWithList | .NET Core 2.1 | 237.62 us | 2.339 us | 2.073 us |  0.82 |    0.01 |
|        BenchmarkIListWithList | .NET Core 3.1 | 213.08 us | 2.038 us | 1.807 us |  0.73 |    0.01 |
|        BenchmarkIListWithList | .NET Core 5.0 | 236.96 us | 2.668 us | 2.365 us |  0.81 |    0.01 |
|                               |               |           |          |          |       |         |
|                BenchmarkArray |      .NET 4.8 |  55.50 us | 0.420 us | 0.373 us |  1.00 |    0.00 |
|                BenchmarkArray | .NET Core 2.1 |  55.84 us | 0.562 us | 0.526 us |  1.01 |    0.01 |
|                BenchmarkArray | .NET Core 3.1 |  56.22 us | 0.247 us | 0.207 us |  1.01 |    0.01 |
|                BenchmarkArray | .NET Core 5.0 |  55.61 us | 0.677 us | 0.633 us |  1.00 |    0.01 |
|                               |               |           |          |          |       |         |
|                 BenchmarkList |      .NET 4.8 |  62.21 us | 0.799 us | 0.708 us |  1.00 |    0.00 |
|                 BenchmarkList | .NET Core 2.1 |  63.90 us | 0.335 us | 0.280 us |  1.03 |    0.01 |
|                 BenchmarkList | .NET Core 3.1 |  63.95 us | 0.563 us | 0.499 us |  1.03 |    0.01 |
|                 BenchmarkList | .NET Core 5.0 |  65.83 us | 1.281 us | 2.175 us |  1.08 |    0.05 |

**Comment by karakasa** [comment]
> Job-UVBDKF : .NET Framework 4.8 (4.8.4180.0), X64 RyuJIT

Is .NET fw 4.8 utilizing RyuJIT? I was using LegacyJIT.

**Comment by AndyAyersMS** [comment]
> Is .NET fw 4.8 utilizing RyuJIT? I was using LegacyJIT.

Ah. You can't really cross-compare x86 vs x64 numbers like this and then say there's a regression. 
All other things being equal, x86 will typically be a bit faster than x64 as more data will fit in the cache.

You should compare x86 to x86 or x64 to x64.

**Comment by AndyAyersMS** [comment]
I was curious what the x86-x86 comparisons looked like -- here is some data. If you compare with the first result I posted above you can see x86 is generally faster than x64.

Eg for net5.0 on BenchmarkList, x86 69.27 us is and x64 is 75.55 us

Also seems like for x86 there might be some regression in .Net Core on x86 vs net48 on those first two tests.

```ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.959 (1909/November2018Update/19H2)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-rc.1.20407.13
  [Host]     : .NET Core 5.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X86 RyuJIT
  Job-ZOTQPH : .NET Framework 4.8 (4.8.4180.0), X86 LegacyJIT
  Job-WQLXNZ : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X86 RyuJIT
  Job-AXIUPO : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X86 RyuJIT
```

|                        Method |       Runtime |      Mean |     Error |    StdDev |    Median | Ratio | RatioSD |
|------------------------------ |-------------- |----------:|----------:|----------:|----------:|------:|--------:|
| BenchmarkIEnumerableWithArray |      .NET 4.8 | 455.41 us |  8.747 us |  8.982 us | 454.74 us |  1.00 |    0.00 |
| BenchmarkIEnumerableWithArray | .NET Core 3.1 | 560.33 us | 11.093 us | 29.991 us | 554.35 us |  1.24 |    0.06 |
| BenchmarkIEnumerableWithArray | .NET Core 5.0 | 492.14 us |  9.563 us |  7.986 us | 491.23 us |  1.09 |    0.02 |
|                               |               |           |           |           |           |       |         |
|  BenchmarkIEnumerableWithList |      .NET 4.8 | 572.76 us | 10.947 us | 10.240 us | 573.55 us |  1.00 |    0.00 |
|  BenchmarkIEnumerableWithList | .NET Core 3.1 | 825.61 us | 16.003 us | 20.238 us | 818.44 us |  1.44 |    0.05 |
|  BenchmarkIEnumerableWithList | .NET Core 5.0 | 743.81 us | 14.768 us | 38.120 us | 729.07 us |  1.33 |    0.06 |
|                               |               |           |           |           |           |       |         |
|       BenchmarkIListWithArray |      .NET 4.8 | 278.80 us |  5.535 us | 13.155 us | 278.13 us |  1.00 |    0.00 |
|       BenchmarkIListWithArray | .NET Core 3.1 | 215.97 us |  6.335 us | 17.973 us | 212.64 us |  0.79 |    0.07 |
|       BenchmarkIListWithArray | .NET Core 5.0 | 259.24 us |  4.522 us |  9.031 us | 256.12 us |  0.93 |    0.06 |
|                               |               |           |           |           |           |       |         |
|        BenchmarkIListWithList |      .NET 4.8 | 335.57 us |  6.643 us | 16.169 us | 331.11 us |  1.00 |    0.00 |
|        BenchmarkIListWithList | .NET Core 3.1 | 237.33 us |  4.722 us | 11.847 us | 234.50 us |  0.71 |    0.05 |
|        BenchmarkIListWithList | .NET Core 5.0 | 237.29 us |  4.732 us | 11.519 us | 232.89 us |  0.71 |    0.05 |
|                               |               |           |           |           |           |       |         |
|                BenchmarkArray |      .NET 4.8 |  53.22 us |  2.656 us |  7.662 us |  52.65 us |  1.00 |    0.00 |
|                BenchmarkArray | .NET Core 3.1 |  42.65 us |  0.847 us |  1.612 us |  42.22 us |  0.79 |    0.09 |
|                BenchmarkArray | .NET Core 5.0 |  42.19 us |  0.804 us |  1.228 us |  41.80 us |  0.78 |    0.09 |
|                               |               |           |           |           |           |       |         |
|                 BenchmarkList |      .NET 4.8 | 134.35 us | 10.914 us | 32.181 us | 127.72 us |  1.00 |    0.00 |
|                 BenchmarkList | .NET Core 3.1 |  63.41 us |  1.832 us |  5.166 us |  62.15 us |  0.49 |    0.11 |
|                 BenchmarkList | .NET Core 5.0 |  69.27 us |  1.341 us |  1.317 us |  69.26 us |  0.72 |    0.08 |

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib if anyone wants to dig into the possible regressions.
