### ISSUE TITLE
Constrain X509ChainPolicy.UrlRetrievalTimeout to acceptable ranges

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#40578]
The [`X509ChainPolicy.UrlRetrievalTimeout`][1] property is a `TimeSpan` that currently does not throw when given a value less than zero, or `TotalMilliseconds` larger than `int.MaxValue`. A negative value for this property behaves differently from Linux and Windows. Linux treats a negative value as-is and every network operation during chain building will time out (all time-budget has been used). Windows ends up treating the negative value as an unsigned value, so -1 ends up being treated as `uint.MaxValue` for example. However, Win32 appears to cap the value at 1 minute anyway, so all negative values are currently being treated as 1 minute.

I propose that the `set` for `UrlRetrievalTimeout` throw an `ArgumentOutOfRangeException` if it is less than zero or greater than `TimeSpan.FromMilliseconds(int.MaxValue)`. Using a negative value likely isn't intentional and more likely a `DateTime` arithmetic mistake or a typo. Using a large value like `TimeSpan.MaxValue` may be done as an attempt to have no timeout.

This would be a breaking behavioral change, though a small one in my opinion.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.urlretrievaltimeout?view=netcore-3.1

**Comment by vcsjones** [comment]
Does this need to go throw API review?

**Comment by bartonjs** [comment]
@GrabYourPitchforks Do you have thoughts here?  The "compat, compat everywhere" voice in my head says that we should just unify that negative numbers mean one minute.  But as an API designer I agree that an ArgumentOutOfRangeException in the setter is what the original implementation should have had.

One possible answer is to wait another week and change it as the first break for 6; though I handwavily feel that it's better to break it in 5 than 6-preview.

**Comment by vcsjones** [comment]
> unify that negative numbers mean one minute

It's technically the max of whatever that version of Windows is willing to tolerate. I have no idea if the cap is say, 5 minutes on Windows 7 / 8, then negative number corresponds to 5 minutes.
