### ISSUE TITLE
RegexOptions.Multiline not matching text

### ISSUE THREAD

**Issue by VS-ux** [dotnet/runtime#40577]
### Description

* Using RegexOptions.Multiline on a string with \r\n fails with this regex:
^(?:[a-zA-Z]\:|\\\\[\w\.]+\\[\w.$]+)\\(?:[\w]+\\)*\w([\w.])+$

### Configuration

* .NET Core 3.1
* Windows 10 20180
* x64
* It is not specific to this config.

### Regression?

* Did this work in a previous build or release of .NET Core, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
No.

### Other information

* This is a duplicate of #40566. In that test, I thought it was due to the \r match failing. However, in this test, I'm using \r\n

```
string textToMatch = "C:\\testpath1.txt\r\nC:\\testpath2.txt";
int matchCount = Regex.Matches(textToMatch, @"^(?:[a-zA-Z]\:|\\\\[\w\.]+\\[\w.$]+)\\(?:[\w]+\\)*\w([\w.])+$", RegexOptions.Compiled | RegexOptions.Multiline).Count;

Console.WriteLine(matchCount); // 1, but if you swap \r\n with \n, it returns 2

**Comment by danmosemsft** [comment]
Can you please try to minimize the repro code/pattern/text? Like last time, this often makes things clearer.

**Comment by VS-ux** [comment]
@danmosemsft Hi! The text is just above.
Here it is again:
```
string textToMatch = "C:\\testpath1.txt\r\nC:\\testpath2.txt";
int matchCount = Regex.Matches(textToMatch, @"^(?:[a-zA-Z]\:|\\\\[\w\.]+\\[\w.$]+)\\(?:[\w]+\\)*\w([\w.])+$", RegexOptions.Compiled | RegexOptions.Multiline).Count;

Console.WriteLine(matchCount); // 1, but if you swap \r\n with \n, it returns 2
```

**Comment by danmosemsft** [comment]
Yes thanks I see that I’m asking you to minimize the pattern please.

**Comment by VS-ux** [comment]
Oops, sorry. Ok here is the simplified version:

```
string textToMatch = "hello\r\nasd";
int matchCount = Regex.Matches(textToMatch, @"^[a-z]+$", RegexOptions.Compiled | RegexOptions.Multiline).Count;

Console.WriteLine(matchCount); // 1, but if you swap \r\n with \n, it returns 2
```

The issue is that RegexOptions.Multiline doesn't get rid of \r so it matches 1 character too much.

**Comment by danmosemsft** [comment]
Right, it only understands \n. The complete description is here:
https://github.com/dotnet/runtime/issues/25598#issuecomment-666955410
Do the docs need clarification? Feel free to submit a PR if so (pencil icon in top right of doc).

I’m going to close this as it’s working as designed. The AnyNewLine feature would help!
