### ISSUE TITLE
[System.XML] Assembly.GetEntryAssembly().Location can cause a NullRef

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#40588]
### Description

This code within [System.Xml.Serialization.Compilation](https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs#L166), tries to retrieve Assembly.GetEntryAssembly() which can return null if the host is native. The exceptions are handled, but there are cases where an AV (NullRef in the case) can bring down the process

### Configuration

Office ran into this since they use a native host and a recent OS change seems to be hijacking the exception handling causing a crash. 

### Regression?

No, this reproed in 3.1 too

### Other information

Just checking for null before .Location should most likely work.

**Comment by jkotas** [comment]
> here are cases where an AV (NullRef in the case) can bring down the process

This is a bug in the runtime that we need to fix. There will be many other cases where Office will hit this bug.

Still, it would be nice to avoid null reference exception here when the runtime is hosted and `Assembly.GetEntryAssembly()` returns null.

**Comment by danmosemsft** [comment]
Do we need a separate issue for the runtime fix?

**Comment by jkotas** [comment]
Yes, there is an ongoing offline investigation and we do not know enough details yet to open a meaningful issue.
