### ISSUE TITLE
ILVerify plans and progress

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/runtime#40586]
Looking around the old issues in CoreRT and in this repo, I find several mentions that ILVerify is (probably) up for rtm in the .NET 5.0 release cycle. However, there appears to be very little activity since about 2 years ago.

Since PEVerify doesn't support many new CLR features, we find ourselves in a limbo between the alpha version of ILVerify and the not further developed, closed source PEVerify. 

This tool is vital for just about any project that emits CIL. The current option is to use the old PEVerify as long as no new features are used, and the new one for those cases that are already covered. The rest has to be left unverified (unless there's another tool in the infrastructure that I'm unaware of). 

Which brings me to the question at hand: is ILVerify still on the roadmap? Is it going to be dropped? Is there some other way to verify assemblies?

**Comment by jkotas** [comment]
We have started publishing ILVerify as dotnet tool as for .NET 5. Here are the instructions for how to use it from .NET 5 previews:

https://github.com/dotnet/runtime/tree/master/src/coreclr/src/tools/ILVerify#how-to-use-ilverify

**Comment by jkotas** [comment]
If there are specific enhancements you would like to see added to ILVerify, it is best to create specific issues for each enhancements.

**Comment by abelbraaksma** [comment]
@jkotas, I was mainly concerned with the present state of the tool. If it's finished and production ready, that's awesome, but several posts and references say otherwise. In fact, the page you linked says that a lot isn't implemented yet. 

I agree that specific issues are more useful, but if the project is very much under development, and implies itself something like "we're nearly halfway there", then there's not (yet) much use to apply it in business scenarios and report every missing feature. 

Quote from you linked page:

Currently every IL command falls into one of these categories:

* Not implemented: the implementation is completely missing. The easiest way is to pick one of them (look for NotImplentedException in the code) and implement it. First you should 100% understand the spec. (see ECMA-335), then try to port an existing implementation (sources below).
* Partially implemented: These are typically methods with TODOs in it. As the first phase we want to make sure that for every command the stack is correctly maintained, therefore for some commands we either have no verification or we have only a not complete verification.
* You can also pick one of these and finish it.
Implemented: find and fix bugs ;) .

**Comment by jkotas** [comment]
I have fixed the README. All IL instructions have at least the basic functionality implemented by now.

There are places (typically marked with TODOs) that can be improved, but they should not prevent the tool from being usable.

> production ready,

The ILVerify is a tool to help compiler developers find issues in the generated IL. I expect it to be used at development time. I do not expect it to be really deployed in production.

**Comment by abelbraaksma** [comment]
>  I expect it to be used at development time. I do not expect it to be really deployed in production.

@jkotas  Sorry, that's what I meant. To use it to check IL of compiler output. It's vital to be able to check it's verifiable, and that check should be reliable and stable. But if it's currently used internally for, say, C#, I think it's time to start an issue for F# as well, so we can move away from peverify (which only works on framework anyway).

If we find issues, I'll report them separately.

**Comment by abelbraaksma** [comment]
Thanks for updating the Readme :)
