### ISSUE TITLE
'Group' does not contain a definition for 'Name'

### ISSUE THREAD

**Issue by tschqr** [dotnet/runtime#40595]
Start a new project with `dotnet new classlib`. Try to use the `Name` attribute of `System.Text.RegularExpressions.Group`, for example with something like

```
using System.Text.RegularExpressions;

namespace GroupBug
{
    public class Class1
    {
        public static (string Name, string Value) Foo()
        {
            var m = new Regex(@"n(?<x>.)").Match("Why no name?");
            /* This should return ("x", "o") */
            return (m.Groups[1].Name, m.Groups[1].Value);
        }
    }
}
```

The build fails.

```
Class1.cs(11,33): error CS1061: 'Group' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'Group' could be found (are you missing a using directive or an assembly reference?) [E:\GroupBug\GroupBug.csproj]
```

Start another project with `dotnet new console` and try the exact same code, with a `Main` that calls `Console.WriteLine(Foo());`, and it works.

I found a possible workaround, changing the `TargetFramework` in my library's csproj file from `netstandard2.0` to `netcoreapp3.1`, but I don't know what problems I might be causing for my future self by doing that.

```
dotnet --version
3.1.302
```

**Comment by huoyaoyuan** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.group.name?view=netcore-3.1#moniker-applies-to

To use the property, it must be present in your target framework. So changing it from `netstandard2.0` to `netcoreapp3.1` is not "workaround", but "right solution".

**Comment by svick** [comment]
As you can see from [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.group.name#moniker-applies-to), `Group.Name` is only available in .Net Standard 2.1, .Net Core 1.1+ and .Net Framework 4.7+. This means that if you need this property, the right fix will involve changing the `TargetFramework`. Some possible values are:

* `<TargetFramework>netcoreapp1.1</TargetFramework>` (or higher). This means your library will only work on .Net Core (and .Net 5+).
* `<TargetFramework>netstandard2.1</TargetFramework>`. With this, the library will work [on .Net Core 3.0 and recent versions of Xamarin](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md#platform-support).
* `<TargetFrameworks>netcoreapp1.1;net47;netcoreapp1.1</TargetFrameworks>`. With this, the library will work on any framework that supports `Group.Name`.

**Comment by tschqr** [comment]
Hmm, documentation looks different when Javascript is enabled. Yes, this makes sense.
