### ISSUE TITLE
should mono support .netcore profiler api or tools? 

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#40609]
should mono support .netcore profiler api or tools?

I found that the mono have not fixed the profiler on windows as this issue(https://github.com/mono/mono/issues/14258) show.

this is so said and terriable for who are using mono.

is there any solution about mono profiler?

**Comment by lambdageek** [comment]
Supported platforms will be able to use .NET Diagnostics tooling like `dotnet-counters` and `dotnet-trace` in .NET 6 https://github.com/dotnet/runtime/issues/46371
