### ISSUE TITLE
Test failure: System.Net.Tests.HttpWebRequestTest_Async.GetResponseAsync_ServerNameNotInDns_ThrowsWebException

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#40606]
failed in job: [runtime-libraries outerloop 20200809.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=762837&view=ms.vss-test-web.build-test-results-tab&runId=23695930&resultId=103352&paneView=debug)

Error message
~~~
Assert.Equal() Failure
Expected: NameResolutionFailure
Actual:   UnknownError


Stack trace
   at System.Net.Tests.HttpWebRequestTest.GetResponseAsync_ServerNameNotInDns_ThrowsWebException() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1412
--- End of stack trace from previous location ---
~~~

**Comment by MihaZupan** [comment]
Fails very frequently across all **amd64** queues since `2020-08-07`.
So far in #40338, #40108, #39201 and master

**Comment by ManickaP** [comment]
Hit in #39201

**Comment by antonfirsov** [comment]
> since `2020-08-07`.

@MihaZupan I'm terribly confused about date formats. Does this mean 8th of July or 7th of August? 

In the latter case I blame #40344. @geoffkizer it looks no OuterLoop test run happened in that PR.

**Comment by geoffkizer** [comment]
Yep, it's probably from my PR. Will take a look.

**Comment by MihaZupan** [comment]
7th of August 

I try to use the Y-M-D (instead of ?-?-Y) format as much as possible to avoid the month vs date confusion. Should have named the month though😄

**Comment by antonfirsov** [comment]
@MihaZupan `Y-M-D` should be the one and only valid date format, [everyone else](https://en.wikipedia.org/wiki/Date_format_by_country#/media/File:Date_format_by_country_NEW.svg) is wrong IMO.

**Comment by antonfirsov** [comment]
@geoffkizer could this do something with the fact that `NetworkError.InvalidAddress` is missing from your PR? (But not the API proposal)

**Comment by geoffkizer** [comment]
I don't think so. I think there's just some logic somewhere that's testing for HostNotFound and it's not mapping it correctly now. Shouldn't be hard to find.
