### ISSUE TITLE
Obsolete SuppressIldasmAttribute

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#40622]
__Edit by @GrabYourPitchforks__: This issue tracks only obsoleting the attribute, not any other ildasm.exe work.

```cs
namespace System.Runtime.CompilerServices
{
    [Obsolete("SuppressIldasmAttribute has no effect in .NET 6.0+ applications.")] // NEW attribute
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Module)]
    public sealed class SuppressIldasmAttribute : Attribute
    {
        public SuppressIldasmAttribute() { }
    }
}
```

(What text do we even put there? "This attribute never made any sense to begin with and has no valid use case."? I've based the text proposed above on the `DisablePrivateReflectionAttribute` obsoletion text already in 6.0.)

-----

It has no valid use case, the security against reverse engineering it provides is nonexistent and there are tons of tools that ignore it.

My proposal is to deprecate it per #33360 and modify ILDasm to stop honoring that attribute.

**Comment by vcsjones** [comment]
Related / duplicate: https://github.com/dotnet/runtime/issues/13341

**Comment by GrabYourPitchforks** [comment]
Reopening this issue, as we need a work item to track obsoleting this specific API.

**Comment by dotMorten** [comment]
I made a comment over here why I think this is a bad idea: https://github.com/dotnet/runtime/issues/13341#issuecomment-816778490

**Comment by bartonjs** [comment]
Approved as proposed, no custom diagnostic is needed.


```diff
namespace System.Runtime.CompilerServices
{
+   [Obsolete("SuppressIldasmAttribute has no effect in .NET 6.0+ applications.")]
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Module)]
    public sealed class SuppressIldasmAttribute : Attribute
    {
        public SuppressIldasmAttribute() { }
    }
}
```

**Comment by dotMorten** [comment]
@bartonjs What is the alternative for this feature then ?
![image](https://user-images.githubusercontent.com/1378165/118857134-8b7ba300-b88c-11eb-83de-bfcaeb89f366.png)

**Comment by GrabYourPitchforks** [comment]
There is no alternative. During API review we briefly touched on whether we want to rip out support entirely or require a "/force" switch. The conclusion was that .NET (which includes the BCL and SDK tools such as ildasm.exe) should simply drop all support.

Nothing in this proposal or in the merged PR prevents other disassemblers (such as Visual Studio) from continuing to honor the attribute. Those disassemblers can abort the operation, display a warning, or implement any other behavior that might be appropriate for their scenarios.
