### ISSUE TITLE
Idea: throw when an ILGenerator.Emit method overload is used with an invalid opcode.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#40620]
`ILGenerator.Emit` calls like `ilg.Emit(OpCodes.Constrained, 59);` and many others do not represent properly structured IL. It would be better if these `Emit` methods throw an exception when such invalid combination is attempted to be used, way before that IL is actually used.

It's technically not a breaking change since only abusers of the `ILGenerator` class will be affected.

**Comment by steveharter** [comment]
Emit does very little validation other than verifying the parameters are valid (non-null, etc) and doesn't verify opcode-specific values.

There are 200+ opcodes, so this would be a large effort to categorize and test.

Verifying per opcode would likely result in a large switch statement and\or dictionary which would have a significant perf hit, so based on this alone I don't think this is feasible.

**Comment by jkotas** [comment]
Ultimately, it would mean reimplementing a large part of https://github.com/dotnet/runtime/tree/master/src/coreclr/src/tools/ILVerify in Reflection.Emit.

I think more interesting way to approach is to figure out how ILVerify can be optionally plugged into Reflection.Emit.

**Comment by steveharter** [comment]
Instead of trying to hook the existing, low-level Emit() method we could add higher-level Emit() APIs that are per-opcode (or grouping combinations of) which would allow for faster validation without switches\dictionaries.

e.g. for the `OpCodes.Constrained` example:
```cs
public static class ILEmitOpcodes
{
    void Constrained(ILGenerator generator, Type type); // Only allow a Type parameter
    // Another 100-200 methods here...
}
```

**Comment by teo-tsirpanis** [comment]
> Verifying per opcode would likely result in a large switch statement and\or dictionary which would have a significant perf hit, so based on this alone I don't think this is feasible.

[Not necessarily.](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.operandtype) And that checker does not need to be exhaustive; some opcode combination edge cases can pass it.
