### ISSUE TITLE
System.DivideByZero exception in System.Threading.FastRandom.Next(Int32 maxValue)

### ISSUE THREAD

**Issue by torqdev** [dotnet/runtime#40639]
# Issue Title

A DivideByZeroException was thrown by the FastRandom.Next method in the System.Threading dll on dotnet Core 3.1

# General

This is kind of a one-off, I don't know what the value passed in as maxValue since the symbols weren't loaded when the exception was thrown but after loading the exception was thrown with this information:

```
System.DivideByZeroException
  HResult=0x80020012
  Message=Attempted to divide by zero.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.FastRandom.Next(Int32 maxValue) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 723
   at System.Threading.ThreadPoolWorkQueue.Dequeue(ThreadPoolWorkQueueThreadLocals tl, Boolean& missedSteal) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 513
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 605
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
```

At the following code:

```c#
    // Simple random number generator. We don't need great randomness, we just need a little and for it to be fast.
    internal struct FastRandom // xorshift prng
    {
        private uint _w, _x, _y, _z;

        public FastRandom(int seed)
        {
            _x = (uint)seed;
            _w = 88675123;
            _y = 362436069;
            _z = 521288629;
        }

        public int Next(int maxValue)
        {
            Debug.Assert(maxValue > 0);

            uint t = _x ^ (_x << 11);
            _x = _y; _y = _z; _z = _w;
            _w = _w ^ (_w >> 19) ^ (t ^ (t >> 8));

            return (int)(_w % (uint)maxValue); // System.DivideByZero exception thrown here
        }
    }
```

**Comment by kouvel** [comment]
I don't see how this can happen normally. Might be some sort of corruption. Could you please take a crash dump if it happens again? See https://github.com/dotnet/runtime/issues/40640#issuecomment-671643587.

**Comment by IronSean** [comment]
@kouvel sent you a crash dump.

**Comment by danmosemsft** [comment]
@stephentoub fixed by your change maybe?

**Comment by stephentoub** [comment]
This exception shouldn't have been possible in the first place: I agree with @kouvel's assessment that it was likely some sort of corruption. That said, if it was possible for `c` to be 0, then the issue still exists even after my change that deletes `FastRandom`, as we're still `%`'ing by `c`.

**Comment by danmosemsft** [comment]
@kouvel is this tractable at this point or should we close?

**Comment by kouvel** [comment]
There should at least be one queue in the list since the thread that is trying to steal should have its own queue in the list. Closing for now.
