### ISSUE TITLE
TLS 1.0 + 1.1 support past end-of-life in HttpClientHandler

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [dotnet/runtime#40647]
Want to check-in (i.e. this is just a question) on the effects of end-of-life for TLS 1.0 + 1.1 come Q3 | Q4 2020 to how Kestrel handles default SllProtocols.  It looks all versions of TLS will still be available when handling client requests (at least peeking at the test cases for HttpClientHandler).  Interpret the end-of-life for TLS 1.0 + 1.1 as a browser restriction not a general Http client restriction and thus not the same effect on the dotnet runtime.  Are there an plans to start dropping older versions of TLS in Kestrel via the dotnet runtime?

**Comment by wfurt** [comment]
If this is really question about Kestrel, this is wrong repo @MatthewDavidCampbell . https://github.com/dotnet/aspnetcore would be better place IMHO. 
As far as SslStream, the support will depend on underlying OS platform and OS configuration.

**Comment by MatthewDavidCampbell** [comment]
@wfurt Yes.  Looked at the test cases with SslStream.  Closing this question.
