### ISSUE TITLE
Unable to draw certain string

### ISSUE THREAD

**Issue by aijkl** [dotnet/runtime#40650]
### Unable to draw certain string
Contents that can be drawn on Windows cannot be drawn on Debian.
Is this a bug in the Graphics class?
If the last character is a specific symbol, it cannot be drawn. The symbol I am checking now is 》.

Is there anyone other than me who has the same symptoms with .NET Core 3.0 Debian Noto Sans JP?
This happens even without using Japanese fonts. English is the same.

```
namespace TEST
{
    class Program
    {
        static void Main(string[] args)
        {
            using Bitmap bitmap = new Bitmap(500, 500);
            using Graphics graphics = Graphics.FromImage(bitmap);
            Font font = new Font("Noto Sans JP", 15);

            graphics.DrawString("Hello .NET《Core》", font, Brushes.Black, new Point(10, 30)); //Failure
            graphics.DrawString("Hello .NET《Core》*****", font, Brushes.Black, new Point(10, 50));//Success
            graphics.DrawString("Hello .NET(Core)", font, Brushes.Black, new Point(10, 70));//Success
            bitmap.Save($"{Directory.GetCurrentDirectory()}{Path.DirectorySeparatorChar}test.jpeg");
        }
    }
}
```

### Configuration
Runtime .NET Core 3.0
OS  Debian
Font  Noto Sans JP

### Other information

No exception thrown
![test](https://user-images.githubusercontent.com/51302983/89897968-da6c1c00-dc1a-11ea-89f5-dcabb0ffee91.jpeg)

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
