### ISSUE TITLE
CollectionAssert.AreEqual does not compare the types of the collections

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/runtime#40653]
### Description

I have written a unit test that contains the following line:
```cs
CollectionAssert.AreEqual (new byte[0], CBitConverter.ToWords (inAB_0, OFF, OFF, OFF));
```

From the name of the method you should already be able to see that this code is wrong. The method `ToWords` creates a `ushort[]`, but the test compares it to a `byte[]`.
This test should fail, but it actually passes, because `CollectionAssert.AreEqual()` works as specified in the documentation:

> Tests whether the specified collections are equal and throws an exception if the two collections are not equal. **Equality is defined as having the same elements in the same order and quantity.** Different references to the same value are considered equal.

In my opinion, this definition of equality is wrong, because it does not include the type of the collection. I would consider this a bug.
It is possible to create and use an own comparer or an own test method (like below), and that's what I just did to continue my work until the failure is fixed, but this is just a workaround to what is missing in the code.

### Configuration

C#
.Net Framework 4.8
VS 2019 (v.16.5.5)

### Workaround
```cs
///-------------------------------------------------------------------
/// \<summary>
/// Check if the given collections are equal and have the same type.
/// \</summary>
/// <param name="i_expected">The expected collection.</param>
/// <param name="i_actual">The actual collection.</param>
///-------------------------------------------------------------------
public static void AreEqualWithType (ICollection i_expected, ICollection i_actual)
{
  CollectionAssert.AreEqual (i_expected, i_actual);
  if (i_expected?.GetType () != i_actual?.GetType ())
    Assert.Fail ($"The type '{i_actual?.GetType ()}' of the actual collection does not match the expected type '{i_expected?.GetType ()}'.");
}
```

**Comment by Clockwork-Muse** [comment]
This was almost certainly done to make it **easier** to test the output of most methods.  For instance, some objects may use and return an internal type, exposing only that they use the `ICollection` (or some other derived) interface - you won't be able to check the type there.
Note that it's _rare_ that the type of the collection matters - if it does, you would want an explicit type check test, independent of the contents of the collection.

**Comment by TobiasKnauss** [comment]
@Clockwork-Muse: I see. This makes sense. I'll use my "workaround" then.
Well, they could/should have added this explanation to their documentation. @jeffschwMSFT: since you from Microsoft have read this already, please notify your colleagues to improve the documentation.

**Comment by danmosemsft** [comment]
@TobiasKnauss  this isn’t the right place for feedback on vs test docs. The topic should have a pencil icon in the top right: you can click that to edit it. Or open an issue in the same repo (but edits are best of all)

**Comment by TobiasKnauss** [comment]
@danmosemsft I know, but this feedback is related to this issue, so I just added it here.
I am not going to edit the doc, because I am not expert enough to write documentation about .Net that is read by thousands of developers. This is your job.
