### ISSUE TITLE
Crossgened assembly - Ready to Run disabled in log

### ISSUE THREAD

**Issue by movedoa** [dotnet/runtime#40683]
.NET Core 3.1

For our usecase we are generating dynamic assemblies with a custom written tool.
To improve the startup performance we want to use crossgen on the generated assemblies since the startup performance is a real neckbreaker in our use case since we are executing a lot of processes with the same assemblies over and over again. (Sadly we can't change that). So most of the time we run in a cold start scenario.

Executing crossgen.exe on our generated dlls works without problems but when we load these assemblies at runtime with Assembly.LoadFile, in the COMPlus_ReadyToRunLogFile all we see is "Ready to Run disabled - collectible module: %asssemblypath%" for all these dlls.

Why is ready to run disabled for these assemblies?
Is there a solution for this problem?

**Comment by davidwrighton** [comment]
ReadyToRun is disabled in the presence of collectible assemblies. The solution here would be to pass false for the `isCollectible` parameter to the constructor for the AssemblyLoadContext that you are using. Or, if you need ReadyToRun support for collectible assemblies, to write up a feature request. We may be able to consider such an issue for .NET 6.

**Comment by movedoa** [comment]
Thx for the quick answer.

So if understand you correctly, afaik assembly unloading requires iscollectible, ao currently there is no way to unload a r2r assembly?

**Comment by davidwrighton** [comment]
Correct. While it is certainly a feature that we could implement, and there are obvious reasons why it would be desirable, our current implementation does not support the combination of these features.
