### ISSUE TITLE
Runtime instance cookie from advertise protocol is different than from GetProcessInfo command

### ISSUE THREAD

**Issue by jander-msft** [dotnet/runtime#40696]
The diagnostics server in the runtime reports its runtime instance cookie via the advertise protocol when it connects to a diagnostic tool that is in listening mode. The serialization of this runtime instance cookie occurs [here](https://github.com/dotnet/runtime/blob/96d34c2f2a8d7d4ba9d07c221cc61bf156410348/src/coreclr/src/vm/diagnosticsprotocol.h#L146).

The diagnostics server in the runtime as provides its runtime instance cookie via the GetProcessInfo command when an external tool issues this command via the diagnostic port. The serialization of this runtime instance cookie occurs [here](https://github.com/dotnet/runtime/blob/82d7d5fc58dcfbf5fd226c34a7c521565a3fb58c/src/coreclr/src/vm/processdiagnosticsprotocolhelper.cpp#L96).

It seems that the cookie returned by the advertise protocol is partially different from the cookie returned from the result of the GetProcessInfo command.

An example of the difference of the values is:
| Source | Value |
|---|---|
| Advertise protocol | cf3642da-628e-70b0-bfac-674c838fb60e |
| GetProcessInfo command | 70b0628e-cf36-42da-bfac-674c838fb60e |

I believe the issue is that the different sources serialize it differently and cause certain fields to be reordered incorrectly.

CC @dotnet/dotnet-diag @josalem

**Comment by josalem** [comment]
Whoops!  Should be an easy fix.  I'll have a PR up soon.
