### ISSUE TITLE
why Microsoft.Extensions.Configuration.Json use SortedDictionary?

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#40697]
[`Microsoft.Extensions.Configuration.Xml`](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Configuration.Xml/src/XmlStreamConfigurationProvider.cs#L33) and [`Microsoft.Extensions.Configuration.Ini`](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Configuration.Ini/src/IniStreamConfigurationProvider.cs#L28) use `Dictionary`, [`Microsoft.Extensions.Configuration.Json`](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L16) use `SortedDictionary` rather than `Dictionary`, why are they different?

**Comment by Clockwork-Muse** [comment]
I don't know, but frankly, I'd be far more worried [about this line](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L65):

```csharp
                case JsonValueKind.Array:
                    int index = 0;
                    foreach (JsonElement arrayElement in value.EnumerateArray()) {
                        EnterContext(index.ToString()); // This line
                        VisitValue(arrayElement);
                        ExitContext();
                        index++;
                    }
                    break;
```
... because that's going to be subject to culture shenanigans (now your config keys depend on the culture of the process used to read the file).  Was that the intention?

**Comment by maryamariyan** [comment]
cc: @HaoK

**Comment by WeihanLi** [comment]
Nice catch, and it's `Dictionary` now

https://github.com/dotnet/runtime/blob/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L16
