### ISSUE TITLE
RCS1242: Do not pass non-read-only struct by read-only reference

### ISSUE THREAD

**Issue by elachlan** [dotnet/runtime#40692]
### Description
I installed Roslynator and it found many references of `RCS1242: Do not pass non-read-only struct by read-only reference`
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1242.md

I was wondering if this is a legitimate issue:
https://github.com/dotnet/runtime/blob/a2df15627fb7384f7c643cc8ba2ad2a55968e288/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs#L230-L243

https://github.com/dotnet/runtime/blob/a2df15627fb7384f7c643cc8ba2ad2a55968e288/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs#L1287-L1294

**Comment by jkotas** [comment]
System.Guid is mostly read-only, but it is non-trivial to mark it as read-only.

https://github.com/dotnet/runtime/issues/1718 and  https://github.com/dotnet/runtime/pull/1809 are related / duplicates.

I do not see legitimate issue here.

**Comment by danmosemsft** [comment]
Thanks for opening.
