### ISSUE TITLE
Add tests for System.Diagnostics.Process.Responding

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#40703]
https://github.com/dotnet/runtime/pull/38385 added a test for `Process.Responding`, which however was disabled since it depends on the current implementation characteristics of Wordpad.

We should replace it with a test that consistently reproduces the behaviour.

**Comment by adamsitnik** [comment]
> Wordpad

@eiriktsarpalis did you mean notepad?

https://github.com/dotnet/runtime/blob/021e77650dde27619397bdb985db545896523fe6/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs#L1598-L1600

**Comment by eiriktsarpalis** [comment]
No, the PR referenced in #40703 relied on wordpad behaviour to produce a non-responsive process.

**Comment by adamsitnik** [comment]
@eiriktsarpalis thanks!

FWIW the commit that removed the test: https://github.com/dotnet/runtime/pull/38385/commits/c4d3ed52ed8c3763ab69dbc53376eca77e02abd4
