### ISSUE TITLE
Add test code coverage for Host.StopAsync

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#40700]
Issue tracks adding a missing test in Microsoft.Extensions.Hosting:

- [ ] in HostTests that verifies StopAsync() doesn't throw given a canceled token (assuming _hostedServices and _hostLifetime also don't throw).

More info: https://github.com/dotnet/runtime/pull/40426

cc: @steveharter @Marusyk

**Comment by WernerMairl** [comment]
What about this implementation ?
https://github.com/WernerMairl/runtime/tree/40700-testcoverage-host-stopasync ?

**Comment by maryamariyan** [comment]
I think the link is broken

**Comment by maryamariyan** [comment]
Sure, please go ahead if you'd like to open the PR.

**Comment by eerhardt** [comment]
Moving to 6.0, as this isn't necessary for 5.0.
