### ISSUE TITLE
No support to marshal Strings in structures to and from wchar_t.

### ISSUE THREAD

**Issue by sfoslund** [dotnet/runtime#40718]
---
**Issue moved from dotnet/sdk#12809**
- Please respond to @johndaintree.

---

_From @johndaintree on Thursday, August 6, 2020 2:28:49 PM_

I have a similar issue to the (now close, but not fixed) one made here:

https://github.com/dotnet/runtime/issues/8271#issuecomment-561912518

In that I have a lot of unmanaged code that uses structures that contain pointers to arrays of wchar_t. I'd like to be able to marshal these structures in an out of managed code as Strings.

However, there is no UnmanagedType field that will do this.  There is UnmanagedTtype.LPWStr, which will work for Windows (2 byte wchar_t), but no equivalent for the Unixes (which have a 4 byte wchar_t). The only portable option is to use UnmanagedType.LPUTF8Str but then I'll have to change all my unmanaged code (in multiple places) to cope.

Custom marshalling also doesn't work on fields in structures- otherwise I'd use that. I guess I could refactor all the code into functions with a parameter per field in the structure  - I believe that custom marshalling will work there. But it seems like a lot hoops to jump though where ( I reckon) the built in marshaller could do it.

**Comment by sfoslund** [comment]
---
**Issue moved from dotnet/sdk#12809**
- Please respond to @johndaintree.

---

_From @johndaintree on Thursday, August 6, 2020 2:31:35 PM_

It would also be great of System.Runtime.InteropServices.Charset could be similarly extended for use with P/Invoke.

**Comment by elinor-fung** [comment]
cc @jkoritzinsky This looks like a (potentially common) use case that would be enabled with the new struct marshalling design / attributes.

**Comment by jkoritzinsky** [comment]
Yes, the new struct marshalling code-gen should cover this scenario pretty well.

**Comment by AaronRobinsonMSFT** [comment]
We've no plans to update our built-in marshallers to support this. It is however something we will be taking into account with out DllImport source generator &ndash; see https://github.com/dotnet/runtime/issues/43060.
