### ISSUE TITLE
HttpContent Bad request {"error":{"message":"Mandatory parameter missed","error_key":null}}

### ISSUE THREAD

**Issue by RaphaelSilv** [dotnet/runtime#40720]
Hi folks, I'm trying to do a simple POST using HttpClient but I've been facing some issues with  `HttpRequestMessage.Content`. and `\n`
In short, if I hard code one of the required parameters without the `escape character`, for instance: 

```c#
string value = "lorem ipsum lorem ipsum lorem ipsum lorem ipsum";
request.Content = new StringContent("{\"requiredParameter\":\""+ value +"\}");
```
Everything works just fine.

However, if I concatenate the string as follows:

```c#
string value = "\norem ipsum \n" +
                       "lorem ipsum \n" +
                       "lorem ipsum\n";
or even
//string value = "\nlorem ipsum lorem ipsum lorem ipsum lorem ipsum";
request.Content = new StringContent("{\"requiredParameter\":\""+ value +"\}");
```
It doesn't and I get a Bad request:

```sh
Status code: BadRequest
{"error":{"message":"Mandatory parameter missed","error_key":null}}
```

### Already tried
**System.Text.Json.JsonSerializer.Serialize**

```c#
 var options = new JsonSerializerOptions
 {
           WriteIndented = true,
  };
string json = System.Text.Json.JsonSerializer.Serialize(value, options);
```
**StringBuilder** since it's more appropriate for extensive string manipulation.
```c#
string value1 = "\nlorem ipsum \n";
string value2 = "lorem ipsum \n";
string value3 = "lorem ipsum\n";

 stringBuilder.Append(value1);
 stringBuilder.Append(value2);
 stringBuilder.Append(value3);

request.Content = new StringContent("{\"requiredParameter\":\""+ stringBuilder.toString() +"\}");
```

and, **Encoding.UTF8, "application/json"**
```c#
request.Content = new StringContent("{\"requiredParameter\":\""+ value +"\", Encoding.UTF8, "application/json");
```
Didn't work.

A minimal repro:

```c#
static async Task<string> postAsync(Uri uri, string postContent)
{
    using (var httpClient = new HttpClient())
    {
        using (var request = new HttpRequestMessage(new HttpMethod("POST"), "https://www.url.com/"))
        {
                   request.Headers.TryAddWithoutValidation("authority", "www.url.com");
                   request.Headers.TryAddWithoutValidation("accept", "application/json, text/plain, */*");
                   request.Headers.TryAddWithoutValidation("x-oauth2-required", "true");                   

                   request.Content = new StringContent("{\"requiredParameter\":\""+ value +"\}");

                   return await response.Content.ReadAsStringAsync();
            }
      }
}                    

static async Task Main(string[] args)
{
    Uri uri = new Uri("www.uri.com");
    var postContent = GenerateDynamicStringContent(List<string> params);
    await PostAsync(uri, postContent);
}

```

What am I missing here?

**Comment by RaphaelSilv** [comment]
@dotnet/ncl @karelz could you help me properly move this issue?

**Comment by karelz** [comment]
@RaphaelSilv it is hard to guess what you're having troubles with. Did you try to create minimal repro?
For example, in your 2nd code snippet, the string concatenated is not the same as the string in 1st code snippet (there are missing spaces). Is that making a difference?
As minimal repro I would use values as "a" and "b" to clarify where the problem lies.

**Comment by RaphaelSilv** [comment]
@karelz, I apologize for the lack of info. Also, I've omitted an important element in my question: the `\n` character which I realize is the origin of my issue. I've already updated the question and added a minimal repro as well.

**Comment by layomia** [comment]
cc @Jozkee

**Comment by geoffkizer** [comment]
I don't see anything that indicates this is an HttpClient bug. If you think there's a bug here, you need to be more specific about what you think the bug is.

**Comment by ManickaP** [comment]
> It doesn't and I get a Bad request:
>
> ```
> Status code: BadRequest
> {"error":{"message":"Mandatory parameter missed","error_key":null}}
> ```

This seems like `HttpClient` is perfectly fine and you're getting an error from the server.
AFAIK `HttpClient` doesn't create `BadRequest` on its own.

**Comment by RaphaelSilv** [comment]
I appreciate all the efforts. I will rely on SO.
