### ISSUE TITLE
Blazor WebAssembly Debugging

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/runtime#40721]
Setting a tracepoint in Visual Studio and running a Blazor WebAssembly App every time a tracepoint is hit there is additional information written to the console:

```
ss_reqs 0 bp_reqs 1
mono_wasm_fire_bp
```

This pollutes the output and makes it hard to debug. 

Is this something the runtime controls or should the issue be raised via VS Feedback?

**Comment by captainsafia** [comment]
@lewing Transferring this to the runtime repo in case something has changed with log verbosity here.
