### ISSUE TITLE
Snap installer - ubuntu 20.04 - libc musl

### ISSUE THREAD

**Issue by sharkguto** [dotnet/runtime#40739]
Today after a snap refresh and update the dotnet-sdk snap package, i am not able to run it anymore.

ERROR:

/snap/dotnet-sdk/95/dotnet: error while loading shared libraries: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

Troubleshooting:

```bash
gustavo@brasil-terminator:~$ sudo apt-get install musl-dev -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
musl-dev is already the newest version (1.1.24-1).
The following package was automatically installed and is no longer required:
  ubuntu-system-service
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 198 not upgraded.
gustavo@brasil-terminator:~$ sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
gustavo@brasil-terminator:~$ dotnet --version
Segmentation fault (core dumped)
gustavo@brasil-terminator:~$ dotnet --version
Segmentation fault (core dumped)
gustavo@brasil-terminator:~$ dotnet --version
Segmentation fault (core dumped)
gustavo@brasil-terminator:~$ dotnet --version
Segmentation fault (core dumped)
gustavo@brasil-terminator:~$ dotnet --version
Segmentation fault (core dumped)
gustavo@brasil-terminator:~$ dotnet version
Segmentation fault (core dumped)
gustavo@brasil-terminator:~$ sudo unlink /lib/libc.musl-x86_64.so.1
gustavo@brasil-terminator:~$ dotnet version
/snap/dotnet-sdk/95/dotnet: error while loading shared libraries: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
gustavo@brasil-terminator:~$ 
```

I tried to install musl and create a symlink , without success.... someone can help me???

using last stable version
dotnet-sdk 3.1.401 from Microsoft .NET Core (dotnetcore✓) refreshed

**Comment by dagood** [comment]
This is weird, to my knowledge Ubuntu uses glibc, not musl, so I don't know why it would be looking for that in this case.

@leecow is it possible something weird happened like the snap ended up containing `linux-musl-x64` rather than `linux-x64`?
I haven't poked at this myself.

/cc @MichaelSimons @NikolaMilosavljevic

**Comment by dagood** [comment]
I wasn't able to get snapd working, but did find out how to download the dotnet-sdk snap raw via advice in https://forum.snapcraft.io/t/download-snap-package/14212/5, and yeah, the dir structure 7zip shows me is a little weird, but it's clear from `shared\Microsoft.NETCore.App\3.1.7\Microsoft.NETCore.App.deps.json` and some other places that it's `linux-musl-x64` rather than `linux-x64`.

It seems like the snap will have to be fixed up to contain `linux-x64` binaries and updated.

**Comment by sharkguto** [comment]
> I wasn't able to get snapd working (in docker), but did find out how to download the dotnet-sdk snap raw via advice in https://forum.snapcraft.io/t/download-snap-package/14212/5, and yeah, the dir structure 7zip shows me is a little weird, but it's clear from `shared\Microsoft.NETCore.App\3.1.7\Microsoft.NETCore.App.deps.json` and some other places that it's `linux-musl-x64` rather than `linux-x64`.
> 
> It seems like the snap will have to be fixed up to contain `linux-x64` binaries and updated.

Thanks for the troubleshooting dagood! My team got a big problem with this bug inside snap package. I hope someone can fix it soon. 

Grateful for your attention

**Comment by leecow** [comment]
@rbhanda to take a look at the build.

**Comment by leecow** [comment]
Rolled back the 3.1 offerings in the Snap store to 3.1.302 until this gets worked out.

**Comment by rbhanda** [comment]
We have published the snap packages again. This should be resolved now

**Comment by dagood** [comment]
@rbhanda I noticed that [3.1.6](https://github.com/dotnet/core/issues/4939) resolved known issue backlink, but doesn't 3.1.401 actually contain a [3.1.7](https://github.com/dotnet/core/issues/5057) runtime so it should be posted there instead?

**Comment by rbhanda** [comment]
It seems I updated wrong issue. I added the list of issues in our August post

**Comment by sharkguto** [comment]
![image](https://user-images.githubusercontent.com/3118165/90419592-2e4c8a00-e08d-11ea-882b-83380c5d74a7.png)
@rbhanda now its working fine. thanks

**Comment by NikolaMilosavljevic** [comment]
Closing the issue as it was resolved.
