### ISSUE TITLE
Mono: MethodInfo.Invoke on a method that takes a ref struct by ref throws ExecutionEngineException

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#40738]
See repro at https://github.com/dotnet/runtime/issues/38769. In coreclr, this sample succeeds even though it shouldn't (see https://github.com/dotnet/runtime/pull/40632). We're updating the logic to detect this condition and throw `NotSupportedException`.

The mono runtime correctly detects that there's an attempt to box a ref struct, and it fails with `ExecutionEngineException`. The unmanaged mono reflection stack should probably detect this by looking at the method sig _before_ the boxing attempt and provide a nicer `NotSupportedException` instead of an `ExecutionEngineException`.

**Comment by lambdageek** [comment]
Looks like a one-line fix near here

https://github.com/dotnet/runtime/blob/6ed3261974e493a54ec4a97ff281381960cf82fc/src/mono/mono/metadata/object.c#L7176

**Comment by MCCshreyas** [comment]
Hi, Can I take this issue to resolve? 
Seems like I need to change the exception type from `mono_error_set_execution_engine` to `mono_error_set_not_supported`!?
I will raise PR for this, once done!

**Comment by vargaz** [comment]
Should be fixed now.
