### ISSUE TITLE
Test failure: Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#40751]
failed in job: [runtime-coreclr jitstress 20200811.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=766498&view=ms.vss-test-web.build-test-results-tab&runId=23829828&resultId=109456&paneView=debug)

failed test:
Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh
Loader\\CollectibleAssemblies\\ByRefLocals\\ByRefLocals\\ByRefLocals.cmd

Error message
~~~
Return code:      1
Raw output file:      /root/helix/work/workitem/Loader/CollectibleAssemblies/Reports/Loader.CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ByRefLocals.dll ''
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh
Expected: True
Actual:   False


Stack trace
   at Loader_CollectibleAssemblies._ByRefLocals_ByRefLocals_ByRefLocals_._ByRefLocals_ByRefLocals_ByRefLocals_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/Loader.CollectibleAssemblies/Loader.CollectibleAssemblies.XUnitWrapper.cs:line 140
~~~

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Treating as 5.0 at least until we've root-caused this.

**Comment by davidwrighton** [comment]
Sigh, this (new) test scratches the very edge of what is legal to rely on, and while it has revealed a number of real issues, I've already had to revise it once for not quite being valid. Please let me know if I can help out.
