### ISSUE TITLE
Is it Possible to Fetch ARP Info in .NET Core?

### ISSUE THREAD

**Issue by JessieArr** [dotnet/runtime#40774]
Hello!

Is it possible to fetch ARP lookups or the cached results of previous lookups via .NET Core?

I'm interested in something like the output from `arp -a` at the Windows command line, or the Powershell `Get-NetNeighbor` commandlet (which seems to be unsupported in Powershell Core currently.)

It looks like most of the solutions in .NET Framework either rely on p/invoke, or starting arp as a child process and capturing its output. And so far my attempts to find a cross-platform solution using .NET Core have come up empty.

Is this possible? ARP is a widely-used protocol, so the ability to dump the OS' address table, or to explicitly perform an ARP lookup on a host seems like it could be implemented in a cross-platform manner, at least in theory.

Thank you for your time.

**Comment by wfurt** [comment]
no, there is no API to get ARP entries. I think executing `arp` utility is probably your best option. That should work on Linux and MacOS as well. There may be more efficient ways how to do it in particular OS but that wan't be portable. 
Since ARP table only sees directly connected nodes on the same L2 segment, the list generally should not be too long.

**Comment by am11** [comment]
You might be interested in NetStandard 2.0 package: [ArPLoopup](https://www.nuget.org/packages/ArpLookup/), it does not spawn a child process on Linux (but instead reads the arp file asynchronously under procfs). On Windows, it does P/Invoke. API shape is simple, see [usage](https://github.com/georg-jung/ArpLookup#usage).

**Comment by am11** [comment]
You might be interested in NetStandard 2.0 package: [ArpLookup](https://www.nuget.org/packages/ArpLookup/), it does not spawn a child process on Linux (but instead reads the arp file asynchronously under procfs). On Windows, it does P/Invoke. API shape is simple, see [usage](https://github.com/georg-jung/ArpLookup#usage).
