### ISSUE TITLE
CompareInfo.IsPrefix/IsSuffix can return wrong results given CompareOptions.IgnoreNonSpace

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#40803]
Calling `CompareInfo.IsPrefix` or `CompareInfo.IsSuffix` with `CompareOptions.IgnoreNonSpace` also seems to incorrectly imply `CompareOptions.IgnoreCase`.

Repro app, running under Windows 10.0.19041.450, using .NET 5.0's ICU mode:

```cs
class Program
{
    static void Main(string[] args)
    {
        RunTest("" /* invariant */);
        RunTest("en-US");
        RunTest("en");
        RunTest("fr-FR");
        RunTest("tr-TR");
        RunTest("zz-ZZ");
    }

    static void RunTest(string cultureName)
    {
        CultureInfo culture = CultureInfo.InvariantCulture;
        if (!string.IsNullOrEmpty(cultureName)) { culture = CultureInfo.GetCultureInfo(cultureName); }
        bool isPrefix = culture.CompareInfo.IsPrefix("x", "X", CompareOptions.IgnoreNonSpace);
        bool isSuffix = culture.CompareInfo.IsSuffix("x", "X", CompareOptions.IgnoreNonSpace);
        Console.WriteLine($"Culture {culture.Name} returned IsPrefix = {isPrefix}, IsSuffix = {isSuffix}.");
    }
}
```

Output:

```txt
Culture  returned IsPrefix = False, IsSuffix = False.
Culture en-US returned IsPrefix = False, IsSuffix = False.
Culture en returned IsPrefix = False, IsSuffix = False.
Culture fr-FR returned IsPrefix = True, IsSuffix = True.
Culture tr-TR returned IsPrefix = True, IsSuffix = True.
Culture zz-ZZ returned IsPrefix = True, IsSuffix = True.
```

Looks like the invariant culture, en, and en-US are special-cased so that they'll return the correct value. All other cultures (including the made-up zz-ZZ culture) fall down to the normal ICU logic, but it looks like we're somehow forwarding bad flags down to that layer.

**Comment by GrabYourPitchforks** [comment]
Also of interest: `CompareInfo.Compare` still seems to be returning the correct value in these cases. It's just `IsPrefix` and `IsSuffix` that are problematic as far as I can tell.

**Comment by tarekgh** [comment]
My guess here is could be the optimization we have in the native side. but I am not sure.

**Comment by adamsitnik** [comment]
> My guess here is could be the optimization we have in the native side. but I am not sure.

To verify this we can just change the following condition:

https://github.com/dotnet/runtime/blob/6362ec357baaac66ae461b6a73c49cec5ea37470/src/libraries/Native/Unix/System.Globalization.Native/pal_collation.c#L842

if it's just a matter of calling the more expensive version for `IgnoreNonSpace` we could include this in 5.0

**Comment by tarekgh** [comment]
@adamsitnik just checking if you plan to look at this one?

**Comment by adamsitnik** [comment]
>  just checking if you plan to look at this one?

@tarekgh  I don't plan to do that in the near future

**Comment by tarekgh** [comment]
I looked at this one and it is a duplicate to https://github.com/dotnet/runtime/issues/56155

It is an ICU issue when doing any string search operations (e.g. IndexOf, LastIndexOf, IsSuffix, and IsPrefix). This issue occurs only when having IgnoreNonSpace option which is translated to Primary Collation Strength with turning off case insensitivity and that is where ICU fail to do the right thing. We already have the ticket https://unicode-org.atlassian.net/browse/ICU-21338 to track getting the fix from ICU.

Note, from the description of this issue it mentioned the problem don't occur with `en` based cultures which is not fully true. We don't see the problem because we have optimization when using `en` cultures with ASCII strings. if using non-ASCII strings, the problem will show up with such cultures too.

```C#
        CompareInfo ci = CultureInfo.GetCultureInfo("en-US").CompareInfo;
        Console.WriteLine($"{ci.Name}: {ci.IsSuffix("\u200dx", "X", CompareOptions.IgnoreNonSpace)}"); // return TRUE as a wrong result
        Console.WriteLine($"{ci.Name}: {ci.IsPrefix("x\u200d", "X", CompareOptions.IgnoreNonSpace)}"); // return TRUE as a wrong result

        Console.WriteLine($"{ci.Name}: IndexOf = {ci.IndexOf("x\u200d", "X", CompareOptions.IgnoreNonSpace)}"); // return 0 as a wrong result
```
