### ISSUE TITLE
EventListener.DisableEvents doesn't work as expected with Guid.Empty eventSource

### ISSUE THREAD

**Issue by erich-wang** [dotnet/runtime#40815]
### Description
Per the description `If the Guid property for eventSource is Empty, events for all event sources in the application domain are disabled for this event listener.` from [doc](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener.disableevents?view=netcore-3.1)

I should not get OnEventWritten notification:
```csharp

    //1. eventListner to enable some event sources
    //2. method eventListener.OnEventWritten is called
   // 3. disable with eventSource whose Guid is Guid.Empty
    eventListener.DisableEvents(MySource.Instance)
    //after above statement, I expect eventListener.OnEventWritten is not called anymore, but actually the method is called.

    [EventSource(Guid = "00000000-0000-0000-0000-000000000000")]
    class MySource : EventSource
    {
        public static MySource Instance = new MySource();
    }

```

**Comment by KalleOlaviNiemitalo** [comment]
`[EventSource(Guid = "00000000-0000-0000-0000-000000000000")]` causes EventSource.Initialize to fail:

<https://github.com/dotnet/runtime/blob/53976d38b1bd6917b8fa4d1dd4f009728ece3adb/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1419-L1422>

I think this is a documentation error.

**Comment by erich-wang** [comment]
@KalleOlaviNiemitalo, did you really get the Initialize failure or just infer from source code? I did not get the failure you mentioned with .Net Core 3.1 on Windows.

**Comment by KalleOlaviNiemitalo** [comment]
@erich-wang, I just read the source code. Do you mean [EventSource.ConstructionException](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventsource.constructionexception?view=netcore-3.1) was not set in your test?

**Comment by KalleOlaviNiemitalo** [comment]
I now tested that .NET Core 3.1 on Windows sets MySource.Instance.ConstructionException.

```
System.ArgumentException: The Guid of an EventSource must be non zero.
   at System.Diagnostics.Tracing.EventSource.Initialize(Guid eventSourceGuid, String eventSourceName, String[] traits)
```

**Comment by tommcdon** [comment]
FYI @sywhang
