### ISSUE TITLE
Add EventCounter for ArrayPoolEventSource

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#40830]
I've been doing some performance investigation recently around how ASP.NET Core uses the ArrayPool and it would be great to have some counters for the existing events:
- BuffersAllocated
- BuffersRented
- BuffersReturned

cc @noahfalk @adamsitnik

**Comment by adamsitnik** [comment]
@davidfowl have you tried using `ArrayPool` [EventSource](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Buffers/ArrayPoolEventSource.cs) ?

It's [not enabled](https://github.com/microsoft/perfview/issues/932) in PerfView by default so when using PerfView you have to put its name like this before starting the collection:

![obraz](https://user-images.githubusercontent.com/6011991/90230253-9004be00-de19-11ea-84e1-a2cbc89ed979.png)

**Comment by davidfowl** [comment]
@adamsitnik 😊 Yes I know how to add custom providers in perfview and using dotnet trace. I'm specifically asking for event counters though.

**Comment by jkotas** [comment]
This would be pretty expensive non-pay-for-play counter. We do not have counter that tracks number of regular objects allocated either.

**Comment by davidfowl** [comment]
> This would be pretty expensive non-pay-for-play counter. We do not have counter that tracks number of regular objects allocated either.

Wait why would it be expensive? Counting using interlocked in this code path is too expensive?

**Comment by jkotas** [comment]
> Counting using interlocked in this code path is too expensive?

Yes!

**Comment by davidfowl** [comment]
@jkotas Can we do a performance test to make sure? I believe you, but we should measure the overhead before we do something more complex.

**Comment by noahfalk** [comment]
I assumed @davidfowl was seeking a counter that would only track the count when someone enabled this provider. The only cost we'd pay by default would be the log.IsEnabled() check returning false and skipping the remainder of the logic, which is already a cost we incur now.

**Comment by jkotas** [comment]
> Can we do a performance test to make sure? 

Here you go:

```
using System;
using System.Diagnostics;
using System.Buffers;
using System.Threading;

class Program
{
    static int rents;
    static int returns;

    static void Work()
    {
        for (int i = 0; i < 100000000; i++)
        {
            Interlocked.Increment(ref rents);
            var a = ArrayPool<byte>.Shared.Rent(100);
            for (int j = 0; j < 100; j++) a[j] = (byte)j;
            Interlocked.Increment(ref returns);
            ArrayPool<byte>.Shared.Return(a);
        }
    }

    static void Main(string[] args)
    {
        for (int i = 0; i < Environment.ProcessorCount - 1; i++)
            new Thread(Work).Start();
        Stopwatch sw = new Stopwatch();
        sw.Start();
        Work();
        sw.Stop();
        Console.WriteLine(sw.ElapsedMilliseconds);
    }
}
```

On my Surfacebook:

Without Interlock.Increments: 13348ms
With Interlocked.Increments: 33192ms

The difference will be even more on higher end server machine.

**Comment by ericstj** [comment]
Setting this as 6.0.0 since I'm not seeing this meet the bar at the moment.

**Comment by tannergooding** [comment]
Moved this to future. @davidfowl it sounds like this need additional thought/work before we can move forward with it.
