### ISSUE TITLE
[System.Text.Json] unable to use Utf8JsonWriter with VB.net

### ISSUE THREAD

**Issue by lucamauri** [dotnet/runtime#40831]
### Description
I am trying to replicate the functionality of [this example](https://gist.github.com/terrajobst/336da6ae0a327bef113c1325710164f0#file-sample9-cs) as explained in the blog post https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/ using **VB.net** _instead_ of C♯.

The original code work well, so I migrated it to:
```vb.net
Dim Options = New JsonWriterOptions

With options
    .Indented = True
End With

Dim MemStream As New MemoryStream
Dim Writer As New Utf8JsonWriter(MemStream, Options)

Writer.WriteStartObject()
Writer.WriteString("date", DateTimeOffset.UtcNow)
Writer.WriteNumber("temp", 42)
Writer.WriteEndObject()

Console.WriteLine(MemStream.Length)

MemStream.Close()

Dim JSON As String = Encoding.UTF8.GetString(MemStream.ToArray())

Console.WriteLine(Json)
```
I am unable to make it work: `MemStream.Length` always return 0. I also tried to add `MemStream.Close()` because I thought the problem might have been on `.ToArray()` method, but to no avail.

### Configuration
I am running this example on VisualStudio 16.7.1 on .NET Framework 4.7.2 using the System.Text.Json from the NuGet manager.
My OS is Windows 10 [Version 10.0.19041.450]

### Regression?
It works on the same machine on a C♯ project using the original code from example.

### Other information
No errors, just an empty stream

**Comment by devsko** [comment]
I think you have to call `Writer.Flush()` or `Writer.Dispose()`. Thats what C#'s `using` is for.

**Comment by lucamauri** [comment]
Indeed it is necessary to use `.Flush()` as written by @devsko and explained here https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.flush
I apparently had a very bad understanding of `using`, thanks for pointing that out.

I am closing this as it is not a bug.
