### ISSUE TITLE
Blazor WebAssembly unrecoverable when session cookie has large number of claims

### ISSUE THREAD

**Issue by moogle001** [dotnet/runtime#40835]
I lost several hours today tracking down a bug in a Blazor WASM project that was not only causing an HTTP Get request to fail with the very unhelpful exception "children could not be evaluated", it then caused the entire Blazor front-end to fail to load even with a CTRL-R refresh in Chrome. Restarting the Blazor project likewise had no impact, the only way to retry the app was by clearing browser cache.

Steps to recreate:

1. Enable cookie authentication in server-side project.
2. Have client call server endpoint which creates session cookie and adds a large number of claims. 
NOTE: There's some vagueness in how large; if it is too large the "login" request will fail and Blazor will not be stuck in an invalid state. 5000 claims seems to trigger this failure, but a session with around 1000 claims seems to "work".
3. The login will have succeeded and everything will seem okay. However, the next time the front-end attempts to use HttpClient against the server, an exception with message "children could not be evaluated" will be thrown. After that Blazor front end is unrecoverable without clearing cookies.

I have uploaded a minimal project that recreates this issue here: https://github.com/moogle001/BrokenBlazor/tree/master/BrokenBlazor

When running this project, going to the Index page creates the session cookie. Then going to FetchData page causes the breakage.

**Comment by moogle001** [comment]
@javiercn Yeah, adding that much data to the cookie was definitely unintentional. It just took me a while to figure out what was going on due to Blazor's reaction. Unfortunately I cannot implement OpenID Connect for this website at this time.

Are you sure this has no impacts within Blazor itself? I found it incredibly bizarre/frustrating that the Blazor WASM wouldn't load pages regardless of HttpClient usage after this was encountered.

**Comment by pavelsavara** [comment]
I'm not clear what is the ask here. Where is the message coming from ? Is that somehow related to runtime ?
