### ISSUE TITLE
Throw exceptions for generic arity mismatches at container build time

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#40848]
```C#
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection();
services.AddSingleton(typeof(IFoo<>), typeof(Foo<,>));
var sp = services.BuildServiceProvider();

sp.GetRequiredService<IFoo<object>>();


public interface IFoo<T>
{

}

public class Foo<T1, T2>
{

}
```

Today these are only caught at resolve time (the call to GetRequiredService), doing this earlier would be better. Context https://github.com/dotnet/runtime/pull/39540/files#r470778826

**Comment by lateapexearlyspeed** [comment]
Hi @davidfowl Not sure can I learn and try it ?

**Comment by lateapexearlyspeed** [comment]
Hi @davidfowl and guys, the PR #51167 is ready for review now, please review, thanks !

**Comment by davidfowl** [comment]
Excellent change @lateapexearlyspeed! If you're looking for more stuff I recently marked https://github.com/dotnet/runtime/issues/43083 if you want to take a look

**Comment by lateapexearlyspeed** [comment]
Hi @davidfowl , I just returned from a journey and found your #43083 is already in progress now. No problem I will keep searching other interesting ones, thanks very much !
