### ISSUE TITLE
[WSL1] Socket created on top of socketpair fd reported as not connected

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#40901]
Creating this issue to document the root cause of #40727. 

Wrapping a socketpair fd with a System.Net.Socket results in its `Connected` property being reported as false. The root cause seems to be this [`getsockopt` syscall](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Native/Unix/System.Native/pal_networking.c#L2522) which fails with an `EINVAL` errno.

cc @stephentoub

**Comment by karelz** [comment]
Triage:
- WSL1 is not that wide-spread and is superseded by WSL2. 
- The workaround above is working for 5.0+, so we do not have burning problem to solve.
- It is new API, so chance of regressions is small (we were unlucky in this case).

We may wan to report it to WSL team.

Closing as Won't Fix, unless it becomes more common scenario users on WSL1 run into.
