### ISSUE TITLE
System.Drawing.Tests.FontFamilyTests.Families_Get_ReturnsExpected failure on libgdiplus platforms

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#40937]
Mono and CoreCLR both fail near-identically on this test on Helix.

CoreCLR https://helix.dot.net/api/2019-06-17/jobs/4f122c80-6e43-48c3-9793-d5c72dc59bbd/workitems/System.Drawing.Common.Tests/console
```
    System.Drawing.Tests.FontFamilyTests.Families_Get_ReturnsExpected [FAIL]
      Assert.Equal() Failure
                â†“ (pos 0)
      Expected: Noto Sans Inscriptional Parthia
      Actual:   Verdana
                â†‘ (pos 0)
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontFamilyTests.cs(126,0): at System.Drawing.Tests.FontFamilyTests.Families_Get_ReturnsExpected()
```

Mono https://helix.dot.net/api/2019-06-17/jobs/6648e68b-974b-4787-9345-e0223c696d09/workitems/System.Drawing.Common.Tests/console
```
    System.Drawing.Tests.FontFamilyTests.Families_Get_ReturnsExpected [FAIL]
      Assert.Equal() Failure
                â†“ (pos 0)
      Expected: Noto Sans Inscriptional Parthia
      Actual:   Verdana
                â†‘ (pos 0)
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontFamilyTests.cs(126,0): at System.Drawing.Tests.FontFamilyTests.Families_Get_ReturnsExpected()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(384,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

We get the same failure on macOS 10.15, and the text implies an issue with the base VM configuration (missing fonts? Too many fonts? Fonts returned in the wrong order?)

**Comment by directhex** [comment]
I think this is actually a real issue

The test is enumerating every font on the system, creating a new font object from each entry's name, and verifying that they match (i.e. checking "i got a font with name X, and can create a font with the same name"). It appears to be failing on fonts with long names, defaulting to Verdana:

```
family Droid Sans Mono Slashed for Pow
copy   Verdana
family Droid Sans Mono Dotted for Powe
copy   Verdana
family Roboto Mono Medium for Powerlin
copy   Verdana
family Ubuntu Mono derivative Powerlin
copy   Verdana
family Noto Sans Inscriptional Parthia
copy   Verdana
```

I need to see if this is _behaviour_ changed in 10.15, or there were no long-named fonts, or what

**Comment by directhex** [comment]
Yeah, real bug.

[Catalina font list](https://support.apple.com/en-us/HT210192)

[High Sierra font list](https://support.apple.com/en-us/HT207962)

The bug wasn't previously discovered, because HS does not ship with any fonts whose name exceeds LF_FACESIZE from wingdi.h (32 chars)

Related, with possible thoughts on workarounds we'll need to implement in libgdiplus: https://github.com/microsoft/terminal/issues/602

**Comment by directhex** [comment]
Confirmed this issue happens on Linux with big font names.

It does NOT happen on Windows, which truncates the font name differently and successfully does `new FontFamily(fontFamily.Name)` with the truncated name.

**Comment by safern** [comment]
@directhex should we pone an issue in libgdiplus?

**Comment by directhex** [comment]
Yeah, probably. I'm out of time today, can do it tomorrow.

Easier repro if you don't have a Mac is to install the `fonts-noto-core` package on Ubuntu, which contains the problem NotoSansInscriptionalParthian-Regular.ttf.

**Comment by directhex** [comment]
`new FontFamily("Noto Sans Inscriptional Parthian")` works, so _creating_ a FontFamily with a >32 byte name is fine, what isn't fine is using the truncated name at all.
