### ISSUE TITLE
API Proposal: Make char.IsAscii public

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#40936]
System.Char currently defines a [private `IsAscii` method](https://github.com/dotnet/runtime/blob/d8ca3562358b036afc14c6f1abc517154c98b095/src/libraries/System.Private.CoreLib/src/System/Char.cs#L82). It think it might make sense to make this public?

```diff
public readonly struct Char
{
+  public static bool IsAscii(char ch);
}
```

**Comment by eiriktsarpalis** [comment]
Not sure what the right area label for corelib stuff is.

**Comment by danmosemsft** [comment]
Note there is already `Rune.IsAscii(char)` but it seems to me this is probably a case where duplication is reasonable, as the duplication is at a trivial level, and `Rune` is much less widely used than `char`; one might operate entirely on `char` and only need this one method on `Rune`.

**Comment by danmosemsft** [comment]
@GrabYourPitchforks

**Comment by terrajobst** [comment]
Unless @GrabYourPitchforks has any objections, this feels like a sensible addition.

**Comment by GrabYourPitchforks** [comment]
We're also adding `Ascii.IsAscii(char)` (see https://github.com/dotnet/runtime/issues/28230).

But I agree, targeted duplication like what's suggested here could help discoverability.

**Comment by terrajobst** [comment]
* Looks reasonable

```C#
namespace System
{
    public readonly struct Char
    {
        public static bool IsAscii(char ch);
    }
}
```

**Comment by GrabYourPitchforks** [comment]
Correction: the parameter should be named _c_, not _ch_. That matches other static APIs on the `char` class.

**Comment by danmosemsft** [comment]
Anyone in the community interested in picking this up?

**Comment by gfoidl** [comment]
You can assign it to me -- will send a PR tomorrow.

Is https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime/tests/System/CharTests.cs the right place to add some tests for this?

> That matches other static APIs on the `char` class.

There is a bit of mix on `c` / `ch`. Shall this be unified to `c` (within the coming PR)?

**Comment by GrabYourPitchforks** [comment]
@gfoidl it's yours! :)

> There is a bit of mix on `c` / `ch`. Shall this be unified to `c` (within the coming PR)?

Looks like we use _c_ for our public APIs and _ch_ (sometimes) for our internal APIs? I can't find any counterexamples offhand but admittedly I didn't look that hard. I wouldn't bother normalizing any other internal methods during this PR.

**Comment by svick** [comment]
@GrabYourPitchforks 

For the record, in .Net Core 3.1 corelib, I count 29 methods with `char c` parameter and 9 methods with `char ch`:

* System.Text.Rune: System.Text.Rune op_Explicit(Char)
* System.Text.Rune: Boolean TryCreate(Char, System.Text.Rune ByRef)
* System.Text.Rune: Void .ctor(Char)
* System.IO.BinaryWriter: Void Write(Char)
* System.Globalization.CharUnicodeInfo: Double GetNumericValue(Char)
* System.Globalization.CharUnicodeInfo: Int32 GetDecimalDigitValue(Char)
* System.Globalization.CharUnicodeInfo: Int32 GetDigitValue(Char)
* System.Globalization.CharUnicodeInfo: System.Globalization.UnicodeCategory GetUnicodeCategory(Char)
* System.Globalization.CompareInfo: Boolean IsSortable(Char)

**Comment by GrabYourPitchforks** [comment]
@svick right, I'm only considering existing static public methods on the `char` type. That way the parameter names are at least locally consistent.

**Comment by gfoidl** [comment]
Are there any steps needed for the documentation?

**Comment by danmosemsft** [comment]
@gfoidl it's complicated -- normally the simple answer is "add XML docs in the src for this new public method" and that may be the correct answer. It's complicated because unlike almost everyone else, the core libraries don't historically generate their docs from the sources. We do want to use XML docs going forward, but only for seeding the docs.microsoft.com text initially. We have a tool that does this seeding so I think the answer is we'll need another PR to add `<summary>` for IsAscii. We missed this in PR review.

Now I've typed that, I see it's documented by @carlossanlop here https://github.com/dotnet/runtime/blob/c87e75e8ef260ccc6e979f9df1cc012536ee036f/docs/coding-guidelines/adding-api-guidelines.md#documentation

**Comment by gfoidl** [comment]
@danmosemsft it was easy to miss, as no other api in https://github.com/dotnet/runtime/blob/756addda8cf593faf696602d8a9dfef759423849/src/libraries/System.Private.CoreLib/src/System/Char.cs#L25 has xml doc comments.

So I'll send a PR with the doc comments (for this new public API)?

**Comment by danmosemsft** [comment]
@gfoidl certainly that is true, and it is because until recent years, there was no path from our source code to docs at all, and I guess we have not added much to Char recently. Yes, all that is needed is one for the new member. thanks
