### ISSUE TITLE
Mono runtime tests build occasionally times out

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#40933]
When the runtime tests are being built (Mono Common Pri0 Test Build AnyOS AnyCPU release), sometimes we hit the 1h30m timeout. I noticed this here: https://github.com/dotnet/runtime/pull/40669/checks?check_run_id=973507764 Supposed it has shown up elsewhere, but I'm not sure how to check and so I have no idea as to the frequency. cc: @jaredpar

**Comment by directhex** [comment]
Is this still a concern?

**Comment by CoffeeFlux** [comment]
I wouldn't know :p
