### ISSUE TITLE
Memory leak in System.DirectoryServices.Protocols

### ISSUE THREAD

**Issue by uiopak** [dotnet/runtime#40946]
### Description
Calling LdapConnection.SendRequest method create memory leak.
Making request that returns 14500 entries in loop 100 times allocates 1.5 GB in native heap that later isn't deallocated in 5.0.0-preview.4.20251.6 version and earlier it is 7MB. When creating 100 000 users it is 96MB and 7MB.

<details>
<summary>my code</summary>
<p>

```c#
private static string dn = "CN=Users,DC=test,DC=local";
static void Main(string[] args)
{
    string userName = "Administrator@test.local";
    string password = "Password1!";
    string ip = "192.168.1.182";
    int port = 389;
    LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier(ip, port);
    LdapConnection connection = new LdapConnection(ldi);

    NetworkCredential credential = new NetworkCredential(userName, password);

    connection.Credential = credential;
    connection.AuthType = AuthType.Basic;

    LdapSessionOptions options = connection.SessionOptions;
    options.ProtocolVersion = 3;
    try
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            options.VerifyServerCertificate
            += (conn, cert) => { return true; };
        }
        options.StartTransportLayerSecurity(null);
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        return;
    }

    try
    {
        connection.Bind();
    }
    catch (LdapException e)
    {
        Console.WriteLine(e);
        return;
    }

    for (int i = 0; i < 100; i++)
    {
        try
        {
            string distinguishedName = $"CN=Name{i},{dn}";
            AddRequest addRequest = new AddRequest(distinguishedName, "user");
            switch (0)
            {
                case 0:
                    returnMaxID(connection);
                    break;
                case 1:
                    addRequest.Attributes.Add(new DirectoryAttribute("uidNumber", (returnMaxID(connection) + 1).ToString()));
                    goto case 2;
                case 2:
                    {
                        addRequest.Attributes.Add(new DirectoryAttribute("unicodePwd", Encoding.Unicode.GetBytes("\"Password1!\"")));
                        var response = connection.SendRequest(addRequest);
                    }
                    break;
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
    }

    try
    {
        options.StopTransportLayerSecurity();
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }

    connection.Dispose();
}
private static int returnMaxID(LdapConnection connection)
{
    var request = new SearchRequest(dn, $"(&(objectClass=user)(uidNumber=*))",
        SearchScope.Subtree, new[] { "uidNumber" });
    var pageResultRequestControl = new PageResultRequestControl(10000);
    request.Controls.Add(pageResultRequestControl);
    try
    {
        List<SearchResultEntry> searchResultEntries = new List<SearchResultEntry>();
        while (true)
        {
            var response = connection.SendRequest(request) as SearchResponse;
            if (response.Entries.Count > 0)
            {
                SearchResultEntry[] sre = new SearchResultEntry[response.Entries.Count];
                response.Entries.CopyTo(sre, 0);
                searchResultEntries.AddRange(sre);
            }
            pageResultRequestControl.Cookie = (response.Controls[0] as PageResultResponseControl).Cookie;
            if (pageResultRequestControl.Cookie.Length == 0)
            {
                break;
            }
        }

        int max = 9999;
        if (searchResultEntries.Count > 0)
        {
            max = searchResultEntries.Max(e => int.Parse(e.Attributes["uidNumber"][0].ToString()));
        }
        return max;
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
    return 9999;
}
```

</p>
</details>

### Configuration
Windows 10 Pro 2004 x64
.Net Core 3.1.6 and 5.0.0-preview.7.20364.11
Linux Manjaro
.Net Core 3.1.3
Debian 10(Docker 3.1-buster-slim)
.Net Core 3.1.7

### Regression?
Problem started with 5.0.0-preview.5.20278.1 version of library.

**Comment by joperezr** [comment]
>Regression?
Problem started with 5.0.0-preview.5.20278.1 version of library.

Do you mind double checking if older versions of the package don't have this problem? I ask because we did recently change this package  a lot, but it was mostly around the Linux implementation of it, not the Windows ( Windows side was practically untouched) so I doubt this is a regression.

**Comment by uiopak** [comment]
I checked it again.
In my code in each iteration SendRequest is called 15 times and receives together 14 499 entries.

Loop 100 times:
| Library version          | Windows | WSL 2    | Docker   | Manjaro  |
| ------------------------ | ------- | -------- | -------- | -------- |
| 5.0.0-preview.7.20364.11 | 1.594GB | 448MB    | 463MB    | 410MB    |
| 5.0.0-preview.6.20305.6  | 1.608GB | 447MB    | 464MB    | 403MB    |
| 5.0.0-preview.5.20278.1  | 1.610GB | 448MB    | 462MB    | 406MB    |
| 5.0.0-preview.4.20251.6  | 53.2MB  | -------- | -------- | -------- |
| 5.0.0-preview.3.20214.6  | 39.1MB  | -------- | -------- | -------- |
| 5.0.0-preview.2.20160.6  | 53.3MB  | -------- | -------- | -------- |
| 5.0.0-preview.1.20120.5  | 56.3MB  | -------- | -------- | -------- |
| 4.7.0                    | 56.1MB  | -------- | -------- | -------- |

Loop 1000 times:

| Library version          | Windows | WSL 2     | Docker    | Manjaro |
| ------------------------ | ------- | --------- | --------- | ------- |
| 5.0.0-preview.7.20364.11 | 15.60GB | 3.830GB   | 3.772GB   | 3.7GB   |
| 5.0.0-preview.6.20305.6  | 15.61GB | 3.832GB   | 3.762GB   | 3.7GB   |
| 5.0.0-preview.5.20278.1  | 15.60GB | 3.828GB   | 3.770GB   | 3.7GB   |
| 5.0.0-preview.4.20251.6  | 51.9MB  | --------- | --------- | ------  |

Windows:
Windows 10 Pro 2004 19041.450
.NetCore 3.1.6
RAM from: Task Manager

WSL 2:
Ubuntu 20.04
.NetCore 3.1.7
RAM from: htop

Docker:
Debian 10
.NetCore 3.1.7
RAM from: docker stats

Manjaro:
Manjaro 20.1
.NetCore 3.1.6
RAM from: gnome-system-monitor

Tests run in debug configuration, but release gives same results.

Loop 100 times Windows:
5.0.0-preview.7.20364.11, 5.0.0-preview.6.20305.6, 5.0.0-preview.5.20278.1 all give similar results:
![image](https://user-images.githubusercontent.com/44174807/90551368-7f45a680-e191-11ea-90e7-c67ef8ab2cd2.png)

5.0.0-preview.4.20251.6, 5.0.0-preview.3.20214.6, 5.0.0-preview.2.20160.6, 5.0.0-preview.1.20120.5, 4.7.0 all give similar results:
![image](https://user-images.githubusercontent.com/44174807/90551231-502f3500-e191-11ea-8120-9978b132de83.png)

Loop 1000 times Windows:
5.0.0-preview.7.20364.11, 5.0.0-preview.6.20305.6, 5.0.0-preview.5.20278.1 all give similar results:
![image](https://user-images.githubusercontent.com/44174807/90551483-af8d4500-e191-11ea-8af5-1e4348619421.png)


5.0.0-preview.4.20251.6 result:
![image](https://user-images.githubusercontent.com/44174807/90551500-b61bbc80-e191-11ea-9dee-ed65608e2ff9.png)

**Comment by joperezr** [comment]
Thanks a lot for your investigation! This will be very helpful and I will do some profiling to figure out what the problem is here.

**Comment by joperezr** [comment]
Re-opening to track the port back to rc
