### ISSUE TITLE
Irregular times for UdpClient.ReceiveAsync with dotnet core running on Linux

### ISSUE THREAD

**Issue by simcoster** [dotnet/runtime#40970]
I’m writing a UDP client that should read packets as fast as possible.

The client is compiled for .net core 3.1 and is running on Linux. I only have 1 connection that gets many packets per second. I’m measuring the time it takes for the method ReceiveAsync to run, using a StopWatch. The variability of the running time is very large:
Of 1000 measurements min is 0 ticks, max is 518, and average is 8

So how can I
a. reduce the time it takes for a single call to run? (I’ve tried the synchronous Receive method, BeginReceive and ReceiveAsync after reading recommendations here)

b. have the running time be more consistent? I doesn’t seem to correlate with the no. of bytes I receive

Example code:

```c#
var myClient = new UdpClient();
myClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, config.LocalAdapterIndex);
myClient.Client.Blocking = false;
myClient.JoinMulticastGroup(address, IPAddress.Parse(config.LocalAdpaterAddress));
_EndPoint = new IPEndPoint(address, port);
myClient.Client.Bind(_EndPoint);
myClient.Client.ReceiveBufferSize = 64 * 1024;
Stopwatch stopwatch = new Stopwatch();
while(true)
{
    stopwatch.Restart();
    UdpReceiveResult result = await _ReceiveClient.ReceiveAsync();
    if (i >= latenciesCount)
    {
        Console.WriteLine($"Latencies are {latencies.Average():n} max {latencies.Max():n} min {latencies.Min():n}");
        i = 0;
    }
    else
    {
        latencies[i] = stopwatch.ElapsedTicks * 100;
        i++;
    }
}
```
@dotnet/ncl

**Comment by simcoster** [comment]
If this should be posted elsewhere please let me know

**Comment by wfurt** [comment]
You would need to figure out where the time is spent @simcoster. With synchronous blocking API, you only depend on kernel e.g. if data is not available kernel will block the call and wake up when ready. With non-blocking or Async you are adding overhead of scheduling. If there is nothing to read, we will need to schedule notification and wake up when notified by kernel.

BTW `strace` has option to measure time spent in system call. You can give it try and get some insight from it.

**Comment by karelz** [comment]
Also note that `Stopwatch` is very rough way to measure -- we recommend to use BenchmarkDotNet which deals with lots of statistics for you. c @adamsitnik

**Comment by adamsitnik** [comment]
> The variability of the running time is very large:
Of 1000 measurements min is 0 ticks, max is 518, and average is 8

> have the running time be more consistent? 

You are most probably hitting an issue with `Stopwatch` resolution: https://aakinshin.net/posts/stopwatch/#pitfalls

As @karelz has mentioned, you could use [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) to benchmark it. It's a library that does all of the heavy lifting for you when it comes to dealing with issues like `Stopwatch` resolution & more.

> reduce the time it takes for a single call to run?

As @wfurt has mentioned:

> You would need to figure out where the time is spent

You can do that by using [perfcollect](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md#perfcollect), [VTune](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md#linux) or [dotnet trace](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md). Once the profiler tells you where most of the time is spent, you can modify your code and remove the bottlenecks (if ther are any).

@simcoster I believe that your question has been answered so I am closing the issue.
If you have more questions please feel free to reopen the issue.
