### ISSUE TITLE
IPEndPoint.Create can return IPEndPoint

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#40977]
## Background and Motivation

With covariant return type it is possible to return a more specific type in the overridden method:

https://docs.microsoft.com/en-us/dotnet/api/system.net.endpoint.create?view=netcore-3.1

EndPoint.Create
```cs
public virtual System.Net.EndPoint Create (System.Net.SocketAddress socketAddress);
```

Since IPEndPoint derives from EndPoint, IPEndPoint.Create can be
```cs
public override System.Net.IPEndPoint Create(System.Net.SocketAddress socketAddress);
```

Same for UnixDomainSocketEndPoint, DnsEndPoint.

**Comment by scalablecory** [comment]
Makes sense to me; @bartonjs this isn't a breaking change, right? The more derived types don't hide any of the member functions.

**Comment by bartonjs** [comment]
It... probably... isn't?  But I don't think we've had one come up in API review yet.

"The adjusted override return type doesn't hide any members from the previous return type" is probably all that's really required.  Fixed-type destination targets won't care, and `var` should only care if `new` method appears in its way.

**Comment by svick** [comment]
@bartonjs As far as I can tell, it kind of behaves like a `new` method. Consider this code:

```c#
var endpoint = IPEndPoint.Create(address);

void WriteType<T>(T x) => Console.WriteLine(typeof(T));
WriteType(endpoint);

EndPoint anotherEndpoint = …;
endpoint = anotherEndpoint;
```

Based on my testing, if `IPEndPoint.Create` was updated to return `IPEndPoint`, then after recompilation with that new target framework, `WriteType` would produce different output, and the last line would no longer compile.

**Comment by stephentoub** [comment]
Or:
```C#
var endpoint = ipEndPoint.Create(address);
Func(ref endpoint);
...
void Func(ref EndPoint ep) { ... }
```

**Comment by NN---** [comment]
Perhaps there can be a new method introduced which returns specific type in derived classes ?

**Comment by bartonjs** [comment]
Ah, yes, generic inference and refs.

This is why I'm a fan of "don't use var except with new/hard-cast/as-cast".  So we'll have to decide if this is a case where we're OK breaking "var" users or not for our general breaking change guidelines.  (Not even just changing it on existing overrides, but can we use covariant returns on any overrides of existing types)

**Comment by scalablecory** [comment]
I think if we were designing these classes today, we would probably do this. But, I don't think this provides enough benefit to be worth a breaking change however small.

**Comment by scalablecory** [comment]
I'm going to close this issue now, as I don't think we will want to take this even as a new method. Thanks for the request.
