### ISSUE TITLE
OID copying in S.S.C.Pkcs may not be sufficient

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#40984]
Since `Oid` is "init-once" in .NET 5, The S.S.C.Pkcs library was changed (by me) to remove defensive `Oid` copies in #38387. Since this package targets other frameworks, it has a helper function intended to continue to copy where applicable.

https://github.com/dotnet/runtime/blob/38aa0b76a6423b902cc4b6c310cad9c49ba675b6/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/PkcsHelpers.cs#L696-L704

However, it looks like the Pkcs project has a target specifically for netcoreapp3.0:

https://github.com/dotnet/runtime/blob/38aa0b76a6423b902cc4b6c310cad9c49ba675b6/src/libraries/System.Security.Cryptography.Pkcs/src/System.Security.Cryptography.Pkcs.csproj#L8

That would mean that 5.0 versions of this package do not create the Oid copies when targeting netcoreapp3.0, but the init-once behavior of Oid is only in net5.0.

I think then the conditional needs to be:

```c#
#if NETCOREAPP && !NETCOREAPP3_0
             return oid; 
 #else 
             return oid is null ? null : new Oid(oid); 
 #endif
```

**Comment by vcsjones** [comment]
I'm happy to PR a fix, I want to make sure though that my understanding and assessment is correct.

**Comment by bartonjs** [comment]
Hm.  Maybe we should just do a capability probe and try to avoid the \#ifs.

```C#
private static readonly bool s_hasInitOnlyOid = DetectInitOnlyOid();

private static bool DetectInitOnlyOid()
{
    Oid oid = new Oid("0.0", null);

    try
    {
        oid.Value = "0.1";
        return false;
    }
    catch (WhateverException)
    {
    }

    return true;
}

public static Oid? CopyOid(this Oid? oid) 
{
    if (s_hasInitOnlyOid)
    {
        return oid;
    }

    return oid is null ? null : new Oid(oid); 
}
```

Since it's an if based on a static readonly that should even JIT down to the way we had it as precompiled.
