### ISSUE TITLE
Custom ICMP type and code

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#40994]
## Background and Motivation

Since Ping class is already implemented using raw sockets in Unix and Osx when running as root, it makes it easy to support any arbitrary type and codes.
Adding Windows support is easy given the implementation mentioned above.

## Usage Examples

`new Ping(new PingOptions { Code = 123, Type = 234 })`

Motivation is to be able to make any custom ICMP request.
The code already allows this just doesn’t expose the option to put any code or type.

**Comment by karelz** [comment]
Triage:
@NN--- why do you need to send ICMP request? We wonder how common is such scenario.
Would using raw sockets directly instead be a sufficient workaround?

**Comment by NN---** [comment]
It is a workaround.
The issue is that different OSes require very different implementation.
You can see it in Ping implementations.

I can take Ping code and make my own classes with the same implementation beside having additional option.
It just seems more convenient to allow such option in the PingOptions.

**Comment by karelz** [comment]
@NN--- in what kind of applications do you need the code and type to be customized? What do you want to achieve with this flexiblity?

**Comment by wfurt** [comment]
it would need to pass API review first.  Since the general usability is low IMHO that may be difficult. Especially if the there is alternative already. 

https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

**Comment by karelz** [comment]
Agreed, given the super limited corner case use case, I am closing this issue as Won't Fix.
It is not worth adding it at the moment.
If there are more customers and more scenarios that need it, we can reconsider in the future.

Thanks for bringing it up @NN--- !
