### ISSUE TITLE
Question: What is the preferred way to register custom logging provider?

### ISSUE THREAD

**Issue by mhsimkin** [dotnet/runtime#41005]
What is the preferred way of registering a custom provider?

When I review the code for the [LoggingBuilderExtensions.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Logging/src/LoggingBuilderExtensions.cs) in the Logging Source code, I see that calling AddProvider with a type of ILoggingBuilder will add the passed logging provider as a singleton to the DI container.

Then when an instance of [LoggerFactory ](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs)is created by the DI, the LoggerFactory constructor is passed a collection of all the registered ILoggerProviders.  The constructor will register all the supplied providers with a call to AddProviderRegistration with dispose as **false**.

As a result, when the application terminates the various ILoggerProvider instances are not disposed.  Is that to be expected?

I've followed the same approach to register my custom provider.  However, my provider needs to have dispose explicitly called in order to clean up some foreground threads managed by a 3rd party library.

What is the preferred approach that I should follow to register my custom provider so that LoggerFactory will call my provider's  dispose method?

Thanks

**Comment by maryamariyan** [comment]
> As a result, when the application terminates the various ILoggerProvider instances are not disposed. Is that to be expected?

I found this tests while doing a quick skim of LoggerFactoryTests:
https://github.com/dotnet/runtime/blob/cd2eed76e149b324197c062dce6d7cff49b2f837/src/libraries/Microsoft.Extensions.Logging/tests/Common/LoggerFactoryTest.cs#L49-L67

I guess that means if you want to make sure all things get disposed all you need to make sure is to dispose of the LoggerFactory.

**Comment by KalleOlaviNiemitalo** [comment]
> ```C#
>              .AddYourCustomLogger(); // your custom logging provider perhaps goes here
> ```

AddYourCustomLogger should register the logger provider with an implementation type or with a factory delegate, not with an implementation instance. That way, the dependency injection container will create the instance and will eventually dispose of it. 

```C#
using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace DisposableLoggerProviderDemo
{
    // Avoid error CS0718: 'Program': static types cannot be used as type arguments
    internal class Program
    {
        private static void Main()
        {
            Console.WriteLine("Creating and populating ServiceCollection");
            IServiceCollection serviceCollection = new ServiceCollection()
                .AddLogging(builder => builder.AddYourCustomLogger());

            Console.WriteLine("Building ServiceProvider");
            using (var serviceProvider = serviceCollection.BuildServiceProvider())
            {
                Console.WriteLine("Requesting ILogger<Program>");
                serviceProvider.GetRequiredService<ILogger<Program>>();
                Console.WriteLine("Got ILogger<Program>");

                Console.WriteLine("Disposing ServiceProvider");
            }

            Console.WriteLine("Disposed ServiceProvider");
        }
    }

    public static class YourCustomLoggerFactoryExtensions
    {
        public static ILoggingBuilder AddYourCustomLogger(this ILoggingBuilder builder)
        {
#if true
            // The DI container will create an instance and later dispose of it.
            builder.Services.AddSingleton<ILoggerProvider, YourCustomLoggerProvider>();
            return builder;
#else
            // This would not let the DI container dispose of the provider.
            return builder.AddProvider(new YourCustomLoggerProvider());
#endif
        }
    }

    public class YourCustomLoggerProvider : ILoggerProvider
    {
        public YourCustomLoggerProvider()
        {
            Console.WriteLine("Constructing YourCustomLoggerProvider");
        }

        public ILogger CreateLogger(string categoryName)
        {
            Console.WriteLine("Pretending to create a logger");
            return NullLogger.Instance;
        }

        public void Dispose()
        {
            Console.WriteLine("Disposing YourCustomLoggerProvider");
        }
    }
}
```

Output:

```
Creating and populating ServiceCollection
Building ServiceProvider
Requesting ILogger<Program>
Constructing YourCustomLoggerProvider
Pretending to create a logger
Got ILogger<Program>
Disposing ServiceProvider
Disposing YourCustomLoggerProvider
Disposed ServiceProvider
```

This example does not demonstrate `LoggerFactory.Create`, but the same `AddMyLogger` implementation should work with that as well, because `LoggerFactory.Create` creates a DI container under the hood and arranges for that to be disposed along with the logger factory.

**Comment by KalleOlaviNiemitalo** [comment]
If you do `builder.Services.AddSingleton<ILoggerProvider, YourCustomLoggerProvider>()`, the logger provider will be owned by the dependency injection container. And if you never dispose the DI container, then the DI container will never dispose the logger provider. So you should also do one of:

- Keep a reference to the DI container, and dispose it when finished. The DI container will then dispose the logger provider.
- Use `LoggerFactory.Create(Action<ILoggingBuilder>)`, and dispose the logger factory when finished. The logger factory will then dispose the DI container, which will in turn dispose the logger provider.

Alternatively, replace `AddSingleton` with `LoggerFactory.AddProvider(ILoggerProvider)`, and dispose the logger factory when finished. The logger factory will then dispose the logger provider.

**Comment by mhsimkin** [comment]
Thanks.  Consider this question resolved.
