### ISSUE TITLE
OSX CI builds failing "Please install openssl before running this script"

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#41006]
```
Starting: Build CoreCLR Runtime
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
/Users/runner/work/1/s/src/coreclr/build-runtime.sh checked x64   -ci
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/13eeaad6-9a45-4642-962d-c1b634862b71.sh
Commencing CoreCLR Repo build
__DistroRid: osx-x64
__RuntimeId: osx-x64
Setting up directories for build
Checking prerequisites...
/usr/local/bin/pkg-config
Please install openssl before running this script, see https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/macos-requirements.md

##[error]Bash exited with code '1'.
Finishing: Build CoreCLR Runtime

```
All OSX, iOS, tvOS, etc legs failing with this in 
https://github.com/dotnet/runtime/pull/41003
https://github.com/dotnet/runtime/pull/40877

**Comment by benaadams** [comment]
Also 
https://github.com/dotnet/runtime/pull/41004
https://github.com/dotnet/runtime/pull/41008

**Comment by wfurt** [comment]
cc: @MattGal

**Comment by safern** [comment]
Perhaps we're missing to link OpenSSL? 


https://github.com/dotnet/runtime/blob/60eff3f3766631bd4e7ee256ca17619fec90e9e6/eng/Brewfile#L6

cc: @akoeplinger

**Comment by MattGal** [comment]
> cc: @MattGal

I can't help with _these_ Macs unfortunately, but I would point out that right now (and through 10/1) there's a transition going on with the hosted Azure Devops mac hardware where it's moving from one place (and type of machine) to another; slightly variances there are quite possible.  Also, in order for the runtime OpenSSL-based tests to pass, we do absolutely have to link in the two dylibs referenced on the test machines, so something like that is likely in order here.

**Comment by safern** [comment]
@MattGal can you help me opening an ICM ticket to figure out what changed?

**Comment by MattGal** [comment]
Ah yes I can do that, let me chat with the team real quick though.

**Comment by jaredpar** [comment]
No hits in last 14 days, closing. 

https://runfo.azurewebsites.net/search/timelines/?bq=repository%3Aruntime+started%3A%7E14&tq=Please+install+openssl
