### ISSUE TITLE
Debugger.Launch not working on MacOS

### ISSUE THREAD

**Issue by thepalbi** [dotnet/runtime#41029]
### Description
A few days ago, while playing around with [Coyote](https://github.com/microsoft/coyote) I find out there was an issue while using a command that supposedly launches a debugger, and wait until you attach it to continue execution. This feature is not working in MacOS, but they suggested trying adding a 

```
Debugger.Launch()
```

to trigger the debugging. This is also not working in MacOS (when running a program directly from the CLI). However, I'm able to debug from VS. Also checked, and the call to `Debugger.Launch` is returning true, as if it executed correctly. 

Is it possible there's no support for this use-case in MacOS?

Also tried this small program:
```
namespace Microsoft.Coyote.Samples.HelloWorldTasks
{
    public static class Program
    {
        public static void Main()
        {
            bool debuggerLaunchSuccessful = Debugger.Launch();
            if (!debuggerLaunchSuccessful)
            {
                Console.WriteLine("Debugger launch not successful 😐");
            }

            Console.WriteLine("Program finished correctly");
        }
    }
}
```
And still getting not the expected behavior. Tried both with `dotnet run`, and building a standalone.

### Configuration
```
➜  HelloWorldTasks git:(master) ✗ dotnet --version
3.1.401
```
- MacOS 10.15.5

**Comment by thepalbi** [comment]
Thanks for the clarification. Left a note that this is not supported on Linux or MacOS, and ended up debugging by creating a custom Run Configuration on VS.

**Comment by danmosemsft** [comment]
@thepalbi you can click the pencil in the top right of the documentation topic to fix stuff like this -- I did it in this case.
