### ISSUE TITLE
[Perf -493%] System.Linq.Tests.Perf_Enumerable.FirstWithPredicate_LastElementMatches 

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#41028]
I am now running an independent 3.1 vs 5.0 comparison and I've confirmed that it's actual regression introduced in 5.0.

The issue has been originally reported by a bot owned by @DrewScoggins in https://github.com/DrewScoggins/performance-2/issues/860 Since I can't transfer issues from https://github.com/DrewScoggins/performance-2/ to https://github.com/dotnet/runtime I have simply copy-pasted its original content:

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Linq.Tests.Perf_Enumerable

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
FirstWithPredicate_LastElementMatches | 663.99 ns | 3.93 μs | 5.92 | Bimodal | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_08_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Linq.Tests.Perf_Enumerable_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_08_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Linq.Tests.Perf_Enumerable.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Linq.Tests.Perf_Enumerable.FirstWithPredicate_LastElementMatches'
```
<details>

#### System.Linq.Tests.Perf_Enumerable.FirstWithPredicate_LastElementMatches(input: IOrderedEnumerable)

```log
[ 574.083 ;  819.245) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 819.245 ; 1064.407) | 
[1064.407 ; 1309.569) | 
[1309.569 ; 1554.731) | 
[1554.731 ; 1799.892) | 
[1799.892 ; 2045.054) | 
[2045.054 ; 2290.216) | 
[2290.216 ; 2535.378) | 
[2535.378 ; 2780.539) | 
[2780.539 ; 3025.701) | 
[3025.701 ; 3270.863) | 
[3270.863 ; 3516.025) | 
[3516.025 ; 3825.415) | 
[3825.415 ; 4101.643) | @@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by adamsitnik** [comment]
## System.Linq.Tests.Perf_Enumerable.FirstWithPredicate_LastElementMatches(input: IOrderedEnumerable)

| Conclusion |   Base |    Diff | Base/Diff | Modality | Operating System        | Bit | Processor Name                              | Base Runtime    | Diff Runtime         |
| ---------- | ------:| -------:| ---------:| --------:| ----------------------- | --- | ------------------------------------------- | --------------- | --------------------- |
| Slower     | 972.74 | 8054.46 |      0.12 |          | Windows 10.0.18363.1016 | Arm | Microsoft SQ1 3.0 GHz                       | .NET Core 3.1.6 | 5.0.100-rc.1.20413.9 |
| Slower     | 598.37 | 3519.26 |      0.17 |          | Windows 10.0.18363.959  | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20404.3 |
| Slower     | 610.20 | 3674.19 |      0.17 |          | Windows 10.0.18363.959  | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3 |
| Slower     | 700.86 | 4238.85 |      0.17 |          | Windows 10.0.19041.450  | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20413.9 |
| Slower     | 626.94 | 3928.55 |      0.16 |          | ubuntu 18.04            | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20403.23|
| Slower     | 743.69 | 4727.58 |      0.16 |          | macOS Mojave 10.14.5    | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20404.2 |

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/39032#issuecomment-656678750
