### ISSUE TITLE
Upcoming OpenSSL change is likely going to cause failing unit tests

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#41021]
This is a heads up warning. The `PKCS12_parse` function used for certificate import on Linux systems used inconsistent ordering (https://github.com/openssl/openssl/issues/6698). Now OpenSSL was modified to reverse the order of the certificates (https://github.com/openssl/openssl/commit/fc0aae737eb1cb2d2554caa8bffea80b8cbd38f9). .NET has [unit tests that check the order of the imported certificates](https://github.com/dotnet/runtime/blob/efafca9bd8ba5a746634820596f8144d0d98fde1/src/libraries/System.Security.Cryptography.X509Certificates/tests/CollectionImportTests.cs#L353-L391). Once this change reaches a production version of OpenSSL it will lead to change in behavior that will cause the unit tests to fail. At the moment the change is included only in the OpenSSL 3.0 branch (master) but it's been mentioned that a port to the OpenSSL 1.1.x branch is planned. 

cc @vcsjones @bartonjs

**Comment by vcsjones** [comment]
Hm, .NET does not use `PKCS12_parse` anymore for decoding PKCS12 files, it's all done with `Pkcs12Info` and friends. The only place it is used is in the OpenSSL certificate "store" which does not get impacted by this. I don't believe there is anything actionable here, unless I am misunderstanding?

**Comment by bartonjs** [comment]
It's still used for 2.1 (EoL in August) and 3.1 (Dec 2022), so if the change does get serviced into OpenSSL we may have to service .NET.

That said, I agree that right now the issue isn't very actionable.

**Comment by filipnavara** [comment]
I agree there's not anything actionable at the moment. At the time I opened the issue it looked like it may become an issue.
