### ISSUE TITLE
[Cross-targeted DBI] CordbModule::InitPublicMetaDataFromFile always returns E_FAIL in the cross-targeted DBI

### ISSUE THREAD

**Issue by clguiman** [dotnet/runtime#41034]
### Description
Some cross-DAC/DBI changes were not backported in 3.1.*. 
For example CordbModule::InitPublicMetaDataFromFile  always returns E_FAIL so the DBI caller cannot provide an external module when the module metadata is missing from the target (all CoreDump scenarios except full dumps).
I suspect the issue is caused by the `#ifdef FEATURE_FAL:`  code line here https://github.com/dotnet/coreclr/blob/dev/diag-cross-dac/3.1.4/src/debug/di/module.cpp#L883 .
I think master doesn't have the same issue (I can't verify since I don't have any 5.0 DAC/DBI binaries), but I need someone to confirm: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/debug/di/module.cpp#L872 (notice the `#ifdef TARGET_UNIX`)

**Comment by tommcdon** [comment]
@sdmaclea

**Comment by sdmaclea** [comment]
Master would behave the same.  Master renamed `FEATURE_PAL` to `TARGET_UNIX`.

Can you elaborate how important this is?  We need probably need to backport this to 5.0 if it is important.

**Comment by clguiman** [comment]
Without a fix we would be able to only debug full memory core dumps. By default the "createdump" tool doesn't contain modules with metadata information, the debugger is supposed to download them from the symbol server and provide them to the DBI (using logic from that method).
dotnet-dump has the same issue when calling "clrstack -i -a". I can provide coredumps that have this issue if needed.

**Comment by sdmaclea** [comment]
@mikem8361

**Comment by noahfalk** [comment]
> By default the "createdump" tool doesn't contain modules with metadata information

@mikem8361 - I thought we changed that policy and now the default dumps do have metadata?

**Comment by mikem8361** [comment]
The `dotnet-dump collect` default was changed to full dumps (which includes the metadata), but the env var based createdump crash/unhandled exception trigger still defaults to "mini".

**Comment by mikem8361** [comment]
This has been fixed and backported to 5.0.
