### ISSUE TITLE
IDictionary/IReadOnlyDictionary - ICollection/IReadOnlyCollection

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#41035]
Please make the following enhacements:
1.  Please make ICollection<T> implement IReadOnlyCollection<T>
2.  Please make IDictionary<K,V> implement IReadOnlyDictionary<K,V>

I believe this is a very minor change.

**Comment by EgorBo** [comment]
Duplicates: https://github.com/dotnet/runtime/issues/31001

> I believe this is a very minor change.

there are pitfalls, e.g. https://github.com/dotnet/runtime/pull/33245#issuecomment-597890374

**Comment by layomia** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/31001.
