### ISSUE TITLE
Behaviour of LogInformation inconsistent with String.Format

### ISSUE THREAD

**Issue by Ninds** [dotnet/runtime#41030]
Hi,
I have the following code \:
```csharp
using Microsoft.Extensions.Logging;
using System;
namespace LogFormat
{
    class Program
    {
        static void Main(string[] args)
        {
            ILogger logger = LoggerFactory.Create(lb => lb.AddConsole()).CreateLogger<Program>();

            // Following 2 lines work as expected
            Console.WriteLine(string.Format("{0}{1}{1}", "a", "b"));
            Console.WriteLine("{0}{1}{1}", "a", "b");

            // The following line throws

            logger.LogInformation("{0}{1}{1}", "a", "b");
        }
    }
}
```
And it throws as indicated.

Perhaps it's expected behaviour in which case confirmation would be appreciated, else I guess it's an oversight.

Thanks
N

**Comment by davidfowl** [comment]
Yes it's expected. There's actually an analyzer to detect these usage patterns and warn you but it's not on by default yet. Logging wants you to use named format strings so that structured logging works (we capture the names of the format string).


This is what logging implements https://messagetemplates.org

**Comment by Ninds** [comment]
> Yes it's expected. There's actually an analyzer to detect these usage patterns and warn you but it's not on by default yet. Logging wants you to use named format strings so that structured logging works (we capture the names of the format string).
> 
> This is what logging implements https://messagetemplates.org

Cheers mate ! 
It clears up a bit of confusion that I didn't realise I had had. 
I read somewhere that string interpolation should be avoided so went back to using the format as demonstrated in the code above.
However All clear now \: structured logging. \neq string interpolation
