### ISSUE TITLE
Missing nullability documentation for library types

### ISSUE THREAD

**Issue by shravan2x** [dotnet/runtime#41077]
Some types in the .NET core library return nullable references since C# 8, but documentation does not explain what cases they may be null in.

1. `ArraySegment<T>.Array` returns a `T[]?`. Looking at [the source here](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/ArraySegment.cs#L36), the field is readonly and always has a value set in constructors so it shouldn't ever be null?
2. `Process.Threads` returns a `ProcessThreadCollection`. Iterating over this collection using a foreach loop like `foreach (ProcessThread thread in process.Threads)` raises a CS8600 since `ProcessThread` may be null. Changing it to `ProcessThread?` resolves the issue but I can't handle the null case unless I know what causes it.
3. `AppDomain.CurrentDomain.BaseDirectory` returns a `string?`

### Configuration

* Which version of .NET is the code running on? .NET Core 3.1

**Comment by reflectronic** [comment]
>  the field is readonly and always has a value set in constructors so it shouldn't ever be null?

`ArraySegment<T>` is a struct, so getting a `default` instance would leave that field empty.

> Iterating over [`ProcessThreadCollection`] using a foreach loop like `foreach (ProcessThread thread in process.Threads)` raises a CS8600

I believe this was fixed in https://github.com/dotnet/runtime/pull/37969. They made that change for the reason you describe; I don't think that the collection returned from `Process.Threads` will actually contain `null`.

> `AppDomain.CurrentDomain.BaseDirectory` returns a `string?`

This one was fixed in https://github.com/dotnet/runtime/pull/32486. It seems to have been annotated that way by mistake.

**Comment by shravan2x** [comment]
Will the fixes be available sooner than .NET 5?

**Comment by reflectronic** [comment]
Likely not. I'm not sure if those would be compatible changes to make, but regardless, I don't think they can change the reference assemblies for these APIs in servicing releases.

**Comment by shravan2x** [comment]
Alright, thanks for the quick responses!
