### ISSUE TITLE
Mark APIs as unsupported on Browser WASM

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#41087]
We can use `UnsupportedOSPlatformAttribute("browser")` attribute to mark unsupported APIs on Browser WASM so that the analyzer can provide warnings when developers accidentally call platform-specific APIs.
Spec: https://github.com/dotnet/designs/pull/144

We use the scanner (https://github.com/dotnet/platform-compat) to gather the list of all the APIs throwing PNSE on Browser WASM at the moment. Below is the file containing ~4500 PNSE methods. 
[pnse-17082020.txt](https://github.com/dotnet/runtime/files/5104573/pnse-17082020.txt)

There can be some special cases:
- APIs can be Windows-specific
- APIs might throw PNSE for all platforms
- APIs might not be considered to be marked (e.g. APIs are not meant to be directly called by user code)
- other cases?

### Namespaces (L# in file above)
- [x] Microsoft.VisualBasic L2-L45 (marked as Windows-specific)
- [x] System.Security.AccessControl L46-65 (marked as Windows-specific)
- [x] Microsoft.Win32.Registry L66-106 (marked as Windows-specific)
- [x] System.Collections L107-L110 (<s>https://github.com/dotnet/runtime/pull/41085</s>) serialization-related infrastructure
- [x] System.Collections.Specialize L111-L114 (<s>https://github.com/dotnet/runtime/pull/41085</s>) serialization-related infrastructure
- [x] System.ComponentModel L115-L120 (https://github.com/dotnet/runtime/pull/41094) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Console L121-L172 (https://github.com/dotnet/runtime/pull/41184) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Data.Common L173-L178 (<s>https://github.com/dotnet/runtime/pull/41263</s>) false-positive, obsolete, serialization related
- [x] System.Data.Odbc (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Diagnostics.FileVersionInfo L179-L207 (https://github.com/dotnet/runtime/pull/41271) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Diagnostics.Process L208-L388 (https://github.com/dotnet/runtime/pull/41694) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Diagnostics.TextWriterTraceListener L389-L393 (<s>https://github.com/dotnet/runtime/pull/41327</s>) False Positive
- [x] System.DirectoryServices.Protocols (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Drawing.Common (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.IO.Compression L394-429 (https://github.com/dotnet/runtime/pull/41683) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.IO.FileSystem.AccessControl L430-L489 (marked as Windows-specific)
- [x] System.IO.FileSystem L490-L495 (marked as Windows-specific)
- [x] System.IO.FileSystem.DriveInfo L496-L497 (<s>https://github.com/dotnet/runtime/pull/41328</s>)
- [x] System.IO.FileSystem.Watcher L498-L547 (https://github.com/dotnet/runtime/pull/41682) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.IO.IsolatedStorage L548-L647 (https://github.com/dotnet/runtime/pull/41700) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.IO.MemoryMappedFiles L648-L662 (<s>https://github.com/dotnet/runtime/pull/41971</s>) false-positive
- [x] System.IO.Pipes L663-L778 (https://github.com/dotnet/runtime/pull/41976) <b>backport https://github.com/dotnet/runtime/pull/42267</b>
- [x] System.IO.Ports (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Linq.Expressions L779 (marked as obsolete)
- [x] System.Linq.Queryable L780-L782 (<s>https://github.com/dotnet/runtime/pull/41330</s>) False Positive
- [x] System.Net.Connections L783 (the namespace is being removed; see PRs 41648 and 42099)
- [x] System.Net.Http L784-L872 (https://github.com/dotnet/runtime/pull/42074) <b>backport https://github.com/dotnet/runtime/pull/42267</b>
- [x] System.Net.HttpListener L873-L883 (https://github.com/dotnet/runtime/pull/42063) <b>backport https://github.com/dotnet/runtime/pull/42267</b>
- [x] System.Net.Mail L884-L1083 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.NameResolution L1084-L1109 (https://github.com/dotnet/runtime/pull/41985) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.NetworkInformation L1110-L1208 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.Ping L1209-L1250 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.Primitives L1251-L1255 (<s>https://github.com/dotnet/runtime/pull/41987</s>) false-positive
- [x] System.Net.Requests L1256-L1600 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.Security L1601-L1828 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.Sockets L1829-L2240 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.Webclient L2241-L2374 (https://github.com/dotnet/runtime/pull/40924) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.WebHeaderCollection L2375-L2377 Serialization Infrastructure
- [x] System.Net.WebProxy L2378-L2383 obsolete/all platforms/serialization-related infrastructure
- [x] System.Net.WebSockets.Client L2384-L2400 (https://github.com/dotnet/runtime/pull/41963) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Net.WebSockets L2401 PNSE everywhere
- [x] System.Runtime L2402-L2424, L2445-L2467 (<s>https://github.com/dotnet/runtime/pull/42030</s>) False-positives/PNSE all mono/windows only
- [x] System.Utf8String.Experimental L2425-L2444, L2507-L2523 likely false positive
- [x] System.Threading.Thread L2468-L2474, L2497 (<s>https://github.com/dotnet/runtime/pull/41892</s>)
- [x] System.Threading.ThreadPool L2475-L2484, L2490 (https://github.com/dotnet/runtime/pull/41891) <b>backport https://github.com/dotnet/runtime/pull/41967</b>
- [x] System.Threading L2485-L2489, L2496, L2498-L2499 (<s>https://github.com/dotnet/runtime/pull/41888</s>)
- [x] System.Threading.Overlapped L2491-L2495 (<s>https://github.com/dotnet/runtime/pull/41884</s>) windows-specific
- [x] System.Private.CoreLib L2500-L2506, L2524-L2600 False-positives/Serialization-related/PNSE all platforms
- [x] System.Runtime.Serialization.Xml L2601-L2617 (all platforms)
- [x] System.Private.Xml L2618 false-positive
- [x] System.Private.Xml.Linq L2619 serialization-related infrastructure
- [x] System.Reflection.DispatchProxy L2620 false-positive (DispatchProxyTests.cs tests pass)
- [x] System.Resources.Writer L2621-L2623 false-positives (ResourceWriterUnitTest.cs passes)
- [x] System.Runtime.InteropServices L2624-L2625 (windows-specific), 2626-2628 (all platforms)
- [x] System.Runtime.Serialization.Formatters L2629-L2630 obsolete
- [x] System.Security.AccessControl L2631-L2909 windows-specific
- [x] System.Security.Claims L2910-2915 (all platforms)
- [x] System.Secuirty.Cryptography L2916-L3464 (https://github.com/dotnet/runtime/pull/42010) <b>backport https://github.com/dotnet/runtime/pull/42267</b>
- [x] System.Security.Cryptography.Cng L3465-L3716 windows-specific
- [x] System.Security.Cryptography.Csp L3717-L3895 (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Cryptography.Encoding L3896-L3974 (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Cryptography.OpenSsl L3975-L4034(https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Cryptography.Pkcs (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Cryptography.Primitives L4035-L4045(https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Cryptography.X509Certificates L4046-4375(https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Cryptography.Xml (https://github.com/dotnet/runtime/pull/40612) <b>No backport necessary</b>
- [x] System.Security.Principal.Windows L4376-L4471 windows-specific
- [x] System.Text.Encodings.Web L4472 Looks like a false-positive
- [x] System.Text.Json L4473-L4494 Looks like false-positives
- [x] System.Text.RegularExpressions L4495-L4499 Looks like false-positives
- [x] System.Transactions.Local L4500-4509 (<s>https://github.com/dotnet/runtime/pull/42027</s>) PNSE all platforms

cc @steveisok @lewing

**Comment by akoeplinger** [comment]
@jeffhandley @adamsitnik while adding the `[UnsupportedOSPlatform]` attributes to the src a question came up what to do when the method we're annotating has multiple implementations (e.g. .Browser.cs, .Unix.cs and .Windows.cs).

Should we add the attribute to all the implementations in those cases? If we don't do that then regenerating the ref would remove the attribute if you're on a different platform.

**Comment by jeffhandley** [comment]
I've been encountering similar stuff with https://github.com/dotnet/runtime/pull/41209, where we're trying to get the runtime repo ready to receive the analyzer. We don't yet have a solid strategy for this scenario.

**Comment by adamsitnik** [comment]
> Should we add the attribute to all the implementations in those cases?

**Comment by jeffhandley** [comment]
We have now filed https://github.com/dotnet/runtime/issues/41354 against the runtime repo to resolve the issues there for RC2.

**Comment by MaximLipnin** [comment]
It looks like the exception scanner doesn't gather PNSEs thrown from runtime, e.g. something that uses `mono_error_set_platform_not_supported` method. At least, I don't see appropriate APIs in the result file attached to the PR's description. In case of Browser, an example of such API could be [Thread.Start()](https://github.com/dotnet/runtime/blob/master/src/mono/netcore/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs#L254-L257) which invokes `StartInternal -> ves_icall_System_Threading_Thread_StartInternal -> mono_error_set_platform_not_supported` .

**Comment by sigmarsson** [comment]
Hi Seniors, Is there an alternative way to retrieve assembly version info on Wasm instead of `FileVersionInfo` ?
That is not supported any more in the browser. 

https://github.com/unoplatform/uno/issues/5916

**Comment by marek-safar** [comment]
@sigmarsson what about using `RuntimeEnvironment.GetSystemVersion ()` ?

**Comment by sigmarsson** [comment]
@marek-safar i wish to retrieve either the calling or the executing assembly version.

**Comment by sigmarsson** [comment]
E.g.

![image](https://user-images.githubusercontent.com/43340959/117109484-07ea8e00-ad85-11eb-8a23-a6699f808cda.png)

**Comment by marek-safar** [comment]
I see, in that case, the closest approximation would be to read System.Reflection.AssemblyFileVersionAttribute from the assembly.

**Comment by MaximLipnin** [comment]
All the namespaces mentioned in this issue are covered so I'm closing it as completed
