### ISSUE TITLE
Unable to build release/3.1 with Clang 12

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#41095]
I am unable to build the release/3.1 branch on Big Sur beta 5 (20A5354i) with Xcode beta 5 tools, with the following build error:

<pre>
EXEC : error : include location '/usr/local/include' is unsafe for cross-compilation [-Werror,-Wpoison-system-directories] [/Users/kjones/Projects/corefx/src/Native/build-native.proj]
  1 error generated.
  make[2]: *** [System.Native/CMakeFiles/System.Native-Static.dir/pal_console.c.o] Error 1
  make[1]: *** [System.Native/CMakeFiles/System.Native-Static.dir/all] Error 2
  make: *** [all] Error 2
  Failed to build corefx native components.
/Users/kjones/Projects/corefx/src/Native/build-native.proj(36,5): error MSB3073: The command ""/Users/kjones/Projects/corefx/src/Native/build-native.sh" x64 Debug OSX outconfig netcoreapp-OSX-Debug-x64 -portable" exited with code 1.

Build FAILED.
</pre>

This error does not occur in release/5.0 or main.

**Comment by vcsjones** [comment]
Repros on release/2.1 as well. There are other errors for 2.1 as well.

<pre>
/Users/kjones/Projects/corefx/src/Native/Unix/System.Net.Http.Native/pal_easy.cpp:146:16: error: comparison of different enumeration types ('PAL_CURLoption' and
      '(anonymous enum at /Users/kjones/Projects/corefx/src/Native/Unix/System.Net.Http.Native/pal_easy.h:11:1)') [-Werror,-Wanon-enum-enum-conversion]
    if (option >= CurlOptionOffTBase)
        ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
2 errors generated.
</pre>

**Comment by danmosemsft** [comment]
I suggest to close this then and just add the flag locally.. Enough others trip on this, or somehow we decide we need to build 3.1 this way, we can revisit.
