### ISSUE TITLE
System.DirectoryServices.Protocols Bind on Linux and OSX throws "The distinguished name contains invalid syntax." exception

### ISSUE THREAD

**Issue by mdshaner** [dotnet/runtime#41103]
### Description

When using a LdapConnection to Bind I get a System.DirectoryServices.Protocols.DirectoryOperationException being thrown with the message "The distinguished name contains invalid syntax.".

```
            using LdapConnection ldapConnection = new LdapConnection(new LdapDirectoryIdentifier("some-active-directory.server"));
            ldapConnection.AuthType = AuthType.Negotiate;
            ldapConnection.Credential = new NetworkCredential(username, password, domain);
            ldapConnection.Timeout = TimeSpan.FromSeconds(1);
            ldapConnection.Bind();
```
https://github.com/mdshaner/ldap-test-dotnet5 is a repo with a test that can demonstrate the issue. The only things that need to be 
This is the minimal code that I am using, where username is a simple "mshaner" and not a DN. The code works on Windows however. I 

### Configuration

.NET 5 Preview 7 (5.0.100-preview.7.20366.6)
Ubuntu 20.04 LTS x64 has the issue.
MacOS 10.15.6 x64 has the issue.
Windows 10 x64 does not have the issue.
I am testing against a Microsoft Active Directory server.

### Other information

```System.DirectoryServices.Protocols.DirectoryOperationException : The distinguished name contains invalid syntax.
   at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
   at System.DirectoryServices.Protocols.LdapConnection.Bind()
   at LdapTest.LdapTester.Test(String username, String password, String domain) in /home/matt/Proof/ldap-test-dotnet5/LdapTest/LdapTester.cs:line 23
   at LdapTestTest.Tests.Test_ShouldAuthenticate() in /home/matt/Proof/ldap-test-dotnet5/LdapTestTest/LdapTesterTest.cs:line 21
```

I did look into the openldap library code and it does look like they are generally expecting a DN to be passed in, while winldap can handle an NT style username.

**Comment by joperezr** [comment]
Thanks for the report @mdshaner, are you able to repro if you instead use `mshaner@YOURREALM.COM` as opposed to just using the username? I've found that openldap (the native library that underneath handles the connection on Linux and OSX) accepts user@REALM.COM format and REALM\user format, but I don't think that just having the user in there is supported by openldap.

**Comment by mdshaner** [comment]
Yes, it does reproduce if I use user@realm.com or REALM\user with  the same exception ```System.DirectoryServices.Protocols.DirectoryOperationException : The distinguished name contains invalid syntax.```

Also to clarify, I am just passing in "user", "user@realm.com" or "REALM\user" in as the username, I am not providing a DN like "CN=User,DC=REALM,DC=COM"

**Comment by joperezr** [comment]
Just to make sure it is not a connectivity problem (as we haven't seen errors like that user user@realm.com) can you try using the openldap linux tools to try to perform a quick search on your ldap directory to see if you are able to connect with that? Here is some quick tips on how to search with ldapsearch tool: https://devconnected.com/how-to-search-ldap-using-ldapsearch-examples/

Basically you want to do something similar to:
`ldapsearch -x -b <search_base> -H <ldap_host> -D <bind_dn> -W` and see if you are able to search.

One other thing that may be happening here is that you might be using an unsupported format to specify your ldap server. Do you mind sharing the code snippet you are trying (obviously without the part where you set your credentials)

**Comment by mdshaner** [comment]
I have a reproduction case up at https://github.com/mdshaner/ldap-test-dotnet5. But the short of it is I'm just passing the ip address in to build the LdapDirectoryIdentifier and then using .Bind() to test the credentials.
```Identifier = new LdapDirectoryIdentifier("192.168.192.168.6.145");``` 

I'll take a look at ldapsearch and see if that can help me get further along. Thank you.

**Comment by joperezr** [comment]
One thing you may want to try which looks like you aren't doing is to set the Protocol Version to be 3, which is not the default in openLdap. You can do so by adding this:
`connection.SessionOptions.ProtocolVersion = 3;`

We do this in both Windows and Linux when running our unit tests as you can see here:

https://github.com/dotnet/runtime/blob/ea06e0c05c34602d4fbb920cff30f681f30b8d81/src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs#L559-L577

**Comment by mdshaner** [comment]
I appreciate the help. It has actually revealed a lot of where my issue is. I had erroneously thought the error was coming from within the libldap, but thanks to those look ups, it's actually something on our LDAP server, so I appreciate your help and I am so glad it's a bit of user error on my part :).

**Comment by joperezr** [comment]
good to know, I'm glad we could help. I'll go ahead and close it for now, but feel free to reopen if you deem necessary.

**Comment by danmosemsft** [comment]
@joperezr I wonder whether `connection.SessionOptions.ProtocolVersion = 3;` is something we should doc, or include in a blog post, if it's helpful. I'm just thinking what would we share if someone asked, how to start using this on Linux.

**Comment by joperezr** [comment]
sure, having it in either a blog or a doc would be nice. I wouldn't change the default as we want to keep the default protocol to be chosen by the LDAP server itself in case a specific one is not provided, bug most LDAP servers today default to protocol version 2 (including Active Directory) which lacks several [features that got added in three](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ldap/differences-between-ldap-2-and-ldap-3) like:

> - Use of UTF-8 for all text string attributes to support extended character sets.
> - Operational attributes that the directory maintains for its own use; for example, to log the date and time when another attribute has been modified.
> - Referrals allow a server to direct a client to another server that may have the data that the client requested.
> - Schema publishing with the directory, allowing a client to discover the object classes and attributes that a server supports.
> - Extended searching operations to allow paging and sorting of results, and client-defined searching and sorting controls.
> - Stronger security through an SASL-based authentication mechanism.
> - Extended operations, providing additional features without changing the protocol version.

Most cases basic operations will still work if you stick to protocol version 2.
