### ISSUE TITLE
Add ConnectionId to ConnectionBase

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#41110]
## Background and Motivation

I migrated [Project Bedrock](https://github.com/davidfowl/BedrockFramework) to the new [System.Net.Connections](https://github.com/dotnet/runtime/issues) APIs and I wanted to make some last minute tweaks based on the usage.

## Proposed APIs

```diff
namespace System.Net.Connections
{
    public class ConnectionBase
    {
+      public virtual string ConnectionId { get; }
    }
```

Adding a connection id, this a great for logging and correlation. We use this extensively today in ASP.NET core to track connections and associate them with requests.

cc @geoffkizer @scalablecory @halter73

**Comment by terrajobst** [comment]
@scalablecory please flip this to ready for review ASAP.

**Comment by scalablecory** [comment]
Why a `string`? I guess you expect connection instantiations to wrap a `long`?

**Comment by davidfowl** [comment]
@scalablecory string because that's the most generic thing representation for an identifier. This will be used as a dictionary key, it'll be logged as well. It'll most likely come from the underlying transport or be random. I'm not a fan of baking this into a long just because its much less restrictive.

**Comment by scalablecory** [comment]
@davidfowl why make this abstract?

We could make it `long` and have `ConnectionBase` ctor set it.

**Comment by davidfowl** [comment]
It should really be a string. It it doesn't need to be abstract.

**Comment by scalablecory** [comment]
> @scalablecory string because that's the most generic thing representation for an identifier. This will be used as a dictionary key, it'll be logged as well. It'll most likely come from the underlying transport or be random. I'm not a fan of baking this into a long just because its much less restrictive.

I don't buy any of this versus `long`. Are we concerned about compat with existing APIs?

**Comment by halter73** [comment]
Using a string will make porting Kestrel's existing transport more straightforward. In the case of Kestrel's HTTP/2 streams, the request ID is "{ConnectionId}:{StreamId}". This is useful for debugging. Today, Kestrel's HTTP/2 streams aren't `Connection`s, but I imagine we'll want something similar for QUIC streams.

What's wrong with using a string? Slower comparisons?

**Comment by geoffkizer** [comment]
Is this strictly for diagnostic purposes, or something else?
Does it have to be guaranteed to be unique? If so why?
How does Kestrel generate these today?

For diagnostic purposes, I've always found that just using GetHashCode works quite nicely. Sure, it's not guaranteed to be unique, but the chance of duplicates is very small, and that's good enough for diagnostic purposes.

**Comment by davidfowl** [comment]
> Is this strictly for diagnostic purposes, or something else?

We use them for diagnostics purposes, but I'd expect that they can be used as dictionary keys.

> Does it have to be guaranteed to be unique? If so why?

So they can be used as a dictionary key and for diagnostics.

> How does Kestrel generate these today?

https://github.com/dotnet/aspnetcore/blob/7e0e50f052bf6de337efdbde3d00a79b00037829/src/Servers/Kestrel/shared/CorrelationIdGenerator.cs#L21

https://github.com/dotnet/aspnetcore/blob/1c71752b1ff99bfd8dd70f54f127832a1645ae35/src/Servers/Kestrel/shared/TransportConnection.cs#L27-L42

We generate a string from a long.

> For diagnostic purposes, I've always found that just using GetHashCode works quite nicely. Sure, it's not guaranteed to be unique, but the chance of duplicates is very small, and that's good enough for diagnostic purposes.

We want something that can be persisted in logs just like request ids can be (we use a similar algorithm for generating unique request ids). We also generate and log the connection id *everywhere* so it's nicely captured in structured logging and can be associated with requests and all operations that we capture that run as part of the connection.

One big advantage to using the string over the long is that the logger doesn't have to re-allocate the string whenever it's pushed out to the logging system (which is quite alot).

**Comment by geoffkizer** [comment]
> We want something that can be persisted in logs just like request ids can be

Is GetHashCode insufficient for this in some way?

**Comment by geoffkizer** [comment]
BTW, the algorithm you use for generating these things looks a lot like a hash function :) In other words, why not just use the built-in hash function in GetHashCode?

**Comment by terrajobst** [comment]
* The connection id shouldn't change. Some protocols, such as QUIC, have changing ids but the connection id of `ConnectionBase` won't be using that. Otherwise, it's impossible for users to track instances over time, which is the goal for this property.
* To guarantee this, we should the template method pattern where the property is non-virtual and it calls a virtual method to lazily initialize itself.
* The base implementation will use an auto generated GUID or a monotonically increasing integer
* We should allow passing the connection ID to `FromPipe` and `FromStream` 

```C#
namespace System.Net.Connections
{
    public partial class ConnectionBase
    {
        public string ConnectionId { get; }
        protected virtual string CreateConnectionId();
    }
    public partial class Connection
    {
        // Existing method, add connectionId
        public static Connection FromPipe(
            IDuplexPipe pipe,
            bool leaveOpen = false,
            IConnectionProperties? properties = null,
            EndPoint? localEndPoint = null,
            EndPoint? remoteEndPoint = null,
            string? connectionId = null);


        // Existing method, add connectionId
        public static Connection FromStream(
            Stream stream,
            bool leaveOpen = false,
            IConnectionProperties? properties = null,
            EndPoint? localEndPoint = null,
            EndPoint? remoteEndPoint = null,
            string? connectionId = null);
    }
}
```

**Comment by karelz** [comment]
Moving to 6.0 as we won't ship these APIs in 5.0.

**Comment by stephentoub** [comment]
I'm going to close this.  If this library ever comes back, this can be a part of it, but until then, it's not actionable.

**Comment by davidfowl** [comment]
RIP
