### ISSUE TITLE
Unable to run libraries tests with Mono, missing libhostpolicy

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#41123]
Running this:
```
./build.sh mono+libs -c debug
./dotnet.sh build src/libraries/System.Reflection/tests/ /t:test /p:configuration=debug
```
Gives me the following error:
```
  A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/ryan/git/runtime/artifacts/bin/testhost/net5.0-OSX-Debug-x64/shared/Microsoft.NETCore.App/6.0.0'.
```
This worked less than a week ago, so I'm not sure what changed. Full log here: https://gist.github.com/CoffeeFlux/e67692c180986e290c48935738360010

**Comment by CoffeeFlux** [comment]
cc: @steveisok

**Comment by steveisok** [comment]
Weird, works on my machine w/ latest master.

**Comment by CoffeeFlux** [comment]
This was resolved by rebuilding and specifying `-Subset` in the build invocation. I haven't the faintest idea why that solved this, but I guess we can close the issue? If anyone else encounters the same problem they can always reopen it.
