### ISSUE TITLE
Consider shipping OSX Universal binaries

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#41127]
With the introduction of Apple Silicon, Apple is reintroducing Universal binaries.

For instance:
```
$ file $(which uname)
/usr/bin/uname: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/uname (for architecture x86_64):       Mach-O 64-bit executable x86_64
/usr/bin/uname (for architecture arm64e):       Mach-O 64-bit executable arm64e
```

For instance,
+ We need to decide if we will ship the runtime as a universal binary.
+ We need to decide what it means for osx crossgen
+ We need to decide what it means for osx single file.

**Comment by iMonZ** [comment]
https://github.com/dotnet/runtime/issues/43313#issuecomment-800193208

**Comment by lewing** [comment]
@jeffhandly no it has nothing to with wasm other than we're one of the platforms that use cross compilers.

**Comment by danmoseley** [comment]
@agocke I think the right home for this is host?

**Comment by agocke** [comment]
We've decided not to do this -- instead "single-file" applications can be compiled into two separate arch-specific binaries, and then lipo'd into universal binaries.
