### ISSUE TITLE
Investigate building osx-arm64 on osx-x64

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#41133]
It seems like it is feasible to build osx-arm64 on a osx-x64 build platform.  

Investigate and see what needs to be done.

This will prepare us for #41131

**Comment by sdmaclea** [comment]
I think this should be close to working in #40943 

Per XCode release notes, we seem to need at least XCode 12 Beta *.  Which requires
```
Xcode 12 beta 6 requires Apple silicon running macOS Big Sur 11 beta or later, or an Intel-based Mac running macOS Catalina 10.15.4 or later
```

I'll try this upgrade week when I have stable WiFi....

**Comment by sdmaclea** [comment]
@dotnet/osx-arm64-core This is the github alias I created.

**Comment by janvorli** [comment]
This was already done in #43187
