### ISSUE TITLE
System.Diagnostics.PerformanceCounter crashes on SurfacePro X

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/runtime#41144]
### Description

We have created a .NET5 preview7 application where we utilize Performance counters. 

On a development machine this works well, but on SurfaceProX the application crashes. 

Looking into the PerformanceCounter code in the netcoreapp2.0 folder inside the nuget, it seems to be reliant on registry keys for .NET Framework to be installed in order to load the native dll perfcounter.dll from a directory specified by that those keys. 

![image](https://user-images.githubusercontent.com/9577365/90869070-ffd5f400-e397-11ea-84c1-5c5fcf402fcb.png)

We expected three things: 
1. No reliance on .NET Framework 
2. No reliance on Windows registry 
3. Performance counters to work on SurfaceProX. 

Is this a bug or a limitation to how far you want to support System.Diagnostics. 

This has apparently been a problem before: https://developercommunity.visualstudio.com/content/problem/310772/module-not-found-exception-when-calling-countersam.html?childToView=394219#comment-394219

**Comment by ericstj** [comment]
> I'm wonder what other places we rely on .NET Framework - the only one I know of is System.Management, where the native part of the implementation is in .NET Framework. That's inevitable.

So this just came up and I noticed System.Management, System.Diagnostics.PerformanceCounter, and System.Diagnostics.EventLog all try to load binaries from the .NETFramework directory.

**Comment by ericstj** [comment]
I took a look at this perfcounter case and it looks to me like the managed code is unnecessarily using that .NETFramework DLL.  The [FormatRawValue](http://vstfdevdiv:8080/devdiv2/DevDiv/_versionControl?path=%24%2FDevDiv%2FFX%2FRel%2FNet48Rel1%2FNDP%2Fclr%2Fsrc%2FProfile%2FPerfCounter%2FPerformanceCounterProvider.cpp&line=283&lineStyle=plain&lineEnd=284&lineStartColumn=1&lineEndColumn=1) function is the only method called and this is just a pass through to [PdhFormatRawValue](https://docs.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhformatfromrawvalue).  I think we can just remove this dependency and call directly into pdh.dll.

PerfCounter.dll is more important for reading .NET Performance counters.  What happens in this case is the .NET Performance counter is registered as implemented in performance dll netfxperf.dll.  NetFxPerf.dll just decides which version of perfcounter.dll to load which is in the .NETFramework.  When a .NET Performance counter is created from a .NET application for writing the managed side of this code opens up a shared memory file in a known location and writes the counter information to it.  When a counter is read from any type of application, the consumer goes through the registry as has been mentioned, which [loads](https://docs.microsoft.com/en-us/windows/win32/perfctrs/providing-counter-data-using-a-performance-dll) up netfxperf.dll which loads perfcounter.dll (into their own process) and perfcounter.dll knows how to access and read the shared memory that is written by the .NET process.

So this means that we might be able to easily make reading non-.NETFramework data work, and writing of .NETFramework counters would work (by writing to shared memory that no-one is reading), but actual .NET performance counter reading will not likely work unless we are able to install netfxperf.dll and perfcounter.dll on the system.

I'd like to hear more from @tommcdon or @noahfalk but think the recommendation for folks investing new code is to use [EventCounters](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md), so perhaps the minimal fix I suggested will help?

**Comment by tommcdon** [comment]
>> I'd like to hear more from @tommcdon or @noahfalk but think the recommendation for folks investing new code is to use EventCounters, so perhaps the minimal fix I suggested will help?

Adding @sywhang

**Comment by sywhang** [comment]
Yes, it is recommended folks writing new counters use the [EventCounters API](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters) instead of the System.Diagnostics.PerformanceCounter because it makes the counters cross-platform by default and makes it easier to integrate with the diagnostics pipeline we built around EventPipe in .NET Core. The runtime and several other stacks are already doing this, so it fits into the rest of the ecosystem better as well.

**Comment by JensNordenbro** [comment]
For me, usage of the other api would be clear If System.Diagnostics.PerforamceCounter was part of https://www.nuget.org/packages/Microsoft.Windows.Compatibility

**Comment by ericstj** [comment]
With https://github.com/dotnet/runtime/pull/45142 it is now possible to use this library on ARM64.  It will function correctly for reading non-.NET perfcounters.  .NET application provided perfcounters will still not work, but it will not fail: the instances will just not appear due to lack of the perfcounter.dll which exposes them to Windows.

**Comment by danmosemsft** [comment]
> With #45142 it is now possible to use this library on ARM64. It will function correctly for reading non-.NET perfcounters. .NET application provided perfcounters will still not work, but it will not fail: the instances will just not appear due to lack of the perfcounter.dll which exposes them to Windows.

@ericstj what about counters exposed by .NET runtime itself - GC and so forth - will those work - my understanding is yes?

**Comment by sywhang** [comment]
The counters exposed by the runtime are all EventCounter implementations and already works on ARM64 with dotnet-counters or EventListeners.

**Comment by danmosemsft** [comment]
Ah, that makes sense.

**Comment by ericstj** [comment]
I opened https://github.com/dotnet/runtime/issues/46589 to track the remaining production of performance counters.  This issue will track the request of reading counters, and porting that back to 5.0.

**Comment by ericstj** [comment]
Fix has been backported to 5.0 and will release in Feb.
