### ISSUE TITLE
Unnessary cast to double in MathF.Round?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/runtime#41140]
Seems it compare an float with an double, and cause unnessary cast. Should it be `0.5f` here?
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/MathF.cs#L376

**Comment by KalleOlaviNiemitalo** [comment]
Would it make sense for the C# compiler or JIT compiler to recognize comparisons of a Single value to a Double constant and silently convert the constant to Single? Even if the conversion is not exact, the compiler could choose a rounding direction that preserves the result of the comparison.

**Comment by danmosemsft** [comment]
@jkotas is @KalleOlaviNiemitalo suggestion above worth an issue against the JIT team?

**Comment by jkotas** [comment]
Feel free to open one.

**Comment by danmosemsft** [comment]
done.
