### ISSUE TITLE
recursive function work wrong behavior not threw exception

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#41153]
https://github.com/dotnet/aspnetcore/issues/25123

I think it is the bug of MonoVM webasembly implemention, so I also open the issues here.
who can help me?

**Comment by SamMonoRT** [comment]
@srxqds - please provide a standalone repro for this - can't proceed without more information from you.

**Comment by SamMonoRT** [comment]
Please re-open issue with a standalone app repro steps.
