### ISSUE TITLE
[Perf -196%] System.Collections.ContainsTrue<Int32> (6)

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#41167]
### Run Information

Architecture | x86
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/e77572ffccc566186f47207f3c5475533c87538e...d2f7c8f52b7b21112a7765d311dc82a413e7116c)

### Regressions in System.Collections.ContainsTrue&lt;Int32&gt;
Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
[Array](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).Array(Size%3A%20512).html) | 41.69 μs | 121.84 μs | 2.92 |  | True
[ImmutableArray](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).ImmutableArray(Size%3A%20512).html) | 43.10 μs | 116.85 μs | 2.71 |  | False
[List](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).List(Size%3A%20512).html) | 40.60 μs | 121.31 μs | 2.99 |  | True
[Queue](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).Queue(Size%3A%20512).html) | 41.12 μs | 121.74 μs | 2.96 |  | True
[ICollection](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).ICollection(Size%3A%20512).html) | 40.48 μs | 120.94 μs | 2.99 |  | True
[Span](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).Span(Size%3A%20512).html) | 38.31 μs | 121.30 μs | 3.17 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32)_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32)_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32)_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32)_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32)_6.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x86_Windows%2010.0.18362/System.Collections.ContainsTrue(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.ContainsTrue<Int32>*';
```
<details>

#### System.Collections.ContainsTrue<Int32>.Array(Size: 512)

```log
[ 37830.974 ;  44220.358) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 44220.358 ;  50609.743) | 
[ 50609.743 ;  56999.127) | 
[ 56999.127 ;  63388.512) | 
[ 63388.512 ;  69777.896) | 
[ 69777.896 ;  76167.281) | 
[ 76167.281 ;  82556.665) | 
[ 82556.665 ;  88946.050) | 
[ 88946.050 ;  95335.434) | 
[ 95335.434 ; 101724.819) | 
[101724.819 ; 108114.203) | 
[108114.203 ; 115700.072) | 
[115700.072 ; 122089.456) | @@@@@@@@@
```
#### System.Collections.ContainsTrue<Int32>.ImmutableArray(Size: 512)

```log
[ 39931.110 ;  45983.331) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 45983.331 ;  52035.551) | 
[ 52035.551 ;  58087.772) | 
[ 58087.772 ;  64139.992) | 
[ 64139.992 ;  70192.213) | 
[ 70192.213 ;  76244.433) | 
[ 76244.433 ;  82296.654) | 
[ 82296.654 ;  88348.874) | 
[ 88348.874 ;  94401.095) | 
[ 94401.095 ; 100453.315) | 
[100453.315 ; 106505.535) | 
[106505.535 ; 114017.398) | 
[114017.398 ; 120282.927) | @@@@@@@@@
```
#### System.Collections.ContainsTrue<Int32>.List(Size: 512)

```log
[ 37081.144 ;  43571.129) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 43571.129 ;  50061.114) | 
[ 50061.114 ;  56551.100) | 
[ 56551.100 ;  63041.085) | 
[ 63041.085 ;  69531.070) | 
[ 69531.070 ;  76021.056) | 
[ 76021.056 ;  82511.041) | 
[ 82511.041 ;  89001.026) | 
[ 89001.026 ;  95491.012) | 
[ 95491.012 ; 101980.997) | 
[101980.997 ; 108470.982) | 
[108470.982 ; 115647.215) | 
[115647.215 ; 122137.200) | @@@@@@@@@
```
#### System.Collections.ContainsTrue<Int32>.Queue(Size: 512)

```log
[ 38137.016 ;  44550.932) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 44550.932 ;  50964.849) | 
[ 50964.849 ;  57378.765) | 
[ 57378.765 ;  63792.681) | 
[ 63792.681 ;  70206.597) | 
[ 70206.597 ;  76620.514) | 
[ 76620.514 ;  83034.430) | 
[ 83034.430 ;  89448.346) | 
[ 89448.346 ;  95862.262) | 
[ 95862.262 ; 102276.179) | 
[102276.179 ; 108690.095) | 
[108690.095 ; 115921.666) | 
[115921.666 ; 122335.582) | @@@@@@@@@
```
#### System.Collections.ContainsTrue<Int32>.ICollection(Size: 512)

```log
[ 37234.692 ;  43644.541) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 43644.541 ;  50054.389) | 
[ 50054.389 ;  56464.238) | 
[ 56464.238 ;  62874.086) | 
[ 62874.086 ;  69283.935) | 
[ 69283.935 ;  75693.783) | 
[ 75693.783 ;  82103.632) | 
[ 82103.632 ;  88513.480) | 
[ 88513.480 ;  94923.329) | 
[ 94923.329 ; 101333.177) | 
[101333.177 ; 107743.026) | 
[107743.026 ; 115217.905) | 
[115217.905 ; 121627.753) | @@@@@@@@@
```
#### System.Collections.ContainsTrue<Int32>.Span(Size: 512)

```log
[ 34357.683 ;  41646.559) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 41646.559 ;  48421.977) | 
[ 48421.977 ;  55197.395) | 
[ 55197.395 ;  61972.813) | 
[ 61972.813 ;  68748.231) | 
[ 68748.231 ;  75523.650) | 
[ 75523.650 ;  82299.068) | 
[ 82299.068 ;  89074.486) | 
[ 89074.486 ;  95849.904) | 
[ 95849.904 ; 102625.322) | 
[102625.322 ; 109400.741) | 
[109400.741 ; 118252.968) | 
[118252.968 ; 125394.354) | @@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment]
> @DrewScoggins one thing worries me here - we had a bunch of scenarios do a clear step function regression of up to 250% in early May - why didn't we know about this until Aug 21st?

I would still like to understand this @DrewScoggins @adamsitnik  .. not interested in blaming anyone 😁 just making sure we understand and can improve our processes if necessary. thoughts?

**Comment by adamsitnik** [comment]
> we had a bunch of scenarios do a clear step function regression of up to 250% in early May - why didn't we know about this until Aug 21st?

The issue was reported by the bot in June: https://github.com/DrewScoggins/performance-2/issues/910#issuecomment-676413559

We meet once a week with Drew, Tanner, Andy an Kunal and go throught the list of all reported  issues. We have most probably not discussed this particular one (human error).

I've confirmed it during my independent verificaiton: https://github.com/DrewScoggins/performance-2/issues/910#issuecomment-677854221 and @DrewScoggins moved it here.

So far this was the only issue like this, all other x86 and x64 issues were already reported (in general the initial results of my verification looks very promissing). 

My plan is to send a report when I am done and also a PR to the bot repo that adds all the actual regressions as unit tests to ensure that we don't loose the precision over time. @danmosemsft does it sound good to you?

**Comment by danmosemsft** [comment]
Sounds good! Again, just interested in ways we can continue to help remove opportunities for error from our processes, as we go along. Thanks!
