### ISSUE TITLE
[wasm-browser] XHarness failure from successful test runs

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#41161]
Some test runs show no failures, WASM exit code 0, but non-zero exit code from XHarness:

```
[14:11:20] dbug: test-browser[0]
      Finished Common.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
      
[14:11:20] dbug: test-browser[0]
      
      
[14:11:20] info: test-browser[0]
      Tests run: 2191, Errors: 0, Failures: 0, Skipped: 2. Time: 105.2617s
      
[14:11:20] dbug: test-browser[0]
      WASM EXIT 0
      
XHarness exit code: 1000
```

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/Common.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/Microsoft.VisualBasic.Core.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Globalization.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Numerics.Vectors.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.RW.FactoryReader.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.RW.SubtreeReader.Tests/console

**Comment by premun** [comment]
FWIW, the exit code [1000 is timeout](https://github.com/dotnet/xharness/blob/1ff8172e92ae0bfb1d998993f34e8685568807c1/src/Microsoft.DotNet.XHarness.Common/CLI/ExitCode.cs#L41).

Probably this is happening?
https://github.com/dotnet/xharness/blob/1ff8172e92ae0bfb1d998993f34e8685568807c1/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs#L114-L119

Maybe it got fixed [here](https://github.com/dotnet/xharness/pull/300) today?

**Comment by directhex** [comment]
Yeah, I'll try bumping xharness & rerunning

**Comment by directhex** [comment]
This failure seems resolved.
