### ISSUE TITLE
Non-Windows sources not avaliable in the source browser (source.dot.net)

### ISSUE THREAD

**Issue by SirIntellegence** [dotnet/runtime#4117]
I was browsing source.dot.net and I was looking for the Unix implementation of something and I wasn't able to find it. I could find Environment.cs, Environment.Windows.cs, and Environment.CoreCLR.cs, but not Environment.Unix.cs (which is located at src/libraries/System.Private.CoreLib/src/System/Environment.Unix.cs). Is there a reason for this and is it possible to set it up so it covers the Unix implementations as well?

**Comment by stephentoub** [comment]
cc: @alexperovich

**Comment by alexperovich** [comment]
Unfortunately the tool that generates that website (https://github.com/KirillOsenkov/SourceBrowser) doesn't support multiple definitions of the same symbol. It can index only one set of sources for each project. To show the unix/mac sources we would need to host an entirely separate website for each variant and index separately.

**Comment by stephentoub** [comment]
> To show the unix/mac sources we would need to host an entirely separate website for each variant and index separately.

Can we just do that? At a minimum one for Windows and one for Linux?

If doing so will take some time, can we switch source.dot.net now to show a Linux build in the meantime?

**Comment by SirIntellegence** [comment]
One could also try to modify the source browser code to be able to handle
it. I would think it would possibly handle multiple definitions the same
way it handles partial classes.

**Comment by ViktorHofer** [comment]
Closing as this was done even though source browser is currently broken for libraries.
