### ISSUE TITLE
Add Environment.Is32BitProcess

### ISSUE THREAD

**Issue by elachlan** [dotnet/runtime#41188]
## Background and Motivation

There are lots of cases where a check like this is done `IntPtr.Size == 4` to check for a 32bit process. It is possible to use `!Environment.Is64BitProcess` but this might not always be the case.

## Proposed API

```diff
namespace Microsoft.Build.Shared
{
+    public static bool Is32BitProcess => IntPtr.Size == 4;
```

## Usage Examples
It would replace code like this:
https://github.com/dotnet/runtime/blob/06731c2dba95f3000e274f5c0a47e24181e88928/src/coreclr/src/System.Private.CoreLib/src/System/GC.cs#L136

## Risks
I believe the change is low risk.

**Comment by elachlan** [comment]
Maybe we can update the xml documentation on the property so that its explicit that true is for a 64bit process and false is for a 32bit process?

**Comment by Clockwork-Muse** [comment]
> I'd like to think you're right but my work requires I deal with cobol and vb6 so I think pessimism may be a good idea here.

I mean, the iSeries platforms have a nominal 128-bit address space, and have for decades.  16-byte pointers, due to "single level store".

**Comment by terrajobst** [comment]
* We already have `Is64BitProcess` and `Is64BitOperatingSystem`. Given that we're extremely unlikely to support either 16bit or 128bit, how would this be different from negating those properties?

```C#
namespace System
{
    public partial class Environment
    {
        public static bool Is32BitProcess  { get; }
        // public static bool Is32BitOperatingSystem { get; }
    }
}
```

**Comment by danmosemsft** [comment]
Fair enough.

**Comment by danmosemsft** [comment]
But I will return here 10 years from now when we work on 128bit support 😄
