### ISSUE TITLE
Unknown Bitmap/Image compression on ubuntu (System.Drawing.Common v.3.1.1)

### ISSUE THREAD

**Issue by msx752** [dotnet/runtime#4118]
i have an issue on **.net core 3.1.1**
If i host my web application on windows 10 `there is no any issue after image processing and save/load`, but `when i deploy my same web application with the docker image to ubuntu(v18.04)` if i call the api to get processed image `the Content-Length (Size) obviously different than windows 10 server.` and **there is huge distortion on images especially Transparent Images**

**For Example**
 `windows 10 returns 46KB` (width:299, height:299) Content-Length but same application different OS `returns 26.94KB` for same request

**what i am using**
- png files with transparency
- my docker configurations
 ```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*
WORKDIR /app
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic AS build
....
```
- classic save to Stream method
```
mybitmap.Save(mystream, ImageFormat.Png);
```
- custom quality settings for Graphics
```
            gr.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality;
            gr.CompositingQuality = System.Drawing.Drawing2D.CompositingQuality.HighQuality;
            gr.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.High;
```
- .net core mvc **FileStreamResult** (final method to retriew the image)
```
                var stream =.........
                return File(stream, "image/png"); //<==returns FileStreamResult
```

**What i tried**
- i used docker **buster-slim** image
- custom bitmap save method
```
        public static void Save(this System.Drawing.Image image, string filePath, string mimeType = "image/png")
        {
            #region save bitmap

            System.Drawing.Imaging.ImageCodecInfo codec = System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders().First(f => f.MimeType == mimeType);
            System.Drawing.Imaging.EncoderParameters eParams = new System.Drawing.Imaging.EncoderParameters(1);
            eParams.Param[0] = new System.Drawing.Imaging.EncoderParameter(System.Drawing.Imaging.Encoder.Quality, 100L);
            image.Save(filePath, codec, eParams);

            #endregion save bitmap
        }
```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
