### ISSUE TITLE
Array.Sort ( .NET 5.0 Preview 7 ) generates wrong result for a sample data set.

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/runtime#41235]
**Array.Sort(sample)** ( .NET 5.0 Preview 7 ) generates wrong result for a sample data set.

The sample data set is a string[] with the _Namespaces_ for each Type in .NET.
This is 8500+ items, including a lot of nulls and repetitions.

I did a short test by modification of the current **Array.Sort** code in the **.NET Core Source Browser.**
I removed the **PartitionSort** part and left only the **HeapSort** for the entire sort.
With the **HeapSort** the result is correct.

Using Visual Studio 2019 version 16.8 with .NET 5.0 Preview 7.
I can provide the sample data set if that helps.

**Comment by jkotas** [comment]
Keep open to track release/5.0 backport

**Comment by jeffhandley** [comment]
This was backported to `release/5.0` with #41239.
