### ISSUE TITLE
Console application has unexpected dependency on Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#41231]
The steps I took:

> $ mkdir Console.asp
> $ cd Console.asp
> $ dotnet new solution
> The template "Solution File" was created successfully.
> $ dotnet new Console -n Hello
> The template "Console Application" was created successfully.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on Hello/Hello.csproj...
>   Determining projects to restore...
>   Restored /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/Hello.csproj (in 93 ms).
> Restore succeeded.
> 
> $ dotnet sln Console.asp.sln add Hello/Hello.csproj
> Project `Hello/Hello.csproj` added to the solution.
> $ dotnet build
> Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
>   Hello -> /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/bin/Debug/net5.0/Hello.dll
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:03.89
> $ dotnet run -p Hello
> Hello World!

Added ```<RuntimeIdentifier>osx-x64</RuntimeIdentifier>``` to the Hello.csproj file

> $ dotnet build
> Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
> /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/Hello.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.osx-x64 with version (= 5.0.0-preview.8.20361.2) [/Users/mj/Documents/develop/runtime.issues/Console.asp/Console.asp.sln]
> /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/Hello.csproj : error NU1102:   - Found 26 version(s) in nuget.org [ Nearest version: 5.0.0-preview.7.20364.11 ] [/Users/mj/Documents/develop/runtime.issues/Console.asp/Console.asp.sln]
> /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/Hello.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.osx-x64 with version (= 5.0.0-preview.8.20360.11) [/Users/mj/Documents/develop/runtime.issues/Console.asp/Console.asp.sln]
> /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/Hello.csproj : error NU1102:   - Found 28 version(s) in nuget.org [ Nearest version: 5.0.0-preview.7.20365.19 ] [/Users/mj/Documents/develop/runtime.issues/Console.asp/Console.asp.sln]
>   Failed to restore /Users/mj/Documents/develop/runtime.issues/Console.asp/Hello/Hello.csproj (in 1.03 sec).
> 
> Build FAILED.

My ```dotnet --info``` output:

> .NET SDK (reflecting any global.json):
>  Version:   5.0.100-preview.8.20362.3
>  Commit:    a5c8f426c2
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /Users/mj/Documents/develop/runtime/.dotnet/sdk/5.0.100-preview.8.20362.3/
> 
> Host (useful for support):
>   Version: 5.0.0-preview.8.20361.2
>   Commit:  f37dd6fc85
> 
> .NET SDKs installed:
>   5.0.100-preview.8.20362.3 [/Users/mj/Documents/develop/runtime/.dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.0-preview.8.20360.11 [/Users/mj/Documents/develop/runtime/.dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.0-preview.8.20361.2 [/Users/mj/Documents/develop/runtime/.dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 

Why does a Console application have a dependency on Microsoft.AspNetCore.App?

**Comment by danmosemsft** [comment]
@ericstj

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/installer/issues/1958
