### ISSUE TITLE
Clean-up VN for promoted fields assigned using the whole parent.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#41242]
This is a follow-up for https://github.com/dotnet/runtime/pull/37745#discussion_r448627965 and https://github.com/dotnet/runtime/pull/41197#pullrequestreview-473022892. 

- [ ] Review all the places where we use `lvaInSsa`, find where we need to check for `CanBeReplacedWithItsField`;

- [ ] Use `optIsSsaLocal` instead of `CanBeReplacedWithItsField` in all phases, maybe move it to `LclVarDsc` or just rename;

- [ ] Rename `optIsSsaLocal` to `optGetSsaLocal` (https://github.com/dotnet/runtime/pull/41243#discussion_r476032547)

- [ ] Design how to extend it for multiregs and multifields `LclVars`.

category:implementation
theme:value-numbering
skill-level:expert
cost:medium

**Comment by sandreenko** [comment]
It is a  potential CQ improvement with medium required changes, out of scope for 6.0.

**Comment by briansull** [comment]
This issue will be fixed in 6.0 by PR ##57282
