### ISSUE TITLE
Sources for System.Runtime.CompilerServices.Unsafe 4.0.0

### ISSUE THREAD

**Issue by rahulmohang** [dotnet/runtime#41244]
Hello team, 

I was looking for source code for System.Runtime.CompilerServices.Unsafe 4.0.0. Can you please direct me to where I can find it? 

Regards,
Rahul

**Comment by benaadams** [comment]
It's the `il.proj` in https://github.com/dotnet/runtime/tree/master/src/libraries/System.Runtime.CompilerServices.Unsafe/src 

Specifically the `System.Runtime.CompilerServices.Unsafe.il` file (is written in cil rather than C# for things that can be expressed in `il` but not `C#`)

**Comment by jkotas** [comment]
If you are looking for assembly version 4.0.0 specifically, it is in the .NET Core 1.0 release branch at https://github.com/dotnet/corefx/tree/release/1.0.0/src/System.Runtime.CompilerServices.Unsafe/src

**Comment by rahulmohang** [comment]
Thank you.
