### ISSUE TITLE
`Avx2` masked gather intrinsics have suboptimal codegen

### ISSUE THREAD

**Issue by sunkin351** [dotnet/runtime#41245]
The hardware intrinsics `Avx2.GatherMaskVector128()` and `Avx2.GatherMaskVector256()` have suboptimal codegen regarding the mask parameter. It needlessly moves the mask to another register before using it.

```cs
var mask = Vector256.Create(uint.MaxValue, uint.MaxValue, uint.MaxValue, uint.MaxValue, uint.MaxValue, uint.MaxValue, uint.MaxValue, 0);

var idx = Vector256.Create(hashIdx);
idx = Avx2.Add(idx, Vector256.Create(0, 4, 8, 12, 16, 20, 24, 0));

var tmp = Avx2.GatherMaskVector256(mask, (uint*)state, idx, mask, 4);

Avx2.MaskStore(hash, mask, tmp);
```
results in an unnecessary `vmovaps`
```
 vmovupd     ymm0,ymmword ptr [00007FFF0D387280h]  
 vmovd       xmm1,r8d  
 vpbroadcastd ymm1,xmm1  
 vpaddd      ymm1,ymm1,ymmword ptr [00007FFF0D3872C0h]  
 vmovaps     ymm2,ymm0  <----- this one here
 vmovaps     ymm3,ymm0  
 vpgatherdd  ymm3,dword ptr [rcx+ymm1*4],ymm2  
 vpmaskmovd  ymmword ptr [rdx],ymm0,ymm3 
```
Its as if it expects the mask register to be trashed by the gather instruction. (Observation made by Tanner Gooding. ^_^)

### Configuration

Running on .NET 5 Preview 7, Windows 10 x64

**Comment by BruceForstall** [comment]
@tannergooding @CarolEidt @echesakovMSFT Does this still happen in Preview 8 and/or RC1?

Since it's CQ, I moved it to Milestone 6.0.0.

**Comment by tannergooding** [comment]
> Does this still happen in Preview 8 and/or RC1?

Will check, I need to rebuild dotnet/runtime anyways now that I'm back from vacation 😄

**Comment by tannergooding** [comment]
This still repros and looks to be because we always mark op2/3/4 as delay free: <https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/lsraxarch.cpp#L2512-L2516>

Looks like this is because `vpgatherdd` does indeed trash the register. The architecture manual additionaly annotates:
> If any pair of the index, mask, or destination registers are the same, this instruction results a UD fault.
