### ISSUE TITLE
Events in interfaces contain nullable annotations

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#41256]
### Description

I might be fundamentally wrong and am going to learn something…

Why do `event` declarations in interfaces carry a nullable annotation? For example
```C#
public interface INotifyPropertyChanged
{
    event PropertyChangedEventHandler? PropertyChanged;
}
```

My understanding is that an interface only declares that two methods exist on an implementing type, one for `+=` and one for `-=`. From outside the type, both these methods are safe to call even when for example a backing multicast delegate is currently `null`. The only time the nullability is relevant is when the type implementing the interface uses a multicast delegate for the implementation and tries to invoke the event handlers.
In short, the nullability of the delegate type is an implementation detail.

With the nullable annotation on the interface, C# will complain about perfectly valid implementations of the interface when using "do nothing":
```C#
public event PropertyChangedEventHandler PropertyChanged { add { } remove { } }
```

On the other hand, when the interface does not contain the nullable annotation, the C# compiler will still warn when implementing the interface is done using a multicast delegate.

I had created https://github.com/dotnet/roslyn/issues/40292. It's about pulling up an event member to an interface and my expectation that the nullable annotation should not be part of that gesture. It was accepted as being a bug, so I'm reasonably confident that there is a discrepancy here in how nullability should be handled in interfaces.

### Configuration

For me, this became overly visible with the .NET 5 annotations for System.ComponentModel.

### Regression?

Yes, kind of. I'm now getting nullability warnings for code that obviously has no nullability issues.

**Comment by stephentoub** [comment]
> I'm now getting nullability warnings for code that obviously has no nullability issues.

What about the code that invokes the event?

**Comment by stephentoub** [comment]
> With the nullable annotation on the interface, C# will complain about perfectly valid implementations of the interface when using "do nothing"

Adding and removing null delegates is expected to be valid.

**Comment by Tragetaschen** [comment]
```C#
#nullable enable
using System;
public interface ITest
{
    event Action E;
}

public class Test : ITest
{
    public event Action? E;
}

public class C
{
    public void M1(ITest test) => test.E += null; // No warning
    public void M2(ITest test) => test.E -= null; // No warning
}
```
Hmm…

**Comment by stephentoub** [comment]
That looks like a bug:
https://github.com/dotnet/roslyn/issues/41961
cc: @jcouv, @cston

**Comment by joperezr** [comment]
Given the original question has been answered and the issue here seems to be a bug on the compiler (which is already logged) I'll go ahead and close this one for now as any fix wouldn't go into runtime repo anyway and instead in roslyn. @Tragetaschen feel free to reopen if you still want to track something else with this.
