### ISSUE TITLE
host-error-codes.md linux values

### ISSUE THREAD

**Issue by eli-fin** [dotnet/runtime#41251]
[host-error-codes.md](https://github.com/dotnet/runtime/blob/master/docs/design/features/host-error-codes.md) documents host exit codes.
However, they're listed as 32bit hex values. But under Linux, you (normally) only get an 8bit value.

For the purpose of clearer documentation and making google searches like 'dotnet exit code 150' come up with this page, I think it would be a good idea to add the 8bit value (and maybe the 32bit decimal signed value you would see in the Windows CMD too).

I'd be happy to create the PR, just checking first.

**Comment by joperezr** [comment]
Thanks for logging this @eli-fin I think it should be fine to add the 8bit value right next to the hex representation on the parenthesis, so it would be great to get a PR if you are interested 😄

**Comment by eli-fin** [comment]
@eli-fin I would also add the 32 bit signed values , which are what you see if you use echo %ERRORLEVEL% on Windows. When I googled those values, I saw they are mentioned and it would probably be beneficial to include them here too.

Was wondering what would be the most readable way:
1. FrameworkMissingFailure (`0x80008096`, `-2147450730`, `150`) - It was not possible to...
   (with a note at the top explaining the values)
2. Change the whole thing into a table

| err name | hex val | signed val | 8bit val | info |
| ---------- | -------- | ----------- | -------- | ---- |
| FrameworkMissingFailure | `0x80008096` | `-2147450730` | `150` | It was not possible to... |

Again, with a note explaining the values.

@joperezr WDYT?

**Comment by joperezr** [comment]
Table sounds great to me 😄

**Comment by eli-fin** [comment]
@joperezr #41566
