### ISSUE TITLE
Add  XmlSchema.ReadAsync

### ISSUE THREAD

**Issue by kronic** [dotnet/runtime#41252]
## Background and Motivation
Async IO
## Proposed API

```csharp
namespace System.Xml.Schema
{
    public class XmlSchema : XmlSchemaObject
    {
         public static Task<XmlSchema> ReadAsync(XmlReader reader, ValidationEventHandler validationEventHandler, CancellationToken cancellationToken)
    }
}
```

## Usage Examples
No

## Alternative Designs
No
## Risks
No

**Comment by buyaa-n** [comment]
@kronic it would be better for prioritizing the issue if the `Background and Motivation` section is filled
