### ISSUE TITLE
Client certificate not included by HttpClientHandler in .net core

### ISSUE THREAD

**Issue by rsegecin** [dotnet/runtime#41260]
I'm having difficulties sending a certificate using HttpClientHandler because the certificate simply won't appear on Server's request. The certificate has the proper EKU for server and client authentication, and Key Usage of "Digital Signature". @davidsh regarded the issue [26531](https://github.com/dotnet/runtime/issues/26531) for the lack of logging that HttpClient had but running my project in Visual Studio (with logs set to Trace and using dotnet 3.1.401) no output error came out. I'm not very familiar at all with logman but I ran it when the issue supposed to happen as I executed my code and nothing from the log stood out indicating what the problem could be. Running out of options to test the code I attempted to add a certificate without the private key on the client request to see if the `httpClientHandler.ClientCertificates.Add ...` would throw any error saying something like "You need a certificate with the private key to sign your request", shouldn't it say anything?

On client:

	services.AddHttpClient<ILetterManClient, LetterManClient.LetterManClient>()
		.ConfigureHttpClient(client =>
		{
			client.BaseAddress = new Uri(configuration.GetValue<string>("Microservices:LetterManAPI"));
		})
		.ConfigurePrimaryHttpMessageHandler(() =>
		{
			HttpClientHandler httpClientHandler = new HttpClientHandler();

			httpClientHandler.ServerCertificateCustomValidationCallback = ValidateServiceCertficate;
			httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;

			clientCertificate = new X509Certificate2("client_cert.pfx", "developer");

			httpClientHandler.ClientCertificates.Add(clientCertificate);

			return httpClientHandler;
		});

On server:

    public class ValidateClientCertificates : TypeFilterAttribute
    {
        public ValidateClientCertificates() : base(typeof(ValidateClientCertificatesImpl))
        {

        }

        private class ValidateClientCertificatesImpl : IAsyncAuthorizationFilter
        {
            X509Certificate2 clientCertificate;
            public ValidateClientCertificatesImpl(IConfiguration configuration, IWebHostEnvironment webHostEnvironment)
            {
                clientCertificate = new X509Certificate2("client_cert.crt");
            }

            public async Task OnAuthorizationAsync(AuthorizationFilterContext context)
            {
                var certificate = await context.HttpContext.Connection.GetClientCertificateAsync();

                if ((certificate == null) || (!certificate.Thumbprint.Equals(clientCertificate.Thumbprint)))
                {
                    context.Result = new UnauthorizedObjectResult("");
                    return;
                }
            }
        }
    }

Side note:
I've been also trying to debug my project using code compiled from corefx repo to see what's going but Visual Studio insists reference the code from local installed sdk instead of the project on corefx that it's referencing it to but this is another issue. 

Any help will be very welcomed.

**Comment by rsegecin** [comment]
I've created [this project](https://github.com/rsegecin/mTLSdotnet) that simulates the issue. It creates the certificates and it has two projects with one service and another client implemented.

**Comment by wfurt** [comment]
Client will not send certificate unless asked for. I did not see anything in you app by doing quick lookup. 
Look at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1 

and yes, client needs certificate with key. Otherwise it won't be able to prove it self. 

cc: @Tratcher in case he has more hints for server (or I missed something)

BTW what version of .NET and OS do you use? Filling up the template helps with proper triage.

**Comment by Tratcher** [comment]
Right, you have to configure the server to require a client cert:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#configure-your-server-to-require-certificates

**Comment by rsegecin** [comment]
You guys are awesome. I'm running dotnet 3.1 on Windows, I'll add this information upfront next time and I'll be updating mTLSDemo soon.  Thank you very much.
