### ISSUE TITLE
Net5.0-Preview 7 Single-File IncludeNativeLibrariesInSingleFile excludes txt files

### ISSUE THREAD

**Issue by scamille** [dotnet/runtime#41266]
#38077 # Description

I have an application which uses an old C DLL, which in turn tries to read some data from a .txt file located alongside it.

Both files are configured as
```
    <Content Include="myDLL.dll" Link="myDLL.dll">
      <PackagePath>runtimes/win-x64/native</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Pack>true</Pack>
    </Content>
    <Content Include="myDLLExtraData.txt" Link="myDLLExtraData.txt">
      <PackagePath>runtimes/win-x64/native</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Pack>true</Pack>
    </Content>
```
in library project, which I then include in a applicaton project as a nuget package.

With a normal .NET 5 build, both files get copied to runtimes/win-x64/native or directly to / when publishing self-contained and everything works.

With both ```<PublishSingleFile>True</PublishSingleFile>``` and ```<IncludeNativeLibrariesInSingleFile>True</IncludeNativeLibrariesInSingleFile>```, only the file myDll.dll gets embedded into the published SingleFile executable, while the myDLLExtraData.txt remains outside.

The application still runs fine and access to myDll.dll work fine, but the connection to myDLLExtraData.txt is broken. I would assume since the two files are no longer located in the same folder, or more generally the running SIngleFile process does not have any access to the non-embedded text file.

The main question/problem is:
* Is it inteded that IncludeNativeLibrariesInSingleFile does not include all files in the runtimes folders, and only embeds selected files (eg. only the .dll, not the .txt file)
* If that is indeed the intention, is there any option to still get all files from runtimes/ embedded into a PublishSingleFile executable?

### Configuration

Windows 10 1909 x64, Visual Studio 2019 16.7.2, Net5.0 preview7

### Regression?

netcoreapp3.1 single file app includes all native runtimes/ files and is thus working fine for my use case.

**Comment by swaroop-sridhar** [comment]
@scamille `IncludeNativeLibrariesInSingleFile` only includes native DLLs of the target platform within the single file bundle.
To include all published files, you need `Include AllContentInSingleFile`. Please see https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md#optional-settings

**Comment by scamille** [comment]
Thanks a lot.
