### ISSUE TITLE
Error with using List<string> within Razor components in Blazor.

### ISSUE THREAD

**Issue by Zabato7** [dotnet/runtime#41276]
Two errors were detected with the use of lists in Razor components in Blazor .
1. When inserting empty data like 
`List<string> list = new List<string>();
list.Add ("");`, 
or empty spaces like 
`List<string> list = new List<string>();
list.Add (" ") `
to the list. These are being stored as null data.
2. Debugging mode: When you insert the character  \
`List<string> list = new List<string>();
list.Add ("\\")` 
when inspecting the items in the list, debugging stops and the browser closes.

**Comment by mkArtakMSFT** [comment]
@lewing  FYI

**Comment by mkArtakMSFT** [comment]
@lewing we think the above is about Debugger behavior - that they simply show up as `null`-s.

**Comment by radical** [comment]
I tried:
```
            var l = new List<string> ();
            l.Add("");
            l.Add(" ");
            l.Add("\\");
```

and inspecting `l`, shows:
![Screen Shot 2020-08-26 at 4 45 30 PM](https://user-images.githubusercontent.com/1472/91355090-af0d3380-e7bb-11ea-82ee-a8c5a5795aa6.png)

The 3rd one seems to be fine though? @Zabato7 do you see something like this?

**Comment by lewing** [comment]
@Zabato7 what version of blazor are you using?

**Comment by Zabato7** [comment]
> Lo intenté:
> 
> ```
>             var l = new List<string> ();
>             l.Add("");
>             l.Add(" ");
>             l.Add("\\");
> ```
> 
> e inspeccionando `l`, muestra:
> ![Captura de pantalla 2020-08-26 a las 4 45 30 PM](https://user-images.githubusercontent.com/1472/91355090-af0d3380-e7bb-11ea-82ee-a8c5a5795aa6.png)
> 
> ¿Sin embargo, el tercero parece estar bien? @ Zabato7 , ¿ves algo como esto?



> Lo intenté:
> 
> ```
>             var l = new List<string> ();
>             l.Add("");
>             l.Add(" ");
>             l.Add("\\");
> ```
> 
> e inspeccionando `l`, muestra:
> ![Captura de pantalla 2020-08-26 a las 4 45 30 PM](https://user-images.githubusercontent.com/1472/91355090-af0d3380-e7bb-11ea-82ee-a8c5a5795aa6.png)
> 
> ¿Sin embargo, el tercero parece estar bien? @ Zabato7 , ¿ves algo como esto?

I tested it with lists not with arrays

**Comment by Zabato7** [comment]
> No pude encontrar la mejor etiqueta de área para agregar a este problema. Si tiene permisos de escritura, ayúdeme a aprender agregando exactamente una [etiqueta de área](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md) .
