### ISSUE TITLE
System.Console.WindowWidth not changing on Linux unless System.Console.CursorTop is accessed

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/runtime#41274]
### Description

When resizing the terminal/ console on Linux (Ubuntu), `System.Console.WindowWidth` (and similar properties) do not change their value unless the properties `System.CursorTop` or `System.CursorLeft` are observed/ accessed.

Minimal repro:

```csharp
using System;
using System.Threading.Tasks;

namespace ConsoleTest
{
	class Program
	{
		static async Task Main(string[] args)
		{
			while(true)
			{
				Console.Clear();

				//Uncomment the following line to make it work
				//int AA = Console.CursorTop;
				Console.WriteLine($"Width:  {Console.WindowWidth}");
				Console.WriteLine($"Height: {Console.WindowHeight}");

				await Task.Delay(1000);
			}
		}
	}
}
```

With `int AA = Console.CursorTop;` commented, the printed values never change when resizing the window. With the lines uncommented, the values change as expected.

### Configuration

.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/zeroskyx/Apps/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/home/zeroskyx/Apps/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/home/zeroskyx/Apps/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/home/zeroskyx/Apps/dotnet/shared/Microsoft.NETCore.App]

### Regression?

Unknown; untested in previous versions of .NETCore.

**Comment by stephentoub** [comment]
cc: @tmds

**Comment by tmds** [comment]
@zeroskyx some APIs of Console cause the signal handling to be setup to detect window size changes. This is missing for `Window{Width,Height}` (fixed by https://github.com/dotnet/runtime/pull/41317). Using one of those other APIs (like `Console.CursorTop`) sets up the handlers, and makes things work.

**Comment by zeroskyx** [comment]
Hi Tom,

Thanks for the explanation and the rapid fix. 

Best regards
-Simon

**Comment by tmds** [comment]
@zeroskyx you may leave issues open, they are normally closed when the PR that fixes them gets merged.
