### ISSUE TITLE
Question: ActivitySource behavior with multiple subscribed ActivityListeners

### ISSUE THREAD

**Issue by alanwest** [dotnet/runtime#41306]
### Description

When an `Activity` is started with the new `ActivitySource` API if _any_ subscribed `ActivityListener` responds with anything higher than `ActivityDataRequest.None` then _all_ subscribed `ActivityListener.ActivityStarted/Stopped` events are fired.

For example:

```csharp
public static void Main(string[] args)
        {
            var listenerA = new ActivityListener()
            {
                ActivityStarted = (a) => System.Console.WriteLine("listenerA.ActivityStarted"),
                ActivityStopped = (a) => System.Console.WriteLine("listenerA.ActivityStopped"),
                ShouldListenTo = _ => true,
                GetRequestedDataUsingParentId = (ref ActivityCreationOptions<string> options) => ActivityDataRequest.None,
                GetRequestedDataUsingContext = (ref ActivityCreationOptions<ActivityContext> options) => ActivityDataRequest.None,
            };

            var listenerB = new ActivityListener()
            {
                ActivityStarted = (a) => System.Console.WriteLine("listenerB.ActivityStarted"),
                ActivityStopped = (a) => System.Console.WriteLine("listenerB.ActivityStopped"),
                ShouldListenTo = _ => true,
                GetRequestedDataUsingParentId = (ref ActivityCreationOptions<string> options) => ActivityDataRequest.AllData,
                GetRequestedDataUsingContext = (ref ActivityCreationOptions<ActivityContext> options) => ActivityDataRequest.AllData,
            };

            ActivitySource.AddActivityListener(listenerA);
            ActivitySource.AddActivityListener(listenerB);

            var activitySource = new ActivitySource("MyActivitySource");

            var activity = activitySource.StartActivity("MyActivity");
            activity?.Stop();
        }
```

This code produces this output:

```shell
listenerA.ActivityStarted
listenerB.ActivityStarted
listenerA.ActivityStopped
listenerB.ActivityStopped
```

Even though `listenerA` responds `ActivityDataRequest.None` it's `ActivityStarted/Stopped` events are fired. Is this the correct behavior? It does not seem intuitive.

@cijothomas

**Comment by tarekgh** [comment]
This is by design, the responding value of `ActivityDataRequest` is not intended for getting the notification or not. it is intended to know if need to create the Activity object or not. If any listener responded with any value different than `ActivityDataRequest.None` then we'll create the `Activity` object and all listeners will get the notifications. The listener is free to set `ActivityStarted/ActivityStopped` to null if needed to stop getting any notifications.

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by cijothomas** [comment]
related: https://github.com/dotnet/runtime/issues/31862#issuecomment-676850526
