### ISSUE TITLE
Handling of collectible types in tailcall dispatcher

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#41314]
The tailcall dispatcher operates with raw function pointers that are not tracked by the GC. In theory, it is possible to get into a situation when there is nothing keeping the tailcall target alive and the target gets unloaded by accident.

**Comment by RamType-0** [comment]
Why is this not marked as a bug?

**Comment by jakobbotsch** [comment]
Do I understand correctly that this can only be an issue for static functions (otherwise 'this' will keep it live)? What is the appropriate way to keep a static function live after taking its address?

**Comment by jkotas** [comment]
> otherwise 'this' will keep it live

This is not strictly guaranteed. `this` can be null.

> What is the appropriate way to keep a static function live after taking its address?

The stackwalker needs to convert the entrypoint back to `MethodDesc*` and report loader allocator associated with the `MethodDesc*`.

**Comment by jakobbotsch** [comment]
> The stackwalker needs to convert the entrypoint back to MethodDesc* and report loader allocator associated with the MethodDesc*.

What function can be used to convert the function pointer to `MethodDesc*`?

I am wondering if we should report loader allocators for both `IL_STUB_CallTailCallTarget` and the target, since direct calls are sometimes done through `calli` in the stub when generics are involved. I suppose reporting both can't hurt?

**Comment by jkotas** [comment]
> What function can be used to convert the function pointer to `MethodDesc*`?

`Entry2MethodDesc`

> I suppose reporting both can't hurt?

Agree.
