### ISSUE TITLE
Consider adding more Half methods to BitConverter

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#41318]
## Background and Motivation

#38288 proposed some methods for `Half` into `BitConverter` class. The class has more methods for other types, so it may be more consistent to add them for `Half`.

## Proposed API

```diff
namespace System
{
    public class BitConverter
    {
+        public static Half ToHalf(byte[] value, int startIndex);
+        public static Half ToHalf(ReadOnlySpan<byte> value);
+        public static byte[] GetBytes(Half value);
+        public static bool TryWriteBytes(Span<byte> destination, Half value);
    }
}
```

## Alternative Designs

What level of feature parity do we need to achieve for `Half`?

It will be good to have concept-based generic implementations, instead of writing type*function matrix manually, but we don't have the ability right now.

Do we want to add valueless methods **only for parity**? The `BitConverter` overloads can be easily covered by `Unsafe`, `MemoryMarshal` and `BinaryPrimitives`.

But, getting parity *class by class* looks reasonable.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System
{
    public class BitConverter
    {
        public static Half ToHalf(byte[] value, int startIndex);
        public static Half ToHalf(ReadOnlySpan<byte> value);
        public static byte[] GetBytes(Half value);
        public static bool TryWriteBytes(Span<byte> destination, Half value);
    }
}
```
