### ISSUE TITLE
Why are some x86 intrinsic vector functions missing?

### ISSUE THREAD

**Issue by RamType-0** [dotnet/runtime#41332]
Where are MOVS(L/H)DUP,and string comparison intrinsic functions?
Why are they missing?

**Comment by huoyaoyuan** [comment]
I've heard that those instructions are unfriendly for modern CPU architectures (comparing to the time they were introduced), and will have strong negative performance impact.

For their functionality, they should be able to be directly represented by `Span` methods. Let BCL to choose the most optimal way to do these.

**Comment by benaadams** [comment]
`Avx.DuplicateEvenIndexed`, `Avx.DuplicateEvenIndexed`, `Avx.DuplicateOddIndexed` etc?

https://github.com/dotnet/runtime/blob/ff4f37fa33160095468275df25ae434d1df46847/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Avx.cs#L380-L395

**Comment by benaadams** [comment]
`Sse42` only has Crc, no string functions though

**Comment by RamType-0** [comment]
I found SSE3 MOVS(L/H)DUP, but I could not found AVX one,thanks!
But why are their naming is inconsistent?

**Comment by tannergooding** [comment]
@RamType-0, do you mean why do the .NET names differ from the C/C++ names?

e.g `Sse3.MoveAndDuplicate` vs `_mm_movedup_pd`?

**Comment by RamType-0** [comment]
> @RamType-0, do you mean why do the .NET names differ from the C/C++ names?
> 
> e.g `Sse3.MoveAndDuplicate` vs `_mm_movedup_pd`?

No.
I mean `Sse3.MoveLowAndDuplicate` vs `Avx.DuplicateEvenIndexed`.

**Comment by tannergooding** [comment]
Likely just an oversight here.

`DuplicateEvenIndexed` and `DuplicateOddIndexed` are the logically better names, while `MoveLowAndDuplicate` is the description used for the `double` variant, as it only has two indices for the 128-bit version.

**Comment by tannergooding** [comment]
Going to close this as resolved. The methods exist, they just have different names.

**Comment by RamType-0** [comment]
> Going to close this as resolved. The methods exist, they just have different names.

Where is string comparison functions?
And also,will we have any changes about inconsistent naming?

**Comment by tannergooding** [comment]
> Where is string comparison functions?

They are tracked by https://github.com/dotnet/runtime/issues/957 and require someone to propose some better names and API surface to ensure the functionality is exposed.

> And also,will we have any changes about inconsistent naming?

At this point, I'd probably say not likely. That would just lead to additional surface area that does the same thing and adds a bit more inconsistency.
If you feel strongly, you should feel free to open an API proposal suggesting we expose them and I can take it to API review: https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md
