### ISSUE TITLE
QUIC/HTTP3 request stream read failures

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#41337]
When reading from interop test servers, some request streams will appear to shutdown prior to receiving any data.

Ongoing investigation notes:
- When a connection is aborted, either by us or by peer, requests are observing this as a graceful (yet incomplete) end of stream rather than with an exception during `QuicStream.ReadAsync()` as expected. This is the mysterious "shutdown" observed in this issue. This specific point may require a larger fix and I can live without fixing for 5.0, so long as the root causes (below) of the aborts are fixed.
- SETTINGS frame was being sent incorrectly; was causing some servers to abort connection.
- Control streams appear to be receiving unusually large frames, either a SETTING frame or an unknown frame. May be a parsing issue, or may be server behavior to adjust to.

**Comment by scalablecory** [comment]
This was resolved by #42315

**Comment by karelz** [comment]
Fixed in 6.0/master (PR #42315) and in 5.0 (PR #42366)
