### ISSUE TITLE
Error: To run this application, you must install .NET Core

### ISSUE THREAD

**Issue by provegard** [dotnet/runtime#41351]
Hi!

I have a winexe application which is based on [CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample/). The project file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>BrowserWrapper</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.WinForms" Version="83.4.20" />
  </ItemGroup>

  <ItemGroup>
    <!-- TODO: These updates are currently required because CefSharp.WinForms specifies
         <Private>false</Private>, which means these libraries will not be specified in
         the .deps.json file, and so the CoreCLR wouldn't load these. -->
    <Reference Update="CefSharp">
      <Private>true</Private>
    </Reference>
    <Reference Update="CefSharp.Core">
      <Private>true</Private>
    </Reference>
    <Reference Update="CefSharp.WinForms">
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <!-- Include CefSharp.BrowserSubprocess.Core so we can selfhost the BrowserSubProcess using our exe -->
  <Choose>
    <When Condition="'$(PlatformTarget)' == 'x64'">
      <ItemGroup>
        <Reference Include="CefSharp.BrowserSubprocess.Core">
          <HintPath>$(CefSharpBrowserProcessCore64)</HintPath>
          <Private>true</Private>
        </Reference>
      </ItemGroup>
    </When>
    <!-- x86, Win32 and AnyCPU -->
    <Otherwise>
      <ItemGroup>
        <Reference Include="CefSharp.BrowserSubprocess.Core">
          <HintPath>$(CefSharpBrowserProcessCore32)</HintPath>
          <Private>true</Private>
        </Reference>
      </ItemGroup>
    </Otherwise>
  </Choose>
</Project>
```

When I target netcoreapp3.1 and run the resulting exe, I get the following dialog:

![image](https://user-images.githubusercontent.com/795010/90525548-af7c4d80-e16f-11ea-9964-3c7960f34be4.png)

I have followed the link to download the lastest 3.1 packages (in particular I though Desktop Runtime 3.1.7 might help, but it didn't).

These are my SDKs and runtimes:

```
❯ dotnet --list-sdks
2.1.2 [C:\Program Files\dotnet\sdk]
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.401 [C:\Program Files\dotnet\sdk]

❯ dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

If I change to `netcoreapp3.0`, I don't get the dialog.

Am I missing something obvious?

**Comment by vitek-karas** [comment]
> If I change to netcoreapp3.0, I don't get the dialog.

The dialog was added in .NET Core 3.1 - since without it the app just doesn't do anything visible.

As for the failure:
* Is this x86 versus x64 problem? Per your project file you're building the app for both x86 and x64. Running just `dotnet --info` from command line will get you the x64 version. So it's possible that you have the x64 runtime installed, but you're trying to run the x86 version of the app - which will require the x86 version of the runtime (should live in `C:\Program Files (x86)\dotnet`).
* If this is not a 100% repro, but rather only happens "rarely" and you're publishing the app with `/p:PublishSingleFile=true` this may be known issue with some OS tool deleting files from temp - if the app is built with 3.1.400 SDK this problem should be almost always solved though.

**Comment by provegard** [comment]
@vitek-karas Thank you for your response! I'm building with:

    dotnet build /p:Platform=x86

or `x64`. After that, I'm just running the exe (this is a sample application, so there's no need to publish anything).

What's strange is that I cannot reproduce the problem now. I can run the application under 3.1 without the dialog showing. My SDK and runtime lists are the same as they were when I created the issue.

Since I cannot reproduce, I'm closing the issue.

**Comment by intrepidis** [comment]
Could it be that the '.json' manifest files were missing?

**Comment by provegard** [comment]
Which ones? I didn't add any, as far as I know.

**Comment by intrepidis** [comment]
> Which ones? I didn't add any, as far as I know.

Hi, actually I'm very new to using .Net Core, but I had the same error and it was because some auto-generated ".deps.json" files were missing from the 'bin' folder. Apparently they're needed for finding the dependencies.
http://stackoverflow.com/questions/46622113/ddg#46623098
