### ISSUE TITLE
SocketsHttpHandler & TLS Cert policies

### ISSUE THREAD

**Issue by mahamr** [dotnet/runtime#41352]
### Description

We have a customer experiencing an issue with SocketsHttpHandler in various .NET Core 2.1+-based applications (dotnet CLI, test app using WebClient, potentially others), when calling their internal NuGet repo. They recently went through some CA changes and have a new TLS cert and chain on that repo. There appears to be an issue with policy constraints in that new chain, and when SocketsHttpHandler is used, calls to that NuGet repo fail with the generic "remote cert invalid" error.

### Configuration

This fails on any 2.1+ app we've tested where SocketsHttpHandler is used

### Regression?

Apps on 2.0 don't experience this issue.
The issue does not occur when UseSocketsHttpHandler == false

### Data

Here's the output from the dotnet CLI: 
```
[root@xxx ~]# dotnet new console -o xx
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on xx/xx.csproj...
  Determining projects to restore...
  Restored /root/xx/xx.csproj (in 131 ms).

Restore succeeded.

[root@xxx ~]# cd mikeg
[root@xxx xx]# dotnet add package -n Newtonsoft.Json
info : Adding PackageReference for package 'Newtonsoft.Json' into project '/root/xx/xx.csproj'.
warn : --no-restore|-n flag was used. No compatibility check will be done and the added package reference will be unconditional.
info : PackageReference for package 'Newtonsoft.Json' version '*' added to file '/root/xx/xx.csproj'.
[root@xxx xx]# dotnet restore
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://**.**/artifactory/api/nuget/nuget/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://**.**/artifactory/api/nuget/nuget/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
/usr/share/dotnet/sdk/3.1.302/NuGet.targets(128,5): error : Failed to retrieve information about 'Newtonsoft.Json' from remote source 'https://**.**/artifactory/api/nuget/nuget/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0'. [/root/xx/xx.csproj]
/usr/share/dotnet/sdk/3.1.302/NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [/root/xx/xx.csproj]
/usr/share/dotnet/sdk/3.1.302/NuGet.targets(128,5): error :   The remote certificate is invalid according to the validation procedure. [/root/xx/x.csproj]
```

And here’s the error from a test app that sends an HTTP request to the repo (via WebClient.DownloadFile(..)):
```
 System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

Here's output from dotnet-trace captured of the test app when it fails:
Event name | Rest
-- | --
Microsoft-System-Net-Security/RemoteCertificateError | HasStack="True" ThreadID="253"   ProcessorNumber="0" secureChannelHash="65,934,242"   message="Remote certificate has errors:"
Microsoft-System-Net-Security/RemoteCertificateError | HasStack="True"   ThreadID="253" ProcessorNumber="0"   secureChannelHash="65,934,242" message="ChainStatus: The certificate has invalid   policy."
Microsoft-System-Net-Security/RemoteCertUserDeclaredInvalid | HasStack="True" ThreadID="253"   ProcessorNumber="0" secureChannelHash="65,934,242"

### Analysis

Regarding the cert chain, this is what I was told:

> I noticed a difference in the X509 policy constraints for the CA in the chain too. The old one has:
> 
>             X509v3 Policy Constraints:
>                 Inhibit Policy Mapping:0
> 
> The new one has:
> 
>             X509v3 Policy Constraints:
>                 Require Explicit Policy:0, Inhibit Policy Mapping:0
> 
> The RFC (https://www.ietf.org/rfc/rfc3280.txt) says:
> 
>    If the requireExplicitPolicy field is present, the value of
>    requireExplicitPolicy indicates the number of additional certificates
>    that may appear in the path before an explicit policy is required for
>    the entire path.  When an explicit policy is required, it is
>    necessary for all certificates in the path to contain an acceptable
>    policy identifier in the certificate policies extension.  An
>    acceptable policy identifier is the identifier of a policy required
>    by the user of the certification path or the identifier of a policy
>    which has been declared equivalent through policy mapping.
> 
> The leaf certificate is using this policy OID:  2.16.840.1.101.3.2.1.3.8
> 
> But this OID is not in the policy mapping nor are there any CPS or user notices declared for 2.16.840.1.101.3.2.1.3.8 in any of the CAs. And since 'inhibit any policy' constraint is also set, the 'anyPolicy' policy set on the root certificate does not generate a match for this OID.

> So it does seem like maybe the policy is the problem, but I guess I have a couple questions/comments:
> 
> •	The error message .NET displays is not remotely helpful. The validation procedure is complex and there should  be a better reason given if this is indeed the problem.
> •	It seems like most widely-used programs do not do any form of policy validation, regardless of policy constraints. I'm thinking of browsers (Chrome, Edge, IE11, Firefox), language runtimes (JavaScript, Java, Python, Ruby, et al), common utilities (curl, wget). So it seems proper for there at least to be an option to disable policy validation to be compatible with the X509 ecosystems most people are using. It seems extremely, extremely unlikely that the CA will get reissued even if we ask about it. This CA services thousands of applications and users across [the org] and has been in place for about a year now.

Thoughts?

**Comment by wfurt** [comment]
cc: @bartonjs

What OS this is running on? 

And yes, the exception is not that useful in 2.1.

**Comment by bartonjs** [comment]
I think the first question would be "does Windows produce the same status codes?", because it could be that our Linux version of X509Chain is just confused by the policy state (policy processing is hard, and not rarely used, so there may be bugs where we were trying to match compatibility).

If Windows says it's fine but Linux says that it has policy errors, we'll fix the policy processor to produce a consistent state (though we'll need a repro description so we can build the verification case).  If they both say it's a problem then we'd have to make the different decision to ignore policy errors when deciding if the certificate is acceptable.

In the short term, you could register a custom TLS verification callback and re-evalute the chain with `chain.ChainPolicy.VerificationFlags |= X509VerificationFlags.IgnoreInvalidPolicy` when the SslPolicyErrors value is only RemoteCertificateChainErrors.  Then, if chain.Build returns true, you can return true.  (Really you'd just return the value from chain.Build in that case).

```C#
// the callback signature is different for different layers, but the body is always the same for what you described:

if (errors == SslPolicyErrors.RemoteCertificateChainErrors)
{
    chain.ChainPolicy.VerificationFlags |= X509VerificationFlags.IgnoreInvalidPolicy;
    return chain.Build(certificate);
}

return errors == SslPolicyErrors.None;
```

**Comment by mahamr** [comment]
@wfurt - I'll get the customer to update that info here

@bartonjs - the problem with that is this affects the dotnet CLI itself, as well - we just identified with a test console app that other apps _can_ experience the same issue

**Comment by karelz** [comment]
@mahamr is there option to fix the certificate? It seems that it is invalid according to Windows (based on your experience) and therefore it would not make much sense to force .NET (incl. CLI) to consider it valid, would it?

**Comment by mahamr** [comment]
@karelz for that I'll defer to the customer's points noted in the "Analysis" portion of my initial post. I'm guessing their only option here is to continue disabling usage of SocketsHttpHandler until another option is more readily doable.

**Comment by wfurt** [comment]
They can use the custom validation as @bartonjs suggested. There is still no good info here about OS or good repro case. 
So we can only speculate here.

**Comment by karelz** [comment]
BTW: @mahamr I think I misunderstood your "other applications" comment -- I thought you experimented with Windows app using OS APIs and it failed. But it seems you tried simple HelloWorld in C# to demonstrate it is not CLI problem. Can you please confirm?

**Comment by mahamr** [comment]
The problem occurs in _both_ the dotnet CLI **and** a simple test console app that uses WebClient.DownloadFile(). It is resolved/worked-around in _both_ when UseSocketsHttpHandler == false.
I've asked our customer for more OS details and will reply here (or they will) once we have those details.

**Comment by jcmcken** [comment]
Hi, just to clarify (since I'm involved with the original report this issue is based on), our primary issue is with the ``dotnet`` CLI, not any .NET applications we've written (although as @mahamr mentioned, it does happen in .NET apps as well, we just haven't had any user reports about it yet). So any solution involving custom code doesn't help us necessarily. We have users attempting to use ``dotnet`` in CI jobs to run their builds and this is where it fails (installing packages from a private NuGet repo).

As to Windows, I can't say, and it's not particularly relevant to us (though it might be to .NET devs) since we have no Windows footprint. I will say, as mentioned in the report, that browsers work, including Chrome. Since Edge is based on Chrome I imagine that it inherits Chrome's handling of X509 policy validation and so there's no issue there (our enterprise does not install Chrome-based Edge though, so I haven't explicitly tested it). For .NET apps running on Windows, again, I can't say -- we don't have any.

I submitted [this issue](https://github.com/GSA/fpki-guides/issues/736) to the PKI that manages the CA that signed the certificate that's causing the underlying issue, but haven't gotten any response so far.

**Comment by bartonjs** [comment]
Can you share a specific certificate/context where you're seeing this error?

**Comment by wfurt** [comment]
Could you recreate the certificate with different keypair and post repro @jcmcken ? That would speed up the investigation IMHO. Also what his underlying OS and OpenSSL version?

**Comment by jcmcken** [comment]
@bartonjs I think all that information has already been shared through Microsoft support with @mahamr . I'm not really sure if I should be divulging it on GitHub, even though it's public certificates. I think GSA/fpki-guides#736 and the info in the OP should have enough info to reproduce. Basically, sign a certificate with a non-standard policy OID, with no CPS or user notice, and with "Require Explicit Policy" and "Inhibit Policy Mapping" set to 0 on the grandfather CA (not sure this matters, it can probably just be the signing CA too).

@wfurt It's an internal, government CA that's not under my control. So short answer: nope, I can't. Underlying OS is CentOS 7.x latest version and openssl is version distributed with the OS (I think the latest RPM is openssl-1.0.2k-19.el7.x86_64). Although I don't think this matters. We've tried it in Alpine and Ubuntu containers too and get the same behavior.

**Comment by mahamr** [comment]
Now that .NET 5 has released and removed the ability to use the "UseSocketsHttpHandler=false" switch, the dotnet CLI on .NET 5 I'm thinking will be broken for the scenario this issue was opened for. Since this is not an issue with System.Net itself, but is really with how the dotnet CLI consumes the System.Net APIs, I am closing this issue in favor of dotnet/sdk#14692

@jcmcken if you're able to test this on your end with .NET 5 CLI _dotnet restore_ that would be great. If it is indeed broken I recommend opening a new issue in the dotnet/sdk repo, referencing this and the one I opened as a feature request above.
