### ISSUE TITLE
BrowserDebugProxy project uses wrong Microsoft.Extensions.Logging reference 

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#41356]
https://github.com/dotnet/runtime/blob/master/src/mono/wasm/debugger/BrowserDebugProxy/BrowserDebugProxy.csproj#L8 uses PackageReference with an old version for `Microsoft.Extensions.Logging` library which is built as part of dotnet/runtime repo.

@thaystg @akoeplinger

**Comment by akoeplinger** [comment]
We can update to latest 3.1.7 but it doesn't really matter that much since it's all encapsulated in the executable (Blazor launches it via dotnet exec).

**Comment by marek-safar** [comment]
That's the point, the latest version is actually 5.0.0-rc1.x.x and will keep updating (trying to avoid future version mismatch)

**Comment by akoeplinger** [comment]
We discussed and agreed we should just bump to latest stable since this is a standalone app.
