### ISSUE TITLE
Add Enumerable.WhereNotNull()

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#41363]
The compiler has limitations what it can infer and express with respect to nullability, especially in the context of generics. When using LINQ, it's common to deal with sequences that should not contain `null` values. Unfortunately, there is no easy way to make the type checker aware when they got removed.

Consider this:

```C#
private static IReadOnlyList<ToolCommand> GetCommands()
{
    return typeof(Program).Assembly
                          .GetTypes()
                          .Where(t => typeof(ToolCommand).IsAssignableFrom(t) &&
                                      !t.IsAbstract && t.GetConstructor(Array.Empty<Type>()) != null)
                          .Select(t => (ToolCommand?)Activator.CreateInstance(t))
                          .OrderBy(t => t.Name)
                          .ToArray();
}
```

Since the `Activator.CreateInstance` may return a null value, the compiler correctly warns me that `.OrderBy(t => t.Name)` may null-ref. Sadly, inserting `.Where(t => t != null)` doesn't fix this because it doesn't change the return type of the `Where()` method. One also has to insert `.Select(t => t!)` to tell the type system that the values are now not-null.

```C#
private static IReadOnlyList<ToolCommand> GetCommands()
{
    return typeof(Program).Assembly
                          .GetTypes()
                          .Where(t => typeof(ToolCommand).IsAssignableFrom(t) &&
                                      !t.IsAbstract && t.GetConstructor(Array.Empty<Type>()) != null)
                          .Select(t => (ToolCommand?)Activator.CreateInstance(t))
                          .Where(t => t != null)
                          .Select(t => t !)
                          .OrderBy(t => t.Name)
                          .ToArray();
}
```

## Proposed API

We can address this problem by introducing a method that explicitly changes the return type:

```C#
namespace System.Linq
{
    public partial class Enumerable
    {
        public static IEnumerable<T> WhereNotNull<T>(this IEnumerable<T?> source)
            where T: class;
    }
}
```

It also makes the common tasks of excluding `null` values easier.

## Usage Examples

```C#
private static IReadOnlyList<ToolCommand> GetCommands()
{
    return typeof(Program).Assembly
                          .GetTypes()
                          .Where(t => typeof(ToolCommand).IsAssignableFrom(t) &&
                                      !t.IsAbstract && t.GetConstructor(Array.Empty<Type>()) != null)
                          .Select(t => (ToolCommand?)Activator.CreateInstance(t))
                          .WhereNotNull()
                          .OrderBy(t => t.Name)
                          .ToArray();
}
```

**Comment by GrabYourPitchforks** [comment]
Is there any way to remove the `where T : class` restriction? I can imagine scenarios where I want to use this within a helper function, but my helper function isn't constrained to `where T : class`. In cases where _T_ is a non-nullable value type the method's implementation would essentially be "return this".

**Comment by mburbea** [comment]
What about just using `OfType<T>()`? It removes null entries and casts a `IEnumerable<T?>` into `IEnumerable<T>`.

https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AGQEsoBHAbjwwKfQGYiBvPI3k9dFx58RANwCGYIgGciAXiJQApgHcSmAgH4A2gF1OAInEGYUCABtzAX0a4RI0gE4AFNLIB5AGYAVAJ4AHJQAeUgIAPmcASk0yAGUlcyUAY2BXOTC3CiUoAHNgAAtIsgBhAHtoVMjI2xErPCsgA===

**Comment by FiniteReality** [comment]
@mburbea That's still an extra method call:
```cs
var values = mySequence
    .Where(x => x != null)
    .OfType<T>();
// or
var values = mySequence
    .Where(x => x != null)
    .Select(x => x!);
```
The goal is:
```cs
var values = mySequence
    .WhereNotNull();
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/30381
