### ISSUE TITLE
Add more Array.Sort test combinations, per #41234

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#41376]
Should we have more test combinations, given this involves the complexity of pivots, etc?

_Originally posted by @danmosemsft in https://github.com/dotnet/runtime/pull/41234#issuecomment-678879413_

**Comment by Peekoe** [comment]
Hello! I am a beginner at contributing to open source and would like to take a shot at this. Where should I look to try writing some tests for Array.Sort? and where are some good example tests to get a feel for how tests are written?

**Comment by DDolG** [comment]
Hello! I want to help. But I don't know how to start.  I am new at the repo. 
Could anyone point me in the right direction to start this thing?
I download the repository to my computer. Looked at what changes were added in the code. Looked at the added test case. I don't understand what is "complexity of pivots" means.

**Comment by krwq** [comment]
@DDolG you'll need to check the internal implementation details of the sort function and try to understand it. The particular piece mentioned in the other PR is referring to pivot from the [intro sort](https://en.wikipedia.org/wiki/Introsort) - See https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/ArraySortHelper.cs#L473 - you will need to pick data which will exercise all branches of that code
