### ISSUE TITLE
Performance regression: Utf8String.IsAscii (x86 only)

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#41388]
## Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\scripts\benchmarks_ci.py -f netcoreapp3.1 netcoreapp5.0 --filter System.Text.Perf_Utf8String.IsAscii --architecture x86
```

@eiriktsarpalis @GrabYourPitchforks @carlossanlop @pgovind  I am setting 5.0 milestone to make sure that it gets triaged within the next few weeks. 

There was a similar issue, but I've verified that https://github.com/dotnet/runtime/pull/41198 is not fixing this problem.

@GrabYourPitchforks @eerhardt  The benchmark throws for all other documents for 3.1.6 which **might be a bug in .NET Standard implementation of Utf8String**:

```log
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  ---> System.ArgumentException: The input buffer contained ill-formed UTF-16 data. (Parameter 'value')
    at System.Utf8String.InitializeBuffer(ReadOnlySpan`1 value)
    at System.Utf8String..ctor(String value)
    at System.Text.Perf_Utf8String.Setup() in C:\Projects\performance\src\benchmarks\micro\libraries\System.Utf8String\Perf.Utf8String.cs:line 21[2020/08/26 12:11:48][INFO]
```

## System.Text.Perf_Utf8String.IsAscii(Input: EnglishAllAscii)

| Conclusion |     Base |     Diff | Base/Diff | Modality | Operating System        | Bit   | Processor Name                              | Base Runtime    | Diff Runtime           |
| ---------- | --------:| --------:| ---------:| -------- | ----------------------- | ----- | ------------------------------------------- | --------------- | ----------------------- |
| Same       | 21236.28 | 21117.76 |      1.01 |          | Windows 10.0.18363.1016 | Arm   | Microsoft SQ1 3.0 GHz                       | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3   |
| Same       |  3660.66 |  3453.20 |      1.06 |          | Windows 10.0.18363.959  | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3   |
| Faster     |  3780.81 |  3095.66 |      1.22 |          | Windows 10.0.19041.450  | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)    | .NET Core 3.1.6 | 5.0.100-rc.1.20419.9   |
| Slower     |  3548.77 |  7006.60 |      0.51 |          | Windows 10.0.18363.959  | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20420.14  |
| Slower     |  4134.58 |  7835.15 |      0.53 |          | Windows 10.0.19041.450  | X86   | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20419.5   |
| Same       | 30655.72 | 42199.20 |      0.73 | bimodal  | ubuntu 18.04            | Arm64 | Unknown processor                           | .NET Core 3.1.6 | 6.0.100-alpha.1.20421.6|

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

@DrewScoggins this regression did not get detected by the bot because benchmark was added just a few days ago, so everything is 👍

**Comment by ericstj** [comment]
@GrabYourPitchforks can you have a look?  (sorry for removing Untriaged, usually when I see a milestone assigned I think it's been triaged).

**Comment by GrabYourPitchforks** [comment]
This is a non-shipping component, but it's still useful to figure out where the perf loss came from.

**Comment by GrabYourPitchforks** [comment]
Transcoding workhorse routine on 3.1.x x86:

```asm
079e8c60 55              push    ebp
079e8c61 8bec            mov     ebp,esp
079e8c63 57              push    edi
079e8c64 56              push    esi
079e8c65 53              push    ebx
079e8c66 c5f877          vzeroupper
079e8c69 b880ffffff      mov     eax,0FFFFFF80h
079e8c6e c5f96ec0        vmovd   xmm0,eax
079e8c72 c4e27979c0      vpbroadcastw xmm0,xmm0
079e8c77 c5fa6f09        vmovdqu xmm1,xmmword ptr [ecx]
079e8c7b c4e27917c8      vptest  xmm1,xmm0
079e8c80 0f94c0          sete    al
079e8c83 0fb6c0          movzx   eax,al
079e8c86 85c0            test    eax,eax
079e8c88 7509            jne     System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d8ab (079e8c93)
079e8c8a 33c0            xor     eax,eax
079e8c8c 5b              pop     ebx
079e8c8d 5e              pop     esi
079e8c8e 5f              pop     edi
079e8c8f 5d              pop     ebp
079e8c90 c20400          ret     4
079e8c93 c5f167d1        vpackuswb xmm2,xmm1,xmm1
079e8c97 c5f9d612        vmovq   mmword ptr [edx],xmm2
079e8c9b b808000000      mov     eax,8
079e8ca0 f6c208          test    dl,8
079e8ca3 751d            jne     System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d8da (079e8cc2)
079e8ca5 c5fa6f4910      vmovdqu xmm1,xmmword ptr [ecx+10h]
079e8caa c4e27917c8      vptest  xmm1,xmm0
079e8caf 0f94c3          sete    bl
079e8cb2 0fb6db          movzx   ebx,bl
079e8cb5 85db            test    ebx,ebx
079e8cb7 7453            je      System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d924 (079e8d0c)
079e8cb9 c5f167d1        vpackuswb xmm2,xmm1,xmm1
079e8cbd c5f9d65208      vmovq   mmword ptr [edx+8],xmm2
079e8cc2 8bc2            mov     eax,edx
079e8cc4 83e00f          and     eax,0Fh
079e8cc7 be10000000      mov     esi,10h
079e8ccc 2bf0            sub     esi,eax
079e8cce 8bc6            mov     eax,esi
079e8cd0 8b7508          mov     esi,dword ptr [ebp+8]
079e8cd3 83ee10          sub     esi,10h
079e8cd6 33ff            xor     edi,edi
079e8cd8 8bf8            mov     edi,eax
079e8cda c5fa6f0c79      vmovdqu xmm1,xmmword ptr [ecx+edi*2]
079e8cdf 33ff            xor     edi,edi
079e8ce1 8bf8            mov     edi,eax
079e8ce3 c5fa6f547910    vmovdqu xmm2,xmmword ptr [ecx+edi*2+10h]
079e8ce9 c5f1ebda        vpor    xmm3,xmm1,xmm2
079e8ced c4e27917d8      vptest  xmm3,xmm0
079e8cf2 0f94c3          sete    bl
079e8cf5 0fb6db          movzx   ebx,bl
079e8cf8 85db            test    ebx,ebx
079e8cfa 7417            je      System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d92b (079e8d13)
079e8cfc c5f167d2        vpackuswb xmm2,xmm1,xmm2
079e8d00 c5f97f1402      vmovdqa xmmword ptr [edx+eax],xmm2
079e8d05 83c010          add     eax,10h
079e8d08 3bc6            cmp     eax,esi
079e8d0a 76ca            jbe     System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d8ee (079e8cd6)
079e8d0c 5b              pop     ebx
079e8d0d 5e              pop     esi
079e8d0e 5f              pop     edi
079e8d0f 5d              pop     ebp
079e8d10 c20400          ret     4
079e8d13 c4e27917c8      vptest  xmm1,xmm0
079e8d18 0f94c1          sete    cl
079e8d1b 0fb6c9          movzx   ecx,cl
079e8d1e 85c9            test    ecx,ecx
079e8d20 74ea            je      System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d924 (079e8d0c)
079e8d22 c5f167d1        vpackuswb xmm2,xmm1,xmm1
079e8d26 c5f9d61402      vmovq   mmword ptr [edx+eax],xmm2
079e8d2b 83c008          add     eax,8
079e8d2e ebdc            jmp     System_Private_CoreLib!System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(Char*, Byte*, UInt32)+0xffffffff`8eb9d924 (079e8d0c)
```

**Comment by joperezr** [comment]
> This is a non-shipping component, but it's still useful to figure out where the perf loss came from.

Changing milestone to 6.0.0 given Utf8String is still experimental and so as to not confuse with remaining 5.0 work.

**Comment by GrabYourPitchforks** [comment]
@adamsitnik Since Utf8String isn't in the runtime repo any more, ok if I close this issue?

**Comment by adamsitnik** [comment]
> Since Utf8String isn't in the runtime repo any more, ok if I close this issue?

It's OK.

@krwq if|when we reintroduce `Utf8String` to the runtime repo again we will have to verify the x86 perf
