### ISSUE TITLE
NullReferenceException in DataContractSerializer

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#41395]
### Description

Not setting `DataContractSerializerSettings.RootNamespace` can cause NullReferenceExceptions in DataContractSerializer. For example:

```C#
using System.Runtime.Serialization;
using System.Xml;

class Customer
{
    public string Name {get; set;}
}

var ds = new DataContractSerializer(typeof(Customer), new DataContractSerializerSettings() { RootName = XmlDictionaryString.Empty });
ds.ReadObject(XmlReader.Create("temp.xml"));
```

Causes:

```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
at System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(XmlDictionaryString localname, XmlDictionaryString ns)
at System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns)
at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlReader reader)
```

**Comment by StephenMolloy** [comment]
The example here is actually setting _RootName_ and not _RootName**space**_. There is no exception when setting the root namespace to the empty string, and the behavior in that case is the same as it was in 4.8.

When setting RootName however, I believe this exception is the same as it was in 4.8 as well. Which makes sense because how do you read or write an xml element whose name is ""?

**Comment by eerhardt** [comment]
> The example here is actually setting RootName and not RootNamespace. 

Correct - that is the point of this bug. 

_Not setting DataContractSerializerSettings.RootNamespace can cause NullReferenceExceptions in DataContractSerializer._

**Comment by StephenMolloy** [comment]
Oh, so you mean that you get an error when you specify a valid RootName without specifying a RootNamespace? The empty string is definitely not valid as a RootName, so I was getting an expected error for that reason with your sample. I see the error you're mentioning here now.

FWIW, this error is also still the same as 4.8. Though I am able to serialize successfully with these settings before failing on the deserializing leg. So we could look at fixing this to improve the round-trip experience.

**Comment by eerhardt** [comment]
Yeah, setting RootName to empty wasn’t really relevant here - it just needed to be set to some non-null value to illustrate the NRE when not setting RootNamespace.

note - I found this bug when I was annotating the XmlSerializer with nullable annotations. It isn’t high priority to fix, but should be pretty simple. So maybe marking it as “up for grabs” might make sense.
