### ISSUE TITLE
Remove the Trailing Slash from URI when converting to String

### ISSUE THREAD

**Issue by mjd575** [dotnet/runtime#41391]
In Asp.net core 3.1, I create a Uri like below:

`Uri uri = new Uri($"https://www.example.com?id=1&name=aa");`

When I convert it to string:

`uri.ToString()`

It will automatically add a trailing slash behind the domain:

`https://www.example.com/?id=1&name=aa`

Is there a way to remove the trailing slash?

**Comment by karelz** [comment]
Try `uri.OriginalString`:

```c#
        Uri uri = new Uri($"https://www.example.com?id=1&name=aa");
        Console.WriteLine(uri.ToString());
        Console.WriteLine(uri.AbsoluteUri);
        Console.WriteLine(uri.OriginalString);
```

Output:
```
https://www.example.com/?id=1&name=aa
https://www.example.com/?id=1&name=aa
https://www.example.com?id=1&name=aa
```

**Comment by MihaZupan** [comment]
What is the goal behind removing this slash?

**Comment by mjd575** [comment]
I'm just curious why this slash is automatically added,  seems it is the default behavior.

**Comment by seonyounggg** [comment]
`ToString`,  `AbsoluteUri` returns the canonically unescaped form of the URI. Otherwise, `OriginalString` returns the original non normalized string.

I think these Docs can help you.
[Uri.ToString](https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring?view=netcore-3.1) , [Uri.OriginalString](https://docs.microsoft.com/en-us/dotnet/api/system.uri.originalstring?view=netcore-3.1)

**Comment by karelz** [comment]
@mjd575 I believe the slash is required by the Uri RFC. Without slash, it is not well formed IMO -- @MihaZupan will be able to say for sure.

**Comment by MihaZupan** [comment]
I believe it may have been required by ancient Url specifications, though not required by the current spec. So having the slash there can theoretically improve compatibility.

Chrome will for example add slash when making a request. See http://example.com?foo=bar

I don't see any value in omitting it - is there a use-case behind it, or just curiosity?

**Comment by KalleOlaviNiemitalo** [comment]
Omitting the slash could make sense for distinguishing an `OPTIONS *` request ([RFC 7230 §5.3.4](<https://tools.ietf.org/html/rfc7230#section-5.3.4> "RFC 7230. Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing
Section 5.3.4. asterisk-form")) from `OPTIONS /`, as hinted by the URI normalization rule ([RFC 7230 §2.7.3](<https://tools.ietf.org/html/rfc7230#section-2.7.3> "RFC 7230. Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing
Section 2.7.3. http and https URI Normalization and Comparison")). [HttpConnection.SendAsyncCore](https://github.com/dotnet/runtime/blob/bf456654f9a4f9a86c15d9d50095ff29cde5f0a4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L381) in SocketsHttpHandler does not seem to support that, though.
