### ISSUE TITLE
[Proposal] Add Permutate in LINQ function in C#

### ISSUE THREAD

**Issue by sps014** [dotnet/runtime#41399]
#### Permutation
A permutation is an arrangement of all or part of a set of objects, with regard to the order of the arrangement.

Permutations of numbers 1,2, 3 are 
```
1  2  3  
1  3  2  
2  1  3  
2  3  1  
3  1  2  
3  2  1  
```

Permutation function is not that hard to implement, so many people might be asking why not create a Extension Method yourself.

#### That's a fair question , actually until now we have been using Permutate function like this only, I really don't have good points to counter that.

1. I come from competitive programming background, I solve all the problems in C# i really encounter many problems involving permutation , In Languages Like C++ and Python  already providing built-in  implementations. Every time I have to either reinvent the wheel or copy from one of my previous solved question if am using C#.
```cpp
//C++ STL builtin
 auto v=std::next_permutation(myints,myints+3);
```
```py
from itertools import permutations 
# python permutations iter tools
p = permutations(s) 
```

2. We have several other LINQ functions that are also easy to implement ourself like Where, Select etc. but at the end of the day we are having them in C#.

3. It won't be a breaking change in C# ecosystem, people won't be troubled with that .

4. With DotNetCore 5 and C# 9 I am expecting more and more people migrating towards C# , this function can come in handy for beginners just like Top Level Programs will benefit them.

##### Proposal 
The Idea is to have a Permutate LINQ Function like,
```cs
var list=new List<int>();
var allPer=list.Permutate().ToList();
allPer=list.Permutate(startIndex:3).ToList();
allPer=list.Permutate(startIndex:3,endIndex:5).ToList();

```

**Comment by sps014** [comment]
Permutate for string Class will be a plus a well

**Comment by ZacharyPatten** [comment]
I have implemented this topic myself. There is probably room for improvement, but I wanted to share my implementation in case it might help:

Source: https://github.com/ZacharyPatten/Towel/blob/master/Sources/Towel/Permute.cs
Examples:
https://github.com/ZacharyPatten/Towel/blob/5f7240096789ad10d6efd4252f8a38b9d8995ef8/Examples/BasicsAndExtensions/Program.cs#L394

**Comment by Clockwork-Muse** [comment]
.... and outside of "competitive" coding (I assume you mean coding challenges on various sites), have you written something that would benefit from this?

Note that `string` is already `IEnumerable<char>` so you'd get that implementation for free.
Note that, if this were placed in LINQ, any implementation would be required to take an additional `N` space, as opposed to using the space of the original (this isn't so bad, actually - a number of existing methods are already required to do this, at least for some types)

**Comment by sps014** [comment]
This is really a handful collection of Utility Classes. @ZacharyPatten 

@Clockwork-Muse  I agree that Permutation is something that people don't use often. It's not wrong if it is implemented in C#, other languages have done this already, I see quite a few C# Programmers on coding platform and some game developers , they  may also get benefited.

**Comment by Clockwork-Muse** [comment]
> other languages have done this already

This is not a reason to implement a new feature.  (It may provide a reason to investigate whether such a feature should be implemented, but it is insufficient on its own)

>I see quite a few C# Programmers on coding platform 

If you're talking about coding challenge platforms, that is not a reason to implement the feature.  Despite developers liking to challenge themselves, that is by far a minority usage.  If you're talking about something else, please clarify.

> and some game developers

This is a "maybe".  Besides the limited audience, in many cases for games needing permutation, they also need to control it in ways we would not be able to provide (and where LINQ may be a poor fit anyways).  Do you have any concrete examples of games that would have benefited from this?

**Comment by eiriktsarpalis** [comment]
Generating permutations for IEnumerable would require creating an _O(n)_ copy of the source. I would suspect writing a bespoke implementation for the source type and application at hand to be more appropriate.

I also fail to think of a real-world application that uses permutations, at least in the context of LINQ. Assuming you're looking to perform some kind of brute-force calculation, then probably the performance overheads of using LINQ might make such an approach infeasible, unless we're looking at really small inputs. The complexity of iterating through all permutations is _n!_, which is asymptotically larger than exponential.

I'm going to close this issue. Feel free to reopen if you would like to resume this conversation.

**Comment by ZacharyPatten** [comment]
@eiriktsarpalis 

_**I agree with not adding a LINQ version of a permutation function to C#. :)**_

But I just want to mention that...
> I would suspect writing a bespoke implementation for the source type

...is not necessary. You can write one version that works with any source type. Assuming by "source type" we mean the collection type (array, list, dictionary, etc.). My example that I linked to in an above comment above accomplishes that topic.

Unfortunately their is no way to abstract `Span<T>` and other types (due to restrictions like not being able to use it in generics, fields, or capture variables), so `Span<T>` requires its own overload currently. I'm sure they will add a way to properly abstract ref structs I the future.
