### ISSUE TITLE
UTF7 Encoder Convert method fails to make progress on "naughty" string

### ISSUE THREAD

**Issue by kevin-montrose** [dotnet/runtime#414]
> I opened an [identical issue](https://github.com/dotnet/corefx/issues/42750) ([erroneously, it turns out](https://github.com/dotnet/corefx/issues/42733)) on [dotnet/corefx](https://github.com/dotnet/corefx), I'm posting it here and closing it over there to fix my error.

I noticed some odd behavior with UTF7's [`Encoder`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoder?view=netcore-3.0), and failing to make progress on a ["naughty" string](https://github.com/minimaxir/big-list-of-naughty-strings).

Namely, adapting the example code provided for [`Convert`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoder.convert?view=netcore-3.0) will spin forever (failing to set `completed == true`) on `@"00˙Ɩ$-"`.

UTF7 is sufficiently weird that maybe this is expected, and I just don't understand it?

I have a [repository with a repro](https://github.com/kevin-montrose/Latin1Repro/blob/master/Latin1Repro/Program.cs#L19) (it also has some Latin1 stuff that I'll report in a separate issue, as it's probably unrelated).

A smaller version of what's in the repo:

```csharp
var destBufferSize = 16;
var encoding = System.Text.Encoding.UTF7;
var text = @"00˙Ɩ$-";

var encoder = encoding.GetEncoder();

var chars = text.ToCharArray();

var sourceSpan = chars.AsSpan();
var destSpan = new byte[destBufferSize].AsSpan();
var encoderBytes = new List<byte>();

var completed = false;

while (!completed)
{
    var flush = sourceSpan.Length == 0;
    encoder.Convert(sourceSpan, destSpan, flush, out var charsConsumed, out var bytesProduced, out completed);
    encoderBytes.AddRange(destSpan.Slice(0, bytesProduced).ToArray());

    sourceSpan = sourceSpan.Slice(charsConsumed);

    if (charsConsumed == 0 && bytesProduced == 0 && flush)
    {
        Console.WriteLine($@"Encoding Convert failure for destBufferSize={destBufferSize}, stopped making progress");
        return;
    }
}
```

Will print, when it (probably) shouldn't.

**Comment by danmosemsft** [comment]
@GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Yeah, `UTF7Encoding` has some really weird / buggy behaviors. We don't allow UTF7-encoded requests by default in ASP.NET 4.5+ (including ASP.NET Core) due to security issues it might impose on the receiving application. There's also a warning [on MSDN docs](https://docs.microsoft.com/en-us/dotnet/api/system.text.utf7encoding) to this effect.

**Comment by GrabYourPitchforks** [comment]
@kevin-montrose, can you clarify what .NET Core versions you were running the repro on? I see from your repo that you're targeting _netcoreapp3.0_, but the demo file there seems like it's testing extra functionality and I don't know whether it affects the runtime you're intending to target.

**Comment by kevin-montrose** [comment]
Missed this ping, sorry for the delay in response.

I was running on .NET Core 3.0, though the issue seems to reproduce on 2.2, 2.1, and 3.1.  The methods I used on Encoder don't exist in early .NET Core (they're Span-y).

**Comment by kevin-montrose** [comment]
I also confirmed this behavior still happens in .NET Core 3.0 if you use the pointer methods instead of the Span ones.

**Comment by GrabYourPitchforks** [comment]
Related: I opened https://github.com/dotnet/runtime/issues/32284 a few days ago to track obsoleting `UTF7Encoding` entirely.

**Comment by GrabYourPitchforks** [comment]
UTF-7 is now properly marked `[Obsolete]`.
