### ISSUE TITLE
Expose Dictionary's comparer through its KeyCollection

### ISSUE THREAD

**Issue by shubhamranjan** [dotnet/runtime#41409]
## Background and Motivation

Currently there is no way to get a `Dictionary.KeyCollection`'s comparer that was used in the containing dictionary. This way other classes cannot be aware of its `IEqualityComparer` and won't be able to compare elements with the intended way while performing certain comparison operations.

For e.g. In #41335 , If an attempt to modify hashset's intersect is made to utilize the dictionary's contains method, it will be inaccurate due to the the inability to compare their `IEqualityComparer`.

## Proposed API
KeyCollection exposes a readonly property which returns the dictionary's comparer.

```
        public sealed class KeyCollection : ICollection<TKey>, ICollection, IReadOnlyCollection<TKey>
        {
            //
            .
            .
            .
            public IEqualityComparer<TKey>? Comparer => _dictionary.Comparer;
            .
            .
            .
        }
```

## Usage Examples
```
private static void Main(string[] args)
{
    Console.WriteLine("Dictionary Props:");
    var dictionary = new Dictionary<int, bool> { { 33, true } };
    DoSomething(dictionary.Keys);

    Console.WriteLine("\nSet Props: ");
    HashSet<int> set= new HashSet<int> { 1 };
    DoSomething(set);
}

static void DoSomething<T>(ICollection<T> collections)
{
    Type? collectionType = collections.GetType();
    collectionType = collectionType.IsGenericType ? collectionType.GetGenericTypeDefinition() : null;
    foreach (var prop in collectionType.GetProperties())
    {
        Console.WriteLine(prop.Name);
    }
}
```

**Comment by eiriktsarpalis** [comment]
I would need to understand what the motivation for adding this property is. What prevents you from obtaining the equality comparer from the parent dictionary object?

**Comment by shubhamranjan** [comment]
Sorry for a vague example. Updated it. If we pass the `Keys` property of the dictionary as a parameter to another method, we will not be able to fetch the comparer from the parent dictionary object.
If the method `DoSomething` is within the same application, then we can surely refactor our code to have references to the parent dictionary but if the method is inside a class library not owned by a user, its not possible to have any sort of reference to the parent Dictionary to fetch its properties like `Comparer`.

**Comment by eiriktsarpalis** [comment]
But what would you need the comparer for? In this example `DoSomething` just enumerates properties using reflection.
