### ISSUE TITLE
Allow model-binding error messages to be customised

### ISSUE THREAD

**Issue by IanKemp** [dotnet/runtime#41408]
Currently, attempting to model bind an invalid enum value results in an error message similar to the following:

```
The JSON value could not be converted to EnumType. Path: $.status | LineNumber: 4 | BytePositionInLine: 17.
```

This is not particularly helpful or useful to end-users, and even less helpful or useful is the fact that this message cannot be customised except by writing your own model binder, which is a lot of work and doesn't really make sense when you just want to change a message.

Can the option to customise the model binder error message be added to 5.0? Preferably via an attribute applied to the model property being bound, similarly to how data annotations currently work?

**Comment by pranavkm** [comment]
The error message is generated by System.Text.Json. Transferring it here to discuss this further.

**Comment by layomia** [comment]
@IanKemp what additional information would you like to see/add here? The error message contains the JSON path which helps you inspect the JSON property that contained the erring value.

> similarly to how data annotations currently work?

Can you please provide more information here? What data annotations are these; can you point me to an example?

**Comment by IanKemp** [comment]
@pranavkm The error message is generated by STJ, yes, but the **context** is model-binding which STJ has no concept of. My guess is that STJ will need to provide a hook to support this functionality, and ASP.NET will need to add its own hook to configure this in `ConfigureServices`. What is the correct approach for filing issues that are cross-cutting in this manner?

@layomia The attributes in the `System.ComponentModel.DataAnnotations` namespace allow a custom `ErrorMessage` to be specified when they are applied to an property. If this is not specified, they fall back to a default error message baked into the runtime ([or a localised version](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#dataannotations-localization)). I'm essentially requesting similar functionality for STJ (if there is already a way to achieve this **without writing a lot of custom code**, I'd be happy to hear it).
