### ISSUE TITLE
GC.GetTotalMemory can crash in rare cases when it races with background GC

### ISSUE THREAD

**Issue by ChrisAhna** [dotnet/runtime#41413]
### Description

Calls to [GC.GetTotalMemory](https://docs.microsoft.com/en-us/dotnet/api/system.gc.gettotalmemory) can crash in rare cases where they race with segment deletion processing in the background GC.

The linked [repro app](https://gist.github.com/ChrisAhna/9596dcd5d93306b4f21043b49bdbe090) calls GC.GetTotalMemory in a loop while another thread drives an allocation pattern geared toward getting background GCs to happen from time to time. In initial experiments across a couple of machines, running the app against .NET 5 or .NET Core 3.1.2 via

```
dotnet run -c Release -r win-x86
```

reliably reproduces the crash within the first several minutes of execution. For example:

```
$ bin\Release\net5\win-x86\TryGetTotalMemory.exe
STATUS: BGC seems to be enabled; a crash is expected to be possible if the bug is present.
0x00ffda04: 0x1f6a937c -> 0x1e6ab978 (Gen2GcCount: 38)
...
0x00ffe52c: 0x203f66e0 -> 0x1f3f81b4 (Gen2GcCount: 215)
Fatal error. Internal CLR error. (0x80131506)
   at System.GC.GetTotalMemory()
   at System.GC.GetTotalMemory(Boolean)
   at Test.App.RunQueryThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

The expected behavior would be for the app to run indefinitely without crashing (i.e., until a manual CTRL-C). When backgroung GC is disabled, the underlying race condition cannot occur, and the app behavior in the expected way, for example:

```
$ set COMPLUS_gcConcurrent=0

$ bin\Release\net5\win-x86\TryGetTotalMemory.exe
STATUS: BGC seems to be disabled; a crash is not expected to be possible.
0x016f1adc: 0x1ec571c4 -> 0x1d5656e8 (Gen2GcCount: 31)
...
0x016e9adc: 0x1ebc4d1c -> 0x1d4db240 (Gen2GcCount: 5888)
^C
```

(About the repro app: Note that it is hardcoded to run against a 32-bit runtime. Also, it uses some spinning threads internally and will refuse to run if Environment.ProcessorCount is smaller than 4. The app has one thread that calls GC.GetTotalMemory in a loop as fast as it can, and prints a line of output whenever the result of one call is more than 0xf00000 bytes smaller than the result of the previous call.)

### Configuration

All experiments were run against x86 .NET 5 preview 8 and x86 .NET Core 3.1.2 on current Win10, but the underlying problem generally applies across any configuration where background GC is enabled.

### Regression?

No (I don't know when it was introduced, but the problem has existed for at least a few years).

### Other information

It looks like the crash always happens due to the following sequence:

- `GCHeap::ApproxTotalBytesInUse` walks the SOH segment list while holding the gc_lock.

- If `gc_heap::background_sweep needs` to delete an SOH segment (i.e., when "delete_p" is true), it uses `gc_heap::generation_delete_heap_segment` to move the segment to the `freeable_small_heap_segment` list, but does not hold the gc_lock at the time.

- If BGC SOH segment deletion happens to move a segment to the `freeable_small_heap_segment` list at exactly the same moment that `GCHeap::ApproxTotalBytesInUse` is capturing the size of that segment, it creates a situation where the SOH segment list walk in `GCHeap::ApproxTotalBytesInUse` will unexpectedly "jump" over to the `freeable_small_heap_segment` list.

- Once this "jump" happens, `GCHeap::ApproxTotalBytesInUse` is guaranteed to dereference null (because it loops until it sees "eph_seg", and is therefore guaranteed to walk all the way through the null "next" pointer at the end of the list since "eph_seg" is not a member the `freeable_small_heap_segment` list).

**Comment by ChrisAhna** [comment]
cc @Maoni0

**Comment by jkotas** [comment]
We should fix this for 5.0.

Note that event counters will call GetTotalMemory frequently by default, so chances of apps hitting this are higher than before.

**Comment by mangod9** [comment]
Assigning to Peter since he has been investigating other race conditions recently.

**Comment by Maoni0** [comment]
I already talked to Peter about this.

**Comment by PeterSolMS** [comment]
See my PR https://github.com/dotnet/runtime/pull/41445

**Comment by mangod9** [comment]
Moving to 6.0 to implement a better fix.

**Comment by PeterSolMS** [comment]
Thank you!

**Comment by PeterSolMS** [comment]
Moving to 7.0 as we have higher priority work, and the current solution hasn't been shown to be problematic.

**Comment by Maoni0** [comment]
fixed in https://github.com/dotnet/runtime/pull/59283

**Comment by jkotas** [comment]
Is it fixed for `!USE_REGIONS` as well?

**Comment by Maoni0** [comment]
yes
