### ISSUE TITLE
Provide workflow to automatically port API docs to dotnet-api-docs

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#41419]
During each release cycle we add new APIs and documentation for them. Currently, the process of moving docs over from the triple-slash comments in dotnet/runtime to the API docs on https://docs.dot.net has a number of manual steps.

I propose that we add a GitHub Action (preferable) or manually-triggered Azure DevOps Pipeline to auto-port the doc comments per-assembly to PRs opened against the dotnet/dotnet-api-docs repository.

**Comment by safern** [comment]
Cc: @carlossanlop

**Comment by safern** [comment]
Marking as 6.0.0

**Comment by ViktorHofer** [comment]
cc @carlossanlop @jeffhandley

**Comment by ViktorHofer** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/44969
