### ISSUE TITLE
Is there any schedule of .net6 preview1 release date?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#41423]
I found this issue https://github.com/xamarin/xamarin-macios/issues/8955 said the .net6 preview1 milestone.

we are embeding with mono runtime, but some features like **Unloadable AseemblyLoadContenxt**, **Profiler** with mono are not working?
We hope these can be compeleted soon.

thank you.

**Comment by jkotas** [comment]
We will start .NET 6 previews after .NET 5 release. I expect that the .NET 6 previews schedule will follow similar pattern as .NET 5 previews. There are no fixed dates nor exact list of features that are going to ship in given preview.

If there are specific features you are looking for in Mono, you may want to watch the issues for specific features. For example, 
 https://github.com/dotnet/runtime/issues/34072 tracks unloadable AssemblyLoadContexts in Mono.
