### ISSUE TITLE
Microbenchmark System.Threading.Tests.Perf_Volatile.Read_double is  3,630 % slower on Wasm vs. desktop interpreter.

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41449]
Microbenchmark System.Threading.Tests.Perf_Volatile.Read_double is  3,630 % slower on Wasm vs. desktop interpreter.

System.Threading.Tests.Perf_Volatile.Write_double is also slow (%866), the causes are probably related.

Repro Instructions for running benchmarks locally:
https://gist.github.com/naricc/efdc186951a912507550509b21fb992b

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

**Comment by vargaz** [comment]
This happens because wasm is a 32 bit platform, so reading 64 bit values atomically is more expensive. But since there are no threads currently, it should be possible to optimize this.

**Comment by marek-safar** [comment]
@SamMonoRT who can look into optimizing this?

**Comment by fanyang-mono** [comment]
I will look into this issue next will. Will consult with Zoltan when necessary.

**Comment by fanyang-mono** [comment]
Like Zoltan mentioned earlier, wasm is a 32 bit platform. So the code path differs starting on the managed side. Look here:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Threading/Volatile.cs#L101-L107

**Comment by BrzVlad** [comment]
@fanyang-mono How does the implementation / generated code for Interlocked.Exchange look ? Does it do a pinvoke that we don't intrinsify ?

**Comment by vargaz** [comment]
Yes, it goes to an icall in threads.c.

**Comment by fanyang-mono** [comment]
This is the location of the call: https://github.com/dotnet/runtime/blob/effaf28d0ca74ab9ae11fc947f524393e545af0d/src/mono/mono/metadata/threads.c#L2588

**Comment by fanyang-mono** [comment]
@BrzVlad The generated code for Interlocked.Exchange looks like this:
```Method (wrapper managed-to-native) System.Threading.Interlocked:Exchange (long&,long), original code:
IL_0000: ldarg.0   
IL_0001: ldarg.1   
IL_0002: mono_ldptr2
IL_0008: calli     0x00000003
IL_000d: ret       

IL_0000 ldarg.0   , sp 0,                 vt_sp 0 (max 0)
IL_0001 ldarg.1   , sp 1, I4              vt_sp 0 (max 0)
IL_0002 unused41  , sp 2, I8              vt_sp 0 (max 0)
IL_0008 calli     , sp 3, I4              vt_sp 0 (max 0)
IL_000d ret       , sp 1, I8              vt_sp 0 (max 0)
Merged BB0 and BB1

cprop iteration
BB0
IL_0000: ldloc.o    0, sp 0, (pop 0, push 1)
IL_0001: ldloc.i8   1, sp 1, (pop 0, push 1)
IL_0002: mono_ldptr 0, sp 2, (pop 0, push 1)
IL_0008: calli.nat  2, sp 3, (pop 3, push 1)
IL_000d: ret       , sp 1, (pop 1, push 0)
Runtime method: (wrapper managed-to-native) System.Threading.Interlocked:Exchange (long&,long) 0x598ca0
Locals size 16, VT stack size: 0
Calculated stack size: 3, stated size: 18
IR_0000: ldloc.o    0
IR_0002: ldloc.i8   8
IR_0004: mono_ldptr 0
IR_0006: calli.nat  2
IR_000c: ret 
```

**Comment by vargaz** [comment]
So the JIT intrensify-s it, but the interpreter doesn't, so it ends up being an icall, which has a lot of overhead.
