### ISSUE TITLE
SchemaExporter.ExportEnumDataContract is never called, but has a NullReferenceException

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#41448]
`EnumDataContract` in System.Private.DataContractSerialization has a member `BaseContractName` which is never set on .NET Core:

https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/EnumDataContract.cs#L27

However, this member is dereferenced in `SchemaExporter.ExportEnumDataContract`:

https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/SchemaExporter.cs#L401-L412

Since this member is never set, it can never be non-null. This means this code will always throw NullReferenceException.

However, it doesn't appear this code will ever be called on .NET Core because of this:

https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XsdDataContractExporter.cs#L52-L61

Which always gets called before `SchemaExporter` can be invoked.

For now, I'm using the `!` operator to suppress the NRE in this code. But we should figure out what to do here. My preference would be to delete the dead code until it is publicly callable.

**Comment by StephenMolloy** [comment]
Schema capabilities are back in #71752, and this Nullref is no longer an issue.
