### ISSUE TITLE
Microbenchmark BenchmarksGame.FannkuchRedux_9.RunBench is  1,395 % slower on Wasm vs. desktop interpreter.

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41452]
Microbenchmark BenchmarksGame.FannkuchRedux_9.RunBench(n: 11, expectedSum: 556355) is  1,395 % slower on Wasm vs. desktop interpreter.

BenchmarksGame.FannkuchRedux_5.RunBench(n: 10, expectedSum: 38) is also % 1,267 slower, probably for the same reason.

[Repro Instructions for running benchmarks locally](https://gist.github.com/naricc/efdc186951a912507550509b21fb992b  )

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

**Comment by SamMonoRT** [comment]
@fanyang-mono - please take a look

**Comment by fanyang-mono** [comment]
One of the reasons of the low performance of this benchmark is probably because the multiple usage of `Interlocked.Decrement_int`, since `Interlocked.Decrement_int` itself is 150% slower too.

**Comment by SamMonoRT** [comment]
https://pvscmdupload.blob.core.windows.net/reports/06_09_2021/report_Daily_ca=x64_cb=refs-heads-main_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2021-06-09.html   suggests we improved by almost 50% . We don't have more targetted improvement here for 6.0.0. We will focus energy on aot-wasm microbenchmark improvements.
