### ISSUE TITLE
UTF7 warning unsuppressable

### ISSUE THREAD

**Issue by rjmholt** [dotnet/runtime#41459]
### Description

We're currently migrating our codebase to .NET 5-preview.8.

We have some code that essentially forwards the UTF7 obsoletion message like this:

```csharp
        public Encoding Encoding
        {
            get
            {
                return _encoding;
            }

            set
            {
                if (value == System.Text.Encoding.UTF7)
                {
                    _provider.WriteWarning(PathUtilsStrings.Utf7EncodingObsolete);
                }
                _encoding = value;
            }
        }
```

Following [this doc](https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx#utf-7-code-paths-are-obsolete), I added suppression pragmas around the offending code like this:

```csharp
#pragma warning disable SYSLIB0001
                if (value == System.Text.Encoding.UTF7)
#pragma warning restore SYSLIB0001
```

However, when building, we still hit a build failure:

```
C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShell\src\System.Management.Automation\namespaces\FileSystemProvider.cs(7621,30): error CS0618: 'Encoding.UTF7' is obsolete: 'The UTF-7 encoding is insecure and should not be used. Consider using UTF-8 instead.' [C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
```

I've also tried adding a global suppression to our project:

```xml
  <PropertyGroup>
    <Product>PowerShell</Product>

    ...

    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>

     ...

    <NoWarn>$(NoWarn);SYSLIB0001</NoWarn>
  </PropertyGroup>
```

**EDIT**, I've now also tried this:

```xml
<EnableUnsafeUTF7Encoding>true</EnableUnsafeUTF7Encoding>
```

However, none of these changes seem to work. I've tried doing things like copying the line verbatim from the doc in case there's something funny going on with characters, but nothing seems to work.

Are there any extra steps I might be missing here?

### Configuration

```
> dotnet --version
5.0.100-preview.8.20417.9
> systeminfo.exe | select -skip 2 -First 2
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
> $env:PROCESSOR_ARCHITECTURE
AMD64
```

**Comment by rjmholt** [comment]
Ah I see that in preview.8 the required warning code is `MSLIB0001` not `SYSLIB0001`!

**Comment by GrabYourPitchforks** [comment]
Glad you found the workaround. Also, from that same page, check out the __Recommended action__ section for the recommended way of checking whether an incoming `Encoding` instance is UTF-7:

```cs
void DoSomething(Encoding enc)
{
    // Don't perform the check this way.
    // It produces a warning and misses some edge cases.
    if (enc == Encoding.UTF7)
    {
        // Encoding is UTF-7.
    }

    // Instead, perform the check this way.
    if (enc != null && enc.CodePage == 65000)
    {
        // Encoding is UTF-7.
    }
}
```

**Comment by jeffhandley** [comment]
I'm sorry for the trouble on this, @rjmholt!  I'm glad you figured it out.
