### ISSUE TITLE
Microbenchmark System.Numerics.Tests.Perf_BitOperations.PopCount_ulongis  464 % slower on Wasm

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41454]
Microbenchmark System.Numerics.Tests.Perf_BitOperations.PopCount_ulongis  464 % slower on Wasm vs. desktop interpreter.

[Repro Instructions for running benchmarks locally](https://gist.github.com/naricc/efdc186951a912507550509b21fb992b)

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

**Comment by EgorBo** [comment]
ah, can fix as part of https://github.com/dotnet/runtime/pull/40069

**Comment by SamMonoRT** [comment]
@EgorBo  - was this fixed as part of #40069  If so, please close this issue.

**Comment by naricc** [comment]
Looking at the benchmark results for today an the last several days, it seems like this benchmark is no around 280 % slower on Wasm vs. Desktop interpreter.

[Latest results ](https://pvscmdupload.blob.core.windows.net/reports/10_23_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-10-23.html). I don't know how to link to just this benchmark, so that will load *all* of them, which will take a while.

**Comment by naricc** [comment]
@EgorBo I think we can close this out unless there is any follow up that need to be done?

**Comment by EgorBo** [comment]
@SamMonoRT @naricc https://github.com/dotnet/runtime/pull/40069 wasn't merged so that must be something else I guess.

**Comment by SamMonoRT** [comment]
Let's keep an eye on the results of this benchmark in next 3-4 days, and then close if we determine it is improved. @EgorBo do you think you changes might help make this even more performant ?

**Comment by tannergooding** [comment]
@naricc, is there any update here. Is this something that is going to be worked on for 6.0.0?

If not, I'd like to either move this to `future` or close, as appropriate.

**Comment by naricc** [comment]
@tannergooding This is not being actively worked on for 6.0.0; I am having some issues verifying weather or not is resolved right now. I will move it to future, and then close it when I am able to get the data (if merited).

**Comment by naricc** [comment]
@ilonatommy t looks like this is still happening.

 wasm-interpreter: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_CompliationMode%3dwasm_RunKind%3dmicro%2fSystem.Numerics.Tests.Perf_BitOperations.PopCount_ulong.html

mono desktop interpreter:
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dtrue_RunKind%3dmicro_mono%2fSystem.Numerics.Tests.Perf_BitOperations.PopCount_ulong.html

This doesn't block anything from shipping; it's not clear there is actually anything that can be done about it, although I haven't investigated enough to confirm that.

**Comment by lewing** [comment]
@SamMonoRT lets triage this properly when 8 starts

**Comment by lewing** [comment]
@kotlarmilos is there a status update on this?

**Comment by kotlarmilos** [comment]
The BitOperations have been intrinsified on both platforms in https://github.com/dotnet/runtime/pull/82827. The microbenchmark `System.Numerics.Tests.Perf_BitOperations.PopCount_ulongis` is about 60% slower on the Wasm than on Interpreter.

Is it expected to have decreased performance when running on Wasm?

**Comment by lewing** [comment]
WasmBase was being incorrectly disabled and that was fixed in https://github.com/dotnet/runtime/pull/88523 lets make sure we have accurate numbers for this now

**Comment by radekdoulik** [comment]
@kotlarmilos what is the configuration with  464% perf. Is it aot or interpreter on wasm?

**Comment by lewing** [comment]
@kg is there a jiterpreter intrinsic for i64.popcnt ?

**Comment by lewing** [comment]
> @kg is there a jiterpreter intrinsic for i64.popcnt ?

I see there is

**Comment by kotlarmilos** [comment]
> @kotlarmilos what is the configuration with 464% perf. Is it aot or interpreter on wasm?

@radekdoulik Sorry for the late reply, it is wasm interpreter.

**Comment by lewing** [comment]
We looked into this and consider it closed
