### ISSUE TITLE
ECDsa.ImportSubjectPublicKeyInfo fails for ecPublicKey with algorithm-specific parameters

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/runtime#41458]
I have the following PublicKeyInfo:

```
MIIBKjCB4wYHKoZIzj0CATCB1wIBATAsBgcqhkjOPQEBAiEA/////wAAAAEAAAAAAAAAAAAAAAD///////////////8wWwQg/////wAAAAEAAAAAAAAAAAAAAAD///////////////wEIFrGNdiqOpPns+u9VXaYhrxlHQawzFOw9jvOPD4n0mBLAxUAxJ02CIbnBJNqZnjhE50mt4GffpAEIQNrF9Hy4SxCR/i85uVjpEDydwN9gS3rM6D0oTlF2JjClgIhAP////8AAAAA//////////+85vqtpxeehPO5ysL8YyVRAgEBA0IABNVLQ1xKY80BFMgGXec++Vw7n8vvNrq32PaHuBiYMm0PEj2JoB7qSSWhfgcjxNVJsxqJ6gDQVWgl0r7LH4dr0KU=
```

Importing this public key into an `ECDsa` instance like this:

```csharp
var ecdsa = ECDsa.Create();
ecdsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(publicKey), out int read);
```

fails:

```
Message: 
    System.Security.Cryptography.CryptographicException : ASN1 corrupted data.
Stack Trace: 
    EccKeyFormatHelper.GetSpecifiedECCurveCore(SpecifiedECDomain specifiedParameters)
    EccKeyFormatHelper.GetSpecifiedECCurve(SpecifiedECDomain specifiedParameters)
    EccKeyFormatHelper.GetCurve(ECDomainParameters domainParameters)
    EccKeyFormatHelper.FromECPublicKey(ReadOnlyMemory`1 key, AlgorithmIdentifierAsn& algId, ECParameters& ret)
    KeyFormatHelper.ReadSubjectPublicKeyInfo[TRet](String[] validOids, ReadOnlyMemory`1 source, KeyReader`1 keyReader, Int32& bytesRead, TRet& ret)
    KeyFormatHelper.ReadSubjectPublicKeyInfo[TRet](String[] validOids, ReadOnlySpan`1 source, KeyReader`1 keyReader, Int32& bytesRead, TRet& ret)
    ECDsa.ImportSubjectPublicKeyInfo(ReadOnlySpan`1 source, Int32& bytesRead)

```

The original `PublicKeyInfo` was generated by BouncyCastle.

Is this a bug or am I using the API wrong?

**Comment by bartonjs** [comment]
I think the problem is that your base point is encoded with point compression `03 6B 17 D1 F2  E1 2C 42 47 F8 BC E6 E5
63 A4 40 F2 77 03 7D 81  2D EB 33 A0 F4 A1 39 45 D8 98 C2 96`.  Only uncompressed (04) points are supported.

**Comment by vcsjones** [comment]
> I think the problem is that your base point is encoded with point compression

Beaten by Jeremy (again), but yes, you're hitting this limitation:

https://github.com/dotnet/runtime/blob/0b02200ebc215496fddd228030fccc3bf0b53ce5/src/libraries/Common/src/System/Security/Cryptography/EccKeyFormatHelper.cs#L438-L442

**Comment by vcsjones** [comment]
For what it's worth, this _looks_ like a standard NIST P256 key that's been explicitly encoded. "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296" is the G<sub>x</sub>, "5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b" is B, etc.

If I am right, I think it would make more sense to have BC use named P-256 curve keys.

**Comment by qmfrederik** [comment]
OK, thanks for looking into this. This is the point compression algorithm defined in [section 2.3.3: EllipticCurvePoint-to-OctetString Conversion](https://www.secg.org/SEC1-Ver-1.0.pdf) (page 10)?

Is there a specific reason to not support this (in the sense of, would you accept a PR which did this)?

@vcsjones I'll double-check whether BC uses compression by default, or whether it was for this key only. I'm trying to migrate off of BC, and I'll have to process public keys which were previously generated by BC.

**Comment by vcsjones** [comment]
> This is the point compression algorithm defined in section 2.3.3: EllipticCurvePoint-to-OctetString Conversion (page 10)?

Yes.

> Is there a specific reason to not support this 

I can't speak for the .NET team, but there are two things working against point compression. The first is patent issues, though my understanding is that patents on point compression expired in 2018 (Not a lawyer, etc). The other, likely due to the former, not a whole not of software accepts compressed EC points. (I don't believe Apple's CoreCrypto accepts compressed keys, for example). OpenSSL does (or did at one point...) require re-compiling with a compiler flag to enable working with compressed keys.

I think this would also be non-trivial to implement without "writing cryptography". OpenSSL has `ec_GFp_simple_set_compressed_coordinates` to set compressed points, however I'm unsure how feasible it would be to implement this for Windows, where there are not low-level EC math functions readily available.

**Comment by qmfrederik** [comment]
> I think this would also be non-trivial to implement without "writing cryptography".

OK, makes more sense now. The difficulty appears to be (still in section 2.3.4 of the same document) in step 2.4.3, where you need _may_ to solve a quadratic equation $ z^2 + z = \beta $, but only if $ q = 2^m $ and $ x_P \neq 0 $.

So let me figure out if I really need this (i.e. whether BouncyCastle enables compression by default or now), first.

**Comment by bartonjs** [comment]
Since there hasn't been any activity here in a long time, closing the issue.

As for the meta-question of supporting compressed points: I think it would be difficult to support on Windows and macOS.  Should I be proven wrong there, then we can totally consider it.
