### ISSUE TITLE
Wasm Span Benchmarks over 400 % slower than Desktop Interpreter

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41456]
Several Span benchmarks are over 400 % slower compared to desktop interpreter:

System.Memory.Span<Char>.SequenceCompareTo(Size: 512)
System.Memory.Span<Int32>.SequenceEqual(Size: 512)
System.Memory.Span<Char>.SequenceEqual(Size: 512)
System.Memory.Span<Int32>.EndsWith(Size: 512)
System.Memory.Span<Int32>.StartsWith(Size: 512)

[Repro Instructions for running benchmarks locally](https://gist.github.com/naricc/efdc186951a912507550509b21fb992b  )

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

**Comment by SamMonoRT** [comment]
There has been a few fixes. Seems like we are in reasonable range atm and don't have cycles for more improvement in this area.
https://pvscmdupload.blob.core.windows.net/reports/06_09_2021/report_Daily_ca=x64_cb=refs-heads-main_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2021-06-09.html

Closing this issue. We might reopen a similar one based on when we get the aot-wasm microbenchmarks running.
