### ISSUE TITLE
Microbenchmark System.Buffers.Text.Tests.Utf8ParserTests.TryParseDateTimeOffset is  1,781 % slower on Wasm vs. desktop interpreter

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41451]
Microbenchmark System.Buffers.Text.Tests.Utf8ParserTests.TryParseDateTimeOffset(value: 12/30/2017 3:45:22 AM -08:00) is  1,781 % slower on Wasm vs. desktop interpreter.

[Repro Instructions for running benchmarks locally](https://gist.github.com/naricc/efdc186951a912507550509b21fb992b  )

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

**Comment by BrzVlad** [comment]
Checked locally and wasm interp is 2-2.5 time slower than desktop interp. I don't think this warrants any deeper investigation
