### ISSUE TITLE
Calling CreateFile() API returns ERROR_INVALID_HANDLE in .NET 5-preview.8

### ISSUE THREAD

**Issue by rjmholt** [dotnet/runtime#41477]
### Description

PowerShell is currently migrating to .NET 5-preview.8 from .NET 5-preview.7, with the work being done in https://github.com/PowerShell/PowerShell/pull/13530.

A new error we've hit here occurs in [this code](https://github.com/PowerShell/PowerShell/blob/4e2b6e9540c1946d22664149f0331447ac0bf797/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L584-L607), which looks like this:

```csharp
        private static readonly Lazy<ConsoleHandle> _outputHandle = new Lazy<SafeFileHandle>(() =>
            {
                // We use CreateFile here instead of GetStdWin32Handle, as GetStdWin32Handle will return redirected handles
                var handle = NativeMethods.CreateFile(
                    "CONOUT$",
                    (UInt32)(NativeMethods.AccessQualifiers.GenericRead | NativeMethods.AccessQualifiers.GenericWrite),
                    (UInt32)NativeMethods.ShareModes.ShareWrite,
                    (IntPtr)0,
                    (UInt32)NativeMethods.CreationDisposition.OpenExisting,
                    0,
                    (IntPtr)0);

                if (handle == NativeMethods.INVALID_HANDLE_VALUE)
                {
                    int err = Marshal.GetLastWin32Error();

                    HostException e = CreateHostException(err, "RetreiveActiveScreenBufferConsoleHandle",
                        ErrorCategory.ResourceUnavailable, ConsoleControlStrings.GetActiveScreenBufferHandleExceptionTemplate);
                    throw e;
                }

                return new ConsoleHandle(handle, true);
            }
        );
```

This code remains unchanged since our initial migration to .NET Core, but has suddenly started failing since moving to .NET 5-preview.8.

The API is now setting `err` to `ERROR_INVALID_HANDLE`, causing PowerShell startup to fail.

The actual P/Invoke is [here](https://github.com/PowerShell/PowerShell/blob/4e2b6e9540c1946d22664149f0331447ac0bf797/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L3018-L3028) and looks like this:

```csharp
            [DllImport(PinvokeDllNames.CreateFileDllName, SetLastError = true, CharSet = CharSet.Unicode)]
            internal static extern NakedWin32Handle CreateFile
            (
                string fileName,
                DWORD desiredAccess,
                DWORD ShareModes,
                IntPtr securityAttributes,
                DWORD creationDisposition,
                DWORD flagsAndAttributes,
                NakedWin32Handle templateFileWin32Handle
            );
```

With the value of `PinvokeDllNames.CreateFileDllName` being `api-ms-win-core-file-l1-1-0.dll`.

Another thing to note is that we deliberately use this API over [`GetStdHandle()`](https://docs.microsoft.com/en-us/windows/console/getstdhandle) because we need the unredirected console handle.

I realise this is a fairly obscure usage, but is there any change in .NET that might have affected this? Or possible a recommended better way to do what we're doing here?

### Configuration

- `dotnet` version: 5.0.100-preview.8.20417.9
- AMD64

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
```

**Comment by rjmholt** [comment]
FYI I'm currently trying to take our last working release and migrate that to .NET 5-preview.8 to eliminate the possibility that new changes are to blame

**Comment by rjmholt** [comment]
> FYI I'm currently trying to take our last working release and migrate that to .NET 5-preview.8 to eliminate the possibility that new changes are to blame

Just finished this. Reproduces the same issue.

**Comment by rjmholt** [comment]
This currently appears to be an issue with our csproj and the nature of the executable generated. Changes in the csproj have caused generation of a GUI exe (subsystem header 2) rather than a CUI exe (subsystem header 3).

**Comment by rjmholt** [comment]
We've established that the above was the issue, caused by `<UseWpf>true</UseWpf>` in the csproj. Removing this resolves the issue

**Comment by SteveL-MSFT** [comment]
We can close this as it's not related to this interop call, but instead due to a change in how `<UseWpf>` in the csproj overrides our setting for `<OutputType>Exe</OutputType>` to be a `WinExe` which, of course, means pwsh.exe isn't associated with a console on start and fails on this API call.  Removing `<UseWpf>` in the csproj produces a correct exe type, but we need to validate something else doesn't get broken because of that.

**Comment by SteveL-MSFT** [comment]
Looks like Rob beat me to it while I was typing...
