### ISSUE TITLE
CoreCLR tests on WASM: System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#41471]
### Description

CoreCLR runtime tests failed with this syndrome:
```
Exception:System.FormatException: Input string was not in a correct format.
           at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
           at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
           at System.Int32.Parse(String s)
           at Benchstone.BenchF.Adams.Main(String[] argv)
```
Affected tests are:
- JIT/Performance/CodeQuality/Benchstones/BenchF/Adams/Adams/Adams.sh
- JIT/Performance/CodeQuality/BenchmarksGame/binarytrees/binarytrees-2/binarytrees-2.s
- JIT/Performance/CodeQuality/BenchmarksGame/fasta/fasta-1/fasta-1.sh
- JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot/mandelbrot-7/mandelbrot-7.sh
- JIT/Performance/CodeQuality/BenchmarksGame/pidigits/pidigits-3/pidigits-3.sh
- JIT/Performance/CodeQuality/V8/Richards/Richards/Richards.s
- JIT/Performance/CodeQuality/BenchmarksGame/fannkuch-redux/fannkuch-redux-2/fannkuch-redux-2.sh
- JIT/Performance/CodeQuality/BenchmarksGame/fannkuch-redux/fannkuch-redux-5/fannkuch-redux-5.sh
- JIT/Performance/CodeQuality/SIMD/SeekUnroll/SeekUnroll/SeekUnroll.sh
- JIT/Performance/CodeQuality/BenchmarksGame/n-body/n-body-3/n-body-3.sh
- JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.sh
- JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot/mandelbrot-2/mandelbrot-2.sh
- JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm-3/spectralnorm-3.sh
- JIT/Performance/CodeQuality/BenchmarksGame/fasta/fasta-2/fasta-2.sh
- JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm-1/spectralnorm-1.sh
- JIT/Performance/CodeQuality/SciMark/SciMark/SciMark.sh
- JIT/Performance/CodeQuality/BenchmarksGame/binarytrees/binarytrees-5/binarytrees-5.sh
- JIT/opt/OSR/example/example.sh

### Reproduction Steps

1. Get dotnet/runtime repo
2. Remove the test(s) that you would like to reproduce from `<repo_root>/src/coreclr/tests/issues.targets`
2. Build WASM: `./build.sh --os Browser --arch wasm --subset mono+libs -c Release`
3. Build runtime tests: `cd src/coreclr/ && ./build-test.sh -skipstressdependencies -excludemonofailures os Browser wasm Release`
4. To run all runtime tests, at the end of the runtime tests build log, there is "Example runtest.sh command". Use that command plus `wasm`. For example, for me it was
`./tests/runtest.sh --coreOverlayDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root --testNativeBinDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/obj/coreclr/Browser.wasm.Release/tests --testRootDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release --copyNativeTestBin Release wasm`
5. To run a single test, you could do
```
set CORE_ROOT=<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root     
<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/JIT/Methodical/switch/switch5/switch5.sh
```

### Regression?

No. WASM is a new product.

### Other information

All of the tests mentioned in this issue were failing with the same syndrome. If the root cause of them are different, feel free to split this issue into multiple ones.

**Comment by marek-safar** [comment]
@EgorBo could you help with this issue

**Comment by EgorBo** [comment]
All these tests (benchmarks) scan input args (`string[] args`) and if it's not empty - try to parse args[0] as int (iterations count).
So it's not a `int.Parse` issue, just some garbage (args for v8?) is forwarded.
