### ISSUE TITLE
Investigate nullability of members in System.Data.Common affected by XmlSerializer.Deserialize

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#41497]
also IMO we should file an issue to investigate if this should return nullable here and below

_Originally posted by @krwq in https://github.com/dotnet/runtime/pull/41474#discussion_r478850186_

https://github.com/dotnet/runtime/blob/8e7a2246b7a16b8a2ece50727d02ad113cb4da2f/src/libraries/System.Data.Common/src/System/Data/Common/ObjectStorage.cs#L442

https://github.com/dotnet/runtime/blob/8e7a2246b7a16b8a2ece50727d02ad113cb4da2f/src/libraries/System.Data.Common/src/System/Data/Common/ObjectStorage.cs#L344

https://github.com/dotnet/runtime/blob/8e7a2246b7a16b8a2ece50727d02ad113cb4da2f/src/libraries/System.Data.Common/src/System/Data/Common/SqlUDTStorage.cs#L164

https://github.com/dotnet/runtime/blob/8e7a2246b7a16b8a2ece50727d02ad113cb4da2f/src/libraries/System.Data.Common/src/System/Data/Common/SqlUDTStorage.cs#L191

**Comment by roji** [comment]
I took a quick look at this, and non-nullable seems like the right annotation (though I'm not very familiar with this part of the code base). For example, XMLDiffLoader.ReadOldRowData calls DataColumn.ConvertXmlToObject (the method in question), and assigns its results to `DataColumn[int]`, which is clearly non-nullable (there's a Debug.Assert check for that).

In any case, DataStorage.cs (where this method resides) is internal, and the nullability here doesn't seem to leak anywhere close to public surface APIs, so the importance here is limited and we can always fix in the future.

So I'll go ahead and close this.
