### ISSUE TITLE
Fail: Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41494]
failed in job: [runtime 20200827.91 ](https://dev.azure.com/dnceng/public/_build/results?buildId=791218&view=ms.vss-test-web.build-test-results-tab&runId=24981082&resultId=181115&paneView=debug)

net5.0-Linux-Release-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20200512010618-efb9f14

Error message
~~~
Assert.Equal() Failure
Expected: 2
Actual:   1


Stack trace
   at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 2242
--- End of stack trace from previous location ---
~~~

**Comment by benaadams** [comment]
Seen in https://github.com/dotnet/runtime/pull/41944Libraries Test Run release coreclr Linux x64 Debug https://github.com/dotnet/runtime/pull/41944/checks?check_run_id=1082964411

https://helix.dot.net/api/2019-06-17/jobs/8834aa22-bf48-4428-8299-991159698166/workitems/System.Net.Http.Functional.Tests/console

**Comment by ViktorHofer** [comment]
Closing as there are no hits in the last 7 days.
