### ISSUE TITLE
dll error on ubuntu 18

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#41491]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1065744/dll-error-on-ubuntu-18.html)._

---
<p>I'm getting some odd issues, the sum of which is my dotnet core dll isn't running on my target machine, which is Ubuntu 18.04. I'm using the latest dotent core SDK 3.1</p><p>My csproj starts with: </p><pre>&lt;PropertyGroup&gt;
    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
    &lt;TargetFramework&gt;netcoreapp3.1&lt;/TargetFramework&gt;
    &lt;PublishReadyToRun&gt;true&lt;/PublishReadyToRun&gt;
    &lt;RuntimeIdentifiers&gt;linux-x64&lt;/RuntimeIdentifiers&gt;
 &lt;/PropertyGroup&gt;

</pre><p>and I publish using the command:</p><pre>dotnet publish -c app -r linux-x64 --self-contained true</pre><p>The publish runs fine, but:</p><p>1. no runtimeconfig.json is generated</p><p>2. The dll will not run with the command dotnet app.dll, I get the error:</p><pre>A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in ',filepath&gt;'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the &lt;filepath&gt;.runtimeconfig.json file specifying the appropriate framework.</pre> <p>3. I manaully added a runtimeconfig.template.json, since one wasn't being generated, to see if this resolved things, it did not:</p><pre>{
    &quot;runtimeOptions&quot;: {
      &quot;tfm&quot;: &quot;netcoreapp3.1&quot;,
      &quot;framework&quot;: {
        &quot;name&quot;: &quot;Microsoft.NetCore.App&quot;,
        &quot;version&quot;: &quot;3.1.0&quot;
      },
      &quot;configProperties&quot;: {
        &quot;System.GC.Concurrent&quot;: false,
        &quot;System.GC.Server&quot;: true
      }
    }
  }

</pre><p>Does anyone know what is going on/going wrong - I am stuck.</p> <p><br>Many thanks in advance.</p> <p></p>

---
#### Feedback Bot on 6/4/2020, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/9/2020, 11:27 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by vitek-karas** [comment]
I tried to repro this, but no luck. One observation - did you really meant to specify `-c app` ? `-c` specifies the configuration, which is most typically either `Release` or `Debug`. You can definitely define your own, but it's not very common. That said even with that it worked for me just fine.

If it's possible to share the repro project - that would definitely help.
You can also try to specify `/bl` on the command line and open the resulting msbuild.binlog with https://msbuildlog.com/ - that would show exactly what was going on. The task which creates `.runtime.config` is called `GenerateRuntimeConfigurationFiles`.

**Comment by agocke** [comment]
This looks like it might be https://github.com/dotnet/sdk/issues/12670, I think it should be fixed now.
