### ISSUE TITLE
Calling Latin1 / iso-8859-1 Encoder Convert method iteratively produces different results than Encoding GetBytes on "naughty" string

### ISSUE THREAD

**Issue by kevin-montrose** [dotnet/runtime#415]
> I opened an [identical issue](https://github.com/dotnet/corefx/issues/42751) ([erroneously, it turns out](https://github.com/dotnet/corefx/issues/42733)) on [dotnet/corefx](https://github.com/dotnet/corefx), I'm posting it here and closing it over there to fix my error.

Another bit of odd behavior with [`Encoder`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoder?view=netcore-3.0), this time with the Latin1 encoding.

For the ["naughty" string ](https://github.com/minimaxir/big-list-of-naughty-strings)`@"0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟"` calling `Encoding.GetBytes(...)` produces a different result than iteratively calling `Encoder.Convert(...)`.  I have a [repository with a reproduction](https://github.com/kevin-montrose/Latin1Repro/blob/master/Latin1Repro/Program.cs#L20) (also shows off issue #42750 , but I suspect these are unrelated issues - I just happened to find them at the same time).

For that string, the issue seems to be that `Encoder` doesn't write the final byte during flushing.

Latin1 is sufficiently weird of an encoding that this may be expected?

A smaller reproduction:

```csharp
var encoding = Encoding.GetEncoding("iso-8859-1");
var text = @"0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟";
var destBufferSize = 2;

var encodingBytes = encoding.GetBytes(text);
var encoder = encoding.GetEncoder();

var chars = text.ToCharArray();

var sourceSpan = chars.AsSpan();
var destSpan = new byte[destBufferSize].AsSpan();
var encoderBytes = new List<byte>();

var completed = false;

// write everything in sourceSpan
while (!completed)
{
    var flush = sourceSpan.Length == 0;
    encoder.Convert(sourceSpan, destSpan, flush, out var charsConsumed, out var bytesProduced, out completed);
    encoderBytes.AddRange(destSpan.Slice(0, bytesProduced).ToArray());

    sourceSpan = sourceSpan.Slice(charsConsumed);
}

var eq = encodingBytes.SequenceEqual(encoderBytes);

if (eq)
{
    return;
}

var encodingAsStr = encoding.GetString(encodingBytes);
var encoderAsStr = encoding.GetString(encoderBytes.ToArray());

Console.WriteLine($@"Encoding Convert failure for destBufferSize={destBufferSize} - {encodingBytes.Length}:""{encodingAsStr}"" vs {encoderBytes.Count}:""{encoderAsStr}""");
```

This prints when it (probably) shouldn't.

This behavior is quite sensitive to the value of `destBufferSize`, happening for this particular string at values 2, 4, 5, 8, 10, 20, 40 ,& 41 (note that 42 is the size the destination buffer needs to be for a single `Convert` call to be sufficient).

**Comment by scalablecory** [comment]
@GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Problem seems to be that `Latin1Encoding.GetBytes` doesn't update the `EncoderNLS._charLeftOver` field when a high surrogate character is seen at the end of the input slice. This means that on the next call to `Latin1Encoding.GetBytes`, it will try to fall back the low surrogate in isolation rather than the high + low surrogate together, resulting in an output of `"?"` rather than `"??"`. Problem also repros in .NET Framework 4.8.

This should be fixed by some other improvements I've been working on in the `Latin1Encoding` class. Will add a test case for it separately. Thanks!

**Comment by eberzosa** [comment]
I've been seeing different results with the following code...
`
         Encoder encoder = Encoding.UTF8.GetEncoder();
         encoder.Fallback = EncoderFallback.ReplacementFallback;

         var data = new[] { '1', '2', '\uD804', '3', '4' };

         var bytes = new byte[10];

         encoder.Convert(data, 0, data.Length, bytes, 0, bytes.Length, false, out _, out var byteCount, out _);

         for (var i = 0; i < byteCount; i++) 
            Console.Write(bytes[i].ToString("x") + " "); // Returns 31 32 3f 33 34 in netcore and framework

         Console.WriteLine();

         encoder = Encoding.UTF8.GetEncoder();
         encoder.Fallback = EncoderFallback.ReplacementFallback;

         foreach (var c in data)
         {
            encoder.Convert(new[] { c }, 0, 1, bytes, 0, bytes.Length, false, out var charCount, out byteCount, out _);

            if (charCount >= 1)
               for (int i = 0; i < byteCount; i++)
                  Console.Write(bytes[i].ToString("x") + " ");

            // Returns 31 32 3f 33 34    in framework
            // Returns 31 32 3f 33 3f 34 in netcore`

I think it's related to the _charLeftOver not being reseted either.

**Comment by GrabYourPitchforks** [comment]
@eberzosa - since your issue regards UTF-8 instead of Latin-1 I think it's best if you open a separate tracking issue. The fix would be in a different place if your reported does end up being a bug.

Also, when you file the separate issue if you could provide a compilable self-contained _Program.cs_ that would help. Thanks!

**Comment by eberzosa** [comment]
@GrabYourPitchforks sure thing
