### ISSUE TITLE
Sockets: Reimplement remaining Task-based async methods using SocketAsyncEventArgs 

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#41502]
Most socket Task-based async APIs are implemented using SocketAsyncEventArgs under the covers today.

The few that are not include:

SendToAsync
ReceiveFromAsync
ReceiveMessageFromAsync

These are instead implemented by wrapping the old IAsyncResult-based async methods.

We should change these to use SocketAsyncEventArgs instead.

**Comment by antonfirsov** [comment]
When doing so, we need to review the exceptions thrown by different implementations, and either decide to harmonize (-> break and document) or to keep compatibility. See: https://github.com/dotnet/runtime/issues/41585#issuecomment-683870587

**Comment by antonfirsov** [comment]
@geoffkizer are you actually working on this? If not, I can give it a try.

**Comment by geoffkizer** [comment]
I have a PR in progress for SendTo/ReceiveFrom/ReceiveMessageFrom. I haven't had time to look at it recently. If you'd like to take what I've got and finish it up, you are welcome to.

The other thing we should do here is to audit the code to see if there are any other methods besides this that are still using old IAsyncResult logic under the covers. I know the MultiConnect stuff was, but @stephentoub just fixed this. I think SendFile is another place -- see https://github.com/dotnet/runtime/issues/42591.

There may be others as well, I'm not entirely sure...

**Comment by stephentoub** [comment]
> but @stephentoub Stephen Toub FTE just fixed this

Hasn't quite been merged yet, but will soon.

**Comment by geoffkizer** [comment]
Just looked: DisconnectAsync doesn't have a Task-based version either (like SendFile). We need to add this.

**Comment by stephentoub** [comment]
> Just looked: DisconnectAsync doesn't have a Task-based version either (like SendFile). We need to add this.

That's called out in https://github.com/dotnet/runtime/issues/33417.  It had been its own issue at https://github.com/dotnet/runtime/issues/1608.

**Comment by geoffkizer** [comment]
The other thing we should be looking at here is getting rid of the old IAsyncResult implementations and replacing them with wrappers on top of Task APIs. We should be able to do this for the APIs that already have Task implementations, i.e. Connect/Accept/Send/Receive. 

I thought there was an issue on this but I can't find it at the moment. Will add if necessary.

**Comment by geoffkizer** [comment]
> FYI, that's called out in #33417. 

Yeah, unfortunately, that issue hasn't had API review. I will probably file a separate issue for DisconnectAsync specifically so we can get it through API review quickly.

**Comment by stephentoub** [comment]
> I will probably file a separate issue for DisconnectAsync specifically so we can get it through API review quickly.

Ok, maybe just reopen the original issue #1608.

**Comment by geoffkizer** [comment]
> Ok, maybe just reopen the original issue #1608.

Done

**Comment by antonfirsov** [comment]
I think we should fix #1712 (harden, and re-enable the test `SendReceive.SendToRecvFrom_Datagram_UDP`) before changing anything in SendTo/ReceiveFrom.
