### ISSUE TITLE
Should VXSort go through GCToOsInterface?

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#41515]
`GetEnabledXStateFeaturesHelper` calls into `WszLoadLibraryEx` that is included from some CoreCLR headers.

This is breaking our ability to use vxsort in Native AOT configurations (CoreRT). I assume it also breaks gcsample.

Should this go through GCToOsInterface?

@PeterSolMS @Maoni0

**Comment by PeterSolMS** [comment]
Ah, you mean vxsort should enquire about enabled instruction sets via the GCToOsInterface? I did something like this in the beginning, but there were some objections, so I ended up keeping it local to GC.

**Comment by jkotas** [comment]
I think we should avoid depending on coreclr internals, but I think it is ok for it to be local to the GC otherwise: #41517
