### ISSUE TITLE
Remove unused USE_REFEMIT define in System.Private.DataContractSerialization

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#41512]
`#if USE_REFEMIT` is used in a quite a few source files in DataContractSerialization, but it is never defined in a .csproj.

https://github.com/dotnet/runtime/issues/20131 mentioned it should be removed as it is unused, but that issue was closed because the .NET Native piece of it was resolved, and this unused define was never removed.

We should remove it, so it doesn't continue cluttering up the code and causing confusion when changes need to be made in this area. (For example - https://github.com/dotnet/runtime/pull/41476#discussion_r479255963).

**Comment by seonyounggg** [comment]
Can I try fix this issue?

**Comment by seonyounggg** [comment]
@eerhardt I just made [PR](https://github.com/dotnet/runtime/pull/41664) for this issue. Please check it!
