### ISSUE TITLE
Remove WebRequest from SoundPlayer

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/runtime#41516]
Current implementation of System.Media.SoundPlayer uses WebRequest which is marked obsolete. This usage is allowed by suppress obsolete warning, however the WebRequest can have a performance and memory consumption penalty.

https://github.com/dotnet/runtime/blob/26a71f95b708721065f974fd43ba82a1dcb3e8f0/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L262

https://github.com/dotnet/runtime/blob/26a71f95b708721065f974fd43ba82a1dcb3e8f0/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs#L482

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/76136#issuecomment-1257266336
