### ISSUE TITLE
Consider defaulting AltJIT to all ISAs enabled

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#41518]
The AltJIT allows one to preview the jitted code for other architectures (such as ARM from x64) or platforms (such as Linux from Windows).

However, certain JIT settings, such as the ISAs used, are largely dependent on the machine being run against and so you cannot currently check codegen for something like `X86.Avx2` if your underlying hardware doesn't support it. Nor can you check for something like `Arm.Dp` from a x64 machine.

It would therefore be beneficial to default the AltJIT such that all ISAs are enabled by default. Individual ISAs can then be disabled by using the `COMPlus_Enable{IsaName}=0` flags (e.g. `COMPlus_EnableAvx2=0`).

This will allow codegen via an altjit to be easily checked against multiple different hardware configurations.

category:implementation
theme:altjit
skill-level:beginner
cost:small

**Comment by tannergooding** [comment]
CC. @CarolEidt, @kunalspathak, @echesakovMSFT

**Comment by BruceForstall** [comment]
To be particular, it's only the non-VM-matching, or cross-targeting, altjits where you want this. (It's possible to have same-platform, same-architecture altjit, but more rare these days.)

**Comment by tannergooding** [comment]
It might be beneficial to do it (or have an opt-in) even for same-architecture.

I'm thinking of cases like AVX-512 or SVE, where the amount of hardware we have that supports it is limited but where you might want to observe and do basic validation of the emitted assembly.

**Comment by CarolEidt** [comment]
I've often thought this would be a good idea, but never got around to filing an issue.

> I'm thinking of cases like AVX-512 or SVE, where the amount of hardware we have that supports it is limited but where you might want to observe and do basic validation of the emitted assembly.

IIRC we used to be able to do this, but lost the ability when we added more (and generally better) ISA support.

**Comment by EgorBo** [comment]
It'd be nice to have, I've integrated `AltJIT` into my `Disasmo` add-in for VS2019 but unfortunately it doesn't allow to play with HW intrinsic because of this issue 🙁 
![screenshot](https://user-images.githubusercontent.com/523221/102016714-48fcea00-3d73-11eb-8920-6c88b316ef6b.gif)

**Comment by EgorBo** [comment]
Marking as Future, it's nice to have, but not critical for 6.0 release.
