### ISSUE TITLE
[WASM runtime test infrastucture] Environment variable is not set: 'CORE_ROOT'

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#41520]
### Description
Tests failed with `Environment variable is not set: 'CORE_ROOT'`.

- ilasm/System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.sh
- JIT/CheckProjects/CheckProjects/CheckProjects.sh

### Configuration

1. Get dotnet/runtime repo
2. Remove the test(s) that you would like to reproduce from `<repo_root>/src/coreclr/tests/issues.targets`
2. Build WASM: `./build.sh --os Browser --arch wasm --subset mono+libs -c Release`
3. Build runtime tests: `cd src/coreclr/ && ./build-test.sh -skipstressdependencies -excludemonofailures os Browser wasm Release`
4. To run all runtime tests, at the end of the runtime tests build log, there is "Example runtest.sh command". Use that command plus `wasm`. For example, for me it was
`./tests/runtest.sh --coreOverlayDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root --testNativeBinDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/obj/coreclr/Browser.wasm.Release/tests --testRootDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release --copyNativeTestBin Release wasm`
5. To run a single test, you could do
```
set CORE_ROOT=<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root     
<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/ilasm/System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.sh
```

**Comment by naricc** [comment]
It looks like this test explicitly copies an .il file, and then uses CORE_ROOT to find it. I think changing the tests to copy everything in the test output directory to the wasm file system, and then explicitly propgating the CORE_ROOT variable (with --setenv=VAR=VALUE ) should work.

I'm not sure if this constitutes a wider pattern in the tests and will fix more than just this one. Any idea if that would be the case @trylek?

**Comment by trylek** [comment]
I tried a full-text query over all *.cs and *.il source files under src/tests in the runtime repo and that yielded just 36 references to <code>CORE_ROOT</code>, often with multiple occurrences in the same file so at the first glance I'm expecting just 10~20 tests to be affected by this issue. I suspect that most of these will be safe to mark as WASM-incompatible (e.g. I'm seeing a test using <code>CORE_ROOT</code> to synthesize the path to <code>corerun</code>).

**Comment by SamMonoRT** [comment]
Low priority, moving to 7.0

**Comment by SamMonoRT** [comment]
@naricc - I believe this can be closed ?

**Comment by eduardo-vp** [comment]
My attempt to remove the exclusion of this issue (https://github.com/dotnet/runtime/pull/75363) in issues.targets apparently made this repro again. I got these logs:

- https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/24004/logs/779
- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75363-merge-b69f90659bb244679c/JIT.1/1/console.c9534f1d.log?helixlogtype=result `(CORE_ROOT must be set)`

**Comment by lambdageek** [comment]
This issue, along with the other references to `CheckProjects` in issues.targets can be resolved by changing the `<Issue>` in issues.targets to something like `"tries to access project source code - not supported on mobile and wasm".
The test tries to locate the `src/tests` folder and opening some .csproj files in it.  That is never going to work in scenarios where the app is bundled and run on a simulator, device, or in a sandboxed environment like a browser.
