### ISSUE TITLE
Unable to load shared library 'User32.dll' in aks container

### ISSUE THREAD

**Issue by rcsprakash** [dotnet/runtime#41528]
Hi, 
Facing this issue when we use System.Drawing library in AKS container running on linux.
System.DllNotFoundException: Unable to load shared library 'User32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libUser32.dll: cannot open shared object file: No such file or directory.
Application developed in .netcore

Below my docker file.
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
 WORKDIR /app

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated libgdiplus libc6-dev

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated libx11-dev
	
RUN ln -s /lib/x86_64-linux-gnu/libdl-2.24.so /lib/x86_64-linux-gnu/libdl.so

EXPOSE 80
FROM microsoft/dotnet:2.2-sdk AS build
 WORKDIR /src

**Comment by rcsprakash** [comment]
area-System.Drawing

**Comment by safern** [comment]
@rcsprakash  could you please share a sample code that is causing you to hit this?

**Comment by rcsprakash** [comment]
Hi,
Am using FonetCore to generate pdf from xml document. Attached the sample project. Hope this helps
[WebApplication4.zip](https://github.com/dotnet/runtime/files/5152013/WebApplication4.zip)

**Comment by rcsprakash** [comment]
@safern Any update?

**Comment by safern** [comment]
Hey @rcsprakash -- not yet. We're focusing on 5.0.0 issues at the moment and I have a couple of those on my plate. We will get to this once we focus on 6.0.0 issues. I'll update you whenever that's the case.

**Comment by ericstj** [comment]
I took a look at the repro.  This has nothing to do with System.Drawing.Common.  The load is happening from Fonet.
```
System.DllNotFoundException: Unable to load shared library 'User32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libUser32.dll: cannot open shared object file: No such file or directory
at Fonet.Pdf.Gdi.LibWrapper.GetDC(IntPtr hWnd)
at Fonet.Render.Pdf.FontSetup.AddSystemFonts(FontType fontType)
at Fonet.Render.Pdf.FontSetup..ctor(FontInfo fontInfo, FontType proxyFontType)
at Fonet.Render.Pdf.PdfRenderer.SetupFontInfo(FontInfo fontInfo)
at Fonet.Fo.FOTreeBuilder.Parse(XmlReader reader)
```

Code is here: https://github.com/daniiiol/FO.NET/blob/850a249c994bfb4bbaf15e540304838390c192aa/src/Core/Pdf/Gdi/LibWrapper.cs#L11

This is a Windows-only library.  It won't work on Linux as far as I can tell.  Please file an issue in that library's repository.

**Comment by safern** [comment]
> I took a look at the repro. 

Thanks @ericstj
