### ISSUE TITLE
`string.Replace()` does not recognize the ethiopic colon `፥` on Windows

### ISSUE THREAD

**Issue by eelstork** [dotnet/runtime#41534]
### Description

```cs
var z = "x ፥ y".Replace("፥", "*");

```

Expected: z == "x * y"
Found: z == "x ፥ y" (Windows; unexpected result)
Found: z == "x * y" (macOS, Linux; expected result)

### Configurations

**macOS**
.NET Core SDK, Version:   3.1.300, Commit:    b2475c1295
Mac OS X 10.14 Darwin RID: osx.10.14-x64

**Linux**
NET Core SDK, Version:   3.1.302, Commit:    41faccf259
ubuntu 16.04 Linux RID: ubuntu.16.04-x64

**Windows**
.NET Core SDK, Version:   3.1.401, Commit:    39d17847db
Windows 10.0.18362 Windows RID: win10-x64

### Regression?

I do not know

### Other information

Above was observed via `string.Replace(string, string)`.
Additionally, 

`char z = '፥';` 

produces a compiler error:
(Too many characters in character literal).
This behavior unlike string replace issue, is observed on all platforms.

**Comment by EgorBo** [comment]
verified: not an issue on .NET 5 + Windows since it's ICU based.

**Comment by tarekgh** [comment]
@eelstork I cannot reproduce this problem. looks something weird happening on your environment. Could you please try it on other machine and let's know? Thanks.

**Comment by eelstork** [comment]
@tarekgh well, perhaps that is a good sign.
I will retest this when I have Windows CI setup (hopefully Wednesday).

Do you see a compile error with `char z = '፥'` ? This I could repro on win/macOS.

Ethiopic colon is U+1365

**Comment by svick** [comment]
@eelstork 

> Do you see a compile error with `char z = '፥'` ?

I don't. Are you sure you using U+1365? Or maybe it's some encoding problem with the file you're compiling?

**Comment by eelstork** [comment]
After setting up CI I can see that this is caused by an underlying error in our source.
Still not sure why U+1365 is specifically affected by this, let alone on Windows vs Linux/macOS
Pending, should be okay to close this.
