### ISSUE TITLE
Consider incorporating cbor official spec suite

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#41548]
CBOR has an official spec test suite which validates handful of corner cases: https://github.com/cbor/test-vectors.

In order to fully incorporate that test data as is in `System.Formats.Cbor`'s test project, it would require implementing RFC 7049 [<kbd>**§6 - Diagnostic Notation**</kbd>](https://tools.ietf.org/html/rfc7049#section-6). Diagnostic Notation API will also help comparing the dotnet's cbor implementation with that of other languages which provide APIs for diagnostic notation.

Playground for diagnostics notation and byte-by-byte explanation: http://cbor.me/
Playground's source code in Ruby: [diagnostics notation](https://github.com/cabo/cbor-diag/blob/0a38a7c926e71e1ac6c73a3e15302a9bf9d31962/lib/cbor-diagnostic.rb) and [byte-by-byte explanation](https://github.com/cabo/cbor-diag/blob/0a38a7c926e71e1ac6c73a3e15302a9bf9d31962/lib/cbor-pretty.rb)

**Comment by am11** [comment]
area-System.Security

cc @eiriktsarpalis, @bartonjs, noticed this discrepancy while investigating: https://github.com/eiriktsarpalis/cbor-fuzz/issues/1.

**Comment by charlesroddie** [comment]
@am11 CBOR should be area-System.Formats now

**Comment by jeffhandley** [comment]
@bartonjs @eiriktsarpalis I triaged this into `Future` as a `test enhancement`. Feel free to adjust that triaging if needed.

**Comment by eiriktsarpalis** [comment]
Per the non-goals listed in the [System.Formats.Cbor design document](https://github.com/dotnet/designs/blob/master/accepted/2020/cbor/cbor.md#non-goals), we are currently not planning on supporting diagnostic notation. We should consider ingesting the test suite if we do decide to implement it in the future.

**Comment by eiriktsarpalis** [comment]
I'm going to close this for now.
