### ISSUE TITLE
Error NETSDK1032: The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible

### ISSUE THREAD

**Issue by andersson09** [dotnet/runtime#41556]
### Description

I want to run **Microsoft.ML 1.5.1** in Blazor. When running the application (dotnet run) I get:
"Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'". 

If I add <PlatformTarget>x64</PlatformTarget> to csproj to fix the above issue I receive:
"Error NETSDK1032: The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible."

### Configuration

5.0.100-preview.8.20417.9
Windows 10

### Regression?

This used to work fine with Blazor 3.2.1.

**Comment by CoffeeFlux** [comment]
cc: @lewing

**Comment by marek-safar** [comment]
This is ML.Net issue which could handle this architecture better. It supports only x64/x86 for its runtimes so it rejects wasm. You can skip the check by setting `EnableMLUnsupportedPlatformTargetCheck` to `false` which will probably break some functionality.

**Comment by marek-safar** [comment]
This issue was moved to dotnet/machinelearning#5375
