### ISSUE TITLE
Microsoft.dotnet.build.tasks.packaging should arcade defined properties to calculate the package version

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#41558]
Arcade introduced a bunch of properties like StablizePackageVersion And IsShipping properties to calculate the version for the package.

This package relies on stableVersion and VersionSufix being set in a particular way. coreclr already uses the arcade properties to build the packages, we should modify the targets(GetPackageIdentity, CalculatePackageVersion) in the package to do the same as well 
```
C:\Users\anagniho\.nuget\packages\microsoft.dotnet.build.tasks.packaging\5.0.0-beta.20427.5\build\Packaging.targets(706,5): error : No VersionSuffix was set. Ensure it is set before targets in packaging are ran. [C:\git\runtime\src\libraries\System.Security.AccessControl\pkg\System.Security.AccessControl.pkgproj]
```
cc @ericstj @safern @ViktorHofer

**Comment by ViktorHofer** [comment]
Stumbled upon this recently. I think we should do this as the additional `StableVersion` property in contrast to the Arcade properties is quite confusing.

**Comment by ViktorHofer** [comment]
Closing as we work towards not relying on this package anymore to generate packages.
