### ISSUE TITLE
[Question] Static readonly fields and branch optimization

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#41568]
Does JIT optimize `if` and `switch` statements based on value of **static readonly** field? I understand that value will be available only at runtime, but once the type is loaded and cctor called then the static fields remain unchanged. In this case, constant propagation can be applied and dead branches can be removed.

**Comment by EgorBo** [comment]
@sakno yes it does, e.g.:
```csharp
class Program
{
    private static readonly int Field = 42;

    static void Main()
    {
        for (int i = 0; i < 50; i++)
        {
            Test(); // promote Test to tier1 (from tier0),
                    // Program class is expected to be already
                    // statically inited at that point
            Thread.Sleep(10);
        }

        Console.ReadKey();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Test()
    {
        if (Field == 43)
            throw new ArgumentException();
    }
}
```
Codegen for `Test`:
```asm
G_M24707_IG01:
                                                ;; bbWeight=1    PerfScore 0.00
G_M24707_IG02:
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.00

; Total bytes of code 1, prolog size 0, PerfScore 1.10, (MethodHash=009c9f7c) for method Program:Test()
; ============================================================
```

**Comment by sakno** [comment]
@EgorBo , thanks for clarification! Just a few additional questions:
1. Does JIT eliminate the field from the memory associated with the class itself?
1. What if declaring type is a generic class instantiated several times with a reference type as a generic argument? AFAIK, only value types used as generic argument force JIT to produce several specializations.

**Comment by RamType-0** [comment]
Many thinkable optimization for field is disabled because of we could access it through reflection.
We could rewrite readonly fields by reflection.
Obviously,it is evil for almost any scenario,but I think it is useful for deserialization.

In contrast,optimization for function locals are very aggressive.

**Comment by jkotas** [comment]
> Does JIT eliminate the field from the memory associated with the class itself?

It does not. Note that the memory footprint of data structures that represent fields is a typically lot more than the memory footprint of the static field itself. Removing the field from the memory would not move the needle in the total memory consumption.

> What if declaring type is a generic class instantiated several times with a reference type

This JIT optimization does not kick in this case.
