### ISSUE TITLE
Assembly.GetExecutingAssembly is much slower than typeof(AClass).Assembly

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#41575]
### Description

When they want to query the currently executing assembly, many codebases forgo using the established and clearly-intended `Assembly.GetExecutingAssembly()` but take the type of the class of the method (say `C`) and use `typeof(C).Assembly instead`.

Upon a closer examination, `typeof(C).Assembly` was significantly faster. Getting the executing assembly should be a simple procedure and both methods should take about the same time.

### Configuration

I used BenchmarkDotNet with .NET 5 Preview 8. This is the source:

``` csharp
using System.Reflection;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace ExecutingAssemblyBenchmark
{
    [RankColumn, DisassemblyDiagnoser, MarkdownExporter]
    public class Program
    {
        [Benchmark]
        public Assembly AExA() => Assembly.GetExecutingAssembly();

        [Benchmark(Baseline = true)]
        public Assembly TypeOf() => typeof(Program).Assembly;
        static void Main() => BenchmarkRunner.Run<Program>();
    }
}
```

### Regression?

No, such performance difference is also present in .NET Framework too.

### Data

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.450 (2004/?/20H1)
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.8.20417.9
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40711, CoreFX 5.0.20.40711), X64 RyuJIT
  DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.40711, CoreFX 5.0.20.40711), X64 RyuJIT


```
| Method |       Mean |     Error |    StdDev | Ratio | RatioSD | Rank | Code Size |
|------- |-----------:|----------:|----------:|------:|--------:|-----:|----------:|
|   AExA | 714.030 ns | 9.2375 ns | 8.1888 ns | 76.53 |    4.17 |    2 |      43 B |
| TypeOf |   9.440 ns | 0.2756 ns | 0.4451 ns |  1.00 |    0.00 |    1 |      31 B |

### Analysis

[SonarSource says](https://rules.sonarsource.com/csharp/RSPEC-3902) that `Assembly.GetExecutingAssembly` performs a stack walk. A stack walk however is not necessary; the JIT could optimize `Assembly.GetExecutingAssembly` into getting the assembly of the containing type of the method, similar to `typeof(C).Assembly`.

**Comment by Kirides** [comment]
But (_correct me if i'm wrong_) `Assembly.GetExecutingAssembly()` returns the currently executing assembly, which can be - in case of an inlined methodcall / property access - something different than `typeof(ContainingClass).Assembly`
Which, to me, is different to what you expect it to do.

**Comment by BruceForstall** [comment]
Given that these (currently) have different semantics, requiring different implementations, I'm going to close this.
