### ISSUE TITLE
Clean XmlCharType struct

### ISSUE THREAD

**Issue by RUSshy** [dotnet/runtime#41572]
Hello

This struct looks kinda messy 

https://github.com/dotnet/runtime/blob/503d5602b01c0e362f1636d55da91ff3b8d909d8/src/libraries/System.Private.Xml/src/System/Xml/XmlCharType.cs

- It needs to manually generate a cryptic ``XmlCharType .bin`` file
- It loads it using reflection from ressources
- it's blocking whenever it's first accessed

I suggest:

- only generate a byte array in that file, either static, or a fixed byte array

I can try to send a PR, but i need to fully understand what's the purpose of all these steps first

**Comment by reflectronic** [comment]
Some existing discussion about this file exists at https://github.com/dotnet/runtime/issues/944

**Comment by RUSshy** [comment]
oh i should have checked.. thanks for the link

**Comment by jkotas** [comment]
PR to replace XmlCharType.bin with a ReadOnlySpan static field would be welcomed.
