### ISSUE TITLE
`Assertion: should not be reached` in `mono-threads-coop.h:48` in Blazor WASM application

### ISSUE THREAD

**Issue by JinShil** [dotnet/runtime#41577]
Here's a screenshot of the error message

![image](https://user-images.githubusercontent.com/6023641/91674789-0cff9980-eb75-11ea-8dd1-d37a98e5e2d9.png)

Unfortunately, this is occurring in a relatively large application, and when I try to isolate it to something simple, the symptom vanishes.  As I discover more information, I'll add to the issue.

```
dotnet --version
5.0.100-preview.8.20417.9
```

Microsoft Edge
Version 85.0.564.41 (Official build) (64-bit)

**Comment by marek-safar** [comment]
@vargaz could you have a look

**Comment by JinShil** [comment]
This issue was caused by a typo in my code that resulted in an infinite recursion.  The recursion grew the stack beyond its limits and began overwriting memory until the program crashed with the error in the original post.  #41673 captures a potential solution.  Unfortunately, stepping through the program in Visual Studio's debugger did not reveal this issue, leading me to believe the Visual Studio WASM debugger still needs some work.
