### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41579]
failed in job: [runtime-libraries outerloop 20200830.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=794139&view=ms.vss-test-web.build-test-results-tab&runId=25109996&resultId=103305&paneView=debug)

net5.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-bfcd90a-20200127194925

Error message
~~~
System.TimeoutException : Task timed out after 00:00:05


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 301
--- End of stack trace from previous location ---
~~~

**Comment by antonfirsov** [comment]
First hit on `2020-07-17`. 5 hits in the last 30 days on Linux machines. Might be related to recent socket changes, therefore probably worth an investigation.

**Comment by aik-jahoda** [comment]
The run from `2020-07-17` is only fail on Windows, the other failures is  Linux. I'll try to reproduce.

**Comment by aik-jahoda** [comment]
On CI it fails on preview 5. 
Locally it passes 111 036 test in row.

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210428.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1111562&view=ms.vss-test-web.build-test-results-tab&runId=33890518&resultId=103930&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
 -System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success
```

**Error message:**
```
System.TimeoutException : The operation has timed out.


Stack trace
   at System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 301
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Failures during 2/23-5/10 (incl. PRs):

Date | Build / PR | OS
-- | -- | --
3/17 | Official run | Ubuntu.1910.Amd64.Open
3/26 | Official run | Windows.10.Amd64.Server19H1.Open
3/27 | Official run | Windows.Server.Core.1909.Amd64.Open
4/2 | Official run | Alpine.312.Amd64.Open
4/4 | PR #50545 | Windows.10.Amd64.Server19H1.ES.Open
4/4 | Official run | Windows.7.Amd64.Open
4/6 | PR #50763 | Windows.Nano.1809.Amd64.Open
4/18 | PR #51212 | Windows.10.Amd64.Server19H1.ES.Open
4/28 | Official run | Windows.7.Amd64.Open

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210516.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1141075&view=ms.vss-test-web.build-test-results-tab&runId=34590410&resultId=103540&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7

- System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success

```
**Error message:**
```
System.TimeoutException : The operation has timed out.


Stack trace
   at System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 304
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210622.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1199070&view=ms.vss-test-web.build-test-results-tab&runId=35939822&resultId=103040&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_release-(Alpine.312.Arm64.Open)ubuntu.1804.armarch.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-arm64v8-20200602002604-25f8a3e

- System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success

```
**Error message:**
```
System.TimeoutException : The operation has timed out.


Stack trace
   at System.Net.Sockets.Tests.SelectTest.Select_AcceptNonBlocking_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs:line 304
--- End of stack trace from previous location ---
```
