### ISSUE TITLE
SocketsHttpHandler.PlaintextFilter isn't implemented for HTTP/1.1 connections

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#41573]
### Description

The only place this setting is used is here:

https://github.com/dotnet/runtime/blob/fd9d2baee8c59e23959084ecd0e962ed61def65a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L616

This is an HTTP2-specific path and won't handle the case where we don't try to make an HTTP2 connection.

Also, there seem to be no tests for this feature. We need to add tests here.

### Regression?

No (new API in 5.0)

**Comment by karelz** [comment]
Triage: With Connection Abstractions being pulled out of 5.0, there is nothing to do in 5.0. Moving to 6.0.
If we decide to add additional callback in 5.0, then this would be part of that work in 5.0.

**Comment by geoffkizer** [comment]
Closing since this was cut from 5.0.
