### ISSUE TITLE
System.Numerics.Vectors binding redirect missing

### ISSUE THREAD

**Issue by jc1001** [dotnet/runtime#41597]
### Description
I have a .NET Core 2 application that is targeting the full .NET Framework (v4.8).
It hosts a web server (using HttpSys) that exposes a SignalR hub.
I can make a successful call from a client (in this case a .NET console application) to the SignalR hub.
Both the client and the server applications are making use of the new "SDK-style" projects.

When I upgrade the [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/1.7.1) library on the server to v1.7.1, the connection call from the client application to the SignalR hub on the server fails with a WebSocketException.

Using the fusion log viewer, I've traced the problem to a missing binding redirect - the server code is trying to load System.Numerics.Vectors v4.1.3, while the output directory contains v4.1.4.  If I add the required binding redirect manually in the app.config, everything works as expected.

Fusion log viewer:
![Fusion log viewer](https://user-images.githubusercontent.com/15125812/91730116-d2622500-eba5-11ea-8e89-760dc0be5937.png)

Binding redirect:
![Binding redirect](https://user-images.githubusercontent.com/15125812/91730130-d8580600-eba5-11ea-9d06-3684d53788ab.png)

I had a look (and tried the suggestions) in the following issues, but did not manage to solve the problem:
https://github.com/dotnet/runtime/issues/27506
https://github.com/dotnet/runtime/issues/26370
https://github.com/dotnet/sdk/issues/901

### To Reproduce
I have attached a sample solution that reproduces the problem.
[SignalRBug.zip](https://github.com/dotnet/runtime/files/5150848/SignalRBug.zip)

The solution contains 2 projects: "Client" and "Server".
An instance of "Server" must be running (hosting on http://localhost:8080) before you can execute "Client".
The example (as attached) will run without any errors.

When you edit the Server.csproj file to include the latest version of the System.Collections.Immutable library, the client application will fail as described above.

### Configuration
* .NET Framework 4.8
* Microsoft Visual Studio Enterprise 2019, Version 16.7.1
* Windows 10, version 2004 (Build: 19041.450)

Thank you. If you require any additional information, please let me know.

**Comment by tannergooding** [comment]
CC. @ericstj.

Seems devs are still having issues with System.Numerics.Vectors bindings out of the box, is there anything we can do here to improve the situation so the default path "just works"?

**Comment by ericstj** [comment]
BindingRedirects will always be required when using nuget packages on desktop.  Usually MSBuild will automatically detect when these are needed, but it is missing the case for System.Numerics.Vectors here. 

This is because the conflict is coming from the two assemblies:
System.Memory -> System.Numerics.Vectors, Version=4.1.4.0
System.Net.WebSockets.WebSocketProtocol -> System.Numerics.Vectors, Version=4.1.3.0

The version of System.Net.WebSockets.WebSocketProtocol referenced is 4.5.1 from Microsoft.AspNetCore.WebSockets.

That version of WebSocketProtocol uses a different reference assembly than implementation and its reference assembly does not use System.Numerics.Vectors.  If you reference a newer version of System.Net.WebSockets.WebSocketProtocol the problem goes away:
```
	<PackageReference Include="System.Net.WebSockets.WebSocketProtocol" Version="4.7.1" />
```

**Comment by jc1001** [comment]
Thank you for the detailed (and quick) response.  I can confirm that my example application is working when I add the reference to the later version of `System.Net.WebSockets.WebSocketProtocol`.  

I'll close this issue and reference the answer on the aspnetcore project (where I initially logged the [issue](https://github.com/dotnet/aspnetcore/issues/24998)) - hopefully they can update the necessary NuGet packages to the working versions.  If not, I can always use the (newer reference) workaround.
