### ISSUE TITLE
System.Drawing.Graphics DrawImage(Image, Rectangle) doesn't fit the picture perfectly.

### ISSUE THREAD

**Issue by kolya5544** [dotnet/runtime#41594]
### Description

I was trying to change the size of a picture. I used `Graphics`, and DrawImage. The output is not correct, while input is correct.
The code is:
```
            //Generating random Bitmap
            Random rng = new Random();
            Bitmap bmp = new Bitmap(15, 15);
            for (int y = 0; y<bmp.Height; y++)
            {
                for (int x = 0; x<bmp.Width; x++)
                {
                    int color = rng.Next(0, 256);
                    bmp.SetPixel(x, y, Color.FromArgb(color, color, color));
                }
            }
            bmp.Save("TEST.png");

            //Trying to change the size
            Bitmap output = new Bitmap(bmp.Width * 5, bmp.Height * 5);
            var graphics = Graphics.FromImage(output);
            graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.NearestNeighbor;
            graphics.DrawImage(bmp, new Rectangle(Point.Empty, output.Size));
            output.Save("OUTPUT.png");
```
What did I expect:
DrawImage(Image, Rectangle) to fit the picture entirely inside the rectangle, as stated in docs: `Draws the specified Image at the specified location and **with the specified size.**`
What am I seeing:
DrawImage(Image, Rectangle) draws the picture, but it's off. The picture itself lacks several pixels to the right and to the top. At the bottom and to the right, there are transparent pixels (look at attachments for an example)
![image](https://user-images.githubusercontent.com/20096248/91728457-c5e0cb00-ebab-11ea-8f9b-031d21e66b7d.png)

### Configuration
Project is .NET Core 3.1, problem persists in .NET Framework 4.5.
Windows 10 Version 10.0.18362.1016 x64
It should not be specific to an OS.

### Other information
Changing the location of drawn picture from (0;0) `Point.Empty` to (1;1) `new Point(1;1)` results in several transparent pixels on all sides. Example:
![image](https://user-images.githubusercontent.com/20096248/91728728-2e2fac80-ebac-11ea-9c70-da405099a60d.png)

It's not affected by NearestNeighbor option.

The original bitmap (`bmp`) is entirely correct, is saved correctly  and doesn't have any transparent pixels.

**Comment by kolya5544** [comment]
Setting PixelOffsetMode of Graphics object to HighQuality seems to completely resolve the problem.

**Comment by JeremyKuhne** [comment]
See the comment [above](https://github.com/dotnet/runtime/issues/41594#issuecomment-683815299) for a resolution.
