### ISSUE TITLE
Support Enumerable.Count(this IEnumerable enumerable) for non-generic enumerable in runtime

### ISSUE THREAD

**Issue by ivanivanyuk1993** [dotnet/runtime#41598]
# Support Enumerable.Count(this IEnumerable enumerable) for non-generic enumerable in runtime

* [x] Proposed

## Summary
[summary]: #summary

Please Support Enumerable.Count(this IEnumerable enumerable) for non-generic enumerable in runtime

## Motivation
[motivation]: #motivation

I have use case
```cs
private PropertyGetterOrConstant<TEntity> GetCountPropertyGetterOrConstant(PropertyGetInfoProto propertyGetInfoProto)
{
    var countPropertyGetterOrConstant = GetPropertyGetterOrConstant(propertyGetInfoProto.Count);

    PropertyGetterOrConstant<TEntity> resultPropertyGetterOrConstant;
    if (countPropertyGetterOrConstant.IsConstant)
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            ((IEnumerable) countPropertyGetterOrConstant.Constant).OfType<object>().Count()
        );
    else
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            entity => ((IEnumerable) countPropertyGetterOrConstant.Getter!(entity)).OfType<object>().Count()
        );

    return resultPropertyGetterOrConstant;
}
```
I have to either use
```cs
.OfType<object>()
```
which effectively adds O(n) complexity, because in my use case IEnumerable can be of primitive types
or add extension method to my code
```cs
public static class EnumerableExtensions
{
     public static int CountNonGeneric(this IEnumerable source)
     {
         if (source is null)
         {
              throw new ArgumentNullException(nameof(source));   
         }
         
         if (source is ICollection collection)
         {
              return collection.Count;   
         }
         
         int count = 0;
         IEnumerator e = source.GetEnumerator();
         checked
         {
             while (e.MoveNext())
             {
                 count++;
             }
         }

        return count; 
     }
}
```
I think it is logical for something like this extension method to exist in runtime

**Comment by canton7** [comment]
> or support Enumerable.Count(this IEnumerable enumerable)

I don't follow I'm afraid: doesn't this already exist? 

What would your ICountable interface look like? How would it differ from ICollection? Which other interfaces if any would implement it?

What's actually wrong with the way that Enumerable.Count is implemented today? It makes sense to me that it first checks whether the object knows its own length, and then takes the slow route of calculating the length if not. It'd an unfortunate bit of legacy that we have both `ICollection` and `ICollection<T>`, but I don't think adding more interfaces is going to help anything here. Type checks are cheap.

**Comment by ivanivanyuk1993** [comment]
> > or support Enumerable.Count(this IEnumerable enumerable)
> 
> I don't follow I'm afraid: doesn't this already exist?
> 
> What would your ICountable interface look like? How would it differ from ICollection? Which other interfaces if any would implement it?
> 
> What's actually wrong with the way that Enumerable.Count is implemented today? It makes sense to me that it first checks whether the object knows its own length, and then takes the slow route of calculating the length if not. It'd an unfortunate bit of legacy that we have both `ICollection` and `ICollection<T>`, but I don't think adding more interfaces is going to help anything here. Type checks are cheap.

Enumerable.Count() supports generic enumerable IEnumerable<TSource>, hence I have to use .OfType<object>(), which effectively add O(n) complexity to my case

**Comment by canton7** [comment]
@ivanivanyuk1993 

So, add the following extension method to your codebase?

```cs
public static class EnumerableExtensions
{
     public static int CountNonGeneric(this IEnumerable source)
     {
         if (source is null)
         {
              throw new ArgumentNullException(nameof(source));   
         }
         
         if (source is ICollection collection)
         {
              return collection.Count;   
         }
         
         int count = 0;
         IEnumerator e = source.GetEnumerator();
         checked
         {
             while (e.MoveNext())
             {
                 count++;
             }
         }

        return count; 
     }
}
```

If that's not what you want, please answer the other questions I asked above.

(Note that if you used `collection.Cast<object>().Count()` instead of `OfType<object>()`, then it becomes `O(n)` only if the collection contains value types: if it contains reference types, then `Cast<object>()` is free)

**Comment by ivanivanyuk1993** [comment]
> What's actually wrong with the way that Enumerable.Count is implemented today? It makes sense to me that it first checks whether the object knows its own length, and then takes the slow route of calculating the length if not. It'd an unfortunate bit of legacy that we have both `ICollection` and `ICollection<T>`, but I don't think adding more interfaces is going to help anything here. Type checks are cheap.

```cs
ICollection.Count
IEnumerable<TSource>.Count()
IIListProvider<TSource>.GetCount()
```
Are not uniform, can not be passed to methods that need only Count(), it is more logical to have
```cs
public interface ICountable
{
    public int Count();
}
public interface ILongCountable
{
    public long CountLong();
}

ICollection : ICountable // It is enough to add method that returns its Count property to implement interface
IEnumerable<TSource> : ICountable // It may even be unnecessary to have every enumerable to implement ICountable
IIListProvider<TSource> : ICountable // It is enough to add method, which will return listProv.GetCount(onlyIfCheap: false)
```

**Comment by ivanivanyuk1993** [comment]
> @ivanivanyuk1993
> 
> So, add the following extension method to your codebase?
> 
> ```cs
> public static class EnumerableExtensions
> {
>      public static int CountNonGeneric(this IEnumerable source)
>      {
>          if (source is null)
>          {
>               throw new ArgumentNullException(nameof(source));   
>          }
>          
>          if (source is ICollection collection)
>          {
>               return collection.Count;   
>          }
>          
>          int count = 0;
>          IEnumerator e = source.GetEnumerator();
>          checked
>          {
>              while (e.MoveNext())
>              {
>                  count++;
>              }
>          }
> 
>         return count; 
>      }
> }
> ```
> 
> If that's not what you want, please answer the other questions I asked above.
> 
> (Note that if you used `collection.Cast<object>().Count()` instead of `OfType<object>()`, then it becomes `O(n)` only if the collection contains value types: if it contains reference types, then `Cast<object>()` is free)

I can and I will, but shouldn't it be in runtime anyway? Isn't it logical?

**Comment by ivanivanyuk1993** [comment]
> (Note that if you used `collection.Cast<object>().Count()` instead of `OfType<object>()`, then it becomes `O(n)` only if the collection contains value types: if it contains reference types, then `Cast<object>()` is free)

If I understand correctly, it won't in my case, because my code can receive
```cs
IEnumerable<int>
IEnumerable<string>
IEnumerable<SomeClass>
etc
```
which can not be cast to typedSource by this code
```cs
IEnumerable<TResult> typedSource = source as IEnumerable<TResult>;
if (typedSource != null)
{
    return typedSource;
}
```

**Comment by canton7** [comment]
Don't worry about `IIListProvider`: that's part of Linq's internal optimizations, but if you're working with a non-generic `IEnumerable` then you won't be using the other parts of Linq anyway, so you won't hit the code paths which create an `IIListProvider`.

Yes we have both `ICollection<T>.Count`, `ICollection.Count` and `Enumerable.Count`, but that's where we are. It's very rare these days to be working with an `IEnumerable` or an `ICollection`: generics came out around 14 years ago, and while you still sometimes find yourself working with the non-generic versions, it's really rather rare.

Forcing every single object which implements `IEnumerable` to implement this new `Count()` method would be a massive, world-breaking change. Every single person who has written their own collection will find that it suddenly fails to compile. This is not going to happen.

You might be able to get away with adding a new method to `IEnumerable` using DIM, but given that the team are very reluctant to add a default implementation for `IEnumerator.Reset`, I doubt very much this would happen. Besides, the approach chosen by Linq was to use extension methods for things like this, and having `Count()` be the odd one out (having both `Enumerable.Count` and `IEnumerable.Count`) would be very inconsistent and confusing.

So, we're left with an `Enumerable.CountNonGeneric()` extension method (you might be able to get away with calling it `Enumerable.Count(this IEnumerable source)`, I'm not entirely sure what the rules are which govern which overload would be chosen). This is something which *could* be added: the question is whether it's worth the effort of design, implementation, testing, documentation, support, given that it will be probably very rarely used, and it's very easy to define your own if you do need it.

**Comment by canton7** [comment]
> 
> 
> > (Note that if you used `collection.Cast<object>().Count()` instead of `OfType<object>()`, then it becomes `O(n)` only if the collection contains value types: if it contains reference types, then `Cast<object>()` is free)
> 
> If I understand correctly, it won't in my case, because my code can receive
> 
> ```cs
> IEnumerable<int>
> IEnumerable<string>
> IEnumerable<SomeClass>
> etc
> ```
> 
> which can not be cast to typedSource by this code
> 
> ```cs
> IEnumerable<TResult> typedSource = source as IEnumerable<TResult>;
> if (typedSource != null)
> {
>     return typedSource;
> }
> ```

Thanks to covariance, [`source as IEnumerable<object>` succeeds](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKGIAYACY8gOgGEB7AGy7gGMYASw6YoAbhr0m5ACwTajZiwAygzAEd5k0gGYGAbxoNjTUqQNGTVgG4QEDAB4MAvA0xwA7gG0AugYYARAEMAL7yVlYOLAAqcLAAPADywABW/DAAfAAUAJThJiE0hdSSeswAbKYMAKIO8KLCojSG1FbEZeSVxDIMsQnR2TAAFoJQ0npqAA7oMDmWxi0RbeQAnFlTMwyj4/EDeSbzoUVAA===).

**Comment by ivanivanyuk1993** [comment]
I think it is best to use extension method in my case, as stated in https://github.com/dotnet/runtime/issues/41598#issuecomment-683858756, but it would still be nice if runtime had it

**Comment by canton7** [comment]
Great, it's good to nail down exactly what is being proposed. Do you mind updating your initial post, so it's clear to others reading this issue?

**Comment by ivanivanyuk1993** [comment]
> Great, it's good to nail down exactly what is being proposed. Do you mind updating your initial post, so it's clear to others reading this issue?

Yes, I will do it now

**Comment by adamsitnik** [comment]
Hi @ivanivanyuk1993 

Thank you for your proposal. 

> I have to either use `.OfType<object>()`

You should most probably use `.Cast<object>` as `OfType` handles `nulls` differently.

> which effectively adds O(n) complexity

Your code is reflection heavy and I would be surprised to see `OfType<object>()` being hot in your profiles. Have you considered using [source generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) and give up on using reflection? This would most probably be the best solution performance-wise.

We (.NET Team) don't prioritize investing in the non-generic collection and historically LINQ never had any non-generic methods. Since this is rather a niche example and you can easily write an extension method on your own, I would be inclined to close this issue.

Thanks,
Adam
