### ISSUE TITLE
Remove dotnet5* feeds from NuGet.config in master

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#41593]
The dotnet5* feeds should be removed as soon as all dependencies are available in the dotnet6* feeds. If that's already the case, it should be done now.

cc @dotnet/runtime-infrastructure

**Comment by safern** [comment]
@mmitche do you know when would this be possible? I guess we can already put up a PR to try it out.

**Comment by mmitche** [comment]
Not sure. Putting up a PR and then identifying which packages need to flow is probalby best.
