### ISSUE TITLE
MaxWorkingSet supported platforms

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#41595]
https://github.com/dotnet/runtime/blob/3130ac980c97c0664eddb04411f8f765a9f908d8/src/libraries/System.Diagnostics.Process/ref/System.Diagnostics.Process.cs#L45

The code specifies supported platforms as Windows only.

However, the [documentation](https://github.com/dotnet/docs/blob/3588fdadac34bee137fe519d50c9a187d704d1fd/docs/core/compatibility/unsupported-apis.md) mentions it throws in Linux only, which means both Windows and macOS are supported.

I think macOS should be missing in either the documentation or the supported platforms attribute.

**Comment by krwq** [comment]
Seems OSX is using BSD code and BSD seems to be supporting MaxWorkingSet:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj#L288

probably the attribute should be added then, not sure if this qualifies as 5.0 bug.

**Comment by krwq** [comment]
@terrajobst any clues how much do we want to have SupportedOSPlatformAttribute up to date for 5.0?

**Comment by terrajobst** [comment]
From looking at [the code](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.BSD.cs#L62-L63) it seems the MaxWorkingSet is only supported for the current process and throws PNSE for all other platforms. That's why the tool still flagged the API as not being supported.

I'd say based [on our principles](https://github.com/dotnet/designs/blob/master/accepted/2020/windows-specific-apis/windows-specific-apis.md#partially-supported-apis) it seems we should be marking this API as supported on `macOS`.

**Comment by terrajobst** [comment]
> @terrajobst any clues how much do we want to have SupportedOSPlatformAttribute up to date for 5.0?

The ones we put should ideally be a 100% correct, but I don't think of bugs like this as ship stoppers. In fact, I'm quite certain we'll have to tweak some of them based on customer feedback.

**Comment by jeffhandley** [comment]
I would be supportive of adding `[SupportedOSPlatform("macos")]` to this API. I recommend we go ahead and get that fix into master and request approval for an RC2 port this week.

**Comment by krwq** [comment]
Ok looking again this looks like for OSX/BSD it has only limited support (only works for the current process) so I'm leaning toward updating docs rather than adding attribute

**Comment by eiriktsarpalis** [comment]
Do we have a platform identifier for FreeBSD? We should also add an attribute for that if that's the case.

**Comment by jeffhandley** [comment]
Testing of this fix surfaced https://github.com/dotnet/roslyn-analyzers/issues/4168; these annotations are currently being ignored because of the assembly-level `[UnsupportedOSPlatform("browser")]` attribute.

We are going to revisit the analyzer logic for the scenario.

**Comment by jeffhandley** [comment]
I am leaning toward fixing this only in 6.0.0 without porting the fix into 5.0.0. While it's unfortunate, the impact seems low overall--it only affects 2 property setters and only surfaces on 2 platforms.  This was a good find, @Youssef1313; I presume you found it by way of reading code and documentation--is that right?

If we ship 5.0 with this as a known issue, the workaround will be very straightforward -- to wrap calls to set these properties on `macos` or `freebsd` with `#pragma warning disable CA1416`.

@terrajobst also commented above that he would not consider this release-blocking.  @adamsitnik / @eiriktsarpalis, what do you think?

**Comment by adamsitnik** [comment]
> what do you think?

In my opinion, it's also not release-blocking.

> wrap calls to set these properties on `macos` or `freebsd` with `#pragma warning disable CA1416`

@jeffhandley Thank you for providing the workaround. Anyone who is going to hit this issue with 5.0 and search for it on the internet should be unblocked thanks to that!

**Comment by Youssef1313** [comment]
> @Youssef1313; I presume you found it by way of reading code and documentation--is that right?

Yes I just came across that doc page and wanted to check its accuracy. So I took some random APIs from the doc and compared them with the code here.

**Comment by jeffhandley** [comment]
Thanks, all.  I've moved this to 6.0.0 and I will close the 5.0-rc2 port PR without merging it.
