### ISSUE TITLE
SignedCms supported platforms

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#41596]
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Security.Cryptography.Pkcs/ref/System.Security.Cryptography.Pkcs.cs#L232-L256

The supported OS platforms attribute isn't specified here. However, the [documentation](https://github.com/dotnet/docs/blob/3588fdadac34bee137fe519d50c9a187d704d1fd/docs/core/compatibility/unsupported-apis.md) states that it's not supported on **all** platforms.

**Comment by krwq** [comment]
`System.Security.Cryptography.Pkcs.CmsSigner..ctor(System.Security.Cryptography.CspParameters)` [will always throw](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs#L63)
`System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(System.Security.Cryptography.Pkcs.CmsSigner,System.Boolean)` [looks like it will just work](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs#L293) also tests don't seem to be disabled for any of the platforms
`System.Security.Cryptography.Pkcs.SignerInfo.ComputeCounterSignature()` [will always throw](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs#L294) - the doc doesn't mention the specific overload but other overload (taking CmsSigner) seem it should just work

we should update the docs to have this information accurate

**Comment by krwq** [comment]
I'm marking as 5.0 since it's doc issue and seems simple enough

**Comment by krwq** [comment]
I am not sure if we want to keep attributes up to date or not, I'll try to find the answer to that

**Comment by krwq** [comment]
@Youssef1313 is the doc fix ok here as a solution? can the issue be closed?
