### ISSUE TITLE
JsonIgnoreCondition.WhenWritingDefault and double

### ISSUE THREAD

**Issue by steveoh** [dotnet/runtime#41630]
### Description

```csharp
// startup
.AddJsonOptions(options => {
  options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
  options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull & JsonIgnoreCondition.WhenWritingDefault;
  options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
});

// ...

[DefaultValue(typeof(decimal), "-1")]
[DefaultValue(-1.0)]
[DefaultValue(-1D)]
public double Prop { 
	get => _prop;
    set => _prop = Math.Round(value, 2);
}
```

When the prop is set to -1, which is the default value, the property is serialized when `JsonIgnoreCondition.WhenWritingDefault` is set. I would expect that property to not be serialized.

### Configuration

osx catalina x64
5.0.100-preview.8.20417.9

**Comment by pinkfloydx33** [comment]
The serializer only looks at the actual default value of the type, meaning `default(T)`. It doesn't look at the `DefaultValueAttribute`

https://github.com/dotnet/runtime/blob/756addda8cf593faf696602d8a9dfef759423849/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs#L137-L138

Aside: your use of `&` in `JsonIgnoreCondition.WhenWritingNull & JsonIgnoreCondition.WhenWritingDefault` is a little weird. That equates to `3&2`==`2` which equals `WhenWritingDefault`. Assuming you meant to use `|` I wanted to point out that it's not a `Flags` enum; it can only ever be one or the other.

**Comment by steveoh** [comment]
Ok thank you for clearing up that misconception. How do I then use both behaviors of ignoring nulls and defaults? If I set ignorenullvalues I am greeted with `System.InvalidOperationException: 'IgnoreNullValues' and 'DefaultIgnoreCondition' cannot both be set to non-default values.` Do I need to write my own converters?

**Comment by pinkfloydx33** [comment]
I believe you want `JsonIgnoreCondition.Always`

**Comment by layomia** [comment]
@steveoh @pinkfloydx33 , the setting you want is `JsonIgnoreCondition.WhenWritingDefault`. This will ignore both `null` for nullable types and `default(T)` for non-nullable types. `JsonIgnoreCondition.WhenWritingNull` will ignore only `null` properties. Please let us know if you still face issues with this.

wrt. using `DefaultValueAttribute` or a similar mechanism to specify a custom default value, that is being tracked by https://github.com/dotnet/runtime/issues/36236. Will close this issue as a duplicate.

**Comment by pinkfloydx33** [comment]
@layomia what is the behavior for `Always`? I'd expect that to behave how you describe `WhenWritingDefault`. Or is that a Serialize vs. Deserialize thing?

**Comment by layomia** [comment]
@pinkfloydx33 - [`JsonIgnoreCondition.Always`](https://github.com/dotnet/runtime/blob/3a94b2c5a8dfbe570922d1962bc4a95dfe103da7/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonIgnoreCondition.cs#L19-L22) means always ignore when serializing or deserializing. This is the default value of [`JsonIgnoreAttribute.Condition`](https://github.com/dotnet/runtime/blob/3a94b2c5a8dfbe570922d1962bc4a95dfe103da7/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Attributes/JsonIgnoreAttribute.cs#L16), but it is not a valid value for `JsonSerializerOptions.DefaultIgnoreCondition` - it doesn't make sense to ignore all properties for both deserialization and serialization across the entire object graph. 

We'll add documentation for all of this behavior - https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-how-to.
