### ISSUE TITLE
superpmi: Ensure SuperPMI works well with crossgen2

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#41639]
This includes both collection and replay, including both assertion checking replay and asm diffs replay.

This issue also includes any documentation required for describing this scenario.

Issue https://github.com/dotnet/runtime/issues/38430 describes various problems encountered trying to use SuperPMI with crossgen2. This issue is more specifically concerned with tracking the SuperPMI work and documentation required to make this work -- these two issues might be considered duplicates, but I didn't want to derail the conversation happening there.

Minimally, it seems that src\coreclr\src\ToolBox\superpmi\readme.md should be updated with directions appropriate for crossgen2. Also, src\coreclr\scripts\superpmi.py should be taught new things to make this path as simple as possible. Ideally, the superpmi tools themselves would "just work" without unnecessary command-line arguments, etc.

category:eng-sys
theme:super-pmi
skill-level:beginner
cost:small

**Comment by sandreenko** [comment]
@davidwrighton I was trying to use `--jitpath ` to run the spmi collector directly but it was showing strange results, 
the default (no spmi collection) gave me methods from 0 to 426.

spmi counter (counts how many times we have called each Jit-EE function) gave me methods 1008-4310, the csv output file had some data that looked valid.

spmi collector gave me methods 1008-2705 methods with a zero mc file.

Do you know why the number of methods compiled with different jits can be different and why the first method has a different number? spmi wrappers do not call anything extra they are just passing all JIT-EE calls.

<details>
  <summary>Full commands</summary>

normal:
```
"D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\corerun" "D:\Sergey\git\runtime\artifacts\bin\coreclr\Windows_NT.x64.Checked\crossgen2\crossgen2.dll" @"D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.Security.AccessControl.dll.rsp" --codegenopt DumpJittedMethods=1  --jitpath "D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\clrjit_win_x64_x64.dll"  --parallelism 1
```

counter:
```
"D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\corerun" "D:\Sergey\git\runtime\artifacts\bin\coreclr\Windows_NT.x64.Checked\crossgen2\crossgen2.dll" @"D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.Security.AccessControl.dll.rsp" --codegenopt DumpJittedMethods=1 --codegenopt AltJit=* --codegenopt NgenAltJit=* --codegenopt AltJitName=superpmi-shim-counter.dll  --jitpath "D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\superpmi-shim-counter.dll"  --parallelism 1
```

collector:
```
"D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\corerun" "D:\Sergey\git\runtime\artifacts\bin\coreclr\Windows_NT.x64.Checked\crossgen2\crossgen2.dll" @"D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.Security.AccessControl.dll.rsp" --codegenopt DumpJittedMethods=1 --codegenopt AltJit=* --codegenopt NgenAltJit=* --codegenopt AltJitName=superpmi-shim-counter.dll  --jitpath "D:\Sergey\git\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\superpmi-shim-collector.dll"  --parallelism 1
```

</details>

**Comment by davidwrighton** [comment]
Ok, I think I found some of the issues here.

1. You are running crossgen2 using corerun. While this works, its not ideal, as its easy to have the runtime jit and the crossgen2 jit get confused. I would suggest running crossgen2 under dotnet.exe instead. I suspect that is why you are seeing radically different jitted method counts here as some part of your setup is measuring running the JIT that is compiling the compiler itself.

2. Crossgen2 does not support the builtin class CLASSID_ARGUMENT_HANDLE.  When there is an attempt to query for that classid, the crossgen2 jit interface will throw an exception. We may wish to fix this, but I was able to workaround that by commenting out the 
```
   our_ICorJitInfo.getBuiltinClass(CLASSID_ARGUMENT_HANDLE);
```
line in src/coreclr/src/ToolBox/superpmi/superpmi-shim-collector/icorjitcompiler.cpp

I don't know where you got your rsp files from, so I wasn't able to use your exact command lines. Instead I used the test build crossgen2 support, and the rsp file is
```
-r:c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\System.*.dll
-r:c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\Microsoft.*.dll
-r:c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\mscorlib.dll
-r:c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\netstandard.dll
-O
--inputbubble
--out:c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\temp.ni._dll
c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\System.Security.AccessControl.dll
--targetarch:x64
```

And set environment variables
```
SuperPMIShimLogPath=c:\temp
SuperPMIShimPath=c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\crossgen2\clrjit_win_x64_x64.dll
```

I placed the rsp file in c:\temp

and used the command line 
```
c:\git2\runtime\.dotnet\dotnet.exe "c:\git2\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\crossgen2\crossgen2.dll" @"c:\temp\System.Security.AccessControl.dll.rsp" --codegenopt DumpJittedMethods=1 --codegenopt AltJit=* --codegenopt NgenAltJit=* --jitpath "c:\git2\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\Tests\Core_Root\superpmi-shim-collector.dll"  --parallelism 1
```

With those steps, I found that the system successfully produced an mc file in c:\temp which is about 4.2MB indicating that the collection process succeeded to some extent.

**Comment by sandreenko** [comment]
@davidwrighton I was using a random rsp generated from `src\tests\build.cmd crossgen2`.

I will try to use dotnet.exe and test if the replay is working as expected.

**Comment by davidwrighton** [comment]
PR #42555 addresses the issues identified in the crossgen2 and superpmi collection binaries.

**Comment by BruceForstall** [comment]
@sandreenko Is this resolved now? Or do we still need superpmi.py scripting work on top of the fixes mentioned here?

**Comment by sandreenko** [comment]
> @sandreenko Is this resolved now? Or do we still need superpmi.py scripting work on top of the fixes mentioned here?

Still need a scripting update, it is on my list.

**Comment by sandreenko** [comment]
@BruceForstall right now you can do the collection using the following command:
```
set SuperPMIShimLogPath=mc_drop_folder
set SuperPMIShimPath=YOUR_Core_Root\clrjit_win_x64_x64.dll
"RUNTIME\dotnet.cmd" "RUNTIME\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\R2RTest\R2RTest.dll" compile-framework -cr "RUNTIME\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root" --output-directory "RUNTIME\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.out"  --large-bubble --release --target-arch x64 -dop 16 --verify-type-and-field-layout --crossgen2-parallelism 1 --crossgen2-path "RUNTIME\artifacts\bin\coreclr\Windows_NT.x64.Checked\crossgen2\crossgen2.dll" --crossgen2-jitpath "RUNTIME\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\superpmi-shim-collector.dll"
```

**Comment by BruceForstall** [comment]
With https://github.com/dotnet/runtime/pull/47513, crossgen2 collection is scripted. I will open separate issues for remaining work.
