### ISSUE TITLE
CoreClr build takes very long and fans out the cpu which results in the machine being unresponsive

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#41637]
The CoreCLR build takes 10-30 minutes depending on number of cores and other hardware metrics. In addition to that, the machine is completely unresponsive during the build, most likely because the CPU is completely fanned out. We should investigate if there's a way to speed the runtime build up (ie with VS 2019 build improvements and/or Ninja) and lower the CPU utilization to not block a dev's machine during the build.

cc @dotnet/runtime-infrastructure @jkoritzinsky @alefranz

**Comment by trylek** [comment]
Related issue: https://github.com/dotnet/runtime/issues/33872

**Comment by ViktorHofer** [comment]
Closing as dupe of https://github.com/dotnet/runtime/issues/33872
