### ISSUE TITLE
How to view the platform related binary code in DLL file ?

### ISSUE THREAD

**Issue by sunny868** [dotnet/runtime#41644]
How to view the platform related binary code in DLL file ? 
Maybe there are tools to use,just like objdump can view the binary code in ELF file.

**Comment by mangod9** [comment]
@sunny868 can you elaborate on your question? are you asking about managed assemblies, R2R native dlls or just any windows binaries? For managed assemblies you could use ILDASM, R2RDump for R2R.

**Comment by sunny868** [comment]
It`s R2R native dll . I`m working on Linux platform. 
When I use the crossgen tool to cross generate mips64 Arch platform related dll files, I want a tool to view the binary code in this file. 
`/coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/x64/crossgen /Platform_Assemblies_Paths /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/IL  /out /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/System.Private.CoreLib.dll /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/IL/System.Private.CoreLib.dll `

Where is R2RDump and how to use it ?

**Comment by mangod9** [comment]
You can find it here: https://github.com/dotnet/runtime/tree/master/src/coreclr/src/tools/r2rdump. You can also find a readme there describing its usage + R2R Format details. Hope this helps.

**Comment by mangod9** [comment]
BTW, it only supports x64, it appears you are building for mips64 and that isnt quite supported (yet).

**Comment by sunny868** [comment]
Thank you very much

**Comment by mangod9** [comment]
You are welcome. Ok to close this issue for now?

**Comment by sunny868** [comment]
I just ran this command on x64 linux:

``./dotnet exec --runtimeconfig shared/Microsoft.NETCore.App/2.1.0/R2RDump.runtimeconfig.json shared/Microsoft.NETCore.App/2.1.0/R2RDump.dll --in hello.dll
Error:
  An assembly specified in the application dependencies manifest (R2RDump.deps.json) was not found:
    package: 'System.CommandLine', version: '0.1.0-e160119-1'
    path: 'lib/portable-net45+win8+wpa81+aspnetcore50/System.CommandLine.dll'

Do I must rebuild System.CommandLine.dll source code (https://github.com/dotnet/command-line-api)?

**Comment by sunny868** [comment]
The System.CommandLine.dll min version is 0.3.0-alpha.20054.1  but not version: '0.1.0-e160119-1' on https://www.nuget.org/

**Comment by xiangzhai** [comment]
Hi,

The same story: [AspNetCore-2.1](https://github.com/dotnet/aspnetcore/tree/v2.1.7) failed to build for X86 either  https://github.com/dotnet/aspnetcore/issues/11309

Fortunately [AspNetCore-3.1](https://github.com/dotnet/aspnetcore/tree/v3.1.7) is OK!

Why the building process is heavily depends on online packages compares with [OpenJDK building](http://openjdk.java.net/groups/build/doc/building.html)?

Thanks,
Leslie Zhai

**Comment by mangod9** [comment]
I am closing this issue since the original question is answered. Please open a different issue for the R2R dependency issue if its not working on 5.0. Thx.
