### ISSUE TITLE
Remove remnant jit-diff automation from CI code

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#41651]
https://github.com/dotnet/coreclr/pull/8032 added the basics of creating jit-diff automation, based on idea here: https://github.com/dotnet/jitutils/issues/62. It was never used. Simply the CI by removing it.

**Comment by ViktorHofer** [comment]
@BruceForstall can you please provide more details? What exactly should be removed?

**Comment by ViktorHofer** [comment]
cc @trylek @jkoritzinsky @hoyosjs

**Comment by BruceForstall** [comment]
Turns out I already fixed this with https://github.com/dotnet/runtime/pull/48852, but didn't close the issue. Doing that now.
