### ISSUE TITLE
release/5.0 - Update SDK to final P8/RC1

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#41684]
We are currently using a non-final P8 SDK in release/5.0. We should update to a final P8/RC1 SDK _at some point_.

To consume the RC1 SDK, the following changes are necessary:
- https://github.com/dotnet/runtime/pull/41666
- https://github.com/dotnet/runtime/pull/42146
- https://github.com/dotnet/runtime/pull/42191
- https://github.com/dotnet/runtime/pull/42174 (unpins Roslyn version)
- Fix for https://github.com/dotnet/runtime/issues/42184 once it is available

We should do the same change in master but as it impacts more developers, it should be done as part of a batched rollout (ideally next week's one).

cc @dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
We believe this isn't necessary for shipping the product but we should do it anyway to minimize servicing diffs when taking a dependency on a serviced SDK.

**Comment by jkotas** [comment]
The release branch is building with Roslyn pinned to one of the preview versions. https://github.com/dotnet/runtime/pull/42174 unpinned compiler in the master branch. Include this change in this port?

**Comment by ViktorHofer** [comment]
Our plan was to work on this post RTM before the first servicing release. Is there risk involved with keeping the existing pinned compiler? If yes, I could prepare a PR today to make this ready for RC2.

**Comment by jkotas** [comment]
This is a discussion for shiproom if there was not one.

I would more worried with the risk involved in updating the SDK and compiler. I would prefer to take it early when everyone is paying attention and problems are identified quickly, and not wait for the first servicing release. As I have said, it is a decision for the shiproom to make.

**Comment by jkotas** [comment]
I have added two more changes (https://github.com/dotnet/runtime/pull/42146 + https://github.com/dotnet/runtime/pull/42191) that need to be included in this.

**Comment by ViktorHofer** [comment]
@jkotas do you think that #42184 is required? Sounds to me that we introduce tons of warnings in our build without any noticeable customer impact.

**Comment by jkotas** [comment]
> Sounds to me that we introduce tons of warnings in our build without any noticeable customer impact.

The CI impact and .NET team engineer impact is very noticeable.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/runtime/pull/42269
