### ISSUE TITLE
Some projects aren't enabled for nullable

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#41696]
I did a pass to compare syntax of APIs as they are in reference assemblies and how they are in implementation assemblies. The full spreadsheet can be [downloaded from here](https://github.com/dotnet/runtime/files/5158462/nullable_differences_assembly_mismatch_only.zip). 

The spreadsheet only shows API differences if the reference assembly and the implementation assembly differ with their `<Nullable>enable</Nullable>` setting (i.e one defines `NullableAttribute` and one does not). This affects these assemblies:

* Microsoft.VisualBasic.Core
* System.CodeDom
* System.IO.Ports
* System.Runtime.CompilerServices.Unsafe
* System.Security.Permissions

The first one is expected because we decided to only annotate the reference assembly; the others aren't.

/cc @dotnet/nullablefc

**Comment by terrajobst** [comment]
@jeffhandley please assign a dev to this so we can take this for approval.

**Comment by safern** [comment]
System.IO.Packaging has `<Nullable>annotations</Nullable>` on the source and the ref doesn't have `<Nullable>enable</Nullable>` we should update both as well to enable nullability on both.

**Comment by stephentoub** [comment]
System.Runtime.CompilerServices.Unsafe's implementation is IL, not C#.

**Comment by ericstj** [comment]
> System.Runtime.CompilerServices.Unsafe's implementation is IL, not C#.

Good point, we could copy the annotations to the .il file from the ref.  Is there value in such an excercise?  It could help anything in the repo that consumes the implementation directly, though I'm not sure we have such a case.

**Comment by stephentoub** [comment]
System.IO.Ports's src is annotations because it has some shared files the use the syntax. The ref doesn't need that. That difference is fine.

**Comment by stephentoub** [comment]
> Is there value in such an excercise?

I don't think so.

**Comment by stephentoub** [comment]
I don't see System.CodeDom's src or ref csproj containing Nullable, so I'm not sure why it's in the list.

**Comment by terrajobst** [comment]
> I don't see System.CodeDom's src or ref csproj containing Nullable, so I'm not sure why it's in the list. Same for System.Security.Permissions.

I don't read the project file, I only check whether the assembly defines `NullableAttribute`. Looks like [CodeTypeReference.ArrayElementType](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/CodeDom/CodeTypeReference.cs#L306) is annotated in impl only.

**Comment by stephentoub** [comment]
> I don't read the project file, I only check whether only one of the assemblies (ref or impl) defines NullableAttribute.

That's not sufficient. Any assembly that includes a shared file that uses nullable syntax will have the emitted by the compiler. It's only relevant of that's on public API.

**Comment by safern** [comment]
These are the ones that are really missing nullable enable:

System.IO.Packaging: both annotated correctly, we missed to add <Nullable>enable</Nullable> on the ref: https://github.com/dotnet/runtime/commit/518df4f20d20f233727cba2fcc42603a31f750df
System.Resources.Extensions: Missing nullable enable on both src and ref: https://github.com/dotnet/runtime/pull/37597/files

**Comment by terrajobst** [comment]
@stephentoub 

I’m not trying to make statements about correctness. The goal of this tool was merely to find discrepancies between ref and impl. My assumption was that we use a manual process to ensure these are intentional. This started because we found discrepancies that didn’t seem intentional. The heuristics like looking a NullableAttribute were only meant to reduce the noise because we a lot of discrepancies.

The right long term plan seems to be in improving GenAPI and ApiCompat. And in a perfect world reference assemblies wouldn’t need as much manual tweaking as they do today b/c it’s prone to errors. A Roslyn based GenAPI might help there because it would allow reading the manual files and only generate the remainders.

**Comment by stephentoub** [comment]
> The heuristics like looking at differences in the presence of NullableAttribute were only meant to reduce the noise

Ok

**Comment by eerhardt** [comment]
> I don't see System.CodeDom's src or ref csproj containing Nullable, so I'm not sure why it's in the list.

System.CodeDom shows up for one API:

![image](https://user-images.githubusercontent.com/8291187/91995206-23386180-ecfd-11ea-836b-9d1ab4868d6c.png)

This class is shared between `System.Private.DataContractSerialization` and `System.CodeDom`. In the former it is internal, and public in the latter. When I annotated `System.Private.DataContractSerialization`, I needed to make `ArrayElementType` nullable, since it can be null. But System.CodeDom is not in netcoreapp, but it is a netstandard2.0 library, so it hasn't been annotated.

I believe we can ignore the System.CodeDom difference - it is expected. If we think this is an issue, we should be able to fix it by using #if:

```C#
    public 
#if FEATURE_SERIALIZATION
        CodeTypeReference?
#else
        CodeTypeReference
#endif
        ArrayElementType { get; set; }
```

**Comment by stephentoub** [comment]
> If we think this is an issue

It's not.
