### ISSUE TITLE
Port infra for regeneration of THIRD-PARTY-NOTICES to runtime repo

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/runtime#41695]
It doesn't look like I linked to my tooling anywhere--it's over here:
https://github.com/dagood/core-setup/compare/bac3b0dc8ec9e0d4d2441524ed2bca24f8bab748...100d6dc55309b01856a15bd991c784f31154f63a ([`regen-tpn`](https://github.com/dagood/core-setup/tree/regen-tpn))

It needs to be ported into https://github.com/dotnet/runtime/tree/master/tools-local/tasks/installer.tasks to be maintainable.

_Originally posted by @dagood in https://github.com/dotnet/runtime/issues/3619#issuecomment-678430400_

**Comment by NikolaMilosavljevic** [comment]
Infra (target and task) needs to be ported to runtime repo.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Needed for 6.0.

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic this issue is still marked as `blocking-release`. As it's unclear to me if this needs to be done and as we are close to the 6.0 release, can you please again take a look and eventually update the milestone? Thanks

**Comment by NikolaMilosavljevic** [comment]
Moved to 7.0.

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/runtime/pull/60091
