### ISSUE TITLE
API Proposal: Range.Contains(Index)

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#417]
Given a range

```c#
[start..end]
```

in order to check if a number `X` is within this range, one needs to remember that `start` of the range is inclusive and `end` is exclusive. Also, the `end` value can be greater than `start`. It would be helpful if `Contains(Index)` is added either as a first-class or an extension method in Range class:

```c#
public class Range
{
    public bool Contains(Index subject) => Start.Value < End.Value ? 
        subject.Value >= Start.Value && subject.Value < End.Value :
        false;
}
```

Inspired by:
* Rust: https://doc.rust-lang.org/std/ops/struct.Range.html#method.contains (end is exclusive)
* Ruby: https://apidock.com/ruby/Range/include%3F (end is inclusive)

**Comment by stephentoub** [comment]
How would an API like that work for something like:
```
[1..3].Contains(^1)
```
? Where/how would you use this method?

**Comment by deadpaukevich** [comment]
СпасибоОтправлено с моего телефона Huawei

**Comment by am11** [comment]
The intended usage is to do a bound check using `Range` type: `(lowerBound..upperBound).Contains(myValue)`.
In this case, the `index from end (^)` operator would use the upper bound (`Start`) of Range object:
```c#
(1..3).Contains(^0) => false
(1..3).Contains(^1) => true
(1..3).Contains(^2) => true
(1..3).Contains(^3) => false
(1..3).Contains(^4) => false
```

**Comment by huoyaoyuan** [comment]
> (1..3).Contains(^0) => false
> (1..3).Contains(^1) => true
> (1..3).Contains(^2) => true
> (1..3).Contains(^3) => false
> (1..3).Contains(^4) => false

This is not how range and index work.
To be meaningful, `range.Contains(index)` should means `collection[range]` contains `collection[index]`. The result is relative to `collection.Length`.

**Comment by stephentoub** [comment]
> This is not how range and index work.
To be meaningful, range.Contains(index) should means collection[range] contains collection[index]. The result is relative to collection.Length.

Right. That's why I was asking how you expect such an API to be used. I'd expect the intended usage to be in the implementation of other types, and in sick types it is likely going to be wrong.

**Comment by am11** [comment]
This proposal is for "is the given index within the range object", and not for "is the given index within the collection object". I understand that thus far, `Range` is mainly perceived for indexers and slice related use cases. However, `Range` (as an independent) type can have useful utility methods for more general use cases.

> how you expect such an API to be used

I am using it to validate values read in web API:

```c#
var index = ReadIndex();
var range = ReadRange();

// validate
if (!RangeContains(range, index))
{
   return Error("index was out of range"); 
}

..
```

**Comment by stephentoub** [comment]
Thanks. I think that should not be part of Range. It's changing the expected meaning of Index, and I expect it's likely to do more harm (from being misused) than good.
