### ISSUE TITLE
PhysicalFileProvider should implement IDisposable correctly

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#41705]
### Description

This is code in PhysicalFileProvider:

https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs#L177-L194

There are at least 3 things wrong with it:

1. It has a finalizer, but doesn't manage any native assets.
2. It touches managed objects during its finalizer.
3. It doesn't call `GC.SuppressFinalize` when it is directly disposed.

We should correctly implement the [IDisposable pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) on this class.

**Comment by ericstj** [comment]
Same bugs here too:
https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs#L231-L249

**Comment by Marusyk** [comment]
I will prepare a PR for this
