### ISSUE TITLE
Where to implement rebasing for R2R in dotnet/coreclr ?

### ISSUE THREAD

**Issue by sunny868** [dotnet/runtime#41730]
When I use crossgen to compile the DLL, the jump address in R2R code is the virtual address related to x64.

` /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/x64/crossgen /Platform_Assemblies_Paths /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/IL  /out /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/System.Private.CoreLib.dll /coreclr-mips64-dev/bin/Product/Linux.mips64.Debug/IL/System.Private.CoreLib.dll`

Then the result in System.Private.CoreLib.dll(PE32+) file ,some R2R code like this:

`G_M31379_IG02:        ; func=00, offs=000030H, size=0108H, gcrefRegs=0000 {}, byrefRegs=0000 {}, byref, isz`
`   0x7fa638d93ba8   nop`
`   0x7fa638d93bac   ld  a0, 296(fp)`
`  0x7fa638d93bb0   bal  0x7fa638d93bb8                \\\bal is mips64 instructions , but 0x7fa638d93bb8 is x64 vaddr`
`   0x7fa638d93bb4   lui  t8, 0x0`

Then I execute  System.Private.CoreLib.dll(PE32+) file, the desired result is:
` bal  0xff7cafxxxx                     \\\bal is mips64 instructions , and 0xff7cafxxxx is mips64 vaddr also`

so how to rebase the jump address to mips64 arch? maybe can tell me where it works in coreclr for x64 or arm64.

**Comment by janvorli** [comment]
@sunny868 I am not sure I understand what you mean that the virtual address is related to x64? Do you mean that the relocations don't work for mips64? If that's the case, relocations for R2R binaries are done in this method:
https://github.com/dotnet/runtime/blob/cfd60300ced9acd1bfa417d89cfd9f0136ec07e2/src/coreclr/src/vm/peimagelayout.cpp#L144

**Comment by sunny868** [comment]
Sorry, The GDB tool let me misunderstood the issue. In fact,R2R code jump is PC-relative,the result in System.Private.CoreLib.dll(PE32+) file :
`bal 0x7fa638d93bb8 \\\bal is mips64 instructions , gdb show 0x7fa638d93bb8(x64_PC+offset)`

Then I execute System.Private.CoreLib.dll(PE32+) file on mips64 platform, the true result is:
`bal 0xff7cafxxxx \\\bal is mips64 instructions , gdb show 0xff7cafxxxx (mips64_PC+offset)`

Thank you for your reply.

**Comment by mangod9** [comment]
Closing, since the question is answered.
