### ISSUE TITLE
Multiple deadlock on exiting dotnet test.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#41752]
### Context
We got a tool that run our build agent on ~25 dotnet core repos in a row. Some days, we hit a deadlock while running dotnet tests on the repos.
Today we attached a debugger on the stuck process, and could see (not on my PC) the parrallel stacktrace and I wrote it down (the day i reproduce it on my machine I will get more data)  

### The deadlocks themself
We seen 2 differents deadlocks, both block the thread for exit (so it block the build): 
#### Telemetry
The one that occured the most was an infinite loop in the Telemetry: 
https://github.com/dotnet/sdk/blob/master/src/Cli/dotnet/Telemetry/PersistenceChannel/Sender.cs#L173
The _stopped flag was false, and main thread was waiting a lock on the Telemetry.
I don't have much more information on this one, I will try to pinpoint the issue the next time I see it, but by reading the code I can't see how it got locked.

#### EventProvider
https://source.dot.net/#System.Private.CoreLib/EventProvider.cs,204
Well sadly for this comment, we got a deadlock there.
We got thread A stuck on this line: 
https://source.dot.net/#System.Private.CoreLib/EventProvider.cs,1243 due to the native code call, I couldn't see what happen behind this.
And thread B is stuck in SendCommand, waiting a lock taken by thread A.

Patterns observed:
It stuck when the tests were completed, and only on heavy test that use the SqlServer (it probably use event tracing ?).

### Configuration

.NET Version:
Happened in .NET Core 2 and .NET Core 3.1,
On two different PCs running Windows (this build tool is mostly used by one person), it happened more often on the slower PC.

### Other information

Sadly, most of the information come from my notes and I only reproduced it only once a few weeks ago.
I will try to run dotnet-dump the next time I see this.

**Comment by sywhang** [comment]
Thanks for reporting this. Please do let us know when you are able to collect a dump.

**Comment by josalem** [comment]
We can reopen this issue when a repro is available.
