### ISSUE TITLE
[WASM] Some Runtime Tests Do Not Build on Wasm

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#41750]
The following runtime tests do not build for wasm (they are disabled in their project files for this architecture):

src/tests/Interop/ICastable/Castable.csproj
~~src/tests/JIT/HardwareIntrinsics/X86/X86Base/CpuId_r.csproj~~
~~src/tests/JIT/HardwareIntrinsics/X86/X86Base/CpuId_ro.csproj~~
~~src/tests/JIT/Intrinsics/TypeIntrinsics_r.csproj~~
~~src/tests/JIT/Intrinsics/TypeIntrinsics_ro.csproj~~ 
~~src/tests/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587.csproj~~
~~src/tests/performance/Scenario/JitBench/unofficial_dotnet/JitBench.csproj~~

This issue is to figure out why, and if feasible fix the problem.

### Quick instructions for building running the tests (these test fail at build time):

Get dotnet/runtime repo
1. Build WASM: ./build.sh --os Browser --arch wasm --subset mono+libs -c Release
2. Build runtime tests: cd src/coreclr/ && ./build-test.sh -skipstressdependencies -excludemonofailures os Browser wasm Release
3. To run all runtime tests, at the end of the runtime tests build log, there is "Example runtest.sh command". Use that command plus wasm. For example, for me it was
./tests/runtest.sh --coreOverlayDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root --testNativeBinDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/obj/coreclr/Browser.wasm.Release/tests --testRootDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release --copyNativeTestBin Release wasm
4. To run a single test, you could do

```set CORE_ROOT=<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root     
<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/ilasm/System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.sh```

**Comment by SamMonoRT** [comment]
@steveisok @lewing @akoeplinger - any ideas about what's needed to get these building for wasm ?

**Comment by akoeplinger** [comment]
What are the build errors?

**Comment by naricc** [comment]
@akoeplinger 

So, I tried to repro this to get the error messages, but the only one that repros is src/tests/Interop/ICastable/Castable.csproj:

The error it gives is:

```CSC : error CS0006: Metadata file '/Users/naricc/workspace/runtime-webassembly-ci/artifacts/bin/coreclr/Browser.wasm.Debug/System.Private.CoreLib.dll' could not be found [/Users/naricc/workspace/runtime-webassembly-ci/src/tests/Interop/ICastable/Castable.csproj] ```

It looks like it is looking explicity for the coreclr version of corelib. It might be worth investigating if it can be made to use the mono one, although if it is difficult, it might not be worth it for only one test.

The other ones I will just put out a PR to re-enable, assuming they pass.

**Comment by naricc** [comment]
I've re-enabled the ones that were building, and struck them above: 

https://github.com/dotnet/runtime/pull/42134

**Comment by naricc** [comment]
I investigated the src/tests/Interop/ICastable/Castable.csproj and determined that this test is too closely tied to the CoreCLR version of System.Private.Corelib to make using it on mono practicable.
