### ISSUE TITLE
Backport .NET Core 3.1 runtime upgrade behavior to 2.1

### ISSUE THREAD

**Issue by nakarnam** [dotnet/runtime#41769]
For .NET Core 3.1, .NET Core runtime update behave as upgrades. The latest servicing/patch update for 3.1 will remove all previous 3.1 patch updates upon successful installation for example Runtime version 3.1.2 will replace 3.1.1 and 3.1.0.  

This issue is to track the effort to backport this behavior to .NET Core 2.1 runtime upgrades as we prepare to [offer .NET Core updates via the Microsoft Update platform](https://github.com/dotnet/core/issues/5013). Major/minor updates will not remove previous major/minor updates.

**Comment by NikolaMilosavljevic** [comment]
This was completed.
