### ISSUE TITLE
Native library export support

### ISSUE THREAD

**Issue by AlseinX** [dotnet/runtime#41765]
CoreRT has a `DllExportAttribute` to export functions for native calling.
But how could this be implemented with CoreCLR?
I know there is a demo about hosting a .NET Core application with native application.
But It is too complexed for a native program that just simply want to call a .NET Core library.
Will it support a `DllExportAttribute` which exports a symbol of a function to host a .NET Core Runtime and call the exported static method?
Since that C++/CLI is not supported (or will be supported on WIndows only) on .NET Core, at least a way for other language/platforms calling .NET Core is needed.

**Comment by jkoritzinsky** [comment]
You can use the `UnmanagedCallersOnlyAttribute` in combination with the [.NET Native Exports](https://github.com/AaronRobinsonMSFT/DNNE) project ([NuGet package named DNNE](https://www.nuget.org/packages/DNNE)) to create a native entrypoint for static functions in your assembly that you want to expose to native code.

**Comment by AaronRobinsonMSFT** [comment]
Closing since the DNNE project is a prototype and something we are considering adding to the product given enough interest.
