### ISSUE TITLE
Potential optimization for `is ""`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#41779]
Based on the current master in sharplab:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACFAmDBhAWACgBvYjCrTYAexoBsMBZAChuACs4BjGDADwCU5SmSKUJWAOwCMASygYAREoDcIigF9imoA==

The following:

```csharp
public bool M(object x)
{
    return x is "";
}
```

is compiled as:

```csharp
public bool M(object x)
{
    string text = x as string;
    if (text != null)
    {
        return text == "";
    }
    return false;
}
```

It's a bit more performant if `return text == ""` is `text.Length == 0`.
That would be a special-casing for this, which I'm unsure if it's acceptable to the compiler team or not.

category:cq
theme:basic-cq
skill-level:intermediate
cost:small

**Comment by jkotas** [comment]
cc @EgorBo

**Comment by EgorBo** [comment]
Yes, if we could tune the inliner to be able to inline `string.Equals` (called via == operator) for constant arguments we could achieve the desired behavior and fold redundant null-checks.
```csharp
// Determines whether two Strings match.
public static bool Equals(string? a, string? b)
{
    if (object.ReferenceEquals(a, b))
    {
        return true;
    }

    if (a is null || b is null || a.Length != b.Length)
    {
        return false;
    }

    return EqualsHelper(a, b);
}
```
(the idea was to tell the inliner "if you see a `get_Length` call on a constant string especially in a condition - try harder")

However, I guess redundant `object.ReferenceEquals(a, b)` and `EqualsHelper(a, b);` would still be presented in the final codegen. So probably makes sense to intrinsify string.Equals and if its argument is a constant string - emit GT_ARRLEN check.

**Comment by EgorBo** [comment]
Prototype with an intrinsic: https://github.com/EgorBo/runtime-1/commit/7c4ef9f87765d5e921b2bbb5002132ed228e7e4e

it optimizes `x == ""` or `x is ""` or `string.Equals(x, "")` to `x != null && x.Length == 0`

**Comment by EgorBo** [comment]
Moving to future
First, we need to be able to import `string.Empty` as GT_CNS_STR to maximize impact of this.
