### ISSUE TITLE
Obsolete message for ConfigurationException class contains faulty message

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/runtime#41770]
# Path contains a **!** and duplicates namespace

# General
```
[Obsolete("This class is obsolete, to create a new exception create a System.Configuration!System.Configuration.ConfigurationErrorsException")]
        public ConfigurationException(string message);
```

Correct should possible be:
```
[Obsolete("This class is obsolete, to create a new exception create a System.Configuration.ConfigurationErrorsException")]
        public ConfigurationException(string message);
```

the [documentation 4.8](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationexception.-ctor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Configuration.ConfigurationException.%2523ctor);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.8) as well as Core contains the same error.

https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationexception.-ctor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Configuration.ConfigurationException.%2523ctor)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netcore-3.0

**Comment by danmosemsft** [comment]
@PeterPann23 would you like to offer a PR to this repo to fix it?

**Comment by PeterPann23** [comment]
why should I pay for your issues

**Comment by danmosemsft** [comment]
@PeterPann23  you don’t have to - I asked because often folks want to contribute. That is how open source works after all.

**Comment by safern** [comment]
@gewarren will this get updated once we get the new ref assemblies on the docs site?

**Comment by gewarren** [comment]
> @gewarren will this get updated once we get the new ref assemblies on the docs site?

No, I don't think so. I'll update it in the docs repo.

**Comment by safern** [comment]
Thanks!

**Comment by gewarren** [comment]
Actually, on second thought, I bet the update will bring those changes in, since they are part of the auto-generated attribute section.
