### ISSUE TITLE
In .net core 3.0, how to merge generated dll and exe into an exe file?

### ISSUE THREAD

**Issue by toolgood** [dotnet/runtime#41774]
In Visual Studio, the csproj project file configuration uses &lt;PublishSingleFile&gt;true&lt;/PublishSingleFile&gt; and &lt;PublishTrimmed&gt;true&lt;/PublishTrimmed&gt; , and the generated exe file is 47M.

But I want a smaller size, the operation is as follows:

1. Use &lt;PublishTrimmed&gt;true&lt;/PublishTrimmed&gt; to build the project.

2. After the project is generated, some invalid dlls are deleted, such as api-ms-win-core-console-l1-1-0.dll, api-ms-win-core-datetime-l1-1-0.dll... ...

3. The *.deps.json file has been modified and the program runs normally.

After modification, the entire file size of the entire program is 30M.

Ask, how to merge dll, exe into an exe file.

Note: Do not consider this tool https://github.com/dgiagio/warp

**Comment by agocke** [comment]
For .NET Core 5.0, you can try `<TrimMode>link</TrimMode>`, which could reduce the size of your application even further, at the expense of potentially trimming away members needed by reflection.
