### ISSUE TITLE
[GCStress=1] tracing/eventpipe/providervalidation/providervalidation/providervalidation.sh

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#41782]
Hi,

### Description

Testcase: [tracing/eventpipe/providervalidation/providervalidation/providervalidation.sh](https://github.com/dotnet/runtime/tree/master/src/tests/tracing/eventpipe/providervalidation)

```
export CORE_ROOT=/home/zhaixiang/coreclr-mips64-dev/bin/tests/Linux.arm64.Debug/Tests/Core_Root
export CORE_LIBRARIES=/home/zhaixiang/dotnet-sdk-3.1.107-linux-arm64/shared/Microsoft.NETCore.App/3.1.7
export COMPlus_GCStress=1
bash ./bin/tests/Linux.arm64.Debug/tracing/eventpipe/providervalidation/providervalidation/providervalidation.sh
```

ARM64:

```
BEGIN EXECUTION
/home/loongson/coreclr-mips64-dev/bin/tests/Linux.arm64.Debug/Tests/Core_Root/corerun providervalidation.exe ''
TEST STARTING
Test FAILED!
No events for provider "MyEventSource"
Configuration:
{
	bufferSize: 16,
	providers: [
		MyEventSource:0xFFFFFFFFFFFFFFFF:5,
		Microsoft-DotNETCore-SampleProfiler:0xFFFFFFFFFFFFFFFF:5,
		SentinelEventSource:0xFFFFFFFFFFFFFFFF:5,
	]
}

Expected:
{
	"MyEventSource" = 1000 +- 300
	"Microsoft-Windows-DotNETRuntimeRundown" = -1 +- -0
	"Microsoft-DotNETCore-SampleProfiler" = -1 +- -0
}

Actual:
{
	"Microsoft-DotNETCore-SampleProfiler" = 23311
	"Microsoft-DotNETCore-EventPipe" = 1
	"Microsoft-Windows-DotNETRuntimeRundown" = 3875
}
Expected: 100
Actual: 255
END EXECUTION - FAILED

real	38m41.307s
user	39m9.280s
sys	0m9.460s
```

MIPS64:

```
BEGIN EXECUTION
/home/loongson/test-file/coreclr/Core_Root-checked/corerun providervalidation.exe ''
TEST STARTING
Test FAILED!
Event count mismatch for provider "MyEventSource": expected 1000 +- 300, but saw 532
Configuration:
{
    bufferSize: 16,
    providers: [
        MyEventSource:0xFFFFFFFFFFFFFFFF:5,
        Microsoft-DotNETCore-SampleProfiler:0xFFFFFFFFFFFFFFFF:5,
        SentinelEventSource:0xFFFFFFFFFFFFFFFF:5,
    ]
}

Expected:
{
    "MyEventSource" = 1000 +- 300
    "Microsoft-Windows-DotNETRuntimeRundown" = -1 +- -0
    "Microsoft-DotNETCore-SampleProfiler" = -1 +- -0
}

Actual:
{
    "Microsoft-DotNETCore-SampleProfiler" = 28604
    "MyEventSource" = 532
    "Microsoft-Windows-DotNETRuntimeRundown" = 5976
}
Expected: 100
Actual: 255
END EXECUTION - FAILED
```

### Configuration

* [coreclr-v3.1.7](https://github.com/dotnet/coreclr/tree/v3.1.7) is able to reproduce the issue.
* NOT TEST runtime master.
* Ubuntu 16.04.3 LTS and Loongnix 1.0 (docker image: aoqi/dotnet-buildtools:loongson3a-loongnix-1.0-llvm8ld)
* ARM64 and MIPS64

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @mangod9 

Please test it for runtime master.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @tommcdon 

Any suggestion?

Thanks,
Leslie Zhai

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
@josalem Did you mention at standup that this test shouldn't be run under GCStress? I don't see it marked as gcstressincompatible https://github.com/dotnet/runtime/blob/master/src/tests/tracing/eventpipe/providervalidation/providervalidation.csproj

**Comment by josalem** [comment]
Hmmm, in September of last year the test was marked as `GCStresssIncompatible` https://github.com/dotnet/coreclr/blob/a9f3fc16483eecfc47fb79c362811d870be02249/tests/src/tracing/eventpipe/providervalidation/providervalidation.csproj#L11.  It currently isn't marked that way in master.  The release/3.1 branch in dotnet/coreclr looks different than I remember and doesn't have any mention of `gcstressincompatible`.

The fact that none of the events from `MyEventSource` made it through on the ARM64 test is troubling.  This test is running on ARM64 as part of PR validation currently and should be running under GCStress over the weekend and I'm unaware of it failing.

**Comment by davmason** [comment]
The arm64 test looks like was run in debug, which in my experience is unusable because it is so slow on arm64. It may just never have gotten to the point where events are written. I ran the test against master on arm64 and it passes, now I'm trying a checked build with GCStress enabled.

**Comment by davmason** [comment]
Nevermind what I said above. I was thinking maybe the test timed out, but it obviously didn't. It completed but didn't get the events.

I ran the test with a checked build and it passed, now I'm trying a debug build but with GCStress it's at over 40 minutes and counting. We've seen a handful of failures over the last couple months where events are dropped, I think most of them had GCStress turned on. It's occurring frequently enough where my spider sense is tingling about a real issue lurking under there, or at the very least some incompatibility with GCStress and EventPipe.

**Comment by davmason** [comment]
The debug test took over 8 hours to complete, but eventually passed. For now I'm going to run the tests in a loop and see if any failures happen

**Comment by josalem** [comment]
@davmason any news on this, or should we close it?

**Comment by davmason** [comment]
I never did get a repro
