### ISSUE TITLE
init-only property should be guarded not to be modified at runtime

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#41793]
### Description
init-only property should not be allowed to be modified
```csharp
class TestClass
{
    public int X { get; init; }
}

var x = new TestClass { X = 3 };
Console.WriteLine(x.X);
Console.WriteLine(x.GetType().GetProperty("X").CanWrite);
x.GetType().GetProperty("X").SetValue(x, 4);
Console.WriteLine(x.X);
```

### Expected result
```none
3
False
InvalidOperationException
```
A runtime exception should be thrown for `X` cannot be modified.

### Actual result
```none
3
True
4
```

### Configuration

.NET 5 preview 8

**Comment by jkotas** [comment]
It is perfectly valid to set these properties using reflection as part of the object construction sequence. The runtime has no way to tell whether you are setting these properties as part of the object construction sequence or not.

**Comment by jkotas** [comment]
The current behavior is by design.
