### ISSUE TITLE
ActivityContext..ctor's argument name differs between impl and ref

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#41790]
Ref:
`public ActivityContext(ActivityTraceId traceId, ActivitySpanId spanId, ActivityTraceFlags traceOptions, string? traceState = null, bool isRemote = false);`
Impl:
`public ActivityContext(ActivityTraceId traceId, ActivitySpanId spanId, ActivityTraceFlags traceFlags, string? traceState = null, bool isRemote = false);`

Note: `traceFlags` vs `traceOptions`

I assume we should match ref but please confirm (although impl name seems might make more sense)

**Comment by stephentoub** [comment]
Marking as 5.0 in case the ref needs to be updated, as we can't do so once 5.0 ships.

**Comment by krwq** [comment]
Looking at the [design doc](https://github.com/dotnet/designs/blob/master/accepted/2020/diagnostics/activity-improvements.md) `traceFlags` seem to be correct so this won't require ref change but I think we should still fix the impl to match this
