### ISSUE TITLE
CreateSocket.CtorAndAccept_SocketNotKeptAliveViaInheritance failures with various reasons

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#41794]
The cases of `System.Net.Sockets.Tests.CreateSocket.CtorAndAccept_SocketNotKeptAliveViaInheritance(validateClientOuter, acceptApiOuter)` have failed 6 times in the last 60 days in different configurations for different reasons. I think the root causes also differ.

| validateClientOuter | acceptApiOuter | Queue | Error | Number of failures | Note   |
|---------------------|----------------|-------|-------|--------------------|--------------------|
| * | * | sles.15.amd64.open | System.IO.FileNotFoundException: Could not load file or assembly System.Runtime.CompilerServices.Unsafe| 3 | Unrelated type load issue |
| True | 0 | ubuntu.1604.amd64.open | Remote Executor timeout | 1 | Happened on 2020-07-30 | 
| True | 0 | [osx.1014.amd64.open](https://dev.azure.com/dnceng/public/_build/results?buildId=798785&view=ms.vss-test-web.build-test-results-tab&runId=25285342&resultId=180737&paneView=debug)  | Remote Executor timeout | 1 | Might be related to #41508 |
| False | 1 | osx.1013.amd64.open  | Xunit.Sdk.FalseException: Assert.False() Failure | 1 |  |

Regarding the Remote Executor timeout case which might be related to #41508, my suggestion is to wait for further occurrences.

**Comment by karelz** [comment]
Triage: Started failing before the big PR in Sockets - so likely not a product regression, or anything serious for 5.0.

**Comment by antonfirsov** [comment]
No new failures since 2020-09-02. If it doesn't happen again we can close.

**Comment by antonfirsov** [comment]
The issue seems to be gone.
