### ISSUE TITLE
Dependency injection logging for analyzing the object creation number of times

### ISSUE THREAD

**Issue by sefacan** [dotnet/runtime#41792]
Hello there,
During the application life cycle, we should be able to determine the correct registration by logging the number of times the objects instance creation and analyzing the incorrectly object creation.

I hope it will help us for deciding to register objects in the most accurate way.

For example Instance Creation Counts:

|       Services              |           Singleton          |            Transient           |           Scoped              |
| ---------------------- | ----------------------- | ------------------------- | ------------------------ |
| IEmailSender             |               4                     |                                     |                                 |
| ISmsSender               |                                     |                                     |              26                |
| INotificationSender   |                                     |                 18                 |                                |

**Comment by maryamariyan** [comment]
cc @davidfowl 

Is this something that we want for DI diagnosing ability for 6.0?

**Comment by davidfowl** [comment]
There isn't a great way to do this today in .NET because event counters don't support dimensions but we have a very noising event source event today that fires whenever a service is resolved. It doesn't have the lifetime though, we could improve that.
