### ISSUE TITLE
[System.Text.Json] Why there is no JsonSerializer.DeserializeFromUtf8Bytes<TValue>(byte[] utf8Bytes, JsonSerializerOptions) method.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#41805]
Why there is no `JsonSerializer.DeserializeFromUtf8Bytes<TValue>(byte[] utf8Bytes, JsonSerializerOptions)` or `JsonSerializer.Deserialize<TValue>(byte[] utf8Bytes, JsonSerializerOptions)`  method while there is a `JsonSerializer.SerializeToUtf8Bytes<TValue>(TValue, JsonSerializerOptions)` method in `System.Text.Json` API?

Is there any technical reason or just have been missed?

Thank you.

**Comment by layomia** [comment]
See [this JsonSerializer.Deserialize overload](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer.deserialize?view=netcore-3.1#System_Text_Json_JsonSerializer_Deserialize__1_System_ReadOnlySpan_System_Byte__System_Text_Json_JsonSerializerOptions_).

**Comment by TanvirArjel** [comment]
Oh! My bad! How can I miss this? I never thought that `ReadOnlySpan<byte> utf8Json` can satisfy for `byte[] utf8Bytes`!

Thank you.

**Comment by layomia** [comment]
@TanvirArjel, no worries! There's an implicit cast from `T[]` to `ReadOnlySpan<T>`. More info [here](https://docs.microsoft.com/en-us/archive/msdn-magazine/2018/january/csharp-all-about-span-exploring-a-new-net-mainstay).

**Comment by ahsonkhan** [comment]
And to add more context: https://github.com/dotnet/runtime/issues/30348#issuecomment-530218830

> The primary reason `SerializeToUtf8Bytes` has "Utf8" in the name was to distinguish it from the one that returns string (since you can't have API overloads with the same name just based on the return type). If you notice, the Deserialize APIs do not have "Utf8" in the name, since we can overload them just fine based on the input parameter.

That's why we leave the `Deserialize` API name as is, but `Serialize` needed to be named `SerializeToUtf8Bytes`.
