### ISSUE TITLE
[Breaking change] Casting an RCW to an interface marked with `ComInterfaceType.InterfaceIsIInspectable` throws a PlatformNotSupportedException

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#41819]
# [Breaking change] Casting an RCW to an interface marked with `ComInterfaceType.InterfaceIsIInspectable` throws a PlatformNotSupportedException

As a follow up to the WinRT removal, casting an RCW to an interface marked as `ComInterfaceType.InterfaceIsIInspectable` now throws an exception at cast time instead of successfully casting and possibly causing access violations when executing methods on the interface.

The replacement for this usage is either to use the C#/WinRT tool (when you can define the interface in a WinMD), or to change the `ComInterfaceType` to `InterfaceIsIUnknown` and add three dummy methods at the start of the interface definition to correctly account for the IInspectable methods.

See https://github.com/dotnet/runtime/pull/41702

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/compat for breaking change guidance.

**Comment by PriyaPurkayastha** [comment]
Please create a breaking change issue using the template https://github.com/dotnet/docs/issues/new?assignees=&labels=&template=dotnet-breaking-change.md

**Comment by PriyaPurkayastha** [comment]
cc @gewarren for awareness

**Comment by jkoritzinsky** [comment]
Opened at https://github.com/dotnet/docs/issues/20439 from the template

**Comment by AaronRobinsonMSFT** [comment]
Closing in deference to the tracking doc issue in https://github.com/dotnet/docs/issues/20439.
