### ISSUE TITLE
Socket.BeginSendFile throws SocketException "The parameter is incorrect" when sending large files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#41834]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1151057/socketbeginsendfile-throws-socketexception-the-par.html)._

---
<p>Socket.BeginSendFile throws a socket exception System.Net.Sockets.SocketException: 'The parameter is incorrect' <br>when trying to send files more than 3.5 GB, however files less than 1.5 GB was sent without problems.</p> <p>To reproduce the issue :<br></p><p>1. Create a TCP socket.<br> 2. Connect the socket to the remote endpoint. <br>3. Send a 3.5 GB file using Socket.BeginSendFile(String, AsyncCallback, Object)<br></p><p>Tested on both 2004 and 1809 Windows 10 builds and same exception was thrown.</p> <p>To help reproducing the issue the code can be found <a href="https://stackoverflow.com/questions/63396302/beginsendfile-socketexception-the-parameter-is-incorrect" target=_blank></a><a href="https://social.msdn.microsoft.com/Forums/en-US/63c6007c-e700-40ee-a1eb-80310676c694/beginsendfile-throws-socketexception-amp39the-parameter-is-incorrectamp39?forum=csharpgeneral" target=_blank>here</a>.</p>

---
#### Feedback Bot on 8/17/2020, 01:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by scalablecory** [comment]
Can you please confirm that this happens on .NET Core 3.x or with a .NET 5 preview?

**Comment by RishoT17** [comment]
It's happening for me on ASP.Net Core 5

**Comment by wfurt** [comment]
Seems like dup of https://github.com/dotnet/runtime/issues/42534 
There was also some more discussion about OS limit here: https://github.com/dotnet/runtime/issues/41906 and it seems like this is OS limitation.

**Comment by RishoT17** [comment]
Yeah, I've found the same thing, according to my research, it's using TransmitFile underneath, which has the 2GB limitation.
Sources: 
https://stackoverflow.com/questions/44745529/socket-sendfile-send-big-file-error-87
https://docs.microsoft.com/en-gb/windows/win32/api/mswsock/nf-mswsock-transmitfile?redirectedfrom=MSDN

One workaround I've found is to use the DotNetZip NuGet package to compress and split the big file into smaller ones before sending. This package can do the splitZip with a custom maxOutputSegmentSize:
```
            int segmentsCreated;
            using (ZipFile zip = new ZipFile())
            {
                zip.AddDirectory(buildPath);
                zip.MaxOutputSegmentSize = int.MaxValue; // 100k segments
                zip.Save(zipPath);

                segmentsCreated = zip.NumberOfSegmentsForMostRecentSave;
            }
```

**Comment by wfurt** [comment]
closing as dup of #42534.
