### ISSUE TITLE
 runtime-coreclr outerloop not running against release branches

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#41841]
Should we be running Pri1 tests against 5.0? While looking for RC1 validation, I found Pri0 test were good, but there's no outerloop for CoreCLR. Libraries outerloop is running nonetheless.

**Comment by BruceForstall** [comment]
@trylek

**Comment by hoyosjs** [comment]
I ran it against the RC1 candidate and we have a green run https://dev.azure.com/dnceng/public/_build/results?buildId=801228&view=ms.vss-test-web.build-test-results-tab
