### ISSUE TITLE
Question: Ability for IHostedService implementation to drop privileges

### ISSUE THREAD

**Issue by polarapfel** [dotnet/runtime#41848]
Hey there,

I'm not sure where this question fits in.

Scenario: an implementation of IHostedService in .Net Core using the worker template with Systemd integration is binding to a socket (on Linux). Ports below <=1024 can only be bound to if the process runs with root privileges. Obviously, it is preferable not to run the process as root.

There doesn't seem to be an API in .Net Core that allows to start the process as root user, bind a socket to a target port <=1024, then drop root privileges.

Suggestions?

thanks,

Tobias W.

**Comment by polarapfel** [comment]
I did some digging. It seems like I might have a path with System.Runtime.InteropServices and PInvoke bridging to setuid() from libc.

**Comment by eerhardt** [comment]
@polarapfel - yes using the [Mono.Posix.NETStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard/1.0.0) will work great for this scenario.

By the way, if you haven't already seen this blog on how to use systemd and Microsoft.Extensions.Hosting, check it out: https://devblogs.microsoft.com/dotnet/net-core-and-systemd/.

I believe this question has been answered, so I'm going to close this. Please re-open if it hasn't been answered.
