### ISSUE TITLE
Question about array bounds check elimination

### ISSUE THREAD

**Issue by RamType-0** [dotnet/runtime#41854]
I saw this kind of code in runtime internal library.

https://github.com/dotnet/runtime/blob/cb1a7feaa43cdbd03b317db24fa30d86eae2a27c/src/mono/netcore/System.Private.CoreLib/src/System/MulticastDelegate.cs#L38-L44

Is this faster than ordinary "for" iteration?

**Comment by EgorBo** [comment]
> Is this faster than ordinary "for" iteration?

No, just a different way to make a loop 🙂 this particular code came from mono/mono repo and was written 6 years ago.
