### ISSUE TITLE
Apps that took dependency on libcoreclr.so fail in single file mode

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#41859]
@migueldeicaza's Gui.cs is an example of a library that took dependency on libcoreclr.so (because apparently that's a way to get at CoreCLR's dlopen).

https://github.com/migueldeicaza/gui.cs/blob/fa29269ade64482c65cf657b2dfcfa68c59ba2de/Terminal.Gui/ConsoleDrivers/CursesDriver/UnmanagedLibrary.cs#L254-L266

This obviously fails in single file mode where libcoreclr.so doesn't exist:

```
Curses failed to initialize, the exception is: System.DllNotFoundException: Unable to load shared library 'libcoreclr.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcoreclr.so: cannot open shared object file: No such file or directory
   at Mono.Terminal.Internal.UnmanagedLibrary.CoreCLR.dlopen(String filename, Int32 flags)
   at Mono.Terminal.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath)
   at Mono.Terminal.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives, Boolean isFullPath)
   at Unix.Terminal.Curses.LoadMethods()
   at Unix.Terminal.Curses.FindNCurses()
   at Unix.Terminal.Curses.initscr()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Unix.Terminal.Curses.raw()
   at Terminal.Gui.CursesDriver.Init(Action terminalResized)
   at Terminal.Gui.Application.Init(Func`1 topLevelFactory)
   at Terminal.Gui.Application.Init()
   at Demo.Main()
Aborted
```

Should we quirk DllImports from libcoreclr.so?

I filed https://github.com/migueldeicaza/gui.cs/issues/889 in Gui.cs, but this might end up being a pattern.

I'm putting this 5.0 so that it's looked at, but feel free to move around.

**Comment by benaadams** [comment]
https://github.com/migueldeicaza/gui.cs/blob/91a86c9460751dd0ed40ee8945b12f6cdb33b5fd/Terminal.Gui/ConsoleDrivers/CursesDriver/UnmanagedLibrary.cs#L254-L266
```csharp
/// <summary>
/// Similarly as for Mono on Linux, we load symbols for
/// dlopen and dlsym from the "libcoreclr.so",
/// to avoid the dependency on libc-dev Linux.
/// </summary>
static class CoreCLR
{
    [DllImport ("libcoreclr.so")]
    internal static extern IntPtr dlopen (string filename, int flags);

    [DllImport ("libcoreclr.so")]
    internal static extern IntPtr dlsym (IntPtr handle, string symbol);
}
```

**Comment by benaadams** [comment]
It looks to be to avoid a runtime dependency on `libc-dev` which it takes for the non-Mono, non-CoreCLR path  https://github.com/migueldeicaza/gui.cs/blob/91a86c9460751dd0ed40ee8945b12f6cdb33b5fd/Terminal.Gui/ConsoleDrivers/CursesDriver/UnmanagedLibrary.cs#L220-L227

```csharp
static class Linux
{
    [DllImport ("libdl.so")]
    internal static extern IntPtr dlopen (string filename, int flags);

    [DllImport ("libdl.so")]
    internal static extern IntPtr dlsym (IntPtr handle, string symbol);
}
```

**Comment by jkotas** [comment]
> Should we quirk DllImports from libcoreclr.so?

No. If we start adding compatibility quirks like this to runtime to virtualize the environment, we won't know where to stop. https://github.com/dotnet/designs/blob/master/accepted/2020/form-factors.md#single-file 

This should be fixed in the library. In the meantime, I believe that this can be worked around in the app by subscribing to `AssemblyLoadContext.ResolvingUnmanagedDll` event and rerouting libcoreclr.so.

**Comment by agocke** [comment]
> No. If we start adding compatibility quirks like this to runtime to virtualize the environment, we won't know where to stop.

Agreed. Fundamentally we need to have a set of supported API points and focus on that. PInvoking `coreclr.dll` is not one of those, it's simply an implementation detail.

**Comment by ptupitsyn** [comment]
I have a similar problem with `pthread_key_create`, it does not work in single-file publish mode:
```cs
            [DllImport("libcoreclr.so")]
            public static extern int pthread_key_create(IntPtr key, IntPtr destructorCallback);
```

Any ideas where to reroute this call?
