### ISSUE TITLE
WinHttpHandler: Not able to retrieve body of GOAWAY packet

### ISSUE THREAD

**Issue by jensolsson** [dotnet/runtime#41865]
Working och a solution that communicates with Apples APNS servers for push message delivery. This service use HTTP/2 only. For different reasons the operation can fail and the server will return an error code as well as a reason within a json structure in the GOAWAY packet.

Using WinHttpHandler I can find no way to read this GOAWAY packet. Is this a missing functionality or is it just me who cannot find the correct API function / callback?

**Comment by jensolsson** [comment]
![Screenshot 2020-09-04 at 14 21 42](https://user-images.githubusercontent.com/1985582/92238670-fbdac380-eeb9-11ea-927c-5829a45f5354.png)

Here is also some code. response.StatusCode can be read. ReasonPhrase is "". I read that this was no longer part of the HTTP/2 standard so fair enough. But I would expect to be able to read the response.Content where I would expect to find the JSON.

**Comment by jensolsson** [comment]
Never mind. I realized I could reach the response using response.Content.ReadAsStringAsync().Result

**Comment by halter73** [comment]
@jensolsson The response body content is different than the GOAWAY frame error code/additional debug content, no? Does Apple's APNS duplicate this in the response body?

**Comment by jensolsson** [comment]
@halter73 very interesting. I believe Apple sends some response additionally. 
Is there any example on hiw to get the goaway packet?
