### ISSUE TITLE
async method generates code slower than Task.FromResult

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#41883]
### Description

async method returning a value generates code slower than the same method returning Task.FromResult.

```

.NET Core SDK=5.0.100-preview.8.20417.9
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40711, CoreFX 5.0.20.40711), X64 RyuJIT
  DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.40711, CoreFX 5.0.20.40711), X64 RyuJIT


|               Method |      Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |----------:|----------:|----------:|------:|--------:|-------:|------:|------:|----------:|
|           Task_Async | 18.184 ns | 0.3842 ns | 0.4859 ns |  1.00 |    0.00 | 0.0172 |     - |     - |      72 B |
|      Task_FromResult |  7.992 ns | 0.1228 ns | 0.1089 ns |  0.44 |    0.02 | 0.0172 |     - |     - |      72 B |
|      ValueTask_Async | 13.992 ns | 0.3004 ns | 0.3906 ns |  0.77 |    0.03 |      - |     - |     - |         - |
| ValueTask_FromResult |  1.950 ns | 0.0624 ns | 0.0613 ns |  0.11 |    0.00 |      - |     - |     - |         - |
```

It is not a regression.
Just an observation.

**Comment by EgorBo** [comment]
```csharp
async Task<int> Foo1() => 1;

Task<int> Foo2() => Task.FromResult(1);
```
here Roslyn emits a state-machine for `Foo1` because of `async` keyword. `Foo2` just calls `FromResult` method, furthermore `FromResult` caches task objects for [-1..9] range (and true/false). So it's a well-known advice to use `FromResult` where possible.

**Comment by stephentoub** [comment]
> furthermore FromResult caches task objects for [-1..9] range (and true/false)

It doesn't. Async methods do.

But the rest is correct. This is all by design. Async methods set up and enter an async state machine, including ensuring execution context is appropriately guarded (which may be necessary for correctness even if the async method never yields). It simply has more overhead.
