### ISSUE TITLE
Vector<T> with array or Span<T> input show performance drop.

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#41905]
### Description
The above title might be a bit misleading, but in the end with .NET my assumption is that arrays and Span<T> are somehow equivalent in performance now.

We are doing a lot of number crunching for that reason we are trying to get as much as performance we can get, but we want to keep readability. Currently there is not vectorized support for Log or Exp method inside the Vector<T> or the new intrinsics library. Currently a lot of algorithms are coming up on our side that deal a lot with exponentials so I tried a way to somehow insert some vectorized support for Exp.

The problem is that every run produces different benchmark results which would be OK, but in this way it is hard to find out which method is best: I made a few tests by handing over the Vector<T> in Exp (see below as `in` or `ref`), but also here it's completely random.

What is completely stable is the conventional method with regular arrays. Even though it seems to me that the Span<T> methods do not show the "promised" improvement for .NET 5.

Also setting      [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)] to the benchmark methods influence the results tremendously. Before setting the optimization the classic array-based method was fasted. After MethodImpl the last two were faster.

Any guidance would be appreciated.

Here is the code sample:

``` CS
    public class Benchmarker
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static Vector<float> Exp(in Vector<float> vector)
        {
            Span<float> result = stackalloc float[Vector<float>.Count];
            for (int i = 0; i < Vector<float>.Count; i++)
                result[i] = MathF.Exp(vector[i]);

            return new Vector<float>(result);
        }

        int N = 1000000;
        float[] A;
        float[] C;

        [GlobalSetup]
        public void GlobalSetup()
        {
            A = new float[N];
            C = new float[N];
            for (int i = 0; i < N; i++)
            {
                A[i] = i;
                C[i] = i;
            }
        }

        [Benchmark]
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public void TestLinear1()
        {
            for (int i = 0; i < N; i++)
                C[i] = A[i] * A[i] * MathF.Exp(A[i]);
        }

        [Benchmark]
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public void TestLinear2()
        {
            int S = Vector<float>.Count;
            int R = N - (N % S);
            int i = 0;
            for (; i < R; i += S)
            {
                Vector<float> ai = new Vector<float>(A, i);
                (ai * ai * Exp( ai)).CopyTo(C, i);
            }

            for (; i < N; i++)
                C[i] = A[i] * A[i] * MathF.Exp(A[i]);
        }

        [Benchmark]
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public void TestLinear3()
        {
            Span<float> AS = A;
            Span<float> CS = C;

            int S = Vector<float>.Count;
            int R = N - (N % S);
            int i = 0;
            for (; i < R; i += S)
            {
                Vector<float> ai = new Vector<float>(AS.Slice(i));
                (ai * ai * Exp( ai)).CopyTo(CS.Slice(i));
            }                


            for (; i < N; i++)
                C[i] = A[i] * A[i] * MathF.Exp(A[i]);
        }
```

### Configuration

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1016 (1909/November2018Update/19H2)
Intel Xeon CPU E5-2670 0 2.60GHz, 2 CPU, 32 logical and 16 physical cores
.NET Core SDK=5.0.100-preview.6.20318.15
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.30506, CoreFX 5.0.20.30506), X64 RyuJIT
  DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.30506, CoreFX 5.0.20.30506), X64 RyuJIT


|      Method |     Mean |    Error |   StdDev |
|------------ |---------:|---------:|---------:|
| TestLinear1 | 79.49 ms | 1.426 ms | 1.334 ms |
| TestLinear2 | 99.98 ms | 1.074 ms | 1.005 ms |
| TestLinear3 | 81.67 ms | 1.214 ms | 2.369 ms |
```

**Comment by benaadams** [comment]
Could you use a more vectorized Exp?

**Note:** I'm not sure on the if my translation from C is correct or the accuracy of this algorithm https://stackoverflow.com/a/50379934/1109918

Using `in` or `ref` for the param will make it worse for this example as it pins the Vector to stack memory rather than a register; but if you change the `Exp(Vector<float> vector)` to
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
static Vector<float> Exp(Vector<float> vector)
{
    // Nic Schraudolph's BetterFastExpSse from https://stackoverflow.com/a/50379934/1109918
    const float M_LN2 = 0.69314718055994530942f;

    Vector<float> a = new Vector<float>((1 << 22) / M_LN2);  // to get exp(x/2)
    Vector<int> b = new Vector<int>(127 * (1 << 23));        // NB: zero shift!

    Vector<int> r = Vector.ConvertToInt32(a * vector);

    Vector<int> s = b + r;
    Vector<int> t = b - r;

    return Vector.AsVectorSingle(s) / Vector.AsVectorSingle(t);
}
```
Then the results are
```
|      Method |        Mean |    Error |   StdDev |
|------------ |------------:|---------:|---------:|
| TestLinear1 | 54,893.3 us | 45.07 us | 35.19 us |
| TestLinear2 |    285.3 us |  1.92 us |  1.60 us |
| TestLinear3 |    299.6 us |  1.35 us |  1.19 us |
```

Note this may not be correct (check the results and errors); may only work for a specific range of x etc; disclaimer, disclaimer

**Comment by benaadams** [comment]
Note also you aren't using the Spans in the final `for` loop; so it should really be (rather than relying on the Span and Array starting at the same position):
```csharp
for (; i < AS.Length; i++)
{
    float ai = AS[i];
    float expAi = MathF.Exp(ai);
    CS[i] = ai * ai * expAi;
}
```

However the Jit won't eliminate the bounds check for `AS` unless `i` starts at `0` in the loop 😢; so you'd need to change it to a `do` + `if` loop when it will:
```csharp
do
{
    if ((uint)i < (uint)AS.Length)
    {
        float ai = AS[i];
        float expAi = MathF.Exp(ai);
        CS[i] = ai * ai * expAi;
    }
    else
    {
        break;
    }

    i++;
} while (true);
```

**Comment by benaadams** [comment]
Then if you were willing to go unsafe, you could combine that and get
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
static Vector<float> Exp(Vector<float> vector)
{
    // Nic Schraudolph's BetterFastExpSse from https://stackoverflow.com/a/50379934/1109918
    const float M_LN2 = 0.69314718055994530942f;

    Vector<float> a = new Vector<float>((1 << 22) / M_LN2);  // to get exp(x/2)
    Vector<int> b = new Vector<int>(127 * (1 << 23));        // NB: zero shift!

    Vector<int> r = Vector.ConvertToInt32(a * vector);

    Vector<int> s = b + r;
    Vector<int> t = b - r;

    return Vector.AsVectorSingle(s) / Vector.AsVectorSingle(t);
}

[Benchmark]
[MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
public void TestLinear4()
{
    Span<float> AS = A;
    Span<float> CS = C;

    if (CS.Length < AS.Length)
    {
        // Going unsafe for the Vector loop, so precheck the destination is large
        // enough as it won't be checked in the loop.
        throw new ArgumentException("Destination too short");
    }

    int R = AS.Length - (int)((uint)AS.Length % (uint)Vector<float>.Count);
    int i = 0;

    ref float asRef = ref MemoryMarshal.GetReference(AS);
    ref float csRef = ref MemoryMarshal.GetReference(CS);
    for (; i < R; i += Vector<float>.Count)
    {
        Vector<float> ai = Unsafe.ReadUnaligned<Vector<float>>(ref Unsafe.As<float, byte>(ref Unsafe.Add(ref asRef, i)));
        Vector<float> expAi = Exp(ai);
        Vector<float> result = ai * ai * expAi;
        Unsafe.WriteUnaligned<Vector<float>>(ref Unsafe.As<float, byte>(ref Unsafe.Add(ref csRef, i)), result);
    }

    do
    {
        if ((uint)i < (uint)AS.Length)
        {
            float ai = AS[i];
            float expAi = MathF.Exp(ai);
            CS[i] = ai * ai * expAi;
        }
        else
        {
            break;
        }

        i++;
    } while (true);
}
```
```
|      Method |        Mean |     Error |    StdDev |
|------------ |------------:|----------:|----------:|
| TestLinear1 | 55,629.8 us | 196.22 us | 173.95 us |
| TestLinear2 |    289.6 us |   2.95 us |   2.76 us |
| TestLinear3 |    303.9 us |   2.75 us |   2.43 us |
| TestLinear4 |    261.1 us |   3.82 us |   3.39 us |
```

**Comment by msedi** [comment]
Hello @benaadams.

Thx for your quick help. You are absolutely right, the last loop was wrong. I have to investigate the Exp method and check the accuracy of it if it can be applied to our situation. So many thanks for the link.

But I still have a few questions about your optimizations;

### 1. Is this line necessary or only a check. 
In my original code I have this line, but I do a few things more. I have encapsulated the check in an external method since it need it very often with additional checks (e.g. there are methods with more than two inputs and this method also creates the result with the correct dimensions). So if this method is not to help the jitter optimize the code then it's OK in my case, but if it is to help the jitter does the jitter check inside the external method?

``` CS
 if (CS.Length < AS.Length)
    {
        // Going unsafe for the Vector loop, so precheck the destination is large
        // enough as it won't be checked in the loop.
        throw new ArgumentException("Destination too short");
    }
```

### 2. Why going unsafe?
I assume with the line below you are going around the regular Vector<T> constructor since it has more overhead, right?

``` CS 
Vector<float> ai = Unsafe.ReadUnaligned<Vector<float>>(ref Unsafe.As<float, byte>(ref Unsafe.Add(ref asRef, i)));`
```

### 3. Aside from using Vector<T>
We are trying to rewrite our `unsafe `methods into Span<T>. Most of our old code is using `unsafe `and pointer arithmetics but the Span<T> is a good opportunity to make the code safer. In some cases I found that the Span<T> outperforms the unsafe/pointer, but there are cases (ImageFilters, etc. especially where you have to access the same index many times) where it seems to me the effort to make the Span<T> version as fast a the pointer version is higher than simply using pointers. I assume there is no general recipe or recommendation if we should completely avoid pointers and do everything with Span<T>, right?

The problem in general us though that it somehow hidden knowledge of how to write the code so that the jitter is able to optimize. Of course this has always been the case but would it be helpful to put the jitter optimization in some context as you for example do with `unchecked`. We could use something like `boundscheck `or the negativ `noboundscheck` which would put it into a larger context. In fact I do not know about the side effects this would cause.

**Comment by benaadams** [comment]
> 1. Is this line necessary or only a check.

It's necessary with the Unsafe example; the regular ones would throw an exception when going out of bounds, whereas the Unsafe would overwrite memory that's not in the array/Span.

> 2. Why going unsafe?

Yes, its reading straight from memory to a register rather than going via extra methods and skipping the bounds checks

> 3. Aside from using Vector

`for (var i = 0; i < span.Length; i++)` or `foreach (var item in span)` is about as fast as it gets; per loop slicing will be slower than pointers or `ref` (as in the Unsafe example; the `ref` approach has the advantage of not getting in the way of the GC unlike `fixed`)

A great advantage of Span is operating over sub ranges of data; as you have a safe bounded range, whereas if you use array (+ start, end like ArraySegment) or pointer there are no checks to prevent you reading around it or going outside. Obviously with the array you are still limited to the array itself, but the pointer there are no guards at all.

The biggest issue is with Vector and intrinsics as there isn't a great way of loading/storing them and avoiding bounds checks with regular span/array (read chunk of x, advance by x); however if you look at the improvement of `TestLinear4` its not huge, so that extra cost may be fine (there's no additional cost once it is in a Vector and you are doing Vector ops, its just load and store)

**Comment by msedi** [comment]
@benaadams. Thanks for your comments I will dig a bit more and see what I can get. In the end you are right, there's not such a big performance improvement. But we are doing it very often (~ 1.000.000 times) so event a small improvment would help. Nevertheless I also want to keep readability and currently this outweighs more.
