### ISSUE TITLE
Possible Socket.SendFileAsync issue with files >2GiB.

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#41906]
Within our Unix code, we are casting `FileStream.Length` to an `int` here:

https://github.com/dotnet/runtime/blob/84c1f62cc29ced0ea7e6b0f6a7d87aaf3b88679a/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L1811-L1812

This would fail for any files greater than 2GiB in length.

**Comment by geoffkizer** [comment]
On Windows. TransmitFile is limited to 2GB. See https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile

We may not need the same limitation for Linux, though.

**Comment by wfurt** [comment]
Would it make sense to check file size and fall-back to some internal implementation if file is too big? That would give us consistency while preserving perf benefits when possible...

**Comment by geoffkizer** [comment]
Possibly, yeah.

At the very least we should give a good exception here instead of just casting and losing the actual file length...

**Comment by wfurt** [comment]
actually

>>> The maximum number of bytes that can be transmitted using a single call to the TransmitFile function is 2,147,483,646, the maximum value for a 32-bit integer minus 1. The maximum number of bytes to send in a single call includes any data sent before or after the file data pointed to by the lpTransmitBuffers parameter plus the value specified in the nNumberOfBytesToWrite parameter for the length of file data to send. If an application needs to transmit a file larger than 2,147,483,646 bytes, then multiple calls to the TransmitFile function can be used with each call transferring no more than 2,147,483,646 bytes. 

it seems like the correct way is to make multiple calls - and I'm not sure we do.

**Comment by stephentoub** [comment]
> it seems like the correct way is to make multiple calls - and I'm not sure we do.

I separated this out into https://github.com/dotnet/runtime/issues/42534.
