### ISSUE TITLE
[RFC] Refactory proposal

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#41926]
Hi,

Thanks for the lesson in CoreCLR MIPS64 porting!

But I met several issues in the very beginning, for example, [porting the interpreter](https://github.com/dotnet/runtime/issues/12673).  Unfortunately [interpreter is not able to work](https://github.com/dotnet/runtime/issues/13759).  Then we decided to port RyuJIT directly.

And I wanted to [refactory the RyuJIT](https://github.com/dotnet/runtime/issues/1046) more than once in my mind, because there are too many `#ifdef TARGET_YOUR_ARCH`.

So here comes the Request for Comments about the Refactory proposal:

1. Redundant register redefine

There are 32 integer registers and 32 floating-point registers for MIPS64, but when I initial ported [CoreCLR v2.1](https://github.com/dotnet/coreclr/tree/release/2.1), sorry for my stupid, I had to redefine the same registers times and times again:

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/inc/cordebuginfo.h#L149

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/inc/crosscomp.h#L388

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/inc/cordebug.idl#L3876

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/inc/regdisp.h#L186

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/gcinfo/gcinfodumper.cpp#L193

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/jit/registermips64.h

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/pal/inc/pal.h#L2449

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/pal/src/arch/mips64/asmconstants.h

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/pal/src/include/pal/context.h#L118

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/pal/prebuilt/inc/cordebug.h#L8951

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/debug/inc/dbgipcevents.h#L1181

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/debug/inc/dbgtargetcontext.h#L477

* https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/debug/inc/mips64/primitives.h

But OpenJDK 8u just only need to define once for MIPS:

* http://hg.loongnix.org/jdk8-mips64-public/hotspot/file/51e607da02c4/src/cpu/mips/vm/register_mips.hpp

Could define register just only once?  But add more informations, for example the pseudo code:

```
REGDEF(name, rnum,       mask, xname, wname, abi, more information...) */
                             
REGDEF(V0,      2,     0x0004, "v0"   , "v0", REG_INTRET_0, ...)
REGDEF(A0,      4,     0x0010, "a0"   , "a0", REG_ARG_0, ...)
REGDEF(S0,     16,    0x10000, "s0"   , "s0", RBM_INT_CALLEE_SAVED_0, ...)

REGDEF(F0,    0+FBASE, FMASK(0),   "f0",  "f0", REG_FLOATRET_0, ...)
REGDEF(F12,  12+FBASE, FMASK(12), "f12", "f12", RBM_FLTARG_0, ...)
```

2. Not good readable `#ifdef TARGET_YOUR_ARCH`

Consider when porting [PowerPC](https://github.com/dotnet/runtime/issues/10055), RISCV, and other architectures, just like [mono supported the architectures](https://github.com/mono/mono/tree/master/mono/arch), for example:

```
//------------------------------------------------------------------------           
// fgResetImplicitByRefRefCount: Clear the ref count field of all implicit byrefs
                                                                                
void Compiler::fgResetImplicitByRefRefCount()                                   
{                                                                               
#if (defined(_TARGET_AMD64_) && !defined(UNIX_AMD64_ABI)) || defined(_TARGET_ARM64_) || defined(_TARGET_MIPS64_) || defined(_TARGET_POWERPC64_) || defined(_TARGET_RISCV64_) || defined(_TARGET_YOUR_ARCH64_)
    printf("Not good readable\n");                                                                  
#endif
```

But OpenJDK abstract target related layer for different architectures, for example the pseudo code to refactory [Compiler::fgResetImplicitByRefRefCount](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/morph.cpp#L17814):

```
void Compiler::fgResetImplicitByRefRefCount() 
{
    YourArchResetImplicitByRefRefCount();
}
```

Then your architecture implement the virtual interface:

```
virtual void YourArchResetImplicitByRefRefCount();
```

MIPS64:

```
void MIPS64:YourArchResetImplicitByRefRefCount()
{
    printf("Good readable\n");
}
```

3. Introduce more GCs, just like OpenJDK, parallelgc, g1gc, zgc, etc. So it needs to refactory GC share common layer to support different GCs.

The same story: introduce more JITs, just like OpenJDK, c1 compiler for client focus on startup, c2 compiler for server. I hold the view that coreclr is just like c1 compiler and mono is c2 compiler.

\cc @jkotas @BruceForstall @janvorli @Maoni0

Welcome feedback!

Thanks,
Leslie Zhai

category:implementation
theme:jit-coding-style
skill-level:intermediate
cost:medium

**Comment by benaadams** [comment]
> 3. Introduce more GCs, just like OpenJDK, parallelgc, g1gc, zgc, etc. So it needs to refactory GC share common layer to support different GCs.

I think you can change the GC already? https://tooslowexception.com/zero-garbage-collector-for-net-core/

**Comment by xiangzhai** [comment]
Hi @benaadams 

Thanks for your response!

> I think you can change the GC already? https://tooslowexception.com/zero-garbage-collector-for-net-core/

I will learn it.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @benaadams 

How to experience [UpsilonGC](https://github.com/kkokosa/UpsilonGC) under Linux?

Thanks,
Leslie Zhai

**Comment by benaadams** [comment]
> How to experience UpsilonGC under Linux?

Not that familiar with it /cc @kkokosa

**Comment by xiangzhai** [comment]
Hi @benaadams @kkokosa

Thanks for your [ZGC implementation](https://tooslowexception.com/zero-garbage-collector-for-net-core/)!

Consider when there are UpsilonGC, parallelgc, g1gc, zgc (pauseless gc), etc.

It needs the global `wbs_GCCustom` to identify different custom GCs in the [JIT_WriteBarrier](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/arm64/asmhelpers.S#L371):

```
#ifdef FEATURE_STANDALONE_GC
    // Update GC custom
    ldr  x12, LOCAL_LABEL(wbs_GCCustom)
    cmp  x12, 0x0                              ; assume ZGC is 0x0 custome GCs
    beq  x12, LOCAL_LABEL(ZGCEnabled)

    cmp  x12, 0x1
    beq  x12, LOCAL_LABEL(YourCustomGCEnabled)
#endif
```

Thanks,
Leslie Zhai

**Comment by jkotas** [comment]
The GC/EE can communicate to the EE what kind of write barrier it wants to use. Look for `WriteBarrierParameters`. The set of write barrier shapes can be extended as needed if there is a good reason to.

> to identify different custom GCs in the JIT_WriteBarrier:

`JIT_WriteBarrier` is a performance critical method. It would not be acceptable to slow it down for custom GCs. Instead, the alternative write barrier shapes should be implemented as separate methods.

**Comment by xiangzhai** [comment]
Hi @jkotas 

> Instead, the alternative write barrier shapes should be implemented as separate methods.

Thanks for your advice!
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @joktas 

Please give me some advice about the 1. and 2. in the Refactory proposal.

Thanks,
Leslie Zhai

**Comment by kkokosa** [comment]
Happy to help @xiangzhai. I must admit, I didn't prepare/compile Upsilon GC for Linux, yet. Although, most of the block are in place, I believe.

The weak control over barriers is my pain point, not raised yet as (AFAIK) no one tried to implement real custom GC in CLR. So the question is @jkotas what do you mean by _"Instead, the alternative write barrier shapes should be implemented as separate methods."_? I'm not aware of any API that would allow to inject/use your own method as a write barrier (so, outside the built-in set). Not even mentioning custom load barriers, that would be required for most "pauseless" GCs.

**Comment by xiangzhai** [comment]
Hi @kkokosa 

Thanks for your kind response!

> Although, most of the block are in place, I believe.

I will try to port it for Linux MIPS64.

> Not even mentioning custom load barriers, that would be required for most "pauseless" GCs.

There might an opportunity to fix the [load-load-reordering](https://github.com/dotnet/runtime/discussions/41253) issue via custom GCs for Linux MIPS64.

Thanks,
Leslie Zhai

**Comment by jkotas** [comment]
> I'm not aware of any API that would allow to inject/use your own method as a write barrier

Right, they cannot be injected. It is expected that implementation of new interesting kinds of GCs would require some modifications of the vm. Some of them may not be even practical to do in the same build of coreclr.dll and may require a custom build of coreclr.dll. 

> Please give me some advice about the 1. and 2. in the Refactory proposal.

1. It should be possible to unify some of these. I do not think it makes sense to unify everything into same file - for example, I do not think it makes sense to have OS/PAL-specific augments together with JIT-specific augments. There are also other factors to consider: For example, cordebuginfo.h that is first on your list is part of the .net runtime public interface and it used by projects outside dotnet/runtime tree. The refactoring would need preserve the values of the existing constants.

2. I think that the @dotnet/jit-contrib team would be generally ok with changes to reduce platform specific ifdefs as long as they improve code readability and do not introduce regressions. Each of these platform specific code pieces should have a comment about how to implement it for a new architecture. For your `fgResetImplicitByRefRefCount` example, what would such comment said? Even better than moving platform specific code around is to unify across platforms and make platform-specific logic unnecessary.

**Comment by xiangzhai** [comment]
Hi @jkotas 

Thanks for your response!

> It is expected that implementation of new interesting kinds of GCs would require some modifications of the vm.

The baseline is don't break default GC and VM.

> For example, cordebuginfo.h that is first on your list is part of the .net runtime public interface and it used by projects outside dotnet/runtime tree.

I agree+1

Another instance is [diagnostics](https://github.com/dotnet/diagnostics/pull/1496).

But why not keep just only one register define beside these independent projects repositories?

> For your fgResetImplicitByRefRefCount example, what would such comment said? Even better than moving platform specific code around is to unify across platforms and make platform-specific logic unnecessary.

Because [morph.cpp](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/morph.cpp) is related to ABI, I [had to add](https://github.com/gsvm/coreclr/blob/release/3.1-mips64-port/src/jit/morph.cpp#L3009) `defined(_TARGET_MIPS64_)` carefully in order to [met MIPS64 N64 ABI](https://github.com/dotnet/runtime/issues/1046).

Even better is `morphYourArch.cpp` to implement the target specific interface instead of tooooo long `#ifdef TARGET_YOUR_ARCH`.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @kkokosa 

> Happy to help @xiangzhai. I must admit, I didn't prepare/compile Upsilon GC for Linux, yet. Although, most of the block are in place, I believe.

Please help me to port UpsilonGC for Linux:  https://github.com/xiangzhai/UpsilonGC

```
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \
-DCORECLR_SOURCE_PATH="/home/loongson/zhaixiang/coreclr-mips64-dev"
```

Build error:

```
$ make
Scanning dependencies of target UpsilonGC
[ 50%] Building CXX object src/UpsilonGC/CMakeFiles/UpsilonGC.dir/UpsilonGC.cpp.o
In file included from /home/loongson/zhaixiang/UpsilonGC/src/UpsilonGC/UpsilonGC.cpp:5:
In file included from /home/loongson/zhaixiang/UpsilonGC/src/UpsilonGC/inc/UpsilonGCHeap.h:6:
In file included from /home/loongson/zhaixiang/coreclr-mips64-dev/src/inc/debugmacros.h:14:
/home/loongson/zhaixiang/coreclr-mips64-dev/src/inc/stacktrace.h:65:168: error: expected expression
void GetStringFromStackLevels(UINT ifrStart, UINT cfrTotal, __out_ecount(cchMaxAssertStackLevelStringLen * cfrTotal) CHAR *pszString, struct _CONTEXT * pContext = NULL);
                                                                                                                                                                       ^

```

Thanks,
Leslie Zhai

**Comment by BruceForstall** [comment]
@xiangzhai I will echo what @jkotas said above: the JIT code base would definitely benefit from some refactoring that improves readability and makes it easier to port to different platforms. You've identified above one of the worst spots: ABI handling, especially in fgMorphArgs and related functions. However, also as @jkotas says, we need to be very careful not to introduce regressions, either to functionality or, importantly, to JIT throughput (how fast the JIT itself runs). There are definitely trade-offs, and we sometimes accept more complexity if it provides a significant throughput win. (However, there are also many cases of organic growth in the code base that led to unnecessary complexity that can simply be improved.)

As for 1, for the JIT code, specifically, we try to be as standalone and independent as possible, so sharing definitions with other components creates a dependency that is sometimes not desired.

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

Thanks for your kind response!

> we need to be very careful not to introduce regressions

I agree+1

We always git push to gerrit to trigger jenkins to test the patch avoid bring in regressions or bugs.

And LLVM toolchain, the [MiddleEnd pass](https://github.com/llvm/llvm-project/tree/master/llvm/lib/Transforms), is able to optimize the target specific interface layer for CoreCLR.  So I argue that Refactory could not slow down RyuJIT.

> so sharing definitions with other components creates a dependency that is sometimes not desired.

I am refactorying runtime master and [performance](https://github.com/dotnet/performance) compare the before and after.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi,

And there are lots of `error: redefinition of 'XXX' as different kind of symbol` issues.  Workaround [patch.txt](https://github.com/dotnet/runtime/files/5215993/patch.txt).

Thanks,
Leslie Zhai

**Comment by BruceForstall** [comment]
@briansull

**Comment by BruceForstall** [comment]
This conversation is stale and there are no specific work items here, so closing.
