### ISSUE TITLE
Should MetadataLoadContext consider System.Private.CoreLib as a core assembly name?

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#41921]
I was following [the tutorial on `MetadataLoadContext`](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext) and noticed that it doesn't work as is on .Net Core. This is because:

* It specifies `typeof(object).Assembly.Location` as one of the available assemblies in `PathAssemblyResolver`, which is System.Private.CoreLib on .Net Core.
* It doesn't specify `coreAssemblyName`, so the default core assembly names are attempted to be used. These are mscorlib, System.Runtime and netstandard and don't include System.Private.CoreLib.

The result of this is an exception:

> System.IO.FileNotFoundException: Could not find core assembly. Either specify a valid core assembly name in the MetadataLoadContext constructor or provide a MetadataAssemblyResolver that can load the core assembly.

If you specify System.Private.CoreLib as `coreAssemblyName`, everything seems to work fine.

My question is: should the default core assembly names be expanded to include System.Private.CoreLib, to make working with `MetadataLoadContext` easier on .Net Core? If not, I think at leas the tutorial should be improved, so that it works on .Net Core.

**Comment by danmosemsft** [comment]
@steveharter

**Comment by steveharter** [comment]
Yes `System.Private.CoreLib` is not in the list of default names so the name needs to be specified as so:

```cs
var mlc = new MetadataLoadContext(resolver, coreAssemblyName: typeof(object).Assembly.GetName().Name);
```

It seems like adding support for `System.Private.CoreLib` directly would be easy and relatively low-risk.

In the original API proposal, the list of default core names was not included at all -- the core assembly name had to be provided when create MetadataLoadContext. Based on feedback, we added the 3 default values you list - `mscorlib`, `System.Runtime` and `netstandard` - but did not list `System.Private.CoreLib` as one of those default. Not sure on the exact reason, other than a netcore-only library perhaps was not considered common enough.

**Comment by jkotas** [comment]
> System.Private.CoreLib as one of those default. Not sure on the exact reason, other than a netcore-only library perhaps was not considered common enough.

I believe that the idea was that the public assembly name should be passed in as core assembly name. System.Private.CoreLib is considered internal implementation detail.

**Comment by steveharter** [comment]
If we keep existing the behavior, the first sample (there are two) should be changed from
```cs
var resolver = new PathAssemblyResolver(new string[] { "ExampleAssembly.dll", typeof(object).Assembly.Location });
var mlc = new MetadataLoadContext(resolver);
```
to
```cs
Assembly coreAssembly = typeof(object).Assembly;
var resolver = new PathAssemblyResolver(new string[] { "ConsoleApp142.dll", coreAssembly.Location });
var mlc = new MetadataLoadContext(resolver, coreAssemblyName: coreAssembly.GetName().Name);
```

**Comment by steveharter** [comment]
I'll create a PR for the doc issue.

Closing for now; re-open or assign 7.0 if deemed appropriate.
