### ISSUE TITLE
Mark System.Threading.Thread ResetAbort as Obsolete

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#41925]
It was recognized in https://github.com/dotnet/runtime/pull/41892 that `System.Threading.Thread` `ResetAbort` throws `PlatformNotSupportedException` everywhere and should be marked as Obsolete.

**Comment by GrabYourPitchforks** [comment]
I've marked this _ready for review_ since it's very straightforward. Recommend reusing the `SYSLIB0006` (Thread.Abort is obsolete) code for this.

**Comment by terrajobst** [comment]
* We believe it makes sense to reuse the existing diagnostic ID

```C#
namespace System.Threading
{
    public sealed class Thread
    {
        // Obsoleted in .NET 5:
        //[Obsolete(DiagnosticId = "SYSLIB0006")]
        //public void Abort();
        //[Obsolete(DiagnosticId = "SYSLIB0006")]
        //public void Abort(object stateInfo);
        [Obsolete(DiagnosticId = "SYSLIB0006")]
        public static void ResetAbort();
    }
}
```
