### ISSUE TITLE
Debugger function evaluation duplicates a string

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#41937]
I'm not sure if this is an issue in the runtime or in Visual Studio, but this is a good place to start.

Consider the following code:

```csharp

        public struct MyStruct
        {
            public MyStruct(string str)
            {
                Value = str;
            }

            public string Value { get; }
        }

        public void Test()
        {
            string str = "/hello";

            CheckEquality(new MyStruct(str), new MyStruct(str)); // Returns true
        }

        public static bool CheckEquality(MyStruct s1, MyStruct s2)
        {
            bool areEqual = object.ReferenceEquals(s1.Value, s2.Value);

            Console.WriteLine(areEqual);

            return areEqual;
        }
```

The `CheckEquality` method returns true, as expected. But if I set a breakpoint at the end of `Test()` and evaluate `CheckEquality(new MyStruct(str), new MyStruct(str))` in the immediate window of Visual Studio, the method returns false. 

If I set a breakpoint inside `CheckEquality` and invoke it from the immediate window, I can see that both `s1` and `s2` hold a different copy of the original string. This only happens with `string`, I couldn't reproduce it with `object`. 

I don't know if it's hitting a special case in https://github.com/dotnet/runtime/blob/master/src/coreclr/src/debug/ee/funceval.cpp, or if it has something to do with the code generated by Visual Studio.

Tested with .net core 3.1.6.

**Comment by tommcdon** [comment]
Thank you for the feedback!  This issue appears to be related to Visual Studio.  Would you mind opening a Visual Studio feedback item? https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
