### ISSUE TITLE
Failed to start platform. Reason: TypeError: stackSave is not a function

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#41942]
```
blazor.webassembly.js:1 Error: Failed to start platform. Reason: TypeError: stackSave is not a function
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.throw (blazor.webassembly.js:1)
    at u (blazor.webassembly.js:1)
```

I randomly get this Error.

**Comment by CoffeeFlux** [comment]
Do you have some sort of repro or more info about what triggers the error? This seems hard to work off.

`stackSave` is coming from emscripten, so this seems like some kind of weird interop issue? I'm not sure we can do much without a repro though. cc: @lewing

**Comment by gmeks** [comment]
I have the same issue.

Working on 1 machine, but this error randomly on another. Workaround is CTRL F5, and then it works....

Smells a bit like a caching issue to me.

**Comment by lewing** [comment]
stackSave is an emscripten function, is something else defining it in your code?

**Comment by nssidhu** [comment]
Yes,
I am using a BarCode library which downloads an additional  .wasm file for it functionality.
I have decided to not use that library any more.
Naunihal
================================================================================================================
    On Friday, October 30, 2020, 02:42:22 PM CDT, Larry Ewing <notifications@github.com> wrote:  
 
 


stackSave is an emscripten function, is something else defining it in your code?

**Comment by pavelsavara** [comment]
I guess this was conflict of 2 emscripten engines in the global namespace on the same page ?

.Net 7 is now encapsulated ES6 module and so it should not happen anymore.
Feel free to re-open with more steps to reproduce.
