### ISSUE TITLE
Nullable annotation mismatch in System.Text.Json.JsonException

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#41956]
#### ref

https://github.com/dotnet/runtime/blob/d81b0662eb33acb135a83f49efebd6afb9682f51/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L145-L146

#### impl

https://github.com/dotnet/runtime/blob/d81b0662eb33acb135a83f49efebd6afb9682f51/src/libraries/System.Text.Json/src/System/Text/Json/JsonException.cs#L29-L47

#### proposed

Annotate all `path` to nullable, since the `Path` property is decided to be nullable.

#### backport priority

Low. The update will be relaxing, and it should be uncommon for user to call constructor of library specified exception.

**Comment by Jozkee** [comment]
This is already being tracked in https://github.com/dotnet/runtime/pull/41731

**Comment by huoyaoyuan** [comment]
The PR title is misleading so I missed it. Thanks.

**Comment by layomia** [comment]
Closing as the fix was merged in https://github.com/dotnet/runtime/pull/41845. cc @Jozkee
