### ISSUE TITLE
[wasm][debugger] Crash/assert when stepping out from an async method

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#41973]
I changed aspnetcore's `StandaloneApp`'s `Counter.razor` to:
```csharp
@code {
    static HttpClient client = new HttpClient();
    int currentCount = 0;

    async Task IncrementCount()
    {
	        currentCount ++;
                await JustWaitAsync("foobar");
    }

    async Task<HttpStatusCode> JustWaitAsync(string some)
    {
        var resp = await client.GetAsync("http://localhost:8080");
        Console.WriteLine($"resp: {resp}"); /// BP at this line

        return resp.StatusCode;
    }
}
```

I set a breakpoint at CWL after `GetAsync`. Once that is hit, then I hit `step-over` twice, to step over the closing brace for `JustWaitAsync`, and then I get:
`: /Users/radical/dev/runtime/src/mono/mono/mini/mini-wasm-debugger.c:248 <disabled>`
.. which corresponds to `	g_error ("set_set_notification_for_wait_completion_flag");`

I'm trying this with my https://github.com/radical/runtime/tree/debugger-5.0-rc2 branch.

**Comment by thaystg** [comment]
Working on it! :)
