### ISSUE TITLE
FileStream constructor throws an ArgumentException with a null ParamName property

### ISSUE THREAD

**Issue by akalnay** [dotnet/runtime#41970]
### Description

The documentation for the `FileStream` class' constructors that take a string for the first argument (the path) states that "_an `ArgumentException` will be thrown if path is an empty string (""), contains only white space, or contains one or more invalid characters_".  An example of one of the constructors I'm referring to is:

`public FileStream (string path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share)`) 

The behavior I'm experiencing is that indeed, an `ArgumentException` is being thrown for those conditions, however **the `ParamName` property of the thrown exception is null**.

For example running the following console application produces the output below (the code also passes a null string as an argument for comparison):

```C#
        static void Main(string[] args)
        {
            ShowFileStreamExceptions();
            Console.WriteLine("Press any key to end.");
            Console.ReadKey();
        }

        private static void ShowFileStreamExceptions()
        {
            string[] fileNames = { null, "", " ", new String(Path.GetInvalidPathChars()) };
            for (int i = 0; i < fileNames.Length; i++)
                ShowFileStreamException(fileNames[i]);
        }

        private static void ShowFileStreamException(string fileName)
        {
            try
            {
                FileStream fileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
            }
            catch (ArgumentException e)
            {
                Console.WriteLine($"ParamName = {e.ParamName}");
                Console.WriteLine($"Message   = {e.Message}");
                Console.WriteLine(new String('.', 20));
                Console.WriteLine();
            }
        }
```
**Code output:**

ParamName = path
Message   = Path cannot be null.
Parameter name: path
....................

ParamName =
Message   = Empty path name is not legal.
....................

ParamName =
Message   = The path is not of a legal form.
....................

ParamName =
Message   = Illegal characters in path.
....................

Press any key to end.

### Issue Summary

The 'FileStream' constructor throws the expected `ArgumentException`, however the exception's ParamName property is null instead of containing the name of the parameter that caused the exception.

### Configuration

Windoes 8.1
.NET Framework 4.8

**Comment by danmosemsft** [comment]
@akalnay thanks for the report. On .NET 5.0, this is not reproducing:
```
C:\proj\1>dotnet run
ParamName = path
Message   = Path cannot be null. (Parameter 'path')
....................

ParamName = path
Message   = Empty path name is not legal. (Parameter 'path')
....................

ParamName = path
Message   = The path is empty. (Parameter 'path')
....................

ParamName = path
Message   = Illegal characters in path. (Parameter 'path')
....................

Press any key to end.
```

We would not take a fix for such a bug in .NET Framework, since it would not have sufficient value to justify the cost/risk of changing that product.
