### ISSUE TITLE
[wasm][debugger] async locals don't show up correctly for non-trivial async methods

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#41979]
.. instead they show up with the underlying async machinery.

**Comment by lewing** [comment]
@radical is there a test for this?  Have you tried it against master?

**Comment by radical** [comment]
I have local changes for this, including tests. I will try it against master.

**Comment by thaystg** [comment]
As I understood this is already fixed and has a lot of tests for it. If there is any case that you know that is not working @radical please reopen the issue and tell me how to reproduce.
