### ISSUE TITLE
[wasm] Error using japanese datetime format

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#41977]
### Description

Running debugger tests on wasm we have an error, but the problem is not on debugger, it's on System.Globalization on wasm.

### Configuration

It's possible to reproduce on master:
1. Uncomment this line: https://github.com/dotnet/runtime/blob/2e9347f34c7fd666f77acc0e4ba892c0309e7e9d/src/mono/wasm/debugger/DebuggerTestSuite/DateTimeTests.cs#L18

2. `./build.sh --arch wasm --os Browser -c release -bl --configuration Release`

3.  `make -C src/mono/wasm/ run-debugger-tests TEST_FILTER=DebuggerTests.DateTimeList`

The failure:

```
Expected: {
  "type": "string",
  "value": "yyyy年M月d日 dddd H:mm:ss"
}. Actual: {
  "type": "string",
  "value": "yyyy年M月d日dddd H:mm:ss",
  "description": "yyyy年M月d日dddd H:mm:ss"
}
```

**Comment by tarekgh** [comment]
CC @safern @EgorBo to triage

**Comment by tarekgh** [comment]
looks Japanese long date format in WASM somehow having space between `yyyy年M月d日` and `dddd`. I looked at what we have in none WASm and we don't have this space in the format. I tried that on Windows.

**Comment by EgorBo** [comment]
I wonder if it's ICU v67 related 🤔

**Comment by tarekgh** [comment]
@thaystg does the debugger runs in its own process (using net core)? if this is the case, then it might be this is by design as you can run into cases in data discrepancies between WASM and net core as both having its own ICU library.

**Comment by thaystg** [comment]
Yes, so we shouldn't expect the same result in both? If this is the case I can change the test.

**Comment by tarekgh** [comment]
> So we shouldn't expect the same result in both? If this is the case I can change the test and close this issue.

It is not guaranteed we'll have the exact ICU data in WASM and in the debugger process. I think fixing the test would be ok but I am worried about the debugger behavior in general. Does the debugger always evaluate any var values from the WASM process or it can do it  using the debugger process?

**Comment by thaystg** [comment]
I think this is the only test that we compare the result from net core with wasm. The others we know which value we expect. I will change the test.

**Comment by tarekgh** [comment]
@thaystg should we close this issue then? or you want to re-label it?

**Comment by thaystg** [comment]
Yes, let's close.
