### ISSUE TITLE
Analyzer Suggestion: Don't seal properties on sealed types

### ISSUE THREAD

**Issue by Mrnikbobjeff** [dotnet/runtime#41980]
I just checked the spec again and applying a sealed modifier to a class also seals all properties. Applying the modifier to a property is a no-op and an analyzer could warn for that. The fixer would simply remove sealed attributes on all members of the class.

**Comment by ericstj** [comment]
Should this be moved to https://github.com/dotnet/roslyn-analyzers @jeffhandley?

**Comment by jeffhandley** [comment]
For the time-being, we've been keeping `code-analyzer` suggestions in this repo. We need to do some triaging/organizing/planning around them though.

**Comment by stephentoub** [comment]
This is purely stylistic, with no impact on consumers of the type, on performance, etc.  We're generally not providing such analyzers as part of dotnet/runtime and dotnet/roslyn-analyzers.  It's more appropriate for something like StylecopAnalyzers.

**Comment by carlossanlop** [comment]
Based on Stephen's comment, we can close the issue as we don't plan on adding an analyzer for this.
