### ISSUE TITLE
System.Diagnostics.Tests.ProcessStandardConsoleTests.TestChangesInConsoleEncoding test fails on server core

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#42000]
I'm enabling Server Core 20H1 libraries test runs and this test failed with:

```
Assert.Equal() Failure
Expected: 65001
Actual:   437
 at System.Diagnostics.Tests.ProcessStandardConsoleTests.<TestChangesInConsoleEncoding>b__1_0(Int32 expectedCodePage) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStandardConsoleTests.cs:line 26
   at System.Diagnostics.Tests.ProcessStandardConsoleTests.TestChangesInConsoleEncoding() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStandardConsoleTests.cs:line 51
```

I noted that we have the following comment that for Nano we only support UTF-8 which is `65001` code page: https://github.com/dotnet/runtime/blob/efafca9bd8ba5a746634820596f8144d0d98fde1/src/libraries/System.Diagnostics.Process/tests/ProcessStandardConsoleTests.cs#L45

I went ahead and created a console app:
```cs
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"CP: {GetConsoleCP()}");
            Console.WriteLine($"Setting CP 437: {SetConsoleCP(437)}");
            Console.WriteLine($"CP: {GetConsoleCP()}");
            Console.WriteLine($"Setting CP to 65001: {SetConsoleCP(65001)}");
            Console.WriteLine($"CP: {GetConsoleCP()}");
        }

        [DllImport("kernel32.dll")]
        internal static extern int SetConsoleCP(int codePage);
        [DllImport("kernel32.dll")]
        internal static extern int GetConsoleCP();
    }
```

Output was:
```
C:\Work\test>tmpTestCodePageServer.exe
CP: 65001
Setting CP 437: 1
CP: 437
Setting CP to 65001: 1
CP: 65001
```

I ran this on both a Nano and a Server container and got the same results:
`mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c`
`mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504`

cc: @ericstj @danmosemsft @jkotas @adamsitnik @eiriktsarpalis

**Comment by danmosemsft** [comment]
Note the asserts are backwards 
https://github.com/dotnet/runtime/blob/efafca9bd8ba5a746634820596f8144d0d98fde1/src/libraries/System.Diagnostics.Process/tests/ProcessStandardConsoleTests.cs#L26
It's setting 437 and getting UTF8.
That would suggest it just needs to be skipped like Nano (which demonstrates why we should not detect OS capabilities by probing for regedit)
But I can't explain the results from your test app

**Comment by eiriktsarpalis** [comment]
It looks like we aren't testing anything at all if that particular heuristic is satisfied. Shouldn't we at least be falling back to UTF8?

https://github.com/dotnet/runtime/blob/d949f2232966c40d5925bcbd6f353997d93b1ce1/src/libraries/System.Diagnostics.Process/tests/ProcessStandardConsoleTests.cs#L46-L52

**Comment by danmosemsft** [comment]
Yes probably we should.

**Comment by safern** [comment]
Yeah that was my initial thought skipping it on server core because we already do that for Nano, but then the results I got from calling the native Windows APIs suggested this should work.

**Comment by ericstj** [comment]
@safern is this OK to happen in 6.0.0 or does a fix need to be made in 5.0.0?

**Comment by safern** [comment]
I think 6.0.0 is fine this is not a regression and we have the same behavior on Nano.

**Comment by eiriktsarpalis** [comment]
> I'm enabling Server Core 20H1 libraries test runs and this test failed

Out of curiosity, are we already running tests on earlier versions of server core?

**Comment by eiriktsarpalis** [comment]
@safern assuming your cherry picked changes have resolved the issue. I'm going to close this.

**Comment by danmoseley** [comment]
seems this code can now be enabled
https://github.com/dotnet/runtime/blob/96d492aafbfd583febdb88b663bd524b7f56873d/src/libraries/System.Diagnostics.Process/tests/ProcessStandardConsoleTests.cs#L35
