### ISSUE TITLE
Add a build to test the runtime repo with the daily Product build

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#42019]
We have hooks which depends on some internal parts of sdk and msbuild. These parts change over time and we only detect when we try to update the sdk version. 

The suggestion here is to pick the daily build of the installer/sdk and run the build using the daily build version. This will help us to catch the bugs\changes earlier

cc @ericstj @safern @ViktorHofer

**Comment by agocke** [comment]
The currently published builds are still non-coherent. I think we should think about this again when we have VMR working.
