### ISSUE TITLE
Error: Invalid setting 'RunConfiguration'. Invalid value 'arm64' specified for 'TargetPlatform'.

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#42017]
I'm trying to run tests on an ARM64 environment and run in to the following output when executing `dotnet test`:

> Settings file provided does not conform to required format. An error occurred while loading the settings.  Error: Invalid setting 'RunConfiguration'. Invalid value 'arm64' specified for 'TargetPlatform'.

My usual testing strategy works on x86-64, so I'm not sure if I should be running tests differently on ARM64 or if what I was doing worked by accident.

My steps are:
1. Build `./build.sh -rc Release -s clr+libs`
2. Ensure the local `.dotnet/dotnet` is on the PATH.
3. `cd src/libraries/System.Security.Cryptography.X509Certificates/tests`
4. `dotnet build`
5. `dotnet test` 

Step 5 is where I get the error.

This is on ARM64 Ubuntu 18.04.5 environment.

**Comment by vcsjones** [comment]
I was able to unblock myself by removing this line from `.runsettings`:

https://github.com/dotnet/runtime/blob/ac3595e47432b728ddccabdc280692ac0e9405f7/eng/testing/.runsettings#L13

**Comment by ViktorHofer** [comment]
@nohwnd is arm64 now supported in vstest? More precisely, is setting that configuration in the runsettings file now supported?

**Comment by nohwnd** [comment]
Will have to try that option itself, but it definitely runs on arm64 with the latest version.

**Comment by nohwnd** [comment]
Added an issue on our repo. We probably need to get some arm64 hardware to fix this properly. The platform is checked in multiple places. Are you facing some other issues when you don't force the platform? Or is that an acceptable workaround?

**Comment by ViktorHofer** [comment]
@jakub do we need to specify the platform in the runsettings file at all?

**Comment by nohwnd** [comment]
@ViktorHofer The only reason to specify it would be forcing x86 on AnyCPU assemblies on a 64-bit system. Can't think of anything else. 

Tagged the wrong Jakub I guess :)
