### ISSUE TITLE
osx-arm64 enable gcstress=c testing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#42025]
osx currently doesn't have any gcstress=`C` testing support.  We were able to get by with this for osx-x64 because the ABI and codegen  for linux-x64 and osx-x64 matched.

Since osx-arm64 ABI is unique it would be ideal if we could run gcstress.

/cc @janvorli

**Comment by janvorli** [comment]
Just a note - if we moved to using signals for everything on OSX, the GC stress C support would come almost if not completely for free with it.

**Comment by sdmaclea** [comment]
I don't know how gcstress=c will need changes to play with write no execute, but it is probably simple to fix.

**Comment by janvorli** [comment]
I was somehow thinking about x64. You are right that it would need changes to write no execute for arm64.

**Comment by sdmaclea** [comment]
Fixed by #46471
