### ISSUE TITLE
Backport AMD perf fix to 3.1

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#42034]
This is to backport the fix for: https://github.com/dotnet/runtime/issues/34478 to 3.1. This will also required this PR to be backported to avoid a regression on Alpine: https://github.com/dotnet/runtime/pull/41532.

**Comment by jkotas** [comment]
This is 6% on microbenchmarks (see https://github.com/dotnet/runtime/issues/34478#issuecomment-608141939). It sounds too small to me to meet the servicing bar.

**Comment by mangod9** [comment]
Ah, missed the only 32-bit part. Will add you to a thread on this issue.

**Comment by mangod9** [comment]
More investigation is required here, so this exact fix might not require a backport.

**Comment by mangod9** [comment]
Closing since this fix isnt required.
