### ISSUE TITLE
.NET 5 rc2 fails on macOS with "Illegal Instruction: 4"

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#42039]
### Description

Context: https://github.com/xamarin/xamarin-android/pull/5100

The `dotnet pack` command appears to be failing on CI for us with:

```
Exec
    Assembly = Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    CommandLineArguments = dotnet pack -p:Configuration=Release -p:AndroidRID=android.21-arm -p:AndroidABI=armeabi-v7a "/Users/builder/azdo/_work/4/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Runtime.proj"
    Welcome to .NET 5.0!
    ---------------------
    SDK Version: 5.0.100-rc.2.20458.11
    Telemetry
    ---------
    The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
    Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
    ----------------
    Installed an ASP.NET Core HTTPS development certificate.
    To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
    Learn about HTTPS: https://aka.ms/dotnet-https
    ----------------
    Write your first app: https://aka.ms/dotnet-hello-world
    Find out what's new: https://aka.ms/dotnet-whats-new
    Explore documentation: https://aka.ms/dotnet-docs
    Report issues and find source on GitHub: https://github.com/dotnet/core
    Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
    --------------------------------------------------------------------------------------
    /var/folders/9k/brhlbh9d729gxd3m_9j0t23w0000gn/T/tmpc81db9a1c872436bb5f037f3e6d68f71.exec.cmd: line 2: 24887 Illegal instruction: 4  dotnet pack -p:Configuration=Release -p:AndroidRID=android.21-arm -p:AndroidABI=armeabi-v7a "/Users/builder/azdo/_work/4/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Runtime.proj"
    Errors
        /Users/builder/azdo/_work/4/s/xamarin-android/build-tools/create-packs/Directory.Build.targets(52,5): error MSB3073: The command "dotnet pack -p:Configuration=Release -p:AndroidRID=android.21-arm -p:AndroidABI=armeabi-v7a "/Users/builder/azdo/_work/4/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Runtime.proj"" exited with code 132.
```
I think "Illegal instruction: 4" means that native code was compiled for a more recent macOS version than it is running on.

It seems like probably any `dotnet` command would fail, this is just the first we hit.

### Configuration

The output of `dotnet --list-sdks`:

```
$ dotnet --list-sdks
3.1.201 [/Users/builder/.dotnet/sdk]
5.0.100-preview.6.20265.2 [/Users/builder/.dotnet/sdk]
5.0.100-preview.7.20307.3 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20365.11 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20411.10 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20414.5 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20426.3 [/Users/builder/.dotnet/sdk]
5.0.100-rc.2.20458.11 [/Users/builder/.dotnet/sdk]
```

The build was downloaded from here:

* https://github.com/dotnet/installer#installers-and-binaries ->
* https://aka.ms/dotnet/net5/rc2/Sdk/dotnet-sdk-osx-x64.pkg ->
* https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.2.20458.11/dotnet-sdk-5.0.100-rc.2.20458.11-osx-x64.pkg

The CI machine is running:
```
macOS 10.14.6
architecture: X64
```

### Regression?

This worked with previous .NET 5 builds: preview7, preview8, rc1.

**Comment by am11** [comment]
With a new console application on macOS 10.14.6, dotnet 5.0.0-rc.2.20458.14 (SDK 5.0.100-rc.2.20459.18) did not threw any error with `dotnet pack -p:Configuration=Release -p:AndroidRID=android.21-arm -p:AndroidABI=armeabi-v7a` on my machine. Is there a self-contained repro that could demonstrate this error?

Note: the `-mmacosx-version-min` for CoreCLR, libraries and installers is currently `10.13`; and mono has`10.12`; so compatibility-wise, apps should work on 10.14.

**Comment by jonathanpeppers** [comment]
I added something on our CI to remove past installations, and it seems to have fixed it.

The CI machine hitting this had lots of past installs:
```
$ dotnet --list-sdks
3.1.201 [/Users/builder/.dotnet/sdk]
5.0.100-preview.6.20265.2 [/Users/builder/.dotnet/sdk]
5.0.100-preview.7.20307.3 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20365.11 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20411.10 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20414.5 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20426.3 [/Users/builder/.dotnet/sdk]
5.0.100-rc.2.20458.11 [/Users/builder/.dotnet/sdk]
```

We are installing these with this script:

https://docs.microsoft.com/dotnet/core/tools/dotnet-install-script

https://github.com/xamarin/xamarin-android/blob/ac4039d309a36467bf982df0a8f30941b5fb9642/build-tools/automation/yaml-templates/use-dot-net.yaml#L18-L25

If it doesn't come up again, maybe we can just close this. Something probably happened during installation.
