### ISSUE TITLE
System.Numeric.Tensors should be moved to runtimelab

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#42031]
We never intend to ship a stable version of this package. The correct place for it should be RuntimeLab

cc @ericstj @safern @ViktorHofer

**Comment by danmosemsft** [comment]
I wouldn’t say we never intend? More like we have no plan to. I agree it makes sense to move it.

**Comment by tannergooding** [comment]
This should be a small work item we can still do for 6.0.0

**Comment by safern** [comment]
@tannergooding should be simple following: https://github.com/dotnet/runtimelab/tree/standalone-template#standalone-experiments

**Comment by eerhardt** [comment]
This isn't required for 6.0. Moving to 7.0.

**Comment by stephentoub** [comment]
No longer relevant
