### ISSUE TITLE
GetFiles/EnumerateFiles returns invalid results for file with a particular name

### ISSUE THREAD

**Issue by jpd236** [dotnet/runtime#42107]
### Description

I am observing System.IO.Directory.EnumerateFiles and System.IO.Directory.GetFiles returning inconsistent results with the actual contents of the directory, which is hosted on a network share. A file that is present in the folder is either omitted from the listing, or returned twice. Renaming the file to a different name causes it to show up, but renaming it back causes it to disappear once again.

Here's a PowerShell session demonstrating the problem:

```
> dir \\10.1.10.9\Public\Backup\Duplicati\duplicati-b1a5979538b6e446f886af67ffc06c145*


    Directory: \\10.1.10.9\Public\Backup\Duplicati


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          8/9/2020   9:12 PM       52342077 duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes


> [System.IO.Directory]::GetFiles('\\10.1.10.9\Public\Backup\Duplicati\') | Select-String -Pattern b1a5979538b6e446f886af67ffc06c145
> Rename-Item -Path "\\10.1.10.9\Public\Backup\Duplicati\duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes" -NewName "testing"
> [System.IO.Directory]::GetFiles('\\10.1.10.9\Public\Backup\Duplicati\') | Select-String -Pattern testing

\\10.1.10.9\Public\Backup\Duplicati\testing


> Rename-Item -Path "\\10.1.10.9\Public\Backup\Duplicati\testing" -NewName "duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes"
> [System.IO.Directory]::GetFiles('\\10.1.10.9\Public\Backup\Duplicati\') | Select-String -Pattern b1a5979538b6e446f886af67ffc06c145
>
```

This was originally reported as a [Duplicati bug](https://github.com/duplicati/duplicati/issues/4303), but per the above, we think we've isolated it down to an issue with .NET APIs, since we can reproduce the problem just by invoking the APIs directly in PowerShell.

### Configuration

I believe I am running .NET Framework 4.8:

```
> Get-STDotNetVersion -LocalHost -NoSummary


ComputerName : localhost
>=4.x        : 4.8 or later
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Installed
v3.0         : Installed
v2.0.50727   : Installed
v1.1.4322    : Not installed (no key)
Ping         : True
Error        :
```

I am running Windows 10, Version	10.0.19041 Build 19041, on a Surface Book 2 (x64). Since I don't know how to get into this state or have other devices handy to test with, I'm not sure whether the issue is specific to this configuration in any way.

### Regression?

Not sure, as this appears to be unique to this file. There are over 10,000 other files in this directory which all list fine, and I have been using Duplicati to make backups (which depends on listing the files in this folder using this API and validating the list against the expected set of files) on a weekly basis over the past few months.

### Other information

The main workaround is to list the files in some other way, e.g. the "dir" command per the above, or by connecting to the drive over SFTP instead of using a direct listing.

**Comment by carlossanlop** [comment]
@jpd236 thank you for your submission. This repo tracks issues for .NET Core, not .NET Framework.

To report issues for .NET Framework, please visit https://developercommunity.visualstudio.com/spaces/61/net.html and report the issue there.

I can see that [all the duplicati csproj files](https://github.com/duplicati/duplicati/search?q=extension%3Acsproj) consume .NET Framework. If you decide to upgrade to .NET Core and you still repro the issue, please let us know here.

Or if you can repro the issue in [PowerShell Core](https://github.com/PowerShell/PowerShell) (not the integrated Windows PowerShell), please let us know, since that one is using .NET Core as well.

**Comment by jpd236** [comment]
Thank you for the background. I tested on PowerShell 6.0.0 and 7.0.3 and both appear to be working fine, so I guess this is specific to .NET Framework.
