### ISSUE TITLE
NLS `System.Globalization.Tests.CompareInfoTests.SortKeyTest` with empty string and ZWJ fails on Windows Insiders Preview

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#42115]
This is under the NLS configuration (`System.Globalization.Nls.Tests`), not sure if it's specific to the version of NLS that ships with the insider builds. Currently I'm running 10 Pro Insiders Build (Dev Channel) Build 20211, ko-KR.

https://github.com/dotnet/runtime/blob/1b18efa5b55df1cbf13838f6ba32d9d59fa147b1/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.cs#L306-L310

Raw XML output:
```xml
<test name="System.Globalization.Tests.CompareInfoTests.SortKeyTest(compareInfo: CompareInfo - , string1: \&quot;\&quot;, string2: \&quot;‌\&quot;, options: None, expectedSign: 0)" type="System.Globalization.Tests.CompareInfoTests" method="SortKeyTest" time="0.0054359" result="Fail">
  <failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\r\nExpected: -1\r\nActual:   0]]></message>
    <stack-trace><![CDATA[   at System.Globalization.Tests.CompareInfoTests.SortKeyTest(CompareInfo compareInfo, String string1, String string2, CompareOptions options, Int32 expectedSign) in C:\Users\gotos\source\repos\runtime\src\libraries\System.Globalization\tests\CompareInfo\CompareInfoTests.cs:line 371]]></stack-trace>
  </failure>
</test>
```

cc @tarekgh

**Comment by safern** [comment]
It seems like what is being affected and returning a different value now is: `Math.Sign(compareInfo.Compare(string1, string2, options))`

@tarekgh could it be a bug introduced in Windows where `"\u200c` is not having a zero weight?

**Comment by tarekgh** [comment]
@Gnbrkm41 could you please try that with en-US instead of invariant? I am seeing many changes in Windows side for Invariant culture and this can be one of them.

**Comment by tarekgh** [comment]
I have confirmed this is a regression in Windows (repro on version 20201 too). I am talking to Windows team about it. but it looks we need to workaround it in our tests for now.
