### ISSUE TITLE
System.Diagnostics.Tests.EventLogConfigurationTests.EventLogConfiguration_CheckProperties_RemainsTheSame fails locally

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#42117]
Using Windows 10 Pro Insiders Preview Build 20211 x64 ko-KR.

```xml
<test name="System.Diagnostics.Tests.EventLogConfigurationTests.EventLogConfiguration_CheckProperties_RemainsTheSame(logName: \&quot;Microsoft-Windows-TaskScheduler/Operational\&quot;)" type="System.Diagnostics.Tests.EventLogConfigurationTests" method="EventLogConfiguration_CheckProperties_RemainsTheSame" time="0.0480149" result="Fail">
  <failure exception-type="Xunit.Sdk.NotEmptyException">
    <message><![CDATA[Assert.NotEmpty() Failure]]></message>
    <stack-trace><![CDATA[   at System.Diagnostics.Tests.EventLogConfigurationTests.EventLogConfiguration_CheckProperties_RemainsTheSame(String logName) in C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\tests\System\Diagnostics\Reader\EventLogConfigurationTests.cs:line 42]]></stack-trace>
  </failure>
</test>
```

https://github.com/dotnet/runtime/blob/1b18efa5b55df1cbf13838f6ba32d9d59fa147b1/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogConfigurationTests.cs#L42

Not sure if this something that's normally supposed to be filled with something or if this is a Windows bug.

**Comment by ericstj** [comment]
Looks to me like the `Microsoft-Windows-TaskScheduler/Operational` exists, but registered with an empty provider name.  
@Anipik have you seen anything like this?

**Comment by Gnbrkm41** [comment]
I'm not hitting this issue on my machine anymore (not sure what fixed it). Feel free to close the issue if you think it's okay...

**Comment by danmosemsft** [comment]
Let's close pending any future report - maybe a Windows update?
