### ISSUE TITLE
Failure in CrossDac packaging (official builds only)

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#42123]
e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=809503&view=logs&j=7a1cd7fd-8fa9-5ec1-980e-a4eb83346ea9&t=a7278a6c-3e31-578e-d34e-bccb203bb339&l=52

Filing this for record keeping purposes. The fix is in https://github.com/dotnet/runtime/pull/42096 and pending merge

**Comment by directhex** [comment]
@hoyosjs @janvorli tagging you both for awareness. I just need (closed!) issues on a dashboard for breakages, for CI council. This should be fine when 42096 is merged

**Comment by safern** [comment]
@directhex I removed the `blocking-clean-ci` label since it just affects official build.

**Comment by directhex** [comment]
OK, fair
