### ISSUE TITLE
osx-arm64 System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#42130]
When running w/ Rosetta emulation, System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture is returning the emulated Architecture as opposed to the actual architecture.

It is unclear whether this is the correct or incorrect behavior for this API.  It is probably TBD.

**Comment by jkotas** [comment]
> System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture is returning the emulated Architecture 

This is correct behavior. E.g. if you run .NET Core ARM on Linux x64 under QEMU, this API returns ARM.
