### ISSUE TITLE
Security review for ILCompiler.Reflection.ReadyToRun

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#42147]
This issue is created as part of https://github.com/dotnet/runtime/issues/41379. This include:

- Understanding what do we need to do to ensure ILCompiler.Reflection.ReadyToRun is secure enough for releasing through Nuget, and
- Perform the necessary work to ensure the binary is secure.

This issue is purely mean for tracking to work to be completed. Specific security issues found should go through the standard process outlined [here](https://github.com/dotnet/runtime#reporting-security-issues-and-security-bugs).

**Comment by mangod9** [comment]
@cshung assume this can be closed?

**Comment by mangod9** [comment]
Closing since this has already been published.
