### ISSUE TITLE
Q - How to make the DefaultCredentials = true work again using SocketsMessageHandler?

### ISSUE THREAD

**Issue by kogratte** [dotnet/runtime#42144]
Hello!

I'm currently facing an issue using aspnetcore 2.2 and IIS

I'm working on a software A using aspnetcore 2.2, running on PoolA authenticated as PoolAIdentity, wich is trying to call api B, running on PoolB authenticated as PoolBIdentity.

What I want is that app B receive the call from A with the A pool identity's, wich does not seems to be working.

Using .Net Fwk 4.x, my code would look like this:
```
using (var client = new HttpClient(new HttpClientHandler { useDefaultCredentials = true }) {
   /// Something usefull
}
```
Using aspnet core, my code is looking like this:
```
var apiUri = new Uri(appConfig["ApiUrls:MyApi"]);
services.AddHttpClient("myApi", c => {
  c.BaseAddress = apiUri;
})
.ConfigurePrimaryHttpMessageHandler(() => {
    var credentialsCache = new CredentialCache { { apiUri, "NTLM", CredentialCache.DefaultNetworkCredentials } };
    return new SocketsMessageHandler { Credentials = credentialsCache };
});

services.AddTransient<IService, Service>();
with IService defined like this:

public Service(IHttpClientFactory factory)
{
   _client = factory.CreateClient("myApi");
}
```
I've tryed many things, but I'm always receiving a 401 from "myApi". When I look on IIS logs, request handled by app B seems to be never authenticated using the A pool identity's.

What am I doing wrong?

**Comment by am11** [comment]
This was previously moved to aspnetcore from https://github.com/dotnet/runtime/issues/29556.

**Comment by ericstj** [comment]
@dotnet/ncl does the sample code above look correct for `useDefaultCredentials` behavior on a `SocketsMessageHandler`?

**Comment by wfurt** [comment]
Can you try simple HttpClient without any pooling? Using `DefaultCredentials` should take identity off your aspnet app. You can can Wireshark and check if you see negotiations. Make sure NTLM is enabled since that is generally deprecated.

**Comment by CarnaViire** [comment]
Triage: the problem doesn't seem specific to HttpClientFactory, more related to SocketsHttpHandler. It also needs additional information to be actionable. Closing for now, but feel free to reopen if the problem still stands and you can provide additional info.
