### ISSUE TITLE
System.Net.Http.HttpRequestException is not marked as [Serializable]

### ISSUE THREAD

**Issue by magole** [dotnet/runtime#42154]
This issue is related to [this issue](https://github.com/dotnet/runtime/issues/16055).

Projects like [Orleans](https://dotnet.github.io/orleans/) require types and especially exceptions to be serializable. Most .NET Core exceptions are already marked as such.

The ask is to mark **HttpRequestException** as **[Serializable]** and add the requisite protected ctors.

**Comment by GrabYourPitchforks** [comment]
API proposal:

```cs
namespace System.Net.Http
{
    [Serializable] // ADD this attribute
    public class HttpRequestException : ISerializable // ADD this interface
    {
        protected HttpRequestException(SerializationInfo info, StreamingContext context); // ADD this ctor
        public virtual void GetObjectData(SerializationInfo info, StreamingContext context); // ADD this method
    }
}
```

This is a request from the Orleans team and matches when we said we'd allow new serialization ctors to be added: (a) it must be an exception-derived type, and (b) the type must exist across both .NET Core and .NET framework. The `HttpRequestException` type meets both of these.

I'll create a separate issue to track allowing `Exception` objects to be serialized without using `BinaryFormatter` or other unsafe-style serialization tech.

**Comment by GrabYourPitchforks** [comment]
Opened https://github.com/dotnet/designs/issues/158 to track creating safe `Exception` serialization tech.

**Comment by scalablecory** [comment]
@dotnet/ncl

**Comment by scalablecory** [comment]
@GrabYourPitchforks this class is not sealed, adding an interface is a breaking change no?

**Comment by GrabYourPitchforks** [comment]
It's not a breaking compile-time change. It's potentially a breaking runtime change in that if somebody marked their subclassed type `[Serializable]` without also implementing `ISerializable` (which honestly would be very, very weird for an Exception to do), the serialized payload format would now change.

**Comment by GrabYourPitchforks** [comment]
Oh, derp, of course the base type already implements the interface. I'll update the proposal.

**Comment by terrajobst** [comment]
* Seems fine per our guidance
* We won't do this for all exception, but only for exceptions that exist in both .NET Framework and .NET Core
* Specifically, we won't do this for .NET Core-only exceptions
* And moving forward, we'll phase out `BinaryFormatter` anyways

```C#
namespace System.Net.Http
{
    [Serializable]
    public class HttpRequestException
    {
        protected HttpRequestException(SerializationInfo info, StreamingContext context);
        public override void GetObjectData(SerializationInfo info, StreamingContext context);
    }
}
```

**Comment by stephentoub** [comment]
Whoever implements this will need to make sure that the type serializes/deserializes correctly in both directions between .NET Core and .NET Framework, otherwise it'll defeat the purpose of this.  And to that end, a) there have been several new members added to HttpRequestException in .NET Core, so they'll need to be properly dealt with, and b) the implementation on .NET Framework uses the "safe serialization" mechanism, and I'm not sure that'll "just work".

**Comment by deeprobin** [comment]
@stephentoub You're welcome to assign me

**Comment by danmoseley** [comment]
@GrabYourPitchforks as this missed 6.0, and in 7.0 we expect to [disable BinaryFormatter by default](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#net-7-nov-2022) and the [hypothetical replacement does not depend on ISerializable.](https://github.com/dotnet/runtime/issues/43482)

I realize this package ships on .NET Framework as well, but as noted above, it must deserialize on .NET Core too.

**Comment by danmoseley** [comment]
@GrabYourPitchforks thoughts?

**Comment by danmoseley** [comment]
@GrabYourPitchforks ...

**Comment by GrabYourPitchforks** [comment]
Spoke offline with Steve about this. Since the scenario of cross-serializing between netfx and netcore won't be supported, the "exceptions which exist on both platforms" rule of thumb really doesn't apply, since we really won't be able to support the scenario that rule of thumb was trying to drive at. I'm supportive of just closing this issue as won't-fix.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/60600#issuecomment-1128079867 mentioned  by @bartonjs  also describes the cross appdomain scenario. Are we consistent, and is our guidance clear? Or is cross appdomain not relevant here?

**Comment by stephentoub** [comment]
That isn't relevant here.
