### ISSUE TITLE
Will Socket support to use Span<byte> as buffer?

### ISSUE THREAD

**Issue by yukozh** [dotnet/runtime#42173]

**Comment by stephentoub** [comment]
With what operation? There are already Socket.Send/Receive overloads that work with spans.

**Comment by yukozh** [comment]
@stephentoub Which .net core version I have to use? I did not see that in .NET Core 3.1

**Comment by svick** [comment]
@yukozh [`Socket.Send(ReadOnlySpan<byte>)`](https://apisof.net/catalog/System.Net.Sockets.Socket.Send(ReadOnlySpan%3CByte%3E)) and [`Socket.Receive(Span<byte>)`](https://apisof.net/catalog/System.Net.Sockets.Socket.Receive(Span%3CByte%3E)) were added in .Net Core 2.1.

**Comment by yukozh** [comment]
@svick But SendAsync & ReceiveAsync does not support that. So how to use these methods for async usage?

**Comment by stephentoub** [comment]
Spans can't be on the heap, so you can't use them with async methods. There are overloads of SendAsync/ReceiveAsync that work with `Memory<T>` instead.

**Comment by yukozh** [comment]
How to build high performance apps using the sync methods? Will it block the threads?

**Comment by stephentoub** [comment]
You can build high-performance apps using either the sync or async methods. But the sync APIs do block threads, so if you want to build a highly-scalable app, you should use the async methods when performing networking operations.

**Comment by yukozh** [comment]
Thanks
