### ISSUE TITLE
GC brick alignment question

### ISSUE THREAD

**Issue by yowl** [dotnet/runtime#42223]
I'm working on an issue (https://github.com/dotnet/corert/issues/8317 in the WebAssembly backend (a 32 bit target using conservative garbage collection with alignment (i32 - 4, i64 - 8) requirements for CoreRT (https://github.com/dotnet/corert) and I have a question about the code in `gc.cpp` `gc_heap::find_first_object`  .  About 40 lines in there is
```
        o = ((prev_brick < min_brick) ? first_object :
                      brick_address (prev_brick) + brick_entry - 1);
```
Is it valid for `o` to _not_ be 4 byte aligned as that is what I am seeing?  I just want to know so I can decide if it worth investigating why, more than likely I've got something wrong in the compilation/allocation.

If it helps I changed the above code to 
```
        if(prev_brick < min_brick){
            o = first_object;
        }
        else
        {
              o = brick_address (prev_brick) + brick_entry - 1;
              if(((int)o & 3) != 0)
              {
                  printf("caclulated address not aligned %p prev_brick %p, brick_address %p brick_entry %d\n", o, prev_brick, brick_address(prev_brick), brick_entry);
              }
        }
```
and it prints (sic)
```
caclulated address not aligned 0x13d16fe prev_brick 0x272, brick_address 0x13d1000 brick_entry 1791
```

**Comment by Maoni0** [comment]
it's definitely not valid if the object is not 4-byte aligned on 32-bit. 

`brick_address (prev_brick) + brick_entry - 1)`

should point to the beginning of an object which means it should be 4-byte aligned. if not it means there's a heap corruption.

**Comment by yowl** [comment]
Great, thanks will close
