### ISSUE TITLE
Add generic override ConfiguredAsyncDisposable

### ISSUE THREAD

**Issue by kronic** [dotnet/runtime#42248]
## Background and Motivation
``` C#
await using FileStream fileStream = File.OpenRead(fullFileName);

await using ConfiguredAsyncDisposable fileStream = File.OpenRead(xsdFullFileName).ConfigureAwait(false);
```
## Proposed API
```diff
namespace System.Threading.Tasks
{
    public static class TaskAsyncEnumerableExtensions
    {   
+       public static ConfiguredAsyncDisposable<T> ConfigureAwait<T>(this T source, bool continueOnCapturedContext) where T : IAsyncDisposable
    }
}
```
## Usage Examples
``` C#
await using var fileStream = File.OpenRead(fullFileName).ConfigureAwait(false);
```
## Alternative Designs
No
## Risks
I do not know

**Comment by stephentoub** [comment]
What problem is this solving? What does this help? What is `ConfiguredAsyncDisposable<T>`?

**Comment by kronic** [comment]
@stephentoub 
```C#
public async Task<XElement> ReadXElementAsync(string fullFileName)
{
	await using FileStream fileStream = File.OpenRead(fullFileName);

	XElement xElement = await XElement.LoadAsync
		(
			fileStream,
			LoadOptions.None,
			CancellationToken.None
		)
		.ConfigureAwait(false);

	return xElement;
}
//not working
public async Task<XElement> ReadXElement1Async(string fullFileName)
{
	//compile error
	await using FileStream fileStream = File.OpenRead(fullFileName).ConfigureAwait(false);

	XElement xElement = await XElement.LoadAsync
		(
			fileStream,
			LoadOptions.None,
			CancellationToken.None
		)
		.ConfigureAwait(false);

	return xElement;
}
```

**Comment by stephentoub** [comment]
The proposed API won't help with that.

> How can I use ConfigureAwait(false) along with using?

Either:
```C#
FileStream fs = File.OpenRead("");
await using (fs.ConfigureAwait(false))
{
    ...
}
```
or
```C#
FileStream fs = File.OpenRead("");
await using var _ = fs.ConfigureAwait(false);
...
```

**Comment by kronic** [comment]
@stephentoub 
```C#
```

**Comment by stephentoub** [comment]
> why does not help here is an example?

Because the `await using` is being applied in your example to the `FileStream`, not to the `ConfiguredAsyncDisposable`.

**Comment by kronic** [comment]
@stephentoub ok sample ReadXElement4Async is work?

**Comment by stephentoub** [comment]
> ok sample ReadXElement4Async is worked?

Sort of... by using `var` that's the same as if you wrote:
```C#
await using ConfiguredAsyncDisposable<FileStream> fileStream = File.OpenRead(fullFileName).ConfigureAwait(false);
```
as at that point you've just created a disposable wrapper that let's you get at the wrapped instance (in your proposal using an implicit cast).  But that's incredibly error prone, as it means:
```C#
await using var fileStream = File.OpenRead(fullFileName).ConfigureAwait(false);
```
and
```C#
await using FileStream fileStream = File.OpenRead(fullFileName).ConfigureAwait(false);
```
end up having subtly different semantics.

It also only does what you want with the `var` when the instance is cast to a FileStream, e.g. this will fail to compile:
```C#
await using var fileStream = File.OpenRead(fullFileName).ConfigureAwait(false);
int count = fileStream.Read(buffer, 0, buffer.Length);
```
because the members of FileStream aren't lifted to this struct wrapper.

**Comment by stephentoub** [comment]
I don't think the API as proposed measurably improves things, and it has the cited problems with it, so I'm going to close this.  But thanks for the interest, and if you have other ideas for how to improve it, please open new issues. Thanks!
