### ISSUE TITLE
unix: child process can cause parent hanging while getting Console.CursorTop/Left

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#42247]
I'm investigating an issue where `dotnet test` hangs and prints out an escape sequence:
```
Microsoft (R) Test Execution Command Line Tool Version 16.3.0-dev+55e7e45431c9c05656c999b902686e7402664573
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
^[[55;1R^[[55;9R
```
The `dotnet test` involves a test host process and an xunit child process. The issue happens because the child turns on echoing while the parent is reading the cursor position from standard in. The cursor position gets echoed, and the parent is blocked waiting for the input here:

https://github.com/dotnet/runtime/blob/088504d243d24018ca258c726ec983e2ee20e840/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L507

The issue can be reproduced with this code (using [Tmds.ExecFunction](https://www.nuget.org/packages/Tmds.ExecFunction)).
```cs
    class Program
    {
        static void Main(string[] args)
        {
            if (ExecFunction.IsExecFunctionCommand(args))
            {
                ExecFunction.Program.Main(args);
            }
            else
            {
                const int ThreadCount = 4;
                Thread[] threads = new Thread[ThreadCount];
                for (int i = 0; i < threads.Length; i++)
                {
                    var thread = new Thread(CreateDotnetChildProcesses);
                    threads[i] = thread;
                    thread.Start();
                }
                while (true)
                {
                    int i = Console.CursorTop;
                    System.Console.Out.Write(".");
                    System.Console.Out.Flush();
                }
            }
        }
        private static void CreateDotnetChildProcesses(object obj)
        {
            while (true)
            {
                ExecFunction.Run(() =>
                {
                    var consoleIn = Console.In;
                });
            }
        }
    }
```
Running this program will print out dots until at some point the cursor position is echoed.

This is the behaviour of .NET regarding echoing and child processes:
- When a child process is started, and there is no on-going read, echoing is turned on. This is to make child processes work that require echoing, which is on by default (e.g. `vi`).
- When a .NET child process terminates, it restores the terminal to settings captured at start.

The issue happens when a .NET child that terminates turns echoing back on, while a cursor read is in progress in the parent.

cc @eiriktsarpalis @stephentoub @omajid @RheaAyase

**Comment by stephentoub** [comment]
Does this repro in 3.1 or did we introduce it in 5.0?

**Comment by tmds** [comment]
This repros with 3.1.

**Comment by tmds** [comment]
https://github.com/dotnet/runtime/pull/42303 will reduce chances of the hang happening. I think it isn't possible to eliminate it completely (see https://github.com/dotnet/runtime/pull/42303#issuecomment-693985108). I will close the issue.
