### ISSUE TITLE
[mono] Tracking: Implement `System.Runtime.Intrinsics.Arm.AdvSimd`

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#42266]
### System.Runtime.Intrinsics.Arm.AdvSimd:

- [x] IsSupported
- [x] Abs
- [x] AbsSaturate
- [x] AbsScalar
- [x] AbsoluteCompareGreaterThan
- [x] AbsoluteCompareGreaterThanOrEqual
- [x] AbsoluteCompareLessThan
- [x] AbsoluteCompareLessThanOrEqual
- [x] AbsoluteDifference
- [x] AbsoluteDifferenceAdd
- [x] AbsoluteDifferenceWideningLower
- [x] AbsoluteDifferenceWideningLowerAndAdd
- [x] AbsoluteDifferenceWideningUpper
- [x] AbsoluteDifferenceWideningUpperAndAdd
- [x] Add
- [x] AddHighNarrowingLower
- [x] AddHighNarrowingUpper
- [x] AddPairwise
- [x] AddPairwiseWidening
- [x] AddPairwiseWideningAndAdd
- [x] AddPairwiseWideningAndAddScalar
- [x] AddPairwiseWideningScalar
- [x] AddRoundedHighNarrowingLower
- [x] AddRoundedHighNarrowingUpper
- [x] AddSaturate
- [x] AddSaturateScalar
- [x] AddScalar
- [x] AddWideningLower
- [x] AddWideningUpper
- [x] And
- [x] BitwiseClear
- [x] BitwiseSelect
- [x] Ceiling
- [x] CeilingScalar
- [x] CompareEqual
- [x] CompareGreaterThan
- [x] CompareGreaterThanOrEqual
- [x] CompareLessThan
- [x] CompareLessThanOrEqual
- [x] CompareTest
- [x] ConvertToInt32RoundAwayFromZero
- [x] ConvertToInt32RoundAwayFromZeroScalar
- [x] ConvertToInt32RoundToEven
- [x] ConvertToInt32RoundToEvenScalar
- [x] ConvertToInt32RoundToNegativeInfinity
- [x] ConvertToInt32RoundToNegativeInfinityScalar
- [x] ConvertToInt32RoundToPositiveInfinity
- [x] ConvertToInt32RoundToPositiveInfinityScalar
- [x] ConvertToInt32RoundToZero
- [x] ConvertToInt32RoundToZeroScalar
- [x] ConvertToSingle
- [x] ConvertToSingleScalar
- [x] ConvertToUInt32RoundAwayFromZero
- [x] ConvertToUInt32RoundAwayFromZeroScalar
- [x] ConvertToUInt32RoundToEven
- [x] ConvertToUInt32RoundToEvenScalar
- [x] ConvertToUInt32RoundToNegativeInfinity
- [x] ConvertToUInt32RoundToNegativeInfinityScalar
- [x] ConvertToUInt32RoundToPositiveInfinity
- [x] ConvertToUInt32RoundToPositiveInfinityScalar
- [x] ConvertToUInt32RoundToZero
- [x] ConvertToUInt32RoundToZeroScalar
- [x] DivideScalar
- [x] DuplicateSelectedScalarToVector128
- [x] DuplicateSelectedScalarToVector64
- [x] DuplicateToVector128
- [x] DuplicateToVector64
- [x] Extract
- [x] ExtractNarrowingLower
- [x] ExtractNarrowingSaturateLower
- [x] ExtractNarrowingSaturateUnsignedLower
- [x] ExtractNarrowingSaturateUnsignedUpper
- [x] ExtractNarrowingSaturateUpper
- [x] ExtractNarrowingUpper
- [x] ExtractVector128
- [x] ExtractVector64
- [x] Floor
- [x] FloorScalar
- [x] FusedAddHalving
- [x] FusedAddRoundedHalving
- [x] FusedMultiplyAdd
- [x] FusedMultiplyAddNegatedScalar
- [x] FusedMultiplyAddScalar
- [x] FusedMultiplySubtract
- [x] FusedMultiplySubtractNegatedScalar
- [x] FusedMultiplySubtractScalar
- [x] FusedSubtractHalving
- [x] Insert
- [x] InsertScalar
- [x] LeadingSignCount
- [x] LeadingZeroCount
- [x] LoadAndInsertScalar
- [x] LoadAndReplicateToVector128
- [x] LoadAndReplicateToVector64
- [x] LoadVector128
- [x] LoadVector64
- [x] Max
- [x] MaxNumber
- [x] MaxNumberScalar
- [x] MaxPairwise
- [x] Min
- [x] MinNumber
- [x] MinNumberScalar
- [x] MinPairwise
- [x] Multiply
- [x] MultiplyAdd
- [x] MultiplyAddByScalar
- [x] MultiplyAddBySelectedScalar
- [x] MultiplyByScalar
- [x] MultiplyBySelectedScalar
- [x] MultiplyBySelectedScalarWideningLower
- [x] MultiplyBySelectedScalarWideningLowerAndAdd
- [x] MultiplyBySelectedScalarWideningLowerAndSubtract
- [x] MultiplyBySelectedScalarWideningUpper
- [x] MultiplyBySelectedScalarWideningUpperAndAdd
- [x] MultiplyBySelectedScalarWideningUpperAndSubtract
- [x] MultiplyDoublingByScalarSaturateHigh
- [x] MultiplyDoublingBySelectedScalarSaturateHigh
- [x] MultiplyDoublingSaturateHigh
- [x] MultiplyDoublingWideningLowerAndAddSaturate
- [x] MultiplyDoublingWideningLowerAndSubtractSaturate
- [x] MultiplyDoublingWideningLowerByScalarAndAddSaturate
- [x] MultiplyDoublingWideningLowerByScalarAndSubtractSaturate
- [x] MultiplyDoublingWideningLowerBySelectedScalarAndAddSaturate
- [x] MultiplyDoublingWideningLowerBySelectedScalarAndSubtractSaturate
- [x] MultiplyDoublingWideningSaturateLower
- [x] MultiplyDoublingWideningSaturateLowerByScalar
- [x] MultiplyDoublingWideningSaturateLowerBySelectedScalar
- [x] MultiplyDoublingWideningSaturateUpper
- [x] MultiplyDoublingWideningSaturateUpperByScalar
- [x] MultiplyDoublingWideningSaturateUpperBySelectedScalar
- [x] MultiplyDoublingWideningUpperAndAddSaturate
- [x] MultiplyDoublingWideningUpperAndSubtractSaturate
- [x] MultiplyDoublingWideningUpperByScalarAndAddSaturate
- [x] MultiplyDoublingWideningUpperByScalarAndSubtractSaturate
- [x] MultiplyDoublingWideningUpperBySelectedScalarAndAddSaturate
- [x] MultiplyDoublingWideningUpperBySelectedScalarAndSubtractSaturate
- [x] MultiplyRoundedDoublingByScalarSaturateHigh
- [x] MultiplyRoundedDoublingBySelectedScalarSaturateHigh
- [x] MultiplyRoundedDoublingSaturateHigh
- [x] MultiplyScalar
- [x] MultiplyScalarBySelectedScalar
- [x] MultiplySubtract
- [x] MultiplySubtractByScalar
- [x] MultiplySubtractBySelectedScalar
- [x] MultiplyWideningLower
- [x] MultiplyWideningLowerAndAdd
- [x] MultiplyWideningLowerAndSubtract
- [x] MultiplyWideningUpper
- [x] MultiplyWideningUpperAndAdd
- [x] MultiplyWideningUpperAndSubtract
- [x] Negate
- [x] NegateSaturate
- [x] NegateScalar
- [x] Not
- [x] Or
- [x] OrNot
- [x] PolynomialMultiply
- [x] PolynomialMultiplyWideningLower
- [x] PolynomialMultiplyWideningUpper
- [x] PopCount
- [x] ReciprocalEstimate
- [x] ReciprocalSquareRootEstimate
- [x] ReciprocalSquareRootStep
- [x] ReciprocalStep
- [x] ReverseElement16
- [x] ReverseElement32
- [x] ReverseElement8
- [x] RoundAwayFromZero
- [x] RoundAwayFromZeroScalar
- [x] RoundToNearest
- [x] RoundToNearestScalar
- [x] RoundToNegativeInfinity
- [x] RoundToNegativeInfinityScalar
- [x] RoundToPositiveInfinity
- [x] RoundToPositiveInfinityScalar
- [x] RoundToZero
- [x] RoundToZeroScalar
- [x] ShiftArithmetic
- [x] ShiftArithmeticRounded
- [x] ShiftArithmeticRoundedSaturate
- [x] ShiftArithmeticRoundedSaturateScalar
- [x] ShiftArithmeticRoundedScalar
- [x] ShiftArithmeticSaturate
- [x] ShiftArithmeticSaturateScalar
- [x] ShiftArithmeticScalar
- [x] ShiftLeftAndInsert
- [x] ShiftLeftAndInsertScalar
- [x] ShiftLeftLogical
- [x] ShiftLeftLogicalSaturate
- [x] ShiftLeftLogicalSaturateScalar
- [x] ShiftLeftLogicalSaturateUnsigned
- [x] ShiftLeftLogicalSaturateUnsignedScalar
- [x] ShiftLeftLogicalScalar
- [x] ShiftLeftLogicalWideningLower
- [x] ShiftLeftLogicalWideningUpper
- [x] ShiftLogical
- [x] ShiftLogicalRounded
- [x] ShiftLogicalRoundedSaturate
- [x] ShiftLogicalRoundedSaturateScalar
- [x] ShiftLogicalRoundedScalar
- [x] ShiftLogicalSaturate
- [x] ShiftLogicalSaturateScalar
- [x] ShiftLogicalScalar
- [x] ShiftRightAndInsert
- [x] ShiftRightAndInsertScalar
- [x] ShiftRightArithmetic
- [x] ShiftRightArithmeticAdd
- [x] ShiftRightArithmeticAddScalar
- [x] ShiftRightArithmeticNarrowingSaturateLower
- [x] ShiftRightArithmeticNarrowingSaturateUnsignedLower
- [x] ShiftRightArithmeticNarrowingSaturateUnsignedUpper
- [x] ShiftRightArithmeticNarrowingSaturateUpper
- [x] ShiftRightArithmeticRounded
- [x] ShiftRightArithmeticRoundedAdd
- [x] ShiftRightArithmeticRoundedAddScalar
- [x] ShiftRightArithmeticRoundedNarrowingSaturateLower
- [x] ShiftRightArithmeticRoundedNarrowingSaturateUnsignedLower
- [x] ShiftRightArithmeticRoundedNarrowingSaturateUnsignedUpper
- [x] ShiftRightArithmeticRoundedNarrowingSaturateUpper
- [x] ShiftRightArithmeticRoundedScalar
- [x] ShiftRightArithmeticScalar
- [x] ShiftRightLogical
- [x] ShiftRightLogicalAdd
- [x] ShiftRightLogicalAddScalar
- [x] ShiftRightLogicalNarrowingLower
- [x] ShiftRightLogicalNarrowingSaturateLower
- [x] ShiftRightLogicalNarrowingSaturateUpper
- [x] ShiftRightLogicalNarrowingUpper
- [x] ShiftRightLogicalRounded
- [x] ShiftRightLogicalRoundedAdd
- [x] ShiftRightLogicalRoundedAddScalar
- [x] ShiftRightLogicalRoundedNarrowingLower
- [x] ShiftRightLogicalRoundedNarrowingSaturateLower
- [x] ShiftRightLogicalRoundedNarrowingSaturateUpper
- [x] ShiftRightLogicalRoundedNarrowingUpper
- [x] ShiftRightLogicalRoundedScalar
- [x] ShiftRightLogicalScalar
- [x] SignExtendWideningLower
- [x] SignExtendWideningUpper
- [x] SqrtScalar
- [x] Store
- [x] StoreSelectedScalar
- [x] Subtract
- [x] SubtractHighNarrowingLower
- [x] SubtractHighNarrowingUpper
- [x] SubtractRoundedHighNarrowingLower
- [x] SubtractRoundedHighNarrowingUpper
- [x] SubtractSaturate
- [x] SubtractSaturateScalar
- [x] SubtractScalar
- [x] SubtractWideningLower
- [x] SubtractWideningUpper
- [x] VectorTableLookup
- [x] VectorTableLookupExtension
- [x] Xor
- [x] ZeroExtendWideningLower
- [x] ZeroExtendWideningUpper

### System.Runtime.Intrinsics.Arm.AdvSimd.Arm64:

- [x] IsSupported
- [x] Abs
- [x] AbsSaturate
- [x] AbsSaturateScalar
- [x] AbsScalar
- [x] AbsoluteCompareGreaterThan
- [x] AbsoluteCompareGreaterThanOrEqual
- [x] AbsoluteCompareGreaterThanOrEqualScalar
- [x] AbsoluteCompareGreaterThanScalar
- [x] AbsoluteCompareLessThan
- [x] AbsoluteCompareLessThanOrEqual
- [x] AbsoluteCompareLessThanOrEqualScalar
- [x] AbsoluteCompareLessThanScalar
- [x] AbsoluteDifference
- [x] AbsoluteDifferenceScalar
- [x] Add
- [x] AddAcross
- [x] AddAcrossWidening
- [x] AddPairwise
- [x] AddPairwiseScalar
- [x] AddSaturate
- [x] AddSaturateScalar
- [x] Ceiling
- [x] CompareEqual
- [x] CompareEqualScalar
- [x] CompareGreaterThan
- [x] CompareGreaterThanOrEqual
- [x] CompareGreaterThanOrEqualScalar
- [x] CompareGreaterThanScalar
- [x] CompareLessThan
- [x] CompareLessThanOrEqual
- [x] CompareLessThanOrEqualScalar
- [x] CompareLessThanScalar
- [x] CompareTest
- [x] CompareTestScalar
- [x] ConvertToDouble
- [x] ConvertToDoubleScalar
- [x] ConvertToDoubleUpper
- [x] ConvertToInt64RoundAwayFromZero
- [x] ConvertToInt64RoundAwayFromZeroScalar
- [x] ConvertToInt64RoundToEven
- [x] ConvertToInt64RoundToEvenScalar
- [x] ConvertToInt64RoundToNegativeInfinity
- [x] ConvertToInt64RoundToNegativeInfinityScalar
- [x] ConvertToInt64RoundToPositiveInfinity
- [x] ConvertToInt64RoundToPositiveInfinityScalar
- [x] ConvertToInt64RoundToZero
- [x] ConvertToInt64RoundToZeroScalar
- [x] ConvertToSingleLower
- [x] ConvertToSingleRoundToOddLower
- [x] ConvertToSingleRoundToOddUpper
- [x] ConvertToSingleUpper
- [x] ConvertToUInt64RoundAwayFromZero
- [x] ConvertToUInt64RoundAwayFromZeroScalar
- [x] ConvertToUInt64RoundToEven
- [x] ConvertToUInt64RoundToEvenScalar
- [x] ConvertToUInt64RoundToNegativeInfinity
- [x] ConvertToUInt64RoundToNegativeInfinityScalar
- [x] ConvertToUInt64RoundToPositiveInfinity
- [x] ConvertToUInt64RoundToPositiveInfinityScalar
- [x] ConvertToUInt64RoundToZero
- [x] ConvertToUInt64RoundToZeroScalar
- [x] Divide
- [x] DuplicateSelectedScalarToVector128
- [x] DuplicateToVector128
- [x] ExtractNarrowingSaturateScalar
- [x] ExtractNarrowingSaturateUnsignedScalar
- [x] Floor
- [x] FusedMultiplyAdd
- [x] FusedMultiplyAddByScalar
- [x] FusedMultiplyAddBySelectedScalar
- [x] FusedMultiplyAddScalarBySelectedScalar
- [x] FusedMultiplySubtract
- [x] FusedMultiplySubtractByScalar
- [x] FusedMultiplySubtractBySelectedScalar
- [x] FusedMultiplySubtractScalarBySelectedScalar
- [x] InsertSelectedScalar
- [x] LoadAndReplicateToVector128
- [x] Max
- [x] MaxAcross
- [x] MaxNumber
- [x] MaxNumberAcross
- [x] MaxNumberPairwise
- [x] MaxNumberPairwiseScalar
- [x] MaxPairwise
- [x] MaxPairwiseScalar
- [x] MaxScalar
- [x] Min
- [x] MinAcross
- [x] MinNumber
- [x] MinNumberAcross
- [x] MinNumberPairwise
- [x] MinNumberPairwiseScalar
- [x] MinPairwise
- [x] MinPairwiseScalar
- [x] MinScalar
- [x] Multiply
- [x] MultiplyByScalar
- [x] MultiplyBySelectedScalar
- [x] MultiplyDoublingSaturateHighScalar
- [x] MultiplyDoublingScalarBySelectedScalarSaturateHigh
- [x] MultiplyDoublingWideningAndAddSaturateScalar
- [x] MultiplyDoublingWideningAndSubtractSaturateScalar
- [x] MultiplyDoublingWideningSaturateScalar
- [x] MultiplyDoublingWideningSaturateScalarBySelectedScalar
- [x] MultiplyDoublingWideningScalarBySelectedScalarAndAddSaturate
- [x] MultiplyDoublingWideningScalarBySelectedScalarAndSubtractSaturate
- [x] MultiplyExtended
- [x] MultiplyExtendedByScalar
- [x] MultiplyExtendedBySelectedScalar
- [x] MultiplyExtendedScalar
- [x] MultiplyExtendedScalarBySelectedScalar
- [x] MultiplyRoundedDoublingSaturateHighScalar
- [x] MultiplyRoundedDoublingScalarBySelectedScalarSaturateHigh
- [x] MultiplyScalarBySelectedScalar
- [x] Negate
- [x] NegateSaturate
- [x] NegateSaturateScalar
- [x] NegateScalar
- [x] ReciprocalEstimate
- [x] ReciprocalEstimateScalar
- [x] ReciprocalExponentScalar
- [x] ReciprocalSquareRootEstimate
- [x] ReciprocalSquareRootEstimateScalar
- [x] ReciprocalSquareRootStep
- [x] ReciprocalSquareRootStepScalar
- [x] ReciprocalStep
- [x] ReciprocalStepScalar
- [x] ReverseElementBits
- [x] RoundAwayFromZero
- [x] RoundToNearest
- [x] RoundToNegativeInfinity
- [x] RoundToPositiveInfinity
- [x] RoundToZero
- [x] ShiftArithmeticRoundedSaturateScalar
- [x] ShiftArithmeticSaturateScalar
- [x] ShiftLeftLogicalSaturateScalar
- [x] ShiftLeftLogicalSaturateUnsignedScalar
- [x] ShiftLogicalRoundedSaturateScalar
- [x] ShiftLogicalSaturateScalar
- [x] ShiftRightArithmeticNarrowingSaturateScalar
- [x] ShiftRightArithmeticNarrowingSaturateUnsignedScalar
- [x] ShiftRightArithmeticRoundedNarrowingSaturateScalar
- [x] ShiftRightArithmeticRoundedNarrowingSaturateUnsignedScalar
- [x] ShiftRightLogicalNarrowingSaturateScalar
- [x] ShiftRightLogicalRoundedNarrowingSaturateScalar
- [x] Sqrt
- [x] StorePair
- [x] StorePairNonTemporal
- [x] StorePairScalar
- [x] StorePairScalarNonTemporal
- [x] Subtract
- [x] SubtractSaturateScalar
- [x] TransposeEven
- [x] TransposeOdd
- [x] UnzipEven
- [x] UnzipOdd
- [x] VectorTableLookup
- [x] VectorTableLookupExtension
- [x] ZipHigh
- [x] ZipLow

**Comment by EgorBo** [comment]
that is a lot of work 🙂

**Comment by kunalspathak** [comment]
In case it is helpful, I have created a reference document of ARM64 intrinsic APIs with examples and code generated.

https://kunalspathak.github.io/tags/#intrinsics

**Comment by imhameed** [comment]
This was implemented in https://github.com/dotnet/runtime/pull/49260.
