### ISSUE TITLE
Difference between IncludeSymbolsInSingleFile and DebugType embedded?

### ISSUE THREAD

**Issue by holc-tkomp** [dotnet/runtime#42278]
What's the difference between adding
```xml
<IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
```
and
```xml
<DebugType>embedded</DebugType>
```
to your .csproj?

This is pretty straightforward question, but I really couldn't find anything more than "IncludeSymbolsInSingleFile" is only available for .NET Core 3.0+ in [design.md](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#optional-settings) (which is kind of obvious, as you have to be able to build single-file).

So, is there any difference? Especially in how they get embedded?

**Comment by agocke** [comment]
In 3.0, symbols could be included by embedding the PDBs in the bundle, and at runtime they would be extracted to a temporary directory next to the app DLLs. In 5.0, we removed support for bundling and extracting the PDBs and recommend using embedded PDBs instead, where the PDB information is directly embedded inside each assembly (there are no separate PDB files). In general, embedded PDBs are better. It's a long supported feature and is usually understandable by most debuggers.

**Comment by holc-tkomp** [comment]
Thanks for your reply, I managed to think of some additional questions in the meantime:

1. How does `IncludeSymbolsInSingleFile` work in .NET 5 then?
2. How can one extract/inspect the "non-extracting" .NET 5 bundle?
3. Could you point me into some sources that could help me better understand what sits inside such .NET 5 bundle and how to potentially read it?
4. Can .NET 5 potentially generate self-extracting bundle? How to achieve this?

**Comment by agocke** [comment]
> How does IncludeSymbolsInSingleFile work in .NET 5 then?

It doesn't. It's not supported.

> How can one extract/inspect the "non-extracting" .NET 5 bundle?

It's currently not supported to examine the bundle, it's basically an opaque exe.

> Can .NET 5 potentially generate self-extracting bundle? How to achieve this?

Setting the property `IncludeContentForSelfExtract` to true will go back to the .NET Core 3.1 behavior instead of using the new bundling.

**Comment by holc-tkomp** [comment]
> > How does IncludeSymbolsInSingleFile work in .NET 5 then?
> 
> It doesn't. It's not supported.

Ah, just updated to RC1, it was still supported in Preview 8, with results below, and thus the question.

<details><summary>Results in Preview 8</summary>

Using simple WPF app, referencing `Microsoft.Data.SqlClient`, using single-file, framework-dependent, win-x86 publish, without `IncludeSymbolsInSingleFile` (or set to false), I was getting the following files as a publish output:

![no include](https://user-images.githubusercontent.com/54799591/93395637-889c5e80-f876-11ea-9136-784d16205111.png)

After setting `IncludeSymbolsInSingleFile` to true, I was getting the following:

![IncludeSymbolsInSingleFile](https://user-images.githubusercontent.com/54799591/93396100-63f4b680-f877-11ea-866b-9ed1b83345a7.png)

</details>

> > How can one extract/inspect the "non-extracting" .NET 5 bundle?
>
> It's currently not supported to examine the bundle, it's basically an opaque exe.

😢

> > Can .NET 5 potentially generate self-extracting bundle? How to achieve this?
> 
> Setting the property `IncludeContentForSelfExtract` to true will go back to the .NET Core 3.1 behavior instead of using the new bundling.

That either works different than expected, or doesn't work at all. I expected it to extract itself in `%temp%\.net\`, but I was not able to found _extracted_ executable anywhere (used [Everything](https://www.voidtools.com/) to search for WpfApp1.exe - nothing that could be considered extraction folder). Should I create issue for this?

**Comment by agocke** [comment]
Sorry, I think I typo'd that: should be `IncludeAllContentForSelfExtract`. Can you try that instead?

**Comment by holc-tkomp** [comment]
With `IncludeAllContentForSelfExtract` folder in `%temp%\.net\` is generated, although it only seems to contain native dependencies - in this case, just one file: `Microsoft.Data.SqlClient.SNI.dll`. No `WpfApp1.dll`, `.deps.json`, `.runtimeconfig.json` like in raw .NET Core 3.1.

**Comment by agocke** [comment]
@holc-tkomp You're right! That looks like a bug to me.

**Comment by agocke** [comment]
Filed https://github.com/dotnet/runtime/issues/42352 for this issue

**Comment by vitek-karas** [comment]
Sorry for the late response...

In 5.0.0 the `IncludeAllContentForSelfExtract` should behave basically identical to 3.1 bundles - all files should be extracted to disk and executed from the disk.

As for the bundle format:

[Design doc](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/bundler.md)

[Implementation of the bundling](https://github.com/dotnet/runtime/tree/master/src/installer/managed/Microsoft.NET.HostModel/Bundle)

Writing a tool to extract all of the content from the bundle should be pretty simple (the format is rather primitive).
