### ISSUE TITLE
ARM64 Runtime Packs and shared FX missing UCRT binaries

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#42287]
### Description

Redist UCRT dll's are missing from runtime packs and msi's for arm64 (ever since we started producing it). Are these needed?

**Comment by jkotas** [comment]
The OS provided OS UCRT is always available on Windows ARM64. We should not need it ship our local copy on Windows ARM64.

We include UCRT binaries for the old Windows versions that may be missing them.
