### ISSUE TITLE
PAL test file_io/GetFullPathNameA/test3/paltest_getfullpathnamea_test3 does not pass

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#42289]
### Description

Run the pal test file_io/GetFullPathNameA/test3/paltest_getfullpathnamea_test3

Note that the following error is produced

`ERROR :2: CreateFileA failed to create "/root/helix/work/workitem/testoutputtmp/test_directory../testing.tmp".`

I believe this test has been failing forever; however, the test did not properly report failure, so the test never failed in CI before.

**Comment by mangod9** [comment]
@janvorli, is this still something which needs fixing?

**Comment by janvorli** [comment]
It is a simple stupid bug in the test - missing path separator character. I will fix it.
