### ISSUE TITLE
[ARM64] ReliabilityFramework time-consumed

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#42290]
Hi,

Follow the [doc](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/coreclr/gc-stress-run-readme.md) to run ReliabilityFramework test:

```
export CORE_ROOT=/home/zhaixiang/coreclr-mips64-dev/bin/tests/Linux.arm64.Debug/Tests/Core_Root
export CORE_LIBRARIES=/home/zhaixiang/dotnet-sdk-3.1.107-linux-arm64/shared/Microsoft.NETCore.App/3.1.7
./bin/Product/Linux.arm64.Debug/corerun ./bin/tests/Linux.arm64.Debug/GC/Stress/Framework/ReliabilityFramework/ReliabilityFramework.exe ./tests/src/GC/Stress/testmix_gc.config
```

But not finished yet after 40 hours...

Please give me some hint.

\cc @jkotas @cshung @janvorli 

Thanks,
Leslie Zhai

**Comment by mangod9** [comment]
@xiangzhai is this on a vanilla arm64 build from master or some other configuration?

**Comment by xiangzhai** [comment]
Hi @mangod9 

coreclr-v3.1.7 Debug for ARM64.

I haven't tested runtime master due to online packages NuGet timeout issue...

Thanks,
Leslie Zhai

**Comment by cshung** [comment]
This particular test is the stress test for the garbage collector. It is not meant to be completed. As long as the test does not crash for long hours, we are good. See [here](https://github.com/cshung/runtime/blob/master/docs/workflow/testing/coreclr/gc-stress-run-readme.md) for more information about this test.

Congrats for having the test survived for 400 hours.

**Comment by mangod9** [comment]
Thanks @cshung. Closing based on that info.

**Comment by xiangzhai** [comment]
> Congrats for having the test survived for 400 hours.

76 hours continuously running for MIPS64 :)

Thanks,
Leslie Zhai
