### ISSUE TITLE
Android requirements?

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#4229]
Once we have a Linux version fully up and running, what will be necessary to get an Android version?  Some sort of roadmap for this should be added to docs.

Thoughts:
- We'll need Linux CoreCLR working for both x86 and ARM32.
- We'll need at least one Activity that starts the CoreCLR app as a NDK call
- How will interop with Android's Java system classes work?
- How will building, deployment and debugging work?
- Yes, before anyone says it, Xamarin is a thing.  Its licensing makes it an extremely onerous thing, however, and it's essentially impossible to create a third-party, open-source development tool to produce Android apps with Xamarin.  It would be nice to rectify that.

**Comment by janvorli** [comment]
Closing this issue as it is stale. Android is supported by our Mono part.
