### ISSUE TITLE
Break on exceptions behaves inconsistently on Blazor WASM apps

### ISSUE THREAD

**Issue by captainsafia** [dotnet/runtime#42326]
Break on exceptions behaves unreliably in a Blazor WASM application. I was able to get it working by doing a combination of setting breakpoints before the exception is thrown and pausing on caught exceptions. Of course, I wasn't able to reproduce the exact state I was in when I managed to get it working when drafting the repro notes here.

### Configuration

**Operating System and Browser**
Google Chrome 85.0.4183.102
macOS 10.15.16
Note: Similar behavior was reproduced on Windows and Chromium Edge.

**.NET SDK (reflecting any global.json):**
 Version:   5.0.100-rc.2.20459.6
 Commit:    4e6d364bbb

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-rc.2.20459.6/

Host (useful for support):
  Version: 5.0.0-rc.2.20458.14
  Commit:  482494f9ec

### Reproduction Steps

1. Create a new Blazor WASM project using `dotnet new blazorwasm -o Testing`.
2. Open `Pages/Counter.razor` and add `throw new Exception("foo")` inside the `IncrementCount` method.
3. Run `dotnet run` and navigate to the Blazor app. Press Alt+Shift+D to open the debugging experience. You'll be directed to relaunch a Chrome session with remote debugging enabled.
4. Enable "Pause on Exceptions" in the debugger.
5. Navigate to the counter page and click the increment button.
6. Observe that the JS exception is thrown in the UI (by Blazor) but not paused on.
![Screen Shot 2020-09-16 at 9 48 23 AM](https://user-images.githubusercontent.com/1857993/93367785-d5921d80-f801-11ea-99a5-7a865e8427b2.png)

8. Enable "Pause on caught exceptions".
9. Refresh the counter page and click the button again.
10. Observe that the debugger pauses on every exception but the one thrown.

**Comment by danroth27** [comment]
@lewing

**Comment by lewing** [comment]
It looks like we're not doing sufficient tracking of the state here.  If you change the state of "Pause on exceptions" after navigating to the counter page does it work as expected?

**Comment by captainsafia** [comment]
>  If you change the state of "Pause on exceptions" after navigating to the counter page does it work as expected?

Yep. Loading the app, then navigating to the counter page, then Enable exceptions (and set pause on caught exceptions), then hitting the button works as expected.

**Comment by lewing** [comment]
Ok good. I think we can fix this by tracking the state in the proxy by session, then forcing the runtime to match on load or exception.

**Comment by thaystg** [comment]
Working on it...

**Comment by lewing** [comment]
Just to update the status here, we've dug into the issue and it seems that the state of this setting is preserved and communicated to the ui outside of the Debugger protocol and we don't currently have a path to retrieve it so we're it isn't clear how this can be properly fixed.  We track the state better once it has changed so we'll start there.

**Comment by thaystg** [comment]
@lewing suggestion: "inject a caught exception and see if we get a pause", I agree that this is possible. Let's try.

**Comment by lewing** [comment]
@thaystg reopen if this isn't actually fixed.
