### ISSUE TITLE
Blazor WASM not respecting DateTime format on all cultures (.NET 5.0)

### ISSUE THREAD

**Issue by ar0311** [dotnet/runtime#42328]
### Describe the bug
When using DateTime in a .razor page in Blazor (WASM only, SSB seems OK) the Date is formatted correctly when using some cultures but not with others.

Observed this behaviour to start when moving from Blazor 3.2 to the 5.0 previews/RC's.

### To Reproduce
Install 5.0 RC1 SDK
Create standard blazorwasm project (dotnet new blazorwasm).
Run it.
Load it into a browser using en-US culture. (United States)
Observe correct Date format on FetchData page. (mm/DD/YYYY)
Load it into a browser using en-GB culture. (United Kingdom)
Observe correct Date format on FetchData page. (dd/MM/YYYY)
Load it into a browser using en-AU culture. (Australia)
Observe incorrect Date format on FetchData page. (mm/DD/YYYY) which should be (dd/MM/YYYY)

### Exceptions (if any)
None

### Further technical details
- ASP.NET Core 5.0 RC1
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-rc.1.20452.10/

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.402 [/usr/local/share/dotnet/sdk]
  5.0.100-rc.1.20452.10 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
@EgorBo FYI

**Comment by EgorBo** [comment]
I guess we should allow all `en-*` locales in the common icudt.dat 🙁 
let me check size impact

**Comment by ar0311** [comment]
Is it planned to customise included locales during build?

**Comment by marek-safar** [comment]
@EgorBo any update on this one?

**Comment by EgorBo** [comment]
@marek-safar the fix is ready, just stuck on dotnet/icu now, working on it.

> Is it planned to customise included locales during build?

we have a set of prebuilt files with locales, the biggest one should cover most locales.
but it's also possible to build a custom one by hand but I am not sure blazor will support it

**Comment by safern** [comment]
@EgorBo we can close this right? I believe it was fixed by: https://github.com/dotnet/runtime/pull/42525

**Comment by EgorBo** [comment]
@safern no, I was asked to split my dotnet/icu patches into separate PRs for dontet/runtime so the proper fix will come in an hour once nuget is built

**Comment by EgorBo** [comment]
Closed via https://github.com/dotnet/runtime/pull/42579

**Comment by ar0311** [comment]
This doesn't seem to have made it into latest RC2.

Installed SDK 5.0.100-rc.2.20480.7
dotnet new blazorwasm

Culture en-AU (dd-MM-yyyy) but being displayed (mm-DD-yyyy) again.
