### ISSUE TITLE
[mono] Tracking: Implement `System.Runtime.Intrinsics.Arm.Rdm`

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#42322]
### System.Runtime.Intrinsics.Arm.Rdm:

- [x] IsSupported
- [x] MultiplyRoundedDoublingAndAddSaturateHigh
- [x] MultiplyRoundedDoublingAndSubtractSaturateHigh
- [x] MultiplyRoundedDoublingBySelectedScalarAndAddSaturateHigh
- [x] MultiplyRoundedDoublingBySelectedScalarAndSubtractSaturateHigh

### System.Runtime.Intrinsics.Arm.Rdm.Arm64:

- [x] IsSupported
- [x] MultiplyRoundedDoublingAndAddSaturateHighScalar
- [x] MultiplyRoundedDoublingAndSubtractSaturateHighScalar
- [x] MultiplyRoundedDoublingScalarBySelectedScalarAndAddSaturateHigh
- [x] MultiplyRoundedDoublingScalarBySelectedScalarAndSubtractSaturateHigh

**Comment by mihir-b-shah** [comment]
Hi I was interested in working on this issue, I was wondering are there any tests available for this or should I be writing my own corresponding tests? Thank you!

**Comment by imhameed** [comment]
Hi @mihir-b-shah,

Awesome. There are tests available but they are currently disabled. The existing tests are located here:
- https://github.com/dotnet/runtime/tree/64da821c7b3e60f9aeaf2c3d544d33d19e2fc82e/src/tests/JIT/HardwareIntrinsics/Arm/Rdm.Arm64
- https://github.com/dotnet/runtime/tree/64da821c7b3e60f9aeaf2c3d544d33d19e2fc82e/src/tests/JIT/HardwareIntrinsics/Arm/Rdm

Other intrinsics-on-Mono work is being done right now, and by looking at some of these commits you should be able to get a feel for what you'll need to do. Here's an example:
- https://github.com/dotnet/runtime/pull/47337

**Comment by SamMonoRT** [comment]
Need https://github.com/dotnet/runtime/issues/48475 to implement a subset of these

**Comment by imhameed** [comment]
Implemented in https://github.com/dotnet/runtime/pull/49737.
