### ISSUE TITLE
Hosting policy on casing resolution is different between Linux-Mac

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#42334]
### Description

Changing the casing on an App assembly has different behavior in Linux & Mac in that deleting the <App>.deps.json file and changing the case of the App assembly (ex. App.dll to app.dll) causes the app to fail in Linux and to pass in Mac (ex. run App.exe)

Given the underlying OS behavior for case comparison is similar in both, investigate this difference further and adjust the below test cases accordingly.

The following 3 tests in src\installer\tests\HostActivation.Tests\DependencyResolution\ResolveComponentDependencies.cs tracks the scenarios for all platforms. Do note that these tests are currently disable in non-windows platforms until this issues is investigated
 - ComponentWithNoDependenciesCaseChangedOnAsm
 - ComponentWithNoDependenciesCaseChangedOnDepsAndAsm
 - ComponentWithNoDependenciesNoDepsCaseChangedOnAsm

### Configuration

* Which version of .NET is the code running on? .NET 6.0
* What OS and version, and what distro if applicable? Any Linux and Mac
* What is the architecture (x64, x86, ARM, ARM64)? x64

### Regression?
No

**Comment by jkotas** [comment]
> Given the underlying OS behavior for case comparison is similar in both

macOS has case-insensitive file system by default. https://www.bing.com/search?q=macOS%20case%20insensitive%20file%20system
