### ISSUE TITLE
HttpClient.GetStreamAsync logs ResponseContentStart/Stop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#42330]
The method doesn't buffer or attempt to read any response content, just as SendAsync doesn't with RequestHeadersRead.  So it shouldn't be logging response content start/stop.

**Comment by MihaZupan** [comment]
@karelz, @ManickaP and I actually discussed this case.

We call `ReadAsStreamAsync` on the content. While the built-in HttpContent types will not buffer, a custom one could choose to do so / do some other longer processing. That is why we decided it's worth logging the Start/Stop around it as well.

**Comment by ManickaP** [comment]
AFAIR, I was the one adding it, probably just because I've added it to all other helper methods. @MihaZupan pointed out that they do not make sense here, I concurred, but we still kept them.

One of the reasons was that when we considered removing it, suggestions for other events (marking start of content reading) started springing. So we decided to rather keep the existing ones, albeit seemingly redundant.

**Comment by stephentoub** [comment]
> We call ReadAsStreamAsync on the content.

From an HTTP perspective, that's not reading the content: no read is performed on the wire for it, etc.  All that's doing is getting a stream that lets you read the content.

The event here makes little sense to me.

**Comment by stephentoub** [comment]
> While the built-in HttpContent types will not buffer, a custom one could choose to do so / do some other longer processing.

If a custom content type chose to buffer, then it could be doing so before we even emit the started log event.

**Comment by stephentoub** [comment]
> So we decided to rather keep the existing ones, albeit seemingly redundant.

The problem is, they're not redundant.  They're incorrect.  We log to say that we've started reading the content and then we've finished reading all the content... but we've not read any of it, and in fact the whole point of the API is to give back a Stream that lets the caller do the reading of the content.
