### ISSUE TITLE
System.Text.Json.JsonSerializer throws NotSupportedException when serializing BitmapImage 

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#42369]
### Description

System.Text.Json.JsonSerializer throws a notsupportexception when trying to serialize a class which contains a Bitmapimage property. `NotSupportedException: "BitmapMetadata" is not available for "BitmapImage".`

### Configuration

Targeting .NET Core 3.1
WPF Application
Windows 10
```
Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
```

##### Code
```
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        System.Text.Json.JsonSerializer.Serialize(new Bla());
    }
}

class Bla
{
    public BitmapImage Cover { get; set; } = new BitmapImage();
}
```

**Comment by layomia** [comment]
Not a regression in .NET 5.0.

> System.Text.Json.JsonSerializer.Serialize(new Bla());

Output in Newtonsoft.Json: `{"Cover":"System.Windows.Media.Imaging.BitmapImage"}`

Can you share what the motivation for serializing the `BitmapImage` type is?

**Comment by Symbai** [comment]
I'm fetching images from the web, keep them in memory only and display them in WPF through an Image control. Then I would like to save my ObservableCollection of this class to disk and load them on next start. Instead of fetching the images again they should be stored in the file containing the serialization. And instead of saving the images to disk as well and store the path ending up with lots of files instead of one (loading several small images from disk is much slower reading one large file from disk).

**Comment by Symbai** [comment]
I was trying to use a jsonconverter but it still throws on serialization  `The unsupported member type is located on type 'System.Windows.Media.ImageMetadata'. Path: $.Cover.Metadata.'`

![image](https://user-images.githubusercontent.com/14368203/110650132-8f1ee980-81ba-11eb-9c48-c1a08d000bf4.png)

```C#
sealed class CustomBitmapConverter : JsonConverter<BitmapImage>
{
    public override BitmapImage Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string image = reader.GetString();

        byte[] byteBuffer = Convert.FromBase64String(image);
        using var stream = new MemoryStream(byteBuffer) { Position = 0 };
        var bitmap = new BitmapImage();
        bitmap.BeginInit();
        bitmap.StreamSource = stream;
        bitmap.CacheOption = BitmapCacheOption.OnLoad;
        bitmap.EndInit();
        bitmap.Freeze();
        return bitmap;
    }
    public override void Write(Utf8JsonWriter writer, BitmapImage value, JsonSerializerOptions options)
    {
        byte[] data;
        JpegBitmapEncoder encoder = new JpegBitmapEncoder();
        encoder.Frames.Add(BitmapFrame.Create(value));
        using (MemoryStream ms = new MemoryStream())
        {
            encoder.Save(ms);
            data = ms.ToArray();
        }
        writer.WriteBase64StringValue(data);
    }

}
```

Does this mean we cannot even use a JsonConverter as fallback (because this is what works on Newtonsoft.Json) or is there a problem with my implementation?!

**Comment by eiriktsarpalis** [comment]
Would it be possible to share a minimal reproduction? The error message seems to suggest an issue with `ImageMetadata`, rather than `BitmapImage` serialization.

**Comment by Symbai** [comment]
You were right, it was caused by a "faulty" image but only on serialization it throw the exception. When I copy the code above into a new WPF project and test it on a "valid" image it works perfectly fine.

Therefore the original problem is solved and I suggest to everyone else having the same problem to use a custom converter.
