### ISSUE TITLE
How to fix the length of TcpClient NetworkStream.ReceiveAsync() with Memory<T>？

### ISSUE THREAD

**Issue by yukozh** [dotnet/runtime#42379]
How to fix the length of TcpClient NetworkStream.ReceiveAsync() with Memory<T>？

I'm using the MemoryPool<byte>.Shared.Rent(8) to created a Memory<byte>, I just wanna receive 8 bytes from the stream. But When I using NetworkStream.ReceiveAsync with Memory<byte>, it received more than 8 bytes.

Is there any way to receive a fixed length with Memory<byte> ?

**Comment by stephentoub** [comment]
The `Memory<byte>` you get back may be longer than what you requested. `Slice` it when passing it to ReceiveAsync.
