### ISSUE TITLE
Calling GetFullPathName() with a path string without terminating '\0'

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#42373]
### Description

System.IO.Path API

Compare:
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/IO/PathHelper.Windows.cs#L26-L31

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/IO/PathHelper.Windows.cs#L50-L55

In second case we explicitly add '\0' but in first case we pass a path without adding '\0'. Looks like a bug.

### Configuration

.Net 5.0 RC mater branch

**Comment by stephentoub** [comment]
strings are already null terminated. There's no need to add an additional terminator when just getting a span for the full string.

**Comment by iSazonov** [comment]
@stephentoub Is it a bug in documentation?
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#:~:text=There%20is%20no%20null%2Dterminating,the%20number%20of%20Unicode%20characters.

>  There is no null-terminating character at the end of a C# string; therefore a C# string can contain any number of embedded null characters ('\0').

**Comment by stephentoub** [comment]
The docs mean that the null terminator isn't how the length of the string is determined, and therefore it can contain nulls. It's an implementation detail of the platform, primarily for interior purposes, that the runtime puts a null terminator at the end.
