### ISSUE TITLE
Task.WhenAll(IEnumerable<Task>) large allocations

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#42376]
## Description

My use case is the following: for each keys of a sql table, I would like to create a `Task` and get notified when they all get completed. With `Task.WhenAll` I can do that
```csharp
IEnumerable<int> data = GetKeys();  // database fetch resulting in thousands of rows
IEnumerable<Task> tasks = data.Select(k => GetAndSetValueForKeyAsync(k)); // create a task by row
Task t = Task.WhenAll(tasks);
```

The issue with that code is that `Task.WhenAll` will collect the `IEnumerable` into a `List` then call `List.ToArray` which are two large allocations.
https://github.com/dotnet/runtime/blob/33dba9518b4eb7fbc487fadc9718c408f95a826c/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5495-L5503

## Benchmark
By benchmarking the difference of allocations between `Task.WhenAny(Task[])` and `Task.WhenAny(IEnumerable<Task>)` with this code
```csharp
[MemoryDiagnoser]
public class TaskWhenAllAllocations
{
    private static readonly IEnumerable<Task> TasksEnumerable = Enumerable.Range(0, 10_000).Select(i => Task.CompletedTask);
    private static readonly Task[] TasksArray = Enumerable.Range(0, 10_000).Select(i => Task.CompletedTask).ToArray();

    [Benchmark]
    public Task WithIEnumerable() => Task.WhenAny(TasksEnumerable);
    [Benchmark]
    public Task WithArray() => Task.WhenAny(TasksArray);
}
```
we get
|          Method |     Mean |   Error |  StdDev |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|---------------- |---------:|--------:|--------:|--------:|--------:|--------:|----------:|
| WithIEnumerable | 200.5 us | 2.82 us | 2.64 us | 41.5039 | 41.5039 | 41.5039 | 256.44 KB |
|       WithArray | 104.8 us | 1.97 us | 1.75 us | 18.7988 |       - |       - |  78.24 KB |

## Solution

`Task.WhenAny` makes a defensive copy but I don't think this is needed. The `IEnumerable` could be iterated only once to add the continuation that would just decrement the counter and complete the task if it's 0.

See PR #42377 

### Caveats

- `SetNotificationForWaitCompletion` was removed (not sure what it is)
- Exceptions thrown in constructor
- Canceled task used is now the first one to complete not the first one  in the array
- More complex logic (i.e. m_count can be negative)

**Comment by stephentoub** [comment]
> Task.WhenAny makes a defensive copy but I don't think this is needed

It's there to avoid leaking continuations registered before detecting invalid input.

**Comment by stephentoub** [comment]
> SetNotificationForWaitCompletion was removed (not sure what it is)

It's required to enable debugger step-out.

**Comment by verdie-g** [comment]
> It's required to enable debugger step-out.

Critical then. I don't see where `SetNotificationForWaitCompletion` could fit in the change I am proposing 😕

**Comment by Clockwork-Muse** [comment]
Side question: what is `GetAndSetValueForKeyAsync(...)` doing?  If you're going right back to the same database, would it be better to just do this as a normal update statement?  (Possibly as part of a data change table...)

**Comment by verdie-g** [comment]
The exact use-case is getting all keys of table and getting the values from memcached.

**Comment by verdie-g** [comment]
Closing since https://github.com/dotnet/runtime/pull/42377 was closed.
