### ISSUE TITLE
`ServiceDescriptor` for generic types does not work.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#42387]
I am registering all of my services to `ServiceCollection` using reflection and that's why I am using `ServiceDescriptor`. Although it is working fine for Concrete type but not working for Generic type.

For example:

Generic Service Type:

    public interface IRepository<T> 
        where T: class
    {
        string Welcome(string name);
    }

Generic Implementaion Type:

    public class EfCoreRepository<T> : IRepository<T>
        where T : class
    {
        public string Welcome(string name)
        {
            return $"Welcome! {name}";
        }
    }

Adding to `ServiceCollection` as follows:

    Type serviceType = Getting Type of IRepository<T> using reflection.
    Type implementationType = Getting Type of  EfCoreRepository<T> using reflection.
    serviceCollection.Add(new ServiceDescriptor(serviceType, implementationType , ServiceLifetime.Scoped));

Throwing the following exception:

> ArgumentException: Cannot instantiate implementation type 'Demo.Implementations.EfCoreRepository`1[T]' for service type 'Demo.GenericServices.IRepository`1[T]'.

If I remove the generics it works fine.

Please help me in this regard. Thank you.

**Comment by davidfowl** [comment]
What types did you pass to `ServiceDescriptor`? Specifically, the real code for this:

```C#
Type serviceType = Getting Type of IRepository<T> using reflection.
Type implementationType = Getting Type of  EfCoreRepository<T> using reflection.
serviceCollection.Add(new ServiceDescriptor(serviceType, implementationType , ServiceLifetime.Scoped));
```

You need to either pass a closed generic or an open generic type

**Comment by TanvirArjel** [comment]
@davidfowl 
> What types did you pass to ServiceDescriptor?

The service type is `typeof(IRepository<T>)` and the implementation type is  `typeof(EfCoreRepository<T>)` which is getting using reflection at runtime.

Please look at the error message:
>ArgumentException: Cannot instantiate implementation type 'Demo.Implementations.EfCoreRepository1[T]' for service type 'Demo.GenericServices.IRepository1[T]'.

**Comment by davidfowl** [comment]
What is the T? Can you show *all* of the code? It is it in a generic class, or a generic method?

**Comment by TanvirArjel** [comment]
@davidfowl Please read the original question thoroughly. I have explained everything clearly with real examples where it is also said that what is T.

**Comment by davidfowl** [comment]
> @davidfowl Please read the original question thoroughly. I have explained everything clearly with real examples where it is also said that what is T. By the way, 'T' is the generic type with class constraint.

Sorta, you're missing some code. I'd like something runnable. 


If that isn't possible I can guess what you want:

```C#
serviceCollection.Add(new ServiceDescriptor(typeof(IRepository<>), typeof(EfCoreRepository<>) , ServiceLifetime.Scoped));
```

**Comment by TanvirArjel** [comment]
@davidfowl Okay. Here is my repository: https://github.com/TanvirArjel/AspNetCore.ServiceRegistration.Dynamic/blob/master/src/AspNetCore.ServiceRegistration.Dynamic/ServiceCollectionExtensions.cs#L140

**Comment by rameel** [comment]
The `GetInterfaces()` method for a type with `IsGenericTypeDefinition == true` returns the list of types with `IsGenericTypeDefinition == false`, so the `typeof(IType<T>) != typeof(Type<T>).GetInterfaces()[0]`

Accordingly, you need to normalize the interface type by calling the `serviceType.GetGenericTypeDefinition()` here https://github.com/TanvirArjel/AspNetCore.ServiceRegistration.Dynamic/blob/master/src/AspNetCore.ServiceRegistration.Dynamic/ServiceCollectionExtensions.cs#L73 like this, for example
```cs
var isGenericTypeDefinition = implementation.IsGenericType && implementation.IsGenericTypeDefinition;
var service = isGenericTypeDefinition
    && serviceType.IsGenericType
    && serviceType.IsGenericTypeDefinition == false
    && serviceType.ContainsGenericParameters
        ? serviceType.GetGenericTypeDefinition()
        : serviceType;
serviceCollection.Add(new ServiceDescriptor(service, implementation, lifetime));
```

**Comment by TanvirArjel** [comment]
@rameel Thank you so much from the bottom of my heart for your contribution. My issue has been solved.
