### ISSUE TITLE
Add support for determining if debugger is attached from runtime

### ISSUE THREAD

**Issue by captainsafia** [dotnet/runtime#42411]
To ensure that we are not doing debugging -related work needlessly, we need a way to ensure that a debugger is attached to the user application.

This is particularly relevant in the context of #42255 and other features that should only be run when in debugging mode.

A simple solution for this is presented in https://github.com/dotnet/runtime/pull/42255#issuecomment-694406441.

**Comment by marek-safar** [comment]
There is already `Debugger.IsAttached` property available, can you use it for your needs?

**Comment by captainsafia** [comment]
This is for the Mono debugger which doesn't expose this property so we need to implement something different.

**Comment by marek-safar** [comment]
@captainsafia That property is available at C# level and C runtime layer. I'm probably missing more context, leaving that to @thaystg to decide.

**Comment by thaystg** [comment]
That property wasn't working on Wasm, now it will be fixed with #42532, then we will be able to check if debugger is attached using this function `mono_is_debugger_attached`.
