### ISSUE TITLE
[wasm][debugger] Stepping out of an async method doesn't return to the call site

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#42421]
Failing test (not added to the repo yet):

```
        [Fact]
        public async Task StepOutOfAsyncMethod()
        {
            var insp = new Inspector();
            //Collect events
            var scripts = SubscribeToScripts(insp);

            await Ready();
            await insp.Ready(async (cli, token) =>
            {
                ctx = new DebugTestContext(cli, insp, token, scripts);
                string source_file = "dotnet://debugger-test.dll/debugger-async-step.cs";

                await SetBreakpointInMethod("debugger-test.dll", "DebuggerTests.AsyncStepClass", "TestAsyncStepOut2", 2);
                await EvaluateAndCheck(
                    "window.setTimeout(function() { invoke_static_method_async('[debugger-test] DebuggerTests.AsyncStepClass:TestAsyncStepOut'); }, 1);",
                    "dotnet://debugger-test.dll/debugger-async-step.cs", 21, 12,
                    "MoveNext");

                await StepAndCheck(StepKind.Out, source_file, 15, 4, "TestAsyncStepOut");
            });
        }
```

Stepping out, should pause at line 16 in the code below.

```
        public static async Task TestAsyncStepOut()
15:        {
16:            await TestAsyncStepOut2("foobar");
        }

        public static async Task<int> TestAsyncStepOut2(string some)
        {
            var resp = await client.GetAsync("http://localhost:9400/debugger-driver.html");
            Console.WriteLine($"resp: {resp}"); /// BP at this line

            return 10;
        }
```

@thaystg this test is on top of your #42299

**Comment by thaystg** [comment]
One question, can we merge #42299 and then fix this or should we fix this on #42299?

**Comment by radical** [comment]
This can be done separately.

**Comment by thaystg** [comment]
@radical and @lewing the problem here is that we don't have a way to configure "step into external code"
![image](https://user-images.githubusercontent.com/4503299/94306466-62974e00-ff49-11ea-8b33-73b6dc3dd6a0.png)
as we have in Vs4Mac and VSWin, and our default is Step Into External Code, that is the reason why we are breaking on NotifyDebuggerOfWaitCompletionIfNecessary and not on TestAsyncStepOut as you expect.
If you enable Step Into External Code on VS4Mac and run the same program, the step out will stop in NotifyDebuggerOfWaitCompletionIfNecessary as in WASM Debugger.
What should we do? Change our default to not step into external code? Create the configuration and talk to VS guys and explain them how they can pass this information for us?

**Comment by lewing** [comment]
Are these settings communicated to the js debugger and how is that done?

cc @captainsafia

**Comment by lewing** [comment]
@thaystg how difficult is the change assuming we know the setting?

**Comment by thaystg** [comment]
I think it's easy, like 4 hours to implement, I'm planning to implement it on monday morning.

**Comment by lewing** [comment]
@thaystg I assume this is still an issue with the VS. settings?

**Comment by ilonatommy** [comment]
@thaystg, has anything changed since the last update? Are we able to fix it in 7.0?

**Comment by lewing** [comment]
Do we have a tracking issue for all the settings we would like to be able to read from vs?

**Comment by thaystg** [comment]
No, but as far as I remember we have issues that should be fixed having these three parameters.
```
Just My Code.
Auto evaluate properties.
Symbol server configuration.
```

**Comment by thaystg** [comment]
I'll move it to 8.0 as we didn't get the approval for the vscode-js-debug extension.
The PR on vscode-js-debug side: https://github.com/microsoft/vscode-js-debug/pull/1311

**Comment by lewing** [comment]
@thaystg can we get a status update here soon?

**Comment by thaystg** [comment]
Sure, I'll work on it on Monday :)
