### ISSUE TITLE
Can't execute Self-contained published Net5 app

### ISSUE THREAD

**Issue by sassy224** [dotnet/runtime#42433]
### Description
I built an application that targets net5-windows, it also references to other net5-windows dlls. I want to publish this application as self-contained app so people can download it and run anywhere.
When I double the exe file, nothing is shown. I checked event viewer log and saw the exception. 

> Application: FlexGridExplorer.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Threading.Dispatcher' threw an exception.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at System.Reflection.RuntimeModule.GetFullyQualifiedName()
   at System.Reflection.RuntimeModule.get_Name()
   at System.Windows.WpfDllVerifier.VerifyWpfDllSet(String[] additionalDlls)
   at System.Windows.Threading.Dispatcher..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
   at System.Windows.Threading.DispatcherObject..ctor()
   at System.Windows.Application..ctor()
   at FlexGridExplorer.App.Main()

>Faulting application name: FlexGridExplorer.exe, version: 5.0.20203.9, time stamp: 0x5f4ed831
Faulting module name: KERNELBASE.dll, version: 10.0.19041.388, time stamp: 0xa2224bb6
Exception code: 0xe0434352
Fault offset: 0x00129862
Faulting process id: 0x8624
Faulting application start time: 0x01d68d75347fce8a
Faulting application path: C:\Users\hansnguyen\Desktop\Builds\publish\FlexGridExplorer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2500fb64-4c78-468f-9a18-6d7447ad33ae
Faulting package full name: 
Faulting package-relative application ID: 

>Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0
Problem signature:
P1: FlexGridExplorer.exe
P2: 5.0.20203.9
P3: 5f4ed831
P4: KERNELBASE.dll
P5: 10.0.19041.388
P6: a2224bb6
P7: e0434352
P8: 00129862
P9: 
P10: 
Attached files:
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_FlexGridExplorer_6f7055a2aabd135d7f6b43fcb1a2778b9bfc7e3_f26e74a3_60e6b26b-f6a0-4bdd-8903-faff2367f879
Analysis symbol: 
Rechecking for solution: 0
Report Id: 2500fb64-4c78-468f-9a18-6d7447ad33ae
Report Status: 4
Hashed bucket: 
Cab Guid: 0

>Fault bucket 1255415866517101526, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0
Problem signature:
P1: FlexGridExplorer.exe
P2: 5.0.20203.9
P3: 5f4ed831
P4: KERNELBASE.dll
P5: 10.0.19041.388
P6: a2224bb6
P7: e0434352
P8: 00129862
P9: 
P10: 
Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6251.tmp.WERInternalMetadata.xml
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_FlexGridExplorer_6f7055a2aabd135d7f6b43fcb1a2778b9bfc7e3_f26e74a3_60e6b26b-f6a0-4bdd-8903-faff2367f879
Analysis symbol: 
Rechecking for solution: 0
Report Id: 2500fb64-4c78-468f-9a18-6d7447ad33ae
Report Status: 268435456
Hashed bucket: 056e2f91f02dad6f216c221441241bd6
Cab Guid: 0

### Configuration
SDK: 5.0.100-rc.1.20452.10
OS: Windows 10 version 2004 (build 19041.388) 64 bit

### Regression?
Not sure, this is my first time published Net5 app. Didn't try before with previous SDKs.

### Other information
I attach the published app and its settings
![publish settings](https://user-images.githubusercontent.com/1535748/93556086-001adc80-f9a2-11ea-8bb7-52c8d8ce8384.png)
Published app: https://1drv.ms/u/s!AksUrKpaFek1gbVztcuqJSYlMflrWw?e=0xga8M

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/runtime/issues/38636, should be fixed in RC2
