### ISSUE TITLE
Does the "state" parameter accept null values in NamedPipeServerStream.BeginWaitForConnection?

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#42434]
### Description

I'm enabling nullable reference types on an existing project. I'm also changing the target framework to .NET 5.0. The nullable annotation for `NamedPipeServerStream.BeginWaitForConnection` indicates that the `state` parameter doesn't accept null values. In my code this parameter is null and it seems to work (at least in previous versions of .NET).

By looking at the code, `BeginWaitForConnection` calls `TaskToApm.Begin` which accepts a nullable state parameter. So, is the nullable annotation ok for this method?

https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs#L179
````
public System.IAsyncResult BeginWaitForConnection(AsyncCallback callback, object state) =>
            TaskToApm.Begin(WaitForConnectionAsync(), callback, state);
````

https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Threading/Tasks/TaskToApm.cs#L33
````
public static IAsyncResult Begin(Task task, AsyncCallback? callback, object? state)
````

**Comment by stephentoub** [comment]
Both the callback and state should be nullable. That's the case for every BeginXx APM method.

**Comment by stephentoub** [comment]
Reopening for potential backport

**Comment by stephentoub** [comment]
Fixed in RC2
