### ISSUE TITLE
Missing exec rights for tizen arm64 rootfs creation scripts after arcade merge to runtime

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#42438]
For some reason `eng/common/cross/arm64/tizen-build-rootfs.sh` and `eng/common/cross/arm64/tizen-fetch.sh` do not have exec rights after arcade is merged to dotnet/runtime repo. Same scripts for armel have all required rights, and in arcade repo scripts also have all required rights.

dotnet/runtime (92b125fc7671b82433f3adbd085b7e6b29b1a73d):
```
$ ls eng/common/cross/armel/ -la
-rwxrwxr-x 1 z z  876 Sep  1 16:09 tizen-build-rootfs.sh
-rwxrwxr-x 1 z z 4259 Sep  1 16:09 tizen-fetch.sh

$ ls eng/common/cross/arm64/ -la
-rw-rw-r-- 1 z z  845 Sep  1 16:09 tizen-build-rootfs.sh
-rw-rw-r-- 1 z z 4261 Sep  1 16:09 tizen-fetch.sh

```

dotnet/arcade (b63ea25b8dc50bb3dfcef128d415254bd5ca4dc8):
```
$ ls eng/common/cross/arm64/ -la
-rwxrwxr-x 1 z z  845 Jul  9 14:47 tizen-build-rootfs.sh
-rwxrwxr-x 1 z z 4261 Aug 20 16:18 tizen-fetch.sh
```

cc @alpencolt

**Comment by ericstj** [comment]
I suspect that darc isn't applying modifiers when new files are added.  cc @jcagme @mmitche Seems the same as https://github.com/dotnet/arcade/issues/5346.

You should be able to simply make the change: `git update-index --chmod=+x`  I've done so and submitted a PR: https://github.com/dotnet/runtime/pull/42533

**Comment by mmitche** [comment]
@riarenas I wonder if this is hitting a case when new files are added. We do handle executable bits, but there must be another corner case.

**Comment by NikolaMilosavljevic** [comment]
Closing as this was fixed with linked PR.
