### ISSUE TITLE
System.Text.Encoding.CodePages Encoding 1252 does not support GetEncoding("cp1252") by name

### ISSUE THREAD

**Issue by KinNeko-De** [dotnet/runtime#42441]
I had to connect to a database that uses the encoding 1252. I used a library that gets the encoding by name.

Code to reproduce:
'Encoding encoding3 = Encoding.GetEncoding(1252);
Encoding encoding4 = Encoding.GetEncoding("cp1252");`
The last line throws an exception 'System.ArgumentException : 'cp1252' is not a supported encoding name.'

`Encoding encoding1 = Encoding.GetEncoding(1256);
Encoding encoding2 = Encoding.GetEncoding("cp1256");`
With encoding 1256 everything works fine.

I think the reason is that the following CSV only contains a mapping of 1256. "cp1256;1256"
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Encoding.CodePages/src/Data/CodePageNameMappings.csv
But I am not sure why it does not contains the code page 1252.

**Comment by krwq** [comment]
I believe you should be using `windows-1252`. Per https://www.iana.org/assignments/charset-reg/windows-1252

> This charset is also known as Windows Code Page 1252 or cp1252 for short; these are NOT aliases.

@tarekgh perhaps makes sense to still add it as this might be fairly popular code page to use?

**Comment by tarekgh** [comment]
The official name `windnows-1252` is right one to use. but usually there is aliasing for such codepages. In the link @krwq mentioned, it has http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT. Which suggest may be a good reason to support this name.

@KinNeko-De do you want submit a PR for this one?

**Comment by KinNeko-De** [comment]
Hello, only for context: I try to connect to a very old sql anywhere database. I can use "cp1256" as charset in the connection string but It does not work with "windows-1252". But there are other problems so i do not use the library.

I tried to create a pull request but i somehow fail.
I added the cp1252 to the csv and added test data in my fork: https://github.com/KinNeko-De/runtime

But i can not find the tool that generates EncodingTable.Data.cs. As far as i understand it, i should not calculate the indexes in my mind.
Maybe the tool is executed during build.cmd. But this fails because it search for Microsoft.Cpp.Default.props in another instance of visual studio. I have a professional edition for work too.

I am sorry for that.

**Comment by tarekgh** [comment]
@KinNeko-De thanks a lot for your try. The tool is not part of the build anymore so we need to restore it. please let me know if you are interested, I can guide you doing it. Otherwise I'll fix it myself.

**Comment by tarekgh** [comment]
@KinNeko-De I have submitted the attached PR. Thanks for bringing this issue to our attention.

**Comment by KinNeko-De** [comment]
Sry.. i was busy all day. I think you are faster when you do it alone :)
I have to thank you for your great work. The encoding package is very usefull for me when i write new code to old requirements.

**Comment by krwq** [comment]
@KinNeko-De as a side note you'll need to wait until 6.0 for this to be in the stable release since this has already missed 5.0 cut-off (we only take very few fixes in there impacting stability)

**Comment by KinNeko-De** [comment]
Thank you.
