### ISSUE TITLE
JsonSerializer don't respect PropertyNamingPolicy when serializing ExpandoObjects containing ExpandoObjects

### ISSUE THREAD

**Issue by petterlabraaten** [dotnet/runtime#42440]
I expect this test to pass, but it seems that PropertyNamingPolicy is ignored when serializing property names of ExpandoObjects contained within other ExpandoObjects:
```
public class TestClass
{
    public ExpandoObject OuterProperty { get; } = new ExpandoObject();

    public TestClass()
    {
        ((dynamic)OuterProperty).InnerProperty = new ExpandoObject();
    }
}

[Fact]
public void TestExpandoSerialization()
{
    var a = new TestClass();

    JsonSerializerOptions options = new JsonSerializerOptions()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DictionaryKeyPolicy = JsonNamingPolicy.CamelCase
    };

    var result = JsonSerializer.Serialize(a, options);

    string expected = "{\"outerProperty\":{\"innerProperty\":{}}}";
    Assert.Equal(expected, result);
}
```

```
Message: 
    Assert.Equal() Failure
                                 ↓ (pos 19)
    Expected: {"outerProperty":{"innerProperty":{}}}
    Actual:   {"outerProperty":{"InnerProperty":{}}}
                                 ↑ (pos 19)
```

If I change the type of InnerProperty , to an integer for instance, PropertyNamingPolicy is treated as expected:
```
public class TestClass
{
    public ExpandoObject OuterProperty { get; } = new ExpandoObject();

    public TestClass()
    {
        ((dynamic)OuterProperty).InnerProperty = 5;
    }
}

[Fact]
public void TestExpandoSerialization()
{
    var a = new TestClass();

    JsonSerializerOptions options = new JsonSerializerOptions()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DictionaryKeyPolicy = JsonNamingPolicy.CamelCase
    };

    var result = JsonSerializer.Serialize(a, options);

    string expected = "{\"outerProperty\":{\"innerProperty\":5}}";
    Assert.Equal(expected, result);
}
```

.Net Core version: 3.1.302

**Comment by layomia** [comment]
cc @steveharter - this was discussed in https://github.com/dotnet/runtime/pull/42097#discussion_r487995086.

Unless the policy is applied for both serialization and deserialization (like regular strongly-typed properties), data will not be able to roundtrip. FWIW, System.Text.Json has the same behavior as Newtonsoft.Json for this scenario - https://dotnetfiddle.net/CmoAM3.

Linking https://github.com/dotnet/runtime/issues/29690 as the uber-issue for ExpandoObject support.

**Comment by steveharter** [comment]
`ExpandoObject` is treated like a dictionary, since there is no custom converter specifically for it and and because it implements `IDictionary<string, object>`.

Using the `DictionaryKeyNamingPolicy` as above works as expected in 5.0. @layomia do you have the issue handy that fixed this? Thanks

**Comment by steveharter** [comment]
Looks like we both posted at same time... This issue should be closed
