### ISSUE TITLE
Regex.Replace(string, MatchEvaluator) reuses the Match object

### ISSUE THREAD

**Issue by slozier** [dotnet/runtime#42448]
### Description

`Regex.Replace(string, MatchEvaluator)` started reusing the `Match` object passed to the `MatchEvaluator` delegate with .NET 5.0. This caused some code which was saving the last `Match` for comparison to start failing. Here is a simple repro:

```C#
Match lastMatch = null;
new Regex("-").Replace("---", (match) => {
    Debug.Assert(match != lastMatch);
    lastMatch = match;
    return "";
});
```

I understand that reusing the `Match` object is likely an optimization, it was just an unexpected change in behavior. In my particular case, I was able to work around it by saving the properties of the `Match` object that were of interest (`Index` and `Length`).

### Configuration

.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

**Comment by stephentoub** [comment]
I opened #42452 to revert the caching/reuse for this API.

**Comment by stephentoub** [comment]
Fixed
