### ISSUE TITLE
Add SerializationInfo.TryGetValue API

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#42460]
## Background and Motivation

I'm implementing a deserializing constructor which may evolve over time or otherwise deserialize elements that *may* have been serialized. There is no way to retrieve a serialized member by name without throwing a `SerializationException` if the member had not been serialized [because `GetValue` calls `GetElement`](https://github.com/dotnet/runtime/blob/92b125fc7671b82433f3adbd085b7e6b29b1a73d/src/libraries/System.Private.CoreLib/src/System/Runtime/Serialization/SerializationInfo.cs#L368) and [`GetElement` throws](https://github.com/dotnet/runtime/blob/92b125fc7671b82433f3adbd085b7e6b29b1a73d/src/libraries/System.Private.CoreLib/src/System/Runtime/Serialization/SerializationInfo.cs#L330) if the named element could not be found.

Ironically the `Exception` class itself had this problem but cheats by [calling an internal `GetValueNoThrow` method](https://github.com/dotnet/runtime/blob/92b125fc7671b82433f3adbd085b7e6b29b1a73d/src/libraries/System.Private.CoreLib/src/System/Exception.cs#L45). Other classes should have the privilege of evolving over time and deserializing members *if* they are defined.

## Proposed API
```diff
namespace System.Runtime.Serialization
{
   public class SerializationInfo
   {
      public object? GetValue(string name, Type type)
+     public bool TryGetValue(string name, Type type, out object? value);
   }
}
```

## Usage Examples

``` C#
        protected RemoteRpcException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
            if (info.TryGetValue(nameof(this.ErrorCode), typeof(int?), out object? value))
            {
                this.ErrorCode = (JsonRpcErrorCode?)(int?)value;
            }
        }
```

## Alternative Designs

We could just make the existing `GetValueNoThrow` method public, but that doesn't fit the public API patterns already found in the .NET Framework.

## Risks

None identified.

**Comment by jkotas** [comment]
Related: https://github.com/dotnet/runtime/issues/24908

We are in the process of obsoleting binary formatter: https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md . It will be make the SerializationInfo type irrelevant.

**Comment by AArnott** [comment]
@jkotas: I used to assume `SerializationInfo` was only useful for the `BinaryFormatter` as well, but it is in fact much more adaptable than that. We now use it to serialize/deserialize exceptions over JSON-RPC with our own formatter.

I support the deprecation of the `BinaryFormatter`, but as there's a lot of precedent for serializable types using `SerializationInfo` and related types, and in fact that's the only way for many exceptions to serialize their data, please do not give up on `SerializationInfo`. :)

**Comment by jkotas** [comment]
The alternative plan for serializing exceptions is being discussed in https://github.com/dotnet/designs/issues/158

**Comment by dotMorten** [comment]
I just hit the need for a TryGetValue today as well. The class is indeed useful for more than just BinaryFormatter (DataContractSerializers are an example).
I'm forced to use try/catch to get a value, as there doesn't seem to be a way to check if a property is present

**Comment by GrabYourPitchforks** [comment]
The typical way to work around the lack of `SerializationInfo.TryGetValue` API is to enumerate the entries in the structure, switching on the ones you expect to be present. If you [search .NET Framework sources](https://referencesource.microsoft.com/mscorlib/R/4b294c30a03a336c.html) you'll find that this pattern is quite common. I admit it's not the cleanest workaround, but it is an established pattern.

You are correct in that the _ISerializable_ pattern is technically independent of BF. However, _ISerializable_ itself is also problematic for various reasons and we would prefer to minimize its status in the ecosystem going forward. I'm closing this issue since a viable workaround exists and there's little appetite for making changes to _SerializationInfo_ itself.
