### ISSUE TITLE
DangerousAcceptAnyServerCertificateValidator for RemoteCertificateValidationCallback

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#42482]
Today with `HttpClientHandler.ServerCertificateCustomValidationCallback` you can do this to accept self-signed certificates:

```csharp
var httpHandler = new HttpClientHandler();
// Return `true` to allow certificates that are untrusted/invalid
httpHandler.ServerCertificateCustomValidationCallback = 
    HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
```

This is good, but the predefined delegate is limited to `HttpClientHandler`. There are options specific to `SocketsHttpHandler` so devs sometimes must use it instead. When they use `SocketsHttpHandler` there isn't an equivalent for quickly accepting self-signed certificates. They must specify a delegate that returns true:

```csharp
var httpHandler = new SocketsHttpHandler();
httpHandler.SslOptions.RemoteCertificateValidationCallback =
    (object sender, X509Certificate? certificate, X509Chain? chain, SslPolicyErrors sslPolicyErrors) => true;
```

It would be nice if there was a helper delegate for `SocketsHttpHandler` like `DangerousAcceptAnyServerCertificateValidator`:

```csharp
var httpHandler = new SocketsHttpHandler();
httpHandler.SslOptions.RemoteCertificateValidationCallback =
    SocketsHttpHandler.DangerousAcceptAnyServerCertificateValidator;
```

The property could either go on `SocketsHttpHandler`, or `SslClientAuthenticationOptions` (which is where `RemoteCertificateValidationCallback` is defined)

**Comment by geoffkizer** [comment]
I'd vote for it to go on SslClientAuthenticationOptions, since it's not specific to SocketsHttpHandler.

**Comment by stephentoub** [comment]
We added the delegate not because it made things simpler but because at the time our Unix implementations needed to be able to know whether an "allow everything" callback was being used. That's no longer the case, so it's purely a usability thing. Personally, I don't think it's worthwhile, when I can just write:
```C#
httpHandler.SslOptions.RemoteCertificateValidationCallback = delegate { return true; };
```

**Comment by stephentoub** [comment]
Given https://github.com/dotnet/runtime/issues/42482#issuecomment-695205357 and there hasn't been any further discussion here in the year and a half since, I'm going to close this.  Thanks for the suggestion.
