### ISSUE TITLE
SemaphoreSlim: synchronous acquisition rationale

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#42498]
In `SemaphoreSlim`, if one of the `Wait` overloads gets called when there aren't any counts available, the caller will synchronously wait until either counts become available (as a result of `Release` getting called), cancellation occurs, or the operation times out. When the synchronous waiter wakes up, the following logic acquires the semaphore:

https://github.com/dotnet/runtime/blob/9c472545df220d7ae26329e1649f880c4ee127e8/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs#L388-L403

I don't see any issues with this logic. However, I don't follow the rationale for this logic as described in the comment. In particular, I don't see how asynchronous waiters have anything to do with this decision: If there were only synchronous waiters, you would still lose counts if a wait failed to acquire the semaphore (without doing anything else). The only way to fail without losing a count would be to effectively `Release` again. And assuming the synchronous wait count was decremented beforehand, `Release(1)` would handle any mix of synchronous and asynchronous waiters just fine (though you'd probably want to refactor `Release` to handle this scenario more elegantly). Again, I think the existing logic works well, particularly in the face of `Monitor`-related race conditions. I just don't get why asynchronous waiters are the reason it is needed.

**Comment by stephentoub** [comment]
This is purely about the order of these checks:
```C#
                    if (m_currentCount > 0)
                    {
                        waitSuccessful = true;
                        m_currentCount--;
                    }
                    else if (oce != null)
                    {
                        throw oce;
                    }
```
The release code path signals a sync waiter and assumes it will wake up. If there are then any async waiters, it doesn't release them. Which means the sync path needs to prioritize an available count over a cancellation request. There is a comment to this effect in Release as well.

**Comment by WizardBrony** [comment]
@stephentoub Yes, I agree with that. But say the async API didn't exist. Wouldn't the order of those checks still be necessary to prevent losing counts? I believe I could make the following edits to your comment and it would still be true:

"The release code path signals a ~~sync~~ waiter and assumes it will wake up. If there are then any ~~async~~ **other** waiters, it doesn't release them. Which means the ~~sync~~ **wait** path needs to prioritize an available count over a cancellation request."

**Comment by stephentoub** [comment]
> Wouldn't the order of those checks still be necessary to prevent losing counts?

No.

For sync, Release always increments the available count and leaves it up to the sync waiter to then decrement the count, and it signals waiters via the monitor that they're waiting on.  For async, Release actually completes the async waiter task and decrements the count (or, rather, doesn't increment the count accordingly), and it only does so after sync waiters have been signaled and only for the difference between ReleasedCount-NumberOfSyncWaiters.

**Comment by WizardBrony** [comment]
@stephentoub I follow what you're saying. I think my misunderstanding has to do with what it would mean to actually lose a count. Could you please explain that scenario?

**Comment by stephentoub** [comment]
> Could you please explain that scenario?

Let's say the code was in the opposite order, such that it first checked for cancellation. Now let's say there's a sync waiter and an async waiter, and a Release(1) call is made.  This will increment the count of the semaphore, and use a Monitor.Pulse to wake up the sync waiter once the Release exits the lock.  It won't complete any async waiters, because it's expecting that the sync waiter will successfully acquire the semaphore.  However, when the sync waiter wakes up, it finds that it's been canceled via the cancellation token, and because that check comes before the check for available count, it throws.  There's no available count in the semaphore, meaning if you were to check SemaphoreSlim.CurrentCount you'd see count available, and if another new waiter were to come along, it would successfully acquire the semaphore... but there's an async waiter that's stuck waiting.

**Comment by WizardBrony** [comment]
@stephentoub Okay, but now let's say you have a sync waiter and a second sync waiter. How would the same thing not happen?

**Comment by stephentoub** [comment]
> How would the same thing not happen?

The cancellation pulses all waiters, not just the one being canceled, and since the first waiter won't have decremented the count, when the second one wakes up, it'll find count available and consume it.

**Comment by WizardBrony** [comment]
@stephentoub Got it. But if instead the first waiter timed out, then the logic would still need to be `if (m_currentCount > 0)` instead of `if (waitSuccessful)` because otherwise you'd end up in the same scenario, correct?

**Comment by stephentoub** [comment]
If the waiter timed out in the Monitor.Wait call, then it won't have consumed the pulse.

**Comment by WizardBrony** [comment]
@stephentoub That was the missing piece. Thank you very much for your time.
