### ISSUE TITLE
[WebAssembly] Declaring a variable named `calledRun` that is initialized to true causes WebAssembly to not load.

### ISSUE THREAD

**Issue by UltimateForm** [dotnet/runtime#42504]
Minimal repo:

* Create a blazor wasm app
* Modify index.html like so:

```diff
+  <script>
+       var calledRun = true;
+    </script>
    <script src="_framework/blazor.webassembly.js"></script>
```

*. Run the app.

----------------------
# Describe the bug
I am not sure if this is a bug, could be a limitation of Blazor, but when I add this script "https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js" to the wwwroot/index.html (within Head) the app no longer loads, the result is a blank page with just "Loading..." (from the default template), **there is no error anywhere**, I checked all consoles, even the client debug one. 

This script will throw an error as it tries to find THREE.js and fails but this should not stop the app tag from loading since these are two different processes that do not even touch each other, I've tested with other faulty scripts and when they throw errors the <app> loading is not interrupted.

I have tested this with the default Blazor template, altering nothing but the Head section of index.html (where I add the script).

I encountered this issue as I began trying to implement [AR.js](https://github.com/AR-js-org/AR.js). After I added the 3 necessary scripts the app stopped loading, then I isolated each script and found that one to be the one causing the issue.

### To Reproduce

1. Create new Blazor WebAssembly project
2. Add `<script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>` to wwwroot/index.html head section
3. Run

### Exceptions (if any)
```
Uncaught ReferenceError: THREE is not defined
    at aframe-ar-nft.js:41
(anonymous) @ aframe-ar-nft.js:41
```
but again...this shouldn't interrupt App from loading since in other similar situations it doesn't

**Comment by campersau** [comment]
Looks like an [emscripten](https://github.com/emscripten-core/emscripten) issue. Here is the code change which introduced it https://github.com/emscripten-core/emscripten/pull/9167

**Comment by kg** [comment]
@campersau is correct, and I don't see any simple way to fix this without an upstream fix in emscripten. I'll see if I can figure out a workaround though.

**Comment by campersau** [comment]
Looking at https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js it seems that it is also using emscripten/webassembly. Which is why the emscripten code is included twice. Is this something which emscripten even supports? I know that there are many other shared global variables which might interfere with each other. Like every property on the `Module` object.

**Comment by kg** [comment]
It appears that emscripten is not designed for this to work as-is. Based on the information in https://github.com/emscripten-core/emscripten/issues/10785 the issue may be that aframe is not being compiled with MODULARIZE turned on, and as a result hosting it in the same page as another webassembly module (in this case, Blazor) will not work.

If you can still reproduce this issue with a MODULARIZE'd build of aframe please feel free to reopen the issue.
