### ISSUE TITLE
Adding to SignalR groups using Context.UserIdentifier rather than Context.ConnectionId

### ISSUE THREAD

**Issue by Roy19** [dotnet/runtime#42512]
### Description

I was wondering why can't we add to SignalR groups using ```Context.UserIdentifier``` rather than using ```Context.ConnectionId```? Is it mostly an architectural issue? If so what might be the recommended approach for getting this behaviour?

Current behaviour: ```await Groups.AddToGroupsAsync(Context.ConnectionId, groupName)```.
Required behaviour: ```await Groups.AddToGroupsAsync(Context.UserIdentifier, groupName)```.

### Configuration

.NET Core version: 3.1.
SignalR server version: 3.1.0.

**Comment by gfoidl** [comment]
@Roy19 see your question in https://github.com/dotnet/aspnetcore/discussions/26121 (which is the correct place for this).
Can you please close this issue here?
