### ISSUE TITLE
ActivityTagsCollection allocates a lot

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#42510]
Almost every operation on `ActivityTagsCollection` uses `List.FindIndex`, which is basically LINQ.

If I create an `ActivityEvent` with a collection 5 tags, each add will eventually call FindIndex, allocating a closure and calling a delegate on previous items.

https://github.com/dotnet/runtime/blob/3ac170acc89adde016b1297f7c29232cda61c102/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/ActivityTagsCollection.cs#L76-L93

A low-level API like this shouldn't be using LINQ. A simple helper method to find the index of a specified key is all that is needed.

**Comment by tarekgh** [comment]
@JamesNK we'll look at fixing this in next release 6.0. I assume this is not a blocking issue for you.

**Comment by JamesNK** [comment]
6 is fine. It's not a blocking issue.
