### ISSUE TITLE
suggestion: make tests that take too long produce a coredump

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#42519]
There is currently nothing there that stops .NET library tests when they take too long. It would be interesting if they get aborted, and generate a coredump file for debugging.

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
That's precisely what we are planning to do. VSTest received numerous features that will make this possible. The remaining work here is to switch to VSTest.

**Comment by tmds** [comment]
@ViktorHofer great! I will close this and follow progress at https://github.com/dotnet/runtime/issues/37953.
