### ISSUE TITLE
Socket.SendFile(string) argument is supposed to be nullable

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#42530]
The docs for Socket.SendFile(string) state that the string argument is allowed to be null, and on .NET Framework when it's null, the operation executes fine, sending nothing.  However, in .NET 5 the string argument is annotated as non-nullable, and on Windows it throws an exception when null is provided, as in https://github.com/dotnet/runtime/issues/42529.

**Comment by wfurt** [comment]
I could see that it can be null if you can also pass in buffer but what do you expect to happen if you use overload just with the string name and that is not provided?

**Comment by stephentoub** [comment]
The same thing that happens on .NET Framework or if you use Socket.Send(new byte[0])... it sends nothing.
