### ISSUE TITLE
No Documentation for c# to wasm using Mono

### ISSUE THREAD

**Issue by guptay1** [dotnet/runtime#42573]
The samples on the link: [https://github.com/dotnet/runtime/tree/master/src/mono/netcore/sample/wasm](url) lacks documentation. It is known that mono provides support for c# to wasm but there is not much documentation on the how of it both on the mono project and this repository as a whole. @steveisok Since you added these samples just last month, can you update the repo with some documentation? Also, can you share some resources which can let new devs in c# to wasm space understand how can they make this happen using mono? These samples are **non-Blazor** ones and that is exactly what I want. I followed this repo in the past: [https://github.com/migueldeicaza/mono-wasm](url) but this seems like a dead project and the artifacts can be built only on macOS. Also went through the documentation on mono project but there is no such documentation available to the best of my knowledge. If it does, can anyone mention it?

**Comment by steveisok** [comment]
@guptay1 Certainly and thank you for the issue.  We'll also be adding a bit more to the samples beyond what's already there.  Hopefully it will help :-).

**Comment by guptay1** [comment]
@steveisok Thanks!! Also, could you share some resources which explain how mono can be used to generate wasm from bitcode? I couldn't find anything satisfactory on the web for the same. I stumbled upon **dotnet/corert** repo but it is experimental and wasm arch is even more experimental with limited functionality.

**Comment by SamMonoRT** [comment]
@steveisok - with the new samples added, can this be moved to future and/or closed ?

**Comment by pavelsavara** [comment]
Now we have basic features documented https://aka.ms/dotnet-wasm-features
