### ISSUE TITLE
Revise arm64_unix_skip_list in runtest.py

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#42577]
Found by accident when messing with the script in the runtimelab repo. We should probably revise the `arm64_unix_skip_list`.

This looks like an ARM64 bringup workaround from more than 2 year ago - I couldn't find associates issues. At this point it's probably just causing us to not have crossgen test coverage on ARM64 because I don't see what should be ARM64 specific on Microsoft.CodeAnalysis.VisualBasic.

https://github.com/dotnet/runtime/blob/c48127daec460692ee18f7ae7552bcc3f7fa8499/src/coreclr/tests/runtest.py#L1188-L1193

**Comment by am11** [comment]
Same case with other skip lists (`skip_list`, `unix_skip_list`) in this file. e.g. `System.Runtime.WindowsRuntime.UI.Xaml` project was deleted in #36715.

**Comment by mangod9** [comment]
since crossgen is no longer used this has part of the script has now been removed.
