### ISSUE TITLE
[.Net 4.5.2+] RuntimeBinderException “string”未包含“GetDateTime”的定义

### ISSUE THREAD

**Issue by chuxiaaaa** [dotnet/runtime#42572]
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: “string”未包含“GetDateTime”的定义

this code test in
```
.Net 4.5.2
.Net 4.7.2
.Net 4.8
```

```
public static DateTime GetDateTime(this String time)
{
    return DateTime.Parse(time);
}

dynamic time = "2020-08-10";
Console.WriteLine(time.GetDateTime());//throw Exception
Console.WriteLine((time as string).GetDateTime());//write:2020/8/10 0:00:00
```

**Comment by huoyaoyuan** [comment]
This should be by design. Dynamic binder cannot search for extension method.

**Comment by cston** [comment]
@chuxiaaaa, thanks for reporting this. 

As @huoyaoyuan mentioned, the behavior is by design since the `dynamic` binder does not search for extension methods.
