### ISSUE TITLE
ClaimsPrincipal.CurrentPrincipal throws ArgumentNullException if no principal is set.

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/runtime#42581]
This is on .NET 5 RC1 Windows

Repo:

Create a new console app and insert

``` csharp
class Program
{
	static void Main(string[] args)
	{
		System.Security.Claims.ClaimsPrincipal.Current?.ToString();
	}
}
```

Expected behavior: Runs without error

Actual behavior:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'principal')
   at System.Security.Claims.ClaimsPrincipal..ctor(IPrincipal principal)
   at System.Security.Claims.ClaimsPrincipal.SelectClaimsPrincipal()
   at System.Security.Claims.ClaimsPrincipal.get_Current()
```

**Comment by stephentoub** [comment]
Regression from .NET 3.1 and .NET Framework 4.8.

**Comment by stephentoub** [comment]
cc: @tannergooding 
https://github.com/dotnet/runtime/pull/40623

**Comment by tannergooding** [comment]
@bartonjs, this looks to be caused by `AppDomain._principalPolicy` differing by default.

In .NET Framework it was `UnauthenticedPrincipal` (`default`, `0`, etc), while in .NET Core it is set to `NoPrincipal` (`1`)

**Comment by jeffhandley** [comment]
@bartonjs Please take a look at this Wednesday if possible. The RC2 window closes Thursday morning, but this fix could also be considered for GA/RTM.

**Comment by bartonjs** [comment]
I don't actually know anything about how the principal stuff is supposed to work.  If we can't make it work like framework, let's just back out the change that was trying to make it work like framework.

**Comment by jeffhandley** [comment]
OK, thanks.  I didn't read through all the history beforehand; now I see and remember the specific comments/conversations around this change.  @eerhardt even [called this behavior out](https://github.com/dotnet/runtime/pull/40623/files#r468809814) in the PR and added a test to assert the `ArgumentNullException` that we introduced (to match NetFx).

But as @tannergooding [called out](https://github.com/dotnet/runtime/issues/42581#issuecomment-696782447), there was a different behavior within the `GetThreadPrincipal()` part of the fallback.

It seems are choices are:

1. Try to further align to .NET Framework with additional fixes (and perhaps a domino effect thereafter)
2. Revert #40623 and document that .NET 5 does not apply this fallback as https://github.com/dotnet/dotnet-api-docs/issues/4213 was originally filed for

The revert seems the lowest risk to me, especially at this stage of .NET 5.0.  What do others think?  Will it be acceptable for us to solidify that we do not perform the fallback?

**Comment by tannergooding** [comment]
From what I can tell, the behavior still "matches" .NET Framework, its just that the default `AppDomain._principalPolicy` differs and so the result differs.

That is .NET Core:
```csharp
return System.Security.Claims.ClaimsPrincipal.Current?.ToString();
```

Is effectively the following on .NET Framework (but with the `SetPrincipalPolicy` call happening as part of app startup):
```csharp
AppDomain.Current.SetPrincipalPolicy(PrincipalPolicy.NoPrincipal);
return System.Security.Claims.ClaimsPrincipal.Current?.ToString();
```

It all works as expected if you do the following on .NET Core and then functions identically to .NET Framework:
```csharp
AppDomain.Current.SetPrincipalPolicy(PrincipalPolicy.UnauthenticatedPrincipal);
return System.Security.Claims.ClaimsPrincipal.Current?.ToString();
```

I don't know what might depend on the .NET Core principal policy differing by default, so I couldn't say if simply switching it to `UnauthenticatedPrincipal` is "safe".

**Comment by vcsjones** [comment]
> I don't know what might depend on the .NET Core principal policy differing by default

[This has come up before](https://github.com/dotnet/runtime/issues/29151#issuecomment-480279920) and I don't think it should be changed, I think it would be fairly risky to change it right now.

>  What do others think?

To match .NET Framework completely seems against the grain of the design choices made in .NET Core (the default principal behavior changed as Tanner pointed out). The original issue by the customer was that it should fall back `Thread.CurrentPrincipal` however. We could just return null as it was doing in .NET Core 3 if there is no Thread principal.  Something like this:

```c#
private static ClaimsPrincipal? SelectClaimsPrincipal()
{
    return Thread.CurrentPrincipal switch {
        ClaimsPrincipal claimsPrincipal => claimsPrincipal,
        not null => new ClaimsPrincipal(Thread.CurrentPrincipal),
        null => null
    };
}
```

**Comment by AndreasHeisel** [comment]
I think @vcsjones's suggestion matches the documentation on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal.current?view=net-5.0#System_Security_Claims_ClaimsPrincipal_Current):

_By default, Thread.CurrentPrincipal is returned. You can change this behavior by setting the ClaimsPrincipalSelector property to specify a delegate to be called to determine the current principal._

And `Thread.Currentprincipal` is `null`.

**Comment by bartonjs** [comment]
Yeah, I think I can get behind @vcsjones' suggestion as a reasonable middle ground.
