### ISSUE TITLE
.NET 5 Linux Trimming Error

### ISSUE THREAD

**Issue by jjxtra** [dotnet/runtime#42582]
Publishing my app to Ubuntu with Linux-x64 platform using .NET 5 RC 1. Trimming is ON, single file is off.

Upon startup, I get this error:

```
Error Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
```

This error does not happen with .net core 3.1 with trimming enabled.

**Comment by Fabi** [comment]
> Publishing my app to Ubuntu with Linux-x64 platform using .NET 5 RC 1. Trimming is ON, single file is off.
> 
> Upon startup, I get this error:
> 
> ```
> Error Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
> File name: 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
>    at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
> ```
> 
> This error does not happen with .net core 3.1 with trimming enabled.

Exclude that  file from trimming

**Comment by jjxtra** [comment]
The file version is 0.0.0.0. It is not part of any of my nuget packages. How would I go about excluding this? It feels like a phantom file given the version...

**Comment by Fabi** [comment]
> The file version is 0.0.0.0. It is not part of any of my nuget packages that I can tell. How would I go about excluding this? It feels like a phantom file given the version...

Is this working? I got similar problems using that and stuff like that fixed many issues for me

```
<ItemGroup>
      <TrimmerRootAssembly Include="mscorlib" />
      <TrimmerRootAssembly Include="netstandard" />
</ItemGroup>
```

**Comment by jjxtra** [comment]
I had to add the following:

```
	<ItemGroup>
		<TrimmerRootAssembly Include="System.Core" />
		<TrimmerRootAssembly Include="System.Reflection" />
		<TrimmerRootAssembly Include="System.Runtime" />
		<TrimmerRootAssembly Include="mscorlib" />
		<TrimmerRootAssembly Include="netstandard" />
	</ItemGroup>
```

It's odd that these core set of assemblies would even be analyzed by the trimmer at all... :|

**Comment by Fabi** [comment]
Yea that's pretty annoying that's true.

**Comment by eerhardt** [comment]
@jjxtra - is it possible to share your .csproj and the exact command you ran to publish the app? You are right, you should not be seeing an error like this by default. I think something is going wrong.

cc @sbomer

**Comment by eerhardt** [comment]
I know `area-Host` isn't the greatest area for this issue - but there isn't an area for "linker" issues like there is for SingleFile, and it is better than "infrastructure". If there is a better one, please correct it.

**Comment by vitek-karas** [comment]
I think for now it's fine - I expect the problem to be somewhere in FX, but before we figure out where... it can stay here :wink:

**Comment by jjxtra** [comment]
I have 2 ubuntu servers. One of them oddly does not have this problem. The other, which I had previously installed the .NET 3.1.101 sdk on and then removed had the issue. Servers are identical otherwise.

```
  <PropertyGroup>
    <TargetFrameworks>net5.0</TargetFrameworks>
    <TrimUnusedDependencies>true</TrimUnusedDependencies>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <DebugType>portable</DebugType>
    <LangVersion>latest</LangVersion>
    <RootNamespace>***</RootNamespace>
    <AssemblyName>***</AssemblyName>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PublishTrimmed>true</PublishTrimmed>
    <GenerateSerializationAssemblies>false</GenerateSerializationAssemblies>
  </PropertyGroup>
```

**Comment by eerhardt** [comment]
Is this fixed now that we are copying facade assemblies? See https://github.com/mono/linker/issues/1837

**Comment by sbomer** [comment]
Yes, I believe this is fixed. (We're not copying facades - we're consistently keeping the pieces that are required by other assemblies that are copied or by string references to facade assemblies).
