### ISSUE TITLE
Displayed Windows Forms Controls Differ in Single File Deployment

### ISSUE THREAD

**Issue by ab-tools** [dotnet/runtime#42593]
### Steps to reproduce:
1. Load this simple example project: [WindowsFormsApp6.zip](https://github.com/dotnet/runtime/files/5263281/WindowsFormsApp6.zip)
2. Publish it with profile "Self-Contained" and run it - it will look like this on Windows 10 64 Bit:
![image](https://user-images.githubusercontent.com/1347603/93921674-28dc0280-fd11-11ea-8067-d153432da4e0.png)
3. Publish it with profile "Self-Contained-Single-File" and run it - it will look like this on Windows 10 64 Bit:
![image](https://user-images.githubusercontent.com/1347603/93922173-e0711480-fd11-11ea-904b-e4e3417a89cb.png)

### Expected Behavior:
No matter if published as single file or not the Windows Forms controls should be displayed the same when executed in the same Windows environment.

## Configuration

- .NET Version 5.0 RC1
- Windows 10.0.18363 64 Bit

**Comment by vitek-karas** [comment]
Thanks for reporting!

Workaround is to add a manifest to your app and add the "enable themes for common controls" section:
```XML
  <!-- Enable themes for Windows common controls and dialogs (Windows XP and later) -->
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
          type="win32"
          name="Microsoft.Windows.Common-Controls"
          version="6.0.0.0"
          processorArchitecture="*"
          publicKeyToken="6595b64144ccf1df"
          language="*"
        />
    </dependentAssembly>
  </dependency>
```

Then it works in both cases the same.
I don't really know why it fails to work without the manifest @AaronRobinsonMSFT any idea - maybe something to do with app contexts?

**Comment by jkotas** [comment]
Related to https://github.com/dotnet/sdk/issues/12904 ?

**Comment by vitek-karas** [comment]
Thanks @jkotas - definitely related, but there's something else going on here:
* publishing the app as self-contained (non-single-file) -> works without the custom manifest
* publishing the app as self-contained single-file -> doesn't work without the custom manifest
* publishing the app as framework dependent (non-single-file) -> works
* publishing the app as framework dependent single-file -> works

So the only difference I can think of is that the failing case is using singlefilehost, while all the other cases are using apphost. But I don't see a difference in the two which would cause this...

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas Agreed on this issue being related to Windows 10 support. If memory serves the Windows 10 styling is included when support is indicated in the manifest. Do we know the manifest situation in the apphost vs singlefilehost?

**Comment by vitek-karas** [comment]
I looked at the manifests of apphost and singlefilehost as produced by the repro - and they are identical (baring any mistakes I might have made). That's what's really weird - as far as I can tell the two binaries look the same.

**Comment by jkotas** [comment]
This: https://github.com/dotnet/winforms/blob/02089e92406b3f508c05060ee0ee7857a8ba3c11/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs#L824

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Boo. That is unfortunate. We should also check out WPF I guess.

**Comment by vitek-karas** [comment]
WPF at least by default should be OK as it does all of its rendering, unlike WinForms which relies on the OS. But there definitely could be some other problems.

This is basically "WinForms is currently not fully compatible with single-file" - unfortunately. Not sure what the fix is though - I can't find a way to create activation context without a file on disk in Win32 APIs. We would have to make this a resource of the singlefilehost - which is definitely doable.

**Comment by AaronRobinsonMSFT** [comment]
>We would have to make this a resource of the singlefilehost - which is definitely doable.

Yep. That is a requirement for the activation context. I used an Activation Context in CoreRun.

https://github.com/dotnet/runtime/blob/a986fe1492e82ba25be351cc76400e5eacfe93ac/src/coreclr/src/hosts/corerun/corerun.cpp#L415-L445

**Comment by ab-tools** [comment]
Just retested this again with Visual Studio 16.9.0 Preview 3 and .NET SDK 5.0.200.preview.20614.14 and looks like things got worse:
Now the Windows Forms application crashes upon application start when published using single file deployment.

**Comment by vitek-karas** [comment]
The underlying problem is https://github.com/dotnet/runtime/issues/40103.
Just to prove it - you can try running the app from the Visual Studio Developer Command Prompt - it works for me (and fails without that).

The fix in progress here: https://github.com/dotnet/runtime/pull/47437

**Comment by vitek-karas** [comment]
With https://github.com/dotnet/runtime/pull/47464 the behavior should be consistent no matter the environment - meaning it should always fail. We think this regression happened because those who tested it happen to run in an environment where it worked.
