### ISSUE TITLE
[Release/3.1] Better way to consume oob corefx packages in coreclr testing.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#42595]
Coreclr uses Microsoft.Private.CoreFx.OOB package to get the oob assemblies.
This package is no longer shipped after rtm version. Hence it doesnot contains assemblies with servicing fixes.

Corefx Tests in coreclr require latest versions. 

Possible Solutions here:-
1) manually add the package references of the servicing packages to corefx.depproj
2) flow all the packages through maestro as a toolset dependency
3) start producing the non-shipping version Microsoft.Private.CoreFx.OOB in servicing releases.

The third is the best option here as its easier to maintain & it will also help us fix https://github.com/dotnet/runtime/issues/42594 

And we already produce some toolset packages in every release for coreclr and core-setup repos

cc @ericstj @safern @ViktorHofer @jkoritzinsky @tommcdon

**Comment by safern** [comment]
I would go with option 3 as well.

**Comment by ViktorHofer** [comment]
> Coreclr uses Microsoft.Private.CoreFx.OOB package to get the oob assemblies.

Why does coreclr depend on library prebuilts?

**Comment by ViktorHofer** [comment]
Microsoft.Private.CoreFx.OOB got deleted 1-2 years ago. Closing.
