### ISSUE TITLE
[release/3.1] Produce a dummy non shipping package every servicing release to run a package testing for allConfig leg

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#42594]
We run package testing when we are servicing an oob package. This leads to vulnerable to changes breaking the package testing in cases when we are not producing any package.

eg https://github.com/dotnet/corefx/commit/55ee01418f3af008cee0adb96635b803b51f48d8 

Producing a dummy package and running package testing on this could easily resolve this issue.

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
Closing as we already produce at least the transport packages per servicing build in main and 3.1 is going out of support next month.
