### ISSUE TITLE
[Proposal] Add Timeout property to Webclient

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#42598]
## Background and Motivation

Currently `System.Net.Webclient` does not support an easy way to set a timeout where a web request should be cancelled / throw a timeout exception. But something like this is constantly requested/asked, see https://stackoverflow.com/questions/601861/set-timeout-for-webclient-downloadfile

The link above also gave a solution but it requires to inherit webclient and override a method. I would prefer it becomes a property instead.

Situations where a smaller timeout is useful is when we batch download files and make it as fast as possible by skipping requests which takes too long. But since this property does not rely on `DownloadFile` only it also benefits to other situations.

## Proposed API

```diff
namespace System.Net
{
    public class WebClient : Component {
+   public int Timeout { get; set; }
}
```

## Usage Examples

``` C#
for (int i = 0; i < 500_000; i++)
{
    var wc = new WebClient { Timeout = 100 };
    try
    {
        wc.DownloadFile(new Uri($"https://www.test.com/images/{i}.jpg"), path + i + ".jpg");
    }
    catch (TimeoutException) { }
    catch (Exception e)
    {
        throw;
    }
}
```

## Alternative Designs

See solution https://stackoverflow.com/a/3052637 by Beniamin
```
using System;
using System.Net;

public class WebDownload : WebClient
{
    /// <summary>
    /// Time in milliseconds
    /// </summary>
    public int Timeout { get; set; }

    public WebDownload() : this(60000) { }

    public WebDownload(int timeout)
    {
        this.Timeout = timeout;
    }

    protected override WebRequest GetWebRequest(Uri address)
    {
        var request = base.GetWebRequest(address);
        if (request != null)
        {
            request.Timeout = this.Timeout;
        }
        return request;
    }
}
```

## Risks

None

**Comment by huoyaoyuan** [comment]
`WebClient` is going to be [deprecated](https://github.com/dotnet/platform-compat/blob/master/docs/DE0004.md). New api wouldn't be accepted.
For replacement, `HttpClient` already has `Timeout` property.

**Comment by Symbai** [comment]
Good point, I missed that. Too bad HttpClient has only async methods and is missing some very convenience methods like DownloadFile and DownloadString and therefore bloats up developers own code. So for me its far away from being a replacement.
