### ISSUE TITLE
Host errors and trace should be improved

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#42607]
I recently ran into an unsupported scenario, per #42478. Per the advice of the team, I enabled host tracing. It sadly did not give me more information than the cryptic error that was already available at the commandline. That was disappointing for an enormous trace file. 

In the specific example, the application was attempting to use an assembly/binary that was unsupported. It should have been included in trace. It would also have been good to have a hint as to why that binary was unsupported, if known.

One imagines that there are other known cases where apps will fail to load for known reasons that are not captured in the log.

I'd propose that we add more logging and then look at opportunities to improve the console error messages. It would be really good if we could generate links to help, as well.

**Comment by agocke** [comment]
I feel as though we have a lot of concrete issues on this topic, and this one is somewhat vague. I'm going to close it in favor of the others, but happy to re-open if we want to be more specific in direction.
