### ISSUE TITLE
Span.Reverse is x6 times slower than Array.Reverse

### ISSUE THREAD

**Issue by astrowalker** [dotnet/runtime#42618]
### Description

Simply run this code, on two computers I measured this absolute times differ of course, but the relative times are the same -- Span.Reverse is around x6 times slower than Array.Reverse.

What this code does is it allocates "big" array once, and then reverses endianess using Array.Reverse and Span.Reverse. Internal loops (indexed by `i`) serve to simulate bigger memory chunk, and outer loop (indexed with `g`) is simply a repetition of the test and making sure both approaches are interleaved.

        static unsafe void Reversing()
        {
            long array_ticks = 0;
            long span_ticks                = 0;
            var data = new byte[1024 * 1024 * 1024];

            for (int g = 0; g < 10; ++g)
            {
                Console.WriteLine($"Iteration {g}");
                {
                    var start = Stopwatch.GetTimestamp();
                    for (int i = 0; i < 5; ++i)
                        data.Reverse(0, data.Length, 8);
                    array_ticks += (Stopwatch.GetTimestamp() - start);
                }
                {
                    GCHandle handle = GCHandle.Alloc(data, GCHandleType.Pinned);
                    try
                    {
                        IntPtr address = handle.AddrOfPinnedObject();
                        var span = new Span<byte>(address.ToPointer(), data.Length);
                        var start = Stopwatch.GetTimestamp();
                        for (int i = 0; i < 5; ++i)
                            span.Reverse(0, data.Length, 8);
                        span_ticks += (Stopwatch.GetTimestamp() - start);
                    }
                    finally
                    {
                        handle.Free();
                    }
                }
            }

            Console.WriteLine($"Array {TimeSpan.FromSeconds(array_ticks*1.0/Stopwatch.Frequency)} span {TimeSpan.FromSeconds(span_ticks * 1.0 / Stopwatch.Frequency)}");
        }

### Configuration

Windows 10, x64, Net Core 3.1.

### Regression?

I am not aware of this.

**Comment by Joe4evr** [comment]
The first thing that stands out to me is that you're measuring using `Stopwatch`, which is discouraged since timings recorded this way can and will change due to the JIT. I'd suggest rewriting and running your tests in BenchmarkDotNet, since that's able to properly measure around the JIT's variance.

**Comment by astrowalker** [comment]
Ah, sorry, for making noise, my mistake, sorry for making noise.
