### ISSUE TITLE
MetadataReference and Single File Applications on .NET 5.0 RC

### ISSUE THREAD

**Issue by ppekrol** [dotnet/runtime#42621]
Hi,

before going with Single File Applications (SFA) my code looked like follows:

```
MetadataReference.CreateFromFile(typeof(Lucene.Net.Documents.Document).Assembly.Location),
```

Obviosuly the `Assembly.Location` is not working after publishing SFA. My question is what is recommended way to work with Roslyn and create MetadataReference when using SFA? I could not find a way to convert in-memory assembly into Stream or byte array (which would be enough for me I guess).

I'm using .NET 5.0 RC 1

```
Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
```

**Comment by jkotas** [comment]
Try this: https://github.com/dotnet/runtime/issues/36590#issuecomment-689883856

**Comment by ppekrol** [comment]
Works like a charm! Thank you for the guidelines.
