### ISSUE TITLE
NETCOREAPP3_1 is declared in .NET 5.0 RC1

### ISSUE THREAD

**Issue by virzak** [dotnet/runtime#42627]
### Description

When running this code using .NET 5, the expectation is that it will compile, but it doesn't:

```csharp
using System;

namespace MacroBug
{
    public class Class1
    {

#if NETCOREAPP3_1
NETCOREAPP3_1 Here to break Compilation
#endif

#if NETCOREAPP3_0
NETCOREAPP3_0 Here to break Compilation
#endif

#if !NET5_0
!NET5_0 Here to break Compilation
#endif
        
    }
}
```

### Configuration

.NET 5.0 RC 1 (5.0.100-rc.1.20452.10) on Windows 10 x64

### Other information

NETCOREAPP3_0 works as expected (not declared in .NET 5)

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/sdk/issues/13377. See https://github.com/dotnet/docs/issues/20692.
