### ISSUE TITLE
Missing command-line-api repo reference in eng/Version.Details.xml

### ISSUE THREAD

**Issue by crummel** [dotnet/runtime#42637]
Runtime uses the dotnet/command-line-api repo, e.g. [here](https://github.com/dotnet/runtime/blob/57fde8309798a53c4bf6eb2b579683d9f3e71bf6/src/coreclr/src/tools/aot/crossgen2/crossgen2.csproj#L38), but this is not included in eng/Version.Details.xml, so Arcade/Maestro package updates and uberclone will not know about the dependency.  This should be added at an appropriate version and hash.

**Comment by mangod9** [comment]
@AntonLapounov is looking at updating the command-line dependency.

**Comment by trylek** [comment]
@AntonLapounov, is this item ready to be closed based on your fix?

**Comment by trylek** [comment]
OK, so it looks like this issue now effectively tracks removing the "new slow" System.CommandLine from ILVerify and R2RDump. While I believe that R2RDump is not considered a shipping product now, I'm not sure about ILVerify. If ILVerify is a shipping product, we should migrate it to the same parser as Crossgen2.

**Comment by mangod9** [comment]
Moving to ILVerification area since its now tracking ILVerify's usage of Commandline.

**Comment by AntonLapounov** [comment]
The dotnet/source-build#1886 issue that motivated this one has been closed.  I don't think it is necessary to do any changes for 6.0.

**Comment by EgorBo** [comment]
I assume it was fixed by https://github.com/dotnet/runtime/pull/66929
