### ISSUE TITLE
[QUIC] Split out MsQuic configuration from connection

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#42642]
An MsQuic configuration allocates a number of resources that are able to be shared between multiple connections.

Currently, we are sharing a configuration on server connections, but are allocating a new one per client-initiated connection. We should consider breaking this out into its own API so that e.g. the `SocketsHttpHandler` connection pools can have a single configuration.

**Comment by geoffkizer** [comment]
What settings/resources are associated with an msquic session?

**Comment by scalablecory** [comment]
According to [docs](https://github.com/microsoft/msquic/blob/main/docs/API.md#session):
> Primarily, this consists of the ALPN string used for the connection handshakes and TLS state used for session resumption.

@nibanks anything else interesting to consider? Why would we ever want to have separate sessions (beyond different ALPN strings)?

**Comment by nibanks** [comment]
The MsQuic "session" object is completely going away. I'd just close this issue. See this PR for more details: https://github.com/microsoft/msquic/pull/777

**Comment by scalablecory** [comment]
This would look something like:

```c#
QuicClientConnectionOptions options = ...;
EndPoint endPoint = ...;

using QuicClientConfiguration clientConfig = await QuicConfiguration.CreateAsync(options, cancellationToken);
using QuicConnection connection = await QuicConnection.ConnectAsync(clientConfig, endPoint, cancellationToken);
```

**Comment by rzikm** [comment]
Since lot of the things have changed since the issue was originally created the issue does not make sense in the current state.
