### ISSUE TITLE
[QUIC] Optimize stream reads

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#42651]
The way we are implementing stream reads means we will often have more async/await overhead than is needed.

Instead of having an internal resettable task that we always await inside of `ReadAsync`, we should return a resettable task and have the MsQuic callback manage completing it. This will allow us to avoid an async state machine in ReadAsync().

**Comment by scalablecory** [comment]
Implementing this as part of #756

**Comment by ManickaP** [comment]
@CarnaViire was this fixed with your PR which scavenged Cory's PR? Can you close this in case of a YES, please?

**Comment by CarnaViire** [comment]
Yes, this was done in #55505
