### ISSUE TITLE
Failed to set a breakpoint on Codespaces

### ISSUE THREAD

**Issue by digeff** [dotnet/runtime#42652]
DebugProxy.SetBreakpoint failed to set a breakpoint on Blazor/Codespaces.

We got a scriptParsed event:
![image](https://user-images.githubusercontent.com/14098140/94074534-53c86400-fdae-11ea-9f49-e5c58803184b.png)
We tried setting a breakpoint:
![image](https://user-images.githubusercontent.com/14098140/94074569-69d62480-fdae-11ea-82b9-7aae1809c318.png)
Both on lines 0 and line 13 and they failed:
![image](https://user-images.githubusercontent.com/14098140/94074589-7490b980-fdae-11ea-96cc-124c1a860627.png)

I'm attaching the debug adapter log with all these messages.
[blazor not hitting bp visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/5272260/blazor.not.hitting.bp.visualstudio-js-debugger.txt)

**Comment by lewing** [comment]
This is because the current proxy was only acting on setBreakpointByUrl, we can add a handler for setBreakpoint but in the meantime you should be able to set a breakpoint there by calling setBreakpointByUrl  with url (not urlRegex) set to the dotnet: url.

**Comment by digeff** [comment]
@lewing Do the urlRegexp version work? (it might be easier for us to get that one working)

**Comment by lewing** [comment]
That should also work as long at the regex matches what is in the url param of the scriptParsed event

**Comment by lewing** [comment]
I believe this particular issue has been fixed
