### ISSUE TITLE
Test failure: threading.WaitForSingleObject.WFSOExSemaphoreTest

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42669]
failed in job: [runtime-coreclr jitstress 20200922.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=826675&view=ms.vss-test-web.build-test-results-tab&runId=26350172&resultId=109027&paneView=debug)

CoreCLR Linux arm64 Checked jitminopts @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

Error message
~~~
Expected thread to wait for 2000 ms (and get interrupted).
Thread waited for 1999 ms! (Acceptable delta: 300)


Stack trace
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr jitstress2-jitstressregs 20201004.1](https://dev.azure.com/dnceng/public/_build/results?buildId=841296&view=ms.vss-test-web.build-test-results-tab&runId=26798506&resultId=108478&paneView=debug)

failed test: threading.WaitForSingleObject.WFSOExSemaphoreTest

CoreCLR Linux arm64 Checked jitstress2_jitstressregs3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

Error message
~~~
Expected thread to wait for 2000 ms (and get interrupted).
Thread waited for 1999 ms! (Acceptable delta: 300)

Stack trace
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr gcstress-extra 20201024.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=865125&view=ms.vss-test-web.build-test-results-tab&runId=27706686&paneView=debug&resultId=103782)

failed test: threading.WaitForSingleObject.WFSOExSemaphoreTest

CoreCLR Linux arm64 Checked gcstress0xc_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855


Error message
~~~
Expected thread to wait for 2000 ms (and get interrupted).
Thread waited for 1999 ms! (Acceptable delta: 300)


Stack trace
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr jitstress2-jitstressregs 20201122.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=895910&view=ms.vss-test-web.build-test-results-tab&runId=28630928&resultId=107669&paneView=debug)

failed test: threading.WaitForSingleObject.WFSOExSemaphoreTest

CoreCLR Linux arm64 Checked jitstress2_jitstressregs1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855


Error message
~~~
Expected thread to wait for 2000 ms (and get interrupted).
Thread waited for 1999 ms! (Acceptable delta: 300)


Stack trace
~~~

**Comment by BruceForstall** [comment]
@kouvel In case you didn't see, this test has failed (at least) 4 times in different jobs.

**Comment by kouvel** [comment]
Sure I'll take a look

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr outerloop 20201210.4](https://dev.azure.com/dnceng/public/_build/results?buildId=916467&view=ms.vss-test-web.build-test-results-tab&runId=29153310&resultId=108764&paneView=debug)

failed test: threading.WaitForSingleObject.WFSOExSemaphoreTest

CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440


Error message
~~~
Expected thread to wait for 2000 ms (and get interrupted).
Thread waited for 1999 ms! (Acceptable delta: 300)


Stack trace
~~~
