### ISSUE TITLE
ILLink Task failed unexpectedly inside VS

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#42676]
```
Error	MSB4018	The "ILLink" task failed unexpectedly.
System.InvalidOperationException: DOTNET_HOST_PATH is not set
   at ILLink.Tasks.ILLink.get_DotNetPath()
   at ILLink.Tasks.ILLink.GenerateFullPathToTool()
   at Microsoft.Build.Utilities.ToolTask.ComputePathToTool()
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	System.Private.Xml	C:\git\runtime3\eng\illink.targets	288	
```

Repro steps: https://github.com/dotnet/runtime/issues/20411#issuecomment-698381392.

cc @layomia @ericstj

**Comment by eerhardt** [comment]
FYI - @sbomer @vitek-karas

**Comment by sbomer** [comment]
This shouldn't be a problem in the SDK, where we already look at `NetCoreRoot`: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L82. See also https://github.com/mono/linker/issues/806.

**Comment by ViktorHofer** [comment]
This is about Desktop MSBuild inside VS. I don't think the SDK comes into play here?

**Comment by sbomer** [comment]
VS still uses the SDK targets (just on desktop MSBuild) when publishing. We still need the fix in runtime - I'm just talking about the "dotnet publish /p:PublishTrimmed" scenario. Desktop MSBuild or not, these targets locate a dotnet host, and start a new process that runs the linker on .NET Core.

**Comment by ViktorHofer** [comment]
Oh, just to clarify, this is broken in our custom invocation of the ILLinkTask in illink.targets: eng\illink.targets	288.

**Comment by sbomer** [comment]
Right, I'm just trying to pre-empt concerns that it's similarly broken in the SDK. :)

**Comment by ViktorHofer** [comment]
Ah cool, got it.
