### ISSUE TITLE
[5.0.0-rc.1.20452.10 (x64)] Single File Publish issue on WPF APP Core 3.0  after retarget .NET5.0

### ISSUE THREAD

**Issue by alvaro-vantis-pt** [dotnet/runtime#42672]
### Description

WPF App does not launch after retarget from Core 3.1 to  NET 5.0. App was retarget in Visual Studio Version 16.8.0 Preview 3.1 

Normal published app can be launched. Only the Single file unable to launch

Single File was published with the following command on "x64 native tools command prompt for VS2019 Platform":
`dotnet publish -r win10-x64 -p:PublishSingleFile=true -c:Release`

also tried with:
`dotnet publish -r win10-x64 -p:PublishSingleFile=true -c:Release -p:PublishTrimmed=false`
and same result.

The following exceptions were found in Application Event Log:
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-09-23T12:34:01.116709600Z" /> 
  <EventRecordID>3372</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>CleanCode1.vantis.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: CleanCodeApp.exe CoreCLR Version: 5.0.20.45114 .NET Version: 5.0.0-rc.1.20451.14 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Threading.Dispatcher' threw an exception. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002) at System.Reflection.RuntimeModule.GetFullyQualifiedName() at System.Reflection.RuntimeModule.get_Name() at System.Windows.WpfDllVerifier.VerifyWpfDllSet(String[] additionalDlls) at System.Windows.Threading.Dispatcher..cctor() --- End of inner exception stack trace --- at System.Windows.Threading.Dispatcher.get_CurrentDispatcher() at System.Windows.Threading.DispatcherObject..ctor() at System.Windows.Application..ctor() at CleanCodeApp.App..ctor() at CleanCodeApp.App.Main()</Data> 
  </EventData>
  </Event>`

`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-09-23T12:34:01.383238500Z" /> 
  <EventRecordID>3373</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>CleanCode1.vantis.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>CleanCodeApp.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>5f4ed81c</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.18362.1049</Data> 
  <Data>1b835a75</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000043b29</Data> 
  <Data>2898</Data> 
  <Data>01d691a5d0790ba1</Data> 
  <Data>C:\Users\alvaro.pereira\source\repos\Vantis-Projects\CleanCode\Vantis.CleanCode\CleanCodeApp\bin\Debug\net5.0\win-x64\publish\CleanCodeApp.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>08734a0e-fbbf-4181-a6f9-619cc6be1e32</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`
'
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-09-23T12:34:04.926017400Z" /> 
  <EventRecordID>3374</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>CleanCode1.vantis.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>1892187016256525009</Data> 
  <Data>4</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>CleanCodeApp.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>5f4ed81c</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.18362.1049</Data> 
  <Data>1b835a75</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000043b29</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AFD.tmp.mdmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33F6.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3446.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3463.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34B2.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CleanCodeApp.exe_976e6eaff88f256636ab5dd2ea0f84b3d77d19_8832f621_85932e8b-cb9a-4b50-b464-42d1660874ad</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>08734a0e-fbbf-4181-a6f9-619cc6be1e32</Data> 
  <Data>268435456</Data> 
  <Data>95ad1110329667830a426610e89392d1</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>`

### Configuration
Windows 10 - Pro x64
`Get-ComputerInfo -Property *

WindowsBuildLabEx                                       : 17763.1.amd64fre.rs5_release.180914-1434
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerHyper
WindowsInstallationType                                 : Server Core
WindowsInstallDateFromRegistry                          : 8/26/2020 4:17:11 PM
WindowsProductId                                        : 03612-029-0000043-76134
WindowsProductName                                      : Hyper-V Server 2019 
WindowsRegisteredOrganization                           : 
WindowsRegisteredOwner                                  : 
WindowsSystemRoot                                       : C:\Windows
WindowsVersion                                          : 1809
BiosCharacteristics                                     : {7, 9, 11, 12...}
BiosBIOSVersion                                         : {HPE    - 1, U30, HPE - 22200}
BiosBuildNumber                                         : 
BiosCaption                                             : U30
BiosCodeSet                                             : 
BiosCurrentLanguage                                     : 
BiosDescription                                         : U30
BiosEmbeddedControllerMajorVersion                      : 2
BiosEmbeddedControllerMinorVersion                      : 16
BiosFirmwareType                                        : Uefi
BiosIdentificationCode                                  : 
BiosInstallableLanguages                                : 
BiosInstallDate                                         : 
BiosLanguageEdition                                     : 
BiosListOfLanguages                                     : 
BiosManufacturer                                        : HPE
BiosName                                                : U30
BiosOtherTargetOS                                       : 
BiosPrimaryBIOS                                         : True
BiosReleaseDate                                         : 4/8/2020 1:00:00 AM
BiosSeralNumber                                         : CZ202903RH
BiosSMBIOSBIOSVersion                                   : U30
BiosSMBIOSMajorVersion                                  : 3
BiosSMBIOSMinorVersion                                  : 2
BiosSMBIOSPresent                                       : True
BiosSoftwareElementState                                : Running
BiosStatus                                              : OK
BiosSystemBiosMajorVersion                              : 2
BiosSystemBiosMinorVersion                              : 34
BiosTargetOperatingSystem                               : 0
BiosVersion                                             : HPE    - 1
CsAdminPasswordStatus                                   : Unknown
CsAutomaticManagedPagefile                              : True
CsAutomaticResetBootOption                              : True
CsAutomaticResetCapability                              : True
CsBootOptionOnLimit                                     : 
CsBootOptionOnWatchDog                                  : 
CsBootROMSupported                                      : True
CsBootStatus                                            : {0, 0, 0, 203...}
CsBootupState                                           : Normal boot
CsCaption                                               : PANDORA
CsChassisBootupState                                    : Safe
CsChassisSKUNumber                                      : 
CsCurrentTimeZone                                       : 60
CsDaylightInEffect                                      : True
CsDescription                                           : AT/AT COMPATIBLE
CsDNSHostName                                           : p*******
CsDomain                                                : ******.local
CsDomainRole                                            : MemberServer
CsEnableDaylightSavingsTime                             : True
CsFrontPanelResetStatus                                 : Unknown
CsHypervisorPresent                                     : True
CsInfraredSupported                                     : False
CsInitialLoadInfo                                       : 
CsInstallDate                                           : 
CsKeyboardPasswordStatus                                : Unknown
CsLastLoadInfo                                          : 
CsManufacturer                                          : HPE
CsModel                                                 : ProLiant DL380 Gen10
CsName                                                  : P******
CsNetworkAdapters                                       : {Ethernet, Embedded LOM 1 Port 3, Embedded LOM 1 Port 1, Embedded LOM 1 
                                                          Port 4...}
CsNetworkServerModeEnabled                              : True
CsNumberOfLogicalProcessors                             : 16
CsNumberOfProcessors                                    : 1
CsProcessors                                            : {Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz}
CsOEMStringArray                                        : {PSF:                                                            , Product 
                                                          ID: P06420-B21, OEM String: }
CsPartOfDomain                                          : True
CsPauseAfterReset                                       : -1
CsPCSystemType                                          : EnterpriseServer
CsPCSystemTypeEx                                        : EnterpriseServer
CsPowerManagementCapabilities                           : 
CsPowerManagementSupported                              : 
CsPowerOnPasswordStatus                                 : Unknown
CsPowerState                                            : Unknown
CsPowerSupplyState                                      : Safe
CsPrimaryOwnerContact                                   : 
CsPrimaryOwnerName                                      : 
CsResetCapability                                       : Other
CsResetCount                                            : -1
CsResetLimit                                            : -1
CsRoles                                                 : {LM_Workstation, LM_Server, NT, Server_NT}
CsStatus                                                : OK
CsSupportContactDescription                             : 
CsSystemFamily                                          : ProLiant
CsSystemSKUNumber                                       : P06420-B21
CsSystemType                                            : x64-based PC
CsThermalState                                          : Safe
CsTotalPhysicalMemory                                   : 34000547840
CsPhyicallyInstalledMemory                              : 33554432
CsUserName                                              : 
CsWakeUpType                                            : PowerSwitch
CsWorkgroup                                             : 
OsName                                                  : Microsoft Hyper-V Server
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : MicrosoftHyperVServer
OsVersion                                               : 10.0.17763
OsCSDVersion                                            : 
OsBuildNumber                                           : 17763
OsHotFixes                                              : {KB4570720, KB4494174, KB4512577, KB4566424...}
OsBootDevice                                            : \Device\HarddiskVolume1
OsSystemDevice                                          : \Device\HarddiskVolume3
OsSystemDirectory                                       : C:\Windows\system32
OsSystemDrive                                           : C:
OsWindowsDirectory                                      : C:\Windows
OsCountryCode                                           : 1
OsCurrentTimeZone                                       : 60
OsLocaleID                                              : 0409
OsLocale                                                : en-US
OsLocalDateTime                                         : 9/24/2020 10:15:11 AM
OsLastBootUpTime                                        : 9/14/2020 11:17:08 AM
OsUptime                                                : 9.22:58:02.6607450
OsBuildType                                             : Multiprocessor Free
OsCodeSet                                               : 1252
OsDataExecutionPreventionAvailable                      : True
OsDataExecutionPrevention32BitApplications              : True
OsDataExecutionPreventionDrivers                        : True
OsDataExecutionPreventionSupportPolicy                  : OptOut
OsDebug                                                 : False
OsDistributed                                           : False
OsEncryptionLevel                                       : 256
OsForegroundApplicationBoost                            : Maximum
OsTotalVisibleMemorySize                                : 33203660
OsFreePhysicalMemory                                    : 8554228
OsTotalVirtualMemorySize                                : 38184396
OsFreeVirtualMemory                                     : 13422728
OsInUseVirtualMemory                                    : 24761668
OsTotalSwapSpaceSize                                    : 
OsSizeStoredInPagingFiles                               : 4980736
OsFreeSpaceInPagingFiles                                : 4846384
OsPagingFiles                                           : {C:\pagefile.sys}
OsHardwareAbstractionLayer                              : 10.0.17763.1369
OsInstallDate                                           : 8/26/2020 5:17:11 PM
OsManufacturer                                          : Microsoft Corporation
OsMaxNumberOfProcesses                                  : 4294967295
OsMaxProcessMemorySize                                  : 137438953344
OsMuiLanguages                                          : {en-US}
OsNumberOfLicensedUsers                                 : 0
OsNumberOfProcesses                                     : 82
OsNumberOfUsers                                         : 10
OsOrganization                                          : 
OsArchitecture                                          : 64-bit
OsLanguage                                              : en-US
OsProductSuites                                         : {TerminalServicesSingleSession}
OsOtherTypeDescription                                  : 
OsPAEEnabled                                            : 
OsPortableOperatingSystem                               : False
OsPrimary                                               : True
OsProductType                                           : Server
OsRegisteredUser                                        : 
OsSerialNumber                                          : 03612-029-0000043-76134
OsServicePackMajorVersion                               : 0
OsServicePackMinorVersion                               : 0
OsStatus                                                : OK
OsSuites                                                : {TerminalServices, TerminalServicesSingleSession}
OsServerLevel                                           : ServerCore
KeyboardLayout                                          : 
TimeZone                                                : (UTC+00:00) Dublin, Edinburgh, Lisbon, London
LogonServer                                             : 
PowerPlatformRole                                       : EnterpriseServer
HyperVisorPresent                                       : True
HyperVRequirementDataExecutionPreventionAvailable       : 
HyperVRequirementSecondLevelAddressTranslation          : 
HyperVRequirementVirtualizationFirmwareEnabled          : 
HyperVRequirementVMMonitorModeExtensions                : 
DeviceGuardSmartStatus                                  : Off
DeviceGuardRequiredSecurityProperties                   : {0}
DeviceGuardAvailableSecurityProperties                  : {BaseVirtualizationSupport, DMAProtection, SecureMemoryOverwrite, 5...}
DeviceGuardSecurityServicesConfigured                   : {0}
DeviceGuardSecurityServicesRunning                      : {0}
DeviceGuardCodeIntegrityPolicyEnforcementStatus         : 
DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus : `

It works fine in .NET Core 3.1

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/runtime/issues/38636, this should be fixed in RC2.

**Comment by alvaro-vantis-pt** [comment]
Just to give a feedback. I've tried RC2 from latest build on GITHUB and it worked as expected.
