### ISSUE TITLE
Do not run `stackLevelSetter` except for x86.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#42673]
Stack level setter is required only for x86, on other platforms, it could be skipped or run only in debug.

However, there is an issue with disabling it:
Stack level setter has code that was supposed to be run only on x86 but is running on all platforms currently:
https://github.com/dotnet/runtime/blob/5cded6d1cab7862a33ed5ee1637065f304119910/src/coreclr/src/jit/stacklevelsetter.cpp#L328-L340

If you put it under `TARGET_X86` as I did in #42197 you will see a big size regressions because you will have to encode bigger offset (from the rsp instead of saved rsp+offset):
```
-000013 lea      rbp, [rsp+C0H]
-000104 mov      dword ptr [V04 rbp+30H], r15d
-000108 mov      dword ptr [V06 rbp+40H], r12d
-00010C mov      dword ptr [V07 rbp+48H], r13d
-
+000102 mov      dword ptr [V04 rsp+F0H], r14d
+00010A mov      dword ptr [V06 rsp+100H], r15d
+000112 mov      dword ptr [V07 rsp+108H], r12d
```

and also see bunch of new bad LSRA decisions. 

category:implementation
theme:throughput
skill-level:beginner
cost:small

**Comment by sandreenko** [comment]
Moving to future unless we have time after https://github.com/dotnet/runtime/issues/7996 to do this.

**Comment by AndyAyersMS** [comment]
I am now co-opting this phase to also scan for unused throw helper blocks, so we will just be running it always.

**Comment by AndyAyersMS** [comment]
https://github.com/dotnet/runtime/pull/95379 now uses this phase for trimming throw helpers. So, closing this.

TP hit from running this phase (non-x86) is around 0.2%
