### ISSUE TITLE
mono_wasm_invoke_js does not handle embedded nulls

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#42693]
### Description

If you use mono_wasm_invoke_js (InvokeJS in managed code) to return a string with embedded nulls, it's truncated at the first null.

The problem is this line in driver.c:

```c
	MonoString *res = mono_string_from_utf16 (native_res);
```

### Regression?

no

**Comment by ericstj** [comment]
@kg is this the same issue you mentioned here: https://github.com/dotnet/runtime/pull/42666?

**Comment by kg** [comment]
It's the same problem but in a different API, I only noticed it while writing a test. My PRs don't fix it

**Comment by vargaz** [comment]
The linked PR should fix it, altough I couldn't test it.
