### ISSUE TITLE
[wasm][debugger] BP on hidden line; debugger should stop at the next available line

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#42704]
This fails with master:

```csharp
        [Fact]
        public async Task BreakpointOnHiddenLineShouldStopAtEarliestNextAvailableLine()
        {
            var insp = new Inspector();

            //Collect events
            var scripts = SubscribeToScripts(insp);

            await Ready();
            await insp.Ready(async (cli, token) =>
            {
                ctx = new DebugTestContext(cli, insp, token, scripts);

                await SetBreakpoint("dotnet://debugger-test.dll/debugger-test.cs", 539, 8);
                await EvaluateAndCheck(
                    "window.setTimeout(function() { invoke_static_method ('[debugger-test] HiddenSequencePointTest:StepOverHiddenSP'); }, 1);",
                    "dotnet://debugger-test.dll/debugger-test.cs", 546, 4,
                    "StepOverHiddenSP2");
            });
        }
```

Issue: debugger never stops

What is the intended behavior with breakpoint on a hidden line? I tried VS/.net, and that automatically moves the the bp to the next "available" line.

Related code: https://gist.github.com/radical/69a593b9fac153937d60b2053559d596

**Comment by lewing** [comment]
Doesn't this check if you can set a breakpoint by line on a breakpoint we never return as available though?

**Comment by radical** [comment]
You are correct! I'll remove the test.

**Comment by lewing** [comment]
Have we tested to see what js does in a case like this?

**Comment by radical** [comment]
Js has hidden bps too? Or I guess, I could try with um lines that you can set bp on?

**Comment by lewing** [comment]
yeah I meant test what happens when you set it on an line that isn't from getpossiblebreakpoints (impossible breakpoint?)
