### ISSUE TITLE
Runtime test build command gives incorrect command for running the tests:

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#42702]
If you build the tests in /src/tests with ./build.sh, it outputs a command to run the tests, for example:

```
 ./tests/runtest.sh <arguments>
```

The script has been renamed to run, so it should look like:

```
./run.sh <arguments>
```

This is potentially confusing to any one trying to run the tests locally. It does not in any way effect the tests when running in CI.

**Comment by ericstj** [comment]
@trylek this looks related to https://github.com/dotnet/runtime/commit/3f30ac6bfb3c6bc6989ea450b8699709407ffee1  Can you have a look?

**Comment by trylek** [comment]
Sure, will fix, thanks for the heads-up.
