### ISSUE TITLE
Test failure: Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions(x: 0, y: 4294967295, type: LessThanOrEqual, result: True, shouldSucceedChecked: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42719]
failed in job:[runtime-coreclr libraries-jitstress 20200924.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=828808&view=ms.vss-test-web.build-test-results-tab&runId=26424988&resultId=108177&paneView=debug)

net5.0-Linux-Release-x64-CoreCLR_checked-jitminopts-Ubuntu.1804.Amd64.Open

Error message
~~~
Assert.Equal() Failure
Expected: True
Actual:   False


Stack trace
   at Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions(Object x, Object y, ExpressionType type, Object result, Boolean shouldSucceedChecked) in /_/src/libraries/Microsoft.CSharp/tests/IntegerBinaryOperationTests.cs:line 504
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstress 20201011.1](https://dev.azure.com/dnceng/public/_build/results?buildId=848293&view=ms.vss-test-web.build-test-results-tab&runId=27025598&resultId=139662&paneView=debug)

failed test: Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions(x: 0, y: 4294967295, type: LessThanOrEqual, result: True, shouldSucceedChecked: True)

net6.0-Windows_NT-Release-x64-CoreCLR_checked-jitminopts-Windows.10.Amd64.Open
net6.0-Windows_NT-Release-x86-CoreCLR_checked-jitminopts-Windows.10.Amd64.Open
net6.0-Linux-Release-x64-CoreCLR_checked-jitminopts-Ubuntu.1804.Amd64.Open


Error message
~~~
Assert.Equal() Failure
Expected: True
Actual:   False

Stack trace
   at Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions(Object x, Object y, ExpressionType type, Object result, Boolean shouldSucceedChecked) in /_/src/libraries/Microsoft.CSharp/tests/IntegerBinaryOperationTests.cs:line 504
~~~

**Comment by wfurt** [comment]
I see ~ 100 failures of the test in last 30 days. I think we should disable it unless we can fix it quickly.

**Comment by cston** [comment]
To repro locally:
```
set COMPlus_JITMinOpts=1
set complus_TieredCompilation=0
dotnet build /t:Test
    /p:XunitMethodName=Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions
```

When compiling `(0u <= 4294967295u)`, `LambdaCompiler.EmitBinaryExpression()` generates the following IL:
```
ldc.i4.0
ldc.i4.m1
cgt.un
ldc.i4.0
ceq
```

It appears the result of executing that IL is `false` rather than `true` with the environment variables set.

**Comment by sandreenko** [comment]
Thanks @cston for the investigation, with his repro I can confirm that it is a codegen issue.

**Comment by sandreenko** [comment]
a small repro that does not require libraries:
```

  .method public static int32 main() cil managed
  {
    .entrypoint
    .maxstack  5
    ldc.i4.s   100
    ldc.i4.0
    ldc.i4.m1
    cgt.un
    add  
    ret
  }
```
compile with minopts, the expected results is 100, the actual is 101.

**Comment by sandreenko** [comment]
The test was disabled in https://github.com/sandreenko/runtime/blob/8c7ecdb1fc5d4ccb6ac667d53255373ae32362b8/src/libraries/Microsoft.CSharp/tests/IntegerBinaryOperationTests.cs#L501 , don't forget to enable it when it is fixed.
