### ISSUE TITLE
Activity.Tags.FirstOrDefault gets different values with different packages

### ISSUE THREAD

**Issue by eddynaka** [dotnet/runtime#42713]
### Description

I have the following code:
```csharp
static void Main(string[] args)
        {
            Activity activity = new Activity("test");
            activity.AddTag("tag", "1");
            activity.AddTag("tag", "2");

            Console.WriteLine(GetOperationName(activity, "tag"));
        }

        private static string GetOperationName(Activity activity, string key)
        {
            return activity.Tags.FirstOrDefault(tag => tag.Key == key).Value;
        }
```

### Configuration

Only testing in Windows.
If I use version `4.6.0` the result printed is `2`
If I use version `5.0.0-rc.1.20451.14` the result printed is `1`

### Other information

This isn't impacting us, but it's a change in the behavior that we didn't expect.

cc: @cijothomas

**Comment by tarekgh** [comment]
@eddynaka this is intentional change to match the OpenTelemetry behavior which order the tags as it get added. looks from your comment this is not impacting you but let's know if you have any question.

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by tarekgh** [comment]
Closing it after chatting offline with @eddynaka

**Comment by tarekgh** [comment]
Just FYI, I have created the PR https://github.com/dotnet/docs/issues/20776 to document the breaking change.
