### ISSUE TITLE
Access to System.GC.RetainVM when deploying a Single File Application

### ISSUE THREAD

**Issue by ppekrol** [dotnet/runtime#42720]
Hi,

most of our GC settings values can be read from `GCSettings` class, but due to the lack of `RetainVM` there, we were reading it's value from the `runtimeconfig.json`. We are exploring now deeply the Single File Application feature of .NET 5.0 (RC1) and from obvious reasons this file is not available any longer. Any idea how I can read this value? Can you consider adding it to the `GCSettings` class?

I've found a similar issue opened a few years back: https://github.com/dotnet/runtime/issues/8700

**Comment by Maoni0** [comment]
is there any reason why you need this setting? this was mostly for the 32-bit days.

**Comment by ppekrol** [comment]
Hi,

our software (database) can run on x64, x86 and ARM. We are using this for information reasons. Writing this value to logs and displaying to the user.

**Comment by Maoni0** [comment]
we just added [an API](https://github.com/dotnet/runtime/pull/70514) to get the config values. so I'm closing this. please let me know if this does not suffice!
