### ISSUE TITLE
publish with PublishSingleFile=true +  IncludeNativeLibrariesInSingleFile=true :   part not included in single file

### ISSUE THREAD

**Issue by mshobohm** [dotnet/runtime#42734]
### Description

Tested with 5.0.100-rc.1.20452.10 on Linux-x64
With the attached Test-Program a situation is shown where a (native) part (libMonoPosixHelper.so) of the nuget package Mono.Posix.NETStandard is not integrated in the single File with dotnet publish
[PublishSingleFilePosix.zip](https://github.com/dotnet/runtime/files/5282831/PublishSingleFilePosix.zip)

* Include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small repo to clone, with steps to run it.
dotnet publish

* What behavior are you seeing, and what behavior would you expect?
  -->
libMonoPosixHelper.so is in the publish Folder
Expected: libMonoPosixHelper.so bound together with all other components in the single File with the FileName "PublishSingleFilePosix"

### Regression?

No (if you regard real publishSingleFile as a new Feature)

**Comment by elinor-fung** [comment]
The `IncludeNativeLibrariesInSingleFile` property was renamed to `IncludeNativeLibrariesForSelfExtract`: dotnet/sdk#12363.

Setting `IncludeNativeLibrariesForSelfExtract=true` should include the native libraries now.

**Comment by mshobohm** [comment]
OK. It seems to do what I wanted. Does the rename mean that there is copy like in the old solition with the /tmp File or is it directly loaded ftom the singlefile ?

**Comment by agocke** [comment]
The rename was to emphasize that native libraries are always extracted -- the OS doesn't currently provide functionality to load libraries from memory

**Comment by mshobohm** [comment]
Ok. Thanks.
