### ISSUE TITLE
Cache String.GetHashCode in object header?

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#42739]
I'm just wondering if we can re-use some of the unused parts of Object to cache a pretty expensive `String.GetHashCode` result, e.g. if I am not mistaken, the upper 4 bytes of Object Header are unused on x64. Here is a small prototype: https://github.com/EgorBo/runtime-1/commit/1aff1d8bf9acbd40492d093c1d1c4b37ea66021e

A small benchmark:
```csharp
// case 1: String.GetHashCode
[Benchmark]
public int StringGetHashCode() => "Какая-то строка Привет Мир Hello World".GetHashCode();


// case 2: Dictionary<String, T>
static Dictionary<string, int> _dictionary = new Dictionary<string, int> {{"hello", 42}};
[Benchmark]
public int DictionaryString() => _dictionary["hello"];
```
Results:
```

       |            Method |      Mean |     Error |    StdDev |
       |------------------ |----------:|----------:|----------:|
master | StringGetHashCode | 27.848 ns | 0.0251 ns | 0.0210 ns |
 proto | StringGetHashCode | 0.4698 ns | 0.0015 ns | 0.0012 ns |

master |  DictionaryString |  9.228 ns | 0.0313 ns | 0.0293 ns |
 proto |  DictionaryString | 8.5809 ns | 0.0263 ns | 0.0246 ns |
```
As @tannergooding noted in the Discord channel, `Dictionary<>` already have some hacks around TKey == String and uses a different NonRandomBasedGetHashCode which is not cached in my branch (we can probably get rid of that and rely on the default one but it will make single-use GetHashCodes slower.

Btw, Dictionary [switches back](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L656-L660) to String.GetHashCode for keys if there are too many collisions with the non-random one.

PS: Span, and namely `ReadOnlySpan<char>` has a 4bytes gap in the actual layout (between pointer and length) and we can fill that with GetHashCode result as well 😄 

/cc @tannergooding @jkotas

**Comment by tannergooding** [comment]
What about reusing the `SyncBlock` dword that caches the `object.GetHashCode`?

**Comment by EgorBo** [comment]
> What about reusing the `SyncBlock` dword that caches the `object.GetHashCode`?

Will this work?:
```csharp
string str = 42.ToString();
int z1 = str.GetHashCode(); // returns some 32bit value (sets most bits) and caches it into syncblock
lock (str)
{
    int z2 = str.GetHashCode();
    bool r = z1 == z2; 
}
```

**Comment by jkotas** [comment]
@Maoni0 has plans to leverage the unused dword in the object header to make GC better.

**Comment by danmosemsft** [comment]
>  `ReadOnlySpan<char>` has a 4bytes gap in the actual layout (between pointer and length) and we can fill that with GetHashCode result as well 

`ReadOnlySpan<char>` may be over a mutable buffer, right?

**Comment by jkotas** [comment]
> A small benchmark

This benchmark is not a good proxy for typical Dictionary use. The typical use will use a new string as a key each time and the extra cycles spent on caching will make those cases run slower.

**Comment by danmosemsft** [comment]
Another idea (if this is a problem worth solving/it is sufficiently beneficial) -- strings over X in length (presumably most costly to hash) could pad (eg at the end) 4 bytes for their hashcode.

**Comment by jkotas** [comment]
I think it is safe to close this. I do not see any way this can fly well.

**Comment by EgorBo** [comment]
> ReadOnlySpan<char> may be over a mutable buffer, right?

Ah, correct but I guess it's possible to find out whether the buffer is a string or not?

> I think it is safe to close this. I do not see any way this can fly well.

Ok makes sense then. Btw, JVM does cache hashcodes for strings 🙂

**Comment by EgorBo** [comment]
> The typical use will use a new string as a key each time and the extra cycles spent on caching will make those cases run slower.

We could do it at least for literals/interned strings. With help of JIT, e.g.

```
if (JitHelpers.IsConstString(input))
{
    // cache logic
}
```

**Comment by tannergooding** [comment]
> This benchmark is not a good proxy for typical Dictionary use. The typical use will use a new string as a key each time and the extra cycles spent on caching will make those cases run slowe

For what its worth, I expect it would minimally impact adding a new dictionary entry (as it just requires checking if a hashcode is cached) but could significantly speed up getting or modifying an existing entry, which is likely just as common for some scenarios.

So it may be worth checking for how often something like Kestrel does one vs the other to determine potential impact vs potential gain.
