### ISSUE TITLE
How memory mapping files are accessed as a variable?If not, is it possible?

### ISSUE THREAD

**Issue by maikebing** [dotnet/runtime#42736]
C code 
```C
foo*  __filemap = mmap(NULL, filesizemaybe, PROT_READ, MAP_SHARED | MAP_LOCKED, _FD, 0);
printf(foo[0].a);
```

C#  now 
```csharp
   var mmf = MemoryMappedFile.CreateFromFile(fi.FullName, FileMode.Open, "MyFile");
                        var cva1 = mmf.CreateViewAccessor(0, rawsize);

                        var cva = mmf.CreateViewAccessor(rawsize, fi.Length - rawsize);
                        arys = new blackdic[head.Total];
                        cva.ReadArray<blackdic>(0, arys, 0, head.Total);
                        cva.Dispose();
                        mmf.Dispose();
```
Memory needs to be allocated.

C#  hope 
```csharp
   var mmf = MemoryMappedFile.CreateFromFile(fi.FullName, FileMode.Open, "MyFile");
var cva = mmf.CreateViewAccessor(0, rawsize);
blackdic[] foo=  cva.Map<blackdic>(0, arys, 0, head.Total);

```

This way we don't need to allocate extra memory, so we can use the files on the disk as memory pointers.

**Comment by huoyaoyuan** [comment]
#37227

**Comment by stephentoub** [comment]
You can get at the raw pointer if that's what you want to use:
```C#
var mmf = MemoryMappedFile.CreateFromFile(...);
var va = mmf.CreateViewAccessor();
byte* ptr = null;
va.SafeMemoryMappedViewHandle.AcquirePointer(ref ptr);
try
{
    ulong length = va.SafeMemoryMappedViewHandle.ByteLength;
    ... // use ptr and length here
}
finally
{
    va.SafeMemoryMappedViewHandle.ReleasePointer();
}
```

**Comment by stephentoub** [comment]
(Also, https://github.com/dotnet/runtime/pull/40842 added a ReadSpan method to go along with ReadArray, but that didn't make it into the .NET 5 release.)

**Comment by stephentoub** [comment]
@maikebing, when you get a chance, please let us know if there's something further you think is needed here or whether this issue can be closed.  Thanks!

**Comment by maikebing** [comment]
My struct  is this code !
```csharp 
  [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
    public struct blackdic
    {
  
        [MarshalAs(UnmanagedType.U4, SizeConst = 4)]
        public uint issuerid;//4
   
        [MarshalAs(UnmanagedType.U2, SizeConst = 2)]
        public ushort cardhead;//2
    
        [MarshalAs(UnmanagedType.U8, SizeConst = 8)]
        public ulong cardid; //8
    
        [MarshalAs(UnmanagedType.U1, SizeConst = 1)]
        public byte cardtype; //1
        [MarshalAs(UnmanagedType.U1, SizeConst = 1)]
        public byte blacktype;//1
    }
```


  blackdic* bdc = null;
 byte* bytex = null;
 cva.SafeMemoryMappedViewHandle.AcquirePointer(ref bytex);
 bdc = (blackdic*)bytex;

The value does not match the actual value.

**Comment by stephentoub** [comment]
> The value does not match the actual value.

What values are you expecting and what values are you getting?

Can you share a standalone small repro that can be run, showing what output your getting and what output you're expecting to get?

**Comment by maikebing** [comment]
@stephentoub  https://github.com/maikebing/runtime42736

**Comment by stephentoub** [comment]
Thanks.  The issue has to do with the offset.  CreateViewAccessor may page-align the offset and size provided, in order to create a page-aligned view.  The Read methods on the returned MemoryMappedViewAccessor then explicitly factor the offset into the calculations (e.g. if you provided an offset of 4050, that might get rounded down internally to 4096 to page-align, and then calls to Read will ensure whatever byte index you provide is incremented by the remaining 4 offset).  But when you ask to acquire the pointer, that's just giving back the raw pointer to the beginning of the page-aligned view, so you need to manually factor in the offset, which is available from the PointerOffset property.  In other words, in your repro, instead of:
```C#
blackdic* _bd_ptr = (blackdic*)ptr;
```
you need to do:
```C#
blackdic* _bd_ptr = (blackdic*)(ptr + cva.PointerOffset);
```
(The docs could probably be improved in this area.)

**Comment by maikebing** [comment]
Thank you for your help, solve my big trouble.

**Comment by stephentoub** [comment]
Actually, I may have steered you wrong / there may be a bug here... I need to look into this more; will do so on Monday. Thanks.

**Comment by stephentoub** [comment]
Nope, I was right, the docs just need to be corrected in a few places. I'll take care of that. Thanks.
