### ISSUE TITLE
How I can set timeout to httpstream which I'm reading?

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/runtime#42733]
Hi there. I am getting an HTTP stream and reading it until it sends some data but I need to figure out how to set a timeout in case of not receiving data from the stream which I'm reading using StreamReader class. This stream sends me data every 50-80 seconds and I wanna handle it when it does not send any data in this timestamp.The sample code is below:
```
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(_configuration.GetSection("COnfig").GetValue<string>("Url"));
                var streamresponse = await client.GetStreamAsync("stream");
                using (StreamReader reader = new StreamReader(streamresponse))
                {
                    //reader.BaseStream.ReadTimeout = 2000;
                    while (true)
                    {
                        string line = await reader.ReadLineAsync();
                        if (!string.IsNullOrWhiteSpace(line))
                        {
                            string decoded = HttpUtility.UrlDecode(line, Encoding.GetEncoding("UTF-8")); ;
                            //some logic
                        }
                    }
                }
```

**Comment by wfurt** [comment]
use Cancellation token and timer..?

**Comment by shahinjabbar** [comment]
I don't wanna set timer for the fixed timestamp. I need to figure out how to make this cancellation using stream, this stream should close itself by timeout property.

**Comment by scalablecory** [comment]
Ideally this would be solved by `StreamReader` adding `CancellationToken` overloads

**Comment by wfurt** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.readasync?view=net-5.0#System_Net_Security_SslStream_ReadAsync_System_Memory_System_Byte__System_Threading_CancellationToken_ ?

**Comment by shahinjabbar** [comment]
Which is the best way to stop reading from stream? Using reader.EndOfStream or checkin value of data from stream if it is null or empty?

**Comment by shahinjabbar** [comment]
```
 using (StreamReader reader = new StreamReader(streamresponse))
                {
                    //reader.BaseStream.ReadTimeout = 2000;
                    while (true)
                    {
                        string line = await reader.ReadLineAsync();
                        if (!string.IsNullOrWhiteSpace(line))
                        {
                            string decoded = HttpUtility.UrlDecode(line, Encoding.GetEncoding("UTF-8")); ;
                            string actualData = Regex.Unescape(decoded);
                            Log.Information("stream data : " + actualData);
                            if (actualData.Equals("CLOSED"))
                            {
                                Log.Information("STREAM was released");
                                break;
                            }
                            await Process(actualData);
                        }
                    }
                }
```

**Comment by shahinjabbar** [comment]
I am reading http stream and sometimes they just closes stream but code is not breaking while statement and I need to figure out how to break while and stop reading stream after not getting any data from stream inside 2 minutes.

**Comment by MihaZupan** [comment]
See discussion on #74568

As of .NET 7.0, `CancellationToken` overloads of `StreamReader` read methods were introduced (#20824).
You should use a `CancellationTokenSource` to specify the timeout for an individual read operation. #74568 includes examples of how this can be done.
