### ISSUE TITLE
[Proposal] Add range check for "Math.Clamp" 

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/runtime#42757]
Hello,

**Brief description:**

I would be nice when Roslyn can check min and max range of a value when it is used in `Math.Clamp` and report **CS0652**

**Languages applicable:**
C# 9.0, .NET 3.1

**Code example that the analyzer should report:**
```cs
/// <summary>
/// Save convert a signed integer value to a unsigned integer value
/// </summary>
/// <param name="value">The singed integer value to convert</param>
/// <returns>A singed integer value or <see cref="uint.MinValue"/> when the given value was lower then <see ref="uint.MinValue"/></returns>
internal static uint SaveConvertToUint(this int value)
{
    return Convert.ToUInt32(Math.Clamp(value, uint.MinValue, uint.MaxValue));
}  
```

**Additional information:**
The analyzer currently report **CS0652** when compare direct
```cs
internal static uint SaveConvertToUint(this int value)
{
    if(value < uint.MinValue)
    {
        return uint.MinValue;
    }

    // CS0652: Comparison to integral constant is useless; the constant is outside the range of type 'int'
    if(value > uint.MaxValue)
    {
        return uint.MaxValue;
    }

    return Convert.ToUInt32(value);
}
```

Any more additional information you would like to add.

**Comment by pgovind** [comment]
@TobiasSekan : Do you have more reasons why you find this useful? I'd be interested in seeing some examples. Also, do you expect a fixer for these cases? If so, I'd like to define all the cases the analyzer/fixer combo should catch first before marking it as up-for-grabs. I think this is a great, focused scenario for someone writing their first roslyn analyzer.

P.S: IIRC, given the Clamp API like this: `Clamp(value, min, max)`, an analyzer that targets this usage would only work for the cases where `min` and `max` are constants.

**Comment by tannergooding** [comment]
Closing. This is much easier to handle now by using `T.Clamp` directly which constrains all three parameters to exactly `T`.

So `uint.Clamp` won't accidentally pick the `ulong` overload and `byte.Clamp` won't accidentally pick or allow inputs over `byte.Min/MaxValue`, etc.
