### ISSUE TITLE
PublishSingleFile results in "System.Exception: Unable to resolve assemblies." in .NET 5.0.0-rc.1 and preview.8 (was working in .NET 5.0.0-preview.7)

### ISSUE THREAD

**Issue by pascallapradebrite4** [dotnet/runtime#42766]
### Description

In .NET 5.0.0-rc.1 and .NET 5.0.0-preview.8, when publishing an F# project (that has references to other projects as part of its solution, one of which is referencing NuGet packages `MySqlConnector` and `SqlProvider`) for a linux-x64 target in `PublishSingleFile` mode, the resulting executable fails to run on the target linux-x64, and outputs the following error when ran (full stacktrace in the "other information" section below):

```
Unhandled exception. System.Exception: Unable to resolve assemblies. One of MySql.Data.dll, MySqlConnector.dll (e.g. from Nuget package MySql.Data) must exist in the paths: 
 /home/vsts/work/1/s/Database
/home/vsts/.nuget/packages/mysqlconnector/1.0.0/lib/net5.0
/home/pascallaprade 
```

The executable is built by a Pipeline on Azure DevOps, and the agent is using the following command:

`/opt/hostedtoolcache/dotnet/dotnet publish /home/vsts/work/1/s/Manager/Manager.fsproj -c Release -r linux-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true /p:IsBuild=true`

(`IsBuild` is a custom parameter that we use with `DefineConstants`, but the minimal reproduction example below doesn't need it and still does not work)

A few weeks ago, we successfully deployed a version, at that time with .NET 5.0.0-preview.7, so I tried pinning the SDK version to the Preview 7 in the Pipeline configuration, and the resulting executable did run successfully on the target machine.

As such, it seems like a change made between Previews 7 and 8 broke the behavior of the linked DLLs, or something like that. It does also break with RC 1.

In other words, the observed behavior is that the executable is not able to run because it is failing to load the assemblies. The expected behavior is for the executable to work out of the box on the target machine, as it did in Preview 7.

Minimal reproduction steps (you'll need to have a MySQL or MariaDB server running with this example, on both your build machine and target machine; I tried reproducing it with a simpler dependency, such as log4net, but the build worked as expected. Using the same dependencies that are failing in our real application did however succeed in reproducing the bug):

1. `dotnet new console --language=f# -o UnableToResolveAssemblies`
2. In the project folder, `dotnet add package MySqlConnector` and `dotnet add package SqlProvider`
3. Replace the contents of `Program.fs` with the following:
```fsharp
open FSharp.Data.Sql

[<Literal>]
let ConnectionString =
    // Change Database, User and Password for compile-time type safety checks.
    "Server=localhost;Database=database;User=user;Password=password;"

type internal DbProvider =
    SqlDataProvider<
      Common.DatabaseProviderTypes.MYSQL,
      ConnectionString
    >

let getConnectionString =
    sprintf "Server=%s;Database=%s;User=%s;Password=%s"

[<EntryPoint>]
let main argv =
    match argv with
    | [|server; database; user; password|] ->
        // Provide the server, database, user and password at runtime if it differs
        // between your build machine and your target machine.
        DbProvider.GetDataContext (getConnectionString server database user password)
        |> ignore
    | _ ->
        DbProvider.GetDataContext ()
        |> ignore
    0

```
4. Publish the project: `dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true`
5. Run the executable on a linux-x64 machine that does not have the .NET runtime installed nor any trace of DLLs or NuGet packages on the system. In theory, it should output a stacktrace instead of nothing.

Notes about the minimal reproduction example:

* Tried building the executable from my development computer (macOS Catalina 10.15.6) and from a standard Azure DevOps provided agent (Ubuntu 18.04), and both lead to the executable working in Preview 7 and not working in Preview 8 and RC 1.
* Tried with a simpler project not requiring a database, but could not reproduce. This might indicate that the issue only happens with certain types of dependencies, but I'm not sure what would be the difference between them.
* Used the following executables on my computer to test between versions of the SDK (on the build agent, this was done through pipeline configuration):
  * Preview 7 : dotnet /usr/local/share/dotnet/sdk/5.0.100-preview.7.20366.6/dotnet.dll
  * Preview 8 : dotnet /usr/local/share/dotnet/sdk/5.0.100-preview.8.20417.9/dotnet.dll
  * RC 1 : dotnet /usr/local/share/dotnet/sdk/5.0.100-rc.1.20452.10/dotnet.dll
* The target machine in our case is on Ubuntu 20.04, and has no trace of .NET other than executables tested (and also currently running).

### Configuration

* Using F# 5.0-preview
* Using .NET SDK version 5.0.100-rc.1.20452.10
* Built on Azure DevOps Pipeline (agent is ubuntu-18.04)
* Deployed on Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
* This is our only pipeline and target for this project, so I don't know if it is specific to this configuration. However, it is reproducible with builds made on my development machine as stated.

### Regression?

* Was working on .NET SDK version 5.0.100-preview.7.20366.6
* Changing our pipeline .NET SDK version from `5.0.x` to `5.0.100-preview.7.20366.6` fixed the issue for us, but we are not particularly interested in continuously running an application built with a preview version of the SDK once the final version is out.

### Other information

To give a bit more context about our use case:
* This is our first F# project, after developers suggested we try it out.
* The project is low priority and internal only, so we thought it was a good opportunity to try the language out, and decided to also use .NET 5, since any bugs from the preview and RC versions would have a low impact on our internal users. It would also prepare us for the full release for other products.
* It is also not a frequently changed project (lowering risks even more to try out new technologies), so it took us more than a month between the initial deployment done on Preview 7 and recently on Preview 8 to realize that the regression appeared. We tried again with RC1 and realized that the regression is still here.
* We do not yet need the scaling capabilities of containers and our infrastructure is not ready to support them yet, but we do also want the possibility to run multiple .NET applications on the same environments with different versions, so that upgrades are done per application instead of system-wide. This is why we use the PublishSingleFile and IncludeNativeLibrariesInSingleFile flags.

Here is the full stack trace from the target machine, generated by the RC1 version of our latest DevOps build:

```stacktrace
Unhandled exception. System.Exception: Unable to resolve assemblies. One of MySql.Data.dll, MySqlConnector.dll (e.g. from Nuget package MySql.Data) must exist in the paths: 
 /home/vsts/work/1/s/Database
/home/vsts/.nuget/packages/mysqlconnector/1.0.0/lib/net5.0
/home/pascallaprade 
Details: 
resolutionPath directory doesn't exist:/home/vsts/work/1/s/Database
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at FSharp.Data.Sql.Providers.MySql.createConnection[a](a connectionString)
   at FSharp.Data.Sql.Providers.MySqlProvider.FSharp-Data-Sql-Common-ISqlProvider-CreateConnection(String connectionString)
   at <StartupCode$FSharp-Data-SqlProvider>.$SqlRuntime.DataContext.addCache@37-1.Invoke(Unit unitVar)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at FSharp.Data.Sql.Runtime.SqlDataContext..ctor(String typeName, String connectionString, DatabaseProviderTypes providerType, String resolutionPath, String[] referencedAssemblies, String runtimeAssembly, String owner, CaseSensitivityChange caseSensitivity, String tableNames, String contextSchemaPath, OdbcQuoteCharacter odbcquote, SQLiteLibrary sqliteLibrary, TransactionOptions transactionOptions, FSharpOption`1 commandTimeout, SelectOperations sqlOperationsInSelect)
   at MachineComputerManager.Database.Context.getContext(String connectionString)
   at MachineComputerManager.Database.Database.getContext(ConfigType config)
   at MachineComputerManager.Database.Database.getComputers@20.Invoke(ConfigType x)
   at MachineComputerManager.Commands.GetComputers.doGetComputers(ConfigType config, Parameters parameters)
   at MachineComputerManager.Commands.GetComputers.exec[a](ConfigType config, FSharpMap`2 args)
   at Program.commands@16-2.Invoke(ConfigType config, FSharpMap`2 args)
   at Program.main(String[] argv)
Aborted (core dumped)
```

**Comment by agocke** [comment]
@vitek-karas @elinor-fung @mateoatr Could we also try this repro with the compat switch?

**Comment by agocke** [comment]
@pascallapradebrite4 It looks like the library you're using looks at the `Assembly.Location` of the calling assembly: https://github.com/fsprojects/SQLProvider/blob/e9549c7fc6b7a0bfb8dd2815554221138f6c1d78/src/SQLProvider/Utils.fs#L407-L414

That won't work in proper single-file, as assemblies are loaded from memory. I'd recommend you open an issue with the library author.

However, there is a compat switch which should be available for GA, which goes back to the old extraction behavior: `IncludeAllContentForSelfExtract`. That could be a viable workaround until the library is fixed for single file.

**Comment by pascallapradebrite4** [comment]
@agocke Thank you for your support! I'll open an issue in the library then, and I'll be using the `IncludeAllContentForSelfExtract` switch when available. Thanks again!
