### ISSUE TITLE
C99 "snprintf" instead of _snprintf all over the place for GCC, Clang and VCR 2015

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#4278]
VC 2015 has (finally) brought support for standard C99 `snprintf`. There are several instances of `_snprintf` in this repo.

There is one difference between non-std `_snprintf` and std `snprintf` that the former does not add null-terminator at the end.

Instead of choosing `_snprintf` as a fallback, the correct solution is to have something what has been done in libuv repo:

[https://github.com/libuv/libuv/blob/../test/task.h#L187-L209](https://github.com/libuv/libuv/blob/9e7568ea7b2b9375be6563c9fb5e795c9753287e/test/task.h#L187-L209) union https://github.com/libuv/libuv/pull/369/files:

``` c
/* Define inline for MSVC<2015 */ 
# if defined(_MSC_VER) && _MSC_VER < 1900 
#  define inline __inline 
# endif 

# if defined(_MSC_VER) && _MSC_VER < 1900 
/* Emulate snprintf() on MSVC<2015, _snprintf() doesn't zero-terminate the buffer 
 * on overflow... 
 */ 
inline int snprintf(char* buf, size_t len, const char* fmt, ...) { 
va_list ap; 
int n; 


va_start(ap, fmt); 
n = _vsprintf_p(buf, len, fmt, ap); 
va_end(ap); 

/* It's a sad fact of life that no one ever checks the return value of 
 * snprintf(). Zero-terminating the buffer hopefully reduces the risk 
 * of gaping security holes. 
 */ 
if (n < 0) 
  if (len > 0) 
    buf[0] = '\0'; 


  return n; 
} 
# endif 
```

We can probably define a proper equivalent (with null-terminator) fallback for VC < 2015 once and then use it everywhere else.

Inviting @janvorli

**Comment by AaronRobinsonMSFT** [comment]
We now use platform `*printf` APIs in all scenarios.

**Comment by adityamandaleeka** [comment]
end of an era 😆
