### ISSUE TITLE
Failure in paltest_waitformultipleobjectsex_test2 on Linux ARM64

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#42781]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=831244&view=logs&jobId=22eeac8c-742e-5aad-c88c-3907a882a5f0&j=f8732ab7-670a-537e-93c0-6fdc525f2002&t=19edcf95-bb1e-5c92-d2a4-c5cf10f389c5

Platform: Linux ARM64

Sadly there's not much diagnostic information in the log

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42386-head-9c94ffd125274dd98a/PALTests/console.d65f912b.log?sv=2019-07-07&se=2020-10-16T01%3A04%3A57Z&sr=c&sp=rl&sig=jhFMyHFdmq%2FWjtzFt6U6nd9B9RxnrfhV8Nqw0FLx13I%3D

which just shows something like:

<pre>
................Expected thread to wait for 1000 ms (and get interrupted).
Interrupt Time: 500 ms,  ThreadWaitDelta 499

FAILED: threading/WaitForMultipleObjectsEx/test2/paltest_waitformultipleobjectsex_test2. Exit code: 1
</pre>

/cc: @davidwrighton, @janvorli, @AntonLapounov

**Comment by janvorli** [comment]
Dup of #6327
