### ISSUE TITLE
Browser test assemblies are throwing locally but are excluded from CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#42807]
While going over some P2P references in test assemblies I noticed that some test assemblies have a Browser tfm but exclude themselves from running in CI: https://github.com/dotnet/runtime/blob/4c3d75927db24f745c3180cc3abedff3f37c6abd/src/libraries/System.Net.Security/tests/UnitTests/System.Net.Security.Unit.Tests.csproj#L15

These are throwing locally when trying to run the tests. Is this expected?

cc @safern @Anipik

**Comment by akoeplinger** [comment]
As far as I know the guidance we got was that the test .csproj should have the same TFMs as the src .csproj.

I'm wondering why it throws for you though, as far as I can see all the test .cs source files are under `<ItemGroup Condition="'$(TargetsBrowser)' != 'true'">` and we have a `[SkipOnMono("System.Net.Security is not supported on Browser", TestPlatforms.Browser)]` in the AssemblyInfo.cs

**Comment by ViktorHofer** [comment]
> https://github.com/dotnet/arcade/issues?q=is%3Aopen+is%3Aissue+label%3Anative-toolset-bootstrapping

The same tfms except for platform not supported throwing assemblies. Those don't need to be tested and we don't need to build a test assembly for it.

**Comment by akoeplinger** [comment]
Ok.

**Comment by ViktorHofer** [comment]
Closing as I didn't see this again.
