### ISSUE TITLE
C# System.Net.Http.StringContent() gives exception during the run time

### ISSUE THREAD

**Issue by manojjayaraman1166** [dotnet/runtime#42810]
We have the following piece of code where we use constructor of System.Net.Http.StringContent(). This following code can be executed by multiple threads in my application.

```
public static HttpContent GetContent(this object model)
    {
        var body = JsonConvert.SerializeObject(model, Formatting.Indented, new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore });           
        var content = new StringContent(body, Encoding.UTF8, "application/json");
        content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
        return content;
    }
```
We are getting Null reference exception in the execution of above code. "body" param is just a string variable which we confirmed it to be not null. The following is the stack trace:

> System.NullReferenceException : Object reference not set to an instance of an object. at System.Text.Encoding.get_WebName() at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType) at AW.Api.Client.Extensions.HttpExtensions.GetContent(Object model, String contentType)

StringContent() is trying to access the WebName property of Encoding.cs.  On seeing the library code of Encoding.cs, https://referencesource.microsoft.com/#mscorlib/system/text/encoding.cs,00987bab2ca262fa ,
we can notice that while accessing the property "WebName", a private field "dataItem" is being referenced after a null-check. Can anyone please help in understanding what might go wrong here? Is there a possibility of race condition where "dataItem" is being referenced by one thread while other thread setting it to null.

Configuration:
This issue occurred only once in our internal CI/CD pipeline.  The configuration for the machine:
OS - Windows 2019 Core. 
.NET framework - v4.8

**Comment by wfurt** [comment]
Can you reproduce this on .NET Core? If not, this is not right place. Follow https://dotnet.microsoft.com/platform/support for .NET framework only issues.
