### ISSUE TITLE
IOptionsMonitor<T> does not detect changes when using "Bind"

### ISSUE THREAD

**Issue by ozziepeeps** [dotnet/runtime#42838]
### Describe the bug
`IOptionsMonitor<T>` does not pick up changes when using the `Bind` syntax, however it works as expected when using the `GetSection` syntax.

### To Reproduce
Check out my repro that demonstrates the issue here: https://github.com/ozziepeeps/IOptionsMonitorBug. Description of the bug and actual/expected behavior is in the README.md.

- ASP.NET Core version: 
3.1.x

- Output of `dotnet --info`:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 - 16.7.4 on Windows 10

**Comment by davidfowl** [comment]
This is by design because the overload that takes the configuration object can use it to subscribe to changes. As far as it's concerned, you gave it a method that binds configuration once. The overload that doesn't take configuration doesn't know how to update the options when configuration changes.

**Comment by ozziepeeps** [comment]
Thank you for the feedback. I couldn’t find this expected behavior documented anywhere obvious. Perhaps I missed it? If not might I suggest that the documentation be updated to make it clear that `Bind` won’t receive updates as it might mean a future developer doesn’t lose hours trying to diagnose.

**Comment by maryamariyan** [comment]
#### Summary

Further information:
- [x] apisof.net page shows APIs available for [OptionsConfigurationServiceCollectionExtensions ](https://apisof.net/catalog/Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions) 
- [x] dotnet/dotnet-api-docs is the repo containing doc content for [OptionsConfigurationServiceCollectionExtensions](https://github.com/dotnet/dotnet-api-docs/blob/9387360ffccf562a68cc862ad2cde4f2be668b6b/xml/Microsoft.Extensions.DependencyInjection/OptionsConfigurationServiceCollectionExtensions.xml#L62-L67)
- [x] Below shows snippet of the docs on the two APIs you used in your sample code:

```c#
public static class OptionsConfigurationServiceCollectionExtensions
    {
        //
        // Summary:
        //     Registers a configuration instance which TOptions will bind against.
        //
        // Parameters:
        //   services:
        //     The Microsoft.Extensions.DependencyInjection.IServiceCollection to add the services
        //     to.
        //
        //   config:
        //     The configuration being bound.
        //
        // Type parameters:
        //   TOptions:
        //     The type of options being configured.
        //
        // Returns:
        //     The Microsoft.Extensions.DependencyInjection.IServiceCollection so that additional
        //     calls can be chained.
        public static IServiceCollection Configure<TOptions>(this IServiceCollection services, IConfiguration config) where TOptions : class;
```

for something like:
```c#
servicesConfigure<TOption>(this.configuration.GetSection(nameof(TOptions)))
```
which detects changes correctly, but 

```c#
public static class OptionsConfigurationServiceCollectionExtensions
    {
        //
        // Summary:
        //     Registers an action used to configure a particular type of options. Note: These
        //     are run before all Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.PostConfigure``1(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.Action{``0}).
        //
        // Parameters:
        //   services:
        //     The Microsoft.Extensions.DependencyInjection.IServiceCollection to add the services
        //     to.
        //
        //   configureOptions:
        //     The action used to configure the options.
        //
        // Type parameters:
        //   TOptions:
        //     The options type to be configured.
        //
        // Returns:
        //     The Microsoft.Extensions.DependencyInjection.IServiceCollection so that additional
        //     calls can be chained.
        public static IServiceCollection Configure<TOptions>(this IServiceCollection services, Action<TOptions> configureOptions) where TOptions : class;
```
for
```c#
services.Configure<TOption>(o => configuration.Bind(nameof(TOptions), o))
```
that doesn't detect changes.

**Comment by ozziepeeps** [comment]
Hi. Whilst the fix looks good in making it clear which method will updates the options when configuration changes, perhaps it would also be beneficial to document the other method to say it **will not** update options?

**Comment by maryamariyan** [comment]
> Whilst the fix looks good in making it clear which method will update the options when configuration changes, perhaps it would also be beneficial to document the other method to say it will not update options?

That makes sense. Would you like to open the PR to address this?

**Comment by ozziepeeps** [comment]
> That makes sense. Would you like to open the PR to address this?

Yes, done: https://github.com/dotnet/dotnet-api-docs/pull/5010
