### ISSUE TITLE
API proposal: Mask testing for IPAddress

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#42845]
## Background and Motivation

From #42840 
A weird workaround is used for mask testing. Masking should be exposed as a direct concept for ip addresses.

## Proposed API

```diff
namespace System.Net
{
    public class IPAddress
    {
+        public bool IsMask(IPAddress address, int maskLength);
    }
}
```

## Usage Examples

``` C#
var mask = IPAddress.Parse("192.168.0.0");
var address = IPAddress.Parse("192.168.1.1");
Assert.True(mask.IsMask(address, 16));
```

## Alternative Designs

Expose a separated `IPAddressMask` type? Then mask length doesn't needed to be passed in every call.

## Risks

Is storing masks violating the `IPAddress` type? If so, an `IPAddressMask` type should be appropriate.

**Comment by scalablecory** [comment]
Would this check if an `IPAddress` is exactly equal to a mask, or only that the IP address is within the mask?

**Comment by wfurt** [comment]
note that mask operations are obsolete in IPv6. There was similar CIDR proposal which did not fly.

**Comment by karelz** [comment]
Given that this is IPv4 only feature and the world is moving towards IPv6, I wonder if this makes sense at all ... should we just close it as Won't Fix?

**Comment by alrz** [comment]
Does a `IPAddressRange` API fits into this bucket? There's https://github.com/jsakamoto/ipaddressrange with horrendous impl that I wouldn't want to use.

**Comment by MihaZupan** [comment]
Have you considered contributing a better implementation that would be acceptable?

**Comment by alrz** [comment]
That's a complete rewrite. I did implement a simple one just to use `Contains` - no parsing or validation though.

**Comment by antonfirsov** [comment]
Unless there are valid concerns, I recommend to close this in favor of #79946.

**Comment by huoyaoyuan** [comment]
Agreed to close in favor of #79946.
