### ISSUE TITLE
API proposal: Expose bitwise operations as operators in BitArray

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#42843]
## Background and Motivation

From https://github.com/dotnet/runtime/issues/42840#issuecomment-700719886 :
`BitArray` has members like `And` `Or` `Not`, but they are in method form, not operator form.

## Proposed API

```diff
namespace System.Collections
{
    public class BitArray
    {
        // Existing
        public BitArray And(BitArray value);
        public BitArray Or(BitArray value);
        public BitArray Not();
        public BitArray LeftShift(int count);
        public BitArray RightShift(int count);
        // new
+        public static BitArray operator &(BitArray left, BitArray right);
+        public static BitArray operator |(BitArray left, BitArray right);
+        public static BitArray operator ~(BitArray array);
+        public static BitArray operator <<(BitArray array, int count);
+        public static BitArray operator >>(BitArray array, int count);
    }
}
```

## Alternative Designs

What about `null` behaviors?
Many operators don't throw for `null`, but `BitArray` does.
Besides, `BitArray` operators have a relatively high chance to throw (length mismatch). Is this considered in the original API design?
Do we need static named methods too?

## Risks

I can't see.

**Comment by jkotas** [comment]
Do the operators create a new instance of the `BitArray`?

If yes, they will be much less efficient compared to the methods.
If not, they will have non-intuitive behavior.

**Comment by huoyaoyuan** [comment]
> Do the operators create a new instance of the `BitArray`?

The existing methods returns `this`. It's really not intuitive until I read the implementation.

**Comment by eiriktsarpalis** [comment]
Given the concerns raised by @jkotas, I think it is unlikely such a proposal would be accepted. I'm going to close this issue.
