### ISSUE TITLE
Exception in callback from native code crushes the whole application on Ubuntu 20.04

### ISSUE THREAD

**Issue by EgorRudakov2** [dotnet/runtime#42842]
### Description

When code in the callback called by native code throws exception the application crushes with message like this:
```
Unhandled exception. System.Exception: Callback failed
   at ConsoleApp.Program.Callback() in /home/user/ConsoleApp/Program.cs:line 15
   at ConsoleApp.Program.DoWithCallback(IntPtr callbackPointer)
   at ConsoleApp.Program.Main(String[] args) in /home/user/ConsoleApp/Program.cs:line 24
Fatal error. Internal CLR error. (0x80131506)
   at ConsoleApp.Program.DoWithCallback(IntPtr)
   at ConsoleApp.Program.DoWithCallback(IntPtr)
   at ConsoleApp.Program.Main(System.String[])
```

This exception cant by handled by any exception handlers.

#### Steps to reproduce

You can use attached sample to reproduce the problem.
[ConsoleApp.zip](https://github.com/dotnet/runtime/files/5299441/ConsoleApp.zip)

1. Run buildNativeLinux.sh to build native library (on Windows build WindowNative\dll.vcxproj project instead).
2. Build and run ConsoleApp.csproj
3. Application will crush with message that you can see above. (on Windows it's simply catch the exception and print "Exception: {e.ToString()}"

#### Expected behavior
Exception should pass through native code and then should by caught by exception handler. It works like that on Windows in both .net core and .net framework.

### Configuration
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.809 [/usr/share/dotnet/sdk]
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

### Regression?

It works on Windows with the same dotnet version (3.1.8).

**Comment by stephentoub** [comment]
https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/exceptions-interoperability.md

**Comment by EgorRudakov2** [comment]
@stephentoub Is the CLR exception turn into unmanaged exception when it's thrown in callback from unmanaged code?
There is no a "real" unmanaged exceptions is this sample like c++ or COM exception.

**Comment by stephentoub** [comment]
There's no guaranteed behavior on Unix for a managed exception being thrown to a native caller; exceptions are not allowed to cross the runtime boundary.

**Comment by stephentoub** [comment]
You're welcome.  Sorry it's not the answer you were looking for.

**Comment by jkotas** [comment]
I have opened https://github.com/dotnet/runtime/issues/42873 on improving the error message. The error message should not have "Internal CLR error." in it.

**Comment by EgorRudakov2** [comment]
@stephentoub Just curious. Is there any technical limitation for CLR to just pass through unmanaged frames until managed frame found? I understand that impossible to handle managed exception or perform some cleanup in unmanaged code in that case, but problems that this can make (memory/resource leaks) dependent from unmanaged library API design.

**Comment by janvorli** [comment]
@EgorRudakov2 technically, it can be relatively easily done that way. But besides potential memory and resources leaks, it can also cause deadlocks in case the native code has a lock around the call to managed stuff.

**Comment by EgorRudakov2** [comment]
@janvorli Yes, I forgot about synchronizations issues. But we can face all this problems on Windows if unmanaged library doesn't support exception. So I can't see any difference between "Windows unmanaged library that doesn't support exceptions" and "Linux unmanaged library that doesn't support exceptions" except that is there no way to support exceptions in unmanaged library on Linux. Why we have different behavior on Linux and Windows then?
Also I think that crushing application in this case is overkill since CLR itself can't make assumptions about what problems unwinding of unmanaged stack creates (did it cause resource leaks and deadlock or not? It's library and API specific). 

For example, I have faced this issue when trying to wrap libjpeg API. Libjepg requires stack unwinding when encounters error (in samples setjmp/longjmp function are used, but since CLR doesn't support them exception was only option)

**Comment by janvorli** [comment]
The Windows is different because of the system wide standard structured exception handling (SEH) that serves as an underlying mechanism for both C++ and .NET exception handling. So the exception handling can properly propagate exceptions coming from C# callback through the C++ caller and back to the C# caller. Even C code can handle these exception using the __try / __except. 
On Unix, there is no system wide exception handling mechanism, so the only option we would have is to skip the native frames. 
So the decision was made to keep the exception propagation enabled for Windows for backwards compatibility reasons, but fail with unhandled exception on Unix. And discourage its use on Windows.
The thinking was that all managed exceptions in managed callbacks invoked by non-.NET code should be caught by the managed implementation of the callback before returning back to the native caller. The information on the error state can then be propagated back to the native callee as some kind of error value (error code, structure with exception details, ...).
