### ISSUE TITLE
BigInteger losing precision (byte arrays)

### ISSUE THREAD

**Issue by agowa338** [dotnet/runtime#42840]
### Description

Biginteger loses precision when working with byte arrays.
`([bigint](([System.Net.IPAddress]"::ffff:169.254.1.1").GetAddressBytes()) -band [bigint](([System.Net.IPAddress]"::ffff:169.254.0.0").GetAddressBytes())).ToByteArray() -join " "`
Results in:
`0 0 0 0 0 0 0 0 0 0 255 255 169 254 0`
instead of
`0 0 0 0 0 0 0 0 0 0 255 255 169 254 0 0`

because of:
`([IPAddress]'::ffff:169.254.0.0').GetAddressBytes() -join " "` returns `0 0 0 0 0 0 0 0 0 0 255 255 169 254 0 0`
and `([BigInt]([IPAddress]'::ffff:169.254.0.0').GetAddressBytes()).ToByteArray() -join " "` loses that precision and only returns `0 0 0 0 0 0 0 0 0 0 255 255 169 254 0` instead.

alternatively to "fixing" this precision issue in biginteger, also implementing the binary operators for [System.Byte[]] would work, so that a byte array doesn't need to be converted to a biginteger at all.

### Configuration

dotnet --list-runtimes
Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
On x64 ArchLinux

**Comment by huoyaoyuan** [comment]
Is it losing "leading" zeros. If so, this should be by design. No precision is lost, because it doesn't preserve the whole content of original byte array.

**Comment by agowa338** [comment]
they are not "leading" zeros in that sense, as it is a byte array and not a number.
But because of the conversion they are. The issue is when bigint is used for binary operations on byte arrays, there it loses precision.

Because of that I asked for the alternative fix of allowing binary operations on a byte array.

**Comment by huoyaoyuan** [comment]
> as it is a byte array and not a number.

`BitInteger` never sees byte array. It would, and should treat everything as number.

> allowing binary operations on a byte array

Are you looking for `System.Collections.BitArray`?

**Comment by agowa338** [comment]
No, as that also doesn't support binary operations. It also throws "does not contain a method named 'op_BitwiseAnd'...

**Comment by huoyaoyuan** [comment]
> as that also doesn't support binary operations

It does supports, but in method form, not operator. You can just call the `Add` method on it. I'll file a separated api proposal for it.

> And it cannot be converted back to a bytearray

Well, it does support copy to. You can use it as a workaround.

I understand your usage to do masking on IP addresses. But sorry, `BitInteger` shouldn't be the right class for it.
It's better to directly expose masking related members on `IPAddress` class.
