### ISSUE TITLE
Assembly.CodeBase obsoletion is incomplete

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#42857]
`Assembly.CodeBase` and `Assembly.EscapedCodeBase` were marked obsolete in https://github.com/dotnet/runtime/issues/31127

but this work was incomplete: `AssemblyName.CodeBase` and `AssemblyName.EscapedCodeBase` are not marked. In addition, usages of these obsolete APIs remain in the source code.

We need to carefully audit all the use-sites and either remove them or provide explicit justification for our continued use.

**Comment by agocke** [comment]
cc @ericstj

**Comment by ericstj** [comment]
Looks like @jkotas suggested pragmatic here: https://github.com/dotnet/runtime/issues/31127#issuecomment-658013131

Not sure about AssemblyName WRT original issue.  Cc @jeffhandley @JoshSchreuder

**Comment by agocke** [comment]
At the stage of the release we were in, I think silencing the warnings was reasonable, but I don't think it's a long-term solution.

This issue just tracks finishing that long-term work.

**Comment by jeffhandley** [comment]
I'd be supportive of adding `AssemblyName.CodeBase` and `AssemblyName.EscapedCodeBase` into the same obsoletion diagnostic id in 6.0 and also taking a sweep through our own usage to remove the `#pragma`s.

**Comment by jkotas** [comment]
>  sweep through our own usage to remove the #pragmas

There is one pragma in the shipping code that #42306 is attempting to fix. The remaining pragmas are in method overrides where they are used by design, and in tests.

**Comment by agocke** [comment]
I think we should also take a look at code in other repos, like WPF and ASP.NET

**Comment by jeffhandley** [comment]
@dotnet/area-system-reflection I spent some time looking into this, but I am not familiar enough with how `AssemblyName` is being used to determine the right path forward here.

I moved the issue to 7.0.0, but if time permits before .NET 6 RC1, this would be nice-to-have.

**Comment by buyaa-n** [comment]
I don't see much real usage of `CodeBase` in `source.dot.net`, mostly setting the property from passed `AssemblyName` to the newly created/cloned `AssemblyName`. There is a few usage that try to load the assembly by setting `CodeBase` and seems it was the main functional usage:
```cs
private static Assembly LoadAssembly(string codeBase)
{
    AssemblyName assemblyName = new AssemblyName { CodeBase = assemblyPath };
    return Assembly.Load(assemblyName);
}
``` 
but this code would not work in .Net Core, therefore I think we should obsolete `CodeBase/EscapedCodeBase` and let developers avoid from issues like: [AssemblyName.CodeBase is ignored in LoadFromAssemblyName](https://github.com/dotnet/runtime/issues/59565) while porting their app from .Net framework
