### ISSUE TITLE
Debugger not working on macOS 10.15.x when vmmap hides full path to process modules

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#42888]
Hi! We found that sometimes `vmmap` that you use for `CreateProcessModules` (https://github.com/dotnet/runtime/blob/d52ee3ada3da7093dd0bdc08bf2c816d7dd2a646/src/coreclr/src/pal/src/thread/process.cpp#L2860), can return paths in a "secure" manner, replacing some parts with *.

For example, on my Mac mini with macOS 10.15.7, when I run dotnet from the `~/Downloads` directory, I see paths like:
```__TEXT                        109fc4000-109fd1000        [   52K    52K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/dotnet
__TEXT                        109ff1000-10a044000        [  332K   332K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/libhostfxr.dylib
__TEXT                        10a04c000-10a091000        [  276K   276K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/libhostpolicy.dylib
__TEXT                        10a09a000-10a526000        [ 4656K  4656K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/libcoreclr.dylib
__TEXT                        10a526000-10a527000        [    4K     4K     4K     0K] r--/rwx SM=COW          /Users/USER/*/libcoreclr.dylib
__TEXT                        10a527000-10a5fa000        [  844K   844K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/libcoreclr.dylib
__TEXT                        10abb0000-10add6000        [ 2200K  2200K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/libclrjit.dylib
__TEXT                        10ae6b000-10ae75000        [   40K    40K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/System.Native.dylib
__TEXT                        10ae79000-10ae82000        [   36K    36K     0K     0K] r-x/rwx SM=COW          /Users/USER/*/System.Globalization.Native.dylib
__TEXT                        112036000-1120c8000        [  584K   568K     0K     0K] r-x/r-x SM=COW          /usr/lib/dyld
```

In this case, we get `CORDBG_E_DEBUG_COMPONENT_MISSING` on debugger initialization (https://github.com/dotnet/runtime/blob/d52ee3ada3da7093dd0bdc08bf2c816d7dd2a646/src/coreclr/src/dlls/dbgshim/dbgshim.cpp#L386) because the `dbiPath` is `/Users/USER/*/libmscordbi.dylib` and `LoadLibraryA` cannot find it.

Do you have any objection to using libproc in `CreateProcessModules`? Looks like iterating over regions using this API gives normal paths, so I'm going to submit a PR. cc @mikem8361 @janvorli @jkotas

**Comment by janvorli** [comment]
cc: @dotnet/dotnet-diag
