### ISSUE TITLE
Dynamic SQL generation is not supported against multiple base tables.

### ISSUE THREAD

**Issue by fenngineering** [dotnet/runtime#42889]
### Description

I have ran into an issue with SqlCommandBuilder.

Consider the below snippet:-

`public void TestMethod1()
        {
            var connstr = @"Data Source=(localdb)\ProjectsV13;Initial Catalog=Tester;Integrated Security=True;Connect Timeout=30;";
            var selectStmt = "select [1].ID " +
                                "from dbo.Table1[1] " +
                                "inner join dbo.Table2[2] " +
                                "on [1].Id = [2].Table1ID " +
                                "inner join dbo.Table3[3] " +
                                "on [2].Id = [3].Table2ID " +
                                "inner join dbo.Table4[4] " +
                                "on [3].Id = [4].Table3ID " +
                                "inner join dbo.Table5[5] " +
                                "on [4].Id = [5].Table4ID";

            using (var sqlDataAdapter = new SqlDataAdapter(selectStmt, connstr))
            {
                using (var destSqlDataAdapter = new SqlDataAdapter(selectStmt, connstr))
                {
                    var deleteCMD = new SqlCommandBuilder(sqlDataAdapter);

                    destSqlDataAdapter.DeleteCommand = deleteCMD.GetDeleteCommand();

                    var deleteStmt = destSqlDataAdapter.DeleteCommand.CommandText;
                }
            }
        }`

The code falls over on this line:-
`destSqlDataAdapter.DeleteCommand = deleteCMD.GetDeleteCommand();`

With exception:-
`Dynamic SQL generation is not supported against multiple base tables.`

I have ran this using .net core 3.1 & .net framework 4.7.2, which all gives me the exception.

However when I switch frameworks to 4.5 (using System.Data v4.0.30319.18020), the excepted behaviour works fine, the variable of `deleteStmt` is populated with this:
`DELETE FROM [dbo].[Table1] WHERE (([Id] = @p1))`

Has a bug been introduced into the framework?

If you need anymore information please let me know.

**Comment by Clockwork-Muse** [comment]
I think this qualifies as [by design](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/generating-commands-with-commandbuilders):
> Database views that are created by joining two or more tables together are not considered a single database table. In this instance you cannot use the `DbCommandBuilder` to automatically generate commands; you must specify your commands explicitly. 

Additionally, consider this: your statement lists five tables - which one do you want it to delete rows from?  I have a feeling that 4.5 was just taking the first table... which might not always be what you want!  For instance, if it's a definition table of some sort (country codes, calendar table, etc), generating the statement this way could be dangerous.

**Comment by cheenamalhotra** [comment]
As linked above, this is by design.
