### ISSUE TITLE
Faster fixed-size array allocations

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#42903]
Problem:
```csharp
object AllocateFixedSizeArray() => new byte[100]
```
Current codegen:
```asm
       48B960672AB6FE7F0000 mov      rcx, 0x7FFEB62A6760
       BA64000000           mov      edx, 100
       E83829A65F           call     CORINFO_HELP_NEWARR_1_VC
       B801000000           mov      eax, 1
```
`CORINFO_HELP_NEWARR_1_VC` call will spend some cpu cycles on checking size (sizeof(byte)*count) to be positive and less than some limit despite the fact it's a known constant. So I wonder if we can introduce a new helper without them for such cases? Does it make sense to continue investigating it & measure performance impact or it definitely not worth the effort and can be closed?

Maybe even try to inline some checks to be able to increment the allocation pointer directly or take the slow path etc.

/cc @jkotas

**Comment by jkotas** [comment]
I do not think a new helper for this would be worth the complexity. These extra checks cost close to nothing.

If we really want to reduce the number of instructions required for allocation, we would tech the JIT how to inlinine the whole allocation helper. Again, I do not think it would be worth the complexity.

**Comment by jkotas** [comment]
> These extra checks cost close to nothing.

Especially when you consider the cost of filling the array with something useful that the surrounding code has to pay.

**Comment by EgorBo** [comment]
>  we would tech the JIT how to inlinine the whole allocation helper

Yeah for a fixed-size array the codegen can be just:
```c
var alloc = GetThread()->allocContext->alloc_ptr + arrayTotalSize;
alloc[-1] = arrayMethodTablePtr;
return alloc;
```
and avoid two checks and TotalSize computation (componentSize * length)

but I agree it definitely adds some complexity.

```
new byte[100];
```
takes 7ns to execute, I'd expect the fix to reduce it down to maybe 3-4.

**Comment by AndyAyersMS** [comment]
There is more work needed than that: the free pointer must be updated and the array length initialized.

Exposing these sorts of low-level initializations can sometimes trip up jit optimizations. We've told the jit the array length field is an invariant, but if we expose this detail the jit now also sees a write to that field; this can lead to some cognitive dissonance.
