### ISSUE TITLE
dotnet-sdk snap builds executables dependent on snaps

### ISSUE THREAD

**Issue by cjp256** [dotnet/runtime#42907]
# Reproducer Steps

```
$ /snap/bin/dotnet-sdk.dotnet new console -n apptest
...

$ /snap/bin/dotnet-sdk.dotnet build apptest
...

$ ldd apptest/bin/Debug/netcoreapp3.1/apptest
	linux-vdso.so.1 (0x00007ffe74d3a000)
	libpthread.so.0 => /snap/core18/current/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe7860f5000)
	libdl.so.2 => /snap/core18/current/lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe785ef1000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe785cee000)
	libm.so.6 => /snap/core18/current/lib/x86_64-linux-gnu/libm.so.6 (0x00007fe785950000)
	libgcc_s.so.1 => /snap/core18/current/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe785738000)
	libc.so.6 => /snap/core18/current/lib/x86_64-linux-gnu/libc.so.6 (0x00007fe785345000)
	/snap/core18/current/lib64/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007fe786316000)
```

The above results can be explained with:

(1) Executable rpath:
```
$ patchelf --print-rpath apptest/bin/Debug/netcoreapp3.1/apptest
$ORIGIN/netcoredeps:$ORIGIN/../../../../../../lib/x86_64-linux-gnu:$ORIGIN/../../../../../../usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu
```

(2) Executable interpreter:
```
$ patchelf --print-interpreter apptest/bin/Debug/netcoreapp3.1/apptest
/snap/core18/current/lib64/ld-linux-x86-64.so.2
```

# What's happening

Snapcraft patches the interpreter and rpath on all executables found within `classic` snaps.  However, .NET SDK has a special binary `apphost` which is used as something of a template executable that the builds are derived from.  Snapcraft patches this, and the subsequent builds then expect to be run in the same snap context (which it's not when executing directly, e.g. `$ apptest/bin/Debug/netcoreapp3.1/apptest`).

# Workaround

Snaps can be utilize a `no-patchelf` `build-attribute` to prevent Snapcraft from patching executes.  In this case, the snap must perform its own patching on the necessary executables to ensure proper operation in the classic mode.

For reference, here's a version of the SDK with `no-patchelf`, with manual patching applied on the `dotnet` binary, as seen in `override-pull`:
https://github.com/cjp256/dotnet-sdk-tests/blob/master/dotnet-sdk-31-2004/snap/snapcraft.yaml#L25

There are improvements that could be done on the Snapcraft side to help with an approach like this, but first it's worth determining what the desirable outcome is in this case from the .NET SDK perspective.

**Comment by joperezr** [comment]
Not sure I follow from the description what is the desired behavior instead. Do you mind elaborating on that? Is the current behavior causing any issues? If so, can you describe them?
