### ISSUE TITLE
Add MicrosoftPlatformCryptoProvider to CngProvider

### ISSUE THREAD

**Issue by DavidSimner** [dotnet/runtime#42906]
## Background and Motivation
In Microsoft CNG there are 3 built-in key storage providers.

Today, in `System.Security.Cryptography.CngProvider` there are public static get-only properties so that developers can easily use 2 of these 3 built-in key storage providers.

| CNG key storage provider | .NET `CngProvider` property | Description |
| --- | --- | --- |
| `MS_KEY_STORAGE_PROVIDER` | `MicrosoftSoftwareKeyStorageProvider` | The software key storage provider that is provided by Microsoft |
| `MS_SMART_CARD_KEY_STORAGE_PROVIDER` | `MicrosoftSmartCardKeyStorageProvider` | The smart card key storage provider that is provided by Microsoft |
| `MS_PLATFORM_CRYPTO_PROVIDER` | **this proposal is to add this** | The TPM key storage provider that is provided by Microsoft |

For the docs for these 3 built-in key storage providers see, for example: https://docs.microsoft.com/en-gb/windows/win32/api/ncrypt/nf-ncrypt-ncryptopenstorageprovider#parameters.

This API proposal is to add a property to `CngProvider` for the 3rd built-in key storage provider, so that just like the other 2, there is a .NET property so that developers can easily access it.

## Proposed API
```diff
namespace System.Security.Cryptography
{
    public sealed class CngProvider : IEquatable<CngProvider>
    {
        ...

+       public static CngProvider MicrosoftPlatformCryptoProvider { get; }
        public static CngProvider MicrosoftSmartCardKeyStorageProvider { get; }
        public static CngProvider MicrosoftSoftwareKeyStorageProvider { get; }
    }
}
```

## Usage Examples
``` C#
  using (CngKey key = CngKey.Open("myKey", CngProvider.MicrosoftPlatformCryptoProvider))
  {
      Console.WriteLine(key.KeySize);
  }
```

## Alternative Designs
I don't see any obvious other alternative designs, and I like the proposed diff above, because the 3rd property is added exactly like the 2 existing properties.

## Risks
No risks that I can see.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Security.Cryptography
{
    public partial class CngProvider : IEquatable<CngProvider>
    {
        public static CngProvider MicrosoftPlatformCryptoProvider { get; }
    }
}
```
