### ISSUE TITLE
"The server is not operational" error when using System.DirectoryServices.AccountManagement to get user groups

### ISSUE THREAD

**Issue by djjz** [dotnet/runtime#42914]
# The problem

I'd like to seek advice on an issue that's been bugging my team and I for some time now.

We're using ASP.NET in both .net core and .net framework 4.7.1 flavours to host some internal websites, authenticating our users through ActiveDirectory groups. Recently we have made a discovery that whenever the domain administrators bring one of the controllers down for maintenance our apps randomly generate "The server is not operational" exceptions for a seemingly random subset of users.

After firing up a debugging session we have managed to trace the issue back to the [ADStoreCtx.GetGroupsMemberOf(Principal p)][1] method - depending on the order of global catalogs the first one might be under maintenance, leading to an exception. Example stacktrace below.

```log
Name: "DOMAINSERVER01.company.intranet"
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.ExpandWellKnownDN(WellKnownDN dn)
   at System.DirectoryServices.ActiveDirectory.DomainController.get_Domain()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOf(Principal p)
   at System.DirectoryServices.AccountManagement.Principal.GetGroupsHelper()
   at Redacted.GetRolesForUser(String username)

System.Runtime.InteropServices.COMException The server is not operational.
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
```

None of us are at the team are experts in the field of Active Directory, which begs several questions:

- What is the correct course of action? Have we encountered a bug?
- Is leaving an offline DC in the sites list bad practice?
- Is there a safe way to check whether a DC is operational before selecting it as a source for data?
- Should the `GetGroupsMemberOf` method use a mechanism akin to the DC Locator?

# Reproduction

Given the presence of a DC that's down yet present in the sites list reproduction is as simple as the following:

```csharp
namespace TestAD
{
    using System;
    using System.DirectoryServices.AccountManagement;
    using System.Linq;

    static class Program
    {
        static void Main(string[] args)
        {
            UserPrincipal userPrincipal;
            string username = "IT\\USERNAME";

            var context = new PrincipalContext(
                ContextType.Domain,
                "company.intranet", "DC=company,DC=intranet",
                ContextOptions.ServerBind | ContextOptions.Negotiate
            );

            userPrincipal = UserPrincipal.FindByIdentity(
                context,
                IdentityType.SamAccountName,
                username
            );

            foreach (var r in userPrincipal.GetGroups().Select(g => g.Name))
            {
                Console.WriteLine(r);
            }

            Console.ReadKey();
        }
    }
}
```

# Mitigation

One of the solutions tried by our domain administrators was moving the DC undergoing maintenance to a temporary _"quarantine site"_ in the AD - which solved the root cause, removing the faulty DC from the forest listing and allowing our apps to continue unhindered. There is, however, significant pressure on my team to treat the situation as a bug inside our apps and/or the runtime, leading to this issue report.
Thanks in advance!

[1]: https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs#L1202

**Comment by joperezr** [comment]
@tquerec do you mind taking a look and trying to reply to these questions:
>What is the correct course of action? Have we encountered a bug?
Is leaving an offline DC in the sites list bad practice?
Is there a safe way to check whether a DC is operational before selecting it as a source for data?
Should the GetGroupsMemberOf method use a mechanism akin to the DC Locator?

**Comment by RvdHorst1980** [comment]
Hi,
What is the state about this issue? Because we also run in the same issue and we don't know how to solve this.

**Comment by djjz** [comment]
> Hi, What is the state about this issue? Because we also run in the same issue and we don't know how to solve this.

Hi,
Think this particular issue got stuck in the backlogs..

No worries though, I was able to remediate the issue:
After seeking help through official Microsoft support I eventually ended up implementing a manual AD query with help of the `System.DirectoryServices.Protocols` namespace. While I wasn't able to give the solution an explicit test it seems to hold up well.

**Comment by danmoseley** [comment]
@djjz thanks for the update. Is there any of your solution that you could paste here, with identifiers etc removed? Might help someone else.

**Comment by senthilray** [comment]
@djjz - we are facing the same issue. Can you share the sample code as @danmoseley mentioned that will be helpful to solve the issue? Thanks in advance

**Comment by djjz** [comment]
Sure thing, here's the core of my solution which demonstrates the alternate way of querying for user groups. The resulting set is nowhere near as neat as the ones you'd come to expect from the principal objects attached to your request context, but that's perfectly workable.

```csharp
namespace Sample
{
    using System;
    using System.Collections.Generic;
    using System.DirectoryServices.Protocols;

    /// <summary>
    /// Microsoft's code sample: finding groups with no nonoperational DC issues
    /// </summary>
    internal class DomainSearcher
    {
        const string GroupAttribute = "memberOf";

        /// <summary>
        /// Gets an ldap connection
        /// </summary>
        /// <param name="domainDNSName">Dns domain name; can be netbios name as well or a server name, but dns domain name is the best thing to use generally</param>
        /// <param name="useSSL">Whether or not to use SSL</param>
        /// <param name="useGCPort">Whether or not to require a Global Catalog server</param>
        /// <returns>LdapConnection with the the specified parameters if it succeeds or null if it fails</returns>
        public static LdapConnection TryGetLdapConnection(string domainDNSName, bool useSSL, bool useGCPort)
        {
            try
            {
                LdapConnection l = new LdapConnection(
                    new LdapDirectoryIdentifier(
                        domainDNSName,
                        useGCPort ? (useSSL ? 3269 : 3268)
                                  : (useSSL ? 636 /*SSL PORT*/ : 389)
                    )
                );

                l.SessionOptions.SecureSocketLayer = useSSL;
                if (useGCPort) l.SessionOptions.LocatorFlag = LocatorFlags.GCRequired;

                // You can deal with other session options, client certificates, etc. here before binding by setting other options here
                // if desired for more advanced control including certification validation and supplying client certs
                // See here for a more thorough introduction into LdapConnection https://msdn.microsoft.com/en-us/library/bb332056.aspx
                // l.AuthType = AuthType.Ntlm; //Set AuthType to a specific type here if you know what type you want to use when binding
                if (!useSSL)
                {
                    l.AuthType = AuthType.Negotiate;
                    l.SessionOptions.Sealing = true;
                    l.SessionOptions.Signing = true;
                }

                // See the line below if you want to specify additional specific types of constraint for domain controller
                // lookup(this is what will be used with DsGetDcOpen - https://msdn.microsoft.com/en-us/library/ms675985(v=vs.85).aspx)
                // l.SessionOptions.LocatorFlag |= LocatorFlags.None;
                l.Bind(); // Pass System.Net.NetworkCredential here to bind with a specific set of credentials
                return l;
            }
            catch (Exception ex)
            {
                // HACK: You'll have to handle these yourself
                return null;
            }
            return null;
        }

        /// <summary>
        /// Gets the security groups a user is a member of recursively
        /// </summary>
        /// <param name="lc">LdapConnection to use</param>
        /// <param name="userDN">User's distinguished name</param>
        /// <param name="username">User's domain alias</param>
        /// <returns>Enumerable collection of security groups if it could be resolved</returns>
        public List<string> GetGroupsForUser(LdapConnection lc, string DLDN, string username)
        {
            // Create the search request
            SearchRequest sr = new SearchRequest();

            // LDAP search query for the domain alias (not domain/user, just username)
            // find search filter syntax and examples here: https://docs.microsoft.com/en-us/windows/desktop/ADSI/search-filter-syntax
            sr.Filter = "(&(sAMAccountName=" + username + "))";

            // dldn is what i'm using for the path, which includes the ou=users
            sr.DistinguishedName = DLDN;
            sr.Scope = System.DirectoryServices.Protocols.SearchScope.Subtree;

            // what attributes do we want back?  The memberOf is applied in the user object for each group they belong to
            // you could add more attributes for the user if you need to, such as the display name.
            sr.Attributes.Add(GroupAttribute);

            //send the search request
            SearchResponse srGroups = (SearchResponse)lc.SendRequest(sr);

            // storage
            List<string> aGroups = new List<string>();

            if (srGroups.ResultCode == ResultCode.Success)
            {
                foreach (SearchResultEntry sre in srGroups.Entries)
                {
                    //attributes of the search result entry are the attributes we added in the search request
                    foreach (byte[] b in sre.Attributes[GroupAttribute])
                    {
                        //The results for each attribute is a byte array, change it to a string
                        string t = System.Text.Encoding.ASCII.GetString(b);
                        aGroups.Add(t);
                    }
                }

                // Will throw out of range if it wasn't found because it doesn't exist or doesn't have the attribute
                return aGroups;
            }
            else
            {
                // we had an error...throw here
                throw new LdapException((int)srGroups.ResultCode, "Failed to query for tokenGroups", srGroups.ErrorMessage);
            }
        }
    }
}
```

**Comment by senthilray** [comment]
@djjz Thanks for the code snippet

**Comment by mateo-fi** [comment]
@djjz - Thanks so much for the code sample as I've struggled with this for years as well. Was there any mention by Microsoft of using the GetGroups(PrincipalContext) overload? I found that suggestion [here](https://stackoverflow.com/questions/55947060/userprincipal-getgroups-method-throws-exception-after-changing-domaincontrolle), and while it doesn't perform as well, I was able to verify that it fixed the issue during a recent DC maintenance I was made aware of. For support/maintenance reasons, I prefer the simplicity of the original code.

The first method is what I'm running now that has same issue you found. The 2nd is the updated one that seems to overcome the issue.

```
        /// <summary>
        /// Get the AD Groups for a given UserPrincipal
        /// </summary>
        /// <param name="user">UserPrincipal to query</param>
        /// <returns></returns>
        private List<string> GetUserGroupsToList(UserPrincipal user)
        {
            var groups = user.GetGroups();
                
            return new List<string>(groups.Select(x => x.SamAccountName));
        }

        /// <summary>
        /// Get the AD Groups for a given UserPrincipal and PrincipalContext
        /// </summary>
        /// <param name="user">UserPrincipal to query</param>
        /// <param name="principalContext"></param>
        /// <returns></returns>
        private List<string> GetUserGroupsToList(UserPrincipal user, PrincipalContext principalContext)
        {
            var groups = user.GetGroups(principalContext);

            return new List<string>(groups.Select(x => x.SamAccountName));
        }
```

**Comment by djjz** [comment]
@mateo-fi Missed that one completely, I'm afraid. Our conversations with Microsoft went quite straightforward from gathering information to triage and the provided code sample.
Do you have any estimations on the performance loss after switching to the overloaded method? It's already a winner, given the ease of implementation.

**Comment by mateo-fi** [comment]
@djjz - No worries. For me personally, I'm a member of ~75 groups. It's about 2x as slow using the "GetGroups(principalContext)" overload. Running locally, it's ~2.5 secs for GetGroups() vs ~5 secs for GetGroups(principalContext). The server is faster though, but the performance hit is proportional. I cache on my side, so this performance hit is minimized.
One user noted this about the "GetGroups(principalContext)" override, but I don't think this affects my scenario:
"Attention! This code returns list of groups only containing in domain associated with domainContext!

**Comment by snakex2000** [comment]
To comment, the LDAP solution should be the fastest & what support sends out when performance question comes into discussion on this topic.
