### ISSUE TITLE
Question - Thread pool alternatives

### ISSUE THREAD

**Issue by Korporal** [dotnet/runtime#42928]
This is just a question.

Does .Net Core provide any classes that implement a "throttled" thread pool concept?

The use case is a situation where a very large number of short lived REST upsert calls are being made, we want to limit the number of concurrent requests to some defined value like 3 or 5 or whatever.

This is to avoid flooding the network with excessive traffic, restrict the network traffic for the entire operation to some controlled value.

The standard thread pool limits the number of concurrent activities based on available CPU core count, such a design would tend to keep the network very busy which is undesirable.

So I just wondered if there have been any additions to .Net over the past few years that address this kind of thing.

Thanks

(I guess one way to do this is to put a Sleep inside every scheduled action and just use the thread pool as is, this will tend to have as many tasks active as there are cores yet prevent network saturation. So if a typical upsert elapsed time was say 50 mS then adding a 50 mS sleep at the end of the operation would reduce network traffic rates by 50%...)

**Comment by stephentoub** [comment]
Closing as a question asked and answered. Thanks.
