### ISSUE TITLE
Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM fails when compiled when Crossgen2

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#42924]
UnitTest_GVM started failing systematically on September 2, 2020, in the "coreclr-runtime crossgen2" runs on all architectures.

Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=826796&view=results

Platform: all

Diagnostic information:

<pre>
    Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.sh [FAIL]
      /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.sh: line 236: -r:/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/IL/*.dll: No such file or directory
      rm: cannot remove '/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll.rsp': No such file or directory
      
      Return code:      1
      Raw output file:      /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/Reports/Loader.classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.output.txt
      Raw output:
      BEGIN EXECUTION
      in takeLock
      /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/IL/UnitTest_GVM.dll
      Response file: /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll.rsp
      /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/IL/UnitTest_GVM.dll
      -o:/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll
      -r:/home/helixbot/work/A9720929/p/System.*.dll
      -r:/home/helixbot/work/A9720929/p/Microsoft.*.dll
      -r:/home/helixbot/work/A9720929/p/mscorlib.dll
      --verify-type-and-field-layout
      --targetarch:x64
      -O
      Running CrossGen2:  dotnet /home/helixbot/work/A9720929/p/crossgen2/crossgen2.dll @/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll.rsp  
      Emitting R2R PE file: /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll
      in ReleaseLock
      /home/helixbot/work/A9720929/p/corerun UnitTest_GVM.dll ''
      EXPECTED: GenRetType<!U,!V> TestType.MyFunc()
      ACTUAL1 : GenRetType<!U,!V> TestType.MyFunc()
      ACTUAL2 : GenRetType<!U,!V> TestType.MyFunc()
      
      EXPECTED: C TestType.MyFunc()
      ACTUAL1 : C TestType.MyFunc()
      ACTUAL2 : C TestType.MyFunc()
      
      EXPECTED: GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
      ACTUAL1 : GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
      ACTUAL2 : GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
      ACTUAL3 : GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
      
      EXPECTED: NonGenericDerived5<!!Y> TestType.MyGenFunc()
      ACTUAL1 : NonGenericDerived5<!!Y> TestType.MyGenFunc()
      ACTUAL2 : NonGenericDerived5<!!Y> TestType.MyGenFunc()
      ACTUAL3 : NonGenericDerived5<!!Y> TestType.MyGenFunc()
      
      EXPECTED: GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
      ACTUAL1 : GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
      ACTUAL2 : GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
      ACTUAL3 : GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
      
      EXPECTED: NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
      ACTUAL1 : NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
      ACTUAL2 : NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
      ACTUAL3 : NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
      
      EXPECTED: GenDerive1<!U, class Dictionary<!!Y,!V>> GenMiddleType.MyGenFunc()
      ACTUAL1 : GenDerive1<!U, class Dictionary<!!Y,!V>> GenMiddleType.MyGenFunc()
      ACTUAL2 : GenDerive1<!U, class Dictionary<!!Y,!V>> GenMiddleType.MyGenFunc()
      
      EXPECTED: NonGenericDerived1<int32,!!Y> GenMiddleType.MyGenFunc()
      ACTUAL1 : NonGenericDerived1<int32,!!Y> GenMiddleType.MyGenFunc()
      ACTUAL2 : NonGenericDerived1<int32,!!Y> GenMiddleType.MyGenFunc()
      
      EXPECTED: GenToNonGen1<!V, class Dictionary<string,!!Y>> GenMiddleType.GenToNonGen()
      ACTUAL1 : GenToNonGen1<!V, class Dictionary<string,!!Y>> GenMiddleType.GenToNonGen()
      ACTUAL2 : GenToNonGen1<!V, class Dictionary<string,!!Y>> GenMiddleType.GenToNonGen()
      
      EXPECTED: NonGenThroughGen2<object,int32,!!Y> GenMiddleType.NonGenThroughGenFunc()
      ACTUAL1 : NonGenThroughGen2<object,int32,!!Y> GenMiddleType.NonGenThroughGenFunc()
      ACTUAL2 : NonGenThroughGen2<object,int32,!!Y> GenMiddleType.NonGenThroughGenFunc()
      
      Caught expected TypeLoadException:
      System.TypeLoadException: Return type in method 'Invalid1[Y].NonGenThroughGenOverride(System.String ByRef)' on type 'Invalid1[U,V]' from assembly 'UnitTest_GVM, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'GenMiddleType[Y].NonGenThroughGenFunc(System.String ByRef)'.
         at CMain.RunInvalidTest1()
         at CMain.Main(String[] args)
      Invalid2[System.Int32,System.Object]
      FAIL: did not catch expected TypeLoadException when loading Invalid2.
      Caught expected TypeLoadException:
      System.TypeLoadException: Return type in method 'Invalid3[Y].NewGenFunc1(System.String ByRef)' on type 'Invalid3[U,V]' from assembly 'UnitTest_GVM, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'GenMiddleType[Y].MyGenFunc(System.String ByRef)'.
         at CMain.RunInvalidTest3()
         at CMain.Main(String[] args)
      Invalid4[System.Int32,System.Object]
      FAIL: did not catch expected TypeLoadException when loading Invalid4.
      Test FAILED
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/home/helixbot/work/A9720929/p
      > /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/artifacts/tests/coreclr/Linux.x64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs(7706,0): at Loader_classloader._MethodImpl_CovariantReturns_UnitTest_UnitTest_GVM_UnitTest_GVM_._MethodImpl_CovariantReturns_UnitTest_UnitTest_GVM_UnitTest_GVM_sh()
      Output:
        /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.sh: line 236: -r:/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/IL/*.dll: No such file or directory
        rm: cannot remove '/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll.rsp': No such file or directory
        
        Return code:      1
        Raw output file:      /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/Reports/Loader.classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.output.txt
        Raw output:
        BEGIN EXECUTION
        in takeLock
        /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/IL/UnitTest_GVM.dll
        Response file: /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll.rsp
        /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/IL/UnitTest_GVM.dll
        -o:/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll
        -r:/home/helixbot/work/A9720929/p/System.*.dll
        -r:/home/helixbot/work/A9720929/p/Microsoft.*.dll
        -r:/home/helixbot/work/A9720929/p/mscorlib.dll
        --verify-type-and-field-layout
        --targetarch:x64
        -O
        Running CrossGen2:  dotnet /home/helixbot/work/A9720929/p/crossgen2/crossgen2.dll @/home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll.rsp  
        Emitting R2R PE file: /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.dll
        in ReleaseLock
        /home/helixbot/work/A9720929/p/corerun UnitTest_GVM.dll ''
        EXPECTED: GenRetType<!U,!V> TestType.MyFunc()
        ACTUAL1 : GenRetType<!U,!V> TestType.MyFunc()
        ACTUAL2 : GenRetType<!U,!V> TestType.MyFunc()
        
        EXPECTED: C TestType.MyFunc()
        ACTUAL1 : C TestType.MyFunc()
        ACTUAL2 : C TestType.MyFunc()
        
        EXPECTED: GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
        ACTUAL1 : GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
        ACTUAL2 : GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
        ACTUAL3 : GenDerive2<!U,!V,!!Y> TestType.MyGenFunc()
        
        EXPECTED: NonGenericDerived5<!!Y> TestType.MyGenFunc()
        ACTUAL1 : NonGenericDerived5<!!Y> TestType.MyGenFunc()
        ACTUAL2 : NonGenericDerived5<!!Y> TestType.MyGenFunc()
        ACTUAL3 : NonGenericDerived5<!!Y> TestType.MyGenFunc()
        
        EXPECTED: GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
        ACTUAL1 : GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
        ACTUAL2 : GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
        ACTUAL3 : GenToNonGen3<!V,!!Y> TestType.GenToNonGen()
        
        EXPECTED: NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
        ACTUAL1 : NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
        ACTUAL2 : NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
        ACTUAL3 : NonGenThroughGen5<!!Y> TestType.NonGenThroughGenFunc()
        
        EXPECTED: GenDerive1<!U, class Dictionary<!!Y,!V>> GenMiddleType.MyGenFunc()
        ACTUAL1 : GenDerive1<!U, class Dictionary<!!Y,!V>> GenMiddleType.MyGenFunc()
        ACTUAL2 : GenDerive1<!U, class Dictionary<!!Y,!V>> GenMiddleType.MyGenFunc()
        
        EXPECTED: NonGenericDerived1<int32,!!Y> GenMiddleType.MyGenFunc()
        ACTUAL1 : NonGenericDerived1<int32,!!Y> GenMiddleType.MyGenFunc()
        ACTUAL2 : NonGenericDerived1<int32,!!Y> GenMiddleType.MyGenFunc()
        
        EXPECTED: GenToNonGen1<!V, class Dictionary<string,!!Y>> GenMiddleType.GenToNonGen()
        ACTUAL1 : GenToNonGen1<!V, class Dictionary<string,!!Y>> GenMiddleType.GenToNonGen()
        ACTUAL2 : GenToNonGen1<!V, class Dictionary<string,!!Y>> GenMiddleType.GenToNonGen()
        
        EXPECTED: NonGenThroughGen2<object,int32,!!Y> GenMiddleType.NonGenThroughGenFunc()
        ACTUAL1 : NonGenThroughGen2<object,int32,!!Y> GenMiddleType.NonGenThroughGenFunc()
        ACTUAL2 : NonGenThroughGen2<object,int32,!!Y> GenMiddleType.NonGenThroughGenFunc()
        
        Caught expected TypeLoadException:
        System.TypeLoadException: Return type in method 'Invalid1[Y].NonGenThroughGenOverride(System.String ByRef)' on type 'Invalid1[U,V]' from assembly 'UnitTest_GVM, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'GenMiddleType[Y].NonGenThroughGenFunc(System.String ByRef)'.
           at CMain.RunInvalidTest1()
           at CMain.Main(String[] args)
        Invalid2[System.Int32,System.Object]
        FAIL: did not catch expected TypeLoadException when loading Invalid2.
        Caught expected TypeLoadException:
        System.TypeLoadException: Return type in method 'Invalid3[Y].NewGenFunc1(System.String ByRef)' on type 'Invalid3[U,V]' from assembly 'UnitTest_GVM, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'GenMiddleType[Y].MyGenFunc(System.String ByRef)'.
           at CMain.RunInvalidTest3()
           at CMain.Main(String[] args)
        Invalid4[System.Int32,System.Object]
        FAIL: did not catch expected TypeLoadException when loading Invalid4.
        Test FAILED
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/home/helixbot/work/A9720929/p
        > /home/helixbot/work/A9720929/w/CA9F0A5F/e/Loader/classloader/MethodImpl/CovariantReturns/UnitTest/UnitTest_GVM/UnitTest_GVM.sh
</pre>

/cc: @dotnet/crossgen-contrib

**Comment by trylek** [comment]
@janvorli, can you please provide an update on this issue? Are we already out of the woods w.r.t. this one based on your various covariant fixes in the past months?

**Comment by janvorli** [comment]
I've tried to run all coreclr test with crossgen2 (removed the issues.targets record first) and everything passed.

**Comment by trylek** [comment]
Thanks Jan - does that mean that you've already removed the issues.targets exclusion or do we still need to do that one last step? In such case I can easily send out the trivial PR if you're busy with other matters, it's just that I noticed we're sitting on dozens of bugs in various states of freshness and I believe we should strive to close as many as we can especially if we believe that the issue in question no longer exists.

**Comment by janvorli** [comment]
I just did that locally before to check, but I can easily create a PR from that local change.

**Comment by trylek** [comment]
That would be great, thank you! I guess we can tag that PR to close this issue.
