### ISSUE TITLE
Enumeration value emitted as empty object

### ISSUE THREAD

**Issue by ethanshea-ms** [dotnet/runtime#42940]
### Description

When serializing enums, if the field type is `Enum` then the emitted value is `{}`

### Configuration

Tested with .NET Core 3.1

### Other information

Code example:
https://dotnetfiddle.net/uYOYJp

```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

public class Program
{    
    public static void Main()
    {
        var options = new JsonSerializerOptions
        {
            Converters =
            {
                new JsonStringEnumConverter(),
            },
        };

        // Prints `"Value"`. Correct behavior
        Console.WriteLine(JsonSerializer.Serialize(TestEnum.Value, options));

        // Prints `{"EnumValue":{}}`. Desired output: `{"EnumValue":"Value"}`
        Console.WriteLine(JsonSerializer.Serialize(new TestModel { EnumValue = TestEnum.Value }, options));
    }
}

public class TestModel {
    public Enum EnumValue {get; set;}
}

public enum TestEnum 
{
   Value
}
```

This does not happen with other serializers like Newtonsoft.

https://dotnetfiddle.net/tT8zZx
```csharp
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public class Program
{    
    public static void Main()
    {
        var options = new JsonSerializerSettings
        {
            Converters =
            {
                new StringEnumConverter(),
            },
        };

        // Prints `"Value"`. Correct behavior
        Console.WriteLine(JsonConvert.SerializeObject(TestEnum.Value, options));

        // Prints `{"EnumValue":"Value"}`. Correct behavior
        Console.WriteLine(JsonConvert.SerializeObject(new TestModel { EnumValue = TestEnum.Value }, options));
    }
}

public class TestModel {
    public Enum EnumValue {get; set;}
}

public enum TestEnum 
{
   Value
}
```

## Known Workaround

Use a field type which is more specific. For example:
```csharp
public class TestModel {
    public TestEnum EnumValue {get; set;}
}
```

**Comment by huoyaoyuan** [comment]
I think this should be by design? In most cases, values are converted using the declared type in model, not the actual object type.

**Comment by ethanshea-ms** [comment]
This behavior breaks the round-trip property of serialization.

**Comment by huoyaoyuan** [comment]
Round-tripping is impossible in this case, because the deserailization site has no information about the `TestEnum` type present.

**Comment by layomia** [comment]
Unless the declared type of the property is `System.Object`, `JsonSerializer` will not serialize it as the runtime type (`typeof(TestEnum)` in this case). The desired behavior will be enabled when polymorphic support is extended - https://github.com/dotnet/runtime/issues/29937, https://github.com/dotnet/runtime/issues/30083.
