### ISSUE TITLE
Add analyzer for Environment.ProcessPath 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#42948]
`Environment.ProcessPath` API introduced by #40862 is a significantly more efficient replacement of `Process.GetCurrentProcess().MainModule.FileName`. This pattern is quite common. We should add analyzer and fixer for this.

More context: https://github.com/dotnet/runtime/pull/42768#issuecomment-699515570

**Comment by Serg046** [comment]
I'll do it, guess it should be there https://github.com/dotnet/roslyn-analyzers/tree/master/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime.
While I'm preparing a PR, you can suggest an analyzer key, name, etc (otherwise we will discuss it in scope of the PR)

**Comment by jkotas** [comment]
Thank you @Serg046 !

The naming and structure of this analyzer should mirror the naming and structure of the existing UseEnvironmentProcessId analyzer. It may be idea a good idea to just add handling of this pattern to the existing analyzer - see https://github.com/dotnet/runtime/pull/42768#issuecomment-699516399 and https://github.com/dotnet/runtime/pull/42768#issuecomment-699520037 for more context.

**Comment by terrajobst** [comment]
Makes sense as proposed
