### ISSUE TITLE
X509RevocationMode.Offline Linux behavior differs from Windows for OCSP

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#42958]
It seems that for `X509RevocationMode.Offline`, OCSP cache behavior is different from Windows. On Windows, I believe this test will pass, and fail on Linux

```c#
[Fact]
public static void TestRevocation_Offline_Revoked_Ocsp()
{
    SimpleTest(
        PkiOptions.OcspEverywhere,
        (root, intermediate, endEntity, onlineHolder, responder) =>
        {
            DateTimeOffset revokeTime = DateTimeOffset.UtcNow;
            intermediate.Revoke(endEntity, revokeTime);

            using ChainHolder offlineHolder = new ChainHolder();
            X509Chain offlineChain = offlineHolder.Chain;
            X509Chain onlineChain = onlineHolder.Chain;
            onlineChain.ChainPolicy.VerificationTime = revokeTime.AddSeconds(1).UtcDateTime;

            CopyChainPolicy(from: onlineChain, to: offlineChain);
            offlineChain.ChainPolicy.RevocationMode = X509RevocationMode.Offline;

            SimpleRevocationBody(
                onlineHolder,
                endEntity,
                rootRevoked: false,
                issrRevoked: false,
                leafRevoked: true);

            responder.Stop();

            SimpleRevocationBody(
                offlineHolder,
                endEntity,
                rootRevoked: false,
                issrRevoked: false,
                leafRevoked: true);

        });
}
```

Linux failure:

```
Expected: X509ChainStatusFlags[] [NoError, NoError, Revoked]
Actual:   X509ChainStatusFlags[] [NoError, RevocationStatusUnknown | OfflineRevocation, RevocationStatusUnknown | OfflineRevocation]
```

It seems the OCSP cache is being ignored, or, the online build didn't cache the OCSP response.

CRL behaves correctly.

**Comment by vcsjones** [comment]
It seems that `OCSP_resp_find_status` is coming back as NULL, and we skip caching anything as null. Hmm.

**Comment by vcsjones** [comment]
[sigh] 🙄 nextUpdate was null... because I was setting it to null... in the test. Nothing to see here.

**Comment by vcsjones** [comment]
I guess if there is another to learn here, is that for an OCSP response, Windows will cache it for some unknown duration even if the response has no `nextUpdate`.

**Comment by bartonjs** [comment]
Assuming I'm reading wincrypt.h correctly, Windows considers an OCSP response expired if nextUpdate is missing and it has been more than 12 hours (CERT_CHAIN_OCSP_VALIDITY_SECONDS_DEFAULT).  I don't know if that's also what's used for the caching policy.  Maybe your computer is bored and wants to run a test overnight? :smile:.  (I don't know enough about their caching engine to know if asking for it will keep it in the cache longer than it might otherwise be there, or what.)
