### ISSUE TITLE
Console.OutputEncoding by default returns a wrong value on Windows Nano Server

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#42959]
```
Encoding curEncoding = Console.OutputEncoding;
```

On Windows Nano Server `curEncoding.EncodingName` is "Codepage - 0" which looks like a default value. This might be a product issue where the Encoding can't be retrieved when pinvoking.

cc @eiriktsarpalis

**Comment by danmosemsft** [comment]
This just means that `::GetConsoleOutputCP()` failed. In such a case we still create and return an `Encoding` about a nonexistent codepage 0. (We did this in .NET Framework too so I am not sure whether it would be a good idea to change it to throw instead.)

I am guessing this API is just stubbed out on Nano and perhaps we should just leave the code as is.
