### ISSUE TITLE
Question: The best place to get the most complete list of HRESULT enums

### ISSUE THREAD

**Issue by o-lekarev** [dotnet/runtime#42953]
We are refactoring our debugger's error handling now and need to process and display error messages. I've found dozen(s) of files, containing the definitions of HRESULT enums here and there inside the Runtime. 
Can anybody tell me the best place where I can get the most completed list of HRESULTs related to ICorDebug* related interfaces. Thank you.

**Comment by hoyosjs** [comment]
`src/coreclr/src/pal/prebuilt/inc/corerror.h` has the master list of errors, and the descriptions if available are at https://github.com/dotnet/runtime/blob/master/src/coreclr/src/inc/corerror.xml

**Comment by danmosemsft** [comment]
@o-lekarev this seems answered. Please reopen if needed.
