### ISSUE TITLE
Investigate simplifying runtime test xunit wrapper generation

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#42969]
Today we generate the XUnit test wrappers for the runtime tests completely within MSBuild. This makes the experience maintaining these wrappers tedious and error prone.

Now that Roslyn supports source generators and Roslyn allows reading metadata from MSBuild that is passed to a source generator (see [the Roslyn cookbook](https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata) and  [this blog post about how to pass MSBuild info to source generators](https://jaylee.org/archive/2020/09/13/msbuild-items-and-properties-in-csharp9-sourcegenerators.html)), we should investigate moving the Xunit wrapper generation from MSBuild into a C# source generator.

**Comment by trylek** [comment]
@jkoritzinsky - I believe this becomes moot in light of our test merging plan. Do you agree we can close this?

**Comment by jkoritzinsky** [comment]
Yes, we can close this
