### ISSUE TITLE
APICompat for ref-pack servicing

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#42961]
We now permit servicing of our ref-packs.  We should make sure that any change made to the ref-packs in servicing is API compatible with an un-serviced ref-pack.

This ensures that a library compiled against the serviced ref-pack will work with a GA runtime, or another un-serviced consuming compile (eg: in case of nuget packages).

The purpose of this would be to *block* API additions in servicing.

I think we can accomplish this in a similar way we do API compat with past release, restoring the GA-refpack.
https://github.com/dotnet/runtime/blob/b87e3351bf4603bfdb66e14c20921d618db954f9/src/libraries/shims/ApiCompat.proj#L107-L121

We should treat current ref-pack as "contract" and GA ref-pack as implementation.  That will catch any case where a current reference couldn't be satisfied by GA ref-pack.

CC @dougbu since this sort of check would be interesting for AspNET as well.

**Comment by ericstj** [comment]
cc @danmosemsft, this is related to https://github.com/dotnet/corefx/pull/42993, although it wouldn't help there.

**Comment by dougbu** [comment]
@ericstj FYI this might be interesting to dotnet/aspnetcore but _only_ in combination with a major back-port to move the GenApi and APICompat changes I and @safern made in Arcade's master branch. Might also need an additional bug fix or two IIRC (e.g. I recall something about attribute exclusions not using configured filters).

We use Roslyn to build our ref/ assemblies and Microsoft.CodeAnalysis.PublicApiAnalyzers to keep the API consistent for 5.0 and later.

**Comment by ericstj** [comment]
@dougbu it's still interesting.  Probably more-so.  It prevents devs from accidentally adding new public surface in servicing.

**Comment by dougbu** [comment]
@ericstj we fail builds if the public API baseline `*.txt` files don't match according to Microsoft.CodeAnalysis.PublicApiAnalyzers. If that check isn't working in our CI builds, we've got a big problem and I'd work with the analyzers team to fix it. But, thanks for the reminder to test again❕

**Comment by ericstj** [comment]
I see. Yeah PublicApiAnalyzers would force a diff to show up which hopefully devs won’t ignore in servicing.

**Comment by ViktorHofer** [comment]
@Anipik is this item necessary for 5.0.x servicing or should we implement it in master for 6.0 LTS?

**Comment by Anipik** [comment]
> @Anipik is this item necessary for 5.0.x servicing or should we implement it in master for 6.0 LTS?

Its not critical for 5.0.x, we can implement for it for 6.0

**Comment by ViktorHofer** [comment]
@ericstj I wonder if we would just need to update the `NetCoreAppLatestStablePackageBaselineVersion` property to `$(MajorVersion).$(MinorVersion).0` when `PreReleaseVersionLabel` equals "servicing" and unset the `ApiCompatNetCoreAppLatestStableBaselineFile` property?

If so, then I'm happy to make the change.

**Comment by ericstj** [comment]
We need to do that, and run it in reverse (or [strict mode](https://github.com/dotnet/sdk/issues/25302) for the new PackageValidation).  The expectation is that we are both compatible with the GA release and we do not add surface area on top of the GA release.
