### ISSUE TITLE
Defining operators to speed up string appension without StringBuilder (proposal)

### ISSUE THREAD

**Issue by faintwary** [dotnet/runtime#42970]
## Would it be practical 
Appending strings is that of an unnecessary difficulty, not particularly in a casual sense, as it is extremely easy to write `foo += bar`. But, in a [performance-critical sense](https://www.tutorialsteacher.com/csharp/csharp-stringbuilder), the current method using StringBuilder is extremely clunky and could use refinement. 

## Example
The following code was written in the context of a Discord API program using the DSharpPlus library.
```cs
            StringBuilder sb = new StringBuilder();
            
            StringBuilder sb2 = new StringBuilder();
            sb2.Append(Program.ALPHA ? "alpha " : "");
            sb2.Append(Program.BETA ? "beta " : "");
            sb2.Append(Program.VERSION);
            sb2.Append(Program.RC ? "rc" : "");
            sb.AppendLine($"**Version:** {sb2.ToString()}");
            sb.AppendLine($"**Developer:** {Program.DEVELOPERS}");
            sb.AppendLine($"**Creation Date:** 8/1/2020");
            sb.AppendLine($"**Prefix:** `r.`");
            
            embed.Description = sb.ToString();
```
The excessive use of StringBuilders is extremely important to the developer. He/she expects the program to have to execute this code multiple times over and asynchronously. This could be easily be simplified by defining an insertion operator.
```cs
            string versionString = "";

            versionString << Program.ALPHA ? "alpha " : "" << Program.BETA ? "beta " : ""
                   << Program.VERSION << Program.RC ? "rc" : "";
            
            embed.Description = $"**Version:** {versionString}\n" 
                     << $"**Developer:** {Program.DEVELOPERS}\n**Creation Date:** 8/1/2020\n**Prefix:**`r.`";
```
## Benchmarks
The benchmark was run on a machine running 3.6GHz turbo.
The benchmark pits three most common methods of combining strings.
There are 100000 iterations, each adding a single character to a string that is initially empty.

[The source code.](https://pastebin.com/YGxdjDMQ)
The results:
```
Interpolation: 1283.5525ms
Concatenation: 1257.3147ms
StringBuilder: 0.6984ms
```

## Pros/Cons
The new code comes with some pros/cons:

**Pros:**
  - The new code will not replace StringBuilders, so it will not break old code
  - The new code can reduce the amount of source code to be written significantly
  - The new code requires less code, while keeping the same performance as more code

**Cons:**
  - The new code could feel alien to experienced .NET programmers
  - The new code, while useful, uses an operator symbol that may feel out of place for its common purpose
  - The new code may make some code a little bit harder to read, or may not feel very verbose

**Comment by DethRaid** [comment]
> The new code could feel alien to experienced .NET programmers

I don't think you appreciate how much of a con this is. `operator<<` isn't worth alienating experienced C# devs

**Comment by danmosemsft** [comment]
Thanks for the suggestions. I don't believe we will do this. I believe this conflicts with our [design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads) specifically it overloads operators on a non-primitive type, and arguably creates "cute" (non intuitive) overloads. It's just not something a .NET developer would expect. 

As @DethRaid mentions, you can make your own extension methods, but also note that all the `Append(..)` overloads return their StringBuilder, so you can chain, if you find that visually more appealing, eg., 
```c#
            StringBuilder sb = new StringBuilder();

            sb.AppendLine($"**Version:** ");
            sb.Append(Program.ALPHA ? "alpha " : Program.BETA ? "beta " : "");
            sb.Append(Program.VERSION).Append(Program.RC ? "rc" : "");
            sb.AppendLine($"**Developer:** {Program.DEVELOPERS}");
            sb.AppendLine($"**Creation Date:** 8/1/2020");
            sb.AppendLine($"**Prefix:** `r.`");
            
            embed.Description = sb.ToString();
```

Thanks for the suggestion.
