### ISSUE TITLE
dotnet-dump collect never returns

### ISSUE THREAD

**Issue by sabrogden** [dotnet/runtime#42980]
I'm trying to collect a dump file on a dotnet core 3.1 process running in docker container FROM mcr.microsoft.com/dotnet/core/runtime:3.1-bionic and the collect call just never returns. It sits there with the message, "Writing full to /root/core_20201001_202020"   What can I do to diagnose this?  I see there is a --diag flag, what will this do?  Write a debug file, where?

Now I have a different docker container using the same base image running a different dotnet core app and the dump works as expected, completing in a second or two.  

My app does pinvoke native dlls, could that be a problem?  Dumping this same process running on windows works. Dumping this process in the docker container works with gcore.

**Comment by tommcdon** [comment]
Fixed in 6.0
