### ISSUE TITLE
BackgroundService.StopAsync never completes when called from a WPF project from Application.Exit event or Application.OnExit override

### ISSUE THREAD

**Issue by codingdna2** [dotnet/runtime#42993]
### Description
BackgroundService StopAsync never completes when called from a WPF project from Application.Exit event or Application.OnExit override. Not sure this is the right repo to open the issue so be patient with me.

### To Reproduce
Steps to reproduce the behavior ([sample project](https://github.com/codingdna2/WPFWithBackgroundService))

Relevant parts:
```csharp
public partial class App : Application
{
    private IHost _host;

    public static IHostBuilder CreateHostBuilder() => new HostBuilder().ConfigureAppConfiguration((context, configurationBuilder) =>
    {
        configurationBuilder.AddEnvironmentVariables();
        configurationBuilder.SetBasePath(context.HostingEnvironment.ContentRootPath);
    });

    public App()
    {
        _host = CreateHostBuilder().ConfigureServices((context, services) =>
        {
            services.AddHostedService<MyService>();
            services.AddSingleton<MainWindow>();
        }).Build();
    }

    private async void OnApplicationExit(object sender, ExitEventArgs e)
    {
        await _host.StopAsync();

        _host.Dispose();

        _host = null;
    }

    private async void OnApplicationStartup(object sender, StartupEventArgs e)
    {
        await _host.StartAsync();

        var mainWindow = _host.Services.GetService<MainWindow>();
        mainWindow.Show();
    }
}
```

```csharp
public class MyService : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            await Task.Delay(10, stoppingToken);
        }
    }
}
```

### Expected behavior
The StopAsync should complete or timeout.

### Additional context
I think a deadlock occurs but I've no idea how to prevent it. I've tried to debug the BackgroundService class and the offending part is the `Task.WhenAny` included in `StopAsync`. I've also tried to wrap the call to `StopAsync` in a `Task` but the effect is the same.

Any suggestion is appreciated.

**Comment by mayorovp** [comment]
Try this:

```cs
    private void OnApplicationExit(object sender, ExitEventArgs e) // this method cannot be async, it MUST wait!
    {
        Task.Run(() => await _host.StopAsync()).Wait();

        _host.Dispose();

        _host = null;
    }
```

Or something like this:

```cs
    private void OnApplicationExit(object sender, ExitEventArgs e) // this method cannot be async, it MUST wait!
    {
        var frame = new DispatcherFrame(false);
        
        Task.Run(() => {
            await _host.StopAsync();
            frame.Continue = false;
        });

        Dispatcher.PushFrame(frame);

        _host.Dispose();

        _host = null;
    }
```

**Comment by codingdna2** [comment]
**Test results, suggested solution 1:**
Changed slightly adding `async`: `Task.Run(async () => await _host.StopAsync()).Wait();`
but this one ends with an `AggregateException` `'Remove root: handle=10, parent=01s.WpfTap.Utility.)'` containing a `TaskCanceledException` which referes to the actual task.

**Test results, suggested solution 2:**
Changed slightly adding `async`. This one appears to be working as excepted! Thanks!
_Updated sample repo with this fix._

I leave to owners decision to close issue or not.

**Comment by eerhardt** [comment]
With #56057 we no longer block on ProcessExit in the ConsoleLifetime on net6.0. So this issue is now fixed.

However, the correct fix here is to not use ConsoleLifetime in a WPF app, since it is not a "console app". So implementing your own WpfLifetime is the right idea.

**Comment by codingdna2** [comment]
Thanks @eerhardt, but I should clarify here the issue was not the ConsoleLifetime (in fact implementing WpfLifetime was a test I've commented above) but the usage of Tasks from the OnApplicationExit event.
