### ISSUE TITLE
When SequenceReader is completed, it's Position is not equal to it's Sequence.End.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#42999]
### Description
```csharp
ReadOnlySequence<byte> buffer = new ReadOnlySequence<byte>( new byte[50] );
SequenceReader<byte> reader = new SequenceReader<byte>( buffer );
reader.Advance( 50 );
reader.End.Should().BeTrue();// Pass
buffer.Slice( reader.Position ).Length.Should().Be( 0 );// Pass
reader.Position.Equals( buffer.End ).Should().BeTrue();// Fail
```
I don't understand why this test fails, is this intended ?
The documentation tell 
> Equality does not guarantee that the two instances point to the same location in a ReadOnlySequence<T>.  

With this, I understand that, two instance not pointing to the same location can be equals,
but not that two SequencePositiong pointing to the same thing are not equal.

Discussed this with @tannergooding on discord.

**Comment by tannergooding** [comment]
When I took a look this morning its because `reader.Position.GetInteger()` didn't have the "end of sequence" flag set, while `buffer.End` did.

**Comment by Kuinox** [comment]
Yes, looks like the `SequenceReader` is not the issue here, the `SequenceReader` call `Sequence.GetPosition`  
And it have the same issue:  
```csharp
ReadOnlySequence<byte> buffer = new ReadOnlySequence<byte>( new byte[50] );
buffer.GetPosition( 50 ).Equals( buffer.End ).Should().BeTrue();// Fail
```

**Comment by Kuinox** [comment]
I stumbled on this bug again:  
```csharp
ReadOnlySequence<byte> sequence = new ReadOnlySequence<byte>( new byte[1] );
SequenceReader<byte> reader = new SequenceReader<byte>();
reader.Position.Should().Be( sequence.Start );// fail
```
If this is indeed a bug (IMO it is), I would love to try to do a PR if possible.

**Comment by tannergooding** [comment]
CC. @GrabYourPitchforks @adamsitnik

**Comment by carlossanlop** [comment]
> I would love to try to do a PR if possible.

@Kuinox thank you for offering. I'm assigning the issue to you.

**Comment by Kuinox** [comment]
Thanks, I will try to do the PR over this WeekEnd.

**Comment by Kuinox** [comment]
I noticed that my snippet had an issue: 
```
ReadOnlySequence<byte> buffer = new ReadOnlySequence<byte>( new byte[50] );
buffer.GetPosition( 50 ).Equals( buffer.End ).Should().BeTrue();// Fail
```
`GetPosition( 50 )`: I thought it should fail with an OutOfRangeException.
But someone pointed me to this issue:  
https://github.com/dotnet/runtime/issues/27751  
And by reading this comment in particular: https://github.com/dotnet/runtime/issues/27751#issuecomment-434524454
I think this change needs more discussion? ^^

Currently, the current behavior is:
`GetPosition(size) != GetPosition(End)`
`GetPosition(size-1) != GetPosition(End)`
`GetPosition(size) != GetPosition(size-1)`

It leads to weird behavior like in my first comment, but it looks like it can't be changed easily.
So I don't know what behavior I should change, or even if it should be changed.

**Comment by Kuinox** [comment]
So I made a fix but there are still weird things:  
An empty sequence will have the flag on End but not Start, but both point to the same position.  
If you instantiate a ROSequence with the constructor `ReadOnlySequence(ReadOnlySequenceSegment<T> startSegment, int startIndex, ReadOnlySequenceSegment<T> endSegment, int endIndex)` the End field won't have the flag.  

I didn't found anything that relies on this flag, it would not be better to delete it if it really has no use?
If anything relies on it, I believe it won't work with the constructor

**Comment by Kuinox** [comment]
Ok so I found what was the purpose of these flags:  
It allows storing the SequenceType.  
A simple fix is to stop leaking these flags.
I open a PR.
