### ISSUE TITLE
Source-build cli/apphost/static/singlefilehost native build failure: "pal_ssl.c:710: undefined reference to `local_X509_new'"

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#42991]
In https://github.com/dotnet/source-build/pull/1782, we're trying to update source-build to 5.0.0-rc.1, but hitting an issue in the installer native build with cli/apphost/static/singlefilehost, during a non-portable build (link to system libraries):

```
    [100%] Built target hostpolicy
    /work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/artifacts/bin/native/net5.0-Linux-Release-x64/libSystem.Security.Cryptography.Native.OpenSsl.a(pal_ssl.c.o): In function `CryptoNative_OpenSslGetProtocolSupport':
    /work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c:710: undefined reference to `local_X509_new'
    clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[2]: *** [cli/apphost/static/singlefilehost] Error 1
    gmake[1]: *** [cli/apphost/static/CMakeFiles/singlefilehost.dir/all] Error 2
    gmake: *** [all] Error 2
    Errors
        /work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/installer/corehost/corehost.proj(46,5): error MSB3073: The command "/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/installer/corehost/build.sh Release x64 -apphostver "5.0.0-rc.1.20451.14" -hostver "5.0.0-rc.1.20451.14" -fxrver "5.0.0-rc.1.20451.14" -policyver "5.0.0-rc.1.20451.14" -commithash "78f189bca6ae9a9d1a994753eae9f88d59b80ef9" -os Linux -cmakeargs "-DVERSION_FILE_PATH=/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/artifacts/obj/_version.c" -portablebuild=false -keepnativesymbols -coreclrartifacts /work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/artifacts/bin/coreclr/Linux.x64.Release/ -nativelibsartifacts /work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/artifacts/bin/native/net5.0-Linux-Release-x64" exited with code 2. [/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/installer/corehost/corehost.proj]
```

This seems to be around the same area as we had issues with in https://github.com/dotnet/runtime/issues/41768, but I'm not good enough at cmake builds to really know what to look at. Here are the same set of logs as last time plus a binlog though, from a build I did on my own machine with a CentOS 7 Docker image:

[5.0-rc1-host-logs.zip](https://github.com/dotnet/runtime/files/5320334/5.0-rc1-host-logs.zip)

@omajid @janvorli can you help diagnose this?

(Manually labeling based on this being a native build error in the host, feel free to relabel.)

**Comment by omajid** [comment]
I am going to try this out locally. 

There's a warning earlier in the build log that might be related:

```
/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c(710,19): warning G1ADEDC8E: implicit declaration of function 'local_X509_new' is invalid in C99 [-Wimplicit-function-declaration] [/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/build-native.proj]
##vso[task.logissue type=warning;sourcepath=/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c;linenumber=710;columnnumber=19;code=G1ADEDC8E;](NETCORE_ENGINEERING_TELEMETRY=Build) implicit declaration of function 'local_X509_new' is invalid in C99 [-Wimplicit-function-declaration%5D
      X509 * cert = X509_new();
                    ^
  /work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.h:1095:18: note: expanded from macro 'X509_new'
  #define X509_new local_X509_new
                   ^
/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c(710,12): warning G8E577B7D: incompatible integer to pointer conversion initializing 'X509 *' (aka 'struct x509_st *') with an expression of type 'int' [-Wint-conversion] [/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/build-native.proj]
##vso[task.logissue type=warning;sourcepath=/work/artifacts/src/runtime.38017c3935de95d0335bac04f4901ddfc2718656/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c;linenumber=710;columnnumber=12;code=G8E577B7D;](NETCORE_ENGINEERING_TELEMETRY=Build) incompatible integer to pointer conversion initializing 'X509 *' (aka 'struct x509_st *') with an expression of type 'int' [-Wint-conversion%5D
      X509 * cert = X509_new();
             ^      ~~~~~~~~~~

```

**Comment by omajid** [comment]
I can not reproduce on Fedora 32 by building commit `78f189bca6ae9a9d1a994753eae9f88d59b80ef9`. The build continues and fails later on building aspnetcore. I am going to try again with one of the other environments used in CI..

**Comment by dagood** [comment]
Interesting. It looks like even in that CI build I linked, it failed in this way on:
CentOS 7, Fedora 30, Fedora 31, Debian 9, Ubuntu 18.04
but it worked (failing later at aspnetcore) on:
CentOS 8, macOS

Thanks for taking a look.

**Comment by janvorli** [comment]
This is strange. The local_X509_new is not defined in the apibridge.c unlike other local_xxx functions. @bartonjs do you have any idea what can be going on?

**Comment by omajid** [comment]
`X509_new` seems to be defined in OpenSSL 1.0.x: https://www.openssl.org/docs/man1.0.2/man3/X509_new.html. It probably doesn't need to have a `local_X509_new` version?

**Comment by omajid** [comment]
@dagood adding https://github.com/dotnet/runtime/pull/43039 to `patches/runtime` fixed the build locally for me.

**Comment by dagood** [comment]
Works for me too, thanks! Leaving this issue open to track getting https://github.com/dotnet/runtime/pull/43039 merged rather than keeping the patch into 5.0.0+.

**Comment by jeffschwMSFT** [comment]
@danmosemsft I think we should consider this one for GA

**Comment by danmosemsft** [comment]
@dagood it sounds like you agree. I see the value, I do not know the risk. @jeffhandley is there someone who handle this one?

**Comment by jeffhandley** [comment]
@krwq Could you take a look at this please?

**Comment by bartonjs** [comment]
Without the fix the build is broken on distros that have OpenSSL 1.0.x headers. https://github.com/dotnet/runtime/pull/43039 fixes it for master, we just need to backport it to release/5.0.  (I just restarted the timed out PR leg)

**Comment by jeffhandley** [comment]
Ah, marvelous -- thanks, @bartonjs!
