### ISSUE TITLE
LINQ IEnumerable extension method optimization

### ISSUE THREAD

**Issue by HermanSchoenfeld** [dotnet/runtime#43001]
LINQ IEnumerable extension methods should add special case IReadOnlyCollection\<T\.

For example, this line https://github.com/dotnet/runtime/blob/271f008f0fe8168dacac45cd3ce1952e6e32bfbb/src/libraries/System.Linq/src/System/Linq/Count.cs#L18

shows an optimization for ICollection\<TSource\>, yet IReadOnlyCollection\<TSource\> will result in a full iteration.

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/issues/42254#issuecomment-692964530

**Comment by stephentoub** [comment]
Closing as dup of #42254. Thanks.
