### ISSUE TITLE
NetworkChange.NetworkAvailabilityChanged No Longer Triggers

### ISSUE THREAD

**Issue by neilspink** [dotnet/runtime#43018]
### Description

The NetworkChange.NetworkAvailabilityChanged event no longer seems to get triggered when changing wifi networks.

```
using System;
using System.Net.NetworkInformation;

namespace ApplicationBridgeTestConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            NetworkChange.NetworkAddressChanged += NetworkChange_NetworkAddressChanged;
            NetworkChange.NetworkAvailabilityChanged += NetworkChange_NetworkAvailabilityChanged;
            Console.WriteLine("Hit any key to exit.");
            Console.ReadKey();
        }

        private static void NetworkChange_NetworkAvailabilityChanged(object sender, NetworkAvailabilityEventArgs e)
        {
            Console.WriteLine($"NetworkAvailability Changed: IsAvailable = {e.IsAvailable}");
        }

        private static void NetworkChange_NetworkAddressChanged(object sender, EventArgs e)
        {
            Console.WriteLine($"Network Address Changed");
        }
    }
}
```

### Configuration

.NET Framework 4.7.2
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041

**Comment by danmosemsft** [comment]
@neilspink this repo is for issues in .NET Core / .NET 5. Does this issue occur in that product?

If not, please open an issue at https://developercommunity.visualstudio.com/spaces/61/index.html
You mentioned this used to work - it would be good if you could add info about whether you had a Windows update, or a .NET Framework update? Windows changes more than .NET Framework so most likely it is Windows related. Perhaps you can help bisect the Windows update if any, or test on another machine?

**Comment by neilspink** [comment]
Nope, neither, so I guess this aint of any interest to you guys.
