### ISSUE TITLE
Multi-threading bugs in System.IO.Packaging

### ISSUE THREAD

**Issue by jr01** [dotnet/runtime#43012]
### Description

Our CI build intermittently fails on tests that process an Excel xlsx. We are using [ClosedXml](https://github.com/ClosedXML/ClosedXML) that uses [Open-XML-SDK](https://github.com/OfficeDev/Open-XML-SDK) that uses System.IO.Packaging.Package. Our unit tests are run concurrently.

We see multiple different exceptions, but they are all XmlException's. One example:
```
System.Xml.XmlException: Unknown xsi:type for DateTime on 'dcterms:created'. Line 1, position 276.
   at System.IO.Packaging.PartBasedPackageProperties.ValidateXsiType(XmlReader reader, Object ns, String name)
   at System.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(PackagePart part)
   at System.IO.Packaging.PartBasedPackageProperties.ReadPropertyValuesFromPackage()
   at System.IO.Packaging.PartBasedPackageProperties..ctor(Package package)
   at System.IO.Packaging.Package.get_PackageProperties()
   at ConsoleApp1.Program.ReadPackage() in ...
```

I have found steps to reproduce. Consider this simple program.
```
class Program
{
	static void Main(string[] args)
	{
		Parallel.For(1, Environment.ProcessorCount, (i) => ReadPackage());
	}

	private static void ReadPackage()
	{
		using var ms = File.OpenRead(@"package.xlsx"); // Any valid Package, e.g. Excel .xlsx

		using var package = Package.Open(ms, FileMode.Open, FileAccess.Read);

		// Trigger parsing some XML inside the package.
		// Note: this is just 1 of the places in Package where XML parsing is done.
		_ = package.PackageProperties;
	}
}
```
	
This program intermittently crashes. Also (and I'm not yet sure why) sometimes it hangs.

This can be easily demonstrated with the following batch file:
```
@echo off
cls
:begin

@echo Run @ %date% %time%
dotnet bin\Debug\netcoreapp3.1\ConsoleApp1.dll

IF %ERRORLEVEL% NEQ 0 goto :end

goto :begin
:end
```

Usually within a few seconds, sometimes up to a few minutes a crash or hang occurs.

### Configuration

* Which version of .NET is the code running on?   Have repeated the issue in .net 4.5.2, .net 4.7.2, .net core 2.0 up to .net5. So probably all .NET versions..
* What OS and version, and what distro if applicable? Windows.  Haven't been able to reproduce on WSL.
* What is the architecture (x64, x86, ARM, ARM64)?  x64
* Do you know whether it is specific to that configuration? I don't believe it to be specific to the configuration.

### Regression?

Probably exists in all .NET core versions that ship with System.IO.Packacing

### Other information

I think I have narrowed the problem down to System.IO.Packaging.Package using the non-thread safe [System.Xml.NameTable](https://source.dot.net/#System.Private.Xml/System/Xml/NameTable.cs,13) in a static https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/PackageXmlStringTable.cs,16 . 

To find the root cause I have created a program with a heavily stripped down implementation of the XML processing that is done in: https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/PartBasedPackageProperties.cs,475

```
class Program
{
	private static readonly NameTable s_nameTable = new NameTable();
	private static readonly object s_core_props;

	static Program()
	{
		s_nameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
		s_nameTable.Add("xsi");
		s_nameTable.Add("xmlns");
		s_core_props = s_nameTable.Add("http://schemas.openxmlformats.org/package/2006/metadata/core-properties");
		s_nameTable.Add("http://purl.org/dc/elements/1.1/");
		s_nameTable.Add("http://purl.org/dc/terms/");
		s_nameTable.Add("dc");
		s_nameTable.Add("dcterms");
		s_nameTable.Add("coreProperties");
		s_nameTable.Add("type");
		s_nameTable.Add("creator");
		s_nameTable.Add("identifier");
		s_nameTable.Add("title");
		s_nameTable.Add("subject");
		s_nameTable.Add("description");
		s_nameTable.Add("language");
		s_nameTable.Add("created");
		s_nameTable.Add("modified");
		s_nameTable.Add("contentType");
		s_nameTable.Add("keywords");
		s_nameTable.Add("category");
		s_nameTable.Add("version");
		s_nameTable.Add("lastModifiedBy");
		s_nameTable.Add("contentStatus");
		s_nameTable.Add("revision");
		s_nameTable.Add("lastPrinted");
	}

	static void Main(string[] args)
	{
		Parallel.For(1, Environment.ProcessorCount, (i) => ParseXML());
	}

	private static void ParseXML()
	{

		var payload = @"<?xml version=""1.0"" encoding=""utf-8""?>
<coreProperties 
xmlns:dc=""http://purl.org/dc/elements/1.1/"" 
xmlns:dcterms=""http://purl.org/dc/terms/"" 
xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" 
xmlns=""http://schemas.openxmlformats.org/package/2006/metadata/core-properties"">
<dcterms:created xsi:type=""dcterms:W3CDTF"">2020-08-28T05:33:18.5018199Z</dcterms:created>
<dcterms:modified xsi:type=""dcterms:W3CDTF"">2020-08-28T05:33:18.5018216Z</dcterms:modified>
</coreProperties>";
		using var stream = new MemoryStream(Encoding.UTF8.GetBytes(payload));

		XmlReaderSettings xrs = new XmlReaderSettings();
		xrs.NameTable = s_nameTable;

		using XmlReader reader = XmlReader.Create(stream, xrs);
		var nodeType = reader.MoveToContent(); // move to coreProperties

		if (!ReferenceEquals(reader.NamespaceURI, s_core_props))
		{
			// Notice: normally count is '30', but in the multi-threaded bug it's gets larger than 31
			// causing the internal NameTable to `Grow()`.

			var fi = s_nameTable.GetType().GetField("_count", BindingFlags.NonPublic | BindingFlags.Instance);
			var count = (int)fi.GetValue(s_nameTable);

			// This is the issue -- this object comparing is all over the place.
			throw new XmlException($@"CorePropertiesElementExpected: 
					Count          = {count}
					Type           = {nodeType}
					Expected Value = {s_core_props}
					Actual   Value = {reader.NamespaceURI}");
		}
	}
}
```

I believe the reason it fails is because from various places strings are added to the (static) NameTable.
One of those palces is https://source.dot.net/#System.Private.Xml/System/Xml/Core/XmlTextReaderImpl.cs,388 and I guess in System.IO.Packaging there exist more places.

Because the XML reading code is called from multiple threads, some/all threads can come to the conclusion that a string isn't yet in the NameTable and add them. 

A solution could be to use an thread-safe XmlNameTable implementation like the one here: https://github.com/dotnet/msbuild/blob/aed5e7ed0b7e031d3e486c63b206902bf825b128/src/Build/ElementLocation/XmlNameTableThreadSafe.cs, I have tested this with the above code and haven't been able to reproduce the problem.

A workaround for us is to not run tests in parallel. In production this issue is very unlikely to occur.

**Comment by adamsitnik** [comment]
@jr01 big thanks for a very detailed bug report! I've fixed it in #56367. it's going to be a part of .NET 6 RC1
