### ISSUE TITLE
ClientWebSocket sends malformed payload - .net 4.7.2 and 4.8

### ISSUE THREAD

**Issue by marto83** [dotnet/runtime#43033]
### Description

When using the System.Net.WebSockets.ClientWebSocket with payloads of about 80kb and sending between 30 and 50 messages per second, eventually the client starts sending malformed payloads and the connection is aborted by the server. This only occurs in .net framework and I haven't managed to replicate it with .net core 3.1 and up.

It's also necessary to have some network latency as I cannot replicate the same issue when the client and server are both on the same machine. You can find a small repo with a client and a server that reproduces the issue. Repository: https://github.com/marto83/websocket-error

What I'm seeing are malformed payloads followed by incorrect websocket messages. Here is a screenshot from Fiddler:
![image](https://user-images.githubusercontent.com/150508/95095055-7b122000-0722-11eb-9386-840258c5a43b.png)

### Configuration

* .NET version: 4.7.1, 4.7.2 and 4.8
* OS Windows 10 Pro -> 10.0.19041 Build 19041
* Architecture -> x64
* I don't think it's specific to that configuration

### Regression?

It works fine with .Net Core

### Other information

Linked to Ably.io issue https://github.com/ably/ably-dotnet/issues/446

**Comment by jeffschwMSFT** [comment]
@marto83 thanks for sharing feedback.  Can you file this on vs feedback?  We track most of our .NET Framework feedback via that channel.  Once you have it filed please link it back to this issue.

**Comment by wfurt** [comment]
closing as core works fine.
