### ISSUE TITLE
Dotnet publish produces weird warning

### ISSUE THREAD

**Issue by KernelErr0r** [dotnet/runtime#43059]
### Description

Command ``dotnet publish -r linux-x64 -c release -p:PublishReadyToRunShowWarnings=true`` produces a weird warning:
```
RUNREADYTORUNCOMPILER : warning : Method not found: 'Void Microsoft.Cci.ISymUnmanagedWriter7._VtblGap1_33()'. while resolving 0x600032d - Microsoft.Cci.ISymUnmanagedWriter7._VtblGap1_33. [/home/runner/work/AudioSensei/AudioSensei/AudioSensei/AudioSensei.csproj]
```

As far as I know, this issue is specific at least to Linux (it doesn't happen on Windows)

### Configuration

Ubuntu 18.04 / .NET Core 3.1 / x64

### Other information

https://github.com/KernelErr0r/AudioSensei/pull/14/checks?check_run_id=1205984110 // Linux
https://github.com/KernelErr0r/AudioSensei/pull/14/checks?check_run_id=1205984101 // Windows
https://github.com/MichalPetryka/AudioSensei/tree/patch-1

**Comment by jkoritzinsky** [comment]
This was fixed by #40404. The fix is in .NET 5.0 RC1 and onwards.
