### ISSUE TITLE
Building .NET 5 windows app fails on latest builds of NanoServer container

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#43057]
.NET 5 port of bug https://github.com/dotnet/runtime/issues/42443

NanoServer container changed behavior and `BeginResourceUpdate` now returns `ERROR_CALL_NOT_IMPLEMENTED` on platforms where it's not supported. SDK has code detect this situation, but it expects different behavior than this error code (the old behavior).

Without this change trying to build any windows application on the NanoServer container fails. The only workaround is to disable building the `.exe` via `UseAppHost=false`.

**Comment by jeffschwMSFT** [comment]
Closed with https://github.com/dotnet/runtime/pull/43058
