### ISSUE TITLE
NO_WAY macro in JIT

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#43067]
The NO_WAY macro is used in the JIT primarily to represent issues in the JIT where either the JIT has failed due to invalid IL code provided to it, or when the JIT has some bug that places the JIT into an invalid state. Currently, the crossgen2 compiler is configured to fail to build if a NO_WAY is encountered unless the --resilient switch is passed to it. (The --resilient switch is passed to the compiler by default by the SDK for customer scenarios.)

However, there is at least one location where the JIT uses a NO_WAY to protect against code while valid, overflows some limit in the jit. See (https://github.com/dotnet/runtime/blob/6b84a7490365cc6918ac7f0f93fe71b3f2fe451c/src/coreclr/src/jit/lclvars.cpp#L404)

I'd like to add a new macro, ... call it NO_WAY_VALIDCODE which would cause the JIT to return an error code which is different from a normal NO_WAY so that crossgen2 can ignore that method and instead allow any failure to occur at runtime instead of at compile time.

I'm looking for some buyoff from the jit team before I do this.

**Comment by BruceForstall** [comment]
You could argue this case should use `IMPL_LIMITATION` instead.

**Comment by davidwrighton** [comment]
Ah, I didn't know of `IMPL_LIMITATION` ... yes, this should be `IMPL_LIMITATION`, but the issue about the return code remains. So I guess, I'd like to see an observable difference between `NO_WAY` and `IMPL_LIMITATION`.

**Comment by davidwrighton** [comment]
If I made the jit return `CORJIT_IMPLLIMITATION` would that be a concern?

**Comment by BruceForstall** [comment]
> If I made the jit return CORJIT_IMPLLIMITATION would that be a concern?

I _think_ that would be ok. There is some special handling with the current `CORJIT_INTERNALERROR`. In particular, I _think_ we will retry the compilation with minopts. (We definitely do for noway_assert). For some of these NO_WAY, that wouldn't make sense, in which case it should actually be retried. But if we hit a NO_WAY during optimization but not during minopts, we want to do the minopts to not block customers.

**Comment by davidwrighton** [comment]
Ah, that's a bit more subtle than I noticed. For some reason, I misread the code and thought that noWay sent `CORJIT_BADCODE`. Oops. Let me adjust my PR.

**Comment by davidwrighton** [comment]
Actually, I adjusted IMPL_LIMITATION, which used to use NO_WAY. From what I can see NO_WAY does not generate a `CORJIT_RECOVERABLEERROR`, that's restricted to `NOWAY_MSG`.  I am confused though, as it appears that some of these limitation should be recoverable, and some might be a bad idea to recover from.
