### ISSUE TITLE
Monitor.Wait consumes much more CPU time on Linux compared to Windows

### ISSUE THREAD

**Issue by mg90707** [dotnet/runtime#43063]
### Description
I have a program which repeatedly call Monitor.Wait in relatively quick succession (every couple of milliseconds). Either through own code or internally (e.g. through Socket.Receive->ManualResetEventSlim). After containerizing the program or when running it directly in WSL2 I've noticed that it consumes MUCH more CPU time than on Windows. On Windows the CPU time is basically zero, but in WSL2 or docker the CPU time is pretty significant with 5-10%. I've made traces with dotnet-trace and Jetbrains Dottrace and both point to Monitor.Wait or other asynchronous constructs which probably call Monitor.Wait internally (ManualResetEventSlim etc.).

The most simple program that somewhat reproduced the issue is a simple console application with the following main function:

    public static void Main(string[] args)
    {
        var obj = new object();
        Task.Run(() => {
            while(true){
                lock(obj) {
                    Monitor.Pulse(obj);
                }
                Thread.Sleep(1);
            }
        });

        while(true) {
            lock (obj) {
                Monitor.Wait(obj);
            }
        }
    }

On Windows I can run this program without any noticable CPU consumption (0-0.5%). In WSL2/Docker however this consumes about 5-10%.

### Configuration

* Which version of .NET is the code running on?
.NET Core 3.1, I also tried .NET 5.0 in Docker, but the isssue remained
* What OS version, and what distro if applicable?
Windows10 2004; WSL2@Ubuntu20.04; Docker Desktop 2.4.0.0 @ WSL2, but I've also tried the "legacy" Hyper-V backend which pretty much gave the same results
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* If relevant, what are the specs of the machine?
Core i7 7700HQ; 32GB RAM
Limits for WSL2: 4 Processors; 8GB RAM

The issue was confirmed on another machine running Windows 10 1803 and Docker 2.3.0.3.

In the attached image you can see a PerfView visualization of the dotnet-trace that shows that pretty much all time is spent in unmanged code and that the callers that spent a significant time there are mostly related to the Monitor class, Async code etc.
![monitor_wait_unmanaged_code_time](https://user-images.githubusercontent.com/43848015/95134007-740b0200-0762-11eb-9e41-e14a668b7333.png)

**Comment by stephentoub** [comment]
I'm curious what happens if you change the `Thread.Sleep(1);` to `Thread.Sleep(15);`?  It's essentially the latter on Windows because of how time quantums work, whereas on Linux it'll be much closer to 1ms when you specify 1.  So for apples to apples, it'd be interesting to see the results with both being closer to 15ms.

**Comment by mg90707** [comment]
It seems that my conclusion was a bit premature as to what exactly causes the problem. I did a timeline trace with dottrace on Windows and as expected the application threads are waiting (suspended) for for data from the remote endpoint almost all the time and the CPU load is accordingly. This should be the same under Linux.

I don't understand however, why the CPU load is so high under WSL2 then. I'm setting up a PC with a bare metal installation of Ubuntu now and will check if the CPU load is as expected there. Maybe this will give me some more insight. Whats interesting is that this issue only occurs on my .NET containers that are all waiting for network traiffic most of the time. My eclipse-mosquitto and my postgresql container, which the .NET containers are communicating with, don't have the issue with unexpectedly high CPU load.

I will close the issue for now, until I can pinpoint it more exactly.
