### ISSUE TITLE
Allow for logging any swallowed exception in the DI background thread

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#43083]
We want to allow for logging of any swallowed exception to happen via the event source, if an exception occurs during the execution of a background thread for resolving DI dependencies.

Refer to https://github.com/dotnet/runtime/pull/42986#discussion_r499069959

**Comment by davidfowl** [comment]
We already have an event source [here](https://github.com/dotnet/runtime/blob/f39d544d6dcbeaf2093657336b06f8712e9b3f6b/src/libraries/Microsoft.Extensions.DependencyInjection/src/DependencyInjectionEventSource.cs#L13). We should add a log here https://github.com/dotnet/runtime/blob/f39d544d6dcbeaf2093657336b06f8712e9b3f6b/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs#L39
