### ISSUE TITLE
No response from EventPipe in a reasonable time with Release configuration of .NET 5 application

### ISSUE THREAD

**Issue by valco1994** [dotnet/runtime#43094]
When I'm using EventPipe to collect events from .NET 5 application built in Release configuration on Windows, sometimes it occurs, that I successfully connect to the corresponding named pipe and send IpcMessage with `CollectTracing2`, but don't receive a response in a reasonable time (20 seconds for example).

If I close the connection and try to reconnect, it's failed to reconnect because the named pipe doesn't exist.

**Comment by valco1994** [comment]
@sywhang @josalem

**Comment by josalem** [comment]
Can you describe setup that causes this a little more?  Specifically, what version of .net5.0 are you using?  How consistently does this behavior happen?

Do you have a consistent repro you can share?

**Comment by valco1994** [comment]
@josalem It is reproduced only on .NET 5 RC 1 for me, I never saw something similar on .NET Core 3.0 or .NET Core 3.1. It's happening not very often, but regularly. It's quite hard for me to evaluate the frequency properly now, I'll try to do it later. 

I'm using the following simple test app to collect events from, but I don't think that it relates to the issue.

```{c#}
using System;  

namespace Tests  {   
  static class Program  {     
    static void Main(string[] args)  {       
      Console.Readline();
      for (var i = 0; i < 10; ++i)  {
         try {           
          throw new Exception($"[{i}] Shit happens...");        
        }  catch (Exception e)         {          
          Console.WriteLine(e);        
        }
       } 
    }
   }
 }

```

**Comment by josalem** [comment]
Hmmm, interesting.  I'll try modifying one of the tests or writing a simple one to have a timeout on connection and running it in a loop locally.

Is this on a particular architecture by chance?

**Comment by josalem** [comment]
BTW I experimented with a simple console app targeting win-x86 and win-x64 and I couldn't repro this behavior.  I believe you that it is happening, but I can't seem to make it happen.

Please let me know if you find a consistent repro or more details on how to trigger it 😄.

**Comment by valco1994** [comment]
@josalem, I collect statistics about this issue and found that actually, it happens not only on Release builds but on Debug too, more frequent on x64 than on x86:

- x64, Release - 12 fails in 1309 runs
- x64, Debug  - 13 fails in 1300 runs
- x86, Release - 10 fails in 1292 runs
- x86, Debug - 6 fails in 1296 runs

I don't know if it relates, but I'm using Mono Runtime to run tests and `System.Diagnostics.Process` API to launch both test application (self-contained, published for net5.0 with .NET 5 RC 1) and my EventPipe client.

**Comment by valco1994** [comment]
I will investigate it further and write here if some new details will be found

**Comment by josalem** [comment]
Let me know if you come up with any repro steps and we can reopen this issue :smile:.

**Comment by valco1994** [comment]
Ok
