### ISSUE TITLE
JsonConverter: calling default converter in custom converter

### ISSUE THREAD

**Issue by yongkeecho** [dotnet/runtime#43096]
Hi. Thanks for the great library. This can be an API suggestion if not available yet.
An API endpoint gives
`
{
      "propA" : {
              "prop1": "prop1Value",
              "prop2": [ 1, 2, 3]
      },
      "propB": [
          {
              "prop1": "prop1Value",
              "prop2": ["prop2Value1", "prop2Value2"]
          }
      ]
}
`
I already have class B
`
public class B
{
   public string Prop1 { get; set; }
   public IList<string> Prop2 { get; set; }
}
`
and I just need IList<B> part. So instead of implementing a class corresponding the API response, I want to get it using JsonConverter<IList<B>> as below:
`
public override IList<B> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
{
     var bs = new List<B>();
     while (reader.Read() && reader.TokenType != JsonTokenType.EndObject)
     {
          var propertyName = reader.GetString();
          if (propertyName == "prop2")
          {
               if (bConverter != null)
                        bs.Add(bConverter .Read(ref reader, typeof(Collection), options));
                }
            }
            return bs;
        }
`
My question is can we generate a converter bConverter from existing type B?

**Comment by yongkeecho** [comment]
Never mind. I found I can use JsonSerializer.Desrialize with reader in the middle of custom converter.
`
var b = JsonSerializer.Deserialize(ref reader, typeof(B), options)
`

**Comment by layomia** [comment]
@yongkeecho - the other thing you can do is call `options.GetConverter(typeof(B))`. Starting in .NET 5, this method will return a compatible `JsonConverter` instance, or throw `NotSupportedException` if the type is not supported and there's no custom converter present.
