### ISSUE TITLE
Compose the shared framework without depending on OOB libraries

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#43118]
Part of the shared framework are shims, generated and manual ones. The [generated shims require all reference assemblies](https://github.com/dotnet/runtime/blob/bb3cf17981b506d22be5b8e1f06084c958372e1d/src/libraries/shims/generated/Directory.Build.props#L32-L36) (both inbox and OOB ones) as an input whereas the [manual shims require all implementation assemblies](https://github.com/dotnet/runtime/blob/bb3cf17981b506d22be5b8e1f06084c958372e1d/src/libraries/shims/manual/Directory.Build.props#L19-L25) (again both inbox and OOB) as an input.

There are various reasons for a clear cut between the shared framework and OOB libraries:
1. Being able to build the shared framework is more often interesting than building OOBs (Microsoft.Extensions.* and Compat projects) for runtime developers.
2. Being able to just build the Microsoft.Extensions.* libraries incrementally and produce packages for them is more often interesting for developers that came from dotnet/extensions.
3. OOBs don't need to live next to the shared framework and could eventually be moved to another location.

cc @ericstj @safern @Anipik @jkotas

**Comment by eerhardt** [comment]
> Being able to just build the Microsoft.Extensions.* libraries incrementally and produce packages for them is more often interesting for developers that came from dotnet/extensions.

Would this mean a dev could work on the Microsoft.Extensions.* libraries without building the whole runtime? Also, would it mean they could run unit tests as well without building the rest of the runtime?

**Comment by ViktorHofer** [comment]
> Would this mean a dev could work on the Microsoft.Extensions.* libraries without building the whole runtime? Also, would it mean they could run unit tests as well without building the rest of the runtime?

You can already build a library without building the BCL beforehand as long as it doesn't have a `$(NetCoreAppCurrent)` configuration. If it has one and you are fine with (if available) the .NETStandard, .NETFramework or an older .NETCoreApp tfm, you can build the library just for that desired tfm via the `dotnet build -f` switch, i.e. `dotnet build -f netstandard2.0`. Building the `$(NetCoreAppCurrent)` tfm requires the targeting pack to be available which requires a root build today.

If we would have a contract between OOBs and the targeting pack (i.e. via a ProjectReference) we would be able to build OOBs without any upfront steps. What makes this non trivial is to make the dependency on the targeting pack performant. The targeting pack should only be (incrementally) built if something changed as unconditionally incrementally building the entire targeting pack is far too slow.

> Also, would it mean they could run unit tests as well without building the rest of the runtime?

Running unit test requires **a** runtime. For .NETFramework, one is already available on the developer's machine (if on Windows). Same for older .NETCoreApp configurations (if the shared framework is installed on the developer's globally installed SDK). To run `$(NetCoreAppCurrent)` compiled test assemblies, you require the live shared framework and the live runtime to be built.

**Comment by ViktorHofer** [comment]
Closing as you can already build `libs.sfx` which just builds the shared framework partition without any OOBs.
