### ISSUE TITLE
How to strong name sign System.Security.Cryptography.Cng

### ISSUE THREAD

**Issue by varunmankal** [dotnet/runtime#43127]
How to strong name sign the System.Security.Cryptography.Cng package using my key ?

I built the 4.5.0 version of the System.Security.Cryptography.Cng package on ubuntu machine. I am not able to strong name sign it ?
It looks like the build command pulls the signing tool and the keys on the fly and does delay signing. 

Why the System.Security.Cryptography.Cng package present in the nuget is not strong name signed ? Is it not required to load the package in .NET Framework ?

**Comment by krwq** [comment]
@varunmankal have your read https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md ? Why do you need to strong name sign it in the first place?

**Comment by varunmankal** [comment]
yes, I went through that. 

Our library which targets at .NET Standard 2.0 uses `System.IdentityModel.Tokens.Jwt ` package as a dependency and a internal team uses our library. The internal team's application targets at 4.7.2 .NET Framework. 
We have a requirement that all the third party packages and its dependencies need to be built on our machines and strong name sign it using our key. So, I was able to build and strong name sign the `jwt` package and its dependencies except `Microsoft.CSharp` and `System.Security.Cryptography.Cng`. 

I came to know that the `Microsoft.CSharp` is not needed to strong name sign because it comes with .NET Framework. 
one question to clarify, I see that the `Cng` package present in nuget is not strong name signed. How will it get loaded into Global assembly cache used by .NET Framework ?

**Comment by varunmankal** [comment]
@krwq can you please check this.

**Comment by krwq** [comment]
@varunmankal the strong name signature is not considered a security feature anymore... @ViktorHofer do you know if there is some easy way to plug @varunmankal's key into the build to strong name sign our binaries with his key? Any reason why do we not sign Linux binaries?

**Comment by varunmankal** [comment]
@krwq Is it not required to strong name sign the libraries to load into GAC ?

**Comment by krwq** [comment]
@varunmankal you can use `sn -Vr <yourassembly>` from developer command prompt (also part of .NET tools from Windows SDK) to disable verification for your library. That will allow it to be loaded into GAC

**Comment by krwq** [comment]
@varunmankal were you able to solve your issue?

**Comment by bartonjs** [comment]
Since we haven't had any activity here since October, closing the issue.
