### ISSUE TITLE
[Question] Why HttpResponseMessage calls GC.SuppressFinalize if it doesn't have a finalizer?

### ISSUE THREAD

**Issue by Kamil-Zakiev** [dotnet/runtime#43133]
Hello, 
Could you please clarify why HttpResponseMessage calls GC.SuppressFinalize during Dispose if the class doesn't have a finalizer?

As I understand, GC won't finilize an object that doesn't have a finalizer

https://github.com/dotnet/runtime/blob/d6887d4aeec045aa4d708463abdfb6e071660dc8/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L242

**Comment by gfoidl** [comment]
See https://github.com/dotnet/runtime/issues/42183 for a discussion about this topic.

In essence it's about sub-classing and that a sub-class may have a finalizer.

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
