### ISSUE TITLE
Does  CoreCLR use multiple finalizer threads  now?

### ISSUE THREAD

**Issue by Sparklix** [dotnet/runtime#43142]
In 《CLR via C#》4th page 526,I read this.
![image](https://user-images.githubusercontent.com/51604064/95355307-f973eb00-08f7-11eb-8300-3600b65921b8.png)

Or
Does CoreCLR use some way to solve deadlock now？
Does CoreCLR use some way to solve  leak memory now？Thanks.

**Comment by jkotas** [comment]
> Does CoreCLR use multiple finalizer threads now?

No.

We do not see the single finalizer thread as performance bottleneck.
