### ISSUE TITLE
WebSockets won't close properly on Linux

### ISSUE THREAD

**Issue by DierkDroth** [dotnet/runtime#43157]
Hi,

I have a websocket server on a Amazon Web Services Linux machine (EC2) and am experiencing that websockets are not closed properly at the server but are kept 'open'.

- build and run attached server on a Linux machine hosting .NET Core 3.1 as per below
- build and run attached client on any .NET Core 3.1 host
- after closing the websocket in the client by typing "quit" at the prompt check the server:
-- "sudo ps -ax | grep dotnet" to find the process ID of the server process
-- "sudo lsof -p <process-id> | grep TCP" to see that the socket at the server still is there. First it would stay in CLOSE_WAIT, ultimately it would not close

The Linux machine hosting the server is configured as per below.

Any idea what am I doing wrong here?

Thanks in advance

[ClientServer.zip](https://github.com/dotnet/runtime/files/5345054/ClientServer.zip)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by stephentoub** [comment]
@dotnet/ncl, the cited issue here is with HttpListener.

**Comment by danmosemsft** [comment]
@DierkDroth  I’m not familiar with this issue, but you might try with 5.0 just to see whether the behavior is the same: https://dotnet.microsoft.com/download/dotnet-core

**Comment by DierkDroth** [comment]
True, that's an option. However, as long as 5.0 is not out yet officially and AWS would not officially support it I would have to stick with 3.1

**Comment by wfurt** [comment]
that may come to past faster than any other option @DierkDroth 
Also that may bring some valuable information if the behavior is different.

**Comment by DierkDroth** [comment]
I suggest the MS team tried the simple-as-possible scenario I crafted to see if the issue is reproducible (3.1 and/or 5.0).

**Comment by karelz** [comment]
@DierkDroth we are trying to juggle quite a few investigations, that's why we often ask folks to help narrow down their problems first. Your minimal repro is definitely appreciated.

I wonder if `context.Response.Close();` has to be called after the `webSocket` is disposed. Or is the WebSocket supposed to take care of that?

BTW: I assume there is nothing specific with AWS and that similar problem would happen on local Linux VM. Also, I assume you can work around the 5.0 support by making your app self-contained. You don't need the VM to have the specific .NET 5.0 version installed.

**Comment by DierkDroth** [comment]
@karelz thanks that was very valuable input: in fact the issue goes way when `context.Response.Close();` is called after disposing the websocket.

This leaves the question: is this is expected usage model or would this only be a workaround for an issue/bug?

BTW: Before posting I tried `context.Response.Close();` right after `context.AcceptWebSocketAsync` ... which did not work

**Comment by karelz** [comment]
I don't have deep knowledge of `HttpListener`, but closing the response (which IMO is related to the TCP connection) is likely the expected usage model. `WebSocket` is just protocol on top of the HTTP connection, so it would feel weird for it to close also the underlying connection.

**Comment by DierkDroth** [comment]
Thanks for clarification @karelz

**Comment by danmosemsft** [comment]
@DierkDroth can this be closed now?

**Comment by DierkDroth** [comment]
Yes
