### ISSUE TITLE
Analyzer suggestion: Prefer Array.Empty over new array

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/runtime#43165]
In the majority of cases `Array.Empty<T>()` is a drop in replacement for `new T[0]` and avoids creating garbage. However the latter has better discoverability, and is quicker to type, so is often used. An analyzer could suggest replacing `new T[0]` and `new T[]{}` with `Array.Empty<T>()`, and offer a code fix to do so.

A diagnostic level of suggestion seems appropriate here, since there are some cases where you care about the identity of the array, and want to make sure it's unique.

**Comment by huoyaoyuan** [comment]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825
Or do you mean something beyond this?

**Comment by YairHalberstadt** [comment]
That looks great. I'm using VS 16.8 preview 3 and .net 5 rc 1, but I can't see the warning or code fix. Do I have to add a package?

**Comment by huoyaoyuan** [comment]
It should be built-in starting from .net 5 sdk. You just need to set the severity of CA1825 to warning in ruleset or editorconfig.

**Comment by YairHalberstadt** [comment]
In that case - I'm not sure why I'm not seeing it.

**Comment by stephentoub** [comment]
> I'm not sure why I'm not seeing it

Where are you looking for it?  It's enabled by default as at "info" level, which means it'll show up as a suggestion in Visual Studio rather than as a warning/error in a command-line build.

I just tried:
- Create new .NET 5 console app
- Add a `new int[0]` in the code
- Look in the suggestions in the Error List, and it shows up (also if I ctrl+. on the line containing the allocation).

**Comment by stephentoub** [comment]
> Is it still worth keeping this ticket open?

I don't think so, but if you continue having trouble with it, please feel free to re-open.  Also if you figure out what the problem was, maybe post a follow-up here in case others hit the same snag.  Thanks.
