### ISSUE TITLE
Add System.Math.SinCos(..) or teach the JITter to calculate Sin and Cos together.

### ISSUE THREAD

**Issue by RaceRalph** [dotnet/runtime#43169]
## Background and Motivation

Sin and Cos often need to be calculated together, which is a very long operation, because they have to be calculated spearately.  In some scientific calculations (e.g. my current project) this may create a bottleneck.
The FSINCOS instruction has been there since 387 and it practically halves the time necessary to calculate Sin and Cos together.   Unfortunately there is no way of accessing it from C#.    .NET is nearly 18 years old and still no SinCos method in sight.

## Proposed API

Introduce System.Math.SinCos(..) and System.MathF.SinCos(..) methods.
There are three options:
```c#
public static partial class Math
{
    public void SinCos(double x, out double sin, out double cos);  // Matches C++ definition, but uses out rather than pointers
    public double SinCos(double x, out double cos);                // Most similar to other existing multi-return APIs we expose
    public (double Sin, double Cos) SinCos(double x);              // Matches what I believe to be the preferred API going forward
}

public static partial class MathF
{
    public void SinCos(float x, out float sin, out float cos);  // Matches C++ definition, but uses out rather than pointers
    public float SinCos(float x, out float cos);                // Most similar to other existing multi-return APIs we expose
    public (float Sin, float Cos) SinCos(float x);              // Matches what I believe to be the preferred API going forward
}
```
My personal vote goes for the third option - the cleanest and matching the newest trends in the language.

## Risks

Both Sin and Cos should be calculated with maximum possible precision.   Speed is important, but precision is fundamental.

**Comment by EgorBo** [comment]
`fsincos` is x87? 

clang(LLVM) seems doesn't do anything special for the case when we need to compute both cos and sin for the same angle at once: https://godbolt.org/z/aajjoG (gcc emits a call to sincos)

**Comment by am11** [comment]
We can use `sincos(3)` to make clang emit call to sincos built-in: https://godbolt.org/z/jh1Yaf.

**Comment by tannergooding** [comment]
This is a case where `sincos` is a fairly common API but which is not part of the C standard library and so we may not be able to always rely on the libm implementation exposing it (I don't believe the MSVC Runtime does, for example).

We would need to have a fallback implementation for such a scenario or maintain our own implementation (either in native or managed). CC. @jkotas, @jeffhandley

**Comment by jkotas** [comment]
> This is a case where sincos is a fairly common API but which is not part of the C standard library

Is the available in the C library on Windows, Linux and macOS?

**Comment by tannergooding** [comment]
It is available in Linux and macOS under the default libm implementation.

On Windows, under `fp:fast`, it recognizes the pattern of `sin(x); cos(x);` and replaces it with a call to the internal `___libm_sse2_sincos_` function.

https://godbolt.org/z/ev638x

**Comment by am11** [comment]
On macOS, it is available as `__sincos`.

```c
// pal_sincos{f} for mac, linux and win

#ifndef _MSC_VER
#define _GNU_SOURCE
#endif

#include <math.h>

#ifdef __APPLE__
#define pal_sincos(x, s, c) __sincos(x, s, c)
#define pal_sincosf(x, s, c) __sincosf(x, s, c)

#elif defined(_MSC_VER)
#define pal_sincos(x, psin, pcos) \
    *psin = sin(x);               \
    *pcos = cos(x)
#define pal_sincosf(x, psin, pcos) \
    *psin = sinf(x);               \
    *pcos = cosf(x)

#else
#define pal_sincos(x, s, c) sincos(x, s, c)
#define pal_sincosf(x, s, c) sincosf(x, s, c)
#endif // __APPLE__
```

**Comment by tannergooding** [comment]
@RaceRalph, you would need to update the original issue to have a proposed additional surface area before I can mark this `api-ready-for-review`.

I would suspect that the right surface is one of the three:
```csharp
public static partial class Math
{
    public void SinCos(double x, out double sin, out double cos);  // Matches C++ definition, but uses out rather than pointers
    public double SinCos(double x, out double cos);                // Most similar to other existing multi-return APIs we expose
    public (double Sin, double Cos) SinCos(double x);              // Matches what I believe to be the preferred API going forward
}

public static partial class MathF
{
    public void SinCos(float x, out float sin, out float cos);  // Matches C++ definition, but uses out rather than pointers
    public float SinCos(float x, out float cos);                // Most similar to other existing multi-return APIs we expose
    public (float Sin, float Cos) SinCos(float x);              // Matches what I believe to be the preferred API going forward
}
```

By "preferred", I mean I believe it will result in the best codegen and handling with the improvements @CarolEidt is adding.

**Comment by SingleAccretion** [comment]
My vote is also for the third option, seems the cleanest both in C# and in the expected codegen.

**Comment by terrajobst** [comment]
* Seems the register allocator will optimize the tuple the best and that also seems to make the most sense, API wise:

```C#
namespace System
{
    public static partial class Math
    {
        public (double Sin, double Cos) SinCos(double x);
    }
    public static partial class MathF
    {
        public (float Sin, float Cos) SinCos(float x);
    }
}
```
