### ISSUE TITLE
excute sql command define multiple store procedure errors

### ISSUE THREAD

**Issue by thanhhactld** [dotnet/runtime#43163]
Currently, I use .net core 3.1 with Microsoft.Data.SqlClient 1.13.20136.2.
i meet error when i call this command:
my sql variable : `
create procedure [SYNC].[sp_sync_count_estimated_changes_MasterData]
    @ScopeId           uniqueidentifier,
    @LastSyncTimestamp bigint,
    @TableName         nvarchar(255)
as
  BEGIN
    BEGIN
      SELECT count(*)
      FROM LIST.MasterData A
             LEFT JOIN LIST.MasterData Parent ON Parent.Id = A.ParentId
             RIGHT JOIN LIST.MasterData__tracking T ON T.Id = A.Id
      WHERE A.MasterKey = @TableName
        and (T.last_sync_timestamp > @LastSyncTimestamp)
        AND (T.scope_id is null
               OR T.scope_id <> @ScopeId
                )
    END
  END;
go
CREATE procedure [SYNC].[sp_sync_MasterData]
@ScopeId					uniqueidentifier,
@LastSyncTimestamp		bigint,
@TableName				nvarchar(255),
@Offset int,
@Limit int
as
BEGIN
	BEGIN
		SELECT A.OldId AS Id,
           Parent.OldId AS ParentId,
					 A.Code, A.Name, A.Rank, A.Note, A.Used
			 , T.last_sync_timestamp
			 , T.last_change_datetime
			 , T.dml_action
			 , T.scope_id
		FROM LIST.MasterData A
		LEFT JOIN LIST.MasterData Parent ON Parent.Id = A.ParentId
		RIGHT JOIN LIST.MasterData__tracking T ON T.Id = A.Id
		WHERE A.MasterKey = @TableName
		and (T.last_sync_timestamp > @LastSyncTimestamp)
				AND (T.scope_id is null
				OR T.scope_id <> @ScopeId
							)
		order by T.last_sync_timestamp, A.OldId
		offset @Offset ROWS FETCH NEXT @Limit ROWS ONLY
	END
END;
`
====net core Code=======
`
var connection = (SqlConnection)_dbContext.Database.GetDbConnection();
var transaction = _dbContext.Database.CurrentTransaction?.GetDbTransaction();
var command = new SqlCommand(sql, connection);
if (transaction != null)
{
  command.Transaction = transaction as SqlTransaction;
}
command.CommandType = CommandType.Text;
await command.ExecuteNonQueryAsync();
`
=====ERROR===========
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'go'.
Must declare the scalar variable "@Offset".
Must declare the scalar variable "@Limit".
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---

**Comment by Clockwork-Muse** [comment]
This is SQL Server squawking at you, not the client libraries.  That is, your statement has errors.  I think it's actually complaining about the fact that you have two different statement delimiters here (both `;` and `go`), and only one of them should be valid.

Leaving aside any potential bugs:
 - Why do this in one statement, as opposed to two?
 - Why are these procedures, instead of views?
 - It doesn't appear that the `BEGIN` and `END` tokens are necessary at all in this scenario (at least for sufficiently recent versions of SQL Server)

**Comment by David-Engel** [comment]
As previously mentioned, this is a T-SQL syntax issue. GO needs to be on a line by itself. Stuff some new lines around GO in your sql string and it might work.

**Comment by thanhhactld** [comment]
> As previously mentioned, this is a T-SQL syntax issue. GO needs to be on a line by itself. Stuff some new lines around GO in your sql string and it might work.



> This is SQL Server squawking at you, not the client libraries. That is, your statement has errors. I think it's actually complaining about the fact that you have two different statement delimiters here (both `;` and `go`), and only one of them should be valid.
> 
> Leaving aside any potential bugs:
> 
> * Why do this in one statement, as opposed to two?
> * Why are these procedures, instead of views?
> * It doesn't appear that the `BEGIN` and `END` tokens are necessary at all in this scenario (at least for sufficiently recent versions of SQL Server)

thanks for your answer but i try to use ";" still not working. 
I try to use execute('raw_sql') then it worked .

**Comment by cheenamalhotra** [comment]
@thanhhactld 

I think you've probably hit a server-side issue here.
I can reproduce same issue with simplified version of queries in SSMS and with JDBC Driver:

```sql
CREATE PROCEDURE [Test1]
as BEGIN SELECT count(*) FROM sys.tables A END; GO;

CREATE PROCEDURE [Test2] @Offset int, @Limit int 
as BEGIN SELECT * from sys.tables ORDER by object_id offset @Offset ROWS FETCH NEXT @Limit ROWS ONLY END;
```

Creating Test2 by itself runs fine, but if it's created in order above, I get same error as you:

SSMS:
```log
.Net SqlClient Data Provider: Msg 102, Level 15, State 1, Procedure Test1, Line 2 [Batch Start Line 0]
Incorrect syntax near 'GO'.
.Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure Test1, Line 5 [Batch Start Line 0]
Must declare the scalar variable "@Offset".
.Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure Test1, Line 5 [Batch Start Line 0]
Must declare the scalar variable "@Limit".
```

JDBC:
```log
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'GO'.
```
Notr that it's treating the second procedure same as Test 1 as all the messages are speaking for "**Procedure Test1**".
I'd recommend you to execute 1 procedure at a time, and request more support from SQL Server teams on this issue.

**Comment by David-Engel** [comment]
@thanhhactld 

As I said, try adding new lines (**\r\n**) to put GO on a line by itself in your SQL and it should work:

`create procedure [SYNC].[sp_sync_count_estimated_changes_MasterData] @ScopeId uniqueidentifier, @LastSyncTimestamp bigint, @TableName nvarchar(255) as BEGIN BEGIN SELECT count(*) FROM LIST.MasterData A LEFT JOIN LIST.MasterData Parent ON Parent.Id = A.ParentId RIGHT JOIN LIST.MasterData__tracking T ON T.Id = A.Id WHERE A.MasterKey = @TableName and (T.last_sync_timestamp > @LastSyncTimestamp) AND (T.scope_id is null OR T.scope_id <> @ScopeId ) END END; \r\ngo\r\n CREATE procedure [SYNC].[sp_sync_MasterData] @ScopeId uniqueidentifier, @LastSyncTimestamp bigint, @TableName nvarchar(255), @Offset int, @Limit int as BEGIN BEGIN SELECT A.OldId AS Id, Parent.OldId AS ParentId, A.Code, A.Name, A.Rank, A.Note, A.Used , T.last_sync_timestamp , T.last_change_datetime , T.dml_action , T.scope_id FROM LIST.MasterData A LEFT JOIN LIST.MasterData Parent ON Parent.Id = A.ParentId RIGHT JOIN LIST.MasterData__tracking T ON T.Id = A.Id WHERE A.MasterKey = @TableName and (T.last_sync_timestamp > @LastSyncTimestamp) AND (T.scope_id is null OR T.scope_id <> @ScopeId ) order by T.last_sync_timestamp, A.OldId offset @Offset ROWS FETCH NEXT @Limit ROWS ONLY END END;`

**Comment by cheenamalhotra** [comment]
I also tested again, it will work as under:

```sql
CREATE PROCEDURE [Test1]
as BEGIN SELECT count(*) FROM sys.tables A END;
GO

CREATE PROCEDURE [Test2] @Offset int, @Limit int 
as BEGIN SELECT * from sys.tables ORDER by object_id offset @Offset ROWS FETCH NEXT @Limit ROWS ONLY END;
```

Disregard my old comment.

I think this issue can be then be closed as not an issue.

**Comment by cheenamalhotra** [comment]
Closing as not an issue
