### ISSUE TITLE
.NET 5: RuntimeConfig.json not Copied as build Asset

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#43168]
### Description
When a "Parent" .NET5 app references a "Child" .NET5 app, the Child's RuntimeConfig.json file is not captured as a build asset.  This prevents the Child app from properly functioning.

### Other information
Here is a sample app that demonstrates the problem:
https://github.com/TonyValenti/ProcTest

**Comment by TonyValenti** [comment]
This seems to be the issue:
https://github.com/dotnet/sdk/issues/1675

**Comment by tannergooding** [comment]
This looks to have been fixed some time back, and isn't a `System.Buffers` related issue
