### ISSUE TITLE
advapi32.dll dependency leaking in the mscorlib.dll for non-Windows systems

### ISSUE THREAD

**Issue by saper** [dotnet/runtime#4317]
It seems that `advapi32.dll` dependency is exposed in the [mscorlib.dll](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug/637/Azure/processDownloadRequest/637/bin/Product/FreeBSD.x64.Debug/mscorlib.dll) built using `freebsdmscorlib` target.

```
$ monodis --moduleref Product/FreeBSD.x64.Debug/mscorlib.dll
ModuleRef Table (1..3)
1: advapi32.dll
2: libcoreclr
3: QCall
```

Below is my theory why:

This might be because of the static reference to the `System.Diagnostics.Tracing.EventProvider/WriteEventErrorCode` from `System.Diagnostics.Eventing.EventSource::ThrowEventSourceException()` method.
And this reference keeps the private class `System.Diagnostics.Tracing.EventProvider`
around along with its disposer and the `EventUnregister` from `ADVAPI32.DLL`.

This method is probably not needed at all in the case where `FEATURE_MANAGED_ETW` is not defined.

@stephentoub @ericstj what do you think?

**Comment by jkotas** [comment]
This was fixed long time ago.
