### ISSUE TITLE
Can the gc cards handle OS pages > 8K ?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtime#43180]
At https://github.com/dotnet/runtime/blob/50ac454d8d8a1915188b2a4bb3fff3b81bf6c0cf/src/coreclr/src/gc/gcpriv.h#L5098
If I understand correctly the 32 bits in a `uint32_t` that is used for a card table entry have to cover an OS page.  Each bit represents 256 bytes, so the maximum page size that can be covered is 32 * 256, which is 8K.  If the OS page size is 16KB (as in emscripten/Wasm), then would this be a problem?

Thanks

**Comment by mangod9** [comment]
@PeterSolMS as fyi.

**Comment by PeterSolMS** [comment]
Interesting question - I'm actually not sure where in the code we rely on covering one OS page with a card_table entry. 

Given that we support large pages on Windows and Linux, I don't think we'll have major issues supporting 16kB pages as well, but we may discover some bugs along the way.

If all else fails, we can have have each card_table bit cover 512 bytes with a pretty small impact on performance.

Thanks

**Comment by Maoni0** [comment]
we don't rely on covering one page with a card_table entry (ie, a card word). on arm64 unix we are using 64k pages and each card word still covers 8k.

**Comment by yowl** [comment]
Thanks, for clearing that up, I can go on without worrying about this.
