### ISSUE TITLE
Consider updating for new TargetFrameworks

### ISSUE THREAD

**Issue by sfoslund** [dotnet/runtime#43186]
With .NET 5 we are introducing a new style of target framework that includes target platform information (for example, net5.0-windows). This change may cause conflicts with existing logic. Specifically, on
https://github.com/dotnet/runtime/blob/ad434fc578b33953c1fcf1123536ce61744bd46a/src/libraries/pkg/test/packageTest.targets#L4-L5 please consider using the `TargetFrameworkIdentifier` property directly here or if that is not possible then use the new MSBuild target framework property functions to parse this value ([see here](https://github.com/dotnet/msbuild/issues/5171#issuecomment-597422462))

**Comment by safern** [comment]
What would the value of `TargetFrameworkIdentifier` property be?

We use this to calculate which targets file to include from this folders:https://github.com/dotnet/runtime/tree/ad434fc578b33953c1fcf1123536ce61744bd46a/src/libraries/pkg/test/frameworkSettings

**Comment by sfoslund** [comment]
The value of the TargetFrameworkIdentifier would be `.NETCoreApp` for .NET Core. If you need this value to specifically be `net`, you can disregard this issue, thanks.

**Comment by ViktorHofer** [comment]
This issue is very valuable as because of I learned about these new functions. We will probably update our projects to use them. Thanks

**Comment by safern** [comment]
Yeah I agree it is very valuable to update our usages of this workaround. However in the case pointed out in the description I believe we should leave it as is given the name of the folders.

**Comment by ViktorHofer** [comment]
Jep, in https://github.com/dotnet/runtime/blob/ad434fc578b33953c1fcf1123536ce61744bd46a/src/libraries/pkg/test/packageTest.targets#L7 you can see that it actually picked up the wrong one before I noticed that 😁.

@sfoslund I'm going to close this PR as the location that you pointed to is working as expected. Thanks.

**Comment by ViktorHofer** [comment]
Both cases are fine the way they are as they intentionally exclude >= net5.0. In the second one it's either the current netcoreapp version (net6.0) or < net5.0. That said, both could be expressed better with the new functions :)
