### ISSUE TITLE
Understanding of generic-class casting performance

### ISSUE THREAD

**Issue by lsoft** [dotnet/runtime#43199]
I am trying to understand why my C # code is running slower than I expected. At dotnet/roslyn I was told that it is better to ask here :) My example is very specific because it originated in the code that is generated by the C # source generator. Such code is quite unlike human-written code.

### Description

Imagine, we have a set of classes:

```
public class Class0 {  }
public class Class1 {  }
...
public class Class999 {  }
```

and also we have a generic interface:

```
public interface IInterface<T> {  T GetNothing(); void SetNothing(T arg); }
```

and we have a superclass like the following:

```
public class Implementer1000 : IInterface<Class0> ,IInterface<Class1>, ... , IInterface<Class999>
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    Class0 IInterface<Class0>.GetNothing()
    {
        return default(Class0);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void IInterface<Class0>.SetNothing(Class0 arg)
    {
        //nothing to do
    }

...


    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    Class999 IInterface<Class999>.GetNothing()
    {
        return default(Class999);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void IInterface<Class999>.SetNothing(Class999 arg)
    {
        //nothing to do
    }


//MAKE NOTE ABOUT THESE METHODS:

    public T IfGetNothing<T>()
    {
        if(this is IInterface<T> r) return r.GetNothing(); else return default(T);
    }

    public T NonIfGetNothing<T>()
    {
        return ((IInterface<T>)this).GetNothing();
    }

    public void IfSetNothing<T>()
    {
        if(this is IInterface<T> r) r.SetNothing(default(T));
    }

    public void NonIfSetNothing<T>()
    {
        ((IInterface<T>)this).SetNothing(default(T));
    }
}
```

After that, we want to know about the time consumed by casting `Implementer1000` to various `IInterface<ClassX>`, so we write a test like that:

```
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    [MemoryDiagnoser]
    [GcServer(true)]
    public class Test
    {
        private Implementer1000 _impl1000;

        [GlobalSetup]
        public void Setup()
        {
            _impl1000 = new Implementer1000();
        }


        [Benchmark]
        public void NonIfGet_From0_Take50()
        {
            _impl1000.NonIfGetNothing<Class0>();
            ...
           _impl1000.NonIfGetNothing<Class49>();
        }

        [Benchmark]
        public void NonIfGet_From950_Take50()
        {
            _impl1000.NonIfGetNothing<Class950>();
            ...
           _impl1000.NonIfGetNothing<Class999>();
        }


....


        [Benchmark]
        public void NonIfSet_From0_Take50()
        {
            _impl1000.NonIfSetNothing<Class0>();
            ...
            _impl1000.NonIfSetNothing<Class49>();
        }


        [Benchmark]
        public void NonIfSet_From950_Take50()
        {
            _impl1000.NonIfSetNothing<Class950>();
            ...
            _impl1000.NonIfSetNothing<Class999>();
        }

...

    }
```

Main idea is cast equal count of interfaces (for example 50) from different ranges: [0;49], [450; 499], [950;999] and check the time consumed by this work.

### Data

I have these results:
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19041
Intel Core i5-4200U CPU 1.60GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=5.0.100-rc.1.20452.10
  [Host]     : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  Job-VIGXEV : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT

Runtime=.NET Core 3.1  Server=True  


|                  Method |        Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |------------:|----------:|----------:|------:|------:|------:|----------:|
|   NonIfGet_From0_Take50 |    145.8 ns |   2.10 ns |   1.97 ns |     - |     - |     - |         - |
| NonIfGet_From450_Take50 |    145.7 ns |   1.97 ns |   1.74 ns |     - |     - |     - |         - |
| NonIfGet_From950_Take50 |    145.7 ns |   1.84 ns |   1.72 ns |     - |     - |     - |         - |
|      IfGet_From0_Take50 |  1,098.6 ns |   8.01 ns |   7.49 ns |     - |     - |     - |         - |
|    IfGet_From450_Take50 | 13,660.1 ns | 268.84 ns | 238.32 ns |     - |     - |     - |         - |
|    IfGet_From950_Take50 | 25,844.7 ns | 236.62 ns | 209.76 ns |     - |     - |     - |         - |
|   NonIfSet_From0_Take50 |  1,104.3 ns |  21.76 ns |  20.36 ns |     - |     - |     - |         - |
| NonIfSet_From450_Take50 | 13,656.6 ns | 146.86 ns | 130.19 ns |     - |     - |     - |         - |
| NonIfSet_From950_Take50 | 25,736.7 ns | 199.85 ns | 186.94 ns |     - |     - |     - |         - |
|      IfSet_From0_Take50 |  1,127.6 ns |  19.70 ns |  17.47 ns |     - |     - |     - |         - |
|    IfSet_From450_Take50 | 13,596.8 ns |  84.79 ns |  70.81 ns |     - |     - |     - |         - |
|    IfSet_From950_Take50 | 25,779.7 ns | 240.44 ns | 213.15 ns |     - |     - |     - |         - |

```

These results makes me completely confused :)

### Analysis

9 out of 12 tests tell us that the later the interface is inherited in the code, the slower the conversion to it (O(n)?), but the first three tests contradict this conclusion (O(1)?). Of course there is a different IL code between `NonIfGet`, `IfGet`, `NonIfSet` and `IfSet`. But in my opinion the difference in IL does not explain why, the larger the x in `(IInterface<ClassX>)`, the slower the casting.

Let's focus on `NonIfSet` and try to modify its signature.

1. As usual

```
public interface IInterface<T> where T : class {  T GetNothing(); void SetNothing(T arg); }
                                                                                  ^^^^^

.method public hidebysig instance void  NonIfSetNothing<class T>(class TypeCastPerformance.Performance.CastToGenericInterface.Implementer1000 impl) cil managed
{
  // Размер кода:       21 (0x15)
  .maxstack  2
  .locals init (!!T V_0)
  IL_0000:  ldarg.1
  IL_0001:  castclass  class TypeCastPerformance.Performance.CastToGenericInterface.IInterface`1<!!T>
  IL_0006:  ldloca.s   V_0
  IL_0008:  initobj    !!T
  IL_000e:  ldloc.0
  IL_000f:  callvirt   instance void class TypeCastPerformance.Performance.CastToGenericInterface.IInterface`1<!!T>::SetNothing(!0)
  IL_0014:  ret
} // end of method Test::NonIfSetNothing


|                  Method |        Mean |       Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |------------:|------------:|----------:|------:|------:|------:|----------:|
| NonIfSet_From950_Take50 | 25,922.3 ns |   676.62 ns | 241.29 ns |     - |     - |     - |         - |

```

2. Remove the parameter
```
public interface IInterface<T> where T : class {  T GetNothing(); void SetNothing(); }
                                                                               ^^^^^


.method public hidebysig instance void  NonIfSetNothing<class T>(class TypeCastPerformance.Performance.CastToGenericInterface.Implementer1000 impl) cil managed
{
  // Размер кода:       12 (0xc)
  .maxstack  8
  IL_0000:  ldarg.1
  IL_0001:  castclass  class TypeCastPerformance.Performance.CastToGenericInterface.IInterface`1<!!T>
  IL_0006:  callvirt   instance void class TypeCastPerformance.Performance.CastToGenericInterface.IInterface`1<!!T>::SetNothing()
  IL_000b:  ret
} // end of method Test::NonIfSetNothing



|                  Method |        Mean |       Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |------------:|------------:|----------:|------:|------:|------:|----------:|
| NonIfSet_From950_Take50 |    143.5 ns |    50.41 ns |   2.76 ns |     - |     - |     - |         - |

```

3. Make parameter System.Object
```
public interface IInterface<T> where T : class {  T GetNothing(); void SetNothing(object arg); }
                                                                                  ^^^^^



.method public hidebysig instance void  NonIfSetNothing<class T>(class TypeCastPerformance.Performance.CastToGenericInterface.Implementer1000 impl) cil managed
{
  // Размер кода:       13 (0xd)
  .maxstack  8
  IL_0000:  ldarg.1
  IL_0001:  castclass  class TypeCastPerformance.Performance.CastToGenericInterface.IInterface`1<!!T>
  IL_0006:  ldnull
  IL_0007:  callvirt   instance void class TypeCastPerformance.Performance.CastToGenericInterface.IInterface`1<!!T>::SetNothing(object)
  IL_000c:  ret
} // end of method Test::NonIfSetNothing




|                  Method |        Mean |       Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |------------:|------------:|----------:|------:|------:|------:|----------:|
| NonIfSet_From950_Take50 |    143.4 ns |    20.38 ns |   1.12 ns |     - |     - |     - |         - |
```

(errors are big because of small count of testing iterations)

So, my main suspects are `ldloca.s   V_0` and `initobj    !!T`. As I can understand both are working with the argument type under the hood. I don't know how to progress further.

Could anyone shed some light about this?

Specifically I would like to know

0. what the reason of these performance drawdown? and why this huge difference exists?
0. I need a syntax `if(this is IInterface<T> r)` with performance of `((IInterface<T>)this)`, any suggestions for a workaround? May be hand-written IL can help me?
0. I understand that it makes little sense to optimize the runtime for such extreme cases, but maybe this problem can be solved at a small cost? :)

Thank you!

Repro (.sln) can be found here: https://github.com/dotnet/roslyn/issues/48441

**Comment by jkotas** [comment]
> Runtime=.NET Core 3.1 

Can you try to rerun your benchmark on .NET 5? The casting performance was greatly improved for number of cases in .NET 5.

cc @VSadov

**Comment by lsoft** [comment]
@jkotas sure, please take a look: 

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.508 (2004/?/20H1)
Intel Core i5-4200U CPU 1.60GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=5.0.100-rc.1.20452.10
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.45114, CoreFX 5.0.20.45114), X64 RyuJIT
  Job-QLPDCP : .NET Core 5.0.0 (CoreCLR 5.0.20.45114, CoreFX 5.0.20.45114), X64 RyuJIT

Runtime=.NET Core 5.0  Server=True  

```
|                  Method |        Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |------------:|----------:|----------:|------:|------:|------:|----------:|
|   NonIfGet_From0_Take50 |    141.9 ns |   2.01 ns |   1.68 ns |     - |     - |     - |         - |
| NonIfGet_From450_Take50 |    142.4 ns |   2.02 ns |   1.89 ns |     - |     - |     - |         - |
| NonIfGet_From950_Take50 |    142.9 ns |   2.55 ns |   2.39 ns |     - |     - |     - |         - |
|      IfGet_From0_Take50 |  1,086.6 ns |   8.49 ns |   7.94 ns |     - |     - |     - |         - |
|    IfGet_From450_Take50 | 13,574.8 ns | 188.64 ns | 157.52 ns |     - |     - |     - |         - |
|    IfGet_From950_Take50 | 25,810.1 ns | 335.11 ns | 279.84 ns |     - |     - |     - |         - |
|   NonIfSet_From0_Take50 |  1,128.8 ns |  16.59 ns |  13.85 ns |     - |     - |     - |         - |
| NonIfSet_From450_Take50 | 13,550.2 ns | 134.91 ns | 126.20 ns |     - |     - |     - |         - |
| NonIfSet_From950_Take50 | 25,573.8 ns | 147.76 ns | 130.99 ns |     - |     - |     - |         - |
|      IfSet_From0_Take50 |  1,126.9 ns |   8.93 ns |   7.92 ns |     - |     - |     - |         - |
|    IfSet_From450_Take50 | 13,439.8 ns | 127.10 ns | 112.67 ns |     - |     - |     - |         - |
|    IfSet_From950_Take50 | 25,743.2 ns | 244.59 ns | 228.79 ns |     - |     - |     - |         - |


Repro:  [TypeCastPerformance.zip](https://github.com/dotnet/runtime/files/5358492/TypeCastPerformance.zip)


To add some light here I want to explain why I need it.

In the field of high performance DI containers we have a standard ('classic') approach like the following:

```
    public interface IResolution { T Get<T>(); }

    public class ClassicCluster :
        IResolution
    {
        public T Get<T>()
        {
            return Cache<T>.Factory();
        }


        public static Dictionary<Type, object> fs = new Dictionary<Type, object>
        {
            [typeof(int)] = new Func<int>( () => 1 ),
            [typeof(string)] = new Func<string>( () => "2" )
        };


        private static class Cache<T>
        {
            public static Func<T> Factory;

            //static constructor works once for each T and initializes Factory
            //'Func<T> Factory' cannot be simplified to 'T Instance' since we want to have singleton/transient scopes
            static Cache()
            {
                if (fs.TryGetValue(typeof(T), out var f))
                {
                    var fff = (Func<T>)f;
                    Factory = fff;
                }
                else
                {
                    //PLEASE MAKE NOTE ABOUT THIS LINE:
                    throw new Exception("unknown binding " + typeof(T).FullName);
                }
            }
        }

    }
```

On my laptop it works with these timings:

|    Namespace | Method |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |------- |----------:|----------:|----------:|------:|------:|------:|----------:|
| perf.Classic |    Get | 10.158 ns | 0.2367 ns | 0.2098 ns |     - |     - |     - |         - |


In searching for faster option I found this design:

```
    public interface IResolution { T Get<T>(); }

    public interface IResolution<T> { T Get(); }


    public class NovelCluster :
        IResolution,
        IResolution<int>,
        IResolution<string>
    {
        public T Get<T>()
        {
            return ((IResolution<T>)this).Get();
        }

        int IResolution<int>.Get()
        {
           //here we can return singleton with double cheking locking or just `new Something()` in case of transient
           //it's easy to generate correct source code with C# source generator
            return 1;
        }

        string IResolution<string>.Get()
        {
            //same here
            return "2";
        }
    }
```

|    Namespace | Method |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |------- |----------:|----------:|----------:|------:|------:|------:|----------:|
|   perf.Novel |    Get |  5.967 ns | 0.1100 ns | 0.0975 ns |     - |     - |     - |         - |

Works for 2 times faster here. Novel approach retains palpable superiority even on a very complex dependency tree with 5000 objects.

But there is a drawback: we've lost checking for unknown bindings. For classical approach we are able to throw meaningful exception, with `((IResolution<T>)this)` we can't. Make switch to `if(this is IResolution<T> r)` and we are here :)


I understand that from practical point of view, there is no differences between ~100 ns and ~200 ns resolutions. But this problem is interested from scientific point: is the best performance you can get in dotnet for DI containers?

If it is possible to make  `if(this is IResolution<T> r)` timings as stable as `((IResolution<T>)this)` (not equal of course, but stable) I would be happy :)

Thanks!

**Comment by VSadov** [comment]
Throughput of ordinary interface casts (not involving variance) did not change much in 5.0. 
We did improve latency guarantees, but these tests check throughput.
Ordinary interface cast/check is indeed a linear scan through the interface list. It is fast because typically the list is short. We could make it O(1) , but it would be slower than O(n) for the most common case (having roughly 8 interfaces or less).

The `NonIfGetNothing` case may be benefitting from inline call-site caching set up by the JIT for the interface invocation. Since you measure a monomorphic case (repeated case with the instance of the same type), it would help. It is a scenario where the call-site remembers what type it saw last time the invocation was made, so if it is the same, it is fast next time. Casts do not have such per-invocation site memory.

That is just a theory though, I would need to take a look at actual emitted native code to be sure what is happening.

**Comment by lsoft** [comment]
@VSadov thank you for the answer.

>  It is a scenario where the call-site remembers what type it saw last time the invocation was made, so if it is the same, it is fast next time.
Each invocation leads to casting to a different interface: `IInterface<Class1>`, `IInterface<Class2>` etc. Or did you mean `IInterface<>` regardless of generic parameter? But `if(this is IInterface<T> r)` has same casting behaviour... 

I fully understand why O(n) is used (it's fastest for general case), but it is not clear to me why the performance is very different between `((IInterface<T>)this)` and `if(this is IInterface<T> r)`. Maybe the problem is not in the casting (i.e. `castclass`)? `castclass` and `callvirt` are the same for `void SetNothing(object arg);` and `void SetNothing(T arg);`. The only difference is  `ldloca.s   V_0`, `initobj    !!T`...

I would like to know if there is a way to modify the runtime to achieve  O(1) or O(log (N)) for the case  `if(this is IInterface<T> r)` without getting slower the general case. Could I ask you to take a look what actually causes the observed performance difference between the cases?

> We could make it O(1) , but it would be slower than O(n) for the most common case (having roughly 8 interfaces or less).
I completely agree there is no sense to get the general case slower for such an extreme case as mine.

Thanks!

**Comment by VSadov** [comment]
>Each invocation leads to casting to a different interface: IInterface<Class1>, IInterface<Class2> etc. Or did you mean IInterface<> regardless of generic parameter? But if(this is IInterface<T> r) has same casting behaviour...

In your benchmark `NonIfGetNothing` is inlined by the JIT, so the caller has 50 call sites which do interface call dispatches. Each remembering the type of the argument that was last dispatched to a statically known target. On the next iteration each of them is O(1).
As an experiment you can add `[MethodImpl(MethodImplOptions.NoInlining)]` to `NonIfGetNothing` and it should have behavior similar to the others. Since `T` is a class, the generic instantiation of `NonIfGetNothing` will be shared among different `T`s, and remembering the last argument type inside that method would not be enough. Last `T` would need to be remembered too, so JIT just emits code with casts, which do not have per-use memory and otherwise O(n) for this case.

>  it is not clear to me why the performance is very different between ((IInterface<T>)this) and if(this is IInterface<T> r)

Behavior of `if(this is IInterface<T> r)` is different because it cannot be reduced to just an interface call. This expression produces `false` instead of throwing when type check fails, so it must do an actual type check.

I need to think/experiment more to see what can be done to have more predictable performance in cases like this. 
We could, for example, do cast check differently when the number of implemented interfaces is grater than some _big_ number, avoiding potential O(n) when n is too large. That is not so simple though. I am fairly sure that there is existing code somewhere which puts most commonly used interfaces intentionally placed at the beginning of the impl list and casts to those are fast regardless of total number of interfaces. Those cases could regress.

**Comment by lsoft** [comment]
@VSadov I think I understand. Thanks for clarification! 'NoInlining' turns `NonIfGetNothing` to O(n), and 'AggressiveInlining' turns `IfGetNothing` into O(1). That finding resolves my issue (I've checked).  I have 2 last questions if you will let me ask them.

1. For the method with 50 invocation (0...49) inlining occurs; for method with 1000 invocation (perf test) it doesn't. I split 1000 invocations into 20 methods with 50 invocations, and everything works fast. Perhaps there is a inlining constraint for the length of the method? Also, I would like to know: What are constraints for inlining? Is there any information about inlining constraints that is understandable to a non-specialist like me?
2. 6.0.0 milestone has been added. Should I keep this issue open or I should close it because my problem is resolved?

Thanks for your help!

**Comment by AndyAyersMS** [comment]
> I think there used to be limits on the containing method size when optimizations were disabled 

"optimizations were enabled"?

There are still these kinds of limits -- methods that are too large (by various measures) won't get optimized. There are a number of measures; one of these is IL size. Currently methods with more than 60,000 bytes of IL will have optimizations disabled.

**Comment by lsoft** [comment]
@VSadov @AndyAyersMS thanks for helpful discussion and useful information!
