### ISSUE TITLE
Allow allocating certain large objects in gen0

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#43194]
Remove the penalty for large objects that don't container references (byte[]/string etc). The scenario is to remove the LOH penalty when people frivolously allocate giant `strings` and `byte[]` when doing things like logging or trying to use the entire request body has a `byte[]` (yes I know it's not good).

There are certain APIs that basically lead you down this path:
- StreamReader.ReadToEndAsync
- File.ReadAllText
- File.ReadAllBytes
- MemoryStream.ToArray()

I could go on but I'll stop there 😄.

cc @Maoni0

**Comment by Maoni0** [comment]
yes, I provided a private build, were you able to get any results from running it?

**Comment by davidfowl** [comment]
@Maoni0 I forgot you gave me a build! Let me dig that up and get some measurements!

**Comment by kkokosa** [comment]
Is this considered to be the new "new"? Or just "smart new" that will allocate on SOH/LOH depending on the size/"contains references"?

**Comment by Maoni0** [comment]
the build I gave to David just uses AllocateArray (with an additional arg).

**Comment by davidfowl** [comment]
I'm now convinced. This is a bad idea 😄
