### ISSUE TITLE
Test failure: System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Windows.Allow_Connection_UnderDifferentUsers_ForClientReading

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43209]
failed in job:[runtime-libraries-coreclr outerloop 20201008.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26906848&paneView=debug&resultId=103443)

failed tests:
System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Windows.Allow_Connection_UnderDifferentUsers_ForClientReading 
System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Windows.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: CurrentUserOnly)
System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Windows.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: CurrentUserOnly, clientPipeOptions: None)
System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Windows.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: None, clientPipeOptions: CurrentUserOnly)
System.IO.Pipes.Tests.NamedPipeTest_CurrentUserOnly_Windows.Connection_UnderDifferentUsers_BehavesAsExpected(serverPipeOptions: None, clientPipeOptions: None)

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
System.AggregateException : One or more errors occurred. (The Server service is not started.
) (The following constructor parameters did not have matching fixture data: TestAccountImpersonator testAccountImpersonator)
---- System.Runtime.InteropServices.COMException : The Server service is not started.

---- The following constructor parameters did not have matching fixture data: TestAccountImpersonator testAccountImpersonator

Stack trace

----- Inner Stack Trace #1 (System.Runtime.InteropServices.COMException) -----
   at System.DirectoryServices.DirectoryEntry.RefreshCache() in /_/src/libraries/System.DirectoryServices/src/System/DirectoryServices/DirectoryEntry.cs:line 959
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit() in /_/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:line 634
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize() in /_/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:line 568
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx() in /_/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:line 1075
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate) in /_/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Principal.cs:line 930
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue) in /_/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Principal.cs:line 909
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, String identityValue) in /_/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/User.cs:line 266
   at System.IO.Pipes.Tests.TestAccountImpersonator..ctor() in /_/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.Windows.cs:line 38
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
~~~

**Comment by carlossanlop** [comment]
```
The Server service is not started.
```

This seems to be an infrastructure issue. The Server service should be enabled in the Windows container running the test.

<img src="https://user-images.githubusercontent.com/1175054/95625484-676dfe80-0a2d-11eb-8eb2-45fd5c8d6baa.png" width="40%">.

The failing container is:

```
(Windows.Server.Core.1909.Amd64.Open)
windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
```

@safern @ViktorHofer @ericstj do you know who can help with this?

**Comment by ViktorHofer** [comment]
that would be a better question for @MattGal and @dotnet/dnceng

**Comment by safern** [comment]
Also since this are outerloop tests we could disable them in servercore. They are already disabled for Nano which I guess it is due to the same problem. 

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.Windows.cs#L126

**Comment by lpatalas** [comment]
> that would be a better question for @MattGal and @dotnet/dnceng

We'll take a look on it.

**Comment by MattGal** [comment]
@carlossanlop I took a look at [the failing work item's log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-6a8b255a0f87428a97/System.ServiceProcess.ServiceController.Tests/console.246f6cbd.log?sv=2019-07-07&se=2020-10-28T13%3A02%3A35Z&sr=c&sp=rl&sig=KjugGQOQBgiiZQCZG2trvrWRwMv1NaKRJg1O1oy6VEQ%3D) and I didn't see `The Server service is not started.` as noted, just a failing test:

```
C:\helix\work\workitem>"C:\helix\work\correlation\dotnet.exe" exec --runtimeconfig System.ServiceProcess.ServiceController.Tests.runtimeconfig.json --depsfile System.ServiceProcess.ServiceController.Tests.deps.json xunit.console.dll System.ServiceProcess.ServiceController.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.ServiceProcess.ServiceController.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ServiceProcess.ServiceController.Tests (found 22 of 37 test cases)
  Starting:    System.ServiceProcess.ServiceController.Tests (parallel test collections = on, max threads = 2)
    System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand [FAIL]
      Assert.Equal() Failure
      Expected: 129
      Actual:   128
      Stack Trace:
        /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs(156,0): at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand()
  Finished:    System.ServiceProcess.ServiceController.Tests
=== TEST EXECUTION SUMMARY ===
   System.ServiceProcess.ServiceController.Tests  Total: 22, Errors: 0, Failed: 1, Skipped: 0, Time: 56.063s
----- end Thu 10/08/2020 13:48:51.38 ----- exit code 1 ----------------------------------------------------------
```

Regardless, if you feel that this image is configured incorrectly you should be able to run the same image used in the test locally to experiment, then if you determine a changes is needed you simply need to go to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/windowsservercore/2004/helix/amd64/Dockerfile and make the appropriate tweaks as a PR, then update the image tag used.  

I'm happy to help, but thus far I don't see anything wrong with the infra here, just assumptions the test is making about the container its running within.

**Comment by safern** [comment]
> Edit: Checking out the test's code, it sure looks like the test is just doing something invariably, while the comment above it mentions not working on core / nano:

Yeah I agree, I think we should just disable the test on Server Core as I noted in an earlier comment that this is already disabled for Nano.
