### ISSUE TITLE
Test failure:System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PingKeepAlive(keepAlivePingDelay: 00:00:01, keepAlivePingPolicy: WithActiveRequests, expectRequestFail: False)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43205]
failed in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26912082&resultId=103147&paneView=debug)

net6.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-bfcd90a-20200127194925

Error message
~~~
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(Xunit.Sdk.NotNullException): Assert.NotNull() Failure
---- Assert.NotNull() Failure

Stack trace
   at System.Net.Test.Common.Http2LoopbackConnection.ReadPingAsync(TimeSpan timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 710
----- Inner Stack Trace -----
   at System.Net.Test.Common.Http2LoopbackConnection.ReadPingAsync(TimeSpan timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 710
~~~

**Comment by ManickaP** [comment]
Triage: probably the same problem as in https://github.com/dotnet/runtime/issues/41929

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/41929
