### ISSUE TITLE
MonoVM: add back dllmap support for macOS

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#43204]
# Description

dllmap support is enabled for iOS (Xamarin.iOS) targets:

https://github.com/dotnet/runtime/blob/c5b6881e9b0e0826029185cd5a1569f80f6b9aba/src/mono/configure.ac#L1420-L1422

this is needed for macOS (Xamarin.Mac) as well, because we use it for the exact same purpose (redirect calls to objc_msgSend to our own implementations).

Example disassembly that shows that it's disabled (calls to `mono_dll_insert` asserts) on macOS:

```
$ otool -vVt -p _mono_dllmap_insert ./microsoft.netcore.app.runtime.ios-x64/5.0.0-rc.2.20475.5/runtimes/ios-x64/native/libmonosgen-2.0.dylib
./microsoft.netcore.app.runtime.ios-x64/5.0.0-rc.2.20475.5/runtimes/ios-x64/native/libmonosgen-2.0.dylib:
(__TEXT,__text) section
_mono_dllmap_insert:
00000000001cdda2	pushq	%rbp
00000000001cdda3	movq	%rsp, %rbp
00000000001cdda6	popq	%rbp
00000000001cdda7	jmp	_mono_dllmap_insert_internal
```

```
$ otool -vVt -p _mono_dllmap_insert ./microsoft.netcore.app.runtime.mono.osx-x64/5.0.0-rc.2.20475.5/runtimes/osx-x64/native/libcoreclr.dylib
./microsoft.netcore.app.runtime.mono.osx-x64/5.0.0-rc.2.20475.5/runtimes/osx-x64/native/libcoreclr.dylib:
(__TEXT,__text) section
_mono_dllmap_insert:
000000000022d430	pushq	%rbp
000000000022d431	movq	%rsp, %rbp
000000000022d434	leaq	0x103e97(%rip), %rdi ## literal pool for: "/Users/runner/work/1/s/src/mono/mono/metadata/native-library.c"
000000000022d43b	movl	$0x112, %esi
000000000022d440	callq	_mono_assertion_message_unreachable
000000000022d445	nopw	%cs:(%rax,%rax)
000000000022d44f	nop
```

**Comment by CoffeeFlux** [comment]
Given we have no alternative for symbol remapping, I'm fine with this. PR in a bit.

We are, however, still going to have to figure out how to extend our loader callbacks to work properly with AOT on mobile, and ideally whatever we add would also cover this functionality.

**Comment by marek-safar** [comment]
I don't think we should do it and instead think about .net core compatible alternatives

**Comment by CoffeeFlux** [comment]
The problem is that I've gotten a large amount of pushback at the idea of adding more generic symbol remapping functionality. 

Unless Xamarin.Mac wants to break compatibility with a long-established pattern they need _some_ method to accomplish symbol remapping. If we're willing to commit to solving this problem more generically for net6 I'd be thrilled, but otherwise I don't see a good alternative to just giving them dllmap.

**Comment by rolfbjarne** [comment]
Using `PINVOKE_OVERRIDE` seems to work, so I'm closing this.
