### ISSUE TITLE
Test failure: System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43207]
failed in job:[runtime-libraries-coreclr outerloop 20201008.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26906848&paneView=debug&resultId=103443)

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
Assert.Equal() Failure
Expected: 129
Actual:   128

Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201025.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=865290&view=ms.vss-test-web.build-test-results-tab&runId=27710548&resultId=102455&paneView=debug)

failed test: System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Assert.Equal() Failure
Expected: 129
Actual:   128


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201124.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=897960&view=ms.vss-test-web.build-test-results-tab&runId=28691260&resultId=104660&paneView=debug)

failed test: System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Assert.Equal() Failure
Expected: 129
Actual:   128


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201214.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=920179&view=ms.vss-test-web.build-test-results-tab&runId=29240704&resultId=104417&paneView=debug)

failed test: System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Assert.Equal() Failure
Expected: 129
Actual:   128


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
~~~

**Comment by VincentBu** [comment]
Failed again in job [runtime-libraries-coreclr outerloop 20210111.2](https://dev.azure.com/dnceng/public/_build/results?buildId=944638&view=ms.vss-test-web.build-test-results-tab&runId=29808938&resultId=103270&paneView=debug)

Failed test : `System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand`

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

**Error message:**
```
Assert.Equal() Failure
Expected: 129
Actual:   128


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
```

**Comment by VincentBu** [comment]
Failed again in job: [runtime-libraries-coreclr outerloop 20210117.2](https://dev.azure.com/dnceng/public/_build/results?buildId=954714&view=ms.vss-test-web.build-test-results-tab&runId=30122654&paneView=work-items&resultId=104003)

Failed tests:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
        - System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand
```

Error message:
```
Assert.Equal() Failure\r\nExpected: 129\r\nActual:   128
at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
```

**Comment by VincentBu** [comment]
Failed again in run [runtime-libraries-coreclr outerloop 20210124.2](https://dev.azure.com/dnceng/public/_build/results?buildId=963738&view=ms.vss-test-web.build-test-results-tab&runId=30351432&paneView=debug&resultId=104183)

Failed tests:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
        - System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand
```

Error message:
```
Assert.Equal() Failure
Expected: 129
Actual:   128

stack trace:
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210131.2](https://dev.azure.com/dnceng/public/_build/results?buildId=973165&view=ms.vss-test-web.build-test-results-tab&runId=30559828&paneView=debug&resultId=104261)

Failed tests:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
    - System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand
```

Error message:
```

**Comment by VincentBu** [comment]
Failed again in run [runtime-libraries-coreclr outerloop 20210217.1](https://dev.azure.com/dnceng/public/_build/results?buildId=998306&view=ms.vss-test-web.build-test-results-tab&runId=31237668&resultId=103983&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

 -System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand
```

**Error message:**
```
Assert.Equal() Failure
Expected: 129
Actual:   128


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
```

**Comment by danmoseley** [comment]
This fails only on Server Core, and always on Server Core - interestingly it passes on Nano.

https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAHWRUUvDMBDH34V9h2Mva6Eb3R6FCmMqTNBNN%2fDBiWTNbc22JiN3wU388Cat2AoKgeT%2b97vc%2f5IlEj8huQMTdC4%2bYWeUhr3SMlNao4VnY%2fdTxpLA6J9gKv9k78y6wvw%2blQF4L9Ai3CqtqEAJVxlIwciqxGiUjtJ%2bOuwPIb1Mw4qbgnvkwkjIMuguvb2Zvjlh7hgnjtiUE1OWQstu4AFPjFrCjozOjsISvoVjNLfmiJYVUnXtNzUxeqO2zgpWHg%2fgIG9LCYxtXijGnJ3FGhAtJYFr3PhhmvImfhClz88LQXXhS29xJv9Ug0oK2d5rArNFXRfc%2bZZ6W0PBIzk%2fllUfCLlxmqMY1meofyaBR4cOxwclKAG2qoy6qxV1%2fdmQD%2fU2%2bjVaHLcy7ZHaemO9rVZu43%2bazBaxf87OxRfIKLiPNAIAAA%3d%3d&web=0

TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where Finished >= datetime(2020-01-1 0:00:00)
| where Method == "TestOnExecuteCustomCommand"
|  extend json=parse_json(Properties)
| extend Configuration=json.configuration, Architecture=json.architecture, Definition=json.DefinitionName, Phase=json['System.PhaseName'], OS=json.operatingSystem
| summarize count() by Result, QueueAlias, trim("\\s", tostring(Configuration)), tostring(Architecture), tostring(Definition), tostring(Phase), trim("\\s", tostring(OS))


Result | QueueAlias | Column1 | Architecture | Definition | Phase | Column2 | count_
-- | -- | -- | -- | -- | -- | -- | --
Fail | windows.server.core.1909.amd64.open | Release | x64 | runtime-libraries-coreclr outerloop-windows | libraries_build_windows_x64_Release | (Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c | 848
Fail | windows.server.core.1909.amd64.open | Release | x64 | runtime-libraries-coreclr outerloop | libraries_build_windows_x64_Release | (Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c | 551
Fail | windows.server.core.1909.amd64.open | Debug | x64 | runtime-libraries-coreclr outerloop | libraries_build_windows_x64_Debug | (Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c | 360
Fail | windows.server.core.1909.amd64.open | Debug | x64 | runtime-libraries-coreclr outerloop-windows | libraries_build_windows_x64_Debug | (Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c | 4
Pass | windows.81.amd64.open | Release | x64 | runtime-libraries-coreclr outerloop |   | Windows.81.Amd64.Open | 59
Pass | windows.10.amd64.serverrs5.open | Release | x64 | runtime-libraries-coreclr outerloop |   | Windows.10.Amd64.ServerRS5.Open | 59
Pass | windows.7.amd64.open | Release | x86 | runtime-libraries-coreclr outerloop |   | Windows.7.Amd64.Open | 59
Pass | windows.10.amd64.server19h1.open | Release | x64 | runtime-libraries-coreclr outerloop |   | Windows.10.Amd64.Server19H1.Open | 59
Pass | windows.nano.1809.amd64.open | Release | x64 | runtime-libraries-coreclr outerloop |   | (Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504 | 59
Pass | windows.10.amd64.server19h1.open | Release | x86 | runtime-libraries-coreclr outerloop |   | Windows.10.Amd64.Server19H1.Open | 59
Pass | windows.10.amd64.serverrs5.open | Release | x86 | runtime-libraries-coreclr outerloop |   | Windows.10.Amd64.ServerRS5.Open | 59
Pass | windows.81.amd64.open | Release | x64 | runtime-libraries-coreclr outerloop-windows |   | Windows.81.Amd64.Open | 15
Pass | windows.10.amd64.serverrs5.open | Release | x64 | runtime-libraries-coreclr outerloop-windows |   | Windows.10.Amd64.ServerRS5.Open | 15
Pass | windows.10.amd64.serverrs5.open | Release | x86 | runtime-libraries-coreclr outerloop-windows |   | Windows.10.Amd64.ServerRS5.Open | 15
Pass | windows.7.amd64.open | Release | x86 | runtime-libraries-coreclr outerloop-windows |   | Windows.7.Amd64.Open | 15
Pass | windows.10.amd64.server19h1.open | Release | x64 | runtime-libraries-coreclr outerloop-windows |   | Windows.10.Amd64.Server19H1.Open | 15
Pass | windows.nano.1809.amd64.open | Release | x64 | runtime-libraries-coreclr outerloop-windows |   | (Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504 | 15
Pass | windows.10.amd64.server19h1.open | Release | x86 | runtime-libraries-coreclr outerloop-windows |   | Windows.10.Amd64.Server19H1.Open | 15
Pass |   | Release | x64 |   |   | Windows.81.Amd64 | 3
Pass |   | Release | x86 |   |   | Windows.10.Amd64.Core | 3
Pass |   | Release | x64 |   |   | Windows.10.Amd64.Core | 3
Pass |   | Release | x86 |   |   | Windows.81.Amd64 | 3
Pass |   | Release | x86 |   |   | Windows.7.Amd64 | 3
Pass |   | Release | x64 |   |   | Windows.10.Amd64 | 3
Pass |   | Release | x86 |   |   | Windows.10.Amd64 | 3
Pass |   | Release | x64 |   |   | Windows.7.Amd64 | 3
Pass | windows.10.amd64.server19h1.es.open | Debug | x64 | runtime-libraries-coreclr outerloop |   | Windows.10.Amd64.Server19H1.ES.Open | 4
Pass | windows.nano.1809.amd64.open | Debug | x64 | runtime-libraries-coreclr outerloop |   | (Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504 | 4
Pass | windows.10.amd64.server19h1.es.open | Release | x86 | runtime-libraries-coreclr outerloop |   | Windows.10.Amd64.Server19H1.ES.Open | 4
Pass | windows.81.amd64.open | Debug | x64 | runtime-libraries-coreclr outerloop |   | Windows.81.Amd64.Open | 4

**Comment by danmoseley** [comment]
@ViktorHofer just curious, which of these do we run elevated? This test only runs when elevated:
`        [ConditionalFact(nameof(IsProcessElevated))]`

But, perhaps if it wasn't elevated, it would not show up as a pass, but rather skipped. (@MattGal are the two distinguished?)

**Comment by MattGal** [comment]
@danmoseley couple things here:

- Passed vs Skipped is indeed distinguished both when test results are ingested to Kusto as well as in Azure Devops
- Helix machines have UAC prompting turned off and most things run in an effectively elevated context ; low-rights helix clients was kind of a non-starter and something we haven't had for at least 4 years.
- At some point, Docker scenarios (core and nano), started requiring that the user always be an elevated admin type user;  this could be relevant, and something you can experiment in locally with Docker.
- As I discussed recently with @safern Nano is still on  1809 for your testing, which is EOL (Nov. '20) and should be updated somewhere higher like 1909 as your Core is.

**Comment by danmoseley** [comment]
Thanks @MattGal . (Interesting that we're always testing elevated. Perhaps we have enough folks running tests locally non-elevated that we're not risking shipping in a broken state non-elevated...)

**Comment by MattGal** [comment]
Every time we've revisited it there were many tests that broke these assumptions (and with LUA dialogs off and low rights, it all has to "work" low rights" to finish.   I am not sure there've been enough actual UAC related bugs (any?) to justify the work but I'm always happy to have the conversation.   I believe you can still, inside a helix work item, start a process with lower rights if you wanted...

**Comment by danmoseley** [comment]
Yup, I'm not pushing back.

Anyway I disabled this test for Server Core. As long as it works on Nano I think we have coverage of it.
