### ISSUE TITLE
Test failure: System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NetworkStream_Renegotiation_Succeeds(useSync: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43203]
failed in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26912096&resultId=102058&paneView=debug)

failed tests:
System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NetworkStream_Renegotiation_Succeeds(useSync: True)
System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NetworkStream_Renegotiation_Succeeds(useSync: False)
System.Net.Security.Tests.SslStreamAllowRenegotiationTests_Async.SslStream_AllowRenegotiation_True_Succeeds
System.Net.Security.Tests.SslStreamAllowRenegotiationTests_Sync.SslStream_AllowRenegotiation_True_Succeeds

Error message
~~~
Assert.InRange() Failure
Range:  (2 - 2147483647)
Actual: 1

Stack trace
   at System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NetworkStream_Renegotiation_Succeeds(Boolean useSync) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs:line 205
--- End of stack trace from previous location ---
~~~

**Comment by ManickaP** [comment]
Duplicate of #43122
