### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43208]
failed in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26906848&paneView=debug&resultId=101950)

failed tests:
System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True)
System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(useShellExecute: True)
System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(useShellExecute: False)

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
Assert.StartsWith() Failure:
Expected: StartInfo_NotepadWithContent_withArgumentList_1156_b0eef443
Actual:

Stack trace
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1179
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201025.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=865290&view=ms.vss-test-web.build-test-results-tab&runId=27710548&paneView=debug&resultId=100047)

failed tests: 
System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True)
System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: False)

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Assert.StartsWith() Failure:
Expected: StartInfo_NotepadWithContent_withArgumentList_1156_f5316ca1
Actual:


Stack trace
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1179
~~~

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/issues/44239
