### ISSUE TITLE
RegionInfo NativeName of "World" is "וועלט" : World in Yiddish instead of English ?

### ISSUE THREAD

**Issue by Safirion** [dotnet/runtime#43212]
When I run this code to get all Region :

```
 public static void Main(string[] args)
        {
            foreach(var c in CultureInfo.GetCultures(CultureTypes.AllCultures)
            .Where(x => !x.Equals(CultureInfo.InvariantCulture))
            .Where(x => !x.IsNeutralCulture))
		{
			try
			{
				var r = new RegionInfo(c.LCID);
				Console.WriteLine("["+r.Name+"]"+ r.EnglishName + ": " + r.NativeName );
			}
			catch 
			{
			}
		}
        }
```

https://dotnetfiddle.net/dUMjJu

I've got this : 
```
...
[CN]China: جۇڭگو
[UA]Ukraine: Україна
[IN]India: بھارت
[PK]Pakistan: پاکستان
[UZ]Uzbekistan: Ўзбекистон
[UZ]Uzbekistan: Oʻzbekiston
[VN]Vietnam: Việt Nam
[SN]Senegal: Senegaal
[ZA]South Africa: eMzantsi Afrika
[001]World: וועלט
[NG]Nigeria: Orílẹ́ède Nàìjíríà
[ZA]South Africa: iNingizimu Afrika
```

I was surprised by the language chosen for the region "World". It is Yiddish ? Why ? 
English must be a better choice as it is the international language of the world.

**Comment by huoyaoyuan** [comment]
I mentioned that your output for China isn't in Chinese.
When reporting culture-related issues, you'd better post your system language and runtime environment.

**Comment by Safirion** [comment]
Ah good catch. I was using an online code generator. It must be that.

**Comment by Safirion** [comment]
Ok, but NativeName must be the name of the country in the country language independently of the system language or the runtime environment no ?
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.regioninfo.nativename?view=netcore-3.1

I have test this code in https://dotnetfiddle.net/ with .Net Core 3.1 option
