### ISSUE TITLE
./build.sh --portablebulid false fails

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#43219]
I would like to add a build configuration in CI to help catch issues like https://github.com/dotnet/runtime/pull/42415. That is, essentially do a `./build.sh --portablebuild false` in a CI leg (on x64).

But that doesn't seem to work on Fedora or RHEL systems that I tried it on.

They all fail with a messages like

```
/home/dotnet/runtime/src/libraries/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : error NU1101: Unable to find package runtime.rhel.8-x64.microsoft.netcore.ilasm. No packages exist with this id in source(s): dotnet-eng
```
It's complaining that the ilasm assets for non-portable RIDs can not be found.

Does a portable build work outside of source-build? Is there a way I can make the build use portable nuget packages for tools like ilasm?

**Comment by omajid** [comment]
cc @tmds

**Comment by omajid** [comment]
Any thoughts, @crummel @dagood  @dleeapho @dseefeld  @jeffschwMSFT @ViktorHofer on how to get portable builds to work?

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
Sounds like the RID used for locating ILAsm is out of sync with that used for the CLI.  We know there is dotnet runtime that works otherwise you wouldn’t have gotten this far.
