### ISSUE TITLE
CipherMode.CFB is EditorBrowserable.Never in ref source

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#43256]
I noticed that as part of the CFB work, the `[EditorBrowsable(EditorBrowsableState.Never)]` was removed from the source here

https://github.com/dotnet/runtime/commit/219c60e19d19f673e141639381022c1d6b4e70ef#diff-bb0fd3f6ae247a27a2d5a60eba7f00d1L17-R19

but is still present in the reference source:

https://github.com/dotnet/runtime/blob/2e070b200ee12a1e1f933d53a24e97e9190761d9/src/libraries/System.Security.Cryptography.Primitives/ref/System.Security.Cryptography.Primitives.cs#L49-L50

Is this an oversight or intentional? Will this affect how developers see the enum with intellisense?

**Comment by bartonjs** [comment]
It was probably an oversight.  netstandard2.0 also has it marked as EB-Never, so it just means it's only there for someone who knows it's there and types it out.

Let's fix it for 6, but we can't adjust the netstandard version, so it's not really worth rescuing 5.
