### ISSUE TITLE
Add analyzer for Environment.CurrentManagedThreadId

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#43257]
`Environment.CurrentManagedThreadId` is more compact and efficient replacement of `Thread.CurrentThread.ManagedThreadId` pattern. This pattern is quite common. We should add analyzer and auto-fixer for this.

**Comment by MCCshreyas** [comment]
Hi @jkotas, do we need to include this code analyzer in this repo, OR in the Roslyn analyzer repo?

**Comment by jkotas** [comment]
The code for the analyzer should be in https://github.com/dotnet/roslyn-analyzers repo.

**Comment by MCCshreyas** [comment]
Yes @jkotas, as I already guessed! 😇

**Comment by terrajobst** [comment]
Makes sense.
