### ISSUE TITLE
Long running test: SslStream_StreamToStream_HandshakeAlert_Ok

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#43262]
```
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:02:32
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:04:32
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:06:32
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:08:32
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:10:32
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:12:32
   System.Net.Security.Tests: [Long Running Test] 'System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok', Elapsed: 00:14:32
```

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42826-merge-b077adc3d89a476ca4/System.Net.Security.Tests/console.5a6360e3.log?sv=2019-07-07&se=2020-10-30T17%3A19%3A37Z&sr=c&sp=rl&sig=nlh1zC7F%2BcUgj1WXyScs5%2BRSJkOwXcNyf3EVBSv7GjE%3D

https://dev.azure.com/dnceng/public/_build/results?buildId=848059&view=ms.vss-test-web.build-test-results-tab&runId=27016046&resultId=187135&paneView=attachments

Configuration: net6.0-Windows_NT-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open

**Comment by stephentoub** [comment]
@wfurt, I got this to hang once locally.  It's stuck in the handshake, with both the client and server waiting to read from each other.  And in particular, the client is stuck here:
https://github.com/dotnet/runtime/blob/9648fdfe72b7a06081c84c75ad310c09b57dd418/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L356
but it already has a message, with a status of ContinueNeeded:
![image](https://user-images.githubusercontent.com/2642209/96025104-ae3f6800-0e22-11eb-9bc8-2a61dccd5c86.png)
Any ideas?

**Comment by wfurt** [comment]
Could you please take another look at #42427 and possibly check if the empty buffer turned into SECBUFFER_EXTRA?

**Comment by stephentoub** [comment]
Sorry, I missed that you were waiting on me for that PR.  I can look now.  You think that might be the cause here?

**Comment by wfurt** [comment]
I don't know but the observed behavior was simiar - the handshake would hang and the remote peer would eventually fail with timeout. I did not see such behavior in tests but if you have it in debugger it should be easy to check. What Windows build do you use?

**Comment by stephentoub** [comment]
Chatted offline with @wfurt.  The cited PR was merged.  Let's see if these stop happening in CI.
