### ISSUE TITLE
​Math.Round supports minus digits

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#43263]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1210772/mathround-supports-minus-digits.html)._

---
<p>I hope Math.Round supports minus digits.</p> <p>Math.Round(4321, -1) =&gt; 4320</p><p>Math.Round(4321, -2) =&gt; 4300</p>

---
#### Feedback Bot on 10/10/2020, 02:53 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by tarekgh** [comment]
@tannergooding please have a look at this request. thanks.

**Comment by pgovind** [comment]
Not sure I completely understand the request here. The current `Round` API doesn't make much sense for non-floating point values. Perhaps what the user wanted may have been an API to do `Math.Floor(4321, 1)` or `Math.Floor(4321, 2)`? They don't exist today, but seem easy enough to implement. If there's more requests for such an API, we could consider adding it.

**Comment by tannergooding** [comment]
Today Round only impacts decimal digits, so you can convert `1234.5678` to `1234.57` for example by specifying `2`

I believe the request is that we also allow `-2` and interpret it as rounding digits on the LHS of the decimal point, in the above example it would return `1200`.

I don't think the usage here is particularly intuitive however and I'm wondering if there is a different API that could be exposed instead to allow the same functionality but with clearer semantics.

**Comment by pgovind** [comment]
Yea that's what I suspected too. So this issue is similar to https://github.com/dotnet/runtime/issues/35464.

**Comment by tannergooding** [comment]
Closing this as it isn't actionable as is. If someone would like this functionality they will need to open an API proposal following our template: https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md&title=

Ideally this would address the feedback above and try to ensure the behavior is intuitive to use.
