### ISSUE TITLE
Make all structs that claim to be thread-safe dereference `this` at most once per entrypoint

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#4329]
`ImmutableArray<T>` goes to great lengths to be thread-safe by [never dereferencing `this` more than once per public entrypoint](https://github.com/dotnet/corefx/blob/1dc118cc46f88e4889a23190b450d89e565967fd/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601.cs#L18-L33) (to fix bug dotnet/coreclr#191). Other structs in the Framework do _not_ take this care (such as `DateTime`, `Nullable<T>`, or `System.Int32`), despite [claiming to be thread-safe in MSDN documentation](https://msdn.microsoft.com/en-us/library/System.DateTime%28v=vs.110%29.aspx).

Should we take the same care for the other structs? 

The community [has been fascinated](http://stackoverflow.com/questions/30957211/what-advantage-is-there-to-storing-this-in-a-local-variable-in-a-struct-method/30957262) by the pattern in `ImmutableArray<T>` and brought up that it might make sense to spread it around more.

See also the [same issue in corefx](/dotnet/corefx/issues/2119).

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/32475
