### ISSUE TITLE
"Failed to load response data" after non-200 http request with Blazor HttpClient in Chromium based browsers

### ISSUE THREAD

**Issue by amityagov** [dotnet/runtime#43311]
### Describe the bug
Http response data not available if request ends with non-200 http status code (tested with 500).  
"Failed to load response data" message in Network tab in Chrome developer tools and  net::ERR_ABORTED 500 error in console.

Same request executed by hand shows response data in Response tab in Network tab.
```
fetch('https://localhost:5001/WeatherForecast')
```

After some investigation (by debugging) i found that error may be due to passing AbortController as `signal` parameter to fetch() method. But i can't found source code for this.

Reproducible in Chromium based browsers, tested in:
* Chrome 85.0.4183.121
* Microsoft Edge 86.0.622.38 

Works fine in Firefox 80.0.1 (64-bit)

### To Reproduce

repro: https://github.com/amityagov/blazor-http-500-aborted

`WeatherForecastController::Get` modified so it will throw exception after invocation.

* `dotnet run`
* Open Chrome Developer Tools
* Open https://localhost:5001/fetchdata
* Request will be executed as page opened

### Exceptions (if any)
Request info in browser console: GET https://localhost:5001/WeatherForecast net::ERR_ABORTED 500

### Further technical details
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  old runtimes skipped
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
@kjpou1 FYI

**Comment by amityagov** [comment]
Hello, looks like this is not bug at all. It is the way Chromium based browsers deal with responses. It will not load response body unless it is really need. So after reading headers and check Status Code with response.EnsureSuccessStatusCode() response reading will be cancelled.

**Comment by lewing** [comment]
@kjpou1 ping

**Comment by kjpou1** [comment]
Not able to reproduce this scenario yet.  Still looking at it.

**Comment by kjpou1** [comment]
@amityagov Where did you find the information for that on Chromium browsers

**Comment by kjpou1** [comment]
Also, I remember that response body would not be available is using redirects.  Is that something that is happening?

**Comment by kjpou1** [comment]
This is the error I am getting with the repro

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[blazor_http_500_aborted.Shared.WeatherForecast[], blazor-http-500-aborted.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[blazor_http_500_aborted.Shared.WeatherForecast[], blazor-http-500-aborted.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[WeatherForecast[]](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[WeatherForecast[]](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.<ReadAsync>d__20`1[[blazor_http_500_aborted.Shared.WeatherForecast[], blazor-http-500-aborted.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__3`1[[blazor_http_500_aborted.Shared.WeatherForecast[], blazor-http-500-aborted.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[blazor_http_500_aborted.Shared.WeatherForecast[], blazor-http-500-aborted.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at blazor_http_500_aborted.Client.Pages.FetchData.OnInitializedAsync() in /Users/Jimmy/websharp/projects/blazor-http-500-aborted/Client/Pages/FetchData.razor:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)


```

**Comment by amityagov** [comment]
@kjpou1 
Hello, 
No, no redirects intended. Just data loading with ajax. 

I did not find any information about Chrome, this is just my conclusion based on a comparison of the browser behavior of Firefox and Chrome. But in the following article there is an indirect confirmation of the situation.

https://groups.google.com/a/chromium.org/g/chromium-dev/c/Fal1ZJnTgGQ/m/UDdxbrf_Rv4J
>The error code net::ERR_ABORTED is intended to only be generated when a user action causes
a load to be interrupted.  

Maybe load interuption caused by exception thrown after  response.EnsureSuccessStatusCode()

> This is the error I am getting with the repro

This is call stack from console. I do not know how, but it is different from the one presented by you.

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Response status code does not indicate success: 500 (Internal Server Error).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[blazor_http_500_aborted.Shared.WeatherForecast[], blazor-http-500-aborted.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at blazor_http_500_aborted.Client.Pages.FetchData.OnInitializedAsync() in D:\tests\blazor-http-500-aborted\Client\Pages\FetchData.razor:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by kjpou1** [comment]
Yeah, not sure why the repo project is not running here.

**Comment by kjpou1** [comment]
Could you post a screen of the difference between chrome and firefox browsers?

**Comment by amityagov** [comment]
@kjpou1 
https://imgur.com/a/Xk4meEX

**Comment by kjpou1** [comment]
Ok, finally able to recreate.  Now need to see what is happening in different browsers.

**Comment by kjpou1** [comment]
Have more information for you.  Was able to finally recreate what you were seeing.  Did not understand at first what exactly you were describing.

The actual fetch code that works like the HttpClientHandler for browser is more or less the following:

```
                onFetchClick: function ()
                {
                    const controller = new AbortController();
                    const { signal } = controller;

                    var headers = new Headers();

                    var fetchExtraArgs = { method: "GET",
                        headers: headers,
                        signal,
                        redirect: "follow",
                        mode: 'no-cors' // 'cors' by default
                    };
                    var fetchArgs = [null, [ "https://localhost:5001/WeatherForecast", fetchExtraArgs   ]];

                    var myfetch = window["fetch"];

                    var m = myfetch ["apply"];
                    if (typeof m === "undefined")
                        throw new Error("Method: '" + js_name + "' not found for: '" + Object.prototype.toString.call(obj) + "'");

                    var res = m.apply (myfetch, fetchArgs)
                    .then(response => {
                        if (!response.ok) {
                            // this seems to be what keeps the the preview from being displayed.
                            controller.abort();
                        }
                        return response.arraybuffer();
                    })
                    .then(data => {
                        console.log(data)
                    })
                    .catch(error =>
                        {
                            console.error(error);
                            console.log(window.location);
                        }
                    )

                    console.log(window.location);

                },
```

When we have a response code that is not ok then we do.

```
                            // this seems to be what keeps the the preview from being displayed.
                            controller.abort();
```

Now that we have identified more or less where this happening or not happening as the case may be, is the above code causing you issues with your application?  

Can you be more specific on what needs to be done so that your application can run correctly.

**Comment by kjpou1** [comment]
FireFox

Fetch code above with abort code:

![image](https://user-images.githubusercontent.com/640466/96419186-119b1280-11f4-11eb-807a-da94312f16cd.png)

![image](https://user-images.githubusercontent.com/640466/96419265-2ecfe100-11f4-11eb-98b1-a778283058a3.png)


Fetch code without abort code:

![image](https://user-images.githubusercontent.com/640466/96419314-40b18400-11f4-11eb-9709-714cc05da2f9.png)

![image](https://user-images.githubusercontent.com/640466/96419352-4e670980-11f4-11eb-80e1-97b1a47a0ac4.png)

**Comment by kjpou1** [comment]
Firefox with just the following line:

![image](https://user-images.githubusercontent.com/640466/96419886-0694b200-11f5-11eb-8d60-0366b68d7c31.png)

Network information:

![image](https://user-images.githubusercontent.com/640466/96419754-db11c780-11f4-11eb-912b-0fe715f784e4.png)

![image](https://user-images.githubusercontent.com/640466/96419774-e238d580-11f4-11eb-89b7-67d664172d89.png)

**Comment by kjpou1** [comment]
Chrome

Chrome based fetch from js code above same as firefox without abort() code execution.

![image](https://user-images.githubusercontent.com/640466/96422288-1cf03d00-11f8-11eb-8f83-65006af5efa2.png)

![image](https://user-images.githubusercontent.com/640466/96422410-4610cd80-11f8-11eb-8e7f-d3757b61e079.png)

**Comment by kjpou1** [comment]
Chrome 

With the same js fetch code above executing abort() same as firefox;

![image](https://user-images.githubusercontent.com/640466/96422735-aef84580-11f8-11eb-9dd9-d40ac84ce1ff.png)

![image](https://user-images.githubusercontent.com/640466/96422791-c6373300-11f8-11eb-8ce3-c33c01d3ee5b.png)

**Comment by kjpou1** [comment]
This above screen shots are executing fetch javascript code and not going through blazor nor managed c# code.  This seems to coincide with the same code running through managed code.

**Comment by amityagov** [comment]
@kjpou1 

Firefox
>Network Error when attempting to fetch resource

Does it mean that no connection to server actually made? 
That is not about internal server error, i think.

**Comment by kjpou1** [comment]
no idea actually.  It is the network tab I was looking at

**Comment by kjpou1** [comment]
> Same request executed by hand shows response data in Response tab in Network tab.
```
fetch('https://localhost:5001/WeatherForecast')
```

**Comment by kjpou1** [comment]
I am going to close this.  Please feel free to reopen if need be.

**Comment by kjpou1** [comment]
No more information received.  Closing
