### ISSUE TITLE
Proposal: Support delegate signature equivalence

### ISSUE THREAD

**Issue by HaloFour** [dotnet/runtime#4331]
See [Roslyn:  Convert delegate types with compatible signature automatically](https://github.com/dotnet/roslyn/issues/3661)

Currently the various CLR compilers do not permit treating one delegate of a specific signature as the same as another delegate of an identical signature.  The compilers that do (VB.NET) do so by wrapping the existing delegate instance with the new delegate which incurs a performance penalty at the time of invocation.

It appears that for whatever reason, accidentally or otherwise, the CLR/JIT have no real issue using one delegate in place of another.  The verifier does complain that an unexpected type is on the stack for the specified call but otherwise the program does execute.

I propose that the verifier be modified that if the type expected and the type on the stack are different but are both delegate types, and that the `Invoke` method on both delegates share the same signature that the verifier allow the operation.

This would permit delegates of identical signatures to be considered equivalent without the performance penalty either at the time of conversion or the time of invocation.

**Comment by dmitriyse** [comment]
Do we have some progress on this feature?
In BCL itself and in a huge amount of other libs we can find a code like this:
```CSharp
    if (obj is Action){ ... }
    else if (obj is Task) { .... }
```
if inside the ```obj``` is any non ```Action``` delegate like ```delegate void MyAction()```, this code will be broken.

Approaches:
 * make ```is```, ```as``` and ```cast operator``` behave especially for delegates with equivalent signature (still problem with ```obj.Type.Name == "Action"``` code)
 * Special Annotation and a compiler suport

```CSharp
// The same annotation technique as for "Nullable" or "Dynamic" for generics support.
public class SupportEquivalenceAttribute: Attribute
{
}

// C# syntax
public void MyNewMethod(var Action a)
{
   ....
}

// IL representation:
public void MyNewMethod([SupportEquivalence]Action a)
{
        if (a.Type.Name == "Action") // Compiler warning or error, because in a could contain different type of delegate
        {
        }
}

public void MyOldMethod(Action a)
{
       
}

delegate void MyAction();
public void MyCode()
{
    MyAction action = ()=>Console.WriteLine("HelloWorld");
    MyOldMethod(action); // Compiler Error!
    MyNewMethod(action) // Works, as implementation of MyNewMethod declares that it's support "Delegate equivalence feature".
}
```
