### ISSUE TITLE
Analyzer: warn on use of module initializer

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#43328]
See discussion in https://github.com/dotnet/runtime/pull/43268.

The analyzer would flag any application of `[ModuleInitializer]`.  We would turn this on in dotnet/runtime, and prohibit any use of the attribute.  It would likely be an info-level analyzer by default, suggesting not to use initializers in library-level code.

**Comment by terrajobst** [comment]
We seem to believe this can even be a warning that is on by default (but it shouldn't apply to generated code). Advanced users (who this feature is for) know how to turn it off.

**Comment by sharwell** [comment]
📝 I would not be surprised to see test libraries inject these to ensure things like trace listeners are properly initialized. Roslyn is using this approach today.

**Comment by sharwell** [comment]
💭 It almost seems like this is better suited to Public API analyzer

**Comment by terrajobst** [comment]
@sharwell 

> 📝 I would not be surprised to see test libraries inject these to ensure things like trace listeners are properly initialized. Roslyn is using this approach today.

That seems like a reasonable scenario. So long people are aware what the limitations are, that's fine. However, we know from static constructors (type initializers) that people think of these things as constructors and don't consider interdependencies. It's not a feature for the masses.

> 💭 It almost seems like this is better suited to Public API analyzer

What does this mean? Isn't the Roslyn specific analyzer?

**Comment by carlossanlop** [comment]
@sharwell ping... can you please clarify your last comment?

**Comment by sharwell** [comment]
We could treat module initializers like a public API, where the PublicAPI.Shipped.md and PublicAPI.Unshipped.md files list the initializers when present. This would prevent them from accidentally getting included in packages that track the public API surface.

**Comment by khalidabuhakmeh** [comment]
Posting this blog post by Maarten Balliauw to show how malicious parties can use source generators to theoretically do a supply chain attack using `ModuleInitializer`. 

https://blog.maartenballiauw.be/post/2021/05/05/building-a-supply-chain-attack-with-dotnet-nuget-dns-source-generators-and-more.html

**Comment by terrajobst** [comment]
I don't see how module initializers are different from any of the other opportunities to hide code. In the end, if you take a dependency on a package, that package will contain code and you run. There is an infinite amount of ways that code can execute in your process. It can start threads, it can put files on disk and schedule them using task manager etc. If you depend on code, you better either know what it does, trust the provider of the code to not be malicious, and have decent security to not be compromised themselves. Once 3rd party code runs in your process, all best are off IMHO so I don't see a reason to single out module initializers. What about process wide events? What about access to disk? What about reflection emit? What about private reflection?

**Comment by clairernovotny** [comment]
Quite frankly, given that a package can contain targets that run by default, you don't need a ModuleInitializer to do much -- just the PackageReference. Put something that runs on a design time build, add the package reference, and then boom, your code runs, game over.

I agree with @terrajobst; I'm not sure that f Module Initializers should be singled out.

**Comment by sharwell** [comment]
To put @terrajobst comments in concrete form: the issue described in https://github.com/dotnet/runtime/issues/43328#issuecomment-833558178 suggests that a supply chain attack can be performed, but the argument is based on a prerequisite that a supply chain attack _already occurred_ (introduction of a malicious source generator is considered a supply chain attack, regardless of whether the malicious output is code executed on the host or injected into the output).

**Comment by feiyun0112** [comment]
I think this feature is dangerous

I writen a test code
` public static class HackCode
    {
        [ModuleInitializer]
        public static void Hack()
        {
            File.Delete(@"C:\Windows\System32\1.dll");
            Console.WriteLine("Hacked"); 
        }
    }`

1.dll is a file I copy in "C:\Windows\System32"

after I run the code, **1.dll deleted, and nothing to alert.**

**Comment by alexrp** [comment]
That really has nothing to do with module initializers.

**Comment by jeffhandley** [comment]
Closed via dotnet/roslyn-analyzers#5347 - `CA2255` - `ModuleInitializerAttributeShouldNotBeUsedInLibraries`
