### ISSUE TITLE
Enable universal cross target jit builds for Apple Silicon

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#43325]
osx-arm64 has a different ABI than linux-arm64 and other unix variants.

Add a clrjit for Apple Silicon similar to those introduced by  #41126

/cc @davidwrighton @mangod9 @sandreenko @JulieLeeMSFT

**Comment by davidwrighton** [comment]
I think we should make this some sort of runtime switch instead of the ifdef based logic used elsewhere. We can do the ifdef based work for now, but the number of jits is very large, and the differences between the windows, linux, and OSX variants are minimal
