### ISSUE TITLE
Issue in getting timezone info when hosted in Linux

### ISSUE THREAD

**Issue by bachi206** [dotnet/runtime#43326]
Below method is giving TimeZoneInfo when we hosted in windows but it is failing to give timezone infor  when we hosted in Linux

TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time")

Error:  **The time zone ID 'Pacific Standard Time' was not found on the local computer**

**Comment by tarekgh** [comment]
@bachi206 thanks for reporting the issue, you may look at https://github.com/dotnet/runtime/issues/14929 for more details but to summarize, you can use the library https://github.com/mj1856/TimeZoneConverter for that. In the future releases we are planning to support that inside our core libraries.

**Comment by bachi206** [comment]
Thank you @tarekgh
