### ISSUE TITLE
FrameworkReference element does not use the TargetFramework for the appropriate version. 

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#43324]
### Description
Not sure if this goes here or in the aspnetcore repo as it deals with moving System.IO.Pipelines from the Microsoft.AspNetCore.App shared framework to Microsoft.NETCore.App shared framework.

As discussed by @davidfowl in this issue https://github.com/dotnet/aspnetcore/issues/24392 System.IO.Pipelines was moved from Microsoft.AspNetCore.App to Microsoft.NETCore.App. I have found at runtime this works for us but it breaks compile time if the environment has .NET 5 installed.

In my context this affects the [Amazon.Lambda.AspNetCoreServer](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer) used at AWS to run ASP.NET Core applications in a serverless environment. Below is a simplified use case.

Given this csproj file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

and code file 

```csharp
namespace PipelinesTest
{
    public class Class1
    {
        public Class1()
        {
            var pipe = new System.IO.Pipelines.Pipe();
        }
    }
```

This compiles in an environment that just has .NET Core 3.1 or a global.json file forcing 3.1. Once I install .NET 5 in my environment the code fails to compile even though I'm not targeting .NET 5 with the following error messages.

```
C:\Users\normj\source\repos\PipelinesTest\PipelinesTest\Class1.cs(11,38): error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [C:\Users\normj\source\repos\PipelinesTest\PipelinesTest\PipelinesTest.csproj]
```

My assumption is the `FrameworkReference` used in the csproj file is always pointing to the latest version installed and not the latest patch for the target framework. Since System.IO.Pipelines was removed out of Microsoft.AspNetCore.App and into Microsoft.NETCore.App it fails to find the System.IO.Pipelines in the .NET 5 Microsoft.AspNetCore.App shared framework. 

### Configuration

.NET 5 SDK. Test with both RC1 and nightly build of RC2.

### Regression?

Yes, libraries build successful when .NET 5 is not installed. Once .NET 5 is installed the build breaks even though nothing is targeting .NET 5.

### Other information

I can add a NuGet reference to System.IO.Pipelines but now that means System.IO.Pipelines.dll will be included in the publish bundle and we really want to reduce unnecessary assemblies in the deployment bundle. Also not sure if the version put in the publish bundle from the NuGet package will be prejitted.

**Comment by wtgodbe** [comment]
This is a known bug with the 5.0 SDK, where it's referencing an older 3.1 AspNetCore targeting pack (https://github.com/dotnet/sdk/issues/14019). We're fixing this for the RTM SDK, but for now you can try the following to exclude the .dll from the package from your output dir:

```
<PackageReference Include="System.IO.Pipelines" version="{version}">
      <IncludeAssets>compile</IncludeAssets>
</PackageReference>
```
