### ISSUE TITLE
Runtime pack's symbol packages contain unsigned DAC/DBI's on arm/arm64

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#43338]
@mmitche reported that the runtime packs symbols have unsigned DAC/DBI bits on arm and arm64. We'd need to investigate this. Dump analysis/collection could be affected if true. 

@dotnet/dotnet-diag

**Comment by tommcdon** [comment]
This issue affects cross-platform, cross-architecture coreclr debugger libraries (specifically debugging linux arm64/arm32 dumps on windows x64/x86, respectively).
