### ISSUE TITLE
Avoid unconditional eager initialization of ReusableTextReader in System.Environment 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#43337]
Context: https://github.com/dotnet/runtime/pull/43154/files#r503595735

**Comment by jkotas** [comment]
@am11 Are you interested in taking this?

**Comment by am11** [comment]
Sure, thanks for pointing it out, I will take a look.

I think there are two options:

1. initialize property and RTR lazily; on first use.
2. refactor the interop method, so we do not need to pass specialized reader for this path.

**Comment by jkotas** [comment]
I would be best to not cache any buffers for this. Something along your option (2) sounds good to me.

**Comment by jkotas** [comment]
(I would use ArrayPool for any buffers that this needs to use.)

**Comment by am11** [comment]
@jkotas, I attempted to replace `ReusableTextReader` completely from source code and replaced the explicit buffer allocation with `ArrayPool<T>`: https://github.com/dotnet/runtime/compare/master...am11:feature/cleanup/purge-reusabletextreader. Quick performance numbers from Environment.WorkingSet benchmark show a slight regression:

|     Method |        Job |                                                                       Toolchain |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | MannWhitney(3ms) | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------- |----------- |-------------------------------------------------------------------------------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|----------------- |--------:|-------:|------:|------:|----------:|
| WorkingSet | Job-CNDQUC |   /runtime_base/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun | 13.65 us | 0.349 us | 0.373 us | 13.52 us | 13.25 us | 14.43 us |  1.00 |             Same |    0.00 | 0.2696 |     - |     - |   2.26 KB |
| WorkingSet | Job-ZSTZST | /runtime_pr/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun | 14.14 us | 0.534 us | 0.594 us | 13.88 us | 13.40 us | 15.57 us |  1.04 |             Base |    0.06 | 0.2699 |     - |     - |   2.26 KB |

If this is an acceptable, I can issue a PR. :)

**Comment by jkotas** [comment]
Yes, submit the PR please.

This code as is has correctness bug. Fixes for correctness bugs often makes the code slower and that's fine. Correctness is more important than performance.
