### ISSUE TITLE
Add verbose dumping if  `gtFoldExpr` changes the expression.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#43348]
`GenTree* Compiler::gtFoldExpr(GenTree* tree)` does not print anything when it folds an expression and does not call `DEBUG_DESTROY` on nodes that it throws away.
The task is to refactor `gtFoldExpr*` to do `JITDUMP` and `DEBUGDESTROY` to makes these transformations observable with `COMPlus_JitDump`.

category:implementation
theme:debug-dumps
skill-level:beginner
cost:small

**Comment by TaurahSP** [comment]
@sandreenko  hi can i grab this one?

**Comment by sandreenko** [comment]
Hi @TaurahSP, sure. Do you still want to work on #42801 as well or you want this one instead?

**Comment by TaurahSP** [comment]
@sandreenko This one only, already unassigned myself from the other one. Thanks

**Comment by TaurahSP** [comment]
@sandreenko  can you give me a little overview what this file and function is doing? Thanks

**Comment by sandreenko** [comment]
Sure, sorry for the late response due to my vacation. 

So `gtFoldExpr*` are folding trees like: 
```
               [000138] ------------                    \--*  ADD       int  
               [000135] ------------                       +--*  LCL_VAR   int  (AX) V36 tmp1         
               [000137] ------------                       \--*  CNS_INT   int    0
```
into 
``` 
[000135] ------------                       +--*  LCL_VAR   int  (AX) V36 tmp1  
```
and after such transformation `000138` and `000137` become dead, so `DEBUGDESTROY` is better be called on them.

also, right now we don't print anything when we fold an expression, so such transformations are hard to catch. It would be useful to add a debug printing (using JITDUMP), like 
```
const unsigned origTreeID = tree->gtTreeID;
...do transformations...
if (verbose && (tree->gtTreeID != origTreeID))
{
  printf("the tree [%06u] was folded into:\n", origTreeID);
  gtDispTree(tree);
}
```

**Comment by SingleAccretion** [comment]
@TaurahSP would it be OK for me to take this over?

**Comment by TaurahSP** [comment]
@SingleAccretion  Sure
