### ISSUE TITLE
Update Android RID graph to reflect different posix implementation

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#43347]
Right now [Android](https://github.com/dotnet/runtime/blob/1c4f3111a40907d91efd42b2fe549e36af58ac78/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json#L550-L556) RID derives directly from `linux` which is incorrect because in the existing schema `linux` actually means `linux-glibc` C standard library.

We have precedent with [Alpine](https://github.com/dotnet/runtime/blob/1c4f3111a40907d91efd42b2fe549e36af58ac78/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json#L2) which derives from `linux-musl` and we should do same for Android to derive from `linux-bionic` instead of `linux` directly.

@ericstj @janvorli

**Comment by ericstj** [comment]
Are there other platforms which use `bionic`?  In other words, what sort of reuse will you gain by this indirection vs folks just using `android` to mean the same thing?

**Comment by marek-safar** [comment]
Very minimal right now, this is more correctness issue than anything else.

**Comment by ericstj** [comment]
I don’t think will add another RID in between Linux and android if there’s no use case for it.  If there’s a specific case for sharing that this would enable then we would consider it.  There’s an infinite number of hypothetical characteristics we could model in the RID graph. We only do so when it makes sense to enable sharing.  It’s big enough already.
