### ISSUE TITLE
Infrastructure - Rollout (November 2020)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#43351]
# Overview

We use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. Changes will be merged on the **first Monday of the month (11/2)**.

| Change |  Impact | Assignee |
| --- | --- | --- |
|  #41897  | Enable using the Ninja generator as an option instead of Visual Studio on Windows builds. | @jkoritzinsky |
|  #43651  | Changing Windows_NT -> Windows for enabling TargetPlatformMoniker feature of the sdk for platform specific tfms | @Anipik |
## Archive
- [September 2020](https://github.com/dotnet/runtime/issues/39788)
- [July 2020](https://github.com/dotnet/runtime/issues/37706)
- [June 2020](https://github.com/dotnet/runtime/issues/35895)
- [May 2020](https://github.com/dotnet/runtime/issues/35202)
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by srxqds** [comment]
this is .net6 preview1?

**Comment by ViktorHofer** [comment]
No, this issue summarizes monthly infrastructure changes that affect developers working in this repository.

**Comment by ViktorHofer** [comment]
The rollout is now completed.
