### ISSUE TITLE
Adding assembly level UnsupportedOSPlatform("browser") System.Security.Cryptography.Primitives is not correct, HashAlgorithm supported on browser

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#43380]
Adding assembly level UnsupportedOSPlatform("browser") System.Security.Cryptography.Primitives is not correct, HashAlgorithm and HashAlgorithmName supported on browser cc @jeffhandley 

`The issue appears to be that we are generating the attribute for all of System.Security.Cryptography.Primitives which is not correct.` _Originally posted by @lewing in https://github.com/dotnet/runtime/pull/43363#discussion_r504305041_

**Comment by lewing** [comment]
HashAlgorithm and HashAlgorithmName are currently marked as unsupported on browser but are available for use. Absent a compelling reason I don't think we should annotate the other primitives that don't include any implementation as unsupported either.

/cc @steveisok @marek-safar

**Comment by kjpou1** [comment]
From my understanding of the Primitives they are there for use of the other Cryptography modules so can be available for use as well.

**Comment by lewing** [comment]
@kjpou1 please review the primitive classes, especially where they base classes, and correct the platform annotations.

**Comment by kjpou1** [comment]
This should be only needed to remove the os platform not supported.  The classes are abstract and implemented in the other cryptography modules.

**Comment by akoeplinger** [comment]
Shouldn't we still mark the static methods on some of these classes as unsupported that we know don't work:

```csharp
namespace System.Security.Cryptography
{
    public abstract partial class AsymmetricAlgorithm : System.IDisposable
    {
        public static System.Security.Cryptography.AsymmetricAlgorithm Create() { throw null; }
        public static System.Security.Cryptography.AsymmetricAlgorithm? Create(string algName) { throw null; }
    }
    public abstract partial class HMAC : System.Security.Cryptography.KeyedHashAlgorithm
    {
        public static new System.Security.Cryptography.HMAC Create() { throw null; }
        public static new System.Security.Cryptography.HMAC? Create(string algorithmName) { throw null; }
    }
    public abstract partial class KeyedHashAlgorithm : System.Security.Cryptography.HashAlgorithm
    {
        public static new System.Security.Cryptography.KeyedHashAlgorithm Create() { throw null; }
        public static new System.Security.Cryptography.KeyedHashAlgorithm? Create(string algName) { throw null; }
    }
    public abstract partial class SymmetricAlgorithm : System.IDisposable
    {
        public static System.Security.Cryptography.SymmetricAlgorithm Create() { throw null; }
        public static System.Security.Cryptography.SymmetricAlgorithm? Create(string algName) { throw null; }
    }
}
```

**Comment by lewing** [comment]
@akoeplinger that is an interesting question.  Create() on all those classes is marked Obsolete and throw PNSE unconditionally on all platforms already
https://github.com/dotnet/runtime/blob/2ca0b935aba3933bf0f22c30dbd3f86c34057a8d/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/AsymmetricAlgorithm.cs#L17

Create(string name) should probably be marked.
