### ISSUE TITLE
Test failure: Microsoft.Extensions.Hosting.Internal.HostTests.BackgroundServiceAsyncExceptionGetsLogged

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43389]
failed in job: [ runtime-coreclr libraries-jitstress 20201013.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=850308&view=ms.vss-test-web.build-test-results-tab&runId=27099406&paneView=debug&resultId=104269)

net6.0-Linux-Release-x64-CoreCLR_checked-no_tiered_compilation-Ubuntu.1804.Amd64.Open

Error message
~~~
'BackgroundService failed' did not get logged
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.Hosting.Internal.HostTests.BackgroundServiceAsyncExceptionGetsLogged() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs:line 1256
~~~

**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL.

**Comment by ViktorHofer** [comment]
Failed again in https://dev.azure.com/dnceng/public/_build/results?buildId=857798&view=ms.vss-test-web.build-test-results-tab&runId=27454930&resultId=102001&paneView=debug.

Configuration: `net6.0-Linux-Debug-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open`

Is this actually code gen related?

cc @maryamariyan @eerhardt

**Comment by eerhardt** [comment]
I’ll take a look. The timeout might need to be increased because checked builds run so much slower.

**Comment by eerhardt** [comment]
@JulieLeeMSFT @kunalspathak -

This looks really similar to https://github.com/dotnet/runtime/issues/43576. In both cases, the test is waiting for some asynchronous operation to occur for a set amount of time. In this test, it is 5 seconds. In #43576 it is 10 seconds.

Both cases are CoreCLR checked no tiered compilation. Did something recently slow down this configuration? Do we need to increase the timeouts for both?

**Comment by kunalspathak** [comment]
@eerhardt - I didn't get chance to investigate. The earliest I will be able to take a look will be tomorrow.

**Comment by kunalspathak** [comment]
Alright, I did some investigation on this. The test failure doesn't fail in JitStress mode, but fails with just tiered compilation off. From [the console logs](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-cabf890fd6ae48c4a4/Microsoft.Extensions.Hosting.Unit.Tests/console.f9e16864.log?sv=2019-07-07&se=2020-11-02T07%3A52%3A52Z&sr=c&sp=rl&sig=MacG0Fs7PPwbVEyHqQZ5%2B7wOBbbuNMwtpttOWjZt5N4%3D).
```
+ export __TestEnv=/home/helixbot/work/C0490A08/p/SetStressModes_no_tiered_compilation.sh
+ cat /home/helixbot/work/C0490A08/p/SetStressModes_no_tiered_compilation.sh
```
In [recent test run](https://dev.azure.com/dnceng/public/_build/results?buildId=859619&view=logs&j=b02ddad0-c847-5898-a3e9-29c2612003f0&t=d27c58e0-d37d-5f1f-22ea-7aef571dd6f2) that happened on 10/20, the test passed. You can check the [testresults.xml](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a58a6048bead48eab8/Microsoft.Extensions.Hosting.Unit.Tests/testResults.xml?sv=2019-07-07&se=2020-11-09T07%3A43%3A08Z&sr=c&sp=rl&sig=9mnGDXJtjWFqzsNH3t4WJhFFcaz90YPH%2FtH%2F3rAlQSU%3D) here for that run in which test passed:

```xml
<test name="Microsoft.Extensions.Hosting.Internal.HostTests.BackgroundServiceAsyncExceptionGetsLogged" type="Microsoft.Extensions.Hosting.Internal.HostTests" method="BackgroundServiceAsyncExceptionGetsLogged" time="0.4297531" result="Pass"/>
```

I also tried reproing it on my local machine with maxThreads=2 and the test passed. So most likely the test depends on the environment and looks flaky. It looks like the test was recently added in https://github.com/dotnet/runtime/pull/42981 , so we might have not got enough runs to conclude that the test is flaky. 

So, it doesn't look like codegen issue. I am removing the labels from this issue.

**Comment by eerhardt** [comment]
So it sounds like with checked, no tiered compilation the CLR is slow enough that the timeout in the test needs to be increased. Today we are waiting for 5 seconds, which isn't long enough in this "slow" mode.

**Comment by kunalspathak** [comment]
> So it sounds like with checked, no tiered compilation the CLR is slow enough

It appears that the slowness is only sometimes and not always, which basically means that the test is time sensitivity and might give different result depending on the environment.

**Comment by ViktorHofer** [comment]
Seeing this again in: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5b189d3203124e8a92/Microsoft.Extensions.Hosting.Unit.Tests/console.12434f67.log?sv=2019-07-07&se=2020-11-20T20%3A33%3A29Z&sr=c&sp=rl&sig=eO0uA9S8OKpYDqPO68mN5nDZ5R2A%2FXXt20Htf9QFMNY%3D

**Comment by eerhardt** [comment]
@ViktorHofer - that error trace is actually different than the original bug, but we can continue to use this issue to track the new problem.

What PR and leg was this run on?

It looks like the issue is that the "background" exception is not being thrown on the background - but instead synchronously.

https://github.com/dotnet/runtime/blob/8ed2e953f6b2142cbdef25c157c6425f508b373f/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs#L1371-L1378

Since there is a `Task.Delay(1)` in there, the exception shouldn't be occurring inline - but according to the above stacktrace, it is occurring inline.

**Comment by ViktorHofer** [comment]
@eerhardt sorry took me a bit longer. Santi helped me to find the build id.

Here's the build: https://dnceng.visualstudio.com/public/_build/results?buildId=872294&view=ms.vss-test-web.build-test-results-tab.

Configuration: `net6.0-Linux-Release-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59`

**Comment by am11** [comment]
Happened again in windows x86 Debug: [helix logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43804-merge-c3a2d8db9dc64a0082/Microsoft.Extensions.Hosting.Unit.Tests/console.6df46711.log?sv=2019-07-07&se=2020-12-09T07%3A09%3A21Z&sr=c&sp=rl&sig=bllEY4DV2IuQjSaXVGakCvdCI6JgRxw67fRRpozRWKk%3D) (on top of 7 hours old master - 21f32f08097d15020298689b687ff0296b3f039e)
```
C:\h\w\B71509CA\w\AB5E0927\e>"C:\h\w\B71509CA\p\dotnet.exe" exec --runtimeconfig Microsoft.Extensions.Hosting.Unit.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.Hosting.Unit.Tests.deps.json xunit.console.dll Microsoft.Extensions.Hosting.Unit.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 86 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 2)
    Microsoft.Extensions.Hosting.Internal.HostTests.BackgroundServiceAsyncExceptionGetsLogged [FAIL]
      System.Exception : Background Exception
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs(1377,0): at Microsoft.Extensions.Hosting.Internal.HostTests.AsyncThrowingService.ExecuteAsync(CancellationToken stoppingToken)
        /_/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs(54,0): at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
        /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostBuilderExtensions.cs(30,0): at Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions.StartAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
        /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostBuilderExtensions.cs(18,0): at Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions.Start(IHostBuilder hostBuilder)
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs(1231,0): at Microsoft.Extensions.Hosting.Internal.HostTests.BackgroundServiceAsyncExceptionGetsLogged()
        --- End of stack trace from previous location ---
info: Microsoft.Extensions.Hosting.Tests.HostTests[0]
```

**Comment by eerhardt** [comment]
@stephentoub - do you have any idea how this exception could be thrown inline? We are awaiting Task.Yield:

https://github.com/dotnet/runtime/blob/cb8c8ec6435f3db3e982382ca2e82017271d0a0a/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs#L1373-L1377

**Comment by stephentoub** [comment]
Yes.  The `await Task.Yield()` will force the containing async method to complete asynchronously, but callers checking that Task's IsCompleted (either explicitly or as part of awaiting it) may see it completed by the time they check.  Simple example of that:
```C#
using System;
using System.Threading.Tasks;

int sync = 0, async = 0;
for (int i = 0; i < 1_000_000; i++)
{
    Task t = YieldsAsync();
    if (t.IsCompleted) sync++;
    else async++;
    await t;
}
Console.WriteLine($"Sync: {sync:N0} Async: {async:N0}");

static async Task YieldsAsync()
{
    await Task.Yield();
}
```
This will obviously yield different results on every execution, but a typical example from my machine:
```
Sync: 30,719 Async: 969,281
```

**Comment by eerhardt** [comment]
Thanks, this makes sense.

I'll switch this test code back to using `Task.Delay` and increase the delay time to `50ms`, which should be long enough that the task shouldn't complete before the calling code can check it, but still short enough that the test runs quickly.
