### ISSUE TITLE
Blazor webassembly on DotNet 5 rc2 missing globalization for Bosnian month names

### ISSUE THREAD

**Issue by adopilot** [dotnet/runtime#43398]
I upgraded my Blazor webassembly project to .Net5 RC2 (from .Net5 RC1) and I did notice that month names for my (Bosnian) ui culture are wrong.

Here is steps to reporduce:

In Main metoh of Program class I do set cultures to Bosninan

```
            CultureInfo.CurrentCulture = new CultureInfo("bs");
            CultureInfo.CurrentUICulture = new CultureInfo("bs");
            CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("bs");
            CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("bs");

```

On any razor page when I try to get long date:

```
<p>Current UI Culture: <strong>@CultureInfo.CurrentUICulture.DisplayName</strong></p>
<p>Current Culture: <strong>@CultureInfo.CurrentCulture.DisplayName</strong></p>
<p>Sada je  @DateTime.Now.ToLongDateString() </p>
```
![image](https://user-images.githubusercontent.com/4448913/95976007-361f7500-0e17-11eb-9ce0-47c3722debb5.png)

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by EgorBo** [comment]
@lewing what is the strategy to address such issues? Just add the missing locales?
`bs` is not presented in the [list of locales](https://github.com/dotnet/icu/blob/maint/maint-67/icu-filters/icudt.json#L7) we support (and neither in https://developer.chrome.com/webstore/i18n)

**Comment by adopilot** [comment]
@lewing  you mentioned 

>[list of supported locales](https://github.com/dotnet/icu/blob/maint/maint-67/icu-filters/icudt.json#L7) 

If I try to set culture to **sr_Latn_RS** which is on list , in browser console I get error console 

 ```
CultureInfo.CurrentCulture = new CultureInfo("sr_Latn_RS");
CultureInfo.CurrentUICulture = new CultureInfo("sr_Latn_RS");
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("sr_Latn_RS");
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("sr_Latn_RS");
```
```
System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
d.printErr @ blazor.webassembly.js:1
put_char @ dotnet.5.0.0-rc.2.20475.5.js:1
write @ dotnet.5.0.0-rc.2.20475.5.js:1
write @ dotnet.5.0.0-rc.2.20475.5.js:1
doWritev @ dotnet.5.0.0-rc.2.20475.5.js:1
_fd_write @ dotnet.5.0.0-rc.2.20475.5.js:1
write @ 00ab9d9a:0x5ca76
SystemNative_Write @ 00ab9d9a:0x1a70a4
do_icall @ 00ab9d9a:0x194cdc
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
g @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
blazor.webassembly.js:1 sr_Latn_RS is an invalid culture identifier.
```

**Comment by lewing** [comment]
That is a differnt issue.  The culture data is split up to save space so you can't just load any culture at runtime and expect it to work you should be able to enable the full culture by setting <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in your csproj

/cc @pranavkm

**Comment by lewing** [comment]
@EgorBo I think we may just need to document things

**Comment by adopilot** [comment]
> That is a different issue. The culture data is split up to save space so you can't just load any culture at runtime and expect it to work. You should be able to enable that full culture list by setting `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` in your csproj
> 
> /cc @pranavkm

I apologies,I did delete my comment.

**Comment by EgorBo** [comment]
@lewing it's documented here https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#icu-on-webassembly (has a link to list of supported locales)

**Comment by pranavkm** [comment]
Yeah, I didn't realize the app was initializing a new culture. We should probably call that out in our docs.

**Comment by safern** [comment]
> @lewing it's documented here https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#icu-on-webassembly (has a link to list of supported locales)

I think we should add a more detailed description on the options to enable a full globalization experience, like the MSBuild property that @lewing pointed out here, does that make sense?

**Comment by cornem** [comment]
I'm experiencing the same after upgrading to RC2. However, the culture I'm using is `nl`, which is listed in the `icu/optimal.json` file. However, it's doesn't appear to be loaded.

What I'm doing: `DateTime.Today.ToString("dddd d MMMM yyyy", CultureInfo.CreateSpecificCulture("nl"))`, which prints `Thursday 15 October 2020` instead of the localized version.

**Comment by lewing** [comment]
@cornem is that with `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>`  in your .csproj?

**Comment by cornem** [comment]
No, is that required now?

**Comment by lewing** [comment]
@cornem by default Blazor loads a small subset of culture data based on the browser's current language setting.  That option tells blazor to load a subset that is intended to mirror the cultures the browser supports.

**Comment by pranavkm** [comment]
Btw, I've added a note about this in our docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1#blazor-webassembly. It should take another day for the website to update.

**Comment by CoffeeStainJo** [comment]
I'm having the same issue for Norwegian, Bokmål (Norway)” (nb-NO).

To Reproduce:
Create a Blazor WebAssembly hosted app (.net5.0) -- ASP.NET Core version: 5.0.102
![image](https://user-images.githubusercontent.com/7232960/107628686-49c1d780-6c61-11eb-95e9-e9ba87a307e0.png)
Is set in Program.cs 

![image](https://user-images.githubusercontent.com/7232960/107628739-5a724d80-6c61-11eb-9ad4-7d9a7b304d60.png)
Is configured in .csproj

![image](https://user-images.githubusercontent.com/7232960/107629820-f51f5c00-6c62-11eb-8687-3281940b6970.png)
Is added in index.html

![image](https://user-images.githubusercontent.com/7232960/107629703-ca350800-6c62-11eb-8dfc-71e6c67b48b9.png)
Does not include the norwegian codes nb-no and DateTime.Now.ToString() returns 
![image](https://user-images.githubusercontent.com/7232960/107630042-47f91380-6c63-11eb-8513-394e01ad2366.png)
![image](https://user-images.githubusercontent.com/7232960/107630075-57785c80-6c63-11eb-8467-cce64df081e5.png)

**Comment by ilonatommy** [comment]
While "bs" culture is not present on the [whitelist](https://github.com/dotnet/icu/blob/0f49268ddfd3331ca090f1c51d2baa2f75f6c6c0/icu-filters/optimal.json#L6-L54) and default culture is loaded instead for it in the current dotnet:
![image](https://user-images.githubusercontent.com/32700855/173324793-b1634745-e997-4de2-ab24-ddcfd51567ff.png)

"no" is on the list and should work but does not:
![image](https://user-images.githubusercontent.com/32700855/173325002-d11d6e79-cbb3-4a11-ad47-7ad2a818387d.png)

All the other cultures from the whitelist work fine.
