### ISSUE TITLE
[Perf -7%] System.Text.Json.Tests.Perf_Basic (3)

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#43413]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/f2d51b5e15808d2c358a59f24af4fad4a9953656...30e643e2f2433055d6ed433af38a925ee657d4ad)

### Regressions in System.Text.Json.Tests.Perf_Basic

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[WriteBasicUtf16](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Json.Tests.Perf_Basic.WriteBasicUtf16(Formatted%3a%20False%2c%20SkipValidation%3a%20False%2c%20DataSize%3a%20100000).html>) | 1.70 ms | 1.81 ms | 1.06 |  | True
[WriteBasicUtf16](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Json.Tests.Perf_Basic.WriteBasicUtf16(Formatted%3a%20False%2c%20SkipValidation%3a%20True%2c%20DataSize%3a%20100000).html>) | 1.58 ms | 1.73 ms | 1.10 | Bimodal | True
[WriteBasicUtf8](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Json.Tests.Perf_Basic.WriteBasicUtf8(Formatted%3a%20False%2c%20SkipValidation%3a%20True%2c%20DataSize%3a%20100000).html>) | 1.60 ms | 1.70 ms | 1.06 | Bimodal | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Basic_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Basic_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Basic_3.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Basic.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Tests.Perf_Basic*'
```
<details>

#### System.Text.Json.Tests.Perf_Basic.WriteBasicUtf16(Formatted: False, SkipValidation: False, DataSize: 100000)

```log
[1676012.495 ; 1724716.090) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1724716.090 ; 1811955.055) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.Text.Json.Tests.Perf_Basic.WriteBasicUtf16(Formatted: False, SkipValidation: True, DataSize: 100000)

```log
[1570573.834 ; 1609118.439) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1609118.439 ; 1647663.044) | 
[1647663.044 ; 1684280.570) | 
[1684280.570 ; 1753660.623) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.Text.Json.Tests.Perf_Basic.WriteBasicUtf8(Formatted: False, SkipValidation: True, DataSize: 100000)

```log
[1586210.469 ; 1649979.447) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1649979.447 ; 1725195.469) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
These tests seem highly related.

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/271f008f0fe8168dacac45cd3ce1952e6e32bfbb...477363b27c658bc4f89bab3995386760e95ee8ef)


### Regressions in System.Text.Json.Tests.Perf_Deep

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[WriteDeepUtf8](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Json.Tests.Perf_Deep.WriteDeepUtf8(Formatted%3a%20False%2c%20SkipValidation%3a%20True).html>) | 3.70 ms | 4.19 ms | 1.13 | Bimodal | True
[WriteDeepUtf8](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Json.Tests.Perf_Deep.WriteDeepUtf8(Formatted%3a%20False%2c%20SkipValidation%3a%20False).html>) | 3.96 ms | 4.50 ms | 1.13 | Bimodal | True
[WriteDeepUtf16](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Json.Tests.Perf_Deep.WriteDeepUtf16(Formatted%3a%20False%2c%20SkipValidation%3a%20True).html>) | 3.76 ms | 4.13 ms | 1.10 | Bimodal | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Deep_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Deep_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Deep_3.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_13_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Json.Tests.Perf_Deep.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Tests.Perf_Deep*'
```
<details>

### Histogram
#### System.Text.Json.Tests.Perf_Deep.WriteDeepUtf8(Formatted: False, SkipValidation: True)

```log
[3608478.718 ; 3740856.569) | @@@@@@@@@@@@@@@@@@@@@@@
[3740856.569 ; 3935689.937) | @@@@@@@@@@@@@@@
[3935689.937 ; 4091747.846) | @@
[4091747.846 ; 4224125.697) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.Text.Json.Tests.Perf_Deep.WriteDeepUtf8(Formatted: False, SkipValidation: False)

```log
[3877435.393 ; 3975882.737) | @@@@@@
[3975882.737 ; 4101365.441) | @@@@@@@@@@@@@@@@@@@@@
[4101365.441 ; 4228997.869) | @@@@@@@@@@
[4228997.869 ; 4348615.675) | @@
[4348615.675 ; 4474098.379) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[4474098.379 ; 4573076.930) | @@@@@@@@
```
#### System.Text.Json.Tests.Perf_Deep.WriteDeepUtf16(Formatted: False, SkipValidation: True)

```log
[3637807.509 ; 3725277.314) | @
[3725277.314 ; 3841047.475) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3841047.475 ; 3955000.233) | @@@@
[3955000.233 ; 4090024.367) | @@@@
[4090024.367 ; 4205794.527) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by steveharter** [comment]
FWIW a quick git log showed no obvious JSON or encoding changes: ```git log --after="2020-10-1" --before="2020-10-7" --oneline```. The nearest JSON change I saw was https://github.com/dotnet/runtime/commit/527f9ae88a0ee216b44d556f9bdc84037fe0ebda

**Comment by steveharter** [comment]
Please re-verify based on https://github.com/dotnet/runtime/pull/57327. Thanks
