### ISSUE TITLE
Interop.Process.GetProcPath on FreeBSD leaks

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#43418]
https://github.com/dotnet/runtime/blob/035b729d829368c2790d825bd02db14f0c0fd2ea/src/libraries/Common/src/Interop/FreeBSD/Interop.Process.cs#L89-L93

Sysctl may allocate a buffer that the caller needs to free.

**Comment by adamsitnik** [comment]
@stephentoub I've set the milestone to 6.0. If you believe that it could meet the 5.0 please set it to 5.0 (I was offline for a few weeks and I don't know how high is the bar now)

**Comment by stephentoub** [comment]
We don't ship supported freebsd builds.  Definitely not 5.0 :-)

**Comment by stephentoub** [comment]
>  I don't know how high is the bar now

As high as it gets :-)
