### ISSUE TITLE
Compatibility between Microsoft.Office.Interop.Word and .NET 5?

### ISSUE THREAD

**Issue by janniksam** [dotnet/runtime#43426]
So, our company builds an application, that is highly relying on / is tightly coupled to the `Microsoft.Office.Interop.Word` library right now to communicate with Word.

In a way you could say that we wrote a wrapping application around Word and use/control it to let our user edit custom forms / fill some content controls in that we use to generate other documents etc.

Our plans for the application lifecycle are long term, which means that an update to .NET 5 will sooner or later have to come.

**I haven't found much information about it yet, so I will ask:**

I would like to know, if there are any plans on make .NET 5+ Office.Interop compatible.
Or even better: Is it support to use word interop with ..NET 5 and up?

Otherwise we would have to get rid of Word sooner or later.

**Comment by AaronRobinsonMSFT** [comment]
@janniksam Support for COM and Office was added in .NET Core 3.0. See the Excel sample at https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo. Please let us know if there are specific scenarios in Word that do not work. I would recommend opening a new issue with a specific repro if one is found.
