### ISSUE TITLE
Encoding.GetString() with MemoryStream.ToArray() returns nothing when using await using on MemoryStream

### ISSUE THREAD

**Issue by Skyppid** [dotnet/runtime#43444]
### Description

I just reworked our JSON builder class so we could remove Newtonsoft.Json and use the new Utf8JsonWriter instead. I did everything according to this [article](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#use-utf8jsonwriter) on Docs. I use a MemoryStream and later on `Encoding.UTF8.GetString(stream.ToArray())` to retrieve the JSON string generated.

Using this in our application resulted in empty JSON files being generated. I realized that the method simply returned `string.Empty`. What I found out is, that this was the result of using `await using MemoryStream stream = new MemoryStream();`.

By removing just that, it worked. So is this expected behavior and I just don't understand the effects of `IAsyncDisposable` fully yet or is this an actual runtime bug?

### Configuration

We're using .Net Core 3.1.9 on Windows x64 - that only, no other platforms.

### Regression?

Not sure if this ever worked. We just upgraded to 3.1.9 from .Net 4.7.2.

**Comment by jeffschwMSFT** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/43445.  Let me know if that is not the intention.

**Comment by Skyppid** [comment]
Yeah, thanks @jeffschwMSFT there was a server error when I submitted the issue. Obviously it did not get lost but the referenced ticket is the current one.
