### ISSUE TITLE
Encoding.GetString() returns empty string when using with MemoryStream.ToArray() which is 'await using' declared

### ISSUE THREAD

**Issue by Skyppid** [dotnet/runtime#43445]
### Description

(Quick rewrite, since GitHub messed up): We switched from Newtonsoft.Json to System.Text.Json.Utf8JsonWriter. I did it like this [article](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#use-utf8jsonwriter) and the result was not really the same.

The method returned an empty string. So I checked again and figured this might be an issue with `IAsyncDisposable`. I introduced the MemoryStream and the writer with `await using` as it was recommended inside an async method. I'd assume that it disposes after `Encoding.UTF8.GetString(stream.ToArray());` processed the value - just before jumping out of the method. Yet when `await using` is prepended to the initialization of my MemoryStream, the method returns an empty string. Remove the await and it works.

Is this a runtime bug? I'd expect that the scope-less using declaration would dispose after the Encoding and before the actual return label.

I decompiled the source using dotPeek and it looks good.

This is the code:
```
await using MemoryStream stream = new MemoryStream();
await using Utf8JsonWriter writer = new Utf8JsonWriter(stream, new JsonWriterOptions {Indented = false});

writer.WriteStartObject();

// Some writing operations

writer.WriteEndObject();
await writer.FlushAsync(token);

return Encoding.UTF8.GetString(stream.ToArray());
```

### Configuration

We're using .Net Core 3.1.9 on Windows-x64 (and only that).

### Regression?

We just upgraded from .Net 4.7.2 to .Net Core 3.1.9 - so not possible to say.

**Comment by stephentoub** [comment]
> This is the code

Could you share a small, complete repro we could run to see the behavior you describe?

**Comment by Skyppid** [comment]
I tried extracting the code into a seperate app but then it works fine. Seems to be a very specific setting where this occurs. I'll run some tests with our software and try to find out where this originates from. Thing is I can't really provide a sample since this is quite tightly integrated into our software.

**Comment by stephentoub** [comment]
I think it's likely that the data just wasn't in the MemoryStream to begin with, i.e. something in your app didn't do exactly what you thought it would, there was a race condition such that sometimes the data you were expecting to be in the MemoryStream never showed up, something didn't get flushed to the MemoryStream, etc.  Let's close this issue, as at present there's no evidence of a bug in dotnet/runtime, but if you're able to narrow it down to demonstrate there is, please do re-open and we'll be happy to take a look.  Thanks!
