### ISSUE TITLE
Deploying ASP.NET Core 2.1 from Git with Kudu fails due to PDB file locked. 

### ISSUE THREAD

**Issue by SimileoluwaExpert** [dotnet/runtime#43443]
**Description**

This issue is similar to https://github.com/dotnet/corefx/pull/38291#.
The issue was fixed in ASP.NET Core 2.2. 
This is to request a backport to 2.1.

During deployment, when  a new build is deployed from the Kudu hook mapped to a GIT branch in Azure DevOps Git Repo, the deploy script fails because the main PDB file is looked.

The service uses ASPNET Core 2.1 and .Net 4.7.

**Customer Impact**
The impact on customer is such that this affect redeployment and requires a restart of the site after redeployment

**Risk**
Impact on customer deployment

@davidfowl @danmosemsft

**Comment by danmosemsft** [comment]
@davidfowl is looking at porting

**Comment by davidfowl** [comment]
PR opened https://github.com/dotnet/corefx/pull/43003

**Comment by akoeplinger** [comment]
Looks like https://github.com/dotnet/corefx/pull/43003 was merged, can this be closed now?

**Comment by davidfowl** [comment]
Yep
