### ISSUE TITLE
CultureInfo.GetCultures(CultureTypes.AllCultures) returns less items on Blazor WASM .NET 5.0

### ISSUE THREAD

**Issue by ilkayilknur** [dotnet/runtime#43449]
### Describe the bug
I just found out that `CultureInfo.GetCultures(CultureTypes.AllCultures)` method returns only 11 items on Blazor WASM .NET 5 RC2. The same method returns more than 300 items on .NET Core 3.1. Is this a known issue?

### To Reproduce

Call `CultureInfo.GetCultures(CultureTypes.AllCultures)` method on Blazor WASM .NET 5 RC2.
### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- Microsoft Visual Studio Community 2019 Preview Version 16.8.0 Preview 4.0

**Comment by lewing** [comment]
@mkArtakMSFT is the BlazorWebAssemblyLoadAllGlobalizationData setting documented anywhere?  I found it by reading the code when looking into https://github.com/dotnet/runtime/issues/43398

**Comment by lewing** [comment]
@ilkayilknur It is expected.  We've started to document the situation at https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#icu-on-webassembly but that doesn't include some of the details about how the data is split up and only a fraction of it (based on the browser language) is loaded by default.
If you intend to load other cultures than the automatic subset you can include:

`<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>`

in your .csproj.  That will load a larger subset of cultures that is intended to mirror the cultures that are supported by browsers.  We're working to improve the documentation to cover this.

**Comment by tarekgh** [comment]
@ilkayilknur I am wondering, what is your scenario that you need to call GetCultures? I am seeing some pattern of the usage of calling this method which is used in wrong way.

**Comment by lewing** [comment]
@pranavkm has added some [documentation about the option](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#blazor-webassembly)

**Comment by SamMonoRT** [comment]
@lewing @pranavkm - is this still an issue for .NET6 or can be closed ?
