### ISSUE TITLE
SetUserFileEncryptionKey fails for certificates not present in store

### ISSUE THREAD

**Issue by benash** [dotnet/runtime#43458]
When calling `SetUserFileEncryptionKey` with a certificate that doesn't exist in the user's store, I get the strange return value of `0x80092004`. My hope is that calling the function in that way would allow for a sort of ephemeral security that would last for only as long as the process lasted.

**Comment by bartonjs** [comment]
I don't see a `SetUserFileEncryptionKey` method anywhere in the API Catalog.  It seems like maybe your issue is with some other library, and maybe it'd be better to start there?

**Comment by benash** [comment]
This is what I'm referring to: https://docs.microsoft.com/en-us/windows/win32/api/winefs/nf-winefs-setuserfileencryptionkey

**Comment by bartonjs** [comment]
Ah.  0x80092004 is CRYPT_E_NOT_FOUND, which presumably is that the certificate is not found in the store.  That function is part of the Windows OS, not .NET, so there's nothing that .NET can really do about it. (I'm also not really clear with what impact it has, it seems like it's a filesystem modification, so it's global, not per-process).

@richlander You're usually good at knowing where to route things... any idea where the best place for this feature request is?

**Comment by benash** [comment]
@bartonjs Got it, thanks for the helpful clarification.

**Comment by bartonjs** [comment]
Since this is about a Windows routine, not a .NET routine, closing the issue.

Sorry we didn't end up providing routing to get closer to the problem.
