### ISSUE TITLE
[Perf -8%] [Mono] System.Memory.ReadOnlyMemory<Char>.ToArray

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#43465]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/d062c63a06c9581bda50a766f8c12ec0a3c29e69...f353158c2b1fc4c1918b4685932e6dd70870fb64)

### Regressions in System.Memory.ReadOnlyMemory<Char>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[ToArray](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Memory.ReadOnlyMemory(Char).ToArray(Size%3a%20512).html>) | 414.13 ns | 445.70 ns | 1.08 |  | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Memory.ReadOnlyMemory(Char)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Memory.ReadOnlyMemory(Char).html>)

<details>

#### System.Memory.ReadOnlyMemory<Char>.ToArray(Size: 512)

```log
[405.622 ; 449.940) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[449.940 ; 494.257) | 
[494.257 ; 538.575) | 
[538.575 ; 582.892) | 
[582.892 ; 613.776) | 
[613.776 ; 658.093) | @@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/d062c63a06c9581bda50a766f8c12ec0a3c29e69...f353158c2b1fc4c1918b4685932e6dd70870fb64)


### Regressions in System.Memory.Span<Byte>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[ToArray](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Memory.Span(Byte).ToArray(Size%3a%20512).html>) | 185.34 ns | 200.68 ns | 1.08 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Memory.Span(Byte)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Memory.Span(Byte).html>)

<details>

### Histogram
#### System.Memory.Span<Byte>.ToArray(Size: 512)

```log
[175.651 ; 213.367) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[213.367 ; 251.084) | 
[251.084 ; 288.800) | 
[288.800 ; 326.517) | 
[326.517 ; 357.817) | 
[357.817 ; 395.534) | @@@@@@@@@@@@@@@@@@@
[395.534 ; 420.337) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by naricc** [comment]
Appears to be caused by this change: https://github.com/dotnet/runtime/compare/56950ad78347dca556d5e835522ac7ee5f305bd3...f63b6f0a1b3ffd35dc1253226984a8d20bd4d91b

**Comment by naricc** [comment]
Specifically, this change: https://github.com/dotnet/runtime/commit/f63b6f0a1b3ffd35dc1253226984a8d20bd4d91b

Same cause as https://github.com/dotnet/runtime/issues/43477
and
https://github.com/dotnet/runtime/issues/43463

**Comment by SamMonoRT** [comment]
These seem to have improved performance in recent runs. Closing this old issue and will monitor future runs.
