### ISSUE TITLE
CG2 Outerloop Test Failure: Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.cmd

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#43461]
Example run:
https://dev.azure.com/dnceng/public/_build/results?buildId=853947&view=ms.vss-test-web.build-test-results-tab&runId=27279076&resultId=101789&paneView=debug

Tests failing:
Interop\\StructMarshalling\\PInvoke\\MarshalStructAsLayoutExp\\MarshalStructAsLayoutExp.cmd

Platform:
Win10 arm64 runs

Item log:
<pre>
Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.cmd [FAIL]
      Could Not Find D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\composite-r2r.dll.rsp
      Fatal error. Verify_TypeLayout 'ExplicitHFA' failed to verify type layout
         at Managed.MarshalStructAsParam_AsExpByVal(StructID)
         at Managed.RunMarshalStructAsParamAsExpByVal()
         at Managed.Main()
      
      Return code:      1
      Raw output file:      D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\Reports\Interop.StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.output.txt
      Raw output:
      BEGIN EXECUTION
      MarshalStructAsLayoutExp.dll
      MarshalStructAsParam.dll
      TestLibrary.dll
              3 file(s) copied.
      Response file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\\composite-r2r.dll.rsp
      D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\IL\*.dll
      -o:D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\\composite-r2r.dll
      --targetarch:arm64
      --verify-type-and-field-layout
      -O
      -r:D:\h\w\B604099A\p\System.*.dll
      -r:D:\h\w\B604099A\p\Microsoft.*.dll
      -r:D:\h\w\B604099A\p\mscorlib.dll
      -r:D:\h\w\B604099A\p\netstandard.dll
      " "dotnet" "D:\h\w\B604099A\p\crossgen2\crossgen2.dll" @"D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\\composite-r2r.dll.rsp"   --composite"
      Emitting R2R PE file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\composite-r2r.dll
      Emitting R2R PE file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.dll
      Emitting R2R PE file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\TestLibrary.dll
       "D:\h\w\B604099A\p\corerun.exe" MarshalStructAsLayoutExp.dll 
      
      Verify marshal Explicit layout struct as param as ByVal
      Expected: 100
      Actual: -268435457
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\B604099A\p
      > D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Interop.StructMarshalling\Interop.StructMarshalling.XUnitWrapper.cs(140,0): at Interop_StructMarshalling._PInvoke_MarshalStructAsLayoutExp_MarshalStructAsLayoutExp_._PInvoke_MarshalStructAsLayoutExp_MarshalStructAsLayoutExp_cmd()
      Output:
        Could Not Find D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\composite-r2r.dll.rsp
        Fatal error. Verify_TypeLayout 'ExplicitHFA' failed to verify type layout
           at Managed.MarshalStructAsParam_AsExpByVal(StructID)
           at Managed.RunMarshalStructAsParamAsExpByVal()
           at Managed.Main()
        
        Return code:      1
        Raw output file:      D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\Reports\Interop.StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.output.txt
        Raw output:
        BEGIN EXECUTION
        MarshalStructAsLayoutExp.dll
        MarshalStructAsParam.dll
        TestLibrary.dll
                3 file(s) copied.
        Response file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\\composite-r2r.dll.rsp
        D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\IL\*.dll
        -o:D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\\composite-r2r.dll
        --targetarch:arm64
        --verify-type-and-field-layout
        -O
        -r:D:\h\w\B604099A\p\System.*.dll
        -r:D:\h\w\B604099A\p\Microsoft.*.dll
        -r:D:\h\w\B604099A\p\mscorlib.dll
        -r:D:\h\w\B604099A\p\netstandard.dll
        " "dotnet" "D:\h\w\B604099A\p\crossgen2\crossgen2.dll" @"D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\\composite-r2r.dll.rsp"   --composite"
        Emitting R2R PE file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\composite-r2r.dll
        Emitting R2R PE file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.dll
        Emitting R2R PE file: D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\TestLibrary.dll
         "D:\h\w\B604099A\p\corerun.exe" MarshalStructAsLayoutExp.dll 
        
        Verify marshal Explicit layout struct as param as ByVal
        Expected: 100
        Actual: -268435457
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\h\w\B604099A\p
        > D:\h\w\B604099A\w\A7500979\e\Interop\StructMarshalling\PInvoke\MarshalStructAsLayoutExp\MarshalStructAsLayoutExp.cmd
</pre>

**Comment by nattress** [comment]
`Verify_TypeLayout 'ExplicitHFA' failed to verify type layout`

Looks like we're not handling type layout checks of HFAs properly.

**Comment by mangod9** [comment]
Believe this should be fixed by latest field layout changes.

**Comment by trylek** [comment]
Hmm, apparently not, @eduardo-vp's work on removing closed issues.targets items made this fail again in

https://dev.azure.com/dnceng-public/public/_build/results?buildId=25840&view=ms.vss-test-web.build-test-results-tab&runId=520140&resultId=104552&paneView=debug

**Comment by trylek** [comment]
Closing as no recent repro for now as the repro from last September is no longer actionable. We should update issues.targets by removing this and seeing if it reproes again.
