### ISSUE TITLE
[Perf -19%] [Mono] System.Text.Tests.Perf_Encoding.GetByteCount

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#43476]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/f2d51b5e15808d2c358a59f24af4fad4a9953656...30e643e2f2433055d6ed433af38a925ee657d4ad)

### Regressions in System.Text.Tests.Perf_Encoding

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[GetByteCount](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Text.Tests.Perf_Encoding.GetByteCount(size%3a%20512%2c%20encName%3a%20%22utf-8%22).html>) | 132.16 ns | 156.75 ns | 1.19 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Text.Tests.Perf_Encoding_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Text.Tests.Perf_Encoding.html>)

<details>

#### System.Text.Tests.Perf_Encoding.GetByteCount(size: 512, encName: "utf-8")

```log
[-127.596 ;  405.832) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 405.832 ;  925.098) | 
[ 925.098 ; 1444.364) | 
[1444.364 ; 1963.630) | 
[1963.630 ; 2188.876) | 
[2188.876 ; 2708.142) | @@@@@@@@@@@@@@@@
[2708.142 ; 3145.833) | @@
[3145.833 ; 3651.283) | 
[3651.283 ; 4174.273) | @@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by naricc** [comment]
This appears to have been caused by one of the commits in this range: https://github.com/dotnet/runtime/compare/f2d51b5e15808d2c358a59f24af4fad4a9953656...d6887d4aeec045aa4d708463abdfb6e071660dc8

**Comment by danmosemsft** [comment]
Scratch that, it's Mono. @SamMonoRT looks like you're already tracking it? 

Although, I don't see any interesting Mono changes in this range.

@DrewScoggins in these issues, it would be very helpful to indicate what platforms and what VM's the repro is on. For example, is this specific to x64? to ubuntu? to Mono? I have spent some time in https://aka.ms/dotnetperfindex  and I was not able to figure that out.

**Comment by danmosemsft** [comment]
Same question for all the issues you recently opened @DrewScoggins -- are these all specific to Mono+Ubuntu+x64?

![image](https://user-images.githubusercontent.com/6385855/96283451-1613c100-0f91-11eb-8d32-a8102437b26e.png)

**Comment by tarekgh** [comment]
Looks all ar eMono specific on Ubuntu

System.Text.Tests.Perf_Encoding.GetByteCount(size: 512, encName: "utf-8")

  | Name | Architecture | OS | Queue | Git Hash | Branch | Repo | Locale | Configurations
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 20201014.6 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 51f6b8bd3a2a38c432b1cd1f7c465c256f5f699c | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono
Compare | 20201014.6 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 51f6b8bd3a2a38c432b1cd1f7c465c256f5f699c | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono

System.Collections.CtorGivenSizeNonGeneric.SortedList(Size: 512)

  | Name | Architecture | OS | Queue | Git Hash | Branch | Repo | Locale | Configurations
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=true,RunKind=micro_mono
Compare | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=true,RunKind=micro_mono


System.Memory.ReadOnlyMemory<Char>.ToArray(Size: 512)

  | Name | Architecture | OS | Queue | Git Hash | Branch | Repo | Locale | Configurations
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono
Compare | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono

System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Span(address: [16, 32, 48, 64, 80, ...])

  | Name | Architecture | OS | Queue | Git Hash | Branch | Repo | Locale | Configurations
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono
Compare | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono


System.Tests.Perf_Int16.ToString(value: 32767)

  | Name | Architecture | OS | Queue | Git Hash | Branch | Repo | Locale | Configurations
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono
Compare | 20201015.8 | x64 | ubuntu 18.04 | Ubuntu.1804.Amd64.Tiger.Perf | 722b8a660e7e0c59419196be102784244883ff08 | refs/heads/master | dotnet/runtime | en-US | CompilationMode=tiered,LLVM=false,MonoAOT=false,MonoInterpreter=false,RunKind=micro_mono

**Comment by SamMonoRT** [comment]
Need to dig in a little more, could be any BCL or runtime change causing the regressions. Also, to note we just enabled the auto-filling for Mono runs, still getting familiar with commit disection

**Comment by SamMonoRT** [comment]
@DrewScoggins  - to avoid confusion, is it possible to add [Mono] to the issue title as part of the auto-filing logic ?

**Comment by DrewScoggins** [comment]
In every bug that I file I always mark with labels all of the affected platforms, that the lab is able to detect. I thought that marking these issues with the runtime-mono label would make it clear that these were on the mono runtime, I can see that this is not the case. I will make sure that all issues that get moved into the runtime repo going forward that are from Mono have [Mono] in the title of the bug.

**Comment by danmosemsft** [comment]
> In every bug that I file I always mark with labels all of the affected platforms, that the lab is able to detect. I thought that marking these issues with the runtime-mono label would make it clear that these were on the mono runtime

@DrewScoggins thanks - I didn't know this.

**Comment by danmosemsft** [comment]
@SamMonoRT any thoughts about where investigation should be? I'm at a bit of a loss as to which of these changes could have caused it.

**Comment by naricc** [comment]
@danmosemsft 

None of the changes look particularly likely to have caused this regression. The ones that only change coreclr code can be ruled out; the ones that change libraries could could theoretically causes a performance regression in Mono. But looking at them and looking at the benchmarks, it seems really unlikely.

Since this is not affecting many benchmarks, I think its likely just a sort of random alignment issue or something like that. So my plan for right now is to just keep this open and monitor this benchmark over the next month or so.

**Comment by danmosemsft** [comment]
@naricc sounds good - thanks!

**Comment by naricc** [comment]
Having followed the benchmarks, I don't think there is any real regression here.
