### ISSUE TITLE
JIT issue backlog review

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#43470]
The CLR CodeGen team has a very large backlog of open GitHub issues: almost 900 as of 15 October 2020 (see [this query](https://github.com/dotnet/runtime/labels/area-CodeGen-coreclr)). These issues contain a large amount of customer and partner feedback about JIT inadequacies, potential JIT improvements, as well as CodeGen team internal work items to improve generated code quality (CQ), throughput (TP), quality, testing, productivity, and more. We need to review the backlog for potential .NET 6 work items, close any issues that have already been addressed or which we do not plan to address in the future, and ensure that our methodology for working with such a large backlog is effective.

We understand that prioritizing some of these work items for .NET 6 addresses real customer feedback, and fulfills a general goal of continuous improvement of .NET fundamentals, even if, individually, they often do not constitute "big" work items.

## Background

The JIT product has a large number of sub-areas, both in terms of functionality as well as characteristics (e.g. JIT throughput vs. code quality). In order to capture these characteristics for each issue without adding a large number of JIT-specific labels to GitHub, a classification system was devised, and has been periodically used to classify issues. Issue [dotnet/runtime#858](https://github.com/dotnet/runtime/issues/858) describes this classification system.

This classification system forms the starting point for an effort to understand what we can do with this large set of open issues.

## Proposed Work

* Ensure that the right set of classifications are in place to be useful.
  * An optional "impact" tag can be added (with values "small", "medium", "large"), to estimate the value of implementing an improvement.
  * Between the `basic-cq` and `optimization` themes, there are about 200 issues; should they be merged?
  * There is an `intrinsics` theme. Is it specific to hardware intrinsics, or does it also contain JIT intrinsics? Perhaps we should have `jit-intrinsics` and `hardware-intrinsics` to clarify.
  * Are the `hardware-intrinsics` and `vector-codegen` themes properly used? `vector-codegen` should only be `Vector<T>`, `Vector2`, `Vector3`, `Vector4`, etc. (the platform-independent vector code).
  * Is there a better way to classify these into distinguished sub-categories?
* With the chosen set of classifications, ensure that all issues have been appropriately classified
* Close all issues that have been already addressed, ideally with a link to the PR that addressed them
    * In particular, it is believed that some of the issues relating to structs, especially enregistration of register-passed or -returned structs, may have been addressed in 5.0 but are not yet closed.
* Close all issues that are unlikely to ever be addressed, with an explanation
    * As a prerequisite to doing this, establish some criteria for determining which issues we are likely to never address?
* Triage the remaining issues for an initial determination of those that should be addressed in .NET 6
    * Create recommendations for areas to focus on and particular issues to address
* To do this work, we will mark all open issues with a new GitHub label, `jit-untriaged`. When an issue has been considered, this label will be removed. When we have finished the review (either we have reviewed all the items, or we have decided not to spend any more time on the exercise), we will delete the label.

## Benefit

* Prioritize fixes to customer and partner reported JIT issues.
* Find patterns of issues that could lead to understanding of particularly weak areas of the JIT, and lead to design prioritization for improving large areas of weakness.
* Reduce the number of outstanding issues that we carry forward; the sheer number can be a tax.

## For each issue

1. Assign either Milestone 6.0.0 or Future, based on estimate of timeframe when it should be addressed.
2. Determine if the issue still exists (if not too time intensive to quickly determine), close if not.
3. Link related issues.
4. Ensure the `category`/`theme`/`skill-level`/`cost` tags are reasonable.
5. Add an `impact` tag, if possible.

## Overall work

1. Determine patterns of issues: what areas should we focus on? Could/should we create "meta-issues" for some groups? Do certain areas deserve coordinated work (e.g., a large set of hardware intrinsics CQ items)?

## Progress

- [x] Split `intrinsics` to `hardware-intrinsics` and `jit-intrinsics`
- [x] Add new `JitUntriaged` label to all open issues
- [ ] When we are done, delete the `JitUntriaged` label

This is the set of themes we are addressing, in order:
- [x] structs (@CarolEidt )
- [x] register-allocator (@CarolEidt WIP)
- [x] jit-intrinsics (@CarolEidt )
- [x] hardware-intrinsics (@CarolEidt WIP)
- [ ] vector-codegen (@CarolEidt WIP)
- [ ] loop-opt (@BruceForstall WIP)
- [ ] basic-cq
- [x] optimization (@BruceForstall WIP)
- [ ] ir
- [ ] inlining (@AndyAyersMS WIP)
- [ ] devirtualization (@AndyAyersMS WIP)
- [ ] jit-coding-style
- [ ] testing

Number of open [label:area-CodeGen-coreclr](https://github.com/dotnet/runtime/issues?q=is%3Aopen+label%3Aarea-CodeGen-coreclr+is%3Aissue) issues: 896
Number of [label:JitUntriaged](https://github.com/dotnet/runtime/labels/JitUntriaged) issues: 524

category:planning
theme:planning
skill-level:expert
cost:large

**Comment by danmosemsft** [comment]
We (eg reporting, bot training) rely on there being exactly one area label.

**Comment by BruceForstall** [comment]
fyi @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
11/16/2020 Number of label:JitUntriaged issues: 652

**Comment by JulieLeeMSFT** [comment]
11/30/2020 Number of label:JitUntriaged issues: 553

100 more issues triaged.

**Comment by JulieLeeMSFT** [comment]
12/7/2020 Number of label:JitUntriaged issues: 524

29 more issues triaged.

**Comment by BruceForstall** [comment]
We will not do any more organized issue triage for .NET 6, so this item will be closed.

# Overview of progress

As of 1/13/2021, area-CodeGen-coreclr has 922 open issues (we started this exercise with 900). Many issues were, in fact, closed, however it's hard to determine exactly how many due to limitations in GitHub query ability.

There are currently 499 issues with the JitUntriaged label. Thus, we examined and triaged about 400 issues during this exercise, especially those previously tagged "structs", "register-allocator", "intrinsics", "basic-cq", and "optimization", and more recently opened items.

JIT tagging was updated on all area-CodeGen-coreclr issues.

Many triaged items had their JIT tags updated (e.g., changing from the non-specific "optimization" to something more specific like "cse"). Some had their milestone changed to .NET 6.

Our internal JIT tagging processing app was updated to support the JitUntriaged label.

Some of the JIT tag categories were refined, such as splitting "intrinsics" into "jit-intrinsics" and "hardware-intrinsics".

# Summary

There were a lot of JIT issues, and there still are.

Triaging issues takes a lot of time. Simply recreating a repro environment or repro test case, where one was not previously created, and verifying that an issue reproduces or does not reproduce, is time consuming, especially if in one of our "harder to work with" platforms, like Linux arm32.

I would still consider the exercise valuable, in that we made some incremental progress closing and analyzing issues, even if the end result wasn't some magic massive reduction of issue numbers.

**Comment by JulieLeeMSFT** [comment]
This was a tedious but valuable exercise in that we could update tags for ~400 issues and could identify issues to address in .NET 6. Kudos to Bruce and team.
