### ISSUE TITLE
[Perf -19%] [Mono] System.Tests.Perf_Int16.ToString

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#43478]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/f2d51b5e15808d2c358a59f24af4fad4a9953656...30e643e2f2433055d6ed433af38a925ee657d4ad)

### Regressions in System.Tests.Perf_Int16

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[ToString](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Int16.ToString(value%3a%2032767).html>) | 17.12 ns | 20.45 ns | 1.19 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Tests.Perf_Int16_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Tests.Perf_Int16.html>)

<details>

#### System.Tests.Perf_Int16.ToString(value: 32767)

```log
[14.939 ; 22.848) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[22.848 ; 30.757) | 
[30.757 ; 38.666) | 
[38.666 ; 46.575) | 
[46.575 ; 52.853) | 
[52.853 ; 60.762) | @@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by naricc** [comment]
This appears to be caused by one of the commits in this time range: https://github.com/dotnet/runtime/compare/f2d51b5e15808d2c358a59f24af4fad4a9953656...30e643e2f2433055d6ed433af38a925ee657d4ad

**Comment by danmoseley** [comment]
the most interesting changes in that range are not relevant to Mono..

**Comment by naricc** [comment]
Having more experience with these benchmarks now, I don't think this represents a real regression.
