### ISSUE TITLE
Consider marking net5.0 obsoleted APIs obsolete in downlevel targets for OOB packages

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#43484]
Many APIs are being [obsoleted in .NET 5](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/obsoletions-in-net5.md). During the PR review for marking those obsoletions, the [question was raised](https://github.com/dotnet/runtime/pull/39269) for whether or not we should apply the obsoletions to OOB packages with downlevel targets such as netstandard2.0 and netcoreapp2.0.

This was an explicit [non-goal of better obsoletions](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/better-obsoletion.md#non-goals), but it's worth further consideration.

If we determine that we should indeed apply the obsoletions to downlevel targets, then we would need to:

1. Extract the list of downlevel-targeted APIs from the [obsoletions in .NET 5](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/obsoletions-in-net5.md)
1. Decide if we want to apply a downlevel `[Obsolete]` attribute without the `DiagnosticId`/`UrlFormat` properties, apply an `[Obsolete]` attribute without those properties (triggering `CS0618`), or implement compiler support for internally-defined `System.Obsolete` attributes with the new properties.

**Comment by stephentoub** [comment]
> Extract the list of downlevel-targeted APIs from the obsoletions in .NET 5

This is specifically referring to APIs we actively ship from dotnet/runtime in nuget packages that have downlevel assets? I'd expect the list of obsoletions there to be very small. Do you have some examples?

**Comment by jeffhandley** [comment]
As part of #51721, I reviewed the APIs that were conditionally obsoleted only in net5.0+, and the set was limited to `System.Security.Permissions` and `System.Reflection.MetadataLoadContext`. The value of obsoleting these down-level is low and it would introduce possible breaking changes upstack. Those obsoletions will not be applied down-level.

With #51595 though, the obsoletion documentation now makes it clearer and easier to obsolete APIs down-level going forward.
