### ISSUE TITLE
Single EXE with an external appsettings.json

### ISSUE THREAD

**Issue by codemonkey85** [dotnet/runtime#43488]
Hello,

I was just wondering if there is a way or a plan to allow single .EXE deployment of my .NET Core apps, while still allowing for an external config file, i.e. appsettings.json.

I didn't see any options that get me to where I want to be: https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#user-experience

**Comment by jjxtra** [comment]
Seems to be a lot better in .NET 5 rc 2, just mark the appsettings.json or app.config as content and copy if newer and the publish does the right thing.

**Comment by vitek-karas** [comment]
.NET 5 changed the default behavior and it will only bundle managed assemblies into the single executable. Any other file type will be left next to the single executable. This includes any "data" files (non-code), like configuration files and so on.

(It will bundle `.deps.json` and `.runtimeconfig.json` which are technically also configuration files)

In .NET Core 3.1 this can be achieved by adding `ExcludeFromSingleFile=true` metadata to the file item in the project - see the detailed doc here: https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design_3_0.md#build-system-interface
