### ISSUE TITLE
Adopt semantic versioning to manage interdependency within core .NET ecosystem

### ISSUE THREAD

**Issue by gulshan** [dotnet/runtime#43489]
Current .NET ecosystem has some major components-
- CoreCLR
- Roslyn
- CoreFX
- netStandard
- SDK
- ASP.NET
- VIsual Studio
- CoreRT
etc

The current practice has been- lumping all of these components together in a major .NET release. But as the whole .NET ecosystem getting more open and larger, this way of interdepencey is getting more complex to manage. I think it is true both inside core .NET dev teams and other developers using these components. Netstandard promised to fix backward compatible library development. But still there are lots of issues.

So how about adopting semantic versioning in the core .NET componets, to manage dependencies? Each component will have its own development and release plan. And everyone will develop on a solid release version of component they are depending on. Earlier version still gets feasible new features. When Roslyn dependes a new feature in CoreCLR, that dependency should be stated in versions, not in ad-hoc basis. And the new Roslyn features not requiring CLR changes can be shipped to multiple versions.

This movement will not be simple or easy. But can this be worthy of discussion?

**Comment by terrajobst** [comment]
We have stopped with the idea that we can ship the .NET platform as a loose set of components, e.g. on NuGet. We have unified vision for the product itself (which, for example, is reflected by the [new framework names for .NET 5](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md) and we have the plan to make certain parts of the .NET platform [optional components](https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workloads.md).
