### ISSUE TITLE
Make MicroBenchmarks project in dotnet performance repo to consume new local dotnet/runtime API

### ISSUE THREAD

**Issue by lateapexearlyspeed** [dotnet/runtime#43506]
Hi, I found I cannot consume new API generated from local dotnet/runtime repo into MicroBenchmarks project of dotnet/performance repo. I tried to learn from this [doc](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md#reference)  , difference between doc and my local environment is referenced assembly path.
my local ref path: artifacts\bin\ref\microsoft.netcore.app\Release\System.Console.dll
![image](https://user-images.githubusercontent.com/72254037/96246506-4da75b00-0fdb-11eb-9d8b-30399d5a2b39.png)

I also checked IL of that local referenced assmebly "System.Console", it contains new API I tried to add previously: WriteHelloWorld.

My MicroBenchmarks csproj:
![image](https://user-images.githubusercontent.com/72254037/96246607-7596be80-0fdb-11eb-9afc-bbbd898db64b.png)

Solution explorer has some warning mark about this referenced assembly, but vs can build if not consume new API:
![image](https://user-images.githubusercontent.com/72254037/96246645-85160780-0fdb-11eb-9c3c-2fb89b1ea619.png)

Can anyone help figuring out any step I may be wrong for referencing new local dotnet runtime assembly which added new API, thanks !
![image](https://user-images.githubusercontent.com/72254037/96248118-a8da4d00-0fdd-11eb-97f4-eeed3ecec0df.png)

**Comment by am11** [comment]
Hello, could you try making this change in microbenchmark csproj:

```diff
<ItemGroup>
-  <Reference Include="System.Console">
-    <HintPath>..\..\..\..\..\runtime\artifacts\bin\ref\microsoft.netcoreapp\Release\System.Console.dll</HintPath
-    <Private>true</Private>
-  </Reference>
+  <Reference Include="..\..\..\..\..\runtime\artifacts\bin\ref\microsoft.netcoreapp\Release\System.Console.dll">
</ItemGroup>
```
---
FWIW, I keep the repo clone with master branch separate from the one with local branch for performance runs; this is to get reliable results in complex changes. I have not tried perf benchmark with Visual Studio but with command-line, this method works which compares performance of local changes vs. master branch (on macOS):

```sh
# example to run perf. tests against runtime master branch (`runtime_base`) vs. PR branch (`runtime_pr`)

# meta

# 1. my local setup
$ git clone https://github.com/dotnet/runtime ~/projects/runtime_base
$ git clone ~/projects/runtime_base ~/projects/runtime_pr
$ cd runtime_pr
$ git remote set-url origin https://github.com/<your username>/runtime
# make code changes in runtime_pr instance using VSCode or editor of choice.

# build steps

# 2. master branch (usually requires running this step only once)
$ ~/projects/runtime_base/build.sh Clr+Libs -c Release && \
  ~/projects/runtime_base/src/tests/build.sh -generatelayoutonly -c Release

# 3. PR branch (requires running after each change in PR branch)
$ ~/projects/runtime_pr/build.sh Clr+Libs -c Release && \
  ~/projects/runtime_pr/src/tests/build.sh -generatelayoutonly -c Release

# performance run

# 4. change directory to performance repo's micro directory and run tests (for Windows change OSX to Windows.
#   the following example has math benchmarks filter applied in this example, YMMV)
$ cd ~/projects/performance/src/benchmarks/micro
$ ~/projects/runtime_pr/.dotnet/dotnet run -c Release -f netcoreapp5.0                      \
  --filter *MathBenchmarks* --statisticalTest 3ms                                           \
  --coreRun                                                                                 \
    ~/projects/runtime_base/artifacts/tests/coreclr/OSX.x64.Release/Tests/Core_Root/corerun \
    ~/projects/runtime_pr/artifacts/tests/coreclr/OSX.x64.Release/Tests/Core_Root/corerun
   # ^ here order matters. we can also have more than two variations of build.
```

A note (typically encountered in custom/freshly initialized containers): although we can use the SDK that was restored when building dotnet/runtime repo  (from script above: `~/projects/runtime_pr/.dotnet/dotnet`) to build and execute projects in performance repo, it still requires `dotnet`'s base directory in `PATH`. Alternatively, we can export `DOTNET_ROOT` environment variable with value set to basedir of `dotnet`.

Hope it helps.

**Comment by lateapexearlyspeed** [comment]
@am11 Thanks for detailed sharing!
I tried to change Reference tag in microbenchmark csproj to what was suggested above, when run benchmark test in command line, compiler reported error about 

> error CS0433: The type 'Console' exists in both 'System.Console, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\dotnetperformance\performance\src\benchmarks\micro\MicroBenchmarks.csproj]

I also used script you provided, it can benchmark performance for local change, but seems it is for existing API, for example changing internal implementation of existing API. (Please correct me if I am wrong). I still cannot benchmark New API which not exist in dotnet before.

My case is to try to create a New method overload in dotnet and benchmark it, at least I can compare result with that existing method overload to see if new one can get better performance, because they have same functionality in specific scenario but based on different arguments, new API may have some opportunity to run faster.

Besides of Reference tag change in microbenchmark.csproj, my benchmark command is:

> C:\dotnetperformance\performance\src\benchmarks\micro>C:\runtime\.dotnet\dotnet run -c Release -f netcoreapp5.0 --filter System.ConsoleTests* --coreRun C:\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\5.0.0\CoreRun.exe
libraries\System.Console\Perf.Console.cs(48,21): error CS0117: 'Console' does not contain a definition for 'WriteHelloWorld' [C:\dotnetperformance\performance\src\benchmarks\micro\MicroBenchmarks.csproj]

After build.cmd clr+libs -rc Release -c Release, the ref System.Console.dll has been verified to contain new 'WriteHelloWorld'.
Is any path I referenced wrong?

**Comment by am11** [comment]
>> error CS0433: The type 'Console' exists in both 'System.Console, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\dotnetperformance\performance\src\benchmarks\micro\MicroBenchmarks.csproj]

Does it give the same error with non-ref assembly `<Reference Include="C:\runtime\artifacts\bin\runtime\net6.0-Windows_NT-Release-x64\System.Console.dll" />` ?

**Comment by lateapexearlyspeed** [comment]
Thanks @am11 ! It works now by add Reference as:
`<Reference Include="..\..\..\..\..\runtime\artifacts\bin\ref\microsoft.netcore.app\Release\System.Console.dll">
   <Private>false</Private>
</Reference>`
Referencing non-ref assembly can also work. 

So the key to achieve consuming new API is to add dll path in "Include" property, rather than in "HintPath" tag which I think was wrongly documented [here](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md#reference).
Sorry I gave wrong error info above, actually it was because the path is wrong: "microsoft.netcoreapp" missed one 'dot' in my windows environment.

> error CS0433: The type 'Console' exists in both 'System.Console, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\dotnetperformance\performance\src\benchmarks\micro\MicroBenchmarks.csproj]


> ```diff
> <ItemGroup>
> -  <Reference Include="System.Console">
> -    <HintPath>..\..\..\..\..\runtime\artifacts\bin\ref\microsoft.netcoreapp\Release\System.Console.dll</HintPath
> -    <Private>true</Private>
> -  </Reference>
> +  <Reference Include="..\..\..\..\..\runtime\artifacts\bin\ref\microsoft.netcoreapp\Release\System.Console.dll">
> </ItemGroup>
> ```

What is difference about dll path in "Include" property and in "HintPath" tag ?

**Comment by am11** [comment]
Interesting that for some reason, I didn't had to specify `Private` on macOS with non-ref path. btw, for shorthand, we can also specify `Private` as an attribute:
`<Reference Include="absolute_or_relative_path\to\dll" Private="False" />`

> What is difference about dll path in "Include" property and in "HintPath" tag ?

It depends on how these items are computed in the internal targets. From MSBuild script perspective, `Include` attribute on item under `<ItemGroup>` simply appends to the group item in order. Then it is up to project system or SDK how to affect the precedence.

Current behavior, with .NET 5 SDK, seems to be:
* `Include` with path value is explicit; if there is a collision, SDK gives this user-specified path value precedence over shared framework assembly.
* `Include` with name value accompanied by `HintPath` appends to its search path. The order of hint (search) path is maintained internally and shared framework path takes precedence in this case.

When in doubt, we can capture the fully log dump with `dotnet build /v:diag > dump.log` and read the internal resolutions in textual form. Alternatively, we can pass `/v:diag /logger:BinaryLogger` to capture binary logs and browse the logs in this GUI tool for Windows: https://msbuildlog.com/.

**Comment by lateapexearlyspeed** [comment]
Thanks for those great information.

> Interesting that for some reason, I didn't had to specify `Private` on macOS with non-ref path

Yes, it is also in Windows. Seems only ref path has to specify Private=false.

BTW, seems we need to reference ref assembly: runtime\artifacts\bin\ref\microsoft.netcore.app\Release\System.Runtime.dll with private=false, if I add api in system.private.corelib.dll and call it in benchmark project. At least it works in my current code change and I cannot find way to reference non-ref private.corelib in microbenchmark project.

**Comment by joperezr** [comment]
From the discussion above this issue seems to be resolved so I'll go ahead and close the issue for now. Feel free to reopen in case I misinterpreted something.
