### ISSUE TITLE
Generic struct including itself breaks the runtime - should be a compiler error?

### ISSUE THREAD

**Issue by mgravell** [dotnet/runtime#43515]
Minimal repro:

```c#
struct Foo { X<Foo> a; }
struct X<Y> { }
```

Even though `X<Y>` is known constant size, the runtime can't load `Foo`:

> Unhandled Exception: System.TypeLoadException: Could not load type 'Foo' from assembly (blah)

---

Not 100% sure whether I should log this in csharplang or coreclr, but it should probably *either*

- work in the runtime (move issue to coreclr)
- tell the user at compile-time (error? similar to CS0523?)

---

real world scenario was actually something more like:

```c#
readonly struct Frame {
    Frame[] subItems;
    // ... some other stuff
}
```

that I tried to migrate to:

```c#
readonly struct Frame {
    Memory<Frame> subItems;
    // ... some other stuff
}
```

(so I could use oversized arrays leased from the array pool, and recycle them after processing payloads)

**Comment by EgorBo** [comment]
Explanation: https://github.com/dotnet/runtime/issues/6924#issuecomment-547078135

**Comment by teo-tsirpanis** [comment]
Duplicate of #6924.
