### ISSUE TITLE
Add concatenation method to int type

### ISSUE THREAD

**Issue by akmadian** [dotnet/runtime#43528]
I'm not sure if this is the right place for this, but I have wanted to concatenate two integers into a new int many times, and while writing an extension method really isn't that much of a pain, but I think that this feature may have a place in .NET.

Instead of this:
```csharp
int x = 1;
int y = 2;

Int.Parse(x.ToString() + y.ToString());
```

I usually use something like this:
```csharp
int x = 1;
int y = 2;

x.Concat(y); // = 12
```

This method could be written so that a collection of ints may be passed as a parameter. I imagine that this feature addition would be welcome for many people (including myself!)

**Comment by lechu445** [comment]
@akmadian you can just write an extension method for that use-case
```c#
public static int Concat(this int first, int second) => (first * 10) + second;
```
