### ISSUE TITLE
Very disappoint on the .net 5 TFM names

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#43530]
this is the doc. https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md
with .net 5 you guys  said it's the journey to one .net,  after I read the article I find that it's a big big lie.
`.net5-ios` ,`.net5-ios14` , so `.net` is not the platform , the OS is ,  and so why not use swift and object-c , they never need a OS to support there language or the language update to support OS Version.
let's see what we know here.
1. to support new OS , we just need to write binding to the native library, which do not have any thing related with .net it self.(.net 1 is support  p/invoke to native)
2.  OS feature is just  things like `Console.ReadLine()` or `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)` 

so you tel me why IOS14 is different than IOS 13?  and what about the older OS?  both IOS and Android,    so people come to .net 5 for what ?  for drop users  that do not want to upgrade their OS because they have a old device ?

android have success is because they only add jvm to andorid no  java BCL stuff,  now you can still target the latest andorid 11 and support Android 4  toooooo !  and IOS even better, they use native language . 
all there work is doing for onething,  you can just write app for latest OS and will work on older version OS too.

Xamarin/Unity team respect that , but sadly  net team don't . 😞

Today using .Net have risk （base on history）
1.  start using  .net now and  want to upgrade to newer .Net  but  your Server OS, or Client OS version is a big problem (after all, .net is the first language that drop support win xp , when people try upgread .net 4 to .net 4.5)
2.  runtime/framework/OS  as a dependency  the customer machine may not install (for that , look at js,  they never let  js engine or electron dependency be  cumbersome)
3. always have some new tech, but not for long ,and not be popular in developer community（that means you can get less help than other languge）, from webform->mvc->core mvc -> razor page -> blazor;   or   winform->wpf->uwp   ,  that mean you need lean more but do less.

I write this because I love C# ,  I really hope .net not go to the wrong way.

and by the way , if oneday  thire is a native C# (static library support and drop vm)  that will be great.

**Comment by terrajobst** [comment]
> and I still do not know will `.net5-ios14` can run on IOS13,IOS12 or not.

Yes, you will be able to. This scenario [is explicitly called out here](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#lighting-up-on-later-os-versions).

> but I still hope you can get the point that I'm arguing above.

I'm not sure I do. It seems to me, your idea of `feature` shares the same problem as the app model that I explained above. The rules for how NuGet would decided which binaries to give you aren't well-defined.
