### ISSUE TITLE
What purpose does `sendBufferSize` parameter serve in `ClientWebSocketOptions.SetBuffer`?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/runtime#43559]
Hi Team,

I'm a bit puzzled by `sendBufferSize` parameter in `ClientWebSocketOptions.SetBuffer`. It does not seem to do what documentation indicates: 

https://github.com/dotnet/runtime/blob/839b1343fbad61526fedcaa722f1ae48b298c543/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocketOptions.cs#L155

[Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions.setbuffer?view=netcore-3.1#System_Net_WebSockets_ClientWebSocketOptions_SetBuffer_System_Int32_System_Int32_) says *The size, in bytes, of the client send buffer.* 

Can anybody explain this to me?

Thank you

**Comment by stephentoub** [comment]
It doesn't currently serve a purpose.  It was used in the original implementation behind this API years ago when it was first introduced in .NET Framework, but it doesn't have a meaningful use with the current implementation rewritten for .NET Core.

**Comment by MartyIX** [comment]
Could this be documented? It's far from obvious.

**Comment by stephentoub** [comment]
It could be,  but the current behavior is an implementation detail.  It could instead, for example,  allocate a buffer of the requested size,  copy the sent data into it,  and then flush the buffer,  but that doesn't perform as well.

**Comment by wfurt** [comment]
it seems like question was answered.
