### ISSUE TITLE
System.Collections.Generic.Dictionary<object, object>.Enumerator MoveNext() keeps returning true

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/runtime#43553]
System.Collections.Generic.Dictionary<object, object>.Enumerator MoveNext() keeps returning true, if it comes from an auto implemented property in the same class.

Below is the code to reproduce the bug. It will keep outputing "this.Enumerator 1 iteration".

----------------------------------------------------------------------------------------
```c#
namespace DictionaryEnumeratorDemo
{
    class Program
    {
        public void Execute()
        {
            System.Collections.Generic.Dictionary<object, object> a;
            a = new System.Collections.Generic.Dictionary<object, object>();

            a.Add("A", "H");


            this.Enumerator = a.GetEnumerator();

            while (this.Enumerator.MoveNext())
            {
                System.Console.WriteLine("this.Enumerator 1 iteration");
            }
        }

        private System.Collections.Generic.Dictionary<object, object>.Enumerator Enumerator { get; set; }

        static void Main(string[] args)
        {
            Program program;
            program = new Program();
            program.Execute();
        }
    }
}
```

**Comment by chrisaut** [comment]
I'm pretty sure that's because the Dictionary Enumerator is a struct, so in every iteration that calls into the Property of your class you get a (value-) copy of the enumerator that has it's internal state to point at the start.

Unexpected perhaps, but I think this is by design for perf reasons.

**Comment by aaabbbcccddd00001111** [comment]
Thanks for the answer.
