### ISSUE TITLE
Each parameter in constructor 'Void .ctor(System.Guid, System.String, System.String, System.String, System.String)' on type 'xxxxxxx' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.

### ISSUE THREAD

**Issue by logcorner** [dotnet/runtime#43563]
Hi, 
I'm facing an issue when using System.Text.Json.   Fields are not correctly Serialized and Deserialized.
and sometimes , I have the er  error :
Each parameter in constructor 'Void .ctor(System.Guid, System.String, System.String, System.String, System.String)' on type 'xxxxxxx' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.

Here is the code :

```
 class Program
    {
        static void Main(string[] args)
        {
            var @event = (Event)new SpeechCreatedEvent(Guid.NewGuid(), "title", "event.com", "descriptuion", "type");
            string serializedEvent = JsonSerializer.Serialize(@event);

            var type = @event.GetType().AssemblyQualifiedName;
            var result = (Event)JsonSerializer.Deserialize(serializedEvent, Type.GetType(type));
            Console.WriteLine("Hello World!", result);
        }
    }

```

```
namespace ConsoleApp1.Domain
{
    public class SpeechCreatedEvent : Event
    {
        public string Title { get; }
        public string Url { get; }
        public string Description { get; }
        public string Type { get; }

        private SpeechCreatedEvent()
        {

        }
        public SpeechCreatedEvent(Guid id, string title, string url,
            string description, string type)
        {
            AggregateId = id;
            Title = title;
            Url = url;
            Description = description;
            Type = type;
        }
    }

    public abstract class Event : IDomainEvent
    {
        public Guid AggregateId { get; protected set; }

        public Guid EventId => Guid.NewGuid();
        public long AggregateVersion { get; private set; }
        public DateTime OcurrendOn => DateTime.UtcNow;

        public void BuildVersion(long aggregateVersion)
        {
            AggregateVersion = aggregateVersion;
        }
    }

    public interface IDomainEvent
    {
        Guid EventId { get; }
        long AggregateVersion { get; }

        void BuildVersion(long aggregateVersion);
    }
}
```

the serialization / deserialization works fine using newtonsoft as follows

```
JsonSerializerSettings settings = new JsonSerializerSettings
             { ContractResolver = new PrivateSetterContractResolver() };
             return (Event)JsonConvert.DeserializeObject(serializedEvent, Type.GetType(eventType), settings);
```
```
 private class PrivateSetterContractResolver : DefaultContractResolver
        {
            protected override JsonProperty CreateProperty(
                MemberInfo member,
                MemberSerialization memberSerialization)
            {
                var prop = base.CreateProperty(member, memberSerialization);
                if (!prop.Writable)
                {
                    var property = member as PropertyInfo;
                    if (property != null)
                    {
                        var hasPrivateSetter = property.GetSetMethod(true) != null;
                        prop.Writable = hasPrivateSetter;
                    }
                }
                return prop;
            }
        }
```
https://github.com/dotnetcore/Home/issues/42

**Comment by huoyaoyuan** [comment]
`System.Text.Json` doesn't support things like contract resolver.
Your class is not simple. In this case you should use `[JsonIgnore]` and `[JsonConstructor]` properly.

**Comment by logcorner** [comment]
@huoyaoyuan   this classes are on domain layer and I do not want to use json properties on.

**NB** : it works fine with newtonsoft.json and I would like to move to System.Text.Json.
If System.Text.Json does not support this, so I have to rollback and continue unsing newtonsoft.json
Regards

**Comment by huoyaoyuan** [comment]
> it works fine with **newtonsoft.json** and I would like to move to **System.Text.Json**

`System.Text.Json` isn't a drop-in replacement of `Newtonsoft.Json`, although it's designed with the latter in mind.
It's expected that you cannot migrate certain workloads.

**Comment by layomia** [comment]
I believe the exception message is pretty clear on what needs to be done here. To make deserialization work as expected, you need to rename the `id` parameter of the parameterized `SpeechCreatedEvent` ctor to `aggregateId` (or some other match case-insensitive match) so that it can bind with the `AggregateId` property. The reason for this restriction is to ensure that data is always roundtrippable, i.e. we are deserializing only data that could have been the output of serializing a given object.

```cs
public SpeechCreatedEvent(Guid aggregateId, string title, string url,
            string description, string type)
{
    AggregateId = aggregateId;
    Title = title;
    Url = url;
    Description = description;
    Type = type;
}
```

A contract-resolver-like feature isn't implemented in System.Text.Json. I believe this will be considered as part of https://github.com/dotnet/runtime/issues/34456. Since the parameterless ctor on `SpeechCreatedEvent` is non-`public` (meaning the parameterized ctor is the only ctor that `JsonSerializer` could choose for deserialization), then a contract resolver isn't necessary in this scenario. I believe contract resolver is being discussed because "decorating" the deserialization ctor with `[JsonConstructor]` is not desired (but as previously mentioned, is not even necessary).
