### ISSUE TITLE
Nullability annotations in System.Linq.Expressions

### ISSUE THREAD

**Issue by olmobrutall** [dotnet/runtime#43566]
I'm porting the LINQ provider of Signum Framework to .Net 5, In general I'm quite happy with the not nullable annotations, but I found two rough corners: 

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/MethodCallExpression.cs#L62
```C#
        public MethodCallExpression Update(Expression @object, IEnumerable<Expression>? arguments)
        public MethodCallExpression Update(Expression? @object, IEnumerable<Expression>? arguments) //Inconsistent: The member is optional, but the Update method is not. 
```

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/NewExpression.cs#L43

```C#
   public ConstructorInfo? Constructor { get; }
   public ConstructorInfo Constructor { get; } //I think the constructor is mandatory, otherwise the Type property will throw exception.
```

**Comment by cston** [comment]
@olmobrutall, thanks for reporting these cases.

It looks like <code>MethodCallExpression.Update(Expression @object, IEnumerable<Expression>? arguments)</code> should allow `null` for <code>@object</code>, as you indicated.

For `NewExpression.Constructor { get; }`, the `Constructor` may be `null` if the type is a value type and the constructor is the default parameter-less constructor (see [sharplab.io](C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AGQEsoBHMgUQA8AHMAUwGdOqB7KTgG48eDCUwB2PAG88ReeIBsJACxEAsgEMaACgCUchbNwLTRAHLsA7szZce)).

**Comment by olmobrutall** [comment]
Then this property will throw an exception: 

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/NewExpression.cs#L32

**Comment by cston** [comment]
`NewExpression.Type { get; }` is overridden for that case: see [NewExpression.cs](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/NewExpression.cs#L101).

**Comment by olmobrutall** [comment]
Oh! found just a few lines below: 

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/NewExpression.cs#L101

Thanks a lot for the explanation :)

BTW: This sharplab.io looks quite cool, I will use it more

**Comment by olmobrutall** [comment]
I keep it open for the  `MethodCallExpression.Update(Expression @object, IEnumerable? arguments)` case

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/runtime/pull/44844.
