### ISSUE TITLE
Vector64<[s]byte> Ssse3.Shuffle(Vector64<[s]byte>, Vector64<[s]byte>) appear to be missing

### ISSUE THREAD

**Issue by twest820** [dotnet/runtime#43585]
### Description
System.Runtime.Instrinsics.X86.Ssse3 contains methods for

__m128i _mm_shuffle_epi8 (__m128i a, __m128i b) PSHUFB xmm, xmm/m128

The Intel Intrinsics Guide also defines pshfub at 64 bit width

__m64 _mm_shuffle_pi8 (__m64 a, __m64 b) PSHUFB xmm, xmm/m64

but corresponding methods don't exist on System.Runtime.Instrinsics.X86.Ssse3.

### Configuration
.NET Core 3.1 project in VS 2019 16.7.6. See also [https://docs.microsoft.com/en-us/dotnet/api/?term=ssse3.shuffle](https://docs.microsoft.com/en-us/dotnet/api/?term=ssse3.shuffle).

### Regression?
No.

### Other information
Low priority for me. I was looking at this for big endian decoding so can call BinaryPrimitives.ReverseEndianness() from overloaded StreamReader methods instead. The Vector128 version also serves as a workaround with a dummy upper 64 bits.

**Comment by tannergooding** [comment]
The intrinsics that work with `__m64` are extensions to the legacy MMX instruction set from 1997 that is essentially deprecated and no longer recommended for use. The backing `__m64` register is also actually part of the x87 FPU stack and so additional considerations must be made when codifying for these which the JIT does not currently do.

There are currently no plans to extend the JIT to support this legacy instruction set.

**Comment by twest820** [comment]
Thanks, Tanner. I'd be fine with closing this won't fix.

**Comment by tannergooding** [comment]
CC. @CarolEidt, @echesakovMSFT
