### ISSUE TITLE
[Cross-targeted debugging] Coredumps from self-contained Linux ARM32 apps can't be debugged on Windows

### ISSUE THREAD

**Issue by clguiman** [dotnet/runtime#43596]
`ClrDataAccess::GetDacGlobals` returns `CORDBG_E_MISSING_DEBUGGER_EXPORTS` when trying to initialized the DAC for a Linux ARM32 coredump.

**Comment by mikem8361** [comment]
The core dump generated (coredump.23887v2) doesn't seem to contain the header/first page of the libcoreclr.so module which is causing SOS to fail loading the DAC.

**Comment by sdmaclea** [comment]
This probably also affects debugging on the `linux-arm` target itself.

**Comment by mikem8361** [comment]
Further investigation indicates that I was wrong about the createdump libcoreclr.so page and it may be a bug in SOS itself.  It doesn't explain the above DAC GetDacGlobals yet. The SOS side needs some more investigation before I blame it on createdump.

**Comment by mikem8361** [comment]
I jumped the gun blaming this issue on createdump. This specific issue in SOS/dotnet-dump (and VS's datatarget I assume)  handling of signed extended memory addresses.  Fixing that in SOS fixed all the problems with the repro coredump.

@clguiman I think we should close this now.

**Comment by clguiman** [comment]
Updating the logic for signed extended addresses in the VS datatarget fixed the DAC loading, but the thread that throws the exception (first one) is not recognized as a managed thread. Does SOS properly identify the exception?

**Comment by clguiman** [comment]
#44553 seems to fix some of the stack walking issue.

**Comment by sdmaclea** [comment]
> the thread that throws the exception (first one) is not recognized as a managed thread

Per @clguiman This thread was marked dead.  I saw SOS had specail casing at least in one place for handling dead threads.

**Comment by sdmaclea** [comment]
I think we should close this issue.  All the arm specific issues should be resolved.

The remaining issue is the inconsistent handling of `dead` and `report as dead` threads.  I think that should be opened as a separate issue.

**Comment by sdmaclea** [comment]
#44599
