### ISSUE TITLE
First chain build failed 5% on Linux and Mac, second chain build succeed. 

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#43608]
### Description
We have a flaky test, which failed on Linux and Mac at 5% of the time, but never failed on Windows.

We could repro by doing the following:
1.Set up a simulated CA and TSA, and OCSP responder. The TSA has three certificates in a chain generated: root -> intermediate -> leaf. All the OCSP responders are set up (the OCSP URL in generated intermediate and leaf certificates are listened). No CRL is configured.
Do the following(step 2-6) for 100 times:
2.Simulated CA issues a certificate for package signing
3.Author sign the package and timestamp the package.
4.Get all certificates(root -> intermediate -> leaf) from timestamp.SignedCms.Certificates from the signed package.
(**first chain build**:)
5.Build certificate chain on the leaf certificate on timestamp.
(**second chain build**:)
6.Build certificate chain on the leaf certificate on timestamp.

### Expected: 
100 times of both first chain build and second chain build should be successful on Windows/Linux/MacOS.
### Actual:  
100 times of both first chain build fail at about **5% of the time on Linux/MacOS**, but second chain build 100% successful.

The chain status of the 5% failed tests are:
```
status : RevocationStatusUnknown
info: CRL has expired
status : OfflineRevocation
info: unable to get certificate CRL
```
All the 100 times tests are using the same three certificates in a chain, which are generated in step1,  so the 100 times of tests are building the same certificate chain. The simulated OCSP is sending out good status response, no matter if the chain build failed or succeeded. 
I also tried to wait for 10s before the first chain build for the 100 times of tests, but the they still keep failing at about 5% of the time on the first chain build.(second chain build always succeed at 100%)

**Comment by bartonjs** [comment]
It sounds like perhaps you have clock skew or boundary conditions going on.  Generally speaking, on Windows if the current time is equal (to the second) to a notAfter time (or nextUpdate time) it's considered valid, but OpenSSL considers it already expired (that the expiry happened when the clock changed to this second).  I don't remember which way Apple's engine counts things, but it seems like they're maybe matching OpenSSL.

Assuming you're setting notAfter values, perhaps make them one second bigger.

**Comment by heng-liu** [comment]
Hi @bartonjs ，thanks for your reply :) 
The `notAfter ` time is only set for author signing certificate, not the timestamping certificate.
And we're building the certificate chain not for author signing certificate, but for the timestamp certificate.
(Timestamp is a SignedCms added as an unsignedAttribute on author signature)
The `notAfter` time for timestamping certificate is set to two hours later https://github.com/NuGet/NuGet.Client/blob/dev/test/TestUtilities/Test.Utility/Signing/IssueCertificateOptions.cs#L39
All of our tests will finish during the two hours, so the timestamping certificate of all the related tests should be not considered expired.

**Comment by bartonjs** [comment]
If you're actually only seeing problems on the first run, it's possibly just the JIT cost causes your OCSP nextUpdate values to be expired, since they're only valid for one second.  And/or that's just the most likely time that the clock rolls over to the next second before running.

https://github.com/NuGet/NuGet.Client/blob/7924156332f078dff65274b03334bc82252b877a/test/TestUtilities/Test.Utility/Signing/OcspResponder.cs#L92

I expect that you'll drop to "only fails during an NTP forward-jump" if you change that 1 to a 2.

**Comment by heng-liu** [comment]
Thanks a lot @bartonjs ! 
I tried with the change you suggested above, and ran the test for 100 times. All of them passed!
So it's not an issue in dotnet runtime.. sorry for raising the misleading issue..

**Comment by heng-liu** [comment]
Just out of curiosity, why the second chain build will always pass?

**Comment by bartonjs** [comment]
Probably just that the second attempt runs faster: all the libraries are loaded, all the P/Invokes are bound, the first JIT pass (if applicable) has completed, there's a warmed up network connection from X509 to your OCSP endpoint, etc,.  Basically, all of the reasons that performance profiling has to ignore the first couple of runs :smile:.
