### ISSUE TITLE
User Story: .NET Core developers can verify more APIs for their correct usage to speed up their development 

### ISSUE THREAD

**Issue by cathysull** [dotnet/runtime#43617]
In .NET 5, we shipped approximately 250 analyzers with the .NET SDK. Many of them already existed but were shipped out-of-band as NuGet packages. Now, .NET comes with an in-depth code analysis and code fixer experiences. This means developers don't have to purely rely on their choices based on reading code completion; .NET can help them pro-actively identify when their code has issues, right from the start. However, many of the code analyzers created don’t come with code fixers yet. We will look at telemetry and customer feedback to prioritize (around a TBD set of principles) which code analyzers would most benefit from code fixers along with which are most popular and consider adding fixers for those. Also, there is a sizable backlog of code analyzers that didn't get included in .NET 5, which will need to prioritized and considered. Furthermore, our goal for .NET 6 is that new features in .NET 6 should come with analyzers.

# Work Items

The [getting started guide](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/NetCore_GettingStarted.md) should be referenced for the Definition of Done to be used for each issue.

External contributors: If you'd like to work on one of the issues marked as "up for grabs", please add a comment directly on that issue asking to get it assigned to you, and tag @carlossanlop or @buyaa-n.

| Status | Issue | PR | Title |
|--------|-------|----|-------|
| :x: Closed | #43971 | N/A | [Platform Compatibility Analyzer] Nested APIs shouldn't be allowed to expand the platform set |
| :x: Closed | #33781 | N/A | Replace local allocations with stack allocated spans |
| :heavy_check_mark: @buyaa-n | #45851 | [#4838](https://github.com/dotnet/roslyn-analyzers/pulls/4838) | Referring to unknown platform names should result in warnings |
| :heavy_check_mark: @mahdiva | #33765 | [#5242](https://github.com/dotnet/roslyn-analyzers/pulls/5242) | Pass number of bytes to `Buffer.BlockCopy` |
| :heavy_check_mark: @NewellClark | #33777 | [#4764](https://github.com/dotnet/roslyn-analyzers/pulls/4764) | Use span-based `string.Concat` |
| :heavy_check_mark: @NewellClark | #33784 | [#4806](https://github.com/dotnet/roslyn-analyzers/pulls/4806) | Prefer `string.AsSpan()` over `string.Substring()` when parsing |
| :heavy_check_mark: @NewellClark | #33789 | [#4726](https://github.com/dotnet/roslyn-analyzers/pulls/4726) | Override `Stream.ReadAsync/WriteAsync` |
| :heavy_check_mark: @ryzngard | #33806 | [#4841](https://github.com/dotnet/roslyn-analyzers/pulls/4841) | Do not call `Task.WhenAll` with a single argument |
| :heavy_check_mark: @ryzngard | #33807 | [#4841](https://github.com/dotnet/roslyn-analyzers/pulls/4841) | Do not call `Task.WaitAll` with a single argument |
| :heavy_check_mark: @NewellClark | #35343 | [#4687](https://github.com/dotnet/roslyn-analyzers/pulls/4687) | Replace `Dictionary<,>.Keys.Contains` with `ContainsKey` |
| :heavy_check_mark: @stephentoub | #42948 | [#4909](https://github.com/dotnet/roslyn-analyzers/pulls/4909) | `Environment.ProcessPath` |
| :heavy_check_mark: @stephentoub | #43257 | [#4909](https://github.com/dotnet/roslyn-analyzers/pulls/4909) | `Environment.CurrentManagedThreadId` |
| :heavy_check_mark: @jeffhandley | #43328 | [#5347](https://github.com/dotnet/roslyn-analyzers/pulls/5347) | Warn on use of module initializer |
| :heavy_check_mark: @NewellClark | #45552 | [#5116](https://github.com/dotnet/roslyn-analyzers/pulls/5116) | Use `String.Equals` instead of `String.Compare` |
| :heavy_check_mark: @jkoritzinsky | #46830 | [#5043](https://github.com/dotnet/roslyn-analyzers/pulls/5043) | Expose interop manipulation of `SafeHandle` |
| :heavy_check_mark: @MeikTranel | #47180 | [#4908](https://github.com/dotnet/roslyn-analyzers/pulls/4908) | Use `String.Contains(char)` instead of `String.Contains(String)` |
| :heavy_check_mark: @maryamariyan | #36064 | [#5244](https://github.com/dotnet/roslyn-analyzers/pulls/5244) | Logging Analyzers |
| @mahdiva | #45661 | [#5367](https://github.com/dotnet/roslyn-analyzers/pulls/5367) | Call async methods when in an async method |

## Work Items Not Completed in .NET 6.0

| Status | Issue | PR | Title |
|--------|-------|----|-------|
| Up for grabs | #27997 | | Hide `Thread.VolatileRead` and `Thread.VolatileWrite` analyzer |
| @Mrnikbobjeff | #33769 | [#4126](https://github.com/dotnet/roslyn-analyzers/pulls/4126) | Use `AsParallel()` correctly |
| @fowl2 | #33770 | [#4328](https://github.com/dotnet/roslyn-analyzers/pulls/4328) | Do not use `OfType<T>()` with impossible types |
| @steveberdy | #33794 | [#5383](https://github.com/dotnet/roslyn-analyzers/pulls/5383) | Extract array of const to static readonly field |
| @psxvoid | #33796 | | Constructor parameters should match property names |
| @chucker | #33797 | [#4836](https://github.com/dotnet/roslyn-analyzers/pulls/4836) | Don't guard `Dictionary<K, V>.Remove(key)` by `ContainsKey(key)` |
| @CollinAlpert | #33798 | [#4851](https://github.com/dotnet/roslyn-analyzers/pulls/4851) | Prefer `Dictionary<K, V>.TryGetValue()` over guarded indexer access |
| @CollinAlpert | #33799 | | Prefer `Dictionary<K, V>.TryAddValue(key)` over guarded `Add(key)` |
| @Mrnikbobjeff | #35695 | [#4130](https://github.com/dotnet/roslyn-analyzers/pulls/4130) | Prefer `ExactSpelling=true` on `[DllImport]` for known APIs |
| @wzchua | #40579 | [#4797](https://github.com/dotnet/roslyn-analyzers/pulls/4797) | Prefer static `HashData` methods over `ComputeHash` |

**Comment by danmosemsft** [comment]
cc @jeffhandley

**Comment by jeffhandley** [comment]
cc @carlossanlop @buyaa-n

**Comment by jeffhandley** [comment]
I'd like to keep this in 6.0.0 until @mahdiva's assigned analyzers are completed, and the others in progress are captured with their final 6.0.0 status. Thereafter, I'll move this to 7.0.0 for the remainder.

**Comment by jeffhandley** [comment]
Closing this user story. Only #45661 remains open for .NET 6.0; the remainder of the analyzers have been captured in #57797 for .NET 7.

**Comment by jeffhandley** [comment]
Minor correction; #40579 might also land in .NET 6.0 (RC2).
