### ISSUE TITLE
Assembly.Load doesn't support side-by-side of different assembly versions in netcoreapp3.1, but it works in net462

### ISSUE THREAD

**Issue by jonathantorley** [dotnet/runtime#43613]
### Description
I've created two libraries, Lib12 and Lib11, that each depend upon newtonsoft v12 and v11 respectively, and build to their own folders. Each of them expose a single function that gets the version of the newtonsoft library they depend upon, returned as a string. All projects are strong named.

I have a third project that uses Assembly.Load to load them each, and run the function, and output the string to console.

In a net462 app, everything works as expected; it loads the two assemblies correctly, and they each return the string of the newtonsoft version they depend on.

If I change the same apps to be netcoreapp3.1, everything falls apart; they either both say v12 (if Lib12 was loaded first), or it blows up trying to load Lib12 if Lib11 was loaded first:
`Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621)`

I've attached a repo with all the apps configured to net462; changing them to netcoreapp3.1 will reproduce the issue.
Here's the repo: https://github.com/jonathantorley/refloadspike

I've logged this as a bug, but I realize that this is most likely a misunderstanding of the differences between core and framework, on my behalf. Can anyone please help me out understanding what's going on here?

### Why I'm doing this
We have a lot of legacy systems that use a (not necessarily well-implemented) plugin architecture, and we're trying to get around issues with dependencies, so I'm investigating how this works. If there's any suggestions on better ways to do side-by-side version loading of dependencies, I'm all ears.

**Comment by vitek-karas** [comment]
This is by design - some docs on this are here: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext
The recommended approach is to isolate is plugin into its own `AssemblyLoadContext` where it can have its own dependencies and there won't be any collisions.
A sample of how this can be done (including two plugins with different versions of Newtonsoft) is here: https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin

**Comment by jonathantorley** [comment]
Thanks for an excellent answer, and such a quick response. That's a perfect example.
