### ISSUE TITLE
New analyzer or extend exisiting one: Replace '.Count() > 1' with 'Skip(1).Any()'

### ISSUE THREAD

**Issue by Evangelink** [dotnet/runtime#43614]
In the same spirit as the analyzer that suggests to use `.Any()` instead of `Count > 0`/`Count == 0` we could suggest `.Skip(1).Any()` in replacement of `Count > 1`/`Count == 1`. 

I am even thinking we could go a bit further and define a threshold (I don't think it's worth having it configurable) for which we can suggest the following change `Count() > X`/`Count() == X` -> `.Skip(X).Any()`.

WDYT?

**Comment by huoyaoyuan** [comment]
```csharp
    [SimpleJob(RuntimeMoniker.NetCoreApp50, baseline: true)]
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    [SimpleJob(RuntimeMoniker.Net48)]
    public class Program
    {
        private static IEnumerable<int> _array = Enumerable.Range(0, 100).ToArray();
        private static IEnumerable<int> _enumerable = Enumerable.Range(0, 100).ToArray().Select(x => x * x);

        static void Main(string[] args)
        {
            BenchmarkRunner.Run<Program>();
        }

        [Benchmark]
        public bool SelectCount() => _enumerable.Count() > 1;

        [Benchmark]
        public bool SelectSkipAny() => _enumerable.Skip(1).Any();

        [Benchmark(Baseline = true)]
        public bool ArrayCount() => _array.Count() > 1;

        [Benchmark]
        public bool ArraySkipAny() => _array.Skip(1).Any();
    }
```

|        Method |           Job |       Runtime |      Mean |    Error |   StdDev | Ratio | RatioSD |
|-------------- |-------------- |-------------- |----------:|---------:|---------:|------:|--------:|
|   SelectCount |      .NET 4.8 |      .NET 4.8 | 376.84 ns | 0.376 ns | 0.333 ns | 36.32 |    0.09 |
| SelectSkipAny |      .NET 4.8 |      .NET 4.8 |  50.49 ns | 0.468 ns | 0.415 ns |  4.87 |    0.04 |
|    ArrayCount |      .NET 4.8 |      .NET 4.8 |  19.32 ns | 0.063 ns | 0.056 ns |  1.86 |    0.01 |
|  ArraySkipAny |      .NET 4.8 |      .NET 4.8 |  35.92 ns | 0.372 ns | 0.348 ns |  3.46 |    0.03 |
|   SelectCount | .NET Core 3.1 | .NET Core 3.1 | 158.24 ns | 0.341 ns | 0.303 ns | 15.25 |    0.05 |
| SelectSkipAny | .NET Core 3.1 | .NET Core 3.1 |  29.78 ns | 0.176 ns | 0.156 ns |  2.87 |    0.01 |
|    ArrayCount | .NET Core 3.1 | .NET Core 3.1 |  11.49 ns | 0.020 ns | 0.017 ns |  1.11 |    0.00 |
|  ArraySkipAny | .NET Core 3.1 | .NET Core 3.1 |  42.72 ns | 0.309 ns | 0.274 ns |  4.12 |    0.03 |
|   SelectCount | .NET Core 5.0 | .NET Core 5.0 | 158.11 ns | 0.245 ns | 0.217 ns | 15.24 |    0.04 |
| SelectSkipAny | .NET Core 5.0 | .NET Core 5.0 |  27.27 ns | 0.212 ns | 0.188 ns |  2.63 |    0.02 |
|    ArrayCount | .NET Core 5.0 | .NET Core 5.0 |  10.38 ns | 0.025 ns | 0.022 ns |  1.00 |    0.00 |
|  ArraySkipAny | .NET Core 5.0 | .NET Core 5.0 |  30.87 ns | 0.233 ns | 0.218 ns |  2.97 |    0.02 |

Unlike `Any` that should be always faster, `Skip(1).Any()` is slower in certain scenarios (when `Count()` on the enumerable is really cheap).

https://github.com/dotnet/runtime/blob/c0669313dd36189c6d3bf5c7d5e866284f98263c/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs#L101-L115

**Comment by stephentoub** [comment]
As @huoyaoyuan cites, there are multiple situations (including common ones) where Skip(1).Any() is going to be slower than Count() != 0.  In such situations, it's frequently also going to allocate more, e.g.
```C#
private IEnumerable<int> _list = new List<int>() { 1, 2, 3, 4, 5 };

[Benchmark]
public bool Count() => _list.Count() > 1;

[Benchmark]
public bool SkipAny() => _list.Skip(1).Any();
```

|  Method |      Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |----------:|----------:|----------:|-------:|------:|------:|----------:|
|   Count |  4.492 ns | 0.0335 ns | 0.0297 ns |      - |     - |     - |         - |
| SkipAny | 31.159 ns | 0.1258 ns | 0.1115 ns | 0.0076 |     - |     - |      48 B |

So from a perf perspective, this could very easily represent a regression rather than an improvement, and from a maintainability perspective, the code is harder to understand.

Interesting suggestion, but we shouldn't add this analyzer.  Thanks.

**Comment by Evangelink** [comment]
Thank you all for the various feedback. Looking at the results provided by @huoyaoyuan it seems to me that if we restrict the analyzer to cases where we are sure there was a enumerable this would be beneficial, let me try to list some examples:

```csharp
public class C
{
	public void M(IEnumerable<int> collection)
	{
		if (collection.Count() > 2) // Do not raise here as we don't know the actual type
		{
			// ...
		}

		var hasAnyFiltered = collection.Where(x => x > 1 && x < 5).Count() > 5; // Raise here as we are no longer under a specific collection type.
	}
}
```

**Comment by stephentoub** [comment]
> Raise here as we are no longer under a specific collection type

This would need to bake into the analyzer knowledge of all the optimizations the current implementation of System.Linq enables, with such optimizations potentially changing over time, and thus the guidance for a particular call site changing over time.  For example, in the initial implementation of LINQ, by these rules `list.Select(...).Count() > 1` would have fired the rule, but then optimizations were made to Select such that it no longer would have, yet someone may have already changed their code to the harder to comprehend and now more expensive `list.Select(...).Skip(1).Any()`.

**Comment by Evangelink** [comment]
I get the point of the optimizations changing over time, yet I am not sure to get this part:

>  For example, in the initial implementation of LINQ, by these rules `list.Select(...).Count() > 1` would have fired the rule, but then optimizations were made to Select such that it no longer would have, yet someone may have already changed their code to the harder to comprehend and now more expensive `list.Select(...).Skip(1).Any()`.

If I am reading and understanding things correctly, we have `SelectSkipAny` always faster than `SelectCount` (in net48, netcoreapp3.1 and net5) and this by quite a big factor.

Getting back to the `List` or `Array`, as soon as you have a `Where` or `Select` (probably true for some other methods) you no longer have the optimization.

Regarding the evolution of the runtime (any further optimization), let's say there is at some point an optimization that makes it better to do `myArray.Select(...).Count() > 2` then I wouldn't be much surprised that the analyzer is updated to cover this new knowledge. I agree this means that the analyzer is linked to language intrinsic knowledge but we are talking about "micro-optimization". As pointed out by @mavasani this is not something I would expect to be enable by default but that's sort of on the same line as https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer.

Anyways I don't want you to lose time on this suggestion, there are plenty other analyzers that are probably more interesting. I just wanted to give my 2 cents and make sure we were aligned on the scope and target of this analyzer :)

**Comment by tannergooding** [comment]
> If I am reading and understanding things correctly, we have SelectSkipAny always faster than SelectCount (in net48, netcoreapp3.1 and net5) and this by quite a big factor.

This will only be true for things which don't implement `ICollection<T>`, `IListProvider<T>`, or `ICollection`: https://source.dot.net/#System.Linq/System/Linq/Count.cs,41ef9e39e54d0d0b

**Comment by stephentoub** [comment]
> This will likely only be true for things which don't implement ICollection<T>, IListProvider<T>, or ICollection

Right.  On top of that, though, one of the key points of LINQ is to enable developers to write simple code that expresses their intent neatly, at the expense of performance: you can pretty much always open-code a custom implementation that is in some way faster than what the LINQ implementation can do, avoiding extra interface calls or delegate invocations or allocations or whatever.  I don't want us recommending to developers that they contort their use of LINQ.  For `Count() != 0` vs `Any()`, they're arguably both simple and self-explanatory, at which point we might as well suggest they use `Any()`.  But that's not the case for `Count() > X` vs `Skip(X).Any()`: the former is very clear and reads exactly how you might think about the condition, whereas the latter requires you to think through the implications of skipping X items and what that means for what's left.
