### ISSUE TITLE
[browser] runtime-test.js arguments are not correctly processed

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#43630]
Argument processing from the command line breaks at the first argument it doesn't understand and that means it is impossible to use run-v8.sh and pass arguments like --setenv=TZ=America/Argentina/Buenos_Aires

**Comment by lewing** [comment]
The quick fix looks like handling --run specially and requiring another plain arg in that case

**Comment by EgorBo** [comment]
is this related: https://github.com/dotnet/runtime/pull/41608/files ?

**Comment by lewing** [comment]
The problem comes from the generated run-v8.sh that places the addition arguments after the `--run` argument

here
https://github.com/dotnet/runtime/blob/04c564447771f73c277e3b0deedf28b5e1d8745c/tools-local/tasks/mobile.tasks/WasmAppBuilder/WasmAppBuilder.cs#L266

but then runtime-test.js stops processing arguments when it hits `--run` here:
https://github.com/dotnet/runtime/blob/04c564447771f73c277e3b0deedf28b5e1d8745c/src/mono/wasm/runtime-test.js#L174

something like
```diff
diff --git a/tools-local/tasks/mobile.tasks/WasmAppBuilder/WasmAppBuilder.cs b/tools-local/tasks/mobile.tasks/WasmAppBuilder/WasmAppBuilder.cs
index fce387d9967..255fd16a0fd 100644
--- a/tools-local/tasks/mobile.tasks/WasmAppBuilder/WasmAppBuilder.cs
+++ b/tools-local/tasks/mobile.tasks/WasmAppBuilder/WasmAppBuilder.cs
@@ -265,7 +265,7 @@ public override bool Execute ()
 
         using (var sw = File.CreateText(Path.Join(AppDir, "run-v8.sh")))
         {
-            sw.WriteLine("v8 --expose_wasm runtime.js -- --run " + Path.GetFileName(MainAssembly) + " $*");
+            sw.WriteLine("v8 --expose_wasm runtime.js -- $* --run " + Path.GetFileName(MainAssembly));
         }
 
         return true;
```
Works around it but also makes it impossible to pass additional non `--` arguments to run

**Comment by pavelsavara** [comment]
cc @Daniel-Genkin

**Comment by Daniel-Genkin** [comment]
Perhaps I am misunderstanding but now the `run-v8.sh` script is generated by MSBuild in src/mono/wasm/build/WasmApp.targets starting on line 165. So this code that Larry mentioned no longer exists. https://github.com/dotnet/runtime/blob/b317d0624f36caf7b7c6f61058e9f6663803f30c/src/mono/wasm/build/WasmApp.targets#L165-L182

Also, I just ran it and looks like it does accept the arguments now
![image](https://user-images.githubusercontent.com/16430693/123272406-b4b4d200-d4cf-11eb-8507-8f462b2e38d1.png)

**Comment by lewing** [comment]
${RUNTIME_ARGS} is probably enough to consider this fixed.
