### ISSUE TITLE
Use TargetPlatformMonikers for net5.0  and above targetFrameworks.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#43646]
Sdk added support for platforms in the targetFramework strings. Many of our projects have platform specific tfms. Currently we have workarounds to make nuget and sdk understand these custom frameworks,
But with the new TargetFramework feature we can remove those workarounds for net5.0 and above tfms.

The pre-requiste to this issue is https://github.com/dotnet/runtime/issues/32451 because the sdk doesnt support  "_" in the name.

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
I support this to largely mitigate the restore issues inside Visual Studio. @Anipik does this require https://github.com/dotnet/project-system/issues/6656 to be fixed as well?

**Comment by Anipik** [comment]
>  @Anipik does this require dotnet/project-system#6656 to be fixed as well?

Not in particular, this warning could be seem in customer projects as well but it does not interfere with any VS experience.

**Comment by ViktorHofer** [comment]
Introducing a new warning isn't ideal but maybe this issue gets away anyway before this is completed.
