### ISSUE TITLE
Add System.Runtime.CompilerServices.ILproj to slns targeting net461 in their tests.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#43648]
we need to Add System.Runtime.CompilerServices.ILproj to slns targeting net461 in their tests because all the test projects have a transitive dependency on this assembly. VS doesnt build the project references if they are not in sln.

dependency https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/TestUtilities/TestUtilities.csproj#L79

cc @ViktorHofer @safern @ericstj

**Comment by safern** [comment]
How are the test projects getting this transitive dependency?

**Comment by Anipik** [comment]
https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/TestUtilities/TestUtilities.csproj#L79

**Comment by Anipik** [comment]
In VS we build everything so projects with 461 configs are failing

**Comment by safern** [comment]
Should we instead just add that reference to test projects that really need it?

**Comment by Anipik** [comment]
> Should we instead just add that reference to test projects that really need it?

yes

**Comment by ViktorHofer** [comment]
@Anipik I'm planning to update all slns with slngen. I don't think that we should spend time on keeping them up-to-date manually. @jeffkl just recently added relative path support in the generated slns so I will give it another try.

**Comment by ViktorHofer** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/43109
