### ISSUE TITLE
CoreCLR taking over signal handlers

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/runtime#43642]
We've received [an issue on sentry.native repo](https://github.com/getsentry/sentry-native/pull/388) that our crash reporting SDK's signal handler isn't invoked once the CoreCLR kicks in.

It's it the case that the CoreCLR signal handler sets itself without forwarding the call to any previous thing registered? If so, is it possible to avoid that? Like [how it's done here.](https://github.com/getsentry/sentry-native/blob/73e4324a01441a4a9c0505b3376b855f820763c7/src/backends/sentry_backend_inproc.c#L80)

**Comment by janvorli** [comment]
CoreCLR is forwarding signals that it didn't handle to the handlers registered before CoreCLR registered its ones. E.g. looking at the sigsegv_handler, it ends with:
https://github.com/dotnet/runtime/blob/35f62c1c6938da074b4c350d6f81947d38bb316d/src/coreclr/src/pal/src/exception/signal.cpp#L571
Here is the code that registers each handler:
https://github.com/dotnet/runtime/blob/35f62c1c6938da074b4c350d6f81947d38bb316d/src/coreclr/src/pal/src/exception/signal.cpp#L924-L962

**Comment by janvorli** [comment]
I've forgotten to mention what it means that we handle a hardware exception signal. We handle it only if it occurred in managed code or at specific places in our native runtime. 
The following function determines whether we will handle it or not:
https://github.com/dotnet/runtime/blob/35f62c1c6938da074b4c350d6f81947d38bb316d/src/coreclr/src/vm/exceptionhandling.cpp#L5071

**Comment by GenuineAster** [comment]
What about on Windows? I think the behavior was sane on Linux but different on Windows. From going through the coreclr source a while ago I'm pretty sure coreclr didn't have the same behavior there?

**Comment by bruno-garcia** [comment]
I was able to collect minidumps from Windows, macOS and Linux automatically with this [NuGet package](https://github.com/getsentry/sentry-dotnet-minidump). 

As the app crashes I mean, a minidump is generated and uploaded. I can see the processed minidump or download it to see it on Visual Studio.
