### ISSUE TITLE
Websockets Not Detecting Proxy Correctly on .Net Core

### ISSUE THREAD

**Issue by eohlde** [dotnet/runtime#43656]
### Description

Using the sample code below works correctly with .Net Framework 4.8. However if you execute the exact same code on .Net Core 3.1, it fails to connect. 

The issue has been tracked into  the HttpConnectionPoolManager.cs file and the call to GetProxy. 
* In Framework 4.8, the URI is changed from a 'ws' scheme to an 'http' scheme via the 'internal.cs' file and a public WebRequest Create(Uri) method
* In Core 3.1, the URI is not changed (so the request to _proxy.GetProxy is a 'ws' scheme) and proxy detection fails

### Configuration

I'm using Windows 10 1909.
*** IMPORTANT *** -> I am behind a corporate proxy, with a .pac autodetection script

### Other information

Sample Code:
``` C#
using System;
using System.Net.WebSockets;
using System.Threading;

namespace Basic_Websocket_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("HTTP_PROXY", null);
            Environment.SetEnvironmentVariable("HTTPS_PROXY", null);

            var client = new ClientWebSocket();
            var uri = new Uri("ws://echo.websocket.org");
            try
            {
                var task = client.ConnectAsync(uri, new CancellationToken());
                task.Wait();
            }
            catch (Exception e)
            {
                // with .Net Core, I always get here, with an exception 
                // "Unable to connect to the remote server
                // with an inner exception ("no such host is known")
                Console.WriteLine("\nException Caught!");
                Console.WriteLine("Message :{0} ", e.Message);
            }
            Console.WriteLine("Done");
        }
    }
}

```

[My SO issue](https://stackoverflow.com/questions/64437705/clientwebsocket-throws-exception-with-corporate-proxy-and-net-core-3-1)

**Comment by wfurt** [comment]
This seems like Windows specific issue. On Linux this seems to work as we check using IsSupportedNonSecureScheme() and that covers `ws://`. On Windows we call WinHttpHelper and that does not seems to handle ws(s) properly. We should perhaps update `GetProxyForUrl()` and add logic to rewrite schema in similar way as Framework.
