### ISSUE TITLE
Support immutable types with configuration binding

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#43662]
Similar to https://github.com/dotnet/runtime/issues/43359 but specifically for configuration binding. Support binding from IConfiguration to say a record or any immutable .NET object. This has been solved in JSON (it's basically deserialization) and we can use any lessons learned there to implement a solution in configuration.

```C#
public record Settings(string Color, int Length);

public void ConfigureServices(IServiceCollection services)
{
    services.Configure<Settings>(Configuration.GetSection("MySettings"));
}
```

**Comment by eerhardt** [comment]
6.0 is now feature complete. Moving to 7.0.

**Comment by AradAral** [comment]
Disappointing that this was not implemented in 6.0 to be honest.

**Comment by SteveDunn** [comment]
@maryamariyan - I'm happy to look at this one

**Comment by maryamariyan** [comment]
> @maryamariyan - I'm happy to look at this one

@SteveDunn sure

**Comment by SteveDunn** [comment]
Hi @davidfowl - I've created a PR for this. I had a question:

Currently, a `ConfigurationKeyNameAttribute` can be applied to properties. Do we want this to also now be applicable to parameters?  

Also, my implementation picks the biggest non-parameterless constructor and binds as many parameters as it can.  I don't know how smart we need to be for this, but this seems like a reasonable starting point.

**Comment by Bosch-Eli-Black** [comment]
Will this change also make it so that configuration can now be bound to a class that has a non-empty constructor? 🙂

e.g.
```c#
public class User
{
    public string Username { get; }
    public string Password { get; }

    public User(string username, string password)
    {
        Username = username ?? ArgumentNullException.ThrowIfNull(username);
        Password = password ?? ArgumentNullExeption.ThrowIfNull(password);
    }
}
```

**Comment by SteveDunn** [comment]
Yes, @Bosch-Eli-Black - that, and records with primary constructors

**Comment by SteveDunn** [comment]
@davidfowl - you mentioned JSON in this description, so in the PR, we've borrowed some ideas from S.T.J. What are your thoughts [on this thread in the PR](https://github.com/dotnet/runtime/pull/67258#discussion_r880943936)?

**Comment by Bosch-Eli-Black** [comment]
> Yes, @Bosch-Eli-Black - that, and records with primary constructors

@SteveDunn Great, thanks! 🙂

**Comment by SteveDunn** [comment]
So very pleased to see this feature done. It'll be useful to a lot of people. And it's been great to be able to contribute to a library that's used by so many people. Big thanks to the reviewers for steering such a feature to completion.

**Comment by davidfowl** [comment]
![SteveHarveyHappyGIF](https://user-images.githubusercontent.com/95136/172942999-a4111ee6-b957-42e6-840e-4661b7e9adaa.gif)

**Comment by davidfowl** [comment]
Yes

**Comment by Bosch-Eli-Black** [comment]
Thanks a ton for the implementation, @SteveDunn ! 🙂
