### ISSUE TITLE
[Mono] Vector256 bug

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#43676]
```csharp
Console.WriteLine(Vector256.Create(1,2,3,4).GetElement(3));
```
Expected output:
```
4
```
Actual output:
```
139755651033901
```

Works as expected in LLVM-mode, but not in JIT.
It's expected to use software fallbacks and work even without SIMD support.

/cc @vargaz @imhameed

**Comment by EgorBo** [comment]
Tracking issue for https://github.com/dotnet/runtime/pull/43578/files#diff-72d87bb5dc27f15b0bfbc2423cff89c3085f4109dc8cd5d83e1724d828ebbde0R946 runtime test.

**Comment by imhameed** [comment]
The repro code no longer generates bogus results, and `HardwareIntrinsics/General/Regression/GitHub_43569` will be reenabled in https://github.com/dotnet/runtime/pull/54127.

**Comment by imhameed** [comment]
https://github.com/dotnet/runtime/pull/54127 was merged and `HardwareIntrinsics/General/Regression/GitHub_43569` is running.
