### ISSUE TITLE
Ensure ICU is fully linked out in invariant mode

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43689]
This is enabled by other work we're doing as part of .NET 6, but we should add assertions in addition to that to make sure everything really is going away.

We should be able to create a new project with the latest SDK, set the following properties, and have the native ICU bits fall away:
```
    <InvariantGlobalization>true</InvariantGlobalization>
    <WasmBuildNative>false</WasmBuildNative>
```

**Comment by lewing** [comment]
To do this we need to be able to scan the linked assemblies for qcalls and we are running into https://github.com/dotnet/runtime/issues/43791

**Comment by lewing** [comment]
qcall linking should be in https://github.com/dotnet/runtime/pull/43798 what is the status here?

**Comment by vargaz** [comment]
This will be solved when pinvoke linking is enabled since the icall qcalls are treated as pinvokes.
However, the icu data/startup code still needs to be disabled.

**Comment by CoffeeFlux** [comment]
I wanted this as a separate issue to add checks to make sure it's not getting included, though like Zoltan said this is dependent on https://github.com/dotnet/runtime/issues/43783 to possibly happen.

**Comment by vargaz** [comment]
This should work now, set the `InvariantGlobalization` and `WasmBuildNative` msbuild properties to `true`.

**Comment by marek-safar** [comment]
@vargaz does it work for interpreter mode?

**Comment by vargaz** [comment]
Yes.

**Comment by CoffeeFlux** [comment]
At what point will I be able to replicate this with a nightly SDK drop? Does Blazor need to pick up runtime changes, or should this work right now? And if so, what exactly do I need to do in order to see it work - just make a new blazorwasm project and set `WasmBuildNative` in the csproj?

**Comment by marek-safar** [comment]
Blazor need to pickup new runtime pack and then you set `InvariantGlobalization` msbuild property
