### ISSUE TITLE
IEnumerable Tuple GetEnumerator

### ISSUE THREAD

**Issue by Logerfo** [dotnet/runtime#43687]
## Background and Motivation

https://github.com/dotnet/csharplang/discussions/2197#discussioncomment-107567

## Proposed API

```c#
public static IEnumerator<(T1, T2)> GetEnumerator<T1, T2>(this (IEnumerable<T1> a, IEnumerable<T2> b) pair) => pair.a.Zip(pair.b, (a, b) => (a, b)).GetEnumerator();
```
For several arities, starting at two, it can go on:
```c#
public static IEnumerator<(T1, T2, T3, T4)> GetEnumerator<T1, T2, T3, T4>(this (IEnumerable<T1> a, IEnumerable<T2> b, IEnumerable<T3> c, IEnumerable<T4> d) pair)
    => pair.a.Zip(pair.b, (a, b) => (a, b)).Zip(pair.c, (a, c) => (a.a, a.b, c)).Zip(pair.d, (a, d) => (a.a, a.b, a.c, d)).GetEnumerator();
```

I don't know where this could go, because `GetEnumerator` as extension methods is a new thing.

## Usage Examples

```c#
foreach(var (a, b) in (collectionA, collectionB)) 
{
	// This block will execute only while both `a` and `b` continue to yield values

	// Code goes here
}
```

**Comment by stephentoub** [comment]
Why is this sufficiently better than:
```C#
foreach(var (a, b) in collectionA.Zip(collectionB))
{
}
```
to warrant a new API?

**Comment by Logerfo** [comment]
@stephentoub I think the bigger the arity, the bigger the gain from the feature:
```c#
public static IEnumerator<(T1, T2, T3, T4)> GetEnumerator<T1, T2, T3, T4>(this (IEnumerable<T1> a, IEnumerable<T2> b, IEnumerable<T3> c, IEnumerable<T4> d) pair)
    => pair.a.Zip(pair.b, (a, b) => (a, b)).Zip(pair.c, (a, c) => (a.a, a.b, c)).Zip(pair.d, (a, d) => (a.a, a.b, a.c, d)).GetEnumerator();


foreach(var (a, b, c, d) in (collectionA, collectionB, collectionC, collectionD)) 
{
	// This block will execute only while both `a`. `b`, `c` and `d` continue to yield values

	// Code goes here
}
```
So you can have `var (a, b, c, d) in (collectionA, collectionB, collectionC, collectionD)` instead of `var (((a, b), c), d) in collectionA.Zip(collectionB).Zip(collectionC).Zip(collectionD)`.

**Comment by stephentoub** [comment]
> I think the bigger the arity, the bigger the gain from the feature

So the actual proposal is for a bunch of methods like the one you included in the initial post?

**Comment by Logerfo** [comment]
@stephentoub Yes, for several arities. I'll add that to the original post.

**Comment by stephentoub** [comment]
Thanks.  Without agreeing or disagreeing with the feature, wouldn't it be better to expose it as additional Zip overloads that return IEnumerable?  Then the output is consumable also by other IEnumerable-based APIs, e.g. the rest of LINQ.  It also avoids the oddity of such IEnumerator-returning extension methods that would be a first for LINQ.

**Comment by Logerfo** [comment]
@stephentoub Hmm, I see. That would be a step towards a better experience with `foreach`es, but in that case I think the original proposal is better. But I recognize that your proposal makes the data more viable for LINQ. What I'm thinking is that both proposals are not mutually exclusive. Both can be implemented and each one has its best use case. In fact, the implementation of the original proposal would be simpler if your proposal is already implemented, since it would be a simple proxy implementation.

**Comment by stephentoub** [comment]
> What I'm thinking is that both proposals are not mutually exclusive

Personally I don't see a lot of benefit in adding additional methods to enable:
```C#
foreach (var (a, b, c) in (collectionA, collectionB, collectionC)) { ... }
```
instead of:
```C#
foreach (var (a, b, c) in collectionA.Zip(collectionB, collectionC)) { ... }
```
I actually think the former is problematic as, while terse, it's not intuitive to me what it means to enumerate a tuple.  Why does that imply zip?  Why not cross product, for example?

**Comment by Logerfo** [comment]
@stephentoub I see the zip operation as straightforward, but I cannot explain why. As I already consider your proposal as an improvement, I think we can move forward creating new overloads for arities greater than two for the extension method you pointed out.

**Comment by eiriktsarpalis** [comment]
Hi @Logerfo, sounds good to me, would you be able to update the API proposal so that it reflects the change?

**Comment by Logerfo** [comment]
@eiriktsarpalis I'm closing this issue and opened another one at #43702. Thanks.
