### ISSUE TITLE
[wasm] Experiment with emscripten settings to shrink binary size

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43694]
The emscripten [settings file](https://github.com/emscripten-core/emscripten/blob/master/src/settings.js) defines a lot of different settings we could possibly set to get size wins without too much effort, but it's hard to ballpark how much of a difference these will make.

Some options that appear initially promising:
- [ ] dlmalloc - we could switch to a more compact implementation, or just remove this entirely from mono-codeman.c
- [ ] EVAL_CTORS - this tries to evaluate global ctors at compile-time, and might potentially give us size wins on the ICU builds?
- [ ] INCOMING_MODULE_JS_API - we probably don't need most of these?
- [ ] WebGL - there are a lot of random WebGL settings that might be keeping things around?
- [ ] ASSERTIONS - this adds runtime assertions that we may not need but bloat the code size

**Comment by CoffeeFlux** [comment]
Some experiments done, but the results are not very promising.

**Comment by lewing** [comment]
closing this
