### ISSUE TITLE
Statically link native libraries into singlefilehost on OSX and Windows

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#43699]
Currently we only support this on Linux.
We should extend the support to other supported/tested platforms.

Prerequisite:#41299

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/runtime/issues/43072?

**Comment by VSadov** [comment]
@agocke - #43072 is about statically linking the components of the runtime, while this is about native libraries that live in libs partition - Like `clrcompression.dll`, `libSystem.Net.Security.Native.so`, `ibSystem.Security.Cryptography.Native.Apple.dylib` and the like. 

Each platform has some of these, except Linux that currently embeds all it needs, but does it in a way that would not work for Windows and OSX, so we should switch it to a more cross-platform friendly plan as well.

The problems that need to be solved are very different, so it makes sense to do these separately and track separately.

**Comment by VSadov** [comment]
Switching to a cross-platform linking of libs is tracked in https://github.com/dotnet/runtime/issues/41299. 
We may that separately and before this workitem or just do them together. 

(similar to doing #43423 first, which just made code more cross-platform friendly and then do #43556)

**Comment by VSadov** [comment]
This was implemented in:
- Windows : https://github.com/dotnet/runtime/issues/41299
- OSX, FreeBSD and other Unix-like : https://github.com/dotnet/runtime/pull/45995
