### ISSUE TITLE
[wasm] Experiment with getting rid of SHA1Transform in the runtime

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43693]
This is currently kept alive due to public key token generation, which is done on assembly load. Is this accessed only from managed, in which case we could just avoid calculating it on the native side? Could we precompute this as part of the bundle?

**Comment by lewing** [comment]
@CoffeeFlux did this every go anywhere?

**Comment by CoffeeFlux** [comment]
I think I looked into it but there ended up being some complicating factor. Maybe we needed the property computation to be lazier? Either way, there's nothing concrete as a result of this.

**Comment by lewing** [comment]
calling this closed
