### ISSUE TITLE
Allow to allocate known eternal objects (especially buffers)

### ISSUE THREAD

**Issue by ayende** [dotnet/runtime#4369]
In our scenario, we do a lot of I/O work. The problem with I/O is that it requires pinning the memory. Which lead to fragmentation.
We tend to pool those buffers early on system start, but because they are pinned, they cannot be moved to higher gens, and cause fragmentation of Gen0.

It would be great if we had a way to tell the GC "hey, this is going to be around for a long time, and it is going to be pinned, so move it somewhere out of the way".

**Comment by GrabYourPitchforks** [comment]
There's now work being done on this front. See:

 * https://github.com/dotnet/runtime/blob/0b25063ec056b0d6668bf0848d108d8c873f3fce/docs/design/features/PinnedHeap.md
 * https://github.com/dotnet/runtime/pull/32283
 * https://github.com/dotnet/runtime/issues/27146

**Comment by SingleAccretion** [comment]
This capability has now been exposed via the [`GC.AllocateArray(pinned: true)`](https://learn.microsoft.com/en-us/dotnet/api/system.gc.allocatearray?view=net-7.0) API.
