### ISSUE TITLE
[wasm] Selectively strip the Name section of the wasm blob

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43690]
Currently, this section takes up about 150K without ICU and 550K with ICU. For a minimal sample we should get rid of everything other than a handful of functions. For the normal build we should get rid of the ICU symbols other than the ones we call directly since they are of little benefit to us in stack traces. See https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#name-section

**Comment by lewing** [comment]
@CoffeeFlux it is much more useful to speak in terms of compressed size for metrics like this.

**Comment by lewing** [comment]
Stripping all the debug information via wasm-opt --strip-debug which removes more than the name section reduces the brotli compressed size:
Size | Case
-----|------
883475 | with debug
776250 | stripped
107225 | difference

**Comment by lewing** [comment]
@kg thoughts on how difficult it would be to strip all names matching a regex while preserving the rest?

**Comment by kg** [comment]
> @kg thoughts on how difficult it would be to strip all names matching a regex while preserving the rest?
Very easy, we'd eat an extra byte or two of filler for the stripped names worst case but it'll compress out

**Comment by lewing** [comment]
@tqiu8 please prioritize

**Comment by tqiu8** [comment]
This is no longer an issue due to #43951, which uses wasm-opt from emscripten to strip out the custom section including names. This will not affect the debugger performance.
