### ISSUE TITLE
Hosts, in particular statically linked ones should be built in clr partition.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#43700]
It is so happened that hosts are built in Installer.

This is not a problem for hosts that refer to native libraries dynamically. However when they need to statically link a number of components (coreclr, jit, libs), building them all in the same partition would simplify the logistics of the build and will make it easer to assure mutual compatibility of the parts.

It is hard to arrange this move while we pick native libraries form libs partition, but once #43699 is implemented we should move static host to clr partition.
This will have to include:
- moving/writing appropriate tests
- most likely moving other hosts as well.

**Comment by am11** [comment]
Would moving corehost to `src/native/corehost` be the right direction for this? I made a prototype for this, that also purges the `cli/` directory from the middle to flatten the structure a little bit. The only nuisance is `corehost.proj` script, which shares version/commit-hash targets with other parts of installer, so it remained under installer (still moved from `src/installer/corehost/` to one level up). If this is interesting, can issue a PR after static linkage PR is in.

**Comment by VSadov** [comment]
resolved by https://github.com/dotnet/runtime/pull/48254
