### ISSUE TITLE
Perf issue in System.Diagnostics.Activity

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#43704]
The `Stop` method on `Activity` has this check:

https://github.com/dotnet/runtime/blob/284b938fb86357231b3ada5414a9cafd930c8d74/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L612

The `Id` getter will actually do an allocation the first time it is accessed for W3C IdFormat:
https://github.com/dotnet/runtime/blob/284b938fb86357231b3ada5414a9cafd930c8d74/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L167

I think the check should be:

```csharp
            if (_id == null && _spanId == null)
            {
                NotifyError(new InvalidOperationException(SR.ActivityNotStarted));
                return;
            }
```

That would match other such checks in `Activity`:

https://github.com/dotnet/runtime/blob/284b938fb86357231b3ada5414a9cafd930c8d74/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L557

And would avoid the allocation.

/cc @tarekgh @eddynaka @cijothomas @noahfalk

**Comment by tarekgh** [comment]
@CodeBlanch I think this would be reasonable to fix.
