### ISSUE TITLE
Improve AppModel inner dev loop

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#43705]
- [ ] Move bundler out of installers
- [x] Move hosts into CLR partition
- [ ] Move host test prep into a "build" step. Currently to run hosting tests one needs to actually run the tests from the command line at least once `build -s Host.Tests -test` which will prepare necessary files on disk. Only after that it's possible to run them directly from VS or one-by-one from command line.
  - Already discussed this with Jeremy after his changes to separate host build subsets and shared framework improvements.
- [x] Document and improve a way to run a single hosting test from command line. Currently this works well from within VS on Windows. Other platforms are problematic.

**Comment by safern** [comment]
@agocke which area would this be?

**Comment by agocke** [comment]
Great question! Infra probably...

**Comment by jkoritzinsky** [comment]
A number of improvements for the host development experience are coming with my shared framework PR, which should be merged in early December.

**Comment by agocke** [comment]
I think this is basically done. We have issues for individual problems now.
