### ISSUE TITLE
System.IO.Ports - Unable to open a SerialPort when BaudRate is set to 1M on a Mac

### ISSUE THREAD

**Issue by MicBoucinha** [dotnet/runtime#43719]
### Description

Unable to connect to a board with a BaudRate set to 1M on a Mac, using System.IO.Ports. The same code works properly on Linux and Windows.

Example code I am using (created a console app using the dotnet new console command):

```csharp
        static void Main(string[] args)
        {
            var ports = SerialPort.GetPortNames();       // always works nicely

            var mySer = new SerialPort("/dev/cu.usbserial-AR0JMV5Z",
                                                    1000000,
                                                    Parity.None, 
                                                    8,
                                                    StopBits.One);

            var msg = new byte[] { 0x02, 0x05, 0x21, 0xFF, 0x01, 0x01, 0x29};

            mySer.Open();

            mySer.Write(msg, 0 , msg.Length);

            while (!Console.KeyAvailable)
                ;

            mySer.Close();
        }
```

When opening the port, I receive the following exception:

```csharp
Exception has occurred: CLR/System.ArgumentException
An unhandled exception of type 'System.ArgumentException' occurred in System.IO.Ports.dll: 'Value does not fall within the expected range.'
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
```

### Configuration
* NET Core 3.1.8 and also tried on .NET 5.0-rc2
* Tried in separate occasions, in both SDKs
    * \<PackageReference Include="System.IO.Ports" Version="4.7.0"/>
    * \<PackageReference Include="System.IO.Ports" Version="5.0.0-rc.2.20475.5"/>
* MacOS Catalina 10.15.7, x64
* FT232R USB UART device (ProdID: 0x6001, VendorID: 0x0403 - FTDI)

### Regression?
Not to my knowledge.

### What I also tried

* I tried to use the NetCoreSerial nuget package (https://www.nuget.org/packages/NetCoreSerial/) and was able to connect and send the message properly. I noticed that that library uses Libc to connect to the port and the .NET runtime uses termios. 
* Tried the same in Ubuntu 20.04.1 LTS and Windows 10 with the same SDK versions and have no issues there so I am assuming this is specific to how Mac handles the usb serial.
* Also tried to connect to the board using Python 3.8 (with pyserial v3.4) and everything works nicely.
* Checked the termios.h on the XCode MacSDK folder and the max BaudRate there is only 230400 so I am assuming that the other library and in python, that "limitation" can be circumvented somehow. 
* Tried to install FTDI VCP drivers 2.4.4 and aliasing the BaudRate according to these instructions (https://spin.atomicobject.com/2013/06/23/baud-rates-ftdi-driver-mac/) and was able to connect but no messages are sent properly so the issue might be something that I don't understand.

Please let me know if you need more information regarding this issue.

Does this happen with anyone else? 

Does anyone know of a workaround?

Thanks!

**Comment by krwq** [comment]
Not sure, it's listed but it might not be defined on OSX. We should definitely investigate solution using libc and see if this is something we could do or fallback to.

**Comment by wfurt** [comment]
termios.h
```
/*
 * Standard speeds
 */
#define B0      0
#define B50     50
#define B75     75
#define B110    110
#define B134    134
#define B150    150
#define B200    200
#define B300    300
#define B600    600
#define B1200   1200
#define B1800   1800
#define B2400   2400
#define B4800   4800
#define B9600   9600
#define B19200  19200
#define B38400  38400
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
#define B7200   7200
#define B14400  14400
#define B28800  28800
#define B57600  57600
#define B76800  76800
#define B115200 115200
#define B230400 230400
#define EXTA    19200
#define EXTB    38400
#endif  /* (!_POSIX_C_SOURCE || _DARWIN_C_SOURCE) */
```

It seems like it ends with 230400. Even if we force, the driver would probably not support it.
If you have setup, can you try it with some standard app. - like minicom @MicBoucinha

**Comment by MichaelCarey** [comment]
I'd be really grateful if you might also please consider non standard baud rates. This is not presently supported on System.IO.Ports. I have tried to set the uart clock freq but opening the the port resets it.  Be great if System.IO.Ports provided access to the uart clock freq or divisor if non standard baud rates is not possible. Thanks much!

**Comment by MicBoucinha** [comment]
I have never used minicom before.

I installed it with brew and tried to setup the connection using `minicom -s`.
In that case, the baud rate speed allowed are the ones defined in the termios.h, so it only allows me to select up to 230400.

I tried to run using `minicom -b 1000000 -D /dev/cu.usbserial-XXXXXX` and no error was presented. However I wasn't able to send anything so far. I will try to learn how I can do it and let you know afterwards.

In the meantime, I tried to connect to the device using CoolTerm (https://freeware.the-meiers.org/) and was able to successfully connect to the device and send a command. 

Please let me know what I can try further to help find out the possible issue/limitation.

Thanks!

**Comment by wfurt** [comment]
Do you have Mac with serial port or do you use some external USB adapter @MicBoucinha ? From what I remember, some of the USB adapters would come with custom driver and that can possibly do more than standard speeds. 

We _could_ define B1000000 (and others) if missing and we can try to set it. I don't know _if_ and _how_ that would fail, but that may be the opportunistic path. (on thin ice)

**Comment by wfurt** [comment]
BTW feel free to contribute @MichaelCarey. Any new API would need to go through API review and be reasonably portable across platforms. Chances are not great IMHO but I could be wrong if we can clearly demonstrate the value.

**Comment by MicBoucinha** [comment]
This is a Macbook Pro (Early 2015). I connect it directly to a custom board with a FTDI controller through a usb port. I tried with the official FTDI drivers (2.4.4) but the result is the same as with Apple's native driver (on Catalina).

On my searches online, I bumped into this comment: https://discussions.apple.com/thread/1587991. Not sure if that is valid for how System.IO.Ports handles the connection.

**Comment by wfurt** [comment]
The IOSSIOSPEED may work. It seems like it does not support reading the current speed and needs to be done last, but we can probably make it work. 
Unfortunately, I currently do not have HW where I can test it. Let me know if you would be willing to participate in testing some experimental code @MicBoucinha

**Comment by MicBoucinha** [comment]
Most certainly.

**Comment by wfurt** [comment]
here is what I would like you to do @MicBoucinha 
1. get daily master build here: https://github.com/dotnet/installer
2. publish self-contained app via `dotnet publish -r OS X-x64`
3. get bits from linked PR [here](
https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-dba18da5-fcbc-48d3-84db-17a038767e65fd888da087d451280/test-runtime-net6.0-OSX-Debug-x64.zip?sv=2019-07-07&se=2020-11-19T19%3A33%3A42Z&sr=c&sp=rl&sig=BSWboemAKy63rEOEZ2IsEm45FBKakeWHZ844U77F9Ns%3D)
4. extract libSystem.IO.Ports.Native.dylib and replace original under your app.
5. run your tests

there are different ways - like rebuilding runtime with proposed change but I thought the steps above are easiest to follow. f this fails, please collect and post any errors you get.

**Comment by MicBoucinha** [comment]
Hi @wfurt,

I just tested following your instructions and the Port opened at 1M baud rate with no issues and I was able to send a command to the board successfully. 

I also tested to send a command to the board that would force a reply and I could also receive the reply properly. I tested it with two board that I have access at the moment, even though the communication settings are the same.

.NET SDK: 6.0.100-alpha.1.20531.2
System.IO.Ports: 5.0.0-rc.2.20475.5 with the replaced dylib.

Please let me know how can I further test this. 

Thank you!
