### ISSUE TITLE
why mono --interp dictionary iterator slower than python?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#43720]
the c# code
```c#
namespace IterMap
{
    class Program
    {
        static void Main(string[] args)
        {
            Dictionary<int, string> map = new Dictionary<int, string>();
            for (int i = 0; i < 10000; i++)
            {
                map[i] = "" + i;
            }

            Stopwatch sw = Stopwatch.StartNew();
            string b;
            sw.Start();
            for (int j = 0; j < 100; j++)
            {
                foreach (KeyValuePair<int, string> entry in map)
                {
                    b = entry.Value;
                }
            }
            sw.Stop();
            Console.WriteLine(String.Format("test_iterate_map, Time taken: {0}ms", sw.Elapsed.TotalMilliseconds));

        }
    }
}
```

> run with mono --interp test.exe with release configuration.

mono --verions:
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

the result:
> test_iterate_map, Time taken: 133.8439ms

the python code
``` python
# -*- coding: utf-8 -*-
import time

def main():
	map = {}
	for i in range(0, 10000):
		map[i] = str(i)
	start = time.time()
	map_v = ""
	for j in range(0, 100):
		for key, value in map.items():
			map_v = value
	end = time.time()

	print("test_iterate_map, Time taken: %.4fms %s" % ((end - start) * 1000), map_v)
```
the result:
> test_iterate_map, Time taken: 66.9999ms

**Comment by SunnyWar** [comment]
`Stopwatch sw = Stopwatch.StartNew();
 string b;
 sw.Start();`

should be 

`Stopwatch sw = Stopwatch.StartNew();
 string b;`

**Comment by Joe4evr** [comment]
Performance benchmarks should be measured with [BenchmarkDotNet](https://www.nuget.org/packages/BenchmarkDotNet/), because factors such as JIT warmup and GC timings make naïve `Stopwatch` measurements inaccurate by nature.

**Comment by chrisaut** [comment]
Even if it's slower, Dictionaries are meant for key lookups, not as a generic container to loop over. Better use a List<KeyValuePair> if that's the use case.

Sure, let's get it as fast as possible but not at the cost of lookup performance.

**Comment by srxqds** [comment]
thank you， i think the Python faster is because it is native implemented
