### ISSUE TITLE
Add System.Math API overloads for nint/nuint

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#43733]
## Background and Motivation
C# 9 includes the new `nint/nuint` types, but it gets pretty awkward to use them in code that was previously using `Math` APIs such as `Min` or `Max`. This proposal is about adding overloads for the `int/uint` APIs in `System.Math` to support `nint/nuint`.

Right now you either have to manually write ternary operators everywhere to work around this, or just stick with `int/uint`.

## Proposed API

```csharp
namespace System
{
    public static class Math
    {
        public static nint Abs(nint value);
        public static nuint Clamp(nuint value, nuint min, nuint max);
        public static nint Clamp(nint value, nint min, nint max);
        public static nint DivRem(nint a, nint b, out nint result);
        public static nint Max(nint val1, nint val2);
        public static nuint Max(nuint val1, nuint val2);
        public static nint Min(nint val1, nint val2);
        public static nuint Min(nuint val1, nuint val2);
        public static nint Sign(nint value);
    }
}
```

**Comment by tannergooding** [comment]
Looking at the other APIs, there is also:
```
BigMul
Clamp
DivRem
```

I don't think `BigMul` makes sense, for the same reason it won't work for `long`; but `Clamp` and `DivRem` seem like reasonable overloads to provide.

**Comment by Sergio0694** [comment]
Added `Clamp` and `DivRem`, was looking at the .NET Standard reference and missed those 😅

**Comment by tannergooding** [comment]
Thanks!

Notably we don't expose unsigned `DivRem` overloads today. Maybe we should....

**Comment by terrajobst** [comment]
Looks good as proposed

```C#
namespace System
{
    public static class Math
    {
        public static nint Abs(nint value);
        public static nuint Clamp(nuint value, nuint min, nuint max);
        public static nint Clamp(nint value, nint min, nint max);
        public static nint DivRem(nint a, nint b, out nint result);
        public static nint Max(nint val1, nint val2);
        public static nuint Max(nuint val1, nuint val2);
        public static nint Min(nint val1, nint val2);
        public static nuint Min(nuint val1, nuint val2);
        public static nint Sign(nint value);
    }
}
```

**Comment by tannergooding** [comment]
See the decision on https://github.com/dotnet/runtime/issues/42156 for `DivRem` and the value tuple pattern.

**Comment by Praveen-Rai** [comment]
Can we also add Math.Pow() to the list ? Presently it operates only on doubles.

**Comment by svick** [comment]
@Praveen-Rai I think that's a separate proposal, considering the issues that were previously raised about it at https://github.com/dotnet/runtime/issues/25784.
