### ISSUE TITLE
Large memory dependency in OrdinalCasing::ToUpper

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#43732]
https://github.com/dotnet/runtime/blob/43bc8e85d16db7a5a152bea86a55b492027bf420/src/libraries/System.Private.CoreLib/src/System/Globalization/OrdinalCasing.Icu.cs#L88 has a dependency on the large array which is unnecessary. The whole array is about ~25k~ 2k and aggressively allocated in the static constructor but it needs to actually store only 32 bytes of data. Please replaced the multi-dimensional array with simple binary map (0 for existing null, 1 for s_noCasingPage).

**Comment by tarekgh** [comment]
> The whole array is about 25k and aggressively allocated in the static constructor 

This is not true. the whole static array size is 256 * sizeof(IntPtr) which maximum static allocation is 2K. how did you come up with the 25K?

**Comment by tarekgh** [comment]
> Please replaced the multi-dimensional array with simple binary map (0 for existing null, 1 for s_noCasingPage).

This is not going to work, at runtime we allocate more dynamic tables and add to this static array.

**Comment by marek-safar** [comment]
> This is not true. the whole static array size is 256 * sizeof(IntPtr) which maximum static allocation is 2K

Sorry, that was a typo, it's 2k which is still very large.

> This is not going to work, at runtime we allocate more dynamic tables and add to this static array.

The existing code only replaces the null entries. I made one suggestion and there are other solutions to remove the large initialization dependency (about 1k of IL) in the code.

**Comment by tarekgh** [comment]
I'll look at that.
