### ISSUE TITLE
Enhance FileSystemEnumerable to track depth recursion

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#43748]
Splitted from #1953

## Background and Motivation

In PowerShell Core repo we are trying to migrate to `FileSystemEnumerable`. Prototype shows great performance improvements.

We need to implement Depth parameter for Get-ChildItem cmdlet (aka `dir`). The parameter limits a depth of recursion.

This cannot be achieved without creating new classes (based on FileSystemEnumerator and FileSystemEnumerable) and creating non-trivial code as it requires processing a directory tree. All this negates the benefits of this API.

## Proposed API

```c#
namespace System.IO
{
    public class EnumerationOptions
    {
        /// <summary>
        /// Stop recursion if current depth exceeds the value.
        /// Default is int.MaxValue (no limit).
        /// </summary>
        public int MaxRecursionDepth { get; set; }  // New API
    }
}
```

## Usage Examples

``` C#
var options = new System.IO.EnumerationOptions
    {
         RecurseSubdirectories = recurse,
         MatchType = MatchType.Win32,
         AttributesToSkip = 0,
         IgnoreInaccessible = false,
         MaxRecursionDepth = 2
    };

var paths = new FileSystemProviderEnumerable<string>(
                directory,
                (ref FileSystemEntry entry) => entry.FileName.ToString()),
                options)
    {
        ShouldIncludePredicate = FileSystemEntryFilter,

        ShouldRecursePredicate = (ref FileSystemEntry entry) => FileSystemRecursionPredicate
    };
```

## Alternative Designs

What is better name - MaxRecursionDepth vs MaxDepthRecursion vs MaxDepthOfRecursion vs MaxDepth ?
(there is `JsonSerializerOptions.MaxDepth`)

## Risks

Minor performance regression due to we have to keep additional uint value in a subdirectory queue.

## Implementation details

Current implementation uses Queue to track subdirectories. We could put [in the queue](https://github.com/dotnet/runtime/blob/d701804307f16e855a8c48a7143040dd474154f1/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Windows.cs#L175) current depth +1 value together with subdirectory path. This allow to restore correct depth value [at subdirectory dequeue](https://github.com/dotnet/runtime/blob/d701804307f16e855a8c48a7143040dd474154f1/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Windows.cs#L212).
And we need add Depth check [in recursion condition](https://github.com/dotnet/runtime/blob/d701804307f16e855a8c48a7143040dd474154f1/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Windows.cs#L164).

**Comment by Jozkee** [comment]
* Should there be a value to specify "no limit"?
  * if the type were `int` then `-1` could mean that (and throw on any other negative value).
* For the sake of naming discussion, there is a similar API called [`JsonSerializerOptions.MaxDepth`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializeroptions.maxdepth?view=net-5.0).
* Why default is `uint.MaxValue`? Perhaps it should be the "no limit" value to avoid breaking behaviors.

**Comment by iSazonov** [comment]
> Should there be a value to specify "no limit"?
> * if the type were `int` then `-1` could mean that (and throw on any other negative value).

I believe we have no need to have "no limit" value:
- it is already _default_ behavior
- _only_ if users need to limit recursion depth they will set explicit value.

Also this complicates implementation without need. If we will have "no limit" value we will have to:
- either check the value on every step
- or convert the value to MaxValue.

If we compare with JsonSerializerOptions.MaxDepth the last has a real default = 64 but for recursion default is "no limit" that is MaxValue.

> For the sake of naming discussion, there is a similar API called JsonSerializerOptions.MaxDepth.

I added this in OP.

> Why default is uint.MaxValue? Perhaps it should be the "no limit" value to avoid breaking behaviors.

The value should be positive by definition - no need to check in implementation.

No breaking changes. On windows long path length is 32,767 characters so max recursion depth is about 16000 and this less then uint.MaxValue.

But I'd agree to follow common pattern if the pattern is `int`.

**Comment by terrajobst** [comment]
* We should `int`
* The default value should be `int.MaxValue`. It seems `0` should just mean don't recurse at all, rather than no limit.

```C#
namespace System.IO
{
    public partial class EnumerationOptions
    {
        public int MaxRecursionDepth { get; set; }
    }
}
```

**Comment by iSazonov** [comment]
> It seems 0 should just mean don't recurse at all, rather than no limit.

Yes, really it is to return only current directory items.

---
The proposal was updated based on the review.

**Comment by iSazonov** [comment]
> The default value should be int.MaxValue. It seems 0 should just mean don't recurse at all, rather than no limit.

@terrajobst This is a contradiction. Default is no recursion which is 0. Yes?

**Comment by iSazonov** [comment]
I am ready to pull PR if .Net team approves.

**Comment by carlossanlop** [comment]
I assigned this issue to you, @iSazonov . Thank you for your help! Looking forward to review the PR.
