### ISSUE TITLE
Using Encoding.GetEncoding("gbk") but get gb2312

### ISSUE THREAD

**Issue by LuGuangguang** [dotnet/runtime#43745]
My platform is Win10(18362),VS 2019,.net core 3.1,System.Text.Encoding.CodePages 4.7.1(5.0 RC I also had used)
When I want to get "gbk" Encoding,I write these code,but I get "gb2312" Encoding.
You know "gb2312" is less than "gbk",so it is not I want.
![图片](https://user-images.githubusercontent.com/34500722/96949298-29d3a000-151a-11eb-96bc-f34b2f83d400.png)
 
![图片](https://user-images.githubusercontent.com/34500722/96949358-4b348c00-151a-11eb-89c6-c8cb942d5fba.png)

**Comment by tarekgh** [comment]
Our current support of `gbk` encoding is through the `codepage 936` we don't support encodings introduced later (which referred to as `gbk1`). We don't have any plans to add any non Unicode codepages as we encourage everyone to use Unicode encoding instead.
Please let's know if you have any more questions.
