### ISSUE TITLE
Observed "Segmentation fault (core dump)" after migrating to Alpine docker image of .Net Core

### ISSUE THREAD

**Issue by shinkarmv** [dotnet/runtime#43753]
Hi Team,

We are started observing the issue with error message - Segmentation fault (core dump).

However, the migration of image works with one application and fails another one.

Hence, we also tried to compare the assembly difference between both applications but found all stuff is similar.

Container logs are as below

Hosting Environment: qa
Content root path: /app/publish
Now listining on: http://0.0.0.0:80
Application started. Press Ctlr +C to shut down

**Comment by wfurt** [comment]
There is not enough details to even guess. Could you perhaps fill the issue template and share some more details about the core -> like show at least the stack trace.

cc: @janvorli in case this turns out to be Alpine PAL issue.

**Comment by shinkarmv** [comment]
Hi @wfurt, @janvorli,

Thank you for comment.

Please find some more details about the issue.

No stack trace returned - only  "Segmentation fault (core dump)" message as error.

On further investigation - I found one error "**tcp connection reset by peers**" - however it was logged in K8s events of pod. but application does not throw that although exception supposed to be thrown by code.

_**Did "tcp connection reset by peers" causes Segmentation fault?**_

After skipped that TCP call - system works as expected.

Regards,
Mukesh

**Comment by wfurt** [comment]
The segmentation fault can be misleading AFAIK and I've seen it also in cases when core is not created. You should check if there is any chance that you have unhandled exception you may hit Assert. If you can reproduce it, you can run it under lldb or you can attach to it from Visual Studio.

**Comment by shinkarmv** [comment]
Thank you @wfurt . Since I am able to fix the issue by handling the exception occurred due to connection refused by peer of one of the infra node.

Hence, closing the issue.
