### ISSUE TITLE
System.Linq.Parallel OrderedPipeliningMergeEnumerator.MoveNext is using API unsupported on browser

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#43752]
System.Linq.Parallel OrderedPipeliningMergeEnumerator.MoveNext is using API unsupported on browser (Monitor.Wait();). It needs to be fixed so it works without `Monitor.Wait()` on browser

`OrderedPipeliningMergeEnumerator.TryWaitForElement` It is calling `Monitor.Wait()`  which is unsupported on browser. Which is further called from [OrderedPipeliningMergeEnumerator.MoveNext](https://source.dot.net/#System.Linq.Parallel/System/Linq/Parallel/Merging/OrderPreservingPipeliningMergeHelper.cs,288) which is overriding `IEnumerator.MoveNext(...)`

_Originally posted by @buyaa-n in https://github.com/dotnet/runtime/pull/43363#r510501000_

**Comment by buyaa-n** [comment]
`AsynchronousChannelMergeEnumerator.MoveNextSlowPath()` also accessing non suppurted `ManualResetEventSlim.Wait()`, i think it doesn't need separate issue as `AsynchronousChannelMergeEnumerator.MoveNextSlowPath()`  also affecting IEnumerator.MoveNext(...)

**Comment by buyaa-n** [comment]
More similar references found:
1. `OrderedHashRepartitionEnumerator.MoveNext(ref Pair<TInputOutput, THashKey> currentElement, ref TOrderKey currentKey)`
2. `HashRepartitionEnumerator.MoveNext(ref Pair<TInputOutput, THashKey> currentElement, ref int currentKey)`
3. `DefaultIfEmptyQueryOperator.MoveNext(ref TSource currentElement, ref TKey currentKey)`
4. `FirstQueryOperator.MoveNext(ref TSource currentElement, ref int currentKey)`
5. `LastQueryOperator.MoveNext(ref TSource currentElement, ref int currentKey)`
6. `TakeOrSkipQueryOperator.MoveNext(ref TResult currentElement, ref TKey currentKey)`
7. `TakeOrSkipWhileQueryOperator. MoveNext(ref TResult currentElement, ref TKey currentKey)`

**Comment by stephentoub** [comment]
These are all the guts of PLINQ.  Really it's just that PLINQ isn't supported on browser, all up.  Either the whole assembly should be annotated as unsupported, or if there's a goal of having it be supported, browser should have its own effectively nop implementation that just delegates everything to Enumerable.

**Comment by buyaa-n** [comment]
As per the suggestion and [discussion](https://github.com/dotnet/runtime/pull/43363#discussion_r522081168),  marked entire assembly unsupported

**Comment by akoeplinger** [comment]
I think we should do what @stephentoub suggested and replace it with an implementation that delegates to Enumerable.

**Comment by danmoseley** [comment]
@akoeplinger does your team expect to do this by Aug 17th

**Comment by akoeplinger** [comment]
@lewing @steveisok what do you think?
