### ISSUE TITLE
IServiceCollection.Configure throw exceptions for POCO class with Regex type property

### ISSUE THREAD

**Issue by shiliangdn** [dotnet/runtime#43758]
### Description

We use Microsoft.Extension libraries for our service. But when we try to inject POCO class with IServiceCollection.Configure function, it throw exception as below snapshot. Our config source is json file and there is a Regex type property in our POCO class. And the Regex property is like this:
            "HostMatcherRegex": {
                "Pattern": ".+[.]ng[.]msg[.]int[.]teams[.]microsoft[.]com",
                "Options": 8
            }

Currently we write customized binder class to unblock. But the way is not convenient. I think better way should be either we support it in the source code or we add support for customized type convertor attribute for POCO class.
![image](https://user-images.githubusercontent.com/8006614/96986386-265d0a80-1554-11eb-9376-c2de1da89f9c.png)

**Comment by davidfowl** [comment]
Regex isn't supported today.
