### ISSUE TITLE
provide Dictionary<T, V> to native implemented, because we found the iterator so slower than python

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#43756]
as these issues show:
https://github.com/dotnet/runtime/issues/43720
https://github.com/dotnet/runtime/issues/42426

the dictionary iterator so slower,  I think it is better to provider native implemented of List and  Dictionary, like Array.

**Comment by BrzVlad** [comment]
The fact that the interpreter is currently slow on these method is not enough of a reason to change the whole bcl implementation. Will keep an eye on tests from https://github.com/dotnet/runtime/issues/42426, for future interp optimizations

**Comment by srxqds** [comment]
ok, thank you.
