### ISSUE TITLE
We should build browser-specific System.Net.WebProxy instead where we could have simple implementation

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#43751]
System.Net.WebProxy accessing APIs unsupported on browser. We should build browser-specific System.Net.WebProxy instead where we could have a simple implementation

_Originally posted by @marek-safar in https://github.com/dotnet/runtime/pull/43363#r509974457_

**Comment by lewing** [comment]
@marek-safar what sort of behavior do you want here?

**Comment by marek-safar** [comment]
I was thinking that we should annotate not working APIs and fix IsLocal to be simple check only.

**Comment by lewing** [comment]
@tqui8 talk a look at this then we can discuss the timeline.
