### ISSUE TITLE
Improve invariant globalization mode to be more complete

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#43774]
The improvements to make invariant globalization mode more complete have been suggested since this mode was introduced. This issue extracts information from various existing comments and suggestion for easier .NET6 tracking.

- [ ] Make basic lower/upper casing of non-ASCII characters work. The experience is pretty bad today if you are non-English speaking and like to use your native alphabet. The size footprint for doing this does not seem prohibitive.
- [x] Throw exceptions when somebody asks for non-invariant culture-specific data to make the bugs caused by missing globalization support easy to discover. We return bogus invariant data silently today.

Related issues
- #30960
- https://github.com/dotnet/dotnet-docker/issues/1877
- https://github.com/dotnet/designs/blob/main/accepted/2020/mono-convergence/globalization-support-in-.net5.md#enhanced-invariant-mode

**Comment by GrabYourPitchforks** [comment]
Also related: https://github.com/dotnet/runtime/issues/20674, which is philosophically a "how do we want `OrdinalIgnoreCase` to behave in an ICU world?" question.

**Comment by Wraith2** [comment]
Libraries can require globalization information to function correctly, for example SqlClient. Currently the way to check if the library is running in invariant mode is `CultureInfo.GetCultureInfo("en-US").EnglishName.Contains("Invariant")` which could be slow if it causes a culture instantiation and isn't obvious. It would be nice if there were a cleaner way to detect the mode.

**Comment by tarekgh** [comment]
> Throw exceptions when somebody asks for non-invariant culture-specific data to make the bugs caused by missing globalization support easy to discover. We return bogus invariant data silently today.

I would be careful doing that. apps using libraries which they don't control and libraries can be creating non invariant cultures.

**Comment by jkotas** [comment]
We can add compat quirks if we find this to be a problem.

**Comment by tarekgh** [comment]
> We can add compat quirks if we find this to be a problem.

I am pretty sure we'll get a lot of noises with that and the volume of complain can be none trivial.

**Comment by danmosemsft** [comment]
@tarekgh could you add an estimated cost label? https://github.com/dotnet/runtime/labels?q=cost

**Comment by tarekgh** [comment]
@danmosemsft done.
