### ISSUE TITLE
This code does not run as expected when compiled with code optimization

### ISSUE THREAD

**Issue by xinchen520** [dotnet/runtime#43787]
```C#
static void Main(string[] args) {
    object key = new object();
    int repeat = 10;
    int count = 0;
    lock (key)
    {
        for (int i = 0; i < repeat; ++i) {
        int x = i;
        Task.Run(() => {
                lock (key)
                {
                    count++;
                }
            });
        }
     }
     while (count != repeat) {
     }
     Console.WriteLine("Done");
}
```

The above code should print "Done". When the code is compiled with code optimization on, it seems the execution will never reach `Console.WriteLine("Done")`. I run the program on netcore 3.1. If I add some statements that is non-trivial inside the while statment, the program runs correctly. I also tried to run the program compiled with optimization on mono, and it runs correctly.

category:correctness
theme:cse
skill-level:expert
cost:medium

**Comment by briansull** [comment]
> does this look familiar to you?
@AndyAyersMS No, I will investigate it.

**Comment by briansull** [comment]
The 3.1 behavior is fine the JIT is allow to optimize this loop:

```
     int repeat = 10;
     int count = value;
      . . .
     while (count != repeat) {
     }
```

By enregistering the 'count'  local variable.   This test has a different thread attempting to asynchronously update the value of 'count'.  If you want this to work correctly then you have to declare 'count' as a 'volatile int'.

**Comment by briansull** [comment]
I will close this issue in a couple of days.

**Comment by briansull** [comment]
Volatile.Read and Volatile.Write are required to update state that is shared between different threads
