### ISSUE TITLE
Math.Min<T> Max<T> Clamp<T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#43796]
## Background and Motivation
Please make it easier to min/max/clamp any classes.

## Proposed API
Right now the Math.Min / Max / Clamp methods only work with a small number of built in data types.  A generic version of these methods should be introduced on the ```Comparer<T>``` base class.

```
public T Comparer<T>.Min(T Value1, T Value2);
public T Comparer<T>.Max(T Value1, T Value2);
public T Comparer<T>.Clamp(T Value, T Min, T Max);

public static T Comparer.Min(T Value1, T Value2) => Comparer<T>.Default.Min(Value1, Value2);
public static T Comparer.Max(T Value1, T Value2) => Comparer<T>.Default.Max(Value1, Value2);
public static T Comparer.Clamp(T Value, T Min, T Max) => Comparer<T>.Default.Clamp(Value1, Min, Max);
```

## Example Implementation
```
    public static class ComparerExtensions {
        public static T Min<T>(this Comparer<T> This, T Value1, T Value2) {
            var ret = This.Compare(Value1, Value2) <= 0
                ? Value1
                : Value2
                ;

            return ret;
        }

        public static T Max<T>(this Comparer<T> This, T Value1, T Value2) {
            var ret = This.Compare(Value1, Value2) >= 0
                ? Value1
                : Value2
                ;

            return ret;
        }

        public static T Clamp<T>(this Comparer<T> This, T Value, T Min, T Max) {
            var ret = Value;
            if (This.Compare(Value, Min) < 0) {
                ret = Min;
            } else if (This.Compare(Value, Max) > 0) {
                ret = Max;
            }

            return ret;
        }
    }
```

## Usage Examples

```Comparer.Clamp(MyValue, TimeSpan.Zero, TimeSpan.FromSeconds(30))```

## Alternative Designs
This could just be ignored.

## Risks
None.

**Comment by EgorBo** [comment]
`Comparer<T>.Default.CompareTo`needs to devirtualized for this: https://github.com/dotnet/runtime/issues/39873

**Comment by GrabYourPitchforks** [comment]
Generic min / max / clamp methods seem worthwhile. But the names feel a bit wrong (first / last? before / after?), and `Math` might not be the right place for it. Otherwise you end up with weirdness like this:

```cs
string first = Math.Min("foo", "bar"); // would compile and return a logical result
```

I don't have better recommendations unfortunately. :(

**Comment by En3Tho** [comment]
What about Comparer.Min/Max/Clamp?

**Comment by TonyValenti** [comment]
@En3Tho Excellent idea!

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/runtime/issues/18481

**Comment by tannergooding** [comment]
@TonyValenti, could you update the original post with the updated API proposal? It sounds like users are wanting to add this to `Comparable`?

**Comment by TonyValenti** [comment]
@tannergooding Updated.

**Comment by tannergooding** [comment]
This might be feasible with the generic math interfaces that are being proposed.

**Comment by tannergooding** [comment]
Closing. This is now feasible using the generic math interfaces. In particular anything `where T : INumber<T>` can now `T.Min`, `T.Max`, or `T.Clamp`
