### ISSUE TITLE
Loop runs ~30% (or ~90%) slower than Java code on GraalVM

### ISSUE THREAD

**Issue by LEI-Hongfaan** [dotnet/runtime#43805]
### Description

Consider the second example Blender.java on the page https://www.graalvm.org/examples/java-performance-examples/ .
```Java
public class Blender {

    private static class Color {
        double r, g, b;

        private Color(double r, double g, double b) {
            this.r = r;
            this.g = g;
            this.b = b;
        }

        public static Color black() {
            return new Color(0, 0, 0);
        }

        public void add(Color other) {
            r += other.r;
            g += other.g;
            b += other.b;
        }

        public void add(double nr, double ng, double nb) {
            r += nr;
            g += ng;
            b += nb;
        }

        public void multiply(double factor) {
            r *= factor;
            g *= factor;
            b *= factor;
        }
    }

    private static final Color[][][] colors = new Color[100][100][100];

    public static void main(String[] args) {
        for (int j = 0; j < 10; j++) {
            long t = System.nanoTime();
            for (int i = 0; i < 100; i++) {
                initialize(new Color(j / 20, 0, 1));
            }
            long d = System.nanoTime() - t;
            System.out.println(d / 1_000_000 + " ms");
        }
    }

    private static void initialize(Color id) {
        for (int x = 0; x < colors.length; x++) {
            Color[][] plane = colors[x];
            for (int y = 0; y < plane.length; y++) {
                Color[] row = plane[y];
                for (int z = 0; z < row.length; z++) {
                    Color color = new Color(x, y, z);
                    color.add(id);
                    if ((color.r + color.g + color.b) % 42 == 0) {
                         // PEA only allocates a color object here.
                         row[z] = color;
                    } else {
                         // In this branch the color object is not allocated at all.
                    }
                }
            }
        }
    }
}
```
Output:
```
996 ms
874 ms
874 ms
870 ms
869 ms
892 ms
875 ms
875 ms
907 ms
875 ms
```
Equivalent C# code using a class Color takes ~11x running time. 
The following version uses a struct Color and has better performance.
```CSharp
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

public class Blender {

    private struct Color {
        nint mt;
        internal double r, g, b;

        internal Color(double r, double g, double b) {
            this.mt = default;
            this.r = r;
            this.g = g;
            this.b = b;
        }

        public static Color black() {
            return new Color(0, 0, 0);
        }

        public void add(Color other) {
            r += other.r;
            g += other.g;
            b += other.b;
        }

        public void add(double nr, double ng, double nb) {
            r += nr;
            g += ng;
            b += nb;
        }

        public void multiply(double factor) {
            r *= factor;
            g *= factor;
            b *= factor;
        }
    }

    private static readonly Color[,,] colors = new Color[100, 100, 100];

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static void Main(String[] args) {
        for (int j = 0; j < 10; j++) {
            long t = Stopwatch.GetTimestamp() * (1000000 / TimeSpan.TicksPerMillisecond);
            for (int i = 0; i < 100; i++) {
                initialize(new Color(j / 20, 0, 1));
            }
            long d = Stopwatch.GetTimestamp() * (1000000 / TimeSpan.TicksPerMillisecond) - t;
            Console.Out.WriteLine(d / 1_000_000 + " ms");
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    private static unsafe void initialize(Color id) {
        fixed (Color* p = colors) {
            var pt = p;
            var c0 = colors.GetLength(0);
            var c1 = colors.GetLength(1);
            var c2 = colors.GetLength(2);
            for (int x = 0; x < c0; x++) {
                //Color<Void>[][] plane = colors[x];
                for (int y = 0; y < c1; y++) {
                    //Color<Void>[] row = plane[y];
                    for (int z = 0; z < c2; z++) {
                        Color color = new Color(x, y, z);
                        color.add(id);
                        if ((color.r + color.g + color.b) % 42 != 0) {
                            // PEA only allocates a color object here.
                            *pt = color;
                        } else {
                            // In this branch the color object is not allocated at all.
                        }
                        ++pt;
                    }
                }
            }
        }
    }
}
```
Output:
```
1370 ms
1357 ms
1356 ms
1359 ms
1359 ms
1359 ms
1357 ms
1356 ms
1358 ms
1358 ms
```
But it is still ~30% slower.
:(

### Configuration

GraalVM
.NET Core 3.1/5.0

### Regression?

No.

### Analysis

Possible causes:
* ~~A struct Color is bigger than a class Color. The Java code has better cache locality.~~
* But we can not switch to a class Color because of lacking stack-allocated objects (escape analysis). Besides, heap object allocations and manipulations are a little slower than those on GraalVM. (GC-related problem?)
* JIT generates poor code for loops.
* Floating-point remainder ~~seems slightly~~ is slower on .NET runtime. (Math.IEEEremainder performs even worse.)

**Comment by EgorBo** [comment]
Looks like the only real bottleneck here is `if ((color.r + color.g + color.b) % 42 != 0)` (in case of `Unsafe` implementation where we don't hit the bound checks)
the only way to make it fast is to perform `%` on integers (avoiding the conversion to fp) perhaps it's what GraalVM does.

**Comment by AmrAlSayed0** [comment]
with this line ```((color.R + color.G + color.B) % 42) != 0``` I get these times:
```
1339 ms
1302 ms
1299 ms
1283 ms
1301 ms
1297 ms
1283 ms
1281 ms
1286 ms
1288 ms
```
with this ```((int)(color.R + color.G + color.B) % 42) != 0```, I get these times:
```
413 ms
400 ms
398 ms
403 ms
400 ms
400 ms
400 ms
398 ms
399 ms
399 ms
```
That's a 70% reduction in runtimes.

**Comment by LEI-Hongfaan** [comment]
@EgorBo 

> Looks like the only real bottleneck here is `if ((color.r + color.g + color.b) % 42 != 0)` (in case of `Unsafe` implementation where we don't hit the bound checks)

What bound checks? Are you referring the unwritten class Color version?
The reason I use unsafe pointers is that currently the performance of non-vector array is pretty low.

> I wonder if GraalVM avoids that int-to-fp conversion and does `idiv` on integers (doesn't sound safe) instead of `fmod`.

Note `initialize(new Color(j / 20, 0, 1));`. I don't think GraalVM is so sophisticated. And I have changed both codes to do integer divisions. C# code is still the ~30% slower one. 

> Issues I noticed:
> `colors.GetLength(0); //1,2` should be converted to compile-time constants due to the fact that `colors` is `static readonly` (with `TC_QuickJitForLoops` on tier1 when `Blender` is statically inited) so the loops become loops with constant limits => can be unrolled/unswitched.

Can not unrolling these loops cause such a perf gap of 450 ms? It's longer the running time of no-op loops.

**Comment by EgorBo** [comment]
>  the performance of non-vector array is pretty low.
Try to rewrite `Color[,,]` to `Color[][][]` just like in Java - going to be the same as `fixed` option (but save `colors` to a temp first - it's a known issue, `static readonly` fields must be invariant for JIT).

So if I've got the GraalVM disasm correctly `(...) % 42 != 0` operation is performed like this: https://gist.github.com/EgorBo/6ea9425c1e28f398db4a7b075651d628#file-blender-initialize-asm-L109-L129 (it uses x87 and inlined)
while RyuJIT just emits a call to `fmod`.

/cc @tannergooding

**Comment by tannergooding** [comment]
> I thought x87 is not used any more

It still is rarely used, just not always.

> it uses x87 fprem and is inlined

`fprem` computes a partial remainder and they are doing so using a loop:
```
0x00000001199fb4c3: fprem  
0x00000001199fb4c5: fstsw  %ax
0x00000001199fb4c8: test   $0x400,%eax
0x00000001199fb4ce: jne    0x00000001199fb4c3
```

This is basically "execute fprem until the C2 flag is clear".

**Comment by tannergooding** [comment]
> while RyuJIT just emits a call to fmod

The Windows x64 implementation of `fmod` is essentially: https://github.com/amd/win-libm/blob/master/fmod.asm
This looks to be using the x87 FPU stack as well and isn't super optimal (it does quite a bit of setup, context saving, and exception checking in addition to the "core loop" JVM has).

The musl implementation doesn't require the x87 FPU and may generates more performant code on modern machines.

**Comment by AndyAyersMS** [comment]
> is it possible to stackalloc a class in some loop and re-box it to the heap when necessary?

Not presently, no. The jit has some experimental support for full escape analysis, but nothing for partial escape analysis.

**Comment by JulieLeeMSFT** [comment]
@LEI-Hongfaan Did you have a chance to look into slow down of the idiv version? Anything more we can answer?
