### ISSUE TITLE
Possible overflow in Numerics.DivRem

### ISSUE THREAD

**Issue by TuomLarsen** [dotnet/runtime#43801]
Please see the following line:
https://github.com/dotnet/runtime/blob/0e402bcd28f38a3b65720474dcd7a338cab0841d/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigIntegerCalculator.DivRem.cs#L198

`shift` can be as much as 31, `valHi` is `t << 32` and `t`comes from 32-bit array. So perhaps `valHi << shift` might overflow?

**Comment by Clockwork-Muse** [comment]
"Overflow" is a specific thing that happens as the result of a _mathematical_ operation (`+ - * /`, etc); shift is a _bitwise_ operation, and won't trigger it.  Normally, pushing bits "off the end" is the desired result.

Are you concerned about data being incorrect?  Or worried about the possible exception?

**Comment by TuomLarsen** [comment]
The concern is that this "pushing bits 'off the end'" might lead to incorrect result.

**Comment by Clockwork-Muse** [comment]
```csharp
// We measure the leading zeros of the divisor
int shift = LeadingZeros(divHi);
```
... so it's going to be shifting things so that the highest bit set is going to be the top-most bit.  So nothing will be pushed off the end.

**Comment by TuomLarsen** [comment]
That's not what the code does.

    valHi << shift
    valHi << LeadingZeros(divHi)
   (((ulong)t << 32) | left[i - 1]) << LeadingZeros(divHi)
   (((ulong)(left[i]) << 32) | left[i - 1]) << LeadingZeros(divHi)

**Comment by Clockwork-Muse** [comment]
Ah, you're right about the shifting off the end.

However, as I said before, this is still the desired behavior.
The key point is [this line](https://github.com/dotnet/runtime/blob/0e402bcd28f38a3b65720474dcd7a338cab0841d/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigIntegerCalculator.DivRem.cs#L188):
```csharp
uint t = i < leftLength ? left[i] : 0;
```

Note that the iteration is _backwards_ from the length of the numbers, so on the first iteration `t` is initially set to `0`.  So on the first iteration the absolute upper digits aren't being shifted off, although they will for subsequent iterations (Assuming the dividend has fewer set bits).
