### ISSUE TITLE
Where's the mutable Json  data representation in C# 

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#43806]
With System.Text.Json  it seems that I can not change/add/remove a property of a dynamic Json.  someone show me to use `JsonDocument` and  "manually rewrite the json  and parse back to JsonDocuement" ,  for me ,this is unacceptable，because if I need to manually write json , then why the libarary `System.Text.Json` exists .   So i'm asking how to do the same in `System.Text.Json` ,  because mvc and  signalr  are both using `System.Text.Json` now, 

```C#
public class ExamQuestion: IExamQuestion
{
     public ExamType ExamType{get;set;}
     public string Question {get;set;}
     ....
    // how can I convert to a Model that work with `System.Text.Json` and ModelBinder
     public JObject Additional {get;set;} = new JObject() 

}

```

**Comment by KalleOlaviNiemitalo** [comment]
Mutable JSON DOM is discussed in <https://github.com/dotnet/runtime/issues/30436>.

**Comment by John0King** [comment]
ok,  and I will close this issue
