### ISSUE TITLE
IHostedService keeps a huge number of references of disposable transient service.

### ISSUE THREAD

**Issue by GggXp** [dotnet/runtime#43819]
ServiceCollectionHostedServiceExtensions.AddHostedService add IHostedService with scoped life time and if my IHostedService using IServiceProvider to get services with transient life time do some work, those transient service cannot be dispose until this scope being disposed while IHostedService will be disposed  at the end of this application life time usually.

**Comment by davidfowl** [comment]
HostedServices are singletons, you can't change the lifetime because they are only ever resolved once at startup and aren't resolved in a scope.

**Comment by GggXp** [comment]
> HostedServices are singletons, you can't change the lifetime because they are only ever resolved once at startup and aren't resolved in a scope.

sorry, maybe it's my mistake. 
I am using dotnet core 3.1. 
But this [List<object>](https://github.com/dotnet/runtime/blob/5a4483eb1c0918542298d1864b7233f962952880/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs#L17)  kept a huge number of references of disposable transient services and comsumed memory.

**Comment by davidfowl** [comment]
Yes, that's by design and unfortunately, it's a bit of a performance trap. Don't resolve transient disposable objects from your IHostedService constructor. If you're looking to do something with a scoped lifetime then you need to explicitly created that scope and resolve services from there.

**Comment by GggXp** [comment]
ok, but why do this design.

**Comment by davidfowl** [comment]
The DI container's is responsible for disposing these objects when the container or scope is disposed. This is true for dependencies of any service that implement `IDisposable`.

**Comment by GggXp** [comment]
thank you.
