### ISSUE TITLE
Support using Crossgen2 for compiling System.Private.CoreLib in CoreCLR build

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#43810]
As part of the planned switchover from Crossgen to Crossgen2 we need to gradually enable Crossgen2 in various parts of our build system. As a first step I believe we should generalize System.Private.CoreLib crossgenning logic to optionally support Crossgen2. As part of this task I'm trying to reduce the duplication in the scripts <code>src/coreclr/crossgen-corelib.cmd / sh</code> by moving most of the build logic into the common project <code>crossgen-corelib.proj</code>.

In my initial local change in this direction I hit the usual problem with <code>setup_vs_tools</code> that is needed on Windows to add paths to a VS installation that are used to search for the PDB native library <code>Microsoft.DiaSymReader.Native.amd64.dll</code>. I'm wondering what is the cleanest way of fixing this:

1) Should we run something like <code>setup_vs_tools</code> at the very beginning i.e. when descending from the build.cmd root script to build.ps1?

2) A relatively conservative way I could approach this now is by changing <code>crossgen-corelib.cmd / sh</code> scripts (that today contain the bulk of the actual work) to thin wrappers, just calling setup_vs_tools on Windows and running the proj script. The downside is that this doesn't solve the descent from <code>eng/Subsets.props</code> to <code>src/coreclr/crossgen-corelib.proj</code>, that still needs a separate solution.

3) Do we actually need / is it the cleanest approach to require VS installation for the presence of the Microsoft.DiaSymReader.Native.amd64.dll library? @tmat, could we consume the library via some Nuget feed instead?

/cc: @dotnet/runtime-infrastructure 
/cc: @dotnet/crossgen-contrib 

RFC: @jkoritzinsky, @ViktorHofer, @safern, @jkotas

**Comment by trylek** [comment]
@mangod9 - what is the proper way to organize this issue? I "triaged it" into "Core Runtime .net 6 Epics" but now it shows in the first column along with the main epic items. How should I make it a subordinate work item of the "Crossgen2 switchover" epic instead?

**Comment by mangod9** [comment]
Made this a user story which should be tagged to #43653.

**Comment by trylek** [comment]
Thank you!

**Comment by terrajobst** [comment]
@mangod9 

> Made this a user story which should be tagged to #43653.

Done. BTW, feel free to make these edits yourself :-)

**Comment by jeffschwMSFT** [comment]
this user story need something to dock against.  Right now it is showing up as a top level user story. :)

**Comment by jeffschwMSFT** [comment]
dropping user story until we can find a suitable parent for this item.

**Comment by mangod9** [comment]
Hi @jeffschwMSFT. It should be parented to #43653. Are you looking for a non-"Team Epic" to parent to?

**Comment by jeffschwMSFT** [comment]
We can try again, it was showing up as a top level item in dotnetepics
