### ISSUE TITLE
Any workaround for lost events on the start with .NET Core 3.0 and .NET Core 3.1?

### ISSUE THREAD

**Issue by valco1994** [dotnet/runtime#43820]
I'm using EventPipe to collect events from .NET Core application, and in my tests, the first expected event is lost sometimes if I'm using .NET Core 3.0 and .NET Core 3.1. I've tried to use standard I/O redirect and lock files for synchronization with the test application, but it did not help.

As far as I understand, this issue is caused by EventPipe initialization which was redesigned in [PR #25760](https://github.com/dotnet/coreclr/pull/25760). And these changes were not released in .NET Core 3.0 or .NET Core 3.1.

Could you propose some workaround?

**Comment by valco1994** [comment]
@josalem

**Comment by valco1994** [comment]
I understand that I can introduce some delay before the session start and test application business logic start, but maybe something better can be proposed

**Comment by josalem** [comment]
(coming off vacation; sorry for the delay!)

You're correct, the changes in the session enable path were not back ported to 3.1.  For testing purposes pre-5.0, I added a sentinel event to the testing harness to work around the async nature of `EventPipe::Enable`.

https://github.com/dotnet/runtime/blob/598426c8ccf2d1d41038d711f2187899d50ff367/src/tests/tracing/eventpipe/common/IpcTraceTest.cs#L191-L204

The test harness listens for the sentinel event + other providers and starts the test generating workload once it sees the first event from the sentinel provider.

You could do something similar: your application has a sentinel provider that generates events until it sees a `sentinel.lock` created.  Your reader app would start a session that listens for the sentinel provider _in addition to your desired events_, then create the `sentinel.lock` file once it sees the first event from the sentinel provider.  Once your application sees `sentinel.lock` it continues execution and stops sending the sentinel event.

In the test suite, applications trace themselves, but the overhead of this mechanism is exceedingly small.  For a multi-app scenario like yours, I would imagine the overhead to be similarly small.

**Comment by valco1994** [comment]
Thank you, @josalem, I will think if I can apply this approach

**Comment by tmds** [comment]
@valco1994 does it help if you use environment variables? See `EventPipe environment variables` section in his blog post: https://developers.redhat.com/blog/2019/12/23/tracing-net-core-applications/.

**Comment by valco1994** [comment]
Thank you, @tmds, I know about EventPipe environment variables, but this approach doesn't fit me

**Comment by josalem** [comment]
It looks like the question has been answered.  If you still need advice, we can reopen it :smile:.

**Comment by valco1994** [comment]
Your answer is exhaustive,  thank you
