### ISSUE TITLE
In a mixed UWP c++/c# project, enabling "Complie with .NET Native tool chain" results in blank screen without useful debug information

### ISSUE THREAD

**Issue by exotexot** [dotnet/runtime#43823]
I'm having troubles with my react-native-windows app submission to the microsoft store due to app certification prbolems. As described in this issue: https://github.com/microsoft/react-native-windows/issues/4516 there are problems, apparently running a mixed c++ / c# project, with the submission process. A solution to fix initial app certificaiton you are required to enable .net native-ization of the code.

After adding the solution mentioned here: https://github.com/microsoft/react-native-windows/issues/4516#issuecomment-665348666, I cannot run my app anymore. The app literally gets stuck with a blank screen without errors being thrown in either terminal console or visual studio debug output. I tried using DotNetNativeVersion 2.2.3 and 2.2.8-rel-28605-00, added all Exception flags to be thrown, but literally nothing happens. Without having the fix applied, I can run and build my app without problems. That seems super strange to me but must somehow be related to the .net native-ization. Any ideas how this could be related?

System:
OS: Windows 10 10.0.19041
CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Memory: 9.30 GB / 15.97 GB
Binaries:
Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK: Not Found
Windows SDK:
AllowDevelopmentWithoutDevLicense: Enabled
AllowAllTrustedApps: Enabled
Versions: 10.0.18362.0, 10.0.19041.0
IDEs:
Android Studio: Not Found
Visual Studio: 16.7.30611.23 (Visual Studio Community 2019)
Languages:
Java: Not Found
Python: Not Found
npmPackages:
@react-native-community/cli: ^4.13.0 => 4.13.0
react: 16.11.0 => 16.11.0
**react-native: 0.62.2 => 0.62.2
react-native-windows: ^0.62.14 => 0.62.14**
npmGlobalPackages:
react-native: Not Found

**Comment by safern** [comment]
I'm not sure if that is the right area... cc: @jkotas @MichalStrehovsky

**Comment by jkotas** [comment]
The feedback for .NET Native for UWP is not actionable in this repo. Could you please report this problem via https://developercommunity.visualstudio.com/ instead?
