### ISSUE TITLE
API documentation debt - System.Net

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43859]
Area owners: @kjpou1 for `HttpRequestOptions`, @dotnet/ncl for the rest.

** **Updated** **

The following APIs were introduced in 6.0 and did not get documented in triple slash. They will need to be manually documented directly in dotnet-api-docs, and must target the net6-rc1 branch. This needs to be done before Tuesday September 14th so we have enough time to generate the IntelliSense package that will be shipped to GA.

<details>
  <summary>Old instructions</summary>

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

</details>
<details>
  <summary>System.Net</summary>

DocId | Summary | Parameters | TypeParameters | ReturnValue
-- | -- | -- | -- | --
[P:System.Net.WebHeaderCollection.Item(System.String)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net/WebHeaderCollection.xml) | Missing | Missing | NA | NA
[T:System.Net.Http.HeaderEncodingSelector\`1](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HeaderEncodingSelector\`1.xml) | Present | Present | Missing | Present
[M:System.Net.Http.HttpContent.CreateContentReadStream(System.Threading.CancellationToken)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpContent.xml) | Missing | Missing | NA | Missing
[P:System.Net.Http.HttpRequestMessage.Options](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestMessage.xml) | Missing | NA | NA | NA
[M:System.Net.Http.HttpRequestOptions.#ctor](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptions.xml) | Missing | NA | NA | NA
[T:System.Net.Http.HttpRequestOptions](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptions.xml) | Missing | NA | NA | NA
[M:System.Net.Http.HttpRequestOptions.Set\`\`1(System.Net.Http.HttpRequestOptionsKey{\`\`0},\`\`0)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptions.xml) | Missing | Missing | Missing | NA
[M:System.Net.Http.HttpRequestOptions.System#Collections#Generic#IDictionary<System#String,System#Object>#TryGetValue(System.String,System.Object@)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptions.xml) | Missing | Missing | NA | Missing
[M:System.Net.Http.HttpRequestOptions.TryGetValue\`\`1(System.Net.Http.HttpRequestOptionsKey{\`\`0},\`\`0@)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptions.xml) | Missing | Missing | Missing | Missing
[M:System.Net.Http.HttpRequestOptionsKey\`1.#ctor(System.String)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptionsKey\`1.xml) | Missing | Missing | NA | NA
[T:System.Net.Http.HttpRequestOptionsKey\`1](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptionsKey\`1.xml) | Missing | NA | Missing | NA
[P:System.Net.Http.HttpRequestOptionsKey\`1.Key](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/HttpRequestOptionsKey\`1.xml) | Missing | NA | NA | NA
[P:System.Net.Http.SocketsHttpHandler.Properties](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Http/SocketsHttpHandler.xml) | Missing | NA | NA | NA
[M:System.Net.Security.NegotiateStream.WriteAsync(System.ReadOnlyMemory{System.Byte},System.Threading.CancellationToken)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Security/NegotiateStream.xml) | Present | Present | NA | Missing
[M:System.Net.Security.NegotiateStream.WriteAsync(System.Byte[],System.Int32,System.Int32,System.Threading.CancellationToken)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Net.Security/NegotiateStream.xml) | Present | Missing | NA | Missing

</details>

**Comment by karelz** [comment]
@ManickaP note that there is already community PR for this.
Thanks @FilipToth!

**Comment by lewing** [comment]
cc @pranavkm
