### ISSUE TITLE
API documentation debt - System.Formats.Cbor

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43858]
Area owners:  @eiriktsarpalis

The `CborContentException` type was accidentally missed it in the 5.0 effort. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>System.Formats.Cbor</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue
  -- | -- | -- | -- | --
  M:System.Formats.Cbor.CborContentException.#ctor(System.String,System.Exception) | Missing | Missing | NA | NA
  M:System.Formats.Cbor.CborContentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext) | Missing | Missing | NA | NA
  M:System.Formats.Cbor.CborContentException.#ctor(System.String) | Missing | Missing | NA | NA
  T:System.Formats.Cbor.CborContentException | Missing | NA | NA | NA

  The System.Formats.Cbor namespace is also missing a summary. We don't have an equivalent file in the runtime repo where this can be documented, so please add the text directly in dotnet-api-docs:
  https://github.com/dotnet/dotnet-api-docs/blob/c9445d2d3a5711aea5998fde980110c14bcc1075/xml/ns-System.Formats.Cbor.xml#L3

</details>

**Comment by eiriktsarpalis** [comment]
I believe the missing entries were added manually in [this PR](https://github.com/dotnet/dotnet-api-docs/pull/4992#pullrequestreview-510652839) to dotnet-api-docs. If I get this correctly, this issue is about backporting dotnet-api-docs back into source?

**Comment by carlossanlop** [comment]
Great! We now need to get these docs ported to dotnet-api-docs, after which we can consider this issue fixed.

@eiriktsarpalis If you want to help (using [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool)), that would be great. Otherwise, I can eventually do it myself.

**Comment by eiriktsarpalis** [comment]
Fixed by #43882
