### ISSUE TITLE
API documentation debt - System.Linq

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43854]
Area owners: @eiriktsarpalis @adamsitnik

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>System.Linq</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue
  -- | -- | -- | -- | --
  M:System.Linq.ImmutableArrayExtensions.Aggregate\`\`3(System.Collections.Immutable.ImmutableArray{\`\`2},\`\`0,System.Func{\`\`0,\`\`2,\`\`0},System.Func{\`\`0,\`\`1}) | Present | Missing | Present | Present
  M:System.Linq.ImmutableArrayExtensions.Single\`\`1(System.Collections.Immutable.ImmutableArray{\`\`0},System.Func{\`\`0,System.Boolean}) | Present | Missing | Present | Present
  M:System.Linq.ImmutableArrayExtensions.ToArray\`\`1(System.Collections.Immutable.ImmutableArray{\`\`0}) | Present | Missing | Present | Present

</details>

**Comment by himanshu8088** [comment]
Hey @carlossanlop, 

I can pick this up. Please let me know if interested in assigning this to me.
As you mentioned in the description, it seems param is not documented in the following source code, please confirm if this one you are referring to -
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Immutable/src/System/Linq/ImmutableArrayExtensions.cs

**Comment by carlossanlop** [comment]
Thank you, @himanshu8088 for offering your help! I assigned this issue to you.

Correct, there are 3 methods in the `ImmutableArrayExtensions` with one or more missing parameters: `Aggregate`, `Single` and `ToArray`.

The table does not keep in mind any missing exceptions, so if you find any, please add them.

Don't forget to read the [documentation guidelines wiki](https://github.com/dotnet/dotnet-api-docs/wiki) to understand the proper language to use with parameters (and exceptions if you realize any have to be added).

**Comment by himanshu8088** [comment]
Thanks @carlossanlop , I will fix as per doc guidelines.

**Comment by adamsitnik** [comment]
@himanshu8088 please let us know if you need any help

**Comment by himanshu8088** [comment]
> @himanshu8088 please let us know if you need any help

thanks @adamsitnik will let you know if required, I just gave a look over the documentation guidelines and it looks simpler and doable, will start with the code changes in free time.

**Comment by jeffhandley** [comment]
@himanshu8088 FYI -- I'm adding @eiriktsarpalis and myself to the assignees for the purpose of seeing this on our team's project board.

**Comment by eiriktsarpalis** [comment]
cc @layomia

**Comment by eiriktsarpalis** [comment]
Issue was addressed by #51845.
