### ISSUE TITLE
Task.Id: potentially unnecessary volatile modifier on the backing field

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#43856]
https://github.com/dotnet/runtime/blob/dd23c81e3c23866164a62b16311bbc08c00e2643/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L123
https://github.com/dotnet/runtime/blob/dd23c81e3c23866164a62b16311bbc08c00e2643/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1178-L1190

`Task.Id`'s implementation only uses `Interlocked` to write to `m_taskId`, which should introduce a full memory fence. I don't see what declaring `m_taskId` as `volatile` is doing that `Interlocked` isn't already doing.

**Comment by stephentoub** [comment]
Without the volatile,  it would be permissible for an extra read to be introduced,  e.g. along the lines of:
```
int id = m_taskId;
if (m_taskId != 0) return id;
...
return m_taskId;
```
which would then enable 0 to be erroneously returned if there's a race.

That said, there are two volatile reads here when there need only be one. That would only have an impact on arm.

**Comment by WizardBrony** [comment]
@stephentoub Oh wow, I didn't know `volatile` prevented things like read introduction... Is that documented anywhere?

Also, since `volatile` is required, would it be best to read `m_taskId` once into a local? Maybe something like this?

```c#
        public int Id
        {
            get
            {
                int id = m_taskId;
                if (id == 0)
                {
                    int newId = NewId();
                    id = Interlocked.CompareExchange(ref m_taskId, newId, 0);
                    if (id == 0)
                        return newId;
                }

                return id;
            }
        }
```

**Comment by stephentoub** [comment]
>  would it be best to read m_taskId once into a local?

Right, that's what I was alluding to with "there are two volatile reads here when there need only be one".  It could be done with a local as you suggest.  Or just removing `volatile` from the field and using `Volatile.Read` on the relevant read:
```C#
private int m_taskId;
...
if (Volatile.Read(ref m_taskId) == 0)
{
    int newId = NewId();
    Interlocked.CompareExchange(ref m_taskId, newId, 0);
}
return m_taskId;
```
I'd personally opt for that approach.

As noted, the extra volatile read only has any real impact on ARM.  On x86/64, the volatile evaporates as part of the asm codegen.

**Comment by WizardBrony** [comment]
@stephentoub Okay, that makes sense. As for `volatile` and `Volatile.Read` preventing read introduction, do you have any insight as to when read introductions are possible?

**Comment by stephentoub** [comment]
> do you have any insight as to when read introductions are possible?

It's rare.  There's some discussion of it at https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2

**Comment by WizardBrony** [comment]
@stephentoub Yes, I've read that article and it kind of scares me, particularly when using language features like the null-conditional operator to do things like [thread-safe delegate invocation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#thread-safe-delegate-invocation). For something like `PropertyChanged?.Invoke(…)`, is it expected that `PropertyChanged` be declared volatile?

**Comment by stephentoub** [comment]
In theory, yes. In practice, no.  Such patterns are so common the runtime goes to extra lengths as an implementation detail to ensure they work.  And it's a detail it could never change because so much code relies on it. For example, all writes of reference types to fields are treated as volatile even if not specified. But we do try to write library code that doesn't assume that and to be explicit about it.

**Comment by WizardBrony** [comment]
That makes sense. Thank you very much for your time.

**Comment by stephentoub** [comment]
Thanks.  I put up https://github.com/dotnet/runtime/pull/43891 to remove the extra volatile read.
