### ISSUE TITLE
API documentation debt - System.Collections

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43850]
Area owners: @eiriktsarpalis @layomia

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>System.Collections</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue
  -- | -- | -- | -- | --
  T:System.Collections.Immutable.ImmutableArray`1.Builder | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableArray`1.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableDictionary`2.Builder | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableDictionary`2.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableHashSet`1.Builder | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableHashSet`1.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableList`1.Builder | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableList`1.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableQueue`1.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableSortedDictionary`2.Builder | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableSortedDictionary`2.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableSortedSet`1.Builder | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableSortedSet`1.Enumerator | Present | NA | Missing | NA
  T:System.Collections.Immutable.ImmutableStack`1.Enumerator | Present | NA | Missing | NA

</details>

**Comment by danmosemsft** [comment]
@carlossanlop is there an analyzer or warning setting that would give errors (so clearing out the errors would resolve this issue)?

Is there a preferred ordering of tags, eg., summary, typeparam, remarks?

**Comment by carlossanlop** [comment]
> _is there an analyzer or warning setting that would give errors (so clearing out the errors would resolve this issue)?_

@danmosemsft Yes, there is a way: https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

But we don't want to enable it yet, it will cause a lot of noise if any public APIs do not have documentation in source, which is the case for a lot of them.

We will first have to port back everything from dotnet-api-docs to triple slash comments and then we will enable that rule. We are working on the plan for this, and we will work on it assembly by assembly. I'll let you know when we are ready to begin.

To answer your question, my suggestion is to simply add the missing documentation from the table. Once we run the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool), it will detect and port only the items that are missing in dotnet-api-docs. Items with existing documentation in that repo will not get their documentation overwritten.

> _Is there a preferred ordering of tags, eg., summary, typeparam, remarks?_

Visual Studio will automatically add the required skeleton if the user types "///" on top of the API to document.

**Comment by danmosemsft** [comment]
> will cause a lot of noise if any public APIs do not have documentation in source

I was just thinking for someone fixing an issue like this, where the source is nearly all documented, they may want to enable it locally so it guides them to the problems.

**Comment by TheMaximum** [comment]
I was looking to see if I could add the missing typeparams into the code, but appear to have hit a wall.
The issues are the same for all types, I'm taking ``ImmutableArray{T}`` as example here.

The mentioned classes are split into multiple files with partial classes. In the case of ``ImmutableArray{T}``, the class summary is added in ``ImmutableArray_1.Minimal.cs`` and includes the required ``typeparam``:

https://github.com/dotnet/runtime/blob/a350bc6e0896d2869e4028fdafb94588e3fe0867/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L14-L37

When it comes to the ``Builder`` and ``Enumerator`` classes, the [documentation on Docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.builder?view=net-5.0) shows one type parameter (``T``). When checking in ``ImmutableArray_1.Builder.cs``, the ``Builder`` class doesn't have any type parameters. It implements ``IList{T}`` and ``IReadOnlyList{T}``, but those type parameters are passed via the type parameter of ``ImmutableArray{T}``.

https://github.com/dotnet/runtime/blob/a350bc6e0896d2869e4028fdafb94588e3fe0867/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Builder.cs#L9-L18

When I would add the ``typeparam`` element to the comment displayed above, I get a ``CS1711`` error (``XML comment has a typeparam tag for 'T', but there is no type parameter by that name``), which is logical - there isn't.

When adding a comment (including ``typeparam``) to the ``ImmutableArray{T}`` class in ``ImmutableArray_1.Builder.cs``, I get a ``CS1710`` error (``XML comment has a duplicate typeparam tag for 'T'``), which is also logical as the ``typeparam`` is already present in ``ImmutableArray_1.Minimal.cs``.

---

Could you indicate how the documentation gets this ``typeparam`` for the ``Builder``/``Enumerator`` classes and what the appropriate action to take would be, @carlossanlop?

**Comment by eiriktsarpalis** [comment]
Superseded by #54869.
