### ISSUE TITLE
API documentation debt - System.ComponentModel

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43852]
Area owners: @safern @ericstj

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>System.ComponentModel</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue
  -- | -- | -- | -- | --
  M:System.ComponentModel.BackgroundWorker.Dispose(System.Boolean) | Missing | Missing | NA | NA

</details>

**Comment by ericstj** [comment]
This looks like an easy fix.  Just missing docs on a single API.  cc @dotnet/area-system-componentmodel

**Comment by buyaa-n** [comment]
I see the `Summary` and `Parameters` sections are documented already: https://github.com/dotnet/dotnet-api-docs/blob/e15fd6a32cae6a52fca00d71887ba3e9ad2b880d/xml/System.ComponentModel/BackgroundWorker.xml#L339-L340
