### ISSUE TITLE
API documentation debt - Microsoft.Extensions.Caching

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43868]
Area owners: @maryamariyan @eerhardt 

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>Microsoft.Extensions.Caching.Distributed</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Caching.Distributed namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Caching.Distributed.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed?branch=master
  T:Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/DistributedCacheEntryExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions?branch=master
  M:Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions.SetAbsoluteExpiration(Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions,System.DateTimeOffset) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/DistributedCacheEntryExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions.SetAbsoluteExpiration?branch=master
  M:Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions.SetAbsoluteExpiration(Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions,System.TimeSpan) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/DistributedCacheEntryExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions.SetAbsoluteExpiration?branch=master
  M:Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions.SetSlidingExpiration(Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions,System.TimeSpan) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/DistributedCacheEntryExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryExtensions.SetSlidingExpiration?branch=master
  M:Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/DistributedCacheEntryOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions.-ctor?branch=master
  M:Microsoft.Extensions.Caching.Distributed.IDistributedCache.GetAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/IDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.IDistributedCache.GetAsync?branch=master
  M:Microsoft.Extensions.Caching.Distributed.IDistributedCache.RefreshAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/IDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.IDistributedCache.RefreshAsync?branch=master
  M:Microsoft.Extensions.Caching.Distributed.IDistributedCache.RemoveAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/IDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.IDistributedCache.RemoveAsync?branch=master
  M:Microsoft.Extensions.Caching.Distributed.IDistributedCache.SetAsync(System.String,System.Byte[],Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/IDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.IDistributedCache.SetAsync?branch=master
  M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.#ctor(Microsoft.Extensions.Caching.Memory.IMemoryCache) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.-ctor?branch=master M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.#ctor(Microsoft.Extensions.Options.IOptions{Microsoft.Extensions.Caching.Memory.MemoryDistributedCacheOptions},Microsoft.Extensions.Logging.ILoggerFactory) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.-ctor?branch=master
  M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.#ctor(Microsoft.Extensions.Options.IOptions{Microsoft.Extensions.Caching.Memory.MemoryDistributedCacheOptions}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.-ctor?branch=master
  M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.GetAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.GetAsync?branch=master
  T:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache?branch=master
  M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.RefreshAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.RefreshAsync?branch=master
  M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.RemoveAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.RemoveAsync?branch=master
  M:Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.SetAsync(System.String,System.Byte[],Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Distributed/MemoryDistributedCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Distributed.MemoryDistributedCache.SetAsync?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Caching.Memory</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Caching.Memory namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Caching.Memory.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory?branch=master
  T:Microsoft.Extensions.Caching.Memory.CacheEntryExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheEntryExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheEntryExtensions?branch=master
  T:Microsoft.Extensions.Caching.Memory.CacheExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Get(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Get?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Get``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Get?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,System.Func{Microsoft.Extensions.Caching.Memory.ICacheEntry,``0}) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,System.Func{Microsoft.Extensions.Caching.Memory.ICacheEntry,System.Threading.Tasks.Task{``0}}) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Set``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,``0,System.TimeSpan) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Set?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Set``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,``0,System.DateTimeOffset) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Set?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Set``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,``0,Microsoft.Extensions.Primitives.IChangeToken) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Set?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Set``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,``0,Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Set?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.Set``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,``0) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.Set?branch=master
  M:Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue``1(Microsoft.Extensions.Caching.Memory.IMemoryCache,System.Object,``0@) | Missing | Missing | Missing | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue?branch=master
  F:Microsoft.Extensions.Caching.Memory.CacheItemPriority.High | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheItemPriority.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheItemPriority?branch=master
  F:Microsoft.Extensions.Caching.Memory.CacheItemPriority.Low | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheItemPriority.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheItemPriority?branch=master
  F:Microsoft.Extensions.Caching.Memory.CacheItemPriority.NeverRemove | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheItemPriority.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheItemPriority?branch=master
  F:Microsoft.Extensions.Caching.Memory.CacheItemPriority.Normal | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/CacheItemPriority.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.CacheItemPriority?branch=master
  T:Microsoft.Extensions.Caching.Memory.EvictionReason | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/EvictionReason.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.EvictionReason?branch=master
  F:Microsoft.Extensions.Caching.Memory.EvictionReason.None | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/EvictionReason.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.EvictionReason?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCache.Compact(System.Double) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCache.Compact?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCache.CreateEntry(System.Object) | Present | Missing | NA | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCache.CreateEntry?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCache.Dispose(System.Boolean) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCache.Dispose?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCache.Remove(System.Object) | Present | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCache.Remove?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(System.Object,System.Object@) | Present | Missing | NA | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue?branch=master
  T:Microsoft.Extensions.Caching.Memory.MemoryCacheEntryExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCacheEntryExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCacheEntryExtensions?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCacheEntryOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions.-ctor?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.-ctor?branch=master
  P:Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.Clock | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.Clock?branch=master
  T:Microsoft.Extensions.Caching.Memory.MemoryCacheOptions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryCacheOptions?branch=master
  M:Microsoft.Extensions.Caching.Memory.MemoryDistributedCacheOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryDistributedCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryDistributedCacheOptions.-ctor?branch=master
  T:Microsoft.Extensions.Caching.Memory.MemoryDistributedCacheOptions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/MemoryDistributedCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.MemoryDistributedCacheOptions?branch=master
  M:Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/PostEvictionCallbackRegistration.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration.-ctor?branch=master
  P:Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration.EvictionCallback | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/PostEvictionCallbackRegistration.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration.EvictionCallback?branch=master
  T:Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/PostEvictionCallbackRegistration.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration?branch=master
  P:Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration.State | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Memory/PostEvictionCallbackRegistration.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Memory.PostEvictionCallbackRegistration.State?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Caching.Redis</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Caching.Redis namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Caching.Redis.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis?branch=master
  M:Microsoft.Extensions.Caching.Redis.RedisCache.#ctor(Microsoft.Extensions.Options.IOptions{Microsoft.Extensions.Caching.Redis.RedisCacheOptions}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCache.-ctor?branch=master
  M:Microsoft.Extensions.Caching.Redis.RedisCache.GetAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCache.GetAsync?branch=master
  T:Microsoft.Extensions.Caching.Redis.RedisCache | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCache?branch=master
  M:Microsoft.Extensions.Caching.Redis.RedisCache.RefreshAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCache.RefreshAsync?branch=master
  M:Microsoft.Extensions.Caching.Redis.RedisCache.RemoveAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCache.RemoveAsync?branch=master
  M:Microsoft.Extensions.Caching.Redis.RedisCache.SetAsync(System.String,System.Byte[],Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCache.SetAsync?branch=master
  M:Microsoft.Extensions.Caching.Redis.RedisCacheOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.Redis/RedisCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.Redis.RedisCacheOptions.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Caching.SqlServer</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Caching.SqlServer namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Caching.SqlServer.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer?branch=master
  M:Microsoft.Extensions.Caching.SqlServer.SqlServerCache.#ctor(Microsoft.Extensions.Options.IOptions{Microsoft.Extensions.Caching.SqlServer.SqlServerCacheOptions}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer.SqlServerCache.-ctor?branch=master
  M:Microsoft.Extensions.Caching.SqlServer.SqlServerCache.GetAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer.SqlServerCache.GetAsync?branch=master
  M:Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RefreshAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RefreshAsync?branch=master
  M:Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RemoveAsync(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RemoveAsync?branch=master
  M:Microsoft.Extensions.Caching.SqlServer.SqlServerCache.SetAsync(System.String,System.Byte[],Microsoft.Extensions.Caching.Distributed.DistributedCacheEntryOptions) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer.SqlServerCache.SetAsync?branch=master
  M:Microsoft.Extensions.Caching.SqlServer.SqlServerCacheOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.SqlServer/SqlServerCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.SqlServer.SqlServerCacheOptions.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Caching.StackExchangeRedis</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Caching.StackExchangeRedis namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Caching.StackExchangeRedis.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.StackExchangeRedis?branch=master
  M:Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.#ctor(Microsoft.Extensions.Options.IOptions{Microsoft.Extensions.Caching.StackExchangeRedis.RedisCacheOptions}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.StackExchangeRedis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.-ctor?branch=master
  T:Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.StackExchangeRedis/RedisCache.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache?branch=master
  M:Microsoft.Extensions.Caching.StackExchangeRedis.RedisCacheOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Caching.StackExchangeRedis/RedisCacheOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Caching.StackExchangeRedis.RedisCacheOptions.-ctor?branch=master

</details>

Note: Some of the APIs are obsolete, so I'll let area owners decide if they want to still document them or skip them. If you opt for documenting them, please do it directly in dotnet-api-docs.

**Comment by maryamariyan** [comment]
Some of the debt mentioned here 

- Microsoft.Extensions.Caching.Redis
- Microsoft.Extensions.Caching.SqlServer
- Microsoft.Extensions.Caching.StackExchangeRedis

do not have APIs sourced in dotnet/runtime and some APIs are dead and out of support. There does not seem like there is much work left to do here.

@carlossanlop I think this issue can be closed.

**Comment by adamsitnik** [comment]
Based on https://github.com/dotnet/runtime/issues/43868#issuecomment-1292367703 I think we should close it.
