### ISSUE TITLE
Convert MonoVM Samples into Functional Tests

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#43865]
The mono [samples](https://github.com/dotnet/runtime/tree/master/src/mono/netcore/sample) do a good job of showing off the platforms we support and often serve as a mini test bed.  Unfortunately, they have a tendency to break over time and sometimes we'll be slow to realize it.  To combat that, we should convert the samples into functional tests.  

We will want to:
- [x] Ensure we build them as part of the build
- [x] Make sure the functional tests are run on CI
- [x] Each test should have a return code for pass/fail 
- [ ] Set default features flags to match to SDK defaults
	- [x] [Blazor](
https://github.com/dotnet/aspnetcore/blob/219ecd6880120215137f4d6ef0dd2aa62c780af2/src/Components/WebAssembly/Sdk/src/targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets#L58-L63)
	- [x] Android
	- [ ] iOS
- [ ] Extract tests into individual test cases for
	- [ ] iOS device (arm64)
		- [ ] Interpreter only
		- [ ] AOT only
		- [ ] PInvoke tests
		- [ ] Invariant culture only mode
	- [x] iOS simulator (x64 & arm64)
		- [x] Interpreter only
		- [x] AOT only
		- [x] PInvoke tests
		- [x] Invariant culture only mode
	- [x] tvOS device (arm64)
		- [x] Interpreter only
		- [x] AOT only
		- [x] PInvoke tests
	- [x] tvOS simulator (x64 & arm64)
		- [x] Interpreter only
		- [x] AOT only
		- [x] PInvoke tests     
	- [x] Android device+simulator
		- [x] Interpreter
		- [x] JIT
		- [x] AOT
		- [x] PInvoke
		- [x] Invariant culture only mode
	- [x] WebAssembly Console
		- [x] Normal interp 
		- [x] AOT
		- [x]  PInvoke
	- [ ] WebAssembly Browser
		- [x]  Normal interp
		- [x]  AOT
		- [ ]  PInvoke
		- [ ] Invariant culture only mode

#### Integrate w/ XHarness 
- [x] iOS
- [x] Android
- [x] Wasm

**Comment by MaximLipnin** [comment]
> Add integration tests for pinvokes for all configurations

@marek-safar Could you please clarify or give some example of what in particular should be done here?

**Comment by marek-safar** [comment]
@MaximLipnin we need tests for each configuration where the test calls unmanaged code via pinvoke. Something like

```c#
class C
{
	[DllImport ("somelib.dll")]
	static void ExternalNativeAPI ();

	public static void Main ()
	{
		int result = ExternalNativeAPI ();
		// check result
	}
}
```

**Comment by steveisok** [comment]
@MaximLipnin Please arrange the functional tests similar to how the tasks are listed in this issue.  

Also, with respect to `Set default features flags to match to SDK defaults`, you're going to need to look at how XA/XI initially set up their configuration.  For example, we want to mirror as much as possible the AOT arguments in XA https://github.com/xamarin/xamarin-android/pull/5539 .  It will require some digging.

**Comment by radical** [comment]
Heads up: Once https://github.com/dotnet/runtime/pull/47683 is merged, you might want to add these test projects as xunit tests.

**Comment by radical** [comment]
FYI, for wasm, we have tests for using native libraries, and for invariant culture mode, in `Wasm.Build.Tests`.

**Comment by mdh1418** [comment]
@steveisok it sounds like the mono samples in this repo are still useful, do we still want to extract tests for iOS device? Either way it seems like this can either be closed or pushed to 8
