### ISSUE TITLE
API documentation debt - Microsoft.Extensions.Configuration

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43869]
Area owners: @maryamariyan @safern

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>Microsoft.Extensions.Configuration</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration?branch=master
  M:Microsoft.Extensions.Configuration.BinderOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/BinderOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.BinderOptions.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.ChainedConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ChainedConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ChainedConfigurationSource.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationBuilder.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationBuilder.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationExtensions.Add\`\`1<br />(Microsoft.Extensions.Configuration.IConfigurationBuilder,System.Action{\`\`0}) | Present | Present | Missing | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationExtensions.Add?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets<br />(Microsoft.Extensions.Configuration.IConfigurationBuilder) | Present | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets<br />(Microsoft.Extensions.Configuration.IConfigurationBuilder,System.Reflection.Assembly) | Present | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets<br />(Microsoft.Extensions.Configuration.IConfigurationBuilder,System.String) | Present | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets\`\`1<br />(Microsoft.Extensions.Configuration.IConfigurationBuilder) | Present | Missing | Present | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationExtensions.Exists<br />(Microsoft.Extensions.Configuration.IConfigurationSection) | Present | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationExtensions.Exists?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationKeyComparer.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationKeyComparer.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationKeyComparer.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationReloadToken.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationReloadToken.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationReloadToken.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.ConfigurationRootExtensions.GetDebugView<br />(Microsoft.Extensions.Configuration.IConfigurationRoot) | Present | Missing | NA | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/ConfigurationRootExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.ConfigurationRootExtensions.GetDebugView?branch=master
  M:Microsoft.Extensions.Configuration.FileConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/FileConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.FileConfigurationSource.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.FileLoadExceptionContext.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/FileLoadExceptionContext.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.FileLoadExceptionContext.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.StreamConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration/StreamConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.StreamConfigurationSource.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.CommandLine</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.CommandLine namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.CommandLine.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.CommandLine?branch=master
  M:Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.CommandLine/CommandLineConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationSource.-ctor?branch=master
  Microsoft.Extensions.Configuration.CommandLine EnvironmentVariables | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.EnvironmentVariables.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.EnvironmentVariables?branch=master
  M:Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.Ini</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.Ini namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.Ini.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Ini?branch=master
  M:Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Ini/IniConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Ini.IniConfigurationSource.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.Ini.IniStreamConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Ini/IniStreamConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Ini.IniStreamConfigurationSource.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.Json</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.Json namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.Json.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Json?branch=master
  M:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Json/JsonConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Json/JsonStreamConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.Memory</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.Memory namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.Memory.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Memory?branch=master
  M:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Memory/MemoryConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.NewtonsoftJson</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.NewtonsoftJson namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.NewtonsoftJson.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.NewtonsoftJson?branch=master
  M:Microsoft.Extensions.Configuration.NewtonsoftJson.NewtonsoftJsonConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.NewtonsoftJson/NewtonsoftJsonConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.NewtonsoftJson.NewtonsoftJsonConfigurationSource.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.NewtonsoftJson.NewtonsoftJsonStreamConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.NewtonsoftJson/NewtonsoftJsonStreamConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.NewtonsoftJson.NewtonsoftJsonStreamConfigurationSource.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.UserSecrets</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.UserSecrets namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.UserSecrets.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.UserSecrets?branch=master
  M:Microsoft.Extensions.Configuration.UserSecrets.PathHelper.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.UserSecrets/PathHelper.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.UserSecrets.PathHelper.-ctor?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Configuration.Xml</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Configuration.Xml namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Configuration.Xml.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Xml?branch=master
  M:Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Xml/XmlConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Xml.XmlConfigurationSource.-ctor?branch=master
  M:Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor.CreateDecryptingXmlReader(System.IO.Stream,System.Xml.XmlReaderSettings) | Present | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Xml/XmlDocumentDecryptor.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor.CreateDecryptingXmlReader?branch=master
  M:Microsoft.Extensions.Configuration.Xml.XmlStreamConfigurationSource.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Configuration.Xml/XmlStreamConfigurationSource.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Configuration.Xml.XmlStreamConfigurationSource.-ctor?branch=master

</details>

Notes:
- The namespaces need to be documented directly in dotnet-api-docs.
- Some of the APIs are obsolete, so I'll let area owners decide if they want to still document them or skip them. If you opt for documenting them, please do it directly in dotnet-api-docs.

**Comment by maryamariyan** [comment]
I did a quick skim over dotnet/runtime repo for

- `Microsoft.Extensions.Configuration` 
- `Microsoft.Extensions.Configuration.CommandLine`
- `Microsoft.Extensions.Configuration.Ini`
- `Microsoft.Extensions.Configuration.Json`
- `Microsoft.Extensions.Configuration.Memory`

and noticed no change is needed here. All listed APIs already have xml docs in the source code.

The default ctors maybe are just missing in the dotnet-api-docs repo itself. No action needed on dotnet/runtime repo side.

Also note, `Microsoft.Extensions.Configuration.NewtonsoftJson` source code does not live in dotnet/runtime.

**Comment by maryamariyan** [comment]
Thanks @KalleOlaviNiemitalo. This issue tracks APIs with no documentation on them.

I added issue dotnet/dotnet-api-docs#8549 to track your feedback,
