### ISSUE TITLE
API documentation debt - System.Security

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43861]
Area owners: @bartonjs @GrabYourPitchforks @krwq

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>System.Security</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue
  -- | -- | -- | -- | --
  P:System.Security.Cryptography.Rfc2898DeriveBytes.HashAlgorithm | Missing | NA | NA | NA
  M:System.Security.Cryptography.RSA.TrySignHash<br />(System.ReadOnlySpan{System.Byte},System.Span{System.Byte},System.Security.Cryptography.HashAlgorithmName,<br />System.Security.Cryptography.RSASignaturePadding,System.Int32@) | Present | Missing | NA | Present
  P:System.Security.Cryptography.TripleDESCng.LegalKeySizes | Missing | NA | NA | NA
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampToken.VerifySignatureForHash<br />(System.ReadOnlySpan{System.Byte},System.Security.Cryptography.Oid,<br />System.Security.Cryptography.X509Certificates.X509Certificate2@,<br />System.Security.Cryptography.X509Certificates.X509Certificate2Collection) | Present | Missing | NA | Present
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.#ctor<br />(System.Security.Cryptography.Oid,System.Security.Cryptography.Oid,System.ReadOnlyMemory{System.Byte},<br />System.ReadOnlyMemory{System.Byte},System.DateTimeOffset,System.Nullable{System.Int64},System.Boolean,<br />System.Nullable{System.ReadOnlyMemory{System.Byte}},System.Nullable{System.ReadOnlyMemory{System.Byte}},<br />System.Security.Cryptography.X509Certificates.X509ExtensionCollection) | Missing | Missing | NA | NA
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.AccuracyInMicroseconds | Missing | NA | NA | NA
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Encode | Missing | NA | NA | Missing
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetExtensions | Missing | NA | NA | Missing
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetMessageHash | Missing | NA | NA | Missing
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetNonce | Missing | NA | NA | Missing
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetSerialNumber | Missing | NA | NA | Missing
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetTimestampAuthorityName | Missing | NA | NA | Missing
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.HasExtensions | Missing | NA | NA | NA
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.HashAlgorithmId | Missing | NA | NA | NA
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.IsOrdering | Missing | NA | NA | NA
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.PolicyId | Missing | NA | NA | NA
  T:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo | Missing | NA | NA | NA
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Timestamp | Missing | NA | NA | NA
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.TryDecode<br />(System.ReadOnlyMemory{System.Byte},System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo@,System.Int32@) | Missing | Missing | NA | Missing
  M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.TryEncode(System.Span{System.Byte},System.Int32@) | Missing | Missing | NA | Missing
  P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Version | Missing | NA | NA | NA
  M:System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.#ctor | Missing | NA | NA | NA
  M:System.Security.Permissions.KeyContainerPermissionAccessEntryEnumerator.#ctor | Missing | NA | NA | NA

</details>

**Comment by vcsjones** [comment]
I guess just to ask, some of these look like they already have documentation on the docs site.

> System.Security.Cryptography.RSA.TrySignHash
(System.ReadOnlySpan{System.Byte},System.Span{System.Byte},System.Security.Cryptography.HashAlgorithmName,
System.Security.Cryptography.RSASignaturePadding,System.Int32@)

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.trysignhash?view=netcore-3.1

Looks like that one and a few others are documented correctly, including the parameters.

Assuming the API is properly documented, I assume we don't want to document them again with XML comments?

**Comment by carlossanlop** [comment]
@vcsjones that API hasn't been fully documented. That API is [missing a description in the "destination" parameter](https://github.com/dotnet/dotnet-api-docs/blob/43f01845379caf9f4241c16e4d2213fe08221cfd/xml/System.Security.Cryptography/RSA.xml#L2301): It has the default boilerplate text "To be added", which needs to be changed.

**Comment by vcsjones** [comment]
> "destination" parameter: It has the default boilerplate text "To be added", which needs to be changed.

Doh! I glossed over that one. Thanks.

**Comment by krwq** [comment]
I believe this is complete now since both PRs are merged.
