### ISSUE TITLE
Feature Request:  Consider passing MemberInfo to the CanConvert method of JsonConverter.

### ISSUE THREAD

**Issue by maliming** [dotnet/runtime#43876]
In this way, we can get more info about the type.

```cs
public abstract bool CanConvert(Type typeToConvert, MemberInfo? memberInfo) ;
```

https://github.com/dotnet/runtime/blob/dbbce4320af818c07c9574c086cf7053379f6c94/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L150

https://github.com/dotnet/runtime/blob/dbbce4320af818c07c9574c086cf7053379f6c94/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L170

https://github.com/dotnet/runtime/blob/dbbce4320af818c07c9574c086cf7053379f6c94/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L223

https://github.com/dotnet/runtime/blob/650f28f2c841c44b0a247e18a9f983c8619286dc/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverter.cs#L20

**Comment by layomia** [comment]
Related: https://github.com/dotnet/runtime/issues/36785.

**Comment by maliming** [comment]
Thanks @layomia
