### ISSUE TITLE
StreamReader.ReadToEndAsync(Token)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#43881]
## Background and Motivation
It would be nice to be able to cancel a read operation.  Currently ```ReadToEndAsync``` exists but it is not cancelable.

## Proposed API
StreamReader.ReadToEndAsync(CancellationToken token)

**Comment by stephentoub** [comment]
Thanks.  This is covered by https://github.com/dotnet/runtime/issues/20824.
