### ISSUE TITLE
API documentation debt - Microsoft.Extensions.DiagnosticAdapter

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43898]
Area owners: @maryamariyan 

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>Microsoft.Extensions.DiagnosticAdapter</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.DiagnosticAdapter namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.DiagnosticAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter?branch=master
  Microsoft.Extensions.DiagnosticAdapter.Infrastructure namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.DiagnosticAdapter.Infrastructure.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.Infrastructure?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticNameAttribute.#ctor(System.String) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticNameAttribute.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticNameAttribute.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.#ctor(System.Object) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.#ctor<br />(System.Object,System.Func{System.String,System.Boolean}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.#ctor<br />(System.Object,System.Func{System.String,System.Boolean},<br />Microsoft.Extensions.DiagnosticAdapter.IDiagnosticSourceMethodAdapter) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.#ctor<br />(System.Object,System.Func{System.String,System.Object,System.Object,System.Boolean}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.#ctor<br />(System.Object,System.Func{System.String,System.Object,System.Object,System.Boolean},<br />Microsoft.Extensions.DiagnosticAdapter.IDiagnosticSourceMethodAdapter) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.IsEnabled(System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.IsEnabled?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.IsEnabled<br />(System.String,System.Object,System.Object) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.IsEnabled?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write<br />(System.String,System.Object) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.IDiagnosticSourceMethodAdapter.Adapt<br />(System.Reflection.MethodInfo,System.Type) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/IDiagnosticSourceMethodAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.IDiagnosticSourceMethodAdapter.Adapt?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/ProxyDiagnosticSourceMethodAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.-ctor?branch=master
  M:Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.Adapt<br />(System.Reflection.MethodInfo,System.Type) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/ProxyDiagnosticSourceMethodAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.Adapt?branch=master
  P:Microsoft.Extensions.DiagnosticAdapter.DiagnosticNameAttribute.Name | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticNameAttribute.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticNameAttribute.Name?branch=master
  T:Microsoft.Extensions.DiagnosticAdapter.DiagnosticNameAttribute | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticNameAttribute.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticNameAttribute?branch=master
  T:Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter?branch=master
  T:Microsoft.Extensions.DiagnosticAdapter.IDiagnosticSourceMethodAdapter | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/IDiagnosticSourceMethodAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.IDiagnosticSourceMethodAdapter?branch=master
  T:Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.DiagnosticAdapter/ProxyDiagnosticSourceMethodAdapter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter?branch=master

</details>

Notes:

- The namespaces need to be documented directly in dotnet-api-docs.
- Some of the APIs are obsolete, so I'll let area owners decide if they want to still document them or skip them. If you opt for documenting them, please do it directly in dotnet-api-docs.

**Comment by maryamariyan** [comment]
In [dotnet/extensions/README.md](https://github.com/dotnet/extensions/blob/master/README.md) is listed as no longer shipping for 5.0

**Comment by buyaa-n** [comment]
> In dotnet/extensions/README.md is listed as no longer shipping for 5.0

@maryamariyan is that meant this issue can be closed? Why did you remove `area-Microsoft.Extensions` if looks should be in that area no in Meta

**Comment by jerviscui** [comment]
How about Microsoft.Extensions.DiagnosticAdapter? 
Obsolescence or No longer update?

**Comment by danmoseley** [comment]
@jerviscui per https://github.com/aspnet/Announcements/issues/411, that component is no longer being updated.

**Comment by jerviscui** [comment]
@danmoseley Thanks, I see it.
Do I give up using Diagnostic？
Change to EventCounter or System.Diagnostics.Metrics？

**Comment by danmoseley** [comment]
@maryamariyan  can you advise?

**Comment by xakep139** [comment]
> @maryamariyan can you advise?

Kind ping here. What's the destiny of `Microsoft.Extensions.DiagnosticAdapter` package?
