### ISSUE TITLE
Dotnet installer does not check macOS version compatibility

### ISSUE THREAD

**Issue by JusteRaimbault** [dotnet/runtime#439]
The OS version is not checked for support by the Dotnet installer (at least on OSX): I could install 3.0 on OSX 12 although it requires OSX13+ (higher supported version for OSX12 is Dotnet 2.2); it obviously failed at runtime later. It may be better to prevent installing if there is no compatibility.

**Comment by NikolaMilosavljevic** [comment]
Should be declared in centralized location and not siloed in installer space.

**Comment by NikolaMilosavljevic** [comment]
Fix has been merged with https://github.com/dotnet/runtime/pull/33306
