### ISSUE TITLE
Why does ILCompiler.TypeSystem.ReadyToRun (crossgen2) use Microsoft.DiaSymReader 1.3.0?

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#43904]
Over in dotnet/source-build, it seems we have to add the [dotnet/symreader](https://github.com/dotnet/symreader) repo (https://github.com/dotnet/source-build/issues/1812) to build this dependency from source:

https://github.com/dotnet/runtime/blob/ae9da6432360728c77ab10b1ef0c414d1a9ee287/src/coreclr/src/tools/aot/ILCompiler.TypeSystem.ReadyToRun/ILCompiler.TypeSystem.ReadyToRun.csproj#L33-L35

Why is crossgen2 (transitively) taking this dependency? The readme of dotnet/symreader says:

> It is recommended that new applications and libraries read Portable PDBs directly using APIs provided by System.Reflection.Metadata package. These APIs are much more efficient than DiaSymReader APIs.

This package is old (2018/6/11), so the infra to build it is stale, but that's just an issue on the source-build side where prebuilt dependencies are not allowed.

I don't think it's a problem to patch up the infra and start building this repo from source-build again, but we'd like to know more about this dependency if possible.

/cc @dleeapho @dseefeld @crummel 

(Historical note: we actually were able to remove dotnet/symreader from source-build back in 2.1 because it wasn't being used: https://github.com/dotnet/source-build/pull/518. 3.1 now doesn't use it. So the repo "coming back" in 5.0 seems like a big red flag, even if it might not be.)

**Comment by MichalStrehovsky** [comment]
The package defines COM interfaces to read oldstyle debug symbols (System.Reflection.Metadata doesn't support that format).

This only works on Windows because it's a call into desktop CLR. We could just choose to say that non-portable debug information is not supported. I'm not even sure crossgen2 actually consumes debug symbols in the first place - it sounds like it should, but I can't seem to find actual calls into this code so maybe it can all be just ifdeffed out.

Cc @dotnet/crossgen-contrib

**Comment by dagood** [comment]
Thanks. I think that makes sense until:

> maybe it can all be just ifdeffed out.

I don't understand why it would be ifdeffed rather than just deleted. In what cases would the code still be intentionally included (and therefore still require the `<PackageReference Include="Microsoft.DiaSymReader">`)?

**Comment by MichalStrehovsky** [comment]
> I don't understand why it would be ifdeffed rather than just deleted

The code is actually used in a feature branch so deleting it would just cause unnecessary churn and `git blame` history mess. The PackageReference can be deleted without replacement if the ifdeffing happens - the `ILCompiler.TypeSystem.ReadyToRun` project is not relevant to the feature branch, only the source files are shared.

(The `#if READYTORUN` ifdef is what I'm alluding to - we already have those for this purpose.)

**Comment by dagood** [comment]
Ah, that makes sense then, thanks. 😄 

I merged the PR this morning to add symreader to 5.0 source-build, so we don't need to do anything extra right now to get rid of a prebuilt. But, the source-build team has to basically maintain fresh Arcade infra on top of the old 1.3.0 symreader commit, so it would be good to remove this dependency at some point to get rid of that maintenance cost.

**Comment by trylek** [comment]
Interestingly enough I just hit something similar in my attempt to generalize crossgenning System.Private.CoreLib to support Crossgen2: in the existing code using the legacy Crossgen as the compiler, we call <code>setup_vs_tools</code> on Windows for the sole reason that Crossgen can grab <code>Microsoft.DiaSymReader.Native.amd64.dll</code> from the ambient VS installation.

I would love to figure out a cleaner way to approach this; the dependency on DiaSymReader will likely need to remain for the time being as it's the only way to process the legacy Windows PDB's that C# compilers still support emitting. (I must admit I haven't studied this aspect of Crossgen1 in that much detail so I'm not 100% clear on all ways it uses the library).

One of our planned tasks for the global switchover from Crossgen1 to Crossgen2 is adding support for generating Windows PDB symbolic information that's required for PerfInfo functionality directly to Crossgen2; at this point an implementation of this emitter exists in the R2RDump utility, IIRC according to @davidwrighton who implemented this we're also using some custom code for emitting the Windows PDB's; that will also become a requirement for the product graph on Windows.

Related issue: https://github.com/dotnet/runtime/issues/43810

**Comment by dagood** [comment]
Interesting. One thing I should point out is that source-build doesn't support Windows at all right now, and there's no desire AFAIK for a *prebuiltless* Windows build even if we did support building on Windows. A Linux-specific condition/ifdef would be enough to let us remove symreader from the source-build infra.

**Comment by mangod9** [comment]
Is this still an issue now that cg2 supports pdb generation?

**Comment by dleeapho** [comment]
cc @MichaelSimons @dseefeld

**Comment by davidwrighton** [comment]
The diasymreader is the binary used to produce Windows native pdbs, for use as an ngen pdb. So, this dependency still remains. However, I would welcome a patch which disabled its use in source build scenarios, as we're certainly not using it on Linux. (I would also approve a patch which built the minimal pdb writer used for ngen pdbs in C# to avoid this dependency entirely, but that's not a small project.)
