### ISSUE TITLE
API documentation debt - Microsoft.Extensions.Http

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43916]
Area owners: @dotnet/ncl 

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>Microsoft.Extensions.Http</summary>

PR | DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
-- | -- | -- | -- | -- | -- | -- | --
PR https://github.com/dotnet/dotnet-api-docs/pull/7110 | Microsoft.Extensions.Http namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Http.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http?branch=master
PR https://github.com/dotnet/dotnet-api-docs/pull/7110 | M:Microsoft.Extensions.Http.HttpClientFactoryOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http/HttpClientFactoryOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.HttpClientFactoryOptions.-ctor?branch=master
PR https://github.com/dotnet/dotnet-api-docs/pull/7110 | M:Microsoft.Extensions.Http.HttpMessageHandlerBuilder.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http/HttpMessageHandlerBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.HttpMessageHandlerBuilder.-ctor?branch=master
PR #57719 | M:Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline<br />(System.Net.Http.HttpMessageHandler,System.Collections.Generic.IEnumerable{System.Net.Http.DelegatingHandler}) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http/HttpMessageHandlerBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline?branch=master
PR #57719 | M:Microsoft.Extensions.Http.IHttpMessageHandlerBuilderFilter.Configure<br />(System.Action{Microsoft.Extensions.Http.HttpMessageHandlerBuilder}) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http/IHttpMessageHandlerBuilderFilter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.IHttpMessageHandlerBuilderFilter.Configure?branch=master
PR https://github.com/dotnet/dotnet-api-docs/pull/7110 | M:Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync<br />(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http/PolicyHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Http.Logging</summary>

PR | DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
-- | -- | -- | -- | -- | -- | -- | --
PR https://github.com/dotnet/dotnet-api-docs/pull/7110 | Microsoft.Extensions.Http.Logging namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Http.Logging.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging?branch=master
PR #57719 | M:Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.#ctor(Microsoft.Extensions.Logging.ILogger) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.-ctor?branch=master
PR #57719 |  M:Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.#ctor<br />(Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Http.HttpClientFactoryOptions) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.-ctor?branch=master
PR #57719 | M:Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync<br />(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync?branch=master
PR #57719 | M:Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.#ctor(Microsoft.Extensions.Logging.ILogger) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingScopeHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.-ctor?branch=master
PR #57719 | M:Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.#ctor<br />(Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Http.HttpClientFactoryOptions) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingScopeHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.-ctor?branch=master
PR #57719 | M:Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync<br />(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingScopeHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync?branch=master
PR #57719 | T:Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler?branch=master
PR #57719 | T:Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Http.Logging/LoggingScopeHttpMessageHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler?branch=master

</details>

Notes:

- The namespaces need to be documented directly in dotnet-api-docs.
- Some of the APIs may be obsolete, so I'll let area owners decide if they want to still document them or skip them. If you opt for documenting them, please do it directly in dotnet-api-docs.

**Comment by karelz** [comment]
Items not addressed by PR #57719:

Item | Notes
-- | --
Microsoft.Extensions.Http namespace | This has to be documented directly in dotnet-api-docs.
M:Microsoft.Extensions.Http.HttpClientFactoryOptions.#ctor | ctor is inferred; does not exist in code; also document directly in dotnet-api-docs? Uncertain.
M:Microsoft.Extensions.Http.HttpMessageHandlerBuilder.#ctor | ctor is inferred; does not exist in code; also document directly in dotnet-api-docs? Uncertain.
M:Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync<br/>(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken) | Could not find class/method to add documentation to? Possibly removed?
Microsoft.Extensions.Http.Logging namespace | This has to be documented directly in dotnet-api-docs.

**Comment by CarnaViire** [comment]
Fixed by dotnet/dotnet-api-docs#7103 and dotnet/dotnet-api-docs#7110
