### ISSUE TITLE
API documentation debt - Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43915]
Area owners: 

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>Microsoft.Extensions.Hosting</summary>
  
  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Hosting namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Hosting.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting?branch=master
  T:Microsoft.Extensions.Hosting.ConsoleLifetimeOptions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/ConsoleLifetimeOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.ConsoleLifetimeOptions?branch=master
  T:Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostingAbstractionsHostBuilderExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions?branch=master
  T:Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostingAbstractionsHostExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions?branch=master
  T:Microsoft.Extensions.Hosting.HostingHostBuilderExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostingHostBuilderExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostingHostBuilderExtensions?branch=master
  M:Microsoft.Extensions.Hosting.BackgroundService.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/BackgroundService.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.BackgroundService.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.ConsoleLifetimeOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/ConsoleLifetimeOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.ConsoleLifetimeOptions.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.HostBuilder.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostBuilder.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.HostBuilderContext.#ctor(System.Collections.Generic.IDictionary{System.Object,System.Object}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostBuilderContext.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostBuilderContext.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.HostOptions.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostOptions.-ctor?branch=master
  F:Microsoft.Extensions.Hosting.EnvironmentName.Development | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/EnvironmentName.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.EnvironmentName.Development?branch=master
  F:Microsoft.Extensions.Hosting.EnvironmentName.Production | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/EnvironmentName.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.EnvironmentName.Production?branch=master
  F:Microsoft.Extensions.Hosting.EnvironmentName.Staging | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/EnvironmentName.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.EnvironmentName.Staging?branch=master
  F:Microsoft.Extensions.Hosting.Environments.Development | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/Environments.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Environments.Development?branch=master
  F:Microsoft.Extensions.Hosting.Environments.Production | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/Environments.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Environments.Production?branch=master
  F:Microsoft.Extensions.Hosting.Environments.Staging | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/Environments.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Environments.Staging?branch=master
  T:Microsoft.Extensions.Hosting.IHostLifetime | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/IHostLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.IHostLifetime?branch=master
  M:Microsoft.Extensions.Hosting.BackgroundService.StartAsync<br />(System.Threading.CancellationToken) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/BackgroundService.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.BackgroundService.StartAsync?branch=master
  M:Microsoft.Extensions.Hosting.BackgroundService.StopAsync<br />(System.Threading.CancellationToken) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/BackgroundService.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.BackgroundService.StopAsync?branch=master
  M:Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureContainer\`\`1<br />(Microsoft.Extensions.Hosting.IHostBuilder,System.Action{\`\`0}) | Present | Present | Missing | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostingHostBuilderExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureContainer?branch=master
  M:Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseDefaultServiceProvider<br />(Microsoft.Extensions.Hosting.IHostBuilder,<br />System.Action{Microsoft.Extensions.DependencyInjection.ServiceProviderOptions}) | Present | Missing | NA | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/HostingHostBuilderExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseDefaultServiceProvider?branch=master
  M:Microsoft.Extensions.Hosting.IHostBuilder.UseServiceProviderFactory\`\`1<br />(System.Func{Microsoft.Extensions.Hosting.HostBuilderContext,<br />Microsoft.Extensions.DependencyInjection.IServiceProviderFactory{\`\`0}}) | Present | Missing | Present | Present | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/IHostBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.IHostBuilder.UseServiceProviderFactory?branch=master
  M:Microsoft.Extensions.Hosting.IHostedService.StartAsync(System.Threading.CancellationToken) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/IHostedService.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.IHostedService.StartAsync?branch=master
  M:Microsoft.Extensions.Hosting.IHostedService.StopAsync(System.Threading.CancellationToken) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/IHostedService.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.IHostedService.StopAsync?branch=master
  M:Microsoft.Extensions.Hosting.SystemdHostBuilderExtensions.UseSystemd(Microsoft.Extensions.Hosting.IHostBuilder) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting/SystemdHostBuilderExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.SystemdHostBuilderExtensions.UseSystemd?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Hosting.Systemd</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Hosting.Systemd namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Hosting.Systemd.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd?branch=master
  T:Microsoft.Extensions.Hosting.Systemd.SystemdLifetime | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/SystemdLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.SystemdLifetime?branch=master
  T:Microsoft.Extensions.Hosting.Systemd.SystemdNotifier | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/SystemdNotifier.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.SystemdNotifier?branch=master
  M:Microsoft.Extensions.Hosting.Systemd.ServiceState.#ctor(System.String) | UnderDoc | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/ServiceState.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.ServiceState.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.Systemd.SystemdLifetime.#ctor<br />(Microsoft.Extensions.Hosting.IHostEnvironment,Microsoft.Extensions.Hosting.IHostApplicationLifetime,<br />Microsoft.Extensions.Hosting.Systemd.ISystemdNotifier,Microsoft.Extensions.Logging.ILoggerFactory) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/SystemdLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.SystemdLifetime.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.Systemd.SystemdNotifier.#ctor | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/SystemdNotifier.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.SystemdNotifier.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.Systemd.ISystemdNotifier.Notify<br />(Microsoft.Extensions.Hosting.Systemd.ServiceState) | Present | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/ISystemdNotifier.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.ISystemdNotifier.Notify?branch=master
  M:Microsoft.Extensions.Hosting.Systemd.ServiceState.ToString | Present | NA | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.Systemd/ServiceState.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.Systemd.ServiceState.ToString?branch=master

</details>

<details>
  <summary>Microsoft.Extensions.Hosting.WindowsServices</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Hosting.WindowsServices namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Hosting.WindowsServices.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.WindowsServices?branch=master
  T:Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.WindowsServices/WindowsServiceLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime?branch=master
  M:Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.#ctor<br />(Microsoft.Extensions.Hosting.IHostEnvironment,Microsoft.Extensions.Hosting.IHostApplicationLifetime,<br />Microsoft.Extensions.Logging.ILoggerFactory,Microsoft.Extensions.Options.IOptions{Microsoft.Extensions.Hosting.HostOptions}) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.WindowsServices/WindowsServiceLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.-ctor?branch=master
  M:Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.Dispose(System.Boolean) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.WindowsServices/WindowsServiceLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.Dispose?branch=master
  M:Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.OnStart(System.String[]) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.WindowsServices/WindowsServiceLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.OnStart?branch=master
  M:Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.OnStop | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Hosting.WindowsServices/WindowsServiceLifetime.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.OnStop?branch=master

</details>

Notes:

- The namespaces need to be documented directly in dotnet-api-docs.
- Some of the APIs are obsolete, so I'll let area owners decide if they want to still document them or skip them. If you opt for documenting them, please do it directly in dotnet-api-docs.

**Comment by Nick-Stanton** [comment]
Reopening while #76692 is in review
