### ISSUE TITLE
A better way to PInvoke nullable pointers?

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#4392]
It's fairly common, when working with PInvoke, to have a function that takes a `MyStruct*` as an argument.  This isn't too difficult to work with; just define it on the managed side as `ref MyStruct`.

...right up until your native function also accepts `NULL` as valid input.  Trying to call it this way won't work, because `NULL` is not assignment-compatible to a struct, and so you end up having to write an overload in your PInvoke header class that replaces it with an `IntPtr`, so that you can specifically pass `IntPtr.Zero`.  And heaven help you if this function takes multiple struct pointers; you can end up with a combinatorial explosion of overloads very quickly!

A much better solution would be to create a `System.Runtime.InteropServices.NullableRefAttribute` that can be placed on an argument, which tells the compiler that it's valid to pass `NULL` here.  It would only be valid to place `NullableRefAttribute` on a `ref` argument on a method that's tagged with `DllImport` (or [whatever equivalent we end up using](https://github.com/dotnet/coreclr/issues/930)).

Obviously something like this would need to be implemented on the Roslyn side of things, but I'm raising it here first to ask people familiar with the CLR if it would require any changes to the runtime in order to support it?  For example, is there any way that code that takes advantage of this might fail to verify, which would then require changes to the verifier?

**Comment by jkotas** [comment]
> You can get a managed value type reference to null using ref Unsafe.AsRef<T>(null). It'll be marshaled as a null pointer as expected.

We have even better shortcut for this now: `Unsafe.NullRef<T>()` that should be good enough to address the scenario. Note that it will work for blittable structures only.
