### ISSUE TITLE
API documentation debt - Microsoft.Extensions.Primitives

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43920]
Area owners: @maryamariyan @eerhardt 

The APIs in the list below are missing some or all of their documentation. Please add the missing documentation directly in triple slash comments in source. We will make sure it gets ported to dotnet-api-docs after it's merged.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>Microsoft.Extensions.Primitives</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  Microsoft.Extensions.Primitives namespace | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-Microsoft.Extensions.Primitives.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives?branch=master
  M:Microsoft.Extensions.Primitives.ChangeToken.OnChange<br />(System.Func{Microsoft.Extensions.Primitives.IChangeToken},System.Action) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/ChangeToken.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.ChangeToken.OnChange?branch=master
  M:Microsoft.Extensions.Primitives.ChangeToken.OnChange\`\`1<br />(System.Func{Microsoft.Extensions.Primitives.IChangeToken},System.Action{\`\`0},\`\`0) | Present | Present | Present | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/ChangeToken.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.ChangeToken.OnChange?branch=master
  T:Microsoft.Extensions.Primitives.Extensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/Extensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.Extensions?branch=master
  M:Microsoft.Extensions.Primitives.InplaceStringBuilder.#ctor(System.Int32) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.-ctor?branch=master
  M:Microsoft.Extensions.Primitives.InplaceStringBuilder.Append<br />(Microsoft.Extensions.Primitives.StringSegment) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.Append?branch=master
  M:Microsoft.Extensions.Primitives.InplaceStringBuilder.Append(System.Char) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.Append?branch=master
  M:Microsoft.Extensions.Primitives.InplaceStringBuilder.Append(System.String) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.Append?branch=master
  M:Microsoft.Extensions.Primitives.InplaceStringBuilder.Append<br />(System.String,System.Int32,System.Int32) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.Append?branch=master
  P:Microsoft.Extensions.Primitives.InplaceStringBuilder.Capacity | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.Capacity?branch=master
  T:Microsoft.Extensions.Primitives.InplaceStringBuilder | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder?branch=master
  M:Microsoft.Extensions.Primitives.InplaceStringBuilder.ToString | Missing | NA | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/InplaceStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.InplaceStringBuilder.ToString?branch=master
  M:Microsoft.Extensions.Primitives.StringSegment.Equals(System.Object) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegment.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegment.Equals?branch=master
  M:Microsoft.Extensions.Primitives.StringSegment.GetHashCode | Missing | NA | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegment.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegment.GetHashCode?branch=master
  M:Microsoft.Extensions.Primitives.StringSegment.IsNullOrEmpty<br />(Microsoft.Extensions.Primitives.StringSegment) | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegment.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegment.IsNullOrEmpty?branch=master
  M:Microsoft.Extensions.Primitives.StringSegment.op_Implicit<br />(Microsoft.Extensions.Primitives.StringSegment)~System.ReadOnlyMemory{System.Char} | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegment.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegment.op_Implicit?branch=master
  M:Microsoft.Extensions.Primitives.StringSegment.op_Implicit<br />(Microsoft.Extensions.Primitives.StringSegment)~System.ReadOnlySpan{System.Char} | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegment.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegment.op_Implicit?branch=master
  M:Microsoft.Extensions.Primitives.StringSegment.op_Implicit<br />(System.String)~Microsoft.Extensions.Primitives.StringSegment | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegment.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegment.op_Implicit?branch=master
  P:Microsoft.Extensions.Primitives.StringSegmentComparer.Ordinal | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegmentComparer.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegmentComparer.Ordinal?branch=master
  P:Microsoft.Extensions.Primitives.StringSegmentComparer.OrdinalIgnoreCase | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegmentComparer.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegmentComparer.OrdinalIgnoreCase?branch=master
  T:Microsoft.Extensions.Primitives.StringSegmentComparer | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringSegmentComparer.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringSegmentComparer?branch=master
  M:Microsoft.Extensions.Primitives.StringTokenizer.GetEnumerator | Missing | NA | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringTokenizer.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringTokenizer.GetEnumerator?branch=master
  M:Microsoft.Extensions.Primitives.StringTokenizer.Enumerator.#ctor<br />(Microsoft.Extensions.Primitives.StringTokenizer@) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringTokenizer+Enumerator.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringTokenizer.Enumerator.-ctor?branch=master
  T:Microsoft.Extensions.Primitives.StringTokenizer.Enumerator | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringTokenizer+Enumerator.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringTokenizer.Enumerator?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.GetHashCode | Missing | NA | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.GetHashCode?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Equality<br />(Microsoft.Extensions.Primitives.StringValues,System.String) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Equality?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Equality<br />(Microsoft.Extensions.Primitives.StringValues,System.String[]) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Equality?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Equality<br />(System.String,Microsoft.Extensions.Primitives.StringValues) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Equality?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Equality<br />(System.String[],Microsoft.Extensions.Primitives.StringValues) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Equality?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Implicit<br />(Microsoft.Extensions.Primitives.StringValues)~System.String[] | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Implicit?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Implicit<br />(System.String)~Microsoft.Extensions.Primitives.StringValues | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Implicit?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.op_Implicit<br />(System.String[])~Microsoft.Extensions.Primitives.StringValues | Present | Present | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.op_Implicit?branch=master
  M:Microsoft.Extensions.Primitives.StringValues.Enumerator.#ctor<br />(Microsoft.Extensions.Primitives.StringValues@) | Missing | Missing | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Primitives/StringValues+Enumerator.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Extensions.Primitives.StringValues.Enumerator.-ctor?branch=master

</details>

Notes:

- The namespaces need to be documented directly in dotnet-api-docs.
- Some of the APIs are obsolete, so I'll let area owners decide if they want to still document them or skip them. If you opt for documenting them, please do it directly in dotnet-api-docs.

**Comment by Nick-Stanton** [comment]
Above PRs resolve this issue
