### ISSUE TITLE
Test failure: System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43928]
failed in job: [runtime 20201027.54 ](https://dev.azure.com/dnceng/public/_build/results?buildId=868036&view=ms.vss-test-web.build-test-results-tab&runId=27787818&paneView=debug&resultId=112413)

failed tests: 
System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 100)
System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 1000)
System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 1500)

net6.0-Android-Release-arm64-Mono_Release-Windows.10.Amd64.Android.Open

Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(Int32 timeout) in /_/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 40
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
~~~

**Comment by akoeplinger** [comment]
Seems to be the same underlying issue as https://github.com/dotnet/runtime/issues/43927, which is https://github.com/dotnet/core-eng/issues/11290.

**Comment by MaximLipnin** [comment]
> Seems to be the same underlying issue as #43927, which is [dotnet/core-eng#11290](https://github.com/dotnet/core-eng/issues/11290).

The underlying issue has been addressed so we can close it.
