### ISSUE TITLE
Test failure: System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_ExternalHost(justAddresses: False)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43927]
failed in job: [runtime 20201027.54 ](https://dev.azure.com/dnceng/public/_build/results?buildId=868036&view=ms.vss-test-web.build-test-results-tab&runId=27787818&resultId=112329&paneView=debug)

failed tests:
System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_ExternalHost(justAddresses: False)
System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_ExternalHost(justAddresses: True)

net6.0-Android-Release-arm64-Mono_Release-Windows.10.Amd64.Android.Open

Error message
~~~
Assert.Equal() Failure
Expected: Success
Actual:   HostNotFound


Stack trace
   at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_ExternalHost(Boolean justAddresses) in /_/src/libraries/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 157
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
~~~

**Comment by akoeplinger** [comment]
Looks like an infrastructure issue specific to a few machines, filed https://github.com/dotnet/core-eng/issues/11290.

**Comment by ViktorHofer** [comment]
@akoeplinger should we close this issue given that we have the core-eng issue tracking why the machines misbehaved?
