### ISSUE TITLE
API Proposal: Add ConfigurationBinder.Bind<T> overloads

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#43930]
## Background and Motivation

We need to enable annotating liker friendly attributes to be applied to the generic argument to preserve things and to allow source generators to replace the implementation of this method by adding generic overloads specialized to a specific T.

## Proposed API

```diff
namespace Microsoft.Extensions.Configuration
{
    public class ConfigurationBinder 
    {
+        public static void Bind<T>(this IConfiguration configuration, string key, T instance);
+        public static void Bind<T>(this IConfiguration configuration, T instance);
+        public static void Bind<T>(this IConfiguration configuration, T instance, Action<BinderOptions> configureOptions);
    }
```

## Usage Examples

``` C#
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;

var configuration = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string>
    {
        { "Name", "David" }
    })
    .Build();

var p = new Person();
// This will infer the new generic overloads instead of the object overload
configuration.Bind(p);

Console.WriteLine(p.Name);

public class Person
{
    public string Name { get; init; }
}
```

## Risks

None.

PS: These will basically win over the non-generic overloads when the instance isn't typed as object. 

cc @jaredpar to check my compiler math.

**Comment by maryamariyan** [comment]
> cc @jaredpar to check my compiler math.

I believe given the concrete class:

```c#
public class Person
{
    public string Name { get; init; }
}
```
the two overloads below in combination
```c#

// The APIs proposed in this issue. So when source gen is not enabled, config binding would remain linker friendly
public static class ConfigurationBinder
{
    public static void Bind<T>(this IConfiguration configuration, T instance, Action<BinderOptions> configureOptions)
        => configuration.Bind((object)instance, configureOptions);
...
}

// source generated code for the concrete types, with compiler ideally picking this overload rather than ambiguous error
public static class PersonConfigurationExensions
{
enabled.
    public static void Bind<Person>(this IConfiguration configuration, Person instance, Action<BinderOptions> configureOptions)
        => configuration.Bind((object)instance, configureOptions);
...
}
```

would cause ambiguous compile error:
```
The call is ambiguous between the following methods or properties: 'ConfigurationBinder.Bind<T>(IConfiguration, T, Action<BinderOptions>)' and 'PersonConfigurationExensions.Bind<Person>(IConfiguration, Person, Action<BinderOptions>)'
```

@davidfowl would it be enough for configuration binding to be linker friendly only when source generation is enabled? If yes, then perhaps we could skip these proposed API additions (additions drafted [here](https://github.com/maryamariyan/runtime/pull/38/files)) and source gen drafted [here](https://gist.github.com/maryamariyan/41ba5355ba0db450bbb5f429f1bd01b9).

**Comment by davidfowl** [comment]
This works for me:

```C#
// The APIs proposed in this issue. So when source gen is not enabled, config binding would remain linker friendly
public static class ConfigurationBinder
{
    public static void Bind<T>(this IConfiguration configuration, T instance, Action<BinderOptions> configureOptions)
        => configuration.Bind((object)instance, configureOptions);
}

// source generated code for the concrete types, with compiler ideally picking this overload rather than ambiguous error
public static class PersonConfigurationExensions
{
    public static void Bind<T>(this IConfiguration configuration, T instance, Action<BinderOptions> configureOptions) where T : Person
    {
             // Source generated implementation
    }
}
```

**Comment by maryamariyan** [comment]
Thanks, I missed adding the where clause in the code blob above, that is needed. 

What I noticed is that we'd still get the ambiguous error even if the two APIs are in two different namespaces and both are added as using statements. Minimal repro [here](https://gist.github.com/maryamariyan/206065b6dd81ef6f027cf0e8a92d0fb8)

**Comment by jaredpar** [comment]
Yes this should be fine assuming all of the overloads today are non-generic.

**Comment by maryamariyan** [comment]
UPDATE:

#### Note on trimming:
As described in the issue here, we'd still need the three APIs above for enabling linker friendly attributes. 
But from what I understood from @eerhardt, seem like the linker today has limitations (needs additional work) to allow support for properly trimming bind for ComplexOptions below:
```c#
public class ComplexOptions
{
    public int Integer { get; set; }
    public NestedOptions Nested { get; set; }
}
public class NestedOptions
{
    public FurtherNestingOptions FurtherNesting { get; set; }
}
```
Where the linker needs to understand not to trim FurtherNestingOptions in this case.

#### Note on source generation
But seems like for the source gen code, we don't really need to conflict with the above three APIs. Instead we could generate something like:

```c#
        public static void Bind(this IConfiguration configuration, Person instance, Action<BinderOptions> configureOptions)
```
This way we can avoid the ambiguous match compile error.

Also note, 
```

cc: @eerhardt

**Comment by eerhardt** [comment]
> from what I understood from @eerhardt, seem like the linker today would have limitations (and needs additional work) to allow support for properly trimming bind for ComplexOptions below

See https://github.com/mono/linker/issues/1087 for more information on the issue with the linker in this area.

**Comment by davidfowl** [comment]
This is the case with JsonDeserialize as well. We just need to be *able* to annotate things (this should have the same annotations as JSON even if they are not fully capable today) since today we can't even do that because of the object overload.

**Comment by GrabYourPitchforks** [comment]
If this API is approved, consider having the new overloads annotated _where T : class_, or if this is not practical, their implementations should fail if _T_ is a value type. Passing a value type _T_ will end up making a copy, so binding the configuration to that instance will essentially be an expensive no-op, and the user probably didn't intend for this to happen.

**Comment by terrajobst** [comment]
* What are the linker annotations?
* Why do we need generic overloads? If we believe the compiler can always implicitly inferred, then it seems maybe we should able to do this inference by the linker as well. In other words, can we annotate the existing object based overloads? It seems local tracking is something the linker could be doing.
* How many APIs like this do we have in the framework? If it's just a couple, adding generic overloads is fine, but if that's a pervasive pattern, than a change in the linker seems more useful.

```C#
namespace Microsoft.Extensions.Configuration
{
    public partial class ConfigurationBinder
    {
        public static void Bind<T>(this IConfiguration configuration, string key, T instance);
        public static void Bind<T>(this IConfiguration configuration, T instance);
        public static void Bind<T>(this IConfiguration configuration, T instance, Action<BinderOptions> configureOptions);
    }
}
```

**Comment by davidfowl** [comment]
> If this API is approved, consider having the new overloads annotated where T : class, or if this is not practical, their implementations should fail if T is a value type. Passing a value type T will end up making a copy, so binding the configuration to that instance will essentially be an expensive no-op, and the user probably didn't intend for this to happen.

@GrabYourPitchforks great observation!

**Comment by davidfowl** [comment]
Closing this in favor of the new source generator.

cc @layomia @ericstj
