### ISSUE TITLE
Developers can use a built in PriorityQueue type

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#43957]
## Background and Motivation

Adding a priority queue has been a feature [long requested by the community](https://github.com/dotnet/runtime/issues/14032), however so far we've fallen short of finalizing a design, primarily due to a lack of consensus on certain high-level features: namely, the support for priority updates and any API or performance considerations this feature entails.

To better identify what a popular .NET priority queue should look like, I have been going through .NET codebases for common usage patterns as well as running benchmarks against various prototypes. The key takeaway is that _90% of the use cases examined do not require priority updates_. It also turns out that implementations without update support can be 2-3x faster compared to ones that do support it. Please refer to the [original issue](https://github.com/dotnet/runtime/issues/14032#issuecomment-713602751) for more details on my investigations.

This issue presents a finalized priority queue API proposal, informed by the above findings. The goal is to introduce a `PriorityQueue` class that has a simple design, caters to the majority of our users' requirements and is as efficient as possible.

A prototype implementing the proposal can be found [here](https://github.com/eiriktsarpalis/pq-tests/blob/master/PriorityQueue/PriorityQueue.cs).

## Design Decisions

* Class is named `PriorityQueue` instead of `Heap`.
* Implements a min priority queue (element with lowest priority dequeued first).
* Priority ordinals are passed as separate values (rather than being encapsulated by the element).
* Uses an array-backed quaternary heap.
* No support for priority updates.
* Not a thread-safe collection.
* Not a stable queue (elements enqueued with equal priority not guaranteed to be dequeued in the same order).
* The type _does not implement IEnumerable or ICollection_. Unlike `Queue<T>`, PriorityQueue cannot efficiently enumerate elements by ascending priority. We therefore expose the enumerable as a separate `UnorderedItems` property, to more effectively communicate this behaviour.

## Implementation Checklist (Definition of Done)

- [x] Implement product code & high coverage unit tests. (In PR https://github.com/dotnet/runtime/pull/46009)
- [x] Add performance benchmarks (In PR https://github.com/dotnet/performance/pull/1665).
- [x] (Optional) Add property-based tests for randomized testing (see the prototype repo [examples](https://github.com/eiriktsarpalis/pq-tests/blob/89d53de3975fd2ef7bc217c355aadbf5f3356f10/PriorityQueue.Tests/PriorityQueueTests.cs#L48)).
- [x] Add detailed API docs (in the form of triple-slash comments).
    - [ ] Port API docs to the [dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/) repo using the [docs porting tool](https://github.com/carlossanlop/DocsPortingTool).

## Proposed API

```csharp
namespace System.Collections.Generic
{
    public class PriorityQueue<TElement, TPriority> // NB does not implement IEnumerable or ICollection
    {
        /// <summary>
        ///   Creates an empty PriorityQueue instance.
        /// </summary>
        public PriorityQueue();

         /// <summary>
        ///   Creates a PriorityQueue instance with specified initial capacity in its backing array.
        /// </summary>
        public PriorityQueue(int initialCapacity);

        /// <summary>
        ///   Creates a PriorityQueue instance with specified priority comparer.
        /// </summary>
        public PriorityQueue(IComparer<TPriority>? comparer);
        public PriorityQueue(int initialCapacity, IComparer<TPriority>? comparer);

        /// <summary>
        ///   Creates a PriorityQueue populated with the specified values and priorities.
        /// </summary>
        public PriorityQueue(IEnumerable<(TElement Element, TPriority Priority)> values);
        public PriorityQueue(IEnumerable<(TElement Element, TPriority Priority)> values, IComparer<TPriority>? comparer);

        /// <summary>
        ///   Gets the current element count in the queue.
        /// </summary>
        public int Count { get; }

        /// <summary>
        ///   Gets the priority comparer of the queue.
        /// </summary>
        public IComparer<TPriority> Comparer { get; }

        /// <summary>
        ///   Enqueues the element with specified priority.
        /// </summary>
        public void Enqueue(TElement element, TPriority priority);

        /// <summary>
        ///   Gets the element with minimal priority, if it exists.
        /// </summary>
        /// <exception cref="InvalidOperationException">The queue is empty.</exception>
        public TElement Peek();

        /// <summary>
        ///    Dequeues the element with minimal priority, if it exists.
        /// </summary>
        /// <exception cref="InvalidOperationException">The queue is empty.</exception>
        public TElement Dequeue();

        /// <summary>
        ///    Try-variants of Dequeue and Peek methods.
        /// </summary>
        public bool TryDequeue([MaybeNullWhen(false)] out TElement element, [MaybeNullWhen(false)] out TPriority priority);
        public bool TryPeek([MaybeNullWhen(false)] out TElement element, [MaybeNullWhen(false)] out TPriority priority);

        /// <summary>
        ///   Combined enqueue/dequeue operation, generally more efficient than sequential Enqueue/Dequeue calls.
        /// </summary>
        public TElement EnqueueDequeue(TElement element, TPriority priority);

        /// <summary>
        ///   Enqueues a sequence of element/priority pairs to the queue.
        /// </summary>
        public void EnqueueRange(IEnumerable<(TElement Element, TPriority Priority)> values);

        /// <summary>
        ///   Enqueues a sequence of elements with provided priority.
        /// </summary>
        public void EnqueueRange(IEnumerable<TElement> values, TPriority priority);

        /// <summary>
        ///   Removes all objects from the PriorityQueue.
        /// </summary>
        public void Clear();

        /// <summary>
        ///   Ensures that the PriorityQueue can hold the specified capacity and resizes its underlying buffer if necessary.
        /// </summary>
        public void EnsureCapacity(int capacity);

        /// <summary>
        ///   Sets capacity to the actual number of elements in the queue, if that is less than 90 percent of current capacity.
        /// </summary>
        public void TrimExcess();

        /// <summary>
        ///   Gets a collection that enumerates the elements of the queue.
        /// </summary>
        public UnorderedItemsCollection UnorderedItems { get; }
        public class UnorderedItemsCollection : IReadOnlyCollection<(TElement Element, TPriority Priority)>, ICollection
        {
            public struct Enumerator : IEnumerator<(TElement TElement, TPriority Priority)>, IEnumerator { }
            public Enumerator GetEnumerator();
        }
    }
}
```

## Usage Examples

``` C#
var pq = new PriorityQueue<string, int>();

pq.Enqueue("John", 1940);
pq.Enqueue("Paul", 1942);
pq.Enqueue("George", 1943);
pq.Enqueue("Ringo", 1940);

Assert.Equal("John", pq.Dequeue());
Assert.Equal("Ringo", pq.Dequeue());
Assert.Equal("Paul", pq.Dequeue());
Assert.Equal("George", pq.Dequeue());
```

## Alternative Designs

We recognize the need for heaps that support efficient priority updates, so we will consider introducing a separate specialized class that addresses this requirement at a later stage. Please refer to the [original issue](https://github.com/dotnet/runtime/issues/14032) for a more in-depth analysis on the alternatives.

## Open Questions

* Should we use `KeyValuePair<TPriority, TElement>` instead of `(TPriority Priority, TElement Element)`? 
   - _We will use tuple types instead of KeyValuePair._
* Should enumeration of elements be sorted by priority?
   - _No. We will expose the enumerable as separate property whose name emphasizes that it is unsorted._
* Should we include a `bool Contains(TElement element);` method?
   - _We should consider adding this. Will be O(n) operation. Another issue is taking custom element equality into consideration._
* Should we include a `void Remove(TElement element);` method?
   - _No. Can be ambiguous operation in the presence of duplicate elements._

**Comment by MihaZupan** [comment]
> Priority ordinals are passed as separate values (rather than being encapsulated by the element)

How come? Is it common to use a heap without having a custom node type? I'm just surprised by this one as I've always just had the node perform comparisons.

**Comment by stephentoub** [comment]
> public class PriorityQueue<TElement, TPriority> : IReadOnlyCollection<(TElement Element, TPriority Priority)>

Are there any constraints on the type parameters? e.g. `where TPriority : notnull`?

> public bool TryDequeue(out TElement element, out TPriority priority);
> public bool TryPeek(out TElement element, out TPriority priority);

These should have `[MaybeNullWhen(false)]` on both arguments.

> EnqueueDequeue

Can you share an example where this is used?  And it's more efficient because, if it's based on a heap, it only has to sift once instead of twice?

> : IReadOnlyCollection<(TElement Element, TPriority Priority)>

Not that LINQ has some optimizations based on the non-generic `ICollection.Count`.  I think this would the (or one of the) first prominent collection types that didn't implement it.  `Queue<T>`, for example, implements both `IReadOnlyCollection<T>` and the non-generic `ICollection`.  Did you consider implementing it?  Or as part of this are we going to revisit `IReadOnlyCollection<T>` specialization in LINQ?  Or... maybe it doesn't matter?

> Should enumeration of elements be sorted by priority?

Can that be done without O(N) additional space?

**Comment by eiriktsarpalis** [comment]
> > Priority ordinals are passed as separate values (rather than being encapsulated by the element)
>
> How come? Is it common to use a heap without having a custom node type? I'm just surprised by this one as I've always had the node perform comparisons.

I think it is pretty common actually. When investigating our codebases I found many PQ implementations passing priority as a separate parameter. However even for queues ordering on the elements themselves, it was very common for consumers to populate the type parameter with a tuple containing an element and a priority, then use a custom comparer that projected to the priority. To me this seems like we might be forcing additional boilerplate just to encapsulate the priority.

I think the real issue here is performance, since you end up copying more stuff. In practice however I found the perf impact to be negligible, but it could still be a real issue if your ordinal is a large struct.

> > public class PriorityQueue<TElement, TPriority> : IReadOnlyCollection<(TElement Element, TPriority Priority)>
>
> Are there any constraints on the type parameters? e.g. where TPriority : notnull?

Probably not. Comparisons are done using the provided `IComparer<TPriority>` instance, and the default comparers seem perfectly capable of handling null parameters.

> > EnqueueDequeue
>
> Can you share an example where this is used? And it's more efficient because, if it's based on a heap, it only has to sift once instead of twice?

Correct. It's also _O(1)_ if the enqueued operation is less or equal to the min element and is always guaranteed to succeed. The standard term for that operation is push-pop and is available in the python heap implementation.

> > : IReadOnlyCollection<(TElement Element, TPriority Priority)>
>
> Not that LINQ has some optimizations based on the non-generic ICollection.Count. I think this would the (or one of the) first prominent collection types that didn't implement it. Queue<T>, for example, implements both IReadOnlyCollection<T> and the non-generic ICollection. Did you consider implementing it? Or as part of this are we going to revisit IReadOnlyCollection<T> specialization in LINQ? Or... maybe it doesn't matter?

I was considering `ICollection<T>` but it was not clear to me how to best implement the `Contains()` and `Remove()` methods. `ICollection` is probably fine though, will update the API proposal.

> > Should enumeration of elements be sorted by priority?
>
> Can that be done without O(N) additional space?

Not to my knowledge. I thought I'd raise this point though, since we had customer feedback stating that unsorted feedback felt counterintuitive (given how `Queue<T>` behaves).

**Comment by stephentoub** [comment]
> The standard term for that operation is push-pop and is available in the python heap implementation.

Can you share an example of an algorithm that uses it?

>> Can that be done without O(N) additional space?

> Not to my knowledge. I thought I'd raise this point though, since we had customer feedback stating that unsorted enumeration felt counterintuitive (given how Queue<T> behaves).

I think a struct-based Enumerator allocating O(N) space would also be counterintuitive ;-)

**Comment by eiriktsarpalis** [comment]
> > The standard term for that operation is push-pop and is available in the python heap implementation.
>
> Can you share an example of an algorithm that uses it?

In python it is commonly used in algorithms that need to keep the heap within a given capacity, for example when calculating [_k_ closest points](https://github.com/keon/algorithms/blob/master/algorithms/heap/k_closest_points.py).

**Comment by stephentoub** [comment]
I see.  Such use doesn't actually care about the result of the dequeue, just that the min is replaced.

**Comment by eiriktsarpalis** [comment]
Correct. Happy to discuss a better method name, I simply adapted `pushpop` to our terminology.

**Comment by stephentoub** [comment]
> Happy to discuss a better method name

Seems ok

**Comment by ericsampson** [comment]
Do you envision a future `ConcurrentPriorityQueue` ?

**Comment by stephentoub** [comment]
> Do you envision a future ConcurrentPriorityQueue ?

Not at present. We'd need significant evidence that there was both a) a strong need for it and b) a significantly better implementation than just lock'ing around each operation.

**Comment by GSPP** [comment]
> Sets capacity to the actual number of elements in the queue, if that is less than 90 percent of current capacity.

1. Should we not allow the user to pick that policy? They can easily perform this check themselves with a percentage of their liking. With this design, it is not possible to use a percentage above 90%.

2. Would sorted enumeration be more efficient than the user sorting after enumeration? If yet it might be worth it to provide a `EnumerateOrdered` method.

3. A `ToArray` method seems useful.

**Comment by eiriktsarpalis** [comment]
> Should we not allow the user to pick that policy? They can easily perform this check themselves with a percentage of their liking. With this design, it is not possible to use a percentage above 90%.

That's literally replicating the logic of the [Queue.TrimExcess](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.queue-1.trimexcess?view=netcore-3.1) method. I'm not sure why the 90% threshold was chosen there.

> Would sorted enumeration be more efficient than the user sorting after enumeration? If yet it might be worth it to provide a EnumerateOrdered method.

Maybe, but users might assume it's a cheap operation. I'd rather they explicitly pay the price by sorting the elements.

> A ToArray method seems useful.

Sounds reasonable, will update the proposal.

**Comment by ericsampson** [comment]
If your `TElement` is a class/struct that contains its priority as a field, is there a suggested pattern to avoid storing the priority twice? (is it dumb/slow to have `TPriority` = `TElement` and then use a custom comparer to project the priority field?)

**Comment by eiriktsarpalis** [comment]
> If your TElement is a class/struct that contains its priority as a field, is there a suggested pattern to avoid storing the priority twice? (is it dumb/slow to have TPriority = TElement and then use a custom comparer to project the priority field?)

Good question. You wouldn't be able to avoid storing the priority twice. However, in my benchmarks I found that this duplication has negligible performance impact (I presume though that the story might be different if the priority type is a large struct).

I recently ran an investigation of codebases that employ PriorityQueues, and found the following to be true:

* Most elements do not encapsulate priorities.
* Priorities are typically small, numeric values.

The design proposed here therefore is a trade-off between duplication (for the cases where elements do contain their priorities) and API simplicity (not requiring users to write wrapper types and custom comparers).

**Comment by Enderlook** [comment]
Can I ask why not having both types?
I mean, one as `PriorityQueue<TElement, TPriority>` and other as `PriorityQueue<T>`, where `T` is both the element and the priority.
Both implementations would be quite similar, so it wouldn't be much effort to have both.

**Comment by eiriktsarpalis** [comment]
> Can I ask why not having both types?

I don't think the benefits outweigh the effort of designing and maintaining two almost identical types.

**Comment by GSPP** [comment]
Is it considered acceptable and "a good idea" to put value tuples in the public surface area? (`(TElement Element, TPriority Priority)`). An alternative could be a custom struct. It would be a pretty simple DTO type.

**Comment by eiriktsarpalis** [comment]
> Is it considered acceptable and "a good idea" to put value tuples in the public surface area?

There is precedent, e.g. the [`Enumerable.Zip`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?view=netcore-3.1) method. Alternatively we could just use `KeyValuePair<TPriority, TElement>`, but I felt that "Key" might not be a name users necessarily associate with priority (even though it is sometimes referred to as that in certain heap implementations).

**Comment by bartonjs** [comment]
> Not a stable queue (elements enqueued with equal priority not guaranteed to be dequeued in the same order).

I don't think you can call it a queue then.  Even in your sample usage you asserted that the item inserted at a given priority (or birth year, whatever) first came out first.

**Comment by bartonjs** [comment]
> Does the name 'queue' necessarily imply FIFO?

Wikipedia says so :smile::

> In computer science, a queue is a collection of entities that are maintained in a sequence and can be modified by the addition of entities at one end of the sequence and the removal of entities from the other end of the sequence. ... The operations of a queue make it a first-in-first-out (FIFO) data structure.

The Oxford Languages dictionary also agrees:

> 2. (Computing) a list of data items, commands, etc., stored so as to be retrievable in a definite order, usually the order of insertion.

While that one tries to avoid locking it to FIFO with "usually" it does say that the order is "definite".

Admittedly, Wikipedia for Priority queue is less prescriptive:

> In some implementations, if two elements have the same priority, they are served according to the order in which they were enqueued, while in other implementations, ordering of elements with the same priority is undefined. 

In a system where the queue gets reliably drained to empty there's not a problem, but in a "we got a surge and then maintain steady state for a long time" situation having one of the oldest items sitting around and aging while newer items at the same priority get processed feels bad to me.  Since I was just dealing with phone-based customer service, I'll say "I certainly hope no customer service phone system uses a priority queue that doesn't maintain ordering at relative priorities".

**Comment by ericsampson** [comment]
> > Is it considered acceptable and "a good idea" to put value tuples in the public surface area?
> 
> 
> 
> There is precedent, e.g. the [`Enumerable.Zip`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?view=netcore-3.1) method. Alternatively we could just use `KeyValuePair<TPriority, TElement>`, but I felt that "Key" might not be a name users necessarily associate with priority (even though it is sometimes referred to as that in certain heap implementations).

Seems like it should be OK now, since this isn't going to be used with Framework etc. it's certainly more intuitive
is this lib going to multitarget ns2.0/2.1, or purely NET5 ?

**Comment by eiriktsarpalis** [comment]
My point is that the term 'queue' doesn't seem to carry strong connotations of FIFO-like behaviour. For example, the [javadoc for queues](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/Queue.html) contains a rather loose interpretation:

> Queues typically, but do not necessarily, order elements in a FIFO (first-in-first-out) manner. Among the exceptions are priority queues, which order elements according to a supplied comparator, or the elements' natural ordering, and LIFO queues (or stacks) which order the elements LIFO (last-in-first-out).

Bottom line, I don't think we would be able to guarantee this without some performance hit. At the same time, it is fairly trivial for users to [obtain stability if they need it](https://github.com/dotnet/runtime/issues/14032#issuecomment-717148011).

**Comment by bartonjs** [comment]
> Is it considered acceptable and "a good idea" to put value tuples in the public surface area?

Hand-waving a lot, the guideline is "don't do it if there's any other sensible approach".

If there's any possibility at all that the API would want to expose an enqueued item with its priority and use that item to update the priority (which would require a method) then it would need to use a custom type now.  But since it's really just "you gave me two things, I'm giving you back those two things" (which is what it was for Enumerable.Zip) then creating a custom type is really just noise, and using KeyValuePair is using worse names just to avoid ValueTuple.

**Comment by bartonjs** [comment]
> My point is that the term 'queue' doesn't seem to carry strong connotations of FIFO-like behaviour.

Something in my background has built "FIFO" and "queue" as literal synonyms, similar with "FILO" and "stack" (data structure).  Various Wikipedia authors seem to have similar backgrounds, since the [FIFO](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)) and [Queue](https://en.wikipedia.org/wiki/Queue_(abstract_data_type)) pages seem to arbitrarily use both terms.

> it is fairly trivial for users to obtain stability if they need it.

That stability approach has an overflow problem; but I suppose if it uses `ulong` then it's effectively immune; though if someone builds one with load/save(//serialize/deserialize) mechanics they'd want to avoid saving the order value and just rebuilding that on load.

**Comment by ericsampson** [comment]
I was figuring that a real implementation of stability might decrement when popping to help with overflow? It'd be good to have a decent example in the eventual docs.

**Comment by ericsampson** [comment]
Naming is always bikesheddy :) if it wasn't for the Java/C++ precedent, a more natural/parallel fit with the existing C# data structures might have been `PriorityBag` :D

**Comment by terrajobst** [comment]
* Add `EnqueueRange(IEnumerable<TElement> values, TPriority priority)`
* Implementing `IEnumerable` might be problematic because consumers are likely expecting it to return the elements in the order in which `Dequeue` would (or at least priority order)
    - That argument likely also applies to `Elements`, so we should removed that
    - Instead add a `public UnorderedItemsCollection UnorderedItems { get; }` (and should not allocate on each get)
* Consider adding `Contains`
* This collection will be shipped in the same assembly that contains the other types in `System.Collections.Generic`

**Comment by MihaZupan** [comment]
Is `UnorderedItemsCollection` a snapshot or an iterator?
- If it's a snapshot, could it be a `(TElement, TPriority)[] ToArray()` instead? There's now no "free" iteration over PQ elements.
- If it's an iterator, is it clear that it has the same modification limitations as a foreach loop? Seems dangerous

**Comment by terrajobst** [comment]
> Is `UnorderedItemsCollection` a snapshot or an iterator?

Clarified

**Comment by eiriktsarpalis** [comment]
Updated the OP and updated the [prototype](https://github.com/eiriktsarpalis/pq-tests/blob/master/PriorityQueue/PriorityQueue.cs) to incorporate API review feedback.

**Comment by eiriktsarpalis** [comment]
@pgolebiowski would you still be interested in contributing the implementation?

**Comment by Rickasaurus** [comment]
Stable would be nice to have if you can swing it. Code gets a lot more complex when things can randomly reorder.

**Comment by reflectronic** [comment]
`EnsureCapacity` should return an `int` representing the actual new capacity. This is how `EnsureCapacity` works in [`StringBuilder` ](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.ensurecapacity?view=net-5.0), [`HashSet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.ensurecapacity?view=net-5.0), and [`Dictionary<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.ensurecapacity?view=net-5.0).

**Comment by eiriktsarpalis** [comment]
> EnsureCapacity should return an int representing the actual new capacity. This is how EnsureCapacity works in StringBuilder , HashSet<T>, and Dictionary<TKey, TValue>.

Good point, the signatures should be consistent. @terrajobst should I just update the proposal?

**Comment by pgolebiowski** [comment]
> @pgolebiowski would you still be interested in contributing the implementation?

Yes, would love to! Will submit a pull request over the next two weeks 😊 Could you add me to the assignees of this issue?

**Comment by danmosemsft** [comment]
Will any concurrent optimizations invalidate the enumerator? For example in `Dictionary<K,V>` just Add/Insert, Trim, and Grow invalidate the enumerator, because those may cause enumeration to misbehave. Remove does not, you just may or may not see the remove depending on where you enumerated to.

**Comment by eiriktsarpalis** [comment]
> Will any concurrent modifications invalidate the enumerator? For example in Dictionary<K,V> just Add/Insert, Trim, and Grow invalidate the enumerator, because those may cause enumeration to misbehave. Remove does not, you just may or may not see the remove depending on where you enumerated to.

In heaps update operations involve shuffling elements around to preserve the heap property, for example in Dequeue you actually pick the last element from the tree and sift it downward from the top. So I don't think we could avoid invalidating the enumeration without potentially skipping elements.

**Comment by eiriktsarpalis** [comment]
Hi @pgolebiowski, I've updated the OP with a "Definition of Done" checklist. Note that this is not work we are asking you to complete in a single PR, rather, it enumerates what is needed for the feature to be considered ready for shipping. It is an effort we will be iterating on, and I will be happy to take on some of the more menial tasks on that list.

**Comment by ericsampson** [comment]
@eiriktsarpalis, do other languages/libraries offer the equivalent of:
```public TElement Dequeue(Tpriority priority)
public TElement Peek(Tpriority priority);
```

**Comment by eiriktsarpalis** [comment]
@ericsampson I'm not sure I understand what these methods should do, find elements whose priority matches (or is greater than) the supplied priority? If so, they are remove operations rather than dequeue operations, and would require a linear time scan of the heap contents.

**Comment by ericsampson** [comment]
Sorry for the terminology confusion, yeah you have the idea. 

A motivation would be to allow a form of priority boosting; say you're writing a job scheduler, and want to ensure that lower-priority jobs get run "sometime", even if the queue is continually full of higher priority jobs. 

I believe that Java's implementation has something like `Remove(Telement element)`, which could be used along with the iterator by the end user to achieve this functionality (although with two scans). 
Or also offering `Remove(Tpriority)`

Am I thinking right that the originally described use case can't be accomplished with the current proposed API surface? If so that could be a good motivation to add `Remove` to the API surface, like Java has. Or maybe I just need more coffee ☕️ :)

**Comment by eiriktsarpalis** [comment]
We discussed adding a `Remove` method like Java, however we eventually decided against it due to poor performance and ambiguity in the presence of duplicate elements.

**Comment by ericsampson** [comment]
I can understand that.

How then could a person achieve this use case (effectively 'dequeue an item with a given priority') given the current API surface? Thanks!

**Comment by eiriktsarpalis** [comment]
> How then could a person achieve this use case (effectively 'dequeue an item with a given priority') given the current API surface? Thanks!

Such an operation would not be supported. I have created a [separate issue](https://github.com/dotnet/runtime/issues/44871) for creating a heap implementation that would support priority update and removal operations (however you could only remove by specifying the element _not_ the priority).

**Comment by ericsampson** [comment]
Thanks, I had a feeling the answer would be "wait for the priority-update supporting version". Cheers

**Comment by eiriktsarpalis** [comment]
Note that it would still not be possible to remove elements _by priority_, at least not without it requiring a linear-time scan.

**Comment by ericsampson** [comment]
Yup. I'd be ok with a scan. Or more likely, to obtain the behavior I originally described, I would bump/increment the priority of lower priority items every N dequeues or something, and let the natural dequeuing pop them off eventually. Thanks Erik.

**Comment by eiriktsarpalis** [comment]
Hi @pgolebiowski, do you have any updates on the progress of the implementation? Feel free to reach out if you need any help.

**Comment by pgolebiowski** [comment]
Hi @eiriktsarpalis! I've just created the scaffolding for product code. It would be really great if you could have a look and sanity check this scaffolding before I add implementation and tests 😊

**Comment by jeffhandley** [comment]
@pgolebiowski FYI - I'm going to add @eiriktsarpalis and myself to the assignees list so that we can see this on our team's project board.

**Comment by eiriktsarpalis** [comment]
Reopening to track outstanding documentation work.

**Comment by sharpninja** [comment]
I don't understand why you would not preserve order of insertion for items at the same queue level.  This basically eliminate use cases where you could dispatch events based on priority from this structure.

**Comment by eiriktsarpalis** [comment]
@sharpninja this is a property common with most heap implementations. You could still guarantee stability using the [technique detailed here](https://github.com/dotnet/runtime/issues/14032#issuecomment-717148011).

**Comment by Gakk** [comment]
> My point is that the term 'queue' doesn't seem to carry strong connotations of FIFO-like behaviour. For example, the [javadoc for queues](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/Queue.html) contains a rather loose interpretation:
> 
> > Queues typically, but do not necessarily, order elements in a FIFO (first-in-first-out) manner. Among the exceptions are priority queues, which order elements according to a supplied comparator, or the elements' natural ordering, and LIFO queues (or stacks) which order the elements LIFO (last-in-first-out).
> 
> Bottom line, I don't think we would be able to guarantee this without some performance hit. At the same time, it is fairly trivial for users to [obtain stability if they need it](https://github.com/dotnet/runtime/issues/14032#issuecomment-717148011). [@eiriktsarpalis]

The way I read the javadoc you quoted, even Java believes _queue_ usually is FIFO - with the exception of priority queue as they can pick a priority element in the middle of the queue. The other exception is a LIFO, and that also has an stable order.

I believe naming this class _PriorityQueue_ is wrong as long as it is not a stable queue for elements with equal priority. Even if the name _queue_ does not _have_ to reflect a stable queue, it is bad naming since a lot of developers will misinterpret and believe it to be a FIFO for elements of equal priority.

[The first blogpost](https://dotnetcoretutorials.com/2021/03/17/priorityqueue-in-net/) I read of this clearly believes this is a stable queue, as it as example uses a line in the bank, and that some customers have priority. It is expected to handle other customers based on order (FIFO/LIFO) within each priority.

Please either make _PriorityQueue_ stable, or consider renaming to **PriorityBag**, as this already is an established term in .NET.

**Comment by eiriktsarpalis** [comment]
> The way I read the javadoc you quoted, even Java believes queue usually is FIFO - with the exception of priority queue as they can pick a priority element in the middle of the queue. The other exception is a LIFO, and that also has an stable order.

Emphasis on _usually_. The example is there to illustrate the fact that the terms 'queue' and 'FIFO', while synonyms, are not entirely identical.

> The first blogpost I read of this clearly believes this is a stable queue, as it as example uses a line in the bank, and that some customers have priority. It is expected to handle other customers based on order (FIFO/LIFO) within each priority.
>
> Please either make PriorityQueue stable, or consider renaming to PriorityBag, as this already is an established term in .NET.

Heap-backed priority queues are not stable (which is not to say it is impossible to build a priority queue that is stable). This is a fairly well-understood property of most standard priority queue implementations, although it still tends to surprise people:

* [Python: Priority queue does'nt keep order on same priority elements](https://stackoverflow.com/questions/47969623/python-priority-queue-doesnt-keep-order-on-same-priority-elements).
* [C++ priority queue does not respect FIFO order](https://stackoverflow.com/questions/41652194/c-priority-queue-does-not-respect-fifo-order).
* [Making a Java PriorityQueue into a stable priority queue](https://stackoverflow.com/questions/21617098/making-a-java-priorityqueue-into-a-stable-priority-queue).

It is fairly evident that established usage of the term 'priority queue' does not imply stability. A quick search on the term "stable priority queue" should further highlight this fact.

**Comment by Gakk** [comment]
Thanks for the well documented answer 👍 

> This is a fairly well-understood property of most standard priority queue implementations, although it still tends to surprise people.

I would argue that the other languages then have failed with naming. I understand that when C#'s implementation of _PriorityQueue_ is equivalent to the others, a similar naming should apply, and therefore i withdraw my earlier proposal for _PriorityBag_.

Another thought is that the other implementations might be older, from a time where most developers knew the difference between heap and stack. Your references to StackOverflow shows that it is a common misunderstanding, and now on introduction is the perfect time to try to avoid this also for .NET.

I hope at least that the documentation is very clear about this, maybe add in the first line of the description (summary that shows as tooltip in a lot of editors) that the constructor creates _an unstable priority queue_. This might tease the curiosity enough that they read what is the difference between stable and unstable queue. A name of _UnstablePriorityQueue_ would also trigger this, and should avoid most misunderstandings 😇

**Comment by Enderlook** [comment]
Don't want to be picky, but a name as *UnstablePriorityQueue* may cause misunderstanding between beginners.

The word "Unstable" looks as if the priority queue were beta and may still have bugs, or as if the feature is unsafe, like methods that starts with *Dangerous[...]* or *Unsafe[...]*.

**Comment by ericsampson** [comment]
Naming always tends to be bikesheddy, but it is interesting to consider "is it more important to be consistent with other languages, or internally within .NET?" because they each have pros and cons.
I also suggested `PriorityBag` a few months ago on the original feature discussion, because AKAIC it really is natural within the existing .NET data structure class naming. So that probably shows my bias :) 

But everyone has a different bias/viewpoint, and at the end of the day what's far more important is that the functionality exists :) 
And hopefully that a followup `UpdateablePriorityQueue` is realistic :) 

Cheers

**Comment by eiriktsarpalis** [comment]
> I also suggested PriorityBag a few months ago on the original feature discussion, because AKAIC it really is natural within the existing .NET data structure class naming. 

"Bag" implies lack of order, from the [ConcurrentBag docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1?view=net-5.0):

> Represents a thread-safe, unordered collection of objects.

This is nothing like heaps, where elements are ordered up to priority.

**Comment by ericsampson** [comment]
Duh me 🤦‍♂️. I might have been thinking of `OrderedBag`, but that's from a NuGet package and not built in. 

I don't want to waste any more time on naming discussions, I was just musing on that same discussion I've seen other cases, matching .NET conventions vs industry recognizable names. 

Back to actual useful discussion :)

**Comment by theodorzoulias** [comment]
> And hopefully that a followup `UpdateablePriorityQueue` is realistic :)

I wonder whether allowing the `PriorityQueue` to be updateable through a boolean property like `SupportsUpdating`, in the spirit of the [`BackgroundWorker.WorkerSupportsCancellation`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker.workersupportscancellation), would be a better option than exposing two priority queue types.

**Comment by FiniteReality** [comment]
> > And hopefully that a followup `UpdateablePriorityQueue` is realistic :)
> 
> I wonder whether allowing the `PriorityQueue` to be updateable through a boolean property like `SupportsUpdating`, in the spirit of the [`BackgroundWorker.WorkerSupportsCancellation`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker.workersupportscancellation), would be a better option than exposing two priority queue types.

I don't think it would be - I think the most likely result for that would be a split implementation (akin to Channels) internally, or far more complicated to support both situations.

**Comment by eiriktsarpalis** [comment]
> And hopefully that a followup UpdateablePriorityQueue is realistic :)

Please indicate your support for the feature by contributing to the conversation in #44871. The popularity of certain issues influences our priorities (much how the popularity of #14032 convinced us to build this PriorityQueue). There's also open design questions that we need your input in order to resolve.
