### ISSUE TITLE
Unexpected "Possible null reference" warnings when passing string literals to XName ctor

### ISSUE THREAD

**Issue by plioi** [dotnet/runtime#43961]
This appeared for me in 5.0.100-rc.1.20452.10. For example:

```cs
new XAttribute("name", message.Assembly.Location),
new XAttribute("run-date", now.ToString("yyyy-MM-dd")),
new XAttribute("run-time", now.ToString("HH:mm:ss")),
new XAttribute("time", Seconds(message.Duration)),
new XAttribute("total", message.Total),
```

Even though the first argument, `name`, is definitely not null here, I get errors on each line (I enabled warnings as errors, and these appear to be Nullable Reference Type warnings):

    error CS8604: Possible null reference argument for parameter 'name' in 'XAttribute.XAttribute(XName name, object value)'

**Comment by am11** [comment]
Seems to be fixed in recent builds (can't repro with `5.0.100-rtm.20515.8`, downloaded from https://github.com/dotnet/installer#installers-and-binaries).

**Comment by plioi** [comment]
Agreed, I think this can be closed.

**Comment by krwq** [comment]
Yes, this is a Roslyn issue and it should already be fixed in recent builds. The workaround for whoever cannot update the compiler is following (it may seem a bit weird though):

`new XAttribute("name"!, message.Assembly.Location)`
