### ISSUE TITLE
[Proposal] Analyzer that suggests ToUpperInvariant/ToLowerInvariant in place of ToUpper/ToLower

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#43976]
When using `String.ToUpper()` or `String.ToLower()`, suggest using `String.ToUpperInvariant()` and `String.ToLowerInvariant()`.

Something similar is already in place here, but for string comparisons: [CA1309: Use ordinal StringComparison](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1309?view=vs-2019)

A PR already exists to fix this. We want to get this proposal approved before reviewing it: https://github.com/dotnet/roslyn-analyzers/pull/2186

- Analyzer: small
- Fixer: small
- Suggested category: [Globalization](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/globalization-warnings)
- Suggested severity: Info (to match [CA1309](https://github.com/dotnet/roslyn-analyzers/blob/f167914d442d0ae0055b28a1c92e5b9d446fdbdb/.editorconfig#L267))
- Milestone: 6.0

Usage examples:
```cs
string s = "my string";
string lower, upper;


// Suggest to use ToLowerInvariant() or to explicitly indicate the culture.
// Offer fix to use ToLowerInvariant()
lower = s.ToLower();
lower = "str".ToLower();

// Suggest to use ToUpperInvariant() or to explicitly indicate the culture.
// Offer fix to use ToUpperInvariant()
upper = s.ToUpper();
upper = "str".ToUpper();

CultureInfo culture = new CultureInfo("es-ES", false);

// Should not suggest
lower = s.ToLower(culture);
upper = s.ToUpper(culture);



// Should we suggest to use To*Invariant() in these cases? tarekgh thinks it's not necessary, but we can discuss it:
// Is this the same as ToLowerInvariant? https://source.dot.net/#System.Private.CoreLib/String.Manipulation.cs,1710
lower = s.ToLower(CultureInfo.InvariantCulture);
// Is this the same as ToUpperInvariant? https://source.dot.net/#System.Private.CoreLib/String.Manipulation.cs,1725
upper = s.ToUpper(CultureInfo.InvariantCulture);
```

**Comment by tarekgh** [comment]
@jamesqo as suggested in this thread you need to add the proposal up in the issue description. 

are you suggesting to have the analyzer suggest ToUpperInvariant/ToLowerInvariant all the time when ToUpper/ToLower show up? or would be depending on the context of the callsite?

**Comment by krwq** [comment]
I think if we do not recommend to use ToUpper/ToLower at all we should deprecate it or change implementation to call into To*Invariant (perhaps with a switch to bring back the old behavior)

**Comment by tarekgh** [comment]
> or change implementation to call into To*Invariant (perhaps with a switch to bring back the old behavior)

I don't think it is a good idea to change the behavior even with a switch. From other discussions with the community in other issues, it looks using the switch is not a solution for all situations. I agree to deprecate `String.ToUpper/ToLower()` though and perhaps we think exposing something like ToUpperOrdinal/ToLowerOrdinal. but anyway, I think having the analyzer warn about `String.ToUpper/ToLower()` is a good thing anyway.

**Comment by carlossanlop** [comment]
I updated the description to get this proposal ready for review. @TKharaishvili @tarekgh let me know if you have any comments about my edit. Otherwise, let's wait for the API review meeting to discuss this.

**Comment by tarekgh** [comment]
I am fine with the proposal. Only the last part `lower = s.ToLower/ToUpper(CultureInfo.InvariantCulture);` is not really necessary as I am seeing both usages still correct.

**Comment by terrajobst** [comment]
* This is one of the more noisy analyzers from FxCop
    - It makes sense for class libraries / server projects, but for WinForms, WPF it doesn't really make a difference
    - Can we scope the analyzer for the project type / output type? Not all libraries are the same (e.g. some are user control, some are test projects)
* However, it seems useful to have a severity of hidden so that people can invoke the fixer to replace all calls to the appropriate overload

**Comment by tarekgh** [comment]
@TKharaishvili just checking, are you still working on that?

**Comment by tarekgh** [comment]
I moved this to 7.0 as I am not seeing urgency to have it for 6.0. That is fine if we get a PR for 6.0 too.

**Comment by TKharaishvili** [comment]
@tarekgh I won't have any time to work on this in the next 2 months. I'll come back to it afterwards if that works for you guys.

**Comment by carlossanlop** [comment]
@TKharaishvili are you still going to work on this?

**Comment by TKharaishvili** [comment]
@carlossanlop yes, I'll have an updated PR over the next several days.

**Comment by TKharaishvili** [comment]
Hi @carlossanlop I tested positive for covid and won't be able to get any work done for some time. If you guys need this taken care of urgently, please unassign me from the issue, otherwise I'll get back to it once I'm better.
I apologize for the inconvenience.

**Comment by TKharaishvili** [comment]
Hi @carlossanlop I'm back at it. I see a lot has changed in the repo since I first sent that PR(which is to be expected for a 3 year gap). Originally I added the analyzer source file to the `Microsoft.NetCore.Analyzers` project. That project is no longer there but I found something similar, I'm thinking the `Microsoft.CodeAnalysis.NetAnalyzers` project -> `Microsoft.NetCore.Analyzers.Runtime` folder is the right place for it. Would you agree?

Also I'm thinking of dropping this current PR and creating a new one instead. Doing a merge after this long is proving to be too much of a headache.

**Comment by tarekgh** [comment]
@carlossanlop @buyaa-n could you please help with @TKharaishvili question in the previous comment? 

@TKharaishvili are you still willing to submit the PR? Thanks!

**Comment by buyaa-n** [comment]
Sorry for late reply @TKharaishvili @tarekgh 

> I'm thinking the Microsoft.CodeAnalysis.NetAnalyzers project -> Microsoft.NetCore.Analyzers.Runtime folder is the right place for it. Would you agree?

Yes that is the right place

> Also I'm thinking of dropping this current PR and creating a new one instead. Doing a merge after this long is proving to be too much of a headache.

Right, sounds good, feel free to close your old PR then

**Comment by TKharaishvili** [comment]
@tarekgh @buyaa-n I already proceeded since there was no response for a while. Decided to update the existing PR, it currently has the analyzer in it and I believe it was looked at by some of the team members. All that's missing right now is a fixer. I'll resume working on that next week.

**Comment by danmoseley** [comment]
@TKharaishvili hello, are you still working on this ?

**Comment by TKharaishvili** [comment]
@danmoseley I pushed the latest code review requested changes yesterday. Waiting for another round of review now.
