### ISSUE TITLE
[Platform Compatibility Analyzer] Nested APIs shouldn't be allowed to expand the platform set

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#43971]
### Repro

```C#
[SupportedOSPlatform("ios")]
class Some
{    
    [SupportedOSPlatform("windows")]
    public static void Api() {}
}
```

### Expected

> 'Api' cannot widen the set of supported platforms of its containing symbol `Some`.

### Work Items

Each of these should produce separate diagnostic ids:

- [ ] Inconsistent List section of the [Advanced Scenarios of Combining Attributes](https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer#advanced-scenarios-for-combining-attributes), when conflicting attributes are applied at the same level
- [x] Nested APIs shouldn't be allowed to expand the platform set and version support

**Comment by carlossanlop** [comment]
@buyaa-n will help group this issue with these two others into one proposal:
https://github.com/dotnet/roslyn-analyzers/issues/4014
https://github.com/dotnet/roslyn-analyzers/issues/4015

**Comment by buyaa-n** [comment]
Category: Interoperability
Suggested Severity: Info

This analyzer might be implemented as part of https://github.com/dotnet/runtime/issues/45851 and should cover the following main scenarios:

- Nested APIs shouldn't be allowed to expand the platform set and version support
- It should flag `Inconsistent list` determined by the following rule:
  - If either `[SupportedOSPlatform]` or `[UnsupportedOSPlatform]` attributes are present, we group all attributes by OS platform identifier:
    - **Allow list**. If the lowest version for each OS platform is a `[SupportedOSPlatform]` attribute, the API is considered to only be supported by the listed platforms and unsupported by all other platforms.
    - **Deny list**. If the lowest version for each OS platform is a `[UnsupportedOSPlatform]` attribute, then the API is considered to only be unsupported by the listed platforms and supported by all other platforms.
    - **Inconsistent list**. If for some platforms the lowest version attribute is `[SupportedOSPlatform]` while for others it is `[UnsupportedOSPlatform]`, the analyzer will produce a warning on the API definition because the API is attributed inconsistently.

- We can add multiple attributes for an API  with the same platform, with the following rule:
    - **Allow list** could have only one `[SupportedOSPlatform]` attribute and an optional `[UnsupportedOSPlatform]` attribute with `>=` version. This implies that if an API was supported on a platform then could have unsupported later, but it cannot be `re-supported` back
    - **Deny list**. could have only two `[UnsupportedOSPlatform]` attributes and one `[SupportedOSPlatform]` attribute. This implies that an API was unsupported for a platform and later added a support, then can be unsupported back. But after that, it cannot be `re-supported` back

**Comment by buyaa-n** [comment]
Examples:
- `Inconsistent list`
```cs
[UnsupportedOSPlatform("browser")] // warns here: `Inconsistent platform 'browser' found in the Supported platforms list`
[SupportedOSPlatform("windows")]
[UnsupportedOSPlatform("windows10.0.19041")]
public void Api1();
```
- `Multiple attributes for same platform`
```cs
// Allow list
[SupportedOSPlatform("ios12.0")] // If two SupportedOSPlatform attributes applied, the one with lowest version accepted
[UnsupportedOSPlatform("ios14.0")]
[SupportedOSPlatform("ios15.0")] // Warns:  `Platform 'ios' is unsupported from version 14.0 cannot re supported back`
public void OnlyWorksOniOS();

// Deny list
[UnsupportedOSPlatform("windows")]
[SupportedOSPlatform("windows8.0")]
[UnsupportedOSPlatform("windows10.0.19041")]
[SupportedOSPlatform("windows10.0.2004")] // Warns: `Platform 'windows' is unsupported from version 10.0.19041 cannot re supported back`
public void WorksOnWindows8To10();
```

**Comment by jeffhandley** [comment]
Throughout .NET 6, we've seen less evidence that we need to have an analyzer warning about this. Our rules for this scenario have continued to be refined, and we have intentionally opened up some scenarios where nested APIs _can_ expand the parent set of platforms--particularly when dealing with cross-platform/platform-neutral libraries.

As a result, I'm going to close this issue; we can revisit after .NET 6 if appropriate.
