### ISSUE TITLE
We need an official MSIX for Windows Desktop

### ISSUE THREAD

**Issue by wjk** [dotnet/runtime#43977]
What the title says. I've been trying to shift as much of my deployment to MSIX as I can, but under the current state of affairs I have to copy the entire .NET 5 core and desktop runtimes into every package (either a self-contained app build, or manually copying `C:\Program Files\dotnet` under `VFS\ProgramFiles64`). This wastes space and increases download time. It would be even better if this MSIX package were made available to use as a dependency in the Windows Store. Some say the store is being supplanted by winget (which, IMO, is a good thing), but I still have three apps in there. This repo seemed like the best place to ask for this. Thanks so much!

**Comment by NikolaMilosavljevic** [comment]
cc @jamshedd

**Comment by NikolaMilosavljevic** [comment]
[Triage] There are no immediate plans to produce MSIX packages.
