### ISSUE TITLE
Invest in library-focused Roslyn analyzers

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43979]
We would like to propose adding the Roslyn Analyzers project as part of the 6.0 objectives to improve .NET.

@buyaa-n and I would like to suggest including this user story in the "_Meeting Developer Expectations_" Theme, and the "_Make sure .NET libraries are continuously improved_" Epic from https://dotnetepics.azurewebsites.net/ cc @terrajobst

We have 36 API proposals in the Roslyn Analyzers project that we are going to be driving for review: https://github.com/dotnet/runtime/projects/46

We also have [27 open issues](https://github.com/dotnet/roslyn-analyzers/issues?q=is%3Aissue+is%3Aopen+label%3AArea-Microsoft.NetCore.Analyzers) (bugs, enhancements) in the roslyn-analyzers repo, as well as a number of PRs to review to fix or improve the analyzers we own.

cc @mavasani

**Comment by danmosemsft** [comment]
@carlossanlop I've added it to https://github.com/dotnet/core/issues/5410 (I simply added a checkbox and link so that it shows up on  https://dotnetepics.azurewebsites.net/ ). 

You should feel free to add other entries to that as seems appropriate (unless @jeffhandley provides other guidance). We can triage, etc later.

**Comment by danmosemsft** [comment]
Moved under https://github.com/dotnet/runtime/issues/43617 as there's already a user story.

**Comment by danmosemsft** [comment]
@terrajobst as discussed can you please replace this issue with the specific analyzers we plan to do so they appear in the tree

**Comment by terrajobst** [comment]
Done
