### ISSUE TITLE
Reduce List<object> allocations by passing the initial array

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/runtime#43989]
Not sure if this is the right repository, or if still relevant as I could not find the source code of EventSource here.

Some minor improvement I noticed while benchmarking allocations on our code, I think could be traced to [the call to Add on the list in this line](https://github.com/microsoft/referencesource/blob/08b84d13e81cfdbd769a557b368539aac6a9cb30/mscorlib/system/diagnostics/eventing/eventsource.cs#L1423)

![image](https://user-images.githubusercontent.com/8791811/96351285-a0a40f80-10ba-11eb-92be-18e393bc0e7a.png)

`````csharp
    List<object> arg = new List<object>();
    arg.Add(msg);
`````

could be changed to:

`````csharp
    List<object> arg = new List<object>(new []{ msg });
`````

**Comment by GrabYourPitchforks** [comment]
Adding a ctor that takes a `T[]` would be a compile-time breaking change. But in theory if we wanted to add something along these lines we could utilize the newly minted [`CollectionsMarshal` class](https://apisof.net/catalog/System.Runtime.InteropServices.CollectionsMarshal).

**Comment by Joe4evr** [comment]
Something that may be worth checking here is the perf of using the List constructor that takes `int initialCapacity`. IIRC, constructors that don't take that parameter initialize the backing array to the `Array.Empty<T>` instance so that the off-chance that nothing ever gets added to said list doesn't actually allocate, at the cost of a slight hit when something gets added the first time.

**Comment by am11** [comment]
> ```c#
>    List<object> arg = new List<object>();
>    arg.Add(msg);
>```
>
> could be changed to:
> ```c#
>    List<object> arg = new List<object>(new []{ msg });
>```

In .NET Core, it was added as:

```c#
eventCallbackArgs.Payload = new ReadOnlyCollection<object>(new List<object>() { msg });
```

in the initial port of EventSource: https://github.com/dotnet/runtime/commit/157a0aee00e8623811c3b9b1ff962a2e2ae8bb67. Later, `FEATURE_ACTIVITYSAMPLING` and associated code were removed in https://github.com/dotnet/runtime/commit/76c7fe9cf8aa6774a6b9fa5d1dd699262fae737e.
