### ISSUE TITLE
.NET Core WebApi 3.1.x how to access .NET 4.x lib

### ISSUE THREAD

**Issue by efgiese** [dotnet/runtime#43995]
I have build a WebApi with .NET core 3.1.101 that accesses a .NET 4.x lib (Progress Open4GL ".NET OpenClient"). I have integrated the "Microsoft.Windows.Compatibility" and all works fine. I have published it to a Server 2019 with IIS.

After upgrading the .NET Core on my notebook to a newer version, the communication to the "OpenClient" fails on my notebook. The build works anyway and i can publish the WebApi to the server a it worked. The server is running the 3.1.101 .NET Core.

What has changed after .NET Core 3.1.101 that the .NET 4.x lib fails to work?

I have read something (never found it again) that there has something changed in using the .NET 4.x lib and .NET Core. Is there a workaround?

I was so happy with .NET Core 3.1 because it was the first time that a build the WebApi with the target "netcoreapp3.1". Before that a had to build it with the target "net461" and .NET Core 2.2.

How can i upgrade to the newest .NET Core Framework an get it to work with the OpenClient lib?

See attached file which is used to build the lib...

[pAMobileEtikett.cs.txt](https://github.com/dotnet/core/files/5110382/pAMobileEtikett.cs.txt)

**Comment by jeffschwMSFT** [comment]
Can you provide more details on what the failure was?  Also can you share more details on what versions you are running against?

cc @jeffhandley

**Comment by efgiese** [comment]
The Progress OpenEdge is 11.7.4.0.1684. I can connect to it with the .NET Core 3.1.101. On any later version the App-Server throw an error and login fails. There are no details available, sorry. Progress has no plan to support .NET Core. The OpenClient compile against the .NET Framework 4.x.

Source see in the file on my first post.

I do not understand why it works with .NET Core 3.1.101 but not with any other .NET Core.

**Comment by joperezr** [comment]
Can you provide a minimal repro or a callstack so that we have something to take a look at?

**Comment by efgiese** [comment]
I created a brand new project, see at https://github.com/efgiese/ProgressConsoleApp, and it works...

Will try to migrate my ohter project to .NET Core 5.0 and see if it works.

Thanks...

**Comment by joperezr** [comment]
Ok, thanks for confirming. In that case I'll go ahead and close this issue for now. Feel free to reopen if you can repro again or have any follow up questions.
