### ISSUE TITLE
EventWaitHandle can be named, but has no Name property

### ISSUE THREAD

**Issue by erikness** [dotnet/runtime#43997]
[AB#1244360](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1244360)
## Background and Motivation

SafeWaitHandle and EventWaitHandle take a name in their constructors, which they pass on to the CreateEventW Windows call. The name is an identifier used by other processes to grab the same handle, so that the two processes can synchronize. But neither SafeWaitHandle or EventWaitHandle stores the name anywhere, and it makes using this API awkward. If a developer wants to keep track of which name corresponds to which EventWaitHandle object, they have to do it themselves, with a dictionary or a container class or something like that.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```diff
namespace System.Threading
{
    public partial class EventWaitHandle
    {
+       public string? Name { get; set; }
    }
}
```

## Usage Examples

Example: wait on multiple handles and you want to see which one was set.
``` C#
EventWaitHandle chorusCompleted =  new EventWaitHandle(false, EventResetMode.ManualReset, @"Global\ChorusCompleted");
EventWaitHandle verseCompleted =  new EventWaitHandle(false, EventResetMode.ManualReset, @"Global\VerseCompleted");
EventWaitHandle bridgeCompleted =  new EventWaitHandle(false, EventResetMode.ManualReset, @"Global\BridgeCompleted");

WaitHandle[] newHandles = new WaitHandle[] { chorusCompleted, verseCompleted, bridgeCompleted };
int triggeredHandleIndex = WaitHandle.WaitAny(newHandles);
WaitHandle triggeredHandle = newHandles[triggeredHandleIndex];

// I would like to be able to get the name so I can log it
MyEventLogging.HandleTriggered(triggeredHandle.Name);

// I want to map handle names to callbacks; I can also map the WaitHandles themselves to callbacks,
// but a string -> callback dictionary is much easier to look at than a WaitHandle -> callback dictionary in a debugger.
CompletionHandlers[triggeredHandle.Name].Invoke();
```

Generally, a Name property would be useful if you want to pass an EventWaitHandle around to many parts of a program, so you don't have to pass around any additional metadata to tie it to the name.

I should note a couple details:
- This may apply to other, similar synchronization classes as well; I'm not familiar enough with them to say for sure
- [The unix implementation](https://github.com/dotnet/runtime/blob/23695a362569af6a4176547b375a01dff08758b3/src/mono/netcore/System.Private.CoreLib/src/System/Threading/EventWaitHandle.Unix.Mono.cs#L44) does not support named handles so this property would have to be Windows-only.
- According to the [CreateEventExW docs](), "If lpName is NULL, the event object is created without a name.". So this property could be also null if you create a new event without a name.

## Alternative Designs

It doesn't seem like there are any Windows functions which allow you to get the name of a handle that you already have. It would be convenient if there were, so we could save a few bytes.

## Risks

What if the handle is invalid? Is it safe to say that the handle object in .NET has a name at all? For example, suppose I invalidate my handle named "Foo", Windows gets rid of it, and a little while later another process creates a new handle, also named "Foo". My SafeHandle object would still have Name == "Foo", but it doesn't actually refer to the handle currently known as "Foo" any longer.

**Comment by jkotas** [comment]
> This may apply to other, similar synchronization classes as well; 

Correct, this applies to most Windows OS objects backed by `HANDLE`.

> It doesn't seem like there are any Windows functions which allow you to get the name of a handle that you already have

`NtQueryObject` is a Windows function that does this. Example: https://gist.github.com/jkotas/12b84a49fe3ab9eecd9cf91cc346bdb3 . Note that this will print the absolute path to handle -  `Global` is replaced with the absolute path.

**Comment by jkotas** [comment]
> `WaitHandle triggeredHandle = WaitHandle.WaitAny(chorusCompleted, verseCompleted, bridgeCompleted);`

This does not compile. WaitAny returns the index of the handle that triggered.

**Comment by stephentoub** [comment]
> The unix implementation does not support named handles so this property would have to be Windows-only

It'd return null just as on Windows when no name is used.

**Comment by erikness** [comment]
> This does not compile. WaitAny returns the index of the handle that triggered.

Woops, you're right, I was too hasty in writing that. Plus WaitAny() actually takes an array, not `params`. I'll correct this:

```WaitHandle triggeredHandle = WaitHandle.WaitAny(chorusCompleted, verseCompleted, bridgeCompleted);```

To this:

```
WaitHandle[] newHandles = new WaitHandle[] { chorusCompleted, verseCompleted, bridgeCompleted };
int triggeredHandleIndex = WaitHandle.WaitAny(newHandles);
WaitHandle triggeredHandle = newHandles[triggeredHandleIndex];
```

> Note that this will print the absolute path to handle - Global is replaced with the absolute path.

For me, it will also prepend "\BasedNamedObjects", i.e. "\BaseNamedObjects\ChorusCompleted". Additionally, if you prepend "Local", i.e. "Local\ChorusCompleted", the absolute path would have the "Local" removed and your Windows session ID is added, like so: `\Sessions\1\BaseNamedObjects\ChorusCompleted` (if I create a handle without a namespace, it's also treated as local).

When I worked with EventWaitHandles recently, the namespace translation confused me for a bit - [the current API docs don't mention global and local namespaces](https://docs.microsoft.com/en-us/dotnet/standard/threading/eventwaithandle). Two programs were supposed to be opening the same handle, but weren't. It turns out one was accessing it via the local namespace because I was running it from an RDP session, and the other program was a service of some kind (no Windows session associated with it) so it used the global namespace by default. I have two thoughts as a result of this:

- I was able to figure it out by looking at the events in Resource Monitor ("Associated Handles" section). The method you wrote, Jan, would allow debug this programmatically, or in a debugger.
- A "Name" property for a method that calls `NtQueryObject` seems like the wrong fit; something like GetHandleName, or TryGetHandleName, or GetHandleAbsolutePath, would be better. The API should at least hint that there's a translation going on here, and that this value isn't exactly what you passed into the constructor.

While there still wouldn't be a way to get back the exact "name" string you put in, there are deterministic rules around the translation, so it could be a good compromise if you're worried about adding 8 bytes to these small objects. Or, if you decide to add name, I think this method would be useful in addition to that - it's useful to see what Windows is doing with it behind the scenes!

**Comment by mangod9** [comment]
This ask is broader for mostly all `WaitHandle` and `SafeWaitHandle` , would probably need review from interop folks.

**Comment by jkotas** [comment]
FWIW, this is nothing to do with interop.

It would be a relatively boring API that gets/sets a field on `WaitHandle`. The API does not make sense for `SafeWaitHandle`.

**Comment by mangod9** [comment]
hmm ok. Moving to .net 6.

**Comment by kouvel** [comment]
I figure if the `Handle` or `SafeWaitHandle` is changed, the `Name` property could return null thereafter.

**Comment by kouvel** [comment]
The `Name` property should probably be on `WaitHandle` instead of `EventWaitHandle`

**Comment by kouvel** [comment]
Also don't think there should be a setter. Updated proposal:

```c#
namespace System.Threading
{
    public partial class WaitHandle
    {
        public string? Name { get; }
    }
}
```

**Comment by erikness** [comment]
I agree with all of these.

**Comment by terrajobst** [comment]
* Looks good as proposed
    - But do we need a protected constructor that takes the name, will we use an internal setter, or should we make the property virtual? Any of these are fine with us.

```C#
namespace System.Threading
{
    public partial class WaitHandle
    {
        public string? Name { get; }
    }
}
```

**Comment by kouvel** [comment]
@terrajobst I was thinking of using just an internal mechanism for setting the name for now. If it's necessary to provide a way to set the name for non-internal derived types I figure it could be considered in the future.

**Comment by kouvel** [comment]
Having a public setter would allow the wait handles returned by variants like `MutexAcl.Create` called with security attributes also be able to provide the name. The `Acl` variants do some handle tweaking by creating an unnamed object first and changing the handle, which is not ideal, but as proposed for those objects the `Name` property would return null. Having a public setter as a result of that issue seems like it would be unfortunate, I'm leaning towards returning null for wait handles returned by `Acl` variants, but I could go either way. Thoughts?

**Comment by jkotas** [comment]
`WaitHandle.SafeHandle` has both getter and setter. One can argue that it is less than ideal design to allow WaitHandle to be mutable, but it is what it is. 

Having both getter and setter for name would follow the design.

**Comment by kouvel** [comment]
Agreed, will go with that then

**Comment by kouvel** [comment]
Updated proposal:

``` c#
namespace System.Threading
{
    public partial class WaitHandle
    {
        public string? Name { get; set; }
    }
}
```

**Comment by kouvel** [comment]
@terrajobst I have marked this as ready for review since this wasn't one of the things you mentioned that was considered ok. Could you please take another look?

**Comment by stephentoub** [comment]
I agree it's strange to have a public setter, but as mentioned, that precedent was already set with WaitHandle.SafeWaitHandle being settable.  So.. LGTM.

**Comment by terrajobst** [comment]
Agreed. I don't think we need to re-review this. Approved.

**Comment by danmoseley** [comment]
@kouvel, I'm going through partner asks still marked 6.0 and this is one. Do you expect to have time to get this in before the RC1 fork, or should it be up for grabs?

**Comment by kouvel** [comment]
In progress, I'll take care of it

**Comment by mangod9** [comment]
This is no longer a partner requirement. So unless there are other benefits we could deprioritize this.

**Comment by kouvel** [comment]
Let's move it to .NET 7 then, any objections?

**Comment by kouvel** [comment]
Also would it be appropriate to remove the partner ask label? It seems I cannot do that.

**Comment by terrajobst** [comment]
> Also would it be appropriate to remove the partner ask label? It seems I cannot do that.

You have write permissions to this repo; you should be able to.

**Comment by kouvel** [comment]
I still can't seem to figure out how to remove the project label, I don't see a check mark that I can uncheck like for other projects

**Comment by stephentoub** [comment]
I removed it.  For future reference, if you click on Projects, it'll take you to the project board, and then for the card for this issue, you can click the ... for the remove menu item:
![image](https://user-images.githubusercontent.com/2642209/126584212-45706108-5057-4429-b1b9-5ac301cbca78.png)

**Comment by kouvel** [comment]
Ah ok, I guess I haven't had to do that before, it's a rather roundabout way but I can see how to do it now. Thanks!

**Comment by danmoseley** [comment]
@kouvel should we mark this up for grabs?

**Comment by GSPP** [comment]
What happens when `SafeWaitHandle` is set? This could desynchronize the handle with the name. If the name is simply set to null, that would also be incorrect for a named object.

The name is not essential to the function of the event in any way. It's just an arbitrary string that is tacked onto this object.

My opinion is that this API should not be added. Users should track the name themselves.

**Comment by kouvel** [comment]
> My opinion is that this API should not be added. Users should track the name themselves.

I'm tending to agree, given that `SafeWaitHandle` can be changed, the type cannot guarantee that the `Name` will be in sync. Either both would have to be changed appropriately by the user, or the user can just as well track the name separately. Though changing the `SafeWaitHandle` seems awkward and probably rare except in code that's doing it properly, code that's currently doing it properly would not be proper anymore after `Name` is added (if it's a named object). The need to track the name seems a bit of a corner case, I'm not sure it's worth it.
