### ISSUE TITLE
Question: what's the plan with Windows 7?

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#440]
To be honest, consumers always ask developers to support old systems beyond official EOL. Would you drop Windows 7 _just_ because EOL? Or keep support of it until some significant feature lack?
MSVC has shipped another XP target long after XP EOL.

To be clear, will .NET 5 support Windows 7?

**Comment by scalablecory** [comment]
@terrajobst @richlander

**Comment by DaZombieKiller** [comment]
There might be precedent for dropping Windows 7 based on https://github.com/dotnet/runtime/issues/423, although I imagine the primary driver for that issue is the difficulty of maintenance as mentioned by @jkotas in a comment. Whether or not a similar case applies to Windows 7, who knows.

**Comment by richlander** [comment]
We are supporting Windows 7 for the lifetime of .NET Core 3.1. We haven't made a decision on .NET 5 yet, and are not actively discussing it. I suspect we'll until June/July (or later) to make that decision.

**Comment by danmosemsft** [comment]
The question here is answered: if there is an update in the summer we'll share it in the usual places. Closing.
