### ISSUE TITLE
System.Text.Json: Structs should serialize all public fields

### ISSUE THREAD

**Issue by jessicah** [dotnet/runtime#44009]
### Description

Structs should serialize all public fields by default.

### Configuration

.net core 5.0

### Other information

I haven't tried C# 9 record types, but I would assume the behaviour should be the same there too.

**Comment by Symbai** [comment]
And can you tell us WHY it should do that?

**Comment by Joe4evr** [comment]
Why have you opened a duplicate issue?

**Comment by GrabYourPitchforks** [comment]
Possible dupe of https://github.com/dotnet/runtime/issues/876.

**Comment by layomia** [comment]
Closing as dupe of https://github.com/dotnet/runtime/issues/44009 and #876.
