### ISSUE TITLE
RyuJIT unsafe code performance regressions (includes repro-code)

### ISSUE THREAD

**Issue by redknightlois** [dotnet/runtime#4400]
**TLDR: With the exception of a single scenario where calling native (which I am very glad it was optimized) for all the rest RyuJIT is slower (sometimes by a big margin).**

Since I discovered https://github.com/dotnet/coreclr/issues/1306 I have been testing some of the most performance sensitives operations we have. I tested 3 different optimized routines, unsafe optimized memory copy, unsafe memory compare and unsafe xxHash32 hashing algorithm. 

The code for all of those is available on github.
- Memory-Copy & Memory-Compare: https://github.com/ayende/ravendb/blob/master/Raven.Sparrow/Sparrow/Memory.cs
- xxHash32 algorithm: https://github.com/ayende/ravendb/blob/master/Raven.Sparrow/Sparrow/Hashing.cs

Sizes are the following:
- Huge: 16Mb per run
- Block: 4Kb per run
- Small: 64bytes per run
- Very Small: 16bytes per run
- Tiny: 6 bytes per run

See benchmark code for details: https://gist.github.com/redknightlois/f71700d2705a7f9fe312 
#### Hashing with xxHash32

// BenchmarkDotNet=v0.7.6.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, ProcessorCount=4
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit
Common:  Type=HashingBenchmark  Mode=Throughput  Platform=X64  .NET=Current

| Method | Jit | AvrTime | StdDev | op/s |
| --- | --- | --- | --- | --- |
| HashHuge | LegacyJit | 3.47 ms | 18.01 us | 288.12 |
| HashHuge | RyuJit | 4.00 ms | 16.09 us | 249.97 |
| HashBlock | LegacyJit | 110.30 ns | 1.85 ns | 9066050.21 |
| HashBlock | RyuJit | 128.70 ns | 0.709 ns | 7770162.29 |
| HashSmall | LegacyJit | 19.98 ns | 0.129 ns | 50038564.91 |
| HashSmall | RyuJit | 22.71 ns | 0.105 ns | 44037116.02 |
| HashVerySmall | LegacyJit | 10.27 ns | 0.0658 ns | 97396785.55 |
| HashVerySmall | RyuJit | 12.30 ns | 1.01 ns | 81326622.54 |
| HashTiny | LegacyJit | 5.78 ns | 0.128 ns | 173011900.05 |
| HashTiny | RyuJit | 8.68 ns | 0.0472 ns | 115268519.76 |

The difference in throughput for 16Mb buffers is 4.61 Gigabytes per second from the LegacyJit to 3.99 Gigabytes per sec with RyuJIT. (600 Mb per second difference which is not a minimal difference). 
#### Memory Compare

// BenchmarkDotNet=v0.7.6.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, ProcessorCount=4
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit
Common:  Type=MemoryCompareBenchmark  Mode=Throughput  Platform=X64  .NET=Current

| Method | Jit | AvrTime | StdDev | op/s |
| --- | --- | --- | --- | --- |
| CompareHuge | LegacyJit | 2.91 ms | 45.50 us | 343.48 |
| CompareHuge | RyuJit | 3.04 ms | 137.93 us | 328.72 |
| CompareBlock | LegacyJit | 326.74 ns | 0.851 ns | 3060564.93 |
| CompareBlock | RyuJit | 339.95 ns | 1.07 ns | 2941580.42 |
| CompareSmall | LegacyJit | 12.51 ns | 0.0534 ns | 79917385.04 |
| CompareSmall | RyuJit | 15.20 ns | 0.0826 ns | 65798760.77 |
| CompareVerySmall | LegacyJit | 5.38 ns | 0.0461 ns | 185792782.3 |
| CompareVerySmall | RyuJit | 6.24 ns | 0.0288 ns | 160192381.38 |
| CompareTiny | LegacyJit | 5.06 ns | 0.0507 ns | 197789356.92 |
| CompareTiny | RyuJit | 5.07 ns | 0.0453 ns | 197293614.74 |

Again in the case of memory compare the difference still exist, but it is not that big. 5.24Gb/sec for RyuJIT vs. 5.48Gb/sec for the LegacyJIT. 
#### Memory Copy

// BenchmarkDotNet=v0.7.6.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, ProcessorCount=4
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit
Common:  Type=MemoryCopyBenchmark  Mode=Throughput  Platform=X64  .NET=Current

| Method | Jit | AvrTime | StdDev | op/s |
| --- | --- | --- | --- | --- |
| CopyHuge | LegacyJit | 2.47 ms | 65.96 us | 404.97 |
| CopyHuge | RyuJit | 2.22 ms | 58.07 us | 449.92 |
| CopyBlock | LegacyJit | 37.60 ns | 0.371 ns | 26598625.77 |
| CopyBlock | RyuJit | 26.63 ns | 0.221 ns | 37548121.15 |
| CopySmall | LegacyJit | 9.04 ns | 1.04 ns | 110636584.56 |
| CopySmall | RyuJit | 10.39 ns | 0.0851 ns | 96216641.11 |
| CopyVerySmall | LegacyJit | 4.46 ns | 0.0206 ns | 224426710.4 |
| CopyVerySmall | RyuJit | 7.14 ns | 0.0328 ns | 140078221.54 |
| CopyTiny | LegacyJit | 4.45 ns | 0.0353 ns | 224550382.94 |
| CopyTiny | RyuJit | 7.72 ns | 0.0625 ns | 129580962.59 |

It appears that for very small RyuJit is worse (16 bytes), for middle size (64 bytes), and for big LegacyJIT is worse ( 4096+ bytes )

For buffers of size 16 MB the throughput is 7.18Gb/sec for RyuJIT to 6.4Gb/sec for the LegacyJIT; but we lost for the small buffers. This means that the marshaling of calls to unmanaged code has been greatly improved. (kudos on that)

category:cq
theme:loop-opt
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Given that the benchmark code appears to no longer be available, and there's nothing obviously actionable here, I'm going to go ahead and close this.
