### ISSUE TITLE
System.Text.Json custom converter doesn't work with Nullable value

### ISSUE THREAD

**Issue by jessicah** [dotnet/runtime#44006]
### Description

Registered a JSON custom converter for Nullable<int>. For instances with a non-null value, the converter gets invoked, but null values do not call the converter.

### Configuration

Using .net 5.0 rc2.

### Regression?

Did not work in .net core 3.1 with the 5.0-rc2 nuget package.

### Other information

```
public class JsonConverterNullableInt : JsonConverter<int?>
{
	public override int? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		return reader.GetInt32();
	}

	public override void Write(Utf8JsonWriter writer, int? value, JsonSerializerOptions options)
	{
		if (value == null)
		{
			writer.WriteStringValue(string.Empty);
		}
		else
		{
			writer.WriteNumberValue(value.Value);
		}
	}
}

public struct IndividualRecord
{
	[JsonInclude]
	public Category category;
	[JsonInclude]
	[JsonConverter(typeof(JsonConverterNullableInt))]
	public int? tid;
}
```

**Comment by layomia** [comment]
This is [not a regression](https://dotnetfiddle.net/SvFaIy) from 3.1. In .NET 5, we added a new feature for custom converter's to handle `null` - https://github.com/dotnet/runtime/issues/34439.

For reference and nullable value types, the serializer does not pass `null` to the read/write methods of custom converters. These converters need to opt-in by setting `JsonConverter<T>.HandleNull` to `true`. See https://github.com/dotnet/runtime/pull/40859#issue-468191956 for more information.

```cs
public class JsonConverterNullableInt : JsonConverter<int?>
{
    public override bool HandleNull => true;

    public override int? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return reader.GetInt32();
    }

    public override void Write(Utf8JsonWriter writer, int? value, JsonSerializerOptions options)
    {
        if (value == null)
        {
            writer.WriteStringValue(string.Empty);
        }
        else
        {
            writer.WriteNumberValue(value.Value);
        }
    }
}
```
