### ISSUE TITLE
"hostfxr_initialize_for_runtime_config" failed if already initialized in "muxer" host mode

### ISSUE THREAD

**Issue by xuhongxu96** [dotnet/runtime#44002]
### Description

I've built a native DLL using C++, which will run .NET Core host to load a .NET Core class library and run a static method, according to [Write a custom .NET Core host to control the .NET runtime from your native code](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting).

I also wrote extern C API for the DLL, which will be called by .NET Core program thru P-Invoke.

In summary, my final program is a .NET Core program, and it will load a native DLL written in C++ and call an API of it. The API will then start a .NET Core host which will load and run another .NET Core library.

The call chain looks like: `.NET Core -- (P-Invoke) --> Native -- (hostfxr) --> Another .NET Core`

It works fine if run by `xxx.exe`.
However, `hostfxr_initialize_for_runtime_config` will fail if I run my final .NET Core program by `dotnet run` or `dotnet ***.dll`.

### Configuration

* Which version of .NET is the code running on? Both `3.1.9` and `5.0.0-rc.2.20475.5`
* What OS and version, and what distro if applicable? Both `Windows 10` and `WSL (Ubuntu 1804)`
* What is the architecture (x64, x86, ARM, ARM64)? `x64`
* Do you know whether it is specific to that configuration? `No, it should be an issue in many environments`

### Regression?

I don't know.

### Other information

I've debugged a lot. I will give some of my insights here.

#### Potential Cause Analysis

When .NET Core program is run by `dotnet run` or `dotnet ***.dll`, the `host_mode` of `hostpolicy_init_t g_init` will be `muxer`.
When it is run by directly calling `***.exe`, `host_mode` will be `apphost`.

When .NET Core program P-Invokes the native DLL and the native DLL starts initializing the hostfxr, the program fails here:

https://github.com/dotnet/runtime/blob/aca727ac79f147eed4d3fae289583f7446f9ad35/src/installer/corehost/cli/hostpolicy/hostpolicy.cpp#L710-L713

If I step into it, we will see the failure eventually comes here:

https://github.com/dotnet/runtime/blob/9d2faae83bf85598e309f82d074547453aadc9b2/src/installer/corehost/cli/hostpolicy/args.cpp#L58-L103

Because `host_mode == muxer` and `argc == 0 < 2`, `parse_arguments` will `return false`.

I also found that, even though the program works fine if run by calling `***.exe`, there exists a potential invalid memory access here. Because `host_mode == apphost` and `argc == 0`, the following code will access an invalid memory and make `argc` invalid as well:

https://github.com/dotnet/runtime/blob/9d2faae83bf85598e309f82d074547453aadc9b2/src/installer/corehost/cli/hostpolicy/args.cpp#L69-L70

BTW, if run by dotnet, the `init.host_info.app_path` will be `C:\Program Files\dotnet\dotnet.dll`, which is a non-existent path. I'm not sure if this is by design or not.

#### Possible Solution

Actually, the above code which caused the issue has no use if the host is already initialized. It only parses the arguments.  
The parsed arguments will be assigned to `args` here:

https://github.com/dotnet/runtime/blob/aca727ac79f147eed4d3fae289583f7446f9ad35/src/installer/corehost/cli/hostpolicy/hostpolicy.cpp#L711

But the `args` won't be used if `wait_for_initialized == true` or `get_contract == true`. And in our case, `wait_for_initialized == true`.

https://github.com/dotnet/runtime/blob/aca727ac79f147eed4d3fae289583f7446f9ad35/src/installer/corehost/cli/hostpolicy/hostpolicy.cpp#L710-L761

So, can we move `corehost_libhost_init` into `else` branch to resolve the issue?

**Comment by jkoritzinsky** [comment]
This might be fixed by https://github.com/dotnet/runtime/pull/43962

**Comment by xuhongxu96** [comment]
> This might be fixed by #43962

Looks great, thanks for pointing out!

BTW, if run by dotnet, the `init.host_info.app_path` will be `C:\Program Files\dotnet\dotnet.dll`, which is a non-existent path. I'm not sure if this is by design or not.

**Comment by vitek-karas** [comment]
> BTW, if run by dotnet, the init.host_info.app_path will be C:\Program Files\dotnet\dotnet.dll, which is a non-existent path. I'm not sure if this is by design or not. Shall I open another issue for this?

Unfortunate fact is that the code in `hostfxr` actually relies on the path not-existing to detect that we're running in the "muxer" mode: https://github.com/dotnet/runtime/blob/master/src/installer/corehost/cli/fxr/fx_muxer.cpp#L332

It would definitely be cleaner if `dotnet.exe` passed empty app path (as it doesn't know yet). The code should keep on working as is.

Unfortunately this is something we're VERY unlikely to change. `dotnet.exe` is a very sensitive component because it can't be SxS, there's basically one version of it on any machine and it's used for running ALL .NET Core versions installed on the machine. The risk associated with this change (it would change how `dotnet.exe` and `hostfxr.dll` interacts) is not worth the reward. In this case (unfortunately) the "if it works, don't touch it" wins in my mind.

**Comment by xuhongxu96** [comment]
Thanks for explanation! 
I just be curious about the fact while debugging the code. I agree with the idea "if it works, don't touch it".😀 
Before closing the issue, I wonder if the fix will only merge into .NET 6.0? (I see the PR-related issue is in Project .NET 6.0)

**Comment by vitek-karas** [comment]
The fix will be in 6.0 only. 5.0 RTM is done and so far the issue doesn't seem important enough to include as a servicing fix for 5.0.1. But if that changes we could backport it if necessary.

**Comment by xuhongxu96** [comment]
That's sad... I've thought this kind of usage should be a major requirement.
Anyway, thanks for info! We'll adjust our plan and I'll close the issue then.

**Comment by vitek-karas** [comment]
We need prioritize on something, and so far this issue is the only external report of the problem (we also found it internally). Servicing fixes typically require certain level of importance - to counterweight the potential risk of introducing a break in a servicing release.

I'm perfectly OK trying to take it through the servicing approval process, but as-is my personal take is that it is unlikely it will be approved.
