### ISSUE TITLE
NTLM authentication HttpClient in Core 3.1  returns a 401

### ISSUE THREAD

**Issue by tokotech** [dotnet/runtime#44018]
I'm trying to use HttpClient to call rest api that requires NTLM authentication.
Below code works fine in .net 4.6 but keep getting 401 with .net core 3.1

            static void Main(string[] args)
            {
                 var handler = new HttpClientHandler { AllowAutoRedirect = true, MaxAutomaticRedirections = 1, UseDefaultCredentials = true };
            var httpClient = new HttpClient(handler);
           
            var parameters = new Dictionary<string, string>
            {.... };

            var uriParameters = new FormUrlEncodedContent(parameters);
            var response = await httpClient.GetAsync($"myUrl?{uriParameters.ReadAsStringAsync().Result}");
         
    }
}
This is running in windows 10.

**Comment by hez2010** [comment]
You need to specify HTTP/1.1 and make your connection Keep-Alive.

**Comment by tokotech** [comment]
Added to my code:  

httpClient.DefaultRequestHeaders.Add("Connection", "Keep-Alive");
 
Still getting 401
 
See output from fiddler
 
Core:
 
http 200 -         CONNECT site.domain.net:443 HTTP/1.1
                                                                                       Host: site.domain.net:443
                                                                                      
 
https 302 -       GET https://site.domain.net/data HTTP/1.1
                                                                                       Host: site.domain.net
                                                                                       Connection: Keep-Alive
                                                                                      
HTTP/1.1 401
 
------------------------------------------------------------
 
FW 4.6
http 200 -         CONNECT site.domain.net:443 HTTP/1.1
                                                                                       Host: site.domain.net
                                                                                       Connection: Keep-Alive
 
https 302 - GET https://site.domain.net/data HTTP/1.1
                                                                                       Host: site.domain.net
                                                                                       Connection: Keep-Alive

**Comment by wfurt** [comment]
from the trace: is there proxy involved since you see CONNECT? Neither of the examples show any NTLM exchange.

**Comment by tokotech** [comment]
Yes there is a proxy, and I have tried with   UseProxy = true,  still 401
also tried  AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

**Comment by wfurt** [comment]
Is there possibility to try it without proxy @tokotech? I'm wondering if that has impact somehow. We can try to reproduce but posted notes may not be sufficient.

**Comment by tokotech** [comment]
sorry no, no proxy is not an option.

**Comment by tokotech** [comment]
I tried other server with NTLM and it worked from Core also, so i guess that is it something with the headers the Core dos different....

**Comment by tokotech** [comment]
Line 1-3 is from Core
Line 17-21 if from 4.7

the both get a 401, but 4.7 resumes with a new 302 this time with a Kerberos ticket, where core just gives up...
how to get core to resume with a Kerberos ticket ??

from fiddler. line 21 = Authorization: Negotiate , Authorization Header (Negotiate) appears to contain a Kerberos ticket:

-
![snip_20201103111903](https://user-images.githubusercontent.com/6986751/97974387-c7a35680-1dc7-11eb-8e70-8c386eadd0e6.png)

**Comment by tokotech** [comment]
ok setting  AllowAutoRedirect = false , and loop over the response seems to work , but why the change in Core ?

**Comment by wfurt** [comment]
Is this NTLM or Kerberos? You confused me with the last comment @tokotech 
There is not enough details here to triage root cause.

**Comment by tokotech** [comment]
I can see why , sorry, is Kerberos. 
But the question is, i guess, why dos Core 3.1 not follows the redirect (302) the same way the FW 4.7 dos even though
AllowAutoRedirect = true ..?

**Comment by wfurt** [comment]
Kerberos is whole different animal and depends on how you have your DNS set up and how SPNs are defined. 
I don't think we will be able to find the answered unless you provide all the details and perhaps packet captures. 
You can check existing kerberos and SPN issues to see if anything looks similar.

**Comment by tokotech** [comment]
ok I give up.

**Comment by wfurt** [comment]
ok. It seems like you have same way forward. Feel free to re-open and share more details in the future.
