### ISSUE TITLE
Test failure: System.Tests.AppDomainTests.MonitoringIsEnabled

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44012]
failed in job: [runtime 20201028.64 ](https://dev.azure.com/dnceng/public/_build/results?buildId=869651&view=ms.vss-test-web.build-test-results-tab&runId=27826580&resultId=147986&paneView=debug)

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open

Error message
~~~
Assert.InRange() Failure
Range:  (00:00:04.5787167 - 10675199.02:48:05.4775807)
Actual: 00:00:04.5787080


Stack trace
   at System.Tests.AppDomainTests.MonitoringIsEnabled() in /_/src/libraries/System.Runtime.Extensions/tests/System/AppDomainTests.cs:line 395
~~~

**Comment by wfurt** [comment]
looks like dup of #44074, fixed by  #44228
