### ISSUE TITLE
Start Process on remote machine 

### ISSUE THREAD

**Issue by JanEggers** [dotnet/runtime#44017]
## Background and Motivation

there are some workarounds to launch a Process on a remote machine like:

psexec
https://stackoverflow.com/questions/25782308/execute-exe-on-remote-machine 
con: requires external binaries
wmi
https://stackoverflow.com/questions/428276/how-to-execute-a-command-in-a-remote-computer
con: just works on windows
ssh
https://github.com/sshnet/SSH.NET
con: just works with ssh

but there is no buildin way to do it. and certainly no way that is cross platform.

I suppose the user has to tell dotnet how to start the process by providing the remote platform. if this can be avoided with some black magic the new api can be reduced to just providing the machine name.

## Proposed API

```diff
namespace System.Diagnostics
{
public class ProcessStartInfo {
+    public string MachineName { get; set; } = Environment.MachineName;
+    public System.Runtime.InteropServices.OSPlatform? Platform { get; set; } 
}
```

## Usage Examples

``` C#
Process.Start(new ProcessStartInfo() {
    FileName = "ping",
    Arguments = "8.8.8.8",
    MachineName = "someothermachine"
    Platform = OSPlatform.Windows 
}); 
```

## Risks

additional complexity in the implementation in case MachineName != Environment.MachineName and Platform  != RuntimeInformation.CurrentOSPlatform

**Comment by eiriktsarpalis** [comment]
SSH typically requires some form of authentication, either password or public key. How might we provide an API that abstracts away those details?

**Comment by JanEggers** [comment]
the processstartinfo already contains username and password I was not aware that this is not sufficient?!

**Comment by eiriktsarpalis** [comment]
I suppose my point is that these are all very different protocols, each configurable in different ways. I do not think we could ever accept a proposal that infers which one should be used with some "black magic", particularly when it comes to the `Process` class.

**Comment by JanEggers** [comment]
> I suppose my point is that these are all very different protocols, each configurable in different ways. I do not think we could ever accept a proposal that infers which one should be used with some "black magic", particularly when it comes to the Process class.

I totally agree. I was just hoping for a more inside the box solution for the problem. but it seems I have to rely on the workarounds / packages mentioned above.
