### ISSUE TITLE
Windows x86 JIT build not minimal

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#44039]
If I create a build (on Windows) using:
```
build clr.runtime+clr.corelib+clr.nativecorelib+libs -arch x86 -c Release
build clr.runtime+clr.corelib+clr.nativecorelib -arch x86 -c Checked -lc Release
```

then "incremental" build using:
```
build clr.jit -arch x86 -c Checked
```

I see:
```
gcinfo_unix_arm.vcxproj -> C:\gh\runtime3\artifacts\obj\coreclr\Windows_NT.x86.Checked\src\gcinfo\Checked\gcinfo_unix_arm.lib
...
clrjit_unix_armel_x86.vcxproj -> C:\gh\runtime3\artifacts\obj\coreclr\Windows_NT.x86.Checked\src\jit\Checked\clrjit_unix_armel_x86.dll
```

Shouldn't these only be built if the `clr.alljits` subset is built?

(This also happens if I use:
```
src\coreclr\build-runtime.cmd x86 checked -skipgenerateversion -skipconfigure -skipcrossarchnative -nopgooptimize -skiprestoreoptdata -skipruntime -skipalljits
```
)

@davidwrighton Is this expected?

On x64, `build clr.jit` only builds one jit: clrjit.dll.

**Comment by davidwrighton** [comment]
Eh, arguably, the clr.jit build could be a bit more minimal. When I implemented it, I targeted getting easy results, not a full swath. The armel build is particularly egregious, as nobody is going to use that on Windows.

**Comment by karelz** [comment]
@davidwrighton @BruceForstall should we move it to 5.0 servicing milestone (5.0.x) or to 6.0/Future?

**Comment by BruceForstall** [comment]
Set to 6.0

**Comment by BruceForstall** [comment]
Pushing this to 7.0.

**Comment by davidwrighton** [comment]
I don't expect to ever fix this. The build is delicate enough as it is, and while the clr.jit build isn't minimal, its generally small enough to build very quickly. @BruceForstall if you have strong opinions here, I would review a fix, but I don't ever see myself as having the time to actually change this for the better.

**Comment by BruceForstall** [comment]
Well, I'm never going to spend time on this, so I'll close the issue.
