### ISSUE TITLE
Test failure: Microsoft.Extensions.FileProviders.Physical.Tests.PhysicalFilesWatcherTests.HandlesOnRenamedEventsThatMatchRootPath

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44057]
failed in job: [runtime-coreclr libraries-jitstress 20201029.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=869879&view=ms.vss-test-web.build-test-results-tab&runId=27834662&resultId=102114&paneView=debug)

net6.0-Windows_NT-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

Error message
~~~
Callback should have been triggered
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.FileProviders.Physical.Tests.PhysicalFilesWatcherTests.HandlesOnRenamedEventsThatMatchRootPath() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFilesWatcherTests.cs:line 56
--- End of stack trace from previous location ---
~~~

**Comment by carlossanlop** [comment]
Triage:
Kusto returned no hits for this test method in the last 60 days.
