### ISSUE TITLE
Update Assembly Versions to 6.0.0.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#44078]
- [x] Update assemblyVersions to 6.0.0.0
- [x] Package index needs to be updated for assemblies which are added in the timeframe between the 6.0 snap and this change.
- [ ] Reenable the validation after a round trip change

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
Can you please explain the required workarounds that you mentioned if we don't update to a newer SDK?

**Comment by Anipik** [comment]
> Can you please explain the required workarounds that you mentioned offline in case we don't update to a 6.0 SDK?

i added few here that we already face https://github.com/dotnet/runtime/issues/44079
i will keep on adding more.
