### ISSUE TITLE
Update Brotli source to 1.0.9

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44073]
The current Brotli source in this repo is 1.0.7.  1.0.9 has been released:
https://github.com/google/brotli/releases/tag/v1.0.9

We need to bring the code in this repo up to date.

cc: @jeffhandley, @carlossanlop, @ericstj, @saucecontrol

**Comment by saucecontrol** [comment]
I've been meaning to do this.  I'll see if I can get a PR up this weekend.

**Comment by stephentoub** [comment]
Thanks!
