### ISSUE TITLE
WorkArounds involved during a major Version Update

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#44079]
This issue is tracking all the workarounds that we do in order to move to a new .NET version. The goal here is either to resolve these or to make them minimum.

The major tasks involved our introducing a new target framework and updating the assembly versions

- [x] Adding  knownFrameworkReference & KnownAppHostPack for net6.0. This needs to be done for the libraries project and the projects that we create to test the assemblies like linker project, installer test projects, package validation projects. These should be remove after we update the sdk with the new tfm in the repo.
- [x] Incrementing  NETCoreAppMaximumVersion  for all the csprojs. This workitem is no longer needs to be done because we set it to 99.0 now
- [x] Projects having dependencies on aspnetcorerefpack needs to build against  previous targetFramework because we dont produce it locally. These projects would need to move to latest .net after the sdk change.
- [x] Similarly, coreclr  toolset dependencies will need to be updated after the latest sdk change.
- [x] apicompat change
- [x] we need to manually make sure that packages do not contain any extra tfms after this change. We should add some validation there so that we dont miss something here.
- [x] diasble validation after the assembly verison change.
- [x] Update the test data in system.resources.extensions project
- [x] Update the package index.json to show the new assembly versions and make sure the versioning is correct for any item added between the release snap and current

I will add more after making the assembly version change.
PRs making these changes https://github.com/dotnet/runtime/pull/42709

cc @ericstj @ViktorHofer @safern

**Comment by safern** [comment]
Just to add it here as it might be relevant. This issue: https://github.com/dotnet/runtime/issues/43137 also causes trouble when updating versions as we need a new SDK with the new major version every time for that to not be broken.

**Comment by ViktorHofer** [comment]
> Just to add it here as it might be relevant. This issue: #43137 also causes trouble when updating versions as we need a new SDK with the new major version every time for that to not be broken.

Thanks to yourself this is now resolved and hopefully won't pop-up again in a future major version iteration.

**Comment by ViktorHofer** [comment]
@Anipik which are the required workarounds to bump the assembly versions without updating the SDK?

**Comment by Anipik** [comment]
> @Anipik which are the required workarounds to bump the assembly versions without updating the SDK?

it seems like adding the new tfm resolved those errors. I am not seeing any, but the https://github.com/dotnet/runtime/pull/44373 will let us know we require any specific workarounds.

**Comment by ViktorHofer** [comment]
Closing as all of these items are done for 6.0. For 7.0 we should try to minimize the required change where possible.
