### ISSUE TITLE
[question] Reporting phase of the moon bugs

### ISSUE THREAD

**Issue by jzabroski** [dotnet/runtime#44083]
I have a bug with `DynamicObject` that is only triggered ever so often and requires a very large object models to reproduce.  I have built a rather minimal repro, but the repro itself only triggers ever so often.  Once it happens, DynamicObject(s) are unusable.

So far, I am only able to reproduce it on .NET Framework (see below for registry values), and I have no way to know if it still occurs in .NET Core other than to re-run the repro many times in a `do { & "My.exe" } while ($LASTEXITCODE -eq 0)` powershell loop.

What's the best way to report these?  Is there some way I can capture the state on my side?
Also, given Microsoft Connect no longer exists, and I see some StackOverflow posts referencing bugs with the DLR (but no description as to what the bug is about), is there any way I can search this repository efficiently for bugs related to DynamicObject?

CC @AaronRobinsonMSFT 

```powershell
[prodweb1]: PS C:\Users\john.zabroski\Documents> get-item "HKLM:\\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4


Name                           Property
----                           --------
Full                           CBS           : 1
                               Install       : 1
                               InstallPath   : C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
                               Release       : 528049
                               Servicing     : 0
                               TargetVersion : 4.0.0
                               Version       : 4.8.03761
```

**Comment by jzabroski** [comment]
As an update, it appears that if I run my repro test using VSTest.Console.exe, I consistently reproduce the bug every single time (10 out of 10 times).  For some reason, if I run the same phase of the moon code through Visual Studio and run the test via the GUI, it does not consistently fail.

As next steps, I will try to repro on .NET Core.

**Comment by cston** [comment]
@jzabroski 

> Once it happens, DynamicObject(s) are unusable.

What is the behavior you're seeing?

> is there any way I can search this repository efficiently for bugs related to DynamicObject?

This [query](https://github.com/dotnet/runtime/issues?q=is%3Aissue+label%3Aarea-System.Dynamic.Runtime+is%3Aopen) includes all issues for area-System.Dynamic.Runtime.

**Comment by jzabroski** [comment]
@cston 
> What is the behavior you're seeing?

Hi Charles, 

Calls to anything that interact with DynamicObject(s) fail.  Calling GetType() on a DynamicObject derived instance fails as well with an error message that indicates the dynamic object is corrupt.

I will invite you to a private GitHub repo I created so you can see for yourself.

**Comment by cston** [comment]
Thanks @jzabroski. I'm able to repro the issue with .NET Framework 4.7.2, but not with .NET Core 3.1 or .NET 5.0. I'll investigate if there is an obvious difference between the .NET Framework and .NET 5.0 implementations.

**Comment by jzabroski** [comment]
@cston Did you ever find any obvious difference between the two implementations?  My hunch is for pre-.NET 5.0 (.NET Core) to .NET Framework the code would probably be vastly different due to the fact the .NET Core didn't support COM and other bindings.

I never got around to trying to repro on .NET 5.0 but I still plan to try (e.g., increasing the object graph even further on .NET 5.0 to see if it's not reproing due to a change in memory allocation).

**Comment by cston** [comment]
@jzabroski, sorry for not following up on this yet. I'll take a look in the next few days.

**Comment by cston** [comment]
@jzabroski, I have not found the source of the dynamic binding failure in .NET Framework. There are some differences in the implementations between .NET Framework and .NET Core, and I haven't hit a similar failure in .NET Core, not even going back to .NET Core 2.0.

**Comment by cston** [comment]
Closing since it appears this issue is specific to .NET Framework only. Thanks @jzabroski.

**Comment by jzabroski** [comment]
@cston Understood.  Glad that code was rewritten.
