### ISSUE TITLE
Generic Host settings documentation inconsistency

### ISSUE THREAD

**Issue by galakt** [dotnet/runtime#44101]
Related to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#shutdowntimeout
```
By default, environment variables used to configure these settings can have a DOTNET_ or ASPNETCORE_ prefix.
```
But GenericHost provided by `Host.CreateDefaultBuilder().Build()` does not respect `ASPNETCORE_` prefixed envs, e.g.
* ApplicationName
* ContentRoot
* EnvironmentName
* ShutdownTimeout

Afaik, because of HostBuilder has only
`config.AddEnvironmentVariables(prefix: "DOTNET_");`

**Comment by maryamariyan** [comment]
Transferring to the aspnet doc repo.

cc @Rick-Anderson @IEvangelist
